Compute Library: NEReductionOperation Class Reference
NEReductionOperation Class Reference
Basic function to simulate a reduction operation.
#include <NEReductionOperation.h>
Public Member Functions
NEReductionOperation (std::shared_ptr< IMemoryManager > memory_manager=nullptr)
Default constructor.
void configure (ITensor *input, ITensor *output, unsigned int axis, ReductionOperation op, bool keep_dims=true)
Set the input and output tensors.
void run () override
Run the kernels contained in the function.
Public Member Functions inherited from IFunction
virtual ~IFunction ()=default
Destructor.
virtual void prepare ()
Prepare the function for executing.
Static Public Member Functions
static Status validate (const ITensorInfo *input, const ITensorInfo *output, unsigned int axis, ReductionOperation op, bool keep_dims=true)
Static function to check if given info will lead to a valid configuration of NEReductionOperation.
Detailed Description
Basic function to simulate a reduction operation.
This function calls the following NEON kernels:
NEFillBorderKernel
NEReductionOperationKernel
Definition at line 45 of file NEReductionOperation.h.
Constructor & Destructor Documentation
NEReductionOperation()
NEReductionOperation (std::shared_ptr< IMemoryManager > memory_manager = nullptr)
Default constructor.
Definition at line 56 of file NEReductionOperation.cpp.
     : _memory_group(memory_manager), _reduction_kernel(), _fill_border_kernel(), _reshape_kernel(), _output_internal(), _window_split(0), _reduction_axis(), _is_reshape_required(false)
 {
 }
Member Function Documentation
configure()
void configure (ITensor * input, ITensor * output, unsigned int axis, ReductionOperation op, bool keep_dims = true)
Set the input and output tensors.
Parameters
[in] input Source tensor. Data type supported: QASYMM8/F16/F32. Data layouts supported: NCHW. (Written to only for border_size != 0)
[out] output Destination tensor. Data types and data layouts supported: same as input.
[in] axis Dimension along which to reduce. Supported reduction axis : 0
[in] op Reduction operation to perform.
[in] keep_dims (Optional) Whether to keep the reduced dimension after the operation. Defaults to true.
Definition at line 100 of file NEReductionOperation.cpp.
 {
     ARM_COMPUTE_ERROR_ON_NULLPTR(input, output);
     _is_reshape_required = !keep_dims;
     auto      *output_internal = output;
     const auto is_arg_min_max  = (op == ReductionOperation::ARG_IDX_MAX) || (op == ReductionOperation::ARG_IDX_MIN);
     if(_is_reshape_required)
     {
         const auto output_internal_shape = arm_compute::misc::shape_calculator::compute_reduced_shape(input->info()->tensor_shape(), axis);
         const auto output_external_shape = arm_compute::misc::shape_calculator::compute_reduced_shape(input->info()->tensor_shape(), axis, false);
         const auto output_data_type      = is_arg_min_max ? DataType::S32 : input->info()->data_type();
         const auto num_channels          = input->info()->num_channels();
         const auto qinfo                 = input->info()->quantization_info();
         _output_internal.allocator()->init(input->info()->clone()->set_data_type(output_data_type).set_tensor_shape(output_internal_shape).reset_padding().set_is_resizable(true).set_num_channels(
                                                num_channels).set_quantization_info(qinfo));
         _memory_group.manage(&_output_internal);
         output_internal = &_output_internal;
         auto_init_if_empty(*output->info(), input->info()->clone()->set_data_type(output_data_type).set_tensor_shape(output_external_shape).reset_padding().set_is_resizable(true));
     }
     ARM_COMPUTE_ERROR_THROW_ON(NEReductionOperation::validate(input->info(), output->info(), axis, op, keep_dims));
     // Configure reduction kernel
     _reduction_kernel.configure(input, output_internal, axis, op);
     _window_split   = reduction_window_split_dimension(axis);
     _reduction_axis = axis;
     if(axis == 0)
     {
         // Configure fill border kernel
         const BorderSize fill_border_size = _reduction_kernel.border_size();
         PixelValue       pixelValue;
         switch(op)
         {
             case ReductionOperation::PROD:
             {
                 pixelValue = PixelValue(1, input->info()->data_type(), input->info()->quantization_info());
                 break;
             }
             case ReductionOperation::MIN:
             {
                 switch(input->info()->data_type())
                 {
                     case DataType::F32:
                     {
                         pixelValue = PixelValue(std::numeric_limits<float>::max());
                         break;
                     }
                     case DataType::F16:
                     {
                         pixelValue = PixelValue(static_cast<half>(65504.0f));
                         break;
                     }
                     case DataType::QASYMM8:
                     {
                         pixelValue = std::get<1>(get_min_max(input->info()->data_type()));
                         break;
                     }
                     default:
                     {
                         ARM_COMPUTE_ERROR("Unsupported DataType");
                     }
                 }
                 break;
             }
             case ReductionOperation::MAX:
             {
                 switch(input->info()->data_type())
                 {
                     case DataType::F32:
                     {
                         pixelValue = PixelValue(-std::numeric_limits<float>::max());
                         break;
                     }
                     case DataType::F16:
                     {
                         pixelValue = PixelValue(static_cast<half>(-65504.0f));
                         break;
                     }
                     case DataType::QASYMM8:
                     {
                         pixelValue = std::get<0>(get_min_max(input->info()->data_type()));
                         break;
                     }
                     default:
                     {
                         ARM_COMPUTE_ERROR("Unsupported DataType");
                     }
                 }
                 break;
             }
             case ReductionOperation::ARG_IDX_MAX:
             case ReductionOperation::ARG_IDX_MIN:
             {
                 pixelValue = PixelValue(0, input->info()->data_type(), input->info()->quantization_info());
                 break;
             }
             case ReductionOperation::MEAN_SUM:
             case ReductionOperation::SUM_SQUARE:
             case ReductionOperation::SUM:
             {
                 pixelValue = PixelValue(static_cast<uint32_t>(0));
                 break;
             }
             default:
                 ARM_COMPUTE_ERROR("Reduction Operation unsupported");
         }
         _fill_border_kernel.configure(input, fill_border_size, (is_arg_min_max ? BorderMode::REPLICATE : BorderMode::CONSTANT), pixelValue);
     }
     if(_is_reshape_required)
     {
         _reshape_kernel.configure(output_internal, output);
         _output_internal.allocator()->allocate();
     }
 }
References TensorAllocator::allocate(), Tensor::allocator(), arm_compute::ARG_IDX_MAX, arm_compute::ARG_IDX_MIN, ARM_COMPUTE_ERROR, ARM_COMPUTE_ERROR_ON_NULLPTR, ARM_COMPUTE_ERROR_THROW_ON, arm_compute::auto_init_if_empty(), arm_compute::test::validation::axis, NEReductionOperationKernel::border_size(), arm_compute::misc::shape_calculator::compute_reduced_shape(), NEReshapeLayerKernel::configure(), NEFillBorderKernel::configure(), NEReductionOperationKernel::configure(), arm_compute::CONSTANT, arm_compute::F16, arm_compute::F32, arm_compute::get_min_max(), ITensor::info(), TensorAllocator::init(), arm_compute::test::validation::input, MemoryGroup::manage(), arm_compute::MAX, arm_compute::MEAN_SUM, arm_compute::MIN, arm_compute::test::validation::output_data_type, arm_compute::PROD, arm_compute::QASYMM8, arm_compute::test::validation::qinfo, arm_compute::REPLICATE, arm_compute::S32, arm_compute::SUM, arm_compute::SUM_SQUARE, and NEReductionOperation::validate().
Referenced by NEL2NormalizeLayer::configure(), and NEFFTConvolutionLayer::configure().
run()
void run () override virtual
Run the kernels contained in the function.
For NEON kernels:
Multi-threading is used for the kernels which are parallelisable.
By default std::thread::hardware_concurrency() threads are used.
Note
CPPScheduler::set_num_threads() can be used to manually set the number of threads
For OpenCL kernels:
All the kernels are enqueued on the queue associated with CLScheduler.
The queue is then flushed.
Note
The function will not block until the kernels are executed. It is the user's responsibility to wait.
Will call prepare() on first run if hasn't been done
Implements IFunction.
Definition at line 221 of file NEReductionOperation.cpp.
 {
     if(_reduction_axis == 0)
     {
         NEScheduler::get().schedule(&_fill_border_kernel, Window::DimY);
     }
     NEScheduler::get().schedule(&_reduction_kernel, _window_split);
     if(_is_reshape_required)
     {
         NEScheduler::get().schedule(&_reshape_kernel, Window::DimY);
     }
 }
References Window::DimY, Scheduler::get(), and IScheduler::schedule().
Referenced by NEL2NormalizeLayer::run(), and NEFFTConvolutionLayer::run().
validate()
Status validate (const ITensorInfo * input, const ITensorInfo * output, unsigned int axis, ReductionOperation op, bool keep_dims = true) static
Static function to check if given info will lead to a valid configuration of NEReductionOperation.
Parameters
[in] input Source tensor info. Data type supported: QASYMM8/F16/F32. Data layouts supported: NCHW. (Written to only for border_size != 0)
[in] output Destination tensor info. Data types and data layouts supported: same as input.
[in] axis Dimension along which to reduce. Supported reduction axis : 0
[in] op Reduction operation to perform.
[in] keep_dims (Optional) Whether to keep the reduced dimension after the operation. Defaults to true.
Returns
a status
Definition at line 61 of file NEReductionOperation.cpp.
 {
     ARM_COMPUTE_RETURN_ERROR_ON_MSG(axis >= TensorShape::num_max_dimensions, "Reduction axis greater than max number of dimensions");
     ARM_COMPUTE_RETURN_ERROR_ON_MSG(axis > 3, "Unsupported reduction axis");
     const auto is_reshape_required = !keep_dims;
     auto *output_internal = output;
     TensorInfo info_before_reshape;
     if(is_reshape_required)
     {
         const TensorInfo expected_output_shape = output->clone()->set_tensor_shape(arm_compute::misc::shape_calculator::compute_reduced_shape(input->tensor_shape(), axis, keep_dims));
         ARM_COMPUTE_RETURN_ERROR_ON_MISMATCHING_SHAPES(&expected_output_shape, output);
         auto shape_before_reshape = input->tensor_shape();
         shape_before_reshape.set(axis, 1);
         const auto input_num_channles = input->num_channels();
         const auto input_qinfo        = input->quantization_info();
         const auto is_arg_min_max     = (op == ReductionOperation::ARG_IDX_MAX) || (op == ReductionOperation::ARG_IDX_MIN);
         const auto output_data_type   = is_arg_min_max ? DataType::S32 : output->data_type();
         info_before_reshape.set_data_type(output_data_type).set_tensor_shape(shape_before_reshape).set_num_channels(input_num_channles).set_quantization_info(input_qinfo);
         output_internal = &info_before_reshape;
     }
     ARM_COMPUTE_RETURN_ON_ERROR(NEReductionOperationKernel::validate(input, output_internal, axis, op));
     if(is_reshape_required)
     {
         ARM_COMPUTE_RETURN_ON_ERROR(NEReshapeLayerKernel::validate(output_internal, output));
     }
     return Status{};
 }
References arm_compute::ARG_IDX_MAX, arm_compute::ARG_IDX_MIN, ARM_COMPUTE_RETURN_ERROR_ON_MISMATCHING_SHAPES, ARM_COMPUTE_RETURN_ERROR_ON_MSG, ARM_COMPUTE_RETURN_ON_ERROR, arm_compute::test::validation::axis, ICloneable< T >::clone(), arm_compute::misc::shape_calculator::compute_reduced_shape(), ITensorInfo::data_type(), arm_compute::test::validation::input, Dimensions< uint32_t >::num_max_dimensions, arm_compute::test::validation::output_data_type, arm_compute::S32, TensorInfo::set_data_type(), ITensorInfo::set_num_channels(), ITensorInfo::set_quantization_info(), ITensorInfo::set_tensor_shape(), NEReshapeLayerKernel::validate(), and NEReductionOperationKernel::validate().
Referenced by NEReductionOperation::configure(), NEL2NormalizeLayer::validate(), and NEArgMinMaxLayer::validate().
The documentation for this class was generated from the following files:
arm_compute/runtime/NEON/functions/NEReductionOperation.h
src/runtime/NEON/functions/NEReductionOperation.cpp