Compute Library: CLReductionOperationKernel Class Reference
CLReductionOperationKernel Class Reference
Interface for the reduction operation kernel.
#include <CLReductionOperationKernel.h>
Public Member Functions
CLReductionOperationKernel ()
Default constructor.
CLReductionOperationKernel (const CLReductionOperationKernel &)=delete
Prevent instances of this class from being copied (As this class contains pointers)
CLReductionOperationKernel & operator= (const CLReductionOperationKernel &)=delete
Prevent instances of this class from being copied (As this class contains pointers)
CLReductionOperationKernel (CLReductionOperationKernel &&)=default
Allow instances of this class to be moved.
CLReductionOperationKernel & operator= (CLReductionOperationKernel &&)=default
Allow instances of this class to be moved.
~CLReductionOperationKernel ()=default
Default destructor.
void configure (const ICLTensor *input, ICLTensor *output, unsigned int axis, ReductionOperation op)
Set the input and output tensors.
void configure (const CLCompileContext &compile_context, const ICLTensor *input, ICLTensor *output, unsigned int axis, ReductionOperation op)
Set the input and output tensors.
void run (const Window &window, cl::CommandQueue &queue) override
Enqueue the OpenCL kernel to process the given window on the passed OpenCL command queue.
Public Member Functions inherited from ICLKernel
ICLKernel ()
Constructor.
cl::Kernel & kernel ()
Returns a reference to the OpenCL kernel of this object.
CLKernelType type () const
Returns the CL kernel type.
template<typename T >
void add_1D_array_argument (unsigned int &idx, const ICLArray< T > *array, const Strides &strides, unsigned int num_dimensions, const Window &window)
Add the passed 1D array's parameters to the object's kernel's arguments starting from the index idx.
void add_1D_tensor_argument (unsigned int &idx, const ICLTensor *tensor, const Window &window)
Add the passed 1D tensor's parameters to the object's kernel's arguments starting from the index idx.
void add_1D_tensor_argument_if (bool cond, unsigned int &idx, const ICLTensor *tensor, const Window &window)
Add the passed 1D tensor's parameters to the object's kernel's arguments starting from the index idx if the condition is true.
void add_2D_tensor_argument (unsigned int &idx, const ICLTensor *tensor, const Window &window)
Add the passed 2D tensor's parameters to the object's kernel's arguments starting from the index idx.
void add_2D_tensor_argument_if (bool cond, unsigned int &idx, const ICLTensor *tensor, const Window &window)
Add the passed 2D tensor's parameters to the object's kernel's arguments starting from the index idx if the condition is true.
void add_3D_tensor_argument (unsigned int &idx, const ICLTensor *tensor, const Window &window)
Add the passed 3D tensor's parameters to the object's kernel's arguments starting from the index idx.
void add_4D_tensor_argument (unsigned int &idx, const ICLTensor *tensor, const Window &window)
Add the passed 4D tensor's parameters to the object's kernel's arguments starting from the index idx.
void add_5D_tensor_argument (unsigned int &idx, const ICLTensor *tensor, const Window &window)
Add the passed 5D tensor's parameters to the object's kernel's arguments starting from the index idx.
void add_3d_tensor_nhw_argument (unsigned int &idx, const ICLTensor *tensor)
Add the passed NHW 3D tensor's parameters to the object's kernel's arguments by passing strides, dimensions and the offset to the first valid element in bytes.
void add_4d_tensor_nhwc_argument (unsigned int &idx, const ICLTensor *tensor)
Add the passed NHWC 4D tensor's parameters to the object's kernel's arguments by passing strides, dimensions and the offset to the first valid element in bytes.
virtual void run_op (ITensorPack &tensors, const Window &window, cl::CommandQueue &queue)
Enqueue the OpenCL kernel to process the given window on the passed OpenCL command queue.
template<typename T >
void add_argument (unsigned int &idx, T value)
Add the passed parameters to the object's kernel's arguments starting from the index idx.
void set_lws_hint (const cl::NDRange &lws_hint)
Set the Local-Workgroup-Size hint.
cl::NDRange lws_hint () const
Return the Local-Workgroup-Size hint.
void set_wbsm_hint (const cl_int &wbsm_hint)
Set the workgroup batch size modifier hint.
cl_int wbsm_hint () const
Return the workgroup batch size modifier hint.
const std::string & config_id () const
Get the configuration ID.
void set_target (GPUTarget target)
Set the targeted GPU architecture.
void set_target (cl::Device &device)
Set the targeted GPU architecture according to the CL device.
GPUTarget get_target () const
Get the targeted GPU architecture.
size_t get_max_workgroup_size ()
Get the maximum workgroup size for the device the CLKernelLibrary uses.
cl::NDRange get_cached_gws () const
Get the cached gws used to enqueue this kernel.
void cache_gws (const cl::NDRange &gws)
Cache the latest gws used to enqueue this kernel.
template<unsigned int dimension_size>
void add_tensor_argument (unsigned &idx, const ICLTensor *tensor, const Window &window)
template<typename T , unsigned int dimension_size>
void add_array_argument (unsigned &idx, const ICLArray< T > *array, const Strides &strides, unsigned int num_dimensions, const Window &window)
Add the passed array's parameters to the object's kernel's arguments starting from the index idx.
Public Member Functions inherited from IKernel
IKernel ()
Constructor.
virtual ~IKernel ()=default
Destructor.
virtual bool is_parallelisable () const
Indicates whether or not the kernel is parallelisable.
virtual BorderSize border_size () const
The size of the border for that kernel.
const Window & window () const
The maximum window the kernel can be executed on.
bool is_window_configured () const
Function to check if the embedded window of this kernel has been configured.
Static Public Member Functions
static Status validate (const ITensorInfo *input, const ITensorInfo *output, unsigned int axis, ReductionOperation op)
Static function to check if given info will lead to a valid configuration of CLReductionOperationKernel.
Static Public Member Functions inherited from ICLKernel
static constexpr unsigned int num_arguments_per_3d_tensor_nhw ()
Returns the number of arguments enqueued per NHW 3D Tensor object.
static constexpr unsigned int num_arguments_per_4d_tensor_nhwc ()
Returns the number of arguments enqueued per NHWC 4D Tensor object.
static constexpr unsigned int num_arguments_per_1D_array ()
Returns the number of arguments enqueued per 1D array object.
static constexpr unsigned int num_arguments_per_1D_tensor ()
Returns the number of arguments enqueued per 1D tensor object.
static constexpr unsigned int num_arguments_per_2D_tensor ()
Returns the number of arguments enqueued per 2D tensor object.
static constexpr unsigned int num_arguments_per_3D_tensor ()
Returns the number of arguments enqueued per 3D tensor object.
static constexpr unsigned int num_arguments_per_4D_tensor ()
Returns the number of arguments enqueued per 4D tensor object.
static cl::NDRange gws_from_window (const Window &window, bool use_dummy_work_items)
Get the global work size given an execution window.
Detailed Description
Interface for the reduction operation kernel.
Definition at line 36 of file CLReductionOperationKernel.h.
Constructor & Destructor Documentation
CLReductionOperationKernel() [1/3]
CLReductionOperationKernel ()
Default constructor.
Definition at line 75 of file CLReductionOperationKernel.cpp.
References arm_compute::ELEMENTWISE, and arm_compute::SUM_SQUARE.
     : _input(nullptr), _output(nullptr), _reduction_axis(0), _op(ReductionOperation::SUM_SQUARE)
 {
     _type = CLKernelType::ELEMENTWISE;
 }
CLReductionOperationKernel() [2/3]
CLReductionOperationKernel (const CLReductionOperationKernel &) delete
Prevent instances of this class from being copied (As this class contains pointers)
CLReductionOperationKernel() [3/3]
CLReductionOperationKernel (CLReductionOperationKernel &&) default
Allow instances of this class to be moved.
~CLReductionOperationKernel()
~CLReductionOperationKernel () default
Default destructor.
Member Function Documentation
configure() [1/2]
void configure (const ICLTensor * input, ICLTensor * output, unsigned int axis, ReductionOperation op)
Set the input and output tensors.
Parameters
[in] input Source tensor. Data types supported: QASYMM8/QASYMM8_SIGNED/S32/F16/F32.
[out] output Destination tensor. Data types and data layouts supported: Same as input. Output will have the same number of dimensions as input.
[in] axis Axis along which to reduce. Supported reduction axis : 0,1,2,3
[in] op Reduction operation to perform. Operations supported: MEAN_SUM, PROD, SUM_SQUARE, SUM, MIN, MAX
Definition at line 81 of file CLReductionOperationKernel.cpp.
References CLKernelLibrary::get().
 {
     configure(CLKernelLibrary::get().get_compile_context(), input, output, axis, op);
 }
configure() [2/2]
void configure (const CLCompileContext & compile_context, const ICLTensor * input, ICLTensor * output, unsigned int axis, ReductionOperation op)
Set the input and output tensors.
Parameters
[in] compile_context The compile context to be used.
[in] input Source tensor. Data types supported: QASYMM8/QASYMM8_SIGNED/S32/F16/F32.
[out] output Destination tensor. Data types and data layouts supported: Same as input. Output will have the same number of dimensions as input.
[in] axis Axis along which to reduce. Supported reduction axis : 0,1,2,3
[in] op Reduction operation to perform. Operations supported: MEAN_SUM, PROD, SUM_SQUARE, SUM, MIN, MAX
Definition at line 86 of file CLReductionOperationKernel.cpp.
References arm_compute::adjust_vec_size(), ARM_COMPUTE_ERROR, ARM_COMPUTE_ERROR_ON, ARM_COMPUTE_ERROR_ON_NULLPTR, ARM_COMPUTE_ERROR_THROW_ON, arm_compute::auto_init_if_empty(), arm_compute::calculate_max_window(), ICloneable< T >::clone(), arm_compute::misc::shape_calculator::compute_reduced_shape(), arm_compute::create_kernel(), arm_compute::test::validation::data_type, ITensorInfo::data_type(), ITensorInfo::dimension(), Window::DimX, arm_compute::float_to_string_with_full_precision(), arm_compute::get_cl_type_from_data_type(), arm_compute::get_padding_info(), arm_compute::has_padding_changed(), ITensor::info(), arm_compute::test::validation::input, arm_compute::is_data_type_float(), arm_compute::is_data_type_quantized(), arm_compute::MAX, arm_compute::MEAN_SUM, arm_compute::MIN, arm_compute::needs_serialized_reduction(), ITensorInfo::num_channels(), UniformQuantizationInfo::offset, arm_compute::test::validation::output_shape, arm_compute::PROD, ITensorInfo::quantization_info(), UniformQuantizationInfo::scale, Window::set(), arm_compute::SUM, arm_compute::SUM_SQUARE, ITensorInfo::tensor_shape(), arm_compute::support::cpp11::to_string(), QuantizationInfo::uniform(), and arm_compute::cpu::kernels::validate_arguments().
 {
     ARM_COMPUTE_ERROR_ON_NULLPTR(input, output);
     ARM_COMPUTE_ERROR_THROW_ON(validate_arguments(input->info(), output->info(), axis, op));
     auto padding_info = get_padding_info({ input, output });
     _input          = input;
     _output         = output;
     _reduction_axis = axis;
     _op             = op;
     const TensorShape output_shape = arm_compute::misc::shape_calculator::compute_reduced_shape(input->info()->tensor_shape(), axis, true);
     auto_init_if_empty(*output->info(), input->info()->clone()->set_tensor_shape(output_shape).reset_padding().set_is_resizable(true));
     // Set build options
     CLBuildOptions build_opts;
     DataType       data_type = input->info()->data_type();
     std::string    data_type_promoted{};
     if(is_data_type_quantized(data_type))
     {
         data_type_promoted = "int";
     }
     else
     {
         data_type_promoted = get_cl_type_from_data_type(data_type);
     }
     const unsigned int width             = input->info()->dimension(0) * input->info()->num_channels();
     unsigned int       vec_size          = (is_data_type_quantized(input->info()->data_type()) && (axis == 0)) ? 1 : 16;
     vec_size                             = adjust_vec_size(vec_size, width);
     const unsigned int vec_size_leftover = width % vec_size;
     build_opts.add_option("-DDATA_TYPE=" + get_cl_type_from_data_type(data_type));
     build_opts.add_option("-DDATA_TYPE_PROMOTED=" + data_type_promoted);
     build_opts.add_option("-DVEC_SIZE=" + support::cpp11::to_string(vec_size));
     build_opts.add_option("-DVEC_SIZE_LEFTOVER=" + support::cpp11::to_string(vec_size_leftover));
     build_opts.add_option_if(is_data_type_float(data_type), "-DFLOAT_DATA_TYPE");
     build_opts.add_option_if(op == ReductionOperation::SUM_SQUARE, "-DSUM_SQUARE");
     build_opts.add_option_if(op == ReductionOperation::MEAN_SUM, "-DMEAN");
     build_opts.add_option_if(op == ReductionOperation::SUM, "-DSUM");
     build_opts.add_option_if(op == ReductionOperation::PROD, "-DPROD");
     build_opts.add_option_if(op == ReductionOperation::MIN, "-DMIN");
     build_opts.add_option_if(op == ReductionOperation::MAX, "-DMAX");
     build_opts.add_option_if(is_data_type_quantized(data_type), "-DOFFSET=" + support::cpp11::to_string(input->info()->quantization_info().uniform().offset));
     build_opts.add_option_if(is_data_type_quantized(data_type), "-DSCALE=" + float_to_string_with_full_precision(input->info()->quantization_info().uniform().scale));
     switch(op)
     {
         case ReductionOperation::SUM_SQUARE:
             build_opts.add_option(("-DOPERATION=square_sum"));
             break;
         case ReductionOperation::SUM:
         case ReductionOperation::MEAN_SUM:
             build_opts.add_option(("-DOPERATION=sum"));
             break;
         case ReductionOperation::MIN:
         case ReductionOperation::MAX:
             break;
         case ReductionOperation::PROD:
             build_opts.add_option(("-DOPERATION=product"));
             break;
         default:
             ARM_COMPUTE_ERROR("Unsupported reduction operation");
     }
     // Create kernel
     std::string kernel_axis_name;
     const bool  is_serial_op = needs_serialized_reduction(_op, _input->info()->data_type(), _reduction_axis);
     switch(axis)
     {
         case 0:
         {
             build_opts.add_option("-DWIDTH=" + support::cpp11::to_string(width));
             kernel_axis_name = ((is_serial_op) ? "non_parallel_x" : "x");
         }
         break;
         case 1:
             build_opts.add_option("-DHEIGHT=" + support::cpp11::to_string(input->info()->dimension(1)));
             kernel_axis_name = "y";
             break;
         case 2:
             build_opts.add_option("-DDEPTH=" + support::cpp11::to_string(input->info()->dimension(2)));
             kernel_axis_name = "z";
             break;
         case 3:
             build_opts.add_option("-DDEPTH=" + support::cpp11::to_string(input->info()->dimension(2)));
             build_opts.add_option("-DBATCH=" + support::cpp11::to_string(input->info()->dimension(3)));
             kernel_axis_name = "w";
             break;
         default:
             ARM_COMPUTE_ERROR("Not supported");
     }
     _kernel = create_kernel(compile_context, "reduction_operation_" + kernel_axis_name, build_opts.options());
     // Configure kernel window
     Window win = calculate_max_window(*input->info(), Steps(vec_size));
     win.set(Window::DimX, Window::Dimension(win.x().start(), win.x().end() * _input->info()->num_channels(), win.x().step()));
     ICLKernel::configure_internal(win);
     ARM_COMPUTE_ERROR_ON(has_padding_changed(padding_info));
 }
operator=() [1/2]
CLReductionOperationKernel& operator= (const CLReductionOperationKernel &) delete
Prevent instances of this class from being copied (As this class contains pointers)
operator=() [2/2]
CLReductionOperationKernel& operator= (CLReductionOperationKernel &&) default
Allow instances of this class to be moved.
run()
void run (const Window & window, cl::CommandQueue & queue) override virtual
Enqueue the OpenCL kernel to process the given window on the passed OpenCL command queue.
Note
The queue is not flushed by this method, and therefore the kernel will not have been executed by the time this method returns.
Parameters
[in] window Region on which to execute the kernel. (Must be a valid region of the window returned by window()).
[in,out] queue Command queue on which to enqueue the kernel.
Reimplemented from ICLKernel.
Definition at line 198 of file CLReductionOperationKernel.cpp.
References ICLKernel::add_1D_tensor_argument(), ICLKernel::add_2D_tensor_argument(), ICLKernel::add_3D_tensor_argument(), ICLKernel::add_4D_tensor_argument(), ARM_COMPUTE_ERROR, ARM_COMPUTE_ERROR_ON, ARM_COMPUTE_ERROR_ON_INVALID_SUBWINDOW, ARM_COMPUTE_ERROR_ON_UNCONFIGURED_KERNEL, Window::collapse_if_possible(), ITensorInfo::data_type(), ITensorInfo::dimension(), Window::DimX, Window::DimY, Window::DimZ, arm_compute::enqueue(), Window::first_slice_window_1D(), Window::first_slice_window_2D(), Window::first_slice_window_3D(), Window::first_slice_window_4D(), ITensor::info(), arm_compute::needs_serialized_reduction(), Window::set(), Window::slide_window_slice_2D(), Window::slide_window_slice_3D(), Window::slide_window_slice_4D(), and IKernel::window().
 {
     ARM_COMPUTE_ERROR_ON_UNCONFIGURED_KERNEL(this);
     ARM_COMPUTE_ERROR_ON_INVALID_SUBWINDOW(IKernel::window(), window);
     const bool is_serial_op = needs_serialized_reduction(_op, _input->info()->data_type(), _reduction_axis);
     switch(_reduction_axis)
     {
         case 0:
         {
             // We use parallel reduction only in non quantized types
             if(is_serial_op)
             {
                 // Get first input and output slices
                 Window window_in{ window };
                 window_in.set(Window::DimX, Window::Dimension(0, _input->info()->dimension(0), _input->info()->dimension(0)));
                 Window out_window{ window };
                 out_window.set(Window::DimX, Window::Dimension(0, 0, 0));
                 Window in_slice  = window_in.first_slice_window_1D();
                 Window out_slice = out_window.first_slice_window_1D();
                 do
                 {
                     unsigned int idx = 0;
                     add_1D_tensor_argument(idx, _input, in_slice);
                     add_1D_tensor_argument(idx, _output, out_slice);
                     enqueue(queue, *this, in_slice);
                 }
                 while(window_in.slide_window_slice_1D(in_slice) && out_window.slide_window_slice_1D(out_slice));
             }
             else
             {
                 // Set out window
                 bool   has_collapsed = true;
                 Window window_in     = window.collapse_if_possible(window, 2, &has_collapsed);
                 ARM_COMPUTE_ERROR_ON(!has_collapsed);
                 Window window_out = window_in;
                 window_out.set(0, Window::Dimension());
                 unsigned int idx = 0;
                 add_3D_tensor_argument(idx, _input, window_in);
                 add_3D_tensor_argument(idx, _output, window_out);
                 enqueue(queue, *this, window_in);
             }
         }
         break;
         case 1:
         {
             // Get first input and output slices
             Window window_in{ window };
             window_in.set(Window::DimY, Window::Dimension(0, _input->info()->dimension(1), _input->info()->dimension(1)));
             Window in_slice  = window_in.first_slice_window_2D();
             Window out_slice = window.first_slice_window_2D();
             do
             {
                 unsigned int idx = 0;
                 add_2D_tensor_argument(idx, _input, in_slice);
                 add_2D_tensor_argument(idx, _output, out_slice);
                 enqueue(queue, *this, in_slice);
             }
             while(window_in.slide_window_slice_2D(in_slice) && window.slide_window_slice_2D(out_slice));
         }
         break;
         case 2:
         {
             // Get first input and output slices
             Window window_in{ window };
             window_in.set(Window::DimZ, Window::Dimension(0, _input->info()->dimension(2), _input->info()->dimension(2)));
             Window in_slice  = window_in.first_slice_window_3D();
             Window out_slice = window.first_slice_window_3D();
             do
             {
                 unsigned int idx = 0;
                 add_3D_tensor_argument(idx, _input, in_slice);
                 add_3D_tensor_argument(idx, _output, out_slice);
                 enqueue(queue, *this, in_slice);
             }
             while(window_in.slide_window_slice_3D(in_slice) && window.slide_window_slice_3D(out_slice));
         }
         break;
         case 3:
         {
             // Get first input and output slices
             Window window_in{ window };
             window_in.set(3, Window::Dimension(0, 1, 1));
             Window in_slice  = window_in.first_slice_window_4D();
             Window out_slice = window.first_slice_window_4D();
             do
             {
                 unsigned int idx = 0;
                 add_4D_tensor_argument(idx, _input, in_slice);
                 add_4D_tensor_argument(idx, _output, out_slice);
                 enqueue(queue, *this, in_slice);
             }
             while(window_in.slide_window_slice_4D(in_slice) && window.slide_window_slice_4D(out_slice));
         }
         break;
         default:
             ARM_COMPUTE_ERROR("Not supported");
     }
 }
validate()
Status validate (const ITensorInfo * input, const ITensorInfo * output, unsigned int axis, ReductionOperation op) static
Static function to check if given info will lead to a valid configuration of CLReductionOperationKernel.
Parameters
[in] input Source tensor info. Data types supported: QASYMM8/QASYMM8_SIGNED/S32/F16/F32.
[in] output Destination tensor info. Data types and data layouts supported: Same as input. Output will have the same number of dimensions as input.
[in] axis Axis along which to reduce. Supported reduction axis : 0,1,2,3
[in] op Reduction operation to perform. Operations supported: MEAN_SUM, PROD, SUM_SQUARE, SUM, MIN, MAX
Returns
a status
Definition at line 192 of file CLReductionOperationKernel.cpp.
References ARM_COMPUTE_RETURN_ON_ERROR, and arm_compute::cpu::kernels::validate_arguments().
Referenced by CLReductionOperation::validate().
 {
     ARM_COMPUTE_RETURN_ON_ERROR(validate_arguments(input, output, axis, op));
     return Status{};
 }
The documentation for this class was generated from the following files:
src/core/CL/kernels/CLReductionOperationKernel.h
src/core/CL/kernels/CLReductionOperationKernel.cpp