Compute Library: CpuConv2d Class Reference
CpuConv2d Class Reference
Basic function to simulate a convolution layer.
#include <CpuConv2d.h>
Public Member Functions
CpuConv2d ()
Constructor.
ARM_COMPUTE_DISALLOW_COPY_ALLOW_MOVE (CpuConv2d)
~CpuConv2d ()
Default destructor.
void configure (ITensorInfo *src, ITensorInfo *weights, const ITensorInfo *biases, ITensorInfo *dst, const PadStrideInfo &conv_info, const WeightsInfo &weights_info=WeightsInfo(), const Size2D &dilation=Size2D(1U, 1U), const ActivationLayerInfo &act_info=ActivationLayerInfo(), bool enable_fast_math=false, unsigned int num_groups=1)
Set the input and output tensors.
void run (ITensorPack &tensors) override
Run the kernels contained in the function.
void prepare (ITensorPack &constants) override
Prepare the function for executing.
experimental::MemoryRequirements workspace () const override
Return the memory requirements required by the workspace.
Public Member Functions inherited from INEOperator
INEOperator (IRuntimeContext *ctx=nullptr)
Constructor.
INEOperator (const INEOperator &)=delete
Prevent instances of this class from being copied (As this class contains pointers)
INEOperator (INEOperator &&)=default
Default move constructor.
INEOperator & operator= (const INEOperator &)=delete
Prevent instances of this class from being copied (As this class contains pointers)
INEOperator & operator= (INEOperator &&)=default
Default move assignment operator.
~INEOperator ()
Default destructor.
Public Member Functions inherited from IOperator
virtual ~IOperator ()=default
Destructor.
Static Public Member Functions
static Status validate (const ITensorInfo *src, const ITensorInfo *weights, const ITensorInfo *biases, const ITensorInfo *output, const PadStrideInfo &conv_info, const WeightsInfo &weights_info=WeightsInfo(), const Size2D &dilation=Size2D(1U, 1U), const ActivationLayerInfo &act_info=ActivationLayerInfo(), bool enable_fast_math=false, unsigned int num_groups=1)
Static function to check if given info will lead to a valid configuration of CpuConv2d.
static ConvolutionMethod get_convolution_method (const ITensorInfo *src, const ITensorInfo *weights, const ITensorInfo *dst, const PadStrideInfo &conv_info, const WeightsInfo &weights_info=WeightsInfo(), const Size2D &dilation=Size2D(1U, 1U), const ActivationLayerInfo &act_info=ActivationLayerInfo(), bool enable_fast_math=false)
Static function to check if given info will return the convolution called by CpuConv2d.
Detailed Description
Basic function to simulate a convolution layer.
This function calls one of the following functions:
CpuGemm (executed only in case GEMM is required for the operation)
CpuWinogradConv2d (executed only in case Winograd is required for the operation)
CpuDirectConv2d (executed only in case Direct Convolution is required for the operation)
The function selects one of the algorithms mentioned above based on:
The size of the kernel
Number of input/output feature maps
Amount of memory needed
Generally GEMM-based convolution is executed when neither Winograd nor FFT nor Direct convolution can be performed.
FP32 Algorithm Filter Size Input/Output feature maps
Winograd 3x3 1x3 3x1 5x1 1x5 5x5(fast maths) 7x1 1x7 Input channels is greater than 3
FFT Squared kernels and greater than 9x9 Input feature maps > Output feature maps
DirectConv 9x9
GEMM Any size
Winograd 5x5 requires fast maths enabled.
FP16 Algorithm Filter Size
Winograd Not supported
FFT Not supported
DirectConv 9x9
GEMM Any size
Definition at line 62 of file CpuConv2d.h.
Constructor & Destructor Documentation
CpuConv2d()
CpuConv2d ()
Constructor.
Definition at line 38 of file CpuConv2d.cpp.
References CpuConv2d::~CpuConv2d().
     : _function()
 {
 }
~CpuConv2d()
~CpuConv2d () default
Default destructor.
Referenced by CpuConv2d::CpuConv2d().
Member Function Documentation
ARM_COMPUTE_DISALLOW_COPY_ALLOW_MOVE()
ARM_COMPUTE_DISALLOW_COPY_ALLOW_MOVE (CpuConv2d)
configure()
void configure (ITensorInfo * src, ITensorInfo * weights, const ITensorInfo * biases, ITensorInfo * dst, const PadStrideInfo & conv_info, const WeightsInfo & weights_info = WeightsInfo(), const Size2D & dilation = Size2D(1U, 1U), const ActivationLayerInfo & act_info = ActivationLayerInfo(), bool enable_fast_math = false, unsigned int num_groups = 1)
Set the input and output tensors.
Valid data layouts:
NHWC
NCHW
Valid data type configurations:
src0 src1 src2 dst
F16 F16 F16 F16
F32 F32 F32 F32
QASYMM8 QASYMM8 S32 QASYMM8
QASYMM8 QSYMM8_PER_CHANNEL S32 QASYMM8
QASYMM8_SIGNED QASYMM8_SIGNED S32 QASYMM8_SIGNED
QASYMM8_SIGNED QSYMM8_PER_CHANNEL S32 QASYMM8_SIGNED
Parameters
[in] src Source tensor info. 3 lower dimensions represent a single input [width, height, IFM], while every optional dimension from 4 and above represent a batch of inputs. Data types supported: QASYMM8/QASYMM8_SIGNED/F16/F32.
[in] weights Weights tensor info. Weights are 4D tensor with dimensions [kernel_x, kernel_y, IFM, OFM]. Data type supported: Same as src, also could be QSYMM8_PER_CHANNEL if input is QASYMM8/QASYMM8_SIGNED.
[in] biases Biases tensor info. Shared biases supported. Biases are 1D tensor with dimensions [OFM]. Data type supported: Same as src, except for input of QASYMM8/QASYMM8_SIGNED type where biases should be of S32 type.
[out] dst Destination tensor info. 3 lower dimensions represent a single output [width, height, OFM], while the rest represent batch of outputs. Data types supported: Same as src.
[in] conv_info Contains padding and stride information described in PadStrideInfo.
[in] weights_info Specifies if the weights tensor has been reshaped with NEWeightsReshapeKernel. If this is not part of the fully connected layer the weights tensor has also been transposed with cpu::kernels::CpuGemmTranspose1xWKernel. Data type supported: Same as input.
[in] dilation (Optional) Dilation, in elements, across x and y. Defaults to (1, 1).
[in] act_info (Optional) Activation layer information in case of a fused activation. Only RELU, BOUNDED_RELU and LU_BOUNDED_RELU supported.
[in] enable_fast_math (Optional) Enable fast math computation. In case this flag were set, the function could dispatch the fastest implementation available which may introduce a drop of accuracy as well. Default is false
[in] num_groups (Optional) Number of groups when performing a grouped convolution. num_groups != 1 is not supported
Definition at line 45 of file CpuConv2d.cpp.
References ARM_COMPUTE_ERROR, ARM_COMPUTE_ERROR_ON_NULLPTR, ARM_COMPUTE_ERROR_THROW_ON, ARM_COMPUTE_LOG_PARAMS, ARM_COMPUTE_UNUSED, arm_compute::DIRECT, arm_compute::GEMM, arm_compute::GEMM_CONV2D, CpuConv2d::get_convolution_method(), arm_compute::test::validation::info, CpuConv2d::validate(), and arm_compute::WINOGRAD.
 {
     // Perform validate step
     ARM_COMPUTE_ERROR_ON_NULLPTR(input, weights, output);
     ARM_COMPUTE_UNUSED(num_groups);
     ARM_COMPUTE_ERROR_THROW_ON(CpuConv2d::validate(input, weights, biases, output, conv_info, weights_info, dilation, act_info,
                                                    enable_fast_math, num_groups));
     ARM_COMPUTE_LOG_PARAMS(input, weights, biases, output, conv_info, weights_info, dilation, act_info, enable_fast_math, num_groups);
     const Conv2dInfo info(conv_info, dilation, act_info, enable_fast_math, num_groups);
     switch(CpuConv2d::get_convolution_method(input, weights, output, conv_info, weights_info, dilation, act_info, enable_fast_math))
     {
         case ConvolutionMethod::WINOGRAD:
         {
             auto f = std::make_unique<CpuWinogradConv2d>();
             f->configure(input, weights, biases, output, conv_info, act_info, enable_fast_math);
             _function = std::move(f);
             break;
         }
         case ConvolutionMethod::GEMM:
         {
             auto f = std::make_unique<CpuGemmConv2d>();
             f->configure(input, weights, biases, output, conv_info, weights_info, dilation, act_info, enable_fast_math);
             _function = std::move(f);
             break;
         }
         case ConvolutionMethod::GEMM_CONV2D:
         {
             auto f = std::make_unique<CpuGemmDirectConv2d>();
             f->configure(input, weights, biases, output, info);
             _function = std::move(f);
             break;
         }
         case ConvolutionMethod::DIRECT:
         {
             auto f = std::make_unique<CpuDirectConv2d>();
             f->configure(input, weights, biases, output, conv_info, act_info);
             _function = std::move(f);
             break;
         }
         default:
             ARM_COMPUTE_ERROR("Not supported.");
             break;
     }
     _aux_mem = _function->workspace();
 }
get_convolution_method()
ConvolutionMethod get_convolution_method (const ITensorInfo * src, const ITensorInfo * weights, const ITensorInfo * dst, const PadStrideInfo & conv_info, const WeightsInfo & weights_info = WeightsInfo(), const Size2D & dilation = Size2D(1U, 1U), const ActivationLayerInfo & act_info = ActivationLayerInfo(), bool enable_fast_math = false) static
Static function to check if given info will return the convolution called by CpuConv2d.
Parameters
[in] src Source tensor info. 3 lower dimensions represent a single input [width, height, IFM], while every optional dimension from 4 and above represent a batch of inputs. Data types supported: QASYMM8/QASYMM8_SIGNED/F16/F32.
[in] weights Weights tensor info. Weights are 4D tensor with dimensions [kernel_x, kernel_y, IFM, OFM]. Data type supported:Same as src, also could be QSYMM8_PER_CHANNEL if input is QASYMM8/QASYMM8_SIGNED.
[in] dst Destination tensor info. 3 lower dimensions represent a single output [width, height, OFM], while the rest represent batch of outputs. Data types supported: Same as src.
[in] conv_info Contains padding and stride information described in PadStrideInfo.
[in] weights_info Specifies if the weights tensor has been reshaped with NEWeightsReshapeKernel. If this is not part of the fully connected layer the weights tensor has also been transposed with cpu::kernels::CpuGemmTranspose1xWKernel. Data type supported: Same as input.
[in] dilation (Optional) Dilation, in elements, across x and y. Defaults to (1, 1).
[in] act_info (Optional) Activation layer information in case of a fused activation.
[in] enable_fast_math (Optional) Enable fast math computation. In case this flag were set, the function could dispatch the fastest implementation available which may introduce a drop of accuracy as well. Default is false
Returns
the Convolution Method Hint
Definition at line 123 of file CpuConv2d.cpp.
References arm_compute::A55r1, ARM_COMPUTE_ERROR_ON_NULLPTR, ARM_COMPUTE_UNUSED, arm_compute::CHANNEL, IScheduler::cpu_info(), ITensorInfo::data_layout(), ITensorInfo::data_type(), ITensorInfo::dimension(), arm_compute::DIRECT, arm_compute::F16, arm_compute::FFT, arm_compute::FLOOR, arm_compute::GEMM, arm_compute::GEMM_CONV2D, Scheduler::get(), CPUInfo::get_cpu_model(), arm_compute::get_data_layout_dimension_index(), arm_compute::HEIGHT, arm_compute::test::validation::info, PadStrideInfo::pad_bottom(), PadStrideInfo::pad_left(), PadStrideInfo::pad_right(), PadStrideInfo::pad_top(), PadStrideInfo::stride(), ITensorInfo::total_size(), arm_compute::utils::cast::U, CpuGemmDirectConv2d::validate(), CpuWinogradConv2d::validate(), CpuDirectConv2d::validate(), NEFFTConvolutionLayer::validate(), arm_compute::WIDTH, and arm_compute::WINOGRAD.
Referenced by CpuConv2d::configure(), NEConvolutionLayer::configure(), arm_compute::test::validation::DATA_TEST_CASE(), NEConvolutionLayer::get_convolution_method(), CpuConv2d::validate(), and NEConvolutionLayer::validate().
 {
     ARM_COMPUTE_ERROR_ON_NULLPTR(input, output, weights);
     ARM_COMPUTE_UNUSED(weights_info);
     const size_t idx_w = get_data_layout_dimension_index(input->data_layout(), DataLayoutDimension::WIDTH);
     const size_t idx_h = get_data_layout_dimension_index(input->data_layout(), DataLayoutDimension::HEIGHT);
     const size_t idx_c = get_data_layout_dimension_index(input->data_layout(), DataLayoutDimension::CHANNEL);
     const Conv2dInfo info(conv_info, dilation, act_info, enable_fast_math, 1);
     /* Input spatial dims, kernel size, IFM/OFM, conv info*/
     using ConvolutionConfiguration = std::tuple<Size2D, Size2D, Size2D, PadStrideInfo>;
     using ConfigurationMethod      = std::pair<ConvolutionConfiguration, ConvolutionMethod>;
     const std::vector<ConfigurationMethod> known_configs =
     {
         // Alexnet
         ConfigurationMethod(ConvolutionConfiguration(Size2D(27U, 27U), Size2D(5U, 5U), Size2D(48U, 128U), PadStrideInfo(1U, 1U, 2U, 2U)), ConvolutionMethod::GEMM),
         // VGG16 / VGG19
         ConfigurationMethod(ConvolutionConfiguration(Size2D(224U, 224U), Size2D(3U, 3U), Size2D(3U, 64U), PadStrideInfo(1U, 1U, 1U, 1U)), ConvolutionMethod::GEMM),
         // Mobilenet 224
         ConfigurationMethod(ConvolutionConfiguration(Size2D(224U, 224U), Size2D(3U, 3U), Size2D(3U, 32U), PadStrideInfo(2U, 2U, 0U, 1U, 0U, 1U, DimensionRoundingType::FLOOR)), ConvolutionMethod::GEMM),
         // Mobilenet 160
         ConfigurationMethod(ConvolutionConfiguration(Size2D(160U, 160U), Size2D(3U, 3U), Size2D(3U, 24U), PadStrideInfo(2U, 2U, 0U, 1U, 0U, 1U, DimensionRoundingType::FLOOR)), ConvolutionMethod::GEMM)
     };
     const auto find_config = [&](ConfigurationMethod c)
     {
         const ConvolutionConfiguration config = c.first;
         const PadStrideInfo            info   = std::get<3>(config);
         return std::get<0>(config) == Size2D(input->dimension(idx_w), input->dimension(idx_h)) && std::get<1>(config) == Size2D(weights->dimension(idx_w), weights->dimension(idx_h))
                && std::get<2>(config) == Size2D(weights->dimension(idx_c), weights->dimension(3)) && info.pad_top() == conv_info.pad_top() && info.pad_right() == conv_info.pad_right()
                && info.pad_bottom() == conv_info.pad_bottom() && info.pad_left() == conv_info.pad_left() && info.stride() == conv_info.stride();
     };
     std::vector<ConfigurationMethod>::const_iterator found;
     if((found = std::find_if(known_configs.begin(), known_configs.end(), find_config)) != known_configs.end())
     {
         return (*found).second;
     }
     if(dilation != Size2D(1U, 1U))
     {
         return ConvolutionMethod::GEMM;
     }
     else
     {
         // SRGAN
         // Output might not be initialized when it is an internal tensor of the layer using the convolution
         if(input->total_size() > 1e7 && (weights->dimension(idx_h) > 7)
            && (CpuDirectConv2d::validate(input, weights, nullptr, output, conv_info, act_info)))
         {
             return ConvolutionMethod::DIRECT;
         }
         if((weights->dimension(idx_h) > 7) && (input->dimension(idx_c) > output->dimension(idx_c)) && (NEFFTConvolutionLayer::validate(input, weights, nullptr, output, conv_info, act_info)))
         {
             return ConvolutionMethod::FFT;
         }
         if(input->dimension(idx_c) < 16)
         {
             return ConvolutionMethod::GEMM;
         }
 #ifdef __ARM_FEATURE_FP16_VECTOR_ARITHMETIC
         // This heuristics only applies to F16 data type on A55r1
         if(NEScheduler::get().cpu_info().get_cpu_model() == CPUModel::A55r1 && enable_fast_math && input->data_type() == DataType::F16)
         {
             // Exclude known bad winograd configs (and defaults to GEMM)
             const std::vector<ConvolutionConfiguration> known_bad_winograd_f16_with_fastmath_configs =
             {
                 // Squeezenet_V1_1 fire2 and fire3
                 ConvolutionConfiguration(Size2D(56U, 56U), Size2D(3U, 3U), Size2D(16U, 64U), PadStrideInfo(1U, 1U, 1U, 1U)),
                 // Squeezenet_V1_1 fire6 and fire7
                 ConvolutionConfiguration(Size2D(14U, 14U), Size2D(3U, 3U), Size2D(48U, 192U), PadStrideInfo(1U, 1U, 1U, 1U)),
                 // Squeezenet_V1_1 fire8 and fire9
                 ConvolutionConfiguration(Size2D(14U, 14U), Size2D(3U, 3U), Size2D(64U, 256U), PadStrideInfo(1U, 1U, 1U, 1U)),
             };
             const auto find_conv_config = [&](ConvolutionConfiguration c)
             {
                 const PadStrideInfo info = std::get<3>(c);
                 return std::get<0>(c) == Size2D(input->dimension(idx_w), input->dimension(idx_h)) && std::get<1>(c) == Size2D(weights->dimension(idx_w), weights->dimension(idx_h))
                        && std::get<2>(c) == Size2D(weights->dimension(idx_c), weights->dimension(3)) && info.pad_top() == conv_info.pad_top() && info.pad_right() == conv_info.pad_right()
                        && info.pad_bottom() == conv_info.pad_bottom() && info.pad_left() == conv_info.pad_left() && info.stride() == conv_info.stride();
             };
             bool found_bad = std::find_if(known_bad_winograd_f16_with_fastmath_configs.begin(), known_bad_winograd_f16_with_fastmath_configs.end(),
                                           find_conv_config)
                              != known_bad_winograd_f16_with_fastmath_configs.end();
             if(found_bad)
             {
                 return ConvolutionMethod::GEMM;
             }
         }
 #endif // __ARM_FEATURE_FP16_VECTOR_ARITHMETIC
         // For 1x1 convolutions run the default GEMM
         if(weights->dimension(idx_w) == 1 && weights->dimension(idx_h) == 1)
         {
             return ConvolutionMethod::GEMM;
         }
         if(bool(CpuWinogradConv2d::validate(input, weights, nullptr, output, conv_info, act_info, enable_fast_math)))
         {
             return ConvolutionMethod::WINOGRAD;
         }
         if(bool(CpuGemmDirectConv2d::validate(input, weights, nullptr, output, info)))
         {
             return ConvolutionMethod::GEMM_CONV2D;
         }
         return ConvolutionMethod::GEMM;
     }
 }
prepare()
void prepare (ITensorPack & constants) override virtual
Prepare the function for executing.
Any one off pre-processing step required by the function is handled here
Parameters
[in] constants Vector that contains the constants tensors.
Note
Prepare stage might not need all the function's buffers' backing memory to be available in order to execute
Reimplemented from INEOperator.
Definition at line 246 of file CpuConv2d.cpp.
Referenced by CpuConv2d::run().
 {
     _function->prepare(tensors);
 }
run()
void run (ITensorPack & tensors) override virtual
Run the kernels contained in the function.
Parameters
[in] tensors Vector that contains the tensors to operate on.
Reimplemented from INEOperator.
Definition at line 240 of file CpuConv2d.cpp.
References CpuConv2d::prepare().
 {
     prepare(tensors);
     _function->run(tensors);
 }
validate()
Status validate (const ITensorInfo * src, const ITensorInfo * weights, const ITensorInfo * biases, const ITensorInfo * output, const PadStrideInfo & conv_info, const WeightsInfo & weights_info = WeightsInfo(), const Size2D & dilation = Size2D(1U, 1U), const ActivationLayerInfo & act_info = ActivationLayerInfo(), bool enable_fast_math = false, unsigned int num_groups = 1) static
Static function to check if given info will lead to a valid configuration of CpuConv2d.
Similar to CpuConv2d::configure()
Returns
a status
Definition at line 95 of file CpuConv2d.cpp.
References ARM_COMPUTE_ERROR, ARM_COMPUTE_RETURN_ERROR_ON_MSG, ARM_COMPUTE_RETURN_ON_ERROR, arm_compute::DIRECT, arm_compute::GEMM, arm_compute::GEMM_CONV2D, CpuConv2d::get_convolution_method(), arm_compute::test::validation::info, CpuGemmDirectConv2d::validate(), CpuDirectConv2d::validate(), CpuWinogradConv2d::validate(), CpuGemmConv2d::validate(), and arm_compute::WINOGRAD.
Referenced by CpuConv2d::configure(), and NEConvolutionLayer::validate().
 {
     ARM_COMPUTE_RETURN_ERROR_ON_MSG((num_groups != 1), "Grouping (num_groups != 1) is not supported on Neon");
     const Conv2dInfo info(conv_info, dilation, act_info, enable_fast_math, num_groups);
     switch(CpuConv2d::get_convolution_method(input, weights, output, conv_info, weights_info, dilation, act_info, enable_fast_math))
     {
         case ConvolutionMethod::WINOGRAD:
             ARM_COMPUTE_RETURN_ON_ERROR(CpuWinogradConv2d::validate(input, weights, biases, output, conv_info, act_info, enable_fast_math));
             break;
         case ConvolutionMethod::GEMM:
             ARM_COMPUTE_RETURN_ON_ERROR(CpuGemmConv2d::validate(input, weights, biases, output, conv_info, weights_info, dilation, act_info, enable_fast_math));
             break;
         case ConvolutionMethod::GEMM_CONV2D:
             ARM_COMPUTE_RETURN_ON_ERROR(CpuGemmDirectConv2d::validate(input, weights, biases, output, info));
             break;
         case ConvolutionMethod::DIRECT:
             ARM_COMPUTE_RETURN_ON_ERROR(CpuDirectConv2d::validate(input, weights, biases, output, conv_info, act_info));
             break;
         default:
             ARM_COMPUTE_ERROR("Not supported.");
             break;
     }
     return Status{};
 }
workspace()
experimental::MemoryRequirements workspace () const override virtual
Return the memory requirements required by the workspace.
Reimplemented from INEOperator.
Definition at line 251 of file CpuConv2d.cpp.
 {
     return _aux_mem;
 }
The documentation for this class was generated from the following files:
src/cpu/operators/CpuConv2d.h
src/cpu/operators/CpuConv2d.cpp