Compute Library: GpuWorkloadSourceCode Class Reference
GpuWorkloadSourceCode Class Reference
Hold the generated kernel source code and other information required to compile and run the workload.
#include <GpuWorkloadSourceCode.h>
Public Member Functions
GpuWorkloadSourceCode ()=default
Default constructor.
UnitWorkloadId add_unit_workload (const GpuKernelSourceCode &kernel_code, const UnitWorkloadStage &stage, const MemoryDescriptorMap &mem_map)
Add a unit workload to the workload code.
const GpuUnitWorkload & query_unit_workload (UnitWorkloadId id) const
Get a unit workload from its id.
std::vector< UnitWorkloadId > unit_workloads () const
Get all unit workloads sorted in topological order.
const GpuWorkloadArgument * query_tensor (ITensorInfo::Id t_id) const
Get a GpuWorkloadArgument from its associated tensor id.
std::vector< ITensorInfo::Id > tensors () const
Get all tensors in the entire workload.
std::vector< UnitWorkloadId > get_unit_workloads_from_tensor (ITensorInfo::Id t_id) const
Get all unit workloads connected to the tensor with t_id.
Detailed Description
Hold the generated kernel source code and other information required to compile and run the workload.
Definition at line 172 of file GpuWorkloadSourceCode.h.
Constructor & Destructor Documentation
GpuWorkloadSourceCode()
GpuWorkloadSourceCode () default
Default constructor.
Member Function Documentation
add_unit_workload()
UnitWorkloadId add_unit_workload (const GpuKernelSourceCode & kernel_code, const UnitWorkloadStage & stage, const MemoryDescriptorMap & mem_map) inline
Add a unit workload to the workload code.
Parameters
[in] kernel_code GpuKernelSourceCode to be contained within the unit workload
[in] stage Stage of the unit workload
[in] mem_map MemoryDescriptor map for all tensors within the unit workload
Returns
UnitWorkloadId Allocated unit workload id
Definition at line 185 of file GpuWorkloadSourceCode.h.
References GpuKernelSourceCode::arguments(), and GpuWorkloadArgument::tensor_info().
Referenced by GpuKernelComponentStream::write_workload_code().
     {
         // Use the size of the kernel codes as Id
         const auto uwk_id    = static_cast<UnitWorkloadId>(_unit_workloads.size());
         const auto unit_work = GpuUnitWorkload(uwk_id, kernel_code, stage);
         _unit_workloads.push_back(unit_work);
         // Assemble kernel argument with memory descriptor to form workload argument
         for(const auto &id_arg : kernel_code.arguments())
         {
             const auto arg_id           = id_arg.first;
             const auto arg              = id_arg.second;
             _workload_arguments[arg_id] = GpuWorkloadArgument{ *arg.tensor_info(), mem_map.at(arg_id), *arg.kernel_argument_info() };
             if(_tensor_uwork_map.find(arg_id) == _tensor_uwork_map.end())
             {
                 _tensor_uwork_map[arg_id] = std::set<UnitWorkloadId>();
             }
             _tensor_uwork_map[arg_id].insert(uwk_id);
         }
         return uwk_id;
     }
get_unit_workloads_from_tensor()
std::vector<UnitWorkloadId> get_unit_workloads_from_tensor (ITensorInfo::Id t_id) const inline
Get all unit workloads connected to the tensor with t_id.
Definition at line 238 of file GpuWorkloadSourceCode.h.
     {
         const auto unit_work_set = _tensor_uwork_map.at(t_id);
         return std::vector<UnitWorkloadId>(unit_work_set.begin(), unit_work_set.end());
     }
query_tensor()
const GpuWorkloadArgument* query_tensor (ITensorInfo::Id t_id) const inline
Get a GpuWorkloadArgument from its associated tensor id.
Definition at line 223 of file GpuWorkloadSourceCode.h.
     {
         return &_workload_arguments.at(t_id);
     }
query_unit_workload()
const GpuUnitWorkload& query_unit_workload (UnitWorkloadId id) const inline
Get a unit workload from its id.
Definition at line 206 of file GpuWorkloadSourceCode.h.
References ARM_COMPUTE_ERROR_ON.
     {
         ARM_COMPUTE_ERROR_ON(id < 0);
         return _unit_workloads.at(id);
     }
tensors()
std::vector<ITensorInfo::Id> tensors () const inline
Get all tensors in the entire workload.
Definition at line 228 of file GpuWorkloadSourceCode.h.
     {
         std::vector<ITensorInfo::Id> ids{};
         for(const auto &id_tensor : _workload_arguments)
         {
             ids.push_back(id_tensor.first);
         }
         return ids;
     }
unit_workloads()
std::vector<UnitWorkloadId> unit_workloads () const inline
Get all unit workloads sorted in topological order.
Definition at line 212 of file GpuWorkloadSourceCode.h.
     {
         std::vector<UnitWorkloadId> ids{};
         for(const auto &uwk : _unit_workloads)
         {
             ids.push_back(uwk.id());
         }
         return ids;
     }
The documentation for this class was generated from the following file:
src/dynamic_fusion/sketch/gpu/GpuWorkloadSourceCode.h