Compute Library: CpuMul Class Reference
CpuMul Class Reference
Basic function to run kernels::CpuMulKernel.
#include <CpuMul.h>
Public Member Functions
void configure (ITensorInfo *src1, ITensorInfo *src2, ITensorInfo *dst, float scale, ConvertPolicy overflow_policy, RoundingPolicy rounding_policy, const ActivationLayerInfo &act_info=ActivationLayerInfo())
Initialise the kernel's inputs, dst and convertion policy.
void run (ITensorPack &tensors) override
Run the kernels contained in the function.
Public Member Functions inherited from INEOperator
INEOperator (IRuntimeContext *ctx=nullptr)
Constructor.
INEOperator (const INEOperator &)=delete
Prevent instances of this class from being copied (As this class contains pointers)
INEOperator (INEOperator &&)=default
Default move constructor.
INEOperator & operator= (const INEOperator &)=delete
Prevent instances of this class from being copied (As this class contains pointers)
INEOperator & operator= (INEOperator &&)=default
Default move assignment operator.
~INEOperator ()
Default destructor.
void prepare (ITensorPack &constants) override
Prepare the function for executing.
MemoryRequirements workspace () const override
Return the memory requirements required by the workspace.
Public Member Functions inherited from IOperator
virtual ~IOperator ()=default
Destructor.
Static Public Member Functions
static Status validate (const ITensorInfo *src1, const ITensorInfo *src2, const ITensorInfo *dst, float scale, ConvertPolicy overflow_policy, RoundingPolicy rounding_policy, const ActivationLayerInfo &act_info=ActivationLayerInfo())
Static function to check if given info will lead to a valid configuration.
Detailed Description
Basic function to run kernels::CpuMulKernel.
Definition at line 35 of file CpuMul.h.
Member Function Documentation
configure()
void configure (ITensorInfo * src1, ITensorInfo * src2, ITensorInfo * dst, float scale, ConvertPolicy overflow_policy, RoundingPolicy rounding_policy, const ActivationLayerInfo & act_info = ActivationLayerInfo())
Initialise the kernel's inputs, dst and convertion policy.
Note
For scale equal to 1/255 only round to nearest even (implemented as round half up) is supported. For all other scale values only round to zero (implemented as round towards minus infinity) is supported.
Parameters
[in,out] src1 First input tensor info. Data types supported: U8/QASYMM8/QASYMM8_SIGNED/S16/S32/QSYMM16/F16/F32 This input tensor is [in, out] because its TensorInfo might be modified inside the kernel in case of broadcasting of dimension 0.
[in,out] src2 Second input tensor info. Data types supported: U8, QASYMM8 (only if src1 is QASYMM8), QASYMM8_SIGNED (only if src1 is QASYMM8_SIGNED), S16, S32, QSYMM16 (only if src1 is QSYMM16), F16 (only if src1 is F16), F32 (only if src1 is F32). This input tensor is [in, out] because its TensorInfo might be modified inside the kernel in case of broadcasting of dimension 0.
[out] dst dst tensor info. Data types supported:
U8, only if both inputs are U8.
QASYMM8, only if both inputs are QASYMM8.
QASYMM8_SIGNED, only if src1 is QASYMM8_SIGNED.
S16.
QSYMM16, only if both inputs are QSYMM16.
S32, only if both inputs are S32 or both are QSYMM16.
F16, only if src1 is F16.
F32, only if both inputs are F32.
[in] scale Scale to apply after multiplication. Scale must be positive and its value must be either 1/255 or 1/2^n where n is between 0 and 15. If both src1, src2 and dst are of datatype S32, scale cannot be 1/255
[in] overflow_policy Overflow policy. ConvertPolicy cannot be WRAP if any of the inputs is of quantized datatype
[in] rounding_policy Rounding policy.
[in] act_info (Optional) Activation layer information in case of a fused activation. Currently not supported.
Definition at line 43 of file CpuMul.cpp.
References ARM_COMPUTE_LOG_PARAMS, ARM_COMPUTE_UNUSED, and arm_compute::test::validation::k.
 {
     ARM_COMPUTE_UNUSED(act_info);
     ARM_COMPUTE_LOG_PARAMS(src1, src2, dst, scale, overflow_policy, rounding_policy, act_info);
     auto k = std::make_unique<kernels::CpuMulKernel>();
     k->configure(src1, src2, dst, scale, overflow_policy, rounding_policy);
     _kernel = std::move(k);
 }
run()
void run (ITensorPack & tensors) override virtual
Run the kernels contained in the function.
Parameters
[in] tensors Vector that contains the tensors to operate on.
Reimplemented from INEOperator.
Definition at line 54 of file CpuMul.cpp.
References ARM_COMPUTE_ERROR_ON_MSG, ITensorPack::empty(), Scheduler::get(), and IScheduler::schedule_op().
 {
     ARM_COMPUTE_ERROR_ON_MSG(tensors.empty(), "No inputs provided");
     auto split_dimension = static_cast<kernels::CpuMulKernel *>(_kernel.get())->get_split_dimension_hint();
     NEScheduler::get().schedule_op(_kernel.get(), split_dimension, _kernel->window(), tensors);
 }
validate()
Status validate (const ITensorInfo * src1, const ITensorInfo * src2, const ITensorInfo * dst, float scale, ConvertPolicy overflow_policy, RoundingPolicy rounding_policy, const ActivationLayerInfo & act_info = ActivationLayerInfo()) static
Static function to check if given info will lead to a valid configuration.
Similar to CpuMul::configure()
Returns
a status
Definition at line 36 of file CpuMul.cpp.
References ARM_COMPUTE_RETURN_ERROR_ON, ActivationLayerInfo::enabled(), and CpuMulKernel::validate().
Referenced by NEPixelWiseMultiplication::validate().
 {
     ARM_COMPUTE_RETURN_ERROR_ON(act_info.enabled());
     return kernels::CpuMulKernel::validate(src1, src2, dst, scale, overflow_policy, rounding_policy);
 }
The documentation for this class was generated from the following files:
src/cpu/operators/CpuMul.h
src/cpu/operators/CpuMul.cpp