Compute Library: ClTemplateCast Class Reference
ClTemplateCast Class Reference final
#include <ClTemplateCast.h>
Public Types
using Attributes = ClComponentCast::Attributes
Public Types inherited from IGpuTemplateComponentWriter
using ComponentGroup = GpuKernelComponentGroup
Public Member Functions
ClTemplateCast (ComponentId id, const ArgumentPack< ITensorInfo > &tensors, const Attributes &attributes)
Constructor.
ClTemplateCast (const ClTemplateCast &cast)=delete
Prevent instances of this class from being copy constructed.
ClTemplateCast & operator= (const ClTemplateCast &cast)=delete
Prevent instances of this class from being copied.
ClTemplateCast (ClTemplateCast &&cast)=default
Allow instances of this class to be move constructed.
ClTemplateCast & operator= (ClTemplateCast &&cast)=default
Allow instances of this class to be moved.
std::string get_name () const override
Generate kernel component name.
std::string get_component_code (const ComponentGroup &comp_group) const override
Generate kernel component code template.
void declare_variables (GpuKernelVariableTable &vtable, const ComponentGroup &comp_group) const override
Declare all variables used by the component in the vtable.
TagLUT get_tag_lut (const GpuKernelVariableTable &vtable, const ComponentGroup &comp_group) const override
Generate the tag look-up table used to instantiate the component code.
CLBuildOptions get_build_options (const ComponentGroup &comp_group) const override
Generate the build options used in the component.
std::string get_config_id () const override
Generate the component config id string used for tuning.
std::set< std::string > get_headers_list () const override
Generate the header list used in the component.
Window get_window () const override
Generate the execution window for the component.
Public Member Functions inherited from IGpuTemplateComponentWriter
IGpuTemplateComponentWriter (ComponentId id, const ArgumentPack< ITensorInfo > &tensors)
Constructor.
virtual ~IGpuTemplateComponentWriter ()
Destructor.
virtual std::string get_additional_macros () const
Generate additional macros used in the component.
ArgumentPack< ITensorInfo > tensors () const
Get tensor arguments.
ComponentId id () const
Get component id.
Additional Inherited Members
Static Public Attributes inherited from IGpuTemplateComponentWriter
static constexpr GpuKernelArgumentInfo::Type common_tensor_type = GpuKernelArgumentInfo::Type::Tensor_4D_t_Buffer
For now all kernel intermeditate/destination tensors are expected to be of type Tensor_4D_t_Buffer.
Detailed Description
Definition at line 37 of file ClTemplateCast.h.
Member Typedef Documentation
Attributes
using Attributes = ClComponentCast::Attributes
Definition at line 40 of file ClTemplateCast.h.
Constructor & Destructor Documentation
ClTemplateCast() [1/3]
ClTemplateCast (ComponentId id, const ArgumentPack< ITensorInfo > & tensors, const Attributes & attributes)
Constructor.
Parameters
[in] id Component id
[in] tensors Tensor arguments to the components
[in] attributes Component attributes
Definition at line 35 of file ClTemplateCast.cpp.
References arm_compute::ACL_DST_0, arm_compute::ACL_SRC_0, ARM_COMPUTE_ERROR_ON_NULLPTR, IGpuTemplateComponentWriter::id(), and IGpuTemplateComponentWriter::tensors().
     : IGpuTemplateComponentWriter{ id, tensors }, _src{}, _dst{}, _attributes{ attributes }
 {
     _src = this->tensors().get_const_tensor(TensorType::ACL_SRC_0);
     _dst = this->tensors().get_const_tensor(TensorType::ACL_DST_0);
     ARM_COMPUTE_ERROR_ON_NULLPTR(_src, _dst);
 }
ClTemplateCast() [2/3]
ClTemplateCast (const ClTemplateCast & cast) delete
Prevent instances of this class from being copy constructed.
ClTemplateCast() [3/3]
ClTemplateCast (ClTemplateCast && cast) default
Allow instances of this class to be move constructed.
Member Function Documentation
declare_variables()
void declare_variables (GpuKernelVariableTable & vtable, const ComponentGroup & comp_group) const override virtual
Declare all variables used by the component in the vtable.
Parameters
[out] vtable Variable table
[in] comp_group Component group of which the component is a part of
Implements IGpuTemplateComponentWriter.
Definition at line 127 of file ClTemplateCast.cpp.
References GpuKernelVariableTable::declare_variable(), and GpuKernelArgumentInfo::Tensor_4D_t_Buffer.
 {
     vtable.declare_variable(
         comp_group,
         _src,
         GpuKernelArgumentInfo(GpuKernelArgumentInfo::Type::Tensor_4D_t_Buffer),
         "src");
     vtable.declare_variable(
         comp_group,
         _dst,
         GpuKernelArgumentInfo(GpuKernelArgumentInfo::Type::Tensor_4D_t_Buffer),
         "dst");
 }
get_build_options()
CLBuildOptions get_build_options (const ComponentGroup & comp_group) const override virtual
Generate the build options used in the component.
Parameters
[in] comp_group Component group of which the component is a part of
Returns
CLBuildOptions Build options
Reimplemented from IGpuTemplateComponentWriter.
Definition at line 165 of file ClTemplateCast.cpp.
References CLBuildOptions::add_option(), ARM_COMPUTE_UNUSED, ITensorInfo::dimension(), GpuKernelComponentGroup::get_root_component(), IGpuTemplateComponentWriter::get_window(), Window::Dimension::step(), IGpuKernelComponent::template_writer(), arm_compute::support::cpp11::to_string(), and Window::x().
 {
     ARM_COMPUTE_UNUSED(comp_group);
     const auto         root_window = comp_group.get_root_component()->template_writer()->get_window();
     const unsigned int n0          = root_window.x().step();
     const unsigned int m0          = root_window.y().step();
     // Set build options
     CLBuildOptions build_opts{};
     build_opts.add_option("-DN0=" + support::cpp11::to_string(n0));
     build_opts.add_option("-DPARTIAL_N0=" + support::cpp11::to_string(_src->dimension(0) % n0));
     build_opts.add_option("-DM0=" + support::cpp11::to_string(m0));
     return build_opts;
 }
get_component_code()
std::string get_component_code (const ComponentGroup & comp_group) const override virtual
Generate kernel component code template.
Parameters
[in] comp_group Component group of which the component is a part of
Returns
std::string Component code
Implements IGpuTemplateComponentWriter.
Definition at line 52 of file ClTemplateCast.cpp.
References ARM_COMPUTE_UNUSED, CastAttributes::convert_policy(), ITensorInfo::data_type(), ClTemplateCast::get_name(), GpuKernelComponentGroup::get_root_component(), IGpuKernelComponent::id(), IGpuTemplateComponentWriter::id(), arm_compute::is_data_type_float(), arm_compute::is_data_type_quantized(), kernel_name, and arm_compute::SATURATE.
 {
     ARM_COMPUTE_UNUSED(comp_group);
     const std::string kernel_name = get_name();
     const auto        is_root     = (comp_group.get_root_component()->id() == this->id());
     std::string code = R"_(
 //------------------ START KERNEL {{meta_kernel_id}} CAST ---------------------
 )_";
     if(is_root)
     {
         code += R"_(
 // IN_0(src)            {{src}}
 // OUT(dst, accum)      {{dst}}
 TILE(uint, M0, 1, g_dst_indirect_y);
 {
     {{src}}_offset_first_element_in_bytes += get_global_id(2) * {{src}}_stride_z;
     TILE({{DATA_TYPE_IN}}, M0, N0, {{tmp}});
     T_LOAD({{DATA_TYPE_IN}}, M0, N0, BUFFER, {{src}}, g_ind_0, g_ind_1, 1, {{src}}_stride_y, {{tmp}});
 )_";
     }
     code += R"_(
     LOOP_UNROLLING(int, m0, 0, 1, M0,
     {
 )_";
     if(kernel_name == "cast_down" && is_data_type_quantized(_src->data_type()))
     {
         code += R"_(
     {{tmp}}[m0].v ^= (VEC_DATA_TYPE({{DATA_TYPE_IN}}, N0))0x80;
 )_";
     }
     if(kernel_name == "cast_down" && (is_data_type_float(_src->data_type()) || _attributes.convert_policy() == ConvertPolicy::SATURATE))
     {
         code += R"_(
     {{dst}}[m0].v = CONVERT_SAT({{tmp}}[m0].v, VEC_DATA_TYPE({{DATA_TYPE_OUT}}, N0));
 )_";
     }
     else
     {
         code += R"_(
     {{dst}}[m0].v = CONVERT({{tmp}}[m0].v, VEC_DATA_TYPE({{DATA_TYPE_OUT}}, N0));
 )_";
     }
     code += R"_(
     })
 )_";
     if(is_root)
     {
         code += R"_(
     LOOP_UNROLLING(int, i, 0, 1, M0,
     {
         g_dst_indirect_y[i].v = (uint)min((int)(g_ind_1 + i), (int)({{arg_dst}}_w) - 1);
         g_dst_indirect_y[i].v += (int)(g_ind_2 % {{arg_dst}}_h) * (int)({{arg_dst}}_w);
         g_dst_indirect_y[i].v += (int)(g_ind_2 / {{arg_dst}}_h) * (int)({{arg_dst}}_w * {{arg_dst}}_h);
     })
 }
 )_";
     }
     code += R"_(
 //------------------ END KERNEL {{meta_kernel_id}} CAST ---------------------
 )_";
     return code;
 }
get_config_id()
std::string get_config_id () const override virtual
Generate the component config id string used for tuning.
Reimplemented from IGpuTemplateComponentWriter.
Definition at line 182 of file ClTemplateCast.cpp.
References ITensorInfo::data_type(), ITensorInfo::dimension(), arm_compute::lower_string(), arm_compute::string_from_data_type(), and arm_compute::support::cpp11::to_string().
 {
     std::string config_id{};
     config_id += "_";
     config_id += lower_string(string_from_data_type(_src->data_type()));
     config_id += "_";
     config_id += lower_string(string_from_data_type(_dst->data_type()));
     config_id += "_";
     config_id += support::cpp11::to_string(_src->dimension(0));
     config_id += "_";
     config_id += support::cpp11::to_string(_src->dimension(1));
     return config_id;
 }
get_headers_list()
std::set< std::string > get_headers_list () const override virtual
Generate the header list used in the component.
Reimplemented from IGpuTemplateComponentWriter.
Definition at line 198 of file ClTemplateCast.cpp.
 {
     return std::set<std::string>{ "helpers.h", "tile_helpers.h" };
 }
get_name()
std::string get_name () const override virtual
Generate kernel component name.
Implements IGpuTemplateComponentWriter.
Definition at line 44 of file ClTemplateCast.cpp.
References arm_compute::data_size_from_type(), and ITensorInfo::data_type().
Referenced by ClTemplateCast::get_component_code().
 {
     const size_t src_size = data_size_from_type(_src->data_type());
     const size_t dst_size = data_size_from_type(_dst->data_type());
     return (src_size >= dst_size) ? "cast_down" : "cast_up";
 }
get_tag_lut()
TagLUT get_tag_lut (const GpuKernelVariableTable & vtable, const ComponentGroup & comp_group) const override virtual
Generate the tag look-up table used to instantiate the component code.
Parameters
[in] vtable Variable table
[in] comp_group Component group of which the component is a part of
Returns
TagLUT Tag lookup table
Implements IGpuTemplateComponentWriter.
Definition at line 142 of file ClTemplateCast.cpp.
References ITensorInfo::data_type(), GpuKernelComponentGroup::get_any_dst_tensor(), arm_compute::get_cl_type_from_data_type(), GpuKernelComponentGroup::get_root_component(), GpuKernelVariableTable::get_variable(), IGpuKernelComponent::id(), IGpuTemplateComponentWriter::id(), and GpuKernelVariableTable::TensorVariable::uniq_name.
 {
     const auto is_root = (comp_group.get_root_component()->id() == this->id());
     TagLUT lut{};
     // Arguments and global shared variables
     lut["src"] = vtable.get_variable(_src);
     lut["dst"] = vtable.get_variable(_dst);
     lut["tmp"] = (is_root) ? lut["src"].value + "_in_data" : lut["src"];
     const auto dst_argument = vtable.get_variable(comp_group.get_any_dst_tensor());
     lut["arg_dst"]          = dst_argument.uniq_name;
     // Local build options
     lut["meta_kernel_id"] = id();
     lut["DATA_TYPE_IN"]  = get_cl_type_from_data_type(_src->data_type());
     lut["DATA_TYPE_OUT"] = get_cl_type_from_data_type(_dst->data_type());
     return lut;
 }
get_window()
Window get_window () const override virtual
Generate the execution window for the component.
Reimplemented from IGpuTemplateComponentWriter.
Definition at line 203 of file ClTemplateCast.cpp.
References arm_compute::adjust_vec_size(), ARM_COMPUTE_ERROR_ON_MSG, arm_compute::calculate_max_window(), ITensorInfo::dimension(), Window::DimZ, ITensorInfo::element_size(), ITensorInfo::tensor_shape(), TensorShape::total_size(), and arm_compute::utils::cast::U.
 {
     ARM_COMPUTE_ERROR_ON_MSG(_dst->tensor_shape().total_size() == 0U, "Destination tensor is not initialized");
     const unsigned int n0  = adjust_vec_size(16 / _dst->element_size(), _dst->dimension(0));
     Window             win = calculate_max_window(*_dst, Steps(n0));
     return win.collapse(win, Window::DimZ);
 }
operator=() [1/2]
ClTemplateCast& operator= (const ClTemplateCast & cast) delete
Prevent instances of this class from being copied.
operator=() [2/2]
ClTemplateCast& operator= (ClTemplateCast && cast) default
Allow instances of this class to be moved.
The documentation for this class was generated from the following files:
src/dynamic_fusion/sketch/gpu/template_writer/cl/ClTemplateCast.h
src/dynamic_fusion/sketch/gpu/template_writer/cl/ClTemplateCast.cpp