Compute Library: SimpleTensor< T > Class Template Reference
SimpleTensor< T > Class Template Reference
Simple tensor object that stores elements in a consecutive chunk of memory.
#include <SimpleTensor.h>
Public Types
using value_type = T
Tensor value type.
using Buffer = std::unique_ptr< value_type[]>
Tensor buffer pointer type.
Public Member Functions
SimpleTensor ()=default
Create an uninitialised tensor.
SimpleTensor (TensorShape shape, Format format)
Create an uninitialised tensor of the given shape and format.
SimpleTensor (TensorShape shape, DataType data_type, int num_channels=1, QuantizationInfo quantization_info=QuantizationInfo(), DataLayout data_layout=DataLayout::NCHW)
Create an uninitialised tensor of the given shape and data type.
SimpleTensor (const SimpleTensor &tensor)
Create a deep copy of the given tensor.
SimpleTensor & operator= (SimpleTensor tensor)
Create a deep copy of the given tensor.
SimpleTensor (SimpleTensor &&)=default
Allow instances of this class to be move constructed.
~SimpleTensor ()=default
Default destructor.
T & operator[] (size_t offset)
Return value at offset in the buffer.
const T & operator[] (size_t offset) const
Return constant value at offset in the buffer.
TensorShape shape () const override
Shape of the tensor.
size_t element_size () const override
Size of each element in the tensor in bytes.
size_t size () const override
Total size of the tensor in bytes.
Format format () const override
Image format of the tensor.
DataLayout data_layout () const override
Data layout of the tensor.
DataType data_type () const override
Data type of the tensor.
int num_channels () const override
Number of channels of the tensor.
int num_elements () const override
Number of elements of the tensor.
PaddingSize padding () const override
Available padding around the tensor.
QuantizationInfo quantization_info () const override
Quantization info in case of asymmetric quantized type.
SimpleTensor< T > & quantization_info (const QuantizationInfo &qinfo)
Set the quantization information of the tensor.
const T * data () const
Constant pointer to the underlying buffer.
T * data ()
Pointer to the underlying buffer.
const void * operator() (const Coordinates &coord) const override
Read only access to the specified element.
void * operator() (const Coordinates &coord) override
Access to the specified element.
Public Member Functions inherited from IAccessor
virtual ~IAccessor ()=default
Virtual destructor.
Friends
class RawTensor
template<typename U >
void swap (SimpleTensor< U > &tensor1, SimpleTensor< U > &tensor2)
Swaps the content of the provided tensors.
Detailed Description
template<typename T>
class arm_compute::test::SimpleTensor< T >
Simple tensor object that stores elements in a consecutive chunk of memory.
It can be created by either loading an image from a file which also initialises the content of the tensor or by explcitly specifying the size. The latter leaves the content uninitialised.
Furthermore, the class provides methods to convert the tensor's values into different image format.
Definition at line 58 of file SimpleTensor.h.
Member Typedef Documentation
Buffer
using Buffer = std::unique_ptr<value_type[]>
Tensor buffer pointer type.
Definition at line 105 of file SimpleTensor.h.
value_type
using value_type = T
Tensor value type.
Definition at line 103 of file SimpleTensor.h.
Constructor & Destructor Documentation
SimpleTensor() [1/5]
SimpleTensor () default
Create an uninitialised tensor.
SimpleTensor() [2/5]
SimpleTensor (TensorShape shape, Format format)
Create an uninitialised tensor of the given shape and format.
Parameters
[in] shape Shape of the new raw tensor.
[in] format Format of the new raw tensor.
Definition at line 271 of file SimpleTensor.h.
     : _buffer(nullptr),
       _shape(shape),
       _format(format),
       _quantization_info(),
       _data_layout(DataLayout::NCHW)
 {
     _num_channels = num_channels();
     _buffer       = std::make_unique<T[]>(num_elements() * _num_channels);
 }
SimpleTensor() [3/5]
SimpleTensor (TensorShape shape, DataType data_type, int num_channels = 1, QuantizationInfo quantization_info = QuantizationInfo(), DataLayout data_layout = DataLayout::NCHW)
Create an uninitialised tensor of the given shape and data type.
Parameters
[in] shape Shape of the new raw tensor.
[in] data_type Data type of the new raw tensor.
[in] num_channels (Optional) Number of channels (default = 1).
[in] quantization_info (Optional) Quantization info for asymmetric quantization (default = empty).
[in] data_layout (Optional) Data layout of the tensor (default = NCHW).
Definition at line 283 of file SimpleTensor.h.
     : _buffer(nullptr),
       _shape(shape),
       _data_type(data_type),
       _num_channels(num_channels),
       _quantization_info(quantization_info),
       _data_layout(data_layout)
 {
     _buffer = std::make_unique<T[]>(this->_shape.total_size() * _num_channels);
 }
SimpleTensor() [4/5]
SimpleTensor (const SimpleTensor< T > & tensor)
Create a deep copy of the given tensor.
Parameters
[in] tensor To be copied tensor.
Definition at line 295 of file SimpleTensor.h.
     : _buffer(nullptr),
       _shape(tensor.shape()),
       _format(tensor.format()),
       _data_type(tensor.data_type()),
       _num_channels(tensor.num_channels()),
       _quantization_info(tensor.quantization_info()),
       _data_layout(tensor.data_layout())
 {
     _buffer = std::make_unique<T[]>(tensor.num_elements() * _num_channels);
     std::copy_n(tensor.data(), this->_shape.total_size() * _num_channels, _buffer.get());
 }
SimpleTensor() [5/5]
SimpleTensor (SimpleTensor< T > &&) default
Allow instances of this class to be move constructed.
~SimpleTensor()
~SimpleTensor () default
Default destructor.
Member Function Documentation
data() [1/2]
const T * data () const
Constant pointer to the underlying buffer.
Returns
a constant pointer to the data.
Definition at line 434 of file SimpleTensor.h.
Referenced by arm_compute::test::validation::reference::bounding_box_transform(), arm_compute::test::validation::reference::channel_shuffle(), arm_compute::test::validation::reference::compute_all_anchors(), arm_compute::test::validation::reference::compute_reduction_operation(), arm_compute::test::validation::reference::conv3d(), arm_compute::test::convolution_3d::detail::convolution3d(), arm_compute::test::validation::reference::copy(), arm_compute::test::copy_tensor(), arm_compute::test::validation::reference::crop_and_resize(), arm_compute::test::validation::reference::deconvolution_layer(), arm_compute::test::validation::reference::depthconcatenate_layer(), AssetsLibrary::fill(), arm_compute::test::validation::reference::flatten_layer(), arm_compute::test::validation::reference::fuse_batch_normalization_conv_layer(), arm_compute::test::validation::reference::fuse_batch_normalization_dwc_layer(), arm_compute::test::validation::reference::gather(), arm_compute::test::validation::reference::gemm_interleave_4x4(), arm_compute::test::validation::reference::gemm_transpose_1xW(), arm_compute::test::validation::get_tile(), arm_compute::test::validation::reference::mean_and_standard_deviation(), arm_compute::test::validation::reference::non_max_suppression(), arm_compute::test::prettify_tensor(), RawTensor::RawTensor(), arm_compute::test::validation::reference::reshape_layer(), arm_compute::test::validation::reference::roi_align_layer(), arm_compute::test::validation::reference::roi_pool_layer(), arm_compute::test::validation::reference::select(), and SimpleTensor< uint8_t >::SimpleTensor().
 {
     return _buffer.get();
 }
data() [2/2]
T * data ()
Pointer to the underlying buffer.
Returns
a pointer to the data.
Definition at line 440 of file SimpleTensor.h.
 {
     return _buffer.get();
 }
data_layout()
DataLayout data_layout () const override virtual
Data layout of the tensor.
Returns
the data layout of the tensor.
Implements IAccessor.
Definition at line 367 of file SimpleTensor.h.
Referenced by arm_compute::test::validation::convert_from_asymmetric(), arm_compute::test::validation::convert_from_symmetric(), arm_compute::test::copy_tensor(), arm_compute::test::validation::reference::crop_and_resize(), arm_compute::test::validation::reference::deconvolution_layer(), arm_compute::test::validation::reference::im2col(), arm_compute::test::validation::reference::im2col_nchw(), arm_compute::test::validation::reference::im2col_nhwc(), arm_compute::test::validation::reference::reorg_layer(), arm_compute::test::validation::reference::winograd_filter_transform(), and arm_compute::test::validation::reference::winograd_input_transform().
 {
     return _data_layout;
 }
data_type()
DataType data_type () const override virtual
Data type of the tensor.
Returns
the data type of the tensor.
Implements IAccessor.
Definition at line 373 of file SimpleTensor.h.
Referenced by arm_compute::test::validation::reference::activation_layer(), arm_compute::test::validation::reference::arithmetic_operation(), arm_compute::test::validation::reference::batch_normalization_layer(), arm_compute::test::validation::reference::batch_to_space(), arm_compute::test::validation::reference::bitwise_and(), arm_compute::test::validation::reference::bitwise_not(), arm_compute::test::validation::reference::bitwise_or(), arm_compute::test::validation::reference::bitwise_xor(), arm_compute::test::validation::reference::bounding_box_transform(), arm_compute::test::validation::reference::channel_shuffle(), arm_compute::test::validation::reference::col2im(), arm_compute::test::validation::reference::compare(), arm_compute::test::validation::reference::compute_all_anchors(), arm_compute::test::validation::reference::compute_reduction_operation(), arm_compute::test::validation::reference::convert_fully_connected_weights(), arm_compute::test::convolution_3d::detail::convolution3d(), arm_compute::test::validation::reference::convolution_layer(), arm_compute::test::validation::reference::copy(), arm_compute::test::copy_tensor(), arm_compute::test::validation::reference::deconvolution_layer(), arm_compute::test::validation::reference::depth_convert(), arm_compute::test::validation::reference::depth_to_space(), arm_compute::test::validation::reference::dequantization_layer(), arm_compute::test::validation::reference::elementwise_unary(), arm_compute::test::validation::reference::erode(), AssetsLibrary::fill(), VerifyAccessor< D >::fill_tensor(), arm_compute::test::validation::reference::flatten_layer(), arm_compute::test::validation::reference::floor_layer(), arm_compute::test::validation::reference::fully_connected_layer(), arm_compute::test::validation::reference::gather(), arm_compute::test::validation::reference::gemm(), arm_compute::test::validation::reference::gemm_mixed_precision(), arm_compute::test::validation::reference::gemm_reshape_lhs_matrix(), arm_compute::test::validation::reference::gemm_reshape_rhs_matrix(), arm_compute::test::validation::reference::gemm_transpose_1xW(), arm_compute::test::validation::reference::im2col_nchw(), arm_compute::test::validation::reference::im2col_nhwc(), arm_compute::test::validation::reference::instance_normalization(), arm_compute::test::validation::reference::l2_normalize(), arm_compute::test::validation::reference::logical_and(), arm_compute::test::validation::reference::logical_not(), arm_compute::test::validation::reference::logical_or(), arm_compute::test::validation::reference::max_unpooling_layer_internal(), arm_compute::test::validation::reference::mean_std_normalization_layer(), arm_compute::test::validation::reference::non_maxima_suppression(), arm_compute::test::validation::reference::normalization_layer(), arm_compute::test::validation::reference::normalize_planar_yuv_layer(), arm_compute::test::validation::reference::pad_layer(), arm_compute::test::validation::reference::permute(), arm_compute::test::validation::reference::pixel_wise_multiplication(), arm_compute::test::validation::reference::pooling_3d_layer_internal(), arm_compute::test::validation::reference::pooling_layer(), arm_compute::test::validation::reference::pooling_layer_internal(), arm_compute::test::validation::reference::prior_box_layer(), arm_compute::test::validation::reference::range(), arm_compute::test::validation::reference::reduction_operation(), arm_compute::test::validation::reference::reorder_layer(), arm_compute::test::validation::reference::reorg_layer(), arm_compute::test::validation::reference::reshape_layer(), arm_compute::test::validation::reference::reverse(), arm_compute::test::validation::reference::roi_align_layer(), arm_compute::test::validation::reference::roi_pool_layer(), arm_compute::test::validation::reference::scale_core(), arm_compute::test::validation::reference::select(), arm_compute::test::validation::reference::slice(), arm_compute::test::validation::reference::softmax_layer(), arm_compute::test::validation::reference::softmax_layer_generic(), arm_compute::test::validation::reference::space_to_batch(), arm_compute::test::validation::reference::space_to_depth(), arm_compute::test::validation::reference::strided_slice(), arm_compute::test::validation::reference::table_lookup(), arm_compute::test::validation::reference::tile(), arm_compute::test::validation::reference::transpose(), arm_compute::test::validation::transpose(), arm_compute::test::validation::validate(), arm_compute::test::validation::validate_wrap(), arm_compute::test::validation::reference::weights_reshape(), arm_compute::test::validation::reference::winograd_filter_transform(), arm_compute::test::validation::reference::winograd_input_transform(), and arm_compute::test::validation::reference::winograd_output_transform().
 {
     if(_format != Format::UNKNOWN)
     {
         return data_type_from_format(_format);
     }
     else
     {
         return _data_type;
     }
 }
element_size()
size_t element_size () const override virtual
Size of each element in the tensor in bytes.
Returns
the size of each element in the tensor in bytes.
Implements IAccessor.
Definition at line 335 of file SimpleTensor.h.
Referenced by AssetsLibrary::fill(), RawTensor::RawTensor(), arm_compute::test::validation::transpose(), arm_compute::test::validation::validate(), and arm_compute::test::validation::validate_wrap().
 {
     return num_channels() * element_size_from_data_type(data_type());
 }
format()
Format format () const override virtual
Image format of the tensor.
Returns
the format of the tensor.
Implements IAccessor.
Definition at line 361 of file SimpleTensor.h.
Referenced by AssetsLibrary::fill(), RawTensor::RawTensor(), arm_compute::test::validation::validate(), and arm_compute::test::validation::validate_wrap().
 {
     return _format;
 }
num_channels()
int num_channels () const override virtual
Number of channels of the tensor.
Returns
the number of channels of the tensor.
Implements IAccessor.
Definition at line 386 of file SimpleTensor.h.
Referenced by arm_compute::test::validation::reference::channel_shuffle(), arm_compute::test::colorconvert_helper::detail::colorconvert_rgb_to_rgbx(), arm_compute::test::colorconvert_helper::detail::colorconvert_rgbx_to_rgb(), arm_compute::test::copy_tensor(), arm_compute::test::validation::reference::dft_2d(), arm_compute::test::validation::reference::non_maxima_suppression(), arm_compute::test::validation::reference::permute(), RawTensor::RawTensor(), arm_compute::test::validation::reference::rdft_2d(), arm_compute::test::validation::reference::reverse(), arm_compute::test::validation::reference::ridft_2d(), arm_compute::test::validation::validate(), arm_compute::test::validation::validate_wrap(), and arm_compute::test::colorconvert_helper::detail::yuyv_to_rgb_calculation().
 {
     switch(_format)
     {
         case Format::U8:
         case Format::U16:
         case Format::S16:
         case Format::U32:
         case Format::S32:
         case Format::F16:
         case Format::F32:
             return 1;
         // Because the U and V channels are subsampled
         // these formats appear like having only 2 channels:
         case Format::YUYV422:
         case Format::UYVY422:
             return 2;
         case Format::UV88:
             return 2;
         case Format::RGB888:
             return 3;
         case Format::RGBA8888:
             return 4;
         case Format::UNKNOWN:
             return _num_channels;
         //Doesn't make sense for planar formats:
         case Format::NV12:
         case Format::NV21:
         case Format::IYUV:
         case Format::YUV444:
         default:
             return 0;
     }
 }
num_elements()
int num_elements () const override virtual
Number of elements of the tensor.
Returns
the number of elements of the tensor.
Implements IAccessor.
Definition at line 422 of file SimpleTensor.h.
Referenced by arm_compute::test::validation::reference::absolute_difference(), arm_compute::test::validation::reference::accumulate(), arm_compute::test::validation::reference::accumulate_squared(), arm_compute::test::validation::reference::accumulate_weighted(), arm_compute::test::validation::reference::activation_layer(), arm_compute::test::validation::reference::bitwise_and(), arm_compute::test::validation::reference::bitwise_not(), arm_compute::test::validation::reference::bitwise_or(), arm_compute::test::validation::reference::bitwise_xor(), arm_compute::test::validation::reference::compute_min_max(), arm_compute::test::validation::convert_from_asymmetric(), arm_compute::test::validation::convert_from_symmetric(), arm_compute::test::validation::reference::convert_fully_connected_weights(), arm_compute::test::validation::convert_to_asymmetric(), arm_compute::test::validation::convert_to_symmetric(), arm_compute::test::validation::reference::copy(), arm_compute::test::validation::reference::crop_and_resize(), arm_compute::test::validation::reference::depth_convert(), arm_compute::test::validation::reference::depthconcatenate_layer(), arm_compute::test::validation::reference::dequantization_layer(), arm_compute::test::validation::reference::elementwise_unary(), arm_compute::test::validation::reference::erode(), VerifyAccessor< D >::fill_tensor(), arm_compute::test::validation::reference::flatten_layer(), arm_compute::test::validation::reference::floor_layer(), arm_compute::test::validation::reference::logical_not(), arm_compute::test::validation::reference::mean_and_standard_deviation(), arm_compute::test::validation::reference::non_maxima_suppression(), arm_compute::test::validation::reference::pad_layer(), arm_compute::test::validation::reference::permute(), arm_compute::test::validation::reference::quantization_layer(), RawTensor::RawTensor(), arm_compute::test::validation::reference::reshape_layer(), arm_compute::test::validation::reference::reverse(), arm_compute::test::validation::reference::select(), SimpleTensor< uint8_t >::SimpleTensor(), arm_compute::test::validation::reference::table_lookup(), arm_compute::test::to_string(), arm_compute::test::validation::reference::transpose(), arm_compute::test::validation::validate(), and arm_compute::test::validation::validate_wrap().
 {
     return _shape.total_size();
 }
operator()() [1/2]
const void * operator() (const Coordinates & coord) const override virtual
Read only access to the specified element.
Parameters
[in] coord Coordinates of the desired element.
Returns
A pointer to the desired element.
Implements IAccessor.
Definition at line 446 of file SimpleTensor.h.
 {
     return _buffer.get() + coord2index(_shape, coord) * _num_channels;
 }
operator()() [2/2]
void * operator() (const Coordinates & coord) override virtual
Access to the specified element.
Parameters
[in] coord Coordinates of the desired element.
Returns
A pointer to the desired element.
Implements IAccessor.
Definition at line 452 of file SimpleTensor.h.
 {
     return _buffer.get() + coord2index(_shape, coord) * _num_channels;
 }
operator=()
SimpleTensor< T > & operator= (SimpleTensor< T > tensor)
Create a deep copy of the given tensor.
Parameters
[in] tensor To be copied tensor.
Returns
a copy of the given tensor.
Definition at line 309 of file SimpleTensor.h.
 {
     swap(*this, tensor);
     return *this;
 }
operator[]() [1/2]
T & operator[] (size_t offset)
Return value at offset in the buffer.
Parameters
[in] offset Offset within the buffer.
Returns
value in the buffer.
Definition at line 317 of file SimpleTensor.h.
 {
     return _buffer[offset];
 }
operator[]() [2/2]
const T & operator[] (size_t offset) const
Return constant value at offset in the buffer.
Parameters
[in] offset Offset within the buffer.
Returns
constant value in the buffer.
Definition at line 323 of file SimpleTensor.h.
 {
     return _buffer[offset];
 }
padding()
PaddingSize padding () const override virtual
Available padding around the tensor.
Returns
the available padding around the tensor.
Implements IAccessor.
Definition at line 428 of file SimpleTensor.h.
 {
     return PaddingSize(0);
 }
quantization_info() [1/2]
QuantizationInfo quantization_info () const override virtual
Quantization info in case of asymmetric quantized type.
Returns
Implements IAccessor.
Definition at line 341 of file SimpleTensor.h.
Referenced by arm_compute::test::validation::reference::activation_layer< int16_t >(), arm_compute::test::validation::reference::activation_layer< int8_t >(), arm_compute::test::validation::reference::activation_layer< uint8_t >(), arm_compute::test::validation::reference::arithmetic_operation(), arm_compute::test::validation::reference::bounding_box_transform(), arm_compute::test::validation::reference::channel_shuffle(), arm_compute::test::validation::reference::compute_all_anchors(), arm_compute::test::validation::reference::compute_reduction_operation(), arm_compute::test::validation::reference::conv3d(), arm_compute::test::validation::convert_from_asymmetric(), arm_compute::test::validation::convert_from_symmetric(), arm_compute::test::convolution_3d::detail::convolution3d(), arm_compute::test::validation::reference::convolution_layer(), arm_compute::test::copy_tensor(), arm_compute::test::validation::reference::deconvolution_layer(), arm_compute::test::validation::reference::depthconcatenate_layer(), arm_compute::test::validation::reference::dequantization_layer(), arm_compute::test::validation::reference::elementwise_unary(), VerifyAccessor< D >::fill_tensor(), arm_compute::test::validation::reference::fully_connected_layer(), arm_compute::test::validation::reference::im2col_nchw(), arm_compute::test::validation::reference::im2col_nhwc(), arm_compute::test::validation::reference::mean_std_normalization_layer(), arm_compute::test::validation::reference::normalize_planar_yuv_layer< int8_t >(), arm_compute::test::validation::reference::normalize_planar_yuv_layer< uint8_t >(), arm_compute::test::validation::reference::permute(), arm_compute::test::validation::reference::qlstm_layer_normalization(), arm_compute::test::validation::reference::range(), arm_compute::test::validation::reference::reduction_operation(), arm_compute::test::validation::reference::reverse(), arm_compute::test::validation::reference::scale(), and arm_compute::test::validation::reference::space_to_batch().
 {
     return _quantization_info;
 }
quantization_info() [2/2]
SimpleTensor< T > & quantization_info (const QuantizationInfo & qinfo)
Set the quantization information of the tensor.
This function does not have any effect on the raw quantized data of the tensor. It simply changes the quantization information, hence changes the dequantized values.
Returns
A reference to the current object.
Definition at line 347 of file SimpleTensor.h.
 {
     _quantization_info = qinfo;
     return *this;
 }
shape()
TensorShape shape () const override virtual
Shape of the tensor.
Returns
the shape of the tensor.
Implements IAccessor.
Definition at line 329 of file SimpleTensor.h.
Referenced by arm_compute::test::validation::reference::absolute_difference(), arm_compute::test::validation::reference::accumulate(), arm_compute::test::validation::reference::accumulate_squared(), arm_compute::test::validation::reference::accumulate_weighted(), arm_compute::test::validation::reference::activation_layer(), arm_compute::test::validation::apply_2d_spatial_filter(), arm_compute::test::validation::reference::arithmetic_division(), arm_compute::test::validation::reference::arithmetic_operation(), arm_compute::test::validation::reference::batch_normalization_layer(), arm_compute::test::validation::reference::batch_to_space(), arm_compute::test::validation::reference::bitwise_and(), arm_compute::test::validation::reference::bitwise_not(), arm_compute::test::validation::reference::bitwise_or(), arm_compute::test::validation::reference::bitwise_xor(), arm_compute::test::validation::reference::bounding_box_transform(), arm_compute::test::validation::reference::channel_shuffle(), arm_compute::test::validation::reference::col2im(), arm_compute::test::colorconvert_helper::detail::colorconvert_rgb_to_iyuv(), arm_compute::test::colorconvert_helper::detail::colorconvert_rgb_to_nv12(), arm_compute::test::colorconvert_helper::detail::colorconvert_rgb_to_rgbx(), arm_compute::test::colorconvert_helper::detail::colorconvert_rgb_to_u8(), arm_compute::test::colorconvert_helper::detail::colorconvert_rgb_to_yuv4(), arm_compute::test::colorconvert_helper::detail::colorconvert_rgbx_to_rgb(), arm_compute::test::colorconvert_helper::detail::colorconvert_yuyv_to_rgb(), arm_compute::test::validation::reference::compare(), arm_compute::test::validation::reference::compute_all_anchors(), arm_compute::test::validation::reference::compute_reduction_operation(), arm_compute::test::validation::reference::conv2d_dft(), arm_compute::test::validation::reference::conv3d(), arm_compute::test::validation::convert_from_asymmetric(), arm_compute::test::validation::convert_from_symmetric(), arm_compute::test::validation::reference::convert_fully_connected_weights(), arm_compute::test::validation::convert_to_asymmetric(), arm_compute::test::validation::convert_to_symmetric(), arm_compute::test::validation::reference::convolution_layer_nchw(), arm_compute::test::validation::reference::copy(), arm_compute::test::copy_tensor(), arm_compute::test::validation::reference::crop_and_resize(), arm_compute::test::validation::reference::deconvolution_layer(), arm_compute::test::validation::reference::depth_convert(), arm_compute::test::validation::reference::depth_to_space(), arm_compute::test::validation::reference::depthconcatenate_layer(), arm_compute::test::validation::reference::dequantization_layer(), arm_compute::test::validation::reference::elementwise_unary(), arm_compute::test::validation::reference::erode(), AssetsLibrary::fill(), arm_compute::test::validation::reference::floor_layer(), arm_compute::test::validation::reference::fully_connected_layer(), arm_compute::test::validation::reference::fuse_batch_normalization_conv_layer(), arm_compute::test::validation::reference::fuse_batch_normalization_dwc_layer(), arm_compute::test::validation::reference::gather(), arm_compute::test::validation::reference::gemm(), arm_compute::test::validation::reference::gemm_interleave_4x4(), arm_compute::test::validation::reference::gemm_interleave_blocked(), arm_compute::test::validation::reference::gemm_mixed_precision(), arm_compute::test::validation::reference::gemm_reshape_lhs_matrix(), arm_compute::test::validation::reference::gemm_reshape_rhs_matrix(), arm_compute::test::validation::reference::gemm_transpose_1xW(), arm_compute::test::validation::reference::gemmlowp_matrix_multiply_core(), arm_compute::test::validation::reference::gemmlowp_quantize_down_scale(), arm_compute::test::validation::reference::gemmlowp_quantize_down_scale_by_fixedpoint(), arm_compute::test::validation::reference::gemmlowp_quantize_down_scale_by_float(), AssetsLibrary::get(), AssetsLibrary::get_image_shape(), arm_compute::test::validation::get_tile(), arm_compute::test::validation::reference::im2col_nchw(), arm_compute::test::validation::reference::im2col_nhwc(), arm_compute::test::validation::reference::instance_normalization(), arm_compute::test::validation::reference::l2_normalize(), arm_compute::test::validation::reference::logical_and(), arm_compute::test::validation::reference::logical_binary_op(), arm_compute::test::validation::reference::logical_not(), arm_compute::test::validation::reference::logical_or(), arm_compute::test::validation::matrix_multiply(), arm_compute::test::validation::reference::max_unpooling_layer_internal(), arm_compute::test::validation::reference::mean_std_normalization_layer(), arm_compute::test::validation::reference::min_max_location(), arm_compute::test::validation::reference::non_max_suppression(), arm_compute::test::validation::reference::non_maxima_suppression(), arm_compute::test::validation::reference::normalization_layer(), arm_compute::test::validation::reference::normalize_planar_yuv_layer(), arm_compute::test::colorconvert_helper::detail::nv_to_iyuv(), arm_compute::test::colorconvert_helper::detail::nv_to_yuv4(), arm_compute::test::validation::reference::pad_layer(), arm_compute::test::validation::reference::permute(), arm_compute::test::validation::reference::pixel_wise_multiplication(), arm_compute::test::validation::reference::pooling_3d_layer_internal(), arm_compute::test::validation::reference::pooling_layer_internal(), arm_compute::test::validation::reference::prior_box_layer(), arm_compute::test::validation::reference::qlstm_layer_normalization(), arm_compute::test::validation::reference::quantization_layer(), arm_compute::test::validation::reference::range(), arm_compute::test::validation::reference::reorder_layer(), arm_compute::test::validation::reference::reorg_layer(), arm_compute::test::validation::reference::reshape_layer(), arm_compute::test::validation::reference::reverse(), arm_compute::test::colorconvert_helper::detail::rgb_to_yuv_calculation(), arm_compute::test::validation::reference::roi_align_layer(), arm_compute::test::validation::reference::roi_pool_layer(), arm_compute::test::validation::reference::safe_read(), arm_compute::test::validation::reference::scale_core(), arm_compute::test::validation::reference::select(), arm_compute::test::validation::reference::slice(), arm_compute::test::validation::reference::softmax_layer_generic(), arm_compute::test::validation::reference::space_to_batch(), arm_compute::test::validation::reference::space_to_depth(), arm_compute::test::colorconvert_helper::detail::store_rgb_from_src(), arm_compute::test::validation::reference::strided_slice(), arm_compute::test::validation::reference::table_lookup(), arm_compute::test::validation::tensor_elem_at(), arm_compute::test::validation::reference::tile(), arm_compute::test::validation::reference::transpose(), arm_compute::test::validation::transpose(), arm_compute::test::validation::transpose_matrix(), arm_compute::test::validation::reference::unstack(), arm_compute::test::validation::validate(), arm_compute::test::validation::validate_wrap(), arm_compute::test::validation::reference::weights_reshape(), arm_compute::test::validation::reference::winograd_filter_transform(), arm_compute::test::validation::reference::winograd_input_transform(), arm_compute::test::validation::reference::winograd_output_transform(), arm_compute::test::colorconvert_helper::detail::yuyv_to_rgb_calculation(), and arm_compute::test::validation::zeros().
 {
     return _shape;
 }
size()
size_t size () const override virtual
Total size of the tensor in bytes.
Returns
the total size of the tensor in bytes.
Implements IAccessor.
Definition at line 354 of file SimpleTensor.h.
Referenced by AssetsLibrary::fill(), and arm_compute::test::validation::reference::weights_reshape().
 {
     const size_t size = std::accumulate(_shape.cbegin(), _shape.cend(), 1, std::multiplies<size_t>());
     return size * element_size();
 }
Friends And Related Function Documentation
RawTensor
friend class RawTensor friend
Definition at line 107 of file SimpleTensor.h.
swap
void swap (SimpleTensor< U > & tensor1, SimpleTensor< U > & tensor2) friend
Swaps the content of the provided tensors.
Parameters
[in,out] tensor1 Tensor to be swapped.
[in,out] tensor2 Tensor to be swapped.
Definition at line 458 of file SimpleTensor.h.
 {
     // Use unqualified call to swap to enable ADL. But make std::swap available
     // as backup.
     using std::swap;
     swap(tensor1._shape, tensor2._shape);
     swap(tensor1._format, tensor2._format);
     swap(tensor1._data_type, tensor2._data_type);
     swap(tensor1._num_channels, tensor2._num_channels);
     swap(tensor1._quantization_info, tensor2._quantization_info);
     swap(tensor1._buffer, tensor2._buffer);
 }
The documentation for this class was generated from the following file:
tests/SimpleTensor.h