Compute Library: ClComponentDepthwiseConv2dSettings Class Reference
ClComponentDepthwiseConv2dSettings Class Reference
Component specific settings.
#include <ClComponentDepthwiseConv2d.h>
Public Member Functions
ClComponentDepthwiseConv2dSettings & export_input_to_cl_image (bool cl_image)
Set export_input_to_cl_image flag.
bool export_input_to_cl_image () const
Get export_input_to_cl_image flag.
ClComponentDepthwiseConv2dSettings & export_weights_to_cl_image (bool cl_image)
Set export_weights_to_cl_image flag.
bool export_weights_to_cl_image () const
Get export_weights_to_cl_image flag.
ClComponentDepthwiseConv2dSettings & fast_relaxed_math (bool fast_relaxed_math)
Set fast_relaxed_math flag.
bool fast_relaxed_math () const
Get fast_relaxed_math flag.
ClComponentDepthwiseConv2dSettings & is_fma_available (bool is_fma_available)
Set is_fma_available flag.
bool is_fma_available () const
Get is_fma_available flag.
ClComponentDepthwiseConv2dSettings & n0 (unsigned int n0)
Set N0: number of columns processed by each thread.
unsigned int n0 () const
Get N0: number of columns processed by each thread.
ClComponentDepthwiseConv2dSettings & m0 (unsigned int m0)
Set M0: number of rows processed by each thread.
unsigned int m0 () const
Set M0: number of rows processed by each thread.
Detailed Description
Component specific settings.
Definition at line 46 of file ClComponentDepthwiseConv2d.h.
Member Function Documentation
export_input_to_cl_image() [1/2]
Settings & export_input_to_cl_image (bool cl_image)
Set export_input_to_cl_image flag.
Definition at line 40 of file ClComponentDepthwiseConv2d.cpp.
Referenced by ClTemplateDepthwiseConv2d::declare_variables(), and ClComponentDepthwiseConv2d::validate().
 {
     _export_input_to_cl_image = cl_image;
     return *this;
 }
export_input_to_cl_image() [2/2]
bool export_input_to_cl_image () const
Get export_input_to_cl_image flag.
Definition at line 46 of file ClComponentDepthwiseConv2d.cpp.
 {
     return _export_input_to_cl_image;
 }
export_weights_to_cl_image() [1/2]
Settings & export_weights_to_cl_image (bool cl_image)
Set export_weights_to_cl_image flag.
Definition at line 51 of file ClComponentDepthwiseConv2d.cpp.
Referenced by ClTemplateDepthwiseConv2d::declare_variables(), and ClComponentDepthwiseConv2d::validate().
 {
     _export_weights_to_cl_image = cl_image;
     return *this;
 }
export_weights_to_cl_image() [2/2]
bool export_weights_to_cl_image () const
Get export_weights_to_cl_image flag.
Definition at line 57 of file ClComponentDepthwiseConv2d.cpp.
 {
     return _export_weights_to_cl_image;
 }
fast_relaxed_math() [1/2]
Settings & fast_relaxed_math (bool fast_relaxed_math)
Set fast_relaxed_math flag.
Definition at line 62 of file ClComponentDepthwiseConv2d.cpp.
References ClComponentDepthwiseConv2dSettings::fast_relaxed_math().
Referenced by ClTemplateDepthwiseConv2d::get_build_options().
 {
     _fast_relaxed_math = fast_relaxed_math;
     return *this;
 }
fast_relaxed_math() [2/2]
bool fast_relaxed_math () const
Get fast_relaxed_math flag.
Definition at line 68 of file ClComponentDepthwiseConv2d.cpp.
Referenced by ClComponentDepthwiseConv2dSettings::fast_relaxed_math().
 {
     return _fast_relaxed_math;
 }
is_fma_available() [1/2]
Settings & is_fma_available (bool is_fma_available)
Set is_fma_available flag.
Definition at line 73 of file ClComponentDepthwiseConv2d.cpp.
References ClComponentDepthwiseConv2dSettings::is_fma_available().
Referenced by ClTemplateDepthwiseConv2d::get_component_code().
 {
     _is_fma_available = is_fma_available;
     return *this;
 }
is_fma_available() [2/2]
bool is_fma_available () const
Get is_fma_available flag.
Definition at line 79 of file ClComponentDepthwiseConv2d.cpp.
Referenced by ClComponentDepthwiseConv2dSettings::is_fma_available().
 {
     return _is_fma_available;
 }
m0() [1/2]
Settings & m0 (unsigned int m0)
Set M0: number of rows processed by each thread.
Definition at line 95 of file ClComponentDepthwiseConv2d.cpp.
References ClComponentDepthwiseConv2dSettings::m0().
Referenced by ClTemplateDepthwiseConv2d::get_build_options(), ClTemplateDepthwiseConv2d::get_window(), and ClComponentDepthwiseConv2d::validate().
 {
     _m0 = m0;
     return *this;
 }
m0() [2/2]
unsigned int m0 () const
Set M0: number of rows processed by each thread.
Definition at line 101 of file ClComponentDepthwiseConv2d.cpp.
Referenced by ClComponentDepthwiseConv2dSettings::m0().
 {
     return _m0;
 }
n0() [1/2]
Settings & n0 (unsigned int n0)
Set N0: number of columns processed by each thread.
Definition at line 84 of file ClComponentDepthwiseConv2d.cpp.
References ClComponentDepthwiseConv2dSettings::n0().
Referenced by ClTemplateDepthwiseConv2d::get_build_options(), ClTemplateDepthwiseConv2d::get_window(), and ClComponentDepthwiseConv2d::validate().
 {
     _n0 = n0;
     return *this;
 }
n0() [2/2]
unsigned int n0 () const
Get N0: number of columns processed by each thread.
Definition at line 90 of file ClComponentDepthwiseConv2d.cpp.
Referenced by ClComponentDepthwiseConv2dSettings::n0().
 {
     return _n0;
 }
The documentation for this class was generated from the following files:
src/dynamic_fusion/sketch/gpu/components/cl/ClComponentDepthwiseConv2d.h
src/dynamic_fusion/sketch/gpu/components/cl/ClComponentDepthwiseConv2d.cpp