Compute Library: CLTuningParams Class Reference
CLTuningParams Class Reference
< OpenCL tuner parameters
#include <CLTuningParams.h>
Public Member Functions
CLTuningParams (const CLTuningParams &tuning_params)
CLTuningParams (unsigned int lws_x=0, unsigned int lws_y=0, unsigned int lws_z=0, int wbsm=0)
CLTuningParams (cl::NDRange lws, cl_int wbsm=0)
CLTuningParams (cl_int wbsm)
CLTuningParams & operator= (const CLTuningParams &other)
void set_lws (cl::NDRange lws)
cl::NDRange get_lws () const
void set_wbsm (cl_int wbsm)
cl_int get_wbsm () const
std::string to_string (CLTuningInfo tuning_info)
bool from_string (CLTuningInfo tuning_info, std::string tuning_params_string)
Detailed Description
< OpenCL tuner parameters
Definition at line 36 of file CLTuningParams.h.
Constructor & Destructor Documentation
CLTuningParams() [1/4]
CLTuningParams (const CLTuningParams & tuning_params) inline
Definition at line 39 of file CLTuningParams.h.
         : _lws(tuning_params._lws), _wbsm(tuning_params._wbsm)
     {
     }
CLTuningParams() [2/4]
CLTuningParams (unsigned int lws_x = 0, unsigned int lws_y = 0, unsigned int lws_z = 0, int wbsm = 0) inline
Definition at line 44 of file CLTuningParams.h.
         : _lws(lws_x, lws_y, lws_z), _wbsm(wbsm)
     {
     }
CLTuningParams() [3/4]
CLTuningParams (cl::NDRange lws, cl_int wbsm = 0) inline
Definition at line 48 of file CLTuningParams.h.
         : _lws(lws), _wbsm(wbsm)
     {
     }
CLTuningParams() [4/4]
CLTuningParams (cl_int wbsm) inline
Definition at line 53 of file CLTuningParams.h.
         : CLTuningParams(cl::NullRange, wbsm)
     {
     }
Member Function Documentation
from_string()
bool from_string (CLTuningInfo tuning_info, std::string tuning_params_string) inline
Definition at line 95 of file CLTuningParams.h.
References arm_compute::test::validation::ss(), arm_compute::support::cpp11::stoi(), and CLTuningInfo::tune_wbsm.
Referenced by CLTuner::load_from_file().
     {
         std::replace(tuning_params_string.begin(), tuning_params_string.end(), ';', ' ');
         std::vector<std::string> array;
         std::stringstream        ss(tuning_params_string);
         std::string              temp;
         while(ss >> temp)
         {
             array.push_back(temp);
         }
         // Read 3 values for lws
         if(array.size() < 3)
         {
             return false;
         }
         const unsigned int lws_0 = support::cpp11::stoi(array[0]);
         const unsigned int lws_1 = support::cpp11::stoi(array[1]);
         const unsigned int lws_2 = support::cpp11::stoi(array[2]);
         if(lws_0 == 0 && lws_1 == 0 && lws_2 == 0)
         {
             // If lws values are 0, cl::NullRange has to be used
             // otherwise the lws object will be badly created
             _lws = cl::NullRange;
         }
         else
         {
             _lws = cl::NDRange(lws_0, lws_1, lws_2);
         }
         array.erase(array.begin(), array.begin() + 3);
         if(tuning_info.tune_wbsm)
         {
             if(array.size() < 1)
             {
                 return false;
             }
             _wbsm = support::cpp11::stoi(array[0]);
             array.erase(array.begin());
         }
         return true;
     }
get_lws()
cl::NDRange get_lws () const inline
Definition at line 69 of file CLTuningParams.h.
Referenced by CLTuner::add_tuning_params(), ICLKernel::lws_hint(), and CLTuner::tune_kernel_dynamic().
     {
         return _lws;
     }
get_wbsm()
cl_int get_wbsm () const inline
Definition at line 79 of file CLTuningParams.h.
Referenced by CLTuner::add_tuning_params(), CLTuner::tune_kernel_dynamic(), and ICLKernel::wbsm_hint().
     {
         return _wbsm;
     }
operator=()
CLTuningParams& operator= (const CLTuningParams & other) inline
Definition at line 57 of file CLTuningParams.h.
     {
         _lws = other._lws;
         _wbsm = other._wbsm;
         return *this;
     }
set_lws()
void set_lws (cl::NDRange lws) inline
Definition at line 64 of file CLTuningParams.h.
Referenced by CLTuner::add_tuning_params(), and ICLKernel::set_lws_hint().
     {
         _lws = lws;
     }
set_wbsm()
void set_wbsm (cl_int wbsm) inline
Definition at line 74 of file CLTuningParams.h.
Referenced by CLTuner::add_tuning_params(), and ICLKernel::set_wbsm_hint().
     {
         _wbsm = wbsm;
     }
to_string()
std::string to_string (CLTuningInfo tuning_info) inline
Definition at line 84 of file CLTuningParams.h.
References arm_compute::support::cpp11::to_string(), and CLTuningInfo::tune_wbsm.
Referenced by CLTuner::save_to_file().
     {
         std::string tuning_params_string = "";
         tuning_params_string += ";" + support::cpp11::to_string(_lws[0]) + ";" + support::cpp11::to_string(_lws[1]) + ";" + support::cpp11::to_string(_lws[2]);
         if(tuning_info.tune_wbsm)
         {
             tuning_params_string += ";" + support::cpp11::to_string(_wbsm);
         }
         return tuning_params_string;
     }
The documentation for this class was generated from the following file:
arm_compute/runtime/CL/CLTuningParams.h