Compute Library: NEBoundingBoxTransform Class Reference
NEBoundingBoxTransform Class Reference
Basic function to run NEBoundingBoxTransformKernel.
#include <NEBoundingBoxTransform.h>
Public Member Functions
void configure (const ITensor *boxes, ITensor *pred_boxes, const ITensor *deltas, const BoundingBoxTransformInfo &info)
Set the input and output tensors.
Public Member Functions inherited from INESimpleFunctionNoBorder
INESimpleFunctionNoBorder (IRuntimeContext *ctx=nullptr)
Constructor.
INESimpleFunctionNoBorder (const INESimpleFunctionNoBorder &)=delete
Prevent instances of this class from being copied (As this class contains pointers)
INESimpleFunctionNoBorder (INESimpleFunctionNoBorder &&)=default
Default move constructor.
INESimpleFunctionNoBorder & operator= (const INESimpleFunctionNoBorder &)=delete
Prevent instances of this class from being copied (As this class contains pointers)
INESimpleFunctionNoBorder & operator= (INESimpleFunctionNoBorder &&)=default
Default move assignment operator.
~INESimpleFunctionNoBorder ()
Default destructor.
void run () override final
Run the kernels contained in the function.
Public Member Functions inherited from IFunction
virtual ~IFunction ()=default
Destructor.
virtual void prepare ()
Prepare the function for executing.
Static Public Member Functions
static Status validate (const ITensorInfo *boxes, const ITensorInfo *pred_boxes, const ITensorInfo *deltas, const BoundingBoxTransformInfo &info)
Static function to check if given info will lead to a valid configuration of NEBoundingBoxTransform.
Detailed Description
Basic function to run NEBoundingBoxTransformKernel.
Definition at line 36 of file NEBoundingBoxTransform.h.
Member Function Documentation
configure()
void configure (const ITensor * boxes, ITensor * pred_boxes, const ITensor * deltas, const BoundingBoxTransformInfo & info)
Set the input and output tensors.
Valid data layouts:
NHWC
NCHW
Valid data type configurations:
src0 src1 dst
QASYMM16 QASYMM8 QASYMM16
F16 F16 F16
F32 F32 F32
Parameters
[in] boxes Source tensor. Bounding box proposals in pixel coordinates. Size(M, 4), format [x1, y1, x2, y2]. Data types supported: QASYMM16/F16/F32.
[out] pred_boxes Destination tensor. Pixel coordinates of the transformed bounding boxes. Size (M, 4*K), format [x1, y1, x2, y2]. Data types supported: Same as input
[in] deltas Bounding box translations and scales. Size (M, 4*K), format [dx, dy, dw, dh], K is the number of classes. Data types supported: QASYMM8 if input is QASYMM16, otherwise same as input.
[in] info Contains BoundingBox operation information described in BoundingBoxTransformInfo.
Note
Only single image prediction is supported. Height and Width (and scale) of the image will be contained in the BoundingBoxTransformInfo struct.
Definition at line 30 of file NEBoundingBoxTransform.cpp.
References ARM_COMPUTE_LOG_PARAMS, and arm_compute::test::validation::k.
Referenced by NEGenerateProposalsLayer::configure().
 {
     ARM_COMPUTE_LOG_PARAMS(boxes, pred_boxes, deltas, info);
     // Configure Bounding Box kernel
     auto k = std::make_unique<NEBoundingBoxTransformKernel>();
     k->configure(boxes, pred_boxes, deltas, info);
     _kernel = std::move(k);
 }
validate()
Status validate (const ITensorInfo * boxes, const ITensorInfo * pred_boxes, const ITensorInfo * deltas, const BoundingBoxTransformInfo & info) static
Static function to check if given info will lead to a valid configuration of NEBoundingBoxTransform.
Parameters
[in] boxes Source tensor info. Bounding box proposals in pixel coordinates. Size(M, 4), format [x1, y1, x2, y2]. Data types supported: QASYMM16/F16/F32.
[in] pred_boxes Destination tensor info. Pixel coordinates of the transformed bounding boxes. Size (M, 4*K), format [x1, y1, x2, y2]. Data types supported: Same as input
[in] deltas Bounding box translations and scales. Size (M, 4*K), format [dx, dy, dw, dh], K is the number of classes. Data types supported: QASYMM8 if input is QASYMM16, otherwise same as input.
[in] info Contains BoundingBox operation information described in BoundingBoxTransformInfo.
Note
Only single image prediction is supported. Height and Width (and scale) of the image will be contained in the BoundingBoxTransformInfo struct.
Returns
a Status
Definition at line 39 of file NEBoundingBoxTransform.cpp.
References NEBoundingBoxTransformKernel::validate().
Referenced by NEGenerateProposalsLayer::validate().
 {
     return NEBoundingBoxTransformKernel::validate(boxes, pred_boxes, deltas, info);
 }
The documentation for this class was generated from the following files:
arm_compute/runtime/NEON/functions/NEBoundingBoxTransform.h
src/runtime/NEON/functions/NEBoundingBoxTransform.cpp