Compute Library: ClComponentCast Class Reference
ClComponentCast Class Reference final
#include <ClComponentCast.h>
Public Types
using Attributes = CastAttributes
Attributes are a set of backend-agnostic parameters that define what a component does.
using Settings = ClComponentCastSettings
Settings are a set of backend-specific parameters that influence the implementation of a component.
Public Types inherited from IGpuKernelComponent
using Properties = KernelProperties
Public Member Functions
ClComponentCast (ComponentId id, const Properties &properties, const ArgumentPack< ITensorInfo > &tensors, const Attributes &attributes, const Settings &settings)
Constructor.
~ClComponentCast () override
Destructor.
ClComponentCast (const ClComponentCast &component)=delete
Prevent instances of this class from being copy constructed.
ClComponentCast & operator= (const ClComponentCast &component)=delete
Prevent instances of this class from being copied.
ClComponentCast (ClComponentCast &&component)=default
Allow instances of this class to be move constructed.
ClComponentCast & operator= (ClComponentCast &&component)=default
Allow instances of this class to be moved.
const IGpuTemplateComponentWriter * template_writer () const override
Get template writer for the component.
GpuComponentType type () const override
Get component type.
Public Member Functions inherited from IGpuKernelComponent
IGpuKernelComponent (ComponentId id, const Properties &properties, const ArgumentPack< ITensorInfo > &tensors)
Constructor.
virtual ~IGpuKernelComponent ()
Destructor.
ComponentId id () const
Get component id.
ArgumentPack< ITensorInfo > tensors () const
Get tensor arguments.
Properties properties () const
Get properties.
Static Public Member Functions
static Status validate (const Properties &properties, const ArgumentPack< ITensorInfo > &tensors, const Attributes &attributes, const Settings &settings)
Validate the component.
Detailed Description
Definition at line 53 of file ClComponentCast.h.
Member Typedef Documentation
Attributes
using Attributes = CastAttributes
Attributes are a set of backend-agnostic parameters that define what a component does.
Definition at line 57 of file ClComponentCast.h.
Settings
using Settings = ClComponentCastSettings
Settings are a set of backend-specific parameters that influence the implementation of a component.
Definition at line 59 of file ClComponentCast.h.
Constructor & Destructor Documentation
ClComponentCast() [1/3]
ClComponentCast (ComponentId id, const Properties & properties, const ArgumentPack< ITensorInfo > & tensors, const Attributes & attributes, const Settings & settings)
Constructor.
Similar to ClComponentCast::validate()
Definition at line 63 of file ClComponentCast.cpp.
References ARM_COMPUTE_UNUSED, IGpuKernelComponent::id(), IGpuKernelComponent::properties(), and IGpuKernelComponent::tensors().
     : IGpuKernelComponent{ id, properties, tensors },
       _component_writer{ std::make_unique<ClTemplateCast>(id, tensors, attributes) }
 {
     ARM_COMPUTE_UNUSED(attributes, settings);
 }
~ClComponentCast()
~ClComponentCast () override
Destructor.
Definition at line 73 of file ClComponentCast.cpp.
 {
 }
ClComponentCast() [2/3]
ClComponentCast (const ClComponentCast & component) delete
Prevent instances of this class from being copy constructed.
ClComponentCast() [3/3]
ClComponentCast (ClComponentCast && component) default
Allow instances of this class to be move constructed.
Member Function Documentation
operator=() [1/2]
ClComponentCast& operator= (const ClComponentCast & component) delete
Prevent instances of this class from being copied.
operator=() [2/2]
ClComponentCast& operator= (ClComponentCast && component) default
Allow instances of this class to be moved.
template_writer()
const IGpuTemplateComponentWriter * template_writer () const override virtual
Get template writer for the component.
Implements IGpuKernelComponent.
Definition at line 76 of file ClComponentCast.cpp.
 {
     return _component_writer.get();
 }
type()
GpuComponentType type () const inline override virtual
Get component type.
Implements IGpuKernelComponent.
Definition at line 121 of file ClComponentCast.h.
References arm_compute::experimental::dynamic_fusion::Simple.
     {
         return GpuComponentType::Simple;
     }
validate()
Status validate (const Properties & properties, const ArgumentPack< ITensorInfo > & tensors, const Attributes & attributes, const Settings & settings) static
Validate the component.
Parameters
[in] properties Component properties Properties
[in,out] tensors Tensor arguments to the component
[in] attributes Component attributes Attributes
[in] settings Component settings Settings
Returns
Status Validation results
Tensor argument names:
ACL_SRC_0: Input
ACL_DST_0: Output
Tensor argument constness:
ACL_SRC_0: Const
ACL_DST_0: Const
Valid data layouts:
All
Valid data type configurations:
ACL_SRC_0 ACL_DST_0
U8 S8, U16, S16, U32, S32, F16, F32
U16 U8, S8, S16, U32, S32, F16, F32
S16 U8, S8, U16, U32, S32, F16, F32
U32 U8, S8, U16, S16, S32, F16, F32
S32 U8, S8, U16, S16, U32, F16, F32
F16 U8, S8, U16, S16, U32, S32, F32
F32 U8, S8, U16, S16, U32, S32, F16
Definition at line 37 of file ClComponentCast.cpp.
References arm_compute::ACL_DST_0, arm_compute::ACL_SRC_0, ARM_COMPUTE_RETURN_ERROR_ON, ARM_COMPUTE_RETURN_ERROR_ON_F16_UNSUPPORTED, ARM_COMPUTE_RETURN_ERROR_ON_MISMATCHING_SHAPES, ARM_COMPUTE_RETURN_ERROR_ON_MSG, ARM_COMPUTE_RETURN_ERROR_ON_NULLPTR, ARM_COMPUTE_UNUSED, CastAttributes::data_type(), ITensorInfo::data_type(), arm_compute::test::validation::dst, ArgumentPack< T >::get_const_tensor(), arm_compute::test::validation::src, and ITensorInfo::total_size().
 {
     ARM_COMPUTE_UNUSED(properties, attributes, settings);
     const ITensorInfo *src = tensors.get_const_tensor(TensorType::ACL_SRC_0);
     const ITensorInfo *dst = tensors.get_const_tensor(TensorType::ACL_DST_0);
     ARM_COMPUTE_RETURN_ERROR_ON_F16_UNSUPPORTED(src);
     ARM_COMPUTE_RETURN_ERROR_ON_F16_UNSUPPORTED(dst);
     ARM_COMPUTE_RETURN_ERROR_ON_NULLPTR(src, dst);
     ARM_COMPUTE_RETURN_ERROR_ON(src == dst);
     ARM_COMPUTE_RETURN_ERROR_ON_MSG(src->data_type() == attributes.data_type(), "input and target data types should be different");
     // Validate in case of configured dst
     if(dst->total_size() > 0)
     {
         ARM_COMPUTE_RETURN_ERROR_ON_MISMATCHING_SHAPES(src, dst);
         ARM_COMPUTE_RETURN_ERROR_ON_MSG(dst->data_type() != attributes.data_type(), "dst and target data types should be same");
     }
     return Status{};
 }
The documentation for this class was generated from the following files:
src/dynamic_fusion/sketch/gpu/components/cl/ClComponentCast.h
src/dynamic_fusion/sketch/gpu/components/cl/ClComponentCast.cpp