Compute Library: ClTemplateStore Class Reference
ClTemplateStore Class Reference final
#include <ClTemplateStore.h>
Public Member Functions
ClTemplateStore (ComponentId id, const ArgumentPack< ITensorInfo > &tensors)
Constructor.
ClTemplateStore (const ClTemplateStore &store)=delete
Prevent instances of this class from being copy constructed.
ClTemplateStore & operator= (const ClTemplateStore &store)=delete
Prevent instances of this class from being copied.
ClTemplateStore (ClTemplateStore &&store)=default
Allow instances of this class to be move constructed.
ClTemplateStore & operator= (ClTemplateStore &&store)=default
Allow instances of this class to be moved.
std::string get_name () const override
Generate kernel component name.
std::string get_component_code (const ComponentGroup &comp_group) const override
Generate kernel component code template.
void declare_variables (GpuKernelVariableTable &vtable, const ComponentGroup &comp_group) const override
Declare all variables used by the component in the vtable.
TagLUT get_tag_lut (const GpuKernelVariableTable &vtable, const ComponentGroup &comp_group) const override
Generate the tag look-up table used to instantiate the component code.
Public Member Functions inherited from IGpuTemplateComponentWriter
IGpuTemplateComponentWriter (ComponentId id, const ArgumentPack< ITensorInfo > &tensors)
Constructor.
virtual ~IGpuTemplateComponentWriter ()
Destructor.
virtual std::string get_additional_macros () const
Generate additional macros used in the component.
virtual CLBuildOptions get_build_options (const ComponentGroup &comp_group) const
Generate the build options used in the component.
virtual std::string get_config_id () const
Generate the component config id string used for tuning.
virtual std::set< std::string > get_headers_list () const
Generate the header list used in the component.
virtual Window get_window () const
Generate the execution window for the component.
ArgumentPack< ITensorInfo > tensors () const
Get tensor arguments.
ComponentId id () const
Get component id.
Additional Inherited Members
Public Types inherited from IGpuTemplateComponentWriter
using ComponentGroup = GpuKernelComponentGroup
Static Public Attributes inherited from IGpuTemplateComponentWriter
static constexpr GpuKernelArgumentInfo::Type common_tensor_type = GpuKernelArgumentInfo::Type::Tensor_4D_t_Buffer
For now all kernel intermeditate/destination tensors are expected to be of type Tensor_4D_t_Buffer.
Detailed Description
Definition at line 37 of file ClTemplateStore.h.
Constructor & Destructor Documentation
ClTemplateStore() [1/3]
ClTemplateStore (ComponentId id, const ArgumentPack< ITensorInfo > & tensors)
Constructor.
Parameters
[in] id Component id
[in] tensors Tensor arguments to the components
Definition at line 34 of file ClTemplateStore.cpp.
References arm_compute::ACL_DST_0, arm_compute::ACL_SRC_0, IGpuTemplateComponentWriter::id(), and IGpuTemplateComponentWriter::tensors().
     : IGpuTemplateComponentWriter{ id, tensors }, _src{}, _dst{}
 {
     _src = this->tensors().get_const_tensor(TensorType::ACL_SRC_0);
     _dst = this->tensors().get_const_tensor(TensorType::ACL_DST_0);
 }
ClTemplateStore() [2/3]
ClTemplateStore (const ClTemplateStore & store) delete
Prevent instances of this class from being copy constructed.
ClTemplateStore() [3/3]
ClTemplateStore (ClTemplateStore && store) default
Allow instances of this class to be move constructed.
Member Function Documentation
declare_variables()
void declare_variables (GpuKernelVariableTable & vtable, const ComponentGroup & comp_group) const override virtual
Declare all variables used by the component in the vtable.
Parameters
[out] vtable Variable table
[in] comp_group Component group of which the component is a part of
Implements IGpuTemplateComponentWriter.
Definition at line 62 of file ClTemplateStore.cpp.
References GpuKernelVariableTable::declare_variable(), and GpuKernelArgumentInfo::Tensor_4D_t_Buffer.
 {
     vtable.declare_variable(
         comp_group,
         _src,
         GpuKernelArgumentInfo(GpuKernelArgumentInfo::Type::Tensor_4D_t_Buffer),
         "src");
     vtable.declare_variable(
         comp_group,
         _dst,
         GpuKernelArgumentInfo(GpuKernelArgumentInfo::Type::Tensor_4D_t_Buffer),
         "dst");
 }
get_component_code()
std::string get_component_code (const ComponentGroup & comp_group) const override virtual
Generate kernel component code template.
Parameters
[in] comp_group Component group of which the component is a part of
Returns
std::string Component code
Implements IGpuTemplateComponentWriter.
Definition at line 46 of file ClTemplateStore.cpp.
References ARM_COMPUTE_UNUSED.
 {
     ARM_COMPUTE_UNUSED(comp_group);
     return R"_(
 //------------------ START KERNEL {{meta_kernel_id}} STORE ---------------------
 {
     bool x_cond = PARTIAL_N0 != 0 && get_global_id(0) == 0;
     T_STORE_INDIRECT_WIDTH_SELECT({{DST_DATA_TYPE}}, M0, N0, PARTIAL_N0, {{DST_TENSOR_TYPE}}, {{dst}}, g_ind_0, {{dst}}_stride_y, x_cond, {{src}}, g_dst_indirect_y);
 //------------------ END KERNEL {{meta_kernel_id}} STORE ---------------------
 }
 )_";
 }
get_name()
std::string get_name () const override virtual
Generate kernel component name.
Implements IGpuTemplateComponentWriter.
Definition at line 41 of file ClTemplateStore.cpp.
 {
     return "store";
 }
get_tag_lut()
TagLUT get_tag_lut (const GpuKernelVariableTable & vtable, const ComponentGroup & comp_group) const override virtual
Generate the tag look-up table used to instantiate the component code.
Parameters
[in] vtable Variable table
[in] comp_group Component group of which the component is a part of
Returns
TagLUT Tag lookup table
Implements IGpuTemplateComponentWriter.
Definition at line 76 of file ClTemplateStore.cpp.
References ARM_COMPUTE_UNUSED, ITensorInfo::data_type(), GpuKernelVariableTable::get_variable(), and IGpuTemplateComponentWriter::id().
 {
     TagLUT lut{};
     // Arguments and global shared variables
     lut["src"] = vtable.get_variable(_src);
     lut["dst"] = vtable.get_variable(_dst);
     // Local build options
     lut["meta_kernel_id"]  = id();
     lut["DST_TENSOR_TYPE"] = "BUFFER";
     lut["DST_DATA_TYPE"]   = _dst->data_type();
     ARM_COMPUTE_UNUSED(comp_group);
     return lut;
 }
operator=() [1/2]
ClTemplateStore& operator= (const ClTemplateStore & store) delete
Prevent instances of this class from being copied.
operator=() [2/2]
ClTemplateStore& operator= (ClTemplateStore && store) default
Allow instances of this class to be moved.
The documentation for this class was generated from the following files:
src/dynamic_fusion/sketch/gpu/template_writer/cl/ClTemplateStore.h
src/dynamic_fusion/sketch/gpu/template_writer/cl/ClTemplateStore.cpp