Compute Library: ClGemmDefaultConfigNativeValhall Class Reference
ClGemmDefaultConfigNativeValhall Class Reference final
Valhall based OpenCL GEMMNative configuration.
#include <ClGemmDefaultConfigNativeValhall.h>
Public Member Functions
ClGemmDefaultConfigNativeValhall (GPUTarget gpu)
Constructor.
std::pair< GEMMLHSMatrixInfo, GEMMRHSMatrixInfo > configure (unsigned int m, unsigned int n, unsigned int k, unsigned int b, DataType data_type) override
Given M, N, K and B, this method returns the GEMMLHSMatrixInfo and GEMMRHSMatrixInfo to be used.
Public Member Functions inherited from IClGemmKernelConfig
IClGemmKernelConfig (GPUTarget arch)
Constructor.
ARM_COMPUTE_DISALLOW_COPY_ALLOW_MOVE (IClGemmKernelConfig)
virtual ~IClGemmKernelConfig ()=default
Virtual destructor.
Detailed Description
Valhall based OpenCL GEMMNative configuration.
Definition at line 38 of file ClGemmDefaultConfigNativeValhall.h.
Constructor & Destructor Documentation
ClGemmDefaultConfigNativeValhall()
ClGemmDefaultConfigNativeValhall (GPUTarget gpu)
Constructor.
Parameters
[in] gpu GPU target
Definition at line 41 of file ClGemmDefaultConfigNativeValhall.cpp.
Referenced by ClGemmDefaultConfigNativeValhall::configure().
     : IClGemmKernelConfig(gpu)
 {
 }
Member Function Documentation
configure()
std::pair< GEMMLHSMatrixInfo, GEMMRHSMatrixInfo > configure (unsigned int m, unsigned int n, unsigned int k, unsigned int b, DataType data_type) override virtual
Given M, N, K and B, this method returns the GEMMLHSMatrixInfo and GEMMRHSMatrixInfo to be used.
Parameters
[in] m Number of rows LHS matrix
[in] n Number of columns RHS matrix
[in] k Number of columns LHS matrix or number of rows RHS matrix
[in] b Batch size
[in] data_type Data type
Implements IClGemmKernelConfig.
Definition at line 46 of file ClGemmDefaultConfigNativeValhall.cpp.
References ARM_COMPUTE_ERROR_ON_MSG, ARM_COMPUTE_UNUSED, arm_compute::test::validation::b, ClGemmDefaultConfigNativeValhall::ClGemmDefaultConfigNativeValhall(), arm_compute::opencl::kernels::gemm::configure_lhs_rhs_info(), arm_compute::dot8_supported(), CLKernelLibrary::get(), CLGEMMConfigArray< T >::get_function(), arm_compute::test::validation::k, arm_compute::test::validation::m, and arm_compute::test::validation::n.
 {
     using ConfigurationFunctionExecutorPtr = std::pair<GEMMLHSMatrixInfo, GEMMRHSMatrixInfo> (ClGemmDefaultConfigNativeValhall::*)(unsigned int m, unsigned int n, unsigned int k,
                                              unsigned int b);
     CLGEMMConfigArray<ConfigurationFunctionExecutorPtr> configs_default(&ClGemmDefaultConfigNativeValhall::configure_G77_f32,
                                                                         &ClGemmDefaultConfigNativeValhall::configure_G77_f16,
                                                                         &ClGemmDefaultConfigNativeValhall::configure_G77_u8);
     auto func = configs_default.get_function(data_type);
     ARM_COMPUTE_ERROR_ON_MSG(func == nullptr, "Data type not support for GEMM");
     return (this->*func)(m, n, k, b);
 }
The documentation for this class was generated from the following files:
src/gpu/cl/kernels/gemm/native/ClGemmDefaultConfigNativeValhall.h
src/gpu/cl/kernels/gemm/native/ClGemmDefaultConfigNativeValhall.cpp