Compute Library: Pool2dAttributes Class Reference
Pool2dAttributes Class Reference
Attributes are backend-agnostic parameters (in addition to the input/output tensors) of an operator.
#include <Pool2dAttributes.h>
Public Member Functions
PoolingType pool_type () const
Pool2dAttributes pool_type (PoolingType pool_type)
Size2D pool_size () const
Pool2dAttributes pool_size (const Size2D &pool_size)
Padding2D pad () const
Pool2dAttributes pad (const Padding2D &padding)
Size2D stride () const
Pool2dAttributes stride (const Size2D &stride)
bool exclude_padding () const
Pool2dAttributes exclude_padding (bool exclude_padding)
Detailed Description
Attributes are backend-agnostic parameters (in addition to the input/output tensors) of an operator.
Definition at line 38 of file Pool2dAttributes.h.
Member Function Documentation
exclude_padding() [1/2]
bool exclude_padding () const
Definition at line 78 of file Pool2dAttributes.cpp.
Referenced by arm_compute::experimental::dynamic_fusion::convert_pool_attr_to_pool_info(), Pool2dAttributes::exclude_padding(), ClTemplatePool2d::get_component_code(), GpuPool2d::is_supported_op(), and arm_compute::operator<<().
 {
     return _exclude_padding;
 }
exclude_padding() [2/2]
Pool2dAttributes exclude_padding (bool exclude_padding)
Definition at line 83 of file Pool2dAttributes.cpp.
References Pool2dAttributes::exclude_padding().
 {
     _exclude_padding = exclude_padding;
     return *this;
 }
pad() [1/2]
Padding2D pad () const
Definition at line 45 of file Pool2dAttributes.cpp.
Referenced by arm_compute::experimental::dynamic_fusion::convert_pool_attr_to_pool_info(), ClTemplatePool2d::get_tag_lut(), arm_compute::operator<<(), and Pool2dAttributes::pad().
 {
     return _pad;
 }
pad() [2/2]
Pool2dAttributes pad (const Padding2D & padding)
Definition at line 50 of file Pool2dAttributes.cpp.
References Pool2dAttributes::pad().
 {
     _pad = pad;
     return *this;
 }
pool_size() [1/2]
Size2D pool_size () const
Definition at line 56 of file Pool2dAttributes.cpp.
Referenced by arm_compute::experimental::dynamic_fusion::convert_pool_attr_to_pool_info(), ClTemplatePool2d::get_component_code(), ClTemplatePool2d::get_tag_lut(), arm_compute::operator<<(), and Pool2dAttributes::pool_size().
 {
     return _pool_size;
 }
pool_size() [2/2]
Pool2dAttributes pool_size (const Size2D & pool_size)
Definition at line 61 of file Pool2dAttributes.cpp.
References Pool2dAttributes::pool_size().
 {
     _pool_size = pool_size;
     return *this;
 }
pool_type() [1/2]
PoolingType pool_type () const
Definition at line 34 of file Pool2dAttributes.cpp.
Referenced by arm_compute::experimental::dynamic_fusion::convert_pool_attr_to_pool_info(), ClTemplatePool2d::get_component_code(), ClTemplatePool2d::get_tag_lut(), arm_compute::operator<<(), Pool2dAttributes::pool_type(), and ClComponentPool2d::validate().
 {
     return _pool_type;
 }
pool_type() [2/2]
Pool2dAttributes pool_type (PoolingType pool_type)
Definition at line 39 of file Pool2dAttributes.cpp.
References Pool2dAttributes::pool_type().
 {
     _pool_type = pool_type;
     return *this;
 }
stride() [1/2]
Size2D stride () const
Definition at line 67 of file Pool2dAttributes.cpp.
Referenced by arm_compute::experimental::dynamic_fusion::convert_pool_attr_to_pool_info(), ClTemplatePool2d::get_tag_lut(), arm_compute::operator<<(), and Pool2dAttributes::stride().
 {
     return _stride;
 }
stride() [2/2]
Pool2dAttributes stride (const Size2D & stride)
Definition at line 72 of file Pool2dAttributes.cpp.
References Pool2dAttributes::stride().
 {
     _stride = stride;
     return *this;
 }
The documentation for this class was generated from the following files:
arm_compute/dynamic_fusion/sketch/attributes/Pool2dAttributes.h
src/dynamic_fusion/sketch/attributes/Pool2dAttributes.cpp