Compute Library: GpuOutput Class Reference
GpuOutput Class Reference final
Operator interface.
#include <GpuOutput.h>
Static Public Member Functions
static void create_op (GpuWorkloadSketch &sketch, ITensorInfo *src, ITensorInfo *dst)
Create an operator and fuse it into the workload sketch.
static Status is_supported_op (const GpuWorkloadContext &context, const ITensorInfo *src, const ITensorInfo *dst)
Check if the operator configuration is supported, irrespective of fusion.
static Status validate_op (const GpuWorkloadSketch &sketch, const ITensorInfo *src, const ITensorInfo *dst)
Validate the operator and check if the its configuration is supported and if it can be fused into the workload sketch.
Detailed Description
Operator interface.
Definition at line 41 of file GpuOutput.h.
Member Function Documentation
create_op()
void create_op (GpuWorkloadSketch & sketch, ITensorInfo * src, ITensorInfo * dst) static
Create an operator and fuse it into the workload sketch.
Note
If validate_op() fails, the creation also fails and may throw an error.
If validate_op() fails, sketch remains unchanged and valid.
Valid data type configurations:
Any
Valid data layouts:
Any
Parameters
[in,out] sketch Workload sketch into which the operator will be fused.
[in,out] src Source tensor info.
[in,out] dst Destination tensor info. If an uninitialized ITensorInfo is passed in, it will be auto-initialized.
Definition at line 93 of file GpuOutput.cpp.
References arm_compute::ACL_DST_0, arm_compute::ACL_SRC_0, ArgumentPack< T >::add_const_tensor(), GpuOperatorGroup::add_operator(), ARM_COMPUTE_ERROR, ARM_COMPUTE_ERROR_ON, ARM_COMPUTE_ERROR_THROW_ON, ARM_COMPUTE_LOG_PARAMS, arm_compute::auto_init_if_empty(), GpuWorkloadSketch::Implementation::component_graph(), GpuWorkloadSketch::Implementation::context(), GpuWorkloadSketch::implementation(), GpuOperatorGroup::new_operator(), arm_compute::experimental::dynamic_fusion::OpenCL, GpuWorkloadSketch::Implementation::operator_group(), UnitWorkloadStage::Run, KernelProperties::stage(), and GpuOutput::validate_op().
Referenced by arm_compute::test::validation::TEST_CASE().
 {
     ARM_COMPUTE_LOG_PARAMS(src, dst);
     ARM_COMPUTE_ERROR_THROW_ON(GpuOutput::validate_op(sketch, src, dst));
     // Auto initialize dst tensor info if empty
     auto_init_if_empty(*dst, *src);
     // Translate into components and add to component graph
     auto      &comp_graph = sketch.implementation().component_graph();
     const auto sketch_ctx = sketch.implementation().context();
     if(sketch_ctx->gpu_language() == GpuLanguage::OpenCL)
     {
         ARM_COMPUTE_ERROR_ON(sketch_ctx->cl_compile_context() == nullptr);
         // Add store component
         {
             IGpuKernelComponent::Properties properties;
             properties.stage(UnitWorkloadStage{ UnitWorkloadStage::Stage::Run });
             ArgumentPack<ITensorInfo> arguments;
             arguments.add_const_tensor(ACL_SRC_0, src);
             arguments.add_const_tensor(ACL_DST_0, dst);
             comp_graph.add_new_component<ClComponentStore>(properties, arguments);
         }
     }
     else
     {
         ARM_COMPUTE_ERROR("Unimplemented Gpu language");
     }
     // Set up fusion test by adding to the Operator Group
     // Note this has to be performed after all the components have been successfully added to the component graph
     // Pack tensor infos
     ArgumentPack<ITensorInfo> tensors;
     tensors.add_const_tensor(ACL_SRC_0, src);
     tensors.add_const_tensor(ACL_DST_0, dst);
     const Operator op = sketch.implementation().operator_group().new_operator(operator_type, tensors);
     sketch.implementation().operator_group().add_operator(op, true);
 }
is_supported_op()
Status is_supported_op (const GpuWorkloadContext & context, const ITensorInfo * src, const ITensorInfo * dst) static
Check if the operator configuration is supported, irrespective of fusion.
Parameters
[in] context Workload context within which the operator is running.
[in] src Source tensor info.
[in] dst Destination tensor info.
Returns
Status
Definition at line 46 of file GpuOutput.cpp.
References ARM_COMPUTE_RETURN_ERROR_ON_MISMATCHING_DATA_TYPES, ARM_COMPUTE_RETURN_ERROR_ON_MISMATCHING_SHAPES, ARM_COMPUTE_RETURN_ERROR_ON_NULLPTR, ARM_COMPUTE_UNUSED, arm_compute::auto_init_if_empty(), and arm_compute::test::validation::dst.
Referenced by GpuOutput::validate_op().
 {
     ARM_COMPUTE_RETURN_ERROR_ON_NULLPTR(src, dst);
     // Initialize the destination tensor info.
     TensorInfo dst_to_validate = *dst;
     auto_init_if_empty(dst_to_validate, *src);
     ARM_COMPUTE_RETURN_ERROR_ON_MISMATCHING_DATA_TYPES(src, &dst_to_validate);
     ARM_COMPUTE_RETURN_ERROR_ON_MISMATCHING_SHAPES(src, &dst_to_validate);
     ARM_COMPUTE_UNUSED(context);
     return Status{};
 }
validate_op()
Status validate_op (const GpuWorkloadSketch & sketch, const ITensorInfo * src, const ITensorInfo * dst) static
Validate the operator and check if the its configuration is supported and if it can be fused into the workload sketch.
Parameters are similar to GpuOutput::create_op().
Returns
Status
Definition at line 63 of file GpuOutput.cpp.
References arm_compute::ACL_DST_0, arm_compute::ACL_SRC_0, ArgumentPack< T >::add_const_tensor(), ARM_COMPUTE_RETURN_ERROR_ON, ARM_COMPUTE_RETURN_ERROR_ON_MISMATCHING_DATA_TYPES, ARM_COMPUTE_RETURN_ERROR_ON_MISMATCHING_SHAPES, ARM_COMPUTE_RETURN_ERROR_ON_MSG, ARM_COMPUTE_RETURN_ERROR_ON_NULLPTR, arm_compute::auto_init_if_empty(), arm_compute::test::validation::dst, GpuWorkloadSketch::gpu_context(), ITensorInfo::has_valid_id(), GpuWorkloadSketch::implementation(), arm_compute::experimental::dynamic_fusion::is_alloc_tensor(), GpuOutput::is_supported_op(), GpuOperatorGroup::new_operator(), GpuWorkloadSketch::Implementation::operator_group(), and arm_compute::test::validation::src.
Referenced by GpuOutput::create_op().
 {
     ARM_COMPUTE_RETURN_ERROR_ON_NULLPTR(src, dst);
     ARM_COMPUTE_RETURN_ERROR_ON(!src->has_valid_id());
     ARM_COMPUTE_RETURN_ERROR_ON(!is_alloc_tensor(dst));
     // Initialize the destination tensor info.
     TensorInfo dst_to_validate = *dst;
     auto_init_if_empty(dst_to_validate, *src);
     ARM_COMPUTE_RETURN_ERROR_ON_MISMATCHING_DATA_TYPES(src, &dst_to_validate);
     ARM_COMPUTE_RETURN_ERROR_ON_MISMATCHING_SHAPES(src, &dst_to_validate);
     // Perform fusion test.
     ArgumentPack<ITensorInfo> tensors;
     tensors.add_const_tensor(ACL_SRC_0, src);
     tensors.add_const_tensor(ACL_DST_0, &dst_to_validate);
     const auto group   = sketch.implementation().operator_group();
     const auto op      = group.new_operator(operator_type, tensors);
     const auto success = group.try_add_operator(op, true);
     ARM_COMPUTE_RETURN_ERROR_ON_MSG(!success, "This operator cannot be fused into the workload.");
     const auto status = is_supported_op(*sketch.gpu_context(), src, dst);
     return status;
 }
The documentation for this class was generated from the following files:
arm_compute/dynamic_fusion/sketch/gpu/operators/GpuOutput.h
src/dynamic_fusion/sketch/gpu/operators/GpuOutput.cpp