Compute Library: arm_compute::support::cpp11 Namespace Reference
arm_compute::support::cpp11 Namespace Reference
Enumerations
enum NumericBase { BASE_10, BASE_16 }
Functions
int stoi (const std::string &str, std::size_t *pos=0, NumericBase base=NumericBase::BASE_10)
Convert string values to integer.
unsigned long stoul (const std::string &str, std::size_t *pos=0, NumericBase base=NumericBase::BASE_10)
Convert string values to unsigned long.
template<typename T >
std::string to_string (T &&value)
Convert integer and float values to string.
std::string to_string (const std::string &value)
template<typename... Ts>
int stof (Ts &&... args)
Convert string values to float.
std::string to_string (bool value)
template<typename T >
T nearbyint (T value)
Rounds the floating-point argument arg to an integer value in floating-point format, using the current rounding mode.
template<typename T , typename = typename std::enable_if<std::is_floating_point<T>::value>::type>
T round (T value)
Round floating-point value with half value rounding away from zero.
template<typename T , typename = typename std::enable_if<std::is_floating_point<T>::value>::type>
long lround (T value)
Round floating-point value with half value rounding away from zero and cast to long.
template<typename T , typename = typename std::enable_if<std::is_floating_point<T>::value>::type>
T trunc (T value)
Truncate floating-point value.
template<typename T , typename = typename std::enable_if<std::is_floating_point<T>::value>::type>
T copysign (T x, T y)
Composes a floating point value with the magnitude of x and the sign of y.
template<typename T , typename = typename std::enable_if < std::is_floating_point<T>::value >::type>
T fma (T x, T y, T z)
Computes (x*y) + z as if to infinite precision and rounded only once to fit the result type.
template<typename... Ts>
int snprintf (char *s, std::size_t n, const char *fmt, Ts &&... args)
Loads the data from the given location, converts them to character string equivalents and writes the result to a character string buffer.
template<typename T >
T lowest ()
template<>
bfloat16 lowest< bfloat16 > ()
template<typename T , typename = typename std::enable_if<std::is_arithmetic<T>::value>::type>
bool isfinite (T value)
bool isfinite (half_float::half value)
bool isfinite (bfloat16 value)
template<typename T , typename = typename std::enable_if<std::is_arithmetic<T>::value>::type>
bool signbit (T value)
bool signbit (half_float::half value)
bool signbit (bfloat16 value)
Enumeration Type Documentation
NumericBase
enum NumericBase strong
Enumerator
BASE_10
BASE_16
Definition at line 38 of file StringSupport.h.
 {
     BASE_10,
     BASE_16
 };
Function Documentation
copysign()
T arm_compute::support::cpp11::copysign (T x, T y) inline
Composes a floating point value with the magnitude of x and the sign of y.
Note
This function implements the same behaviour as std::copysign except that it doesn't support Integral type. The latter is not in the namespace std in some Android toolchains.
Parameters
[in] x value that contains the magnitude to be used in constructing the result.
[in] y value that contains the sign to be used in construct in the result.
Returns
Floating-point value with magnitude of x and sign of y.
Definition at line 231 of file ToolchainSupport.h.
References type.
Referenced by arm_compute::test::round_half_even(), and arm_compute::utils::rounding::round_half_even().
 {
     return std::copysign(x, y);
 }
fma()
T arm_compute::support::cpp11::fma (T x, T y, T z) inline
Computes (x*y) + z as if to infinite precision and rounded only once to fit the result type.
Note
This function implements the same behaviour as std::fma except that it doesn't support Integral type. The latter is not in the namespace std in some Android toolchains.
Parameters
[in] x floating-point value
[in] y floating-point value
[in] z floating-point value
Returns
Result floating point value equal to (x*y) + z.
Definition at line 252 of file ToolchainSupport.h.
 {
     return std::fma(x, y, z);
 }
isfinite() [1/3]
bool arm_compute::support::cpp11::isfinite (T value) inline
Definition at line 298 of file ToolchainSupport.h.
References isfinite().
 {
     return std::isfinite(static_cast<double>(value));
 }
isfinite() [2/3]
bool arm_compute::support::cpp11::isfinite (half_float::half value) inline
Definition at line 303 of file ToolchainSupport.h.
References isfinite().
 {
     return half_float::isfinite(value);
 }
isfinite() [3/3]
bool arm_compute::support::cpp11::isfinite (bfloat16 value) inline
Definition at line 308 of file ToolchainSupport.h.
References type.
Referenced by isfinite().
 {
     return std::isfinite(float(value));
 }
lowest()
T arm_compute::support::cpp11::lowest () inline
Definition at line 277 of file ToolchainSupport.h.
Referenced by arm_compute::helpers::tensor_transform::calculate_end_on_index(), arm_compute::helpers::tensor_transform::calculate_start_on_index(), arm_compute::check_value_range(), ClPool2dKernel::configure(), ClPool3dKernel::configure(), NEQLSTMLayer::configure(), CLQLSTMLayer::configure(), arm_compute::test::convolution_3d::detail::convolution3d(), PoolingDepthfirstCacheOblivious< strategy >::execute(), AssetsLibrary::fill_tensor_uniform(), AssetsLibrary::fill_tensor_uniform_ranged(), arm_compute::cpu::get_initial_min(), arm_compute::get_min_max(), ClTemplatePool2d::get_tag_lut(), arm_compute::test::validation::reference::pooling_layer_internal(), arm_compute::utils::cast::saturate_cast(), arm_compute::test::saturate_cast(), NEQLSTMLayer::validate(), and CLQLSTMLayer::validate().
 {
     return std::numeric_limits<T>::lowest();
 }
lowest< bfloat16 >()
bfloat16 arm_compute::support::cpp11::lowest< bfloat16 > () inline
Definition at line 291 of file ToolchainSupport.h.
References bfloat16::lowest(), and type.
 {
     return bfloat16::lowest();
 }
lround()
long arm_compute::support::cpp11::lround (T value) inline
Round floating-point value with half value rounding away from zero and cast to long.
Note
This function implements the same behaviour as std::lround except that it doesn't support Integral type. The latter is not in the namespace std in some Android toolchains.
Parameters
[in] value floating-point value to be rounded.
Returns
Floating-point value of rounded value casted to long
Definition at line 200 of file ToolchainSupport.h.
References type.
Referenced by arm_compute::cpu::add_sub_q8_neon_fixedpoint(), arm_compute::cpu::add_sub_qasymm8_neon(), arm_compute::cpu::add_sub_qasymm8_signed_neon(), ClLogits1DMaxShiftExpSumKernel::configure(), arm_compute::cpu::neon_qasymm8_activation(), arm_compute::cpu::neon_qasymm8_signed_activation(), and Qasymm8QuantizationHelper< QUANTIZED_TYPE >::quantize().
 {
     return std::lround(value);
 }
nearbyint()
T arm_compute::support::cpp11::nearbyint (T value) inline
Rounds the floating-point argument arg to an integer value in floating-point format, using the current rounding mode.
Note
This function acts as a convenience wrapper around std::nearbyint. The latter is missing in some Android toolchains.
Parameters
[in] value Value to be rounded.
Returns
The rounded value.
Definition at line 169 of file ToolchainSupport.h.
References type.
Referenced by arm_compute::cpu::elementwise_op_scalar_imp(), and arm_compute::test::validation::reference::elementwise_unary().
 {
     return static_cast<T>(std::nearbyint(value));
 }
round()
T arm_compute::support::cpp11::round (T value) inline
Round floating-point value with half value rounding away from zero.
Note
This function implements the same behaviour as std::round except that it doesn't support Integral type. The latter is not in the namespace std in some Android toolchains.
Parameters
[in] value floating-point value to be rounded.
Returns
Floating-point value of rounded value.
Definition at line 184 of file ToolchainSupport.h.
References type.
Referenced by arm_compute::quantization::calculate_quantized_multiplier_greater_than_one(), arm_compute::quantization::calculate_quantized_multiplier_less_than_one(), choose_quantization_params(), arm_compute::cpu::poolingMxN_q8_neon_nhwc(), arm_compute::test::validation::reference::roi_pool_layer(), arm_compute::round(), arm_compute::test::round_half_even(), arm_compute::utils::rounding::round_half_even(), and NEROIPoolingLayerKernel::run().
 {
     //Workaround Valgrind's mismatches: when running from Valgrind the call to std::round(-4.500000) == -4.000000 instead of 5.00000
     return (value < 0.f) ? static_cast<int>(value - 0.5f) : static_cast<int>(value + 0.5f);
 }
signbit() [1/3]
bool arm_compute::support::cpp11::signbit (T value) inline
Definition at line 315 of file ToolchainSupport.h.
References signbit().
Referenced by arm_compute::quantization::saturating_rounding_doubling_highmul().
 {
     return std::signbit(static_cast<double>(value));
 }
signbit() [2/3]
bool arm_compute::support::cpp11::signbit (half_float::half value) inline
Definition at line 320 of file ToolchainSupport.h.
References signbit().
 {
     return half_float::signbit(value);
 }
signbit() [3/3]
bool arm_compute::support::cpp11::signbit (bfloat16 value) inline
Definition at line 325 of file ToolchainSupport.h.
Referenced by signbit().
 {
     return std::signbit(float(value));
 }
snprintf()
int arm_compute::support::cpp11::snprintf (char * s, std::size_t n, const char * fmt, Ts &&... args) inline
Loads the data from the given location, converts them to character string equivalents and writes the result to a character string buffer.
Parameters
[in] s Pointer to a character string to write to
[in] n Up to buf_size - 1 characters may be written, plus the null ending character
[in] fmt Pointer to a null-ended multibyte string specifying how to interpret the data.
[in] args Arguments forwarded to std::snprintf.
Returns
Number of characters that would have been written for a sufficiently large buffer if successful (not including the ending null character), or a negative value if an error occurred.
Definition at line 269 of file ToolchainSupport.h.
References GemmTuner::args.
Referenced by arm_compute::create_error_msg(), and arm_compute::logging::string_with_format().
 {
     return std::snprintf(s, n, fmt, std::forward<Ts>(args)...);
 }
stof()
int arm_compute::support::cpp11::stof (Ts &&... args)
Convert string values to float.
Note
This function acts as a convenience wrapper around std::stof. The latter is missing in some Android toolchains.
Parameters
[in] args Arguments forwarded to std::stof.
Returns
Float representation of input string.
Definition at line 189 of file StringSupport.h.
References GemmTuner::args.
Referenced by stoul().
 {
     return ::std::stof(std::forward<Ts>(args)...);
 }
stoi()
int arm_compute::support::cpp11::stoi (const std::string & str, std::size_t * pos = 0, NumericBase base = NumericBase::BASE_10) inline
Convert string values to integer.
Note
This function implements the same behaviour as std::stoi. The latter is missing in some Android toolchains.
Parameters
[in] str String to be converted to int.
[in] pos If idx is not a null pointer, the function sets the value of pos to the position of the first character in str after the number.
[in] base Numeric base used to interpret the string.
Returns
Integer representation of str.
Definition at line 55 of file StringSupport.h.
References BASE_10, BASE_16, arm_compute::test::validation::ss(), and caffe_mnist_image_extractor::str.
Referenced by CLTuningParams::from_string(), CLCompileContext::get_ddk_version(), and TestFilter::is_selected().
 {
     assert(base == NumericBase::BASE_10 || base == NumericBase::BASE_16);
     unsigned int      x;
     std::stringstream ss;
     if(base == NumericBase::BASE_16)
     {
         ss << std::hex;
     }
     ss << str;
     ss >> x;
     if(pos)
     {
         std::string       s;
         std::stringstream ss_p;
         ss_p << x;
         ss_p >> s;
         *pos = s.length();
     }
     return x;
 }
stoul()
unsigned long arm_compute::support::cpp11::stoul (const std::string & str, std::size_t * pos = 0, NumericBase base = NumericBase::BASE_10) inline
Convert string values to unsigned long.
Note
This function implements the same behaviour as std::stoul. The latter is missing in some Android toolchains.
Parameters
[in] str String to be converted to unsigned long.
[in] pos If idx is not a null pointer, the function sets the value of pos to the position of the first character in str after the number.
[in] base Numeric base used to interpret the string.
Returns
Unsigned long representation of str.
Definition at line 91 of file StringSupport.h.
References BASE_10, BASE_16, stof(), caffe_mnist_image_extractor::str, to_string(), and type.
 {
     assert(base == NumericBase::BASE_10 || base == NumericBase::BASE_16);
     std::stringstream stream;
     unsigned long     value = 0;
     if(base == NumericBase::BASE_16)
     {
         stream << std::hex;
     }
     stream << str;
     stream >> value;
     if(pos)
     {
         std::string       s;
         std::stringstream ss_p;
         ss_p << value;
         ss_p >> s;
         *pos = s.length();
     }
     return value;
 }
to_string() [1/3]
std::string arm_compute::support::cpp11::to_string (T && value) inline
Convert integer and float values to string.
Note
This function acts as a convenience wrapper around std::to_string. The latter is missing in some Android toolchains.
Parameters
[in] value Value to be converted to string.
Returns
String representation of value.
Definition at line 168 of file StringSupport.h.
References to_string().
Referenced by ClTransposedConvolutionKernel::configure(), ClFloorKernel::configure(), ClDequantizeKernel::configure(), ClTransposeKernel::configure(), ClCopyKernel::configure(), ClElementWiseUnaryKernel::configure(), ClFillKernel::configure(), ClScaleKernel::configure(), ClWidthConcatenate2TensorsKernel::configure(), ClActivationKernel::configure(), ClMatMulNativeKernel::configure(), ClPool2dKernel::configure(), ClPool3dKernel::configure(), ClHeightConcatenateKernel::configure(), ClWidthConcatenateKernel::configure(), ClMatMulLowpNativeKernel::configure(), ClQuantizeKernel::configure(), ClPermuteKernel::configure(), ClWidthConcatenate4TensorsKernel::configure(), CLStridedSliceKernel::configure(), ClBatchConcatenateKernel::configure(), ClCropKernel::configure(), ClDepthConcatenateKernel::configure(), ClConvertFullyConnectedWeightsKernel::configure(), ClGemmLowpMatrixMultiplyNativeKernel::configure(), ClGemmReshapeLhsMatrixKernel::configure(), ClGemmMatrixMultiplyNativeKernel::configure(), CLBitwiseKernel::configure(), CLInstanceNormalizationLayerKernel::configure(), ClGemmMatrixMultiplyReshapedOnlyRhsMMULKernel::configure(), ClIndirectConv2dKernel::configure(), CLMaxUnpoolingLayerKernel::configure(), ClWinogradFilterTransformKernel::configure(), ClWinogradInputTransformKernel::configure(), CLReverseKernel::configure(), ClGemmLowpQuantizeDownInt32ScaleByFixedPointKernel::configure(), CLSelectKernel::configure(), CLChannelShuffleLayerKernel::configure(), ClIndirectConv2dAddressPrecalculationKernel::configure(), CLDepthToSpaceLayerKernel::configure(), CLSpaceToDepthLayerKernel::configure(), ClLogits1DMaxShiftExpSumKernel::configure(), ClWinogradOutputTransformKernel::configure(), ClCastKernel::configure(), ClGemmLowpQuantizeDownInt32ScaleByFloatKernel::configure(), ClGemmLowpQuantizeDownInt32ScaleKernel::configure(), CLComputeAllAnchorsKernel::configure(), CLQLSTMLayerNormalizationKernel::configure(), CLFFTScaleKernel::configure(), CLSpaceToBatchLayerKernel::configure(), CLGatherKernel::configure(), CLNormalizationLayerKernel::configure(), ClGemmLowpMatrixMultiplyReshapedKernel::configure(), CLTileKernel::configure(), CLComparisonKernel::configure(), CLBatchToSpaceLayerKernel::configure(), CLReorgLayerKernel::configure(), CLFFTDigitReverseKernel::configure(), ClGemmLowpOffsetContributionKernel::configure(), ClGemmLowpOffsetContributionOutputStageKernel::configure(), ClGemmReshapeRhsMatrixKernel::configure(), CLMeanStdDevNormalizationKernel::configure(), CLRangeKernel::configure(), CLReductionOperationKernel::configure(), ClDirectConv2dKernel::configure(), CLNormalizePlanarYUVLayerKernel::configure(), CLPadLayerKernel::configure(), ClCol2ImKernel::configure(), CLPriorBoxLayerKernel::configure(), CLFFTRadixStageKernel::configure(), ClDirectConv3dKernel::configure(), ClGemmLowpMatrixMultiplyReshapedOnlyRhsKernel::configure(), CLL2NormalizeLayerKernel::configure(), CLBoundingBoxTransformKernel::configure(), ClMulKernel::configure(), CLDepthwiseConvolutionLayerNativeKernel::configure(), CLFillBorderKernel::configure(), CLROIPoolingLayerKernel::configure(), CLStackLayerKernel::configure(), ClGemmLowpMatrixAReductionKernel::configure(), ClGemmMatrixMultiplyReshapedOnlyRhsKernel::configure(), ClWeightsReshapeKernel::configure(), CLArgMinMaxLayerKernel::configure(), CLROIAlignLayerKernel::configure(), ClIm2ColKernel::configure(), CLDeconvolutionReshapeOutputKernel::configure(), CLFuseBatchNormalizationKernel::configure(), CLBatchNormalizationLayerKernel::configure(), ClGemmMatrixMultiplyReshapedKernel::configure(), ClLogits1DNormKernel::configure(), ClGemmLowpMatrixBReductionKernel::configure(), CLComputeMeanVariance::configure(), RangeDataset< T >::iterator::description(), SingletonDataset< T >::iterator::description(), ContainerDataset< T >::iterator::description(), ClTemplateCast::get_build_options(), ClTemplateLogits1DMaxShiftExpSum::get_build_options(), ClTemplateLogits1DNorm::get_build_options(), ClTemplateReshape::get_build_options(), ClTemplateDepthwiseConv2d::get_build_options(), ClTemplateElementwiseBinary::get_build_options(), ClTemplateDirectConv2d::get_build_options(), ClTemplatePool2d::get_build_options(), ClTemplateResize::get_build_options(), ClTemplateActivation::get_build_options(), ClTemplateCast::get_config_id(), ClTemplateLogits1DMaxShiftExpSum::get_config_id(), ClTemplateLogits1DNorm::get_config_id(), ClTemplateReshape::get_config_id(), ClTemplateDepthwiseConv2d::get_config_id(), ClTemplateDirectConv2d::get_config_id(), ClTemplateElementwiseBinary::get_config_id(), ClTemplateActivation::get_config_id(), ClTemplateResize::get_config_id(), ClTemplatePool2d::get_config_id(), ClTemplateLogits1DMaxShiftExpSum::get_tag_lut(), arm_compute::utils::get_typestring(), arm_compute::test::get_typestring(), arm_compute::test::join(), main(), OpenCLClock< output_timestamps >::measurements(), MaliCounter::measurements(), SchedulerClock< output_timestamps >::measurements(), DotGraphPrinter::print(), arm_compute::utils::run_example(), CLCompileContext::set_context(), PostOpCLKernelUtils::set_post_ops_cl_build_options(), stoul(), TagVal::TagVal(), Size3D::to_string(), Size2D::to_string(), CLTuningParams::to_string(), arm_compute::to_string(), and CLTuner::tune_kernel_dynamic().
 {
     return ::std::to_string(std::forward<T>(value));
 }
to_string() [2/3]
std::string arm_compute::support::cpp11::to_string (const std::string & value) inline
Definition at line 174 of file StringSupport.h.
 {
     return value;
 }
to_string() [3/3]
std::string arm_compute::support::cpp11::to_string (bool value) inline
Definition at line 196 of file StringSupport.h.
References caffe_mnist_image_extractor::str.
Referenced by to_string().
 {
     std::stringstream str;
     str << std::boolalpha << value;
     return str.str();
 }
trunc()
T arm_compute::support::cpp11::trunc (T value) inline
Truncate floating-point value.
Note
This function implements the same behaviour as std::truncate except that it doesn't support Integral type. The latter is not in the namespace std in some Android toolchains.
Parameters
[in] value floating-point value to be truncated.
Returns
Floating-point value of truncated value.
Definition at line 215 of file ToolchainSupport.h.
References type.
Referenced by arm_compute::cpu::add_sub_qasymm8_neon(), arm_compute::cpu::add_sub_qasymm8_signed_neon(), arm_compute::test::validation::apply_2d_spatial_filter(), FilePrinter::FilePrinter(), and arm_compute::test::validation::TEST_CASE().
 {
     return std::trunc(value);
 }