var searchData=
[
  ['backendregistrar',['BackendRegistrar',['../classarm__compute_1_1graph_1_1backends_1_1detail_1_1_backend_registrar.xhtml',1,'arm_compute::graph::backends::detail']]],
  ['backendregistry',['BackendRegistry',['../classarm__compute_1_1graph_1_1backends_1_1_backend_registry.xhtml',1,'arm_compute::graph::backends']]],
  ['barrier',['barrier',['../classarm__gemm_1_1barrier.xhtml',1,'arm_gemm']]],
  ['batchnormalizationlayer',['BatchNormalizationLayer',['../classarm__compute_1_1graph_1_1frontend_1_1_batch_normalization_layer.xhtml',1,'arm_compute::graph::frontend']]],
  ['batchnormalizationlayernode',['BatchNormalizationLayerNode',['../classarm__compute_1_1graph_1_1_batch_normalization_layer_node.xhtml',1,'arm_compute::graph']]],
  ['benchmarkresult',['BenchmarkResult',['../class_gemm_tuner_1_1_benchmark_result.xhtml',1,'GemmTuner']]],
  ['bfloat16',['bfloat16',['../classarm__compute_1_1bfloat16.xhtml',1,'arm_compute']]],
  ['blobinfo',['BlobInfo',['../structarm__compute_1_1_blob_info.xhtml',1,'arm_compute']]],
  ['bloblifetimemanager',['BlobLifetimeManager',['../classarm__compute_1_1_blob_lifetime_manager.xhtml',1,'arm_compute']]],
  ['blobmemorypool',['BlobMemoryPool',['../classarm__compute_1_1_blob_memory_pool.xhtml',1,'arm_compute']]],
  ['bordersize',['BorderSize',['../structarm__compute_1_1_border_size.xhtml',1,'arm_compute']]],
  ['boundingboxtransforminfo',['BoundingBoxTransformInfo',['../classarm__compute_1_1_bounding_box_transform_info.xhtml',1,'arm_compute']]],
  ['boundingboxtransformlayer',['BoundingBoxTransformLayer',['../classarm__compute_1_1graph_1_1frontend_1_1_bounding_box_transform_layer.xhtml',1,'arm_compute::graph::frontend']]],
  ['boundingboxtransformlayernode',['BoundingBoxTransformLayerNode',['../classarm__compute_1_1graph_1_1_bounding_box_transform_layer_node.xhtml',1,'arm_compute::graph']]],
  ['boxnmslimitinfo',['BoxNMSLimitInfo',['../classarm__compute_1_1_box_n_m_s_limit_info.xhtml',1,'arm_compute']]],
  ['branchnode',['BranchNode',['../structarm__compute_1_1mlgo_1_1_heuristic_tree_1_1_branch_node.xhtml',1,'arm_compute::mlgo::HeuristicTree']]],
  ['brelu',['brelu',['../structarm__compute_1_1detail_1_1brelu.xhtml',1,'arm_compute::detail']]],
  ['broadcastquantizedlooparguments',['BroadcastQuantizedLoopArguments',['../structarm__compute_1_1cpu_1_1_broadcast_quantized_loop_arguments.xhtml',1,'arm_compute::cpu']]]
];
