Compute Library: NEDirectConvolutionLayer Class Reference
NEDirectConvolutionLayer Class Reference
Function to run the direct convolution.
#include <NEDirectConvolutionLayer.h>
Public Member Functions
NEDirectConvolutionLayer (std::shared_ptr< IMemoryManager > memory_manager=nullptr)
Constructor.
void configure (ITensor *input, const ITensor *weights, const ITensor *bias, ITensor *output, const PadStrideInfo &conv_info, const ActivationLayerInfo &act_info=ActivationLayerInfo())
Set the input, weights, biases and output tensors.
void run () override
Run the kernels contained in the function.
Public Member Functions inherited from IFunction
virtual ~IFunction ()=default
Destructor.
virtual void prepare ()
Prepare the function for executing.
Static Public Member Functions
static Status validate (const ITensorInfo *input, const ITensorInfo *weights, const ITensorInfo *bias, const ITensorInfo *output, const PadStrideInfo &conv_info, const ActivationLayerInfo &act_info=ActivationLayerInfo())
Static function to check if given info will lead to a valid configuration of NEDirectConvolutionLayer.
Detailed Description
Function to run the direct convolution.
This function calls the following NEON kernels:
NEFillBorderKernel for the input
NEDirectConvolutionLayerOutputStageKernel
NEDirectConvolutionLayerKernel
Definition at line 49 of file NEDirectConvolutionLayer.h.
Constructor & Destructor Documentation
NEDirectConvolutionLayer()
NEDirectConvolutionLayer (std::shared_ptr< IMemoryManager > memory_manager = nullptr)
Constructor.
Definition at line 36 of file NEDirectConvolutionLayer.cpp.
     : _memory_group(std::move(memory_manager)), _output_stage_kernel(), _conv_kernel(), _input_border_handler(), _activationlayer_function(), _accumulator(), _has_bias(false),
       _is_activationlayer_enabled(false), _dim_split(Window::DimZ)
 {
 }
Member Function Documentation
configure()
void configure (ITensor * input, const ITensor * weights, const ITensor * bias, ITensor * output, const PadStrideInfo & conv_info, const ActivationLayerInfo & act_info = ActivationLayerInfo())
Set the input, weights, biases and output tensors.
Note
: DirectConvolution only works in the following configurations: 1x1 convolution with stride_x = 1/2/3, stride_y = 1/2/3 data type = F16/F32 3x3 convolution with stride_x = 1/2/3, stride_y = 1/2/3 data type = F16/F32 5x5 convolution with stride_x = 1/2/3, stride_y = 1/2/3 data type = F32
Parameters
[in,out] input Input tensor. Data types supported: F16/F32.
[in] weights Set of kernels to convolve the input volume. Supported sizes: 1x1, 3x3 and 5x5. The 3rd dimension must be the same as the input's volume 3rd dimension. Data type supported: Same as input.
[in] bias Set of biases. Can be nullptr. Data type supported: Same as input.
[out] output Output tensor. The 3rd dimensions must be equal to the 4th dimension of the kernels tensor. Data types supported: Same as input.
[in] conv_info Contains padding and stride information described in PadStrideInfo.
[in] act_info (Optional) Activation layer information in case of a fused activation.
Definition at line 42 of file NEDirectConvolutionLayer.cpp.
 {
     ARM_COMPUTE_ERROR_ON(input->info()->data_layout() == DataLayout::UNKNOWN);
     // Free accumulator
     if(_accumulator.buffer() != nullptr)
     {
         _accumulator.allocator()->free();
     }
     _dim_split = input->info()->data_layout() == DataLayout::NCHW ? Window::DimZ : Window::DimY;
     // Check if bias should be added in the convolution result
     _has_bias = (bias != nullptr);
     _conv_kernel.configure(input, weights, output, conv_info);
     if(_has_bias)
     {
         _output_stage_kernel.configure(output, bias);
     }
     // Add zero padding XY
     _input_border_handler.configure(input, _conv_kernel.border_size(), BorderMode::CONSTANT, PixelValue(static_cast<float>(0.f)));
     //Configure Activation Layer
     _is_activationlayer_enabled = act_info.enabled();
     if(_is_activationlayer_enabled)
     {
         _activationlayer_function.configure(output, nullptr, act_info);
     }
 }
References arm_compute::test::validation::act_info, Tensor::allocator(), ARM_COMPUTE_ERROR_ON, arm_compute::test::validation::bias, NEDirectConvolutionLayerKernel::border_size(), Tensor::buffer(), NEActivationLayer::configure(), NEFillBorderKernel::configure(), NEDirectConvolutionLayerOutputStageKernel::configure(), NEDirectConvolutionLayerKernel::configure(), arm_compute::CONSTANT, arm_compute::test::validation::conv_info, ITensorInfo::data_layout(), Window::DimY, Window::DimZ, TensorAllocator::free(), ITensor::info(), arm_compute::NCHW, arm_compute::UNKNOWN, and arm_compute::test::validation::weights.
Referenced by NEDepthwiseSeparableConvolutionLayer::configure().
run()
void run () override virtual
Run the kernels contained in the function.
For NEON kernels:
Multi-threading is used for the kernels which are parallelisable.
By default std::thread::hardware_concurrency() threads are used.
Note
CPPScheduler::set_num_threads() can be used to manually set the number of threads
For OpenCL kernels:
All the kernels are enqueued on the queue associated with CLScheduler.
The queue is then flushed.
Note
The function will not block until the kernels are executed. It is the user's responsibility to wait.
Will call prepare() on first run if hasn't been done
Implements IFunction.
Definition at line 104 of file NEDirectConvolutionLayer.cpp.
 {
     NEScheduler::get().schedule(&_input_border_handler, Window::DimZ);
     MemoryGroupResourceScope scope_mg(_memory_group);
     NEScheduler::get().schedule(&_conv_kernel, _dim_split);
     if(_has_bias)
     {
         NEScheduler::get().schedule(&_output_stage_kernel, Window::DimY);
     }
     if(_is_activationlayer_enabled)
     {
         _activationlayer_function.run();
     }
 }
References Window::DimY, Window::DimZ, Scheduler::get(), INESimpleFunctionNoBorder::run(), and IScheduler::schedule().
Referenced by NEDepthwiseSeparableConvolutionLayer::run().
validate()
Status validate (const ITensorInfo * input, const ITensorInfo * weights, const ITensorInfo * bias, const ITensorInfo * output, const PadStrideInfo & conv_info, const ActivationLayerInfo & act_info = ActivationLayerInfo()) static
Static function to check if given info will lead to a valid configuration of NEDirectConvolutionLayer.
Note
: DirectConvolution only works in the following configurations: 1x1 convolution with stride_x = 1/2/3, stride_y = 1/2/3 data type = F16/F32 3x3 convolution with stride_x = 1/2/3, stride_y = 1/2/3 data type = F16/F32 5x5 convolution with stride_x = 1/2/3, stride_y = 1/2/3 data type = F32
Parameters
[in] input Input tensor. Data types supported: F16/F32.
[in] weights Set of kernels to convolve the input volume. Supported sizes: 1x1, 3x3 and 5x5. The 3rd dimension must be the same as the input's volume 3rd dimension. Data type supported: Same as input.
[in] bias Set of biases. Can be nullptr. Data type supported: Same as input.
[in] output Output tensor. The 3rd dimensions must be equal to the 4th dimension of the kernels tensor. Data types supported: Same as input.
[in] conv_info Contains padding and stride information described in PadStrideInfo.
[in] act_info (Optional) Activation layer information in case of a fused activation.
Returns
a status
Definition at line 74 of file NEDirectConvolutionLayer.cpp.
 {
     ARM_COMPUTE_RETURN_ERROR_ON_NULLPTR(input, weights, output);
     DataType   data_type = output->data_type();
     TensorInfo accumulator(output->clone()->set_is_resizable(true).reset_padding().set_data_type(data_type));
     // Validate Convolution kernel
     ARM_COMPUTE_RETURN_ON_ERROR(NEDirectConvolutionLayerKernel::validate(input, weights, &accumulator, conv_info));
     if(bias != nullptr)
     {
         ARM_COMPUTE_RETURN_ERROR_ON_MISMATCHING_DATA_TYPES(weights, bias);
         ARM_COMPUTE_RETURN_ERROR_ON_MSG(bias->dimension(0) != weights->dimension(3),
                                         "Biases size and number of input feature maps should match");
         ARM_COMPUTE_RETURN_ERROR_ON_MSG(bias->num_dimensions() > 1, "Biases should be one dimensional");
     }
     // Validate bias kernel
     ARM_COMPUTE_RETURN_ON_ERROR(NEDirectConvolutionLayerOutputStageKernel::validate(&accumulator, bias, output));
     if(act_info.enabled())
     {
         ARM_COMPUTE_RETURN_ON_ERROR(NEActivationLayer::validate(output, nullptr, act_info));
     }
     return Status{};
 }
References arm_compute::test::validation::act_info, ARM_COMPUTE_RETURN_ERROR_ON_MISMATCHING_DATA_TYPES, ARM_COMPUTE_RETURN_ERROR_ON_MSG, ARM_COMPUTE_RETURN_ERROR_ON_NULLPTR, ARM_COMPUTE_RETURN_ON_ERROR, arm_compute::test::validation::bias, ICloneable< T >::clone(), arm_compute::test::validation::conv_info, arm_compute::test::validation::data_type, ITensorInfo::data_type(), NEActivationLayer::validate(), NEDirectConvolutionLayerOutputStageKernel::validate(), NEDirectConvolutionLayerKernel::validate(), and arm_compute::test::validation::weights.
Referenced by NEConvolutionLayer::validate().
The documentation for this class was generated from the following files:
arm_compute/runtime/NEON/functions/NEDirectConvolutionLayer.h
src/runtime/NEON/functions/NEDirectConvolutionLayer.cpp