Compute Library: NESobel7x7VertKernel Class Reference
NESobel7x7VertKernel Class Reference
Interface for the kernel to run the vertical pass of 7x7 Sobel Y filter on a tensor.
#include <NESobel7x7Kernel.h>
Public Member Functions
const char * name () const override
Name of the kernel.
NESobel7x7VertKernel ()
Default constructor.
NESobel7x7VertKernel (const NESobel7x7VertKernel &)=delete
Prevent instances of this class from being copied (As this class contains pointers)
NESobel7x7VertKernel & operator= (const NESobel7x7VertKernel &)=delete
Prevent instances of this class from being copied (As this class contains pointers)
NESobel7x7VertKernel (NESobel7x7VertKernel &&)=default
Allow instances of this class to be moved.
NESobel7x7VertKernel & operator= (NESobel7x7VertKernel &&)=default
Allow instances of this class to be moved.
~NESobel7x7VertKernel ()=default
Default destructor.
void configure (const ITensor *input_x, const ITensor *input_y, ITensor *output_x, ITensor *output_y, bool border_undefined)
Initialise the kernel's source, destination and border mode.
void run (const Window &window, const ThreadInfo &info) override
Execute the kernel on the passed window.
BorderSize border_size () const override
The size of the border for that kernel.
Public Member Functions inherited from ICPPKernel
virtual ~ICPPKernel ()=default
Default destructor.
Public Member Functions inherited from IKernel
IKernel ()
Constructor.
virtual ~IKernel ()=default
Destructor.
virtual bool is_parallelisable () const
Indicates whether or not the kernel is parallelisable.
const Window & window () const
The maximum window the kernel can be executed on.
Detailed Description
Interface for the kernel to run the vertical pass of 7x7 Sobel Y filter on a tensor.
Definition at line 83 of file NESobel7x7Kernel.h.
Constructor & Destructor Documentation
NESobel7x7VertKernel() [1/3]
NESobel7x7VertKernel ()
Default constructor.
Definition at line 297 of file NESobel7x7Kernel.cpp.
     : _input_x(nullptr), _input_y(nullptr), _output_x(nullptr), _output_y(nullptr), _run_sobel_x(false), _run_sobel_y(false)
 {
 }
NESobel7x7VertKernel() [2/3]
NESobel7x7VertKernel (const NESobel7x7VertKernel &) delete
Prevent instances of this class from being copied (As this class contains pointers)
NESobel7x7VertKernel() [3/3]
NESobel7x7VertKernel (NESobel7x7VertKernel &&) default
Allow instances of this class to be moved.
~NESobel7x7VertKernel()
~NESobel7x7VertKernel () default
Default destructor.
Member Function Documentation
border_size()
BorderSize border_size () const override virtual
The size of the border for that kernel.
Returns
The width in number of elements of the border.
Reimplemented from IKernel.
Definition at line 302 of file NESobel7x7Kernel.cpp.
 {
     return BorderSize{ 3, 0 };
 }
Referenced by NESobel7x7VertKernel::configure().
configure()
void configure (const ITensor * input_x, const ITensor * input_y, ITensor * output_x, ITensor * output_y, bool border_undefined)
Initialise the kernel's source, destination and border mode.
Note
At least one of output_x or output_y must be set
If output_x is set then input_x must be set too
If output_y is set then input_y must be set too
Parameters
[in] input_x (Optional) Input for X (X output of hor pass). Data type supported: S32.
[in] input_y (Optional) Input for Y (Y output of hor pass). Data type supported: S32.
[out] output_x (Optional) Destination tensor for the X gradient. Data type supported: S32.
[out] output_y (Optional) Destination tensor for the Y gradient. Data type supported: S32.
[in] border_undefined True if the border mode is undefined. False if it's replicate or constant.
Definition at line 307 of file NESobel7x7Kernel.cpp.
 {
     ARM_COMPUTE_ERROR_ON((output_x == nullptr) && (output_y == nullptr));
     _run_sobel_x = (output_x != nullptr);
     _run_sobel_y = (output_y != nullptr);
     if(_run_sobel_x)
     {
         ARM_COMPUTE_ERROR_ON_FORMAT_NOT_IN(input_x, Format::S32);
         ARM_COMPUTE_ERROR_ON_FORMAT_NOT_IN(output_x, Format::S32);
     }
     if(_run_sobel_y)
     {
         ARM_COMPUTE_ERROR_ON_FORMAT_NOT_IN(input_y, Format::S32);
         ARM_COMPUTE_ERROR_ON_FORMAT_NOT_IN(output_y, Format::S32);
     }
     _input_x  = input_x;
     _input_y  = input_y;
     _output_x = output_x;
     _output_y = output_y;
     const ITensor *const input = _run_sobel_x ? input_x : input_y;
     // Configure kernel window
     constexpr unsigned int num_elems_processed_per_iteration = 8;
     constexpr unsigned int num_elems_read_per_iteration      = 8;
     constexpr unsigned int num_elems_written_per_iteration   = 8;
     constexpr unsigned int num_rows_read_per_iteration       = 7;
     Window                 win = calculate_max_window(*input->info(), Steps(num_elems_processed_per_iteration), border_undefined, border_size());
     AccessWindowHorizontal output_x_access(output_x == nullptr ? nullptr : output_x->info(), 0, num_elems_written_per_iteration);
     AccessWindowHorizontal output_y_access(output_y == nullptr ? nullptr : output_y->info(), 0, num_elems_written_per_iteration);
     update_window_and_padding(win,
                               AccessWindowRectangle(input_x == nullptr ? nullptr : input_x->info(), 0, -border_size().top, num_elems_read_per_iteration, num_rows_read_per_iteration),
                               AccessWindowRectangle(input_y == nullptr ? nullptr : input_y->info(), 0, -border_size().top, num_elems_read_per_iteration, num_rows_read_per_iteration),
                               output_x_access,
                               output_y_access);
     output_x_access.set_valid_region(win, input->info()->valid_region(), border_undefined, border_size());
     output_y_access.set_valid_region(win, input->info()->valid_region(), border_undefined, border_size());
     INEKernel::configure(win);
 }
References ARM_COMPUTE_ERROR_ON, ARM_COMPUTE_ERROR_ON_FORMAT_NOT_IN, NESobel7x7VertKernel::border_size(), arm_compute::calculate_max_window(), ITensor::info(), arm_compute::S32, BorderSize::top, arm_compute::update_window_and_padding(), and ITensorInfo::valid_region().
Referenced by NESobel7x7::configure().
name()
const char* name () const inline override virtual
Name of the kernel.
Returns
Kernel name
Implements ICPPKernel.
Definition at line 86 of file NESobel7x7Kernel.h.
     {
         return "NESobel7x7VertKernel";
     }
operator=() [1/2]
NESobel7x7VertKernel& operator= (const NESobel7x7VertKernel &) delete
Prevent instances of this class from being copied (As this class contains pointers)
operator=() [2/2]
NESobel7x7VertKernel& operator= (NESobel7x7VertKernel &&) default
Allow instances of this class to be moved.
run()
void run (const Window & window, const ThreadInfo & info) override virtual
Execute the kernel on the passed window.
Warning
If is_parallelisable() returns false then the passed window must be equal to window()
Note
The window has to be a region within the window returned by the window() method
The width of the window has to be a multiple of num_elems_processed_per_iteration().
Parameters
[in] window Region on which to execute the kernel. (Must be a region of the window returned by window())
[in] info Info about executing thread and CPU.
Implements ICPPKernel.
Definition at line 355 of file NESobel7x7Kernel.cpp.
 {
     ARM_COMPUTE_UNUSED(info);
     ARM_COMPUTE_ERROR_ON_UNCONFIGURED_KERNEL(this);
     ARM_COMPUTE_ERROR_ON_INVALID_SUBWINDOW(INEKernel::window(), window);
     Iterator input_x;
     Iterator input_y;
     Iterator output_x;
     Iterator output_y;
     int32_t in_x_stride = 0;
     int32_t in_y_stride = 0;
     if(_run_sobel_x)
     {
         input_x     = Iterator(_input_x, window);
         output_x    = Iterator(_output_x, window);
         in_x_stride = _input_x->info()->strides_in_bytes()[1] / pixel_size_from_format(_input_x->info()->format());
     }
     if(_run_sobel_y)
     {
         input_y     = Iterator(_input_y, window);
         output_y    = Iterator(_output_y, window);
         in_y_stride = _input_y->info()->strides_in_bytes()[1] / pixel_size_from_format(_input_y->info()->format());
     }
     if(_run_sobel_x)
     {
         execute_window_loop(window, [&](const Coordinates &)
         {
             auto in_ptr = reinterpret_cast<int32_t *>(input_x.ptr()) - 3 * in_x_stride;
             //top3
             int32x4x2_t data =
             {
                 {
                     vld1q_s32(in_ptr),
                     vld1q_s32(in_ptr + 4)
                 }
             };
             int32x4x2_t out = data;
             //top2
             in_ptr += in_x_stride;
             data.val[0] = vld1q_s32(in_ptr);
             out.val[0]  = vmlaq_s32(out.val[0], data.val[0], six);
             data.val[1] = vld1q_s32(in_ptr + 4);
             out.val[1]  = vmlaq_s32(out.val[1], data.val[1], six);
             //top
             in_ptr += in_x_stride;
             data.val[0] = vld1q_s32(in_ptr);
             out.val[0]  = vmlaq_s32(out.val[0], data.val[0], fifteen);
             data.val[1] = vld1q_s32(in_ptr + 4);
             out.val[1]  = vmlaq_s32(out.val[1], data.val[1], fifteen);
             //mid
             in_ptr += in_x_stride;
             data.val[0] = vld1q_s32(in_ptr);
             out.val[0]  = vmlaq_s32(out.val[0], data.val[0], twenty);
             data.val[1] = vld1q_s32(in_ptr + 4);
             out.val[1]  = vmlaq_s32(out.val[1], data.val[1], twenty);
             //low
             in_ptr += in_x_stride;
             data.val[0] = vld1q_s32(in_ptr);
             out.val[0]  = vmlaq_s32(out.val[0], data.val[0], fifteen);
             data.val[1] = vld1q_s32(in_ptr + 4);
             out.val[1]  = vmlaq_s32(out.val[1], data.val[1], fifteen);
             //low2
             in_ptr += in_x_stride;
             data.val[0] = vld1q_s32(in_ptr);
             out.val[0]  = vmlaq_s32(out.val[0], data.val[0], six);
             data.val[1] = vld1q_s32(in_ptr + 4);
             out.val[1]  = vmlaq_s32(out.val[1], data.val[1], six);
             //low3
             in_ptr += in_x_stride;
             data.val[0] = vld1q_s32(in_ptr);
             out.val[0]  = vaddq_s32(out.val[0], data.val[0]);
             data.val[1] = vld1q_s32(in_ptr + 4);
             out.val[1]  = vaddq_s32(out.val[1], data.val[1]);
             vst1q_s32(reinterpret_cast<int32_t *>(output_x.ptr()) + 0, out.val[0]);
             vst1q_s32(reinterpret_cast<int32_t *>(output_x.ptr()) + 4, out.val[1]);
         },
         input_x, output_x);
     }
     if(_run_sobel_y)
     {
         execute_window_loop(window, [&](const Coordinates &)
         {
             auto in_ptr = reinterpret_cast<int32_t *>(input_y.ptr()) - 3 * in_y_stride;
             //top3
             int32x4x2_t data =
             {
                 {
                     vld1q_s32(in_ptr),
                     vld1q_s32(in_ptr + 4)
                 }
             };
             int32x4x2_t out =
             {
                 {
                     vnegq_s32(data.val[0]),
                     vnegq_s32(data.val[1])
                 }
             };
             //top2
             in_ptr += in_y_stride;
             data.val[0] = vld1q_s32(in_ptr);
             out.val[0]  = vmlaq_s32(out.val[0], data.val[0], minusfour);
             data.val[1] = vld1q_s32(in_ptr + 4);
             out.val[1]  = vmlaq_s32(out.val[1], data.val[1], minusfour);
             //top
             in_ptr += in_y_stride;
             data.val[0] = vld1q_s32(in_ptr);
             out.val[0]  = vmlaq_s32(out.val[0], data.val[0], minusfive);
             data.val[1] = vld1q_s32(in_ptr + 4);
             out.val[1]  = vmlaq_s32(out.val[1], data.val[1], minusfive);
             //low
             in_ptr += (2 * in_y_stride);
             data.val[0] = vld1q_s32(in_ptr);
             out.val[0]  = vmlaq_s32(out.val[0], data.val[0], five);
             data.val[1] = vld1q_s32(in_ptr + 4);
             out.val[1]  = vmlaq_s32(out.val[1], data.val[1], five);
             //low2
             in_ptr += in_y_stride;
             data.val[0] = vld1q_s32(in_ptr);
             out.val[0]  = vmlaq_s32(out.val[0], data.val[0], four);
             data.val[1] = vld1q_s32(in_ptr + 4);
             out.val[1]  = vmlaq_s32(out.val[1], data.val[1], four);
             //low3
             in_ptr += in_y_stride;
             data.val[0] = vld1q_s32(in_ptr);
             out.val[0]  = vaddq_s32(out.val[0], data.val[0]);
             data.val[1] = vld1q_s32(in_ptr + 4);
             out.val[1]  = vaddq_s32(out.val[1], data.val[1]);
             vst1q_s32(reinterpret_cast<int32_t *>(output_y.ptr()) + 0, out.val[0]);
             vst1q_s32(reinterpret_cast<int32_t *>(output_y.ptr()) + 4, out.val[1]);
         },
         input_y, output_y);
     }
 }
References ARM_COMPUTE_ERROR_ON_INVALID_SUBWINDOW, ARM_COMPUTE_ERROR_ON_UNCONFIGURED_KERNEL, ARM_COMPUTE_UNUSED, arm_compute::execute_window_loop(), ITensorInfo::format(), ITensor::info(), arm_compute::test::validation::info, arm_compute::pixel_size_from_format(), Iterator::ptr(), ITensorInfo::strides_in_bytes(), and IKernel::window().
The documentation for this class was generated from the following files:
arm_compute/core/NEON/kernels/NESobel7x7Kernel.h
src/core/NEON/kernels/NESobel7x7Kernel.cpp