Compute Library: CLWarpAffineKernel Class Reference
CLWarpAffineKernel Class Reference
Interface for the warp affine kernel.
#include <CLWarpAffineKernel.h>
Public Member Functions
void configure (const ICLTensor *input, ICLTensor *output, const std::array< float, 9 > &matrix, InterpolationPolicy policy)
Initialize the function's source, destination, interpolation policy and border_mode.
BorderSize border_size () const override
The size of the border for that kernel.
Public Member Functions inherited from ICLSimple2DKernel
void run (const Window &window, cl::CommandQueue &queue) override
Enqueue the OpenCL kernel to process the given window on the passed OpenCL command queue.
Public Member Functions inherited from ICLSimpleKernel
ICLSimpleKernel ()
Constructor.
ICLSimpleKernel (const ICLSimpleKernel &)=delete
Prevent instances of this class from being copied (As this class contains pointers)
ICLSimpleKernel & operator= (const ICLSimpleKernel &)=delete
Prevent instances of this class from being copied (As this class contains pointers)
ICLSimpleKernel (ICLSimpleKernel &&)=default
Allow instances of this class to be moved.
ICLSimpleKernel & operator= (ICLSimpleKernel &&)=default
Allow instances of this class to be moved.
~ICLSimpleKernel ()=default
Default destructor.
void configure (const ICLTensor *input, ICLTensor *output, unsigned int num_elems_processed_per_iteration, bool border_undefined=false, const BorderSize &border_size=BorderSize())
Configure the kernel.
Public Member Functions inherited from ICLKernel
ICLKernel ()
Constructor.
cl::Kernel & kernel ()
Returns a reference to the OpenCL kernel of this object.
template<typename T >
void add_1D_array_argument (unsigned int &idx, const ICLArray< T > *array, const Strides &strides, unsigned int num_dimensions, const Window &window)
Add the passed 1D array's parameters to the object's kernel's arguments starting from the index idx.
void add_1D_tensor_argument (unsigned int &idx, const ICLTensor *tensor, const Window &window)
Add the passed 1D tensor's parameters to the object's kernel's arguments starting from the index idx.
void add_2D_tensor_argument (unsigned int &idx, const ICLTensor *tensor, const Window &window)
Add the passed 2D tensor's parameters to the object's kernel's arguments starting from the index idx.
void add_3D_tensor_argument (unsigned int &idx, const ICLTensor *tensor, const Window &window)
Add the passed 3D tensor's parameters to the object's kernel's arguments starting from the index idx.
void add_4D_tensor_argument (unsigned int &idx, const ICLTensor *tensor, const Window &window)
Add the passed 4D tensor's parameters to the object's kernel's arguments starting from the index idx.
template<typename T >
void add_argument (unsigned int &idx, T value)
Add the passed parameters to the object's kernel's arguments starting from the index idx.
void set_lws_hint (const cl::NDRange &lws_hint)
Set the Local-Workgroup-Size hint.
cl::NDRange lws_hint () const
Return the Local-Workgroup-Size hint.
const std::string & config_id () const
Get the configuration ID.
void set_target (GPUTarget target)
Set the targeted GPU architecture.
void set_target (cl::Device &device)
Set the targeted GPU architecture according to the CL device.
GPUTarget get_target () const
Get the targeted GPU architecture.
size_t get_max_workgroup_size ()
Get the maximum workgroup size for the device the CLKernelLibrary uses.
template<typename T , unsigned int dimension_size>
void add_array_argument (unsigned &idx, const ICLArray< T > *array, const Strides &strides, unsigned int num_dimensions, const Window &window)
Add the passed array's parameters to the object's kernel's arguments starting from the index idx.
template<unsigned int dimension_size>
void add_tensor_argument (unsigned &idx, const ICLTensor *tensor, const Window &window)
Public Member Functions inherited from IKernel
IKernel ()
Constructor.
virtual ~IKernel ()=default
Destructor.
virtual bool is_parallelisable () const
Indicates whether or not the kernel is parallelisable.
const Window & window () const
The maximum window the kernel can be executed on.
Additional Inherited Members
Static Public Member Functions inherited from ICLKernel
static constexpr unsigned int num_arguments_per_1D_array ()
Returns the number of arguments enqueued per 1D array object.
static constexpr unsigned int num_arguments_per_1D_tensor ()
Returns the number of arguments enqueued per 1D tensor object.
static constexpr unsigned int num_arguments_per_2D_tensor ()
Returns the number of arguments enqueued per 2D tensor object.
static constexpr unsigned int num_arguments_per_3D_tensor ()
Returns the number of arguments enqueued per 3D tensor object.
static constexpr unsigned int num_arguments_per_4D_tensor ()
Returns the number of arguments enqueued per 4D tensor object.
static cl::NDRange gws_from_window (const Window &window)
Get the global work size given an execution window.
Detailed Description
Interface for the warp affine kernel.
Definition at line 35 of file CLWarpAffineKernel.h.
Member Function Documentation
border_size()
BorderSize border_size () const override virtual
The size of the border for that kernel.
Returns
The width in number of elements of the border.
Reimplemented from IKernel.
Definition at line 56 of file CLWarpAffineKernel.cpp.
 {
     return BorderSize(1);
 }
Referenced by CLWarpAffineKernel::configure().
configure()
void configure (const ICLTensor * input, ICLTensor * output, const std::array< float, 9 > & matrix, InterpolationPolicy policy)
Initialize the function's source, destination, interpolation policy and border_mode.
Parameters
[in] input Source tensor. Data types supported: U8.
[out] output Destination tensor, Data types supported: U8.
[in] matrix The perspective matrix. Must be 2x3 of type float The matrix argument requires 9 values, the last 3 values are ignored.
[in] policy The interpolation type.
Definition at line 61 of file CLWarpAffineKernel.cpp.
 {
     ARM_COMPUTE_ERROR_ON_DATA_TYPE_CHANNEL_NOT_IN(input, 1, DataType::U8);
     ARM_COMPUTE_ERROR_ON_DATA_TYPE_CHANNEL_NOT_IN(output, 1, DataType::U8);
     ARM_COMPUTE_ERROR_ON(InterpolationPolicy::AREA == policy);
     _input  = input;
     _output = output;
     // Create build options
     std::set<std::string> options;
     options_add_matrix(options, matrix);
     options.emplace(("-DDATA_TYPE=" + get_cl_type_from_data_type(input->info()->data_type())));
     // Create kernel
     std::string interpolation_name = string_from_interpolation_policy(policy);
     std::transform(interpolation_name.begin(), interpolation_name.end(), interpolation_name.begin(), ::tolower);
     std::string kernel_name = "warp_affine_" + interpolation_name;
     _kernel                 = static_cast<cl::Kernel>(CLKernelLibrary::get().create_kernel(kernel_name, options));
     // Set static kernel arguments
     unsigned int idx = 2 * num_arguments_per_2D_tensor(); //Skip the input and output parameters
     _kernel.setArg<cl_int>(idx++, input->info()->dimension(0));
     _kernel.setArg<cl_int>(idx++, input->info()->dimension(1));
     // Configure kernel window
     const unsigned int num_elems_processed_per_iteration = 4;
     Window win = calculate_max_window(*output->info(), Steps(num_elems_processed_per_iteration));
     int       total_right  = ceil_to_multiple(input->info()->dimension(0), num_elems_processed_per_iteration);
     const int access_right = total_right + (((total_right - input->info()->dimension(0)) == 0) ? border_size().right : 0);
     AccessWindowStatic     input_access(input->info(), -border_size().left, -border_size().top, access_right, input->info()->dimension(1) + border_size().bottom);
     AccessWindowHorizontal output_access(output->info(), 0, num_elems_processed_per_iteration);
     update_window_and_padding(win, input_access, output_access);
     output_access.set_valid_region(win, ValidRegion(Coordinates(), output->info()->tensor_shape()));
     ICLKernel::configure_internal(win);
 }
References arm_compute::AREA, ARM_COMPUTE_ERROR_ON, ARM_COMPUTE_ERROR_ON_DATA_TYPE_CHANNEL_NOT_IN, CLWarpAffineKernel::border_size(), BorderSize::bottom, arm_compute::calculate_max_window(), arm_compute::ceil_to_multiple(), arm_compute::create_kernel(), ITensorInfo::data_type(), ITensorInfo::dimension(), CLKernelLibrary::get(), arm_compute::get_cl_type_from_data_type(), ITensor::info(), BorderSize::left, ICLKernel::num_arguments_per_2D_tensor(), arm_compute::test::validation::policy, BorderSize::right, arm_compute::string_from_interpolation_policy(), ITensorInfo::tensor_shape(), arm_compute::utility::tolower(), BorderSize::top, arm_compute::U8, and arm_compute::update_window_and_padding().
The documentation for this class was generated from the following files:
arm_compute/core/CL/kernels/CLWarpAffineKernel.h
src/core/CL/kernels/CLWarpAffineKernel.cpp