Compute Library: CLStackLayerKernel Class Reference
CLStackLayerKernel Class Reference
OpenCL kernel to stacks a rank-R tensor into one with rank-(R+1) along the axis dimension.
#include <CLStackLayerKernel.h>
Public Member Functions
CLStackLayerKernel ()
Default constructor.
CLStackLayerKernel (const CLStackLayerKernel &)=delete
Prevent instances of this class from being copied (As this class contains pointers)
CLStackLayerKernel & operator= (const CLStackLayerKernel &)=delete
Prevent instances of this class from being copied (As this class contains pointers)
CLStackLayerKernel (CLStackLayerKernel &&)=default
Allow instances of this class to be moved.
CLStackLayerKernel & operator= (CLStackLayerKernel &&)=default
Allow instances of this class to be moved.
~CLStackLayerKernel ()=default
Default destructor.
void configure (const ICLTensor *input, unsigned int axis, unsigned int idx_input, unsigned int num_tensors, ICLTensor *output)
Initialise the kernel's inputs and output.
void run (const Window &window, cl::CommandQueue &queue) override
Enqueue the OpenCL kernel to process the given window on the passed OpenCL command queue.
Public Member Functions inherited from ICLKernel
ICLKernel ()
Constructor.
cl::Kernel & kernel ()
Returns a reference to the OpenCL kernel of this object.
template<typename T >
void add_1D_array_argument (unsigned int &idx, const ICLArray< T > *array, const Strides &strides, unsigned int num_dimensions, const Window &window)
Add the passed 1D array's parameters to the object's kernel's arguments starting from the index idx.
void add_1D_tensor_argument (unsigned int &idx, const ICLTensor *tensor, const Window &window)
Add the passed 1D tensor's parameters to the object's kernel's arguments starting from the index idx.
void add_2D_tensor_argument (unsigned int &idx, const ICLTensor *tensor, const Window &window)
Add the passed 2D tensor's parameters to the object's kernel's arguments starting from the index idx.
void add_3D_tensor_argument (unsigned int &idx, const ICLTensor *tensor, const Window &window)
Add the passed 3D tensor's parameters to the object's kernel's arguments starting from the index idx.
void add_4D_tensor_argument (unsigned int &idx, const ICLTensor *tensor, const Window &window)
Add the passed 4D tensor's parameters to the object's kernel's arguments starting from the index idx.
template<typename T >
void add_argument (unsigned int &idx, T value)
Add the passed parameters to the object's kernel's arguments starting from the index idx.
void set_lws_hint (const cl::NDRange &lws_hint)
Set the Local-Workgroup-Size hint.
cl::NDRange lws_hint () const
Return the Local-Workgroup-Size hint.
const std::string & config_id () const
Get the configuration ID.
void set_target (GPUTarget target)
Set the targeted GPU architecture.
void set_target (cl::Device &device)
Set the targeted GPU architecture according to the CL device.
GPUTarget get_target () const
Get the targeted GPU architecture.
size_t get_max_workgroup_size ()
Get the maximum workgroup size for the device the CLKernelLibrary uses.
template<typename T , unsigned int dimension_size>
void add_array_argument (unsigned &idx, const ICLArray< T > *array, const Strides &strides, unsigned int num_dimensions, const Window &window)
Add the passed array's parameters to the object's kernel's arguments starting from the index idx.
template<unsigned int dimension_size>
void add_tensor_argument (unsigned &idx, const ICLTensor *tensor, const Window &window)
Public Member Functions inherited from IKernel
IKernel ()
Constructor.
virtual ~IKernel ()=default
Destructor.
virtual bool is_parallelisable () const
Indicates whether or not the kernel is parallelisable.
virtual BorderSize border_size () const
The size of the border for that kernel.
const Window & window () const
The maximum window the kernel can be executed on.
Static Public Member Functions
static Status validate (const ITensorInfo *input, unsigned int axis, unsigned int idx_input, unsigned int num_tensors, const ITensorInfo *output)
Static function to check if given info will lead to a valid configuration of CLStackLayerKernel.
Static Public Member Functions inherited from ICLKernel
static constexpr unsigned int num_arguments_per_1D_array ()
Returns the number of arguments enqueued per 1D array object.
static constexpr unsigned int num_arguments_per_1D_tensor ()
Returns the number of arguments enqueued per 1D tensor object.
static constexpr unsigned int num_arguments_per_2D_tensor ()
Returns the number of arguments enqueued per 2D tensor object.
static constexpr unsigned int num_arguments_per_3D_tensor ()
Returns the number of arguments enqueued per 3D tensor object.
static constexpr unsigned int num_arguments_per_4D_tensor ()
Returns the number of arguments enqueued per 4D tensor object.
static cl::NDRange gws_from_window (const Window &window)
Get the global work size given an execution window.
Detailed Description
OpenCL kernel to stacks a rank-R tensor into one with rank-(R+1) along the axis dimension.
Definition at line 36 of file CLStackLayerKernel.h.
Constructor & Destructor Documentation
CLStackLayerKernel() [1/3]
CLStackLayerKernel ()
Default constructor.
Definition at line 79 of file CLStackLayerKernel.cpp.
     : _input(nullptr), _output(nullptr)
 {
 }
CLStackLayerKernel() [2/3]
CLStackLayerKernel (const CLStackLayerKernel &) delete
Prevent instances of this class from being copied (As this class contains pointers)
CLStackLayerKernel() [3/3]
CLStackLayerKernel (CLStackLayerKernel &&) default
Allow instances of this class to be moved.
~CLStackLayerKernel()
~CLStackLayerKernel () default
Default destructor.
Member Function Documentation
configure()
void configure (const ICLTensor * input, unsigned int axis, unsigned int idx_input, unsigned int num_tensors, ICLTensor * output)
Initialise the kernel's inputs and output.
Note
Supported input tensor rank: up to 4
Parameters
[in] input Input tensor. Data types supported: U8/S8/QASYMM8/U16/S16/F16/U32/S32/F32
[in] axis The dimension to stack the tensors along. It must be smaller than the number of input dimensions.
[in] idx_input Index of the input tensor in the list of tensors to stack. All tensors in the list must have the same shape
[in] num_tensors Number of tensors to stack
[out] output Output tensor. Data types supported: Same as input.
Definition at line 84 of file CLStackLayerKernel.cpp.
 {
     ARM_COMPUTE_ERROR_ON_NULLPTR(input, output);
     ARM_COMPUTE_ERROR_THROW_ON(validate_arguments(input->info(), axis, idx_input, num_tensors, output->info()));
     _input  = input;
     _output = output;
     // Configure kernel window
     auto win_config = validate_and_configure_window(input->info(), axis, num_tensors, output->info());
     // Add build options
     CLBuildOptions build_opts;
     build_opts.add_option("-DDATA_TYPE=" + get_underlying_cl_type_from_data_type(input->info()->data_type()));
     build_opts.add_option("-DAXIS=" + support::cpp11::to_string(axis));
     build_opts.add_option("-DSRC_DIM2=" + support::cpp11::to_string(input->info()->dimension(2)));
     build_opts.add_option("-DDST_DIM3=" + support::cpp11::to_string(output->info()->dimension(3)));
     // Create kernel
     _kernel = static_cast<cl::Kernel>(CLKernelLibrary::get().create_kernel("stack_layer", build_opts.options()));
     ARM_COMPUTE_ERROR_THROW_ON(win_config.first);
     ICLKernel::configure_internal(win_config.second);
     const unsigned int idx = 2 * num_arguments_per_4D_tensor();
     _kernel.setArg<cl_uint>(idx, idx_input);
 }
References CLBuildOptions::add_option(), ARM_COMPUTE_ERROR_ON_NULLPTR, ARM_COMPUTE_ERROR_THROW_ON, arm_compute::test::validation::axis, arm_compute::create_kernel(), ITensorInfo::data_type(), ITensorInfo::dimension(), CLKernelLibrary::get(), arm_compute::get_underlying_cl_type_from_data_type(), ITensor::info(), ICLKernel::num_arguments_per_4D_tensor(), arm_compute::test::validation::num_tensors, and arm_compute::support::cpp11::to_string().
operator=() [1/2]
CLStackLayerKernel& operator= (const CLStackLayerKernel &) delete
Prevent instances of this class from being copied (As this class contains pointers)
operator=() [2/2]
CLStackLayerKernel& operator= (CLStackLayerKernel &&) default
Allow instances of this class to be moved.
run()
void run (const Window & window, cl::CommandQueue & queue) override virtual
Enqueue the OpenCL kernel to process the given window on the passed OpenCL command queue.
Note
The queue is not flushed by this method, and therefore the kernel will not have been executed by the time this method returns.
Parameters
[in] window Region on which to execute the kernel. (Must be a valid region of the window returned by window()).
[in,out] queue Command queue on which to enqueue the kernel.
Implements ICLKernel.
Definition at line 119 of file CLStackLayerKernel.cpp.
 {
     ARM_COMPUTE_ERROR_ON_UNCONFIGURED_KERNEL(this);
     ARM_COMPUTE_ERROR_ON_INVALID_SUBWINDOW(ICLKernel::window(), window);
     Window window_out;
     window_out.use_tensor_dimensions(_output->info()->tensor_shape());
     Window collapsed = window.collapse(ICLKernel::window(), Window::DimZ);
     Window slice_in  = collapsed.first_slice_window_4D();
     Window slice_out = window_out.first_slice_window_4D();
     unsigned int idx = 0;
     add_4D_tensor_argument(idx, _input, slice_in);
     add_4D_tensor_argument(idx, _output, slice_out);
     enqueue(queue, *this, slice_in);
 }
References ICLKernel::add_4D_tensor_argument(), ARM_COMPUTE_ERROR_ON_INVALID_SUBWINDOW, ARM_COMPUTE_ERROR_ON_UNCONFIGURED_KERNEL, Window::collapse(), Window::DimZ, arm_compute::enqueue(), Window::first_slice_window_4D(), ITensor::info(), ITensorInfo::tensor_shape(), Window::use_tensor_dimensions(), and IKernel::window().
validate()
Status validate (const ITensorInfo * input, unsigned int axis, unsigned int idx_input, unsigned int num_tensors, const ITensorInfo * output) static
Static function to check if given info will lead to a valid configuration of CLStackLayerKernel.
Note
Supported input tensor rank: up to 4
Parameters
[in] input Input tensor info. Data types supported: U8/S8/QASYMM8/U16/S16/F16/U32/S32/F32
[in] axis The dimension to stack the tensors along. It must be smaller than the number of input dimensions.
[in] idx_input Index of the input tensor in the list of tensors to stack All tensors in the list must have the same shape
[in] num_tensors Number of tensors to stack
[in] output Output tensor info. Data types supported: Same as input.
Returns
a status
Definition at line 112 of file CLStackLayerKernel.cpp.
 {
     ARM_COMPUTE_RETURN_ON_ERROR(validate_arguments(input, axis, idx_input, num_tensors, output));
     ARM_COMPUTE_RETURN_ON_ERROR(validate_and_configure_window(input->clone().get(), axis, num_tensors, output->clone().get()).first);
     return Status{};
 }
References ARM_COMPUTE_RETURN_ON_ERROR, arm_compute::test::validation::axis, ICloneable< T >::clone(), and arm_compute::test::validation::num_tensors.
Referenced by CLStackLayer::validate().
The documentation for this class was generated from the following files:
arm_compute/core/CL/kernels/CLStackLayerKernel.h
src/core/CL/kernels/CLStackLayerKernel.cpp