Compute Library: NEOpticalFlow Class Reference
NEOpticalFlow Class Reference
Basic function to execute optical flow.
#include <NEOpticalFlow.h>
Public Member Functions
NEOpticalFlow (std::shared_ptr< IMemoryManager > memory_manager=nullptr)
Constructor.
NEOpticalFlow (const NEOpticalFlow &)=delete
Prevent instances of this class from being copied (As this class contains pointers)
NEOpticalFlow & operator= (const NEOpticalFlow &)=delete
Prevent instances of this class from being copied (As this class contains pointers)
void configure (const Pyramid *old_pyramid, const Pyramid *new_pyramid, const IKeyPointArray *old_points, const IKeyPointArray *new_points_estimates, IKeyPointArray *new_points, Termination termination, float epsilon, unsigned int num_iterations, size_t window_dimension, bool use_initial_estimate, BorderMode border_mode, uint8_t constant_border_value=0)
Initialise the function input and output.
void run () override
Run the kernels contained in the function.
Public Member Functions inherited from IFunction
virtual ~IFunction ()=default
Destructor.
virtual void prepare ()
Prepare the function for executing.
Detailed Description
Basic function to execute optical flow.
This function calls the following NEON kernels and functions:
NEScharr3x3
NELKTrackerKernel
Definition at line 53 of file NEOpticalFlow.h.
Constructor & Destructor Documentation
NEOpticalFlow() [1/2]
NEOpticalFlow (std::shared_ptr< IMemoryManager > memory_manager = nullptr)
Constructor.
Parameters
[in] memory_manager (Optional) Memory manager.
Definition at line 40 of file NEOpticalFlow.cpp.
     : _memory_group(std::move(memory_manager)),
       _func_scharr(),
       _kernel_tracker(),
       _scharr_gx(),
       _scharr_gy(),
       _new_points(nullptr),
       _new_points_estimates(nullptr),
       _old_points(nullptr),
       _new_points_internal(),
       _old_points_internal(),
       _num_levels(0)
 {
 }
NEOpticalFlow() [2/2]
NEOpticalFlow (const NEOpticalFlow &) delete
Prevent instances of this class from being copied (As this class contains pointers)
Member Function Documentation
configure()
void configure (const Pyramid * old_pyramid, const Pyramid * new_pyramid, const IKeyPointArray * old_points, const IKeyPointArray * new_points_estimates, IKeyPointArray * new_points, Termination termination, float epsilon, unsigned int num_iterations, size_t window_dimension, bool use_initial_estimate, BorderMode border_mode, uint8_t constant_border_value = 0)
Initialise the function input and output.
Parameters
[in] old_pyramid Pointer to the pyramid for the old tensor. Data type supported U8
[in] new_pyramid Pointer to the pyramid for the new tensor. Data type supported U8
[in] old_points Pointer to the IKeyPointArray storing old key points
[in] new_points_estimates Pointer to the IKeyPointArray storing new estimates key points
[out] new_points Pointer to the IKeyPointArray storing new key points
[in] termination The criteria to terminate the search of each keypoint.
[in] epsilon The error for terminating the algorithm
[in] num_iterations The maximum number of iterations before terminate the alogrithm
[in] window_dimension The size of the window on which to perform the algorithm
[in] use_initial_estimate The flag to indicate whether the initial estimated position should be used
[in] border_mode The border mode applied at scharr kernel stage
[in] constant_border_value (Optional) Constant value to use for borders if border_mode is set to CONSTANT
Definition at line 55 of file NEOpticalFlow.cpp.
 {
     ARM_COMPUTE_ERROR_ON(nullptr == old_pyramid);
     ARM_COMPUTE_ERROR_ON(nullptr == new_pyramid);
     ARM_COMPUTE_ERROR_ON(nullptr == old_points);
     ARM_COMPUTE_ERROR_ON(nullptr == new_points_estimates);
     ARM_COMPUTE_ERROR_ON(nullptr == new_points);
     ARM_COMPUTE_ERROR_ON(old_pyramid->info()->num_levels() != new_pyramid->info()->num_levels());
     ARM_COMPUTE_ERROR_ON(0 == old_pyramid->info()->num_levels());
     ARM_COMPUTE_ERROR_ON(old_pyramid->info()->width() != new_pyramid->info()->width());
     ARM_COMPUTE_ERROR_ON(old_pyramid->info()->height() != new_pyramid->info()->height());
     ARM_COMPUTE_ERROR_ON(use_initial_estimate && old_points->num_values() != new_points_estimates->num_values());
     _num_levels           = old_pyramid->info()->num_levels();
     _old_points           = old_points;
     _new_points           = new_points;
     _new_points_estimates = new_points_estimates;
     const float pyr_scale = old_pyramid->info()->scale();
     _func_scharr.reserve(_num_levels);
     _kernel_tracker.reserve(_num_levels);
     _scharr_gx.reserve(_num_levels);
     _scharr_gy.reserve(_num_levels);
     _old_points_internal = LKInternalKeypointArray(old_points->num_values());
     _new_points_internal = LKInternalKeypointArray(old_points->num_values());
     _new_points->resize(old_points->num_values());
     for(unsigned int i = 0; i < _num_levels; ++i)
     {
         // Get images from the ith level of old and right pyramid
         IImage *old_ith_input = old_pyramid->get_pyramid_level(i);
         IImage *new_ith_input = new_pyramid->get_pyramid_level(i);
         // Get width and height of images
         const unsigned int width_ith  = old_ith_input->info()->dimension(0);
         const unsigned int height_ith = new_ith_input->info()->dimension(1);
         TensorInfo tensor_info(TensorShape(width_ith, height_ith), Format::S16);
         auto scharr_gx = support::cpp14::make_unique<Tensor>();
         auto scharr_gy = support::cpp14::make_unique<Tensor>();
         scharr_gx->allocator()->init(tensor_info);
         scharr_gy->allocator()->init(tensor_info);
         // Manage intermediate buffers
         _memory_group.manage(scharr_gx.get());
         _memory_group.manage(scharr_gy.get());
         // Init Scharr kernel
         auto func_scharr = support::cpp14::make_unique<NEScharr3x3>();
         func_scharr->configure(old_ith_input, scharr_gx.get(), scharr_gy.get(), border_mode, constant_border_value);
         // Init Lucas-Kanade kernel
         auto kernel_tracker = support::cpp14::make_unique<NELKTrackerKernel>();
         kernel_tracker->configure(old_ith_input, new_ith_input, scharr_gx.get(), scharr_gy.get(),
                                   old_points, new_points_estimates, new_points,
                                   &_old_points_internal, &_new_points_internal,
                                   termination, use_initial_estimate, epsilon, num_iterations, window_dimension,
                                   i, _num_levels, pyr_scale);
         scharr_gx->allocator()->allocate();
         scharr_gy->allocator()->allocate();
         _func_scharr.emplace_back(std::move(func_scharr));
         _kernel_tracker.emplace_back(std::move(kernel_tracker));
         _scharr_gx.emplace_back(std::move(scharr_gx));
         _scharr_gy.emplace_back(std::move(scharr_gy));
     }
 }
References ARM_COMPUTE_ERROR_ON, arm_compute::test::validation::border_mode, ITensorInfo::dimension(), epsilon, Pyramid::get_pyramid_level(), PyramidInfo::height(), ITensor::info(), Pyramid::info(), MemoryGroupBase< TensorType >::manage(), PyramidInfo::num_levels(), IArray< T >::num_values(), IArray< T >::resize(), arm_compute::S16, PyramidInfo::scale(), and PyramidInfo::width().
operator=()
NEOpticalFlow& operator= (const NEOpticalFlow &) delete
Prevent instances of this class from being copied (As this class contains pointers)
run()
void run () override virtual
Run the kernels contained in the function.
For NEON kernels:
Multi-threading is used for the kernels which are parallelisable.
By default std::thread::hardware_concurrency() threads are used.
Note
CPPScheduler::set_num_threads() can be used to manually set the number of threads
For OpenCL kernels:
All the kernels are enqueued on the queue associated with CLScheduler.
The queue is then flushed.
Note
The function will not block until the kernels are executed. It is the user's responsibility to wait.
Will call prepare() on first run if hasn't been done
Implements IFunction.
Definition at line 129 of file NEOpticalFlow.cpp.
 {
     ARM_COMPUTE_ERROR_ON_MSG(_num_levels == 0, "Unconfigured function");
     MemoryGroupResourceScope scope_mg(_memory_group);
     for(unsigned int level = _num_levels; level > 0; --level)
     {
         // Run Scharr kernel
         _func_scharr[level - 1].get()->run();
         // Run Lucas-Kanade kernel
         NEScheduler::get().schedule(_kernel_tracker[level - 1].get(), Window::DimX);
     }
 }
References ARM_COMPUTE_ERROR_ON_MSG, Window::DimX, Scheduler::get(), and IScheduler::schedule().
The documentation for this class was generated from the following files:
arm_compute/runtime/NEON/functions/NEOpticalFlow.h
src/runtime/NEON/functions/NEOpticalFlow.cpp