Compute Library: Tensor Class Reference
Tensor Class Reference final
Tensor object.
#include <Tensor.h>
Public Member Functions
Tensor (TensorID id, TensorDescriptor desc)
Default constructor.
TensorID id () const
Tensor ID accessor.
TensorDescriptor & desc ()
TensorInfo metadata accessor.
const TensorDescriptor & desc () const
TensorInfo metadata accessor.
void set_handle (std::unique_ptr< ITensorHandle > backend_tensor)
Sets the backend tensor.
ITensorHandle * handle ()
Backend tensor handle accessor.
void set_accessor (std::unique_ptr< ITensorAccessor > accessor)
Sets the backend tensor accessor.
ITensorAccessor * accessor ()
Backend tensor accessor.
std::unique_ptr< ITensorAccessor > extract_accessor ()
Extracts accessor from the tensor.
bool call_accessor ()
Calls accessor on tensor.
void bind_edge (EdgeID eid)
Binds the tensor with an edge.
void unbind_edge (EdgeID eid)
Unbinds an edge from a tensor.
std::set< EdgeID > bound_edges () const
Accessor the edges that are bound with the tensor.
Detailed Description
Tensor object.
Definition at line 41 of file Tensor.h.
Constructor & Destructor Documentation
Tensor()
Tensor (TensorID id, TensorDescriptor desc)
Default constructor.
Parameters
[in] id Tensor ID
[in] desc Tensor information
Definition at line 30 of file Tensor.cpp.
     : _id(id), _desc(std::move(desc)), _handle(nullptr), _accessor(nullptr), _bound_edges()
 {
 }
Member Function Documentation
accessor()
ITensorAccessor * accessor ()
Backend tensor accessor.
Returns
Backend tensor accessor
Definition at line 65 of file Tensor.cpp.
 {
     return _accessor.get();
 }
Referenced by Tensor::set_accessor().
bind_edge()
void bind_edge (EdgeID eid)
Binds the tensor with an edge.
Parameters
[in] eid Edge ID that is bound to the tensor
Definition at line 101 of file Tensor.cpp.
 {
     _bound_edges.insert(eid);
 }
Referenced by Graph::add_connection(), and INode::set_output_tensor().
bound_edges()
std::set< EdgeID > bound_edges () const
Accessor the edges that are bound with the tensor.
Returns
Bound edges
Definition at line 111 of file Tensor.cpp.
 {
     return _bound_edges;
 }
Referenced by arm_compute::graph::detail::allocate_all_input_tensors(), and arm_compute::graph::detail::allocate_all_output_tensors().
call_accessor()
bool call_accessor ()
Calls accessor on tensor.
Returns
True if the accessor was called else false
Definition at line 75 of file Tensor.cpp.
 {
     // Early exit guard
     if(!_accessor || !_handle)
     {
         return false;
     }
     // Map tensor
     _handle->map(true);
     // Return in case of null backend buffer
     if(_handle->tensor().buffer() == nullptr)
     {
         return false;
     }
     // Call accessor
     bool retval = _accessor->access_tensor(_handle->tensor());
     // Unmap tensor
     _handle->unmap();
     return retval;
 }
Referenced by arm_compute::graph::detail::call_tensor_accessor().
desc() [1/2]
TensorDescriptor & desc ()
TensorInfo metadata accessor.
Returns
Tensor descriptor metadata
Definition at line 40 of file Tensor.cpp.
 {
     return _desc;
 }
Referenced by ROIAlignLayerNode::configure_output(), StackLayerNode::configure_output(), ConcatenateLayerNode::configure_output(), arm_compute::graph::configure_tensor(), arm_compute::graph::backends::detail::create_concatenate_layer(), NEDeviceBackend::create_tensor(), GCDeviceBackend::create_tensor(), CLDeviceBackend::create_tensor(), InputNode::forward_descriptors(), ConstNode::forward_descriptors(), SplitLayerNode::forward_descriptors(), arm_compute::graph::backends::detail::get_backing_tensor(), arm_compute::graph::get_tensor_descriptor(), NodeFusionMutator::mutate(), DepthConcatSubTensorMutator::mutate(), and SplitLayerSubTensorMutator::mutate().
desc() [2/2]
const TensorDescriptor & desc () const
TensorInfo metadata accessor.
Returns
Tensor descriptor metadata
Definition at line 45 of file Tensor.cpp.
 {
     return _desc;
 }
extract_accessor()
std::unique_ptr< ITensorAccessor > extract_accessor ()
Extracts accessor from the tensor.
Warning
Accessor gets unbound from the tensor
Returns
The accessor of the tensor
Definition at line 70 of file Tensor.cpp.
 {
     return std::move(_accessor);
 }
handle()
ITensorHandle * handle ()
Backend tensor handle accessor.
Returns
Backend tensor handle
Definition at line 55 of file Tensor.cpp.
 {
     return _handle.get();
 }
Referenced by arm_compute::graph::detail::allocate_all_input_tensors(), arm_compute::graph::detail::allocate_all_output_tensors(), arm_compute::graph::configure_tensor(), arm_compute::graph::backends::detail::get_backing_tensor(), arm_compute::graph::backends::detail::get_backing_tensor_info(), and SplitLayerSubTensorMutator::mutate().
id()
TensorID id () const
Tensor ID accessor.
Returns
Tensor ID
Definition at line 35 of file Tensor.cpp.
 {
     return _id;
 }
Referenced by Edge::tensor_id().
set_accessor()
void set_accessor (std::unique_ptr< ITensorAccessor > accessor)
Sets the backend tensor accessor.
Parameters
[in] accessor Accessor to set
Definition at line 60 of file Tensor.cpp.
 {
     _accessor = std::move(accessor);
 }
References Tensor::accessor().
Referenced by GroupedConvolutionMutator::mutate(), and arm_compute::graph::set_tensor_accessor().
set_handle()
void set_handle (std::unique_ptr< ITensorHandle > backend_tensor)
Sets the backend tensor.
Parameters
[in] backend_tensor Backend tensor to set
Definition at line 50 of file Tensor.cpp.
 {
     _handle = std::move(backend_tensor);
 }
Referenced by arm_compute::graph::configure_tensor(), and SplitLayerSubTensorMutator::mutate().
unbind_edge()
void unbind_edge (EdgeID eid)
Unbinds an edge from a tensor.
Parameters
[in] eid Edge to unbind
Definition at line 106 of file Tensor.cpp.
 {
     _bound_edges.erase(eid);
 }
Referenced by Graph::remove_connection(), and INode::set_output_tensor().
The documentation for this class was generated from the following files:
arm_compute/graph/Tensor.h
src/graph/Tensor.cpp