Compute Library: NEMeanStdDevKernel Class Reference
NEMeanStdDevKernel Class Reference
Interface for the kernel to calculate mean and standard deviation of input image pixels.
#include <NEMeanStdDevKernel.h>
Public Member Functions
const char * name () const override
Name of the kernel.
NEMeanStdDevKernel ()
Default constructor.
NEMeanStdDevKernel (const NEMeanStdDevKernel &)=delete
Prevent instances of this class from being copied (As this class contains pointers)
NEMeanStdDevKernel & operator= (const NEMeanStdDevKernel &)=delete
Prevent instances of this class from being copied (As this class contains pointers)
NEMeanStdDevKernel (NEMeanStdDevKernel &&)=default
Allow instances of this class to be moved.
NEMeanStdDevKernel & operator= (NEMeanStdDevKernel &&)=default
Allow instances of this class to be moved.
~NEMeanStdDevKernel ()=default
Default destructor.
void configure (const IImage *input, float *mean, uint64_t *global_sum, float *stddev=nullptr, uint64_t *global_sum_squared=nullptr)
Initialise the kernel's input and outputs.
void run (const Window &window, const ThreadInfo &info) override
Execute the kernel on the passed window.
BorderSize border_size () const override
The size of the border for that kernel.
Public Member Functions inherited from ICPPKernel
virtual ~ICPPKernel ()=default
Default destructor.
Public Member Functions inherited from IKernel
IKernel ()
Constructor.
virtual ~IKernel ()=default
Destructor.
virtual bool is_parallelisable () const
Indicates whether or not the kernel is parallelisable.
const Window & window () const
The maximum window the kernel can be executed on.
Detailed Description
Interface for the kernel to calculate mean and standard deviation of input image pixels.
Definition at line 38 of file NEMeanStdDevKernel.h.
Constructor & Destructor Documentation
NEMeanStdDevKernel() [1/3]
NEMeanStdDevKernel ()
Default constructor.
Definition at line 87 of file NEMeanStdDevKernel.cpp.
     : _input(nullptr), _mean(nullptr), _stddev(nullptr), _global_sum(nullptr), _global_sum_squared(nullptr), _mtx(), _border_size(0)
 {
 }
NEMeanStdDevKernel() [2/3]
NEMeanStdDevKernel (const NEMeanStdDevKernel &) delete
Prevent instances of this class from being copied (As this class contains pointers)
NEMeanStdDevKernel() [3/3]
NEMeanStdDevKernel (NEMeanStdDevKernel &&) default
Allow instances of this class to be moved.
~NEMeanStdDevKernel()
~NEMeanStdDevKernel () default
Default destructor.
Member Function Documentation
border_size()
BorderSize border_size () const override virtual
The size of the border for that kernel.
Returns
The width in number of elements of the border.
Reimplemented from IKernel.
Definition at line 92 of file NEMeanStdDevKernel.cpp.
 {
     return _border_size;
 }
Referenced by NEMeanStdDev::configure().
configure()
void configure (const IImage * input, float * mean, uint64_t * global_sum, float * stddev = nullptr, uint64_t * global_sum_squared = nullptr)
Initialise the kernel's input and outputs.
Parameters
[in] input Input image. Data type supported: U8.
[out] mean Input average pixel value.
[out] global_sum Keeps global sum of pixel values.
[out] stddev (Optional) Output standard deviation of pixel values.
[out] global_sum_squared (Optional if stddev is not set, required if stddev is set) Keeps global sum of squared pixel values.
Definition at line 97 of file NEMeanStdDevKernel.cpp.
 {
     ARM_COMPUTE_ERROR_ON_TENSOR_NOT_2D(input);
     ARM_COMPUTE_ERROR_ON(nullptr == mean);
     ARM_COMPUTE_ERROR_ON(nullptr == global_sum);
     ARM_COMPUTE_ERROR_ON(stddev && nullptr == global_sum_squared);
     ARM_COMPUTE_ERROR_ON_DATA_TYPE_CHANNEL_NOT_IN(input, 1, DataType::U8);
     _input              = input;
     _mean               = mean;
     _stddev             = stddev;
     _global_sum         = global_sum;
     _global_sum_squared = global_sum_squared;
     constexpr unsigned int num_elems_processed_per_iteration = 16;
     _border_size = BorderSize(ceil_to_multiple(input->info()->dimension(0), num_elems_processed_per_iteration) - input->info()->dimension(0));
     // Configure kernel window
     Window win = calculate_max_window(*input->info(), Steps(num_elems_processed_per_iteration));
     update_window_and_padding(win, AccessWindowHorizontal(input->info(), 0, num_elems_processed_per_iteration));
     INEKernel::configure(win);
 }
References ARM_COMPUTE_ERROR_ON, ARM_COMPUTE_ERROR_ON_DATA_TYPE_CHANNEL_NOT_IN, ARM_COMPUTE_ERROR_ON_TENSOR_NOT_2D, arm_compute::calculate_max_window(), arm_compute::ceil_to_multiple(), ITensorInfo::dimension(), ITensor::info(), arm_compute::U8, and arm_compute::update_window_and_padding().
Referenced by NEMeanStdDev::configure().
name()
const char* name () const inline override virtual
Name of the kernel.
Returns
Kernel name
Implements ICPPKernel.
Definition at line 41 of file NEMeanStdDevKernel.h.
     {
         return "NEMeanStdDevKernel";
     }
operator=() [1/2]
NEMeanStdDevKernel& operator= (const NEMeanStdDevKernel &) delete
Prevent instances of this class from being copied (As this class contains pointers)
operator=() [2/2]
NEMeanStdDevKernel& operator= (NEMeanStdDevKernel &&) default
Allow instances of this class to be moved.
run()
void run (const Window & window, const ThreadInfo & info) override virtual
Execute the kernel on the passed window.
Warning
If is_parallelisable() returns false then the passed window must be equal to window()
Note
The window has to be a region within the window returned by the window() method
The width of the window has to be a multiple of num_elems_processed_per_iteration().
Parameters
[in] window Region on which to execute the kernel. (Must be a region of the window returned by window())
[in] info Info about executing thread and CPU.
Implements ICPPKernel.
Definition at line 123 of file NEMeanStdDevKernel.cpp.
 {
     ARM_COMPUTE_UNUSED(info);
     ARM_COMPUTE_ERROR_ON_UNCONFIGURED_KERNEL(this);
     ARM_COMPUTE_ERROR_ON_INVALID_SUBWINDOW(INEKernel::window(), window);
     Iterator input(_input, window);
     uint64x1_t local_sum         = vdup_n_u64(0);
     uint64x1_t local_sum_squared = vdup_n_u64(0);
     if(_stddev != nullptr)
     {
         std::tie(local_sum, local_sum_squared) = accumulate<true>(window, input);
     }
     else
     {
         std::tie(local_sum, local_sum_squared) = accumulate<false>(window, input);
     }
     const float num_pixels = _input->info()->dimension(0) * _input->info()->dimension(1);
     // Merge sum and calculate mean and stddev
     std::unique_lock<arm_compute::Mutex> lock(_mtx);
     *_global_sum += vget_lane_u64(local_sum, 0);
     const float mean = *_global_sum / num_pixels;
     *_mean           = mean;
     if(_stddev != nullptr)
     {
         const uint64_t tmp_sum_squared = vget_lane_u64(local_sum_squared, 0);
         *_global_sum_squared += tmp_sum_squared;
         *_stddev = std::sqrt((*_global_sum_squared / num_pixels) - (mean * mean));
     }
     lock.unlock();
 }
References ARM_COMPUTE_ERROR_ON_INVALID_SUBWINDOW, ARM_COMPUTE_ERROR_ON_UNCONFIGURED_KERNEL, ARM_COMPUTE_UNUSED, ITensorInfo::dimension(), ITensor::info(), arm_compute::test::validation::info, and IKernel::window().
The documentation for this class was generated from the following files:
arm_compute/core/NEON/kernels/NEMeanStdDevKernel.h
src/core/NEON/kernels/NEMeanStdDevKernel.cpp