Compute Library: NEFillArrayKernel Class Reference
NEFillArrayKernel Class Reference
This kernel adds all texels greater than or equal to the threshold value to the keypoint array.
#include <NEFillArrayKernel.h>
Public Member Functions
const char * name () const override
Name of the kernel.
NEFillArrayKernel ()
Default contructor.
NEFillArrayKernel (const NEFillArrayKernel &)=delete
Prevent instances of this class from being copied (As this class contains pointers)
NEFillArrayKernel & operator= (const NEFillArrayKernel &)=delete
Prevent instances of this class from being copied (As this class contains pointers)
NEFillArrayKernel (NEFillArrayKernel &&)=default
Allow instances of this class to be moved.
NEFillArrayKernel & operator= (NEFillArrayKernel &&)=default
Allow instances of this class to be moved.
~NEFillArrayKernel ()=default
Default detructor.
void configure (const IImage *input, uint8_t threshold, IKeyPointArray *output)
Initialise the kernel.
void run (const Window &window, const ThreadInfo &info) override
Execute the kernel on the passed window.
bool is_parallelisable () const override
Indicates whether or not the kernel is parallelisable.
Public Member Functions inherited from ICPPKernel
virtual ~ICPPKernel ()=default
Default destructor.
Public Member Functions inherited from IKernel
IKernel ()
Constructor.
virtual ~IKernel ()=default
Destructor.
virtual BorderSize border_size () const
The size of the border for that kernel.
const Window & window () const
The maximum window the kernel can be executed on.
Detailed Description
This kernel adds all texels greater than or equal to the threshold value to the keypoint array.
Definition at line 39 of file NEFillArrayKernel.h.
Constructor & Destructor Documentation
NEFillArrayKernel() [1/3]
NEFillArrayKernel ()
Default contructor.
Definition at line 34 of file NEFillArrayKernel.cpp.
     : _input(nullptr), _output(nullptr), _threshold(0)
 {
 }
NEFillArrayKernel() [2/3]
NEFillArrayKernel (const NEFillArrayKernel &) delete
Prevent instances of this class from being copied (As this class contains pointers)
NEFillArrayKernel() [3/3]
NEFillArrayKernel (NEFillArrayKernel &&) default
Allow instances of this class to be moved.
~NEFillArrayKernel()
~NEFillArrayKernel () default
Default detructor.
Member Function Documentation
configure()
void configure (const IImage * input, uint8_t threshold, IKeyPointArray * output)
Initialise the kernel.
Parameters
[in] input Source image. Data type supported: U8.
[in] threshold Texels greater than the threshold will be added to the array.
[out] output Arrays of keypoints to store the results.
Definition at line 39 of file NEFillArrayKernel.cpp.
 {
     ARM_COMPUTE_ERROR_ON_TENSOR_NOT_2D(input);
     ARM_COMPUTE_ERROR_ON_DATA_TYPE_CHANNEL_NOT_IN(input, 1, DataType::U8);
     ARM_COMPUTE_ERROR_ON(nullptr == output);
     _input     = input;
     _output    = output;
     _threshold = threshold;
     constexpr unsigned int num_elems_processed_per_iteration = 1;
     constexpr unsigned int num_elems_read_per_iteration      = 1;
     // Configure kernel window
     Window win = calculate_max_window(*input->info(), Steps(num_elems_processed_per_iteration));
     update_window_and_padding(win, AccessWindowHorizontal(input->info(), 0, num_elems_read_per_iteration));
     INEKernel::configure(win);
 }
References ARM_COMPUTE_ERROR_ON, ARM_COMPUTE_ERROR_ON_DATA_TYPE_CHANNEL_NOT_IN, ARM_COMPUTE_ERROR_ON_TENSOR_NOT_2D, arm_compute::calculate_max_window(), ITensor::info(), arm_compute::test::validation::reference::threshold(), arm_compute::U8, and arm_compute::update_window_and_padding().
Referenced by NEFastCorners::configure().
is_parallelisable()
bool is_parallelisable () const override virtual
Indicates whether or not the kernel is parallelisable.
If the kernel is parallelisable then the window returned by window() can be split into sub-windows which can then be run in parallel.
If the kernel is not parallelisable then only the window returned by window() can be passed to run()
Returns
True if the kernel is parallelisable
Reimplemented from IKernel.
Definition at line 60 of file NEFillArrayKernel.cpp.
 {
     return false;
 }
name()
const char* name () const inline override virtual
Name of the kernel.
Returns
Kernel name
Implements ICPPKernel.
Definition at line 42 of file NEFillArrayKernel.h.
     {
         return "NEFillArrayKernel";
     }
operator=() [1/2]
NEFillArrayKernel& operator= (const NEFillArrayKernel &) delete
Prevent instances of this class from being copied (As this class contains pointers)
operator=() [2/2]
NEFillArrayKernel& operator= (NEFillArrayKernel &&) default
Allow instances of this class to be moved.
run()
void run (const Window & window, const ThreadInfo & info) override virtual
Execute the kernel on the passed window.
Warning
If is_parallelisable() returns false then the passed window must be equal to window()
Note
The window has to be a region within the window returned by the window() method
The width of the window has to be a multiple of num_elems_processed_per_iteration().
Parameters
[in] window Region on which to execute the kernel. (Must be a region of the window returned by window())
[in] info Info about executing thread and CPU.
Implements ICPPKernel.
Definition at line 65 of file NEFillArrayKernel.cpp.
 {
     ARM_COMPUTE_UNUSED(info);
     ARM_COMPUTE_ERROR_ON_UNCONFIGURED_KERNEL(this);
     ARM_COMPUTE_ERROR_ON_INVALID_SUBWINDOW(INEKernel::window(), window);
     Iterator input(_input, window);
     execute_window_loop(window, [&](const Coordinates & id)
     {
         const uint8_t value = *input.ptr();
         if(value >= _threshold)
         {
             KeyPoint p;
             p.x               = id.x();
             p.y               = id.y();
             p.strength        = value;
             p.tracking_status = 1;
             p.scale           = 0.f;
             p.orientation     = 0.f;
             p.error           = 0.f;
             if(!_output->push_back(p))
             {
                 return; //Overflowed: stop trying to add more points
             }
         }
     },
     input);
 }
References ARM_COMPUTE_ERROR_ON_INVALID_SUBWINDOW, ARM_COMPUTE_ERROR_ON_UNCONFIGURED_KERNEL, ARM_COMPUTE_UNUSED, arm_compute::execute_window_loop(), arm_compute::test::validation::info, and IKernel::window().
The documentation for this class was generated from the following files:
arm_compute/core/NEON/kernels/NEFillArrayKernel.h
src/core/NEON/kernels/NEFillArrayKernel.cpp