Compute Library: ICLLut Class Reference
ICLLut Class Reference abstract
Interface for OpenCL LUT.
#include <ICLLut.h>
Public Member Functions
ICLLut ()
ICLLut (const ICLLut &)=delete
ICLLut & operator= (const ICLLut &)=delete
virtual const cl::Buffer & cl_buffer () const =0
Interface to be implemented by the child class to return a reference to the OpenCL buffer containing the lut's data.
void map (cl::CommandQueue &q, bool blocking=true)
Enqueue a map operation of the allocated buffer on the given queue.
void unmap (cl::CommandQueue &q)
Enqueue an unmap operation of the allocated and mapped buffer on the given queue.
uint8_t * buffer () const override
Returns a pointer to the start of the LUT.
Public Member Functions inherited from ILut
virtual ~ILut ()=default
Default virtual destructor.
virtual size_t num_elements () const =0
Returns the total number of elements in the LUT.
virtual uint32_t index_offset () const =0
Indicates the offset that needs to be applied to the raw index before performing a lookup in the LUT.
virtual size_t size_in_bytes () const =0
Returns the total size in bytes of the LUT.
virtual DataType type () const =0
Returns the type of the LUT.
virtual void clear ()=0
Clears the LUT by setting every element to zero.
Detailed Description
Interface for OpenCL LUT.
Definition at line 40 of file ICLLut.h.
Constructor & Destructor Documentation
ICLLut() [1/2]
ICLLut ()
Definition at line 28 of file ICLLut.cpp.
     : _mapping(nullptr)
 {
 }
ICLLut() [2/2]
ICLLut (const ICLLut &) delete
Member Function Documentation
buffer()
uint8_t * buffer () const override virtual
Returns a pointer to the start of the LUT.
Other elements of the LUT can be accessed using buffer()[idx] for 0 <= idx < num_elements().
Returns
Pointer to the start of the lut.
Implements ILut.
Definition at line 44 of file ICLLut.cpp.
 {
     return _mapping;
 }
Referenced by CLLutAccessor< T >::operator[]().
cl_buffer()
virtual const cl::Buffer& cl_buffer () const pure virtual
Interface to be implemented by the child class to return a reference to the OpenCL buffer containing the lut's data.
Returns
A reference to an OpenCL buffer containing the lut's data.
Implemented in CLLut.
Referenced by CLTableLookupKernel::configure().
map()
void map (cl::CommandQueue & q, bool blocking = true)
Enqueue a map operation of the allocated buffer on the given queue.
Parameters
[in,out] q The CL command queue to use for the mapping operation.
[in] blocking If true, then the mapping will be ready to use by the time this method returns, else it is the caller's responsibility to flush the queue and wait for the mapping operation to have completed before using the returned mapping pointer.
Definition at line 33 of file ICLLut.cpp.
 {
     _mapping = do_map(q, blocking);
 }
Referenced by CLLut::map().
operator=()
ICLLut& operator= (const ICLLut &) delete
unmap()
void unmap (cl::CommandQueue & q)
Enqueue an unmap operation of the allocated and mapped buffer on the given queue.
Note
This method simply enqueues the unmap operation, it is the caller's responsibility to flush the queue and make sure the unmap is finished before the memory is accessed by the device.
Parameters
[in,out] q The CL command queue to use for the mapping operation.
Definition at line 38 of file ICLLut.cpp.
 {
     do_unmap(q);
     _mapping = nullptr;
 }
Referenced by CLLut::unmap().
The documentation for this class was generated from the following files:
arm_compute/core/CL/ICLLut.h
src/core/CL/ICLLut.cpp