Compute Library: NEConvolutionKernel< matrix_size > Class Template Reference
NEConvolutionKernel< matrix_size > Class Template Reference
Interface for the kernel to run an arbitrary size convolution on a tensor.
#include <NEConvolutionKernel.h>
Public Member Functions
const char * name () const override
Name of the kernel.
NEConvolutionKernel ()
Default constructor.
void configure (const ITensor *input, ITensor *output, const int16_t *conv, uint32_t scale, bool border_undefined)
Initialise the kernel's input, output and border mode.
void run (const Window &window, const ThreadInfo &info) override
Execute the kernel on the passed window.
BorderSize border_size () const override
The size of the border for that kernel.
Public Member Functions inherited from ICPPSimpleKernel
ICPPSimpleKernel ()
Constructor.
ICPPSimpleKernel (const ICPPSimpleKernel &)=delete
Prevent instances of this class from being copied (As this class contains pointers)
ICPPSimpleKernel & operator= (const ICPPSimpleKernel &)=delete
Prevent instances of this class from being copied (As this class contains pointers)
ICPPSimpleKernel (ICPPSimpleKernel &&)=default
Allow instances of this class to be moved.
ICPPSimpleKernel & operator= (ICPPSimpleKernel &&)=default
Allow instances of this class to be moved.
~ICPPSimpleKernel ()=default
Default destructor.
Public Member Functions inherited from ICPPKernel
virtual ~ICPPKernel ()=default
Default destructor.
Public Member Functions inherited from IKernel
IKernel ()
Constructor.
virtual ~IKernel ()=default
Destructor.
virtual bool is_parallelisable () const
Indicates whether or not the kernel is parallelisable.
const Window & window () const
The maximum window the kernel can be executed on.
Detailed Description
template<unsigned int matrix_size>
class arm_compute::NEConvolutionKernel< matrix_size >
Interface for the kernel to run an arbitrary size convolution on a tensor.
(Currently supports 3x3, 5x5, 7x7 and 9x9). The client can supply a convolution matrix \(C_{m,n} \).
\begin{eqnarray} k_0 &=& \frac{m}{2} \\ l_0 &=& \frac{n}{2} \\ sum &=& \sum_{k=0,l=0}^{k=m-1,l=n-1} input(x+k-k_0, y+l-l_0) C_{k,l} \end{eqnarray}
Note
The above equation for this function is similar to the default OpenCV Filter2D function, which actually computes a correlation and not a convolution. In case of a real convolution the convolution matrix should be flipped both horizontally and vertically.
Definition at line 55 of file NEConvolutionKernel.h.
Constructor & Destructor Documentation
NEConvolutionKernel()
NEConvolutionKernel ()
Default constructor.
Definition at line 312 of file NEConvolutionKernel.cpp.
     : INESimpleKernel(), _scale(0), _convolution{ {} }
 {
 }
Member Function Documentation
border_size()
BorderSize border_size () const override virtual
The size of the border for that kernel.
Returns
The width in number of elements of the border.
Reimplemented from IKernel.
Definition at line 318 of file NEConvolutionKernel.cpp.
 {
     return BorderSize{ matrix_size / 2 };
 }
configure()
void configure (const ITensor * input, ITensor * output, const int16_t * conv, uint32_t scale, bool border_undefined)
Initialise the kernel's input, output and border mode.
Parameters
[in] input Source tensor. Data type supported: U8.
[out] output Destination tensor. Data types supported: U8, S16.
[in] conv Convolution matrix to apply to the input tensor.
[in] scale Scale of the convolution matrix. If 0 is passed, it will be set to the sum of the coefficients of the convolution or 1 if they add up to 0.
[in] border_undefined True if the border mode is undefined. False if it's replicate or constant.
Definition at line 324 of file NEConvolutionKernel.cpp.
 {
     ARM_COMPUTE_ERROR_ON_NULLPTR(input, output, conv);
     set_shape_if_empty(*output->info(), input->info()->tensor_shape());
     ARM_COMPUTE_ERROR_ON_MISMATCHING_SHAPES(input, output);
     ARM_COMPUTE_ERROR_ON_DATA_TYPE_CHANNEL_NOT_IN(input, 1, DataType::U8);
     ARM_COMPUTE_ERROR_ON_DATA_TYPE_CHANNEL_NOT_IN(output, 1, DataType::U8, DataType::S16);
     _input  = input;
     _output = output;
     std::copy_n(conv, _convolution.size(), _convolution.begin());
     if(scale == 0)
     {
         _scale = calculate_matrix_scale(_convolution.data(), matrix_size);
     }
     else
     {
         _scale = scale;
     }
     // Configure kernel window
     constexpr unsigned int num_elems_processed_per_iteration = 8;
     constexpr unsigned int num_elems_read_per_iteration      = 16;
     constexpr unsigned int num_elems_written_per_iteration   = 8;
     Window                 win = calculate_max_window(*input->info(), Steps(num_elems_processed_per_iteration), border_undefined, border_size());
     AccessWindowHorizontal output_access(output->info(), 0, num_elems_written_per_iteration);
     update_window_and_padding(win,
                               AccessWindowRectangle(input->info(), -border_size().left, -border_size().top, num_elems_read_per_iteration, matrix_size),
                               output_access);
     output_access.set_valid_region(win, input->info()->valid_region(), border_undefined, border_size());
     INEKernel::configure(win);
 }
References ARM_COMPUTE_ERROR_ON_DATA_TYPE_CHANNEL_NOT_IN, ARM_COMPUTE_ERROR_ON_MISMATCHING_SHAPES, ARM_COMPUTE_ERROR_ON_NULLPTR, arm_compute::calculate_matrix_scale(), arm_compute::calculate_max_window(), arm_compute::test::validation::conv, ITensor::info(), arm_compute::S16, arm_compute::test::validation::scale, arm_compute::set_shape_if_empty(), ITensorInfo::tensor_shape(), arm_compute::U8, arm_compute::update_window_and_padding(), and ITensorInfo::valid_region().
name()
const char* name () const inline override virtual
Name of the kernel.
Returns
Kernel name
Implements ICPPKernel.
Definition at line 58 of file NEConvolutionKernel.h.
     {
         return "NEConvolutionKernel";
     }
run()
void run (const Window & window, const ThreadInfo & info) override virtual
Execute the kernel on the passed window.
Warning
If is_parallelisable() returns false then the passed window must be equal to window()
Note
The window has to be a region within the window returned by the window() method
The width of the window has to be a multiple of num_elems_processed_per_iteration().
Parameters
[in] window Region on which to execute the kernel. (Must be a region of the window returned by window())
[in] info Info about executing thread and CPU.
Implements ICPPKernel.
Definition at line 624 of file NEConvolutionKernel.cpp.
 {
     ARM_COMPUTE_UNUSED(info);
     ARM_COMPUTE_ERROR_ON_UNCONFIGURED_KERNEL(this);
     ARM_COMPUTE_ERROR_ON_INVALID_SUBWINDOW(INEKernel::window(), window);
     switch(_output->info()->data_type())
     {
         case DataType::U8:
             convolution<uint8_t>(window);
             break;
         case DataType::S16:
             convolution<int16_t>(window);
             break;
         default:
             ARM_COMPUTE_ERROR("Not supported Data type!");
             break;
     }
 }
References ARM_COMPUTE_ERROR, ARM_COMPUTE_ERROR_ON_INVALID_SUBWINDOW, ARM_COMPUTE_ERROR_ON_UNCONFIGURED_KERNEL, ARM_COMPUTE_UNUSED, arm_compute::test::validation::info, arm_compute::S16, arm_compute::U8, and IKernel::window().
The documentation for this class was generated from the following files:
arm_compute/core/NEON/kernels/NEConvolutionKernel.h
src/core/NEON/kernels/NEConvolutionKernel.cpp