Compute Library: Graph Class Reference
Graph Class Reference final
Graph class.
#include <Graph.h>
Public Member Functions
Graph ()=default
Graph (GraphID id, std::string name)
Constructor.
Graph (const Graph &)=delete
Prevent instances of this class from being copied (As this class contains pointers)
Graph & operator= (const Graph &)=delete
Prevent instances of this class from being copy assigned (As this class contains pointers)
Graph (Graph &&)=default
Allow instances of this class to be moved.
Graph & operator= (Graph &&)=default
Allow instances of this class to be move assigned.
template<typename NT , typename... Ts>
NodeID add_node (Ts &&... args)
Adds a node to the graph.
bool remove_node (NodeID nid)
Remove the node with the given ID.
EdgeID add_connection (NodeID source, size_t source_idx, NodeID sink, size_t sink_idx)
Adds a connection between two nodes.
bool remove_connection (EdgeID eid)
Removes an edge (connection)
std::string name () const
Returns graph name.
GraphID id () const
Returns graph id.
const std::vector< NodeID > & nodes (NodeType type)
Returns graph input nodes.
std::vector< std::unique_ptr< INode > > & nodes ()
Returns nodes of graph.
const std::vector< std::unique_ptr< INode > > & nodes () const
Returns nodes of graph.
const std::vector< std::unique_ptr< Edge > > & edges () const
Returns edges of graph.
std::vector< std::unique_ptr< Tensor > > & tensors ()
Returns tensors of graph.
const std::vector< std::unique_ptr< Tensor > > & tensors () const
Returns tensors of graph.
const INode * node (NodeID id) const
Get node object given its id.
INode * node (NodeID id)
Get node object given its id.
const Edge * edge (EdgeID id) const
Get edge object given its id.
Edge * edge (EdgeID id)
Get edge object given its id.
const Tensor * tensor (TensorID id) const
Get tensor object given its id.
Tensor * tensor (TensorID id)
Get tensor object given its id.
Detailed Description
Graph class.
Represents a multiple source - multiple sink directed graph
Definition at line 50 of file Graph.h.
Constructor & Destructor Documentation
Graph() [1/4]
Graph () default
Graph() [2/4]
Graph (GraphID id, std::string name)
Constructor.
Parameters
[in] id Graph identification number. Can be used to differentiate between graphs. Default value 0
[in] name Graph name. Default value empty string
Definition at line 30 of file Graph.cpp.
     : _id(id), _name(std::move(name)), _nodes(), _edges(), _tensors(), _tagged_nodes(), _mtx()
 {
 }
Graph() [3/4]
Graph (const Graph &) delete
Prevent instances of this class from being copied (As this class contains pointers)
Graph() [4/4]
Graph (Graph &&) default
Allow instances of this class to be moved.
Member Function Documentation
add_connection()
EdgeID add_connection (NodeID source, size_t source_idx, NodeID sink, size_t sink_idx)
Adds a connection between two nodes.
Parameters
[in] source ID of the source node
[in] source_idx Output index of the source node
[in] sink ID of the sink node
[in] sink_idx Input index of the sink node
Returns
ID of this connection
Definition at line 69 of file Graph.cpp.
 {
     std::lock_guard<arm_compute::Mutex> lock(_mtx);
     // Check if node index is valid, if node exists and finally if the connection index is valid
     ARM_COMPUTE_ERROR_ON((source >= _nodes.size()) || (_nodes[source] == nullptr) || (source_idx >= _nodes[source]->num_outputs()));
     ARM_COMPUTE_ERROR_ON((sink >= _nodes.size()) || (_nodes[sink] == nullptr) || (sink_idx >= _nodes[sink]->num_inputs()));
     // Get nodes
     std::unique_ptr<INode> &source_node = _nodes[source];
     std::unique_ptr<INode> &sink_node   = _nodes[sink];
     // Check for duplicate connections (Check only sink node)
     Edge *sink_node_edge = sink_node->input_edge(sink_idx);
     if((sink_node_edge != nullptr) && (sink_node_edge->producer_id() == source) && (sink_node_edge->producer_idx() == source_idx)
        && (sink_node_edge->consumer_id() == sink) && (sink_node_edge->consumer_idx() == sink_idx))
     {
         return sink_node_edge->id();
     }
     // Check if there is already a tensor associated with output if not create one
     TensorID tid = source_node->output_id(source_idx);
     if(tid == NullTensorID)
     {
         tid = create_tensor();
     }
     std::unique_ptr<Tensor> &tensor = _tensors[tid];
     // Create connections
     EdgeID eid        = _edges.size();
     auto   connection = arm_compute::support::cpp14::make_unique<Edge>(eid, source_node.get(), source_idx, sink_node.get(), sink_idx, tensor.get());
     _edges.push_back(std::move(connection));
     // Add connections to source and sink nodes
     source_node->_output_edges.insert(eid);
     sink_node->_input_edges[sink_idx] = eid;
     // Set tensor output node
     source_node->_outputs[source_idx] = tid;
     // Bind tensor to the edge
     tensor->bind_edge(eid);
     // Try and propagate shapes in sink node
     sink_node->forward_descriptors();
     return eid;
 }
References ARM_COMPUTE_ERROR_ON, Tensor::bind_edge(), Edge::consumer_id(), Edge::consumer_idx(), Edge::id(), arm_compute::graph::NullTensorID, Edge::producer_id(), Edge::producer_idx(), and Graph::tensor().
Referenced by GraphBuilder::add_batch_normalization_node(), GraphBuilder::add_bounding_box_transform_node(), GraphBuilder::add_convolution_node(), GraphBuilder::add_deconvolution_node(), GraphBuilder::add_depthwise_convolution_node(), GraphBuilder::add_detection_output_node(), GraphBuilder::add_elementwise_node(), GraphBuilder::add_fully_connected_layer(), GraphBuilder::add_generate_proposals_node(), GraphBuilder::add_normalize_planar_yuv_node(), GraphBuilder::add_output_node(), GraphBuilder::add_priorbox_node(), GraphBuilder::add_roi_align_node(), arm_compute::graph::detail::fuse_convolution_with_batch_normalization(), arm_compute::graph::detail::fuse_node_with_activation(), and GroupedConvolutionMutator::mutate().
add_node()
NodeID add_node (Ts &&... args) inline
Adds a node to the graph.
Note
Models a single output node
Template Parameters
NT Node operation
Ts Arguments to operation
Parameters
[in] args Node arguments
Returns
ID of the node
Definition at line 232 of file Graph.h.
 {
     std::lock_guard<arm_compute::Mutex> lock(_mtx);
     // Create node
     NodeID nid  = _nodes.size();
     auto   node = support::cpp14::make_unique<NT>(std::forward<Ts>(args)...);
     node->set_graph(this);
     node->set_id(nid);
     // Keep track of input nodes
     _tagged_nodes[node->type()].push_back(nid);
     // Associate a new tensor with each output
     for(auto &output : node->_outputs)
     {
         output = create_tensor();
     }
     // Propagate node shape if possible
     node->forward_descriptors();
     // Add node to the graph nodes
     _nodes.push_back(std::move(node));
     return nid;
 }
References INode::forward_descriptors(), Graph::node(), INode::set_graph(), INode::set_id(), and INode::type().
Referenced by GraphBuilder::add_batch_normalization_node(), GraphBuilder::add_bounding_box_transform_node(), GraphBuilder::add_const_node(), GraphBuilder::add_convolution_node(), GraphBuilder::add_deconvolution_node(), GraphBuilder::add_depthwise_convolution_node(), GraphBuilder::add_detection_output_node(), GraphBuilder::add_elementwise_node(), GraphBuilder::add_fully_connected_layer(), GraphBuilder::add_generate_proposals_node(), GraphBuilder::add_input_node(), GraphBuilder::add_normalize_planar_yuv_node(), GraphBuilder::add_output_node(), GraphBuilder::add_priorbox_node(), GraphBuilder::add_roi_align_node(), and arm_compute::graph::detail::fuse_convolution_with_batch_normalization().
edge() [1/2]
const Edge * edge (EdgeID id) const
Get edge object given its id.
Warning
Can be nullptr if node was removed during the mutation steps of the graph
Parameters
[in] id Edge ID
Returns
The actual edge object
Definition at line 214 of file Graph.cpp.
 {
     return (id >= _edges.size()) ? nullptr : _edges[id].get();
 }
Referenced by arm_compute::graph::detail::all_inputs_are_visited(), arm_compute::graph::bfs(), arm_compute::graph::dfs(), arm_compute::graph::detail::fuse_layer(), arm_compute::graph::get_driving_nodes(), INode::input(), INode::input_edge(), INode::input_id(), NodeFusionMutator::mutate(), DepthConcatSubTensorMutator::mutate(), Graph::remove_connection(), and INode::set_output_tensor().
edge() [2/2]
Edge * edge (EdgeID id)
Get edge object given its id.
Warning
Can be nullptr if node was removed during the mutation steps of the graph
Parameters
[in] id Edge ID
Returns
The actual edge object
Definition at line 219 of file Graph.cpp.
 {
     return (id >= _edges.size()) ? nullptr : _edges[id].get();
 }
edges()
const std::vector< std::unique_ptr< Edge > > & edges () const
Returns edges of graph.
Warning
Edges can be nullptr if they have been removed during the mutation steps of the graph
Returns
Edges of graph
Definition at line 189 of file Graph.cpp.
 {
     return _edges;
 }
id()
GraphID id () const
Returns graph id.
Returns
Graph id
Definition at line 169 of file Graph.cpp.
 {
     return _id;
 }
Referenced by GraphManager::execute_graph(), GraphManager::finalize_graph(), and GraphManager::invalidate_graph().
name()
std::string name () const
Returns graph name.
Returns
Graph name
Definition at line 164 of file Graph.cpp.
 {
     return _name;
 }
node() [1/2]
const INode * node (NodeID id) const
Get node object given its id.
Warning
Can be nullptr if node was removed during the mutation steps of the graph
Parameters
[in] id Node ID
Returns
The actual node object
Definition at line 204 of file Graph.cpp.
 {
     return (id >= _nodes.size()) ? nullptr : _nodes[id].get();
 }
Referenced by GraphBuilder::add_batch_normalization_node(), GraphBuilder::add_convolution_node(), GraphBuilder::add_deconvolution_node(), GraphBuilder::add_depthwise_convolution_node(), GraphBuilder::add_fully_connected_layer(), Graph::add_node(), GraphBuilder::add_normalize_planar_yuv_node(), GraphBuilder::add_scale_layer(), arm_compute::graph::bfs(), arm_compute::graph::detail::configure_all_nodes(), ConcatLayer::create_layer(), StackLayer::create_layer(), arm_compute::graph::dfs(), arm_compute::graph::detail::fuse_convolution_with_batch_normalization(), DepthConcatSubTensorMutator::mutate(), SplitLayerSubTensorMutator::mutate(), GroupedConvolutionMutator::mutate(), and Graph::remove_node().
node() [2/2]
INode * node (NodeID id)
Get node object given its id.
Warning
Can be nullptr if node was removed during the mutation steps of the graph
Parameters
[in] id Node ID
Returns
The actual node object
Definition at line 209 of file Graph.cpp.
 {
     return (id >= _nodes.size()) ? nullptr : _nodes[id].get();
 }
nodes() [1/3]
const std::vector< NodeID > & nodes (NodeType type)
Returns graph input nodes.
Parameters
[in] type Type of nodes to return
Returns
vector containing the graph node of given type
Definition at line 174 of file Graph.cpp.
 {
     return _tagged_nodes[type];
 }
Referenced by arm_compute::graph::detail::allocate_const_tensors(), arm_compute::graph::bfs(), arm_compute::graph::detail::call_all_const_node_accessors(), arm_compute::graph::detail::configure_all_nodes(), arm_compute::graph::dfs(), arm_compute::graph::force_target_to_graph(), arm_compute::graph::detail::fuse_layer(), InPlaceOperationMutator::mutate(), SplitLayerSubTensorMutator::mutate(), DepthConcatSubTensorMutator::mutate(), GroupedConvolutionMutator::mutate(), and arm_compute::graph::detail::validate_all_nodes().
nodes() [2/3]
std::vector< std::unique_ptr< INode > > & nodes ()
Returns nodes of graph.
Warning
Nodes can be nullptr if they have been removed during the mutation steps of the graph
Returns
Nodes of graph
Definition at line 179 of file Graph.cpp.
 {
     return _nodes;
 }
nodes() [3/3]
const std::vector< std::unique_ptr< INode > > & nodes () const
Returns nodes of graph.
Warning
Nodes can be nullptr if they have been removed during the mutation steps of the graph
Returns
Nodes of graph
Definition at line 184 of file Graph.cpp.
 {
     return _nodes;
 }
operator=() [1/2]
Graph& operator= (const Graph &) delete
Prevent instances of this class from being copy assigned (As this class contains pointers)
operator=() [2/2]
Graph& operator= (Graph &&) default
Allow instances of this class to be move assigned.
remove_connection()
bool remove_connection (EdgeID eid)
Removes an edge (connection)
Parameters
[in] eid Connection to remove
Returns
True if the removal took place else false
Definition at line 118 of file Graph.cpp.
 {
     if(eid >= _edges.size())
     {
         return false;
     }
     std::unique_ptr<Edge> &edge = _edges[eid];
     // Remove node connections
     if(edge != nullptr)
     {
         // Get tensor bound to the edge
         if(edge->tensor() != nullptr)
         {
             edge->tensor()->unbind_edge(eid);
         }
         // Remove edges from source node
         if(edge->producer() != nullptr)
         {
             edge->producer()->_output_edges.erase(eid);
         }
         // Remove edges from sink node
         if((edge->consumer() != nullptr) && (edge->consumer_idx() < edge->consumer()->_input_edges.size()))
         {
             edge->consumer()->_input_edges[edge->consumer_idx()] = EmptyEdgeID;
         }
     }
     // Clear edge
     edge = nullptr;
     return true;
 }
References Edge::consumer(), Edge::consumer_idx(), Graph::edge(), arm_compute::graph::EmptyEdgeID, Edge::producer(), Edge::tensor(), and Tensor::unbind_edge().
Referenced by Graph::remove_node().
remove_node()
bool remove_node (NodeID nid)
Remove the node with the given ID.
Parameters
[in] nid ID of the node to remove
Returns
True if the removal took place else false
Definition at line 35 of file Graph.cpp.
 {
     if(nid >= _nodes.size())
     {
         return false;
     }
     std::unique_ptr<INode> &node = _nodes[nid];
     if(node)
     {
         // Remove input connections
         for(auto &input_eid : node->_input_edges)
         {
             remove_connection(input_eid);
         }
         // Remove output connections
         std::set<EdgeID> output_edges_copy = node->output_edges();
         for(auto &outpud_eid : output_edges_copy)
         {
             remove_connection(outpud_eid);
         }
         // Remove nid from tagged nodes
         std::vector<NodeID> &tnodes = _tagged_nodes.at(node->type());
         tnodes.erase(std::remove(tnodes.begin(), tnodes.end(), nid), tnodes.end());
     }
     node = nullptr;
     return true;
 }
References Graph::node(), INode::output_edges(), Graph::remove_connection(), and INode::type().
Referenced by arm_compute::graph::detail::fuse_convolution_with_batch_normalization(), arm_compute::graph::detail::fuse_node_with_activation(), and GroupedConvolutionMutator::mutate().
tensor() [1/2]
const Tensor * tensor (TensorID id) const
Get tensor object given its id.
Warning
Can be nullptr if tensor was removed during the mutation steps of the graph
Parameters
[in] id Tensor ID
Returns
The actual tensor object
Definition at line 224 of file Graph.cpp.
 {
     return (id >= _tensors.size()) ? nullptr : _tensors[id].get();
 }
Referenced by Graph::add_connection(), arm_compute::graph::get_tensor_descriptor(), SplitLayerSubTensorMutator::mutate(), INode::output(), and INode::set_output_tensor().
tensor() [2/2]
Tensor * tensor (TensorID id)
Get tensor object given its id.
Warning
Can be nullptr if tensor was removed during the mutation steps of the graph
Parameters
[in] id Tensor ID
Returns
The actual tensor object
Definition at line 229 of file Graph.cpp.
 {
     return (id >= _tensors.size()) ? nullptr : _tensors[id].get();
 }
tensors() [1/2]
std::vector< std::unique_ptr< Tensor > > & tensors ()
Returns tensors of graph.
Warning
Tensor can be nullptr if they have been removed during the mutation steps of the graph
Returns
Tensors of graph
Definition at line 194 of file Graph.cpp.
 {
     return _tensors;
 }
Referenced by arm_compute::graph::detail::allocate_all_tensors(), arm_compute::graph::detail::configure_all_tensors(), arm_compute::graph::force_target_to_graph(), GroupedConvolutionMutator::mutate(), and arm_compute::graph::detail::release_unused_tensors().
tensors() [2/2]
const std::vector< std::unique_ptr< Tensor > > & tensors () const
Returns tensors of graph.
Warning
Tensor can be nullptr if they have been removed during the mutation steps of the graph
Returns
Tensors of graph
Definition at line 199 of file Graph.cpp.
 {
     return _tensors;
 }
The documentation for this class was generated from the following files:
arm_compute/graph/Graph.h
src/graph/Graph.cpp