Compute Library: NEDepthwiseVectorToTensorKernel Class Reference
NEDepthwiseVectorToTensorKernel Class Reference
Interface for the depthwise vector to tensor kernel.
#include <NEDepthwiseVectorToTensorKernel.h>
Public Member Functions
const char * name () const override
Name of the kernel.
NEDepthwiseVectorToTensorKernel ()
Default constructor.
NEDepthwiseVectorToTensorKernel (const NEDepthwiseVectorToTensorKernel &)=delete
Prevent instances of this class from being copied (As this class contains pointers)
NEDepthwiseVectorToTensorKernel & operator= (const NEDepthwiseVectorToTensorKernel &)=delete
Prevent instances of this class from being copied (As this class contains pointers)
NEDepthwiseVectorToTensorKernel (NEDepthwiseVectorToTensorKernel &&)=default
Allow instances of this class to be moved.
NEDepthwiseVectorToTensorKernel & operator= (NEDepthwiseVectorToTensorKernel &&)=default
Allow instances of this class to be moved.
void configure (const ITensor *input, ITensor *output, size_t conv_w, size_t conv_h)
Set the input and output of the kernel.
void run (const Window &window, const ThreadInfo &info) override
Execute the kernel on the passed window.
Public Member Functions inherited from ICPPKernel
virtual ~ICPPKernel ()=default
Default destructor.
Public Member Functions inherited from IKernel
IKernel ()
Constructor.
virtual ~IKernel ()=default
Destructor.
virtual bool is_parallelisable () const
Indicates whether or not the kernel is parallelisable.
virtual BorderSize border_size () const
The size of the border for that kernel.
const Window & window () const
The maximum window the kernel can be executed on.
Static Public Member Functions
static Status validate (const ITensorInfo *input, const ITensorInfo *output, size_t conv_w, size_t conv_h)
Static function to check if given info will lead to a valid configuration of NEDepthwiseVectorToTensorKernel.
Detailed Description
Interface for the depthwise vector to tensor kernel.
This kernel takes the 1D tensor that's been produced by the MatrixVectorMultiply kernel and reshapes it to given width and height (previously calculated, based on input/weights dimensions and convolution strides and padding).
Definition at line 40 of file NEDepthwiseVectorToTensorKernel.h.
Constructor & Destructor Documentation
NEDepthwiseVectorToTensorKernel() [1/3]
NEDepthwiseVectorToTensorKernel ()
Default constructor.
Definition at line 93 of file NEDepthwiseVectorToTensorKernel.cpp.
     : _func(nullptr), _input(nullptr), _output(nullptr), _conv_dims()
 {
 }
NEDepthwiseVectorToTensorKernel() [2/3]
NEDepthwiseVectorToTensorKernel (const NEDepthwiseVectorToTensorKernel &) delete
Prevent instances of this class from being copied (As this class contains pointers)
NEDepthwiseVectorToTensorKernel() [3/3]
NEDepthwiseVectorToTensorKernel (NEDepthwiseVectorToTensorKernel &&) default
Allow instances of this class to be moved.
Member Function Documentation
configure()
void configure (const ITensor * input, ITensor * output, size_t conv_w, size_t conv_h)
Set the input and output of the kernel.
Parameters
[in] input The input vector to convert. Data type supported: QASYMM8/S32/F16/F32.
[out] output The output tensor. 3 lower dimensions represent a single input [width, height, IFM]. Data type supported: same as input.
[in] conv_w The converted tensor's width.
[in] conv_h The converted tensor's height.
Definition at line 98 of file NEDepthwiseVectorToTensorKernel.cpp.
 {
     ARM_COMPUTE_ERROR_ON_NULLPTR(input, output);
     // Output auto inizialitation if not yet initialized
     TensorShape output_shape = compute_vector_to_tensor_output_shape(input->info()->tensor_shape(), conv_w, conv_h, output->info()->data_layout());
     auto_init_if_empty(*output->info(), input->info()->clone()->set_tensor_shape(output_shape));
     ARM_COMPUTE_ERROR_THROW_ON(validate_arguments(input->info(), output->info(), conv_w, conv_h));
     _input     = input;
     _output    = output;
     _conv_dims = std::pair<size_t, size_t>(conv_w, conv_h);
     // Set appropriate function to run
     switch(input->info()->data_type())
     {
         case DataType::QASYMM8:
             _func = &NEDepthwiseVectorToTensorKernel::vector_to_tensor<uint8_t>;
             break;
         case DataType::S32:
             _func = &NEDepthwiseVectorToTensorKernel::vector_to_tensor<int32_t>;
             break;
         case DataType::F16:
             _func = &NEDepthwiseVectorToTensorKernel::vector_to_tensor<half>;
             break;
         case DataType::F32:
             _func = &NEDepthwiseVectorToTensorKernel::vector_to_tensor<float>;
             break;
         default:
             ARM_COMPUTE_ERROR("Unsupported data type");
     }
     // Configure  kernel window
     Window win = calculate_max_window(*input->info(), Steps());
     // The NEDepthwisevectorToTensorKernel doesn't need padding so update_window_and_padding() can be skipped
     output->info()->set_valid_region(ValidRegion(Coordinates(), output->info()->tensor_shape()));
     INEKernel::configure(win);
 }
References ARM_COMPUTE_ERROR, ARM_COMPUTE_ERROR_ON_NULLPTR, ARM_COMPUTE_ERROR_THROW_ON, arm_compute::auto_init_if_empty(), arm_compute::calculate_max_window(), ICloneable< T >::clone(), arm_compute::misc::shape_calculator::compute_vector_to_tensor_output_shape(), ITensorInfo::data_layout(), ITensorInfo::data_type(), arm_compute::F16, arm_compute::F32, ITensor::info(), arm_compute::test::validation::output_shape, arm_compute::QASYMM8, arm_compute::S32, ITensorInfo::set_valid_region(), and ITensorInfo::tensor_shape().
Referenced by NEDepthwiseConvolutionLayer::configure().
name()
const char* name () const inline override virtual
Name of the kernel.
Returns
Kernel name
Implements ICPPKernel.
Definition at line 43 of file NEDepthwiseVectorToTensorKernel.h.
     {
         return "NEDepthwiseVectorToTensorKernel";
     }
operator=() [1/2]
NEDepthwiseVectorToTensorKernel& operator= (const NEDepthwiseVectorToTensorKernel &) delete
Prevent instances of this class from being copied (As this class contains pointers)
operator=() [2/2]
NEDepthwiseVectorToTensorKernel& operator= (NEDepthwiseVectorToTensorKernel &&) default
Allow instances of this class to be moved.
run()
void run (const Window & window, const ThreadInfo & info) override virtual
Execute the kernel on the passed window.
Warning
If is_parallelisable() returns false then the passed window must be equal to window()
Note
The window has to be a region within the window returned by the window() method
The width of the window has to be a multiple of num_elems_processed_per_iteration().
Parameters
[in] window Region on which to execute the kernel. (Must be a region of the window returned by window())
[in] info Info about executing thread and CPU.
Implements ICPPKernel.
Definition at line 146 of file NEDepthwiseVectorToTensorKernel.cpp.
 {
     ARM_COMPUTE_UNUSED(info);
     ARM_COMPUTE_ERROR_ON_UNCONFIGURED_KERNEL(this);
     ARM_COMPUTE_ERROR_ON_INVALID_SUBWINDOW(INEKernel::window(), window);
     if(_func != nullptr)
     {
         (this->*_func)(window);
     }
 }
References ARM_COMPUTE_ERROR_ON_INVALID_SUBWINDOW, ARM_COMPUTE_ERROR_ON_UNCONFIGURED_KERNEL, ARM_COMPUTE_UNUSED, arm_compute::test::validation::info, and IKernel::window().
validate()
Status validate (const ITensorInfo * input, const ITensorInfo * output, size_t conv_w, size_t conv_h) static
Static function to check if given info will lead to a valid configuration of NEDepthwiseVectorToTensorKernel.
Parameters
[in] input The input vector to convert. Data type supported: QASYMM8/S32/F16/F32.
[in] output The output tensor. 3 lower dimensions represent a single input [width, height, IFM]. Data type supported: same as input.
[in] conv_w The converted tensor's width.
[in] conv_h The converted tensor's height.
Definition at line 139 of file NEDepthwiseVectorToTensorKernel.cpp.
 {
     ARM_COMPUTE_RETURN_ERROR_ON_NULLPTR(input, output);
     ARM_COMPUTE_RETURN_ON_ERROR(validate_arguments(input, output, conv_w, conv_h));
     return Status{};
 }
References ARM_COMPUTE_RETURN_ERROR_ON_NULLPTR, and ARM_COMPUTE_RETURN_ON_ERROR.
Referenced by NEDepthwiseConvolutionLayer::validate().
The documentation for this class was generated from the following files:
arm_compute/core/NEON/kernels/NEDepthwiseVectorToTensorKernel.h
src/core/NEON/kernels/NEDepthwiseVectorToTensorKernel.cpp