Compute Library: CLPriorBoxLayerKernel Class Reference
CLPriorBoxLayerKernel Class Reference
Interface for the PriorBox layer kernel.
#include <CLPriorBoxLayerKernel.h>
Public Member Functions
CLPriorBoxLayerKernel ()
Constructor.
CLPriorBoxLayerKernel (const CLPriorBoxLayerKernel &)=delete
Prevent instances of this class from being copied (As this class contains pointers)
CLPriorBoxLayerKernel & operator= (const CLPriorBoxLayerKernel &)=delete
Prevent instances of this class from being copied (As this class contains pointers)
CLPriorBoxLayerKernel (CLPriorBoxLayerKernel &&)=default
Default Move Constructor.
CLPriorBoxLayerKernel & operator= (CLPriorBoxLayerKernel &&)=default
Default move assignment operator.
~CLPriorBoxLayerKernel ()=default
Default destructor.
void configure (const ICLTensor *input1, const ICLTensor *input2, ICLTensor *output, const PriorBoxLayerInfo &info, cl::Buffer *min, cl::Buffer *max, cl::Buffer *aspect_ratios)
Set the input and output tensors.
void run (const Window &window, cl::CommandQueue &queue) override
Enqueue the OpenCL kernel to process the given window on the passed OpenCL command queue.
Public Member Functions inherited from ICLKernel
ICLKernel ()
Constructor.
cl::Kernel & kernel ()
Returns a reference to the OpenCL kernel of this object.
template<typename T >
void add_1D_array_argument (unsigned int &idx, const ICLArray< T > *array, const Strides &strides, unsigned int num_dimensions, const Window &window)
Add the passed 1D array's parameters to the object's kernel's arguments starting from the index idx.
void add_1D_tensor_argument (unsigned int &idx, const ICLTensor *tensor, const Window &window)
Add the passed 1D tensor's parameters to the object's kernel's arguments starting from the index idx.
void add_2D_tensor_argument (unsigned int &idx, const ICLTensor *tensor, const Window &window)
Add the passed 2D tensor's parameters to the object's kernel's arguments starting from the index idx.
void add_3D_tensor_argument (unsigned int &idx, const ICLTensor *tensor, const Window &window)
Add the passed 3D tensor's parameters to the object's kernel's arguments starting from the index idx.
void add_4D_tensor_argument (unsigned int &idx, const ICLTensor *tensor, const Window &window)
Add the passed 4D tensor's parameters to the object's kernel's arguments starting from the index idx.
template<typename T >
void add_argument (unsigned int &idx, T value)
Add the passed parameters to the object's kernel's arguments starting from the index idx.
void set_lws_hint (const cl::NDRange &lws_hint)
Set the Local-Workgroup-Size hint.
cl::NDRange lws_hint () const
Return the Local-Workgroup-Size hint.
const std::string & config_id () const
Get the configuration ID.
void set_target (GPUTarget target)
Set the targeted GPU architecture.
void set_target (cl::Device &device)
Set the targeted GPU architecture according to the CL device.
GPUTarget get_target () const
Get the targeted GPU architecture.
size_t get_max_workgroup_size ()
Get the maximum workgroup size for the device the CLKernelLibrary uses.
template<typename T , unsigned int dimension_size>
void add_array_argument (unsigned &idx, const ICLArray< T > *array, const Strides &strides, unsigned int num_dimensions, const Window &window)
Add the passed array's parameters to the object's kernel's arguments starting from the index idx.
template<unsigned int dimension_size>
void add_tensor_argument (unsigned &idx, const ICLTensor *tensor, const Window &window)
Public Member Functions inherited from IKernel
IKernel ()
Constructor.
virtual ~IKernel ()=default
Destructor.
virtual bool is_parallelisable () const
Indicates whether or not the kernel is parallelisable.
virtual BorderSize border_size () const
The size of the border for that kernel.
const Window & window () const
The maximum window the kernel can be executed on.
Static Public Member Functions
static Status validate (const ITensorInfo *input1, const ITensorInfo *input2, const ITensorInfo *output, const PriorBoxLayerInfo &info)
Static function to check if given info will lead to a valid configuration of CLPriorBoxLayerKernel.
Static Public Member Functions inherited from ICLKernel
static constexpr unsigned int num_arguments_per_1D_array ()
Returns the number of arguments enqueued per 1D array object.
static constexpr unsigned int num_arguments_per_1D_tensor ()
Returns the number of arguments enqueued per 1D tensor object.
static constexpr unsigned int num_arguments_per_2D_tensor ()
Returns the number of arguments enqueued per 2D tensor object.
static constexpr unsigned int num_arguments_per_3D_tensor ()
Returns the number of arguments enqueued per 3D tensor object.
static constexpr unsigned int num_arguments_per_4D_tensor ()
Returns the number of arguments enqueued per 4D tensor object.
static cl::NDRange gws_from_window (const Window &window)
Get the global work size given an execution window.
Detailed Description
Interface for the PriorBox layer kernel.
Definition at line 34 of file CLPriorBoxLayerKernel.h.
Constructor & Destructor Documentation
CLPriorBoxLayerKernel() [1/3]
CLPriorBoxLayerKernel ()
Constructor.
Definition at line 98 of file CLPriorBoxLayerKernel.cpp.
     : _input1(nullptr), _input2(nullptr), _output(nullptr), _info(), _num_priors(), _min(), _max(), _aspect_ratios()
 {
 }
CLPriorBoxLayerKernel() [2/3]
CLPriorBoxLayerKernel (const CLPriorBoxLayerKernel &) delete
Prevent instances of this class from being copied (As this class contains pointers)
CLPriorBoxLayerKernel() [3/3]
CLPriorBoxLayerKernel (CLPriorBoxLayerKernel &&) default
Default Move Constructor.
~CLPriorBoxLayerKernel()
~CLPriorBoxLayerKernel () default
Default destructor.
Member Function Documentation
configure()
void configure (const ICLTensor * input1, const ICLTensor * input2, ICLTensor * output, const PriorBoxLayerInfo & info, cl::Buffer * min, cl::Buffer * max, cl::Buffer * aspect_ratios)
Set the input and output tensors.
Parameters
[in] input1 First source tensor. Data types supported: F32. Data layouts supported: NCHW/NHWC.
[in] input2 Second source tensor. Data types and layouts supported: same as input1
[out] output Destination tensor. Output dimensions are [W * H * num_priors * 4, 2]. Data types and layouts supported: same as input1
[in] info Prior box layer info.
[in] min Minimum prior box values
[in] max Maximum prior box values
[in] aspect_ratios Aspect ratio values
Definition at line 103 of file CLPriorBoxLayerKernel.cpp.
 {
     ARM_COMPUTE_ERROR_ON_NULLPTR(input1, input2, output);
     _input1        = input1;
     _input2        = input2;
     _output        = output;
     _info          = info;
     _min           = min;
     _max           = max;
     _aspect_ratios = aspect_ratios;
     ARM_COMPUTE_ERROR_THROW_ON(validate_arguments(input1->info(), input2->info(), output->info(), info));
     // Calculate number of aspect ratios
     _num_priors = info.aspect_ratios().size() * info.min_sizes().size() + info.max_sizes().size();
     const DataLayout data_layout = input1->info()->data_layout();
     const int width_idx  = get_data_layout_dimension_index(data_layout, DataLayoutDimension::WIDTH);
     const int height_idx = get_data_layout_dimension_index(data_layout, DataLayoutDimension::HEIGHT);
     const int layer_width  = input1->info()->dimension(width_idx);
     const int layer_height = input1->info()->dimension(height_idx);
     int img_width  = info.img_size().x;
     int img_height = info.img_size().y;
     if(img_width == 0 || img_height == 0)
     {
         img_width  = input2->info()->dimension(width_idx);
         img_height = input2->info()->dimension(height_idx);
     }
     float step_x = info.steps()[0];
     float step_y = info.steps()[0];
     if(step_x == 0.f || step_y == 0.f)
     {
         step_x = static_cast<float>(img_width) / layer_width;
         step_y = static_cast<float>(img_height) / layer_height;
     }
     // Set build options
     CLBuildOptions build_opts;
     build_opts.add_option("-DDATA_TYPE=" + get_cl_type_from_data_type(input1->info()->data_type()));
     build_opts.add_option("-DWIDTH=" + support::cpp11::to_string(img_width));
     build_opts.add_option("-DHEIGHT=" + support::cpp11::to_string(img_height));
     build_opts.add_option("-DLAYER_WIDTH=" + support::cpp11::to_string(layer_width));
     build_opts.add_option("-DLAYER_HEIGHT=" + support::cpp11::to_string(layer_height));
     build_opts.add_option("-DSTEP_X=" + support::cpp11::to_string(step_x));
     build_opts.add_option("-DSTEP_Y=" + support::cpp11::to_string(step_y));
     build_opts.add_option("-DNUM_PRIORS=" + support::cpp11::to_string(_num_priors));
     build_opts.add_option("-DOFFSET=" + support::cpp11::to_string(info.offset()));
     build_opts.add_option_if(info.clip(), "-DIN_PLACE");
     if(info.variances().size() > 1)
     {
         for(unsigned int i = 0; i < info.variances().size(); ++i)
         {
             build_opts.add_option("-DVARIANCE_" + support::cpp11::to_string(i) + "=" + support::cpp11::to_string(info.variances().at(i)));
         }
     }
     else
     {
         for(unsigned int i = 0; i < 4; ++i)
         {
             build_opts.add_option("-DVARIANCE_" + support::cpp11::to_string(i) + "=" + support::cpp11::to_string(info.variances().at(0)));
         }
     }
     unsigned int idx = num_arguments_per_2D_tensor();
     _kernel          = static_cast<cl::Kernel>(CLKernelLibrary::get().create_kernel("prior_box_layer_nchw", build_opts.options()));
     _kernel.setArg(idx++, *_min);
     _kernel.setArg(idx++, *_max);
     _kernel.setArg(idx++, *_aspect_ratios);
     _kernel.setArg<unsigned int>(idx++, info.min_sizes().size());
     _kernel.setArg<unsigned int>(idx++, info.max_sizes().size());
     _kernel.setArg<unsigned int>(idx++, info.aspect_ratios().size());
     // Configure kernel window
     auto win_config = validate_and_configure_window(input1->info(), input2->info(), output->info(), info, _num_priors);
     ARM_COMPUTE_ERROR_THROW_ON(win_config.first);
     ICLKernel::configure_internal(win_config.second);
 }
References CLBuildOptions::add_option(), CLBuildOptions::add_option_if(), ARM_COMPUTE_ERROR_ON_NULLPTR, ARM_COMPUTE_ERROR_THROW_ON, arm_compute::create_kernel(), ITensorInfo::data_layout(), ITensorInfo::data_type(), ITensorInfo::dimension(), CLKernelLibrary::get(), arm_compute::get_cl_type_from_data_type(), arm_compute::get_data_layout_dimension_index(), arm_compute::HEIGHT, ITensor::info(), arm_compute::test::validation::info, ICLKernel::num_arguments_per_2D_tensor(), CLBuildOptions::options(), arm_compute::support::cpp11::to_string(), and arm_compute::WIDTH.
operator=() [1/2]
CLPriorBoxLayerKernel& operator= (const CLPriorBoxLayerKernel &) delete
Prevent instances of this class from being copied (As this class contains pointers)
operator=() [2/2]
CLPriorBoxLayerKernel& operator= (CLPriorBoxLayerKernel &&) default
Default move assignment operator.
run()
void run (const Window & window, cl::CommandQueue & queue) override virtual
Enqueue the OpenCL kernel to process the given window on the passed OpenCL command queue.
Note
The queue is not flushed by this method, and therefore the kernel will not have been executed by the time this method returns.
Parameters
[in] window Region on which to execute the kernel. (Must be a valid region of the window returned by window()).
[in,out] queue Command queue on which to enqueue the kernel.
Implements ICLKernel.
Definition at line 200 of file CLPriorBoxLayerKernel.cpp.
 {
     ARM_COMPUTE_ERROR_ON_UNCONFIGURED_KERNEL(this);
     ARM_COMPUTE_ERROR_ON_INVALID_SUBWINDOW(IKernel::window(), window);
     queue.enqueueWriteBuffer(*_min, CL_TRUE, 0, _info.min_sizes().size() * sizeof(float), _info.min_sizes().data());
     queue.enqueueWriteBuffer(*_aspect_ratios, CL_TRUE, 0, _info.aspect_ratios().size() * sizeof(float), _info.aspect_ratios().data());
     if(!_info.max_sizes().empty())
     {
         queue.enqueueWriteBuffer(*_max, CL_TRUE, 0, _info.max_sizes().size() * sizeof(float), _info.max_sizes().data());
     }
     Window slice = window.first_slice_window_2D();
     slice.set(Window::DimY, Window::Dimension(0, _output->info()->dimension(1), 2));
     unsigned int idx = 0;
     add_2D_tensor_argument(idx, _output, slice);
     enqueue(queue, *this, slice);
 }
References ICLKernel::add_2D_tensor_argument(), ARM_COMPUTE_ERROR_ON_INVALID_SUBWINDOW, ARM_COMPUTE_ERROR_ON_UNCONFIGURED_KERNEL, PriorBoxLayerInfo::aspect_ratios(), ITensorInfo::dimension(), Window::DimY, arm_compute::enqueue(), Window::first_slice_window_2D(), ITensor::info(), PriorBoxLayerInfo::max_sizes(), PriorBoxLayerInfo::min_sizes(), arm_compute::test::validation::reference::slice(), and IKernel::window().
validate()
Status validate (const ITensorInfo * input1, const ITensorInfo * input2, const ITensorInfo * output, const PriorBoxLayerInfo & info) static
Static function to check if given info will lead to a valid configuration of CLPriorBoxLayerKernel.
Parameters
[in] input1 First source tensor info. Data types supported: F32. Data layouts supported: NCHW/NHWC.
[in] input2 Second source tensor info. Data types and layouts supported: same as input1
[in] output Destination tensor info. Output dimensions are [W * H * num_priors * 4, 2]. Data type supported: same as input1
[in] info Prior box layer info.
Returns
a status
Definition at line 189 of file CLPriorBoxLayerKernel.cpp.
 {
     ARM_COMPUTE_ERROR_ON_NULLPTR(input1, input2, output);
     ARM_COMPUTE_RETURN_ON_ERROR(validate_arguments(input1, input2, output, info));
     const int num_priors = info.aspect_ratios().size() * info.min_sizes().size() + info.max_sizes().size();
     ARM_COMPUTE_RETURN_ON_ERROR(validate_and_configure_window(input1->clone().get(), input2->clone().get(), output->clone().get(), info, num_priors)
                                 .first);
     return Status{};
 }
References ARM_COMPUTE_ERROR_ON_NULLPTR, ARM_COMPUTE_RETURN_ON_ERROR, ICloneable< T >::clone(), and arm_compute::test::validation::info.
Referenced by CLPriorBoxLayer::validate().
The documentation for this class was generated from the following files:
arm_compute/core/CL/kernels/CLPriorBoxLayerKernel.h
src/core/CL/kernels/CLPriorBoxLayerKernel.cpp