Compute Library: NEWidthConcatenateLayer Class Reference
NEWidthConcatenateLayer Class Reference
Basic function to execute concatenate tensors along x axis.
#include <NEWidthConcatenateLayer.h>
Public Member Functions
NEWidthConcatenateLayer ()
Default constructor.
void configure (std::vector< ITensor * > inputs_vector, ITensor *output)
Initialise the kernel's inputs vector and output.
void configure (std::vector< const ITensor * > inputs_vector, ITensor *output)
void run () override
Run the kernels contained in the function.
Public Member Functions inherited from IFunction
virtual ~IFunction ()=default
Destructor.
virtual void prepare ()
Prepare the function for executing.
Static Public Member Functions
static Status validate (const std::vector< ITensorInfo * > &inputs_vector, const ITensorInfo *output)
Static function to check if given info will lead to a valid configuration of NEWidthConcatenateLayer.
static Status validate (const std::vector< const ITensorInfo * > &inputs_vector, const ITensorInfo *output)
Detailed Description
Basic function to execute concatenate tensors along x axis.
This function calls the following kernel:
NEWidthConcatenateLayerKernel
Deprecated:
This function is deprecated and will be removed in release 19.08
Definition at line 50 of file NEWidthConcatenateLayer.h.
Constructor & Destructor Documentation
NEWidthConcatenateLayer()
NEWidthConcatenateLayer ()
Default constructor.
Definition at line 37 of file NEWidthConcatenateLayer.cpp.
     : _concat_kernels_vector(),
       _num_inputs(0)
 {
 }
Member Function Documentation
configure() [1/2]
void configure (std::vector< ITensor * > inputs_vector, ITensor * output)
Initialise the kernel's inputs vector and output.
Parameters
[in] inputs_vector The vectors containing all the tensors to concatenate. Data types supported: U8/S8/QASYMM8/U16/S16/F16/U32/S32/F32. Dimensions of all the inputs should match apart for the width which can differ.
[out] output Output tensor. Data types supported: Same as input. Output tensor dimensions are the same with the inputs from the second dimension and above. The first dimension (width) is the sum of the input tensors' widths.
Definition at line 91 of file NEWidthConcatenateLayer.cpp.
 {
     configure_internal(std::move(inputs_vector), output);
 }
Referenced by NELSTMLayer::configure().
configure() [2/2]
void configure (std::vector< const ITensor * > inputs_vector, ITensor * output)
Definition at line 96 of file NEWidthConcatenateLayer.cpp.
 {
     configure_internal(std::move(inputs_vector), output);
 }
run()
void run () override virtual
Run the kernels contained in the function.
For NEON kernels:
Multi-threading is used for the kernels which are parallelisable.
By default std::thread::hardware_concurrency() threads are used.
Note
CPPScheduler::set_num_threads() can be used to manually set the number of threads
For OpenCL kernels:
All the kernels are enqueued on the queue associated with CLScheduler.
The queue is then flushed.
Note
The function will not block until the kernels are executed. It is the user's responsibility to wait.
Will call prepare() on first run if hasn't been done
Implements IFunction.
Definition at line 111 of file NEWidthConcatenateLayer.cpp.
 {
     for(unsigned i = 0; i < _num_inputs; ++i)
     {
         NEScheduler::get().schedule(&_concat_kernels_vector[i], Window::DimY);
     }
 }
References Window::DimY, Scheduler::get(), and IScheduler::schedule().
Referenced by NELSTMLayer::prepare(), and NELSTMLayer::run().
validate() [1/2]
Status validate (const std::vector< ITensorInfo * > & inputs_vector, const ITensorInfo * output) static
Static function to check if given info will lead to a valid configuration of NEWidthConcatenateLayer.
Parameters
[in] inputs_vector The vectors containing all the tensors to concatenate. Data types supported: U8/S8/QASYMM8/U16/S16/F16/U32/S32/F32. Dimensions of all the inputs should match apart for the width which can differ.
[in] output Output tensor. Data types supported: Same as input. Output tensor dimensions are the same with the inputs from the second dimension and above. The first dimension (width) is the sum of the input tensors' widths.
Returns
a status
Definition at line 101 of file NEWidthConcatenateLayer.cpp.
 {
     return validate_internal(inputs_vector, output);
 }
Referenced by NELSTMLayer::validate().
validate() [2/2]
Status validate (const std::vector< const ITensorInfo * > & inputs_vector, const ITensorInfo * output) static
Definition at line 106 of file NEWidthConcatenateLayer.cpp.
 {
     return validate_internal(inputs_vector, output);
 }
The documentation for this class was generated from the following files:
arm_compute/runtime/NEON/functions/NEWidthConcatenateLayer.h
src/runtime/NEON/functions/NEWidthConcatenateLayer.cpp