Compute Library: CLDepthwiseConvolutionLayer3x3 Class Reference
CLDepthwiseConvolutionLayer3x3 Class Reference
Basic function to execute a depthwise convolution for kernel size 3x3xC (when data layout NCHW) or Cx3x3 (when data layout NHWC).
#include <CLDepthwiseConvolutionLayer.h>
Public Member Functions
CLDepthwiseConvolutionLayer3x3 (std::shared_ptr< IMemoryManager > memory_manager=nullptr)
Default constructor.
CLDepthwiseConvolutionLayer3x3 (const CLDepthwiseConvolutionLayer3x3 &)=delete
Prevent instances of this class from being copied (As this class contains pointers)
CLDepthwiseConvolutionLayer3x3 (CLDepthwiseConvolutionLayer3x3 &&)=default
Default move constructor.
CLDepthwiseConvolutionLayer3x3 & operator= (const CLDepthwiseConvolutionLayer3x3 &)=delete
Prevent instances of this class from being copied (As this class contains pointers)
CLDepthwiseConvolutionLayer3x3 & operator= (CLDepthwiseConvolutionLayer3x3 &&)=default
Default move assignment operator.
void configure (ICLTensor *input, const ICLTensor *weights, const ICLTensor *biases, ICLTensor *output, const PadStrideInfo &conv_info, unsigned int depth_multiplier=1, ActivationLayerInfo act_info=ActivationLayerInfo(), const Size2D &dilation=Size2D(1U, 1U))
Initialize the function's source, destination, conv and border_size.
void run () override
Run the kernels contained in the function.
void prepare () override
Prepare the function for executing.
Public Member Functions inherited from IFunction
virtual ~IFunction ()=default
Destructor.
Static Public Member Functions
static Status validate (const ITensorInfo *input, const ITensorInfo *weights, const ITensorInfo *biases, const ITensorInfo *output, const PadStrideInfo &conv_info, unsigned int depth_multiplier=1, ActivationLayerInfo act_info=ActivationLayerInfo(), GPUTarget gpu_target=GPUTarget::MIDGARD, const Size2D &dilation=Size2D(1U, 1U))
Static function to check if given info will lead to a valid configuration of CLDepthwiseConvolutionLayer3x3.
Detailed Description
Basic function to execute a depthwise convolution for kernel size 3x3xC (when data layout NCHW) or Cx3x3 (when data layout NHWC).
This function calls the following OpenCL kernels:
CLDepthwiseConvolutionLayer3x3NCHWKernel (if data_layout == NCHW)
CLDepthwiseConvolutionLayer3x3NHWCKernel (if data_layout == NHWC)
CLDepthwiseConvolutionLayerReshapeWeightsKernel (if data_layout == NHWC)
CLFillBorderKernel (if pad_x or pad_y > 0)
Definition at line 56 of file CLDepthwiseConvolutionLayer.h.
Constructor & Destructor Documentation
CLDepthwiseConvolutionLayer3x3() [1/3]
CLDepthwiseConvolutionLayer3x3 (std::shared_ptr< IMemoryManager > memory_manager = nullptr)
Default constructor.
Definition at line 41 of file CLDepthwiseConvolutionLayer.cpp.
     : _memory_group(std::move(memory_manager)), _kernel(nullptr), _border_handler(), _permute_input_to_nchw(), _permute_weights_to_nchw(), _permute_output_to_nhwc(), _reshape_weights(), _permuted_input(),
       _permuted_weights(), _permuted_output(), _original_weights(nullptr), _needs_permute(false), _needs_weights_reshape(false), _is_prepared(false)
 {
 }
CLDepthwiseConvolutionLayer3x3() [2/3]
CLDepthwiseConvolutionLayer3x3 (const CLDepthwiseConvolutionLayer3x3 &) delete
Prevent instances of this class from being copied (As this class contains pointers)
CLDepthwiseConvolutionLayer3x3() [3/3]
CLDepthwiseConvolutionLayer3x3 (CLDepthwiseConvolutionLayer3x3 &&) default
Default move constructor.
Member Function Documentation
configure()
void configure (ICLTensor * input, const ICLTensor * weights, const ICLTensor * biases, ICLTensor * output, const PadStrideInfo & conv_info, unsigned int depth_multiplier = 1, ActivationLayerInfo act_info = ActivationLayerInfo(), const Size2D & dilation = Size2D(1U, 1U))
Initialize the function's source, destination, conv and border_size.
Parameters
[in,out] input Source tensor. Data type supported: QASYMM8/F16/F32. (Written to only for border filling).
[in] weights Weights tensor. A 3D tensor with shape [3, 3, IFM]. Data type supported: Same as input.
[in] biases Biases tensor. A 1D tensor with shape [IFM]. Must be nullptr if not needed. Data type supported: Same as input.
[out] output Destination tensor. Data type supported: same as input.
[in] conv_info Padding and stride information to use for the convolution.
[in] depth_multiplier (Optional) Multiplier to apply to the input's depth in order to retrieve the output's depth. Defaults to 1.
[in] act_info (Optional) Activation layer information in case of a fused activation. Only RELU, BOUNDED_RELU and LU_BOUNDED_RELU for 3x3 QASYMM8 supported.
[in] dilation (Optional) Dilation, in elements, across x and y. Defaults to (1, 1).
Definition at line 47 of file CLDepthwiseConvolutionLayer.cpp.
 {
     ARM_COMPUTE_ERROR_ON_DATA_TYPE_CHANNEL_NOT_IN(input, 1, DataType::QASYMM8, DataType::F16, DataType::F32);
     ARM_COMPUTE_ERROR_ON_MISMATCHING_DATA_TYPES(input, weights);
     // idx_w and idx_h only used for validation
     const size_t idx_w = get_data_layout_dimension_index(input->info()->data_layout(), DataLayoutDimension::WIDTH);
     const size_t idx_h = get_data_layout_dimension_index(input->info()->data_layout(), DataLayoutDimension::HEIGHT);
     ARM_COMPUTE_UNUSED(idx_w);
     ARM_COMPUTE_UNUSED(idx_h);
     ARM_COMPUTE_ERROR_ON(weights->info()->dimension(idx_w) + (weights->info()->dimension(idx_w) - 1) * (dilation.x() - 1) > input->info()->dimension(idx_w) + conv_info.pad_left() + conv_info.pad_right());
     ARM_COMPUTE_ERROR_ON(weights->info()->dimension(idx_h) + (weights->info()->dimension(idx_h) - 1) * (dilation.y() - 1) > input->info()->dimension(idx_h) + conv_info.pad_top() + conv_info.pad_bottom());
     const bool is_nhwc = input->info()->data_layout() == DataLayout::NHWC;
     _needs_permute         = is_nhwc && (depth_multiplier > 1);
     _needs_weights_reshape = is_nhwc && (depth_multiplier == 1)
                              && is_data_type_quantized_asymmetric(input->info()->data_type());
     _is_prepared      = false;
     _original_weights = weights;
     ICLTensor       *input_to_use   = input;
     const ICLTensor *weights_to_use = weights;
     ICLTensor       *output_to_use  = output;
     const bool is_stride_1            = ((conv_info.stride().first == conv_info.stride().second) && (conv_info.stride().first == 1));
     const bool is_dot8_supported      = dot8_supported(CLKernelLibrary::get().get_device());
     const bool is_stride_1_dilation_1 = (is_stride_1 && dilation.x() == 1 && dilation.y() == 1);
     DepthwiseConvolutionReshapeInfo info;
     info.c0        = 4;
     info.transpose = is_stride_1_dilation_1 && is_dot8_supported;
     if(_needs_permute)
     {
         _memory_group.manage(&_permuted_input);
         _memory_group.manage(&_permuted_output);
         // Configure the function to transform the input tensor from NHWC -> NCHW
         _permute_input_to_nchw.configure(input, &_permuted_input, PermutationVector(1U, 2U, 0U));
         _permuted_input.info()->set_data_layout(DataLayout::NCHW);
         // Configure the function to transform the weights tensor from HWI -> IHW
         _permute_weights_to_nchw.configure(weights, &_permuted_weights, PermutationVector(1U, 2U, 0U));
         _permuted_weights.info()->set_data_layout(DataLayout::NCHW);
         input_to_use   = &_permuted_input;
         weights_to_use = &_permuted_weights;
         output_to_use  = &_permuted_output;
         _kernel = arm_compute::support::cpp14::make_unique<CLDepthwiseConvolutionLayer3x3NCHWKernel>();
     }
     else if(is_nhwc)
     {
         if(_needs_weights_reshape)
         {
             _reshape_weights.configure(weights, &_permuted_weights, info);
             weights_to_use = &_permuted_weights;
         }
         _kernel = arm_compute::support::cpp14::make_unique<CLDepthwiseConvolutionLayer3x3NHWCKernel>();
     }
     else
     {
         _kernel = arm_compute::support::cpp14::make_unique<CLDepthwiseConvolutionLayer3x3NCHWKernel>();
     }
     // Configure kernel
     _kernel->set_target(CLScheduler::get().target());
     _kernel->configure(input_to_use, weights_to_use, biases, output_to_use, conv_info, depth_multiplier, act_info, dilation);
     // Permute output if needed
     if(_needs_permute)
     {
         // Configure the function to transform the convoluted output to ACL's native ordering format NCHW
         _permuted_output.info()->set_data_layout(DataLayout::NCHW);
         _permute_output_to_nhwc.configure(&_permuted_output, output, PermutationVector(2U, 0U, 1U));
         // Allocate tensors
         _permuted_input.allocator()->allocate();
         _permuted_output.allocator()->allocate();
     }
     // Configure border handler
     PixelValue &&zero_value(0.f);
     if(is_data_type_quantized_asymmetric(input->info()->data_type()))
     {
         zero_value = PixelValue(static_cast<uint8_t>(input->info()->quantization_info().offset));
     }
     _border_handler.configure(input_to_use, _kernel->border_size(), BorderMode::CONSTANT, zero_value);
 }
References arm_compute::test::validation::act_info, CLTensorAllocator::allocate(), CLTensor::allocator(), ARM_COMPUTE_ERROR_ON, ARM_COMPUTE_ERROR_ON_DATA_TYPE_CHANNEL_NOT_IN, ARM_COMPUTE_ERROR_ON_MISMATCHING_DATA_TYPES, ARM_COMPUTE_UNUSED, CLPermute::configure(), CLDepthwiseConvolutionLayerReshapeWeightsKernel::configure(), CLFillBorderKernel::configure(), arm_compute::CONSTANT, arm_compute::test::validation::conv_info, ITensorInfo::data_layout(), ITensorInfo::data_type(), arm_compute::test::validation::dilation, ITensorInfo::dimension(), TensorInfo::dimension(), arm_compute::dot8_supported(), arm_compute::F16, arm_compute::F32, CLScheduler::get(), CLKernelLibrary::get(), arm_compute::get_data_layout_dimension_index(), arm_compute::HEIGHT, ITensor::info(), CLTensor::info(), arm_compute::test::validation::info, arm_compute::is_data_type_quantized_asymmetric(), MemoryGroupBase< TensorType >::manage(), arm_compute::NCHW, arm_compute::NHWC, QuantizationInfo::offset, arm_compute::QASYMM8, ITensorInfo::quantization_info(), TensorInfo::set_data_layout(), arm_compute::U, arm_compute::test::validation::weights, and arm_compute::WIDTH.
operator=() [1/2]
CLDepthwiseConvolutionLayer3x3& operator= (const CLDepthwiseConvolutionLayer3x3 &) delete
Prevent instances of this class from being copied (As this class contains pointers)
operator=() [2/2]
CLDepthwiseConvolutionLayer3x3& operator= (CLDepthwiseConvolutionLayer3x3 &&) default
Default move assignment operator.
prepare()
void prepare () override virtual
Prepare the function for executing.
Any one off pre-processing step required by the function is handled here
Note
Prepare stage might not need all the function's buffers' backing memory to be available in order to execute
Reimplemented from IFunction.
Definition at line 208 of file CLDepthwiseConvolutionLayer.cpp.
 {
     if(!_is_prepared)
     {
         if(_needs_permute)
         {
             ARM_COMPUTE_ERROR_ON(!_original_weights->is_used());
             _permuted_weights.allocator()->allocate();
             _permute_weights_to_nchw.run();
             _original_weights->mark_as_unused();
         }
         if(_needs_weights_reshape)
         {
             ARM_COMPUTE_ERROR_ON(_needs_permute);
             ARM_COMPUTE_ERROR_ON(!_original_weights->is_used());
             _permuted_weights.allocator()->allocate();
             CLScheduler::get().enqueue(_reshape_weights);
             _original_weights->mark_as_unused();
         }
         _is_prepared = true;
     }
 }
References CLTensorAllocator::allocate(), CLTensor::allocator(), ARM_COMPUTE_ERROR_ON, CLScheduler::enqueue(), CLScheduler::get(), ITensor::is_used(), ITensor::mark_as_unused(), and ICLSimpleFunction::run().
Referenced by CLDepthwiseConvolutionLayer3x3::run().
run()
void run () override virtual
Run the kernels contained in the function.
For NEON kernels:
Multi-threading is used for the kernels which are parallelisable.
By default std::thread::hardware_concurrency() threads are used.
Note
CPPScheduler::set_num_threads() can be used to manually set the number of threads
For OpenCL kernels:
All the kernels are enqueued on the queue associated with CLScheduler.
The queue is then flushed.
Note
The function will not block until the kernels are executed. It is the user's responsibility to wait.
Will call prepare() on first run if hasn't been done
Implements IFunction.
Definition at line 189 of file CLDepthwiseConvolutionLayer.cpp.
 {
     prepare();
     MemoryGroupResourceScope scope_mg(_memory_group);
     if(_needs_permute)
     {
         _permute_input_to_nchw.run();
     }
     CLScheduler::get().enqueue(_border_handler);
     CLScheduler::get().enqueue(*_kernel);
     if(_needs_permute)
     {
         _permute_output_to_nhwc.run();
     }
 }
References CLScheduler::enqueue(), CLScheduler::get(), CLDepthwiseConvolutionLayer3x3::prepare(), and ICLSimpleFunction::run().
validate()
Status validate (const ITensorInfo * input, const ITensorInfo * weights, const ITensorInfo * biases, const ITensorInfo * output, const PadStrideInfo & conv_info, unsigned int depth_multiplier = 1, ActivationLayerInfo act_info = ActivationLayerInfo(), GPUTarget gpu_target = GPUTarget::MIDGARD, const Size2D & dilation = Size2D(1U, 1U)) static
Static function to check if given info will lead to a valid configuration of CLDepthwiseConvolutionLayer3x3.
Parameters
[in] input Source tensor info. Data type supported: QASYMM8 for all layouts, F16/F32 for NCHW.
[in] weights Weights tensor info. A 3D tensor with shape [3, 3, IFM]. Data type supported: Same as input.
[in] biases Biases tensor info. A 1D tensor with shape [IFM]. Must be nullptr if not needed. Data type supported: Same as input, S32 when input is QASYMM8.
[in] output Destination tensor. Data type supported: same as input.
[in] conv_info Padding and stride information to use for the convolution.
[in] depth_multiplier (Optional) Multiplier to apply to the input's depth in order to retrieve the output's depth. Defaults to 1.
[in] act_info (Optional) Activation layer information in case of a fused activation. Only RELU, BOUNDED_RELU and LU_BOUNDED_RELU for 3x3 QASYMM8 supported.
[in] gpu_target (Optional) GPU target to validate the kernel for. Defaults to midgard.
[in] dilation (Optional) Dilation, in elements, across x and y. Defaults to (1, 1).
Returns
a status
Definition at line 138 of file CLDepthwiseConvolutionLayer.cpp.
 {
     ARM_COMPUTE_RETURN_ERROR_ON_NULLPTR(input, weights, output);
     ARM_COMPUTE_RETURN_ERROR_ON(input->data_layout() == DataLayout::UNKNOWN);
     const bool                      is_nhwc                = input->data_layout() == DataLayout::NHWC;
     const bool                      needs_permute          = is_nhwc && (depth_multiplier > 1);
     const bool                      needs_weights_reshape  = is_nhwc && (depth_multiplier == 1);
     const bool                      is_stride_1            = ((conv_info.stride().first == conv_info.stride().second) && (conv_info.stride().first == 1));
     const bool                      is_stride_1_dilation_1 = (is_stride_1 && dilation.x() == 1 && dilation.y() == 1);
     const bool                      is_dot8_supported      = dot8_supported(CLKernelLibrary::get().get_device());
     DepthwiseConvolutionReshapeInfo info;
     info.c0        = 4;
     info.transpose = is_stride_1_dilation_1 && is_dot8_supported;
     if(needs_permute)
     {
         TensorShape permuted_input_shape   = input->tensor_shape();
         TensorShape permuted_weights_shape = weights->tensor_shape();
         TensorShape permuted_output_shape  = shape_calculator::compute_depthwise_convolution_shape(*input, *weights, conv_info, depth_multiplier, dilation);
         permute(permuted_input_shape, PermutationVector(1U, 2U, 0U));
         permute(permuted_weights_shape, PermutationVector(1U, 2U, 0U));
         permute(permuted_output_shape, PermutationVector(1U, 2U, 0U));
         const TensorInfo permuted_input   = input->clone()->set_is_resizable(true).reset_padding().set_tensor_shape(permuted_input_shape).set_data_layout(DataLayout::NCHW);
         const TensorInfo permuted_weights = weights->clone()->set_is_resizable(true).reset_padding().set_tensor_shape(permuted_weights_shape).set_data_layout(DataLayout::NCHW);
         const TensorInfo permuted_output  = output->clone()->set_is_resizable(true).reset_padding().set_tensor_shape(permuted_output_shape).set_data_layout(DataLayout::NCHW);
         ARM_COMPUTE_RETURN_ON_ERROR(CLDepthwiseConvolutionLayer3x3NCHWKernel::validate(&permuted_input, &permuted_weights, biases, &permuted_output, conv_info, depth_multiplier, act_info, gpu_target,
                                                                                        dilation));
     }
     else if(is_nhwc)
     {
         if(needs_weights_reshape)
         {
             auto reshaped_weights_shape = arm_compute::misc::shape_calculator::compute_reshaped_depthwise_weights_shape(*weights, info);
             ARM_COMPUTE_RETURN_ON_ERROR(CLDepthwiseConvolutionLayer3x3NHWCKernel::validate(input, &weights->clone()->set_tensor_shape(reshaped_weights_shape), biases, output, conv_info, depth_multiplier,
                                                                                            act_info, dilation));
         }
         ARM_COMPUTE_RETURN_ON_ERROR(CLDepthwiseConvolutionLayer3x3NHWCKernel::validate(input, weights, biases, output, conv_info, depth_multiplier, act_info, dilation));
     }
     else
     {
         ARM_COMPUTE_RETURN_ON_ERROR(CLDepthwiseConvolutionLayer3x3NCHWKernel::validate(input, weights, biases, output, conv_info, depth_multiplier, act_info, gpu_target, dilation));
     }
     return Status{};
 }
References arm_compute::test::validation::act_info, ARM_COMPUTE_RETURN_ERROR_ON, ARM_COMPUTE_RETURN_ERROR_ON_NULLPTR, ARM_COMPUTE_RETURN_ON_ERROR, ICloneable< T >::clone(), arm_compute::misc::shape_calculator::compute_depthwise_convolution_shape(), arm_compute::misc::shape_calculator::compute_reshaped_depthwise_weights_shape(), arm_compute::test::validation::conv_info, ITensorInfo::data_layout(), arm_compute::test::validation::dilation, arm_compute::dot8_supported(), CLKernelLibrary::get(), arm_compute::test::validation::info, arm_compute::NCHW, arm_compute::NHWC, arm_compute::permute(), ITensorInfo::tensor_shape(), arm_compute::U, arm_compute::UNKNOWN, CLDepthwiseConvolutionLayer3x3NCHWKernel::validate(), CLDepthwiseConvolutionLayer3x3NHWCKernel::validate(), and arm_compute::test::validation::weights.
Referenced by CLDepthwiseConvolutionLayer::validate().
The documentation for this class was generated from the following files:
arm_compute/runtime/CL/functions/CLDepthwiseConvolutionLayer.h
src/runtime/CL/functions/CLDepthwiseConvolutionLayer.cpp