Compute Library: CLPyramid Class Reference
CLPyramid Class Reference
Basic implementation of the OpenCL pyramid interface.
#include <CLPyramid.h>
Public Member Functions
CLPyramid ()
Default constructor.
void init (const PyramidInfo &info)
Initialize pyramid data-object using the given Pyramid's metadata.
void init_auto_padding (const PyramidInfo &info)
Initialize pyramid data-object using the given Pyramid's metadata.
void allocate ()
Allocate the planes in the pyramid.
const PyramidInfo * info () const override
Interface to be implemented by the child class to return the Pyramid's metadata.
CLTensor * get_pyramid_level (size_t index) const override
Retrieves a level of the pyramid as a ITensor pointer.
Public Member Functions inherited from IPyramid
virtual ~IPyramid ()=default
Default virtual destructor.
Detailed Description
Basic implementation of the OpenCL pyramid interface.
Definition at line 40 of file CLPyramid.h.
Constructor & Destructor Documentation
CLPyramid()
CLPyramid ()
Default constructor.
Definition at line 37 of file CLPyramid.cpp.
     : _info(), _pyramid()
 {
 }
Member Function Documentation
allocate()
void allocate ()
Allocate the planes in the pyramid.
Note
The pyramid must not already be allocated when calling this function.
Definition at line 110 of file CLPyramid.cpp.
 {
     for(size_t i = 0; i < _info.num_levels(); ++i)
     {
         _pyramid[i].allocator()->allocate();
     }
 }
References PyramidInfo::num_levels().
Referenced by CLLaplacianPyramid::configure(), and CLLaplacianReconstruct::configure().
get_pyramid_level()
CLTensor * get_pyramid_level (size_t index) const override virtual
Retrieves a level of the pyramid as a ITensor pointer.
Parameters
[in] index The index of the level, such that index is less than levels.
Returns
An ITensor pointer
Implements IPyramid.
Definition at line 123 of file CLPyramid.cpp.
 {
     ARM_COMPUTE_ERROR_ON(index >= _info.num_levels());
     return &_pyramid[index];
 }
References ARM_COMPUTE_ERROR_ON, and PyramidInfo::num_levels().
Referenced by CLLaplacianPyramid::configure(), CLLaplacianReconstruct::configure(), CLGaussianPyramidHalf::configure(), CLOpticalFlow::configure(), and CLGaussianPyramidOrb::configure().
info()
const PyramidInfo * info () const override virtual
Interface to be implemented by the child class to return the Pyramid's metadata.
Returns
A pointer to the Pyramid's metadata.
Implements IPyramid.
Definition at line 118 of file CLPyramid.cpp.
 {
     return &_info;
 }
Referenced by CLLaplacianPyramid::configure(), CLLaplacianReconstruct::configure(), CLGaussianPyramidHalf::configure(), CLOpticalFlow::configure(), CLGaussianPyramidOrb::configure(), CLPyramid::init(), CLPyramid::init_auto_padding(), and CLLaplacianReconstruct::run().
init()
void init (const PyramidInfo & info)
Initialize pyramid data-object using the given Pyramid's metadata.
Parameters
[in] info Pyramid's metadata
Definition at line 42 of file CLPyramid.cpp.
 {
     internal_init(info, false);
 }
References CLPyramid::info().
Referenced by CLLaplacianPyramid::configure(), CLLaplacianReconstruct::configure(), and arm_compute::test::validation::DATA_TEST_CASE().
init_auto_padding()
void init_auto_padding (const PyramidInfo & info)
Initialize pyramid data-object using the given Pyramid's metadata.
Note
Uses conservative padding strategy which fits all kernels.
Parameters
[in] info Pyramid's metadata
Definition at line 47 of file CLPyramid.cpp.
 {
     internal_init(info, true);
 }
References CLPyramid::info().
The documentation for this class was generated from the following files:
arm_compute/runtime/CL/CLPyramid.h
src/runtime/CL/CLPyramid.cpp