Compute Library: GCDirectConvolutionLayer Class Reference
GCDirectConvolutionLayer Class Reference
Basic function to execute direct convolution function.
#include <GCDirectConvolutionLayer.h>
Public Member Functions
GCDirectConvolutionLayer ()
Default constructor.
void configure (IGCTensor *input, const IGCTensor *weights, const IGCTensor *biases, IGCTensor *output, const PadStrideInfo &conv_info, const ActivationLayerInfo &act_info=ActivationLayerInfo())
Set the input and output tensors.
void run () override final
Run the kernels contained in the function.
Public Member Functions inherited from IFunction
virtual ~IFunction ()=default
Destructor.
virtual void prepare ()
Prepare the function for executing.
Detailed Description
Basic function to execute direct convolution function.
This function calls the following kernels:
GCDirectConvolutionLayerKernel
GCFillBorderKernel
GCTensorShiftKernel
Note
Supported kernel size: 1x1, 3x3, and 5x5
This OpenGL ES implementation works with stride_x = 1 and 2
Definition at line 50 of file GCDirectConvolutionLayer.h.
Constructor & Destructor Documentation
GCDirectConvolutionLayer()
GCDirectConvolutionLayer ()
Default constructor.
Definition at line 37 of file GCDirectConvolutionLayer.cpp.
     : _kernel(nullptr), _border_handler(), _shift_handler()
 {
 }
Member Function Documentation
configure()
void configure (IGCTensor * input, const IGCTensor * weights, const IGCTensor * biases, IGCTensor * output, const PadStrideInfo & conv_info, const ActivationLayerInfo & act_info = ActivationLayerInfo())
Set the input and output tensors.
Parameters
[in,out] input Source tensor. 3 lower dimensions represent a single input [width, height, IFM], while every optional dimension from 4 and above represent a batch of inputs. Data types supported: F16/F32. input will be written to only if it is currently left aligned.
[in] weights Weights tensor. Weights are 4D tensor with dimensions [kernel_x, kernel_y, IFM, OFM]. Data type supported:Same as input.
[in] biases Biases tensor. Shared biases supported. Biases are 1D tensor with dimensions [OFM]. Data type supported:Same as input.
[out] output Destination tensor. 3 lower dimensions represent a single output [width, height, OFM], while the rest represent batch of outputs. Data types supported: Same as input.
[in] conv_info Contains padding and stride information described in PadStrideInfo.
[in] act_info (Optional) Activation layer information in case of a fused activation.
Definition at line 42 of file GCDirectConvolutionLayer.cpp.
 {
     int kernel_size = weights->info()->dimension(0);
     if(kernel_size == 1)
     {
         auto k = arm_compute::support::cpp14::make_unique<GCDirectConvolutionLayer1x1Kernel>();
         k->configure(input, weights, biases, output, conv_info, act_info);
         _kernel = std::move(k);
     }
     else if(kernel_size == 3)
     {
         auto k = arm_compute::support::cpp14::make_unique<GCDirectConvolutionLayer3x3Kernel>();
         k->configure(input, weights, biases, output, conv_info, act_info);
         _kernel = std::move(k);
     }
     else if(kernel_size == 5)
     {
         auto k = arm_compute::support::cpp14::make_unique<GCDirectConvolutionLayer5x5Kernel>();
         k->configure(input, weights, biases, output, conv_info, act_info);
         _kernel = std::move(k);
     }
     else
     {
         ARM_COMPUTE_ERROR("kernel size unsupported!");
         return;
     }
     _border_handler.configure(input, _kernel->border_size(), BorderMode::CONSTANT, PixelValue());
     _shift_handler.configure(input);
 }
References arm_compute::test::validation::act_info, ARM_COMPUTE_ERROR, GCFillBorderKernel::configure(), GCTensorShiftKernel::configure(), arm_compute::CONSTANT, arm_compute::test::validation::conv_info, TensorInfo::dimension(), CLTensor::info(), and arm_compute::test::validation::weights.
run()
void run () final override virtual
Run the kernels contained in the function.
For NEON kernels:
Multi-threading is used for the kernels which are parallelisable.
By default std::thread::hardware_concurrency() threads are used.
Note
CPPScheduler::set_num_threads() can be used to manually set the number of threads
For OpenCL kernels:
All the kernels are enqueued on the queue associated with CLScheduler.
The queue is then flushed.
Note
The function will not block until the kernels are executed. It is the user's responsibility to wait.
Will call prepare() on first run if hasn't been done
Implements IFunction.
Definition at line 76 of file GCDirectConvolutionLayer.cpp.
 {
     GCScheduler::get().dispatch(_shift_handler, false);
     GCScheduler::get().memory_barrier();
     GCScheduler::get().dispatch(_border_handler, false);
     GCScheduler::get().memory_barrier();
     GCScheduler::get().dispatch(*_kernel);
     GCScheduler::get().memory_barrier();
     GCScheduler::get().dispatch(_shift_handler);
 }
References GCScheduler::dispatch(), GCScheduler::get(), and GCScheduler::memory_barrier().
The documentation for this class was generated from the following files:
arm_compute/runtime/GLES_COMPUTE/functions/GCDirectConvolutionLayer.h
src/runtime/GLES_COMPUTE/functions/GCDirectConvolutionLayer.cpp