Compute Library: NEConcatenateLayer Class Reference
NEConcatenateLayer Class Reference
Basic function to execute concatenate tensors along a given axis.
#include <NEConcatenateLayer.h>
Public Member Functions
NEConcatenateLayer ()
Default constructor.
void configure (const std::vector< ITensor * > &inputs_vector, ITensor *output, size_t axis)
Initialise the kernel's inputs vector and output.
void run () override
Run the kernels contained in the function.
Public Member Functions inherited from IFunction
virtual ~IFunction ()=default
Destructor.
virtual void prepare ()
Prepare the function for executing.
Static Public Member Functions
static Status validate (const std::vector< ITensorInfo * > &inputs_vector, const ITensorInfo *output, size_t axis)
Static function to check if given info will lead to a valid configuration of NEConcatenateLayer.
Detailed Description
Basic function to execute concatenate tensors along a given axis.
This function calls the following kernels:
NEWidthConcatenateLayer (if underlying concatenation axis is 0).
NEHeightConcatenateLayerKernel (if underlying concatenation axis is 1).
NEDepthConcatenateLayer (if underlying concatenation axis is 2).
Definition at line 48 of file NEConcatenateLayer.h.
Constructor & Destructor Documentation
NEConcatenateLayer()
NEConcatenateLayer ()
Default constructor.
Definition at line 40 of file NEConcatenateLayer.cpp.
     : _concat_kernels(),
       _num_inputs(0),
       _axis(Window::DimX)
 {
 }
Member Function Documentation
configure()
void configure (const std::vector< ITensor * > & inputs_vector, ITensor * output, size_t axis)
Initialise the kernel's inputs vector and output.
Note
Input and output tensor dimensions preconditions defer depending on the concatenation axis.
Preconditions can be found respectively at NEWidthConcatenateLayer, NEHeightConcatenateLayerKernel and NEDepthConcatenateLayer.
Parameters
[in,out] inputs_vector The vectors containing all the tensors to concatenate. Data types supported: QASYMM8/F16/F32.
[out] output Output tensor. Data types supported: Same as input.
[in] axis Concatenation axis. Supported underlying concatenation axis are 0, 1 and 2.
Definition at line 47 of file NEConcatenateLayer.cpp.
 {
     ARM_COMPUTE_ERROR_ON(output == nullptr);
     _axis       = axis;
     _num_inputs = inputs_vector.size();
     std::vector<ITensorInfo *> inputs_vector_info;
     inputs_vector_info.reserve(_num_inputs);
     for(unsigned int i = 0; i < _num_inputs; ++i)
     {
         ARM_COMPUTE_ERROR_ON_NULLPTR(inputs_vector.at(i));
         inputs_vector_info.emplace_back(inputs_vector.at(i)->info());
     }
     TensorShape output_shape = arm_compute::misc::shape_calculator::calculate_concatenate_shape(inputs_vector, _axis);
     // Output auto inizialitation if not yet initialized
     auto_init_if_empty(*output->info(), output_shape, 1, inputs_vector[0]->info()->data_type());
     ARM_COMPUTE_ERROR_THROW_ON(NEConcatenateLayer::validate(inputs_vector_info, output->info(), axis));
     unsigned int offset = 0;
     for(unsigned int i = 0; i < _num_inputs; ++i)
     {
         switch(_axis)
         {
             case Window::DimX:
             {
                 auto kernel = support::cpp14::make_unique<NEWidthConcatenateLayerKernel>();
                 kernel->configure(inputs_vector.at(i), offset, output);
                 _concat_kernels.emplace_back(std::move(kernel));
                 break;
             }
             case Window::DimY:
             {
                 auto kernel = support::cpp14::make_unique<NEHeightConcatenateLayerKernel>();
                 kernel->configure(inputs_vector.at(i), offset, output);
                 _concat_kernels.emplace_back(std::move(kernel));
                 break;
             }
             case Window::DimZ:
             {
                 auto kernel = support::cpp14::make_unique<NEDepthConcatenateLayerKernel>();
                 kernel->configure(inputs_vector.at(i), offset, output);
                 _concat_kernels.emplace_back(std::move(kernel));
                 break;
             }
             default:
                 ARM_COMPUTE_ERROR("Axis not supported");
         }
         offset += inputs_vector.at(i)->info()->dimension(_axis);
     }
 }
References ARM_COMPUTE_ERROR, ARM_COMPUTE_ERROR_ON, ARM_COMPUTE_ERROR_ON_NULLPTR, ARM_COMPUTE_ERROR_THROW_ON, arm_compute::auto_init_if_empty(), arm_compute::test::validation::axis, arm_compute::misc::shape_calculator::calculate_concatenate_shape(), Window::DimX, Window::DimY, Window::DimZ, ITensor::info(), offset(), arm_compute::test::validation::output_shape, and NEConcatenateLayer::validate().
run()
void run () override virtual
Run the kernels contained in the function.
For NEON kernels:
Multi-threading is used for the kernels which are parallelisable.
By default std::thread::hardware_concurrency() threads are used.
Note
CPPScheduler::set_num_threads() can be used to manually set the number of threads
For OpenCL kernels:
All the kernels are enqueued on the queue associated with CLScheduler.
The queue is then flushed.
Note
The function will not block until the kernels are executed. It is the user's responsibility to wait.
Will call prepare() on first run if hasn't been done
Implements IFunction.
Definition at line 141 of file NEConcatenateLayer.cpp.
 {
     for(auto &kernel : _concat_kernels)
     {
         NEScheduler::get().schedule(kernel.get(), _axis);
     }
 }
References Scheduler::get(), and IScheduler::schedule().
validate()
Status validate (const std::vector< ITensorInfo * > & inputs_vector, const ITensorInfo * output, size_t axis) static
Static function to check if given info will lead to a valid configuration of NEConcatenateLayer.
Note
Input and output tensor dimensions preconditions defer depending on the concatenation axis.
Preconditions can be found respectively at NEWidthConcatenateLayer, NEHeightConcatenateLayerKernel and NEDepthConcatenateLayer.
Parameters
[in] inputs_vector The vectors containing all the tensors info to concatenate. Data types supported: QASYMM8/F16/F32.
[in] output Output tensor info. Data types supported: Same as input.
[in] axis Concatenation axis. Supported underlying concatenation axis are 0, 1 and 2.
Returns
a status
Definition at line 100 of file NEConcatenateLayer.cpp.
 {
     ARM_COMPUTE_RETURN_ERROR_ON_NULLPTR(output);
     ARM_COMPUTE_RETURN_ERROR_ON(inputs_vector.size() < 2);
     unsigned int offset = 0;
     for(const auto &input : inputs_vector)
     {
         ARM_COMPUTE_RETURN_ERROR_ON_NULLPTR(input);
         switch(axis)
         {
             case Window::DimX:
             {
                 ARM_COMPUTE_RETURN_ON_ERROR(NEWidthConcatenateLayerKernel::validate(input, offset, output));
                 break;
             }
             case Window::DimY:
             {
                 ARM_COMPUTE_RETURN_ON_ERROR(NEHeightConcatenateLayerKernel::validate(input, offset, output));
                 break;
             }
             case Window::DimZ:
             {
                 ARM_COMPUTE_RETURN_ON_ERROR(NEDepthConcatenateLayerKernel::validate(input, offset, output));
                 break;
             }
             default:
                 ARM_COMPUTE_ERROR("Axis not supported");
         }
         offset += input->dimension(axis);
     }
     if(output->total_size() != 0)
     {
         TensorShape output_shape = arm_compute::misc::shape_calculator::calculate_concatenate_shape(inputs_vector, axis);
         ARM_COMPUTE_RETURN_ERROR_ON(output_shape.total_size() != output->tensor_shape().total_size());
     }
     return Status{};
 }
References ARM_COMPUTE_ERROR, ARM_COMPUTE_RETURN_ERROR_ON, ARM_COMPUTE_RETURN_ERROR_ON_NULLPTR, ARM_COMPUTE_RETURN_ON_ERROR, arm_compute::test::validation::axis, arm_compute::misc::shape_calculator::calculate_concatenate_shape(), Window::DimX, Window::DimY, Window::DimZ, offset(), arm_compute::test::validation::output_shape, ITensorInfo::tensor_shape(), TensorShape::total_size(), ITensorInfo::total_size(), NEHeightConcatenateLayerKernel::validate(), NEWidthConcatenateLayerKernel::validate(), and NEDepthConcatenateLayerKernel::validate().
Referenced by NEConcatenateLayer::configure().
The documentation for this class was generated from the following files:
arm_compute/runtime/NEON/functions/NEConcatenateLayer.h
src/runtime/NEON/functions/NEConcatenateLayer.cpp