Compute Library: TestSuiteRegistrar Class Reference
TestSuiteRegistrar Class Reference final
Helper class to statically begin and end a test suite.
#include <Registrars.h>
Public Member Functions
TestSuiteRegistrar ()
Remove the last added test suite from the framework.
TestSuiteRegistrar (std::string name)
Add a new test suite with the given name to the framework.
Detailed Description
Helper class to statically begin and end a test suite.
Definition at line 66 of file Registrars.h.
Constructor & Destructor Documentation
TestSuiteRegistrar() [1/2]
TestSuiteRegistrar () inline
Remove the last added test suite from the framework.
Definition at line 100 of file Registrars.h.
 {
     Framework::get().pop_suite();
 }
References Framework::get(), and Framework::pop_suite().
TestSuiteRegistrar() [2/2]
TestSuiteRegistrar (std::string name) inline
Add a new test suite with the given name to the framework.
Parameters
[in] name Name of the test suite.
Definition at line 105 of file Registrars.h.
 {
     Framework::get().push_suite(std::move(name));
 }
References Framework::get(), and Framework::push_suite().
The documentation for this class was generated from the following file:
tests/framework/Registrars.h