Compute Library: CLSobel5x5VertKernel Class Reference
CLSobel5x5VertKernel Class Reference
Interface for the kernel to run the vertical pass of 5x5 Sobel filter on a tensor.
#include <CLSobel5x5Kernel.h>
Public Member Functions
CLSobel5x5VertKernel ()
Default constructor: initialize all the pointers to nullptr and parameters to zero.
CLSobel5x5VertKernel (const CLSobel5x5VertKernel &)=delete
Prevent instances of this class from being copied (As this class contains pointers)
CLSobel5x5VertKernel & operator= (const CLSobel5x5VertKernel &)=delete
Prevent instances of this class from being copied (As this class contains pointers)
CLSobel5x5VertKernel (CLSobel5x5VertKernel &&)=default
Allow instances of this class to be moved.
CLSobel5x5VertKernel & operator= (CLSobel5x5VertKernel &&)=default
Allow instances of this class to be moved.
~CLSobel5x5VertKernel ()=default
Default destructor.
void configure (const ICLTensor *input_x, const ICLTensor *input_y, ICLTensor *output_x, ICLTensor *output_y, bool border_undefined)
Initialise the kernel's source, destination and border.
void run (const Window &window, cl::CommandQueue &queue) override
Enqueue the OpenCL kernel to process the given window on the passed OpenCL command queue.
BorderSize border_size () const override
The size of the border for that kernel.
Public Member Functions inherited from ICLKernel
ICLKernel ()
Constructor.
cl::Kernel & kernel ()
Returns a reference to the OpenCL kernel of this object.
template<typename T >
void add_1D_array_argument (unsigned int &idx, const ICLArray< T > *array, const Strides &strides, unsigned int num_dimensions, const Window &window)
Add the passed 1D array's parameters to the object's kernel's arguments starting from the index idx.
void add_1D_tensor_argument (unsigned int &idx, const ICLTensor *tensor, const Window &window)
Add the passed 1D tensor's parameters to the object's kernel's arguments starting from the index idx.
void add_2D_tensor_argument (unsigned int &idx, const ICLTensor *tensor, const Window &window)
Add the passed 2D tensor's parameters to the object's kernel's arguments starting from the index idx.
void add_3D_tensor_argument (unsigned int &idx, const ICLTensor *tensor, const Window &window)
Add the passed 3D tensor's parameters to the object's kernel's arguments starting from the index idx.
void add_4D_tensor_argument (unsigned int &idx, const ICLTensor *tensor, const Window &window)
Add the passed 4D tensor's parameters to the object's kernel's arguments starting from the index idx.
template<typename T >
void add_argument (unsigned int &idx, T value)
Add the passed parameters to the object's kernel's arguments starting from the index idx.
void set_lws_hint (const cl::NDRange &lws_hint)
Set the Local-Workgroup-Size hint.
cl::NDRange lws_hint () const
Return the Local-Workgroup-Size hint.
const std::string & config_id () const
Get the configuration ID.
void set_target (GPUTarget target)
Set the targeted GPU architecture.
void set_target (cl::Device &device)
Set the targeted GPU architecture according to the CL device.
GPUTarget get_target () const
Get the targeted GPU architecture.
size_t get_max_workgroup_size ()
Get the maximum workgroup size for the device the CLKernelLibrary uses.
template<typename T , unsigned int dimension_size>
void add_array_argument (unsigned &idx, const ICLArray< T > *array, const Strides &strides, unsigned int num_dimensions, const Window &window)
Add the passed array's parameters to the object's kernel's arguments starting from the index idx.
template<unsigned int dimension_size>
void add_tensor_argument (unsigned &idx, const ICLTensor *tensor, const Window &window)
Public Member Functions inherited from IKernel
IKernel ()
Constructor.
virtual ~IKernel ()=default
Destructor.
virtual bool is_parallelisable () const
Indicates whether or not the kernel is parallelisable.
const Window & window () const
The maximum window the kernel can be executed on.
Additional Inherited Members
Static Public Member Functions inherited from ICLKernel
static constexpr unsigned int num_arguments_per_1D_array ()
Returns the number of arguments enqueued per 1D array object.
static constexpr unsigned int num_arguments_per_1D_tensor ()
Returns the number of arguments enqueued per 1D tensor object.
static constexpr unsigned int num_arguments_per_2D_tensor ()
Returns the number of arguments enqueued per 2D tensor object.
static constexpr unsigned int num_arguments_per_3D_tensor ()
Returns the number of arguments enqueued per 3D tensor object.
static constexpr unsigned int num_arguments_per_4D_tensor ()
Returns the number of arguments enqueued per 4D tensor object.
static cl::NDRange gws_from_window (const Window &window)
Get the global work size given an execution window.
Detailed Description
Interface for the kernel to run the vertical pass of 5x5 Sobel filter on a tensor.
Definition at line 75 of file CLSobel5x5Kernel.h.
Constructor & Destructor Documentation
CLSobel5x5VertKernel() [1/3]
CLSobel5x5VertKernel ()
Default constructor: initialize all the pointers to nullptr and parameters to zero.
Definition at line 134 of file CLSobel5x5Kernel.cpp.
     : _input_x(nullptr), _input_y(nullptr), _output_x(nullptr), _output_y(nullptr), _run_sobel_x(false), _run_sobel_y(false)
 {
 }
CLSobel5x5VertKernel() [2/3]
CLSobel5x5VertKernel (const CLSobel5x5VertKernel &) delete
Prevent instances of this class from being copied (As this class contains pointers)
CLSobel5x5VertKernel() [3/3]
CLSobel5x5VertKernel (CLSobel5x5VertKernel &&) default
Allow instances of this class to be moved.
~CLSobel5x5VertKernel()
~CLSobel5x5VertKernel () default
Default destructor.
Member Function Documentation
border_size()
BorderSize border_size () const override virtual
The size of the border for that kernel.
Returns
The width in number of elements of the border.
Reimplemented from IKernel.
Definition at line 139 of file CLSobel5x5Kernel.cpp.
 {
     return BorderSize{ 2, 0 };
 }
Referenced by CLSobel5x5VertKernel::configure().
configure()
void configure (const ICLTensor * input_x, const ICLTensor * input_y, ICLTensor * output_x, ICLTensor * output_y, bool border_undefined)
Initialise the kernel's source, destination and border.
Note
At least one of output_x or output_y must be set and the corresponding input.
Parameters
[in] input_x (Optional) Input for X (X output of horizontal pass). Data types supported: S16.
[in] input_y (Optional) Input for Y (Y output of horizontal pass). Data types supported: S16.
[out] output_x (Optional) Destination tensor for the X gradient, Data types supported: S16.
[out] output_y (Optional) Destination tensor for the Y gradient, Data types supported: S16.
[in] border_undefined True if the border mode is undefined. False if it's replicate or constant.
Definition at line 144 of file CLSobel5x5Kernel.cpp.
 {
     ARM_COMPUTE_ERROR_ON((output_x == nullptr) && (output_y == nullptr));
     _run_sobel_x = output_x != nullptr;
     _run_sobel_y = output_y != nullptr;
     if(_run_sobel_x)
     {
         ARM_COMPUTE_ERROR_ON_DATA_TYPE_CHANNEL_NOT_IN(input_x, 1, DataType::S16);
         ARM_COMPUTE_ERROR_ON_DATA_TYPE_CHANNEL_NOT_IN(output_x, 1, DataType::S16);
     }
     if(_run_sobel_y)
     {
         ARM_COMPUTE_ERROR_ON_DATA_TYPE_CHANNEL_NOT_IN(input_y, 1, DataType::S16);
         ARM_COMPUTE_ERROR_ON_DATA_TYPE_CHANNEL_NOT_IN(output_y, 1, DataType::S16);
     }
     _input_x  = input_x;
     _input_y  = input_y;
     _output_x = output_x;
     _output_y = output_y;
     // Set build options
     std::set<std::string> build_opts;
     if(_run_sobel_x)
     {
         build_opts.insert("-DGRAD_X");
     }
     if(_run_sobel_y)
     {
         build_opts.insert("-DGRAD_Y");
     }
     // Create kernel
     _kernel = static_cast<cl::Kernel>(CLKernelLibrary::get().create_kernel("sobel_separable5x1", build_opts));
     const ICLTensor *input = _run_sobel_x ? _input_x : _input_y;
     // Configure kernel window
     constexpr unsigned int num_elems_processed_per_iteration = 8;
     constexpr unsigned int num_elems_written_per_iteration   = 8;
     constexpr unsigned int num_elems_read_per_iteration      = 8;
     constexpr unsigned int num_rows_read_per_iteration       = 5;
     Window win = calculate_max_window(*input->info(), Steps(num_elems_processed_per_iteration), border_undefined, border_size());
     AccessWindowRectangle  input_x_access(input_x == nullptr ? nullptr : input_x->info(), 0, -border_size().top, num_elems_read_per_iteration, num_rows_read_per_iteration);
     AccessWindowRectangle  input_y_access(input_y == nullptr ? nullptr : input_y->info(), 0, -border_size().top, num_elems_read_per_iteration, num_rows_read_per_iteration);
     AccessWindowHorizontal output_x_access(output_x == nullptr ? nullptr : output_x->info(), 0, num_elems_written_per_iteration);
     AccessWindowHorizontal output_y_access(output_y == nullptr ? nullptr : output_y->info(), 0, num_elems_written_per_iteration);
     update_window_and_padding(win, input_x_access, input_y_access, output_x_access, output_y_access);
     output_x_access.set_valid_region(win, input->info()->valid_region(), border_undefined, border_size());
     output_y_access.set_valid_region(win, input->info()->valid_region(), border_undefined, border_size());
     ICLKernel::configure_internal(win);
 }
References ARM_COMPUTE_ERROR_ON, ARM_COMPUTE_ERROR_ON_DATA_TYPE_CHANNEL_NOT_IN, CLSobel5x5VertKernel::border_size(), arm_compute::calculate_max_window(), arm_compute::create_kernel(), CLKernelLibrary::get(), ITensor::info(), arm_compute::S16, BorderSize::top, arm_compute::update_window_and_padding(), and ITensorInfo::valid_region().
Referenced by CLSobel5x5::configure().
operator=() [1/2]
CLSobel5x5VertKernel& operator= (const CLSobel5x5VertKernel &) delete
Prevent instances of this class from being copied (As this class contains pointers)
operator=() [2/2]
CLSobel5x5VertKernel& operator= (CLSobel5x5VertKernel &&) default
Allow instances of this class to be moved.
run()
void run (const Window & window, cl::CommandQueue & queue) override virtual
Enqueue the OpenCL kernel to process the given window on the passed OpenCL command queue.
Note
The queue is not flushed by this method, and therefore the kernel will not have been executed by the time this method returns.
Parameters
[in] window Region on which to execute the kernel. (Must be a valid region of the window returned by window()).
[in,out] queue Command queue on which to enqueue the kernel.
Implements ICLKernel.
Definition at line 207 of file CLSobel5x5Kernel.cpp.
 {
     ARM_COMPUTE_ERROR_ON_UNCONFIGURED_KERNEL(this);
     ARM_COMPUTE_ERROR_ON_INVALID_SUBWINDOW(ICLKernel::window(), window);
     Window slice = window.first_slice_window_2D();
     do
     {
         unsigned int idx = 0;
         if(_run_sobel_x)
         {
             add_2D_tensor_argument(idx, _input_x, slice);
             add_2D_tensor_argument(idx, _output_x, slice);
         }
         if(_run_sobel_y)
         {
             add_2D_tensor_argument(idx, _input_y, slice);
             add_2D_tensor_argument(idx, _output_y, slice);
         }
         _kernel.setArg(idx++, 0 /*dummy*/);
         enqueue(queue, *this, slice);
     }
     while(window.slide_window_slice_2D(slice));
 }
References ICLKernel::add_2D_tensor_argument(), ARM_COMPUTE_ERROR_ON_INVALID_SUBWINDOW, ARM_COMPUTE_ERROR_ON_UNCONFIGURED_KERNEL, arm_compute::enqueue(), Window::first_slice_window_2D(), arm_compute::test::validation::reference::slice(), Window::slide_window_slice_2D(), and IKernel::window().
The documentation for this class was generated from the following files:
arm_compute/core/CL/kernels/CLSobel5x5Kernel.h
src/core/CL/kernels/CLSobel5x5Kernel.cpp