Compute Library: CLSeparableConvolutionVertKernel< matrix_size > Class Template Reference
CLSeparableConvolutionVertKernel< matrix_size > Class Template Reference
Kernel for the Vertical pass of a Separable Convolution.
#include <CLConvolutionKernel.h>
Public Member Functions
void configure (const ICLTensor *input, ICLTensor *output, const int16_t *conv, uint32_t scale, bool border_undefined, DataType data_type=DataType::S32)
Initialise the kernel's input, output and border mode.
BorderSize border_size () const override
The size of the border for that kernel.
Public Member Functions inherited from ICLSimple2DKernel
void run (const Window &window, cl::CommandQueue &queue) override
Enqueue the OpenCL kernel to process the given window on the passed OpenCL command queue.
Public Member Functions inherited from ICLSimpleKernel
ICLSimpleKernel ()
Constructor.
ICLSimpleKernel (const ICLSimpleKernel &)=delete
Prevent instances of this class from being copied (As this class contains pointers)
ICLSimpleKernel & operator= (const ICLSimpleKernel &)=delete
Prevent instances of this class from being copied (As this class contains pointers)
ICLSimpleKernel (ICLSimpleKernel &&)=default
Allow instances of this class to be moved.
ICLSimpleKernel & operator= (ICLSimpleKernel &&)=default
Allow instances of this class to be moved.
~ICLSimpleKernel ()=default
Default destructor.
void configure (const ICLTensor *input, ICLTensor *output, unsigned int num_elems_processed_per_iteration, bool border_undefined=false, const BorderSize &border_size=BorderSize())
Configure the kernel.
Public Member Functions inherited from ICLKernel
ICLKernel ()
Constructor.
cl::Kernel & kernel ()
Returns a reference to the OpenCL kernel of this object.
template<typename T >
void add_1D_array_argument (unsigned int &idx, const ICLArray< T > *array, const Strides &strides, unsigned int num_dimensions, const Window &window)
Add the passed 1D array's parameters to the object's kernel's arguments starting from the index idx.
void add_1D_tensor_argument (unsigned int &idx, const ICLTensor *tensor, const Window &window)
Add the passed 1D tensor's parameters to the object's kernel's arguments starting from the index idx.
void add_2D_tensor_argument (unsigned int &idx, const ICLTensor *tensor, const Window &window)
Add the passed 2D tensor's parameters to the object's kernel's arguments starting from the index idx.
void add_3D_tensor_argument (unsigned int &idx, const ICLTensor *tensor, const Window &window)
Add the passed 3D tensor's parameters to the object's kernel's arguments starting from the index idx.
void add_4D_tensor_argument (unsigned int &idx, const ICLTensor *tensor, const Window &window)
Add the passed 4D tensor's parameters to the object's kernel's arguments starting from the index idx.
template<typename T >
void add_argument (unsigned int &idx, T value)
Add the passed parameters to the object's kernel's arguments starting from the index idx.
void set_lws_hint (const cl::NDRange &lws_hint)
Set the Local-Workgroup-Size hint.
cl::NDRange lws_hint () const
Return the Local-Workgroup-Size hint.
const std::string & config_id () const
Get the configuration ID.
void set_target (GPUTarget target)
Set the targeted GPU architecture.
void set_target (cl::Device &device)
Set the targeted GPU architecture according to the CL device.
GPUTarget get_target () const
Get the targeted GPU architecture.
size_t get_max_workgroup_size ()
Get the maximum workgroup size for the device the CLKernelLibrary uses.
template<typename T , unsigned int dimension_size>
void add_array_argument (unsigned &idx, const ICLArray< T > *array, const Strides &strides, unsigned int num_dimensions, const Window &window)
Add the passed array's parameters to the object's kernel's arguments starting from the index idx.
template<unsigned int dimension_size>
void add_tensor_argument (unsigned &idx, const ICLTensor *tensor, const Window &window)
Public Member Functions inherited from IKernel
IKernel ()
Constructor.
virtual ~IKernel ()=default
Destructor.
virtual bool is_parallelisable () const
Indicates whether or not the kernel is parallelisable.
const Window & window () const
The maximum window the kernel can be executed on.
Additional Inherited Members
Static Public Member Functions inherited from ICLKernel
static constexpr unsigned int num_arguments_per_1D_array ()
Returns the number of arguments enqueued per 1D array object.
static constexpr unsigned int num_arguments_per_1D_tensor ()
Returns the number of arguments enqueued per 1D tensor object.
static constexpr unsigned int num_arguments_per_2D_tensor ()
Returns the number of arguments enqueued per 2D tensor object.
static constexpr unsigned int num_arguments_per_3D_tensor ()
Returns the number of arguments enqueued per 3D tensor object.
static constexpr unsigned int num_arguments_per_4D_tensor ()
Returns the number of arguments enqueued per 4D tensor object.
static cl::NDRange gws_from_window (const Window &window)
Get the global work size given an execution window.
Detailed Description
template<unsigned int matrix_size>
class arm_compute::CLSeparableConvolutionVertKernel< matrix_size >
Kernel for the Vertical pass of a Separable Convolution.
Currently supports 5x5, 7x7, 9x9
Definition at line 114 of file CLConvolutionKernel.h.
Member Function Documentation
border_size()
BorderSize border_size () const override virtual
The size of the border for that kernel.
Returns
The width in number of elements of the border.
Reimplemented from IKernel.
Definition at line 177 of file CLConvolutionKernel.cpp.
 {
     return BorderSize{ matrix_size / 2, 0 };
 }
configure()
void configure (const ICLTensor * input, ICLTensor * output, const int16_t * conv, uint32_t scale, bool border_undefined, DataType data_type = DataType::S32)
Initialise the kernel's input, output and border mode.
Parameters
[in] input Source tensor. Data types supported: S16.
[out] output Destination tensor, Data types supported: U8, S16.
[in] conv Convolution matrix to apply to the input tensor.
[in] scale Scale of the convolution matrix.
[in] border_undefined True if the border mode is undefined. False if it's replicate or constant.
[in] data_type Data type to use for intermeidate result.
See also
data_type_for_convolution
Definition at line 183 of file CLConvolutionKernel.cpp.
 {
     ARM_COMPUTE_ERROR_ON_DATA_TYPE_CHANNEL_NOT_IN(input, 1, DataType::U16, DataType::S16, DataType::S32);
     ARM_COMPUTE_ERROR_ON_DATA_TYPE_CHANNEL_NOT_IN(output, 1, DataType::U8, DataType::S16);
     ARM_COMPUTE_ERROR_ON((matrix_size != 5) && (matrix_size != 7) && (matrix_size != 9));
     ARM_COMPUTE_ERROR_ON(scale == 0);
     _input  = input;
     _output = output;
     std::set<std::string> build_opts;
     std::array<int16_t, matrix_size *matrix_size> mat = { 0 };
     memcpy(mat.data() + matrix_size, conv, matrix_size * sizeof(int16_t));
     for(unsigned int j = 0; j < matrix_size * matrix_size; j++)
     {
         build_opts.insert("-DMAT" + support::cpp11::to_string(j) + "=" + support::cpp11::to_string(mat[j]));
     }
     build_opts.insert("-DSCALE=" + support::cpp11::to_string(scale));
     build_opts.insert("-DDATA_TYPE=" + get_cl_type_from_data_type(input->info()->data_type()));
     build_opts.insert("-DCOMPUTE_TYPE=" + get_cl_type_from_data_type(data_type));
     std::stringstream out_type;
     out_type << "-DDATA_TYPE_OUT=" << get_cl_type_from_data_type(output->info()->data_type());
     build_opts.insert(out_type.str());
     // Create kernel
     _kernel = static_cast<cl::Kernel>(CLKernelLibrary::get().create_kernel("convolution_separable" + support::cpp11::to_string(matrix_size) + "x1_static", build_opts));
     // Configure kernel window
     constexpr unsigned int num_elems_processed_per_iteration = 8;
     constexpr unsigned int num_elems_written_per_iteration   = 8;
     constexpr unsigned int num_elems_read_per_iteration      = 8;
     constexpr unsigned int num_rows_read_per_iteration       = matrix_size;
     Window win = calculate_max_window(*input->info(), Steps(num_elems_processed_per_iteration), border_undefined, border_size());
     AccessWindowRectangle  input_access(input->info(), 0, -border_size().top, num_elems_read_per_iteration, num_rows_read_per_iteration);
     AccessWindowHorizontal output_access(output->info(), 0, num_elems_written_per_iteration);
     update_window_and_padding(win, input_access, output_access);
     output_access.set_valid_region(win, input->info()->valid_region(), border_undefined, border_size());
     ICLKernel::configure_internal(win);
 }
References ARM_COMPUTE_ERROR_ON, ARM_COMPUTE_ERROR_ON_DATA_TYPE_CHANNEL_NOT_IN, arm_compute::calculate_max_window(), arm_compute::test::validation::conv, arm_compute::create_kernel(), arm_compute::test::validation::data_type, ITensorInfo::data_type(), CLKernelLibrary::get(), arm_compute::get_cl_type_from_data_type(), ITensor::info(), arm_compute::S16, arm_compute::S32, arm_compute::test::validation::scale, arm_compute::support::cpp11::to_string(), arm_compute::U16, arm_compute::U8, arm_compute::update_window_and_padding(), and ITensorInfo::valid_region().
Referenced by CLGaussian5x5VertKernel::configure().
The documentation for this class was generated from the following files:
arm_compute/core/CL/kernels/CLConvolutionKernel.h
src/core/CL/kernels/CLConvolutionKernel.cpp