Compute Library: NESpaceToBatchLayerKernel Class Reference
NESpaceToBatchLayerKernel Class Reference
Interface for the space to batch kernel.
#include <NESpaceToBatchLayerKernel.h>
Public Member Functions
const char * name () const override
Name of the kernel.
NESpaceToBatchLayerKernel ()
Default constructor.
NESpaceToBatchLayerKernel (const NESpaceToBatchLayerKernel &)=delete
Prevent instances of this class from being copied (As this class contains pointers)
NESpaceToBatchLayerKernel & operator= (const NESpaceToBatchLayerKernel &)=delete
Prevent instances of this class from being copied (As this class contains pointers)
NESpaceToBatchLayerKernel (NESpaceToBatchLayerKernel &&)=default
Allow instances of this class to be moved.
NESpaceToBatchLayerKernel & operator= (NESpaceToBatchLayerKernel &&)=default
Allow instances of this class to be moved.
~NESpaceToBatchLayerKernel ()=default
Default destructor.
void configure (const ITensor *input, const ITensor *block_shape, const ITensor *paddings, ITensor *output)
Initialise the kernel's inputs and output.
void configure (const ITensor *input, const int block_shape_x, const int block_shape_y, const Size2D &padding_left, const Size2D &padding_right, ITensor *output)
Initialise the kernel's input and output.
void run (const Window &window, const ThreadInfo &info) override
Execute the kernel on the passed window.
Public Member Functions inherited from ICPPKernel
virtual ~ICPPKernel ()=default
Default destructor.
Public Member Functions inherited from IKernel
IKernel ()
Constructor.
virtual ~IKernel ()=default
Destructor.
virtual bool is_parallelisable () const
Indicates whether or not the kernel is parallelisable.
virtual BorderSize border_size () const
The size of the border for that kernel.
const Window & window () const
The maximum window the kernel can be executed on.
Static Public Member Functions
static Status validate (const ITensorInfo *input, const ITensorInfo *block_shape, const ITensorInfo *paddings, const ITensorInfo *output)
Static function to check if given info will lead to a valid configuration of NESpaceToBatchLayerKernel.
static Status validate (const ITensorInfo *input, const int block_shape_x, const int block_shape_y, const Size2D &padding_left, const Size2D &padding_right, const ITensorInfo *output)
Static function to check if given info will lead to a valid configuration of NESpaceToBatchLayerKernel (Static block shape and paddings)
Detailed Description
Interface for the space to batch kernel.
Definition at line 35 of file NESpaceToBatchLayerKernel.h.
Constructor & Destructor Documentation
NESpaceToBatchLayerKernel() [1/3]
NESpaceToBatchLayerKernel ()
Default constructor.
Definition at line 88 of file NESpaceToBatchLayerKernel.cpp.
     : _input(nullptr), _block_shape(nullptr), _paddings(nullptr), _output(nullptr), _padding_left(), _block_shape_x(), _block_shape_y()
 {
 }
NESpaceToBatchLayerKernel() [2/3]
NESpaceToBatchLayerKernel (const NESpaceToBatchLayerKernel &) delete
Prevent instances of this class from being copied (As this class contains pointers)
NESpaceToBatchLayerKernel() [3/3]
NESpaceToBatchLayerKernel (NESpaceToBatchLayerKernel &&) default
Allow instances of this class to be moved.
~NESpaceToBatchLayerKernel()
~NESpaceToBatchLayerKernel () default
Default destructor.
Member Function Documentation
configure() [1/2]
void configure (const ITensor * input, const ITensor * block_shape, const ITensor * paddings, ITensor * output)
Initialise the kernel's inputs and output.
Parameters
[in] input Tensor input. Supported tensor rank: 4. Data types supported: U8/S8/QASYMM8/U16/S16/F16/U32/S32/F32.
[in] block_shape 1-D tensor with shape [M]. Data types supported: S32
[in] paddings 2-D tensor with shape [2, M]. Data types supported: S32
[out] output Tensor output. Data types supported: same as input
Definition at line 93 of file NESpaceToBatchLayerKernel.cpp.
 {
     ARM_COMPUTE_ERROR_ON_NULLPTR(input, output);
     ARM_COMPUTE_ERROR_THROW_ON(validate_arguments(input->info(), block_shape->info(), paddings->info(), output->info()));
     _input       = input;
     _block_shape = block_shape;
     _paddings    = paddings;
     _output      = output;
     // Configure kernel window
     Window win = calculate_max_window(*output->info(), Steps());
     ICPPKernel::configure(win);
 }
References ARM_COMPUTE_ERROR_ON_NULLPTR, ARM_COMPUTE_ERROR_THROW_ON, arm_compute::calculate_max_window(), and ITensor::info().
Referenced by NESpaceToBatchLayer::configure().
configure() [2/2]
void configure (const ITensor * input, const int block_shape_x, const int block_shape_y, const Size2D & padding_left, const Size2D & padding_right, ITensor * output)
Initialise the kernel's input and output.
(Static block shape and paddings)
Parameters
[in] input Tensor input. Supported tensor rank: 4. Data types supported: U8/S8/QASYMM8/U16/S16/F16/U32/S32/F32.
[in] block_shape_x Block shape x value.
[in] block_shape_y Block shape y value.
[in] padding_left The left padding of the output tensor.
[in] padding_right The right padding of the output tensor.
[out] output Tensor output. Data types supported: same as input
Definition at line 108 of file NESpaceToBatchLayerKernel.cpp.
 {
     ARM_COMPUTE_ERROR_ON_NULLPTR(input, output);
     TensorShape output_shape = misc::shape_calculator::compute_space_to_batch_shape(input->info(), block_shape_x, block_shape_y, padding_left, padding_right);
     auto_init_if_empty(*output->info(), output_shape, 1, input->info()->data_type());
     ARM_COMPUTE_ERROR_THROW_ON(validate_arguments_static(input->info(), block_shape_x, block_shape_y, padding_left, padding_right, output->info()));
     _input         = input;
     _output        = output;
     _block_shape_x = block_shape_x;
     _block_shape_y = block_shape_y;
     _padding_left  = padding_left;
     // Configure kernel window
     Window win = calculate_max_window(*output->info(), Steps());
     INEKernel::configure(win);
 }
References ARM_COMPUTE_ERROR_ON_NULLPTR, ARM_COMPUTE_ERROR_THROW_ON, arm_compute::auto_init_if_empty(), arm_compute::calculate_max_window(), arm_compute::misc::shape_calculator::compute_space_to_batch_shape(), ITensorInfo::data_type(), ITensor::info(), and arm_compute::test::validation::output_shape.
name()
const char* name () const inline override virtual
Name of the kernel.
Returns
Kernel name
Implements ICPPKernel.
Definition at line 38 of file NESpaceToBatchLayerKernel.h.
     {
         return "NESpaceToBatchLayerKernel";
     }
operator=() [1/2]
NESpaceToBatchLayerKernel& operator= (const NESpaceToBatchLayerKernel &) delete
Prevent instances of this class from being copied (As this class contains pointers)
operator=() [2/2]
NESpaceToBatchLayerKernel& operator= (NESpaceToBatchLayerKernel &&) default
Allow instances of this class to be moved.
run()
void run (const Window & window, const ThreadInfo & info) override virtual
Execute the kernel on the passed window.
Warning
If is_parallelisable() returns false then the passed window must be equal to window()
Note
The window has to be a region within the window returned by the window() method
The width of the window has to be a multiple of num_elems_processed_per_iteration().
Parameters
[in] window Region on which to execute the kernel. (Must be a region of the window returned by window())
[in] info Info about executing thread and CPU.
Implements ICPPKernel.
Definition at line 141 of file NESpaceToBatchLayerKernel.cpp.
 {
     ARM_COMPUTE_UNUSED(info);
     ARM_COMPUTE_ERROR_ON_UNCONFIGURED_KERNEL(this);
     ARM_COMPUTE_ERROR_ON_INVALID_SUBWINDOW(ICPPKernel::window(), window);
     if(_block_shape != nullptr)
     {
         // Retrieve the block shapes dynamically
         _block_shape_x = *(reinterpret_cast<const int *>(_block_shape->ptr_to_element(0)));
         _block_shape_y = *(reinterpret_cast<const int *>(_block_shape->ptr_to_element(1)));
     }
     if(_paddings != nullptr)
     {
         const size_t pad_left_x = *reinterpret_cast<const size_t *>(_paddings->ptr_to_element({ 0, 0 }));
         const size_t pad_left_y = *reinterpret_cast<const size_t *>(_paddings->ptr_to_element({ 1, 0 }));
         _padding_left           = Size2D(pad_left_x, pad_left_y);
     }
     const DataLayout data_layout  = _input->info()->data_layout();
     const int        height_idx   = get_data_layout_dimension_index(data_layout, DataLayoutDimension::HEIGHT);
     const int        width_idx    = get_data_layout_dimension_index(data_layout, DataLayoutDimension::WIDTH);
     const int        element_size = _input->info()->element_size();
     const size_t height     = _input->info()->dimension(height_idx);
     const size_t width      = _input->info()->dimension(width_idx);
     const size_t batch_size = _input->info()->dimension(3);
     Window slice_out = window.first_slice_window_3D();
     Window slice_in  = window.first_slice_window_4D();
     slice_in.set(Window::DimX, Window::Dimension(0, 0, 0));
     slice_in.set(Window::DimY, Window::Dimension(0, 0, 0));
     slice_in.set(Window::DimZ, Window::Dimension(0, 0, 0));
     slice_in.set(3, Window::Dimension(0, 0, 0));
     int batch_id = 0;
     // Main loop for NCHW and NHWC
     if(_output->info()->data_layout() == DataLayout::NCHW)
     {
         do
         {
             Iterator out(_output, slice_out);
             execute_window_loop(slice_out, [&](const Coordinates & id)
             {
                 const size_t out_x = id.x();
                 const size_t out_y = id.y();
                 const size_t z     = id.z();
                 const size_t pos_x = out_x * _block_shape_x + (batch_id / batch_size) % _block_shape_x;
                 const size_t pos_y = out_y * _block_shape_y + (batch_id / batch_size) / _block_shape_x;
                 if(pos_y >= _padding_left.y() && pos_y < _padding_left.y() + height && pos_x >= _padding_left.x() && pos_x < _padding_left.x() + width)
                 {
                     const int   w    = batch_id % batch_size;
                     const int   in_x = pos_x - _padding_left.x();
                     const int   in_y = pos_y - _padding_left.y();
                     Coordinates input_coords{ in_x, in_y, z, w };
                     memcpy(out.ptr(), _input->ptr_to_element(input_coords), element_size);
                 }
             },
             out);
             ++batch_id;
         }
         while(window.slide_window_slice_3D(slice_out));
     }
     else
     {
         do
         {
             Iterator out(_output, slice_out);
             execute_window_loop(slice_out, [&](const Coordinates & id)
             {
                 const size_t out_x = id.y();
                 const size_t out_y = id.z();
                 const size_t z     = id.x();
                 const size_t pos_x = out_x * _block_shape_x + (batch_id / batch_size) % _block_shape_x;
                 const size_t pos_y = out_y * _block_shape_y + (batch_id / batch_size) / _block_shape_x;
                 if(pos_y >= _padding_left.y() && pos_y < _padding_left.y() + height && pos_x >= _padding_left.x() && pos_x < _padding_left.x() + width)
                 {
                     const int   w    = batch_id % batch_size;
                     const int   in_x = pos_x - _padding_left.x();
                     const int   in_y = pos_y - _padding_left.y();
                     Coordinates input_coords{ z, in_x, in_y, w };
                     memcpy(out.ptr(), _input->ptr_to_element(input_coords), element_size);
                 }
             },
             out);
             ++batch_id;
         }
         while(window.slide_window_slice_3D(slice_out));
     }
 }
References ARM_COMPUTE_ERROR_ON_INVALID_SUBWINDOW, ARM_COMPUTE_ERROR_ON_UNCONFIGURED_KERNEL, ARM_COMPUTE_UNUSED, ITensorInfo::data_layout(), ITensorInfo::dimension(), Window::DimX, Window::DimY, Window::DimZ, ITensorInfo::element_size(), arm_compute::execute_window_loop(), Window::first_slice_window_3D(), Window::first_slice_window_4D(), arm_compute::get_data_layout_dimension_index(), arm_compute::HEIGHT, ITensor::info(), arm_compute::test::validation::info, arm_compute::NCHW, Iterator::ptr(), ITensor::ptr_to_element(), Window::set(), Window::slide_window_slice_3D(), arm_compute::test::validation::w, arm_compute::WIDTH, IKernel::window(), Size2D::x(), Window::x(), Size2D::y(), and Window::y().
validate() [1/2]
Status validate (const ITensorInfo * input, const ITensorInfo * block_shape, const ITensorInfo * paddings, const ITensorInfo * output) static
Static function to check if given info will lead to a valid configuration of NESpaceToBatchLayerKernel.
Parameters
[in] input Tensor input. Supported tensor rank: 4. Data types supported: U8/S8/QASYMM8/U16/S16/F16/U32/S32/F32.
[in] block_shape 1-D tensor with shape [M]. Data types supported: S32
[in] paddings 2-D tensor with shape [2, M]. Data types supported: S32
[in] output Tensor output. Data types supported: same as input
Returns
a status
Definition at line 129 of file NESpaceToBatchLayerKernel.cpp.
 {
     ARM_COMPUTE_RETURN_ON_ERROR(validate_arguments(input, block_shape, paddings, output));
     return Status{};
 }
References ARM_COMPUTE_RETURN_ON_ERROR.
Referenced by NESpaceToBatchLayer::validate().
validate() [2/2]
Status validate (const ITensorInfo * input, const int block_shape_x, const int block_shape_y, const Size2D & padding_left, const Size2D & padding_right, const ITensorInfo * output) static
Static function to check if given info will lead to a valid configuration of NESpaceToBatchLayerKernel (Static block shape and paddings)
Parameters
[in] input Tensor input. Supported tensor rank: 4. Data types supported: U8/S8/QASYMM8/U16/S16/F16/U32/S32/F32.
[in] block_shape_x Block shape x value.
[in] block_shape_y Block shape y value.
[in] padding_left The left padding of the output tensor.
[in] padding_right The right padding of the output tensor.
[in] output Tensor output. Data types supported: same as input
Returns
a status
Definition at line 134 of file NESpaceToBatchLayerKernel.cpp.
 {
     ARM_COMPUTE_RETURN_ON_ERROR(validate_arguments_static(input, block_shape_x, block_shape_y, padding_left, padding_right, output));
     return Status{};
 }
References ARM_COMPUTE_RETURN_ON_ERROR.
The documentation for this class was generated from the following files:
arm_compute/core/NEON/kernels/NESpaceToBatchLayerKernel.h
src/core/NEON/kernels/NESpaceToBatchLayerKernel.cpp