Compute Library: GCFullyConnectedLayer Class Reference
GCFullyConnectedLayer Class Reference
Basic function to compute a Fully Connected layer on OpenGL ES.
#include <GCFullyConnectedLayer.h>
Public Member Functions
GCFullyConnectedLayer (std::shared_ptr< IMemoryManager > memory_manager=nullptr)
Constructor.
GCFullyConnectedLayer (const GCFullyConnectedLayer &)=delete
Prevent instances of this class from being copied (As this class contains pointers)
GCFullyConnectedLayer (GCFullyConnectedLayer &&)=default
Default move constructor.
GCFullyConnectedLayer & operator= (const GCFullyConnectedLayer &)=delete
Prevent instances of this class from being copied (As this class contains pointers)
GCFullyConnectedLayer & operator= (GCFullyConnectedLayer &&)=default
Default move assignment operator.
void configure (const IGCTensor *input, const IGCTensor *weights, const IGCTensor *biases, IGCTensor *output, FullyConnectedLayerInfo fc_info=FullyConnectedLayerInfo())
Set the input and output tensors.
void run () override
Run the kernels contained in the function.
void prepare () override
Prepare the function for executing.
Public Member Functions inherited from IFunction
virtual ~IFunction ()=default
Destructor.
Detailed Description
Basic function to compute a Fully Connected layer on OpenGL ES.
This function calls the following OpenGL ES kernels:
GCIm2ColKernel (called when the input comes from a convolutional layer)
GCFullyConnectedLayerReshapeWeights (if are_weights_reshaped is set to false and transpose_weights is set to true) (called once)
GCGEMMMatrixMultiplyKernel
GCGEMMMatrixAccumulateBiasesKernel (if biases is not equal to nullptr)
Note
The fully connected layer accepts "weights" tensors only with 2 dimensions.
Definition at line 63 of file GCFullyConnectedLayer.h.
Constructor & Destructor Documentation
GCFullyConnectedLayer() [1/3]
GCFullyConnectedLayer (std::shared_ptr< IMemoryManager > memory_manager = nullptr)
Constructor.
Definition at line 41 of file GCFullyConnectedLayer.cpp.
     : _memory_group(std::move(memory_manager)), _im2col_kernel(), _reshape_weights_kernel(), _mm_kernel(), _accumulate_biases_kernel(), _im2col_output(), _reshape_weights_output(),
       _original_weights(nullptr), _are_weights_reshaped(true), _is_fc_after_conv(true), _accumulate_biases(false)
 {
 }
GCFullyConnectedLayer() [2/3]
GCFullyConnectedLayer (const GCFullyConnectedLayer &) delete
Prevent instances of this class from being copied (As this class contains pointers)
GCFullyConnectedLayer() [3/3]
GCFullyConnectedLayer (GCFullyConnectedLayer &&) default
Default move constructor.
Member Function Documentation
configure()
void configure (const IGCTensor * input, const IGCTensor * weights, const IGCTensor * biases, IGCTensor * output, FullyConnectedLayerInfo fc_info = FullyConnectedLayerInfo())
Set the input and output tensors.
Parameters
[in] input Source tensor. Data type supported: F16/F32.
[in] weights Weights tensor. The weights must be 2 dimensional. Data type supported: Same as input
[in] biases Bias tensor. It can be nullptr. Data type supported:Same as input.
[out] output Destination tensor. Data type supported: Same as input.
[in] fc_info (Optional) Fully connected layer additional info
Definition at line 82 of file GCFullyConnectedLayer.cpp.
 {
     ARM_COMPUTE_ERROR_ON_DATA_TYPE_CHANNEL_NOT_IN(input, 1, DataType::F32, DataType::F16);
     ARM_COMPUTE_ERROR_ON_MISMATCHING_DATA_TYPES(input, weights, output);
     ARM_COMPUTE_ERROR_ON(weights->info()->num_dimensions() > 2);
     _original_weights     = weights;
     _are_weights_reshaped = fc_info.transpose_weights ? fc_info.are_weights_reshaped : true;
     _is_fc_after_conv     = true;
     _accumulate_biases    = false;
     if(biases != nullptr)
     {
         ARM_COMPUTE_ERROR_ON_MISMATCHING_DATA_TYPES(input, biases);
         _accumulate_biases = true;
         // Configure accumulate biases kernel
         _accumulate_biases_kernel.configure(output, biases);
     }
     // With the Fully Connected layer we can have 4 different cases:
     //  1) Convolution layer -> Fully Connected layer without batches
     //  2) Fully Connected layer -> Fully Connected layer without batches
     //  3) Convolution layer -> Fully Connected layer with batches
     //  4) Fully Connected layer -> Fully Connected layer with batches
     const IGCTensor *weights_to_use = weights;
     if(!_are_weights_reshaped)
     {
         weights_to_use = &_reshape_weights_output;
         // Reshape the weights
         _reshape_weights_kernel.configure(weights, &_reshape_weights_output);
     }
     // Check if we have a fully connected layer with batches
     const bool is_batched_fc_layer = output->info()->dimension(1) > 1;
     if(is_batched_fc_layer)
     {
         _is_fc_after_conv = (TensorShape::num_max_dimensions >= 4) && (std::equal(input->info()->tensor_shape().cbegin() + 3,
                                                                                   input->info()->tensor_shape().cend(),
                                                                                   output->info()->tensor_shape().cbegin() + 1));
     }
     else
     {
         _is_fc_after_conv = input->info()->num_dimensions() > 1;
     }
     if(_is_fc_after_conv)
     {
         // Fully Connected layer after a Convolution Layer without batches
         configure_conv_fc(input, weights_to_use, output);
     }
     else
     {
         // Fully Connected layer after a Fully Connected Layer without batches
         configure_fc_fc(input, weights_to_use, output);
     }
     ARM_COMPUTE_ERROR_ON(fc_info.retain_internal_weights && _reshape_weights_output.gc_buffer() == 0);
     _are_weights_reshaped = _are_weights_reshaped || fc_info.retain_internal_weights;
 }
References FullyConnectedLayerInfo::are_weights_reshaped, ARM_COMPUTE_ERROR_ON, ARM_COMPUTE_ERROR_ON_DATA_TYPE_CHANNEL_NOT_IN, ARM_COMPUTE_ERROR_ON_MISMATCHING_DATA_TYPES, Dimensions< T >::cbegin(), Dimensions< T >::cend(), GCFullyConnectedLayerReshapeWeights::configure(), GCGEMMMatrixAccumulateBiasesKernel::configure(), ITensorInfo::dimension(), arm_compute::F16, arm_compute::F32, GCTensor::gc_buffer(), ITensor::info(), CLTensor::info(), ITensorInfo::num_dimensions(), TensorInfo::num_dimensions(), Dimensions< size_t >::num_max_dimensions, FullyConnectedLayerInfo::retain_internal_weights, ITensorInfo::tensor_shape(), FullyConnectedLayerInfo::transpose_weights, and arm_compute::test::validation::weights.
Referenced by arm_compute::test::validation::DATA_TEST_CASE().
operator=() [1/2]
GCFullyConnectedLayer& operator= (const GCFullyConnectedLayer &) delete
Prevent instances of this class from being copied (As this class contains pointers)
operator=() [2/2]
GCFullyConnectedLayer& operator= (GCFullyConnectedLayer &&) default
Default move assignment operator.
prepare()
void prepare () override virtual
Prepare the function for executing.
Any one off pre-processing step required by the function is handled here
Note
Prepare stage might not need all the function's buffers' backing memory to be available in order to execute
Reimplemented from IFunction.
Definition at line 178 of file GCFullyConnectedLayer.cpp.
 {
     // Reshape of the weights (happens only once)
     if(!_are_weights_reshaped)
     {
         ARM_COMPUTE_ERROR_ON(!_original_weights->is_used());
         // Run reshape weights kernel and mark weights as unused
         _reshape_weights_output.allocator()->allocate();
         _reshape_weights_kernel.run();
         // Mark original weights tensor as unused
         _original_weights->mark_as_unused();
         _are_weights_reshaped = true;
     }
 }
References ITensorAllocator::allocate(), GCTensor::allocator(), ARM_COMPUTE_ERROR_ON, ITensor::is_used(), ITensor::mark_as_unused(), and IGCSimpleFunction::run().
Referenced by GCFullyConnectedLayer::run().
run()
void run () override virtual
Run the kernels contained in the function.
For NEON kernels:
Multi-threading is used for the kernels which are parallelisable.
By default std::thread::hardware_concurrency() threads are used.
Note
CPPScheduler::set_num_threads() can be used to manually set the number of threads
For OpenCL kernels:
All the kernels are enqueued on the queue associated with CLScheduler.
The queue is then flushed.
Note
The function will not block until the kernels are executed. It is the user's responsibility to wait.
Will call prepare() on first run if hasn't been done
Implements IFunction.
Definition at line 149 of file GCFullyConnectedLayer.cpp.
 {
     prepare();
     MemoryGroupResourceScope scope_mg(_memory_group);
     // Linearize input if it comes from a convolutional layer
     if(_is_fc_after_conv)
     {
         GCScheduler::get().dispatch(_im2col_kernel, false);
     }
     if(!_are_weights_reshaped || _is_fc_after_conv)
     {
         GCScheduler::get().memory_barrier();
     }
     // Run matrix multiply
     GCScheduler::get().dispatch(_mm_kernel, !_accumulate_biases);
     // Accumulate biases if provided
     if(_accumulate_biases)
     {
         GCScheduler::get().memory_barrier();
         GCScheduler::get().dispatch(_accumulate_biases_kernel);
     }
 }
References GCScheduler::dispatch(), GCScheduler::get(), GCScheduler::memory_barrier(), and GCFullyConnectedLayer::prepare().
The documentation for this class was generated from the following files:
arm_compute/runtime/GLES_COMPUTE/functions/GCFullyConnectedLayer.h
src/runtime/GLES_COMPUTE/functions/GCFullyConnectedLayer.cpp