Compute Library: GCDepthwiseConvolutionLayer3x3 Class Reference
GCDepthwiseConvolutionLayer3x3 Class Reference
Basic function to execute a depthwise convolution for kernel size 3x3xC.
#include <GCDepthwiseConvolutionLayer.h>
Public Member Functions
GCDepthwiseConvolutionLayer3x3 ()
Default constructor.
void configure (IGCTensor *input, const IGCTensor *weights, const IGCTensor *biases, IGCTensor *output, const PadStrideInfo &conv_info, unsigned int depth_multiplier=1, const ActivationLayerInfo &act_info=ActivationLayerInfo(), const Size2D &dilation=Size2D(1U, 1U))
Initialize the function's source, destination, conv and border_size.
void run () override final
Run the kernels contained in the function.
Public Member Functions inherited from IFunction
virtual ~IFunction ()=default
Destructor.
virtual void prepare ()
Prepare the function for executing.
Detailed Description
Basic function to execute a depthwise convolution for kernel size 3x3xC.
This function calls the following OpenGLES kernels:
GCDepthwiseConvolutionLayer3x3Kernel
GCFillBorderKernel (if pad_x or pad_y > 0)
Definition at line 44 of file GCDepthwiseConvolutionLayer.h.
Constructor & Destructor Documentation
GCDepthwiseConvolutionLayer3x3()
GCDepthwiseConvolutionLayer3x3 ()
Default constructor.
Definition at line 33 of file GCDepthwiseConvolutionLayer.cpp.
     : _kernel(nullptr), _border_handler(), _shift_handler(), _activationlayer_function(), _is_activationlayer_enabled(false)
 {
 }
Member Function Documentation
configure()
void configure (IGCTensor * input, const IGCTensor * weights, const IGCTensor * biases, IGCTensor * output, const PadStrideInfo & conv_info, unsigned int depth_multiplier = 1, const ActivationLayerInfo & act_info = ActivationLayerInfo(), const Size2D & dilation = Size2D(1U, 1U))
Initialize the function's source, destination, conv and border_size.
Parameters
[in,out] input Source tensor. Data type supported: F16. (Written to only for border filling).
[in] weights Weights tensor. A 3D tensor with shape [3, 3, IFM]. Data type supported: Same as input.
[in] biases Biases tensor. A 1D tensor with shape [IFM]. Must be nullptr if not needed. Data type supported: Same as input.
[out] output Destination tensor. Data type supported: same as input.
[in] conv_info Padding and stride information to use for the convolution.
[in] depth_multiplier (Optional) Multiplier to apply to the input's depth in order to retrieve the output's depth. Defaults to 1.
[in] act_info (Optional) Activation layer information in case of a fused activation.
[in] dilation (Optional) Dilation, in elements, across x and y. Defaults to (1, 1). Currently supports (1,1) only.
Definition at line 38 of file GCDepthwiseConvolutionLayer.cpp.
 {
     ARM_COMPUTE_ERROR_ON(dilation.x() != 1 || dilation.y() != 1);
     ARM_COMPUTE_UNUSED(dilation);
     auto k = arm_compute::support::cpp14::make_unique<GCDepthwiseConvolutionLayer3x3Kernel>();
     k->configure(input, weights, biases, output, conv_info, depth_multiplier);
     _kernel = std::move(k);
     // Configure border handler
     _border_handler.configure(input, _kernel->border_size(), BorderMode::CONSTANT, PixelValue());
     _shift_handler.configure(input);
     //Configure Activation Layer
     _is_activationlayer_enabled = act_info.enabled();
     if(_is_activationlayer_enabled)
     {
         _activationlayer_function.configure(output, nullptr, act_info);
     }
 }
References arm_compute::test::validation::act_info, ARM_COMPUTE_ERROR_ON, ARM_COMPUTE_UNUSED, GCActivationLayer::configure(), GCFillBorderKernel::configure(), GCTensorShiftKernel::configure(), arm_compute::CONSTANT, arm_compute::test::validation::conv_info, arm_compute::test::validation::dilation, and arm_compute::test::validation::weights.
run()
void run () final override virtual
Run the kernels contained in the function.
For NEON kernels:
Multi-threading is used for the kernels which are parallelisable.
By default std::thread::hardware_concurrency() threads are used.
Note
CPPScheduler::set_num_threads() can be used to manually set the number of threads
For OpenCL kernels:
All the kernels are enqueued on the queue associated with CLScheduler.
The queue is then flushed.
Note
The function will not block until the kernels are executed. It is the user's responsibility to wait.
Will call prepare() on first run if hasn't been done
Implements IFunction.
Definition at line 61 of file GCDepthwiseConvolutionLayer.cpp.
 {
     GCScheduler::get().dispatch(_shift_handler, false);
     GCScheduler::get().memory_barrier();
     GCScheduler::get().dispatch(_border_handler, false);
     GCScheduler::get().memory_barrier();
     GCScheduler::get().dispatch(*_kernel);
     // Run Activation Layer
     if(_is_activationlayer_enabled)
     {
         _activationlayer_function.run();
     }
 }
References GCScheduler::dispatch(), GCScheduler::get(), GCScheduler::memory_barrier(), and IGCSimpleFunction::run().
The documentation for this class was generated from the following files:
arm_compute/runtime/GLES_COMPUTE/functions/GCDepthwiseConvolutionLayer.h
src/runtime/GLES_COMPUTE/functions/GCDepthwiseConvolutionLayer.cpp