Compute Library: MultiImageInfo Class Reference
MultiImageInfo Class Reference
Store the multi-planar image's metadata.
#include <MultiImageInfo.h>
Public Member Functions
MultiImageInfo ()
Constructor.
void init (unsigned int width, unsigned int height, Format format)
Initialize the metadata structure with the given parameters.
Format format () const
Colour format of the image.
unsigned int width () const
Width in pixels.
unsigned int height () const
Height in pixels.
Detailed Description
Store the multi-planar image's metadata.
Definition at line 32 of file MultiImageInfo.h.
Constructor & Destructor Documentation
MultiImageInfo()
MultiImageInfo ()
Constructor.
Definition at line 28 of file MultiImageInfo.cpp.
     : _width(0), _height(0), _format(Format::UNKNOWN)
 {
 }
References arm_compute::UNKNOWN.
Member Function Documentation
format()
Format format () const
Colour format of the image.
Returns
Colour format of the image
Definition at line 40 of file MultiImageInfo.cpp.
 {
     return _format;
 }
Referenced by CLMultiImage::allocate(), MultiImage::allocate(), CLChannelExtractKernel::configure(), CLColorConvertKernel::configure(), NEColorConvertKernel::configure(), CLChannelCombineKernel::configure(), NEChannelExtractKernel::configure(), NEChannelCombineKernel::configure(), MultiImage::create_subimage(), MultiImageInfo::init(), CLChannelCombineKernel::run(), and CLColorConvertKernel::run().
height()
unsigned int height () const
Height in pixels.
Returns
The height in pixels
Definition at line 50 of file MultiImageInfo.cpp.
 {
     return _height;
 }
Referenced by MultiImageInfo::init().
init()
void init (unsigned int width, unsigned int height, Format format)
Initialize the metadata structure with the given parameters.
Parameters
[in] width Width of the image (in number of pixels)
[in] height Height of the image (in number of pixels)
[in] format Colour format of the image.
Definition at line 33 of file MultiImageInfo.cpp.
 {
     _format = format;
     _width  = width;
     _height = height;
 }
References MultiImageInfo::format(), MultiImageInfo::height(), and MultiImageInfo::width().
Referenced by MultiImage::create_subimage().
width()
unsigned int width () const
Width in pixels.
Returns
The width in pixels
Definition at line 45 of file MultiImageInfo.cpp.
 {
     return _width;
 }
Referenced by MultiImageInfo::init().
The documentation for this class was generated from the following files:
arm_compute/core/MultiImageInfo.h
src/core/MultiImageInfo.cpp