Compute Library: NEArithmeticOperationKernel Class Reference
NEArithmeticOperationKernel Class Reference
#include <NEElementwiseOperationKernel.h>
Public Member Functions
NEArithmeticOperationKernel ()=default
Default constructor.
void configure (ArithmeticOperation op, const ITensor *input1, const ITensor *input2, ITensor *output)
Static function to check if given info will lead to a valid configuration of NEArithmeticOperationKernel.
Public Member Functions inherited from NEElementwiseOperationKernel
const char * name () const override
Name of the kernel.
NEElementwiseOperationKernel ()
Default constructor.
NEElementwiseOperationKernel (const NEElementwiseOperationKernel &)=delete
Prevent instances of this class from being copied (As this class contains pointers)
NEElementwiseOperationKernel & operator= (const NEElementwiseOperationKernel &)=delete
Prevent instances of this class from being copied (As this class contains pointers)
NEElementwiseOperationKernel (NEElementwiseOperationKernel &&)=default
Allow instances of this class to be moved.
NEElementwiseOperationKernel & operator= (NEElementwiseOperationKernel &&)=default
Allow instances of this class to be moved.
~NEElementwiseOperationKernel ()=default
Default destructor.
void run (const Window &window, const ThreadInfo &info) override
Execute the kernel on the passed window.
Public Member Functions inherited from ICPPKernel
virtual ~ICPPKernel ()=default
Default destructor.
Public Member Functions inherited from IKernel
IKernel ()
Constructor.
virtual ~IKernel ()=default
Destructor.
virtual bool is_parallelisable () const
Indicates whether or not the kernel is parallelisable.
virtual BorderSize border_size () const
The size of the border for that kernel.
const Window & window () const
The maximum window the kernel can be executed on.
Static Public Member Functions
static Status validate (ArithmeticOperation op, const ITensorInfo *input1, const ITensorInfo *input2, const ITensorInfo *output)
Static function to check if given info will lead to a valid configuration of NEArithmeticOperationKernel.
Additional Inherited Members
Public Types inherited from NEElementwiseOperationKernel
using ElementwiseFunction = void(const ITensor *input1, const ITensor *input2, ITensor *output, const Window &window)
Common signature for all the specialised arithmetic functions.
Detailed Description
Definition at line 94 of file NEElementwiseOperationKernel.h.
Constructor & Destructor Documentation
NEArithmeticOperationKernel()
NEArithmeticOperationKernel () default
Default constructor.
Member Function Documentation
configure()
void configure (ArithmeticOperation op, const ITensor * input1, const ITensor * input2, ITensor * output)
Static function to check if given info will lead to a valid configuration of NEArithmeticOperationKernel.
Arithmetic operators (min, max, squared_diff)
Parameters
[in] op Arithmetic operation to be executed.
[in] input1 First tensor input. Data types supported: QASYMM8/S16/F16/S32/F32.
[in] input2 Second tensor input. Data types supported: Same as input1.
[in] output Output tensor. Data types supported: Same as input1.
Definition at line 822 of file NEElementwiseOperationKernel.cpp.
 {
     ARM_COMPUTE_ERROR_THROW_ON(validate_arguments(*input1->info(), *input2->info(), *output->info()));
     configure_common(input1, input2, output);
     switch(op)
     {
         case ArithmeticOperation::MAX:
             _function = configure_arithm_func<ArithmeticOperation::MAX>(input1, input2, output);
             break;
         case ArithmeticOperation::MIN:
             _function = configure_arithm_func<ArithmeticOperation::MIN>(input1, input2, output);
             break;
         case ArithmeticOperation::SQUARED_DIFF:
             _function = configure_arithm_func<ArithmeticOperation::SQUARED_DIFF>(input1, input2, output);
             break;
         default:
             ARM_COMPUTE_ERROR("NOT_SUPPORTED!");
     }
 }
References ARM_COMPUTE_ERROR, ARM_COMPUTE_ERROR_THROW_ON, ITensor::info(), arm_compute::MAX, arm_compute::MIN, and arm_compute::SQUARED_DIFF.
validate()
Status validate (ArithmeticOperation op, const ITensorInfo * input1, const ITensorInfo * input2, const ITensorInfo * output) static
Static function to check if given info will lead to a valid configuration of NEArithmeticOperationKernel.
Parameters
[in] op Arithmetic operation to be executed.
[in] input1 First tensor input info. Data types supported: QASYMM8/S16/F16/S32/F32.
[in] input2 Second tensor input info. Data types supported: Same as input1.
[in] output Output tensor info. Data types supported: Same as input1.
Returns
a Status
Definition at line 852 of file NEElementwiseOperationKernel.cpp.
 {
     ARM_COMPUTE_UNUSED(op);
     ARM_COMPUTE_RETURN_ERROR_ON_NULLPTR(input1, input2, output);
     ARM_COMPUTE_RETURN_ON_ERROR(validate_arguments(*input1, *input2, *output));
     return Status{};
 }
References ARM_COMPUTE_RETURN_ERROR_ON_NULLPTR, ARM_COMPUTE_RETURN_ON_ERROR, and ARM_COMPUTE_UNUSED.
Referenced by NEElementwiseMax::validate(), NEElementwiseMin::validate(), and NEElementwiseSquaredDiff::validate().
The documentation for this class was generated from the following files:
arm_compute/core/NEON/kernels/NEElementwiseOperationKernel.h
src/core/NEON/kernels/NEElementwiseOperationKernel.cpp