Compute Library: IArray< T > Class Template Reference
IArray< T > Class Template Reference abstract
Array of type T.
#include <IArray.h>
Public Member Functions
IArray ()
Default constructor.
IArray (size_t max_num_values)
Constructor: initializes an array which can contain up to max_num_points values.
size_t max_num_values () const
Maximum number of values which can be stored in this array.
virtual ~IArray ()=default
Default virtual destructor.
size_t num_values () const
Number of values currently stored in the array.
bool push_back (const T &val)
Append the passed argument to the end of the array if there is room.
void clear ()
Clear all the points from the array.
bool overflow () const
Did we lose some values because the array is too small?
virtual T * buffer () const =0
Pointer to the first element of the array.
virtual T & at (size_t index) const
Reference to the element of the array located at the given index.
void resize (size_t num)
Resizes the array to contain "num" elements.
Detailed Description
template<class T>
class arm_compute::IArray< T >
Array of type T.
Definition at line 40 of file IArray.h.
Constructor & Destructor Documentation
IArray() [1/2]
IArray () inline
Default constructor.
Definition at line 44 of file IArray.h.
         : _num_values(0), _max_size(0) {};
IArray() [2/2]
IArray (size_t max_num_values) inline
Constructor: initializes an array which can contain up to max_num_points values.
Parameters
[in] max_num_values Maximum number of values the array will be able to stored
Definition at line 50 of file IArray.h.
         : _num_values(0), _max_size(max_num_values)
     {
     }
~IArray()
virtual ~IArray () virtual default
Default virtual destructor.
Member Function Documentation
at()
virtual T& at (size_t index) const inline virtual
Reference to the element of the array located at the given index.
Parameters
[in] index Index of the element
Returns
A reference to the element of the array located at the given index.
Definition at line 117 of file IArray.h.
     {
         ARM_COMPUTE_ERROR_ON(buffer() == nullptr);
         ARM_COMPUTE_ERROR_ON(index >= max_num_values());
         return buffer()[index];
     }
Referenced by CLHOGMultiDetection::configure(), NEHOGMultiDetection::configure(), IArray< NELKInternalKeypoint >::push_back(), and CPPDetectionWindowNonMaximaSuppressionKernel::run().
buffer()
virtual T* buffer () const pure virtual
Pointer to the first element of the array.
Other elements of the array can be accessed using buffer()[idx] for 0 <= idx < num_poins().
Returns
A pointer to the first element of the array
Implemented in ICLArray< T >, Array< T >, and Array< NELKInternalKeypoint >.
Referenced by IArray< NELKInternalKeypoint >::at(), and CPPDetectionWindowNonMaximaSuppressionKernel::run().
clear()
void clear () inline
Clear all the points from the array.
Definition at line 91 of file IArray.h.
     {
         _num_values = 0;
     }
Referenced by CLHOGMultiDetection::run(), and NEHOGMultiDetection::run().
max_num_values()
size_t max_num_values () const inline
Maximum number of values which can be stored in this array.
Returns
Maximum number of values
Definition at line 58 of file IArray.h.
     {
         return _max_size;
     }
Referenced by IArray< NELKInternalKeypoint >::at(), NEHOGDetectorKernel::configure(), CLHOGDetectorKernel::configure(), CLMinMaxLocationKernel::configure(), CLCopyToArrayKernel::configure(), IArray< NELKInternalKeypoint >::overflow(), IArray< NELKInternalKeypoint >::push_back(), IArray< NELKInternalKeypoint >::resize(), CLMinMaxLocation::run(), and CLFastCorners::run().
num_values()
size_t num_values () const inline
Number of values currently stored in the array.
Returns
Number of values currently stored in the array or max_num_values + 1 if the array is overflowed.
Definition at line 68 of file IArray.h.
     {
         return _num_values;
     }
Referenced by NEOpticalFlow::configure(), CLHOGMultiDetection::configure(), NEHOGMultiDetection::configure(), CLLKTrackerInitKernel::configure(), CLOpticalFlow::configure(), CLLKTrackerFinalizeKernel::configure(), CLLKTrackerStage0Kernel::configure(), CLLKTrackerStage1Kernel::configure(), CPPDetectionWindowNonMaximaSuppressionKernel::run(), CLHOGDetector::run(), and NEHOGDetectorKernel::run().
overflow()
bool overflow () const inline
Did we lose some values because the array is too small?
Returns
True if we tried to add a value using push_back() but there wasn't any room left to store it. False if all the values were successfully added to the array.
Definition at line 100 of file IArray.h.
     {
         return _num_values > max_num_values();
     }
push_back()
bool push_back (const T & val) inline
Append the passed argument to the end of the array if there is room.
Parameters
[in] val Value to add to the array.
Returns
True if the point was successfully added to the array. False if the array is full and the point couldn't be added.
Definition at line 78 of file IArray.h.
     {
         ARM_COMPUTE_ERROR_ON(0 == _max_size);
         if(_num_values >= max_num_values())
         {
             _num_values = max_num_values() + 1;
             return false;
         }
         at(_num_values) = val;
         _num_values++;
         return true;
     }
Referenced by CPPSortEuclideanDistanceKernel::run(), and NEHOGDetectorKernel::run().
resize()
void resize (size_t num) inline
Resizes the array to contain "num" elements.
If "num" is smaller than the maximum array size, the content is reduced to its first "num" elements, "num" elements can't be bigger than the maximum number of values which can be stored in this array.
Parameters
[in] num The new array size in number of elements
Definition at line 128 of file IArray.h.
     {
         ARM_COMPUTE_ERROR_ON(num > max_num_values());
         _num_values = num;
     };
Referenced by NEOpticalFlow::configure(), CLOpticalFlow::configure(), CPPDetectionWindowNonMaximaSuppressionKernel::run(), CLHOGDetector::run(), CLMinMaxLocation::run(), and CLFastCorners::run().
The documentation for this class was generated from the following file:
arm_compute/core/IArray.h