Compute Library: FusedConvolutionBatchNormalizationNode Class Reference
FusedConvolutionBatchNormalizationNode Class Reference final
Batch Normalization node.
#include <FusedConvolutionBatchNormalizationNode.h>
Public Member Functions
FusedConvolutionBatchNormalizationNode (float epsilon, PadStrideInfo info, unsigned int num_groups=1, ConvolutionMethod method=ConvolutionMethod::Default, FastMathHint fast_math_hint=FastMathHint::Disabled, QuantizationInfo out_quant_info=QuantizationInfo(), ActivationLayerInfo fused_activation=ActivationLayerInfo())
Constructor.
float epsilon () const
Epsilon parameter accessor.
ActivationLayerInfo fused_activation () const
Returns fused activation.
void set_fused_activation (ActivationLayerInfo fused_activation)
Sets fused activation.
void set_convolution_method (ConvolutionMethod method)
Sets the convolution layer method to use.
unsigned int num_groups () const
Number of groups in convolution accessor.
ConvolutionMethod convolution_method () const
Convolution layer method accessor.
void set_fast_math_hint (FastMathHint hint)
Sets the fast math fast hint.
FastMathHint fast_math_hint () const
Fast math hint accessor.
PadStrideInfo convolution_info () const
Convolution metadata accessor.
NodeType type () const override
Returns node's type.
bool forward_descriptors () override
Forwards descriptor information to outputs if possible.
TensorDescriptor configure_output (size_t idx) const override
Calculates output configuration.
void accept (INodeVisitor &v) override
Accepts a node visitor.
Public Member Functions inherited from INode
INode ()
Constructor.
virtual ~INode ()=default
Destructor.
INode (const INode &)=delete
Prevent instances of this class from being copied (As this class contains pointers)
INode & operator= (const INode &)=delete
Prevent instances of this class from being copy assigned (As this class contains pointers)
INode (INode &&)=default
Allow instances of this class to be moved.
INode & operator= (INode &&)=default
Allow instances of this class to be move assigned.
virtual Status validate () const
Validate node.
std::string name () const
Returns node's name.
NodeID id () const
Returns node's ID.
const Graph * graph () const
Returns node's Graph.
Graph * graph ()
Returns node's Graph.
void set_graph (Graph *g)
Sets the graph that this node is registered to.
void set_id (NodeID id)
Sets the node id.
void set_common_node_parameters (NodeParams common_params)
Sets common node parameters.
void set_requested_target (Target target)
Sets target preference.
void set_assigned_target (Target target)
Sets the final execution target.
void set_output_tensor (TensorID tid, size_t idx)
Sets the output tensor of at a given index.
const std::vector< TensorID > & inputs () const
Returns inputs of the node.
const std::vector< TensorID > & outputs () const
Returns outputs of the node.
const std::vector< EdgeID > & input_edges () const
Returns input edge set.
const std::set< EdgeID > & output_edges () const
Returns output edge set.
TensorID input_id (size_t idx) const
Returns the tensor ID of a given input of the node.
TensorID output_id (size_t idx) const
Returns the tensor ID of a given output of the node.
Tensor * input (size_t idx) const
Returns the tensor of a given input of the node.
Tensor * output (size_t idx) const
Returns the tensor of a given output of the node.
EdgeID input_edge_id (size_t idx) const
Returns the edge ID of a given input of the node.
Edge * input_edge (size_t idx) const
Returns the edge of a given input of the node.
size_t num_inputs () const
Returns number of inputs of the node.
size_t num_outputs () const
Returns number of outputs of the node.
NodeParams common_node_params () const
Returns common node parameters.
Target requested_target () const
Returns requested target for this node.
Target assigned_target () const
Returns assigned target for this node.
Static Public Member Functions
static TensorDescriptor compute_output_descriptor (const TensorDescriptor &input_descriptor, const TensorDescriptor &weights_descriptor, const PadStrideInfo &info)
Computes convolution output descriptor.
Static Public Attributes
static constexpr NodeType node_type = NodeType::FusedConvolutionBatchNormalizationLayer
Detailed Description
Batch Normalization node.
Definition at line 34 of file FusedConvolutionBatchNormalizationNode.h.
Constructor & Destructor Documentation
FusedConvolutionBatchNormalizationNode()
FusedConvolutionBatchNormalizationNode (float epsilon, PadStrideInfo info, unsigned int num_groups = 1, ConvolutionMethod method = ConvolutionMethod::Default, FastMathHint fast_math_hint = FastMathHint::Disabled, QuantizationInfo out_quant_info = QuantizationInfo(), ActivationLayerInfo fused_activation = ActivationLayerInfo())
Constructor.
Parameters
[in] epsilon Epsilon parameter.
[in] info Convolution layer attributes.
[in] num_groups (Optional) Number of groups (Defaults to 1)
[in] method (Optional) Convolution method to use
[in] fast_math_hint (Optional) Fast math hint
[in] out_quant_info (Optional) Output quantization info
[in] fused_activation (Optional) Fused activation layer. Disabled if not specified
Definition at line 35 of file FusedConvolutionBatchNormalizationNode.cpp.
     : _epsilon(epsilon), _info(std::move(info)), _num_groups(num_groups), _method(method), _fast_math_hint(fast_math_hint), _out_quant_info(out_quant_info), _fused_activation(fused_activation)
 {
     _input_edges.resize(7, EmptyEdgeID);
     _outputs.resize(1, NullTensorID);
 }
References arm_compute::graph::EmptyEdgeID, and arm_compute::graph::NullTensorID.
Member Function Documentation
accept()
void accept (INodeVisitor & v) override virtual
Accepts a node visitor.
Parameters
[in] v Visitor to accept
Implements INode.
Definition at line 148 of file FusedConvolutionBatchNormalizationNode.cpp.
 {
     v.visit(*this);
 }
References INodeVisitor::visit().
compute_output_descriptor()
TensorDescriptor compute_output_descriptor (const TensorDescriptor & input_descriptor, const TensorDescriptor & weights_descriptor, const PadStrideInfo & info) static
Computes convolution output descriptor.
Parameters
[in] input_descriptor Input descriptor
[in] weights_descriptor Weights descriptor
[in] info Convolution operation attributes
Returns
Output descriptor
Definition at line 91 of file FusedConvolutionBatchNormalizationNode.cpp.
 {
     unsigned int output_width  = 0;
     unsigned int output_height = 0;
     const unsigned int input_width   = get_dimension_size(input_descriptor, DataLayoutDimension::WIDTH);
     const unsigned int input_height  = get_dimension_size(input_descriptor, DataLayoutDimension::HEIGHT);
     const unsigned int kernel_width  = get_dimension_size(weights_descriptor, DataLayoutDimension::WIDTH);
     const unsigned int kernel_height = get_dimension_size(weights_descriptor, DataLayoutDimension::HEIGHT);
     std::tie(output_width, output_height) = scaled_dimensions(input_width, input_height, kernel_width, kernel_height, info);
     const DataLayout data_layout       = input_descriptor.layout;
     TensorDescriptor output_descriptor = input_descriptor;
     output_descriptor.shape.set(get_dimension_idx(data_layout, DataLayoutDimension::WIDTH), output_width);
     output_descriptor.shape.set(get_dimension_idx(data_layout, DataLayoutDimension::HEIGHT), output_height);
     output_descriptor.shape.set(get_dimension_idx(data_layout, DataLayoutDimension::CHANNEL), weights_descriptor.shape[3]);
     return output_descriptor;
 }
References arm_compute::CHANNEL, arm_compute::graph::get_dimension_idx(), arm_compute::graph::get_dimension_size(), arm_compute::HEIGHT, arm_compute::test::validation::info, TensorDescriptor::layout, arm_compute::scaled_dimensions(), TensorShape::set(), TensorDescriptor::shape, and arm_compute::WIDTH.
Referenced by FusedConvolutionBatchNormalizationNode::configure_output().
configure_output()
TensorDescriptor configure_output (size_t idx) const override virtual
Calculates output configuration.
Parameters
[in] idx Output index to configure
Returns
Output descriptor configuration
Implements INode.
Definition at line 126 of file FusedConvolutionBatchNormalizationNode.cpp.
 {
     ARM_COMPUTE_UNUSED(idx);
     const Tensor *src     = input(0);
     const Tensor *weights = input(1);
     ARM_COMPUTE_ERROR_ON(src == nullptr || weights == nullptr);
     TensorDescriptor output_info = compute_output_descriptor(src->desc(), weights->desc(), _info);
     if(!_out_quant_info.empty())
     {
         output_info.quant_info = _out_quant_info;
     }
     return output_info;
 }
References ARM_COMPUTE_ERROR_ON, ARM_COMPUTE_UNUSED, FusedConvolutionBatchNormalizationNode::compute_output_descriptor(), QuantizationInfo::empty(), INode::input(), arm_compute::test::validation::output_info, arm_compute::test::validation::src, and arm_compute::test::validation::weights.
Referenced by FusedConvolutionBatchNormalizationNode::forward_descriptors().
convolution_info()
PadStrideInfo convolution_info () const
Convolution metadata accessor.
Returns
Convolution information
Definition at line 71 of file FusedConvolutionBatchNormalizationNode.cpp.
 {
     return _info;
 }
Referenced by arm_compute::graph::backends::detail::create_fused_convolution_batch_normalization_layer().
convolution_method()
ConvolutionMethod convolution_method () const
Convolution layer method accessor.
Note
This is an indication on which convolution layer implementation to use, if it fails to be created the library's heuristic approach will be used
Returns
Convolution layer method to be used by the node
Definition at line 56 of file FusedConvolutionBatchNormalizationNode.cpp.
 {
     return _method;
 }
epsilon()
float epsilon () const
Epsilon parameter accessor.
Returns
Epsilon parameter
Definition at line 51 of file FusedConvolutionBatchNormalizationNode.cpp.
 {
     return _epsilon;
 }
Referenced by arm_compute::graph::backends::detail::create_fused_convolution_batch_normalization_layer().
fast_math_hint()
FastMathHint fast_math_hint () const
Fast math hint accessor.
Returns
Fast math hint to be used by the node
Definition at line 66 of file FusedConvolutionBatchNormalizationNode.cpp.
 {
     return _fast_math_hint;
 }
Referenced by arm_compute::graph::backends::detail::create_fused_convolution_batch_normalization_layer().
forward_descriptors()
bool forward_descriptors () override virtual
Forwards descriptor information to outputs if possible.
Returns
True if descriptor information could be forwarded otherwise false
Implements INode.
Definition at line 114 of file FusedConvolutionBatchNormalizationNode.cpp.
 {
     if((input_id(0) != NullTensorID) && (input_id(1) != NullTensorID) && (output_id(0) != NullTensorID))
     {
         Tensor *dst = output(0);
         ARM_COMPUTE_ERROR_ON(dst == nullptr);
         dst->desc() = configure_output(0);
         return true;
     }
     return false;
 }
References ARM_COMPUTE_ERROR_ON, FusedConvolutionBatchNormalizationNode::configure_output(), arm_compute::test::validation::dst, INode::input_id(), arm_compute::graph::NullTensorID, INode::output(), and INode::output_id().
fused_activation()
ActivationLayerInfo fused_activation () const
Returns fused activation.
Returns
Fused activation
Definition at line 81 of file FusedConvolutionBatchNormalizationNode.cpp.
 {
     return _fused_activation;
 }
Referenced by arm_compute::graph::backends::detail::create_fused_convolution_batch_normalization_layer(), and FusedConvolutionBatchNormalizationNode::set_fused_activation().
num_groups()
unsigned int num_groups () const
Number of groups in convolution accessor.
Returns
Number of groups in convolution
Definition at line 76 of file FusedConvolutionBatchNormalizationNode.cpp.
 {
     return _num_groups;
 }
Referenced by arm_compute::graph::backends::detail::create_fused_convolution_batch_normalization_layer().
set_convolution_method()
void set_convolution_method (ConvolutionMethod method)
Sets the convolution layer method to use.
Parameters
[in] method Method to use for convolution
Definition at line 46 of file FusedConvolutionBatchNormalizationNode.cpp.
 {
     _method = method;
 }
set_fast_math_hint()
void set_fast_math_hint (FastMathHint hint)
Sets the fast math fast hint.
Parameters
[in] hint Hint to use for convolution
Definition at line 61 of file FusedConvolutionBatchNormalizationNode.cpp.
 {
     _fast_math_hint = hint;
 }
set_fused_activation()
void set_fused_activation (ActivationLayerInfo fused_activation)
Sets fused activation.
Parameters
[in] fused_activation Fused activation to set
Definition at line 86 of file FusedConvolutionBatchNormalizationNode.cpp.
 {
     _fused_activation = fused_activation;
 }
References FusedConvolutionBatchNormalizationNode::fused_activation().
type()
NodeType type () const override virtual
Returns node's type.
Returns
Node's type
Implements INode.
Definition at line 143 of file FusedConvolutionBatchNormalizationNode.cpp.
 {
     return FusedConvolutionBatchNormalizationNode::node_type;
 }
References FusedConvolutionBatchNormalizationNode::node_type.
Field Documentation
node_type
constexpr NodeType node_type = NodeType::FusedConvolutionBatchNormalizationLayer static
Definition at line 129 of file FusedConvolutionBatchNormalizationNode.h.
Referenced by FusedConvolutionBatchNormalizationNode::type().
The documentation for this class was generated from the following files:
arm_compute/graph/nodes/FusedConvolutionBatchNormalizationNode.h
src/graph/nodes/FusedConvolutionBatchNormalizationNode.cpp