Compute Library: MemoryGroupBase< TensorType > Class Template Reference
MemoryGroupBase< TensorType > Class Template Reference
Memory group.
#include <CLTensorAllocator.h>
Public Member Functions
MemoryGroupBase (std::shared_ptr< IMemoryManager > memory_manager=nullptr)
Default Constructor.
~MemoryGroupBase ()=default
Default destructor.
MemoryGroupBase (const MemoryGroupBase &)=delete
Prevent instances of this class from being copied (As this class contains pointers)
MemoryGroupBase & operator= (const MemoryGroupBase &)=delete
Prevent instances of this class from being copy assigned (As this class contains pointers)
MemoryGroupBase (MemoryGroupBase &&)=default
Allow instances of this class to be moved.
MemoryGroupBase & operator= (MemoryGroupBase &&)=default
Allow instances of this class to be moved.
void manage (TensorType *obj)
Sets a object to be managed by the given memory group.
void finalize_memory (TensorType *obj, IMemory &obj_memory, size_t size, size_t alignment=0)
Finalizes memory for a given object.
void acquire () override
Acquires backing memory for the whole group.
void release () override
Releases backing memory of the whole group.
MemoryMappings & mappings () override
Gets the memory mapping of the group.
Public Member Functions inherited from IMemoryGroup
virtual ~IMemoryGroup ()=default
Default virtual destructor.
Detailed Description
template<typename TensorType>
class arm_compute::MemoryGroupBase< TensorType >
Memory group.
Definition at line 38 of file CLTensorAllocator.h.
Constructor & Destructor Documentation
MemoryGroupBase() [1/3]
MemoryGroupBase (std::shared_ptr< IMemoryManager > memory_manager = nullptr) inline
Default Constructor.
Definition at line 92 of file MemoryGroupBase.h.
     : _memory_manager(std::move(memory_manager)), _pool(nullptr), _mappings()
 {
     if(_memory_manager)
     {
         ARM_COMPUTE_ERROR_ON(!_memory_manager->lifetime_manager());
     }
 }
~MemoryGroupBase()
~MemoryGroupBase () default
Default destructor.
MemoryGroupBase() [2/3]
MemoryGroupBase (const MemoryGroupBase< TensorType > &) delete
Prevent instances of this class from being copied (As this class contains pointers)
MemoryGroupBase() [3/3]
MemoryGroupBase (MemoryGroupBase< TensorType > &&) default
Allow instances of this class to be moved.
Member Function Documentation
acquire()
void acquire () inline override virtual
Acquires backing memory for the whole group.
Implements IMemoryGroup.
Definition at line 134 of file MemoryGroupBase.h.
 {
     if(!_mappings.empty())
     {
         ARM_COMPUTE_ERROR_ON(!_memory_manager->pool_manager());
         _pool = _memory_manager->pool_manager()->lock_pool();
         _pool->acquire(_mappings);
     }
 }
Referenced by NEFFT2D::run().
finalize_memory()
void finalize_memory (TensorType * obj, IMemory & obj_memory, size_t size, size_t alignment = 0) inline
Finalizes memory for a given object.
Note
Manager must not be finalized
Parameters
[in,out] obj Object to request memory for
[in,out] obj_memory Object's memory handling interface which can be used to alter the underlying memory that is used by the object.
[in] size Size of memory to allocate
[in] alignment (Optional) Alignment to use
Definition at line 120 of file MemoryGroupBase.h.
 {
     // TODO (geopin01) : Check size (track size in MemoryMappings)
     // Check if existing mapping is valid
     ARM_COMPUTE_ERROR_ON(!_mappings.empty() && (_mappings.find(&obj_memory) == std::end(_mappings)));
     if(_memory_manager && _mappings.empty())
     {
         ARM_COMPUTE_ERROR_ON(!_memory_manager->lifetime_manager());
         _memory_manager->lifetime_manager()->end_lifetime(obj, obj_memory, size, alignment);
     }
 }
Referenced by TensorAllocator::allocate(), CLTensorAllocator::allocate(), and GCTensorAllocator::allocate().
manage()
void manage (TensorType * obj) inline
Sets a object to be managed by the given memory group.
Note
Manager must not be finalized
Parameters
[in] obj Object to be managed
Definition at line 102 of file MemoryGroupBase.h.
 {
     if(_memory_manager && _mappings.empty())
     {
         ARM_COMPUTE_ERROR_ON(!_memory_manager->lifetime_manager());
         // Defer registration to the first managed object
         _memory_manager->lifetime_manager()->register_group(this);
         // Associate this memory group with the tensor
         associate_memory_group(obj);
         // Start object lifetime
         _memory_manager->lifetime_manager()->start_lifetime(obj);
     }
 }
Referenced by CLReduceMean::configure(), NEGEMMLowpAssemblyMatrixMultiplyCore::configure(), CLRNNLayer::configure(), NEReduceMean::configure(), NEFFT2D::configure(), CLFFT2D::configure(), NEL2NormalizeLayer::configure(), CLFFT1D::configure(), NEFFT1D::configure(), CLMeanStdDev::configure(), NEHOGDescriptor::configure(), GCNormalizationLayer::configure(), CLL2NormalizeLayer::configure(), CLReductionOperation::configure(), CLHOGDescriptor::configure(), GCSoftmaxLayer::configure(), NEGaussian5x5::configure(), NEHOGGradient::configure(), NENormalizationLayer::configure(), CLHOGGradient::configure(), CLGaussian5x5::configure(), NERNNLayer::configure(), CLSoftmaxLayer::configure(), NESobel5x5::configure(), NESobel7x7::configure(), NEFastCorners::configure(), CLSobel5x5::configure(), CLSobel7x7::configure(), NEDepthwiseConvolutionAssemblyDispatch::configure(), CLCannyEdge::configure(), CLFastCorners::configure(), NESoftmaxLayer::configure(), NEWinogradConvolutionLayer::configure(), CLLocallyConnectedLayer::configure(), NELocallyConnectedLayer::configure(), NEGEMM::configure(), CLWinogradConvolutionLayer::configure(), NECannyEdge::configure(), GCGEMM::configure(), CLDepthwiseConvolutionLayer3x3::configure(), NEOpticalFlow::configure(), CLHarrisCorners::configure(), NEHarrisCorners::configure(), NELSTMLayer::configure(), CLGEMMLowpMatrixMultiplyCore::configure(), CLHOGMultiDetection::configure(), NEHOGMultiDetection::configure(), NEGEMMLowpMatrixMultiplyCore::configure(), NEFFTConvolutionLayer::configure(), CLFFTConvolutionLayer::configure(), CLGenerateProposalsLayer::configure(), CLOpticalFlow::configure(), CLLSTMLayer::configure(), CLDirectDeconvolutionLayer::configure(), CLGEMMDeconvolutionLayer::configure(), NEDeconvolutionLayer::configure(), GCConvolutionLayer::configure(), NEGEMMInterleavedWrapper::configure(), NEGEMMConvolutionLayer::configure(), and CLGEMMConvolutionLayer::configure().
mappings()
MemoryMappings & mappings () inline override virtual
Gets the memory mapping of the group.
Implements IMemoryGroup.
Definition at line 158 of file MemoryGroupBase.h.
 {
     return _mappings;
 }
operator=() [1/2]
MemoryGroupBase& operator= (const MemoryGroupBase< TensorType > &) delete
Prevent instances of this class from being copy assigned (As this class contains pointers)
operator=() [2/2]
MemoryGroupBase& operator= (MemoryGroupBase< TensorType > &&) default
Allow instances of this class to be moved.
release()
void release () inline override virtual
Releases backing memory of the whole group.
Implements IMemoryGroup.
Definition at line 145 of file MemoryGroupBase.h.
 {
     if(_pool != nullptr)
     {
         ARM_COMPUTE_ERROR_ON(!_memory_manager->pool_manager());
         ARM_COMPUTE_ERROR_ON(_mappings.empty());
         _pool->release(_mappings);
         _memory_manager->pool_manager()->unlock_pool(_pool);
         _pool = nullptr;
     }
 }
Referenced by NEFFT2D::run().
The documentation for this class was generated from the following files:
arm_compute/runtime/CL/CLTensorAllocator.h
arm_compute/runtime/MemoryGroupBase.h