Compute Library: CLLKTrackerStage0Kernel Class Reference
CLLKTrackerStage0Kernel Class Reference
Interface to run the first stage of LKTracker, where A11, A12, A22, min_eig, ival, ixval and iyval are computed.
#include <CLLKTrackerKernel.h>
Public Member Functions
CLLKTrackerStage0Kernel ()
Default constructor.
CLLKTrackerStage0Kernel (const CLLKTrackerStage0Kernel &)=delete
Prevent instances of this class from being copied (As this class contains pointers)
CLLKTrackerStage0Kernel & operator= (const CLLKTrackerStage0Kernel &)=delete
Prevent instances of this class from being copied (As this class contains pointers)
CLLKTrackerStage0Kernel (CLLKTrackerStage0Kernel &&)=default
Allow instances of this class to be moved.
CLLKTrackerStage0Kernel & operator= (CLLKTrackerStage0Kernel &&)=default
Allow instances of this class to be moved.
void configure (const ICLTensor *old_input, const ICLTensor *old_scharr_gx, const ICLTensor *old_scharr_gy, ICLLKInternalKeypointArray *old_points_internal, ICLLKInternalKeypointArray *new_points_internal, ICLCoefficientTableArray *coeff_table, ICLOldValArray *old_ival, size_t window_dimension, size_t level)
Initialise the kernel input and output.
void run (const Window &window, cl::CommandQueue &queue) override
Enqueue the OpenCL kernel to process the given window on the passed OpenCL command queue.
Public Member Functions inherited from ICLKernel
ICLKernel ()
Constructor.
cl::Kernel & kernel ()
Returns a reference to the OpenCL kernel of this object.
template<typename T >
void add_1D_array_argument (unsigned int &idx, const ICLArray< T > *array, const Strides &strides, unsigned int num_dimensions, const Window &window)
Add the passed 1D array's parameters to the object's kernel's arguments starting from the index idx.
void add_1D_tensor_argument (unsigned int &idx, const ICLTensor *tensor, const Window &window)
Add the passed 1D tensor's parameters to the object's kernel's arguments starting from the index idx.
void add_2D_tensor_argument (unsigned int &idx, const ICLTensor *tensor, const Window &window)
Add the passed 2D tensor's parameters to the object's kernel's arguments starting from the index idx.
void add_3D_tensor_argument (unsigned int &idx, const ICLTensor *tensor, const Window &window)
Add the passed 3D tensor's parameters to the object's kernel's arguments starting from the index idx.
void add_4D_tensor_argument (unsigned int &idx, const ICLTensor *tensor, const Window &window)
Add the passed 4D tensor's parameters to the object's kernel's arguments starting from the index idx.
template<typename T >
void add_argument (unsigned int &idx, T value)
Add the passed parameters to the object's kernel's arguments starting from the index idx.
void set_lws_hint (const cl::NDRange &lws_hint)
Set the Local-Workgroup-Size hint.
cl::NDRange lws_hint () const
Return the Local-Workgroup-Size hint.
const std::string & config_id () const
Get the configuration ID.
void set_target (GPUTarget target)
Set the targeted GPU architecture.
void set_target (cl::Device &device)
Set the targeted GPU architecture according to the CL device.
GPUTarget get_target () const
Get the targeted GPU architecture.
size_t get_max_workgroup_size ()
Get the maximum workgroup size for the device the CLKernelLibrary uses.
template<typename T , unsigned int dimension_size>
void add_array_argument (unsigned &idx, const ICLArray< T > *array, const Strides &strides, unsigned int num_dimensions, const Window &window)
Add the passed array's parameters to the object's kernel's arguments starting from the index idx.
template<unsigned int dimension_size>
void add_tensor_argument (unsigned &idx, const ICLTensor *tensor, const Window &window)
Public Member Functions inherited from IKernel
IKernel ()
Constructor.
virtual ~IKernel ()=default
Destructor.
virtual bool is_parallelisable () const
Indicates whether or not the kernel is parallelisable.
virtual BorderSize border_size () const
The size of the border for that kernel.
const Window & window () const
The maximum window the kernel can be executed on.
Additional Inherited Members
Static Public Member Functions inherited from ICLKernel
static constexpr unsigned int num_arguments_per_1D_array ()
Returns the number of arguments enqueued per 1D array object.
static constexpr unsigned int num_arguments_per_1D_tensor ()
Returns the number of arguments enqueued per 1D tensor object.
static constexpr unsigned int num_arguments_per_2D_tensor ()
Returns the number of arguments enqueued per 2D tensor object.
static constexpr unsigned int num_arguments_per_3D_tensor ()
Returns the number of arguments enqueued per 3D tensor object.
static constexpr unsigned int num_arguments_per_4D_tensor ()
Returns the number of arguments enqueued per 4D tensor object.
static cl::NDRange gws_from_window (const Window &window)
Get the global work size given an execution window.
Detailed Description
Interface to run the first stage of LKTracker, where A11, A12, A22, min_eig, ival, ixval and iyval are computed.
Definition at line 111 of file CLLKTrackerKernel.h.
Constructor & Destructor Documentation
CLLKTrackerStage0Kernel() [1/3]
CLLKTrackerStage0Kernel ()
Default constructor.
Definition at line 118 of file CLLKTrackerKernel.cpp.
     : _old_input(nullptr), _old_scharr_gx(nullptr), _old_scharr_gy(nullptr)
 {
 }
CLLKTrackerStage0Kernel() [2/3]
CLLKTrackerStage0Kernel (const CLLKTrackerStage0Kernel &) delete
Prevent instances of this class from being copied (As this class contains pointers)
CLLKTrackerStage0Kernel() [3/3]
CLLKTrackerStage0Kernel (CLLKTrackerStage0Kernel &&) default
Allow instances of this class to be moved.
Member Function Documentation
configure()
void configure (const ICLTensor * old_input, const ICLTensor * old_scharr_gx, const ICLTensor * old_scharr_gy, ICLLKInternalKeypointArray * old_points_internal, ICLLKInternalKeypointArray * new_points_internal, ICLCoefficientTableArray * coeff_table, ICLOldValArray * old_ival, size_t window_dimension, size_t level)
Initialise the kernel input and output.
Parameters
[in] old_input Pointer to the input old tensor. Data types supported: U8
[in] old_scharr_gx Pointer to the input scharr X tensor. Data types supported: S16
[in] old_scharr_gy Pointer to the input scharr Y tensor. Data types supported: S16
[in] old_points_internal Pointer to the array of CLLKInternalKeypoint old points
[in,out] new_points_internal Pointer to the array of CLLKInternalKeypoint new points
[out] coeff_table Pointer to the array holding the Spatial Gradient coefficients
[out] old_ival Pointer to the array holding internal values
[in] window_dimension The size of the window on which to perform the algorithm
[in] level The pyramid level
Definition at line 123 of file CLLKTrackerKernel.cpp.
 {
     ARM_COMPUTE_ERROR_ON_DATA_TYPE_CHANNEL_NOT_IN(old_input, 1, DataType::U8);
     ARM_COMPUTE_ERROR_ON_DATA_TYPE_CHANNEL_NOT_IN(old_scharr_gx, 1, DataType::S16);
     ARM_COMPUTE_ERROR_ON_DATA_TYPE_CHANNEL_NOT_IN(old_scharr_gy, 1, DataType::S16);
     ARM_COMPUTE_ERROR_ON(old_points_internal == nullptr);
     ARM_COMPUTE_ERROR_ON(new_points_internal == nullptr);
     ARM_COMPUTE_ERROR_ON(coeff_table == nullptr);
     ARM_COMPUTE_ERROR_ON(old_ival == nullptr);
     _old_input     = old_input;
     _old_scharr_gx = old_scharr_gx;
     _old_scharr_gy = old_scharr_gy;
     // Configure kernel window
     Window window;
     window.set(Window::DimX, Window::Dimension(0, new_points_internal->num_values(), 1));
     window.set(Window::DimY, Window::Dimension(0, 1, 1));
     const ValidRegion valid_region = intersect_valid_regions(
                                          old_input->info()->valid_region(),
                                          old_scharr_gx->info()->valid_region(),
                                          old_scharr_gy->info()->valid_region());
     update_window_and_padding(window,
                               AccessWindowStatic(old_input->info(), valid_region.start(0), valid_region.start(1),
                                                  valid_region.end(0), valid_region.end(1)),
                               AccessWindowStatic(old_scharr_gx->info(), valid_region.start(0), valid_region.start(1),
                                                  valid_region.end(0), valid_region.end(1)),
                               AccessWindowStatic(old_scharr_gy->info(), valid_region.start(0), valid_region.start(1),
                                                  valid_region.end(0), valid_region.end(1)));
     ICLKernel::configure_internal(window);
     // Initialize required variables
     const int       level0              = (level == 0) ? 1 : 0;
     const int       window_size         = window_dimension;
     const int       window_size_squared = window_dimension * window_dimension;
     const int       window_size_half    = window_dimension / 2;
     const float     eig_const           = 1.0f / (2.0f * window_size_squared);
     const cl_float3 border_limits =
     {
         {
             // -1 because we load 2 values at once for bilinear interpolation
             static_cast<cl_float>(valid_region.end(0) - window_size - 1),
             static_cast<cl_float>(valid_region.end(1) - window_size - 1),
             static_cast<cl_float>(valid_region.start(0))
         }
     };
     // Create kernel
     _kernel = static_cast<cl::Kernel>(CLKernelLibrary::get().create_kernel("lktracker_stage0"));
     // Set arguments
     unsigned int idx = 3 * num_arguments_per_2D_tensor();
     _kernel.setArg(idx++, old_points_internal->cl_buffer());
     _kernel.setArg(idx++, new_points_internal->cl_buffer());
     _kernel.setArg(idx++, coeff_table->cl_buffer());
     _kernel.setArg(idx++, old_ival->cl_buffer());
     _kernel.setArg<cl_int>(idx++, window_size);
     _kernel.setArg<cl_int>(idx++, window_size_squared);
     _kernel.setArg<cl_int>(idx++, window_size_half);
     _kernel.setArg<cl_float3>(idx++, border_limits);
     _kernel.setArg<cl_float>(idx++, eig_const);
     _kernel.setArg<cl_int>(idx++, level0);
 }
References ARM_COMPUTE_ERROR_ON, ARM_COMPUTE_ERROR_ON_DATA_TYPE_CHANNEL_NOT_IN, ICLArray< T >::cl_buffer(), arm_compute::create_kernel(), Window::DimX, Window::DimY, ValidRegion::end(), CLKernelLibrary::get(), ITensor::info(), arm_compute::intersect_valid_regions(), ICLKernel::num_arguments_per_2D_tensor(), IArray< T >::num_values(), arm_compute::S16, Window::set(), ValidRegion::start(), arm_compute::U8, arm_compute::update_window_and_padding(), arm_compute::test::validation::valid_region, ITensorInfo::valid_region(), and IKernel::window().
operator=() [1/2]
CLLKTrackerStage0Kernel& operator= (const CLLKTrackerStage0Kernel &) delete
Prevent instances of this class from being copied (As this class contains pointers)
operator=() [2/2]
CLLKTrackerStage0Kernel& operator= (CLLKTrackerStage0Kernel &&) default
Allow instances of this class to be moved.
run()
void run (const Window & window, cl::CommandQueue & queue) override virtual
Enqueue the OpenCL kernel to process the given window on the passed OpenCL command queue.
Note
The queue is not flushed by this method, and therefore the kernel will not have been executed by the time this method returns.
Parameters
[in] window Region on which to execute the kernel. (Must be a valid region of the window returned by window()).
[in,out] queue Command queue on which to enqueue the kernel.
Implements ICLKernel.
Definition at line 194 of file CLLKTrackerKernel.cpp.
 {
     ARM_COMPUTE_ERROR_ON_UNCONFIGURED_KERNEL(this);
     ARM_COMPUTE_ERROR_ON_INVALID_SUBWINDOW(ICLKernel::window(), window);
     // Set static tensor arguments. Setting here as allocation might be deferred.
     unsigned int idx = 0;
     add_2D_tensor_argument(idx, _old_input, window);
     add_2D_tensor_argument(idx, _old_scharr_gx, window);
     add_2D_tensor_argument(idx, _old_scharr_gy, window);
     enqueue(queue, *this, window);
 }
References ICLKernel::add_2D_tensor_argument(), ARM_COMPUTE_ERROR_ON_INVALID_SUBWINDOW, ARM_COMPUTE_ERROR_ON_UNCONFIGURED_KERNEL, arm_compute::enqueue(), and IKernel::window().
The documentation for this class was generated from the following files:
arm_compute/core/CL/kernels/CLLKTrackerKernel.h
src/core/CL/kernels/CLLKTrackerKernel.cpp