Compute Library: ILut Class Reference
ILut Class Reference abstract
Lookup Table object interface.
#include <ILut.h>
Public Member Functions
virtual ~ILut ()=default
Default virtual destructor.
virtual size_t num_elements () const =0
Returns the total number of elements in the LUT.
virtual uint32_t index_offset () const =0
Indicates the offset that needs to be applied to the raw index before performing a lookup in the LUT.
virtual size_t size_in_bytes () const =0
Returns the total size in bytes of the LUT.
virtual DataType type () const =0
Returns the type of the LUT.
virtual uint8_t * buffer () const =0
Returns a pointer to the start of the LUT.
virtual void clear ()=0
Clears the LUT by setting every element to zero.
Detailed Description
Lookup Table object interface.
Definition at line 34 of file ILut.h.
Constructor & Destructor Documentation
~ILut()
virtual ~ILut () virtual default
Default virtual destructor.
Member Function Documentation
buffer()
virtual uint8_t* buffer () const pure virtual
Returns a pointer to the start of the LUT.
Other elements of the LUT can be accessed using buffer()[idx] for 0 <= idx < num_elements().
Returns
Pointer to the start of the lut.
Implemented in ICLLut, and Lut.
Referenced by LutAccessor< T >::operator[](), and NECumulativeDistributionKernel::run().
clear()
virtual void clear () pure virtual
Clears the LUT by setting every element to zero.
Implemented in CLLut, and Lut.
index_offset()
virtual uint32_t index_offset () const pure virtual
Indicates the offset that needs to be applied to the raw index before performing a lookup in the LUT.
Returns
The normalization offset.
Implemented in CLLut, and Lut.
Referenced by CLTableLookupKernel::configure(), and LutAccessor< T >::operator[]().
num_elements()
virtual size_t num_elements () const pure virtual
Returns the total number of elements in the LUT.
Returns
Total number of elements.
Implemented in CLLut, and Lut.
Referenced by CLTableLookupKernel::configure(), NECumulativeDistributionKernel::configure(), and LutAccessor< T >::num_elements().
size_in_bytes()
virtual size_t size_in_bytes () const pure virtual
Returns the total size in bytes of the LUT.
Returns
Total size of the LUT in bytes.
Implemented in CLLut, and Lut.
type()
virtual DataType type () const pure virtual
Returns the type of the LUT.
Returns
The type of the LUT.
Implemented in CLLut, and Lut.
Referenced by CLTableLookupKernel::configure(), and NECumulativeDistributionKernel::configure().
The documentation for this class was generated from the following file:
arm_compute/core/ILut.h