Compute Library: CLTensorAllocator Class Reference
CLTensorAllocator Class Reference
Basic implementation of a CL memory tensor allocator.
#include <CLTensorAllocator.h>
Public Member Functions
CLTensorAllocator (CLTensor *owner=nullptr)
Default constructor.
CLTensorAllocator (const CLTensorAllocator &)=delete
Prevent instances of this class from being copied (As this class contains pointers)
CLTensorAllocator & operator= (const CLTensorAllocator &)=delete
Prevent instances of this class from being copy assigned (As this class contains pointers)
CLTensorAllocator (CLTensorAllocator &&)=default
Allow instances of this class to be moved.
CLTensorAllocator & operator= (CLTensorAllocator &&)=default
Allow instances of this class to be moved.
uint8_t * data ()
Interface to be implemented by the child class to return the pointer to the mapped data.
const cl::Buffer & cl_data () const
Interface to be implemented by the child class to return the pointer to the CL data.
uint8_t * map (cl::CommandQueue &q, bool blocking)
Enqueue a map operation of the allocated buffer on the given queue.
void unmap (cl::CommandQueue &q, uint8_t *mapping)
Enqueue an unmap operation of the allocated buffer on the given queue.
void allocate () override
Allocate size specified by TensorInfo of OpenCL memory.
void free () override
Free allocated OpenCL memory.
Status import_memory (cl::Buffer buffer)
Import an existing memory as a tensor's backing memory.
void set_associated_memory_group (CLMemoryGroup *associated_memory_group)
Associates the tensor with a memory group.
Public Member Functions inherited from ITensorAllocator
ITensorAllocator ()
Default constructor.
ITensorAllocator (const ITensorAllocator &)=default
Allow instances of this class to be copy constructed.
ITensorAllocator & operator= (const ITensorAllocator &)=default
Allow instances of this class to be copied.
ITensorAllocator (ITensorAllocator &&)=default
Allow instances of this class to be move constructed.
ITensorAllocator & operator= (ITensorAllocator &&)=default
Allow instances of this class to be moved.
virtual ~ITensorAllocator ()=default
Default virtual destructor.
void init (const TensorInfo &input, size_t alignment=0)
Initialize a tensor based on the passed TensorInfo.
TensorInfo & info ()
Return a reference to the tensor's metadata.
const TensorInfo & info () const
Return a constant reference to the tensor's metadata.
size_t alignment () const
Return underlying's tensor buffer alignment.
Detailed Description
Basic implementation of a CL memory tensor allocator.
Definition at line 43 of file CLTensorAllocator.h.
Constructor & Destructor Documentation
CLTensorAllocator() [1/3]
CLTensorAllocator (CLTensor * owner = nullptr)
Default constructor.
Parameters
[in] owner (Optional) Owner of the allocator.
Definition at line 59 of file CLTensorAllocator.cpp.
     : _associated_memory_group(nullptr), _memory(), _mapping(nullptr), _owner(owner)
 {
 }
CLTensorAllocator() [2/3]
CLTensorAllocator (const CLTensorAllocator &) delete
Prevent instances of this class from being copied (As this class contains pointers)
CLTensorAllocator() [3/3]
CLTensorAllocator (CLTensorAllocator &&) default
Allow instances of this class to be moved.
Member Function Documentation
allocate()
void allocate () override virtual
Allocate size specified by TensorInfo of OpenCL memory.
Note
: The tensor must not already be allocated when calling this function.
Implements ITensorAllocator.
Definition at line 74 of file CLTensorAllocator.cpp.
 {
     if(_associated_memory_group == nullptr)
     {
         if(_memory.region() != nullptr && _memory.cl_region()->cl_data().get() != nullptr)
         {
             // Memory is already allocated. Reuse it if big enough, otherwise fire an assertion
             ARM_COMPUTE_ERROR_ON_MSG(info().total_size() > _memory.region()->size(),
                                      "Reallocation of a bigger memory region is not allowed!");
         }
         else
         {
             // Perform memory allocation
             _memory.set_owned_region(allocate_region(CLScheduler::get().context(), info().total_size(), 0));
         }
     }
     else
     {
         _associated_memory_group->finalize_memory(_owner, _memory, info().total_size());
     }
     info().set_is_resizable(false);
 }
References ARM_COMPUTE_ERROR_ON_MSG, ICLMemoryRegion::cl_data(), CLMemory::cl_region(), MemoryGroupBase< TensorType >::finalize_memory(), CLScheduler::get(), ITensorAllocator::info(), CLMemory::region(), TensorInfo::set_is_resizable(), CLMemory::set_owned_region(), and IMemoryRegion::size().
Referenced by CLTensorHandle::allocate(), CLRNNLayer::configure(), CLFFT2D::configure(), CLFFT1D::configure(), CLMeanStdDev::configure(), CLHOGDescriptor::configure(), CLL2NormalizeLayer::configure(), CLHOGGradient::configure(), CLGaussian5x5::configure(), CLSoftmaxLayer::configure(), CLSobel5x5::configure(), CLSobel7x7::configure(), CLCannyEdge::configure(), CLFastCorners::configure(), CLLocallyConnectedLayer::configure(), CLWinogradConvolutionLayer::configure(), CLDepthwiseConvolutionLayer3x3::configure(), CLHarrisCorners::configure(), CLGEMMLowpMatrixMultiplyCore::configure(), CLHOGMultiDetection::configure(), CLFFTConvolutionLayer::configure(), CLGenerateProposalsLayer::configure(), CLLSTMLayer::configure(), CLDirectDeconvolutionLayer::configure(), CLGEMMDeconvolutionLayer::configure(), CLFullyConnectedLayer::configure(), CLGEMMConvolutionLayer::configure(), CLDepthwiseConvolutionLayer::configure(), CLLocallyConnectedLayer::prepare(), CLGEMMLowpMatrixMultiplyCore::prepare(), CLDepthwiseConvolutionLayer3x3::prepare(), CLWinogradConvolutionLayer::prepare(), CLGEMM::prepare(), CLFFTConvolutionLayer::prepare(), CLGEMMDeconvolutionLayer::prepare(), CLDirectDeconvolutionLayer::prepare(), CLFullyConnectedLayer::prepare(), CLGEMMConvolutionLayer::prepare(), CLDepthwiseConvolutionLayer::prepare(), and arm_compute::test::validation::TEST_CASE().
cl_data()
const cl::Buffer & cl_data () const
Interface to be implemented by the child class to return the pointer to the CL data.
Returns
pointer to the CL data.
Definition at line 69 of file CLTensorAllocator.cpp.
 {
     return _memory.region() == nullptr ? _empty_buffer : _memory.cl_region()->cl_data();
 }
References ICLMemoryRegion::cl_data(), CLMemory::cl_region(), and CLMemory::region().
Referenced by CLTensor::cl_buffer().
data()
uint8_t * data ()
Interface to be implemented by the child class to return the pointer to the mapped data.
Returns
pointer to the mapped data.
Definition at line 64 of file CLTensorAllocator.cpp.
 {
     return _mapping;
 }
free()
void free () override virtual
Free allocated OpenCL memory.
Note
The tensor must have been allocated when calling this function.
Implements ITensorAllocator.
Definition at line 97 of file CLTensorAllocator.cpp.
 {
     _mapping = nullptr;
     _memory.set_region(nullptr);
     info().set_is_resizable(true);
 }
References ITensorAllocator::info(), TensorInfo::set_is_resizable(), and CLMemory::set_region().
Referenced by CLTensorHandle::free(), CLWinogradConvolutionLayer::prepare(), CLFFTConvolutionLayer::prepare(), CLGEMMDeconvolutionLayer::prepare(), CLDirectDeconvolutionLayer::prepare(), CLGEMMConvolutionLayer::prepare(), CLTensorHandle::release_if_unused(), and arm_compute::test::validation::TEST_CASE().
import_memory()
Status import_memory (cl::Buffer buffer)
Import an existing memory as a tensor's backing memory.
Warning
memory should have been created under the same context that ACL uses.
memory is expected to be aligned with the device requirements.
tensor shouldn't be memory managed.
ownership of memory is not transferred.
Note
buffer size will be checked to be compliant with total_size reported by ITensorInfo.
Parameters
[in] buffer Buffer to be used as backing memory
Returns
An error status
Definition at line 104 of file CLTensorAllocator.cpp.
 {
     ARM_COMPUTE_RETURN_ERROR_ON(buffer.get() == nullptr);
     ARM_COMPUTE_RETURN_ERROR_ON(buffer.getInfo<CL_MEM_SIZE>() < info().total_size());
     ARM_COMPUTE_RETURN_ERROR_ON(buffer.getInfo<CL_MEM_CONTEXT>().get() != CLScheduler::get().context().get());
     ARM_COMPUTE_RETURN_ERROR_ON(_associated_memory_group != nullptr);
     _memory.set_owned_region(support::cpp14::make_unique<CLBufferMemoryRegion>(buffer));
     info().set_is_resizable(false);
     return Status{};
 }
References ARM_COMPUTE_RETURN_ERROR_ON, CLScheduler::context(), CLScheduler::get(), ITensorAllocator::info(), TensorInfo::set_is_resizable(), and CLMemory::set_owned_region().
Referenced by CLFFTConvolutionLayer::run(), and arm_compute::test::validation::TEST_CASE().
map()
uint8_t * map (cl::CommandQueue & q, bool blocking)
Enqueue a map operation of the allocated buffer on the given queue.
Parameters
[in,out] q The CL command queue to use for the mapping operation.
[in] blocking If true, then the mapping will be ready to use by the time this method returns, else it is the caller's responsibility to flush the queue and wait for the mapping operation to have completed before using the returned mapping pointer.
Returns
The mapping address.
Definition at line 137 of file CLTensorAllocator.cpp.
 {
     ARM_COMPUTE_ERROR_ON(_mapping != nullptr);
     ARM_COMPUTE_ERROR_ON(_memory.region() == nullptr);
     ARM_COMPUTE_ERROR_ON(_memory.region()->buffer() != nullptr);
     _mapping = reinterpret_cast<uint8_t *>(_memory.cl_region()->map(q, blocking));
     return _mapping;
 }
References ARM_COMPUTE_ERROR_ON, IMemoryRegion::buffer(), CLMemory::cl_region(), ICLMemoryRegion::map(), and CLMemory::region().
operator=() [1/2]
CLTensorAllocator& operator= (const CLTensorAllocator &) delete
Prevent instances of this class from being copy assigned (As this class contains pointers)
operator=() [2/2]
CLTensorAllocator& operator= (CLTensorAllocator &&) default
Allow instances of this class to be moved.
set_associated_memory_group()
void set_associated_memory_group (CLMemoryGroup * associated_memory_group)
Associates the tensor with a memory group.
Parameters
[in] associated_memory_group Memory group to associate the tensor with
Definition at line 117 of file CLTensorAllocator.cpp.
 {
     ARM_COMPUTE_ERROR_ON(associated_memory_group == nullptr);
     ARM_COMPUTE_ERROR_ON(_associated_memory_group != nullptr);
     ARM_COMPUTE_ERROR_ON(_memory.region() != nullptr && _memory.cl_region()->cl_data().get() != nullptr);
     _associated_memory_group = associated_memory_group;
 }
References ARM_COMPUTE_ERROR_ON, ICLMemoryRegion::cl_data(), CLMemory::cl_region(), and CLMemory::region().
unmap()
void unmap (cl::CommandQueue & q, uint8_t * mapping)
Enqueue an unmap operation of the allocated buffer on the given queue.
Note
This method simply enqueue the unmap operation, it is the caller's responsibility to flush the queue and make sure the unmap is finished before the memory is accessed by the device.
Parameters
[in,out] q The CL command queue to use for the mapping operation.
[in] mapping The cpu mapping to unmap.
Definition at line 147 of file CLTensorAllocator.cpp.
 {
     ARM_COMPUTE_ERROR_ON(_mapping == nullptr);
     ARM_COMPUTE_ERROR_ON(_mapping != mapping);
     ARM_COMPUTE_ERROR_ON(_memory.region() == nullptr);
     ARM_COMPUTE_ERROR_ON(_memory.region()->buffer() == nullptr);
     ARM_COMPUTE_UNUSED(mapping);
     _memory.cl_region()->unmap(q);
     _mapping = nullptr;
 }
References ARM_COMPUTE_ERROR_ON, ARM_COMPUTE_UNUSED, IMemoryRegion::buffer(), CLMemory::cl_region(), CLMemory::region(), and ICLMemoryRegion::unmap().
The documentation for this class was generated from the following files:
arm_compute/runtime/CL/CLTensorAllocator.h
src/runtime/CL/CLTensorAllocator.cpp