Compute Library: CLDirectConvolutionLayerKernel Class Reference
CLDirectConvolutionLayerKernel Class Reference
Interface for the direct convolution kernel.
#include <CLDirectConvolutionLayerKernel.h>
Public Member Functions
CLDirectConvolutionLayerKernel ()
Default constructor.
CLDirectConvolutionLayerKernel (const CLDirectConvolutionLayerKernel &)=delete
Prevent instances of this class from being copied (As this class contains pointers)
CLDirectConvolutionLayerKernel & operator= (const CLDirectConvolutionLayerKernel &)=delete
Prevent instances of this class from being copied (As this class contains pointers)
CLDirectConvolutionLayerKernel (CLDirectConvolutionLayerKernel &&)=default
Allow instances of this class to be moved.
CLDirectConvolutionLayerKernel & operator= (CLDirectConvolutionLayerKernel &&)=default
Allow instances of this class to be moved.
~CLDirectConvolutionLayerKernel ()=default
Default destructor.
void configure (const ICLTensor *input, const ICLTensor *weights, const ICLTensor *biases, ICLTensor *output, const PadStrideInfo &conv_info)
Set the input, weights, biases and output tensors.
void run (const Window &window, cl::CommandQueue &queue) override
Enqueue the OpenCL kernel to process the given window on the passed OpenCL command queue.
BorderSize border_size () const override
The size of the border for that kernel.
Public Member Functions inherited from ICLKernel
ICLKernel ()
Constructor.
cl::Kernel & kernel ()
Returns a reference to the OpenCL kernel of this object.
template<typename T >
void add_1D_array_argument (unsigned int &idx, const ICLArray< T > *array, const Strides &strides, unsigned int num_dimensions, const Window &window)
Add the passed 1D array's parameters to the object's kernel's arguments starting from the index idx.
void add_1D_tensor_argument (unsigned int &idx, const ICLTensor *tensor, const Window &window)
Add the passed 1D tensor's parameters to the object's kernel's arguments starting from the index idx.
void add_2D_tensor_argument (unsigned int &idx, const ICLTensor *tensor, const Window &window)
Add the passed 2D tensor's parameters to the object's kernel's arguments starting from the index idx.
void add_3D_tensor_argument (unsigned int &idx, const ICLTensor *tensor, const Window &window)
Add the passed 3D tensor's parameters to the object's kernel's arguments starting from the index idx.
void add_4D_tensor_argument (unsigned int &idx, const ICLTensor *tensor, const Window &window)
Add the passed 4D tensor's parameters to the object's kernel's arguments starting from the index idx.
template<typename T >
void add_argument (unsigned int &idx, T value)
Add the passed parameters to the object's kernel's arguments starting from the index idx.
void set_lws_hint (const cl::NDRange &lws_hint)
Set the Local-Workgroup-Size hint.
cl::NDRange lws_hint () const
Return the Local-Workgroup-Size hint.
const std::string & config_id () const
Get the configuration ID.
void set_target (GPUTarget target)
Set the targeted GPU architecture.
void set_target (cl::Device &device)
Set the targeted GPU architecture according to the CL device.
GPUTarget get_target () const
Get the targeted GPU architecture.
size_t get_max_workgroup_size ()
Get the maximum workgroup size for the device the CLKernelLibrary uses.
template<typename T , unsigned int dimension_size>
void add_array_argument (unsigned &idx, const ICLArray< T > *array, const Strides &strides, unsigned int num_dimensions, const Window &window)
Add the passed array's parameters to the object's kernel's arguments starting from the index idx.
template<unsigned int dimension_size>
void add_tensor_argument (unsigned &idx, const ICLTensor *tensor, const Window &window)
Public Member Functions inherited from IKernel
IKernel ()
Constructor.
virtual ~IKernel ()=default
Destructor.
virtual bool is_parallelisable () const
Indicates whether or not the kernel is parallelisable.
const Window & window () const
The maximum window the kernel can be executed on.
Static Public Member Functions
static Status validate (const ITensorInfo *input, const ITensorInfo *weights, const ITensorInfo *biases, const ITensorInfo *output, const PadStrideInfo &conv_info, const GPUTarget target)
Static function to check if given info will lead to a valid configuration of CLDirectConvolutionLayerKernel.
Static Public Member Functions inherited from ICLKernel
static constexpr unsigned int num_arguments_per_1D_array ()
Returns the number of arguments enqueued per 1D array object.
static constexpr unsigned int num_arguments_per_1D_tensor ()
Returns the number of arguments enqueued per 1D tensor object.
static constexpr unsigned int num_arguments_per_2D_tensor ()
Returns the number of arguments enqueued per 2D tensor object.
static constexpr unsigned int num_arguments_per_3D_tensor ()
Returns the number of arguments enqueued per 3D tensor object.
static constexpr unsigned int num_arguments_per_4D_tensor ()
Returns the number of arguments enqueued per 4D tensor object.
static cl::NDRange gws_from_window (const Window &window)
Get the global work size given an execution window.
Data Fields
const ICLTensor * _input
const ICLTensor * _biases
const ICLTensor * _weights
ICLTensor * _output
BorderSize _border_size
int _conv_stride_x
int _conv_stride_y
Detailed Description
Interface for the direct convolution kernel.
Definition at line 36 of file CLDirectConvolutionLayerKernel.h.
Constructor & Destructor Documentation
CLDirectConvolutionLayerKernel() [1/3]
CLDirectConvolutionLayerKernel ()
Default constructor.
Definition at line 340 of file CLDirectConvolutionLayerKernel.cpp.
     : _input(nullptr), _biases(nullptr), _weights(nullptr), _output(nullptr), _border_size(0), _conv_stride_x(0), _conv_stride_y(0)
 {
 }
CLDirectConvolutionLayerKernel() [2/3]
CLDirectConvolutionLayerKernel (const CLDirectConvolutionLayerKernel &) delete
Prevent instances of this class from being copied (As this class contains pointers)
CLDirectConvolutionLayerKernel() [3/3]
CLDirectConvolutionLayerKernel (CLDirectConvolutionLayerKernel &&) default
Allow instances of this class to be moved.
~CLDirectConvolutionLayerKernel()
~CLDirectConvolutionLayerKernel () default
Default destructor.
Member Function Documentation
border_size()
BorderSize border_size () const override virtual
The size of the border for that kernel.
Returns
The width in number of elements of the border.
Reimplemented from IKernel.
Definition at line 345 of file CLDirectConvolutionLayerKernel.cpp.
 {
     return _border_size;
 }
References CLDirectConvolutionLayerKernel::_border_size.
Referenced by CLDirectConvolutionLayer::configure(), and CLDirectConvolutionLayerKernel::configure().
configure()
void configure (const ICLTensor * input, const ICLTensor * weights, const ICLTensor * biases, ICLTensor * output, const PadStrideInfo & conv_info)
Set the input, weights, biases and output tensors.
Note
: DirectConvolution only works in the following configurations: 1x1 convolution with stride_x = 1/2/3, stride_y = 1/2/3 3x3 convolution with stride_x = 1/2, stride_y = 1/2 5x5 convolution with stride_x = 1/2, stride_y = 1/2
Parameters
[in] input The input tensor to convolve. 3 lower dimensions represent a single input [width, height, IFM], while every optional dimension from 4 and above represent a batch of inputs. Data types supported: QASYMM8/F16/F32.
[in] weights Weights tensor. Weights are 4D tensor with dimensions [kernel_x, kernel_y, IFM, OFM]. The 3rd dimension must be the same as the input's volume 3rd dimension. Data type supported:Same as input.
[in] biases Biases tensor. Biases are 1D tensor with dimension [OFM]. Data type supported: Should match input data type, except for input of QASYMM8 type where biases should be of S32 type
[out] output Output tensor. The 3rd dimensions must be equal to the 4th dimension of the kernels tensor. Data types supported: Same as input.
[in] conv_info Contains padding and stride information described in PadStrideInfo.
Definition at line 350 of file CLDirectConvolutionLayerKernel.cpp.
 {
     ARM_COMPUTE_ERROR_ON_NULLPTR(input, weights, output);
     const DataLayout data_layout = input->info()->data_layout();
     const int        width_idx   = get_data_layout_dimension_index(data_layout, DataLayoutDimension::WIDTH);
     const int        height_idx  = get_data_layout_dimension_index(data_layout, DataLayoutDimension::HEIGHT);
     const int        channel_idx = get_data_layout_dimension_index(data_layout, DataLayoutDimension::CHANNEL);
     const unsigned int kernel_size = weights->info()->dimension(width_idx);
     const DataType     data_type   = input->info()->data_type();
     // Get convolved dimensions
     TensorShape output_shape = misc::shape_calculator::compute_deep_convolution_shape(*input->info(), *weights->info(), conv_info);
     // Output auto inizialitation if not yet initialized
     // TODO(COMPMID-2078): input->clone()->set_tensor_shape(output_shape) doesn't work with subtensors for grouped direct convolutions (AlexNet).
     auto_init_if_empty(*output->info(),
                        output_shape,
                        1,
                        input->info()->data_type(),
                        input->info()->quantization_info());
     // Perform validation step
     ARM_COMPUTE_ERROR_THROW_ON(validate_arguments(input->info(),
                                                   weights->info(),
                                                   (biases != nullptr) ? biases->info() : nullptr,
                                                   output->info(),
                                                   conv_info));
     _conv_stride_x = std::get<0>(conv_info.stride());
     _conv_stride_y = std::get<1>(conv_info.stride());
     if(data_layout == DataLayout::NHWC)
     {
         _border_size = BorderSize(conv_info.pad_left(), 0, conv_info.pad_right(), 0);
     }
     else if(data_layout == DataLayout::NCHW)
     {
         _border_size = BorderSize(conv_info.pad_top(), conv_info.pad_right(), conv_info.pad_bottom(), conv_info.pad_left());
     }
     else
     {
         ARM_COMPUTE_ERROR("Not supported");
     }
     _input   = input;
     _weights = weights;
     _output  = output;
     _biases  = biases;
     const GPUTarget gpu_target = get_target();
     std::stringstream kernel_name;
     kernel_name << "direct_convolution" << kernel_size << "x" << kernel_size;
     if(data_layout == DataLayout::NHWC)
     {
         kernel_name << "_" << lower_string(string_from_data_layout(data_layout));
     }
     CLBuildOptions build_options;
     build_options.add_option_if(_biases != nullptr, std::string("-DHAS_BIAS"));
     const bool run_optimized_for_bifrost = can_run_optimized_kernel_for_bifrost(gpu_target, _conv_stride_x, _conv_stride_y, kernel_size, data_type, data_layout);
     if(run_optimized_for_bifrost)
     {
         build_options.add_option(std::string("-DWEIGHTS_DEPTH=" + support::cpp11::to_string(_weights->info()->dimension(channel_idx))));
         kernel_name << "_f32_bifrost";
         _kernel = static_cast<cl::Kernel>(CLKernelLibrary::get().create_kernel(kernel_name.str(), build_options.options()));
     }
     else
     {
         const bool is_quantized_asymm = is_data_type_quantized_asymmetric(data_type);
         build_options.add_option_if(is_quantized_asymm, std::string("-DKERNEL_SIZE=" + support::cpp11::to_string(kernel_size)));
         build_options.add_option(std::string("-DDATA_TYPE=" + get_cl_type_from_data_type(data_type)));
         build_options.add_option(std::string("-DDATA_SIZE=" + get_data_size_from_data_type(data_type)));
         build_options.add_option(std::string("-DWEIGHTS_DEPTH=" + support::cpp11::to_string(_weights->info()->dimension(channel_idx))));
         build_options.add_option(std::string("-DSTRIDE_X=" + support::cpp11::to_string(_conv_stride_x)));
         if(data_layout == DataLayout::NHWC)
         {
             build_options.add_option(std::string("-DDATA_LAYOUT_NHWC=1"));
             build_options.add_option(std::string("-DDST_HEIGHT=" + support::cpp11::to_string(_output->info()->dimension(height_idx))));
             build_options.add_option(std::string("-DDST_WIDTH=" + support::cpp11::to_string(_output->info()->dimension(width_idx))));
             build_options.add_option(std::string("-DSRC_HEIGHT=" + support::cpp11::to_string(_input->info()->dimension(height_idx))));
             build_options.add_option(std::string("-DSRC_WIDTH=" + support::cpp11::to_string(_input->info()->dimension(width_idx))));
             build_options.add_option(std::string("-DPAD_LEFT=" + support::cpp11::to_string(conv_info.pad_left())));
             build_options.add_option(std::string("-DPAD_TOP=" + support::cpp11::to_string(conv_info.pad_top())));
             build_options.add_option(std::string("-DSTRIDE_Y=" + support::cpp11::to_string(_conv_stride_y)));
         }
         build_options.add_option(std::string("-DDATA_TYPE_PROMOTED=" + get_cl_type_from_data_type(data_type)));
         // Create kernel
         _kernel = static_cast<cl::Kernel>(CLKernelLibrary::get().create_kernel(is_quantized_asymm ? "direct_convolution_1x1_3x3_5x5_quantized" : kernel_name.str(),
                                                                                build_options.options()));
     }
     // Configure kernel window
     auto win_config = validate_and_configure_window(input->info(), weights->info(), output->info(), conv_info, gpu_target);
     ARM_COMPUTE_ERROR_THROW_ON(win_config.first);
     ICLKernel::configure_internal(win_config.second);
     // Set static kernel arguments
     if(is_data_type_quantized_asymmetric(data_type))
     {
         int output_multiplier = 0;
         int output_shift      = 0;
         float multiplier = _input->info()->quantization_info().scale * _weights->info()->quantization_info().scale / _output->info()->quantization_info().scale;
         ARM_COMPUTE_THROW_ON_ERROR(quantization::calculate_quantized_multiplier_less_than_one(multiplier, &output_multiplier, &output_shift));
         unsigned int idx = 3 * num_arguments_per_3D_tensor() + ((_biases != nullptr) ? num_arguments_per_1D_tensor() : 0) + 1;
         _kernel.setArg(idx++, -_input->info()->quantization_info().offset);
         _kernel.setArg(idx++, -_weights->info()->quantization_info().offset);
         _kernel.setArg(idx++, _output->info()->quantization_info().offset);
         _kernel.setArg(idx++, output_multiplier);
         _kernel.setArg(idx++, output_shift);
     }
     // Set config_id for enabling LWS tuning
     _config_id = "direct_convolution_";
     _config_id += lower_string(string_from_data_type(data_type));
     _config_id += "_";
     _config_id += support::cpp11::to_string(kernel_size);
     _config_id += "_";
     _config_id += support::cpp11::to_string(border_size().left);
     _config_id += "_";
     _config_id += support::cpp11::to_string(border_size().top);
     _config_id += "_";
     _config_id += support::cpp11::to_string(border_size().right);
     _config_id += "_";
     _config_id += support::cpp11::to_string(border_size().bottom);
     _config_id += "_";
     _config_id += support::cpp11::to_string(_conv_stride_x);
     _config_id += "_";
     _config_id += support::cpp11::to_string(_conv_stride_y);
     _config_id += "_";
     _config_id += support::cpp11::to_string(output->info()->dimension(width_idx));
     _config_id += "_";
     _config_id += support::cpp11::to_string(output->info()->dimension(height_idx));
     _config_id += "_";
     _config_id += lower_string(string_from_data_layout(data_layout));
 }
References CLDirectConvolutionLayerKernel::_biases, CLDirectConvolutionLayerKernel::_border_size, CLDirectConvolutionLayerKernel::_conv_stride_x, CLDirectConvolutionLayerKernel::_conv_stride_y, CLDirectConvolutionLayerKernel::_input, CLDirectConvolutionLayerKernel::_output, CLDirectConvolutionLayerKernel::_weights, CLBuildOptions::add_option(), CLBuildOptions::add_option_if(), ARM_COMPUTE_ERROR, ARM_COMPUTE_ERROR_ON_NULLPTR, ARM_COMPUTE_ERROR_THROW_ON, ARM_COMPUTE_THROW_ON_ERROR, arm_compute::auto_init_if_empty(), CLDirectConvolutionLayerKernel::border_size(), arm_compute::quantization::calculate_quantized_multiplier_less_than_one(), arm_compute::CHANNEL, arm_compute::misc::shape_calculator::compute_deep_convolution_shape(), arm_compute::test::validation::conv_info, arm_compute::create_kernel(), ITensorInfo::data_layout(), arm_compute::test::validation::data_type, ITensorInfo::data_type(), ITensorInfo::dimension(), TensorInfo::dimension(), CLKernelLibrary::get(), arm_compute::get_cl_type_from_data_type(), arm_compute::get_data_layout_dimension_index(), arm_compute::get_data_size_from_data_type(), ICLKernel::get_target(), arm_compute::HEIGHT, ITensor::info(), CLTensor::info(), arm_compute::is_data_type_quantized_asymmetric(), arm_compute::lower_string(), arm_compute::NCHW, arm_compute::NHWC, ICLKernel::num_arguments_per_1D_tensor(), ICLKernel::num_arguments_per_3D_tensor(), QuantizationInfo::offset, CLBuildOptions::options(), arm_compute::test::validation::output_shape, ITensorInfo::quantization_info(), QuantizationInfo::scale, arm_compute::string_from_data_layout(), arm_compute::string_from_data_type(), arm_compute::support::cpp11::to_string(), arm_compute::test::validation::weights, and arm_compute::WIDTH.
Referenced by CLDirectConvolutionLayer::configure().
operator=() [1/2]
CLDirectConvolutionLayerKernel& operator= (const CLDirectConvolutionLayerKernel &) delete
Prevent instances of this class from being copied (As this class contains pointers)
operator=() [2/2]
CLDirectConvolutionLayerKernel& operator= (CLDirectConvolutionLayerKernel &&) default
Allow instances of this class to be moved.
run()
void run (const Window & window, cl::CommandQueue & queue) override virtual
Enqueue the OpenCL kernel to process the given window on the passed OpenCL command queue.
Note
The queue is not flushed by this method, and therefore the kernel will not have been executed by the time this method returns.
Parameters
[in] window Region on which to execute the kernel. (Must be a valid region of the window returned by window()).
[in,out] queue Command queue on which to enqueue the kernel.
Implements ICLKernel.
Definition at line 503 of file CLDirectConvolutionLayerKernel.cpp.
 {
     ARM_COMPUTE_ERROR_ON_UNCONFIGURED_KERNEL(this);
     ARM_COMPUTE_ERROR_ON_INVALID_SUBWINDOW(IKernel::window(), window);
     // Get initial windows
     Window slice  = window.first_slice_window_3D();
     Window win_in = window;
     win_in.adjust(Window::DimX, -_border_size.left, true);
     win_in.adjust(Window::DimY, -_border_size.top, true);
     const DataLayout data_layout = _input->info()->data_layout();
     const int        width_idx   = get_data_layout_dimension_index(data_layout, DataLayoutDimension::WIDTH);
     const int        height_idx  = get_data_layout_dimension_index(data_layout, DataLayoutDimension::HEIGHT);
     win_in.set_dimension_step(width_idx, window[width_idx].step() * _conv_stride_x);
     win_in.set_dimension_step(height_idx, window[height_idx].step() * _conv_stride_y);
     Window       slice_in = win_in.first_slice_window_3D();
     unsigned int idx1     = 2 * num_arguments_per_3D_tensor();
     add_3D_tensor_argument(idx1, _weights, slice);
     if(_biases != nullptr)
     {
         Window slice_biases;
         slice_biases.use_tensor_dimensions(_biases->info()->tensor_shape());
         add_1D_tensor_argument(idx1, _biases, slice_biases);
     }
     _kernel.setArg(idx1++, static_cast<unsigned int>(_weights->info()->strides_in_bytes()[3]));
     do
     {
         unsigned int idx = 0;
         add_3D_tensor_argument(idx, _input, slice_in);
         add_3D_tensor_argument(idx, _output, slice);
         enqueue(queue, *this, slice, lws_hint());
     }
     while(window.slide_window_slice_3D(slice) && win_in.slide_window_slice_3D(slice_in));
 }
References CLDirectConvolutionLayerKernel::_biases, CLDirectConvolutionLayerKernel::_border_size, CLDirectConvolutionLayerKernel::_conv_stride_x, CLDirectConvolutionLayerKernel::_conv_stride_y, CLDirectConvolutionLayerKernel::_input, CLDirectConvolutionLayerKernel::_output, CLDirectConvolutionLayerKernel::_weights, ICLKernel::add_1D_tensor_argument(), ICLKernel::add_3D_tensor_argument(), Window::adjust(), ARM_COMPUTE_ERROR_ON_INVALID_SUBWINDOW, ARM_COMPUTE_ERROR_ON_UNCONFIGURED_KERNEL, ITensorInfo::data_layout(), Window::DimX, Window::DimY, arm_compute::enqueue(), Window::first_slice_window_3D(), arm_compute::get_data_layout_dimension_index(), arm_compute::HEIGHT, ITensor::info(), BorderSize::left, ICLKernel::lws_hint(), ICLKernel::num_arguments_per_3D_tensor(), Window::set_dimension_step(), arm_compute::test::validation::reference::slice(), Window::slide_window_slice_3D(), arm_compute::test::validation::step, ITensorInfo::strides_in_bytes(), ITensorInfo::tensor_shape(), BorderSize::top, Window::use_tensor_dimensions(), arm_compute::WIDTH, and IKernel::window().
validate()
Status validate (const ITensorInfo * input, const ITensorInfo * weights, const ITensorInfo * biases, const ITensorInfo * output, const PadStrideInfo & conv_info, const GPUTarget target) static
Static function to check if given info will lead to a valid configuration of CLDirectConvolutionLayerKernel.
Parameters
[in] input The input tensor to convolve. 3 lower dimensions represent a single input [width, height, IFM], while every optional dimension from 4 and above represent a batch of inputs. Data types supported: QASYMM8/F16/F32.
[in] weights Weights tensor. Weights are 4D tensor with dimensions [kernel_x, kernel_y, IFM, OFM]. The 3rd dimension must be the same as the input's volume 3rd dimension. Data type supported:Same as input.
[in] biases Biases tensor. Biases are 1D tensor with dimension [OFM]. Data type supported: Same as input.
[in] output Output tensor. The 3rd dimensions must be equal to the 4th dimension of the kernels tensor. Data types supported: Same as input.
[in] conv_info Contains padding and stride information described in PadStrideInfo.
[in] target Target GPU architecture.
Returns
a status
Definition at line 494 of file CLDirectConvolutionLayerKernel.cpp.
 {
     ARM_COMPUTE_RETURN_ON_ERROR(validate_arguments(input, weights, biases, output, conv_info));
     ARM_COMPUTE_RETURN_ON_ERROR(validate_and_configure_window(input->clone().get(), weights->clone().get(), output->clone().get(), conv_info, target).first);
     return Status{};
 }
References ARM_COMPUTE_RETURN_ON_ERROR, ICloneable< T >::clone(), arm_compute::test::validation::conv_info, and arm_compute::test::validation::weights.
Referenced by CLDirectConvolutionLayer::validate().
Field Documentation
_biases
const ICLTensor* _biases
Definition at line 93 of file CLDirectConvolutionLayerKernel.h.
Referenced by CLDirectConvolutionLayerKernel::configure(), and CLDirectConvolutionLayerKernel::run().
_border_size
BorderSize _border_size
Definition at line 96 of file CLDirectConvolutionLayerKernel.h.
Referenced by CLDirectConvolutionLayerKernel::border_size(), CLDirectConvolutionLayerKernel::configure(), and CLDirectConvolutionLayerKernel::run().
_conv_stride_x
int _conv_stride_x
Definition at line 97 of file CLDirectConvolutionLayerKernel.h.
Referenced by CLDirectConvolutionLayerKernel::configure(), and CLDirectConvolutionLayerKernel::run().
_conv_stride_y
int _conv_stride_y
Definition at line 98 of file CLDirectConvolutionLayerKernel.h.
Referenced by CLDirectConvolutionLayerKernel::configure(), and CLDirectConvolutionLayerKernel::run().
_input
const ICLTensor* _input
Definition at line 92 of file CLDirectConvolutionLayerKernel.h.
Referenced by CLDirectConvolutionLayerKernel::configure(), and CLDirectConvolutionLayerKernel::run().
_output
ICLTensor* _output
Definition at line 95 of file CLDirectConvolutionLayerKernel.h.
Referenced by CLDirectConvolutionLayerKernel::configure(), and CLDirectConvolutionLayerKernel::run().
_weights
const ICLTensor* _weights
Definition at line 94 of file CLDirectConvolutionLayerKernel.h.
Referenced by CLDirectConvolutionLayerKernel::configure(), and CLDirectConvolutionLayerKernel::run().
The documentation for this class was generated from the following files:
arm_compute/core/CL/kernels/CLDirectConvolutionLayerKernel.h
src/core/CL/kernels/CLDirectConvolutionLayerKernel.cpp