Compute Library: NEGEMMTranspose1xWKernel Class Reference
NEGEMMTranspose1xWKernel Class Reference
NEON kernel which transposes the elements of a matrix in chunks of 1xW, where W is equal to (16 / element size of the tensor)
#include <NEGEMMTranspose1xWKernel.h>
Public Member Functions
const char * name () const override
Name of the kernel.
void configure (const ITensor *input, ITensor *output)
Initialise the kernel's input and output.
void run (const Window &window, const ThreadInfo &info) override
Execute the kernel on the passed window.
Public Member Functions inherited from ICPPSimpleKernel
ICPPSimpleKernel ()
Constructor.
ICPPSimpleKernel (const ICPPSimpleKernel &)=delete
Prevent instances of this class from being copied (As this class contains pointers)
ICPPSimpleKernel & operator= (const ICPPSimpleKernel &)=delete
Prevent instances of this class from being copied (As this class contains pointers)
ICPPSimpleKernel (ICPPSimpleKernel &&)=default
Allow instances of this class to be moved.
ICPPSimpleKernel & operator= (ICPPSimpleKernel &&)=default
Allow instances of this class to be moved.
~ICPPSimpleKernel ()=default
Default destructor.
Public Member Functions inherited from ICPPKernel
virtual ~ICPPKernel ()=default
Default destructor.
Public Member Functions inherited from IKernel
IKernel ()
Constructor.
virtual ~IKernel ()=default
Destructor.
virtual bool is_parallelisable () const
Indicates whether or not the kernel is parallelisable.
virtual BorderSize border_size () const
The size of the border for that kernel.
const Window & window () const
The maximum window the kernel can be executed on.
Static Public Member Functions
static Status validate (const ITensorInfo *input, const ITensorInfo *output)
Static function to check if given info will lead to a valid configuration of NEGEMMTranspose1xWKernel.
Detailed Description
NEON kernel which transposes the elements of a matrix in chunks of 1xW, where W is equal to (16 / element size of the tensor)
Following an example of how the transposition1xW works when the input data is F32
\[ \left(\begin{array}{cccc} a00 & a01 & a02 & a03 \\ a10 & a11 & a12 & a13 \\ a20 & a21 & a22 & a23 \\ a30 & a31 & a32 & a33 \\ \end{array} \right) \rightarrow \left(\begin{array}{ccccccccccccccccc} a00 & a01 & a02 & a03 & a10 & a11 & a12 & a13 & a20 & a21 & a22 & a23 & a30 & a31 & a32 & a33 \\ \end{array} \right) \]
Following an example of how the transposition1xW works when the input data type is F16
\[ \left(\begin{array}{cccccccc} a00 & a01 & a02 & a03 & a04 & a05 & a06 & a07 \\ a10 & a11 & a12 & a13 & a14 & a15 & a16 & a17 \\ a20 & a21 & a22 & a23 & a24 & a25 & a26 & a27 \\ a30 & a31 & a32 & a33 & a34 & a35 & a36 & a37 \\ \end{array} \right) \rightarrow \left(\begin{array}{cccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccc} a00 & a01 & a02 & a03 & a04 & a05 & a06 & a07 & a10 & a11 & a12 & a13 & a14 & a15 & a16 & a17 & a20 & a21 & a22 & a23 & a24 & a25 & a26 & a27 & a30 & a31 & a32 & a33 & a34 & a35 & a36 & a37\\ \end{array} \right) \]
Note
The output matrix will have the following shape: [ height * W, ceil(width / W) ], where W = (16 / element size of the tensor)
Definition at line 68 of file NEGEMMTranspose1xWKernel.h.
Member Function Documentation
configure()
void configure (const ITensor * input, ITensor * output)
Initialise the kernel's input and output.
Parameters
[in] input Input tensor. Data types supported: U8/S8/QASYMM8/U16/S16/F16/U32/S32/F32
[out] output Output tensor. Data type supported: same as input.
Definition at line 100 of file NEGEMMTranspose1xWKernel.cpp.
 {
     ARM_COMPUTE_ERROR_ON_NULLPTR(input, output);
     // Output tensor auto inizialitation if not yet initialized
     auto_init_if_empty(*output->info(), get_output_shape(input->info()), 1, input->info()->data_type());
     // Perform validate step
     ARM_COMPUTE_ERROR_THROW_ON(validate_arguments(input->info(), output->info()));
     _input  = input;
     _output = output;
     // Configure kernel window
     auto win_config = validate_and_configure_window(input->info(), output->info());
     ARM_COMPUTE_ERROR_THROW_ON(win_config.first);
     INEKernel::configure(win_config.second);
 }
References ARM_COMPUTE_ERROR_ON_NULLPTR, ARM_COMPUTE_ERROR_THROW_ON, arm_compute::auto_init_if_empty(), ITensorInfo::data_type(), and ITensor::info().
Referenced by NEGEMM::configure().
name()
const char* name () const inline override virtual
Name of the kernel.
Returns
Kernel name
Implements ICPPKernel.
Definition at line 71 of file NEGEMMTranspose1xWKernel.h.
     {
         return "NEGEMMTranspose1xWKernel";
     }
run()
void run (const Window & window, const ThreadInfo & info) override virtual
Execute the kernel on the passed window.
Warning
If is_parallelisable() returns false then the passed window must be equal to window()
Note
The window has to be a region within the window returned by the window() method
The width of the window has to be a multiple of num_elems_processed_per_iteration().
Parameters
[in] window Region on which to execute the kernel. (Must be a region of the window returned by window())
[in] info Info about executing thread and CPU.
Implements ICPPKernel.
Definition at line 127 of file NEGEMMTranspose1xWKernel.cpp.
 {
     ARM_COMPUTE_UNUSED(info);
     ARM_COMPUTE_ERROR_ON_UNCONFIGURED_KERNEL(this);
     ARM_COMPUTE_ERROR_ON_INVALID_SUBWINDOW(INESimpleKernel::window(), window);
     /*
      * Following an example of how the transposition1xW works when the input data type is F32
      *
      *         |a00 a01 a02 a03|
      *         |a10 a11 a12 a13|
      *         |a20 a21 a22 a23| = | a00 a01 a02 a03 || a10 a11 a12 a13 || a20 a21 a22 a23 || a30 a31 a32 a33 |
      *         |a30 a31 a32 a33|
      *
      * The output matrix will have the following shape: [ height * W, ceil(width / W) ], where W = (16 / element size of the tensor)
      */
     // Set window for output tensor. Set to 0 the X and Y dimensions in order to allow multi-threading implementation and future batched matrix multiplications
     Window win_out(window);
     win_out.set(Window::DimX, Window::Dimension(0, 0, 0));
     win_out.set(Window::DimY, Window::Dimension(0, 0, 0));
     Iterator in(_input, window);
     Iterator out(_output, win_out);
     switch(_input->info()->element_size())
     {
         case 1:
         {
             const size_t out_stride = _output->info()->strides_in_bytes()[1];
             execute_window_loop(window, [&](const Coordinates & id)
             {
                 // Output address = base addr + (y * 16) + (x / 16 ) * stride
                 const uint8_t *in_ptr  = in.ptr();
                 uint8_t *const out_ptr = out.ptr() + (id.y() << 4) + (id.x() >> 4) * out_stride;
                 vst1q_u8(out_ptr, vld1q_u8(in_ptr));
             },
             in, out);
             break;
         }
         case 2:
         {
             const size_t out_stride = _output->info()->strides_in_bytes()[1] / sizeof(int16_t);
             execute_window_loop(window, [&](const Coordinates & id)
             {
                 // Output address = base addr + (y * 8) + (x / 8 ) * stride
                 const auto in_ptr  = reinterpret_cast<const uint16_t *>(in.ptr());
                 const auto out_ptr = reinterpret_cast<uint16_t *>(out.ptr()) + (id.y() << 3) + (id.x() >> 3) * out_stride;
                 vst1q_u16(out_ptr, vld1q_u16(in_ptr));
             },
             in, out);
             break;
         }
         case 4:
         {
             const size_t out_stride = _output->info()->strides_in_bytes()[1] / sizeof(float);
             execute_window_loop(window, [&](const Coordinates & id)
             {
                 // Output address = base addr + (y * 4) + (x / 4 ) * stride
                 const auto in_ptr  = reinterpret_cast<const uint32_t *>(in.ptr());
                 const auto out_ptr = reinterpret_cast<uint32_t *>(out.ptr()) + (id.y() << 2) + (id.x() >> 2) * out_stride;
                 vst1q_u32(out_ptr, vld1q_u32(in_ptr));
             },
             in, out);
             break;
         }
         default:
         {
             ARM_COMPUTE_ERROR("Element size not supported");
             break;
         }
     }
 }
References ARM_COMPUTE_ERROR, ARM_COMPUTE_ERROR_ON_INVALID_SUBWINDOW, ARM_COMPUTE_ERROR_ON_UNCONFIGURED_KERNEL, ARM_COMPUTE_UNUSED, Window::DimX, Window::DimY, arm_compute::execute_window_loop(), arm_compute::test::validation::info, Iterator::ptr(), Window::set(), and IKernel::window().
validate()
Status validate (const ITensorInfo * input, const ITensorInfo * output) static
Static function to check if given info will lead to a valid configuration of NEGEMMTranspose1xWKernel.
Parameters
[in] input Input tensor info. Data types supported: U8/S8/QASYMM8/U16/S16/F16/U32/S32/F32
[in] output Output tensor info. Data type supported: same as input.
Returns
a status
Definition at line 119 of file NEGEMMTranspose1xWKernel.cpp.
 {
     ARM_COMPUTE_RETURN_ON_ERROR(validate_arguments(input, output));
     ARM_COMPUTE_RETURN_ON_ERROR(validate_and_configure_window(input->clone().get(), output->clone().get()).first);
     return Status{};
 }
References ARM_COMPUTE_RETURN_ON_ERROR, and ICloneable< T >::clone().
Referenced by NEGEMMTranspose1xW::validate(), NEGEMM::validate(), and NEGEMMLowpMatrixMultiplyCore::validate().
The documentation for this class was generated from the following files:
arm_compute/core/NEON/kernels/NEGEMMTranspose1xWKernel.h
src/core/NEON/kernels/NEGEMMTranspose1xWKernel.cpp