Compute Library: YOLOLayer Class Reference
YOLOLayer Class Reference final
YOLO Layer.
#include <Layers.h>
Public Member Functions
YOLOLayer (ActivationLayerInfo act_info, int32_t num_classes)
Construct a YOLO layer.
NodeID create_layer (IStream &s) override
Create layer and add to the given stream.
Public Member Functions inherited from ILayer
virtual ~ILayer ()=default
Default destructor.
ILayer & set_name (std::string name)
Sets the name of the layer.
const std::string & name () const
Layer name accessor.
Detailed Description
YOLO Layer.
Definition at line 1154 of file Layers.h.
Constructor & Destructor Documentation
YOLOLayer()
YOLOLayer (ActivationLayerInfo act_info, int32_t num_classes) inline
Construct a YOLO layer.
Parameters
[in] act_info Activation info
[in] num_classes Number of classes to activate
Definition at line 1162 of file Layers.h.
         : _act_info(act_info), _num_classes(num_classes)
     {
     }
Member Function Documentation
create_layer()
NodeID create_layer (IStream & s) inline override virtual
Create layer and add to the given stream.
Parameters
[in] s Stream to add layer to.
Returns
ID of the created node.
Implements ILayer.
Definition at line 1167 of file Layers.h.
     {
         NodeParams  common_params = { name(), s.hints().target_hint };
         NodeIdxPair input         = { s.tail_node(), 0 };
         return GraphBuilder::add_yolo_node(s.graph(), common_params, input, _act_info, _num_classes);
     }
References GraphBuilder::add_yolo_node(), IStream::graph(), IStream::hints(), ILayer::name(), IStream::tail_node(), and StreamHints::target_hint.
The documentation for this class was generated from the following file:
arm_compute/graph/frontend/Layers.h