Compute Library: NEConvolutionSquare< matrix_size > Class Template Reference
NEConvolutionSquare< matrix_size > Class Template Reference
Basic function to execute convolution of size 5x5, 7x7, 9x9.
#include <NEConvolution.h>
Public Member Functions
NEConvolutionSquare (std::shared_ptr< IMemoryManager > memory_manager=nullptr)
Default constructor.
void configure (ITensor *input, ITensor *output, const int16_t *conv, uint32_t scale, BorderMode border_mode, uint8_t constant_border_value=0)
Initialize the function's source, destination, conv and border_mode.
void run () override
Run the kernels contained in the function.
Public Member Functions inherited from IFunction
virtual ~IFunction ()=default
Destructor.
virtual void prepare ()
Prepare the function for executing.
Detailed Description
template<unsigned int matrix_size>
class arm_compute::NEConvolutionSquare< matrix_size >
Basic function to execute convolution of size 5x5, 7x7, 9x9.
This function calls the following NEON kernels:
NEFillBorderKernel (executed if border_mode == CONSTANT or border_mode == REPLICATE)
NEConvolutionKernel or
NESeparableConvolutionHorKernel and NESeparableConvolutionVertKernel (if convolution matrix is separable)
Definition at line 72 of file NEConvolution.h.
Constructor & Destructor Documentation
NEConvolutionSquare()
NEConvolutionSquare (std::shared_ptr< IMemoryManager > memory_manager = nullptr)
Default constructor.
Definition at line 51 of file NEConvolution.cpp.
     : _memory_group(std::move(memory_manager)), _tmp(), _is_separable(false), _kernel_hor(), _kernel_vert(), _kernel(), _border_handler()
 {
 }
Member Function Documentation
configure()
void configure (ITensor * input, ITensor * output, const int16_t * conv, uint32_t scale, BorderMode border_mode, uint8_t constant_border_value = 0)
Initialize the function's source, destination, conv and border_mode.
Parameters
[in,out] input Source tensor. Data type supported: U8. (Written to only for border_mode != UNDEFINED)
[out] output Destination tensor, Data types supported: U8 or S16.
[in] conv matrix_size x matrix_size S16 coefficients structured as a row-major 2D array in a linear buffer.
[in] scale Scale of the convolution matrix. If 0 is passed, it will be set to the sum of the coefficients of the convolution or 1 if they add up to 0.
[in] border_mode Strategy to use for borders.
[in] constant_border_value (Optional) Constant value to use for borders if border_mode is set to CONSTANT.
Definition at line 57 of file NEConvolution.cpp.
 {
     ARM_COMPUTE_ERROR_ON(conv == nullptr);
     ARM_COMPUTE_ERROR_ON_DATA_TYPE_CHANNEL_NOT_IN(input, 1, DataType::U8);
     ARM_COMPUTE_ERROR_ON_DATA_TYPE_CHANNEL_NOT_IN(output, 1, DataType::U8, DataType::S16);
     std::array<int16_t, matrix_size> conv_col{ { 0 } };
     std::array<int16_t, matrix_size> conv_row{ { 0 } };
     _is_separable = separate_matrix(conv, conv_col.data(), conv_row.data(), matrix_size);
     if(_is_separable)
     {
         DataType intermediate_type = DataType::UNKNOWN;
         std::tie(std::ignore, intermediate_type) = data_type_for_convolution(conv_col.data(), conv_row.data(), matrix_size);
         _tmp.allocator()->init(TensorInfo(input->info()->tensor_shape(), 1, intermediate_type));
         // Manage intermediate buffers
         _memory_group.manage(&_tmp);
         // Calculate scale
         if(scale == 0)
         {
             scale = calculate_matrix_scale(conv, matrix_size);
         }
         _kernel_hor.configure(input, &_tmp, conv_row.data(), border_mode == BorderMode::UNDEFINED);
         _kernel_vert.configure(&_tmp, output, conv_col.data(), scale, border_mode == BorderMode::UNDEFINED);
         _tmp.allocator()->allocate();
         _border_handler.configure(input, _kernel_hor.border_size(), border_mode, PixelValue(constant_border_value));
     }
     else
     {
         _kernel.configure(input, output, conv, scale, border_mode == BorderMode::UNDEFINED);
         _border_handler.configure(input, _kernel.border_size(), border_mode, PixelValue(constant_border_value));
     }
 }
References ARM_COMPUTE_ERROR_ON, ARM_COMPUTE_ERROR_ON_DATA_TYPE_CHANNEL_NOT_IN, arm_compute::test::validation::border_mode, arm_compute::calculate_matrix_scale(), arm_compute::test::validation::conv, arm_compute::data_type_for_convolution(), ITensor::info(), arm_compute::S16, arm_compute::test::validation::scale, arm_compute::separate_matrix(), ITensorInfo::tensor_shape(), arm_compute::U8, arm_compute::UNDEFINED, and arm_compute::UNKNOWN.
run()
void run () override virtual
Run the kernels contained in the function.
For NEON kernels:
Multi-threading is used for the kernels which are parallelisable.
By default std::thread::hardware_concurrency() threads are used.
Note
CPPScheduler::set_num_threads() can be used to manually set the number of threads
For OpenCL kernels:
All the kernels are enqueued on the queue associated with CLScheduler.
The queue is then flushed.
Note
The function will not block until the kernels are executed. It is the user's responsibility to wait.
Will call prepare() on first run if hasn't been done
Implements IFunction.
Definition at line 100 of file NEConvolution.cpp.
 {
     NEScheduler::get().schedule(&_border_handler, Window::DimZ);
     if(_is_separable)
     {
         MemoryGroupResourceScope scope_mg(_memory_group);
         NEScheduler::get().schedule(&_kernel_hor, Window::DimY);
         NEScheduler::get().schedule(&_kernel_vert, Window::DimY);
     }
     else
     {
         NEScheduler::get().schedule(&_kernel, Window::DimY);
     }
 }
References Window::DimY, Window::DimZ, Scheduler::get(), and IScheduler::schedule().
The documentation for this class was generated from the following files:
arm_compute/runtime/NEON/functions/NEConvolution.h
src/runtime/NEON/functions/NEConvolution.cpp