Compute Library: CLDepthwiseConvolutionLayer3x3NHWCKernel Class Reference
CLDepthwiseConvolutionLayer3x3NHWCKernel Class Reference
Interface for the kernel to run a 3x3 depthwise convolution on a tensor when the data layout is NHWC.
#include <CLDepthwiseConvolutionLayer3x3NHWCKernel.h>
Public Member Functions
CLDepthwiseConvolutionLayer3x3NHWCKernel ()
Default constructor.
void configure (const ICLTensor *input, const ICLTensor *weights, const ICLTensor *biases, ICLTensor *output, const PadStrideInfo &conv_info, unsigned int depth_multiplier, ActivationLayerInfo act_info, const Size2D &dilation) override
Default move assignment operator.
void run (const Window &window, cl::CommandQueue &queue) override
Enqueue the OpenCL kernel to process the given window on the passed OpenCL command queue.
BorderSize border_size () const override
The size of the border for that kernel.
Public Member Functions inherited from ICLDepthwiseConvolutionLayer3x3Kernel
ICLDepthwiseConvolutionLayer3x3Kernel ()
Default constructor.
ICLDepthwiseConvolutionLayer3x3Kernel (const ICLDepthwiseConvolutionLayer3x3Kernel &)=delete
Prevent instances of this class from being copied (As this class contains pointers)
ICLDepthwiseConvolutionLayer3x3Kernel & operator= (const ICLDepthwiseConvolutionLayer3x3Kernel &)=delete
Prevent instances of this class from being copied (As this class contains pointers)
ICLDepthwiseConvolutionLayer3x3Kernel (ICLDepthwiseConvolutionLayer3x3Kernel &&)=default
Default Move Constructor.
ICLDepthwiseConvolutionLayer3x3Kernel & operator= (ICLDepthwiseConvolutionLayer3x3Kernel &&)=default
Default move assignment operator.
Public Member Functions inherited from ICLKernel
ICLKernel ()
Constructor.
cl::Kernel & kernel ()
Returns a reference to the OpenCL kernel of this object.
template<typename T >
void add_1D_array_argument (unsigned int &idx, const ICLArray< T > *array, const Strides &strides, unsigned int num_dimensions, const Window &window)
Add the passed 1D array's parameters to the object's kernel's arguments starting from the index idx.
void add_1D_tensor_argument (unsigned int &idx, const ICLTensor *tensor, const Window &window)
Add the passed 1D tensor's parameters to the object's kernel's arguments starting from the index idx.
void add_2D_tensor_argument (unsigned int &idx, const ICLTensor *tensor, const Window &window)
Add the passed 2D tensor's parameters to the object's kernel's arguments starting from the index idx.
void add_3D_tensor_argument (unsigned int &idx, const ICLTensor *tensor, const Window &window)
Add the passed 3D tensor's parameters to the object's kernel's arguments starting from the index idx.
void add_4D_tensor_argument (unsigned int &idx, const ICLTensor *tensor, const Window &window)
Add the passed 4D tensor's parameters to the object's kernel's arguments starting from the index idx.
template<typename T >
void add_argument (unsigned int &idx, T value)
Add the passed parameters to the object's kernel's arguments starting from the index idx.
void set_lws_hint (const cl::NDRange &lws_hint)
Set the Local-Workgroup-Size hint.
cl::NDRange lws_hint () const
Return the Local-Workgroup-Size hint.
const std::string & config_id () const
Get the configuration ID.
void set_target (GPUTarget target)
Set the targeted GPU architecture.
void set_target (cl::Device &device)
Set the targeted GPU architecture according to the CL device.
GPUTarget get_target () const
Get the targeted GPU architecture.
size_t get_max_workgroup_size ()
Get the maximum workgroup size for the device the CLKernelLibrary uses.
template<typename T , unsigned int dimension_size>
void add_array_argument (unsigned &idx, const ICLArray< T > *array, const Strides &strides, unsigned int num_dimensions, const Window &window)
Add the passed array's parameters to the object's kernel's arguments starting from the index idx.
template<unsigned int dimension_size>
void add_tensor_argument (unsigned &idx, const ICLTensor *tensor, const Window &window)
Public Member Functions inherited from IKernel
IKernel ()
Constructor.
virtual ~IKernel ()=default
Destructor.
virtual bool is_parallelisable () const
Indicates whether or not the kernel is parallelisable.
const Window & window () const
The maximum window the kernel can be executed on.
Static Public Member Functions
static Status validate (const ITensorInfo *input, const ITensorInfo *weights, const ITensorInfo *biases, const ITensorInfo *output, const PadStrideInfo &conv_info, unsigned int depth_multiplier, ActivationLayerInfo act_info=ActivationLayerInfo(), const Size2D &dilation=Size2D(1U, 1U))
Static function to check if given info will lead to a valid configuration of CLDepthwiseConvolutionLayer3x3NHWCKernel.
Static Public Member Functions inherited from ICLKernel
static constexpr unsigned int num_arguments_per_1D_array ()
Returns the number of arguments enqueued per 1D array object.
static constexpr unsigned int num_arguments_per_1D_tensor ()
Returns the number of arguments enqueued per 1D tensor object.
static constexpr unsigned int num_arguments_per_2D_tensor ()
Returns the number of arguments enqueued per 2D tensor object.
static constexpr unsigned int num_arguments_per_3D_tensor ()
Returns the number of arguments enqueued per 3D tensor object.
static constexpr unsigned int num_arguments_per_4D_tensor ()
Returns the number of arguments enqueued per 4D tensor object.
static cl::NDRange gws_from_window (const Window &window)
Get the global work size given an execution window.
Detailed Description
Interface for the kernel to run a 3x3 depthwise convolution on a tensor when the data layout is NHWC.
Definition at line 35 of file CLDepthwiseConvolutionLayer3x3NHWCKernel.h.
Constructor & Destructor Documentation
CLDepthwiseConvolutionLayer3x3NHWCKernel()
CLDepthwiseConvolutionLayer3x3NHWCKernel ()
Default constructor.
Definition at line 162 of file CLDepthwiseConvolutionLayer3x3NHWCKernel.cpp.
     : _num_rows_processed_per_iteration(1), _num_planes_processed_per_iteration(1)
 {
 }
Member Function Documentation
border_size()
BorderSize border_size () const override virtual
The size of the border for that kernel.
Returns
The width in number of elements of the border.
Reimplemented from IKernel.
Definition at line 167 of file CLDepthwiseConvolutionLayer3x3NHWCKernel.cpp.
 {
     return _border_size;
 }
configure()
void configure (const ICLTensor * input, const ICLTensor * weights, const ICLTensor * biases, ICLTensor * output, const PadStrideInfo & conv_info, unsigned int depth_multiplier, ActivationLayerInfo act_info, const Size2D & dilation) override virtual
Default move assignment operator.
Initialize the function's source, destination, conv and border_size.
Parameters
[in] input Source tensor. DataType supported: QASYMM8.
[in] weights Weights tensor. A 3D tensor with dimensions [IFM, 3, 3]. Data type supported: Same as input.
[in] biases Biases tensor. A 1D tensor with dimensions [IFM]. Must be nullptr if not needed. Data type supported: Same as input.
[out] output Destination tensor. Data type supported: Same as input.
[in] conv_info Padding and stride information to use for the convolution.
[in] depth_multiplier (Optional) Multiplier to apply to the input's depth in order to retrieve the output's depth. Defaults to 1.
[in] act_info (Optional) Activation layer information in case of a fused activation. Only RELU, BOUNDED_RELU and LU_BOUNDED_RELU are supported.
[in] dilation (Optional) Dilation, in elements, across x and y. Defaults to (1, 1).
Implements ICLDepthwiseConvolutionLayer3x3Kernel.
Definition at line 172 of file CLDepthwiseConvolutionLayer3x3NHWCKernel.cpp.
 {
     ARM_COMPUTE_ERROR_ON_NULLPTR(input, weights, output);
     ARM_COMPUTE_ERROR_THROW_ON(validate_arguments(input->info(), weights->info(), (biases != nullptr) ? biases->info() : nullptr, output->info(), conv_info, depth_multiplier, act_info, dilation));
     auto win_config = validate_and_configure_window(input->info(), weights->info(), biases != nullptr ? biases->info() : nullptr, output->info(), conv_info, depth_multiplier, dilation);
     ARM_COMPUTE_ERROR_THROW_ON(win_config.first);
     const bool is_qasymm              = is_data_type_quantized_asymmetric(input->info()->data_type());
     const bool is_stride_1            = ((conv_info.stride().first == conv_info.stride().second) && (conv_info.stride().first == 1));
     const bool is_stride_1_dilation_1 = (is_stride_1 && dilation.x() == 1 && dilation.y() == 1);
     const bool is_dot8_supported = dot8_supported(CLKernelLibrary::get().get_device());
     _input                              = input;
     _output                             = output;
     _weights                            = weights;
     _biases                             = biases;
     _conv_stride_y                      = conv_info.stride().second;
     _num_rows_processed_per_iteration   = is_stride_1_dilation_1 ? 2 : 1;
     _num_planes_processed_per_iteration = is_stride_1_dilation_1 ? 2 : 1;
     // If QASYMM8 and the 8 bit dot product is available, force _num_planes_processed_per_iteration to 1
     if(is_dot8_supported && is_qasymm)
     {
         _num_planes_processed_per_iteration = 1;
     }
     _border_size = BorderSize(is_qasymm && is_stride_1 ? 0 : conv_info.pad_left(), 0, std::max(std::max(conv_info.pad_right(), conv_info.pad_bottom()), conv_info.pad_top()), 0);
     const unsigned int num_elems_accessed_per_iteration = is_qasymm ? 4 : (8 / input->info()->element_size());
     CLBuildOptions build_opts;
     build_opts.add_option_if(act_info.enabled(), "-DFUSED_ACTIVATION=" + lower_string(string_from_activation_func(act_info.activation())));
     build_opts.add_option_if(_biases != nullptr, "-DHAS_BIAS");
     build_opts.add_option("-DVEC_SIZE=" + support::cpp11::to_string(num_elems_accessed_per_iteration));
     build_opts.add_option("-DSRC_DIM_2=" + support::cpp11::to_string(_input->info()->dimension(2)));
     build_opts.add_option("-DCONV_PAD_TOP=" + support::cpp11::to_string(conv_info.pad_top()));
     build_opts.add_option("-DCONV_PAD_LEFT=" + support::cpp11::to_string(conv_info.pad_left()));
     build_opts.add_option("-DDILATION_X=" + support::cpp11::to_string(dilation.x()));
     build_opts.add_option("-DDILATION_Y=" + support::cpp11::to_string(dilation.y()));
     if(is_qasymm)
     {
         float multiplier        = _input->info()->quantization_info().scale * _weights->info()->quantization_info().scale / _output->info()->quantization_info().scale;
         int   output_multiplier = 0;
         int   output_shift      = 0;
         quantization::calculate_quantized_multiplier_less_than_one(multiplier, &output_multiplier, &output_shift);
         build_opts.add_option("-DSRC_DIM_1=" + support::cpp11::to_string(_input->info()->dimension(1)));
         build_opts.add_option("-DINPUT_OFFSET=" + support::cpp11::to_string(-_input->info()->quantization_info().offset));
         build_opts.add_option("-DWEIGHTS_OFFSET=" + support::cpp11::to_string(-_weights->info()->quantization_info().offset));
         build_opts.add_option("-DOUTPUT_OFFSET=" + support::cpp11::to_string(_output->info()->quantization_info().offset));
         build_opts.add_option("-DK_OFFSET=" + support::cpp11::to_string(9 * input->info()->quantization_info().offset * weights->info()->quantization_info().offset));
         build_opts.add_option("-DOUTPUT_MULTIPLIER=" + support::cpp11::to_string(output_multiplier));
         build_opts.add_option("-DOUTPUT_SHIFT=" + support::cpp11::to_string(output_shift));
         if(act_info.enabled())
         {
             const int a_val = output->info()->quantization_info().quantize(act_info.a(), RoundingPolicy::TO_NEAREST_UP);
             const int b_val = output->info()->quantization_info().quantize(act_info.b(), RoundingPolicy::TO_NEAREST_UP);
             const int o1    = output->info()->quantization_info().offset;
             build_opts.add_option("-DA_VAL=" + support::cpp11::to_string(a_val));
             build_opts.add_option("-DB_VAL=" + support::cpp11::to_string(b_val));
             build_opts.add_option("-DCONST_0=" + support::cpp11::to_string(o1));
             const float s1 = input->info()->quantization_info().scale;
             build_opts.add_option("-DS1_VAL=" + float_to_string_with_full_precision(s1));
             build_opts.add_option("-DO1_VAL=" + support::cpp11::to_string(o1));
         }
     }
     else
     {
         build_opts.add_option_if(act_info.enabled(), "-DA_VAL=" + float_to_string_with_full_precision(act_info.a()));
         build_opts.add_option_if(act_info.enabled(), "-DB_VAL=" + float_to_string_with_full_precision(act_info.b()));
         build_opts.add_option_if(act_info.enabled(), "-DSELECT_DATA_TYPE=" + get_cl_select_type_from_data_type(input->info()->data_type()));
         build_opts.add_option("-DDATA_TYPE=" + get_cl_type_from_data_type(_input->info()->data_type()));
     }
     if(is_stride_1_dilation_1)
     {
         build_opts.add_option("-DNUM_ROWS_PROCESSED=" + support::cpp11::to_string(_num_rows_processed_per_iteration));
         build_opts.add_option("-DNUM_PLANES_PROCESSED=" + support::cpp11::to_string(_num_planes_processed_per_iteration));
         build_opts.add_option("-DDST_DIM_2=" + support::cpp11::to_string(_output->info()->dimension(2)));
     }
     else
     {
         build_opts.add_option("-DCONV_STRIDE_X=" + support::cpp11::to_string(conv_info.stride().first));
         build_opts.add_option("-DCONV_STRIDE_Y=" + support::cpp11::to_string(_conv_stride_y));
     }
     build_opts.add_option_if(_input->info()->tensor_shape().total_size_upper(3) > 1,
                              "-DDST_DEPTH=" + support::cpp11::to_string(static_cast<int>(std::ceil(_output->info()->dimension(2) / static_cast<float>(_num_planes_processed_per_iteration)))));
     std::string kernel_name;
     // Create kernel
     if(is_qasymm)
     {
         kernel_name = std::string("dwc_3x3_reshaped_qasymm8");
         kernel_name += (is_dot8_supported && is_stride_1_dilation_1 ? "_dot8" : "");
         kernel_name += (is_stride_1_dilation_1 ? "_stride1" : "");
         kernel_name += "_nhwc";
     }
     else
     {
         kernel_name = std::string("depthwise_convolution_3x3_nhwc");
         kernel_name += (is_stride_1_dilation_1 ? "_stride1" : "");
     }
     build_opts.add_option_if(input->info()->data_type() == DataType::F16, "-DIS_F16");
     build_opts.add_option_if(input->info()->data_type() == DataType::F32, "-DIS_F32");
     ICLKernel::configure_internal(win_config.second);
     _kernel = static_cast<cl::Kernel>(CLKernelLibrary::get().create_kernel(kernel_name, build_opts.options()));
     // Set config_id for enabling LWS tuning
     _config_id = kernel_name;
     _config_id += "_";
     _config_id += support::cpp11::to_string(input->info()->dimension(0));
     _config_id += "_";
     _config_id += support::cpp11::to_string(input->info()->dimension(1));
     _config_id += "_";
     _config_id += support::cpp11::to_string(input->info()->dimension(2));
     _config_id += "_";
     _config_id += support::cpp11::to_string(output->info()->dimension(0));
     _config_id += "_";
     _config_id += support::cpp11::to_string(output->info()->dimension(1));
     _config_id += "_";
     _config_id += string_from_data_type(input->info()->data_type());
 }
References arm_compute::test::validation::act_info, CLBuildOptions::add_option(), CLBuildOptions::add_option_if(), ARM_COMPUTE_ERROR_ON_NULLPTR, ARM_COMPUTE_ERROR_THROW_ON, arm_compute::quantization::calculate_quantized_multiplier_less_than_one(), arm_compute::test::validation::conv_info, arm_compute::create_kernel(), ITensorInfo::data_type(), arm_compute::test::validation::dilation, ITensorInfo::dimension(), arm_compute::dot8_supported(), ITensorInfo::element_size(), arm_compute::F16, arm_compute::F32, arm_compute::float_to_string_with_full_precision(), CLKernelLibrary::get(), arm_compute::get_cl_select_type_from_data_type(), arm_compute::get_cl_type_from_data_type(), ITensor::info(), CLTensor::info(), arm_compute::is_data_type_quantized_asymmetric(), arm_compute::lower_string(), QuantizationInfo::offset, CLBuildOptions::options(), ITensorInfo::quantization_info(), TensorInfo::quantization_info(), QuantizationInfo::quantize(), QuantizationInfo::scale, arm_compute::string_from_activation_func(), arm_compute::string_from_data_type(), arm_compute::TO_NEAREST_UP, arm_compute::support::cpp11::to_string(), and arm_compute::test::validation::weights.
run()
void run (const Window & window, cl::CommandQueue & queue) override virtual
Enqueue the OpenCL kernel to process the given window on the passed OpenCL command queue.
Note
The queue is not flushed by this method, and therefore the kernel will not have been executed by the time this method returns.
Parameters
[in] window Region on which to execute the kernel. (Must be a valid region of the window returned by window()).
[in,out] queue Command queue on which to enqueue the kernel.
Implements ICLKernel.
Definition at line 315 of file CLDepthwiseConvolutionLayer3x3NHWCKernel.cpp.
 {
     ARM_COMPUTE_ERROR_ON_UNCONFIGURED_KERNEL(this);
     ARM_COMPUTE_ERROR_ON_INVALID_SUBWINDOW(IKernel::window(), window);
     // Collapse window
     Window       window_collapsed = window.collapse_if_possible(ICLKernel::window(), Window::DimZ);
     const size_t total_batches    = _input->info()->tensor_shape().total_size_upper(3);
     const bool   is_qasymm        = is_data_type_quantized_asymmetric(_input->info()->data_type());
     Window win = window_collapsed;
     win.set(Window::DimZ, Window::Dimension(0, std::ceil(_output->info()->dimension(2) / static_cast<float>(_num_planes_processed_per_iteration)) * total_batches, 1));
     // Create input window and adjust
     Window win_in = win;
     win_in.set_dimension_step(Window::DimY, _num_rows_processed_per_iteration);
     win_in.set_dimension_step(Window::DimZ, _conv_stride_y);
     ARM_COMPUTE_ERROR_ON((win_in.y().step() < window.y().step()) || (win_in.z().step() < window.z().step()));
     Window slice_in  = win_in.first_slice_window_4D();
     Window slice_out = win.first_slice_window_4D();
     unsigned int idx = 2 * num_arguments_per_4D_tensor() + (is_qasymm ? num_arguments_per_2D_tensor() : num_arguments_per_3D_tensor());
     if(_biases != nullptr)
     {
         Window win_biases;
         win_biases.use_tensor_dimensions(_biases->info()->tensor_shape());
         win_biases.set_dimension_step(Window::DimX, window.x().step());
         add_1D_tensor_argument(idx, _biases, win_biases);
     }
     const int max_offset = _input->info()->strides_in_bytes().z() * _input->info()->dimension(2) - (_input->info()->padding().bottom + _input->info()->padding().top) *
                            _input->info()->strides_in_bytes().y();
     _kernel.setArg(idx, max_offset);
     do
     {
         unsigned int idx = 0;
         add_4D_tensor_argument(idx, _input, slice_in);
         add_4D_tensor_argument(idx, _output, slice_out);
         if(is_qasymm)
         {
             add_2D_tensor_argument(idx, _weights, slice_out);
         }
         else
         {
             add_3D_tensor_argument(idx, _weights, slice_out);
         }
         enqueue(queue, *this, slice_out, lws_hint());
     }
     while(win.slide_window_slice_4D(slice_out) && win_in.slide_window_slice_4D(slice_in));
 }
References ICLKernel::add_1D_tensor_argument(), ICLKernel::add_2D_tensor_argument(), ICLKernel::add_3D_tensor_argument(), ICLKernel::add_4D_tensor_argument(), ARM_COMPUTE_ERROR_ON, ARM_COMPUTE_ERROR_ON_INVALID_SUBWINDOW, ARM_COMPUTE_ERROR_ON_UNCONFIGURED_KERNEL, Window::collapse_if_possible(), Window::DimX, Window::DimY, Window::DimZ, arm_compute::enqueue(), Window::first_slice_window_4D(), arm_compute::is_data_type_quantized_asymmetric(), ICLKernel::lws_hint(), ICLKernel::num_arguments_per_2D_tensor(), ICLKernel::num_arguments_per_3D_tensor(), ICLKernel::num_arguments_per_4D_tensor(), Window::set(), Window::set_dimension_step(), Window::slide_window_slice_4D(), Window::Dimension::step(), Window::use_tensor_dimensions(), IKernel::window(), Window::x(), Window::y(), and Window::z().
validate()
Status validate (const ITensorInfo * input, const ITensorInfo * weights, const ITensorInfo * biases, const ITensorInfo * output, const PadStrideInfo & conv_info, unsigned int depth_multiplier, ActivationLayerInfo act_info = ActivationLayerInfo(), const Size2D & dilation = Size2D(1U, 1U)) static
Static function to check if given info will lead to a valid configuration of CLDepthwiseConvolutionLayer3x3NHWCKernel.
Parameters
[in] input Source tensor info. DataType supported: QASYMM8.
[in] weights Weights tensor info. A 3D tensor with dimensions [IFM, 3, 3]. Data type supported: Same as input.
[in] biases Biases tensor info. A 1D tensor with dimensions [IFM]. Must be nullptr if not needed. Data type supported: Same as input.
[in] output Destination tensor info. Data type supported: Same as input.
[in] conv_info Padding and stride information to use for the convolution.
[in] depth_multiplier (Optional) Multiplier to apply to the input's depth in order to retrieve the output's depth. Defaults to 1.
[in] act_info (Optional) Activation layer information in case of a fused activation. Only RELU, BOUNDED_RELU and LU_BOUNDED_RELU are supported.
[in] dilation (Optional) Dilation, in elements, across x and y. Defaults to (1, 1).
Returns
a status
Definition at line 303 of file CLDepthwiseConvolutionLayer3x3NHWCKernel.cpp.
 {
     ARM_COMPUTE_RETURN_ON_ERROR(validate_arguments(input, weights, biases, output, conv_info, depth_multiplier, act_info, dilation));
     ARM_COMPUTE_RETURN_ON_ERROR(validate_and_configure_window(input->clone().get(), weights->clone().get(),
                                                               biases != nullptr ? biases->clone().get() : nullptr,
                                                               output->clone().get(), conv_info, depth_multiplier, dilation)
                                 .first);
     return Status{};
 }
References arm_compute::test::validation::act_info, ARM_COMPUTE_RETURN_ON_ERROR, ICloneable< T >::clone(), arm_compute::test::validation::conv_info, arm_compute::test::validation::dilation, and arm_compute::test::validation::weights.
Referenced by CLDepthwiseConvolutionLayer3x3::validate().
The documentation for this class was generated from the following files:
arm_compute/core/CL/kernels/CLDepthwiseConvolutionLayer3x3NHWCKernel.h
src/core/CL/kernels/CLDepthwiseConvolutionLayer3x3NHWCKernel.cpp