Compute Library: ILayer Class Reference
ILayer Class Reference abstract
ILayer interface.
#include <ILayer.h>
Public Member Functions
virtual ~ILayer ()=default
Default destructor.
virtual NodeID create_layer (IStream &s)=0
Create layer and add to the given stream.
ILayer & set_name (std::string name)
Sets the name of the layer.
const std::string & name () const
Layer name accessor.
Detailed Description
ILayer interface.
Definition at line 37 of file ILayer.h.
Constructor & Destructor Documentation
~ILayer()
virtual ~ILayer () virtual default
Default destructor.
Member Function Documentation
create_layer()
virtual NodeID create_layer (IStream & s) pure virtual
Create layer and add to the given stream.
Parameters
[in] s Stream to add layer to.
Returns
ID of the created node.
Implemented in YOLOLayer, UpsampleLayer, StackLayer, SoftmaxLayer, SliceLayer, ScaleLayer, ROIAlignLayer, ResizeLayer, ReshapeLayer, ReorgLayer, PriorBoxLayer, PoolingLayer, PermuteLayer, PadLayer, NormalizePlanarYUVLayer, NormalizationLayer, GenerateProposalsLayer, FullyConnectedLayer, FlattenLayer, EltwiseLayer, DummyLayer, DetectionOutputLayer, DepthwiseConvolutionLayer, DeconvolutionLayer, ConvolutionLayer, ConcatLayer, ChannelShuffleLayer, BoundingBoxTransformLayer, BatchNormalizationLayer, ActivationLayer, OutputLayer, and InputLayer.
Referenced by SubStream::add_layer(), and Stream::add_layer().
name()
const std::string& name () const inline
Layer name accessor.
Returns
Returns the name of the layer
Definition at line 64 of file ILayer.h.
     {
         return _name;
     }
Referenced by InputLayer::create_layer(), OutputLayer::create_layer(), ActivationLayer::create_layer(), BatchNormalizationLayer::create_layer(), BoundingBoxTransformLayer::create_layer(), ChannelShuffleLayer::create_layer(), ConcatLayer::create_layer(), ConvolutionLayer::create_layer(), DeconvolutionLayer::create_layer(), DepthwiseConvolutionLayer::create_layer(), DetectionOutputLayer::create_layer(), DummyLayer::create_layer(), EltwiseLayer::create_layer(), FlattenLayer::create_layer(), FullyConnectedLayer::create_layer(), GenerateProposalsLayer::create_layer(), NormalizationLayer::create_layer(), NormalizePlanarYUVLayer::create_layer(), PadLayer::create_layer(), PermuteLayer::create_layer(), PoolingLayer::create_layer(), PriorBoxLayer::create_layer(), ReorgLayer::create_layer(), ReshapeLayer::create_layer(), ResizeLayer::create_layer(), ROIAlignLayer::create_layer(), ScaleLayer::create_layer(), SliceLayer::create_layer(), SoftmaxLayer::create_layer(), StackLayer::create_layer(), UpsampleLayer::create_layer(), YOLOLayer::create_layer(), and ILayer::set_name().
set_name()
ILayer& set_name (std::string name) inline
Sets the name of the layer.
Parameters
[in] name Name of the layer
Returns
The layer object
Definition at line 55 of file ILayer.h.
     {
         _name = name;
         return *this;
     }
References ILayer::name().
The documentation for this class was generated from the following file:
arm_compute/graph/frontend/ILayer.h