Compute Library: NEDepthConvertLayer Class Reference
NEDepthConvertLayer Class Reference
Basic function to run NEDepthConvertLayerKernel.
#include <NEDepthConvertLayer.h>
Public Member Functions
NEDepthConvertLayer ()=default
NEDepthConvertLayer (const NEDepthConvertLayer &)=delete
Prevent instances of this class from being copied (As this class contains pointers)
const NEDepthConvertLayer & operator= (const NEDepthConvertLayer &)=delete
Prevent instances of this class from being copied (As this class contains pointers)
void configure (const ITensor *input, ITensor *output, ConvertPolicy policy, uint32_t shift=0)
Initialize the function's source, destination.
Public Member Functions inherited from INESimpleFunctionNoBorder
INESimpleFunctionNoBorder ()
Constructor.
void run () override final
Run the kernels contained in the function.
Public Member Functions inherited from IFunction
virtual ~IFunction ()=default
Destructor.
virtual void prepare ()
Prepare the function for executing.
Static Public Member Functions
static Status validate (const ITensorInfo *input, const ITensorInfo *output, ConvertPolicy policy, uint32_t shift=0)
Static function to check if given info will lead to a valid configuration of NEDepthConvertLayer.
Detailed Description
Basic function to run NEDepthConvertLayerKernel.
Definition at line 37 of file NEDepthConvertLayer.h.
Constructor & Destructor Documentation
NEDepthConvertLayer() [1/2]
NEDepthConvertLayer () default
NEDepthConvertLayer() [2/2]
NEDepthConvertLayer (const NEDepthConvertLayer &) delete
Prevent instances of this class from being copied (As this class contains pointers)
Member Function Documentation
configure()
void configure (const ITensor * input, ITensor * output, ConvertPolicy policy, uint32_t shift = 0)
Initialize the function's source, destination.
Valid conversions Input -> Output :
QASYMM8 -> F16, F32
U8 -> U16, S16, S32
U16 -> U8, U32
S16 -> U8, S32
F16 -> QASYMM8, F32
F32 -> QASYMM8, F16
Parameters
[in] input The input tensor to convert. Data types supported: QASYMM8/U8/U16/S16/F16/F32.
[out] output The output tensor. Data types supported: QASYMM8/U8/U16/S16/U32/S32/F16/F32.
[in] policy Conversion policy.
[in] shift (Optional) Value for down/up conversions. Must be 0 <= shift < 8.
Definition at line 33 of file NEDepthConvertLayer.cpp.
 {
     auto k = arm_compute::support::cpp14::make_unique<NEDepthConvertLayerKernel>();
     k->configure(input, output, policy, shift);
     _kernel = std::move(k);
 }
References arm_compute::test::validation::policy, and arm_compute::test::validation::shift.
Referenced by NELaplacianPyramid::configure(), and NELaplacianReconstruct::configure().
operator=()
const NEDepthConvertLayer& operator= (const NEDepthConvertLayer &) delete
Prevent instances of this class from being copied (As this class contains pointers)
validate()
Status validate (const ITensorInfo * input, const ITensorInfo * output, ConvertPolicy policy, uint32_t shift = 0) static
Static function to check if given info will lead to a valid configuration of NEDepthConvertLayer.
Parameters
[in] input Source tensor info. Data types supported: QASYMM8/U8/U16/S16/F16/F32.
[in] output Destination tensor info. Data type supported: QASYMM8/U8/U16/S16/U32/S32/F16/F32.
[in] policy Conversion policy.
[in] shift (Optional) Value for down/up conversions. Must be 0 <= shift < 8.
Returns
a status
Definition at line 40 of file NEDepthConvertLayer.cpp.
 {
     return NEDepthConvertLayerKernel::validate(input, output, policy, shift);
 }
References arm_compute::test::validation::policy, arm_compute::test::validation::shift, and NEDepthConvertLayerKernel::validate().
The documentation for this class was generated from the following files:
arm_compute/runtime/NEON/functions/NEDepthConvertLayer.h
src/runtime/NEON/functions/NEDepthConvertLayer.cpp