Compute Library: NELocallyConnectedMatrixMultiplyKernel Class Reference
NELocallyConnectedMatrixMultiplyKernel Class Reference
NEON kernel to multiply each row of first tensor with low 2 dimensions of second tensor.
#include <NELocallyConnectedMatrixMultiplyKernel.h>
Public Member Functions
const char * name () const override
Name of the kernel.
NELocallyConnectedMatrixMultiplyKernel ()
Default constructor.
NELocallyConnectedMatrixMultiplyKernel (const NELocallyConnectedMatrixMultiplyKernel &)=delete
Prevent instances of this class from being copied (As this class contains pointers)
NELocallyConnectedMatrixMultiplyKernel & operator= (const NELocallyConnectedMatrixMultiplyKernel &)=delete
Prevent instances of this class from being copied (As this class contains pointers)
NELocallyConnectedMatrixMultiplyKernel (NELocallyConnectedMatrixMultiplyKernel &&)=default
Allow instances of this class to be moved.
NELocallyConnectedMatrixMultiplyKernel & operator= (NELocallyConnectedMatrixMultiplyKernel &&)=default
Allow instances of this class to be moved.
void configure (const ITensor *input0, const ITensor *input1, ITensor *output)
Initialise the kernel's input and output.
void run (const Window &window, const ThreadInfo &info) override
Execute the kernel on the passed window.
Public Member Functions inherited from ICPPKernel
virtual ~ICPPKernel ()=default
Default destructor.
Public Member Functions inherited from IKernel
IKernel ()
Constructor.
virtual ~IKernel ()=default
Destructor.
virtual bool is_parallelisable () const
Indicates whether or not the kernel is parallelisable.
virtual BorderSize border_size () const
The size of the border for that kernel.
const Window & window () const
The maximum window the kernel can be executed on.
Static Public Member Functions
static Status validate (const ITensorInfo *input0, const ITensorInfo *input1, const ITensorInfo *output)
Static function to check if given info will lead to a valid configuration of NELocallyConnectedMatrixMultiplyKernel.
Detailed Description
NEON kernel to multiply each row of first tensor with low 2 dimensions of second tensor.
Definition at line 34 of file NELocallyConnectedMatrixMultiplyKernel.h.
Constructor & Destructor Documentation
NELocallyConnectedMatrixMultiplyKernel() [1/3]
NELocallyConnectedMatrixMultiplyKernel ()
Default constructor.
Definition at line 338 of file NELocallyConnectedMatrixMultiplyKernel.cpp.
     : _input0(nullptr), _input1(nullptr), _output(nullptr)
 {
 }
NELocallyConnectedMatrixMultiplyKernel() [2/3]
NELocallyConnectedMatrixMultiplyKernel (const NELocallyConnectedMatrixMultiplyKernel &) delete
Prevent instances of this class from being copied (As this class contains pointers)
NELocallyConnectedMatrixMultiplyKernel() [3/3]
NELocallyConnectedMatrixMultiplyKernel (NELocallyConnectedMatrixMultiplyKernel &&) default
Allow instances of this class to be moved.
Member Function Documentation
configure()
void configure (const ITensor * input0, const ITensor * input1, ITensor * output)
Initialise the kernel's input and output.
Parameters
[in] input0 First input tensor. Data types supported: F16, F32
[in] input1 Second input tensor containing the Matrix B. Data type supported: same as input0
[out] output Output tensor to store the result of matrix multiplication. Data type supported: same as input0
Definition at line 343 of file NELocallyConnectedMatrixMultiplyKernel.cpp.
 {
     ARM_COMPUTE_ERROR_ON_NULLPTR(input0, input1, output);
     ARM_COMPUTE_ERROR_THROW_ON(validate_arguments(input0->info(), input1->info(), output->info()));
     _input0 = input0;
     _input1 = input1;
     _output = output;
     // Configure kernel window
     auto win_config = validate_and_configure_window(input0->info(), input1->info(), output->info());
     ARM_COMPUTE_ERROR_THROW_ON(std::get<0>(win_config));
     INEKernel::configure(std::get<1>(win_config));
 }
References ARM_COMPUTE_ERROR_ON_NULLPTR, ARM_COMPUTE_ERROR_THROW_ON, and ITensor::info().
Referenced by NELocallyConnectedLayer::configure().
name()
const char* name () const inline override virtual
Name of the kernel.
Returns
Kernel name
Implements ICPPKernel.
Definition at line 37 of file NELocallyConnectedMatrixMultiplyKernel.h.
     {
         return "NELocallyConnectedMatrixMultiplyKernel";
     }
operator=() [1/2]
NELocallyConnectedMatrixMultiplyKernel& operator= (const NELocallyConnectedMatrixMultiplyKernel &) delete
Prevent instances of this class from being copied (As this class contains pointers)
operator=() [2/2]
NELocallyConnectedMatrixMultiplyKernel& operator= (NELocallyConnectedMatrixMultiplyKernel &&) default
Allow instances of this class to be moved.
run()
void run (const Window & window, const ThreadInfo & info) override virtual
Execute the kernel on the passed window.
Warning
If is_parallelisable() returns false then the passed window must be equal to window()
Note
The window has to be a region within the window returned by the window() method
The width of the window has to be a multiple of num_elems_processed_per_iteration().
Parameters
[in] window Region on which to execute the kernel. (Must be a region of the window returned by window())
[in] info Info about executing thread and CPU.
Implements ICPPKernel.
Definition at line 368 of file NELocallyConnectedMatrixMultiplyKernel.cpp.
 {
     ARM_COMPUTE_ERROR_ON_UNCONFIGURED_KERNEL(this);
     ARM_COMPUTE_ERROR_ON_INVALID_SUBWINDOW(INEKernel::window(), window);
     switch(_input0->info()->data_type())
     {
         case DataType::F16:
         {
             vector_matrix_multiply_f16(_input0, _input1, _output, window, info);
             break;
         }
         case DataType::F32:
         {
             vector_matrix_multiply_f32(_input0, _input1, _output, window, info);
             break;
         }
         default:
         {
             ARM_COMPUTE_ERROR("Data type not supported");
             break;
         }
     }
 }
References ARM_COMPUTE_ERROR, ARM_COMPUTE_ERROR_ON_INVALID_SUBWINDOW, ARM_COMPUTE_ERROR_ON_UNCONFIGURED_KERNEL, ITensorInfo::data_type(), arm_compute::F16, arm_compute::F32, ITensor::info(), arm_compute::test::validation::info, and IKernel::window().
validate()
Status validate (const ITensorInfo * input0, const ITensorInfo * input1, const ITensorInfo * output) static
Static function to check if given info will lead to a valid configuration of NELocallyConnectedMatrixMultiplyKernel.
Parameters
[in] input0 First input tensor info. Data types supported: F16, F32
[in] input1 Second input tensor info. Data type supported: same as input0
[in] output Output tensor info. Data type supported: same as input0
Returns
a status
Definition at line 360 of file NELocallyConnectedMatrixMultiplyKernel.cpp.
 {
     ARM_COMPUTE_RETURN_ON_ERROR(validate_arguments(input0, input1, output));
     ARM_COMPUTE_RETURN_ON_ERROR(std::get<0>(validate_and_configure_window(input0->clone().get(), input1->clone().get(), output->clone().get())));
     return Status{};
 }
References ARM_COMPUTE_RETURN_ON_ERROR, and ICloneable< T >::clone().
Referenced by NELocallyConnectedLayer::validate().
The documentation for this class was generated from the following files:
arm_compute/core/NEON/kernels/NELocallyConnectedMatrixMultiplyKernel.h
src/core/NEON/kernels/NELocallyConnectedMatrixMultiplyKernel.cpp