Compute Library: ITensorInfo Class Reference
ITensorInfo Class Reference abstract
Store the tensor's metadata.
#include <ITensorInfo.h>
Public Member Functions
virtual ~ITensorInfo ()=default
Default virtual destructor.
virtual ITensorInfo & set_data_type (DataType data_type)=0
Set the data type to the specified value.
virtual ITensorInfo & set_num_channels (int num_channels)=0
Set the number of channels to the specified value.
virtual ITensorInfo & set_format (Format format)=0
Set the format of an already initialized tensor.
virtual ITensorInfo & set_tensor_shape (const TensorShape &shape)=0
Set the shape of an already initialized tensor.
virtual ITensorInfo & set_quantization_info (const QuantizationInfo &quantization_info)=0
Set the quantization settings (scale and offset) of the tensor.
virtual ITensorInfo & set_data_layout (const DataLayout &data_layout)=0
Set the data layout of the tensor.
virtual ITensorInfo & reset_padding ()=0
Resets the padding settings of the tensor.
virtual bool auto_padding ()=0
Update the offset to the first element and the strides to automatically computed values.
virtual bool extend_padding (const PaddingSize &padding)=0
Update the offset to the first element, the strides and the total size.
virtual size_t dimension (size_t index) const =0
Return the size of the requested dimension.
virtual size_t dimension (DataLayoutDimension dimension) const =0
Return the size of the requested data layout dimension.
virtual const Strides & strides_in_bytes () const =0
The strides in bytes for accessing each dimension of the tensor.
virtual size_t offset_first_element_in_bytes () const =0
The offset from the beginning of the memory allocation to the first element of the tensor.
virtual size_t offset_element_in_bytes (const Coordinates &pos) const =0
The offset in bytes from the beginning of the memory allocation to access the element at position (x, y, z ...)
virtual size_t element_size () const =0
Element size in bytes calculated as data_size() * num_channels()
virtual size_t num_dimensions () const =0
The number of dimensions of the tensor (rank)
virtual size_t num_channels () const =0
The number of channels for each tensor element.
virtual const TensorShape & tensor_shape () const =0
Size for each dimension of the tensor.
virtual DataType data_type () const =0
Data type used for each element of the tensor.
virtual Format format () const =0
Colour format of the image.
virtual size_t total_size () const =0
Returns the total size of the tensor in bytes.
virtual PaddingSize padding () const =0
Padding of tensor.
virtual bool has_padding () const =0
Checks if the tensor has been allocated with padding or not.
virtual bool is_resizable () const =0
Flag indicating whether the size of the tensor can be changed.
virtual ITensorInfo & set_is_resizable (bool is_resizable)=0
Set the flag whether the tensor size can be changed.
virtual ValidRegion valid_region () const =0
Valid region of the tensor.
virtual void set_valid_region (const ValidRegion &valid_region)=0
Set the valid region of the tensor.
virtual QuantizationInfo quantization_info () const =0
Get the quantization settings (scale and offset) of the tensor.
virtual DataLayout data_layout () const =0
Get the data layout of the tensor.
Public Member Functions inherited from ICloneable< ITensorInfo >
virtual ~ICloneable ()=default
Default virtual desctructor.
virtual std::unique_ptr< ITensorInfo > clone () const=0
Provide a clone of the current object of class T.
Static Public Member Functions
template<typename... Infos>
static std::pair< TensorShape, ValidRegion > broadcast_shape_and_valid_region (const Infos &... infos)
If infos are broadcast compatible tensor info's, return the broadcasted shape and the intersection of the broadcasted valid regions of the tensors.
Detailed Description
Store the tensor's metadata.
Definition at line 40 of file ITensorInfo.h.
Constructor & Destructor Documentation
~ITensorInfo()
virtual ~ITensorInfo () virtual default
Default virtual destructor.
Member Function Documentation
auto_padding()
virtual bool auto_padding () pure virtual
Update the offset to the first element and the strides to automatically computed values.
Note
The padding used by this method is really conservative so that the tensor can be used for most functions.
Returns
True if the strides or the offset to the first element have changed.
Implemented in TensorInfo, and SubTensorInfo.
Referenced by SubTensorInfo::auto_padding(), and AccessWindowAutoPadding::update_padding_if_needed().
broadcast_shape_and_valid_region()
static std::pair<TensorShape, ValidRegion> broadcast_shape_and_valid_region (const Infos &... infos) inline static
If infos are broadcast compatible tensor info's, return the broadcasted shape and the intersection of the broadcasted valid regions of the tensors.
Two tensor info's are broadcast compatible if their shapes are broadcast compatible.
Two tensor shapes are broadcast compatible if for each dimension, they're equal or one of them is 1.
If two shapes are compatible, each dimension in the broadcasted shape is the max of the original dimensions.
Parameters
[in] infos Tensor info's.
Returns
The broadcasted shape and valid region, or an empty shape and valid region if the info's are not broadcast compatible.
Definition at line 247 of file ITensorInfo.h.
     {
         TensorShape bc_shape = TensorShape::broadcast_shape(infos.tensor_shape()...);
         ValidRegion bc_valid_region{ Coordinates(), bc_shape };
         auto broadcast_valid_region = [&bc_valid_region](const ITensorInfo & info)
         {
             if(info.num_dimensions() != 0)
             {
                 for(size_t d = 0; d < bc_valid_region.shape.num_dimensions(); ++d)
                 {
                     const bool is_broadcast = (info.tensor_shape()[d] == 1);
                     const int    anchor_max = std::max(bc_valid_region.anchor[d], info.valid_region().anchor[d]);
                     const size_t valid_min  = std::min(bc_valid_region.shape[d], info.valid_region().shape[d]);
                     if(!is_broadcast || (valid_min == 0))
                     {
                         bc_valid_region.anchor.set(d, anchor_max);
                         bc_valid_region.shape.set(d, valid_min);
                     }
                 }
             }
         };
         utility::for_each(broadcast_valid_region, infos...);
         return std::pair<TensorShape, ValidRegion>(bc_shape, bc_valid_region);
     }
References TensorShape::broadcast_shape(), arm_compute::utility::for_each(), arm_compute::test::validation::info, and TensorShape::set().
Referenced by NEElementwiseUnaryKernel::configure().
data_layout()
virtual DataLayout data_layout () const pure virtual
Get the data layout of the tensor.
Returns
A DataLayout containing the layout data information.
Implemented in TensorInfo, and SubTensorInfo.
Referenced by ImageAccessor::access_tensor(), ValidationInputAccessor::access_tensor(), arm_compute::auto_init_if_empty(), arm_compute::calculate_valid_region_scale(), arm_compute::misc::shape_calculator::compute_batch_to_space_shape(), arm_compute::misc::shape_calculator::compute_col2im_shape(), arm_compute::misc::shape_calculator::compute_deconvolution_output_shape(), arm_compute::misc::shape_calculator::compute_deconvolution_upsampled_shape(), arm_compute::misc::shape_calculator::compute_deep_convolution_shape(), arm_compute::misc::shape_calculator::compute_depthwise_convolution_shape(), arm_compute::misc::shape_calculator::compute_im2col_conv_shape(), arm_compute::misc::shape_calculator::compute_output_stage_shape(), arm_compute::misc::shape_calculator::compute_pool_shape(), arm_compute::misc::shape_calculator::compute_prior_box_shape(), arm_compute::misc::shape_calculator::compute_reorg_output_shape(), arm_compute::misc::shape_calculator::compute_reshaped_depthwise_weights_shape(), arm_compute::misc::shape_calculator::compute_roi_align_shape(), arm_compute::misc::shape_calculator::compute_space_to_batch_shape(), arm_compute::misc::shape_calculator::compute_upsample_shape(), arm_compute::misc::shape_calculator::compute_winograd_filter_transform_shape(), arm_compute::misc::shape_calculator::compute_winograd_input_transform_shape(), CLScaleKernel::configure(), CLPoolingLayer::configure(), CLScale::configure(), NEUpsampleLayer::configure(), CLRNNLayer::configure(), CLChannelShuffleLayerKernel::configure(), NEIm2Col::configure(), NEPoolingLayer::configure(), CLNormalizationLayerKernel::configure(), CLBatchToSpaceLayerKernel::configure(), CLReorgLayerKernel::configure(), CLSpaceToBatchLayerKernel::configure(), CLUpsampleLayerKernel::configure(), CLComparisonKernel::configure(), NEScale::configure(), CLDepthwiseConvolutionLayerReshapeWeightsGenericKernel::configure(), CLNormalizePlanarYUVLayerKernel::configure(), CLPoolingLayerKernel::configure(), CLDepthwiseVectorToTensorKernel::configure(), CLPriorBoxLayerKernel::configure(), NEPoolingLayerKernel::configure(), NEUpsampleLayerKernel::configure(), NENormalizationLayerKernel::configure(), CLDepthwiseIm2ColKernel::configure(), NEYOLOLayerKernel::configure(), CLWinogradInputTransformKernel::configure(), CLYOLOLayerKernel::configure(), NERNNLayer::configure(), NEDepthwiseVectorToTensorKernel::configure(), CLROIAlignLayerKernel::configure(), CLDirectConvolutionLayerOutputStageKernel::configure(), CLBatchNormalizationLayerKernel::configure(), CLWinogradFilterTransformKernel::configure(), NEDirectConvolutionLayerOutputStageKernel::configure(), CLDirectConvolutionLayerKernel::configure(), CLDeconvolutionReshapeOutputKernel::configure(), NEScaleKernel::configure(), NEDirectConvolutionLayer::configure(), NEWinogradConvolutionLayer::configure(), CLWinogradConvolutionLayer::configure(), NEDepthwiseConvolutionLayer3x3::configure(), CLIm2ColKernel::configure(), CLDepthwiseConvolutionLayer3x3::configure(), CLFFTConvolutionLayer::configure(), NEFFTConvolutionLayer::configure(), CLGenerateProposalsLayer::configure(), NEIm2ColKernel::configure(), CLDirectDeconvolutionLayer::configure(), CLGEMMDeconvolutionLayer::configure(), NEFullyConnectedLayer::configure(), CLFullyConnectedLayer::configure(), NEDeconvolutionLayer::configure(), NEGEMMConvolutionLayer::configure(), CLGEMMConvolutionLayer::configure(), CLDepthwiseConvolutionLayer::configure(), NEDepthwiseConvolutionLayer::configure(), Accessor::data_layout(), SubTensorInfo::data_layout(), SubTensorInfo::dimension(), arm_compute::error_on_data_layout_not_in(), arm_compute::error_on_mismatching_data_layouts(), CPPFlipWeightsKernel::flip_weights(), CLConvolutionLayer::get_convolution_method(), NEConvolutionLayer::get_convolution_method(), CLDeconvolutionLayer::get_deconvolution_method(), NEDepthwiseConvolutionAssemblyDispatch::is_optimized_supported(), CaffePreproccessor::preprocess(), CLUpsampleLayerKernel::run(), CLDeconvolutionLayerUpsampleKernel::run(), CLPoolingLayerKernel::run(), CLDepthwiseConvolutionLayerReshapeWeightsGenericKernel::run(), NEChannelShuffleLayerKernel::run(), NEPoolingLayerKernel::run(), NEReorgLayerKernel::run(), NEWinogradConvolutionLayer::run(), CLROIAlignLayerKernel::run(), NEDirectConvolutionLayerKernel::run(), CLWinogradInputTransformKernel::run(), CLDirectConvolutionLayerKernel::run(), NEBatchToSpaceLayerKernel::run(), NESpaceToBatchLayerKernel::run(), CLIm2ColKernel::run(), CLUpsampleLayerKernel::validate(), CLRNNLayer::validate(), CLDeconvolutionLayerUpsampleKernel::validate(), NEUpsampleLayerKernel::validate(), NEScale::validate(), NEPoolingLayerKernel::validate(), NERNNLayer::validate(), NEDepthwiseConvolutionAssemblyDispatch::validate(), CLConvolutionLayer::validate(), NEScaleKernel::validate(), NEDepthwiseConvolutionLayer3x3::validate(), NEWinogradConvolutionLayer::validate(), CLWinogradConvolutionLayer::validate(), CLDepthwiseConvolutionLayer3x3::validate(), CLGenerateProposalsLayer::validate(), NEFFTConvolutionLayer::validate(), CLFFTConvolutionLayer::validate(), CLGEMMDeconvolutionLayer::validate(), CLDirectDeconvolutionLayer::validate(), NEFullyConnectedLayer::validate(), CLFullyConnectedLayer::validate(), NEGEMMConvolutionLayer::validate(), CLGEMMConvolutionLayer::validate(), CLDepthwiseConvolutionLayer::validate(), NEDepthwiseConvolutionLayer::validate(), and INEWinogradLayerTransformWeightsKernel< T >::validate().
data_type()
virtual DataType data_type () const pure virtual
Data type used for each element of the tensor.
Returns
Tensor data type
Implemented in TensorInfo, and SubTensorInfo.
Referenced by NumPyAccessor::access_tensor(), ValidationOutputAccessor::access_tensor(), DetectionOutputAccessor::access_tensor(), TopNPredictionsAccessor::access_tensor(), RandomAccessor::access_tensor(), arm_compute::auto_init_if_empty(), GCLogits1DMaxKernel::configure(), CLWarpPerspectiveKernel::configure(), CLElementWiseUnaryLayerKernel::configure(), CLNonMaximaSuppression3x3Kernel::configure(), NEFloorKernel::configure(), CLWarpAffineKernel::configure(), GCTransposeKernel::configure(), CLScaleKernel::configure(), NELogits1DMaxKernel::configure(), CLPoolingLayer::configure(), CLGEMMMatrixAccumulateBiasesKernel::configure(), CLDepthwiseConvolutionLayer3x3NCHWKernel::configure(), GCGEMMMatrixAccumulateBiasesKernel::configure(), CLGEMMMatrixVectorMultiplyKernel::configure(), CLReduceMean::configure(), CLDepthwiseConvolutionLayer3x3NHWCKernel::configure(), NEReduceMean::configure(), CLDepthwiseConvolutionLayerReshapeWeightsKernel::configure(), CLDequantizationLayerKernel::configure(), CLFlattenLayerKernel::configure(), CLFloorKernel::configure(), CLRNNLayer::configure(), NEGEMMLowpAssemblyMatrixMultiplyCore::configure(), NEPoolingLayer::configure(), NEReductionOperation::configure(), CLChannelShuffleLayerKernel::configure(), CLReverseKernel::configure(), CLReshapeLayerKernel::configure(), CLCopyKernel::configure(), CLBatchToSpaceLayerKernel::configure(), CLNormalizationLayerKernel::configure(), CLPermuteKernel::configure(), CLGradientKernel::configure(), CLComputeAllAnchorsKernel::configure(), CLMinMaxKernel::configure(), CLQuantizationLayerKernel::configure(), CLRemapKernel::configure(), NEGEMMMatrixVectorMultiplyKernel::configure(), CLReorgLayerKernel::configure(), CLSpaceToBatchLayerKernel::configure(), CLTileKernel::configure(), NETileKernel::configure(), CLUpsampleLayerKernel::configure(), CLGatherKernel::configure(), CLLocallyConnectedMatrixMultiplyKernel::configure(), CLDepthConvertLayerKernel::configure(), CLDepthwiseConvolutionLayerReshapeWeightsGenericKernel::configure(), CLMemsetKernel::configure(), CLComparisonKernel::configure(), CLFFTScaleKernel::configure(), CLActivationLayerKernel::configure(), NETableLookupKernel::configure(), GCActivationLayerKernel::configure(), CLDeconvolutionLayerUpsampleKernel::configure(), GCDepthwiseConvolutionLayer3x3Kernel::configure(), GCPoolingLayerKernel::configure(), CLNormalizePlanarYUVLayerKernel::configure(), CLPixelWiseMultiplicationKernel::configure(), CLPoolingLayerKernel::configure(), CLFFTDigitReverseKernel::configure(), CLFillBorderKernel::configure(), CLWidthConcatenate2TensorsKernel::configure(), CLGEMMMatrixAdditionKernel::configure(), CLDirectConvolutionLayer::configure(), CPPFlipWeightsKernel::configure(), CLMeanStdDev::configure(), GCFillBorderKernel::configure(), GCGEMMMatrixAdditionKernel::configure(), CLAbsoluteDifferenceKernel::configure(), CLDepthwiseVectorToTensorKernel::configure(), CLPriorBoxLayerKernel::configure(), CLReductionOperationKernel::configure(), CLWidthConcatenateLayerKernel::configure(), CLCropKernel::configure(), CLBoundingBoxTransformKernel::configure(), GCNormalizationLayer::configure(), CLHeightConcatenateLayerKernel::configure(), CLRangeKernel::configure(), NEPoolingLayerKernel::configure(), NEUpsampleLayerKernel::configure(), CLWidthConcatenate4TensorsKernel::configure(), CLReductionOperation::configure(), GCGEMMTranspose1xWKernel::configure(), CLL2NormalizeLayerKernel::configure(), CLMagnitudePhaseKernel::configure(), NENormalizationLayer::configure(), CLFFTRadixStageKernel::configure(), CLSelectKernel::configure(), NEReductionOperationKernel::configure(), CLFuseBatchNormalizationKernel::configure(), GCSoftmaxLayer::configure(), CLDepthwiseIm2ColKernel::configure(), CLConvertFullyConnectedWeightsKernel::configure(), CLConvolutionKernel< matrix_size >::configure(), NENormalizationLayerKernel::configure(), CLStackLayerKernel::configure(), NEYOLOLayerKernel::configure(), GCBatchNormalizationLayerKernel::configure(), GCDepthConcatenateLayerKernel::configure(), GCDirectConvolutionLayerKernel< kernel_size >::configure(), CLGEMMReshapeLHSMatrixKernel::configure(), CLDepthConcatenateLayerKernel::configure(), NEAbsoluteDifferenceKernel::configure(), NERNNLayer::configure(), NEDepthwiseConvolutionLayer3x3Kernel::configure(), NEDepthwiseVectorToTensorKernel::configure(), CLGEMMLowpMatrixMultiplyKernel::configure(), CLWinogradInputTransformKernel::configure(), CLYOLOLayerKernel::configure(), CLGEMMMatrixMultiplyReshapedOnlyRHSKernel::configure(), CLROIAlignLayerKernel::configure(), NEMinMaxKernel::configure(), NENonMaximaSuppression3x3Kernel::configure(), CLROIPoolingLayerKernel::configure(), NERangeKernel::configure(), CLSoftmaxLayer::configure(), NEGradientKernel::configure(), NEDepthConcatenateLayerKernel::configure(), NEDirectConvolutionLayerOutputStageKernel::configure(), NEElementwiseUnaryKernel::configure(), CLDirectConvolutionLayerOutputStageKernel::configure(), NEFuseBatchNormalizationKernel::configure(), NEGEMMMatrixAdditionKernel::configure(), NEActivationLayerKernel::configure(), CLBatchNormalizationLayerKernel::configure(), GCDropoutLayerKernel::configure(), CLWinogradFilterTransformKernel::configure(), GCLogits1DShiftExpSumKernel::configure(), NEDepthwiseIm2ColKernel::configure(), NEGatherKernel::configure(), NEPixelWiseMultiplicationKernel::configure(), NESelectKernel::configure(), CLStridedSliceKernel::configure(), GCGEMMMatrixMultiplyKernel::configure(), CLHarrisScoreKernel::configure(), NECumulativeDistributionKernel::configure(), NEDirectConvolutionLayerKernel::configure(), CLWinogradOutputTransformKernel::configure(), CLGEMMMatrixMultiplyReshapedKernel::configure(), CLDirectConvolutionLayerKernel::configure(), NEROIPoolingLayerKernel::configure(), CLDeconvolutionLayerUpsample::configure(), CLGEMMMatrixMultiplyKernel::configure(), GCGEMMInterleave4x4Kernel::configure(), CLDeconvolutionReshapeOutputKernel::configure(), NESpaceToBatchLayerKernel::configure(), NEArithmeticSubtractionKernel::configure(), NEWinogradConvolutionLayer::configure(), NECropKernel::configure(), CLGEMMInterleave4x4Kernel::configure(), NEArithmeticAdditionKernel::configure(), NESoftmaxLayer::configure(), GCTensorShiftKernel::configure(), CLCol2ImKernel::configure(), NELocallyConnectedLayer::configure(), CLLocallyConnectedLayer::configure(), CLWinogradConvolutionLayer::configure(), NEDepthwiseConvolutionLayer3x3::configure(), GCWeightsReshapeKernel::configure(), NEGEMMTranspose1xWKernel::configure(), GCCol2ImKernel::configure(), CLDepthwiseConvolutionLayer3x3::configure(), CLWeightsReshapeKernel::configure(), GCIm2ColKernel::configure(), CLIm2ColKernel::configure(), NELSTMLayer::configure(), CLGEMM::configure(), NEGEMMLowpMatrixMultiplyCore::configure(), CLGenerateProposalsLayer::configure(), NEIm2ColKernel::configure(), CLLSTMLayer::configure(), CLEdgeNonMaxSuppressionKernel::configure(), CLMinMaxLocationKernel::configure(), NEGEMMAssemblyDispatch::configure(), NEHarrisScoreKernel< block_size >::configure(), CLSeparableConvolutionHorKernel< matrix_size >::configure(), GCLogits1DNormKernel::configure(), CLDirectDeconvolutionLayer::configure(), CLGEMMDeconvolutionLayer::configure(), NEFullyConnectedLayer::configure(), NELogits1DSoftmaxKernel::configure(), CLFullyConnectedLayer::configure(), NEDeconvolutionLayer::configure(), GCConvolutionLayer::configure(), NEGEMMInterleavedWrapper::configure(), NEGEMMConvolutionLayer::configure(), NEEdgeNonMaxSuppressionKernel::configure(), CLLogits1DMaxShiftExpSumKernel::configure(), CLSeparableConvolutionVertKernel< matrix_size >::configure(), CLGEMMConvolutionLayer::configure(), CLEdgeTraceKernel::configure(), NEMinMaxLocationKernel::configure(), CLDepthwiseConvolutionLayer::configure(), CLConvolutionRectangleKernel::configure(), CLLogits1DNormKernel::configure(), NEDepthwiseConvolutionLayer::configure(), arm_compute::graph::backends::detail::create_concatenate_layer< GCDepthConcatenateLayer, GCTargetInfo >(), arm_compute::graph::backends::detail::create_convolution_layer< GCConvolutionLayerFunctions, GCTargetInfo >(), arm_compute::graph::backends::detail::create_convolution_layer< NEConvolutionLayerFunctions, NETargetInfo >(), arm_compute::graph::backends::detail::create_depthwise_convolution_layer< GCDepthwiseConvolutionLayerFunctions, GCTargetInfo >(), arm_compute::graph::backends::detail::create_detection_output_layer< CPPDetectionOutputLayer, CLTargetInfo >(), arm_compute::graph::backends::detail::create_normalization_layer< NENormalizationLayer, NETargetInfo >(), Accessor::data_type(), SubTensorInfo::data_type(), arm_compute::error_on_data_type_not_in(), arm_compute::error_on_mismatching_data_types(), arm_compute::error_on_mismatching_quantization_info(), arm_compute::error_on_unsupported_cpu_fp16(), arm_compute::error_on_unsupported_fp16(), NEMinMaxKernel::reset(), CLMinMaxKernel::run(), NEFillInnerBorderKernel::run(), NENonMaximaSuppression3x3Kernel::run(), NEGEMMMatrixAccumulateBiasesKernel::run(), NELocallyConnectedMatrixMultiplyKernel::run(), NEDequantizationLayerKernel::run(), NEFillBorderKernel::run(), NEHOGDetectorKernel::run(), CPPBoxWithNonMaximaSuppressionLimitKernel::run(), NEReverseKernel::run(), NEQuantizationLayerKernel::run(), NEPoolingLayerKernel::run(), CPPTopKVKernel::run(), CLReductionOperationKernel::run(), NEWidthConcatenateLayerKernel::run(), NEHeightConcatenateLayerKernel::run(), NEDepthConvertLayerKernel::run(), NEGEMMLowpMatrixMultiplyKernel::run(), NEDepthwiseConvolutionLayer3x3Kernel::run(), NEDirectConvolutionLayerKernel::run(), NEGEMMMatrixMultiplyKernel::run(), NEHOGBlockNormalizationKernel::run(), NEEdgeNonMaxSuppressionKernel::run(), NELSTMLayer::run(), NEConvolutionRectangleKernel::run(), SubTensorInfo::set_tensor_shape(), CLRNNLayer::validate(), CLFFT1D::validate(), NEFFT1D::validate(), CLMeanStdDev::validate(), NEL2NormalizeLayer::validate(), CLReductionOperation::validate(), CLL2NormalizeLayer::validate(), CLSoftmaxLayer::validate(), NERNNLayer::validate(), NESoftmaxLayer::validate(), CLLocallyConnectedLayer::validate(), NELocallyConnectedLayer::validate(), NEDirectConvolutionLayer::validate(), NEDepthwiseConvolutionLayer3x3::validate(), CLWinogradConvolutionLayer::validate(), CLGEMM::validate(), NEGEMMAssemblyDispatch::validate(), CLGEMMDeconvolutionLayer::validate(), CLDirectDeconvolutionLayer::validate(), NEDeconvolutionLayer::validate(), NEFullyConnectedLayer::validate(), CLFullyConnectedLayer::validate(), NELSTMLayer::validate(), CLLSTMLayer::validate(), NEGEMMConvolutionLayer::validate(), CLGEMMConvolutionLayer::validate(), CLDepthwiseConvolutionLayer::validate(), and NEDepthwiseConvolutionLayer::validate().
dimension() [1/2]
virtual size_t dimension (size_t index) const pure virtual
Return the size of the requested dimension.
Parameters
[in] index Index of the dimension
Returns
Dimension of the requested dimension
Implemented in TensorInfo, and SubTensorInfo.
Referenced by NumPyAccessor::access_tensor(), TopNPredictionsAccessor::access_tensor(), CLElementwiseOperationKernel::border_size(), CLComparisonKernel::border_size(), CLPixelWiseMultiplicationKernel::border_size(), NEPixelWiseMultiplicationKernel::border_size(), NEArithmeticSubtractionKernel::border_size(), CLComplexPixelWiseMultiplicationKernel::border_size(), NEComplexPixelWiseMultiplicationKernel::border_size(), arm_compute::misc::shape_calculator::compute_deconvolution_upsampled_shape(), arm_compute::misc::shape_calculator::compute_interleaved_shape(), arm_compute::misc::shape_calculator::compute_lhs_reshaped_shape(), arm_compute::misc::shape_calculator::compute_mm_shape(), arm_compute::misc::shape_calculator::compute_prior_box_shape(), arm_compute::misc::shape_calculator::compute_reductionB_shape(), arm_compute::misc::shape_calculator::compute_reshaped_depthwise_weights_shape(), arm_compute::misc::shape_calculator::compute_rhs_reshaped_shape(), arm_compute::misc::shape_calculator::compute_roi_align_shape(), arm_compute::misc::shape_calculator::compute_transposed_shape(), arm_compute::misc::shape_calculator::compute_upsample_shape(), arm_compute::misc::shape_calculator::compute_winograd_filter_transform_shape(), arm_compute::misc::shape_calculator::compute_winograd_output_transform_shape(), GCLogits1DMaxKernel::configure(), CLIntegralImageHorKernel::configure(), CLWarpPerspectiveKernel::configure(), GCTransposeKernel::configure(), CLWarpAffineKernel::configure(), GCScaleKernel::configure(), CLScaleKernel::configure(), CLComparison::configure(), CLPixelWiseMultiplication::configure(), CLDepthwiseConvolutionLayer3x3NCHWKernel::configure(), GCGEMMMatrixAccumulateBiasesKernel::configure(), CLDepthwiseConvolutionLayer3x3NHWCKernel::configure(), CLGEMMMatrixVectorMultiplyKernel::configure(), NEArithmeticSubtraction::configure(), NEPixelWiseMultiplication::configure(), CLMinMaxLayerKernel::configure(), CLFlattenLayerKernel::configure(), CLRNNLayer::configure(), NEGEMMLowpAssemblyMatrixMultiplyCore::configure(), CLDepthwiseConvolutionLayerReshapeWeightsKernel::configure(), CLChannelShuffleLayerKernel::configure(), CLGaussianPyramidHorKernel::configure(), CLReverseKernel::configure(), NEPoolingLayer::configure(), NEUnstack::configure(), CLBatchToSpaceLayerKernel::configure(), CLNormalizationLayerKernel::configure(), CLPermuteKernel::configure(), CLComputeAllAnchorsKernel::configure(), CLLocallyConnectedMatrixMultiplyKernel::configure(), CLMinMaxKernel::configure(), NEGEMMMatrixVectorMultiplyKernel::configure(), CLGatherKernel::configure(), CLRemapKernel::configure(), CLReorgLayerKernel::configure(), CLSpaceToBatchLayerKernel::configure(), CLTileKernel::configure(), CLUpsampleLayerKernel::configure(), CLUnstack::configure(), NEScale::configure(), GCPoolingLayerKernel::configure(), CLFFTScaleKernel::configure(), CLComparisonKernel::configure(), CLActivationLayerKernel::configure(), CLDepthwiseConvolutionLayerReshapeWeightsGenericKernel::configure(), GCDepthwiseConvolutionLayer3x3Kernel::configure(), CLHOGOrientationBinningKernel::configure(), NEGaussianPyramidHorKernel::configure(), CLFFTDigitReverseKernel::configure(), CLNormalizePlanarYUVLayerKernel::configure(), CLPoolingLayerKernel::configure(), CLMeanStdDev::configure(), CLWidthConcatenate2TensorsKernel::configure(), GCGEMMMatrixAdditionKernel::configure(), NEHOGDescriptor::configure(), CLPriorBoxLayerKernel::configure(), CLReductionOperationKernel::configure(), CLWidthConcatenateLayerKernel::configure(), GCConvolutionLayerReshapeWeights::configure(), CLHeightConcatenateLayerKernel::configure(), GCGEMMTranspose1xWKernel::configure(), CLMeanStdDevKernel::configure(), NEPoolingLayerKernel::configure(), CLRangeKernel::configure(), CLHOGDescriptor::configure(), CLReductionOperation::configure(), CLWidthConcatenate4TensorsKernel::configure(), CPPTopKVKernel::configure(), CLGEMMReshapeRHSMatrixKernel::configure(), CLFFTRadixStageKernel::configure(), NEReductionOperationKernel::configure(), CLFuseBatchNormalizationKernel::configure(), CLSelectKernel::configure(), CLDepthwiseIm2ColKernel::configure(), NEHOGOrientationBinningKernel::configure(), NERemapKernel::configure(), CLStackLayerKernel::configure(), CLGEMMReshapeLHSMatrixKernel::configure(), GCDepthConcatenateLayerKernel::configure(), GCDirectConvolutionLayerKernel< kernel_size >::configure(), CLIntegralImageVertKernel::configure(), NERNNLayer::configure(), CLGEMMLowpMatrixMultiplyKernel::configure(), CLGEMMLowpMatrixMultiplyReshapedOnlyRHSKernel::configure(), CLGEMMMatrixMultiplyReshapedOnlyRHSKernel::configure(), CLWinogradInputTransformKernel::configure(), CLYOLOLayerKernel::configure(), CLROIAlignLayerKernel::configure(), CLROIPoolingLayerKernel::configure(), GCLogits1DShiftExpSumKernel::configure(), CLWinogradFilterTransformKernel::configure(), NEMeanStdDevKernel::configure(), CLBatchNormalizationLayerKernel::configure(), CLGEMMLowpMatrixMultiplyReshapedKernel::configure(), CLStridedSliceKernel::configure(), CLGEMMLowpOffsetContributionOutputStageKernel::configure(), GCGEMMMatrixMultiplyKernel::configure(), CLGEMMMatrixMultiplyReshapedKernel::configure(), CLWinogradOutputTransformKernel::configure(), CPPBoxWithNonMaximaSuppressionLimitKernel::configure(), CLDirectConvolutionLayerKernel::configure(), NEGEMMMatrixMultiplyKernel::configure(), NEROIPoolingLayerKernel::configure(), CLGEMMMatrixMultiplyKernel::configure(), NELaplacianPyramid::configure(), CLCannyEdge::configure(), CLLaplacianPyramid::configure(), CLDeconvolutionReshapeOutputKernel::configure(), GCGEMMInterleave4x4Kernel::configure(), NEScaleKernel::configure(), CLGEMMLowpOffsetContributionKernel::configure(), GCTensorShiftKernel::configure(), NEWinogradConvolutionLayer::configure(), NECropKernel::configure(), CLGEMMInterleave4x4Kernel::configure(), CLGEMMLowpMatrixAReductionKernel::configure(), CLCol2ImKernel::configure(), CLLocallyConnectedLayer::configure(), NELocallyConnectedLayer::configure(), CLComparisonStatic< COP >::configure(), NEGEMM::configure(), GCGEMM::configure(), NEDepthwiseConvolutionLayer3x3::configure(), NELaplacianReconstruct::configure(), GCWeightsReshapeKernel::configure(), CLLaplacianReconstruct::configure(), GCCol2ImKernel::configure(), CLIm2ColKernel::configure(), GCIm2ColKernel::configure(), NEOpticalFlow::configure(), CLComplexPixelWiseMultiplication::configure(), CLDepthwiseConvolutionLayer3x3::configure(), CLGEMMLowpMatrixMultiplyCore::configure(), NEHOGMultiDetection::configure(), CLHOGMultiDetection::configure(), NEComplexPixelWiseMultiplication::configure(), GCFullyConnectedLayer::configure(), CLGEMM::configure(), NEGEMMLowpMatrixMultiplyCore::configure(), CLHistogramBorderKernel::configure(), CLGaussianPyramidVertKernel::configure(), CLGenerateProposalsLayer::configure(), NEIm2ColKernel::configure(), CLGaussianPyramidHalf::configure(), CLOpticalFlow::configure(), NEGaussianPyramidHalf::configure(), NEGaussianPyramidVertKernel::configure(), CLDirectDeconvolutionLayer::configure(), CLGEMMDeconvolutionLayer::configure(), CLGEMMLowpMatrixBReductionKernel::configure(), NEFullyConnectedLayer::configure(), CLFullyConnectedLayer::configure(), NEDeconvolutionLayer::configure(), GCConvolutionLayer::configure(), CLGaussianPyramidOrb::configure(), CPPDetectionOutputLayer::configure(), NEGaussianPyramidOrb::configure(), NEGEMMConvolutionLayer::configure(), CLLogits1DMaxShiftExpSumKernel::configure(), CLGEMMConvolutionLayer::configure(), CLEdgeTraceKernel::configure(), CLDepthwiseConvolutionLayer::configure(), NEDepthwiseConvolutionLayer::configure(), NECropKernel::configure_output_shape(), ITensor::copy_from(), CPPFlipWeightsKernel::flip_weights(), CLConvolutionLayer::get_convolution_method(), NEConvolutionLayer::get_convolution_method(), CLHistogramKernel::run(), CLGEMMMatrixVectorMultiplyKernel::run(), CLIntegralImageVertKernel::run(), CPPUpsampleKernel::run(), NECopyKernel::run(), CLROIPoolingLayerKernel::run(), NEMeanStdDevKernel::run(), NETileKernel::run(), CLUpsampleLayerKernel::run(), NEGEMMMatrixVectorMultiplyKernel::run(), CLDepthwiseConvolutionLayerReshapeWeightsGenericKernel::run(), CLPoolingLayerKernel::run(), CLDeconvolutionLayerUpsampleKernel::run(), CLDepthwiseVectorToTensorKernel::run(), NEROIPoolingLayerKernel::run(), CLPriorBoxLayerKernel::run(), NEFlattenLayerKernel::run(), NEPoolingLayerKernel::run(), CLMeanStdDevKernel::run(), CPPNonMaximumSuppression::run(), CLReductionOperationKernel::run(), NEGEMMLowpMatrixMultiplyKernel::run(), CLDepthwiseIm2ColKernel::run(), CLROIAlignLayerKernel::run(), GCCol2ImKernel::run(), NEFFTRadixStageKernel::run(), NEGEMMMatrixMultiplyKernel::run(), NEDirectConvolutionLayerKernel::run(), NEBatchToSpaceLayerKernel::run(), NESpaceToBatchLayerKernel::run(), NEWeightsReshapeKernel::run(), CLWeightsReshapeKernel::run(), CLLogits1DMaxShiftExpSumKernel::run(), CPPBoxWithNonMaximaSuppressionLimitKernel::run_nmslimit(), arm_compute::run_reverse(), CLReduceMean::validate(), NEUnstack::validate(), NEReduceMean::validate(), CLUnstack::validate(), CLRNNLayer::validate(), CLUpsampleLayerKernel::validate(), CLMeanStdDev::validate(), CLDeconvolutionLayerUpsampleKernel::validate(), NEUpsampleLayerKernel::validate(), CLConvertFullyConnectedWeightsKernel::validate(), NEScale::validate(), NEPadLayer::validate(), CLReductionOperation::validate(), NEConvolutionLayerReshapeWeights::validate(), NEPoolingLayerKernel::validate(), CLCropKernel::validate(), NEConvertFullyConnectedWeightsKernel::validate(), CLPadLayer::validate(), NERNNLayer::validate(), CLConvolutionLayerReshapeWeights::validate(), NELocallyConnectedLayer::validate(), CLLocallyConnectedLayer::validate(), NEGEMM::validate(), CLGEMMLowpMatrixMultiplyCore::validate(), CLCropResize::validate(), NEDepthwiseConvolutionLayer3x3::validate(), NEWinogradConvolutionLayer::validate(), CLGEMM::validate(), NEGEMMLowpMatrixMultiplyCore::validate(), CLGenerateProposalsLayer::validate(), CLGEMMDeconvolutionLayer::validate(), CLDirectDeconvolutionLayer::validate(), NEDeconvolutionLayer::validate(), NEFullyConnectedLayer::validate(), CLFullyConnectedLayer::validate(), NELSTMLayer::validate(), CLLSTMLayer::validate(), NEGEMMConvolutionLayer::validate(), CLGEMMConvolutionLayer::validate(), CLDepthwiseConvolutionLayer::validate(), and NEDepthwiseConvolutionLayer::validate().
dimension() [2/2]
virtual size_t dimension (DataLayoutDimension dimension) const pure virtual
Return the size of the requested data layout dimension.
Parameters
[in] dimension DataLayoutDimension of the dimension
Returns
Dimension of the requested dimension
Implemented in TensorInfo, and SubTensorInfo.
element_size()
virtual size_t element_size () const pure virtual
Element size in bytes calculated as data_size() * num_channels()
Returns
The size of one element in bytes
Implemented in TensorInfo, and SubTensorInfo.
Referenced by CLElementWiseUnaryLayerKernel::configure(), CLTransposeKernel::configure(), CLDepthwiseConvolutionLayer3x3NHWCKernel::configure(), CLDequantizationLayerKernel::configure(), CLFloorKernel::configure(), CLChannelShuffleLayerKernel::configure(), CLReverseKernel::configure(), CLCopyKernel::configure(), CLQuantizationLayerKernel::configure(), NEGEMMMatrixVectorMultiplyKernel::configure(), CLTileKernel::configure(), CLMemsetKernel::configure(), CLActivationLayerKernel::configure(), GCActivationLayerKernel::configure(), NEScale::configure(), CLNormalizePlanarYUVLayerKernel::configure(), CLWidthConcatenate2TensorsKernel::configure(), CLHeightConcatenateLayerKernel::configure(), GCGEMMTranspose1xWKernel::configure(), NEDepthwiseWeightsReshapeKernel::configure(), CLWidthConcatenate4TensorsKernel::configure(), NEUpsampleLayerKernel::configure(), CLGEMMReshapeRHSMatrixKernel::configure(), CLSelectKernel::configure(), NENormalizationLayerKernel::configure(), CLGEMMReshapeLHSMatrixKernel::configure(), NETransposeKernel::configure(), CLDepthConcatenateLayerKernel::configure(), CPPPermuteKernel::configure(), CLYOLOLayerKernel::configure(), NEPermuteKernel::configure(), GCDropoutLayerKernel::configure(), NEGEMMInterleave4x4Kernel::configure(), CLBatchNormalizationLayerKernel::configure(), CLStridedSliceKernel::configure(), CLGEMMInterleave4x4Kernel::configure(), NEWinogradConvolutionLayer::configure(), CLCol2ImKernel::configure(), CLGEMMTranspose1xWKernel::configure(), NECol2ImKernel::configure(), GCIm2ColKernel::configure(), ITensor::copy_from(), Accessor::element_size(), SubTensorInfo::element_size(), NEDepthwiseConvolutionAssemblyDispatch::prepare(), NEMemsetKernel::run(), CPPUpsampleKernel::run(), NECopyKernel::run(), NETileKernel::run(), NEFlattenLayerKernel::run(), NEReorgLayerKernel::run(), CLReductionOperationKernel::run(), NEConvertFullyConnectedWeightsKernel::run(), NEGEMMLowpMatrixMultiplyKernel::run(), NEStackLayerKernel::run(), NEBatchToSpaceLayerKernel::run(), NESpaceToBatchLayerKernel::run(), NEWeightsReshapeKernel::run(), NEDepthwiseConvolutionAssemblyDispatch::run(), NELogits1DSoftmaxKernel::run(), NELSTMLayer::run(), arm_compute::run_reverse(), and NEUpsampleLayerKernel::validate().
extend_padding()
virtual bool extend_padding (const PaddingSize & padding) pure virtual
Update the offset to the first element, the strides and the total size.
Note
This function can only increase the offset, strides and total size.
Parameters
[in] padding Padding around the XY plane in number of elements.
Returns
True if the strides, offset and total size have changed.
Implemented in TensorInfo, and SubTensorInfo.
Referenced by GCConvolutionLayer::configure(), SubTensorInfo::extend_padding(), AccessWindowStatic::update_padding_if_needed(), and AccessWindowRectangle::update_padding_if_needed().
format()
virtual Format format () const pure virtual
Colour format of the image.
Returns
Colour format of the image
Implemented in TensorInfo, and SubTensorInfo.
Referenced by CLChannelExtractKernel::configure(), CLColorConvertKernel::configure(), CLChannelCombineKernel::configure(), NEColorConvertKernel::configure(), NEChannelExtractKernel::configure(), NEChannelCombineKernel::configure(), Accessor::format(), SubTensorInfo::format(), NEHOGOrientationBinningKernel::run(), NESobel7x7VertKernel::run(), and SubTensorInfo::set_tensor_shape().
has_padding()
virtual bool has_padding () const pure virtual
Checks if the tensor has been allocated with padding or not.
Returns
True if padding is allocated in the tensor, otherwise false.
Implemented in TensorInfo, and SubTensorInfo.
Referenced by SubTensorInfo::has_padding(), NECropKernel::run(), and NECropKernel::validate().
is_resizable()
virtual bool is_resizable () const pure virtual
Flag indicating whether the size of the tensor can be changed.
Returns
True if the tensor size can be changed.
Implemented in TensorInfo, and SubTensorInfo.
Referenced by arm_compute::test::validation::DATA_TEST_CASE(), SubTensorInfo::extend_padding(), SubTensorInfo::is_resizable(), arm_compute::test::validation::TEST_CASE(), AccessWindowAutoPadding::update_padding_if_needed(), AccessWindowStatic::update_padding_if_needed(), AccessWindowRectangle::update_padding_if_needed(), AccessWindowStatic::update_window_if_needed(), and AccessWindowRectangle::update_window_if_needed().
num_channels()
virtual size_t num_channels () const pure virtual
The number of channels for each tensor element.
Returns
The number of channels for each tensor element
Implemented in TensorInfo, and SubTensorInfo.
Referenced by arm_compute::auto_init_if_empty(), CLReduceMean::configure(), NEReduceMean::configure(), CLFFTScaleKernel::configure(), CLFFT1D::configure(), GCFillBorderKernel::configure(), NEFFT1D::configure(), CLFFTDigitReverseKernel::configure(), CLFillBorderKernel::configure(), CLReductionOperationKernel::configure(), GCSoftmaxLayer::configure(), NEFFTDigitReverseKernel::configure(), NEHOGDetectorKernel::configure(), CLHOGDetectorKernel::configure(), CLHOGBlockNormalizationKernel::configure(), NEHOGBlockNormalizationKernel::configure(), ITensor::copy_from(), arm_compute::error_on_data_type_channel_not_in(), Accessor::num_channels(), SubTensorInfo::num_channels(), NEHOGBlockNormalizationKernel::run(), CLFFT1D::validate(), NEFFT1D::validate(), and CLReductionOperation::validate().
num_dimensions()
virtual size_t num_dimensions () const pure virtual
The number of dimensions of the tensor (rank)
Returns
The number of dimensions of the tensor (rank)
Implemented in TensorInfo, and SubTensorInfo.
Referenced by arm_compute::misc::shape_calculator::compute_mm_shape(), arm_compute::misc::shape_calculator::compute_stack_shape(), AccessWindowStatic::compute_valid_region(), AccessWindowRectangle::compute_valid_region(), GCGEMMMatrixAccumulateBiasesKernel::configure(), CLReduceMean::configure(), CLFlattenLayerKernel::configure(), NEReduceMean::configure(), CLPermuteKernel::configure(), CLGatherKernel::configure(), GCDepthwiseConvolutionLayer3x3Kernel::configure(), CPPFlipWeightsKernel::configure(), GCConvolutionLayerReshapeWeights::configure(), NEChannelShuffleLayerKernel::configure(), NEQuantizationLayerKernel::configure(), CPPPermuteKernel::configure(), CLGEMMLowpMatrixMultiplyKernel::configure(), CLGEMMMatrixMultiplyReshapedOnlyRHSKernel::configure(), CLGEMMLowpMatrixMultiplyReshapedOnlyRHSKernel::configure(), CPPUpsampleKernel::configure(), NEPermuteKernel::configure(), CLROIPoolingLayerKernel::configure(), GCGEMMMatrixMultiplyKernel::configure(), CLGEMMLowpOffsetContributionOutputStageKernel::configure(), NEGatherKernel::configure(), CLGEMMLowpMatrixMultiplyReshapedKernel::configure(), CLStridedSliceKernel::configure(), CLGEMMMatrixMultiplyReshapedKernel::configure(), CLGEMMMatrixMultiplyKernel::configure(), NEROIPoolingLayerKernel::configure(), CLGEMMLowpOffsetContributionKernel::configure(), GCWeightsReshapeKernel::configure(), NELaplacianReconstruct::configure(), CLLaplacianReconstruct::configure(), GCFullyConnectedLayer::configure(), CLGEMM::configure(), CLGaussianPyramidHalf::configure(), NEGaussianPyramidHalf::configure(), NEFullyConnectedLayer::configure(), CLFullyConnectedLayer::configure(), GCConvolutionLayer::configure(), CPPDetectionOutputLayer::configure(), CLGaussianPyramidOrb::configure(), NEGaussianPyramidOrb::configure(), ITensor::copy_from(), arm_compute::error_on_tensor_not_2d(), CLGEMMLowpMatrixMultiplyKernel::run(), NEGEMMLowpMatrixMultiplyKernel::run(), CLColorConvertKernel::run(), GCGEMMMatrixMultiplyKernel::run(), NEStackLayerKernel::run(), CLGEMMLowpMatrixMultiplyReshapedOnlyRHSKernel::run(), CLGEMMMatrixMultiplyReshapedOnlyRHSKernel::run(), CLGEMMMatrixMultiplyKernel::run(), NEGEMMLowpOffsetContributionKernel::run(), CLGEMMLowpMatrixMultiplyReshapedKernel::run(), CLGEMMMatrixMultiplyReshapedKernel::run(), AccessWindowStatic::update_window_if_needed(), AccessWindowRectangle::update_window_if_needed(), CLReduceMean::validate(), NESplit::validate(), CLSplit::validate(), NEReduceMean::validate(), CLConvertFullyConnectedWeightsKernel::validate(), NEConvolutionLayerReshapeWeights::validate(), CLCropKernel::validate(), NEConvertFullyConnectedWeightsKernel::validate(), CLSoftmaxLayer::validate(), NEGatherKernel::validate(), CLPadLayer::validate(), CLConvolutionLayerReshapeWeights::validate(), NESoftmaxLayer::validate(), NECropKernel::validate(), CLLocallyConnectedLayer::validate(), NELocallyConnectedLayer::validate(), NEDepthwiseConvolutionLayer3x3::validate(), CLGenerateProposalsLayer::validate(), NEFullyConnectedLayer::validate(), CLFullyConnectedLayer::validate(), NELSTMLayer::validate(), CLLSTMLayer::validate(), NEGEMMConvolutionLayer::validate(), and CLGEMMConvolutionLayer::validate().
offset_element_in_bytes()
virtual size_t offset_element_in_bytes (const Coordinates & pos) const pure virtual
The offset in bytes from the beginning of the memory allocation to access the element at position (x, y, z ...)
Parameters
[in] pos Vector with the coordinates of the element to access. The size of this vector must be equal to the number of dimensions of the tensor
Returns
Offset in bytes from the beginning of the memory allocation to access the element (x, y, z, ...)
Implemented in TensorInfo, and SubTensorInfo.
Referenced by arm_compute::utils::draw_detection_rectangle(), SubTensorInfo::offset_first_element_in_bytes(), ITensor::ptr_to_element(), and NEReorgLayerKernel::run().
offset_first_element_in_bytes()
virtual size_t offset_first_element_in_bytes () const pure virtual
The offset from the beginning of the memory allocation to the first element of the tensor.
This can be used to access efficiently elements in a 2D tensor
Returns
The offset in bytes to access the first element of the tensor.
Implemented in TensorInfo, and SubTensorInfo.
Referenced by NEDepthwiseConvolutionAssemblyDispatch::prepare(), NEWidthConcatenateLayerKernel::run(), NEHeightConcatenateLayerKernel::run(), NEDepthwiseConvolutionAssemblyDispatch::run(), AccessWindowStatic::update_window_if_needed(), and AccessWindowRectangle::update_window_if_needed().
padding()
virtual PaddingSize padding () const pure virtual
Padding of tensor.
Returns
Padding.
Implemented in TensorInfo, and SubTensorInfo.
Referenced by GCDepthwiseConvolutionLayer3x3Kernel::configure(), GCFillBorderKernel::configure(), CLFillBorderKernel::configure(), GCDirectConvolutionLayerKernel< kernel_size >::configure(), NEFillBorderKernel::configure(), GCTensorShiftKernel::configure(), GCIm2ColKernel::configure(), arm_compute::test::validation::DATA_TEST_CASE(), Accessor::padding(), SubTensorInfo::padding(), GCActivationLayerKernel::run(), GCDepthwiseConvolutionLayer3x3Kernel::run(), GCPoolingLayerKernel::run(), GCArithmeticAdditionKernel::run(), GCNormalizePlanarYUVLayerKernel::run(), GCTensorShiftKernel::run(), CLGEMMLowpMatrixMultiplyKernel::run(), CLGEMMReshapeLHSMatrixKernel::run(), CLGEMMLowpMatrixMultiplyReshapedOnlyRHSKernel::run(), CLGEMMInterleave4x4Kernel::run(), CLGEMMMatrixMultiplyReshapedOnlyRHSKernel::run(), GCBatchNormalizationLayerKernel::run(), CLGEMMMatrixMultiplyKernel::run(), CLGEMMLowpMatrixMultiplyReshapedKernel::run(), CLGEMMMatrixMultiplyReshapedKernel::run(), and AccessWindowRectangle::update_window_if_needed().
quantization_info()
virtual QuantizationInfo quantization_info () const pure virtual
Get the quantization settings (scale and offset) of the tensor.
Returns
A QuantizationInfo containing the scale and offset.
Implemented in TensorInfo, and SubTensorInfo.
Referenced by arm_compute::auto_init_if_empty(), CLScaleKernel::configure(), CLPoolingLayer::configure(), CLDepthwiseConvolutionLayer3x3NCHWKernel::configure(), CLDepthwiseConvolutionLayer3x3NHWCKernel::configure(), CLReduceMean::configure(), CLGEMMMatrixVectorMultiplyKernel::configure(), CLDequantizationLayerKernel::configure(), NEReduceMean::configure(), NEPoolingLayer::configure(), NEReductionOperation::configure(), CLQuantizationLayerKernel::configure(), CLActivationLayerKernel::configure(), CLComparisonKernel::configure(), CLPixelWiseMultiplicationKernel::configure(), CLPoolingLayerKernel::configure(), CLDirectConvolutionLayer::configure(), CLWidthConcatenate2TensorsKernel::configure(), CLNormalizePlanarYUVLayerKernel::configure(), CLWidthConcatenateLayerKernel::configure(), CLHeightConcatenateLayerKernel::configure(), CLRangeKernel::configure(), CLWidthConcatenate4TensorsKernel::configure(), CLDepthwiseIm2ColKernel::configure(), CLDepthConcatenateLayerKernel::configure(), CLDeconvolutionLayerUpsample::configure(), CLDirectConvolutionLayerKernel::configure(), CLDepthwiseConvolutionLayer3x3::configure(), CLGEMMLowpMatrixMultiplyCore::configure(), NEGEMMLowpMatrixMultiplyCore::configure(), CLDirectDeconvolutionLayer::configure(), CLGEMMDeconvolutionLayer::configure(), NEFullyConnectedLayer::configure(), CLFullyConnectedLayer::configure(), NEDeconvolutionLayer::configure(), NEGEMMConvolutionLayer::configure(), CLLogits1DMaxShiftExpSumKernel::configure(), CLGEMMConvolutionLayer::configure(), CLDepthwiseConvolutionLayer::configure(), CLLogits1DNormKernel::configure(), NEDepthwiseConvolutionLayer::configure(), arm_compute::graph::backends::detail::create_convolution_layer< GCConvolutionLayerFunctions, GCTargetInfo >(), arm_compute::graph::backends::detail::create_convolution_layer< NEConvolutionLayerFunctions, NETargetInfo >(), arm_compute::graph::backends::detail::create_depthwise_convolution_layer< GCDepthwiseConvolutionLayerFunctions, GCTargetInfo >(), arm_compute::error_on_mismatching_quantization_info(), Accessor::quantization_info(), SubTensorInfo::quantization_info(), NEQuantizationLayerKernel::run(), NEWidthConcatenateLayerKernel::run(), NEHeightConcatenateLayerKernel::run(), NEDepthConvertLayerKernel::run(), NEPixelWiseMultiplicationKernel::run(), arm_compute::helpers::tensor_info::tensors_have_different_quantization_info(), NESoftmaxLayer::validate(), CLGEMMLowpMatrixMultiplyCore::validate(), NEGEMMLowpMatrixMultiplyCore::validate(), NEGEMMConvolutionLayer::validate(), and CLGEMMConvolutionLayer::validate().
reset_padding()
virtual ITensorInfo& reset_padding () pure virtual
Resets the padding settings of the tensor.
Returns
Reference to this ITensorInfo object
Implemented in TensorInfo, and SubTensorInfo.
Referenced by SubTensorInfo::reset_padding().
set_data_layout()
virtual ITensorInfo& set_data_layout (const DataLayout & data_layout) pure virtual
Set the data layout of the tensor.
Parameters
[in] data_layout DataLayout containing the layout data information.
Returns
Reference to this ITensorInfo object
Implemented in TensorInfo, and SubTensorInfo.
Referenced by arm_compute::auto_init_if_empty(), CLUpsampleLayerKernel::configure(), NEUpsampleLayerKernel::configure(), NEFFTConvolutionLayer::configure(), NEDepthwiseConvolutionLayer::configure(), and SubTensorInfo::set_data_layout().
set_data_type()
virtual ITensorInfo& set_data_type (DataType data_type) pure virtual
Set the data type to the specified value.
Warning
This resets the format to UNKNOWN.
Parameters
[in] data_type The new data type.
Returns
Reference to this ITensorInfo object
Implemented in TensorInfo, and SubTensorInfo.
Referenced by arm_compute::auto_init_if_empty(), arm_compute::graph::backends::detail::create_convolution_layer< GCConvolutionLayerFunctions, GCTargetInfo >(), arm_compute::graph::backends::detail::create_depthwise_convolution_layer< GCDepthwiseConvolutionLayerFunctions, GCTargetInfo >(), SubTensorInfo::set_data_type(), and arm_compute::graph::backends::detail::validate_convolution_layer().
set_format()
virtual ITensorInfo& set_format (Format format) pure virtual
Set the format of an already initialized tensor.
Note
If the data type has already been configured (i.e. not UNKNOWN) it must match the new format. If data type hasn't been configured it will be based on the format.
Parameters
[in] format Single-plane format of the tensor.
Returns
Reference to this ITensorInfo object
Implemented in TensorInfo, and SubTensorInfo.
Referenced by arm_compute::test::validation::DATA_TEST_CASE(), and SubTensorInfo::set_format().
set_is_resizable()
virtual ITensorInfo& set_is_resizable (bool is_resizable) pure virtual
Set the flag whether the tensor size can be changed.
Parameters
[in] is_resizable Flag that marks the tensor if it can be changed or not.
Returns
Reference to this ITensorInfo object
Implemented in TensorInfo, and SubTensorInfo.
Referenced by SubTensorInfo::set_is_resizable().
set_num_channels()
virtual ITensorInfo& set_num_channels (int num_channels) pure virtual
Set the number of channels to the specified value.
Warning
This resets the format to UNKNOWN.
Parameters
[in] num_channels New number of channels.
Returns
Reference to this ITensorInfo object
Implemented in TensorInfo, and SubTensorInfo.
Referenced by arm_compute::auto_init_if_empty(), and SubTensorInfo::set_num_channels().
set_quantization_info()
virtual ITensorInfo& set_quantization_info (const QuantizationInfo & quantization_info) pure virtual
Set the quantization settings (scale and offset) of the tensor.
Parameters
[in] quantization_info QuantizationInfo containing the scale and offset
Returns
Reference to this ITensorInfo object
Implemented in TensorInfo, and SubTensorInfo.
Referenced by arm_compute::auto_init_if_empty(), NEConvolutionLayerReshapeWeights::configure(), CLConvolutionLayerReshapeWeights::configure(), arm_compute::test::validation::DATA_TEST_CASE(), and SubTensorInfo::set_quantization_info().
set_tensor_shape()
virtual ITensorInfo& set_tensor_shape (const TensorShape & shape) pure virtual
Set the shape of an already initialized tensor.
Warning
Changing the shape requires to recompute the strides and is therefore only possible if the tensor hasn't been allocated yet.
Parameters
[in] shape New tensor shape.
Returns
Reference to this ITensorInfo object
Implemented in TensorInfo, and SubTensorInfo.
Referenced by arm_compute::auto_init_if_empty(), NECropKernel::configure_output_shape(), SubTensorInfo::set_tensor_shape(), NEL2NormalizeLayer::validate(), and CLL2NormalizeLayer::validate().
set_valid_region()
virtual void set_valid_region (const ValidRegion & valid_region) pure virtual
Set the valid region of the tensor.
Parameters
[in] valid_region Valid region to set.
Implemented in TensorInfo, and SubTensorInfo.
Referenced by NEReshapeLayerKernel::configure(), CLGaussianPyramidHorKernel::configure(), CLReshapeLayerKernel::configure(), CLPermuteKernel::configure(), CLReorgLayerKernel::configure(), CLDepthwiseConvolutionLayerReshapeWeightsGenericKernel::configure(), CLHOGOrientationBinningKernel::configure(), CPPFlipWeightsKernel::configure(), NEGaussianPyramidHorKernel::configure(), CLDepthwiseVectorToTensorKernel::configure(), NEChannelShuffleLayerKernel::configure(), NEReorgLayerKernel::configure(), NEDepthwiseWeightsReshapeKernel::configure(), NEQuantizationLayerKernel::configure(), CLFuseBatchNormalizationKernel::configure(), NEHOGOrientationBinningKernel::configure(), CLDepthwiseIm2ColKernel::configure(), CPPPermuteKernel::configure(), CPPUpsampleKernel::configure(), NEDepthwiseVectorToTensorKernel::configure(), NEDepthConcatenateLayer::configure(), NEPermuteKernel::configure(), GCDropoutLayerKernel::configure(), NEFuseBatchNormalizationKernel::configure(), NEGatherKernel::configure(), NEDepthwiseIm2ColKernel::configure(), CLDepthConcatenateLayer::configure(), GCWeightsReshapeKernel::configure(), CLWeightsReshapeKernel::configure(), GCIm2ColKernel::configure(), CLGaussianPyramidVertKernel::configure(), NEGaussianPyramidVertKernel::configure(), CPPDetectionOutputLayer::configure(), ITensor::copy_from(), CPPDetectionOutputLayer::run(), SubTensorInfo::set_tensor_shape(), AccessWindowAutoPadding::set_valid_region(), AccessWindowStatic::set_valid_region(), and AccessWindowRectangle::set_valid_region().
strides_in_bytes()
virtual const Strides& strides_in_bytes () const pure virtual
The strides in bytes for accessing each dimension of the tensor.
Returns
Strides in bytes for each tensor dimension
Implemented in TensorInfo, and SubTensorInfo.
Referenced by CLROIPoolingLayerKernel::configure(), arm_compute::utils::draw_detection_rectangle(), NEDepthwiseConvolutionAssemblyDispatch::prepare(), NEHOGOrientationBinningKernel::run(), CLROIPoolingLayerKernel::run(), NENonMaximaSuppression3x3Kernel::run(), NEHOGDetectorKernel::run(), CLDepthConcatenateLayerKernel::run(), NEHeightConcatenateLayerKernel::run(), NEWidthConcatenateLayerKernel::run(), CLGEMMLowpMatrixMultiplyKernel::run(), NEGEMMLowpMatrixMultiplyKernel::run(), NEMinMaxLayerKernel::run(), GCCol2ImKernel::run(), CLROIAlignLayerKernel::run(), NEStackLayerKernel::run(), CLGEMMLowpMatrixMultiplyReshapedOnlyRHSKernel::run(), CLGEMMMatrixMultiplyReshapedOnlyRHSKernel::run(), CLWinogradInputTransformKernel::run(), CLDirectConvolutionLayerKernel::run(), CLGEMMMatrixMultiplyKernel::run(), CLGEMMLowpMatrixMultiplyReshapedKernel::run(), CLWinogradOutputTransformKernel::run(), CLGEMMMatrixMultiplyReshapedKernel::run(), NEWeightsReshapeKernel::run(), CLWeightsReshapeKernel::run(), CLIm2ColKernel::run(), NEDepthwiseConvolutionAssemblyDispatch::run(), NESobel7x7VertKernel::run(), NEHOGBlockNormalizationKernel::run(), NEEdgeNonMaxSuppressionKernel::run(), NEEdgeTraceKernel::run(), SubTensorInfo::strides_in_bytes(), AccessWindowStatic::update_window_if_needed(), and AccessWindowRectangle::update_window_if_needed().
tensor_shape()
virtual const TensorShape& tensor_shape () const pure virtual
Size for each dimension of the tensor.
Returns
A vector with the size for each dimension of the tensor
Implemented in TensorInfo, and SubTensorInfo.
Referenced by ImageAccessor::access_tensor(), ValidationInputAccessor::access_tensor(), arm_compute::auto_init_if_empty(), arm_compute::calculate_valid_region_scale(), arm_compute::utils::compare_tensor(), arm_compute::misc::shape_calculator::compute_batch_to_space_shape(), arm_compute::misc::shape_calculator::compute_col2im_shape(), arm_compute::misc::shape_calculator::compute_deconvolution_output_shape(), arm_compute::misc::shape_calculator::compute_deconvolution_upsampled_shape(), arm_compute::misc::shape_calculator::compute_deep_convolution_shape(), arm_compute::misc::shape_calculator::compute_depthwise_convolution_shape(), arm_compute::misc::shape_calculator::compute_flatten_shape(), arm_compute::misc::shape_calculator::compute_im2col_conv_shape(), arm_compute::misc::shape_calculator::compute_interleaved_shape(), arm_compute::misc::shape_calculator::compute_lhs_reshaped_shape(), arm_compute::misc::shape_calculator::compute_min_max_shape(), arm_compute::misc::shape_calculator::compute_mm_shape(), arm_compute::misc::shape_calculator::compute_output_stage_shape(), arm_compute::misc::shape_calculator::compute_permutation_output_shape(), arm_compute::misc::shape_calculator::compute_pool_shape(), arm_compute::misc::shape_calculator::compute_reductionB_shape(), arm_compute::misc::shape_calculator::compute_reorg_output_shape(), arm_compute::misc::shape_calculator::compute_rhs_reshaped_shape(), arm_compute::misc::shape_calculator::compute_rnn_shape(), arm_compute::misc::shape_calculator::compute_roi_align_shape(), arm_compute::misc::shape_calculator::compute_softmax_shape(), arm_compute::misc::shape_calculator::compute_space_to_batch_shape(), arm_compute::misc::shape_calculator::compute_split_shape(), arm_compute::misc::shape_calculator::compute_stack_shape(), arm_compute::misc::shape_calculator::compute_strided_slice_shape(), arm_compute::misc::shape_calculator::compute_transposed_shape(), arm_compute::misc::shape_calculator::compute_upsample_shape(), AccessWindowAutoPadding::compute_valid_region(), AccessWindowStatic::compute_valid_region(), arm_compute::misc::shape_calculator::compute_winograd_filter_transform_shape(), arm_compute::misc::shape_calculator::compute_winograd_input_transform_shape(), arm_compute::misc::shape_calculator::compute_winograd_output_transform_shape(), GCLogits1DMaxKernel::configure(), CLWarpPerspectiveKernel::configure(), CLElementWiseUnaryLayerKernel::configure(), NEFloorKernel::configure(), CLTransposeKernel::configure(), NEReshapeLayerKernel::configure(), CLWarpAffineKernel::configure(), GCTransposeKernel::configure(), NEBox3x3Kernel::configure(), GCScaleKernel::configure(), NEAccumulateKernel::configure(), CLReduceMean::configure(), NEGEMMLowpAssemblyMatrixMultiplyCore::configure(), NEReduceMean::configure(), CLDequantizationLayerKernel::configure(), CLFloorKernel::configure(), CLReshapeLayerKernel::configure(), CLCopyKernel::configure(), CLGaussianPyramidHorKernel::configure(), NEUnstack::configure(), CLPermuteKernel::configure(), CLQuantizationLayerKernel::configure(), CLRemapKernel::configure(), CLReorgLayerKernel::configure(), CLTileKernel::configure(), NETileKernel::configure(), CLDepthConvertLayerKernel::configure(), CLUnstack::configure(), CLDeconvolutionLayerUpsampleKernel::configure(), CLDepthwiseConvolutionLayerReshapeWeightsGenericKernel::configure(), GCActivationLayerKernel::configure(), CLFFT1D::configure(), GCDepthwiseConvolutionLayer3x3Kernel::configure(), GCPixelWiseMultiplicationKernel::configure(), CLHOGOrientationBinningKernel::configure(), NEPadLayer::configure(), CLPoolingLayerKernel::configure(), NEGaussianPyramidHorKernel::configure(), INEWarpKernel::configure(), CPPFlipWeightsKernel::configure(), GCFillBorderKernel::configure(), CLFillBorderKernel::configure(), NEFFT1D::configure(), NEHOGDescriptor::configure(), NEChannelShuffleLayerKernel::configure(), CLChannelExtractKernel::configure(), CLDepthwiseVectorToTensorKernel::configure(), GCNormalizationLayer::configure(), NEBitwiseNotKernel::configure(), NEBitwiseXorKernel::configure(), NEBitwiseOrKernel::configure(), NEDepthwiseWeightsReshapeKernel::configure(), NEReorgLayerKernel::configure(), CPPTopKVKernel::configure(), GCArithmeticAdditionKernel::configure(), CLHOGDescriptor::configure(), GCGEMMTranspose1xWKernel::configure(), CLReductionOperation::configure(), NEBitwiseAndKernel::configure(), NEHOGGradient::configure(), NENormalizationLayer::configure(), CLChannelCombineKernel::configure(), CLSelectKernel::configure(), NEQuantizationLayerKernel::configure(), GCSoftmaxLayer::configure(), CLFuseBatchNormalizationKernel::configure(), NEGaussian5x5::configure(), NEColorConvertKernel::configure(), NEHOGOrientationBinningKernel::configure(), NERemapKernel::configure(), NETransposeKernel::configure(), CPPPermuteKernel::configure(), GCDepthConcatenateLayerKernel::configure(), CLDepthwiseIm2ColKernel::configure(), GCDirectConvolutionLayerKernel< kernel_size >::configure(), CLHOGGradient::configure(), NESpaceToBatchLayer::configure(), NEDepthwiseVectorToTensorKernel::configure(), CLWinogradInputTransformKernel::configure(), CPPUpsampleKernel::configure(), CLGaussian5x5::configure(), CLPadLayer::configure(), NEAbsoluteDifferenceKernel::configure(), NESobel5x5::configure(), NESobel7x7::configure(), NEChannelExtractKernel::configure(), NEFillInnerBorderKernel::configure(), NEPermuteKernel::configure(), CLSoftmaxLayer::configure(), CLSpaceToBatchLayer::configure(), NEFillBorderKernel::configure(), GCDropoutLayerKernel::configure(), GCLogits1DShiftExpSumKernel::configure(), NEGradientKernel::configure(), CLGEMMLowpOffsetContributionOutputStageKernel::configure(), CLSobel7x7::configure(), NEChannelCombineKernel::configure(), NEDepthConvertLayerKernel::configure(), NEDepthwiseIm2ColKernel::configure(), NEGatherKernel::configure(), CLStridedSliceKernel::configure(), CLColorConvertKernel::configure(), NESelectKernel::configure(), CLSobel5x5::configure(), NEFastCorners::configure(), CLWinogradOutputTransformKernel::configure(), NEGEMMLowpMatrixMultiplyKernel::configure(), NEGEMMMatrixMultiplyKernel::configure(), NEROIPoolingLayerKernel::configure(), CLCannyEdge::configure(), GCGEMMInterleave4x4Kernel::configure(), NECropResize::configure(), NEStridedSliceKernel::configure(), CLGEMMLowpOffsetContributionKernel::configure(), CLFastCorners::configure(), NEConvolutionKernel< matrix_size >::configure(), NESoftmaxLayer::configure(), GCTensorShiftKernel::configure(), NEGEMMLowpOffsetContributionKernel::configure(), CLCropResize::configure(), NEGEMM::configure(), CLWinogradConvolutionLayer::configure(), NECannyEdge::configure(), NELaplacianReconstruct::configure(), CLLaplacianReconstruct::configure(), GCWeightsReshapeKernel::configure(), GCCol2ImKernel::configure(), CLWeightsReshapeKernel::configure(), GCIm2ColKernel::configure(), CLHarrisCorners::configure(), NEAccumulateWeightedKernel::configure(), NELSTMLayer::configure(), NEHarrisCorners::configure(), CLHOGMultiDetection::configure(), NEHOGMultiDetection::configure(), GCFullyConnectedLayer::configure(), NEGEMMLowpMatrixMultiplyCore::configure(), CLConvolutionSquare< matrix_size >::configure(), CLFFTConvolutionLayer::configure(), NEConvolutionSquare< matrix_size >::configure(), NEFFTConvolutionLayer::configure(), CLGaussianPyramidVertKernel::configure(), CLLSTMLayer::configure(), NEGEMMLowpOffsetContributionOutputStageKernel::configure(), CLHOGBlockNormalizationKernel::configure(), NEGaussianPyramidVertKernel::configure(), GCLogits1DNormKernel::configure(), NEFullyConnectedLayer::configure(), CLFullyConnectedLayer::configure(), GCConvolutionLayer::configure(), CPPDetectionOutputLayer::configure(), NESeparableConvolutionHorKernel< matrix_size >::configure(), NEGEMMConvolutionLayer::configure(), NEHOGBlockNormalizationKernel::configure(), CLLogits1DMaxShiftExpSumKernel::configure(), NEAccumulateSquaredKernel::configure(), CLDepthwiseConvolutionLayer::configure(), NESeparableConvolutionVertKernel< matrix_size >::configure(), NEEdgeTraceKernel::configure(), NEDepthwiseConvolutionLayer::configure(), NEConvolutionRectangleKernel::configure(), NECropKernel::configure_output_shape(), ITensor::copy_from(), arm_compute::graph::backends::detail::create_concatenate_layer< GCDepthConcatenateLayer, GCTargetInfo >(), arm_compute::graph::backends::detail::create_convolution_layer< GCConvolutionLayerFunctions, GCTargetInfo >(), arm_compute::graph::backends::detail::create_convolution_layer< NEConvolutionLayerFunctions, NETargetInfo >(), arm_compute::graph::backends::detail::create_depthwise_convolution_layer< GCDepthwiseConvolutionLayerFunctions, GCTargetInfo >(), arm_compute::graph::backends::detail::create_detection_output_layer< CPPDetectionOutputLayer, CLTargetInfo >(), arm_compute::graph::backends::detail::create_normalization_layer< NENormalizationLayer, NETargetInfo >(), arm_compute::extract_bounding_boxes_from_tensor(), arm_compute::extract_scores_from_tensor(), arm_compute::misc::shape_calculator::extract_shape(), NEDepthwiseConvolutionAssemblyDispatch::is_optimized_supported(), Accessor::num_elements(), CaffePreproccessor::preprocess(), TFPreproccessor::preprocess(), CLMinMaxLayerKernel::reset(), NEMinMaxLayerKernel::reset(), CLElementwiseOperationKernel::run(), GCDepthwiseConvolutionLayer3x3Kernel::run(), CLFlattenLayerKernel::run(), CLLocallyConnectedMatrixMultiplyKernel::run(), NETileKernel::run(), CLPoolingLayerKernel::run(), CLComparisonKernel::run(), CLDepthwiseConvolutionLayerReshapeWeightsGenericKernel::run(), NEFlattenLayerKernel::run(), NEReorgLayerKernel::run(), CLPixelWiseMultiplicationKernel::run(), CLCropKernel::run(), CLStackLayerKernel::run(), CLDirectConvolutionLayerOutputStageKernel::run(), NEMinMaxLayerKernel::run(), GCWeightsReshapeKernel::run(), NEStackLayerKernel::run(), NEPixelWiseMultiplicationKernel::run(), CLCol2ImKernel::run(), CLDirectConvolutionLayerKernel::run(), CLWinogradFilterTransformKernel::run(), NEGEMMLowpOffsetContributionKernel::run(), CLWinogradOutputTransformKernel::run(), CLWeightsReshapeKernel::run(), CLIm2ColKernel::run(), CLComplexPixelWiseMultiplicationKernel::run(), NEComplexPixelWiseMultiplicationKernel::run(), SubTensorInfo::set_tensor_shape(), SubTensorInfo::set_valid_region(), Accessor::shape(), AccessWindowStatic::update_padding_if_needed(), AccessWindowStatic::update_window_if_needed(), AccessWindowRectangle::update_window_if_needed(), CLReduceMean::validate(), NEUnstack::validate(), NEReduceMean::validate(), CLUnstack::validate(), CLFFT1D::validate(), CLRNNLayer::validate(), NEFFT1D::validate(), NEL2NormalizeLayer::validate(), CLL2NormalizeLayer::validate(), CLReductionOperation::validate(), NEPadLayer::validate(), NEConcatenateLayer::validate(), CLCropKernel::validate(), CLConcatenateLayer::validate(), CLSoftmaxLayer::validate(), NEGatherKernel::validate(), CLPadLayer::validate(), NERNNLayer::validate(), NESelectKernel::validate(), NEDepthwiseConvolutionAssemblyDispatch::validate(), NESoftmaxLayer::validate(), NECropKernel::validate(), NECropResize::validate(), CLCropResize::validate(), CLWinogradConvolutionLayer::validate(), CLDepthwiseConvolutionLayer3x3::validate(), NEGEMMLowpMatrixMultiplyCore::validate(), CLFFTConvolutionLayer::validate(), NEFFTConvolutionLayer::validate(), CLGEMMDeconvolutionLayer::validate(), NEDeconvolutionLayer::validate(), NEFullyConnectedLayer::validate(), CLFullyConnectedLayer::validate(), NEGEMMConvolutionLayer::validate(), CLGEMMConvolutionLayer::validate(), CLDepthwiseConvolutionLayer::validate(), and NEDepthwiseConvolutionLayer::validate().
total_size()
virtual size_t total_size () const pure virtual
Returns the total size of the tensor in bytes.
Returns
Total size of the tensor in bytes.
Implemented in TensorInfo, and SubTensorInfo.
Referenced by CLROIPoolingLayerKernel::configure(), NEROIPoolingLayerKernel::configure(), CLGEMMConvolutionLayer::configure(), SubTensorInfo::extend_padding(), CPPUpsampleKernel::run(), NECannyEdge::run(), CLWinogradOutputTransformKernel::run(), NELogits1DSoftmaxKernel::run(), NELSTMLayer::run(), Accessor::size(), SubTensorInfo::total_size(), AccessWindowStatic::update_window_if_needed(), AccessWindowRectangle::update_window_if_needed(), NEFFT2D::validate(), CLFFT2D::validate(), CLReduceMean::validate(), NEReduceMean::validate(), CLFFT1D::validate(), NEFFT1D::validate(), CLConvertFullyConnectedWeightsKernel::validate(), NEUpsampleLayerKernel::validate(), NEConvolutionLayerReshapeWeights::validate(), NEPadLayer::validate(), CLCropKernel::validate(), CLConcatenateLayer::validate(), NEConcatenateLayer::validate(), NEConvertFullyConnectedWeightsKernel::validate(), NEGatherKernel::validate(), CLPadLayer::validate(), NESelectKernel::validate(), CLConvolutionLayerReshapeWeights::validate(), NEDepthwiseConvolutionAssemblyDispatch::validate(), NECropKernel::validate(), NEGEMM::validate(), NECropResize::validate(), CLCropResize::validate(), CLGEMMLowpMatrixMultiplyCore::validate(), CLGenerateProposalsLayer::validate(), NEFFTConvolutionLayer::validate(), CLFFTConvolutionLayer::validate(), and CLGEMMConvolutionLayer::validate().
valid_region()
virtual ValidRegion valid_region () const pure virtual
Valid region of the tensor.
All elements in the valid region have defined values, i.e. are not undefined.
Returns
The valid region.
Implemented in TensorInfo, and SubTensorInfo.
Referenced by arm_compute::calculate_valid_region_scale(), CLIntegralImageHorKernel::configure(), CLDilateKernel::configure(), CLMedian3x3Kernel::configure(), CLErodeKernel::configure(), CLBox3x3Kernel::configure(), CLGaussian3x3Kernel::configure(), CLNonMaximaSuppression3x3Kernel::configure(), NEIntegralImageKernel::configure(), GCTransposeKernel::configure(), NEDilateKernel::configure(), NEErodeKernel::configure(), NEGaussian3x3Kernel::configure(), NEMedian3x3Kernel::configure(), GCScaleKernel::configure(), NEBox3x3Kernel::configure(), NELogits1DMaxKernel::configure(), NEGaussian5x5HorKernel::configure(), CLNonLinearFilterKernel::configure(), CLGradientKernel::configure(), CLBitwiseOrKernel::configure(), CLBitwiseAndKernel::configure(), CLBitwiseXorKernel::configure(), CLSobel3x3Kernel::configure(), CLDerivativeKernel::configure(), ICLSimpleKernel::configure(), IGCSimpleKernel::configure(), GCActivationLayerKernel::configure(), GCPixelWiseMultiplicationKernel::configure(), CLSobel5x5HorKernel::configure(), CLSobel7x7HorKernel::configure(), CLFillBorderKernel::configure(), GCFillBorderKernel::configure(), GCNormalizationLayerKernel::configure(), INEWarpKernel::configure(), GCGEMMMatrixAdditionKernel::configure(), CLChannelExtractKernel::configure(), GCAbsoluteDifferenceKernel::configure(), CLAbsoluteDifferenceKernel::configure(), NEBitwiseNotKernel::configure(), CLMagnitudePhaseKernel::configure(), CLColorConvertKernel::configure(), NEBitwiseAndKernel::configure(), NEBitwiseXorKernel::configure(), NEBitwiseOrKernel::configure(), NEDerivativeKernel::configure(), CLChannelCombineKernel::configure(), CLFuseBatchNormalizationKernel::configure(), NEColorConvertKernel::configure(), NEFastCornersKernel::configure(), CLConvolutionKernel< matrix_size >::configure(), NEThresholdKernel::configure(), NENonLinearFilterKernel::configure(), NEAbsoluteDifferenceKernel::configure(), CLIntegralImageVertKernel::configure(), NEChannelExtractKernel::configure(), NEMagnitudePhaseKernel< mag_type, phase_type >::configure(), NENonMaximaSuppression3x3Kernel::configure(), NESobel7x7HorKernel::configure(), NESobel5x5HorKernel::configure(), NEFuseBatchNormalizationKernel::configure(), NEGradientKernel::configure(), GCLogits1DShiftExpSumKernel::configure(), NEChannelCombineKernel::configure(), NEHOGDetectorKernel::configure(), NESelectKernel::configure(), CLHarrisScoreKernel::configure(), CLFastCornersKernel::configure(), NEROIPoolingLayerKernel::configure(), CLHOGDetectorKernel::configure(), GCGEMMInterleave4x4Kernel::configure(), NEConvolutionKernel< matrix_size >::configure(), NEScharr3x3Kernel::configure(), NESobel3x3Kernel::configure(), CLScharr3x3Kernel::configure(), NEGaussian5x5VertKernel::configure(), GCCol2ImKernel::configure(), CLEdgeNonMaxSuppressionKernel::configure(), NEHarrisScoreKernel< block_size >::configure(), CLSeparableConvolutionHorKernel< matrix_size >::configure(), GCLogits1DNormKernel::configure(), CLSobel7x7VertKernel::configure(), CLSobel5x5VertKernel::configure(), CLCopyToArrayKernel::configure(), NESobel5x5VertKernel::configure(), NESobel7x7VertKernel::configure(), NESeparableConvolutionHorKernel< matrix_size >::configure(), NEEdgeNonMaxSuppressionKernel::configure(), CLSeparableConvolutionVertKernel< matrix_size >::configure(), CLEdgeTraceKernel::configure(), CLLKTrackerStage0Kernel::configure(), NESeparableConvolutionVertKernel< matrix_size >::configure(), CLConvolutionRectangleKernel::configure(), CLLKTrackerStage1Kernel::configure(), NEEdgeTraceKernel::configure(), NEConvolutionRectangleKernel::configure(), ITensor::copy_from(), arm_compute::test::validation::DATA_TEST_CASE(), NEMemsetKernel::run(), NELogits1DSoftmaxKernel::run(), and SubTensorInfo::set_valid_region().
The documentation for this class was generated from the following file:
arm_compute/core/ITensorInfo.h