Compute Library: ChannelShuffleLayer Class Reference
ChannelShuffleLayer Class Reference final
Channel Shuffle Layer.
#include <Layers.h>
Public Member Functions
ChannelShuffleLayer (unsigned int num_groups)
Construct a Channel Shuffle layer.
NodeID create_layer (IStream &s) override
Create layer and add to the given stream.
Public Member Functions inherited from ILayer
virtual ~ILayer ()=default
Default destructor.
ILayer & set_name (std::string name)
Sets the name of the layer.
const std::string & name () const
Layer name accessor.
Detailed Description
Channel Shuffle Layer.
Definition at line 199 of file Layers.h.
Constructor & Destructor Documentation
ChannelShuffleLayer()
ChannelShuffleLayer (unsigned int num_groups) inline
Construct a Channel Shuffle layer.
Parameters
[in] num_groups Number of groups
Definition at line 206 of file Layers.h.
         : _num_groups(num_groups)
     {
     }
Member Function Documentation
create_layer()
NodeID create_layer (IStream & s) inline override virtual
Create layer and add to the given stream.
Parameters
[in] s Stream to add layer to.
Returns
ID of the created node.
Implements ILayer.
Definition at line 211 of file Layers.h.
     {
         NodeParams  common_params = { name(), s.hints().target_hint };
         NodeIdxPair input         = { s.tail_node(), 0 };
         return GraphBuilder::add_channel_shuffle_node(s.graph(), common_params, input, _num_groups);
     }
References GraphBuilder::add_channel_shuffle_node(), IStream::graph(), IStream::hints(), ILayer::name(), IStream::tail_node(), and StreamHints::target_hint.
The documentation for this class was generated from the following file:
arm_compute/graph/frontend/Layers.h