Compute Library: NEMinMaxLocationKernel Class Reference
NEMinMaxLocationKernel Class Reference
Interface for the kernel to find min max locations of an image.
#include <NEMinMaxLocationKernel.h>
Public Member Functions
const char * name () const override
Name of the kernel.
NEMinMaxLocationKernel ()
Default constructor.
NEMinMaxLocationKernel (const NEMinMaxLocationKernel &)=delete
Prevent instances of this class from being copied (As this class contains pointers)
NEMinMaxLocationKernel & operator= (const NEMinMaxLocationKernel &)=delete
Prevent instances of this class from being copied (As this class contains pointers)
NEMinMaxLocationKernel (NEMinMaxLocationKernel &&)=default
Allow instances of this class to be moved.
NEMinMaxLocationKernel & operator= (NEMinMaxLocationKernel &&)=default
Allow instances of this class to be moved.
~NEMinMaxLocationKernel ()=default
Default destructor.
void configure (const IImage *input, void *min, void *max, ICoordinates2DArray *min_loc=nullptr, ICoordinates2DArray *max_loc=nullptr, uint32_t *min_count=nullptr, uint32_t *max_count=nullptr)
Initialise the kernel's input and outputs.
void run (const Window &window, const ThreadInfo &info) override
Execute the kernel on the passed window.
bool is_parallelisable () const override
Indicates whether or not the kernel is parallelisable.
Public Member Functions inherited from ICPPKernel
virtual ~ICPPKernel ()=default
Default destructor.
Public Member Functions inherited from IKernel
IKernel ()
Constructor.
virtual ~IKernel ()=default
Destructor.
virtual BorderSize border_size () const
The size of the border for that kernel.
const Window & window () const
The maximum window the kernel can be executed on.
Detailed Description
Interface for the kernel to find min max locations of an image.
Definition at line 106 of file NEMinMaxLocationKernel.h.
Constructor & Destructor Documentation
NEMinMaxLocationKernel() [1/3]
NEMinMaxLocationKernel ()
Default constructor.
Definition at line 313 of file NEMinMaxLocationKernel.cpp.
     : _func(nullptr), _input(nullptr), _min(nullptr), _max(nullptr), _min_count(nullptr), _max_count(nullptr), _min_loc(nullptr), _max_loc(nullptr)
 {
 }
NEMinMaxLocationKernel() [2/3]
NEMinMaxLocationKernel (const NEMinMaxLocationKernel &) delete
Prevent instances of this class from being copied (As this class contains pointers)
NEMinMaxLocationKernel() [3/3]
NEMinMaxLocationKernel (NEMinMaxLocationKernel &&) default
Allow instances of this class to be moved.
~NEMinMaxLocationKernel()
~NEMinMaxLocationKernel () default
Default destructor.
Member Function Documentation
configure()
void configure (const IImage * input, void * min, void * max, ICoordinates2DArray * min_loc = nullptr, ICoordinates2DArray * max_loc = nullptr, uint32_t * min_count = nullptr, uint32_t * max_count = nullptr)
Initialise the kernel's input and outputs.
Parameters
[in] input Input Image. Data types supported: U8/S16/F32.
[out] min Minimum value of image. Data types supported: S32 if input type is U8/S16, F32 if input type is F32.
[out] max Maximum value of image. Data types supported: S32 if input type is U8/S16, F32 if input type is F32.
[out] min_loc Array of minimum value locations.
[out] max_loc Array of maximum value locations.
[out] min_count Number of minimum value encounters.
[out] max_count Number of maximum value encounters.
Definition at line 335 of file NEMinMaxLocationKernel.cpp.
 {
     ARM_COMPUTE_ERROR_ON_TENSOR_NOT_2D(input);
     ARM_COMPUTE_ERROR_ON_DATA_TYPE_CHANNEL_NOT_IN(input, 1, DataType::U8, DataType::S16, DataType::F32);
     ARM_COMPUTE_ERROR_ON(nullptr == min);
     ARM_COMPUTE_ERROR_ON(nullptr == max);
     _input     = input;
     _min       = min;
     _max       = max;
     _min_count = min_count;
     _max_count = max_count;
     _min_loc   = min_loc;
     _max_loc   = max_loc;
     unsigned int count_min = (nullptr != min_count ? 1 : 0);
     unsigned int count_max = (nullptr != max_count ? 1 : 0);
     unsigned int loc_min   = (nullptr != min_loc ? 1 : 0);
     unsigned int loc_max   = (nullptr != max_loc ? 1 : 0);
     unsigned int table_idx = (count_min << 3) | (count_max << 2) | (loc_min << 1) | loc_max;
     switch(input->info()->data_type())
     {
         case DataType::U8:
             _func = create_func_table<uint8_t, utility::index_sequence_t<16>>::func_table[table_idx];
             break;
         case DataType::S16:
             _func = create_func_table<int16_t, utility::index_sequence_t<16>>::func_table[table_idx];
             break;
         case DataType::F32:
             _func = create_func_table<float, utility::index_sequence_t<16>>::func_table[table_idx];
             break;
         default:
             ARM_COMPUTE_ERROR("Unsupported data type");
             break;
     }
     constexpr unsigned int num_elems_processed_per_iteration = 1;
     // Configure kernel window
     Window win = calculate_max_window(*input->info(), Steps(num_elems_processed_per_iteration));
     update_window_and_padding(win, AccessWindowHorizontal(input->info(), 0, num_elems_processed_per_iteration));
     INEKernel::configure(win);
 }
References ARM_COMPUTE_ERROR, ARM_COMPUTE_ERROR_ON, ARM_COMPUTE_ERROR_ON_DATA_TYPE_CHANNEL_NOT_IN, ARM_COMPUTE_ERROR_ON_TENSOR_NOT_2D, arm_compute::calculate_max_window(), ITensorInfo::data_type(), arm_compute::F32, ITensor::info(), arm_compute::S16, arm_compute::U8, and arm_compute::update_window_and_padding().
Referenced by NEMinMaxLocation::configure().
is_parallelisable()
bool is_parallelisable () const override virtual
Indicates whether or not the kernel is parallelisable.
If the kernel is parallelisable then the window returned by window() can be split into sub-windows which can then be run in parallel.
If the kernel is not parallelisable then only the window returned by window() can be passed to run()
Returns
True if the kernel is parallelisable
Reimplemented from IKernel.
Definition at line 318 of file NEMinMaxLocationKernel.cpp.
 {
     return false;
 }
name()
const char* name () const inline override virtual
Name of the kernel.
Returns
Kernel name
Implements ICPPKernel.
Definition at line 109 of file NEMinMaxLocationKernel.h.
     {
         return "NEMinMaxLocationKernel";
     }
operator=() [1/2]
NEMinMaxLocationKernel& operator= (const NEMinMaxLocationKernel &) delete
Prevent instances of this class from being copied (As this class contains pointers)
operator=() [2/2]
NEMinMaxLocationKernel& operator= (NEMinMaxLocationKernel &&) default
Allow instances of this class to be moved.
run()
void run (const Window & window, const ThreadInfo & info) override virtual
Execute the kernel on the passed window.
Warning
If is_parallelisable() returns false then the passed window must be equal to window()
Note
The window has to be a region within the window returned by the window() method
The width of the window has to be a multiple of num_elems_processed_per_iteration().
Parameters
[in] window Region on which to execute the kernel. (Must be a region of the window returned by window())
[in] info Info about executing thread and CPU.
Implements ICPPKernel.
Definition at line 385 of file NEMinMaxLocationKernel.cpp.
 {
     ARM_COMPUTE_UNUSED(info);
     ARM_COMPUTE_ERROR_ON_UNCONFIGURED_KERNEL(this);
     ARM_COMPUTE_ERROR_ON_INVALID_SUBWINDOW(INEKernel::window(), window);
     ARM_COMPUTE_ERROR_ON(_func == nullptr);
     (this->*_func)(window);
 }
References ARM_COMPUTE_ERROR_ON, ARM_COMPUTE_ERROR_ON_INVALID_SUBWINDOW, ARM_COMPUTE_ERROR_ON_UNCONFIGURED_KERNEL, ARM_COMPUTE_UNUSED, arm_compute::test::validation::info, and IKernel::window().
The documentation for this class was generated from the following files:
arm_compute/core/NEON/kernels/NEMinMaxLocationKernel.h
src/core/NEON/kernels/NEMinMaxLocationKernel.cpp