Compute Library: src/core/CL/cl_kernels/magnitude_phase.cl File Reference
magnitude_phase.cl File Reference
#include "helpers.h"
Macros
#define MAGNITUDE_OP(x, y) magnitude_l1((x), (y))
#define PHASE_OP(x, y) phase_unsigned((x), (y))
Functions
DATA_TYPE16 magnitude_l1 (DATA_TYPE16 a, DATA_TYPE16 b)
Calculates L1 normalization between two inputs.
DATA_TYPE16 magnitude_l2 (int16 a, int16 b)
Calculates L2 normalization between two inputs.
uchar16 phase_unsigned (DATA_TYPE16 a, DATA_TYPE16 b)
Calculates unsigned phase between two inputs.
uchar16 phase_signed (DATA_TYPE16 a, DATA_TYPE16 b)
Calculates signed phase between two inputs.
__kernel void magnitude_phase (__global uchar *gx_ptr, uint gx_stride_x, uint gx_step_x, uint gx_stride_y, uint gx_step_y, uint gx_offset_first_element_in_bytes, __global uchar *gy_ptr, uint gy_stride_x, uint gy_step_x, uint gy_stride_y, uint gy_step_y, uint gy_offset_first_element_in_bytes, __global uchar *magnitude_ptr, uint magnitude_stride_x, uint magnitude_step_x, uint magnitude_stride_y, uint magnitude_step_y, uint magnitude_offset_first_element_in_bytes, __global uchar *phase_ptr, uint phase_stride_x, uint phase_step_x, uint phase_stride_y, uint phase_step_y, uint phase_offset_first_element_in_bytes)
Calculate the magnitude and phase of given the gradients of an image.
Macro Definition Documentation
MAGNITUDE_OP
#define MAGNITUDE_OP (x, y) magnitude_l1((x), (y))
Definition at line 81 of file magnitude_phase.cl.
PHASE_OP
#define PHASE_OP (x, y) phase_unsigned((x), (y))
Definition at line 89 of file magnitude_phase.cl.
Function Documentation
magnitude_l1()
DATA_TYPE16 magnitude_l1 (DATA_TYPE16 a, DATA_TYPE16 b) inline
Calculates L1 normalization between two inputs.
Parameters
[in] a First input. Supported data types: S16, S32
[in] b Second input. Supported data types: S16, S32
Returns
L1 normalization magnitude result. Supported data types: S16, S32
Definition at line 33 of file magnitude_phase.cl.
 {
     return CONVERT_SAT(add_sat(abs(a), abs(b)), VEC_DATA_TYPE(DATA_TYPE, 16));
 }
References arm_compute::wrapper::add_sat(), arm_compute::test::validation::b, CONVERT_SAT, DATA_TYPE, and VEC_DATA_TYPE.
magnitude_l2()
DATA_TYPE16 magnitude_l2 (int16 a, int16 b) inline
Calculates L2 normalization between two inputs.
Parameters
[in] a First input. Supported data types: S16, S32
[in] b Second input. Supported data types: S16, S32
Returns
L2 normalization magnitude result. Supported data types: S16, S32
Definition at line 45 of file magnitude_phase.cl.
 {
     return CONVERT_SAT((sqrt(convert_float16((convert_uint16(a * a) + convert_uint16(b * b)))) + 0.5f),
                        VEC_DATA_TYPE(DATA_TYPE, 16));
 }
References arm_compute::test::validation::b, CONVERT_SAT, DATA_TYPE, and VEC_DATA_TYPE.
magnitude_phase()
__kernel void magnitude_phase (__global uchar * gx_ptr, uint gx_stride_x, uint gx_step_x, uint gx_stride_y, uint gx_step_y, uint gx_offset_first_element_in_bytes, __global uchar * gy_ptr, uint gy_stride_x, uint gy_step_x, uint gy_stride_y, uint gy_step_y, uint gy_offset_first_element_in_bytes, __global uchar * magnitude_ptr, uint magnitude_stride_x, uint magnitude_step_x, uint magnitude_stride_y, uint magnitude_step_y, uint magnitude_offset_first_element_in_bytes, __global uchar * phase_ptr, uint phase_stride_x, uint phase_step_x, uint phase_stride_y, uint phase_step_y, uint phase_offset_first_element_in_bytes)
Calculate the magnitude and phase of given the gradients of an image.
Note
Magnitude calculation supported: L1 normalization(type = 1) and L2 normalization(type = 2).
Phase calculation supported: Unsigned(type = 1) [0,128] and Signed(type = 2) [0,256).
Attention
To enable phase calculation -DPHASE="phase_calculation_type_id" must be provided at compile time. eg -DPHASE=1
To enable magnitude calculation -DMAGNITUDE="magnitude_calculation_type_id" must be provided at compile time. eg -DMAGNITUDE=1
Datatype of the two inputs is passed at compile time using -DDATA_TYPE. e.g -DDATA_TYPE=short. Supported data_types are: short and int
Parameters
[in] gx_ptr Pointer to the first source image (gradient X). Supported data types: S16, S32
[in] gx_stride_x Stride of the source image in X dimension (in bytes)
[in] gx_step_x gx_stride_x * number of elements along X processed per workitem(in bytes)
[in] gx_stride_y Stride of the source image in Y dimension (in bytes)
[in] gx_step_y gx_stride_y * number of elements along Y processed per workitem(in bytes)
[in] gx_offset_first_element_in_bytes The offset of the first element in the source image
[in] gy_ptr Pointer to the second source image (gradient Y) . Supported data types: S16, S32
[in] gy_stride_x Stride of the destination image in X dimension (in bytes)
[in] gy_step_x gy_stride_x * number of elements along X processed per workitem(in bytes)
[in] gy_stride_y Stride of the destination image in Y dimension (in bytes)
[in] gy_step_y gy_stride_y * number of elements along Y processed per workitem(in bytes)
[in] gy_offset_first_element_in_bytes The offset of the first element in the destination image
[out] magnitude_ptr Pointer to the magnitude destination image. Supported data types: S16, S32
[in] magnitude_stride_x Stride of the source image in X dimension (in bytes)
[in] magnitude_step_x magnitude_stride_x * number of elements along X processed per workitem(in bytes)
[in] magnitude_stride_y Stride of the source image in Y dimension (in bytes)
[in] magnitude_step_y magnitude_stride_y * number of elements along Y processed per workitem(in bytes)
[in] magnitude_offset_first_element_in_bytes The offset of the first element in the source image
[out] phase_ptr Pointer to the phase destination image. Supported data types: U8
[in] phase_stride_x Stride of the destination image in X dimension (in bytes)
[in] phase_step_x phase_stride_x * number of elements along X processed per workitem(in bytes)
[in] phase_stride_y Stride of the destination image in Y dimension (in bytes)
[in] phase_step_y phase_stride_y * number of elements along Y processed per workitem(in bytes)
[in] phase_offset_first_element_in_bytes The offset of the first element in the destination image
Definition at line 130 of file magnitude_phase.cl.
 {
     // Get pixels pointer
     Image gx = CONVERT_TO_IMAGE_STRUCT(gx);
     Image gy = CONVERT_TO_IMAGE_STRUCT(gy);
     // Load values
     VEC_DATA_TYPE(DATA_TYPE, 16)
     in_a = vload16(0, (__global DATA_TYPE *)gx.ptr);
     VEC_DATA_TYPE(DATA_TYPE, 16)
     in_b = vload16(0, (__global DATA_TYPE *)gy.ptr);
     // Calculate and store the results
 #ifdef MAGNITUDE
     Image magnitude = CONVERT_TO_IMAGE_STRUCT(magnitude);
     vstore16(MAGNITUDE_OP(in_a, in_b), 0, (__global DATA_TYPE *)magnitude.ptr);
 #endif /* MAGNITUDE */
 #ifdef PHASE
     Image phase = CONVERT_TO_IMAGE_STRUCT(phase);
     vstore16(PHASE_OP(in_a, in_b), 0, phase.ptr);
 #endif /* PHASE */
 }
References CONVERT_TO_IMAGE_STRUCT, DATA_TYPE, arm_compute::test::validation::reference::magnitude(), MAGNITUDE_OP, arm_compute::test::validation::reference::phase(), PHASE_OP, Image::ptr, and VEC_DATA_TYPE.
phase_signed()
uchar16 phase_signed (DATA_TYPE16 a, DATA_TYPE16 b) inline
Calculates signed phase between two inputs.
Parameters
[in] a First input. Supported data types: S16, S32
[in] b Second input. Supported data types: S16, S32
Returns
Signed phase mapped in the interval [0, 256). Supported data types: U8
Definition at line 72 of file magnitude_phase.cl.
 {
     float16 arct = atan2pi(convert_float16(b), convert_float16(a));
     arct         = select(arct, arct + 2, arct < 0.0f);
     return convert_uchar16(convert_int16(mad(arct, 128, 0.5f)) & (int16)0xFFu);
 }
References arm_compute::test::validation::b, and arm_compute::test::validation::select.
phase_unsigned()
uchar16 phase_unsigned (DATA_TYPE16 a, DATA_TYPE16 b) inline
Calculates unsigned phase between two inputs.
Parameters
[in] a First input. Supported data types: S16, S32
[in] b Second input. Supported data types: S16, S32
Returns
Unsigned phase mapped in the interval [0, 180]. Supported data types: U8
Definition at line 58 of file magnitude_phase.cl.
 {
     float16 angle_deg_f32 = atan2pi(convert_float16(b), convert_float16(a)) * (float16)180.0f;
     angle_deg_f32         = select(angle_deg_f32, (float16)180.0f + angle_deg_f32, angle_deg_f32 < (float16)0.0f);
     return convert_uchar16(angle_deg_f32);
 }
References arm_compute::test::validation::b, and arm_compute::test::validation::select.