Compute Library: arm_compute::graph::backends Namespace Reference
arm_compute::graph::backends Namespace Reference
Namespaces
detail
Data Structures
class BackendRegistry
Registry holding all the supported backends.
class CLDeviceBackend
OpenCL device backend.
class CLFunctionFactory
Factory for generating OpenCL backend functions.
class CLNodeValidator
class CLSubTensorHandle
OpenCL Sub-Tensor handle interface object.
class CLTensorHandle
OpenCL Tensor handle interface object.
class FusedConvolutionBatchNormalizationFunction
Wrapper function to first apply {NE, CL}BatchNormalizationLayer on the weights and then run {NE, CL}ConvolutionLayer with the modified weights.
class GCDeviceBackend
GLES Compute device backend.
class GCFunctionFactory
Factory for generating GLES compute backend functions.
class GCNodeValidator
class GCTensorHandle
GLES compute tensor handle interface object.
class IDeviceBackend
Device backend interface.
class NEDeviceBackend
NEON device backend.
class NEFunctionFactory
Factory for generating NEON backend functions.
class NENodeValidator
class NESubTensorHandle
NEON Sub-Tensor handle interface object.
class NETensorHandle
NEON Tensor handle interface object.
Functions
template<typename FunctionType , typename FunctionNameType , typename... ParameterType>
std::pair< std::unique_ptr< arm_compute::IFunction >, FunctionNameType > create_named_function (FunctionNameType name, ParameterType... args)
Creates and configures a named function.
template<typename FunctionType , typename FunctionNameType , typename MemoryManagerType , typename... ParameterType>
std::pair< std::unique_ptr< arm_compute::IFunction >, FunctionNameType > create_named_memory_managed_function (FunctionNameType name, MemoryManagerType mm, ParameterType... args)
Creates and configures a named function.
bool is_in_place_operation (void *input, void *output)
Checks if an operation is in place.
std::shared_ptr< IMemoryManager > get_memory_manager (GraphContext &ctx, Target target)
Returns the memory manager for a given target.
Function Documentation
create_named_function()
std::pair<std::unique_ptr<arm_compute::IFunction>, FunctionNameType> arm_compute::graph::backends::create_named_function (FunctionNameType name, ParameterType... args)
Creates and configures a named function.
Parameters
[in] name Name of the function
[in] args Function arguments
Returns
A configured backend function
Definition at line 44 of file Utils.h.
 {
     auto f = arm_compute::support::cpp14::make_unique<FunctionType>();
     f->configure(std::forward<ParameterType>(args)...);
     return std::make_pair(std::move(f), name);
 }
create_named_memory_managed_function()
std::pair<std::unique_ptr<arm_compute::IFunction>, FunctionNameType> arm_compute::graph::backends::create_named_memory_managed_function (FunctionNameType name, MemoryManagerType mm, ParameterType... args)
Creates and configures a named function.
Parameters
[in] name Name of the function
[in] mm Memory manager to use
[in] args Function arguments
Returns
A configured backend function
Definition at line 60 of file Utils.h.
 {
     auto f = arm_compute::support::cpp14::make_unique<FunctionType>(mm);
     f->configure(std::forward<ParameterType>(args)...);
     return std::make_pair(std::move(f), name);
 }
get_memory_manager()
std::shared_ptr<IMemoryManager> arm_compute::graph::backends::get_memory_manager (GraphContext & ctx, Target target) inline
Returns the memory manager for a given target.
Parameters
[in] ctx Graph context containing memory management metadata
[in] target Target to retrieve the memory manager from
Returns
The memory manager for the given target else false
Definition at line 88 of file Utils.h.
 {
     bool enabled = ctx.config().use_function_memory_manager && (ctx.memory_management_ctx(target) != nullptr);
     return enabled ? ctx.memory_management_ctx(target)->intra_mm : nullptr;
 }
References GraphContext::config(), MemoryManagerContext::intra_mm, GraphContext::memory_management_ctx(), and GraphConfig::use_function_memory_manager.
Referenced by arm_compute::graph::backends::detail::create_convolution_layer(), arm_compute::graph::backends::detail::create_convolution_layer< GCConvolutionLayerFunctions, GCTargetInfo >(), arm_compute::graph::backends::detail::create_convolution_layer< NEConvolutionLayerFunctions, NETargetInfo >(), arm_compute::graph::backends::detail::create_deconvolution_layer(), arm_compute::graph::backends::detail::create_fully_connected_layer(), arm_compute::graph::backends::detail::create_generate_proposals_layer(), arm_compute::graph::backends::detail::create_normalization_layer< NENormalizationLayer, NETargetInfo >(), and arm_compute::graph::backends::detail::create_softmax_layer().
is_in_place_operation()
bool arm_compute::graph::backends::is_in_place_operation (void * input, void * output) inline
Checks if an operation is in place.
Parameters
[in] input Pointer to input
[in] output Pointer to output
Returns
True if output is nullptr or input is equal to the output, else false
Definition at line 76 of file Utils.h.
 {
     return (output == nullptr) || (input == output);
 }
Referenced by arm_compute::graph::backends::detail::create_activation_layer(), and arm_compute::graph::backends::detail::create_batch_normalization_layer().