Compute Library: NETranspose Class Reference
NETranspose Class Reference
Basic function to run cpu::kernels::CpuTransposeKernel.
#include <NETranspose.h>
Public Member Functions
NETranspose ()
Default Constructor.
~NETranspose ()
Default Destructor.
NETranspose (const NETranspose &)=delete
Prevent instances of this class from being copied (As this class contains pointers)
NETranspose (NETranspose &&)=default
Default move constructor.
NETranspose & operator= (const NETranspose &)=delete
Prevent instances of this class from being copied (As this class contains pointers)
NETranspose & operator= (NETranspose &&)=default
Default move assignment operator.
void configure (const ITensor *input, ITensor *output)
Initialise the kernel's inputs and output.
void run () override
Run the kernels contained in the function.
Public Member Functions inherited from IFunction
virtual ~IFunction ()=default
Destructor.
virtual void prepare ()
Prepare the function for executing.
Static Public Member Functions
static Status validate (const ITensorInfo *input, const ITensorInfo *output)
Static function to check if given info will lead to a valid configuration of NETranspose.
Detailed Description
Basic function to run cpu::kernels::CpuTransposeKernel.
Definition at line 40 of file NETranspose.h.
Constructor & Destructor Documentation
NETranspose() [1/3]
NETranspose ()
Default Constructor.
Definition at line 39 of file NETranspose.cpp.
References NETranspose::~NETranspose().
     : _impl(std::make_unique<Impl>())
 {
 }
~NETranspose()
~NETranspose () default
Default Destructor.
Referenced by NETranspose::NETranspose().
NETranspose() [2/3]
NETranspose (const NETranspose &) delete
Prevent instances of this class from being copied (As this class contains pointers)
NETranspose() [3/3]
NETranspose (NETranspose &&) default
Default move constructor.
Member Function Documentation
configure()
void configure (const ITensor * input, ITensor * output)
Initialise the kernel's inputs and output.
Valid data layouts:
All
Valid data type configurations:
src dst
All All
Parameters
[in] input Input tensor. Data types supported: All
[out] output Output tensor. Data type supported: Same as input
Definition at line 46 of file NETranspose.cpp.
References ARM_COMPUTE_ERROR_ON_NULLPTR, ARM_COMPUTE_LOG_PARAMS, ITensor::info(), and arm_compute::test::validation::input.
Referenced by NEFullyConnectedLayerReshapeWeightsManaged::configure(), NELSTMLayerQuantized::configure(), NELSTMLayer::configure(), and NEQLSTMLayer::configure().
 {
     ARM_COMPUTE_ERROR_ON_NULLPTR(input, output);
     ARM_COMPUTE_LOG_PARAMS(input, output);
     _impl->src = input;
     _impl->dst = output;
     _impl->op  = std::make_unique<cpu::CpuTranspose>();
     _impl->op->configure(input->info(), output->info());
 }
operator=() [1/2]
NETranspose& operator= (const NETranspose &) delete
Prevent instances of this class from being copied (As this class contains pointers)
operator=() [2/2]
NETranspose& operator= (NETranspose &&) default
Default move assignment operator.
run()
void run () override virtual
Run the kernels contained in the function.
For CPU kernels:
Multi-threading is used for the kernels which are parallelisable.
By default std::thread::hardware_concurrency() threads are used.
Note
CPPScheduler::set_num_threads() can be used to manually set the number of threads
For OpenCL kernels:
All the kernels are enqueued on the queue associated with CLScheduler.
The queue is then flushed.
Note
The function will not block until the kernels are executed. It is the user's responsibility to wait.
Will call prepare() on first run if hasn't been done
Implements IFunction.
Definition at line 64 of file NETranspose.cpp.
References arm_compute::ACL_DST, arm_compute::ACL_SRC, ITensorPack::add_tensor(), and arm_compute::test::validation::pack.
Referenced by NELSTMLayerQuantized::prepare(), NEQLSTMLayer::prepare(), NEFullyConnectedLayerReshapeWeightsManaged::run(), and NELSTMLayer::run().
 {
     ITensorPack pack;
     pack.add_tensor(TensorType::ACL_SRC, _impl->src);
     pack.add_tensor(TensorType::ACL_DST, _impl->dst);
     _impl->op->run(pack);
 }
validate()
Status validate (const ITensorInfo * input, const ITensorInfo * output) static
Static function to check if given info will lead to a valid configuration of NETranspose.
Parameters
[in] input The input tensor. Data types supported: All
[in] output The output tensor. Data types supported: Same as input
Returns
a status
Definition at line 57 of file NETranspose.cpp.
References ARM_COMPUTE_RETURN_ERROR_ON_NULLPTR, ARM_COMPUTE_RETURN_ON_ERROR, and CpuTranspose::validate().
Referenced by arm_compute::test::validation::DATA_TEST_CASE(), NELSTMLayerQuantized::validate(), and NEQLSTMLayer::validate().
 {
     ARM_COMPUTE_RETURN_ERROR_ON_NULLPTR(input, output);
     ARM_COMPUTE_RETURN_ON_ERROR(cpu::CpuTranspose::validate(input, output));
     return Status{};
 }
The documentation for this class was generated from the following files:
arm_compute/runtime/NEON/functions/NETranspose.h
src/runtime/NEON/functions/NETranspose.cpp