Compute Library: IClKernelComponent Class Reference
IClKernelComponent Class Reference abstract
#include <Common.h>
Data Structures
struct TagVal
Public Types
using Link = SharedVarLink
using Tag = std::string
using TagLUT = std::unordered_map< Tag, TagVal >
Public Member Functions
IClKernelComponent (ClKernelBlueprint *blueprint)
ARM_COMPUTE_DISALLOW_COPY_ALLOW_MOVE (IClKernelComponent)
virtual ~IClKernelComponent ()=default
virtual ComponentType get_component_type () const =0
virtual std::vector< Link > get_links () const =0
virtual std::string name () const =0
ComponentID id () const
void set_id (ComponentID id)
virtual std::set< std::string > get_headers_list () const
virtual std::string get_additional_macros () const
virtual std::string get_component_code () const
virtual Window get_window () const
virtual TagLUT get_tag_lut (const SharedVarTable &vtable) const =0
Get the tag look-up table used to instantiate the component code.
virtual void allocate_shared_vars (SharedVarTable &vtable) const =0
Allocate all shared variables used by the component in the vtable.
virtual std::string get_dst_addr_calculation () const
virtual std::string generate_config_id () const
Generate config id of the component.
virtual CLBuildOptions generate_build_options () const
Static Public Member Functions
static std::string replace_tags (const std::string &code_template, const TagLUT &tags)
Detailed Description
Definition at line 256 of file Common.h.
Member Typedef Documentation
Link
using Link = SharedVarLink
Definition at line 259 of file Common.h.
Tag
using Tag = std::string
Definition at line 260 of file Common.h.
TagLUT
using TagLUT = std::unordered_map<Tag, TagVal>
Definition at line 292 of file Common.h.
Constructor & Destructor Documentation
IClKernelComponent()
IClKernelComponent (ClKernelBlueprint * blueprint) inline
Definition at line 294 of file Common.h.
References ARM_COMPUTE_DISALLOW_COPY_ALLOW_MOVE, and name.
Referenced by ClDirectConvolutionKernelComponent::ClDirectConvolutionKernelComponent().
         : _blueprint(blueprint)
     {
     }
~IClKernelComponent()
virtual ~IClKernelComponent () virtual default
Member Function Documentation
allocate_shared_vars()
virtual void allocate_shared_vars (SharedVarTable & vtable) const pure virtual
Allocate all shared variables used by the component in the vtable.
Parameters
vtable
Implemented in ClStoreIndirectWidthSelectKernelComponent, ClDirectConvolutionKernelComponent, ClElementwiseAddKernelComponent, and ClStoreBlockBoundaryAwareKernelComponent.
ARM_COMPUTE_DISALLOW_COPY_ALLOW_MOVE()
ARM_COMPUTE_DISALLOW_COPY_ALLOW_MOVE (IClKernelComponent)
generate_build_options()
virtual CLBuildOptions generate_build_options () const inline virtual
Reimplemented in ClStoreIndirectWidthSelectKernelComponent, ClDirectConvolutionKernelComponent, ClElementwiseAddKernelComponent, and ClStoreBlockBoundaryAwareKernelComponent.
Definition at line 401 of file Common.h.
     {
         return CLBuildOptions{};
     }
generate_config_id()
virtual std::string generate_config_id () const inline virtual
Generate config id of the component.
Returns
std::string
Reimplemented in ClElementwiseAddKernelComponent.
Definition at line 396 of file Common.h.
     {
         return "";
     }
get_additional_macros()
virtual std::string get_additional_macros () const inline virtual
Reimplemented in ClDirectConvolutionKernelComponent.
Definition at line 360 of file Common.h.
     {
         return "";
     }
get_component_code()
virtual std::string get_component_code () const inline virtual
Reimplemented in ClStoreIndirectWidthSelectKernelComponent, ClDirectConvolutionKernelComponent, ClElementwiseAddKernelComponent, and ClStoreBlockBoundaryAwareKernelComponent.
Definition at line 365 of file Common.h.
     {
         return "";
     }
get_component_type()
virtual ComponentType get_component_type () const pure virtual
Implemented in ClStoreIndirectWidthSelectKernelComponent, ClDirectConvolutionKernelComponent, ClElementwiseAddKernelComponent, and ClStoreBlockBoundaryAwareKernelComponent.
get_dst_addr_calculation()
virtual std::string get_dst_addr_calculation () const inline virtual
Definition at line 387 of file Common.h.
     {
         return "";
     }
get_headers_list()
virtual std::set<std::string> get_headers_list () const inline virtual
Reimplemented in ClDirectConvolutionKernelComponent, and ClElementwiseAddKernelComponent.
Definition at line 355 of file Common.h.
     {
         return std::set<std::string> {};
     }
get_links()
virtual std::vector<Link> get_links () const pure virtual
Implemented in ClStoreIndirectWidthSelectKernelComponent, ClDirectConvolutionKernelComponent, ClElementwiseAddKernelComponent, and ClStoreBlockBoundaryAwareKernelComponent.
get_tag_lut()
virtual TagLUT get_tag_lut (const SharedVarTable & vtable) const pure virtual
Get the tag look-up table used to instantiate the component code.
Parameters
vtable
Returns
TagLUT
Implemented in ClStoreIndirectWidthSelectKernelComponent, ClDirectConvolutionKernelComponent, ClElementwiseAddKernelComponent, and ClStoreBlockBoundaryAwareKernelComponent.
get_window()
virtual Window get_window () const inline virtual
Reimplemented in ClDirectConvolutionKernelComponent, and ClElementwiseAddKernelComponent.
Definition at line 370 of file Common.h.
     {
         return Window{};
     }
id()
ComponentID id () const inline
Definition at line 346 of file Common.h.
Referenced by ClStoreBlockBoundaryAwareKernelComponent::get_tag_lut(), ClElementwiseAddKernelComponent::get_tag_lut(), ClDirectConvolutionKernelComponent::get_tag_lut(), and ClStoreIndirectWidthSelectKernelComponent::get_tag_lut().
     {
         return _id;
     }
name()
virtual std::string name () const pure virtual
Implemented in ClStoreIndirectWidthSelectKernelComponent, ClDirectConvolutionKernelComponent, ClElementwiseAddKernelComponent, and ClStoreBlockBoundaryAwareKernelComponent.
replace_tags()
static std::string replace_tags (const std::string & code_template, const TagLUT & tags) inline static
Definition at line 307 of file Common.h.
References ARM_COMPUTE_ERROR_ON_MSG.
Referenced by ClKernelBlueprint::Implementation::build_code().
     {
         std::string replaced_code    = "";
         bool        scanning_pattern = false;
         std::string pattern_found    = "";
         for(size_t i = 0; i < code_template.size() - 1; ++i)
         {
             if(!scanning_pattern)
             {
                 if(code_template[i] == '{' && code_template[i + 1] == '{')
                 {
                     i += 1;
                     scanning_pattern = true;
                     pattern_found    = "";
                 }
                 else
                 {
                     replaced_code += code_template[i];
                 }
             }
             else
             {
                 if(code_template[i] == '}' && code_template[i + 1] == '}')
                 {
                     i += 1;
                     scanning_pattern = false;
                     std::string err  = "Pattern " + pattern_found + " not found in tags";
                     ARM_COMPUTE_ERROR_ON_MSG(tags.find(pattern_found) == tags.end(), err.c_str());
                     replaced_code += tags.find(pattern_found)->second.value;
                 }
                 else
                 {
                     pattern_found += code_template[i];
                 }
             }
         }
         return replaced_code;
     }
set_id()
void set_id (ComponentID id) inline
Definition at line 350 of file Common.h.
     {
         _id = id;
     }
The documentation for this class was generated from the following file:
src/core/experimental/dynamic_fusion/ClKernelBuildingImpl/Common.h