Compute Library: ClKernelBlueprint Class Reference
ClKernelBlueprint Class Reference
Intermediate representation of the final, complete kernel source.
#include <ClKernelBuildingAPI.h>
Data Structures
struct Implementation
Intermediate representation of the final, complete kernel source.
Public Member Functions
ClKernelBlueprint ()
~ClKernelBlueprint ()
Implementation & impl ()
const Implementation & impl () const
Detailed Description
Intermediate representation of the final, complete kernel source.
Definition at line 46 of file ClKernelBuildingAPI.h.
Constructor & Destructor Documentation
ClKernelBlueprint()
ClKernelBlueprint ()
Definition at line 36 of file ClKernelBuildingAPI.cpp.
References ClKernelBlueprint::~ClKernelBlueprint().
     : _impl{ std::make_unique<ClKernelBlueprint::Implementation>() }
 {
 }
~ClKernelBlueprint()
~ClKernelBlueprint () default
Referenced by ClKernelBlueprint::ClKernelBlueprint().
Member Function Documentation
impl() [1/2]
ClKernelBlueprint::Implementation & impl ()
Definition at line 43 of file ClKernelBuildingAPI.cpp.
Referenced by arm_compute::experimental::dynamic_fusion::add_kcomp_direct_conv2d(), arm_compute::experimental::dynamic_fusion::add_kcomp_eltwise_add(), arm_compute::experimental::dynamic_fusion::add_kcomp_store(), arm_compute::experimental::dynamic_fusion::add_tensor(), arm_compute::experimental::dynamic_fusion::build(), arm_compute::experimental::dynamic_fusion::get_dependency_graph(), arm_compute::experimental::dynamic_fusion::set_tile_info(), and arm_compute::experimental::dynamic_fusion::update_merge_point().
 {
     return *_impl;
 }
impl() [2/2]
const ClKernelBlueprint::Implementation & impl () const
Definition at line 47 of file ClKernelBuildingAPI.cpp.
 {
     return *_impl;
 }
The documentation for this class was generated from the following files:
src/core/experimental/dynamic_fusion/ClKernelBuildingAPI.h
src/core/experimental/dynamic_fusion/ClKernelBuildingAPI.cpp