Compute Library: GEMMBenchmarkResultRecorder Class Reference
GEMMBenchmarkResultRecorder Class Reference
Public Member Functions
def __init__ (self, tol=0.01)
def add
def get_record (self)
def get_best_gemm_configs (self)
def get_best_gemm_configs_as_sequence (self)
def get_config_distributions (self)
def get_best_gemm_strategies (self)
def save_to_jsons (self, out_dir, only_best_config=True)
def summary (self, sum_level=SummaryLevel.Short)
Static Public Attributes
SummaryLevel = Enum("SummaryLevel", ["Short", "Detailed"])
Detailed Description
A recorder that records and organises GEMM Benchmark results, and produces various reports on the record.
Definition at line 201 of file GemmTuner.py.
Constructor & Destructor Documentation
__init__()
def __init__ (self, tol = 0.01)
Initializer
Definition at line 207 of file GemmTuner.py.
References GEMMBenchmarkResultRecorder._strategies, GEMMBenchmarkResultRecorder._tol, and arm_compute::test::validation.set().
     def __init__(self, tol=0.01):
         """ Initializer
         """
         self._benchmark_result_record: List[BenchmarkResult] = []
         # Strategies recorded
         self._strategies = set()
         self._tol = tol
Member Function Documentation
add()
def add (self, benchmark_result)
Definition at line 215 of file GemmTuner.py.
References GEMMBenchmarkResultRecorder._strategies.
Referenced by GEMMBenchmarkResultRecorder.get_config_distributions().
     def add(self, benchmark_result: BenchmarkResult):
         """ Add a benchmark result to the record.
         """
         gemm_param, strategy, gemm_config, measurement = benchmark_result
         # Update strategies encoutnered
         self._strategies.add(strategy)
         self._benchmark_result_record.append(benchmark_result)
get_best_gemm_configs()
def get_best_gemm_configs (self)
Get the best GEMMConfig set per GEMMParam per Strategy
Definition at line 229 of file GemmTuner.py.
References GEMMBenchmarkResultRecorder._tol, and GEMMBenchmarkResultRecorder.get_record().
Referenced by GEMMBenchmarkResultRecorder.get_best_gemm_configs_as_sequence(), and GEMMBenchmarkResultRecorder.summary().
     def get_best_gemm_configs(self):
         """ Get the best GEMMConfig set per GEMMParam per Strategy
         """
         best_gc_sets: Dict[
             Tuple[GEMMParam, Strategy], List[Tuple[GEMMConfig, Measurement]]
         ] = defaultdict(list)
         for gemm_param, strategy, gemm_config, measurement in self.get_record():
             best_gc_set = best_gc_sets.setdefault((gemm_param, strategy), [])
             best_gc_set.append((gemm_config, measurement))
             # Sort the best config set (list)
             best_gc_set = sorted(
                 best_gc_set, key=lambda gc_and_m: gc_and_m[1].get_total_ms()
             )
             # Filter out configs that are beyond tolerance to the best GEMMConfig's measurement
             best_gc, best_m = best_gc_set[0]
             best_gc_set_new = [
                 (gemm_config, measurement)
                 for gemm_config, measurement in best_gc_set[1:]
                 if measurement.is_close_to(best_m, self._tol)
             ]
             # Add back the best config
             best_gc_set_new.insert(0, (best_gc, best_m))
             best_gc_sets[(gemm_param, strategy)] = best_gc_set_new
         return best_gc_sets
get_best_gemm_configs_as_sequence()
def get_best_gemm_configs_as_sequence (self)
Get the best GEMMConfig set per GEMMParam per Strategy, and flatten the result into a sequence
of BenchmarkResults
Definition at line 255 of file GemmTuner.py.
References GEMMBenchmarkResultRecorder.get_best_gemm_configs().
Referenced by GEMMBenchmarkResultRecorder.get_config_distributions(), and GEMMBenchmarkResultRecorder.save_to_jsons().
     def get_best_gemm_configs_as_sequence(self):
         """ Get the best GEMMConfig set per GEMMParam per Strategy, and flatten the result into a sequence
         of BenchmarkResults
         """
         for (
             (gemm_param, strategy),
             best_gc_sets,
         ) in self.get_best_gemm_configs().items():
             for best_gemm_config, best_measurement in best_gc_sets:
                 yield BenchmarkResult(
                     gemm_param, strategy, best_gemm_config, best_measurement
                 )
get_best_gemm_strategies()
def get_best_gemm_strategies (self)
Get the best Stratey per GEMMParam
Definition at line 280 of file GemmTuner.py.
References GEMMBenchmarkResultRecorder.get_record().
Referenced by GEMMBenchmarkResultRecorder.save_to_jsons().
     def get_best_gemm_strategies(self):
         """ Get the best Stratey per GEMMParam
         """
         all_results: Dict[GEMMParam, List[Tuple[Strategy, Measurement]]] = defaultdict(
             list
         )
         best_strategies: Dict[GEMMParam, Strategy] = {}
         for gemm_param, strategy, gemm_config, measurement in self.get_record():
             all_results[gemm_param].append((strategy, measurement))
         for gemm_param, results_set in all_results.items():
             # Sort the best results set (list)
             results_set = sorted(
                 results_set, key=lambda s_and_m: s_and_m[1].get_total_ms()
             )
             # Select best Strategy
             best_s, best_m = results_set[0]
             best_strategies[gemm_param] = best_s
         return best_strategies
get_config_distributions()
def get_config_distributions (self)
Return GEMMConfigDistribution for each strategy
Definition at line 268 of file GemmTuner.py.
References GEMMBenchmarkResultRecorder.add(), and GEMMBenchmarkResultRecorder.get_best_gemm_configs_as_sequence().
     def get_config_distributions(self):
         """ Return GEMMConfigDistribution for each strategy
         """
         gemm_config_distributions: Dict[Strategy, GEMMConfigDistribution] = defaultdict(
             GEMMConfigDistribution
         )
         for benchmark_result in self.get_best_gemm_configs_as_sequence():
             _, strategy, _, _ = benchmark_result
             gemm_config_distributions[strategy].add(benchmark_result)
         return gemm_config_distributions
get_record()
def get_record (self, Generator, BenchmarkResult, None, None)
Return an iterator that iterates over the record.
Definition at line 224 of file GemmTuner.py.
Referenced by GEMMBenchmarkResultRecorder.get_best_gemm_configs(), GEMMBenchmarkResultRecorder.get_best_gemm_strategies(), GEMMBenchmarkResultRecorder.save_to_jsons(), and GEMMBenchmarkResultRecorder.summary().
     def get_record(self) -> Generator[BenchmarkResult, None, None]:
         """ Return an iterator that iterates over the record.
         """
         yield from self._benchmark_result_record
save_to_jsons()
def save_to_jsons (self, out_dir, only_best_config = True)
Save records to an output directory of JSON files.
The directory is organized such that each strategy gets its own JSON file.
The directory also includes a JSON file to define the best strategy per GEMM Param.
Definition at line 303 of file GemmTuner.py.
References GEMMBenchmarkResultRecorder._strategies, GemmTuner.check_out_path(), GemmTuner.dump_json(), GEMMBenchmarkResultRecorder.get_best_gemm_configs_as_sequence(), GEMMBenchmarkResultRecorder.get_best_gemm_strategies(), GEMMBenchmarkResultRecorder.get_record(), and caffe_data_extractor.str.
     def save_to_jsons(self, out_dir, only_best_config=True):
         """ Save records to an output directory of JSON files.
         The directory is organized such that each strategy gets its own JSON file.
         The directory also includes a JSON file to define the best strategy per GEMM Param.
         """
         if not os.path.exists(out_dir):
             logging.info(
                 "Output directory {} does not exist. Creating...".format(
                     out_dir)
             )
             os.mkdir(out_dir)
         out_json_path = os.path.join(out_dir, "gemm_type_selection.json")
         if check_out_path(out_json_path):
             results = self.get_best_gemm_strategies()
             results = {str(key): value.name for key, value in results.items()}
             dump_json(out_json_path, results)
         for strategy in self._strategies:
             out_json_path = os.path.join(
                 out_dir, ("gemm_config_" + strategy.name.lower() + ".json")
             )
             if check_out_path(out_json_path):
                 record = (
                     self.get_best_gemm_configs_as_sequence()
                     if only_best_config
                     else self.get_record()
                 )
                 results = defaultdict(list)
                 for res in record:
                     if res.strategy == strategy:
                         results[str(res.gemm_param)].append(
{
                                 "GEMMConfig": str(res.gemm_config),
                                 "OpenCL_Timer_ms_reshape": str(
                                     res.measurement.opencl_timer_ms_reshape
                                 ),
                                 "OpenCL_Timer_ms_kernel": str(
                                     res.measurement.opencl_timer_ms_kernel
                                 ),
                             }
                         )
                 dump_json(out_json_path, results)
summary()
def summary (self, sum_level = SummaryLevel.Short)
Return the summary string of the record
Definition at line 347 of file GemmTuner.py.
References GEMMBenchmarkResultRecorder.get_best_gemm_configs(), GEMMBenchmarkResultRecorder.get_record(), and arm_compute::test.join().
     def summary(self, sum_level=SummaryLevel.Short):
         """ Return the summary string of the record
         """
         num_raw_records = sum(1 for _ in self.get_record())
         gemm_params_per_strategy = defaultdict(list)
         for gemm_param, strategy in self.get_best_gemm_configs().keys():
             gemm_params_per_strategy[strategy].append(gemm_param)
         global_summary = f"""
 === {self.__class__.__name__} Summary ===
 [Global]
 Strategies recorded: {", ".join(map(lambda s: s.name, self._strategies))}
 Total number of results recorded: {num_raw_records}
 [Per strategy]
         """
         strategy_summaries = []
         for strategy in gemm_params_per_strategy:
             summary = f"""
 Strategy {strategy.name}:
 GEMM parameters:
     Number of: {len(gemm_params_per_strategy[strategy])}
             """
             if sum_level == self.__class__.SummaryLevel.Detailed:
                 summary += f"""
     Content: {gemm_params_per_strategy[strategy]}
                 """
             strategy_summaries.append(summary)
         return global_summary + "".join(strategy_summaries)
Field Documentation
SummaryLevel
SummaryLevel = Enum("SummaryLevel", ["Short", "Detailed"]) static
Definition at line 205 of file GemmTuner.py.
The documentation for this class was generated from the following file:
examples/gemm_tuner/GemmTuner.py