Compute Library: DotGraphPrinter Class Reference
DotGraphPrinter Class Reference final
Graph printer interface.
#include <DotGraphPrinter.h>
Public Member Functions
void print (const Graph &g, std::ostream &os) override
Print graph.
Public Member Functions inherited from IGraphPrinter
virtual ~IGraphPrinter ()=default
Virtual Destructor.
Detailed Description
Graph printer interface.
Definition at line 72 of file DotGraphPrinter.h.
Member Function Documentation
print()
void print (const Graph & g, std::ostream & os) override virtual
Print graph.
Parameters
[in] g Graph to print
[out] os Output stream
Implements IGraphPrinter.
Definition at line 141 of file DotGraphPrinter.cpp.
References ARM_COMPUTE_ERROR_ON, ARM_COMPUTE_UNUSED, TensorDescriptor::data_type, Tensor::desc(), Graph::edges(), TensorDescriptor::layout, arm_compute::test::validation::n, name, Graph::name(), Graph::nodes(), TensorDescriptor::shape, tf_frozen_model_extractor::t, and arm_compute::support::cpp11::to_string().
 {
     // Print header
     print_header(g, os);
     // Print nodes
     print_nodes(g, os);
     // Print edges
     print_edges(g, os);
     // Print footer
     print_footer(g, os);
 }
The documentation for this class was generated from the following files:
arm_compute/graph/printers/DotGraphPrinter.h
src/graph/printers/DotGraphPrinter.cpp