Compute Library: NEBatchNormalizationLayerKernel Class Reference
NEBatchNormalizationLayerKernel Class Reference
Interface for the batch normalization layer kernel.
#include <NEBatchNormalizationLayerKernel.h>
Public Member Functions
const char * name () const override
Name of the kernel.
NEBatchNormalizationLayerKernel ()
Default constructor.
NEBatchNormalizationLayerKernel (const NEBatchNormalizationLayerKernel &)=delete
Prevent instances of this class from being copied (As this class contains pointers)
NEBatchNormalizationLayerKernel & operator= (const NEBatchNormalizationLayerKernel &)=delete
Prevent instances of this class from being copied (As this class contains pointers)
NEBatchNormalizationLayerKernel (NEBatchNormalizationLayerKernel &&)=default
Default Move Constructor.
NEBatchNormalizationLayerKernel & operator= (NEBatchNormalizationLayerKernel &&)=default
Default move assignment operator.
~NEBatchNormalizationLayerKernel ()=default
Default destructor.
void configure (ITensor *input, ITensor *output, const ITensor *mean, const ITensor *var, const ITensor *beta=nullptr, const ITensor *gamma=nullptr, float epsilon=0.001f, ActivationLayerInfo act_info=ActivationLayerInfo())
Set the input and output tensors.
void run (const Window &window, const ThreadInfo &info) override
Execute the kernel on the passed window.
Public Member Functions inherited from ICPPKernel
virtual ~ICPPKernel ()=default
Default destructor.
virtual void run_nd (const Window &window, const ThreadInfo &info, const Window &thread_locator)
legacy compatibility layer for implemantions which do not support thread_locator In these cases we simply narrow the interface down the legacy version
virtual void run_op (ITensorPack &tensors, const Window &window, const ThreadInfo &info)
Execute the kernel on the passed window.
virtual size_t get_mws (const CPUInfo &platform, size_t thread_count) const
Return minimum workload size of the relevant kernel.
Public Member Functions inherited from IKernel
IKernel ()
Constructor.
virtual ~IKernel ()=default
Destructor.
virtual bool is_parallelisable () const
Indicates whether or not the kernel is parallelisable.
virtual BorderSize border_size () const
The size of the border for that kernel.
const Window & window () const
The maximum window the kernel can be executed on.
bool is_window_configured () const
Function to check if the embedded window of this kernel has been configured.
Static Public Member Functions
static Status validate (const ITensorInfo *input, const ITensorInfo *output, const ITensorInfo *mean, const ITensorInfo *var, const ITensorInfo *beta=nullptr, const ITensorInfo *gamma=nullptr, float epsilon=0.001f, ActivationLayerInfo act_info=ActivationLayerInfo())
Static function to check if given info will lead to a valid configuration of NEBatchNormalizationLayerKernel.
Additional Inherited Members
Static Public Attributes inherited from ICPPKernel
static constexpr size_t default_mws = 1
Detailed Description
Interface for the batch normalization layer kernel.
Definition at line 36 of file NEBatchNormalizationLayerKernel.h.
Constructor & Destructor Documentation
NEBatchNormalizationLayerKernel() [1/3]
NEBatchNormalizationLayerKernel ()
Default constructor.
Definition at line 309 of file NEBatchNormalizationLayerKernel.cpp.
Referenced by NEBatchNormalizationLayerKernel::name().
     : _func(nullptr), _input(nullptr), _output(nullptr), _mean(nullptr), _var(nullptr), _gamma(nullptr), _beta(nullptr), _epsilon(), _act_info()
 {
 }
NEBatchNormalizationLayerKernel() [2/3]
NEBatchNormalizationLayerKernel (const NEBatchNormalizationLayerKernel &) delete
Prevent instances of this class from being copied (As this class contains pointers)
NEBatchNormalizationLayerKernel() [3/3]
NEBatchNormalizationLayerKernel (NEBatchNormalizationLayerKernel &&) default
Default Move Constructor.
~NEBatchNormalizationLayerKernel()
~NEBatchNormalizationLayerKernel () default
Default destructor.
Referenced by NEBatchNormalizationLayerKernel::name().
Member Function Documentation
configure()
void configure (ITensor * input, ITensor * output, const ITensor * mean, const ITensor * var, const ITensor * beta = nullptr, const ITensor * gamma = nullptr, float epsilon = 0.001f, ActivationLayerInfo act_info = ActivationLayerInfo())
Set the input and output tensors.
Note
If the output tensor is a nullptr, the batch normalization function will be performed in-place
Parameters
[in,out] input Source tensor. In case of output tensor = nullptr, this tensor will store the result. 3 lower dimensions represent a single input with dimensions [width, height, FM]. The rest are optional and used for representing batches. Data types supported: F16/F32.
[out] output Destination tensor. Output will have the same number of dimensions as input. Data type supported: same as input
[in] mean Mean values tensor. 1 dimension with size equal to the feature maps [FM]. Data types supported: Same as input
[in] var Variance values tensor. 1 dimension with size equal to the feature maps [FM]. Data types supported: Same as input
[in] beta (Optional) Beta values tensor info. 1 dimension with size equal to the feature maps [FM]. If not provided, default value for beta is 0. Data types supported: Same as input
[in] gamma (Optional) Gamma values tensor info. 1 dimension with size equal to the feature maps [FM]. If not provided, default value for gamma is 1. Data types supported: Same as input
[in] epsilon (Optional) Small value to avoid division with zero. Default value is 0.001f.
[in] act_info (Optional) Activation layer information in case of a fused activation. Only RELU, BOUNDED_RELU and LU_BOUNDED_RELU supported.
Definition at line 314 of file NEBatchNormalizationLayerKernel.cpp.
References ARM_COMPUTE_ERROR_ON_NULLPTR, ARM_COMPUTE_ERROR_THROW_ON, arm_compute::auto_init_if_empty(), arm_compute::calculate_max_window(), ICloneable< T >::clone(), ITensorInfo::data_layout(), ActivationLayerInfo::enabled(), arm_compute::quantization::epsilon, ITensor::info(), arm_compute::test::validation::input, arm_compute::NCHW, and arm_compute::cpu::kernels::validate_arguments().
Referenced by NEBatchNormalizationLayerKernel::name().
 {
     ARM_COMPUTE_ERROR_ON_NULLPTR(input, mean, var);
     ARM_COMPUTE_ERROR_THROW_ON(validate_arguments(input->info(), (output != nullptr) ? output->info() : nullptr,
                                                   mean->info(), var->info(),
                                                   (beta != nullptr) ? beta->info() : nullptr,
                                                   (gamma != nullptr) ? gamma->info() : nullptr,
                                                   epsilon, act_info));
     _input    = input;
     _output   = input;
     _mean     = mean;
     _var      = var;
     _gamma    = gamma;
     _beta     = beta;
     _epsilon  = epsilon;
     _act_info = act_info;
     const bool run_in_place = (output == nullptr) || (output == input);
     if(!run_in_place)
     {
         _output = output;
     }
     // Configure activation function to run
     const bool is_nchw = _input->info()->data_layout() == DataLayout::NCHW;
     if(is_nchw)
     {
         if(_act_info.enabled())
         {
             configure_fused();
         }
         else
         {
             configure_non_fused();
         }
     }
     // Configure kernel window
     Window win = calculate_max_window(*input->info(), Steps());
     INEKernel::configure(win);
     if(output != nullptr)
     {
         // Output auto initialization if not yet initialized
         auto_init_if_empty(*output->info(), *input->info()->clone());
     }
 }
name()
const char* name () const inline override virtual
Name of the kernel.
Returns
Kernel name
Implements ICPPKernel.
Definition at line 39 of file NEBatchNormalizationLayerKernel.h.
References NEBatchNormalizationLayerKernel::configure(), arm_compute::quantization::epsilon, arm_compute::test::validation::info, arm_compute::test::validation::input, NEBatchNormalizationLayerKernel::NEBatchNormalizationLayerKernel(), NEBatchNormalizationLayerKernel::operator=(), NEBatchNormalizationLayerKernel::run(), NEBatchNormalizationLayerKernel::validate(), IKernel::window(), and NEBatchNormalizationLayerKernel::~NEBatchNormalizationLayerKernel().
     {
         return "NEBatchNormalizationLayerKernel";
     }
operator=() [1/2]
NEBatchNormalizationLayerKernel& operator= (const NEBatchNormalizationLayerKernel &) delete
Prevent instances of this class from being copied (As this class contains pointers)
Referenced by NEBatchNormalizationLayerKernel::name().
operator=() [2/2]
NEBatchNormalizationLayerKernel& operator= (NEBatchNormalizationLayerKernel &&) default
Default move assignment operator.
run()
void run (const Window & window, const ThreadInfo & info) override virtual
Execute the kernel on the passed window.
Warning
If is_parallelisable() returns false then the passed window must be equal to window()
Note
The window has to be a region within the window returned by the window() method
The width of the window has to be a multiple of num_elems_processed_per_iteration().
Parameters
[in] window Region on which to execute the kernel. (Must be a region of the window returned by window())
[in] info Info about executing thread and CPU.
Reimplemented from ICPPKernel.
Definition at line 377 of file NEBatchNormalizationLayerKernel.cpp.
References ARM_COMPUTE_ERROR_ON, ARM_COMPUTE_ERROR_ON_INVALID_SUBWINDOW, ARM_COMPUTE_ERROR_ON_UNCONFIGURED_KERNEL, ARM_COMPUTE_UNUSED, ITensorInfo::data_layout(), ITensorInfo::data_type(), CPUInfo::get(), ITensor::info(), arm_compute::NCHW, and IKernel::window().
Referenced by NEBatchNormalizationLayerKernel::name().
 {
     ARM_COMPUTE_UNUSED(info);
     ARM_COMPUTE_ERROR_ON_UNCONFIGURED_KERNEL(this);
     ARM_COMPUTE_ERROR_ON_INVALID_SUBWINDOW(INEKernel::window(), window);
     ARM_COMPUTE_ERROR_ON(_func == nullptr && _input->info()->data_layout() == DataLayout::NCHW);
     const bool is_nchw = _input->info()->data_layout() == DataLayout::NCHW;
     if(is_nchw)
     {
         (this->*_func)(window);
     }
     else
     {
         const auto *uk = get_implementation(BatchNormalizationSelectorData{ _input->info()->data_type(), CPUInfo::get() });
         uk->ukernel(_input, _output, _mean, _var, _beta, _gamma, _epsilon, _act_info, window);
     }
 }
validate()
Status validate (const ITensorInfo * input, const ITensorInfo * output, const ITensorInfo * mean, const ITensorInfo * var, const ITensorInfo * beta = nullptr, const ITensorInfo * gamma = nullptr, float epsilon = 0.001f, ActivationLayerInfo act_info = ActivationLayerInfo()) static
Static function to check if given info will lead to a valid configuration of NEBatchNormalizationLayerKernel.
Parameters
[in] input Source tensor info. In case of output tensor = nullptr, this tensor will store the result. 3 lower dimensions represent a single input with dimensions [width, height, FM]. The rest are optional and used for representing batches. Data types supported: F16/F32.
[in] output Destination tensor info. Output will have the same number of dimensions as input. Data type supported: same as input
[in] mean Mean values tensor info. 1 dimension with size equal to the feature maps [FM]. Data types supported: Same as input
[in] var Variance values tensor info. 1 dimension with size equal to the feature maps [FM]. Data types supported: Same as input
[in] beta (Optional) Beta values tensor info. 1 dimension with size equal to the feature maps [FM]. If not provided, default value for beta is 0. Data types supported: Same as input
[in] gamma (Optional) Gamma values tensor info. 1 dimension with size equal to the feature maps [FM]. If not provided, default value for gamma is 1. Data types supported: Same as input
[in] epsilon (Optional) Small value to avoid division with zero. Default value is 0.001f.
[in] act_info (Optional) Activation layer information in case of a fused activation. Only RELU, BOUNDED_RELU and LU_BOUNDED_RELU supported.
Returns
a status
Definition at line 367 of file NEBatchNormalizationLayerKernel.cpp.
References ARM_COMPUTE_RETURN_ON_ERROR, and arm_compute::cpu::kernels::validate_arguments().
Referenced by NEBatchNormalizationLayerKernel::name(), and NEBatchNormalizationLayer::validate().
 {
     ARM_COMPUTE_RETURN_ON_ERROR(validate_arguments(input, output, mean, var, beta, gamma, epsilon, act_info));
     return Status{};
 }
The documentation for this class was generated from the following files:
src/core/NEON/kernels/NEBatchNormalizationLayerKernel.h
src/core/NEON/kernels/NEBatchNormalizationLayerKernel.cpp