Compute Library: CLArithmeticAddition Class Reference
CLArithmeticAddition Class Reference
Basic function to run opencl::kernels::ClSaturatedArithmeticKernel for addition.
#include <CLElementwiseOperations.h>
Public Member Functions
CLArithmeticAddition ()
Default Constructor.
~CLArithmeticAddition ()
Default Destructor.
CLArithmeticAddition (const CLArithmeticAddition &)=delete
Prevent instances of this class from being copied (As this class contains pointers)
CLArithmeticAddition (CLArithmeticAddition &&)
Default move constructor.
CLArithmeticAddition & operator= (const CLArithmeticAddition &)=delete
Prevent instances of this class from being copied (As this class contains pointers)
CLArithmeticAddition & operator= (CLArithmeticAddition &&)
Default move assignment operator.
void configure (ICLTensor *input1, ICLTensor *input2, ICLTensor *output, ConvertPolicy policy, const ActivationLayerInfo &act_info=ActivationLayerInfo())
Initialise the kernel's inputs, output and conversion policy.
void configure (const CLCompileContext &compile_context, const ICLTensor *input1, const ICLTensor *input2, ICLTensor *output, ConvertPolicy policy, const ActivationLayerInfo &act_info=ActivationLayerInfo())
Initialise the kernel's inputs, output and conversion policy.
void run () override
Run the kernels contained in the function.
Public Member Functions inherited from IFunction
virtual ~IFunction ()=default
Destructor.
virtual void prepare ()
Prepare the function for executing.
Static Public Member Functions
static Status validate (const ITensorInfo *input1, const ITensorInfo *input2, const ITensorInfo *output, ConvertPolicy policy, const ActivationLayerInfo &act_info=ActivationLayerInfo())
Static function to check if given info will lead to a valid configuration of opencl::kernels::ClSaturatedArithmeticKernel for addition.
Detailed Description
Basic function to run opencl::kernels::ClSaturatedArithmeticKernel for addition.
Note
The tensor data type for the inputs must be U8/QASYMM8/QASYMM8_SIGNED/S16/QSYMM16/S32/F16/F32.
The function performs an arithmetic addition between two tensors.
Definition at line 41 of file CLElementwiseOperations.h.
Constructor & Destructor Documentation
CLArithmeticAddition() [1/3]
CLArithmeticAddition ()
Default Constructor.
Definition at line 45 of file CLElementwiseOperations.cpp.
References CLArithmeticAddition::operator=(), and CLArithmeticAddition::~CLArithmeticAddition().
     : _impl(std::make_unique<Impl>())
 {
 }
~CLArithmeticAddition()
~CLArithmeticAddition () default
Default Destructor.
Referenced by CLArithmeticAddition::CLArithmeticAddition().
CLArithmeticAddition() [2/3]
CLArithmeticAddition (const CLArithmeticAddition &) delete
Prevent instances of this class from being copied (As this class contains pointers)
CLArithmeticAddition() [3/3]
CLArithmeticAddition (CLArithmeticAddition &&) default
Default move constructor.
Member Function Documentation
configure() [1/2]
void configure (ICLTensor * input1, ICLTensor * input2, ICLTensor * output, ConvertPolicy policy, const ActivationLayerInfo & act_info = ActivationLayerInfo())
Initialise the kernel's inputs, output and conversion policy.
Valid data layouts:
All
Valid data type configurations:
src0 src1 dst
QASYMM8 QASYMM8 QASYMM8
QASYMM8_SIGNED QASYMM8_SIGNED QASYMM8_SIGNED
QSYMM16 QSYMM16 QASYMM16
U8 U8 U8
U8 U8 S16
U8 S16 S16
S16 U8 S16
S16 S16 S16
S32 S32 S32
F16 F16 F16
F32 F32 F32
Parameters
[in,out] input1 First tensor input. Data types supported: U8/QASYMM8/QASYMM8_SIGNED/S16/QSYMM16/S32/F16/F32. The input tensor is [in, out] because its TensorInfo might be modified inside the kernel in case of broadcasting of dimension 0.
[in,out] input2 Second tensor input. Data types supported: U8/QASYMM8/QASYMM8_SIGNED/S16/QSYMM16/S32/F16/F32. The input tensor is [in, out] because its TensorInfo might be modified inside the kernel in case of broadcasting of dimension 0.
[out] output Output tensor. Data types supported: U8/QASYMM8/QASYMM8_SIGNED/S16/QSYMM16/S32/F16/F32.
[in] policy Policy to use to handle overflow.
[in] act_info (Optional) Activation layer information in case of a fused activation.
Definition at line 53 of file CLElementwiseOperations.cpp.
References CLKernelLibrary::get().
Referenced by CLRNNLayer::configure(), CLFFTConvolutionLayer::configure(), CLLSTMLayerQuantized::configure(), CLLSTMLayer::configure(), and CLQLSTMLayer::configure().
 {
     configure(CLKernelLibrary::get().get_compile_context(), input1, input2, output, policy, act_info);
 }
configure() [2/2]
void configure (const CLCompileContext & compile_context, const ICLTensor * input1, const ICLTensor * input2, ICLTensor * output, ConvertPolicy policy, const ActivationLayerInfo & act_info = ActivationLayerInfo())
Initialise the kernel's inputs, output and conversion policy.
Valid configurations (Input1,Input2) -> Output :
(U8,U8) -> U8
(U8,U8) -> S16
(S16,U8) -> S16
(U8,S16) -> S16
(S16,S16) -> S16
(S32,S32) -> S32
(F16,F16) -> F16
(F32,F32) -> F32
(QASYMM8,QASYMM8) -> QASYMM8
(QASYMM8_SIGNED,QASYMM8_SIGNED) -> QASYMM8_SIGNED
(QSYMM16,QSYMM16) -> QSYMM16
Parameters
[in] compile_context The compile context to be used.
[in,out] input1 First tensor input. Data types supported: U8/QASYMM8/QASYMM8_SIGNED/S16/QSYMM16/S32/F16/F32. The input tensor is [in, out] because its TensorInfo might be modified inside the kernel in case of broadcasting of dimension 0.
[in,out] input2 Second tensor input. Data types supported: U8/QASYMM8/QASYMM8_SIGNED/S16/QSYMM16/S32/F16/F32. The input tensor is [in, out] because its TensorInfo might be modified inside the kernel in case of broadcasting of dimension 0.
[out] output Output tensor. Data types supported: U8/QASYMM8/QASYMM8_SIGNED/S16/QSYMM16/S32/F16/F32.
[in] policy Policy to use to handle overflow.
[in] act_info (Optional) Activation layer information in case of a fused activation.
Definition at line 58 of file CLElementwiseOperations.cpp.
References ITensor::info().
 {
     _impl->src_0 = input1;
     _impl->src_1 = input2;
     _impl->dst   = output;
     _impl->op    = std::make_unique<opencl::ClAdd>();
     _impl->op->configure(compile_context, input1->info(), input2->info(), output->info(), policy, act_info);
 }
operator=() [1/2]
CLArithmeticAddition& operator= (const CLArithmeticAddition &) delete
Prevent instances of this class from being copied (As this class contains pointers)
Referenced by CLArithmeticAddition::CLArithmeticAddition().
operator=() [2/2]
CLArithmeticAddition & operator= (CLArithmeticAddition &&) default
Default move assignment operator.
run()
void run () override virtual
Run the kernels contained in the function.
For CPU kernels:
Multi-threading is used for the kernels which are parallelisable.
By default std::thread::hardware_concurrency() threads are used.
Note
CPPScheduler::set_num_threads() can be used to manually set the number of threads
For OpenCL kernels:
All the kernels are enqueued on the queue associated with CLScheduler.
The queue is then flushed.
Note
The function will not block until the kernels are executed. It is the user's responsibility to wait.
Will call prepare() on first run if hasn't been done
Implements IFunction.
Definition at line 73 of file CLElementwiseOperations.cpp.
References arm_compute::ACL_DST, arm_compute::ACL_SRC_0, arm_compute::ACL_SRC_1, ITensorPack::add_tensor(), arm_compute::test::validation::dst, and arm_compute::test::validation::pack.
Referenced by CLQLSTMLayer::prepare(), CLRNNLayer::run(), CLFFTConvolutionLayer::run(), CLLSTMLayerQuantized::run(), CLLSTMLayer::run(), and CLQLSTMLayer::run().
 {
     ITensorPack pack;
     pack.add_tensor(TensorType::ACL_SRC_0, _impl->src_0);
     pack.add_tensor(TensorType::ACL_SRC_1, _impl->src_1);
     pack.add_tensor(TensorType::ACL_DST, _impl->dst);
     _impl->op->run(pack);
 }
validate()
Status validate (const ITensorInfo * input1, const ITensorInfo * input2, const ITensorInfo * output, ConvertPolicy policy, const ActivationLayerInfo & act_info = ActivationLayerInfo()) static
Static function to check if given info will lead to a valid configuration of opencl::kernels::ClSaturatedArithmeticKernel for addition.
Valid configurations (Input1,Input2) -> Output :
(U8,U8) -> U8
(U8,U8) -> S16
(S16,U8) -> S16
(U8,S16) -> S16
(S16,S16) -> S16
(S32,S32) -> S32
(F16,F16) -> F16
(F32,F32) -> F32
(QASYMM8,QASYMM8) -> QASYMM8
(QASYMM8_SIGNED,QASYMM8_SIGNED) -> QASYMM8_SIGNED
(QSYMM16,QSYMM16) -> QSYMM16
Parameters
[in] input1 First tensor input info. Data types supported: U8/QASYMM8/QASYMM8_SIGNED/S16/QSYMM16/S32/F16/F32.
[in] input2 Second tensor input info. Data types supported: U8/QASYMM8/QASYMM8_SIGNED/S16/QSYMM16/S32/F16/F32.
[in] output Output tensor info. Data types supported: U8/QASYMM8/QASYMM8_SIGNED/S16/QSYMM16/S32/F16/F32.
[in] policy Policy to use to handle overflow.
[in] act_info (Optional) Activation layer information in case of a fused activation.
Returns
a status
Definition at line 68 of file CLElementwiseOperations.cpp.
References ClAdd::validate().
Referenced by arm_compute::test::validation::DATA_TEST_CASE(), arm_compute::test::validation::TEST_CASE(), CLRNNLayer::validate(), CLLSTMLayerQuantized::validate(), CLLSTMLayer::validate(), and CLQLSTMLayer::validate().
 {
     return opencl::ClAdd::validate(input1, input2, output, policy, act_info);
 }
The documentation for this class was generated from the following files:
arm_compute/runtime/CL/functions/CLElementwiseOperations.h
src/runtime/CL/functions/CLElementwiseOperations.cpp