Compute Library: DependencyGraph Class Reference
DependencyGraph Class Reference
The dependency graph of a workload, where the nodes are of 2 types: Tensor or Operator Represented as a doubly-linked adjacency list with the differentiation between source and destination.
#include <DependencyGraph.h>
Data Structures
struct OpPack
A pack of operator including its input and output tensors, used by traversing through the graph in topological order.
class SerialIdAllocator
A serial Id allocator.
Public Types
using Id = SerialIdAllocator::Id
using AdjList = std::map< Id, std::vector< Id > >
Adjacency list.
Public Member Functions
DependencyGraph ()=default
DependencyGraph (const std::vector< Id > &imported_tensors)
DependencyGraph (const AdjList &adj_src_tensors, const AdjList &adj_dst_tensors, const AdjList &adj_src_ops, const AdjList &adj_dst_ops, std::map< Id, Id > merge_points={})
Id add_tensor (Id merge_tensor=empty_id())
Add a new tensor.
void remove_tensor (Id tensor)
std::pair< Status, DependencyGraph::Id > add_operator (const std::vector< Id > &inputs, const std::vector< Id > &outputs)
Add a new operator.
void remove_operator (Id op)
std::pair< Status, std::vector< OpPack > > topological_sort () const
Sort the graph in a topological order.
std::vector< Id > src_ops (Id op) const
std::vector< Id > dst_ops (Id op) const
std::vector< Id > src_ops_from_tensor (Id tensor) const
std::vector< Id > dst_ops_from_tensor (Id tensor) const
std::map< Id, Id > get_merge_points () const
Get the merge points object.
std::vector< Id > get_root_ops () const
Get all root ops.
std::vector< Id > get_dst_ops () const
Get all dst ops of the whole graph.
std::vector< Id > src_tensors (Id op) const
Get source tensors to an operator.
std::vector< Id > dst_tensors (Id op) const
Get destination tensors to an operator.
std::vector< Id > src_tensors () const
Get source tensors of the whole graph.
std::vector< Id > dst_tensors () const
Get destination tensors of the whole graph.
std::vector< Id > all_ops () const
Get all operators.
std::vector< Id > all_tensors () const
Get all tensors.
unsigned int number_of_ops () const
Number of operators.
unsigned int number_of_tensors () const
Number of tensors.
Status update_merge_point (Id t_id, Id merge_point)
Update merge_point to point to t_id.
void link_input (Id op, Id in_tensor)
void link_output (Id op, Id out_tensor)
bool path_exists_from_tensor_to_op (Id src_tensor, Id dst_op) const
Check if there's a path from src_tensor to dst_op.
bool path_exists_from_op_to_op (Id src_op, Id dst_op) const
Check if there's a path from src_op to dst_op.
bool is_src_tensor (Id tensor) const
Check if tensor is the src tensor of the entire graph.
bool is_dst_tensor (Id tensor) const
Check if tensor is the dst tensor of the entire graph.
Static Public Member Functions
static constexpr Id empty_id ()
Friends
bool operator== (const DependencyGraph &g0, const DependencyGraph &g1)
Strict equality comparison (all internal ids and order of insertion matter).
Detailed Description
The dependency graph of a workload, where the nodes are of 2 types: Tensor or Operator Represented as a doubly-linked adjacency list with the differentiation between source and destination.
A "Merge Tensor" is an external tensor associated with the tensor within the graph, and serve as a merge point
Definition at line 51 of file DependencyGraph.h.
Member Typedef Documentation
AdjList
using AdjList = std::map<Id, std::vector<Id> >
Adjacency list.
Definition at line 77 of file DependencyGraph.h.
Id
using Id = SerialIdAllocator::Id
Definition at line 73 of file DependencyGraph.h.
Constructor & Destructor Documentation
DependencyGraph() [1/3]
DependencyGraph () default
Referenced by DependencyGraph::empty_id().
DependencyGraph() [2/3]
DependencyGraph (const std::vector< Id > & imported_tensors) explicit
Definition at line 41 of file DependencyGraph.cpp.
References tf_frozen_model_extractor::t.
     : _adj_src_tensors{}, _adj_dst_tensors{}, _adj_src_ops{}, _adj_dst_ops{}, _merge_to_internal{}, _operator_id{}, _tensor_id{}
 {
     for(auto t : imported_tensors)
     {
         _adj_src_ops[t] = {};
         _adj_dst_ops[t] = {};
     }
 }
DependencyGraph() [3/3]
DependencyGraph (const AdjList & adj_src_tensors, const AdjList & adj_dst_tensors, const AdjList & adj_src_ops, const AdjList & adj_dst_ops, std::map< Id, Id > merge_points = {})
Definition at line 37 of file DependencyGraph.cpp.
     : _adj_src_tensors{ adj_src_tensors }, _adj_dst_tensors{ adj_dst_tensors }, _adj_src_ops{ adj_src_ops }, _adj_dst_ops{ adj_dst_ops }, _merge_to_internal{ merge_points }, _operator_id{}, _tensor_id{}
 {
 }
Member Function Documentation
add_operator()
std::pair< Status, DependencyGraph::Id > add_operator (const std::vector< Id > & inputs, const std::vector< Id > & outputs)
Add a new operator.
Parameters
inputs Input tensors to the operator
outputs Output tensors to the operator
Returns
std::pair<Status, DependencyGraph::Id> where id is the newly allocated operator
Definition at line 103 of file DependencyGraph.cpp.
References DependencyGraph::link_input(), DependencyGraph::link_output(), and DependencyGraph::topological_sort().
Referenced by ClKernelFusionGroup::add_fused_kernel(), arm_compute::experimental::dynamic_fusion::add_op_conv2d(), arm_compute::experimental::dynamic_fusion::add_op_elementwise_add(), and DependencyGraph::empty_id().
 {
     Id new_op = insert_new_op();
     for(Id tensor : inputs)
     {
         link_input(new_op, tensor);
     }
     for(Id tensor : outputs)
     {
         link_output(new_op, tensor);
     }
     // Use topological sort in order to detect possible loops / cycles.
     // NOTE: This is unscalable. We'll need to have a better way of detecting loops or relax this invariant during operation, and add a validate method instead
     return std::pair<Status, DependencyGraph::Id>(topological_sort().first, new_op);
 }
add_tensor()
DependencyGraph::Id add_tensor (Id merge_tensor = empty_id())
Add a new tensor.
Parameters
merge_tensor The external merge point associated with the tensor. Leave empty if not needed.
Returns
Id The newly allocated tensor, or a previously added tensor associated with merge_tensor
Definition at line 61 of file DependencyGraph.cpp.
References DependencyGraph::empty_id().
Referenced by ClKernelFusionGroup::add_fused_kernel(), arm_compute::experimental::dynamic_fusion::add_tensor(), DependencyGraph::empty_id(), and arm_compute::test::validation::TEST_CASE().
 {
     Id new_tensor{ empty_id() };
     if(merge_tensor != empty_id())
     {
         if(_merge_to_internal.find(merge_tensor) != _merge_to_internal.end())
         {
             new_tensor = _merge_to_internal[merge_tensor];
         }
         else
         {
             new_tensor                       = insert_new_tensor();
             _merge_to_internal[merge_tensor] = new_tensor;
         }
     }
     else
     {
         new_tensor = insert_new_tensor();
     }
     return new_tensor;
 }
all_ops()
std::vector< DependencyGraph::Id > all_ops () const
Get all operators.
Returns
std::vector<Id>
Definition at line 218 of file DependencyGraph.cpp.
References arm_compute::mlgo::parser::end().
Referenced by DependencyGraph::empty_id(), DependencyGraph::get_dst_ops(), DependencyGraph::get_root_ops(), and DependencyGraph::topological_sort().
 {
     std::vector<Id> ops{};
     std::transform(std::begin(_adj_src_tensors), std::end(_adj_src_tensors), std::back_inserter(ops), [](const auto & it)
     {
         return it.first;
     });
     return ops;
 }
all_tensors()
std::vector< DependencyGraph::Id > all_tensors () const
Get all tensors.
Returns
std::vector<Id>
Definition at line 260 of file DependencyGraph.cpp.
References arm_compute::mlgo::parser::end().
Referenced by DependencyGraph::empty_id().
 {
     std::vector<Id> tensors{};
     std::transform(std::begin(_adj_src_ops), std::end(_adj_src_ops), std::back_inserter(tensors), [](const auto & it)
     {
         return it.first;
     });
     return tensors;
 }
dst_ops()
std::vector< DependencyGraph::Id > dst_ops (Id op) const
Definition at line 369 of file DependencyGraph.cpp.
References ARM_COMPUTE_ERROR_ON, and arm_compute::mlgo::parser::end().
Referenced by DependencyGraph::empty_id(), DependencyGraph::get_dst_ops(), DependencyGraph::remove_operator(), and DependencyGraph::topological_sort().
 {
     ARM_COMPUTE_ERROR_ON(!operator_exists(op));
     std::vector<Id> ops{};
     for(Id dst_tensor : _adj_dst_tensors.at(op))
     {
         ops.insert(ops.end(), std::begin(_adj_dst_ops.at(dst_tensor)), std::end(_adj_dst_ops.at(dst_tensor)));
     }
     return ops;
 }
dst_ops_from_tensor()
std::vector< DependencyGraph::Id > dst_ops_from_tensor (Id tensor) const
Definition at line 213 of file DependencyGraph.cpp.
Referenced by DependencyGraph::empty_id(), and DependencyGraph::path_exists_from_tensor_to_op().
 {
     return _adj_dst_ops.at(tensor);
 }
dst_tensors() [1/2]
std::vector< DependencyGraph::Id > dst_tensors (Id op) const
Get destination tensors to an operator.
Parameters
op
Returns
std::vector<Id>
Definition at line 181 of file DependencyGraph.cpp.
References ARM_COMPUTE_ERROR_ON.
Referenced by arm_compute::experimental::dynamic_fusion::build(), arm_compute::experimental::dynamic_fusion::generate(), arm_compute::experimental::dynamic_fusion::generate_store(), and ClKernelFusionGroup::get_dst_tensors().
 {
     ARM_COMPUTE_ERROR_ON(!operator_exists(op));
     return _adj_dst_tensors.at(op);
 }
dst_tensors() [2/2]
std::vector< DependencyGraph::Id > dst_tensors () const
Get destination tensors of the whole graph.
Returns
std::vector<Id>
Definition at line 198 of file DependencyGraph.cpp.
Referenced by DependencyGraph::empty_id(), DependencyGraph::is_dst_tensor(), DependencyGraph::path_exists_from_op_to_op(), DependencyGraph::remove_tensor(), and DependencyGraph::topological_sort().
 {
     std::vector<Id> tensors;
     for(auto tensor_dst_ops : _adj_dst_ops)
     {
         if(tensor_dst_ops.second.empty())
             tensors.push_back(tensor_dst_ops.first);
     }
     return tensors;
 }
empty_id()
static constexpr Id empty_id () inline static
Definition at line 97 of file DependencyGraph.h.
References DependencyGraph::add_operator(), DependencyGraph::add_tensor(), DependencyGraph::all_ops(), DependencyGraph::all_tensors(), DependencyGraph::DependencyGraph(), DependencyGraph::dst_ops(), DependencyGraph::dst_ops_from_tensor(), DependencyGraph::dst_tensors(), DependencyGraph::SerialIdAllocator::empty(), DependencyGraph::get_dst_ops(), DependencyGraph::get_merge_points(), DependencyGraph::get_root_ops(), DependencyGraph::number_of_ops(), DependencyGraph::number_of_tensors(), DependencyGraph::remove_operator(), DependencyGraph::remove_tensor(), DependencyGraph::src_ops(), DependencyGraph::src_ops_from_tensor(), DependencyGraph::src_tensors(), DependencyGraph::topological_sort(), and DependencyGraph::update_merge_point().
Referenced by DependencyGraph::add_tensor().
     {
         return SerialIdAllocator::empty();
     }
get_dst_ops()
std::vector< DependencyGraph::Id > get_dst_ops () const
Get all dst ops of the whole graph.
Returns
std::vector<Id>
Definition at line 160 of file DependencyGraph.cpp.
References DependencyGraph::all_ops(), and DependencyGraph::dst_ops().
Referenced by DependencyGraph::empty_id(), and DependencyGraph::path_exists_from_op_to_op().
 {
     std::vector<Id> ops{};
     const auto      op_list = all_ops();
     for(auto op : op_list)
     {
         if(dst_ops(op).empty())
         {
             ops.emplace_back(op);
         }
     }
     return ops;
 }
get_merge_points()
std::map< DependencyGraph::Id, DependencyGraph::Id > get_merge_points () const
Get the merge points object.
Returns
std::map<Id, Id>
Definition at line 140 of file DependencyGraph.cpp.
Referenced by arm_compute::experimental::dynamic_fusion::build(), and DependencyGraph::empty_id().
 {
     return _merge_to_internal;
 }
get_root_ops()
std::vector< DependencyGraph::Id > get_root_ops () const
Get all root ops.
Root ops can also be referred to as "src ops" of the whole graph
Returns
std::vector<Id>
Definition at line 145 of file DependencyGraph.cpp.
References DependencyGraph::all_ops(), and DependencyGraph::src_ops().
Referenced by arm_compute::experimental::dynamic_fusion::add_op_conv2d(), DependencyGraph::empty_id(), ClKernelBlueprint::Implementation::get_graph(), and ClKernelFusionGroup::get_root_kernel().
 {
     std::vector<Id> ops{};
     const auto      op_list = all_ops();
     for(auto op : op_list)
     {
         if(src_ops(op).empty())
         {
             ops.emplace_back(op);
         }
     }
     return ops;
 }
is_dst_tensor()
bool is_dst_tensor (Id tensor) const
Check if tensor is the dst tensor of the entire graph.
Parameters
tensor
Returns
true
false
Definition at line 328 of file DependencyGraph.cpp.
References DependencyGraph::dst_tensors(), and DependencyGraph::src_tensors().
 {
     if(!tensor_exists(tensor))
     {
         return false;
     }
     return _adj_dst_ops.at(tensor).empty();
 }
is_src_tensor()
bool is_src_tensor (Id tensor) const
Check if tensor is the src tensor of the entire graph.
Parameters
tensor
Returns
true
false
Definition at line 319 of file DependencyGraph.cpp.
 {
     if(!tensor_exists(tensor))
     {
         return false;
     }
     return _adj_src_ops.at(tensor).empty();
 }
link_input()
void link_input (Id op, Id in_tensor)
Definition at line 294 of file DependencyGraph.cpp.
References ARM_COMPUTE_ERROR_ON.
Referenced by DependencyGraph::add_operator().
 {
     ARM_COMPUTE_ERROR_ON(!operator_exists(op));
     ARM_COMPUTE_ERROR_ON(!tensor_exists(in_tensor));
     ARM_COMPUTE_ERROR_ON(are_connected(op, in_tensor));
     _adj_src_tensors[op].push_back(in_tensor);
     _adj_dst_ops[in_tensor].push_back(op);
 }
link_output()
void link_output (Id op, Id out_tensor)
Definition at line 302 of file DependencyGraph.cpp.
References ARM_COMPUTE_ERROR_ON.
Referenced by DependencyGraph::add_operator().
 {
     ARM_COMPUTE_ERROR_ON(!operator_exists(op));
     ARM_COMPUTE_ERROR_ON(!tensor_exists(out_tensor));
     ARM_COMPUTE_ERROR_ON(are_connected(op, out_tensor));
     _adj_dst_tensors[op].push_back(out_tensor);
     _adj_src_ops[out_tensor].push_back(op);
 }
number_of_ops()
unsigned int number_of_ops () const
Number of operators.
Returns
unsigned int
Definition at line 270 of file DependencyGraph.cpp.
Referenced by DependencyGraph::empty_id(), and DependencyGraph::topological_sort().
 {
     return _adj_src_tensors.size();
 }
number_of_tensors()
unsigned int number_of_tensors () const
Number of tensors.
Returns
unsigned int
Definition at line 275 of file DependencyGraph.cpp.
References DependencyGraph::SerialIdAllocator::alloc().
Referenced by DependencyGraph::empty_id().
 {
     return _adj_src_ops.size();
 }
path_exists_from_op_to_op()
bool path_exists_from_op_to_op (Id src_op, Id dst_op) const
Check if there's a path from src_op to dst_op.
Parameters
src_op
dst_op
Returns
true
false
Definition at line 240 of file DependencyGraph.cpp.
References DependencyGraph::dst_tensors(), DependencyGraph::get_dst_ops(), arm_compute::experimental::dynamic_fusion::is_in(), and DependencyGraph::path_exists_from_tensor_to_op().
Referenced by DependencyGraph::path_exists_from_tensor_to_op().
 {
     if(src_op == dst_op)
     {
         return true;
     }
     if(is_in(src_op, get_dst_ops()))
     {
         return false;
     }
     for(auto child_tensor : dst_tensors(src_op))
     {
         if(path_exists_from_tensor_to_op(child_tensor, dst_op))
         {
             return true;
         }
     }
     return false;
 }
path_exists_from_tensor_to_op()
bool path_exists_from_tensor_to_op (Id src_tensor, Id dst_op) const
Check if there's a path from src_tensor to dst_op.
Parameters
src_tensor
dst_op
Returns
true
false
Definition at line 228 of file DependencyGraph.cpp.
References DependencyGraph::dst_ops_from_tensor(), and DependencyGraph::path_exists_from_op_to_op().
Referenced by DependencyGraph::path_exists_from_op_to_op().
 {
     for(auto child_op : dst_ops_from_tensor(src_tensor))
     {
         if(path_exists_from_op_to_op(child_op, dst_op))
         {
             return true;
         }
     }
     return false;
 }
remove_operator()
void remove_operator (Id op)
Definition at line 120 of file DependencyGraph.cpp.
References DependencyGraph::dst_ops(), arm_compute::mlgo::parser::end(), and DependencyGraph::src_ops().
Referenced by DependencyGraph::empty_id().
 {
     for(auto src_tensor : _adj_src_tensors.at(op))
     {
         auto &dst_ops = _adj_dst_ops.at(src_tensor);
         dst_ops.erase(
             std::remove(std::begin(dst_ops), std::end(dst_ops), op),
             std::end(dst_ops));
     }
     for(auto dst_tensor : _adj_dst_tensors.at(op))
     {
         auto &src_ops = _adj_src_ops.at(dst_tensor);
         src_ops.erase(
             std::remove(std::begin(src_ops), std::end(src_ops), op),
             std::end(src_ops));
     }
     _adj_src_tensors.erase(op);
     _adj_dst_tensors.erase(op);
 }
remove_tensor()
void remove_tensor (Id tensor)
Definition at line 83 of file DependencyGraph.cpp.
References DependencyGraph::dst_tensors(), arm_compute::mlgo::parser::end(), and DependencyGraph::src_tensors().
Referenced by DependencyGraph::empty_id().
 {
     for(auto src_op : _adj_src_ops.at(tensor))
     {
         auto &dst_tensors = _adj_dst_tensors.at(src_op);
         dst_tensors.erase(
             std::remove(std::begin(dst_tensors), std::end(dst_tensors), tensor),
             std::end(dst_tensors));
     }
     for(auto dst_op : _adj_dst_ops.at(tensor))
     {
         auto &src_tensors = _adj_src_tensors.at(dst_op);
         src_tensors.erase(
             std::remove(std::begin(src_tensors), std::end(src_tensors), tensor),
             std::end(src_tensors));
     }
     _adj_src_ops.erase(tensor);
     _adj_dst_ops.erase(tensor);
 }
src_ops()
std::vector< DependencyGraph::Id > src_ops (Id op) const
Definition at line 358 of file DependencyGraph.cpp.
References ARM_COMPUTE_ERROR_ON, arm_compute::mlgo::parser::end(), and DependencyGraph::src_tensors().
Referenced by DependencyGraph::empty_id(), DependencyGraph::get_root_ops(), DependencyGraph::remove_operator(), and DependencyGraph::topological_sort().
 {
     ARM_COMPUTE_ERROR_ON(!operator_exists(op));
     std::vector<Id> ops{};
     for(Id src_tensor : src_tensors(op))
     {
         ops.insert(ops.end(), std::begin(_adj_src_ops.at(src_tensor)), std::end(_adj_src_ops.at(src_tensor)));
     }
     return ops;
 }
src_ops_from_tensor()
std::vector< DependencyGraph::Id > src_ops_from_tensor (Id tensor) const
Definition at line 209 of file DependencyGraph.cpp.
Referenced by DependencyGraph::empty_id().
 {
     return _adj_src_ops.at(tensor);
 }
src_tensors() [1/2]
std::vector< DependencyGraph::Id > src_tensors (Id op) const
Get source tensors to an operator.
Parameters
op
Returns
std::vector<Id>
Definition at line 175 of file DependencyGraph.cpp.
References ARM_COMPUTE_ERROR_ON.
Referenced by arm_compute::experimental::dynamic_fusion::build(), arm_compute::experimental::dynamic_fusion::generate(), and ClKernelFusionGroup::get_src_tensors().
 {
     ARM_COMPUTE_ERROR_ON(!operator_exists(op));
     return _adj_src_tensors.at(op);
 }
src_tensors() [2/2]
std::vector< DependencyGraph::Id > src_tensors () const
Get source tensors of the whole graph.
Returns
std::vector<Id>
Definition at line 187 of file DependencyGraph.cpp.
Referenced by DependencyGraph::empty_id(), DependencyGraph::is_dst_tensor(), DependencyGraph::remove_tensor(), DependencyGraph::src_ops(), and DependencyGraph::topological_sort().
 {
     std::vector<Id> tensors;
     for(auto tensor_src_ops : _adj_src_ops)
     {
         if(tensor_src_ops.second.empty())
             tensors.push_back(tensor_src_ops.first);
     }
     return tensors;
 }
topological_sort()
std::pair< Status, std::vector< DependencyGraph::OpPack > > topological_sort () const
Sort the graph in a topological order.
Returns
std::pair<Status, std::vector<OpPack>>
Definition at line 380 of file DependencyGraph.cpp.
References DependencyGraph::all_ops(), DependencyGraph::dst_ops(), DependencyGraph::dst_tensors(), DependencyGraph::number_of_ops(), arm_compute::RUNTIME_ERROR, DependencyGraph::src_ops(), and DependencyGraph::src_tensors().
Referenced by DependencyGraph::add_operator(), ClCompositeOperator::configure(), DependencyGraph::empty_id(), and arm_compute::experimental::dynamic_fusion::traverse().
 {
     // Incident degree (number of source operators to an op)
     std::map<Id, unsigned int> in_degree{};
     std::set<Id>        visited_ops{};
     std::deque<Id>      zero_in_degree_ops{};
     std::vector<OpPack> sorted_op_packs{};
     for(auto op : all_ops())
     {
         const auto degree = src_ops(op).size();
         in_degree[op]     = degree;
         if(degree == 0)
         {
             zero_in_degree_ops.push_back(op);
             visited_ops.insert(op);
         }
     }
     while(!zero_in_degree_ops.empty())
     {
         const Id op = zero_in_degree_ops.front();
         zero_in_degree_ops.pop_front();
         sorted_op_packs.push_back(OpPack{ op, src_tensors(op), dst_tensors(op) });
         for(const auto next_op : dst_ops(op))
         {
             if(in_degree[next_op] > 0)
             {
                 in_degree[next_op]--;
             }
             if(in_degree[next_op] == 0 && visited_ops.find(next_op) == visited_ops.end())
             {
                 zero_in_degree_ops.push_back(next_op);
                 visited_ops.insert(op);
             }
         }
     }
     // If there are remaining ops with in_degree > 0, then it's indication that there are cycles in the graph
     Status st{};
     if(sorted_op_packs.size() != number_of_ops())
     {
         st = Status{ ErrorCode::RUNTIME_ERROR, "Cycles or loops are not allowed in a DependencyGraph" };
     }
     return std::make_pair(st, sorted_op_packs);
 }
update_merge_point()
Status update_merge_point (Id t_id, Id merge_point)
Update merge_point to point to t_id.
Parameters
t_id
merge_point
Definition at line 51 of file DependencyGraph.cpp.
References arm_compute::RUNTIME_ERROR.
Referenced by DependencyGraph::empty_id().
 {
     if(_merge_to_internal.find(merge_point) == _merge_to_internal.end())
     {
         return Status{ ErrorCode::RUNTIME_ERROR, "Merge point does not exist" };
     }
     _merge_to_internal[merge_point] = t_id;
     return Status{};
 }
Friends And Related Function Documentation
operator==
bool operator== (const DependencyGraph & g0, const DependencyGraph & g1) friend
Strict equality comparison (all internal ids and order of insertion matter).
In the future this may be replaced with a topological comparison, allowing equivalent graphs with different internal ids to be equal
Parameters
g0
g1
Returns
true
false
Definition at line 212 of file DependencyGraph.h.
     {
         // Do not compare id allocators
         return std::make_tuple(
                    g0._adj_src_tensors, g0._adj_dst_tensors, g0._adj_src_ops, g0._adj_dst_ops, g0._merge_to_internal)
                == std::make_tuple(
                    g1._adj_src_tensors, g1._adj_dst_tensors, g1._adj_src_ops, g1._adj_dst_ops, g1._merge_to_internal);
     }
The documentation for this class was generated from the following files:
arm_compute/core/experimental/DependencyGraph.h
src/core/experimental/dynamic_fusion/WorkloadImpl/DependencyGraph.cpp