Compute Library: GemmHybridQuantized< strategy, To, Tr > Class Template Reference
GemmHybridQuantized< strategy, To, Tr > Class Template Reference
#include <gemm_hybrid_quantized.hpp>
Public Member Functions
GemmHybridQuantized (GemmHybridQuantized &)=delete
GemmHybridQuantized & operator= (GemmHybridQuantized &)=delete
GemmHybridQuantized (const GemmArgs &args, const Requantize32 &qp)
ndrange_t get_window_size () const override
bool supports_dynamic_scheduling () const override
void execute (const ndcoord_t &work_range, const ndcoord_t &, int threadid) override
Main execute member fucntion.
size_t get_working_size () const override
void set_working_space (void *buffer) override
bool B_is_pretransposed () const override
bool B_pretranspose_required () const override
size_t get_B_pretransposed_array_size () const override
void requantize_bias (void *in_buffer, const To *B, const int ldb, const int B_multi_stride) override
void pretranspose_B_array (void *in_buffer, const To *B, const int ldb, const int B_multi_stride) override
void set_pretransposed_B_data (void *in_buffer) override
void set_quantized_bias (const int32_t *bias, size_t bias_multi_stride) override
GemmConfig get_config () override
Public Member Functions inherited from GemmCommon< To, Tr >
virtual void set_arrays (const To *A, const int lda, const int A_batch_stride, const int A_multi_stride, const To *B, const int ldb, const int B_multi_stride, Tr *C, const int ldc, const int C_batch_stride, const int C_multi_stride, const Tr *bias, const int bias_multi_stride)
void set_arrays_generic (const void *A, const int lda, const int A_batch_stride, const int A_multi_stride, const void *B, const int ldb, const int B_multi_stride, void *C, const int ldc, const int C_batch_stride, const int C_multi_stride, const void *bias, const int bias_multi_stride) override
void pretranspose_B_array_generic (void *out, const void *in, const int row_stride, const int multi_stride) override
virtual void set_indirect_parameters (size_t, const To *const *const *)
void set_indirect_parameters_generic (size_t sz, const void *const *const *ptr) override
Public Member Functions inherited from IGemmCommon
virtual void set_nthreads (int)
virtual void set_convolution_parameters (ConvolutionParameters)
virtual ~IGemmCommon ()
Detailed Description
template<typename strategy, typename To, typename Tr>
class arm_gemm::GemmHybridQuantized< strategy, To, Tr >
Definition at line 45 of file gemm_hybrid_quantized.hpp.
Constructor & Destructor Documentation
GemmHybridQuantized() [1/2]
GemmHybridQuantized (GemmHybridQuantized< strategy, To, Tr > &) delete
GemmHybridQuantized() [2/2]
GemmHybridQuantized (const GemmArgs & args, const Requantize32 & qp) inline
Definition at line 156 of file gemm_hybrid_quantized.hpp.
               : _ci(args._ci), _Msize(args._Msize), _Nsize(args._Nsize), _Ksize(args._Ksize),
                 _nbatches(args._nbatches), _nmulti(args._nmulti),
                 _k_block(compute_k_block(args)), _n_block(compute_n_block(args)),
                 _Mround(roundup(args._Msize, strategy::out_height())),
                 _window_range(iceildiv(args._Msize, strategy::out_height()), _nbatches, iceildiv(_Nsize, _n_block), _nmulti),
                 _qp (qp), _nthreads(args._maxthreads) { }
Member Function Documentation
B_is_pretransposed()
bool B_is_pretransposed () const inline override virtual
Reimplemented from IGemmCommon.
Definition at line 260 of file gemm_hybrid_quantized.hpp.
{
         return true;
     }
B_pretranspose_required()
bool B_pretranspose_required () const inline override virtual
Reimplemented from IGemmCommon.
Definition at line 264 of file gemm_hybrid_quantized.hpp.
{
         return (_B_transposed==nullptr);
     }
execute()
void execute (const ndcoord_t & work_range, const ndcoord_t & thread_locator, int threadid) inline override virtual
Main execute member fucntion.
Parameters
[in] work_range specifies the range of work we want to be computed, total range defined by get_window_size()
[in] thread_locator where are we inside of the thread space
[in] threadid a unique threadid
Implements IGemmCommon.
Definition at line 175 of file gemm_hybrid_quantized.hpp.
References arm_compute::test::validation::batch, arm_gemm::compute_row_sums(), NDCoordinate< N >::get_position(), NDCoordinate< N >::get_position_end(), NDRange< D >::iterator(), arm_gemm::requantize_block_32(), arm_gemm::roundup(), and strategy.
{
 #ifdef CYCLE_PROFILING
         profiler prof;
 #endif
         strategy strat(_ci);
         uintptr_t working_int = reinterpret_cast<uintptr_t>(working_space);
         Tri *result_buffer = reinterpret_cast<Tri *>(working_int + (threadid * strategy::out_height() * _Nsize * sizeof(Tri)));
         /* Make sure we've been set up correctly. */
         assert(_B_transposed);
         static_assert(std::is_same<To, Toi>::value, "gemm_native: Operand types must be the same.");
         /* For now, each work item implies all the K for a given output
          * pixel (so we don't need to synchronize access to the output
          * array).  So separate the loop over K blocks here.  */
         for (unsigned int k0=0; k0<_Ksize; k0+=_k_block) {
             unsigned int kmax   = std::min(k0 + _k_block, _Ksize);
             unsigned int kern_k = roundup(kmax-k0, strategy::k_unroll());
             auto p = _window_range.iterator(work_range.get_position(0), work_range.get_position_end(0));
             if (p.done()) {
                 return;
             }
             do {
                 const unsigned int m_start = p.dim(0) * strategy::out_height();
                 const unsigned int m_end   = std::min((p.dim(0) + 1) * strategy::out_height(), _Msize);
                 const unsigned int batch   = p.dim(1);
                 const unsigned int n0      = p.dim(2) * _n_block;
                 const unsigned int nmax    = std::min(n0 + _n_block, _Nsize);
                 const unsigned int multi   = p.dim(3);
                 int32_t local_row_sums[strategy::out_height()];
                 const Toi *b_panel = _B_transposed +
                                      (multi * roundup(_Nsize, strategy::out_width()) * roundup(_Ksize, strategy::k_unroll())) +
                                      (k0 * roundup(_Nsize, strategy::out_width())) +
                                      (n0 * kern_k);
                 {
 #ifdef CYCLE_PROFILING
                     auto p = prof.ScopedProfiler(PROFILE_KERNEL, (m_end - m_start) * kern_k * roundup(nmax-n0, strategy::out_width()));
 #endif
                     strat.kernel(this->_Aptr + (multi * this->_A_multi_stride) + (batch * this->_A_batch_stride) + (m_start * this->_lda) + k0, this->_lda,
                                  b_panel,
                                  result_buffer, (nmax-n0),
                                  (m_end - m_start), (nmax - n0), kern_k,
                                  nullptr, Activation(), false);
                 }
                 {
 #ifdef CYCLE_PROFILING
                     auto p = prof.ScopedProfiler(PROFILE_ROWSUMS, (m_end - m_start) * _Ksize);
 #endif
                     compute_row_sums(_qp, _Ksize, (m_end - m_start),
                                      this->_Aptr + (multi * this->_A_multi_stride) + (batch * this->_A_batch_stride) + (m_start * this->_lda), this->_lda,
                                      local_row_sums);
                 }
                 {
 #ifdef CYCLE_PROFILING
                     auto p = prof.ScopedProfiler(PROFILE_QUANTIZE, (m_end - m_start) * _Nsize);
 #endif
                     requantize_block_32(_qp, (nmax - n0), (m_end - m_start), result_buffer, (nmax - n0),
                                         this->_Cptr + (multi * this->_C_multi_stride) + (batch * this->_C_batch_stride) + (m_start * this->_ldc) + n0, this->_ldc,
                                         local_row_sums, col_bias + (multi * _Nsize) + n0, n0);
                 }
             } while (p.next_dim0());
         }
     }
get_B_pretransposed_array_size()
size_t get_B_pretransposed_array_size () const inline override virtual
Reimplemented from IGemmCommon.
Definition at line 268 of file gemm_hybrid_quantized.hpp.
References arm_gemm::roundup().
{
         return get_col_sum_size() + (roundup(_Nsize, strategy::out_width()) * roundup(_Ksize, strategy::k_unroll()) * _nmulti * sizeof(Toi));
     }
get_config()
GemmConfig get_config () inline override virtual
Implements IGemmCommon.
Definition at line 318 of file gemm_hybrid_quantized.hpp.
References GemmConfig::filter, arm_gemm::GEMM_HYBRID, GemmConfig::inner_block_size, GemmConfig::method, and GemmConfig::outer_block_size.
{
         GemmConfig c;
         c.method = GemmMethod::GEMM_HYBRID;
         c.inner_block_size = _k_block;
         c.outer_block_size = _n_block;
         c.filter = get_type_name<strategy>();
         return c;
     }
get_window_size()
ndrange_t get_window_size () const inline override virtual
Returns
an ndrange containing ranges of the compute space which can be broken up and parallelised over
Implements IGemmCommon.
Definition at line 165 of file gemm_hybrid_quantized.hpp.
References NDRange< D >::total_size().
{
         return { _window_range.total_size() };
     }
get_working_size()
size_t get_working_size (void) const inline override virtual
Reimplemented from IGemmCommon.
Definition at line 251 of file gemm_hybrid_quantized.hpp.
{
         return (_nthreads * strategy::out_height() * _Nsize * sizeof(Tri));
     }
operator=()
GemmHybridQuantized& operator= (GemmHybridQuantized< strategy, To, Tr > &) delete
pretranspose_B_array()
void pretranspose_B_array (void * in_buffer, const To * B, const int ldb, const int B_multi_stride) inline override virtual
Reimplemented from GemmCommon< To, Tr >.
Definition at line 280 of file gemm_hybrid_quantized.hpp.
References GemmHybridQuantized< strategy, To, Tr >::requantize_bias(), arm_gemm::roundup(), and strategy.
{
         requantize_bias(in_buffer, B, ldb, B_multi_stride);
         uintptr_t buffer_int = reinterpret_cast<uintptr_t>(in_buffer);
         Toi *buffer = reinterpret_cast<Toi *>(buffer_int + get_col_sum_size());
         _B_transposed = buffer;
         strategy strat(_ci);
         for (unsigned int multi=0; multi<_nmulti; multi++) {
             for (unsigned int k0=0; k0<_Ksize; k0+=_k_block) {
                 const unsigned int kmax = std::min(k0 + _k_block, _Ksize);
                 const unsigned int k_size = roundup(kmax-k0, strategy::k_unroll());
                 for (unsigned int x0=0; x0<_Nsize; x0+=_n_block) {
                     const unsigned int xmax = std::min(x0+_n_block, _Nsize);
                     const unsigned int size = roundup(xmax-x0, strategy::out_width()) * k_size;
                     strat.transforms.PrepareB( buffer, B + (multi * B_multi_stride), ldb,
                                                x0, xmax, k0, kmax);
                     buffer += size;
                 }
             }
         }
     }
requantize_bias()
void requantize_bias (void * in_buffer, const To * B, const int ldb, const int B_multi_stride) inline override virtual
Reimplemented from GemmCommon< To, Tr >.
Definition at line 272 of file gemm_hybrid_quantized.hpp.
References arm_gemm::compute_col_sums().
Referenced by GemmHybridQuantized< strategy, To, Tr >::pretranspose_B_array().
{
         col_bias = reinterpret_cast<int32_t *>(in_buffer);
         for (unsigned int i=0; i<_nmulti; i++) {
             compute_col_sums(_qp, _Nsize, _Ksize, B + (i * B_multi_stride), ldb, col_bias + (i * _Nsize),  _Ksize, i, 0);
         }
     }
set_pretransposed_B_data()
void set_pretransposed_B_data (void * in_buffer) inline override virtual
Reimplemented from IGemmCommon.
Definition at line 307 of file gemm_hybrid_quantized.hpp.
{
         uintptr_t buffer_int = reinterpret_cast<uintptr_t>(in_buffer);
         _B_transposed = reinterpret_cast<Toi *>(buffer_int + get_col_sum_size());
         col_bias = reinterpret_cast<int32_t *>(in_buffer);
     }
set_quantized_bias()
void set_quantized_bias (const int32_t * bias, size_t bias_multi_stride) inline override virtual
Reimplemented from IGemmCommon.
Definition at line 313 of file gemm_hybrid_quantized.hpp.
References Requantize32::bias, bias, and Requantize32::bias_multi_stride.
{
         _qp.bias = bias;
         _qp.bias_multi_stride = bias_multi_stride;
     }
set_working_space()
void set_working_space (void * buffer) inline override virtual
Reimplemented from IGemmCommon.
Definition at line 255 of file gemm_hybrid_quantized.hpp.
{
         working_space = buffer;
     }
supports_dynamic_scheduling()
bool supports_dynamic_scheduling () const inline override virtual
Reimplemented from IGemmCommon.
Definition at line 170 of file gemm_hybrid_quantized.hpp.
{
         return true;
     }
The documentation for this class was generated from the following file:
src/core/NEON/kernels/arm_gemm/gemm_hybrid_quantized.hpp