Compute Library: BoxNMSLimitInfo Class Reference
BoxNMSLimitInfo Class Reference final
BoxWithNonMaximaSuppressionLimit Information class.
#include <Types.h>
Public Member Functions
BoxNMSLimitInfo (float score_thresh=0.05f, float nms=0.3f, int detections=100, bool soft_nms_enabled=false, NMSType soft_nms_method=NMSType::LINEAR, float soft_nms_sigma=0.5f, float soft_nms_min_score_thres=0.001f, bool suppress_size=false, float min_size=1.0f, float im_width=1.0f, float im_height=1.0f)
Constructor.
float score_thresh () const
Get the score threshold.
float nms () const
Get the NMS.
int detections_per_im () const
Get the number of detections.
bool soft_nms_enabled () const
Check if soft NMS is enabled.
NMSType soft_nms_method () const
Get soft NMS method.
float soft_nms_sigma () const
Get soft NMS sigma.
float soft_nms_min_score_thres () const
Get soft nms min score threshold.
bool suppress_size () const
Get if NMS will suppress boxes based on their size/position.
float min_size () const
Get size suppression threshold.
float im_width () const
Get image width (NMS may suppress boxes whose center sits beyond the image width)
float im_height () const
Get image height (NMS may suppress boxes whose center sits beyond the image height)
Detailed Description
BoxWithNonMaximaSuppressionLimit Information class.
Definition at line 573 of file Types.h.
Constructor & Destructor Documentation
BoxNMSLimitInfo()
BoxNMSLimitInfo (float score_thresh = 0.05f, float nms = 0.3f, int detections = 100, bool soft_nms_enabled = false, NMSType soft_nms_method = NMSType::LINEAR, float soft_nms_sigma = 0.5f, float soft_nms_min_score_thres = 0.001f, bool suppress_size = false, float min_size = 1.0f, float im_width = 1.0f, float im_height = 1.0f) inline
Constructor.
Parameters
[in] score_thresh (Optional) Score threshold.
[in] nms (Optional) NMS value
[in] detections (Optional) Number of detections
[in] soft_nms_enabled (Optional) Enable SoftNMS
[in] soft_nms_method (Optional) Soft NMS method
[in] soft_nms_sigma (Optional) Soft NMS sigma value
[in] soft_nms_min_score_thres (Optional) Soft NMS minimum score threshold
[in] suppress_size (Optional) Filter out boxes based on their size. Defaults to false
[in] min_size (Optional) Smaller boxes than min_size will be filtered out. Defaults to 1
[in] im_width (Optional) Boxes whose centers (on the x axis) is beyond im_width will be filtered. Defaults to 1
[in] im_height (Optional) Boxes whose centers (on the y axis) is beyond im_height will be filtered. Defaults to 1
Definition at line 590 of file Types.h.
         : _score_thresh(score_thresh), _nms(nms), _detections_per_im(detections), _soft_nms_enabled(soft_nms_enabled), _soft_nms_method(soft_nms_method), _soft_nms_sigma(soft_nms_sigma),
           _soft_nms_min_score_thres(soft_nms_min_score_thres), _suppress_size(suppress_size), _min_size(min_size), _im_width(im_width), _im_height(im_height)
     {
     }
Member Function Documentation
detections_per_im()
int detections_per_im () const inline
Get the number of detections.
Definition at line 609 of file Types.h.
Referenced by arm_compute::operator<<(), and CPPBoxWithNonMaximaSuppressionLimitKernel::run_nmslimit().
     {
         return _detections_per_im;
     }
im_height()
float im_height () const inline
Get image height (NMS may suppress boxes whose center sits beyond the image height)
Definition at line 649 of file Types.h.
Referenced by arm_compute::operator<<().
     {
         return _im_height;
     }
im_width()
float im_width () const inline
Get image width (NMS may suppress boxes whose center sits beyond the image width)
Definition at line 644 of file Types.h.
Referenced by arm_compute::operator<<().
     {
         return _im_width;
     }
min_size()
float min_size () const inline
Get size suppression threshold.
Definition at line 639 of file Types.h.
Referenced by arm_compute::operator<<().
     {
         return _min_size;
     }
nms()
float nms () const inline
Get the NMS.
Definition at line 604 of file Types.h.
Referenced by arm_compute::operator<<().
     {
         return _nms;
     }
score_thresh()
float score_thresh () const inline
Get the score threshold.
Definition at line 599 of file Types.h.
Referenced by arm_compute::operator<<(), and CPPBoxWithNonMaximaSuppressionLimitKernel::run_nmslimit().
     {
         return _score_thresh;
     }
soft_nms_enabled()
bool soft_nms_enabled () const inline
Check if soft NMS is enabled.
Definition at line 614 of file Types.h.
Referenced by arm_compute::operator<<(), and CPPBoxWithNonMaximaSuppressionLimitKernel::run_nmslimit().
     {
         return _soft_nms_enabled;
     }
soft_nms_method()
NMSType soft_nms_method () const inline
Get soft NMS method.
Definition at line 619 of file Types.h.
     {
         return _soft_nms_method;
     }
soft_nms_min_score_thres()
float soft_nms_min_score_thres () const inline
Get soft nms min score threshold.
Definition at line 629 of file Types.h.
Referenced by arm_compute::operator<<().
     {
         return _soft_nms_min_score_thres;
     }
soft_nms_sigma()
float soft_nms_sigma () const inline
Get soft NMS sigma.
Definition at line 624 of file Types.h.
     {
         return _soft_nms_sigma;
     }
suppress_size()
bool suppress_size () const inline
Get if NMS will suppress boxes based on their size/position.
Definition at line 634 of file Types.h.
Referenced by arm_compute::operator<<().
     {
         return _suppress_size;
     }
The documentation for this class was generated from the following file:
arm_compute/core/Types.h