Compute Library: CLBoundingBoxTransform Class Reference
CLBoundingBoxTransform Class Reference
Basic function to run CLBoundingBoxTransformKernel.
#include <CLBoundingBoxTransform.h>
Public Member Functions
void configure (const ICLTensor *boxes, ICLTensor *pred_boxes, const ICLTensor *deltas, const BoundingBoxTransformInfo &info)
Set the input and output tensors.
void configure (const CLCompileContext &compile_context, const ICLTensor *boxes, ICLTensor *pred_boxes, const ICLTensor *deltas, const BoundingBoxTransformInfo &info)
Set the input and output tensors.
Public Member Functions inherited from ICLSimpleFunction
ICLSimpleFunction (CLRuntimeContext *ctx=nullptr)
Constructor.
ICLSimpleFunction (const ICLSimpleFunction &)=delete
Prevent instances of this class from being copied (As this class contains pointers)
ICLSimpleFunction (ICLSimpleFunction &&)=default
Default move constructor.
ICLSimpleFunction & operator= (const ICLSimpleFunction &)=delete
Prevent instances of this class from being copied (As this class contains pointers)
ICLSimpleFunction & operator= (ICLSimpleFunction &&)=default
Default move assignment operator.
~ICLSimpleFunction ()
Default destructor.
void run () override final
Run the kernels contained in the function.
Public Member Functions inherited from IFunction
virtual ~IFunction ()=default
Destructor.
virtual void prepare ()
Prepare the function for executing.
Static Public Member Functions
static Status validate (const ITensorInfo *boxes, const ITensorInfo *pred_boxes, const ITensorInfo *deltas, const BoundingBoxTransformInfo &info)
Static function to check if given info will lead to a valid configuration of CLBoundingBoxTransform.
Detailed Description
Basic function to run CLBoundingBoxTransformKernel.
This function calls the following OpenCL kernels:
CLBoundingBoxTransformKernel
Definition at line 43 of file CLBoundingBoxTransform.h.
Member Function Documentation
configure() [1/2]
void configure (const ICLTensor * boxes, ICLTensor * pred_boxes, const ICLTensor * deltas, const BoundingBoxTransformInfo & info)
Set the input and output tensors.
Valid data layouts:
NHWC
NCHW
Valid data type configurations:
src0 src1 dst
QASYMM16 QASYMM8 QASYMM16
F16 F16 F16
F32 F32 F32
Parameters
[in] boxes Source tensor. Bounding box proposals in pixel coordinates. Size(M, 4), format [x1, y1, x2, y2]. Data types supported: QASYMM16/F16/F32.
[out] pred_boxes Destination tensor. Pixel coordinates of the transformed bounding boxes. Size (M, 4*K), format [x1, y1, x2, y2]. Data types supported: Same as input
[in] deltas Bounding box translations and scales. Size (M, 4*K), format [dx, dy, dw, dh], K is the number of classes. Data types supported: QASYMM8 if input is QASYMM16, otherwise same as input
[in] info Contains BoundingBox operation information described in BoundingBoxTransformInfo.
Note
Only single image prediction is supported. Height and Width (and scale) of the image will be contained in the BoundingBoxTransformInfo struct.
Definition at line 32 of file CLBoundingBoxTransform.cpp.
References CLKernelLibrary::get().
 {
     configure(CLKernelLibrary::get().get_compile_context(), boxes, pred_boxes, deltas, info);
 }
configure() [2/2]
void configure (const CLCompileContext & compile_context, const ICLTensor * boxes, ICLTensor * pred_boxes, const ICLTensor * deltas, const BoundingBoxTransformInfo & info)
Set the input and output tensors.
Parameters
[in] compile_context The compile context to be used.
[in] boxes Source tensor. Bounding box proposals in pixel coordinates. Size(M, 4), format [x1, y1, x2, y2]. Data types supported: QASYMM16/F16/F32.
[out] pred_boxes Destination tensor. Pixel coordinates of the transformed bounding boxes. Size (M, 4*K), format [x1, y1, x2, y2]. Data types supported: Same as input
[in] deltas Bounding box translations and scales. Size (M, 4*K), format [dx, dy, dw, dh], K is the number of classes. Data types supported: QASYMM8 if input is QASYMM16, otherwise same as input
[in] info Contains BoundingBox operation information described in BoundingBoxTransformInfo.
Note
Only single image prediction is supported. Height and Width (and scale) of the image will be contained in the BoundingBoxTransformInfo struct.
Definition at line 37 of file CLBoundingBoxTransform.cpp.
References ARM_COMPUTE_LOG_PARAMS, and arm_compute::test::validation::k.
 {
     ARM_COMPUTE_LOG_PARAMS(boxes, pred_boxes, deltas, info);
     // Configure Bounding Box kernel
     auto k = std::make_unique<CLBoundingBoxTransformKernel>();
     k->configure(compile_context, boxes, pred_boxes, deltas, info);
     _kernel = std::move(k);
 }
validate()
Status validate (const ITensorInfo * boxes, const ITensorInfo * pred_boxes, const ITensorInfo * deltas, const BoundingBoxTransformInfo & info) static
Static function to check if given info will lead to a valid configuration of CLBoundingBoxTransform.
Parameters
[in] boxes Source tensor info. Bounding box proposals in pixel coordinates. Size(M, 4), format [x1, y1, x2, y2]. Data types supported: QASYMM16/F16/F32.
[in] pred_boxes Destination tensor info. Pixel coordinates of the transformed bounding boxes. Size (M, 4*K), format [x1, y1, x2, y2]. Data types supported: Same as input
[in] deltas Bounding box translations and scales. Size (M, 4*K), format [dx, dy, dw, dh], K is the number of classes. Data types supported: QASYMM8 if input is QASYMM16, otherwise same as input
[in] info Contains BoundingBox operation information described in BoundingBoxTransformInfo.
Note
Only single image prediction is supported. Height and Width (and scale) of the image will be contained in the BoundingBoxTransformInfo struct.
Returns
a Status
Definition at line 47 of file CLBoundingBoxTransform.cpp.
References CLBoundingBoxTransformKernel::validate().
Referenced by arm_compute::test::validation::DATA_TEST_CASE().
 {
     return CLBoundingBoxTransformKernel::validate(boxes, pred_boxes, deltas, info);
 }
The documentation for this class was generated from the following files:
arm_compute/runtime/CL/functions/CLBoundingBoxTransform.h
src/runtime/CL/functions/CLBoundingBoxTransform.cpp