Compute Library: ClStoreIndirectWidthSelectKernelComponent Class Reference
ClStoreIndirectWidthSelectKernelComponent Class Reference
#include <ClStoreKernelComponents.h>
Public Member Functions
ClStoreIndirectWidthSelectKernelComponent (ClKernelBlueprint *blueprint, const Link &src, const Link &dst)
ComponentType get_component_type () const override
std::string get_component_code () const override
CLBuildOptions generate_build_options () const override
virtual TagLUT get_tag_lut (const SharedVarTable &vtable) const override
Get the tag look-up table used to instantiate the component code.
void allocate_shared_vars (SharedVarTable &vtable) const override
Allocate all shared variables used by the component in the vtable.
virtual std::vector< Link > get_links () const override
virtual std::string name () const override
Public Member Functions inherited from IClKernelComponent
IClKernelComponent (ClKernelBlueprint *blueprint)
ARM_COMPUTE_DISALLOW_COPY_ALLOW_MOVE (IClKernelComponent)
virtual ~IClKernelComponent ()=default
ComponentID id () const
void set_id (ComponentID id)
virtual std::set< std::string > get_headers_list () const
virtual std::string get_additional_macros () const
virtual Window get_window () const
virtual std::string get_dst_addr_calculation () const
virtual std::string generate_config_id () const
Generate config id of the component.
Additional Inherited Members
Public Types inherited from IClKernelComponent
using Link = SharedVarLink
using Tag = std::string
using TagLUT = std::unordered_map< Tag, TagVal >
Static Public Member Functions inherited from IClKernelComponent
static std::string replace_tags (const std::string &code_template, const TagLUT &tags)
Detailed Description
Definition at line 65 of file ClStoreKernelComponents.h.
Constructor & Destructor Documentation
ClStoreIndirectWidthSelectKernelComponent()
ClStoreIndirectWidthSelectKernelComponent (ClKernelBlueprint * blueprint, const Link & src, const Link & dst) inline
Definition at line 68 of file ClStoreKernelComponents.h.
References ClStoreBlockBoundaryAwareKernelComponent::allocate_shared_vars(), arm_compute::test::validation::dst, ClStoreBlockBoundaryAwareKernelComponent::generate_build_options(), ClStoreBlockBoundaryAwareKernelComponent::get_component_code(), ClStoreBlockBoundaryAwareKernelComponent::get_component_type(), and ClStoreBlockBoundaryAwareKernelComponent::get_tag_lut().
         : IClKernelComponent(blueprint), _src{ src }, _dst{ dst }
     {
     }
Member Function Documentation
allocate_shared_vars()
void allocate_shared_vars (SharedVarTable & vtable) const override virtual
Allocate all shared variables used by the component in the vtable.
Parameters
vtable
Implements IClKernelComponent.
Definition at line 141 of file ClStoreKernelComponents.cpp.
References SharedVarTable::add(), SharedVarLink::arg_id, and arm_compute::experimental::dynamic_fusion::Tensor_4D_t_Buffer.
 {
     vtable.add(_src, _blueprint->impl().group(_src.arg_id), ClKernelArgDescriptor(_src.arg_id, ClKernelTensorArgType::Tensor_4D_t_Buffer), "src");
     vtable.add(_dst, _blueprint->impl().group(_dst.arg_id), ClKernelArgDescriptor(_dst.arg_id, ClKernelTensorArgType::Tensor_4D_t_Buffer), "dst");
 }
generate_build_options()
CLBuildOptions generate_build_options () const override virtual
Reimplemented from IClKernelComponent.
Definition at line 134 of file ClStoreKernelComponents.cpp.
 {
     CLBuildOptions build_opts{};
     return build_opts;
 }
get_component_code()
std::string get_component_code () const override virtual
Reimplemented from IClKernelComponent.
Definition at line 106 of file ClStoreKernelComponents.cpp.
 {
     return R"_(
     //------------------ START KERNEL {{meta_kernel_id}} STORE ---------------------
     {
     #define _IDST_WIDTH {{dst}}_w
     #define _IDST_HEIGHT {{dst}}_h
         TILE(uint, M0, 1, dst_indirect_y);
         // Calculate the destination indirect Y
         LOOP_UNROLLING(int, i, 0, 1, M0,
         {
             dst_indirect_y[i].v = (uint)min(mout + i, (int)(_IDST_WIDTH * _IDST_HEIGHT) - 1);
             dst_indirect_y[i].v += bout * (int)(_IDST_WIDTH * _IDST_HEIGHT);
         })
         bool x_cond = PARTIAL_N0 != 0 && get_global_id(0) == 0;
         T_STORE_INDIRECT_WIDTH_SELECT({{DST_DATA_TYPE}}, M0, N0, PARTIAL_N0, {{DST_TENSOR_TYPE}}, {{dst}}, cout, {{dst}}_stride_y, x_cond, {{src}}, dst_indirect_y);
     #undef _IDST_WIDTH
     #undef _IDST_HEIGHT
         //------------------ END KERNEL {{meta_kernel_id}} STORE ---------------------
     }
 )_";
 }
get_component_type()
ComponentType get_component_type () const override virtual
Implements IClKernelComponent.
Definition at line 101 of file ClStoreKernelComponents.cpp.
References arm_compute::experimental::dynamic_fusion::Store.
 {
     return ComponentType::Store;
 }
get_links()
virtual std::vector<Link> get_links () const inline override virtual
Implements IClKernelComponent.
Definition at line 78 of file ClStoreKernelComponents.h.
     {
         return { _src, _dst };
     }
get_tag_lut()
ClStoreIndirectWidthSelectKernelComponent::TagLUT get_tag_lut (const SharedVarTable & vtable) const override virtual
Get the tag look-up table used to instantiate the component code.
Parameters
vtable
Returns
TagLUT
Implements IClKernelComponent.
Definition at line 147 of file ClStoreKernelComponents.cpp.
References SharedVarTable::get(), and IClKernelComponent::id().
 {
     TagLUT lut{};
     // Arguments and global shared variables
     lut["src"] = vtable.get(_src);
     lut["dst"] = vtable.get(_dst);
     // Local build options
     lut["meta_kernel_id"]  = id();
     lut["DST_TENSOR_TYPE"] = "BUFFER";
     const auto dst_info    = _blueprint->impl().get_kernel_argument_info(_blueprint->impl().get_dst_id());
     lut["DST_DATA_TYPE"]   = dst_info->data_type();
     return lut;
 }
name()
virtual std::string name () const inline override virtual
Implements IClKernelComponent.
Definition at line 83 of file ClStoreKernelComponents.h.
     {
         return "";
     }
The documentation for this class was generated from the following files:
src/core/experimental/dynamic_fusion/ClKernelBuildingImpl/components/ClStoreKernelComponents.h
src/core/experimental/dynamic_fusion/ClKernelBuildingImpl/components/ClStoreKernelComponents.cpp