Compute Library: CLReorgLayer Class Reference
CLReorgLayer Class Reference
#include <CLReorgLayer.h>
Public Member Functions
void configure (ICLTensor *input, ICLTensor *output, int32_t stride)
Initialise the function's source and destination.
void configure (const CLCompileContext &compile_context, ICLTensor *input, ICLTensor *output, int32_t stride)
Initialise the function's source and destination.
Public Member Functions inherited from ICLSimpleFunction
ICLSimpleFunction (CLRuntimeContext *ctx=nullptr)
Constructor.
ICLSimpleFunction (const ICLSimpleFunction &)=delete
Prevent instances of this class from being copied (As this class contains pointers)
ICLSimpleFunction (ICLSimpleFunction &&)=default
Default move constructor.
ICLSimpleFunction & operator= (const ICLSimpleFunction &)=delete
Prevent instances of this class from being copied (As this class contains pointers)
ICLSimpleFunction & operator= (ICLSimpleFunction &&)=default
Default move assignment operator.
~ICLSimpleFunction ()
Default destructor.
void run () override final
Run the kernels contained in the function.
Public Member Functions inherited from IFunction
virtual ~IFunction ()=default
Destructor.
virtual void prepare ()
Prepare the function for executing.
Static Public Member Functions
static Status validate (const ITensorInfo *input, const ITensorInfo *output, int32_t stride)
Static function to check if given info will lead to a valid configuration of CLReorgLayer.
Detailed Description
Definition at line 36 of file CLReorgLayer.h.
Member Function Documentation
configure() [1/2]
void configure (ICLTensor * input, ICLTensor * output, int32_t stride)
Initialise the function's source and destination.
Valid data layouts:
NHWC
NCHW
Valid data type configurations:
src dst
All All
Parameters
[in] input Source tensor. Data types supported: All.
[out] output Destination tensor with tensor shape: [width_input / stride, height_input / stride, channels_input * stride * stride, batch_size]. This means the output has the same number of input elements. Data types supported: same as input.
[in] stride Stride value to use for reorganizing the values in the output tensor. It defines the spatial distance between 2 consecutive pixels in the x and y direction
Definition at line 38 of file CLReorgLayer.cpp.
References CLKernelLibrary::get().
 {
     configure(CLKernelLibrary::get().get_compile_context(), input, output, stride);
 }
configure() [2/2]
void configure (const CLCompileContext & compile_context, ICLTensor * input, ICLTensor * output, int32_t stride)
Initialise the function's source and destination.
Parameters
[in] compile_context The compile context to be used.
[in] input Source tensor. Data types supported: All.
[out] output Destination tensor with tensor shape: [width_input / stride, height_input / stride, channels_input * stride * stride, batch_size]. This means the output has the same number of input elements. Data types supported: same as input.
[in] stride Stride value to use for reorganizing the values in the output tensor. It defines the spatial distance between 2 consecutive pixels in the x and y direction
Definition at line 43 of file CLReorgLayer.cpp.
References ARM_COMPUTE_LOG_PARAMS, and arm_compute::test::validation::k.
 {
     ARM_COMPUTE_LOG_PARAMS(input, output, stride);
     auto k = std::make_unique<CLReorgLayerKernel>();
     k->configure(compile_context, input, output, stride);
     _kernel = std::move(k);
 }
validate()
Status validate (const ITensorInfo * input, const ITensorInfo * output, int32_t stride) static
Static function to check if given info will lead to a valid configuration of CLReorgLayer.
Parameters
[in] input Source tensor. Data types supported: All.
[in] output Destination tensor with tensor shape: [width_input / stride, height_input / stride, channels_input * stride * stride, batch_size]. This means the output has the same number of input elements. Data types supported: same as input. Data types supported: same as input.
[in] stride Stride value to use for reorganizing the values in the output tensor It defines the spatial distance between 2 consecutive pixels in the x and y direction
Returns
a status
Definition at line 51 of file CLReorgLayer.cpp.
References CLReorgLayerKernel::validate().
Referenced by arm_compute::test::validation::DATA_TEST_CASE().
 {
     return CLReorgLayerKernel::validate(input, output, stride);
 }
The documentation for this class was generated from the following files:
arm_compute/runtime/CL/functions/CLReorgLayer.h
src/runtime/CL/functions/CLReorgLayer.cpp