Compute Library: CpuGemmLowpOffsetContributionKernel Class Reference
CpuGemmLowpOffsetContributionKernel Class Reference
Kernel used to add the offset contribution after CpuGemmLowpMatrixMultiplyKernel.
#include <CpuGemmLowpOffsetContributionKernel.h>
Public Member Functions
CpuGemmLowpOffsetContributionKernel ()=default
Default constructor.
ARM_COMPUTE_DISALLOW_COPY_ALLOW_MOVE (CpuGemmLowpOffsetContributionKernel)
void configure (ITensorInfo *mm_result, ITensorInfo *vector_sum_col, ITensorInfo *vector_sum_row, int32_t k, int32_t a_offset, int32_t b_offset)
Initialise the kernel's input and output.
void run_op (ITensorPack &tensors, const Window &window, const ThreadInfo &info) override
Execute the kernel on the passed window.
const char * name () const override
Name of the kernel.
Public Member Functions inherited from ICPPKernel
virtual ~ICPPKernel ()=default
Default destructor.
virtual void run (const Window &window, const ThreadInfo &info)
Execute the kernel on the passed window.
virtual void run_nd (const Window &window, const ThreadInfo &info, const Window &thread_locator)
legacy compatibility layer for implemantions which do not support thread_locator In these cases we simply narrow the interface down the legacy version
virtual size_t get_mws (const CPUInfo &platform, size_t thread_count) const
Return minimum workload size of the relevant kernel.
Public Member Functions inherited from IKernel
IKernel ()
Constructor.
virtual ~IKernel ()=default
Destructor.
virtual bool is_parallelisable () const
Indicates whether or not the kernel is parallelisable.
virtual BorderSize border_size () const
The size of the border for that kernel.
const Window & window () const
The maximum window the kernel can be executed on.
bool is_window_configured () const
Function to check if the embedded window of this kernel has been configured.
Static Public Member Functions
static Status validate (const ITensorInfo *mm_result, const ITensorInfo *vector_sum_col, const ITensorInfo *vector_sum_row, int32_t a_offset, int32_t b_offset)
Static function to check if given info will lead to a valid configuration.
Static Public Member Functions inherited from ICpuKernel< CpuGemmLowpOffsetContributionKernel >
static const auto * get_implementation (const SelectorType &selector, KernelSelectionType selection_type=KernelSelectionType::Supported)
Micro-kernel selector.
Additional Inherited Members
Static Public Attributes inherited from ICPPKernel
static constexpr size_t default_mws = 1
Detailed Description
Kernel used to add the offset contribution after CpuGemmLowpMatrixMultiplyKernel.
The computation is performed in-place
This kernel takes a final int32 accumulator value (the output of CpuGemmLowpMatrixMultiplyKernel), and adds to it the offset contribution of matrix A and matrix B in-place.
The final result is:
mm_result[i][k] = mm_result[i][k] + (vector_sum_col[k] * a_offset) + (vector_sum_row[i] * b_offset) + (a_offset * b_offset * k)
Definition at line 49 of file CpuGemmLowpOffsetContributionKernel.h.
Constructor & Destructor Documentation
CpuGemmLowpOffsetContributionKernel()
CpuGemmLowpOffsetContributionKernel () default
Default constructor.
Member Function Documentation
ARM_COMPUTE_DISALLOW_COPY_ALLOW_MOVE()
ARM_COMPUTE_DISALLOW_COPY_ALLOW_MOVE (CpuGemmLowpOffsetContributionKernel)
configure()
void configure (ITensorInfo * mm_result, ITensorInfo * vector_sum_col, ITensorInfo * vector_sum_row, int32_t k, int32_t a_offset, int32_t b_offset)
Initialise the kernel's input and output.
Parameters
[in,out] mm_result Input tensor containing the result of CpuGemmLowpMatrixMultiplyKernel. Data type supported: S32
[in] vector_sum_col Input row-vector of sums of all the entries in each column of matrix B. Note: vector_sum_col can be a nullptr in case a_offset = 0. Data type supported: same as mm_result
[in] vector_sum_row Input row-vector of sums of all the entries in each row of matrix A. Note: vector_sum_row can be a nullptr in case b_offset = 0. Data type supported: same as mm_result
[in] k Number of matrix A columns or Matrix B rows
[in] a_offset Offset to be added to each element of the matrix A.
[in] b_offset Offset to be added to each element of the matrix B.
Definition at line 361 of file CpuGemmLowpOffsetContributionKernel.cpp.
References ARM_COMPUTE_ERROR_ON_NULLPTR, ARM_COMPUTE_ERROR_THROW_ON, ARM_COMPUTE_UNUSED, arm_compute::calculate_max_window(), arm_compute::test::validation::k, Dimensions< T >::num_dimensions(), ITensorInfo::tensor_shape(), and arm_compute::cpu::kernels::validate_arguments().
 {
     // Perform validate step
     ARM_COMPUTE_UNUSED(vector_sum_row);
     ARM_COMPUTE_ERROR_ON_NULLPTR(mm_result);
     ARM_COMPUTE_ERROR_THROW_ON(validate_arguments(mm_result, vector_sum_col, vector_sum_row, a_offset, b_offset));
     _a_offset = a_offset;
     _b_offset = b_offset;
     _k_offset = a_offset * b_offset * k;
     // If a_offset == 0, vector_sum_col can be a nullptr
     if(a_offset != 0)
     {
         // Check if vector_sum_col_shape should be slidden or not
         // Don't slide vector_sum_col_shape along the y dimension if vector_sum_col_shape has just 1 dimension and vector_sum_row_shape more than 1
         // This scenario can happen when the the matrix multiplication is used to perform a convolution operation
         _slide_vector_sum_col = vector_sum_col->tensor_shape().num_dimensions() > 1;
     }
     // Configure kernel window
     Window win = calculate_max_window(*mm_result, Steps());
     ICpuKernel::configure(win);
 }
name()
const char * name () const override virtual
Name of the kernel.
Returns
Kernel name
Implements ICPPKernel.
Definition at line 411 of file CpuGemmLowpOffsetContributionKernel.cpp.
 {
     return "CpuGemmLowpOffsetContributionKernel";
 }
run_op()
void run_op (ITensorPack & tensors, const Window & window, const ThreadInfo & info) override virtual
Execute the kernel on the passed window.
Warning
If is_parallelisable() returns false then the passed window must be equal to window()
Note
The window has to be a region within the window returned by the window() method
The width of the window has to be a multiple of num_elems_processed_per_iteration().
Parameters
[in] tensors A vector containing the tensors to operate on.
[in] window Region on which to execute the kernel. (Must be a region of the window returned by window())
[in] info Info about executing thread and CPU.
Reimplemented from ICPPKernel.
Definition at line 393 of file CpuGemmLowpOffsetContributionKernel.cpp.
References arm_compute::ACL_DST, arm_compute::ACL_SRC_0, arm_compute::ACL_SRC_1, ARM_COMPUTE_ERROR_ON_INVALID_SUBWINDOW, ARM_COMPUTE_ERROR_ON_UNCONFIGURED_KERNEL, ARM_COMPUTE_UNUSED, ITensorPack::get_const_tensor(), ITensorPack::get_tensor(), ITensor::info(), ITensorInfo::num_dimensions(), and IKernel::window().
 {
     ARM_COMPUTE_UNUSED(info);
     ARM_COMPUTE_ERROR_ON_UNCONFIGURED_KERNEL(this);
     ARM_COMPUTE_ERROR_ON_INVALID_SUBWINDOW(ICpuKernel::window(), window);
     auto vector_sum_col = tensors.get_const_tensor(TensorType::ACL_SRC_0);
     auto vector_sum_row = tensors.get_const_tensor(TensorType::ACL_SRC_1);
     auto mm_result      = tensors.get_tensor(TensorType::ACL_DST);
     // Check if input is a 3D reinterpretation
     const bool reinterpret_as_3d = vector_sum_row != nullptr
                                    && mm_result->info()->num_dimensions() > 1
                                    && mm_result->info()->tensor_shape().y() != vector_sum_row->info()->tensor_shape().x();
     run_offset_contribution(window, mm_result, vector_sum_col, vector_sum_row, _a_offset, _b_offset, _k_offset, _slide_vector_sum_col, reinterpret_as_3d);
 }
validate()
Status validate (const ITensorInfo * mm_result, const ITensorInfo * vector_sum_col, const ITensorInfo * vector_sum_row, int32_t a_offset, int32_t b_offset) static
Static function to check if given info will lead to a valid configuration.
Similar to CpuGemmLowpOffsetContributionKernel::configure()
Returns
a status
Definition at line 386 of file CpuGemmLowpOffsetContributionKernel.cpp.
References ARM_COMPUTE_RETURN_ON_ERROR, and arm_compute::cpu::kernels::validate_arguments().
Referenced by CpuGemmLowpMatrixMultiplyCore::validate().
 {
     ARM_COMPUTE_RETURN_ON_ERROR(validate_arguments(mm_result, vector_sum_col, vector_sum_row, a_offset, b_offset));
     return Status{};
 }
The documentation for this class was generated from the following files:
src/cpu/kernels/CpuGemmLowpOffsetContributionKernel.h
src/cpu/kernels/CpuGemmLowpOffsetContributionKernel.cpp