Compute Library: AddContent Class Reference
AddContent Class Reference
#include <OperatorGraphImpl.h>
Public Member Functions
AddContent ()=default
AddContent (const OperatorGraph::Implementation *graph, Id id, const AddDescriptor &desc, const ITensorDescPack< OpTensorContent > &tensors)
~AddContent ()=default
AddContent (const AddContent &)=default
AddContent & operator= (const AddContent &)=default
AddContent (AddContent &&)=default
AddContent & operator= (AddContent &&)=default
bool operator== (const OperatorContent &other) const override
OperatorComplexity complexity () const override
Status translate (ClKernelGraph &kernel_graph) const override
Public Member Functions inherited from OperatorContent
OperatorContent ()=default
OperatorContent (const OperatorGraph::Implementation *graph, Id id, const ITensorDescPack< OpTensorContent > &tensors)
OperatorContent (const OperatorContent &op)=default
OperatorContent & operator= (const OperatorContent &op)=default
OperatorContent (OperatorContent &&op)=default
OperatorContent & operator= (OperatorContent &&op)=default
virtual ~OperatorContent ()=default
Additional Inherited Members
Public Types inherited from OperatorContent
using Id = DependencyGraph::Id
Detailed Description
Definition at line 160 of file OperatorGraphImpl.h.
Constructor & Destructor Documentation
AddContent() [1/4]
AddContent () default
AddContent() [2/4]
AddContent (const OperatorGraph::Implementation * graph, Id id, const AddDescriptor & desc, const ITensorDescPack< OpTensorContent > & tensors) inline
Definition at line 164 of file OperatorGraphImpl.h.
References arm_compute::experimental::dynamic_fusion::operator==().
         : OperatorContent(graph, id, tensors), desc(desc)
     {
     }
~AddContent()
~AddContent () default
AddContent() [3/4]
AddContent (const AddContent &) default
AddContent() [4/4]
AddContent (AddContent &&) default
Member Function Documentation
complexity()
OperatorComplexity complexity () const inline override virtual
Implements OperatorContent.
Definition at line 174 of file OperatorGraphImpl.h.
References arm_compute::experimental::dynamic_fusion::Simple, and arm_compute::experimental::dynamic_fusion::translate().
     {
         return OperatorComplexity::Simple;
     }
operator=() [1/2]
AddContent& operator= (const AddContent &) default
operator=() [2/2]
AddContent& operator= (AddContent &&) default
operator==()
bool operator== (const OperatorContent & other) const override virtual
Implements OperatorContent.
Definition at line 127 of file OperatorGraphImpl.cpp.
References Conv2dContent::desc.
 {
     const auto converted = *utils::cast::polymorphic_downcast<const AddContent *>(&other);
     return desc == converted.desc;
 }
translate()
Status translate (ClKernelGraph & kernel_graph) const override virtual
Implements OperatorContent.
Definition at line 314 of file OperatorGraphImpl.cpp.
References arm_compute::ACL_DST_0, arm_compute::ACL_SRC_0, arm_compute::ACL_SRC_1, ITensorDescPack< TDesc >::add_const_tensor(), ClKernelGraph::add_kernel(), ARM_COMPUTE_ERROR_ON_NULLPTR, ARM_COMPUTE_RETURN_ON_ERROR, ARM_COMPUTE_UNUSED, Conv2dContent::desc, arm_compute::test::validation::dst, ClKernelGraph::get_tensor(), UnitWorkloadStage::Run, arm_compute::experimental::dynamic_fusion::TStoreIndirectWidthSelect, and ClAddKernel::validate().
 {
     const auto lhs = _tensors.get_const_tensor(TensorType::ACL_SRC_0);
     const auto rhs = _tensors.get_const_tensor(TensorType::ACL_SRC_1);
     const auto dst = _tensors.get_const_tensor(TensorType::ACL_DST_0);
     ARM_COMPUTE_ERROR_ON_NULLPTR(lhs, rhs, dst);
     ITensorDescPack<ClKernelTensor> tensors;
     DependencyGraph::Id lhs_id;
     auto                st = add_kernel_tensor(kernel_graph, *_graph, *lhs, lhs_id);
     ARM_COMPUTE_RETURN_ON_ERROR(st);
     tensors.add_const_tensor(ACL_SRC_0, kernel_graph.get_tensor(lhs_id));
     DependencyGraph::Id rhs_id;
     st = add_kernel_tensor(kernel_graph, *_graph, *rhs, rhs_id);
     ARM_COMPUTE_RETURN_ON_ERROR(st);
     tensors.add_const_tensor(ACL_SRC_1, kernel_graph.get_tensor(rhs_id));
     DependencyGraph::Id dst_id;
     st = add_kernel_tensor(kernel_graph, *_graph, *dst, dst_id);
     ARM_COMPUTE_RETURN_ON_ERROR(st);
     tensors.add_const_tensor(ACL_DST_0, kernel_graph.get_tensor(dst_id));
     DependencyGraph::Id add_id;
     ClKernelConfig      config{ UnitWorkloadStage{ UnitWorkloadStage::Stage::Run }, TileDescriptor{}, StoreType::TStoreIndirectWidthSelect };
     st = ClAddKernel::validate(lhs->desc, rhs->desc, dst->desc);
     ARM_COMPUTE_RETURN_ON_ERROR(st);
     st = kernel_graph.add_kernel<ClAddKernel>(config, ClEltwiseAddKernelDescriptor{ desc }, tensors, add_id);
     ARM_COMPUTE_RETURN_ON_ERROR(st);
     ARM_COMPUTE_UNUSED(add_id);
     return Status{};
 }
The documentation for this class was generated from the following files:
src/core/experimental/dynamic_fusion/WorkloadImpl/OperatorGraphImpl.h
src/core/experimental/dynamic_fusion/WorkloadImpl/OperatorGraphImpl.cpp