Compute Library: Queue Class Reference
Queue Class Reference
Queue classData type enumeration.
#include <Acl.hpp>
Data Structures
struct Options
< Queue options
Public Member Functions
Queue (Context &ctx, StatusCode *status=nullptr)
Constructor.
Queue (Context &ctx, const Options &options=Options(), StatusCode *status=nullptr)
Constructor.
StatusCode finish ()
Block until all the tasks of the queue have been marked as finished.
Public Member Functions inherited from ObjectBase< AclQueue_ >
~ObjectBase ()=default
Destructor.
ObjectBase (const ObjectBase< AclQueue_ > &)=default
Copy constructor.
ObjectBase (ObjectBase< AclQueue_ > &&)=default
Move Constructor.
ObjectBase< AclQueue_ > & operator= (const ObjectBase< AclQueue_ > &)=default
Copy assignment operator.
ObjectBase< AclQueue_ > & operator= (ObjectBase< AclQueue_ > &&)=default
Move assignment operator.
void reset (AclQueue_ *val)
Reset object value.
const AclQueue_ * get () const
Access uderlying object.
AclQueue_ * get ()
Access uderlying object.
Detailed Description
Queue classData type enumeration.
Queue is responsible for the execution related aspects, with main responsibilities those of scheduling and tuning operators.
Multiple queues can be created from the same context, and the same operator can be scheduled on each concurrently.
Note
An operator might depend on the maximum possible compute units that are provided in the context, thus in cases where the number of the scheduling units of the queue are greater might lead to errors.
Definition at line 416 of file Acl.hpp.
Constructor & Destructor Documentation
Queue() [1/2]
Queue (Context & ctx, StatusCode * status = nullptr) inline explicit
Constructor.
Note
Serves as a simpler delegate constructor
As queue options, default conservative options will be used
Parameters
[in] ctx Context to create queue for
[out] status Status information if requested
Definition at line 451 of file Acl.hpp.
         : Queue(ctx, Options(), status)
     {
     }
Queue() [2/2]
Queue (Context & ctx, const Options & options = Options(), StatusCode * status = nullptr) inline explicit
Constructor.
Note
As queue options, default conservative options will be used
Parameters
[in] ctx Context from where the queue will be created from
[in] options Queue options to be used
[out] status Status information if requested
Definition at line 463 of file Acl.hpp.
References AclCreateQueue(), and ObjectBase< T >::get().
     {
         AclQueue   queue;
         const auto st = detail::as_enum<StatusCode>(AclCreateQueue(&queue, ctx.get(), &options.opts));
         reset(queue);
         report_status(st, "[Compute Library] Failed to create queue!");
         if(status)
         {
             *status = st;
         }
     }
Member Function Documentation
finish()
StatusCode finish () inline
Block until all the tasks of the queue have been marked as finished.
Returns
Status code
Definition at line 478 of file Acl.hpp.
References AclQueueFinish().
     {
         return detail::as_enum<StatusCode>(AclQueueFinish(_object.get()));
     }
The documentation for this class was generated from the following file:
arm_compute/Acl.hpp