Compute Library: MLGOHeuristics Class Reference
MLGOHeuristics Class Reference
MLGOHeuristics for configuring GEMM kernels.
#include <MLGOHeuristics.h>
Public Member Functions
MLGOHeuristics ()
Constructor.
~MLGOHeuristics ()=default
Default Destructor.
MLGOHeuristics (const MLGOHeuristics &)=delete
Prevent Copy Construct.
MLGOHeuristics & operator= (const MLGOHeuristics &)=delete
Prevent Copy Assignment.
MLGOHeuristics (MLGOHeuristics &&)=default
Default Move Constructor.
MLGOHeuristics & operator= (MLGOHeuristics &&)=default
Default Move Assignment.
std::pair< bool, GEMMType > query_gemm_type (const Query &query) const
Query the gemm type.
std::pair< bool, GEMMConfigNative > query_gemm_config_native (const Query &query) const
Query the gemm configuration for native kernel.
std::pair< bool, GEMMConfigReshapedOnlyRHS > query_gemm_config_reshaped_only_rhs (const Query &query) const
Query the gemm configuration for reshaped only rhs kernel.
std::pair< bool, GEMMConfigReshaped > query_gemm_config_reshaped (const Query &query) const
Query the gemm configuration for reshaped kernel.
bool reload_from_file (const std::string &filename)
(Re)Load the heuristics from reading a dotmlgo file
bool reload_from_stream (std::istream &istream)
(Re)Load the heuristics from reading an input stream
std::pair< bool, HeuristicTree * > get_heuristic_tree (HeuristicTree::TreeID id)
Get the heuristic tree from tree id.
bool add_heuristic_tree (HeuristicTree &&t)
Add a heuristic tree.
bool check_heuristic_tree (HeuristicTree::TreeID id)
Check the validity of the heuristic tree.
bool check_all () const
Check the overall validity of the heuristics.
Detailed Description
MLGOHeuristics for configuring GEMM kernels.
Definition at line 54 of file MLGOHeuristics.h.
Constructor & Destructor Documentation
MLGOHeuristics() [1/3]
MLGOHeuristics ()
Constructor.
Definition at line 53 of file MLGOHeuristics.cpp.
     : _indices{}, _trees{}, _tree_valid{}, _valid{ false }
 {
 }
~MLGOHeuristics()
~MLGOHeuristics () default
Default Destructor.
MLGOHeuristics() [2/3]
MLGOHeuristics (const MLGOHeuristics &) delete
Prevent Copy Construct.
MLGOHeuristics() [3/3]
MLGOHeuristics (MLGOHeuristics &&) default
Default Move Constructor.
Member Function Documentation
add_heuristic_tree()
bool add_heuristic_tree (HeuristicTree && t)
Add a heuristic tree.
Parameters
t Heuristic tree to be added
Definition at line 187 of file MLGOHeuristics.cpp.
References ARM_COMPUTE_LOG_INFO_MSG_CORE, ARM_COMPUTE_LOG_INFO_MSG_WITH_FORMAT_CORE, and tf_frozen_model_extractor::t.
Referenced by arm_compute::mlgo::parser::heuristics_table_entry().
 {
     if(_indices.size() >= _max_num_trees)
     {
         ARM_COMPUTE_LOG_INFO_MSG_WITH_FORMAT_CORE("Exceeding the max number of trees allowed: %zu", _max_num_trees);
         return false;
     }
     // PRE: correctness of t is guaranteed by the tree construction process
     // Ensure unique id
     const auto id = t.id();
     if(_indices.find(id) != _indices.end())
     {
         ARM_COMPUTE_LOG_INFO_MSG_WITH_FORMAT_CORE("Cannot add redundant trees; tree id %zu already exists", id);
         return false;
     }
     // Ensure unique index
     const auto index = t.index();
     if(_trees.find(index) != _trees.end())
     {
         ARM_COMPUTE_LOG_INFO_MSG_CORE("Cannot add redundant trees; tree index already exists");
         return false;
     }
     _indices[id]    = index;
     _trees[index]   = std::move(t);
     _tree_valid[id] = false;
     return true;
 }
check_all()
bool check_all () const
Check the overall validity of the heuristics.
Returns
bool
Definition at line 149 of file MLGOHeuristics.cpp.
References ARM_COMPUTE_LOG_INFO_MSG_CORE.
Referenced by arm_compute::mlgo::parser::mlgo().
 {
     // Tree validities are already checked and cached.
     bool all_trees_are_checked = std::find_if(_tree_valid.begin(), _tree_valid.end(), [](auto v)
     {
         return !v.second;
     })
     == _tree_valid.end();
     if(!all_trees_are_checked)
     {
         ARM_COMPUTE_LOG_INFO_MSG_CORE("Missing checks on some trees. Make sure to call check_heuristic_tree after each tree is completed. This could also indicate there are no trees in the dotmlgo");
         return false;
     }
     // Other top level checks...
     return true;
 }
check_heuristic_tree()
bool check_heuristic_tree (HeuristicTree::TreeID id)
Check the validity of the heuristic tree.
Parameters
id ID of the tree to be checked
Returns
bool
Definition at line 131 of file MLGOHeuristics.cpp.
References MLGOHeuristics::get_heuristic_tree().
Referenced by arm_compute::mlgo::parser::heuristic_tree().
 {
     bool           status;
     HeuristicTree *tree{ nullptr };
     std::tie(status, tree) = get_heuristic_tree(id);
     if(!status)
     {
         return status;
     }
     status = tree->check();
     if(!status)
     {
         return status;
     }
     _tree_valid[id] = true;
     return true;
 }
get_heuristic_tree()
std::pair< bool, HeuristicTree * > get_heuristic_tree (HeuristicTree::TreeID id)
Get the heuristic tree from tree id.
Parameters
[in] id Tree id.
Returns
HeuristicTree&
Definition at line 168 of file MLGOHeuristics.cpp.
References ARM_COMPUTE_LOG_INFO_MSG_CORE, ARM_COMPUTE_LOG_INFO_MSG_WITH_FORMAT_CORE, and tf_frozen_model_extractor::t.
Referenced by MLGOHeuristics::check_heuristic_tree(), and arm_compute::mlgo::parser::heuristic_tree().
 {
     if(_indices.find(id) == _indices.end())
     {
         ARM_COMPUTE_LOG_INFO_MSG_WITH_FORMAT_CORE("Cannot find tree with id %zu", id);
         return std::make_pair(false, nullptr);
     }
     const auto index = _indices[id];
     if(_trees.find(index) == _trees.end())
     {
         ARM_COMPUTE_LOG_INFO_MSG_CORE("Cannot find tree index");
         return std::make_pair(false, nullptr);
     }
     auto &t = _trees[index];
     return std::make_pair(true, &t);
 }
operator=() [1/2]
MLGOHeuristics& operator= (const MLGOHeuristics &) delete
Prevent Copy Assignment.
operator=() [2/2]
MLGOHeuristics& operator= (MLGOHeuristics &&) default
Default Move Assignment.
query_gemm_config_native()
std::pair< bool, GEMMConfigNative > query_gemm_config_native (const Query & query) const
Query the gemm configuration for native kernel.
Parameters
[in] query Query
Returns
std::pair<bool, GEMMConfigNative> bool signals if the query succeeded or failed
Definition at line 76 of file MLGOHeuristics.cpp.
References ARM_COMPUTE_LOG_INFO_MSG_CORE, ARM_COMPUTE_LOG_INFO_MSG_WITH_FORMAT_CORE, Query::b, Query::data_type, arm_compute::mlgo::GEMM_Config_Native, Query::ip_target, Query::k, Query::m, Query::n, and arm_compute::mlgo::to_string().
Referenced by arm_compute::cl_gemm::auto_heuristics::select_mlgo_gemm_config_native().
 {
     ARM_COMPUTE_LOG_INFO_MSG_WITH_FORMAT_CORE("MLGOHeuristics querying gemm config native. %s.", to_string(query).c_str());
     const auto invalid = GEMMConfigNative{};
     if(!_valid)
     {
         ARM_COMPUTE_LOG_INFO_MSG_CORE("Invalid DotMLGO. Use default heuristics instead");
         return { false, invalid };
     }
     auto      index = std::make_tuple(HeuristicType::GEMM_Config_Native, query.ip_target, query.data_type);
     GEMMShape shape_query{ query.m, query.n, query.k, query.b };
     if(_trees.find(index) == _trees.end())
     {
         ARM_COMPUTE_LOG_INFO_MSG_CORE("Cannot find tree index");
         return { false, invalid };
     }
     return _trees.at(index).query<GEMMConfigNative>(shape_query);
 }
query_gemm_config_reshaped()
std::pair< bool, GEMMConfigReshaped > query_gemm_config_reshaped (const Query & query) const
Query the gemm configuration for reshaped kernel.
Parameters
[in] query Query
Returns
std::pair<bool, GEMMConfigReshaped> bool signals if the query succeeded or failed
Definition at line 112 of file MLGOHeuristics.cpp.
References ARM_COMPUTE_LOG_INFO_MSG_CORE, ARM_COMPUTE_LOG_INFO_MSG_WITH_FORMAT_CORE, Query::b, Query::data_type, arm_compute::mlgo::GEMM_Config_Reshaped, Query::ip_target, Query::k, Query::m, Query::n, and arm_compute::mlgo::to_string().
Referenced by arm_compute::cl_gemm::auto_heuristics::select_mlgo_gemm_config_reshaped(), and arm_compute::test::validation::TEST_CASE().
 {
     ARM_COMPUTE_LOG_INFO_MSG_WITH_FORMAT_CORE("MLGOHeuristics querying gemm config reshaped. %s.", to_string(query).c_str());
     const auto invalid = GEMMConfigReshaped{};
     if(!_valid)
     {
         ARM_COMPUTE_LOG_INFO_MSG_CORE("Invalid DotMLGO. Use default heuristics instead");
         return { false, invalid };
     }
     auto      index = std::make_tuple(HeuristicType::GEMM_Config_Reshaped, query.ip_target, query.data_type);
     GEMMShape shape_query{ query.m, query.n, query.k, query.b };
     if(_trees.find(index) == _trees.end())
     {
         ARM_COMPUTE_LOG_INFO_MSG_CORE("Cannot find tree index");
         return { false, invalid };
     }
     return _trees.at(index).query<GEMMConfigReshaped>(shape_query);
 }
query_gemm_config_reshaped_only_rhs()
std::pair< bool, GEMMConfigReshapedOnlyRHS > query_gemm_config_reshaped_only_rhs (const Query & query) const
Query the gemm configuration for reshaped only rhs kernel.
Parameters
[in] query Query
Returns
std::pair<bool, GEMMConfigReshapedOnlyRHS> bool signals if the query succeeded or failed
Definition at line 94 of file MLGOHeuristics.cpp.
References ARM_COMPUTE_LOG_INFO_MSG_CORE, ARM_COMPUTE_LOG_INFO_MSG_WITH_FORMAT_CORE, Query::b, Query::data_type, arm_compute::mlgo::GEMM_Config_Reshaped_Only_RHS, Query::ip_target, Query::k, Query::m, Query::n, and arm_compute::mlgo::to_string().
Referenced by arm_compute::cl_gemm::auto_heuristics::select_mlgo_gemm_config_reshaped_only_rhs(), and arm_compute::test::validation::TEST_CASE().
 {
     ARM_COMPUTE_LOG_INFO_MSG_WITH_FORMAT_CORE("MLGOHeuristics querying gemm config reshaped only rhs. %s.", to_string(query).c_str());
     const auto invalid = GEMMConfigReshapedOnlyRHS{};
     if(!_valid)
     {
         ARM_COMPUTE_LOG_INFO_MSG_CORE("Invalid DotMLGO. Use default heuristics instead");
         return { false, invalid };
     }
     auto      index = std::make_tuple(HeuristicType::GEMM_Config_Reshaped_Only_RHS, query.ip_target, query.data_type);
     GEMMShape shape_query{ query.m, query.n, query.k, query.b };
     if(_trees.find(index) == _trees.end())
     {
         ARM_COMPUTE_LOG_INFO_MSG_CORE("Cannot find tree index");
         return { false, invalid };
     }
     return _trees.at(index).query<GEMMConfigReshapedOnlyRHS>(shape_query);
 }
query_gemm_type()
std::pair< bool, GEMMType > query_gemm_type (const Query & query) const
Query the gemm type.
Parameters
[in] query Query
Returns
std::pair<bool, GEMMType> signals if the query succeeded or failed
Definition at line 58 of file MLGOHeuristics.cpp.
References ARM_COMPUTE_LOG_INFO_MSG_CORE, ARM_COMPUTE_LOG_INFO_MSG_WITH_FORMAT_CORE, Query::b, Query::data_type, arm_compute::mlgo::GEMM_Type, Query::ip_target, Query::k, Query::m, Query::n, arm_compute::RESHAPED, and arm_compute::mlgo::to_string().
Referenced by arm_compute::cl_gemm::auto_heuristics::select_mlgo_gemm_kernel(), and arm_compute::test::validation::TEST_CASE().
 {
     ARM_COMPUTE_LOG_INFO_MSG_WITH_FORMAT_CORE("MLGOHeuristics querying gemm type. %s.", to_string(query).c_str());
     const auto invalid = GEMMType::RESHAPED;
     if(!_valid)
     {
         ARM_COMPUTE_LOG_INFO_MSG_CORE("Invalid DotMLGO. Use default heuristics instead");
         return { false, invalid };
     }
     auto      index = std::make_tuple(HeuristicType::GEMM_Type, query.ip_target, query.data_type);
     GEMMShape shape_query{ query.m, query.n, query.k, query.b };
     if(_trees.find(index) == _trees.end())
     {
         ARM_COMPUTE_LOG_INFO_MSG_CORE("Cannot find tree index");
         return { false, invalid };
     }
     return _trees.at(index).query<GEMMType>(shape_query);
 }
reload_from_file()
bool reload_from_file (const std::string & filename)
(Re)Load the heuristics from reading a dotmlgo file
Parameters
[in] filename Path to the dotmlgo file
Returns
bool Signals if the reload succeeded or failed
Definition at line 217 of file MLGOHeuristics.cpp.
References ARM_COMPUTE_LOG_INFO_MSG_WITH_FORMAT_CORE, and MLGOHeuristics::reload_from_stream().
 {
     std::ifstream fs;
     fs.exceptions(std::ifstream::badbit);
     fs.open(filename, std::ios::in);
     if(!fs.is_open())
     {
         ARM_COMPUTE_LOG_INFO_MSG_WITH_FORMAT_CORE("Cannot open DotMLGO file %s. Use default heuristics instead", filename.c_str());
         return _valid = false;
     }
     return reload_from_stream(fs);
 }
reload_from_stream()
bool reload_from_stream (std::istream & istream)
(Re)Load the heuristics from reading an input stream
Parameters
[in] istream Istream containing mlgo heuristics
Returns
bool Signals if the reload succeeded or failed
Definition at line 230 of file MLGOHeuristics.cpp.
References ARM_COMPUTE_LOG_INFO_MSG_CORE, and arm_compute::mlgo::parser::parse_mlgo().
Referenced by MLGOHeuristics::reload_from_file(), and arm_compute::test::validation::TEST_CASE().
 {
     auto parsed = parser::parse_mlgo(in);
     if(!parsed.first)
     {
         ARM_COMPUTE_LOG_INFO_MSG_CORE("DotMLGO parsing failed. Use default heuristics instead");
         return _valid = false;
     }
     *this = std::move(parsed.second);
     ARM_COMPUTE_LOG_INFO_MSG_CORE("DotMLGO loaded successfully");
     return _valid = true;
 }
The documentation for this class was generated from the following files:
src/runtime/CL/mlgo/MLGOHeuristics.h
src/runtime/CL/mlgo/MLGOHeuristics.cpp