Compute Library: arm_compute::cpuinfo Namespace Reference
arm_compute::cpuinfo Namespace Reference
Data Structures
class CpuInfo
Aggregate class that contains CPU related information.
struct CpuIsaInfo
CPU ISA (Instruction Set Architecture) information.
Typedefs
using CpuModel = arm_compute::CPUModel
Functions
uint32_t num_threads_hint ()
Some systems have both big and small cores, this fuction computes the minimum number of cores that are exactly the same on the system.
CpuIsaInfo init_cpu_isa_from_hwcaps (uint32_t hwcaps, uint32_t hwcaps2, uint32_t midr)
Identify ISA related information through system information.
CpuIsaInfo init_cpu_isa_from_regs (uint64_t isar0, uint64_t isar1, uint64_t pfr0, uint64_t svefr0, uint64_t midr)
Identify ISA related information through register information.
std::string cpu_model_to_string (CpuModel model)
Convert a CPU model value to a string.
bool model_supports_fp16 (CpuModel model)
Check if a model supports half-precision floating point arithmetic.
bool model_supports_dot (CpuModel model)
Check if a model supports dot product.
CpuModel midr_to_model (uint32_t midr)
Extract the model type from the MIDR value.
Typedef Documentation
CpuModel
using CpuModel = arm_compute::CPUModel
Definition at line 36 of file CpuModel.h.
Function Documentation
cpu_model_to_string()
std::string cpu_model_to_string (CpuModel model)
Convert a CPU model value to a string.
Parameters
model CpuModel value to be converted
Returns
String representing the corresponding CpuModel
Definition at line 30 of file CpuModel.cpp.
References ARM_COMPUTE_CPU_MODEL_LIST.
Referenced by main().
 {
     switch(model)
     {
 #define X(MODEL)          \
 case CpuModel::MODEL: \
     return #MODEL;
             ARM_COMPUTE_CPU_MODEL_LIST
 #undef X
         default:
         {
             return std::string("GENERIC");
         }
     };
 }
init_cpu_isa_from_hwcaps()
CpuIsaInfo init_cpu_isa_from_hwcaps (uint32_t hwcaps, uint32_t hwcaps2, uint32_t midr)
Identify ISA related information through system information.
Parameters
[in] hwcaps HWCAPS feature information
[in] hwcaps2 HWCAPS2 feature information
[in] midr MIDR value
Returns
CpuIsaInfo A populated ISA feature structure
Definition at line 131 of file CpuIsaInfo.cpp.
References isa, and midr_to_model().
Referenced by CpuInfo::build().
 {
     CpuIsaInfo isa;
     decode_hwcaps(isa, hwcaps, hwcaps2);
     const CpuModel model = midr_to_model(midr);
     allowlisted_model_features(isa, model);
     return isa;
 }
init_cpu_isa_from_regs()
CpuIsaInfo init_cpu_isa_from_regs (uint64_t isar0, uint64_t isar1, uint64_t pfr0, uint64_t svefr0, uint64_t midr)
Identify ISA related information through register information.
Parameters
[in] isar0 Value of Instruction Set Attribute Register 0 (ID_AA64ISAR0_EL1)
[in] isar1 Value of Instruction Set Attribute Register 1 (ID_AA64ISAR1_EL1)
[in] pfr0 Value of Processor Feature Register 0 (ID_AA64PFR0_EL1)
[in] svefr0 Value of SVE feature ID register 0 (ID_AA64ZFR0_EL1)
[in] midr Value of Main ID Register (MIDR)
Returns
CpuIsaInfo A populated ISA feature structure
Definition at line 143 of file CpuIsaInfo.cpp.
References isa, and midr_to_model().
Referenced by CpuInfo::build().
 {
     CpuIsaInfo isa;
     decode_regs(isa, isar0, isar1, pfr0, svefr0);
     const CpuModel model = midr_to_model(midr);
     allowlisted_model_features(isa, model);
     return isa;
 }
midr_to_model()
CpuModel midr_to_model (uint32_t midr)
Extract the model type from the MIDR value.
Parameters
[in] midr MIDR information
Returns
CpuModel a mapped CPU model
Definition at line 78 of file CpuModel.cpp.
References arm_compute::A510, arm_compute::A53, arm_compute::A55r0, arm_compute::A55r1, arm_compute::A64FX, arm_compute::A73, arm_compute::GENERIC, arm_compute::GENERIC_FP16, arm_compute::GENERIC_FP16_DOT, arm_compute::V1, and arm_compute::X1.
Referenced by CpuInfo::build(), init_cpu_isa_from_hwcaps(), and init_cpu_isa_from_regs().
 {
     CpuModel model = CpuModel::GENERIC;
     // Unpack variant and CPU ID
     const int implementer = (midr >> 24) & 0xFF;
     const int variant     = (midr >> 20) & 0xF;
     const int cpunum      = (midr >> 4) & 0xFFF;
     // Only CPUs we have code paths for are detected.  All other CPUs can be safely classed as "GENERIC"
     if(implementer == 0x41) // Arm CPUs
     {
         switch(cpunum)
         {
             case 0xd03: // A53
             case 0xd04: // A35
                 model = CpuModel::A53;
                 break;
             case 0xd05: // A55
                 if(variant != 0)
                 {
                     model = CpuModel::A55r1;
                 }
                 else
                 {
                     model = CpuModel::A55r0;
                 }
                 break;
             case 0xd09: // A73
                 model = CpuModel::A73;
                 break;
             case 0xd0a: // A75
                 if(variant != 0)
                 {
                     model = CpuModel::GENERIC_FP16_DOT;
                 }
                 else
                 {
                     model = CpuModel::GENERIC_FP16;
                 }
                 break;
             case 0xd06: // A65
             case 0xd0b: // A76
             case 0xd0c: // N1
             case 0xd0d: // A77
             case 0xd0e: // A76AE
             case 0xd41: // A78
             case 0xd42: // A78AE
             case 0xd4a: // E1
                 model = CpuModel::GENERIC_FP16_DOT;
                 break;
             case 0xd40: // V1
                 model = CpuModel::V1;
                 break;
             case 0xd44: // X1
                 model = CpuModel::X1;
                 break;
             case 0xd46:
                 model = CpuModel::A510;
                 break;
             default:
                 model = CpuModel::GENERIC;
                 break;
         }
     }
     else if(implementer == 0x46)
     {
         switch(cpunum)
         {
             case 0x001: // A64FX
                 model = CpuModel::A64FX;
                 break;
             default:
                 model = CpuModel::GENERIC;
                 break;
         }
     }
     else if(implementer == 0x48)
     {
         switch(cpunum)
         {
             case 0xd40: // A76
                 model = CpuModel::GENERIC_FP16_DOT;
                 break;
             default:
                 model = CpuModel::GENERIC;
                 break;
         }
     }
     else if(implementer == 0x51)
     {
         switch(cpunum)
         {
             case 0x800: // A73
                 model = CpuModel::A73;
                 break;
             case 0x801: // A53
                 model = CpuModel::A53;
                 break;
             case 0x803: // A55r0
                 model = CpuModel::A55r0;
                 break;
             case 0x804: // A76
                 model = CpuModel::GENERIC_FP16_DOT;
                 break;
             case 0x805: // A55r1
                 model = CpuModel::A55r1;
                 break;
             default:
                 model = CpuModel::GENERIC;
                 break;
         }
     }
     return model;
 }
model_supports_dot()
bool model_supports_dot (CpuModel model)
Check if a model supports dot product.
Note
This is used in case of old kernel configurations where some capabilities are not exposed.
Parameters
[in] model Model to check for allowlisted capabilities
Definition at line 63 of file CpuModel.cpp.
References arm_compute::A510, arm_compute::A55r1, arm_compute::GENERIC_FP16_DOT, arm_compute::V1, and arm_compute::X1.
 {
     switch(model)
     {
         case CpuModel::GENERIC_FP16_DOT:
         case CpuModel::A55r1:
         case CpuModel::A510:
         case CpuModel::X1:
         case CpuModel::V1:
             return true;
         default:
             return false;
     }
 }
model_supports_fp16()
bool model_supports_fp16 (CpuModel model)
Check if a model supports half-precision floating point arithmetic.
Note
This is used in case of old kernel configurations where some capabilities are not exposed.
Parameters
[in] model Model to check for allowlisted capabilities
Definition at line 46 of file CpuModel.cpp.
References arm_compute::A510, arm_compute::A55r1, arm_compute::A64FX, arm_compute::GENERIC_FP16, arm_compute::GENERIC_FP16_DOT, arm_compute::V1, and arm_compute::X1.
 {
     switch(model)
     {
         case CpuModel::GENERIC_FP16:
         case CpuModel::GENERIC_FP16_DOT:
         case CpuModel::A55r1:
         case CpuModel::A510:
         case CpuModel::X1:
         case CpuModel::V1:
         case CpuModel::A64FX:
             return true;
         default:
             return false;
     }
 }
num_threads_hint()
uint32_t num_threads_hint ()
Some systems have both big and small cores, this fuction computes the minimum number of cores that are exactly the same on the system.
To maximize performance the library attempts to process workloads concurrently using as many threads as big cores are available on the system.
Returns
The minumum number of common cores.
Definition at line 391 of file CpuInfo.cpp.
References ARM_COMPUTE_ERROR_ON_MSG, ARM_COMPUTE_UNUSED, CpuInfo::cpus(), arm_compute::mlgo::parser::end(), and arm_compute::wrapper::vmin().
Referenced by CpuInfo::cpus(), and IScheduler::IScheduler().
 {
     unsigned int num_threads_hint = 1;
 #if !defined(BARE_METAL) && !defined(_WIN64)
     std::vector<std::string> cpus;
     cpus.reserve(64);
     // CPU part regex
     regex_t cpu_part_rgx;
     memset(&cpu_part_rgx, 0, sizeof(regex_t));
     int ret_status = regcomp(&cpu_part_rgx, R"(.*CPU part.+/?\:[[:space:]]+([[:alnum:]]+).*)", REG_EXTENDED);
     ARM_COMPUTE_UNUSED(ret_status);
     ARM_COMPUTE_ERROR_ON_MSG(ret_status != 0, "Regex compilation failed.");
     // Read cpuinfo and get occurrence of each core
     std::ifstream cpuinfo_file("/proc/cpuinfo", std::ios::in);
     if(cpuinfo_file.is_open())
     {
         std::string line;
         while(bool(getline(cpuinfo_file, line)))
         {
             std::array<regmatch_t, 2> match;
             if(regexec(&cpu_part_rgx, line.c_str(), 2, match.data(), 0) == 0)
             {
                 cpus.emplace_back(line.substr(match[1].rm_so, (match[1].rm_eo - match[1].rm_so)));
             }
         }
     }
     regfree(&cpu_part_rgx);
     // Get min number of threads
     std::sort(std::begin(cpus), std::end(cpus));
     auto least_frequent_cpu_occurences = [](const std::vector<std::string> &cpus) -> uint32_t
     {
         std::unordered_map<std::string, uint32_t> cpus_freq;
         for(const auto &cpu : cpus)
         {
             cpus_freq[cpu]++;
         }
         uint32_t vmin = cpus.size() + 1;
         for(const auto &cpu_freq : cpus_freq)
         {
             vmin = std::min(vmin, cpu_freq.second);
         }
         return vmin;
     };
     // Set thread hint
     num_threads_hint = cpus.empty() ? std::thread::hardware_concurrency() : least_frequent_cpu_occurences(cpus);
 #endif /* !defined(BARE_METAL) */
     return num_threads_hint;
 }