Compute Library: ClAddKernel Struct Reference
ClAddKernel Struct Reference
#include <ClKernelGraph.h>
Public Member Functions
Complexity complexity () const override
ClAddKernel ()=default
~ClAddKernel () override=default
ClAddKernel (const ClKernelGraph *graph, Id id, const ClKernelConfig &config, const ClEltwiseAddKernelDescriptor &desc, const ITensorDescPack< ClKernelTensor > tensors)
bool operator== (const ClKernel &other) const override
Status generate (ClKernelBlueprint &bp) const override
Public Member Functions inherited from ClKernel
ClKernel ()=default
virtual ~ClKernel ()=default
ClKernel (const ClKernel &kernel)=default
ClKernel & operator= (const ClKernel &kernel)=default
ClKernel (ClKernel &&kernel)=default
ClKernel & operator= (ClKernel &&kernel)=default
ClKernel (const ClKernelGraph *graph, Id id, const ClKernelConfig &config, const ITensorDescPack< ClKernelTensor > &tensors)
Id id () const
ITensorDescPack< ClKernelTensor > tensors () const
ClKernelConfig config () const
Static Public Member Functions
static Status validate (const ITensorInfo *lhs, const ITensorInfo *rhs, const ITensorInfo *dst)
Data Fields
ClEltwiseAddKernelDescriptor desc {}
Additional Inherited Members
Public Types inherited from ClKernel
using Id = DependencyGraph::Id
Detailed Description
Definition at line 142 of file ClKernelGraph.h.
Constructor & Destructor Documentation
ClAddKernel() [1/2]
ClAddKernel () default
~ClAddKernel()
~ClAddKernel () override default
ClAddKernel() [2/2]
ClAddKernel (const ClKernelGraph * graph, Id id, const ClKernelConfig & config, const ClEltwiseAddKernelDescriptor & desc, const ITensorDescPack< ClKernelTensor > tensors) inline
Definition at line 151 of file ClKernelGraph.h.
References arm_compute::test::validation::dst, arm_compute::experimental::dynamic_fusion::generate(), arm_compute::experimental::dynamic_fusion::operator==(), and arm_compute::experimental::dynamic_fusion::validate().
         : ClKernel{ graph, id, config, tensors }, desc{ desc }
     {
     }
Member Function Documentation
complexity()
Complexity complexity () const inline override virtual
Implements ClKernel.
Definition at line 145 of file ClKernelGraph.h.
References arm_compute::experimental::dynamic_fusion::Simple.
     {
         return Complexity::Simple;
     }
generate()
Status generate (ClKernelBlueprint & bp) const override virtual
Implements ClKernel.
Definition at line 127 of file ClKernelGraph.cpp.
References arm_compute::ACL_DST_0, arm_compute::ACL_SRC_0, arm_compute::ACL_SRC_1, arm_compute::experimental::dynamic_fusion::add_kcomp_eltwise_add(), arm_compute::experimental::dynamic_fusion::add_tensor(), ARM_COMPUTE_ERROR_ON_NULLPTR, ClDirectConv2dKernel::desc, and arm_compute::test::validation::dst.
 {
     const auto lhs = _tensors.get_const_tensor(TensorType::ACL_SRC_0);
     const auto rhs = _tensors.get_const_tensor(TensorType::ACL_SRC_1);
     const auto dst = _tensors.get_const_tensor(TensorType::ACL_DST_0);
     ARM_COMPUTE_ERROR_ON_NULLPTR(lhs, rhs, dst);
     ArgumentID lhs_id;
     add_tensor(bp, lhs->desc, lhs_id, lhs->id);
     ArgumentID rhs_id;
     add_tensor(bp, rhs->desc, rhs_id, rhs->id);
     ArgumentID dst_id;
     add_tensor(bp, dst->desc, dst_id, dst->id);
     add_kcomp_eltwise_add(bp, desc, lhs_id, rhs_id, dst_id);
     return Status{};
 }
operator==()
bool operator== (const ClKernel & other) const override virtual
Implements ClKernel.
Definition at line 189 of file ClKernelGraph.cpp.
References ClKernel::config(), ClDirectConv2dKernel::desc, and ClKernel::tensors().
 {
     const auto converted = *utils::cast::polymorphic_downcast<const ClAddKernel *>(&other);
     return config() == other.config() && tensors() == other.tensors() && desc == converted.desc;
 }
validate()
Status validate (const ITensorInfo * lhs, const ITensorInfo * rhs, const ITensorInfo * dst) static
Definition at line 144 of file ClKernelGraph.cpp.
References ARM_COMPUTE_RETURN_ERROR_ON, ARM_COMPUTE_RETURN_ERROR_ON_DATA_LAYOUT_NOT_IN, ARM_COMPUTE_RETURN_ERROR_ON_DATA_TYPE_CHANNEL_NOT_IN, ARM_COMPUTE_RETURN_ERROR_ON_F16_UNSUPPORTED, ARM_COMPUTE_RETURN_ERROR_ON_MISMATCHING_DATA_LAYOUT, ARM_COMPUTE_RETURN_ERROR_ON_MISMATCHING_DATA_TYPES, ARM_COMPUTE_RETURN_ERROR_ON_MSG, ARM_COMPUTE_RETURN_ERROR_ON_NULLPTR, TensorShape::broadcast_shape(), arm_compute::test::validation::dst, arm_compute::F16, arm_compute::F32, arm_compute::detail::have_different_dimensions(), arm_compute::NHWC, ITensorInfo::tensor_shape(), and TensorShape::total_size().
Referenced by AddContent::translate().
 {
     // 1. Check validity
     ARM_COMPUTE_RETURN_ERROR_ON_NULLPTR(lhs, rhs, dst);
     // Matching data type
     ARM_COMPUTE_RETURN_ERROR_ON_MISMATCHING_DATA_TYPES(lhs, rhs);
     ARM_COMPUTE_RETURN_ERROR_ON_MISMATCHING_DATA_TYPES(lhs, dst);
     // Matching data layout
     ARM_COMPUTE_RETURN_ERROR_ON_MISMATCHING_DATA_LAYOUT(lhs, rhs);
     ARM_COMPUTE_RETURN_ERROR_ON_MISMATCHING_DATA_LAYOUT(lhs, dst);
     // All tensor infos are initialized
     ARM_COMPUTE_RETURN_ERROR_ON(lhs->tensor_shape().total_size() == 0);
     ARM_COMPUTE_RETURN_ERROR_ON(rhs->tensor_shape().total_size() == 0);
     ARM_COMPUTE_RETURN_ERROR_ON(dst->tensor_shape().total_size() == 0);
     // Device requirements are met
     ARM_COMPUTE_RETURN_ERROR_ON_F16_UNSUPPORTED(lhs);
     const bool in_place      = (lhs == dst) || (rhs == dst);
     const bool src0_in_place = in_place && (lhs == dst);
     // dst shape is correct
     const TensorShape out_shape = TensorShape::broadcast_shape(lhs->tensor_shape(), rhs->tensor_shape());
     ARM_COMPUTE_RETURN_ERROR_ON_MSG(out_shape.total_size() == 0, "Inputs are not broadcast compatible");
     ARM_COMPUTE_RETURN_ERROR_ON_MSG(detail::have_different_dimensions(out_shape, dst->tensor_shape(), 0), "Wrong shape for dst");
     if(in_place)
     {
         ARM_COMPUTE_RETURN_ERROR_ON_MSG(detail::have_different_dimensions(out_shape, src0_in_place ? lhs->tensor_shape() : rhs->tensor_shape(), 0),
                                         "Wrong shape for dst, cannot do in_place calculation");
     }
     // 2. Check support level
     // Data type
     ARM_COMPUTE_RETURN_ERROR_ON_DATA_TYPE_CHANNEL_NOT_IN(lhs, 1, DataType::F32, DataType::F16);
     // Data layout
     ARM_COMPUTE_RETURN_ERROR_ON_DATA_LAYOUT_NOT_IN(lhs, DataLayout::NHWC);
     return Status{};
 }
Field Documentation
desc
ClEltwiseAddKernelDescriptor desc {}
Definition at line 159 of file ClKernelGraph.h.
The documentation for this struct was generated from the following files:
src/core/experimental/dynamic_fusion/WorkloadImpl/ClKernelGraph.h
src/core/experimental/dynamic_fusion/WorkloadImpl/ClKernelGraph.cpp