Compute Library: ClKernel Struct Reference
ClKernel Struct Reference abstract
#include <ClKernelGraph.h>
Public Types
using Id = DependencyGraph::Id
Public Member Functions
ClKernel ()=default
virtual ~ClKernel ()=default
ClKernel (const ClKernel &kernel)=default
ClKernel & operator= (const ClKernel &kernel)=default
ClKernel (ClKernel &&kernel)=default
ClKernel & operator= (ClKernel &&kernel)=default
ClKernel (const ClKernelGraph *graph, Id id, const ClKernelConfig &config, const ITensorDescPack< ClKernelTensor > &tensors)
virtual bool operator== (const ClKernel &other) const =0
virtual Complexity complexity () const =0
virtual Status generate (ClKernelBlueprint &bp) const =0
Id id () const
ITensorDescPack< ClKernelTensor > tensors () const
ClKernelConfig config () const
Detailed Description
Definition at line 85 of file ClKernelGraph.h.
Member Typedef Documentation
Id
using Id = DependencyGraph::Id
Definition at line 88 of file ClKernelGraph.h.
Constructor & Destructor Documentation
ClKernel() [1/4]
ClKernel () default
~ClKernel()
virtual ~ClKernel () virtual default
ClKernel() [2/4]
ClKernel (const ClKernel & kernel) default
ClKernel() [3/4]
ClKernel (ClKernel && kernel) default
ClKernel() [4/4]
ClKernel (const ClKernelGraph * graph, Id id, const ClKernelConfig & config, const ITensorDescPack< ClKernelTensor > & tensors) inline
Definition at line 95 of file ClKernelGraph.h.
References arm_compute::experimental::dynamic_fusion::generate(), and arm_compute::experimental::dynamic_fusion::operator==().
         : _graph{ graph }, _id{ id }, _config{ config }, _tensors{ tensors }
     {
     }
Member Function Documentation
complexity()
virtual Complexity complexity () const pure virtual
Implemented in ClAddKernel, and ClDirectConv2dKernel.
config()
ClKernelConfig config () const inline
Definition at line 110 of file ClKernelGraph.h.
Referenced by arm_compute::experimental::dynamic_fusion::generate_store(), ClDirectConv2dKernel::operator==(), and ClAddKernel::operator==().
     {
         return _config;
     }
generate()
virtual Status generate (ClKernelBlueprint & bp) const pure virtual
Implemented in ClAddKernel, and ClDirectConv2dKernel.
id()
Id id () const inline
Definition at line 102 of file ClKernelGraph.h.
     {
         return _id;
     }
operator=() [1/2]
ClKernel& operator= (const ClKernel & kernel) default
operator=() [2/2]
ClKernel& operator= (ClKernel && kernel) default
operator==()
virtual bool operator== (const ClKernel & other) const pure virtual
Implemented in ClAddKernel, and ClDirectConv2dKernel.
tensors()
ITensorDescPack<ClKernelTensor> tensors () const inline
Definition at line 106 of file ClKernelGraph.h.
Referenced by ClKernelFusionGroup::add_fused_kernel(), ClDirectConv2dKernel::operator==(), and ClAddKernel::operator==().
     {
         return _tensors;
     }
The documentation for this struct was generated from the following file:
src/core/experimental/dynamic_fusion/WorkloadImpl/ClKernelGraph.h