Compute Library: ClKernelBlueprint::Implementation Struct Reference
ClKernelBlueprint::Implementation Struct Reference
Intermediate representation of the final, complete kernel source.
#include <Common.h>
Public Member Functions
Implementation ()=default
~Implementation ()=default
Status update_merge_point (ArgumentID t_id, ArgumentID merge_point)
ArgumentID add_kernel_tensor (ITensorInfo *tensor_info, ArgumentID merge_point=DependencyGraph::empty_id())
void set_tile_info (const TileDescriptor &tile_info)
SharedVarGroup group (ArgumentID arg_id) const
void validate_arg_ids (std::initializer_list< ArgumentID > args) const
void add_component (ComponentUniquePtr component)
std::string build_kernel_name () const
std::string build_code ()
std::string build_config_id () const
Generate config id of the entire kernel.
CLBuildOptions build_options () const
TileDescriptor get_tile_info () const
Window get_execution_window () const
ArgumentID get_dst_id () const
ClKernelArgList get_arguments () const
SharedVarTable::Arguments get_argument_shared_vars () const
Get the arguments as shared vars from the vtable.
const ITensorInfo * get_kernel_argument_info (const ArgumentID id) const
ITensorInfo * get_kernel_argument_info (const ArgumentID id)
void finalize ()
Finalize graph construction.
DependencyGraph get_graph () const
Detailed Description
Intermediate representation of the final, complete kernel source.
Definition at line 417 of file Common.h.
Constructor & Destructor Documentation
Implementation()
Implementation () default
~Implementation()
~Implementation () default
Member Function Documentation
add_component()
void add_component (ComponentUniquePtr component) inline
Definition at line 464 of file Common.h.
References ARM_COMPUTE_ERROR_ON_MSG, arm_compute::experimental::dynamic_fusion::Complex, arm_compute::experimental::dynamic_fusion::Input, and arm_compute::experimental::dynamic_fusion::Store.
Referenced by arm_compute::experimental::dynamic_fusion::add_kcomp_direct_conv2d(), arm_compute::experimental::dynamic_fusion::add_kcomp_eltwise_add(), and arm_compute::experimental::dynamic_fusion::add_kcomp_store().
     {
         if(component->get_component_type() == ComponentType::Complex)
         {
             ++_num_complex_components;
             ARM_COMPUTE_ERROR_ON_MSG(_num_complex_components > 1, "Only one complex component per blueprint is supported.");
         }
         // Get an unique ID for the component that's being added
         std::vector<ArgumentID> src_tensors;
         std::vector<ArgumentID> dst_tensors;
         for(const auto &link : component->get_links())
         {
             if(link.is_empty())
             {
                 continue;
             }
             if(link.io == SharedVarIO::Input)
             {
                 src_tensors.push_back(link.arg_id);
             }
             else
             {
                 dst_tensors.push_back(link.arg_id);
             }
         }
         const ComponentID component_id = _graph.add_operator(src_tensors, dst_tensors).second;
         component->set_id(component_id);
         // Add this component to the component graph. Don't connect it to anything yet
         _component_graph.emplace(component_id, ComponentList{});
         // For every { arg_id, arg_io } passed along with this component...
         for(const auto &link : component->get_links())
         {
             const ArgumentID &arg_id = link.arg_id;
             const SharedVarIO &arg_io = link.io;
             // Add the arg_id to the map describing the input/output relationship between an argument and the components that use it, if it doesn't yet exist there
             if(_outgoing_components.find(arg_id) == _outgoing_components.end())
             {
                 _outgoing_components.emplace(arg_id, ComponentList{});
                 _incoming_components.emplace(arg_id, ComponentList{});
             }
             // If it's an input argument, connect any other component that has it as output with this component
             // Additionally, set this component as one that treats this argument as "Input" (append to index 0)
             // This is used so that we keep track of whether two components use the same argument, one as input and one as output
             if(arg_io == SharedVarIO::Input)
             {
                 for(const auto &prev_component : _incoming_components[arg_id])
                 {
                     _component_graph[prev_component].push_back(component_id);
                 }
                 _outgoing_components[arg_id].push_back(component_id);
             }
             // If it's an output argument, connect this component with any other component that has it as input
             // Additionally, set this component as one that treats this argument as "Output" (append to index 1)
             else
             {
                 if(component->get_component_type() == ComponentType::Store)
                 {
                     ARM_COMPUTE_ERROR_ON_MSG(_dst_id >= 0, "Trying to add more than one dst argument to the graph");
                     _dst_id = arg_id;
                 }
                 for(const auto &subseq_component : _outgoing_components[arg_id])
                 {
                     _component_graph[component_id].push_back(subseq_component);
                 }
                 _incoming_components[arg_id].push_back(component_id);
             }
         }
         ARM_COMPUTE_ERROR_ON_MSG(_graph.get_root_ops().size() != 1, "Trying to add more than one root to the graph");
         // Finally, add this component to the dictionary of components
         _components.insert(std::make_pair(component_id, std::move(component)));
     }
add_kernel_tensor()
ArgumentID add_kernel_tensor (ITensorInfo * tensor_info, ArgumentID merge_point = DependencyGraph::empty_id()) inline
Definition at line 429 of file Common.h.
Referenced by arm_compute::experimental::dynamic_fusion::add_tensor().
     {
         const auto id = _graph.add_tensor(merge_point);
         if(_kernel_tensors.find(id) == _kernel_tensors.end())
         {
             _kernel_tensors.insert(std::make_pair(id, tensor_info));
         }
         return id;
     }
build_code()
std::string build_code () inline
Definition at line 558 of file Common.h.
References ARM_COMPUTE_ERROR_ON_MSG, CLKernelLibrary::get(), CLKernelLibrary::get_program(), arm_compute::mlgo::parser::header(), and IClKernelComponent::replace_tags().
Referenced by arm_compute::experimental::dynamic_fusion::build().
     {
         ARM_COMPUTE_ERROR_ON_MSG(_graph_root < 0, "No root found in the component graph");
         // These data structures will hold the data from all the components in the blueprint
         std::set<std::string>    headers_list{};
         std::set<std::string>    additional_macros{};
         std::vector<std::string> component_codes{}; // vector because order matters
         // Step 1: Allocate all kernel argument shared variables before generating the component code
         auto stack = topological_sort();
         while(!stack.empty())
         {
             auto  curr_component_id = stack.top();
             auto &curr_component    = _components.find(curr_component_id)->second;
             curr_component->allocate_shared_vars(_vtable);
             stack.pop();
         }
         // Step 2: Generate component codes
         stack = topological_sort();
         while(!stack.empty())
         {
             auto  curr_component_id = stack.top();
             auto &curr_component    = _components.find(curr_component_id)->second;
             auto       curr_headers_list      = curr_component->get_headers_list();
             auto       curr_additional_macros = curr_component->get_additional_macros();
             auto       curr_component_code    = curr_component->get_component_code();
             const auto var_lut                = curr_component->get_tag_lut(_vtable); // Ideally can be merged with get_component_code once we have finer-grained code generation technique
             component_codes.push_back(IClKernelComponent::replace_tags(curr_component_code, var_lut));
             headers_list.insert(curr_headers_list.begin(), curr_headers_list.end());
             if(!curr_additional_macros.empty()) // Some components might not have any
             {
                 additional_macros.insert(IClKernelComponent::replace_tags(curr_additional_macros, var_lut));
             }
             stack.pop();
         }
         // Step 3: Assemble the data gathered by traversing the graph into the string "code"
         std::string code = "";
         for(auto &header : headers_list)
         {
 #if defined(EMBEDDED_KERNELS)
             code += CLKernelLibrary::get().get_program(header).first;
 #else  // defined(EMBEDDED_KERNELS)
             code += "#include \"" + header + "\"\n";
 #endif // defined(EMBEDDED_KERNELS)
         }
         for(auto &macros : additional_macros)
         {
             code += macros;
         }
         code += generate_kernel_signature(_vtable.get_kernel_arguments());
         code += "\n{\n\n";
         code += "    //------------------ START KERNEL_BUILDER_COORDINATE ---------------------\n\n";
         code += generate_global_section();
         code += "    //------------------ END KERNEL_BUILDER_COORDINATE ---------------------\n";
         for(auto &component_code : component_codes)
         {
             code += component_code;
         }
         code += "}\n";
         return code;
     }
build_config_id()
std::string build_config_id () const inline
Generate config id of the entire kernel.
Format: kernel_name–comp0_config_id–comp1_config_id–...
Returns
std::string
Definition at line 641 of file Common.h.
References arm_compute::experimental::dynamic_fusion::traverse().
Referenced by arm_compute::experimental::dynamic_fusion::build().
     {
         std::string config_id = build_kernel_name();
         traverse([&](std::stack<ComponentID> stack)
         {
             config_id += "--" + _components.find(stack.top())->second->generate_config_id() + "--";
         });
         return config_id;
     }
build_kernel_name()
std::string build_kernel_name () const inline
Definition at line 546 of file Common.h.
References name, and arm_compute::experimental::dynamic_fusion::traverse().
Referenced by arm_compute::experimental::dynamic_fusion::build().
     {
         std::string name = "";
         traverse([&](std::stack<ComponentID> stack)
         {
             name += _components.find(stack.top())->second->name() + (stack.size() > 2 ? "___" : "");
         });
         return name;
     }
build_options()
CLBuildOptions build_options () const inline
Definition at line 652 of file Common.h.
References arm_compute::experimental::dynamic_fusion::traverse().
Referenced by arm_compute::experimental::dynamic_fusion::build().
     {
         CLBuildOptions build_opts{};
         traverse([&](std::stack<ComponentID> stack)
         {
             build_opts.add_options(_components.find(stack.top())->second->generate_build_options().options());
         });
         return build_opts;
     }
finalize()
void finalize () inline
Finalize graph construction.
Graph is expected to not mutate after being finalized
Definition at line 722 of file Common.h.
Referenced by arm_compute::experimental::dynamic_fusion::build().
     {
         cache_root_component();
         assign_shared_var_group();
     }
get_argument_shared_vars()
SharedVarTable::Arguments get_argument_shared_vars () const inline
Get the arguments as shared vars from the vtable.
Returns
SharedVarTable::Arguments
Definition at line 696 of file Common.h.
     {
         return _vtable.get_kernel_arguments();
     }
get_arguments()
ClKernelArgList get_arguments () const inline
Definition at line 682 of file Common.h.
Referenced by arm_compute::experimental::dynamic_fusion::build().
     {
         ClKernelArgList arg_list{};
         for(const auto &arg_var : _vtable.get_kernel_arguments().get_all_vars())
         {
             arg_list[arg_var.desc.arg_id] = arg_var.desc;
         }
         return arg_list;
     }
get_dst_id()
ArgumentID get_dst_id () const inline
Definition at line 677 of file Common.h.
     {
         return _dst_id;
     }
get_execution_window()
Window get_execution_window () const inline
Definition at line 669 of file Common.h.
References ARM_COMPUTE_ERROR_ON_MSG.
Referenced by arm_compute::experimental::dynamic_fusion::build().
     {
         ARM_COMPUTE_ERROR_ON_MSG(_graph_root < 0, "No root found in the component graph");
         ARM_COMPUTE_ERROR_ON_MSG(_dst_id == -1, "Destination Tensor Id should be ready before calling get_execution_window()");
         return _components.find(_graph_root)->second->get_window();
     }
get_graph()
DependencyGraph get_graph () const inline
Definition at line 728 of file Common.h.
References arm_compute::experimental::dynamic_fusion::Argument, ARM_COMPUTE_ERROR, ARM_COMPUTE_ERROR_ON_MSG, arm_compute::experimental::dynamic_fusion::Automatic, arm_compute::experimental::dynamic_fusion::BOTTOM_LEFT, arm_compute::experimental::dynamic_fusion::BOTTOM_RIGHT, SharedVarTable::SharedVar::desc, SharedVarTable::Arguments::get_all_vars(), DependencyGraph::get_root_ops(), SharedVarTable::SharedVar::group, arm_compute::experimental::dynamic_fusion::Image, arm_compute::experimental::dynamic_fusion::Image_3D, arm_compute::experimental::dynamic_fusion::Image_3D_Export_To_ClImage2D, arm_compute::cpu::step, arm_compute::experimental::dynamic_fusion::Tensor_4D_t_Buffer, arm_compute::experimental::dynamic_fusion::Tensor_4D_t_Image, ClKernelArgDescriptor::tensor_arg_type, arm_compute::experimental::dynamic_fusion::to_string(), arm_compute::experimental::dynamic_fusion::TOP_LEFT, arm_compute::experimental::dynamic_fusion::TOP_RIGHT, arm_compute::experimental::dynamic_fusion::traverse(), SharedVarTable::SharedVar::uniq_name, and arm_compute::experimental::dynamic_fusion::Vector.
Referenced by arm_compute::experimental::dynamic_fusion::get_dependency_graph().
     {
         return _graph;
     }
get_kernel_argument_info() [1/2]
const ITensorInfo* get_kernel_argument_info (const ArgumentID id) const inline
Definition at line 701 of file Common.h.
     {
         auto it = _kernel_tensors.find(id);
         if(it != _kernel_tensors.end())
         {
             return it->second;
         }
         return nullptr;
     }
get_kernel_argument_info() [2/2]
ITensorInfo* get_kernel_argument_info (const ArgumentID id) inline
Definition at line 711 of file Common.h.
     {
         auto it = _kernel_tensors.find(id);
         if(it != _kernel_tensors.end())
         {
             return it->second;
         }
         return nullptr;
     }
get_tile_info()
TileDescriptor get_tile_info () const inline
Definition at line 664 of file Common.h.
     {
         return _tile_info;
     }
group()
SharedVarGroup group (ArgumentID arg_id) const inline
Definition at line 444 of file Common.h.
References arm_compute::experimental::dynamic_fusion::Argument.
     {
         if(arg_id == g_arg_placeholder)
         {
             // In case of placeholder, don't care what we return;
             return SharedVarGroup::Argument;
         }
         return _shared_var_group_lut.at(arg_id);
     }
set_tile_info()
void set_tile_info (const TileDescriptor & tile_info) inline
Definition at line 439 of file Common.h.
Referenced by arm_compute::experimental::dynamic_fusion::set_tile_info().
     {
         _tile_info = tile_info;
     }
update_merge_point()
Status update_merge_point (ArgumentID t_id, ArgumentID merge_point) inline
Definition at line 424 of file Common.h.
Referenced by arm_compute::experimental::dynamic_fusion::update_merge_point().
     {
         return _graph.update_merge_point(t_id, merge_point);
     }
validate_arg_ids()
void validate_arg_ids (std::initializer_list< ArgumentID > args) const inline
Definition at line 454 of file Common.h.
References ARM_COMPUTE_ERROR_ON_MSG, and ARM_COMPUTE_UNUSED.
     {
         for(const auto arg_id : args)
         {
             ARM_COMPUTE_UNUSED(arg_id);
             ARM_COMPUTE_ERROR_ON_MSG(_kernel_tensors.find(arg_id) == _kernel_tensors.end() && arg_id != g_arg_placeholder,
                                      "Trying to use an argument that hasn't been added to the blueprint");
         }
     }
The documentation for this struct was generated from the following file:
src/core/experimental/dynamic_fusion/ClKernelBuildingImpl/Common.h