# SPDX-FileCopyrightText: 2024-2025 Arm Limited
#
# SPDX-License-Identifier: MIT
#
# Permission is hereby granted, free of charge, to any person obtaining a copy
# of this software and associated documentation files (the "Software"), to
# deal in the Software without restriction, including without limitation the
# rights to use, copy, modify, merge, publish, distribute, sublicense, and/or
# sell copies of the Software, and to permit persons to whom the Software is
# furnished to do so, subject to the following conditions:
#
# The above copyright notice and this permission notice shall be included in all
# copies or substantial portions of the Software.
#
# THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
# IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
# FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
# AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
# LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
# OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
# SOFTWARE.

version = 1

[[annotations]]
path = ["filedefs.json"]
SPDX-FileCopyrightText = "2021-2023, 2025 Arm Limited"
SPDX-License-Identifier = "MIT"

[[annotations]]
path = ["filelist.json"]
SPDX-FileCopyrightText = "2021-2025 Arm Limited"
SPDX-License-Identifier = "MIT"

[[annotations]]
path = [
	"data/images/*",
	".clang-tidy",
	"SECURITY.md"
]
SPDX-FileCopyrightText = "2020 Arm Limited"
SPDX-License-Identifier = "MIT"

[[annotations]]
path = [".github/issue_template.md"]
SPDX-FileCopyrightText = "2018 Arm Limited"
SPDX-License-Identifier = "MIT"

[[annotations]]
path = ["CONTRIBUTING.md"]
SPDX-FileCopyrightText = "2022-2025 Arm Limited"
SPDX-License-Identifier = "MIT"

[[annotations]]
path = ["README.md"]
SPDX-FileCopyrightText = "2018-2025 Arm Limited"
SPDX-License-Identifier = "MIT"

[[annotations]]
path = ["examples/gemm_tuner/README.md"]
SPDX-FileCopyrightText = "2019-2021 Arm Limited"
SPDX-License-Identifier = "MIT"

[[annotations]]
path = ["python/scripts/report-model-ops/README.md"]
SPDX-FileCopyrightText = "2021 Arm Limited"
SPDX-License-Identifier = "MIT"

[[annotations]]
path = ["docs/contributor_guide/non_inclusive_language_examples.dox"]
SPDX-FileCopyrightText = "2022 Arm Limited"
SPDX-License-Identifier = "MIT"
