Compute Library: FullyConnectedLayer Class Reference
FullyConnectedLayer Class Reference final
Fully Connected Layer.
#include <Layers.h>
Public Member Functions
FullyConnectedLayer (unsigned int num_outputs, ITensorAccessorUPtr weights, ITensorAccessorUPtr bias, const FullyConnectedLayerInfo fc_info=FullyConnectedLayerInfo(), const QuantizationInfo weights_quant_info=QuantizationInfo(), const QuantizationInfo out_quant_info=QuantizationInfo())
Construct a fully connected layer.
FullyConnectedLayer (unsigned int num_outputs, SubStream sub_stream_weights, SubStream sub_stream_bias, const FullyConnectedLayerInfo fc_info=FullyConnectedLayerInfo(), const QuantizationInfo weights_quant_info=QuantizationInfo(), const QuantizationInfo out_quant_info=QuantizationInfo())
Construct a fully connected layer.
NodeID create_layer (IStream &s) override
Create layer and add to the given stream.
Public Member Functions inherited from ILayer
virtual ~ILayer ()=default
Default destructor.
ILayer & set_name (std::string name)
Sets the name of the layer.
const std::string & name () const
Layer name accessor.
Detailed Description
Fully Connected Layer.
Definition at line 643 of file Layers.h.
Constructor & Destructor Documentation
FullyConnectedLayer() [1/2]
FullyConnectedLayer (unsigned int num_outputs, ITensorAccessorUPtr weights, ITensorAccessorUPtr bias, const FullyConnectedLayerInfo fc_info = FullyConnectedLayerInfo(), const QuantizationInfo weights_quant_info = QuantizationInfo(), const QuantizationInfo out_quant_info = QuantizationInfo()) inline
Construct a fully connected layer.
Parameters
[in] num_outputs Number of outputs.
[in] weights Accessor to get weights from.
[in] bias Accessor to get bias from.
[in] fc_info (Optional) Fully connected layer metadata
[in] weights_quant_info (Optional) Weights quantization information
[in] out_quant_info (Optional) Output quantization info
Definition at line 655 of file Layers.h.
         : _num_outputs(num_outputs),
           _weights(std::move(weights)),
           _bias(std::move(bias)),
           _weights_ss(nullptr),
           _bias_ss(nullptr),
           _fc_info(fc_info),
           _weights_quant_info(std::move(weights_quant_info)),
           _out_quant_info(std::move(out_quant_info))
     {
     }
FullyConnectedLayer() [2/2]
FullyConnectedLayer (unsigned int num_outputs, SubStream sub_stream_weights, SubStream sub_stream_bias, const FullyConnectedLayerInfo fc_info = FullyConnectedLayerInfo(), const QuantizationInfo weights_quant_info = QuantizationInfo(), const QuantizationInfo out_quant_info = QuantizationInfo()) inline
Construct a fully connected layer.
Parameters
[in] num_outputs Number of outputs.
[in] sub_stream_weights Graph sub-stream for the weights.
[in] sub_stream_bias Graph sub-stream for the bias.
[in] fc_info (Optional) Fully connected layer metadata
[in] weights_quant_info (Optional) Weights quantization information
[in] out_quant_info (Optional) Output quantization info
Definition at line 681 of file Layers.h.
         : _num_outputs(num_outputs),
           _weights(nullptr),
           _bias(nullptr),
           _weights_ss(arm_compute::support::cpp14::make_unique<SubStream>(std::move(sub_stream_weights))),
           _bias_ss(arm_compute::support::cpp14::make_unique<SubStream>(std::move(sub_stream_bias))),
           _fc_info(fc_info),
           _weights_quant_info(std::move(weights_quant_info)),
           _out_quant_info(std::move(out_quant_info))
     {
     }
Member Function Documentation
create_layer()
NodeID create_layer (IStream & s) inline override virtual
Create layer and add to the given stream.
Parameters
[in] s Stream to add layer to.
Returns
ID of the created node.
Implements ILayer.
Definition at line 704 of file Layers.h.
     {
         NodeParams  common_params = { name(), s.hints().target_hint };
         NodeIdxPair input         = { s.tail_node(), 0 };
         if(_weights != nullptr)
         {
             return GraphBuilder::add_fully_connected_layer(s.graph(), common_params, input, _num_outputs,
                                                            std::move(_weights), std::move(_bias), _fc_info,
                                                            std::move(_weights_quant_info), std::move(_out_quant_info));
         }
         else
         {
             ARM_COMPUTE_ERROR_ON(_weights_ss == nullptr);
             NodeID bias_nid = (_bias_ss == nullptr) ? EmptyNodeID : _bias_ss->tail_node();
             return GraphBuilder::add_fully_connected_layer(s.graph(), common_params, input, _num_outputs,
                                                            _weights_ss->tail_node(), bias_nid, _fc_info,
                                                            std::move(_out_quant_info));
         }
     }
References GraphBuilder::add_fully_connected_layer(), ARM_COMPUTE_ERROR_ON, arm_compute::graph::EmptyNodeID, IStream::graph(), IStream::hints(), arm_compute::test::validation::input, ILayer::name(), IStream::tail_node(), and StreamHints::target_hint.
The documentation for this class was generated from the following file:
arm_compute/graph/frontend/Layers.h