ARM Compute Library: examples/cl_convolution.cpp File Reference
cl_convolution.cpp File Reference
#include "arm_compute/core/Types.h"
#include "arm_compute/runtime/CL/CLFunctions.h"
#include "arm_compute/runtime/CL/CLScheduler.h"
#include "test_helpers/Utils.h"
Macros
#define ARM_COMPUTE_CL /* So that OpenCL exceptions get caught too */
Functions
void main_cl_convolution (int argc, const char **argv)
int main (int argc, const char **argv)
Main program for convolution test.
Variables
const int16_t gaussian3x3 []
Gaussian 3x3 matrix.
const int16_t gaussian5x5 []
Gaussian 5x5 matrix.
Macro Definition Documentation
#define ARM_COMPUTE_CL /* So that OpenCL exceptions get caught too */
Definition at line 24 of file cl_convolution.cpp.
Function Documentation
int main (int argc, const char ** argv)
Main program for convolution test.
Parameters
[in] argc Number of arguments
[in] argv Arguments ([optional] Path to PPM image to process)
Definition at line 115 of file cl_convolution.cpp.
References main_cl_convolution(), and test_helpers::run_example().
 {
     return test_helpers::run_example(argc, argv, main_cl_convolution);
 }
void main_cl_convolution (int argc, const char ** argv)
Definition at line 53 of file cl_convolution.cpp.
References ITensorAllocator::allocate(), CLTensor::allocator(), CLConvolution3x3::configure(), CLConvolutionSquare< matrix_size >::configure(), CLScheduler::default_init(), PPMLoader::fill_image(), gaussian3x3, gaussian5x5, CLScheduler::get(), CLTensor::info(), ITensorAllocator::init(), PPMLoader::init_image(), PPMLoader::is_open(), PPMLoader::open(), ICLSimpleFunction::run(), CLConvolutionSquare< matrix_size >::run(), test_helpers::save_to_ppm(), CLScheduler::sync(), arm_compute::U8, and arm_compute::UNDEFINED.
Referenced by main().
 {
     PPMLoader ppm;
     CLImage   src, tmp, dst;
     CLScheduler::get().default_init();
     if(argc < 2)
     {
         // Print help
         std::cout << "Usage: ./build/cl_convolution [input_image.ppm]\n\n";
         std::cout << "No input_image provided, creating a dummy 640x480 image\n";
         // Create an empty grayscale 640x480 image
         src.allocator()->init(TensorInfo(640, 480, Format::U8));
     }
     else
     {
         ppm.open(argv[1]);
         ppm.init_image(src, Format::U8);
     }
     // Configure the temporary and destination images
     tmp.allocator()->init(*src.info());
     dst.allocator()->init(*src.info());
     CLConvolution3x3 conv3x3;
     CLConvolution5x5 conv5x5;
     // Apply a Gaussian 3x3 filter to the source image followed by a Gaussian 5x5:
     conv3x3.configure(&src, &tmp, gaussian3x3, 0 /* Let arm_compute calculate the scale */, BorderMode::UNDEFINED);
     conv5x5.configure(&tmp, &dst, gaussian5x5, 0 /* Let arm_compute calculate the scale */, BorderMode::UNDEFINED);
     // Allocate all the images
     src.allocator()->allocate();
     tmp.allocator()->allocate();
     dst.allocator()->allocate();
     // Fill the input image with the content of the PPM image if a filename was provided:
     if(ppm.is_open())
     {
         ppm.fill_image(src);
     }
     // Execute the functions:
     conv3x3.run();
     conv5x5.run();
     // Make sure all the OpenCL jobs are done executing:
     CLScheduler::get().sync();
     // Save the result to file:
     if(ppm.is_open())
     {
         const std::string output_filename = std::string(argv[1]) + "_out.ppm";
         save_to_ppm(dst, output_filename); // save_to_ppm maps and unmaps the image to store as PPM
     }
 }
Variable Documentation
const int16_t gaussian3x3[]
Initial value:
=
{
    1, 2, 1,
    2, 4, 2,
    1, 2, 1
}
Gaussian 3x3 matrix.
Definition at line 35 of file cl_convolution.cpp.
Referenced by main_cl_convolution().
const int16_t gaussian5x5[]
Initial value:
=
{
    1, 4, 6, 4, 1,
    4, 16, 24, 16, 4,
    6, 24, 36, 24, 6,
    4, 16, 24, 16, 4,
    1, 4, 6, 4, 1
}
Gaussian 5x5 matrix.
Definition at line 44 of file cl_convolution.cpp.
Referenced by main_cl_convolution().