ARM Compute Library: PPMLoader Class Reference
PPMLoader Class Reference
Class to load the content of a PPM file into an Image.
#include <Utils.h>
Public Member Functions
PPMLoader ()
void open (const std::string &ppm_filename)
Open a PPM file and reads its metadata (Width, height)
bool is_open ()
Return true if a PPM file is currently open.
template<typename T >
void init_image (T &image, Format format)
Initialise an image's metadata with the dimensions of the PPM file currently open.
template<typename T >
void fill_image (T &image)
Fill an image with the content of the currently open PPM file.
Detailed Description
Class to load the content of a PPM file into an Image.
Definition at line 83 of file Utils.h.
Constructor & Destructor Documentation
PPMLoader () inline
Definition at line 86 of file Utils.h.
         : _fs(), _width(0), _height(0)
     {
     }
Member Function Documentation
void fill_image (T & image) inline
Fill an image with the content of the currently open PPM file.
Note
If the image is a CLImage, the function maps and unmaps the image
Parameters
[in,out] image Image to fill (Must be allocated, and of matching dimensions with the opened PPM).
Definition at line 142 of file Utils.h.
References ARM_COMPUTE_ERROR, ARM_COMPUTE_ERROR_ON, ARM_COMPUTE_ERROR_ON_FORMAT_NOT_IN, ARM_COMPUTE_ERROR_ON_MSG, ARM_COMPUTE_UNUSED, Window::DimX, Window::DimY, arm_compute::execute_window_loop(), Iterator::ptr(), arm_compute::RGB888, Window::set(), and arm_compute::U8.
Referenced by main_cl_convolution(), main_cl_events(), main_neon_convolution(), main_neon_scale(), and main_neoncl_scale_median_gaussian().
     {
         ARM_COMPUTE_ERROR_ON(!is_open());
         ARM_COMPUTE_ERROR_ON(image.info()->dimension(0) != _width || image.info()->dimension(1) != _height);
         ARM_COMPUTE_ERROR_ON_FORMAT_NOT_IN(&image, Format::U8, Format::RGB888);
         try
         {
 #ifdef ARM_COMPUTE_CL
             // Map buffer if creating a CLTensor
             if(std::is_same<typename std::decay<T>::type, CLImage>::value)
             {
                 image.map();
             }
 #endif
             // Check if the file is large enough to fill the image
             const size_t current_position = _fs.tellg();
             _fs.seekg(0, std::ios_base::end);
             const size_t end_position = _fs.tellg();
             _fs.seekg(current_position, std::ios_base::beg);
             ARM_COMPUTE_ERROR_ON_MSG((end_position - current_position) < image.info()->tensor_shape().total_size() * image.info()->element_size(),
                                      "Not enough data in file");
             ARM_COMPUTE_UNUSED(end_position);
             switch(image.info()->format())
             {
                 case Format::U8:
                 {
                     // We need to convert the data from RGB to grayscale:
                     // Iterate through every pixel of the image
                     Window window;
                     window.set(Window::DimX, Window::Dimension(0, _width, 1));
                     window.set(Window::DimY, Window::Dimension(0, _height, 1));
                     Iterator out(&image, window);
                     unsigned char red   = 0;
                     unsigned char green = 0;
                     unsigned char blue  = 0;
                     execute_window_loop(window, [&](const Coordinates & id)
                     {
                         red   = _fs.get();
                         green = _fs.get();
                         blue  = _fs.get();
                         *out.ptr() = 0.2126f * red + 0.7152f * green + 0.0722f * blue;
                     },
                     out);
                     break;
                 }
                 case Format::RGB888:
                 {
                     // There is no format conversion needed: we can simply copy the content of the input file to the image one row at the time.
                     // Create a vertical window to iterate through the image's rows:
                     Window window;
                     window.set(Window::DimY, Window::Dimension(0, _height, 1));
                     Iterator out(&image, window);
                     execute_window_loop(window, [&](const Coordinates & id)
                     {
                         // Copy one row from the input file to the current row of the image:
                         _fs.read(reinterpret_cast<std::fstream::char_type *>(out.ptr()), _width * image.info()->element_size());
                     },
                     out);
                     break;
                 }
                 default:
                     ARM_COMPUTE_ERROR("Unsupported format");
             }
 #ifdef ARM_COMPUTE_CL
             // Unmap buffer if creating a CLTensor
             if(std::is_same<typename std::decay<T>::type, CLTensor>::value)
             {
                 image.unmap();
             }
 #endif
         }
         catch(const std::ifstream::failure &e)
         {
             ARM_COMPUTE_ERROR("Loading PPM file: %s", e.what());
         }
     }
void init_image (T & image, Format format) inline
Initialise an image's metadata with the dimensions of the PPM file currently open.
Parameters
[out] image Image to initialise
[in] format Format to use for the image (Must be RGB888 or U8)
Definition at line 125 of file Utils.h.
References ARM_COMPUTE_ERROR_ON, arm_compute::RGB888, and arm_compute::U8.
Referenced by main_cl_convolution(), main_cl_events(), main_neon_convolution(), main_neon_scale(), and main_neoncl_scale_median_gaussian().
     {
         ARM_COMPUTE_ERROR_ON(!is_open());
         ARM_COMPUTE_ERROR_ON(format != Format::RGB888 && format != Format::U8);
         // Use the size of the input PPM image
         TensorInfo image_info(_width, _height, format);
         image.allocator()->init(image_info);
     }
bool is_open () inline
Return true if a PPM file is currently open.
Definition at line 114 of file Utils.h.
Referenced by main_cl_convolution(), main_cl_events(), main_neon_convolution(), main_neon_scale(), and main_neoncl_scale_median_gaussian().
     {
         return _fs.is_open();
     }
void open (const std::string & ppm_filename) inline
Open a PPM file and reads its metadata (Width, height)
Parameters
[in] ppm_filename File to open
Definition at line 94 of file Utils.h.
References ARM_COMPUTE_ERROR, ARM_COMPUTE_ERROR_ON, ARM_COMPUTE_ERROR_ON_MSG, and test_helpers::parse_ppm_header().
Referenced by main_cl_convolution(), main_cl_events(), main_neon_convolution(), main_neon_scale(), and main_neoncl_scale_median_gaussian().
     {
         ARM_COMPUTE_ERROR_ON(is_open());
         try
         {
             _fs.exceptions(std::ifstream::failbit | std::ifstream::badbit);
             _fs.open(ppm_filename, std::ios::in | std::ios::binary);
             unsigned int max_val = 0;
             std::tie(_width, _height, max_val) = parse_ppm_header(_fs);
             ARM_COMPUTE_ERROR_ON_MSG(max_val >= 256, "2 bytes per colour channel not supported in file %s", ppm_filename.c_str());
         }
         catch(const std::ifstream::failure &e)
         {
             ARM_COMPUTE_ERROR("Accessing %s: %s", ppm_filename.c_str(), e.what());
         }
     }
The documentation for this class was generated from the following file:
test_helpers/Utils.h