ARM Compute Library: test_helpers Namespace Reference
test_helpers Namespace Reference
Data Structures
class PPMLoader
Class to load the content of a PPM file into an Image.
Typedefs
using example = void(int argc, const char **argv)
Signature of an example to run.
Functions
int run_example (int argc, const char **argv, example &func)
Run an example and handle the potential exceptions it throws.
void draw_detection_rectangle (ITensor *tensor, const DetectionWindow &rect, uint8_t r, uint8_t g, uint8_t b)
Draw a RGB rectangular window for the detected object.
std::tuple< unsigned int, unsigned int, int > parse_ppm_header (std::ifstream &fs)
Parse the ppm header from an input file stream.
template<typename T >
void save_to_ppm (T &tensor, const std::string &ppm_filename)
Template helper function to save a tensor image to a PPM file.
Typedef Documentation
using example = void(int argc, const char **argv)
Signature of an example to run.
Parameters
[in] argc Number of command line arguments
[in] argv Command line arguments
Definition at line 52 of file Utils.h.
Function Documentation
void draw_detection_rectangle (ITensor * tensor, const DetectionWindow & rect, uint8_t r, uint8_t g, uint8_t b)
Draw a RGB rectangular window for the detected object.
Parameters
[in,out] tensor Input tensor where the rectangle will be drawn on. Format supported: RGB888
[in] rect Geometry of the rectangular window
[in] r Red colour to use
[in] g Green colour to use
[in] b Blue colour to use
Definition at line 99 of file Utils.cpp.
References ARM_COMPUTE_ERROR_ON_FORMAT_NOT_IN, ITensor::buffer(), DetectionWindow::height, ITensor::info(), TensorInfo::offset_element_in_bytes(), TensorInfo::strides_in_bytes(), DetectionWindow::width, DetectionWindow::x, and DetectionWindow::y.
 {
     ARM_COMPUTE_ERROR_ON_FORMAT_NOT_IN(tensor, Format::RGB888);
     uint8_t *top    = tensor->info()->offset_element_in_bytes(Coordinates(rect.x, rect.y)) + tensor->buffer();
     uint8_t *bottom = tensor->info()->offset_element_in_bytes(Coordinates(rect.x, rect.y + rect.height)) + tensor->buffer();
     uint8_t *left   = top;
     uint8_t *right  = tensor->info()->offset_element_in_bytes(Coordinates(rect.x + rect.width, rect.y)) + tensor->buffer();
     size_t   stride = tensor->info()->strides_in_bytes()[Window::DimY];
     for(size_t x = 0; x < rect.width; ++x)
     {
         top[0]    = r;
         top[1]    = g;
         top[2]    = b;
         bottom[0] = r;
         bottom[1] = g;
         bottom[2] = b;
         top += 3;
         bottom += 3;
     }
     for(size_t y = 0; y < rect.height; ++y)
     {
         left[0]  = r;
         left[1]  = g;
         left[2]  = b;
         right[0] = r;
         right[1] = g;
         right[2] = b;
         left += stride;
         right += stride;
     }
 }
std::tuple< unsigned int, unsigned int, int > parse_ppm_header (std::ifstream & fs)
Parse the ppm header from an input file stream.
At the end of the execution, the file position pointer will be located at the first pixel stored in the ppm file
Parameters
[in] fs Input file stream to parse
Returns
The width, height and max value stored in the header of the PPM file
Definition at line 136 of file Utils.cpp.
References ARM_COMPUTE_ERROR_ON_MSG, and ARM_COMPUTE_UNUSED.
Referenced by PPMLoader::open().
 {
     // Check the PPM magic number is valid
     std::array<char, 2> magic_number{ { 0 } };
     fs >> magic_number[0] >> magic_number[1];
     ARM_COMPUTE_ERROR_ON_MSG(magic_number[0] != 'P' || magic_number[1] != '6', "Invalid file type");
     ARM_COMPUTE_UNUSED(magic_number);
     discard_comments_and_spaces(fs);
     unsigned int width = 0;
     fs >> width;
     discard_comments_and_spaces(fs);
     unsigned int height = 0;
     fs >> height;
     discard_comments_and_spaces(fs);
     int max_val = 0;
     fs >> max_val;
     discard_comments(fs);
     ARM_COMPUTE_ERROR_ON_MSG(isspace(fs.peek()) == 0, "Invalid PPM header");
     fs.ignore(1);
     return std::make_tuple(width, height, max_val);
 }
int run_example (int argc, const char ** argv, example & func)
Run an example and handle the potential exceptions it throws.
Parameters
[in] argc Number of command line arguments
[in] argv Command line arguments
[in] func Pointer to the function containing the code to run
Definition at line 65 of file Utils.cpp.
Referenced by main().
 {
     std::cout << "\n"
               << argv[0] << "\n\n";
     try
     {
         func(argc, argv);
         std::cout << "\nTest passed\n";
         return 0;
     }
 #ifdef ARM_COMPUTE_CL
     catch(cl::Error &err)
     {
         std::cerr << "!!!!!!!!!!!!!!!!!!!!!!!!!!!" << std::endl;
         std::cerr << std::endl
                   << "ERROR " << err.what() << "(" << err.err() << ")" << std::endl;
         std::cerr << "!!!!!!!!!!!!!!!!!!!!!!!!!!!" << std::endl;
     }
 #endif /* ARM_COMPUTE_CL */
     catch(std::runtime_error &err)
     {
         std::cerr << "!!!!!!!!!!!!!!!!!!!!!!!!!!!" << std::endl;
         std::cerr << std::endl
                   << "ERROR " << err.what() << " " << (errno ? strerror(errno) : "") << std::endl;
         std::cerr << "!!!!!!!!!!!!!!!!!!!!!!!!!!!" << std::endl;
     }
     std::cout << "\nTest FAILED\n";
     return -1;
 }
void test_helpers::save_to_ppm (T & tensor, const std::string & ppm_filename)
Template helper function to save a tensor image to a PPM file.
Note
Only U8 and RGB888 formats supported.
Only works with 2D tensors.
If the input tensor is a CLTensor, the function maps and unmaps the image
Parameters
[in] tensor The tensor to save as PPM file
[in] ppm_filename Filename of the file to create.
Definition at line 245 of file Utils.h.
References ARM_COMPUTE_ERROR, ARM_COMPUTE_ERROR_ON, ARM_COMPUTE_ERROR_ON_FORMAT_NOT_IN, Window::DimX, Window::DimY, arm_compute::execute_window_loop(), Iterator::ptr(), arm_compute::RGB888, Window::set(), and arm_compute::U8.
Referenced by main_cl_convolution(), main_cl_events(), main_neon_convolution(), main_neon_scale(), and main_neoncl_scale_median_gaussian().
 {
     ARM_COMPUTE_ERROR_ON_FORMAT_NOT_IN(&tensor, Format::RGB888, Format::U8);
     ARM_COMPUTE_ERROR_ON(tensor.info()->num_dimensions() > 2);
     std::ofstream fs;
     try
     {
         fs.exceptions(std::ofstream::failbit | std::ofstream::badbit | std::ofstream::eofbit);
         fs.open(ppm_filename, std::ios::out | std::ios::binary);
         const unsigned int width  = tensor.info()->tensor_shape()[0];
         const unsigned int height = tensor.info()->tensor_shape()[1];
         fs << "P6\n"
            << width << " " << height << " 255\n";
 #ifdef ARM_COMPUTE_CL
         // Map buffer if creating a CLTensor
         if(std::is_same<typename std::decay<T>::type, CLTensor>::value)
         {
             tensor.map();
         }
 #endif
         switch(tensor.info()->format())
         {
             case Format::U8:
             {
                 Window window;
                 window.set(Window::DimX, Window::Dimension(0, width, 1));
                 window.set(Window::DimY, Window::Dimension(0, height, 1));
                 Iterator in(&tensor, window);
                 execute_window_loop(window, [&](const Coordinates & id)
                 {
                     const unsigned char value = *in.ptr();
                     fs << value << value << value;
                 },
                 in);
                 break;
             }
             case Format::RGB888:
             {
                 Window window;
                 window.set(Window::DimX, Window::Dimension(0, width, width));
                 window.set(Window::DimY, Window::Dimension(0, height, 1));
                 Iterator in(&tensor, window);
                 execute_window_loop(window, [&](const Coordinates & id)
                 {
                     fs.write(reinterpret_cast<std::fstream::char_type *>(in.ptr()), width * tensor.info()->element_size());
                 },
                 in);
                 break;
             }
             default:
                 ARM_COMPUTE_ERROR("Unsupported format");
         }
 #ifdef ARM_COMPUTE_CL
         // Unmap buffer if creating a CLTensor
         if(std::is_same<typename std::decay<T>::type, CLTensor>::value)
         {
             tensor.unmap();
         }
 #endif
     }
     catch(const std::ofstream::failure &e)
     {
         ARM_COMPUTE_ERROR("Writing %s: (%s)", ppm_filename.c_str(), e.what());
     }
 }