Compute Library: NEWinogradLayerBatchedGEMMKernel< TIn, TOut, OutputTileRows, OutputTileCols, KernelRows, KernelCols > Class Template Reference
NEWinogradLayerBatchedGEMMKernel< TIn, TOut, OutputTileRows, OutputTileCols, KernelRows, KernelCols > Class Template Reference
#include <NEWinogradLayerKernel.h>
Public Types
using WinogradBase = winograd::WinogradGEMM< OutputTileRows, OutputTileCols, KernelRows, KernelCols >
using WinogradConv = typename WinogradBase::template Convolution< TIn, TOut >
using MultiGEMM = winograd::BatchedBlockedGemm< WinogradConv::M_BLOCK, WinogradConv::N_BLOCK, TIn, TOut >
Public Member Functions
const char * name () const override
Name of the kernel.
NEWinogradLayerBatchedGEMMKernel ()
Constructor.
NEWinogradLayerBatchedGEMMKernel (const NEWinogradLayerBatchedGEMMKernel &)=delete
Prevent instances of this class from being copied (As this class contains pointers)
NEWinogradLayerBatchedGEMMKernel & operator= (const NEWinogradLayerBatchedGEMMKernel &)=delete
Prevent instances of this class from being copied (As this class contains pointers)
NEWinogradLayerBatchedGEMMKernel (NEWinogradLayerBatchedGEMMKernel &&)=default
Allow instances of this class to be moved.
NEWinogradLayerBatchedGEMMKernel & operator= (NEWinogradLayerBatchedGEMMKernel &&)=default
Allow instances of this class to be moved.
~NEWinogradLayerBatchedGEMMKernel ()=default
unsigned int get_number_gemms () const override
Get the number of GEMMs to compute.
int get_output_tile_rows () const override
Get the number of tiles per row.
int get_output_tile_cols () const override
Get the number of tiles per columns.
int get_number_blocks () const override
Get the number of blocks.
void configure (const unsigned int n_gemms, const int M, const int K, const int N, const int a_matrix_stride, const int a_row_stride, const int b_matrix_stride, const int b_row_stride, const int c_matrix_stride, const int c_row_stride, const TIn *const a_ptr, const TIn *const b_ptr, TOut *const c_ptr) override
Initialise the kernel.
void run (const Window &window, const ThreadInfo &info) override
Execute the kernel on the passed window.
Public Member Functions inherited from ICPPKernel
virtual ~ICPPKernel ()=default
Default destructor.
Public Member Functions inherited from IKernel
IKernel ()
Constructor.
virtual ~IKernel ()=default
Destructor.
virtual bool is_parallelisable () const
Indicates whether or not the kernel is parallelisable.
virtual BorderSize border_size () const
The size of the border for that kernel.
const Window & window () const
The maximum window the kernel can be executed on.
Static Public Attributes
static const int _output_tile_rows = OutputTileRows
static const int _output_tile_cols = OutputTileCols
Detailed Description
template<typename TIn, typename TOut, int OutputTileRows, int OutputTileCols, int KernelRows, int KernelCols>
class arm_compute::NEWinogradLayerBatchedGEMMKernel< TIn, TOut, OutputTileRows, OutputTileCols, KernelRows, KernelCols >
Definition at line 410 of file NEWinogradLayerKernel.h.
Member Typedef Documentation
using MultiGEMM = winograd::BatchedBlockedGemm<WinogradConv::M_BLOCK, WinogradConv::N_BLOCK, TIn, TOut>
Definition at line 415 of file NEWinogradLayerKernel.h.
using WinogradBase = winograd::WinogradGEMM<OutputTileRows, OutputTileCols, KernelRows, KernelCols>
Definition at line 413 of file NEWinogradLayerKernel.h.
using WinogradConv = typename WinogradBase::template Convolution<TIn, TOut>
Definition at line 414 of file NEWinogradLayerKernel.h.
Constructor & Destructor Documentation
NEWinogradLayerBatchedGEMMKernel ()
Constructor.
NEWinogradLayerBatchedGEMMKernel (const NEWinogradLayerBatchedGEMMKernel< TIn, TOut, OutputTileRows, OutputTileCols, KernelRows, KernelCols > &) delete
Prevent instances of this class from being copied (As this class contains pointers)
NEWinogradLayerBatchedGEMMKernel (NEWinogradLayerBatchedGEMMKernel< TIn, TOut, OutputTileRows, OutputTileCols, KernelRows, KernelCols > &&) default
Allow instances of this class to be moved.
~NEWinogradLayerBatchedGEMMKernel () default
Member Function Documentation
void configure (const unsigned int n_gemms, const int M, const int K, const int N, const int a_matrix_stride, const int a_row_stride, const int b_matrix_stride, const int b_row_stride, const int c_matrix_stride, const int c_row_stride, const TIn *const a_ptr, const TIn *const b_ptr, TOut *const c_ptr) override virtual
Initialise the kernel.
Parameters
[in] n_gemms Number of GEMMs to compute.
[in] M in_shape.n_batches * tile_rows * tile_cols.
[in] K Number of channels in the input tensor.
[in] N Number of channels in the output tensor.
[in] a_matrix_stride Stride between input matrices.
[in] a_row_stride Row stride inside input matrix.
[in] b_matrix_stride Stride between weights matrices.
[in] b_row_stride Row stride inside the weights matrix.
[in] c_matrix_stride Stride between output matrices.
[in] c_row_stride Row stride inside the output matrix.
[out] a_ptr Input workspace.
[out] b_ptr Kernel workspace.
[out] c_ptr Output workspace.
Implements INEWinogradLayerBatchedGEMMKernel< TIn, TOut >.
int get_number_blocks () const override virtual
Get the number of blocks.
Implements INEWinogradLayerBatchedGEMMKernel< TIn, TOut >.
unsigned int get_number_gemms () const override virtual
Get the number of GEMMs to compute.
Implements INEWinogradLayerBatchedGEMMKernel< TIn, TOut >.
int get_output_tile_cols () const override virtual
Get the number of tiles per columns.
Implements INEWinogradLayerBatchedGEMMKernel< TIn, TOut >.
int get_output_tile_rows () const override virtual
Get the number of tiles per row.
Implements INEWinogradLayerBatchedGEMMKernel< TIn, TOut >.
const char* name () const inline override virtual
Name of the kernel.
Returns
Kernel name
Implements ICPPKernel.
Definition at line 420 of file NEWinogradLayerKernel.h.
References INEWinogradLayerTransformInputKernel< T >::configure(), arm_compute::test::validation::info(), ICPPKernel::run(), and IKernel::window().
     {
         return "NEWinogradLayerBatchedGEMMKernel";
     }
NEWinogradLayerBatchedGEMMKernel& operator= (const NEWinogradLayerBatchedGEMMKernel< TIn, TOut, OutputTileRows, OutputTileCols, KernelRows, KernelCols > &) delete
Prevent instances of this class from being copied (As this class contains pointers)
NEWinogradLayerBatchedGEMMKernel& operator= (NEWinogradLayerBatchedGEMMKernel< TIn, TOut, OutputTileRows, OutputTileCols, KernelRows, KernelCols > &&) default
Allow instances of this class to be moved.
void run (const Window & window, const ThreadInfo & info) override virtual
Execute the kernel on the passed window.
Warning
If is_parallelisable() returns false then the passed window must be equal to window()
Note
The window has to be a region within the window returned by the window() method
The width of the window has to be a multiple of num_elems_processed_per_iteration().
Parameters
[in] window Region on which to execute the kernel. (Must be a region of the window returned by window())
[in] info Info about executing thread and CPU.
Implements ICPPKernel.
Field Documentation
const int _output_tile_cols = OutputTileCols static
Definition at line 418 of file NEWinogradLayerKernel.h.
const int _output_tile_rows = OutputTileRows static
Definition at line 417 of file NEWinogradLayerKernel.h.
The documentation for this class was generated from the following file:
arm_compute/core/NEON/kernels/NEWinogradLayerKernel.h