Compute Library: NEWinogradLayerTransformOutputKernel< T, OutputTileRows, OutputTileCols, KernelRows, KernelCols > Class Template Reference
NEWinogradLayerTransformOutputKernel< T, OutputTileRows, OutputTileCols, KernelRows, KernelCols > Class Template Reference
#include <NEWinogradLayerKernel.h>
Public Member Functions
const char * name () const override
Name of the kernel.
NEWinogradLayerTransformOutputKernel ()
Constructor.
NEWinogradLayerTransformOutputKernel (const NEWinogradLayerTransformOutputKernel &)=delete
Prevent instances of this class from being copied (As this class contains pointers)
NEWinogradLayerTransformOutputKernel & operator= (const NEWinogradLayerTransformOutputKernel &)=delete
Prevent instances of this class from being copied (As this class contains pointers)
NEWinogradLayerTransformOutputKernel (NEWinogradLayerTransformOutputKernel &&)=default
Allow instances of this class to be moved.
NEWinogradLayerTransformOutputKernel & operator= (NEWinogradLayerTransformOutputKernel &&)=default
Allow instances of this class to be moved.
~NEWinogradLayerTransformOutputKernel ()=default
unsigned int get_output_storage_size (int n_batches, int n_rows, int n_cols, int n_output_channels, bool same_padding) const override
Determine how much memory (in units of TOut) to allocate for the (Winograd domain) output.
int get_matrix_stride (const KernelShape &kernel_shape, const Tensor4DShape &input_shape, const PaddingType padding_type) const override
Gets the stride between matrices in the output worspace.
Tensor4DShape get_output_shape (const KernelShape &kernel_shape, const Tensor4DShape &in_shape, const PaddingType padding) const override
Get the output shape of a convolution.
void configure (const ITensor *biases, const T *const output_workingspace, const int matrix_stride, T *const output, const int n_batches, const int n_rows, const int n_cols, const int n_channels) override
Configure the output transform kernel.
void run (const Window &window, const ThreadInfo &info) override
Execute the kernel on the passed window.
bool is_parallelisable () const override
Indicates whether or not the kernel is parallelisable.
Public Member Functions inherited from INEWinogradLayerTransformOutputKernel< T >
virtual ~INEWinogradLayerTransformOutputKernel ()
Public Member Functions inherited from ICPPKernel
virtual ~ICPPKernel ()=default
Default destructor.
Public Member Functions inherited from IKernel
IKernel ()
Constructor.
virtual ~IKernel ()=default
Destructor.
virtual BorderSize border_size () const
The size of the border for that kernel.
const Window & window () const
The maximum window the kernel can be executed on.
Detailed Description
template<typename T, int OutputTileRows, int OutputTileCols, int KernelRows, int KernelCols>
class arm_compute::NEWinogradLayerTransformOutputKernel< T, OutputTileRows, OutputTileCols, KernelRows, KernelCols >
Definition at line 212 of file NEWinogradLayerKernel.h.
Constructor & Destructor Documentation
NEWinogradLayerTransformOutputKernel ()
Constructor.
NEWinogradLayerTransformOutputKernel (const NEWinogradLayerTransformOutputKernel< T, OutputTileRows, OutputTileCols, KernelRows, KernelCols > &) delete
Prevent instances of this class from being copied (As this class contains pointers)
NEWinogradLayerTransformOutputKernel (NEWinogradLayerTransformOutputKernel< T, OutputTileRows, OutputTileCols, KernelRows, KernelCols > &&) default
Allow instances of this class to be moved.
~NEWinogradLayerTransformOutputKernel () default
Member Function Documentation
void configure (const ITensor * biases, const T *const output_workingspace, const int matrix_stride, T *const output, const int n_batches, const int n_rows, const int n_cols, const int n_channels) override virtual
Configure the output transform kernel.
Parameters
[in] biases Pointer to the biases tensor.
[in] output_workingspace Pointer to working space for the output tensor in the Winograd domain.
[in] matrix_stride Output matrix stride, can be computed with winograd::WinogradGEMM<2, 2, 3, 3>::Convolution<float, float>::get_output_matrix_stride()
[out] output Pointer to NHWC ordered output tensor, in the spatial domain.
[in] n_batches Number of batches in the input tensor.
[in] n_rows Number of rows in output tensor.
[in] n_cols Number of columns in output tensor.
[in] n_channels Number of feature maps in the output tensor.
Implements INEWinogradLayerTransformOutputKernel< T >.
int get_matrix_stride (const KernelShape & kernel_shape, const Tensor4DShape & input_shape, const PaddingType padding_type) const override virtual
Gets the stride between matrices in the output worspace.
Parameters
[in] kernel_shape The shape of the weights tensor.
[in] input_shape The shape of the input tensor.
[in] padding_type The type of padding to be used.
Returns
Stride expressed in bytes.
Implements INEWinogradLayerTransformOutputKernel< T >.
Tensor4DShape get_output_shape (const KernelShape & kernel_shape, const Tensor4DShape & in_shape, const PaddingType padding) const override virtual
Get the output shape of a convolution.
Parameters
[in] kernel_shape The shape of the weights tensor.
[in] in_shape The shape of the input tensor.
[in] padding The type of padding to be used.
Returns
Stride expressed in bytes.
Implements INEWinogradLayerTransformOutputKernel< T >.
unsigned int get_output_storage_size (int n_batches, int n_rows, int n_cols, int n_output_channels, bool same_padding) const override virtual
Determine how much memory (in units of TOut) to allocate for the (Winograd domain) output.
Parameters
[in] n_batches Number of batches in the output tensor.
[in] n_rows Number of rows in each feature map of the input tensor.
[in] n_cols Number of columns in each feature map of the input tensor.
[in] n_output_channels Number of feature maps in the output tensor.
[in] same_padding Use "SAME" padding, otherwise use "VALID".
Implements INEWinogradLayerTransformOutputKernel< T >.
bool is_parallelisable () const override virtual
Indicates whether or not the kernel is parallelisable.
If the kernel is parallelisable then the window returned by window() can be split into sub-windows which can then be run in parallel.
If the kernel is not parallelisable then only the window returned by window() can be passed to run()
Returns
True if the kernel is parallelisable
Reimplemented from IKernel.
const char* name () const inline override virtual
Name of the kernel.
Returns
Kernel name
Implements ICPPKernel.
Definition at line 215 of file NEWinogradLayerKernel.h.
References INEWinogradLayerTransformInputKernel< T >::configure(), INEWinogradLayerTransformInputKernel< T >::get_matrix_stride(), arm_compute::test::validation::info(), IKernel::is_parallelisable(), padding, ICPPKernel::run(), and IKernel::window().
     {
         return "NEWinogradLayerTransformOutputKernel";
     }
NEWinogradLayerTransformOutputKernel& operator= (const NEWinogradLayerTransformOutputKernel< T, OutputTileRows, OutputTileCols, KernelRows, KernelCols > &) delete
Prevent instances of this class from being copied (As this class contains pointers)
NEWinogradLayerTransformOutputKernel& operator= (NEWinogradLayerTransformOutputKernel< T, OutputTileRows, OutputTileCols, KernelRows, KernelCols > &&) default
Allow instances of this class to be moved.
void run (const Window & window, const ThreadInfo & info) override virtual
Execute the kernel on the passed window.
Warning
If is_parallelisable() returns false then the passed window must be equal to window()
Note
The window has to be a region within the window returned by the window() method
The width of the window has to be a multiple of num_elems_processed_per_iteration().
Parameters
[in] window Region on which to execute the kernel. (Must be a region of the window returned by window())
[in] info Info about executing thread and CPU.
Implements ICPPKernel.
The documentation for this class was generated from the following file:
arm_compute/core/NEON/kernels/NEWinogradLayerKernel.h