Compute Library: src/c/AclTensor.cpp File Reference
AclTensor.cpp File Reference
#include "arm_compute/AclEntrypoints.h"
#include "arm_compute/AclUtils.h"
#include "src/common/ITensorV2.h"
#include "src/common/utils/Macros.h"
Functions
AclStatus AclCreateTensor (AclTensor *external_tensor, AclContext external_ctx, const AclTensorDescriptor *desc, bool allocate)
Create a Tensor object.
AclStatus AclMapTensor (AclTensor external_tensor, void **handle)
Map a tensor's backing memory to the host.
AclStatus AclUnmapTensor (AclTensor external_tensor, void *handle)
Unmap the tensor's backing memory.
AclStatus AclTensorImport (AclTensor external_tensor, void *handle, AclImportMemoryType type)
Import external memory to a given tensor object.
AclStatus AclDestroyTensor (AclTensor external_tensor)
Destroy a given tensor object.
AclStatus AclGetTensorSize (AclTensor tensor, uint64_t *size)
__cplusplus
AclStatus AclGetTensorDescriptor (AclTensor tensor, AclTensorDescriptor *desc)
Get the descriptor of this tensor.
Function Documentation
AclCreateTensor()
AclStatus AclCreateTensor (AclTensor * tensor, AclContext ctx, const AclTensorDescriptor * desc, bool allocate)
Create a Tensor object.
Tensor is a generalized matrix construct that can represent up to ND dimensionality (where N = 6 for Compute Library) The object holds a backing memory along-side to operate on
Parameters
[in,out] tensor A valid non-zero tensor object if no failures occur
[in] ctx Context to be used
[in] desc Tensor representation meta-data
[in] allocate Instructs allocation of the tensor objects
Returns:
AclSuccess if function was completed successfully
AclOutOfMemory if there was a failure allocating memory resources
AclUnsupportedTarget if the requested target is unsupported
AclInvalidArgument if a given argument is invalid
Definition at line 68 of file AclTensor.cpp.
References AclInvalidArgument, AclOutOfMemory, AclSuccess, ARM_COMPUTE_LOG_ERROR_ACL, ARM_COMPUTE_RETURN_CENUM_ON_FAILURE, IContext::create_tensor(), arm_compute::get_internal(), and arm_compute::detail::validate_internal_context().
Referenced by Tensor::Tensor().
 {
     using namespace arm_compute;
     IContext *ctx = get_internal(external_ctx);
     StatusCode status = detail::validate_internal_context(ctx);
     ARM_COMPUTE_RETURN_CENUM_ON_FAILURE(status);
     if(desc == nullptr || !is_desc_valid(*desc))
     {
         ARM_COMPUTE_LOG_ERROR_ACL("[AclCreateTensor]: Descriptor is invalid!");
         return AclInvalidArgument;
     }
     auto tensor = ctx->create_tensor(*desc, allocate);
     if(tensor == nullptr)
     {
         ARM_COMPUTE_LOG_ERROR_ACL("[AclCreateTensor]: Couldn't allocate internal resources for tensor creation!");
         return AclOutOfMemory;
     }
     *external_tensor = tensor;
     return AclSuccess;
 }
AclDestroyTensor()
AclStatus AclDestroyTensor (AclTensor tensor)
Destroy a given tensor object.
Parameters
[in,out] tensor A valid tensor object to be destroyed
Returns
Status code
Returns:
AclSuccess if function was completed successfully
AclInvalidArgument if the provided tensor is invalid
Definition at line 144 of file AclTensor.cpp.
References AclSuccess, ARM_COMPUTE_RETURN_CENUM_ON_FAILURE, arm_compute::get_internal(), and arm_compute::detail::validate_internal_tensor().
 {
     using namespace arm_compute;
     auto tensor = get_internal(external_tensor);
     StatusCode status = detail::validate_internal_tensor(tensor);
     ARM_COMPUTE_RETURN_CENUM_ON_FAILURE(status);
     delete tensor;
     return AclSuccess;
 }
AclGetTensorDescriptor()
AclStatus AclGetTensorDescriptor (AclTensor tensor, AclTensorDescriptor * desc)
Get the descriptor of this tensor.
Parameters
[in] tensor A tensor in interest
[out] desc The descriptor of the tensor
Returns
Status code
AclSuccess if function was completed successfully
AclInvalidArgument if a given argument is invalid
Definition at line 175 of file AclTensor.cpp.
References AclInvalidArgument, and ARM_COMPUTE_RETURN_CENUM_ON_FAILURE.
Referenced by Tensor::get_descriptor().
 {
     using namespace arm_compute;
     if(desc == nullptr)
     {
         return AclStatus::AclInvalidArgument;
     }
     ITensorV2 *internal_tensor{ nullptr };
     const auto status = convert_and_validate_tensor(tensor, &internal_tensor);
     ARM_COMPUTE_RETURN_CENUM_ON_FAILURE(status);
     *desc = internal_tensor->get_descriptor();
     return utils::as_cenum<AclStatus>(status);
 }
AclGetTensorSize()
AclStatus AclGetTensorSize (AclTensor tensor, uint64_t * size)
__cplusplus
Get the size of the existing tensor in byte
Note
The size isn't based on allocated memory, but based on information in its descriptor (dimensions, data type, etc.).
Parameters
[in] tensor A tensor in interest
[out] size The size of the tensor
Returns
Status code
AclSuccess if function was completed successfully
AclInvalidArgument if a given argument is invalid
Definition at line 158 of file AclTensor.cpp.
References AclInvalidArgument, and ARM_COMPUTE_RETURN_CENUM_ON_FAILURE.
Referenced by Tensor::get_size().
 {
     using namespace arm_compute;
     if(size == nullptr)
     {
         return AclStatus::AclInvalidArgument;
     }
     ITensorV2 *internal_tensor{ nullptr };
     auto       status = convert_and_validate_tensor(tensor, &internal_tensor);
     ARM_COMPUTE_RETURN_CENUM_ON_FAILURE(status);
     *size = internal_tensor->get_size();
     return utils::as_cenum<AclStatus>(status);
 }
AclMapTensor()
AclStatus AclMapTensor (AclTensor tensor, void ** handle)
Map a tensor's backing memory to the host.
Parameters
[in] tensor Tensor to be mapped
[in,out] handle A handle to the underlying backing memory
Returns
Status code
Returns:
AclSuccess if function was completed successfully
AclInvalidArgument if a given argument is invalid
Definition at line 97 of file AclTensor.cpp.
References AclInvalidArgument, AclSuccess, ARM_COMPUTE_LOG_ERROR_ACL, ARM_COMPUTE_RETURN_CENUM_ON_FAILURE, arm_compute::get_internal(), and arm_compute::detail::validate_internal_tensor().
Referenced by Tensor::map().
 {
     using namespace arm_compute;
     auto       tensor = get_internal(external_tensor);
     StatusCode status = detail::validate_internal_tensor(tensor);
     ARM_COMPUTE_RETURN_CENUM_ON_FAILURE(status);
     if(handle == nullptr)
     {
         ARM_COMPUTE_LOG_ERROR_ACL("[AclMapTensor]: Handle object is nullptr!");
         return AclInvalidArgument;
     }
     *handle = tensor->map();
     return AclSuccess;
 }
AclTensorImport()
AclStatus AclTensorImport (AclTensor tensor, void * handle, AclImportMemoryType type)
Import external memory to a given tensor object.
Parameters
[in,out] tensor Tensor to import memory to
[in] handle Backing memory to be imported
[in] type Type of the imported memory
Returns:
AclSuccess if function was completed successfully
AclInvalidArgument if a given argument is invalid
Definition at line 130 of file AclTensor.cpp.
References AclSuccess, ARM_COMPUTE_RETURN_CENUM_ON_FAILURE, arm_compute::get_internal(), and arm_compute::detail::validate_internal_tensor().
Referenced by Tensor::import().
 {
     using namespace arm_compute;
     auto       tensor = get_internal(external_tensor);
     StatusCode status = detail::validate_internal_tensor(tensor);
     ARM_COMPUTE_RETURN_CENUM_ON_FAILURE(status);
     status = tensor->import(handle, utils::as_enum<ImportMemoryType>(type));
     ARM_COMPUTE_RETURN_CENUM_ON_FAILURE(status);
     return AclSuccess;
 }
AclUnmapTensor()
AclStatus AclUnmapTensor (AclTensor tensor, void * handle)
Unmap the tensor's backing memory.
Parameters
[in] tensor tensor to unmap memory from
[in] handle Backing memory to be unmapped
Returns
Status code
Returns:
AclSuccess if function was completed successfully
AclInvalidArgument if a given argument is invalid
Definition at line 116 of file AclTensor.cpp.
References AclSuccess, ARM_COMPUTE_RETURN_CENUM_ON_FAILURE, ARM_COMPUTE_UNUSED, arm_compute::get_internal(), and arm_compute::detail::validate_internal_tensor().
Referenced by Tensor::unmap().
 {
     ARM_COMPUTE_UNUSED(handle);
     using namespace arm_compute;
     auto       tensor = get_internal(external_tensor);
     StatusCode status = detail::validate_internal_tensor(tensor);
     ARM_COMPUTE_RETURN_CENUM_ON_FAILURE(status);
     status = tensor->unmap();
     return AclSuccess;
 }