Compute Library: ITransformWeights Class Reference
ITransformWeights Class Reference abstract
Weights tensor transform interface In order to identify the different reshape functions, each reshape function has to generate a unique id.
#include <ITransformWeights.h>
Public Member Functions
ITransformWeights ()=default
Default Constructor.
virtual ~ITransformWeights ()=default
Default Destructor.
ITransformWeights (const ITransformWeights &)=delete
Prevent instances of this class to be copy constructed.
ITransformWeights & operator= (const ITransformWeights &)=delete
Prevent instances of this class to be copied.
ITransformWeights (ITransformWeights &&other)
Allow instances of this class to be move constructed.
ITransformWeights & operator= (ITransformWeights &&other)
Allow instances of this class to be moved.
virtual ITensor * get_weights ()=0
Get a pointer to the transformed weights.
virtual uint32_t uid ()=0
Function that returns a unique id of the reshape function.
virtual void run ()=0
Run the transformation function.
virtual void release ()=0
Release transformed weights memory.
void increase_refcount ()
Increase the object's refcount.
int32_t decrease_refcount ()
Decrease the object's refcount and return the updated value.
bool is_reshape_run ()
Function that returns a flag on whether the weights are reshaped or not.
Detailed Description
Weights tensor transform interface In order to identify the different reshape functions, each reshape function has to generate a unique id.
We use the following conversion using an unsigned 32bit value:
Lower two bits store the target: 00 -> Neon 01 -> CL 11 -> Unused
Five bits store the id of the reshape function: 00000 -> FullyConnectedLayerReshapeWeights 00001 -> ConvertFullyConnectedWeights 00010 -> ConvolutionLayerReshapeWeights 00011 -> DepthwiseConvolutionLayerReshapeWeights 00100 -> GEMMReshapeLHSMatrixKernel 00101 -> GEMMReshapeRHSMatrixKernel
Rest of the bits are used for identifying special cases such as assembly functions and extra arguments in the reshape kernels.
Definition at line 56 of file ITransformWeights.h.
Constructor & Destructor Documentation
ITransformWeights() [1/3]
ITransformWeights () default
Default Constructor.
~ITransformWeights()
virtual ~ITransformWeights () virtual default
Default Destructor.
ITransformWeights() [2/3]
ITransformWeights (const ITransformWeights &) delete
Prevent instances of this class to be copy constructed.
ITransformWeights() [3/3]
ITransformWeights (ITransformWeights && other) inline
Allow instances of this class to be move constructed.
Definition at line 68 of file ITransformWeights.h.
     {
         *this = std::move(other);
     }
Member Function Documentation
decrease_refcount()
int32_t decrease_refcount () inline
Decrease the object's refcount and return the updated value.
Returns
The updated refcount
Definition at line 107 of file ITransformWeights.h.
     {
         return --_num_refcount;
     }
get_weights()
virtual ITensor* get_weights () pure virtual
Get a pointer to the transformed weights.
Returns
The pointer to the transformed ITensor weights
Implemented in CLConvertFullyConnectedWeightsManaged, and NEFullyConnectedLayerReshapeWeightsManaged.
Referenced by IWeightsManager::acquire(), ITransformWeights::operator=(), and IWeightsManager::run().
increase_refcount()
void increase_refcount () inline
Increase the object's refcount.
Definition at line 98 of file ITransformWeights.h.
Referenced by IWeightsManager::acquire().
     {
         ++_num_refcount;
     }
is_reshape_run()
bool is_reshape_run () inline
Function that returns a flag on whether the weights are reshaped or not.
Returns
True if the function is reshaped
Definition at line 116 of file ITransformWeights.h.
     {
         return _reshape_run;
     }
operator=() [1/2]
ITransformWeights& operator= (const ITransformWeights &) delete
Prevent instances of this class to be copied.
operator=() [2/2]
ITransformWeights& operator= (ITransformWeights && other) inline
Allow instances of this class to be moved.
Definition at line 73 of file ITransformWeights.h.
References ITransformWeights::get_weights(), ITransformWeights::release(), ITransformWeights::run(), and ITransformWeights::uid().
     {
         if(this != &other)
         {
             _num_refcount = other._num_refcount.load();
             _reshape_run  = other._reshape_run;
         }
         return *this;
     }
release()
virtual void release () pure virtual
Release transformed weights memory.
Implemented in CLConvertFullyConnectedWeightsManaged, and NEFullyConnectedLayerReshapeWeightsManaged.
Referenced by ITransformWeights::operator=().
run()
virtual void run () pure virtual
Run the transformation function.
Implemented in CLConvertFullyConnectedWeightsManaged, and NEFullyConnectedLayerReshapeWeightsManaged.
Referenced by ITransformWeights::operator=(), and IWeightsManager::run().
uid()
virtual uint32_t uid () pure virtual
Function that returns a unique id of the reshape function.
Returns
The computed unique id
Implemented in CLConvertFullyConnectedWeightsManaged, and NEFullyConnectedLayerReshapeWeightsManaged.
Referenced by IWeightsManager::acquire(), ITransformWeights::operator=(), and IWeightsManager::run().
The documentation for this class was generated from the following file:
arm_compute/runtime/ITransformWeights.h