Compute Library: Size3D Class Reference
Size3D Class Reference
Class for specifying the size of a 3D shape or object.
#include <Size3D.h>
Public Member Functions
Size3D ()=default
Default constructor.
Size3D (size_t w, size_t h, size_t d) noexcept
Constructor.
std::string to_string () const
Convert the values stored to string.
size_t x () const
Semantic accessor for width as x.
size_t y () const
Semantic accessor for height as y.
size_t z () const
Semantic accessor for depth as z.
bool operator!= (const Size3D &other) const
bool operator== (const Size3D &other) const
Data Fields
size_t width = {}
Width of the 3D shape or object.
size_t height = {}
Height of the 3D shape or object.
size_t depth = {}
Depth of the 3D shape or object.
Detailed Description
Class for specifying the size of a 3D shape or object.
Definition at line 32 of file Size3D.h.
Constructor & Destructor Documentation
Size3D() [1/2]
Size3D () default
Default constructor.
Size3D() [2/2]
Size3D (size_t w, size_t h, size_t d) inline noexcept
Constructor.
Initializes "width", "height" and "depth" respectively with "w", "h" and "d"
Parameters
[in] w Width of the 3D shape or object
[in] h Height of the 3D shape or object
[in] d Depth of the 3D shape or object
Definition at line 43 of file Size3D.h.
References Size3D::to_string().
         : width(w), height(h), depth(d)
     {
     }
Member Function Documentation
operator!=()
bool operator!= (const Size3D & other) const inline
Definition at line 81 of file Size3D.h.
     {
         return !(*this == other);
     }
operator==()
bool operator== (const Size3D & other) const inline
Definition at line 86 of file Size3D.h.
References Size3D::depth, Size3D::height, and Size3D::width.
     {
         return (width == other.width) && (height == other.height) && (depth == other.depth);
     }
to_string()
std::string to_string () const
Convert the values stored to string.
Returns
string of (width x height x depth).
Definition at line 29 of file Size3D.cpp.
References Size3D::depth, Size3D::height, arm_compute::support::cpp11::to_string(), and Size3D::width.
Referenced by Size3D::Size3D().
 {
     return support::cpp11::to_string(width) + std::string("x") + support::cpp11::to_string(height) + std::string("x") + support::cpp11::to_string(depth);
 }
x()
size_t x () const inline
Semantic accessor for width as x.
Returns
x.
Definition at line 58 of file Size3D.h.
References Size3D::width.
Referenced by arm_compute::misc::shape_calculator::compute_conv3d_shape(), ClDirectConv3dKernel::configure(), and arm_compute::test::validation::reference::conv3d().
     {
         return width;
     }
y()
size_t y () const inline
Semantic accessor for height as y.
Returns
y.
Definition at line 67 of file Size3D.h.
References Size3D::height.
Referenced by arm_compute::misc::shape_calculator::compute_conv3d_shape(), ClDirectConv3dKernel::configure(), and arm_compute::test::validation::reference::conv3d().
     {
         return height;
     }
z()
size_t z () const inline
Semantic accessor for depth as z.
Returns
z.
Definition at line 76 of file Size3D.h.
References Size3D::depth.
Referenced by arm_compute::misc::shape_calculator::compute_conv3d_shape(), ClDirectConv3dKernel::configure(), and arm_compute::test::validation::reference::conv3d().
     {
         return depth;
     }
Field Documentation
depth
size_t depth = {}
Depth of the 3D shape or object.
Definition at line 94 of file Size3D.h.
Referenced by arm_compute::misc::shape_calculator::compute_conv3d_shape(), arm_compute::cpu::directconv3d_float_neon_ndhwc(), arm_compute::cpu::directconv3d_quantized_neon_ndhwc(), arm_compute::operator<<(), Size3D::operator==(), Size3D::to_string(), and Size3D::z().
height
size_t height = {}
Height of the 3D shape or object.
Definition at line 93 of file Size3D.h.
Referenced by arm_compute::misc::shape_calculator::compute_conv3d_shape(), arm_compute::cpu::directconv3d_float_neon_ndhwc(), arm_compute::cpu::directconv3d_quantized_neon_ndhwc(), arm_compute::operator<<(), Size3D::operator==(), Size3D::to_string(), and Size3D::y().
width
size_t width = {}
Width of the 3D shape or object.
Definition at line 92 of file Size3D.h.
Referenced by arm_compute::misc::shape_calculator::compute_conv3d_shape(), arm_compute::cpu::directconv3d_float_neon_ndhwc(), arm_compute::cpu::directconv3d_quantized_neon_ndhwc(), arm_compute::operator<<(), Size3D::operator==(), Size3D::to_string(), and Size3D::x().
The documentation for this class was generated from the following files:
arm_compute/core/Size3D.h
src/core/Size3D.cpp