Compute Library: ClGemmLowpOutputStage Class Reference
ClGemmLowpOutputStage Class Reference
Basic function to execute GEMMLowpQuantizeDown kernels on CL.
#include <ClGemmLowpOutputStage.h>
Public Member Functions
ClGemmLowpOutputStage ()=default
Constructor.
void configure (const CLCompileContext &compile_context, const ITensorInfo *src, const ITensorInfo *bias, ITensorInfo *dst, const GEMMLowpOutputStageInfo &info)
Initialise the kernel's inputs, output.
void run (ITensorPack &tensors) override
Run the kernels contained in the function.
Public Member Functions inherited from ICLOperator
ICLOperator (IRuntimeContext *ctx=nullptr)
Constructor.
ICLOperator (const ICLOperator &)=delete
Prevent instances of this class from being copied (As this class contains pointers)
ICLOperator (ICLOperator &&)=default
Default move constructor.
ICLOperator & operator= (const ICLOperator &)=delete
Prevent instances of this class from being copied (As this class contains pointers)
ICLOperator & operator= (ICLOperator &&)=default
Default move assignment operator.
void prepare (ITensorPack &constants) override
Prepare the function for executing.
MemoryRequirements workspace () const override
Return the memory requirements required by the workspace.
Public Member Functions inherited from IOperator
virtual ~IOperator ()=default
Destructor.
Static Public Member Functions
static Status validate (const ITensorInfo *src, const ITensorInfo *bias, const ITensorInfo *dst, const GEMMLowpOutputStageInfo &info)
Static function to check if given info will lead to a valid configuration.
Detailed Description
Basic function to execute GEMMLowpQuantizeDown kernels on CL.
This function calls the following CL kernels:
opencl::kernels::ClGemmLowpQuantizeDownInt32ScaleKernel
opencl::kernels::ClGemmLowpQuantizeDownInt32ScaleByFloatKernel
opencl::kernels::ClGemmLowpQuantizeDownInt32ScaleByFixedPointKernel
Definition at line 50 of file ClGemmLowpOutputStage.h.
Constructor & Destructor Documentation
ClGemmLowpOutputStage()
ClGemmLowpOutputStage () default
Constructor.
Member Function Documentation
configure()
void configure (const CLCompileContext & compile_context, const ITensorInfo * src, const ITensorInfo * bias, ITensorInfo * dst, const GEMMLowpOutputStageInfo & info)
Initialise the kernel's inputs, output.
Valid data layouts:
All
Valid data type configurations:
src0 src1 dst
S32 S32 QASYMM8
S32 S32 QASYMM8_SIGNED
S32 S32 QSYMM16
Parameters
[in] compile_context The compile context to be used.
[in] src Source tensor. Data type supported: S32
[in] bias Biases tensor. Only shared biases supported and it can be a nullptr if the biases addition is not required. Biases are 1D tensor with dimensions [OFM]. Data type supported: Same as src.
[out] dst Destination tensor. Data type supported: QASYMM8/QASYMM8_SIGNED
[in] info GEMMLowp output stage metadata.
Definition at line 40 of file ClGemmLowpOutputStage.cpp.
References ARM_COMPUTE_ERROR, ARM_COMPUTE_ERROR_ON_NULLPTR, ARM_COMPUTE_LOG_PARAMS, arm_compute::test::validation::k, arm_compute::QUANTIZE_DOWN, arm_compute::QUANTIZE_DOWN_FIXEDPOINT, arm_compute::QUANTIZE_DOWN_FLOAT, and GEMMLowpOutputStageInfo::type.
 {
     ARM_COMPUTE_ERROR_ON_NULLPTR(src, dst);
     ARM_COMPUTE_LOG_PARAMS(src, bias, dst, info);
     switch(info.type)
     {
         case GEMMLowpOutputStageType::QUANTIZE_DOWN_FIXEDPOINT:
         {
             auto k = std::make_unique<opencl::kernels::ClGemmLowpQuantizeDownInt32ScaleByFixedPointKernel>();
             k->configure(compile_context, src, bias, dst, &info);
             _kernel = std::move(k);
             break;
         }
         case GEMMLowpOutputStageType::QUANTIZE_DOWN:
         {
             auto k = std::make_unique<opencl::kernels::ClGemmLowpQuantizeDownInt32ScaleKernel>();
             k->configure(compile_context, src, bias, dst, &info);
             _kernel = std::move(k);
             break;
         }
         case GEMMLowpOutputStageType::QUANTIZE_DOWN_FLOAT:
         {
             auto k = std::make_unique<opencl::kernels::ClGemmLowpQuantizeDownInt32ScaleByFloatKernel>();
             k->configure(compile_context, src, bias, dst, &info);
             _kernel = std::move(k);
             break;
         }
         default:
             ARM_COMPUTE_ERROR("Unsupported GEMMLowpOutputStage type.");
     }
 }
run()
void run (ITensorPack & tensors) override virtual
Run the kernels contained in the function.
Parameters
[in] tensors Vector that contains the tensors to operate on.
Reimplemented from ICLOperator.
Definition at line 91 of file ClGemmLowpOutputStage.cpp.
References arm_compute::ACL_BIAS, arm_compute::ACL_DST, arm_compute::ACL_SRC, arm_compute::test::validation::dst, CLScheduler::enqueue_op(), CLScheduler::get(), ITensorPack::get_const_tensor(), ITensorPack::get_tensor(), arm_compute::test::validation::pack, and arm_compute::test::validation::src.
 {
     const ITensor *src  = tensors.get_const_tensor(ACL_SRC);
     const ITensor *bias = tensors.get_const_tensor(ACL_BIAS);
     ITensor       *dst  = tensors.get_tensor(ACL_DST);
     ITensorPack pack{ { ACL_SRC, src }, { ACL_BIAS, bias }, { ACL_DST, dst } };
     CLScheduler::get().enqueue_op(*_kernel, pack, true);
 }
validate()
Status validate (const ITensorInfo * src, const ITensorInfo * bias, const ITensorInfo * dst, const GEMMLowpOutputStageInfo & info) static
Static function to check if given info will lead to a valid configuration.
Similar to ClGemmLowpOutputStage::configure()
Returns
a status
Definition at line 73 of file ClGemmLowpOutputStage.cpp.
References ARM_COMPUTE_CREATE_ERROR, ARM_COMPUTE_RETURN_ERROR_ON_DATA_TYPE_CHANNEL_NOT_IN, ARM_COMPUTE_RETURN_ERROR_ON_NULLPTR, arm_compute::QASYMM8, arm_compute::QASYMM8_SIGNED, arm_compute::QSYMM16, arm_compute::QUANTIZE_DOWN, arm_compute::QUANTIZE_DOWN_FIXEDPOINT, arm_compute::QUANTIZE_DOWN_FLOAT, arm_compute::RUNTIME_ERROR, GEMMLowpOutputStageInfo::type, ClGemmLowpQuantizeDownInt32ScaleByFixedPointKernel::validate(), ClGemmLowpQuantizeDownInt32ScaleByFloatKernel::validate(), and ClGemmLowpQuantizeDownInt32ScaleKernel::validate().
Referenced by CLGEMMLowpOutputStage::validate().
 {
     ARM_COMPUTE_RETURN_ERROR_ON_NULLPTR(dst);
     ARM_COMPUTE_RETURN_ERROR_ON_DATA_TYPE_CHANNEL_NOT_IN(dst, 1, DataType::QASYMM8, DataType::QASYMM8_SIGNED, DataType::QSYMM16);
     switch(info.type)
     {
         case GEMMLowpOutputStageType::QUANTIZE_DOWN_FIXEDPOINT:
             return opencl::kernels::ClGemmLowpQuantizeDownInt32ScaleByFixedPointKernel::validate(src, bias, dst, &info);
         case GEMMLowpOutputStageType::QUANTIZE_DOWN:
             return opencl::kernels::ClGemmLowpQuantizeDownInt32ScaleKernel::validate(src, bias, dst, &info);
         case GEMMLowpOutputStageType::QUANTIZE_DOWN_FLOAT:
             return opencl::kernels::ClGemmLowpQuantizeDownInt32ScaleByFloatKernel::validate(src, bias, dst, &info);
         default:
             return ARM_COMPUTE_CREATE_ERROR(ErrorCode::RUNTIME_ERROR, "Unsupported GEMMLowpOutputStage type.");
     }
 }
The documentation for this class was generated from the following files:
src/gpu/cl/operators/ClGemmLowpOutputStage.h
src/gpu/cl/operators/ClGemmLowpOutputStage.cpp