Compute Library: ClPermute Class Reference
ClPermute Class Reference
Basic function to run kernels::ClPermuteKernel.
#include <ClPermute.h>
Public Member Functions
void configure (const CLCompileContext &compile_context, const ITensorInfo *src, ITensorInfo *dst, const PermutationVector &perm)
Initialise the kernel's inputs and outputs and permute vector.
Public Member Functions inherited from ICLOperator
ICLOperator (IRuntimeContext *ctx=nullptr)
Constructor.
ICLOperator (const ICLOperator &)=delete
Prevent instances of this class from being copied (As this class contains pointers)
ICLOperator (ICLOperator &&)=default
Default move constructor.
ICLOperator & operator= (const ICLOperator &)=delete
Prevent instances of this class from being copied (As this class contains pointers)
ICLOperator & operator= (ICLOperator &&)=default
Default move assignment operator.
void run (ITensorPack &tensors) override
Run the kernels contained in the function.
void prepare (ITensorPack &constants) override
Prepare the function for executing.
MemoryRequirements workspace () const override
Return the memory requirements required by the workspace.
Public Member Functions inherited from IOperator
virtual ~IOperator ()=default
Destructor.
Static Public Member Functions
static Status validate (const ITensorInfo *src, const ITensorInfo *dst, const PermutationVector &perm)
Static function to check if given info will lead to a valid configuration.
Detailed Description
Basic function to run kernels::ClPermuteKernel.
Definition at line 35 of file ClPermute.h.
Member Function Documentation
configure()
void configure (const CLCompileContext & compile_context, const ITensorInfo * src, ITensorInfo * dst, const PermutationVector & perm)
Initialise the kernel's inputs and outputs and permute vector.
Note
Arbitrary permutation vectors are supported with rank not greater than 4
Parameters
[in] compile_context The compile context to be used.
[in] src The src tensor info. Data types supported: All.
[in] dst The dst tensor info. Data types supported: Same as src
[in] perm Permutation vector
Definition at line 35 of file ClPermute.cpp.
References ARM_COMPUTE_LOG_PARAMS, and arm_compute::test::validation::k.
 {
     ARM_COMPUTE_LOG_PARAMS(src, dst, perm);
     auto k = std::make_unique<kernels::ClPermuteKernel>();
     k->configure(compile_context, src, dst, perm);
     _kernel = std::move(k);
 }
validate()
Status validate (const ITensorInfo * src, const ITensorInfo * dst, const PermutationVector & perm) static
Static function to check if given info will lead to a valid configuration.
Similar to ClPermute::configure()
Returns
a status
Definition at line 43 of file ClPermute.cpp.
References ClPermuteKernel::validate().
Referenced by ClSoftmax::validate(), and CLPermute::validate().
 {
     return kernels::ClPermuteKernel::validate(src, dst, perm);
 }
The documentation for this class was generated from the following files:
src/gpu/cl/operators/ClPermute.h
src/gpu/cl/operators/ClPermute.cpp