Compute Library: CLCompileContext Class Reference
CLCompileContext Class Reference final
CLCompileContext class.
#include <CLCompileContext.h>
Public Member Functions
CLCompileContext ()
Constructor.
CLCompileContext (cl::Context context, const cl::Device &device)
Constructor.
cl::Context & context ()
Accessor for the associated CL context.
void set_context (cl::Context context)
Sets the CL context used to create programs.
const cl::Device & get_device () const
Gets the CL device for which the programs are created.
void set_device (cl::Device device)
Sets the CL device for which the programs are created.
Kernel create_kernel (const std::string &kernel_name, const std::string &program_name, const std::string &program_source, const std::string &kernel_path, const StringSet &build_options_set, bool is_binary) const
Creates an OpenCL kernel.
void clear_programs_cache ()
Clear the library's cache of binary programs.
const std::map< std::string, cl::Program > & get_built_programs () const
Access the cache of built OpenCL programs.
void add_built_program (const std::string &built_program_name, const cl::Program &program) const
Add a new built program to the cache.
bool fp16_supported () const
Returns true if FP16 is supported by the CL device.
cl_uint get_num_compute_units () const
Return the maximum number of compute units in the device.
size_t max_local_workgroup_size (const cl::Kernel &kernel) const
Find the maximum number of local work items in a workgroup can be supported for the kernel.
cl::NDRange default_ndrange () const
Return the default NDRange for the device.
std::string get_device_version () const
Return the device version.
bool int64_base_atomics_supported () const
Returns true if int64_base_atomics extension is supported by the CL device.
bool is_wbsm_supported () const
Detailed Description
CLCompileContext class.
Definition at line 202 of file CLCompileContext.h.
Constructor & Destructor Documentation
CLCompileContext() [1/2]
CLCompileContext ()
Constructor.
Definition at line 141 of file CLCompileContext.cpp.
     : _context(), _device(), _programs_map(), _built_programs_map(), _is_wbsm_supported()
 {
 }
CLCompileContext() [2/2]
CLCompileContext (cl::Context context, const cl::Device & device)
Constructor.
Parameters
[in] context A CL context.
[in] device A CL device.
Definition at line 146 of file CLCompileContext.cpp.
References arm_compute::get_wbsm_support_info().
     : _context(), _device(), _programs_map(), _built_programs_map(), _is_wbsm_supported()
 {
     _context           = std::move(context);
     _device            = CLDevice(device);
     _is_wbsm_supported = get_wbsm_support_info(device);
 }
Member Function Documentation
add_built_program()
void add_built_program (const std::string & built_program_name, const cl::Program & program) const
Add a new built program to the cache.
Parameters
[in] built_program_name Name of the program
[in] program Built program to add to the cache
Definition at line 308 of file CLCompileContext.cpp.
Referenced by CLKernelLibrary::add_built_program().
 {
     _built_programs_map.emplace(built_program_name, program);
 }
clear_programs_cache()
void clear_programs_cache ()
Clear the library's cache of binary programs.
Definition at line 313 of file CLCompileContext.cpp.
Referenced by CLKernelLibrary::clear_programs_cache().
 {
     _programs_map.clear();
     _built_programs_map.clear();
 }
context()
cl::Context & context ()
Accessor for the associated CL context.
Returns
A CL context.
Definition at line 324 of file CLCompileContext.cpp.
Referenced by CLKernelLibrary::context().
 {
     return _context;
 }
create_kernel()
Kernel create_kernel (const std::string & kernel_name, const std::string & program_name, const std::string & program_source, const std::string & kernel_path, const StringSet & build_options_set, bool is_binary) const
Creates an OpenCL kernel.
Parameters
[in] kernel_name Kernel name.
[in] program_name Program name.
[in] program_source Program source.
[in] kernel_path CL kernel path.
[in] build_options_set Kernel build options as a set.
[in] is_binary Flag to indicate if the program source is binary.
Returns
The created kernel.
Definition at line 154 of file CLCompileContext.cpp.
References ARM_COMPUTE_UNUSED, Program::build(), build_options, and CLDevice::cl_device().
Referenced by CLKernelLibrary::create_kernel(), arm_compute::create_kernel(), and arm_compute::test::validation::TEST_CASE().
 {
     const std::string build_options      = generate_build_options(build_options_set, kernel_path);
     const std::string built_program_name = program_name + "_" + build_options;
     auto              built_program_it   = _built_programs_map.find(built_program_name);
     cl::Program       cl_program;
     if(_built_programs_map.end() != built_program_it)
     {
         // If program has been built, retrieve to create kernel from it
         cl_program = built_program_it->second;
     }
     else
     {
         Program program = load_program(program_name, program_source, is_binary);
         // Build program
         cl_program = program.build(build_options);
         // Add built program to internal map
         _built_programs_map.emplace(built_program_name, cl_program);
     }
     // Create and return kernel
     return Kernel(kernel_name, cl_program);
 }
default_ndrange()
cl::NDRange default_ndrange () const
Return the default NDRange for the device.
Definition at line 340 of file CLCompileContext.cpp.
References CLDevice::cl_device(), arm_compute::get_target_from_device(), arm_compute::MIDGARD, arm_compute::T600, arm_compute::T700, and arm_compute::T800.
Referenced by CLKernelLibrary::default_ndrange().
 {
     GPUTarget   _target = get_target_from_device(_device.cl_device());
     cl::NDRange default_range;
     switch(_target)
     {
         case GPUTarget::MIDGARD:
         case GPUTarget::T600:
         case GPUTarget::T700:
         case GPUTarget::T800:
             default_range = cl::NDRange(128u, 1);
             break;
         default:
             default_range = cl::NullRange;
     }
     return default_range;
 }
fp16_supported()
bool fp16_supported () const
Returns true if FP16 is supported by the CL device.
Returns
true if the CL device supports FP16
Definition at line 285 of file CLCompileContext.cpp.
References ARM_COMPUTE_UNUSED, and CLDevice::supported().
Referenced by CLKernelLibrary::fp16_supported().
 {
     return _device.supported("cl_khr_fp16");
 }
get_built_programs()
const std::map< std::string, cl::Program > & get_built_programs () const
Access the cache of built OpenCL programs.
Definition at line 319 of file CLCompileContext.cpp.
Referenced by CLKernelLibrary::get_built_programs(), and arm_compute::test::validation::TEST_CASE().
 {
     return _built_programs_map;
 }
get_device()
const cl::Device & get_device () const
Gets the CL device for which the programs are created.
Definition at line 329 of file CLCompileContext.cpp.
References CLDevice::cl_device().
Referenced by CLKernelLibrary::get_device().
 {
     return _device.cl_device();
 }
get_device_version()
std::string get_device_version () const
Return the device version.
Returns
The content of CL_DEVICE_VERSION
Definition at line 381 of file CLCompileContext.cpp.
References CLDevice::device_version().
Referenced by CLKernelLibrary::get_device_version().
 {
     return _device.device_version();
 }
get_num_compute_units()
cl_uint get_num_compute_units () const
Return the maximum number of compute units in the device.
Returns
The content of CL_DEVICE_MAX_COMPUTE_UNITS
Definition at line 386 of file CLCompileContext.cpp.
References CLDevice::compute_units().
Referenced by CLKernelLibrary::get_num_compute_units().
 {
     return _device.compute_units();
 }
int64_base_atomics_supported()
bool int64_base_atomics_supported () const
Returns true if int64_base_atomics extension is supported by the CL device.
Returns
true if the CL device supports int64_base_atomics extension
Definition at line 360 of file CLCompileContext.cpp.
References CLDevice::supported().
Referenced by CLKernelLibrary::int64_base_atomics_supported().
 {
     return _device.supported("cl_khr_int64_base_atomics");
 }
is_wbsm_supported()
bool is_wbsm_supported () const
Definition at line 365 of file CLCompileContext.cpp.
Referenced by CLKernelLibrary::is_wbsm_supported().
 {
     return _is_wbsm_supported;
 }
max_local_workgroup_size()
size_t max_local_workgroup_size (const cl::Kernel & kernel) const
Find the maximum number of local work items in a workgroup can be supported for the kernel.
Definition at line 370 of file CLCompileContext.cpp.
References ARM_COMPUTE_ERROR_ON_MSG, ARM_COMPUTE_UNUSED, and CLDevice::cl_device().
Referenced by CLKernelLibrary::max_local_workgroup_size().
 {
     size_t result;
     size_t err = kernel.getWorkGroupInfo(_device.cl_device(), CL_KERNEL_WORK_GROUP_SIZE, &result);
     ARM_COMPUTE_ERROR_ON_MSG(err != 0, "clGetKernelWorkGroupInfo failed to return the maximum workgroup size for the kernel");
     ARM_COMPUTE_UNUSED(err);
     return result;
 }
set_context()
void set_context (cl::Context context)
Sets the CL context used to create programs.
Note
Setting the context also resets the device to the first one available in the new context.
Parameters
[in] context A CL context.
Definition at line 213 of file CLCompileContext.cpp.
References ARM_COMPUTE_ERROR, build_options, arm_compute::CL20, CLDevice::device_version(), arm_compute::get_arch_from_target(), arm_compute::MIDGARD, arm_compute::support::cpp11::stoi(), CLDevice::supported(), CLDevice::target(), arm_compute::support::cpp11::to_string(), type, arm_compute::UNKNOWN, and CLDevice::version().
Referenced by CLKernelLibrary::set_context().
 {
     _context = std::move(context);
     if(_context.get() != nullptr)
     {
         const auto cl_devices = _context.getInfo<CL_CONTEXT_DEVICES>();
         if(!cl_devices.empty())
         {
             _device = CLDevice(cl_devices[0]);
         }
     }
 }
set_device()
void set_device (cl::Device device)
Sets the CL device for which the programs are created.
Parameters
[in] device A CL device.
Definition at line 334 of file CLCompileContext.cpp.
References arm_compute::get_wbsm_support_info().
Referenced by CLKernelLibrary::set_device().
 {
     _device            = std::move(device);
     _is_wbsm_supported = get_wbsm_support_info(device);
 }
The documentation for this class was generated from the following files:
arm_compute/core/CL/CLCompileContext.h
src/core/CL/CLCompileContext.cpp