Compute Library: NESelectKernel Class Reference
NESelectKernel Class Reference
Interface for the select kernel.
#include <NESelectKernel.h>
Public Member Functions
const char * name () const override
Name of the kernel.
NESelectKernel ()
Default constructor.
NESelectKernel (const NESelectKernel &)=delete
Prevent instances of this class from being copied (As this class contains pointers)
NESelectKernel & operator= (const NESelectKernel &)=delete
Prevent instances of this class from being copied (As this class contains pointers)
NESelectKernel (NESelectKernel &&)=default
Allow instances of this class to be moved.
NESelectKernel & operator= (NESelectKernel &&)=default
Allow instances of this class to be moved.
~NESelectKernel ()=default
Default destructor.
void configure (const ITensor *c, const ITensor *x, const ITensor *y, ITensor *output)
Common signature for all the specialised elementwise functions.
void run (const Window &window, const ThreadInfo &info) override
Execute the kernel on the passed window.
Public Member Functions inherited from ICPPKernel
virtual ~ICPPKernel ()=default
Default destructor.
virtual void run_nd (const Window &window, const ThreadInfo &info, const Window &thread_locator)
legacy compatibility layer for implemantions which do not support thread_locator In these cases we simply narrow the interface down the legacy version
virtual void run_op (ITensorPack &tensors, const Window &window, const ThreadInfo &info)
Execute the kernel on the passed window.
virtual size_t get_mws (const CPUInfo &platform, size_t thread_count) const
Return minimum workload size of the relevant kernel.
Public Member Functions inherited from IKernel
IKernel ()
Constructor.
virtual ~IKernel ()=default
Destructor.
virtual bool is_parallelisable () const
Indicates whether or not the kernel is parallelisable.
virtual BorderSize border_size () const
The size of the border for that kernel.
const Window & window () const
The maximum window the kernel can be executed on.
bool is_window_configured () const
Function to check if the embedded window of this kernel has been configured.
Static Public Member Functions
static Status validate (const ITensorInfo *c, const ITensorInfo *x, const ITensorInfo *y, const ITensorInfo *output)
Validate the argument passed to the kernel.
Additional Inherited Members
Static Public Attributes inherited from ICPPKernel
static constexpr size_t default_mws = 1
Detailed Description
Interface for the select kernel.
Select is computed by:
\[ output(i) = condition(i) ? x(i) : y(i) \]
Definition at line 41 of file NESelectKernel.h.
Constructor & Destructor Documentation
NESelectKernel() [1/3]
NESelectKernel ()
Default constructor.
Definition at line 164 of file NESelectKernel.cpp.
Referenced by NESelectKernel::name().
     : /*_function(nullptr), */ _c(nullptr), _x(nullptr), _y(nullptr), _output(nullptr), _has_same_rank(false)
 {
 }
NESelectKernel() [2/3]
NESelectKernel (const NESelectKernel &) delete
Prevent instances of this class from being copied (As this class contains pointers)
NESelectKernel() [3/3]
NESelectKernel (NESelectKernel &&) default
Allow instances of this class to be moved.
~NESelectKernel()
~NESelectKernel () default
Default destructor.
Referenced by NESelectKernel::name().
Member Function Documentation
configure()
void configure (const ITensor * c, const ITensor * x, const ITensor * y, ITensor * output)
Common signature for all the specialised elementwise functions.
Parameters
[in] c Condition input tensor. Data types supported: U8.
[in] x First input tensor. Data types supported: All.
[out] y Second input tensor. Data types supported: Same as x
[in] output Output tensor. Data types supported: Same as x
Definition at line 169 of file NESelectKernel.cpp.
References ARM_COMPUTE_ERROR_ON_NULLPTR, ARM_COMPUTE_ERROR_THROW_ON, arm_compute::auto_init_if_empty(), arm_compute::calculate_max_window(), ITensorInfo::data_type(), ITensor::info(), Dimensions< T >::num_dimensions(), ITensorInfo::tensor_shape(), and NESelectKernel::validate().
Referenced by NESelectKernel::name().
 {
     ARM_COMPUTE_ERROR_ON_NULLPTR(c, x, y, output);
     // Auto initialize output if not initialized
     auto_init_if_empty(*output->info(), x->info()->tensor_shape(), 1, x->info()->data_type());
     ARM_COMPUTE_ERROR_THROW_ON(validate(c->info(), x->info(), y->info(), output->info()));
     _c             = c;
     _x             = x;
     _y             = y;
     _output        = output;
     _has_same_rank = (c->info()->tensor_shape().num_dimensions() == x->info()->tensor_shape().num_dimensions());
     Window win = calculate_max_window(*x->info());
     INEKernel::configure(win);
 }
name()
const char* name () const inline override virtual
Name of the kernel.
Returns
Kernel name
Implements ICPPKernel.
Definition at line 44 of file NESelectKernel.h.
References NESelectKernel::configure(), arm_compute::test::validation::info, NESelectKernel::NESelectKernel(), NESelectKernel::operator=(), NESelectKernel::run(), NESelectKernel::validate(), IKernel::window(), and NESelectKernel::~NESelectKernel().
     {
         return "NESelectKernel";
     }
operator=() [1/2]
NESelectKernel& operator= (const NESelectKernel &) delete
Prevent instances of this class from being copied (As this class contains pointers)
Referenced by NESelectKernel::name().
operator=() [2/2]
NESelectKernel& operator= (NESelectKernel &&) default
Allow instances of this class to be moved.
run()
void run (const Window & window, const ThreadInfo & info) override virtual
Execute the kernel on the passed window.
Warning
If is_parallelisable() returns false then the passed window must be equal to window()
Note
The window has to be a region within the window returned by the window() method
The width of the window has to be a multiple of num_elems_processed_per_iteration().
Parameters
[in] window Region on which to execute the kernel. (Must be a region of the window returned by window())
[in] info Info about executing thread and CPU.
Reimplemented from ICPPKernel.
Definition at line 209 of file NESelectKernel.cpp.
References ARM_COMPUTE_ERROR_ON, ARM_COMPUTE_ERROR_ON_INVALID_SUBWINDOW, ARM_COMPUTE_ERROR_ON_UNCONFIGURED_KERNEL, ARM_COMPUTE_UNUSED, ITensorInfo::data_type(), ITensor::info(), and IKernel::window().
Referenced by NESelectKernel::name().
 {
     ARM_COMPUTE_UNUSED(info);
     ARM_COMPUTE_ERROR_ON_UNCONFIGURED_KERNEL(this);
     ARM_COMPUTE_ERROR_ON_INVALID_SUBWINDOW(INEKernel::window(), window);
     ARM_COMPUTE_ERROR_ON(_output == nullptr);
     ARM_COMPUTE_ERROR_ON(_output->info() == nullptr);
     const auto *uk = get_implementation(SelectKernelSelectorData{ _output->info()->data_type(), _has_same_rank });
     ARM_COMPUTE_ERROR_ON(uk == nullptr);
     ARM_COMPUTE_ERROR_ON(uk->ukernel == nullptr);
     uk->ukernel(_c, _x, _y, _output, window);
 }
validate()
Status validate (const ITensorInfo * c, const ITensorInfo * x, const ITensorInfo * y, const ITensorInfo * output) static
Validate the argument passed to the kernel.
Parameters
[in] c Condition input tensor. Data types supported: U8.
[in] x First input tensor. Data types supported: All.
[in] y Second input tensor. Data types supported: Same as x
[in] output Output tensor. Data types supported: Same as x.
Returns
a status
Definition at line 187 of file NESelectKernel.cpp.
References ARM_COMPUTE_RETURN_ERROR_ON, ARM_COMPUTE_RETURN_ERROR_ON_CPU_F16_UNSUPPORTED, ARM_COMPUTE_RETURN_ERROR_ON_DATA_TYPE_CHANNEL_NOT_IN, ARM_COMPUTE_RETURN_ERROR_ON_MISMATCHING_DATA_TYPES, ARM_COMPUTE_RETURN_ERROR_ON_MISMATCHING_SHAPES, ARM_COMPUTE_RETURN_ERROR_ON_NULLPTR, ITensorInfo::data_type(), is_same_rank, Dimensions< T >::num_dimensions(), ITensorInfo::tensor_shape(), ITensorInfo::total_size(), arm_compute::U8, arm_compute::UNKNOWN, and Dimensions< T >::x().
Referenced by NESelectKernel::configure(), NESelectKernel::name(), and NESelect::validate().
 {
     ARM_COMPUTE_RETURN_ERROR_ON_NULLPTR(c, x, y);
     ARM_COMPUTE_RETURN_ERROR_ON_CPU_F16_UNSUPPORTED(x);
     ARM_COMPUTE_RETURN_ERROR_ON(x->data_type() == DataType::UNKNOWN);
     ARM_COMPUTE_RETURN_ERROR_ON_MISMATCHING_SHAPES(x, y);
     ARM_COMPUTE_RETURN_ERROR_ON_MISMATCHING_DATA_TYPES(x, y);
     ARM_COMPUTE_RETURN_ERROR_ON_DATA_TYPE_CHANNEL_NOT_IN(c, 1, DataType::U8);
     const bool is_same_rank = (c->tensor_shape().num_dimensions() == x->tensor_shape().num_dimensions());
     ARM_COMPUTE_RETURN_ERROR_ON(is_same_rank && (x->tensor_shape() != c->tensor_shape()));
     ARM_COMPUTE_RETURN_ERROR_ON(!is_same_rank && ((c->tensor_shape().num_dimensions() > 1) || (c->tensor_shape().x() != x->tensor_shape()[x->tensor_shape().num_dimensions() - 1])));
     if(output != nullptr && output->total_size() != 0)
     {
         ARM_COMPUTE_RETURN_ERROR_ON_MISMATCHING_SHAPES(x, output);
         ARM_COMPUTE_RETURN_ERROR_ON_MISMATCHING_DATA_TYPES(x, output);
     }
     return Status{};
 }
The documentation for this class was generated from the following files:
src/core/NEON/kernels/NESelectKernel.h
src/core/NEON/kernels/NESelectKernel.cpp