Compute Library: CLSlice Class Reference
CLSlice Class Reference
Basic function to perform tensor slicing.
#include <CLSlice.h>
Public Member Functions
void configure (const CLCompileContext &compile_context, const ITensorInfo *input, ITensorInfo *output, const Coordinates &starts, const Coordinates &ends)
Configure kernel.
Public Member Functions inherited from ICLOperator
ICLOperator (IRuntimeContext *ctx=nullptr)
Constructor.
ICLOperator (const ICLOperator &)=delete
Prevent instances of this class from being copied (As this class contains pointers)
ICLOperator (ICLOperator &&)=default
Default move constructor.
ICLOperator & operator= (const ICLOperator &)=delete
Prevent instances of this class from being copied (As this class contains pointers)
ICLOperator & operator= (ICLOperator &&)=default
Default move assignment operator.
void run (ITensorPack &tensors) override
Run the kernels contained in the function.
void prepare (ITensorPack &constants) override
Prepare the function for executing.
MemoryRequirements workspace () const override
Return the memory requirements required by the workspace.
Public Member Functions inherited from IOperator
virtual ~IOperator ()=default
Destructor.
Static Public Member Functions
static Status validate (const ITensorInfo *input, const ITensorInfo *output, const Coordinates &starts, const Coordinates &ends)
Static function to check if given info will lead to a valid configuration of CLSlice.
Detailed Description
Basic function to perform tensor slicing.
Definition at line 116 of file CLSlice.h.
Member Function Documentation
configure()
void configure (const CLCompileContext & compile_context, const ITensorInfo * input, ITensorInfo * output, const Coordinates & starts, const Coordinates & ends)
Configure kernel.
Note
Supported tensor rank: up to 4
Start indices must be non-negative. 0 <= starts[i]
End coordinates can be negative, which represents the number of elements before the end of that dimension.
End indices are not inclusive unless negative.
Parameters
[in] compile_context The compile context to be used.
[in] input Source tensor info. Data type supported: All.
[out] output Destination tensor info. Data type supported: Same as input
[in] starts The starts of the dimensions of the input tensor to be sliced. The length must be of rank(input).
[in] ends The ends of the dimensions of the input tensor to be sliced. The length must be of rank(input).
Definition at line 37 of file CLSlice.cpp.
References ARM_COMPUTE_ERROR_ON_NULLPTR, ARM_COMPUTE_LOG_PARAMS, arm_compute::helpers::tensor_transform::construct_slice_end_mask(), and arm_compute::test::validation::k.
 {
     ARM_COMPUTE_ERROR_ON_NULLPTR(input);
     ARM_COMPUTE_LOG_PARAMS(input, output, starts, ends);
     // Get absolute end coordinates
     const int32_t slice_end_mask = arm_compute::helpers::tensor_transform::construct_slice_end_mask(ends);
     auto k = std::make_unique<CLStridedSliceKernel>();
     k->configure(compile_context, input, output, starts, ends, BiStrides(), 0, slice_end_mask, 0);
     _kernel = std::move(k);
 }
validate()
Status validate (const ITensorInfo * input, const ITensorInfo * output, const Coordinates & starts, const Coordinates & ends) static
Static function to check if given info will lead to a valid configuration of CLSlice.
Note
Supported tensor rank: up to 4
Start indices must be non-negative. 0 <= starts[i]
End coordinates can be negative, which represents the number of elements before the end of that dimension.
End indices are not inclusive unless negative.
Parameters
[in] input Source tensor info. Data type supported: All
[in] output Destination tensor info. Data type supported: Same as input
[in] starts The starts of the dimensions of the input tensor to be sliced. The length must be of rank(input).
[in] ends The ends of the dimensions of the input tensor to be sliced. The length must be of rank(input).
Returns
A status
Definition at line 50 of file CLSlice.cpp.
References ARM_COMPUTE_RETURN_ERROR_ON, ARM_COMPUTE_RETURN_ERROR_ON_NULLPTR, Dimensions< T >::cbegin(), arm_compute::helpers::tensor_transform::construct_slice_end_mask(), arm_compute::test::validation::dst, Dimensions< T >::num_dimensions(), arm_compute::test::validation::src, and CLStridedSliceKernel::validate().
Referenced by CLSlice::validate().
 {
     ARM_COMPUTE_RETURN_ERROR_ON_NULLPTR(input);
     // Check start dimensions for being non-negative
     ARM_COMPUTE_RETURN_ERROR_ON(std::any_of(starts.cbegin(), starts.cbegin() + starts.num_dimensions(), [](int i)
     {
         return i < 0;
     }));
     // Get absolute end coordinates
     const int32_t slice_end_mask = arm_compute::helpers::tensor_transform::construct_slice_end_mask(ends);
     return CLStridedSliceKernel::validate(input, output, starts, ends, BiStrides(), 0, slice_end_mask, 0);
 }
The documentation for this class was generated from the following files:
arm_compute/runtime/CL/functions/CLSlice.h
src/runtime/CL/functions/CLSlice.cpp