Compute Library: NEPadLayer Class Reference
NEPadLayer Class Reference
Basic function to pad a tensor.
#include <NEPadLayer.h>
Public Member Functions
NEPadLayer ()
Default Constructor.
NEPadLayer (const NEPadLayer &)=delete
Prevent instances of this class from being copied (As this class contains pointers)
NEPadLayer & operator= (const NEPadLayer &)=delete
Prevent instances of this class from being copied (As this class contains pointers)
NEPadLayer (NEPadLayer &&)=delete
Prevent instances of this class from being moved (As this class contains non movable objects)
NEPadLayer & operator= (NEPadLayer &&)=delete
Prevent instances of this class from being moved (As this class contains non movable objects)
~NEPadLayer ()
Default destructor.
void configure (ITensor *input, ITensor *output, const PaddingList &padding, const PixelValue constant_value=PixelValue(), const PaddingMode mode=PaddingMode::CONSTANT)
Initialize the function.
void run () override
Run the kernels contained in the function.
Public Member Functions inherited from IFunction
virtual ~IFunction ()=default
Destructor.
virtual void prepare ()
Prepare the function for executing.
Static Public Member Functions
static Status validate (const ITensorInfo *input, const ITensorInfo *output, const PaddingList &padding, const PixelValue constant_value=PixelValue(), const PaddingMode mode=PaddingMode::CONSTANT)
Static function to check if given info will lead to a valid configuration of NEPadLayer.
Detailed Description
Basic function to pad a tensor.
This function calls the following functions/kernels:
For padding mode = PaddingMode::CONSTANT:
NEPadLayerKernel
Otherwise:
NECopy
NEStridedSlice
NEConcatenateLayer
Definition at line 51 of file NEPadLayer.h.
Constructor & Destructor Documentation
NEPadLayer() [1/3]
NEPadLayer ()
Default Constructor.
Definition at line 54 of file NEPadLayer.cpp.
References arm_compute::CONSTANT, ITensorInfo::dimension(), ITensor::info(), arm_compute::test::validation::info, arm_compute::test::validation::input, ITensorInfo::quantization_info(), arm_compute::REFLECT, and ITensorInfo::set_quantization_info().
     : _copy_function(), _pad_kernel(), _mode(), _padding(), _num_dimensions(0), _slice_functions(), _concat_functions(), _slice_results(), _concat_results()
 {
 }
NEPadLayer() [2/3]
NEPadLayer (const NEPadLayer &) delete
Prevent instances of this class from being copied (As this class contains pointers)
NEPadLayer() [3/3]
NEPadLayer (NEPadLayer &&) delete
Prevent instances of this class from being moved (As this class contains non movable objects)
~NEPadLayer()
~NEPadLayer () default
Default destructor.
Member Function Documentation
configure()
void configure (ITensor * input, ITensor * output, const PaddingList & padding, const PixelValue constant_value = PixelValue(), const PaddingMode mode = PaddingMode::CONSTANT)
Initialize the function.
Valid data layouts:
NHWC
NCHW
Valid data type configurations:
src dst
All All
Parameters
[in] input Source tensor. Data types supported: All.
[out] output Output tensor. Data type supported: same as input
[in] padding The padding for each spatial dimension of the input tensor. The pair padding[i] specifies the front and the end padding in the i-th dimension.
[in] constant_value (Optional) Constant value to be used for the padding
[in] mode (Optional) Controls whether the padding should be filled with constant_value using CONSTANT, or reflect the input, either including the border values (SYMMETRIC) or not (REFLECT).
Definition at line 173 of file NEPadLayer.cpp.
References ARM_COMPUTE_ERROR, ARM_COMPUTE_ERROR_THROW_ON, ARM_COMPUTE_LOG_PARAMS, arm_compute::auto_init_if_empty(), ICloneable< T >::clone(), arm_compute::misc::shape_calculator::compute_padded_shape(), NECopy::configure(), arm_compute::CONSTANT, ITensor::info(), clang_tidy_rules::mode, arm_compute::REFLECT, arm_compute::SYMMETRIC, ITensorInfo::tensor_shape(), and NEPadLayer::validate().
Referenced by NEFFTConvolutionLayer::configure(), and NEGenerateProposalsLayer::configure().
 {
     ARM_COMPUTE_ERROR_THROW_ON(validate(input->info(), output->info(), padding, constant_value, mode));
     ARM_COMPUTE_LOG_PARAMS(input, output, padding, constant_value, mode);
     _padding = padding;
     _mode    = mode;
     const TensorShape padded_shape = misc::shape_calculator::compute_padded_shape(input->info()->tensor_shape(), _padding);
     auto_init_if_empty(*output->info(), input->info()->clone()->set_tensor_shape(padded_shape));
     // Find the last dimension requiring padding so that it is known when to write to output and whether any padding is applied.
     _num_dimensions = last_padding_dimension(padding) + 1;
     if(_num_dimensions > 0)
     {
         switch(_mode)
         {
             case PaddingMode::CONSTANT:
             {
                 configure_constant_mode(input, output, padding, constant_value);
                 break;
             }
             case PaddingMode::REFLECT:
             case PaddingMode::SYMMETRIC:
             {
                 configure_reflect_symmetric_mode(input, output);
                 break;
             }
             default:
                 ARM_COMPUTE_ERROR("Padding mode not supported.");
         }
     }
     else
     {
         // Copy the input to the whole output if no padding is applied
         _copy_function.configure(input, output);
     }
 }
operator=() [1/2]
NEPadLayer& operator= (const NEPadLayer &) delete
Prevent instances of this class from being copied (As this class contains pointers)
operator=() [2/2]
NEPadLayer& operator= (NEPadLayer &&) delete
Prevent instances of this class from being moved (As this class contains non movable objects)
run()
void run () override virtual
Run the kernels contained in the function.
For CPU kernels:
Multi-threading is used for the kernels which are parallelisable.
By default std::thread::hardware_concurrency() threads are used.
Note
CPPScheduler::set_num_threads() can be used to manually set the number of threads
For OpenCL kernels:
All the kernels are enqueued on the queue associated with CLScheduler.
The queue is then flushed.
Note
The function will not block until the kernels are executed. It is the user's responsibility to wait.
Will call prepare() on first run if hasn't been done
Implements IFunction.
Definition at line 257 of file NEPadLayer.cpp.
References ARM_COMPUTE_ERROR, arm_compute::CONSTANT, Window::DimZ, Scheduler::get(), arm_compute::test::validation::info, arm_compute::REFLECT, NECopy::run(), IScheduler::schedule(), and arm_compute::SYMMETRIC.
Referenced by NEFFTConvolutionLayer::prepare(), NEGenerateProposalsLayer::run(), and NEFFTConvolutionLayer::run().
 {
     if(_num_dimensions > 0)
     {
         switch(_mode)
         {
             case PaddingMode::CONSTANT:
             {
                 NEScheduler::get().schedule(_pad_kernel.get(), Window::DimZ);
                 break;
             }
             case PaddingMode::REFLECT:
             case PaddingMode::SYMMETRIC:
             {
                 for(uint32_t i = 0; i < _num_dimensions; ++i)
                 {
                     if(_padding[i].first > 0 || _padding[i].second > 0)
                     {
                         if(_padding[i].first > 0 && _slice_results[2 * i].info()->total_size() > 0)
{
                             _slice_functions[2 * i].run();
                         }
                         if(_padding[i].second > 0 && _slice_results[2 * i + 1].info()->total_size() > 0)
{
                             _slice_functions[2 * i + 1].run();
                         }
                         _concat_functions[i].run();
                     }
                 }
                 break;
             }
             default:
                 ARM_COMPUTE_ERROR("Padding mode not supported.");
         }
     }
     else
     {
         _copy_function.run();
     }
 }
validate()
Status validate (const ITensorInfo * input, const ITensorInfo * output, const PaddingList & padding, const PixelValue constant_value = PixelValue(), const PaddingMode mode = PaddingMode::CONSTANT) static
Static function to check if given info will lead to a valid configuration of NEPadLayer.
Parameters
[in] input Source tensor info. Data types supported: All.
[in] output Output tensor info. Data type supported: same as input
[in] padding The padding for each spatial dimension of the input tensor. The pair padding[i] specifies the front and the end padding in the i-th dimension.
[in] constant_value (Optional) Constant value to be used for the padding
[in] mode (Optional) Controls whether the padding should be filled with constant_value using CONSTANT, or reflect the input, either including the border values (SYMMETRIC) or not (REFLECT).
Returns
a status
Definition at line 213 of file NEPadLayer.cpp.
References ARM_COMPUTE_ERROR, ARM_COMPUTE_RETURN_ERROR_ON, ARM_COMPUTE_RETURN_ERROR_ON_MISMATCHING_DATA_TYPES, ARM_COMPUTE_RETURN_ERROR_ON_MISMATCHING_DIMENSIONS, ARM_COMPUTE_UNUSED, arm_compute::misc::shape_calculator::compute_padded_shape(), arm_compute::CONSTANT, ITensorInfo::dimension(), arm_compute::REFLECT, arm_compute::SYMMETRIC, ITensorInfo::tensor_shape(), ITensorInfo::total_size(), and NEPadLayerKernel::validate().
Referenced by NEPadLayer::configure(), arm_compute::test::validation::DATA_TEST_CASE(), and NEGenerateProposalsLayer::validate().
 {
     ARM_COMPUTE_UNUSED(constant_value);
     const TensorShape padded_shape = misc::shape_calculator::compute_padded_shape(input->tensor_shape(), padding);
     if(output->total_size() > 0)
     {
         ARM_COMPUTE_RETURN_ERROR_ON_MISMATCHING_DIMENSIONS(output->tensor_shape(), padded_shape);
         ARM_COMPUTE_RETURN_ERROR_ON_MISMATCHING_DATA_TYPES(input, output);
     }
     switch(mode)
     {
         case PaddingMode::CONSTANT:
         {
             return NEPadLayerKernel::validate(input, output, padding, constant_value, mode);
         }
         case PaddingMode::REFLECT:
         case PaddingMode::SYMMETRIC:
         {
             for(uint32_t i = 0; i < padding.size(); ++i)
             {
                 if(mode == PaddingMode::REFLECT)
                 {
                     ARM_COMPUTE_RETURN_ERROR_ON(padding[i].first >= input->dimension(i));
                     ARM_COMPUTE_RETURN_ERROR_ON(padding[i].second >= input->dimension(i));
                 }
                 else
                 {
                     ARM_COMPUTE_RETURN_ERROR_ON(padding[i].first > input->dimension(i));
                     ARM_COMPUTE_RETURN_ERROR_ON(padding[i].second > input->dimension(i));
                 }
             }
             break;
         }
         default:
         {
             ARM_COMPUTE_ERROR("Invalid mode");
         }
     }
     return Status{};
 }
The documentation for this class was generated from the following files:
arm_compute/runtime/NEON/functions/NEPadLayer.h
src/runtime/NEON/functions/NEPadLayer.cpp