Compute Library: PostOpList< TensorRelatedT > Class Template Reference
PostOpList< TensorRelatedT > Class Template Reference
A sequence of PostOps that can be appended to the end of other operators.
#include <IPostOp.h>
Public Member Functions
PostOpList ()=default
Constructor.
~PostOpList ()=default
Destructor.
PostOpList (const PostOpList &other)
PostOpList & operator= (const PostOpList &other)
PostOpList (PostOpList &&other)=default
PostOpList & operator= (PostOpList &&other)=default
template<typename OpT , typename... Args>
void push_back_op (Args &&... args)
Add a new post op at the end of the list.
size_t size () const
Number of post ops.
size_t total_num_arguments () const
Total number of post ops.
std::vector< std::unique_ptr< IPostOp< TensorRelatedT > > > & get_list ()
Get the underlying post op list.
const std::vector< std::unique_ptr< IPostOp< TensorRelatedT > > > & get_list () const
Detailed Description
template<typename TensorRelatedT>
class arm_compute::experimental::PostOpList< TensorRelatedT >
A sequence of PostOps that can be appended to the end of other operators.
Definition at line 119 of file IPostOp.h.
Constructor & Destructor Documentation
PostOpList() [1/3]
PostOpList () default
Constructor.
~PostOpList()
~PostOpList () default
Destructor.
PostOpList() [2/3]
PostOpList (const PostOpList< TensorRelatedT > & other) inline
Definition at line 126 of file IPostOp.h.
     {
         for(const auto &op : other._post_ops)
         {
             this->_post_ops.push_back(op->clone());
         }
     }
PostOpList() [3/3]
PostOpList (PostOpList< TensorRelatedT > && other) default
Member Function Documentation
get_list() [1/2]
std::vector<std::unique_ptr<IPostOp<TensorRelatedT> > >& get_list () inline
Get the underlying post op list.
Definition at line 165 of file IPostOp.h.
Referenced by PostOpCLKernelUtils::are_post_op_shapes_compliant(), arm_compute::experimental::get_post_op_sequence(), PostOpCLKernelUtils::set_post_ops_cl_build_options(), and arm_compute::experimental::transform_post_op_list_arguments().
     {
         return _post_ops;
     }
get_list() [2/2]
const std::vector<std::unique_ptr<IPostOp<TensorRelatedT> > >& get_list () const inline
Definition at line 169 of file IPostOp.h.
     {
         return _post_ops;
     }
operator=() [1/2]
PostOpList& operator= (const PostOpList< TensorRelatedT > & other) inline
Definition at line 133 of file IPostOp.h.
     {
         PostOpList tmp{ other };
         std::swap(tmp, *this);
         return *this;
     }
operator=() [2/2]
PostOpList& operator= (PostOpList< TensorRelatedT > && other) default
push_back_op()
void push_back_op (Args &&... args) inline
Add a new post op at the end of the list.
Definition at line 144 of file IPostOp.h.
Referenced by arm_compute::test::validation::DATA_TEST_CASE(), and arm_compute::test::validation::TEST_CASE().
     {
         _post_ops.push_back(std::make_unique<OpT>(std::forward<Args>(args)...));
     }
size()
size_t size () const inline
Number of post ops.
Definition at line 150 of file IPostOp.h.
Referenced by PostOpCLKernelUtils::is_post_op_sequence_supported(), PostOpCLKernelUtils::set_post_ops_cl_build_options(), and CLConvolutionLayer::validate().
     {
         return _post_ops.size();
     }
total_num_arguments()
size_t total_num_arguments () const inline
Total number of post ops.
Definition at line 156 of file IPostOp.h.
     {
         return std::accumulate(_post_ops.begin(), _post_ops.end(), 0, [](size_t op1_arity, const auto & op2)
         {
             return op1_arity + op2->arity();
         });
     }
The documentation for this class was generated from the following file:
arm_compute/core/experimental/IPostOp.h