Compute Library: ContextSchedulerUser Class Reference
ContextSchedulerUser Class Reference
#include <Helpers.h>
Public Member Functions
ContextSchedulerUser (RuntimeContext *ctx)
Default Constructor.
ContextSchedulerUser (const ContextSchedulerUser &)=delete
Prevent instances of this class from being copied (As this class contains pointers)
ContextSchedulerUser (ContextSchedulerUser &&)=default
Default move constructor.
ContextSchedulerUser & operator= (const ContextSchedulerUser &)=delete
Prevent instances of this class from being copied (As this class contains pointers)
ContextSchedulerUser & operator= (ContextSchedulerUser &&)=default
Default move assignment operator.
void intercept_scheduler (std::unique_ptr< IScheduler > interceptor)
Intercept the scheduler used by.
void restore_scheduler ()
Restore the original scheduler.
IScheduler * scheduler ()
Real scheduler accessor.
Public Member Functions inherited from ISchedulerUser
virtual ~ISchedulerUser ()=default
Default Destructor.
Detailed Description
Definition at line 34 of file Helpers.h.
Constructor & Destructor Documentation
ContextSchedulerUser() [1/3]
ContextSchedulerUser (RuntimeContext * ctx) inline
Default Constructor.
Parameters
[in] ctx Runtime context to track
Definition at line 41 of file Helpers.h.
References ARM_COMPUTE_ERROR_ON, ContextSchedulerUser::operator=(), and RuntimeContext::scheduler().
         : _ctx(ctx), _scheduler_to_use(nullptr), _real_scheduler(nullptr), _interceptor(nullptr)
     {
         ARM_COMPUTE_ERROR_ON(ctx == nullptr);
         _real_scheduler   = _ctx->scheduler();
         _scheduler_to_use = _real_scheduler;
     }
ContextSchedulerUser() [2/3]
ContextSchedulerUser (const ContextSchedulerUser &) delete
Prevent instances of this class from being copied (As this class contains pointers)
ContextSchedulerUser() [3/3]
ContextSchedulerUser (ContextSchedulerUser &&) default
Default move constructor.
Member Function Documentation
intercept_scheduler()
void intercept_scheduler (std::unique_ptr< IScheduler > interceptor) inline virtual
Intercept the scheduler used by.
Parameters
interceptor Intercept the scheduler used by the scheduler user.
Implements ISchedulerUser.
Definition at line 58 of file Helpers.h.
References RuntimeContext::set_scheduler().
     {
         if(interceptor != nullptr)
         {
             _interceptor      = std::move(interceptor);
             _scheduler_to_use = _interceptor.get();
             _ctx->set_scheduler(_scheduler_to_use);
         }
     }
operator=() [1/2]
ContextSchedulerUser& operator= (const ContextSchedulerUser &) delete
Prevent instances of this class from being copied (As this class contains pointers)
Referenced by ContextSchedulerUser::ContextSchedulerUser().
operator=() [2/2]
ContextSchedulerUser& operator= (ContextSchedulerUser &&) default
Default move assignment operator.
restore_scheduler()
void restore_scheduler () inline virtual
Restore the original scheduler.
Implements ISchedulerUser.
Definition at line 67 of file Helpers.h.
References RuntimeContext::set_scheduler().
     {
         _interceptor      = nullptr;
         _scheduler_to_use = _real_scheduler;
         _ctx->set_scheduler(_scheduler_to_use);
     }
scheduler()
IScheduler* scheduler () inline virtual
Real scheduler accessor.
Returns
The real scheduler
Implements ISchedulerUser.
Definition at line 73 of file Helpers.h.
     {
         return _real_scheduler;
     }
The documentation for this class was generated from the following file:
tests/instruments/Helpers.h