Compute Library: CpuDirectConv3d Class Reference
CpuDirectConv3d Class Reference
Function to run the direct convolution.
#include <CpuDirectConv3d.h>
Public Member Functions
CpuDirectConv3d (std::shared_ptr< IMemoryManager > memory_manager=nullptr)
~CpuDirectConv3d ()
void configure (ITensorInfo *src0, ITensorInfo *src1, const ITensorInfo *src2, ITensorInfo *dst, const Conv3dInfo conv_info)
Set the input, weights, biases and output tensor info.
void run (ITensorPack &tensors) override
Run the kernels contained in the function.
Public Member Functions inherited from INEOperator
INEOperator (IRuntimeContext *ctx=nullptr)
Constructor.
INEOperator (const INEOperator &)=delete
Prevent instances of this class from being copied (As this class contains pointers)
INEOperator (INEOperator &&)=default
Default move constructor.
INEOperator & operator= (const INEOperator &)=delete
Prevent instances of this class from being copied (As this class contains pointers)
INEOperator & operator= (INEOperator &&)=default
Default move assignment operator.
~INEOperator ()
Default destructor.
void prepare (ITensorPack &constants) override
Prepare the function for executing.
MemoryRequirements workspace () const override
Return the memory requirements required by the workspace.
Public Member Functions inherited from IOperator
virtual ~IOperator ()=default
Destructor.
Static Public Member Functions
static Status validate (const ITensorInfo *src0, const ITensorInfo *src1, const ITensorInfo *src2, const ITensorInfo *dst, const Conv3dInfo conv_info)
Static function to check if given info will lead to a valid configuration.
Detailed Description
Function to run the direct convolution.
This function calls the following kernels:
kernels::CpuDirectConv3dKernel
Definition at line 53 of file CpuDirectConv3d.h.
Constructor & Destructor Documentation
CpuDirectConv3d()
CpuDirectConv3d (std::shared_ptr< IMemoryManager > memory_manager = nullptr)
Definition at line 38 of file CpuDirectConv3d.cpp.
     : _memory_group(std::move(memory_manager)), _conv_kernel(), _activationlayer_function(), _accumulator(), _is_activationlayer_enabled(false), _dim_split(Window::DimZ)
 {
 }
~CpuDirectConv3d()
~CpuDirectConv3d () default
Member Function Documentation
configure()
void configure (ITensorInfo * src0, ITensorInfo * src1, const ITensorInfo * src2, ITensorInfo * dst, const Conv3dInfo conv_info)
Set the input, weights, biases and output tensor info.
Valid data layouts:
NDHWC
Valid data type configurations:
src0 src1 src2 dst
F16 F16 F16 F16
F32 F32 F32 F32
QASYMM8 QASYMM8 S32 QASYMM8
QASYMM8_SIGNED QASYMM8_SIGNED S32 QASYMM8_SIGNED
Parameters
[in,out] src0 Input tensor info.
[in] src1 Set of kernels to convolve the input volume. The 2nd dimension must be the same as the src0's volume 1st dimension.
[in] src2 Set of biases. Can be nullptr.
[out] dst Output tensor info. The 1st dimensions must be equal to the 1st dimension of the kernels tensor.
[in] conv_info Contains padding, stride, acitvation information.
Definition at line 43 of file CpuDirectConv3d.cpp.
References Conv3dInfo::act_info, Tensor::allocator(), ARM_COMPUTE_ERROR_ON, ARM_COMPUTE_LOG_PARAMS, Tensor::buffer(), ITensorInfo::data_layout(), Window::DimY, ActivationLayerInfo::enabled(), TensorAllocator::free(), and arm_compute::NDHWC.
 {
     ARM_COMPUTE_LOG_PARAMS(src0, src1, src2, dst, conv_info);
     ARM_COMPUTE_ERROR_ON(src0->data_layout() != DataLayout::NDHWC);
     _conv_kernel = std::make_unique<kernels::CpuDirectConv3dKernel>();
     // Free accumulator
     if(_accumulator.buffer() != nullptr)
     {
         _accumulator.allocator()->free();
     }
     _dim_split = Window::DimY;
     _conv_kernel->configure(src0, src1, src2, dst, conv_info);
     //Configure Activation Layer
     _is_activationlayer_enabled = conv_info.act_info.enabled();
     if(_is_activationlayer_enabled)
     {
         _activationlayer_function = std::make_unique<CpuActivation>();
         _activationlayer_function->configure(dst, dst, conv_info.act_info);
     }
 }
run()
void run (ITensorPack & tensors) override virtual
Run the kernels contained in the function.
Parameters
[in] tensors Vector that contains the tensors to operate on.
Reimplemented from INEOperator.
Definition at line 84 of file CpuDirectConv3d.cpp.
References arm_compute::ACL_DST, arm_compute::ACL_SRC, ITensorPack::add_tensor(), arm_compute::test::validation::dst, Scheduler::get(), ITensorPack::get_tensor(), arm_compute::test::validation::pack, and IScheduler::schedule_op().
 {
     MemoryGroupResourceScope scope_mg(_memory_group);
     auto dst = tensors.get_tensor(TensorType::ACL_DST);
     NEScheduler::get().schedule_op(_conv_kernel.get(), _dim_split, _conv_kernel->window(), tensors);
     if(_is_activationlayer_enabled)
     {
         ITensorPack pack;
         pack.add_tensor(TensorType::ACL_SRC, dst);
         pack.add_tensor(TensorType::ACL_DST, dst);
         _activationlayer_function->run(pack);
     }
 }
validate()
Status validate (const ITensorInfo * src0, const ITensorInfo * src1, const ITensorInfo * src2, const ITensorInfo * dst, const Conv3dInfo conv_info) static
Static function to check if given info will lead to a valid configuration.
Similar to CpuDirectConv3d::configure()
Returns
a status
Definition at line 69 of file CpuDirectConv3d.cpp.
References Conv3dInfo::act_info, ARM_COMPUTE_RETURN_ERROR_ON_NULLPTR, ARM_COMPUTE_RETURN_ON_ERROR, ActivationLayerInfo::enabled(), CpuActivation::validate(), and CpuDirectConv3dKernel::validate().
Referenced by NEConv3D::configure(), and NEConv3D::validate().
 {
     ARM_COMPUTE_RETURN_ERROR_ON_NULLPTR(src0, src1, dst);
     // Validate Convolution kernel
     ARM_COMPUTE_RETURN_ON_ERROR(kernels::CpuDirectConv3dKernel::validate(src0, src1, src2, dst, conv_info));
     if(conv_info.act_info.enabled())
     {
         ARM_COMPUTE_RETURN_ON_ERROR(CpuActivation::validate(dst, nullptr, conv_info.act_info));
     }
     return Status{};
 }
The documentation for this class was generated from the following files:
src/cpu/operators/CpuDirectConv3d.h
src/cpu/operators/CpuDirectConv3d.cpp