Compute Library: ROIPoolingLayerInfo Class Reference
ROIPoolingLayerInfo Class Reference final
ROI Pooling Layer Information class.
#include <Types.h>
Public Member Functions
ROIPoolingLayerInfo (unsigned int pooled_width, unsigned int pooled_height, float spatial_scale, unsigned int sampling_ratio=0)
Constructor.
unsigned int pooled_width () const
Get the pooled width of the layer.
unsigned int pooled_height () const
Get the pooled height of the layer.
float spatial_scale () const
Get the spatial scale.
unsigned int sampling_ratio () const
Get sampling ratio.
Detailed Description
ROI Pooling Layer Information class.
Definition at line 1268 of file Types.h.
Constructor & Destructor Documentation
ROIPoolingLayerInfo()
ROIPoolingLayerInfo (unsigned int pooled_width, unsigned int pooled_height, float spatial_scale, unsigned int sampling_ratio = 0) inline
Constructor.
Parameters
[in] pooled_width Pooled width of the layer.
[in] pooled_height Pooled height of the layer.
[in] spatial_scale Spatial scale to be applied to the ROI coordinates and dimensions.
[in] sampling_ratio Number of samples to include in each pooling region (if set to zero, a ceil(roi_dims/pooling_dims))
Definition at line 1278 of file Types.h.
         : _pooled_width(pooled_width), _pooled_height(pooled_height), _spatial_scale(spatial_scale), _sampling_ratio(sampling_ratio)
     {
     }
Member Function Documentation
pooled_height()
unsigned int pooled_height () const inline
Get the pooled height of the layer.
Definition at line 1288 of file Types.h.
Referenced by arm_compute::misc::shape_calculator::compute_roi_align_shape(), NEROIPoolingLayerKernel::configure(), CLROIPoolingLayerKernel::configure(), CLROIAlignLayerKernel::configure(), ROIAlignLayerNode::configure_output(), arm_compute::graph::backends::detail::create_roi_align_layer(), arm_compute::operator<<(), arm_compute::cpu::roi_align(), arm_compute::test::validation::reference::roi_align_layer(), arm_compute::test::validation::reference::roi_pool_layer(), NEROIPoolingLayerKernel::run(), and CLROIPoolingLayerKernel::validate().
     {
         return _pooled_height;
     }
pooled_width()
unsigned int pooled_width () const inline
Get the pooled width of the layer.
Definition at line 1283 of file Types.h.
Referenced by arm_compute::misc::shape_calculator::compute_roi_align_shape(), NEROIPoolingLayerKernel::configure(), CLROIPoolingLayerKernel::configure(), CLROIAlignLayerKernel::configure(), ROIAlignLayerNode::configure_output(), arm_compute::graph::backends::detail::create_roi_align_layer(), arm_compute::operator<<(), arm_compute::cpu::roi_align(), arm_compute::test::validation::reference::roi_align_layer(), arm_compute::test::validation::reference::roi_pool_layer(), NEROIPoolingLayerKernel::run(), and CLROIPoolingLayerKernel::validate().
     {
         return _pooled_width;
     }
sampling_ratio()
unsigned int sampling_ratio () const inline
Get sampling ratio.
Definition at line 1298 of file Types.h.
Referenced by CLROIAlignLayerKernel::configure(), arm_compute::cpu::roi_align(), and arm_compute::test::validation::reference::roi_align_layer().
     {
         return _sampling_ratio;
     }
spatial_scale()
float spatial_scale () const inline
Get the spatial scale.
Definition at line 1293 of file Types.h.
Referenced by CLROIPoolingLayerKernel::configure(), CLROIAlignLayerKernel::configure(), arm_compute::operator<<(), arm_compute::cpu::roi_align(), arm_compute::test::validation::reference::roi_align_layer(), arm_compute::test::validation::reference::roi_pool_layer(), and NEROIPoolingLayerKernel::run().
     {
         return _spatial_scale;
     }
The documentation for this class was generated from the following file:
arm_compute/core/Types.h