Compute Library: CpuWinogradConv2dTransformInputKernel< T, OutputTileRows, OutputTileCols, KernelRows, KernelCols > Class Template Reference
CpuWinogradConv2dTransformInputKernel< T, OutputTileRows, OutputTileCols, KernelRows, KernelCols > Class Template Reference
Kernel to perform Winograd input transform.
#include <CpuWinogradConv2dKernel.h>
Public Types
using WinogradBase = winograd::WinogradGEMM< OutputTileRows, OutputTileCols, KernelRows, KernelCols, winograd::WinogradRoots::Integers >
Winograd base kernel.
using WinogradConv = typename WinogradBase::template Convolution< T, T >
Winograd convolution kernel.
Public Member Functions
CpuWinogradConv2dTransformInputKernel (const CpuWinogradConv2dTransformInputKernel &)=delete
Prevent instances of this class from being copied (As this class contains pointers)
CpuWinogradConv2dTransformInputKernel & operator= (const CpuWinogradConv2dTransformInputKernel &)=delete
Prevent instances of this class from being copied (As this class contains pointers)
CpuWinogradConv2dTransformInputKernel (CpuWinogradConv2dTransformInputKernel &&)=default
Allow instances of this class to be moved.
CpuWinogradConv2dTransformInputKernel & operator= (CpuWinogradConv2dTransformInputKernel &&)=default
Allow instances of this class to be moved.
~CpuWinogradConv2dTransformInputKernel ()=default
Default destructor.
unsigned int get_input_storage_size (int num_batches, int num_channels, int num_rows, int num_cols, bool same_padding) const override
Determine how much memory (in units of TIn) to allocate for the transformed input.
unsigned int get_working_space_size (unsigned int num_threads) const override
Get the working space required to perform the transformation.
int get_matrix_stride (int num_batches, int num_channels, int num_rows, int num_cols, bool same_padding) const override
Gets the stride between matrices in the input worspace.
CpuWinogradConv2dTransformInputKernel ()
Default constructor.
const char * name () const override
Name of the kernel.
void configure (const ITensorInfo *input_nhwc, const int num_batches, const int num_rows, const int num_cols, const int num_channels, const PaddingType padding, ITensorInfo *output, const int matrix_stride, ITensorInfo *workspace) override
Configure the output transform kernel.
void run_op (ITensorPack &tensors, const Window &window, const ThreadInfo &info) override
Execute the kernel on the passed window.
Public Member Functions inherited from ICpuWinogradConv2dTransformInputKernel
virtual ~ICpuWinogradConv2dTransformInputKernel ()
Destructor.
Public Member Functions inherited from ICPPKernel
virtual ~ICPPKernel ()=default
Default destructor.
virtual void run (const Window &window, const ThreadInfo &info)
Execute the kernel on the passed window.
virtual void run_nd (const Window &window, const ThreadInfo &info, const Window &thread_locator)
legacy compatibility layer for implemantions which do not support thread_locator In these cases we simply narrow the interface down the legacy version
virtual size_t get_mws (const CPUInfo &platform, size_t thread_count) const
Return minimum workload size of the relevant kernel.
Public Member Functions inherited from IKernel
IKernel ()
Constructor.
virtual ~IKernel ()=default
Destructor.
virtual bool is_parallelisable () const
Indicates whether or not the kernel is parallelisable.
virtual BorderSize border_size () const
The size of the border for that kernel.
const Window & window () const
The maximum window the kernel can be executed on.
bool is_window_configured () const
Function to check if the embedded window of this kernel has been configured.
Static Public Member Functions
static Status validate (const ITensorInfo *input, const ITensorInfo *output, const WinogradInfo &winograd_info)
Static function to check if given info will lead to a valid configuration of CpuWinogradConv2dTransformInputKernel.
Static Public Member Functions inherited from ICpuKernel< ICpuWinogradConv2dTransformInputKernel >
static const auto * get_implementation (const SelectorType &selector, KernelSelectionType selection_type=KernelSelectionType::Supported)
Micro-kernel selector.
Additional Inherited Members
Static Public Attributes inherited from ICPPKernel
static constexpr size_t default_mws = 1
Detailed Description
template<typename T, int OutputTileRows, int OutputTileCols, int KernelRows, int KernelCols>
class arm_compute::cpu::CpuWinogradConv2dTransformInputKernel< T, OutputTileRows, OutputTileCols, KernelRows, KernelCols >
Kernel to perform Winograd input transform.
Definition at line 100 of file CpuWinogradConv2dKernel.h.
Member Typedef Documentation
WinogradBase
using WinogradBase = winograd::WinogradGEMM<OutputTileRows, OutputTileCols, KernelRows, KernelCols, winograd::WinogradRoots::Integers>
Winograd base kernel.
Definition at line 196 of file CpuWinogradConv2dKernel.h.
WinogradConv
using WinogradConv = typename WinogradBase::template Convolution<T, T>
Winograd convolution kernel.
Definition at line 198 of file CpuWinogradConv2dKernel.h.
Constructor & Destructor Documentation
CpuWinogradConv2dTransformInputKernel() [1/3]
CpuWinogradConv2dTransformInputKernel (const CpuWinogradConv2dTransformInputKernel< T, OutputTileRows, OutputTileCols, KernelRows, KernelCols > &) delete
Prevent instances of this class from being copied (As this class contains pointers)
CpuWinogradConv2dTransformInputKernel() [2/3]
CpuWinogradConv2dTransformInputKernel (CpuWinogradConv2dTransformInputKernel< T, OutputTileRows, OutputTileCols, KernelRows, KernelCols > &&) default
Allow instances of this class to be moved.
~CpuWinogradConv2dTransformInputKernel()
~CpuWinogradConv2dTransformInputKernel () default
Default destructor.
CpuWinogradConv2dTransformInputKernel() [3/3]
CpuWinogradConv2dTransformInputKernel ()
Default constructor.
Definition at line 322 of file CpuWinogradConv2dKernel.cpp.
     : _transform(nullptr), _num_channels(0), _matrix_stride(0)
 {
 }
Member Function Documentation
configure()
void configure (const ITensorInfo * input_nhwc, const int num_batches, const int num_rows, const int num_cols, const int num_channels, const PaddingType padding, ITensorInfo * output, const int matrix_stride, ITensorInfo * workspace) override virtual
Configure the output transform kernel.
Parameters
[in] input_nhwc Input tensor. Data types supported: F16/F32. Layout supported NHWC.
[in] num_batches Number of batches in input tensor.
[in] num_rows Number of rows in input tensor.
[in] num_cols Number of columns in input tensor.
[in] num_channels Number of channels in input tensor.
[in] padding Padding type.
[out] output Base of output matrices.
[in] matrix_stride Stride between output matrices.
[in] workspace Tensor to be used as the working space during the computation.
< Padding to apply to the top of the image.
< Padding to apply to the left of the image.
< Padding to apply to the bottom of the image.
< Padding to apply to the right of the image.
Implements ICpuWinogradConv2dTransformInputKernel.
Definition at line 328 of file CpuWinogradConv2dKernel.cpp.
References ARM_COMPUTE_UNUSED, Window::DimX, and arm_gemm::iceildiv().
 {
     ARM_COMPUTE_UNUSED(input_nhwc, output, matrix_stride, workspace);
     _num_channels  = num_channels;
     _matrix_stride = matrix_stride;
     const int padding_top    = (padding == PADDING_SAME) ? (KernelRows - 1) / 2 : 0;
     const int padding_left   = (padding == PADDING_SAME) ? (KernelCols - 1) / 2 : 0;
     const int padding_bottom = (padding == PADDING_SAME) ? iceildiv(KernelRows - 1, 2) : 0;
     const int padding_right  = (padding == PADDING_SAME) ? iceildiv(KernelCols - 1, 2) : 0;
     _transform = std::make_unique<InputTransform>(
                      KernelRows,
                      KernelCols,
                      num_batches,
                      num_rows,
                      num_cols,
                      num_channels,
                      padding_top,    /**< Padding to apply to the top of the image. */
                      padding_left,   /**< Padding to apply to the left of the image. */
                      padding_bottom, /**< Padding to apply to the bottom of the image. */
                      padding_right   /**< Padding to apply to the right of the image. */
                  );
     Window win;
     auto   win_last = _transform->get_window();
     win.set(Window::DimX, Window::Dimension(0, win_last, 1));
     ICpuKernel::configure(win);
 }
get_input_storage_size()
unsigned int get_input_storage_size (int num_batches, int num_channels, int num_rows, int num_cols, bool same_padding) const override virtual
Determine how much memory (in units of TIn) to allocate for the transformed input.
Parameters
[in] num_batches Number of batches in the input tensor.
[in] num_channels Number of feature maps in the input tensor.
[in] num_rows Number of rows in each feature map.
[in] num_cols Number of columns in each feature map.
[in] same_padding Use "SAME" padding, otherwise use "VALID".
Returns
Storage size (in units of TIn) required.
Implements ICpuWinogradConv2dTransformInputKernel.
Definition at line 289 of file CpuWinogradConv2dKernel.cpp.
References arm_compute::test::validation::input_shape.
 {
     // Construct shapes for the input and kernel tensors.
     const Tensor4DShape input_shape(num_batches, num_rows, num_cols, num_channels);
     const KernelShape   kern_shape(1, KernelRows, KernelCols, num_channels);
     // Return the size, converted into units of TIn
     return static_cast<unsigned int>(WinogradConv::get_input_storage_size(num_batches, num_rows, num_cols, num_channels, same_padding) / sizeof(T));
 }
get_matrix_stride()
int get_matrix_stride (int num_batches, int num_channels, int num_rows, int num_cols, bool same_padding) const override virtual
Gets the stride between matrices in the input worspace.
Parameters
[in] num_batches Number of batches in the input tensor.
[in] num_channels Number of feature maps in the input tensor.
[in] num_rows Number of rows in each feature map.
[in] num_cols Number of columns in each feature map.
[in] same_padding Use "SAME" padding, otherwise use "VALID".
Returns
Stride expressed in bytes.
Implements ICpuWinogradConv2dTransformInputKernel.
Definition at line 311 of file CpuWinogradConv2dKernel.cpp.
 {
     return WinogradConv::get_input_matrix_stride(num_batches, num_rows, num_cols, num_channels, same_padding);
 }
get_working_space_size()
unsigned int get_working_space_size (unsigned int num_threads) const override virtual
Get the working space required to perform the transformation.
Note, the working space is only required when performing the transformation - hence it can be reused whenever the transformation is not running.
Parameters
[in] num_threads The greatest number of threads that will be used to execute the transform.
Returns
Size of working space required in bytes.
Implements ICpuWinogradConv2dTransformInputKernel.
Definition at line 305 of file CpuWinogradConv2dKernel.cpp.
 {
     return _transform->get_working_space_size(num_threads);
 }
name()
const char* name () const inline override virtual
Name of the kernel.
Returns
Kernel name
Implements ICPPKernel.
Definition at line 164 of file CpuWinogradConv2dKernel.h.
References ICpuWinogradConv2dTransformInputKernel::configure(), arm_compute::test::validation::info, ICPPKernel::run_op(), and IKernel::window().
     {
         return "CpuWinogradConv2dTransformInputKernel";
     }
operator=() [1/2]
CpuWinogradConv2dTransformInputKernel& operator= (const CpuWinogradConv2dTransformInputKernel< T, OutputTileRows, OutputTileCols, KernelRows, KernelCols > &) delete
Prevent instances of this class from being copied (As this class contains pointers)
operator=() [2/2]
CpuWinogradConv2dTransformInputKernel& operator= (CpuWinogradConv2dTransformInputKernel< T, OutputTileRows, OutputTileCols, KernelRows, KernelCols > &&) default
Allow instances of this class to be moved.
run_op()
void run_op (ITensorPack & tensors, const Window & window, const ThreadInfo & info) override virtual
Execute the kernel on the passed window.
Warning
If is_parallelisable() returns false then the passed window must be equal to window()
Note
The window has to be a region within the window returned by the window() method
The width of the window has to be a multiple of num_elems_processed_per_iteration().
Parameters
[in] tensors A vector containing the tensors to operate on.
[in] window Region on which to execute the kernel. (Must be a region of the window returned by window())
[in] info Info about executing thread and CPU.
Reimplemented from ICPPKernel.
Definition at line 369 of file CpuWinogradConv2dKernel.cpp.
References arm_compute::ACL_DST, arm_compute::ACL_INT, arm_compute::ACL_SRC, ARM_COMPUTE_ERROR_ON, ARM_COMPUTE_ERROR_ON_NULLPTR, ARM_COMPUTE_ERROR_ON_UNCONFIGURED_KERNEL, ARM_COMPUTE_UNUSED, ITensor::buffer(), ITensorInfo::element_size(), ITensorPack::empty(), Window::Dimension::end(), ITensorPack::get_const_tensor(), ITensorPack::get_tensor(), ITensor::info(), ITensorInfo::offset_first_element_in_bytes(), Window::Dimension::start(), ThreadInfo::thread_id, and Window::x().
 {
     ARM_COMPUTE_UNUSED(info);
     ARM_COMPUTE_ERROR_ON_UNCONFIGURED_KERNEL(this);
     ARM_COMPUTE_ERROR_ON(tensors.empty());
     const ITensor *input_nhwc = tensors.get_const_tensor(TensorType::ACL_SRC);
     const ITensor *workspace  = tensors.get_const_tensor(TensorType::ACL_INT);
     ITensor       *output     = tensors.get_tensor(TensorType::ACL_DST);
     const int  element_size_in_bytes = input_nhwc->info()->element_size();
     const int  input_col_stride      = input_nhwc->info()->strides_in_bytes().y() / element_size_in_bytes;
     const int  input_row_stride      = input_nhwc->info()->strides_in_bytes().z() / element_size_in_bytes;
     const int  input_batch_stride    = input_nhwc->info()->strides_in_bytes()[3] / element_size_in_bytes;
     const auto input_nhwc_ptr        = reinterpret_cast<const T *>(input_nhwc->buffer() + input_nhwc->info()->offset_first_element_in_bytes());
     auto       output_ptr            = reinterpret_cast<T *>(output->buffer() + output->info()->offset_first_element_in_bytes());
     ARM_COMPUTE_ERROR_ON_NULLPTR(output_ptr);
     _transform->set_input_tensor(input_nhwc_ptr, input_batch_stride, input_row_stride, input_col_stride);
     _transform->set_output_matrices(output_ptr, _matrix_stride, _num_channels);
     _transform->set_working_space(workspace->buffer());
     // The code below cannot be moved to configure because biases hasn't been allocated at that point
     const size_t fst = window.x().start();
     const size_t lst = window.x().end();
     _transform->run(fst, lst, info.thread_id);
 }
validate()
Status validate (const ITensorInfo * input, const ITensorInfo * output, const WinogradInfo & winograd_info) static
Static function to check if given info will lead to a valid configuration of CpuWinogradConv2dTransformInputKernel.
Parameters
[in] input First tensor input info. Data types supported: F16/F32.
[in] output Output tensor info. Data types supported: same as input.
[in] winograd_info Contains Winograd's information described in WinogradInfo
Returns
a status
Definition at line 399 of file CpuWinogradConv2dKernel.cpp.
References ARM_COMPUTE_RETURN_ON_ERROR, and ICloneable< T >::clone().
 {
     ARM_COMPUTE_RETURN_ON_ERROR(validate_arguments_winograd_input_trans(input, output, winograd_info));
     ARM_COMPUTE_RETURN_ON_ERROR(validate_and_configure_window_winograd_input_trans(input->clone().get(), output->clone().get(), winograd_info).first);
     return Status{};
 }
The documentation for this class was generated from the following files:
src/cpu/kernels/CpuWinogradConv2dKernel.h
src/cpu/kernels/CpuWinogradConv2dKernel.cpp