Compute Library: CLGather Class Reference
CLGather Class Reference
Basic function to run CLGatherKernel.
#include <CLGather.h>
Public Member Functions
void configure (const ICLTensor *input, const ICLTensor *indices, ICLTensor *output, int axis=0)
Initialise the kernel's inputs and outputs.
void configure (const CLCompileContext &compile_context, const ICLTensor *input, const ICLTensor *indices, ICLTensor *output, int axis=0)
Initialise the kernel's inputs and outputs.
Public Member Functions inherited from ICLSimpleFunction
ICLSimpleFunction (CLRuntimeContext *ctx=nullptr)
Constructor.
ICLSimpleFunction (const ICLSimpleFunction &)=delete
Prevent instances of this class from being copied (As this class contains pointers)
ICLSimpleFunction (ICLSimpleFunction &&)=default
Default move constructor.
ICLSimpleFunction & operator= (const ICLSimpleFunction &)=delete
Prevent instances of this class from being copied (As this class contains pointers)
ICLSimpleFunction & operator= (ICLSimpleFunction &&)=default
Default move assignment operator.
~ICLSimpleFunction ()
Default destructor.
void run () override final
Run the kernels contained in the function.
Public Member Functions inherited from IFunction
virtual ~IFunction ()=default
Destructor.
virtual void prepare ()
Prepare the function for executing.
Static Public Member Functions
static Status validate (const ITensorInfo *input, const ITensorInfo *indices, const ITensorInfo *output, int axis=0)
Static function to check if given info will lead to a valid configuration of CLGatherKernel.
Detailed Description
Basic function to run CLGatherKernel.
Definition at line 38 of file CLGather.h.
Member Function Documentation
configure() [1/2]
void configure (const ICLTensor * input, const ICLTensor * indices, ICLTensor * output, int axis = 0)
Initialise the kernel's inputs and outputs.
Valid data layouts:
All
Valid data type configurations:
src dst
All All
Parameters
[in] input Source tensor. Supported tensor rank: up to 4. Data type supported: All.
[in] indices Indices tensor. Supported tensor rank: up to 1. Must be one of the following types: U32/S32. Each value must be in range [0, input.shape[axis])
[out] output Destination tensor. Data type supported: Same as input
[in] axis (Optional) The axis in input to gather indices from. Defaults to 0
Definition at line 33 of file CLGather.cpp.
References CLKernelLibrary::get().
 {
     configure(CLKernelLibrary::get().get_compile_context(), input, indices, output, axis);
 }
configure() [2/2]
void configure (const CLCompileContext & compile_context, const ICLTensor * input, const ICLTensor * indices, ICLTensor * output, int axis = 0)
Initialise the kernel's inputs and outputs.
Parameters
[in] compile_context The compile context to be used.
[in] input Source tensor. Supported tensor rank: up to 4. Data type supported: All.
[in] indices Indices tensor. Supported tensor rank: up to 1. Must be one of the following types: U32/S32. Each value must be in range [0, input.shape[axis])
[out] output Destination tensor. Data type supported: Same as input
[in] axis (Optional) The axis in input to gather indices from. Defaults to 0
Definition at line 38 of file CLGather.cpp.
References ARM_COMPUTE_LOG_PARAMS, and arm_compute::test::validation::k.
 {
     ARM_COMPUTE_LOG_PARAMS(input, indices, output, axis);
     auto k = std::make_unique<CLGatherKernel>();
     k->configure(compile_context, input, indices, output, axis);
     _kernel = std::move(k);
 }
validate()
Status validate (const ITensorInfo * input, const ITensorInfo * indices, const ITensorInfo * output, int axis = 0) static
Static function to check if given info will lead to a valid configuration of CLGatherKernel.
Parameters
[in] input Source tensor info. Supported tensor rank: up to 4. Data type supported: All.
[in] indices Indices tensor info. Supported tensor rank: up to 4. Must be one of the following types: U32/S32. Each value must be in range [0, input.shape[axis])
[in] output Destination tensor info. Data type supported: Same as input
[in] axis (Optional) The axis in input to gather indices from. Defaults to 0
Returns
a status
Definition at line 46 of file CLGather.cpp.
References CLGatherKernel::validate().
Referenced by arm_compute::test::validation::DATA_TEST_CASE().
 {
     return CLGatherKernel::validate(input, indices, output, axis);
 }
The documentation for this class was generated from the following files:
arm_compute/runtime/CL/functions/CLGather.h
src/runtime/CL/functions/CLGather.cpp