Compute Library: CpuFloorKernel Class Reference
CpuFloorKernel Class Reference
Cpu accelarated kernel to perform a floor operation.
#include <CpuFloorKernel.h>
Data Structures
struct FloorKernel
Public Member Functions
CpuFloorKernel ()=default
ARM_COMPUTE_DISALLOW_COPY_ALLOW_MOVE (CpuFloorKernel)
void configure (const ITensorInfo *src, ITensorInfo *dst)
Configure kernel for a given list of arguments.
Window infer_window (const ITensorInfo *src, const ITensorInfo *dst)
Infer execution window.
void run_op (ITensorPack &tensors, const Window &window, const ThreadInfo &info) override
Execute the kernel on the passed window.
const char * name () const override
Name of the kernel.
Public Member Functions inherited from ICPPKernel
virtual ~ICPPKernel ()=default
Default destructor.
virtual void run (const Window &window, const ThreadInfo &info)
Execute the kernel on the passed window.
virtual void run_nd (const Window &window, const ThreadInfo &info, const Window &thread_locator)
legacy compatibility layer for implemantions which do not support thread_locator In these cases we simply narrow the interface down the legacy version
virtual size_t get_mws (const CPUInfo &platform, size_t thread_count) const
Return minimum workload size of the relevant kernel.
Public Member Functions inherited from IKernel
IKernel ()
Constructor.
virtual ~IKernel ()=default
Destructor.
virtual bool is_parallelisable () const
Indicates whether or not the kernel is parallelisable.
virtual BorderSize border_size () const
The size of the border for that kernel.
const Window & window () const
The maximum window the kernel can be executed on.
bool is_window_configured () const
Function to check if the embedded window of this kernel has been configured.
Static Public Member Functions
static Status validate (const ITensorInfo *src, const ITensorInfo *dst)
Static function to check if given info will lead to a valid configuration.
static const std::vector< FloorKernel > & get_available_kernels ()
Static Public Member Functions inherited from ICpuKernel< CpuFloorKernel >
static const auto * get_implementation (const SelectorType &selector, KernelSelectionType selection_type=KernelSelectionType::Supported)
Micro-kernel selector.
Additional Inherited Members
Static Public Attributes inherited from ICPPKernel
static constexpr size_t default_mws = 1
Detailed Description
Cpu accelarated kernel to perform a floor operation.
Definition at line 37 of file CpuFloorKernel.h.
Constructor & Destructor Documentation
CpuFloorKernel()
CpuFloorKernel () default
Member Function Documentation
ARM_COMPUTE_DISALLOW_COPY_ALLOW_MOVE()
ARM_COMPUTE_DISALLOW_COPY_ALLOW_MOVE (CpuFloorKernel)
configure()
void configure (const ITensorInfo * src, ITensorInfo * dst)
Configure kernel for a given list of arguments.
Parameters
[in] src Source tensor. Data type supported: F16/F32.
[out] dst Destination tensor. Same as src
Definition at line 77 of file CpuFloorKernel.cpp.
References ARM_COMPUTE_ERROR_ON_NULLPTR, ARM_COMPUTE_ERROR_THROW_ON, arm_compute::auto_init_if_empty(), arm_compute::calculate_max_window(), ITensorInfo::data_type(), CPUInfo::get(), ICpuKernel< CpuFloorKernel >::get_implementation(), CPUInfo::get_isa(), and ITensorInfo::tensor_shape().
 {
     ARM_COMPUTE_ERROR_ON_NULLPTR(src, dst);
     ARM_COMPUTE_ERROR_THROW_ON(validate_arguments(src, dst));
     auto_init_if_empty(*dst, src->tensor_shape(), 1, src->data_type());
     const auto *uk = CpuFloorKernel::get_implementation(DataTypeISASelectorData{ src->data_type(), CPUInfo::get().get_isa() });
     ARM_COMPUTE_ERROR_ON_NULLPTR(uk);
     _run_method = uk->ukernel;
     _name       = std::string("CpuFloorKernel").append("/").append(uk->name);
     // Configure kernel window
     const Window win = calculate_max_window(*src, Steps());
     ICPPKernel::configure(win);
 }
get_available_kernels()
const std::vector< CpuFloorKernel::FloorKernel > & get_available_kernels () static
Definition at line 143 of file CpuFloorKernel.cpp.
 {
     return available_kernels;
 }
infer_window()
Window infer_window (const ITensorInfo * src, const ITensorInfo * dst)
Infer execution window.
Parameters
[in] src Source tensor info. Data type supported: F16/F32.
[in] dst Destination tensor info. Same as src
Returns
an execution Window
Definition at line 96 of file CpuFloorKernel.cpp.
References ARM_COMPUTE_ERROR_ON, ARM_COMPUTE_UNUSED, ITensorInfo::tensor_shape(), and Window::use_tensor_dimensions().
 {
     ARM_COMPUTE_UNUSED(dst);
     ARM_COMPUTE_ERROR_ON(!bool(validate_arguments(src, dst)));
     Window win;
     win.use_tensor_dimensions(src->tensor_shape());
     return win;
 }
name()
const char * name () const override virtual
Name of the kernel.
Returns
Kernel name
Implements ICPPKernel.
Definition at line 138 of file CpuFloorKernel.cpp.
 {
     return _name.c_str();
 }
run_op()
void run_op (ITensorPack & tensors, const Window & window, const ThreadInfo & info) override virtual
Execute the kernel on the passed window.
Warning
If is_parallelisable() returns false then the passed window must be equal to window()
Note
The window has to be a region within the window returned by the window() method
The width of the window has to be a multiple of num_elems_processed_per_iteration().
Parameters
[in] tensors A vector containing the tensors to operate on.
[in] window Region on which to execute the kernel. (Must be a region of the window returned by window())
[in] info Info about executing thread and CPU.
Reimplemented from ICPPKernel.
Definition at line 112 of file CpuFloorKernel.cpp.
References arm_compute::ACL_DST, arm_compute::ACL_SRC, ARM_COMPUTE_ERROR_ON, ARM_COMPUTE_ERROR_ON_INVALID_SUBWINDOW, ARM_COMPUTE_ERROR_ON_UNCONFIGURED_KERNEL, ARM_COMPUTE_UNUSED, Window::DimX, ITensorPack::empty(), Window::Dimension::end(), arm_compute::execute_window_loop(), ITensorPack::get_const_tensor(), ITensorPack::get_tensor(), Iterator::ptr(), Window::set(), Window::Dimension::start(), IKernel::window(), and Window::x().
 {
     ARM_COMPUTE_UNUSED(info);
     ARM_COMPUTE_ERROR_ON_UNCONFIGURED_KERNEL(this);
     ARM_COMPUTE_ERROR_ON_INVALID_SUBWINDOW(IKernel::window(), window);
     ARM_COMPUTE_ERROR_ON(tensors.empty());
     ARM_COMPUTE_ERROR_ON(_run_method == nullptr);
     const ITensor *src = tensors.get_const_tensor(TensorType::ACL_SRC);
     ITensor       *dst = tensors.get_tensor(TensorType::ACL_DST);
     const auto     len = static_cast<int>(window.x().end()) - static_cast<int>(window.x().start());
     Window win{ window };
     win.set(Window::DimX, Window::Dimension(0, 1, 1));
     Iterator src_it(src, win);
     Iterator dst_it(dst, win);
     execute_window_loop(win, [&](const Coordinates &)
     {
         _run_method(src_it.ptr(), dst_it.ptr(), len);
     },
     src_it, dst_it);
 }
validate()
Status validate (const ITensorInfo * src, const ITensorInfo * dst) static
Static function to check if given info will lead to a valid configuration.
Similar to CpuFloorKernel::configure()
Returns
a status
Definition at line 106 of file CpuFloorKernel.cpp.
References ARM_COMPUTE_RETURN_ON_ERROR.
Referenced by CpuFloor::validate().
 {
     ARM_COMPUTE_RETURN_ON_ERROR(validate_arguments(input, output));
     return Status{};
 }
The documentation for this class was generated from the following files:
src/cpu/kernels/CpuFloorKernel.h
src/cpu/kernels/CpuFloorKernel.cpp