Compute Library: src/c/AclContext.cpp File Reference
AclContext.cpp File Reference
#include "arm_compute/AclEntrypoints.h"
#include "src/common/IContext.h"
#include "src/common/utils/Macros.h"
#include "src/common/utils/Validate.h"
Functions
AclStatus AclCreateContext (AclContext *external_ctx, AclTarget target, const AclContextOptions *options)
__cplusplus
AclStatus AclDestroyContext (AclContext external_ctx)
Destroy a given context object.
Function Documentation
AclCreateContext()
AclStatus AclCreateContext (AclContext * ctx, AclTarget target, const AclContextOptions * options)
__cplusplus
Create a context object
Context is responsible for retaining internal information and work as an aggregate service mechanism
Parameters
[in,out] ctx A valid non-zero context object if no failure occurs
[in] target Target to create the context for
[in] options Context options to be used for all the kernels that are created under the context
Returns
Status code
Returns:
AclSuccess if function was completed successfully
AclOutOfMemory if there was a failure allocating memory resources
AclUnsupportedTarget if the requested target is unsupported
AclInvalidArgument if a given argument is invalid
Definition at line 78 of file AclContext.cpp.
References AclInvalidArgument, AclOutOfMemory, AclSuccess, AclUnsupportedTarget, and ARM_COMPUTE_LOG_ERROR_WITH_FUNCNAME_ACL.
Referenced by Context::Context(), and arm_compute::test::validation::TEST_CASE().
 {
     if(!is_target_valid(target))
     {
         ARM_COMPUTE_LOG_ERROR_WITH_FUNCNAME_ACL("Target is invalid!");
         return AclUnsupportedTarget;
     }
     if(options != nullptr && !are_context_options_valid(options))
     {
         ARM_COMPUTE_LOG_ERROR_WITH_FUNCNAME_ACL("Context options are invalid!");
         return AclInvalidArgument;
     }
     auto ctx = create_context(target, options);
     if(ctx == nullptr)
     {
         ARM_COMPUTE_LOG_ERROR_WITH_FUNCNAME_ACL("Couldn't allocate internal resources for context creation!");
         return AclOutOfMemory;
     }
     *external_ctx = ctx;
     return AclSuccess;
 }
AclDestroyContext()
AclStatus AclDestroyContext (AclContext ctx)
Destroy a given context object.
Parameters
[in] ctx A valid context object to destroy
Returns
Status code
Returns:
AclSuccess if functions was completed successfully
AclInvalidArgument if the provided context is invalid
Definition at line 105 of file AclContext.cpp.
References ARM_COMPUTE_LOG_ERROR_WITH_FUNCNAME_ACL, ARM_COMPUTE_RETURN_CENUM_ON_FAILURE, arm_compute::get_internal(), IContext::refcount(), and arm_compute::detail::validate_internal_context().
 {
     using namespace arm_compute;
     IContext *ctx = get_internal(external_ctx);
     StatusCode status = detail::validate_internal_context(ctx);
     ARM_COMPUTE_RETURN_CENUM_ON_FAILURE(status);
     if(ctx->refcount() != 0)
     {
         ARM_COMPUTE_LOG_ERROR_WITH_FUNCNAME_ACL("Context has references on it that haven't been released!");
         // TODO: Fix the refcount with callback when reaches 0
     }
     delete ctx;
     return utils::as_cenum<AclStatus>(status);
 }