Compute Library: ICpuWinogradConv2dTransformWeightsKernel Class Reference
ICpuWinogradConv2dTransformWeightsKernel Class Reference abstract
Interface for the kernel to perform Winograd weights transform.
#include <CpuWinogradConv2dKernel.h>
Public Member Functions
ICpuWinogradConv2dTransformWeightsKernel (const ICpuWinogradConv2dTransformWeightsKernel &)=default
Prevent instances of this class from being copied (As this class contains pointers)
ICpuWinogradConv2dTransformWeightsKernel & operator= (const ICpuWinogradConv2dTransformWeightsKernel &)=default
Prevent instances of this class from being copied (As this class contains pointers)
ICpuWinogradConv2dTransformWeightsKernel (ICpuWinogradConv2dTransformWeightsKernel &&)=default
Allow instances of this class to be moved.
ICpuWinogradConv2dTransformWeightsKernel & operator= (ICpuWinogradConv2dTransformWeightsKernel &&)=default
Allow instances of this class to be moved.
ICpuWinogradConv2dTransformWeightsKernel ()
virtual ~ICpuWinogradConv2dTransformWeightsKernel ()
virtual unsigned int get_weight_storage_size (int num_output_channels, int num_input_channels) const =0
Determine how much memory (in units of T) to allocate for the transformed weights.
virtual int get_matrix_stride (int num_output_channels, int num_input_channels) const =0
Gets the stride between matrices in the kernel worspace.
virtual void configure (const ITensorInfo *weights_hwio, ITensorInfo *output, const int matrix_stride, const int num_output_channels, const int num_input_channels)=0
Configure the weights transform kernel.
Public Member Functions inherited from ICPPKernel
virtual ~ICPPKernel ()=default
Default destructor.
virtual void run (const Window &window, const ThreadInfo &info)
Execute the kernel on the passed window.
virtual void run_nd (const Window &window, const ThreadInfo &info, const Window &thread_locator)
legacy compatibility layer for implemantions which do not support thread_locator In these cases we simply narrow the interface down the legacy version
virtual void run_op (ITensorPack &tensors, const Window &window, const ThreadInfo &info)
Execute the kernel on the passed window.
virtual const char * name () const =0
Name of the kernel.
Public Member Functions inherited from IKernel
IKernel ()
Constructor.
virtual ~IKernel ()=default
Destructor.
virtual bool is_parallelisable () const
Indicates whether or not the kernel is parallelisable.
virtual BorderSize border_size () const
The size of the border for that kernel.
const Window & window () const
The maximum window the kernel can be executed on.
bool is_window_configured () const
Function to check if the embedded window of this kernel has been configured.
Static Public Member Functions
static Status validate (const ITensorInfo *input, const ITensorInfo *weights)
Static function to check if given info will lead to a valid configuration of CpuWinogradConv2dTransformWeightsKernel.
Detailed Description
Interface for the kernel to perform Winograd weights transform.
Definition at line 421 of file CpuWinogradConv2dKernel.h.
Constructor & Destructor Documentation
ICpuWinogradConv2dTransformWeightsKernel() [1/3]
ICpuWinogradConv2dTransformWeightsKernel (const ICpuWinogradConv2dTransformWeightsKernel &) default
Prevent instances of this class from being copied (As this class contains pointers)
ICpuWinogradConv2dTransformWeightsKernel() [2/3]
ICpuWinogradConv2dTransformWeightsKernel (ICpuWinogradConv2dTransformWeightsKernel &&) default
Allow instances of this class to be moved.
ICpuWinogradConv2dTransformWeightsKernel() [3/3]
ICpuWinogradConv2dTransformWeightsKernel () inline
Definition at line 433 of file CpuWinogradConv2dKernel.h.
     {
     }
~ICpuWinogradConv2dTransformWeightsKernel()
virtual ~ICpuWinogradConv2dTransformWeightsKernel () inline virtual
Definition at line 436 of file CpuWinogradConv2dKernel.h.
References ICpuWinogradConv2dTransformInputKernel::configure(), ICpuWinogradConv2dTransformInputKernel::get_matrix_stride(), arm_compute::test::validation::input, and arm_compute::validate().
     {
     }
Member Function Documentation
configure()
virtual void configure (const ITensorInfo * weights_hwio, ITensorInfo * output, const int matrix_stride, const int num_output_channels, const int num_input_channels) pure virtual
Configure the weights transform kernel.
Parameters
[in] weights_hwio Pointer to the weights tensor info
[out] output Pointer to working space for the output tensor in the Winograd domain.
[in] matrix_stride Stride across matrices in the output workspace.
[in] num_output_channels Number of filters.
[in] num_input_channels Number of channels in each filter.
Referenced by CpuWinogradConv2dTransformWeightsKernel< T, OutputTileRows, OutputTileCols, KernelRows, KernelCols >::get_matrix_stride().
get_matrix_stride()
virtual int get_matrix_stride (int num_output_channels, int num_input_channels) const pure virtual
Gets the stride between matrices in the kernel worspace.
Parameters
[in] num_output_channels Number of output feature maps.
[in] num_input_channels Number of input feature maps.
Returns
Stride expressed in bytes.
Implemented in CpuWinogradConv2dTransformWeightsKernel< T, OutputTileRows, OutputTileCols, KernelRows, KernelCols >.
get_weight_storage_size()
virtual unsigned int get_weight_storage_size (int num_output_channels, int num_input_channels) const pure virtual
Determine how much memory (in units of T) to allocate for the transformed weights.
Parameters
[in] num_output_channels Number of output feature maps.
[in] num_input_channels Number of input feature maps.
Returns
Storage size (in units of T) required.
Implemented in CpuWinogradConv2dTransformWeightsKernel< T, OutputTileRows, OutputTileCols, KernelRows, KernelCols >.
operator=() [1/2]
ICpuWinogradConv2dTransformWeightsKernel& operator= (const ICpuWinogradConv2dTransformWeightsKernel &) default
Prevent instances of this class from being copied (As this class contains pointers)
operator=() [2/2]
ICpuWinogradConv2dTransformWeightsKernel& operator= (ICpuWinogradConv2dTransformWeightsKernel &&) default
Allow instances of this class to be moved.
validate()
Status validate (const ITensorInfo * input, const ITensorInfo * weights) static
Static function to check if given info will lead to a valid configuration of CpuWinogradConv2dTransformWeightsKernel.
Parameters
[in] input First tensor input info. Data types supported: F16/F32.
[in] weights Weights tensor info. Data types supported: same as input.
Returns
a status
Definition at line 180 of file CpuWinogradConv2dKernel.cpp.
References ARM_COMPUTE_RETURN_ERROR_ON, ARM_COMPUTE_RETURN_ERROR_ON_DATA_TYPE_CHANNEL_NOT_IN, ARM_COMPUTE_RETURN_ERROR_ON_MISMATCHING_DATA_TYPES, ARM_COMPUTE_RETURN_ERROR_ON_MSG, arm_compute::test::validation::data_layout, ITensorInfo::data_layout(), ITensorInfo::data_type(), ITensorInfo::dimension(), arm_compute::F16, arm_compute::F32, arm_compute::get_data_layout_dimension_index(), arm_compute::HEIGHT, ITensorInfo::num_dimensions(), and arm_compute::WIDTH.
 {
     ARM_COMPUTE_RETURN_ERROR_ON_DATA_TYPE_CHANNEL_NOT_IN(input, 1, DataType::F16, DataType::F32);
     ARM_COMPUTE_RETURN_ERROR_ON_MISMATCHING_DATA_TYPES(input, weights);
     const DataLayout   data_layout = input->data_layout();
     const unsigned int width_idx   = get_data_layout_dimension_index(data_layout, DataLayoutDimension::WIDTH);
     const unsigned int height_idx  = get_data_layout_dimension_index(data_layout, DataLayoutDimension::HEIGHT);
     ARM_COMPUTE_RETURN_ERROR_ON_MSG(!is_kernel_size_supported(input->data_type(), Size2D(weights->dimension(width_idx), weights->dimension(height_idx))),
                                     "Only 1x3, 3x1, 3x3 and 5x5 kernels are supported");
     ARM_COMPUTE_RETURN_ERROR_ON(weights->num_dimensions() > 4);
     return Status{};
 }
The documentation for this class was generated from the following files:
src/core/cpu/kernels/CpuWinogradConv2dKernel.h
src/core/cpu/kernels/CpuWinogradConv2dKernel.cpp