Compute Library: CLBoundingBoxTransformKernel Class Reference
CLBoundingBoxTransformKernel Class Reference
Interface for the bounding box kernel.
#include <CLBoundingBoxTransformKernel.h>
Public Member Functions
CLBoundingBoxTransformKernel ()
Default constructor.
CLBoundingBoxTransformKernel (const CLBoundingBoxTransformKernel &)=delete
Prevent instances of this class from being copied (As this class contains pointers)
CLBoundingBoxTransformKernel & operator= (const CLBoundingBoxTransformKernel &)=delete
Prevent instances of this class from being copied (As this class contains pointers)
CLBoundingBoxTransformKernel (CLBoundingBoxTransformKernel &&)=default
Allow instances of this class to be moved.
CLBoundingBoxTransformKernel & operator= (CLBoundingBoxTransformKernel &&)=default
Allow instances of this class to be moved.
~CLBoundingBoxTransformKernel ()=default
Default destructor.
void configure (const ICLTensor *boxes, ICLTensor *pred_boxes, const ICLTensor *deltas, const BoundingBoxTransformInfo &info)
Set the input and output tensors.
void configure (const CLCompileContext &compile_context, const ICLTensor *boxes, ICLTensor *pred_boxes, const ICLTensor *deltas, const BoundingBoxTransformInfo &info)
Set the input and output tensors.
void run (const Window &window, cl::CommandQueue &queue) override
Enqueue the OpenCL kernel to process the given window on the passed OpenCL command queue.
Public Member Functions inherited from ICLKernel
ICLKernel ()
Constructor.
cl::Kernel & kernel ()
Returns a reference to the OpenCL kernel of this object.
CLKernelType type () const
Returns the CL kernel type.
template<typename T >
void add_1D_array_argument (unsigned int &idx, const ICLArray< T > *array, const Strides &strides, unsigned int num_dimensions, const Window &window)
Add the passed 1D array's parameters to the object's kernel's arguments starting from the index idx.
void add_1D_tensor_argument (unsigned int &idx, const ICLTensor *tensor, const Window &window)
Add the passed 1D tensor's parameters to the object's kernel's arguments starting from the index idx.
void add_1D_tensor_argument_if (bool cond, unsigned int &idx, const ICLTensor *tensor, const Window &window)
Add the passed 1D tensor's parameters to the object's kernel's arguments starting from the index idx if the condition is true.
void add_2D_tensor_argument (unsigned int &idx, const ICLTensor *tensor, const Window &window)
Add the passed 2D tensor's parameters to the object's kernel's arguments starting from the index idx.
void add_2D_tensor_argument_if (bool cond, unsigned int &idx, const ICLTensor *tensor, const Window &window)
Add the passed 2D tensor's parameters to the object's kernel's arguments starting from the index idx if the condition is true.
void add_3D_tensor_argument (unsigned int &idx, const ICLTensor *tensor, const Window &window)
Add the passed 3D tensor's parameters to the object's kernel's arguments starting from the index idx.
void add_4D_tensor_argument (unsigned int &idx, const ICLTensor *tensor, const Window &window)
Add the passed 4D tensor's parameters to the object's kernel's arguments starting from the index idx.
virtual void run_op (ITensorPack &tensors, const Window &window, cl::CommandQueue &queue)
Enqueue the OpenCL kernel to process the given window on the passed OpenCL command queue.
template<typename T >
void add_argument (unsigned int &idx, T value)
Add the passed parameters to the object's kernel's arguments starting from the index idx.
void set_lws_hint (const cl::NDRange &lws_hint)
Set the Local-Workgroup-Size hint.
cl::NDRange lws_hint () const
Return the Local-Workgroup-Size hint.
void set_wbsm_hint (const cl_int &wbsm_hint)
Set the workgroup batch size modifier hint.
cl_int wbsm_hint () const
Return the workgroup batch size modifier hint.
const std::string & config_id () const
Get the configuration ID.
void set_target (GPUTarget target)
Set the targeted GPU architecture.
void set_target (cl::Device &device)
Set the targeted GPU architecture according to the CL device.
GPUTarget get_target () const
Get the targeted GPU architecture.
size_t get_max_workgroup_size ()
Get the maximum workgroup size for the device the CLKernelLibrary uses.
template<unsigned int dimension_size>
void add_tensor_argument (unsigned &idx, const ICLTensor *tensor, const Window &window)
template<typename T , unsigned int dimension_size>
void add_array_argument (unsigned &idx, const ICLArray< T > *array, const Strides &strides, unsigned int num_dimensions, const Window &window)
Add the passed array's parameters to the object's kernel's arguments starting from the index idx.
Public Member Functions inherited from IKernel
IKernel ()
Constructor.
virtual ~IKernel ()=default
Destructor.
virtual bool is_parallelisable () const
Indicates whether or not the kernel is parallelisable.
virtual BorderSize border_size () const
The size of the border for that kernel.
const Window & window () const
The maximum window the kernel can be executed on.
bool is_window_configured () const
Function to check if the embedded window of this kernel has been configured.
Static Public Member Functions
static Status validate (const ITensorInfo *boxes, const ITensorInfo *pred_boxes, const ITensorInfo *deltas, const BoundingBoxTransformInfo &info)
Static function to check if given info will lead to a valid configuration of CLBoundingBoxTransform.
Static Public Member Functions inherited from ICLKernel
static constexpr unsigned int num_arguments_per_1D_array ()
Returns the number of arguments enqueued per 1D array object.
static constexpr unsigned int num_arguments_per_1D_tensor ()
Returns the number of arguments enqueued per 1D tensor object.
static constexpr unsigned int num_arguments_per_2D_tensor ()
Returns the number of arguments enqueued per 2D tensor object.
static constexpr unsigned int num_arguments_per_3D_tensor ()
Returns the number of arguments enqueued per 3D tensor object.
static constexpr unsigned int num_arguments_per_4D_tensor ()
Returns the number of arguments enqueued per 4D tensor object.
static cl::NDRange gws_from_window (const Window &window)
Get the global work size given an execution window.
Detailed Description
Interface for the bounding box kernel.
Definition at line 34 of file CLBoundingBoxTransformKernel.h.
Constructor & Destructor Documentation
CLBoundingBoxTransformKernel() [1/3]
CLBoundingBoxTransformKernel ()
Default constructor.
Definition at line 85 of file CLBoundingBoxTransformKernel.cpp.
References arm_compute::ELEMENTWISE.
     : _boxes(nullptr), _pred_boxes(nullptr), _deltas(nullptr)
 {
     _type = CLKernelType::ELEMENTWISE;
 }
CLBoundingBoxTransformKernel() [2/3]
CLBoundingBoxTransformKernel (const CLBoundingBoxTransformKernel &) delete
Prevent instances of this class from being copied (As this class contains pointers)
CLBoundingBoxTransformKernel() [3/3]
CLBoundingBoxTransformKernel (CLBoundingBoxTransformKernel &&) default
Allow instances of this class to be moved.
~CLBoundingBoxTransformKernel()
~CLBoundingBoxTransformKernel () default
Default destructor.
Member Function Documentation
configure() [1/2]
void configure (const ICLTensor * boxes, ICLTensor * pred_boxes, const ICLTensor * deltas, const BoundingBoxTransformInfo & info)
Set the input and output tensors.
Parameters
[in] boxes Source tensor. Bounding box proposals in pixel coordinates. Size(M, 4), format [x1, y1, x2, y2]. Data types supported: QASYMM16/F16/F32.
[out] pred_boxes Destination tensor. Pixel coordinates of the transformed bounding boxes. Size (M, 4*K), format [x1, y1, x2, y2]. Data types supported: Same as input
[in] deltas Bounding box translations and scales. Size (M, 4*K), format [dx, dy, dw, dh], K is the number of classes. Data types supported: QASYMM8 if input is QASYMM16, otherwise same as input
[in] info Contains BoundingBox operation information described in BoundingBoxTransformInfo.
Note
Only single image prediction is supported. Height and Width (and scale) of the image will be contained in the BoundingBoxTransformInfo struct.
Definition at line 91 of file CLBoundingBoxTransformKernel.cpp.
References CLKernelLibrary::get().
 {
     configure(CLKernelLibrary::get().get_compile_context(), boxes, pred_boxes, deltas, info);
 }
configure() [2/2]
void configure (const CLCompileContext & compile_context, const ICLTensor * boxes, ICLTensor * pred_boxes, const ICLTensor * deltas, const BoundingBoxTransformInfo & info)
Set the input and output tensors.
Parameters
[in] compile_context The compile context to be used.
[in] boxes Source tensor. Bounding box proposals in pixel coordinates. Size(M, 4), format [x1, y1, x2, y2]. Data types supported: QASYMM16/F16/F32.
[out] pred_boxes Destination tensor. Pixel coordinates of the transformed bounding boxes. Size (M, 4*K), format [x1, y1, x2, y2]. Data types supported: Same as input
[in] deltas Bounding box translations and scales. Size (M, 4*K), format [dx, dy, dw, dh], K is the number of classes. Data types supported: QASYMM8 if input is QASYMM16, otherwise same as input
[in] info Contains BoundingBox operation information described in BoundingBoxTransformInfo.
Note
Only single image prediction is supported. Height and Width (and scale) of the image will be contained in the BoundingBoxTransformInfo struct.
Definition at line 96 of file CLBoundingBoxTransformKernel.cpp.
References CLBuildOptions::add_option(), BoundingBoxTransformInfo::apply_scale(), ARM_COMPUTE_ERROR_ON, ARM_COMPUTE_ERROR_ON_NULLPTR, ARM_COMPUTE_ERROR_THROW_ON, arm_compute::auto_init_if_empty(), BoundingBoxTransformInfo::bbox_xform_clip(), arm_compute::calculate_max_window(), ICloneable< T >::clone(), BoundingBoxTransformInfo::correct_transform_coords(), arm_compute::create_kernel(), ITensorInfo::data_type(), arm_compute::float_to_string_with_full_precision(), arm_compute::get_cl_type_from_data_type(), arm_compute::get_padding_info(), arm_compute::has_padding_changed(), BoundingBoxTransformInfo::img_height(), BoundingBoxTransformInfo::img_width(), ITensor::info(), arm_compute::test::validation::info, arm_compute::is_data_type_quantized(), kernel_name, num_elems_processed_per_iteration, UniformQuantizationInfo::offset, ITensorInfo::quantization_info(), UniformQuantizationInfo::scale, BoundingBoxTransformInfo::scale(), arm_compute::support::cpp11::to_string(), QuantizationInfo::uniform(), and BoundingBoxTransformInfo::weights().
 {
     ARM_COMPUTE_ERROR_ON_NULLPTR(boxes, pred_boxes, deltas);
     auto padding_info = get_padding_info({ boxes, pred_boxes, deltas });
     auto_init_if_empty(*pred_boxes->info(), deltas->info()->clone()->set_data_type(boxes->info()->data_type()).set_quantization_info(boxes->info()->quantization_info()));
     ARM_COMPUTE_ERROR_THROW_ON(validate_arguments(boxes->info(), pred_boxes->info(), deltas->info(), info));
     // Set instance variables
     _boxes      = boxes;
     _pred_boxes = pred_boxes;
     _deltas     = deltas;
     // Get image height and widht (rescaled)
     const int img_h = floor(info.img_height() / info.scale() + 0.5f);
     const int img_w = floor(info.img_width() / info.scale() + 0.5f);
     const bool is_quantized = is_data_type_quantized(boxes->info()->data_type());
     // Set build options
     CLBuildOptions build_opts;
     build_opts.add_option("-DDATA_TYPE=" + get_cl_type_from_data_type(boxes->info()->data_type()));
     build_opts.add_option("-DWEIGHT_X=" + float_to_string_with_full_precision(info.weights()[0]));
     build_opts.add_option("-DWEIGHT_Y=" + float_to_string_with_full_precision(info.weights()[1]));
     build_opts.add_option("-DWEIGHT_W=" + float_to_string_with_full_precision(info.weights()[2]));
     build_opts.add_option("-DWEIGHT_H=" + float_to_string_with_full_precision(info.weights()[3]));
     build_opts.add_option("-DBBOX_XFORM_CLIP=" + float_to_string_with_full_precision(info.bbox_xform_clip()));
     build_opts.add_option("-DIMG_WIDTH=" + support::cpp11::to_string(img_w));
     build_opts.add_option("-DIMG_HEIGHT=" + support::cpp11::to_string(img_h));
     build_opts.add_option("-DBOX_FIELDS=" + support::cpp11::to_string(4));
     build_opts.add_option("-DSCALE_BEFORE=" + float_to_string_with_full_precision(info.scale()));
     build_opts.add_option_if(info.apply_scale(), "-DSCALE_AFTER=" + float_to_string_with_full_precision(info.scale()));
     build_opts.add_option_if(info.correct_transform_coords(), "-DOFFSET=1");
     if(is_quantized)
     {
         build_opts.add_option("-DDATA_TYPE_DELTAS=" + get_cl_type_from_data_type(deltas->info()->data_type()));
         const UniformQuantizationInfo boxes_qinfo      = boxes->info()->quantization_info().uniform();
         const UniformQuantizationInfo deltas_qinfo     = deltas->info()->quantization_info().uniform();
         const UniformQuantizationInfo pred_boxes_qinfo = pred_boxes->info()->quantization_info().uniform();
         build_opts.add_option("-DOFFSET_BOXES=" + float_to_string_with_full_precision(boxes_qinfo.offset));
         build_opts.add_option("-DSCALE_BOXES=" + float_to_string_with_full_precision(boxes_qinfo.scale));
         build_opts.add_option("-DOFFSET_DELTAS=" + float_to_string_with_full_precision(deltas_qinfo.offset));
         build_opts.add_option("-DSCALE_DELTAS=" + float_to_string_with_full_precision(deltas_qinfo.scale));
         build_opts.add_option("-DOFFSET_PRED_BOXES=" + float_to_string_with_full_precision(pred_boxes_qinfo.offset));
         build_opts.add_option("-DSCALE_PRED_BOXES=" + float_to_string_with_full_precision(pred_boxes_qinfo.scale));
     }
     // Create kernel
     const std::string kernel_name = (is_quantized) ? "bounding_box_transform_quantized" : "bounding_box_transform";
     _kernel                       = create_kernel(compile_context, kernel_name, build_opts.options());
     // Since the number of columns is a multiple of 4 by definition, we don't need to pad the tensor
     const unsigned int num_elems_processed_per_iteration = 4;
     Window             win                               = calculate_max_window(*deltas->info(), Steps(num_elems_processed_per_iteration));
     ICLKernel::configure_internal(win);
     ARM_COMPUTE_ERROR_ON(has_padding_changed(padding_info));
 }
operator=() [1/2]
CLBoundingBoxTransformKernel& operator= (const CLBoundingBoxTransformKernel &) delete
Prevent instances of this class from being copied (As this class contains pointers)
operator=() [2/2]
CLBoundingBoxTransformKernel& operator= (CLBoundingBoxTransformKernel &&) default
Allow instances of this class to be moved.
run()
void run (const Window & window, cl::CommandQueue & queue) override virtual
Enqueue the OpenCL kernel to process the given window on the passed OpenCL command queue.
Note
The queue is not flushed by this method, and therefore the kernel will not have been executed by the time this method returns.
Parameters
[in] window Region on which to execute the kernel. (Must be a valid region of the window returned by window()).
[in,out] queue Command queue on which to enqueue the kernel.
Reimplemented from ICLKernel.
Definition at line 161 of file CLBoundingBoxTransformKernel.cpp.
References ICLKernel::add_1D_tensor_argument(), ICLKernel::add_2D_tensor_argument(), ARM_COMPUTE_ERROR_ON_INVALID_SUBWINDOW, ARM_COMPUTE_ERROR_ON_UNCONFIGURED_KERNEL, arm_compute::enqueue(), Window::first_slice_window_2D(), ICLKernel::lws_hint(), arm_compute::test::validation::reference::slice(), and IKernel::window().
 {
     ARM_COMPUTE_ERROR_ON_UNCONFIGURED_KERNEL(this);
     ARM_COMPUTE_ERROR_ON_INVALID_SUBWINDOW(IKernel::window(), window);
     Window slice = window.first_slice_window_2D();
     // Set arguments
     unsigned int idx = 0;
     add_1D_tensor_argument(idx, _boxes, slice);
     add_2D_tensor_argument(idx, _pred_boxes, slice);
     add_2D_tensor_argument(idx, _deltas, slice);
     // Note that we don't need to loop over the slices, as we are sure that we are dealing with all 2D tensors
     enqueue(queue, *this, slice, lws_hint());
 }
validate()
Status validate (const ITensorInfo * boxes, const ITensorInfo * pred_boxes, const ITensorInfo * deltas, const BoundingBoxTransformInfo & info) static
Static function to check if given info will lead to a valid configuration of CLBoundingBoxTransform.
Parameters
[in] boxes Source tensor info. Bounding box proposals in pixel coordinates. Size(M, 4), format [x1, y1, x2, y2]. Data types supported: QASYMM16/F16/F32.
[in] pred_boxes Destination tensor info. Pixel coordinates of the transformed bounding boxes. Size (M, 4*K), format [x1, y1, x2, y2]. Data types supported: Same as input
[in] deltas Bounding box translations and scales. Size (M, 4*K), format [dx, dy, dw, dh], K is the number of classes. Data types supported: QASYMM8 if input is QASYMM16, otherwise same as input
[in] info Contains BoundingBox operation information described in BoundingBoxTransformInfo.
Note
Only single image prediction is supported. Height and Width (and scale) of the image will be contained in the BoundingBoxTransformInfo struct.
Returns
a Status
Definition at line 155 of file CLBoundingBoxTransformKernel.cpp.
References ARM_COMPUTE_RETURN_ON_ERROR.
Referenced by CLBoundingBoxTransform::validate(), and CLGenerateProposalsLayer::validate().
 {
     ARM_COMPUTE_RETURN_ON_ERROR(validate_arguments(boxes, pred_boxes, deltas, info));
     return Status{};
 }
The documentation for this class was generated from the following files:
src/core/CL/kernels/CLBoundingBoxTransformKernel.h
src/core/CL/kernels/CLBoundingBoxTransformKernel.cpp