Compute Library: NERemapKernel Class Reference
NERemapKernel Class Reference
Kernel to perform a remap on a tensor.
#include <NERemapKernel.h>
Public Member Functions
const char * name () const override
Name of the kernel.
NERemapKernel ()
Default constructor.
NERemapKernel (const NERemapKernel &)=delete
Prevent instances of this class from being copied (As this class contains pointers)
NERemapKernel & operator= (const NERemapKernel &)=delete
Prevent instances of this class from being copied (As this class contains pointers)
NERemapKernel (NERemapKernel &&)=default
Allow instances of this class to be moved.
NERemapKernel & operator= (NERemapKernel &&)=default
Allow instances of this class to be moved.
~NERemapKernel ()=default
Default destructor.
void configure (const ITensor *input, const ITensor *map_x, const ITensor *map_y, ITensor *output, InterpolationPolicy policy, BorderMode border_mode, uint8_t constant_border_value=0)
Initialize the kernel's input, output and border mode.
void run (const Window &window, const ThreadInfo &info) override
Execute the kernel on the passed window.
Public Member Functions inherited from ICPPKernel
virtual ~ICPPKernel ()=default
Default destructor.
virtual void run_nd (const Window &window, const ThreadInfo &info, const Window &thread_locator)
legacy compatibility layer for implemantions which do not support thread_locator In these cases we simply narrow the interface down the legacy version
virtual void run_op (ITensorPack &tensors, const Window &window, const ThreadInfo &info)
Execute the kernel on the passed window.
Public Member Functions inherited from IKernel
IKernel ()
Constructor.
virtual ~IKernel ()=default
Destructor.
virtual bool is_parallelisable () const
Indicates whether or not the kernel is parallelisable.
virtual BorderSize border_size () const
The size of the border for that kernel.
const Window & window () const
The maximum window the kernel can be executed on.
bool is_window_configured () const
Function to check if the embedded window of this kernel has been configured.
Detailed Description
Kernel to perform a remap on a tensor.
Definition at line 35 of file NERemapKernel.h.
Constructor & Destructor Documentation
NERemapKernel() [1/3]
NERemapKernel ()
Default constructor.
Definition at line 117 of file NERemapKernel.cpp.
References arm_compute::UNDEFINED.
Referenced by NERemapKernel::name().
     : _func(nullptr), _input(nullptr), _output(nullptr), _map_x(nullptr), _map_y(nullptr), _border_mode(BorderMode::UNDEFINED), _constant_border_value(0)
 {
 }
NERemapKernel() [2/3]
NERemapKernel (const NERemapKernel &) delete
Prevent instances of this class from being copied (As this class contains pointers)
NERemapKernel() [3/3]
NERemapKernel (NERemapKernel &&) default
Allow instances of this class to be moved.
~NERemapKernel()
~NERemapKernel () default
Default destructor.
Referenced by NERemapKernel::name().
Member Function Documentation
configure()
void configure (const ITensor * input, const ITensor * map_x, const ITensor * map_y, ITensor * output, InterpolationPolicy policy, BorderMode border_mode, uint8_t constant_border_value = 0)
Initialize the kernel's input, output and border mode.
Parameters
[in] input Source tensor. Data type supported: U8.
[in] map_x Map for X coordinates. Data type supported: F32.
[in] map_y Map for Y coordinates. Data type supported: F32.
[out] output Destination tensor. Data types supported: U8. All but the lowest two dimensions must be the same size as in the input tensor, i.e. remapping is only performed within the XY-plane.
[in] policy The interpolation type.
[in] border_mode Border mode to use on the input tensor.
[in] constant_border_value (Optional) Constant value to use for borders if border_mode is set to CONSTANT. Defaults to 0.
Definition at line 122 of file NERemapKernel.cpp.
References ARM_COMPUTE_ERROR, ARM_COMPUTE_ERROR_ON_DATA_TYPE_CHANNEL_NOT_IN, arm_compute::BILINEAR, arm_compute::calculate_max_window(), arm_compute::test::validation::configure(), ITensorInfo::dimension(), Window::DimX, Window::DimY, Window::Dimension::end(), arm_compute::execute_window_loop(), arm_compute::F32, ITensor::info(), arm_compute::test::validation::input, arm_compute::NEAREST_NEIGHBOR, Iterator::ptr(), Window::set(), Window::Dimension::start(), ITensorInfo::strides_in_bytes(), arm_compute::U8, IKernel::window(), and Window::x().
Referenced by NERemapKernel::name().
 {
     ARM_COMPUTE_ERROR_ON_DATA_TYPE_CHANNEL_NOT_IN(input, 1, DataType::U8);
     ARM_COMPUTE_ERROR_ON_DATA_TYPE_CHANNEL_NOT_IN(output, 1, DataType::U8);
     ARM_COMPUTE_ERROR_ON_DATA_TYPE_CHANNEL_NOT_IN(map_x, 1, DataType::F32);
     ARM_COMPUTE_ERROR_ON_DATA_TYPE_CHANNEL_NOT_IN(map_y, 1, DataType::F32);
     _input                 = input;
     _output                = output;
     _map_x                 = map_x;
     _map_y                 = map_y;
     _border_mode           = border_mode;
     _constant_border_value = constant_border_value;
     switch(policy)
     {
         case InterpolationPolicy::NEAREST_NEIGHBOR:
         {
             _func = &NERemapKernel::remap_nearest;
             break;
         }
         case InterpolationPolicy::BILINEAR:
         {
             _func = &NERemapKernel::remap_bilinear;
             break;
         }
         default:
             ARM_COMPUTE_ERROR("Unsupported interpolation mode");
             break;
     }
     // Configure kernel window
     Window win = calculate_max_window(*output->info(), Steps());
     INEKernel::configure(win);
 }
name()
const char* name () const inline override virtual
Name of the kernel.
Returns
Kernel name
Implements ICPPKernel.
Definition at line 38 of file NERemapKernel.h.
References NERemapKernel::configure(), arm_compute::test::validation::info, arm_compute::test::validation::input, NERemapKernel::NERemapKernel(), NERemapKernel::operator=(), NERemapKernel::run(), IKernel::window(), and NERemapKernel::~NERemapKernel().
     {
         return "NERemapKernel";
     }
operator=() [1/2]
NERemapKernel& operator= (const NERemapKernel &) delete
Prevent instances of this class from being copied (As this class contains pointers)
Referenced by NERemapKernel::name().
operator=() [2/2]
NERemapKernel& operator= (NERemapKernel &&) default
Allow instances of this class to be moved.
run()
void run (const Window & window, const ThreadInfo & info) override virtual
Execute the kernel on the passed window.
Warning
If is_parallelisable() returns false then the passed window must be equal to window()
Note
The window has to be a region within the window returned by the window() method
The width of the window has to be a multiple of num_elems_processed_per_iteration().
Parameters
[in] window Region on which to execute the kernel. (Must be a region of the window returned by window())
[in] info Info about executing thread and CPU.
Reimplemented from ICPPKernel.
Definition at line 317 of file NERemapKernel.cpp.
References ARM_COMPUTE_ERROR_ON, ARM_COMPUTE_ERROR_ON_INVALID_SUBWINDOW, ARM_COMPUTE_ERROR_ON_UNCONFIGURED_KERNEL, ARM_COMPUTE_UNUSED, and IKernel::window().
Referenced by NERemapKernel::name().
 {
     ARM_COMPUTE_UNUSED(info);
     ARM_COMPUTE_ERROR_ON_UNCONFIGURED_KERNEL(this);
     ARM_COMPUTE_ERROR_ON_INVALID_SUBWINDOW(INEKernel::window(), window);
     ARM_COMPUTE_ERROR_ON(_func == nullptr);
     (this->*_func)(window);
 }
The documentation for this class was generated from the following files:
src/core/NEON/kernels/NERemapKernel.h
src/core/NEON/kernels/NERemapKernel.cpp