Compute Library: ClPool2d Class Reference
ClPool2d Class Reference
Basic function to simulate a pooling layer with the specified pooling operation.
#include <ClPool2d.h>
Public Member Functions
ClPool2d ()=default
Constructor.
void configure (const ClCompileContext &compile_context, ITensorInfo *src, ITensorInfo *dst, const PoolingLayerInfo &info, ITensorInfo *indices=nullptr)
Configure operator for a given list of arguments.
void run (ITensorPack &tensors) override
Run the kernels contained in the function.
Public Member Functions inherited from ICLOperator
ICLOperator (IRuntimeContext *ctx=nullptr)
Constructor.
ICLOperator (const ICLOperator &)=delete
Prevent instances of this class from being copied (As this class contains pointers)
ICLOperator (ICLOperator &&)=default
Default move constructor.
ICLOperator & operator= (const ICLOperator &)=delete
Prevent instances of this class from being copied (As this class contains pointers)
ICLOperator & operator= (ICLOperator &&)=default
Default move assignment operator.
void prepare (ITensorPack &constants) override
Prepare the function for executing.
MemoryRequirements workspace () const override
Return the memory requirements required by the workspace.
Public Member Functions inherited from IOperator
virtual ~IOperator ()=default
Destructor.
Static Public Member Functions
static Status validate (const ITensorInfo *src, const ITensorInfo *dst, const PoolingLayerInfo &info, const ITensorInfo *indices=nullptr)
Static function to check if given info will lead to a valid configuration.
Detailed Description
Basic function to simulate a pooling layer with the specified pooling operation.
This function calls the following OpenCL kernels:
CLFillBorderKernel (executed if padding size is different from zero)
opencl::ClPool2d
Definition at line 41 of file ClPool2d.h.
Constructor & Destructor Documentation
ClPool2d()
ClPool2d () default
Constructor.
Member Function Documentation
configure()
void configure (const ClCompileContext & compile_context, ITensorInfo * src, ITensorInfo * dst, const PoolingLayerInfo & info, ITensorInfo * indices = nullptr)
Configure operator for a given list of arguments.
Parameters
[in] compile_context The compile context to be used.
[in] src Source tensor info. Data types supported: QASYMM8/QASYMM8_SIGNED/F16/F32.
[out] dst Destination tensor info. Data type supported: same as src
[in] info Pooling layer parameters.
[out] indices (optional) The indices info of the maximal values. Data type supported: U32.
Definition at line 36 of file ClPool2d.cpp.
References ARM_COMPUTE_ERROR, ARM_COMPUTE_ERROR_ON_NULLPTR, arm_compute::test::validation::b, arm_compute::CONSTANT, arm_compute::test::validation::data_layout, ITensorInfo::data_layout(), PoolingLayerInfo::data_layout, arm_compute::test::validation::data_type, ITensorInfo::data_type(), PoolingLayerInfo::exclude_padding, CLScheduler::get(), arm_compute::get_min_max(), arm_compute::is_data_type_quantized(), arm_compute::is_data_type_quantized_asymmetric(), arm_compute::support::cpp11::lowest(), arm_compute::MAX, arm_compute::NCHW, arm_compute::NHWC, PoolingLayerInfo::pool_type, ITensorInfo::quantization_info(), arm_compute::REPLICATE, CLScheduler::tune_kernel_static(), and arm_compute::UNKNOWN.
 {
     ARM_COMPUTE_ERROR_ON_NULLPTR(src);
     // Configure pooling kernel
     auto k = std::make_unique<kernels::ClPool2dKernel>();
     k->set_target(CLScheduler::get().target());
     k->configure(compile_context, src, dst, info, indices);
     _pooling = std::move(k);
     const DataType data_type = src->data_type();
     // Configure border depending on operation required (quantize border in case of asymmetric data_type)
     BorderMode border_mode{};
     PixelValue pixel_value(0.f);
     if(is_data_type_quantized_asymmetric(data_type) && !info.exclude_padding)
     {
         pixel_value = PixelValue(0, data_type, src->quantization_info());
     }
     // Data layout
     const auto data_layout = info.data_layout == DataLayout::UNKNOWN ? src->data_layout() : info.data_layout;
     switch(data_layout)
     {
         case DataLayout::NCHW:
             border_mode = (PoolingType::MAX == info.pool_type) ? BorderMode::REPLICATE : BorderMode::CONSTANT;
             break;
         case DataLayout::NHWC:
             border_mode = BorderMode::CONSTANT;
             if(PoolingType::MAX == info.pool_type)
             {
                 if(is_data_type_quantized(data_type))
                 {
                     std::tie(pixel_value, std::ignore) = get_min_max(data_type);
                 }
                 else
                 {
                     pixel_value = PixelValue(std::numeric_limits<float>::lowest());
                 }
             }
             break;
         default:
             ARM_COMPUTE_ERROR("Data layout not supported");
     }
     auto b = std::make_unique<CLFillBorderKernel>();
     b->configure(compile_context, src, _pooling->border_size(), border_mode, pixel_value);
     _border_handler = std::move(b);
     // Tune kernels
     CLScheduler::get().tune_kernel_static(*_pooling);
 }
run()
void run (ITensorPack & tensors) override virtual
Run the kernels contained in the function.
Parameters
[in] tensors Vector that contains the tensors to operate on.
Reimplemented from ICLOperator.
Definition at line 93 of file ClPool2d.cpp.
References ARM_COMPUTE_ERROR_ON_MSG, ITensorPack::empty(), CLScheduler::enqueue_op(), and CLScheduler::get().
 {
     ARM_COMPUTE_ERROR_ON_MSG(tensors.empty(), "No inputs provided");
     CLScheduler::get().enqueue_op(*_border_handler.get(), tensors, false);
     CLScheduler::get().enqueue_op(*_pooling.get(), tensors, false);
 }
validate()
Status validate (const ITensorInfo * src, const ITensorInfo * dst, const PoolingLayerInfo & info, const ITensorInfo * indices = nullptr) static
Static function to check if given info will lead to a valid configuration.
Similar to ClPool2d::configure()
Returns
a status
Definition at line 88 of file ClPool2d.cpp.
References ClPool2dKernel::validate().
Referenced by CLPoolingLayer::validate().
 {
     return kernels::ClPool2dKernel::validate(src, dst, info, indices);
 }
The documentation for this class was generated from the following files:
src/runtime/gpu/cl/operators/ClPool2d.h
src/runtime/gpu/cl/operators/ClPool2d.cpp