Compute Library: NEStridedSlice Class Reference
NEStridedSlice Class Reference
Basic function to run NEStridedSliceKernel.
#include <NEStridedSlice.h>
Public Member Functions
NEStridedSlice ()
Default Constructor.
~NEStridedSlice ()
Default Destructor.
NEStridedSlice (const NEStridedSlice &)=delete
Prevent instances of this class from being copied (As this class contains pointers)
NEStridedSlice (NEStridedSlice &&)
Default move constructor.
NEStridedSlice & operator= (const NEStridedSlice &)=delete
Prevent instances of this class from being copied (As this class contains pointers)
NEStridedSlice & operator= (NEStridedSlice &&)
Default move assignment operator.
void configure (const ITensor *input, ITensor *output, const Coordinates &starts, const Coordinates &ends, const BiStrides &strides, int32_t begin_mask=0, int32_t end_mask=0, int32_t shrink_axis_mask=0)
Configure kernel.
void run () override
Run the kernels contained in the function.
Public Member Functions inherited from IFunction
virtual ~IFunction ()=default
Destructor.
virtual void prepare ()
Prepare the function for executing.
Static Public Member Functions
static Status validate (const ITensorInfo *input, const ITensorInfo *output, const Coordinates &starts, const Coordinates &ends, const BiStrides &strides, int32_t begin_mask=0, int32_t end_mask=0, int32_t shrink_axis_mask=0)
Static function to check if given info will lead to a valid configuration of NEStridedSlice.
Detailed Description
Basic function to run NEStridedSliceKernel.
Definition at line 36 of file NEStridedSlice.h.
Constructor & Destructor Documentation
NEStridedSlice() [1/3]
NEStridedSlice ()
Default Constructor.
Definition at line 58 of file NEStridedSlice.cpp.
References NEStridedSlice::operator=(), and NEStridedSlice::~NEStridedSlice().
     : _impl(std::make_unique<Impl>())
 {
 }
~NEStridedSlice()
~NEStridedSlice () default
Default Destructor.
Referenced by NEStridedSlice::NEStridedSlice().
NEStridedSlice() [2/3]
NEStridedSlice (const NEStridedSlice &) delete
Prevent instances of this class from being copied (As this class contains pointers)
NEStridedSlice() [3/3]
NEStridedSlice (NEStridedSlice &&) default
Default move constructor.
Member Function Documentation
configure()
void configure (const ITensor * input, ITensor * output, const Coordinates & starts, const Coordinates & ends, const BiStrides & strides, int32_t begin_mask = 0, int32_t end_mask = 0, int32_t shrink_axis_mask = 0)
Configure kernel.
Valid data layouts:
All
Valid data type configurations:
src dst
All All
Note
Supported tensor rank: up to 4
Parameters
[in] input Source tensor. Data type supported: All
[out] output Destination tensor. Data type supported: Same as input
[in] starts The starts of the dimensions of the input tensor to be sliced. The length must be of rank(input).
[in] ends The ends of the dimensions of the input tensor to be sliced. The length must be of rank(input).
[in] strides The strides of the dimensions of the input tensor to be sliced. The length must be of rank(input).
[in] begin_mask (Optional) If the ith bit of begin_mask is set, starts[i] is ignored and the fullest possible range in that dimension is used instead.
[in] end_mask (Optional) If the ith bit of end_mask is set, ends[i] is ignored and the fullest possible range in that dimension is used instead.
[in] shrink_axis_mask (Optional) If the ith bit of shrink_axis_mask is set, it implies that the ith specification shrinks the dimensionality by 1. A slice of size 1 starting from starts[i] in the dimension must be preserved.
Definition at line 66 of file NEStridedSlice.cpp.
References ITensor::info(), and arm_compute::test::validation::input.
 {
     _impl->src = input;
     _impl->dst = output;
     _impl->op  = std::make_unique<experimental::NEStridedSlice>();
     _impl->op->configure(input->info(), output->info(), starts, ends, strides, begin_mask, end_mask, shrink_axis_mask);
 }
operator=() [1/2]
NEStridedSlice& operator= (const NEStridedSlice &) delete
Prevent instances of this class from being copied (As this class contains pointers)
Referenced by NEStridedSlice::NEStridedSlice().
operator=() [2/2]
NEStridedSlice & operator= (NEStridedSlice &&) default
Default move assignment operator.
run()
void run () override virtual
Run the kernels contained in the function.
For CPU kernels:
Multi-threading is used for the kernels which are parallelisable.
By default std::thread::hardware_concurrency() threads are used.
Note
CPPScheduler::set_num_threads() can be used to manually set the number of threads
For OpenCL kernels:
All the kernels are enqueued on the queue associated with CLScheduler.
The queue is then flushed.
Note
The function will not block until the kernels are executed. It is the user's responsibility to wait.
Will call prepare() on first run if hasn't been done
Implements IFunction.
Definition at line 76 of file NEStridedSlice.cpp.
References arm_compute::ACL_DST, arm_compute::ACL_SRC, ITensorPack::add_tensor(), and arm_compute::test::validation::pack.
 {
     ITensorPack pack;
     pack.add_tensor(TensorType::ACL_SRC, _impl->src);
     pack.add_tensor(TensorType::ACL_DST, _impl->dst);
     _impl->op->run(pack);
 }
validate()
Status validate (const ITensorInfo * input, const ITensorInfo * output, const Coordinates & starts, const Coordinates & ends, const BiStrides & strides, int32_t begin_mask = 0, int32_t end_mask = 0, int32_t shrink_axis_mask = 0) static
Static function to check if given info will lead to a valid configuration of NEStridedSlice.
Note
Supported tensor rank: up to 4
Parameters
[in] input Source tensor info. Data type supported: All
[in] output Destination tensor info. Data type supported: Same as input
[in] starts The starts of the dimensions of the input tensor to be sliced. The length must be of rank(input).
[in] ends The ends of the dimensions of the input tensor to be sliced. The length must be of rank(input).
[in] strides The strides of the dimensions of the input tensor to be sliced. The length must be of rank(input).
[in] begin_mask (Optional) If the ith bit of begin_mask is set, starts[i] is ignored and the fullest possible range in that dimension is used instead.
[in] end_mask (Optional) If the ith bit of end_mask is set, ends[i] is ignored and the fullest possible range in that dimension is used instead.
[in] shrink_axis_mask (Optional) If the ith bit of shrink_axis_mask is set, it implies that the ith specification shrinks the dimensionality by 1. A slice of size 1 starting from starts[i] in the dimension must be preserved.
Definition at line 84 of file NEStridedSlice.cpp.
References NEStridedSlice::validate().
Referenced by NEUnstack::validate().
 {
     return experimental::NEStridedSlice::validate(input, output, starts, ends, strides, begin_mask, end_mask, shrink_axis_mask);
 }
The documentation for this class was generated from the following files:
arm_compute/runtime/NEON/functions/NEStridedSlice.h
src/runtime/NEON/functions/NEStridedSlice.cpp