Compute Library: DepthwiseDepthfirstQuantized< strategy > Class Template Reference
DepthwiseDepthfirstQuantized< strategy > Class Template Reference
#include <depthwise_depthfirst_quantized.hpp>
Public Member Functions
DepthwiseDepthfirstQuantized (const DepthwiseArgs &args, const arm_gemm::Requantize32 &qp)
DepthwiseDepthfirstQuantized (DepthwiseDepthfirstQuantized &)=delete
DepthwiseDepthfirstQuantized & operator= (DepthwiseDepthfirstQuantized &)=delete
size_t get_storage_size (void) const override
void pack_parameters (void *buffer, const void *const bias, const void *weights, size_t ld_weight_col, size_t ld_weight_row) override
size_t get_working_size (const unsigned int n_threads, const unsigned int n_channels) const override
void execute (const unsigned int batches, const unsigned int input_height, const unsigned int input_width, const unsigned int input_channels, const PaddingValues &padding, const void *const _input, const size_t ld_input_col, const size_t ld_input_row, const size_t ld_input_batch, const void *const parameters, const unsigned int output_height, const unsigned int output_width, void *const _output, const size_t ld_output_col, const size_t ld_output_row, const size_t ld_output_batch, void *_working_space, const unsigned int thread_id, const unsigned int n_threads) const override
Detailed Description
template<class strategy>
class arm_conv::depthwise::DepthwiseDepthfirstQuantized< strategy >
Definition at line 109 of file depthwise_depthfirst_quantized.hpp.
Constructor & Destructor Documentation
DepthwiseDepthfirstQuantized() [1/2]
DepthwiseDepthfirstQuantized (const DepthwiseArgs & args, const arm_gemm::Requantize32 & qp) inline
Definition at line 166 of file depthwise_depthfirst_quantized.hpp.
References DepthwiseDepthfirstQuantized< strategy >::operator=().
     : DepthwiseCommon<TInput, TWeight, TOutput>(args), m_qp(qp)
   {
   }
DepthwiseDepthfirstQuantized() [2/2]
DepthwiseDepthfirstQuantized (DepthwiseDepthfirstQuantized< strategy > &) delete
Member Function Documentation
execute()
void execute (const unsigned int batches, const unsigned int input_height, const unsigned int input_width, const unsigned int input_channels, const PaddingValues & padding, const void *const _input, const size_t ld_input_col, const size_t ld_input_row, const size_t ld_input_batch, const void *const parameters, const unsigned int output_height, const unsigned int output_width, void *const _output, const size_t ld_output_col, const size_t ld_output_row, const size_t ld_output_batch, void * _working_space, const unsigned int thread_id, const unsigned int n_threads) const inline override
Definition at line 210 of file depthwise_depthfirst_quantized.hpp.
References Requantize32::a_offset, batches, Requantize32::bias, DepthwiseDepthfirstQuantized< strategy >::get_working_size(), arm_gemm::iceildiv(), Requantize32::per_channel_muls, Requantize32::per_channel_requant, Requantize32::per_channel_right_shifts, Requantize32::per_layer_mul, and Requantize32::per_layer_right_shift.
   {
     strategy strat(this->m_args.cpu_info);
 #ifdef CYCLE_PROFILING
     arm_gemm::profiler prof;
 #endif
     // Get a unified API for the kernel function
     auto kernel = get_unified_kernel<TInput, TWeight, TOutput>(strat.kernel);
     // Determine what portion of the work to do.
     const unsigned int n_rows_per_thread = arm_gemm::iceildiv(output_height, n_threads);
     const int start_out_height = std::min(thread_id * n_rows_per_thread, output_height);
     const int end_out_height = std::min(start_out_height + n_rows_per_thread, output_height);
     // Cast input and output pointers into the right types
     const TInput *const inptr = static_cast<const TInput *>(_input);
     TOutput *const outptr = static_cast<TOutput *>(_output);
     // Create an array for the input pointers
     const TInput * _inptr_array[strategy::input_rows * strategy::input_cols];
     const TInput **const inptr_array = _inptr_array;
     // Create an array for the output pointers
     TOutput * _outptr_array[strategy::output_rows * strategy::output_cols];
     TOutput **const outptr_array = _outptr_array;
     // Allocate portions of the working space
     uint8_t *working_space = static_cast<uint8_t *>(_working_space) + get_working_size(thread_id, input_channels);
     TOutput *const output_buffer = reinterpret_cast<TOutput *>(working_space);
     working_space += sizeof_output_buffer(input_channels * this->m_args.channel_multiplier);
     TInput *const input_buffer = reinterpret_cast<TInput *>(working_space);
     working_space += sizeof_input_buffer(input_channels);
     const int32_t *const bias_ptr = (m_qp.bias == nullptr) ? reinterpret_cast<int32_t *>(working_space)
                                                            : m_qp.bias;
     working_space += sizeof_bias_buffer(input_channels * this->m_args.channel_multiplier);
     const int32_t *const requant_mul_vec = !m_qp.per_channel_requant ? reinterpret_cast<int32_t *>(working_space)
                                                                      : m_qp.per_channel_muls;
     working_space += sizeof_requant_mul_buffer(input_channels * this->m_args.channel_multiplier);
     const int32_t *const requant_shift_vec = !m_qp.per_channel_requant ? reinterpret_cast<int32_t *>(working_space)
                                                                        : m_qp.per_channel_right_shifts;
     if (strategy_requires_unravelled_bias_and_quant_params<strategy>())
     {
       // Initialise the bias buffer
       if (m_qp.bias == nullptr)
       {
         for (unsigned int c = 0; c < input_channels * this->m_args.channel_multiplier; c++)
         {
           const_cast<int32_t *>(bias_ptr)[c] = 0;
         }
       }
       // Initialise the requantisation parameters
       if (!m_qp.per_channel_requant)
       {
         for (unsigned int c = 0; c < input_channels * this->m_args.channel_multiplier; c++)
         {
           const_cast<int32_t *>(requant_mul_vec)[c] = m_qp.per_layer_mul;
           const_cast<int32_t *>(requant_shift_vec)[c] = m_qp.per_layer_right_shift;
         }
       }
     }
     // Initialise the input buffer
     for (unsigned int c = 0; c < input_channels; c++)
     {
       input_buffer[c] = static_cast<TInput>(m_qp.a_offset);
     }
     // For each output tile, construct the requisite set of pointers and call
     // into the kernel.
     for (unsigned int batch = 0; batch < batches; batch++)
     {
       // Get batch pointers
       const auto inptr_batch = inptr + batch * ld_input_batch;
       const auto outptr_batch = outptr + batch * ld_output_batch;
       for (int start_out_i = start_out_height;
            start_out_i < end_out_height;
            start_out_i += static_cast<int>(strategy::output_rows))
       {
         const int end_out_i = start_out_i + strategy::output_rows;
         const int start_in_i = start_out_i * strategy::stride_rows - padding.top;
         const int end_in_i = start_in_i + strategy::input_rows;
         // Compute top/bottom padding
         const auto pad_top = static_cast<unsigned int>(-std::min(start_in_i, 0));
         const auto pad_bottom = static_cast<unsigned int>(-std::min(static_cast<int>(input_height) - end_in_i, 0));
         const unsigned int valid_output_rows = std::min(
           end_out_i - start_out_i,
           static_cast<int>(output_height) - start_out_i
         );
         // Fill the input pointer array with padding values
         for (auto index = 0u; index < strategy::input_rows * strategy::input_cols; index++)
         {
           inptr_array[index] = input_buffer;
         }
         for (int start_out_j = 0; start_out_j < static_cast<int>(output_width);)
         {
           const int start_in_j = start_out_j * strategy::stride_cols - this->m_args.padding.left;
           const int pad_left = -std::min(0, start_in_j);
           const int end_out_j = start_out_j + strategy::output_cols;
           const int end_in_j = start_in_j + strategy::input_cols;
           const auto pad_right = static_cast<unsigned int>(-std::min(static_cast<int>(input_width) - end_in_j, 0));
           const unsigned int valid_output_cols = std::min(
             end_out_j - start_out_j,
             static_cast<int>(output_width) - start_out_j
           );
           // Construct the input pointer array - fill the array with pointers to
           // the input buffer and then fill in the required values.
           for (auto i = pad_top; i < strategy::input_rows - pad_bottom; i++)
           {
             // Can skip over the left padding because we will have either the
             // same or less than the previous tile.
             unsigned int j = pad_left;
             const TInput *colptr = inptr_batch + (start_in_i + i) * ld_input_row + (start_in_j + j) * ld_input_col;
             const TInput **ptrs = inptr_array + i * strategy::input_cols + j;
             for (; j < strategy::input_cols - pad_right; j++)
             {
               *(ptrs++) = colptr;
               colptr += ld_input_col;
             }
             for (; j < strategy::input_cols; j++)
             {
               *(ptrs++) = input_buffer;
             }
           }
           // Construct the output pointer array.
           TOutput **outptr_pos = outptr_array;
           for (auto i = 0u; i < valid_output_rows; i++)
           {
             unsigned int j = 0u;
             TOutput *colptr = outptr_batch + (start_out_i + i) * ld_output_row + start_out_j * ld_output_col;
             for (; j < valid_output_cols; j++)
             {
               *(outptr_pos++) = colptr;
                colptr += ld_output_col;
             }
             for (; j < strategy::output_cols; j++)
             {
               *(outptr_pos++) = output_buffer;
             }
           }
           for (auto i = valid_output_rows; i < strategy::output_rows; i++)
           {
             for (auto j = 0u; j < strategy::output_cols; j++)
             {
               *(outptr_pos++) = output_buffer;
             }
           }
           start_out_j += strategy::output_cols;
 #ifdef CYCLE_PROFILING
           // TODO Work number
           auto p = prof.ScopedProfiler(PROFILE_KERNEL, (unsigned long)(strategy::output_rows * strategy::output_cols * this->m_args.kernel_rows * this->m_args.kernel_cols));
 #endif
           kernel(
             this->m_args.input_channels,
             inptr_array,
             reinterpret_cast<const TWeight *>(parameters),
             bias_ptr, m_qp, requant_mul_vec, requant_shift_vec,
             outptr_array
           );
         }
       }
     }
   }
get_storage_size()
size_t get_storage_size (void) const inline override
Definition at line 174 of file depthwise_depthfirst_quantized.hpp.
   {
     return strategy::get_packed_size(this->m_args);
   }
get_working_size()
size_t get_working_size (const unsigned int n_threads, const unsigned int n_channels) const inline override
Definition at line 197 of file depthwise_depthfirst_quantized.hpp.
Referenced by DepthwiseDepthfirstQuantized< strategy >::execute().
   {
     const unsigned int n_output_channels = n_channels * this->m_args.channel_multiplier;
     return n_threads * (
       sizeof_output_buffer(n_output_channels) +
       sizeof_input_buffer(n_channels) +
       sizeof_bias_buffer(n_channels) +
       sizeof_requant_mul_buffer(n_channels) +
       sizeof_requant_shift_buffer(n_channels)
     );
   }
operator=()
DepthwiseDepthfirstQuantized& operator= (DepthwiseDepthfirstQuantized< strategy > &) delete
Referenced by DepthwiseDepthfirstQuantized< strategy >::DepthwiseDepthfirstQuantized().
pack_parameters()
void pack_parameters (void * buffer, const void *const bias, const void * weights, size_t ld_weight_col, size_t ld_weight_row) inline override
Definition at line 179 of file depthwise_depthfirst_quantized.hpp.
References Requantize32::bias.
   {
     if (strategy_requires_unravelled_bias_and_quant_params<strategy>())
     {
       m_qp.bias = static_cast<const int32_t *>(bias);
     }
     get_unified_packer<TWeight>(strategy::pack_parameters)(
       this->m_args.input_channels,
       buffer,
       static_cast<const int32_t *>(bias),
       reinterpret_cast<const TWeight *>(weights),
       m_qp,
       ld_weight_col,
       ld_weight_row
     );
   }
The documentation for this class was generated from the following file:
src/core/NEON/kernels/arm_conv/depthwise/depthwise_depthfirst_quantized.hpp