Compute Library: CLPoolingLayer Class Reference
CLPoolingLayer Class Reference
Basic function to run opencl::ClPool2d.
#include <CLPoolingLayer.h>
Public Member Functions
CLPoolingLayer ()
Default Constructor.
~CLPoolingLayer ()
Default Destructor.
CLPoolingLayer (const CLPoolingLayer &)=delete
Prevent instances of this class from being copied (As this class contains pointers)
CLPoolingLayer (CLPoolingLayer &&)=default
Default move constructor.
CLPoolingLayer & operator= (const CLPoolingLayer &)=delete
Prevent instances of this class from being copied (As this class contains pointers)
CLPoolingLayer & operator= (CLPoolingLayer &&)=default
Default move assignment operator.
void configure (ICLTensor *input, ICLTensor *output, const PoolingLayerInfo &pool_info, ICLTensor *indices=nullptr)
Set the input and output tensors.
void configure (const CLCompileContext &compile_context, ICLTensor *input, ICLTensor *output, const PoolingLayerInfo &pool_info, ICLTensor *indices=nullptr)
Set the input and output tensors.
void run () override
Run the kernels contained in the function.
Public Member Functions inherited from IFunction
virtual ~IFunction ()=default
Destructor.
virtual void prepare ()
Prepare the function for executing.
Static Public Member Functions
static Status validate (const ITensorInfo *input, const ITensorInfo *output, const PoolingLayerInfo &pool_info, const ITensorInfo *indices=nullptr)
Static function to check if given info will lead to a valid configuration of CLPoolingLayer.
Detailed Description
Basic function to run opencl::ClPool2d.
Definition at line 40 of file CLPoolingLayer.h.
Constructor & Destructor Documentation
CLPoolingLayer() [1/3]
CLPoolingLayer ()
Default Constructor.
Definition at line 41 of file CLPoolingLayer.cpp.
References CLPoolingLayer::~CLPoolingLayer().
     : _impl(std::make_unique<Impl>())
 {
 }
~CLPoolingLayer()
~CLPoolingLayer () default
Default Destructor.
Referenced by CLPoolingLayer::CLPoolingLayer().
CLPoolingLayer() [2/3]
CLPoolingLayer (const CLPoolingLayer &) delete
Prevent instances of this class from being copied (As this class contains pointers)
CLPoolingLayer() [3/3]
CLPoolingLayer (CLPoolingLayer &&) default
Default move constructor.
Member Function Documentation
configure() [1/2]
void configure (ICLTensor * input, ICLTensor * output, const PoolingLayerInfo & pool_info, ICLTensor * indices = nullptr)
Set the input and output tensors.
Valid data layouts:
NHWC
NCHW
Valid data type configurations:
src dst
QASYMM8 QASYMM8
QASYMM8_SIGNED QASYMM8_SIGNED
F16 F16
F32 F32
Parameters
[in,out] input Source tensor. (Written to only when padding != 0) Data types supported: QASYMM8/QASYMM8_SIGNED/F16/F32.
[out] output Destination tensor. Data types supported: Same as input.
[in] pool_info Contains pooling operation information described in PoolingLayerInfo.
[out] indices (optional) The indices of the maximal values. Data type supported: U32.
Definition at line 47 of file CLPoolingLayer.cpp.
References CLKernelLibrary::get().
 {
     configure(CLKernelLibrary::get().get_compile_context(), input, output, pool_info, indices);
 }
configure() [2/2]
void configure (const CLCompileContext & compile_context, ICLTensor * input, ICLTensor * output, const PoolingLayerInfo & pool_info, ICLTensor * indices = nullptr)
Set the input and output tensors.
Parameters
[in] compile_context The compile context to be used.
[in,out] input Source tensor. (Written to only when padding != 0) Data types supported: QASYMM8/QASYMM8_SIGNED/F16/F32.
[out] output Destination tensor. Data types supported: Same as input.
[in] pool_info Contains pooling operation information described in PoolingLayerInfo.
[out] indices (optional) The indices of the maximal values. Data type supported: U32.
Definition at line 52 of file CLPoolingLayer.cpp.
References ITensor::info(), and arm_compute::test::validation::input.
 {
     _impl->src     = input;
     _impl->dst     = output;
     _impl->indices = indices;
     _impl->op = std::make_unique<opencl::ClPool2d>();
     _impl->op->configure(compile_context, input->info(), output->info(), pool_info, (indices) ? indices->info() : nullptr);
 }
operator=() [1/2]
CLPoolingLayer& operator= (const CLPoolingLayer &) delete
Prevent instances of this class from being copied (As this class contains pointers)
operator=() [2/2]
CLPoolingLayer& operator= (CLPoolingLayer &&) default
Default move assignment operator.
run()
void run () override virtual
Run the kernels contained in the function.
For CPU kernels:
Multi-threading is used for the kernels which are parallelisable.
By default std::thread::hardware_concurrency() threads are used.
Note
CPPScheduler::set_num_threads() can be used to manually set the number of threads
For OpenCL kernels:
All the kernels are enqueued on the queue associated with CLScheduler.
The queue is then flushed.
Note
The function will not block until the kernels are executed. It is the user's responsibility to wait.
Will call prepare() on first run if hasn't been done
Implements IFunction.
Definition at line 67 of file CLPoolingLayer.cpp.
References arm_compute::ACL_DST_0, arm_compute::ACL_DST_1, arm_compute::ACL_SRC, ITensorPack::add_tensor(), and arm_compute::test::validation::pack.
 {
     ITensorPack pack;
     pack.add_tensor(TensorType::ACL_SRC, _impl->src);
     pack.add_tensor(TensorType::ACL_DST_0, _impl->dst);
     pack.add_tensor(TensorType::ACL_DST_1, _impl->indices);
     _impl->op->run(pack);
 }
validate()
Status validate (const ITensorInfo * input, const ITensorInfo * output, const PoolingLayerInfo & pool_info, const ITensorInfo * indices = nullptr) static
Static function to check if given info will lead to a valid configuration of CLPoolingLayer.
Parameters
[in] input Source tensor info. Data types supported: QASYMM8/QASYMM8_SIGNED/F16/F32.
[in] output Destination tensor info. Data types supported: Same as input.
[in] pool_info Contains pooling operation information described in PoolingLayerInfo.
[in] indices (optional) The indices of the maximal values. Data type supported: U32.
Returns
a status
Definition at line 62 of file CLPoolingLayer.cpp.
References ClPool2d::validate().
Referenced by arm_compute::test::validation::DATA_TEST_CASE().
 {
     return opencl::ClPool2d::validate(input, output, pool_info, indices);
 }
The documentation for this class was generated from the following files:
arm_compute/runtime/CL/functions/CLPoolingLayer.h
src/runtime/CL/functions/CLPoolingLayer.cpp