Compute Library: CLInstanceNormalizationLayer Class Reference
CLInstanceNormalizationLayer Class Reference
Basic function to perform a Instance normalization.
#include <CLInstanceNormalizationLayer.h>
Public Member Functions
CLInstanceNormalizationLayer (CLRuntimeContext *ctx=nullptr)
Constructor.
CLInstanceNormalizationLayer (const CLInstanceNormalizationLayer &)=delete
Prevent instances of this class from being copied (As this class contains pointers)
CLInstanceNormalizationLayer (CLInstanceNormalizationLayer &&)=default
Default move constructor.
CLInstanceNormalizationLayer & operator= (const CLInstanceNormalizationLayer &)=delete
Prevent instances of this class from being copied (As this class contains pointers)
CLInstanceNormalizationLayer & operator= (CLInstanceNormalizationLayer &&)=default
Default move assignment operator.
~CLInstanceNormalizationLayer ()
Default destructor.
void configure (ICLTensor *input, ICLTensor *output, float gamma=1.0f, float beta=0.0f, float epsilon=1e-12f, bool use_mixed_precision=true)
Set the input and output tensors.
void configure (const CLCompileContext &compile_context, ICLTensor *input, ICLTensor *output, float gamma=1.0f, float beta=0.0f, float epsilon=1e-12f, bool use_mixed_precision=true)
Set the input and output tensors.
void run () override
Run the kernels contained in the function.
Public Member Functions inherited from IFunction
virtual ~IFunction ()=default
Destructor.
virtual void prepare ()
Prepare the function for executing.
Static Public Member Functions
static Status validate (const ITensorInfo *input, const ITensorInfo *output, float gamma=1.0f, float beta=0.0f, float epsilon=1e-12f, bool use_mixed_precision=true)
Static function to check if given info will lead to a valid configuration of CLInstanceNormalizationLayer.
Detailed Description
Basic function to perform a Instance normalization.
This function runs the following kernels:
CLInstanceNormalizationLayerKernel
Definition at line 46 of file CLInstanceNormalizationLayer.h.
Constructor & Destructor Documentation
CLInstanceNormalizationLayer() [1/3]
CLInstanceNormalizationLayer (CLRuntimeContext * ctx = nullptr)
Constructor.
Parameters
[in] ctx Runtime context to be used by the function
Definition at line 36 of file CLInstanceNormalizationLayer.cpp.
     : _inst_norm_kernel(),
       _mean_var_kernel(),
       _mean_var_tensor(),
       _ctx(ctx)
 {
 }
CLInstanceNormalizationLayer() [2/3]
CLInstanceNormalizationLayer (const CLInstanceNormalizationLayer &) delete
Prevent instances of this class from being copied (As this class contains pointers)
CLInstanceNormalizationLayer() [3/3]
CLInstanceNormalizationLayer (CLInstanceNormalizationLayer &&) default
Default move constructor.
~CLInstanceNormalizationLayer()
~CLInstanceNormalizationLayer ()
Default destructor.
Definition at line 43 of file CLInstanceNormalizationLayer.cpp.
 {
 }
Member Function Documentation
configure() [1/2]
void configure (ICLTensor * input, ICLTensor * output, float gamma = 1.0f, float beta = 0.0f, float epsilon = 1e-12f, bool use_mixed_precision = true)
Set the input and output tensors.
Valid data layouts:
NHWC
NCHW
Valid data type configurations:
src dst
F16 F16
F32 F32
Parameters
[in,out] input Source tensor. In case of output tensor = nullptr this tensor will store the result of the normalization. Data types supported: F16/F32. Data layout supported: NHWC, NCHW
[out] output Destination tensor. Data types and data layouts supported: same as input.
[in] gamma (Optional) The scale scalar value applied to the normalized tensor. Defaults to 1.0
[in] beta (Optional) The offset scalar value applied to the normalized tensor. Defaults to 0.0
[in] epsilon (Optional) Lower bound value for the normalization. Defaults to 1e-12
[in] use_mixed_precision (Optional) Use mixed precision in case of FP16 execution
Definition at line 47 of file CLInstanceNormalizationLayer.cpp.
References CLKernelLibrary::get().
 {
     configure(CLKernelLibrary::get().get_compile_context(), input, output, gamma, beta, epsilon, use_mixed_precision);
 }
configure() [2/2]
void configure (const CLCompileContext & compile_context, ICLTensor * input, ICLTensor * output, float gamma = 1.0f, float beta = 0.0f, float epsilon = 1e-12f, bool use_mixed_precision = true)
Set the input and output tensors.
Parameters
[in] compile_context The compile context to be used.
[in,out] input Source tensor. In case of output tensor = nullptr this tensor will store the result of the normalization. Data types supported: F16/F32. Data layout supported: NHWC, NCHW
[out] output Destination tensor. Data types and data layouts supported: same as input.
[in] gamma (Optional) The scale scalar value applied to the normalized tensor. Defaults to 1.0
[in] beta (Optional) The offset scalar value applied to the normalized tensor. Defaults to 0.0
[in] epsilon (Optional) Lower bound value for the normalization. Defaults to 1e-12
[in] use_mixed_precision (Optional) Use mixed precision in case of FP16 execution
Definition at line 52 of file CLInstanceNormalizationLayer.cpp.
References CLTensorAllocator::allocate(), CLTensor::allocator(), and arm_compute::test::validation::w.
 {
     auto w = std::make_unique<CLComputeMeanVariance>();
     w->configure(compile_context, input, &_mean_var_tensor, use_mixed_precision);
     _mean_var_kernel = std::move(w);
     auto k           = std::make_unique<CLInstanceNormalizationLayerKernel>();
     k->configure(compile_context, input, &_mean_var_tensor, output, InstanceNormalizationLayerKernelInfo(gamma, beta, epsilon, use_mixed_precision));
     _inst_norm_kernel = std::move(k);
     _mean_var_tensor.allocator()->allocate();
 }
operator=() [1/2]
CLInstanceNormalizationLayer& operator= (const CLInstanceNormalizationLayer &) delete
Prevent instances of this class from being copied (As this class contains pointers)
operator=() [2/2]
CLInstanceNormalizationLayer& operator= (CLInstanceNormalizationLayer &&) default
Default move assignment operator.
run()
void run () override virtual
Run the kernels contained in the function.
For CPU kernels:
Multi-threading is used for the kernels which are parallelisable.
By default std::thread::hardware_concurrency() threads are used.
Note
CPPScheduler::set_num_threads() can be used to manually set the number of threads
For OpenCL kernels:
All the kernels are enqueued on the queue associated with CLScheduler.
The queue is then flushed.
Note
The function will not block until the kernels are executed. It is the user's responsibility to wait.
Will call prepare() on first run if hasn't been done
Implements IFunction.
Definition at line 68 of file CLInstanceNormalizationLayer.cpp.
References ARM_COMPUTE_ERROR_ON_MSG, and arm_compute::schedule_kernel_on_ctx().
 {
     ARM_COMPUTE_ERROR_ON_MSG(!_inst_norm_kernel, "The child class didn't set the CL kernel or function isn't configured");
     schedule_kernel_on_ctx(_ctx, _mean_var_kernel.get());
     schedule_kernel_on_ctx(_ctx, _inst_norm_kernel.get());
 }
validate()
Status validate (const ITensorInfo * input, const ITensorInfo * output, float gamma = 1.0f, float beta = 0.0f, float epsilon = 1e-12f, bool use_mixed_precision = true) static
Static function to check if given info will lead to a valid configuration of CLInstanceNormalizationLayer.
Parameters
[in] input Source tensor info. Data types supported: F16/F32. Data layout supported: NHWC, NCHW
[in] output Destination tensor info. Data types and data layouts supported: same as input.
[in] gamma (Optional) The scale scalar value applied to the normalized tensor. Defaults to 1.0
[in] beta (Optional) The offset scalar value applied to the normalized tensor. Defaults to 0.0
[in] epsilon (Optional) Lower bound value for the normalization. Defaults to 1e-12
[in] use_mixed_precision (Optional) Use mixed precision in case of FP16 execution
Returns
a status
Definition at line 63 of file CLInstanceNormalizationLayer.cpp.
References CLInstanceNormalizationLayerKernel::validate().
Referenced by arm_compute::test::validation::DATA_TEST_CASE().
 {
     return CLInstanceNormalizationLayerKernel::validate(input, output, InstanceNormalizationLayerKernelInfo(gamma, beta, epsilon, use_mixed_precision));
 }
The documentation for this class was generated from the following files:
arm_compute/runtime/CL/functions/CLInstanceNormalizationLayer.h
src/runtime/CL/functions/CLInstanceNormalizationLayer.cpp