Compute Library: DepthwiseDepthfirstGenericBase< Strategy, OutputRows, OutputCols > Class Template Reference
DepthwiseDepthfirstGenericBase< Strategy, OutputRows, OutputCols > Class Template Reference
#include <depthwise_depthfirst_generic.hpp>
Public Member Functions
DepthwiseDepthfirstGenericBase (const DepthwiseArgs &args)
DepthwiseDepthfirstGenericBase (DepthwiseDepthfirstGenericBase &)=delete
DepthwiseDepthfirstGenericBase & operator= (DepthwiseDepthfirstGenericBase &)=delete
size_t get_storage_size (void) const override
void pack_parameters (void *_buffer, const void *, const void *_weights, size_t ld_weight_col, size_t ld_weight_row) override
size_t get_working_size (const unsigned int n_threads, const unsigned int n_channels) const override
Detailed Description
template<class Strategy, unsigned OutputRows, unsigned int OutputCols>
class arm_conv::depthwise::DepthwiseDepthfirstGenericBase< Strategy, OutputRows, OutputCols >
Definition at line 39 of file depthwise_depthfirst_generic.hpp.
Constructor & Destructor Documentation
DepthwiseDepthfirstGenericBase() [1/2]
DepthwiseDepthfirstGenericBase (const DepthwiseArgs & args) inline
Definition at line 222 of file depthwise_depthfirst_generic.hpp.
References DepthwiseDepthfirstGenericBase< Strategy, OutputRows, OutputCols >::operator=().
                                                             : DepthwiseCommon<TInput, TWeight, TOutput>(args)
   {
   }
DepthwiseDepthfirstGenericBase() [2/2]
DepthwiseDepthfirstGenericBase (DepthwiseDepthfirstGenericBase< Strategy, OutputRows, OutputCols > &) delete
Member Function Documentation
get_storage_size()
size_t get_storage_size (void) const inline override
Definition at line 229 of file depthwise_depthfirst_generic.hpp.
References arm_gemm::roundup().
   {
     const unsigned int vl = arm_gemm::utils::get_vector_length<TAccum>(Strategy::vl_type);
     const auto rounded_channels = arm_gemm::roundup(this->m_args.input_channels, vl);
     return (this->m_args.kernel_rows * this->m_args.kernel_cols) * rounded_channels * sizeof(TWeight);
   }
get_working_size()
size_t get_working_size (const unsigned int n_threads, const unsigned int n_channels) const inline override
Definition at line 272 of file depthwise_depthfirst_generic.hpp.
   {
     const unsigned int n_output_channels = n_channels * this->m_args.channel_multiplier;
     return n_threads * (sizeof_input_ptr_array() +
                         sizeof_output_buffer(n_output_channels) +
                         sizeof_input_buffer(n_channels));
   }
operator=()
DepthwiseDepthfirstGenericBase& operator= (DepthwiseDepthfirstGenericBase< Strategy, OutputRows, OutputCols > &) delete
Referenced by DepthwiseDepthfirstGeneric< Strategy, OutputRows, OutputCols >::DepthwiseDepthfirstGeneric(), and DepthwiseDepthfirstGenericBase< Strategy, OutputRows, OutputCols >::DepthwiseDepthfirstGenericBase().
pack_parameters()
void pack_parameters (void * _buffer, const void * , const void * _weights, size_t ld_weight_col, size_t ld_weight_row) inline override
Definition at line 236 of file depthwise_depthfirst_generic.hpp.
Referenced by DepthwiseDepthfirstGenericQuantized< Strategy, OutputRows, OutputCols >::pack_parameters().
   {
     // Cast the pointers
     TWeight *buffer = static_cast<TWeight *>(_buffer);
     const TWeight *const weights = static_cast<const TWeight *>(_weights);
     const unsigned int vl = arm_gemm::utils::get_vector_length<TAccum>(Strategy::vl_type);
     ld_weight_col = (ld_weight_col == 0) ? this->m_args.input_channels : ld_weight_col;
     ld_weight_row = (ld_weight_row == 0) ? this->m_args.kernel_cols * ld_weight_col : ld_weight_row;
     for (unsigned int n = 0; n < this->m_args.input_channels; n += vl)
     {
       const unsigned int todo = std::min(vl, this->m_args.input_channels - n);
       // Copy each of the weights in turn
       auto weights_row = weights + n;
       for (unsigned int i = 0; i < this->m_args.kernel_rows; i++)
       {
         auto weights_col = weights_row;
         for (unsigned int j = 0; j < this->m_args.kernel_cols; j++)
         {
           for (unsigned int m = 0; m < todo; m++)
           {
             buffer[m] = weights_col[m];
           }
           buffer += vl;
           weights_col += ld_weight_col;
         }
         weights_row += ld_weight_row;
       }
     }
   }
The documentation for this class was generated from the following file:
src/core/NEON/kernels/arm_conv/depthwise/depthwise_depthfirst_generic.hpp