Compute Library: CLNormalizePlanarYUVLayer Class Reference
CLNormalizePlanarYUVLayer Class Reference
Basic function to run CLNormalizePlanarYUVLayerKernel.
#include <CLNormalizePlanarYUVLayer.h>
Public Member Functions
void configure (const ICLTensor *input, ICLTensor *output, const ICLTensor *mean, const ICLTensor *std)
Set the input and output tensors.
void configure (const CLCompileContext &compile_context, const ICLTensor *input, ICLTensor *output, const ICLTensor *mean, const ICLTensor *std)
Set the input and output tensors.
Public Member Functions inherited from ICLSimpleFunction
ICLSimpleFunction (CLRuntimeContext *ctx=nullptr)
Constructor.
ICLSimpleFunction (const ICLSimpleFunction &)=delete
Prevent instances of this class from being copied (As this class contains pointers)
ICLSimpleFunction (ICLSimpleFunction &&)=default
Default move constructor.
ICLSimpleFunction & operator= (const ICLSimpleFunction &)=delete
Prevent instances of this class from being copied (As this class contains pointers)
ICLSimpleFunction & operator= (ICLSimpleFunction &&)=default
Default move assignment operator.
~ICLSimpleFunction ()
Default destructor.
void run () override final
Run the kernels contained in the function.
Public Member Functions inherited from IFunction
virtual ~IFunction ()=default
Destructor.
virtual void prepare ()
Prepare the function for executing.
Static Public Member Functions
static Status validate (const ITensorInfo *input, const ITensorInfo *output, const ITensorInfo *mean, const ITensorInfo *std)
Static function to check if given info will lead to a valid configuration of CLNormalizePlanarYUVLayer.
Detailed Description
Basic function to run CLNormalizePlanarYUVLayerKernel.
Note
The function simulates a NormalizePlanarYUV layer.
Definition at line 42 of file CLNormalizePlanarYUVLayer.h.
Member Function Documentation
configure() [1/2]
void configure (const ICLTensor * input, ICLTensor * output, const ICLTensor * mean, const ICLTensor * std)
Set the input and output tensors.
Parameters
[in] input Source tensor. 3 lower dimensions represent a single input with dimensions [width, height, channels]. Data types supported: QASYMM8/QASYMM8_SIGNED/F16/F32.
[out] output Destinationfeature tensor. Data type supported: same as input
[in] mean Mean values tensor. 1 dimension with size equal to the number of input channels. Data types supported: Same as input
[in] std Standard deviation values tensor. 1 dimension with size equal to the number of input channels. Data types supported: Same as input
Definition at line 33 of file CLNormalizePlanarYUVLayer.cpp.
References CLKernelLibrary::get().
 {
     configure(CLKernelLibrary::get().get_compile_context(), input, output, mean, std);
 }
configure() [2/2]
void configure (const CLCompileContext & compile_context, const ICLTensor * input, ICLTensor * output, const ICLTensor * mean, const ICLTensor * std)
Set the input and output tensors.
Parameters
[in] compile_context The compile context to be used.
[in] input Source tensor. 3 lower dimensions represent a single input with dimensions [width, height, channels]. Data types supported: QASYMM8/QASYMM8_SIGNED/F16/F32.
[out] output Destinationfeature tensor. Data type supported: same as input
[in] mean Mean values tensor. 1 dimension with size equal to the number of input channels. Data types supported: Same as input
[in] std Standard deviation values tensor. 1 dimension with size equal to the number of input channels. Data types supported: Same as input
Definition at line 38 of file CLNormalizePlanarYUVLayer.cpp.
 {
     auto k = std::make_unique<CLNormalizePlanarYUVLayerKernel>();
     k->configure(compile_context, input, output, mean, std);
     _kernel = std::move(k);
 }
validate()
Status validate (const ITensorInfo * input, const ITensorInfo * output, const ITensorInfo * mean, const ITensorInfo * std) static
Static function to check if given info will lead to a valid configuration of CLNormalizePlanarYUVLayer.
Parameters
[in] input Source tensor info. 3 lower dimensions represent a single input with dimensions [width, height, channels]. Data types supported: QASYMM8/QASYMM8_SIGNED/F16/F32.
[out] output Destination tensor info. Data type supported: same as input
[in] mean Mean values tensor info. 1 dimension with size equal to the number of input channels. Data types supported: Same as input
[in] std Standard deviation values tensor info. 1 dimension with size equal to the number of input channels. Data types supported: Same as input
Returns
a status
Definition at line 45 of file CLNormalizePlanarYUVLayer.cpp.
References CLNormalizePlanarYUVLayerKernel::validate().
Referenced by arm_compute::test::validation::DATA_TEST_CASE().
 {
     return CLNormalizePlanarYUVLayerKernel::validate(input, output, mean, std);
 }
The documentation for this class was generated from the following files:
arm_compute/runtime/CL/functions/CLNormalizePlanarYUVLayer.h
src/runtime/CL/functions/CLNormalizePlanarYUVLayer.cpp