Compute Library: src/core/NEON/kernels/arm_gemm/gemm_interleaved.hpp File Reference
gemm_interleaved.hpp File Reference
#include <algorithm>
#include <cassert>
#include "arm_gemm.hpp"
#include "convolver.hpp"
#include "mergeresults.hpp"
#include "performance_parameters.hpp"
#include "quantized.hpp"
#include "transform.hpp"
#include "utils.hpp"
Data Structures
class GemmInterleaved< strategy, To, Tr, OutputStage, MergeStep, ForceThreadColumns >
Namespaces
arm_gemm
Macros
#define ALLOC_ROUND 64
#define ROUND_UP(x) ((((x) + ALLOC_ROUND-1) / ALLOC_ROUND) * ALLOC_ROUND)
Typedefs
template<typename strategy , typename To , typename Tr , typename OutputStage = Nothing>
using GemmInterleavedNoMerge = GemmInterleaved< strategy, To, Tr, OutputStage, false >
template<typename strategy , typename To , typename Tr >
using GemmInterleavedPretransposedNoMergeQuantizedInline = GemmInterleaved< strategy, To, Tr, Requantize32, false >
template<typename strategy , typename To , typename Tr >
using GemmInterleavedQuantized = GemmInterleaved< strategy, To, Tr, Requantize32 >
Macro Definition Documentation
ALLOC_ROUND
#define ALLOC_ROUND 64
Definition at line 43 of file gemm_interleaved.hpp.
ROUND_UP
#define ROUND_UP (x) ((((x) + ALLOC_ROUND-1) / ALLOC_ROUND) * ALLOC_ROUND)
Definition at line 44 of file gemm_interleaved.hpp.
Variable Documentation
type
decltype(strategy::transforms) typedef type
Definition at line 227 of file gemm_interleaved.hpp.
Referenced by arm_compute::adjust_vec_size(), arm_compute::test::apply(), acl::detail::as_cenum(), arm_compute::cpu::bilinear_neon_scale(), CommonOptions::CommonOptions(), CpuScaleKernel::configure(), CLNormalizationLayerKernel::configure(), arm_compute::detail::convolve_3x3(), arm_compute::test::copy_tensor(), arm_compute::support::cpp11::copysign(), CLFunctionFactory::create(), NEFunctionFactory::create(), ImageLoaderFactory::create(), arm_compute::test::create_tensor(), arm_compute::test::validation::reference::depth_convert(), arm_compute::cpu::elementwise_arithm_op(), arm_compute::cpu::elementwise_arithm_op_broadcast(), PoolingDepthfirst< strategy >::execute(), GemmInterleaved< strategy, To, Tr, OutputStage, MergeStep, ForceThreadColumns >::execute(), AssetsLibrary::fill_boxes(), arm_compute::utils::fill_random_tensor(), arm_compute::test::validation::reference::gemm(), arm_compute::test::validation::reference::gemmlowp_matrix_multiply_core(), arm_compute::utils::get_image_type_from_file(), Framework::get_profiler(), Tensor::import(), TensorInfo::init(), TensorInfo::init_auto_padding(), ITensorV2::is_valid(), arm_compute::test::convolution_3d::detail::is_valid_pixel(), arm_compute::support::cpp11::lowest< bfloat16 >(), arm_compute::support::cpp11::lround(), arm_compute::support::cpp11::nearbyint(), Graph::nodes(), arm_compute::test::validation::reference::normalization_layer(), arm_compute::test::framework::operator &(), compare< AbsoluteTolerance< U > >::operator bool(), compare< RelativeTolerance< U > >::operator bool(), Token::operator==(), arm_compute::test::framework::operator|(), arm_compute::test::framework::operator|=(), arm_compute::permute_strides(), arm_compute::test::validation::reference::pooling_layer_internal(), arm_compute::cpu::poolingMxN_q8_neon_nhwc(), arm_compute::cpu::quantize(), arm_compute::support::cpp11::round(), arm_compute::test::round_half_up(), PassManager::run_type(), arm_compute::utils::cast::saturate_cast(), arm_compute::utils::save_to_npy(), CLCompileContext::set_context(), arm_compute::detail::single_convolve_3x3_dilation(), arm_compute::test::validation::reference::softmax_layer(), arm_compute::test::validation::reference::softmax_layer_generic(), arm_compute::support::cpp11::stoul(), arm_compute::string_from_norm_type(), arm_compute::string_from_pooling_type(), arm_compute::test::sync_if_necessary(), arm_compute::to_string(), arm_compute::support::cpp11::trunc(), NENodeValidator::validate(), CLNodeValidator::validate(), arm_compute::test::validation::validate(), arm_compute::test::validation::validate_wrap(), arm_compute::wrapper::vcvt(), and arm_compute::wrapper::vqmov().