Compute Library: arm_conv::pooling Namespace Reference
arm_conv::pooling Namespace Reference
Data Structures
struct a64_fp32_nhwc_avg_3x3_s1_output2x2_depthfirst
struct a64_fp32_nhwc_max_2x2_s1_output2x2_depthfirst
struct a64_s8_nhwc_max_2x2_s1_output2x2_depthfirst
struct a64_u8_nhwc_max_2x2_s1_output2x2_depthfirst
struct cpp_nhwc_1x1_stride_any_depthfirst
class PoolingDepthfirst
class PoolingDepthfirstCacheOblivious
class PoolingDepthfirstGeneric
class PoolingDepthfirstGenericQuantized
struct PoolingImplementation
Functions
void a64_fp32_nhwc_avg_3x3_s1_output2x2_depthfirst_impl (const unsigned int n_channels, const float *const *const inptrs, float *const *const outptrs, const bool exclude_padding, const unsigned int pad_left, const unsigned int pad_top, const unsigned int pad_right, const unsigned int pad_bottom)
void a64_fp32_nhwc_max_2x2_s1_output2x2_depthfirst_impl (const unsigned int n_channels, const float *const *const inptrs, float *const *const outptrs, const bool exclude_padding, const unsigned int pad_left, const unsigned int pad_top, const unsigned int pad_right, const unsigned int pad_bottom)
void a64_s8_nhwc_max_2x2_s1_output2x2_depthfirst_impl (const unsigned int n_channels, const int8_t *const *const inptrs, int8_t *const *const outptrs, const bool exclude_padding, const unsigned int pad_left, const unsigned int pad_top, const unsigned int pad_right, const unsigned int pad_bottom)
void a64_u8_nhwc_max_2x2_s1_output2x2_depthfirst_impl (const unsigned int n_channels, const uint8_t *const *const inptrs, uint8_t *const *const outptrs, const bool exclude_padding, const unsigned int pad_left, const unsigned int pad_top, const unsigned int pad_right, const unsigned int pad_bottom)
template<typename T >
void cpp_nhwc_1x1_stride_any_depthfirst_impl (uint64_t, uint64_t, const uint64_t n_channels, const T *const *const inptrs, T *outptr)
template void cpp_nhwc_1x1_stride_any_depthfirst_impl (uint64_t, uint64_t, uint64_t, const float *const *, float *)
template void cpp_nhwc_1x1_stride_any_depthfirst_impl (uint64_t, uint64_t, uint64_t, const int8_t *const *, int8_t *)
template void cpp_nhwc_1x1_stride_any_depthfirst_impl (uint64_t, uint64_t, uint64_t, const uint8_t *const *, uint8_t *)
template<>
const PoolingImplementation< float, float > * pooling_implementation_list ()
template UniquePoolingCommon< float, float > pooling (const PoolingArgs &, const Nothing &)
template<typename TInput , typename TOutput , class OutputStage = Nothing>
const PoolingImplementation< TInput, TOutput, OutputStage > * pooling_implementation_list ()
template<typename TInput , typename TOutput , class OutputStage = Nothing>
bool find_implementation (const PoolingArgs &args, const OutputStage &os, const PoolingImplementation< TInput, TOutput, OutputStage > *&selected)
template<typename TInput , typename TOutput , class OutputStage >
UniquePoolingCommon< TInput, TOutput, OutputStage > pooling (const PoolingArgs &args, const OutputStage &os)
template<>
const PoolingImplementation< int8_t, int8_t > * pooling_implementation_list ()
template<>
const PoolingImplementation< int8_t, int8_t, Requantize32 > * pooling_implementation_list ()
template UniquePoolingCommon< int8_t, int8_t, Requantize32 > pooling (const PoolingArgs &, const Requantize32 &)
template<>
const PoolingImplementation< uint8_t, uint8_t > * pooling_implementation_list ()
template<>
const PoolingImplementation< uint8_t, uint8_t, Requantize32 > * pooling_implementation_list ()
Function Documentation
a64_fp32_nhwc_avg_3x3_s1_output2x2_depthfirst_impl()
void a64_fp32_nhwc_avg_3x3_s1_output2x2_depthfirst_impl (const unsigned int n_channels, const float *const *const inptrs, float *const *const outptrs, const bool exclude_padding, const unsigned int pad_left, const unsigned int pad_top, const unsigned int pad_right, const unsigned int pad_bottom)
Definition at line 32 of file generic.cpp.
References GemmTuner::args.
 {
   struct KernelArgs
   {
     const uint64_t n_channels;
     const float *const *const inptrs;
     float *const *const outptrs;
     float rescale_vals[4];
     KernelArgs(
       unsigned int channels,
       const float *const *input_ptrs,
       float *const * output_ptrs,
       bool exclude_padding, unsigned int pad_left, unsigned int pad_top, unsigned int pad_right, unsigned int pad_bottom
     ) : n_channels(channels),
         inptrs(input_ptrs),
         outptrs(output_ptrs)
     {
       for (unsigned int i = 0; i < 2; i++)
       {
         const int start_i = 1*i - static_cast<int>(pad_top);
         const int end_i = std::min<int>(start_i + 3, 4 - pad_top - pad_bottom);
         const int valid_rows = end_i - std::max<int>(0, start_i);
         for (unsigned int j = 0; j < 2; j++)
         {
           const int start_j = 1*j - static_cast<int>(pad_left);
           const int end_j = std::min<int>(start_j + 3, 4 - pad_left - pad_right);
           const int valid_cols = end_j - std::max<int>(0, start_j);
           rescale_vals[i*2 + j] = static_cast<float>(1.0f / static_cast<float>(
             exclude_padding ? valid_rows * valid_cols : 9
           ));
         }
       }
     }
   };
   const KernelArgs args(n_channels, inptrs, outptrs, exclude_padding,
                         pad_left, pad_top, pad_right, pad_bottom);
   __asm__ __volatile__(
     "ldr x4, [%x[args], %[offsetof_n_channels]]\n"
     "mov x5, #0x0\n"
     "ldr x20, [%x[args], %[offsetof_outptrs]]\n"
     "mov x6, #0x0\n"
     "ldr x19, [%x[args], %[offsetof_inptrs]]\n"
     "cmp x4, #0x4\n"
     "ldp x7, x8, [x20, #0x0]\n"
     "ldp x17, x16, [x20, #0x10]\n"
     "ldp x15, x14, [x19, #0x0]\n"
     "ldp x13, x12, [x19, #0x10]\n"
     "ldp x11, x10, [x19, #0x20]\n"
     "ldp x9, x28, [x19, #0x30]\n"
     "ldp x27, x26, [x19, #0x40]\n"
     "ldp x25, x24, [x19, #0x50]\n"
     "ldp x23, x22, [x19, #0x60]\n"
     "ldp x21, x20, [x19, #0x70]\n"
     "ldr q8, [%x[args], %[offsetof_rescale]]\n"
     "blt 3f\n"
     "ldr q7, [x10, x5]\n"
     "lsr x19, x4, #0x2\n"
     "ldr q6, [x9, x5]\n"
     "sub x4, x4, x19, LSL #2\n"
     "ldr q5, [x26, x5]\n"
     "subs x19, x19, #0x1\n"
     "ldr q4, [x25, x5]\n"
     "ldr q3, [x14, x5]\n"
     "ldr q2, [x13, x5]\n"
     "ldr q1, [x11, x5]\n"
     "ldr q0, [x27, x5]\n"
     "ldr q31, [x28, x5]\n"
     "ldr q30, [x24, x5]\n"
     "ldr q29, [x22, x5]\n"
     "ldr q28, [x21, x5]\n"
     "ldr q27, [x15, x5]\n"
     "ldr q26, [x12, x5]\n"
     "ldr q25, [x23, x5]\n"
     "ldr q24, [x20, x5]\n"
     "add x5, x5, #0x10\n"
     "beq 2f\n"
     "1:"  // Vector: Loop
     "fadd v17.4s, v7.4s, v6.4s\n"
     "ldr q7, [x10, x5]\n"
     "subs x19, x19, #0x1\n"
     "fadd v16.4s, v5.4s, v4.4s\n"
     "ldr q6, [x9, x5]\n"
     "fadd v18.4s, v3.4s, v2.4s\n"
     "ldr q5, [x26, x5]\n"
     "fadd v23.4s, v1.4s, v0.4s\n"
     "ldr q4, [x25, x5]\n"
     "fadd v22.4s, v31.4s, v30.4s\n"
     "ldr q3, [x14, x5]\n"
     "fadd v17.4s, v17.4s, v16.4s\n"
     "ldr q2, [x13, x5]\n"
     "fadd v16.4s, v29.4s, v28.4s\n"
     "ldr q1, [x11, x5]\n"
     "fadd v19.4s, v27.4s, v23.4s\n"
     "ldr q0, [x27, x5]\n"
     "fadd v21.4s, v18.4s, v17.4s\n"
     "ldr q31, [x28, x5]\n"
     "fadd v20.4s, v16.4s, v17.4s\n"
     "ldr q30, [x24, x5]\n"
     "fadd v18.4s, v26.4s, v22.4s\n"
     "ldr q29, [x22, x5]\n"
     "fadd v17.4s, v25.4s, v23.4s\n"
     "ldr q28, [x21, x5]\n"
     "fadd v16.4s, v24.4s, v22.4s\n"
     "ldr q27, [x15, x5]\n"
     "fadd v19.4s, v21.4s, v19.4s\n"
     "ldr q26, [x12, x5]\n"
     "fadd v18.4s, v21.4s, v18.4s\n"
     "ldr q25, [x23, x5]\n"
     "fadd v17.4s, v17.4s, v20.4s\n"
     "ldr q24, [x20, x5]\n"
     "add x5, x5, #0x10\n"
     "fadd v16.4s, v20.4s, v16.4s\n"
     "fmul v19.4s, v19.4s, v8.s[0]\n"
     "str q19, [x7, x6]\n"
     "fmul v18.4s, v18.4s, v8.s[1]\n"
     "fmul v17.4s, v17.4s, v8.s[2]\n"
     "str q18, [x8, x6]\n"
     "fmul v16.4s, v16.4s, v8.s[3]\n"
     "str q17, [x17, x6]\n"
     "str q16, [x16, x6]\n"
     "add x6, x6, #0x10\n"
     "bgt 1b\n"
     "2:"  // Vector: Tail
     "fadd v17.4s, v7.4s, v6.4s\n"
     "fadd v16.4s, v5.4s, v4.4s\n"
     "fadd v18.4s, v3.4s, v2.4s\n"
     "fadd v23.4s, v1.4s, v0.4s\n"
     "fadd v17.4s, v17.4s, v16.4s\n"
     "fadd v22.4s, v31.4s, v30.4s\n"
     "fadd v16.4s, v29.4s, v28.4s\n"
     "fadd v21.4s, v18.4s, v17.4s\n"
     "fadd v19.4s, v27.4s, v23.4s\n"
     "fadd v20.4s, v16.4s, v17.4s\n"
     "fadd v18.4s, v26.4s, v22.4s\n"
     "fadd v17.4s, v25.4s, v23.4s\n"
     "fadd v16.4s, v24.4s, v22.4s\n"
     "fadd v19.4s, v21.4s, v19.4s\n"
     "fadd v18.4s, v21.4s, v18.4s\n"
     "fadd v17.4s, v17.4s, v20.4s\n"
     "fadd v16.4s, v20.4s, v16.4s\n"
     "fmul v19.4s, v19.4s, v8.s[0]\n"
     "str q19, [x7, x6]\n"
     "fmul v18.4s, v18.4s, v8.s[1]\n"
     "fmul v17.4s, v17.4s, v8.s[2]\n"
     "str q18, [x8, x6]\n"
     "fmul v16.4s, v16.4s, v8.s[3]\n"
     "str q17, [x17, x6]\n"
     "str q16, [x16, x6]\n"
     "add x6, x6, #0x10\n"
     "cbz x4, 4f\n"
     "3:"  // Oddments
     "ldr s7, [x10, x5]\n"
     "subs x4, x4, #0x1\n"
     "ldr s6, [x9, x5]\n"
     "fadd v17.4s, v7.4s, v6.4s\n"
     "ldr s5, [x26, x5]\n"
     "ldr s4, [x25, x5]\n"
     "fadd v16.4s, v5.4s, v4.4s\n"
     "ldr s3, [x14, x5]\n"
     "ldr s2, [x13, x5]\n"
     "fadd v17.4s, v17.4s, v16.4s\n"
     "ldr s1, [x11, x5]\n"
     "ldr s0, [x27, x5]\n"
     "fadd v18.4s, v3.4s, v2.4s\n"
     "ldr s31, [x28, x5]\n"
     "fadd v23.4s, v1.4s, v0.4s\n"
     "ldr s30, [x24, x5]\n"
     "fadd v21.4s, v18.4s, v17.4s\n"
     "ldr s29, [x22, x5]\n"
     "ldr s28, [x21, x5]\n"
     "fadd v22.4s, v31.4s, v30.4s\n"
     "ldr s27, [x15, x5]\n"
     "ldr s26, [x12, x5]\n"
     "fadd v16.4s, v29.4s, v28.4s\n"
     "ldr s25, [x23, x5]\n"
     "fadd v20.4s, v16.4s, v17.4s\n"
     "ldr s24, [x20, x5]\n"
     "add x5, x5, #0x4\n"
     "fadd v19.4s, v27.4s, v23.4s\n"
     "fadd v18.4s, v26.4s, v22.4s\n"
     "fadd v17.4s, v25.4s, v23.4s\n"
     "fadd v16.4s, v24.4s, v22.4s\n"
     "fadd v19.4s, v21.4s, v19.4s\n"
     "fadd v18.4s, v21.4s, v18.4s\n"
     "fadd v17.4s, v17.4s, v20.4s\n"
     "fadd v16.4s, v20.4s, v16.4s\n"
     "fmul v19.4s, v19.4s, v8.s[0]\n"
     "str s19, [x7, x6]\n"
     "fmul v18.4s, v18.4s, v8.s[1]\n"
     "fmul v17.4s, v17.4s, v8.s[2]\n"
     "str s18, [x8, x6]\n"
     "fmul v16.4s, v16.4s, v8.s[3]\n"
     "str s17, [x17, x6]\n"
     "str s16, [x16, x6]\n"
     "add x6, x6, #0x4\n"
     "bgt 3b\n"
     "4:"  // End
     :
     : [args] "r" (&args), [offsetof_inptrs] "I" (offsetof(KernelArgs, inptrs)), [offsetof_n_channels] "I" (offsetof(KernelArgs, n_channels)), [offsetof_outptrs] "I" (offsetof(KernelArgs, outptrs)), [offsetof_rescale] "I" (offsetof(KernelArgs, rescale_vals))
     : "cc", "memory", "v0", "v1", "v2", "v3", "v4", "v5", "v6", "v7", "v8", "v16", "v17", "v18", "v19", "v20", "v21", "v22", "v23", "v24", "v25", "v26", "v27", "v28", "v29", "v30", "v31", "x4", "x5", "x6", "x7", "x8", "x9", "x10", "x11", "x12", "x13", "x14", "x15", "x16", "x17", "x19", "x20", "x21", "x22", "x23", "x24", "x25", "x26", "x27", "x28"
   );
 }
a64_fp32_nhwc_max_2x2_s1_output2x2_depthfirst_impl()
void a64_fp32_nhwc_max_2x2_s1_output2x2_depthfirst_impl (const unsigned int n_channels, const float *const *const inptrs, float *const *const outptrs, const bool exclude_padding, const unsigned int pad_left, const unsigned int pad_top, const unsigned int pad_right, const unsigned int pad_bottom)
Definition at line 32 of file generic.cpp.
References GemmTuner::args.
 {
   struct KernelArgs
   {
     const uint64_t n_channels;
     const float *const *const inptrs;
     float *const *const outptrs;
     KernelArgs(
       unsigned int channels,
       const float *const *input_ptrs,
       float *const * output_ptrs,
       bool, unsigned int, unsigned int, unsigned int, unsigned int
     ) : n_channels(channels),
         inptrs(input_ptrs),
         outptrs(output_ptrs)
     {
     }
   };
   const KernelArgs args(n_channels, inptrs, outptrs, exclude_padding,
                         pad_left, pad_top, pad_right, pad_bottom);
   __asm__ __volatile__(
     "ldr x15, [%x[args], %[offsetof_n_channels]]\n"
     "mov x14, #0x0\n"
     "ldr x20, [%x[args], %[offsetof_outptrs]]\n"
     "mov x13, #0x0\n"
     "ldr x19, [%x[args], %[offsetof_inptrs]]\n"
     "cmp x15, #0x4\n"
     "ldp x12, x11, [x20, #0x0]\n"
     "ldp x10, x9, [x20, #0x10]\n"
     "ldp x28, x27, [x19, #0x0]\n"
     "ldp x26, x25, [x19, #0x10]\n"
     "ldp x24, x23, [x19, #0x20]\n"
     "ldp x22, x21, [x19, #0x30]\n"
     "ldr x20, [x19, #0x40]\n"
     "blt 3f\n"
     "ldr q30, [x27, x14]\n"
     "lsr x19, x15, #0x2\n"
     "ldr q29, [x24, x14]\n"
     "sub x15, x15, x19, LSL #2\n"
     "ldr q28, [x21, x14]\n"
     "subs x19, x19, #0x1\n"
     "ldr q27, [x25, x14]\n"
     "ldr q26, [x28, x14]\n"
     "ldr q25, [x23, x14]\n"
     "ldr q24, [x26, x14]\n"
     "ldr q23, [x22, x14]\n"
     "ldr q22, [x20, x14]\n"
     "add x14, x14, #0x10\n"
     "beq 2f\n"
     "1:"  // Vector: Loop
     "fmax v21.4s, v30.4s, v29.4s\n"
     "ldr q30, [x27, x14]\n"
     "subs x19, x19, #0x1\n"
     "fmax v20.4s, v29.4s, v28.4s\n"
     "ldr q29, [x24, x14]\n"
     "fmax v19.4s, v27.4s, v26.4s\n"
     "ldr q28, [x21, x14]\n"
     "fmax v18.4s, v25.4s, v24.4s\n"
     "ldr q26, [x28, x14]\n"
     "fmax v17.4s, v23.4s, v27.4s\n"
     "ldr q27, [x25, x14]\n"
     "fmax v16.4s, v25.4s, v22.4s\n"
     "ldr q25, [x23, x14]\n"
     "fmax v19.4s, v21.4s, v19.4s\n"
     "ldr q24, [x26, x14]\n"
     "fmax v18.4s, v21.4s, v18.4s\n"
     "ldr q23, [x22, x14]\n"
     "fmax v17.4s, v20.4s, v17.4s\n"
     "ldr q22, [x20, x14]\n"
     "add x14, x14, #0x10\n"
     "fmax v16.4s, v20.4s, v16.4s\n"
     "str q19, [x12, x13]\n"
     "str q18, [x11, x13]\n"
     "str q17, [x10, x13]\n"
     "str q16, [x9, x13]\n"
     "add x13, x13, #0x10\n"
     "bgt 1b\n"
     "2:"  // Vector: Tail
     "fmax v21.4s, v30.4s, v29.4s\n"
     "fmax v20.4s, v29.4s, v28.4s\n"
     "fmax v19.4s, v27.4s, v26.4s\n"
     "fmax v18.4s, v25.4s, v24.4s\n"
     "fmax v17.4s, v23.4s, v27.4s\n"
     "fmax v16.4s, v25.4s, v22.4s\n"
     "fmax v19.4s, v21.4s, v19.4s\n"
     "str q19, [x12, x13]\n"
     "fmax v18.4s, v21.4s, v18.4s\n"
     "fmax v17.4s, v20.4s, v17.4s\n"
     "str q18, [x11, x13]\n"
     "fmax v16.4s, v20.4s, v16.4s\n"
     "str q17, [x10, x13]\n"
     "str q16, [x9, x13]\n"
     "add x13, x13, #0x10\n"
     "cbz x15, 4f\n"
     "3:"  // Oddments
     "ldr s30, [x27, x14]\n"
     "subs x15, x15, #0x1\n"
     "ldr s29, [x24, x14]\n"
     "fmax v21.4s, v30.4s, v29.4s\n"
     "ldr s28, [x21, x14]\n"
     "ldr s27, [x25, x14]\n"
     "fmax v20.4s, v29.4s, v28.4s\n"
     "ldr s26, [x28, x14]\n"
     "ldr s25, [x23, x14]\n"
     "fmax v19.4s, v27.4s, v26.4s\n"
     "ldr s24, [x26, x14]\n"
     "ldr s23, [x22, x14]\n"
     "fmax v19.4s, v21.4s, v19.4s\n"
     "ldr s22, [x20, x14]\n"
     "add x14, x14, #0x4\n"
     "fmax v18.4s, v25.4s, v24.4s\n"
     "str s19, [x12, x13]\n"
     "fmax v17.4s, v23.4s, v27.4s\n"
     "fmax v16.4s, v25.4s, v22.4s\n"
     "fmax v18.4s, v21.4s, v18.4s\n"
     "str s18, [x11, x13]\n"
     "fmax v17.4s, v20.4s, v17.4s\n"
     "fmax v16.4s, v20.4s, v16.4s\n"
     "str s17, [x10, x13]\n"
     "str s16, [x9, x13]\n"
     "add x13, x13, #0x4\n"
     "bgt 3b\n"
     "4:"  // End
     :
     : [args] "r" (&args), [offsetof_inptrs] "I" (offsetof(KernelArgs, inptrs)), [offsetof_n_channels] "I" (offsetof(KernelArgs, n_channels)), [offsetof_outptrs] "I" (offsetof(KernelArgs, outptrs))
     : "cc", "memory", "v16", "v17", "v18", "v19", "v20", "v21", "v22", "v23", "v24", "v25", "v26", "v27", "v28", "v29", "v30", "x9", "x10", "x11", "x12", "x13", "x14", "x15", "x19", "x20", "x21", "x22", "x23", "x24", "x25", "x26", "x27", "x28"
   );
 }
a64_s8_nhwc_max_2x2_s1_output2x2_depthfirst_impl()
void a64_s8_nhwc_max_2x2_s1_output2x2_depthfirst_impl (const unsigned int n_channels, const int8_t *const *const inptrs, int8_t *const *const outptrs, const bool exclude_padding, const unsigned int pad_left, const unsigned int pad_top, const unsigned int pad_right, const unsigned int pad_bottom)
Definition at line 32 of file generic.cpp.
References GemmTuner::args.
 {
   struct KernelArgs
   {
     const uint64_t n_channels;
     const int8_t *const *const inptrs;
     int8_t *const *const outptrs;
     KernelArgs(
       unsigned int channels,
       const int8_t *const *input_ptrs,
       int8_t *const * output_ptrs,
       bool, unsigned int, unsigned int, unsigned int, unsigned int
     ) : n_channels(channels),
         inptrs(input_ptrs),
         outptrs(output_ptrs)
     {
     }
   };
   const KernelArgs args(n_channels, inptrs, outptrs, exclude_padding,
                         pad_left, pad_top, pad_right, pad_bottom);
   __asm__ __volatile__(
     "ldr x15, [%x[args], %[offsetof_n_channels]]\n"
     "mov x14, #0x0\n"
     "ldr x20, [%x[args], %[offsetof_outptrs]]\n"
     "mov x13, #0x0\n"
     "ldr x19, [%x[args], %[offsetof_inptrs]]\n"
     "cmp x15, #0x10\n"
     "ldp x12, x11, [x20, #0x0]\n"
     "ldp x10, x9, [x20, #0x10]\n"
     "ldp x28, x27, [x19, #0x0]\n"
     "ldp x26, x25, [x19, #0x10]\n"
     "ldp x24, x23, [x19, #0x20]\n"
     "ldp x22, x21, [x19, #0x30]\n"
     "ldr x20, [x19, #0x40]\n"
     "blt 3f\n"
     "ldr q30, [x27, x14]\n"
     "lsr x19, x15, #0x4\n"
     "ldr q29, [x24, x14]\n"
     "sub x15, x15, x19, LSL #4\n"
     "ldr q28, [x21, x14]\n"
     "subs x19, x19, #0x1\n"
     "ldr q27, [x25, x14]\n"
     "ldr q26, [x28, x14]\n"
     "ldr q25, [x23, x14]\n"
     "ldr q24, [x26, x14]\n"
     "ldr q23, [x22, x14]\n"
     "ldr q22, [x20, x14]\n"
     "add x14, x14, #0x10\n"
     "beq 2f\n"
     "1:"  // Vector: Loop
     "smax v21.16b, v30.16b, v29.16b\n"
     "ldr q30, [x27, x14]\n"
     "subs x19, x19, #0x1\n"
     "smax v20.16b, v29.16b, v28.16b\n"
     "ldr q29, [x24, x14]\n"
     "smax v19.16b, v27.16b, v26.16b\n"
     "ldr q28, [x21, x14]\n"
     "smax v18.16b, v25.16b, v24.16b\n"
     "ldr q26, [x28, x14]\n"
     "smax v17.16b, v23.16b, v27.16b\n"
     "ldr q27, [x25, x14]\n"
     "smax v16.16b, v25.16b, v22.16b\n"
     "ldr q25, [x23, x14]\n"
     "smax v19.16b, v21.16b, v19.16b\n"
     "ldr q24, [x26, x14]\n"
     "smax v18.16b, v21.16b, v18.16b\n"
     "ldr q23, [x22, x14]\n"
     "smax v17.16b, v20.16b, v17.16b\n"
     "ldr q22, [x20, x14]\n"
     "add x14, x14, #0x10\n"
     "smax v16.16b, v20.16b, v16.16b\n"
     "str q19, [x12, x13]\n"
     "str q18, [x11, x13]\n"
     "str q17, [x10, x13]\n"
     "str q16, [x9, x13]\n"
     "add x13, x13, #0x10\n"
     "bgt 1b\n"
     "2:"  // Vector: Tail
     "smax v21.16b, v30.16b, v29.16b\n"
     "smax v20.16b, v29.16b, v28.16b\n"
     "smax v19.16b, v27.16b, v26.16b\n"
     "smax v18.16b, v25.16b, v24.16b\n"
     "smax v17.16b, v23.16b, v27.16b\n"
     "smax v16.16b, v25.16b, v22.16b\n"
     "smax v19.16b, v21.16b, v19.16b\n"
     "str q19, [x12, x13]\n"
     "smax v18.16b, v21.16b, v18.16b\n"
     "smax v17.16b, v20.16b, v17.16b\n"
     "str q18, [x11, x13]\n"
     "smax v16.16b, v20.16b, v16.16b\n"
     "str q17, [x10, x13]\n"
     "str q16, [x9, x13]\n"
     "add x13, x13, #0x10\n"
     "cbz x15, 4f\n"
     "3:"  // Oddments
     "ldr b30, [x27, x14]\n"
     "subs x15, x15, #0x1\n"
     "ldr b29, [x24, x14]\n"
     "smax v21.16b, v30.16b, v29.16b\n"
     "ldr b28, [x21, x14]\n"
     "ldr b27, [x25, x14]\n"
     "smax v20.16b, v29.16b, v28.16b\n"
     "ldr b26, [x28, x14]\n"
     "ldr b25, [x23, x14]\n"
     "smax v19.16b, v27.16b, v26.16b\n"
     "ldr b24, [x26, x14]\n"
     "ldr b23, [x22, x14]\n"
     "smax v19.16b, v21.16b, v19.16b\n"
     "ldr b22, [x20, x14]\n"
     "add x14, x14, #0x1\n"
     "smax v18.16b, v25.16b, v24.16b\n"
     "str b19, [x12, x13]\n"
     "smax v17.16b, v23.16b, v27.16b\n"
     "smax v16.16b, v25.16b, v22.16b\n"
     "smax v18.16b, v21.16b, v18.16b\n"
     "str b18, [x11, x13]\n"
     "smax v17.16b, v20.16b, v17.16b\n"
     "smax v16.16b, v20.16b, v16.16b\n"
     "str b17, [x10, x13]\n"
     "str b16, [x9, x13]\n"
     "add x13, x13, #0x1\n"
     "bgt 3b\n"
     "4:"  // End
     :
     : [args] "r" (&args), [offsetof_inptrs] "I" (offsetof(KernelArgs, inptrs)), [offsetof_n_channels] "I" (offsetof(KernelArgs, n_channels)), [offsetof_outptrs] "I" (offsetof(KernelArgs, outptrs))
     : "cc", "memory", "v16", "v17", "v18", "v19", "v20", "v21", "v22", "v23", "v24", "v25", "v26", "v27", "v28", "v29", "v30", "x9", "x10", "x11", "x12", "x13", "x14", "x15", "x19", "x20", "x21", "x22", "x23", "x24", "x25", "x26", "x27", "x28"
   );
 }
a64_u8_nhwc_max_2x2_s1_output2x2_depthfirst_impl()
void a64_u8_nhwc_max_2x2_s1_output2x2_depthfirst_impl (const unsigned int n_channels, const uint8_t *const *const inptrs, uint8_t *const *const outptrs, const bool exclude_padding, const unsigned int pad_left, const unsigned int pad_top, const unsigned int pad_right, const unsigned int pad_bottom)
Definition at line 32 of file generic.cpp.
References GemmTuner::args.
 {
   struct KernelArgs
   {
     const uint64_t n_channels;
     const uint8_t *const *const inptrs;
     uint8_t *const *const outptrs;
     KernelArgs(
       unsigned int channels,
       const uint8_t *const *input_ptrs,
       uint8_t *const * output_ptrs,
       bool, unsigned int, unsigned int, unsigned int, unsigned int
     ) : n_channels(channels),
         inptrs(input_ptrs),
         outptrs(output_ptrs)
     {
     }
   };
   const KernelArgs args(n_channels, inptrs, outptrs, exclude_padding,
                         pad_left, pad_top, pad_right, pad_bottom);
   __asm__ __volatile__(
     "ldr x15, [%x[args], %[offsetof_n_channels]]\n"
     "mov x14, #0x0\n"
     "ldr x20, [%x[args], %[offsetof_outptrs]]\n"
     "mov x13, #0x0\n"
     "ldr x19, [%x[args], %[offsetof_inptrs]]\n"
     "cmp x15, #0x10\n"
     "ldp x12, x11, [x20, #0x0]\n"
     "ldp x10, x9, [x20, #0x10]\n"
     "ldp x28, x27, [x19, #0x0]\n"
     "ldp x26, x25, [x19, #0x10]\n"
     "ldp x24, x23, [x19, #0x20]\n"
     "ldp x22, x21, [x19, #0x30]\n"
     "ldr x20, [x19, #0x40]\n"
     "blt 3f\n"
     "ldr q30, [x27, x14]\n"
     "lsr x19, x15, #0x4\n"
     "ldr q29, [x24, x14]\n"
     "sub x15, x15, x19, LSL #4\n"
     "ldr q28, [x21, x14]\n"
     "subs x19, x19, #0x1\n"
     "ldr q27, [x25, x14]\n"
     "ldr q26, [x28, x14]\n"
     "ldr q25, [x23, x14]\n"
     "ldr q24, [x26, x14]\n"
     "ldr q23, [x22, x14]\n"
     "ldr q22, [x20, x14]\n"
     "add x14, x14, #0x10\n"
     "beq 2f\n"
     "1:"  // Vector: Loop
     "umax v21.16b, v30.16b, v29.16b\n"
     "ldr q30, [x27, x14]\n"
     "subs x19, x19, #0x1\n"
     "umax v20.16b, v29.16b, v28.16b\n"
     "ldr q29, [x24, x14]\n"
     "umax v19.16b, v27.16b, v26.16b\n"
     "ldr q28, [x21, x14]\n"
     "umax v18.16b, v25.16b, v24.16b\n"
     "ldr q26, [x28, x14]\n"
     "umax v17.16b, v23.16b, v27.16b\n"
     "ldr q27, [x25, x14]\n"
     "umax v16.16b, v25.16b, v22.16b\n"
     "ldr q25, [x23, x14]\n"
     "umax v19.16b, v21.16b, v19.16b\n"
     "ldr q24, [x26, x14]\n"
     "umax v18.16b, v21.16b, v18.16b\n"
     "ldr q23, [x22, x14]\n"
     "umax v17.16b, v20.16b, v17.16b\n"
     "ldr q22, [x20, x14]\n"
     "add x14, x14, #0x10\n"
     "umax v16.16b, v20.16b, v16.16b\n"
     "str q19, [x12, x13]\n"
     "str q18, [x11, x13]\n"
     "str q17, [x10, x13]\n"
     "str q16, [x9, x13]\n"
     "add x13, x13, #0x10\n"
     "bgt 1b\n"
     "2:"  // Vector: Tail
     "umax v21.16b, v30.16b, v29.16b\n"
     "umax v20.16b, v29.16b, v28.16b\n"
     "umax v19.16b, v27.16b, v26.16b\n"
     "umax v18.16b, v25.16b, v24.16b\n"
     "umax v17.16b, v23.16b, v27.16b\n"
     "umax v16.16b, v25.16b, v22.16b\n"
     "umax v19.16b, v21.16b, v19.16b\n"
     "str q19, [x12, x13]\n"
     "umax v18.16b, v21.16b, v18.16b\n"
     "umax v17.16b, v20.16b, v17.16b\n"
     "str q18, [x11, x13]\n"
     "umax v16.16b, v20.16b, v16.16b\n"
     "str q17, [x10, x13]\n"
     "str q16, [x9, x13]\n"
     "add x13, x13, #0x10\n"
     "cbz x15, 4f\n"
     "3:"  // Oddments
     "ldr b30, [x27, x14]\n"
     "subs x15, x15, #0x1\n"
     "ldr b29, [x24, x14]\n"
     "umax v21.16b, v30.16b, v29.16b\n"
     "ldr b28, [x21, x14]\n"
     "ldr b27, [x25, x14]\n"
     "umax v20.16b, v29.16b, v28.16b\n"
     "ldr b26, [x28, x14]\n"
     "ldr b25, [x23, x14]\n"
     "umax v19.16b, v27.16b, v26.16b\n"
     "ldr b24, [x26, x14]\n"
     "ldr b23, [x22, x14]\n"
     "umax v19.16b, v21.16b, v19.16b\n"
     "ldr b22, [x20, x14]\n"
     "add x14, x14, #0x1\n"
     "umax v18.16b, v25.16b, v24.16b\n"
     "str b19, [x12, x13]\n"
     "umax v17.16b, v23.16b, v27.16b\n"
     "umax v16.16b, v25.16b, v22.16b\n"
     "umax v18.16b, v21.16b, v18.16b\n"
     "str b18, [x11, x13]\n"
     "umax v17.16b, v20.16b, v17.16b\n"
     "umax v16.16b, v20.16b, v16.16b\n"
     "str b17, [x10, x13]\n"
     "str b16, [x9, x13]\n"
     "add x13, x13, #0x1\n"
     "bgt 3b\n"
     "4:"  // End
     :
     : [args] "r" (&args), [offsetof_inptrs] "I" (offsetof(KernelArgs, inptrs)), [offsetof_n_channels] "I" (offsetof(KernelArgs, n_channels)), [offsetof_outptrs] "I" (offsetof(KernelArgs, outptrs))
     : "cc", "memory", "v16", "v17", "v18", "v19", "v20", "v21", "v22", "v23", "v24", "v25", "v26", "v27", "v28", "v29", "v30", "x9", "x10", "x11", "x12", "x13", "x14", "x15", "x19", "x20", "x21", "x22", "x23", "x24", "x25", "x26", "x27", "x28"
   );
 }
cpp_nhwc_1x1_stride_any_depthfirst_impl() [1/4]
void cpp_nhwc_1x1_stride_any_depthfirst_impl (uint64_t , uint64_t , const uint64_t n_channels, const T *const *const inptrs, T * outptr)
Definition at line 32 of file generic.cpp.
 {
   std::memcpy(outptr, inptrs[0], n_channels * sizeof(T));
 }
cpp_nhwc_1x1_stride_any_depthfirst_impl() [2/4]
template void arm_conv::pooling::cpp_nhwc_1x1_stride_any_depthfirst_impl (uint64_t , uint64_t , uint64_t , const float *const * , float *)
cpp_nhwc_1x1_stride_any_depthfirst_impl() [3/4]
template void arm_conv::pooling::cpp_nhwc_1x1_stride_any_depthfirst_impl (uint64_t , uint64_t , uint64_t , const int8_t *const * , int8_t *)
cpp_nhwc_1x1_stride_any_depthfirst_impl() [4/4]
template void arm_conv::pooling::cpp_nhwc_1x1_stride_any_depthfirst_impl (uint64_t , uint64_t , uint64_t , const uint8_t *const * , uint8_t *)
find_implementation()
bool arm_conv::pooling::find_implementation (const PoolingArgs & args, const OutputStage & os, const PoolingImplementation< TInput, TOutput, OutputStage > *& selected)
Definition at line 64 of file pooling_implementation.hpp.
 {
   // For now, return the first valid implementation
   const auto *impl = pooling_implementation_list<TInput, TOutput, OutputStage>();
   for (; impl->method != PoolingMethod::DEFAULT; impl++)
   {
     if (args.config != nullptr)
     {
       // Apply filters provided by the configuration
       const auto cfg = args.config;
       if (cfg->filter != "" && !std::strstr(impl->name, cfg->filter.c_str()))
       {
         continue;
       }
     }
     if (impl->get_is_supported(args, os))
     {
       selected = impl;
       return true;
     }
   }
   return false;
 }
pooling() [1/3]
UniquePoolingCommon<TInput, TOutput, OutputStage> arm_conv::pooling::pooling (const PoolingArgs & args, const OutputStage & os)
Definition at line 95 of file pooling_implementation.hpp.
References GemmTuner::args, and PoolingImplementation< TInput, TOutput, OutputStage >::get_instance().
 {
   const PoolingImplementation<TInput, TOutput, OutputStage> *impl = nullptr;
   const bool success = find_implementation<TInput, TOutput, OutputStage>(args, os, impl);
   return UniquePoolingCommon<TInput, TOutput, OutputStage>(success ? impl->get_instance(args, os) : nullptr);
 }
pooling() [2/3]
template UniquePoolingCommon< uint8_t, uint8_t, Requantize32 > pooling (const PoolingArgs & , const Requantize32 &)
pooling() [3/3]
template UniquePoolingCommon< uint8_t, uint8_t > pooling (const PoolingArgs & , const Nothing &)
Referenced by pooling_implementation_list().
pooling_implementation_list() [1/6]
const PoolingImplementation<TInput, TOutput, OutputStage>* arm_conv::pooling::pooling_implementation_list ()
Definition at line 161 of file pooling_fp32.cpp.
References pooling().
Referenced by PoolingImplementation< TInput, TOutput, OutputStage >::get_instance().
 {
   return pooling_fp32_methods;
 }
pooling_implementation_list() [2/6]
const PoolingImplementation<int8_t, int8_t, Requantize32>* arm_conv::pooling::pooling_implementation_list ()
Definition at line 93 of file pooling_s8q.cpp.
References pooling().
 {
   return pooling_u8_methods;
 }
pooling_implementation_list() [3/6]
const PoolingImplementation<uint8_t, uint8_t, Requantize32>* arm_conv::pooling::pooling_implementation_list ()
Definition at line 93 of file pooling_u8q.cpp.
References pooling().
 {
   return pooling_u8_methods;
 }
pooling_implementation_list() [4/6]
const PoolingImplementation<int8_t, int8_t>* arm_conv::pooling::pooling_implementation_list ()
Definition at line 141 of file pooling_s8.cpp.
References pooling().
 {
   return pooling_s8_methods;
 }
pooling_implementation_list() [5/6]
const PoolingImplementation<uint8_t, uint8_t>* arm_conv::pooling::pooling_implementation_list ()
Definition at line 157 of file pooling_u8.cpp.
References pooling().
 {
   return pooling_u8_methods;
 }
pooling_implementation_list() [6/6]
const PoolingImplementation<float, float>* arm_conv::pooling::pooling_implementation_list ()
Definition at line 161 of file pooling_fp32.cpp.
Referenced by PoolingImplementation< TInput, TOutput, OutputStage >::get_instance().
 {
   return pooling_fp32_methods;
 }