Compute Library: src/core/CL/cl_kernels/nchw/pooling_layer.cl File Reference
pooling_layer.cl File Reference
#include "helpers.h"
#include "repeat.h"
#include "tile_helpers.h"
Macros
#define POOL_OP(x, y) ((x) + (y))
#define POW2_OP(x, vec_size) (x)
#define DIV_OP(x, y) (x * (1.f / y))
#define SQRT_OP(x) sqrt((x))
#define VLOAD_AND_CONVERT_TO_ACC_DATA_TYPE(n, offset, ptr) vload##n(offset, ptr)
Functions
ACC_DATA_TYPE calculate_avg_scale (const int pool_size_x, const int pool_size_y, const int upper_bound_w, const int upper_bound_h, const int pad_x, const int pad_y, const int stride_x, const int stride_y)
__kernel void pooling_layer_2_nchw_indices_fp32 (__global uchar *input_ptr, uint input_stride_x, uint input_step_x, uint input_stride_y, uint input_step_y, uint input_stride_z, uint input_step_z, uint input_offset_first_element_in_bytes, __global uchar *output_ptr, uint output_stride_x, uint output_step_x, uint output_stride_y, uint output_step_y, uint output_stride_z, uint output_step_z, uint output_offset_first_element_in_bytes, __global uchar *indices_ptr, uint indices_stride_x, uint indices_step_x, uint indices_stride_y, uint indices_step_y, uint indices_stride_z, uint indices_step_z, uint indices_offset_first_element_in_bytes)
Performs a MAX pooling of pool size equal to 2, and record max value indices for NCHW.
__kernel void pooling_layer_2_nchw_indices_fp16 (__global uchar *input_ptr, uint input_stride_x, uint input_step_x, uint input_stride_y, uint input_step_y, uint input_stride_z, uint input_step_z, uint input_offset_first_element_in_bytes, __global uchar *output_ptr, uint output_stride_x, uint output_step_x, uint output_stride_y, uint output_step_y, uint output_stride_z, uint output_step_z, uint output_offset_first_element_in_bytes, __global uchar *indices_ptr, uint indices_stride_x, uint indices_step_x, uint indices_stride_y, uint indices_step_y, uint indices_stride_z, uint indices_step_z, uint indices_offset_first_element_in_bytes)
Performs a MAX pooling of pool size equal to 2, and record max value indices for NCHW.
Macro Definition Documentation
DIV_OP
#define DIV_OP (x, y) (x * (1.f / y))
Definition at line 40 of file pooling_layer.cl.
Referenced by calculate_avg_scale().
POOL_OP
#define POOL_OP (x, y) ((x) + (y))
Definition at line 29 of file pooling_layer.cl.
Referenced by calculate_avg_scale(), pooling_layer_2_nchw_indices_fp16(), and pooling_layer_2_nchw_indices_fp32().
POW2_OP
#define POW2_OP (x, vec_size) (x)
Definition at line 37 of file pooling_layer.cl.
SQRT_OP
#define SQRT_OP (x) sqrt((x))
Definition at line 41 of file pooling_layer.cl.
Referenced by calculate_avg_scale().
VLOAD_AND_CONVERT_TO_ACC_DATA_TYPE
#define VLOAD_AND_CONVERT_TO_ACC_DATA_TYPE (n, offset, ptr) vload##n(offset, ptr)
Definition at line 48 of file pooling_layer.cl.
Referenced by calculate_avg_scale().
Function Documentation
calculate_avg_scale()
ACC_DATA_TYPE calculate_avg_scale (const int pool_size_x, const int pool_size_y, const int upper_bound_w, const int upper_bound_h, const int pad_x, const int pad_y, const int stride_x, const int stride_y)
Definition at line 51 of file pooling_layer.cl.
References calculate_avg_scale(), CONVERT_TO_TENSOR3D_STRUCT, DIV_OP, arm_compute::test::validation::input, Tensor3D::offset_first_element_in_bytes, POOL_OP, Tensor3D::ptr, SQRT_OP, Tensor3D::stride_x, Tensor3D::stride_y, Tensor3D::stride_z, TENSOR3D_DECLARATION, tensor3D_offset(), VEC_DATA_TYPE, and VLOAD_AND_CONVERT_TO_ACC_DATA_TYPE.
 {
     int       start_x = get_global_id(0) * stride_x - pad_x;
     int       start_y = get_global_id(1) * stride_y - pad_y;
     const int end_x   = min(start_x + pool_size_x, upper_bound_w);
     const int end_y   = min(start_y + pool_size_y, upper_bound_h);
 #if defined(EXCLUDE_PADDING)
     start_x = max(0, start_x);
     start_y = max(0, start_y);
 #endif /* defined(EXCLUDE_PADDING) */
     return ((end_y - start_y) * (end_x - start_x));
 }
pooling_layer_2_nchw_indices_fp16()
__kernel void pooling_layer_2_nchw_indices_fp16 (__global uchar * input_ptr, uint input_stride_x, uint input_step_x, uint input_stride_y, uint input_step_y, uint input_stride_z, uint input_step_z, uint input_offset_first_element_in_bytes, __global uchar * output_ptr, uint output_stride_x, uint output_step_x, uint output_stride_y, uint output_step_y, uint output_stride_z, uint output_step_z, uint output_offset_first_element_in_bytes, __global uchar * indices_ptr, uint indices_stride_x, uint indices_step_x, uint indices_stride_y, uint indices_step_y, uint indices_stride_z, uint indices_step_z, uint indices_offset_first_element_in_bytes)
Performs a MAX pooling of pool size equal to 2, and record max value indices for NCHW.
Note
Datatype must be passed using -DDATA_TYPE e.g. -DDATA_TYPE=half. Supported data types are F16
Pool sizes must be passed using -DPOOL_SIZE_X and -DPOOL_SIZE_Y e.g. -DPOOL_SIZE_X=13;
Tensors width and height must be passed at compile time using -DMAX_WIDTH and -DMAX_HEIGHT
Pool strides must be passed at compile time using -DSTRIDE_X and -DSTRIDE_Y which are the steps of the window along the x and y directions
Tensor padding values must be passed at compile time using PAD_TENSOR_LEFT, PAD_TENSOR_RIGHT, PAD_TENSOR_TOP and PAD_TENSOR_BOTTOM
Parameters
[in] input_ptr Pointer to the source tensor. Supported data types: F16
[in] input_stride_x Stride of the source tensor in X dimension (in bytes)
[in] input_step_x input_stride_x * number of elements along X processed per workitem(in bytes)
[in] input_stride_y Stride of the source tensor in Y dimension (in bytes)
[in] input_step_y input_stride_y * number of elements along Y processed per workitem(in bytes)
[in] input_stride_z Stride of the source tensor in Z dimension (in bytes)
[in] input_step_z input_stride_z * number of elements along Z processed per workitem(in bytes)
[in] input_offset_first_element_in_bytes The offset of the first element in the source tensor
[out] output_ptr Pointer to the destination tensor. Supported data types: same as input_ptr
[in] output_stride_x Stride of the destination tensor in X dimension (in bytes)
[in] output_step_x output_stride_x * number of elements along X processed per workitem(in bytes)
[in] output_stride_y Stride of the destination tensor in Y dimension (in bytes)
[in] output_step_y output_stride_y * number of elements along Y processed per workitem(in bytes)
[in] output_stride_z Stride of the source tensor in Z dimension (in bytes)
[in] output_step_z output_stride_z * number of elements along Z processed per workitem(in bytes)
[in] output_offset_first_element_in_bytes The offset of the first element in the destination tensor
[in] indices_ptr Pointer to the indices tensor. Supported data types: U32
[in] indices_stride_x Stride of the indices tensor in X dimension (in bytes)
[in] indices_step_x indices_stride_x * number of elements along X processed per workitem(in bytes)
[in] indices_stride_y Stride of the indices tensor in Y dimension (in bytes)
[in] indices_step_y indices_stride_y * number of elements along Y processed per workitem(in bytes)
[in] indices_stride_z Stride of the indices tensor in Z dimension (in bytes)
[in] indices_step_z indices_stride_z * number of elements along Z processed per workitem(in bytes)
[in] indices_offset_first_element_in_bytes The offset of the first element in the indices tensor
Definition at line 296 of file pooling_layer.cl.
References CONVERT_TO_TENSOR3D_STRUCT, POOL_OP, Tensor3D::ptr, arm_compute::test::validation::reference::select(), tensor3D_offset(), and VLOAD.
 {
     // Get pixels pointer
     Tensor3D input   = CONVERT_TO_TENSOR3D_STRUCT(input);
     Tensor3D output  = CONVERT_TO_TENSOR3D_STRUCT(output);
     Tensor3D indices = CONVERT_TO_TENSOR3D_STRUCT(indices);
     // Load data
     half2 data0 = VLOAD(2)(0, (__global half *)tensor3D_offset(&input, 0, 0, 0));
     half2 data1 = VLOAD(2)(0, (__global half *)tensor3D_offset(&input, 0, 1, 0));
     // Perform calculations
     half data0_max = POOL_OP(data0.s0, data0.s1);
     half data1_max = POOL_OP(data1.s0, data1.s1);
     half res       = POOL_OP(data0_max, data1_max);
     // Store result
     *(__global half *)output.ptr = res;
 #if defined(PAD_TENSOR_LEFT) && defined(PAD_TENSOR_RIGHT) && defined(PAD_TENSOR_TOP) && defined(PAD_TENSOR_BOTTOM)
     uint offset_top    = 0;
     uint offset_bottom = 0;
     offset_no_padding_nchw(&input, &offset_top, &offset_bottom);
     uint index0 = select(offset_top + 1, offset_top, isgreaterequal(data0.s0, data0.s1));
     uint index1 = select(offset_bottom + 1, offset_bottom, isgreaterequal(data1.s0, data1.s1));
     uint index  = select(index1, index0, isgreaterequal(data0_max, data1_max));
     *(__global uint *)indices.ptr = index;
 #endif //defined(PAD_TENSOR_LEFT) && defined(PAD_TENSOR_RIGHT) && defined(PAD_TENSOR_TOP) && defined(PAD_TENSOR_BOTTOM)
 }
pooling_layer_2_nchw_indices_fp32()
__kernel void pooling_layer_2_nchw_indices_fp32 (__global uchar * input_ptr, uint input_stride_x, uint input_step_x, uint input_stride_y, uint input_step_y, uint input_stride_z, uint input_step_z, uint input_offset_first_element_in_bytes, __global uchar * output_ptr, uint output_stride_x, uint output_step_x, uint output_stride_y, uint output_step_y, uint output_stride_z, uint output_step_z, uint output_offset_first_element_in_bytes, __global uchar * indices_ptr, uint indices_stride_x, uint indices_step_x, uint indices_stride_y, uint indices_step_y, uint indices_stride_z, uint indices_step_z, uint indices_offset_first_element_in_bytes)
Performs a MAX pooling of pool size equal to 2, and record max value indices for NCHW.
Note
Datatype must be passed using -DDATA_TYPE e.g. -DDATA_TYPE=half. Supported data types are F32
Pool sizes must be passed using -DPOOL_SIZE_X and -DPOOL_SIZE_Y e.g. -DPOOL_SIZE_X=13;
Tensors width and height must be passed at compile time using -DMAX_WIDTH and -DMAX_HEIGHT
Pool strides must be passed at compile time using -DSTRIDE_X and -DSTRIDE_Y which are the steps of the window along the x and y directions
Tensor padding values must be passed at compile time using PAD_TENSOR_LEFT, PAD_TENSOR_RIGHT, PAD_TENSOR_TOP and PAD_TENSOR_BOTTOM
Parameters
[in] input_ptr Pointer to the source tensor. Supported data types: F32
[in] input_stride_x Stride of the source tensor in X dimension (in bytes)
[in] input_step_x input_stride_x * number of elements along X processed per workitem(in bytes)
[in] input_stride_y Stride of the source tensor in Y dimension (in bytes)
[in] input_step_y input_stride_y * number of elements along Y processed per workitem(in bytes)
[in] input_stride_z Stride of the source tensor in Z dimension (in bytes)
[in] input_step_z input_stride_z * number of elements along Z processed per workitem(in bytes)
[in] input_offset_first_element_in_bytes The offset of the first element in the source tensor
[out] output_ptr Pointer to the destination tensor. Supported data types: same as input_ptr
[in] output_stride_x Stride of the destination tensor in X dimension (in bytes)
[in] output_step_x output_stride_x * number of elements along X processed per workitem(in bytes)
[in] output_stride_y Stride of the destination tensor in Y dimension (in bytes)
[in] output_step_y output_stride_y * number of elements along Y processed per workitem(in bytes)
[in] output_stride_z Stride of the source tensor in Z dimension (in bytes)
[in] output_step_z output_stride_z * number of elements along Z processed per workitem(in bytes)
[in] output_offset_first_element_in_bytes The offset of the first element in the destination tensor
[in] indices_ptr Pointer to the indices tensor. Supported data types: U32
[in] indices_stride_x Stride of the indices tensor in X dimension (in bytes)
[in] indices_step_x indices_stride_x * number of elements along X processed per workitem(in bytes)
[in] indices_stride_y Stride of the indices tensor in Y dimension (in bytes)
[in] indices_step_y indices_stride_y * number of elements along Y processed per workitem(in bytes)
[in] indices_stride_z Stride of the indices tensor in Z dimension (in bytes)
[in] indices_step_z indices_stride_z * number of elements along Z processed per workitem(in bytes)
[in] indices_offset_first_element_in_bytes The offset of the first element in the indices tensor
Definition at line 226 of file pooling_layer.cl.
References CONVERT_TO_TENSOR3D_STRUCT, POOL_OP, Tensor3D::ptr, arm_compute::test::validation::reference::select(), tensor3D_offset(), and VLOAD.
 {
     // Get pixels pointer
     Tensor3D input   = CONVERT_TO_TENSOR3D_STRUCT(input);
     Tensor3D output  = CONVERT_TO_TENSOR3D_STRUCT(output);
     Tensor3D indices = CONVERT_TO_TENSOR3D_STRUCT(indices);
     // Load data
     float2 data0 = VLOAD(2)(0, (__global float *)tensor3D_offset(&input, 0, 0, 0));
     float2 data1 = VLOAD(2)(0, (__global float *)tensor3D_offset(&input, 0, 1, 0));
     // Perform calculations
     float data0_max = POOL_OP(data0.s0, data0.s1);
     float data1_max = POOL_OP(data1.s0, data1.s1);
     float res       = POOL_OP(data0_max, data1_max);
     // Store result
     *(__global float *)output.ptr = res;
 #if defined(PAD_TENSOR_LEFT) && defined(PAD_TENSOR_RIGHT) && defined(PAD_TENSOR_TOP) && defined(PAD_TENSOR_BOTTOM)
     uint offset_top    = 0;
     uint offset_bottom = 0;
     offset_no_padding_nchw(&input, &offset_top, &offset_bottom);
     uint index0 = select(offset_top + 1, offset_top, isgreaterequal(data0.s0, data0.s1));
     uint index1 = select(offset_bottom + 1, offset_bottom, isgreaterequal(data1.s0, data1.s1));
     uint index  = select(index1, index0, isgreaterequal(data0_max, data1_max));
     *(__global uint *)indices.ptr = index;
 #endif //defined(PAD_TENSOR_LEFT) && defined(PAD_TENSOR_RIGHT) && defined(PAD_TENSOR_TOP) && defined(PAD_TENSOR_BOTTOM)
 }