Compute Library: AclAllocator Struct Reference
AclAllocator Struct Reference
#include <AclTypes.h>
Data Fields
void *(* alloc)(void *user_data, size_t size)
Allocate a block of size bytes of memory.
void(* free)(void *user_data, void *ptr)
Release a block of size bytes of memory.
void *(* aligned_alloc)(void *user_data, size_t size, size_t alignment)
Allocate a block of size bytes of memory.
void(* aligned_free)(void *user_data, void *ptr)
Allocate a block of size bytes of memory.
void * user_data
Detailed Description
Definition at line 98 of file AclTypes.h.
Field Documentation
aligned_alloc
void*(* aligned_alloc) (void *user_data, size_t size, size_t alignment)
Allocate a block of size bytes of memory.
Parameters
[in] user_data User provided data that can be used by the allocator
[in] size Size of the allocation
Returns
A pointer to the allocated block if successfull else NULL
Definition at line 121 of file AclTypes.h.
Referenced by AllocatorWrapper::aligned_alloc().
aligned_free
void(* aligned_free) (void *user_data, void *ptr)
Allocate a block of size bytes of memory.
Parameters
[in] user_data User provided data that can be used by the allocator
[in] size Size of the allocationUser provided information
Definition at line 127 of file AclTypes.h.
Referenced by AllocatorWrapper::aligned_free().
alloc
void*(* alloc) (void *user_data, size_t size)
Allocate a block of size bytes of memory.
Parameters
[in] user_data User provided data that can be used by the allocator
[in] size Size of the allocation
Returns
A pointer to the allocated block if successfull else NULL
Definition at line 107 of file AclTypes.h.
Referenced by AllocatorWrapper::alloc().
free
void(* free) (void *user_data, void *ptr)
Release a block of size bytes of memory.
Parameters
[in] user_data User provided data that can be used by the allocator
[in] size Size of the allocation
Definition at line 113 of file AclTypes.h.
Referenced by AllocatorWrapper::free().
user_data
void* user_data
Definition at line 130 of file AclTypes.h.
Referenced by AllocatorWrapper::aligned_alloc(), AllocatorWrapper::aligned_free(), AllocatorWrapper::alloc(), AllocatorWrapper::free(), and AllocatorWrapper::set_user_data().
The documentation for this struct was generated from the following file:
arm_compute/AclTypes.h