var searchData=
[
  ['random_2eh_15517',['Random.h',['../_random_8h.xhtml',1,'']]],
  ['range_2ecl_15518',['range.cl',['../range_8cl.xhtml',1,'']]],
  ['range_2ecpp_15519',['Range.cpp',['../_c_l_2_range_8cpp.xhtml',1,'(Global Namespace)'],['../_n_e_o_n_2_range_8cpp.xhtml',1,'(Global Namespace)'],['../reference_2_range_8cpp.xhtml',1,'(Global Namespace)']]],
  ['range_2eh_15520',['Range.h',['../_range_8h.xhtml',1,'']]],
  ['rangedataset_2eh_15521',['RangeDataset.h',['../_range_dataset_8h.xhtml',1,'']]],
  ['rawtensor_2ecpp_15522',['RawTensor.cpp',['../_raw_tensor_8cpp.xhtml',1,'']]],
  ['rawtensor_2eh_15523',['RawTensor.h',['../_raw_tensor_8h.xhtml',1,'']]],
  ['readme_2emd_15524',['README.md',['../_r_e_a_d_m_e_8md.xhtml',1,'']]],
  ['reducemean_2ecpp_15525',['ReduceMean.cpp',['../_c_l_2_reduce_mean_8cpp.xhtml',1,'(Global Namespace)'],['../_n_e_o_n_2_reduce_mean_8cpp.xhtml',1,'(Global Namespace)']]],
  ['reduction_5foperation_2ecl_15526',['reduction_operation.cl',['../reduction__operation_8cl.xhtml',1,'']]],
  ['reductionlayernode_2ecpp_15527',['ReductionLayerNode.cpp',['../_reduction_layer_node_8cpp.xhtml',1,'']]],
  ['reductionlayernode_2eh_15528',['ReductionLayerNode.h',['../_reduction_layer_node_8h.xhtml',1,'']]],
  ['reductionoperation_2ecpp_15529',['ReductionOperation.cpp',['../_c_l_2_reduction_operation_8cpp.xhtml',1,'(Global Namespace)'],['../_n_e_o_n_2_reduction_operation_8cpp.xhtml',1,'(Global Namespace)'],['../reference_2_reduction_operation_8cpp.xhtml',1,'(Global Namespace)']]],
  ['reductionoperation_2eh_15530',['ReductionOperation.h',['../_reduction_operation_8h.xhtml',1,'']]],
  ['registrars_2eh_15531',['Registrars.h',['../src_2core_2common_2_registrars_8h.xhtml',1,'(Global Namespace)'],['../tests_2framework_2_registrars_8h.xhtml',1,'(Global Namespace)']]],
  ['reinterpret_2eh_15532',['reinterpret.h',['../reinterpret_8h.xhtml',1,'']]],
  ['release_5fversion_5fand_5fchange_5flog_2edox_15533',['release_version_and_change_log.dox',['../release__version__and__change__log_8dox.xhtml',1,'']]],
  ['reorder_2ecpp_15534',['Reorder.cpp',['../_reorder_8cpp.xhtml',1,'']]],
  ['reorder_2eh_15535',['Reorder.h',['../_reorder_8h.xhtml',1,'']]],
  ['reorderlayer_2ecpp_15536',['ReorderLayer.cpp',['../_reorder_layer_8cpp.xhtml',1,'']]],
  ['reorg_5flayer_2ecl_15537',['reorg_layer.cl',['../nchw_2reorg__layer_8cl.xhtml',1,'(Global Namespace)'],['../nhwc_2reorg__layer_8cl.xhtml',1,'(Global Namespace)']]],
  ['reorglayer_2ecpp_15538',['ReorgLayer.cpp',['../_c_l_2_reorg_layer_8cpp.xhtml',1,'(Global Namespace)'],['../_n_e_o_n_2_reorg_layer_8cpp.xhtml',1,'(Global Namespace)'],['../reference_2_reorg_layer_8cpp.xhtml',1,'(Global Namespace)']]],
  ['reorglayer_2eh_15539',['ReorgLayer.h',['../_reorg_layer_8h.xhtml',1,'']]],
  ['reorglayernode_2ecpp_15540',['ReorgLayerNode.cpp',['../_reorg_layer_node_8cpp.xhtml',1,'']]],
  ['reorglayernode_2eh_15541',['ReorgLayerNode.h',['../_reorg_layer_node_8h.xhtml',1,'']]],
  ['repeat_2eh_15542',['repeat.h',['../repeat_8h.xhtml',1,'']]],
  ['reshape_2ecpp_15543',['Reshape.cpp',['../_reshape_8cpp.xhtml',1,'']]],
  ['reshape_5flayer_2ecl_15544',['reshape_layer.cl',['../reshape__layer_8cl.xhtml',1,'']]],
  ['reshapeattributes_2ecpp_15545',['ReshapeAttributes.cpp',['../_reshape_attributes_8cpp.xhtml',1,'']]],
  ['reshapeattributes_2eh_15546',['ReshapeAttributes.h',['../_reshape_attributes_8h.xhtml',1,'']]],
  ['reshapelayer_2ecpp_15547',['ReshapeLayer.cpp',['../src_2graph_2nodes_2_reshape_layer_8cpp.xhtml',1,'(Global Namespace)'],['../tests_2validation_2_c_l_2_reshape_layer_8cpp.xhtml',1,'(Global Namespace)'],['../tests_2validation_2_n_e_o_n_2_reshape_layer_8cpp.xhtml',1,'(Global Namespace)'],['../tests_2validation_2reference_2_reshape_layer_8cpp.xhtml',1,'(Global Namespace)']]],
  ['reshapelayer_2eh_15548',['ReshapeLayer.h',['../_reshape_layer_8h.xhtml',1,'']]],
  ['reshapelayernode_2eh_15549',['ReshapeLayerNode.h',['../_reshape_layer_node_8h.xhtml',1,'']]],
  ['resize_2ecpp_15550',['Resize.cpp',['../_resize_8cpp.xhtml',1,'']]],
  ['resizeattributes_2ecpp_15551',['ResizeAttributes.cpp',['../_resize_attributes_8cpp.xhtml',1,'']]],
  ['resizeattributes_2eh_15552',['ResizeAttributes.h',['../_resize_attributes_8h.xhtml',1,'']]],
  ['resizelayernode_2ecpp_15553',['ResizeLayerNode.cpp',['../_resize_layer_node_8cpp.xhtml',1,'']]],
  ['resizelayernode_2eh_15554',['ResizeLayerNode.h',['../_resize_layer_node_8h.xhtml',1,'']]],
  ['rev64_2eh_15555',['rev64.h',['../rev64_8h.xhtml',1,'']]],
  ['reverse_2ecl_15556',['reverse.cl',['../reverse_8cl.xhtml',1,'']]],
  ['reverse_2ecpp_15557',['Reverse.cpp',['../_c_l_2_reverse_8cpp.xhtml',1,'(Global Namespace)'],['../_n_e_o_n_2_reverse_8cpp.xhtml',1,'(Global Namespace)'],['../reference_2_reverse_8cpp.xhtml',1,'(Global Namespace)']]],
  ['reverse_2eh_15558',['Reverse.h',['../_reverse_8h.xhtml',1,'']]],
  ['rnnlayer_2ecpp_15559',['RNNLayer.cpp',['../_c_l_2_r_n_n_layer_8cpp.xhtml',1,'(Global Namespace)'],['../_n_e_o_n_2_r_n_n_layer_8cpp.xhtml',1,'(Global Namespace)']]],
  ['roi_5falign_5flayer_2ecl_15560',['roi_align_layer.cl',['../roi__align__layer_8cl.xhtml',1,'']]],
  ['roi_5falign_5flayer_5fquantized_2ecl_15561',['roi_align_layer_quantized.cl',['../roi__align__layer__quantized_8cl.xhtml',1,'']]],
  ['roi_5fpooling_5flayer_2ecl_15562',['roi_pooling_layer.cl',['../roi__pooling__layer_8cl.xhtml',1,'']]],
  ['roialignlayer_2ecpp_15563',['ROIAlignLayer.cpp',['../_c_l_2_r_o_i_align_layer_8cpp.xhtml',1,'(Global Namespace)'],['../_n_e_o_n_2_r_o_i_align_layer_8cpp.xhtml',1,'(Global Namespace)'],['../reference_2_r_o_i_align_layer_8cpp.xhtml',1,'(Global Namespace)']]],
  ['roialignlayer_2eh_15564',['ROIAlignLayer.h',['../_r_o_i_align_layer_8h.xhtml',1,'']]],
  ['roialignlayernode_2ecpp_15565',['ROIAlignLayerNode.cpp',['../_r_o_i_align_layer_node_8cpp.xhtml',1,'']]],
  ['roialignlayernode_2eh_15566',['ROIAlignLayerNode.h',['../_r_o_i_align_layer_node_8h.xhtml',1,'']]],
  ['roipoolinglayer_2ecpp_15567',['ROIPoolingLayer.cpp',['../_c_l_2_r_o_i_pooling_layer_8cpp.xhtml',1,'(Global Namespace)'],['../_n_e_o_n_2_r_o_i_pooling_layer_8cpp.xhtml',1,'(Global Namespace)'],['../reference_2_r_o_i_pooling_layer_8cpp.xhtml',1,'(Global Namespace)']]],
  ['roipoolinglayer_2eh_15568',['ROIPoolingLayer.h',['../_r_o_i_pooling_layer_8h.xhtml',1,'']]],
  ['round_2eh_15569',['round.h',['../round_8h.xhtml',1,'']]],
  ['rounding_2ecpp_15570',['Rounding.cpp',['../_rounding_8cpp.xhtml',1,'']]],
  ['rounding_2eh_15571',['Rounding.h',['../arm__compute_2core_2_rounding_8h.xhtml',1,'(Global Namespace)'],['../support_2_rounding_8h.xhtml',1,'(Global Namespace)']]],
  ['roundlayer_2ecpp_15572',['RoundLayer.cpp',['../_round_layer_8cpp.xhtml',1,'']]],
  ['rowsum_5findirect_5fs8_2ecpp_15573',['rowsum_indirect_s8.cpp',['../rowsum__indirect__s8_8cpp.xhtml',1,'']]],
  ['rowsum_5findirect_5fu8_2ecpp_15574',['rowsum_indirect_u8.cpp',['../rowsum__indirect__u8_8cpp.xhtml',1,'']]],
  ['rsqrtlayer_2ecpp_15575',['RsqrtLayer.cpp',['../_rsqrt_layer_8cpp.xhtml',1,'']]],
  ['runexample_2ecpp_15576',['RunExample.cpp',['../benchmark__examples_2_run_example_8cpp.xhtml',1,'(Global Namespace)'],['../validate__examples_2_run_example_8cpp.xhtml',1,'(Global Namespace)']]],
  ['runtimecontext_2ecpp_15577',['RuntimeContext.cpp',['../src_2runtime_2_runtime_context_8cpp.xhtml',1,'(Global Namespace)'],['../tests_2validation_2_n_e_o_n_2_u_n_i_t_2_runtime_context_8cpp.xhtml',1,'(Global Namespace)']]],
  ['runtimecontext_2eh_15578',['RuntimeContext.h',['../_runtime_context_8h.xhtml',1,'']]]
];
