var searchData=
[
  ['data_5flayout_2edox_14525',['data_layout.dox',['../data__layout_8dox.xhtml',1,'']]],
  ['data_5ftype_2edox_14526',['data_type.dox',['../data__type_8dox.xhtml',1,'']]],
  ['datalayervisitor_2ecpp_14527',['DataLayerVisitor.cpp',['../_data_layer_visitor_8cpp.xhtml',1,'']]],
  ['datalayervisitor_2eh_14528',['DataLayerVisitor.h',['../_data_layer_visitor_8h.xhtml',1,'']]],
  ['dataset_2eh_14529',['Dataset.h',['../_dataset_8h.xhtml',1,'']]],
  ['datasetmodes_2ecpp_14530',['DatasetModes.cpp',['../_dataset_modes_8cpp.xhtml',1,'']]],
  ['datasetmodes_2eh_14531',['DatasetModes.h',['../_dataset_modes_8h.xhtml',1,'']]],
  ['datasets_2eh_14532',['Datasets.h',['../_datasets_8h.xhtml',1,'']]],
  ['deconvolution_5flayer_2ecl_14533',['deconvolution_layer.cl',['../deconvolution__layer_8cl.xhtml',1,'']]],
  ['deconvolutionlayer_2ecpp_14534',['DeconvolutionLayer.cpp',['../_c_l_2_deconvolution_layer_8cpp.xhtml',1,'(Global Namespace)'],['../_n_e_o_n_2_deconvolution_layer_8cpp.xhtml',1,'(Global Namespace)'],['../reference_2_deconvolution_layer_8cpp.xhtml',1,'(Global Namespace)']]],
  ['deconvolutionlayer_2eh_14535',['DeconvolutionLayer.h',['../_deconvolution_layer_8h.xhtml',1,'']]],
  ['deconvolutionlayernode_2ecpp_14536',['DeconvolutionLayerNode.cpp',['../_deconvolution_layer_node_8cpp.xhtml',1,'']]],
  ['deconvolutionlayernode_2eh_14537',['DeconvolutionLayerNode.h',['../_deconvolution_layer_node_8h.xhtml',1,'']]],
  ['deepcopy_2eh_14538',['DeepCopy.h',['../_deep_copy_8h.xhtml',1,'']]],
  ['defaultlwsheuristics_2ecpp_14539',['DefaultLWSHeuristics.cpp',['../_default_l_w_s_heuristics_8cpp.xhtml',1,'']]],
  ['defaultlwsheuristics_2eh_14540',['DefaultLWSHeuristics.h',['../_default_l_w_s_heuristics_8h.xhtml',1,'']]],
  ['dependencygraph_2eh_14541',['DependencyGraph.h',['../_dependency_graph_8h.xhtml',1,'']]],
  ['depth_5fto_5fspace_2ecl_14542',['depth_to_space.cl',['../nchw_2depth__to__space_8cl.xhtml',1,'(Global Namespace)'],['../nhwc_2depth__to__space_8cl.xhtml',1,'(Global Namespace)']]],
  ['depthconcatenatelayer_2ecpp_14543',['DepthConcatenateLayer.cpp',['../_c_l_2_depth_concatenate_layer_8cpp.xhtml',1,'(Global Namespace)'],['../_n_e_o_n_2_depth_concatenate_layer_8cpp.xhtml',1,'(Global Namespace)'],['../reference_2_depth_concatenate_layer_8cpp.xhtml',1,'(Global Namespace)']]],
  ['depthconcatenatelayer_2eh_14544',['DepthConcatenateLayer.h',['../_depth_concatenate_layer_8h.xhtml',1,'']]],
  ['depthconcatsubtensormutator_2ecpp_14545',['DepthConcatSubTensorMutator.cpp',['../_depth_concat_sub_tensor_mutator_8cpp.xhtml',1,'']]],
  ['depthconcatsubtensormutator_2eh_14546',['DepthConcatSubTensorMutator.h',['../_depth_concat_sub_tensor_mutator_8h.xhtml',1,'']]],
  ['depthconvertlayer_2ecpp_14547',['DepthConvertLayer.cpp',['../_c_l_2_depth_convert_layer_8cpp.xhtml',1,'(Global Namespace)'],['../_n_e_o_n_2_depth_convert_layer_8cpp.xhtml',1,'(Global Namespace)'],['../reference_2_depth_convert_layer_8cpp.xhtml',1,'(Global Namespace)']]],
  ['depthconvertlayer_2eh_14548',['DepthConvertLayer.h',['../_depth_convert_layer_8h.xhtml',1,'']]],
  ['depthfirst_5fdriver_2ehpp_14549',['depthfirst_driver.hpp',['../depthwise_2depthfirst__driver_8hpp.xhtml',1,'(Global Namespace)'],['../pooling_2depthfirst__driver_8hpp.xhtml',1,'(Global Namespace)']]],
  ['depthtospacelayer_2ecpp_14550',['DepthToSpaceLayer.cpp',['../_c_l_2_depth_to_space_layer_8cpp.xhtml',1,'(Global Namespace)'],['../_n_e_o_n_2_depth_to_space_layer_8cpp.xhtml',1,'(Global Namespace)'],['../reference_2_depth_to_space_layer_8cpp.xhtml',1,'(Global Namespace)']]],
  ['depthtospacelayer_2eh_14551',['DepthToSpaceLayer.h',['../_depth_to_space_layer_8h.xhtml',1,'']]],
  ['depthtospacelayernode_2ecpp_14552',['DepthToSpaceLayerNode.cpp',['../_depth_to_space_layer_node_8cpp.xhtml',1,'']]],
  ['depthtospacelayernode_2eh_14553',['DepthToSpaceLayerNode.h',['../_depth_to_space_layer_node_8h.xhtml',1,'']]],
  ['depthwise_5fcommon_2ecpp_14554',['depthwise_common.cpp',['../depthwise__common_8cpp.xhtml',1,'']]],
  ['depthwise_5fdepthfirst_2ehpp_14555',['depthwise_depthfirst.hpp',['../depthwise__depthfirst_8hpp.xhtml',1,'']]],
  ['depthwise_5fdepthfirst_5fgeneric_2ehpp_14556',['depthwise_depthfirst_generic.hpp',['../depthwise__depthfirst__generic_8hpp.xhtml',1,'']]],
  ['depthwise_5fdepthfirst_5fmultiplier_2ehpp_14557',['depthwise_depthfirst_multiplier.hpp',['../depthwise__depthfirst__multiplier_8hpp.xhtml',1,'']]],
  ['depthwise_5ffp16_2ecpp_14558',['depthwise_fp16.cpp',['../depthwise__fp16_8cpp.xhtml',1,'']]],
  ['depthwise_5ffp32_2ecpp_14559',['depthwise_fp32.cpp',['../depthwise__fp32_8cpp.xhtml',1,'']]],
  ['depthwise_5fimplementation_2ehpp_14560',['depthwise_implementation.hpp',['../depthwise__implementation_8hpp.xhtml',1,'']]],
  ['depthwise_5fimplementation_5fconstraints_2ehpp_14561',['depthwise_implementation_constraints.hpp',['../depthwise__implementation__constraints_8hpp.xhtml',1,'']]],
  ['depthwise_5fplanar_2ehpp_14562',['depthwise_planar.hpp',['../depthwise__planar_8hpp.xhtml',1,'']]],
  ['depthwise_5fs8q_2ecpp_14563',['depthwise_s8q.cpp',['../depthwise__s8q_8cpp.xhtml',1,'']]],
  ['depthwise_5fstrategies_5fcommon_2ecpp_14564',['depthwise_strategies_common.cpp',['../depthwise__strategies__common_8cpp.xhtml',1,'']]],
  ['depthwise_5fstrategies_5fcommon_2ehpp_14565',['depthwise_strategies_common.hpp',['../depthwise__strategies__common_8hpp.xhtml',1,'']]],
  ['depthwise_5fu8q_2ecpp_14566',['depthwise_u8q.cpp',['../depthwise__u8q_8cpp.xhtml',1,'']]],
  ['depthwise_5fu8s8u8q_2ecpp_14567',['depthwise_u8s8u8q.cpp',['../depthwise__u8s8u8q_8cpp.xhtml',1,'']]],
  ['depthwiseconv2d_2ecpp_14568',['DepthwiseConv2d.cpp',['../_depthwise_conv2d_8cpp.xhtml',1,'']]],
  ['depthwiseconv2dattributes_2ecpp_14569',['DepthwiseConv2dAttributes.cpp',['../_depthwise_conv2d_attributes_8cpp.xhtml',1,'']]],
  ['depthwiseconv2dattributes_2eh_14570',['DepthwiseConv2dAttributes.h',['../_depthwise_conv2d_attributes_8h.xhtml',1,'']]],
  ['depthwiseconvolutionlayer_2ecpp_14571',['DepthwiseConvolutionLayer.cpp',['../_c_l_2_depthwise_convolution_layer_8cpp.xhtml',1,'(Global Namespace)'],['../_n_e_o_n_2_depthwise_convolution_layer_8cpp.xhtml',1,'(Global Namespace)'],['../reference_2_depthwise_convolution_layer_8cpp.xhtml',1,'(Global Namespace)']]],
  ['depthwiseconvolutionlayer_2eh_14572',['DepthwiseConvolutionLayer.h',['../_depthwise_convolution_layer_8h.xhtml',1,'']]],
  ['depthwiseconvolutionlayernative_2ecpp_14573',['DepthwiseConvolutionLayerNative.cpp',['../_c_l_2_depthwise_convolution_layer_native_8cpp.xhtml',1,'(Global Namespace)'],['../_n_e_o_n_2_depthwise_convolution_layer_native_8cpp.xhtml',1,'(Global Namespace)']]],
  ['depthwiseconvolutionlayernode_2ecpp_14574',['DepthwiseConvolutionLayerNode.cpp',['../_depthwise_convolution_layer_node_8cpp.xhtml',1,'']]],
  ['depthwiseconvolutionlayernode_2eh_14575',['DepthwiseConvolutionLayerNode.h',['../_depthwise_convolution_layer_node_8h.xhtml',1,'']]],
  ['depthwiseseparableconvolutionlayer_2eh_14576',['DepthwiseSeparableConvolutionLayer.h',['../_depthwise_separable_convolution_layer_8h.xhtml',1,'']]],
  ['dequantization_5flayer_2ecl_14577',['dequantization_layer.cl',['../common_2dequantization__layer_8cl.xhtml',1,'(Global Namespace)'],['../nchw_2dequantization__layer_8cl.xhtml',1,'(Global Namespace)'],['../nhwc_2dequantization__layer_8cl.xhtml',1,'(Global Namespace)']]],
  ['dequantizationlayer_2ecpp_14578',['DequantizationLayer.cpp',['../_c_l_2_dequantization_layer_8cpp.xhtml',1,'(Global Namespace)'],['../_n_e_o_n_2_dequantization_layer_8cpp.xhtml',1,'(Global Namespace)'],['../reference_2_dequantization_layer_8cpp.xhtml',1,'(Global Namespace)']]],
  ['dequantizationlayer_2eh_14579',['DequantizationLayer.h',['../_dequantization_layer_8h.xhtml',1,'']]],
  ['dequantizationlayernode_2ecpp_14580',['DequantizationLayerNode.cpp',['../_dequantization_layer_node_8cpp.xhtml',1,'']]],
  ['dequantizationlayernode_2eh_14581',['DequantizationLayerNode.h',['../_dequantization_layer_node_8h.xhtml',1,'']]],
  ['detectionoutputlayernode_2ecpp_14582',['DetectionOutputLayerNode.cpp',['../_detection_output_layer_node_8cpp.xhtml',1,'']]],
  ['detectionoutputlayernode_2eh_14583',['DetectionOutputLayerNode.h',['../_detection_output_layer_node_8h.xhtml',1,'']]],
  ['detectionpostprocesslayer_2ecpp_14584',['DetectionPostProcessLayer.cpp',['../_c_p_p_2_detection_post_process_layer_8cpp.xhtml',1,'(Global Namespace)'],['../_n_e_o_n_2_detection_post_process_layer_8cpp.xhtml',1,'(Global Namespace)']]],
  ['detectionpostprocesslayernode_2ecpp_14585',['DetectionPostProcessLayerNode.cpp',['../_detection_post_process_layer_node_8cpp.xhtml',1,'']]],
  ['detectionpostprocesslayernode_2eh_14586',['DetectionPostProcessLayerNode.h',['../_detection_post_process_layer_node_8h.xhtml',1,'']]],
  ['dft_2ecpp_14587',['DFT.cpp',['../_c_p_p_2_d_f_t_8cpp.xhtml',1,'(Global Namespace)'],['../reference_2_d_f_t_8cpp.xhtml',1,'(Global Namespace)']]],
  ['dft_2eh_14588',['DFT.h',['../_d_f_t_8h.xhtml',1,'']]],
  ['dilatedconvolutionlayer_2ecpp_14589',['DilatedConvolutionLayer.cpp',['../_c_l_2_dilated_convolution_layer_8cpp.xhtml',1,'(Global Namespace)'],['../_n_e_o_n_2_dilated_convolution_layer_8cpp.xhtml',1,'(Global Namespace)']]],
  ['dimensions_2eh_14590',['Dimensions.h',['../_dimensions_8h.xhtml',1,'']]],
  ['direct_5fconvolution_2ecl_14591',['direct_convolution.cl',['../nchw_2direct__convolution_8cl.xhtml',1,'(Global Namespace)'],['../nhwc_2direct__convolution_8cl.xhtml',1,'(Global Namespace)']]],
  ['direct_5fconvolution3d_2ecl_14592',['direct_convolution3d.cl',['../direct__convolution3d_8cl.xhtml',1,'']]],
  ['directconv2d_2ecpp_14593',['DirectConv2d.cpp',['../_direct_conv2d_8cpp.xhtml',1,'']]],
  ['directconvolutionlayer_2ecpp_14594',['DirectConvolutionLayer.cpp',['../_c_l_2_direct_convolution_layer_8cpp.xhtml',1,'(Global Namespace)'],['../_n_e_o_n_2_direct_convolution_layer_8cpp.xhtml',1,'(Global Namespace)']]],
  ['div_2eh_14595',['div.h',['../div_8h.xhtml',1,'']]],
  ['dotgraphprinter_2ecpp_14596',['DotGraphPrinter.cpp',['../_dot_graph_printer_8cpp.xhtml',1,'']]],
  ['dotgraphprinter_2eh_14597',['DotGraphPrinter.h',['../_dot_graph_printer_8h.xhtml',1,'']]],
  ['dummynode_2ecpp_14598',['DummyNode.cpp',['../_dummy_node_8cpp.xhtml',1,'']]],
  ['dummynode_2eh_14599',['DummyNode.h',['../_dummy_node_8h.xhtml',1,'']]],
  ['dup_5fn_2eh_14600',['dup_n.h',['../dup__n_8h.xhtml',1,'']]],
  ['dwc_5fnative_5ffp_5fnhwc_2ecl_14601',['dwc_native_fp_nhwc.cl',['../dwc__native__fp__nhwc_8cl.xhtml',1,'']]],
  ['dwc_5fnative_5fquantized_5fnhwc_2ecl_14602',['dwc_native_quantized_nhwc.cl',['../dwc__native__quantized__nhwc_8cl.xhtml',1,'']]],
  ['dynamictensor_2ecpp_14603',['DynamicTensor.cpp',['../_c_l_2_u_n_i_t_2_dynamic_tensor_8cpp.xhtml',1,'(Global Namespace)'],['../_n_e_o_n_2_u_n_i_t_2_dynamic_tensor_8cpp.xhtml',1,'(Global Namespace)']]]
];
