var searchData=
[
  ['backendregistrar_11964',['BackendRegistrar',['../classarm__compute_1_1graph_1_1backends_1_1detail_1_1_backend_registrar.xhtml',1,'arm_compute::graph::backends::detail']]],
  ['backendregistry_11965',['BackendRegistry',['../classarm__compute_1_1graph_1_1backends_1_1_backend_registry.xhtml',1,'arm_compute::graph::backends']]],
  ['barrier_11966',['barrier',['../classarm__gemm_1_1barrier.xhtml',1,'arm_gemm']]],
  ['batchnormalizationlayer_11967',['BatchNormalizationLayer',['../classarm__compute_1_1graph_1_1frontend_1_1_batch_normalization_layer.xhtml',1,'arm_compute::graph::frontend']]],
  ['batchnormalizationlayernode_11968',['BatchNormalizationLayerNode',['../classarm__compute_1_1graph_1_1_batch_normalization_layer_node.xhtml',1,'arm_compute::graph']]],
  ['benchmarkresult_11969',['BenchmarkResult',['../class_gemm_tuner_1_1_benchmark_result.xhtml',1,'GemmTuner']]],
  ['bfloat16_11970',['bfloat16',['../classarm__compute_1_1bfloat16.xhtml',1,'arm_compute']]],
  ['blobinfo_11971',['BlobInfo',['../structarm__compute_1_1_blob_info.xhtml',1,'arm_compute']]],
  ['bloblifetimemanager_11972',['BlobLifetimeManager',['../classarm__compute_1_1_blob_lifetime_manager.xhtml',1,'arm_compute']]],
  ['blobmemorypool_11973',['BlobMemoryPool',['../classarm__compute_1_1_blob_memory_pool.xhtml',1,'arm_compute']]],
  ['bordersize_11974',['BorderSize',['../structarm__compute_1_1_border_size.xhtml',1,'arm_compute']]],
  ['boundingboxtransforminfo_11975',['BoundingBoxTransformInfo',['../classarm__compute_1_1_bounding_box_transform_info.xhtml',1,'arm_compute']]],
  ['boundingboxtransformlayer_11976',['BoundingBoxTransformLayer',['../classarm__compute_1_1graph_1_1frontend_1_1_bounding_box_transform_layer.xhtml',1,'arm_compute::graph::frontend']]],
  ['boundingboxtransformlayernode_11977',['BoundingBoxTransformLayerNode',['../classarm__compute_1_1graph_1_1_bounding_box_transform_layer_node.xhtml',1,'arm_compute::graph']]],
  ['boxnmslimitinfo_11978',['BoxNMSLimitInfo',['../classarm__compute_1_1_box_n_m_s_limit_info.xhtml',1,'arm_compute']]],
  ['branchnode_11979',['BranchNode',['../structarm__compute_1_1mlgo_1_1_heuristic_tree_1_1_branch_node.xhtml',1,'arm_compute::mlgo::HeuristicTree']]],
  ['brelu_11980',['brelu',['../structarm__compute_1_1detail_1_1brelu.xhtml',1,'arm_compute::detail']]]
];
