var searchData=
[
  ['random_2eh_15723',['Random.h',['../_random_8h.xhtml',1,'']]],
  ['range_2ecl_15724',['range.cl',['../range_8cl.xhtml',1,'']]],
  ['range_2ecpp_15725',['Range.cpp',['../_c_l_2_range_8cpp.xhtml',1,'(Global Namespace)'],['../_n_e_o_n_2_range_8cpp.xhtml',1,'(Global Namespace)'],['../reference_2_range_8cpp.xhtml',1,'(Global Namespace)']]],
  ['range_2eh_15726',['Range.h',['../_range_8h.xhtml',1,'']]],
  ['rangedataset_2eh_15727',['RangeDataset.h',['../_range_dataset_8h.xhtml',1,'']]],
  ['rawtensor_2ecpp_15728',['RawTensor.cpp',['../_raw_tensor_8cpp.xhtml',1,'']]],
  ['rawtensor_2eh_15729',['RawTensor.h',['../_raw_tensor_8h.xhtml',1,'']]],
  ['readme_2emd_15730',['README.md',['../_r_e_a_d_m_e_8md.xhtml',1,'']]],
  ['reducemean_2ecpp_15731',['ReduceMean.cpp',['../_c_l_2_reduce_mean_8cpp.xhtml',1,'(Global Namespace)'],['../_n_e_o_n_2_reduce_mean_8cpp.xhtml',1,'(Global Namespace)']]],
  ['reduction_5foperation_2ecl_15732',['reduction_operation.cl',['../reduction__operation_8cl.xhtml',1,'']]],
  ['reductionlayernode_2ecpp_15733',['ReductionLayerNode.cpp',['../_reduction_layer_node_8cpp.xhtml',1,'']]],
  ['reductionlayernode_2eh_15734',['ReductionLayerNode.h',['../_reduction_layer_node_8h.xhtml',1,'']]],
  ['reductionoperation_2ecpp_15735',['ReductionOperation.cpp',['../_c_l_2_reduction_operation_8cpp.xhtml',1,'(Global Namespace)'],['../_n_e_o_n_2_reduction_operation_8cpp.xhtml',1,'(Global Namespace)'],['../reference_2_reduction_operation_8cpp.xhtml',1,'(Global Namespace)']]],
  ['reductionoperation_2eh_15736',['ReductionOperation.h',['../_reduction_operation_8h.xhtml',1,'']]],
  ['registrars_2eh_15737',['Registrars.h',['../src_2core_2common_2_registrars_8h.xhtml',1,'(Global Namespace)'],['../tests_2framework_2_registrars_8h.xhtml',1,'(Global Namespace)']]],
  ['reinterpret_2eh_15738',['reinterpret.h',['../reinterpret_8h.xhtml',1,'']]],
  ['release_5fversion_5fand_5fchange_5flog_2edox_15739',['release_version_and_change_log.dox',['../release__version__and__change__log_8dox.xhtml',1,'']]],
  ['reorder_2ecpp_15740',['Reorder.cpp',['../_reorder_8cpp.xhtml',1,'']]],
  ['reorder_2eh_15741',['Reorder.h',['../_reorder_8h.xhtml',1,'']]],
  ['reorderlayer_2ecpp_15742',['ReorderLayer.cpp',['../_reorder_layer_8cpp.xhtml',1,'']]],
  ['reorg_5flayer_2ecl_15743',['reorg_layer.cl',['../nchw_2reorg__layer_8cl.xhtml',1,'(Global Namespace)'],['../nhwc_2reorg__layer_8cl.xhtml',1,'(Global Namespace)']]],
  ['reorglayer_2ecpp_15744',['ReorgLayer.cpp',['../_c_l_2_reorg_layer_8cpp.xhtml',1,'(Global Namespace)'],['../_n_e_o_n_2_reorg_layer_8cpp.xhtml',1,'(Global Namespace)'],['../reference_2_reorg_layer_8cpp.xhtml',1,'(Global Namespace)']]],
  ['reorglayer_2eh_15745',['ReorgLayer.h',['../_reorg_layer_8h.xhtml',1,'']]],
  ['reorglayernode_2ecpp_15746',['ReorgLayerNode.cpp',['../_reorg_layer_node_8cpp.xhtml',1,'']]],
  ['reorglayernode_2eh_15747',['ReorgLayerNode.h',['../_reorg_layer_node_8h.xhtml',1,'']]],
  ['repeat_2eh_15748',['repeat.h',['../repeat_8h.xhtml',1,'']]],
  ['reshape_2ecpp_15749',['Reshape.cpp',['../_reshape_8cpp.xhtml',1,'']]],
  ['reshape_5flayer_2ecl_15750',['reshape_layer.cl',['../reshape__layer_8cl.xhtml',1,'']]],
  ['reshapeattributes_2ecpp_15751',['ReshapeAttributes.cpp',['../_reshape_attributes_8cpp.xhtml',1,'']]],
  ['reshapeattributes_2eh_15752',['ReshapeAttributes.h',['../_reshape_attributes_8h.xhtml',1,'']]],
  ['reshapelayer_2ecpp_15753',['ReshapeLayer.cpp',['../src_2graph_2nodes_2_reshape_layer_8cpp.xhtml',1,'(Global Namespace)'],['../tests_2validation_2_c_l_2_reshape_layer_8cpp.xhtml',1,'(Global Namespace)'],['../tests_2validation_2_n_e_o_n_2_reshape_layer_8cpp.xhtml',1,'(Global Namespace)'],['../tests_2validation_2reference_2_reshape_layer_8cpp.xhtml',1,'(Global Namespace)']]],
  ['reshapelayer_2eh_15754',['ReshapeLayer.h',['../_reshape_layer_8h.xhtml',1,'']]],
  ['reshapelayernode_2eh_15755',['ReshapeLayerNode.h',['../_reshape_layer_node_8h.xhtml',1,'']]],
  ['resize_2ecpp_15756',['Resize.cpp',['../_resize_8cpp.xhtml',1,'']]],
  ['resizeattributes_2ecpp_15757',['ResizeAttributes.cpp',['../_resize_attributes_8cpp.xhtml',1,'']]],
  ['resizeattributes_2eh_15758',['ResizeAttributes.h',['../_resize_attributes_8h.xhtml',1,'']]],
  ['resizelayernode_2ecpp_15759',['ResizeLayerNode.cpp',['../_resize_layer_node_8cpp.xhtml',1,'']]],
  ['resizelayernode_2eh_15760',['ResizeLayerNode.h',['../_resize_layer_node_8h.xhtml',1,'']]],
  ['rev64_2eh_15761',['rev64.h',['../rev64_8h.xhtml',1,'']]],
  ['reverse_2ecl_15762',['reverse.cl',['../reverse_8cl.xhtml',1,'']]],
  ['reverse_2ecpp_15763',['Reverse.cpp',['../_c_l_2_reverse_8cpp.xhtml',1,'(Global Namespace)'],['../_n_e_o_n_2_reverse_8cpp.xhtml',1,'(Global Namespace)'],['../reference_2_reverse_8cpp.xhtml',1,'(Global Namespace)']]],
  ['reverse_2eh_15764',['Reverse.h',['../_reverse_8h.xhtml',1,'']]],
  ['rnnlayer_2ecpp_15765',['RNNLayer.cpp',['../_c_l_2_r_n_n_layer_8cpp.xhtml',1,'(Global Namespace)'],['../_n_e_o_n_2_r_n_n_layer_8cpp.xhtml',1,'(Global Namespace)']]],
  ['roi_5falign_5flayer_2ecl_15766',['roi_align_layer.cl',['../roi__align__layer_8cl.xhtml',1,'']]],
  ['roi_5falign_5flayer_5fquantized_2ecl_15767',['roi_align_layer_quantized.cl',['../roi__align__layer__quantized_8cl.xhtml',1,'']]],
  ['roi_5fpooling_5flayer_2ecl_15768',['roi_pooling_layer.cl',['../roi__pooling__layer_8cl.xhtml',1,'']]],
  ['roialignlayer_2ecpp_15769',['ROIAlignLayer.cpp',['../_c_l_2_r_o_i_align_layer_8cpp.xhtml',1,'(Global Namespace)'],['../_n_e_o_n_2_r_o_i_align_layer_8cpp.xhtml',1,'(Global Namespace)'],['../reference_2_r_o_i_align_layer_8cpp.xhtml',1,'(Global Namespace)']]],
  ['roialignlayer_2eh_15770',['ROIAlignLayer.h',['../_r_o_i_align_layer_8h.xhtml',1,'']]],
  ['roialignlayernode_2ecpp_15771',['ROIAlignLayerNode.cpp',['../_r_o_i_align_layer_node_8cpp.xhtml',1,'']]],
  ['roialignlayernode_2eh_15772',['ROIAlignLayerNode.h',['../_r_o_i_align_layer_node_8h.xhtml',1,'']]],
  ['roipoolinglayer_2ecpp_15773',['ROIPoolingLayer.cpp',['../_c_l_2_r_o_i_pooling_layer_8cpp.xhtml',1,'(Global Namespace)'],['../_n_e_o_n_2_r_o_i_pooling_layer_8cpp.xhtml',1,'(Global Namespace)'],['../reference_2_r_o_i_pooling_layer_8cpp.xhtml',1,'(Global Namespace)']]],
  ['roipoolinglayer_2eh_15774',['ROIPoolingLayer.h',['../_r_o_i_pooling_layer_8h.xhtml',1,'']]],
  ['round_2eh_15775',['round.h',['../round_8h.xhtml',1,'']]],
  ['rounding_2ecpp_15776',['Rounding.cpp',['../_rounding_8cpp.xhtml',1,'']]],
  ['rounding_2eh_15777',['Rounding.h',['../arm__compute_2core_2_rounding_8h.xhtml',1,'(Global Namespace)'],['../support_2_rounding_8h.xhtml',1,'(Global Namespace)']]],
  ['roundlayer_2ecpp_15778',['RoundLayer.cpp',['../_round_layer_8cpp.xhtml',1,'']]],
  ['rowsum_5findirect_5fs8_2ecpp_15779',['rowsum_indirect_s8.cpp',['../rowsum__indirect__s8_8cpp.xhtml',1,'']]],
  ['rowsum_5findirect_5fu8_2ecpp_15780',['rowsum_indirect_u8.cpp',['../rowsum__indirect__u8_8cpp.xhtml',1,'']]],
  ['rsqrtlayer_2ecpp_15781',['RsqrtLayer.cpp',['../_rsqrt_layer_8cpp.xhtml',1,'']]],
  ['runexample_2ecpp_15782',['RunExample.cpp',['../benchmark__examples_2_run_example_8cpp.xhtml',1,'(Global Namespace)'],['../validate__examples_2_run_example_8cpp.xhtml',1,'(Global Namespace)']]],
  ['runtimecontext_2ecpp_15783',['RuntimeContext.cpp',['../src_2runtime_2_runtime_context_8cpp.xhtml',1,'(Global Namespace)'],['../tests_2validation_2_n_e_o_n_2_u_n_i_t_2_runtime_context_8cpp.xhtml',1,'(Global Namespace)']]],
  ['runtimecontext_2eh_15784',['RuntimeContext.h',['../_runtime_context_8h.xhtml',1,'']]]
];
