var searchData=
[
  ['macros_2eh_15239',['Macros.h',['../arm__compute_2core_2utils_2logging_2_macros_8h.xhtml',1,'(Global Namespace)'],['../arm__compute_2core_2utils_2misc_2_macros_8h.xhtml',1,'(Global Namespace)'],['../src_2common_2utils_2_macros_8h.xhtml',1,'(Global Namespace)'],['../src_2core_2common_2_macros_8h.xhtml',1,'(Global Namespace)'],['../tests_2framework_2_macros_8h.xhtml',1,'(Global Namespace)']]],
  ['main_2ecpp_15240',['main.cpp',['../main_8cpp.xhtml',1,'']]],
  ['malicounter_2ecpp_15241',['MaliCounter.cpp',['../_mali_counter_8cpp.xhtml',1,'']]],
  ['malicounter_2eh_15242',['MaliCounter.h',['../_mali_counter_8h.xhtml',1,'']]],
  ['mat_5fmul_2ecl_15243',['mat_mul.cl',['../mat__mul_8cl.xhtml',1,'']]],
  ['mat_5fmul_5fmmul_2ecl_15244',['mat_mul_mmul.cl',['../mat__mul__mmul_8cl.xhtml',1,'']]],
  ['mat_5fmul_5fquantized_2ecl_15245',['mat_mul_quantized.cl',['../mat__mul__quantized_8cl.xhtml',1,'']]],
  ['mat_5fmul_5fquantized_5fmmul_2ecl_15246',['mat_mul_quantized_mmul.cl',['../mat__mul__quantized__mmul_8cl.xhtml',1,'']]],
  ['math_2ecpp_15247',['Math.cpp',['../_math_8cpp.xhtml',1,'']]],
  ['math_2eh_15248',['Math.h',['../arm__compute_2core_2utils_2math_2_math_8h.xhtml',1,'(Global Namespace)'],['../src_2core_2utils_2_math_8h.xhtml',1,'(Global Namespace)']]],
  ['matmul_2ecpp_15249',['MatMul.cpp',['../_c_l_2_mat_mul_8cpp.xhtml',1,'(Global Namespace)'],['../dynamic__fusion_2gpu_2cl_2_mat_mul_8cpp.xhtml',1,'(Global Namespace)'],['../_n_e_o_n_2_mat_mul_8cpp.xhtml',1,'(Global Namespace)']]],
  ['matmulattributes_2ecpp_15250',['MatMulAttributes.cpp',['../_mat_mul_attributes_8cpp.xhtml',1,'']]],
  ['matmulattributes_2eh_15251',['MatMulAttributes.h',['../_mat_mul_attributes_8h.xhtml',1,'']]],
  ['matmulinfo_2eh_15252',['MatMulInfo.h',['../_mat_mul_info_8h.xhtml',1,'']]],
  ['matmulkernel_2ecpp_15253',['MatMulKernel.cpp',['../_mat_mul_kernel_8cpp.xhtml',1,'']]],
  ['matmulkernelhelpers_2ecpp_15254',['MatMulKernelHelpers.cpp',['../_mat_mul_kernel_helpers_8cpp.xhtml',1,'']]],
  ['matmulkernelhelpers_2eh_15255',['MatMulKernelHelpers.h',['../_mat_mul_kernel_helpers_8h.xhtml',1,'']]],
  ['matmullowpnativekernel_2ecpp_15256',['MatMulLowpNativeKernel.cpp',['../_mat_mul_lowp_native_kernel_8cpp.xhtml',1,'']]],
  ['matmullowpnativemmulkernel_2ecpp_15257',['MatMulLowpNativeMMULKernel.cpp',['../_mat_mul_lowp_native_m_m_u_l_kernel_8cpp.xhtml',1,'']]],
  ['matmulnativemmulkernel_2ecpp_15258',['MatMulNativeMMULKernel.cpp',['../_mat_mul_native_m_m_u_l_kernel_8cpp.xhtml',1,'']]],
  ['max_2eh_15259',['max.h',['../max_8h.xhtml',1,'']]],
  ['maxunpoolinglayer_2ecpp_15260',['MaxUnpoolingLayer.cpp',['../_c_l_2_max_unpooling_layer_8cpp.xhtml',1,'(Global Namespace)'],['../_n_e_o_n_2_max_unpooling_layer_8cpp.xhtml',1,'(Global Namespace)'],['../reference_2_max_unpooling_layer_8cpp.xhtml',1,'(Global Namespace)']]],
  ['maxunpoolinglayer_2eh_15261',['MaxUnpoolingLayer.h',['../_max_unpooling_layer_8h.xhtml',1,'']]],
  ['mean_5fstddev_5fnormalization_2ecl_15262',['mean_stddev_normalization.cl',['../mean__stddev__normalization_8cl.xhtml',1,'']]],
  ['meanstddev_2ecpp_15263',['MeanStdDev.cpp',['../_mean_std_dev_8cpp.xhtml',1,'']]],
  ['meanstddev_2eh_15264',['MeanStdDev.h',['../_mean_std_dev_8h.xhtml',1,'']]],
  ['meanstddevnormalizationlayer_2ecpp_15265',['MeanStdDevNormalizationLayer.cpp',['../_c_l_2_mean_std_dev_normalization_layer_8cpp.xhtml',1,'(Global Namespace)'],['../_n_e_o_n_2_mean_std_dev_normalization_layer_8cpp.xhtml',1,'(Global Namespace)'],['../reference_2_mean_std_dev_normalization_layer_8cpp.xhtml',1,'(Global Namespace)']]],
  ['meanstddevnormalizationlayer_2eh_15266',['MeanStdDevNormalizationLayer.h',['../_mean_std_dev_normalization_layer_8h.xhtml',1,'']]],
  ['measurement_2eh_15267',['Measurement.h',['../_measurement_8h.xhtml',1,'']]],
  ['memory_2ecpp_15268',['Memory.cpp',['../_memory_8cpp.xhtml',1,'']]],
  ['memory_2eh_15269',['Memory.h',['../_memory_8h.xhtml',1,'']]],
  ['memorydescriptor_2eh_15270',['MemoryDescriptor.h',['../_memory_descriptor_8h.xhtml',1,'']]],
  ['memorygroup_2eh_15271',['MemoryGroup.h',['../_memory_group_8h.xhtml',1,'']]],
  ['memoryhelpers_2eh_15272',['MemoryHelpers.h',['../_memory_helpers_8h.xhtml',1,'']]],
  ['memorymanager_2ecpp_15273',['MemoryManager.cpp',['../_c_l_2_u_n_i_t_2_memory_manager_8cpp.xhtml',1,'(Global Namespace)'],['../_n_e_o_n_2_u_n_i_t_2_memory_manager_8cpp.xhtml',1,'(Global Namespace)']]],
  ['memorymanagerondemand_2ecpp_15274',['MemoryManagerOnDemand.cpp',['../_memory_manager_on_demand_8cpp.xhtml',1,'']]],
  ['memorymanagerondemand_2eh_15275',['MemoryManagerOnDemand.h',['../_memory_manager_on_demand_8h.xhtml',1,'']]],
  ['memoryregion_2eh_15276',['MemoryRegion.h',['../_memory_region_8h.xhtml',1,'']]],
  ['memset_2ecl_15277',['memset.cl',['../memset_8cl.xhtml',1,'']]],
  ['mergeresults_2dfp16_2ecpp_15278',['mergeresults-fp16.cpp',['../mergeresults-fp16_8cpp.xhtml',1,'']]],
  ['mergeresults_2dsve_2ecpp_15279',['mergeresults-sve.cpp',['../mergeresults-sve_8cpp.xhtml',1,'']]],
  ['mergeresults_2ecpp_15280',['mergeresults.cpp',['../mergeresults_8cpp.xhtml',1,'']]],
  ['mergeresults_2ehpp_15281',['mergeresults.hpp',['../mergeresults_8hpp.xhtml',1,'']]],
  ['min_2eh_15282',['min.h',['../min_8h.xhtml',1,'']]],
  ['minmax_5flayer_2ecl_15283',['minmax_layer.cl',['../minmax__layer_8cl.xhtml',1,'']]],
  ['minmaxlocation_2ecpp_15284',['MinMaxLocation.cpp',['../_min_max_location_8cpp.xhtml',1,'']]],
  ['minmaxlocation_2eh_15285',['MinMaxLocation.h',['../_min_max_location_8h.xhtml',1,'']]],
  ['misc_2dsve_2ecpp_15286',['misc-sve.cpp',['../misc-sve_8cpp.xhtml',1,'']]],
  ['misc_2ecpp_15287',['misc.cpp',['../misc_8cpp.xhtml',1,'']]],
  ['mla_2eh_15288',['mla.h',['../mla_8h.xhtml',1,'']]],
  ['mlgoheuristics_2ecpp_15289',['MLGOHeuristics.cpp',['../src_2runtime_2_c_l_2mlgo_2_m_l_g_o_heuristics_8cpp.xhtml',1,'(Global Namespace)'],['../tests_2validation_2_c_l_2_u_n_i_t_2_m_l_g_o_heuristics_8cpp.xhtml',1,'(Global Namespace)']]],
  ['mlgoheuristics_2eh_15290',['MLGOHeuristics.h',['../_m_l_g_o_heuristics_8h.xhtml',1,'']]],
  ['mlgoparser_2ecpp_15291',['MLGOParser.cpp',['../_m_l_g_o_parser_8cpp.xhtml',1,'']]],
  ['mlgoparser_2eh_15292',['MLGOParser.h',['../_m_l_g_o_parser_8h.xhtml',1,'']]],
  ['mmappedfile_2ecpp_15293',['MMappedFile.cpp',['../_m_mapped_file_8cpp.xhtml',1,'']]],
  ['mmappedfile_2eh_15294',['MMappedFile.h',['../_m_mapped_file_8h.xhtml',1,'']]],
  ['movl_2eh_15295',['movl.h',['../movl_8h.xhtml',1,'']]],
  ['movn_2eh_15296',['movn.h',['../movn_8h.xhtml',1,'']]],
  ['mul_2ecpp_15297',['Mul.cpp',['../_mul_8cpp.xhtml',1,'']]],
  ['mul_2eh_15298',['mul.h',['../mul_8h.xhtml',1,'']]],
  ['multithreaded_2ecpp_15299',['Multithreaded.cpp',['../_multithreaded_8cpp.xhtml',1,'']]],
  ['mutatorutils_2ecpp_15300',['MutatorUtils.cpp',['../_mutator_utils_8cpp.xhtml',1,'']]],
  ['mutatorutils_2eh_15301',['MutatorUtils.h',['../_mutator_utils_8h.xhtml',1,'']]],
  ['mutex_2eh_15302',['Mutex.h',['../_mutex_8h.xhtml',1,'']]]
];
