Compute Library: tests/validate_examples/cl_gemm.cpp File Reference
cl_gemm.cpp File Reference
#include "arm_compute/core/Types.h"
#include "arm_compute/core/Utils.h"
#include "arm_compute/core/utils/quantization/AsymmHelpers.h"
#include "arm_compute/runtime/CL/CLScheduler.h"
#include "arm_compute/runtime/CL/functions/CLGEMM.h"
#include "arm_compute/runtime/CL/functions/CLGEMMLowpMatrixMultiplyCore.h"
#include "arm_compute/runtime/CL/functions/CLGEMMLowpOutputStage.h"
#include "src/core/CL/kernels/CLDepthConvertLayerKernel.h"
#include "src/core/CL/kernels/CLFillBorderKernel.h"
#include "src/core/CL/kernels/CLGEMMLowpMatrixMultiplyNativeKernel.h"
#include "src/core/CL/kernels/CLGEMMLowpMatrixMultiplyReshapedOnlyRHSKernel.h"
#include "src/core/CL/kernels/CLGEMMLowpOffsetContributionKernel.h"
#include "src/core/CL/kernels/CLGEMMLowpOffsetContributionOutputStageKernel.h"
#include "src/core/CL/kernels/CLGEMMLowpReductionKernel.h"
#include "src/core/CL/kernels/CLGEMMMatrixMultiplyReshapedKernel.h"
#include "src/core/CL/kernels/CLGEMMMatrixMultiplyReshapedOnlyRHSKernel.h"
#include "src/core/CL/kernels/CLGEMMReshapeLHSMatrixKernel.h"
#include "src/core/CL/kernels/CLGEMMReshapeRHSMatrixKernel.h"
#include "src/core/CL/kernels/CLIm2ColKernel.h"
#include "src/core/CL/kernels/CLWeightsReshapeKernel.h"
#include "tests/AssetsLibrary.h"
#include "tests/CL/CLAccessor.h"
#include "tests/Globals.h"
#include "tests/IAccessor.h"
#include "tests/SimpleTensor.h"
#include "tests/validation/Validation.h"
#include "tests/validation/reference/GEMM.h"
#include "tests/validation/reference/GEMMLowp.h"
#include "utils/TypePrinter.h"
#include "utils/Utils.h"
#include "utils/command_line/CommandLineOptions.h"
#include "utils/command_line/CommandLineParser.h"
#include "ValidateExample.h"
#include <cstdlib>
Functions
constexpr float abs_tolerance_f32 (0.0001f)
F32 Absolute tolerance value for comparing reference's output against implementation's output for floating point data types in case using relative tolerance fails because of small values.
int main (int argc, char **argv)
Main program for gemm test.
Variables
RelativeTolerance< float > tolerance_f32 (0.001f)
F32 Tolerance value for comparing reference's output against implementation's output for floating point data types.
RelativeTolerance< half_float::half > tolerance_f16 (half(0.2))
F16 Tolerance value for comparing reference's output against implementation's output for floating point data types.
constexpr float tolerance_num_f16 = 0.02f
F16 Tolerance number.
Function Documentation
abs_tolerance_f32()
constexpr float abs_tolerance_f32 (0. 0001f)
F32 Absolute tolerance value for comparing reference's output against implementation's output for floating point data types in case using relative tolerance fails because of small values.
Referenced by arm_compute::test::validation::combine(), arm_compute::test::validation::detail::configure_conv_function< NEGEMMConv2d, Tensor >(), arm_compute::test::validation::FIXTURE_DATA_TEST_CASE(), and arm_compute::test::validation::FIXTURE_DATA_TEST_CASE_NEW().
main()
int main (int argc, char ** argv)
Main program for gemm test.
Parameters
[in] argc Number of arguments
[in] argv Arguments
Definition at line 414 of file cl_gemm.cpp.
 {
     return utils::run_example<CLGEMMValidateExample>(argc, argv);
 }
Variable Documentation
tolerance_f16
RelativeTolerance<half_float::half> tolerance_f16(half(0.2))
F16 Tolerance value for comparing reference's output against implementation's output for floating point data types.
Referenced by arm_compute::test::validation::combine(), arm_compute::test::validation::FIXTURE_DATA_TEST_CASE(), and arm_compute::test::validation::FIXTURE_DATA_TEST_CASE_NEW().
tolerance_f32
RelativeTolerance<float> tolerance_f32(0.001f)
F32 Tolerance value for comparing reference's output against implementation's output for floating point data types.
Referenced by arm_compute::test::validation::combine(), arm_compute::test::validation::DATA_TEST_CASE(), arm_compute::test::validation::FIXTURE_DATA_TEST_CASE(), arm_compute::test::validation::FIXTURE_DATA_TEST_CASE_NEW(), and arm_compute::test::validation::FIXTURE_TEST_CASE().
tolerance_num_f16
constexpr float tolerance_num_f16 = 0.02f
F16 Tolerance number.
Definition at line 75 of file cl_gemm.cpp.
Referenced by arm_compute::test::validation::combine(), and arm_compute::test::validation::detail::configure_conv_function< NEGEMMConv2d, Tensor >().