Compute Library: INEOperator Class Reference
INEOperator Class Reference
Basic interface for functions which have a single async CPU kernel.
#include <INEOperator.h>
Public Member Functions
INEOperator (IRuntimeContext *ctx=nullptr)
Constructor.
INEOperator (const INEOperator &)=delete
Prevent instances of this class from being copied (As this class contains pointers)
INEOperator (INEOperator &&)=default
Default move constructor.
INEOperator & operator= (const INEOperator &)=delete
Prevent instances of this class from being copied (As this class contains pointers)
INEOperator & operator= (INEOperator &&)=default
Default move assignment operator.
~INEOperator ()
Default destructor.
void run (ITensorPack &tensors) override
Run the kernels contained in the function.
void prepare (ITensorPack &constants) override
Prepare the function for executing.
MemoryRequirements workspace () const override
Return the memory requirements required by the workspace.
Public Member Functions inherited from IOperator
virtual ~IOperator ()=default
Destructor.
Detailed Description
Basic interface for functions which have a single async CPU kernel.
Definition at line 43 of file INEOperator.h.
Constructor & Destructor Documentation
INEOperator() [1/3]
INEOperator (IRuntimeContext * ctx = nullptr)
Constructor.
Parameters
[in] ctx Runtime context to be used by the function
Definition at line 35 of file INEOperator.cpp.
     : _kernel(), _ctx(ctx), _workspace()
 {
 }
INEOperator() [2/3]
INEOperator (const INEOperator &) delete
Prevent instances of this class from being copied (As this class contains pointers)
INEOperator() [3/3]
INEOperator (INEOperator &&) default
Default move constructor.
~INEOperator()
~INEOperator () default
Default destructor.
Member Function Documentation
operator=() [1/2]
INEOperator& operator= (const INEOperator &) delete
Prevent instances of this class from being copied (As this class contains pointers)
operator=() [2/2]
INEOperator& operator= (INEOperator &&) default
Default move assignment operator.
prepare()
void prepare (ITensorPack & constants) override virtual
Prepare the function for executing.
Any one off pre-processing step required by the function is handled here
Parameters
[in] constants Vector that contains the constants tensors.
Note
Prepare stage might not need all the function's buffers' backing memory to be available in order to execute
Implements IOperator.
Reimplemented in CpuConv2d, CpuGemmConv2d, CpuGemmLowpMatrixMultiplyCore, CpuGemmAssemblyDispatch, CpuGemm, CpuFullyConnected, CpuWinogradConv2d, CpuDepthwiseConv2d, CpuGemmDirectConv2d, CpuDepthwiseConv2dAssemblyDispatch, and CpuScale.
Definition at line 55 of file INEOperator.cpp.
References ARM_COMPUTE_UNUSED.
Referenced by CpuDequantize::run().
 {
     ARM_COMPUTE_UNUSED(constants);
 }
run()
void run (ITensorPack & tensors) override virtual
Run the kernels contained in the function.
Parameters
[in] tensors Vector that contains the tensors to operate on.
Implements IOperator.
Reimplemented in CpuConv2d, NESynthetizeFunctionWithZeroConstantKernelBorder< K >, CpuGemmConv2d, CpuGemmLowpMatrixMultiplyCore, CpuGemmAssemblyDispatch, CpuGemm, CpuComplexMul, CpuFullyConnected, CpuDirectConv2d, CpuDirectConv3d, CpuWinogradConv2d, CpuDepthwiseConv2d, CpuGemmDirectConv2d, CpuGemmLowpOutputStage, CpuSoftmaxGeneric< IS_LOG >, CpuMul, CpuPool2d, CpuDepthwiseConv2dAssemblyDispatch, CpuConcatenate, CpuScale, CpuConvertFullyConnectedWeights, CpuElementwiseUnary, CpuDequantize, CpuQuantize, and CpuElementwiseBase.
Definition at line 40 of file INEOperator.cpp.
References ARM_COMPUTE_ERROR, Window::DimY, ITensorPack::empty(), Scheduler::get(), and IScheduler::schedule_op().
Referenced by CpuElementwiseBase::run(), CpuElementwiseUnary::run(), and CpuSoftmaxGeneric< IS_LOG >::run().
 {
     if(tensors.empty())
     {
         ARM_COMPUTE_ERROR("No inputs provided");
     }
     run(tensors, _kernel->window());
 }
workspace()
MemoryRequirements workspace () const override virtual
Return the memory requirements required by the workspace.
Implements IOperator.
Reimplemented in CpuConv2d, CpuGemmConv2d, CpuGemmLowpMatrixMultiplyCore, CpuGemmAssemblyDispatch, CpuGemm, CpuFullyConnected, CpuWinogradConv2d, CpuGemmDirectConv2d, CpuSoftmaxGeneric< IS_LOG >, CpuDepthwiseConv2dAssemblyDispatch, and CpuPool2d.
Definition at line 60 of file INEOperator.cpp.
 {
     return _workspace;
 }
The documentation for this class was generated from the following files:
arm_compute/runtime/NEON/INEOperator.h
src/runtime/NEON/INEOperator.cpp