Compute Library: ClLogits1DMaxShiftExpSumKernel Class Reference
ClLogits1DMaxShiftExpSumKernel Class Reference
Interface for max, shifting, exponentiating and summing the logits.
#include <ClSoftmaxKernel.h>
Public Types
using ParallelReductionInfo = std::tuple< bool, unsigned int >
Info for whether a parallel reduction will be run and the vector size of the execution.
Public Member Functions
ClLogits1DMaxShiftExpSumKernel ()
ARM_COMPUTE_DISALLOW_COPY_ALLOW_MOVE (ClLogits1DMaxShiftExpSumKernel)
void configure (const CLCompileContext &compile_context, const ITensorInfo &src, ITensorInfo &max, ITensorInfo &dst, ITensorInfo &sum, const SoftmaxKernelInfo &info)
Configure the kernel using the given information about tensors.
void run_op (ITensorPack &tensors, const Window &window, ::cl::CommandQueue &queue) override
Public Member Functions inherited from ICLKernel
ICLKernel ()
Constructor.
cl::Kernel & kernel ()
Returns a reference to the OpenCL kernel of this object.
CLKernelType type () const
Returns the CL kernel type.
template<typename T >
void add_1D_array_argument (unsigned int &idx, const ICLArray< T > *array, const Strides &strides, unsigned int num_dimensions, const Window &window)
Add the passed 1D array's parameters to the object's kernel's arguments starting from the index idx.
void add_1D_tensor_argument (unsigned int &idx, const ICLTensor *tensor, const Window &window)
Add the passed 1D tensor's parameters to the object's kernel's arguments starting from the index idx.
void add_1D_tensor_argument_if (bool cond, unsigned int &idx, const ICLTensor *tensor, const Window &window)
Add the passed 1D tensor's parameters to the object's kernel's arguments starting from the index idx if the condition is true.
void add_2D_tensor_argument (unsigned int &idx, const ICLTensor *tensor, const Window &window)
Add the passed 2D tensor's parameters to the object's kernel's arguments starting from the index idx.
void add_2D_tensor_argument_if (bool cond, unsigned int &idx, const ICLTensor *tensor, const Window &window)
Add the passed 2D tensor's parameters to the object's kernel's arguments starting from the index idx if the condition is true.
void add_3D_tensor_argument (unsigned int &idx, const ICLTensor *tensor, const Window &window)
Add the passed 3D tensor's parameters to the object's kernel's arguments starting from the index idx.
void add_4D_tensor_argument (unsigned int &idx, const ICLTensor *tensor, const Window &window)
Add the passed 4D tensor's parameters to the object's kernel's arguments starting from the index idx.
virtual void run (const Window &window, cl::CommandQueue &queue)
Enqueue the OpenCL kernel to process the given window on the passed OpenCL command queue.
virtual void run_op (ITensorPack &tensors, const Window &window, cl::CommandQueue &queue)
Enqueue the OpenCL kernel to process the given window on the passed OpenCL command queue.
template<typename T >
void add_argument (unsigned int &idx, T value)
Add the passed parameters to the object's kernel's arguments starting from the index idx.
void set_lws_hint (const cl::NDRange &lws_hint)
Set the Local-Workgroup-Size hint.
cl::NDRange lws_hint () const
Return the Local-Workgroup-Size hint.
void set_wbsm_hint (const cl_int &wbsm_hint)
Set the workgroup batch size modifier hint.
cl_int wbsm_hint () const
Return the workgroup batch size modifier hint.
const std::string & config_id () const
Get the configuration ID.
void set_target (GPUTarget target)
Set the targeted GPU architecture.
void set_target (cl::Device &device)
Set the targeted GPU architecture according to the CL device.
GPUTarget get_target () const
Get the targeted GPU architecture.
size_t get_max_workgroup_size ()
Get the maximum workgroup size for the device the CLKernelLibrary uses.
template<unsigned int dimension_size>
void add_tensor_argument (unsigned &idx, const ICLTensor *tensor, const Window &window)
template<typename T , unsigned int dimension_size>
void add_array_argument (unsigned &idx, const ICLArray< T > *array, const Strides &strides, unsigned int num_dimensions, const Window &window)
Add the passed array's parameters to the object's kernel's arguments starting from the index idx.
Public Member Functions inherited from IKernel
IKernel ()
Constructor.
virtual ~IKernel ()=default
Destructor.
virtual bool is_parallelisable () const
Indicates whether or not the kernel is parallelisable.
virtual BorderSize border_size () const
The size of the border for that kernel.
const Window & window () const
The maximum window the kernel can be executed on.
bool is_window_configured () const
Function to check if the embedded window of this kernel has been configured.
Static Public Member Functions
static Status validate (const ITensorInfo &src, const ITensorInfo &max, const ITensorInfo &dst, const ITensorInfo &sum)
Static function to check if given info will lead to a valid configuration.
static ParallelReductionInfo is_parallel_reduction (size_t size)
Checks if the given size is eligible for parallel reduction.
Static Public Member Functions inherited from ICLKernel
static constexpr unsigned int num_arguments_per_1D_array ()
Returns the number of arguments enqueued per 1D array object.
static constexpr unsigned int num_arguments_per_1D_tensor ()
Returns the number of arguments enqueued per 1D tensor object.
static constexpr unsigned int num_arguments_per_2D_tensor ()
Returns the number of arguments enqueued per 2D tensor object.
static constexpr unsigned int num_arguments_per_3D_tensor ()
Returns the number of arguments enqueued per 3D tensor object.
static constexpr unsigned int num_arguments_per_4D_tensor ()
Returns the number of arguments enqueued per 4D tensor object.
static cl::NDRange gws_from_window (const Window &window)
Get the global work size given an execution window.
Detailed Description
Interface for max, shifting, exponentiating and summing the logits.
Definition at line 40 of file ClSoftmaxKernel.h.
Member Typedef Documentation
ParallelReductionInfo
using ParallelReductionInfo = std::tuple<bool, unsigned int>
Info for whether a parallel reduction will be run and the vector size of the execution.
Definition at line 51 of file ClSoftmaxKernel.h.
Constructor & Destructor Documentation
ClLogits1DMaxShiftExpSumKernel()
ClLogits1DMaxShiftExpSumKernel ()
Definition at line 157 of file ClSoftmaxKernel.cpp.
References arm_compute::ELEMENTWISE.
 {
     _type = CLKernelType::ELEMENTWISE;
 }
Member Function Documentation
ARM_COMPUTE_DISALLOW_COPY_ALLOW_MOVE()
ARM_COMPUTE_DISALLOW_COPY_ALLOW_MOVE (ClLogits1DMaxShiftExpSumKernel)
configure()
void configure (const CLCompileContext & compile_context, const ITensorInfo & src, ITensorInfo & max, ITensorInfo & dst, ITensorInfo & sum, const SoftmaxKernelInfo & info)
Configure the kernel using the given information about tensors.
Parameters
[in] compile_context The compile context to be used.
[in] src Source tensor. Data types supported: QASYMM8/QASYMM8_SIGNED/F16/F32
[in,out] max Max values tensor. Data types supported: same as src
[out] dst Destination tensor. Data types supported: same as src
[out] sum Sum of 1D logits tensor. Data types supported: same as src
[in] info Contains information consumed by kernels for softmax described in SoftmaxKernelInfo.
Definition at line 162 of file ClSoftmaxKernel.cpp.
References CLBuildOptions::add_option(), CLBuildOptions::add_option_if(), CLBuildOptions::add_options_if(), arm_compute::adjust_vec_size(), ARM_COMPUTE_ERROR_ON, ARM_COMPUTE_ERROR_THROW_ON, arm_compute::auto_init_if_empty(), SoftmaxKernelInfo::beta, arm_compute::calculate_max_window(), ICloneable< T >::clone(), arm_compute::create_kernel(), ITensorInfo::data_type(), ITensorInfo::dimension(), arm_compute::test::validation::dst, dt, arm_compute::F16, arm_compute::float_to_string_with_full_precision(), arm_compute::get_cl_type_from_data_type(), arm_compute::get_padding_info(), arm_compute::has_padding_changed(), SoftmaxKernelInfo::input_data_type, arm_compute::is_data_type_float(), arm_compute::is_data_type_quantized_asymmetric(), arm_compute::is_data_type_quantized_asymmetric_signed(), SoftmaxKernelInfo::is_log, kernel_name, arm_compute::support::cpp11::lround(), ICLKernel::lws_hint(), CLBuildOptions::options(), arm_compute::test::validation::qinfo, ITensorInfo::quantization_info(), UniformQuantizationInfo::scale, arm_compute::test::validation::src, ITensorInfo::tensor_shape(), arm_compute::support::cpp11::to_string(), and QuantizationInfo::uniform().
 {
     auto padding_info = get_padding_info({ &src, &max, &dst, &sum });
     // Output auto initialization if not yet initialized
     auto_init_if_empty(sum, src.clone()->set_tensor_shape(max.tensor_shape()));
     auto_init_if_empty(dst, *src.clone());
     // Perform validation step
     ARM_COMPUTE_ERROR_THROW_ON(validate_arguments_1DMaxShiftExpSum(src, max, dst, sum));
     const DataType                dt                 = src.data_type();
     const UniformQuantizationInfo qinfo              = src.quantization_info().uniform();
     const size_t                  reduction_dim_size = src.dimension(0);
     const float                   beta               = info.beta;
     const auto                    is_signed_qasymm8  = is_data_type_quantized_asymmetric_signed(info.input_data_type);
     const int                     min_value          = is_signed_qasymm8 ? CL_SCHAR_MIN : 0;
     const unsigned int vector_size = adjust_vec_size(_serial_vector_size, reduction_dim_size);
     // Set build options
     CLBuildOptions build_opts;
     build_opts.add_option("-DDATA_TYPE=" + get_cl_type_from_data_type(dt));
     build_opts.add_option("-DMIN_VALUE=" + support::cpp11::to_string(min_value));
     build_opts.add_option("-DVECTOR_SIZE=" + support::cpp11::to_string(vector_size));
     build_opts.add_option("-DSRC_WIDTH=" + support::cpp11::to_string(reduction_dim_size));
     build_opts.add_option("-DVECTOR_SIZE_LEFTOVER=" + support::cpp11::to_string(reduction_dim_size % vector_size));
     build_opts.add_option("-DLOG_VECTOR_SIZE=" + support::cpp11::to_string(lround(log2(vector_size))));
     build_opts.add_option_if((reduction_dim_size % vector_size) != 0, "-DNON_MULTIPLE_OF_VECTOR_SIZE");
     build_opts.add_option_if(is_signed_qasymm8, "-DQASYMM8_SIGNED");
     build_opts.add_option_if(is_data_type_float(dt) && (beta != 1.0f), "-DBETA=" + float_to_string_with_full_precision(beta));
     build_opts.add_option_if(is_data_type_float(dt) && info.is_log, "-DLOG_SOFTMAX");
     build_opts.add_option_if(is_data_type_float(dt), "-DMINVAL=" + ((dt == DataType::F16) ? std::string("-HALF_MAX") : std::string("-FLT_MAX")));
     build_opts.add_option_if(is_data_type_quantized_asymmetric(dt), "-DSCALE=" + float_to_string_with_full_precision(qinfo.scale));
     build_opts.add_option_if(is_data_type_quantized_asymmetric(dt), "-DBETA=" + float_to_string_with_full_precision(beta));
     build_opts.add_options_if(is_data_type_quantized_asymmetric(dt), prepare_quantized_softmax_build_options(qinfo.scale, beta).options());
     cl::NDRange lws_hint(cl::NullRange);
     std::string kernel_name = std::string("softmax_layer_max_shift_exp_sum_") + (is_data_type_quantized_asymmetric(dt) ? "quantized_" : "") + "serial";
     // Create kernel.
     _kernel = create_kernel(compile_context, kernel_name, build_opts.options());
     // Configure window
     Window win = calculate_max_window(src, Steps(reduction_dim_size));
     IClKernel::configure_internal(win, lws_hint);
     ARM_COMPUTE_ERROR_ON(has_padding_changed(padding_info));
 }
is_parallel_reduction()
ClLogits1DMaxShiftExpSumKernel::ParallelReductionInfo is_parallel_reduction (size_t size) static
Checks if the given size is eligible for parallel reduction.
Note
Serial reduction is launched for width < (_grid_size * _serial_vector_size).
Parallel reduction is launched for width >= (_grid_size * _serial_vector_size) and vector_size is forced to 4.
Parameters
[in] size Size to check
Returns
A two-element tuple where the first element is a boolean specifying if a parallel reduction will be run, while the second element is the vector size of the execution.
Definition at line 218 of file ClSoftmaxKernel.cpp.
Referenced by ClLogits1DMaxShiftExpSumKernel::run_op().
 {
     bool         is_parallel_reduction = (size >= (_grid_size * _serial_vector_size)) && (_grid_size > 1);
     unsigned int vector_size           = is_parallel_reduction ? _parallel_vector_size : _serial_vector_size;
     return std::make_tuple(is_parallel_reduction, vector_size);
 }
run_op()
void run_op (ITensorPack & tensors, const Window & window, ::cl::CommandQueue & queue) override
Definition at line 225 of file ClSoftmaxKernel.cpp.
References arm_compute::ACL_DST, arm_compute::ACL_INT_0, arm_compute::ACL_INT_1, arm_compute::ACL_SRC, ICLKernel::add_3D_tensor_argument(), ARM_COMPUTE_ERROR_ON_INVALID_SUBWINDOW, ARM_COMPUTE_ERROR_ON_NULLPTR, ARM_COMPUTE_ERROR_ON_UNCONFIGURED_KERNEL, Window::collapse_if_possible(), Window::DimX, Window::DimZ, arm_compute::enqueue(), Window::first_slice_window_3D(), ITensorPack::get_const_tensor(), ITensorPack::get_tensor(), ClLogits1DMaxShiftExpSumKernel::is_parallel_reduction(), ICLKernel::lws_hint(), Window::set(), arm_compute::test::validation::reference::slice(), Window::slide_window_slice_3D(), and IKernel::window().
 {
     ARM_COMPUTE_ERROR_ON_UNCONFIGURED_KERNEL(this);
     ARM_COMPUTE_ERROR_ON_INVALID_SUBWINDOW(IKernel::window(), window);
     auto src = utils::cast::polymorphic_downcast<const ICLTensor *>(tensors.get_const_tensor(TensorType::ACL_SRC));
     auto dst = utils::cast::polymorphic_downcast<ICLTensor *>(tensors.get_tensor(TensorType::ACL_DST));
     auto max = utils::cast::polymorphic_downcast<ICLTensor *>(tensors.get_tensor(TensorType::ACL_INT_0));
     auto sum = utils::cast::polymorphic_downcast<ICLTensor *>(tensors.get_tensor(TensorType::ACL_INT_1));
     ARM_COMPUTE_ERROR_ON_NULLPTR(src, dst, max, sum);
     // Collapse window in Z dimension
     Window window_collapsed = window.collapse_if_possible(IClKernel::window(), Window::DimZ);
     // Reconfigure window in case of parallel reduction
     ParallelReductionInfo parallel_reduction_info = is_parallel_reduction(src->info()->dimension(0));
     if(std::get<0>(parallel_reduction_info))
     {
         // Launch grid_size parallel work items
         window_collapsed.set(Window::DimX, Window::Dimension(0, _grid_size, 1));
     }
     // Get slices
     Window slice = window_collapsed.first_slice_window_3D();
     do
     {
         unsigned int idx = 0;
         // Set inputs
         add_3D_tensor_argument(idx, src, slice);
         add_3D_tensor_argument(idx, max, slice);
         add_3D_tensor_argument(idx, dst, slice);
         add_3D_tensor_argument(idx, sum, slice);
         enqueue(queue, *this, slice, lws_hint());
     }
     while(window_collapsed.slide_window_slice_3D(slice));
 }
validate()
Status validate (const ITensorInfo & src, const ITensorInfo & max, const ITensorInfo & dst, const ITensorInfo & sum) static
Static function to check if given info will lead to a valid configuration.
Similar to ClLogits1DMaxShiftExpSumKernel::configure()
Returns
a status
Definition at line 212 of file ClSoftmaxKernel.cpp.
References ARM_COMPUTE_RETURN_ON_ERROR.
Referenced by ClSoftmax::validate().
 {
     ARM_COMPUTE_RETURN_ON_ERROR(validate_arguments_1DMaxShiftExpSum(src, max, dst, sum));
     return Status{};
 }
The documentation for this class was generated from the following files:
src/gpu/cl/kernels/ClSoftmaxKernel.h
src/gpu/cl/kernels/ClSoftmaxKernel.cpp