Compute Library: CpuTensor Class Reference
CpuTensor Class Reference final
CPU tensor implementation class.
#include <CpuTensor.h>
Public Member Functions
CpuTensor (IContext *ctx, const AclTensorDescriptor &desc)
Construct a new Cpu Tensor object.
StatusCode allocate ()
Allocates tensor.
void * map () override
Map tensor to a host pointer.
StatusCode unmap () override
Unmap tensor.
arm_compute::ITensor * tensor () const override
Get the legacy tensor object.
StatusCode import (void *handle, ImportMemoryType type) override
Import external memory handle.
Public Member Functions inherited from ITensorV2
ITensorV2 (IContext *ctx)
Explict Operator Constructor.
virtual ~ITensorV2 ()
Destructor.
bool is_valid () const
Checks if a queue is valid.
size_t get_size () const
Get the size of the tensor in byte.
AclTensorDescriptor get_descriptor () const
Get the descriptor of this tensor.
Additional Inherited Members
Data Fields inherited from AclTensor_
arm_compute::detail::Header header { arm_compute::detail::ObjectType::Tensor, nullptr }
Detailed Description
CPU tensor implementation class.
Definition at line 36 of file CpuTensor.h.
Constructor & Destructor Documentation
CpuTensor()
CpuTensor (IContext * ctx, const AclTensorDescriptor & desc)
Construct a new Cpu Tensor object.
Parameters
[in] ctx Context to be used
[in] desc Tensor descriptor
Definition at line 32 of file CpuTensor.cpp.
References ARM_COMPUTE_ASSERT, arm_compute::detail::convert_to_legacy_tensor_info(), arm_compute::Cpu, and IContext::type().
     : ITensorV2(ctx), _legacy_tensor()
 {
     ARM_COMPUTE_ASSERT((ctx != nullptr) && (ctx->type() == Target::Cpu));
     _legacy_tensor = std::make_unique<Tensor>();
     _legacy_tensor->allocator()->init(arm_compute::detail::convert_to_legacy_tensor_info(desc));
 }
Member Function Documentation
allocate()
StatusCode allocate ()
Allocates tensor.
Returns
StatusCode A status code
Definition at line 52 of file CpuTensor.cpp.
References ARM_COMPUTE_ASSERT, and arm_compute::Success.
Referenced by CpuContext::create_tensor().
 {
     ARM_COMPUTE_ASSERT(_legacy_tensor.get() != nullptr);
     _legacy_tensor->allocator()->allocate();
     return StatusCode::Success;
 }
import()
StatusCode import (void * handle, ImportMemoryType type) override virtual
Import external memory handle.
Parameters
[in] handle Memory to import
[in] type Type of imported memory
Returns
Status code
Implements ITensorV2.
Definition at line 66 of file CpuTensor.cpp.
References ARM_COMPUTE_ASSERT, ARM_COMPUTE_UNUSED, arm_compute::RuntimeError, and arm_compute::Success.
 {
     ARM_COMPUTE_ASSERT(_legacy_tensor.get() != nullptr);
     ARM_COMPUTE_UNUSED(type);
     const auto st = _legacy_tensor->allocator()->import_memory(handle);
     return bool(st) ? StatusCode::Success : StatusCode::RuntimeError;
 }
map()
void * map () override virtual
Map tensor to a host pointer.
Returns
A pointer to the underlying backing memory if successful else nullptr
Implements ITensorV2.
Definition at line 40 of file CpuTensor.cpp.
References ARM_COMPUTE_ASSERT, and ARM_COMPUTE_LOG_ERROR_ACL.
 {
     ARM_COMPUTE_ASSERT(_legacy_tensor.get() != nullptr);
     if(_legacy_tensor == nullptr)
     {
         ARM_COMPUTE_LOG_ERROR_ACL("[CpuTensor:map]: Backing tensor does not exist!");
         return nullptr;
     }
     return _legacy_tensor->buffer();
 }
tensor()
arm_compute::ITensor * tensor () const override virtual
Get the legacy tensor object.
Returns
The legacy underlying tensor object
Implements ITensorV2.
Definition at line 75 of file CpuTensor.cpp.
 {
     return _legacy_tensor.get();
 }
unmap()
StatusCode unmap () override virtual
Unmap tensor.
Returns
AclStatus A status cod
Implements ITensorV2.
Definition at line 60 of file CpuTensor.cpp.
References arm_compute::Success.
 {
     // No-op
     return StatusCode::Success;
 }
The documentation for this class was generated from the following files:
src/cpu/CpuTensor.h
src/cpu/CpuTensor.cpp