Compute Library: DepthwiseDepthfirstGenericQuantized< Strategy, OutputRows, OutputCols > Class Template Reference
DepthwiseDepthfirstGenericQuantized< Strategy, OutputRows, OutputCols > Class Template Reference
#include <depthwise_depthfirst_generic_quantized.hpp>
Public Member Functions
DepthwiseDepthfirstGenericQuantized (const DepthwiseArgs &args, const Requantize32 &qp)
DepthwiseDepthfirstGenericQuantized (DepthwiseDepthfirstGenericQuantized &)=delete
DepthwiseDepthfirstGenericQuantized & operator= (DepthwiseDepthfirstGenericQuantized &)=delete
void pack_parameters (void *buffer, const void *biases, const void *weights, size_t ld_weight_col, size_t ld_weight_row) override
void execute (const unsigned int batches, const unsigned int input_height, const unsigned int input_width, const unsigned int input_channels, const PaddingValues &padding, const void *const _input, const size_t ld_input_col, const size_t ld_input_row, const size_t ld_input_batch, const void *const parameters, const unsigned int output_height, const unsigned int output_width, void *const _output, const size_t ld_output_col, const size_t ld_output_row, const size_t ld_output_batch, void *const _working_space, const unsigned int thread_id, const unsigned int n_threads) const override
Public Member Functions inherited from DepthwiseDepthfirstGenericBase< Strategy, OutputRows, OutputCols >
DepthwiseDepthfirstGenericBase (const DepthwiseArgs &args)
DepthwiseDepthfirstGenericBase (DepthwiseDepthfirstGenericBase &)=delete
DepthwiseDepthfirstGenericBase & operator= (DepthwiseDepthfirstGenericBase &)=delete
size_t get_storage_size (void) const override
void pack_parameters (void *_buffer, const void *, const void *_weights, size_t ld_weight_col, size_t ld_weight_row) override
size_t get_working_size (const unsigned int n_threads, const unsigned int n_channels) const override
Detailed Description
template<class Strategy, unsigned OutputRows, unsigned int OutputCols>
class arm_conv::depthwise::DepthwiseDepthfirstGenericQuantized< Strategy, OutputRows, OutputCols >
Definition at line 42 of file depthwise_depthfirst_generic_quantized.hpp.
Constructor & Destructor Documentation
DepthwiseDepthfirstGenericQuantized() [1/2]
DepthwiseDepthfirstGenericQuantized (const DepthwiseArgs & args, const Requantize32 & qp) inline
Definition at line 52 of file depthwise_depthfirst_generic_quantized.hpp.
References DepthwiseDepthfirstGenericQuantized< Strategy, OutputRows, OutputCols >::operator=().
     : Parent(args), m_qp(qp)
   {
   }
DepthwiseDepthfirstGenericQuantized() [2/2]
DepthwiseDepthfirstGenericQuantized (DepthwiseDepthfirstGenericQuantized< Strategy, OutputRows, OutputCols > &) delete
Member Function Documentation
execute()
void execute (const unsigned int batches, const unsigned int input_height, const unsigned int input_width, const unsigned int input_channels, const PaddingValues & padding, const void *const _input, const size_t ld_input_col, const size_t ld_input_row, const size_t ld_input_batch, const void *const parameters, const unsigned int output_height, const unsigned int output_width, void *const _output, const size_t ld_output_col, const size_t ld_output_row, const size_t ld_output_batch, void *const _working_space, const unsigned int thread_id, const unsigned int n_threads) const inline override
Definition at line 67 of file depthwise_depthfirst_generic_quantized.hpp.
References Requantize32::a_offset, arm_compute::test::validation::n, and GemmTuner::Strategy.
   {
     Strategy strat(this->m_args.cpu_info);
 #ifdef CYCLE_PROFILING
     arm_gemm::profiler prof;
 #endif
     // Create a function to initialise the input buffer
     const auto initialise_input_buffer = [this] (TInput *const buffer, const unsigned int n) {
       std::memset(buffer, static_cast<TInput>(m_qp.a_offset), n * sizeof(TInput));
     };
     // Create a function to execute a tile of work
     const auto tile_fn = [&] (const TInput *const *const inptrs, TOutput *const * const outptrs) {
 #ifdef CYCLE_PROFILING
       auto p = prof.ScopedProfiler(
         PROFILE_KERNEL,
         (unsigned long) (OutputRows * OutputCols * this->m_args.kernel_rows* this->m_args.kernel_cols)
       );
 #endif
       strat.kernel(inptrs, outptrs, parameters, m_qp,
                    this->m_args.kernel_rows * this->m_args.kernel_cols,
                    this->m_args.input_channels);
     };
     // Call into a parent utility function to do the actual work.
     Parent::execute_tiles(
       tile_fn, initialise_input_buffer,
       batches, input_height, input_width, input_channels, padding,
       _input, ld_input_col, ld_input_row, ld_input_batch,
       output_height, output_width,
       _output, ld_output_col, ld_output_row, ld_output_batch,
       _working_space, thread_id, n_threads
     );
   }
operator=()
DepthwiseDepthfirstGenericQuantized& operator= (DepthwiseDepthfirstGenericQuantized< Strategy, OutputRows, OutputCols > &) delete
Referenced by DepthwiseDepthfirstGenericQuantized< Strategy, OutputRows, OutputCols >::DepthwiseDepthfirstGenericQuantized().
pack_parameters()
void pack_parameters (void * buffer, const void * biases, const void * weights, size_t ld_weight_col, size_t ld_weight_row) inline override
Definition at line 60 of file depthwise_depthfirst_generic_quantized.hpp.
References Requantize32::bias, and DepthwiseDepthfirstGenericBase< Strategy, OutputRows, OutputCols >::pack_parameters().
   {
     m_qp.bias = static_cast<const TAccum *>(biases);
     Parent::pack_parameters(buffer, biases, weights, ld_weight_col, ld_weight_row);
   }
The documentation for this class was generated from the following file:
src/core/NEON/kernels/arm_conv/depthwise/depthwise_depthfirst_generic_quantized.hpp