Compute Library: CLArgMinMaxLayer Class Reference
CLArgMinMaxLayer Class Reference
Function to calculate the index of the minimum or maximum values in a tensor based on an axis.
#include <CLArgMinMaxLayer.h>
Public Member Functions
CLArgMinMaxLayer (std::shared_ptr< IMemoryManager > memory_manager=nullptr)
Default Constructor.
CLArgMinMaxLayer (const CLArgMinMaxLayer &)=delete
Prevent instances of this class from being copied.
CLArgMinMaxLayer & operator= (const CLArgMinMaxLayer &)=delete
Prevent instances of this class from being copied.
CLArgMinMaxLayer (CLArgMinMaxLayer &&)=delete
Prevent instances of this class to be moved.
CLArgMinMaxLayer & operator= (CLArgMinMaxLayer &&)=delete
Prevent instances of this class to be moved.
~CLArgMinMaxLayer ()
Default destructor.
void configure (const ICLTensor *input, int axis, ICLTensor *output, const ReductionOperation &op)
Set the input and output tensors.
void configure (const CLCompileContext &compile_context, const ICLTensor *input, int axis, ICLTensor *output, const ReductionOperation &op)
Set the input and output tensors.
void run () override
Run the kernels contained in the function.
Public Member Functions inherited from IFunction
virtual ~IFunction ()=default
Destructor.
virtual void prepare ()
Prepare the function for executing.
Static Public Member Functions
static Status validate (const ITensorInfo *input, int axis, const ITensorInfo *output, const ReductionOperation &op)
Static function to check if given info will lead to a valid configuration of CLArgMinMaxLayer.
Detailed Description
Function to calculate the index of the minimum or maximum values in a tensor based on an axis.
Note
The default data type for an uninitialized output tensor is signed 32-bit integer (S32). It is the user's responsibility to check that the results do not overflow because the indices are computed in unsigned 32-bit (U32).
Definition at line 48 of file CLArgMinMaxLayer.h.
Constructor & Destructor Documentation
CLArgMinMaxLayer() [1/3]
CLArgMinMaxLayer (std::shared_ptr< IMemoryManager > memory_manager = nullptr)
Default Constructor.
Parameters
[in] memory_manager (Optional) Memory manager.
Definition at line 41 of file CLArgMinMaxLayer.cpp.
References CLArgMinMaxLayer::~CLArgMinMaxLayer().
     : _memory_group(std::move(memory_manager)), _results_vector(), _not_reshaped_output(), _reduction_kernels_vector(), _reshape(), _num_of_stages(), _reduction_axis()
 {
 }
CLArgMinMaxLayer() [2/3]
CLArgMinMaxLayer (const CLArgMinMaxLayer &) delete
Prevent instances of this class from being copied.
CLArgMinMaxLayer() [3/3]
CLArgMinMaxLayer (CLArgMinMaxLayer &&) delete
Prevent instances of this class to be moved.
~CLArgMinMaxLayer()
~CLArgMinMaxLayer () default
Default destructor.
Referenced by CLArgMinMaxLayer::CLArgMinMaxLayer().
Member Function Documentation
configure() [1/2]
void configure (const ICLTensor * input, int axis, ICLTensor * output, const ReductionOperation & op)
Set the input and output tensors.
Valid data layouts:
All
Valid data type configurations:
src dst
QASYMM8 U32, S32
QASYMM8_SIGNED U32, S32
S32 U32, S32
F16 U32, S32
F32 U32, S32
Parameters
[in] input Input source tensor. Data types supported: QASYMM8/QASYMM8_SIGNED/S32/F16/F32.
[in] axis Axis to find max/min index.
[out] output Output source tensor. Data types supported: U32/S32.
[in] op Reduction operation to perform. Operations supported: ARG_IDX_MAX, ARG_IDX_MIN
Definition at line 116 of file CLArgMinMaxLayer.cpp.
References CLKernelLibrary::get().
 {
     configure(CLKernelLibrary::get().get_compile_context(), input, axis, output, op);
 }
configure() [2/2]
void configure (const CLCompileContext & compile_context, const ICLTensor * input, int axis, ICLTensor * output, const ReductionOperation & op)
Set the input and output tensors.
Parameters
[in] compile_context The compile context to be used.
[in] input Input source tensor. Data types supported: QASYMM8/QASYMM8_SIGNED/S32/F16/F32.
[in] axis Axis to find max/min index.
[out] output Output source tensor. Data types supported: U32/S32.
[in] op Reduction operation to perform. Operations supported: ARG_IDX_MAX, ARG_IDX_MIN
Definition at line 121 of file CLArgMinMaxLayer.cpp.
References CLTensorAllocator::allocate(), CLTensor::allocator(), ARM_COMPUTE_ERROR_ON_NULLPTR, ARM_COMPUTE_LOG_PARAMS, arm_compute::auto_init_if_empty(), arm_compute::utils::calculate_number_of_stages_only_x_axis(), ICloneable< T >::clone(), arm_compute::misc::shape_calculator::compute_reduced_shape(), CLReshapeLayer::configure(), ITensorInfo::data_type(), ITensorInfo::dimension(), ITensor::info(), arm_compute::test::validation::input, MemoryGroup::manage(), arm_compute::test::validation::output_shape, arm_compute::S32, arm_compute::test::validation::shape, ITensorInfo::tensor_shape(), and arm_compute::UNKNOWN.
 {
     ARM_COMPUTE_ERROR_ON_NULLPTR(input, output);
     ARM_COMPUTE_LOG_PARAMS(input, axis, output, op);
     _num_of_stages  = utils::calculate_number_of_stages_only_x_axis(input->info()->dimension(0), axis);
     _reduction_axis = axis;
     const TensorShape output_shape     = arm_compute::misc::shape_calculator::compute_reduced_shape(input->info()->tensor_shape(), axis, false);
     DataType          output_data_type = (output->info()->data_type() == DataType::UNKNOWN) ? DataType::S32 : output->info()->data_type();
     auto_init_if_empty(*output->info(), input->info()->clone()->set_tensor_shape(output_shape).set_data_type(output_data_type).reset_padding().set_is_resizable(true));
     // Configure reduction operation kernels
     _reduction_kernels_vector.reserve(_num_of_stages);
     auto add_reduction_kernel = [this, &compile_context, axis, op](const ICLTensor * input, const ICLTensor * prev_output, ICLTensor * output)
     {
         _reduction_kernels_vector.emplace_back(std::make_unique<CLArgMinMaxLayerKernel>());
         _reduction_kernels_vector.back()->configure(compile_context, input, prev_output, output, axis, op);
     };
     _memory_group.manage(&_not_reshaped_output);
     // Create temporary tensors
     if(_num_of_stages == 1)
     {
         add_reduction_kernel(input, nullptr, &_not_reshaped_output);
     }
     else
     {
         _results_vector.resize(_num_of_stages - 1);
         TensorShape shape{ input->info()->tensor_shape() };
         for(unsigned int i = 0; i < _num_of_stages - 1; i++)
         {
             shape.set(0, ceil(shape.x() / 128.f));
             _results_vector[i].allocator()->init(input->info()->clone()->set_tensor_shape(shape).set_data_type(output_data_type));
         }
         // Apply ReductionOperation only on first kernel
         _memory_group.manage(&_results_vector[0]);
         add_reduction_kernel(input, nullptr, &_results_vector[0]);
         // Apply ReductionOperation on intermediate stages
         for(unsigned int i = 1; i < _num_of_stages - 1; ++i)
         {
             _memory_group.manage(&_results_vector[i]);
             add_reduction_kernel(input, &_results_vector[i - 1], &_results_vector[i]);
             _results_vector[i - 1].allocator()->allocate();
         }
         // Apply ReductionOperation on the last stage
         const unsigned int last_stage = _num_of_stages - 1;
         add_reduction_kernel(input, &_results_vector[last_stage - 1], &_not_reshaped_output);
         _results_vector[last_stage - 1].allocator()->allocate();
     }
     _reshape.configure(compile_context, &_not_reshaped_output, output);
     _not_reshaped_output.allocator()->allocate();
 }
operator=() [1/2]
CLArgMinMaxLayer& operator= (const CLArgMinMaxLayer &) delete
Prevent instances of this class from being copied.
operator=() [2/2]
CLArgMinMaxLayer& operator= (CLArgMinMaxLayer &&) delete
Prevent instances of this class to be moved.
run()
void run () override virtual
Run the kernels contained in the function.
For CPU kernels:
Multi-threading is used for the kernels which are parallelisable.
By default std::thread::hardware_concurrency() threads are used.
Note
CPPScheduler::set_num_threads() can be used to manually set the number of threads
For OpenCL kernels:
All the kernels are enqueued on the queue associated with CLScheduler.
The queue is then flushed.
Note
The function will not block until the kernels are executed. It is the user's responsibility to wait.
Will call prepare() on first run if hasn't been done
Implements IFunction.
Definition at line 179 of file CLArgMinMaxLayer.cpp.
References CLScheduler::enqueue(), CLScheduler::get(), and CLReshapeLayer::run().
 {
     MemoryGroupResourceScope scope_mg(_memory_group);
     for(unsigned int i = 0; i < _num_of_stages; ++i)
     {
         CLScheduler::get().enqueue(*_reduction_kernels_vector[i], false);
     }
     _reshape.run();
 }
validate()
Status validate (const ITensorInfo * input, int axis, const ITensorInfo * output, const ReductionOperation & op) static
Static function to check if given info will lead to a valid configuration of CLArgMinMaxLayer.
Parameters
[in] input Input source tensor info. Data types supported: QASYMM8/QASYMM8_SIGNED/S32/F16/F32.
[in] axis Axis to find max/min index.
[in] output Output source tensor info. Data types supported: U32/S32.
[in] op Reduction operation to perform. Operations supported: ARG_IDX_MAX, ARG_IDX_MIN
Returns
a status
Definition at line 48 of file CLArgMinMaxLayer.cpp.
References arm_compute::ARG_IDX_MAX, arm_compute::ARG_IDX_MIN, ARM_COMPUTE_ERROR_ON_NULLPTR, ARM_COMPUTE_RETURN_ERROR_ON_DATA_TYPE_CHANNEL_NOT_IN, ARM_COMPUTE_RETURN_ERROR_ON_F16_UNSUPPORTED, ARM_COMPUTE_RETURN_ERROR_ON_MISMATCHING_SHAPES, ARM_COMPUTE_RETURN_ERROR_ON_MSG, ARM_COMPUTE_RETURN_ON_ERROR, arm_compute::utils::calculate_number_of_stages_only_x_axis(), ICloneable< T >::clone(), arm_compute::misc::shape_calculator::compute_reduced_shape(), arm_compute::test::validation::data_type, ITensorInfo::data_type(), ITensorInfo::dimension(), arm_compute::F16, arm_compute::F32, ITensorInfo::num_channels(), Dimensions< size_t >::num_max_dimensions, arm_compute::QASYMM8, arm_compute::QASYMM8_SIGNED, arm_compute::test::validation::qinfo, ITensorInfo::quantization_info(), arm_compute::S32, TensorShape::set(), TensorInfo::set_data_type(), ITensorInfo::set_num_channels(), ITensorInfo::set_quantization_info(), ITensorInfo::set_tensor_shape(), arm_compute::test::validation::shape, ITensorInfo::tensor_shape(), ITensorInfo::total_size(), CLReshapeLayer::validate(), and CLArgMinMaxLayerKernel::validate().
Referenced by arm_compute::test::validation::DATA_TEST_CASE().
 {
     ARM_COMPUTE_ERROR_ON_NULLPTR(input, output);
     ARM_COMPUTE_RETURN_ERROR_ON_F16_UNSUPPORTED(input);
     ARM_COMPUTE_RETURN_ERROR_ON_DATA_TYPE_CHANNEL_NOT_IN(input, 1, DataType::QASYMM8, DataType::QASYMM8_SIGNED, DataType::S32, DataType::F16, DataType::F32);
     ARM_COMPUTE_RETURN_ERROR_ON_MSG(op != ReductionOperation::ARG_IDX_MAX && op != ReductionOperation::ARG_IDX_MIN, "Invalid reduction operation");
     ARM_COMPUTE_RETURN_ERROR_ON_MSG(axis >= static_cast<int>(TensorShape::num_max_dimensions), "Reduction axis greater than max number of dimensions");
     ARM_COMPUTE_RETURN_ERROR_ON_MSG(axis > 3, "Unsupported reduction axis");
     const unsigned int num_of_stages = utils::calculate_number_of_stages_only_x_axis(input->dimension(0), axis);
     DataType   output_data_type = DataType::S32;
     TensorInfo not_reshaped_output;
     const auto input_num_channles = input->num_channels();
     const auto input_qinfo        = input->quantization_info();
     if(output->total_size() != 0)
     {
         output_data_type                       = output->data_type();
         const TensorInfo expected_output_shape = output->clone()->set_tensor_shape(arm_compute::misc::shape_calculator::compute_reduced_shape(input->tensor_shape(), axis, false));
         ARM_COMPUTE_RETURN_ERROR_ON_MISMATCHING_SHAPES(&expected_output_shape, output);
     }
     auto shape_before_reshape = input->tensor_shape();
     shape_before_reshape.set(axis, 1);
     auto initialize_tensorinfo = [](TensorInfo & ti, TensorShape shape, DataType data_type, int num_channels, QuantizationInfo qinfo)
     {
         ti.set_data_type(data_type).set_tensor_shape(shape).set_num_channels(num_channels).set_quantization_info(qinfo);
     };
     initialize_tensorinfo(not_reshaped_output, shape_before_reshape, output_data_type, input_num_channles, input_qinfo);
     if(num_of_stages == 1)
     {
         ARM_COMPUTE_RETURN_ON_ERROR(CLArgMinMaxLayerKernel::validate(input, nullptr, &not_reshaped_output, axis, op));
     }
     else
     {
         // Create temporary tensor infos
         std::vector<TensorInfo> sums_vector(num_of_stages - 1);
         // Create intermediate tensor info
         TensorShape shape{ input->tensor_shape() };
         for(unsigned int i = 0; i < num_of_stages - 1; i++)
         {
             shape.set(0, ceil(shape.x() / 128.f));
             sums_vector[i].set_data_type(input->data_type());
             sums_vector[i].set_tensor_shape(shape);
             sums_vector[i].set_num_channels(input->num_channels());
         }
         // Validate ReductionOperation only on first kernel
         ARM_COMPUTE_RETURN_ON_ERROR(CLArgMinMaxLayerKernel::validate(input, nullptr, &sums_vector[0], axis, op));
         // Validate ReductionOperation on intermediate stages
         for(unsigned int i = 1; i < num_of_stages - 1; ++i)
         {
             ARM_COMPUTE_RETURN_ON_ERROR(CLArgMinMaxLayerKernel::validate(input, &sums_vector[i - 1], &sums_vector[i], axis, op));
         }
         // Validate ReductionOperation on the last stage
         const unsigned int last_stage = num_of_stages - 1;
         ARM_COMPUTE_RETURN_ON_ERROR(CLArgMinMaxLayerKernel::validate(input, &sums_vector[last_stage - 1], &not_reshaped_output, axis, op));
     }
     ARM_COMPUTE_RETURN_ON_ERROR(CLReshapeLayer::validate(&not_reshaped_output, output));
     return Status{};
 }
The documentation for this class was generated from the following files:
arm_compute/runtime/CL/functions/CLArgMinMaxLayer.h
src/runtime/CL/functions/CLArgMinMaxLayer.cpp