Compute Library: CLFill Class Reference
CLFill Class Reference
Basic function to run opencl::kernels::ClFillKernel.
#include <CLFill.h>
Public Member Functions
CLFill ()
Constructor.
~CLFill ()
Destructor.
CLFill (const CLFill &)=delete
Prevent instances of this class from being copied (As this class contains pointers)
CLFill (CLFill &&)
Default move constructor.
CLFill & operator= (const CLFill &)=delete
Prevent instances of this class from being copied (As this class contains pointers)
CLFill & operator= (CLFill &&)
Default move assignment operator.
void configure (ICLTensor *tensor, const PixelValue &constant_value, Window *window=nullptr)
Initialize the kernel's tensor and filling value.
void configure (const CLCompileContext &compile_context, ICLTensor *tensor, const PixelValue &constant_value, Window *window=nullptr)
Initialise the kernel's tensor and filling value.
void run () override
Run the kernels contained in the function.
Public Member Functions inherited from IFunction
virtual ~IFunction ()=default
Destructor.
virtual void prepare ()
Prepare the function for executing.
Static Public Member Functions
static Status validate (const ITensorInfo *tensor, const PixelValue &constant_value, Window *window=nullptr)
Static function to check if given info will lead to a valid configuration of CLFill.
Detailed Description
Basic function to run opencl::kernels::ClFillKernel.
Definition at line 38 of file CLFill.h.
Constructor & Destructor Documentation
CLFill() [1/3]
CLFill ()
Constructor.
Definition at line 44 of file CLFill.cpp.
References CLFill::operator=(), and CLFill::~CLFill().
     : _impl(std::make_unique<Impl>())
 {
 }
~CLFill()
~CLFill () default
Destructor.
Referenced by CLFill::CLFill().
CLFill() [2/3]
CLFill (const CLFill &) delete
Prevent instances of this class from being copied (As this class contains pointers)
CLFill() [3/3]
CLFill (CLFill &&) default
Default move constructor.
Member Function Documentation
configure() [1/2]
void configure (ICLTensor * tensor, const PixelValue & constant_value, Window * window = nullptr)
Initialize the kernel's tensor and filling value.
Valid data layouts:
All
Valid data type configurations:
src dst
All All
Parameters
[in,out] tensor Input tensor to fill. Supported data types: All.
[in] constant_value The value used to fill the planes of the tensor
[in] window Window to be used in case setting only part of a tensor. Default is nullptr.
Definition at line 52 of file CLFill.cpp.
References CLKernelLibrary::get().
Referenced by CLDeconvolutionLayerUpsample::configure(), CLSpaceToBatchLayer::configure(), CLMaxUnpoolingLayer::configure(), and CLLSTMLayer::configure().
 {
     configure(CLKernelLibrary::get().get_compile_context(), tensor, constant_value, dst_window);
 }
configure() [2/2]
void configure (const CLCompileContext & compile_context, ICLTensor * tensor, const PixelValue & constant_value, Window * window = nullptr)
Initialise the kernel's tensor and filling value.
Parameters
[in] compile_context The compile context to be used.
[in,out] tensor Input tensor to fill. Supported data types: All.
[in] constant_value The value used to fill the planes of the tensor
[in] window Window to be used in case setting only part of a tensor. Default is nullptr.
Definition at line 57 of file CLFill.cpp.
References ARM_COMPUTE_ERROR_ON_NULLPTR.
 {
     ARM_COMPUTE_ERROR_ON_NULLPTR(tensor);
     _impl->src = tensor;
     _impl->op = std::make_unique<opencl::ClFill>();
     _impl->op->configure(compile_context, _impl->src->info(), constant_value, dst_window);
 }
operator=() [1/2]
CLFill& operator= (const CLFill &) delete
Prevent instances of this class from being copied (As this class contains pointers)
Referenced by CLFill::CLFill().
operator=() [2/2]
CLFill & operator= (CLFill &&) default
Default move assignment operator.
run()
void run () override virtual
Run the kernels contained in the function.
For CPU kernels:
Multi-threading is used for the kernels which are parallelisable.
By default std::thread::hardware_concurrency() threads are used.
Note
CPPScheduler::set_num_threads() can be used to manually set the number of threads
For OpenCL kernels:
All the kernels are enqueued on the queue associated with CLScheduler.
The queue is then flushed.
Note
The function will not block until the kernels are executed. It is the user's responsibility to wait.
Will call prepare() on first run if hasn't been done
Implements IFunction.
Definition at line 72 of file CLFill.cpp.
References arm_compute::ACL_SRC, ITensorPack::add_tensor(), and arm_compute::test::validation::pack.
Referenced by CLDeconvolutionLayerUpsample::run(), CLMaxUnpoolingLayer::run(), CLSpaceToBatchLayer::run(), and CLLSTMLayer::run().
 {
     ITensorPack pack;
     pack.add_tensor(TensorType::ACL_SRC, _impl->src);
     _impl->op->run(pack);
 }
validate()
Status validate (const ITensorInfo * tensor, const PixelValue & constant_value, Window * window = nullptr) static
Static function to check if given info will lead to a valid configuration of CLFill.
Parameters
[in] tensor Source tensor info. Data types supported: All.
[in] constant_value The value used to fill the planes of the tensor
[in] window Window to be used in case setting only part of a tensor. Default is nullptr.
Returns
a status
Definition at line 67 of file CLFill.cpp.
References ClFill::validate().
Referenced by CLSpaceToBatchLayer::validate().
 {
     return opencl::ClFill::validate(tensor, constant_value, dst_window);
 }
The documentation for this class was generated from the following files:
arm_compute/runtime/CL/functions/CLFill.h
src/runtime/CL/functions/CLFill.cpp