Compute Library: CLRemapKernel Class Reference
CLRemapKernel Class Reference
OpenCL kernel to perform a remap on a tensor.
#include <CLRemapKernel.h>
Public Member Functions
CLRemapKernel ()
Default constructor.
CLRemapKernel (const CLRemapKernel &)=delete
Prevent instances of this class from being copied (As this class contains pointers)
CLRemapKernel & operator= (const CLRemapKernel &)=delete
Prevent instances of this class from being copied (As this class contains pointers)
CLRemapKernel (CLRemapKernel &&)=default
Allow instances of this class to be moved.
CLRemapKernel & operator= (CLRemapKernel &&)=default
Allow instances of this class to be moved.
void configure (const CLCompileContext &compile_context, const ICLTensor *input, const ICLTensor *map_x, const ICLTensor *map_y, ICLTensor *output, RemapInfo info)
Initialize the kernel's input, output and border mode.
template<class T >
void set_constant_border (unsigned int idx, const PixelValue &constant_border_value)
Function to set the constant value on fill border kernel depending on type.
void run (const Window &window, cl::CommandQueue &queue) override
Enqueue the OpenCL kernel to process the given window on the passed OpenCL command queue.
BorderSize border_size () const override
The size of the border for that kernel.
Public Member Functions inherited from ICLKernel
ICLKernel ()
Constructor.
cl::Kernel & kernel ()
Returns a reference to the OpenCL kernel of this object.
CLKernelType type () const
Returns the CL kernel type.
template<typename T >
void add_1D_array_argument (unsigned int &idx, const ICLArray< T > *array, const Strides &strides, unsigned int num_dimensions, const Window &window)
Add the passed 1D array's parameters to the object's kernel's arguments starting from the index idx.
void add_1D_tensor_argument (unsigned int &idx, const ICLTensor *tensor, const Window &window)
Add the passed 1D tensor's parameters to the object's kernel's arguments starting from the index idx.
void add_1D_tensor_argument_if (bool cond, unsigned int &idx, const ICLTensor *tensor, const Window &window)
Add the passed 1D tensor's parameters to the object's kernel's arguments starting from the index idx if the condition is true.
void add_2D_tensor_argument (unsigned int &idx, const ICLTensor *tensor, const Window &window)
Add the passed 2D tensor's parameters to the object's kernel's arguments starting from the index idx.
void add_2D_tensor_argument_if (bool cond, unsigned int &idx, const ICLTensor *tensor, const Window &window)
Add the passed 2D tensor's parameters to the object's kernel's arguments starting from the index idx if the condition is true.
void add_3D_tensor_argument (unsigned int &idx, const ICLTensor *tensor, const Window &window)
Add the passed 3D tensor's parameters to the object's kernel's arguments starting from the index idx.
void add_4D_tensor_argument (unsigned int &idx, const ICLTensor *tensor, const Window &window)
Add the passed 4D tensor's parameters to the object's kernel's arguments starting from the index idx.
virtual void run_op (ITensorPack &tensors, const Window &window, cl::CommandQueue &queue)
Enqueue the OpenCL kernel to process the given window on the passed OpenCL command queue.
template<typename T >
void add_argument (unsigned int &idx, T value)
Add the passed parameters to the object's kernel's arguments starting from the index idx.
void set_lws_hint (const cl::NDRange &lws_hint)
Set the Local-Workgroup-Size hint.
cl::NDRange lws_hint () const
Return the Local-Workgroup-Size hint.
void set_wbsm_hint (const cl_int &wbsm_hint)
Set the workgroup batch size modifier hint.
cl_int wbsm_hint () const
Return the workgroup batch size modifier hint.
const std::string & config_id () const
Get the configuration ID.
void set_target (GPUTarget target)
Set the targeted GPU architecture.
void set_target (cl::Device &device)
Set the targeted GPU architecture according to the CL device.
GPUTarget get_target () const
Get the targeted GPU architecture.
size_t get_max_workgroup_size ()
Get the maximum workgroup size for the device the CLKernelLibrary uses.
template<unsigned int dimension_size>
void add_tensor_argument (unsigned &idx, const ICLTensor *tensor, const Window &window)
template<typename T , unsigned int dimension_size>
void add_array_argument (unsigned &idx, const ICLArray< T > *array, const Strides &strides, unsigned int num_dimensions, const Window &window)
Add the passed array's parameters to the object's kernel's arguments starting from the index idx.
Public Member Functions inherited from IKernel
IKernel ()
Constructor.
virtual ~IKernel ()=default
Destructor.
virtual bool is_parallelisable () const
Indicates whether or not the kernel is parallelisable.
const Window & window () const
The maximum window the kernel can be executed on.
bool is_window_configured () const
Function to check if the embedded window of this kernel has been configured.
Static Public Member Functions
static Status validate (const ITensorInfo *input, const ITensorInfo *map_x, const ITensorInfo *map_y, const ITensorInfo *output, RemapInfo info)
Checks if the kernel's input, output and border mode will lead to a valid configuration of CLRemapKernel.
Static Public Member Functions inherited from ICLKernel
static constexpr unsigned int num_arguments_per_1D_array ()
Returns the number of arguments enqueued per 1D array object.
static constexpr unsigned int num_arguments_per_1D_tensor ()
Returns the number of arguments enqueued per 1D tensor object.
static constexpr unsigned int num_arguments_per_2D_tensor ()
Returns the number of arguments enqueued per 2D tensor object.
static constexpr unsigned int num_arguments_per_3D_tensor ()
Returns the number of arguments enqueued per 3D tensor object.
static constexpr unsigned int num_arguments_per_4D_tensor ()
Returns the number of arguments enqueued per 4D tensor object.
static cl::NDRange gws_from_window (const Window &window)
Get the global work size given an execution window.
Detailed Description
OpenCL kernel to perform a remap on a tensor.
Definition at line 36 of file CLRemapKernel.h.
Constructor & Destructor Documentation
CLRemapKernel() [1/3]
CLRemapKernel ()
Default constructor.
Definition at line 37 of file CLRemapKernel.cpp.
References arm_compute::ELEMENTWISE, and arm_compute::NCHW.
     : _input(nullptr), _output(nullptr), _map_x(nullptr), _map_y(nullptr), _data_layout(DataLayout::NCHW)
 {
     _type = CLKernelType::ELEMENTWISE;
 }
CLRemapKernel() [2/3]
CLRemapKernel (const CLRemapKernel &) delete
Prevent instances of this class from being copied (As this class contains pointers)
CLRemapKernel() [3/3]
CLRemapKernel (CLRemapKernel &&) default
Allow instances of this class to be moved.
Member Function Documentation
border_size()
BorderSize border_size () const override virtual
The size of the border for that kernel.
Returns
The width in number of elements of the border.
Reimplemented from IKernel.
Definition at line 43 of file CLRemapKernel.cpp.
References arm_compute::NCHW.
Referenced by CLRemapKernel::configure().
 {
     return _data_layout == DataLayout::NCHW ? BorderSize(1) : BorderSize(0);
 }
configure()
void configure (const CLCompileContext & compile_context, const ICLTensor * input, const ICLTensor * map_x, const ICLTensor * map_y, ICLTensor * output, RemapInfo info)
Initialize the kernel's input, output and border mode.
Parameters
[in] compile_context The compile context to be used.
[in] input Source tensor. Data types supported: U8 (or F16 when layout is NHWC).
[in] map_x Map for X coordinates. Data types supported: F32.
[in] map_y Map for Y coordinates. Data types supported: F32.
[out] output Destination tensor. Data types supported: Same as input. All but the lowest two dimensions must be the same size as in the input tensor, i.e. remapping is only performed within the XY-plane.
[in] info RemapInfo struct:
policy Interpolation policy to use. Only NEAREST and BILINEAR are supported.
border_mode Border mode to use on the input tensor. Only CONSTANT and UNDEFINED are supported.
constant_border_value Constant value to use for borders if border_mode is set to CONSTANT.
Definition at line 75 of file CLRemapKernel.cpp.
References CLBuildOptions::add_option(), CLBuildOptions::add_option_if(), ARM_COMPUTE_ERROR, ARM_COMPUTE_ERROR_ON_NULLPTR, ARM_COMPUTE_ERROR_THROW_ON, RemapInfo::border_mode, CLRemapKernel::border_size(), BorderSize::bottom, arm_compute::calculate_max_window(), arm_compute::ceil_to_multiple(), arm_compute::CONSTANT, RemapInfo::constant_border_value, arm_compute::create_kernel(), ITensorInfo::data_layout(), ITensorInfo::data_type(), ITensorInfo::dimension(), arm_compute::F16, arm_compute::get_cl_type_from_data_type(), arm_compute::get_data_layout_dimension_index(), arm_compute::HEIGHT, arm_compute::test::validation::idx_height, arm_compute::test::validation::idx_width, ITensor::info(), arm_compute::test::validation::info, arm_compute::test::validation::input, input_height, input_width, kernel_name, BorderSize::left, arm_compute::lower_string(), arm_compute::NCHW, arm_compute::NHWC, ICLKernel::num_arguments_per_2D_tensor(), ICLKernel::num_arguments_per_4D_tensor(), num_elems_processed_per_iteration, CLBuildOptions::options(), RemapInfo::policy, BorderSize::right, arm_compute::string_from_data_layout(), arm_compute::string_from_interpolation_policy(), arm_compute::support::cpp11::to_string(), BorderSize::top, arm_compute::U8, arm_compute::update_window_and_padding(), CLRemapKernel::validate(), and arm_compute::WIDTH.
 {
     ARM_COMPUTE_ERROR_ON_NULLPTR(input, map_x, map_y, output);
     ARM_COMPUTE_ERROR_THROW_ON(CLRemapKernel::validate(input->info(), map_x->info(), map_y->info(), output->info(), info));
     _input       = input;
     _output      = output;
     _map_x       = map_x;
     _map_y       = map_y;
     _data_layout = input->info()->data_layout();
     const bool is_nhwc            = _data_layout == DataLayout::NHWC;
     const bool is_constant_border = info.border_mode == BorderMode::CONSTANT;
     // Create kernel
     CLBuildOptions build_opts;
     build_opts.add_option(("-DDATA_TYPE=" + get_cl_type_from_data_type(input->info()->data_type())));
     build_opts.add_option_if(is_nhwc, "-DDEPTH_OUT=" + support::cpp11::to_string(output->info()->dimension(2)));
     build_opts.add_option_if(is_constant_border, "-DCONSTANT_BORDER");
     const std::string interpolation_name = lower_string(string_from_interpolation_policy(info.policy));
     const std::string kernel_name        = "remap_" + interpolation_name + "_" + lower_string(string_from_data_layout(_data_layout));
     _kernel                              = create_kernel(compile_context, kernel_name, build_opts.options());
     const unsigned int num_elems_processed_per_iteration = is_nhwc ? 1 : 4;
     const int          idx_height                        = get_data_layout_dimension_index(_data_layout, DataLayoutDimension::HEIGHT);
     const int          idx_width                         = get_data_layout_dimension_index(_data_layout, DataLayoutDimension::WIDTH);
     const int          input_height                      = input->info()->dimension(idx_height);
     const int          input_width                       = input->info()->dimension(idx_width);
     // Configure window
     Window win = calculate_max_window(*_output->info(), Steps(num_elems_processed_per_iteration));
     // Update padding in NCHW case
     if(_data_layout == DataLayout::NCHW)
     {
         const int          total_right  = ceil_to_multiple(input_width, num_elems_processed_per_iteration);
         const int          access_right = total_right + (((total_right - input_width) == 0) ? border_size().right : 0);
         AccessWindowStatic input_access(input->info(), -border_size().left, -border_size().top, access_right, input_height + border_size().bottom);
         AccessWindowHorizontal output_access(output->info(), 0, num_elems_processed_per_iteration);
         update_window_and_padding(win, input_access, output_access);
     }
     ICLKernel::configure_internal(win);
     // Set static arguments
     unsigned int idx = 4 * (is_nhwc ? num_arguments_per_4D_tensor() : num_arguments_per_2D_tensor());
     _kernel.setArg<cl_float>(idx++, input_width);
     _kernel.setArg<cl_float>(idx++, input_height);
     if(is_nhwc && is_constant_border)
     {
         switch(input->info()->data_type())
         {
             case DataType::U8:
                 set_constant_border<uint8_t>(idx, info.constant_border_value);
                 break;
             case DataType::F16:
                 static_assert(sizeof(cl_half) == sizeof(half), "Half must be same size as cl_half");
                 static_assert(sizeof(cl_half) == 2, "Half must be 16 bit");
                 set_constant_border<half>(idx, info.constant_border_value);
                 break;
             default:
                 ARM_COMPUTE_ERROR("Data Type not handled");
         }
     }
 }
operator=() [1/2]
CLRemapKernel& operator= (const CLRemapKernel &) delete
Prevent instances of this class from being copied (As this class contains pointers)
operator=() [2/2]
CLRemapKernel& operator= (CLRemapKernel &&) default
Allow instances of this class to be moved.
run()
void run (const Window & window, cl::CommandQueue & queue) override virtual
Enqueue the OpenCL kernel to process the given window on the passed OpenCL command queue.
Note
The queue is not flushed by this method, and therefore the kernel will not have been executed by the time this method returns.
Parameters
[in] window Region on which to execute the kernel. (Must be a valid region of the window returned by window()).
[in,out] queue Command queue on which to enqueue the kernel.
Reimplemented from ICLKernel.
Definition at line 144 of file CLRemapKernel.cpp.
References ICLKernel::add_2D_tensor_argument(), ICLKernel::add_4D_tensor_argument(), ARM_COMPUTE_ERROR, ARM_COMPUTE_ERROR_ON_INVALID_SUBWINDOW, ARM_COMPUTE_ERROR_ON_UNCONFIGURED_KERNEL, Window::collapse(), Window::DimZ, arm_compute::enqueue(), Window::first_slice_window_2D(), Window::first_slice_window_4D(), ICLKernel::lws_hint(), arm_compute::NCHW, arm_compute::NHWC, arm_compute::test::validation::reference::slice(), Window::slide_window_slice_2D(), and IKernel::window().
 {
     ARM_COMPUTE_ERROR_ON_UNCONFIGURED_KERNEL(this);
     ARM_COMPUTE_ERROR_ON_INVALID_SUBWINDOW(ICLKernel::window(), window);
     switch(_data_layout)
     {
         case DataLayout::NCHW:
         {
             Window slice = window.first_slice_window_2D();
             do
             {
                 unsigned int idx = 0;
                 add_2D_tensor_argument(idx, _input, slice);
                 add_2D_tensor_argument(idx, _output, slice);
                 add_2D_tensor_argument(idx, _map_x, slice);
                 add_2D_tensor_argument(idx, _map_y, slice);
                 enqueue(queue, *this, slice, lws_hint());
             }
             while(window.slide_window_slice_2D(slice));
             break;
         }
         case DataLayout::NHWC:
         {
             Window collapsed = window.collapse(ICLKernel::window(), Window::DimZ);
             Window slice     = collapsed.first_slice_window_4D();
             unsigned int idx = 0;
             add_4D_tensor_argument(idx, _input, slice);
             add_4D_tensor_argument(idx, _output, slice);
             add_4D_tensor_argument(idx, _map_x, slice);
             add_4D_tensor_argument(idx, _map_y, slice);
             enqueue(queue, *this, slice, lws_hint());
             break;
         }
         default:
             ARM_COMPUTE_ERROR("Invalid Data layout");
     }
 }
set_constant_border()
void set_constant_border (unsigned int idx, const PixelValue & constant_border_value)
Function to set the constant value on fill border kernel depending on type.
Parameters
[in] idx Index of the kernel argument to set.
[in] constant_border_value Constant value to use for borders if border_mode is set to CONSTANT.
Definition at line 49 of file CLRemapKernel.cpp.
References PixelValue::get().
 {
     T value;
     constant_border_value.get(value);
     ICLKernel::add_argument<T>(idx, static_cast<T>(value));
 }
validate()
Status validate (const ITensorInfo * input, const ITensorInfo * map_x, const ITensorInfo * map_y, const ITensorInfo * output, RemapInfo info) static
Checks if the kernel's input, output and border mode will lead to a valid configuration of CLRemapKernel.
Similar to CLRemapKernel::configure(const CLCompileContext &compile_context, const ICLTensor *input, const ICLTensor *map_x, const ICLTensor *map_y, ICLTensor *output, RemapInfo info)
Definition at line 56 of file CLRemapKernel.cpp.
References arm_compute::AREA, ARM_COMPUTE_RETURN_ERROR_ON_DATA_TYPE_CHANNEL_NOT_IN, ARM_COMPUTE_RETURN_ERROR_ON_MSG, ARM_COMPUTE_RETURN_ERROR_ON_NULLPTR, RemapInfo::border_mode, arm_compute::CONSTANT, ITensorInfo::data_layout(), ITensorInfo::data_type(), arm_compute::F16, arm_compute::F32, arm_compute::NCHW, RemapInfo::policy, arm_compute::U8, and arm_compute::UNDEFINED.
Referenced by CLRemapKernel::configure(), and CLRemap::validate().
 {
     ARM_COMPUTE_RETURN_ERROR_ON_NULLPTR(input, map_x, map_y, output);
     if(input->data_layout() == DataLayout::NCHW)
     {
         ARM_COMPUTE_RETURN_ERROR_ON_DATA_TYPE_CHANNEL_NOT_IN(input, 1, DataType::U8);
     }
     else
     {
         ARM_COMPUTE_RETURN_ERROR_ON_DATA_TYPE_CHANNEL_NOT_IN(input, 1, DataType::U8, DataType::F16);
     }
     ARM_COMPUTE_RETURN_ERROR_ON_MSG(input->data_type() != output->data_type(), "Input/output have different data types");
     ARM_COMPUTE_RETURN_ERROR_ON_DATA_TYPE_CHANNEL_NOT_IN(map_x, 1, DataType::F32);
     ARM_COMPUTE_RETURN_ERROR_ON_DATA_TYPE_CHANNEL_NOT_IN(map_y, 1, DataType::F32);
     ARM_COMPUTE_RETURN_ERROR_ON_MSG(info.policy == InterpolationPolicy::AREA, "Area interpolation is not supported!");
     ARM_COMPUTE_RETURN_ERROR_ON_MSG(info.border_mode != BorderMode::CONSTANT && info.border_mode != BorderMode::UNDEFINED, "Border mode not supported");
     return Status{};
 }
The documentation for this class was generated from the following files:
src/core/CL/kernels/CLRemapKernel.h
src/core/CL/kernels/CLRemapKernel.cpp