Compute Library: CpuDirectConv2dKernel Class Reference
CpuDirectConv2dKernel Class Reference
Interface for the kernel to perform Direct Convolution Layer.
#include <CpuDirectConv2dKernel.h>
Public Member Functions
CpuDirectConv2dKernel ()=default
ARM_COMPUTE_DISALLOW_COPY_ALLOW_MOVE (CpuDirectConv2dKernel)
void configure (ITensorInfo *src, ITensorInfo *weights, ITensorInfo *dst, const PadStrideInfo &conv_info)
Set the src, weights, and dst tensors.
void run_op (ITensorPack &tensors, const Window &window, const ThreadInfo &info) override
Execute the kernel on the passed window.
const char * name () const override
Name of the kernel.
BorderSize border_size () const override
The size of the border for that kernel.
Public Member Functions inherited from ICPPKernel
virtual ~ICPPKernel ()=default
Default destructor.
virtual void run (const Window &window, const ThreadInfo &info)
Execute the kernel on the passed window.
virtual void run_nd (const Window &window, const ThreadInfo &info, const Window &thread_locator)
legacy compatibility layer for implemantions which do not support thread_locator In these cases we simply narrow the interface down the legacy version
virtual size_t get_mws (const CPUInfo &platform, size_t thread_count) const
Return minimum workload size of the relevant kernel.
Public Member Functions inherited from IKernel
IKernel ()
Constructor.
virtual ~IKernel ()=default
Destructor.
virtual bool is_parallelisable () const
Indicates whether or not the kernel is parallelisable.
const Window & window () const
The maximum window the kernel can be executed on.
bool is_window_configured () const
Function to check if the embedded window of this kernel has been configured.
Static Public Member Functions
static Status validate (const ITensorInfo *src, const ITensorInfo *weights, const ITensorInfo *dst, const PadStrideInfo &conv_info)
Static function to check if given info will lead to a valid configuration.
Additional Inherited Members
Static Public Attributes inherited from ICPPKernel
static constexpr size_t default_mws = 128
static constexpr size_t small_network_mws = 256
Detailed Description
Interface for the kernel to perform Direct Convolution Layer.
Definition at line 37 of file CpuDirectConv2dKernel.h.
Constructor & Destructor Documentation
CpuDirectConv2dKernel()
CpuDirectConv2dKernel () default
Member Function Documentation
ARM_COMPUTE_DISALLOW_COPY_ALLOW_MOVE()
ARM_COMPUTE_DISALLOW_COPY_ALLOW_MOVE (CpuDirectConv2dKernel)
border_size()
BorderSize border_size () const override virtual
The size of the border for that kernel.
Returns
The width in number of elements of the border.
Reimplemented from IKernel.
Definition at line 1211 of file CpuDirectConv2dKernel.cpp.
 {
     return _border_size;
 }
configure()
void configure (ITensorInfo * src, ITensorInfo * weights, ITensorInfo * dst, const PadStrideInfo & conv_info)
Set the src, weights, and dst tensors.
Note
: DirectConvolution only works in the following configurations: 1x1 convolution with stride_x = 1/2/3, stride_y = 1/2/3 3x3 convolution with stride_x = 1/2/3, stride_y = 1/2/3
Parameters
[in] src The input tensor to convolve. 3 lower dimensions represent a single input [width, height, IFM], while every optional dimension from 4 and above represent a batch of inputs. Data types supported: F16/F32.
[in] weights Weights tensor. Weights are 4D tensor with dimensions [kernel_x, kernel_y, IFM, OFM]. The 3rd dimension must be the same as the input's volume 3rd dimension. Data type supported:Same as input.
[out] dst Output tensor. The 3rd dimensions must be equal to the 4th dimension of the kernels tensor. Data types supported: F16/F32
[in] conv_info Contains padding and stride information described in PadStrideInfo.
Definition at line 1216 of file CpuDirectConv2dKernel.cpp.
References ARM_COMPUTE_ERROR_ON_NULLPTR, ARM_COMPUTE_ERROR_THROW_ON, arm_compute::auto_init_if_empty(), arm_compute::misc::shape_calculator::compute_deep_convolution_shape(), arm_compute::test::validation::configure(), arm_compute::test::validation::conv_info, ITensorInfo::data_layout(), ITensorInfo::data_type(), ITensorInfo::dimension(), arm_compute::get_data_layout_dimension_index(), arm_compute::NCHW, PadStrideInfo::pad_bottom(), PadStrideInfo::pad_left(), PadStrideInfo::pad_right(), PadStrideInfo::pad_top(), and arm_compute::WIDTH.
 {
     ARM_COMPUTE_ERROR_ON_NULLPTR(src, weights, dst);
     _conv_info   = conv_info;
     _data_layout = src->data_layout();
     _kernel_size = weights->dimension(get_data_layout_dimension_index(_data_layout, DataLayoutDimension::WIDTH));
     const unsigned int conv_pad_left   = conv_info.pad_left();
     const unsigned int conv_pad_top    = conv_info.pad_top();
     const unsigned int conv_pad_right  = conv_info.pad_right();
     const unsigned int conv_pad_bottom = conv_info.pad_bottom();
     if(_data_layout == DataLayout::NCHW)
     {
         _border_size = BorderSize(conv_pad_top, conv_pad_right, conv_pad_bottom, conv_pad_left);
     }
     else
     {
         _border_size = BorderSize(0);
     }
     // Get convolved dimensions
     TensorShape output_shape = misc::shape_calculator::compute_deep_convolution_shape(*src, *weights, conv_info);
     DataType data_type = src->data_type();
     // Output auto inizialitation if not yet initialized
     auto_init_if_empty(*dst, output_shape, 1, data_type);
     // Perform validation step
     ARM_COMPUTE_ERROR_THROW_ON(validate_arguments(src, weights, dst, conv_info));
     // Configure kernel window
     auto win_config = validate_and_configure_window(src, weights, dst, conv_info, _num_weight_elems_read_per_row,
                                                     _num_elems_read_per_iteration, _num_elems_written_per_iteration, _border_size);
     ARM_COMPUTE_ERROR_THROW_ON(win_config.first);
     ICpuKernel::configure(win_config.second);
 }
name()
const char * name () const override virtual
Name of the kernel.
Returns
Kernel name
Implements ICPPKernel.
Definition at line 1368 of file CpuDirectConv2dKernel.cpp.
 {
     return "CpuDirectConvolutionLayerKernel";
 }
run_op()
void run_op (ITensorPack & tensors, const Window & window, const ThreadInfo & info) override virtual
Execute the kernel on the passed window.
Warning
If is_parallelisable() returns false then the passed window must be equal to window()
Note
The window has to be a region within the window returned by the window() method
The width of the window has to be a multiple of num_elems_processed_per_iteration().
Parameters
[in] tensors A vector containing the tensors to operate on.
[in] window Region on which to execute the kernel. (Must be a region of the window returned by window())
[in] info Info about executing thread and CPU.
Reimplemented from ICPPKernel.
Definition at line 1275 of file CpuDirectConv2dKernel.cpp.
References arm_compute::ACL_DST, arm_compute::ACL_SRC_0, arm_compute::ACL_SRC_1, ARM_COMPUTE_ERROR, ARM_COMPUTE_ERROR_ON_INVALID_SUBWINDOW, ARM_COMPUTE_ERROR_ON_UNCONFIGURED_KERNEL, ARM_COMPUTE_UNUSED, ITensorInfo::dimension(), arm_compute::test::validation::dst, arm_compute::F16, arm_compute::F32, ITensorPack::get_const_tensor(), arm_compute::get_data_layout_dimension_index(), ITensorPack::get_tensor(), ITensor::info(), arm_compute::NCHW, arm_compute::test::validation::src, and arm_compute::WIDTH.
 {
     ARM_COMPUTE_UNUSED(info);
     ARM_COMPUTE_ERROR_ON_UNCONFIGURED_KERNEL(this);
     ARM_COMPUTE_ERROR_ON_INVALID_SUBWINDOW(ICpuKernel::window(), window);
     auto      src         = tensors.get_const_tensor(TensorType::ACL_SRC_0);
     auto      weights     = tensors.get_const_tensor(TensorType::ACL_SRC_1);
     auto      dst         = tensors.get_tensor(TensorType::ACL_DST);
     const int kernel_size = weights->info()->dimension(get_data_layout_dimension_index(_data_layout, DataLayoutDimension::WIDTH));
     if(_data_layout == DataLayout::NCHW)
     {
         switch(kernel_size)
         {
             case 1:
             {
                 switch(src->info()->data_type())
                 {
                     case DataType::F32:
                         convolve_1x1<float, float>(window, _num_elems_read_per_iteration, _num_elems_written_per_iteration, src, weights, dst, _conv_info);
                         break;
 #ifdef __ARM_FEATURE_FP16_VECTOR_ARITHMETIC
                     case DataType::F16:
                         convolve_1x1<float16_t, float16_t>(window, _num_elems_read_per_iteration, _num_elems_written_per_iteration, src, weights, dst, _conv_info);
                         break;
 #endif /* __ARM_FEATURE_FP16_VECTOR_ARITHMETIC */
                     default:
                         ARM_COMPUTE_ERROR("Data type not supported");
                         break;
                 }
                 break;
             }
             case 3:
             {
                 switch(src->info()->data_type())
                 {
                     case DataType::F32:
                         convolve_3x3<float, float>(window, _num_elems_read_per_iteration, _num_elems_written_per_iteration, src, weights, dst, _conv_info);
                         break;
 #ifdef __ARM_FEATURE_FP16_VECTOR_ARITHMETIC
                     case DataType::F16:
                         convolve_3x3<float16_t, float16_t>(window, _num_elems_read_per_iteration, _num_elems_written_per_iteration, src, weights, dst, _conv_info);
                         break;
 #endif /* __ARM_FEATURE_FP16_VECTOR_ARITHMETIC */
                     default:
                         ARM_COMPUTE_ERROR("Data type not supported");
                         break;
                 }
                 break;
             }
             case 5:
             {
                 switch(src->info()->data_type())
                 {
                     case DataType::F32:
                         convolve_5x5<float, float>(window, _num_elems_read_per_iteration, _num_elems_written_per_iteration, src, weights, dst, _conv_info);
                         break;
                     default:
                         ARM_COMPUTE_ERROR("Data type not supported");
                         break;
                 }
                 break;
             }
             default:
             {
                 ARM_COMPUTE_ERROR("Only kernel sizes 1x1, 3x3 and 5x5 are supported.");
                 break;
             }
         }
     }
     else
     {
         switch(src->info()->data_type())
         {
             case DataType::F32:
             {
                 if(have_zero_x_internal_padding(src->info(), weights->info()))
                 {
                     convolve_nhwc_optimized<float>(window, src, weights, dst);
                 }
                 else
                 {
                     convolve_nhwc<float>(window, src, weights, dst);
                 }
                 break;
             }
             default:
                 ARM_COMPUTE_ERROR("Data type not supported");
                 break;
         }
     }
 }
validate()
Status validate (const ITensorInfo * src, const ITensorInfo * weights, const ITensorInfo * dst, const PadStrideInfo & conv_info) static
Static function to check if given info will lead to a valid configuration.
Similar to CpuDirectConv2dKernel::configure()
Returns
a status
Definition at line 1255 of file CpuDirectConv2dKernel.cpp.
References ARM_COMPUTE_RETURN_ON_ERROR, ICloneable< T >::clone(), and arm_compute::test::validation::conv_info.
Referenced by CpuDirectConv2d::validate().
 {
     unsigned int num_weight_elems_read_per_row   = 0;
     unsigned int num_elems_read_per_iteration    = 0;
     unsigned int num_elems_written_per_iteration = 0;
     BorderSize   border_size                     = {};
     ARM_COMPUTE_RETURN_ON_ERROR(validate_arguments(src, weights, dst, conv_info));
     ARM_COMPUTE_RETURN_ON_ERROR(validate_and_configure_window(src->clone().get(),
                                                               weights->clone().get(),
                                                               dst->clone().get(),
                                                               conv_info,
                                                               num_weight_elems_read_per_row,
                                                               num_elems_read_per_iteration,
                                                               num_elems_written_per_iteration,
                                                               border_size)
                                 .first);
     return Status{};
 }
The documentation for this class was generated from the following files:
src/cpu/kernels/CpuDirectConv2dKernel.h
src/cpu/kernels/CpuDirectConv2dKernel.cpp