Compute Library: ICLOperator Class Reference
ICLOperator Class Reference
Basic interface for functions which have a single async CL kernel.
#include <ICLOperator.h>
Public Member Functions
ICLOperator (IRuntimeContext *ctx=nullptr)
Constructor.
ICLOperator (const ICLOperator &)=delete
Prevent instances of this class from being copied (As this class contains pointers)
ICLOperator (ICLOperator &&)=default
Default move constructor.
ICLOperator & operator= (const ICLOperator &)=delete
Prevent instances of this class from being copied (As this class contains pointers)
ICLOperator & operator= (ICLOperator &&)=default
Default move assignment operator.
void run (ITensorPack &tensors) override
Run the kernels contained in the function.
void prepare (ITensorPack &constants) override
Prepare the function for executing.
MemoryRequirements workspace () const override
Return the memory requirements required by the workspace.
Public Member Functions inherited from IOperator
virtual ~IOperator ()=default
Destructor.
Detailed Description
Basic interface for functions which have a single async CL kernel.
Definition at line 41 of file ICLOperator.h.
Constructor & Destructor Documentation
ICLOperator() [1/3]
ICLOperator (IRuntimeContext * ctx = nullptr)
Constructor.
Parameters
[in] ctx Runtime context to be used by the function
Definition at line 33 of file CLOperator.cpp.
     : _kernel(), _ctx(ctx), _workspace()
 {
 }
ICLOperator() [2/3]
ICLOperator (const ICLOperator &) delete
Prevent instances of this class from being copied (As this class contains pointers)
ICLOperator() [3/3]
ICLOperator (ICLOperator &&) default
Default move constructor.
Member Function Documentation
operator=() [1/2]
ICLOperator& operator= (const ICLOperator &) delete
Prevent instances of this class from being copied (As this class contains pointers)
operator=() [2/2]
ICLOperator& operator= (ICLOperator &&) default
Default move assignment operator.
prepare()
void prepare (ITensorPack & constants) override virtual
Prepare the function for executing.
Any one off pre-processing step required by the function is handled here
Parameters
[in] constants Vector that contains the constants tensors.
Note
Prepare stage might not need all the function's buffers' backing memory to be available in order to execute
Implements IOperator.
Reimplemented in ClConv2d, ClGemmConv2d, ClWinogradConv2d, ClGemmLowpMatrixMultiplyCore, ClFullyConnected, and ClGemm.
Definition at line 48 of file CLOperator.cpp.
References ARM_COMPUTE_UNUSED.
 {
     ARM_COMPUTE_UNUSED(constants);
 }
run()
void run (ITensorPack & tensors) override virtual
Run the kernels contained in the function.
Parameters
[in] tensors Vector that contains the tensors to operate on.
Implements IOperator.
Reimplemented in ClSynthetizeOperatorWithBorder< K >, ClConv2d, ClGemmConv2d, ClWinogradConv2d, CLSynthetizeOperatorInitOutputWithZeroAndWithZeroConstantBorder< K, bordersize >, ClGemmLowpMatrixMultiplyCore, ClFullyConnected, ClGemm, ClGemmLowpOutputStage, ClDirectConv3d, ClDirectConv2d, ClConcatenate, ClSoftmax, ClScale, ClPRelu, ClQuantize, and ClDequantize.
Definition at line 38 of file CLOperator.cpp.
References ARM_COMPUTE_ERROR, ITensorPack::empty(), CLScheduler::enqueue_op(), and CLScheduler::get().
Referenced by ClPRelu::run(), CLLogicalOr::run(), and CLLogicalAnd::run().
 {
     if(tensors.empty())
     {
         ARM_COMPUTE_ERROR("No inputs provided");
     }
     CLScheduler::get().enqueue_op(*_kernel.get(), tensors, false);
 }
workspace()
MemoryRequirements workspace () const override virtual
Return the memory requirements required by the workspace.
Implements IOperator.
Reimplemented in ClConv2d, ClGemmConv2d, ClWinogradConv2d, ClGemmLowpMatrixMultiplyCore, ClFullyConnected, ClGemm, and ClSoftmax.
Definition at line 53 of file CLOperator.cpp.
 {
     return {};
 }
The documentation for this class was generated from the following files:
arm_compute/runtime/CL/ICLOperator.h
src/runtime/CL/CLOperator.cpp