Compute Library: CLRemap Class Reference
CLRemap Class Reference
Basic function to execute remap.
#include <CLRemap.h>
Public Member Functions
void configure (const CLCompileContext &compile_context, ICLTensor *input, const ICLTensor *map_x, const ICLTensor *map_y, ICLTensor *output, InterpolationPolicy policy, BorderMode border_mode, uint8_t constant_border_value=0)
Initialise the function's sources, destination, interpolation policy and border mode.
void configure (ICLTensor *input, const ICLTensor *map_x, const ICLTensor *map_y, ICLTensor *output, InterpolationPolicy policy, BorderMode border_mode, uint8_t constant_border_value=0)
Initialise the function's sources, destination, interpolation policy and border mode.
void configure (const CLCompileContext &compile_context, ICLTensor *input, const ICLTensor *map_x, const ICLTensor *map_y, ICLTensor *output, InterpolationPolicy policy, BorderMode border_mode, PixelValue constant_border_value=PixelValue{})
Initialise the function's sources, destination, interpolation policy and border mode.
void configure (ICLTensor *input, const ICLTensor *map_x, const ICLTensor *map_y, ICLTensor *output, InterpolationPolicy policy, BorderMode border_mode, PixelValue constant_border_value=PixelValue{})
Initialise the function's sources, destination, interpolation policy and border mode.
Public Member Functions inherited from ICLSimpleFunction
ICLSimpleFunction (CLRuntimeContext *ctx=nullptr)
Constructor.
ICLSimpleFunction (const ICLSimpleFunction &)=delete
Prevent instances of this class from being copied (As this class contains pointers)
ICLSimpleFunction (ICLSimpleFunction &&)=default
Default move constructor.
ICLSimpleFunction & operator= (const ICLSimpleFunction &)=delete
Prevent instances of this class from being copied (As this class contains pointers)
ICLSimpleFunction & operator= (ICLSimpleFunction &&)=default
Default move assignment operator.
~ICLSimpleFunction ()
Default destructor.
void run () override final
Run the kernels contained in the function.
Public Member Functions inherited from IFunction
virtual ~IFunction ()=default
Destructor.
virtual void prepare ()
Prepare the function for executing.
Static Public Member Functions
static Status validate (const ITensorInfo *input, const ITensorInfo *map_x, const ITensorInfo *map_y, const ITensorInfo *output, const InterpolationPolicy policy, const BorderMode border_mode, PixelValue constant_border_value=PixelValue{})
Checks if the kernel's input, output and border mode will lead to a valid configuration of CLRemap.
Detailed Description
Basic function to execute remap.
This function calls the following OpenCL kernels:
CLFillBorderKernel (executed if border_mode == CONSTANT or border_mode == REPLICATE)
CLRemapKernel
Definition at line 45 of file CLRemap.h.
Member Function Documentation
configure() [1/4]
void configure (const CLCompileContext & compile_context, ICLTensor * input, const ICLTensor * map_x, const ICLTensor * map_y, ICLTensor * output, InterpolationPolicy policy, BorderMode border_mode, uint8_t constant_border_value = 0)
Initialise the function's sources, destination, interpolation policy and border mode.
Valid data layouts:
All
Valid data type configurations:
src0 src1 src2 dst
U8 F32 F32 U8
F16 F32 F32 F16
Parameters
[in] compile_context The compile context to be used.
[in,out] input Source tensor. Data types supported: U8. (Written to only for border_mode != UNDEFINED)
[in] map_x Map for X coords. Data types supported: F32.
[in] map_y Map for Y coords. Data types supported: F32.
[out] output Output tensor. Data types supported: U8.
[in] policy Interpolation policy to use. Only NEAREST and BILINEAR are supported.
[in] border_mode Border mode to use on the input tensor. Only CONSTANT and UNDEFINED are supported.
[in] constant_border_value (Optional) Constant value to use for borders if border_mode is set to CONSTANT.
Deprecated:
This function is deprecated and is intended to be removed in 22.02 release
Definition at line 37 of file CLRemap.cpp.
Referenced by CLRemap::configure().
 {
     configure(compile_context, input, map_x, map_y, output, policy, border_mode, PixelValue{ constant_border_value });
 }
configure() [2/4]
void configure (ICLTensor * input, const ICLTensor * map_x, const ICLTensor * map_y, ICLTensor * output, InterpolationPolicy policy, BorderMode border_mode, uint8_t constant_border_value = 0)
Initialise the function's sources, destination, interpolation policy and border mode.
Similar to CLRemap::configure(const CLCompileContext &compile_context, ICLTensor *input, const ICLTensor *map_x, const ICLTensor *map_y, ICLTensor *output, InterpolationPolicy policy, BorderMode border_mode, uint8_t constant_border_value)
Deprecated:
This function is deprecated and is intended to be removed in 22.02 release
Definition at line 43 of file CLRemap.cpp.
References CLRemap::configure(), and CLKernelLibrary::get().
 {
     configure(CLKernelLibrary::get().get_compile_context(), input, map_x, map_y, output, policy, border_mode, PixelValue{ constant_border_value });
 }
configure() [3/4]
void configure (const CLCompileContext & compile_context, ICLTensor * input, const ICLTensor * map_x, const ICLTensor * map_y, ICLTensor * output, InterpolationPolicy policy, BorderMode border_mode, PixelValue constant_border_value = PixelValue{})
Initialise the function's sources, destination, interpolation policy and border mode.
Parameters
[in] compile_context The compile context to be used.
[in,out] input Source tensor. Data types supported: U8,(or F16 when layout is NHWC). (Written to only for border_mode != UNDEFINED)
[in] map_x Map for X coords. Data types supported: F32.
[in] map_y Map for Y coords. Data types supported: F32.
[out] output Output tensor. Data types supported: Same as input.
[in] policy Interpolation policy to use. Only NEAREST and BILINEAR are supported.
[in] border_mode Border mode to use on the input tensor. Only CONSTANT and UNDEFINED are supported.
[in] constant_border_value (Optional) Constant value to use for borders if border_mode is set to CONSTANT.
Definition at line 53 of file CLRemap.cpp.
References ARM_COMPUTE_LOG_PARAMS, and arm_compute::test::validation::k.
 {
     ARM_COMPUTE_LOG_PARAMS(input, map_x, map_y, output, policy, border_mode, constant_border_value);
     auto k = std::make_unique<CLRemapKernel>();
     k->configure(compile_context, input, map_x, map_y, output, RemapInfo{ policy, border_mode, constant_border_value });
     _kernel = std::move(k);
     _border_handler->configure(compile_context, input, _kernel->border_size(), border_mode, constant_border_value);
 }
configure() [4/4]
void configure (ICLTensor * input, const ICLTensor * map_x, const ICLTensor * map_y, ICLTensor * output, InterpolationPolicy policy, BorderMode border_mode, PixelValue constant_border_value = PixelValue{})
Initialise the function's sources, destination, interpolation policy and border mode.
Similar to CLRemap::configure(const CLCompileContext &compile_context, ICLTensor *input, const ICLTensor *map_x, const ICLTensor *map_y, ICLTensor *output, InterpolationPolicy policy, BorderMode border_mode, PixelValue constant_border_value)
Definition at line 48 of file CLRemap.cpp.
References CLRemap::configure(), and CLKernelLibrary::get().
 {
     configure(CLKernelLibrary::get().get_compile_context(), input, map_x, map_y, output, policy, border_mode, constant_border_value);
 }
validate()
Status validate (const ITensorInfo * input, const ITensorInfo * map_x, const ITensorInfo * map_y, const ITensorInfo * output, const InterpolationPolicy policy, const BorderMode border_mode, PixelValue constant_border_value = PixelValue{}) static
Checks if the kernel's input, output and border mode will lead to a valid configuration of CLRemap.
Similar to CLRemap::configure(const CLCompileContext &compile_context, ICLTensor *input, const ICLTensor *map_x, const ICLTensor *map_y, ICLTensor *output, InterpolationPolicy policy, BorderMode border_mode, PixelValue constant_border_value)
Returns
a Status
Definition at line 63 of file CLRemap.cpp.
References CLRemapKernel::validate().
Referenced by arm_compute::test::validation::DATA_TEST_CASE().
 {
     return CLRemapKernel::validate(input, map_x, map_y, output, RemapInfo{ policy, border_mode, constant_border_value });
 }
The documentation for this class was generated from the following files:
arm_compute/runtime/CL/functions/CLRemap.h
src/runtime/CL/functions/CLRemap.cpp