Compute Library: MemoryGroup Class Reference
MemoryGroup Class Reference final
Memory group.
#include <MemoryGroup.h>
Public Member Functions
MemoryGroup (std::shared_ptr< IMemoryManager >=nullptr) noexcept
Default Constructor.
~MemoryGroup ()=default
Default destructor.
MemoryGroup (const MemoryGroup &)=delete
Prevent instances of this class from being copied (As this class contains pointers)
MemoryGroup & operator= (const MemoryGroup &)=delete
Prevent instances of this class from being copy assigned (As this class contains pointers)
MemoryGroup (MemoryGroup &&)=default
Allow instances of this class to be moved.
MemoryGroup & operator= (MemoryGroup &&)=default
Allow instances of this class to be moved.
void manage (IMemoryManageable *obj) override
Sets a object to be managed by the given memory group.
void finalize_memory (IMemoryManageable *obj, IMemory &obj_memory, size_t size, size_t alignment) override
Finalizes memory for a given object.
void acquire () override
Acquires backing memory for the whole group.
void release () override
Releases backing memory of the whole group.
MemoryMappings & mappings () override
Gets the memory mapping of the group.
Public Member Functions inherited from IMemoryGroup
virtual ~IMemoryGroup ()=default
Default virtual destructor.
Detailed Description
Memory group.
Definition at line 43 of file MemoryGroup.h.
Constructor & Destructor Documentation
MemoryGroup() [1/3]
MemoryGroup (std::shared_ptr< IMemoryManager > memory_manager = nullptr) inline noexcept
Default Constructor.
Definition at line 72 of file MemoryGroup.h.
     : _memory_manager(memory_manager),
       _pool(nullptr),
       _mappings()
 {
 }
~MemoryGroup()
~MemoryGroup () default
Default destructor.
MemoryGroup() [2/3]
MemoryGroup (const MemoryGroup &) delete
Prevent instances of this class from being copied (As this class contains pointers)
MemoryGroup() [3/3]
MemoryGroup (MemoryGroup &&) default
Allow instances of this class to be moved.
Member Function Documentation
acquire()
void acquire () inline override virtual
Acquires backing memory for the whole group.
Implements IMemoryGroup.
Definition at line 105 of file MemoryGroup.h.
References ARM_COMPUTE_ERROR_ON.
Referenced by NEFFT2D::run().
 {
     if(!_mappings.empty())
     {
         ARM_COMPUTE_ERROR_ON(!_memory_manager->pool_manager());
         _pool = _memory_manager->pool_manager()->lock_pool();
         _pool->acquire(_mappings);
     }
 }
finalize_memory()
void finalize_memory (IMemoryManageable * obj, IMemory & obj_memory, size_t size, size_t alignment) inline override virtual
Finalizes memory for a given object.
Note
Manager must not be finalized
Parameters
[in,out] obj Object to request memory for
[in,out] obj_memory Object's memory handling interface which can be used to alter the underlying memory that is used by the object.
[in] size Size of memory to allocate
[in] alignment (Optional) Alignment to use
Implements IMemoryGroup.
Definition at line 96 of file MemoryGroup.h.
References ARM_COMPUTE_ERROR_ON.
 {
     if(_memory_manager)
     {
         ARM_COMPUTE_ERROR_ON(!_memory_manager->lifetime_manager());
         _memory_manager->lifetime_manager()->end_lifetime(obj, obj_memory, size, alignment);
     }
 }
manage()
void manage (IMemoryManageable * obj) inline override virtual
Sets a object to be managed by the given memory group.
Note
Manager must not be finalized
Parameters
[in] obj Object to be managed
Implements IMemoryGroup.
Definition at line 79 of file MemoryGroup.h.
References ARM_COMPUTE_ERROR_ON, and IMemoryManageable::associate_memory_group().
Referenced by CLQLSTMLayer::CLQLSTMLayer(), CPPBoxWithNonMaximaSuppressionLimit::configure(), CPPDetectionPostProcessLayer::configure(), NEFFT2D::configure(), NEReduceMean::configure(), NERNNLayer::configure(), CLReduceMean::configure(), NEL2NormalizeLayer::configure(), NEReductionOperation::configure(), NEFFT1D::configure(), NEInstanceNormalizationLayer::configure(), NEDetectionPostProcessLayer::configure(), NENormalizationLayer::configure(), CLFFT2D::configure(), CLRNNLayer::configure(), CLFFT1D::configure(), CLDepthwiseConvolutionLayer::configure(), CLL2NormalizeLayer::configure(), CLReductionOperation::configure(), CLArgMinMaxLayer::configure(), NEFFTConvolutionLayer::configure(), NEGenerateProposalsLayer::configure(), NELSTMLayerQuantized::configure(), NELSTMLayer::configure(), NEDeconvolutionLayer::configure(), CLFFTConvolutionLayer::configure(), CLGenerateProposalsLayer::configure(), CLGEMMDeconvolutionLayer::configure(), CLDirectDeconvolutionLayer::configure(), CLLSTMLayerQuantized::configure(), NEQLSTMLayer::configure(), CLLSTMLayer::configure(), CLQLSTMLayer::configure(), arm_compute::manage_workspace(), and NEQLSTMLayer::NEQLSTMLayer().
 {
     if(_memory_manager && (obj != nullptr))
     {
         ARM_COMPUTE_ERROR_ON(!_memory_manager->lifetime_manager());
         // Defer registration to the first managed object
         _memory_manager->lifetime_manager()->register_group(this);
         // Associate this memory group with the tensor
         obj->associate_memory_group(this);
         // Start object lifetime
         _memory_manager->lifetime_manager()->start_lifetime(obj);
     }
 }
mappings()
MemoryMappings & mappings () inline override virtual
Gets the memory mapping of the group.
Implements IMemoryGroup.
Definition at line 127 of file MemoryGroup.h.
 {
     return _mappings;
 }
operator=() [1/2]
MemoryGroup& operator= (const MemoryGroup &) delete
Prevent instances of this class from being copy assigned (As this class contains pointers)
operator=() [2/2]
MemoryGroup& operator= (MemoryGroup &&) default
Allow instances of this class to be moved.
release()
void release () inline override virtual
Releases backing memory of the whole group.
Implements IMemoryGroup.
Definition at line 115 of file MemoryGroup.h.
References ARM_COMPUTE_ERROR_ON, and IMemoryPool::release().
Referenced by NEFFT2D::run().
 {
     if(_pool != nullptr)
     {
         ARM_COMPUTE_ERROR_ON(!_memory_manager->pool_manager());
         ARM_COMPUTE_ERROR_ON(_mappings.empty());
         _pool->release(_mappings);
         _memory_manager->pool_manager()->unlock_pool(_pool);
         _pool = nullptr;
     }
 }
The documentation for this class was generated from the following file:
arm_compute/runtime/MemoryGroup.h