Compute Library: CLBitwiseKernel Class Reference
CLBitwiseKernel Class Reference
Interface for the bitwise operation kernel.
#include <CLBitwiseKernel.h>
Public Member Functions
CLBitwiseKernel ()
Default constructor.
CLBitwiseKernel (const CLBitwiseKernel &)=delete
Prevent instances of this class from being copied (As this class contains pointers)
CLBitwiseKernel & operator= (const CLBitwiseKernel &)=delete
Prevent instances of this class from being copied (As this class contains pointers)
CLBitwiseKernel (CLBitwiseKernel &&)=default
Allow instances of this class to be moved.
CLBitwiseKernel & operator= (CLBitwiseKernel &&)=default
Allow instances of this class to be moved.
void configure (const CLCompileContext &compile_context, const ICLTensor *input1, const ICLTensor *input2, ICLTensor *output, BitwiseOperation op)
Set the inputs and output tensors.
void run (const Window &window, cl::CommandQueue &queue) override
Enqueue the OpenCL kernel to process the given window on the passed OpenCL command queue.
Public Member Functions inherited from ICLKernel
ICLKernel ()
Constructor.
cl::Kernel & kernel ()
Returns a reference to the OpenCL kernel of this object.
CLKernelType type () const
Returns the CL kernel type.
template<typename T >
void add_1D_array_argument (unsigned int &idx, const ICLArray< T > *array, const Strides &strides, unsigned int num_dimensions, const Window &window)
Add the passed 1D array's parameters to the object's kernel's arguments starting from the index idx.
void add_1D_tensor_argument (unsigned int &idx, const ICLTensor *tensor, const Window &window)
Add the passed 1D tensor's parameters to the object's kernel's arguments starting from the index idx.
void add_1D_tensor_argument_if (bool cond, unsigned int &idx, const ICLTensor *tensor, const Window &window)
Add the passed 1D tensor's parameters to the object's kernel's arguments starting from the index idx if the condition is true.
void add_2D_tensor_argument (unsigned int &idx, const ICLTensor *tensor, const Window &window)
Add the passed 2D tensor's parameters to the object's kernel's arguments starting from the index idx.
void add_2D_tensor_argument_if (bool cond, unsigned int &idx, const ICLTensor *tensor, const Window &window)
Add the passed 2D tensor's parameters to the object's kernel's arguments starting from the index idx if the condition is true.
void add_3D_tensor_argument (unsigned int &idx, const ICLTensor *tensor, const Window &window)
Add the passed 3D tensor's parameters to the object's kernel's arguments starting from the index idx.
void add_4D_tensor_argument (unsigned int &idx, const ICLTensor *tensor, const Window &window)
Add the passed 4D tensor's parameters to the object's kernel's arguments starting from the index idx.
virtual void run_op (ITensorPack &tensors, const Window &window, cl::CommandQueue &queue)
Enqueue the OpenCL kernel to process the given window on the passed OpenCL command queue.
template<typename T >
void add_argument (unsigned int &idx, T value)
Add the passed parameters to the object's kernel's arguments starting from the index idx.
void set_lws_hint (const cl::NDRange &lws_hint)
Set the Local-Workgroup-Size hint.
cl::NDRange lws_hint () const
Return the Local-Workgroup-Size hint.
void set_wbsm_hint (const cl_int &wbsm_hint)
Set the workgroup batch size modifier hint.
cl_int wbsm_hint () const
Return the workgroup batch size modifier hint.
const std::string & config_id () const
Get the configuration ID.
void set_target (GPUTarget target)
Set the targeted GPU architecture.
void set_target (cl::Device &device)
Set the targeted GPU architecture according to the CL device.
GPUTarget get_target () const
Get the targeted GPU architecture.
size_t get_max_workgroup_size ()
Get the maximum workgroup size for the device the CLKernelLibrary uses.
template<unsigned int dimension_size>
void add_tensor_argument (unsigned &idx, const ICLTensor *tensor, const Window &window)
template<typename T , unsigned int dimension_size>
void add_array_argument (unsigned &idx, const ICLArray< T > *array, const Strides &strides, unsigned int num_dimensions, const Window &window)
Add the passed array's parameters to the object's kernel's arguments starting from the index idx.
Public Member Functions inherited from IKernel
IKernel ()
Constructor.
virtual ~IKernel ()=default
Destructor.
virtual bool is_parallelisable () const
Indicates whether or not the kernel is parallelisable.
virtual BorderSize border_size () const
The size of the border for that kernel.
const Window & window () const
The maximum window the kernel can be executed on.
bool is_window_configured () const
Function to check if the embedded window of this kernel has been configured.
Additional Inherited Members
Static Public Member Functions inherited from ICLKernel
static constexpr unsigned int num_arguments_per_1D_array ()
Returns the number of arguments enqueued per 1D array object.
static constexpr unsigned int num_arguments_per_1D_tensor ()
Returns the number of arguments enqueued per 1D tensor object.
static constexpr unsigned int num_arguments_per_2D_tensor ()
Returns the number of arguments enqueued per 2D tensor object.
static constexpr unsigned int num_arguments_per_3D_tensor ()
Returns the number of arguments enqueued per 3D tensor object.
static constexpr unsigned int num_arguments_per_4D_tensor ()
Returns the number of arguments enqueued per 4D tensor object.
static cl::NDRange gws_from_window (const Window &window)
Get the global work size given an execution window.
Detailed Description
Interface for the bitwise operation kernel.
Result depends on the BitwiseOperation and is computed by: AND operation:
\[ output(x,y) = input1(x,y) \land input2(x,y) \]
NOT operation:
\[ output(x,y) = \lnot input1(x,y) \]
OR operation:
\[ output(x,y) = input1(x,y) \lor input2(x,y) \]
XOR operation:
\[ output(x,y) = input1(x,y) \oplus input2(x,y) \]
Definition at line 41 of file CLBitwiseKernel.h.
Constructor & Destructor Documentation
CLBitwiseKernel() [1/3]
CLBitwiseKernel ()
Default constructor.
Definition at line 37 of file CLBitwiseKernel.cpp.
References arm_compute::ELEMENTWISE.
     : _input1(nullptr), _input2(nullptr), _output(nullptr)
 {
     _type = CLKernelType::ELEMENTWISE;
 }
CLBitwiseKernel() [2/3]
CLBitwiseKernel (const CLBitwiseKernel &) delete
Prevent instances of this class from being copied (As this class contains pointers)
CLBitwiseKernel() [3/3]
CLBitwiseKernel (CLBitwiseKernel &&) default
Allow instances of this class to be moved.
Member Function Documentation
configure()
void configure (const CLCompileContext & compile_context, const ICLTensor * input1, const ICLTensor * input2, ICLTensor * output, BitwiseOperation op)
Set the inputs and output tensors.
Parameters
[in] compile_context The compile context to be used.
[in] input1 Source tensor. Data types supported: U8.
[in] input2 Source tensor. Data types supported: U8.
[out] output Destination tensor. Data types supported: U8.
[in] op Bitwise operation to perform. Supported: AND, OR, NOT, XOR.
Definition at line 43 of file CLBitwiseKernel.cpp.
References CLBuildOptions::add_option(), arm_compute::adjust_vec_size(), arm_compute::AND, ARM_COMPUTE_ERROR, ARM_COMPUTE_ERROR_ON, ARM_COMPUTE_ERROR_ON_DATA_TYPE_CHANNEL_NOT_IN, ARM_COMPUTE_ERROR_ON_NULLPTR, arm_compute::auto_init_if_empty(), arm_compute::calculate_max_window(), arm_compute::create_kernel(), ITensorInfo::dimension(), ITensorInfo::element_size(), arm_compute::get_padding_info(), arm_compute::has_padding_changed(), ITensor::info(), kernel_name, arm_compute::NOT, CLBuildOptions::options(), arm_compute::OR, arm_compute::support::cpp11::to_string(), arm_compute::U8, and arm_compute::XOR.
 {
     ARM_COMPUTE_ERROR_ON_NULLPTR(input1);
     ARM_COMPUTE_ERROR_ON_DATA_TYPE_CHANNEL_NOT_IN(input1, 1, DataType::U8);
     if(op != BitwiseOperation::NOT)
     {
         ARM_COMPUTE_ERROR_ON_NULLPTR(input2);
         ARM_COMPUTE_ERROR_ON_DATA_TYPE_CHANNEL_NOT_IN(input2, 1, DataType::U8);
     }
     ARM_COMPUTE_ERROR_ON_NULLPTR(output);
     ARM_COMPUTE_ERROR_ON_DATA_TYPE_CHANNEL_NOT_IN(output, 1, DataType::U8);
     // Output auto inizialitation if not yet initialized
     auto_init_if_empty(*(output->info()), *(input1->info()));
     auto padding_info = get_padding_info({ input1, input2, output });
     // Configure kernel window
     const unsigned int vec_size_x = adjust_vec_size(16 / output->info()->element_size(), output->info()->dimension(0));
     Window             win        = calculate_max_window(*output->info(), Steps(vec_size_x));
     _input1 = input1;
     _input2 = input2;
     _output = output;
     // Create kernel
     std::string kernel_name = "";
     switch(op)
     {
         case BitwiseOperation::AND:
             kernel_name = "bitwise_and";
             break;
         case BitwiseOperation::NOT:
             kernel_name = "bitwise_not";
             break;
         case BitwiseOperation::OR:
             kernel_name = "bitwise_or";
             break;
         case BitwiseOperation::XOR:
             kernel_name = "bitwise_xor";
             break;
         default:
             ARM_COMPUTE_ERROR("Bitwise operation not supported");
     }
     CLBuildOptions build_opts;
     const int      vec_size_x_leftovers = output->info()->dimension(0) % vec_size_x;
     build_opts.add_option("-DVEC_SIZE=" + support::cpp11::to_string(vec_size_x));
     build_opts.add_option("-DVEC_SIZE_LEFTOVER=" + support::cpp11::to_string(vec_size_x_leftovers));
     _kernel = create_kernel(compile_context, kernel_name, build_opts.options());
     ICLKernel::configure_internal(win);
     ARM_COMPUTE_ERROR_ON(has_padding_changed(padding_info));
 }
operator=() [1/2]
CLBitwiseKernel& operator= (const CLBitwiseKernel &) delete
Prevent instances of this class from being copied (As this class contains pointers)
operator=() [2/2]
CLBitwiseKernel& operator= (CLBitwiseKernel &&) default
Allow instances of this class to be moved.
run()
void run (const Window & window, cl::CommandQueue & queue) override virtual
Enqueue the OpenCL kernel to process the given window on the passed OpenCL command queue.
Note
The queue is not flushed by this method, and therefore the kernel will not have been executed by the time this method returns.
Parameters
[in] window Region on which to execute the kernel. (Must be a valid region of the window returned by window()).
[in,out] queue Command queue on which to enqueue the kernel.
Reimplemented from ICLKernel.
Definition at line 97 of file CLBitwiseKernel.cpp.
References ICLKernel::add_2D_tensor_argument(), ARM_COMPUTE_ERROR_ON_INVALID_SUBWINDOW, ARM_COMPUTE_ERROR_ON_UNCONFIGURED_KERNEL, arm_compute::enqueue(), Window::first_slice_window_2D(), ICLKernel::lws_hint(), arm_compute::test::validation::reference::slice(), Window::slide_window_slice_2D(), and IKernel::window().
 {
     ARM_COMPUTE_ERROR_ON_UNCONFIGURED_KERNEL(this);
     ARM_COMPUTE_ERROR_ON_INVALID_SUBWINDOW(ICLKernel::window(), window);
     Window slice = window.first_slice_window_2D();
     do
     {
         unsigned int idx = 0;
         add_2D_tensor_argument(idx, _input1, slice);
         if(_input2 != nullptr)
         {
             add_2D_tensor_argument(idx, _input2, slice);
         }
         add_2D_tensor_argument(idx, _output, slice);
         enqueue(queue, *this, slice, lws_hint());
     }
     while(window.slide_window_slice_2D(slice));
 }
The documentation for this class was generated from the following files:
src/core/CL/kernels/CLBitwiseKernel.h
src/core/CL/kernels/CLBitwiseKernel.cpp