Compute Library: CpuWinogradConv2dTransformWeightsKernel< T, OutputTileRows, OutputTileCols, KernelRows, KernelCols > Class Template Reference
CpuWinogradConv2dTransformWeightsKernel< T, OutputTileRows, OutputTileCols, KernelRows, KernelCols > Class Template Reference final
Kernel to perform Winograd weights transform.
#include <CpuWinogradConv2dKernel.h>
Public Member Functions
CpuWinogradConv2dTransformWeightsKernel (const CpuWinogradConv2dTransformWeightsKernel &)=delete
Prevent instances of this class from being copied (As this class contains pointers)
CpuWinogradConv2dTransformWeightsKernel & operator= (const CpuWinogradConv2dTransformWeightsKernel &)=delete
Prevent instances of this class from being copied (As this class contains pointers)
CpuWinogradConv2dTransformWeightsKernel (CpuWinogradConv2dTransformWeightsKernel &&)=default
Allow instances of this class to be moved.
CpuWinogradConv2dTransformWeightsKernel & operator= (CpuWinogradConv2dTransformWeightsKernel &&)=default
Allow instances of this class to be moved.
~CpuWinogradConv2dTransformWeightsKernel ()=default
Default destructor.
CpuWinogradConv2dTransformWeightsKernel ()
Default constructor.
const char * name () const override
Name of the kernel.
unsigned int get_weight_storage_size (int num_output_channels, int num_input_channels) const override
Determine how much memory (in units of T) to allocate for the transformed weights.
int get_matrix_stride (int num_output_channels, int num_input_channels) const override
Gets the stride between matrices in the input worspace.
void run_op (ITensorPack &tensors, const Window &window, const ThreadInfo &info) override
Execute the kernel on the passed window.
bool is_parallelisable () const override
Indicates whether or not the kernel is parallelisable.
Public Member Functions inherited from ICpuWinogradConv2dTransformWeightsKernel
ICpuWinogradConv2dTransformWeightsKernel (const ICpuWinogradConv2dTransformWeightsKernel &)=default
Prevent instances of this class from being copied (As this class contains pointers)
ICpuWinogradConv2dTransformWeightsKernel & operator= (const ICpuWinogradConv2dTransformWeightsKernel &)=default
Prevent instances of this class from being copied (As this class contains pointers)
ICpuWinogradConv2dTransformWeightsKernel (ICpuWinogradConv2dTransformWeightsKernel &&)=default
Allow instances of this class to be moved.
ICpuWinogradConv2dTransformWeightsKernel & operator= (ICpuWinogradConv2dTransformWeightsKernel &&)=default
Allow instances of this class to be moved.
ICpuWinogradConv2dTransformWeightsKernel ()
virtual ~ICpuWinogradConv2dTransformWeightsKernel ()
virtual void configure (const ITensorInfo *weights_hwio, ITensorInfo *output, const int matrix_stride, const int num_output_channels, const int num_input_channels)=0
Configure the weights transform kernel.
Public Member Functions inherited from ICPPKernel
virtual ~ICPPKernel ()=default
Default destructor.
virtual void run (const Window &window, const ThreadInfo &info)
Execute the kernel on the passed window.
virtual void run_nd (const Window &window, const ThreadInfo &info, const Window &thread_locator)
legacy compatibility layer for implemantions which do not support thread_locator In these cases we simply narrow the interface down the legacy version
virtual size_t get_mws (const CPUInfo &platform, size_t thread_count) const
Return minimum workload size of the relevant kernel.
Public Member Functions inherited from IKernel
IKernel ()
Constructor.
virtual ~IKernel ()=default
Destructor.
virtual BorderSize border_size () const
The size of the border for that kernel.
const Window & window () const
The maximum window the kernel can be executed on.
bool is_window_configured () const
Function to check if the embedded window of this kernel has been configured.
Static Public Member Functions
static Status validate (const ITensorInfo *input, const ITensorInfo *output, const WinogradInfo &winograd_info)
Static function to check if given info will lead to a valid configuration of CpuWinogradConv2dTransformWeightsKernel.
Static Public Member Functions inherited from ICpuWinogradConv2dTransformWeightsKernel
static Status validate (const ITensorInfo *input, const ITensorInfo *weights)
Static function to check if given info will lead to a valid configuration of CpuWinogradConv2dTransformWeightsKernel.
Additional Inherited Members
Static Public Attributes inherited from ICPPKernel
static constexpr size_t default_mws = 128
static constexpr size_t small_network_mws = 256
Detailed Description
template<typename T, int OutputTileRows, int OutputTileCols, int KernelRows, int KernelCols>
class arm_compute::cpu::CpuWinogradConv2dTransformWeightsKernel< T, OutputTileRows, OutputTileCols, KernelRows, KernelCols >
Kernel to perform Winograd weights transform.
Definition at line 480 of file CpuWinogradConv2dKernel.h.
Constructor & Destructor Documentation
CpuWinogradConv2dTransformWeightsKernel() [1/3]
CpuWinogradConv2dTransformWeightsKernel (const CpuWinogradConv2dTransformWeightsKernel< T, OutputTileRows, OutputTileCols, KernelRows, KernelCols > &) delete
Prevent instances of this class from being copied (As this class contains pointers)
CpuWinogradConv2dTransformWeightsKernel() [2/3]
CpuWinogradConv2dTransformWeightsKernel (CpuWinogradConv2dTransformWeightsKernel< T, OutputTileRows, OutputTileCols, KernelRows, KernelCols > &&) default
Allow instances of this class to be moved.
~CpuWinogradConv2dTransformWeightsKernel()
~CpuWinogradConv2dTransformWeightsKernel () default
Default destructor.
CpuWinogradConv2dTransformWeightsKernel() [3/3]
CpuWinogradConv2dTransformWeightsKernel ()
Default constructor.
Definition at line 202 of file CpuWinogradConv2dKernel.cpp.
     : _transform(nullptr), _num_output_channels(0), _matrix_stride(0)
 {
 }
Member Function Documentation
get_matrix_stride()
int get_matrix_stride (int num_output_channels, int num_input_channels) const override virtual
Gets the stride between matrices in the input worspace.
Parameters
[in] num_output_channels Number of output feature maps.
[in] num_input_channels Number of input feature maps.
Returns
Stride expressed in bytes.
Implements ICpuWinogradConv2dTransformWeightsKernel.
Definition at line 208 of file CpuWinogradConv2dKernel.cpp.
References ARM_COMPUTE_UNUSED, ICpuWinogradConv2dTransformWeightsKernel::configure(), Window::DimX, and Window::set().
 {
     return WinogradConv::get_kernel_matrix_stride(num_input_channels, num_output_channels);
 }
get_weight_storage_size()
unsigned int get_weight_storage_size (int num_output_channels, int num_input_channels) const override virtual
Determine how much memory (in units of T) to allocate for the transformed weights.
Parameters
[in] num_output_channels Number of output feature maps.
[in] num_input_channels Number of input feature maps.
Returns
Storage size (in units of T) required.
Implements ICpuWinogradConv2dTransformWeightsKernel.
Definition at line 194 of file CpuWinogradConv2dKernel.cpp.
References arm_compute::test::validation::shape.
 {
     const KernelShape shape(num_output_channels, KernelRows, KernelCols, num_input_channels);
     // WinogradConv returns the size in bytes, we divide by `sizeof(T)` to express that in units of T
     return static_cast<unsigned int>(WinogradConv::get_kernel_storage_size(num_input_channels, num_output_channels) / sizeof(T));
 }
is_parallelisable()
bool is_parallelisable () const override virtual
Indicates whether or not the kernel is parallelisable.
If the kernel is parallelisable then the window returned by window() can be split into sub-windows which can then be run in parallel.
If the kernel is not parallelisable then only the window returned by window() can be passed to run()
Returns
True if the kernel is parallelisable
Reimplemented from IKernel.
Definition at line 257 of file CpuWinogradConv2dKernel.cpp.
 {
     return false;
 }
name()
const char* name () const inline override virtual
Name of the kernel.
Returns
Kernel name
Implements ICPPKernel.
Definition at line 496 of file CpuWinogradConv2dKernel.h.
References ICpuWinogradConv2dTransformInputKernel::configure(), ICpuWinogradConv2dTransformInputKernel::get_matrix_stride(), arm_compute::test::validation::info, arm_compute::test::validation::input, IKernel::is_parallelisable(), ICPPKernel::run_op(), arm_compute::validate(), and IKernel::window().
     {
         return "CpuWinogradConv2dTransformWeightsKernel";
     }
operator=() [1/2]
CpuWinogradConv2dTransformWeightsKernel& operator= (const CpuWinogradConv2dTransformWeightsKernel< T, OutputTileRows, OutputTileCols, KernelRows, KernelCols > &) delete
Prevent instances of this class from being copied (As this class contains pointers)
operator=() [2/2]
CpuWinogradConv2dTransformWeightsKernel& operator= (CpuWinogradConv2dTransformWeightsKernel< T, OutputTileRows, OutputTileCols, KernelRows, KernelCols > &&) default
Allow instances of this class to be moved.
run_op()
void run_op (ITensorPack & tensors, const Window & window, const ThreadInfo & info) override virtual
Execute the kernel on the passed window.
Warning
If is_parallelisable() returns false then the passed window must be equal to window()
Note
The window has to be a region within the window returned by the window() method
The width of the window has to be a multiple of num_elems_processed_per_iteration().
Parameters
[in] tensors A vector containing the tensors to operate on.
[in] window Region on which to execute the kernel. (Must be a region of the window returned by window())
[in] info Info about executing thread and CPU.
Reimplemented from ICPPKernel.
Definition at line 236 of file CpuWinogradConv2dKernel.cpp.
References arm_compute::ACL_DST, arm_compute::ACL_SRC, ARM_COMPUTE_ERROR_ON, ARM_COMPUTE_ERROR_ON_UNCONFIGURED_KERNEL, ARM_COMPUTE_UNUSED, ITensor::buffer(), ITensorPack::empty(), Window::Dimension::end(), ITensorPack::get_const_tensor(), ITensorPack::get_tensor(), arm_gemm::roundup(), Window::Dimension::start(), and Window::x().
 {
     ARM_COMPUTE_UNUSED(info);
     ARM_COMPUTE_ERROR_ON_UNCONFIGURED_KERNEL(this);
     ARM_COMPUTE_ERROR_ON(tensors.empty());
     const size_t fst = window.x().start();
     const size_t lst = window.x().end();
     const ITensor *weights_hwio = tensors.get_const_tensor(TensorType::ACL_SRC);
     ITensor       *output       = tensors.get_tensor(TensorType::ACL_DST);
     _transform->set_weight_tensor(weights_hwio->buffer());
     const int matrix_row_stride = roundup(_num_output_channels, WinogradConv::N_BLOCK);
     _transform->set_output_matrices(output->buffer(), _matrix_stride, matrix_row_stride);
     _transform->set_working_space(output->buffer());
     _transform->run(fst, lst);
 }
validate()
Status validate (const ITensorInfo * input, const ITensorInfo * output, const WinogradInfo & winograd_info) static
Static function to check if given info will lead to a valid configuration of CpuWinogradConv2dTransformWeightsKernel.
Parameters
[in] input Source tensor info. The input is a 4D tensor with dimensions [kernel_x, kernel_y, IFM, OFM] (NCHW data layout). kernel_x must be 3 and equal to kernel_y. Data types supported: F16/F32.
[in] output Destination tensor info. The output is a 3D tensor with dimensions [OFM, IFM, 16] or [OFM, IFM, 36]. Data type supported: same as input
[in] winograd_info Contains Winograd's information described in WinogradInfo
Returns
a status
Definition at line 263 of file CpuWinogradConv2dKernel.cpp.
References ARM_COMPUTE_RETURN_ON_ERROR, and ICloneable< T >::clone().
 {
     ARM_COMPUTE_RETURN_ON_ERROR(validate_arguments_winograd_weight_trans(input, output, winograd_info));
     ARM_COMPUTE_RETURN_ON_ERROR(validate_and_configure_window_winograd_weight_trans(input->clone().get(), output->clone().get(), winograd_info).first);
     return Status{};
 }
The documentation for this class was generated from the following files:
src/cpu/kernels/CpuWinogradConv2dKernel.h
src/cpu/kernels/CpuWinogradConv2dKernel.cpp