Compute Library: arm_compute::utility Namespace Reference
arm_compute::utility Namespace Reference
Namespaces
detail
Functions
template<std::size_t N, typename Iterator >
std::array< typename std::iterator_traits< Iterator >::value_type, N > make_array (Iterator first, Iterator last)
template<typename DataType , typename RangeType = DataType>
DataType clamp (const DataType &n, const DataType &lower=std::numeric_limits< RangeType >::lowest(), const DataType &upper=std::numeric_limits< RangeType >::max())
Performs clamping among a lower and upper value.
template<typename F >
void for_each (F &&)
Base case of for_each.
template<typename F , typename T , typename... Ts>
void for_each (F &&func, T &&arg, Ts &&... args)
Call the function for each of the arguments.
template<typename F , typename T >
T && foldl (F &&, T &&value)
Base case of foldl.
template<typename F , typename T , typename U , typename... Us>
auto foldl (F &&func, T &&initial, U &&value, Us &&... values) -> decltype(func(std::forward< T >(initial), std::forward< U >(value)))
Fold left.
template<typename T >
std::vector< size_t > sort_indices (const std::vector< T > &v)
Perform an index sort of a given vector.
bool endswith (const std::string &str, const std::string &suffix)
Checks if a string contains a given suffix.
bool check_aligned (void *ptr, const size_t alignment)
Checks if a pointer complies with a given alignment.
std::string tolower (std::string string)
Convert string to lower case.
std::string getenv (const std::string &env_name)
Get environment variable as a string.
Function Documentation
check_aligned()
bool arm_compute::utility::check_aligned (void * ptr, const size_t alignment) inline
Checks if a pointer complies with a given alignment.
Parameters
[in] ptr Pointer to check
[in] alignment Alignment value
Returns
True if the pointer is aligned else false
Definition at line 194 of file Utility.h.
Referenced by TensorAllocator::import_memory(), and arm_compute::test::validation::TEST_CASE().
 {
     return (reinterpret_cast<std::uintptr_t>(ptr) % alignment) == 0;
 }
clamp()
DataType arm_compute::utility::clamp (const DataType & n, const DataType & lower = std::numeric_limits<RangeType>::lowest(), const DataType & upper = std::numeric_limits<RangeType>::max()) inline
Performs clamping among a lower and upper value.
Parameters
[in] n Value to clamp.
[in] lower Lower threshold.
[in] upper Upper threshold.
Returns
Clamped value.
Definition at line 101 of file Utility.h.
Referenced by calculate_avg_scale(), arm_compute::helpers::tensor_transform::calculate_end_on_index(), arm_compute::helpers::tensor_transform::calculate_start_on_index(), clamp_to_border_with_size(), arm_compute::compute_region_coordinate(), pooling_layer_2_nchw_indices(), arm_compute::test::validation::reference::roi_align_layer(), roi_pooling_layer(), scale_bilinear_nchw(), scale_bilinear_nhwc(), scale_nearest_neighbour_nchw(), and scale_nearest_neighbour_nhwc().
 {
     return std::max(lower, std::min(n, upper));
 }
endswith()
bool arm_compute::utility::endswith (const std::string & str, const std::string & suffix) inline
Checks if a string contains a given suffix.
Parameters
[in] str Input string
[in] suffix Suffix to check for
Returns
True if the string ends with the given suffix else false
Definition at line 178 of file Utility.h.
Referenced by arm_compute::graph_utils::get_input_accessor().
 {
     if(str.size() < suffix.size())
     {
         return false;
     }
     return std::equal(suffix.rbegin(), suffix.rend(), str.rbegin());
 }
foldl() [1/2]
T&& arm_compute::utility::foldl (F && , T && value) inline
Base case of foldl.
Returns
value.
Definition at line 132 of file Utility.h.
References arm_compute::utils::cast::U.
Referenced by foldl(), and arm_compute::intersect_valid_regions().
 {
     return std::forward<T>(value);
 }
foldl() [2/2]
auto arm_compute::utility::foldl (F && func, T && initial, U && value, Us &&... values) -> decltype(func(std::forward<T>(initial), std::forward<U>(value))) inline
Fold left.
Parameters
[in] func Function to be called
[in] initial Initial value
[in] value Argument passed to the function
[in] values Remaining arguments
Definition at line 145 of file Utility.h.
References foldl().
 {
     return foldl(std::forward<F>(func), func(std::forward<T>(initial), std::forward<U>(value)), std::forward<Us>(values)...);
 }
for_each() [1/2]
void arm_compute::utility::for_each (F &&) inline
Base case of for_each.
Does nothing.
Definition at line 110 of file Utility.h.
Referenced by TensorShape::broadcast_shape(), ITensorInfo::broadcast_shape_and_valid_region(), arm_compute::graph::detail::call_all_input_node_accessors(), arm_compute::graph::detail::call_all_output_node_accessors(), ConcatLayer::ConcatLayer(), for_each(), OffsetLifetimeManager::mapping_type(), GroupedConvolutionMutator::mutate(), Framework::print_test_info(), StackLayer::StackLayer(), SchedulerClock< output_timestamps >::test_start(), SchedulerClock< output_timestamps >::test_stop(), and arm_compute::update_window_and_padding().
 {
 }
for_each() [2/2]
void arm_compute::utility::for_each (F && func, T && arg, Ts &&... args) inline
Call the function for each of the arguments.
Parameters
[in] func Function to be called
[in] arg Argument passed to the function
[in] args Remaining arguments
Definition at line 121 of file Utility.h.
References GemmTuner::args, and for_each().
 {
     func(std::forward<T>(arg));
     for_each(std::forward<F>(func), std::forward<Ts>(args)...);
 }
getenv()
std::string arm_compute::utility::getenv (const std::string & env_name) inline
Get environment variable as a string.
Note
Return empty string on bare-metal
Parameters
[in] env_name Name of the Environment variable to retrieve
Returns
Environment variable content, or empty string if the variable is undefined or on bare-metal
Definition at line 222 of file Utility.h.
References ARM_COMPUTE_UNUSED.
 {
 #ifdef BARE_METAL
     ARM_COMPUTE_UNUSED(env_name);
     return std::string{};
 #else  // BARE_METAL
     const auto env_chr = std::getenv(env_name.c_str());
     return env_chr == nullptr ? std::string{} : std::string{ env_chr };
 #endif // BARE_METAL
 }
make_array()
std::array<typename std::iterator_traits<Iterator>::value_type, N> arm_compute::utility::make_array (Iterator first, Iterator last)
Definition at line 86 of file Utility.h.
References ARM_COMPUTE_UNUSED, and arm_compute::utility::detail::make_array().
 {
     ARM_COMPUTE_UNUSED(last);
     return detail::make_array(first, index_sequence_t<N> {});
 }
sort_indices()
std::vector<size_t> arm_compute::utility::sort_indices (const std::vector< T > & v)
Perform an index sort of a given vector.
Parameters
[in] v Vector to sort
Returns
Sorted index vector.
Definition at line 157 of file Utility.h.
Referenced by InstrumentsStats::InstrumentsStats().
 {
     std::vector<size_t> idx(v.size());
     std::iota(idx.begin(), idx.end(), 0);
     std::sort(idx.begin(), idx.end(),
               [&v](size_t i1, size_t i2)
     {
         return v[i1] < v[i2];
     });
     return idx;
 }
tolower()
std::string arm_compute::utility::tolower (std::string string) inline
Convert string to lower case.
Parameters
[in] string To be converted string.
Returns
Lower case string.
Definition at line 205 of file Utility.h.
References arm_compute::mlgo::parser::end().
Referenced by HeuristicTree::add_branch(), ClScaleKernel::configure(), arm_compute::graph::Convolution_method_from_name(), arm_compute::data_layout_from_name(), arm_compute::data_type_from_name(), arm_compute::graph::depthwise_convolution_method_from_name(), arm_compute::lower_string(), arm_compute::utils::operator>>(), CommandLineParser::parse(), arm_compute::graph::target_from_name(), and arm_compute::tuner_mode_from_name().
 {
     std::transform(string.begin(), string.end(), string.begin(), [](unsigned char c)
     {
         return std::tolower(c);
     });
     return string;
 }