Compute Library: arm_compute::softmax_helpers Namespace Reference
arm_compute::softmax_helpers Namespace Reference
Functions
PermutationVector get_permutation_vector_from_softmax_axis (size_t axis)
Given a softmax axis, this function returns the permutation vector required to put the axis to the front.
Function Documentation
get_permutation_vector_from_softmax_axis()
PermutationVector get_permutation_vector_from_softmax_axis (size_t axis)
Given a softmax axis, this function returns the permutation vector required to put the axis to the front.
Note
This function assumes a tensor rank <= 4
Axis selects the dimension on which softmax is performed. E.g. For input of shape 4x5x6 and axis=1, softmax will be applied to 4x6=24 vectors of size 5. Interally softmax kernels is always performed on the first dimension (front dimension), therefore permutation is required to put the dimension specified by axis to the first dimension.
Parameters
[in] axis Axis on which to perform softmax. Supported: 1, 2, 3 (0 implies no permutation needed)
Returns
the permutation vector
Definition at line 30 of file SoftmaxHelpers.cpp.
References ARM_COMPUTE_ERROR, and arm_compute::utils::cast::U.
Referenced by ClSoftmax::configure(), CpuSoftmaxGeneric< IS_LOG >::configure(), ClSoftmax::validate(), and CpuSoftmaxGeneric< IS_LOG >::validate().
 {
     switch(axis)
     {
         case 1:
             return PermutationVector(1U, 0U, 2U, 3U);
         case 2:
             return PermutationVector(2U, 1U, 0U, 3U);
         case 3:
             return PermutationVector(3U, 1U, 2U, 0U);
         default:
             ARM_COMPUTE_ERROR("Axis not supported");
     }
 }