Compute Library: DepthwiseImplementation< TInput, TWeight, TOutput, OutputStage > Struct Template Reference
DepthwiseImplementation< TInput, TWeight, TOutput, OutputStage > Struct Template Reference
#include <depthwise_implementation.hpp>
Public Member Functions
bool get_is_supported (const DepthwiseArgs &args, const OutputStage &os) const
uint64_t get_cycle_estimate (const DepthwiseArgs &args, const OutputStage &os) const
DepthwiseCommon< TInput, TWeight, TOutput > * get_instance (const DepthwiseArgs &args, const OutputStage &os) const
Data Fields
const DepthwiseMethod method
const char * name
std::function< bool(const DepthwiseArgs &, const OutputStage &)> is_supported
std::function< uint64_t(const DepthwiseArgs &, const OutputStage &)> cycle_estimate
std::function< DepthwiseCommon< TInput, TWeight, TOutput > *(const DepthwiseArgs &, const OutputStage &)> initialise
Detailed Description
template<typename TInput, typename TWeight = TInput, typename TOutput = TInput, class OutputStage = Nothing>
struct arm_conv::depthwise::DepthwiseImplementation< TInput, TWeight, TOutput, OutputStage >
Definition at line 38 of file depthwise_implementation.hpp.
Member Function Documentation
get_cycle_estimate()
uint64_t get_cycle_estimate (const DepthwiseArgs & args, const OutputStage & os) const inline
Definition at line 51 of file depthwise_implementation.hpp.
References DepthwiseImplementation< TInput, TWeight, TOutput, OutputStage >::cycle_estimate.
Referenced by arm_conv::depthwise::get_compatible_kernels().
   {
     return (cycle_estimate == nullptr) ? 0 : cycle_estimate(args, os);
   }
get_instance()
DepthwiseCommon<TInput, TWeight, TOutput>* get_instance (const DepthwiseArgs & args, const OutputStage & os) const inline
Definition at line 56 of file depthwise_implementation.hpp.
References arm_conv::depthwise::depthwise_implementation_list(), and DepthwiseImplementation< TInput, TWeight, TOutput, OutputStage >::initialise.
Referenced by arm_conv::depthwise::depthwise().
   {
     return initialise(args, os);
   }
get_is_supported()
bool get_is_supported (const DepthwiseArgs & args, const OutputStage & os) const inline
Definition at line 46 of file depthwise_implementation.hpp.
References DepthwiseImplementation< TInput, TWeight, TOutput, OutputStage >::is_supported.
   {
     return (is_supported == nullptr) ? true : is_supported(args, os);
   }
Field Documentation
cycle_estimate
std::function<uint64_t(const DepthwiseArgs &, const OutputStage &)> cycle_estimate
Definition at line 43 of file depthwise_implementation.hpp.
Referenced by arm_conv::depthwise::find_implementation(), and DepthwiseImplementation< TInput, TWeight, TOutput, OutputStage >::get_cycle_estimate().
initialise
std::function<DepthwiseCommon<TInput, TWeight, TOutput> *(const DepthwiseArgs &, const OutputStage &)> initialise
Definition at line 44 of file depthwise_implementation.hpp.
Referenced by DepthwiseImplementation< TInput, TWeight, TOutput, OutputStage >::get_instance().
is_supported
std::function<bool(const DepthwiseArgs &, const OutputStage &)> is_supported
Definition at line 42 of file depthwise_implementation.hpp.
Referenced by DepthwiseImplementation< TInput, TWeight, TOutput, OutputStage >::get_is_supported().
method
const DepthwiseMethod method
Definition at line 40 of file depthwise_implementation.hpp.
name
const char* name
Definition at line 41 of file depthwise_implementation.hpp.
The documentation for this struct was generated from the following file:
src/core/NEON/kernels/arm_conv/depthwise/depthwise_implementation.hpp