Compute Library: ClComponentMatMul Class Reference
ClComponentMatMul Class Reference final
#include <ClComponentMatMul.h>
Public Types
using Attributes = MatMulAttributes
Attributes are a set of backend-agnostic parameters that define what a component does.
using Settings = GpuMatMulSettings
Settings are a set of backend-specific parameters that influence the implementation of a component.
Public Types inherited from IGpuKernelComponent
using Properties = KernelProperties
Public Member Functions
ClComponentMatMul (ComponentId id, const Properties &properties, const ArgumentPack< ITensorInfo > &tensors, const Attributes &attributes, const Settings &settings)
Constructor.
~ClComponentMatMul () override
Destructor.
ClComponentMatMul (const ClComponentMatMul &component)=delete
Prevent instances of this class from being copy constructed.
ClComponentMatMul & operator= (const ClComponentMatMul &component)=delete
Prevent instances of this class from being copied.
ClComponentMatMul (ClComponentMatMul &&component)=default
Allow instances of this class to be move constructed.
ClComponentMatMul & operator= (ClComponentMatMul &&component)=default
Allow instances of this class to be moved.
const IGpuCkwComponentDriver * ckw_component_driver () const override
Get writer for the component.
GpuComponentType type () const override
Get component type.
Public Member Functions inherited from IGpuKernelComponent
IGpuKernelComponent (ComponentId id, const Properties &properties, const ArgumentPack< ITensorInfo > &tensors)
Constructor.
virtual ~IGpuKernelComponent ()
Destructor.
ComponentId id () const
Get component id.
ArgumentPack< ITensorInfo > tensors () const
Get tensor arguments.
Properties properties () const
Get properties.
Static Public Member Functions
static Status validate (const Properties &properties, const ArgumentPack< ITensorInfo > &tensors, const Attributes &attributes, const Settings &settings)
Validate the component.
Detailed Description
Definition at line 49 of file ClComponentMatMul.h.
Member Typedef Documentation
Attributes
using Attributes = MatMulAttributes
Attributes are a set of backend-agnostic parameters that define what a component does.
Definition at line 53 of file ClComponentMatMul.h.
Settings
using Settings = GpuMatMulSettings
Settings are a set of backend-specific parameters that influence the implementation of a component.
Definition at line 55 of file ClComponentMatMul.h.
Constructor & Destructor Documentation
ClComponentMatMul() [1/3]
ClComponentMatMul (ComponentId id, const Properties & properties, const ArgumentPack< ITensorInfo > & tensors, const Attributes & attributes, const Settings & settings)
Constructor.
Similar to ClComponentMatMul::validate()
Definition at line 127 of file ClComponentMatMul.cpp.
     : IGpuKernelComponent{id, properties, tensors},
       _component_writer{std::make_unique<GpuCkwMatMul>(id, tensors, attributes, settings)}
 {
 }
References IGpuKernelComponent::id(), IGpuKernelComponent::properties(), and IGpuKernelComponent::tensors().
~ClComponentMatMul()
~ClComponentMatMul () override
Destructor.
Definition at line 137 of file ClComponentMatMul.cpp.
 {
 }
ClComponentMatMul() [2/3]
ClComponentMatMul (const ClComponentMatMul & component) delete
Prevent instances of this class from being copy constructed.
ClComponentMatMul() [3/3]
ClComponentMatMul (ClComponentMatMul && component) default
Allow instances of this class to be move constructed.
Member Function Documentation
ckw_component_driver()
const IGpuCkwComponentDriver * ckw_component_driver () const override virtual
Get writer for the component.
Reimplemented from IGpuKernelComponent.
Definition at line 141 of file ClComponentMatMul.cpp.
 {
     return _component_writer.get();
 }
operator=() [1/2]
ClComponentMatMul& operator= (ClComponentMatMul && component) default
Allow instances of this class to be moved.
operator=() [2/2]
ClComponentMatMul& operator= (const ClComponentMatMul & component) delete
Prevent instances of this class from being copied.
type()
GpuComponentType type () const inline override virtual
Get component type.
Implements IGpuKernelComponent.
Definition at line 112 of file ClComponentMatMul.h.
     {
         return GpuComponentType::Complex;
     }
References arm_compute::experimental::dynamic_fusion::Complex.
validate()
Status validate (const Properties & properties, const ArgumentPack< ITensorInfo > & tensors, const Attributes & attributes, const Settings & settings) static
Validate the component.
Parameters
[in] properties Component properties
[in,out] tensors Tensor arguments to the component
[in] attributes Component attributes
[in] settings Component settings
Returns
Status Validation results
Tensor argument names:
ACL_SRC_0: LHS
ACL_SRC_1: RHS
ACL_DST_0: Output
Tensor argument constness:
ACL_SRC_0: Const
ACL_SRC_1: Const
ACL_DST_0: Const
Valid data layouts:
NHWC
Valid data type configurations:
ACL_SRC_0 ACL_SRC_1 ACL_DST_0
F16 F16 F16
F32 F32 F32
Definition at line 81 of file ClComponentMatMul.cpp.
 {
     ARM_COMPUTE_UNUSED(properties);
     ARM_COMPUTE_UNUSED(attributes);
     const auto lhs = tensors.get_const_tensor(TensorType::ACL_SRC_0);
     const auto rhs = tensors.get_const_tensor(TensorType::ACL_SRC_1);
     const auto dst = tensors.get_const_tensor(TensorType::ACL_DST_0);
     // Currently, the only supported case is when adj_lhs = false and adj_rhs = true
     ARM_COMPUTE_RETURN_ERROR_ON((attributes.adj_lhs() != false) && (attributes.adj_rhs() != true));
     // Check if Matching data type
     ARM_COMPUTE_RETURN_ERROR_ON_MISMATCHING_DATA_TYPES(lhs, rhs);
     ARM_COMPUTE_RETURN_ERROR_ON_MISMATCHING_DATA_TYPES(lhs, dst);
     // Data type
     ARM_COMPUTE_RETURN_ERROR_ON_DATA_TYPE_CHANNEL_NOT_IN(lhs, 1, DataType::F16, DataType::F32);
     ARM_COMPUTE_RETURN_ERROR_ON_MISMATCHING_DATA_TYPES(lhs, dst);
     // All tensor infos are initialized
     ARM_COMPUTE_RETURN_ERROR_ON(lhs->tensor_shape().total_size() == 0);
     ARM_COMPUTE_RETURN_ERROR_ON(rhs->tensor_shape().total_size() == 0);
     ARM_COMPUTE_RETURN_ERROR_ON(dst->tensor_shape().total_size() == 0);
     // Device requirements are met
     ARM_COMPUTE_RETURN_ERROR_ON_F16_UNSUPPORTED(lhs);
     // Check if block sizes are supported
     MatMulKernelInfo matmul_kernel_info =
         MatMulKernelInfo(attributes.adj_lhs(), attributes.adj_rhs(), settings.m0(), settings.n0(), settings.k0());
     ARM_COMPUTE_RETURN_ON_ERROR(validate_matmul_kernel_info(attributes, settings));
     ARM_COMPUTE_RETURN_ON_ERROR(
         opencl::kernels::validate_matmul_input_shapes(lhs->tensor_shape(), rhs->tensor_shape(), matmul_kernel_info));
     // Check if dst shape is correct
     const auto expected_dst_shape =
         misc::shape_calculator::compute_matmul_shape(lhs->tensor_shape(), rhs->tensor_shape(), matmul_kernel_info);
     ARM_COMPUTE_RETURN_ERROR_ON_MISMATCHING_DIMENSIONS(dst->tensor_shape(), expected_dst_shape);
     return Status{};
 }
References arm_compute::ACL_DST_0, arm_compute::ACL_SRC_0, arm_compute::ACL_SRC_1, MatMulAttributes::adj_lhs(), MatMulAttributes::adj_rhs(), ARM_COMPUTE_RETURN_ERROR_ON, ARM_COMPUTE_RETURN_ERROR_ON_DATA_TYPE_CHANNEL_NOT_IN, ARM_COMPUTE_RETURN_ERROR_ON_F16_UNSUPPORTED, ARM_COMPUTE_RETURN_ERROR_ON_MISMATCHING_DATA_TYPES, ARM_COMPUTE_RETURN_ERROR_ON_MISMATCHING_DIMENSIONS, ARM_COMPUTE_RETURN_ON_ERROR, ARM_COMPUTE_UNUSED, arm_compute::misc::shape_calculator::compute_matmul_shape(), arm_compute::test::validation::dst, arm_compute::F16, arm_compute::F32, GpuMatMulSettings::k0(), GpuMatMulSettings::m0(), GpuMatMulSettings::n0(), IGpuKernelComponent::properties(), IGpuKernelComponent::tensors(), and arm_compute::opencl::kernels::validate_matmul_input_shapes().
The documentation for this class was generated from the following files:
src/dynamic_fusion/sketch/gpu/components/cl/ClComponentMatMul.h
src/dynamic_fusion/sketch/gpu/components/cl/ClComponentMatMul.cpp