Compute Library: RedOpYZW_complex< T, S, axis, op > Struct Template Reference
RedOpYZW_complex< T, S, axis, op > Struct Template Reference
#include <impl.h>
Public Types
using ExactTagType = typename wrapper::traits::neon_vector< T, S >::tag_type
SIMD vector tag type.
using neon_vector = typename wrapper::traits::neon_vector< T, S >::type
Public Member Functions
void operator() (const Window &in_window, Window &out_window, const ITensor *in, ITensor *out, int, const ReductionOperation)
Detailed Description
template<typename T, int S, int axis, ReductionOperation op>
struct arm_compute::RedOpYZW_complex< T, S, axis, op >
Definition at line 1130 of file impl.h.
Member Typedef Documentation
ExactTagType
using ExactTagType = typename wrapper::traits::neon_vector<T, S>::tag_type
SIMD vector tag type.
Definition at line 1133 of file impl.h.
neon_vector
using neon_vector = typename wrapper::traits::neon_vector<T, S>::type
Definition at line 1134 of file impl.h.
Member Function Documentation
operator()()
void operator() (const Window & in_window, Window & out_window, const ITensor * in, ITensor * out, int , const ReductionOperation) inline
Definition at line 1136 of file impl.h.
     {
         ARM_COMPUTE_ERROR_ON(axis != 2);
         ARM_COMPUTE_ERROR_ON(op != ReductionOperation::SUM);
         const TensorInfo in_info            = *(in->info());
         const size_t     stride_z           = in_info.strides_in_bytes()[axis];
         const int        window_step_x      = 16 / sizeof(T);
         const auto       window_start_x_tmp = static_cast<int>(in_window.x().start());
         const auto       window_end_x_tmp   = static_cast<int>(in_window.x().end());
         // As it split over x-axis, need to set the correct spiltted window start and end.
         const auto window_start_x = static_cast<int>(0);
         const auto window_end_x   = static_cast<int>(in_window.shape().x());
         Window in_win_no_pad = in_window;
         in_win_no_pad.set(Window::DimX, Window::Dimension(window_start_x_tmp, window_end_x_tmp, in_window.shape().x()));
         Window out_win_no_pad = out_window;
         out_win_no_pad.set(Window::DimX,
                            Window::Dimension(window_start_x_tmp, window_end_x_tmp, out_window.shape().x()));
         Iterator input(in, in_win_no_pad);
         Iterator output(out, out_win_no_pad);
         execute_window_loop(
             in_win_no_pad,
             [&](const Coordinates &)
             {
                 // Compute window_step_x elements per iteration
                 int x = window_start_x;
                 for (; x <= (window_end_x - window_step_x); x += window_step_x)
                 {
                     neon_vector vec_res_value_0 = {0};
                     neon_vector vec_res_value_1 = {0};
                     vec_res_value_0 = wrapper::vdup_n(static_cast<T>(0.f), ExactTagType{});
                     vec_res_value_1 = wrapper::vdup_n(static_cast<T>(0.f), ExactTagType{});
                     T *out_ptr = reinterpret_cast<T *>(output.ptr() + 2 * x * sizeof(T));
                     for (unsigned int dim = 0; dim < in_info.dimension(axis); ++dim)
                     {
                         T *in_ptr_0 = reinterpret_cast<T *>(input.ptr() + 2 * x * sizeof(T) + stride_z * dim);
                         T *in_ptr_1 = reinterpret_cast<T *>(input.ptr() + 2 * x * sizeof(T) + 16 + stride_z * dim);
                         const auto vec_elements_0 = wrapper::vloadq(in_ptr_0);
                         const auto vec_elements_1 = wrapper::vloadq(in_ptr_1);
                         vec_res_value_0 = wrapper::vadd(vec_elements_0, vec_res_value_0);
                         vec_res_value_1 = wrapper::vadd(vec_elements_1, vec_res_value_1);
                     }
                     wrapper::vstore(out_ptr, vec_res_value_0);
                     wrapper::vstore(out_ptr + 4, vec_res_value_1);
                 }
                 // Compute left-over elements
                 for (; x < window_end_x; ++x)
                 {
                     auto res_value_0 = 0.f;
                     auto res_value_1 = 0.f;
                     T *out_ptr = reinterpret_cast<T *>(output.ptr() + 2 * x * sizeof(T));
                     for (unsigned int dim = 0; dim < in_info.dimension(axis); ++dim)
                     {
                         T *in_ptr = reinterpret_cast<T *>(input.ptr() + 2 * x * sizeof(T) + stride_z * dim);
                         res_value_0 += *in_ptr;
                         res_value_1 += *(in_ptr + 1);
                     }
                     *out_ptr       = res_value_0;
                     *(out_ptr + 1) = res_value_1;
                 }
             },
             input, output);
     }
References ARM_COMPUTE_ERROR_ON, TensorInfo::dimension(), Window::DimX, Window::Dimension::end(), arm_compute::execute_window_loop(), ITensor::info(), arm_compute::test::validation::input, Iterator::ptr(), Window::set(), Window::shape(), Window::Dimension::start(), TensorInfo::strides_in_bytes(), arm_compute::SUM, arm_compute::wrapper::vadd(), arm_compute::wrapper::vdup_n(), arm_compute::wrapper::vloadq(), arm_compute::wrapper::vstore(), Dimensions< T >::x(), and Window::x().
The documentation for this struct was generated from the following file:
src/cpu/kernels/reduction_layer/generic/neon/impl.h