Compute Library: ClScatter Class Reference
ClScatter Class Reference
Basic operator to execute Scatter on OpenCL.
#include <ClScatter.h>
Public Member Functions
ClScatter ()
Constructor.
~ClScatter ()=default
Default destructor.
void configure (const CLCompileContext &compile_context, const ITensorInfo *src, const ITensorInfo *updates, const ITensorInfo *indices, ITensorInfo *dst, const ScatterInfo &Scatter_info)
Initialise the kernel's inputs and output.
void run (ITensorPack &tensors) override
Run the kernels contained in the function.
Public Member Functions inherited from ICLOperator
ICLOperator (IRuntimeContext *ctx=nullptr)
Constructor.
ICLOperator (const ICLOperator &)=delete
Prevent instances of this class from being copied (As this class contains pointers)
ICLOperator (ICLOperator &&)=default
Default move constructor.
ICLOperator & operator= (const ICLOperator &)=delete
Prevent instances of this class from being copied (As this class contains pointers)
ICLOperator & operator= (ICLOperator &&)=default
Default move assignment operator.
void prepare (ITensorPack &constants) override
Prepare the function for executing.
MemoryRequirements workspace () const override
Return the memory requirements required by the workspace.
Public Member Functions inherited from IOperator
virtual ~IOperator ()=default
Destructor.
Static Public Member Functions
static Status validate (const ITensorInfo *src, const ITensorInfo *updates, const ITensorInfo *indices, const ITensorInfo *dst, const ScatterInfo &Scatter_info)
Static function to check if given info will lead to a valid configuration.
Detailed Description
Basic operator to execute Scatter on OpenCL.
This operator calls the following OpenCL kernels:
kernels::ClScatterKernel
Definition at line 47 of file ClScatter.h.
Constructor & Destructor Documentation
ClScatter()
ClScatter ()
Constructor.
Definition at line 39 of file ClScatter.cpp.
 {
 }
~ClScatter()
~ClScatter () default
Default destructor.
Member Function Documentation
configure()
void configure (const CLCompileContext & compile_context, const ITensorInfo * src, const ITensorInfo * updates, const ITensorInfo * indices, ITensorInfo * dst, const ScatterInfo & Scatter_info)
Initialise the kernel's inputs and output.
Valid data layouts:
All
Note
indices must always be U32
src, updates and dst tensors must be same datatype.
Parameters
[in] compile_context The compile context to be used.
[in] src Source input tensor info. Can be nullptr when using "Add" Scatter Function with zero initialization.
[in] updates Tensor info for tensor storing update values to use for scatter function. Data types supported: same as src.
[in] indices Tensor info for tensor storing indices to use for scatter function. Data types supported: U32 only.
[out] dst Output tensor to store the result of the Scatter Function. Data types supported: same as src and updates.
[in] Scatter_info Contains Scatter operation information described in ScatterInfo.
Definition at line 55 of file ClScatter.cpp.
 {
     ARM_COMPUTE_ERROR_ON_NULLPTR(updates, indices, dst);
     ARM_COMPUTE_LOG_PARAMS(src, indices, dst, info);
     ARM_COMPUTE_UNUSED(src);
     ARM_COMPUTE_UNUSED(updates);
     ARM_COMPUTE_UNUSED(indices);
     ARM_COMPUTE_UNUSED(dst);
     ARM_COMPUTE_UNUSED(info);
     // Perform validation step
     ARM_COMPUTE_ERROR_THROW_ON(validate(src, updates, indices, dst, info));
     _fill_zero = info.zero_initialization;
     // If necessary, create fill kernel to fill dst tensor.
     if (_fill_zero)
     {
         _fill_kernel = std::make_unique<kernels::ClFillKernel>();
     }
     // Configure ClScatterKernel
     auto k = std::make_unique<kernels::ClScatterKernel>();
     k->set_target(CLScheduler::get().target());
     k->configure(compile_context, src, updates, indices, dst, info);
     _scatter_kernel = std::move(k);
 }
References ARM_COMPUTE_ERROR_ON_NULLPTR, ARM_COMPUTE_ERROR_THROW_ON, ARM_COMPUTE_LOG_PARAMS, ARM_COMPUTE_UNUSED, arm_compute::test::validation::dst, CLScheduler::get(), arm_compute::test::validation::info, arm_compute::test::validation::src, and arm_compute::validate().
run()
void run (ITensorPack & tensors) override virtual
Run the kernels contained in the function.
Parameters
[in] tensors Vector that contains the tensors to operate on.
Reimplemented from ICLOperator.
Definition at line 87 of file ClScatter.cpp.
 {
     ARM_COMPUTE_UNUSED(tensors);
 }
References ARM_COMPUTE_UNUSED.
validate()
Status validate (const ITensorInfo * src, const ITensorInfo * updates, const ITensorInfo * indices, const ITensorInfo * dst, const ScatterInfo & Scatter_info) static
Static function to check if given info will lead to a valid configuration.
Similar to ClScatter::configure()
Returns
a status
Definition at line 43 of file ClScatter.cpp.
 {
     ARM_COMPUTE_RETURN_ERROR_ON_NULLPTR(updates, indices, dst);
     ARM_COMPUTE_RETURN_ERROR_ON_DATA_TYPE_CHANNEL_NOT_IN(indices, 1, DataType::U32);
     return kernels::ClScatterKernel::validate(src, updates, indices, dst, info);
 }
References ARM_COMPUTE_RETURN_ERROR_ON_DATA_TYPE_CHANNEL_NOT_IN, ARM_COMPUTE_RETURN_ERROR_ON_NULLPTR, arm_compute::test::validation::dst, arm_compute::test::validation::info, arm_compute::test::validation::src, arm_compute::U32, and ClScatterKernel::validate().
The documentation for this class was generated from the following files:
src/gpu/cl/operators/ClScatter.h
src/gpu/cl/operators/ClScatter.cpp