Compute Library: GpuWorkloadContext Class Reference
GpuWorkloadContext Class Reference
Provide context necessary for the creation and configuration of a workload e.g.
#include <GpuWorkloadContext.h>
Public Member Functions
GpuWorkloadContext (CLCompileContext *cl_compile_context)
Constructor.
GpuWorkloadContext (const GpuWorkloadContext &config)=default
Allow instances of this class to be copy constructed.
GpuWorkloadContext & operator= (const GpuWorkloadContext &config)=default
Allow instances of this class to be copied.
GpuWorkloadContext (GpuWorkloadContext &&config)=default
Allow instances of this class to be move constructed.
GpuWorkloadContext & operator= (GpuWorkloadContext &&config)=default
Allow instances of this class to be moved.
GpuLanguage gpu_language () const
Get GpuLanguage of the context.
GpuTarget gpu_target () const
Get GpuTarget of the context.
const CLCompileContext * cl_compile_context () const
Get CLCompileContext If the gpu language is not OpenCL, then return nullptr.
Detailed Description
Provide context necessary for the creation and configuration of a workload e.g.
gpu targets and capabilities, cl::Device for querying OpenCl extensions. Both can affect how a kernel is generated
This context is shared between different operators within a sketch, and has to stay valid for the entire workload creation session. This context may also be shared between different sketches.
This class only contains information for workload creation, but not for runtime (e.g. cl::Queue for enqueueing the kernels)
Definition at line 56 of file GpuWorkloadContext.h.
Constructor & Destructor Documentation
GpuWorkloadContext() [1/3]
GpuWorkloadContext (CLCompileContext * cl_compile_context)
Constructor.
Definition at line 33 of file GpuWorkloadContext.cpp.
References arm_compute::experimental::dynamic_fusion::OpenCL.
     : _gpu_language{ GpuLanguage::OpenCL }, _cl_compile_ctx{ cl_compile_ctx }
 {
 }
GpuWorkloadContext() [2/3]
GpuWorkloadContext (const GpuWorkloadContext & config) default
Allow instances of this class to be copy constructed.
GpuWorkloadContext() [3/3]
GpuWorkloadContext (GpuWorkloadContext && config) default
Allow instances of this class to be move constructed.
Member Function Documentation
cl_compile_context()
const CLCompileContext * cl_compile_context () const
Get CLCompileContext If the gpu language is not OpenCL, then return nullptr.
Definition at line 48 of file GpuWorkloadContext.cpp.
Referenced by ClWorkloadRuntime::configure(), GpuReshape::create_op(), GpuSoftmax::create_op(), GpuPool2d::create_op(), GpuSoftmax::is_supported_op(), and GpuPool2d::is_supported_op().
 {
     return _cl_compile_ctx;
 }
gpu_language()
GpuLanguage gpu_language () const
Get GpuLanguage of the context.
Definition at line 43 of file GpuWorkloadContext.cpp.
Referenced by ClWorkloadRuntime::configure(), GpuSoftmax::is_supported_op(), and GpuPool2d::is_supported_op().
 {
     return _gpu_language;
 }
gpu_target()
GpuTarget gpu_target () const
Get GpuTarget of the context.
Definition at line 38 of file GpuWorkloadContext.cpp.
References CLCompileContext::get_gpu_target().
Referenced by GpuDepthwiseConv2d::create_op(), and GpuConv2d::create_op().
 {
     return _cl_compile_ctx->get_gpu_target();
 }
operator=() [1/2]
GpuWorkloadContext& operator= (const GpuWorkloadContext & config) default
Allow instances of this class to be copied.
operator=() [2/2]
GpuWorkloadContext& operator= (GpuWorkloadContext && config) default
Allow instances of this class to be moved.
The documentation for this class was generated from the following files:
arm_compute/dynamic_fusion/sketch/gpu/GpuWorkloadContext.h
src/dynamic_fusion/sketch/gpu/GpuWorkloadContext.cpp