Compute Library: ClKernelLibrary Class Reference
ClKernelLibrary Class Reference final
ClKernelLibrary contains all the OpenCL kernels that are used throughout the library.
#include <ClKernelLibrary.h>
Data Structures
struct ClProgramInfo
Structure to encapsulte program related information.
Public Member Functions
void set_kernel_path (std::string kernel_path)
Sets the path that the kernels reside in.
const std::string & kernel_path () const
Gets the path that the kernels reside in.
ClProgramInfo program (const std::string &program_name) const
Gets the source of the selected program.
std::string program_name (const std::string &kernel_name) const
Returns the program name given a kernel name.
Static Public Member Functions
static ClKernelLibrary & get ()
Access the KernelLibrary singleton.
Detailed Description
ClKernelLibrary contains all the OpenCL kernels that are used throughout the library.
Note
Kernel library is a singleton to reduce memory requirements
Sole responsibility is just to provide access to the kernel string, does not perform any compilation and relevant tasks
Definition at line 41 of file ClKernelLibrary.h.
Member Function Documentation
get()
ClKernelLibrary & get () static
Access the KernelLibrary singleton.
Returns
The KernelLibrary instance
Definition at line 1001 of file ClKernelLibrary.cpp.
Referenced by ClKernelRuntime::configure(), CLKernelLibrary::create_kernel(), arm_compute::create_kernel(), CLKernelLibrary::get_kernel_path(), CLKernelLibrary::get_program(), CLKernelLibrary::get_program_name(), CLKernelLibrary::init(), and CLKernelLibrary::set_kernel_path().
 {
     static ClKernelLibrary _kernel_library;
     return _kernel_library;
 }
kernel_path()
const std::string & kernel_path () const
Gets the path that the kernels reside in.
Definition at line 1028 of file ClKernelLibrary.cpp.
Referenced by ClKernelRuntime::configure(), arm_compute::create_kernel(), and CLKernelLibrary::get_kernel_path().
 {
     return _kernel_path;
 }
program()
ClKernelLibrary::ClProgramInfo program (const std::string & program_name) const
Gets the source of the selected program.
Parameters
[in] program_name Program name
Returns
A pair with the source (false) or the binary (true), of the selected program
Definition at line 1033 of file ClKernelLibrary.cpp.
References ARM_COMPUTE_ERROR_ON_MSG, ARM_COMPUTE_ERROR_VAR, ClKernelLibrary::program_name(), and arm_compute::read_file().
Referenced by CLKernelLibrary::create_kernel(), arm_compute::create_kernel(), and CLKernelLibrary::get_program().
 {
 #ifdef EMBEDDED_KERNELS
 #ifdef ARM_COMPUTE_COMPRESSED_KERNELS
     const auto inflatted_program_source_it = _decompressed_source_map.find(program_name);
     if(inflatted_program_source_it != _decompressed_source_map.end())
     {
         return ClProgramInfo{ inflatted_program_source_it->second, false };
     }
 #endif /* ARM_COMPUTE_COMPRESSED_KERNELS */
     const auto program_source_it = _program_source_map.find(program_name);
     if(program_source_it == _program_source_map.end())
     {
         ARM_COMPUTE_ERROR_VAR("Embedded program for %s does not exist.", program_name.c_str());
     }
     std::string program_source = program_source_it->second;
 #ifdef ARM_COMPUTE_COMPRESSED_KERNELS
     std::string decompressed_program_source = decompress_zlib(decode_base64(program_source_it->second));
     ARM_COMPUTE_ERROR_ON_MSG(decompressed_program_source.empty(), "Cannot de-compress requested program");
     _decompressed_source_map.insert(std::make_pair(program_name, decompressed_program_source));
     program_source = std::move(decompressed_program_source);
 #endif /* ARM_COMPUTE_COMPRESSED_KERNELS */
     return ClProgramInfo{ program_source, false };
 #else  /* EMBEDDED_KERNELS */
     // Check for binary
     std::string source_name = _kernel_path + program_name;
     std::string binary_name = source_name + "bin";
     std::string program_source{};
     bool        is_binary = false;
     if(std::ifstream(binary_name).is_open())
     {
         program_source = read_file(binary_name, true);
         is_binary      = true;
     }
     else if(std::ifstream(source_name).is_open())
     {
         program_source = read_file(source_name, false);
     }
     else
     {
         ARM_COMPUTE_ERROR_VAR("Kernel file %s does not exist.", source_name.c_str());
     }
     return ClProgramInfo{ program_source, is_binary };
 #endif /* EMBEDDED_KERNELS */
 }
program_name()
std::string program_name (const std::string & kernel_name) const
Returns the program name given a kernel name.
Returns
Program name
Definition at line 1007 of file ClKernelLibrary.cpp.
References ARM_COMPUTE_ERROR_VAR.
Referenced by CLKernelLibrary::create_kernel(), arm_compute::create_kernel(), CLKernelLibrary::get_program_name(), and ClKernelLibrary::program().
 {
     // Find which program contains the kernel
     auto kernel_program_it = _kernel_program_map.find(kernel_name);
     if(_kernel_program_map.end() == kernel_program_it)
     {
         ARM_COMPUTE_ERROR_VAR("Kernel %s not found in the CLKernelLibrary", kernel_name.c_str());
     }
     const std::string program_name = kernel_program_it->second;
     return program_name;
 }
set_kernel_path()
void set_kernel_path (std::string kernel_path)
Sets the path that the kernels reside in.
Parameters
[in] kernel_path Path of the kernel
Definition at line 1022 of file ClKernelLibrary.cpp.
Referenced by CLKernelLibrary::init(), and CLKernelLibrary::set_kernel_path().
 {
     _kernel_path = std::move(kernel_path);
     _kernel_path += "/";
 }
The documentation for this class was generated from the following files:
src/gpu/cl/ClKernelLibrary.h
src/gpu/cl/ClKernelLibrary.cpp