Compute Library: SingleThreadScheduler Class Reference
SingleThreadScheduler Class Reference final
Pool of threads to automatically split a kernel's execution among several threads.
#include <SingleThreadScheduler.h>
Public Member Functions
SingleThreadScheduler ()=default
Constructor.
void set_num_threads (unsigned int num_threads) override
Sets the number of threads the scheduler will use to run the kernels.
unsigned int num_threads () const override
Returns the number of threads that the SingleThreadScheduler has, which is always 1.
void schedule (ICPPKernel *kernel, const Hints &hints) override
Runs the kernel in the same thread as the caller synchronously.
void schedule_op (ICPPKernel *kernel, const Hints &hints, const Window &window, ITensorPack &tensors) override
Runs the kernel in the same thread as the caller synchronously.
Public Member Functions inherited from IScheduler
IScheduler ()
Default constructor.
virtual ~IScheduler ()=default
Destructor.
virtual void set_num_threads_with_affinity (unsigned int num_threads, BindFunc func)
Sets the number of threads the scheduler will use to run the kernels but also using a binding function to pin the threads to given logical cores.
virtual void run_tagged_workloads (std::vector< Workload > &workloads, const char *tag)
Execute all the passed workloads.
CPUInfo & cpu_info ()
Get CPU info.
unsigned int num_threads_hint () const
Get a hint for the best possible number of execution threads.
Additional Inherited Members
Public Types inherited from IScheduler
enum StrategyHint { STATIC, DYNAMIC }
Strategies available to split a workload.
using BindFunc = std::function< int(int, int)>
Function to be used and map a given thread id to a logical core id.
using Workload = std::function< void(const ThreadInfo &)>
Signature for the workloads to execute.
Static Public Attributes inherited from IScheduler
static constexpr unsigned int split_dimensions_all = std::numeric_limits<unsigned>::max()
When arm_compute::ISchedular::Hints::_split_dimension is initialized with this value then the schedular is free to break down the problem space over as many dimensions as it wishes.
Detailed Description
Pool of threads to automatically split a kernel's execution among several threads.
Definition at line 32 of file SingleThreadScheduler.h.
Constructor & Destructor Documentation
SingleThreadScheduler()
SingleThreadScheduler () default
Constructor.
Member Function Documentation
num_threads()
unsigned int num_threads () const override virtual
Returns the number of threads that the SingleThreadScheduler has, which is always 1.
Returns
Number of threads available in SingleThreadScheduler.
Implements IScheduler.
Definition at line 73 of file SingleThreadScheduler.cpp.
 {
     return 1;
 }
schedule()
void schedule (ICPPKernel * kernel, const Hints & hints) override virtual
Runs the kernel in the same thread as the caller synchronously.
Parameters
[in] kernel Kernel to execute.
[in] hints Hints for the scheduler.
Implements IScheduler.
Definition at line 38 of file SingleThreadScheduler.cpp.
References ThreadInfo::cpu_info, IScheduler::cpu_info(), arm_compute::test::validation::info, Window::num_iterations(), ICPPKernel::run(), IScheduler::Hints::split_dimension(), IScheduler::split_dimensions_all, and IKernel::window().
 {
     const Window &max_window = kernel->window();
     if(hints.split_dimension() != IScheduler::split_dimensions_all)
     {
         const unsigned int num_iterations = max_window.num_iterations(hints.split_dimension());
         if(num_iterations < 1)
         {
             return;
         }
     }
     ThreadInfo info;
     info.cpu_info = &cpu_info();
     kernel->run(kernel->window(), info);
 }
schedule_op()
void schedule_op (ICPPKernel * kernel, const Hints & hints, const Window & window, ITensorPack & tensors) override virtual
Runs the kernel in the same thread as the caller synchronously.
Parameters
[in] kernel Kernel to execute.
[in] hints Hints for the scheduler.
[in] window Window to use for kernel execution.
[in] tensors Vector containing the tensors to operate on.
Implements IScheduler.
Definition at line 56 of file SingleThreadScheduler.cpp.
References ARM_COMPUTE_UNUSED, ThreadInfo::cpu_info, IScheduler::cpu_info(), arm_compute::test::validation::info, and ICPPKernel::run_op().
 {
     ARM_COMPUTE_UNUSED(hints);
     ThreadInfo info;
     info.cpu_info = &cpu_info();
     kernel->run_op(tensors, window, info);
 }
set_num_threads()
void set_num_threads (unsigned int num_threads) override virtual
Sets the number of threads the scheduler will use to run the kernels.
Parameters
[in] num_threads This is ignored for this scheduler as the number of threads is always one.
Implements IScheduler.
Definition at line 32 of file SingleThreadScheduler.cpp.
References ARM_COMPUTE_ERROR_ON, and ARM_COMPUTE_UNUSED.
 {
     ARM_COMPUTE_UNUSED(num_threads);
     ARM_COMPUTE_ERROR_ON(num_threads != 1);
 }
The documentation for this class was generated from the following files:
arm_compute/runtime/SingleThreadScheduler.h
src/runtime/CPP/SingleThreadScheduler.cpp