Compute Library: CLCommandBuffer Class Reference
CLCommandBuffer Class Reference abstract
Command buffer contains a list of commands that is constructed once and later enqueued multiple times.
#include <CLCommandBuffer.h>
Public Member Functions
CLCommandBuffer ()
Constructor.
virtual ~CLCommandBuffer ()
Destructor.
CLCommandBuffer (const CLCommandBuffer &)=delete
Disallow copy constructor.
CLCommandBuffer & operator= (const CLCommandBuffer &)=delete
Disallow copy assignment.
CLCommandBuffer (CLCommandBuffer &&other)=delete
Disallow move constructor.
CLCommandBuffer & operator= (CLCommandBuffer &&other)=delete
Disallow move assignment.
virtual void add_kernel (cl_kernel kernel, const cl::NDRange &offset, const cl::NDRange &global, const cl::NDRange &local)=0
Add a kernel enqueue command to the command queue.
template<typename T , typename = std::enable_if_t<std::is_arithmetic<T>::value || std::is_pointer<T>::value>>
void add_mutable_argument (cl_uint arg_idx, const T *value)
Add the mutable argument to the current kernel enqueue command.
virtual void finalize ()=0
Finalize the command buffer.
virtual void update ()=0
Update the command buffer with new kernel argument values.
virtual void enqueue ()=0
Enqueue the command buffer.
virtual bool is_finalized () const =0
Check if the command buffer has been finalized.
Static Public Member Functions
static std::unique_ptr< CLCommandBuffer > create (cl_command_queue queue)
Create a new command buffer targeting the specified command queue.
Detailed Description
Command buffer contains a list of commands that is constructed once and later enqueued multiple times.
To prepare a command buffer:
Construct a new command buffer targeting a command queue using CLCommandBuffer::create.
Add kernel enqueue command to the buffer using CLCommandBuffer::add_kernel. The kernel must be ready to be enqueued with all the arguments set.
Specify which kernel argument is mutable after the command buffer has been finalized.
When all the kernel enqueue commands have been added, call CLCommandBuffer::finalize. After this point the command buffer is ready to be executed.
To execute the command buffer:
Make any changes in the value which the mutable arguments are pointing to.
Call CLCommandBuffer::update to apply the argument value changes.
Call CLCommandBuffer::enqueue to enqueue the command buffer to execute.
Definition at line 52 of file CLCommandBuffer.h.
Constructor & Destructor Documentation
CLCommandBuffer() [1/3]
CLCommandBuffer () default
Constructor.
~CLCommandBuffer()
~CLCommandBuffer () virtual default
Destructor.
CLCommandBuffer() [2/3]
CLCommandBuffer (const CLCommandBuffer &) delete
Disallow copy constructor.
CLCommandBuffer() [3/3]
CLCommandBuffer (CLCommandBuffer && other) delete
Disallow move constructor.
Member Function Documentation
add_kernel()
virtual void add_kernel (cl_kernel kernel, const cl::NDRange & offset, const cl::NDRange & global, const cl::NDRange & local) pure virtual
Add a kernel enqueue command to the command queue.
This function must be called before the command buffer has been finalized.
Parameters
[in] kernel The CL kernel.
[in] offset The global work offset.
[in] global The global work size.
[in] local The local work size.
Implemented in CLCompatCommandBuffer, and CLMutableCommandBuffer.
add_mutable_argument()
void add_mutable_argument (cl_uint arg_idx, const T * value) inline
Add the mutable argument to the current kernel enqueue command.
This function must be called after CLCommandBuffer::add_kernel but before the command buffer has been finalized.
The pointer must be valid and it must point to the correct value at the time CLCommandBuffer::update is called so that the value of the argument can be applied successfully to the kernel enqueue command.
Parameters
[in] arg_idx The index of the argument in the current kernel program.
[in] value The pointer to the value of the argument.
Definition at line 106 of file CLCommandBuffer.h.
     {
         add_mutable_argument_generic(arg_idx, value, sizeof(T));
     }
create()
std::unique_ptr< CLCommandBuffer > create (cl_command_queue queue) static
Create a new command buffer targeting the specified command queue.
Parameters
[in] queue The command queue to execute the command buffer.
Returns
A unique pointer to the newly created command buffer.
Definition at line 36 of file CLCommandBuffer.cpp.
 {
     const auto &cl_device            = CLKernelLibrary::get().get_device();
     const auto  has_mutable_dispatch = command_buffer_mutable_dispatch_supported(cl_device);
     if (has_mutable_dispatch)
     {
         return std::make_unique<CLMutableCommandBuffer>(queue);
     }
     else
     {
         return std::make_unique<CLCompatCommandBuffer>(queue);
     }
 }
References arm_compute::command_buffer_mutable_dispatch_supported(), CLKernelLibrary::get(), and CLKernelLibrary::get_device().
enqueue()
virtual void enqueue () pure virtual
Enqueue the command buffer.
This function must be called after the command buffer has been finalized.
Implemented in CLCompatCommandBuffer, and CLMutableCommandBuffer.
finalize()
virtual void finalize () pure virtual
Finalize the command buffer.
Implemented in CLCompatCommandBuffer, and CLMutableCommandBuffer.
is_finalized()
virtual bool is_finalized () const pure virtual
Check if the command buffer has been finalized.
Returns
true if the command buffer has been finalized.
Implemented in CLCompatCommandBuffer, and CLMutableCommandBuffer.
operator=() [1/2]
CLCommandBuffer& operator= (CLCommandBuffer && other) delete
Disallow move assignment.
operator=() [2/2]
CLCommandBuffer& operator= (const CLCommandBuffer &) delete
Disallow copy assignment.
update()
virtual void update () pure virtual
Update the command buffer with new kernel argument values.
This function must be called after the command buffer has been finalized.
All the value pointed by the mutable argument will be applied to the command buffer.
Implemented in CLCompatCommandBuffer, and CLMutableCommandBuffer.
The documentation for this class was generated from the following files:
src/core/CL/CLCommandBuffer.h
src/core/CL/CLCommandBuffer.cpp