Compute Library: CLRoundLayer Class Reference
CLRoundLayer Class Reference
Basic function to get the round (to the nearest even) value of an input tensor.
#include <CLElementwiseUnaryLayer.h>
Public Member Functions
CLRoundLayer ()
Default Constructor.
~CLRoundLayer ()
Default Destructor.
CLRoundLayer (const CLRoundLayer &)=delete
Prevent instances of this class from being copied (As this class contains pointers)
CLRoundLayer (CLRoundLayer &&)
Default move constructor.
CLRoundLayer & operator= (const CLRoundLayer &)=delete
Prevent instances of this class from being copied (As this class contains pointers)
CLRoundLayer & operator= (CLRoundLayer &&)
Default move assignment operator.
void configure (const ICLTensor *input, ICLTensor *output)
Initialize the function.
void configure (const CLCompileContext &compile_context, const ICLTensor *input, ICLTensor *output)
Initialize the function.
void run () override
Run the kernels contained in the function.
Public Member Functions inherited from IFunction
virtual ~IFunction ()=default
Destructor.
virtual void prepare ()
Prepare the function for executing.
Static Public Member Functions
static Status validate (const ITensorInfo *input, const ITensorInfo *output)
Static function to check if given info will lead to a valid configuration of CLRoundLayer.
Detailed Description
Basic function to get the round (to the nearest even) value of an input tensor.
Definition at line 371 of file CLElementwiseUnaryLayer.h.
Constructor & Destructor Documentation
CLRoundLayer() [1/3]
CLRoundLayer ()
Default Constructor.
Definition at line 288 of file CLElementwiseUnaryLayer.cpp.
References CLRoundLayer::operator=(), and CLRoundLayer::~CLRoundLayer().
     : _impl(std::make_unique<Impl>())
 {
 }
~CLRoundLayer()
~CLRoundLayer () default
Default Destructor.
Referenced by CLRoundLayer::CLRoundLayer().
CLRoundLayer() [2/3]
CLRoundLayer (const CLRoundLayer &) delete
Prevent instances of this class from being copied (As this class contains pointers)
CLRoundLayer() [3/3]
CLRoundLayer (CLRoundLayer &&) default
Default move constructor.
Member Function Documentation
configure() [1/2]
void configure (const ICLTensor * input, ICLTensor * output)
Initialize the function.
Valid data layouts:
All
Valid data type configurations:
src dst
F16 F16
F32 F32
Parameters
[in] input Input tensor. Data types supported: F16/F32.
[out] output Output tensor. Data types supported: same as input.
Definition at line 297 of file CLElementwiseUnaryLayer.cpp.
References CLKernelLibrary::get().
 {
     configure(CLKernelLibrary::get().get_compile_context(), input, output);
 }
configure() [2/2]
void configure (const CLCompileContext & compile_context, const ICLTensor * input, ICLTensor * output)
Initialize the function.
Parameters
[in] compile_context The compile context to be used.
[in] input Input tensor. Data types supported: F16/F32.
[out] output Output tensor. Data types supported: same as input.
Definition at line 302 of file CLElementwiseUnaryLayer.cpp.
References ITensor::info(), and arm_compute::test::validation::input.
 {
     _impl->src = input;
     _impl->dst = output;
     _impl->op  = std::make_unique<opencl::ClRound>();
     _impl->op->configure(compile_context, input->info(), output->info());
 }
operator=() [1/2]
CLRoundLayer& operator= (const CLRoundLayer &) delete
Prevent instances of this class from being copied (As this class contains pointers)
Referenced by CLRoundLayer::CLRoundLayer().
operator=() [2/2]
CLRoundLayer & operator= (CLRoundLayer &&) default
Default move assignment operator.
run()
void run () override virtual
Run the kernels contained in the function.
For CPU kernels:
Multi-threading is used for the kernels which are parallelisable.
By default std::thread::hardware_concurrency() threads are used.
Note
CPPScheduler::set_num_threads() can be used to manually set the number of threads
For OpenCL kernels:
All the kernels are enqueued on the queue associated with CLScheduler.
The queue is then flushed.
Note
The function will not block until the kernels are executed. It is the user's responsibility to wait.
Will call prepare() on first run if hasn't been done
Implements IFunction.
Definition at line 314 of file CLElementwiseUnaryLayer.cpp.
References arm_compute::ACL_DST, arm_compute::ACL_SRC, ITensorPack::add_tensor(), and arm_compute::test::validation::pack.
 {
     ITensorPack pack;
     pack.add_tensor(TensorType::ACL_SRC, _impl->src);
     pack.add_tensor(TensorType::ACL_DST, _impl->dst);
     _impl->op->run(pack);
 }
validate()
Status validate (const ITensorInfo * input, const ITensorInfo * output) static
Static function to check if given info will lead to a valid configuration of CLRoundLayer.
Parameters
[in] input First tensor input info. Data types supported: F16/F32.
[in] output Output tensor info. Data types supported: Same as input.
Returns
a status
Definition at line 309 of file CLElementwiseUnaryLayer.cpp.
References ClRound::validate().
 {
     return opencl::ClRound::validate(input, output);
 }
The documentation for this class was generated from the following files:
arm_compute/runtime/CL/functions/CLElementwiseUnaryLayer.h
src/runtime/CL/functions/CLElementwiseUnaryLayer.cpp