Compute Library: CpuActivationKernel Class Reference
CpuActivationKernel Class Reference
Interface for the activation kernel.
#include <CpuActivationKernel.h>
Data Structures
struct ActivationKernel
Public Member Functions
CpuActivationKernel ()=default
ARM_COMPUTE_DISALLOW_COPY_ALLOW_MOVE (CpuActivationKernel)
void configure (const ITensorInfo *src, ITensorInfo *dst, ActivationLayerInfo activation_info)
Configure kernel for a given list of arguments.
size_t get_mws (const CPUInfo &platform, size_t thread_count) const override
Return minimum workload size of the relevant kernel.
void run_op (ITensorPack &tensors, const Window &window, const ThreadInfo &info) override
Execute the kernel on the passed window.
const char * name () const override
Name of the kernel.
size_t get_split_dimension_hint () const
Get the preferred dimension in which the scheduler splits the work into multiple jobs.
Public Member Functions inherited from ICPPKernel
virtual ~ICPPKernel ()=default
Default destructor.
virtual void run (const Window &window, const ThreadInfo &info)
Execute the kernel on the passed window.
virtual void run_nd (const Window &window, const ThreadInfo &info, const Window &thread_locator)
legacy compatibility layer for implemantions which do not support thread_locator In these cases we simply narrow the interface down the legacy version
Public Member Functions inherited from IKernel
IKernel ()
Constructor.
virtual ~IKernel ()=default
Destructor.
virtual bool is_parallelisable () const
Indicates whether or not the kernel is parallelisable.
virtual BorderSize border_size () const
The size of the border for that kernel.
const Window & window () const
The maximum window the kernel can be executed on.
bool is_window_configured () const
Function to check if the embedded window of this kernel has been configured.
Static Public Member Functions
static Status validate (const ITensorInfo *src, const ITensorInfo *dst, const ActivationLayerInfo &act_info)
Static function to check if given info will lead to a valid configuration.
static const std::vector< ActivationKernel > & get_available_kernels ()
Static Public Member Functions inherited from ICpuKernel< CpuActivationKernel >
static const auto * get_implementation (const SelectorType &selector, KernelSelectionType selection_type=KernelSelectionType::Supported)
Micro-kernel selector.
Additional Inherited Members
Static Public Attributes inherited from ICPPKernel
static constexpr size_t default_mws = 1
Detailed Description
Interface for the activation kernel.
Definition at line 37 of file CpuActivationKernel.h.
Constructor & Destructor Documentation
CpuActivationKernel()
CpuActivationKernel () default
Member Function Documentation
ARM_COMPUTE_DISALLOW_COPY_ALLOW_MOVE()
ARM_COMPUTE_DISALLOW_COPY_ALLOW_MOVE (CpuActivationKernel)
configure()
void configure (const ITensorInfo * src, ITensorInfo * dst, ActivationLayerInfo activation_info)
Configure kernel for a given list of arguments.
Note
If the output tensor is a nullptr, the activation function will be performed in-place
Parameters
[in,out] src Source tensor info. In case of dst tensor = nullptr, this tensor will store the result of the activation function. Data types supported: QASYMM8/QASYMM8_SIGNED/QSYMM16/F16/F32.
[out] dst Destination tensor info. Data type supported: same as src
[in] activation_info Activation layer information.
Definition at line 189 of file CpuActivationKernel.cpp.
References ActivationLayerInfo::activation(), ARM_COMPUTE_ERROR_ON_NULLPTR, ARM_COMPUTE_ERROR_THROW_ON, ARM_COMPUTE_UNUSED, arm_compute::auto_init_if_empty(), arm_compute::calculate_squashed_or_max_window(), ICloneable< T >::clone(), ITensorInfo::data_type(), arm_compute::test::validation::dst, CPUInfo::get(), CPUInfo::get_cpu_model(), ICpuKernel< CpuActivationKernel >::get_implementation(), CPUInfo::get_isa(), ActivationLayerInfo::is_lut_supported(), ITensorInfo::quantization_info(), QuantizationInfo::uniform(), and arm_compute::cpu::kernels::validate_arguments().
 {
     ARM_COMPUTE_UNUSED(dst);
     ARM_COMPUTE_ERROR_ON_NULLPTR(src);
     ARM_COMPUTE_ERROR_THROW_ON(validate_arguments(src, dst, activation_info));
     const auto uk = CpuActivationKernel::get_implementation(ActivationDataTypeISASelectorData{ src->data_type(), CPUInfo::get().get_cpu_model(), CPUInfo::get().get_isa(), activation_info.activation() });
     if(dst != nullptr)
     {
         // dst auto inizialitation if not yet initialized
         auto_init_if_empty(*dst, *src->clone());
     }
     ARM_COMPUTE_ERROR_ON_NULLPTR(uk);
     _run_method = uk->ukernel;
     _name       = std::string("CpuActivationKernel").append("/").append(uk->name);
 #ifdef __aarch64__
     if(ActivationLayerInfo::is_lut_supported(activation_info.activation(), src->data_type()))
     {
         activation_info.init_lut(src->data_type(), src->quantization_info().uniform(), (dst) ? dst->quantization_info().uniform() : src->quantization_info().uniform());
     }
 #endif // __aarch64__
     _act_info = activation_info;
     Window win;
     // Use squashed window
     std::tie(win, _split_dimension) = calculate_squashed_or_max_window(*src);
     ICPPKernel::configure(win);
 }
get_available_kernels()
const std::vector< CpuActivationKernel::ActivationKernel > & get_available_kernels () static
Definition at line 271 of file CpuActivationKernel.cpp.
 {
     return available_kernels;
 }
get_mws()
size_t get_mws (const CPUInfo & platform, size_t thread_count) const override virtual
Return minimum workload size of the relevant kernel.
Parameters
[in] platform The CPU platform used to create the context.
[in] thread_count Number of threads in the execution.
Returns
[out] small_network_mws Minimum workload size for requsted configuration.
Reimplemented from ICPPKernel.
Definition at line 231 of file CpuActivationKernel.cpp.
References ARM_COMPUTE_UNUSED, ICPPKernel::default_mws, and Window::DimX.
 {
     ARM_COMPUTE_UNUSED(thread_count);
     ARM_COMPUTE_UNUSED(platform);
     if(_split_dimension == Window::DimX)
     {
         // Don't split the work load too small if the tensor has been reinterpreted as 1D.
         // This number is loosely chosen as threading overhead in each platform varies wildly.
         return 1536;
     }
     return default_mws;
 }
get_split_dimension_hint()
size_t get_split_dimension_hint () const inline
Get the preferred dimension in which the scheduler splits the work into multiple jobs.
Returns
The split dimension hint.
Definition at line 80 of file CpuActivationKernel.h.
     {
         return _split_dimension;
     }
name()
const char * name () const override virtual
Name of the kernel.
Returns
Kernel name
Implements ICPPKernel.
Definition at line 266 of file CpuActivationKernel.cpp.
 {
     return _name.c_str();
 }
run_op()
void run_op (ITensorPack & tensors, const Window & window, const ThreadInfo & info) override virtual
Execute the kernel on the passed window.
Warning
If is_parallelisable() returns false then the passed window must be equal to window()
Note
The window has to be a region within the window returned by the window() method
The width of the window has to be a multiple of num_elems_processed_per_iteration().
Parameters
[in] tensors A vector containing the tensors to operate on.
[in] window Region on which to execute the kernel. (Must be a region of the window returned by window())
[in] info Info about executing thread and CPU.
Reimplemented from ICPPKernel.
Definition at line 245 of file CpuActivationKernel.cpp.
References arm_compute::ACL_DST, arm_compute::ACL_SRC, ARM_COMPUTE_ERROR_ON, ARM_COMPUTE_ERROR_ON_INVALID_SUBWINDOW, ARM_COMPUTE_ERROR_ON_UNCONFIGURED_KERNEL, ARM_COMPUTE_UNUSED, ITensorPack::empty(), ActivationLayerInfo::enabled(), ITensorPack::get_const_tensor(), ITensorPack::get_tensor(), and IKernel::window().
 {
     // Early exit on disabled activation
     if(!_act_info.enabled())
     {
         return;
     }
     ARM_COMPUTE_UNUSED(info);
     ARM_COMPUTE_ERROR_ON_UNCONFIGURED_KERNEL(this);
     ARM_COMPUTE_ERROR_ON_INVALID_SUBWINDOW(IKernel::window(), window);
     ARM_COMPUTE_ERROR_ON(tensors.empty());
     ARM_COMPUTE_ERROR_ON(_run_method == nullptr);
     const ITensor *src = tensors.get_const_tensor(TensorType::ACL_SRC);
     ITensor       *dst = tensors.get_tensor(TensorType::ACL_DST);
     _run_method(src, dst, _act_info, window);
 }
validate()
Status validate (const ITensorInfo * src, const ITensorInfo * dst, const ActivationLayerInfo & act_info) static
Static function to check if given info will lead to a valid configuration.
Similar to CpuActivationKernel::configure()
Returns
a status
Definition at line 222 of file CpuActivationKernel.cpp.
References ARM_COMPUTE_RETURN_ON_ERROR, ARM_COMPUTE_UNUSED, ICloneable< T >::clone(), arm_compute::cpu::kernels::validate_and_configure_window(), and arm_compute::cpu::kernels::validate_arguments().
Referenced by CpuActivation::validate().
 {
     ARM_COMPUTE_UNUSED(act_info);
     ARM_COMPUTE_RETURN_ON_ERROR(validate_arguments(src, dst, act_info));
     ARM_COMPUTE_RETURN_ON_ERROR(validate_and_configure_window(src->clone().get(), (dst != nullptr) ? dst->clone().get() : nullptr).first);
     return Status{};
 }
The documentation for this class was generated from the following files:
src/cpu/kernels/CpuActivationKernel.h
src/cpu/kernels/CpuActivationKernel.cpp