Compute Library: ClQueue Class Reference
ClQueue Class Reference final
OpenCL queue implementation class.
#include <ClQueue.h>
Public Member Functions
ClQueue (IContext *ctx, const AclQueueOptions *options)
Construct a new CpuQueue object.
arm_compute::CLScheduler & scheduler ()
Return legacy scheduler.
::cl::CommandQueue cl_queue ()
Underlying cl command queue accessor.
bool set_cl_queue (::cl::CommandQueue queue)
Update/inject an underlying cl command queue object.
StatusCode finish () override
Public Member Functions inherited from IQueue
IQueue (IContext *ctx)
Explict Operator Constructor.
virtual ~IQueue ()
Destructor.
bool is_valid () const
Checks if a queue is valid.
Additional Inherited Members
Data Fields inherited from AclQueue_
arm_compute::detail::Header header { arm_compute::detail::ObjectType::Queue, nullptr }
Detailed Description
OpenCL queue implementation class.
Definition at line 43 of file ClQueue.h.
Constructor & Destructor Documentation
ClQueue()
ClQueue (IContext * ctx, const AclQueueOptions * options)
Construct a new CpuQueue object.
Parameters
[in] ctx Context to be used
[in] options Command queue options
Definition at line 71 of file ClQueue.cpp.
     : IQueue(ctx), _tuner(nullptr)
 {
     _tuner = populate_tuner(options);
 }
Member Function Documentation
cl_queue()
cl::CommandQueue cl_queue ()
Underlying cl command queue accessor.
Returns
the cl command queue used
Definition at line 82 of file ClQueue.cpp.
References CLScheduler::get(), and CLScheduler::queue().
 {
     return arm_compute::CLScheduler::get().queue();
 }
finish()
StatusCode finish () override virtual
Implements IQueue.
Definition at line 94 of file ClQueue.cpp.
References CLScheduler::get(), CLScheduler::queue(), and arm_compute::Success.
 {
     arm_compute::CLScheduler::get().queue().finish();
     return StatusCode::Success;
 }
scheduler()
arm_compute::CLScheduler & scheduler ()
Return legacy scheduler.
Returns
arm_compute::IScheduler&
Definition at line 77 of file ClQueue.cpp.
References CLScheduler::get().
 {
     return arm_compute::CLScheduler::get();
 }
set_cl_queue()
bool set_cl_queue (::cl::CommandQueue queue)
Update/inject an underlying cl command queue object.
Warning
Command queue needs to come from the same context as the AclQueue
Parameters
[in] queue Underlying cl command queue to be used
Returns
true if the queue was set successfully else falseS
Definition at line 87 of file ClQueue.cpp.
References CLScheduler::get(), and CLScheduler::set_queue().
 {
     // TODO: Check queue is from the same context
     arm_compute::CLScheduler::get().set_queue(queue);
     return true;
 }
The documentation for this class was generated from the following files:
src/gpu/cl/ClQueue.h
src/gpu/cl/ClQueue.cpp