Compute Library: RandomAccessor Class Reference
RandomAccessor Class Reference final
Random accessor class.
#include <GraphUtils.h>
Public Member Functions
RandomAccessor (PixelValue lower, PixelValue upper, const std::random_device::result_type seed=0)
Constructor.
RandomAccessor (RandomAccessor &&)=default
Allows instances to move constructed.
bool access_tensor (ITensor &tensor) override
Interface to be implemented to access a given tensor.
Public Member Functions inherited from ITensorAccessor
virtual ~ITensorAccessor ()=default
Default virtual destructor.
virtual bool access_tensor_data ()
Returns true if the tensor data is being accessed.
Detailed Description
Random accessor class.
Definition at line 407 of file GraphUtils.h.
Constructor & Destructor Documentation
RandomAccessor() [1/2]
RandomAccessor (PixelValue lower, PixelValue upper, const std::random_device::result_type seed = 0)
Constructor.
Parameters
[in] lower Lower bound value.
[in] upper Upper bound value.
[in] seed (Optional) Seed used to initialise the random number generator.
Definition at line 666 of file GraphUtils.cpp.
References ITensor::buffer(), arm_compute::test::validation::distribution(), ITensorInfo::element_size(), BorderSize::empty(), arm_compute::execute_window_loop(), ITensor::info(), offset(), ITensorInfo::padding(), ITensor::ptr_to_element(), tensor, ITensorInfo::tensor_shape(), ITensorInfo::total_size(), and Window::use_tensor_dimensions().
     : _lower(lower), _upper(upper), _seed(seed)
 {
 }
RandomAccessor() [2/2]
RandomAccessor (RandomAccessor &&) default
Allows instances to move constructed.
Member Function Documentation
access_tensor()
bool access_tensor (ITensor & tensor) override virtual
Interface to be implemented to access a given tensor.
Parameters
[in] tensor Tensor to be accessed
Returns
True if access is successful else false
Implements ITensorAccessor.
Definition at line 698 of file GraphUtils.cpp.
References ARM_COMPUTE_ERROR, ITensorInfo::data_type(), arm_compute::F16, arm_compute::F32, arm_compute::F64, PixelValue::get(), ITensor::info(), arm_compute::QASYMM8, arm_compute::S16, arm_compute::S32, arm_compute::S64, arm_compute::S8, tensor, arm_compute::U16, arm_compute::U32, arm_compute::U64, and arm_compute::U8.
 {
     switch(tensor.info()->data_type())
     {
         case DataType::QASYMM8:
         case DataType::U8:
         {
             std::uniform_int_distribution<uint8_t> distribution_u8(_lower.get<uint8_t>(), _upper.get<uint8_t>());
             fill<uint8_t>(tensor, distribution_u8);
             break;
         }
         case DataType::S8:
         {
             std::uniform_int_distribution<int8_t> distribution_s8(_lower.get<int8_t>(), _upper.get<int8_t>());
             fill<int8_t>(tensor, distribution_s8);
             break;
         }
         case DataType::U16:
         {
             std::uniform_int_distribution<uint16_t> distribution_u16(_lower.get<uint16_t>(), _upper.get<uint16_t>());
             fill<uint16_t>(tensor, distribution_u16);
             break;
         }
         case DataType::S16:
         {
             std::uniform_int_distribution<int16_t> distribution_s16(_lower.get<int16_t>(), _upper.get<int16_t>());
             fill<int16_t>(tensor, distribution_s16);
             break;
         }
         case DataType::U32:
         {
             std::uniform_int_distribution<uint32_t> distribution_u32(_lower.get<uint32_t>(), _upper.get<uint32_t>());
             fill<uint32_t>(tensor, distribution_u32);
             break;
         }
         case DataType::S32:
         {
             std::uniform_int_distribution<int32_t> distribution_s32(_lower.get<int32_t>(), _upper.get<int32_t>());
             fill<int32_t>(tensor, distribution_s32);
             break;
         }
         case DataType::U64:
         {
             std::uniform_int_distribution<uint64_t> distribution_u64(_lower.get<uint64_t>(), _upper.get<uint64_t>());
             fill<uint64_t>(tensor, distribution_u64);
             break;
         }
         case DataType::S64:
         {
             std::uniform_int_distribution<int64_t> distribution_s64(_lower.get<int64_t>(), _upper.get<int64_t>());
             fill<int64_t>(tensor, distribution_s64);
             break;
         }
         case DataType::F16:
         {
             arm_compute::utils::uniform_real_distribution_16bit<half> distribution_f16(_lower.get<float>(), _upper.get<float>());
             fill<half>(tensor, distribution_f16);
             break;
         }
         case DataType::F32:
         {
             std::uniform_real_distribution<float> distribution_f32(_lower.get<float>(), _upper.get<float>());
             fill<float>(tensor, distribution_f32);
             break;
         }
         case DataType::F64:
         {
             std::uniform_real_distribution<double> distribution_f64(_lower.get<double>(), _upper.get<double>());
             fill<double>(tensor, distribution_f64);
             break;
         }
         default:
             ARM_COMPUTE_ERROR("NOT SUPPORTED!");
     }
     return true;
 }
The documentation for this class was generated from the following files:
utils/GraphUtils.h
utils/GraphUtils.cpp