Compute Library: GpuCkwStore Class Reference
GpuCkwStore Class Reference
An interface used by ClTemplateWriter to write source code for a kernel component.
#include <GpuCkwStore.h>
Public Member Functions
GpuCkwStore (ComponentId id, const ArgumentPack< ITensorInfo > &tensors)
Constructor.
ARM_COMPUTE_DISALLOW_COPY_ALLOW_MOVE (GpuCkwStore)
~GpuCkwStore () override=default
Destructor.
virtual void write_component_code (const ComponentGroup &comp_group, GpuCkwVariableTable &vtable, GpuCkwScopedKernelWriter writer) const override
Generate kernel component code.
std::string get_name (const ComponentGroup &comp_group) const override
Generate the name of the component.
Public Member Functions inherited from IGpuCkwComponentDriver
IGpuCkwComponentDriver (ComponentId id, const ArgumentPack< ITensorInfo > &tensors)
Constructor.
virtual ~IGpuCkwComponentDriver ()
Destructor.
ArgumentPack< ITensorInfo > tensors () const
Get tensor arguments.
virtual Window get_window () const
Generate the execution window for the component.
virtual std::string get_tuner_id (const ComponentGroup &comp_group) const
Generate the tuner id of the component This id should capture all the parameters that distinguish one kernel's lws tuning from another.
ComponentId id () const
Get component id.
Additional Inherited Members
Public Types inherited from IGpuCkwComponentDriver
using ComponentGroup = GpuKernelComponentGroup
Detailed Description
An interface used by ClTemplateWriter to write source code for a kernel component.
Definition at line 38 of file GpuCkwStore.h.
Constructor & Destructor Documentation
GpuCkwStore()
GpuCkwStore (ComponentId id, const ArgumentPack< ITensorInfo > & tensors)
Constructor.
Parameters
[in] id Component id
[in] tensors Tensor arguments to the component
Definition at line 39 of file GpuCkwStore.cpp.
     : IGpuCkwComponentDriver{ id, tensors }, _src{}, _dst{}
 {
     _src = this->tensors().get_const_tensor(TensorType::ACL_SRC_0);
     _dst = this->tensors().get_const_tensor(TensorType::ACL_DST_0);
 }
References IGpuCkwComponentDriver::id(), and IGpuCkwComponentDriver::tensors().
~GpuCkwStore()
~GpuCkwStore () override default
Destructor.
Member Function Documentation
ARM_COMPUTE_DISALLOW_COPY_ALLOW_MOVE()
ARM_COMPUTE_DISALLOW_COPY_ALLOW_MOVE (GpuCkwStore)
get_name()
std::string get_name (const ComponentGroup & comp_group) const override virtual
Generate the name of the component.
This will be concatenated with other components' names to form the name of the kernel
Reimplemented from IGpuCkwComponentDriver.
Definition at line 57 of file GpuCkwStore.cpp.
 {
     ARM_COMPUTE_UNUSED(comp_group);
     return "store";
 }
References ARM_COMPUTE_UNUSED.
write_component_code()
void write_component_code (const ComponentGroup & comp_group, GpuCkwVariableTable & vtable, GpuCkwScopedKernelWriter writer) const override virtual
Generate kernel component code.
Parameters
[in] comp_group Component group of which the component is a part of
[in,out] vtable Table of variables declared by each component
[in,out] writer CKW writer that writes code scoped to this kernel component.
                       @note @p writer can only be passed via value since the new scope is created in the copy constructor
Implements IGpuCkwComponentDriver.
Definition at line 45 of file GpuCkwStore.cpp.
 {
     auto src = vtable.declare_variable(comp_group, writer, _src, TensorStorageType::ClBufferUint8Ptr, "src");
     auto dst = vtable.declare_variable(comp_group, writer, _dst, TensorStorageType::ClBufferUint8Ptr, "dst");
     auto       &src_tile   = src->tile();
     const auto &sampler    = src->tile_sampler();
     auto       &dst_tensor = dst->tensor();
     writer->op_store(dst_tensor, src_tile, sampler);
 }
References GpuCkwVariableTable::declare_variable(), arm_compute::test::validation::dst, and arm_compute::test::validation::src.
The documentation for this class was generated from the following files:
src/dynamic_fusion/sketch/gpu/ckw_driver/components/GpuCkwStore.h
src/dynamic_fusion/sketch/gpu/ckw_driver/components/GpuCkwStore.cpp