Compute Library: format_code Namespace Reference
format_code Namespace Reference
Data Structures
class FormatCodeRun
class GenerateAndroidBP
class OtherChecksRun
Functions
def adjust_copyright_year (copyright_years, curr_year)
def check_copyright (filename)
def check_license (filename)
def run_fix_code_formatting (files="git-head", folder=".", num_threads=1, error_on_diff=True)
Variables
logger = logging.getLogger("format_code")
list exceptions
parser
list file_sources = ["git-diff","git-head","all"]
action
help
nargs
metavar
choices
default
args = parser.parse_args()
logging_level = logging.INFO
level
Function Documentation
adjust_copyright_year()
def format_code.adjust_copyright_year (copyright_years, curr_year)
Definition at line 51 of file format_code.py.
 def adjust_copyright_year(copyright_years, curr_year):
     ret_copyright_year = str()
     # Read last year in the Copyright
     last_year = int(copyright_years[-4:])
     if last_year == curr_year:
         ret_copyright_year = copyright_years
     elif last_year == (curr_year - 1):
         # Create range if latest year on the copyright is the previous
         if len(copyright_years) > 4 and copyright_years[-5] == "-":
             # Range already exists, update year to current
             ret_copyright_year = copyright_years[:-5] + "-" + str(curr_year)
         else:
             # Create a new range
             ret_copyright_year = copyright_years + "-" + str(curr_year)
     else:
         ret_copyright_year = copyright_years + ", " + str(curr_year)
     return ret_copyright_year
References caffe_mnist_image_extractor.str.
Referenced by check_copyright(), and check_license().
check_copyright()
def format_code.check_copyright (filename)
Definition at line 69 of file format_code.py.
 def check_copyright( filename ):
     f = open(filename, "r")
     content = f.readlines()
     f.close()
     f = open(filename, "w")
     year = datetime.datetime.now().year
     ref = open("scripts/copyright_mit.txt","r").readlines()
     # Need to handle python files separately
     if("SConstruct" in filename or "SConscript" in filename):
         start = 2
         if("SConscript" in filename):
             start = 3
         m = re.match("(# Copyright \(c\) )(.*\d{4})( [Arm|ARM].*)", content[start])
         line = m.group(1)
         if m.group(2): # Is there a year already?
             # Yes: adjust accordingly
             line += adjust_copyright_year(m.group(2), year)
         else:
             # No: add current year
             line += str(year)
         line += m.group(3).replace("ARM", "Arm")
         if("SConscript" in filename):
             f.write('#!/usr/bin/python\n')
         f.write('# -*- coding: utf-8 -*-\n\n')
         f.write(line+"\n")
         # Copy the rest of the file's content:
         f.write("".join(content[start + 1:]))
         f.close()
         return
     # This only works until year 9999
     m = re.match("(.*Copyright \(c\) )(.*\d{4})( [Arm|ARM].*)", content[1])
     start =len(ref)+2
     if content[0] != "/*\n" or not m:
         start = 0
         f.write("/*\n * Copyright (c) %d Arm Limited.\n" % year)
     else:
         logger.debug("Found Copyright start")
         logger.debug("\n\t".join([ g or "" for g in m.groups()]))
         line = m.group(1)
         if m.group(2): # Is there a year already?
             # Yes: adjust accordingly
             line += adjust_copyright_year(m.group(2), year)
         else:
             # No: add current year
             line += str(year)
         line += m.group(3).replace("ARM", "Arm")
         f.write("/*\n"+line+"\n")
         logger.debug(line)
     # Write out the rest of the Copyright header:
     for i in range(1, len(ref)):
         line = ref[i]
         f.write(" *")
         if line.rstrip() != "":
             f.write(" %s" % line)
         else:
             f.write("\n")
     f.write(" */\n")
     # Copy the rest of the file's content:
     f.write("".join(content[start:]))
     f.close()
References adjust_copyright_year(), arm_compute.join(), arm_compute::test::validation::reference.range(), and caffe_mnist_image_extractor.str.
check_license()
def format_code.check_license (filename)
Check that the license file is up-to-date
Definition at line 136 of file format_code.py.
 def check_license(filename):
     """
     Check that the license file is up-to-date
     """
     f = open(filename, "r")
     content = f.readlines()
     f.close()
     f = open(filename, "w")
     f.write("".join(content[:2]))
     year = datetime.datetime.now().year
     # This only works until year 9999
     m = re.match("(.*Copyright \(c\) )(.*\d{4})( [Arm|ARM].*)", content[2])
     if not m:
         f.write("Copyright (c) {} Arm Limited\n".format(year))
     else:
         updated_year = adjust_copyright_year(m.group(2), year)
         f.write("Copyright (c) {} Arm Limited\n".format(updated_year))
     # Copy the rest of the file's content:
     f.write("".join(content[3:]))
     f.close()
References adjust_copyright_year(), and arm_compute.join().
run_fix_code_formatting()
def format_code.run_fix_code_formatting (files = "git-head", folder = ".", num_threads = 1, error_on_diff = True)
Definition at line 369 of file format_code.py.
 def run_fix_code_formatting( files="git-head", folder=".", num_threads=1, error_on_diff=True):
     try:
         retval = 0
         # Genereate Android.bp file and test it
         gen_android_bp = GenerateAndroidBP(folder)
         gen_android_bp.run()
         to_check, skip_copyright = FormatCodeRun.get_files(folder, files)
         other_checks = OtherChecksRun(folder,error_on_diff, files)
         other_checks.run()
         logger.debug(to_check)
         num_files = len(to_check)
         per_thread = max( num_files / num_threads,1)
         start=0
         logger.info("Files to format:\n\t%s" % "\n\t".join(to_check))
         for i in range(num_threads):
             if i == num_threads -1:
                 end = num_files
             else:
                 end= min(start+per_thread, num_files)
             sub = to_check[start:end]
             logger.debug("[%d] [%d,%d] %s" % (i, start, end, sub))
             start = end
             format_code_run = FormatCodeRun(sub, folder, skip_copyright=skip_copyright)
             format_code_run.run()
         return retval
     except Exception as e:
         logger.error("Exception caught in run_fix_code_formatting: %s" % e)
         return -1
References arm_compute.join(), and arm_compute::test::validation::reference.range().
Variable Documentation
action
action
Definition at line 410 of file format_code.py.
args
args = parser.parse_args()
Definition at line 415 of file format_code.py.
choices
choices
Definition at line 412 of file format_code.py.
default
default
Definition at line 412 of file format_code.py.
exceptions
list exceptions
Initial value:
 =  [
     "src/core/NEON/kernels/assembly/gemm",
     "src/core/NEON/kernels/assembly/arm",
     "/winograd/",
     "/convolution/",
     "/arm_gemm/",
     "/arm_conv/",
     "SConscript",
     "SConstruct"
 ]
Definition at line 40 of file format_code.py.
file_sources
file_sources = ["git-diff","git-head","all"]
Definition at line 409 of file format_code.py.
help
help
Definition at line 410 of file format_code.py.
level
level
Definition at line 421 of file format_code.py.
logger
logger = logging.getLogger("format_code")
Definition at line 37 of file format_code.py.
logging_level
logging_level = logging.INFO
Definition at line 417 of file format_code.py.
metavar
metavar
Definition at line 412 of file format_code.py.
nargs
nargs
Definition at line 412 of file format_code.py.
parser
parser
Initial value:
 =  argparse.ArgumentParser(
             formatter_class=argparse.RawDescriptionHelpFormatter,
             description="Build & run pre-commit tests",
     )
Definition at line 404 of file format_code.py.