Compute Library: arm_compute::cl_matmul Namespace Reference
arm_compute::cl_matmul Namespace Reference
Data Structures
class ClMatMulNativeConfigArray
Basic container for the OpenCL MatMul Native configuration functions.
class ClMatMulNativeDefaultConfigValhall
Valhall based OpenCL matmul configuration.
class ClMatMulNativeKernelConfigurationFactory
ClMatMul configuration factory class.
class IClMatMulNativeKernelConfig
Basic interface for the matmul native kernel configuration.
Typedefs
using MatMulNativeConfigsMatrix = std::vector< std::vector< int32_t > >
Functions
MatMulKernelInfo select_info (const MatMulKernelInfo &info0, const MatMulKernelInfo &info1, unsigned int m, unsigned int n, unsigned int k, unsigned int b, DataType data_type, bool rhs_lock_padding)
This function accepts two MatMulKernelInfo objects where only the first can be with cl_image2d support enabled.
MatMulKernelInfo find_info (const MatMulNativeConfigsMatrix &configs, bool adj_lhs, bool adj_rhs, unsigned int m, unsigned int n, unsigned int k, unsigned int b)
Find the preferred configurations for the MatMul Native kernel using the MatMulNativeConfigsMatrix provided by the user.
Typedef Documentation
MatMulNativeConfigsMatrix
using MatMulNativeConfigsMatrix = std::vector<std::vector<int32_t> >
Definition at line 36 of file ClMatMulNativeHelpers.h.
Function Documentation
find_info()
MatMulKernelInfo find_info (const MatMulNativeConfigsMatrix & configs, bool adj_lhs, bool adj_rhs, unsigned int m, unsigned int n, unsigned int k, unsigned int b)
Find the preferred configurations for the MatMul Native kernel using the MatMulNativeConfigsMatrix provided by the user.
Parameters
[in] configs List of best configurations for a limited number of MatMul shapes
[in] adj_lhs Adjoint LHS flag value
[in] adj_rhs Adjoint RHS flag value
[in] m Number of rows (M) of the LHS matrix
[in] n Number of columns (N) in the RHS matrix not reshaped
[in] k Number of rows (K) in the RHS matrix not reshaped
[in] b Batch size
Returns
MatMulKernelInfo
Definition at line 70 of file ClMatMulNativeHelpers.cpp.
References MatMulKernelInfo::adj_lhs, MatMulKernelInfo::adj_rhs, ARM_COMPUTE_ERROR_ON, ARM_COMPUTE_ERROR_ON_MSG, ARM_COMPUTE_UNUSED, MatMulKernelInfo::export_rhs_to_cl_image, MatMulKernelInfo::k0, MatMulKernelInfo::m0, MatMulKernelInfo::n0, and arm_compute::utils::cast::U.
Referenced by ClMatMulNativeDefaultConfigValhall::configure().
 {
     size_t min_acc = std::numeric_limits<size_t>::max();
     size_t min_idx = 0;
     ARM_COMPUTE_ERROR_ON(configs.size() == 0);
     const size_t num_rows = configs.size();
     const size_t num_cols = configs[0].size();
     ARM_COMPUTE_ERROR_ON_MSG(num_cols != 8U, "The entry should have 8 integer values representing: M, N, K, B, M0, N0. K0, IMG_RHS");
     ARM_COMPUTE_UNUSED(num_cols);
     // Find nearest GeMM workload
     // Note: the workload does not depend on the K dimension
     for(size_t y = 0; y < num_rows; ++y)
     {
         size_t mc0 = static_cast<size_t>(configs[y][0]);
         size_t nc0 = static_cast<size_t>(configs[y][1]);
         size_t kc0 = static_cast<size_t>(configs[y][2]);
         size_t bc0 = static_cast<size_t>(configs[y][3]);
         size_t acc = 0;
         acc += (m - mc0) * (m - mc0);
         acc += (n - nc0) * (n - nc0);
         acc += (k - kc0) * (k - kc0);
         acc += (b - bc0) * (b - bc0);
         acc = std::sqrt(acc);
         if(acc < min_acc)
         {
             min_acc = acc;
             min_idx = y;
         }
     }
     // Get the configuration from the nearest GeMM shape
     MatMulKernelInfo desc;
     desc.adj_lhs                = adj_lhs;
     desc.adj_rhs                = adj_rhs;
     desc.m0                     = configs[min_idx][4];
     desc.n0                     = configs[min_idx][5];
     desc.k0                     = configs[min_idx][6];
     desc.export_rhs_to_cl_image = configs[min_idx][7];
     return desc;
 }
select_info()
MatMulKernelInfo select_info (const MatMulKernelInfo & info0, const MatMulKernelInfo & info1, unsigned int m, unsigned int n, unsigned int k, unsigned int b, DataType data_type, bool rhs_lock_padding)
This function accepts two MatMulKernelInfo objects where only the first can be with cl_image2d support enabled.
The aim of this function is to check whether the first MatMulKernelInfo object is valid. If not, the function will return the second MatMulKernelInfo object. Otherwise, the first one.
Parameters
[in] info0 MatMulKernelInfo with cl_image2d support
[in] info1 MatMulKernelInfo to fall-back if cl_image2d cannot be used
[in] m Number of rows (M) of the LHS matrix
[in] n Number of columns (N) in the RHS matrix not reshaped
[in] k Number of rows (K) in the RHS matrix not reshaped
[in] b Batch size
[in] data_type Data type
[in] rhs_lock_padding Flag used to know whether the RHS paddings are locked
Returns
MatMulKernelInfo
Definition at line 38 of file ClMatMulNativeHelpers.cpp.
References MatMulKernelInfo::adj_lhs, MatMulKernelInfo::adj_rhs, ARM_COMPUTE_ERROR_ON_MSG, MatMulKernelInfo::export_rhs_to_cl_image, arm_compute::test::validation::lhs_info, arm_compute::test::validation::rhs_info, and ClMatMulNativeKernel::validate().
Referenced by ClMatMulNativeDefaultConfigValhall::configure().
 {
     ARM_COMPUTE_ERROR_ON_MSG(info1.export_rhs_to_cl_image == true, "The fallback MatMul configuration cannot have export_to_cl_image = true");
     ARM_COMPUTE_ERROR_ON_MSG(info0.adj_lhs != info1.adj_lhs, "The MatMul configurations must have the same adj_lhs value");
     ARM_COMPUTE_ERROR_ON_MSG(info0.adj_rhs != info1.adj_rhs, "The MatMul configurations must have the same adj_rhs value");
     const bool adj_lhs = info0.adj_lhs;
     const bool adj_rhs = info0.adj_rhs;
     TensorInfo lhs_info = !adj_lhs ? TensorInfo(TensorShape(k, m, b), 1, data_type) : TensorInfo(TensorShape(m, k, b), 1, data_type);
     TensorInfo rhs_info = !adj_rhs ? TensorInfo(TensorShape(n, k, b), 1, data_type) : TensorInfo(TensorShape(k, n, b), 1, data_type);
     TensorInfo dst_info;
     if(rhs_lock_padding == false)
     {
         if(bool(opencl::kernels::ClMatMulNativeKernel::validate(&lhs_info, &rhs_info, &dst_info, info0)))
         {
             return info0;
         }
         else
         {
             return info1;
         }
     }
     else
     {
         return info1;
     }
 }