Compute Library: arm_conv::depthwise Namespace Reference
arm_conv::depthwise Namespace Reference
Namespaces
depthfirst_multiplier
depthwise_depthfirst
interleaves
Data Structures
struct DefaultOutputStage
struct DefaultOutputStage< int8_t >
struct DefaultOutputStage< uint8_t >
struct DefaultTAccum
struct DefaultTAccum< int8_t >
struct DefaultTAccum< uint8_t >
class DepthfirstDriver
class DepthfirstMultiplierStrategy
class DepthfirstMultiplierStrategy< TInput, TWeight, TOutput, int32_t >
class DepthfirstStrategy
class DepthfirstStrategyUntyped
class DepthwiseDepthfirst
class DepthwiseDepthfirstCommon
class DepthwiseDepthfirstGeneric
struct DepthwiseDepthfirstGenericKernelCall
struct DepthwiseDepthfirstGenericKernelCall< arm_gemm::Requantize32 >
struct DepthwiseDepthfirstGenericKernelCall< Nothing >
class DepthwiseDepthfirstMultiplier
class DepthwiseDepthfirstStrategy
class DepthwiseDepthfirstStrategy< TInput, TWeight, TOutput, int32_t >
class DepthwiseDepthfirstStrategyCommon
struct DepthwiseImplementation
class DepthwisePlanar
class GenericDepthfirstKernelStrategy
struct GenericDepthfirstKernelStrategyFunctionType
struct GenericDepthfirstKernelStrategyFunctionType< TInput, TOutput, int32_t >
class GenericDepthfirstMultiplierKernelStrategy
class GenericDepthfirstMultiplierKernelStrategy< TInput, TWeight, TOutput, int32_t >
class GenericDepthfirstMultiplierStrategy
class GenericDepthfirstStrategy
class GenericInputArrayElement
class IDepthfirstStrategy
struct interleave_a64_s8q_3x3_dot
struct interleave_a64_u8q_3x3_dot
class IPlanarStrategy
struct PlanarKernelType
struct PlanarKernelType< TInput, TWeight, TOutput, int32_t, arm_gemm::Requantize32 >
struct PlanarKernelType< TInput, TWeight, TOutput, TAccum, Nothing >
class PlanarStrategy
class sme2_fp16_nhwc_3x3_s1_output2x2_mla_depthfirst
class sme2_fp16_nhwc_3x3_s1_output3x3_mla_depthfirst
class sme2_fp16_nhwc_3x3_s1_output4x4_mla_depthfirst
class sme2_fp16_nhwc_3x3_s2_output2x2_mla_depthfirst
class sme2_fp16_nhwc_5x5_s1_output2x2_mla_depthfirst
class sme2_fp32_planar_3x3_s1_4rows_mla_za
class sme2_fp32_planar_3x3_s2_4rows_mla_za
class sme2_fp32_planar_5x5_s1_4rows_mla_za
class sme2_fp32_planar_5x5_s2_4rows_mla_za
class sme2_fp32bf16fp32_planar_3x3_s1_4rows_dot_za
class sme2_fp32bf16fp32_planar_3x3_s2_4rows_dot_za
class sme2_fp32bf16fp32_planar_5x5_s1_4rows_dot_za
class sme2_fp32bf16fp32_planar_5x5_s2_4rows_dot_za
class sme2_s8q_planar_3x3_s1_4rows_dot_za
class sme2_s8q_planar_3x3_s2_4rows_dot_za
class sme2_s8q_planar_5x5_s1_4rows_dot_za
class sme2_s8q_planar_5x5_s2_4rows_dot_za
class sme2_u8q_planar_3x3_s1_4rows_dot_za
class sme2_u8q_planar_3x3_s2_4rows_dot_za
class sme2_u8q_planar_5x5_s1_4rows_dot_za
class sme2_u8q_planar_5x5_s2_4rows_dot_za
class sme2_u8s8u8q_planar_3x3_s1_4rows_dot_za
class sme2_u8s8u8q_planar_3x3_s2_4rows_dot_za
class sme2_u8s8u8q_planar_5x5_s1_4rows_dot_za
class sme2_u8s8u8q_planar_5x5_s2_4rows_dot_za
struct TensorSpec
Functions
std::tuple< size_t, size_t, size_t, size_t, size_t > get_reduced_view_for_dilation (size_t out_size, size_t in_size, const size_t d, const size_t dilation_factor, const size_t kernel_size, const size_t stride, const size_t orig_pad_before)
template<>
const DepthwiseImplementation< float > * depthwise_implementation_list ()
template UniqueDepthwiseCommon< float > depthwise (const DepthwiseArgs &, const Nothing &)
template std::vector< KernelDescription > get_compatible_kernels< float > (const DepthwiseArgs &, const Nothing &)
template<typename TInput , typename TWeight = TInput, typename TOutput = TInput, class OutputStage = Nothing>
const DepthwiseImplementation< TInput, TWeight, TOutput, OutputStage > * depthwise_implementation_list ()
template<typename TInput , typename TWeight = TInput, typename TOutput = TInput, class OutputStage = Nothing>
bool find_implementation (const DepthwiseArgs &args, const OutputStage &os, const DepthwiseImplementation< TInput, TWeight, TOutput, OutputStage > *&selected)
template<typename TInput , typename TWeight , typename TOutput , class OutputStage >
std::vector< KernelDescription > get_compatible_kernels (const DepthwiseArgs &args, const OutputStage &os)
template<typename TInput , typename TWeight , typename TOutput , class OutputStage >
UniqueDepthwiseCommon< TInput, TWeight, TOutput > depthwise (const DepthwiseArgs &args, const OutputStage &os)
template<>
const DepthwiseImplementation< int8_t, int8_t, int8_t, Requantize32 > * depthwise_implementation_list ()
template UniqueDepthwiseCommon< int8_t, int8_t, int8_t > depthwise (const DepthwiseArgs &, const Requantize32 &)
template std::vector< KernelDescription > get_compatible_kernels< int8_t, int8_t, int8_t, Requantize32 > (const DepthwiseArgs &, const Requantize32 &)
template<>
const DepthwiseImplementation< uint8_t, uint8_t, uint8_t, Requantize32 > * depthwise_implementation_list ()
template std::vector< KernelDescription > get_compatible_kernels< uint8_t, uint8_t, uint8_t, Requantize32 > (const DepthwiseArgs &, const Requantize32 &)
template<>
const DepthwiseImplementation< uint8_t, int8_t, uint8_t, Requantize32 > * depthwise_implementation_list ()
template std::vector< KernelDescription > get_compatible_kernels< uint8_t, int8_t, uint8_t, Requantize32 > (const DepthwiseArgs &, const Requantize32 &)
void sme2_fp16_nhwc_3x3_s1_output2x2_mla_depthfirst_indirect_impl (const __fp16 *const *const input_ptrs, __fp16 *const *const outptrs, const void *params, unsigned int n_channels, const __fp16 activation_min, const __fp16 activation_max)
void sme2_fp16_nhwc_3x3_s1_output2x2_mla_depthfirst_direct_impl (const unsigned int n_tile_rows, const unsigned int n_tile_cols, const __fp16 *inptr, int64_t ld_input_row, int64_t ld_input_col, __fp16 *outptr, int64_t ld_output_row, int64_t ld_output_col, const void *params, unsigned int n_channels, const __fp16 activation_min, const __fp16 activation_max)
void sme2_fp16_nhwc_3x3_s1_output3x3_mla_depthfirst_indirect_impl (const __fp16 *const *const input_ptrs, __fp16 *const *const outptrs, const void *params, unsigned int n_channels, const __fp16 activation_min, const __fp16 activation_max)
void sme2_fp16_nhwc_3x3_s1_output3x3_mla_depthfirst_direct_impl (const unsigned int n_tile_rows, const unsigned int n_tile_cols, const __fp16 *inptr, int64_t ld_input_row, int64_t ld_input_col, __fp16 *outptr, int64_t ld_output_row, int64_t ld_output_col, const void *params, unsigned int n_channels, const __fp16 activation_min, const __fp16 activation_max)
void sme2_fp16_nhwc_3x3_s1_output4x4_mla_depthfirst_indirect_impl (const __fp16 *const *const input_ptrs, __fp16 *const *const outptrs, const void *params, unsigned int n_channels, const __fp16 activation_min, const __fp16 activation_max)
void sme2_fp16_nhwc_3x3_s1_output4x4_mla_depthfirst_direct_impl (const unsigned int n_tile_rows, const unsigned int n_tile_cols, const __fp16 *inptr, int64_t ld_input_row, int64_t ld_input_col, __fp16 *outptr, int64_t ld_output_row, int64_t ld_output_col, const void *params, unsigned int n_channels, const __fp16 activation_min, const __fp16 activation_max)
void sme2_fp16_nhwc_3x3_s2_output2x2_mla_depthfirst_indirect_impl (const __fp16 *const *const input_ptrs, __fp16 *const *const outptrs, const void *params, unsigned int n_channels, const __fp16 activation_min, const __fp16 activation_max)
void sme2_fp16_nhwc_3x3_s2_output2x2_mla_depthfirst_direct_impl (const unsigned int n_tile_rows, const unsigned int n_tile_cols, const __fp16 *inptr, int64_t ld_input_row, int64_t ld_input_col, __fp16 *outptr, int64_t ld_output_row, int64_t ld_output_col, const void *params, unsigned int n_channels, const __fp16 activation_min, const __fp16 activation_max)
void sme2_fp16_nhwc_5x5_s1_output2x2_mla_depthfirst_indirect_impl (const __fp16 *const *const input_ptrs, __fp16 *const *const outptrs, const void *params, unsigned int n_channels, const __fp16 activation_min, const __fp16 activation_max)
void sme2_fp16_nhwc_5x5_s1_output2x2_mla_depthfirst_direct_impl (const unsigned int n_tile_rows, const unsigned int n_tile_cols, const __fp16 *inptr, int64_t ld_input_row, int64_t ld_input_col, __fp16 *outptr, int64_t ld_output_row, int64_t ld_output_col, const void *params, unsigned int n_channels, const __fp16 activation_min, const __fp16 activation_max)
void sme2_fp32_planar_3x3_s1_4rows_mla_za_impl (const float *inptr, size_t ld_in_row, size_t ld_in_col, size_t ld_in_vl, unsigned int pad_top, unsigned int valid_input_rows, unsigned int pad_left, unsigned int valid_input_cols, const float *weights, const float *bias, float **outptrs, const size_t *outlds, const size_t *outvllds, unsigned int output_cols, unsigned int start_channel, unsigned int valid_channels, float act_min, float act_max)
void sme2_fp32_planar_3x3_s2_4rows_mla_za_impl (const float *inptr, size_t ld_in_row, size_t ld_in_col, size_t ld_in_vl, unsigned int pad_top, unsigned int valid_input_rows, unsigned int pad_left, unsigned int valid_input_cols, const float *weights, const float *bias, float **outptrs, const size_t *outlds, const size_t *outvllds, unsigned int output_cols, unsigned int start_channel, unsigned int valid_channels, float act_min, float act_max)
void sme2_fp32_planar_5x5_s1_4rows_mla_za_impl (const float *inptr, size_t ld_in_row, size_t ld_in_col, size_t ld_in_vl, unsigned int pad_top, unsigned int valid_input_rows, unsigned int pad_left, unsigned int valid_input_cols, const float *weights, const float *bias, float **outptrs, const size_t *outlds, const size_t *outvllds, unsigned int output_cols, unsigned int start_channel, unsigned int valid_channels, float act_min, float act_max)
void sme2_fp32_planar_5x5_s2_4rows_mla_za_impl (const float *inptr, size_t ld_in_row, size_t ld_in_col, size_t ld_in_vl, unsigned int pad_top, unsigned int valid_input_rows, unsigned int pad_left, unsigned int valid_input_cols, const float *weights, const float *bias, float **outptrs, const size_t *outlds, const size_t *outvllds, unsigned int output_cols, unsigned int start_channel, unsigned int valid_channels, float act_min, float act_max)
void sme2_fp32bf16fp32_planar_3x3_s1_4rows_dot_za_impl (const float *inptr, size_t ld_in_row, size_t ld_in_col, size_t ld_in_vl, unsigned int pad_top, unsigned int valid_input_rows, unsigned int pad_left, unsigned int valid_input_cols, const float *weights, const float *bias, float **outptrs, const size_t *outlds, const size_t *outvllds, unsigned int output_cols, unsigned int start_channel, unsigned int valid_channels, float act_min, float act_max)
void sme2_fp32bf16fp32_planar_3x3_s2_4rows_dot_za_impl (const float *inptr, size_t ld_in_row, size_t ld_in_col, size_t ld_in_vl, unsigned int pad_top, unsigned int valid_input_rows, unsigned int pad_left, unsigned int valid_input_cols, const float *weights, const float *bias, float **outptrs, const size_t *outlds, const size_t *outvllds, unsigned int output_cols, unsigned int start_channel, unsigned int valid_channels, float act_min, float act_max)
void sme2_fp32bf16fp32_planar_5x5_s1_4rows_dot_za_impl (const float *inptr, size_t ld_in_row, size_t ld_in_col, size_t ld_in_vl, unsigned int pad_top, unsigned int valid_input_rows, unsigned int pad_left, unsigned int valid_input_cols, const float *weights, const float *bias, float **outptrs, const size_t *outlds, const size_t *outvllds, unsigned int output_cols, unsigned int start_channel, unsigned int valid_channels, float act_min, float act_max)
void sme2_fp32bf16fp32_planar_5x5_s2_4rows_dot_za_impl (const float *inptr, size_t ld_in_row, size_t ld_in_col, size_t ld_in_vl, unsigned int pad_top, unsigned int valid_input_rows, unsigned int pad_left, unsigned int valid_input_cols, const float *weights, const float *bias, float **outptrs, const size_t *outlds, const size_t *outvllds, unsigned int output_cols, unsigned int start_channel, unsigned int valid_channels, float act_min, float act_max)
void sme2_s8q_planar_3x3_s1_4rows_dot_za_impl (const int8_t *inptr, size_t ld_in_row, size_t ld_in_col, size_t ld_in_vl, unsigned int pad_top, unsigned int valid_input_rows, unsigned int pad_left, unsigned int valid_input_cols, const int8_t *weights, int8_t **outptrs, const size_t *outlds, const size_t *outvllds, unsigned int output_cols, unsigned int start_channel, unsigned int valid_channels, const arm_gemm::Requantize32 &qp)
void sme2_s8q_planar_3x3_s2_4rows_dot_za_impl (const int8_t *inptr, size_t ld_in_row, size_t ld_in_col, size_t ld_in_vl, unsigned int pad_top, unsigned int valid_input_rows, unsigned int pad_left, unsigned int valid_input_cols, const int8_t *weights, int8_t **outptrs, const size_t *outlds, const size_t *outvllds, unsigned int output_cols, unsigned int start_channel, unsigned int valid_channels, const arm_gemm::Requantize32 &qp)
void sme2_s8q_planar_5x5_s1_4rows_dot_za_impl (const int8_t *inptr, size_t ld_in_row, size_t ld_in_col, size_t ld_in_vl, unsigned int pad_top, unsigned int valid_input_rows, unsigned int pad_left, unsigned int valid_input_cols, const int8_t *weights, int8_t **outptrs, const size_t *outlds, const size_t *outvllds, unsigned int output_cols, unsigned int start_channel, unsigned int valid_channels, const arm_gemm::Requantize32 &qp)
void sme2_s8q_planar_5x5_s2_4rows_dot_za_impl (const int8_t *inptr, size_t ld_in_row, size_t ld_in_col, size_t ld_in_vl, unsigned int pad_top, unsigned int valid_input_rows, unsigned int pad_left, unsigned int valid_input_cols, const int8_t *weights, int8_t **outptrs, const size_t *outlds, const size_t *outvllds, unsigned int output_cols, unsigned int start_channel, unsigned int valid_channels, const arm_gemm::Requantize32 &qp)
void sme2_u8q_planar_3x3_s1_4rows_dot_za_impl (const uint8_t *inptr, size_t ld_in_row, size_t ld_in_col, size_t ld_in_vl, unsigned int pad_top, unsigned int valid_input_rows, unsigned int pad_left, unsigned int valid_input_cols, const uint8_t *weights, uint8_t **outptrs, const size_t *outlds, const size_t *outvllds, unsigned int output_cols, unsigned int start_channel, unsigned int valid_channels, const arm_gemm::Requantize32 &qp)
void sme2_u8q_planar_3x3_s2_4rows_dot_za_impl (const uint8_t *inptr, size_t ld_in_row, size_t ld_in_col, size_t ld_in_vl, unsigned int pad_top, unsigned int valid_input_rows, unsigned int pad_left, unsigned int valid_input_cols, const uint8_t *weights, uint8_t **outptrs, const size_t *outlds, const size_t *outvllds, unsigned int output_cols, unsigned int start_channel, unsigned int valid_channels, const arm_gemm::Requantize32 &qp)
void sme2_u8q_planar_5x5_s1_4rows_dot_za_impl (const uint8_t *inptr, size_t ld_in_row, size_t ld_in_col, size_t ld_in_vl, unsigned int pad_top, unsigned int valid_input_rows, unsigned int pad_left, unsigned int valid_input_cols, const uint8_t *weights, uint8_t **outptrs, const size_t *outlds, const size_t *outvllds, unsigned int output_cols, unsigned int start_channel, unsigned int valid_channels, const arm_gemm::Requantize32 &qp)
void sme2_u8q_planar_5x5_s2_4rows_dot_za_impl (const uint8_t *inptr, size_t ld_in_row, size_t ld_in_col, size_t ld_in_vl, unsigned int pad_top, unsigned int valid_input_rows, unsigned int pad_left, unsigned int valid_input_cols, const uint8_t *weights, uint8_t **outptrs, const size_t *outlds, const size_t *outvllds, unsigned int output_cols, unsigned int start_channel, unsigned int valid_channels, const arm_gemm::Requantize32 &qp)
void sme2_u8s8u8q_planar_3x3_s1_4rows_dot_za_impl (const uint8_t *inptr, size_t ld_in_row, size_t ld_in_col, size_t ld_in_vl, unsigned int pad_top, unsigned int valid_input_rows, unsigned int pad_left, unsigned int valid_input_cols, const int8_t *weights, uint8_t **outptrs, const size_t *outlds, const size_t *outvllds, unsigned int output_cols, unsigned int start_channel, unsigned int valid_channels, const arm_gemm::Requantize32 &qp)
void sme2_u8s8u8q_planar_3x3_s2_4rows_dot_za_impl (const uint8_t *inptr, size_t ld_in_row, size_t ld_in_col, size_t ld_in_vl, unsigned int pad_top, unsigned int valid_input_rows, unsigned int pad_left, unsigned int valid_input_cols, const int8_t *weights, uint8_t **outptrs, const size_t *outlds, const size_t *outvllds, unsigned int output_cols, unsigned int start_channel, unsigned int valid_channels, const arm_gemm::Requantize32 &qp)
void sme2_u8s8u8q_planar_5x5_s1_4rows_dot_za_impl (const uint8_t *inptr, size_t ld_in_row, size_t ld_in_col, size_t ld_in_vl, unsigned int pad_top, unsigned int valid_input_rows, unsigned int pad_left, unsigned int valid_input_cols, const int8_t *weights, uint8_t **outptrs, const size_t *outlds, const size_t *outvllds, unsigned int output_cols, unsigned int start_channel, unsigned int valid_channels, const arm_gemm::Requantize32 &qp)
void sme2_u8s8u8q_planar_5x5_s2_4rows_dot_za_impl (const uint8_t *inptr, size_t ld_in_row, size_t ld_in_col, size_t ld_in_vl, unsigned int pad_top, unsigned int valid_input_rows, unsigned int pad_left, unsigned int valid_input_cols, const int8_t *weights, uint8_t **outptrs, const size_t *outlds, const size_t *outvllds, unsigned int output_cols, unsigned int start_channel, unsigned int valid_channels, const arm_gemm::Requantize32 &qp)
Function Documentation
depthwise() [1/3]
UniqueDepthwiseCommon<TInput, TWeight, TOutput> arm_conv::depthwise::depthwise (const DepthwiseArgs & args, const OutputStage & os)
Definition at line 137 of file depthwise_implementation.hpp.
References GemmTuner::args, and DepthwiseImplementation< TInput, TWeight, TOutput, OutputStage >::get_instance().
 {
   const DepthwiseImplementation<TInput, TWeight, TOutput, OutputStage> *impl = nullptr;
   const bool success = find_implementation<TInput, TWeight, TOutput, OutputStage>(args, os, impl);
   return UniqueDepthwiseCommon<TInput, TWeight, TOutput>(success ? impl->get_instance(args, os) : nullptr);
 }
depthwise() [2/3]
template UniqueDepthwiseCommon< uint8_t, int8_t, uint8_t > depthwise (const DepthwiseArgs & , const Requantize32 &)
depthwise() [3/3]
template UniqueDepthwiseCommon<float> arm_conv::depthwise::depthwise (const DepthwiseArgs & , const Nothing &)
Referenced by depthwise_implementation_list(), and generic_pack().
depthwise_implementation_list() [1/5]
const DepthwiseImplementation<TInput, TWeight, TOutput, OutputStage>* arm_conv::depthwise::depthwise_implementation_list ()
Definition at line 491 of file depthwise_fp32.cpp.
References depthwise(), get_compatible_kernels< float >(), get_compatible_kernels< int8_t, int8_t, int8_t, Requantize32 >(), get_compatible_kernels< uint8_t, int8_t, uint8_t, Requantize32 >(), and get_compatible_kernels< uint8_t, uint8_t, uint8_t, Requantize32 >().
Referenced by DepthwiseImplementation< TInput, TWeight, TOutput, OutputStage >::get_instance().
 {
   return depthwise_fp32_methods;
 }
depthwise_implementation_list() [2/5]
const DepthwiseImplementation<uint8_t, int8_t, uint8_t, Requantize32>* arm_conv::depthwise::depthwise_implementation_list ()
Definition at line 221 of file depthwise_u8s8u8q.cpp.
References depthwise(), get_compatible_kernels< float >(), and get_compatible_kernels< uint8_t, int8_t, uint8_t, Requantize32 >().
 {
   return depthwise_u8q_methods;
 }
depthwise_implementation_list() [3/5]
const DepthwiseImplementation<int8_t, int8_t, int8_t, Requantize32>* arm_conv::depthwise::depthwise_implementation_list ()
Definition at line 347 of file depthwise_s8q.cpp.
References depthwise(), and get_compatible_kernels< int8_t, int8_t, int8_t, Requantize32 >().
 {
   return depthwise_s8q_methods;
 }
depthwise_implementation_list() [4/5]
const DepthwiseImplementation<uint8_t, uint8_t, uint8_t, Requantize32>* arm_conv::depthwise::depthwise_implementation_list ()
Definition at line 354 of file depthwise_u8q.cpp.
References depthwise(), and get_compatible_kernels< uint8_t, uint8_t, uint8_t, Requantize32 >().
 {
   return depthwise_u8q_methods;
 }
depthwise_implementation_list() [5/5]
const DepthwiseImplementation<float>* arm_conv::depthwise::depthwise_implementation_list ()
Definition at line 491 of file depthwise_fp32.cpp.
Referenced by DepthwiseImplementation< TInput, TWeight, TOutput, OutputStage >::get_instance().
 {
   return depthwise_fp32_methods;
 }
find_implementation()
bool arm_conv::depthwise::find_implementation (const DepthwiseArgs & args, const OutputStage & os, const DepthwiseImplementation< TInput, TWeight, TOutput, OutputStage > *& selected)
Definition at line 68 of file depthwise_implementation.hpp.
References DepthwiseImplementation< TInput, TWeight, TOutput, OutputStage >::cycle_estimate.
 {
   selected = nullptr;
   uint64_t best_cycle_estimate = UINT64_MAX;
   const auto *impl = depthwise_implementation_list<TInput, TWeight, TOutput, OutputStage>();
   for (; impl->method != DepthwiseMethod::DEFAULT; impl++)
   {
     const bool has_cfg = (args.config != nullptr);
     const auto &cfg = args.config;
     if (
       !impl->get_is_supported(args, os) ||  // Problem is unsupported
       (has_cfg && cfg->method != DepthwiseMethod::DEFAULT && cfg->method != impl->method) ||
       (has_cfg && cfg->filter != "" && !std::strstr(impl->name, cfg->filter.c_str()))
     )
     {
       continue;
     }
     const auto cycle_estimate = impl->get_cycle_estimate(args, os);
     if (cycle_estimate == 0)
     {
       selected = impl;
       break;
     }
     if (selected == nullptr || cycle_estimate < best_cycle_estimate)
     {
       selected = impl;
       best_cycle_estimate = cycle_estimate;
     }
   }
   return (selected != nullptr);
 }
get_compatible_kernels()
std::vector<KernelDescription> arm_conv::depthwise::get_compatible_kernels (const DepthwiseArgs & args, const OutputStage & os)
Definition at line 111 of file depthwise_implementation.hpp.
References GemmTuner::args, and DepthwiseImplementation< TInput, TWeight, TOutput, OutputStage >::get_cycle_estimate().
 {
   std::vector<KernelDescription> kerns;
   // Find the default implementation so we can flag it accordingly
   const DepthwiseImplementation<TInput, TWeight, TOutput, OutputStage> *default_impl;
   find_implementation<TInput, TWeight, TOutput, OutputStage>(args, os, default_impl);
   for (auto impl = depthwise_implementation_list<TInput, TWeight, TOutput, OutputStage>();
        impl->method != DepthwiseMethod::DEFAULT; impl++)
   {
     if (!impl->get_is_supported(args, os))
     {
       continue;
     }
     kerns.emplace_back(
       impl->method, impl->name, impl == default_impl,
       impl->get_cycle_estimate(args, os)
     );
   }
   return kerns;
 }
get_compatible_kernels< float >()
template std::vector<KernelDescription> arm_conv::depthwise::get_compatible_kernels< float > (const DepthwiseArgs & , const Nothing &)
Referenced by depthwise_implementation_list().
get_compatible_kernels< int8_t, int8_t, int8_t, Requantize32 >()
template std::vector<KernelDescription> arm_conv::depthwise::get_compatible_kernels< int8_t, int8_t, int8_t, Requantize32 > (const DepthwiseArgs & , const Requantize32 &)
Referenced by depthwise_implementation_list().
get_compatible_kernels< uint8_t, int8_t, uint8_t, Requantize32 >()
template std::vector<KernelDescription> arm_conv::depthwise::get_compatible_kernels< uint8_t, int8_t, uint8_t, Requantize32 > (const DepthwiseArgs & , const Requantize32 &)
Referenced by depthwise_implementation_list().
get_compatible_kernels< uint8_t, uint8_t, uint8_t, Requantize32 >()
template std::vector<KernelDescription> arm_conv::depthwise::get_compatible_kernels< uint8_t, uint8_t, uint8_t, Requantize32 > (const DepthwiseArgs & , const Requantize32 &)
Referenced by depthwise_implementation_list().
get_reduced_view_for_dilation()
std::tuple<size_t, size_t, size_t, size_t, size_t> arm_conv::depthwise::get_reduced_view_for_dilation (size_t out_size, size_t in_size, const size_t d, const size_t dilation_factor, const size_t kernel_size, const size_t stride, const size_t orig_pad_before)
Definition at line 34 of file depthwise_common.cpp.
References arm_gemm::iceildiv().
{
     // Get the valid output range
     out_size = iceildiv(out_size - d, dilation_factor);
     // Compute the start offset and the amount of padding which applies to this
     // portion of the work.
     size_t start_pos = d * stride, pad_before = 0;
     if (start_pos < orig_pad_before) {
         pad_before = iceildiv(orig_pad_before - start_pos, dilation_factor);
     }
     start_pos += pad_before * dilation_factor - orig_pad_before;
     // Hence compute the valid input range
     in_size = start_pos < in_size
                   ? iceildiv(in_size - start_pos, dilation_factor)
                   : 0;
     // Finally, compute the "after" padding
     const size_t reqd_input = (out_size - 1) * stride + kernel_size;
     size_t pad_after = 0;
     if (reqd_input > (pad_before + in_size)) {
         pad_after = reqd_input - (pad_before + in_size);
     }
     return std::make_tuple(out_size, in_size, start_pos, pad_before, pad_after);
 }
sme2_fp16_nhwc_3x3_s1_output2x2_mla_depthfirst_direct_impl()
void arm_conv::depthwise::sme2_fp16_nhwc_3x3_s1_output2x2_mla_depthfirst_direct_impl (const unsigned int n_tile_rows, const unsigned int n_tile_cols, const __fp16 * inptr, int64_t ld_input_row, int64_t ld_input_col, __fp16 * outptr, int64_t ld_output_row, int64_t ld_output_col, const void * params, unsigned int n_channels, const __fp16 activation_min, const __fp16 activation_max)
sme2_fp16_nhwc_3x3_s1_output2x2_mla_depthfirst_indirect_impl()
void arm_conv::depthwise::sme2_fp16_nhwc_3x3_s1_output2x2_mla_depthfirst_indirect_impl (const __fp16 *const *const input_ptrs, __fp16 *const *const outptrs, const void * params, unsigned int n_channels, const __fp16 activation_min, const __fp16 activation_max)
sme2_fp16_nhwc_3x3_s1_output3x3_mla_depthfirst_direct_impl()
void arm_conv::depthwise::sme2_fp16_nhwc_3x3_s1_output3x3_mla_depthfirst_direct_impl (const unsigned int n_tile_rows, const unsigned int n_tile_cols, const __fp16 * inptr, int64_t ld_input_row, int64_t ld_input_col, __fp16 * outptr, int64_t ld_output_row, int64_t ld_output_col, const void * params, unsigned int n_channels, const __fp16 activation_min, const __fp16 activation_max)
sme2_fp16_nhwc_3x3_s1_output3x3_mla_depthfirst_indirect_impl()
void arm_conv::depthwise::sme2_fp16_nhwc_3x3_s1_output3x3_mla_depthfirst_indirect_impl (const __fp16 *const *const input_ptrs, __fp16 *const *const outptrs, const void * params, unsigned int n_channels, const __fp16 activation_min, const __fp16 activation_max)
sme2_fp16_nhwc_3x3_s1_output4x4_mla_depthfirst_direct_impl()
void arm_conv::depthwise::sme2_fp16_nhwc_3x3_s1_output4x4_mla_depthfirst_direct_impl (const unsigned int n_tile_rows, const unsigned int n_tile_cols, const __fp16 * inptr, int64_t ld_input_row, int64_t ld_input_col, __fp16 * outptr, int64_t ld_output_row, int64_t ld_output_col, const void * params, unsigned int n_channels, const __fp16 activation_min, const __fp16 activation_max)
sme2_fp16_nhwc_3x3_s1_output4x4_mla_depthfirst_indirect_impl()
void arm_conv::depthwise::sme2_fp16_nhwc_3x3_s1_output4x4_mla_depthfirst_indirect_impl (const __fp16 *const *const input_ptrs, __fp16 *const *const outptrs, const void * params, unsigned int n_channels, const __fp16 activation_min, const __fp16 activation_max)
sme2_fp16_nhwc_3x3_s2_output2x2_mla_depthfirst_direct_impl()
void arm_conv::depthwise::sme2_fp16_nhwc_3x3_s2_output2x2_mla_depthfirst_direct_impl (const unsigned int n_tile_rows, const unsigned int n_tile_cols, const __fp16 * inptr, int64_t ld_input_row, int64_t ld_input_col, __fp16 * outptr, int64_t ld_output_row, int64_t ld_output_col, const void * params, unsigned int n_channels, const __fp16 activation_min, const __fp16 activation_max)
sme2_fp16_nhwc_3x3_s2_output2x2_mla_depthfirst_indirect_impl()
void arm_conv::depthwise::sme2_fp16_nhwc_3x3_s2_output2x2_mla_depthfirst_indirect_impl (const __fp16 *const *const input_ptrs, __fp16 *const *const outptrs, const void * params, unsigned int n_channels, const __fp16 activation_min, const __fp16 activation_max)
sme2_fp16_nhwc_5x5_s1_output2x2_mla_depthfirst_direct_impl()
void arm_conv::depthwise::sme2_fp16_nhwc_5x5_s1_output2x2_mla_depthfirst_direct_impl (const unsigned int n_tile_rows, const unsigned int n_tile_cols, const __fp16 * inptr, int64_t ld_input_row, int64_t ld_input_col, __fp16 * outptr, int64_t ld_output_row, int64_t ld_output_col, const void * params, unsigned int n_channels, const __fp16 activation_min, const __fp16 activation_max)
sme2_fp16_nhwc_5x5_s1_output2x2_mla_depthfirst_indirect_impl()
void arm_conv::depthwise::sme2_fp16_nhwc_5x5_s1_output2x2_mla_depthfirst_indirect_impl (const __fp16 *const *const input_ptrs, __fp16 *const *const outptrs, const void * params, unsigned int n_channels, const __fp16 activation_min, const __fp16 activation_max)
sme2_fp32_planar_3x3_s1_4rows_mla_za_impl()
void arm_conv::depthwise::sme2_fp32_planar_3x3_s1_4rows_mla_za_impl (const float * inptr, size_t ld_in_row, size_t ld_in_col, size_t ld_in_vl, unsigned int pad_top, unsigned int valid_input_rows, unsigned int pad_left, unsigned int valid_input_cols, const float * weights, const float * bias, float ** outptrs, const size_t * outlds, const size_t * outvllds, unsigned int output_cols, unsigned int start_channel, unsigned int valid_channels, float act_min, float act_max)
Referenced by sme2_fp32_planar_3x3_s1_4rows_mla_za::get_kernel().
sme2_fp32_planar_3x3_s2_4rows_mla_za_impl()
void arm_conv::depthwise::sme2_fp32_planar_3x3_s2_4rows_mla_za_impl (const float * inptr, size_t ld_in_row, size_t ld_in_col, size_t ld_in_vl, unsigned int pad_top, unsigned int valid_input_rows, unsigned int pad_left, unsigned int valid_input_cols, const float * weights, const float * bias, float ** outptrs, const size_t * outlds, const size_t * outvllds, unsigned int output_cols, unsigned int start_channel, unsigned int valid_channels, float act_min, float act_max)
Referenced by sme2_fp32_planar_3x3_s2_4rows_mla_za::get_kernel().
sme2_fp32_planar_5x5_s1_4rows_mla_za_impl()
void arm_conv::depthwise::sme2_fp32_planar_5x5_s1_4rows_mla_za_impl (const float * inptr, size_t ld_in_row, size_t ld_in_col, size_t ld_in_vl, unsigned int pad_top, unsigned int valid_input_rows, unsigned int pad_left, unsigned int valid_input_cols, const float * weights, const float * bias, float ** outptrs, const size_t * outlds, const size_t * outvllds, unsigned int output_cols, unsigned int start_channel, unsigned int valid_channels, float act_min, float act_max)
Referenced by sme2_fp32_planar_5x5_s1_4rows_mla_za::get_kernel().
sme2_fp32_planar_5x5_s2_4rows_mla_za_impl()
void arm_conv::depthwise::sme2_fp32_planar_5x5_s2_4rows_mla_za_impl (const float * inptr, size_t ld_in_row, size_t ld_in_col, size_t ld_in_vl, unsigned int pad_top, unsigned int valid_input_rows, unsigned int pad_left, unsigned int valid_input_cols, const float * weights, const float * bias, float ** outptrs, const size_t * outlds, const size_t * outvllds, unsigned int output_cols, unsigned int start_channel, unsigned int valid_channels, float act_min, float act_max)
Referenced by sme2_fp32_planar_5x5_s2_4rows_mla_za::get_kernel().
sme2_fp32bf16fp32_planar_3x3_s1_4rows_dot_za_impl()
void arm_conv::depthwise::sme2_fp32bf16fp32_planar_3x3_s1_4rows_dot_za_impl (const float * inptr, size_t ld_in_row, size_t ld_in_col, size_t ld_in_vl, unsigned int pad_top, unsigned int valid_input_rows, unsigned int pad_left, unsigned int valid_input_cols, const float * weights, const float * bias, float ** outptrs, const size_t * outlds, const size_t * outvllds, unsigned int output_cols, unsigned int start_channel, unsigned int valid_channels, float act_min, float act_max)
Referenced by sme2_fp32bf16fp32_planar_3x3_s1_4rows_dot_za::get_kernel().
sme2_fp32bf16fp32_planar_3x3_s2_4rows_dot_za_impl()
void arm_conv::depthwise::sme2_fp32bf16fp32_planar_3x3_s2_4rows_dot_za_impl (const float * inptr, size_t ld_in_row, size_t ld_in_col, size_t ld_in_vl, unsigned int pad_top, unsigned int valid_input_rows, unsigned int pad_left, unsigned int valid_input_cols, const float * weights, const float * bias, float ** outptrs, const size_t * outlds, const size_t * outvllds, unsigned int output_cols, unsigned int start_channel, unsigned int valid_channels, float act_min, float act_max)
Referenced by sme2_fp32bf16fp32_planar_3x3_s2_4rows_dot_za::get_kernel().
sme2_fp32bf16fp32_planar_5x5_s1_4rows_dot_za_impl()
void arm_conv::depthwise::sme2_fp32bf16fp32_planar_5x5_s1_4rows_dot_za_impl (const float * inptr, size_t ld_in_row, size_t ld_in_col, size_t ld_in_vl, unsigned int pad_top, unsigned int valid_input_rows, unsigned int pad_left, unsigned int valid_input_cols, const float * weights, const float * bias, float ** outptrs, const size_t * outlds, const size_t * outvllds, unsigned int output_cols, unsigned int start_channel, unsigned int valid_channels, float act_min, float act_max)
Referenced by sme2_fp32bf16fp32_planar_5x5_s1_4rows_dot_za::get_kernel().
sme2_fp32bf16fp32_planar_5x5_s2_4rows_dot_za_impl()
void arm_conv::depthwise::sme2_fp32bf16fp32_planar_5x5_s2_4rows_dot_za_impl (const float * inptr, size_t ld_in_row, size_t ld_in_col, size_t ld_in_vl, unsigned int pad_top, unsigned int valid_input_rows, unsigned int pad_left, unsigned int valid_input_cols, const float * weights, const float * bias, float ** outptrs, const size_t * outlds, const size_t * outvllds, unsigned int output_cols, unsigned int start_channel, unsigned int valid_channels, float act_min, float act_max)
Referenced by sme2_fp32bf16fp32_planar_5x5_s2_4rows_dot_za::get_kernel().
sme2_s8q_planar_3x3_s1_4rows_dot_za_impl()
void arm_conv::depthwise::sme2_s8q_planar_3x3_s1_4rows_dot_za_impl (const int8_t * inptr, size_t ld_in_row, size_t ld_in_col, size_t ld_in_vl, unsigned int pad_top, unsigned int valid_input_rows, unsigned int pad_left, unsigned int valid_input_cols, const int8_t * weights, int8_t ** outptrs, const size_t * outlds, const size_t * outvllds, unsigned int output_cols, unsigned int start_channel, unsigned int valid_channels, const arm_gemm::Requantize32 & qp)
Referenced by sme2_s8q_planar_3x3_s1_4rows_dot_za::get_kernel().
sme2_s8q_planar_3x3_s2_4rows_dot_za_impl()
void arm_conv::depthwise::sme2_s8q_planar_3x3_s2_4rows_dot_za_impl (const int8_t * inptr, size_t ld_in_row, size_t ld_in_col, size_t ld_in_vl, unsigned int pad_top, unsigned int valid_input_rows, unsigned int pad_left, unsigned int valid_input_cols, const int8_t * weights, int8_t ** outptrs, const size_t * outlds, const size_t * outvllds, unsigned int output_cols, unsigned int start_channel, unsigned int valid_channels, const arm_gemm::Requantize32 & qp)
Referenced by sme2_s8q_planar_3x3_s2_4rows_dot_za::get_kernel().
sme2_s8q_planar_5x5_s1_4rows_dot_za_impl()
void arm_conv::depthwise::sme2_s8q_planar_5x5_s1_4rows_dot_za_impl (const int8_t * inptr, size_t ld_in_row, size_t ld_in_col, size_t ld_in_vl, unsigned int pad_top, unsigned int valid_input_rows, unsigned int pad_left, unsigned int valid_input_cols, const int8_t * weights, int8_t ** outptrs, const size_t * outlds, const size_t * outvllds, unsigned int output_cols, unsigned int start_channel, unsigned int valid_channels, const arm_gemm::Requantize32 & qp)
Referenced by sme2_s8q_planar_5x5_s1_4rows_dot_za::get_kernel().
sme2_s8q_planar_5x5_s2_4rows_dot_za_impl()
void arm_conv::depthwise::sme2_s8q_planar_5x5_s2_4rows_dot_za_impl (const int8_t * inptr, size_t ld_in_row, size_t ld_in_col, size_t ld_in_vl, unsigned int pad_top, unsigned int valid_input_rows, unsigned int pad_left, unsigned int valid_input_cols, const int8_t * weights, int8_t ** outptrs, const size_t * outlds, const size_t * outvllds, unsigned int output_cols, unsigned int start_channel, unsigned int valid_channels, const arm_gemm::Requantize32 & qp)
Referenced by sme2_s8q_planar_5x5_s2_4rows_dot_za::get_kernel().
sme2_u8q_planar_3x3_s1_4rows_dot_za_impl()
void arm_conv::depthwise::sme2_u8q_planar_3x3_s1_4rows_dot_za_impl (const uint8_t * inptr, size_t ld_in_row, size_t ld_in_col, size_t ld_in_vl, unsigned int pad_top, unsigned int valid_input_rows, unsigned int pad_left, unsigned int valid_input_cols, const uint8_t * weights, uint8_t ** outptrs, const size_t * outlds, const size_t * outvllds, unsigned int output_cols, unsigned int start_channel, unsigned int valid_channels, const arm_gemm::Requantize32 & qp)
Referenced by sme2_u8q_planar_3x3_s1_4rows_dot_za::get_kernel().
sme2_u8q_planar_3x3_s2_4rows_dot_za_impl()
void arm_conv::depthwise::sme2_u8q_planar_3x3_s2_4rows_dot_za_impl (const uint8_t * inptr, size_t ld_in_row, size_t ld_in_col, size_t ld_in_vl, unsigned int pad_top, unsigned int valid_input_rows, unsigned int pad_left, unsigned int valid_input_cols, const uint8_t * weights, uint8_t ** outptrs, const size_t * outlds, const size_t * outvllds, unsigned int output_cols, unsigned int start_channel, unsigned int valid_channels, const arm_gemm::Requantize32 & qp)
Referenced by sme2_u8q_planar_3x3_s2_4rows_dot_za::get_kernel().
sme2_u8q_planar_5x5_s1_4rows_dot_za_impl()
void arm_conv::depthwise::sme2_u8q_planar_5x5_s1_4rows_dot_za_impl (const uint8_t * inptr, size_t ld_in_row, size_t ld_in_col, size_t ld_in_vl, unsigned int pad_top, unsigned int valid_input_rows, unsigned int pad_left, unsigned int valid_input_cols, const uint8_t * weights, uint8_t ** outptrs, const size_t * outlds, const size_t * outvllds, unsigned int output_cols, unsigned int start_channel, unsigned int valid_channels, const arm_gemm::Requantize32 & qp)
Referenced by sme2_u8q_planar_5x5_s1_4rows_dot_za::get_kernel().
sme2_u8q_planar_5x5_s2_4rows_dot_za_impl()
void arm_conv::depthwise::sme2_u8q_planar_5x5_s2_4rows_dot_za_impl (const uint8_t * inptr, size_t ld_in_row, size_t ld_in_col, size_t ld_in_vl, unsigned int pad_top, unsigned int valid_input_rows, unsigned int pad_left, unsigned int valid_input_cols, const uint8_t * weights, uint8_t ** outptrs, const size_t * outlds, const size_t * outvllds, unsigned int output_cols, unsigned int start_channel, unsigned int valid_channels, const arm_gemm::Requantize32 & qp)
Referenced by sme2_u8q_planar_5x5_s2_4rows_dot_za::get_kernel().
sme2_u8s8u8q_planar_3x3_s1_4rows_dot_za_impl()
void arm_conv::depthwise::sme2_u8s8u8q_planar_3x3_s1_4rows_dot_za_impl (const uint8_t * inptr, size_t ld_in_row, size_t ld_in_col, size_t ld_in_vl, unsigned int pad_top, unsigned int valid_input_rows, unsigned int pad_left, unsigned int valid_input_cols, const int8_t * weights, uint8_t ** outptrs, const size_t * outlds, const size_t * outvllds, unsigned int output_cols, unsigned int start_channel, unsigned int valid_channels, const arm_gemm::Requantize32 & qp)
Referenced by sme2_u8s8u8q_planar_3x3_s1_4rows_dot_za::get_kernel().
sme2_u8s8u8q_planar_3x3_s2_4rows_dot_za_impl()
void arm_conv::depthwise::sme2_u8s8u8q_planar_3x3_s2_4rows_dot_za_impl (const uint8_t * inptr, size_t ld_in_row, size_t ld_in_col, size_t ld_in_vl, unsigned int pad_top, unsigned int valid_input_rows, unsigned int pad_left, unsigned int valid_input_cols, const int8_t * weights, uint8_t ** outptrs, const size_t * outlds, const size_t * outvllds, unsigned int output_cols, unsigned int start_channel, unsigned int valid_channels, const arm_gemm::Requantize32 & qp)
Referenced by sme2_u8s8u8q_planar_3x3_s2_4rows_dot_za::get_kernel().
sme2_u8s8u8q_planar_5x5_s1_4rows_dot_za_impl()
void arm_conv::depthwise::sme2_u8s8u8q_planar_5x5_s1_4rows_dot_za_impl (const uint8_t * inptr, size_t ld_in_row, size_t ld_in_col, size_t ld_in_vl, unsigned int pad_top, unsigned int valid_input_rows, unsigned int pad_left, unsigned int valid_input_cols, const int8_t * weights, uint8_t ** outptrs, const size_t * outlds, const size_t * outvllds, unsigned int output_cols, unsigned int start_channel, unsigned int valid_channels, const arm_gemm::Requantize32 & qp)
Referenced by sme2_u8s8u8q_planar_5x5_s1_4rows_dot_za::get_kernel().
sme2_u8s8u8q_planar_5x5_s2_4rows_dot_za_impl()
void arm_conv::depthwise::sme2_u8s8u8q_planar_5x5_s2_4rows_dot_za_impl (const uint8_t * inptr, size_t ld_in_row, size_t ld_in_col, size_t ld_in_vl, unsigned int pad_top, unsigned int valid_input_rows, unsigned int pad_left, unsigned int valid_input_cols, const int8_t * weights, uint8_t ** outptrs, const size_t * outlds, const size_t * outvllds, unsigned int output_cols, unsigned int start_channel, unsigned int valid_channels, const arm_gemm::Requantize32 & qp)
Referenced by sme2_u8s8u8q_planar_5x5_s2_4rows_dot_za::get_kernel().