Compute Library: arm_compute::cl_dwc Namespace Reference
arm_compute::cl_dwc Namespace Reference
Data Structures
class ClDWCNativeConfigArray
Basic container for the OpenCL depthwise convolution configuration functions.
class ClDWCNativeDefaultConfigBifrost
Bifrost based OpenCL depthwise convolution configuration.
class ClDWCNativeDefaultConfigValhall
Valhall based OpenCL depthwise convolution configuration.
class ClDWCNativeKernelConfigurationFactory
ClDWCNativeKernelConfigurationFactory factory class.
class IClDWCNativeKernelConfig
Basic interface for the depthwise convolution kernel configuration.
Functions
bool use_cl_image_for_weights (const ITensorInfo *weights, unsigned int depth_multiplier)
Utility function to know whether we can use the cl image storage for the weights of depthwise convolution to get better performance.
Function Documentation
use_cl_image_for_weights()
bool use_cl_image_for_weights (const ITensorInfo * weights, unsigned int depth_multiplier)
Utility function to know whether we can use the cl image storage for the weights of depthwise convolution to get better performance.
Parameters
[in] weights Weights TensorInfo of the depthwise convolution
[in] depth_multiplier Depth multiplier
Returns
true if the weights of depthwise convolution can be kept in the cl image storage to improve the performance
Definition at line 32 of file ClDWCNativeHeuristicsHelpers.cpp.
References ITensorInfo::data_layout(), arm_compute::export_to_cl_image(), arm_compute::get_data_layout_dimension_index(), arm_compute::HEIGHT, ITensorInfo::tensor_shape(), and arm_compute::WIDTH.
Referenced by ClDWCNativeDefaultConfigValhall::configure().
 {
     // Check whether we can use the cl image with the weights.
     if(!export_to_cl_image(weights))
     {
         return false;
     }
     const size_t idx_w    = get_data_layout_dimension_index(weights->data_layout(), DataLayoutDimension::WIDTH);
     const size_t idx_h    = get_data_layout_dimension_index(weights->data_layout(), DataLayoutDimension::HEIGHT);
     const size_t kernel_w = weights->tensor_shape()[idx_w];
     const size_t kernel_h = weights->tensor_shape()[idx_h];
     // If we can use the cl image storage with the weights, we prefer to use the cl buffer storage in the following cases for performance reasons:
     // 1- When the kernel size is 1x1
     // 2- When the depth multiplier is greater than 1 and not multiple of 4.
     if((kernel_w == 1) && (kernel_h == 1))
     {
         return false;
     }
     if((depth_multiplier > 1) && (depth_multiplier % 4) != 0)
     {
         return false;
     }
     return true;
 }