Compute Library: RedOpX< T, S > Struct Template Reference
RedOpX< T, S > Struct Template Reference
#include <impl.h>
Public Types
using ExactTagType = typename wrapper::traits::neon_vector< T, S >::tag_type
SIMD vector tag type.
Public Member Functions
void operator() (const Window &in_window, Window &out_window, const ITensor *in, ITensor *out, const ReductionOperation op)
Detailed Description
template<typename T, int S>
struct arm_compute::RedOpX< T, S >
Definition at line 382 of file impl.h.
Member Typedef Documentation
ExactTagType
using ExactTagType = typename wrapper::traits::neon_vector<T, S>::tag_type
SIMD vector tag type.
Definition at line 385 of file impl.h.
Member Function Documentation
operator()()
void operator() (const Window & in_window, Window & out_window, const ITensor * in, ITensor * out, const ReductionOperation op) inline
Definition at line 387 of file impl.h.
     {
         const size_t input_dim_0    = in->info()->dimension(0);
         const int    window_step_x  = 16 / sizeof(T);
         const auto   window_start_x = static_cast<int>(in_window.x().start());
         const auto   window_end_x   = static_cast<int>(in_window.x().end());
         Window in_win_no_pad = in_window;
         in_win_no_pad.set(Window::DimX, Window::Dimension(0, 1, 1));
         Iterator input(in, in_win_no_pad);
         Iterator output(out, out_window);
         execute_window_loop(
             in_win_no_pad,
             [&](const Coordinates &)
             {
                 const auto input_ptr = reinterpret_cast<const T *>(input.ptr());
                 auto init_res_value = static_cast<T>(0.f);
                 switch (op)
                 {
                     case ReductionOperation::ARG_IDX_MAX:
                     case ReductionOperation::ARG_IDX_MIN:
                     case ReductionOperation::MIN:
                     case ReductionOperation::MAX:
                     {
                         init_res_value = static_cast<T>(*input_ptr);
                         break;
                     }
                     case ReductionOperation::PROD:
                     {
                         init_res_value = static_cast<T>(1.f);
                         break;
                     }
                     default:
                         break;
                 }
                 auto         vec_res_value = wrapper::vdup_n(init_res_value, ExactTagType{});
                 uint32x4x4_t vec_res_idx{{0}};
                 // Compute window_step_x elements per iteration
                 int x = window_start_x;
                 for (; x <= (window_end_x - window_step_x); x += window_step_x)
                 {
                     const auto vec_elements = wrapper::vloadq(input_ptr + x);
                     switch (op)
                     {
                         case ReductionOperation::SUM_SQUARE:
                             vec_res_value = wrapper::vadd(wrapper::vmul(vec_elements, vec_elements), vec_res_value);
                             break;
                         case ReductionOperation::MEAN_SUM:
                         case ReductionOperation::SUM:
                             vec_res_value = wrapper::vadd(vec_elements, vec_res_value);
                             break;
                         case ReductionOperation::PROD:
                             vec_res_value = wrapper::vmul(vec_elements, vec_res_value);
                             break;
                         case ReductionOperation::ARG_IDX_MIN:
{
                             auto temp_vec_res_value = wrapper::vmin(vec_elements, vec_res_value);
                             vec_res_idx = calculate_index<decltype(vec_res_value)>(x, temp_vec_res_value, vec_res_value,
                                                                                    vec_res_idx, op, 0);
                             vec_res_value = temp_vec_res_value;
                             break;
                         }
                         case ReductionOperation::ARG_IDX_MAX:
{
                             auto temp_vec_res_value = wrapper::vmax(vec_elements, vec_res_value);
                             vec_res_idx = calculate_index<decltype(vec_res_value)>(x, temp_vec_res_value, vec_res_value,
                                                                                    vec_res_idx, op, 0);
                             vec_res_value = temp_vec_res_value;
                             break;
                         }
                         case ReductionOperation::MIN:
{
                             vec_res_value = wrapper::vmin(vec_elements, vec_res_value);
                             break;
                         }
                         case ReductionOperation::MAX:
{
                             vec_res_value = wrapper::vmax(vec_elements, vec_res_value);
                             break;
                         }
                         default:
                             ARM_COMPUTE_ERROR("Not supported");
                     }
                 }
                 switch (op)
                 {
                     case ReductionOperation::SUM:
                     case ReductionOperation::MEAN_SUM:
                     case ReductionOperation::SUM_SQUARE:
                     {
 #ifdef ARM_COMPUTE_DEBUG_ENABLED
                         auto res = static_cast<T>(0.f);
                         for (int i = 0; i < S; ++i)
{
                             res += wrapper::vgetlane(vec_res_value, i);
                         }
 #else  // ARM_COMPUTE_DEBUG_ENABLED
                         auto carry_res =
                             wrapper::vpadd(wrapper::vgethigh(vec_res_value), wrapper::vgetlow(vec_res_value));
                         for (int i = 0; i < S / 4; ++i)
{
                             carry_res = wrapper::vpadd(carry_res, carry_res);
                         }
                         auto res = wrapper::vgetlane(carry_res, 0);
 #endif // ARM_COMPUTE_DEBUG_ENABLED
                         if (op == ReductionOperation::SUM_SQUARE)
{
                             // Compute left-over elements
                             for (; x < window_end_x; ++x)
{
                                 res += (*(input_ptr + x)) * (*(input_ptr + x));
                             }
                         }
                         else
{
                             // Compute left-over elements
                             for (; x < window_end_x; ++x)
{
                                 res += *(input_ptr + x);
                             }
                         }
                         if (op == ReductionOperation::MEAN_SUM)
{
                             res /= input_dim_0;
                         }
                         *(reinterpret_cast<T *>(output.ptr())) = res;
                         break;
                     }
                     case ReductionOperation::PROD:
                     {
                         auto carry_res =
                             wrapper::vmul(wrapper::vgethigh(vec_res_value), wrapper::vgetlow(vec_res_value));
                         T res = 1;
                         for (int i = 0; i < S / 2; ++i)
{
                             res *= wrapper::vgetlane(carry_res, i);
                         }
                         // Compute left-over elements
                         for (; x < window_end_x; ++x)
{
                             res *= *(input_ptr + x);
                         }
                         *(reinterpret_cast<T *>(output.ptr())) = res;
                         break;
                     }
                     case ReductionOperation::ARG_IDX_MIN:
                     {
                         auto idx = calculate_vector_index<decltype(vec_res_value)>(vec_res_idx, vec_res_value, op);
                         auto res = static_cast<T>(wrapper::vgetlane(calculate_min(vec_res_value), 0));
                         // Compute left-over elements
                         for (; x < window_end_x; ++x)
{
                             if (*(input_ptr + x) < res)
{
                                 idx = x;
                                 res = *(input_ptr + x);
                             }
                         }
                         *(reinterpret_cast<uint32_t *>(output.ptr())) = idx;
                         break;
                     }
                     case ReductionOperation::ARG_IDX_MAX:
                     {
                         auto idx = calculate_vector_index<decltype(vec_res_value)>(vec_res_idx, vec_res_value, op);
                         auto res = static_cast<T>(wrapper::vgetlane(calculate_max(vec_res_value), 0));
                         // Compute left-over elements
                         for (; x < window_end_x; ++x)
{
                             if (*(input_ptr + x) > res)
{
                                 idx = x;
                                 res = *(input_ptr + x);
                             }
                         }
                         *(reinterpret_cast<uint32_t *>(output.ptr())) = idx;
                         break;
                     }
                     case ReductionOperation::MIN:
                     {
                         auto res = static_cast<T>(wrapper::vgetlane(calculate_min(vec_res_value), 0));
                         // Compute left-over elements
                         for (; x < window_end_x; ++x)
{
                             res = *(input_ptr + x) < res ? *(input_ptr + x) : res;
                         }
                         *(reinterpret_cast<T *>(output.ptr())) = res;
                         break;
                     }
                     case ReductionOperation::MAX:
                     {
                         auto res = static_cast<T>(wrapper::vgetlane(calculate_max(vec_res_value), 0));
                         // Compute left-over elements
                         for (; x < window_end_x; ++x)
{
                             res = *(input_ptr + x) > res ? *(input_ptr + x) : res;
                         }
                         *(reinterpret_cast<T *>(output.ptr())) = res;
                         break;
                     }
                     default:
                         ARM_COMPUTE_ERROR("Not supported");
                 }
             },
             input, output);
     }
References arm_compute::ARG_IDX_MAX, arm_compute::ARG_IDX_MIN, ARM_COMPUTE_ERROR, arm_compute::calculate_max(), arm_compute::calculate_min(), ITensorInfo::dimension(), Window::DimX, Window::Dimension::end(), arm_compute::execute_window_loop(), ITensor::info(), arm_compute::test::validation::input, arm_compute::MAX, arm_compute::MEAN_SUM, arm_compute::MIN, arm_compute::PROD, Iterator::ptr(), Window::set(), Window::Dimension::start(), arm_compute::SUM, arm_compute::SUM_SQUARE, arm_compute::wrapper::vadd(), arm_compute::wrapper::vdup_n(), arm_compute::wrapper::vgethigh(), arm_compute::wrapper::vgetlane(), arm_compute::wrapper::vgetlow(), arm_compute::wrapper::vloadq(), arm_compute::wrapper::vmax(), arm_compute::wrapper::vmin(), arm_compute::wrapper::vmul(), arm_compute::wrapper::vpadd(), and Window::x().
The documentation for this struct was generated from the following file:
src/cpu/kernels/reduction_layer/generic/neon/impl.h