Compute Library: Tensor4D< ShapeT, T > Struct Template Reference
Tensor4D< ShapeT, T > Struct Template Reference final
Structure to hold 4D tensor information.
#include <tensor.hpp>
Public Member Functions
Tensor4D (ShapeT shape)
~Tensor4D ()
T * ptr () const
const ShapeT & shape () const
size_t size_bytes () const
bool TestEq (Tensor4D< ShapeT, T > &other) const
T & element (int, int, int, int) const
void Print () const
void Clear ()
void Fill (T val)
void TestPattern ()
void Rand (const int seed=2311)
Tensor4D (const Tensor4D &)=delete
Tensor4D & operator= (const Tensor4D &)=delete
Prevent instances of this class from being copied (As this class contains pointers)
Tensor4D (Tensor4D &&)=default
Allow instances of this class to be moved.
Tensor4D & operator= (Tensor4D &&)=default
Allow instances of this class to be moved.
template<>
float & element (int n, int i, int j, int c) const
template<>
float & element (int oc, int i, int j, int ic) const
template<>
bool TestEq (Tensor4D< Tensor4DShape, float > &other) const
template<>
void Print () const
template<>
void Print () const
Data Fields
__global uchar * ptr
Pointer to the starting postion of the buffer.
int offset_first_element_in_bytes
The offset of the first element in the source image.
int stride_x
Stride of the image in X dimension (in bytes)
int stride_y
Stride of the image in Y dimension (in bytes)
int stride_z
Stride of the image in Z dimension (in bytes)
int stride_w
Stride of the image in W dimension (in bytes)
Detailed Description
template<typename ShapeT, typename T>
struct Tensor4D< ShapeT, T >
Structure to hold 4D tensor information.
Definition at line 67 of file tensor.hpp.
Constructor & Destructor Documentation
Tensor4D (ShapeT shape) inline
Definition at line 69 of file tensor.hpp.
                            :
       _shape(shape),
       _data(reinterpret_cast<T*>(ALLOCATE(size_bytes()))) {
         Clear();
     }
~Tensor4D () inline
Definition at line 75 of file tensor.hpp.
                 {
       free(_data);
     }
Tensor4D (const Tensor4D< ShapeT, T > &) delete
Tensor4D (Tensor4D< ShapeT, T > &&) default
Allow instances of this class to be moved.
Member Function Documentation
void Clear () inline
Definition at line 95 of file tensor.hpp.
                  {
       Fill(static_cast<T>(0));
     }
T& element (int , int , int , int) const
Referenced by Tensor4D< ShapeT, T >::TestEq().
float & element (int n, int i, int j, int c) const inline
Definition at line 133 of file tensor.hpp.
References arm_compute::test::validation::c.
{
   int index = ((n*_shape.n_rows + i)*_shape.n_cols + j)*_shape.n_channels + c;
   return _data[index];
 }
float & element (int oc, int i, int j, int ic) const inline
Definition at line 140 of file tensor.hpp.
{
   int index = ((i*_shape.n_cols + j)*_shape.n_input_channels + ic)*_shape.n_output_channels + oc;
   return _data[index];
 }
void Fill (T val) inline
Definition at line 99 of file tensor.hpp.
                      {
       for (int i = 0; i < _shape.size(); i++)
         _data[i] = val;
     }
Tensor4D& operator= (const Tensor4D< ShapeT, T > &) delete
Prevent instances of this class from being copied (As this class contains pointers)
Tensor4D& operator= (Tensor4D< ShapeT, T > &&) default
Allow instances of this class to be moved.
void Print () const
void Print () const inline
Definition at line 182 of file tensor.hpp.
References arm_compute::test::validation::c.
{
   for (int n = 0; n < _shape.n_batches; n++) {
     for (int c = 0; c < _shape.n_channels; c++) {
       for (int i = 0; i < _shape.n_rows; i++) {
         for (int j = 0; j < _shape.n_cols; j++) {
           printf("%5.2f ", element(n, i, j, c));
         }
         printf("\n");
       }
       printf("\n");
     }
   }
 }
void Print () const inline
Definition at line 198 of file tensor.hpp.
{
   for (int oc = 0; oc < _shape.n_output_channels; oc++) {
     for (int ic = 0; ic < _shape.n_input_channels; ic++) {
       for (int i = 0; i < _shape.n_rows; i++) {
         for (int j = 0; j < _shape.n_cols; j++) {
           printf("%5.2f ", element(oc, i, j, ic));
         }
         printf("\n");
       }
       printf("\n");
     }
   }
 }
T* ptr () const inline
Definition at line 79 of file tensor.hpp.
                    {
       return _data;
     }
void Rand (const int seed = 2311) inline
Definition at line 109 of file tensor.hpp.
{
       std::mt19937 gen(seed);
       std::uniform_int_distribution<> dis(-50, +50);
       for (int i = 0; i < _shape.size(); i++) {
         _data[i] = static_cast<T>(dis(gen));
       }
     }
const ShapeT& shape () const inline
Definition at line 83 of file tensor.hpp.
Referenced by Tensor4D< ShapeT, T >::TestEq().
{
       return _shape;
     }
size_t size_bytes () const inline
Definition at line 87 of file tensor.hpp.
{
       return _shape.size() * sizeof(T);
     }
bool TestEq (Tensor4D< ShapeT, T > & other) const
bool TestEq (Tensor4D< Tensor4DShape, float > & other) const inline
Definition at line 146 of file tensor.hpp.
References arm_compute::test::validation::a, arm_compute::test::validation::b, arm_compute::test::validation::c, Tensor4D< ShapeT, T >::element(), and Tensor4D< ShapeT, T >::shape().
{
   // Test equivalence, printing errors
   // First test the shapes are the same
   if (!_shape.TestEq(other.shape())) {
     printf("Tensors have different shapes.\n");
     return false;
   } else {
     int incorrects = 0;
     for (int n = 0; n < _shape.n_batches; n++) {
       for (int i = 0; i < _shape.n_rows; i++) {
         for (int j = 0; j < _shape.n_cols; j++) {
           for (int c = 0; c < _shape.n_channels; c++) {
             // Check elements for equivalence
             const auto a = this->element(n, i, j, c);
             const auto b = other.element(n, i, j, c);
             if (a != b) {
               printf("Difference at element {%d, %d, %d, %d}: %.3f != %.3f\n", n, i, j, c, a, b);
               if (++incorrects > 100) {
                 printf("More than 100 incorrect values, stopping test.\n");
                 return false;
               }
             }
           }
         }
       }
     }
     return incorrects == 0;
   }
 }
void TestPattern () inline
Definition at line 104 of file tensor.hpp.
{
       for (int i = 0; i < _shape.size(); i++)
         _data[i] = static_cast<T>(i);
     }
Field Documentation
int offset_first_element_in_bytes
The offset of the first element in the source image.
Definition at line 162 of file helpers.h.
Referenced by update_tensor4D_workitem_ptr().
__global uchar* ptr
Pointer to the starting postion of the buffer.
Definition at line 161 of file helpers.h.
Referenced by tensor4D_offset(), and update_tensor4D_workitem_ptr().
int stride_w
Stride of the image in W dimension (in bytes)
Definition at line 166 of file helpers.h.
Referenced by tensor4D_offset().
int stride_x
Stride of the image in X dimension (in bytes)
Definition at line 163 of file helpers.h.
Referenced by tensor4D_offset().
int stride_y
Stride of the image in Y dimension (in bytes)
Definition at line 164 of file helpers.h.
Referenced by tensor4D_offset().
int stride_z
Stride of the image in Z dimension (in bytes)
Definition at line 165 of file helpers.h.
Referenced by tensor4D_offset().
The documentation for this struct was generated from the following files:
arm_compute/core/NEON/kernels/winograd/tensor.hpp
src/core/CL/cl_kernels/helpers.h