Compute Library: examples/graph_vgg16.cpp File Reference
graph_vgg16.cpp File Reference
#include "arm_compute/graph/Graph.h"
#include "arm_compute/graph/Nodes.h"
#include "support/ToolchainSupport.h"
#include "utils/GraphUtils.h"
#include "utils/Utils.h"
#include <cstdlib>
Functions
void main_graph_vgg16 (int argc, const char **argv)
Example demonstrating how to implement VGG16's network using the Compute Library's graph API.
int main (int argc, const char **argv)
Main program for VGG16.
Function Documentation
int main (int argc, const char ** argv)
Main program for VGG16.
Parameters
[in] argc Number of arguments
[in] argv Arguments ([optional] Target (0 = NEON, 1 = OpenCL), [optional] Path to the weights folder, [optional] image, [optional] labels)
Definition at line 219 of file graph_vgg16.cpp.
References main_graph_vgg16(), and arm_compute::utils::run_example().
 {
     return arm_compute::utils::run_example(argc, argv, main_graph_vgg16);
 }
void main_graph_vgg16 (int argc, const char ** argv)
Example demonstrating how to implement VGG16's network using the Compute Library's graph API.
Parameters
[in] argc Number of arguments
[in] argv Arguments ([optional] Target (0 = NEON, 1 = OpenCL), [optional] Path to the weights folder, [optional] image, [optional] labels)
Definition at line 40 of file graph_vgg16.cpp.
References arm_compute::graph::ActivationLayer, arm_compute::graph::ConvolutionLayer, arm_compute::graph::DIRECT, arm_compute::F32, arm_compute::graph::FullyConnectedLayer, arm_compute::graph_utils::get_input_accessor(), arm_compute::graph_utils::get_output_accessor(), arm_compute::graph_utils::get_weights_accessor(), arm_compute::MAX, arm_compute::graph::PoolingLayer, ActivationLayerInfo::RELU, Graph::run(), arm_compute::graph_utils::set_target_hint(), and arm_compute::graph::SoftmaxLayer.
Referenced by main().
 {
     std::string data_path; /* Path to the trainable data */
     std::string image;     /* Image data */
     std::string label;     /* Label data */
     constexpr float mean_r = 123.68f;  /* Mean value to subtract from red channel */
     constexpr float mean_g = 116.779f; /* Mean value to subtract from green channel */
     constexpr float mean_b = 103.939f; /* Mean value to subtract from blue channel */
     // Set target. 0 (NEON), 1 (OpenCL). By default it is NEON
     TargetHint            target_hint      = set_target_hint(argc > 1 ? std::strtol(argv[1], nullptr, 10) : 0);
     ConvolutionMethodHint convolution_hint = ConvolutionMethodHint::DIRECT;
     // Parse arguments
     if(argc < 2)
     {
         // Print help
         std::cout << "Usage: " << argv[0] << " [target] [path_to_data] [image] [labels]\n\n";
         std::cout << "No data folder provided: using random values\n\n";
     }
     else if(argc == 2)
     {
         std::cout << "Usage: " << argv[0] << " " << argv[1] << " [path_to_data] [image] [labels]\n\n";
         std::cout << "No data folder provided: using random values\n\n";
     }
     else if(argc == 3)
     {
         data_path = argv[2];
         std::cout << "Usage: " << argv[0] << " " << argv[1] << " " << argv[2] << " [image] [labels]\n\n";
         std::cout << "No image provided: using random values\n\n";
     }
     else if(argc == 4)
     {
         data_path = argv[2];
         image     = argv[3];
         std::cout << "Usage: " << argv[0] << " " << argv[1] << " " << argv[2] << " " << argv[3] << " [labels]\n\n";
         std::cout << "No text file with labels provided: skipping output accessor\n\n";
     }
     else
     {
         data_path = argv[2];
         image     = argv[3];
         label     = argv[4];
     }
     Graph graph;
     graph << target_hint
           << convolution_hint
           << Tensor(TensorInfo(TensorShape(224U, 224U, 3U, 1U), 1, DataType::F32),
                     get_input_accessor(image, mean_r, mean_g, mean_b))
           << ConvolutionMethodHint::DIRECT
           // Layer 1
           << ConvolutionLayer(
               3U, 3U, 64U,
               get_weights_accessor(data_path, "/cnn_data/vgg16_model/conv1_1_w.npy"),
               get_weights_accessor(data_path, "/cnn_data/vgg16_model/conv1_1_b.npy"),
               PadStrideInfo(1, 1, 1, 1))
           << ActivationLayer(ActivationLayerInfo(ActivationLayerInfo::ActivationFunction::RELU))
           // Layer 2
           << ConvolutionLayer(
               3U, 3U, 64U,
               get_weights_accessor(data_path, "/cnn_data/vgg16_model/conv1_2_w.npy"),
               get_weights_accessor(data_path, "/cnn_data/vgg16_model/conv1_2_b.npy"),
               PadStrideInfo(1, 1, 1, 1))
           << ActivationLayer(ActivationLayerInfo(ActivationLayerInfo::ActivationFunction::RELU))
           << PoolingLayer(PoolingLayerInfo(PoolingType::MAX, 2, PadStrideInfo(2, 2, 0, 0)))
           // Layer 3
           << ConvolutionLayer(
               3U, 3U, 128U,
               get_weights_accessor(data_path, "/cnn_data/vgg16_model/conv2_1_w.npy"),
               get_weights_accessor(data_path, "/cnn_data/vgg16_model/conv2_1_b.npy"),
               PadStrideInfo(1, 1, 1, 1))
           << ActivationLayer(ActivationLayerInfo(ActivationLayerInfo::ActivationFunction::RELU))
           // Layer 4
           << ConvolutionLayer(
               3U, 3U, 128U,
               get_weights_accessor(data_path, "/cnn_data/vgg16_model/conv2_2_w.npy"),
               get_weights_accessor(data_path, "/cnn_data/vgg16_model/conv2_2_b.npy"),
               PadStrideInfo(1, 1, 1, 1))
           << ActivationLayer(ActivationLayerInfo(ActivationLayerInfo::ActivationFunction::RELU))
           << PoolingLayer(PoolingLayerInfo(PoolingType::MAX, 2, PadStrideInfo(2, 2, 0, 0)))
           // Layer 5
           << ConvolutionLayer(
               3U, 3U, 256U,
               get_weights_accessor(data_path, "/cnn_data/vgg16_model/conv3_1_w.npy"),
               get_weights_accessor(data_path, "/cnn_data/vgg16_model/conv3_1_b.npy"),
               PadStrideInfo(1, 1, 1, 1))
           << ActivationLayer(ActivationLayerInfo(ActivationLayerInfo::ActivationFunction::RELU))
           // Layer 6
           << ConvolutionLayer(
               3U, 3U, 256U,
               get_weights_accessor(data_path, "/cnn_data/vgg16_model/conv3_2_w.npy"),
               get_weights_accessor(data_path, "/cnn_data/vgg16_model/conv3_2_b.npy"),
               PadStrideInfo(1, 1, 1, 1))
           << ActivationLayer(ActivationLayerInfo(ActivationLayerInfo::ActivationFunction::RELU))
           // Layer 7
           << ConvolutionLayer(
               3U, 3U, 256U,
               get_weights_accessor(data_path, "/cnn_data/vgg16_model/conv3_3_w.npy"),
               get_weights_accessor(data_path, "/cnn_data/vgg16_model/conv3_3_b.npy"),
               PadStrideInfo(1, 1, 1, 1))
           << ActivationLayer(ActivationLayerInfo(ActivationLayerInfo::ActivationFunction::RELU))
           << PoolingLayer(PoolingLayerInfo(PoolingType::MAX, 2, PadStrideInfo(2, 2, 0, 0)))
           // Layer 8
           << ConvolutionLayer(
               3U, 3U, 512U,
               get_weights_accessor(data_path, "/cnn_data/vgg16_model/conv4_1_w.npy"),
               get_weights_accessor(data_path, "/cnn_data/vgg16_model/conv4_1_b.npy"),
               PadStrideInfo(1, 1, 1, 1))
           << ActivationLayer(ActivationLayerInfo(ActivationLayerInfo::ActivationFunction::RELU))
           // Layer 9
           << ConvolutionLayer(
               3U, 3U, 512U,
               get_weights_accessor(data_path, "/cnn_data/vgg16_model/conv4_2_w.npy"),
               get_weights_accessor(data_path, "/cnn_data/vgg16_model/conv4_2_b.npy"),
               PadStrideInfo(1, 1, 1, 1))
           << ActivationLayer(ActivationLayerInfo(ActivationLayerInfo::ActivationFunction::RELU))
           // Layer 10
           << ConvolutionLayer(
               3U, 3U, 512U,
               get_weights_accessor(data_path, "/cnn_data/vgg16_model/conv4_3_w.npy"),
               get_weights_accessor(data_path, "/cnn_data/vgg16_model/conv4_3_b.npy"),
               PadStrideInfo(1, 1, 1, 1))
           << ActivationLayer(ActivationLayerInfo(ActivationLayerInfo::ActivationFunction::RELU))
           << PoolingLayer(PoolingLayerInfo(PoolingType::MAX, 2, PadStrideInfo(2, 2, 0, 0)))
           // Layer 11
           << ConvolutionLayer(
               3U, 3U, 512U,
               get_weights_accessor(data_path, "/cnn_data/vgg16_model/conv5_1_w.npy"),
               get_weights_accessor(data_path, "/cnn_data/vgg16_model/conv5_1_b.npy"),
               PadStrideInfo(1, 1, 1, 1))
           << ActivationLayer(ActivationLayerInfo(ActivationLayerInfo::ActivationFunction::RELU))
           // Layer 12
           << ConvolutionLayer(
               3U, 3U, 512U,
               get_weights_accessor(data_path, "/cnn_data/vgg16_model/conv5_2_w.npy"),
               get_weights_accessor(data_path, "/cnn_data/vgg16_model/conv5_2_b.npy"),
               PadStrideInfo(1, 1, 1, 1))
           << ActivationLayer(ActivationLayerInfo(ActivationLayerInfo::ActivationFunction::RELU))
           // Layer 13
           << ConvolutionLayer(
               3U, 3U, 512U,
               get_weights_accessor(data_path, "/cnn_data/vgg16_model/conv5_3_w.npy"),
               get_weights_accessor(data_path, "/cnn_data/vgg16_model/conv5_3_b.npy"),
               PadStrideInfo(1, 1, 1, 1))
           << ActivationLayer(ActivationLayerInfo(ActivationLayerInfo::ActivationFunction::RELU))
           << PoolingLayer(PoolingLayerInfo(PoolingType::MAX, 2, PadStrideInfo(2, 2, 0, 0)))
           // Layer 14
           << FullyConnectedLayer(
               4096U,
               get_weights_accessor(data_path, "/cnn_data/vgg16_model/fc6_w.npy"),
               get_weights_accessor(data_path, "/cnn_data/vgg16_model/fc6_b.npy"))
           << ActivationLayer(ActivationLayerInfo(ActivationLayerInfo::ActivationFunction::RELU))
           // Layer 15
           << FullyConnectedLayer(
               4096U,
               get_weights_accessor(data_path, "/cnn_data/vgg16_model/fc7_w.npy"),
               get_weights_accessor(data_path, "/cnn_data/vgg16_model/fc7_b.npy"))
           << ActivationLayer(ActivationLayerInfo(ActivationLayerInfo::ActivationFunction::RELU))
           // Layer 16
           << FullyConnectedLayer(
               1000U,
               get_weights_accessor(data_path, "/cnn_data/vgg16_model/fc8_w.npy"),
               get_weights_accessor(data_path, "/cnn_data/vgg16_model/fc8_b.npy"))
           // Softmax
           << SoftmaxLayer()
           << Tensor(get_output_accessor(label, 5));
     // Run graph
     graph.run();
 }