Compute Library: examples/graph_mobilenet.cpp File Reference
graph_mobilenet.cpp File Reference
#include "arm_compute/graph/Graph.h"
#include "arm_compute/graph/Nodes.h"
#include "support/ToolchainSupport.h"
#include "utils/GraphUtils.h"
#include "utils/Utils.h"
#include <cstdlib>
Functions
void main_graph_mobilenet (int argc, const char **argv)
Example demonstrating how to implement MobileNet's network using the Compute Library's graph API.
int main (int argc, const char **argv)
Main program for MobileNetV1.
Function Documentation
int main (int argc, const char ** argv)
Main program for MobileNetV1.
Parameters
[in] argc Number of arguments
[in] argv Arguments ([optional] Target (0 = NEON, 1 = OpenCL), [optional] Path to the weights folder, [optional] image, [optional] labels)
Definition at line 172 of file graph_mobilenet.cpp.
References main_graph_mobilenet(), and arm_compute::utils::run_example().
 {
     return arm_compute::utils::run_example(argc, argv, main_graph_mobilenet);
 }
void main_graph_mobilenet (int argc, const char ** argv)
Example demonstrating how to implement MobileNet's network using the Compute Library's graph API.
Parameters
[in] argc Number of arguments
[in] argv Arguments ([optional] Target (0 = NEON, 1 = OpenCL), [optional] Path to the weights folder, [optional] image, [optional] labels)
Definition at line 78 of file graph_mobilenet.cpp.
References arm_compute::graph::ActivationLayer, arm_compute::AVG, arm_compute::graph::BatchNormalizationLayer, ActivationLayerInfo::BOUNDED_RELU, arm_compute::graph::ConvolutionLayer, arm_compute::F32, arm_compute::FLOOR, arm_compute::graph_utils::get_input_accessor(), arm_compute::graph_utils::get_output_accessor(), arm_compute::graph_utils::get_weights_accessor(), arm_compute::graph::PoolingLayer, arm_compute::graph::ReshapeLayer, Graph::run(), arm_compute::graph_utils::set_target_hint(), and arm_compute::graph::SoftmaxLayer.
Referenced by main().
 {
     std::string data_path; /* Path to the trainable data */
     std::string image;     /* Image data */
     std::string label;     /* Label data */
     constexpr float mean_r = 122.68f; /* Mean value to subtract from red channel */
     constexpr float mean_g = 116.67f; /* Mean value to subtract from green channel */
     constexpr float mean_b = 104.01f; /* Mean value to subtract from blue channel */
     // Set target. 0 (NEON), 1 (OpenCL). By default it is NEON
     TargetHint target_hint = set_target_hint(argc > 1 ? std::strtol(argv[1], nullptr, 10) : 0);
     // Parse arguments
     if(argc < 2)
     {
         // Print help
         std::cout << "Usage: " << argv[0] << " [target] [path_to_data] [image] [labels]\n\n";
         std::cout << "No data folder provided: using random values\n\n";
     }
     else if(argc == 2)
     {
         std::cout << "Usage: " << argv[0] << " " << argv[1] << " [path_to_data] [image] [labels]\n\n";
         std::cout << "No data folder provided: using random values\n\n";
     }
     else if(argc == 3)
     {
         data_path = argv[2];
         std::cout << "Usage: " << argv[0] << " " << argv[1] << " " << argv[2] << " [image] [labels]\n\n";
         std::cout << "No image provided: using random values\n\n";
     }
     else if(argc == 4)
     {
         data_path = argv[2];
         image     = argv[3];
         std::cout << "Usage: " << argv[0] << " " << argv[1] << " " << argv[2] << " " << argv[3] << " [labels]\n\n";
         std::cout << "No text file with labels provided: skipping output accessor\n\n";
     }
     else
     {
         data_path = argv[2];
         image     = argv[3];
         label     = argv[4];
     }
     Graph graph;
     graph << target_hint
           << Tensor(TensorInfo(TensorShape(224U, 224U, 3U, 1U), 1, DataType::F32),
                     get_input_accessor(image, mean_r, mean_g, mean_b))
           << ConvolutionLayer(
               3U, 3U, 32U,
               get_weights_accessor(data_path, "/cnn_data/mobilenet_v1_model/Conv2d_0_weights.npy"),
               std::unique_ptr<arm_compute::graph::ITensorAccessor>(nullptr),
               PadStrideInfo(2, 2, 0, 1, 0, 1, DimensionRoundingType::FLOOR))
           << BatchNormalizationLayer(
               get_weights_accessor(data_path, "/cnn_data/mobilenet_v1_model/Conv2d_0_BatchNorm_moving_mean.npy"),
               get_weights_accessor(data_path, "/cnn_data/mobilenet_v1_model/Conv2d_0_BatchNorm_moving_variance.npy"),
               get_weights_accessor(data_path, "/cnn_data/mobilenet_v1_model/Conv2d_0_BatchNorm_beta.npy"),
               get_weights_accessor(data_path, "/cnn_data/mobilenet_v1_model/Conv2d_0_BatchNorm_gamma.npy"),
               0.001f)
           << ActivationLayer(ActivationLayerInfo(ActivationLayerInfo::ActivationFunction::BOUNDED_RELU, 6.f))
           << get_dwsc_node(data_path, "Conv2d_1", 64, PadStrideInfo(1, 1, 1, 1), PadStrideInfo(1, 1, 0, 0))
           << get_dwsc_node(data_path, "Conv2d_2", 128, PadStrideInfo(2, 2, 0, 1, 0, 1, DimensionRoundingType::FLOOR), PadStrideInfo(1, 1, 0, 0))
           << get_dwsc_node(data_path, "Conv2d_3", 128, PadStrideInfo(1, 1, 1, 1, 1, 1, DimensionRoundingType::FLOOR), PadStrideInfo(1, 1, 0, 0))
           << get_dwsc_node(data_path, "Conv2d_4", 256, PadStrideInfo(2, 2, 0, 1, 0, 1, DimensionRoundingType::FLOOR), PadStrideInfo(1, 1, 0, 0))
           << get_dwsc_node(data_path, "Conv2d_5", 256, PadStrideInfo(1, 1, 1, 1, 1, 1, DimensionRoundingType::FLOOR), PadStrideInfo(1, 1, 0, 0))
           << get_dwsc_node(data_path, "Conv2d_6", 512, PadStrideInfo(2, 2, 0, 1, 0, 1, DimensionRoundingType::FLOOR), PadStrideInfo(1, 1, 0, 0))
           << get_dwsc_node(data_path, "Conv2d_7", 512, PadStrideInfo(1, 1, 1, 1, 1, 1, DimensionRoundingType::FLOOR), PadStrideInfo(1, 1, 0, 0))
           << get_dwsc_node(data_path, "Conv2d_8", 512, PadStrideInfo(1, 1, 1, 1, 1, 1, DimensionRoundingType::FLOOR), PadStrideInfo(1, 1, 0, 0))
           << get_dwsc_node(data_path, "Conv2d_9", 512, PadStrideInfo(1, 1, 1, 1, 1, 1, DimensionRoundingType::FLOOR), PadStrideInfo(1, 1, 0, 0))
           << get_dwsc_node(data_path, "Conv2d_10", 512, PadStrideInfo(1, 1, 1, 1, 1, 1, DimensionRoundingType::FLOOR), PadStrideInfo(1, 1, 0, 0))
           << get_dwsc_node(data_path, "Conv2d_11", 512, PadStrideInfo(1, 1, 1, 1, 1, 1, DimensionRoundingType::FLOOR), PadStrideInfo(1, 1, 0, 0))
           << get_dwsc_node(data_path, "Conv2d_12", 1024, PadStrideInfo(2, 2, 0, 1, 0, 1, DimensionRoundingType::FLOOR), PadStrideInfo(1, 1, 0, 0))
           << get_dwsc_node(data_path, "Conv2d_13", 1024, PadStrideInfo(1, 1, 1, 1, 1, 1, DimensionRoundingType::FLOOR), PadStrideInfo(1, 1, 0, 0))
           << PoolingLayer(PoolingLayerInfo(PoolingType::AVG))
           << ConvolutionLayer(
               1U, 1U, 1001U,
               get_weights_accessor(data_path, "/cnn_data/mobilenet_v1_model/Logits_Conv2d_1c_1x1_weights.npy"),
               get_weights_accessor(data_path, "/cnn_data/mobilenet_v1_model/Logits_Conv2d_1c_1x1_biases.npy"),
               PadStrideInfo(1, 1, 0, 0))
           << ReshapeLayer(TensorShape(1001U))
           << SoftmaxLayer()
           << Tensor(get_output_accessor(label, 5));
     graph.run();
 }