Compute Library: examples/neoncl_scale_median_gaussian.cpp File Reference
neoncl_scale_median_gaussian.cpp File Reference
#include "arm_compute/core/Types.h"
#include "arm_compute/runtime/CL/CLFunctions.h"
#include "arm_compute/runtime/CL/CLScheduler.h"
#include "arm_compute/runtime/NEON/NEFunctions.h"
#include "utils/Utils.h"
Functions
void main_neoncl_scale_median_gaussian (int argc, const char **argv)
Example demonstrating how to use both CL and NEON functions in the same pipeline.
int main (int argc, const char **argv)
Main program for convolution test.
Function Documentation
int main (int argc, const char ** argv)
Main program for convolution test.
Parameters
[in] argc Number of arguments
[in] argv Arguments ([optional] Path to PPM image to process)
Definition at line 126 of file neoncl_scale_median_gaussian.cpp.
References main_neoncl_scale_median_gaussian(), and arm_compute::utils::run_example().
 {
     return utils::run_example(argc, argv, main_neoncl_scale_median_gaussian);
 }
void main_neoncl_scale_median_gaussian (int argc, const char ** argv)
Example demonstrating how to use both CL and NEON functions in the same pipeline.
Parameters
[in] argc Number of arguments
[in] argv Arguments ([optional] Path to PPM image to process)
[NEON / OpenCL Interop]
[NEON / OpenCL Interop]
Definition at line 42 of file neoncl_scale_median_gaussian.cpp.
References ITensorAllocator::allocate(), CLTensor::allocator(), CLScale::configure(), NEMedian3x3::configure(), CLGaussian5x5::configure(), CLScheduler::default_init(), TensorInfo::dimension(), arm_compute::test::validation::dst, PPMLoader::fill_image(), CLScheduler::get(), CLTensor::info(), ITensorAllocator::init(), PPMLoader::init_image(), PPMLoader::is_open(), CLTensor::map(), arm_compute::NEAREST_NEIGHBOR, PPMLoader::open(), arm_compute::REPLICATE, INESimpleFunction::run(), ICLSimpleFunction::run(), CLGaussian5x5::run(), arm_compute::utils::save_to_ppm(), arm_compute::test::validation::scale, CLScheduler::sync(), arm_compute::U8, and CLTensor::unmap().
Referenced by main().
 {
     PPMLoader ppm;
     CLImage   src, scale_median, median_gauss, dst;
     CLScheduler::get().default_init();
     if(argc < 2)
     {
         // Print help
         std::cout << "Usage: ./build/cl_convolution [input_image.ppm]\n\n";
         std::cout << "No input_image provided, creating a dummy 640x480 image\n";
         // Create an empty grayscale 640x480 image
         src.allocator()->init(TensorInfo(640, 480, Format::U8));
     }
     else
     {
         ppm.open(argv[1]);
         ppm.init_image(src, Format::U8);
     }
     TensorInfo scale_median_info(TensorInfo(src.info()->dimension(0) / 2, src.info()->dimension(1) / 2, Format::U8));
     // Configure the temporary and destination images
     scale_median.allocator()->init(scale_median_info);
     median_gauss.allocator()->init(scale_median_info);
     dst.allocator()->init(scale_median_info);
     // Declare and configure the functions to create the following pipeline: scale -> median -> gauss
     CLScale       scale;
     NEMedian3x3   median;
     CLGaussian5x5 gauss;
     scale.configure(&src, &scale_median, InterpolationPolicy::NEAREST_NEIGHBOR, BorderMode::REPLICATE);
     median.configure(&scale_median, &median_gauss, BorderMode::REPLICATE);
     gauss.configure(&median_gauss, &dst, BorderMode::REPLICATE);
     // Allocate all the images
     src.allocator()->allocate();
     scale_median.allocator()->allocate();
     median_gauss.allocator()->allocate();
     dst.allocator()->allocate();
     // Fill the input image with the content of the PPM image if a filename was provided:
     if(ppm.is_open())
     {
         ppm.fill_image(src);
     }
     // Enqueue and flush the OpenCL kernel:
     scale.run();
     // Do a blocking map of the input and output buffers of the NEON function:
     scale_median.map();
     median_gauss.map();
     // Run the NEON function:
     median.run();
     // Unmap the output buffer before it's used again by OpenCL:
     scale_median.unmap();
     median_gauss.unmap();
     // Run the final OpenCL function:
     gauss.run();
     // Make sure all the OpenCL jobs are done executing:
     CLScheduler::get().sync();
     // Save the result to file:
     if(ppm.is_open())
     {
         const std::string output_filename = std::string(argv[1]) + "_out.ppm";
         save_to_ppm(dst, output_filename); // save_to_ppm maps and unmaps the image to store as PPM
     }
 }