Compute Library: CLRuntimeContext Class Reference
CLRuntimeContext Class Reference
Runtime context.
#include <CLRuntimeContext.h>
Public Member Functions
CLRuntimeContext ()
Default Constructor.
~CLRuntimeContext ()=default
Destructor.
CLRuntimeContext (const CLRuntimeContext &)=delete
Prevent instances of this class from being copied (As this class contains pointers)
CLRuntimeContext & operator= (const CLRuntimeContext &)=delete
Prevent instances of this class from being copied (As this class contains pointers)
void set_gpu_scheduler (CLScheduler *scheduler)
CPU Scheduler setter.
CLScheduler * gpu_scheduler ()
CLKernelLibrary & kernel_library ()
CLCoreRuntimeContext * core_runtime_context ()
Public Member Functions inherited from RuntimeContext
RuntimeContext ()
Default Constructor.
~RuntimeContext ()=default
Destructor.
RuntimeContext (const RuntimeContext &)=delete
Prevent instances of this class from being copied (As this class contains pointers)
RuntimeContext (RuntimeContext &&)=default
Default move constructor.
RuntimeContext & operator= (const RuntimeContext &)=delete
Prevent instances of this class from being copied (As this class contains pointers)
RuntimeContext & operator= (RuntimeContext &&)=default
Default move assignment operator.
void set_scheduler (IScheduler *scheduler)
CPU Scheduler setter.
IScheduler * scheduler () override
Scheduler accessor.
IAssetManager * asset_manager () override
Asset manager accessor.
const DeviceProperties & properties () override
Device propertied accessor.
Public Member Functions inherited from IRuntimeContext
virtual ~IRuntimeContext ()=default
Destructor.
Detailed Description
Runtime context.
Definition at line 38 of file CLRuntimeContext.h.
Constructor & Destructor Documentation
CLRuntimeContext() [1/2]
CLRuntimeContext ()
Default Constructor.
Definition at line 33 of file CLRuntimeContext.cpp.
     : _gpu_owned_scheduler(support::cpp14::make_unique<CLScheduler>()), _gpu_scheduler(_gpu_owned_scheduler.get()), _symbols(), _core_context()
 {
     _symbols.load_default();
     auto ctx_dev_err = create_opencl_context_and_device();
     ARM_COMPUTE_ERROR_ON_MSG(std::get<2>(ctx_dev_err) != CL_SUCCESS, "Failed to create OpenCL context");
     auto             ctx   = std::get<0>(ctx_dev_err);
     auto             dev   = std::get<1>(ctx_dev_err);
     cl::CommandQueue queue = cl::CommandQueue(ctx, dev);
     _gpu_owned_scheduler->init(ctx, queue, dev, &_tuner);
     const std::string cl_kernels_folder("./cl_kernels");
     CLKernelLibrary::get().init(cl_kernels_folder, ctx, dev);
     _core_context = CLCoreRuntimeContext(&CLKernelLibrary::get(), _gpu_owned_scheduler->context(), _gpu_owned_scheduler->queue());
 }
References ARM_COMPUTE_ERROR_ON_MSG, arm_compute::create_opencl_context_and_device(), CLKernelLibrary::get(), CLKernelLibrary::init(), and CLSymbols::load_default().
~CLRuntimeContext()
~CLRuntimeContext () default
Destructor.
CLRuntimeContext() [2/2]
CLRuntimeContext (const CLRuntimeContext &) delete
Prevent instances of this class from being copied (As this class contains pointers)
Member Function Documentation
core_runtime_context()
CLCoreRuntimeContext * core_runtime_context ()
Definition at line 53 of file CLRuntimeContext.cpp.
 {
     return &_core_context;
 }
Referenced by CLTensorAllocator::allocate(), and CLTensorAllocator::import_memory().
gpu_scheduler()
CLScheduler * gpu_scheduler ()
Definition at line 64 of file CLRuntimeContext.cpp.
 {
     return _gpu_scheduler;
 }
Referenced by CLTensor::map(), arm_compute::schedule_kernel_on_ctx(), and CLTensor::unmap().
kernel_library()
CLKernelLibrary & kernel_library ()
Definition at line 48 of file CLRuntimeContext.cpp.
 {
     return CLKernelLibrary::get();
 }
References CLKernelLibrary::get().
operator=()
CLRuntimeContext& operator= (const CLRuntimeContext &) delete
Prevent instances of this class from being copied (As this class contains pointers)
set_gpu_scheduler()
void set_gpu_scheduler (CLScheduler * scheduler)
CPU Scheduler setter.
Definition at line 58 of file CLRuntimeContext.cpp.
 {
     ARM_COMPUTE_ERROR_ON_NULLPTR(scheduler);
     _gpu_scheduler = scheduler;
 }
References ARM_COMPUTE_ERROR_ON_NULLPTR, and RuntimeContext::scheduler().
The documentation for this class was generated from the following files:
arm_compute/runtime/CL/CLRuntimeContext.h
src/runtime/CL/CLRuntimeContext.cpp