Compute Library: NEBoundingBoxTransformKernel Class Reference
NEBoundingBoxTransformKernel Class Reference
Interface for the bounding box kernel.
#include <NEBoundingBoxTransformKernel.h>
Public Member Functions
const char * name () const override
Name of the kernel.
NEBoundingBoxTransformKernel ()
Default constructor.
NEBoundingBoxTransformKernel (const NEBoundingBoxTransformKernel &)=delete
Prevent instances of this class from being copied (As this class contains pointers)
NEBoundingBoxTransformKernel & operator= (const NEBoundingBoxTransformKernel &)=delete
Prevent instances of this class from being copied (As this class contains pointers)
NEBoundingBoxTransformKernel (NEBoundingBoxTransformKernel &&)=default
Allow instances of this class to be moved.
NEBoundingBoxTransformKernel & operator= (NEBoundingBoxTransformKernel &&)=default
Allow instances of this class to be moved.
~NEBoundingBoxTransformKernel ()=default
Default destructor.
void configure (const ITensor *boxes, ITensor *pred_boxes, const ITensor *deltas, const BoundingBoxTransformInfo &info)
Set the input and output tensors.
void run (const Window &window, const ThreadInfo &info) override
Execute the kernel on the passed window.
Public Member Functions inherited from ICPPKernel
virtual ~ICPPKernel ()=default
Default destructor.
virtual void run_nd (const Window &window, const ThreadInfo &info, const Window &thread_locator)
legacy compatibility layer for implemantions which do not support thread_locator In these cases we simply narrow the interface down the legacy version
virtual void run_op (ITensorPack &tensors, const Window &window, const ThreadInfo &info)
Execute the kernel on the passed window.
Public Member Functions inherited from IKernel
IKernel ()
Constructor.
virtual ~IKernel ()=default
Destructor.
virtual bool is_parallelisable () const
Indicates whether or not the kernel is parallelisable.
virtual BorderSize border_size () const
The size of the border for that kernel.
const Window & window () const
The maximum window the kernel can be executed on.
Static Public Member Functions
static Status validate (const ITensorInfo *boxes, const ITensorInfo *pred_boxes, const ITensorInfo *deltas, const BoundingBoxTransformInfo &info)
Static function to check if given info will lead to a valid configuration of CLBoundingBoxTransform.
Detailed Description
Interface for the bounding box kernel.
Definition at line 34 of file NEBoundingBoxTransformKernel.h.
Constructor & Destructor Documentation
NEBoundingBoxTransformKernel() [1/3]
NEBoundingBoxTransformKernel ()
Default constructor.
Definition at line 83 of file NEBoundingBoxTransformKernel.cpp.
     : _boxes(nullptr), _pred_boxes(nullptr), _deltas(nullptr), _bbinfo(0, 0, 0)
 {
 }
NEBoundingBoxTransformKernel() [2/3]
NEBoundingBoxTransformKernel (const NEBoundingBoxTransformKernel &) delete
Prevent instances of this class from being copied (As this class contains pointers)
NEBoundingBoxTransformKernel() [3/3]
NEBoundingBoxTransformKernel (NEBoundingBoxTransformKernel &&) default
Allow instances of this class to be moved.
~NEBoundingBoxTransformKernel()
~NEBoundingBoxTransformKernel () default
Default destructor.
Member Function Documentation
configure()
void configure (const ITensor * boxes, ITensor * pred_boxes, const ITensor * deltas, const BoundingBoxTransformInfo & info)
Set the input and output tensors.
Parameters
[in] boxes Source tensor. Bounding box proposals in pixel coordinates. Size(M, 4), format [x1, y1, x2, y2]. Data types supported: QASYMM16/F16/F32.
[out] pred_boxes Destination tensor. Pixel coordinates of the transformed bounding boxes. Size (M, 4*K), format [x1, y1, x2, y2]. Data types supported: Same as input
[in] deltas Bounding box translations and scales. Size (M, 4*K), format [dx, dy, dw, dh], K is the number of classes. Data types supported: QASYMM8 if input is QASYMM16, otherwise same as input.
[in] info Contains BoundingBox operation information described in BoundingBoxTransformInfo.
Note
Only single image prediction is supported. Height and Width (and scale) of the image will be contained in the BoundingBoxTransformInfo struct.
Definition at line 88 of file NEBoundingBoxTransformKernel.cpp.
 {
     ARM_COMPUTE_ERROR_ON_NULLPTR(boxes, pred_boxes, deltas);
     ARM_COMPUTE_ERROR_THROW_ON(validate_arguments(boxes->info(), pred_boxes->info(), deltas->info(), info));
     // Configure kernel window
     auto_init_if_empty(*pred_boxes->info(), deltas->info()->clone()->set_data_type(boxes->info()->data_type()).set_quantization_info(boxes->info()->quantization_info()));
     // Set instance variables
     _boxes      = boxes;
     _pred_boxes = pred_boxes;
     _deltas     = deltas;
     _bbinfo     = info;
     const unsigned int num_boxes = boxes->info()->dimension(1);
     Window             win       = calculate_max_window(*pred_boxes->info(), Steps());
     Coordinates        coord;
     coord.set_num_dimensions(pred_boxes->info()->num_dimensions());
     pred_boxes->info()->set_valid_region(ValidRegion(coord, pred_boxes->info()->tensor_shape()));
     win.set(Window::DimX, Window::Dimension(0, 1u));
     win.set(Window::DimY, Window::Dimension(0, num_boxes));
     INEKernel::configure(win);
 }
References ARM_COMPUTE_ERROR_ON_NULLPTR, ARM_COMPUTE_ERROR_THROW_ON, arm_compute::auto_init_if_empty(), arm_compute::calculate_max_window(), ICloneable< T >::clone(), ITensorInfo::data_type(), ITensorInfo::dimension(), Window::DimX, Window::DimY, ITensor::info(), arm_compute::test::validation::info, ITensorInfo::num_dimensions(), ITensorInfo::quantization_info(), Window::set(), Dimensions< T >::set_num_dimensions(), ITensorInfo::set_valid_region(), ITensorInfo::tensor_shape(), and arm_compute::validate_arguments().
name()
const char* name () const inline override virtual
Name of the kernel.
Returns
Kernel name
Implements ICPPKernel.
Definition at line 37 of file NEBoundingBoxTransformKernel.h.
     {
         return "NEBoundingBoxTransformKernel";
     }
operator=() [1/2]
NEBoundingBoxTransformKernel& operator= (const NEBoundingBoxTransformKernel &) delete
Prevent instances of this class from being copied (As this class contains pointers)
operator=() [2/2]
NEBoundingBoxTransformKernel& operator= (NEBoundingBoxTransformKernel &&) default
Allow instances of this class to be moved.
run()
void run (const Window & window, const ThreadInfo & info) override virtual
Execute the kernel on the passed window.
Warning
If is_parallelisable() returns false then the passed window must be equal to window()
Note
The window has to be a region within the window returned by the window() method
The width of the window has to be a multiple of num_elems_processed_per_iteration().
Parameters
[in] window Region on which to execute the kernel. (Must be a region of the window returned by window())
[in] info Info about executing thread and CPU.
Reimplemented from ICPPKernel.
Definition at line 230 of file NEBoundingBoxTransformKernel.cpp.
 {
     ARM_COMPUTE_UNUSED(info);
     ARM_COMPUTE_ERROR_ON_UNCONFIGURED_KERNEL(this);
     ARM_COMPUTE_ERROR_ON_INVALID_SUBWINDOW(INEKernel::window(), window);
     switch(_boxes->info()->data_type())
     {
         case DataType::F32:
         {
             internal_run<float>(window);
             break;
         }
         case DataType::QASYMM16:
         {
             internal_run<uint16_t>(window);
             break;
         }
 #ifdef __ARM_FEATURE_FP16_VECTOR_ARITHMETIC
         case DataType::F16:
         {
             internal_run<float16_t>(window);
             break;
         }
 #endif // __ARM_FEATURE_FP16_VECTOR_ARITHMETIC
         default:
         {
             ARM_COMPUTE_ERROR("Data type not supported");
         }
     }
 }
References ARM_COMPUTE_ERROR, ARM_COMPUTE_ERROR_ON_INVALID_SUBWINDOW, ARM_COMPUTE_ERROR_ON_UNCONFIGURED_KERNEL, ARM_COMPUTE_UNUSED, ITensorInfo::data_type(), arm_compute::F16, arm_compute::F32, ITensor::info(), arm_compute::test::validation::info, arm_compute::QASYMM16, and IKernel::window().
validate()
Status validate (const ITensorInfo * boxes, const ITensorInfo * pred_boxes, const ITensorInfo * deltas, const BoundingBoxTransformInfo & info) static
Static function to check if given info will lead to a valid configuration of CLBoundingBoxTransform.
Parameters
[in] boxes Source tensor info. Bounding box proposals in pixel coordinates. Size(M, 4), format [x1, y1, x2, y2]. Data types supported: QASYMM16/F16/F32.
[in] pred_boxes Destination tensor info. Pixel coordinates of the transformed bounding boxes. Size (M, 4*K), format [x1, y1, x2, y2]. Data types supported: Same as input
[in] deltas Bounding box translations and scales. Size (M, 4*K), format [dx, dy, dw, dh], K is the number of classes. Data types supported: QASYMM8 if input is QASYMM16, otherwise same as input.
[in] info Contains BoundingBox operation information described in BoundingBoxTransformInfo.
Note
Only single image prediction is supported. Height and Width (and scale) of the image will be contained in the BoundingBoxTransformInfo struct.
Returns
a Status
Definition at line 113 of file NEBoundingBoxTransformKernel.cpp.
 {
     ARM_COMPUTE_RETURN_ON_ERROR(validate_arguments(boxes, pred_boxes, deltas, info));
     return Status{};
 }
References ARM_COMPUTE_RETURN_ON_ERROR, arm_compute::test::validation::info, and arm_compute::validate_arguments().
Referenced by NEBoundingBoxTransform::validate().
The documentation for this class was generated from the following files:
src/core/NEON/kernels/NEBoundingBoxTransformKernel.h
src/core/NEON/kernels/NEBoundingBoxTransformKernel.cpp