Compute Library: NEGEMMLowpQuantizeDownInt32ScaleKernel Class Reference
NEGEMMLowpQuantizeDownInt32ScaleKernel Class Reference
NEON kernel used to quantize down the int32 accumulator values of GEMMLowp to QASYMM8/QASYMM8_SIGNED.
#include <NEGEMMLowpQuantizeDownInt32ScaleKernel.h>
Public Member Functions
const char * name () const override
Name of the kernel.
NEGEMMLowpQuantizeDownInt32ScaleKernel ()
Constructor.
NEGEMMLowpQuantizeDownInt32ScaleKernel (const NEGEMMLowpQuantizeDownInt32ScaleKernel &)=delete
Prevent instances of this class from being copied (As this class contains pointers)
NEGEMMLowpQuantizeDownInt32ScaleKernel & operator= (const NEGEMMLowpQuantizeDownInt32ScaleKernel &)=delete
Prevent instances of this class from being copied (As this class contains pointers)
NEGEMMLowpQuantizeDownInt32ScaleKernel (NEGEMMLowpQuantizeDownInt32ScaleKernel &&)=default
Allow instances of this class to be moved.
NEGEMMLowpQuantizeDownInt32ScaleKernel & operator= (NEGEMMLowpQuantizeDownInt32ScaleKernel &&)=default
Allow instances of this class to be moved.
~NEGEMMLowpQuantizeDownInt32ScaleKernel ()=default
Default destructor.
void configure (const ITensor *input, const ITensor *bias, ITensor *output, const GEMMLowpOutputStageInfo *output_stage)
Initialise the kernel's input and output.
void run (const Window &window, const ThreadInfo &info) override
Execute the kernel on the passed window.
Public Member Functions inherited from ICPPKernel
virtual ~ICPPKernel ()=default
Default destructor.
virtual void run_nd (const Window &window, const ThreadInfo &info, const Window &thread_locator)
legacy compatibility layer for implemantions which do not support thread_locator In these cases we simply narrow the interface down the legacy version
virtual void run_op (ITensorPack &tensors, const Window &window, const ThreadInfo &info)
Execute the kernel on the passed window.
Public Member Functions inherited from IKernel
IKernel ()
Constructor.
virtual ~IKernel ()=default
Destructor.
virtual bool is_parallelisable () const
Indicates whether or not the kernel is parallelisable.
virtual BorderSize border_size () const
The size of the border for that kernel.
const Window & window () const
The maximum window the kernel can be executed on.
Static Public Member Functions
static Status validate (const ITensorInfo *input, const ITensorInfo *bias, const ITensorInfo *output, const GEMMLowpOutputStageInfo *output_stage)
Static function to check if given info will lead to a valid configuration of NEGEMMLowpQuantizeDownInt32ScaleKernel.
Detailed Description
NEON kernel used to quantize down the int32 accumulator values of GEMMLowp to QASYMM8/QASYMM8_SIGNED.
This kernel takes a final int32 accumulator value (the output of NEGEMMLowpMatrixMultiplyKernel), and processes it to obtain the final QASYMM8/QASYMM8_SIGNED value. The following computations will be performed by the kernel:
Add offset terms to final result
Multiply each entry of result by result_mult_int
Add bias to final result if bias tensor is not a nullptr
Shift the int32 accumulator by result_shift
Clamp the value between the specified min and max bounds
Clamp the resulting int32 values:
-to the [0..255] range and cast to QASYMM8.
-to the [-128..127] range and cast to QASYMM8_SIGNED.
Definition at line 48 of file NEGEMMLowpQuantizeDownInt32ScaleKernel.h.
Constructor & Destructor Documentation
NEGEMMLowpQuantizeDownInt32ScaleKernel() [1/3]
NEGEMMLowpQuantizeDownInt32ScaleKernel ()
Constructor.
Definition at line 258 of file NEGEMMLowpQuantizeDownInt32ScaleKernel.cpp.
     : _func(nullptr), _input(nullptr), _bias(nullptr), _output(nullptr), _output_stage(nullptr), _is_bounded_relu(false)
 {
 }
NEGEMMLowpQuantizeDownInt32ScaleKernel() [2/3]
NEGEMMLowpQuantizeDownInt32ScaleKernel (const NEGEMMLowpQuantizeDownInt32ScaleKernel &) delete
Prevent instances of this class from being copied (As this class contains pointers)
NEGEMMLowpQuantizeDownInt32ScaleKernel() [3/3]
NEGEMMLowpQuantizeDownInt32ScaleKernel (NEGEMMLowpQuantizeDownInt32ScaleKernel &&) default
Allow instances of this class to be moved.
~NEGEMMLowpQuantizeDownInt32ScaleKernel()
~NEGEMMLowpQuantizeDownInt32ScaleKernel () default
Default destructor.
Member Function Documentation
configure()
void configure (const ITensor * input, const ITensor * bias, ITensor * output, const GEMMLowpOutputStageInfo * output_stage)
Initialise the kernel's input and output.
Parameters
[in] input Input tensor. Data type supported: S32
[in] bias Biases tensor. Only shared biases supported and it can be a nullptr if the biases addition is not required. Biases are 1D tensor with dimensions [OFM]. Data type supported: Same as input.
[out] output Output tensor. Data type supported: Data type supported: QASYMM8/QASYMM8_SIGNED
[out] output_stage GEMMLowp output stage metadata.
Definition at line 263 of file NEGEMMLowpQuantizeDownInt32ScaleKernel.cpp.
 {
     // Perform validate step
     ARM_COMPUTE_ERROR_ON_NULLPTR(input, output, output_stage);
     // Output auto inizialitation if not yet initialized
     auto_init_if_empty(*output->info(), input->info()->clone()->set_data_type(output_stage->output_data_type));
     ARM_COMPUTE_ERROR_THROW_ON(validate_arguments(input->info(),
                                                   (bias != nullptr) ? bias->info() : nullptr,
                                                   output->info(),
                                                   output_stage));
     _input        = input;
     _bias         = bias;
     _output       = output;
     _output_stage = output_stage;
     // Configure kernel window
     Window      win = calculate_max_window(*input->info(), Steps());
     Coordinates coord;
     coord.set_num_dimensions(output->info()->num_dimensions());
     output->info()->set_valid_region(ValidRegion(coord, output->info()->tensor_shape()));
     INEKernel::configure(win);
     // Check if we need to clamp the result using min and max
     _is_bounded_relu = ((_output_stage->gemmlowp_min_bound != _output_stage->gemmlowp_max_bound)
                         && !(_output_stage->gemmlowp_min_bound == std::get<0>(quantization::get_min_max_values_from_quantized_data_type(output_stage->output_data_type))
                              && _output_stage->gemmlowp_max_bound == std::get<1>(quantization::get_min_max_values_from_quantized_data_type(output_stage->output_data_type))));
     if(_output_stage->output_data_type == DataType::QASYMM8)
     {
         _func = &NEGEMMLowpQuantizeDownInt32ScaleKernel::run<uint8_t>;
     }
     else if(_output_stage->output_data_type == DataType::QASYMM8_SIGNED)
     {
         _func = &NEGEMMLowpQuantizeDownInt32ScaleKernel::run<int8_t>;
     }
     else
     {
         ARM_COMPUTE_ERROR("Data type not supported");
     }
 }
References ARM_COMPUTE_ERROR_ON_NULLPTR, ARM_COMPUTE_ERROR_THROW_ON, arm_compute::auto_init_if_empty(), ITensor::info(), arm_compute::test::validation::input, GEMMLowpOutputStageInfo::output_data_type, and arm_compute::validate_arguments().
name()
const char* name () const inline override virtual
Name of the kernel.
Returns
Kernel name
Implements ICPPKernel.
Definition at line 51 of file NEGEMMLowpQuantizeDownInt32ScaleKernel.h.
     {
         return "NEGEMMLowpQuantizeDownInt32ScaleKernel";
     }
operator=() [1/2]
NEGEMMLowpQuantizeDownInt32ScaleKernel& operator= (const NEGEMMLowpQuantizeDownInt32ScaleKernel &) delete
Prevent instances of this class from being copied (As this class contains pointers)
operator=() [2/2]
NEGEMMLowpQuantizeDownInt32ScaleKernel& operator= (NEGEMMLowpQuantizeDownInt32ScaleKernel &&) default
Allow instances of this class to be moved.
run()
void run (const Window & window, const ThreadInfo & info) override virtual
Execute the kernel on the passed window.
Warning
If is_parallelisable() returns false then the passed window must be equal to window()
Note
The window has to be a region within the window returned by the window() method
The width of the window has to be a multiple of num_elems_processed_per_iteration().
Parameters
[in] window Region on which to execute the kernel. (Must be a region of the window returned by window())
[in] info Info about executing thread and CPU.
Reimplemented from ICPPKernel.
Definition at line 315 of file NEGEMMLowpQuantizeDownInt32ScaleKernel.cpp.
 {
     ARM_COMPUTE_UNUSED(info);
     ARM_COMPUTE_ERROR_ON_UNCONFIGURED_KERNEL(this);
     ARM_COMPUTE_ERROR_ON_INVALID_SUBWINDOW(INEKernel::window(), window);
     (this->*_func)(window);
 }
References ARM_COMPUTE_ERROR_ON_INVALID_SUBWINDOW, ARM_COMPUTE_ERROR_ON_UNCONFIGURED_KERNEL, ARM_COMPUTE_UNUSED, arm_compute::test::validation::info, and IKernel::window().
validate()
Status validate (const ITensorInfo * input, const ITensorInfo * bias, const ITensorInfo * output, const GEMMLowpOutputStageInfo * output_stage) static
Static function to check if given info will lead to a valid configuration of NEGEMMLowpQuantizeDownInt32ScaleKernel.
Parameters
[in] input Input tensor. Data type supported: S32
[in] bias Biases tensor. Only shared biases supported and it can be a nullptr if the biases addition is not required. Biases are 1D tensor with dimensions [OFM]. Data type supported: Same as input.
[in] output Output tensor. Data type supported: Data type supported: QASYMM8/QASYMM8_SIGNED
[out] output_stage GEMMLowp output stage metadata.
Returns
a status
Definition at line 307 of file NEGEMMLowpQuantizeDownInt32ScaleKernel.cpp.
 {
     ARM_COMPUTE_ERROR_ON_NULLPTR(input, output);
     ARM_COMPUTE_RETURN_ON_ERROR(validate_arguments(input, bias, output, output_stage));
     return Status{};
 }
References ARM_COMPUTE_ERROR_ON_NULLPTR, ARM_COMPUTE_RETURN_ON_ERROR, arm_compute::test::validation::input, and arm_compute::validate_arguments().
Referenced by NEGEMMLowpOutputStage::validate().
The documentation for this class was generated from the following files:
src/core/NEON/kernels/NEGEMMLowpQuantizeDownInt32ScaleKernel.h
src/core/NEON/kernels/NEGEMMLowpQuantizeDownInt32ScaleKernel.cpp