Compute Library: CLSoftmaxLayerGeneric< IS_LOG > Class Template Reference
CLSoftmaxLayerGeneric< IS_LOG > Class Template Reference
Basic function to compute a SoftmaxLayer.
#include <CLSoftmaxLayer.h>
Public Member Functions
CLSoftmaxLayerGeneric (std::shared_ptr< IMemoryManager > memory_manager=nullptr)
Constructor.
CLSoftmaxLayerGeneric (const CLSoftmaxLayerGeneric &)=delete
Prevent instances of this class from being copied.
CLSoftmaxLayerGeneric & operator= (const CLSoftmaxLayerGeneric &)=delete
Prevent instances of this class from being copied.
CLSoftmaxLayerGeneric (CLSoftmaxLayerGeneric &&)=delete
Prevent instances of this class to be moved.
CLSoftmaxLayerGeneric & operator= (CLSoftmaxLayerGeneric &&)=delete
Prevent instances of this class to be moved.
~CLSoftmaxLayerGeneric ()
Default destructor.
void configure (const ICLTensor *input, ICLTensor *output, float beta=1.0f, int32_t axis=0)
Set the input and output tensors.
void configure (const CLCompileContext &compile_context, const ICLTensor *input, ICLTensor *output, float beta=1.0f, int32_t axis=0)
Set the input and output tensors.
void run () override
Run the kernels contained in the function.
Public Member Functions inherited from IFunction
virtual ~IFunction ()=default
Destructor.
virtual void prepare ()
Prepare the function for executing.
Static Public Member Functions
static Status validate (const ITensorInfo *input, const ITensorInfo *output, float beta=1.0f, int32_t axis=0)
Static function to check if given info will lead to a valid configuration of CLSoftmaxLayer.
Detailed Description
template<bool IS_LOG = false>
class arm_compute::CLSoftmaxLayerGeneric< IS_LOG >
Basic function to compute a SoftmaxLayer.
Softmax is calculated by :
\[ out = exp((x - max(x)) * beta) / sum(exp((x - max(x)) * beta)) \]
Log Softmax is calculated by :
\[ out = (x - max(x) * beta) - log(\sum{e^{x - max(x) * beta}}) \]
This function runs the following kernels:
If axis is not 0:
CLPermute
CLLogits1DNormKernel
CLLogits1DMaxShiftExpSumKernel
Definition at line 58 of file CLSoftmaxLayer.h.
Constructor & Destructor Documentation
CLSoftmaxLayerGeneric() [1/3]
CLSoftmaxLayerGeneric (std::shared_ptr< IMemoryManager > memory_manager = nullptr)
Constructor.
Definition at line 41 of file CLSoftmaxLayer.cpp.
     : _memory_group(std::move(memory_manager)),
       _permute_input(),
       _permute_output(),
       _max_shift_exp_sum_kernel(support::cpp14::make_unique<CLLogits1DMaxShiftExpSumKernel>()),
       _norm_kernel(support::cpp14::make_unique<CLLogits1DNormKernel>()),
       _max(),
       _sum(),
       _tmp(),
       _input_permuted(),
       _output_permuted(),
       _needs_permute()
 {
 }
CLSoftmaxLayerGeneric() [2/3]
CLSoftmaxLayerGeneric (const CLSoftmaxLayerGeneric< IS_LOG > &) delete
Prevent instances of this class from being copied.
CLSoftmaxLayerGeneric() [3/3]
CLSoftmaxLayerGeneric (CLSoftmaxLayerGeneric< IS_LOG > &&) delete
Prevent instances of this class to be moved.
~CLSoftmaxLayerGeneric()
~CLSoftmaxLayerGeneric () default
Default destructor.
Member Function Documentation
configure() [1/2]
void configure (const ICLTensor * input, ICLTensor * output, float beta = 1.0f, int32_t axis = 0)
Set the input and output tensors.
Parameters
[in] input Source tensor. Data types supported: QASYMM8/QASYMM8_SIGNED/F16/F32 for Softmax and F16/F32 for Log Softmax
[out] output Destination tensor. Data types supported: same as input
[in] beta (Optional) A scaling factor for the exponent. Defaults to 1.f
[in] axis (Optional) The dimension in which to apply the function. E.g. for input of shape 4x5x6 and axis=1, softmax will be applied to 4x6=24 vectors of size 5. Defaults to 0
Definition at line 60 of file CLSoftmaxLayer.cpp.
 {
     configure(CLKernelLibrary::get().get_compile_context(), input, output, beta, axis);
 }
References CLKernelLibrary::get(), and arm_compute::test::validation::input.
configure() [2/2]
void configure (const CLCompileContext & compile_context, const ICLTensor * input, ICLTensor * output, float beta = 1.0f, int32_t axis = 0)
Set the input and output tensors.
Parameters
[in] compile_context The compile context to be used.
[in] input Source tensor. Data types supported: QASYMM8/QASYMM8_SIGNED/F16/F32 for Softmax and F16/F32 for Log Softmax
[out] output Destination tensor. Data types supported: same as input
[in] beta (Optional) A scaling factor for the exponent. Defaults to 1.f
[in] axis (Optional) The dimension in which to apply the function. E.g. for input of shape 4x5x6 and axis=1, softmax will be applied to 4x6=24 vectors of size 5. Defaults to 0
Definition at line 66 of file CLSoftmaxLayer.cpp.
 {
     // Perform validation step
     ARM_COMPUTE_ERROR_ON_NULLPTR(input, output);
     ARM_COMPUTE_ERROR_THROW_ON(CLSoftmaxLayerGeneric<IS_LOG>::validate(input->info(), output->info(), beta, axis));
     const size_t actual_axis = static_cast<size_t>(wrap_around(axis, static_cast<int32_t>(input->info()->num_dimensions())));
     _needs_permute              = actual_axis != 0;
     ICLTensor       *tmp_output = output;
     const ICLTensor *tmp_input  = _needs_permute ? &_input_permuted : input;
     if(_needs_permute)
     {
         _memory_group.manage(&_input_permuted);
         _memory_group.manage(&_output_permuted);
         _permute_input.configure(compile_context, input, &_input_permuted, softmax_helpers::get_permutation_vector_from_softmax_axis(actual_axis));
         tmp_output = &_output_permuted;
     }
     // Create intermediate tensors
     DataType   tmp_data_type = is_data_type_quantized_asymmetric(tmp_input->info()->data_type()) ? DataType::S32 : tmp_input->info()->data_type();
     TensorInfo tensor_info_tmp(tmp_input->info()->clone()->set_data_type(tmp_data_type));
     _tmp.allocator()->init(tensor_info_tmp);
     TensorShape max_sum_shape = tmp_input->info()->tensor_shape();
     max_sum_shape.set(0, 1);
     _max.allocator()->init(tmp_input->info()->clone()->set_tensor_shape(max_sum_shape));
     _sum.allocator()->init(tmp_input->info()->clone()->set_tensor_shape(max_sum_shape).set_data_type(tmp_data_type));
     // Set GPU target to kernels
     _max_shift_exp_sum_kernel->set_target(CLScheduler::get().target());
     // Manage intermediate buffers
     _memory_group.manage(&_tmp);
     _memory_group.manage(&_max);
     _memory_group.manage(&_sum);
     SoftmaxKernelInfo softmax_info;
     softmax_info.beta            = beta;
     softmax_info.is_log          = IS_LOG;
     softmax_info.input_data_type = tmp_input->info()->data_type();
     // Configure kernels
     _max_shift_exp_sum_kernel->configure(compile_context, tmp_input, &_max, &_tmp, &_sum, softmax_info);
     _norm_kernel->configure(compile_context, &_tmp, &_sum, tmp_output, softmax_info);
     // Allocate intermediate buffers
     _tmp.allocator()->allocate();
     _max.allocator()->allocate();
     _sum.allocator()->allocate();
     if(_needs_permute)
     {
         _permute_output.configure(compile_context, &_output_permuted, output, softmax_helpers::get_permutation_vector_from_softmax_axis(actual_axis));
         _input_permuted.allocator()->allocate();
         _output_permuted.allocator()->allocate();
     }
 }
References ARM_COMPUTE_ERROR_ON_NULLPTR, ARM_COMPUTE_ERROR_THROW_ON, SoftmaxKernelInfo::beta, ICloneable< T >::clone(), ITensorInfo::data_type(), CLScheduler::get(), arm_compute::softmax_helpers::get_permutation_vector_from_softmax_axis(), ITensor::info(), TensorInfo::init(), arm_compute::test::validation::input, SoftmaxKernelInfo::input_data_type, arm_compute::is_data_type_quantized_asymmetric(), SoftmaxKernelInfo::is_log, arm_compute::S32, TensorShape::set(), ITensorInfo::tensor_shape(), and arm_compute::wrap_around().
operator=() [1/2]
CLSoftmaxLayerGeneric& operator= (const CLSoftmaxLayerGeneric< IS_LOG > &) delete
Prevent instances of this class from being copied.
operator=() [2/2]
CLSoftmaxLayerGeneric& operator= (CLSoftmaxLayerGeneric< IS_LOG > &&) delete
Prevent instances of this class to be moved.
run()
void run () override virtual
Run the kernels contained in the function.
For NEON kernels:
Multi-threading is used for the kernels which are parallelisable.
By default std::thread::hardware_concurrency() threads are used.
Note
CPPScheduler::set_num_threads() can be used to manually set the number of threads
For OpenCL kernels:
All the kernels are enqueued on the queue associated with CLScheduler.
The queue is then flushed.
Note
The function will not block until the kernels are executed. It is the user's responsibility to wait.
Will call prepare() on first run if hasn't been done
Implements IFunction.
Definition at line 164 of file CLSoftmaxLayer.cpp.
 {
     MemoryGroupResourceScope scope_mg(_memory_group);
     if(_needs_permute)
     {
         _permute_input.run();
     }
     CLScheduler::get().enqueue(*_max_shift_exp_sum_kernel, false);
     CLScheduler::get().enqueue(*_norm_kernel, !_needs_permute);
     if(_needs_permute)
     {
         _permute_output.run();
     }
 }
References CLScheduler::enqueue(), and CLScheduler::get().
validate()
Status validate (const ITensorInfo * input, const ITensorInfo * output, float beta = 1.0f, int32_t axis = 0) static
Static function to check if given info will lead to a valid configuration of CLSoftmaxLayer.
Parameters
[in] input Source tensor. Data types supported: QASYMM8/QASYMM8_SIGNED/F16/F32 for Softmax and F16/F32 for Log Softmax
[in] output Destination tensor. Data types supported: same as input
[in] beta (Optional) A scaling factor for the exponent. Defaults to 1.f
[in] axis (Optional) The dimension in which to apply the function. E.g. for input of shape 4x5x6 and axis=1, softmax will be applied to 4x6=24 vectors of size 5. Defaults to 0
Returns
a status
Definition at line 124 of file CLSoftmaxLayer.cpp.
 {
     ARM_COMPUTE_RETURN_ERROR_ON_NULLPTR(input, output);
     ARM_COMPUTE_RETURN_ERROR_ON_MSG(input->num_dimensions() > 4, "Only up to 4 dimensions are supported");
     ARM_COMPUTE_UNUSED(beta);
     ARM_COMPUTE_RETURN_ERROR_ON(axis < static_cast<int32_t>(-input->num_dimensions()) || static_cast<int32_t>(input->num_dimensions()) <= axis);
     const size_t actual_axis   = static_cast<size_t>(wrap_around(axis, static_cast<int32_t>(input->num_dimensions())));
     const bool   needs_permute = actual_axis != 0;
     if(needs_permute)
     {
         const PermutationVector permutation_vector = softmax_helpers::get_permutation_vector_from_softmax_axis(actual_axis);
         const TensorShape       permuted_shape     = misc::shape_calculator::compute_permutation_output_shape(*input, permutation_vector);
         TensorInfo              input_permuted(input->clone()->set_tensor_shape(permuted_shape));
         ARM_COMPUTE_RETURN_ON_ERROR(CLPermute::validate(input, &input_permuted, permutation_vector));
         TensorInfo output_permuted(output->clone()->set_tensor_shape(permuted_shape));
         ARM_COMPUTE_RETURN_ON_ERROR(CLPermute::validate(&output_permuted, output, permutation_vector));
     }
     // Create intermediate tensor info
     DataType   tmp_data_type = is_data_type_quantized_asymmetric(input->data_type()) ? DataType::S32 : input->data_type();
     TensorInfo tensor_info_tmp(input->clone()->set_data_type(tmp_data_type).set_is_resizable(true));
     TensorShape max_sum_shape = input->tensor_shape();
     max_sum_shape.set(0, 1);
     TensorInfo tensor_info_max(input->clone()->set_tensor_shape(max_sum_shape).set_is_resizable(true));
     TensorInfo tensor_info_sum(input->clone()->set_tensor_shape(max_sum_shape).set_data_type(tmp_data_type).set_quantization_info(QuantizationInfo()).set_is_resizable(true));
     SoftmaxKernelInfo softmax_info;
     softmax_info.beta            = beta;
     softmax_info.is_log          = IS_LOG;
     softmax_info.input_data_type = input->data_type();
     ARM_COMPUTE_RETURN_ON_ERROR(CLLogits1DMaxShiftExpSumKernel::validate(input, &tensor_info_max, &tensor_info_tmp, &tensor_info_sum));
     ARM_COMPUTE_RETURN_ON_ERROR(CLLogits1DNormKernel::validate(&tensor_info_tmp, &tensor_info_sum, output, softmax_info));
     return Status{};
 }
References ARM_COMPUTE_RETURN_ERROR_ON, ARM_COMPUTE_RETURN_ERROR_ON_MSG, ARM_COMPUTE_RETURN_ERROR_ON_NULLPTR, ARM_COMPUTE_RETURN_ON_ERROR, ARM_COMPUTE_UNUSED, SoftmaxKernelInfo::beta, ICloneable< T >::clone(), arm_compute::misc::shape_calculator::compute_permutation_output_shape(), arm_compute::softmax_helpers::get_permutation_vector_from_softmax_axis(), arm_compute::test::validation::input, arm_compute::is_data_type_quantized_asymmetric(), arm_compute::S32, CLPermute::validate(), CLLogits1DMaxShiftExpSumKernel::validate(), CLLogits1DNormKernel::validate(), and arm_compute::wrap_around().
The documentation for this class was generated from the following files:
arm_compute/runtime/CL/functions/CLSoftmaxLayer.h
src/runtime/CL/functions/CLSoftmaxLayer.cpp