Compute Library: NESobel5x5 Class Reference
NESobel5x5 Class Reference
Basic function to execute sobel 5x5 filter.
#include <NESobel5x5.h>
Public Member Functions
NESobel5x5 (std::shared_ptr< IMemoryManager > memory_manager=nullptr)
Default constructor.
NESobel5x5 (const NESobel5x5 &)=delete
Prevent instances of this class from being copied (As this class contains pointers)
NESobel5x5 & operator= (const NESobel5x5 &)=delete
Prevent instances of this class from being copied (As this class contains pointers)
NESobel5x5 (NESobel5x5 &&)=delete
Prevent instances of this class from being moved (As this class contains non movable objects)
NESobel5x5 & operator= (NESobel5x5 &&)=delete
Prevent instances of this class from being moved (As this class contains non movable objects)
~NESobel5x5 ()
Default destructor.
void configure (ITensor *input, ITensor *output_x, ITensor *output_y, BorderMode border_mode, uint8_t constant_border_value=0)
Initialise the function's source, destinations and border mode.
void run () override
Run the kernels contained in the function.
Public Member Functions inherited from IFunction
virtual ~IFunction ()=default
Destructor.
virtual void prepare ()
Prepare the function for executing.
Detailed Description
Basic function to execute sobel 5x5 filter.
This function calls the following NEON kernels:
NEFillBorderKernel (executed if border_mode == CONSTANT or border_mode == REPLICATE)
NESobel5x5HorKernel
NESobel5x5VertKernel
Deprecated:
This function is deprecated and is intended to be removed in 21.05 release
Definition at line 52 of file NESobel5x5.h.
Constructor & Destructor Documentation
NESobel5x5() [1/3]
NESobel5x5 (std::shared_ptr< IMemoryManager > memory_manager = nullptr)
Default constructor.
Definition at line 40 of file NESobel5x5.cpp.
     : _memory_group(std::move(memory_manager)), _sobel_hor(), _sobel_vert(), _tmp_x(), _tmp_y(), _border_handler()
 {
 }
NESobel5x5() [2/3]
NESobel5x5 (const NESobel5x5 &) delete
Prevent instances of this class from being copied (As this class contains pointers)
NESobel5x5() [3/3]
NESobel5x5 (NESobel5x5 &&) delete
Prevent instances of this class from being moved (As this class contains non movable objects)
~NESobel5x5()
~NESobel5x5 () default
Default destructor.
Member Function Documentation
configure()
void configure (ITensor * input, ITensor * output_x, ITensor * output_y, BorderMode border_mode, uint8_t constant_border_value = 0)
Initialise the function's source, destinations and border mode.
Note
At least one of output_x or output_y must be not NULL.
Parameters
[in,out] input Source tensor. Data type supported: U8. (Written to only for border_mode != UNDEFINED)
[out] output_x (optional) Destination for the Sobel 5x5 convolution along the X axis. Data type supported: S16.
[out] output_y (optional) Destination for the Sobel 5x5 convolution along the Y axis. Data type supported: S16.
[in] border_mode Border mode to use for the convolution.
[in] constant_border_value (Optional) Constant value to use for borders if border_mode is set to CONSTANT.
Definition at line 45 of file NESobel5x5.cpp.
 {
     ARM_COMPUTE_ERROR_ON_DATA_TYPE_CHANNEL_NOT_IN(input, 1, DataType::U8);
     const bool run_sobel_x = output_x != nullptr;
     const bool run_sobel_y = output_y != nullptr;
     TensorInfo tensor_info(input->info()->tensor_shape(), Format::S16);
     _sobel_hor      = arm_compute::support::cpp14::make_unique<NESobel5x5HorKernel>();
     _sobel_vert     = arm_compute::support::cpp14::make_unique<NESobel5x5VertKernel>();
     _border_handler = arm_compute::support::cpp14::make_unique<NEFillBorderKernel>();
     if(run_sobel_x && run_sobel_y)
     {
         _tmp_x.allocator()->init(tensor_info);
         _tmp_y.allocator()->init(tensor_info);
         _memory_group.manage(&_tmp_x);
         _memory_group.manage(&_tmp_y);
         _sobel_hor->configure(input, &_tmp_x, &_tmp_y, border_mode == BorderMode::UNDEFINED);
         _sobel_vert->configure(&_tmp_x, &_tmp_y, output_x, output_y, border_mode == BorderMode::UNDEFINED);
         _tmp_x.allocator()->allocate();
         _tmp_y.allocator()->allocate();
     }
     else if(run_sobel_x)
     {
         _tmp_x.allocator()->init(tensor_info);
         _memory_group.manage(&_tmp_x);
         _sobel_hor->configure(input, &_tmp_x, nullptr, border_mode == BorderMode::UNDEFINED);
         _sobel_vert->configure(&_tmp_x, nullptr, output_x, nullptr, border_mode == BorderMode::UNDEFINED);
         _tmp_x.allocator()->allocate();
     }
     else if(run_sobel_y)
     {
         _tmp_y.allocator()->init(tensor_info);
         _memory_group.manage(&_tmp_y);
         _sobel_hor->configure(input, nullptr, &_tmp_y, border_mode == BorderMode::UNDEFINED);
         _sobel_vert->configure(nullptr, &_tmp_y, nullptr, output_y, border_mode == BorderMode::UNDEFINED);
         _tmp_y.allocator()->allocate();
     }
     _border_handler->configure(input, _sobel_hor->border_size(), border_mode, PixelValue(constant_border_value));
 }
References TensorAllocator::allocate(), Tensor::allocator(), ARM_COMPUTE_ERROR_ON_DATA_TYPE_CHANNEL_NOT_IN, TensorAllocator::init(), arm_compute::test::validation::input, MemoryGroup::manage(), arm_compute::S16, arm_compute::U8, and arm_compute::UNDEFINED.
operator=() [1/2]
NESobel5x5& operator= (const NESobel5x5 &) delete
Prevent instances of this class from being copied (As this class contains pointers)
operator=() [2/2]
NESobel5x5& operator= (NESobel5x5 &&) delete
Prevent instances of this class from being moved (As this class contains non movable objects)
run()
void run () override virtual
Run the kernels contained in the function.
For NEON kernels:
Multi-threading is used for the kernels which are parallelisable.
By default std::thread::hardware_concurrency() threads are used.
Note
CPPScheduler::set_num_threads() can be used to manually set the number of threads
For OpenCL kernels:
All the kernels are enqueued on the queue associated with CLScheduler.
The queue is then flushed.
Note
The function will not block until the kernels are executed. It is the user's responsibility to wait.
Will call prepare() on first run if hasn't been done
Implements IFunction.
Definition at line 89 of file NESobel5x5.cpp.
 {
     NEScheduler::get().schedule(_border_handler.get(), Window::DimZ);
     MemoryGroupResourceScope scope_mg(_memory_group);
     NEScheduler::get().schedule(_sobel_hor.get(), Window::DimY);
     NEScheduler::get().schedule(_sobel_vert.get(), Window::DimY);
 }
References Window::DimY, Window::DimZ, Scheduler::get(), and IScheduler::schedule().
The documentation for this class was generated from the following files:
arm_compute/runtime/NEON/functions/NESobel5x5.h
src/runtime/NEON/functions/NESobel5x5.cpp