Compute Library: NELaplacianPyramid Class Reference
NELaplacianPyramid Class Reference
Basic function to execute laplacian pyramid.
#include <NELaplacianPyramid.h>
Public Member Functions
NELaplacianPyramid ()
Constructor.
NELaplacianPyramid (const NELaplacianPyramid &)=delete
Prevent instances of this class from being copied (As this class contains pointers)
NELaplacianPyramid & operator= (const NELaplacianPyramid &)=delete
Prevent instances of this class from being copied (As this class contains pointers)
NELaplacianPyramid (NELaplacianPyramid &&)=delete
Prevent instances of this class from being moved (As this class contains non movable objects)
NELaplacianPyramid & operator= (NELaplacianPyramid &&)=delete
Prevent instances of this class from being moved (As this class contains non movable objects)
~NELaplacianPyramid ()
Default destructor.
void configure (const ITensor *input, IPyramid *pyramid, ITensor *output, BorderMode border_mode, uint8_t constant_border_value)
Initialise the function's source, destinations and border mode.
void run () override
Run the kernels contained in the function.
Public Member Functions inherited from IFunction
virtual ~IFunction ()=default
Destructor.
virtual void prepare ()
Prepare the function for executing.
Detailed Description
Basic function to execute laplacian pyramid.
This function calls the following NEON kernels and functions:
NEGaussianPyramidHalf
NEGaussian5x5
NEArithmeticSubtraction
First a Gaussian pyramid is created. Then, for each level i, the corresponding tensor I(i) is blurred with the Gaussian 5x5 filter, and then difference between the two tensors is the corresponding level L(i) of the Laplacian pyramid. L(i) = I(i) - Gaussian5x5(I(i)) Level 0 has always the same first two dimensions as the input tensor.
Deprecated:
This function is deprecated and is intended to be removed in 21.05 release
Definition at line 57 of file NELaplacianPyramid.h.
Constructor & Destructor Documentation
NELaplacianPyramid() [1/3]
NELaplacianPyramid ()
Constructor.
Definition at line 42 of file NELaplacianPyramid.cpp.
     : _num_levels(0),
       _gaussian_pyr_function(),
       _convf(),
       _subf(),
       _gauss_pyr(),
       _conv_pyr(),
       _depth_function()
 {
 }
NELaplacianPyramid() [2/3]
NELaplacianPyramid (const NELaplacianPyramid &) delete
Prevent instances of this class from being copied (As this class contains pointers)
NELaplacianPyramid() [3/3]
NELaplacianPyramid (NELaplacianPyramid &&) delete
Prevent instances of this class from being moved (As this class contains non movable objects)
~NELaplacianPyramid()
~NELaplacianPyramid () default
Default destructor.
Member Function Documentation
configure()
void configure (const ITensor * input, IPyramid * pyramid, ITensor * output, BorderMode border_mode, uint8_t constant_border_value)
Initialise the function's source, destinations and border mode.
Parameters
[in] input Source tensor. Data type supported: U8.
[out] pyramid Destination pyramid tensors, Data type supported at each level: S16.
[out] output The lowest resolution tensor necessary to reconstruct the input tensor from the pyramid. Data type supported: S16. The first two dimensions of this tensor must match the first two dimensions of the tensor in the last level of the pyramid, that is: out.width = in.width() / pow(2,pyramid_levels-1) and out.height = in.height() / pow(2,pyramid_levels-1)
[in] border_mode Border mode to use.
[in] constant_border_value (Optional) Constant value to use for borders if border_mode is set to CONSTANT.
Definition at line 75 of file NELaplacianPyramid.cpp.
 {
     ARM_COMPUTE_ERROR_ON(nullptr == pyramid);
     ARM_COMPUTE_ERROR_ON_DATA_TYPE_CHANNEL_NOT_IN(input, 1, DataType::U8);
     ARM_COMPUTE_ERROR_ON_DATA_TYPE_CHANNEL_NOT_IN(output, 1, DataType::S16);
     ARM_COMPUTE_ERROR_ON(0 == pyramid->info()->num_levels());
     ARM_COMPUTE_ERROR_ON(input->info()->dimension(0) != pyramid->info()->width());
     ARM_COMPUTE_ERROR_ON(input->info()->dimension(1) != pyramid->info()->height());
     ARM_COMPUTE_ERROR_ON(output->info()->dimension(0) != pyramid->get_pyramid_level(pyramid->info()->num_levels() - 1)->info()->dimension(0));
     ARM_COMPUTE_ERROR_ON(output->info()->dimension(1) != pyramid->get_pyramid_level(pyramid->info()->num_levels() - 1)->info()->dimension(1));
     _num_levels = pyramid->info()->num_levels();
     // Create and initialize the gaussian pyramid and the convoluted pyramid
     PyramidInfo pyramid_info;
     pyramid_info.init(_num_levels, 0.5f, pyramid->info()->tensor_shape(), arm_compute::Format::U8);
     _gauss_pyr.init(pyramid_info);
     _conv_pyr.init(pyramid_info);
     // Create Gaussian Pyramid function
     _gaussian_pyr_function.configure(input, &_gauss_pyr, border_mode, constant_border_value);
     _convf.resize(_num_levels);
     _subf.resize(_num_levels);
     for(unsigned int i = 0; i < _num_levels; ++i)
     {
         _convf[i].configure(_gauss_pyr.get_pyramid_level(i), _conv_pyr.get_pyramid_level(i), border_mode, constant_border_value);
         _subf[i].configure(_gauss_pyr.get_pyramid_level(i), _conv_pyr.get_pyramid_level(i), pyramid->get_pyramid_level(i), ConvertPolicy::WRAP);
     }
     _depth_function.configure(_conv_pyr.get_pyramid_level(_num_levels - 1), output, ConvertPolicy::WRAP, 0);
     _gauss_pyr.allocate();
     _conv_pyr.allocate();
 }
References Pyramid::allocate(), ARM_COMPUTE_ERROR_ON, ARM_COMPUTE_ERROR_ON_DATA_TYPE_CHANNEL_NOT_IN, NEDepthConvertLayer::configure(), NEGaussianPyramidHalf::configure(), ITensorInfo::dimension(), IPyramid::get_pyramid_level(), Pyramid::get_pyramid_level(), PyramidInfo::height(), ITensor::info(), IPyramid::info(), arm_compute::test::validation::info, Pyramid::init(), PyramidInfo::init(), arm_compute::test::validation::input, PyramidInfo::num_levels(), arm_compute::S16, PyramidInfo::tensor_shape(), arm_compute::U8, PyramidInfo::width(), and arm_compute::WRAP.
operator=() [1/2]
NELaplacianPyramid& operator= (const NELaplacianPyramid &) delete
Prevent instances of this class from being copied (As this class contains pointers)
operator=() [2/2]
NELaplacianPyramid& operator= (NELaplacianPyramid &&) delete
Prevent instances of this class from being moved (As this class contains non movable objects)
run()
void run () override virtual
Run the kernels contained in the function.
For NEON kernels:
Multi-threading is used for the kernels which are parallelisable.
By default std::thread::hardware_concurrency() threads are used.
Note
CPPScheduler::set_num_threads() can be used to manually set the number of threads
For OpenCL kernels:
All the kernels are enqueued on the queue associated with CLScheduler.
The queue is then flushed.
Note
The function will not block until the kernels are executed. It is the user's responsibility to wait.
Will call prepare() on first run if hasn't been done
Implements IFunction.
Definition at line 53 of file NELaplacianPyramid.cpp.
 {
     ARM_COMPUTE_ERROR_ON_MSG(0 == _num_levels, "Unconfigured function");
     // Compute Gaussian Pyramid
     _gaussian_pyr_function.run();
     for(unsigned int i = 0; i < _num_levels; ++i)
     {
         // Apply Gaussian filter to gaussian pyramid image
         _convf[i].run();
     }
     for(unsigned int i = 0; i < _num_levels; ++i)
     {
         // Compute laplacian image
         _subf[i].run();
     }
     _depth_function.run();
 }
References ARM_COMPUTE_ERROR_ON_MSG, INESimpleFunctionNoBorder::run(), and NEGaussianPyramidHalf::run().
The documentation for this class was generated from the following files:
arm_compute/runtime/NEON/functions/NELaplacianPyramid.h
src/runtime/NEON/functions/NELaplacianPyramid.cpp