Compute Library: CLLogicalBinaryKernel Class Reference
CLLogicalBinaryKernel Class Reference
#include <CLElementwiseOperationKernel.h>
Public Member Functions
CLLogicalBinaryKernel ()=default
Default constructor.
CLLogicalBinaryKernel (const CLLogicalBinaryKernel &)=delete
Prevent instances of this class from being copied (As this class contains pointers)
CLLogicalBinaryKernel & operator= (const CLLogicalBinaryKernel &)=delete
Prevent instances of this class from being copied (As this class contains pointers)
CLLogicalBinaryKernel (CLLogicalBinaryKernel &&)=default
Allow instances of this class to be moved.
CLLogicalBinaryKernel & operator= (CLLogicalBinaryKernel &&)=default
Allow instances of this class to be moved.
~CLLogicalBinaryKernel ()=default
Default destructor.
void configure (const CLCompileContext &compile_context, kernels::LogicalOperation op, ITensorInfo *input1, ITensorInfo *input2, ITensorInfo *output)
Function to configure kernel.
Public Member Functions inherited from CLElementwiseOperationKernel
CLElementwiseOperationKernel ()
Default constructor.
CLElementwiseOperationKernel (const CLElementwiseOperationKernel &)=delete
Prevent instances of this class from being copied (As this class contains pointers)
CLElementwiseOperationKernel & operator= (const CLElementwiseOperationKernel &)=delete
Prevent instances of this class from being copied (As this class contains pointers)
CLElementwiseOperationKernel (CLElementwiseOperationKernel &&)=default
Allow instances of this class to be moved.
CLElementwiseOperationKernel & operator= (CLElementwiseOperationKernel &&)=default
Allow instances of this class to be moved.
~CLElementwiseOperationKernel ()=default
Default destructor.
void run_op (ITensorPack &tensors, const Window &window, cl::CommandQueue &queue) override
Enqueue the OpenCL kernel to process the given window on the passed OpenCL command queue.
Public Member Functions inherited from ICLKernel
ICLKernel ()
Constructor.
cl::Kernel & kernel ()
Returns a reference to the OpenCL kernel of this object.
template<typename T >
void add_1D_array_argument (unsigned int &idx, const ICLArray< T > *array, const Strides &strides, unsigned int num_dimensions, const Window &window)
Add the passed 1D array's parameters to the object's kernel's arguments starting from the index idx.
void add_1D_tensor_argument (unsigned int &idx, const ICLTensor *tensor, const Window &window)
Add the passed 1D tensor's parameters to the object's kernel's arguments starting from the index idx.
void add_1D_tensor_argument_if (bool cond, unsigned int &idx, const ICLTensor *tensor, const Window &window)
Add the passed 1D tensor's parameters to the object's kernel's arguments starting from the index idx if the condition is true.
void add_2D_tensor_argument (unsigned int &idx, const ICLTensor *tensor, const Window &window)
Add the passed 2D tensor's parameters to the object's kernel's arguments starting from the index idx.
void add_2D_tensor_argument_if (bool cond, unsigned int &idx, const ICLTensor *tensor, const Window &window)
Add the passed 2D tensor's parameters to the object's kernel's arguments starting from the index idx if the condition is true.
void add_3D_tensor_argument (unsigned int &idx, const ICLTensor *tensor, const Window &window)
Add the passed 3D tensor's parameters to the object's kernel's arguments starting from the index idx.
void add_4D_tensor_argument (unsigned int &idx, const ICLTensor *tensor, const Window &window)
Add the passed 4D tensor's parameters to the object's kernel's arguments starting from the index idx.
virtual void run (const Window &window, cl::CommandQueue &queue)
Enqueue the OpenCL kernel to process the given window on the passed OpenCL command queue.
template<typename T >
void add_argument (unsigned int &idx, T value)
Add the passed parameters to the object's kernel's arguments starting from the index idx.
void set_lws_hint (const cl::NDRange &lws_hint)
Set the Local-Workgroup-Size hint.
cl::NDRange lws_hint () const
Return the Local-Workgroup-Size hint.
const std::string & config_id () const
Get the configuration ID.
void set_target (GPUTarget target)
Set the targeted GPU architecture.
void set_target (cl::Device &device)
Set the targeted GPU architecture according to the CL device.
GPUTarget get_target () const
Get the targeted GPU architecture.
size_t get_max_workgroup_size ()
Get the maximum workgroup size for the device the CLKernelLibrary uses.
template<unsigned int dimension_size>
void add_tensor_argument (unsigned &idx, const ICLTensor *tensor, const Window &window)
template<typename T , unsigned int dimension_size>
void add_array_argument (unsigned &idx, const ICLArray< T > *array, const Strides &strides, unsigned int num_dimensions, const Window &window)
Add the passed array's parameters to the object's kernel's arguments starting from the index idx.
Public Member Functions inherited from IKernel
IKernel ()
Constructor.
virtual ~IKernel ()=default
Destructor.
virtual bool is_parallelisable () const
Indicates whether or not the kernel is parallelisable.
virtual BorderSize border_size () const
The size of the border for that kernel.
const Window & window () const
The maximum window the kernel can be executed on.
Static Public Member Functions
static Status validate (kernels::LogicalOperation op, const ITensorInfo *input1, const ITensorInfo *input2, const ITensorInfo *output)
Static function to check if the given configuration is valid for this kernel.
Static Public Member Functions inherited from ICLKernel
static constexpr unsigned int num_arguments_per_1D_array ()
Returns the number of arguments enqueued per 1D array object.
static constexpr unsigned int num_arguments_per_1D_tensor ()
Returns the number of arguments enqueued per 1D tensor object.
static constexpr unsigned int num_arguments_per_2D_tensor ()
Returns the number of arguments enqueued per 2D tensor object.
static constexpr unsigned int num_arguments_per_3D_tensor ()
Returns the number of arguments enqueued per 3D tensor object.
static constexpr unsigned int num_arguments_per_4D_tensor ()
Returns the number of arguments enqueued per 4D tensor object.
static cl::NDRange gws_from_window (const Window &window)
Get the global work size given an execution window.
Detailed Description
Definition at line 103 of file CLElementwiseOperationKernel.h.
Constructor & Destructor Documentation
CLLogicalBinaryKernel() [1/3]
CLLogicalBinaryKernel () default
Default constructor.
CLLogicalBinaryKernel() [2/3]
CLLogicalBinaryKernel (const CLLogicalBinaryKernel &) delete
Prevent instances of this class from being copied (As this class contains pointers)
CLLogicalBinaryKernel() [3/3]
CLLogicalBinaryKernel (CLLogicalBinaryKernel &&) default
Allow instances of this class to be moved.
~CLLogicalBinaryKernel()
~CLLogicalBinaryKernel () default
Default destructor.
Member Function Documentation
configure()
void configure (const CLCompileContext & compile_context, kernels::LogicalOperation op, ITensorInfo * input1, ITensorInfo * input2, ITensorInfo * output)
Function to configure kernel.
Logical binary.
Parameters
[in] compile_context The compile context to be used.
[in] op Logical binary operation to be executed.
[in] input1 First tensor input info. Data types supported: U8.
[in] input2 Second tensor input info. Data types supported: U8.
[in] output Output tensor info. Data types supported: U8.
Definition at line 336 of file CLElementwiseOperationKernel.cpp.
 {
     ARM_COMPUTE_ERROR_ON_NULLPTR(input1, input2, output);
     ARM_COMPUTE_ERROR_THROW_ON(CLLogicalBinaryKernel::validate(op, input1, input2, output));
     _op = op;
     configure_common(compile_context, input1, input2, output);
 }
References ARM_COMPUTE_ERROR_ON_NULLPTR, ARM_COMPUTE_ERROR_THROW_ON, and CLLogicalBinaryKernel::validate().
operator=() [1/2]
CLLogicalBinaryKernel& operator= (const CLLogicalBinaryKernel &) delete
Prevent instances of this class from being copied (As this class contains pointers)
operator=() [2/2]
CLLogicalBinaryKernel& operator= (CLLogicalBinaryKernel &&) default
Allow instances of this class to be moved.
validate()
Status validate (kernels::LogicalOperation op, const ITensorInfo * input1, const ITensorInfo * input2, const ITensorInfo * output) static
Static function to check if the given configuration is valid for this kernel.
Parameters
[in] op Logical binary operation to be executed.
[in] input1 First tensor input info. Data types supported: U8.
[in] input2 Second tensor input info. Data types supported: U8.
[in] output Output tensor info. Data types supported: U8.
Definition at line 344 of file CLElementwiseOperationKernel.cpp.
 {
     ARM_COMPUTE_UNUSED(op);
     ARM_COMPUTE_ASSERT(op != kernels::LogicalOperation::Unknown && op != kernels::LogicalOperation::Not);
     ARM_COMPUTE_RETURN_ERROR_ON_NULLPTR(input1, input2, output);
     ARM_COMPUTE_RETURN_ERROR_ON_DATA_TYPE_CHANNEL_NOT_IN(input1, 1, DataType::U8);
     ARM_COMPUTE_RETURN_ERROR_ON_MISMATCHING_DATA_TYPES(input1, input2);
     ARM_COMPUTE_RETURN_ON_ERROR(validate_arguments_with_arithmetic_rules(*input1, *input2, *output));
     ARM_COMPUTE_RETURN_ON_ERROR(validate_and_configure_window_for_logical_binary_operators(*input1->clone(), *input2->clone(), *output->clone()).first);
     return Status{};
 }
References ARM_COMPUTE_ASSERT, ARM_COMPUTE_RETURN_ERROR_ON_DATA_TYPE_CHANNEL_NOT_IN, ARM_COMPUTE_RETURN_ERROR_ON_MISMATCHING_DATA_TYPES, ARM_COMPUTE_RETURN_ERROR_ON_NULLPTR, ARM_COMPUTE_RETURN_ON_ERROR, ARM_COMPUTE_UNUSED, ICloneable< T >::clone(), arm_compute::kernels::Not, arm_compute::U8, and arm_compute::kernels::Unknown.
Referenced by CLLogicalBinaryKernel::configure(), CLLogicalOr::validate(), and CLLogicalAnd::validate().
The documentation for this class was generated from the following files:
src/core/CL/kernels/CLElementwiseOperationKernel.h
src/core/CL/kernels/CLElementwiseOperationKernel.cpp