Compute Library: NEArithmeticAddition Class Reference
NEArithmeticAddition Class Reference
Basic function to run NEArithmeticAdditionKernel.
#include <NEArithmeticAddition.h>
Public Member Functions
NEArithmeticAddition ()=default
Constructor.
NEArithmeticAddition (const NEArithmeticAddition &)=delete
Prevent instances of this class from being copied (As this class contains pointers)
NEArithmeticAddition & operator= (const NEArithmeticAddition &)=delete
Prevent instances of this class from being copied (As this class contains pointers)
NEArithmeticAddition (NEArithmeticAddition &&)=delete
Prevent instances of this class from being moved (As this class contains non movable objects)
NEArithmeticAddition & operator= (NEArithmeticAddition &&)=delete
Prevent instances of this class from being moved (As this class contains non movable objects)
~NEArithmeticAddition ()
Default destructor.
void configure (const ITensorInfo *input1, const ITensorInfo *input2, ITensorInfo *output, ConvertPolicy policy, const ActivationLayerInfo &act_info=ActivationLayerInfo())
Initialise the kernel's inputs, output and conversion policy.
Public Member Functions inherited from INEOperator
INEOperator (IRuntimeContext *ctx=nullptr)
Constructor.
INEOperator (const INEOperator &)=delete
Prevent instances of this class from being copied (As this class contains pointers)
INEOperator (INEOperator &&)=default
Default move constructor.
INEOperator & operator= (const INEOperator &)=delete
Prevent instances of this class from being copied (As this class contains pointers)
INEOperator & operator= (INEOperator &&)=default
Default move assignment operator.
~INEOperator ()
Default destructor.
void run (ITensorPack &tensors) override
Run the kernels contained in the function.
void prepare (ITensorPack &constants) override
Prepare the function for executing.
MemoryRequirements workspace () const override
Return the memory requirements required by the workspace.
Public Member Functions inherited from IOperator
virtual ~IOperator ()=default
Destructor.
Static Public Member Functions
static Status validate (const ITensorInfo *input1, const ITensorInfo *input2, const ITensorInfo *output, ConvertPolicy policy, const ActivationLayerInfo &act_info=ActivationLayerInfo())
Static function to check if given info will lead to a valid configuration of NEArithmeticAddition.
Detailed Description
Basic function to run NEArithmeticAdditionKernel.
Definition at line 38 of file NEArithmeticAddition.h.
Constructor & Destructor Documentation
NEArithmeticAddition() [1/3]
NEArithmeticAddition () default
Constructor.
NEArithmeticAddition() [2/3]
NEArithmeticAddition (const NEArithmeticAddition &) delete
Prevent instances of this class from being copied (As this class contains pointers)
NEArithmeticAddition() [3/3]
NEArithmeticAddition (NEArithmeticAddition &&) delete
Prevent instances of this class from being moved (As this class contains non movable objects)
~NEArithmeticAddition()
~NEArithmeticAddition () default
Default destructor.
Member Function Documentation
configure()
void configure (const ITensorInfo * input1, const ITensorInfo * input2, ITensorInfo * output, ConvertPolicy policy, const ActivationLayerInfo & act_info = ActivationLayerInfo())
Initialise the kernel's inputs, output and conversion policy.
Valid configurations (Input1,Input2) -> Output :
(U8,U8) -> U8
(U8,U8) -> S16
(S16,U8) -> S16
(U8,S16) -> S16
(S16,S16) -> S16
(S32,S32) -> S32
(F16,F16) -> F16
(F32,F32) -> F32
(QASYMM8,QASYMM8) -> QASYMM8
(QASYMM8_SIGNED,QASYMM8_SIGNED) -> QASYMM8_SIGNED
(QSYMM16,QSYMM16) -> QSYMM16
Parameters
[in] input1 First tensor input info. Data types supported: U8/QASYMM8/QASYMM8_SIGNED/S16/QSYMM16/F16/S32/F32
[in] input2 Second tensor input info. Data types supported: U8/QASYMM8/QASYMM8_SIGNED/S16/QSYMM16/F16/S32/F32
[out] output Output tensor info. Data types supported: U8/QASYMM8/QASYMM8_SIGNED/S16/QSYMM16/F16/S32/F32
[in] policy Policy to use to handle overflow.
[in] act_info (Optional) Activation layer information in case of a fused activation. Currently not supported.
Definition at line 38 of file NEArithmeticAddition.cpp.
 {
     ARM_COMPUTE_UNUSED(act_info);
     auto k = arm_compute::support::cpp14::make_unique<NEArithmeticAdditionKernel>();
     k->configure(input1, input2, output, policy);
     _kernel = std::move(k);
 }
References ARM_COMPUTE_UNUSED.
operator=() [1/2]
NEArithmeticAddition& operator= (const NEArithmeticAddition &) delete
Prevent instances of this class from being copied (As this class contains pointers)
operator=() [2/2]
NEArithmeticAddition& operator= (NEArithmeticAddition &&) delete
Prevent instances of this class from being moved (As this class contains non movable objects)
validate()
Status validate (const ITensorInfo * input1, const ITensorInfo * input2, const ITensorInfo * output, ConvertPolicy policy, const ActivationLayerInfo & act_info = ActivationLayerInfo()) static
Static function to check if given info will lead to a valid configuration of NEArithmeticAddition.
Parameters
[in] input1 First tensor input info. Data types supported: U8/QASYMM8/QASYMM8_SIGNED/S16/QSYMM16/F16/S32/F32
[in] input2 Second tensor input info. Data types supported: U8/QASYMM8/QASYMM8_SIGNED/S16/QSYMM16/F16/S32/F32
[in] output Output tensor info. Data types supported: U8/SQASYMM8/QASYMM8_SIGNED/S16/QSYMM16/F16/S32/F32
[in] policy Policy to use to handle overflow
[in] act_info (Optional) Activation layer information in case of a fused activation. Currently not supported.
Returns
a status
Definition at line 45 of file NEArithmeticAddition.cpp.
 {
     ARM_COMPUTE_RETURN_ERROR_ON(act_info.enabled());
     return NEArithmeticAdditionKernel::validate(input1, input2, output, policy);
 }
References ARM_COMPUTE_RETURN_ERROR_ON, ActivationLayerInfo::enabled(), and NEArithmeticAdditionKernel::validate().
Referenced by NEArithmeticAddition::validate().
The documentation for this class was generated from the following files:
arm_compute/runtime/NEON/functions/NEArithmeticAddition.h
src/runtime/NEON/functions/NEArithmeticAddition.cpp