Compute Library: NELocallyConnectedLayer Class Reference
NELocallyConnectedLayer Class Reference
Basic function to compute the locally connected layer.
#include <NELocallyConnectedLayer.h>
Public Member Functions
NELocallyConnectedLayer (std::shared_ptr< IMemoryManager > memory_manager=nullptr)
Default constructor.
NELocallyConnectedLayer (const NELocallyConnectedLayer &)=delete
Prevent instances of this class from being copied (As this class contains pointers)
NELocallyConnectedLayer (NELocallyConnectedLayer &&)=delete
Prevent instances of this class from being moved (As this class contains pointers)
NELocallyConnectedLayer & operator= (const NELocallyConnectedLayer &)=delete
Prevent instances of this class from being copied (As this class contains pointers)
NELocallyConnectedLayer & operator= (NELocallyConnectedLayer &&)=delete
Prevent instances of this class from being moved (As this class contains pointers)
~NELocallyConnectedLayer ()
Default destructor.
void configure (const ITensor *input, const ITensor *weights, const ITensor *biases, ITensor *output, const PadStrideInfo &conv_info)
Set the input and output tensors.
void run () override
Run the kernels contained in the function.
void prepare () override
Prepare the function for executing.
Public Member Functions inherited from IFunction
virtual ~IFunction ()=default
Destructor.
Static Public Member Functions
static Status validate (const ITensorInfo *input, const ITensorInfo *weights, const ITensorInfo *biases, const ITensorInfo *output, const PadStrideInfo &conv_info)
Static function to check if given info will lead to a valid configuration of NELocallyConnectedLayer.
Detailed Description
Basic function to compute the locally connected layer.
This function calls the following NEON kernels:
NEWeightsReshapeKernel (executed only once for each configuration)
NEIm2ColKernel
NELocallyConnectedMatrixMultiplyKernel
NECol2ImKernel
Definition at line 51 of file NELocallyConnectedLayer.h.
Constructor & Destructor Documentation
NELocallyConnectedLayer() [1/3]
NELocallyConnectedLayer (std::shared_ptr< IMemoryManager > memory_manager = nullptr)
Default constructor.
Definition at line 79 of file NELocallyConnectedLayer.cpp.
     : _memory_group(std::move(memory_manager)), _input_im2col(), _weights_reshape_kernel(), _mm_kernel(), _output_col2im(), _input_im2col_reshaped(), _weights_reshaped(), _gemm_output(),
       _is_prepared(false), _original_weights(nullptr)
 {
 }
NELocallyConnectedLayer() [2/3]
NELocallyConnectedLayer (const NELocallyConnectedLayer &) delete
Prevent instances of this class from being copied (As this class contains pointers)
NELocallyConnectedLayer() [3/3]
NELocallyConnectedLayer (NELocallyConnectedLayer &&) delete
Prevent instances of this class from being moved (As this class contains pointers)
~NELocallyConnectedLayer()
~NELocallyConnectedLayer () default
Default destructor.
Member Function Documentation
configure()
void configure (const ITensor * input, const ITensor * weights, const ITensor * biases, ITensor * output, const PadStrideInfo & conv_info)
Set the input and output tensors.
Parameters
[in] input Source tensor. 3 lower dimensions represent a single input [width, height, IFM], while every optional dimension from 4 and above represent a batch of inputs. Data types supported: F16, F32.
[in] weights Weights tensor. Weights are 5D tensor with dimensions [kernel_x, kernel_y, IFM, OFM, num_patches]. Data type supported:Same as input.
[in] biases Biases tensor. Shared biases supported. Biases are 2D tensor with dimensions [OFM, num_patches]. Data type supported:Same as input.
[out] output Destination tensor. 3 lower dimensions represent a single output [width, height, OFM], while the rest represent batch of outputs. Data types supported: Same as input.
[in] conv_info Contains padding and stride information described in PadStrideInfo.
Definition at line 129 of file NELocallyConnectedLayer.cpp.
 {
     ARM_COMPUTE_ERROR_ON_NULLPTR(input, weights, output);
     ARM_COMPUTE_ERROR_THROW_ON(NELocallyConnectedLayer::validate(input->info(), weights->info(), biases == nullptr ? nullptr : biases->info(), output->info(), conv_info));
     bool _has_bias    = (biases != nullptr);
     _is_prepared      = false;
     _original_weights = weights;
     const unsigned int kernel_width  = weights->info()->dimension(0);
     const unsigned int kernel_height = weights->info()->dimension(1);
     // Get convolved dimensions
     unsigned int conv_w = 0;
     unsigned int conv_h = 0;
     std::tie(conv_w, conv_h) = scaled_dimensions(input->info()->dimension(0), input->info()->dimension(1), kernel_width, kernel_height,
                                                  conv_info);
     // Calculate intermediate buffer shapes
     TensorShape shape_wr;
     TensorShape shape_im2col;
     TensorShape shape_gemm;
     calculate_shapes(input->info(), weights->info(), biases == nullptr ? nullptr : biases->info(), output->info(), conv_info, shape_wr, shape_im2col, shape_gemm);
     _weights_reshaped.allocator()->init(TensorInfo(shape_wr, 1, weights->info()->data_type()));
     _input_im2col_reshaped.allocator()->init(TensorInfo(shape_im2col, 1, input->info()->data_type()));
     _gemm_output.allocator()->init(TensorInfo(shape_gemm, 1, input->info()->data_type()));
     // Manage intermediate buffers
     _memory_group.manage(&_input_im2col_reshaped);
     _memory_group.manage(&_gemm_output);
     // Configure kernels
     _input_im2col.configure(input, &_input_im2col_reshaped, Size2D(kernel_width, kernel_height), conv_info, _has_bias);
     _weights_reshape_kernel = arm_compute::support::cpp14::make_unique<NEWeightsReshapeKernel>();
     _weights_reshape_kernel->configure(weights, biases, &_weights_reshaped);
     _mm_kernel = arm_compute::support::cpp14::make_unique<NELocallyConnectedMatrixMultiplyKernel>();
     _mm_kernel->configure(&_input_im2col_reshaped, &_weights_reshaped, &_gemm_output);
     _output_col2im.configure(&_gemm_output, output, Size2D(conv_w, conv_h));
     // Allocate intermediate tensors
     _input_im2col_reshaped.allocator()->allocate();
     _gemm_output.allocator()->allocate();
 }
References TensorAllocator::allocate(), Tensor::allocator(), ARM_COMPUTE_ERROR_ON_NULLPTR, ARM_COMPUTE_ERROR_THROW_ON, NECol2Im::configure(), NEIm2Col::configure(), arm_compute::test::validation::conv_info, ITensorInfo::data_type(), ITensorInfo::dimension(), ITensor::info(), TensorAllocator::init(), arm_compute::test::validation::input, MemoryGroup::manage(), arm_compute::scaled_dimensions(), and NELocallyConnectedLayer::validate().
operator=() [1/2]
NELocallyConnectedLayer& operator= (const NELocallyConnectedLayer &) delete
Prevent instances of this class from being copied (As this class contains pointers)
operator=() [2/2]
NELocallyConnectedLayer& operator= (NELocallyConnectedLayer &&) delete
Prevent instances of this class from being moved (As this class contains pointers)
prepare()
void prepare () override virtual
Prepare the function for executing.
Any one off pre-processing step required by the function is handled here
Note
Prepare stage might not need all the function's buffers' backing memory to be available in order to execute
Reimplemented from IFunction.
Definition at line 190 of file NELocallyConnectedLayer.cpp.
 {
     if(!_is_prepared)
     {
         ARM_COMPUTE_ERROR_ON(!_original_weights->is_used());
         // Run weights reshaping and mark original weights tensor as unused
         _weights_reshaped.allocator()->allocate();
         NEScheduler::get().schedule(_weights_reshape_kernel.get(), 3);
         _original_weights->mark_as_unused();
         _is_prepared = true;
     }
 }
References TensorAllocator::allocate(), Tensor::allocator(), ARM_COMPUTE_ERROR_ON, Scheduler::get(), ITensor::is_used(), ITensor::mark_as_unused(), and IScheduler::schedule().
Referenced by NELocallyConnectedLayer::run().
run()
void run () override virtual
Run the kernels contained in the function.
For NEON kernels:
Multi-threading is used for the kernels which are parallelisable.
By default std::thread::hardware_concurrency() threads are used.
Note
CPPScheduler::set_num_threads() can be used to manually set the number of threads
For OpenCL kernels:
All the kernels are enqueued on the queue associated with CLScheduler.
The queue is then flushed.
Note
The function will not block until the kernels are executed. It is the user's responsibility to wait.
Will call prepare() on first run if hasn't been done
Implements IFunction.
Definition at line 174 of file NELocallyConnectedLayer.cpp.
 {
     prepare();
     MemoryGroupResourceScope scope_mg(_memory_group);
     // Run input reshaping
     _input_im2col.run();
     // Runs GEMM on reshaped matrices
     NEScheduler::get().schedule(_mm_kernel.get(), Window::DimX);
     // Reshape output matrix
     _output_col2im.run();
 }
References Window::DimX, Scheduler::get(), NELocallyConnectedLayer::prepare(), INESimpleFunctionNoBorder::run(), NEIm2Col::run(), and IScheduler::schedule().
validate()
Status validate (const ITensorInfo * input, const ITensorInfo * weights, const ITensorInfo * biases, const ITensorInfo * output, const PadStrideInfo & conv_info) static
Static function to check if given info will lead to a valid configuration of NELocallyConnectedLayer.
Parameters
[in] input Input tensor info. 3 lower dimensions represent a single input [width, height, IFM], while every optional dimension from 4 and above represent a batch of inputs. Data types supported: F16, F32.
[in] weights Weights tensor info. Weights are 5D tensor with dimensions [kernel_x, kernel_y, IFM, OFM, num_patches]. Data type supported:Same as input.
[in] biases Biases tensor info. Shared biases supported. Biases are 2D tensor with dimensions [OFM, num_patches]. Data type supported:Same as input.
[in] output Output tensor info. 3 lower dimensions represent a single output [width, height, OFM], while the rest represent batch of outputs. Data types supported: Same as input.
[in] conv_info Contains padding and stride information described in PadStrideInfo.
Returns
a status
Definition at line 85 of file NELocallyConnectedLayer.cpp.
 {
     ARM_COMPUTE_RETURN_ERROR_ON_NULLPTR(input, weights, output);
     ARM_COMPUTE_RETURN_ERROR_ON(weights->dimension(2) != input->dimension(2));
     ARM_COMPUTE_RETURN_ERROR_ON(!conv_info.padding_is_symmetric());
     bool has_bias = (biases != nullptr);
     if(has_bias)
     {
         ARM_COMPUTE_RETURN_ERROR_ON(biases->dimension(0) != weights->dimension(3));
         ARM_COMPUTE_RETURN_ERROR_ON(biases->num_dimensions() > 2);
     }
     const unsigned int kernel_width  = weights->dimension(0);
     const unsigned int kernel_height = weights->dimension(1);
     // Get convolved dimensions
     unsigned int conv_w = 0;
     unsigned int conv_h = 0;
     std::tie(conv_w, conv_h) = scaled_dimensions(input->dimension(0), input->dimension(1), kernel_width, kernel_height,
                                                  conv_info);
     ARM_COMPUTE_RETURN_ERROR_ON_MSG((output->dimension(0) != conv_w) || (output->dimension(1) != conv_h), "Output shape does not match the expected one");
     ARM_COMPUTE_RETURN_ERROR_ON_MSG(weights->dimension(4) != (conv_w * conv_h), "Weights shape does not match the expected one");
     // Calculate intermediate buffer shapes
     TensorShape shape_wr;
     TensorShape shape_im2col;
     TensorShape shape_gemm;
     calculate_shapes(input, weights, biases, output, conv_info, shape_wr, shape_im2col, shape_gemm);
     TensorInfo weights_reshaped_info(shape_wr, 1, weights->data_type());
     TensorInfo input_im2col_reshaped_info(shape_im2col, 1, input->data_type());
     TensorInfo gemm_output_info(shape_gemm, 1, input->data_type());
     ARM_COMPUTE_RETURN_ON_ERROR(NEIm2Col::validate(input, &input_im2col_reshaped_info, Size2D(kernel_width, kernel_height), conv_info, has_bias));
     ARM_COMPUTE_RETURN_ON_ERROR(NEWeightsReshapeKernel::validate(weights, biases, &weights_reshaped_info));
     ARM_COMPUTE_RETURN_ON_ERROR(NELocallyConnectedMatrixMultiplyKernel::validate(&input_im2col_reshaped_info, &weights_reshaped_info, &gemm_output_info));
     ARM_COMPUTE_RETURN_ON_ERROR(NECol2Im::validate(&gemm_output_info, output, Size2D(conv_w, conv_h)));
     return Status{};
 }
References ARM_COMPUTE_RETURN_ERROR_ON, ARM_COMPUTE_RETURN_ERROR_ON_MSG, ARM_COMPUTE_RETURN_ERROR_ON_NULLPTR, ARM_COMPUTE_RETURN_ON_ERROR, arm_compute::test::validation::conv_info, ITensorInfo::data_type(), ITensorInfo::dimension(), arm_compute::test::validation::has_bias, arm_compute::test::validation::input, ITensorInfo::num_dimensions(), arm_compute::scaled_dimensions(), NECol2Im::validate(), NELocallyConnectedMatrixMultiplyKernel::validate(), NEIm2Col::validate(), and NEWeightsReshapeKernel::validate().
Referenced by NELocallyConnectedLayer::configure().
The documentation for this class was generated from the following files:
arm_compute/runtime/NEON/functions/NELocallyConnectedLayer.h
src/runtime/NEON/functions/NELocallyConnectedLayer.cpp