Compute Library: CLElementwiseSquaredDiff Class Reference
CLElementwiseSquaredDiff Class Reference
Basic function to run CLArithmeticOperationKernel for squared difference.
#include <CLElementwiseOperations.h>
Public Member Functions
CLElementwiseSquaredDiff ()
Default Constructor.
~CLElementwiseSquaredDiff ()
Default Destructor.
CLElementwiseSquaredDiff (const CLElementwiseSquaredDiff &)=delete
Prevent instances of this class from being copied (As this class contains pointers)
CLElementwiseSquaredDiff (CLElementwiseSquaredDiff &&)
Default move constructor.
CLElementwiseSquaredDiff & operator= (const CLElementwiseSquaredDiff &)=delete
Prevent instances of this class from being copied (As this class contains pointers)
CLElementwiseSquaredDiff & operator= (CLElementwiseSquaredDiff &&)
Default move assignment operator.
void configure (ICLTensor *input1, ICLTensor *input2, ICLTensor *output, const ActivationLayerInfo &act_info=ActivationLayerInfo())
Initialise the kernel's inputs, output and conversion policy.
void configure (const CLCompileContext &compile_context, ICLTensor *input1, ICLTensor *input2, ICLTensor *output, const ActivationLayerInfo &act_info=ActivationLayerInfo())
Initialise the kernel's inputs, output and conversion policy.
void run () override
Run the kernels contained in the function.
Public Member Functions inherited from IFunction
virtual ~IFunction ()=default
Destructor.
virtual void prepare ()
Prepare the function for executing.
Static Public Member Functions
static Status validate (const ITensorInfo *input1, const ITensorInfo *input2, const ITensorInfo *output, const ActivationLayerInfo &act_info=ActivationLayerInfo())
Static function to check if given info will lead to a valid configuration of CLArithmeticOperationKernel for squared difference.
Detailed Description
Basic function to run CLArithmeticOperationKernel for squared difference.
Note
The tensor data type for the inputs must be QASYMM8/U8/S16/QSYMM16/F16/F32.
The function performs a squared different operation between two tensors (i.e., out[i] = (in1[i] - in2[i])^2
Definition at line 750 of file CLElementwiseOperations.h.
Constructor & Destructor Documentation
CLElementwiseSquaredDiff() [1/3]
CLElementwiseSquaredDiff ()
Default Constructor.
Definition at line 421 of file CLElementwiseOperations.cpp.
     : _impl(support::cpp14::make_unique<Impl>())
 {
 }
~CLElementwiseSquaredDiff()
~CLElementwiseSquaredDiff () default
Default Destructor.
CLElementwiseSquaredDiff() [2/3]
CLElementwiseSquaredDiff (const CLElementwiseSquaredDiff &) delete
Prevent instances of this class from being copied (As this class contains pointers)
CLElementwiseSquaredDiff() [3/3]
CLElementwiseSquaredDiff (CLElementwiseSquaredDiff &&) default
Default move constructor.
Member Function Documentation
configure() [1/2]
void configure (ICLTensor * input1, ICLTensor * input2, ICLTensor * output, const ActivationLayerInfo & act_info = ActivationLayerInfo())
Initialise the kernel's inputs, output and conversion policy.
Parameters
[in,out] input1 First tensor input. Data types supported: U8/QASYMM8/QASYMM8_SIGNED/S16/QSYMM16/F16/F32. The input tensor is [in, out] because its TensorInfo might be modified inside the kernel in case of broadcasting of dimension 0.
[in,out] input2 Second tensor input. Data types supported: same as input1. The input tensor is [in, out] because its TensorInfo might be modified inside the kernel in case of broadcasting of dimension 0.
[out] output Output tensor. Data types supported: same as input1.
[in] act_info (Optional) Activation layer information in case of a fused activation.
Definition at line 429 of file CLElementwiseOperations.cpp.
 {
     configure(CLKernelLibrary::get().get_compile_context(), input1, input2, output, act_info);
 }
References CLKernelLibrary::get().
configure() [2/2]
void configure (const CLCompileContext & compile_context, ICLTensor * input1, ICLTensor * input2, ICLTensor * output, const ActivationLayerInfo & act_info = ActivationLayerInfo())
Initialise the kernel's inputs, output and conversion policy.
Parameters
[in] compile_context The compile context to be used.
[in,out] input1 First tensor input. Data types supported: U8/QASYMM8/QASYMM8_SIGNED/S16/QSYMM16/F16/F32. The input tensor is [in, out] because its TensorInfo might be modified inside the kernel in case of broadcasting of dimension 0.
[in,out] input2 Second tensor input. Data types supported: same as input1. The input tensor is [in, out] because its TensorInfo might be modified inside the kernel in case of broadcasting of dimension 0.
[out] output Output tensor. Data types supported: same as input1.
[in] act_info (Optional) Activation layer information in case of a fused activation.
Definition at line 434 of file CLElementwiseOperations.cpp.
 {
     _impl->src_0 = input1;
     _impl->src_1 = input2;
     _impl->dst   = output;
     _impl->op    = arm_compute::support::cpp14::make_unique<experimental::CLElementwiseSquaredDiff>();
     _impl->op->configure(compile_context, input1->info(), input2->info(), output->info(), act_info);
 }
References ITensor::info().
operator=() [1/2]
CLElementwiseSquaredDiff& operator= (const CLElementwiseSquaredDiff &) delete
Prevent instances of this class from being copied (As this class contains pointers)
operator=() [2/2]
CLElementwiseSquaredDiff & operator= (CLElementwiseSquaredDiff &&) default
Default move assignment operator.
run()
void run () override virtual
Run the kernels contained in the function.
For NEON kernels:
Multi-threading is used for the kernels which are parallelisable.
By default std::thread::hardware_concurrency() threads are used.
Note
CPPScheduler::set_num_threads() can be used to manually set the number of threads
For OpenCL kernels:
All the kernels are enqueued on the queue associated with CLScheduler.
The queue is then flushed.
Note
The function will not block until the kernels are executed. It is the user's responsibility to wait.
Will call prepare() on first run if hasn't been done
Implements IFunction.
Definition at line 448 of file CLElementwiseOperations.cpp.
 {
     ITensorPack pack;
     pack.add_tensor(TensorType::ACL_SRC_0, _impl->src_0);
     pack.add_tensor(TensorType::ACL_SRC_1, _impl->src_1);
     pack.add_tensor(TensorType::ACL_DST, _impl->dst);
     _impl->op->run(pack);
 }
References arm_compute::ACL_DST, arm_compute::ACL_SRC_0, arm_compute::ACL_SRC_1, and ITensorPack::add_tensor().
validate()
Status validate (const ITensorInfo * input1, const ITensorInfo * input2, const ITensorInfo * output, const ActivationLayerInfo & act_info = ActivationLayerInfo()) static
Static function to check if given info will lead to a valid configuration of CLArithmeticOperationKernel for squared difference.
Parameters
[in] input1 First tensor input info. Data types supported: U8/QASYMM8/QASYMM8_SIGNED/S16/QSYMM16/F16/F32.
[in] input2 Second tensor input info. Data types supported: same as input1.
[in] output Output tensor info. Data types supported: same as input1.
[in] act_info (Optional) Activation layer information in case of a fused activation.
Returns
a status
Definition at line 443 of file CLElementwiseOperations.cpp.
 {
     return experimental::CLElementwiseSquaredDiff::validate(input1, input2, output, act_info);
 }
References CLElementwiseSquaredDiff::validate().
The documentation for this class was generated from the following files:
arm_compute/runtime/CL/functions/CLElementwiseOperations.h
src/runtime/CL/functions/CLElementwiseOperations.cpp