Compute Library: NEHistogram Class Reference
NEHistogram Class Reference
Basic function to run NEHistogramKernel.
#include <NEHistogram.h>
Public Member Functions
NEHistogram ()
Default Constructor.
NEHistogram (const NEHistogram &)=delete
Prevent instances of this class from being copied (As this class contains pointers)
NEHistogram & operator= (const NEHistogram &)=delete
Prevent instances of this class from being copied (As this class contains pointers)
NEHistogram (NEHistogram &&)=delete
Prevent instances of this class from being moved (As this class contains non movable objects)
NEHistogram & operator= (NEHistogram &&)=delete
Prevent instances of this class from being moved (As this class contains non movable objects)
~NEHistogram ()
Default destructor.
void configure (const IImage *input, IDistribution1D *output)
Initialise the kernel's inputs.
void run () override
Run the kernels contained in the function.
Public Member Functions inherited from IFunction
virtual ~IFunction ()=default
Destructor.
virtual void prepare ()
Prepare the function for executing.
Detailed Description
Basic function to run NEHistogramKernel.
Deprecated:
This function is deprecated and is intended to be removed in 21.05 release
Definition at line 46 of file NEHistogram.h.
Constructor & Destructor Documentation
NEHistogram() [1/3]
NEHistogram ()
Default Constructor.
Definition at line 39 of file NEHistogram.cpp.
     : _histogram_kernel(), _local_hist(), _window_lut(window_lut_default_size), _local_hist_size(0)
 {
 }
NEHistogram() [2/3]
NEHistogram (const NEHistogram &) delete
Prevent instances of this class from being copied (As this class contains pointers)
NEHistogram() [3/3]
NEHistogram (NEHistogram &&) delete
Prevent instances of this class from being moved (As this class contains non movable objects)
~NEHistogram()
~NEHistogram () default
Default destructor.
Member Function Documentation
configure()
void configure (const IImage * input, IDistribution1D * output)
Initialise the kernel's inputs.
Parameters
[in] input Input image. Data type supported: U8.
[out] output Output distribution.
Definition at line 44 of file NEHistogram.cpp.
 {
     ARM_COMPUTE_ERROR_ON_TENSOR_NOT_2D(input);
     ARM_COMPUTE_ERROR_ON(nullptr == output);
     // Allocate space for threads local histograms
     _local_hist_size = output->num_bins() * NEScheduler::get().num_threads();
     _local_hist.resize(_local_hist_size);
     // Configure kernel
     _histogram_kernel = arm_compute::support::cpp14::make_unique<NEHistogramKernel>();
     _histogram_kernel->configure(input, output, _local_hist.data(), _window_lut.data());
 }
References ARM_COMPUTE_ERROR_ON, ARM_COMPUTE_ERROR_ON_TENSOR_NOT_2D, Scheduler::get(), arm_compute::test::validation::input, IDistribution1D::num_bins(), and IScheduler::num_threads().
operator=() [1/2]
NEHistogram& operator= (const NEHistogram &) delete
Prevent instances of this class from being copied (As this class contains pointers)
operator=() [2/2]
NEHistogram& operator= (NEHistogram &&) delete
Prevent instances of this class from being moved (As this class contains non movable objects)
run()
void run () override virtual
Run the kernels contained in the function.
For NEON kernels:
Multi-threading is used for the kernels which are parallelisable.
By default std::thread::hardware_concurrency() threads are used.
Note
CPPScheduler::set_num_threads() can be used to manually set the number of threads
For OpenCL kernels:
All the kernels are enqueued on the queue associated with CLScheduler.
The queue is then flushed.
Note
The function will not block until the kernels are executed. It is the user's responsibility to wait.
Will call prepare() on first run if hasn't been done
Implements IFunction.
Definition at line 58 of file NEHistogram.cpp.
 {
     // Calculate histogram of input.
     NEScheduler::get().schedule(_histogram_kernel.get(), Window::DimY);
 }
References Window::DimY, Scheduler::get(), and IScheduler::schedule().
The documentation for this class was generated from the following files:
arm_compute/runtime/NEON/functions/NEHistogram.h
src/runtime/NEON/functions/NEHistogram.cpp