Compute Library: NEFullyConnectedLayerReshapeWeights Class Reference
NEFullyConnectedLayerReshapeWeights Class Reference
Basic function to reshape the weights of Fully Connected layer with NEON.
#include <NEFullyConnectedLayer.h>
Public Member Functions
NEFullyConnectedLayerReshapeWeights ()=default
Constructor.
NEFullyConnectedLayerReshapeWeights (const NEFullyConnectedLayerReshapeWeights &)=delete
Prevent instances of this class from being copied (As this class contains pointers)
NEFullyConnectedLayerReshapeWeights & operator= (const NEFullyConnectedLayerReshapeWeights &)=delete
Prevent instances of this class from being copied (As this class contains pointers)
NEFullyConnectedLayerReshapeWeights (NEFullyConnectedLayerReshapeWeights &&)=delete
Prevent instances of this class from being moved (As this class contains non movable objects)
NEFullyConnectedLayerReshapeWeights & operator= (NEFullyConnectedLayerReshapeWeights &&)=delete
Prevent instances of this class from being moved (As this class contains non movable objects)
~NEFullyConnectedLayerReshapeWeights ()=default
Default destructor.
void configure (const ITensor *input, ITensor *output)
Set the input and output tensors.
Public Member Functions inherited from INESimpleFunctionNoBorder
INESimpleFunctionNoBorder (IRuntimeContext *ctx=nullptr)
Constructor.
INESimpleFunctionNoBorder (const INESimpleFunctionNoBorder &)=delete
Prevent instances of this class from being copied (As this class contains pointers)
INESimpleFunctionNoBorder (INESimpleFunctionNoBorder &&)=default
Default move constructor.
INESimpleFunctionNoBorder & operator= (const INESimpleFunctionNoBorder &)=delete
Prevent instances of this class from being copied (As this class contains pointers)
INESimpleFunctionNoBorder & operator= (INESimpleFunctionNoBorder &&)=default
Default move assignment operator.
~INESimpleFunctionNoBorder ()
Default destructor.
void run () override final
Run the kernels contained in the function.
Public Member Functions inherited from IFunction
virtual ~IFunction ()=default
Destructor.
virtual void prepare ()
Prepare the function for executing.
Static Public Member Functions
static Status validate (const ITensorInfo *input, const ITensorInfo *output)
Static function to check if given info will lead to a valid configuration of NEFullyConnectedLayerReshapeWeights.
Detailed Description
Basic function to reshape the weights of Fully Connected layer with NEON.
This function calls the following kernels:
Note
The fully connected layer accepts "weights" tensors only with 2 dimensions.
Definition at line 44 of file NEFullyConnectedLayer.h.
Constructor & Destructor Documentation
NEFullyConnectedLayerReshapeWeights() [1/3]
NEFullyConnectedLayerReshapeWeights () default
Constructor.
NEFullyConnectedLayerReshapeWeights() [2/3]
NEFullyConnectedLayerReshapeWeights (const NEFullyConnectedLayerReshapeWeights &) delete
Prevent instances of this class from being copied (As this class contains pointers)
NEFullyConnectedLayerReshapeWeights() [3/3]
NEFullyConnectedLayerReshapeWeights (NEFullyConnectedLayerReshapeWeights &&) delete
Prevent instances of this class from being moved (As this class contains non movable objects)
~NEFullyConnectedLayerReshapeWeights()
~NEFullyConnectedLayerReshapeWeights () default
Default destructor.
Member Function Documentation
configure()
void configure (const ITensor * input, ITensor * output)
Set the input and output tensors.
Parameters
[in] input Weights tensor. The weights must be 2 dimensional. Data types supported: QASYMM8/QASYMM8_SIGNED/F16/F32.
[out] output Destination tensor. Data type supported: Same as input.
Definition at line 149 of file NEFullyConnectedLayer.cpp.
 {
     auto k = arm_compute::support::cpp14::make_unique<NETransposeKernel>();
     k->configure(input, output);
     _kernel = std::move(k);
 }
References arm_compute::test::validation::input.
Referenced by NEFullyConnectedLayerReshapeWeightsManaged::configure(), and NEFullyConnectedLayer::configure().
operator=() [1/2]
NEFullyConnectedLayerReshapeWeights& operator= (const NEFullyConnectedLayerReshapeWeights &) delete
Prevent instances of this class from being copied (As this class contains pointers)
operator=() [2/2]
NEFullyConnectedLayerReshapeWeights& operator= (NEFullyConnectedLayerReshapeWeights &&) delete
Prevent instances of this class from being moved (As this class contains non movable objects)
validate()
Status validate (const ITensorInfo * input, const ITensorInfo * output) static
Static function to check if given info will lead to a valid configuration of NEFullyConnectedLayerReshapeWeights.
Parameters
[in] input Weights tensor info. The weights must be 2 dimensional. Data types supported: QASYMM8/QASYMM8_SIGNED/F16/F32.
[in] output Destination tensor info. Data type supported: Same as input.
Returns
a status
Definition at line 156 of file NEFullyConnectedLayer.cpp.
 {
     return NETransposeKernel::validate(input, output);
 }
References arm_compute::test::validation::input, and NETransposeKernel::validate().
Referenced by NEFullyConnectedLayer::validate().
The documentation for this class was generated from the following files:
arm_compute/runtime/NEON/functions/NEFullyConnectedLayer.h
src/runtime/NEON/functions/NEFullyConnectedLayer.cpp