Compute Library: NEConcatenation Class Reference
NEConcatenation Class Reference
Basic function to execute concatenate tensors along a given axis.
#include <NEConcatenateLayer.h>
Public Member Functions
NEConcatenation ()
Constructor.
NEConcatenation (const NEConcatenation &)=delete
Prevent instances of this class from being copied (As this class contains pointers)
NEConcatenation & operator= (const NEConcatenation &)=delete
Prevent instances of this class from being copied (As this class contains pointers)
NEConcatenation (NEConcatenation &&)=delete
Prevent instances of this class from being moved (As this class contains non movable objects)
NEConcatenation & operator= (NEConcatenation &&)=delete
Prevent instances of this class from being moved (As this class contains non movable objects)
~NEConcatenation ()=default
Default destructor.
void configure (const std::vector< const ITensorInfo * > &inputs_vector, ITensorInfo *output, size_t axis)
Initialise the kernel's inputs vector and output.
void run (ITensorPack &tensors) override
Run the kernels contained in the function.
Public Member Functions inherited from INEOperator
INEOperator (IRuntimeContext *ctx=nullptr)
Constructor.
INEOperator (const INEOperator &)=delete
Prevent instances of this class from being copied (As this class contains pointers)
INEOperator (INEOperator &&)=default
Default move constructor.
INEOperator & operator= (const INEOperator &)=delete
Prevent instances of this class from being copied (As this class contains pointers)
INEOperator & operator= (INEOperator &&)=default
Default move assignment operator.
~INEOperator ()
Default destructor.
void run (ITensorPack &tensors) override
Run the kernels contained in the function.
void prepare (ITensorPack &constants) override
Prepare the function for executing.
MemoryRequirements workspace () const override
Return the memory requirements required by the workspace.
Public Member Functions inherited from IOperator
virtual ~IOperator ()=default
Destructor.
Static Public Member Functions
static Status validate (const std::vector< const ITensorInfo * > &inputs_vector, const ITensorInfo *output, size_t axis)
Static function to check if given info will lead to a valid configuration of NEConcatenateLayer.
Detailed Description
Basic function to execute concatenate tensors along a given axis.
This function calls the following kernels:
NEWidthConcatenateLayerKernel (if underlying concatenation axis is 0).
NEHeightConcatenateLayerKernel (if underlying concatenation axis is 1).
NEDepthConcatenateLayerKernel (if underlying concatenation axis is 2).
NEBatchConcatenateLayerKernel (if underlying concatenation axis is 3).
Definition at line 105 of file NEConcatenateLayer.h.
Constructor & Destructor Documentation
NEConcatenation() [1/3]
NEConcatenation ()
Constructor.
Definition at line 45 of file NEConcatenateLayer.cpp.
     : _concat_kernels(), _num_inputs(0), _axis(0)
 {
 }
NEConcatenation() [2/3]
NEConcatenation (const NEConcatenation &) delete
Prevent instances of this class from being copied (As this class contains pointers)
NEConcatenation() [3/3]
NEConcatenation (NEConcatenation &&) delete
Prevent instances of this class from being moved (As this class contains non movable objects)
~NEConcatenation()
~NEConcatenation () default
Default destructor.
Member Function Documentation
configure()
void configure (const std::vector< const ITensorInfo * > & inputs_vector, ITensorInfo * output, size_t axis)
Initialise the kernel's inputs vector and output.
Note
Input and output tensor dimensions preconditions defer depending on the concatenation axis.
Preconditions can be found respectively at NEWidthConcatenateLayerKernel, NEHeightConcatenateLayerKernel and NEDepthConcatenateLayerKernel.
Parameters
[in,out] inputs_vector The vectors containing all the tensors to concatenate. Data types supported: QASYMM8/QASYMM8_SIGNED/F16/F32.
[out] output Output tensor. Data types supported: Same as input.
[in] axis Concatenation axis. Supported underlying concatenation axis are 0, 1, 2 and 3.
Definition at line 50 of file NEConcatenateLayer.cpp.
 {
     ARM_COMPUTE_ERROR_ON(output == nullptr);
     _axis       = axis;
     _num_inputs = inputs_vector.size();
     TensorShape output_shape = arm_compute::misc::shape_calculator::calculate_concatenate_shape(inputs_vector, axis);
     // Output auto inizialitation if not yet initialized
     auto_init_if_empty(*output, output_shape, 1, inputs_vector[0]->data_type());
     ARM_COMPUTE_ERROR_THROW_ON(NEConcatenateLayer::validate(inputs_vector, output, axis));
     unsigned int offset = 0;
     for(unsigned int i = 0; i < _num_inputs; ++i)
     {
         switch(axis)
         {
             case Window::DimX:
             {
                 auto kernel = support::cpp14::make_unique<NEWidthConcatenateLayerKernel>();
                 kernel->configure(inputs_vector.at(i), offset, output);
                 _concat_kernels.emplace_back(std::move(kernel));
                 break;
             }
             case Window::DimY:
             {
                 auto kernel = support::cpp14::make_unique<NEHeightConcatenateLayerKernel>();
                 kernel->configure(inputs_vector.at(i), offset, output);
                 _concat_kernels.emplace_back(std::move(kernel));
                 break;
             }
             case Window::DimZ:
             {
                 auto kernel = support::cpp14::make_unique<NEDepthConcatenateLayerKernel>();
                 kernel->configure(inputs_vector.at(i), offset, output);
                 _concat_kernels.emplace_back(std::move(kernel));
                 break;
             }
             case 3:
             {
                 auto kernel = support::cpp14::make_unique<NEBatchConcatenateLayerKernel>();
                 kernel->configure(inputs_vector.at(i), offset, output);
                 _concat_kernels.emplace_back(std::move(kernel));
                 break;
             }
             default:
                 ARM_COMPUTE_ERROR("Axis not supported");
         }
         offset += inputs_vector.at(i)->dimension(axis);
     }
 }
References ARM_COMPUTE_ERROR, ARM_COMPUTE_ERROR_ON, ARM_COMPUTE_ERROR_THROW_ON, arm_compute::auto_init_if_empty(), arm_compute::misc::shape_calculator::calculate_concatenate_shape(), arm_compute::test::validation::data_type, Window::DimX, Window::DimY, Window::DimZ, offset(), arm_compute::test::validation::output_shape, and NEConcatenateLayer::validate().
operator=() [1/2]
NEConcatenation& operator= (const NEConcatenation &) delete
Prevent instances of this class from being copied (As this class contains pointers)
operator=() [2/2]
NEConcatenation& operator= (NEConcatenation &&) delete
Prevent instances of this class from being moved (As this class contains non movable objects)
run()
void run (ITensorPack & tensors) override virtual
Run the kernels contained in the function.
Parameters
[in] tensors Vector that contains the tensors to operate on.
Implements IOperator.
Definition at line 150 of file NEConcatenateLayer.cpp.
 {
     if(tensors.empty())
     {
         ARM_COMPUTE_ERROR("No inputs provided");
     }
     if(static_cast<int>(tensors.size() - 1) != static_cast<int>(_num_inputs))
     {
         ARM_COMPUTE_ERROR("Configured with different number of inputs");
     }
     int i = 0;
     for(auto &k : _concat_kernels)
     {
         ITensorPack pack;
         pack.add_tensor(TensorType::ACL_SRC, tensors.get_const_tensor(ACL_SRC_VEC + i));
         pack.add_tensor(TensorType::ACL_DST, tensors.get_tensor(ACL_DST));
         NEScheduler::get().schedule_op(k.get(), Window::DimY, pack);
         ++i;
     }
 }
References arm_compute::ACL_DST, arm_compute::ACL_SRC, arm_compute::ACL_SRC_VEC, ITensorPack::add_tensor(), ARM_COMPUTE_ERROR, Window::DimY, ITensorPack::empty(), Scheduler::get(), ITensorPack::get_const_tensor(), ITensorPack::get_tensor(), IScheduler::schedule_op(), and ITensorPack::size().
validate()
Status validate (const std::vector< const ITensorInfo * > & inputs_vector, const ITensorInfo * output, size_t axis) static
Static function to check if given info will lead to a valid configuration of NEConcatenateLayer.
Note
Input and output tensor dimensions preconditions defer depending on the concatenation axis.
Preconditions can be found respectively at NEWidthConcatenateLayerKernel, NEHeightConcatenateLayerKernel and NEDepthConcatenateLayerKernel.
Parameters
[in] inputs_vector The vectors containing all the tensors info to concatenate. Data types supported: QASYMM8/QASYMM8_SIGNED/F16/F32.
[in] output Output tensor info. Data types supported: Same as input.
[in] axis Concatenation axis. Supported underlying concatenation axis are 0, 1, 2 and 3.
Returns
a status
Definition at line 104 of file NEConcatenateLayer.cpp.
 {
     ARM_COMPUTE_RETURN_ERROR_ON_NULLPTR(output);
     ARM_COMPUTE_RETURN_ERROR_ON(inputs_vector.size() < 2);
     unsigned int offset = 0;
     for(const auto &input : inputs_vector)
     {
         ARM_COMPUTE_RETURN_ERROR_ON_NULLPTR(input);
         switch(axis)
         {
             case Window::DimX:
             {
                 ARM_COMPUTE_RETURN_ON_ERROR(NEWidthConcatenateLayerKernel::validate(input, offset, output));
                 break;
             }
             case Window::DimY:
             {
                 ARM_COMPUTE_RETURN_ON_ERROR(NEHeightConcatenateLayerKernel::validate(input, offset, output));
                 break;
             }
             case Window::DimZ:
             {
                 ARM_COMPUTE_RETURN_ON_ERROR(NEDepthConcatenateLayerKernel::validate(input, offset, output));
                 break;
             }
             case 3:
             {
                 ARM_COMPUTE_RETURN_ON_ERROR(NEBatchConcatenateLayerKernel::validate(input, offset, output));
                 break;
             }
             default:
                 ARM_COMPUTE_ERROR("Axis not supported");
         }
         offset += input->dimension(axis);
     }
     if(output->total_size() != 0)
     {
         TensorShape output_shape = arm_compute::misc::shape_calculator::calculate_concatenate_shape(inputs_vector, axis);
         ARM_COMPUTE_RETURN_ERROR_ON(output_shape.total_size() != output->tensor_shape().total_size());
     }
     return Status{};
 }
References ARM_COMPUTE_ERROR, ARM_COMPUTE_RETURN_ERROR_ON, ARM_COMPUTE_RETURN_ERROR_ON_NULLPTR, ARM_COMPUTE_RETURN_ON_ERROR, arm_compute::misc::shape_calculator::calculate_concatenate_shape(), Window::DimX, Window::DimY, Window::DimZ, arm_compute::test::validation::input, offset(), arm_compute::test::validation::output_shape, ITensorInfo::tensor_shape(), TensorShape::total_size(), ITensorInfo::total_size(), NEWidthConcatenateLayerKernel::validate(), NEHeightConcatenateLayerKernel::validate(), NEBatchConcatenateLayerKernel::validate(), and NEDepthConcatenateLayerKernel::validate().
Referenced by NEConcatenateLayer::validate().
The documentation for this class was generated from the following files:
arm_compute/runtime/NEON/functions/NEConcatenateLayer.h
src/runtime/NEON/functions/NEConcatenateLayer.cpp