Compute Library: CLGEMMLowpOutputStage Class Reference
CLGEMMLowpOutputStage Class Reference
Basic function to execute GEMMLowpQuantizeDown kernels on CL.
#include <CLGEMMLowpOutputStage.h>
Public Member Functions
void configure (const ICLTensor *input, const ICLTensor *bias, ICLTensor *output, const GEMMLowpOutputStageInfo &info)
Initialise the kernel's inputs, output.
void configure (const CLCompileContext &compile_context, const ICLTensor *input, const ICLTensor *bias, ICLTensor *output, const GEMMLowpOutputStageInfo &info)
Initialise the kernel's inputs, output.
Public Member Functions inherited from ICLSimpleFunction
ICLSimpleFunction (CLRuntimeContext *ctx=nullptr)
Constructor.
ICLSimpleFunction (const ICLSimpleFunction &)=delete
Prevent instances of this class from being copied (As this class contains pointers)
ICLSimpleFunction (ICLSimpleFunction &&)=default
Default move constructor.
ICLSimpleFunction & operator= (const ICLSimpleFunction &)=delete
Prevent instances of this class from being copied (As this class contains pointers)
ICLSimpleFunction & operator= (ICLSimpleFunction &&)=default
Default move assignment operator.
~ICLSimpleFunction ()
Default destructor.
void run () override final
Run the kernels contained in the function.
Public Member Functions inherited from IFunction
virtual ~IFunction ()=default
Destructor.
virtual void prepare ()
Prepare the function for executing.
Static Public Member Functions
static Status validate (const ITensorInfo *input, const ITensorInfo *bias, const ITensorInfo *output, const GEMMLowpOutputStageInfo &info)
Static function to check if given info will lead to a valid configuration of CLGEMMLowpQuantizeDownInt32ScaleByFixedPointKernel.
Detailed Description
Basic function to execute GEMMLowpQuantizeDown kernels on CL.
This function calls the following CL kernels:
CLGEMMLowpQuantizeDownInt32ScaleKernel
CLGEMMLowpQuantizeDownInt32ScaleByFloatKernel
CLGEMMLowpQuantizeDownInt32ScaleByFixedPointKernel
Definition at line 286 of file CLGEMMLowpOutputStage.h.
Member Function Documentation
configure() [1/2]
void configure (const ICLTensor * input, const ICLTensor * bias, ICLTensor * output, const GEMMLowpOutputStageInfo & info)
Initialise the kernel's inputs, output.
Parameters
[in] input Input tensor. Data type supported: S32
[in] bias Biases tensor. Only shared biases supported and it can be a nullptr if the biases addition is not required. Biases are 1D tensor with dimensions [OFM]. Data type supported: Same as input.
[out] output Output tensor. Data type supported: QASYMM8/QASYMM8_SIGNED
[in] info GEMMLowp output stage metadata.
Definition at line 135 of file CLGEMMLowpOutputStage.cpp.
 {
     configure(CLKernelLibrary::get().get_compile_context(), input, bias, output, info);
 }
References CLKernelLibrary::get(), arm_compute::test::validation::info, and arm_compute::test::validation::input.
Referenced by CLGEMMDeconvolutionLayer::configure(), and CLQLSTMLayer::configure().
configure() [2/2]
void configure (const CLCompileContext & compile_context, const ICLTensor * input, const ICLTensor * bias, ICLTensor * output, const GEMMLowpOutputStageInfo & info)
Initialise the kernel's inputs, output.
Parameters
[in] compile_context The compile context to be used.
[in] input Input tensor. Data type supported: S32
[in] bias Biases tensor. Only shared biases supported and it can be a nullptr if the biases addition is not required. Biases are 1D tensor with dimensions [OFM]. Data type supported: Same as input.
[out] output Output tensor. Data type supported: QASYMM8/QASYMM8_SIGNED
[in] info GEMMLowp output stage metadata.
Definition at line 140 of file CLGEMMLowpOutputStage.cpp.
 {
     ARM_COMPUTE_ERROR_ON_NULLPTR(input, output);
     switch(info.type)
     {
         case GEMMLowpOutputStageType::QUANTIZE_DOWN_FIXEDPOINT:
         {
             auto k = arm_compute::support::cpp14::make_unique<CLGEMMLowpQuantizeDownInt32ScaleByFixedPointKernel>();
             k->configure(compile_context, input, bias, output, &info);
             _kernel = std::move(k);
             break;
         }
         case GEMMLowpOutputStageType::QUANTIZE_DOWN:
         {
             auto k = arm_compute::support::cpp14::make_unique<CLGEMMLowpQuantizeDownInt32ScaleKernel>();
             k->configure(compile_context, input, bias, output, &info);
             _kernel = std::move(k);
             break;
         }
         case GEMMLowpOutputStageType::QUANTIZE_DOWN_FLOAT:
         {
             auto k = arm_compute::support::cpp14::make_unique<CLGEMMLowpQuantizeDownInt32ScaleByFloatKernel>();
             k->configure(compile_context, input, bias, output, &info);
             _kernel = std::move(k);
             break;
         }
         default:
             ARM_COMPUTE_ERROR("Unsupported GEMMLowpOutputStage type.");
     }
 }
References ARM_COMPUTE_ERROR, ARM_COMPUTE_ERROR_ON_NULLPTR, arm_compute::test::validation::info, arm_compute::test::validation::input, arm_compute::QUANTIZE_DOWN, arm_compute::QUANTIZE_DOWN_FIXEDPOINT, and arm_compute::QUANTIZE_DOWN_FLOAT.
validate()
Status validate (const ITensorInfo * input, const ITensorInfo * bias, const ITensorInfo * output, const GEMMLowpOutputStageInfo & info) static
Static function to check if given info will lead to a valid configuration of CLGEMMLowpQuantizeDownInt32ScaleByFixedPointKernel.
Parameters
[in] input Input tensor. It is the output of CLGEMMLowpMatrixMultiplyCore function. Data type supported: S32
[in] bias Biases tensor. Only shared biases supported and it can be a nullptr if the addition of biases is not required. Biases are 1D tensor with dimensions [OFM]. Data type supported: Same as input.
[in] output Output tensor. Data type supported: QASYMM8/QASYMM8_SIGNED
[in] info GEMMLowp output stage metadata.
Returns
a status
Definition at line 172 of file CLGEMMLowpOutputStage.cpp.
 {
     ARM_COMPUTE_RETURN_ERROR_ON_NULLPTR(output);
     ARM_COMPUTE_RETURN_ERROR_ON_DATA_TYPE_CHANNEL_NOT_IN(output, 1, DataType::QASYMM8, DataType::QASYMM8_SIGNED, DataType::QSYMM16);
     switch(info.type)
     {
         case GEMMLowpOutputStageType::QUANTIZE_DOWN_FIXEDPOINT:
             return CLGEMMLowpQuantizeDownInt32ScaleByFixedPointKernel::validate(input, bias, output, &info);
         case GEMMLowpOutputStageType::QUANTIZE_DOWN:
             return CLGEMMLowpQuantizeDownInt32ScaleKernel::validate(input, bias, output, &info);
         case GEMMLowpOutputStageType::QUANTIZE_DOWN_FLOAT:
             return CLGEMMLowpQuantizeDownInt32ScaleByFloatKernel::validate(input, bias, output, &info);
         default:
             return ARM_COMPUTE_CREATE_ERROR(ErrorCode::RUNTIME_ERROR, "Unsupported GEMMLowpOutputStage type.");
     }
 }
References ARM_COMPUTE_CREATE_ERROR, ARM_COMPUTE_RETURN_ERROR_ON_DATA_TYPE_CHANNEL_NOT_IN, ARM_COMPUTE_RETURN_ERROR_ON_NULLPTR, arm_compute::test::validation::info, arm_compute::test::validation::input, arm_compute::QASYMM8, arm_compute::QASYMM8_SIGNED, arm_compute::QSYMM16, arm_compute::QUANTIZE_DOWN, arm_compute::QUANTIZE_DOWN_FIXEDPOINT, arm_compute::QUANTIZE_DOWN_FLOAT, arm_compute::RUNTIME_ERROR, CLGEMMLowpQuantizeDownInt32ScaleByFixedPointKernel::validate(), CLGEMMLowpQuantizeDownInt32ScaleKernel::validate(), and CLGEMMLowpQuantizeDownInt32ScaleByFloatKernel::validate().
Referenced by CLGEMMDeconvolutionLayer::validate(), and CLQLSTMLayer::validate().
The documentation for this class was generated from the following files:
arm_compute/runtime/CL/functions/CLGEMMLowpOutputStage.h
src/runtime/CL/functions/CLGEMMLowpOutputStage.cpp