Compute Library: CLPixelWiseMultiplication Class Reference
CLPixelWiseMultiplication Class Reference
Basic function to run CLPixelWiseMultiplicationKernel.
#include <CLPixelWiseMultiplication.h>
Public Member Functions
CLPixelWiseMultiplication ()
Default Constructor.
~CLPixelWiseMultiplication ()
Default Destructor.
CLPixelWiseMultiplication (const CLPixelWiseMultiplication &)=delete
Prevent instances of this class from being copied (As this class contains pointers)
CLPixelWiseMultiplication (CLPixelWiseMultiplication &&)
Default move constructor.
CLPixelWiseMultiplication & operator= (const CLPixelWiseMultiplication &)=delete
Prevent instances of this class from being copied (As this class contains pointers)
CLPixelWiseMultiplication & operator= (CLPixelWiseMultiplication &&)
Default move assignment operator.
void configure (ICLTensor *input1, ICLTensor *input2, ICLTensor *output, float scale, ConvertPolicy overflow_policy, RoundingPolicy rounding_policy, const ActivationLayerInfo &act_info=ActivationLayerInfo())
Initialise the kernel's inputs, output and convertion policy.
void configure (const CLCompileContext &compile_context, ICLTensor *input1, ICLTensor *input2, ICLTensor *output, float scale, ConvertPolicy overflow_policy, RoundingPolicy rounding_policy, const ActivationLayerInfo &act_info=ActivationLayerInfo())
Initialise the kernel's inputs, output and convertion policy.
void run () override
Run the kernels contained in the function.
Public Member Functions inherited from IFunction
virtual ~IFunction ()=default
Destructor.
virtual void prepare ()
Prepare the function for executing.
Static Public Member Functions
static Status validate (const ITensorInfo *input1, const ITensorInfo *input2, const ITensorInfo *output, float scale, ConvertPolicy overflow_policy, RoundingPolicy rounding_policy, const ActivationLayerInfo &act_info=ActivationLayerInfo())
Static function to check if given info will lead to a valid configuration of CLPixelWiseMultiplication.
Detailed Description
Basic function to run CLPixelWiseMultiplicationKernel.
Definition at line 149 of file CLPixelWiseMultiplication.h.
Constructor & Destructor Documentation
CLPixelWiseMultiplication() [1/3]
CLPixelWiseMultiplication ()
Default Constructor.
Definition at line 137 of file CLPixelWiseMultiplication.cpp.
     : _impl(support::cpp14::make_unique<Impl>())
 {
 }
~CLPixelWiseMultiplication()
~CLPixelWiseMultiplication () default
Default Destructor.
CLPixelWiseMultiplication() [2/3]
CLPixelWiseMultiplication (const CLPixelWiseMultiplication &) delete
Prevent instances of this class from being copied (As this class contains pointers)
CLPixelWiseMultiplication() [3/3]
CLPixelWiseMultiplication (CLPixelWiseMultiplication &&) default
Default move constructor.
Member Function Documentation
configure() [1/2]
void configure (ICLTensor * input1, ICLTensor * input2, ICLTensor * output, float scale, ConvertPolicy overflow_policy, RoundingPolicy rounding_policy, const ActivationLayerInfo & act_info = ActivationLayerInfo())
Initialise the kernel's inputs, output and convertion policy.
Valid configurations (Input1,Input2) -> Output :
(U8,U8) -> U8
(U8,U8) -> S16
(U8,S16) -> S16
(S16,U8) -> S16
(S16,S16) -> S16
(F16,F16) -> F16
(F32,F32) -> F32
(QASYMM8,QASYMM8) -> QASYMM8
(QASYMM8_SIGNED,QASYMM8_SIGNED) -> QASYMM8_SIGNED
(QSYMM16,QSYMM16) -> QSYMM16
(QSYMM16,QSYMM16) -> S32
Parameters
[in,out] input1 An input tensor. Data types supported: U8/QASYMM8/QASYMM8_SIGNED/S16/QSYMM16/F16/F32. The input tensor is [in, out] because its TensorInfo might be modified inside the kernel in case of broadcasting of dimension 0.
[in,out] input2 An input tensor. Data types supported: U8/QASYMM8/QASYMM8_SIGNED/S16/QSYMM16/F16/F32. The input tensor is [in, out] because its TensorInfo might be modified inside the kernel in case of broadcasting of dimension 0.
[out] output The output tensor. Data types supported: U8/QASYMM8/QASYMM8_SIGNED/S16/QSYMM16/F16/F32.
[in] scale Scale to apply after multiplication. Scale must be positive and its value must be either 1/255 or 1/2^n where n is between 0 and 15.
[in] overflow_policy Overflow policy. Supported overflow policies: Wrap, Saturate
[in] rounding_policy Rounding policy. Supported rounding modes: to zero, to nearest even.
[in] act_info (Optional) Activation layer information in case of a fused activation.
Definition at line 145 of file CLPixelWiseMultiplication.cpp.
 {
     configure(CLKernelLibrary::get().get_compile_context(), input1, input2, output, scale, overflow_policy, rounding_policy, act_info);
 }
References CLKernelLibrary::get(), and arm_compute::test::validation::scale.
Referenced by CLLSTMLayerQuantized::configure(), CLLSTMLayer::configure(), and CLQLSTMLayer::configure().
configure() [2/2]
void configure (const CLCompileContext & compile_context, ICLTensor * input1, ICLTensor * input2, ICLTensor * output, float scale, ConvertPolicy overflow_policy, RoundingPolicy rounding_policy, const ActivationLayerInfo & act_info = ActivationLayerInfo())
Initialise the kernel's inputs, output and convertion policy.
Valid configurations (Input1,Input2) -> Output :
(U8,U8) -> U8
(U8,U8) -> S16
(U8,S16) -> S16
(S16,U8) -> S16
(S16,S16) -> S16
(F16,F16) -> F16
(F32,F32) -> F32
(QASYMM8,QASYMM8) -> QASYMM8
(QASYMM8_SIGNED,QASYMM8_SIGNED) -> QASYMM8_SIGNED
(QSYMM16,QSYMM16) -> QSYMM16
(QSYMM16,QSYMM16) -> S32
Parameters
[in] compile_context The compile context to be used.
[in,out] input1 An input tensor. Data types supported: U8/QASYMM8/QASYMM8_SIGNED/S16/QSYMM16/F16/F32. The input tensor is [in, out] because its TensorInfo might be modified inside the kernel in case of broadcasting of dimension 0.
[in,out] input2 An input tensor. Data types supported: U8/QASYMM8/QASYMM8_SIGNED/S16/QSYMM16/F16/F32. The input tensor is [in, out] because its TensorInfo might be modified inside the kernel in case of broadcasting of dimension 0.
[out] output The output tensor. Data types supported: U8/QASYMM8/QASYMM8_SIGNED/S16/QSYMM16/F16/F32.
[in] scale Scale to apply after multiplication. Scale must be positive and its value must be either 1/255 or 1/2^n where n is between 0 and 15.
[in] overflow_policy Overflow policy. Supported overflow policies: Wrap, Saturate
[in] rounding_policy Rounding policy. Supported rounding modes: to zero, to nearest even.
[in] act_info (Optional) Activation layer information in case of a fused activation.
Definition at line 151 of file CLPixelWiseMultiplication.cpp.
 {
     _impl->src_0 = input1;
     _impl->src_1 = input2;
     _impl->dst   = output;
     _impl->op    = arm_compute::support::cpp14::make_unique<experimental::CLPixelWiseMultiplication>();
     _impl->op->configure(compile_context, input1->info(), input2->info(), output->info(), scale, overflow_policy, rounding_policy, act_info);
 }
References ITensor::info(), and arm_compute::test::validation::scale.
operator=() [1/2]
CLPixelWiseMultiplication& operator= (const CLPixelWiseMultiplication &) delete
Prevent instances of this class from being copied (As this class contains pointers)
operator=() [2/2]
CLPixelWiseMultiplication & operator= (CLPixelWiseMultiplication &&) default
Default move assignment operator.
run()
void run () override virtual
Run the kernels contained in the function.
For NEON kernels:
Multi-threading is used for the kernels which are parallelisable.
By default std::thread::hardware_concurrency() threads are used.
Note
CPPScheduler::set_num_threads() can be used to manually set the number of threads
For OpenCL kernels:
All the kernels are enqueued on the queue associated with CLScheduler.
The queue is then flushed.
Note
The function will not block until the kernels are executed. It is the user's responsibility to wait.
Will call prepare() on first run if hasn't been done
Implements IFunction.
Definition at line 167 of file CLPixelWiseMultiplication.cpp.
 {
     ITensorPack pack;
     pack.add_tensor(TensorType::ACL_SRC_0, _impl->src_0);
     pack.add_tensor(TensorType::ACL_SRC_1, _impl->src_1);
     pack.add_tensor(TensorType::ACL_DST, _impl->dst);
     _impl->op->run(pack);
 }
References arm_compute::ACL_DST, arm_compute::ACL_SRC_0, arm_compute::ACL_SRC_1, and ITensorPack::add_tensor().
Referenced by CLLSTMLayerQuantized::run(), CLLSTMLayer::run(), and CLQLSTMLayer::run().
validate()
Status validate (const ITensorInfo * input1, const ITensorInfo * input2, const ITensorInfo * output, float scale, ConvertPolicy overflow_policy, RoundingPolicy rounding_policy, const ActivationLayerInfo & act_info = ActivationLayerInfo()) static
Static function to check if given info will lead to a valid configuration of CLPixelWiseMultiplication.
Valid configurations (Input1,Input2) -> Output :
(U8,U8) -> U8
(U8,U8) -> S16
(U8,S16) -> S16
(S16,U8) -> S16
(S16,S16) -> S16
(F16,F16) -> F16
(F32,F32) -> F32
(QASYMM8,QASYMM8) -> QASYMM8
(QASYMM8_SIGNED,QASYMM8_SIGNED) -> QASYMM8_SIGNED
(QSYMM16,QSYMM16) -> QSYMM16
(QSYMM16,QSYMM16) -> S32
Parameters
[in] input1 An input tensor info. Data types supported: U8/QASYMM8/QASYMM8_SIGNED/S16/QSYMM16/F16/F32.
[in] input2 An input tensor info. Data types supported: U8/QASYMM8/QASYMM8_SIGNED/S16/QSYMM16/F16/F32.
[in] output The output tensor info. Data types supported: U8/QASYMM8/QASYMM8_SIGNED/S16/QSYMM16/F16/F32.
[in] scale Scale to apply after multiplication. Scale must be positive and its value must be either 1/255 or 1/2^n where n is between 0 and 15.
[in] overflow_policy Overflow policy. Supported overflow policies: Wrap, Saturate
[in] rounding_policy Rounding policy. Supported rounding modes: to zero, to nearest even.
[in] act_info (Optional) Activation layer information in case of a fused activation.
Returns
a status
Definition at line 161 of file CLPixelWiseMultiplication.cpp.
 {
     return experimental::CLPixelWiseMultiplication::validate(input1, input2, output, scale, overflow_policy, rounding_policy, act_info);
 }
References arm_compute::test::validation::scale, and CLPixelWiseMultiplication::validate().
Referenced by CLLSTMLayerQuantized::validate(), CLLSTMLayer::validate(), and CLQLSTMLayer::validate().
The documentation for this class was generated from the following files:
arm_compute/runtime/CL/functions/CLPixelWiseMultiplication.h
src/runtime/CL/functions/CLPixelWiseMultiplication.cpp