Compute Library: CLFlattenLayerKernel Class Reference
CLFlattenLayerKernel Class Reference
OpenCL interface for the flatten kernel.
#include <CLFlattenLayerKernel.h>
Public Member Functions
CLFlattenLayerKernel ()
Default constructor.
CLFlattenLayerKernel (const CLFlattenLayerKernel &)=delete
Prevent instances of this class from being copied (As this class contains pointers)
CLFlattenLayerKernel & operator= (const CLFlattenLayerKernel &)=delete
Prevent instances of this class from being copied (As this class contains pointers)
CLFlattenLayerKernel (CLFlattenLayerKernel &&)=default
Allow instances of this class to be moved.
CLFlattenLayerKernel & operator= (CLFlattenLayerKernel &&)=default
Allow instances of this class to be moved.
void configure (const ICLTensor *input, ICLTensor *output)
Set the input and output of the kernel.
void configure (const CLCompileContext &compile_context, const ICLTensor *input, ICLTensor *output)
Set the input and output of the kernel.
void run (const Window &window, cl::CommandQueue &queue) override
Enqueue the OpenCL kernel to process the given window on the passed OpenCL command queue.
Public Member Functions inherited from ICLKernel
ICLKernel ()
Constructor.
cl::Kernel & kernel ()
Returns a reference to the OpenCL kernel of this object.
template<typename T >
void add_1D_array_argument (unsigned int &idx, const ICLArray< T > *array, const Strides &strides, unsigned int num_dimensions, const Window &window)
Add the passed 1D array's parameters to the object's kernel's arguments starting from the index idx.
void add_1D_tensor_argument (unsigned int &idx, const ICLTensor *tensor, const Window &window)
Add the passed 1D tensor's parameters to the object's kernel's arguments starting from the index idx.
void add_1D_tensor_argument_if (bool cond, unsigned int &idx, const ICLTensor *tensor, const Window &window)
Add the passed 1D tensor's parameters to the object's kernel's arguments starting from the index idx if the condition is true.
void add_2D_tensor_argument (unsigned int &idx, const ICLTensor *tensor, const Window &window)
Add the passed 2D tensor's parameters to the object's kernel's arguments starting from the index idx.
void add_2D_tensor_argument_if (bool cond, unsigned int &idx, const ICLTensor *tensor, const Window &window)
Add the passed 2D tensor's parameters to the object's kernel's arguments starting from the index idx if the condition is true.
void add_3D_tensor_argument (unsigned int &idx, const ICLTensor *tensor, const Window &window)
Add the passed 3D tensor's parameters to the object's kernel's arguments starting from the index idx.
void add_4D_tensor_argument (unsigned int &idx, const ICLTensor *tensor, const Window &window)
Add the passed 4D tensor's parameters to the object's kernel's arguments starting from the index idx.
virtual void run_op (ITensorPack &tensors, const Window &window, cl::CommandQueue &queue)
Enqueue the OpenCL kernel to process the given window on the passed OpenCL command queue.
template<typename T >
void add_argument (unsigned int &idx, T value)
Add the passed parameters to the object's kernel's arguments starting from the index idx.
void set_lws_hint (const cl::NDRange &lws_hint)
Set the Local-Workgroup-Size hint.
cl::NDRange lws_hint () const
Return the Local-Workgroup-Size hint.
const std::string & config_id () const
Get the configuration ID.
void set_target (GPUTarget target)
Set the targeted GPU architecture.
void set_target (cl::Device &device)
Set the targeted GPU architecture according to the CL device.
GPUTarget get_target () const
Get the targeted GPU architecture.
size_t get_max_workgroup_size ()
Get the maximum workgroup size for the device the CLKernelLibrary uses.
template<unsigned int dimension_size>
void add_tensor_argument (unsigned &idx, const ICLTensor *tensor, const Window &window)
template<typename T , unsigned int dimension_size>
void add_array_argument (unsigned &idx, const ICLArray< T > *array, const Strides &strides, unsigned int num_dimensions, const Window &window)
Add the passed array's parameters to the object's kernel's arguments starting from the index idx.
Public Member Functions inherited from IKernel
IKernel ()
Constructor.
virtual ~IKernel ()=default
Destructor.
virtual bool is_parallelisable () const
Indicates whether or not the kernel is parallelisable.
virtual BorderSize border_size () const
The size of the border for that kernel.
const Window & window () const
The maximum window the kernel can be executed on.
Static Public Member Functions
static Status validate (const ITensorInfo *input, const ITensorInfo *output)
Static function to check if given info will lead to a valid configuration of CLFlattenLayerKernel.
Static Public Member Functions inherited from ICLKernel
static constexpr unsigned int num_arguments_per_1D_array ()
Returns the number of arguments enqueued per 1D array object.
static constexpr unsigned int num_arguments_per_1D_tensor ()
Returns the number of arguments enqueued per 1D tensor object.
static constexpr unsigned int num_arguments_per_2D_tensor ()
Returns the number of arguments enqueued per 2D tensor object.
static constexpr unsigned int num_arguments_per_3D_tensor ()
Returns the number of arguments enqueued per 3D tensor object.
static constexpr unsigned int num_arguments_per_4D_tensor ()
Returns the number of arguments enqueued per 4D tensor object.
static cl::NDRange gws_from_window (const Window &window)
Get the global work size given an execution window.
Data Fields
const ICLTensor * _input
ICLTensor * _output
Detailed Description
OpenCL interface for the flatten kernel.
Definition at line 34 of file CLFlattenLayerKernel.h.
Constructor & Destructor Documentation
CLFlattenLayerKernel() [1/3]
CLFlattenLayerKernel ()
Default constructor.
Definition at line 57 of file CLFlattenLayerKernel.cpp.
     : _input(nullptr), _output(nullptr)
 {
 }
CLFlattenLayerKernel() [2/3]
CLFlattenLayerKernel (const CLFlattenLayerKernel &) delete
Prevent instances of this class from being copied (As this class contains pointers)
CLFlattenLayerKernel() [3/3]
CLFlattenLayerKernel (CLFlattenLayerKernel &&) default
Allow instances of this class to be moved.
Member Function Documentation
configure() [1/2]
void configure (const ICLTensor * input, ICLTensor * output)
Set the input and output of the kernel.
Parameters
[in] input First input tensor to flatten with at least 3 dimensions. The dimensions above the third will be interpreted as batches. Data types supported: All.
[out] output Output tensor with shape [w*h*d, input_batches] where: w = width input tensor, h = height input tensor and d = depth input tensor. Data type supported: same as input
Definition at line 62 of file CLFlattenLayerKernel.cpp.
 {
     configure(CLKernelLibrary::get().get_compile_context(), input, output);
 }
References CLKernelLibrary::get(), and arm_compute::test::validation::input.
configure() [2/2]
void configure (const CLCompileContext & compile_context, const ICLTensor * input, ICLTensor * output)
Set the input and output of the kernel.
Parameters
[in] compile_context The compile context to be used.
[in] input First input tensor to flatten with at least 3 dimensions. The dimensions above the third will be interpreted as batches. Data types supported: All.
[out] output Output tensor with shape [w*h*d, input_batches] where: w = width input tensor, h = height input tensor and d = depth input tensor. Data type supported: same as input
Definition at line 67 of file CLFlattenLayerKernel.cpp.
 {
     ARM_COMPUTE_ERROR_ON_NULLPTR(input, output);
     // Output tensor auto initialization if not yet initialized
     auto_init_if_empty(*output->info(), input->info()->clone()->set_tensor_shape(compute_flatten_shape(input->info())));
     auto padding_info = get_padding_info({ input, output });
     ARM_COMPUTE_ERROR_THROW_ON(validate_arguments(input->info(), output->info()));
     _input  = input;
     _output = output;
     CLBuildOptions build_opts;
     build_opts.add_option("-DDATA_TYPE=" + get_cl_unsigned_type_from_element_size(data_size_from_type(input->info()->data_type())));
     build_opts.add_option("-DSRC_WIDTH=" + support::cpp11::to_string(input->info()->dimension(0)));
     build_opts.add_option("-DSRC_HEIGHT=" + support::cpp11::to_string(input->info()->dimension(1)));
     build_opts.add_option("-DSRC_DEPTH=" + support::cpp11::to_string(input->info()->dimension(2)));
     build_opts.add_option_if(output->info()->num_dimensions() > 2, "-DDST_DIM1=" + support::cpp11::to_string(output->info()->dimension(1)));
     // Create kernel
     _kernel = create_kernel(compile_context, "flatten", build_opts.options());
     // Configure kernel window
     Window win = calculate_max_window(*input->info(), Steps());
     ICLKernel::configure_internal(win);
     output->info()->set_valid_region(ValidRegion(Coordinates(), output->info()->tensor_shape()));
     ARM_COMPUTE_ERROR_ON(has_padding_changed(padding_info));
     // Set config_id for enabling LWS tuning
     _config_id = "flatten";
     _config_id += "_";
     _config_id += lower_string(string_from_data_type(input->info()->data_type()));
     _config_id += "_";
     _config_id += support::cpp11::to_string(input->info()->dimension(0));
     _config_id += "_";
     _config_id += support::cpp11::to_string(input->info()->dimension(1));
     _config_id += "_";
     _config_id += support::cpp11::to_string(input->info()->dimension(2));
     _config_id += "_";
     _config_id += support::cpp11::to_string(output->info()->dimension(0));
     _config_id += "_";
     _config_id += support::cpp11::to_string(output->info()->dimension(1));
 }
References CLFlattenLayerKernel::_input, CLFlattenLayerKernel::_output, CLBuildOptions::add_option(), CLBuildOptions::add_option_if(), ARM_COMPUTE_ERROR_ON, ARM_COMPUTE_ERROR_ON_NULLPTR, ARM_COMPUTE_ERROR_THROW_ON, arm_compute::auto_init_if_empty(), arm_compute::calculate_max_window(), arm_compute::misc::shape_calculator::compute_flatten_shape(), arm_compute::create_kernel(), arm_compute::data_size_from_type(), ITensorInfo::dimension(), arm_compute::get_cl_unsigned_type_from_element_size(), arm_compute::get_padding_info(), arm_compute::has_padding_changed(), ITensor::info(), arm_compute::test::validation::input, arm_compute::lower_string(), ITensorInfo::num_dimensions(), CLBuildOptions::options(), ITensorInfo::set_valid_region(), arm_compute::string_from_data_type(), ITensorInfo::tensor_shape(), arm_compute::support::cpp11::to_string(), and arm_compute::validate_arguments().
operator=() [1/2]
CLFlattenLayerKernel& operator= (const CLFlattenLayerKernel &) delete
Prevent instances of this class from being copied (As this class contains pointers)
operator=() [2/2]
CLFlattenLayerKernel& operator= (CLFlattenLayerKernel &&) default
Allow instances of this class to be moved.
run()
void run (const Window & window, cl::CommandQueue & queue) override virtual
Enqueue the OpenCL kernel to process the given window on the passed OpenCL command queue.
Note
The queue is not flushed by this method, and therefore the kernel will not have been executed by the time this method returns.
Parameters
[in] window Region on which to execute the kernel. (Must be a valid region of the window returned by window()).
[in,out] queue Command queue on which to enqueue the kernel.
Reimplemented from ICLKernel.
Definition at line 121 of file CLFlattenLayerKernel.cpp.
 {
     ARM_COMPUTE_ERROR_ON_UNCONFIGURED_KERNEL(this);
     ARM_COMPUTE_ERROR_ON_MISMATCHING_WINDOWS(ICLKernel::window(), window);
     Window collapsed_window = window.collapse(ICLKernel::window(), Window::DimZ);
     Window output_window;
     output_window.use_tensor_dimensions(_output->info()->tensor_shape());
     // Run kernel
     unsigned int idx = 0;
     add_4D_tensor_argument(idx, _input, collapsed_window);
     add_3D_tensor_argument(idx, _output, output_window);
     enqueue(queue, *this, collapsed_window, lws_hint());
 }
References CLFlattenLayerKernel::_input, CLFlattenLayerKernel::_output, ICLKernel::add_3D_tensor_argument(), ICLKernel::add_4D_tensor_argument(), ARM_COMPUTE_ERROR_ON_MISMATCHING_WINDOWS, ARM_COMPUTE_ERROR_ON_UNCONFIGURED_KERNEL, Window::collapse(), Window::DimZ, arm_compute::enqueue(), ITensor::info(), ICLKernel::lws_hint(), ITensorInfo::tensor_shape(), Window::use_tensor_dimensions(), and IKernel::window().
validate()
Status validate (const ITensorInfo * input, const ITensorInfo * output) static
Static function to check if given info will lead to a valid configuration of CLFlattenLayerKernel.
Parameters
[in] input First input tensor to flatten with at least 3 dimensions. The dimensions above the third will be interpreted as batches. Data types supported: All.
[out] output Output tensor with shape [w*h*d, input_batches] where: w = width input tensor, h = height input tensor and d = depth input tensor. Data type supported: same as input
Returns
a status
Definition at line 115 of file CLFlattenLayerKernel.cpp.
 {
     ARM_COMPUTE_RETURN_ON_ERROR(validate_arguments(input, output));
     return Status{};
 }
References ARM_COMPUTE_RETURN_ON_ERROR, arm_compute::test::validation::input, and arm_compute::validate_arguments().
Referenced by CLFlattenLayer::validate().
Field Documentation
_input
const ICLTensor* _input
Definition at line 79 of file CLFlattenLayerKernel.h.
Referenced by CLFlattenLayerKernel::configure(), and CLFlattenLayerKernel::run().
_output
ICLTensor* _output
Definition at line 80 of file CLFlattenLayerKernel.h.
Referenced by CLFlattenLayerKernel::configure(), and CLFlattenLayerKernel::run().
The documentation for this class was generated from the following files:
src/core/CL/kernels/CLFlattenLayerKernel.h
src/core/CL/kernels/CLFlattenLayerKernel.cpp