Compute Library: CLSaturatedArithmeticOperationKernel Class Reference
CLSaturatedArithmeticOperationKernel Class Reference
Addition operation.
#include <CLElementwiseOperationKernel.h>
Public Member Functions
CLSaturatedArithmeticOperationKernel ()
void configure (ArithmeticOperation op, ITensorInfo *input1, ITensorInfo *input2, ITensorInfo *output, const ConvertPolicy &policy, const ActivationLayerInfo &act_info=ActivationLayerInfo())
Static function to check if given info will lead to a valid configuration of CLSaturatedArithmeticOperationKernel.
void configure (const CLCompileContext &compile_context, ArithmeticOperation op, ITensorInfo *input1, ITensorInfo *input2, ITensorInfo *output, const ConvertPolicy &policy, const ActivationLayerInfo &act_info=ActivationLayerInfo())
Static function to check if given info will lead to a valid configuration of CLSaturatedArithmeticOperationKernel.
Public Member Functions inherited from CLElementwiseOperationKernel
CLElementwiseOperationKernel ()
Default constructor.
CLElementwiseOperationKernel (const CLElementwiseOperationKernel &)=delete
Prevent instances of this class from being copied (As this class contains pointers)
CLElementwiseOperationKernel & operator= (const CLElementwiseOperationKernel &)=delete
Prevent instances of this class from being copied (As this class contains pointers)
CLElementwiseOperationKernel (CLElementwiseOperationKernel &&)=default
Allow instances of this class to be moved.
CLElementwiseOperationKernel & operator= (CLElementwiseOperationKernel &&)=default
Allow instances of this class to be moved.
~CLElementwiseOperationKernel ()=default
Default destructor.
void run_op (ITensorPack &tensors, const Window &window, cl::CommandQueue &queue) override
Enqueue the OpenCL kernel to process the given window on the passed OpenCL command queue.
Public Member Functions inherited from ICLKernel
ICLKernel ()
Constructor.
cl::Kernel & kernel ()
Returns a reference to the OpenCL kernel of this object.
template<typename T >
void add_1D_array_argument (unsigned int &idx, const ICLArray< T > *array, const Strides &strides, unsigned int num_dimensions, const Window &window)
Add the passed 1D array's parameters to the object's kernel's arguments starting from the index idx.
void add_1D_tensor_argument (unsigned int &idx, const ICLTensor *tensor, const Window &window)
Add the passed 1D tensor's parameters to the object's kernel's arguments starting from the index idx.
void add_1D_tensor_argument_if (bool cond, unsigned int &idx, const ICLTensor *tensor, const Window &window)
Add the passed 1D tensor's parameters to the object's kernel's arguments starting from the index idx if the condition is true.
void add_2D_tensor_argument (unsigned int &idx, const ICLTensor *tensor, const Window &window)
Add the passed 2D tensor's parameters to the object's kernel's arguments starting from the index idx.
void add_2D_tensor_argument_if (bool cond, unsigned int &idx, const ICLTensor *tensor, const Window &window)
Add the passed 2D tensor's parameters to the object's kernel's arguments starting from the index idx if the condition is true.
void add_3D_tensor_argument (unsigned int &idx, const ICLTensor *tensor, const Window &window)
Add the passed 3D tensor's parameters to the object's kernel's arguments starting from the index idx.
void add_4D_tensor_argument (unsigned int &idx, const ICLTensor *tensor, const Window &window)
Add the passed 4D tensor's parameters to the object's kernel's arguments starting from the index idx.
virtual void run (const Window &window, cl::CommandQueue &queue)
Enqueue the OpenCL kernel to process the given window on the passed OpenCL command queue.
template<typename T >
void add_argument (unsigned int &idx, T value)
Add the passed parameters to the object's kernel's arguments starting from the index idx.
void set_lws_hint (const cl::NDRange &lws_hint)
Set the Local-Workgroup-Size hint.
cl::NDRange lws_hint () const
Return the Local-Workgroup-Size hint.
const std::string & config_id () const
Get the configuration ID.
void set_target (GPUTarget target)
Set the targeted GPU architecture.
void set_target (cl::Device &device)
Set the targeted GPU architecture according to the CL device.
GPUTarget get_target () const
Get the targeted GPU architecture.
size_t get_max_workgroup_size ()
Get the maximum workgroup size for the device the CLKernelLibrary uses.
template<unsigned int dimension_size>
void add_tensor_argument (unsigned &idx, const ICLTensor *tensor, const Window &window)
template<typename T , unsigned int dimension_size>
void add_array_argument (unsigned &idx, const ICLArray< T > *array, const Strides &strides, unsigned int num_dimensions, const Window &window)
Add the passed array's parameters to the object's kernel's arguments starting from the index idx.
Public Member Functions inherited from IKernel
IKernel ()
Constructor.
virtual ~IKernel ()=default
Destructor.
virtual bool is_parallelisable () const
Indicates whether or not the kernel is parallelisable.
virtual BorderSize border_size () const
The size of the border for that kernel.
const Window & window () const
The maximum window the kernel can be executed on.
Static Public Member Functions
static Status validate (ArithmeticOperation op, const ITensorInfo *input1, const ITensorInfo *input2, const ITensorInfo *output, const ConvertPolicy &policy, const ActivationLayerInfo &act_info=ActivationLayerInfo())
Static function to check if given info will lead to a valid configuration of CLSaturatedArithmeticOperationKernel.
Static Public Member Functions inherited from ICLKernel
static constexpr unsigned int num_arguments_per_1D_array ()
Returns the number of arguments enqueued per 1D array object.
static constexpr unsigned int num_arguments_per_1D_tensor ()
Returns the number of arguments enqueued per 1D tensor object.
static constexpr unsigned int num_arguments_per_2D_tensor ()
Returns the number of arguments enqueued per 2D tensor object.
static constexpr unsigned int num_arguments_per_3D_tensor ()
Returns the number of arguments enqueued per 3D tensor object.
static constexpr unsigned int num_arguments_per_4D_tensor ()
Returns the number of arguments enqueued per 4D tensor object.
static cl::NDRange gws_from_window (const Window &window)
Get the global work size given an execution window.
Detailed Description
Addition operation.
Definition at line 147 of file CLElementwiseOperationKernel.h.
Constructor & Destructor Documentation
CLSaturatedArithmeticOperationKernel()
CLSaturatedArithmeticOperationKernel () inline
Definition at line 150 of file CLElementwiseOperationKernel.h.
         : CLElementwiseOperationKernel(), _policy(), _op()
     {
     }
Member Function Documentation
configure() [1/2]
void configure (ArithmeticOperation op, ITensorInfo * input1, ITensorInfo * input2, ITensorInfo * output, const ConvertPolicy & policy, const ActivationLayerInfo & act_info = ActivationLayerInfo())
Static function to check if given info will lead to a valid configuration of CLSaturatedArithmeticOperationKernel.
Arithmetic operations with saturation.
Parameters
[in] op Arithmetic operation to be executed.
[in] input1 First tensor input info. Data types supported: U8/QASYMM8/QASYMM8_SIGNED/S16/QSYMM16/F16/S32/F32.
[in] input2 Second tensor input info. Data types supported: Same as input1.
[in] output Output tensor info. Data types supported: Same as input1.
[in] policy Policy to use to handle overflow.
[in] act_info (Optional) Activation layer information in case of a fused activation.
Definition at line 393 of file CLElementwiseOperationKernel.cpp.
 {
     configure(CLKernelLibrary::get().get_compile_context(), op, input1, input2, output, policy, act_info);
 }
References CLKernelLibrary::get().
configure() [2/2]
void configure (const CLCompileContext & compile_context, ArithmeticOperation op, ITensorInfo * input1, ITensorInfo * input2, ITensorInfo * output, const ConvertPolicy & policy, const ActivationLayerInfo & act_info = ActivationLayerInfo())
Static function to check if given info will lead to a valid configuration of CLSaturatedArithmeticOperationKernel.
Parameters
[in] compile_context The compile context to be used.
[in] op Arithmetic operation to be executed.
[in] input1 First tensor input info. Data types supported: U8/QASYMM8/QASYMM8_SIGNED/S16/QSYMM16/F16/S32/F32.
[in] input2 Second tensor input info. Data types supported: Same as input1.
[in] output Output tensor info. Data types supported: Same as input1.
[in] policy Policy to use to handle overflow.
[in] act_info (Optional) Activation layer information in case of a fused activation.
Definition at line 399 of file CLElementwiseOperationKernel.cpp.
 {
     ARM_COMPUTE_ERROR_ON_NULLPTR(input1, input2, output);
     ARM_COMPUTE_ERROR_THROW_ON(CLSaturatedArithmeticOperationKernel::validate(op, input1, input2, output, policy, act_info));
     auto padding_info = get_padding_info({ input1, input2, output });
     _policy   = policy;
     _op       = op;
     _act_info = act_info;
     configure_common(compile_context, input1, input2, output);
     ARM_COMPUTE_ERROR_ON(has_padding_changed(padding_info));
 }
References ARM_COMPUTE_ERROR_ON, ARM_COMPUTE_ERROR_ON_NULLPTR, ARM_COMPUTE_ERROR_THROW_ON, arm_compute::get_padding_info(), arm_compute::has_padding_changed(), and CLSaturatedArithmeticOperationKernel::validate().
validate()
Status validate (ArithmeticOperation op, const ITensorInfo * input1, const ITensorInfo * input2, const ITensorInfo * output, const ConvertPolicy & policy, const ActivationLayerInfo & act_info = ActivationLayerInfo()) static
Static function to check if given info will lead to a valid configuration of CLSaturatedArithmeticOperationKernel.
Parameters
[in] op Arithmetic operation to be executed.
[in] input1 First tensor input info info. Data types supported: U8/QASYMM8/QASYMM8_SIGNED/S16/QSYMM16/F16/S32/F32.
[in] input2 Second tensor input info info. Data types supported: Same as input1.
[in] output Output tensor info info. Data types supported: Same as input1.
[in] policy Policy to use to handle overflow.
[in] act_info (Optional) Activation layer information in case of a fused activation.
Returns
a Status
Definition at line 414 of file CLElementwiseOperationKernel.cpp.
 {
     ARM_COMPUTE_UNUSED(op, policy);
     ARM_COMPUTE_RETURN_ERROR_ON_NULLPTR(input1, input2, output);
     ARM_COMPUTE_RETURN_ON_ERROR(validate_arguments_with_arithmetic_rules(*input1, *input2, *output));
     ARM_COMPUTE_RETURN_ON_ERROR(validate_and_configure_window_for_arithmetic_operators(*input1->clone(), *input2->clone(), *output->clone()).first);
     ARM_COMPUTE_RETURN_ERROR_ON(act_info.enabled() && !is_data_type_float(output->data_type()));
     return Status{};
 }
References ARM_COMPUTE_RETURN_ERROR_ON, ARM_COMPUTE_RETURN_ERROR_ON_NULLPTR, ARM_COMPUTE_RETURN_ON_ERROR, ARM_COMPUTE_UNUSED, ICloneable< T >::clone(), ITensorInfo::data_type(), ActivationLayerInfo::enabled(), and arm_compute::is_data_type_float().
Referenced by CLSaturatedArithmeticOperationKernel::configure(), CLArithmeticAddition::validate(), and CLArithmeticSubtraction::validate().
The documentation for this class was generated from the following files:
src/core/CL/kernels/CLElementwiseOperationKernel.h
src/core/CL/kernels/CLElementwiseOperationKernel.cpp