Compute Library: CLDepthConvertLayerKernel Class Reference
CLDepthConvertLayerKernel Class Reference
Interface for the depth conversion kernel.
#include <CLDepthConvertLayerKernel.h>
Public Member Functions
void configure (const ICLTensor *input, ICLTensor *output, ConvertPolicy policy, uint32_t shift)
Set the input and output of the kernel.
void configure (const CLCompileContext &compile_context, const ICLTensor *input, ICLTensor *output, ConvertPolicy policy, uint32_t shift)
Set the input and output of the kernel.
Public Member Functions inherited from ICLSimple3DKernel
void run (const Window &window, cl::CommandQueue &queue) override
Enqueue the OpenCL kernel to process the given window on the passed OpenCL command queue.
Public Member Functions inherited from ICLSimpleKernel
ICLSimpleKernel ()
Constructor.
ICLSimpleKernel (const ICLSimpleKernel &)=delete
Prevent instances of this class from being copied (As this class contains pointers)
ICLSimpleKernel & operator= (const ICLSimpleKernel &)=delete
Prevent instances of this class from being copied (As this class contains pointers)
ICLSimpleKernel (ICLSimpleKernel &&)=default
Allow instances of this class to be moved.
ICLSimpleKernel & operator= (ICLSimpleKernel &&)=default
Allow instances of this class to be moved.
~ICLSimpleKernel ()=default
Default destructor.
void configure (const ICLTensor *input, ICLTensor *output, unsigned int num_elems_processed_per_iteration, bool border_undefined=false, const BorderSize &border_size=BorderSize())
Configure the kernel.
Public Member Functions inherited from ICLKernel
ICLKernel ()
Constructor.
cl::Kernel & kernel ()
Returns a reference to the OpenCL kernel of this object.
template<typename T >
void add_1D_array_argument (unsigned int &idx, const ICLArray< T > *array, const Strides &strides, unsigned int num_dimensions, const Window &window)
Add the passed 1D array's parameters to the object's kernel's arguments starting from the index idx.
void add_1D_tensor_argument (unsigned int &idx, const ICLTensor *tensor, const Window &window)
Add the passed 1D tensor's parameters to the object's kernel's arguments starting from the index idx.
void add_1D_tensor_argument_if (bool cond, unsigned int &idx, const ICLTensor *tensor, const Window &window)
Add the passed 1D tensor's parameters to the object's kernel's arguments starting from the index idx if the condition is true.
void add_2D_tensor_argument (unsigned int &idx, const ICLTensor *tensor, const Window &window)
Add the passed 2D tensor's parameters to the object's kernel's arguments starting from the index idx.
void add_2D_tensor_argument_if (bool cond, unsigned int &idx, const ICLTensor *tensor, const Window &window)
Add the passed 2D tensor's parameters to the object's kernel's arguments starting from the index idx if the condition is true.
void add_3D_tensor_argument (unsigned int &idx, const ICLTensor *tensor, const Window &window)
Add the passed 3D tensor's parameters to the object's kernel's arguments starting from the index idx.
void add_4D_tensor_argument (unsigned int &idx, const ICLTensor *tensor, const Window &window)
Add the passed 4D tensor's parameters to the object's kernel's arguments starting from the index idx.
virtual void run_op (ITensorPack &tensors, const Window &window, cl::CommandQueue &queue)
Enqueue the OpenCL kernel to process the given window on the passed OpenCL command queue.
template<typename T >
void add_argument (unsigned int &idx, T value)
Add the passed parameters to the object's kernel's arguments starting from the index idx.
void set_lws_hint (const cl::NDRange &lws_hint)
Set the Local-Workgroup-Size hint.
cl::NDRange lws_hint () const
Return the Local-Workgroup-Size hint.
const std::string & config_id () const
Get the configuration ID.
void set_target (GPUTarget target)
Set the targeted GPU architecture.
void set_target (cl::Device &device)
Set the targeted GPU architecture according to the CL device.
GPUTarget get_target () const
Get the targeted GPU architecture.
size_t get_max_workgroup_size ()
Get the maximum workgroup size for the device the CLKernelLibrary uses.
template<unsigned int dimension_size>
void add_tensor_argument (unsigned &idx, const ICLTensor *tensor, const Window &window)
template<typename T , unsigned int dimension_size>
void add_array_argument (unsigned &idx, const ICLArray< T > *array, const Strides &strides, unsigned int num_dimensions, const Window &window)
Add the passed array's parameters to the object's kernel's arguments starting from the index idx.
Public Member Functions inherited from IKernel
IKernel ()
Constructor.
virtual ~IKernel ()=default
Destructor.
virtual bool is_parallelisable () const
Indicates whether or not the kernel is parallelisable.
virtual BorderSize border_size () const
The size of the border for that kernel.
const Window & window () const
The maximum window the kernel can be executed on.
Static Public Member Functions
static Status validate (const ITensorInfo *input, const ITensorInfo *output, ConvertPolicy policy, uint32_t shift)
Static function to check if given info will lead to a valid configuration of CLDepthConvertLayerKernel.
Static Public Member Functions inherited from ICLKernel
static constexpr unsigned int num_arguments_per_1D_array ()
Returns the number of arguments enqueued per 1D array object.
static constexpr unsigned int num_arguments_per_1D_tensor ()
Returns the number of arguments enqueued per 1D tensor object.
static constexpr unsigned int num_arguments_per_2D_tensor ()
Returns the number of arguments enqueued per 2D tensor object.
static constexpr unsigned int num_arguments_per_3D_tensor ()
Returns the number of arguments enqueued per 3D tensor object.
static constexpr unsigned int num_arguments_per_4D_tensor ()
Returns the number of arguments enqueued per 4D tensor object.
static cl::NDRange gws_from_window (const Window &window)
Get the global work size given an execution window.
Detailed Description
Interface for the depth conversion kernel.
Definition at line 37 of file CLDepthConvertLayerKernel.h.
Member Function Documentation
configure() [1/2]
void configure (const ICLTensor * input, ICLTensor * output, ConvertPolicy policy, uint32_t shift)
Set the input and output of the kernel.
Valid conversions Input -> Output :
QSYMM8_PER_CHANNEL -> QASYMM8 (ATTENTION: it is the user's responsibility to keep track of the quantization info in the TensorInfo meta-data)
U8 -> S8, U16, S16, U32, S32, F16, F32
U16 -> U8, S8, S16, U32, S32, F16, F32
S16 -> U8, S8, U16, U32, S32, F16, F32
U32 -> U8, S8, U16, S16, S32, F16, F32
S32 -> U8, S8, U16, S16, U32, F16, F32
F16 -> U8, S8, U16, S16, U32, F32
F32 -> U8, S8, U16, S16, U32, F16
Parameters
[in] input The input tensor to convert. Data types supported: U8/S8/QSYMM8_PER_CHANNEL/U16/S16/U32/S32/F16/F32.
[out] output The output tensor. Data types supported: U8/S8/QASYMM8/U16/S16/U32/S32/F16/F32.
[in] policy Conversion policy
[in] shift Value for down/up conversions. Must be 0 <= shift < 8.
Definition at line 76 of file CLDepthConvertLayerKernel.cpp.
 {
     configure(CLKernelLibrary::get().get_compile_context(), input, output, policy, shift);
 }
References CLKernelLibrary::get(), and arm_compute::test::validation::input.
configure() [2/2]
void configure (const CLCompileContext & compile_context, const ICLTensor * input, ICLTensor * output, ConvertPolicy policy, uint32_t shift)
Set the input and output of the kernel.
Valid conversions Input -> Output :
QSYMM8_PER_CHANNEL -> QASYMM8 (ATTENTION: it is the user's responsibility to keep track of the quantization info in the TensorInfo meta-data)
U8 -> S8, U16, S16, U32, S32, F16, F32
U16 -> U8, S8, S16, U32, S32, F16, F32
S16 -> U8, S8, U16, U32, S32, F16, F32
U32 -> U8, S8, U16, S16, S32, F16, F32
S32 -> U8, S8, U16, S16, U32, F16, F32
F16 -> U8, S8, U16, S16, U32, F32
F32 -> U8, S8, U16, S16, U32, F16
Parameters
[in] compile_context The compile context to be used.
[in] input The input tensor to convert. Data types supported: U8/S8/QSYMM8_PER_CHANNEL/U16/S16/U32/S32/F16/F32.
[out] output The output tensor. Data types supported: U8/S8/QASYMM8/U16/S16/U32/S32/F16/F32.
[in] policy Conversion policy
[in] shift Value for down/up conversions. Must be 0 <= shift < 8.
Definition at line 81 of file CLDepthConvertLayerKernel.cpp.
 {
     ARM_COMPUTE_ERROR_ON_NULLPTR(input, output);
     _input  = input;
     _output = output;
     // Auto initialize output shape if not initialized (We can only auto-configure the shape, datatype must be given)
     set_shape_if_empty(*output->info(), input->info()->tensor_shape());
     ARM_COMPUTE_ERROR_THROW_ON(validate_arguments(input->info(), output->info(), policy, shift));
     auto padding_info = get_padding_info({ input, output });
     // Get data sizes
     const size_t input_size  = data_size_from_type(input->info()->data_type());
     const size_t output_size = data_size_from_type(output->info()->data_type());
     // Get number of elements to process per iterations
     const unsigned int num_elems_processed_per_iteration = adjust_vec_size(16 / input->info()->element_size(), input->info()->dimension(0));
     // Set build options
     CLBuildOptions build_opts;
     build_opts.add_option("-DVEC_SIZE=" + support::cpp11::to_string(num_elems_processed_per_iteration));
     build_opts.add_option("-DVEC_SIZE_LEFTOVER=" + support::cpp11::to_string(input->info()->dimension(0) % num_elems_processed_per_iteration));
     build_opts.add_option("-DDATA_TYPE_IN=" + get_cl_type_from_data_type(input->info()->data_type()));
     build_opts.add_option("-DDATA_TYPE_OUT=" + get_cl_type_from_data_type(output->info()->data_type()));
     // Conversions from float always SATURATE as out-of-bounds conversion from float->integer is implementation defined
     build_opts.add_option_if(is_data_type_float(input->info()->data_type()) || policy == ConvertPolicy::SATURATE, "-DSATURATE");
     build_opts.add_option_if(is_data_type_float(input->info()->data_type()) || is_data_type_float(output->info()->data_type()), "-DIS_DATA_TYPE_FLOAT");
     build_opts.add_option_if(is_data_type_quantized(input->info()->data_type()), "-DIS_DATA_TYPE_QUANTIZED");
     // Create kernel
     const std::string kernel_name = (input_size >= output_size) ? "convert_depth_down" : "convert_depth_up";
     _kernel                       = create_kernel(compile_context, kernel_name, build_opts.options());
     // Set shift arg
     unsigned int idx = 2 * num_arguments_per_3D_tensor(); // Skip the input and output parameters
     _kernel.setArg(idx++, shift);
     // Since we have a leftover vector size calculated using the input tensor shape, it is required to
     // have the input region equal to the tensor shape
     ValidRegion input_valid_region = input->info()->valid_region();
     input->info()->set_valid_region(ValidRegion(Coordinates(0, 0), input->info()->tensor_shape()));
     // Configure kernel
     Window win = calculate_max_window(*input->info(), Steps(num_elems_processed_per_iteration));
     ICLKernel::configure_internal(win);
     // Collapse window
     const Window &full_window      = window();
     Window        collapsed_window = full_window.collapse_if_possible(full_window, Window::DimZ);
     ICLKernel::configure_internal(collapsed_window);
     // Restore the valid region
     input->info()->set_valid_region(input_valid_region);
     ARM_COMPUTE_ERROR_ON(has_padding_changed(padding_info));
     // Set config_id for enabling LWS tuning
     _config_id = kernel_name;
     _config_id += "_";
     _config_id += lower_string(string_from_data_type(input->info()->data_type()));
     _config_id += "_";
     _config_id += support::cpp11::to_string(input->info()->dimension(0));
     _config_id += "_";
     _config_id += support::cpp11::to_string(input->info()->dimension(1));
     _config_id += "_";
     _config_id += support::cpp11::to_string(output->info()->dimension(0));
     _config_id += "_";
     _config_id += support::cpp11::to_string(output->info()->dimension(1));
 }
References CLBuildOptions::add_option(), arm_compute::adjust_vec_size(), ARM_COMPUTE_ERROR_ON, ARM_COMPUTE_ERROR_ON_NULLPTR, ARM_COMPUTE_ERROR_THROW_ON, arm_compute::calculate_max_window(), Window::collapse_if_possible(), arm_compute::create_kernel(), arm_compute::data_size_from_type(), ITensorInfo::data_type(), ITensorInfo::dimension(), Window::DimZ, arm_compute::get_cl_type_from_data_type(), arm_compute::get_padding_info(), arm_compute::has_padding_changed(), ITensor::info(), arm_compute::test::validation::input, arm_compute::test::validation::input_size, arm_compute::is_data_type_float(), arm_compute::is_data_type_quantized(), kernel_name, arm_compute::lower_string(), ICLKernel::num_arguments_per_3D_tensor(), num_elems_processed_per_iteration, arm_compute::test::validation::output_size, arm_compute::SATURATE, arm_compute::set_shape_if_empty(), arm_compute::string_from_data_type(), arm_compute::support::cpp11::to_string(), arm_compute::validate_arguments(), and IKernel::window().
validate()
Status validate (const ITensorInfo * input, const ITensorInfo * output, ConvertPolicy policy, uint32_t shift) static
Static function to check if given info will lead to a valid configuration of CLDepthConvertLayerKernel.
Parameters
[in] input Source tensor info. Data types supported: U8/S8/QSYMM8_PER_CHANNEL/U16/S16/U32/S32/F16/F32.
[in] output Destination tensor info. Data type supported: U8/S8/QASYMM8/U16/S16/U32/S32/F16/F32.
[in] policy Conversion policy
[in] shift Value for down/up conversions. Must be 0 <= shift < 8.
Returns
a status
Definition at line 154 of file CLDepthConvertLayerKernel.cpp.
 {
     ARM_COMPUTE_RETURN_ON_ERROR(validate_arguments(input, output, policy, shift));
     return Status{};
 }
References ARM_COMPUTE_RETURN_ON_ERROR, arm_compute::test::validation::input, and arm_compute::validate_arguments().
Referenced by CLCast::validate(), CLDepthConvertLayer::validate(), and CLGEMMLowpMatrixMultiplyCore::validate().
The documentation for this class was generated from the following files:
src/core/CL/kernels/CLDepthConvertLayerKernel.h
src/core/CL/kernels/CLDepthConvertLayerKernel.cpp