Compute Library: CLConvolutionLayerReshapeWeights Class Reference
CLConvolutionLayerReshapeWeights Class Reference
Function to reshape and transpose the weights.
#include <CLGEMMConvolutionLayer.h>
Public Member Functions
CLConvolutionLayerReshapeWeights ()
Constructor.
CLConvolutionLayerReshapeWeights (const CLConvolutionLayerReshapeWeights &)=delete
Prevent instances of this class from being copied.
CLConvolutionLayerReshapeWeights & operator= (const CLConvolutionLayerReshapeWeights &)=delete
Prevent instances of this class from being copied.
CLConvolutionLayerReshapeWeights (CLConvolutionLayerReshapeWeights &&)=default
Default move constructor.
CLConvolutionLayerReshapeWeights & operator= (CLConvolutionLayerReshapeWeights &&)=default
Default move assignment operator.
~CLConvolutionLayerReshapeWeights ()
Default destructor.
void configure (const ICLTensor *weights, const ICLTensor *biases, ICLTensor *output, unsigned int num_groups=1)
Set the input and output tensors.
void configure (const CLCompileContext &compile_context, const ICLTensor *weights, const ICLTensor *biases, ICLTensor *output, unsigned int num_groups=1)
Set the input and output tensors.
void run () override
Run the kernels contained in the function.
Public Member Functions inherited from IFunction
virtual ~IFunction ()=default
Destructor.
virtual void prepare ()
Prepare the function for executing.
Static Public Member Functions
static Status validate (const ITensorInfo *weights, const ITensorInfo *biases, const ITensorInfo *output, unsigned int num_groups=1)
Static function to check if given info will lead to a valid configuration of CLConvolutionLayerReshapeWeights.
Detailed Description
Function to reshape and transpose the weights.
This function calls the following kernels:
CLWeightsReshapeKernel
Definition at line 52 of file CLGEMMConvolutionLayer.h.
Constructor & Destructor Documentation
CLConvolutionLayerReshapeWeights() [1/3]
CLConvolutionLayerReshapeWeights ()
Constructor.
Definition at line 60 of file CLGEMMConvolutionLayer.cpp.
     : _weights_reshape_kernel(support::cpp14::make_unique<CLWeightsReshapeKernel>())
 {
 }
CLConvolutionLayerReshapeWeights() [2/3]
CLConvolutionLayerReshapeWeights (const CLConvolutionLayerReshapeWeights &) delete
Prevent instances of this class from being copied.
CLConvolutionLayerReshapeWeights() [3/3]
CLConvolutionLayerReshapeWeights (CLConvolutionLayerReshapeWeights &&) default
Default move constructor.
~CLConvolutionLayerReshapeWeights()
~CLConvolutionLayerReshapeWeights () default
Default destructor.
Member Function Documentation
configure() [1/2]
void configure (const ICLTensor * weights, const ICLTensor * biases, ICLTensor * output, unsigned int num_groups = 1)
Set the input and output tensors.
Parameters
[in] weights Weights tensor. Weights are 4D tensor with dimensions [kernel_x, kernel_y, IFM, OFM]. Data type supported: QASYMM8/QASYMM8_SIGNED/QSYMM8_PER_CHANNEL/F16/F32.
[in] biases Biases tensor. Shared biases supported. Biases are 1D tensor with dimensions [OFM]. Data type supported: Same as weights.
[out] output Destination tensor. Data types supported: Same as weights.
[in] num_groups (Optional) Number of groups when performing a grouped convolution. num_groups != 1 is only supported for NCHW data layout
Definition at line 67 of file CLGEMMConvolutionLayer.cpp.
 {
     configure(CLKernelLibrary::get().get_compile_context(), weights, biases, output, num_groups);
 }
References CLKernelLibrary::get(), and arm_compute::test::validation::num_groups.
Referenced by CLConvolutionLayerReshapeWeightsTransform::configure(), and CLGEMMConvolutionLayer::configure().
configure() [2/2]
void configure (const CLCompileContext & compile_context, const ICLTensor * weights, const ICLTensor * biases, ICLTensor * output, unsigned int num_groups = 1)
Set the input and output tensors.
Parameters
[in] compile_context The compile context to be used.
[in] weights Weights tensor. Weights are 4D tensor with dimensions [kernel_x, kernel_y, IFM, OFM]. Data type supported: QASYMM8/QASYMM8_SIGNED/QSYMM8_PER_CHANNEL/F16/F32.
[in] biases Biases tensor. Shared biases supported. Biases are 1D tensor with dimensions [OFM]. Data type supported: Same as weights.
[out] output Destination tensor. Data types supported: Same as weights.
[in] num_groups (Optional) Number of groups when performing a grouped convolution. num_groups != 1 is only supported for NCHW data layout
Definition at line 72 of file CLGEMMConvolutionLayer.cpp.
 {
     // Perform validation step
     ARM_COMPUTE_ERROR_ON_NULLPTR(weights, output);
     ARM_COMPUTE_ERROR_THROW_ON(CLConvolutionLayerReshapeWeights::validate(weights->info(),
                                                                           (biases != nullptr) ? biases->info() : nullptr,
                                                                           output->info(),
                                                                           num_groups));
     const bool       append_biases = (biases != nullptr) && !is_data_type_quantized_asymmetric(weights->info()->data_type());
     const ICLTensor *biases_to_use = (append_biases) ? biases : nullptr;
     _weights_reshape_kernel->configure(compile_context, weights, biases_to_use, output, num_groups);
     output->info()->set_quantization_info(weights->info()->quantization_info());
 }
References ARM_COMPUTE_ERROR_ON_NULLPTR, ARM_COMPUTE_ERROR_THROW_ON, ITensorInfo::data_type(), ITensor::info(), arm_compute::is_data_type_quantized_asymmetric(), arm_compute::test::validation::num_groups, ITensorInfo::quantization_info(), ITensorInfo::set_quantization_info(), and CLConvolutionLayerReshapeWeights::validate().
operator=() [1/2]
CLConvolutionLayerReshapeWeights& operator= (const CLConvolutionLayerReshapeWeights &) delete
Prevent instances of this class from being copied.
operator=() [2/2]
CLConvolutionLayerReshapeWeights& operator= (CLConvolutionLayerReshapeWeights &&) default
Default move assignment operator.
run()
void run () override virtual
Run the kernels contained in the function.
For NEON kernels:
Multi-threading is used for the kernels which are parallelisable.
By default std::thread::hardware_concurrency() threads are used.
Note
CPPScheduler::set_num_threads() can be used to manually set the number of threads
For OpenCL kernels:
All the kernels are enqueued on the queue associated with CLScheduler.
The queue is then flushed.
Note
The function will not block until the kernels are executed. It is the user's responsibility to wait.
Will call prepare() on first run if hasn't been done
Implements IFunction.
Definition at line 114 of file CLGEMMConvolutionLayer.cpp.
 {
     CLScheduler::get().enqueue(*_weights_reshape_kernel);
 }
References CLScheduler::enqueue(), and CLScheduler::get().
Referenced by CLGEMMConvolutionLayer::prepare(), and CLConvolutionLayerReshapeWeightsTransform::run().
validate()
Status validate (const ITensorInfo * weights, const ITensorInfo * biases, const ITensorInfo * output, unsigned int num_groups = 1) static
Static function to check if given info will lead to a valid configuration of CLConvolutionLayerReshapeWeights.
Parameters
[in] weights Weights tensor. Weights are 4D tensor with dimensions [kernel_x, kernel_y, IFM, OFM]. Data type supported: QASYMM8/QASYMM8_SIGNED/QSYMM8_PER_CHANNEL/F16/F32.
[in] biases Biases tensor. Shared biases supported. Biases are 1D tensor with dimensions [OFM]. Data type supported: Same as weights.
[in] output Destination tensor. Data types supported: Same as weights.
[in] num_groups (Optional) Number of groups when performing a grouped convolution. num_groups != 1 is only supported for NCHW data layout
Returns
a status
Definition at line 89 of file CLGEMMConvolutionLayer.cpp.
 {
     ARM_COMPUTE_RETURN_ERROR_ON_NULLPTR(weights);
     ARM_COMPUTE_RETURN_ERROR_ON_DATA_TYPE_CHANNEL_NOT_IN(weights, 1, DataType::QASYMM8, DataType::QASYMM8_SIGNED, DataType::QSYMM8_PER_CHANNEL, DataType::F16, DataType::F32);
     ARM_COMPUTE_RETURN_ERROR_ON(weights->num_dimensions() > 4);
     if(biases != nullptr)
     {
         const int idx_kernels = get_data_layout_dimension_index(weights->data_layout(), DataLayoutDimension::BATCHES);
         ARM_COMPUTE_RETURN_ERROR_ON(is_data_type_quantized(weights->data_type()));
         ARM_COMPUTE_RETURN_ERROR_ON_MISMATCHING_DATA_TYPES(weights, biases);
         ARM_COMPUTE_RETURN_ERROR_ON(biases->dimension(0) != weights->dimension(idx_kernels));
         ARM_COMPUTE_RETURN_ERROR_ON(biases->num_dimensions() > 1);
     }
     if((output != nullptr) && (output->total_size() != 0))
     {
         ARM_COMPUTE_RETURN_ERROR_ON_MISMATCHING_DATA_TYPES(weights, output);
         CLWeightsReshapeKernel::validate(weights, biases, output, num_groups);
     }
     return Status{};
 }
References ARM_COMPUTE_RETURN_ERROR_ON, ARM_COMPUTE_RETURN_ERROR_ON_DATA_TYPE_CHANNEL_NOT_IN, ARM_COMPUTE_RETURN_ERROR_ON_MISMATCHING_DATA_TYPES, ARM_COMPUTE_RETURN_ERROR_ON_NULLPTR, arm_compute::BATCHES, ITensorInfo::data_layout(), ITensorInfo::data_type(), ITensorInfo::dimension(), arm_compute::F16, arm_compute::F32, arm_compute::get_data_layout_dimension_index(), arm_compute::is_data_type_quantized(), ITensorInfo::num_dimensions(), arm_compute::test::validation::num_groups, arm_compute::QASYMM8, arm_compute::QASYMM8_SIGNED, arm_compute::QSYMM8_PER_CHANNEL, ITensorInfo::total_size(), and CLWeightsReshapeKernel::validate().
Referenced by CLConvolutionLayerReshapeWeights::configure(), and CLGEMMConvolutionLayer::validate().
The documentation for this class was generated from the following files:
arm_compute/runtime/CL/functions/CLGEMMConvolutionLayer.h
src/runtime/CL/functions/CLGEMMConvolutionLayer.cpp