Compute Library: GCRuntimeContext Class Reference
GCRuntimeContext Class Reference
Runtime context.
#include <GCRuntimeContext.h>
Public Member Functions
GCRuntimeContext ()
Default Constructor.
~GCRuntimeContext ()=default
Destructor.
GCRuntimeContext (const GCRuntimeContext &)=delete
Prevent instances of this class from being copied (As this class contains pointers)
GCRuntimeContext & operator= (const GCRuntimeContext &)=delete
Prevent instances of this class from being copied (As this class contains pointers)
void set_gpu_scheduler (GCScheduler *scheduler)
CPU Scheduler setter.
GCScheduler * gpu_scheduler ()
GCKernelLibrary & kernel_library ()
GCCoreRuntimeContext * core_runtime_context ()
Public Member Functions inherited from RuntimeContext
RuntimeContext ()
Default Constructor.
~RuntimeContext ()=default
Destructor.
RuntimeContext (const RuntimeContext &)=delete
Prevent instances of this class from being copied (As this class contains pointers)
RuntimeContext (RuntimeContext &&)=default
Default move constructor.
RuntimeContext & operator= (const RuntimeContext &)=delete
Prevent instances of this class from being copied (As this class contains pointers)
RuntimeContext & operator= (RuntimeContext &&)=default
Default move assignment operator.
void set_scheduler (IScheduler *scheduler)
CPU Scheduler setter.
IScheduler * scheduler () override
Scheduler accessor.
IAssetManager * asset_manager () override
Asset manager accessor.
const DeviceProperties & properties () override
Device propertied accessor.
Public Member Functions inherited from IRuntimeContext
virtual ~IRuntimeContext ()=default
Destructor.
Detailed Description
Runtime context.
Definition at line 37 of file GCRuntimeContext.h.
Constructor & Destructor Documentation
GCRuntimeContext() [1/2]
GCRuntimeContext ()
Default Constructor.
Definition at line 32 of file GCRuntimeContext.cpp.
     : _gpu_owned_scheduler(support::cpp14::make_unique<GCScheduler>()),
       _gpu_scheduler(_gpu_owned_scheduler.get()),
       _core_context()
 {
     auto attrs   = create_opengl_display_and_context();
     auto display = std::get<0>(attrs);
     auto ctx     = std::get<1>(attrs);
     _gpu_owned_scheduler->default_init_with_context(display, ctx);
     _kernel_lib.init("./cs_shaders/", display, ctx);
     _core_context = GCCoreRuntimeContext(&_kernel_lib);
 }
References arm_compute::create_opengl_display_and_context(), and GCKernelLibrary::init().
~GCRuntimeContext()
~GCRuntimeContext () default
Destructor.
GCRuntimeContext() [2/2]
GCRuntimeContext (const GCRuntimeContext &) delete
Prevent instances of this class from being copied (As this class contains pointers)
Member Function Documentation
core_runtime_context()
GCCoreRuntimeContext * core_runtime_context ()
Definition at line 52 of file GCRuntimeContext.cpp.
 {
     return &_core_context;
 }
gpu_scheduler()
GCScheduler * gpu_scheduler ()
Definition at line 63 of file GCRuntimeContext.cpp.
 {
     return _gpu_scheduler;
 }
Referenced by IGCSimpleFunction::run().
kernel_library()
GCKernelLibrary & kernel_library ()
Definition at line 47 of file GCRuntimeContext.cpp.
 {
     return _kernel_lib;
 }
operator=()
GCRuntimeContext& operator= (const GCRuntimeContext &) delete
Prevent instances of this class from being copied (As this class contains pointers)
set_gpu_scheduler()
void set_gpu_scheduler (GCScheduler * scheduler)
CPU Scheduler setter.
Definition at line 57 of file GCRuntimeContext.cpp.
 {
     ARM_COMPUTE_ERROR_ON_NULLPTR(scheduler);
     _gpu_scheduler = scheduler;
 }
References ARM_COMPUTE_ERROR_ON_NULLPTR, and RuntimeContext::scheduler().
The documentation for this class was generated from the following files:
arm_compute/runtime/GLES_COMPUTE/GCRuntimeContext.h
src/runtime/GLES_COMPUTE/GCRuntimeContext.cpp