Compute Library: NEGEMMConv2d Class Reference
NEGEMMConv2d Class Reference
Basic function to compute the convolution layer.
#include <NEGEMMConv2d.h>
Public Member Functions
NEGEMMConv2d (const std::shared_ptr< IMemoryManager > &memory_manager=nullptr)
Constructor.
NEGEMMConv2d (const NEGEMMConv2d &)=delete
Prevent instances of this class from being copied (As this class contains pointers)
NEGEMMConv2d (NEGEMMConv2d &&)=default
Default move constructor.
NEGEMMConv2d & operator= (const NEGEMMConv2d &)=delete
Prevent instances of this class from being copied (As this class contains pointers)
NEGEMMConv2d & operator= (NEGEMMConv2d &&)=default
Default move assignment operator.
void configure (ITensor *input, const ITensor *weights, const ITensor *biases, ITensor *output, const Conv2dInfo &info)
Set the input and output tensors.
void run () override
Run the kernels contained in the function.
void prepare () override
Prepare the function for executing.
Public Member Functions inherited from IFunction
virtual ~IFunction ()=default
Destructor.
Static Public Member Functions
static Status validate (const ITensorInfo *input, const ITensorInfo *weights, const ITensorInfo *biases, const ITensorInfo *output, const Conv2dInfo &info)
Static function to check if given info will lead to a valid configuration of NEGEMMConv2d.
Detailed Description
Basic function to compute the convolution layer.
This function calls the following NEON kernels/functions:
Supports only NHWC data layout
NEGEMMAssemblyDispatch
NEActivationLayer, in case activation cannot be fused in the assembly dispatch
Weights are transformed from OHWI to HWIO format using the following kernels:
NEPermute
Definition at line 50 of file NEGEMMConv2d.h.
Constructor & Destructor Documentation
NEGEMMConv2d() [1/3]
NEGEMMConv2d (const std::shared_ptr< IMemoryManager > & memory_manager = nullptr)
Constructor.
Definition at line 81 of file NEGEMMConv2d.cpp.
     : _gemm_asm_func(memory_manager), _activation_func(), _weights_permute_func(), _original_weights(nullptr), _permuted_weights(), _is_prepared(false), _run_activation(false)
 {
 }
NEGEMMConv2d() [2/3]
NEGEMMConv2d (const NEGEMMConv2d &) delete
Prevent instances of this class from being copied (As this class contains pointers)
NEGEMMConv2d() [3/3]
NEGEMMConv2d (NEGEMMConv2d &&) default
Default move constructor.
Member Function Documentation
configure()
void configure (ITensor * input, const ITensor * weights, const ITensor * biases, ITensor * output, const Conv2dInfo & info)
Set the input and output tensors.
Parameters
[in] input Source tensor. 3 lower dimensions represent a single input [width, height, IFM], while every optional dimension from 4 and above represent a batch of inputs. Data types supported: QASYMM8/QASYMM8_SIGNED/BFLOAT16/F16/F32.
[in] weights Weights tensor. Weights are 4D tensor with dimensions [kernel_x, kernel_y, IFM, OFM]. Data type supported: QASYMM8/QASYMM8_SIGNED/QSYMM8_PER_CHANNEL/BFLOAT16/F16/F32.
[in] biases Biases tensor. Shared biases supported. Biases are 1D tensor with dimensions [OFM]. Data type supported: Should match input data type, except for input of QASYMM8/QASYMM8_SIGNED type where biases should be of S32 type.
[out] output Destination tensor. 3 lower dimensions represent a single output [width, height, OFM], while the rest represent batch of outputs. Data types supported: Same as input.
[in] info Convolution layer descriptor
Definition at line 85 of file NEGEMMConv2d.cpp.
 {
     ARM_COMPUTE_ERROR_ON_NULLPTR(input, weights, output);
     ARM_COMPUTE_ERROR_THROW_ON(NEGEMMConv2d::validate(input->info(),
                                                       weights->info(),
                                                       biases != nullptr ? biases->info() : nullptr,
                                                       output->info(),
                                                       info));
     _original_weights = weights;
     _weights_permute_func.configure(weights, &_permuted_weights, PermutationVector{ 3, 0, 1, 2 });
     // Configure assembly dispatch
     AsmGemmInfo asm_info = init_assembly_metadata(info, false);
     if(is_data_type_quantized(input->info()->data_type()))
     {
         asm_info.output_stage = calculate_output_stage_metadata(input->info(), weights->info(), output->info(), info.act_info);
     }
     _gemm_asm_func.configure(input, &_permuted_weights, biases, output, asm_info);
     // Configure activation
     if(info.act_info.enabled() && !_gemm_asm_func.is_activation_supported(info.act_info))
     {
         _activation_func.configure(output, nullptr, info.act_info);
         _run_activation = true;
     }
 }
References ARM_COMPUTE_ERROR_ON_NULLPTR, ARM_COMPUTE_ERROR_THROW_ON, NEPermute::configure(), NEActivationLayer::configure(), NEGEMMAssemblyDispatch::configure(), ITensor::info(), arm_compute::test::validation::info, arm_compute::test::validation::input, NEGEMMAssemblyDispatch::is_activation_supported(), arm_compute::is_data_type_quantized(), AsmGemmInfo::output_stage, and NEGEMMConv2d::validate().
Referenced by arm_compute::test::validation::detail::configure_conv_function< NEGEMMConv2d, Tensor >().
operator=() [1/2]
NEGEMMConv2d& operator= (const NEGEMMConv2d &) delete
Prevent instances of this class from being copied (As this class contains pointers)
operator=() [2/2]
NEGEMMConv2d& operator= (NEGEMMConv2d &&) default
Default move assignment operator.
prepare()
void prepare () override virtual
Prepare the function for executing.
Any one off pre-processing step required by the function is handled here
Note
Prepare stage might not need all the function's buffers' backing memory to be available in order to execute
Reimplemented from IFunction.
Definition at line 157 of file NEGEMMConv2d.cpp.
 {
     if(!_is_prepared)
     {
         _permuted_weights.allocator()->allocate();
         _weights_permute_func.run();
         _original_weights->mark_as_unused();
         _is_prepared = true;
     }
 }
References TensorAllocator::allocate(), Tensor::allocator(), ITensor::mark_as_unused(), and INESimpleFunctionNoBorder::run().
Referenced by NEGEMMConv2d::run().
run()
void run () override virtual
Run the kernels contained in the function.
For NEON kernels:
Multi-threading is used for the kernels which are parallelisable.
By default std::thread::hardware_concurrency() threads are used.
Note
CPPScheduler::set_num_threads() can be used to manually set the number of threads
For OpenCL kernels:
All the kernels are enqueued on the queue associated with CLScheduler.
The queue is then flushed.
Note
The function will not block until the kernels are executed. It is the user's responsibility to wait.
Will call prepare() on first run if hasn't been done
Implements IFunction.
Definition at line 147 of file NEGEMMConv2d.cpp.
 {
     prepare();
     _gemm_asm_func.run();
     if(_run_activation)
     {
         _activation_func.run();
     }
 }
References NEGEMMConv2d::prepare(), NEActivationLayer::run(), and NEGEMMAssemblyDispatch::run().
validate()
Status validate (const ITensorInfo * input, const ITensorInfo * weights, const ITensorInfo * biases, const ITensorInfo * output, const Conv2dInfo & info) static
Static function to check if given info will lead to a valid configuration of NEGEMMConv2d.
Parameters
[in] input Source tensor info. 3 lower dimensions represent a single input [width, height, IFM], while every optional dimension from 4 and above represent a batch of inputs. Data types supported: QASYMM8/QASYMM8_SIGNED/BFLOAT16/F16/F32.
[in] weights Weights tensor info. Weights are 4D tensor with dimensions [kernel_x, kernel_y, IFM, OFM]. Data type supported: QASYMM8/QASYMM8_SIGNED/QSYMM8_PER_CHANNEL/BFLOAT16/F16/F32.
[in] biases Biases tensor info. Shared biases supported. Biases are 1D tensor with dimensions [OFM]. Data type supported: Should match input data type, except for input of QASYMM8/QASYMM8_SIGNED type where biases should be of S32 type.
[in] output Destination tensor info. 3 lower dimensions represent a single output [width, height, OFM], while the rest represent batch of outputs. Data types supported: Same as input.
[in] info Contains padding and stride information described in PadStrideInfo.
Returns
a status
Definition at line 111 of file NEGEMMConv2d.cpp.
 {
     ARM_COMPUTE_RETURN_ERROR_ON_NULLPTR(input, weights, output);
     ARM_COMPUTE_RETURN_ERROR_ON_DATA_TYPE_CHANNEL_NOT_IN(input, 1, DataType::QASYMM8, DataType::QASYMM8_SIGNED, DataType::BFLOAT16, DataType::F16, DataType::F32);
     ARM_COMPUTE_RETURN_ERROR_ON_DATA_TYPE_CHANNEL_NOT_IN(weights, 1, DataType::QASYMM8, DataType::QASYMM8_SIGNED, DataType::QSYMM8_PER_CHANNEL, DataType::BFLOAT16, DataType::F16, DataType::F32);
     ARM_COMPUTE_RETURN_ERROR_ON_MISMATCHING_DATA_LAYOUT(input, weights);
     ARM_COMPUTE_RETURN_ERROR_ON_MSG(info.num_groups > 1, "Grouping (num_groups != 1) is not supported on NEON");
     ARM_COMPUTE_RETURN_ERROR_ON_MSG(input->data_layout() != DataLayout::NHWC, "Data layout supported is NHWC");
     const DataType    data_type = input->data_type();
     const TensorShape i_shape   = input->tensor_shape();
     const TensorShape w_shape   = weights->tensor_shape();
     ARM_COMPUTE_RETURN_ERROR_ON(w_shape[0] != i_shape[0]);
     ARM_COMPUTE_RETURN_ERROR_ON(weights->num_dimensions() > 4);
     // Validate biases
     if(biases != nullptr)
     {
         if(is_data_type_quantized_asymmetric(data_type))
         {
             ARM_COMPUTE_RETURN_ERROR_ON_DATA_TYPE_CHANNEL_NOT_IN(biases, 1, DataType::S32);
         }
         else if(data_type == DataType::BFLOAT16)
         {
             ARM_COMPUTE_RETURN_ERROR_ON_DATA_TYPE_CHANNEL_NOT_IN(biases, 1, DataType::F32);
         }
         else
         {
             ARM_COMPUTE_RETURN_ERROR_ON_MISMATCHING_DATA_TYPES(input, biases);
         }
         ARM_COMPUTE_RETURN_ERROR_ON(biases->dimension(0) != weights->dimension(3));
         ARM_COMPUTE_RETURN_ERROR_ON(biases->num_dimensions() > 1);
     }
     AsmGemmInfo asm_info = init_assembly_metadata(info, false);
     ARM_COMPUTE_RETURN_ON_ERROR(NEGEMMAssemblyDispatch::validate(input, weights, biases, output, asm_info));
     return Status{};
 }
References ARM_COMPUTE_RETURN_ERROR_ON, ARM_COMPUTE_RETURN_ERROR_ON_DATA_TYPE_CHANNEL_NOT_IN, ARM_COMPUTE_RETURN_ERROR_ON_MISMATCHING_DATA_LAYOUT, ARM_COMPUTE_RETURN_ERROR_ON_MISMATCHING_DATA_TYPES, ARM_COMPUTE_RETURN_ERROR_ON_MSG, ARM_COMPUTE_RETURN_ERROR_ON_NULLPTR, ARM_COMPUTE_RETURN_ON_ERROR, arm_compute::BFLOAT16, arm_compute::test::validation::data_type, ITensorInfo::dimension(), arm_compute::F16, arm_compute::F32, arm_compute::test::validation::info, arm_compute::test::validation::input, arm_compute::is_data_type_quantized_asymmetric(), arm_compute::NHWC, ITensorInfo::num_dimensions(), arm_compute::QASYMM8, arm_compute::QASYMM8_SIGNED, arm_compute::QSYMM8_PER_CHANNEL, arm_compute::S32, ITensorInfo::tensor_shape(), and NEGEMMAssemblyDispatch::validate().
Referenced by NEGEMMConv2d::configure(), NEConvolutionLayer::get_convolution_method(), and NEConvolutionLayer::validate().
The documentation for this class was generated from the following files:
arm_compute/runtime/NEON/functions/NEGEMMConv2d.h
src/runtime/NEON/functions/NEGEMMConv2d.cpp