Compute Library: NEElementwiseUnaryKernel Class Reference
NEElementwiseUnaryKernel Class Reference
Interface for an element-wise unary operation kernel.
#include <NEElementwiseUnaryKernel.h>
Public Member Functions
const char * name () const override
Name of the kernel.
NEElementwiseUnaryKernel ()
Default constructor.
NEElementwiseUnaryKernel (const NEElementwiseUnaryKernel &)=delete
Prevent instances of this class from being copied (As this class contains pointers)
NEElementwiseUnaryKernel & operator= (const NEElementwiseUnaryKernel &)=delete
Prevent instances of this class from being copied (As this class contains pointers)
NEElementwiseUnaryKernel (NEElementwiseUnaryKernel &&)=default
Allow instances of this class to be moved.
NEElementwiseUnaryKernel & operator= (NEElementwiseUnaryKernel &&)=default
Allow instances of this class to be moved.
~NEElementwiseUnaryKernel ()=default
Default destructor.
void configure (ElementWiseUnary op, const ITensor *input, ITensor *output)
Function to configure the NEElementwiseUnaryKernel.
void run (const Window &window, const ThreadInfo &info) override
Execute the kernel on the passed window.
Public Member Functions inherited from ICPPKernel
virtual ~ICPPKernel ()=default
Default destructor.
virtual void run_nd (const Window &window, const ThreadInfo &info, const Window &thread_locator)
legacy compatibility layer for implemantions which do not support thread_locator In these cases we simply narrow the interface down the legacy version
virtual void run_op (ITensorPack &tensors, const Window &window, const ThreadInfo &info)
Execute the kernel on the passed window.
Public Member Functions inherited from IKernel
IKernel ()
Constructor.
virtual ~IKernel ()=default
Destructor.
virtual bool is_parallelisable () const
Indicates whether or not the kernel is parallelisable.
virtual BorderSize border_size () const
The size of the border for that kernel.
const Window & window () const
The maximum window the kernel can be executed on.
Static Public Member Functions
static Status validate (ElementWiseUnary op, const ITensorInfo *input, const ITensorInfo *output)
Static function to check if given info will lead to a valid configuration of NEElementwiseUnaryKernel.
Detailed Description
Interface for an element-wise unary operation kernel.
Element-wise operation is computed by:
\[ output(x) = OP(input(x))\]
Definition at line 40 of file NEElementwiseUnaryKernel.h.
Constructor & Destructor Documentation
NEElementwiseUnaryKernel() [1/3]
NEElementwiseUnaryKernel ()
Default constructor.
Definition at line 120 of file NEElementwiseUnaryKernel.cpp.
     : _func(nullptr), _input(nullptr), _output(nullptr), _op()
 {
 }
NEElementwiseUnaryKernel() [2/3]
NEElementwiseUnaryKernel (const NEElementwiseUnaryKernel &) delete
Prevent instances of this class from being copied (As this class contains pointers)
NEElementwiseUnaryKernel() [3/3]
NEElementwiseUnaryKernel (NEElementwiseUnaryKernel &&) default
Allow instances of this class to be moved.
~NEElementwiseUnaryKernel()
~NEElementwiseUnaryKernel () default
Default destructor.
Member Function Documentation
configure()
void configure (ElementWiseUnary op, const ITensor * input, ITensor * output)
Function to configure the NEElementwiseUnaryKernel.
Parameters
[in] op Arithmetic operation to be executed.
[in] input First tensor input. Data types supported: F16/F32, F16/F32/S32 for NEG/ABS operations.
[out] output Output tensor. Data types supported: Same as input.
Definition at line 125 of file NEElementwiseUnaryKernel.cpp.
 {
     ARM_COMPUTE_ERROR_THROW_ON(validate(op, input->info(), output->info()));
     ARM_COMPUTE_ERROR_ON_NULLPTR(input, output);
     // Configure kernel window
     const std::pair<TensorShape, ValidRegion> broadcast_pair = ITensorInfo::broadcast_shape_and_valid_region(*input->info());
     const TensorShape &out_shape    = broadcast_pair.first;
     const ValidRegion &valid_region = broadcast_pair.second;
     // Auto initialize output if not initialized
     auto_init_if_empty(*output->info(), out_shape, 1, input->info()->data_type());
     Window win = calculate_max_window(valid_region);
     _input  = input;
     _output = output;
     _op     = op;
     INEKernel::configure(win);
     switch(input->info()->data_type())
     {
         case DataType::F32:
             _func = &NEElementwiseUnaryKernel::elementwise_op<float>;
             break;
 #ifdef __ARM_FEATURE_FP16_VECTOR_ARITHMETIC
         case DataType::F16:
             _func = &NEElementwiseUnaryKernel::elementwise_op<float16_t>;
 #endif /* __ARM_FEATURE_FP16_VECTOR_ARITHMETIC */
             break;
         case DataType::S32:
             _func = &NEElementwiseUnaryKernel::elementwise_op<int32_t>;
             break;
         default:
             ARM_COMPUTE_ERROR("DataType not supported");
     }
 }
References ARM_COMPUTE_ERROR, ARM_COMPUTE_ERROR_ON_NULLPTR, ARM_COMPUTE_ERROR_THROW_ON, arm_compute::auto_init_if_empty(), ITensorInfo::broadcast_shape_and_valid_region(), arm_compute::calculate_max_window(), arm_compute::F16, arm_compute::F32, ITensor::info(), arm_compute::test::validation::input, arm_compute::S32, arm_compute::test::validation::valid_region, and NEElementwiseUnaryKernel::validate().
name()
const char* name () const inline override virtual
Name of the kernel.
Returns
Kernel name
Implements ICPPKernel.
Definition at line 43 of file NEElementwiseUnaryKernel.h.
     {
         return "NEElementwiseUnaryKernel";
     }
operator=() [1/2]
NEElementwiseUnaryKernel& operator= (const NEElementwiseUnaryKernel &) delete
Prevent instances of this class from being copied (As this class contains pointers)
operator=() [2/2]
NEElementwiseUnaryKernel& operator= (NEElementwiseUnaryKernel &&) default
Allow instances of this class to be moved.
run()
void run (const Window & window, const ThreadInfo & info) override virtual
Execute the kernel on the passed window.
Warning
If is_parallelisable() returns false then the passed window must be equal to window()
Note
The window has to be a region within the window returned by the window() method
The width of the window has to be a multiple of num_elems_processed_per_iteration().
Parameters
[in] window Region on which to execute the kernel. (Must be a region of the window returned by window())
[in] info Info about executing thread and CPU.
Reimplemented from ICPPKernel.
Definition at line 193 of file NEElementwiseUnaryKernel.cpp.
 {
     ARM_COMPUTE_UNUSED(info);
     ARM_COMPUTE_ERROR_ON_UNCONFIGURED_KERNEL(this);
     ARM_COMPUTE_ERROR_ON_INVALID_SUBWINDOW(INEKernel::window(), window);
     ARM_COMPUTE_ERROR_ON(_func == nullptr);
     (this->*_func)(window);
 }
References ARM_COMPUTE_ERROR_ON, ARM_COMPUTE_ERROR_ON_INVALID_SUBWINDOW, ARM_COMPUTE_ERROR_ON_UNCONFIGURED_KERNEL, ARM_COMPUTE_UNUSED, arm_compute::test::validation::info, and IKernel::window().
validate()
Status validate (ElementWiseUnary op, const ITensorInfo * input, const ITensorInfo * output) static
Static function to check if given info will lead to a valid configuration of NEElementwiseUnaryKernel.
Parameters
[in] op Arithmetic operation to be executed.
[in] input First tensor input info. Data types supported: F16/F32, F16/F32/S32 for NEG/ABS operations.
[in] output Output tensor info. Data types supported: Same as input.
Returns
a Status
Definition at line 164 of file NEElementwiseUnaryKernel.cpp.
 {
     ARM_COMPUTE_RETURN_ERROR_ON_NULLPTR(input, output);
     ARM_COMPUTE_RETURN_ERROR_ON_CPU_F16_UNSUPPORTED(input);
     switch(op)
     {
         case ElementWiseUnary::EXP:
         case ElementWiseUnary::RSQRT:
         case ElementWiseUnary::LOG:
         case ElementWiseUnary::ROUND:
         case ElementWiseUnary::SIN:
             ARM_COMPUTE_RETURN_ERROR_ON_DATA_TYPE_CHANNEL_NOT_IN(input, 1, DataType::F16, DataType::F32);
             break;
         case ElementWiseUnary::NEG:
         case ElementWiseUnary::ABS:
             ARM_COMPUTE_RETURN_ERROR_ON_DATA_TYPE_CHANNEL_NOT_IN(input, 1, DataType::F16, DataType::F32, DataType::S32);
             break;
         default:
             ARM_COMPUTE_ERROR("ElementWiseUnary operation not supported");
     }
     // Validate in case of configured output
     if(output->total_size() > 0)
     {
         ARM_COMPUTE_RETURN_ERROR_ON_MISMATCHING_DATA_TYPES(input, output);
     }
     return Status{};
 }
References arm_compute::ABS, ARM_COMPUTE_ERROR, ARM_COMPUTE_RETURN_ERROR_ON_CPU_F16_UNSUPPORTED, ARM_COMPUTE_RETURN_ERROR_ON_DATA_TYPE_CHANNEL_NOT_IN, ARM_COMPUTE_RETURN_ERROR_ON_MISMATCHING_DATA_TYPES, ARM_COMPUTE_RETURN_ERROR_ON_NULLPTR, arm_compute::EXP, arm_compute::F16, arm_compute::F32, arm_compute::test::validation::input, arm_compute::LOG, arm_compute::NEG, arm_compute::ROUND, arm_compute::RSQRT, arm_compute::S32, arm_compute::SIN, and ITensorInfo::total_size().
Referenced by NEElementwiseUnaryKernel::configure(), NERsqrtLayer::validate(), NEExpLayer::validate(), NENegLayer::validate(), NELogLayer::validate(), NEAbsLayer::validate(), NERoundLayer::validate(), and NESinLayer::validate().
The documentation for this class was generated from the following files:
src/core/NEON/kernels/NEElementwiseUnaryKernel.h
src/core/NEON/kernels/NEElementwiseUnaryKernel.cpp