Compute Library: NECopyKernel Class Reference
NECopyKernel Class Reference
NEON kernel to perform a copy between two tensors.
#include <NECopyKernel.h>
Public Member Functions
const char * name () const override
Name of the kernel.
NECopyKernel ()
Default constructor.
NECopyKernel (const NECopyKernel &)=delete
Prevent instances of this class from being copied (As this class contains pointers).
NECopyKernel & operator= (const NECopyKernel &)=delete
Prevent instances of this class from being copied (As this class contains pointers).
NECopyKernel (NECopyKernel &&)=default
Allow instances of this class to be moved.
NECopyKernel & operator= (NECopyKernel &&)=default
Allow instances of this class to be moved.
~NECopyKernel ()=default
Default destructor.
void configure (const ITensor *input, ITensor *output, const PaddingList &padding=PaddingList())
Initialize the kernel's input, output.
void run (const Window &window, const ThreadInfo &info) override
Execute the kernel on the passed window.
Public Member Functions inherited from ICPPKernel
virtual ~ICPPKernel ()=default
Default destructor.
virtual void run_nd (const Window &window, const ThreadInfo &info, const Window &thread_locator)
legacy compatibility layer for implemantions which do not support thread_locator In these cases we simply narrow the interface down the legacy version
virtual void run_op (ITensorPack &tensors, const Window &window, const ThreadInfo &info)
Execute the kernel on the passed window.
Public Member Functions inherited from IKernel
IKernel ()
Constructor.
virtual ~IKernel ()=default
Destructor.
virtual bool is_parallelisable () const
Indicates whether or not the kernel is parallelisable.
virtual BorderSize border_size () const
The size of the border for that kernel.
const Window & window () const
The maximum window the kernel can be executed on.
Static Public Member Functions
static Status validate (const ITensorInfo *input, const ITensorInfo *output, const PaddingList &padding=PaddingList())
Static function to check if given info will lead to a valid configuration of NECopyKernel.
Detailed Description
NEON kernel to perform a copy between two tensors.
Definition at line 35 of file NECopyKernel.h.
Constructor & Destructor Documentation
NECopyKernel() [1/3]
NECopyKernel ()
Default constructor.
Definition at line 75 of file NECopyKernel.cpp.
     : _input(nullptr), _output(nullptr), _padding()
 {
 }
NECopyKernel() [2/3]
NECopyKernel (const NECopyKernel &) delete
Prevent instances of this class from being copied (As this class contains pointers).
NECopyKernel() [3/3]
NECopyKernel (NECopyKernel &&) default
Allow instances of this class to be moved.
~NECopyKernel()
~NECopyKernel () default
Default destructor.
Member Function Documentation
configure()
void configure (const ITensor * input, ITensor * output, const PaddingList & padding = PaddingList())
Initialize the kernel's input, output.
Parameters
[in] input Source tensor. Data types supported: All
[out] output Destination tensor. Data types supported: same as input.
[in] padding (Optional) Padding to be applied to the input tensor
Definition at line 80 of file NECopyKernel.cpp.
 {
     ARM_COMPUTE_ERROR_ON_NULLPTR(input, output);
     ARM_COMPUTE_ERROR_THROW_ON(validate_arguments(input->info(), output->info(), padding));
     _input   = input;
     _output  = output;
     _padding = padding;
     std::pair<Status, Window> win_config;
     if(padding.empty())
     {
         win_config = validate_and_configure_window(input->info(), output->info());
     }
     else
     {
         win_config = validate_and_configure_window_with_padding(input->info(), output->info(), padding);
     }
     ARM_COMPUTE_ERROR_THROW_ON(win_config.first);
     INEKernel::configure(win_config.second);
 }
References ARM_COMPUTE_ERROR_ON_NULLPTR, ARM_COMPUTE_ERROR_THROW_ON, ITensor::info(), arm_compute::test::validation::input, and arm_compute::validate_arguments().
name()
const char* name () const inline override virtual
Name of the kernel.
Returns
Kernel name
Implements ICPPKernel.
Definition at line 38 of file NECopyKernel.h.
     {
         return "NECopyKernel";
     }
operator=() [1/2]
NECopyKernel& operator= (const NECopyKernel &) delete
Prevent instances of this class from being copied (As this class contains pointers).
operator=() [2/2]
NECopyKernel& operator= (NECopyKernel &&) default
Allow instances of this class to be moved.
run()
void run (const Window & window, const ThreadInfo & info) override virtual
Execute the kernel on the passed window.
Warning
If is_parallelisable() returns false then the passed window must be equal to window()
Note
The window has to be a region within the window returned by the window() method
The width of the window has to be a multiple of num_elems_processed_per_iteration().
Parameters
[in] window Region on which to execute the kernel. (Must be a region of the window returned by window())
[in] info Info about executing thread and CPU.
Reimplemented from ICPPKernel.
Definition at line 120 of file NECopyKernel.cpp.
 {
     ARM_COMPUTE_UNUSED(info);
     ARM_COMPUTE_ERROR_ON_UNCONFIGURED_KERNEL(this);
     ARM_COMPUTE_ERROR_ON_INVALID_SUBWINDOW(INEKernel::window(), window);
     if(_padding.empty())
     {
         Window output_window{ window };
         output_window.set(Window::DimX, Window::Dimension(output_window.x().start(), output_window.x().end(), _input->info()->dimension(0)));
         Window out_slice = output_window.first_slice_window_1D();
         do
         {
             Iterator input_it(_input, out_slice);
             Iterator output_it(_output, out_slice);
             execute_window_loop(out_slice, [&](const Coordinates &)
             {
                 memcpy(output_it.ptr(), input_it.ptr(), _output->info()->dimension(0) * _output->info()->element_size());
             },
             input_it, output_it);
         }
         while(output_window.slide_window_slice_1D(out_slice));
     }
     else
     {
         Window input_window{ window };
         input_window.set(Window::DimX, Window::Dimension(0, window.x().end() - _padding[0].first, _input->info()->dimension(0)));
         Iterator     input_it(_input, input_window);
         Iterator     output_it(_output, window);
         const size_t row_size_in_bytes = _input->info()->dimension(0) * _input->info()->element_size();
         execute_window_loop(window, [&](const Coordinates &)
         {
             auto dst_ptr = output_it.ptr() + _padding[0].first * _output->info()->element_size();
             std::memcpy(dst_ptr, input_it.ptr(), row_size_in_bytes);
         },
         input_it, output_it);
     }
 }
References ARM_COMPUTE_ERROR_ON_INVALID_SUBWINDOW, ARM_COMPUTE_ERROR_ON_UNCONFIGURED_KERNEL, ARM_COMPUTE_UNUSED, ITensorInfo::dimension(), Window::DimX, ITensorInfo::element_size(), Window::Dimension::end(), arm_compute::execute_window_loop(), Window::first_slice_window_1D(), ITensor::info(), arm_compute::test::validation::info, Iterator::ptr(), Window::set(), IKernel::window(), and Window::x().
validate()
Status validate (const ITensorInfo * input, const ITensorInfo * output, const PaddingList & padding = PaddingList()) static
Static function to check if given info will lead to a valid configuration of NECopyKernel.
Parameters
[in] input Source tensor. Data types supported: All
[in] output Destination tensor. Data types supported: same as input.
[in] padding (Optional) Padding to be applied to the input tensor
Returns
a status
Definition at line 104 of file NECopyKernel.cpp.
 {
     ARM_COMPUTE_RETURN_ON_ERROR(validate_arguments(input, output, padding));
     if(padding.empty())
     {
         ARM_COMPUTE_RETURN_ON_ERROR(validate_and_configure_window(input->clone().get(), output->clone().get()).first);
     }
     else
     {
         ARM_COMPUTE_RETURN_ON_ERROR(validate_and_configure_window_with_padding(input->clone().get(), output->clone().get(), padding).first);
     }
     return Status{};
 }
References ARM_COMPUTE_RETURN_ON_ERROR, ICloneable< T >::clone(), arm_compute::test::validation::input, and arm_compute::validate_arguments().
Referenced by NECopy::validate().
The documentation for this class was generated from the following files:
src/core/NEON/kernels/NECopyKernel.h
src/core/NEON/kernels/NECopyKernel.cpp