Compute Library: NEComplexPixelWiseMultiplicationKernel Class Reference
NEComplexPixelWiseMultiplicationKernel Class Reference
Interface for the complex pixelwise multiplication kernel.
#include <NEPixelWiseMultiplicationKernel.h>
Public Member Functions
const char * name () const override
Name of the kernel.
void configure (ITensorInfo *input1, ITensorInfo *input2, ITensorInfo *output)
Initialise the kernel's input, output and border mode.
void run_op (ITensorPack &tensors, const Window &window, const ThreadInfo &info) override
Execute the kernel on the passed window.
Public Member Functions inherited from ICPPKernel
virtual ~ICPPKernel ()=default
Default destructor.
virtual void run (const Window &window, const ThreadInfo &info)
Execute the kernel on the passed window.
virtual void run_nd (const Window &window, const ThreadInfo &info, const Window &thread_locator)
legacy compatibility layer for implemantions which do not support thread_locator In these cases we simply narrow the interface down the legacy version
Public Member Functions inherited from IKernel
IKernel ()
Constructor.
virtual ~IKernel ()=default
Destructor.
virtual bool is_parallelisable () const
Indicates whether or not the kernel is parallelisable.
virtual BorderSize border_size () const
The size of the border for that kernel.
const Window & window () const
The maximum window the kernel can be executed on.
Static Public Member Functions
static Status validate (const ITensorInfo *input1, const ITensorInfo *input2, const ITensorInfo *output)
Static function to check if given info will lead to a valid configuration of NEComplexPixelWiseMultiplicationKernel.
Detailed Description
Interface for the complex pixelwise multiplication kernel.
Definition at line 157 of file NEPixelWiseMultiplicationKernel.h.
Member Function Documentation
configure()
void configure (ITensorInfo * input1, ITensorInfo * input2, ITensorInfo * output)
Initialise the kernel's input, output and border mode.
Parameters
[in] input1 An input tensor. Data types supported: F32. Number of channels supported: 2 (complex tensor).
[in] input2 An input tensor. Data types supported: same as input1. Number of channels supported: same as input1.
[out] output The output tensor, Data types supported: same as input1. Number of channels supported: same as input1.
Definition at line 1636 of file NEPixelWiseMultiplicationKernel.cpp.
 {
     ARM_COMPUTE_ERROR_ON_NULLPTR(input1, input2, output);
     ARM_COMPUTE_ERROR_THROW_ON(validate_arguments_complex(input1, input2, output));
     const std::pair<TensorShape, ValidRegion> broadcast_pair = ITensorInfo::broadcast_shape_and_valid_region(*input1, *input2);
     const TensorShape &out_shape    = broadcast_pair.first;
     const ValidRegion &valid_region = broadcast_pair.second;
     // Auto initialize output if not initialized
     const TensorInfo out_info(out_shape, input1->num_channels(), input1->data_type());
     auto_init_if_empty(*output, out_info);
     // Configure kernel window
     Coordinates coord;
     coord.set_num_dimensions(output->num_dimensions());
     output->set_valid_region(valid_region);
     Window win = calculate_max_window(valid_region, Steps());
     INEKernel::configure(win);
 }
References ARM_COMPUTE_ERROR_ON_NULLPTR, ARM_COMPUTE_ERROR_THROW_ON, arm_compute::auto_init_if_empty(), ITensorInfo::broadcast_shape_and_valid_region(), arm_compute::calculate_max_window(), ITensorInfo::data_type(), ITensorInfo::num_channels(), ITensorInfo::num_dimensions(), Dimensions< T >::set_num_dimensions(), ITensorInfo::set_valid_region(), and arm_compute::test::validation::valid_region.
name()
const char* name () const inline override virtual
Name of the kernel.
Returns
Kernel name
Implements ICPPKernel.
Definition at line 160 of file NEPixelWiseMultiplicationKernel.h.
     {
         return "NEComplexPixelWiseMultiplicationKernel";
     }
run_op()
void run_op (ITensorPack & tensors, const Window & window, const ThreadInfo & info) override virtual
Execute the kernel on the passed window.
Warning
If is_parallelisable() returns false then the passed window must be equal to window()
Note
The window has to be a region within the window returned by the window() method
The width of the window has to be a multiple of num_elems_processed_per_iteration().
Parameters
[in] tensors A vector containing the tensors to operate on.
[in] window Region on which to execute the kernel. (Must be a region of the window returned by window())
[in] info Info about executing thread and CPU.
Reimplemented from ICPPKernel.
Definition at line 1666 of file NEPixelWiseMultiplicationKernel.cpp.
 {
     ARM_COMPUTE_UNUSED(info);
     ARM_COMPUTE_ERROR_ON_UNCONFIGURED_KERNEL(this);
     ARM_COMPUTE_ERROR_ON_INVALID_SUBWINDOW(INEKernel::window(), window);
     auto input1 = tensors.get_const_tensor(TensorType::ACL_SRC_0);
     auto input2 = tensors.get_const_tensor(TensorType::ACL_SRC_1);
     auto output = tensors.get_tensor(TensorType::ACL_DST);
     c_mul_F32_F32_F32_n(input1, input2, output, window);
 }
References arm_compute::ACL_DST, arm_compute::ACL_SRC_0, arm_compute::ACL_SRC_1, ARM_COMPUTE_ERROR_ON_INVALID_SUBWINDOW, ARM_COMPUTE_ERROR_ON_UNCONFIGURED_KERNEL, ARM_COMPUTE_UNUSED, ITensorPack::get_const_tensor(), ITensorPack::get_tensor(), arm_compute::test::validation::info, and IKernel::window().
validate()
Status validate (const ITensorInfo * input1, const ITensorInfo * input2, const ITensorInfo * output) static
Static function to check if given info will lead to a valid configuration of NEComplexPixelWiseMultiplicationKernel.
Parameters
[in] input1 An input tensor info. Data types supported: F32. Number of channels supported: 2 (complex tensor).
[in] input2 An input tensor info. Data types supported: same as input1. Number of channels supported: same as input1.
[in] output The output tensor info. Data types supported: same as input1. Number of channels supported: same as input1.
Returns
a status
Definition at line 1658 of file NEPixelWiseMultiplicationKernel.cpp.
 {
     ARM_COMPUTE_ERROR_ON_NULLPTR(input1, input2, output);
     ARM_COMPUTE_RETURN_ON_ERROR(validate_arguments_complex(input1, input2, output));
     return Status{};
 }
References ARM_COMPUTE_ERROR_ON_NULLPTR, and ARM_COMPUTE_RETURN_ON_ERROR.
Referenced by NEComplexPixelWiseMultiplication::validate().
The documentation for this class was generated from the following files:
src/core/NEON/kernels/NEPixelWiseMultiplicationKernel.h
src/core/NEON/kernels/NEPixelWiseMultiplicationKernel.cpp