Compute Library: arm_compute::cl_gemm Namespace Reference
arm_compute::cl_gemm Namespace Reference
Data Structures
class CLGEMMKernelSelectionBifrost
Bifrost based OpenCL GEMMKernel selection.
class CLGEMMKernelSelectionFactory
CLGEMMKernelSelection factory class.
class CLGEMMKernelSelectionMidgard
Midgard based OpenCL GEMMKernel selection.
class CLGEMMKernelSelectionValhall
Valhall based OpenCL GEMMKernel selection.
class CLGEMMNativeKernelConfigurationBifrost
Bifrost based OpenCL GEMMNative configuration.
class CLGEMMNativeKernelConfigurationFactory
CLGEMMNative factory class.
class CLGEMMNativeKernelConfigurationMidgard
Midgard based OpenCL GEMMNative configuration.
class CLGEMMNativeKernelConfigurationValhall
Valhall based OpenCL GEMMNative configuration.
class CLGEMMReshapedKernelConfigurationBifrost
Bifrost based OpenCL GEMMReshaped configuration.
class CLGEMMReshapedKernelConfigurationFactory
CLGEMMReshaped factory class.
class CLGEMMReshapedKernelConfigurationValhall
Valhall based OpenCL GEMMReshaped configuration.
class CLGEMMReshapedOnlyRHSKernelConfigurationBifrost
Bifrost based OpenCL GEMMReshapedOnlyRHS configuration.
class CLGEMMReshapedOnlyRHSKernelConfigurationFactory
CLGEMMReshapedOnlyRHS factory class.
class CLGEMMReshapedOnlyRHSKernelConfigurationValhall
Valhall based OpenCL GEMMReshapedOnlyRHS configuration.
class ICLGEMMKernelSelection
Basic interface for the GEMM kernel selection.
Functions
std::pair< GEMMLHSMatrixInfo, GEMMRHSMatrixInfo > configure_lhs_rhs_info (unsigned int m, unsigned int n, unsigned int m0, unsigned int n0, unsigned int k0, unsigned int v0, unsigned int h0, bool lhs_interleave, bool rhs_interleave, bool lhs_transpose, bool rhs_transpose, bool export_to_cl_image=false)
Configure GEMMLHSMatrixInfo and GEMMRHSMatrixInfo.
std::pair< GEMMLHSMatrixInfo, GEMMRHSMatrixInfo > select_lhs_rhs_info (std::pair< GEMMLHSMatrixInfo, GEMMRHSMatrixInfo > info_img, std::pair< GEMMLHSMatrixInfo, GEMMRHSMatrixInfo > info_buf, unsigned int n, unsigned int k, unsigned int b, DataType data_type)
Select GEMMLHSMatrixInfo and GEMMRHSMatrixInfo.
void update_padding_for_cl_image (ITensorInfo *tensor)
Update padding required to export the OpenCL buffer to OpenCL image2d.
Status validate_image2d_support_on_rhs (const ITensorInfo &tensor_reshaped_info, const GEMMRHSMatrixInfo &rhs_info)
Utility function to validate the image2d OpenCL object support on the RHS reshaped matrix.
Function Documentation
configure_lhs_rhs_info()
std::pair< GEMMLHSMatrixInfo, GEMMRHSMatrixInfo > configure_lhs_rhs_info (unsigned int m, unsigned int n, unsigned int m0, unsigned int n0, unsigned int k0, unsigned int v0, unsigned int h0, bool lhs_interleave, bool rhs_interleave, bool lhs_transpose, bool rhs_transpose, bool export_to_cl_image = false)
Configure GEMMLHSMatrixInfo and GEMMRHSMatrixInfo.
Parameters
[in] m Number of rows (M) in the LHS matrix not reshaped
[in] n Number of columns (N) in the RHS matrix not reshaped
[in] m0 Number of rows processed by each thread/work-item
[in] n0 Number of columns processed by each thread/work-item
[in] k0 Number of inner accumulation performed by each thread/work-item
[in] v0 Number of vertical blocks of size (m0xk0) stored on the same output row
[in] h0 Number of horizontal blocks of size (k0xn0) stored on the same output row
[in] lhs_interleave True if the v0 (m0xk0) blocks have to be interleaved in the output row
[in] rhs_interleave True if the h0 (k0xn0) blocks have to be interleaved in the output row
[in] lhs_transpose True if the (m0xk0) block has to be transposed before been stored
[in] rhs_transpose True if the (k0xn0) block has to be transposed before been stored
[in] export_to_cl_image (Optional) True if the RHS reshaped matrix has to be exported to cl_image
Returns
GEMMLHSMatrixInfo and GEMMRHSMatrixInfo
Definition at line 40 of file CLGEMMHelpers.cpp.
 {
     v0 = std::max(std::min(static_cast<int>(m / m0), static_cast<int>(v0)), static_cast<int>(1));
     h0 = std::max(std::min(static_cast<int>(n / n0), static_cast<int>(h0)), static_cast<int>(1));
     const GEMMLHSMatrixInfo lhs_info(m0, k0, v0, lhs_transpose, lhs_interleave);
     const GEMMRHSMatrixInfo rhs_info(n0, k0, h0, rhs_transpose, rhs_interleave, export_to_cl_image);
     return std::make_pair(lhs_info, rhs_info);
 }
select_lhs_rhs_info()
std::pair< GEMMLHSMatrixInfo, GEMMRHSMatrixInfo > select_lhs_rhs_info (std::pair< GEMMLHSMatrixInfo, GEMMRHSMatrixInfo > info_img, std::pair< GEMMLHSMatrixInfo, GEMMRHSMatrixInfo > info_buf, unsigned int n, unsigned int k, unsigned int b, DataType data_type)
Select GEMMLHSMatrixInfo and GEMMRHSMatrixInfo.
This function accepts two pairs of GEMMLHSMatrixInfo/GEMMRHSMatrixInfo where only the first is with cl_image2d support, and selects the valid one validating the GEMMRHSMatrixInfo. If the validation passes, the functions will return the first GEMMLHSMatrixInfo/GEMMRHSMatrixInfo pair with cl_image2d support.
Parameters
[in] info_img GEMMLHSMatrixInfo/GEMMRHSMatrixInfo with cl_image2d support
[in] info_buf GEMMLHSMatrixInfo/GEMMRHSMatrixInfo to fall-back if cl_image2d cannot be used
[in] n Number of columns (N) in the RHS matrix not reshaped
[in] k Number of rows (K) in the RHS matrix not reshaped
[in] b Batch size
[in] data_type Data type
Returns
GEMMLHSMatrixInfo and GEMMRHSMatrixInfo
Definition at line 52 of file CLGEMMHelpers.cpp.
 {
     const TensorInfo  tensor_rhs_info(TensorShape(n, k, b), 1, data_type);
     const TensorShape shape = compute_rhs_reshaped_shape(tensor_rhs_info, info_img.second);
     const TensorInfo  tensor_reshaped_info(shape, 1, data_type);
     if(bool(validate_image2d_support_on_rhs(tensor_reshaped_info, info_img.second)))
     {
         return info_img;
     }
     else
     {
         return info_buf;
     }
 }
References arm_compute::test::validation::b, arm_compute::misc::shape_calculator::compute_rhs_reshaped_shape(), arm_compute::test::validation::data_type, arm_compute::test::validation::shape, and validate_image2d_support_on_rhs().
update_padding_for_cl_image()
void update_padding_for_cl_image (ITensorInfo * tensor)
Update padding required to export the OpenCL buffer to OpenCL image2d.
Parameters
[in,out] tensor ITensorInfo of the tensor required to be exported to OpenCL image2d
Definition at line 70 of file CLGEMMHelpers.cpp.
 {
     constexpr unsigned int num_floats_per_pixel = 4;
     const unsigned int stride_y_in_elements = tensor->strides_in_bytes()[1] / tensor->element_size();
     const unsigned int pixel_aligment       = get_cl_image_pitch_alignment(CLKernelLibrary::get().get_device());
     const unsigned int row_pitch_alignment  = pixel_aligment * num_floats_per_pixel;
     const unsigned int round_up_width       = ((stride_y_in_elements + row_pitch_alignment - 1) / row_pitch_alignment) * row_pitch_alignment;
     const unsigned int padding              = round_up_width - stride_y_in_elements;
     tensor->extend_padding(PaddingSize(0, padding, 0, 0));
 }
References ITensorInfo::element_size(), ITensorInfo::extend_padding(), CLKernelLibrary::get(), arm_compute::get_cl_image_pitch_alignment(), and ITensorInfo::strides_in_bytes().
validate_image2d_support_on_rhs()
Status validate_image2d_support_on_rhs (const ITensorInfo & tensor_reshaped_info, const GEMMRHSMatrixInfo & rhs_info)
Utility function to validate the image2d OpenCL object support on the RHS reshaped matrix.
Parameters
[in] tensor_reshaped_info TensorInfo for the RHS reshaped matrix
[in] rhs_info GEMMRHSMatrixInfo
Returns
Status reporting if we can use the image2d OpenCL object on the RHS reshaped matrix
Definition at line 83 of file CLGEMMHelpers.cpp.
 {
     if(rhs_info.export_to_cl_image)
     {
         ARM_COMPUTE_RETURN_ERROR_ON_MSG((rhs_info.n0 == 2) || (rhs_info.n0 == 3), "Export to cl_image only supported with n0 = 4, 8 or 16");
         ARM_COMPUTE_RETURN_ERROR_ON_MSG((rhs_info.k0 == 2) || (rhs_info.k0 == 3), "Export to cl_image only supported with k0 = 4, 8 or 16");
         ARM_COMPUTE_RETURN_ERROR_ON_DATA_TYPE_NOT_IN(&tensor_reshaped_info, DataType::F32, DataType::F16);
         ARM_COMPUTE_RETURN_ERROR_ON_MSG(!image2d_from_buffer_supported(CLKernelLibrary::get().get_device()), "The extension cl_khr_image2d_from_buffer is not supported on the target platform");
         ARM_COMPUTE_RETURN_ERROR_ON_MSG(get_cl_image_pitch_alignment(CLKernelLibrary::get().get_device()) == 0, "Impossible to retrieve the cl_image pitch alignment");
         // Check the width and height of the output tensor.
         // Since we cannot create a 3d image from a buffer, the third dimension is collapsed on the second dimension
         const size_t max_image_w = CLKernelLibrary::get().get_device().getInfo<CL_DEVICE_IMAGE2D_MAX_WIDTH>();
         const size_t max_image_h = CLKernelLibrary::get().get_device().getInfo<CL_DEVICE_IMAGE2D_MAX_HEIGHT>();
         ARM_COMPUTE_RETURN_ERROR_ON_MSG(tensor_reshaped_info.tensor_shape()[0] > max_image_w * 4, "Not supported width for cl_image");
         ARM_COMPUTE_RETURN_ERROR_ON_MSG(tensor_reshaped_info.tensor_shape()[1] * tensor_reshaped_info.tensor_shape()[2] > max_image_h, "Not supported height for cl_image");
     }
     return Status{};
 }
References ARM_COMPUTE_RETURN_ERROR_ON_DATA_TYPE_NOT_IN, ARM_COMPUTE_RETURN_ERROR_ON_MSG, GEMMRHSMatrixInfo::export_to_cl_image, arm_compute::F16, arm_compute::F32, CLKernelLibrary::get(), arm_compute::get_cl_image_pitch_alignment(), CLKernelLibrary::get_device(), arm_compute::image2d_from_buffer_supported(), GEMMRHSMatrixInfo::k0, GEMMRHSMatrixInfo::n0, and ITensorInfo::tensor_shape().
Referenced by select_lhs_rhs_info().