Compute Library: CLElementwiseSquaredDiff Class Reference
CLElementwiseSquaredDiff Class Reference
Basic function to run CLArithmeticOperationKernel for squared difference.
#include <CLElementwiseOperations.h>
Public Member Functions
CLElementwiseSquaredDiff ()
Default Constructor.
void configure (const CLCompileContext &compile_context, ITensorInfo *input1, ITensorInfo *input2, ITensorInfo *output, const ActivationLayerInfo &act_info=ActivationLayerInfo())
Initialise the kernel's inputs, output and conversion policy.
void run (ITensorPack &tensors) override
Run the kernels contained in the function.
Public Member Functions inherited from ICLOperator
ICLOperator (IRuntimeContext *ctx=nullptr)
Constructor.
ICLOperator (const ICLOperator &)=delete
Prevent instances of this class from being copied (As this class contains pointers)
ICLOperator (ICLOperator &&)=default
Default move constructor.
ICLOperator & operator= (const ICLOperator &)=delete
Prevent instances of this class from being copied (As this class contains pointers)
ICLOperator & operator= (ICLOperator &&)=default
Default move assignment operator.
void run (ITensorPack &tensors) override
Run the kernels contained in the function.
void prepare (ITensorPack &constants) override
Prepare the function for executing.
MemoryRequirements workspace () const override
Return the memory requirements required by the workspace.
Public Member Functions inherited from IOperator
virtual ~IOperator ()=default
Destructor.
Static Public Member Functions
static Status validate (const ITensorInfo *input1, const ITensorInfo *input2, const ITensorInfo *output, const ActivationLayerInfo &act_info=ActivationLayerInfo())
Static function to check if given info will lead to a valid configuration of CLArithmeticOperationKernel for squared difference.
Detailed Description
Basic function to run CLArithmeticOperationKernel for squared difference.
Note
The tensor data type for the inputs must be QASYMM8/U8/S16/QSYMM16/F16/F32.
The function performs a squared different operation between two tensors (i.e., out[i] = (in1[i] - in2[i])^2
Definition at line 299 of file CLElementwiseOperations.h.
Constructor & Destructor Documentation
CLElementwiseSquaredDiff()
CLElementwiseSquaredDiff ()
Default Constructor.
Definition at line 196 of file CLElementwiseOperations.cpp.
     : _border_handler()
 {
 }
Member Function Documentation
configure()
void configure (const CLCompileContext & compile_context, ITensorInfo * input1, ITensorInfo * input2, ITensorInfo * output, const ActivationLayerInfo & act_info = ActivationLayerInfo())
Initialise the kernel's inputs, output and conversion policy.
Parameters
[in] compile_context The compile context to be used.
[in,out] input1 First tensor input. Data types supported: U8/QASYMM8/QASYMM8_SIGNED/S16/QSYMM16/F16/F32. The input tensor is [in, out] because its TensorInfo might be modified inside the kernel in case of broadcasting of dimension 0.
[in,out] input2 Second tensor input. Data types supported: same as input1. The input tensor is [in, out] because its TensorInfo might be modified inside the kernel in case of broadcasting of dimension 0.
[out] output Output tensor. Data types supported: same as input1.
[in] act_info (Optional) Activation layer information in case of a fused activation.
Definition at line 201 of file CLElementwiseOperations.cpp.
 {
     auto k = arm_compute::support::cpp14::make_unique<CLArithmeticOperationKernel>();
     k->configure(compile_context, ArithmeticOperation::SQUARED_DIFF, input1, input2, output, act_info);
     _kernel = std::move(k);
     configure_border_handler(compile_context, _border_handler, _kernel->border_size(), input1, input2, output);
 }
References IKernel::border_size(), and arm_compute::SQUARED_DIFF.
run()
void run (ITensorPack & tensors) override virtual
Run the kernels contained in the function.
Parameters
[in] tensors Vector that contains the tensors to operate on.
Implements IOperator.
Definition at line 214 of file CLElementwiseOperations.cpp.
 {
     auto border_pack = select_border_input(tensors);
     CLScheduler::get().enqueue_op(_border_handler, border_pack);
     ICLOperator::run(tensors);
 }
References CLScheduler::enqueue_op(), CLScheduler::get(), and ICLOperator::run().
validate()
Status validate (const ITensorInfo * input1, const ITensorInfo * input2, const ITensorInfo * output, const ActivationLayerInfo & act_info = ActivationLayerInfo()) static
Static function to check if given info will lead to a valid configuration of CLArithmeticOperationKernel for squared difference.
Parameters
[in] input1 First tensor input info. Data types supported: U8/QASYMM8/QASYMM8_SIGNED/S16/QSYMM16/F16/F32.
[in] input2 Second tensor input info. Data types supported: same as input1.
[in] output Output tensor info. Data types supported: same as input1.
[in] act_info (Optional) Activation layer information in case of a fused activation.
Returns
a status
Definition at line 209 of file CLElementwiseOperations.cpp.
 {
     return CLArithmeticOperationKernel::validate(ArithmeticOperation::SQUARED_DIFF, input1, input2, output, act_info);
 }
References arm_compute::SQUARED_DIFF, and CLArithmeticOperationKernel::validate().
Referenced by CLElementwiseSquaredDiff::validate().
The documentation for this class was generated from the following files:
arm_compute/runtime/CL/functions/CLElementwiseOperations.h
src/runtime/CL/functions/CLElementwiseOperations.cpp