Compute Library: NEMaxUnpoolingLayer Class Reference
NEMaxUnpoolingLayer Class Reference
Function to perform MaxUnpooling.
#include <NEMaxUnpoolingLayer.h>
Public Member Functions
NEMaxUnpoolingLayer ()
Constructor.
void configure (ITensor *input, ITensor *indices, ITensor *output, const PoolingLayerInfo &pool_info)
Set the input and output tensors.
void run () override
Run the kernels contained in the function.
Public Member Functions inherited from IFunction
virtual ~IFunction ()=default
Destructor.
virtual void prepare ()
Prepare the function for executing.
Static Public Member Functions
static Status validate (const ITensorInfo *input, const ITensorInfo *indices, const ITensorInfo *output, const PoolingLayerInfo &pool_info)
Static function to check if given info will lead to a valid configuration of NEMaxUnpoolingLayer.
Detailed Description
Function to perform MaxUnpooling.
This function calls the following NEON kernels:
NEMemsetKernel
NEMaxUnpoolingLayerKernel
Definition at line 41 of file NEMaxUnpoolingLayer.h.
Constructor & Destructor Documentation
NEMaxUnpoolingLayer()
NEMaxUnpoolingLayer ()
Constructor.
Definition at line 31 of file NEMaxUnpoolingLayer.cpp.
     : _memset_kernel(), _unpooling_layer_kernel()
 {
 }
Member Function Documentation
configure()
void configure (ITensor * input, ITensor * indices, ITensor * output, const PoolingLayerInfo & pool_info)
Set the input and output tensors.
Note
Only supported pool size 2
Parameters
[in,out] input Source tensor. (Written to only when padding != 0) Data types supported: QASYMM8/QASYMM8_SIGNED/F16/F32.
[out] output Destination tensor. Data types supported: Same as input.
[out] indices The indices of the maximal values. Data type supported: U32.
[in] pool_info Contains pooling operation information described in PoolingLayerInfo.
Definition at line 37 of file NEMaxUnpoolingLayer.cpp.
 {
     const PixelValue zero_value(0.f);
     _memset_kernel.configure(output, zero_value);
     _unpooling_layer_kernel.configure(input, indices, output, pool_info);
 }
References NEMemsetKernel::configure(), NEMaxUnpoolingLayerKernel::configure(), and arm_compute::test::validation::input.
run()
void run () override virtual
Run the kernels contained in the function.
For NEON kernels:
Multi-threading is used for the kernels which are parallelisable.
By default std::thread::hardware_concurrency() threads are used.
Note
CPPScheduler::set_num_threads() can be used to manually set the number of threads
For OpenCL kernels:
All the kernels are enqueued on the queue associated with CLScheduler.
The queue is then flushed.
Note
The function will not block until the kernels are executed. It is the user's responsibility to wait.
Will call prepare() on first run if hasn't been done
Implements IFunction.
Definition at line 49 of file NEMaxUnpoolingLayer.cpp.
 {
     NEScheduler::get().schedule(&_memset_kernel, Window::DimY);
     NEScheduler::get().schedule(&_unpooling_layer_kernel, Window::DimY);
 }
References Window::DimY, Scheduler::get(), and IScheduler::schedule().
validate()
Status validate (const ITensorInfo * input, const ITensorInfo * indices, const ITensorInfo * output, const PoolingLayerInfo & pool_info) static
Static function to check if given info will lead to a valid configuration of NEMaxUnpoolingLayer.
Note
Only supported pool size 2
Parameters
[in] input Source tensor. (Written to only when padding != 0) Data types supported: QASYMM8/QASYMM8_SIGNED/F16/F32.
[in] indices The indices of the maximal values. Data type supported: U32.
[in] output Destination tensor. Data types supported: Same as input.
[in] pool_info Contains pooling operation information described in PoolingLayerInfo.
Returns
a status
Definition at line 44 of file NEMaxUnpoolingLayer.cpp.
 {
     return NEMaxUnpoolingLayerKernel::validate(input, indices, output, pool_info);
 }
References arm_compute::test::validation::input, and NEMaxUnpoolingLayerKernel::validate().
The documentation for this class was generated from the following files:
arm_compute/runtime/NEON/functions/NEMaxUnpoolingLayer.h
src/runtime/NEON/functions/NEMaxUnpoolingLayer.cpp