Compute Library: RuntimeContext Class Reference
RuntimeContext Class Reference
Runtime context.
#include <RuntimeContext.h>
Public Member Functions
RuntimeContext ()
Default Constructor.
~RuntimeContext ()=default
Destructor.
RuntimeContext (const RuntimeContext &)=delete
Prevent instances of this class from being copied (As this class contains pointers)
RuntimeContext (RuntimeContext &&)=default
Default move constructor.
RuntimeContext & operator= (const RuntimeContext &)=delete
Prevent instances of this class from being copied (As this class contains pointers)
RuntimeContext & operator= (RuntimeContext &&)=default
Default move assignment operator.
void set_scheduler (IScheduler *scheduler)
CPU Scheduler setter.
IScheduler * scheduler () override
Scheduler accessor.
IAssetManager * asset_manager () override
Asset manager accessor.
const DeviceProperties & properties () override
Device propertied accessor.
Public Member Functions inherited from IRuntimeContext
virtual ~IRuntimeContext ()=default
Destructor.
Detailed Description
Runtime context.
Definition at line 35 of file RuntimeContext.h.
Constructor & Destructor Documentation
RuntimeContext() [1/3]
RuntimeContext ()
Default Constructor.
Definition at line 31 of file RuntimeContext.cpp.
     : _owned_scheduler(SchedulerFactory::create()), _scheduler(_owned_scheduler.get()), _device_props()
 {
 }
~RuntimeContext()
~RuntimeContext () default
Destructor.
RuntimeContext() [2/3]
RuntimeContext (const RuntimeContext &) delete
Prevent instances of this class from being copied (As this class contains pointers)
RuntimeContext() [3/3]
RuntimeContext (RuntimeContext &&) default
Default move constructor.
Member Function Documentation
asset_manager()
IAssetManager * asset_manager () override virtual
Asset manager accessor.
Note
Asset manager is used to manage objects/tensors within functions
Returns
The asset manager registered to the context
Implements IRuntimeContext.
Definition at line 47 of file RuntimeContext.cpp.
 {
     return nullptr;
 }
Referenced by arm_compute::test::validation::TEST_CASE().
operator=() [1/2]
RuntimeContext& operator= (const RuntimeContext &) delete
Prevent instances of this class from being copied (As this class contains pointers)
operator=() [2/2]
RuntimeContext& operator= (RuntimeContext &&) default
Default move assignment operator.
properties()
const DeviceProperties & properties () override virtual
Device propertied accessor.
Returns
Device properties
Implements IRuntimeContext.
Definition at line 52 of file RuntimeContext.cpp.
 {
     return _device_props;
 }
scheduler()
IScheduler * scheduler () override virtual
Scheduler accessor.
Note
Scheduler is used to schedule workloads
Returns
The scheduler registered to the context
Implements IRuntimeContext.
Definition at line 42 of file RuntimeContext.cpp.
 {
     return _scheduler;
 }
Referenced by ContextSchedulerUser::ContextSchedulerUser(), GCRuntimeContext::set_gpu_scheduler(), CLRuntimeContext::set_gpu_scheduler(), RuntimeContext::set_scheduler(), and arm_compute::test::validation::TEST_CASE().
set_scheduler()
void set_scheduler (IScheduler * scheduler)
CPU Scheduler setter.
Definition at line 36 of file RuntimeContext.cpp.
 {
     ARM_COMPUTE_ERROR_ON_NULLPTR(scheduler);
     _scheduler = scheduler;
 }
References ARM_COMPUTE_ERROR_ON_NULLPTR, and RuntimeContext::scheduler().
Referenced by ContextSchedulerUser::intercept_scheduler(), ContextSchedulerUser::restore_scheduler(), and arm_compute::test::validation::TEST_CASE().
The documentation for this class was generated from the following files:
arm_compute/runtime/RuntimeContext.h
src/runtime/RuntimeContext.cpp