Compute Library: NEArithmeticSubtractionKernel Class Reference
NEArithmeticSubtractionKernel Class Reference
Interface for the kernel to perform subtraction between two tensors.
#include <NEArithmeticSubtractionKernel.h>
Public Member Functions
const char * name () const override
Name of the kernel.
NEArithmeticSubtractionKernel ()
Default constructor.
NEArithmeticSubtractionKernel (const NEArithmeticSubtractionKernel &)=delete
Prevent instances of this class from being copied (As this class contains pointers)
NEArithmeticSubtractionKernel & operator= (const NEArithmeticSubtractionKernel &)=delete
Prevent instances of this class from being copied (As this class contains pointers)
NEArithmeticSubtractionKernel (NEArithmeticSubtractionKernel &&)=default
Allow instances of this class to be moved.
NEArithmeticSubtractionKernel & operator= (NEArithmeticSubtractionKernel &&)=default
Allow instances of this class to be moved.
~NEArithmeticSubtractionKernel ()=default
Default destructor.
void configure (const ITensorInfo *input1, const ITensorInfo *input2, ITensorInfo *output, ConvertPolicy policy)
Initialise the kernel's input and output.
void run_op (ITensorPack &tensors, const Window &window, const ThreadInfo &info) override
Execute the kernel on the passed window.
Public Member Functions inherited from ICPPKernel
virtual ~ICPPKernel ()=default
Default destructor.
virtual void run (const Window &window, const ThreadInfo &info)
Execute the kernel on the passed window.
virtual void run_nd (const Window &window, const ThreadInfo &info, const Window &thread_locator)
legacy compatibility layer for implemantions which do not support thread_locator In these cases we simply narrow the interface down the legacy version
Public Member Functions inherited from IKernel
IKernel ()
Constructor.
virtual ~IKernel ()=default
Destructor.
virtual bool is_parallelisable () const
Indicates whether or not the kernel is parallelisable.
virtual BorderSize border_size () const
The size of the border for that kernel.
const Window & window () const
The maximum window the kernel can be executed on.
Static Public Member Functions
static Status validate (const ITensorInfo *input1, const ITensorInfo *input2, const ITensorInfo *output, ConvertPolicy policy)
Static function to check if given info will lead to a valid configuration of NEArithmeticSubtractionKernel.
Detailed Description
Interface for the kernel to perform subtraction between two tensors.
Definition at line 35 of file NEArithmeticSubtractionKernel.h.
Constructor & Destructor Documentation
NEArithmeticSubtractionKernel() [1/3]
NEArithmeticSubtractionKernel ()
Default constructor.
Definition at line 721 of file NEArithmeticSubtractionKernel.cpp.
     : _func(nullptr), _policy(ConvertPolicy::WRAP)
 {
 }
References arm_compute::WRAP.
NEArithmeticSubtractionKernel() [2/3]
NEArithmeticSubtractionKernel (const NEArithmeticSubtractionKernel &) delete
Prevent instances of this class from being copied (As this class contains pointers)
NEArithmeticSubtractionKernel() [3/3]
NEArithmeticSubtractionKernel (NEArithmeticSubtractionKernel &&) default
Allow instances of this class to be moved.
~NEArithmeticSubtractionKernel()
~NEArithmeticSubtractionKernel () default
Default destructor.
Member Function Documentation
configure()
void configure (const ITensorInfo * input1, const ITensorInfo * input2, ITensorInfo * output, ConvertPolicy policy)
Initialise the kernel's input and output.
Valid configurations (Input1,Input2) -> Output :
(U8,U8) -> U8
(U8,U8) -> S16
(QASYMM8, QASYMM8) -> QASYMM8
(QASYMM8_SIGNED, QASYMM8_SIGNED) -> QASYMM8_SIGNED
(S16,U8) -> S16
(U8,S16) -> S16
(S16,S16) -> S16
(F16,F16) -> F16
(F32,F32) -> F32
Parameters
[in] input1 An input tensor. Data types supported: U8/QASYMM8/QASYMM8_SIGNED/QSYMM16/S16/F16/F32
[in] input2 An input tensor. Data types supported: U8/QASYMM8/QASYMM8_SIGNED/QSYMM16/S16/F16/F32
[out] output The output tensor. Data types supported: U8/QASYMM8/QASYMM8_SIGNED/QSYMM16/S16/F16/F32.
[in] policy Overflow policy. Convert policy cannot be WRAP if datatype is quantized.
Definition at line 726 of file NEArithmeticSubtractionKernel.cpp.
 {
     ARM_COMPUTE_ERROR_ON_NULLPTR(input1, input2, output);
     ARM_COMPUTE_ERROR_THROW_ON(validate_arguments(*input1, *input2, *output, policy));
     _policy = policy;
     const std::pair<TensorShape, ValidRegion> broadcast_pair = ITensorInfo::broadcast_shape_and_valid_region(*input1, *input2);
     const TensorShape &out_shape    = broadcast_pair.first;
     const ValidRegion &valid_region = broadcast_pair.second;
     // Auto initialize output if not initialized
     set_shape_if_empty(*output, out_shape);
     switch(input1->data_type())
     {
         case DataType::U8:
             if(input2->data_type() == DataType::U8 && output->data_type() == DataType::U8)
             {
                 _func = &sub_same<uint8_t>;
             }
             else if(input2->data_type() == DataType::U8 && output->data_type() == DataType::S16)
             {
                 _func = &sub_U8_U8_S16;
             }
             else
             {
                 _func = &sub_U8_S16_S16;
             }
             break;
         case DataType::QASYMM8:
             _func = &sub_quantized<uint8_t>;
             set_data_type_if_unknown(*output, DataType::QASYMM8);
             break;
         case DataType::QASYMM8_SIGNED:
             _func = &sub_quantized<int8_t>;
             set_data_type_if_unknown(*output, DataType::QASYMM8_SIGNED);
             break;
         case DataType::S16:
             if(input2->data_type() == DataType::U8)
             {
                 _func = &sub_S16_U8_S16;
             }
             else
             {
                 _func = &sub_same<int16_t>;
             }
             set_format_if_unknown(*output, Format::S16);
             break;
         case DataType::QSYMM16:
             _func = &sub_QSYMM16_QSYMM16_QSYMM16;
             set_data_type_if_unknown(*output, DataType::QSYMM16);
             break;
 #ifdef __ARM_FEATURE_FP16_VECTOR_ARITHMETIC
         case DataType::F16:
             _func = &sub_same<float16_t>;
             set_format_if_unknown(*output, Format::F16);
             break;
 #endif /* __ARM_FEATURE_FP16_VECTOR_ARITHMETIC */
         case DataType::F32:
             _func = &sub_same<float>;
             set_format_if_unknown(*output, Format::F32);
             break;
         default:
             _func = nullptr;
     }
     // NEArithmeticSubtractionKernel doesn't need padding so update_window_and_padding() can be skipped
     Coordinates coord;
     coord.set_num_dimensions(output->num_dimensions());
     output->set_valid_region(valid_region);
     Window win = calculate_max_window(valid_region, Steps());
     INEKernel::configure(win);
 }
References ARM_COMPUTE_ERROR_ON_NULLPTR, ARM_COMPUTE_ERROR_THROW_ON, ITensorInfo::broadcast_shape_and_valid_region(), arm_compute::calculate_max_window(), ITensorInfo::data_type(), arm_compute::F16, arm_compute::F32, ITensorInfo::num_dimensions(), arm_compute::test::validation::policy, arm_compute::QASYMM8, arm_compute::QASYMM8_SIGNED, arm_compute::QSYMM16, arm_compute::S16, arm_compute::set_data_type_if_unknown(), arm_compute::set_format_if_unknown(), Dimensions< T >::set_num_dimensions(), arm_compute::set_shape_if_empty(), ITensorInfo::set_valid_region(), arm_compute::U8, arm_compute::test::validation::valid_region, and arm_compute::validate_arguments().
name()
const char* name () const inline override virtual
Name of the kernel.
Returns
Kernel name
Implements ICPPKernel.
Definition at line 38 of file NEArithmeticSubtractionKernel.h.
     {
         return "NEArithmeticSubtractionKernel";
     }
operator=() [1/2]
NEArithmeticSubtractionKernel& operator= (const NEArithmeticSubtractionKernel &) delete
Prevent instances of this class from being copied (As this class contains pointers)
operator=() [2/2]
NEArithmeticSubtractionKernel& operator= (NEArithmeticSubtractionKernel &&) default
Allow instances of this class to be moved.
run_op()
void run_op (ITensorPack & tensors, const Window & window, const ThreadInfo & info) override virtual
Execute the kernel on the passed window.
Warning
If is_parallelisable() returns false then the passed window must be equal to window()
Note
The window has to be a region within the window returned by the window() method
The width of the window has to be a multiple of num_elems_processed_per_iteration().
Parameters
[in] tensors A vector containing the tensors to operate on.
[in] window Region on which to execute the kernel. (Must be a region of the window returned by window())
[in] info Info about executing thread and CPU.
Reimplemented from ICPPKernel.
Definition at line 810 of file NEArithmeticSubtractionKernel.cpp.
 {
     ARM_COMPUTE_UNUSED(info);
     ARM_COMPUTE_ERROR_ON_UNCONFIGURED_KERNEL(this);
     ARM_COMPUTE_ERROR_ON_INVALID_SUBWINDOW(INEKernel::window(), window);
     // Dispatch kernel
     (*_func)(tensors.get_const_tensor(TensorType::ACL_SRC_0),
              tensors.get_const_tensor(TensorType::ACL_SRC_1),
              tensors.get_tensor(TensorType::ACL_DST),
              window,
              (_policy == ConvertPolicy::SATURATE));
 }
References arm_compute::ACL_DST, arm_compute::ACL_SRC_0, arm_compute::ACL_SRC_1, ARM_COMPUTE_ERROR_ON_INVALID_SUBWINDOW, ARM_COMPUTE_ERROR_ON_UNCONFIGURED_KERNEL, ARM_COMPUTE_UNUSED, ITensorPack::get_const_tensor(), ITensorPack::get_tensor(), arm_compute::test::validation::info, arm_compute::SATURATE, and IKernel::window().
validate()
Status validate (const ITensorInfo * input1, const ITensorInfo * input2, const ITensorInfo * output, ConvertPolicy policy) static
Static function to check if given info will lead to a valid configuration of NEArithmeticSubtractionKernel.
Valid configurations (Input1,Input2) -> Output :
(U8,U8) -> U8
(U8,U8) -> S16
(QASYMM8, QASYMM8) -> QASYMM8
(QASYMM8_SIGNED, QASYMM8_SIGNED) -> QASYMM8_SIGNED
(S16,U8) -> S16
(U8,S16) -> S16
(S16,S16) -> S16
(F16,F16) -> F16
(F32,F32) -> F32
Note
Convert policy cannot be WRAP if datatype is QASYMM8
Parameters
[in] input1 An input tensor info. Data types supported: U8/QASYMM8/QASYMM8_SIGNED/QSYMM16/S16/F16/F32
[in] input2 An input tensor info. Data types supported: U8/QASYMM8/QASYMM8_SIGNED/QSYMM16/S16/F16/F32
[in] output The output tensor info. Data types supported: U8/QASYMM8/QASYMM8_SIGNED/QSYMM16/S16/F16/F32.
[in] policy Policy to use to handle overflow. Convert policy cannot be WRAP if datatype is quantized.
Returns
a status
Definition at line 802 of file NEArithmeticSubtractionKernel.cpp.
 {
     ARM_COMPUTE_RETURN_ERROR_ON_NULLPTR(input1, input2, output);
     ARM_COMPUTE_RETURN_ON_ERROR(validate_arguments(*input1, *input2, *output, policy));
     return Status{};
 }
References ARM_COMPUTE_RETURN_ERROR_ON_NULLPTR, ARM_COMPUTE_RETURN_ON_ERROR, arm_compute::test::validation::policy, and arm_compute::validate_arguments().
Referenced by NEArithmeticSubtraction::validate().
The documentation for this class was generated from the following files:
arm_compute/core/NEON/kernels/NEArithmeticSubtractionKernel.h
src/core/NEON/kernels/NEArithmeticSubtractionKernel.cpp