Compute Library: CLCoreRuntimeContext Class Reference
CLCoreRuntimeContext Class Reference final
Core runtime context for OpenCL.
#include <CLCoreRuntimeContext.h>
Public Member Functions
CLCoreRuntimeContext ()
Legacy constructor.
CLCoreRuntimeContext (CLKernelLibrary *kernel_lib, cl::Context ctx, cl::CommandQueue queue)
Constructor.
~CLCoreRuntimeContext ()=default
Destructor.
CLCoreRuntimeContext (const CLCoreRuntimeContext &)=default
Default copy constructor.
CLCoreRuntimeContext (CLCoreRuntimeContext &&)=default
Default move constructor.
CLCoreRuntimeContext & operator= (const CLCoreRuntimeContext &)=default
Default copy assignment.
CLCoreRuntimeContext & operator= (CLCoreRuntimeContext &&)=default
Default move assignment operator.
CLKernelLibrary * kernel_library () const
Kernel Library accessor.
cl::Context context ()
OpenCL context accessor.
cl::CommandQueue queue ()
OpenCL command queue accessor.
Detailed Description
Core runtime context for OpenCL.
Definition at line 35 of file CLCoreRuntimeContext.h.
Constructor & Destructor Documentation
CLCoreRuntimeContext() [1/4]
CLCoreRuntimeContext ()
Legacy constructor.
Definition at line 38 of file CLCoreRuntimeContext.cpp.
     : _kernel_lib(nullptr), _ctx(), _queue()
 {
 }
CLCoreRuntimeContext() [2/4]
CLCoreRuntimeContext (CLKernelLibrary * kernel_lib, cl::Context ctx, cl::CommandQueue queue)
Constructor.
Definition at line 43 of file CLCoreRuntimeContext.cpp.
     : _kernel_lib(kernel_lib), _ctx(ctx), _queue(queue)
 {
 }
~CLCoreRuntimeContext()
~CLCoreRuntimeContext () default
Destructor.
CLCoreRuntimeContext() [3/4]
CLCoreRuntimeContext (const CLCoreRuntimeContext &) default
Default copy constructor.
CLCoreRuntimeContext() [4/4]
CLCoreRuntimeContext (CLCoreRuntimeContext &&) default
Default move constructor.
Member Function Documentation
context()
cl::Context context ()
OpenCL context accessor.
Returns
The OpenCL context used by the core context
Definition at line 28 of file CLCoreRuntimeContext.cpp.
 {
     return _ctx;
 }
Referenced by CLBufferAllocator::allocate(), and CLBufferMemoryRegion::CLBufferMemoryRegion().
kernel_library()
CLKernelLibrary * kernel_library () const
Kernel Library accessor.
Returns
The kernel library instance used by the core context
Definition at line 48 of file CLCoreRuntimeContext.cpp.
 {
     return _kernel_lib;
 }
Referenced by arm_compute::create_opencl_kernel().
operator=() [1/2]
CLCoreRuntimeContext& operator= (const CLCoreRuntimeContext &) default
Default copy assignment.
operator=() [2/2]
CLCoreRuntimeContext& operator= (CLCoreRuntimeContext &&) default
Default move assignment operator.
queue()
cl::CommandQueue queue ()
OpenCL command queue accessor.
Returns
The OpenCL queue used by the core context
Definition at line 33 of file CLCoreRuntimeContext.cpp.
 {
     return _queue;
 }
The documentation for this class was generated from the following files:
arm_compute/core/CL/CLCoreRuntimeContext.h
src/core/CL/CLCoreRuntimeContext.cpp