Compute Library: bfloat16 Class Reference
bfloat16 Class Reference final
Brain floating point representation class.
#include <Bfloat16.h>
Public Member Functions
bfloat16 ()
Default Constructor.
bfloat16 (float v)
Constructor.
bfloat16 & operator= (float v)
Assignment operator.
operator float () const
Floating point conversion operator.
Static Public Member Functions
static bfloat16 lowest ()
Lowest representative value.
static bfloat16 max ()
Largest representative value.
Detailed Description
Brain floating point representation class.
Definition at line 80 of file Bfloat16.h.
Constructor & Destructor Documentation
bfloat16() [1/2]
bfloat16 () inline
Default Constructor.
Definition at line 84 of file Bfloat16.h.
         : value(0)
     {
     }
bfloat16() [2/2]
bfloat16 (float v) inline explicit
Constructor.
Parameters
[in] v Floating-point value
Definition at line 92 of file Bfloat16.h.
         : value(float_to_bf16(v))
     {
     }
Member Function Documentation
lowest()
static bfloat16 lowest () inline static
Lowest representative value.
Returns
Returns the lowest finite value representable by bfloat16
Definition at line 119 of file Bfloat16.h.
     {
         bfloat16 val;
         val.value = 0xFF7F;
         return val;
     }
Referenced by arm_compute::check_value_range(), arm_compute::get_min_max(), and arm_compute::support::cpp11::lowest< bfloat16 >().
max()
static bfloat16 max () inline static
Largest representative value.
Returns
Returns the largest finite value representable by bfloat16
Definition at line 129 of file Bfloat16.h.
     {
         bfloat16 val;
         val.value = 0x7F7F;
         return val;
     }
Referenced by arm_compute::check_value_range(), and arm_compute::get_min_max().
operator float()
operator float () const inline
Floating point conversion operator.
Returns
Floating point representation of the value
Definition at line 111 of file Bfloat16.h.
     {
         return bf16_to_float(value);
     }
operator=()
bfloat16& operator= (float v) inline
Assignment operator.
Parameters
[in] v Floating point value to assign
Returns
The updated object
Definition at line 102 of file Bfloat16.h.
     {
         value = float_to_bf16(v);
         return *this;
     }
The documentation for this class was generated from the following file:
support/Bfloat16.h