Compute Library: CLBatchNormalizationLayer Class Reference
CLBatchNormalizationLayer Class Reference
Basic function to run CLNormalizationLayerKernel and simulate a batch normalization layer.
#include <CLBatchNormalizationLayer.h>
Public Member Functions
CLBatchNormalizationLayer ()
Default constructor.
void configure (ICLTensor *input, ICLTensor *output, const ICLTensor *mean, const ICLTensor *var, const ICLTensor *beta=nullptr, const ICLTensor *gamma=nullptr, float epsilon=0.001f, ActivationLayerInfo act_info=ActivationLayerInfo())
Set the input and output tensors.
void configure (const CLCompileContext &compile_context, ICLTensor *input, ICLTensor *output, const ICLTensor *mean, const ICLTensor *var, const ICLTensor *beta=nullptr, const ICLTensor *gamma=nullptr, float epsilon=0.001f, ActivationLayerInfo act_info=ActivationLayerInfo())
Set the input and output tensors.
void run () override
Run the kernels contained in the function.
Public Member Functions inherited from IFunction
virtual ~IFunction ()=default
Destructor.
virtual void prepare ()
Prepare the function for executing.
Static Public Member Functions
static Status validate (const ITensorInfo *input, const ITensorInfo *output, const ITensorInfo *mean, const ITensorInfo *var, const ITensorInfo *beta=nullptr, const ITensorInfo *gamma=nullptr, float epsilon=0.001f, ActivationLayerInfo act_info=ActivationLayerInfo())
Static function to check if given info will lead to a valid configuration of CLBatchNormalizationLayer.
Detailed Description
Basic function to run CLNormalizationLayerKernel and simulate a batch normalization layer.
Batch normalization is calculated by:
\[ out_i = \gamma * (\frac{in_i - \mu_{B}}{\sqrt{\sigma^2_{B} + \epsilon}}) + \beta \equiv BN_{\gamma,\beta}(in_i) \]
Definition at line 42 of file CLBatchNormalizationLayer.h.
Constructor & Destructor Documentation
CLBatchNormalizationLayer()
CLBatchNormalizationLayer ()
Default constructor.
Definition at line 35 of file CLBatchNormalizationLayer.cpp.
     : _norm_kernel()
 {
 }
Member Function Documentation
configure() [1/2]
void configure (ICLTensor * input, ICLTensor * output, const ICLTensor * mean, const ICLTensor * var, const ICLTensor * beta = nullptr, const ICLTensor * gamma = nullptr, float epsilon = 0.001f, ActivationLayerInfo act_info = ActivationLayerInfo())
Set the input and output tensors.
Note
If the output tensor is a nullptr or is equal to the input, the batch normalization function will be performed in-place
Parameters
[in,out] input Source tensor. In case of output tensor = nullptr, this tensor will store the result. 3 lower dimensions represent a single input with dimensions [width, height, FM]. The rest are optional and used for representing batches. Data types supported: F16/F32. Data layouts supported: NCHW/NHWC.
[out] output Destination tensor. Output will have the same number of dimensions as input. Data type supported: same as input
[in] mean Mean values tensor. 1 dimension with size equal to the feature maps [FM]. Data types supported: Same as input
[in] var Variance values tensor. 1 dimension with size equal to the feature maps [FM]. Data types supported: Same as input
[in] beta (Optional) Beta values tensor info. 1 dimension with size equal to the feature maps [FM]. If not provided, default value for beta is 0. Data types supported: Same as input
[in] gamma (Optional) Gamma values tensor info. 1 dimension with size equal to the feature maps [FM]. If not provided, default value for gamma is 1. Data types supported: Same as input
[in] epsilon (Optional) Small value to avoid division with zero. Default value is 0.001f.
[in] act_info (Optional) Activation layer information in case of a fused activation. Only RELU, BOUNDED_RELU and LU_BOUNDED_RELU supported.
Definition at line 40 of file CLBatchNormalizationLayer.cpp.
 {
     configure(CLKernelLibrary::get().get_compile_context(), input, output, mean, var, beta, gamma, epsilon, act_info);
 }
References arm_compute::quantization::epsilon, CLKernelLibrary::get(), and arm_compute::test::validation::input.
configure() [2/2]
void configure (const CLCompileContext & compile_context, ICLTensor * input, ICLTensor * output, const ICLTensor * mean, const ICLTensor * var, const ICLTensor * beta = nullptr, const ICLTensor * gamma = nullptr, float epsilon = 0.001f, ActivationLayerInfo act_info = ActivationLayerInfo())
Set the input and output tensors.
Note
If the output tensor is a nullptr or is equal to the input, the batch normalization function will be performed in-place
Parameters
[in] compile_context The compile context to be used.
[in,out] input Source tensor. In case of output tensor = nullptr, this tensor will store the result. 3 lower dimensions represent a single input with dimensions [width, height, FM]. The rest are optional and used for representing batches. Data types supported: F16/F32. Data layouts supported: NCHW/NHWC.
[out] output Destination tensor. Output will have the same number of dimensions as input. Data type supported: same as input
[in] mean Mean values tensor. 1 dimension with size equal to the feature maps [FM]. Data types supported: Same as input
[in] var Variance values tensor. 1 dimension with size equal to the feature maps [FM]. Data types supported: Same as input
[in] beta (Optional) Beta values tensor info. 1 dimension with size equal to the feature maps [FM]. If not provided, default value for beta is 0. Data types supported: Same as input
[in] gamma (Optional) Gamma values tensor info. 1 dimension with size equal to the feature maps [FM]. If not provided, default value for gamma is 1. Data types supported: Same as input
[in] epsilon (Optional) Small value to avoid division with zero. Default value is 0.001f.
[in] act_info (Optional) Activation layer information in case of a fused activation. Only RELU, BOUNDED_RELU and LU_BOUNDED_RELU supported.
Definition at line 46 of file CLBatchNormalizationLayer.cpp.
 {
     _norm_kernel.configure(compile_context, input, output, mean, var, beta, gamma, epsilon, act_info);
 }
References CLBatchNormalizationLayerKernel::configure(), arm_compute::quantization::epsilon, and arm_compute::test::validation::input.
run()
void run () override virtual
Run the kernels contained in the function.
For NEON kernels:
Multi-threading is used for the kernels which are parallelisable.
By default std::thread::hardware_concurrency() threads are used.
Note
CPPScheduler::set_num_threads() can be used to manually set the number of threads
For OpenCL kernels:
All the kernels are enqueued on the queue associated with CLScheduler.
The queue is then flushed.
Note
The function will not block until the kernels are executed. It is the user's responsibility to wait.
Will call prepare() on first run if hasn't been done
Implements IFunction.
Definition at line 61 of file CLBatchNormalizationLayer.cpp.
 {
     CLScheduler::get().enqueue(_norm_kernel, true);
 }
References CLScheduler::enqueue(), and CLScheduler::get().
validate()
Status validate (const ITensorInfo * input, const ITensorInfo * output, const ITensorInfo * mean, const ITensorInfo * var, const ITensorInfo * beta = nullptr, const ITensorInfo * gamma = nullptr, float epsilon = 0.001f, ActivationLayerInfo act_info = ActivationLayerInfo()) static
Static function to check if given info will lead to a valid configuration of CLBatchNormalizationLayer.
Parameters
[in] input Source tensor info. In case of output tensor info = nullptr, this tensor will store the result. 3 lower dimensions represent a single input with dimensions [width, height, FM]. The rest are optional and used for representing batches. Data types supported: F16/F32. Data layouts supported: NCHW/NHWC.
[in] output Destination tensor info. Output will have the same number of dimensions as input. Data type supported: same as input
[in] mean Mean values tensor info. 1 dimension with size equal to the feature maps [FM]. Data types supported: Same as input
[in] var Variance values tensor info. 1 dimension with size equal to the feature maps [FM]. Data types supported: Same as input
[in] beta (Optional) Beta values tensor info. 1 dimension with size equal to the feature maps [FM]. If not provided, default value for beta is 0. Data types supported: Same as input
[in] gamma (Optional) Gamma values tensor info. 1 dimension with size equal to the feature maps [FM]. If not provided, default value for gamma is 1. Data types supported: Same as input
[in] epsilon (Optional) Small value to avoid division with zero. Default value is 0.001f.
[in] act_info (Optional) Activation layer information in case of a fused activation. Only RELU, BOUNDED_RELU and LU_BOUNDED_RELU supported.
Returns
a status
Definition at line 53 of file CLBatchNormalizationLayer.cpp.
 {
     return CLBatchNormalizationLayerKernel::validate(input, output, mean, var, beta, gamma, epsilon, act_info);
 }
References arm_compute::quantization::epsilon, arm_compute::test::validation::input, and CLBatchNormalizationLayerKernel::validate().
The documentation for this class was generated from the following files:
arm_compute/runtime/CL/functions/CLBatchNormalizationLayer.h
src/runtime/CL/functions/CLBatchNormalizationLayer.cpp