Compute Library: CLComplexPixelWiseMultiplication Class Reference
CLComplexPixelWiseMultiplication Class Reference
Basic function to run CLComplexPixelWiseMultiplicationKernel.
#include <CLPixelWiseMultiplication.h>
Public Member Functions
CLComplexPixelWiseMultiplication ()
Default Constructor.
void configure (const CLCompileContext &compile_context, ITensorInfo *input1, ITensorInfo *input2, ITensorInfo *output, const ActivationLayerInfo &act_info=ActivationLayerInfo())
Initialise the kernel's inputs, output.
void run (ITensorPack &tensors) override
Run the kernels contained in the function.
Public Member Functions inherited from ICLOperator
ICLOperator (IRuntimeContext *ctx=nullptr)
Constructor.
ICLOperator (const ICLOperator &)=delete
Prevent instances of this class from being copied (As this class contains pointers)
ICLOperator (ICLOperator &&)=default
Default move constructor.
ICLOperator & operator= (const ICLOperator &)=delete
Prevent instances of this class from being copied (As this class contains pointers)
ICLOperator & operator= (ICLOperator &&)=default
Default move assignment operator.
void run (ITensorPack &tensors) override
Run the kernels contained in the function.
void prepare (ITensorPack &constants) override
Prepare the function for executing.
MemoryRequirements workspace () const override
Return the memory requirements required by the workspace.
Public Member Functions inherited from IOperator
virtual ~IOperator ()=default
Destructor.
Static Public Member Functions
static Status validate (const ITensorInfo *input1, const ITensorInfo *input2, const ITensorInfo *output, const ActivationLayerInfo &act_info=ActivationLayerInfo())
Static function to check if given info will lead to a valid configuration of CLComplexPixelWiseMultiplication.
Detailed Description
Basic function to run CLComplexPixelWiseMultiplicationKernel.
Definition at line 113 of file CLPixelWiseMultiplication.h.
Constructor & Destructor Documentation
CLComplexPixelWiseMultiplication()
CLComplexPixelWiseMultiplication ()
Default Constructor.
Definition at line 93 of file CLPixelWiseMultiplication.cpp.
     : _border_handler()
 {
 }
Member Function Documentation
configure()
void configure (const CLCompileContext & compile_context, ITensorInfo * input1, ITensorInfo * input2, ITensorInfo * output, const ActivationLayerInfo & act_info = ActivationLayerInfo())
Initialise the kernel's inputs, output.
Parameters
[in] compile_context The compile context to be used.
[in,out] input1 An input tensor. Data types supported: F32. Number of channels supported: 2. The input tensor is [in, out] because its TensorInfo might be modified inside the kernel in case of broadcasting of dimension 0.
[in,out] input2 An input tensor. Data types supported: same as input1. Number of channels supported: same as input1. The input tensor is [in, out] because its TensorInfo might be modified inside the kernel in case of broadcasting of dimension 0.
[out] output The output tensor, Data types supported: same as input1. Number of channels supported: same as input1.
[in] act_info (Optional) Activation layer information in case of a fused activation.
Definition at line 98 of file CLPixelWiseMultiplication.cpp.
 {
     auto k = arm_compute::support::cpp14::make_unique<CLComplexPixelWiseMultiplicationKernel>();
     k->configure(compile_context, input1, input2, output, act_info);
     _kernel = std::move(k);
     if(output->dimension(0) > 1)
     {
         ITensorInfo *broadcasted_info = (input1->dimension(0) == 1) ? input1 : input2;
         if(broadcasted_info->dimension(0) == 1)
         {
             _border_handler.configure(compile_context, broadcasted_info, _kernel->border_size(), BorderMode::REPLICATE);
         }
     }
 }
References CLFillBorderKernel::configure(), ITensorInfo::dimension(), and arm_compute::REPLICATE.
run()
void run (ITensorPack & tensors) override virtual
Run the kernels contained in the function.
Parameters
[in] tensors Vector that contains the tensors to operate on.
Implements IOperator.
Definition at line 120 of file CLPixelWiseMultiplication.cpp.
 {
     auto border_pack = select_border_input(tensors);
     CLScheduler::get().enqueue_op(_border_handler, border_pack);
     ICLOperator::run(tensors);
 }
References CLScheduler::enqueue_op(), CLScheduler::get(), and ICLOperator::run().
validate()
Status validate (const ITensorInfo * input1, const ITensorInfo * input2, const ITensorInfo * output, const ActivationLayerInfo & act_info = ActivationLayerInfo()) static
Static function to check if given info will lead to a valid configuration of CLComplexPixelWiseMultiplication.
Parameters
[in] input1 An input tensor info. Data types supported: F32. Number of channels supported: 2.
[in] input2 An input tensor info. Data types supported: same as input1. Number of channels supported: same as input1.
[in] output The output tensor info, Data types supported: same as input1. Number of channels supported: same as input1.
[in] act_info (Optional) Activation layer information in case of a fused activation.
Definition at line 115 of file CLPixelWiseMultiplication.cpp.
 {
     return CLComplexPixelWiseMultiplicationKernel::validate(input1, input2, output, act_info);
 }
References CLComplexPixelWiseMultiplicationKernel::validate().
Referenced by CLComplexPixelWiseMultiplication::validate().
The documentation for this class was generated from the following files:
arm_compute/runtime/CL/functions/CLPixelWiseMultiplication.h
src/runtime/CL/functions/CLPixelWiseMultiplication.cpp