Compute Library: NEComputeAllAnchorsKernel Class Reference
NEComputeAllAnchorsKernel Class Reference
Interface for Compute All Anchors kernel.
#include <NEGenerateProposalsLayerKernel.h>
Public Member Functions
const char * name () const override
Name of the kernel.
NEComputeAllAnchorsKernel ()
Default constructor.
NEComputeAllAnchorsKernel (const NEComputeAllAnchorsKernel &)=delete
Prevent instances of this class from being copied (As this class contains pointers)
NEComputeAllAnchorsKernel & operator= (const NEComputeAllAnchorsKernel &)=delete
Prevent instances of this class from being copied (As this class contains pointers)
NEComputeAllAnchorsKernel (NEComputeAllAnchorsKernel &&)=default
Allow instances of this class to be moved.
NEComputeAllAnchorsKernel & operator= (NEComputeAllAnchorsKernel &&)=default
Allow instances of this class to be moved.
~NEComputeAllAnchorsKernel ()=default
Default destructor.
void configure (const ITensor *anchors, ITensor *all_anchors, const ComputeAnchorsInfo &info)
Set the input and output tensors.
void run (const Window &window, const ThreadInfo &info) override
Execute the kernel on the passed window.
Public Member Functions inherited from ICPPKernel
virtual ~ICPPKernel ()=default
Default destructor.
virtual void run_nd (const Window &window, const ThreadInfo &info, const Window &thread_locator)
legacy compatibility layer for implemantions which do not support thread_locator In these cases we simply narrow the interface down the legacy version
virtual void run_op (ITensorPack &tensors, const Window &window, const ThreadInfo &info)
Execute the kernel on the passed window.
Public Member Functions inherited from IKernel
IKernel ()
Constructor.
virtual ~IKernel ()=default
Destructor.
virtual bool is_parallelisable () const
Indicates whether or not the kernel is parallelisable.
virtual BorderSize border_size () const
The size of the border for that kernel.
const Window & window () const
The maximum window the kernel can be executed on.
Static Public Member Functions
static Status validate (const ITensorInfo *anchors, const ITensorInfo *all_anchors, const ComputeAnchorsInfo &info)
Static function to check if given info will lead to a valid configuration of NEComputeAllAnchorsKernel.
Detailed Description
Interface for Compute All Anchors kernel.
Definition at line 33 of file NEGenerateProposalsLayerKernel.h.
Constructor & Destructor Documentation
NEComputeAllAnchorsKernel() [1/3]
NEComputeAllAnchorsKernel ()
Default constructor.
Definition at line 66 of file NEGenerateProposalsLayerKernel.cpp.
     : _anchors(nullptr), _all_anchors(nullptr), _anchors_info(0.f, 0.f, 0.f)
 {
 }
NEComputeAllAnchorsKernel() [2/3]
NEComputeAllAnchorsKernel (const NEComputeAllAnchorsKernel &) delete
Prevent instances of this class from being copied (As this class contains pointers)
NEComputeAllAnchorsKernel() [3/3]
NEComputeAllAnchorsKernel (NEComputeAllAnchorsKernel &&) default
Allow instances of this class to be moved.
~NEComputeAllAnchorsKernel()
~NEComputeAllAnchorsKernel () default
Default destructor.
Member Function Documentation
configure()
void configure (const ITensor * anchors, ITensor * all_anchors, const ComputeAnchorsInfo & info)
Set the input and output tensors.
Parameters
[in] anchors Source tensor. Original set of anchors of size (4, A), where A is the number of anchors. Data types supported: QSYMM16/F16/F32
[out] all_anchors Destination tensor. Destination anchors of size (4, H*W*A) where H and W are the height and width of the feature map and A is the number of anchors. Data types supported: Same as input
[in] info Contains Compute Anchors operation information described in ComputeAnchorsInfo
Definition at line 71 of file NEGenerateProposalsLayerKernel.cpp.
 {
     ARM_COMPUTE_ERROR_ON_NULLPTR(anchors, all_anchors);
     ARM_COMPUTE_ERROR_THROW_ON(validate_arguments(anchors->info(), all_anchors->info(), info));
     // Metadata
     const size_t   num_anchors = anchors->info()->dimension(1);
     const DataType data_type   = anchors->info()->data_type();
     const float    width       = info.feat_width();
     const float    height      = info.feat_height();
     // Initialize the output if empty
     const TensorShape output_shape(info.values_per_roi(), width * height * num_anchors);
     auto_init_if_empty(*all_anchors->info(), TensorInfo(output_shape, 1, data_type, anchors->info()->quantization_info()));
     // Set instance variables
     _anchors      = anchors;
     _all_anchors  = all_anchors;
     _anchors_info = info;
     Window win = calculate_max_window(*all_anchors->info(), Steps(info.values_per_roi()));
     INEKernel::configure(win);
 }
References ARM_COMPUTE_ERROR_ON_NULLPTR, ARM_COMPUTE_ERROR_THROW_ON, arm_compute::auto_init_if_empty(), arm_compute::calculate_max_window(), ITensorInfo::data_type(), arm_compute::test::validation::data_type, ITensorInfo::dimension(), ITensor::info(), arm_compute::test::validation::info, arm_compute::test::validation::output_shape, ITensorInfo::quantization_info(), and arm_compute::validate_arguments().
Referenced by NEGenerateProposalsLayer::configure().
name()
const char* name () const inline override virtual
Name of the kernel.
Returns
Kernel name
Implements ICPPKernel.
Definition at line 36 of file NEGenerateProposalsLayerKernel.h.
     {
         return "NEComputeAllAnchorsKernel";
     }
operator=() [1/2]
NEComputeAllAnchorsKernel& operator= (const NEComputeAllAnchorsKernel &) delete
Prevent instances of this class from being copied (As this class contains pointers)
operator=() [2/2]
NEComputeAllAnchorsKernel& operator= (NEComputeAllAnchorsKernel &&) default
Allow instances of this class to be moved.
run()
void run (const Window & window, const ThreadInfo & info) override virtual
Execute the kernel on the passed window.
Warning
If is_parallelisable() returns false then the passed window must be equal to window()
Note
The window has to be a region within the window returned by the window() method
The width of the window has to be a multiple of num_elems_processed_per_iteration().
Parameters
[in] window Region on which to execute the kernel. (Must be a region of the window returned by window())
[in] info Info about executing thread and CPU.
Reimplemented from ICPPKernel.
Definition at line 167 of file NEGenerateProposalsLayerKernel.cpp.
 {
     ARM_COMPUTE_UNUSED(info);
     ARM_COMPUTE_ERROR_ON_UNCONFIGURED_KERNEL(this);
     ARM_COMPUTE_ERROR_ON_INVALID_SUBWINDOW(INEKernel::window(), window);
     switch(_anchors->info()->data_type())
     {
         case DataType::QSYMM16:
         {
             internal_run<int16_t>(window);
             break;
         }
 #ifdef __ARM_FEATURE_FP16_VECTOR_ARITHMETIC
         case DataType::F16:
         {
             internal_run<float16_t>(window);
             break;
         }
 #endif // __ARM_FEATURE_FP16_VECTOR_ARITHMETIC
         case DataType::F32:
         {
             internal_run<float>(window);
             break;
         }
         default:
         {
             ARM_COMPUTE_ERROR("Data type not supported");
         }
     }
 }
References ARM_COMPUTE_ERROR, ARM_COMPUTE_ERROR_ON_INVALID_SUBWINDOW, ARM_COMPUTE_ERROR_ON_UNCONFIGURED_KERNEL, ARM_COMPUTE_UNUSED, ITensorInfo::data_type(), arm_compute::F16, arm_compute::F32, ITensor::info(), arm_compute::test::validation::info, arm_compute::QSYMM16, and IKernel::window().
validate()
Status validate (const ITensorInfo * anchors, const ITensorInfo * all_anchors, const ComputeAnchorsInfo & info) static
Static function to check if given info will lead to a valid configuration of NEComputeAllAnchorsKernel.
Parameters
[in] anchors Source tensor info. Original set of anchors of size (4, A), where A is the number of anchors. Data types supported: QSYMM16/F16/F32
[in] all_anchors Destination tensor info. Destination anchors of size (4, H*W*A) where H and W are the height and width of the feature map and A is the number of anchors. Data types supported: Same as input
[in] info Contains Compute Anchors operation information described in ComputeAnchorsInfo
Returns
a Status
Definition at line 96 of file NEGenerateProposalsLayerKernel.cpp.
 {
     ARM_COMPUTE_RETURN_ON_ERROR(validate_arguments(anchors, all_anchors, info));
     return Status{};
 }
References ARM_COMPUTE_RETURN_ON_ERROR, arm_compute::test::validation::info, and arm_compute::validate_arguments().
Referenced by NEComputeAllAnchors::validate(), and NEGenerateProposalsLayer::validate().
The documentation for this class was generated from the following files:
arm_compute/core/NEON/kernels/NEGenerateProposalsLayerKernel.h
src/core/NEON/kernels/NEGenerateProposalsLayerKernel.cpp