Compute Library: CLConcatenation Class Reference
CLConcatenation Class Reference
Basic function to execute concatenate tensors along a given axis.
#include <CLConcatenateLayer.h>
Public Member Functions
CLConcatenation ()
Default constructor.
void configure (const CLCompileContext &compile_context, const std::vector< ITensorInfo * > &inputs_vector, ITensorInfo *output, size_t axis)
Initialise the kernel's inputs vector and output.
void run (ITensorPack &tensors) override
Run the kernels contained in the function.
Public Member Functions inherited from ICLOperator
ICLOperator (IRuntimeContext *ctx=nullptr)
Constructor.
ICLOperator (const ICLOperator &)=delete
Prevent instances of this class from being copied (As this class contains pointers)
ICLOperator (ICLOperator &&)=default
Default move constructor.
ICLOperator & operator= (const ICLOperator &)=delete
Prevent instances of this class from being copied (As this class contains pointers)
ICLOperator & operator= (ICLOperator &&)=default
Default move assignment operator.
void run (ITensorPack &tensors) override
Run the kernels contained in the function.
void prepare (ITensorPack &constants) override
Prepare the function for executing.
MemoryRequirements workspace () const override
Return the memory requirements required by the workspace.
Public Member Functions inherited from IOperator
virtual ~IOperator ()=default
Destructor.
Static Public Member Functions
static Status validate (const std::vector< const ITensorInfo * > &inputs_vector, const ITensorInfo *output, size_t axis)
Static function to check if given info will lead to a valid configuration of NEConcatenateLayer.
Detailed Description
Basic function to execute concatenate tensors along a given axis.
This function calls the following kernels:
CLWidthConcatenateLayerKernel (if underlying concatenation axis is 0).
CLHeightConcatenateLayerKernel (if underlying concatenation axis is 1).
CLDepthConcatenateLayerKernel (if underlying concatenation axis is 2).
CLBatchConcatenateLayerKernel (if underlying concatenation axis is 3).
Definition at line 116 of file CLConcatenateLayer.h.
Constructor & Destructor Documentation
CLConcatenation()
CLConcatenation ()
Default constructor.
Definition at line 45 of file CLConcatenateLayer.cpp.
     : _concat_kernels(),
       _num_inputs(0),
       _axis(Window::DimX)
 {
 }
Member Function Documentation
configure()
void configure (const CLCompileContext & compile_context, const std::vector< ITensorInfo * > & inputs_vector, ITensorInfo * output, size_t axis)
Initialise the kernel's inputs vector and output.
Note
Input and output tensor dimensions preconditions defer depending on the concatenation axis.
Preconditions can be found respectively at CLWidthConcatenateLayerKernel, CLHeightConcatenateLayerKernel and CLDepthConcatenateLayerKernel.
Parameters
[in] compile_context The compile context to be used.
[in,out] inputs_vector The vectors containing all the tensors to concatenate. Data types supported: All
[out] output Output tensor. Data types supported: Same as input.
[in] axis Concatenation axis. Supported underlying concatenation axis are 0, 1, 2 and 3.
Definition at line 52 of file CLConcatenateLayer.cpp.
 {
     ARM_COMPUTE_ERROR_ON(output == nullptr);
     _axis       = axis;
     _num_inputs = inputs_vector.size();
     TensorShape                      output_shape = arm_compute::misc::shape_calculator::calculate_concatenate_shape(inputs_vector, _axis);
     std::vector<const ITensorInfo *> const_inputs_vector(inputs_vector.size());
     std::transform(inputs_vector.begin(), inputs_vector.end(), const_inputs_vector.begin(), [](ITensorInfo * t)
     {
         ARM_COMPUTE_ERROR_ON_NULLPTR(t);
         return t;
     });
     // Output auto inizialitation if not yet initialized
     auto_init_if_empty(*output, output_shape, 1, inputs_vector[0]->data_type());
     ARM_COMPUTE_ERROR_THROW_ON(CLConcatenateLayer::validate(const_inputs_vector, output, axis));
     unsigned int offset = 0;
     switch(_axis)
     {
         case Window::DimX:
         {
             switch(_num_inputs)
             {
                 case 2:
                 {
                     // Configure WidthConcatenate2Tensors kernel
                     auto kernel = support::cpp14::make_unique<CLWidthConcatenate2TensorsKernel>();
                     kernel->configure(compile_context, inputs_vector.at(0), inputs_vector.at(1), output);
                     _concat_kernels.emplace_back(std::move(kernel));
                     break;
                 }
                 case 4:
                 {
                     // Configure WidthConcatenate4Tensors kernel
                     auto kernel = support::cpp14::make_unique<CLWidthConcatenate4TensorsKernel>();
                     kernel->configure(compile_context, inputs_vector.at(0), inputs_vector.at(1), inputs_vector.at(2), inputs_vector.at(3), output);
                     _concat_kernels.emplace_back(std::move(kernel));
                     break;
                 }
                 default:
                 {
                     // Configure generic case WidthConcatenate kernels
                     for(unsigned int i = 0; i < _num_inputs; ++i)
                     {
                         auto kernel = support::cpp14::make_unique<CLWidthConcatenateLayerKernel>();
                         kernel->configure(compile_context, inputs_vector.at(i), offset, output);
                         offset += inputs_vector.at(i)->dimension(_axis);
                         _concat_kernels.emplace_back(std::move(kernel));
                     }
                     break;
                 }
             }
             break;
         }
         case Window::DimY:
         {
             for(unsigned int i = 0; i < _num_inputs; ++i)
             {
                 auto kernel = support::cpp14::make_unique<CLHeightConcatenateLayerKernel>();
                 kernel->configure(compile_context, inputs_vector.at(i), offset, output);
                 offset += inputs_vector.at(i)->dimension(_axis);
                 _concat_kernels.emplace_back(std::move(kernel));
             }
             break;
         }
         case Window::DimZ:
         {
             for(unsigned int i = 0; i < _num_inputs; ++i)
             {
                 auto kernel = support::cpp14::make_unique<CLDepthConcatenateLayerKernel>();
                 kernel->configure(compile_context, inputs_vector.at(i), offset, output);
                 offset += inputs_vector.at(i)->dimension(_axis);
                 _concat_kernels.emplace_back(std::move(kernel));
             }
             break;
         }
         case 3:
         {
             for(unsigned int i = 0; i < _num_inputs; ++i)
             {
                 auto kernel = support::cpp14::make_unique<CLBatchConcatenateLayerKernel>();
                 kernel->configure(compile_context, inputs_vector.at(i), offset, output);
                 offset += inputs_vector.at(i)->dimension(_axis);
                 _concat_kernels.emplace_back(std::move(kernel));
             }
             break;
         }
         default:
             ARM_COMPUTE_ERROR("Axis not supported");
     }
 }
References ARM_COMPUTE_ERROR, ARM_COMPUTE_ERROR_ON, ARM_COMPUTE_ERROR_ON_NULLPTR, ARM_COMPUTE_ERROR_THROW_ON, arm_compute::auto_init_if_empty(), arm_compute::test::validation::axis, arm_compute::misc::shape_calculator::calculate_concatenate_shape(), arm_compute::test::validation::data_type, Window::DimX, Window::DimY, Window::DimZ, offset(), arm_compute::test::validation::output_shape, and CLConcatenateLayer::validate().
run()
void run (ITensorPack & tensors) override virtual
Run the kernels contained in the function.
Parameters
[in] tensors Vector that contains the tensors to operate on.
Implements IOperator.
Definition at line 223 of file CLConcatenateLayer.cpp.
 {
     if(tensors.empty())
     {
         ARM_COMPUTE_ERROR("No inputs provided");
     }
     if(static_cast<int>(tensors.size()) - 1 != static_cast<int>(_num_inputs))
     {
         ARM_COMPUTE_ERROR("Configured with different number of inputs");
     }
     if(_axis == Window::DimX && (_num_inputs == 2 || _num_inputs == 4))
     {
         ARM_COMPUTE_ERROR_ON(_concat_kernels.empty());
         CLScheduler::get().enqueue_op(*_concat_kernels.at(0), tensors, true);
     }
     else
     {
         int i = 0;
         for(auto &k : _concat_kernels)
         {
             ITensorPack pack;
             pack.add_tensor(TensorType::ACL_SRC, tensors.get_const_tensor(ACL_SRC_VEC + i));
             pack.add_tensor(TensorType::ACL_DST, tensors.get_tensor(ACL_DST));
             CLScheduler::get().enqueue_op(*k, pack, true);
             ++i;
         }
     }
 }
References arm_compute::ACL_DST, arm_compute::ACL_SRC, arm_compute::ACL_SRC_VEC, ITensorPack::add_tensor(), ARM_COMPUTE_ERROR, ARM_COMPUTE_ERROR_ON, Window::DimX, ITensorPack::empty(), CLScheduler::enqueue_op(), CLScheduler::get(), ITensorPack::get_const_tensor(), ITensorPack::get_tensor(), and ITensorPack::size().
validate()
Status validate (const std::vector< const ITensorInfo * > & inputs_vector, const ITensorInfo * output, size_t axis) static
Static function to check if given info will lead to a valid configuration of NEConcatenateLayer.
Note
Input and output tensor dimensions preconditions defer depending on the concatenation axis.
Preconditions can be found respectively at CLWidthConcatenateLayerKernel, CLHeightConcatenateLayerKernel and CLDepthConcatenateLayerKernel.
Parameters
[in] inputs_vector The vectors containing all the tensors info to concatenate. Data types supported: All
[in] output Output tensor info. Data types supported: Same as input.
[in] axis Concatenation axis. Supported underlying concatenation axis are 0, 1, 2 and 3.
Returns
a status
Definition at line 146 of file CLConcatenateLayer.cpp.
 {
     ARM_COMPUTE_RETURN_ERROR_ON(output == nullptr);
     const unsigned int num_inputs = inputs_vector.size();
     ARM_COMPUTE_RETURN_ERROR_ON_NULLPTR(output);
     ARM_COMPUTE_RETURN_ERROR_ON(num_inputs < 2);
     unsigned int offset = 0;
     switch(axis)
     {
         case Window::DimX:
         {
             switch(num_inputs)
             {
                 case 2:
                     // Validate WidthConcatenate2Tensors kernels if there are 2 inputs
                     ARM_COMPUTE_RETURN_ERROR_ON_NULLPTR(inputs_vector[0], inputs_vector[1]);
                     ARM_COMPUTE_RETURN_ON_ERROR(CLWidthConcatenate2TensorsKernel::validate(inputs_vector[0], inputs_vector[1], output));
                     break;
                 case 4:
                     // Validate WidthConcatenate4Tensors kernels if there are 4 inputs
                     ARM_COMPUTE_RETURN_ERROR_ON_NULLPTR(inputs_vector[0], inputs_vector[1], inputs_vector[2], inputs_vector[3]);
                     ARM_COMPUTE_RETURN_ON_ERROR(CLWidthConcatenate4TensorsKernel::validate(inputs_vector[0], inputs_vector[1], inputs_vector[2], inputs_vector[3], output));
                     break;
                 default:
                     // Validate generic case of WidthConcatenate kernel
                     for(const auto &input : inputs_vector)
                     {
                         ARM_COMPUTE_RETURN_ERROR_ON_NULLPTR(input);
                         ARM_COMPUTE_RETURN_ON_ERROR(CLWidthConcatenateLayerKernel::validate(input, offset, output));
                         offset += input->dimension(axis);
                     }
                     break;
             }
             break;
         }
         case Window::DimY:
         {
             for(const auto &input : inputs_vector)
             {
                 ARM_COMPUTE_RETURN_ON_ERROR(CLHeightConcatenateLayerKernel::validate(input, offset, output));
                 offset += input->dimension(axis);
             }
             break;
         }
         case Window::DimZ:
         {
             for(const auto &input : inputs_vector)
             {
                 ARM_COMPUTE_RETURN_ON_ERROR(CLDepthConcatenateLayerKernel::validate(input, offset, output));
                 offset += input->dimension(axis);
             }
             break;
         }
         case 3:
         {
             for(const auto &input : inputs_vector)
             {
                 ARM_COMPUTE_RETURN_ON_ERROR(CLBatchConcatenateLayerKernel::validate(input, offset, output));
                 offset += input->dimension(axis);
             }
             break;
         }
         default:
             ARM_COMPUTE_ERROR("Axis not supported");
     }
     if(output->total_size() != 0)
     {
         TensorShape output_shape = arm_compute::misc::shape_calculator::calculate_concatenate_shape(inputs_vector, axis);
         ARM_COMPUTE_RETURN_ERROR_ON(output_shape.total_size() != output->tensor_shape().total_size());
     }
     return Status{};
 }
References ARM_COMPUTE_ERROR, ARM_COMPUTE_RETURN_ERROR_ON, ARM_COMPUTE_RETURN_ERROR_ON_NULLPTR, ARM_COMPUTE_RETURN_ON_ERROR, arm_compute::test::validation::axis, arm_compute::misc::shape_calculator::calculate_concatenate_shape(), Window::DimX, Window::DimY, Window::DimZ, arm_compute::test::validation::input, offset(), arm_compute::test::validation::output_shape, ITensorInfo::tensor_shape(), TensorShape::total_size(), ITensorInfo::total_size(), CLWidthConcatenate2TensorsKernel::validate(), CLWidthConcatenateLayerKernel::validate(), CLHeightConcatenateLayerKernel::validate(), CLWidthConcatenate4TensorsKernel::validate(), CLDepthConcatenateLayerKernel::validate(), and CLBatchConcatenateLayerKernel::validate().
Referenced by CLConcatenateLayer::validate().
The documentation for this class was generated from the following files:
arm_compute/runtime/CL/functions/CLConcatenateLayer.h
src/runtime/CL/functions/CLConcatenateLayer.cpp