Compute Library: CLConvolutionRectangleKernel Class Reference
CLConvolutionRectangleKernel Class Reference
Kernel for the running convolution on a rectangle matrix.
#include <CLConvolutionKernel.h>
Public Member Functions
CLConvolutionRectangleKernel ()
Default constructor.
CLConvolutionRectangleKernel (const CLConvolutionRectangleKernel &)=delete
Prevent instances of this class from being copied (As this class contains pointers)
CLConvolutionRectangleKernel & operator= (const CLConvolutionRectangleKernel &)=delete
Prevent instances of this class from being copied (As this class contains pointers)
CLConvolutionRectangleKernel (CLConvolutionRectangleKernel &&)=default
Allow instances of this class to be moved.
CLConvolutionRectangleKernel & operator= (CLConvolutionRectangleKernel &&)=default
Allow instances of this class to be moved.
void configure (const ICLTensor *input, ICLTensor *output, const int16_t *conv, uint32_t width, uint32_t height, uint32_t scale, bool border_undefined)
Initialise the kernel's input, output and border mode.
void configure (const CLCompileContext &compile_context, const ICLTensor *input, ICLTensor *output, const int16_t *conv, uint32_t width, uint32_t height, uint32_t scale, bool border_undefined)
Initialise the kernel's input, output and border mode.
void run (const Window &window, cl::CommandQueue &queue) override
Enqueue the OpenCL kernel to process the given window on the passed OpenCL command queue.
BorderSize border_size () const override
The size of the border for that kernel.
Public Member Functions inherited from ICLKernel
ICLKernel ()
Constructor.
cl::Kernel & kernel ()
Returns a reference to the OpenCL kernel of this object.
template<typename T >
void add_1D_array_argument (unsigned int &idx, const ICLArray< T > *array, const Strides &strides, unsigned int num_dimensions, const Window &window)
Add the passed 1D array's parameters to the object's kernel's arguments starting from the index idx.
void add_1D_tensor_argument (unsigned int &idx, const ICLTensor *tensor, const Window &window)
Add the passed 1D tensor's parameters to the object's kernel's arguments starting from the index idx.
void add_1D_tensor_argument_if (bool cond, unsigned int &idx, const ICLTensor *tensor, const Window &window)
Add the passed 1D tensor's parameters to the object's kernel's arguments starting from the index idx if the condition is true.
void add_2D_tensor_argument (unsigned int &idx, const ICLTensor *tensor, const Window &window)
Add the passed 2D tensor's parameters to the object's kernel's arguments starting from the index idx.
void add_2D_tensor_argument_if (bool cond, unsigned int &idx, const ICLTensor *tensor, const Window &window)
Add the passed 2D tensor's parameters to the object's kernel's arguments starting from the index idx if the condition is true.
void add_3D_tensor_argument (unsigned int &idx, const ICLTensor *tensor, const Window &window)
Add the passed 3D tensor's parameters to the object's kernel's arguments starting from the index idx.
void add_4D_tensor_argument (unsigned int &idx, const ICLTensor *tensor, const Window &window)
Add the passed 4D tensor's parameters to the object's kernel's arguments starting from the index idx.
virtual void run_op (ITensorPack &tensors, const Window &window, cl::CommandQueue &queue)
Enqueue the OpenCL kernel to process the given window on the passed OpenCL command queue.
template<typename T >
void add_argument (unsigned int &idx, T value)
Add the passed parameters to the object's kernel's arguments starting from the index idx.
void set_lws_hint (const cl::NDRange &lws_hint)
Set the Local-Workgroup-Size hint.
cl::NDRange lws_hint () const
Return the Local-Workgroup-Size hint.
const std::string & config_id () const
Get the configuration ID.
void set_target (GPUTarget target)
Set the targeted GPU architecture.
void set_target (cl::Device &device)
Set the targeted GPU architecture according to the CL device.
GPUTarget get_target () const
Get the targeted GPU architecture.
size_t get_max_workgroup_size ()
Get the maximum workgroup size for the device the CLKernelLibrary uses.
template<typename T , unsigned int dimension_size>
void add_array_argument (unsigned &idx, const ICLArray< T > *array, const Strides &strides, unsigned int num_dimensions, const Window &window)
Add the passed array's parameters to the object's kernel's arguments starting from the index idx.
template<unsigned int dimension_size>
void add_tensor_argument (unsigned &idx, const ICLTensor *tensor, const Window &window)
Public Member Functions inherited from IKernel
IKernel ()
Constructor.
virtual ~IKernel ()=default
Destructor.
virtual bool is_parallelisable () const
Indicates whether or not the kernel is parallelisable.
const Window & window () const
The maximum window the kernel can be executed on.
Additional Inherited Members
Static Public Member Functions inherited from ICLKernel
static constexpr unsigned int num_arguments_per_1D_array ()
Returns the number of arguments enqueued per 1D array object.
static constexpr unsigned int num_arguments_per_1D_tensor ()
Returns the number of arguments enqueued per 1D tensor object.
static constexpr unsigned int num_arguments_per_2D_tensor ()
Returns the number of arguments enqueued per 2D tensor object.
static constexpr unsigned int num_arguments_per_3D_tensor ()
Returns the number of arguments enqueued per 3D tensor object.
static constexpr unsigned int num_arguments_per_4D_tensor ()
Returns the number of arguments enqueued per 4D tensor object.
static cl::NDRange gws_from_window (const Window &window)
Get the global work size given an execution window.
Detailed Description
Kernel for the running convolution on a rectangle matrix.
Note
Supports combinations of 3,5,7 and 9.
Definition at line 177 of file CLConvolutionKernel.h.
Constructor & Destructor Documentation
CLConvolutionRectangleKernel() [1/3]
CLConvolutionRectangleKernel ()
Default constructor.
Definition at line 291 of file CLConvolutionKernel.cpp.
     : _border_size(0), _input(nullptr), _output(nullptr)
 {
 }
CLConvolutionRectangleKernel() [2/3]
CLConvolutionRectangleKernel (const CLConvolutionRectangleKernel &) delete
Prevent instances of this class from being copied (As this class contains pointers)
CLConvolutionRectangleKernel() [3/3]
CLConvolutionRectangleKernel (CLConvolutionRectangleKernel &&) default
Allow instances of this class to be moved.
Member Function Documentation
border_size()
BorderSize border_size () const override virtual
The size of the border for that kernel.
Returns
The width in number of elements of the border.
Reimplemented from IKernel.
Definition at line 296 of file CLConvolutionKernel.cpp.
 {
     return _border_size;
 }
Referenced by CLConvolutionRectangleKernel::configure().
configure() [1/2]
void configure (const ICLTensor * input, ICLTensor * output, const int16_t * conv, uint32_t width, uint32_t height, uint32_t scale, bool border_undefined)
Initialise the kernel's input, output and border mode.
Parameters
[in] input Source tensor. Data types supported: U8.
[out] output Destination tensor, Data types supported: U8, S16.
[in] conv Convolution matrix to apply to the input tensor.
[in] width Width of convolution matrix (Number of columns)
[in] height Height of convolution matrix (Number of rows)
[in] scale Scale of the convolution matrix. If 0 is passed, it will be set to the sum of the coefficients of the convolution or 1 if they add up to 0.
[in] border_undefined True if the border mode is undefined. False if it's replicate or constant.
Definition at line 301 of file CLConvolutionKernel.cpp.
 {
     configure(CLKernelLibrary::get().get_compile_context(), input, output, conv, width, height, scale, border_undefined);
 }
References arm_compute::test::validation::conv, CLKernelLibrary::get(), arm_compute::test::validation::input, and arm_compute::test::validation::reference::scale().
configure() [2/2]
void configure (const CLCompileContext & compile_context, const ICLTensor * input, ICLTensor * output, const int16_t * conv, uint32_t width, uint32_t height, uint32_t scale, bool border_undefined)
Initialise the kernel's input, output and border mode.
Parameters
[in] compile_context The compile context to be used.
[in] input Source tensor. Data types supported: U8.
[out] output Destination tensor, Data types supported: U8, S16.
[in] conv Convolution matrix to apply to the input tensor.
[in] width Width of convolution matrix (Number of columns)
[in] height Height of convolution matrix (Number of rows)
[in] scale Scale of the convolution matrix. If 0 is passed, it will be set to the sum of the coefficients of the convolution or 1 if they add up to 0.
[in] border_undefined True if the border mode is undefined. False if it's replicate or constant.
Definition at line 306 of file CLConvolutionKernel.cpp.
 {
     ARM_COMPUTE_ERROR_ON_DATA_TYPE_CHANNEL_NOT_IN(input, 1, DataType::U8);
     ARM_COMPUTE_ERROR_ON_DATA_TYPE_CHANNEL_NOT_IN(output, 1, DataType::U8, DataType::S16);
     ARM_COMPUTE_ERROR_ON(nullptr == conv);
     ARM_COMPUTE_ERROR_ON(3 != width && 5 != width && 7 != width && 9 != width);
     ARM_COMPUTE_ERROR_ON(3 != height && 5 != height && 7 != height && 9 != height);
     ARM_COMPUTE_ERROR_ON(0 == scale);
     _input       = input;
     _output      = output;
     _border_size = BorderSize(height / 2, width / 2);
     std::set<std::string> options;
     std::stringstream output_type;
     output_type << "-DDATA_TYPE_OUT=" << get_cl_type_from_data_type(output->info()->data_type());
     options.insert(output_type.str());
     uint32_t matrix_size = width * height;
     std::array<int16_t, max_matrix_size> mat = { 0 };
     memcpy(mat.data(), conv, matrix_size * sizeof(int16_t));
     for(unsigned int j = 0; j < max_matrix_size; j++)
     {
         options.insert("-DMAT" + support::cpp11::to_string(j) + "=" + support::cpp11::to_string(mat[j]));
     }
     options.insert("-DSCALE=" + support::cpp11::to_string(scale));
     DataType data_type = data_type_for_convolution_matrix(conv, matrix_size);
     options.insert("-DDATA_TYPE=" + get_cl_type_from_data_type(data_type));
     options.insert("-DMATRIX_WIDTH=" + support::cpp11::to_string(width));
     options.insert("-DMATRIX_HEIGHT=" + support::cpp11::to_string(height));
     _kernel = create_kernel(compile_context, "convolution_rectangle", options);
     // Configure kernel window
     constexpr unsigned int num_elems_processed_per_iteration = 8;
     constexpr unsigned int num_elems_read_per_iteration      = 16;
     constexpr unsigned int num_elems_written_per_iteration   = 8;
     const unsigned int     num_rows_read_per_iteration       = height;
     Window win = calculate_max_window(*input->info(), Steps(num_elems_processed_per_iteration), border_undefined, border_size());
     AccessWindowRectangle  input_access(input->info(), -border_size().left, -border_size().top, num_elems_read_per_iteration, num_rows_read_per_iteration);
     AccessWindowHorizontal output_access(output->info(), 0, num_elems_written_per_iteration);
     update_window_and_padding(win, input_access, output_access);
     output_access.set_valid_region(win, input->info()->valid_region(), border_undefined, border_size());
     ICLKernel::configure_internal(win);
 }
References ARM_COMPUTE_ERROR_ON, ARM_COMPUTE_ERROR_ON_DATA_TYPE_CHANNEL_NOT_IN, CLConvolutionRectangleKernel::border_size(), arm_compute::calculate_max_window(), arm_compute::test::validation::conv, arm_compute::create_kernel(), ITensorInfo::data_type(), arm_compute::test::validation::data_type, arm_compute::data_type_for_convolution_matrix(), arm_compute::get_cl_type_from_data_type(), ITensor::info(), arm_compute::test::validation::input, BorderSize::left, num_elems_processed_per_iteration, arm_compute::S16, arm_compute::test::validation::reference::scale(), arm_compute::support::cpp11::to_string(), BorderSize::top, arm_compute::U8, and arm_compute::update_window_and_padding().
operator=() [1/2]
CLConvolutionRectangleKernel& operator= (const CLConvolutionRectangleKernel &) delete
Prevent instances of this class from being copied (As this class contains pointers)
operator=() [2/2]
CLConvolutionRectangleKernel& operator= (CLConvolutionRectangleKernel &&) default
Allow instances of this class to be moved.
run()
void run (const Window & window, cl::CommandQueue & queue) override virtual
Enqueue the OpenCL kernel to process the given window on the passed OpenCL command queue.
Note
The queue is not flushed by this method, and therefore the kernel will not have been executed by the time this method returns.
Parameters
[in] window Region on which to execute the kernel. (Must be a valid region of the window returned by window()).
[in,out] queue Command queue on which to enqueue the kernel.
Reimplemented from ICLKernel.
Definition at line 365 of file CLConvolutionKernel.cpp.
 {
     ARM_COMPUTE_ERROR_ON_UNCONFIGURED_KERNEL(this);
     ARM_COMPUTE_ERROR_ON_INVALID_SUBWINDOW(IKernel::window(), window);
     Window slice = window.first_slice_window_2D();
     do
     {
         unsigned int idx = 0;
         add_2D_tensor_argument(idx, _input, slice);
         add_2D_tensor_argument(idx, _output, slice);
         enqueue(queue, *this, slice, lws_hint());
     }
     while(window.slide_window_slice_2D(slice));
 }
References ICLKernel::add_2D_tensor_argument(), ARM_COMPUTE_ERROR_ON_INVALID_SUBWINDOW, ARM_COMPUTE_ERROR_ON_UNCONFIGURED_KERNEL, arm_compute::enqueue(), Window::first_slice_window_2D(), ICLKernel::lws_hint(), arm_compute::test::validation::reference::slice(), Window::slide_window_slice_2D(), and IKernel::window().
The documentation for this class was generated from the following files:
arm_compute/core/CL/kernels/CLConvolutionKernel.h
src/core/CL/kernels/CLConvolutionKernel.cpp