Compute Library: NEQuantizationLayerKernel Class Reference
NEQuantizationLayerKernel Class Reference
Interface for the quantization layer kernel.
#include <NEQuantizationLayerKernel.h>
Public Member Functions
const char * name () const override
Name of the kernel.
NEQuantizationLayerKernel ()
Default constructor.
NEQuantizationLayerKernel (const NEQuantizationLayerKernel &)=delete
Prevent instances of this class from being copied (As this class contains pointers)
NEQuantizationLayerKernel & operator= (const NEQuantizationLayerKernel &)=delete
Prevent instances of this class from being copied (As this class contains pointers)
NEQuantizationLayerKernel (NEQuantizationLayerKernel &&)=default
Default Move Constructor.
NEQuantizationLayerKernel & operator= (NEQuantizationLayerKernel &&)=default
Default move assignment operator.
~NEQuantizationLayerKernel ()=default
Default destructor.
void configure (const ITensor *input, ITensor *output)
Set the input, output.
void run (const Window &window, const ThreadInfo &info) override
Execute the kernel on the passed window.
Public Member Functions inherited from ICPPKernel
virtual ~ICPPKernel ()=default
Default destructor.
virtual void run_nd (const Window &window, const ThreadInfo &info, const Window &thread_locator)
legacy compatibility layer for implemantions which do not support thread_locator In these cases we simply narrow the interface down the legacy version
virtual void run_op (ITensorPack &tensors, const Window &window, const ThreadInfo &info)
Execute the kernel on the passed window.
Public Member Functions inherited from IKernel
IKernel ()
Constructor.
virtual ~IKernel ()=default
Destructor.
virtual bool is_parallelisable () const
Indicates whether or not the kernel is parallelisable.
virtual BorderSize border_size () const
The size of the border for that kernel.
const Window & window () const
The maximum window the kernel can be executed on.
Static Public Member Functions
static Status validate (const ITensorInfo *input, const ITensorInfo *output)
Static function to check if given info will lead to a valid configuration of NEQuantizationLayerKernel.
Detailed Description
Interface for the quantization layer kernel.
Note
The implementation supports only 3D input tensors
Definition at line 38 of file NEQuantizationLayerKernel.h.
Constructor & Destructor Documentation
NEQuantizationLayerKernel() [1/3]
NEQuantizationLayerKernel ()
Default constructor.
Definition at line 105 of file NEQuantizationLayerKernel.cpp.
     : _input(nullptr), _output(nullptr), _func(nullptr)
 {
 }
NEQuantizationLayerKernel() [2/3]
NEQuantizationLayerKernel (const NEQuantizationLayerKernel &) delete
Prevent instances of this class from being copied (As this class contains pointers)
NEQuantizationLayerKernel() [3/3]
NEQuantizationLayerKernel (NEQuantizationLayerKernel &&) default
Default Move Constructor.
~NEQuantizationLayerKernel()
~NEQuantizationLayerKernel () default
Default destructor.
Member Function Documentation
configure()
void configure (const ITensor * input, ITensor * output)
Set the input, output.
Parameters
[in] input Source tensor. The dimensions over the third will be interpreted as batches. Data types supported: QASYMM8/QASYMM8_SIGNED/F32/F16.
[out] output Destination tensor with the same dimensions of input. Data types supported: QASYMM8/QASYMM8_SIGNED/QASYMM16.
Note
Output auto initialization is not supported by this kernel
Definition at line 110 of file NEQuantizationLayerKernel.cpp.
 {
     ARM_COMPUTE_ERROR_ON_NULLPTR(input, output);
     ARM_COMPUTE_ERROR_THROW_ON(validate_arguments(input->info(), output->info()));
     _input  = input;
     _output = output;
     static const std::map<std::string, QuantizationFunctionExecutorPtr> quant_map =
     {
         { "op_QASYMM8_QASYMM8", &NEQuantizationLayerKernel::run_quantize_qasymm8<uint8_t, uint8_t> },
         { "op_QASYMM8_QASYMM8_SIGNED", &NEQuantizationLayerKernel::run_quantize_qasymm8<uint8_t, int8_t> },
         { "op_QASYMM8_QASYMM16", &NEQuantizationLayerKernel::run_quantize_qasymm16<uint8_t> },
         { "op_QASYMM8_SIGNED_QASYMM8", &NEQuantizationLayerKernel::run_quantize_qasymm8<int8_t, uint8_t> },
         { "op_QASYMM8_SIGNED_QASYMM8_SIGNED", &NEQuantizationLayerKernel::run_quantize_qasymm8<int8_t, int8_t> },
         { "op_QASYMM8_SIGNED_QASYMM16", &NEQuantizationLayerKernel::run_quantize_qasymm16<int8_t> },
         { "op_F32_QASYMM8", &NEQuantizationLayerKernel::run_quantize_qasymm8<float, uint8_t> },
         { "op_F32_QASYMM8_SIGNED", &NEQuantizationLayerKernel::run_quantize_qasymm8<float, int8_t> },
         { "op_F32_QASYMM16", &NEQuantizationLayerKernel::run_quantize_qasymm16<float> },
 #ifdef __ARM_FEATURE_FP16_VECTOR_ARITHMETIC
         { "op_F16_QASYMM8", &NEQuantizationLayerKernel::run_quantize_qasymm8<float16_t, uint8_t> },
         { "op_F16_QASYMM8_SIGNED", &NEQuantizationLayerKernel::run_quantize_qasymm8<float16_t, int8_t> },
         { "op_F16_QASYMM16", &NEQuantizationLayerKernel::run_quantize_qasymm16<float16_t> },
 #endif /* __ARM_FEATURE_FP16_VECTOR_ARITHMETIC*/
     };
     std::string function_to_call("op_");
     function_to_call += string_from_data_type(_input->info()->data_type()) + "_";
     function_to_call += string_from_data_type(_output->info()->data_type());
     auto it = quant_map.find(function_to_call);
     if(it == quant_map.end())
     {
         ARM_COMPUTE_ERROR("Unsupported combination of input and output data types");
     }
     _func = it->second;
     // Configure kernel window
     Window win_config = calculate_max_window(*input->info(), Steps());
     Coordinates coord;
     coord.set_num_dimensions(output->info()->num_dimensions());
     output->info()->set_valid_region(ValidRegion(coord, output->info()->tensor_shape()));
     INEKernel::configure(win_config);
 }
References ARM_COMPUTE_ERROR, ARM_COMPUTE_ERROR_ON_NULLPTR, ARM_COMPUTE_ERROR_THROW_ON, arm_compute::calculate_max_window(), ITensorInfo::data_type(), ITensor::info(), arm_compute::test::validation::input, ITensorInfo::num_dimensions(), Dimensions< T >::set_num_dimensions(), ITensorInfo::set_valid_region(), arm_compute::string_from_data_type(), ITensorInfo::tensor_shape(), and arm_compute::validate_arguments().
Referenced by NEGenerateProposalsLayer::configure().
name()
const char* name () const inline override virtual
Name of the kernel.
Returns
Kernel name
Implements ICPPKernel.
Definition at line 41 of file NEQuantizationLayerKernel.h.
     {
         return "NEQuantizationLayerKernel";
     }
operator=() [1/2]
NEQuantizationLayerKernel& operator= (const NEQuantizationLayerKernel &) delete
Prevent instances of this class from being copied (As this class contains pointers)
operator=() [2/2]
NEQuantizationLayerKernel& operator= (NEQuantizationLayerKernel &&) default
Default move assignment operator.
run()
void run (const Window & window, const ThreadInfo & info) override virtual
Execute the kernel on the passed window.
Warning
If is_parallelisable() returns false then the passed window must be equal to window()
Note
The window has to be a region within the window returned by the window() method
The width of the window has to be a multiple of num_elems_processed_per_iteration().
Parameters
[in] window Region on which to execute the kernel. (Must be a region of the window returned by window())
[in] info Info about executing thread and CPU.
Reimplemented from ICPPKernel.
Definition at line 255 of file NEQuantizationLayerKernel.cpp.
 {
     ARM_COMPUTE_UNUSED(info);
     ARM_COMPUTE_ERROR_ON_UNCONFIGURED_KERNEL(this);
     ARM_COMPUTE_ERROR_ON_INVALID_SUBWINDOW(INEKernel::window(), window);
     ARM_COMPUTE_ERROR_ON(_func == nullptr);
     (this->*_func)(window);
 }
References ARM_COMPUTE_ERROR_ON, ARM_COMPUTE_ERROR_ON_INVALID_SUBWINDOW, ARM_COMPUTE_ERROR_ON_UNCONFIGURED_KERNEL, ARM_COMPUTE_UNUSED, arm_compute::test::validation::info, and IKernel::window().
validate()
Status validate (const ITensorInfo * input, const ITensorInfo * output) static
Static function to check if given info will lead to a valid configuration of NEQuantizationLayerKernel.
Parameters
[in] input Input tensor info. Data types supported: QASYMM8/QASYMM8_SIGNED/F32/F16.
[in] output Output tensor info. Data types supported: QASYMM8/QASYMM8_SIGNED/QASYMM16.
Returns
a status
Definition at line 161 of file NEQuantizationLayerKernel.cpp.
 {
     ARM_COMPUTE_RETURN_ON_ERROR(validate_arguments(input, output));
     return Status{};
 }
References ARM_COMPUTE_RETURN_ON_ERROR, arm_compute::test::validation::input, and arm_compute::validate_arguments().
Referenced by NEQuantizationLayer::validate(), and NEGenerateProposalsLayer::validate().
The documentation for this class was generated from the following files:
arm_compute/core/NEON/kernels/NEQuantizationLayerKernel.h
src/core/NEON/kernels/NEQuantizationLayerKernel.cpp