Compute Library: GCSoftmaxLayer Class Reference
GCSoftmaxLayer Class Reference
Basic function to compute a SoftmaxLayer.
#include <GCSoftmaxLayer.h>
Public Member Functions
GCSoftmaxLayer (std::shared_ptr< IMemoryManager > memory_manager=nullptr)
Constructor.
void configure (const IGCTensor *input, IGCTensor *output, float beta=1.0f, size_t reduce_end_axis=0)
Set the input and output tensors.
void run () override
Run the kernels contained in the function.
Public Member Functions inherited from IFunction
virtual ~IFunction ()=default
Destructor.
virtual void prepare ()
Prepare the function for executing.
Detailed Description
Basic function to compute a SoftmaxLayer.
Softmax is calculated by :
\[ out = exp(x - max(x)) / sum(exp(x - max(x))) \]
This function runs the following kernels:
GCLogits1DMaxKernel
GCLogits1DShiftExpSumKernel
GCLogits1DNormKernel
Definition at line 46 of file GCSoftmaxLayer.h.
Constructor & Destructor Documentation
GCSoftmaxLayer()
GCSoftmaxLayer (std::shared_ptr< IMemoryManager > memory_manager = nullptr)
Constructor.
Definition at line 32 of file GCSoftmaxLayer.cpp.
     : _memory_group(std::move(memory_manager)), _max_kernel(), _shift_exp_sum_kernel(), _norm_kernel(), _max(), _sum(), _tmp()
 {
 }
Member Function Documentation
configure()
void configure (const IGCTensor * input, IGCTensor * output, float beta = 1.0f, size_t reduce_end_axis = 0)
Set the input and output tensors.
Parameters
[in] input Source tensor. Data types supported: F16/F32
[out] output Destination tensor. Data types supported: same as input
[in] beta (Optional) A scaling factor for the exponent. Only beta = 1 is supported
[in] reduce_end_axis (Optional) The last axis of the first n dimensions (inclusive)to reduce. Defaults to 0. It has the purpose of squashing together the first n dimensions till (including) the reduce_end_axis. For instance, given a [2x3x4x5] image, when reduce_end_axis is 1, the reduction will be applied to axes 0 and 1, and the Softmax op will be applied on each of the [2x3] planes of the input image. Must be in range [0, input_num_dimensions).
Note
The value of reduce_end_axis must be always 0 for GLES
Definition at line 37 of file GCSoftmaxLayer.cpp.
 {
     ARM_COMPUTE_UNUSED(beta, reduce_end_axis);
     ARM_COMPUTE_ERROR_ON_DATA_TYPE_CHANNEL_NOT_IN(input, 1, DataType::F16, DataType::F32);
     ARM_COMPUTE_ERROR_ON(beta != 1.0f);
     ARM_COMPUTE_ERROR_ON_MSG(reduce_end_axis != 0, "Reduce_end_axis must be 0 for GLES");
     // Create intermediate tensors shapes
     _tmp.allocator()->init(TensorInfo(input->info()->tensor_shape(), input->info()->num_channels(), input->info()->data_type()));
     TensorShape shape = input->info()->tensor_shape();
     shape.set(0, 1);
     TensorInfo tensor_info_max_sum(shape, input->info()->num_channels(), input->info()->data_type());
     _max.allocator()->init(tensor_info_max_sum);
     _sum.allocator()->init(tensor_info_max_sum);
     // Manage intermediate buffers
     _memory_group.manage(&_tmp);
     _memory_group.manage(&_max);
     _memory_group.manage(&_sum);
     // Configure Kernels
     _max_kernel.configure(input, &_max);
     _shift_exp_sum_kernel.configure(input, &_max, &_tmp, &_sum);
     _norm_kernel.configure(&_tmp, &_sum, output);
     // Allocate intermediate buffers
     _tmp.allocator()->allocate();
     _max.allocator()->allocate();
     _sum.allocator()->allocate();
 }
References ITensorAllocator::allocate(), GCTensor::allocator(), ARM_COMPUTE_ERROR_ON, ARM_COMPUTE_ERROR_ON_DATA_TYPE_CHANNEL_NOT_IN, ARM_COMPUTE_ERROR_ON_MSG, ARM_COMPUTE_UNUSED, GCLogits1DMaxKernel::configure(), GCLogits1DShiftExpSumKernel::configure(), GCLogits1DNormKernel::configure(), arm_compute::F16, arm_compute::F32, ITensorAllocator::init(), arm_compute::test::validation::input, MemoryGroup::manage(), and arm_compute::test::validation::shape.
Referenced by arm_compute::test::validation::DATA_TEST_CASE().
run()
void run () override virtual
Run the kernels contained in the function.
For NEON kernels:
Multi-threading is used for the kernels which are parallelisable.
By default std::thread::hardware_concurrency() threads are used.
Note
CPPScheduler::set_num_threads() can be used to manually set the number of threads
For OpenCL kernels:
All the kernels are enqueued on the queue associated with CLScheduler.
The queue is then flushed.
Note
The function will not block until the kernels are executed. It is the user's responsibility to wait.
Will call prepare() on first run if hasn't been done
Implements IFunction.
Definition at line 70 of file GCSoftmaxLayer.cpp.
 {
     MemoryGroupResourceScope scope_mg(_memory_group);
     GCScheduler::get().dispatch(_max_kernel, false);
     GCScheduler::get().memory_barrier();
     GCScheduler::get().dispatch(_shift_exp_sum_kernel, false);
     GCScheduler::get().memory_barrier();
     GCScheduler::get().dispatch(_norm_kernel);
 }
References GCScheduler::dispatch(), GCScheduler::get(), and GCScheduler::memory_barrier().
The documentation for this class was generated from the following files:
arm_compute/runtime/GLES_COMPUTE/functions/GCSoftmaxLayer.h
src/runtime/GLES_COMPUTE/functions/GCSoftmaxLayer.cpp