Compute Library: NEWidthConcatenateLayerKernel Class Reference
NEWidthConcatenateLayerKernel Class Reference
Interface for the width concatenate kernel.
#include <NEWidthConcatenateLayerKernel.h>
Public Member Functions
const char * name () const override
Name of the kernel.
NEWidthConcatenateLayerKernel ()
Default constructor.
NEWidthConcatenateLayerKernel (const NEWidthConcatenateLayerKernel &)=delete
Prevent instances of this class from being copied (As this class contains pointers)
NEWidthConcatenateLayerKernel & operator= (const NEWidthConcatenateLayerKernel &)=delete
Prevent instances of this class from being copied (As this class contains pointers)
NEWidthConcatenateLayerKernel (NEWidthConcatenateLayerKernel &&)=default
Allow instances of this class to be moved.
NEWidthConcatenateLayerKernel & operator= (NEWidthConcatenateLayerKernel &&)=default
Allow instances of this class to be moved.
~NEWidthConcatenateLayerKernel ()=default
Default destructor.
void configure (const ITensorInfo *input, unsigned int width_offset, ITensorInfo *output)
Initialise the kernel's inputs and output.
void run_op (ITensorPack &tensors, const Window &window, const ThreadInfo &info) override
Execute the kernel on the passed window.
Public Member Functions inherited from ICPPKernel
virtual ~ICPPKernel ()=default
Default destructor.
virtual void run (const Window &window, const ThreadInfo &info)
Execute the kernel on the passed window.
virtual void run_nd (const Window &window, const ThreadInfo &info, const Window &thread_locator)
legacy compatibility layer for implemantions which do not support thread_locator In these cases we simply narrow the interface down the legacy version
Public Member Functions inherited from IKernel
IKernel ()
Constructor.
virtual ~IKernel ()=default
Destructor.
virtual bool is_parallelisable () const
Indicates whether or not the kernel is parallelisable.
virtual BorderSize border_size () const
The size of the border for that kernel.
const Window & window () const
The maximum window the kernel can be executed on.
Static Public Member Functions
static Status validate (const ITensorInfo *input, unsigned int width_offset, const ITensorInfo *output)
Static function to check if given info will lead to a valid configuration of NEWidthConcatenateLayerKernel.
Detailed Description
Interface for the width concatenate kernel.
The input tensor will be concatenated into the output tensor.
Definition at line 39 of file NEWidthConcatenateLayerKernel.h.
Constructor & Destructor Documentation
NEWidthConcatenateLayerKernel() [1/3]
NEWidthConcatenateLayerKernel ()
Default constructor.
Definition at line 60 of file NEWidthConcatenateLayerKernel.cpp.
     : _width_offset(0)
 {
 }
NEWidthConcatenateLayerKernel() [2/3]
NEWidthConcatenateLayerKernel (const NEWidthConcatenateLayerKernel &) delete
Prevent instances of this class from being copied (As this class contains pointers)
NEWidthConcatenateLayerKernel() [3/3]
NEWidthConcatenateLayerKernel (NEWidthConcatenateLayerKernel &&) default
Allow instances of this class to be moved.
~NEWidthConcatenateLayerKernel()
~NEWidthConcatenateLayerKernel () default
Default destructor.
Member Function Documentation
configure()
void configure (const ITensorInfo * input, unsigned int width_offset, ITensorInfo * output)
Initialise the kernel's inputs and output.
Parameters
[in] input Input tensor info. Data types supported: All
[in] width_offset The offset on the X axis.
[in,out] output Output tensor info. Data types supported: Same as input.
Definition at line 65 of file NEWidthConcatenateLayerKernel.cpp.
 {
     ARM_COMPUTE_ERROR_ON_NULLPTR(input, output);
     ARM_COMPUTE_ERROR_THROW_ON(validate_arguments(input, width_offset, output));
     _width_offset = width_offset;
     // Configure kernel window
     Window      win = calculate_max_window(*input, Steps());
     Coordinates coord;
     coord.set_num_dimensions(output->num_dimensions());
     output->set_valid_region(ValidRegion(coord, output->tensor_shape()));
     INEKernel::configure(win);
 }
References ARM_COMPUTE_ERROR_ON_NULLPTR, ARM_COMPUTE_ERROR_THROW_ON, arm_compute::calculate_max_window(), arm_compute::test::validation::input, ITensorInfo::num_dimensions(), Dimensions< T >::set_num_dimensions(), ITensorInfo::set_valid_region(), ITensorInfo::tensor_shape(), and arm_compute::validate_arguments().
name()
const char* name () const inline override virtual
Name of the kernel.
Returns
Kernel name
Implements ICPPKernel.
Definition at line 42 of file NEWidthConcatenateLayerKernel.h.
     {
         return "NEWidthConcatenateLayerKernel";
     }
operator=() [1/2]
NEWidthConcatenateLayerKernel& operator= (const NEWidthConcatenateLayerKernel &) delete
Prevent instances of this class from being copied (As this class contains pointers)
operator=() [2/2]
NEWidthConcatenateLayerKernel& operator= (NEWidthConcatenateLayerKernel &&) default
Allow instances of this class to be moved.
run_op()
void run_op (ITensorPack & tensors, const Window & window, const ThreadInfo & info) override virtual
Execute the kernel on the passed window.
Warning
If is_parallelisable() returns false then the passed window must be equal to window()
Note
The window has to be a region within the window returned by the window() method
The width of the window has to be a multiple of num_elems_processed_per_iteration().
Parameters
[in] tensors A vector containing the tensors to operate on.
[in] window Region on which to execute the kernel. (Must be a region of the window returned by window())
[in] info Info about executing thread and CPU.
Reimplemented from ICPPKernel.
Definition at line 87 of file NEWidthConcatenateLayerKernel.cpp.
 {
     ARM_COMPUTE_UNUSED(info);
     ARM_COMPUTE_ERROR_ON_UNCONFIGURED_KERNEL(this);
     ARM_COMPUTE_ERROR_ON_INVALID_SUBWINDOW(INEKernel::window(), window);
     const auto src = tensors.get_const_tensor(TensorType::ACL_SRC);
     auto       dst = tensors.get_tensor(TensorType::ACL_DST);
     // Offset output pointer to the correct position
     uint8_t *output_ptr = dst->buffer() + dst->info()->offset_first_element_in_bytes() + _width_offset * dst->info()->strides_in_bytes()[0];
     const auto    window_start_x = static_cast<int>(window.x().start());
     const auto    window_end_x   = static_cast<int>(window.x().end()) * static_cast<int>(dst->info()->element_size());
     constexpr int window_step_x  = 16;
     Window win{ window };
     win.set(Window::DimX, Window::Dimension(0, 1, 1));
     // Create iterators
     Iterator                       input(src, win);
     Iterator                       output(dst, win);
     const DataType                 dt           = src->info()->data_type();
     const UniformQuantizationInfo &input_qinfo  = src->info()->quantization_info().uniform();
     const UniformQuantizationInfo &output_qinfo = dst->info()->quantization_info().uniform();
     if(dt == DataType::QASYMM8 && input_qinfo != output_qinfo)
     {
         execute_window_loop(win, [&](const Coordinates &)
         {
             int x = window_start_x;
             for(; x <= (window_end_x - window_step_x); x += window_step_x)
             {
                 vst1q_u8(output_ptr + output.offset() + x, vquantize(vdequantize(vld1q_u8(input.ptr() + x), input_qinfo), output_qinfo));
             }
             // Compute left-over elements
             for(; x < window_end_x; ++x)
             {
                 *(output_ptr + output.offset() + x) = quantize_qasymm8(dequantize_qasymm8(*(input.ptr() + x), input_qinfo), output_qinfo);
             }
         },
         input, output);
     }
     else if(dt == DataType::QASYMM8_SIGNED && input_qinfo != output_qinfo)
     {
         execute_window_loop(win, [&](const Coordinates &)
         {
             int x = window_start_x;
             for(; x <= (window_end_x - window_step_x); x += window_step_x)
             {
                 vst1q_s8(reinterpret_cast<int8_t *>(output_ptr + output.offset() + x),
                          vquantize_signed(vdequantize(vld1q_s8(reinterpret_cast<int8_t *>(input.ptr() + x)), input_qinfo), output_qinfo));
             }
             // Compute left-over elements
             for(; x < window_end_x; ++x)
             {
                 *(output_ptr + output.offset() + x) = quantize_qasymm8_signed(dequantize_qasymm8_signed(*(input.ptr() + x), input_qinfo), output_qinfo);
             }
         },
         input, output);
     }
     else
     {
         execute_window_loop(win, [&](const Coordinates &)
         {
             const auto in_ptr  = input.ptr();
             const auto out_ptr = output_ptr + output.offset();
             int        x       = window_start_x;
             for(; x <= (window_end_x - window_step_x); x += window_step_x)
             {
                 wrapper::vstore(out_ptr + x, wrapper::vloadq(in_ptr + x));
             }
             // Compute left-over elements
             for(; x < window_end_x; ++x)
             {
                 *(out_ptr + x) = *(in_ptr + x);
             }
         },
         input, output);
     }
 }
References arm_compute::ACL_DST, arm_compute::ACL_SRC, ARM_COMPUTE_ERROR_ON_INVALID_SUBWINDOW, ARM_COMPUTE_ERROR_ON_UNCONFIGURED_KERNEL, ARM_COMPUTE_UNUSED, ICLTensor::buffer(), arm_compute::dequantize_qasymm8(), arm_compute::dequantize_qasymm8_signed(), Window::DimX, arm_compute::test::validation::dst, TensorInfo::element_size(), Window::Dimension::end(), arm_compute::execute_window_loop(), ITensorPack::get_const_tensor(), ITensorPack::get_tensor(), CLTensor::info(), arm_compute::test::validation::info, arm_compute::test::validation::input, Iterator::offset(), TensorInfo::offset_first_element_in_bytes(), arm_compute::QASYMM8, arm_compute::QASYMM8_SIGNED, TensorInfo::quantization_info(), arm_compute::quantize_qasymm8(), arm_compute::quantize_qasymm8_signed(), Window::set(), arm_compute::test::validation::src, Window::Dimension::start(), TensorInfo::strides_in_bytes(), QuantizationInfo::uniform(), arm_compute::vdequantize(), arm_compute::wrapper::vloadq(), arm_compute::vquantize(), arm_compute::vquantize_signed(), arm_compute::wrapper::vstore(), IKernel::window(), and Window::x().
validate()
Status validate (const ITensorInfo * input, unsigned int width_offset, const ITensorInfo * output) static
Static function to check if given info will lead to a valid configuration of NEWidthConcatenateLayerKernel.
Parameters
[in] input Input tensor info. Data types supported: All
[in] width_offset The offset on the X axis.
[in] output Output tensor info. Data types supported: Same as input.
Returns
a status
Definition at line 81 of file NEWidthConcatenateLayerKernel.cpp.
 {
     ARM_COMPUTE_RETURN_ON_ERROR(validate_arguments(input, width_offset, output));
     return Status{};
 }
References ARM_COMPUTE_RETURN_ON_ERROR, arm_compute::test::validation::input, and arm_compute::validate_arguments().
Referenced by NEConcatenation::validate().
The documentation for this class was generated from the following files:
arm_compute/core/NEON/kernels/NEWidthConcatenateLayerKernel.h
src/core/NEON/kernels/NEWidthConcatenateLayerKernel.cpp