Compute Library: GCScaleKernel Class Reference
GCScaleKernel Class Reference
Interface for the scale kernel.
#include <GCScaleKernel.h>
Public Member Functions
void configure (const IGCTensor *input, IGCTensor *output, const ScaleKernelInfo &info)
Initialise the kernel's inputs, output and interpolation policy.
void run (const Window &window) override
Enqueue the OpenGL ES shader to process the given window.
BorderSize border_size () const override
The size of the border for that kernel.
Public Member Functions inherited from IGCSimpleKernel
IGCSimpleKernel ()
Constructor.
IGCSimpleKernel (const IGCSimpleKernel &)=delete
Prevent instances of this class from being copied (As this class contains pointers)
IGCSimpleKernel & operator= (const IGCSimpleKernel &)=delete
Prevent instances of this class from being copied (As this class contains pointers)
IGCSimpleKernel (IGCSimpleKernel &&)=default
Allow instances of this class to be moved.
IGCSimpleKernel & operator= (IGCSimpleKernel &&)=default
Allow instances of this class to be moved.
~IGCSimpleKernel ()=default
Default destructor.
void configure (const IGCTensor *input, IGCTensor *output, unsigned int num_elems_processed_per_iteration, bool border_undefined=false, const BorderSize &border_size=BorderSize())
Configure the kernel.
Public Member Functions inherited from IGCKernel
IGCKernel ()
Constructor.
GCKernel & kernel ()
Returns a reference to the GLES kernel of this object.
void add_1D_tensor_argument (unsigned int &idx, const IGCTensor *tensor, const unsigned int binding_point, const Window &window)
Add the passed 1D tensor's parameters to the object's kernel's arguments starting from the index idx.
void add_2D_tensor_argument (unsigned int &idx, const IGCTensor *tensor, const unsigned int binding_point, const Window &window)
Add the passed 2D tensor's parameters to the object's kernel's arguments starting from the index idx.
void add_3D_tensor_argument (unsigned int &idx, const IGCTensor *tensor, const unsigned int binding_point, const Window &window)
Add the passed 3D tensor's parameters to the object's kernel's arguments starting from the index idx.
unsigned int num_arguments_per_1D_tensor () const
Returns the number of arguments enqueued per 1D tensor object.
unsigned int num_arguments_per_2D_tensor () const
Returns the number of arguments enqueued per 2D tensor object.
unsigned int num_arguments_per_3D_tensor () const
Returns the number of arguments enqueued per 3D tensor object.
void set_lws_hint (gles::NDRange &lws_hint)
Set the Local-Workgroup-Size hint.
void set_target (GPUTarget target)
Set the targeted GPU architecture.
GPUTarget get_target () const
Get the targeted GPU architecture.
Public Member Functions inherited from IKernel
IKernel ()
Constructor.
virtual ~IKernel ()=default
Destructor.
virtual bool is_parallelisable () const
Indicates whether or not the kernel is parallelisable.
const Window & window () const
The maximum window the kernel can be executed on.
Detailed Description
Interface for the scale kernel.
Definition at line 35 of file GCScaleKernel.h.
Member Function Documentation
border_size()
BorderSize border_size () const override virtual
The size of the border for that kernel.
Returns
The width in number of elements of the border.
Reimplemented from IKernel.
Definition at line 43 of file GCScaleKernel.cpp.
 {
     return BorderSize(1);
 }
Referenced by GCScaleKernel::configure().
configure()
void configure (const IGCTensor * input, IGCTensor * output, const ScaleKernelInfo & info)
Initialise the kernel's inputs, output and interpolation policy.
Parameters
[in] input Source tensor. Data types supported: F16
[out] output Destination tensor. Data types supported: Same as input All but the lowest two dimensions must be the same size as in the input tensor, i.e. scaling is only performed within the XY-plane.
[in] info ScaleKernelInfo descriptor to be used to configure
Definition at line 48 of file GCScaleKernel.cpp.
 {
     ARM_COMPUTE_ERROR_ON_DATA_TYPE_CHANNEL_NOT_IN(input, 1, DataType::F16);
     ARM_COMPUTE_ERROR_ON_NULLPTR(output);
     ARM_COMPUTE_ERROR_ON_MISMATCHING_DATA_TYPES(input, output);
     ARM_COMPUTE_ERROR_ON(output == input);
     ARM_COMPUTE_ERROR_ON(info.interpolation_policy != InterpolationPolicy::NEAREST_NEIGHBOR);
     _input  = input;
     _output = output;
     // Compute the ratio between source width/height and destination width/height
     const auto wr = static_cast<float>(input->info()->dimension(0)) / static_cast<float>(output->info()->dimension(0));
     const auto hr = static_cast<float>(input->info()->dimension(1)) / static_cast<float>(output->info()->dimension(1));
     // Compute actual border size
     const bool border_undefined = info.border_mode == BorderMode::UNDEFINED;
     BorderSize border           = border_undefined ? BorderSize(0) : border_size();
     // Area interpolation behaves as Nearest Neighbour in case of up-sampling
     auto interpolation_policy_to_use = info.interpolation_policy;
     if(interpolation_policy_to_use == InterpolationPolicy::AREA && wr <= 1.f && hr <= 1.f)
     {
         interpolation_policy_to_use = InterpolationPolicy::NEAREST_NEIGHBOR;
     }
     else
     {
         ARM_COMPUTE_ERROR_ON(interpolation_policy_to_use == InterpolationPolicy::AREA);
     }
     // Create kernel
     std::set<std::string> build_opts;
     build_opts.emplace("#define LOCAL_SIZE_X " + support::cpp11::to_string(1));
     build_opts.emplace("#define LOCAL_SIZE_Y " + support::cpp11::to_string(1));
     build_opts.emplace("#define LOCAL_SIZE_Z " + support::cpp11::to_string(1));
     build_opts.emplace("#define DATA_TYPE_FP16");
     build_opts.emplace("#define BORDER_SIZE " + support::cpp11::to_string(border.right));
     if(info.sampling_policy == SamplingPolicy::TOP_LEFT)
     {
         build_opts.emplace("#define SAMPLING_POLICY_TOP_LEFT");
     }
     else
     {
         build_opts.emplace("#define SAMPLING_POLICY_CENTER");
     }
     // Configure kernel window
     unsigned int num_elems_processed_per_iteration = 4;
     unsigned int input_width_alignment             = 2;
     // performance optimization for 2x upscaling with no border
     if((fabs(wr - 0.5) < 1e-6) && (fabs(hr - 0.5) < 1e-6) && border_undefined)
     {
         num_elems_processed_per_iteration = 8;
         input_width_alignment             = 4;
         build_opts.emplace("#define SCALE_NEAREST_8X");
     }
     else
     {
         build_opts.emplace("#define SCALE_NEAREST_GENERIC");
     }
     std::string interpolation_name = string_from_interpolation_policy(interpolation_policy_to_use); // NOLINT
     std::transform(interpolation_name.begin(), interpolation_name.end(), interpolation_name.begin(), ::tolower);
     std::string kernel_name = "scale_" + interpolation_name;
     _kernel                 = GCKernelLibrary::get().create_kernel(kernel_name, build_opts);
     Window win = calculate_max_window(*output->info(), Steps(num_elems_processed_per_iteration));
     const ValidRegion &input_valid_region = input->info()->valid_region();
     const int total_width   = border.left + input_valid_region.anchor[0] + input_valid_region.shape[0] + border.right;
     const int padding_right = ceil_to_multiple(total_width, input_width_alignment) - border.left - input_valid_region.anchor[0] - input_valid_region.shape[0];
     // Reads can occur within the valid region of the input
     AccessWindowStatic input_access(input->info(),
                                     input_valid_region.anchor[0] - border.left, input_valid_region.anchor[1] - border.top,
                                     input_valid_region.anchor[0] + input_valid_region.shape[0] + padding_right,
                                     input_valid_region.anchor[1] + input_valid_region.shape[1] + border.bottom);
     AccessWindowHorizontal output_access(output->info(), 0, num_elems_processed_per_iteration);
     update_window_and_padding(win, input_access, output_access);
     output_access.set_valid_region(win, calculate_valid_region_scale(*(input->info()),
                                                                      output->info()->tensor_shape(),
                                                                      info.interpolation_policy,
                                                                      info.sampling_policy,
                                                                      border_undefined));
     IGCKernel::configure(win);
     unsigned int idx = 2 * num_arguments_per_3D_tensor(); //Skip the tensor parameters
     _kernel.set_argument<float>(idx++, static_cast<float>(input->info()->dimension(0)));
     _kernel.set_argument<float>(idx++, static_cast<float>(input->info()->dimension(1)));
     _kernel.set_argument<float>(idx++, wr);
     _kernel.set_argument<float>(idx++, hr);
 }
References arm_compute::AREA, ARM_COMPUTE_ERROR_ON, ARM_COMPUTE_ERROR_ON_DATA_TYPE_CHANNEL_NOT_IN, ARM_COMPUTE_ERROR_ON_MISMATCHING_DATA_TYPES, ARM_COMPUTE_ERROR_ON_NULLPTR, GCScaleKernel::border_size(), BorderSize::bottom, arm_compute::calculate_max_window(), arm_compute::calculate_valid_region_scale(), arm_compute::ceil_to_multiple(), GCKernelLibrary::create_kernel(), ITensorInfo::dimension(), arm_compute::F16, GCKernelLibrary::get(), ITensor::info(), arm_compute::test::validation::info, arm_compute::test::validation::input, kernel_name, BorderSize::left, arm_compute::NEAREST_NEIGHBOR, IGCKernel::num_arguments_per_3D_tensor(), num_elems_processed_per_iteration, BorderSize::right, arm_compute::string_from_interpolation_policy(), ITensorInfo::tensor_shape(), arm_compute::support::cpp11::to_string(), arm_compute::utility::tolower(), BorderSize::top, arm_compute::TOP_LEFT, arm_compute::UNDEFINED, and arm_compute::update_window_and_padding().
run()
void run (const Window & window) override virtual
Enqueue the OpenGL ES shader to process the given window.
Parameters
[in] window Region on which to execute the kernel. (Must be a valid region of the window returned by window()).
Reimplemented from IGCSimple3DKernel.
Definition at line 148 of file GCScaleKernel.cpp.
 {
     ARM_COMPUTE_ERROR_ON_UNCONFIGURED_KERNEL(this);
     ARM_COMPUTE_ERROR_ON_INVALID_SUBWINDOW(IKernel::window(), window);
     _kernel.use();
     _output->set_needs_shifting(true);
     Window slice    = window.first_slice_window_3D();
     Window slice_in = window.first_slice_window_3D();
     slice.shift(Window::DimX, -(_output->info()->padding()).left);
     do
     {
         unsigned int idx = 0;
         add_3D_tensor_argument(idx, _input, 1, slice_in);
         add_3D_tensor_argument(idx, _output, 2, slice);
         _kernel.update_shader_params();
         enqueue(*this, slice);
     }
     while(window.slide_window_slice_3D(slice) && window.slide_window_slice_3D(slice_in));
 }
References IGCKernel::add_3D_tensor_argument(), ARM_COMPUTE_ERROR_ON_INVALID_SUBWINDOW, ARM_COMPUTE_ERROR_ON_UNCONFIGURED_KERNEL, Window::DimX, arm_compute::enqueue(), Window::first_slice_window_3D(), Tensor::info(), ITensorInfo::padding(), arm_compute::test::validation::reference::slice(), Window::slide_window_slice_3D(), and IKernel::window().
The documentation for this class was generated from the following files:
arm_compute/core/GLES_COMPUTE/kernels/GCScaleKernel.h
src/core/GLES_COMPUTE/kernels/GCScaleKernel.cpp