Compute Library: NEUpsampleLayerKernel Class Reference
NEUpsampleLayerKernel Class Reference
Interface for the Upsample layer kernel.
#include <NEUpsampleLayerKernel.h>
Public Member Functions
const char * name () const override
Name of the kernel.
NEUpsampleLayerKernel ()
Default constructor.
NEUpsampleLayerKernel (const NEUpsampleLayerKernel &)=delete
Prevent instances of this class from being copied (As this class contains pointers)
NEUpsampleLayerKernel & operator= (const NEUpsampleLayerKernel &)=delete
Prevent instances of this class from being copied (As this class contains pointers)
NEUpsampleLayerKernel (NEUpsampleLayerKernel &&)=default
Default Move Constructor.
NEUpsampleLayerKernel & operator= (NEUpsampleLayerKernel &&)=default
Default move assignment operator.
~NEUpsampleLayerKernel ()=default
Default destructor.
void configure (const ITensor *input, ITensor *output, const Size2D &info, const InterpolationPolicy policy)
Set the input output tensors.
void run (const Window &window, const ThreadInfo &info) override
Execute the kernel on the passed window.
Public Member Functions inherited from ICPPKernel
virtual ~ICPPKernel ()=default
Default destructor.
virtual void run_nd (const Window &window, const ThreadInfo &info, const Window &thread_locator)
legacy compatibility layer for implemantions which do not support thread_locator In these cases we simply narrow the interface down the legacy version
virtual void run_op (ITensorPack &tensors, const Window &window, const ThreadInfo &info)
Execute the kernel on the passed window.
Public Member Functions inherited from IKernel
IKernel ()
Constructor.
virtual ~IKernel ()=default
Destructor.
virtual bool is_parallelisable () const
Indicates whether or not the kernel is parallelisable.
virtual BorderSize border_size () const
The size of the border for that kernel.
const Window & window () const
The maximum window the kernel can be executed on.
Static Public Member Functions
static Status validate (const ITensorInfo *input, const ITensorInfo *output, const Size2D &info, const InterpolationPolicy policy)
Static function to check if given info will lead to a valid configuration of NEUpsampleLayerKernel.
Detailed Description
Interface for the Upsample layer kernel.
Definition at line 34 of file NEUpsampleLayerKernel.h.
Constructor & Destructor Documentation
NEUpsampleLayerKernel() [1/3]
NEUpsampleLayerKernel ()
Default constructor.
Definition at line 54 of file NEUpsampleLayerKernel.cpp.
     : _func(nullptr), _input(nullptr), _output(nullptr), _info()
 {
 }
NEUpsampleLayerKernel() [2/3]
NEUpsampleLayerKernel (const NEUpsampleLayerKernel &) delete
Prevent instances of this class from being copied (As this class contains pointers)
NEUpsampleLayerKernel() [3/3]
NEUpsampleLayerKernel (NEUpsampleLayerKernel &&) default
Default Move Constructor.
~NEUpsampleLayerKernel()
~NEUpsampleLayerKernel () default
Default destructor.
Member Function Documentation
configure()
void configure (const ITensor * input, ITensor * output, const Size2D & info, const InterpolationPolicy policy)
Set the input output tensors.
Parameters
[in] input Source tensor. Data types supported: QASYMM8/QASYMM8_SIGNED/F16/F32.
[out] output Destination tensor. Data types supported: same as input.
[in] info Contains stride information described in Size2D.
[in] policy Defines the policy to fill the intermediate pixels.
Definition at line 186 of file NEUpsampleLayerKernel.cpp.
 {
     ARM_COMPUTE_ERROR_ON_NULLPTR(input, output);
     ARM_COMPUTE_UNUSED(policy);
     _input  = input;
     _output = output;
     _info   = info;
     const DataLayout data_layout = input->info()->data_layout();
     TensorShape output_shape = misc::shape_calculator::compute_upsample_shape(*input->info(), info);
     auto_init_if_empty(*output->info(), output_shape, 1, input->info()->data_type());
     output->info()->set_data_layout(data_layout);
     // Perform validation step
     ARM_COMPUTE_ERROR_THROW_ON(NEUpsampleLayerKernel::validate(input->info(), output->info(), info, policy));
     switch(data_layout)
     {
         case DataLayout::NCHW:
         {
             switch(input->info()->data_type())
             {
                 case DataType::QASYMM8_SIGNED:
                     _func = &NEUpsampleLayerKernel::upsample_nchw<int8_t, 16>;
                     break;
                 case DataType::QASYMM8:
                     _func = &NEUpsampleLayerKernel::upsample_nchw<uint8_t, 16>;
                     break;
                 case DataType::F32:
                     _func = &NEUpsampleLayerKernel::upsample_nchw<float, 4>;
                     break;
 #ifdef __ARM_FEATURE_FP16_VECTOR_ARITHMETIC
                 case DataType::F16:
                     _func = &NEUpsampleLayerKernel::upsample_nchw<float16_t, 8>;
                     ;
                     break;
 #endif /* __ARM_FEATURE_FP16_VECTOR_ARITHMETIC */
                 default:
                     ARM_COMPUTE_ERROR("Not implemented");
             }
             break;
         }
         case DataLayout::NHWC:
         {
             switch(input->info()->data_type())
             {
                 case DataType::QASYMM8_SIGNED:
                     _func = &NEUpsampleLayerKernel::upsample_nhwc<int8_t, 16>;
                     break;
                 case DataType::QASYMM8:
                     _func = &NEUpsampleLayerKernel::upsample_nhwc<uint8_t, 16>;
                     break;
                 case DataType::F32:
                     _func = &NEUpsampleLayerKernel::upsample_nhwc<float, 4>;
                     break;
 #ifdef __ARM_FEATURE_FP16_VECTOR_ARITHMETIC
                 case DataType::F16:
                     _func = &NEUpsampleLayerKernel::upsample_nhwc<float16_t, 8>;
                     break;
 #endif /* __ARM_FEATURE_FP16_VECTOR_ARITHMETIC */
                 default:
                     ARM_COMPUTE_ERROR("Not implemented");
             }
             break;
         }
         default:
             ARM_COMPUTE_ERROR("Not implemented");
     }
     // Configure window
     Window      win = calculate_max_window(*input->info(), Steps());
     Coordinates coord;
     coord.set_num_dimensions(output->info()->num_dimensions());
     output->info()->set_valid_region(ValidRegion(coord, output->info()->tensor_shape()));
     INEKernel::configure(win);
 }
References ARM_COMPUTE_ERROR, ARM_COMPUTE_ERROR_ON_NULLPTR, ARM_COMPUTE_ERROR_THROW_ON, ARM_COMPUTE_UNUSED, arm_compute::auto_init_if_empty(), arm_compute::calculate_max_window(), arm_compute::misc::shape_calculator::compute_upsample_shape(), arm_compute::test::validation::data_layout, arm_compute::F16, arm_compute::F32, ITensor::info(), arm_compute::test::validation::info, arm_compute::test::validation::input, arm_compute::NCHW, arm_compute::NHWC, ITensorInfo::num_dimensions(), arm_compute::test::validation::output_shape, arm_compute::test::validation::policy, arm_compute::QASYMM8, arm_compute::QASYMM8_SIGNED, ITensorInfo::set_data_layout(), Dimensions< T >::set_num_dimensions(), ITensorInfo::set_valid_region(), ITensorInfo::tensor_shape(), and NEUpsampleLayerKernel::validate().
Referenced by NEUpsampleLayer::configure().
name()
const char* name () const inline override virtual
Name of the kernel.
Returns
Kernel name
Implements ICPPKernel.
Definition at line 37 of file NEUpsampleLayerKernel.h.
     {
         return "NEUpsampleLayerKernel";
     }
operator=() [1/2]
NEUpsampleLayerKernel& operator= (const NEUpsampleLayerKernel &) delete
Prevent instances of this class from being copied (As this class contains pointers)
operator=() [2/2]
NEUpsampleLayerKernel& operator= (NEUpsampleLayerKernel &&) default
Default move assignment operator.
run()
void run (const Window & window, const ThreadInfo & info) override virtual
Execute the kernel on the passed window.
Warning
If is_parallelisable() returns false then the passed window must be equal to window()
Note
The window has to be a region within the window returned by the window() method
The width of the window has to be a multiple of num_elems_processed_per_iteration().
Parameters
[in] window Region on which to execute the kernel. (Must be a region of the window returned by window())
[in] info Info about executing thread and CPU.
Reimplemented from ICPPKernel.
Definition at line 265 of file NEUpsampleLayerKernel.cpp.
 {
     ARM_COMPUTE_UNUSED(info);
     ARM_COMPUTE_ERROR_ON_UNCONFIGURED_KERNEL(this);
     ARM_COMPUTE_ERROR_ON_INVALID_SUBWINDOW(INEKernel::window(), window);
     ARM_COMPUTE_ERROR_ON(_func == nullptr);
     (this->*_func)(window);
 }
References ARM_COMPUTE_ERROR_ON, ARM_COMPUTE_ERROR_ON_INVALID_SUBWINDOW, ARM_COMPUTE_ERROR_ON_UNCONFIGURED_KERNEL, ARM_COMPUTE_UNUSED, arm_compute::test::validation::info, and IKernel::window().
validate()
Status validate (const ITensorInfo * input, const ITensorInfo * output, const Size2D & info, const InterpolationPolicy policy) static
Static function to check if given info will lead to a valid configuration of NEUpsampleLayerKernel.
Parameters
[in] input Source tensor info. Data types supported: QASYMM8/QASYMM8_SIGNED/F16/F32.
[in] output Destination tensor info. Data types supported: same as input.
[in] info Contains stride information described in Size2D.
[in] policy Defines the policy to fill the intermediate pixels.
Returns
a status
Definition at line 59 of file NEUpsampleLayerKernel.cpp.
 {
     ARM_COMPUTE_RETURN_ERROR_ON_NULLPTR(input, output);
     ARM_COMPUTE_UNUSED(policy);
     const DataLayout data_layout = input->data_layout();
     const int        idx_width   = get_data_layout_dimension_index(data_layout, DataLayoutDimension::WIDTH);
     const int        idx_height  = get_data_layout_dimension_index(data_layout, DataLayoutDimension::HEIGHT);
     ARM_COMPUTE_RETURN_ERROR_ON_CPU_F16_UNSUPPORTED(input);
     ARM_COMPUTE_RETURN_ERROR_ON_DATA_TYPE_CHANNEL_NOT_IN(input, 1, DataType::QASYMM8_SIGNED, DataType::QASYMM8, DataType::F16, DataType::F32);
     ARM_COMPUTE_RETURN_ERROR_ON_MSG(info.x() != 2 || info.y() != 2, "Only stride 2 is supported");
     ARM_COMPUTE_RETURN_ERROR_ON_MSG(policy != InterpolationPolicy::NEAREST_NEIGHBOR, "Only nearest neighbor policy supported");
     // Check output if configured
     if(output->total_size() != 0)
     {
         ARM_COMPUTE_RETURN_ERROR_ON_MISMATCHING_DATA_TYPES(input, output);
         ARM_COMPUTE_RETURN_ERROR_ON_MISMATCHING_DATA_LAYOUT(input, output);
         ARM_COMPUTE_RETURN_ERROR_ON(output->dimension(idx_width) != info.x() * input->dimension(idx_width));
         ARM_COMPUTE_RETURN_ERROR_ON(output->dimension(idx_height) != info.y() * input->dimension(idx_height));
         ARM_COMPUTE_RETURN_ERROR_ON_MISMATCHING_QUANTIZATION_INFO(input, output);
     }
     return Status{};
 }
References ARM_COMPUTE_RETURN_ERROR_ON, ARM_COMPUTE_RETURN_ERROR_ON_CPU_F16_UNSUPPORTED, ARM_COMPUTE_RETURN_ERROR_ON_DATA_TYPE_CHANNEL_NOT_IN, ARM_COMPUTE_RETURN_ERROR_ON_MISMATCHING_DATA_LAYOUT, ARM_COMPUTE_RETURN_ERROR_ON_MISMATCHING_DATA_TYPES, ARM_COMPUTE_RETURN_ERROR_ON_MISMATCHING_QUANTIZATION_INFO, ARM_COMPUTE_RETURN_ERROR_ON_MSG, ARM_COMPUTE_RETURN_ERROR_ON_NULLPTR, ARM_COMPUTE_UNUSED, arm_compute::test::validation::data_layout, ITensorInfo::dimension(), arm_compute::F16, arm_compute::F32, arm_compute::get_data_layout_dimension_index(), arm_compute::HEIGHT, arm_compute::test::validation::info, arm_compute::test::validation::input, arm_compute::NEAREST_NEIGHBOR, arm_compute::test::validation::policy, arm_compute::QASYMM8, arm_compute::QASYMM8_SIGNED, ITensorInfo::total_size(), and arm_compute::WIDTH.
Referenced by NEUpsampleLayerKernel::configure(), and NEUpsampleLayer::validate().
The documentation for this class was generated from the following files:
arm_compute/core/NEON/kernels/NEUpsampleLayerKernel.h
src/core/NEON/kernels/NEUpsampleLayerKernel.cpp