Compute Library: CLPReluLayer Class Reference
CLPReluLayer Class Reference
Basic function to run CLArithmeticOperationKernel for PRELU.
#include <CLPReluLayer.h>
Public Member Functions
CLPReluLayer ()
Default Constructor.
void configure (const CLCompileContext &compile_context, ITensorInfo *input, ITensorInfo *alpha, ITensorInfo *output)
Set the input and output tensor.
void run (ITensorPack &tensors) override
Run the kernels contained in the function.
Public Member Functions inherited from ICLOperator
ICLOperator (IRuntimeContext *ctx=nullptr)
Constructor.
ICLOperator (const ICLOperator &)=delete
Prevent instances of this class from being copied (As this class contains pointers)
ICLOperator (ICLOperator &&)=default
Default move constructor.
ICLOperator & operator= (const ICLOperator &)=delete
Prevent instances of this class from being copied (As this class contains pointers)
ICLOperator & operator= (ICLOperator &&)=default
Default move assignment operator.
void run (ITensorPack &tensors) override
Run the kernels contained in the function.
void prepare (ITensorPack &constants) override
Prepare the function for executing.
MemoryRequirements workspace () const override
Return the memory requirements required by the workspace.
Public Member Functions inherited from IOperator
virtual ~IOperator ()=default
Destructor.
Static Public Member Functions
static Status validate (const ITensorInfo *input, const ITensorInfo *alpha, const ITensorInfo *output)
Static function to check if given info will lead to a valid configuration of CLPReluLayer.
Detailed Description
Basic function to run CLArithmeticOperationKernel for PRELU.
Note
The function implements an activation layer with the PRELU activation function.
Definition at line 41 of file CLPReluLayer.h.
Constructor & Destructor Documentation
CLPReluLayer()
CLPReluLayer ()
Default Constructor.
Definition at line 68 of file CLPReluLayer.cpp.
     : _border_handler()
 {
 }
Member Function Documentation
configure()
void configure (const CLCompileContext & compile_context, ITensorInfo * input, ITensorInfo * alpha, ITensorInfo * output)
Set the input and output tensor.
Note
If the output tensor is a nullptr or is equal to the input, the activation function will be performed in-place
Parameters
[in] compile_context The compile context to be used.
[in] input Source tensor. Data types supported: QASYMM8/QASYMM8_SIGNED/F16/F32.
[in] alpha PRelu layer parameters. Data types supported: same of input.
[out] output Destination tensor. Data type supported: same as input
Definition at line 73 of file CLPReluLayer.cpp.
 {
     auto k = arm_compute::support::cpp14::make_unique<CLArithmeticOperationKernel>();
     k->configure(compile_context, ArithmeticOperation::PRELU, input, alpha, output);
     _kernel = std::move(k);
     configure_border_handler(compile_context, _border_handler, _kernel->border_size(), input, alpha, output);
 }
References arm_compute::test::validation::alpha, IKernel::border_size(), arm_compute::test::validation::input, and arm_compute::PRELU.
run()
void run (ITensorPack & tensors) override virtual
Run the kernels contained in the function.
Parameters
[in] tensors Vector that contains the tensors to operate on.
Implements IOperator.
Definition at line 86 of file CLPReluLayer.cpp.
 {
     auto border_pack = select_border_input(tensors);
     CLScheduler::get().enqueue_op(_border_handler, border_pack);
     ICLOperator::run(tensors);
 }
References CLScheduler::enqueue_op(), CLScheduler::get(), and ICLOperator::run().
validate()
Status validate (const ITensorInfo * input, const ITensorInfo * alpha, const ITensorInfo * output) static
Static function to check if given info will lead to a valid configuration of CLPReluLayer.
Parameters
[in] input Source tensor info. Data types supported: QASYMM8/QASYMM8_SIGNED/F16/F32.
[in] alpha PRelu layer parameters. Data types supported: same of input.
[in] output Destination tensor info. Data type supported: same as input
Returns
a status
Definition at line 81 of file CLPReluLayer.cpp.
 {
     return CLArithmeticOperationKernel::validate(ArithmeticOperation::PRELU, input, alpha, output);
 }
References arm_compute::test::validation::alpha, arm_compute::test::validation::input, arm_compute::PRELU, and CLArithmeticOperationKernel::validate().
Referenced by CLPReluLayer::validate().
The documentation for this class was generated from the following files:
arm_compute/runtime/CL/functions/CLPReluLayer.h
src/runtime/CL/functions/CLPReluLayer.cpp