Compute Library: CLPixelWiseMultiplication Class Reference
CLPixelWiseMultiplication Class Reference
Basic function to run CLPixelWiseMultiplicationKernel.
#include <CLPixelWiseMultiplication.h>
Public Member Functions
CLPixelWiseMultiplication ()
Default Constructor.
void configure (const CLCompileContext &compile_context, ITensorInfo *input1, ITensorInfo *input2, ITensorInfo *output, float scale, ConvertPolicy overflow_policy, RoundingPolicy rounding_policy, const ActivationLayerInfo &act_info=ActivationLayerInfo())
Initialise the kernel's inputs, output and convertion policy.
void run (ITensorPack &tensors) override
Run the kernels contained in the function.
Public Member Functions inherited from ICLOperator
ICLOperator (IRuntimeContext *ctx=nullptr)
Constructor.
ICLOperator (const ICLOperator &)=delete
Prevent instances of this class from being copied (As this class contains pointers)
ICLOperator (ICLOperator &&)=default
Default move constructor.
ICLOperator & operator= (const ICLOperator &)=delete
Prevent instances of this class from being copied (As this class contains pointers)
ICLOperator & operator= (ICLOperator &&)=default
Default move assignment operator.
void run (ITensorPack &tensors) override
Run the kernels contained in the function.
void prepare (ITensorPack &constants) override
Prepare the function for executing.
MemoryRequirements workspace () const override
Return the memory requirements required by the workspace.
Public Member Functions inherited from IOperator
virtual ~IOperator ()=default
Destructor.
Static Public Member Functions
static Status validate (const ITensorInfo *input1, const ITensorInfo *input2, const ITensorInfo *output, float scale, ConvertPolicy overflow_policy, RoundingPolicy rounding_policy, const ActivationLayerInfo &act_info=ActivationLayerInfo())
Static function to check if given info will lead to a valid configuration of CLPixelWiseMultiplication.
Detailed Description
Basic function to run CLPixelWiseMultiplicationKernel.
Definition at line 39 of file CLPixelWiseMultiplication.h.
Constructor & Destructor Documentation
CLPixelWiseMultiplication()
CLPixelWiseMultiplication ()
Default Constructor.
Definition at line 57 of file CLPixelWiseMultiplication.cpp.
     : _border_handler()
 {
 }
Member Function Documentation
configure()
void configure (const CLCompileContext & compile_context, ITensorInfo * input1, ITensorInfo * input2, ITensorInfo * output, float scale, ConvertPolicy overflow_policy, RoundingPolicy rounding_policy, const ActivationLayerInfo & act_info = ActivationLayerInfo())
Initialise the kernel's inputs, output and convertion policy.
Valid configurations (Input1,Input2) -> Output :
(U8,U8) -> U8
(U8,U8) -> S16
(U8,S16) -> S16
(S16,U8) -> S16
(S16,S16) -> S16
(F16,F16) -> F16
(F32,F32) -> F32
(QASYMM8,QASYMM8) -> QASYMM8
(QASYMM8_SIGNED,QASYMM8_SIGNED) -> QASYMM8_SIGNED
(QSYMM16,QSYMM16) -> QSYMM16
(QSYMM16,QSYMM16) -> S32
Parameters
[in] compile_context The compile context to be used.
[in,out] input1 An input tensor. Data types supported: U8/QASYMM8/QASYMM8_SIGNED/S16/QSYMM16/F16/F32. The input tensor is [in, out] because its TensorInfo might be modified inside the kernel in case of broadcasting of dimension 0.
[in,out] input2 An input tensor. Data types supported: U8/QASYMM8/QASYMM8_SIGNED/S16/QSYMM16/F16/F32. The input tensor is [in, out] because its TensorInfo might be modified inside the kernel in case of broadcasting of dimension 0.
[out] output The output tensor. Data types supported: U8/QASYMM8/QASYMM8_SIGNED/S16/QSYMM16/F16/F32.
[in] scale Scale to apply after multiplication. Scale must be positive and its value must be either 1/255 or 1/2^n where n is between 0 and 15.
[in] overflow_policy Overflow policy. Supported overflow policies: Wrap, Saturate
[in] rounding_policy Rounding policy. Supported rounding modes: to zero, to nearest even.
[in] act_info (Optional) Activation layer information in case of a fused activation.
Definition at line 62 of file CLPixelWiseMultiplication.cpp.
 {
     auto k = arm_compute::support::cpp14::make_unique<CLPixelWiseMultiplicationKernel>();
     k->configure(compile_context, input1, input2, output, scale, overflow_policy, rounding_policy, act_info);
     _kernel = std::move(k);
     if(output->dimension(0) > 1)
     {
         ITensorInfo *broadcasted_info = (input1->dimension(0) == 1) ? input1 : input2;
         if(broadcasted_info->dimension(0) == 1)
         {
             _border_handler.configure(compile_context, broadcasted_info, _kernel->border_size(), BorderMode::REPLICATE);
         }
     }
 }
References CLFillBorderKernel::configure(), ITensorInfo::dimension(), arm_compute::REPLICATE, and arm_compute::test::validation::reference::scale().
run()
void run (ITensorPack & tensors) override virtual
Run the kernels contained in the function.
Parameters
[in] tensors Vector that contains the tensors to operate on.
Implements IOperator.
Definition at line 86 of file CLPixelWiseMultiplication.cpp.
 {
     auto border_pack = select_border_input(tensors);
     CLScheduler::get().enqueue_op(_border_handler, border_pack);
     ICLOperator::run(tensors);
 }
References CLScheduler::enqueue_op(), CLScheduler::get(), and ICLOperator::run().
validate()
Status validate (const ITensorInfo * input1, const ITensorInfo * input2, const ITensorInfo * output, float scale, ConvertPolicy overflow_policy, RoundingPolicy rounding_policy, const ActivationLayerInfo & act_info = ActivationLayerInfo()) static
Static function to check if given info will lead to a valid configuration of CLPixelWiseMultiplication.
Valid configurations (Input1,Input2) -> Output :
(U8,U8) -> U8
(U8,U8) -> S16
(U8,S16) -> S16
(S16,U8) -> S16
(S16,S16) -> S16
(F16,F16) -> F16
(F32,F32) -> F32
(QASYMM8,QASYMM8) -> QASYMM8
(QASYMM8_SIGNED,QASYMM8_SIGNED) -> QASYMM8_SIGNED
(QSYMM16,QSYMM16) -> QSYMM16
(QSYMM16,QSYMM16) -> S32
Parameters
[in] input1 An input tensor info. Data types supported: U8/QASYMM8/QASYMM8_SIGNED/S16/QSYMM16/F16/F32.
[in] input2 An input tensor info. Data types supported: U8/QASYMM8/QASYMM8_SIGNED/S16/QSYMM16/F16/F32.
[in] output The output tensor info. Data types supported: U8/QASYMM8/QASYMM8_SIGNED/S16/QSYMM16/F16/F32.
[in] scale Scale to apply after multiplication. Scale must be positive and its value must be either 1/255 or 1/2^n where n is between 0 and 15.
[in] overflow_policy Overflow policy. Supported overflow policies: Wrap, Saturate
[in] rounding_policy Rounding policy. Supported rounding modes: to zero, to nearest even.
[in] act_info (Optional) Activation layer information in case of a fused activation.
Returns
a status
Definition at line 80 of file CLPixelWiseMultiplication.cpp.
 {
     return CLPixelWiseMultiplicationKernel::validate(input1, input2, output, scale, overflow_policy, rounding_policy, act_info);
 }
References arm_compute::test::validation::reference::scale(), and CLPixelWiseMultiplicationKernel::validate().
Referenced by CLPixelWiseMultiplication::validate().
The documentation for this class was generated from the following files:
arm_compute/runtime/CL/functions/CLPixelWiseMultiplication.h
src/runtime/CL/functions/CLPixelWiseMultiplication.cpp