Compute Library: NEROIAlignLayerKernel Class Reference
NEROIAlignLayerKernel Class Reference
Interface for the RoIAlign kernel.
#include <NEROIAlignLayerKernel.h>
Public Member Functions
const char * name () const override
Name of the kernel.
NEROIAlignLayerKernel ()
Constructor.
NEROIAlignLayerKernel (const NEROIAlignLayerKernel &)=delete
Prevent instances of this class from being copied (As this class contains pointers)
NEROIAlignLayerKernel & operator= (const NEROIAlignLayerKernel &)=delete
Prevent instances of this class from being copied (As this class contains pointers)
NEROIAlignLayerKernel (NEROIAlignLayerKernel &&)=default
Default Move Constructor.
NEROIAlignLayerKernel & operator= (NEROIAlignLayerKernel &&)=default
Default move assignment operator.
~NEROIAlignLayerKernel ()=default
Default destructor.
void configure (const ITensor *input, const ITensor *rois, ITensor *output, const ROIPoolingLayerInfo &pool_info)
Set the input and output tensors.
void run (const Window &window, const ThreadInfo &info) override
Execute the kernel on the passed window.
Public Member Functions inherited from ICPPKernel
virtual ~ICPPKernel ()=default
Default destructor.
virtual void run_nd (const Window &window, const ThreadInfo &info, const Window &thread_locator)
legacy compatibility layer for implemantions which do not support thread_locator In these cases we simply narrow the interface down the legacy version
virtual void run_op (ITensorPack &tensors, const Window &window, const ThreadInfo &info)
Execute the kernel on the passed window.
Public Member Functions inherited from IKernel
IKernel ()
Constructor.
virtual ~IKernel ()=default
Destructor.
virtual bool is_parallelisable () const
Indicates whether or not the kernel is parallelisable.
virtual BorderSize border_size () const
The size of the border for that kernel.
const Window & window () const
The maximum window the kernel can be executed on.
Static Public Member Functions
static Status validate (const ITensorInfo *input, const ITensorInfo *rois, ITensorInfo *output, const ROIPoolingLayerInfo &pool_info)
Static function to check if given info will lead to a valid configuration of NEROIAlignLayerKernel.
Detailed Description
Interface for the RoIAlign kernel.
Definition at line 35 of file NEROIAlignLayerKernel.h.
Constructor & Destructor Documentation
NEROIAlignLayerKernel() [1/3]
NEROIAlignLayerKernel ()
Constructor.
Definition at line 77 of file NEROIAlignLayerKernel.cpp.
     : _input(nullptr), _output(nullptr), _rois(nullptr), _pool_info(0, 0, 0.f)
 {
 }
NEROIAlignLayerKernel() [2/3]
NEROIAlignLayerKernel (const NEROIAlignLayerKernel &) delete
Prevent instances of this class from being copied (As this class contains pointers)
NEROIAlignLayerKernel() [3/3]
NEROIAlignLayerKernel (NEROIAlignLayerKernel &&) default
Default Move Constructor.
~NEROIAlignLayerKernel()
~NEROIAlignLayerKernel () default
Default destructor.
Member Function Documentation
configure()
void configure (const ITensor * input, const ITensor * rois, ITensor * output, const ROIPoolingLayerInfo & pool_info)
Set the input and output tensors.
Parameters
[in] input Source tensor. Data types supported: QASYMM8/F16/F32.
[in] rois ROIs tensor, it is a 2D tensor of size [5, N] (where N is the number of ROIs) containing top left and bottom right corner as coordinate of an image and batch_id of ROI [ batch_id, x1, y1, x2, y2 ]. Data types supported: QASYMM16 with scale of 0.125 and 0 offset if input is QASYMM8, otherwise same as input
[out] output Destination tensor. Data types supported: Same as input.
[in] pool_info Contains pooling operation information described in ROIPoolingLayerInfo.
Note
The x and y dimensions of output tensor must be the same as pool_info 's pooled width and pooled height.
The z dimensions of output tensor and input tensor must be the same.
The fourth dimension of output tensor must be the same as the number of elements in rois array.
Definition at line 82 of file NEROIAlignLayerKernel.cpp.
 {
     ARM_COMPUTE_ERROR_ON_NULLPTR(input, output, rois);
     ARM_COMPUTE_ERROR_THROW_ON(validate_arguments(input->info(), rois->info(), output->info(), pool_info));
     // Output auto inizialitation if not yet initialized
     const TensorShape output_shape = compute_roi_align_shape(*input->info(), *rois->info(), pool_info);
     auto_init_if_empty((*output->info()), output_shape, 1, input->info()->data_type(), input->info()->quantization_info());
     output->info()->set_data_layout(input->info()->data_layout());
     // Configure kernel window
     const unsigned int num_rois = rois->info()->dimension(1);
     Window             window;
     window.set(Window::DimX, Window::Dimension(0, num_rois));
     window.set(Window::DimY, Window::Dimension(0, 1));
     Coordinates coord;
     coord.set_num_dimensions(output->info()->num_dimensions());
     output->info()->set_valid_region(ValidRegion(coord, output->info()->tensor_shape()));
     // Set instance variables
     _input     = input;
     _rois      = rois;
     _output    = output;
     _pool_info = pool_info;
     INEKernel::configure(window);
 }
References ARM_COMPUTE_ERROR_ON_NULLPTR, ARM_COMPUTE_ERROR_THROW_ON, arm_compute::auto_init_if_empty(), arm_compute::misc::shape_calculator::compute_roi_align_shape(), ITensorInfo::dimension(), Window::DimX, Window::DimY, ITensor::info(), arm_compute::test::validation::input, ITensorInfo::num_dimensions(), arm_compute::test::validation::output_shape, Window::set(), ITensorInfo::set_data_layout(), Dimensions< T >::set_num_dimensions(), ITensorInfo::set_valid_region(), ITensorInfo::tensor_shape(), arm_compute::validate_arguments(), and IKernel::window().
name()
const char* name () const inline override virtual
Name of the kernel.
Returns
Kernel name
Implements ICPPKernel.
Definition at line 38 of file NEROIAlignLayerKernel.h.
     {
         return "NEROIAlignLayerKernel";
     }
operator=() [1/2]
NEROIAlignLayerKernel& operator= (const NEROIAlignLayerKernel &) delete
Prevent instances of this class from being copied (As this class contains pointers)
operator=() [2/2]
NEROIAlignLayerKernel& operator= (NEROIAlignLayerKernel &&) default
Default move assignment operator.
run()
void run (const Window & window, const ThreadInfo & info) override virtual
Execute the kernel on the passed window.
Warning
If is_parallelisable() returns false then the passed window must be equal to window()
Note
The window has to be a region within the window returned by the window() method
The width of the window has to be a multiple of num_elems_processed_per_iteration().
Parameters
[in] window Region on which to execute the kernel. (Must be a region of the window returned by window())
[in] info Info about executing thread and CPU.
Reimplemented from ICPPKernel.
Definition at line 264 of file NEROIAlignLayerKernel.cpp.
 {
     if(_input->info()->data_layout() == DataLayout::NCHW)
     {
         switch(_input->info()->data_type())
         {
             case DataType::QASYMM8:
             {
                 NEROIAlignLayerKernel::internal_run<DataLayout::NCHW, uint8_t, uint16_t>(window, info);
                 break;
             }
             case DataType::F32:
             {
                 NEROIAlignLayerKernel::internal_run<DataLayout::NCHW, float>(window, info);
                 break;
             }
 #ifdef __ARM_FEATURE_FP16_VECTOR_ARITHMETIC
             case DataType::F16:
             {
                 NEROIAlignLayerKernel::internal_run<DataLayout::NCHW, float16_t>(window, info);
                 break;
             }
 #endif // __ARM_FEATURE_FP16_VECTOR_ARITHMETIC
             default:
             {
                 ARM_COMPUTE_ERROR("DataType not supported");
                 break;
             }
         }
     }
     else if(_input->info()->data_layout() == DataLayout::NHWC)
     {
         switch(_input->info()->data_type())
         {
             case DataType::QASYMM8:
             {
                 NEROIAlignLayerKernel::internal_run<DataLayout::NHWC, uint8_t, uint16_t>(window, info);
                 break;
             }
             case DataType::F32:
             {
                 NEROIAlignLayerKernel::internal_run<DataLayout::NHWC, float>(window, info);
                 break;
             }
 #ifdef __ARM_FEATURE_FP16_VECTOR_ARITHMETIC
             case DataType::F16:
             {
                 NEROIAlignLayerKernel::internal_run<DataLayout::NHWC, float16_t>(window, info);
                 break;
             }
 #endif // __ARM_FEATURE_FP16_VECTOR_ARITHMETIC
             default:
             {
                 ARM_COMPUTE_ERROR("DataType not supported");
                 break;
             }
         }
     }
     else
     {
         ARM_COMPUTE_ERROR("Invalid layout");
     }
 }
References ARM_COMPUTE_ERROR, ITensorInfo::data_layout(), ITensorInfo::data_type(), arm_compute::F16, arm_compute::F32, ITensor::info(), arm_compute::test::validation::info, arm_compute::NCHW, arm_compute::NHWC, arm_compute::QASYMM8, and IKernel::window().
validate()
Status validate (const ITensorInfo * input, const ITensorInfo * rois, ITensorInfo * output, const ROIPoolingLayerInfo & pool_info) static
Static function to check if given info will lead to a valid configuration of NEROIAlignLayerKernel.
Parameters
[in] input Source tensor info. Data types supported: QASYMM8/F16/F32.
[in] rois ROIs tensor info. Data types supported: QASYMM16 with scale of 0.125 and 0 offset if input is QASYMM8, otherwise same as input
[in] output Destination tensor info. Data types supported: Same as input.
[in] pool_info Contains pooling operation information described in ROIPoolingLayerInfo.
Note
The x and y dimensions of output tensor must be the same as pool_info 's pooled width and pooled height.
The z dimensions of output tensor and input tensor must be the same.
The fourth dimension of output tensor must be the same as the number of elements in rois array.
Returns
a Status
Definition at line 110 of file NEROIAlignLayerKernel.cpp.
 {
     ARM_COMPUTE_RETURN_ON_ERROR(validate_arguments(input, rois, output, pool_info));
     return Status{};
 }
References ARM_COMPUTE_RETURN_ON_ERROR, arm_compute::test::validation::input, and arm_compute::validate_arguments().
Referenced by NEROIAlignLayer::validate().
The documentation for this class was generated from the following files:
arm_compute/core/NEON/kernels/NEROIAlignLayerKernel.h
src/core/NEON/kernels/NEROIAlignLayerKernel.cpp