Compute Library: NEComplexPixelWiseMultiplication Class Reference
NEComplexPixelWiseMultiplication Class Reference
Basic function to run NEComplexPixelWiseMultiplicationKernel.
#include <NEPixelWiseMultiplication.h>
Public Member Functions
void configure (ITensorInfo *input1, ITensorInfo *input2, ITensorInfo *output, const ActivationLayerInfo &act_info=ActivationLayerInfo())
Initialise the kernel's inputs, output.
Public Member Functions inherited from INEOperator
INEOperator (IRuntimeContext *ctx=nullptr)
Constructor.
INEOperator (const INEOperator &)=delete
Prevent instances of this class from being copied (As this class contains pointers)
INEOperator (INEOperator &&)=default
Default move constructor.
INEOperator & operator= (const INEOperator &)=delete
Prevent instances of this class from being copied (As this class contains pointers)
INEOperator & operator= (INEOperator &&)=default
Default move assignment operator.
void run (ITensorPack &tensors) override
Run the kernels contained in the function.
void prepare (ITensorPack &constants) override
Prepare the function for executing.
MemoryRequirements workspace () const override
Return the memory requirements required by the workspace.
Public Member Functions inherited from IOperator
virtual ~IOperator ()=default
Destructor.
Static Public Member Functions
static Status validate (const ITensorInfo *input1, const ITensorInfo *input2, const ITensorInfo *output, const ActivationLayerInfo &act_info=ActivationLayerInfo())
Static function to check if given info will lead to a valid configuration of NEComplexPixelWiseMultiplication.
Detailed Description
Basic function to run NEComplexPixelWiseMultiplicationKernel.
Definition at line 108 of file NEPixelWiseMultiplication.h.
Member Function Documentation
configure()
void configure (ITensorInfo * input1, ITensorInfo * input2, ITensorInfo * output, const ActivationLayerInfo & act_info = ActivationLayerInfo())
Initialise the kernel's inputs, output.
Parameters
[in,out] input1 An input tensor. Data types supported: F32. Number of channels supported: 2 (complex tensor). The input tensor is [in, out] because its TensorInfo might be modified inside the kernel in case of broadcasting of dimension 0.
[in,out] input2 An input tensor. Data types supported: same as input1. Number of channels supported: same as input1. The input tensor is [in, out] because its TensorInfo might be modified inside the kernel in case of broadcasting of dimension 0.
[out] output The output tensor. Data types supported: same as input1. Number of channels: same as input1.
[in] act_info (Optional) Activation layer information in case of a fused activation. Currently not supported.
Definition at line 51 of file NEPixelWiseMultiplication.cpp.
 {
     ARM_COMPUTE_UNUSED(act_info);
     auto k = arm_compute::support::cpp14::make_unique<NEComplexPixelWiseMultiplicationKernel>();
     k->configure(input1, input2, output);
     _kernel = std::move(k);
 }
References ARM_COMPUTE_UNUSED.
validate()
Status validate (const ITensorInfo * input1, const ITensorInfo * input2, const ITensorInfo * output, const ActivationLayerInfo & act_info = ActivationLayerInfo()) static
Static function to check if given info will lead to a valid configuration of NEComplexPixelWiseMultiplication.
Parameters
[in] input1 An input tensor info. Data types supported: F32. Number of channels supported: 2 (complex tensor).
[in] input2 An input tensor info. Data types supported: same as input1. Number of channels supported: same as input1.
[in] output The output tensor info. Data types supported: same as input1. Number of channels supported: same as input1.
[in] act_info (Optional) Activation layer information in case of a fused activation. Currently not supported.
Definition at line 59 of file NEPixelWiseMultiplication.cpp.
 {
     ARM_COMPUTE_RETURN_ERROR_ON(act_info.enabled());
     return NEComplexPixelWiseMultiplicationKernel::validate(input1, input2, output);
 }
References ARM_COMPUTE_RETURN_ERROR_ON, ActivationLayerInfo::enabled(), and NEComplexPixelWiseMultiplicationKernel::validate().
Referenced by NEComplexPixelWiseMultiplication::validate().
The documentation for this class was generated from the following files:
arm_compute/runtime/NEON/functions/NEPixelWiseMultiplication.h
src/runtime/NEON/functions/NEPixelWiseMultiplication.cpp