Compute Library: src/core/CL/cl_kernels/pooling_layer.cl File Reference
pooling_layer.cl File Reference
#include "helpers.h"
Macros
#define POOL_OP(x, y) ((x) + (y))
#define POW2_OP(x, vec_size) (x)
#define DIV_OP(x, y) (x * (1.f / y))
#define SQRT_OP(x) sqrt((x))
#define DIV_OP_NHWC(x, y) (x * (VEC_DATA_TYPE(ACC_DATA_TYPE, 8))(1.f / y))
#define VLOAD_AND_CONVERT_TO_ACC_DATA_TYPE(n, offset, ptr) vload##n(offset, ptr)
#define POOLING3x3_STRIDE1(res, input, output)
#define POOLING3x3_STRIDE2(res, input, output)
#define POOLING3x3_STRIDE3(res, input, output)
Functions
ACC_DATA_TYPE calculate_avg_scale (const int pool_size_x, const int pool_size_y, const int upper_bound_w, const int upper_bound_h, const int pad_x, const int pad_y, const int stride_x, const int stride_y)
__kernel void pooling_layer_2 (__global uchar *input_ptr, uint input_stride_x, uint input_step_x, uint input_stride_y, uint input_step_y, uint input_stride_z, uint input_step_z, uint input_offset_first_element_in_bytes, __global uchar *output_ptr, uint output_stride_x, uint output_step_x, uint output_stride_y, uint output_step_y, uint output_stride_z, uint output_step_z, uint output_offset_first_element_in_bytes)
Performs a pooling function of pool size equal to 2.
__kernel void pooling_layer_3 (__global uchar *input_ptr, uint input_stride_x, uint input_step_x, uint input_stride_y, uint input_step_y, uint input_stride_z, uint input_step_z, uint input_offset_first_element_in_bytes, __global uchar *output_ptr, uint output_stride_x, uint output_step_x, uint output_stride_y, uint output_step_y, uint output_stride_z, uint output_step_z, uint output_offset_first_element_in_bytes)
Performs a pooling function of pool size equal to 3.
ACC_DATA_TYPE calculate_avg_scale_nhwc (const int pool_size_x, const int pool_size_y, int upper_bound_w, int upper_bound_h, const int pad_x, const int pad_y, const int stride_x, const int stride_y)
__kernel void pooling_layer_MxN_nhwc (__global uchar *input_ptr, uint input_stride_x, uint input_step_x, uint input_stride_y, uint input_step_y, uint input_stride_z, uint input_step_z, uint input_stride_w, uint input_step_w, uint input_offset_first_element_in_bytes, __global uchar *output_ptr, uint output_stride_x, uint output_step_x, uint output_stride_y, uint output_step_y, uint output_stride_z, uint output_step_z, uint output_stride_w, uint output_step_w, uint output_offset_first_element_in_bytes)
Performs a pooling function of pool size equal to N (NHWC)
__kernel void pooling_layer_2_nchw_indices_fp32 (__global uchar *input_ptr, uint input_stride_x, uint input_step_x, uint input_stride_y, uint input_step_y, uint input_stride_z, uint input_step_z, uint input_offset_first_element_in_bytes, __global uchar *output_ptr, uint output_stride_x, uint output_step_x, uint output_stride_y, uint output_step_y, uint output_stride_z, uint output_step_z, uint output_offset_first_element_in_bytes, __global uchar *indices_ptr, uint indices_stride_x, uint indices_step_x, uint indices_stride_y, uint indices_step_y, uint indices_stride_z, uint indices_step_z, uint indices_offset_first_element_in_bytes)
Performs a MAX pooling of pool size equal to 2, and record max value indices for NCHW.
__kernel void pooling_layer_2_nchw_indices_fp16 (__global uchar *input_ptr, uint input_stride_x, uint input_step_x, uint input_stride_y, uint input_step_y, uint input_stride_z, uint input_step_z, uint input_offset_first_element_in_bytes, __global uchar *output_ptr, uint output_stride_x, uint output_step_x, uint output_stride_y, uint output_step_y, uint output_stride_z, uint output_step_z, uint output_offset_first_element_in_bytes, __global uchar *indices_ptr, uint indices_stride_x, uint indices_step_x, uint indices_stride_y, uint indices_step_y, uint indices_stride_z, uint indices_step_z, uint indices_offset_first_element_in_bytes)
Performs a MAX pooling of pool size equal to 2, and record max value indices for NCHW.
__kernel void pooling_layer_2_nhwc_indices_fp32 (__global uchar *input_ptr, uint input_stride_x, uint input_step_x, uint input_stride_y, uint input_step_y, uint input_stride_z, uint input_step_z, uint input_stride_w, uint input_step_w, uint input_offset_first_element_in_bytes, __global uchar *output_ptr, uint output_stride_x, uint output_step_x, uint output_stride_y, uint output_step_y, uint output_stride_z, uint output_step_z, uint output_stride_w, uint output_step_w, uint output_offset_first_element_in_bytes, __global uchar *indices_ptr, uint indices_stride_x, uint indices_step_x, uint indices_stride_y, uint indices_step_y, uint indices_stride_z, uint indices_step_z, uint indices_stride_w, uint indices_step_w, uint indices_offset_first_element_in_bytes)
Performs a MAX pooling of pool size equal to 2, and record max value indices for NHWC.
__kernel void pooling_layer_2_nhwc_indices_fp16 (__global uchar *input_ptr, uint input_stride_x, uint input_step_x, uint input_stride_y, uint input_step_y, uint input_stride_z, uint input_step_z, uint input_stride_w, uint input_step_w, uint input_offset_first_element_in_bytes, __global uchar *output_ptr, uint output_stride_x, uint output_step_x, uint output_stride_y, uint output_step_y, uint output_stride_z, uint output_step_z, uint output_stride_w, uint output_step_w, uint output_offset_first_element_in_bytes, __global uchar *indices_ptr, uint indices_stride_x, uint indices_step_x, uint indices_stride_y, uint indices_step_y, uint indices_stride_z, uint indices_step_z, uint indices_stride_w, uint indices_step_w, uint indices_offset_first_element_in_bytes)
Performs a MAX pooling of pool size equal to 2, and record max value indices for NHWC.
Macro Definition Documentation
DIV_OP
#define DIV_OP (x, y) (x * (1.f / y))
Definition at line 38 of file pooling_layer.cl.
DIV_OP_NHWC
#define DIV_OP_NHWC (x, y) (x * (VEC_DATA_TYPE(ACC_DATA_TYPE, 8))(1.f / y))
Definition at line 41 of file pooling_layer.cl.
POOL_OP
#define POOL_OP (x, y) ((x) + (y))
Definition at line 27 of file pooling_layer.cl.
POOLING3x3_STRIDE1
#define POOLING3x3_STRIDE1 (res, input, output)
Definition at line 59 of file pooling_layer.cl.
POOLING3x3_STRIDE2
#define POOLING3x3_STRIDE2 (res, input, output)
Definition at line 102 of file pooling_layer.cl.
POOLING3x3_STRIDE3
#define POOLING3x3_STRIDE3 (res, input, output)
Value:
({                                                                                                                                       \
        VEC_DATA_TYPE(ACC_DATA_TYPE, 8)                                                                                                      \
        data00 = VLOAD_AND_CONVERT_TO_ACC_DATA_TYPE(8, 0, (__global DATA_TYPE *)tensor3D_offset(&input, 0, 0, 0));                           \
        VEC_DATA_TYPE(ACC_DATA_TYPE, 4)                                                                                                      \
        data01 = VLOAD_AND_CONVERT_TO_ACC_DATA_TYPE(4, 0, (__global DATA_TYPE *)tensor3D_offset(&input, 0, 0, 0) + 8);                       \
        VEC_DATA_TYPE(ACC_DATA_TYPE, 8)                                                                                                      \
        data10 = VLOAD_AND_CONVERT_TO_ACC_DATA_TYPE(8, 0, (__global DATA_TYPE *)tensor3D_offset(&input, 0, 1, 0));                           \
        VEC_DATA_TYPE(ACC_DATA_TYPE, 4)                                                                                                      \
        data11 = VLOAD_AND_CONVERT_TO_ACC_DATA_TYPE(4, 0, (__global DATA_TYPE *)tensor3D_offset(&input, 0, 1, 0) + 8);                       \
        VEC_DATA_TYPE(ACC_DATA_TYPE, 8)                                                                                                      \
        data20 = VLOAD_AND_CONVERT_TO_ACC_DATA_TYPE(8, 0, (__global DATA_TYPE *)tensor3D_offset(&input, 0, 2, 0));                           \
        VEC_DATA_TYPE(ACC_DATA_TYPE, 4)                                                                                                      \
        data21 = VLOAD_AND_CONVERT_TO_ACC_DATA_TYPE(4, 0, (__global DATA_TYPE *)tensor3D_offset(&input, 0, 2, 0) + 8);                       \
        data00 = POW2_OP(data00, 8);                                                                                                         \
        data01 = POW2_OP(data01, 4);                                                                                                         \
        data10 = POW2_OP(data10, 8);                                                                                                         \
        data11 = POW2_OP(data11, 4);                                                                                                         \
        data20 = POW2_OP(data20, 8);                                                                                                         \
        data21 = POW2_OP(data21, 4);                                                                                                         \
        \
        data00 = POOL_OP(data00, data10);                                                                                                    \
        data01 = POOL_OP(data01, data11);                                                                                                    \
        data00 = POOL_OP(data00, data20);                                                                                                    \
        data01 = POOL_OP(data01, data21);                                                                                                    \
        \
        res = POOL_OP((VEC_DATA_TYPE(ACC_DATA_TYPE, 4))(data00.s036, data01.s1), (VEC_DATA_TYPE(ACC_DATA_TYPE, 4))(data00.s147, data01.s2)); \
        res = POOL_OP(res, (VEC_DATA_TYPE(ACC_DATA_TYPE, 4))(data00.s25, data01.s03));                                                       \
    })
Definition at line 142 of file pooling_layer.cl.
POW2_OP
#define POW2_OP (x, vec_size) (x)
Definition at line 35 of file pooling_layer.cl.
SQRT_OP
#define SQRT_OP (x) sqrt((x))
Definition at line 39 of file pooling_layer.cl.
VLOAD_AND_CONVERT_TO_ACC_DATA_TYPE
#define VLOAD_AND_CONVERT_TO_ACC_DATA_TYPE (n, offset, ptr) vload##n(offset, ptr)
Definition at line 56 of file pooling_layer.cl.
Function Documentation
calculate_avg_scale()
ACC_DATA_TYPE calculate_avg_scale (const int pool_size_x, const int pool_size_y, const int upper_bound_w, const int upper_bound_h, const int pad_x, const int pad_y, const int stride_x, const int stride_y)
Definition at line 172 of file pooling_layer.cl.
 {
     int       start_x = get_global_id(0) * stride_x - pad_x;
     int       start_y = get_global_id(1) * stride_y - pad_y;
     const int end_x   = min(start_x + pool_size_x, upper_bound_w);
     const int end_y   = min(start_y + pool_size_y, upper_bound_h);
 #if defined(EXCLUDE_PADDING)
     start_x = max(0, start_x);
     start_y = max(0, start_y);
 #endif /* defined(EXCLUDE_PADDING) */
     return ((end_y - start_y) * (end_x - start_x));
 }
Referenced by pooling_layer_2(), and pooling_layer_3().
calculate_avg_scale_nhwc()
ACC_DATA_TYPE calculate_avg_scale_nhwc (const int pool_size_x, const int pool_size_y, int upper_bound_w, int upper_bound_h, const int pad_x, const int pad_y, const int stride_x, const int stride_y)
Definition at line 484 of file pooling_layer.cl.
 {
     int start_x = get_global_id(1) * stride_x - pad_x;
 #if defined(DST_DEPTH)
     int start_y = (get_global_id(2) % DST_DEPTH) * stride_y - pad_y;
 #else  /* defined(DST_DEPTH) */
     int       start_y    = get_global_id(2) * stride_y - pad_y;
 #endif /* defined(DST_DEPTH) */
 #if !defined(EXCLUDE_PADDING)
     upper_bound_w += pad_x;
     upper_bound_h += pad_y;
 #endif /* defined(EXCLUDE_PADDING) */
     const int end_x = min(start_x + pool_size_x, upper_bound_w);
     const int end_y = min(start_y + pool_size_y, upper_bound_h);
 #if defined(EXCLUDE_PADDING)
     start_x = max(0, start_x);
     start_y = max(0, start_y);
 #endif /* defined(EXCLUDE_PADDING) */
     return ((end_y - start_y) * (end_x - start_x));
 }
Referenced by pooling_layer_MxN_nhwc().
pooling_layer_2()
__kernel void pooling_layer_2 (__global uchar * input_ptr, uint input_stride_x, uint input_step_x, uint input_stride_y, uint input_step_y, uint input_stride_z, uint input_step_z, uint input_offset_first_element_in_bytes, __global uchar * output_ptr, uint output_stride_x, uint output_step_x, uint output_stride_y, uint output_step_y, uint output_stride_z, uint output_step_z, uint output_offset_first_element_in_bytes)
Performs a pooling function of pool size equal to 2.
Note
Datatype must be passed using -DDATA_TYPE e.g. -DDATA_TYPE=float. Supported data types are F16/F32;
In case of average pooling the following information must be passed at compile time: -DPOOL_AVG or -DPOOL_L2 must be provided otherwise max pooling will be performed. -DMAX_WIDTH and -DMAX_HEIGHT which are the maximum accessible indeces in x and y dimensions (width + pad) -DSTRIDE_X and -DSTRIDE_Y which are the steps of the window along the x and y directions -DPAD_X and -DPAD_Y which are the pooling paddings in x and y dimension
Parameters
[in] input_ptr Pointer to the source tensor. Supported data types: F16/F32
[in] input_stride_x Stride of the source tensor in X dimension (in bytes)
[in] input_step_x input_stride_x * number of elements along X processed per workitem(in bytes)
[in] input_stride_y Stride of the source tensor in Y dimension (in bytes)
[in] input_step_y input_stride_y * number of elements along Y processed per workitem(in bytes)
[in] input_stride_z Stride of the source tensor in Z dimension (in bytes)
[in] input_step_z input_stride_z * number of elements along Z processed per workitem(in bytes)
[in] input_offset_first_element_in_bytes The offset of the first element in the source tensor
[out] output_ptr Pointer to the destination tensor. Supported data types: same as input_ptr
[in] output_stride_x Stride of the destination tensor in X dimension (in bytes)
[in] output_step_x output_stride_x * number of elements along X processed per workitem(in bytes)
[in] output_stride_y Stride of the destination tensor in Y dimension (in bytes)
[in] output_step_y output_stride_y * number of elements along Y processed per workitem(in bytes)
[in] output_stride_z Stride of the source tensor in Z dimension (in bytes)
[in] output_step_z output_stride_z * number of elements along Z processed per workitem(in bytes)
[in] output_offset_first_element_in_bytes The offset of the first element in the destination tensor
Definition at line 212 of file pooling_layer.cl.
 {
     // Get pixels pointer
     Tensor3D input  = CONVERT_TO_TENSOR3D_STRUCT(input);
     Tensor3D output = CONVERT_TO_TENSOR3D_STRUCT(output);
     // Load data
     VEC_DATA_TYPE(ACC_DATA_TYPE, 2)
     data0 = VLOAD_AND_CONVERT_TO_ACC_DATA_TYPE(2, 0, (__global DATA_TYPE *)tensor3D_offset(&input, 0, 0, 0));
     VEC_DATA_TYPE(ACC_DATA_TYPE, 2)
     data1 = VLOAD_AND_CONVERT_TO_ACC_DATA_TYPE(2, 0, (__global DATA_TYPE *)tensor3D_offset(&input, 0, 1, 0));
 #if defined(POOL_L2)
     // Raise to power of 2 for L2 Pooling
     data0 = POW2_OP(data0, 2);
     data1 = POW2_OP(data1, 2);
 #endif /* defined(POOL_L2) */
     // Perform calculations
     data0             = POOL_OP(data0, data1);
     ACC_DATA_TYPE res = POOL_OP(data0.s0, data0.s1);
 #if defined(POOL_AVG) || defined(POOL_L2)
     // Divide by pool region in case of average or l2 pooling
     res = DIV_OP(res, calculate_avg_scale(2, 2, MAX_WIDTH, MAX_HEIGHT, PAD_X, PAD_Y, STRIDE_X, STRIDE_Y));
 #endif /* defined(POOL_AVG) || defined(POOL_L2) */
 #if defined(POOL_L2)
     // Take square root of the result in L2 pooling
     res = SQRT_OP(res);
 #endif /* defined(POOL_L2) */
     // Store result
     *(__global DATA_TYPE *)output.ptr = (DATA_TYPE)res;
 }
References calculate_avg_scale(), CONVERT_TO_TENSOR3D_STRUCT, DATA_TYPE, DIV_OP, arm_compute::test::validation::input, POOL_OP, POW2_OP, Tensor3D::ptr, SQRT_OP, tensor3D_offset(), VEC_DATA_TYPE, and VLOAD_AND_CONVERT_TO_ACC_DATA_TYPE.
pooling_layer_2_nchw_indices_fp16()
__kernel void pooling_layer_2_nchw_indices_fp16 (__global uchar * input_ptr, uint input_stride_x, uint input_step_x, uint input_stride_y, uint input_step_y, uint input_stride_z, uint input_step_z, uint input_offset_first_element_in_bytes, __global uchar * output_ptr, uint output_stride_x, uint output_step_x, uint output_stride_y, uint output_step_y, uint output_stride_z, uint output_step_z, uint output_offset_first_element_in_bytes, __global uchar * indices_ptr, uint indices_stride_x, uint indices_step_x, uint indices_stride_y, uint indices_step_y, uint indices_stride_z, uint indices_step_z, uint indices_offset_first_element_in_bytes)
Performs a MAX pooling of pool size equal to 2, and record max value indices for NCHW.
Note
Datatype must be passed using -DDATA_TYPE e.g. -DDATA_TYPE=half. Supported data types are F16
Pool sizes must be passed using -DPOOL_SIZE_X and -DPOOL_SIZE_Y e.g. -DPOOL_SIZE_X=13;
Tensors width and height must be passed at compile time using -DMAX_WIDTH and -DMAX_HEIGHT
Pool strides must be passed at compile time using -DSTRIDE_X and -DSTRIDE_Y which are the steps of the window along the x and y directions
Tensor padding values must be passed at compile time using PAD_TENSOR_LEFT, PAD_TENSOR_RIGHT, PAD_TENSOR_TOP and PAD_TENSOR_BOTTOM
Parameters
[in] input_ptr Pointer to the source tensor. Supported data types: F16
[in] input_stride_x Stride of the source tensor in X dimension (in bytes)
[in] input_step_x input_stride_x * number of elements along X processed per workitem(in bytes)
[in] input_stride_y Stride of the source tensor in Y dimension (in bytes)
[in] input_step_y input_stride_y * number of elements along Y processed per workitem(in bytes)
[in] input_stride_z Stride of the source tensor in Z dimension (in bytes)
[in] input_step_z input_stride_z * number of elements along Z processed per workitem(in bytes)
[in] input_offset_first_element_in_bytes The offset of the first element in the source tensor
[out] output_ptr Pointer to the destination tensor. Supported data types: same as input_ptr
[in] output_stride_x Stride of the destination tensor in X dimension (in bytes)
[in] output_step_x output_stride_x * number of elements along X processed per workitem(in bytes)
[in] output_stride_y Stride of the destination tensor in Y dimension (in bytes)
[in] output_step_y output_stride_y * number of elements along Y processed per workitem(in bytes)
[in] output_stride_z Stride of the source tensor in Z dimension (in bytes)
[in] output_step_z output_stride_z * number of elements along Z processed per workitem(in bytes)
[in] output_offset_first_element_in_bytes The offset of the first element in the destination tensor
[in] indices_ptr Pointer to the indices tensor. Supported data types: U32
[in] indices_stride_x Stride of the indices tensor in X dimension (in bytes)
[in] indices_step_x indices_stride_x * number of elements along X processed per workitem(in bytes)
[in] indices_stride_y Stride of the indices tensor in Y dimension (in bytes)
[in] indices_step_y indices_stride_y * number of elements along Y processed per workitem(in bytes)
[in] indices_stride_z Stride of the indices tensor in Z dimension (in bytes)
[in] indices_step_z indices_stride_z * number of elements along Z processed per workitem(in bytes)
[in] indices_offset_first_element_in_bytes The offset of the first element in the indices tensor
Definition at line 798 of file pooling_layer.cl.
 {
     // Get pixels pointer
     Tensor3D input   = CONVERT_TO_TENSOR3D_STRUCT(input);
     Tensor3D output  = CONVERT_TO_TENSOR3D_STRUCT(output);
     Tensor3D indices = CONVERT_TO_TENSOR3D_STRUCT(indices);
     // Load data
     half2 data0 = VLOAD(2)(0, (__global half *)tensor3D_offset(&input, 0, 0, 0));
     half2 data1 = VLOAD(2)(0, (__global half *)tensor3D_offset(&input, 0, 1, 0));
     // Perform calculations
     half data0_max = POOL_OP(data0.s0, data0.s1);
     half data1_max = POOL_OP(data1.s0, data1.s1);
     half res       = POOL_OP(data0_max, data1_max);
     // Store result
     *(__global half *)output.ptr = res;
 #if defined(PAD_TENSOR_LEFT) && defined(PAD_TENSOR_RIGHT) && defined(PAD_TENSOR_TOP) && defined(PAD_TENSOR_BOTTOM)
     uint offset_top    = 0;
     uint offset_bottom = 0;
     offset_no_padding_nchw(&input, &offset_top, &offset_bottom);
     uint index0 = select(offset_top + 1, offset_top, isgreaterequal(data0.s0, data0.s1));
     uint index1 = select(offset_bottom + 1, offset_bottom, isgreaterequal(data1.s0, data1.s1));
     uint index  = select(index1, index0, isgreaterequal(data0_max, data1_max));
     *(__global uint *)indices.ptr = index;
 #endif //defined(PAD_TENSOR_LEFT) && defined(PAD_TENSOR_RIGHT) && defined(PAD_TENSOR_TOP) && defined(PAD_TENSOR_BOTTOM)
 }
References CONVERT_TO_TENSOR3D_STRUCT, arm_compute::test::validation::input, POOL_OP, Tensor3D::ptr, arm_compute::test::validation::select, tensor3D_offset(), and VLOAD.
pooling_layer_2_nchw_indices_fp32()
__kernel void pooling_layer_2_nchw_indices_fp32 (__global uchar * input_ptr, uint input_stride_x, uint input_step_x, uint input_stride_y, uint input_step_y, uint input_stride_z, uint input_step_z, uint input_offset_first_element_in_bytes, __global uchar * output_ptr, uint output_stride_x, uint output_step_x, uint output_stride_y, uint output_step_y, uint output_stride_z, uint output_step_z, uint output_offset_first_element_in_bytes, __global uchar * indices_ptr, uint indices_stride_x, uint indices_step_x, uint indices_stride_y, uint indices_step_y, uint indices_stride_z, uint indices_step_z, uint indices_offset_first_element_in_bytes)
Performs a MAX pooling of pool size equal to 2, and record max value indices for NCHW.
Note
Datatype must be passed using -DDATA_TYPE e.g. -DDATA_TYPE=half. Supported data types are F32
Pool sizes must be passed using -DPOOL_SIZE_X and -DPOOL_SIZE_Y e.g. -DPOOL_SIZE_X=13;
Tensors width and height must be passed at compile time using -DMAX_WIDTH and -DMAX_HEIGHT
Pool strides must be passed at compile time using -DSTRIDE_X and -DSTRIDE_Y which are the steps of the window along the x and y directions
Tensor padding values must be passed at compile time using PAD_TENSOR_LEFT, PAD_TENSOR_RIGHT, PAD_TENSOR_TOP and PAD_TENSOR_BOTTOM
Parameters
[in] input_ptr Pointer to the source tensor. Supported data types: F32
[in] input_stride_x Stride of the source tensor in X dimension (in bytes)
[in] input_step_x input_stride_x * number of elements along X processed per workitem(in bytes)
[in] input_stride_y Stride of the source tensor in Y dimension (in bytes)
[in] input_step_y input_stride_y * number of elements along Y processed per workitem(in bytes)
[in] input_stride_z Stride of the source tensor in Z dimension (in bytes)
[in] input_step_z input_stride_z * number of elements along Z processed per workitem(in bytes)
[in] input_offset_first_element_in_bytes The offset of the first element in the source tensor
[out] output_ptr Pointer to the destination tensor. Supported data types: same as input_ptr
[in] output_stride_x Stride of the destination tensor in X dimension (in bytes)
[in] output_step_x output_stride_x * number of elements along X processed per workitem(in bytes)
[in] output_stride_y Stride of the destination tensor in Y dimension (in bytes)
[in] output_step_y output_stride_y * number of elements along Y processed per workitem(in bytes)
[in] output_stride_z Stride of the source tensor in Z dimension (in bytes)
[in] output_step_z output_stride_z * number of elements along Z processed per workitem(in bytes)
[in] output_offset_first_element_in_bytes The offset of the first element in the destination tensor
[in] indices_ptr Pointer to the indices tensor. Supported data types: U32
[in] indices_stride_x Stride of the indices tensor in X dimension (in bytes)
[in] indices_step_x indices_stride_x * number of elements along X processed per workitem(in bytes)
[in] indices_stride_y Stride of the indices tensor in Y dimension (in bytes)
[in] indices_step_y indices_stride_y * number of elements along Y processed per workitem(in bytes)
[in] indices_stride_z Stride of the indices tensor in Z dimension (in bytes)
[in] indices_step_z indices_stride_z * number of elements along Z processed per workitem(in bytes)
[in] indices_offset_first_element_in_bytes The offset of the first element in the indices tensor
Definition at line 728 of file pooling_layer.cl.
 {
     // Get pixels pointer
     Tensor3D input   = CONVERT_TO_TENSOR3D_STRUCT(input);
     Tensor3D output  = CONVERT_TO_TENSOR3D_STRUCT(output);
     Tensor3D indices = CONVERT_TO_TENSOR3D_STRUCT(indices);
     // Load data
     float2 data0 = VLOAD(2)(0, (__global float *)tensor3D_offset(&input, 0, 0, 0));
     float2 data1 = VLOAD(2)(0, (__global float *)tensor3D_offset(&input, 0, 1, 0));
     // Perform calculations
     float data0_max = POOL_OP(data0.s0, data0.s1);
     float data1_max = POOL_OP(data1.s0, data1.s1);
     float res       = POOL_OP(data0_max, data1_max);
     // Store result
     *(__global float *)output.ptr = res;
 #if defined(PAD_TENSOR_LEFT) && defined(PAD_TENSOR_RIGHT) && defined(PAD_TENSOR_TOP) && defined(PAD_TENSOR_BOTTOM)
     uint offset_top    = 0;
     uint offset_bottom = 0;
     offset_no_padding_nchw(&input, &offset_top, &offset_bottom);
     uint index0 = select(offset_top + 1, offset_top, isgreaterequal(data0.s0, data0.s1));
     uint index1 = select(offset_bottom + 1, offset_bottom, isgreaterequal(data1.s0, data1.s1));
     uint index  = select(index1, index0, isgreaterequal(data0_max, data1_max));
     *(__global uint *)indices.ptr = index;
 #endif //defined(PAD_TENSOR_LEFT) && defined(PAD_TENSOR_RIGHT) && defined(PAD_TENSOR_TOP) && defined(PAD_TENSOR_BOTTOM)
 }
References CONVERT_TO_TENSOR3D_STRUCT, arm_compute::test::validation::input, POOL_OP, Tensor3D::ptr, arm_compute::test::validation::select, tensor3D_offset(), and VLOAD.
pooling_layer_2_nhwc_indices_fp16()
__kernel void pooling_layer_2_nhwc_indices_fp16 (__global uchar * input_ptr, uint input_stride_x, uint input_step_x, uint input_stride_y, uint input_step_y, uint input_stride_z, uint input_step_z, uint input_stride_w, uint input_step_w, uint input_offset_first_element_in_bytes, __global uchar * output_ptr, uint output_stride_x, uint output_step_x, uint output_stride_y, uint output_step_y, uint output_stride_z, uint output_step_z, uint output_stride_w, uint output_step_w, uint output_offset_first_element_in_bytes, __global uchar * indices_ptr, uint indices_stride_x, uint indices_step_x, uint indices_stride_y, uint indices_step_y, uint indices_stride_z, uint indices_step_z, uint indices_stride_w, uint indices_step_w, uint indices_offset_first_element_in_bytes)
Performs a MAX pooling of pool size equal to 2, and record max value indices for NHWC.
Note
Datatype must be passed using -DDATA_TYPE e.g. -DDATA_TYPE=half. Supported data types are F16
Pool sizes must be passed using -DPOOL_SIZE_X and -DPOOL_SIZE_Y e.g. -DPOOL_SIZE_X=13;
Tensors width and height must be passed at compile time using -DMAX_WIDTH and -DMAX_HEIGHT
Pool strides must be passed at compile time using -DSTRIDE_X and -DSTRIDE_Y which are the steps of the window along the x and y directions
Tensor padding values must be passed at compile time using PAD_TENSOR_LEFT, PAD_TENSOR_RIGHT, PAD_TENSOR_TOP and PAD_TENSOR_BOTTOM
Parameters
[in] input_ptr Pointer to the source tensor. Supported data types: F16
[in] input_stride_x Stride of the source tensor in X dimension (in bytes)
[in] input_step_x input_stride_x * number of elements along X processed per workitem(in bytes)
[in] input_stride_y Stride of the source tensor in Y dimension (in bytes)
[in] input_step_y input_stride_y * number of elements along Y processed per workitem(in bytes)
[in] input_stride_z Stride of the source tensor in Z dimension (in bytes)
[in] input_step_z input_stride_z * number of elements along Z processed per workitem(in bytes)
[in] input_stride_w Stride of the source tensor in W dimension (in bytes)
[in] input_step_w input_stride_w * number of elements along W processed per workitem(in bytes)
[in] input_offset_first_element_in_bytes The offset of the first element in the source tensor
[out] output_ptr Pointer to the destination tensor. Supported data types: same as input_ptr
[in] output_stride_x Stride of the destination tensor in X dimension (in bytes)
[in] output_step_x output_stride_x * number of elements along X processed per workitem(in bytes)
[in] output_stride_y Stride of the destination tensor in Y dimension (in bytes)
[in] output_step_y output_stride_y * number of elements along Y processed per workitem(in bytes)
[in] output_stride_z Stride of the destination tensor in Z dimension (in bytes)
[in] output_step_z output_stride_z * number of elements along Z processed per workitem(in bytes)
[in] output_stride_w Stride of the destination tensor in W dimension (in bytes)
[in] output_step_w output_stride_w * number of elements along W processed per workitem(in bytes)
[in] output_offset_first_element_in_bytes The offset of the first element in the destination tensor
[in] indices_ptr Pointer to the indices tensor. Supported data types: U32
[in] indices_stride_x Stride of the indices tensor in X dimension (in bytes)
[in] indices_step_x indices_stride_x * number of elements along X processed per workitem(in bytes)
[in] indices_stride_y Stride of the indices tensor in Y dimension (in bytes)
[in] indices_step_y indices_stride_y * number of elements along Y processed per workitem(in bytes)
[in] indices_stride_z Stride of the indices tensor in Z dimension (in bytes)
[in] indices_step_z indices_stride_z * number of elements along Z processed per workitem(in bytes)
[in] indices_stride_w Stride of the indices tensor in W dimension (in bytes)
[in] indices_step_w indices_stride_w * number of elements along W processed per workitem(in bytes)
[in] indices_offset_first_element_in_bytes The offset of the first element in the indices tensor
Definition at line 974 of file pooling_layer.cl.
 {
     // Get pixels pointer
 #if defined(DST_DEPTH)
     Tensor4D input   = CONVERT_TO_TENSOR4D_STRUCT(input, DST_DEPTH);
     Tensor4D output  = CONVERT_TO_TENSOR4D_STRUCT(output, DST_DEPTH);
     Tensor4D indices = CONVERT_TO_TENSOR4D_STRUCT(indices, DST_DEPTH);
 #else  /* defined(DST_DEPTH) */
     Tensor3D input        = CONVERT_TO_TENSOR3D_STRUCT(input);
     Tensor3D output       = CONVERT_TO_TENSOR3D_STRUCT(output);
     Tensor3D indices      = CONVERT_TO_TENSOR3D_STRUCT(indices);
 #endif /* defined(DST_DEPTH) */
 #if defined(DST_DEPTH)
     // Load data
     half8 data_top0    = VLOAD(8)(0, (__global half *)tensor4D_offset(&input, 0, 0, 0, 0));
     half8 data_top1    = VLOAD(8)(0, (__global half *)tensor4D_offset(&input, 0, 1, 0, 0));
     half8 data_bottom0 = VLOAD(8)(0, (__global half *)tensor4D_offset(&input, 0, 0, 1, 0));
     half8 data_bottom1 = VLOAD(8)(0, (__global half *)tensor4D_offset(&input, 0, 1, 1, 0));
 #else  /* defined(DST_DEPTH) */
     // Load data
     half8 data_top0    = VLOAD(8)(0, (__global half *)tensor3D_offset(&input, 0, 0, 0));
     half8 data_top1    = VLOAD(8)(0, (__global half *)tensor3D_offset(&input, 0, 1, 0));
     half8 data_bottom0 = VLOAD(8)(0, (__global half *)tensor3D_offset(&input, 0, 0, 1));
     half8 data_bottom1 = VLOAD(8)(0, (__global half *)tensor3D_offset(&input, 0, 1, 1));
 #endif /* defined(DST_DEPTH) */
     half8 data_top_max    = POOL_OP(data_top0, data_top1);
     half8 data_bottom_max = POOL_OP(data_bottom0, data_bottom1);
     half8 data_max        = POOL_OP(data_top_max, data_bottom_max);
     vstore8(data_max, 0, (__global half *)output.ptr);
 #if defined(PAD_TENSOR_LEFT) && defined(PAD_TENSOR_RIGHT) && defined(PAD_TENSOR_TOP) && defined(PAD_TENSOR_BOTTOM)
     uint offset_x0_int = 0;
     uint offset_x1_int = 0;
     uint offset_x2_int = 0;
     uint offset_x3_int = 0;
 #if defined(DST_DEPTH)
     offset_no_padding_nhwc_4D(&input, &offset_x0_int, &offset_x1_int, &offset_x2_int, &offset_x3_int);
 #else  /* defined(DST_DEPTH) */
     offset_no_padding_nhwc_3D(&input, &offset_x0_int, &offset_x1_int, &offset_x2_int, &offset_x3_int);
 #endif /* defined(DST_DEPTH) */
     ushort offset_x0 = (ushort)offset_x0_int;
     ushort offset_x1 = (ushort)offset_x1_int;
     ushort offset_x2 = (ushort)offset_x2_int;
     ushort offset_x3 = (ushort)offset_x3_int;
     ushort8 voffset_x0 = { offset_x0, offset_x0 + 1, offset_x0 + 2, offset_x0 + 3, offset_x0 + 4, offset_x0 + 5, offset_x0 + 6, offset_x0 + 7 };
     ushort8 voffset_x1 = { offset_x1, offset_x1 + 1, offset_x1 + 2, offset_x1 + 3, offset_x1 + 4, offset_x1 + 5, offset_x1 + 6, offset_x1 + 7 };
     ushort8 voffset_x2 = { offset_x2, offset_x2 + 1, offset_x2 + 2, offset_x2 + 3, offset_x2 + 4, offset_x2 + 5, offset_x2 + 6, offset_x2 + 7 };
     ushort8 voffset_x3 = { offset_x3, offset_x3 + 1, offset_x3 + 2, offset_x3 + 3, offset_x3 + 4, offset_x3 + 5, offset_x3 + 6, offset_x3 + 7 };
     ushort8 index0 = select(voffset_x1, voffset_x0, isgreaterequal(data_top0, data_top1));
     ushort8 index1 = select(voffset_x3, voffset_x2, isgreaterequal(data_bottom0, data_bottom1));
     ushort8 index  = select(index1, index0, isgreaterequal(data_top_max, data_bottom_max));
     vstore8(CONVERT(index, uint8), 0, (__global uint *)indices.ptr);
 #endif /* defined(PAD_TENSOR_LEFT) && defined(PAD_TENSOR_RIGHT) && defined(PAD_TENSOR_TOP) && defined(PAD_TENSOR_BOTTOM */
 }
References CONVERT, CONVERT_TO_TENSOR3D_STRUCT, CONVERT_TO_TENSOR4D_STRUCT, arm_compute::test::validation::input, POOL_OP, Tensor3D::ptr, arm_compute::test::validation::select, tensor3D_offset(), tensor4D_offset(), and VLOAD.
pooling_layer_2_nhwc_indices_fp32()
__kernel void pooling_layer_2_nhwc_indices_fp32 (__global uchar * input_ptr, uint input_stride_x, uint input_step_x, uint input_stride_y, uint input_step_y, uint input_stride_z, uint input_step_z, uint input_stride_w, uint input_step_w, uint input_offset_first_element_in_bytes, __global uchar * output_ptr, uint output_stride_x, uint output_step_x, uint output_stride_y, uint output_step_y, uint output_stride_z, uint output_step_z, uint output_stride_w, uint output_step_w, uint output_offset_first_element_in_bytes, __global uchar * indices_ptr, uint indices_stride_x, uint indices_step_x, uint indices_stride_y, uint indices_step_y, uint indices_stride_z, uint indices_step_z, uint indices_stride_w, uint indices_step_w, uint indices_offset_first_element_in_bytes)
Performs a MAX pooling of pool size equal to 2, and record max value indices for NHWC.
Note
Datatype must be passed using -DDATA_TYPE e.g. -DDATA_TYPE=half. Supported data types are F32
Pool sizes must be passed using -DPOOL_SIZE_X and -DPOOL_SIZE_Y e.g. -DPOOL_SIZE_X=13;
Tensors width and height must be passed at compile time using -DMAX_WIDTH and -DMAX_HEIGHT
Pool strides must be passed at compile time using -DSTRIDE_X and -DSTRIDE_Y which are the steps of the window along the x and y directions
Tensor padding values must be passed at compile time using PAD_TENSOR_LEFT, PAD_TENSOR_RIGHT, PAD_TENSOR_TOP and PAD_TENSOR_BOTTOM
Parameters
[in] input_ptr Pointer to the source tensor. Supported data types: F32
[in] input_stride_x Stride of the source tensor in X dimension (in bytes)
[in] input_step_x input_stride_x * number of elements along X processed per workitem(in bytes)
[in] input_stride_y Stride of the source tensor in Y dimension (in bytes)
[in] input_step_y input_stride_y * number of elements along Y processed per workitem(in bytes)
[in] input_stride_z Stride of the source tensor in Z dimension (in bytes)
[in] input_step_z input_stride_z * number of elements along Z processed per workitem(in bytes)
[in] input_stride_w Stride of the source tensor in W dimension (in bytes)
[in] input_step_w input_stride_w * number of elements along W processed per workitem(in bytes)
[in] input_offset_first_element_in_bytes The offset of the first element in the source tensor
[out] output_ptr Pointer to the destination tensor. Supported data types: same as input_ptr
[in] output_stride_x Stride of the destination tensor in X dimension (in bytes)
[in] output_step_x output_stride_x * number of elements along X processed per workitem(in bytes)
[in] output_stride_y Stride of the destination tensor in Y dimension (in bytes)
[in] output_step_y output_stride_y * number of elements along Y processed per workitem(in bytes)
[in] output_stride_z Stride of the destination tensor in Z dimension (in bytes)
[in] output_step_z output_stride_z * number of elements along Z processed per workitem(in bytes)
[in] output_stride_w Stride of the destination tensor in W dimension (in bytes)
[in] output_step_w output_stride_w * number of elements along W processed per workitem(in bytes)
[in] output_offset_first_element_in_bytes The offset of the first element in the destination tensor
[in] indices_ptr Pointer to the indices tensor. Supported data types: U32
[in] indices_stride_x Stride of the indices tensor in X dimension (in bytes)
[in] indices_step_x indices_stride_x * number of elements along X processed per workitem(in bytes)
[in] indices_stride_y Stride of the indices tensor in Y dimension (in bytes)
[in] indices_step_y indices_stride_y * number of elements along Y processed per workitem(in bytes)
[in] indices_stride_z Stride of the indices tensor in Z dimension (in bytes)
[in] indices_step_z indices_stride_z * number of elements along Z processed per workitem(in bytes)
[in] indices_stride_w Stride of the indices tensor in W dimension (in bytes)
[in] indices_step_w indices_stride_w * number of elements along W processed per workitem(in bytes)
[in] indices_offset_first_element_in_bytes The offset of the first element in the indices tensor
Definition at line 874 of file pooling_layer.cl.
 {
     // Get pixels pointer
 #if defined(DST_DEPTH)
     Tensor4D input   = CONVERT_TO_TENSOR4D_STRUCT(input, DST_DEPTH);
     Tensor4D output  = CONVERT_TO_TENSOR4D_STRUCT(output, DST_DEPTH);
     Tensor4D indices = CONVERT_TO_TENSOR4D_STRUCT(indices, DST_DEPTH);
 #else  /* defined(DST_DEPTH) */
     Tensor3D input   = CONVERT_TO_TENSOR3D_STRUCT(input);
     Tensor3D output  = CONVERT_TO_TENSOR3D_STRUCT(output);
     Tensor3D indices = CONVERT_TO_TENSOR3D_STRUCT(indices);
 #endif /* defined(DST_DEPTH) */
 #if defined(DST_DEPTH)
     // Load data
     float8 data_top0    = VLOAD(8)(0, (__global float *)tensor4D_offset(&input, 0, 0, 0, 0));
     float8 data_top1    = VLOAD(8)(0, (__global float *)tensor4D_offset(&input, 0, 1, 0, 0));
     float8 data_bottom0 = VLOAD(8)(0, (__global float *)tensor4D_offset(&input, 0, 0, 1, 0));
     float8 data_bottom1 = VLOAD(8)(0, (__global float *)tensor4D_offset(&input, 0, 1, 1, 0));
 #else  /* defined(DST_DEPTH) */
     // Load data
     float8   data_top0    = VLOAD(8)(0, (__global float *)tensor3D_offset(&input, 0, 0, 0));
     float8   data_top1    = VLOAD(8)(0, (__global float *)tensor3D_offset(&input, 0, 1, 0));
     float8   data_bottom0 = VLOAD(8)(0, (__global float *)tensor3D_offset(&input, 0, 0, 1));
     float8   data_bottom1 = VLOAD(8)(0, (__global float *)tensor3D_offset(&input, 0, 1, 1));
 #endif /* defined(DST_DEPTH) */
     float8 data_top_max    = POOL_OP(data_top0, data_top1);
     float8 data_bottom_max = POOL_OP(data_bottom0, data_bottom1);
     float8 data_max        = POOL_OP(data_top_max, data_bottom_max);
     vstore8(data_max, 0, (__global float *)output.ptr);
 #if defined(PAD_TENSOR_LEFT) && defined(PAD_TENSOR_RIGHT) && defined(PAD_TENSOR_TOP) && defined(PAD_TENSOR_BOTTOM)
     uint offset_x0 = 0;
     uint offset_x1 = 0;
     uint offset_x2 = 0;
     uint offset_x3 = 0;
 #if defined(DST_DEPTH)
     offset_no_padding_nhwc_4D(&input, &offset_x0, &offset_x1, &offset_x2, &offset_x3);
 #else  /* defined(DST_DEPTH) */
     offset_no_padding_nhwc_3D(&input, &offset_x0, &offset_x1, &offset_x2, &offset_x3);
 #endif /* defined(DST_DEPTH) */
     uint8 voffset_x0 = { offset_x0, offset_x0 + 1, offset_x0 + 2, offset_x0 + 3, offset_x0 + 4, offset_x0 + 5, offset_x0 + 6, offset_x0 + 7 };
     uint8 voffset_x1 = { offset_x1, offset_x1 + 1, offset_x1 + 2, offset_x1 + 3, offset_x1 + 4, offset_x1 + 5, offset_x1 + 6, offset_x1 + 7 };
     uint8 voffset_x2 = { offset_x2, offset_x2 + 1, offset_x2 + 2, offset_x2 + 3, offset_x2 + 4, offset_x2 + 5, offset_x2 + 6, offset_x2 + 7 };
     uint8 voffset_x3 = { offset_x3, offset_x3 + 1, offset_x3 + 2, offset_x3 + 3, offset_x3 + 4, offset_x3 + 5, offset_x3 + 6, offset_x3 + 7 };
     uint8 index0 = select(voffset_x1, voffset_x0, isgreaterequal(data_top0, data_top1));
     uint8 index1 = select(voffset_x3, voffset_x2, isgreaterequal(data_bottom0, data_bottom1));
     uint8 index  = select(index1, index0, isgreaterequal(data_top_max, data_bottom_max));
     vstore8(index, 0, (__global uint *)indices.ptr);
 #endif /* defined(PAD_TENSOR_LEFT) && defined(PAD_TENSOR_RIGHT) && defined(PAD_TENSOR_TOP) && defined(PAD_TENSOR_BOTTOM */
 }
References CONVERT_TO_TENSOR3D_STRUCT, CONVERT_TO_TENSOR4D_STRUCT, arm_compute::test::validation::input, POOL_OP, Tensor3D::ptr, arm_compute::test::validation::select, tensor3D_offset(), tensor4D_offset(), and VLOAD.
pooling_layer_3()
__kernel void pooling_layer_3 (__global uchar * input_ptr, uint input_stride_x, uint input_step_x, uint input_stride_y, uint input_step_y, uint input_stride_z, uint input_step_z, uint input_offset_first_element_in_bytes, __global uchar * output_ptr, uint output_stride_x, uint output_step_x, uint output_stride_y, uint output_step_y, uint output_stride_z, uint output_step_z, uint output_offset_first_element_in_bytes)
Performs a pooling function of pool size equal to 3.
Note
Datatype must be passed using -DDATA_TYPE e.g. -DDATA_TYPE=float. Supported data types are F16/F32;
In case of average pooling the following information must be passed at compile time: -DPOOL_AVG or -DPOOL_L2 must be provided otherwise max pooling will be performed. -DMAX_WIDTH and -DMAX_HEIGHT which are the maximum accessible indeces in x and y dimensions (width + pad) -DSTRIDE_X and -DSTRIDE_Y which are the steps of the window along the x and y directions -DPAD_X and -DPAD_Y which are the pooling paddings in x and y dimension
Parameters
[in] input_ptr Pointer to the source tensor. Supported data types: F16/F32
[in] input_stride_x Stride of the source tensor in X dimension (in bytes)
[in] input_step_x input_stride_x * number of elements along X processed per workitem(in bytes)
[in] input_stride_y Stride of the source tensor in Y dimension (in bytes)
[in] input_step_y input_stride_y * number of elements along Y processed per workitem(in bytes)
[in] input_stride_z Stride of the source tensor in Z dimension (in bytes)
[in] input_step_z input_stride_z * number of elements along Z processed per workitem(in bytes)
[in] input_offset_first_element_in_bytes The offset of the first element in the source tensor
[out] output_ptr Pointer to the destination tensor. Supported data types: same as input_ptr
[in] output_stride_x Stride of the destination tensor in X dimension (in bytes)
[in] output_step_x output_stride_x * number of elements along X processed per workitem(in bytes)
[in] output_stride_y Stride of the destination tensor in Y dimension (in bytes)
[in] output_step_y output_stride_y * number of elements along Y processed per workitem(in bytes)
[in] output_stride_z Stride of the source tensor in Z dimension (in bytes)
[in] output_step_z output_stride_z * number of elements along Z processed per workitem(in bytes)
[in] output_offset_first_element_in_bytes The offset of the first element in the destination tensor
Definition at line 276 of file pooling_layer.cl.
 {
     // Get pixels pointer
     Tensor3D input  = CONVERT_TO_TENSOR3D_STRUCT(input);
     Tensor3D output = CONVERT_TO_TENSOR3D_STRUCT(output);
     // Load data
     VEC_DATA_TYPE(ACC_DATA_TYPE, 3)
     data0 = VLOAD_AND_CONVERT_TO_ACC_DATA_TYPE(3, 0, (__global DATA_TYPE *)tensor3D_offset(&input, 0, 0, 0));
     VEC_DATA_TYPE(ACC_DATA_TYPE, 3)
     data1 = VLOAD_AND_CONVERT_TO_ACC_DATA_TYPE(3, 0, (__global DATA_TYPE *)tensor3D_offset(&input, 0, 1, 0));
     VEC_DATA_TYPE(ACC_DATA_TYPE, 3)
     data2 = VLOAD_AND_CONVERT_TO_ACC_DATA_TYPE(3, 0, (__global DATA_TYPE *)tensor3D_offset(&input, 0, 2, 0));
 #if defined(POOL_L2)
     // Raise to power of 2 for L2 Pooling
     data0 = POW2_OP(data0, 3);
     data1 = POW2_OP(data1, 3);
     data2 = POW2_OP(data2, 3);
 #endif /* defined(POOL_L2) */
     // Perform calculations
     data0             = POOL_OP(data0, data1);
     data0             = POOL_OP(data0, data2);
     ACC_DATA_TYPE res = POOL_OP(POOL_OP(data0.s0, data0.s1), data0.s2);
 #if defined(POOL_AVG) || defined(POOL_L2)
     // Divide by pool region in case of average pooling
     res = DIV_OP(res, calculate_avg_scale(3, 3, MAX_WIDTH, MAX_HEIGHT, PAD_X, PAD_Y, STRIDE_X, STRIDE_Y));
 #endif /* defined(POOL_AVG) || defined(POOL_L2) */
 #if defined(POOL_L2)
     // Take square root of the result in L2 pooling
     res = SQRT_OP(res);
 #endif /* defined(POOL_L2) */
     // Store result
     *(__global DATA_TYPE *)output.ptr = (DATA_TYPE)res;
 }
References calculate_avg_scale(), CONVERT_TO_TENSOR3D_STRUCT, DATA_TYPE, DIV_OP, arm_compute::test::validation::input, POOL_OP, POW2_OP, Tensor3D::ptr, SQRT_OP, tensor3D_offset(), VEC_DATA_TYPE, and VLOAD_AND_CONVERT_TO_ACC_DATA_TYPE.
pooling_layer_MxN_nhwc()
__kernel void pooling_layer_MxN_nhwc (__global uchar * input_ptr, uint input_stride_x, uint input_step_x, uint input_stride_y, uint input_step_y, uint input_stride_z, uint input_step_z, uint input_stride_w, uint input_step_w, uint input_offset_first_element_in_bytes, __global uchar * output_ptr, uint output_stride_x, uint output_step_x, uint output_stride_y, uint output_step_y, uint output_stride_z, uint output_step_z, uint output_stride_w, uint output_step_w, uint output_offset_first_element_in_bytes)
Performs a pooling function of pool size equal to N (NHWC)
Note
Datatype must be passed using -DDATA_TYPE e.g. -DDATA_TYPE=float. Supported data types are F16/F32
Pool sizes must be passed using -DPOOL_SIZE_X and -DPOOL_SIZE_Y e.g. -DPOOL_SIZE_X=13;
Tensors width and height must be passed at compile time using -DMAX_WIDTH and -DMAX_HEIGHT
Strides must be passed at compile time using -DSTRIDE_X and -DSTRIDE_Y which are the steps of the window along the x and y directions
Pad values must be passed at compile time using -DPAD_X and -DPAD_Y which are the pooling paddings in x and y dimension
In case of average pooling the following information must be passed at compile time: -DPOOL_AVG must be provided otherwise max pooling will be performed.
The initial value for the pooling operation must be passed at compile time using -DINITIAL_VALUE e.g. -DINITIAL_VALUE=0
Parameters
[in] input_ptr Pointer to the source tensor. Supported data types: F16/F32
[in] input_stride_x Stride of the source tensor in X dimension (in bytes)
[in] input_step_x input_stride_x * number of elements along X processed per workitem(in bytes)
[in] input_stride_y Stride of the source tensor in Y dimension (in bytes)
[in] input_step_y input_stride_y * number of elements along Y processed per workitem(in bytes)
[in] input_stride_z Stride of the source tensor in Z dimension (in bytes)
[in] input_step_z input_stride_z * number of elements along Z processed per workitem(in bytes)
[in] input_stride_w Stride of the source tensor in W dimension (in bytes)
[in] input_step_w input_stride_w * number of elements along W processed per workitem(in bytes)
[in] input_offset_first_element_in_bytes The offset of the first element in the source tensor
[out] output_ptr Pointer to the destination tensor. Supported data types: same as input_ptr
[in] output_stride_x Stride of the destination tensor in X dimension (in bytes)
[in] output_step_x output_stride_x * number of elements along X processed per workitem(in bytes)
[in] output_stride_y Stride of the destination tensor in Y dimension (in bytes)
[in] output_step_y output_stride_y * number of elements along Y processed per workitem(in bytes)
[in] output_stride_z Stride of the destination tensor in Z dimension (in bytes)
[in] output_step_z output_stride_z * number of elements along Z processed per workitem(in bytes)
[in] output_stride_w Stride of the destination tensor in W dimension (in bytes)
[in] output_step_w output_stride_w * number of elements along W processed per workitem(in bytes)
[in] output_offset_first_element_in_bytes The offset of the first element in the destination tensor
Definition at line 539 of file pooling_layer.cl.
 {
     // Get pixels pointer
 #if defined(DST_DEPTH)
     Tensor4D input  = CONVERT_TO_TENSOR4D_STRUCT(input, DST_DEPTH);
     Tensor4D output = CONVERT_TO_TENSOR4D_STRUCT(output, DST_DEPTH);
 #else  /* defined(DST_DEPTH) */
     Tensor3D  input      = CONVERT_TO_TENSOR3D_STRUCT(input);
     Tensor3D  output     = CONVERT_TO_TENSOR3D_STRUCT(output);
 #endif /* defined(DST_DEPTH) */
     VEC_DATA_TYPE(ACC_DATA_TYPE, 8)
     vdata = INITIAL_VALUE;
     const int idx_width = get_global_id(1) * STRIDE_X;
 #if defined(DST_DEPTH)
     const int idx_height = (get_global_id(2) % DST_DEPTH) * STRIDE_Y;
 #else  /* defined(DST_DEPTH) */
     const int idx_height = get_global_id(2) * STRIDE_Y;
 #endif /* defined(DST_DEPTH) */
     for(int y = 0; y < POOL_SIZE_Y; ++y)
     {
         int y1 = select(y, PAD_Y - idx_height, y + idx_height - PAD_Y < 0 || y + idx_height - PAD_Y >= MAX_HEIGHT);
         for(int x = 0; x < POOL_SIZE_X; ++x)
         {
             int x1 = select(x, PAD_X - idx_width - 1, x + idx_width - PAD_X < 0 || x + idx_width - PAD_X >= MAX_WIDTH);
             x1     = select(x1, PAD_X - idx_width - 1, y != y1);
 #if defined(DST_DEPTH)
             VEC_DATA_TYPE(ACC_DATA_TYPE, 8)
             data0 = VLOAD_AND_CONVERT_TO_ACC_DATA_TYPE(8, 0, (__global DATA_TYPE *)tensor4D_offset(&input, 0, x1 - PAD_X, y1 - PAD_Y, 0));
 #else  /* defined(DST_DEPTH) */
             VEC_DATA_TYPE(ACC_DATA_TYPE, 8)
             data0    = VLOAD_AND_CONVERT_TO_ACC_DATA_TYPE(8, 0, (__global DATA_TYPE *)tensor3D_offset(&input, 0, x1 - PAD_X, y1 - PAD_Y));
 #endif /* defined(DST_DEPTH) */
 #if defined(POOL_L2)
             // Raise to power of 2 for L2 Pooling
             data0 *= data0;
 #endif /* defined(POOL_L2) */
             vdata = POOL_OP(vdata, CONVERT(data0, VEC_DATA_TYPE(ACC_DATA_TYPE, 8)));
         }
     }
 #if defined(POOL_AVG) || defined(POOL_L2)
     // Divide by pool region in case of average pooling
     vdata = DIV_OP_NHWC(vdata, calculate_avg_scale_nhwc(POOL_SIZE_X, POOL_SIZE_Y, MAX_WIDTH, MAX_HEIGHT, PAD_X, PAD_Y, STRIDE_X, STRIDE_Y));
 #endif /* defined(POOL_AVG) || defined(POOL_L2) */
 #if defined(POOL_L2)
     // Take square root of the result in L2 pooling
     vdata = SQRT_OP(vdata);
 #endif /* defined(POOL_L2) */
     // Store result
     vstore8(CONVERT(vdata, VEC_DATA_TYPE(DATA_TYPE, 8)), 0, (__global DATA_TYPE *)output.ptr);
 }
References calculate_avg_scale_nhwc(), CONVERT, CONVERT_TO_TENSOR3D_STRUCT, CONVERT_TO_TENSOR4D_STRUCT, DATA_TYPE, DIV_OP_NHWC, arm_compute::test::validation::input, POOL_OP, Tensor3D::ptr, arm_compute::test::validation::select, SQRT_OP, tensor3D_offset(), tensor4D_offset(), VEC_DATA_TYPE, and VLOAD_AND_CONVERT_TO_ACC_DATA_TYPE.