Compute Library: TaskExecutor Class Reference
TaskExecutor Class Reference final
Task executor.
#include <Workload.h>
Static Public Member Functions
static TaskExecutor & get ()
Task executor accessor.
Data Fields
std::function< decltype(execute_task)> execute_function
Function that is responsible for executing tasks.
Detailed Description
Task executor.
Definition at line 50 of file Workload.h.
Member Function Documentation
static TaskExecutor& get () static
Task executor accessor.
Returns
Task executor instance
Referenced by OpenCLTimer::test_start(), SchedulerTimer::test_start(), OpenCLTimer::test_stop(), and SchedulerTimer::test_stop().
Field Documentation
std::function<decltype(execute_task)> execute_function
Function that is responsible for executing tasks.
Definition at line 63 of file Workload.h.
Referenced by OpenCLTimer::test_start(), SchedulerTimer::test_start(), OpenCLTimer::test_stop(), and SchedulerTimer::test_stop().
The documentation for this class was generated from the following file:
arm_compute/graph/Workload.h