Compute Library: NEWinogradLayerTransformInputKernel< T, OutputTileRows, OutputTileCols, KernelRows, KernelCols > Class Template Reference
NEWinogradLayerTransformInputKernel< T, OutputTileRows, OutputTileCols, KernelRows, KernelCols > Class Template Reference
NEON kernel to perform Winograd input transform.
#include <NEWinogradConvolutionLayerKernel.h>
Public Types
using WinogradBase = winograd::WinogradGEMM< OutputTileRows, OutputTileCols, KernelCols, KernelCols >
Winograd base kernel.
using WinogradConv = typename WinogradBase::template Convolution< T, T >
Winograd convolution kernel.
Public Member Functions
unsigned int get_input_storage_size (int n_batches, int n_channels, int n_rows, int n_cols, bool same_padding) const override
Determine how much memory (in units of TIn) to allocate for the transformed input.
int get_matrix_stride (const KernelShape &kernel_shape, const Tensor4DShape &input_shape, const PaddingType padding_type) const override
Gets the stride between matrices in the input worspace.
NEWinogradLayerTransformInputKernel ()
Default constructor.
const char * name () const override
Name of the kernel.
void configure (const T *const input, const int n_batches, const int n_rows, const int n_cols, const int n_channels, const PaddingType padding, T *const output, const int matrix_stride) override
Configure the output transform kernel.
void run (const Window &window, const ThreadInfo &info) override
Execute the kernel on the passed window.
Public Member Functions inherited from INEWinogradLayerTransformInputKernel< T >
virtual ~INEWinogradLayerTransformInputKernel ()
Destructor.
Public Member Functions inherited from ICPPKernel
virtual ~ICPPKernel ()=default
Default destructor.
Public Member Functions inherited from IKernel
IKernel ()
Constructor.
virtual ~IKernel ()=default
Destructor.
virtual bool is_parallelisable () const
Indicates whether or not the kernel is parallelisable.
virtual BorderSize border_size () const
The size of the border for that kernel.
const Window & window () const
The maximum window the kernel can be executed on.
Static Public Member Functions
static Status validate (const ITensorInfo *input, const ITensorInfo *output, const WinogradInfo &winograd_info)
Static function to check if given info will lead to a valid configuration of NEWinogradLayerTransformInputKernel.
Detailed Description
template<typename T, int OutputTileRows, int OutputTileCols, int KernelRows, int KernelCols>
class arm_compute::NEWinogradLayerTransformInputKernel< T, OutputTileRows, OutputTileCols, KernelRows, KernelCols >
NEON kernel to perform Winograd input transform.
Definition at line 86 of file NEWinogradConvolutionLayerKernel.h.
Member Typedef Documentation
using WinogradBase = winograd::WinogradGEMM<OutputTileRows, OutputTileCols, KernelCols, KernelCols>
Winograd base kernel.
Definition at line 150 of file NEWinogradConvolutionLayerKernel.h.
using WinogradConv = typename WinogradBase::template Convolution<T, T>
Winograd convolution kernel.
Definition at line 152 of file NEWinogradConvolutionLayerKernel.h.
Constructor & Destructor Documentation
NEWinogradLayerTransformInputKernel ()
Default constructor.
Member Function Documentation
void configure (const T *const input, const int n_batches, const int n_rows, const int n_cols, const int n_channels, const PaddingType padding, T *const output, const int matrix_stride) override virtual
Configure the output transform kernel.
Parameters
[in] input Input tensor data. Data types supported: F32.
[in] n_batches Number of batches in input tensor.
[in] n_rows Number of rows in input tensor.
[in] n_cols Number of columns in input tensor.
[in] n_channels Number of channels in input tensor.
[in] padding Padding type.
[out] output Base of output matrices.
[in] matrix_stride Stride between output matrices.
Implements INEWinogradLayerTransformInputKernel< T >.
unsigned int get_input_storage_size (int n_batches, int n_channels, int n_rows, int n_cols, bool same_padding) const override virtual
Determine how much memory (in units of TIn) to allocate for the transformed input.
Parameters
[in] n_batches Number of batches in the input tensor.
[in] n_channels Number of feature maps in the input tensor.
[in] n_rows Number of rows in each feature map.
[in] n_cols Number of columns in each feature map.
[in] same_padding Use "SAME" padding, otherwise use "VALID".
Returns
Storage size (in units of TIn) required.
Implements INEWinogradLayerTransformInputKernel< T >.
int get_matrix_stride (const KernelShape & kernel_shape, const Tensor4DShape & input_shape, const PaddingType padding_type) const override virtual
Gets the stride between matrices in the input worspace.
Parameters
[in] kernel_shape The shape of the weights tensor.
[in] input_shape The shape of the input tensor.
[in] padding_type The type of padding to be used.
Returns
Stride expressed in bytes.
Implements INEWinogradLayerTransformInputKernel< T >.
const char* name () const inline override virtual
Name of the kernel.
Returns
Kernel name
Implements ICPPKernel.
Definition at line 120 of file NEWinogradConvolutionLayerKernel.h.
References INEWinogradLayerTransformInputKernel< T >::configure(), arm_compute::test::validation::info(), ICPPKernel::run(), and IKernel::window().
     {
         return "NEWinogradLayerTransformInputKernel";
     }
void run (const Window & window, const ThreadInfo & info) override virtual
Execute the kernel on the passed window.
Warning
If is_parallelisable() returns false then the passed window must be equal to window()
Note
The window has to be a region within the window returned by the window() method
The width of the window has to be a multiple of num_elems_processed_per_iteration().
Parameters
[in] window Region on which to execute the kernel. (Must be a region of the window returned by window())
[in] info Info about executing thread and CPU.
Implements ICPPKernel.
static Status validate (const ITensorInfo * input, const ITensorInfo * output, const WinogradInfo & winograd_info) static
Static function to check if given info will lead to a valid configuration of NEWinogradLayerTransformInputKernel.
Parameters
[in] input First tensor input info. Data types supported: F32.
[in] output Output tensor info. Data types supported: same as input.
[in] winograd_info Contains Winograd's information described in WinogradInfo
Returns
a status
The documentation for this class was generated from the following file:
arm_compute/core/NEON/kernels/NEWinogradConvolutionLayerKernel.h