Compute Library: INEWinogradLayerTransformInputKernel< T > Class Template Reference
INEWinogradLayerTransformInputKernel< T > Class Template Reference abstract
Interface for the NEON kernel to perform Winograd input transform.
#include <NEWinogradConvolutionLayerKernel.h>
Public Member Functions
virtual unsigned int get_input_storage_size (int n_batches, int n_channels, int n_rows, int n_cols, bool same_padding) const =0
Determine how much memory (in units of TIn) to allocate for the transformed input.
virtual int get_matrix_stride (const KernelShape &kernel_shape, const Tensor4DShape &input_shape, const PaddingType padding_type) const =0
Gets the stride between matrices in the input worspace.
virtual void configure (const T *const input, const int n_batches, const int n_rows, const int n_cols, const int n_channels, const PaddingType padding, T *const output, const int matrix_stride)=0
Configure the output transform kernel.
virtual ~INEWinogradLayerTransformInputKernel ()
Destructor.
Public Member Functions inherited from ICPPKernel
virtual ~ICPPKernel ()=default
Default destructor.
virtual void run (const Window &window, const ThreadInfo &info)=0
Execute the kernel on the passed window.
virtual const char * name () const =0
Name of the kernel.
Public Member Functions inherited from IKernel
IKernel ()
Constructor.
virtual ~IKernel ()=default
Destructor.
virtual bool is_parallelisable () const
Indicates whether or not the kernel is parallelisable.
virtual BorderSize border_size () const
The size of the border for that kernel.
const Window & window () const
The maximum window the kernel can be executed on.
Detailed Description
template<typename T>
class arm_compute::INEWinogradLayerTransformInputKernel< T >
Interface for the NEON kernel to perform Winograd input transform.
Definition at line 39 of file NEWinogradConvolutionLayerKernel.h.
Constructor & Destructor Documentation
virtual ~INEWinogradLayerTransformInputKernel () inline virtual
Destructor.
Definition at line 79 of file NEWinogradConvolutionLayerKernel.h.
     {
     }
Member Function Documentation
virtual void configure (const T *const input, const int n_batches, const int n_rows, const int n_cols, const int n_channels, const PaddingType padding, T *const output, const int matrix_stride) pure virtual
Configure the output transform kernel.
Parameters
[in] input Input tensor data
[in] n_batches Number of batches in input tensor.
[in] n_rows Number of rows in input tensor.
[in] n_cols Number of columns in input tensor.
[in] n_channels Number of channels in input tensor.
[in] padding Padding type.
[out] output Base of output matrices.
[in] matrix_stride Stride between output matrices.
Implemented in NEWinogradLayerTransformInputKernel< T, OutputTileRows, OutputTileCols, KernelRows, KernelCols >.
Referenced by NEWinogradLayerTransformInputKernel< T, OutputTileRows, OutputTileCols, KernelRows, KernelCols >::name(), NEWinogradLayerTransformOutputKernel< T, OutputTileRows, OutputTileCols, KernelRows, KernelCols >::name(), NEWinogradLayerTransformWeightsKernel< T, OutputTileRows, OutputTileCols, KernelRows, KernelCols >::name(), and NEWinogradLayerBatchedGEMMKernel< TIn, TOut, OutputTileRows, OutputTileCols, KernelRows, KernelCols >::name().
virtual unsigned int get_input_storage_size (int n_batches, int n_channels, int n_rows, int n_cols, bool same_padding) const pure virtual
Determine how much memory (in units of TIn) to allocate for the transformed input.
Parameters
[in] n_batches Number of batches in the input tensor.
[in] n_channels Number of feature maps in the input tensor.
[in] n_rows Number of rows in each feature map.
[in] n_cols Number of columns in each feature map.
[in] same_padding Use "SAME" padding, otherwise use "VALID".
Returns
Storage size (in units of TIn) required.
Implemented in NEWinogradLayerTransformInputKernel< T, OutputTileRows, OutputTileCols, KernelRows, KernelCols >.
virtual int get_matrix_stride (const KernelShape & kernel_shape, const Tensor4DShape & input_shape, const PaddingType padding_type) const pure virtual
Gets the stride between matrices in the input worspace.
Parameters
[in] kernel_shape The shape of the weights tensor.
[in] input_shape The shape of the input tensor.
[in] padding_type The type of padding to be used.
Returns
Stride expressed in bytes.
Implemented in NEWinogradLayerTransformInputKernel< T, OutputTileRows, OutputTileCols, KernelRows, KernelCols >.
Referenced by NEWinogradLayerTransformOutputKernel< T, OutputTileRows, OutputTileCols, KernelRows, KernelCols >::name(), and NEWinogradLayerTransformWeightsKernel< T, OutputTileRows, OutputTileCols, KernelRows, KernelCols >::name().
The documentation for this class was generated from the following file:
arm_compute/core/NEON/kernels/NEWinogradConvolutionLayerKernel.h