Compute Library: ReshapeLayer Class Reference
ReshapeLayer Class Reference final
Reshape Layer.
#include <Layers.h>
Public Member Functions
ReshapeLayer (TensorShape shape)
Construct a reshape layer.
NodeID create_layer (IStream &s) override
Create layer and add to the given stream.
Public Member Functions inherited from ILayer
virtual ~ILayer ()=default
Default destructor.
ILayer & set_name (std::string name)
Sets the name of the layer.
const std::string & name () const
Layer name accessor.
Detailed Description
Reshape Layer.
Definition at line 360 of file Layers.h.
Constructor & Destructor Documentation
ReshapeLayer (TensorShape shape) inline
Construct a reshape layer.
Parameters
[in] shape Target shape.
Definition at line 367 of file Layers.h.
         : _shape(shape)
     {
     }
Member Function Documentation
NodeID create_layer (IStream & s) inline override virtual
Create layer and add to the given stream.
Parameters
[in] s Stream to add layer to.
Returns
ID of the created node.
Implements ILayer.
Definition at line 372 of file Layers.h.
References GraphBuilder::add_reshape_node(), IStream::graph(), IStream::hints(), ILayer::name(), IStream::tail_node(), and StreamHints::target_hint.
     {
         NodeParams  common_params = { name(), s.hints().target_hint };
         NodeIdxPair input         = { s.tail_node(), 0 };
         return GraphBuilder::add_reshape_node(s.graph(), common_params, input, _shape);
     }
The documentation for this class was generated from the following file:
arm_compute/graph/frontend/Layers.h