Compute Library: arm_compute::test::convolution_3d::detail Namespace Reference
arm_compute::test::convolution_3d::detail Namespace Reference
Functions
bool is_valid_pixel (int i, int min, int max)
template<typename T , typename TB , typename std::enable_if< validation::is_floating_point< T >::value &&validation::is_floating_point< TB >::value, int >::type = 0>
void convolution3d (const SimpleTensor< T > &in, const SimpleTensor< T > &weights, const SimpleTensor< TB > &bias, SimpleTensor< T > &out, int i_offset, int w_offset, int b_offset, int o_offset, int xi, int yi, int width_in, int height_in, int depth_in, int width_weights, int height_weights, int dilation_x=1, int dilation_y=1)
template<>
void convolution3d (const SimpleTensor< uint8_t > &in, const SimpleTensor< uint8_t > &weights, const SimpleTensor< int32_t > &bias, SimpleTensor< uint8_t > &out, int i_offset, int w_offset, int b_offset, int o_offset, int xi, int yi, int width_in, int height_in, int depth_in, int width_weights, int height_weights, int dilation_x, int dilation_y)
Function Documentation
void convolution3d (const SimpleTensor< T > & in, const SimpleTensor< T > & weights, const SimpleTensor< TB > & bias, SimpleTensor< T > & out, int i_offset, int w_offset, int b_offset, int o_offset, int xi, int yi, int width_in, int height_in, int depth_in, int width_weights, int height_weights, int dilation_x = 1, int dilation_y = 1) inline
Definition at line 47 of file Convolution3d.h.
References arm_compute::test::validation::b, SimpleTensor< T >::data(), SimpleTensor< T >::fixed_point_position(), and is_valid_pixel().
Referenced by arm_compute::test::validation::reference::convolution_layer_nchw(), and arm_compute::test::validation::reference::locally_connected().
 {
     const T *in_ptr  = in.data() + i_offset;
     const T *w_ptr   = weights.data() + w_offset;
     const TB *b_ptr   = bias.data() + b_offset;
     T        *out_ptr = out.data() + o_offset;
     const int half_width_weights_start  = width_weights / 2;
     const int half_width_weights_end    = ((width_weights % 2) == 0) ? (half_width_weights_start - 1) : half_width_weights_start;
     const int half_height_weights_start = height_weights / 2;
     const int half_height_weights_end   = ((height_weights % 2) == 0) ? (half_height_weights_start - 1) : half_height_weights_start;
     // Reset accumulator
     T acc(0);
     // Compute a 2D convolution for each IFM and accumulate the result
     for(int ifm = 0; ifm < depth_in; ++ifm)
     {
         // Compute the offset for the input slice
         const int offset_slice_in = xi + yi * width_in + ifm * width_in * height_in;
         // Compute 2D convolution
         for(int yk = -half_height_weights_start; yk <= half_height_weights_end; ++yk)
         {
             for(int xk = -half_width_weights_start; xk <= half_width_weights_end; ++xk)
             {
                 // Check if the pixel is out-of-bound
                 if(is_valid_pixel(xi + xk * dilation_x, 0, width_in) && is_valid_pixel(yi + yk * dilation_y, 0, height_in))
                 {
                     const int idx = xk + half_width_weights_start;
                     const int idy = yk + half_height_weights_start;
                     const T i_value = in_ptr[offset_slice_in + xk * dilation_x + yk * dilation_y * width_in];
                     const T w_value = w_ptr[idx + idy * width_weights + ifm * width_weights * height_weights];
                     acc += i_value * w_value;
                 }
             }
         }
     }
     // Accumulate the bias and store the result
     *out_ptr = acc + (*b_ptr);
 }
void arm_compute::test::convolution_3d::detail::convolution3d (const SimpleTensor< uint8_t > & in, const SimpleTensor< uint8_t > & weights, const SimpleTensor< int32_t > & bias, SimpleTensor< uint8_t > & out, int i_offset, int w_offset, int b_offset, int o_offset, int xi, int yi, int width_in, int height_in, int depth_in, int width_weights, int height_weights, int dilation_x, int dilation_y) inline
Definition at line 154 of file Convolution3d.h.
References arm_compute::test::validation::asymm_int_mult(), arm_compute::test::validation::asymm_rounding_divide_by_pow2(), arm_compute::quantization::calculate_quantized_multiplier_less_than_one(), SimpleTensor< T >::data(), is_valid_pixel(), QuantizationInfo::offset, SimpleTensor< T >::quantization_info(), and QuantizationInfo::scale.
 {
     const uint8_t *in_ptr  = in.data() + i_offset;
     const uint8_t *w_ptr   = weights.data() + w_offset;
     const int32_t *b_ptr   = bias.data() + b_offset;
     uint8_t       *out_ptr = out.data() + o_offset;
     const int   input_offset   = -in.quantization_info().offset;
     const float input_scale    = in.quantization_info().scale;
     const int   weights_offset = -weights.quantization_info().offset;
     const float weights_scale  = weights.quantization_info().scale;
     const int   output_offset  = out.quantization_info().offset;
     const float output_scale   = out.quantization_info().scale;
     int         output_multiplier = 0;
     int         output_shift      = 0;
     const float multiplier        = input_scale * weights_scale / output_scale;
     arm_compute::quantization::calculate_quantized_multiplier_less_than_one(multiplier, &output_multiplier, &output_shift);
     const int half_width_weights_start  = width_weights / 2;
     const int half_width_weights_end    = ((width_weights % 2) == 0) ? (half_width_weights_start - 1) : half_width_weights_start;
     const int half_height_weights_start = height_weights / 2;
     const int half_height_weights_end   = ((height_weights % 2) == 0) ? (half_height_weights_start - 1) : half_height_weights_start;
     // Reset accumulator
     int32_t acc(0);
     // Compute a 2D convolution for each IFM and accumulate the result
     for(int ifm = 0; ifm < depth_in; ++ifm)
     {
         // Compute the offset for the input slice
         const int offset_slice_in = xi + yi * width_in + ifm * width_in * height_in;
         // Compute 2D convolution
         for(int yk = -half_height_weights_start; yk <= half_height_weights_end; ++yk)
         {
             for(int xk = -half_width_weights_start; xk <= half_width_weights_end; ++xk)
             {
                 // Check if the pixel is out-of-bound
                 if(is_valid_pixel(xi + xk * dilation_x, 0, width_in) && is_valid_pixel(yi + yk * dilation_y, 0, height_in))
                 {
                     const int idx = xk + half_width_weights_start;
                     const int idy = yk + half_height_weights_start;
                     const uint8_t i_value = in_ptr[offset_slice_in + xk * dilation_x + yk * dilation_y * width_in];
                     const uint8_t w_value = w_ptr[idx + idy * width_weights + ifm * width_weights * height_weights];
                     acc += (i_value + input_offset) * (w_value + weights_offset);
                 }
             }
         }
     }
     // Accumulate the bias
     acc += (*b_ptr);
     acc = validation::asymm_rounding_divide_by_pow2(validation::asymm_int_mult(acc, output_multiplier), output_shift);
     acc += output_offset;
     acc = utility::clamp<int32_t>(acc, 0, 255);
     // Store the result
     *out_ptr = acc;
 }
bool arm_compute::test::convolution_3d::detail::is_valid_pixel (int i, int min, int max) inline
Definition at line 40 of file Convolution3d.h.
Referenced by convolution3d().
 {
     return (i >= min && i < max);
 }