Compute Library: caffe_data_extractor Namespace Reference
caffe_data_extractor Namespace Reference
Variables
tuple parser = argparse.ArgumentParser('Extract Caffe net parameters')
tuple args = parser.parse_args()
tuple net = caffe.Net(args.netFile, 1, weights=args.modelFile)
string outname = name+"_w"
varname = outname
Variable Documentation
tuple args = parser.parse_args()
Definition at line 21 of file caffe_data_extractor.py.
Referenced by CommandLineParser.add_option(), CommandLineParser.add_positional_option(), arm_compute.create_configure_kernel(), arm_compute.for_each(), arm_compute::support::cpp14.make_unique(), arm_compute::support::cpp11.stof(), arm_compute::support::cpp11.stoi(), and arm_compute::support::cpp11.stoul().
tuple net = caffe.Net(args.netFile, 1, weights=args.modelFile)
Definition at line 24 of file caffe_data_extractor.py.
string outname = name+"_w"
Definition at line 32 of file caffe_data_extractor.py.
tuple parser = argparse.ArgumentParser('Extract Caffe net parameters')
Definition at line 18 of file caffe_data_extractor.py.
Referenced by main().
tuple varname = outname
Definition at line 39 of file caffe_data_extractor.py.