Compute Library: Logger Class Reference
Logger Class Reference
Logger singleton class.
#include <Logger.h>
Public Member Functions
void set_logger (std::ostream &ostream, LoggerVerbosity verbosity)
std::ostream & log_info ()
Static Public Member Functions
static Logger & get ()
Detailed Description
Logger singleton class.
Definition at line 47 of file Logger.h.
Member Function Documentation
static Logger& get () static
Referenced by main_graph_alexnet(), and main_graph_lenet().
std::ostream& log_info ()
void set_logger (std::ostream & ostream, LoggerVerbosity verbosity)
Referenced by main_graph_alexnet(), and main_graph_lenet().
The documentation for this class was generated from the following file:
arm_compute/core/Logger.h