Compute Library: arm_compute::test::validation Namespace Reference
arm_compute::test::validation Namespace Reference
Namespaces
reference
Data Structures
class ActivationValidationFixedPointFixture
class ActivationValidationFixture
class ArithmeticAdditionValidationFixedPointFixture
class ArithmeticAdditionValidationFixture
class ArithmeticSubtractionValidationFixedPointFixture
class ArithmeticSubtractionValidationFixture
class BatchNormalizationLayerValidationFixedPointFixture
class BatchNormalizationLayerValidationFixture
class BitwiseAndValidationFixture
class BitwiseNotValidationFixture
class BitwiseOrValidationFixture
class BitwiseXorValidationFixture
class Box3x3ValidationFixture
class ConvolutionValidationFixedPointFixture
class ConvolutionValidationFixture
class DepthConcatenateValidationFixture
class DepthConvertValidationFixedPointFixture
class DepthConvertValidationFixture
class DepthConvertValidationFractionalBitsFixture
class DepthwiseConvolutionValidationFixture
class DepthwiseSeparableConvolutionValidationFixture
class DequantizationValidationFixedPointFixture
class DequantizationValidationFixture
class DirectConvolutionValidationFixedPointFixture
class DirectConvolutionValidationFixture
class FixedPointValidationFixture
class FlattenLayerValidationFixture
class FloorValidationFixture
class FullyConnectedLayerValidationFixedPointFixture
class FullyConnectedLayerValidationFixture
class Gaussian3x3ValidationFixture
class Gaussian5x5ValidationFixture
class GEMMValidationFixedPointFixture
class GEMMValidationFixture
class GEMMLowpOffsetValidationFixture
class HarrisCornersValidationFixture
class IntegralImageValidationFixture
class L2NormalizeValidationFixture
class MeanStdDevValidationFixture
class MinMaxLocationValidationFixture
class NonLinearFilterValidationFixture
class NormalizationValidationFixedPointFixture
class NormalizationValidationFixture
class PoolingLayerValidationFixedPointFixture
class PoolingLayerValidationFixture
class GlobalPoolingLayerValidationFixture
class QuantizationValidationFixedPointFixture
class QuantizationValidationFixture
class ReductionOperationValidationFixture
class ReshapeLayerValidationFixture
class ScaleValidationFixture
class SobelValidationFixture
class SoftmaxValidationFixedPointFixture
class SoftmaxValidationFixture
class TableLookupValidationFixture
class ThresholdValidationFixture
class WarpAffineValidationFixture
class WarpPerspectiveValidationFixture
struct is_floating_point
struct is_floating_point< half >
struct HarrisCornersParameters
Parameters of Harris Corners algorithm.
class AbsoluteTolerance
Class reprensenting an absolute tolerance value.
class RelativeTolerance
Class reprensenting a relative tolerance value.
struct compare_base
struct compare
struct compare< AbsoluteTolerance< U > >
struct compare< RelativeTolerance< U > >
Typedefs
template<typename T >
using CLActivationLayerFixture = ActivationValidationFixture< CLTensor, CLAccessor, CLActivationLayer, T >
template<typename T >
using CLActivationLayerFixedPointFixture = ActivationValidationFixedPointFixture< CLTensor, CLAccessor, CLActivationLayer, T >
template<typename T >
using CLArithmeticAdditionFixture = ArithmeticAdditionValidationFixture< CLTensor, CLAccessor, CLArithmeticAddition, T >
template<typename T >
using CLArithmeticAdditionFixedPointFixture = ArithmeticAdditionValidationFixedPointFixture< CLTensor, CLAccessor, CLArithmeticAddition, T >
template<typename T >
using CLArithmeticSubtractionFixture = ArithmeticSubtractionValidationFixture< CLTensor, CLAccessor, CLArithmeticSubtraction, T >
template<typename T >
using CLArithmeticSubtractionFixedPointFixture = ArithmeticSubtractionValidationFixedPointFixture< CLTensor, CLAccessor, CLArithmeticSubtraction, T >
template<typename T >
using CLBatchNormalizationLayerFixture = BatchNormalizationLayerValidationFixture< CLTensor, CLAccessor, CLBatchNormalizationLayer, T >
template<typename T >
using CLBatchNormalizationLayerFixedPointFixture = BatchNormalizationLayerValidationFixedPointFixture< CLTensor, CLAccessor, CLBatchNormalizationLayer, T >
template<typename T >
using CLBitwiseAndFixture = BitwiseAndValidationFixture< CLTensor, CLAccessor, CLBitwiseAnd, T >
template<typename T >
using CLBitwiseNotFixture = BitwiseNotValidationFixture< CLTensor, CLAccessor, CLBitwiseNot, T >
template<typename T >
using CLBitwiseOrFixture = BitwiseOrValidationFixture< CLTensor, CLAccessor, CLBitwiseOr, T >
template<typename T >
using CLBitwiseXorFixture = BitwiseXorValidationFixture< CLTensor, CLAccessor, CLBitwiseXor, T >
template<typename T >
using CLBox3x3Fixture = Box3x3ValidationFixture< CLTensor, CLAccessor, CLBox3x3, T >
template<typename T >
using CLConvolutionLayerFixture = ConvolutionValidationFixture< CLTensor, CLAccessor, CLConvolutionLayer, T >
template<typename T >
using CLConvolutionLayerFixedPointFixture = ConvolutionValidationFixedPointFixture< CLTensor, CLAccessor, CLConvolutionLayer, T >
template<typename T >
using CLDepthConcatenateLayerFixture = DepthConcatenateValidationFixture< CLTensor, ICLTensor, CLAccessor, CLDepthConcatenate, T >
template<typename T >
using CLDepthConvertToU16Fixture = DepthConvertValidationFixture< CLTensor, CLAccessor, CLDepthConvert, T, uint16_t >
template<typename T >
using CLDepthConvertToS16Fixture = DepthConvertValidationFixture< CLTensor, CLAccessor, CLDepthConvert, T, int16_t >
template<typename T >
using CLDepthConvertToS32Fixture = DepthConvertValidationFixture< CLTensor, CLAccessor, CLDepthConvert, T, int32_t >
template<typename T >
using CLDepthConvertToU8Fixture = DepthConvertValidationFixture< CLTensor, CLAccessor, CLDepthConvert, T, uint8_t >
template<typename T >
using CLDepthConvertToU32Fixture = DepthConvertValidationFixture< CLTensor, CLAccessor, CLDepthConvert, T, uint32_t >
template<typename T >
using CLDepthConvertToFP32FixedPointFixture = DepthConvertValidationFractionalBitsFixture< CLTensor, CLAccessor, CLDepthConvert, T, float >
template<typename T >
using CLDepthConvertToQS8FixedPointFixture = DepthConvertValidationFractionalBitsFixture< CLTensor, CLAccessor, CLDepthConvert, T, int8_t >
template<typename T >
using CLDepthConvertToQS16FixedPointFixture = DepthConvertValidationFractionalBitsFixture< CLTensor, CLAccessor, CLDepthConvert, T, int16_t >
template<typename T >
using CLDepthwiseConvolutionFixture = DepthwiseConvolutionValidationFixture< CLTensor, CLAccessor, CLDepthwiseConvolution, T >
template<typename T >
using CLDepthwiseConvolutionFixture3x3 = DepthwiseConvolutionValidationFixture< CLTensor, CLAccessor, CLDepthwiseConvolution3x3, T >
template<typename T >
using CLDepthwiseSeparableConvolutionLayerFixture = DepthwiseSeparableConvolutionValidationFixture< CLTensor, CLAccessor, CLDepthwiseSeparableConvolutionLayer, T >
template<typename T >
using CLDequantizationLayerFixture = DequantizationValidationFixture< CLTensor, CLAccessor, CLDequantizationLayer, T >
template<typename T >
using CLDirectConvolutionLayerFixture = DirectConvolutionValidationFixture< CLTensor, CLAccessor, CLDirectConvolutionLayer, T >
template<typename T >
using CLDirectConvolutionLayerFixedPointFixture = DirectConvolutionValidationFixedPointFixture< CLTensor, CLAccessor, CLDirectConvolutionLayer, T >
template<typename T >
using CLFixedPointFixture = FixedPointValidationFixture< CLTensor, CLAccessor, T >
template<typename T >
using CLFlattenLayerFixture = FlattenLayerValidationFixture< CLTensor, CLAccessor, CLFlattenLayer, T >
template<typename T >
using CLFloorFixture = FloorValidationFixture< CLTensor, CLAccessor, CLFloor, T >
template<typename T >
using CLFullyConnectedLayerFixture = FullyConnectedLayerValidationFixture< CLTensor, CLAccessor, CLFullyConnectedLayer, T, false >
template<typename T >
using CLFullyConnectedLayerFixedPointFixture = FullyConnectedLayerValidationFixedPointFixture< CLTensor, CLAccessor, CLFullyConnectedLayer, T, false >
template<typename T >
using CLGaussian3x3Fixture = Gaussian3x3ValidationFixture< CLTensor, CLAccessor, CLGaussian3x3, T >
template<typename T >
using CLGaussian5x5Fixture = Gaussian5x5ValidationFixture< CLTensor, CLAccessor, CLGaussian5x5, T >
template<typename T >
using CLGEMMFixture = GEMMValidationFixture< CLTensor, CLAccessor, CLGEMM, T >
template<typename T >
using CLGEMMFixedPointFixture = GEMMValidationFixedPointFixture< CLTensor, CLAccessor, CLGEMM, T >
template<typename T >
using CLGlobalPoolingLayerFixture = GlobalPoolingLayerValidationFixture< CLTensor, CLAccessor, CLPoolingLayer, T >
template<typename T >
using CLHarrisCornersFixture = HarrisCornersValidationFixture< CLTensor, CLAccessor, CLKeyPointArray, CLHarrisCorners, T >
template<typename T >
using CLIntegralImageFixture = IntegralImageValidationFixture< CLTensor, CLAccessor, CLIntegralImage, T >
template<typename T >
using CLL2NormalizeFixture = L2NormalizeValidationFixture< CLTensor, CLAccessor, CLL2Normalize, T >
template<typename T >
using CLMeanStdDevFixture = MeanStdDevValidationFixture< CLTensor, CLAccessor, CLMeanStdDev, T >
template<typename T >
using CLMinMaxLocationFixture = MinMaxLocationValidationFixture< CLTensor, CLAccessor, CLArray< Coordinates2D >, CLArrayAccessor< Coordinates2D >, CLMinMaxLocation, T >
template<typename T >
using CLNonLinearFilterFixture = NonLinearFilterValidationFixture< CLTensor, CLAccessor, CLNonLinearFilter, T >
template<typename T >
using CLNormalizationLayerFixture = NormalizationValidationFixture< CLTensor, CLAccessor, CLNormalizationLayer, T >
template<typename T >
using CLNormalizationLayerFixedPointFixture = NormalizationValidationFixedPointFixture< CLTensor, CLAccessor, CLNormalizationLayer, T >
template<typename T >
using CLPoolingLayerFixture = PoolingLayerValidationFixture< CLTensor, CLAccessor, CLPoolingLayer, T >
template<typename T >
using CLPoolingLayerFixedPointFixture = PoolingLayerValidationFixedPointFixture< CLTensor, CLAccessor, CLPoolingLayer, T >
template<typename T >
using CLQuantizationLayerFixture = QuantizationValidationFixture< CLTensor, CLAccessor, CLQuantizationLayer, T >
template<typename T >
using CLReductionOperationFixture = ReductionOperationValidationFixture< CLTensor, CLAccessor, CLReductionOperation, T >
template<typename T >
using CLReshapeLayerFixture = ReshapeLayerValidationFixture< CLTensor, CLAccessor, CLReshapeLayer, T >
template<typename T >
using CLScaleFixture = ScaleValidationFixture< CLTensor, CLAccessor, CLScale, T >
using CLSobel3x3Fixture = SobelValidationFixture< CLTensor, CLAccessor, CLSobel3x3, uint8_t, int16_t >
using CLSobel5x5Fixture = SobelValidationFixture< CLTensor, CLAccessor, CLSobel5x5, uint8_t, int16_t >
using CLSobel7x7Fixture = SobelValidationFixture< CLTensor, CLAccessor, CLSobel7x7, uint8_t, int32_t >
template<typename T >
using CLSoftmaxLayerFixture = SoftmaxValidationFixture< CLTensor, CLAccessor, CLSoftmaxLayer, T >
template<typename T >
using CLSoftmaxLayerFixedPointFixture = SoftmaxValidationFixedPointFixture< CLTensor, CLAccessor, CLSoftmaxLayer, T >
template<typename T >
using CLTableLookupFixture = TableLookupValidationFixture< CLTensor, CLAccessor, CLTableLookup, CLLutAccessor< T >, CLLut, T >
template<typename T >
using CLThresholdFixture = ThresholdValidationFixture< CLTensor, CLAccessor, CLThreshold, T >
template<typename T >
using CLWarpAffineFixture = WarpAffineValidationFixture< CLTensor, CLAccessor, CLWarpAffine, T >
template<typename T >
using CLWarpPerspectiveFixture = WarpPerspectiveValidationFixture< CLTensor, CLAccessor, CLWarpPerspective, T >
template<typename T >
using NEActivationLayerFixture = ActivationValidationFixture< Tensor, Accessor, NEActivationLayer, T >
template<typename T >
using NEActivationLayerFixedPointFixture = ActivationValidationFixedPointFixture< Tensor, Accessor, NEActivationLayer, T >
template<typename T >
using NEArithmeticAdditionFixture = ArithmeticAdditionValidationFixture< Tensor, Accessor, NEArithmeticAddition, T >
template<typename T >
using NEArithmeticAdditionFixedPointFixture = ArithmeticAdditionValidationFixedPointFixture< Tensor, Accessor, NEArithmeticAddition, T >
template<typename T >
using NEArithmeticSubtractionFixture = ArithmeticSubtractionValidationFixture< Tensor, Accessor, NEArithmeticSubtraction, T >
template<typename T >
using NEArithmeticSubtractionFixedPointFixture = ArithmeticSubtractionValidationFixedPointFixture< Tensor, Accessor, NEArithmeticSubtraction, T >
template<typename T >
using NEBatchNormalizationLayerFixture = BatchNormalizationLayerValidationFixture< Tensor, Accessor, NEBatchNormalizationLayer, T >
template<typename T >
using NEBatchNormalizationLayerFixedPointFixture = BatchNormalizationLayerValidationFixedPointFixture< Tensor, Accessor, NEBatchNormalizationLayer, T >
template<typename T >
using NEBitwiseAndFixture = BitwiseAndValidationFixture< Tensor, Accessor, NEBitwiseAnd, T >
template<typename T >
using NEBitwiseNotFixture = BitwiseNotValidationFixture< Tensor, Accessor, NEBitwiseNot, T >
template<typename T >
using NEBitwiseOrFixture = BitwiseOrValidationFixture< Tensor, Accessor, NEBitwiseOr, T >
template<typename T >
using NEBitwiseXorFixture = BitwiseXorValidationFixture< Tensor, Accessor, NEBitwiseXor, T >
template<typename T >
using NEBox3x3Fixture = Box3x3ValidationFixture< Tensor, Accessor, NEBox3x3, T >
template<typename T >
using NEConvolutionLayerFixture = ConvolutionValidationFixture< Tensor, Accessor, NEConvolutionLayer, T >
template<typename T >
using NEConvolutionLayerFixedPointFixture = ConvolutionValidationFixedPointFixture< Tensor, Accessor, NEConvolutionLayer, T >
template<typename T >
using NEDepthConcatenateLayerFixture = DepthConcatenateValidationFixture< Tensor, ITensor, Accessor, NEDepthConcatenate, T >
template<typename T >
using NEDepthConvertToU16Fixture = DepthConvertValidationFixture< Tensor, Accessor, NEDepthConvert, T, uint16_t >
template<typename T >
using NEDepthConvertToS16Fixture = DepthConvertValidationFixture< Tensor, Accessor, NEDepthConvert, T, int16_t >
template<typename T >
using NEDepthConvertToS32Fixture = DepthConvertValidationFixture< Tensor, Accessor, NEDepthConvert, T, int32_t >
template<typename T >
using NEDepthConvertToU8Fixture = DepthConvertValidationFixture< Tensor, Accessor, NEDepthConvert, T, uint8_t >
template<typename T >
using NEDepthConvertToU32Fixture = DepthConvertValidationFixture< Tensor, Accessor, NEDepthConvert, T, uint32_t >
template<typename T >
using NEDepthConvertToFP32FixedPointFixture = DepthConvertValidationFractionalBitsFixture< Tensor, Accessor, NEDepthConvert, T, float >
template<typename T >
using NEDepthConvertToQS8FixedPointFixture = DepthConvertValidationFractionalBitsFixture< Tensor, Accessor, NEDepthConvert, T, int8_t >
template<typename T >
using NEDepthConvertToQS16FixedPointFixture = DepthConvertValidationFractionalBitsFixture< Tensor, Accessor, NEDepthConvert, T, int16_t >
template<typename T >
using NEDequantizationLayerFixture = DequantizationValidationFixture< Tensor, Accessor, NEDequantizationLayer, T >
template<typename T >
using NEDirectConvolutionLayerFixture = DirectConvolutionValidationFixture< Tensor, Accessor, NEDirectConvolutionLayer, T >
template<typename T >
using NEDirectConvolutionLayerFixedPointFixture = DirectConvolutionValidationFixedPointFixture< Tensor, Accessor, NEDirectConvolutionLayer, T >
template<typename T >
using NEFixedPointFixture = FixedPointValidationFixture< Tensor, Accessor, T >
template<typename T >
using NEFlattenLayerFixture = FlattenLayerValidationFixture< Tensor, Accessor, NEFlattenLayer, T >
template<typename T >
using NEFloorFixture = FloorValidationFixture< Tensor, Accessor, NEFloor, T >
template<typename T >
using NEFullyConnectedLayerFixture = FullyConnectedLayerValidationFixture< Tensor, Accessor, NEFullyConnectedLayer, T, true >
template<typename T >
using NEFullyConnectedLayerFixedPointFixture = FullyConnectedLayerValidationFixedPointFixture< Tensor, Accessor, NEFullyConnectedLayer, T, true >
template<typename T >
using NEGaussian3x3Fixture = Gaussian3x3ValidationFixture< Tensor, Accessor, NEGaussian3x3, T >
template<typename T >
using NEGaussian5x5Fixture = Gaussian5x5ValidationFixture< Tensor, Accessor, NEGaussian5x5, T >
template<typename T >
using NEGEMMFixture = GEMMValidationFixture< Tensor, Accessor, NEGEMM, T >
template<typename T >
using NEGEMMFixedPointFixture = GEMMValidationFixedPointFixture< Tensor, Accessor, NEGEMM, T >
using NEGEMMLowpOffsetFixture = GEMMLowpOffsetValidationFixture< Tensor, Accessor, NEGEMMLowp >
template<typename T >
using NEGlobalPoolingLayerFixture = GlobalPoolingLayerValidationFixture< Tensor, Accessor, NEPoolingLayer, T >
template<typename T >
using NEHarrisCornersFixture = HarrisCornersValidationFixture< Tensor, Accessor, KeyPointArray, NEHarrisCorners, T >
template<typename T >
using NEIntegralImageFixture = IntegralImageValidationFixture< Tensor, Accessor, NEIntegralImage, T >
template<typename T >
using NEL2NormalizeFixture = L2NormalizeValidationFixture< Tensor, Accessor, NEL2Normalize, T >
template<typename T >
using NEMeanStdDevFixture = MeanStdDevValidationFixture< Tensor, Accessor, NEMeanStdDev, T >
template<typename T >
using NEMinMaxLocationFixture = MinMaxLocationValidationFixture< Tensor, Accessor, Array< Coordinates2D >, ArrayAccessor< Coordinates2D >, NEMinMaxLocation, T >
template<typename T >
using NENonLinearFilterFixture = NonLinearFilterValidationFixture< Tensor, Accessor, NENonLinearFilter, T >
template<typename T >
using NENormalizationLayerFixture = NormalizationValidationFixture< Tensor, Accessor, NENormalizationLayer, T >
template<typename T >
using NENormalizationLayerFixedPointFixture = NormalizationValidationFixedPointFixture< Tensor, Accessor, NENormalizationLayer, T >
template<typename T >
using NEPoolingLayerFixture = PoolingLayerValidationFixture< Tensor, Accessor, NEPoolingLayer, T >
template<typename T >
using NEPoolingLayerFixedPointFixture = PoolingLayerValidationFixedPointFixture< Tensor, Accessor, NEPoolingLayer, T >
template<typename T >
using NEQuantizationLayerFixture = QuantizationValidationFixture< Tensor, Accessor, NEQuantizationLayer, T >
template<typename T >
using NEReductionOperationFixture = ReductionOperationValidationFixture< Tensor, Accessor, NEReductionOperation, T >
template<typename T >
using NEReshapeLayerFixture = ReshapeLayerValidationFixture< Tensor, Accessor, NEReshapeLayer, T >
template<typename T >
using NEScaleFixture = ScaleValidationFixture< Tensor, Accessor, NEScale, T >
using NESobel3x3Fixture = SobelValidationFixture< Tensor, Accessor, NESobel3x3, uint8_t, int16_t >
using NESobel5x5Fixture = SobelValidationFixture< Tensor, Accessor, NESobel5x5, uint8_t, int16_t >
using NESobel7x7Fixture = SobelValidationFixture< Tensor, Accessor, NESobel7x7, uint8_t, int32_t >
template<typename T >
using NESoftmaxLayerFixture = SoftmaxValidationFixture< Tensor, Accessor, NESoftmaxLayer, T >
template<typename T >
using NESoftmaxLayerFixedPointFixture = SoftmaxValidationFixedPointFixture< Tensor, Accessor, NESoftmaxLayer, T >
template<typename T >
using NETableLookupFixture = TableLookupValidationFixture< Tensor, Accessor, NETableLookup, LutAccessor< T >, Lut, T >
template<typename T >
using ThresholdFixture = ThresholdValidationFixture< Tensor, Accessor, NEThreshold, T >
template<typename T >
using NEWarpAffineFixture = WarpAffineValidationFixture< Tensor, Accessor, NEWarpAffine, T >
template<typename T >
using NEWarpPerspectiveFixture = WarpPerspectiveValidationFixture< Tensor, Accessor, NEWarpPerspective, T >
Functions
DATA_TEST_CASE (Configuration, framework::DatasetMode::ALL, combine(combine(concat(datasets::SmallShapes(), datasets::LargeShapes()), CNNDataTypes), framework::dataset::make("InPlace",{false, true})), shape, data_type, in_place)
FIXTURE_DATA_TEST_CASE (RunSmall, CLActivationLayerFixture< half >, framework::DatasetMode::PRECOMMIT, combine(combine(datasets::SmallShapes(), ActivationDataset), framework::dataset::make("DataType", DataType::F16)))
FIXTURE_DATA_TEST_CASE (RunLarge, CLActivationLayerFixture< half >, framework::DatasetMode::NIGHTLY, combine(combine(datasets::LargeShapes(), ActivationDataset), framework::dataset::make("DataType", DataType::F16)))
FIXTURE_DATA_TEST_CASE (RunSmall, CLActivationLayerFixture< float >, framework::DatasetMode::PRECOMMIT, combine(combine(datasets::SmallShapes(), ActivationDataset), framework::dataset::make("DataType", DataType::F32)))
FIXTURE_DATA_TEST_CASE (RunLarge, CLActivationLayerFixture< float >, framework::DatasetMode::NIGHTLY, combine(combine(datasets::LargeShapes(), ActivationDataset), framework::dataset::make("DataType", DataType::F32)))
FIXTURE_DATA_TEST_CASE (RunSmall, CLActivationLayerFixedPointFixture< int8_t >, framework::DatasetMode::PRECOMMIT, combine(combine(combine(datasets::SmallShapes(), ActivationDataset), framework::dataset::make("DataType", DataType::QS8)), framework::dataset::make("FractionalBits", 3, 6)))
FIXTURE_DATA_TEST_CASE (RunLarge, CLActivationLayerFixedPointFixture< int8_t >, framework::DatasetMode::NIGHTLY, combine(combine(combine(datasets::LargeShapes(), ActivationDataset), framework::dataset::make("DataType", DataType::QS8)), framework::dataset::make("FractionalBits", 3, 6)))
FIXTURE_DATA_TEST_CASE (RunSmall, CLActivationLayerFixedPointFixture< int16_t >, framework::DatasetMode::PRECOMMIT, combine(combine(combine(datasets::SmallShapes(), ActivationDataset), framework::dataset::make("DataType", DataType::QS16)), framework::dataset::make("FractionalBits", 1, 14)))
FIXTURE_DATA_TEST_CASE (RunLarge, CLActivationLayerFixedPointFixture< int16_t >, framework::DatasetMode::NIGHTLY, combine(combine(combine(datasets::LargeShapes(), ActivationDataset), framework::dataset::make("DataType", DataType::QS16)), framework::dataset::make("FractionalBits", 1, 14)))
DATA_TEST_CASE (Configuration, framework::DatasetMode::ALL, combine(framework::dataset::concat(datasets::SmallShapes(), datasets::LargeShapes()), framework::dataset::make("ConvertPolicy",{ConvertPolicy::SATURATE, ConvertPolicy::WRAP})), shape, policy)
FIXTURE_DATA_TEST_CASE (RunSmall, CLArithmeticAdditionFixture< uint8_t >, framework::DatasetMode::PRECOMMIT, combine(combine(datasets::SmallShapes(), ArithmeticAdditionU8Dataset), framework::dataset::make("ConvertPolicy",{ConvertPolicy::SATURATE, ConvertPolicy::WRAP})))
DATA_TEST_CASE (Configuration, framework::DatasetMode::ALL, combine(combine(framework::dataset::concat(datasets::SmallShapes(), datasets::LargeShapes()), framework::dataset::make("DataType",{DataType::U8, DataType::S16})), framework::dataset::make("ConvertPolicy",{ConvertPolicy::SATURATE, ConvertPolicy::WRAP})), shape, data_type, policy)
FIXTURE_DATA_TEST_CASE (RunSmall, CLArithmeticAdditionFixture< int16_t >, framework::DatasetMode::PRECOMMIT, combine(combine(datasets::SmallShapes(), ArithmeticAdditionS16Dataset), framework::dataset::make("ConvertPolicy",{ConvertPolicy::SATURATE, ConvertPolicy::WRAP})))
FIXTURE_DATA_TEST_CASE (RunLarge, CLArithmeticAdditionFixture< int16_t >, framework::DatasetMode::NIGHTLY, combine(combine(datasets::LargeShapes(), ArithmeticAdditionS16Dataset), framework::dataset::make("ConvertPolicy",{ConvertPolicy::SATURATE, ConvertPolicy::WRAP})))
FIXTURE_DATA_TEST_CASE (RunSmall, CLArithmeticAdditionFixedPointFixture< int8_t >, framework::DatasetMode::PRECOMMIT, combine(combine(combine(datasets::SmallShapes(), ArithmeticAdditionQS8Dataset), framework::dataset::make("ConvertPolicy",{ConvertPolicy::SATURATE, ConvertPolicy::WRAP})), framework::dataset::make("FractionalBits", 1, 7)))
FIXTURE_DATA_TEST_CASE (RunLarge, CLArithmeticAdditionFixedPointFixture< int8_t >, framework::DatasetMode::NIGHTLY, combine(combine(combine(datasets::LargeShapes(), ArithmeticAdditionQS8Dataset), framework::dataset::make("ConvertPolicy",{ConvertPolicy::SATURATE, ConvertPolicy::WRAP})), framework::dataset::make("FractionalBits", 1, 7)))
FIXTURE_DATA_TEST_CASE (RunSmall, CLArithmeticAdditionFixedPointFixture< int16_t >, framework::DatasetMode::PRECOMMIT, combine(combine(combine(datasets::SmallShapes(), ArithmeticAdditionQS16Dataset), framework::dataset::make("ConvertPolicy",{ConvertPolicy::SATURATE, ConvertPolicy::WRAP})), framework::dataset::make("FractionalBits", 1, 15)))
FIXTURE_DATA_TEST_CASE (RunLarge, CLArithmeticAdditionFixedPointFixture< int16_t >, framework::DatasetMode::NIGHTLY, combine(combine(combine(datasets::LargeShapes(), ArithmeticAdditionQS16Dataset), framework::dataset::make("ConvertPolicy",{ConvertPolicy::SATURATE, ConvertPolicy::WRAP})), framework::dataset::make("FractionalBits", 1, 15)))
FIXTURE_DATA_TEST_CASE (RunSmall, CLArithmeticAdditionFixture< half >, framework::DatasetMode::ALL, combine(combine(datasets::SmallShapes(), ArithmeticAdditionFP16Dataset), framework::dataset::make("ConvertPolicy",{ConvertPolicy::SATURATE, ConvertPolicy::WRAP})))
FIXTURE_DATA_TEST_CASE (RunSmall, CLArithmeticAdditionFixture< float >, framework::DatasetMode::PRECOMMIT, combine(combine(datasets::SmallShapes(), ArithmeticAdditionFP32Dataset), framework::dataset::make("ConvertPolicy",{ConvertPolicy::SATURATE, ConvertPolicy::WRAP})))
FIXTURE_DATA_TEST_CASE (RunLarge, CLArithmeticAdditionFixture< float >, framework::DatasetMode::NIGHTLY, combine(combine(datasets::LargeShapes(), ArithmeticAdditionFP32Dataset), framework::dataset::make("ConvertPolicy",{ConvertPolicy::SATURATE, ConvertPolicy::WRAP})))
FIXTURE_DATA_TEST_CASE (RunSmall, CLArithmeticSubtractionFixture< uint8_t >, framework::DatasetMode::PRECOMMIT, combine(combine(datasets::SmallShapes(), ArithmeticSubtractionU8Dataset), framework::dataset::make("ConvertPolicy",{ConvertPolicy::SATURATE, ConvertPolicy::WRAP})))
FIXTURE_DATA_TEST_CASE (RunSmall, CLArithmeticSubtractionFixture< int16_t >, framework::DatasetMode::PRECOMMIT, combine(combine(datasets::SmallShapes(), ArithmeticSubtractionS16Dataset), framework::dataset::make("ConvertPolicy",{ConvertPolicy::SATURATE, ConvertPolicy::WRAP})))
FIXTURE_DATA_TEST_CASE (RunLarge, CLArithmeticSubtractionFixture< int16_t >, framework::DatasetMode::NIGHTLY, combine(combine(datasets::LargeShapes(), ArithmeticSubtractionS16Dataset), framework::dataset::make("ConvertPolicy",{ConvertPolicy::SATURATE, ConvertPolicy::WRAP})))
FIXTURE_DATA_TEST_CASE (RunSmall, CLArithmeticSubtractionFixedPointFixture< int8_t >, framework::DatasetMode::PRECOMMIT, combine(combine(combine(datasets::SmallShapes(), ArithmeticSubtractionQS8Dataset), framework::dataset::make("ConvertPolicy",{ConvertPolicy::SATURATE, ConvertPolicy::WRAP})), framework::dataset::make("FractionalBits", 1, 7)))
FIXTURE_DATA_TEST_CASE (RunLarge, CLArithmeticSubtractionFixedPointFixture< int8_t >, framework::DatasetMode::NIGHTLY, combine(combine(combine(datasets::LargeShapes(), ArithmeticSubtractionQS8Dataset), framework::dataset::make("ConvertPolicy",{ConvertPolicy::SATURATE, ConvertPolicy::WRAP})), framework::dataset::make("FractionalBits", 1, 7)))
FIXTURE_DATA_TEST_CASE (RunSmall, CLArithmeticSubtractionFixedPointFixture< int16_t >, framework::DatasetMode::PRECOMMIT, combine(combine(combine(datasets::SmallShapes(), ArithmeticSubtractionQS16Dataset), framework::dataset::make("ConvertPolicy",{ConvertPolicy::SATURATE, ConvertPolicy::WRAP})), framework::dataset::make("FractionalBits", 1, 15)))
FIXTURE_DATA_TEST_CASE (RunLarge, CLArithmeticSubtractionFixedPointFixture< int16_t >, framework::DatasetMode::NIGHTLY, combine(combine(combine(datasets::LargeShapes(), ArithmeticSubtractionQS16Dataset), framework::dataset::make("ConvertPolicy",{ConvertPolicy::SATURATE, ConvertPolicy::WRAP})), framework::dataset::make("FractionalBits", 1, 15)))
FIXTURE_DATA_TEST_CASE (RunSmall, CLArithmeticSubtractionFixture< half >, framework::DatasetMode::ALL, combine(combine(datasets::SmallShapes(), ArithmeticSubtractionFP16Dataset), framework::dataset::make("ConvertPolicy",{ConvertPolicy::SATURATE, ConvertPolicy::WRAP})))
FIXTURE_DATA_TEST_CASE (RunSmall, CLArithmeticSubtractionFixture< float >, framework::DatasetMode::PRECOMMIT, combine(combine(datasets::SmallShapes(), ArithmeticSubtractionFP32Dataset), framework::dataset::make("ConvertPolicy",{ConvertPolicy::SATURATE, ConvertPolicy::WRAP})))
FIXTURE_DATA_TEST_CASE (RunLarge, CLArithmeticSubtractionFixture< float >, framework::DatasetMode::NIGHTLY, combine(combine(datasets::LargeShapes(), ArithmeticSubtractionFP32Dataset), framework::dataset::make("ConvertPolicy",{ConvertPolicy::SATURATE, ConvertPolicy::WRAP})))
DATA_TEST_CASE (Configuration, framework::DatasetMode::ALL, combine(datasets::RandomBatchNormalizationLayerDataset(), framework::dataset::make("DataType",{DataType::QS8, DataType::QS16, DataType::F16, DataType::F32})), shape0, shape1, epsilon, dt)
FIXTURE_DATA_TEST_CASE (Random, CLBatchNormalizationLayerFixture< float >, framework::DatasetMode::PRECOMMIT, combine(datasets::RandomBatchNormalizationLayerDataset(), framework::dataset::make("DataType", DataType::F32)))
FIXTURE_DATA_TEST_CASE (Random, CLBatchNormalizationLayerFixture< half >, framework::DatasetMode::PRECOMMIT, combine(datasets::RandomBatchNormalizationLayerDataset(), framework::dataset::make("DataType", DataType::F16)))
FIXTURE_DATA_TEST_CASE (Random, CLBatchNormalizationLayerFixedPointFixture< int8_t >, framework::DatasetMode::PRECOMMIT, combine(combine(datasets::RandomBatchNormalizationLayerDataset(), framework::dataset::make("DataType", DataType::QS8)), framework::dataset::make("FractionalBits", 1, 6)))
FIXTURE_DATA_TEST_CASE (Random, CLBatchNormalizationLayerFixedPointFixture< int16_t >, framework::DatasetMode::PRECOMMIT, combine(combine(datasets::RandomBatchNormalizationLayerDataset(), framework::dataset::make("DataType", DataType::QS16)), framework::dataset::make("FractionalBits", 1, 14)))
DATA_TEST_CASE (Configuration, framework::DatasetMode::ALL, combine(concat(datasets::SmallShapes(), datasets::LargeShapes()), framework::dataset::make("DataType", DataType::U8)), shape, data_type)
FIXTURE_DATA_TEST_CASE (RunSmall, CLBitwiseAndFixture< uint8_t >, framework::DatasetMode::PRECOMMIT, combine(datasets::SmallShapes(), framework::dataset::make("DataType", DataType::U8)))
FIXTURE_DATA_TEST_CASE (RunLarge, CLBitwiseAndFixture< uint8_t >, framework::DatasetMode::NIGHTLY, combine(datasets::LargeShapes(), framework::dataset::make("DataType", DataType::U8)))
FIXTURE_DATA_TEST_CASE (RunSmall, CLBitwiseNotFixture< uint8_t >, framework::DatasetMode::PRECOMMIT, combine(datasets::SmallShapes(), framework::dataset::make("DataType", DataType::U8)))
FIXTURE_DATA_TEST_CASE (RunLarge, CLBitwiseNotFixture< uint8_t >, framework::DatasetMode::NIGHTLY, combine(datasets::LargeShapes(), framework::dataset::make("DataType", DataType::U8)))
FIXTURE_DATA_TEST_CASE (RunSmall, CLBitwiseOrFixture< uint8_t >, framework::DatasetMode::PRECOMMIT, combine(datasets::SmallShapes(), framework::dataset::make("DataType", DataType::U8)))
FIXTURE_DATA_TEST_CASE (RunLarge, CLBitwiseOrFixture< uint8_t >, framework::DatasetMode::NIGHTLY, combine(datasets::LargeShapes(), framework::dataset::make("DataType", DataType::U8)))
FIXTURE_DATA_TEST_CASE (RunSmall, CLBitwiseXorFixture< uint8_t >, framework::DatasetMode::PRECOMMIT, combine(datasets::SmallShapes(), framework::dataset::make("DataType", DataType::U8)))
FIXTURE_DATA_TEST_CASE (RunLarge, CLBitwiseXorFixture< uint8_t >, framework::DatasetMode::NIGHTLY, combine(datasets::LargeShapes(), framework::dataset::make("DataType", DataType::U8)))
DATA_TEST_CASE (Configuration, framework::DatasetMode::ALL, combine(combine(concat(datasets::SmallShapes(), datasets::LargeShapes()), framework::dataset::make("DataType", DataType::U8)), datasets::BorderModes()), shape, data_type, border_mode)
FIXTURE_DATA_TEST_CASE (RunSmall, CLBox3x3Fixture< uint8_t >, framework::DatasetMode::PRECOMMIT, combine(combine(datasets::SmallShapes(), framework::dataset::make("DataType", DataType::U8)), datasets::BorderModes()))
FIXTURE_DATA_TEST_CASE (RunLarge, CLBox3x3Fixture< uint8_t >, framework::DatasetMode::NIGHTLY, combine(combine(datasets::LargeShapes(), framework::dataset::make("DataType", DataType::U8)), datasets::BorderModes()))
DATA_TEST_CASE (Configuration, framework::DatasetMode::ALL, combine(framework::dataset::concat(datasets::SmallConvolutionLayerDataset(), datasets::LargeConvolutionLayerDataset()), CNNDataTypes), input_shape, weights_shape, bias_shape, output_shape, info, data_type)
FIXTURE_DATA_TEST_CASE (RunSmall, CLConvolutionLayerFixture< half >, framework::DatasetMode::PRECOMMIT, combine(combine(datasets::SmallConvolutionLayerDataset(), framework::dataset::make("ReshapeWeights",{true, false})), framework::dataset::make("DataType", DataType::F16)))
FIXTURE_DATA_TEST_CASE (RunLarge, CLConvolutionLayerFixture< half >, framework::DatasetMode::NIGHTLY, combine(combine(datasets::LargeConvolutionLayerDataset(), framework::dataset::make("ReshapeWeights",{true, false})), framework::dataset::make("DataType", DataType::F16)))
FIXTURE_DATA_TEST_CASE (RunSmall, CLConvolutionLayerFixture< float >, framework::DatasetMode::PRECOMMIT, combine(combine(datasets::SmallConvolutionLayerDataset(), framework::dataset::make("ReshapeWeights",{true, false})), framework::dataset::make("DataType", DataType::F32)))
FIXTURE_DATA_TEST_CASE (RunLarge, CLConvolutionLayerFixture< float >, framework::DatasetMode::NIGHTLY, combine(combine(datasets::LargeConvolutionLayerDataset(), framework::dataset::make("ReshapeWeights",{true, false})), framework::dataset::make("DataType", DataType::F32)))
FIXTURE_DATA_TEST_CASE (RunSmall, CLConvolutionLayerFixedPointFixture< int8_t >, framework::DatasetMode::PRECOMMIT, combine(combine(combine(datasets::SmallConvolutionLayerDataset(), framework::dataset::make("ReshapeWeights",{true, false})), framework::dataset::make("DataType", DataType::QS8)), framework::dataset::make("FractionalBits", 4, 7)))
FIXTURE_DATA_TEST_CASE (RunLarge, CLConvolutionLayerFixedPointFixture< int8_t >, framework::DatasetMode::NIGHTLY, combine(combine(combine(datasets::LargeConvolutionLayerDataset(), framework::dataset::make("ReshapeWeights",{true, false})), framework::dataset::make("DataType", DataType::QS8)), framework::dataset::make("FractionalBits", 4, 7)))
FIXTURE_DATA_TEST_CASE (RunSmall, CLConvolutionLayerFixedPointFixture< int16_t >, framework::DatasetMode::PRECOMMIT, combine(combine(combine(datasets::SmallConvolutionLayerDataset(), framework::dataset::make("ReshapeWeights",{true, false})), framework::dataset::make("DataType", DataType::QS16)), framework::dataset::make("FractionalBits", 1, 14)))
FIXTURE_DATA_TEST_CASE (RunLarge, CLConvolutionLayerFixedPointFixture< int16_t >, framework::DatasetMode::NIGHTLY, combine(combine(combine(datasets::LargeConvolutionLayerDataset(), framework::dataset::make("ReshapeWeights",{true, false})), framework::dataset::make("DataType", DataType::QS16)), framework::dataset::make("FractionalBits", 1, 14)))
FIXTURE_DATA_TEST_CASE (RunSmall, CLDepthConcatenateLayerFixture< half >, framework::DatasetMode::PRECOMMIT, combine(datasets::Small2DShapes(), framework::dataset::make("DataType", DataType::F16)))
FIXTURE_DATA_TEST_CASE (RunLarge, CLDepthConcatenateLayerFixture< half >, framework::DatasetMode::NIGHTLY, combine(datasets::Large2DShapes(), framework::dataset::make("DataType", DataType::F16)))
FIXTURE_DATA_TEST_CASE (RunSmall, CLDepthConcatenateLayerFixture< float >, framework::DatasetMode::PRECOMMIT, combine(datasets::Small2DShapes(), framework::dataset::make("DataType", DataType::F32)))
FIXTURE_DATA_TEST_CASE (RunLarge, CLDepthConcatenateLayerFixture< float >, framework::DatasetMode::NIGHTLY, combine(datasets::DepthConcatenateShapes(), framework::dataset::make("DataType", DataType::F32)))
FIXTURE_DATA_TEST_CASE (RunSmall, CLDepthConcatenateLayerFixture< int8_t >, framework::DatasetMode::PRECOMMIT, combine(datasets::Small2DShapes(), framework::dataset::make("DataType", DataType::QS8)))
FIXTURE_DATA_TEST_CASE (RunLarge, CLDepthConcatenateLayerFixture< int8_t >, framework::DatasetMode::NIGHTLY, combine(datasets::DepthConcatenateShapes(), framework::dataset::make("DataType", DataType::QS8)))
FIXTURE_DATA_TEST_CASE (RunSmall, CLDepthConcatenateLayerFixture< int16_t >, framework::DatasetMode::PRECOMMIT, combine(datasets::Small2DShapes(), framework::dataset::make("DataType", DataType::QS16)))
FIXTURE_DATA_TEST_CASE (RunLarge, CLDepthConcatenateLayerFixture< int16_t >, framework::DatasetMode::NIGHTLY, combine(datasets::DepthConcatenateShapes(), framework::dataset::make("DataType", DataType::QS16)))
DATA_TEST_CASE (Configuration, framework::DatasetMode::ALL, combine(combine(framework::dataset::concat(datasets::SmallShapes(), datasets::LargeShapes()), framework::dataset::make("ConvertPolicy",{ConvertPolicy::SATURATE, ConvertPolicy::WRAP})), DepthConvertShiftDataset), shape, policy, shift)
FIXTURE_DATA_TEST_CASE (RunSmall, CLDepthConvertToU16Fixture< uint8_t >, framework::DatasetMode::PRECOMMIT, combine(combine(combine(datasets::SmallShapes(), DepthConvertU8toU16Dataset), framework::dataset::make("ConvertPolicy",{ConvertPolicy::SATURATE, ConvertPolicy::WRAP})), DepthConvertShiftDataset))
FIXTURE_DATA_TEST_CASE (RunLarge, CLDepthConvertToU16Fixture< uint8_t >, framework::DatasetMode::NIGHTLY, combine(combine(combine(datasets::LargeShapes(), DepthConvertU8toU16Dataset), framework::dataset::make("ConvertPolicy",{ConvertPolicy::SATURATE, ConvertPolicy::WRAP})), DepthConvertShiftDataset))
FIXTURE_DATA_TEST_CASE (RunSmall, CLDepthConvertToS16Fixture< uint8_t >, framework::DatasetMode::PRECOMMIT, combine(combine(combine(datasets::SmallShapes(), DepthConvertU8toS16Dataset), framework::dataset::make("ConvertPolicy",{ConvertPolicy::SATURATE, ConvertPolicy::WRAP})), DepthConvertShiftDataset))
FIXTURE_DATA_TEST_CASE (RunLarge, CLDepthConvertToS16Fixture< uint8_t >, framework::DatasetMode::NIGHTLY, combine(combine(combine(datasets::LargeShapes(), DepthConvertU8toS16Dataset), framework::dataset::make("ConvertPolicy",{ConvertPolicy::SATURATE, ConvertPolicy::WRAP})), DepthConvertShiftDataset))
FIXTURE_DATA_TEST_CASE (RunSmall, CLDepthConvertToS32Fixture< uint8_t >, framework::DatasetMode::PRECOMMIT, combine(combine(combine(datasets::SmallShapes(), DepthConvertU8toS32Dataset), framework::dataset::make("ConvertPolicy",{ConvertPolicy::SATURATE, ConvertPolicy::WRAP})), DepthConvertShiftDataset))
FIXTURE_DATA_TEST_CASE (RunLarge, CLDepthConvertToS32Fixture< uint8_t >, framework::DatasetMode::NIGHTLY, combine(combine(combine(datasets::LargeShapes(), DepthConvertU8toS32Dataset), framework::dataset::make("ConvertPolicy",{ConvertPolicy::SATURATE, ConvertPolicy::WRAP})), DepthConvertShiftDataset))
FIXTURE_DATA_TEST_CASE (RunSmall, CLDepthConvertToU8Fixture< uint16_t >, framework::DatasetMode::PRECOMMIT, combine(combine(combine(datasets::SmallShapes(), DepthConvertU16toU8Dataset), framework::dataset::make("ConvertPolicy",{ConvertPolicy::SATURATE, ConvertPolicy::WRAP})), DepthConvertShiftDataset))
FIXTURE_DATA_TEST_CASE (RunLarge, CLDepthConvertToU8Fixture< uint16_t >, framework::DatasetMode::NIGHTLY, combine(combine(combine(datasets::LargeShapes(), DepthConvertU16toU8Dataset), framework::dataset::make("ConvertPolicy",{ConvertPolicy::SATURATE, ConvertPolicy::WRAP})), DepthConvertShiftDataset))
FIXTURE_DATA_TEST_CASE (RunSmall, CLDepthConvertToU32Fixture< uint16_t >, framework::DatasetMode::PRECOMMIT, combine(combine(combine(datasets::SmallShapes(), DepthConvertU16toU32Dataset), framework::dataset::make("ConvertPolicy",{ConvertPolicy::SATURATE, ConvertPolicy::WRAP})), DepthConvertShiftDataset))
FIXTURE_DATA_TEST_CASE (RunLarge, CLDepthConvertToU32Fixture< uint16_t >, framework::DatasetMode::NIGHTLY, combine(combine(combine(datasets::LargeShapes(), DepthConvertU16toU32Dataset), framework::dataset::make("ConvertPolicy",{ConvertPolicy::SATURATE, ConvertPolicy::WRAP})), DepthConvertShiftDataset))
FIXTURE_DATA_TEST_CASE (RunSmall, CLDepthConvertToU8Fixture< int16_t >, framework::DatasetMode::PRECOMMIT, combine(combine(combine(datasets::SmallShapes(), DepthConvertS16toU8Dataset), framework::dataset::make("ConvertPolicy",{ConvertPolicy::SATURATE, ConvertPolicy::WRAP})), DepthConvertShiftDataset))
FIXTURE_DATA_TEST_CASE (RunLarge, CLDepthConvertToU8Fixture< int16_t >, framework::DatasetMode::NIGHTLY, combine(combine(combine(datasets::LargeShapes(), DepthConvertS16toU8Dataset), framework::dataset::make("ConvertPolicy",{ConvertPolicy::SATURATE, ConvertPolicy::WRAP})), DepthConvertShiftDataset))
FIXTURE_DATA_TEST_CASE (RunSmall, CLDepthConvertToS32Fixture< int16_t >, framework::DatasetMode::PRECOMMIT, combine(combine(combine(datasets::SmallShapes(), DepthConvertS16toS32Dataset), framework::dataset::make("ConvertPolicy",{ConvertPolicy::SATURATE, ConvertPolicy::WRAP})), DepthConvertShiftDataset))
FIXTURE_DATA_TEST_CASE (RunLarge, CLDepthConvertToS32Fixture< int16_t >, framework::DatasetMode::NIGHTLY, combine(combine(combine(datasets::LargeShapes(), DepthConvertS16toS32Dataset), framework::dataset::make("ConvertPolicy",{ConvertPolicy::SATURATE, ConvertPolicy::WRAP})), DepthConvertShiftDataset))
DATA_TEST_CASE (Configuration, framework::DatasetMode::ALL, combine(combine(combine(framework::dataset::concat(datasets::SmallShapes(), datasets::LargeShapes()), framework::dataset::make("DataType",{DataType::QS8, DataType::QS16})), framework::dataset::make("ConvertPolicy",{ConvertPolicy::SATURATE, ConvertPolicy::WRAP})), DepthConvertFixedPointQuantizedDataset), shape, dt, policy, fixed_point_position)
FIXTURE_DATA_TEST_CASE (RunSmallQS8, CLDepthConvertToFP32FixedPointFixture< int8_t >, framework::DatasetMode::PRECOMMIT, combine(combine(combine(datasets::SmallShapes(), DepthConvertQS8toFP32Dataset), framework::dataset::make("ConvertPolicy",{ConvertPolicy::SATURATE, ConvertPolicy::WRAP})), DepthConvertFixedPointQuantizedDataset))
FIXTURE_DATA_TEST_CASE (RunSmallQS16, CLDepthConvertToFP32FixedPointFixture< int16_t >, framework::DatasetMode::PRECOMMIT, combine(combine(combine(datasets::SmallShapes(), DepthConvertQS16toFP32Dataset), framework::dataset::make("ConvertPolicy",{ConvertPolicy::SATURATE, ConvertPolicy::WRAP})), DepthConvertFixedPointQuantizedDataset))
FIXTURE_DATA_TEST_CASE (RunLargeQS8, CLDepthConvertToFP32FixedPointFixture< int8_t >, framework::DatasetMode::NIGHTLY, combine(combine(combine(datasets::LargeShapes(), DepthConvertQS8toFP32Dataset), framework::dataset::make("ConvertPolicy",{ConvertPolicy::SATURATE, ConvertPolicy::WRAP})), DepthConvertFixedPointQuantizedDataset))
FIXTURE_DATA_TEST_CASE (RunLargeQS16, CLDepthConvertToFP32FixedPointFixture< int16_t >, framework::DatasetMode::NIGHTLY, combine(combine(combine(datasets::LargeShapes(), DepthConvertQS16toFP32Dataset), framework::dataset::make("ConvertPolicy",{ConvertPolicy::SATURATE, ConvertPolicy::WRAP})), DepthConvertFixedPointQuantizedDataset))
FIXTURE_DATA_TEST_CASE (RunSmallQS8, CLDepthConvertToQS8FixedPointFixture< float >, framework::DatasetMode::PRECOMMIT, combine(combine(combine(datasets::SmallShapes(), DepthConvertFP32toQS8Dataset), framework::dataset::make("ConvertPolicy",{ConvertPolicy::SATURATE, ConvertPolicy::WRAP})), DepthConvertFixedPointQuantizedDataset))
FIXTURE_DATA_TEST_CASE (RunSmallQS16, CLDepthConvertToQS16FixedPointFixture< float >, framework::DatasetMode::PRECOMMIT, combine(combine(combine(datasets::SmallShapes(), DepthConvertFP32toQS16Dataset), framework::dataset::make("ConvertPolicy",{ConvertPolicy::SATURATE, ConvertPolicy::WRAP})), DepthConvertFixedPointQuantizedDataset))
FIXTURE_DATA_TEST_CASE (RunLargeQS8, CLDepthConvertToQS8FixedPointFixture< float >, framework::DatasetMode::NIGHTLY, combine(combine(combine(datasets::LargeShapes(), DepthConvertFP32toQS8Dataset), framework::dataset::make("ConvertPolicy",{ConvertPolicy::SATURATE, ConvertPolicy::WRAP})), DepthConvertFixedPointQuantizedDataset))
FIXTURE_DATA_TEST_CASE (RunLargeQS16, CLDepthConvertToQS16FixedPointFixture< float >, framework::DatasetMode::NIGHTLY, combine(combine(combine(datasets::LargeShapes(), DepthConvertFP32toQS16Dataset), framework::dataset::make("ConvertPolicy",{ConvertPolicy::SATURATE, ConvertPolicy::WRAP})), DepthConvertFixedPointQuantizedDataset))
DATA_TEST_CASE (Configuration, framework::DatasetMode::ALL, combine(DequantizationShapes, framework::dataset::make("DataType", DataType::U8)), shape, data_type)
FIXTURE_DATA_TEST_CASE (RunSmall, CLDequantizationLayerFixture< uint8_t >, framework::DatasetMode::PRECOMMIT, combine(concat(datasets::Small3DShapes(), datasets::Small4DShapes()), framework::dataset::make("DataType", DataType::U8)))
FIXTURE_DATA_TEST_CASE (RunLarge, CLDequantizationLayerFixture< uint8_t >, framework::DatasetMode::NIGHTLY, combine(concat(datasets::Large3DShapes(), datasets::Large4DShapes()), framework::dataset::make("DataType", DataType::U8)))
FIXTURE_DATA_TEST_CASE (Run, CLDirectConvolutionLayerFixture< half >, framework::DatasetMode::ALL, combine(data, framework::dataset::make("DataType", DataType::F16)))
FIXTURE_DATA_TEST_CASE (Run, CLDirectConvolutionLayerFixture< float >, framework::DatasetMode::ALL, combine(data, framework::dataset::make("DataType", DataType::F32)))
FIXTURE_DATA_TEST_CASE (Run, CLDirectConvolutionLayerFixedPointFixture< int8_t >, framework::DatasetMode::ALL, combine(combine(data_quantized, framework::dataset::make("DataType", DataType::QS8)), framework::dataset::make("FractionalBits", 2, 7)))
FIXTURE_DATA_TEST_CASE (Run, CLDirectConvolutionLayerFixedPointFixture< int16_t >, framework::DatasetMode::ALL, combine(combine(data_quantized, framework::dataset::make("DataType", DataType::QS16)), framework::dataset::make("FractionalBits", 2, 15)))
DATA_TEST_CASE (FillBorder, framework::DatasetMode::ALL, combine(combine(combine(combine(datasets::SmallShapes(), datasets::BorderModes()), BorderSizesDataset), PaddingSizesDataset), framework::dataset::make("DataType", DataType::U8)), shape, border_mode, size, padding, data_type)
FIXTURE_DATA_TEST_CASE (RunSmall, CLFixedPointFixture< int8_t >, framework::DatasetMode::ALL, combine(combine(combine(datasets::Small1DShape(), framework::dataset::make("DataType", DataType::QS8)), framework::dataset::make("FixedPointOp", FixedPointOp::EXP)), framework::dataset::make("FractionalBits", 1, 6)))
FIXTURE_DATA_TEST_CASE (RunSmall, CLFixedPointFixture< int8_t >, framework::DatasetMode::ALL, combine(combine(combine(datasets::Small1DShape(), framework::dataset::make("DataType", DataType::QS8)), framework::dataset::make("FixedPointOp", FixedPointOp::LOG)), framework::dataset::make("FractionalBits", 3, 6)))
FIXTURE_DATA_TEST_CASE (RunSmall, CLFixedPointFixture< int8_t >, framework::DatasetMode::ALL, combine(combine(combine(datasets::Small1DShape(), framework::dataset::make("DataType", DataType::QS8)), framework::dataset::make("FixedPointOp", FixedPointOp::INV_SQRT)), framework::dataset::make("FractionalBits", 1, 6)))
FIXTURE_DATA_TEST_CASE (RunSmall, CLFlattenLayerFixture< float >, framework::DatasetMode::ALL, combine(framework::dataset::concat(datasets::Small3DShapes(), datasets::Small4DShapes()), framework::dataset::make("DataType", DataType::F32)))
FIXTURE_DATA_TEST_CASE (RunLarge, CLFlattenLayerFixture< float >, framework::DatasetMode::NIGHTLY, combine(framework::dataset::concat(datasets::Large3DShapes(), datasets::Large4DShapes()), framework::dataset::make("DataType", DataType::F32)))
FIXTURE_DATA_TEST_CASE (RunSmall, CLFlattenLayerFixture< half >, framework::DatasetMode::ALL, combine(framework::dataset::concat(datasets::Small3DShapes(), datasets::Small4DShapes()), framework::dataset::make("DataType", DataType::F16)))
FIXTURE_DATA_TEST_CASE (RunLarge, CLFlattenLayerFixture< half >, framework::DatasetMode::NIGHTLY, combine(framework::dataset::concat(datasets::Large3DShapes(), datasets::Large4DShapes()), framework::dataset::make("DataType", DataType::F16)))
FIXTURE_DATA_TEST_CASE (RunSmall, CLFlattenLayerFixture< int8_t >, framework::DatasetMode::ALL, combine(framework::dataset::concat(datasets::Small3DShapes(), datasets::Small4DShapes()), framework::dataset::make("DataType", DataType::QS8)))
FIXTURE_DATA_TEST_CASE (RunLarge, CLFlattenLayerFixture< int8_t >, framework::DatasetMode::NIGHTLY, combine(framework::dataset::concat(datasets::Large3DShapes(), datasets::Large4DShapes()), framework::dataset::make("DataType", DataType::QS8)))
FIXTURE_DATA_TEST_CASE (RunSmall, CLFlattenLayerFixture< int16_t >, framework::DatasetMode::ALL, combine(framework::dataset::concat(datasets::Small3DShapes(), datasets::Small4DShapes()), framework::dataset::make("DataType", DataType::QS16)))
FIXTURE_DATA_TEST_CASE (RunLarge, CLFlattenLayerFixture< int16_t >, framework::DatasetMode::NIGHTLY, combine(framework::dataset::concat(datasets::Large3DShapes(), datasets::Large4DShapes()), framework::dataset::make("DataType", DataType::QS16)))
FIXTURE_DATA_TEST_CASE (RunSmall, CLFloorFixture< float >, framework::DatasetMode::PRECOMMIT, combine(datasets::SmallShapes(), framework::dataset::make("DataType", DataType::F32)))
FIXTURE_DATA_TEST_CASE (RunLarge, CLFloorFixture< float >, framework::DatasetMode::NIGHTLY, combine(datasets::LargeShapes(), framework::dataset::make("DataType", DataType::F32)))
DATA_TEST_CASE (Configuration, framework::DatasetMode::ALL, combine(combine(framework::dataset::concat(datasets::SmallFullyConnectedLayerDataset(), datasets::LargeFullyConnectedLayerDataset()), FullyConnectedParameters), CNNDataTypes), src_shape, weights_shape, bias_shape, dst_shape, transpose_weights, reshape_weights, data_type)
FIXTURE_DATA_TEST_CASE (RunSmall, CLFullyConnectedLayerFixture< half >, framework::DatasetMode::PRECOMMIT, combine(combine(datasets::SmallFullyConnectedLayerDataset(), FullyConnectedParameters), framework::dataset::make("DataType", DataType::F16)))
FIXTURE_DATA_TEST_CASE (RunLarge, CLFullyConnectedLayerFixture< half >, framework::DatasetMode::NIGHTLY, combine(combine(datasets::LargeFullyConnectedLayerDataset(), FullyConnectedParameters), framework::dataset::make("DataType", DataType::F16)))
FIXTURE_DATA_TEST_CASE (RunSmall, CLFullyConnectedLayerFixture< float >, framework::DatasetMode::PRECOMMIT, combine(combine(datasets::SmallFullyConnectedLayerDataset(), FullyConnectedParameters), framework::dataset::make("DataType", DataType::F32)))
FIXTURE_DATA_TEST_CASE (RunLarge, CLFullyConnectedLayerFixture< float >, framework::DatasetMode::NIGHTLY, combine(combine(datasets::LargeFullyConnectedLayerDataset(), FullyConnectedParameters), framework::dataset::make("DataType", DataType::F32)))
FIXTURE_DATA_TEST_CASE (RunSmall, CLFullyConnectedLayerFixedPointFixture< int8_t >, framework::DatasetMode::PRECOMMIT, combine(combine(combine(datasets::SmallFullyConnectedLayerDataset(), FullyConnectedParameters), framework::dataset::make("DataType", DataType::QS8)), framework::dataset::make("FractionalBits", 1, 6)))
FIXTURE_DATA_TEST_CASE (RunLarge, CLFullyConnectedLayerFixedPointFixture< int8_t >, framework::DatasetMode::NIGHTLY, combine(combine(combine(datasets::LargeFullyConnectedLayerDataset(), FullyConnectedParameters), framework::dataset::make("DataType", DataType::QS8)), framework::dataset::make("FractionalBits", 1, 6)))
FIXTURE_DATA_TEST_CASE (RunSmall, CLFullyConnectedLayerFixedPointFixture< int16_t >, framework::DatasetMode::PRECOMMIT, combine(combine(combine(datasets::SmallFullyConnectedLayerDataset(), FullyConnectedParameters), framework::dataset::make("DataType", DataType::QS16)), framework::dataset::make("FractionalBits", 1, 14)))
FIXTURE_DATA_TEST_CASE (RunLarge, CLFullyConnectedLayerFixedPointFixture< int16_t >, framework::DatasetMode::NIGHTLY, combine(combine(combine(datasets::LargeFullyConnectedLayerDataset(), FullyConnectedParameters), framework::dataset::make("DataType", DataType::QS16)), framework::dataset::make("FractionalBits", 1, 14)))
FIXTURE_DATA_TEST_CASE (RunSmall, CLGaussian3x3Fixture< uint8_t >, framework::DatasetMode::PRECOMMIT, combine(combine(datasets::SmallShapes(), framework::dataset::make("DataType", DataType::U8)), datasets::BorderModes()))
FIXTURE_DATA_TEST_CASE (RunLarge, CLGaussian3x3Fixture< uint8_t >, framework::DatasetMode::NIGHTLY, combine(combine(datasets::LargeShapes(), framework::dataset::make("DataType", DataType::U8)), datasets::BorderModes()))
FIXTURE_DATA_TEST_CASE (RunSmall, CLGaussian5x5Fixture< uint8_t >, framework::DatasetMode::PRECOMMIT, combine(combine(datasets::SmallShapes(), framework::dataset::make("DataType", DataType::U8)), datasets::BorderModes()))
FIXTURE_DATA_TEST_CASE (RunLarge, CLGaussian5x5Fixture< uint8_t >, framework::DatasetMode::NIGHTLY, combine(combine(datasets::LargeShapes(), framework::dataset::make("DataType", DataType::U8)), datasets::BorderModes()))
DATA_TEST_CASE (Configuration, framework::DatasetMode::ALL, combine(framework::dataset::concat(datasets::SmallGEMMDataset(), datasets::LargeGEMMDataset()), CNNDataTypes), shape_a, shape_b, shape_c, output_shape, alpha, beta, data_type)
FIXTURE_DATA_TEST_CASE (RunSmall, CLGEMMFixture< half >, framework::DatasetMode::PRECOMMIT, combine(datasets::SmallGEMMDataset(), framework::dataset::make("DataType", DataType::F16)))
FIXTURE_DATA_TEST_CASE (RunLarge, CLGEMMFixture< half >, framework::DatasetMode::NIGHTLY, combine(datasets::LargeGEMMDataset(), framework::dataset::make("DataType", DataType::F16)))
FIXTURE_DATA_TEST_CASE (RunSmall, CLGEMMFixture< float >, framework::DatasetMode::PRECOMMIT, combine(datasets::SmallGEMMDataset(), framework::dataset::make("DataType", DataType::F32)))
FIXTURE_DATA_TEST_CASE (RunLarge, CLGEMMFixture< float >, framework::DatasetMode::NIGHTLY, combine(datasets::LargeGEMMDataset(), framework::dataset::make("DataType", DataType::F32)))
FIXTURE_DATA_TEST_CASE (RunSmall, CLGEMMFixedPointFixture< int8_t >, framework::DatasetMode::PRECOMMIT, combine(combine(datasets::SmallGEMMDataset(), framework::dataset::make("DataType", DataType::QS8)), framework::dataset::make("FractionalBits", 1, 7)))
FIXTURE_DATA_TEST_CASE (RunLarge, CLGEMMFixedPointFixture< int8_t >, framework::DatasetMode::NIGHTLY, combine(combine(datasets::LargeGEMMDataset(), framework::dataset::make("DataType", DataType::QS8)), framework::dataset::make("FractionalBits", 1, 7)))
FIXTURE_DATA_TEST_CASE (RunSmall, CLGEMMFixedPointFixture< int16_t >, framework::DatasetMode::PRECOMMIT, combine(combine(datasets::SmallGEMMDataset(), framework::dataset::make("DataType", DataType::QS16)), framework::dataset::make("FractionalBits", 1, 14)))
FIXTURE_DATA_TEST_CASE (RunLarge, CLGEMMFixedPointFixture< int16_t >, framework::DatasetMode::NIGHTLY, combine(combine(datasets::LargeGEMMDataset(), framework::dataset::make("DataType", DataType::QS16)), framework::dataset::make("FractionalBits", 1, 14)))
FIXTURE_DATA_TEST_CASE (RunGlobalPooling, CLGlobalPoolingLayerFixture< float >, framework::DatasetMode::ALL, combine(GlobalPoolingLayerDataset, framework::dataset::make("DataType", DataType::F32)))
FIXTURE_DATA_TEST_CASE (RunGlobalPooling, CLGlobalPoolingLayerFixture< half >, framework::DatasetMode::ALL, combine(GlobalPoolingLayerDataset, framework::dataset::make("DataType", DataType::F16)))
DATA_TEST_CASE (Configuration, framework::DatasetMode::ALL, combine(combine(concat(datasets::Small2DShapes(), datasets::Large2DShapes()), data), framework::dataset::make("Format", Format::U8)), shape, gradient_size, block_size, border_mode, use_fp16, format)
FIXTURE_DATA_TEST_CASE (RunSmall, CLHarrisCornersFixture< uint8_t >, framework::DatasetMode::PRECOMMIT, combine(combine(datasets::Small2DShapes(), data), framework::dataset::make("Format", Format::U8)))
FIXTURE_DATA_TEST_CASE (RunLarge, CLHarrisCornersFixture< uint8_t >, framework::DatasetMode::NIGHTLY, combine(combine(datasets::Large2DShapes(), data), framework::dataset::make("Format", Format::U8)))
FIXTURE_DATA_TEST_CASE (RunSmall, CLIntegralImageFixture< uint8_t >, framework::DatasetMode::PRECOMMIT, combine(datasets::SmallShapes(), framework::dataset::make("DataType", DataType::U8)))
FIXTURE_DATA_TEST_CASE (RunLarge, CLIntegralImageFixture< uint8_t >, framework::DatasetMode::NIGHTLY, combine(datasets::LargeShapes(), framework::dataset::make("DataType", DataType::U8)))
FIXTURE_DATA_TEST_CASE (RunSmall, CLL2NormalizeFixture< float >, framework::DatasetMode::PRECOMMIT, combine(combine(combine(datasets::SmallShapes(), framework::dataset::make("DataType", DataType::F32)), framework::dataset::make("Axis",{0})), framework::dataset::make("Epsilon",{1e-12})))
FIXTURE_DATA_TEST_CASE (RunLarge, CLL2NormalizeFixture< float >, framework::DatasetMode::NIGHTLY, combine(combine(combine(datasets::LargeShapes(), framework::dataset::make("DataType", DataType::F32)), framework::dataset::make("Axis",{0})), framework::dataset::make("Epsilon",{1e-12})))
DATA_TEST_CASE (Configuration, framework::DatasetMode::ALL, combine(concat(datasets::Small2DShapes(), datasets::Large2DShapes()), framework::dataset::make("DataType", DataType::U8)), shape, data_type)
FIXTURE_DATA_TEST_CASE (RunSmall, CLMeanStdDevFixture< uint8_t >, framework::DatasetMode::PRECOMMIT, combine(datasets::Small2DShapes(), framework::dataset::make("DataType", DataType::U8)))
FIXTURE_DATA_TEST_CASE (RunLarge, CLMeanStdDevFixture< uint8_t >, framework::DatasetMode::NIGHTLY, combine(datasets::Large2DShapes(), framework::dataset::make("DataType", DataType::U8)))
void validate_configuration (const CLTensor &src, TensorShape shape)
FIXTURE_DATA_TEST_CASE (RunSmall, CLMinMaxLocationFixture< uint8_t >, framework::DatasetMode::PRECOMMIT, combine(datasets::Small2DShapes(), framework::dataset::make("DataType", DataType::U8)))
FIXTURE_DATA_TEST_CASE (RunLarge, CLMinMaxLocationFixture< uint8_t >, framework::DatasetMode::NIGHTLY, combine(datasets::Large2DShapes(), framework::dataset::make("DataType", DataType::U8)))
TEST_SUITE_END () DATA_TEST_CASE(Configuration
combine (concat(datasets::Small2DShapes(), datasets::Large2DShapes()), framework::dataset::make("DataType", DataType::S16))
src info () -> set_format(Format::S16)
validate_configuration (src, shape)
FIXTURE_DATA_TEST_CASE (RunSmall, CLMinMaxLocationFixture< int16_t >, framework::DatasetMode::PRECOMMIT, combine(datasets::Small2DShapes(), framework::dataset::make("DataType", DataType::S16)))
FIXTURE_DATA_TEST_CASE (RunLarge, CLMinMaxLocationFixture< int16_t >, framework::DatasetMode::NIGHTLY, combine(datasets::Large2DShapes(), framework::dataset::make("DataType", DataType::S16)))
combine (concat(datasets::Small2DShapes(), datasets::Large2DShapes()), framework::dataset::make("DataType", DataType::F32))
FIXTURE_DATA_TEST_CASE (RunSmall, CLMinMaxLocationFixture< float >, framework::DatasetMode::PRECOMMIT, combine(datasets::Small2DShapes(), framework::dataset::make("DataType", DataType::F32)))
FIXTURE_DATA_TEST_CASE (RunLarge, CLMinMaxLocationFixture< float >, framework::DatasetMode::NIGHTLY, combine(datasets::Large2DShapes(), framework::dataset::make("DataType", DataType::F32)))
DATA_TEST_CASE (Configuration, framework::DatasetMode::ALL, combine(combine(combine(combine(concat(datasets::SmallShapes(), datasets::LargeShapes()), datasets::NonLinearFilterFunctions()), framework::dataset::make("MaskSize",{3U, 5U})), datasets::MatrixPatterns()), datasets::BorderModes()), shape, function, mask_size, pattern, border_mode)
FIXTURE_DATA_TEST_CASE (RunSmall, CLNonLinearFilterFixture< uint8_t >, framework::DatasetMode::PRECOMMIT, combine(combine(combine(combine(combine(datasets::SmallShapes(), datasets::NonLinearFilterFunctions()), framework::dataset::make("MaskSize",{3U, 5U})), datasets::MatrixPatterns()), datasets::BorderModes()), framework::dataset::make("DataType", DataType::U8)))
FIXTURE_DATA_TEST_CASE (RunLarge, CLNonLinearFilterFixture< uint8_t >, framework::DatasetMode::NIGHTLY, combine(combine(combine(combine(combine(datasets::LargeShapes(), datasets::NonLinearFilterFunctions()), framework::dataset::make("MaskSize",{3U, 5U})), datasets::MatrixPatterns()), datasets::BorderModes()), framework::dataset::make("DataType", DataType::U8)))
FIXTURE_DATA_TEST_CASE (RunSmall, CLNormalizationLayerFixture< half >, framework::DatasetMode::PRECOMMIT, combine(NormalizationDataset, framework::dataset::make("DataType", DataType::F16)))
FIXTURE_DATA_TEST_CASE (RunLarge, CLNormalizationLayerFixture< half >, framework::DatasetMode::NIGHTLY, combine(NormalizationDataset, framework::dataset::make("DataType", DataType::F16)))
FIXTURE_DATA_TEST_CASE (RunSmall, CLNormalizationLayerFixture< float >, framework::DatasetMode::PRECOMMIT, combine(NormalizationDataset, framework::dataset::make("DataType", DataType::F32)))
FIXTURE_DATA_TEST_CASE (RunLarge, CLNormalizationLayerFixture< float >, framework::DatasetMode::NIGHTLY, combine(NormalizationDataset, framework::dataset::make("DataType", DataType::F32)))
FIXTURE_DATA_TEST_CASE (RunSmall, CLNormalizationLayerFixedPointFixture< int8_t >, framework::DatasetMode::PRECOMMIT, combine(combine(NormalizationDataset, framework::dataset::make("DataType", DataType::QS8)), framework::dataset::make("FractionalBits", 1, 6)))
FIXTURE_DATA_TEST_CASE (RunLarge, CLNormalizationLayerFixedPointFixture< int8_t >, framework::DatasetMode::NIGHTLY, combine(combine(NormalizationDataset, framework::dataset::make("DataType", DataType::QS8)), framework::dataset::make("FractionalBits", 1, 6)))
FIXTURE_DATA_TEST_CASE (RunSmall, CLNormalizationLayerFixedPointFixture< int16_t >, framework::DatasetMode::PRECOMMIT, combine(combine(NormalizationDataset, framework::dataset::make("DataType", DataType::QS16)), framework::dataset::make("FractionalBits", 1, 14)))
FIXTURE_DATA_TEST_CASE (RunLarge, CLNormalizationLayerFixedPointFixture< int16_t >, framework::DatasetMode::NIGHTLY, combine(combine(NormalizationDataset, framework::dataset::make("DataType", DataType::QS16)), framework::dataset::make("FractionalBits", 1, 14)))
FIXTURE_DATA_TEST_CASE (RunSmall, CLPoolingLayerFixture< float >, framework::DatasetMode::ALL, combine(datasets::SmallShapes(), combine(PoolingLayerDatasetFP, framework::dataset::make("DataType", DataType::F32))))
FIXTURE_DATA_TEST_CASE (RunLarge, CLPoolingLayerFixture< float >, framework::DatasetMode::NIGHTLY, combine(datasets::LargeShapes(), combine(PoolingLayerDatasetFP, framework::dataset::make("DataType", DataType::F32))))
FIXTURE_DATA_TEST_CASE (RunSmall, CLPoolingLayerFixture< half >, framework::DatasetMode::ALL, combine(datasets::SmallShapes(), combine(PoolingLayerDatasetFP, framework::dataset::make("DataType", DataType::F16))))
FIXTURE_DATA_TEST_CASE (RunLarge, CLPoolingLayerFixture< half >, framework::DatasetMode::NIGHTLY, combine(datasets::LargeShapes(), combine(PoolingLayerDatasetFP, framework::dataset::make("DataType", DataType::F16))))
FIXTURE_DATA_TEST_CASE (RunSmall, CLPoolingLayerFixedPointFixture< int8_t >, framework::DatasetMode::ALL, combine(combine(datasets::SmallShapes(), combine(PoolingLayerDatasetQS, framework::dataset::make("DataType", DataType::QS8))), framework::dataset::make("FractionalBits", 1, 4)))
FIXTURE_DATA_TEST_CASE (RunLarge, CLPoolingLayerFixedPointFixture< int8_t >, framework::DatasetMode::NIGHTLY, combine(combine(datasets::LargeShapes(), combine(PoolingLayerDatasetQS, framework::dataset::make("DataType", DataType::QS8))), framework::dataset::make("FractionalBits", 1, 4)))
FIXTURE_DATA_TEST_CASE (RunSmall, CLPoolingLayerFixedPointFixture< int16_t >, framework::DatasetMode::ALL, combine(combine(datasets::SmallShapes(), combine(PoolingLayerDatasetQS, framework::dataset::make("DataType", DataType::QS16))), framework::dataset::make("FractionalBits", 1, 12)))
FIXTURE_DATA_TEST_CASE (RunLarge, CLPoolingLayerFixedPointFixture< int16_t >, framework::DatasetMode::NIGHTLY, combine(combine(datasets::LargeShapes(), combine(PoolingLayerDatasetQS, framework::dataset::make("DataType", DataType::QS16))), framework::dataset::make("FractionalBits", 1, 12)))
DATA_TEST_CASE (Configuration, framework::DatasetMode::ALL, combine(QuantizationShapes, framework::dataset::make("DataType", DataType::F32)), shape, data_type)
FIXTURE_DATA_TEST_CASE (RunSmall, CLQuantizationLayerFixture< float >, framework::DatasetMode::PRECOMMIT, combine(concat(datasets::Small3DShapes(), datasets::Small4DShapes()), framework::dataset::make("DataType", DataType::F32)))
FIXTURE_DATA_TEST_CASE (RunLarge, CLQuantizationLayerFixture< float >, framework::DatasetMode::NIGHTLY, combine(concat(datasets::Large3DShapes(), datasets::Large4DShapes()), framework::dataset::make("DataType", DataType::F32)))
FIXTURE_DATA_TEST_CASE (RunSmall, CLReductionOperationFixture< float >, framework::DatasetMode::PRECOMMIT, combine(combine(combine(datasets::LargeShapes(), framework::dataset::make("DataType", DataType::F32)), framework::dataset::make("Axis",{0})), datasets::ReductionOperations()))
FIXTURE_DATA_TEST_CASE (RunLarge, CLReductionOperationFixture< float >, framework::DatasetMode::NIGHTLY, combine(combine(combine(datasets::LargeShapes(), framework::dataset::make("DataType", DataType::F32)), framework::dataset::make("Axis",{0})), datasets::ReductionOperations()))
FIXTURE_DATA_TEST_CASE (RunSmall, CLReshapeLayerFixture< float >, framework::DatasetMode::ALL, combine(datasets::SmallReshapeLayerDataset(), framework::dataset::make("DataType", DataType::F32)))
FIXTURE_DATA_TEST_CASE (RunSmall, CLReshapeLayerFixture< half >, framework::DatasetMode::ALL, combine(datasets::SmallReshapeLayerDataset(), framework::dataset::make("DataType", DataType::F16)))
FIXTURE_DATA_TEST_CASE (RunSmall, CLReshapeLayerFixture< int8_t >, framework::DatasetMode::ALL, combine(datasets::SmallReshapeLayerDataset(), framework::dataset::make("DataType", DataType::S8)))
FIXTURE_DATA_TEST_CASE (RunSmall, CLReshapeLayerFixture< int16_t >, framework::DatasetMode::ALL, combine(datasets::SmallReshapeLayerDataset(), framework::dataset::make("DataType", DataType::S16)))
DATA_TEST_CASE (Configuration, framework::DatasetMode::ALL, combine(combine(combine(concat(datasets::MediumShapes(), datasets::LargeShapes()), ScaleDataTypes), framework::dataset::make("InterpolationPolicy",{InterpolationPolicy::NEAREST_NEIGHBOR, InterpolationPolicy::BILINEAR})), datasets::BorderModes()), shape, data_type, policy, border_mode)
FIXTURE_DATA_TEST_CASE (RunSmall, CLScaleFixture< float >, framework::DatasetMode::ALL, combine(combine(combine(datasets::SmallShapes(), framework::dataset::make("DataType", DataType::F32)), framework::dataset::make("InterpolationPolicy",{InterpolationPolicy::NEAREST_NEIGHBOR, InterpolationPolicy::BILINEAR})), datasets::BorderModes()))
FIXTURE_DATA_TEST_CASE (RunLarge, CLScaleFixture< float >, framework::DatasetMode::NIGHTLY, combine(combine(combine(datasets::LargeShapes(), framework::dataset::make("DataType", DataType::F32)), framework::dataset::make("InterpolationPolicy",{InterpolationPolicy::NEAREST_NEIGHBOR, InterpolationPolicy::BILINEAR})), datasets::BorderModes()))
FIXTURE_DATA_TEST_CASE (RunSmall, CLScaleFixture< half >, framework::DatasetMode::ALL, combine(combine(combine(datasets::SmallShapes(), framework::dataset::make("DataType", DataType::F16)), framework::dataset::make("InterpolationPolicy",{InterpolationPolicy::NEAREST_NEIGHBOR, InterpolationPolicy::BILINEAR})), datasets::BorderModes()))
FIXTURE_DATA_TEST_CASE (RunLarge, CLScaleFixture< half >, framework::DatasetMode::NIGHTLY, combine(combine(combine(datasets::LargeShapes(), framework::dataset::make("DataType", DataType::F16)), framework::dataset::make("InterpolationPolicy",{InterpolationPolicy::NEAREST_NEIGHBOR, InterpolationPolicy::BILINEAR})), datasets::BorderModes()))
FIXTURE_DATA_TEST_CASE (RunSmall, CLScaleFixture< uint8_t >, framework::DatasetMode::ALL, combine(combine(combine(datasets::SmallShapes(), framework::dataset::make("DataType", DataType::U8)), framework::dataset::make("InterpolationPolicy",{InterpolationPolicy::NEAREST_NEIGHBOR, InterpolationPolicy::BILINEAR})), datasets::BorderModes()))
FIXTURE_DATA_TEST_CASE (RunLarge, CLScaleFixture< uint8_t >, framework::DatasetMode::NIGHTLY, combine(combine(combine(datasets::LargeShapes(), framework::dataset::make("DataType", DataType::U8)), framework::dataset::make("InterpolationPolicy",{InterpolationPolicy::NEAREST_NEIGHBOR, InterpolationPolicy::BILINEAR})), datasets::BorderModes()))
FIXTURE_DATA_TEST_CASE (RunSmall, CLScaleFixture< int16_t >, framework::DatasetMode::ALL, combine(combine(combine(datasets::SmallShapes(), framework::dataset::make("DataType", DataType::S16)), framework::dataset::make("InterpolationPolicy",{InterpolationPolicy::NEAREST_NEIGHBOR, InterpolationPolicy::BILINEAR})), datasets::BorderModes()))
FIXTURE_DATA_TEST_CASE (RunLarge, CLScaleFixture< int16_t >, framework::DatasetMode::NIGHTLY, combine(combine(combine(datasets::LargeShapes(), framework::dataset::make("DataType", DataType::S16)), framework::dataset::make("InterpolationPolicy",{InterpolationPolicy::NEAREST_NEIGHBOR, InterpolationPolicy::BILINEAR})), datasets::BorderModes()))
DATA_TEST_CASE (Configuration, framework::DatasetMode::ALL, combine(combine(concat(datasets::Small2DShapes(), datasets::Large2DShapes()), datasets::BorderModes()), framework::dataset::make("Format", Format::U8)), shape, border_mode, format)
FIXTURE_DATA_TEST_CASE (RunSmall, CLSobel3x3Fixture, framework::DatasetMode::PRECOMMIT, combine(combine(datasets::Small2DShapes(), datasets::BorderModes()), framework::dataset::make("Format", Format::U8)))
FIXTURE_DATA_TEST_CASE (RunLarge, CLSobel3x3Fixture, framework::DatasetMode::NIGHTLY, combine(combine(datasets::Large2DShapes(), datasets::BorderModes()), framework::dataset::make("Format", Format::U8)))
FIXTURE_DATA_TEST_CASE (RunSmall, CLSobel5x5Fixture, framework::DatasetMode::PRECOMMIT, combine(combine(datasets::Small2DShapes(), datasets::BorderModes()), framework::dataset::make("Format", Format::U8)))
FIXTURE_DATA_TEST_CASE (RunLarge, CLSobel5x5Fixture, framework::DatasetMode::NIGHTLY, combine(combine(datasets::Large2DShapes(), datasets::BorderModes()), framework::dataset::make("Format", Format::U8)))
FIXTURE_DATA_TEST_CASE (RunSmall, CLSobel7x7Fixture, framework::DatasetMode::PRECOMMIT, combine(combine(datasets::Small2DShapes(), datasets::BorderModes()), framework::dataset::make("Format", Format::U8)))
FIXTURE_DATA_TEST_CASE (RunLarge, CLSobel7x7Fixture, framework::DatasetMode::NIGHTLY, combine(combine(datasets::Large2DShapes(), datasets::BorderModes()), framework::dataset::make("Format", Format::U8)))
DATA_TEST_CASE (Configuration, framework::DatasetMode::ALL, combine(concat(datasets::SmallShapes(), datasets::LargeShapes()), CNNDataTypes), shape, data_type)
FIXTURE_DATA_TEST_CASE (RunSmall, CLSoftmaxLayerFixture< half >, framework::DatasetMode::PRECOMMIT, combine(datasets::SmallShapes(), framework::dataset::make("DataType", DataType::F16)))
FIXTURE_DATA_TEST_CASE (RunLarge, CLSoftmaxLayerFixture< half >, framework::DatasetMode::NIGHTLY, combine(datasets::LargeShapes(), framework::dataset::make("DataType", DataType::F16)))
FIXTURE_DATA_TEST_CASE (RunSmall, CLSoftmaxLayerFixture< float >, framework::DatasetMode::PRECOMMIT, combine(datasets::SmallShapes(), framework::dataset::make("DataType", DataType::F32)))
FIXTURE_DATA_TEST_CASE (RunLarge, CLSoftmaxLayerFixture< float >, framework::DatasetMode::NIGHTLY, combine(datasets::LargeShapes(), framework::dataset::make("DataType", DataType::F32)))
FIXTURE_DATA_TEST_CASE (RunSmall, CLSoftmaxLayerFixedPointFixture< int8_t >, framework::DatasetMode::PRECOMMIT, combine(combine(datasets::SmallShapes(), framework::dataset::make("DataType", DataType::QS8)), framework::dataset::make("FractionalBits", 1, 6)))
FIXTURE_DATA_TEST_CASE (RunLarge, CLSoftmaxLayerFixedPointFixture< int8_t >, framework::DatasetMode::NIGHTLY, combine(combine(datasets::LargeShapes(), framework::dataset::make("DataType", DataType::QS8)), framework::dataset::make("FractionalBits", 1, 6)))
FIXTURE_DATA_TEST_CASE (RunSmall, CLSoftmaxLayerFixedPointFixture< int16_t >, framework::DatasetMode::PRECOMMIT, combine(combine(datasets::SmallShapes(), framework::dataset::make("DataType", DataType::QS16)), framework::dataset::make("FractionalBits", 1, 14)))
FIXTURE_DATA_TEST_CASE (RunLarge, CLSoftmaxLayerFixedPointFixture< int16_t >, framework::DatasetMode::NIGHTLY, combine(combine(datasets::LargeShapes(), framework::dataset::make("DataType", DataType::QS16)), framework::dataset::make("FractionalBits", 1, 14)))
TEST_CASE (AlexNet, framework::DatasetMode::PRECOMMIT)
TEST_CASE (LeNet5, framework::DatasetMode::PRECOMMIT)
DATA_TEST_CASE (Configuration, framework::DatasetMode::ALL, combine(framework::dataset::concat(datasets::SmallShapes(), datasets::LargeShapes()), framework::dataset::make("DataType",{DataType::U8, DataType::S16})), shape, data_type)
FIXTURE_DATA_TEST_CASE (RunSmallU8, CLTableLookupFixture< uint8_t >, framework::DatasetMode::PRECOMMIT, combine(datasets::SmallShapes(), framework::dataset::make("DataType", DataType::U8)))
FIXTURE_DATA_TEST_CASE (RunLargeU8, CLTableLookupFixture< uint8_t >, framework::DatasetMode::NIGHTLY, combine(datasets::LargeShapes(), framework::dataset::make("DataType", DataType::U8)))
FIXTURE_DATA_TEST_CASE (RunSmallS16, CLTableLookupFixture< int16_t >, framework::DatasetMode::PRECOMMIT, combine(datasets::SmallShapes(), framework::dataset::make("DataType", DataType::S16)))
FIXTURE_DATA_TEST_CASE (RunLargeS16, CLTableLookupFixture< int16_t >, framework::DatasetMode::NIGHTLY, combine(datasets::LargeShapes(), framework::dataset::make("DataType", DataType::S16)))
DATA_TEST_CASE (Configuration, framework::DatasetMode::ALL, combine(combine(concat(datasets::SmallShapes(), datasets::LargeShapes()), datasets::MixedThresholdDataset()), framework::dataset::make("DataType", DataType::U8)), shape, threshold, false_value, true_value, type, upper, data_type)
FIXTURE_DATA_TEST_CASE (RunSmall, CLThresholdFixture< uint8_t >, framework::DatasetMode::PRECOMMIT, combine(combine(datasets::SmallShapes(), datasets::MixedThresholdDataset()), framework::dataset::make("DataType", DataType::U8)))
FIXTURE_DATA_TEST_CASE (RunLarge, CLThresholdFixture< uint8_t >, framework::DatasetMode::NIGHTLY, combine(combine(datasets::LargeShapes(), datasets::MixedThresholdDataset()), framework::dataset::make("DataType", DataType::U8)))
DATA_TEST_CASE (Configuration, framework::DatasetMode::ALL, combine(combine(combine(concat(datasets::SmallShapes(), datasets::LargeShapes()), framework::dataset::make("DataType", DataType::U8)), framework::dataset::make("InterpolationPolicy",{InterpolationPolicy::NEAREST_NEIGHBOR, InterpolationPolicy::BILINEAR})), datasets::BorderModes()), shape, data_type, policy, border_mode)
FIXTURE_DATA_TEST_CASE (RunSmall, CLWarpAffineFixture< uint8_t >, framework::DatasetMode::PRECOMMIT, combine(combine(combine(datasets::SmallShapes(), framework::dataset::make("DataType", DataType::U8)), framework::dataset::make("InterpolationPolicy",{InterpolationPolicy::NEAREST_NEIGHBOR, InterpolationPolicy::BILINEAR})), datasets::BorderModes()))
FIXTURE_DATA_TEST_CASE (RunLarge, CLWarpAffineFixture< uint8_t >, framework::DatasetMode::NIGHTLY, combine(combine(combine(datasets::LargeShapes(), framework::dataset::make("DataType", DataType::U8)), framework::dataset::make("InterpolationPolicy",{InterpolationPolicy::NEAREST_NEIGHBOR, InterpolationPolicy::BILINEAR})), datasets::BorderModes()))
FIXTURE_DATA_TEST_CASE (RunSmall, CLWarpPerspectiveFixture< uint8_t >, framework::DatasetMode::PRECOMMIT, combine(combine(combine(datasets::SmallShapes(), framework::dataset::make("DataType", DataType::U8)), framework::dataset::make("InterpolationPolicy",{InterpolationPolicy::NEAREST_NEIGHBOR, InterpolationPolicy::BILINEAR})), datasets::BorderModes()))
FIXTURE_DATA_TEST_CASE (RunLarge, CLWarpPerspectiveFixture< uint8_t >, framework::DatasetMode::NIGHTLY, combine(combine(combine(datasets::LargeShapes(), framework::dataset::make("DataType", DataType::U8)), framework::dataset::make("InterpolationPolicy",{InterpolationPolicy::NEAREST_NEIGHBOR, InterpolationPolicy::BILINEAR})), datasets::BorderModes()))
template<typename T >
T bilinear_policy (const SimpleTensor< T > &in, Coordinates id, float xn, float yn, BorderMode border_mode, T constant_border_value)
template uint8_t bilinear_policy (const SimpleTensor< uint8_t > &in, Coordinates id, float xn, float yn, BorderMode border_mode, uint8_t constant_border_value)
template int16_t bilinear_policy (const SimpleTensor< int16_t > &in, Coordinates id, float xn, float yn, BorderMode border_mode, int16_t constant_border_value)
template half bilinear_policy (const SimpleTensor< half > &in, Coordinates id, float xn, float yn, BorderMode border_mode, half constant_border_value)
template float bilinear_policy (const SimpleTensor< float > &in, Coordinates id, float xn, float yn, BorderMode border_mode, float constant_border_value)
RawTensor transpose (const RawTensor &src, int chunk_width)
bool valid_bilinear_policy (float xn, float yn, int width, int height, BorderMode border_mode)
template<typename T >
T tensor_elem_at (const SimpleTensor< T > &src, Coordinates coord, BorderMode border_mode, T constant_border_value)
template<typename T , typename U , typename V >
void apply_2d_spatial_filter (Coordinates coord, const SimpleTensor< T > &src, SimpleTensor< U > &dst, const TensorShape &filter_shape, const V *filter_itr, double scale, BorderMode border_mode, T constant_border_value=T(0))
template<std::size_t SIZE>
void fill_warp_matrix (std::array< float, SIZE > &matrix)
Fill matrix random.
void fill_mask_from_pattern (uint8_t *mask, int cols, int rows, MatrixPattern pattern)
Fill mask with the corresponding given pattern.
TensorShape calculate_depth_concatenate_shape (const std::vector< TensorShape > &input_shapes)
Calculate output tensor shape give a vector of input tensor to concatenate.
HarrisCornersParameters harris_corners_parameters ()
Generate parameters for Harris Corners algorithm.
template<typename T >
std::pair< T, T > get_activation_layer_test_bounds (ActivationLayerInfo::ActivationFunction activation, DataType data_type, int fixed_point_position=0)
Helper function to get the testing range for each activation layer.
template<typename T >
void fill_lookuptable (T &&table)
Helper function to fill the Lut random by a ILutAccessor.
template<typename T >
std::pair< T, T > get_batchnormalization_layer_test_bounds (int fixed_point_position=1)
Helper function to get the testing range for batch normalization layer.
FIXTURE_DATA_TEST_CASE (RunSmall, NEActivationLayerFixture< half >, framework::DatasetMode::PRECOMMIT, combine(combine(datasets::SmallShapes(), ActivationDataset), framework::dataset::make("DataType", DataType::F16)))
FIXTURE_DATA_TEST_CASE (RunLarge, NEActivationLayerFixture< half >, framework::DatasetMode::NIGHTLY, combine(combine(datasets::LargeShapes(), ActivationDataset), framework::dataset::make("DataType", DataType::F16)))
FIXTURE_DATA_TEST_CASE (RunSmall, NEActivationLayerFixture< float >, framework::DatasetMode::PRECOMMIT, combine(combine(datasets::SmallShapes(), ActivationDataset), framework::dataset::make("DataType", DataType::F32)))
FIXTURE_DATA_TEST_CASE (RunLarge, NEActivationLayerFixture< float >, framework::DatasetMode::NIGHTLY, combine(combine(datasets::LargeShapes(), ActivationDataset), framework::dataset::make("DataType", DataType::F32)))
FIXTURE_DATA_TEST_CASE (RunSmall, NEActivationLayerFixedPointFixture< int8_t >, framework::DatasetMode::PRECOMMIT, combine(combine(combine(datasets::SmallShapes(), ActivationDataset), framework::dataset::make("DataType", DataType::QS8)), framework::dataset::make("FractionalBits", 3, 6)))
FIXTURE_DATA_TEST_CASE (RunLarge, NEActivationLayerFixedPointFixture< int8_t >, framework::DatasetMode::NIGHTLY, combine(combine(combine(datasets::LargeShapes(), ActivationDataset), framework::dataset::make("DataType", DataType::QS8)), framework::dataset::make("FractionalBits", 3, 6)))
FIXTURE_DATA_TEST_CASE (RunSmall, NEActivationLayerFixedPointFixture< int16_t >, framework::DatasetMode::PRECOMMIT, combine(combine(combine(datasets::SmallShapes(), ActivationDataset), framework::dataset::make("DataType", DataType::QS16)), framework::dataset::make("FractionalBits", 1, 14)))
FIXTURE_DATA_TEST_CASE (RunLarge, NEActivationLayerFixedPointFixture< int16_t >, framework::DatasetMode::NIGHTLY, combine(combine(combine(datasets::LargeShapes(), ActivationDataset), framework::dataset::make("DataType", DataType::QS16)), framework::dataset::make("FractionalBits", 1, 14)))
FIXTURE_DATA_TEST_CASE (RunSmall, NEArithmeticAdditionFixture< uint8_t >, framework::DatasetMode::PRECOMMIT, combine(combine(datasets::SmallShapes(), ArithmeticAdditionU8Dataset), framework::dataset::make("ConvertPolicy",{ConvertPolicy::SATURATE, ConvertPolicy::WRAP})))
FIXTURE_DATA_TEST_CASE (RunSmall, NEArithmeticAdditionFixture< int16_t >, framework::DatasetMode::PRECOMMIT, combine(combine(datasets::SmallShapes(), ArithmeticAdditionS16Dataset), framework::dataset::make("ConvertPolicy",{ConvertPolicy::SATURATE, ConvertPolicy::WRAP})))
FIXTURE_DATA_TEST_CASE (RunLarge, NEArithmeticAdditionFixture< int16_t >, framework::DatasetMode::NIGHTLY, combine(combine(datasets::LargeShapes(), ArithmeticAdditionS16Dataset), framework::dataset::make("ConvertPolicy",{ConvertPolicy::SATURATE, ConvertPolicy::WRAP})))
FIXTURE_DATA_TEST_CASE (RunSmall, NEArithmeticAdditionFixedPointFixture< int8_t >, framework::DatasetMode::PRECOMMIT, combine(combine(combine(datasets::SmallShapes(), ArithmeticAdditionQS8Dataset), framework::dataset::make("ConvertPolicy",{ConvertPolicy::SATURATE, ConvertPolicy::WRAP})), framework::dataset::make("FractionalBits", 1, 7)))
FIXTURE_DATA_TEST_CASE (RunLarge, NEArithmeticAdditionFixedPointFixture< int8_t >, framework::DatasetMode::NIGHTLY, combine(combine(combine(datasets::LargeShapes(), ArithmeticAdditionQS8Dataset), framework::dataset::make("ConvertPolicy",{ConvertPolicy::SATURATE, ConvertPolicy::WRAP})), framework::dataset::make("FractionalBits", 1, 7)))
FIXTURE_DATA_TEST_CASE (RunSmall, NEArithmeticAdditionFixedPointFixture< int16_t >, framework::DatasetMode::PRECOMMIT, combine(combine(combine(datasets::SmallShapes(), ArithmeticAdditionQS16Dataset), framework::dataset::make("ConvertPolicy",{ConvertPolicy::SATURATE, ConvertPolicy::WRAP})), framework::dataset::make("FractionalBits", 1, 15)))
FIXTURE_DATA_TEST_CASE (RunLarge, NEArithmeticAdditionFixedPointFixture< int16_t >, framework::DatasetMode::NIGHTLY, combine(combine(combine(datasets::LargeShapes(), ArithmeticAdditionQS16Dataset), framework::dataset::make("ConvertPolicy",{ConvertPolicy::SATURATE, ConvertPolicy::WRAP})), framework::dataset::make("FractionalBits", 1, 15)))
FIXTURE_DATA_TEST_CASE (RunSmall, NEArithmeticAdditionFixture< half >, framework::DatasetMode::ALL, combine(combine(datasets::SmallShapes(), ArithmeticAdditionFP16Dataset), framework::dataset::make("ConvertPolicy",{ConvertPolicy::SATURATE, ConvertPolicy::WRAP})))
FIXTURE_DATA_TEST_CASE (RunSmall, NEArithmeticAdditionFixture< float >, framework::DatasetMode::PRECOMMIT, combine(combine(datasets::SmallShapes(), ArithmeticAdditionFP32Dataset), framework::dataset::make("ConvertPolicy",{ConvertPolicy::SATURATE, ConvertPolicy::WRAP})))
FIXTURE_DATA_TEST_CASE (RunLarge, NEArithmeticAdditionFixture< float >, framework::DatasetMode::NIGHTLY, combine(combine(datasets::LargeShapes(), ArithmeticAdditionFP32Dataset), framework::dataset::make("ConvertPolicy",{ConvertPolicy::SATURATE, ConvertPolicy::WRAP})))
FIXTURE_DATA_TEST_CASE (RunSmall, NEArithmeticSubtractionFixture< uint8_t >, framework::DatasetMode::PRECOMMIT, combine(combine(datasets::SmallShapes(), ArithmeticSubtractionU8Dataset), framework::dataset::make("ConvertPolicy",{ConvertPolicy::SATURATE, ConvertPolicy::WRAP})))
FIXTURE_DATA_TEST_CASE (RunSmall, NEArithmeticSubtractionFixture< int16_t >, framework::DatasetMode::PRECOMMIT, combine(combine(datasets::SmallShapes(), ArithmeticSubtractionS16Dataset), framework::dataset::make("ConvertPolicy",{ConvertPolicy::SATURATE, ConvertPolicy::WRAP})))
FIXTURE_DATA_TEST_CASE (RunLarge, NEArithmeticSubtractionFixture< int16_t >, framework::DatasetMode::NIGHTLY, combine(combine(datasets::LargeShapes(), ArithmeticSubtractionS16Dataset), framework::dataset::make("ConvertPolicy",{ConvertPolicy::SATURATE, ConvertPolicy::WRAP})))
FIXTURE_DATA_TEST_CASE (RunSmall, NEArithmeticSubtractionFixedPointFixture< int8_t >, framework::DatasetMode::PRECOMMIT, combine(combine(combine(datasets::SmallShapes(), ArithmeticSubtractionQS8Dataset), framework::dataset::make("ConvertPolicy",{ConvertPolicy::SATURATE, ConvertPolicy::WRAP})), framework::dataset::make("FractionalBits", 1, 7)))
FIXTURE_DATA_TEST_CASE (RunLarge, NEArithmeticSubtractionFixedPointFixture< int8_t >, framework::DatasetMode::NIGHTLY, combine(combine(combine(datasets::LargeShapes(), ArithmeticSubtractionQS8Dataset), framework::dataset::make("ConvertPolicy",{ConvertPolicy::SATURATE, ConvertPolicy::WRAP})), framework::dataset::make("FractionalBits", 1, 7)))
FIXTURE_DATA_TEST_CASE (RunSmall, NEArithmeticSubtractionFixedPointFixture< int16_t >, framework::DatasetMode::PRECOMMIT, combine(combine(combine(datasets::SmallShapes(), ArithmeticSubtractionQS16Dataset), framework::dataset::make("ConvertPolicy",{ConvertPolicy::SATURATE, ConvertPolicy::WRAP})), framework::dataset::make("FractionalBits", 1, 15)))
FIXTURE_DATA_TEST_CASE (RunLarge, NEArithmeticSubtractionFixedPointFixture< int16_t >, framework::DatasetMode::NIGHTLY, combine(combine(combine(datasets::LargeShapes(), ArithmeticSubtractionQS16Dataset), framework::dataset::make("ConvertPolicy",{ConvertPolicy::SATURATE, ConvertPolicy::WRAP})), framework::dataset::make("FractionalBits", 1, 15)))
FIXTURE_DATA_TEST_CASE (RunSmall, NEArithmeticSubtractionFixture< half >, framework::DatasetMode::ALL, combine(combine(datasets::SmallShapes(), ArithmeticSubtractionFP16Dataset), framework::dataset::make("ConvertPolicy",{ConvertPolicy::SATURATE, ConvertPolicy::WRAP})))
FIXTURE_DATA_TEST_CASE (RunSmall, NEArithmeticSubtractionFixture< float >, framework::DatasetMode::PRECOMMIT, combine(combine(datasets::SmallShapes(), ArithmeticSubtractionFP32Dataset), framework::dataset::make("ConvertPolicy",{ConvertPolicy::SATURATE, ConvertPolicy::WRAP})))
FIXTURE_DATA_TEST_CASE (RunLarge, NEArithmeticSubtractionFixture< float >, framework::DatasetMode::NIGHTLY, combine(combine(datasets::LargeShapes(), ArithmeticSubtractionFP32Dataset), framework::dataset::make("ConvertPolicy",{ConvertPolicy::SATURATE, ConvertPolicy::WRAP})))
DATA_TEST_CASE (Configuration, framework::DatasetMode::ALL, combine(datasets::RandomBatchNormalizationLayerDataset(), framework::dataset::make("DataType",{DataType::QS8, DataType::QS16, DataType::F32})), shape0, shape1, epsilon, dt)
FIXTURE_DATA_TEST_CASE (Random, NEBatchNormalizationLayerFixture< float >, framework::DatasetMode::PRECOMMIT, combine(datasets::RandomBatchNormalizationLayerDataset(), framework::dataset::make("DataType", DataType::F32)))
FIXTURE_DATA_TEST_CASE (Random, NEBatchNormalizationLayerFixture< half >, framework::DatasetMode::PRECOMMIT, combine(datasets::RandomBatchNormalizationLayerDataset(), framework::dataset::make("DataType", DataType::F16)))
FIXTURE_DATA_TEST_CASE (Random, NEBatchNormalizationLayerFixedPointFixture< int8_t >, framework::DatasetMode::PRECOMMIT, combine(combine(datasets::RandomBatchNormalizationLayerDataset(), framework::dataset::make("DataType", DataType::QS8)), framework::dataset::make("FractionalBits", 1, 6)))
FIXTURE_DATA_TEST_CASE (Random, NEBatchNormalizationLayerFixedPointFixture< int16_t >, framework::DatasetMode::PRECOMMIT, combine(combine(datasets::RandomBatchNormalizationLayerDataset(), framework::dataset::make("DataType", DataType::QS16)), framework::dataset::make("FractionalBits", 1, 14)))
FIXTURE_DATA_TEST_CASE (RunSmall, NEBitwiseAndFixture< uint8_t >, framework::DatasetMode::PRECOMMIT, combine(datasets::SmallShapes(), framework::dataset::make("DataType", DataType::U8)))
FIXTURE_DATA_TEST_CASE (RunLarge, NEBitwiseAndFixture< uint8_t >, framework::DatasetMode::NIGHTLY, combine(datasets::LargeShapes(), framework::dataset::make("DataType", DataType::U8)))
FIXTURE_DATA_TEST_CASE (RunSmall, NEBitwiseNotFixture< uint8_t >, framework::DatasetMode::PRECOMMIT, combine(datasets::SmallShapes(), framework::dataset::make("DataType", DataType::U8)))
FIXTURE_DATA_TEST_CASE (RunLarge, NEBitwiseNotFixture< uint8_t >, framework::DatasetMode::NIGHTLY, combine(datasets::LargeShapes(), framework::dataset::make("DataType", DataType::U8)))
FIXTURE_DATA_TEST_CASE (RunSmall, NEBitwiseOrFixture< uint8_t >, framework::DatasetMode::PRECOMMIT, combine(datasets::SmallShapes(), framework::dataset::make("DataType", DataType::U8)))
FIXTURE_DATA_TEST_CASE (RunLarge, NEBitwiseOrFixture< uint8_t >, framework::DatasetMode::NIGHTLY, combine(datasets::LargeShapes(), framework::dataset::make("DataType", DataType::U8)))
FIXTURE_DATA_TEST_CASE (RunSmall, NEBitwiseXorFixture< uint8_t >, framework::DatasetMode::PRECOMMIT, combine(datasets::SmallShapes(), framework::dataset::make("DataType", DataType::U8)))
FIXTURE_DATA_TEST_CASE (RunLarge, NEBitwiseXorFixture< uint8_t >, framework::DatasetMode::NIGHTLY, combine(datasets::LargeShapes(), framework::dataset::make("DataType", DataType::U8)))
FIXTURE_DATA_TEST_CASE (RunSmall, NEBox3x3Fixture< uint8_t >, framework::DatasetMode::PRECOMMIT, combine(combine(datasets::SmallShapes(), framework::dataset::make("DataType", DataType::U8)), datasets::BorderModes()))
FIXTURE_DATA_TEST_CASE (RunLarge, NEBox3x3Fixture< uint8_t >, framework::DatasetMode::NIGHTLY, combine(combine(datasets::LargeShapes(), framework::dataset::make("DataType", DataType::U8)), datasets::BorderModes()))
FIXTURE_DATA_TEST_CASE (RunSmall, NEConvolutionLayerFixture< half >, framework::DatasetMode::PRECOMMIT, combine(combine(datasets::SmallConvolutionLayerDataset(), framework::dataset::make("ReshapeWeights",{true, false})), framework::dataset::make("DataType", DataType::F16)))
FIXTURE_DATA_TEST_CASE (RunLarge, NEConvolutionLayerFixture< half >, framework::DatasetMode::NIGHTLY, combine(combine(datasets::LargeConvolutionLayerDataset(), framework::dataset::make("ReshapeWeights",{true, false})), framework::dataset::make("DataType", DataType::F16)))
FIXTURE_DATA_TEST_CASE (RunSmall, NEConvolutionLayerFixture< float >, framework::DatasetMode::PRECOMMIT, combine(combine(datasets::SmallConvolutionLayerDataset(), framework::dataset::make("ReshapeWeights",{true, false})), framework::dataset::make("DataType", DataType::F32)))
FIXTURE_DATA_TEST_CASE (RunLarge, NEConvolutionLayerFixture< float >, framework::DatasetMode::NIGHTLY, combine(combine(datasets::LargeConvolutionLayerDataset(), framework::dataset::make("ReshapeWeights",{true, false})), framework::dataset::make("DataType", DataType::F32)))
FIXTURE_DATA_TEST_CASE (RunSmall, NEConvolutionLayerFixedPointFixture< int8_t >, framework::DatasetMode::PRECOMMIT, combine(combine(combine(datasets::SmallConvolutionLayerDataset(), framework::dataset::make("ReshapeWeights",{true, false})), framework::dataset::make("DataType", DataType::QS8)), framework::dataset::make("FractionalBits", 4, 7)))
FIXTURE_DATA_TEST_CASE (RunLarge, NEConvolutionLayerFixedPointFixture< int8_t >, framework::DatasetMode::NIGHTLY, combine(combine(combine(datasets::LargeConvolutionLayerDataset(), framework::dataset::make("ReshapeWeights",{true, false})), framework::dataset::make("DataType", DataType::QS8)), framework::dataset::make("FractionalBits", 4, 7)))
FIXTURE_DATA_TEST_CASE (RunSmall, NEConvolutionLayerFixedPointFixture< int16_t >, framework::DatasetMode::PRECOMMIT, combine(combine(combine(datasets::SmallConvolutionLayerDataset(), framework::dataset::make("ReshapeWeights",{true, false})), framework::dataset::make("DataType", DataType::QS16)), framework::dataset::make("FractionalBits", 1, 14)))
FIXTURE_DATA_TEST_CASE (RunLarge, NEConvolutionLayerFixedPointFixture< int16_t >, framework::DatasetMode::NIGHTLY, combine(combine(combine(datasets::LargeConvolutionLayerDataset(), framework::dataset::make("ReshapeWeights",{true, false})), framework::dataset::make("DataType", DataType::QS16)), framework::dataset::make("FractionalBits", 1, 14)))
FIXTURE_DATA_TEST_CASE (RunSmall, NEDepthConcatenateLayerFixture< half >, framework::DatasetMode::PRECOMMIT, combine(datasets::Small2DShapes(), framework::dataset::make("DataType", DataType::F16)))
FIXTURE_DATA_TEST_CASE (RunLarge, NEDepthConcatenateLayerFixture< half >, framework::DatasetMode::NIGHTLY, combine(datasets::DepthConcatenateShapes(), framework::dataset::make("DataType", DataType::F16)))
FIXTURE_DATA_TEST_CASE (RunSmall, NEDepthConcatenateLayerFixture< float >, framework::DatasetMode::PRECOMMIT, combine(datasets::Small2DShapes(), framework::dataset::make("DataType", DataType::F32)))
FIXTURE_DATA_TEST_CASE (RunLarge, NEDepthConcatenateLayerFixture< float >, framework::DatasetMode::NIGHTLY, combine(datasets::DepthConcatenateShapes(), framework::dataset::make("DataType", DataType::F32)))
FIXTURE_DATA_TEST_CASE (RunSmall, NEDepthConcatenateLayerFixture< int8_t >, framework::DatasetMode::PRECOMMIT, combine(datasets::Small2DShapes(), framework::dataset::make("DataType", DataType::QS8)))
FIXTURE_DATA_TEST_CASE (RunLarge, NEDepthConcatenateLayerFixture< int8_t >, framework::DatasetMode::NIGHTLY, combine(datasets::DepthConcatenateShapes(), framework::dataset::make("DataType", DataType::QS8)))
FIXTURE_DATA_TEST_CASE (RunSmall, NEDepthConcatenateLayerFixture< int16_t >, framework::DatasetMode::PRECOMMIT, combine(datasets::Small2DShapes(), framework::dataset::make("DataType", DataType::QS16)))
FIXTURE_DATA_TEST_CASE (RunLarge, NEDepthConcatenateLayerFixture< int16_t >, framework::DatasetMode::NIGHTLY, combine(datasets::DepthConcatenateShapes(), framework::dataset::make("DataType", DataType::QS16)))
FIXTURE_DATA_TEST_CASE (RunSmall, NEDepthConvertToU16Fixture< uint8_t >, framework::DatasetMode::PRECOMMIT, combine(combine(combine(datasets::SmallShapes(), DepthConvertU8toU16Dataset), framework::dataset::make("ConvertPolicy",{ConvertPolicy::SATURATE, ConvertPolicy::WRAP})), DepthConvertShiftDataset))
FIXTURE_DATA_TEST_CASE (RunLarge, NEDepthConvertToU16Fixture< uint8_t >, framework::DatasetMode::NIGHTLY, combine(combine(combine(datasets::LargeShapes(), DepthConvertU8toU16Dataset), framework::dataset::make("ConvertPolicy",{ConvertPolicy::SATURATE, ConvertPolicy::WRAP})), DepthConvertShiftDataset))
FIXTURE_DATA_TEST_CASE (RunSmall, NEDepthConvertToS16Fixture< uint8_t >, framework::DatasetMode::PRECOMMIT, combine(combine(combine(datasets::SmallShapes(), DepthConvertU8toS16Dataset), framework::dataset::make("ConvertPolicy",{ConvertPolicy::SATURATE, ConvertPolicy::WRAP})), DepthConvertShiftDataset))
FIXTURE_DATA_TEST_CASE (RunLarge, NEDepthConvertToS16Fixture< uint8_t >, framework::DatasetMode::NIGHTLY, combine(combine(combine(datasets::LargeShapes(), DepthConvertU8toS16Dataset), framework::dataset::make("ConvertPolicy",{ConvertPolicy::SATURATE, ConvertPolicy::WRAP})), DepthConvertShiftDataset))
FIXTURE_DATA_TEST_CASE (RunSmall, NEDepthConvertToS32Fixture< uint8_t >, framework::DatasetMode::PRECOMMIT, combine(combine(combine(datasets::SmallShapes(), DepthConvertU8toS32Dataset), framework::dataset::make("ConvertPolicy",{ConvertPolicy::SATURATE, ConvertPolicy::WRAP})), DepthConvertShiftDataset))
FIXTURE_DATA_TEST_CASE (RunLarge, NEDepthConvertToS32Fixture< uint8_t >, framework::DatasetMode::NIGHTLY, combine(combine(combine(datasets::LargeShapes(), DepthConvertU8toS32Dataset), framework::dataset::make("ConvertPolicy",{ConvertPolicy::SATURATE, ConvertPolicy::WRAP})), DepthConvertShiftDataset))
FIXTURE_DATA_TEST_CASE (RunSmall, NEDepthConvertToU8Fixture< uint16_t >, framework::DatasetMode::PRECOMMIT, combine(combine(combine(datasets::SmallShapes(), DepthConvertU16toU8Dataset), framework::dataset::make("ConvertPolicy",{ConvertPolicy::SATURATE, ConvertPolicy::WRAP})), DepthConvertShiftDataset))
FIXTURE_DATA_TEST_CASE (RunLarge, NEDepthConvertToU8Fixture< uint16_t >, framework::DatasetMode::NIGHTLY, combine(combine(combine(datasets::LargeShapes(), DepthConvertU16toU8Dataset), framework::dataset::make("ConvertPolicy",{ConvertPolicy::SATURATE, ConvertPolicy::WRAP})), DepthConvertShiftDataset))
FIXTURE_DATA_TEST_CASE (RunSmall, NEDepthConvertToU32Fixture< uint16_t >, framework::DatasetMode::PRECOMMIT, combine(combine(combine(datasets::SmallShapes(), DepthConvertU16toU32Dataset), framework::dataset::make("ConvertPolicy",{ConvertPolicy::SATURATE, ConvertPolicy::WRAP})), DepthConvertShiftDataset))
FIXTURE_DATA_TEST_CASE (RunLarge, NEDepthConvertToU32Fixture< uint16_t >, framework::DatasetMode::NIGHTLY, combine(combine(combine(datasets::LargeShapes(), DepthConvertU16toU32Dataset), framework::dataset::make("ConvertPolicy",{ConvertPolicy::SATURATE, ConvertPolicy::WRAP})), DepthConvertShiftDataset))
FIXTURE_DATA_TEST_CASE (RunSmall, NEDepthConvertToU8Fixture< int16_t >, framework::DatasetMode::PRECOMMIT, combine(combine(combine(datasets::SmallShapes(), DepthConvertS16toU8Dataset), framework::dataset::make("ConvertPolicy",{ConvertPolicy::SATURATE, ConvertPolicy::WRAP})), DepthConvertShiftDataset))
FIXTURE_DATA_TEST_CASE (RunLarge, NEDepthConvertToU8Fixture< int16_t >, framework::DatasetMode::NIGHTLY, combine(combine(combine(datasets::LargeShapes(), DepthConvertS16toU8Dataset), framework::dataset::make("ConvertPolicy",{ConvertPolicy::SATURATE, ConvertPolicy::WRAP})), DepthConvertShiftDataset))
FIXTURE_DATA_TEST_CASE (RunSmall, NEDepthConvertToS32Fixture< int16_t >, framework::DatasetMode::PRECOMMIT, combine(combine(combine(datasets::SmallShapes(), DepthConvertS16toS32Dataset), framework::dataset::make("ConvertPolicy",{ConvertPolicy::SATURATE, ConvertPolicy::WRAP})), DepthConvertShiftDataset))
FIXTURE_DATA_TEST_CASE (RunLarge, NEDepthConvertToS32Fixture< int16_t >, framework::DatasetMode::NIGHTLY, combine(combine(combine(datasets::LargeShapes(), DepthConvertS16toS32Dataset), framework::dataset::make("ConvertPolicy",{ConvertPolicy::SATURATE, ConvertPolicy::WRAP})), DepthConvertShiftDataset))
FIXTURE_DATA_TEST_CASE (RunSmallQS8, NEDepthConvertToFP32FixedPointFixture< int8_t >, framework::DatasetMode::PRECOMMIT, combine(combine(combine(datasets::SmallShapes(), DepthConvertQS8toFP32Dataset), framework::dataset::make("ConvertPolicy",{ConvertPolicy::SATURATE, ConvertPolicy::WRAP})), DepthConvertFixedPointQuantizedDataset))
FIXTURE_DATA_TEST_CASE (RunSmallQS16, NEDepthConvertToFP32FixedPointFixture< int16_t >, framework::DatasetMode::PRECOMMIT, combine(combine(combine(datasets::SmallShapes(), DepthConvertQS16toFP32Dataset), framework::dataset::make("ConvertPolicy",{ConvertPolicy::SATURATE, ConvertPolicy::WRAP})), DepthConvertFixedPointQuantizedDataset))
FIXTURE_DATA_TEST_CASE (RunLargeQS8, NEDepthConvertToFP32FixedPointFixture< int8_t >, framework::DatasetMode::NIGHTLY, combine(combine(combine(datasets::LargeShapes(), DepthConvertQS8toFP32Dataset), framework::dataset::make("ConvertPolicy",{ConvertPolicy::SATURATE, ConvertPolicy::WRAP})), DepthConvertFixedPointQuantizedDataset))
FIXTURE_DATA_TEST_CASE (RunLargeQS16, NEDepthConvertToFP32FixedPointFixture< int16_t >, framework::DatasetMode::NIGHTLY, combine(combine(combine(datasets::LargeShapes(), DepthConvertQS16toFP32Dataset), framework::dataset::make("ConvertPolicy",{ConvertPolicy::SATURATE, ConvertPolicy::WRAP})), DepthConvertFixedPointQuantizedDataset))
FIXTURE_DATA_TEST_CASE (RunSmallQS8, NEDepthConvertToQS8FixedPointFixture< float >, framework::DatasetMode::PRECOMMIT, combine(combine(combine(datasets::SmallShapes(), DepthConvertFP32toQS8Dataset), framework::dataset::make("ConvertPolicy",{ConvertPolicy::SATURATE, ConvertPolicy::WRAP})), DepthConvertFixedPointQuantizedDataset))
FIXTURE_DATA_TEST_CASE (RunSmallQS16, NEDepthConvertToQS16FixedPointFixture< float >, framework::DatasetMode::PRECOMMIT, combine(combine(combine(datasets::SmallShapes(), DepthConvertFP32toQS16Dataset), framework::dataset::make("ConvertPolicy",{ConvertPolicy::SATURATE, ConvertPolicy::WRAP})), DepthConvertFixedPointQuantizedDataset))
FIXTURE_DATA_TEST_CASE (RunLargeQS8, NEDepthConvertToQS8FixedPointFixture< float >, framework::DatasetMode::NIGHTLY, combine(combine(combine(datasets::LargeShapes(), DepthConvertFP32toQS8Dataset), framework::dataset::make("ConvertPolicy",{ConvertPolicy::SATURATE, ConvertPolicy::WRAP})), DepthConvertFixedPointQuantizedDataset))
FIXTURE_DATA_TEST_CASE (RunLargeQS16, NEDepthConvertToQS16FixedPointFixture< float >, framework::DatasetMode::NIGHTLY, combine(combine(combine(datasets::LargeShapes(), DepthConvertFP32toQS16Dataset), framework::dataset::make("ConvertPolicy",{ConvertPolicy::SATURATE, ConvertPolicy::WRAP})), DepthConvertFixedPointQuantizedDataset))
FIXTURE_DATA_TEST_CASE (RunSmall, NEDequantizationLayerFixture< uint8_t >, framework::DatasetMode::PRECOMMIT, combine(concat(datasets::Small3DShapes(), datasets::Small4DShapes()), framework::dataset::make("DataType", DataType::U8)))
FIXTURE_DATA_TEST_CASE (RunLarge, NEDequantizationLayerFixture< uint8_t >, framework::DatasetMode::NIGHTLY, combine(concat(datasets::Large3DShapes(), datasets::Large4DShapes()), framework::dataset::make("DataType", DataType::U8)))
FIXTURE_DATA_TEST_CASE (Run, NEDirectConvolutionLayerFixture< half >, framework::DatasetMode::ALL, combine(data_f32, framework::dataset::make("DataType", DataType::F16)))
FIXTURE_DATA_TEST_CASE (Run, NEDirectConvolutionLayerFixture< float >, framework::DatasetMode::ALL, combine(data_f32, framework::dataset::make("DataType", DataType::F32)))
FIXTURE_DATA_TEST_CASE (Run, NEDirectConvolutionLayerFixedPointFixture< int8_t >, framework::DatasetMode::ALL, combine(combine(data_qs8, framework::dataset::make("DataType", DataType::QS8)), framework::dataset::make("FractionalBits", 4, 7)))
FIXTURE_DATA_TEST_CASE (Run, NEDirectConvolutionLayerFixedPointFixture< int16_t >, framework::DatasetMode::ALL, combine(combine(data_qs16, framework::dataset::make("DataType", DataType::QS16)), framework::dataset::make("FractionalBits", 4, 14)))
FIXTURE_DATA_TEST_CASE (RunSmall, NEFixedPointFixture< int8_t >, framework::DatasetMode::ALL, combine(combine(combine(datasets::Small1DShape(), framework::dataset::make("DataType", DataType::QS8)), framework::dataset::make("FixedPointOp", FixedPointOp::EXP)), framework::dataset::make("FractionalBits", 1, 7)))
FIXTURE_DATA_TEST_CASE (RunSmall, NEFixedPointFixture< int8_t >, framework::DatasetMode::ALL, combine(combine(combine(datasets::Small1DShape(), framework::dataset::make("DataType", DataType::QS8)), framework::dataset::make("FixedPointOp", FixedPointOp::INV_SQRT)), framework::dataset::make("FractionalBits", 1, 6)))
FIXTURE_DATA_TEST_CASE (RunSmall, NEFixedPointFixture< int8_t >, framework::DatasetMode::ALL, combine(combine(combine(datasets::Small1DShape(), framework::dataset::make("DataType", DataType::QS8)), framework::dataset::make("FixedPointOp", FixedPointOp::LOG)), framework::dataset::make("FractionalBits", 3, 6)))
FIXTURE_DATA_TEST_CASE (RunSmall, NEFixedPointFixture< int8_t >, framework::DatasetMode::ALL, combine(combine(combine(datasets::Small1DShape(), framework::dataset::make("DataType", DataType::QS8)), framework::dataset::make("FixedPointOp", FixedPointOp::RECIPROCAL)), framework::dataset::make("FractionalBits", 1, 6)))
FIXTURE_DATA_TEST_CASE (RunSmall, NEFixedPointFixture< int16_t >, framework::DatasetMode::ALL, combine(combine(combine(datasets::Small1DShape(), framework::dataset::make("DataType", DataType::QS16)), framework::dataset::make("FixedPointOp", FixedPointOp::EXP)), framework::dataset::make("FractionalBits", 1, 15)))
FIXTURE_DATA_TEST_CASE (RunSmall, NEFixedPointFixture< int16_t >, framework::DatasetMode::ALL, combine(combine(combine(framework::dataset::make("Shape", TensorShape(8192U)), framework::dataset::make("DataType", DataType::QS16)), framework::dataset::make("FixedPointOp", FixedPointOp::INV_SQRT)), framework::dataset::make("FractionalBits", 1, 14)))
FIXTURE_DATA_TEST_CASE (RunSmall, NEFixedPointFixture< int16_t >, framework::DatasetMode::ALL, combine(combine(combine(datasets::Small1DShape(), framework::dataset::make("DataType", DataType::QS16)), framework::dataset::make("FixedPointOp", FixedPointOp::LOG)), framework::dataset::make("FractionalBits", 4, 14)))
FIXTURE_DATA_TEST_CASE (RunSmall, NEFixedPointFixture< int16_t >, framework::DatasetMode::ALL, combine(combine(combine(datasets::Small1DShape(), framework::dataset::make("DataType", DataType::QS16)), framework::dataset::make("FixedPointOp", FixedPointOp::RECIPROCAL)), framework::dataset::make("FractionalBits", 1, 14)))
FIXTURE_DATA_TEST_CASE (RunSmall, NEFlattenLayerFixture< float >, framework::DatasetMode::ALL, combine(framework::dataset::concat(datasets::Small3DShapes(), datasets::Small4DShapes()), framework::dataset::make("DataType", DataType::F32)))
FIXTURE_DATA_TEST_CASE (RunLarge, NEFlattenLayerFixture< float >, framework::DatasetMode::NIGHTLY, combine(framework::dataset::concat(datasets::Large3DShapes(), datasets::Large4DShapes()), framework::dataset::make("DataType", DataType::F32)))
FIXTURE_DATA_TEST_CASE (RunSmall, NEFlattenLayerFixture< half >, framework::DatasetMode::ALL, combine(framework::dataset::concat(datasets::Small3DShapes(), datasets::Small4DShapes()), framework::dataset::make("DataType", DataType::F16)))
FIXTURE_DATA_TEST_CASE (RunLarge, NEFlattenLayerFixture< half >, framework::DatasetMode::NIGHTLY, combine(framework::dataset::concat(datasets::Large3DShapes(), datasets::Large4DShapes()), framework::dataset::make("DataType", DataType::F16)))
FIXTURE_DATA_TEST_CASE (RunSmall, NEFlattenLayerFixture< int8_t >, framework::DatasetMode::ALL, combine(framework::dataset::concat(datasets::Small3DShapes(), datasets::Small4DShapes()), framework::dataset::make("DataType", DataType::QS8)))
FIXTURE_DATA_TEST_CASE (RunLarge, NEFlattenLayerFixture< int8_t >, framework::DatasetMode::NIGHTLY, combine(framework::dataset::concat(datasets::Large3DShapes(), datasets::Large4DShapes()), framework::dataset::make("DataType", DataType::QS8)))
FIXTURE_DATA_TEST_CASE (RunSmall, NEFlattenLayerFixture< int16_t >, framework::DatasetMode::ALL, combine(framework::dataset::concat(datasets::Small3DShapes(), datasets::Small4DShapes()), framework::dataset::make("DataType", DataType::QS16)))
FIXTURE_DATA_TEST_CASE (RunLarge, NEFlattenLayerFixture< int16_t >, framework::DatasetMode::NIGHTLY, combine(framework::dataset::concat(datasets::Large3DShapes(), datasets::Large4DShapes()), framework::dataset::make("DataType", DataType::QS16)))
FIXTURE_DATA_TEST_CASE (RunSmall, NEFloorFixture< float >, framework::DatasetMode::PRECOMMIT, combine(datasets::SmallShapes(), framework::dataset::make("DataType", DataType::F32)))
FIXTURE_DATA_TEST_CASE (RunLarge, NEFloorFixture< float >, framework::DatasetMode::NIGHTLY, combine(datasets::LargeShapes(), framework::dataset::make("DataType", DataType::F32)))
FIXTURE_DATA_TEST_CASE (RunSmall, NEFullyConnectedLayerFixture< half >, framework::DatasetMode::PRECOMMIT, combine(combine(datasets::SmallFullyConnectedLayerDataset(), FullyConnectedParameters), framework::dataset::make("DataType", DataType::F16)))
FIXTURE_DATA_TEST_CASE (RunLarge, NEFullyConnectedLayerFixture< half >, framework::DatasetMode::NIGHTLY, combine(combine(datasets::LargeFullyConnectedLayerDataset(), FullyConnectedParameters), framework::dataset::make("DataType", DataType::F16)))
FIXTURE_DATA_TEST_CASE (RunSmall, NEFullyConnectedLayerFixture< float >, framework::DatasetMode::PRECOMMIT, combine(combine(datasets::SmallFullyConnectedLayerDataset(), FullyConnectedParameters), framework::dataset::make("DataType", DataType::F32)))
FIXTURE_DATA_TEST_CASE (RunLarge, NEFullyConnectedLayerFixture< float >, framework::DatasetMode::NIGHTLY, combine(combine(datasets::LargeFullyConnectedLayerDataset(), FullyConnectedParameters), framework::dataset::make("DataType", DataType::F32)))
FIXTURE_DATA_TEST_CASE (RunSmall, NEFullyConnectedLayerFixedPointFixture< int8_t >, framework::DatasetMode::PRECOMMIT, combine(combine(combine(datasets::SmallFullyConnectedLayerDataset(), FullyConnectedParameters), framework::dataset::make("DataType", DataType::QS8)), framework::dataset::make("FractionalBits", 1, 6)))
FIXTURE_DATA_TEST_CASE (RunLarge, NEFullyConnectedLayerFixedPointFixture< int8_t >, framework::DatasetMode::NIGHTLY, combine(combine(combine(datasets::LargeFullyConnectedLayerDataset(), FullyConnectedParameters), framework::dataset::make("DataType", DataType::QS8)), framework::dataset::make("FractionalBits", 1, 6)))
FIXTURE_DATA_TEST_CASE (RunSmall, NEFullyConnectedLayerFixedPointFixture< int16_t >, framework::DatasetMode::PRECOMMIT, combine(combine(combine(datasets::SmallFullyConnectedLayerDataset(), FullyConnectedParameters), framework::dataset::make("DataType", DataType::QS16)), framework::dataset::make("FractionalBits", 1, 14)))
FIXTURE_DATA_TEST_CASE (RunLarge, NEFullyConnectedLayerFixedPointFixture< int16_t >, framework::DatasetMode::NIGHTLY, combine(combine(combine(datasets::LargeFullyConnectedLayerDataset(), FullyConnectedParameters), framework::dataset::make("DataType", DataType::QS16)), framework::dataset::make("FractionalBits", 1, 14)))
FIXTURE_DATA_TEST_CASE (RunSmall, NEGaussian3x3Fixture< uint8_t >, framework::DatasetMode::PRECOMMIT, combine(combine(datasets::SmallShapes(), framework::dataset::make("DataType", DataType::U8)), datasets::BorderModes()))
FIXTURE_DATA_TEST_CASE (RunLarge, NEGaussian3x3Fixture< uint8_t >, framework::DatasetMode::NIGHTLY, combine(combine(datasets::LargeShapes(), framework::dataset::make("DataType", DataType::U8)), datasets::BorderModes()))
FIXTURE_DATA_TEST_CASE (RunSmall, NEGaussian5x5Fixture< uint8_t >, framework::DatasetMode::PRECOMMIT, combine(combine(datasets::SmallShapes(), framework::dataset::make("DataType", DataType::U8)), datasets::BorderModes()))
FIXTURE_DATA_TEST_CASE (RunLarge, NEGaussian5x5Fixture< uint8_t >, framework::DatasetMode::NIGHTLY, combine(combine(datasets::LargeShapes(), framework::dataset::make("DataType", DataType::U8)), datasets::BorderModes()))
FIXTURE_DATA_TEST_CASE (RunSmall, NEGEMMFixture< half >, framework::DatasetMode::PRECOMMIT, combine(datasets::SmallGEMMDataset(), framework::dataset::make("DataType", DataType::F16)))
FIXTURE_DATA_TEST_CASE (RunLarge, NEGEMMFixture< half >, framework::DatasetMode::NIGHTLY, combine(datasets::LargeGEMMDataset(), framework::dataset::make("DataType", DataType::F16)))
FIXTURE_DATA_TEST_CASE (RunSmall, NEGEMMFixture< float >, framework::DatasetMode::PRECOMMIT, combine(datasets::SmallGEMMDataset(), framework::dataset::make("DataType", DataType::F32)))
FIXTURE_DATA_TEST_CASE (RunLarge, NEGEMMFixture< float >, framework::DatasetMode::NIGHTLY, combine(datasets::LargeGEMMDataset(), framework::dataset::make("DataType", DataType::F32)))
FIXTURE_DATA_TEST_CASE (RunSmall, NEGEMMFixedPointFixture< int8_t >, framework::DatasetMode::PRECOMMIT, combine(combine(datasets::SmallGEMMDataset(), framework::dataset::make("DataType", DataType::QS8)), framework::dataset::make("FractionalBits", 1, 7)))
FIXTURE_DATA_TEST_CASE (RunLarge, NEGEMMFixedPointFixture< int8_t >, framework::DatasetMode::NIGHTLY, combine(combine(datasets::LargeGEMMDataset(), framework::dataset::make("DataType", DataType::QS8)), framework::dataset::make("FractionalBits", 1, 7)))
FIXTURE_DATA_TEST_CASE (RunSmall, NEGEMMFixedPointFixture< int16_t >, framework::DatasetMode::PRECOMMIT, combine(combine(datasets::SmallGEMMDataset(), framework::dataset::make("DataType", DataType::QS16)), framework::dataset::make("FractionalBits", 1, 14)))
FIXTURE_DATA_TEST_CASE (RunLarge, NEGEMMFixedPointFixture< int16_t >, framework::DatasetMode::NIGHTLY, combine(combine(datasets::LargeGEMMDataset(), framework::dataset::make("DataType", DataType::QS16)), framework::dataset::make("FractionalBits", 1, 14)))
FIXTURE_DATA_TEST_CASE (RunSmall, NEGEMMLowpOffsetFixture, framework::DatasetMode::PRECOMMIT, data_mnk *data_offsets)
FIXTURE_DATA_TEST_CASE (RunGlobalPooling, NEGlobalPoolingLayerFixture< float >, framework::DatasetMode::ALL, combine(GlobalPoolingLayerDataset, framework::dataset::make("DataType", DataType::F32)))
FIXTURE_DATA_TEST_CASE (RunSmall, NEHarrisCornersFixture< uint8_t >, framework::DatasetMode::PRECOMMIT, combine(combine(datasets::Small2DShapes(), data), framework::dataset::make("Format", Format::U8)))
FIXTURE_DATA_TEST_CASE (RunLarge, NEHarrisCornersFixture< uint8_t >, framework::DatasetMode::NIGHTLY, combine(combine(datasets::Large2DShapes(), data), framework::dataset::make("Format", Format::U8)))
FIXTURE_DATA_TEST_CASE (RunSmall, NEIntegralImageFixture< uint8_t >, framework::DatasetMode::PRECOMMIT, combine(datasets::SmallShapes(), framework::dataset::make("DataType", DataType::U8)))
FIXTURE_DATA_TEST_CASE (RunLarge, NEIntegralImageFixture< uint8_t >, framework::DatasetMode::NIGHTLY, combine(datasets::LargeShapes(), framework::dataset::make("DataType", DataType::U8)))
FIXTURE_DATA_TEST_CASE (RunSmall, NEL2NormalizeFixture< float >, framework::DatasetMode::PRECOMMIT, combine(combine(combine(datasets::SmallShapes(), framework::dataset::make("DataType", DataType::F32)), framework::dataset::make("Axis",{0})), framework::dataset::make("Epsilon",{1e-12})))
FIXTURE_DATA_TEST_CASE (RunLarge, NEL2NormalizeFixture< float >, framework::DatasetMode::NIGHTLY, combine(combine(combine(datasets::LargeShapes(), framework::dataset::make("DataType", DataType::F32)), framework::dataset::make("Axis",{0})), framework::dataset::make("Epsilon",{1e-12})))
FIXTURE_DATA_TEST_CASE (RunSmall, NEMeanStdDevFixture< uint8_t >, framework::DatasetMode::PRECOMMIT, combine(datasets::Small2DShapes(), framework::dataset::make("DataType", DataType::U8)))
FIXTURE_DATA_TEST_CASE (RunLarge, NEMeanStdDevFixture< uint8_t >, framework::DatasetMode::NIGHTLY, combine(datasets::Large2DShapes(), framework::dataset::make("DataType", DataType::U8)))
void validate_configuration (const Tensor &src, TensorShape shape)
FIXTURE_DATA_TEST_CASE (RunSmall, NEMinMaxLocationFixture< uint8_t >, framework::DatasetMode::PRECOMMIT, combine(datasets::Small2DShapes(), framework::dataset::make("DataType", DataType::U8)))
FIXTURE_DATA_TEST_CASE (RunLarge, NEMinMaxLocationFixture< uint8_t >, framework::DatasetMode::NIGHTLY, combine(datasets::Large2DShapes(), framework::dataset::make("DataType", DataType::U8)))
FIXTURE_DATA_TEST_CASE (RunSmall, NEMinMaxLocationFixture< int16_t >, framework::DatasetMode::PRECOMMIT, combine(datasets::Small2DShapes(), framework::dataset::make("DataType", DataType::S16)))
FIXTURE_DATA_TEST_CASE (RunLarge, NEMinMaxLocationFixture< int16_t >, framework::DatasetMode::NIGHTLY, combine(datasets::Large2DShapes(), framework::dataset::make("DataType", DataType::S16)))
FIXTURE_DATA_TEST_CASE (RunSmall, NEMinMaxLocationFixture< float >, framework::DatasetMode::PRECOMMIT, combine(datasets::Small2DShapes(), framework::dataset::make("DataType", DataType::F32)))
FIXTURE_DATA_TEST_CASE (RunLarge, NEMinMaxLocationFixture< float >, framework::DatasetMode::NIGHTLY, combine(datasets::Large2DShapes(), framework::dataset::make("DataType", DataType::F32)))
FIXTURE_DATA_TEST_CASE (RunSmall, NENonLinearFilterFixture< uint8_t >, framework::DatasetMode::PRECOMMIT, combine(combine(combine(combine(combine(datasets::SmallShapes(), datasets::NonLinearFilterFunctions()), framework::dataset::make("MaskSize",{3U, 5U})), datasets::MatrixPatterns()), datasets::BorderModes()), framework::dataset::make("DataType", DataType::U8)))
FIXTURE_DATA_TEST_CASE (RunLarge, NENonLinearFilterFixture< uint8_t >, framework::DatasetMode::NIGHTLY, combine(combine(combine(combine(combine(datasets::LargeShapes(), datasets::NonLinearFilterFunctions()), framework::dataset::make("MaskSize",{3U, 5U})), datasets::MatrixPatterns()), datasets::BorderModes()), framework::dataset::make("DataType", DataType::U8)))
FIXTURE_DATA_TEST_CASE (RunSmall, NENormalizationLayerFixture< half >, framework::DatasetMode::PRECOMMIT, combine(NormalizationDataset, framework::dataset::make("DataType", DataType::F16)))
FIXTURE_DATA_TEST_CASE (RunLarge, NENormalizationLayerFixture< half >, framework::DatasetMode::NIGHTLY, combine(NormalizationDataset, framework::dataset::make("DataType", DataType::F16)))
FIXTURE_DATA_TEST_CASE (RunSmall, NENormalizationLayerFixture< float >, framework::DatasetMode::PRECOMMIT, combine(NormalizationDataset, framework::dataset::make("DataType", DataType::F32)))
FIXTURE_DATA_TEST_CASE (RunLarge, NENormalizationLayerFixture< float >, framework::DatasetMode::NIGHTLY, combine(NormalizationDataset, framework::dataset::make("DataType", DataType::F32)))
FIXTURE_DATA_TEST_CASE (RunSmall, NENormalizationLayerFixedPointFixture< int8_t >, framework::DatasetMode::PRECOMMIT, combine(combine(NormalizationDataset, framework::dataset::make("DataType", DataType::QS8)), framework::dataset::make("FractionalBits", 1, 6)))
FIXTURE_DATA_TEST_CASE (RunLarge, NENormalizationLayerFixedPointFixture< int8_t >, framework::DatasetMode::NIGHTLY, combine(combine(NormalizationDataset, framework::dataset::make("DataType", DataType::QS8)), framework::dataset::make("FractionalBits", 1, 6)))
FIXTURE_DATA_TEST_CASE (RunSmall, NENormalizationLayerFixedPointFixture< int16_t >, framework::DatasetMode::PRECOMMIT, combine(combine(NormalizationDataset, framework::dataset::make("DataType", DataType::QS16)), framework::dataset::make("FractionalBits", 1, 14)))
FIXTURE_DATA_TEST_CASE (RunLarge, NENormalizationLayerFixedPointFixture< int16_t >, framework::DatasetMode::NIGHTLY, combine(combine(NormalizationDataset, framework::dataset::make("DataType", DataType::QS16)), framework::dataset::make("FractionalBits", 1, 14)))
FIXTURE_DATA_TEST_CASE (RunSmall, NEPoolingLayerFixture< float >, framework::DatasetMode::ALL, combine(datasets::SmallShapes(), combine(PoolingLayerDatasetFP, framework::dataset::make("DataType", DataType::F32))))
FIXTURE_DATA_TEST_CASE (RunLarge, NEPoolingLayerFixture< float >, framework::DatasetMode::NIGHTLY, combine(datasets::LargeShapes(), combine(PoolingLayerDatasetFP, framework::dataset::make("DataType", DataType::F32))))
FIXTURE_DATA_TEST_CASE (RunSmall, NEPoolingLayerFixture< half >, framework::DatasetMode::ALL, combine(datasets::SmallShapes(), combine(PoolingLayerDatasetFP, framework::dataset::make("DataType", DataType::F16))))
FIXTURE_DATA_TEST_CASE (RunLarge, NEPoolingLayerFixture< half >, framework::DatasetMode::NIGHTLY, combine(datasets::LargeShapes(), combine(PoolingLayerDatasetFP, framework::dataset::make("DataType", DataType::F16))))
FIXTURE_DATA_TEST_CASE (RunSmall, NEPoolingLayerFixedPointFixture< int8_t >, framework::DatasetMode::ALL, combine(combine(datasets::SmallShapes(), combine(PoolingLayerDatasetQS, framework::dataset::make("DataType", DataType::QS8))), framework::dataset::make("FractionalBits", 1, 5)))
FIXTURE_DATA_TEST_CASE (RunLarge, NEPoolingLayerFixedPointFixture< int8_t >, framework::DatasetMode::NIGHTLY, combine(combine(datasets::LargeShapes(), combine(PoolingLayerDatasetQS, framework::dataset::make("DataType", DataType::QS8))), framework::dataset::make("FractionalBits", 1, 5)))
FIXTURE_DATA_TEST_CASE (RunSmall, NEPoolingLayerFixedPointFixture< int16_t >, framework::DatasetMode::ALL, combine(combine(datasets::SmallShapes(), combine(PoolingLayerDatasetQS, framework::dataset::make("DataType", DataType::QS16))), framework::dataset::make("FractionalBits", 1, 13)))
FIXTURE_DATA_TEST_CASE (RunLarge, NEPoolingLayerFixedPointFixture< int16_t >, framework::DatasetMode::NIGHTLY, combine(combine(datasets::LargeShapes(), combine(PoolingLayerDatasetQS, framework::dataset::make("DataType", DataType::QS16))), framework::dataset::make("FractionalBits", 1, 13)))
FIXTURE_DATA_TEST_CASE (RunSmall, NEQuantizationLayerFixture< float >, framework::DatasetMode::PRECOMMIT, combine(concat(datasets::Small3DShapes(), datasets::Small4DShapes()), framework::dataset::make("DataType", DataType::F32)))
FIXTURE_DATA_TEST_CASE (RunLarge, NEQuantizationLayerFixture< float >, framework::DatasetMode::NIGHTLY, combine(concat(datasets::Large3DShapes(), datasets::Large4DShapes()), framework::dataset::make("DataType", DataType::F32)))
FIXTURE_DATA_TEST_CASE (RunSmall, NEReductionOperationFixture< float >, framework::DatasetMode::PRECOMMIT, combine(combine(combine(datasets::SmallShapes(), framework::dataset::make("DataType", DataType::F32)), framework::dataset::make("Axis",{0})), datasets::ReductionOperations()))
FIXTURE_DATA_TEST_CASE (RunLarge, NEReductionOperationFixture< float >, framework::DatasetMode::NIGHTLY, combine(combine(combine(datasets::LargeShapes(), framework::dataset::make("DataType", DataType::F32)), framework::dataset::make("Axis",{0})), datasets::ReductionOperations()))
FIXTURE_DATA_TEST_CASE (RunSmall, NEReshapeLayerFixture< float >, framework::DatasetMode::ALL, combine(datasets::SmallReshapeLayerDataset(), framework::dataset::make("DataType", DataType::F32)))
FIXTURE_DATA_TEST_CASE (RunSmall, NEReshapeLayerFixture< int8_t >, framework::DatasetMode::ALL, combine(datasets::SmallReshapeLayerDataset(), framework::dataset::make("DataType", DataType::S8)))
FIXTURE_DATA_TEST_CASE (RunSmall, NEReshapeLayerFixture< int16_t >, framework::DatasetMode::ALL, combine(datasets::SmallReshapeLayerDataset(), framework::dataset::make("DataType", DataType::S16)))
DATA_TEST_CASE (Configuration, framework::DatasetMode::ALL, combine(combine(combine(concat(datasets::SmallShapes(), datasets::LargeShapes()), ScaleDataTypes), framework::dataset::make("InterpolationPolicy",{InterpolationPolicy::NEAREST_NEIGHBOR, InterpolationPolicy::BILINEAR})), datasets::BorderModes()), shape, data_type, policy, border_mode)
FIXTURE_DATA_TEST_CASE (RunSmall, NEScaleFixture< float >, framework::DatasetMode::ALL, combine(combine(combine(datasets::SmallShapes(), framework::dataset::make("DataType", DataType::F32)), framework::dataset::make("InterpolationPolicy",{InterpolationPolicy::NEAREST_NEIGHBOR, InterpolationPolicy::BILINEAR})), datasets::BorderModes()))
FIXTURE_DATA_TEST_CASE (RunLarge, NEScaleFixture< float >, framework::DatasetMode::NIGHTLY, combine(combine(combine(datasets::LargeShapes(), framework::dataset::make("DataType", DataType::F32)), framework::dataset::make("InterpolationPolicy",{InterpolationPolicy::NEAREST_NEIGHBOR, InterpolationPolicy::BILINEAR})), datasets::BorderModes()))
FIXTURE_DATA_TEST_CASE (RunSmall, NEScaleFixture< uint8_t >, framework::DatasetMode::ALL, combine(combine(combine(datasets::SmallShapes(), framework::dataset::make("DataType", DataType::U8)), framework::dataset::make("InterpolationPolicy",{InterpolationPolicy::NEAREST_NEIGHBOR, InterpolationPolicy::BILINEAR})), datasets::BorderModes()))
FIXTURE_DATA_TEST_CASE (RunLarge, NEScaleFixture< uint8_t >, framework::DatasetMode::NIGHTLY, combine(combine(combine(datasets::LargeShapes(), framework::dataset::make("DataType", DataType::U8)), framework::dataset::make("InterpolationPolicy",{InterpolationPolicy::NEAREST_NEIGHBOR, InterpolationPolicy::BILINEAR})), datasets::BorderModes()))
FIXTURE_DATA_TEST_CASE (RunSmall, NEScaleFixture< int16_t >, framework::DatasetMode::ALL, combine(combine(combine(datasets::SmallShapes(), framework::dataset::make("DataType", DataType::S16)), framework::dataset::make("InterpolationPolicy",{InterpolationPolicy::NEAREST_NEIGHBOR, InterpolationPolicy::BILINEAR})), datasets::BorderModes()))
FIXTURE_DATA_TEST_CASE (RunLarge, NEScaleFixture< int16_t >, framework::DatasetMode::NIGHTLY, combine(combine(combine(datasets::LargeShapes(), framework::dataset::make("DataType", DataType::S16)), framework::dataset::make("InterpolationPolicy",{InterpolationPolicy::NEAREST_NEIGHBOR, InterpolationPolicy::BILINEAR})), datasets::BorderModes()))
FIXTURE_DATA_TEST_CASE (RunSmall, NESobel3x3Fixture, framework::DatasetMode::PRECOMMIT, combine(combine(datasets::Small2DShapes(), datasets::BorderModes()), framework::dataset::make("Format", Format::U8)))
FIXTURE_DATA_TEST_CASE (RunLarge, NESobel3x3Fixture, framework::DatasetMode::NIGHTLY, combine(combine(datasets::Large2DShapes(), datasets::BorderModes()), framework::dataset::make("Format", Format::U8)))
FIXTURE_DATA_TEST_CASE (RunSmall, NESobel5x5Fixture, framework::DatasetMode::PRECOMMIT, combine(combine(datasets::Small2DShapes(), datasets::BorderModes()), framework::dataset::make("Format", Format::U8)))
FIXTURE_DATA_TEST_CASE (RunLarge, NESobel5x5Fixture, framework::DatasetMode::NIGHTLY, combine(combine(datasets::Large2DShapes(), datasets::BorderModes()), framework::dataset::make("Format", Format::U8)))
FIXTURE_DATA_TEST_CASE (RunSmall, NESobel7x7Fixture, framework::DatasetMode::PRECOMMIT, combine(combine(datasets::Small2DShapes(), datasets::BorderModes()), framework::dataset::make("Format", Format::U8)))
FIXTURE_DATA_TEST_CASE (RunLarge, NESobel7x7Fixture, framework::DatasetMode::NIGHTLY, combine(combine(datasets::Large2DShapes(), datasets::BorderModes()), framework::dataset::make("Format", Format::U8)))
FIXTURE_DATA_TEST_CASE (RunSmall, NESoftmaxLayerFixture< half >, framework::DatasetMode::PRECOMMIT, combine(datasets::SmallShapes(), framework::dataset::make("DataType", DataType::F16)))
FIXTURE_DATA_TEST_CASE (RunLarge, NESoftmaxLayerFixture< half >, framework::DatasetMode::NIGHTLY, combine(datasets::LargeShapes(), framework::dataset::make("DataType", DataType::F16)))
FIXTURE_DATA_TEST_CASE (RunSmall, NESoftmaxLayerFixture< float >, framework::DatasetMode::PRECOMMIT, combine(datasets::SmallShapes(), framework::dataset::make("DataType", DataType::F32)))
FIXTURE_DATA_TEST_CASE (RunLarge, NESoftmaxLayerFixture< float >, framework::DatasetMode::NIGHTLY, combine(datasets::LargeShapes(), framework::dataset::make("DataType", DataType::F32)))
FIXTURE_DATA_TEST_CASE (RunSmall, NESoftmaxLayerFixedPointFixture< int8_t >, framework::DatasetMode::PRECOMMIT, combine(combine(datasets::SmallShapes(), framework::dataset::make("DataType", DataType::QS8)), framework::dataset::make("FractionalBits", 1, 6)))
FIXTURE_DATA_TEST_CASE (RunLarge, NESoftmaxLayerFixedPointFixture< int8_t >, framework::DatasetMode::NIGHTLY, combine(combine(datasets::LargeShapes(), framework::dataset::make("DataType", DataType::QS8)), framework::dataset::make("FractionalBits", 1, 6)))
FIXTURE_DATA_TEST_CASE (RunSmall, NESoftmaxLayerFixedPointFixture< int16_t >, framework::DatasetMode::PRECOMMIT, combine(combine(datasets::SmallShapes(), framework::dataset::make("DataType", DataType::QS16)), framework::dataset::make("FractionalBits", 1, 14)))
FIXTURE_DATA_TEST_CASE (RunLarge, NESoftmaxLayerFixedPointFixture< int16_t >, framework::DatasetMode::NIGHTLY, combine(combine(datasets::LargeShapes(), framework::dataset::make("DataType", DataType::QS16)), framework::dataset::make("FractionalBits", 1, 14)))
FIXTURE_DATA_TEST_CASE (RunSmallU8, NETableLookupFixture< uint8_t >, framework::DatasetMode::PRECOMMIT, combine(datasets::SmallShapes(), framework::dataset::make("DataType", DataType::U8)))
FIXTURE_DATA_TEST_CASE (RunLargeU8, NETableLookupFixture< uint8_t >, framework::DatasetMode::NIGHTLY, combine(datasets::LargeShapes(), framework::dataset::make("DataType", DataType::U8)))
FIXTURE_DATA_TEST_CASE (RunSmallS16, NETableLookupFixture< int16_t >, framework::DatasetMode::PRECOMMIT, combine(datasets::SmallShapes(), framework::dataset::make("DataType", DataType::S16)))
FIXTURE_DATA_TEST_CASE (RunLargeS16, NETableLookupFixture< int16_t >, framework::DatasetMode::NIGHTLY, combine(datasets::LargeShapes(), framework::dataset::make("DataType", DataType::S16)))
FIXTURE_DATA_TEST_CASE (RunSmall, ThresholdFixture< uint8_t >, framework::DatasetMode::PRECOMMIT, combine(combine(datasets::SmallShapes(), datasets::MixedThresholdDataset()), framework::dataset::make("DataType", DataType::U8)))
FIXTURE_DATA_TEST_CASE (RunLarge, ThresholdFixture< uint8_t >, framework::DatasetMode::NIGHTLY, combine(combine(datasets::LargeShapes(), datasets::MixedThresholdDataset()), framework::dataset::make("DataType", DataType::U8)))
FIXTURE_DATA_TEST_CASE (RunSmall, NEWarpAffineFixture< uint8_t >, framework::DatasetMode::PRECOMMIT, combine(combine(combine(datasets::SmallShapes(), framework::dataset::make("DataType", DataType::U8)), framework::dataset::make("InterpolationPolicy",{InterpolationPolicy::NEAREST_NEIGHBOR, InterpolationPolicy::BILINEAR})), datasets::BorderModes()))
DISABLED_FIXTURE_DATA_TEST_CASE (RunLarge, NEWarpAffineFixture< uint8_t >, framework::DatasetMode::NIGHTLY, combine(combine(combine(datasets::LargeShapes(), framework::dataset::make("DataType", DataType::U8)), framework::dataset::make("InterpolationPolicy",{InterpolationPolicy::NEAREST_NEIGHBOR, InterpolationPolicy::BILINEAR})), datasets::BorderModes()))
FIXTURE_DATA_TEST_CASE (RunSmall, NEWarpPerspectiveFixture< uint8_t >, framework::DatasetMode::PRECOMMIT, combine(combine(combine(datasets::SmallShapes(), framework::dataset::make("DataType", DataType::U8)), framework::dataset::make("InterpolationPolicy",{InterpolationPolicy::NEAREST_NEIGHBOR, InterpolationPolicy::BILINEAR})), datasets::BorderModes()))
FIXTURE_DATA_TEST_CASE (RunLarge, NEWarpPerspectiveFixture< uint8_t >, framework::DatasetMode::NIGHTLY, combine(combine(combine(datasets::LargeShapes(), framework::dataset::make("DataType", DataType::U8)), framework::dataset::make("InterpolationPolicy",{InterpolationPolicy::NEAREST_NEIGHBOR, InterpolationPolicy::BILINEAR})), datasets::BorderModes()))
DATA_TEST_CASE (FixedPointQS8Inputs, framework::DatasetMode::ALL, combine(FuncNamesDataset, framework::dataset::make("FractionalBits", 1, 7)), func_name, frac_bits)
DATA_TEST_CASE (FixedPointQS8Outputs, framework::DatasetMode::ALL, zip(combine(FuncNamesDataset, framework::dataset::make("FractionalBits", 1, 7)), framework::dataset::make("ExpectedFailures",{0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 7, 8, 13, 2, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 5, 33, 96})), func_name, frac_bits, expected_failures)
DATA_TEST_CASE (AutoPadding, framework::DatasetMode::ALL, zip(zip(zip(framework::dataset::make("TensorShape",{TensorShape{}, TensorShape{10U}, TensorShape{10U, 10U}, TensorShape{10U, 10U, 10U}, TensorShape{10U, 10U, 10U, 10U}, TensorShape{10U, 10U, 10U, 10U, 10U}, TensorShape{10U, 10U, 10U, 10U, 10U, 10U}}), framework::dataset::make("PaddingSize",{PaddingSize{0, 0, 0, 0}, PaddingSize{0, 36, 0, 4}, PaddingSize{4, 36, 4, 4}, PaddingSize{4, 36, 4, 4}, PaddingSize{4, 36, 4, 4}, PaddingSize{4, 36, 4, 4}, PaddingSize{4, 36, 4, 4}})), framework::dataset::make("Strides",{Strides{}, Strides{1U, 50U}, Strides{1U, 50U}, Strides{1U, 50U, 900U}, Strides{1U, 50U, 900U, 9000U}, Strides{1U, 50U, 900U, 9000U, 90000U}, Strides{1U, 50U, 900U, 9000U, 90000U, 900000U}})), framework::dataset::make("Offset",{0U, 4U, 204U, 204U, 204U, 204U, 204U})), shape, auto_padding, strides, offset)
DATA_TEST_CASE (Construction, framework::DatasetMode::ALL, zip(zip(framework::dataset::make("TensorShape",{TensorShape{}, TensorShape{1U}, TensorShape{2U}, TensorShape{2U, 3U}, TensorShape{2U, 3U, 5U}, TensorShape{2U, 3U, 5U, 7U}, TensorShape{2U, 3U, 5U, 7U, 11U}, TensorShape{2U, 3U, 5U, 7U, 11U, 13U}}), framework::dataset::make("NumDimensions",{0U, 1U, 1U, 2U, 3U, 4U, 5U, 6U})), framework::dataset::make("TotalSize",{0U, 1U, 2U, 6U, 30U, 210U, 2310U, 30030U})), shape, num_dimensions, total_size)
shape set (dimension, 10)
ARM_COMPUTE_EXPECT (shape.num_dimensions()==dimension+1, framework::LogLevel::ERRORS)
void validate (const arm_compute::ValidRegion &region, const arm_compute::ValidRegion &reference)
Validate valid regions.
void validate (const arm_compute::PaddingSize &padding, const arm_compute::PaddingSize &reference)
Validate padding.
void validate (const IAccessor &tensor, const void *reference_value)
Validate tensors against constant value.
void validate (const IAccessor &tensor, BorderSize border_size, const BorderMode &border_mode, const void *border_value)
Validate border against a constant value.
void validate (std::vector< unsigned int > classified_labels, std::vector< unsigned int > expected_labels)
Validate classified labels against expected ones.
template<typename T >
inline::std::ostream & operator<< (::std::ostream &os, const AbsoluteTolerance< T > &tolerance)
Print AbsoluteTolerance type.
template<typename T >
inline::std::ostream & operator<< (::std::ostream &os, const RelativeTolerance< T > &tolerance)
Print RelativeTolerance type.
template<typename T >
bool compare_dimensions (const Dimensions< T > &dimensions1, const Dimensions< T > &dimensions2)
template<typename T , typename U = AbsoluteTolerance<T>>
void validate (const IAccessor &tensor, const SimpleTensor< T > &reference, U tolerance_value=U(), float tolerance_number=0.f)
Validate tensors.
template<typename T , typename U = AbsoluteTolerance<T>>
void validate (const IAccessor &tensor, const SimpleTensor< T > &reference, const ValidRegion &valid_region, U tolerance_value=U(), float tolerance_number=0.f)
Validate tensors with valid region.
template<typename T , typename U = AbsoluteTolerance<T>>
void validate (const IAccessor &tensor, const SimpleTensor< T > &reference, const SimpleTensor< T > &valid_mask, U tolerance_value=U(), float tolerance_number=0.f)
Validate tensors with valid mask.
template<typename T , typename U = AbsoluteTolerance<T>>
bool validate (T target, T reference, U tolerance=AbsoluteTolerance< T >())
Validate float value.
template<typename T , typename U , typename V = AbsoluteTolerance<float>>
void validate_keypoints (T target_first, T target_last, U reference_first, U reference_last, V tolerance=AbsoluteTolerance< float >())
Validate key points.
template<typename T , typename U , typename V >
std::pair< int64_t, int64_t > compare_keypoints (T first1, T last1, U first2, U last2, V tolerance)
Check which keypoints from [first1, last1) are missing in [first2, last2)
template<typename T , typename U >
void validate_min_max_loc (const MinMaxLocationValues< T > &target, const MinMaxLocationValues< U > &reference)
Variables
const auto PaddingSizesDataset
const auto BorderSizesDataset = framework::dataset::make("BorderSize", 0, 6)
shape
data_type
Typedef Documentation
using CLActivationLayerFixedPointFixture = ActivationValidationFixedPointFixture<CLTensor, CLAccessor, CLActivationLayer, T>
Definition at line 197 of file ActivationLayer.cpp.
using CLActivationLayerFixture = ActivationValidationFixture<CLTensor, CLAccessor, CLActivationLayer, T>
Definition at line 160 of file ActivationLayer.cpp.
using CLArithmeticAdditionFixedPointFixture = ArithmeticAdditionValidationFixedPointFixture<CLTensor, CLAccessor, CLArithmeticAddition, T>
Definition at line 140 of file ArithmeticAddition.cpp.
using CLArithmeticAdditionFixture = ArithmeticAdditionValidationFixture<CLTensor, CLAccessor, CLArithmeticAddition, T>
Definition at line 65 of file ArithmeticAddition.cpp.
using CLArithmeticSubtractionFixedPointFixture = ArithmeticSubtractionValidationFixedPointFixture<CLTensor, CLAccessor, CLArithmeticSubtraction, T>
Definition at line 141 of file ArithmeticSubtraction.cpp.
using CLArithmeticSubtractionFixture = ArithmeticSubtractionValidationFixture<CLTensor, CLAccessor, CLArithmeticSubtraction, T>
Definition at line 66 of file ArithmeticSubtraction.cpp.
using CLBatchNormalizationLayerFixedPointFixture = BatchNormalizationLayerValidationFixedPointFixture<CLTensor, CLAccessor, CLBatchNormalizationLayer, T>
Definition at line 103 of file BatchNormalizationLayer.cpp.
using CLBatchNormalizationLayerFixture = BatchNormalizationLayerValidationFixture<CLTensor, CLAccessor, CLBatchNormalizationLayer, T>
Definition at line 56 of file BatchNormalizationLayer.cpp.
using CLBitwiseAndFixture = BitwiseAndValidationFixture<CLTensor, CLAccessor, CLBitwiseAnd, T>
Definition at line 75 of file BitwiseAnd.cpp.
using CLBitwiseNotFixture = BitwiseNotValidationFixture<CLTensor, CLAccessor, CLBitwiseNot, T>
Definition at line 71 of file BitwiseNot.cpp.
using CLBitwiseOrFixture = BitwiseOrValidationFixture<CLTensor, CLAccessor, CLBitwiseOr, T>
Definition at line 75 of file BitwiseOr.cpp.
using CLBitwiseXorFixture = BitwiseXorValidationFixture<CLTensor, CLAccessor, CLBitwiseXor, T>
Definition at line 75 of file BitwiseXor.cpp.
using CLBox3x3Fixture = Box3x3ValidationFixture<CLTensor, CLAccessor, CLBox3x3, T>
Definition at line 89 of file Box3x3.cpp.
using CLConvolutionLayerFixedPointFixture = ConvolutionValidationFixedPointFixture<CLTensor, CLAccessor, CLConvolutionLayer, T>
Definition at line 141 of file ConvolutionLayer.cpp.
using CLConvolutionLayerFixture = ConvolutionValidationFixture<CLTensor, CLAccessor, CLConvolutionLayer, T>
Definition at line 98 of file ConvolutionLayer.cpp.
using CLDepthConcatenateLayerFixture = DepthConcatenateValidationFixture<CLTensor, ICLTensor, CLAccessor, CLDepthConcatenate, T>
Definition at line 46 of file DepthConcatenateLayer.cpp.
using CLDepthConvertToFP32FixedPointFixture = DepthConvertValidationFractionalBitsFixture<CLTensor, CLAccessor, CLDepthConvert, T, float>
Definition at line 75 of file DepthConvert.cpp.
using CLDepthConvertToQS16FixedPointFixture = DepthConvertValidationFractionalBitsFixture<CLTensor, CLAccessor, CLDepthConvert, T, int16_t>
Definition at line 79 of file DepthConvert.cpp.
using CLDepthConvertToQS8FixedPointFixture = DepthConvertValidationFractionalBitsFixture<CLTensor, CLAccessor, CLDepthConvert, T, int8_t>
Definition at line 77 of file DepthConvert.cpp.
using CLDepthConvertToS16Fixture = DepthConvertValidationFixture<CLTensor, CLAccessor, CLDepthConvert, T, int16_t>
Definition at line 67 of file DepthConvert.cpp.
using CLDepthConvertToS32Fixture = DepthConvertValidationFixture<CLTensor, CLAccessor, CLDepthConvert, T, int32_t>
Definition at line 69 of file DepthConvert.cpp.
using CLDepthConvertToU16Fixture = DepthConvertValidationFixture<CLTensor, CLAccessor, CLDepthConvert, T, uint16_t>
Definition at line 65 of file DepthConvert.cpp.
using CLDepthConvertToU32Fixture = DepthConvertValidationFixture<CLTensor, CLAccessor, CLDepthConvert, T, uint32_t>
Definition at line 73 of file DepthConvert.cpp.
using CLDepthConvertToU8Fixture = DepthConvertValidationFixture<CLTensor, CLAccessor, CLDepthConvert, T, uint8_t>
Definition at line 71 of file DepthConvert.cpp.
using CLDepthwiseConvolutionFixture = DepthwiseConvolutionValidationFixture<CLTensor, CLAccessor, CLDepthwiseConvolution, T>
Definition at line 52 of file DepthwiseConvolution.cpp.
using CLDepthwiseConvolutionFixture3x3 = DepthwiseConvolutionValidationFixture<CLTensor, CLAccessor, CLDepthwiseConvolution3x3, T>
Initial value:
{
    validate(CLAccessor(_target), _reference, tolerance_f32)
Definition at line 66 of file DepthwiseConvolution.cpp.
using CLDepthwiseSeparableConvolutionLayerFixture = DepthwiseSeparableConvolutionValidationFixture<CLTensor, CLAccessor, CLDepthwiseSeparableConvolutionLayer, T>
Definition at line 55 of file DepthwiseSeparableConvolutionLayer.cpp.
using CLDequantizationLayerFixture = DequantizationValidationFixture<CLTensor, CLAccessor, CLDequantizationLayer, T>
Definition at line 96 of file DequantizationLayer.cpp.
using CLDirectConvolutionLayerFixedPointFixture = DirectConvolutionValidationFixedPointFixture<CLTensor, CLAccessor, CLDirectConvolutionLayer, T>
Definition at line 102 of file DirectConvolutionLayer.cpp.
using CLDirectConvolutionLayerFixture = DirectConvolutionValidationFixture<CLTensor, CLAccessor, CLDirectConvolutionLayer, T>
Definition at line 81 of file DirectConvolutionLayer.cpp.
using CLFixedPointFixture = FixedPointValidationFixture<CLTensor, CLAccessor, T>
Definition at line 56 of file FixedPoint_QS8.cpp.
using CLFlattenLayerFixture = FlattenLayerValidationFixture<CLTensor, CLAccessor, CLFlattenLayer, T>
Definition at line 47 of file Flatten.cpp.
using CLFloorFixture = FloorValidationFixture<CLTensor, CLAccessor, CLFloor, T>
Definition at line 47 of file Floor.cpp.
using CLFullyConnectedLayerFixedPointFixture = FullyConnectedLayerValidationFixedPointFixture<CLTensor, CLAccessor, CLFullyConnectedLayer, T, false>
Definition at line 144 of file FullyConnectedLayer.cpp.
using CLFullyConnectedLayerFixture = FullyConnectedLayerValidationFixture<CLTensor, CLAccessor, CLFullyConnectedLayer, T, false>
Definition at line 107 of file FullyConnectedLayer.cpp.
using CLGaussian3x3Fixture = Gaussian3x3ValidationFixture<CLTensor, CLAccessor, CLGaussian3x3, T>
Definition at line 89 of file Gaussian3x3.cpp.
using CLGaussian5x5Fixture = Gaussian5x5ValidationFixture<CLTensor, CLAccessor, CLGaussian5x5, T>
Definition at line 89 of file Gaussian5x5.cpp.
using CLGEMMFixedPointFixture = GEMMValidationFixedPointFixture<CLTensor, CLAccessor, CLGEMM, T>
Definition at line 119 of file GEMM.cpp.
using CLGEMMFixture = GEMMValidationFixture<CLTensor, CLAccessor, CLGEMM, T>
Definition at line 87 of file GEMM.cpp.
using CLGlobalPoolingLayerFixture = GlobalPoolingLayerValidationFixture<CLTensor, CLAccessor, CLPoolingLayer, T>
Definition at line 58 of file GlobalPoolingLayer.cpp.
using CLHarrisCornersFixture = HarrisCornersValidationFixture<CLTensor, CLAccessor, CLKeyPointArray, CLHarrisCorners, T>
Definition at line 102 of file HarrisCorners.cpp.
using CLIntegralImageFixture = IntegralImageValidationFixture<CLTensor, CLAccessor, CLIntegralImage, T>
Definition at line 65 of file IntegralImage.cpp.
using CLL2NormalizeFixture = L2NormalizeValidationFixture<CLTensor, CLAccessor, CLL2Normalize, T>
Definition at line 54 of file L2Normalize.cpp.
using CLMeanStdDevFixture = MeanStdDevValidationFixture<CLTensor, CLAccessor, CLMeanStdDev, T>
Definition at line 72 of file MeanStdDev.cpp.
using CLMinMaxLocationFixture = MinMaxLocationValidationFixture<CLTensor, CLAccessor, CLArray<Coordinates2D>, CLArrayAccessor<Coordinates2D>, CLMinMaxLocation, T>
Definition at line 43 of file MinMaxLocation.cpp.
using CLNonLinearFilterFixture = NonLinearFilterValidationFixture<CLTensor, CLAccessor, CLNonLinearFilter, T>
Definition at line 91 of file NonLinearFilter.cpp.
using CLNormalizationLayerFixedPointFixture = NormalizationValidationFixedPointFixture<CLTensor, CLAccessor, CLNormalizationLayer, T>
Definition at line 95 of file NormalizationLayer.cpp.
using CLNormalizationLayerFixture = NormalizationValidationFixture<CLTensor, CLAccessor, CLNormalizationLayer, T>
Definition at line 64 of file NormalizationLayer.cpp.
using CLPoolingLayerFixedPointFixture = PoolingLayerValidationFixedPointFixture<CLTensor, CLAccessor, CLPoolingLayer, T>
Definition at line 99 of file PoolingLayer.cpp.
using CLPoolingLayerFixture = PoolingLayerValidationFixture<CLTensor, CLAccessor, CLPoolingLayer, T>
Definition at line 64 of file PoolingLayer.cpp.
using CLQuantizationLayerFixture = QuantizationValidationFixture<CLTensor, CLAccessor, CLQuantizationLayer, T>
Definition at line 80 of file QuantizationLayer.cpp.
using CLReductionOperationFixture = ReductionOperationValidationFixture<CLTensor, CLAccessor, CLReductionOperation, T>
Definition at line 54 of file ReductionOperation.cpp.
using CLReshapeLayerFixture = ReshapeLayerValidationFixture<CLTensor, CLAccessor, CLReshapeLayer, T>
Definition at line 48 of file ReshapeLayer.cpp.
using CLScaleFixture = ScaleValidationFixture<CLTensor, CLAccessor, CLScale, T>
Definition at line 111 of file Scale.cpp.
using CLSobel3x3Fixture = SobelValidationFixture<CLTensor, CLAccessor, CLSobel3x3, uint8_t, int16_t>
Definition at line 50 of file Sobel.cpp.
using CLSobel5x5Fixture = SobelValidationFixture<CLTensor, CLAccessor, CLSobel5x5, uint8_t, int16_t>
Definition at line 127 of file Sobel.cpp.
using CLSobel7x7Fixture = SobelValidationFixture<CLTensor, CLAccessor, CLSobel7x7, uint8_t, int32_t>
Definition at line 203 of file Sobel.cpp.
using CLSoftmaxLayerFixedPointFixture = SoftmaxValidationFixedPointFixture<CLTensor, CLAccessor, CLSoftmaxLayer, T>
Definition at line 124 of file SoftmaxLayer.cpp.
using CLSoftmaxLayerFixture = SoftmaxValidationFixture<CLTensor, CLAccessor, CLSoftmaxLayer, T>
Definition at line 93 of file SoftmaxLayer.cpp.
using CLTableLookupFixture = TableLookupValidationFixture<CLTensor, CLAccessor, CLTableLookup, CLLutAccessor<T>, CLLut, T>
Definition at line 52 of file TableLookup.cpp.
using CLThresholdFixture = ThresholdValidationFixture<CLTensor, CLAccessor, CLThreshold, T>
Definition at line 68 of file Threshold.cpp.
using CLWarpAffineFixture = WarpAffineValidationFixture<CLTensor, CLAccessor, CLWarpAffine, T>
Definition at line 99 of file WarpAffine.cpp.
using CLWarpPerspectiveFixture = WarpPerspectiveValidationFixture<CLTensor, CLAccessor, CLWarpPerspective, T>
Definition at line 101 of file WarpPerspective.cpp.
using NEActivationLayerFixedPointFixture = ActivationValidationFixedPointFixture<Tensor, Accessor, NEActivationLayer, T>
Definition at line 180 of file ActivationLayer.cpp.
using NEActivationLayerFixture = ActivationValidationFixture<Tensor, Accessor, NEActivationLayer, T>
Definition at line 141 of file ActivationLayer.cpp.
using NEArithmeticAdditionFixedPointFixture = ArithmeticAdditionValidationFixedPointFixture<Tensor, Accessor, NEArithmeticAddition, T>
Definition at line 142 of file ArithmeticAddition.cpp.
using NEArithmeticAdditionFixture = ArithmeticAdditionValidationFixture<Tensor, Accessor, NEArithmeticAddition, T>
Definition at line 67 of file ArithmeticAddition.cpp.
using NEArithmeticSubtractionFixedPointFixture = ArithmeticSubtractionValidationFixedPointFixture<Tensor, Accessor, NEArithmeticSubtraction, T>
Definition at line 143 of file ArithmeticSubtraction.cpp.
using NEArithmeticSubtractionFixture = ArithmeticSubtractionValidationFixture<Tensor, Accessor, NEArithmeticSubtraction, T>
Definition at line 68 of file ArithmeticSubtraction.cpp.
using NEBatchNormalizationLayerFixedPointFixture = BatchNormalizationLayerValidationFixedPointFixture<Tensor, Accessor, NEBatchNormalizationLayer, T>
Definition at line 105 of file BatchNormalizationLayer.cpp.
using NEBatchNormalizationLayerFixture = BatchNormalizationLayerValidationFixture<Tensor, Accessor, NEBatchNormalizationLayer, T>
Definition at line 58 of file BatchNormalizationLayer.cpp.
using NEBitwiseAndFixture = BitwiseAndValidationFixture<Tensor, Accessor, NEBitwiseAnd, T>
Definition at line 75 of file BitwiseAnd.cpp.
using NEBitwiseNotFixture = BitwiseNotValidationFixture<Tensor, Accessor, NEBitwiseNot, T>
Definition at line 71 of file BitwiseNot.cpp.
using NEBitwiseOrFixture = BitwiseOrValidationFixture<Tensor, Accessor, NEBitwiseOr, T>
Definition at line 75 of file BitwiseOr.cpp.
using NEBitwiseXorFixture = BitwiseXorValidationFixture<Tensor, Accessor, NEBitwiseXor, T>
Definition at line 75 of file BitwiseXor.cpp.
using NEBox3x3Fixture = Box3x3ValidationFixture<Tensor, Accessor, NEBox3x3, T>
Definition at line 89 of file Box3x3.cpp.
using NEConvolutionLayerFixedPointFixture = ConvolutionValidationFixedPointFixture<Tensor, Accessor, NEConvolutionLayer, T>
Definition at line 142 of file ConvolutionLayer.cpp.
using NEConvolutionLayerFixture = ConvolutionValidationFixture<Tensor, Accessor, NEConvolutionLayer, T>
Definition at line 101 of file ConvolutionLayer.cpp.
using NEDepthConcatenateLayerFixture = DepthConcatenateValidationFixture<Tensor, ITensor, Accessor, NEDepthConcatenate, T>
Definition at line 46 of file DepthConcatenateLayer.cpp.
using NEDepthConvertToFP32FixedPointFixture = DepthConvertValidationFractionalBitsFixture<Tensor, Accessor, NEDepthConvert, T, float>
Definition at line 75 of file DepthConvert.cpp.
using NEDepthConvertToQS16FixedPointFixture = DepthConvertValidationFractionalBitsFixture<Tensor, Accessor, NEDepthConvert, T, int16_t>
Definition at line 79 of file DepthConvert.cpp.
using NEDepthConvertToQS8FixedPointFixture = DepthConvertValidationFractionalBitsFixture<Tensor, Accessor, NEDepthConvert, T, int8_t>
Definition at line 77 of file DepthConvert.cpp.
using NEDepthConvertToS16Fixture = DepthConvertValidationFixture<Tensor, Accessor, NEDepthConvert, T, int16_t>
Definition at line 67 of file DepthConvert.cpp.
using NEDepthConvertToS32Fixture = DepthConvertValidationFixture<Tensor, Accessor, NEDepthConvert, T, int32_t>
Definition at line 69 of file DepthConvert.cpp.
using NEDepthConvertToU16Fixture = DepthConvertValidationFixture<Tensor, Accessor, NEDepthConvert, T, uint16_t>
Definition at line 65 of file DepthConvert.cpp.
using NEDepthConvertToU32Fixture = DepthConvertValidationFixture<Tensor, Accessor, NEDepthConvert, T, uint32_t>
Definition at line 73 of file DepthConvert.cpp.
using NEDepthConvertToU8Fixture = DepthConvertValidationFixture<Tensor, Accessor, NEDepthConvert, T, uint8_t>
Definition at line 71 of file DepthConvert.cpp.
using NEDequantizationLayerFixture = DequantizationValidationFixture<Tensor, Accessor, NEDequantizationLayer, T>
Definition at line 100 of file DequantizationLayer.cpp.
using NEDirectConvolutionLayerFixedPointFixture = DirectConvolutionValidationFixedPointFixture<Tensor, Accessor, NEDirectConvolutionLayer, T>
Definition at line 118 of file DirectConvolutionLayer.cpp.
using NEDirectConvolutionLayerFixture = DirectConvolutionValidationFixture<Tensor, Accessor, NEDirectConvolutionLayer, T>
Definition at line 95 of file DirectConvolutionLayer.cpp.
using NEFixedPointFixture = FixedPointValidationFixture<Tensor, Accessor, T>
Definition at line 59 of file FixedPoint.cpp.
using NEFlattenLayerFixture = FlattenLayerValidationFixture<Tensor, Accessor, NEFlattenLayer, T>
Definition at line 47 of file Flatten.cpp.
using NEFloorFixture = FloorValidationFixture<Tensor, Accessor, NEFloor, T>
Definition at line 47 of file Floor.cpp.
using NEFullyConnectedLayerFixedPointFixture = FullyConnectedLayerValidationFixedPointFixture<Tensor, Accessor, NEFullyConnectedLayer, T, true>
Definition at line 158 of file FullyConnectedLayer.cpp.
using NEFullyConnectedLayerFixture = FullyConnectedLayerValidationFixture<Tensor, Accessor, NEFullyConnectedLayer, T, true>
Definition at line 119 of file FullyConnectedLayer.cpp.
using NEGaussian3x3Fixture = Gaussian3x3ValidationFixture<Tensor, Accessor, NEGaussian3x3, T>
Definition at line 89 of file Gaussian3x3.cpp.
using NEGaussian5x5Fixture = Gaussian5x5ValidationFixture<Tensor, Accessor, NEGaussian5x5, T>
Definition at line 89 of file Gaussian5x5.cpp.
using NEGEMMFixedPointFixture = GEMMValidationFixedPointFixture<Tensor, Accessor, NEGEMM, T>
Definition at line 121 of file GEMM.cpp.
using NEGEMMFixture = GEMMValidationFixture<Tensor, Accessor, NEGEMM, T>
Definition at line 87 of file GEMM.cpp.
using NEGEMMLowpOffsetFixture = GEMMLowpOffsetValidationFixture<Tensor, Accessor, NEGEMMLowp>
Definition at line 56 of file GEMMLowp.cpp.
using NEGlobalPoolingLayerFixture = GlobalPoolingLayerValidationFixture<Tensor, Accessor, NEPoolingLayer, T>
Definition at line 57 of file GlobalPoolingLayer.cpp.
using NEHarrisCornersFixture = HarrisCornersValidationFixture<Tensor, Accessor, KeyPointArray, NEHarrisCorners, T>
Definition at line 103 of file HarrisCorners.cpp.
using NEIntegralImageFixture = IntegralImageValidationFixture<Tensor, Accessor, NEIntegralImage, T>
Definition at line 67 of file IntegralImage.cpp.
using NEL2NormalizeFixture = L2NormalizeValidationFixture<Tensor, Accessor, NEL2Normalize, T>
Definition at line 53 of file L2Normalize.cpp.
using NEMeanStdDevFixture = MeanStdDevValidationFixture<Tensor, Accessor, NEMeanStdDev, T>
Definition at line 68 of file MeanStdDev.cpp.
using NEMinMaxLocationFixture = MinMaxLocationValidationFixture<Tensor, Accessor, Array<Coordinates2D>, ArrayAccessor<Coordinates2D>, NEMinMaxLocation, T>
Definition at line 44 of file MinMaxLocation.cpp.
using NENonLinearFilterFixture = NonLinearFilterValidationFixture<Tensor, Accessor, NENonLinearFilter, T>
Definition at line 91 of file NonLinearFilter.cpp.
using NENormalizationLayerFixedPointFixture = NormalizationValidationFixedPointFixture<Tensor, Accessor, NENormalizationLayer, T>
Definition at line 97 of file NormalizationLayer.cpp.
using NENormalizationLayerFixture = NormalizationValidationFixture<Tensor, Accessor, NENormalizationLayer, T>
Definition at line 64 of file NormalizationLayer.cpp.
using NEPoolingLayerFixedPointFixture = PoolingLayerValidationFixedPointFixture<Tensor, Accessor, NEPoolingLayer, T>
Definition at line 103 of file PoolingLayer.cpp.
using NEPoolingLayerFixture = PoolingLayerValidationFixture<Tensor, Accessor, NEPoolingLayer, T>
Definition at line 66 of file PoolingLayer.cpp.
using NEQuantizationLayerFixture = QuantizationValidationFixture<Tensor, Accessor, NEQuantizationLayer, T>
Definition at line 82 of file QuantizationLayer.cpp.
using NEReductionOperationFixture = ReductionOperationValidationFixture<Tensor, Accessor, NEReductionOperation, T>
Definition at line 54 of file ReductionOperation.cpp.
using NEReshapeLayerFixture = ReshapeLayerValidationFixture<Tensor, Accessor, NEReshapeLayer, T>
Definition at line 48 of file ReshapeLayer.cpp.
using NEScaleFixture = ScaleValidationFixture<Tensor, Accessor, NEScale, T>
Definition at line 115 of file Scale.cpp.
using NESobel3x3Fixture = SobelValidationFixture<Tensor, Accessor, NESobel3x3, uint8_t, int16_t>
Definition at line 50 of file Sobel.cpp.
using NESobel5x5Fixture = SobelValidationFixture<Tensor, Accessor, NESobel5x5, uint8_t, int16_t>
Definition at line 127 of file Sobel.cpp.
using NESobel7x7Fixture = SobelValidationFixture<Tensor, Accessor, NESobel7x7, uint8_t, int32_t>
Definition at line 204 of file Sobel.cpp.
using NESoftmaxLayerFixedPointFixture = SoftmaxValidationFixedPointFixture<Tensor, Accessor, NESoftmaxLayer, T>
Definition at line 130 of file SoftmaxLayer.cpp.
using NESoftmaxLayerFixture = SoftmaxValidationFixture<Tensor, Accessor, NESoftmaxLayer, T>
Definition at line 97 of file SoftmaxLayer.cpp.
using NETableLookupFixture = TableLookupValidationFixture<Tensor, Accessor, NETableLookup, LutAccessor<T>, Lut, T>
Definition at line 51 of file TableLookup.cpp.
using NEWarpAffineFixture = WarpAffineValidationFixture<Tensor, Accessor, NEWarpAffine, T>
Definition at line 99 of file WarpAffine.cpp.
using NEWarpPerspectiveFixture = WarpPerspectiveValidationFixture<Tensor, Accessor, NEWarpPerspective, T>
Definition at line 102 of file WarpPerspective.cpp.
using ThresholdFixture = ThresholdValidationFixture<Tensor, Accessor, NEThreshold, T>
Definition at line 69 of file Threshold.cpp.
Function Documentation
void arm_compute::test::validation::apply_2d_spatial_filter (Coordinates coord, const SimpleTensor< T > & src, SimpleTensor< U > & dst, const TensorShape & filter_shape, const V * filter_itr, double scale, BorderMode border_mode, T constant_border_value = T(0))
Definition at line 81 of file Utils.h.
References arm_compute::test::coord2index(), Dimensions< T >::set(), SimpleTensor< T >::shape(), tensor_elem_at(), arm_compute::support::cpp11::trunc(), Dimensions< T >::x(), and Dimensions< T >::y().
Referenced by arm_compute::test::validation::reference::box3x3(), arm_compute::test::validation::reference::gaussian3x3(), arm_compute::test::validation::reference::gaussian5x5(), and arm_compute::test::validation::reference::sobel().
 {
     double    val = 0.;
     const int x   = coord.x();
     const int y   = coord.y();
     for(int j = y - static_cast<int>(filter_shape[1] / 2); j <= y + static_cast<int>(filter_shape[1] / 2); ++j)
     {
         for(int i = x - static_cast<int>(filter_shape[0] / 2); i <= x + static_cast<int>(filter_shape[0] / 2); ++i)
         {
             coord.set(0, i);
             coord.set(1, j);
             val += static_cast<double>(*filter_itr) * tensor_elem_at(src, coord, border_mode, constant_border_value);
             ++filter_itr;
         }
     }
     coord.set(0, x);
     coord.set(1, y);
     dst[coord2index(src.shape(), coord)] = saturate_cast<U>(support::cpp11::trunc(val * scale));
 }
ARM_COMPUTE_EXPECT (shape. num_dimensions() = =dimension+1, framework::LogLevel::ERRORS)
Referenced by DATA_TEST_CASE(), validate(), validate_configuration(), and validate_min_max_loc().
T bilinear_policy (const SimpleTensor< T > & in, Coordinates id, float xn, float yn, BorderMode border_mode, T constant_border_value)
Definition at line 36 of file Utils.cpp.
References tensor_elem_at().
Referenced by arm_compute::test::validation::reference::scale(), arm_compute::test::validation::reference::warp_affine(), and arm_compute::test::validation::reference::warp_perspective().
 {
     const int idx = std::floor(xn);
     const int idy = std::floor(yn);
     const float dx   = xn - idx;
     const float dy   = yn - idy;
     const float dx_1 = 1.0f - dx;
     const float dy_1 = 1.0f - dy;
     const T border_value = constant_border_value;
     id.set(0, idx);
     id.set(1, idy);
     const float tl = tensor_elem_at(in, id, border_mode, border_value);
     id.set(0, idx + 1);
     id.set(1, idy);
     const float tr = tensor_elem_at(in, id, border_mode, border_value);
     id.set(0, idx);
     id.set(1, idy + 1);
     const float bl = tensor_elem_at(in, id, border_mode, border_value);
     id.set(0, idx + 1);
     id.set(1, idy + 1);
     const float br = tensor_elem_at(in, id, border_mode, border_value);
     return static_cast<T>(tl * (dx_1 * dy_1) + tr * (dx * dy_1) + bl * (dx_1 * dy) + br * (dx * dy));
 }
template uint8_t arm_compute::test::validation::bilinear_policy (const SimpleTensor< uint8_t > & in, Coordinates id, float xn, float yn, BorderMode border_mode, uint8_t constant_border_value)
template int16_t arm_compute::test::validation::bilinear_policy (const SimpleTensor< int16_t > & in, Coordinates id, float xn, float yn, BorderMode border_mode, int16_t constant_border_value)
template half arm_compute::test::validation::bilinear_policy (const SimpleTensor< half > & in, Coordinates id, float xn, float yn, BorderMode border_mode, half constant_border_value)
template float arm_compute::test::validation::bilinear_policy (const SimpleTensor< float > & in, Coordinates id, float xn, float yn, BorderMode border_mode, float constant_border_value)
TensorShape calculate_depth_concatenate_shape (const std::vector< TensorShape > & input_shapes)
Calculate output tensor shape give a vector of input tensor to concatenate.
Parameters
[in] input_shapes Shapes of the tensors to concatenate across depth.
Returns
The shape of output concatenated tensor.
Definition at line 74 of file Helpers.cpp.
References ARM_COMPUTE_ERROR_ON, arm_compute::test::fixed_point_arithmetic::detail::max(), and shape.
Referenced by arm_compute::test::validation::reference::depthconcatenate_layer().
 {
     ARM_COMPUTE_ERROR_ON(input_shapes.empty());
     TensorShape out_shape = input_shapes[0];
     size_t max_x = 0;
     size_t max_y = 0;
     size_t depth = 0;
     for(const auto &shape : input_shapes)
     {
         max_x = std::max(shape.x(), max_x);
         max_y = std::max(shape.y(), max_y);
         depth += shape.z();
     }
     out_shape.set(0, max_x);
     out_shape.set(1, max_y);
     out_shape.set(2, depth);
     return out_shape;
 }
combine (concat(datasets::Small2DShapes(), datasets::Large2DShapes()) , framework::dataset:: make"DataType", DataType::S16)
combine (concat(datasets::Small2DShapes(), datasets::Large2DShapes()) , framework::dataset:: make"DataType", DataType::F32)
bool arm_compute::test::validation::compare_dimensions (const Dimensions< T > & dimensions1, const Dimensions< T > & dimensions2)
Definition at line 133 of file Validation.h.
References Dimensions< T >::num_dimensions().
Referenced by validate().
 {
     if(dimensions1.num_dimensions() != dimensions2.num_dimensions())
     {
         return false;
     }
     for(unsigned int i = 0; i < dimensions1.num_dimensions(); ++i)
     {
         if(dimensions1[i] != dimensions2[i])
         {
             return false;
         }
     }
     return true;
 }
std::pair<int64_t, int64_t> arm_compute::test::validation::compare_keypoints (T first1, T last1, U first2, U last2, V tolerance)
Check which keypoints from [first1, last1) are missing in [first2, last2)
Definition at line 381 of file Validation.h.
References ARM_COMPUTE_EXPECT_FAIL, ARM_COMPUTE_TEST_INFO, arm_compute::test::framework::DEBUG, KeyPoint::error, KeyPoint::orientation, KeyPoint::scale, KeyPoint::strength, KeyPoint::tracking_status, validate(), KeyPoint::x, and KeyPoint::y.
Referenced by validate_keypoints().
 {
     int64_t num_missing    = 0;
     int64_t num_mismatches = 0;
     while(first1 != last1)
     {
         const auto point = std::find_if(first2, last2, [&](KeyPoint point)
         {
             return point.x == first1->x && point.y == first1->y;
         });
         if(point == last2)
         {
             ++num_missing;
             ARM_COMPUTE_TEST_INFO("keypoint1 = " << *first1)
             ARM_COMPUTE_EXPECT_FAIL("Key point not found", framework::LogLevel::DEBUG);
         }
         else if(!validate(point->tracking_status, first1->tracking_status) || !validate(point->strength, first1->strength, tolerance) || !validate(point->scale, first1->scale)
                 || !validate(point->orientation, first1->orientation) || !validate(point->error, first1->error))
         {
             ++num_mismatches;
             ARM_COMPUTE_TEST_INFO("keypoint1 = " << *first1)
             ARM_COMPUTE_TEST_INFO("keypoint2 = " << *point)
             ARM_COMPUTE_EXPECT_FAIL("Mismatching keypoint", framework::LogLevel::DEBUG);
         }
         ++first1;
     }
     return std::make_pair(num_missing, num_mismatches);
 }
arm_compute::test::validation::DATA_TEST_CASE (Construction , framework::DatasetMode::ALL , zip(zip(framework::dataset::make("TensorShape",{TensorShape{},TensorShape{1U},TensorShape{2U},TensorShape{2U, 3U},TensorShape{2U, 3U, 5U},TensorShape{2U, 3U, 5U, 7U},TensorShape{2U, 3U, 5U, 7U, 11U},TensorShape{2U, 3U, 5U, 7U, 11U, 13U}}),framework::dataset::make("NumDimensions",{0U, 1U, 1U, 2U, 3U, 4U, 5U, 6U})),framework::dataset::make("TotalSize",{0U, 1U, 2U, 6U, 30U, 210U, 2310U, 30030U})) , shape , num_dimensions , total_size)
Definition at line 39 of file TensorShape.cpp.
References arm_compute::U.
{
                TensorShape{},
                TensorShape{ 1U },
                TensorShape{ 2U },
                TensorShape{ 2U, 3U },
                TensorShape{ 2U, 3U, 5U },
                TensorShape{ 2U, 3U, 5U, 7U },
                TensorShape{ 2U, 3U, 5U, 7U, 11U },
                TensorShape{ 2U, 3U, 5U, 7U, 11U, 13U }}),
                framework::dataset::make("NumDimensions", { 0U, 1U, 1U, 2U, 3U, 4U, 5U, 6U })),
                framework::dataset::make("TotalSize", { 0U, 1U, 2U, 6U, 30U, 210U, 2310U, 30030U })),
                shape, num_dimensions, total_size)
 {
     ARM_COMPUTE_EXPECT(shape.num_dimensions() == num_dimensions, framework::LogLevel::ERRORS);
     ARM_COMPUTE_EXPECT(shape.total_size() == total_size, framework::LogLevel::ERRORS);
 }
DATA_TEST_CASE (Configuration , framework::DatasetMode::ALL , combine(combine(concat(datasets::SmallShapes(), datasets::LargeShapes()), datasets::MixedThresholdDataset()),framework::dataset::make("DataType", DataType::U8)) , shape , threshold , false_value , true_value , type , upper , data_type)
Definition at line 42 of file Threshold.cpp.
References ARM_COMPUTE_EXPECT(), CLThreshold::configure(), data_type, arm_compute::test::framework::ERRORS, CLTensor::info(), TensorInfo::is_resizable(), TensorInfo::padding(), padding, shape, arm_compute::test::shape_to_valid_region(), and validate().
 {
     // Create tensors
     CLTensor src = create_tensor<CLTensor>(shape, data_type);
     CLTensor dst = create_tensor<CLTensor>(shape, data_type);
     ARM_COMPUTE_EXPECT(src.info()->is_resizable(), framework::LogLevel::ERRORS);
     ARM_COMPUTE_EXPECT(dst.info()->is_resizable(), framework::LogLevel::ERRORS);
     // Create and configure function
     CLThreshold thrsh;
     thrsh.configure(&src, &dst, threshold, false_value, true_value, type, upper);
     // Validate valid region
     const ValidRegion valid_region = shape_to_valid_region(shape);
     validate(dst.info()->valid_region(), valid_region);
     // Validate padding
     const PaddingSize padding = PaddingCalculator(shape.x(), 16).required_padding();
     validate(src.info()->padding(), padding);
     validate(dst.info()->padding(), padding);
 }
arm_compute::test::validation::DATA_TEST_CASE (AutoPadding , framework::DatasetMode::ALL , zip(zip(zip(framework::dataset::make("TensorShape",{TensorShape{},TensorShape{10U},TensorShape{10U, 10U},TensorShape{10U, 10U, 10U},TensorShape{10U, 10U, 10U, 10U},TensorShape{10U, 10U, 10U, 10U, 10U},TensorShape{10U, 10U, 10U, 10U, 10U, 10U}}),framework::dataset::make("PaddingSize",{PaddingSize{0, 0, 0, 0},PaddingSize{0, 36, 0, 4},PaddingSize{4, 36, 4, 4},PaddingSize{4, 36, 4, 4},PaddingSize{4, 36, 4, 4},PaddingSize{4, 36, 4, 4},PaddingSize{4, 36, 4, 4}})),framework::dataset::make("Strides",{Strides{},Strides{1U, 50U},Strides{1U, 50U},Strides{1U, 50U, 900U},Strides{1U, 50U, 900U, 9000U},Strides{1U, 50U, 900U, 9000U, 90000U},Strides{1U, 50U, 900U, 9000U, 90000U, 900000U}})),framework::dataset::make("Offset",{0U, 4U, 204U, 204U, 204U, 204U, 204U})) , shape , auto_padding , strides , offset)
Definition at line 43 of file TensorInfo.cpp.
References arm_compute::U.
{
                TensorShape{},
                TensorShape{ 10U },
                TensorShape{ 10U, 10U },
                TensorShape{ 10U, 10U, 10U },
                TensorShape{ 10U, 10U, 10U, 10U },
                TensorShape{ 10U, 10U, 10U, 10U, 10U },
                TensorShape{ 10U, 10U, 10U, 10U, 10U, 10U }}),
                framework::dataset::make("PaddingSize", {
                PaddingSize{ 0, 0, 0, 0 },
                PaddingSize{ 0, 36, 0, 4 },
                PaddingSize{ 4, 36, 4, 4 },
                PaddingSize{ 4, 36, 4, 4 },
                PaddingSize{ 4, 36, 4, 4 },
                PaddingSize{ 4, 36, 4, 4 },
                PaddingSize{ 4, 36, 4, 4 }})),
                framework::dataset::make("Strides", {
                Strides{},
                Strides{ 1U, 50U },
                Strides{ 1U, 50U },
                Strides{ 1U, 50U, 900U },
                Strides{ 1U, 50U, 900U, 9000U },
                Strides{ 1U, 50U, 900U, 9000U, 90000U },
                Strides{ 1U, 50U, 900U, 9000U, 90000U, 900000U }})),
                framework::dataset::make("Offset", { 0U, 4U, 204U, 204U, 204U, 204U, 204U })),
                shape, auto_padding, strides, offset)
 {
     TensorInfo info{ shape, Format::U8 };
     ARM_COMPUTE_EXPECT(!info.has_padding(), framework::LogLevel::ERRORS);
     info.auto_padding();
     validate(info.padding(), auto_padding);
     ARM_COMPUTE_EXPECT(compare_dimensions(info.strides_in_bytes(), strides), framework::LogLevel::ERRORS);
     ARM_COMPUTE_EXPECT(info.offset_first_element_in_bytes() == offset, framework::LogLevel::ERRORS);
 }
DATA_TEST_CASE (Configuration , framework::DatasetMode::ALL , combine(combine(combine(combine(concat(datasets::SmallShapes(), datasets::LargeShapes()), datasets::NonLinearFilterFunctions()),framework::dataset::make("MaskSize",{3U, 5U})),datasets::MatrixPatterns()),datasets::BorderModes()) , shape , function , mask_size , pattern , border_mode)
Definition at line 44 of file NonLinearFilter.cpp.
References arm_compute::U.
                                                                                                                     { 3U, 5U })),
                                                                            datasets::MatrixPatterns()),
                                                                    datasets::BorderModes()),
                shape, function, mask_size, pattern, border_mode)
 {
     std::mt19937                           generator(library->seed());
     std::uniform_int_distribution<uint8_t> distribution_u8(0, 255);
     const uint8_t                          constant_border_value = distribution_u8(generator);
     // Create the mask
     uint8_t mask[mask_size * mask_size];
     fill_mask_from_pattern(mask, mask_size, mask_size, pattern);
     const auto half_mask_size = static_cast<int>(mask_size / 2);
     // Create tensors
     CLTensor src = create_tensor<CLTensor>(shape, DataType::U8);
     CLTensor dst = create_tensor<CLTensor>(shape, DataType::U8);
     ARM_COMPUTE_EXPECT(src.info()->is_resizable(), framework::LogLevel::ERRORS);
     ARM_COMPUTE_EXPECT(dst.info()->is_resizable(), framework::LogLevel::ERRORS);
     // Create and configure function
     CLNonLinearFilter filter;
     filter.configure(&src, &dst, function, mask_size, pattern, mask, border_mode, constant_border_value);
     // Validate valid region
     const ValidRegion dst_valid_region = shape_to_valid_region(shape, border_mode == BorderMode::UNDEFINED, BorderSize(half_mask_size));
     validate(dst.info()->valid_region(), dst_valid_region);
     // Validate padding
     PaddingCalculator calculator(shape.x(), ((MatrixPattern::OTHER == pattern) ? 1 : 8));
     calculator.set_border_mode(border_mode);
     calculator.set_border_size(half_mask_size);
     const PaddingSize write_padding = calculator.required_padding(PaddingCalculator::Option::EXCLUDE_BORDER);
     calculator.set_accessed_elements(16);
     calculator.set_access_offset(-half_mask_size);
     const PaddingSize read_padding = calculator.required_padding(PaddingCalculator::Option::INCLUDE_BORDER);
     validate(src.info()->padding(), read_padding);
     validate(dst.info()->padding(), write_padding);
 }
DATA_TEST_CASE (Configuration , framework::DatasetMode::ALL , combine(concat(datasets::SmallShapes(), datasets::LargeShapes()), framework::dataset::make("DataType", DataType::U8)) , shape , data_type)
Definition at line 46 of file BitwiseAnd.cpp.
References ARM_COMPUTE_EXPECT(), bitwise_and(), data_type, arm_compute::test::framework::ERRORS, CLTensor::info(), TensorInfo::is_resizable(), TensorInfo::padding(), padding, shape, arm_compute::test::shape_to_valid_region(), TensorInfo::valid_region(), and validate().
 {
     // Create tensors
     CLTensor src1 = create_tensor<CLTensor>(shape, data_type);
     CLTensor src2 = create_tensor<CLTensor>(shape, data_type);
     CLTensor dst  = create_tensor<CLTensor>(shape, data_type);
     ARM_COMPUTE_EXPECT(src1.info()->is_resizable(), framework::LogLevel::ERRORS);
     ARM_COMPUTE_EXPECT(src2.info()->is_resizable(), framework::LogLevel::ERRORS);
     ARM_COMPUTE_EXPECT(dst.info()->is_resizable(), framework::LogLevel::ERRORS);
     // Create and configure function
     CLBitwiseAnd bitwise_and;
     bitwise_and.configure(&src1, &src2, &dst);
     // Validate valid region
     const ValidRegion valid_region = shape_to_valid_region(shape);
     validate(src1.info()->valid_region(), valid_region);
     validate(src2.info()->valid_region(), valid_region);
     validate(dst.info()->valid_region(), valid_region);
     // Validate padding
     const PaddingSize padding = PaddingCalculator(shape.x(), 16).required_padding();
     validate(src1.info()->padding(), padding);
     validate(src2.info()->padding(), padding);
     validate(dst.info()->padding(), padding);
 }
DATA_TEST_CASE (Configuration , framework::DatasetMode::ALL , combine(concat(datasets::Small2DShapes(), datasets::Large2DShapes()), framework::dataset::make("DataType", DataType::U8)) , shape , data_type)
Definition at line 47 of file MeanStdDev.cpp.
References ARM_COMPUTE_EXPECT(), CLMeanStdDev::configure(), data_type, arm_compute::test::framework::ERRORS, CLTensor::info(), TensorInfo::is_resizable(), TensorInfo::padding(), padding, shape, arm_compute::test::shape_to_valid_region(), TensorInfo::valid_region(), and validate().
 {
     // Create tensors
     CLTensor src = create_tensor<CLTensor>(shape, data_type);
     // Create output variables
     float mean    = 0.f;
     float std_dev = 0.f;
     ARM_COMPUTE_EXPECT(src.info()->is_resizable(), framework::LogLevel::ERRORS);
     // Create configure function
     CLMeanStdDev mean_std_dev_image;
     mean_std_dev_image.configure(&src, &mean, &std_dev);
     // Validate valid region
     const ValidRegion valid_region = shape_to_valid_region(shape);
     validate(src.info()->valid_region(), valid_region);
     // Validate padding
     const PaddingSize padding = PaddingCalculator(shape.x(), 8).required_padding();
     validate(src.info()->padding(), padding);
 }
DATA_TEST_CASE (FillBorder , framework::DatasetMode::ALL , combine(combine(combine(combine(datasets::SmallShapes(),datasets::BorderModes()),BorderSizesDataset),PaddingSizesDataset),framework::dataset::make("DataType", DataType::U8)) , shape , border_mode , size , padding , data_type)
Definition at line 52 of file FillBorder.cpp.
References ITensorAllocator::allocate(), CLTensor::allocator(), CLFillBorderKernel::configure(), data_type, TensorInfo::extend_padding(), CLScheduler::get(), CLTensor::info(), arm_compute::test::library, TensorInfo::padding(), padding, CLScheduler::queue(), CLFillBorderKernel::run(), shape, size, TEST_SUITE_END(), validate(), and IKernel::window().
 {
     BorderSize border_size{ static_cast<unsigned int>(size) };
     std::mt19937                           generator(library->seed());
     std::uniform_int_distribution<uint8_t> distribution_u8(0, 255);
     const uint8_t                          border_value = distribution_u8(generator);
     const uint8_t                          tensor_value = distribution_u8(generator);
     // Create tensors
     CLTensor src = create_tensor<CLTensor>(shape, data_type);
     src.info()->extend_padding(padding);
     // Allocate tensor
     src.allocator()->allocate();
     // Check padding is as required
     validate(src.info()->padding(), padding);
     // Fill tensor with constant value
     std::uniform_int_distribution<uint8_t> distribution{ tensor_value, tensor_value };
     library->fill(CLAccessor(src), distribution, 0);
     // Create and configure kernel
     CLFillBorderKernel fill_border;
     fill_border.configure(&src, border_size, border_mode, border_value);
     // Run kernel
     fill_border.run(fill_border.window(), CLScheduler::get().queue());
     // Validate border
     border_size.limit(padding);
     validate(CLAccessor(src), border_size, border_mode, &border_value);
     // Validate tensor
     validate(CLAccessor(src), &tensor_value);
 }
DATA_TEST_CASE (Configuration , framework::DatasetMode::ALL , combine(combine(concat(datasets::Small2DShapes(), datasets::Large2DShapes()), datasets::BorderModes()), framework::dataset::make("Format",Format::U8)) , shape , border_mode , format)
Definition at line 52 of file Sobel.cpp.
References ARM_COMPUTE_EXPECT(), arm_compute::data_type_from_format(), arm_compute::test::framework::ERRORS, CLTensor::info(), TensorInfo::is_resizable(), arm_compute::test::library, TensorInfo::padding(), arm_compute::S16, PaddingCalculator::set_border_mode(), TensorInfo::set_format(), shape, arm_compute::test::shape_to_valid_region(), arm_compute::test::validation::reference::sobel(), arm_compute::UNDEFINED, and validate().
 {
     // Generate a random constant value
     std::mt19937                           gen(library->seed());
     std::uniform_int_distribution<uint8_t> int_dist(0, 255);
     const uint8_t                          constant_border_value = int_dist(gen);
     // Create tensors
     CLTensor src   = create_tensor<CLTensor>(shape, data_type_from_format(format));
     CLTensor dst_x = create_tensor<CLTensor>(shape, DataType::S16);
     CLTensor dst_y = create_tensor<CLTensor>(shape, DataType::S16);
     src.info()->set_format(format);
     dst_x.info()->set_format(Format::S16);
     dst_y.info()->set_format(Format::S16);
     ARM_COMPUTE_EXPECT(src.info()->is_resizable(), framework::LogLevel::ERRORS);
     ARM_COMPUTE_EXPECT(dst_x.info()->is_resizable(), framework::LogLevel::ERRORS);
     ARM_COMPUTE_EXPECT(dst_y.info()->is_resizable(), framework::LogLevel::ERRORS);
     // Create sobel 3x3 configure function
     CLSobel3x3 sobel;
     sobel.configure(&src, &dst_x, &dst_y, border_mode, constant_border_value);
     // Validate valid region
     constexpr BorderSize border_size{ 1 };
     const ValidRegion    dst_valid_region = shape_to_valid_region(shape, border_mode == BorderMode::UNDEFINED, border_size);
     validate(dst_x.info()->valid_region(), dst_valid_region);
     validate(dst_y.info()->valid_region(), dst_valid_region);
     // Validate padding
     PaddingCalculator calculator(shape.x(), 8);
     calculator.set_border_mode(border_mode);
     calculator.set_border_size(1);
     const PaddingSize dst_padding = calculator.required_padding();
     calculator.set_accessed_elements(16);
     calculator.set_access_offset(-1);
     const PaddingSize src_padding = calculator.required_padding();
     validate(src.info()->padding(), src_padding);
     validate(dst_x.info()->padding(), dst_padding);
     validate(dst_y.info()->padding(), dst_padding);
 }
DATA_TEST_CASE (Configuration , framework::DatasetMode::ALL , combine(combine(concat(datasets::SmallShapes(), datasets::LargeShapes()), framework::dataset::make("DataType", DataType::U8)),datasets::BorderModes()) , shape , data_type , border_mode)
Definition at line 53 of file Box3x3.cpp.
References ARM_COMPUTE_EXPECT(), arm_compute::test::validation::reference::box3x3(), data_type, arm_compute::test::framework::ERRORS, CLTensor::info(), TensorInfo::is_resizable(), TensorInfo::padding(), PaddingCalculator::set_border_size(), shape, arm_compute::test::shape_to_valid_region(), arm_compute::UNDEFINED, and validate().
 {
     // Create tensors
     CLTensor src = create_tensor<CLTensor>(shape, data_type);
     CLTensor dst = create_tensor<CLTensor>(shape, data_type);
     ARM_COMPUTE_EXPECT(src.info()->is_resizable(), framework::LogLevel::ERRORS);
     ARM_COMPUTE_EXPECT(dst.info()->is_resizable(), framework::LogLevel::ERRORS);
     // Create and configure function
     CLBox3x3 box3x3;
     box3x3.configure(&src, &dst, border_mode);
     // Validate valid region
     const ValidRegion dst_valid_region = shape_to_valid_region(shape, (border_mode == BorderMode::UNDEFINED), border_size);
     validate(dst.info()->valid_region(), dst_valid_region);
     // Validate padding
     PaddingCalculator calculator(shape.x(), 8);
     calculator.set_border_size(1);
     calculator.set_border_mode(border_mode);
     const PaddingSize dst_padding = calculator.required_padding();
     calculator.set_accessed_elements(16);
     calculator.set_access_offset(-1);
     const PaddingSize src_padding = calculator.required_padding();
     validate(src.info()->padding(), src_padding);
     validate(dst.info()->padding(), dst_padding);
 }
DATA_TEST_CASE (Configuration , framework::DatasetMode::ALL , combine(DequantizationShapes, framework::dataset::make("DataType", DataType::U8)) , shape , data_type)
Definition at line 54 of file DequantizationLayer.cpp.
References ARM_COMPUTE_EXPECT(), CLDequantizationLayer::configure(), data_type, Window::DimX, arm_compute::test::framework::ERRORS, arm_compute::F32, CLTensor::info(), TensorInfo::is_resizable(), TensorInfo::padding(), padding, TensorShape::remove_dimension(), TensorShape::set(), shape, arm_compute::test::shape_to_valid_region(), TensorInfo::valid_region(), and validate().
 {
     TensorShape shape_min_max = shape;
     shape_min_max.set(Window::DimX, 2);
     // Remove Y and Z dimensions and keep the batches
     shape_min_max.remove_dimension(1);
     shape_min_max.remove_dimension(1);
     // Create tensors
     CLTensor src     = create_tensor<CLTensor>(shape, data_type);
     CLTensor dst     = create_tensor<CLTensor>(shape, DataType::F32);
     CLTensor min_max = create_tensor<CLTensor>(shape_min_max, DataType::F32);
     ARM_COMPUTE_EXPECT(src.info()->is_resizable(), framework::LogLevel::ERRORS);
     ARM_COMPUTE_EXPECT(dst.info()->is_resizable(), framework::LogLevel::ERRORS);
     ARM_COMPUTE_EXPECT(min_max.info()->is_resizable(), framework::LogLevel::ERRORS);
     // Create and configure function
     CLDequantizationLayer dequant_layer;
     dequant_layer.configure(&src, &dst, &min_max);
     // Validate valid region
     const ValidRegion valid_region = shape_to_valid_region(shape);
     validate(src.info()->valid_region(), valid_region);
     validate(dst.info()->valid_region(), valid_region);
     // Validate valid region of min_max tensor
     const ValidRegion valid_region_min_max = shape_to_valid_region(shape_min_max);
     validate(min_max.info()->valid_region(), valid_region_min_max);
     // Validate padding
     const PaddingSize padding = PaddingCalculator(shape.x(), 4).required_padding();
     validate(src.info()->padding(), padding);
     validate(dst.info()->padding(), padding);
     // Validate padding of min_max tensor
     const PaddingSize padding_min_max = PaddingCalculator(shape_min_max.x(), 2).required_padding();
     validate(min_max.info()->padding(), padding_min_max);
 }
DATA_TEST_CASE (Configuration , framework::DatasetMode::ALL , combine(framework::dataset::concat(datasets::SmallShapes(), datasets::LargeShapes()), framework::dataset::make("DataType",{DataType::U8, DataType::S16})) , shape , data_type)
Definition at line 54 of file TableLookup.cpp.
References arm_compute::S16, and arm_compute::U8.
                                                                                                                                                                       { DataType::U8, DataType::S16 })),
                shape, data_type)
 {
     // Create Lut
     const int num_elem = (data_type == DataType::U8) ? std::numeric_limits<uint8_t>::max() + 1 : std::numeric_limits<int16_t>::max() - std::numeric_limits<int16_t>::lowest() + 1;
     CLLut     cllut(num_elem, data_type);
     switch(data_type)
     {
         case DataType::U8:
             fill_lookuptable(CLLutAccessor<uint8_t>(cllut));
             break;
         case DataType::S16:
             fill_lookuptable(CLLutAccessor<int16_t>(cllut));
             break;
         default:
             ARM_COMPUTE_ERROR("Not supported");
     }
     // Create tensors
     CLTensor src = create_tensor<CLTensor>(shape, data_type);
     CLTensor dst = create_tensor<CLTensor>(shape, data_type);
     // Create and Configure function
     CLTableLookup table_lookup;
     table_lookup.configure(&src, &cllut, &dst);
     // Validate valid region
     const ValidRegion valid_region = shape_to_valid_region(shape);
     validate(dst.info()->valid_region(), valid_region);
     // Validate padding
     const PaddingSize padding = PaddingCalculator(shape.x(), 8).required_padding();
     validate(src.info()->padding(), padding);
     validate(dst.info()->padding(), padding);
 }
DATA_TEST_CASE (Configuration , framework::DatasetMode::ALL , combine(QuantizationShapes, framework::dataset::make("DataType", DataType::F32)) , shape , data_type)
Definition at line 55 of file QuantizationLayer.cpp.
References ARM_COMPUTE_EXPECT(), CLQuantizationLayer::configure(), data_type, arm_compute::test::framework::ERRORS, CLTensor::info(), TensorInfo::is_resizable(), TensorInfo::padding(), padding, shape, arm_compute::test::shape_to_valid_region(), arm_compute::U8, TensorInfo::valid_region(), and validate().
 {
     // Create tensors
     CLTensor src = create_tensor<CLTensor>(shape, data_type);
     CLTensor dst = create_tensor<CLTensor>(shape, DataType::U8);
     ARM_COMPUTE_EXPECT(src.info()->is_resizable(), framework::LogLevel::ERRORS);
     ARM_COMPUTE_EXPECT(dst.info()->is_resizable(), framework::LogLevel::ERRORS);
     // Create and configure function
     CLQuantizationLayer quant_layer;
     quant_layer.configure(&src, &dst);
     // Validate valid region
     const ValidRegion valid_region = shape_to_valid_region(shape);
     validate(src.info()->valid_region(), valid_region);
     validate(dst.info()->valid_region(), valid_region);
     // Validate padding
     const PaddingSize padding = PaddingCalculator(shape.x(), 4).required_padding();
     validate(src.info()->padding(), padding);
     validate(dst.info()->padding(), padding);
 }
DATA_TEST_CASE (Configuration , framework::DatasetMode::ALL , combine(combine(concat(datasets::Small2DShapes(), datasets::Large2DShapes()), data), framework::dataset::make("Format", Format::U8)) , shape , gradient_size , block_size , border_mode , use_fp16 , format)
Definition at line 57 of file HarrisCorners.cpp.
References ARM_COMPUTE_ERROR_ON, ARM_COMPUTE_EXPECT(), ARM_COMPUTE_UNUSED, CLHarrisCorners::configure(), arm_compute::data_type_from_format(), arm_compute::test::framework::ERRORS, CLTensor::info(), TensorInfo::is_resizable(), arm_compute::test::library, TensorInfo::padding(), padding, PaddingCalculator::set_border_mode(), TensorInfo::set_format(), shape, arm_compute::test::validation::reference::threshold(), and validate().
 {
     ARM_COMPUTE_UNUSED(use_fp16);
     ARM_COMPUTE_ERROR_ON(use_fp16);
     std::mt19937                          gen(library->seed());
     std::uniform_real_distribution<float> real_dist(0.f, 0.01f);
     const float threshold   = real_dist(gen);
     const float sensitivity = real_dist(gen);
     constexpr float max_euclidean_distance = 30.f;
     real_dist                              = std::uniform_real_distribution<float>(0.f, max_euclidean_distance);
     const float min_dist                   = real_dist(gen);
     // Generate a random constant value
     std::uniform_int_distribution<uint8_t> int_dist(0, 255);
     const uint8_t                          constant_border_value = int_dist(gen);
     // Create tensors
     CLTensor src = create_tensor<CLTensor>(shape, data_type_from_format(format));
     src.info()->set_format(format);
     CLKeyPointArray corners;
     ARM_COMPUTE_EXPECT(src.info()->is_resizable(), framework::LogLevel::ERRORS);
     // Create harris corners configure function
     CLHarrisCorners harris_corners;
     harris_corners.configure(&src, threshold, min_dist, sensitivity, gradient_size, block_size, &corners, border_mode, constant_border_value);
     // Validate padding
     PaddingCalculator calculator(shape.x(), 8);
     calculator.set_border_mode(border_mode);
     calculator.set_border_size(gradient_size / 2);
     calculator.set_access_offset(-gradient_size / 2);
     calculator.set_accessed_elements(16);
     const PaddingSize padding = calculator.required_padding();
     validate(src.info()->padding(), padding);
 }
DATA_TEST_CASE (Configuration , framework::DatasetMode::ALL , combine(combine(combine(concat(datasets::SmallShapes(), datasets::LargeShapes()), framework::dataset::make("DataType", DataType::U8)),framework::dataset::make("InterpolationPolicy",{InterpolationPolicy::NEAREST_NEIGHBOR, InterpolationPolicy::BILINEAR})),datasets::BorderModes()) , shape , data_type , policy , border_mode)
Definition at line 57 of file WarpAffine.cpp.
References arm_compute::BILINEAR, and arm_compute::NEAREST_NEIGHBOR.
                                                                                                                        { InterpolationPolicy::NEAREST_NEIGHBOR, InterpolationPolicy::BILINEAR })),
                                                                    datasets::BorderModes()),
                shape, data_type, policy, border_mode)
 {
     // Generate a random constant value if border_mode is constant
     std::mt19937                           gen(library->seed());
     std::uniform_int_distribution<uint8_t> distribution_u8(0, 255);
     uint8_t                                constant_border_value = distribution_u8(gen);
     // Create the matrix
     std::array<float, 6> matrix{ {} };
     fill_warp_matrix<6>(matrix);
     // Create tensors
     CLTensor src = create_tensor<CLTensor>(shape, data_type);
     CLTensor dst = create_tensor<CLTensor>(shape, data_type);
     ARM_COMPUTE_EXPECT(src.info()->is_resizable(), framework::LogLevel::ERRORS);
     ARM_COMPUTE_EXPECT(dst.info()->is_resizable(), framework::LogLevel::ERRORS);
     // Create and configure function
     CLWarpAffine warp_affine;
     warp_affine.configure(&src, &dst, matrix.data(), policy, border_mode, constant_border_value);
     // Validate valid region
     const ValidRegion valid_region = shape_to_valid_region(shape);
     validate(src.info()->valid_region(), valid_region);
     validate(dst.info()->valid_region(), valid_region);
     // Validate padding
     int               total_right  = ceil_to_multiple(shape[0], 4);
     const int         access_right = total_right + (((total_right - shape[0]) == 0) ? 1 : 0);
     const PaddingSize read_padding(1, access_right - shape[0], 1, 1);
     validate(src.info()->padding(), read_padding);
     PaddingCalculator calculator(shape.x(), 4);
     validate(dst.info()->padding(), calculator.required_padding());
 }
arm_compute::test::validation::DATA_TEST_CASE (Configuration , framework::DatasetMode::ALL , combine(datasets::RandomBatchNormalizationLayerDataset(), framework::dataset::make("DataType",{DataType::QS8, DataType::QS16, DataType::F16, DataType::F32})) , shape0 , shape1 , epsilon , dt)
Definition at line 58 of file BatchNormalizationLayer.cpp.
References arm_compute::F16, arm_compute::F32, arm_compute::QS16, and arm_compute::QS8.
                                                                                                                                                 { DataType::QS8, DataType::QS16, DataType::F16, DataType::F32 })),
                shape0, shape1, epsilon, dt)
 {
     // Set fixed point position data type allowed
     int fixed_point_position = (arm_compute::is_data_type_fixed_point(dt)) ? 3 : 0;
     // Create tensors
     CLTensor src   = create_tensor<CLTensor>(shape0, dt, 1, fixed_point_position);
     CLTensor dst   = create_tensor<CLTensor>(shape0, dt, 1, fixed_point_position);
     CLTensor mean  = create_tensor<CLTensor>(shape1, dt, 1, fixed_point_position);
     CLTensor var   = create_tensor<CLTensor>(shape1, dt, 1, fixed_point_position);
     CLTensor beta  = create_tensor<CLTensor>(shape1, dt, 1, fixed_point_position);
     CLTensor gamma = create_tensor<CLTensor>(shape1, dt, 1, fixed_point_position);
     // Create and Configure function
     CLBatchNormalizationLayer norm;
     norm.configure(&src, &dst, &mean, &var, &beta, &gamma, epsilon);
     // Validate valid region
     const ValidRegion valid_region = shape_to_valid_region(shape0);
     validate(dst.info()->valid_region(), valid_region);
 }
arm_compute::test::validation::DATA_TEST_CASE (Configuration , framework::DatasetMode::ALL , combine(datasets::RandomBatchNormalizationLayerDataset(), framework::dataset::make("DataType",{DataType::QS8, DataType::QS16, DataType::F32})) , shape0 , shape1 , epsilon , dt)
Definition at line 60 of file BatchNormalizationLayer.cpp.
References arm_compute::F32, arm_compute::QS16, and arm_compute::QS8.
                                                                                                                                                 { DataType::QS8, DataType::QS16, DataType::F32 })),
                shape0, shape1, epsilon, dt)
 {
     // Set fixed point position data type allowed
     int fixed_point_position = (arm_compute::is_data_type_fixed_point(dt)) ? 3 : 0;
     // Create tensors
     Tensor src   = create_tensor<Tensor>(shape0, dt, 1, fixed_point_position);
     Tensor dst   = create_tensor<Tensor>(shape0, dt, 1, fixed_point_position);
     Tensor mean  = create_tensor<Tensor>(shape1, dt, 1, fixed_point_position);
     Tensor var   = create_tensor<Tensor>(shape1, dt, 1, fixed_point_position);
     Tensor beta  = create_tensor<Tensor>(shape1, dt, 1, fixed_point_position);
     Tensor gamma = create_tensor<Tensor>(shape1, dt, 1, fixed_point_position);
     // Create and Configure function
     NEBatchNormalizationLayer norm;
     norm.configure(&src, &dst, &mean, &var, &beta, &gamma, epsilon);
     // Validate valid region
     const ValidRegion valid_region = shape_to_valid_region(shape0);
     validate(dst.info()->valid_region(), valid_region);
 }
DATA_TEST_CASE (Configuration , framework::DatasetMode::ALL , combine(framework::dataset::concat(datasets::SmallConvolutionLayerDataset(), datasets::LargeConvolutionLayerDataset()), CNNDataTypes) , input_shape , weights_shape , bias_shape , output_shape , info , data_type)
Definition at line 64 of file ConvolutionLayer.cpp.
References ARM_COMPUTE_EXPECT(), CLConvolutionLayer::configure(), data_type, arm_compute::test::framework::ERRORS, CLTensor::info(), arm_compute::is_data_type_fixed_point(), TensorInfo::is_resizable(), arm_compute::test::shape_to_valid_region(), TensorInfo::valid_region(), and validate().
 {
     // Set fixed point position data type allowed
     int fixed_point_position = is_data_type_fixed_point(data_type) ? 3 : 0;
     // Create tensors
     CLTensor src     = create_tensor<CLTensor>(input_shape, data_type, 1, fixed_point_position);
     CLTensor weights = create_tensor<CLTensor>(weights_shape, data_type, 1, fixed_point_position);
     CLTensor bias    = create_tensor<CLTensor>(bias_shape, data_type, 1, fixed_point_position);
     CLTensor dst     = create_tensor<CLTensor>(output_shape, data_type, 1, fixed_point_position);
     ARM_COMPUTE_EXPECT(src.info()->is_resizable(), framework::LogLevel::ERRORS);
     ARM_COMPUTE_EXPECT(weights.info()->is_resizable(), framework::LogLevel::ERRORS);
     ARM_COMPUTE_EXPECT(bias.info()->is_resizable(), framework::LogLevel::ERRORS);
     ARM_COMPUTE_EXPECT(dst.info()->is_resizable(), framework::LogLevel::ERRORS);
     // Create and configure function
     CLConvolutionLayer conv;
     conv.configure(&src, &weights, &bias, &dst, info);
     // Validate valid region
     const ValidRegion src_valid_region     = shape_to_valid_region(input_shape);
     const ValidRegion weights_valid_region = shape_to_valid_region(weights_shape);
     const ValidRegion bias_valid_region    = shape_to_valid_region(bias_shape);
     const ValidRegion dst_valid_region     = shape_to_valid_region(output_shape);
     validate(src.info()->valid_region(), src_valid_region);
     validate(weights.info()->valid_region(), weights_valid_region);
     validate(bias.info()->valid_region(), bias_valid_region);
     validate(dst.info()->valid_region(), dst_valid_region);
 }
DATA_TEST_CASE (Configuration , framework::DatasetMode::ALL , combine(framework::dataset::concat(datasets::SmallGEMMDataset(), datasets::LargeGEMMDataset()), CNNDataTypes) , shape_a , shape_b , shape_c , output_shape , alpha , beta , data_type)
Definition at line 64 of file GEMM.cpp.
References ARM_COMPUTE_EXPECT(), data_type, arm_compute::test::framework::ERRORS, arm_compute::test::validation::reference::gemm(), CLTensor::info(), arm_compute::is_data_type_fixed_point(), and TensorInfo::is_resizable().
 {
     // Set fixed point position data type allowed
     const int fixed_point_position = is_data_type_fixed_point(data_type) ? 3 : 0;
     // Create tensors
     CLTensor a   = create_tensor<CLTensor>(shape_a, data_type, 1, fixed_point_position);
     CLTensor b   = create_tensor<CLTensor>(shape_b, data_type, 1, fixed_point_position);
     CLTensor c   = create_tensor<CLTensor>(shape_c, data_type, 1, fixed_point_position);
     CLTensor dst = create_tensor<CLTensor>(output_shape, data_type, 1, fixed_point_position);
     ARM_COMPUTE_EXPECT(a.info()->is_resizable(), framework::LogLevel::ERRORS);
     ARM_COMPUTE_EXPECT(b.info()->is_resizable(), framework::LogLevel::ERRORS);
     ARM_COMPUTE_EXPECT(c.info()->is_resizable(), framework::LogLevel::ERRORS);
     ARM_COMPUTE_EXPECT(dst.info()->is_resizable(), framework::LogLevel::ERRORS);
     // Create and configure function
     CLGEMM gemm;
     gemm.configure(&a, &b, &c, &dst, alpha, beta);
 }
DATA_TEST_CASE (Configuration , framework::DatasetMode::ALL , combine(concat(datasets::SmallShapes(), datasets::LargeShapes()), CNNDataTypes) , shape , data_type)
Definition at line 65 of file SoftmaxLayer.cpp.
References ARM_COMPUTE_EXPECT(), CLSoftmaxLayer::configure(), data_type, arm_compute::test::framework::ERRORS, CLTensor::info(), arm_compute::is_data_type_fixed_point(), TensorInfo::is_resizable(), TensorInfo::padding(), padding, shape, arm_compute::test::shape_to_valid_region(), TensorInfo::valid_region(), and validate().
 {
     // Set fixed point position data type allowed
     const int fixed_point_position = is_data_type_fixed_point(data_type) ? 3 : 0;
     // Create tensors
     CLTensor src = create_tensor<CLTensor>(shape, data_type, 1, fixed_point_position);
     CLTensor dst = create_tensor<CLTensor>(shape, data_type, 1, fixed_point_position);
     ARM_COMPUTE_EXPECT(src.info()->is_resizable(), framework::LogLevel::ERRORS);
     ARM_COMPUTE_EXPECT(dst.info()->is_resizable(), framework::LogLevel::ERRORS);
     // Create and configure function
     CLSoftmaxLayer smx_layer;
     smx_layer.configure(&src, &dst);
     // Validate valid region
     const ValidRegion valid_region = shape_to_valid_region(shape);
     validate(src.info()->valid_region(), valid_region);
     validate(dst.info()->valid_region(), valid_region);
     // Validate padding
     const PaddingSize padding = PaddingCalculator(shape.x(), 16).required_padding();
     validate(src.info()->padding(), padding);
     validate(dst.info()->padding(), padding);
 }
arm_compute::test::validation::DATA_TEST_CASE (FixedPointQS8Inputs , framework::DatasetMode::ALL , combine(FuncNamesDataset,framework::dataset::make("FractionalBits", 1, 7)) , func_name , frac_bits)
Definition at line 67 of file FixedPoint.cpp.
References ARM_COMPUTE_EXPECT(), arm_compute::test::framework::ERRORS, arm_compute::test::library, shape, arm_compute::to_string(), arm_compute::support::cpp11::to_string(), and arm_compute::test::tolower().
 {
     std::vector<double>        data;
     std::vector<unsigned long> shape; //NOLINT
     std::string func_name_lower = to_string(func_name);
     std::transform(func_name_lower.begin(), func_name_lower.end(), func_name_lower.begin(), ::tolower);
     const std::string inputs_file = library->path()
     + "fixed_point/"
     + func_name_lower
     + "_Q8."
     + support::cpp11::to_string(frac_bits)
     + ".in.npy";
     load_array_from_numpy(inputs_file, shape, data);
     // Values stored as doubles so reinterpret as floats
     const auto *float_val    = reinterpret_cast<float *>(&data[0]);
     const size_t num_elements = data.size() * sizeof(double) / sizeof(float);
     for(unsigned int i = 0; i < num_elements; ++i)
     {
         // Convert to fixed point
         fixed_point_arithmetic::fixed_point<int8_t> in_val(float_val[i], frac_bits);
         // Check that the value didn't change
         ARM_COMPUTE_EXPECT(static_cast<float>(in_val) == float_val[i], framework::LogLevel::ERRORS);
     }
 }
DATA_TEST_CASE (Configuration , framework::DatasetMode::ALL , combine(framework::dataset::concat(datasets::SmallShapes(), datasets::LargeShapes()), framework::dataset::make("ConvertPolicy",{ConvertPolicy::SATURATE, ConvertPolicy::WRAP})) , shape , policy)
Definition at line 68 of file ArithmeticAddition.cpp.
References arm_compute::SATURATE, and arm_compute::WRAP.
                                                                                                                                                                            { ConvertPolicy::SATURATE, ConvertPolicy::WRAP })),
                shape, policy)
 {
     // Create tensors
     CLTensor ref_src1 = create_tensor<CLTensor>(shape, DataType::U8);
     CLTensor ref_src2 = create_tensor<CLTensor>(shape, DataType::U8);
     CLTensor dst      = create_tensor<CLTensor>(shape, DataType::U8);
     // Create and Configure function
     CLArithmeticAddition add;
     add.configure(&ref_src1, &ref_src2, &dst, policy);
     // Validate valid region
     const ValidRegion valid_region = shape_to_valid_region(shape);
     validate(dst.info()->valid_region(), valid_region);
     // Validate padding
     const PaddingSize padding = PaddingCalculator(shape.x(), 16).required_padding();
     validate(ref_src1.info()->padding(), padding);
     validate(ref_src2.info()->padding(), padding);
     validate(dst.info()->padding(), padding);
 }
DATA_TEST_CASE (Configuration , framework::DatasetMode::ALL , combine(combine(framework::dataset::concat(datasets::SmallFullyConnectedLayerDataset(), datasets::LargeFullyConnectedLayerDataset()),FullyConnectedParameters),CNNDataTypes) , src_shape , weights_shape , bias_shape , dst_shape , transpose_weights , reshape_weights , data_type)
Definition at line 68 of file FullyConnectedLayer.cpp.
References ARM_COMPUTE_EXPECT(), CLFullyConnectedLayer::configure(), data_type, arm_compute::test::framework::ERRORS, CLTensor::info(), arm_compute::is_data_type_fixed_point(), TensorInfo::is_resizable(), TensorShape::set(), arm_compute::test::shape_to_valid_region(), validate(), Dimensions< T >::x(), and Dimensions< T >::y().
 {
     // Set fixed point position data type allowed
     int fixed_point_position = is_data_type_fixed_point(data_type) ? 3 : 0;
     TensorShape ws(weights_shape);
     // Transpose weights if not done in the function
     if(!reshape_weights || !transpose_weights)
     {
         const size_t shape_x = ws.x();
         ws.set(0, ws.y());
         ws.set(1, shape_x);
     }
     // Create tensors
     CLTensor src     = create_tensor<CLTensor>(src_shape, data_type, 1, fixed_point_position);
     CLTensor weights = create_tensor<CLTensor>(ws, data_type, 1, fixed_point_position);
     CLTensor bias    = create_tensor<CLTensor>(bias_shape, data_type, 1, fixed_point_position);
     CLTensor dst     = create_tensor<CLTensor>(dst_shape, data_type, 1, fixed_point_position);
     ARM_COMPUTE_EXPECT(src.info()->is_resizable(), framework::LogLevel::ERRORS);
     ARM_COMPUTE_EXPECT(weights.info()->is_resizable(), framework::LogLevel::ERRORS);
     ARM_COMPUTE_EXPECT(bias.info()->is_resizable(), framework::LogLevel::ERRORS);
     ARM_COMPUTE_EXPECT(dst.info()->is_resizable(), framework::LogLevel::ERRORS);
     // Create and configure function.
     CLFullyConnectedLayer fc;
     fc.configure(&src, &weights, &bias, &dst, transpose_weights, !reshape_weights);
     // Validate valid region
     const ValidRegion dst_valid_region = shape_to_valid_region(dst_shape);
     validate(dst.info()->valid_region(), dst_valid_region);
 }
arm_compute::test::validation::DATA_TEST_CASE (Configuration , framework::DatasetMode::ALL , combine(combine(combine(concat(datasets::MediumShapes(), datasets::LargeShapes()), ScaleDataTypes),framework::dataset::make("InterpolationPolicy",{InterpolationPolicy::NEAREST_NEIGHBOR, InterpolationPolicy::BILINEAR})),datasets::BorderModes()) , shape , data_type , policy , border_mode)
Definition at line 69 of file Scale.cpp.
References arm_compute::BILINEAR, and arm_compute::NEAREST_NEIGHBOR.
                                                                                                                        { InterpolationPolicy::NEAREST_NEIGHBOR, InterpolationPolicy::BILINEAR })),
                                                                    datasets::BorderModes()),
                shape, data_type, policy, border_mode)
 {
     std::mt19937                           generator(library->seed());
     std::uniform_real_distribution<float>  distribution_float(0.25, 2);
     const float                            scale_x = distribution_float(generator);
     const float                            scale_y = distribution_float(generator);
     std::uniform_int_distribution<uint8_t> distribution_u8(0, 255);
     uint8_t                                constant_border_value = distribution_u8(generator);
     // Create tensors
     CLTensor    src = create_tensor<CLTensor>(shape, data_type);
     TensorShape shape_scaled(shape);
     shape_scaled.set(0, shape[0] * scale_x);
     shape_scaled.set(1, shape[1] * scale_y);
     CLTensor dst = create_tensor<CLTensor>(shape_scaled, data_type);
     ARM_COMPUTE_EXPECT(src.info()->is_resizable(), framework::LogLevel::ERRORS);
     ARM_COMPUTE_EXPECT(dst.info()->is_resizable(), framework::LogLevel::ERRORS);
     // Create and configure function
     CLScale clscale;
     clscale.configure(&src, &dst, policy, border_mode, constant_border_value);
     // Validate valid region
     const ValidRegion dst_valid_region = calculate_valid_region_scale(*(src.info()), shape_scaled, policy, BorderSize(1), (border_mode == BorderMode::UNDEFINED));
     validate(dst.info()->valid_region(), dst_valid_region);
     // Validate padding
     PaddingCalculator calculator(shape_scaled.x(), 4);
     calculator.set_border_mode(border_mode);
     const PaddingSize read_padding(1);
     const PaddingSize write_padding = calculator.required_padding(PaddingCalculator::Option::EXCLUDE_BORDER);
     validate(src.info()->padding(), read_padding);
     validate(dst.info()->padding(), write_padding);
 }
arm_compute::test::validation::DATA_TEST_CASE (Configuration , framework::DatasetMode::ALL , combine(combine(combine(concat(datasets::SmallShapes(), datasets::LargeShapes()), ScaleDataTypes),framework::dataset::make("InterpolationPolicy",{InterpolationPolicy::NEAREST_NEIGHBOR, InterpolationPolicy::BILINEAR})),datasets::BorderModes()) , shape , data_type , policy , border_mode)
Definition at line 69 of file Scale.cpp.
References arm_compute::BILINEAR, and arm_compute::NEAREST_NEIGHBOR.
                                                                                                                        { InterpolationPolicy::NEAREST_NEIGHBOR, InterpolationPolicy::BILINEAR })),
                                                                    datasets::BorderModes()),
                shape, data_type, policy, border_mode)
 {
     std::mt19937                          generator(library->seed());
     std::uniform_real_distribution<float> distribution_float(0.25, 2);
     const float                           scale_x               = distribution_float(generator);
     const float                           scale_y               = distribution_float(generator);
     uint8_t                               constant_border_value = 0;
     if(border_mode == BorderMode::CONSTANT)
     {
         std::uniform_int_distribution<uint8_t> distribution_u8(0, 255);
         constant_border_value = distribution_u8(generator);
     }
     // Create tensors
     Tensor      src = create_tensor<Tensor>(shape, data_type);
     TensorShape shape_scaled(shape);
     shape_scaled.set(0, shape[0] * scale_x);
     shape_scaled.set(1, shape[1] * scale_y);
     Tensor dst = create_tensor<Tensor>(shape_scaled, data_type);
     ARM_COMPUTE_EXPECT(src.info()->is_resizable(), framework::LogLevel::ERRORS);
     ARM_COMPUTE_EXPECT(dst.info()->is_resizable(), framework::LogLevel::ERRORS);
     // Create and configure function
     NEScale nescale;
     nescale.configure(&src, &dst, policy, border_mode, constant_border_value);
     // Validate valid region
     const ValidRegion dst_valid_region = calculate_valid_region_scale(*(src.info()), shape_scaled, policy, BorderSize(1), (border_mode == BorderMode::UNDEFINED));
     validate(dst.info()->valid_region(), dst_valid_region);
     // Validate padding
     PaddingCalculator calculator(shape_scaled.x(), 16);
     calculator.set_border_mode(border_mode);
     const PaddingSize read_padding(1);
     const PaddingSize write_padding = calculator.required_padding(PaddingCalculator::Option::EXCLUDE_BORDER);
     validate(src.info()->padding(), read_padding);
     validate(dst.info()->padding(), write_padding);
 }
DATA_TEST_CASE (Configuration , framework::DatasetMode::ALL , combine(combine(framework::dataset::concat(datasets::SmallShapes(), datasets::LargeShapes()), framework::dataset::make("ConvertPolicy",{ConvertPolicy::SATURATE, ConvertPolicy::WRAP})),DepthConvertShiftDataset) , shape , policy , shift)
Definition at line 82 of file DepthConvert.cpp.
References arm_compute::SATURATE, and arm_compute::WRAP.
                                                                                                                                                                                    { ConvertPolicy::SATURATE, ConvertPolicy::WRAP })),
                                                                    DepthConvertShiftDataset),
                shape, policy, shift)
 {
     int fixed_point_position = 0;
     // Create tensors
     CLTensor src = create_tensor<CLTensor>(shape, DataType::U8, 1, fixed_point_position);
     CLTensor dst = create_tensor<CLTensor>(shape, DataType::U16, 1, fixed_point_position);
     // Create and Configure function
     CLDepthConvert depth_convert;
     depth_convert.configure(&src, &dst, policy, shift);
     // Validate valid region
     const ValidRegion valid_region = shape_to_valid_region(shape);
     validate(dst.info()->valid_region(), valid_region);
     // Validate padding
     const PaddingSize padding = PaddingCalculator(shape.x(), 16).required_padding();
     validate(src.info()->padding(), padding);
     validate(dst.info()->padding(), padding);
 }
DATA_TEST_CASE (Configuration , framework::DatasetMode::ALL , combine(combine(framework::dataset::concat(datasets::SmallShapes(), datasets::LargeShapes()), framework::dataset::make("DataType",{DataType::U8, DataType::S16})),framework::dataset::make("ConvertPolicy",{ConvertPolicy::SATURATE, ConvertPolicy::WRAP})) , shape , data_type , policy)
Definition at line 100 of file ArithmeticAddition.cpp.
References arm_compute::S16, and arm_compute::U8.
                                                                                                                                                                               { DataType::U8, DataType::S16 })),
                                                                    framework::dataset::make("ConvertPolicy", { ConvertPolicy::SATURATE, ConvertPolicy::WRAP })),
                shape, data_type, policy)
 {
     // Create tensors
     CLTensor ref_src1 = create_tensor<CLTensor>(shape, data_type);
     CLTensor ref_src2 = create_tensor<CLTensor>(shape, DataType::S16);
     CLTensor dst      = create_tensor<CLTensor>(shape, DataType::S16);
     // Create and Configure function
     CLArithmeticAddition add;
     add.configure(&ref_src1, &ref_src2, &dst, policy);
     // Validate valid region
     const ValidRegion valid_region = shape_to_valid_region(shape);
     validate(dst.info()->valid_region(), valid_region);
     // Validate padding
     const PaddingSize padding = PaddingCalculator(shape.x(), 16).required_padding();
     validate(ref_src1.info()->padding(), padding);
     validate(ref_src2.info()->padding(), padding);
     validate(dst.info()->padding(), padding);
 }
arm_compute::test::validation::DATA_TEST_CASE (FixedPointQS8Outputs , framework::DatasetMode::ALL , zip(combine(FuncNamesDataset,framework::dataset::make("FractionalBits", 1, 7)),framework::dataset::make("ExpectedFailures",{0, 0, 0, 0, 0, 0,0, 0, 0, 0, 0, 0,0, 0, 0, 0, 0, 0,7, 8, 13, 2, 0, 0,0, 0, 0, 0, 0, 0,0, 0, 0, 5, 33, 96})) , func_name , frac_bits , expected_failures)
Definition at line 109 of file FixedPoint.cpp.
                                                         { 0, 0, 0, 0, 0, 0,
                                                               0, 0, 0, 0, 0, 0,
                                                               0, 0, 0, 0, 0, 0,
                                                               7, 8, 13, 2, 0, 0,
                                                               0, 0, 0, 0, 0, 0,
                                                               0, 0, 0, 5, 33, 96 })),
                func_name, frac_bits, expected_failures)
 // clang-format on
 // *INDENT-ON*
 {
     std::vector<double>        in_data;
     std::vector<unsigned long> in_shape; //NOLINT
     std::vector<double>        out_data;
     std::vector<unsigned long> out_shape; //NOLINT
     std::string func_name_lower = to_string(func_name);
     std::transform(func_name_lower.begin(), func_name_lower.end(), func_name_lower.begin(), ::tolower);
     const std::string base_file_name = library->path()
     + "fixed_point/"
     + func_name_lower
     + "_Q8."
     + support::cpp11::to_string(frac_bits);
     const std::string inputs_file    = base_file_name + ".in.npy";
     const std::string reference_file = base_file_name + ".out.npy";
     load_array_from_numpy(inputs_file, in_shape, in_data);
     load_array_from_numpy(reference_file, out_shape, out_data);
     ARM_COMPUTE_EXPECT(in_shape.front() == out_shape.front(), framework::LogLevel::ERRORS);
     const float step_size      = std::pow(2.f, -frac_bits);
     int64_t     num_mismatches = 0;
     // Values stored as doubles so reinterpret as floats
     const auto *float_val = reinterpret_cast<float *>(&in_data[0]);
     const auto *ref_val   = reinterpret_cast<float *>(&out_data[0]);
     const size_t num_elements = in_data.size() * sizeof(double) / sizeof(float);
     for(unsigned int i = 0; i < num_elements; ++i)
     {
         fixed_point_arithmetic::fixed_point<int8_t> in_val(float_val[i], frac_bits);
         fixed_point_arithmetic::fixed_point<int8_t> out_val(0.f, frac_bits);
         float tolerance = 0.f;
         if(func_name == FixedPointOp::ADD)
         {
             out_val = in_val + in_val;
         }
         else if(func_name == FixedPointOp::SUB)
         {
             out_val = in_val - in_val; //NOLINT
         }
         else if(func_name == FixedPointOp::MUL)
         {
             tolerance = 1.f * step_size;
             out_val   = in_val * in_val;
         }
         else if(func_name == FixedPointOp::EXP)
         {
             tolerance = 2.f * step_size;
             out_val   = fixed_point_arithmetic::exp(in_val);
         }
         else if(func_name == FixedPointOp::LOG)
         {
             tolerance = 4.f * step_size;
             out_val   = fixed_point_arithmetic::log(in_val);
         }
         else if(func_name == FixedPointOp::INV_SQRT)
         {
             tolerance = 5.f * step_size;
             out_val   = fixed_point_arithmetic::inv_sqrt(in_val);
         }
         if(std::abs(static_cast<float>(out_val) - ref_val[i]) > tolerance)
         {
             ARM_COMPUTE_TEST_INFO("input = " << in_val);
             ARM_COMPUTE_TEST_INFO("output = " << out_val);
             ARM_COMPUTE_TEST_INFO("reference = " << ref_val[i]);
             ARM_COMPUTE_TEST_INFO("tolerance = " << tolerance);
             ARM_COMPUTE_TEST_INFO((std::abs(static_cast<float>(out_val) - ref_val[i]) <= tolerance));
             ++num_mismatches;
         }
     }
     ARM_COMPUTE_EXPECT(num_mismatches == expected_failures, framework::LogLevel::ERRORS);
 }
DATA_TEST_CASE (Configuration , framework::DatasetMode::ALL , combine(combine(concat(datasets::SmallShapes(), datasets::LargeShapes()), CNNDataTypes), framework::dataset::make("InPlace",{false, true})) , shape , data_type , in_place)
Definition at line 114 of file ActivationLayer.cpp.
                                                                                                                                                                             { false, true })),
                shape, data_type, in_place)
 {
     // Set fixed point position data type allowed
     const int fixed_point_position = is_data_type_fixed_point(data_type) ? 3 : 0;
     // Create tensors
     CLTensor src = create_tensor<CLTensor>(shape, data_type, 1, fixed_point_position);
     CLTensor dst = create_tensor<CLTensor>(shape, data_type, 1, fixed_point_position);
     ARM_COMPUTE_EXPECT(src.info()->is_resizable(), framework::LogLevel::ERRORS);
     ARM_COMPUTE_EXPECT(dst.info()->is_resizable(), framework::LogLevel::ERRORS);
     // Create and configure function
     CLActivationLayer act_layer;
     if(in_place)
     {
         act_layer.configure(&src, nullptr, ActivationLayerInfo(ActivationLayerInfo::ActivationFunction::ABS));
     }
     else
     {
         act_layer.configure(&src, &dst, ActivationLayerInfo(ActivationLayerInfo::ActivationFunction::ABS));
     }
     // Validate valid region
     const ValidRegion valid_region = shape_to_valid_region(shape);
     validate(src.info()->valid_region(), valid_region);
     if(!in_place)
     {
         validate(dst.info()->valid_region(), valid_region);
     }
     // Validate padding
     const int         step    = 16 / arm_compute::data_size_from_type(data_type);
     const PaddingSize padding = PaddingCalculator(shape.x(), step).required_padding();
     validate(src.info()->padding(), padding);
     if(!in_place)
     {
         validate(dst.info()->padding(), padding);
     }
 }
DATA_TEST_CASE (Configuration , framework::DatasetMode::ALL , combine(combine(combine(framework::dataset::concat(datasets::SmallShapes(), datasets::LargeShapes()), framework::dataset::make("DataType",{DataType::QS8, DataType::QS16})),framework::dataset::make("ConvertPolicy",{ConvertPolicy::SATURATE, ConvertPolicy::WRAP})),DepthConvertFixedPointQuantizedDataset) , shape , dt , policy , fixed_point_position)
Definition at line 371 of file DepthConvert.cpp.
References arm_compute::QS16, and arm_compute::QS8.
                                                                                                                                                                                       { DataType::QS8, DataType::QS16 })),
                                                                            framework::dataset::make("ConvertPolicy", { ConvertPolicy::SATURATE, ConvertPolicy::WRAP })),
                                                                    DepthConvertFixedPointQuantizedDataset),
                shape, dt, policy, fixed_point_position)
 {
     int shift = 0;
     // Create tensors
     CLTensor src = create_tensor<CLTensor>(shape, dt, 1, fixed_point_position);
     CLTensor dst = create_tensor<CLTensor>(shape, DataType::F32, 1, fixed_point_position);
     // Create and Configure function
     CLDepthConvert depth_convert;
     depth_convert.configure(&src, &dst, policy, shift);
     // Validate valid region
     const ValidRegion valid_region = shape_to_valid_region(shape);
     validate(dst.info()->valid_region(), valid_region);
     // Validate padding
     const PaddingSize padding = PaddingCalculator(shape.x(), 16).required_padding();
     validate(src.info()->padding(), padding);
     validate(dst.info()->padding(), padding);
 }
arm_compute::test::validation::DISABLED_FIXTURE_DATA_TEST_CASE (RunLarge , NEWarpAffineFixture< uint8_t > , framework::DatasetMode::NIGHTLY , combine(combine(combine(datasets::LargeShapes(), framework::dataset::make("DataType",DataType::U8)),framework::dataset::make("InterpolationPolicy",{InterpolationPolicy::NEAREST_NEIGHBOR, InterpolationPolicy::BILINEAR})),datasets::BorderModes()))
Definition at line 108 of file WarpAffine.cpp.
References arm_compute::BILINEAR, and arm_compute::NEAREST_NEIGHBOR.
                                                                                                                                                              { InterpolationPolicy::NEAREST_NEIGHBOR, InterpolationPolicy::BILINEAR })),
                                                                                                                  datasets::BorderModes()))
 {
     // Validate output
     validate(Accessor(_target), _reference, _valid_mask, tolerance, 0.02f);
 }
void arm_compute::test::validation::fill_lookuptable (T && table)
Helper function to fill the Lut random by a ILutAccessor.
Parameters
[in,out] table Accessor at the Lut.
Definition at line 169 of file Helpers.h.
References arm_compute::test::library, arm_compute::test::fixed_point_arithmetic::detail::max(), and arm_compute::test::fixed_point_arithmetic::detail::min().
 {
     std::mt19937                                          generator(library->seed());
     std::uniform_int_distribution<typename T::value_type> distribution(std::numeric_limits<typename T::value_type>::min(), std::numeric_limits<typename T::value_type>::max());
     for(int i = std::numeric_limits<typename T::value_type>::min(); i <= std::numeric_limits<typename T::value_type>::max(); i++)
     {
         table[i] = distribution(generator);
     }
 }
void fill_mask_from_pattern (uint8_t * mask, int cols, int rows, MatrixPattern pattern)
Fill mask with the corresponding given pattern.
Parameters
[in,out] mask Mask to be filled according to pattern
[in] cols Columns (width) of mask
[in] rows Rows (height) of mask
[in] pattern Pattern to fill the mask according to
Definition at line 32 of file Helpers.cpp.
References arm_compute::BOX, arm_compute::CROSS, arm_compute::DISK, arm_compute::test::library, and arm_compute::OTHER.
Referenced by NonLinearFilterValidationFixture< TensorType, AccessorType, FunctionType, T >::setup().
 {
     unsigned int                v = 0;
     std::mt19937                gen(library->seed());
     std::bernoulli_distribution dist(0.5);
     for(int r = 0; r < rows; ++r)
     {
         for(int c = 0; c < cols; ++c, ++v)
         {
             uint8_t val = 0;
             switch(pattern)
             {
                 case MatrixPattern::BOX:
                     val = 255;
                     break;
                 case MatrixPattern::CROSS:
                     val = ((r == (rows / 2)) || (c == (cols / 2))) ? 255 : 0;
                     break;
                 case MatrixPattern::DISK:
                     val = (((r - rows / 2.0f + 0.5f) * (r - rows / 2.0f + 0.5f)) / ((rows / 2.0f) * (rows / 2.0f)) + ((c - cols / 2.0f + 0.5f) * (c - cols / 2.0f + 0.5f)) / ((cols / 2.0f) *
                             (cols / 2.0f))) <= 1.0f ? 255 : 0;
                     break;
                 case MatrixPattern::OTHER:
                     val = (dist(gen) ? 0 : 255);
                     break;
                 default:
                     return;
             }
             mask[v] = val;
         }
     }
     if(pattern == MatrixPattern::OTHER)
     {
         std::uniform_int_distribution<uint8_t> distribution_u8(0, ((cols * rows) - 1));
         mask[distribution_u8(gen)] = 255;
     }
 }
void arm_compute::test::validation::fill_warp_matrix (std::array< float, SIZE > & matrix) inline
Fill matrix random.
Parameters
[in,out] matrix Matrix
Definition at line 109 of file Utils.h.
References arm_compute::test::library.
 {
     std::mt19937                          gen(library.get()->seed());
     std::uniform_real_distribution<float> dist(-1, 1);
     for(auto &x : matrix)
     {
         x = dist(gen);
     }
     if(SIZE == 9)
     {
         // This is only used in Warp Perspective, we set M[3][3] = 1 so that Z0 is not 0 and we avoid division by 0.
         matrix[8] = 1.f;
     }
 }
arm_compute::test::validation::FIXTURE_DATA_TEST_CASE (RunSmall , NEFloorFixture< float > , framework::DatasetMode::PRECOMMIT , combine(datasets::SmallShapes(), framework::dataset::make("DataType", DataType::F32)))
Definition at line 50 of file Floor.cpp.
References validate().
 {
     // Validate output
     validate(Accessor(_target), _reference);
 }
arm_compute::test::validation::FIXTURE_DATA_TEST_CASE (RunSmall , CLFloorFixture< float > , framework::DatasetMode::PRECOMMIT , combine(datasets::SmallShapes(), framework::dataset::make("DataType", DataType::F32)))
Definition at line 50 of file Floor.cpp.
References validate().
 {
     // Validate output
     validate(CLAccessor(_target), _reference);
 }
arm_compute::test::validation::FIXTURE_DATA_TEST_CASE (RunSmall , CLDepthConcatenateLayerFixture< half > , framework::DatasetMode::PRECOMMIT , combine(datasets::Small2DShapes(), framework::dataset::make("DataType",DataType::F16)))
Definition at line 50 of file DepthConcatenateLayer.cpp.
References validate().
 {
     // Validate output
     validate(CLAccessor(_target), _reference);
 }
arm_compute::test::validation::FIXTURE_DATA_TEST_CASE (RunSmall , NEDepthConcatenateLayerFixture< half > , framework::DatasetMode::PRECOMMIT , combine(datasets::Small2DShapes(), framework::dataset::make("DataType",DataType::F16)))
Definition at line 51 of file DepthConcatenateLayer.cpp.
References validate().
 {
     // Validate output
     validate(Accessor(_target), _reference);
 }
arm_compute::test::validation::FIXTURE_DATA_TEST_CASE (RunSmall , NEFlattenLayerFixture< float > , framework::DatasetMode::ALL , combine(framework::dataset::concat(datasets::Small3DShapes(), datasets::Small4DShapes()),framework::dataset::make("DataType", DataType::F32)))
Definition at line 51 of file Flatten.cpp.
References validate().
 {
     // Validate output
     validate(Accessor(_target), _reference);
 }
arm_compute::test::validation::FIXTURE_DATA_TEST_CASE (RunSmall , CLFlattenLayerFixture< float > , framework::DatasetMode::ALL , combine(framework::dataset::concat(datasets::Small3DShapes(), datasets::Small4DShapes()),framework::dataset::make("DataType", DataType::F32)))
Definition at line 51 of file Flatten.cpp.
References validate().
 {
     // Validate output
     validate(CLAccessor(_target), _reference);
 }
arm_compute::test::validation::FIXTURE_DATA_TEST_CASE (RunSmall , CLReshapeLayerFixture< float > , framework::DatasetMode::ALL , combine(datasets::SmallReshapeLayerDataset(), framework::dataset::make("DataType", DataType::F32)))
Definition at line 52 of file ReshapeLayer.cpp.
References validate().
 {
     // Validate output
     validate(CLAccessor(_target), _reference);
 }
arm_compute::test::validation::FIXTURE_DATA_TEST_CASE (RunSmall , NEReshapeLayerFixture< float > , framework::DatasetMode::ALL , combine(datasets::SmallReshapeLayerDataset(), framework::dataset::make("DataType", DataType::F32)))
Definition at line 52 of file ReshapeLayer.cpp.
References validate().
 {
     // Validate output
     validate(Accessor(_target), _reference);
 }
arm_compute::test::validation::FIXTURE_DATA_TEST_CASE (RunLarge , NEFloorFixture< float > , framework::DatasetMode::NIGHTLY , combine(datasets::LargeShapes(), framework::dataset::make("DataType", DataType::F32)))
Definition at line 55 of file Floor.cpp.
References validate().
 {
     // Validate output
     validate(Accessor(_target), _reference);
 }
arm_compute::test::validation::FIXTURE_DATA_TEST_CASE (RunLarge , CLFloorFixture< float > , framework::DatasetMode::NIGHTLY , combine(datasets::LargeShapes(), framework::dataset::make("DataType", DataType::F32)))
Definition at line 55 of file Floor.cpp.
References validate().
 {
     // Validate output
     validate(CLAccessor(_target), _reference);
 }
arm_compute::test::validation::FIXTURE_DATA_TEST_CASE (RunSmall , NEL2NormalizeFixture< float > , framework::DatasetMode::PRECOMMIT , combine(combine(combine(datasets::SmallShapes(), framework::dataset::make("DataType", DataType::F32)), framework::dataset::make("Axis",{0})), framework::dataset::make("Epsilon",{1e-12})))
Definition at line 56 of file L2Normalize.cpp.
                                                                                                                                                    { 0 })), framework::dataset::make("Epsilon", { 1e-12 })))
 {
     // Validate output
     validate(Accessor(_target), _reference, tolerance_f32);
 }
arm_compute::test::validation::FIXTURE_DATA_TEST_CASE (RunLarge , CLDepthConcatenateLayerFixture< half > , framework::DatasetMode::NIGHTLY , combine(datasets::Large2DShapes(), framework::dataset::make("DataType",DataType::F16)))
Definition at line 56 of file DepthConcatenateLayer.cpp.
References validate().
 {
     // Validate output
     validate(CLAccessor(_target), _reference);
 }
arm_compute::test::validation::FIXTURE_DATA_TEST_CASE (RunLarge , NEDepthConcatenateLayerFixture< half > , framework::DatasetMode::NIGHTLY , combine(datasets::DepthConcatenateShapes(), framework::dataset::make("DataType",DataType::F16)))
Definition at line 57 of file DepthConcatenateLayer.cpp.
References validate().
 {
     // Validate output
     validate(Accessor(_target), _reference);
 }
arm_compute::test::validation::FIXTURE_DATA_TEST_CASE (RunLarge , NEFlattenLayerFixture< float > , framework::DatasetMode::NIGHTLY , combine(framework::dataset::concat(datasets::Large3DShapes(), datasets::Large4DShapes()),framework::dataset::make("DataType", DataType::F32)))
Definition at line 57 of file Flatten.cpp.
References validate().
 {
     // Validate output
     validate(Accessor(_target), _reference);
 }
arm_compute::test::validation::FIXTURE_DATA_TEST_CASE (RunSmall , NEGEMMLowpOffsetFixture , framework::DatasetMode::PRECOMMIT , data_mnk * data_offsets)
Definition at line 57 of file GEMMLowp.cpp.
References validate().
 {
     // Validate output
     validate(Accessor(_target), _reference, tolerance_f);
 }
arm_compute::test::validation::FIXTURE_DATA_TEST_CASE (RunSmall , NEReductionOperationFixture< float > , framework::DatasetMode::PRECOMMIT , combine(combine(combine(datasets::SmallShapes(), framework::dataset::make("DataType", DataType::F32)), framework::dataset::make("Axis",{0})), datasets::ReductionOperations()))
Definition at line 57 of file ReductionOperation.cpp.
                                                                                                                                                    { 0 })), datasets::ReductionOperations()))
 {
     // Validate output
     validate(Accessor(_target), _reference, tolerance_f32);
 }
arm_compute::test::validation::FIXTURE_DATA_TEST_CASE (RunLarge , CLFlattenLayerFixture< float > , framework::DatasetMode::NIGHTLY , combine(framework::dataset::concat(datasets::Large3DShapes(), datasets::Large4DShapes()),framework::dataset::make("DataType", DataType::F32)))
Definition at line 57 of file Flatten.cpp.
References validate().
 {
     // Validate output
     validate(CLAccessor(_target), _reference);
 }
arm_compute::test::validation::FIXTURE_DATA_TEST_CASE (RunSmall , CLL2NormalizeFixture< float > , framework::DatasetMode::PRECOMMIT , combine(combine(combine(datasets::SmallShapes(), framework::dataset::make("DataType", DataType::F32)), framework::dataset::make("Axis",{0})), framework::dataset::make("Epsilon",{1e-12})))
Definition at line 58 of file L2Normalize.cpp.
                                                                                                                                                    { 0 })), framework::dataset::make("Epsilon", { 1e-12 })))
 {
     // Validate output
     validate(CLAccessor(_target), _reference, tolerance_f32);
 }
arm_compute::test::validation::FIXTURE_DATA_TEST_CASE (RunSmall , CLReductionOperationFixture< float > , framework::DatasetMode::PRECOMMIT , combine(combine(combine(datasets::LargeShapes(), framework::dataset::make("DataType", DataType::F32)), framework::dataset::make("Axis",{0})), datasets::ReductionOperations()))
Definition at line 58 of file ReductionOperation.cpp.
                                                                                                                                                    { 0 })), datasets::ReductionOperations()))
 {
     // Validate output
     validate(CLAccessor(_target), _reference, tolerance_f32);
 }
arm_compute::test::validation::FIXTURE_DATA_TEST_CASE (RunSmall , CLFixedPointFixture< int8_t > , framework::DatasetMode::ALL , combine(combine(combine(datasets::Small1DShape(), framework::dataset::make("DataType",DataType::QS8)),framework::dataset::make("FixedPointOp", FixedPointOp::EXP)),framework::dataset::make("FractionalBits", 1, 6)))
Definition at line 59 of file FixedPoint_QS8.cpp.
References validate().
 {
     // Validate output
     validate(CLAccessor(_target), _reference, tolerance_exp);
 }
arm_compute::test::validation::FIXTURE_DATA_TEST_CASE (RunSmall , CLReshapeLayerFixture< half > , framework::DatasetMode::ALL , combine(datasets::SmallReshapeLayerDataset(), framework::dataset::make("DataType",DataType::F16)))
Definition at line 60 of file ReshapeLayer.cpp.
References validate().
 {
     // Validate output
     validate(CLAccessor(_target), _reference);
 }
arm_compute::test::validation::FIXTURE_DATA_TEST_CASE (RunGlobalPooling , NEGlobalPoolingLayerFixture< float > , framework::DatasetMode::ALL , combine(GlobalPoolingLayerDataset, framework::dataset::make("DataType", DataType::F32)))
Definition at line 61 of file GlobalPoolingLayer.cpp.
References validate().
 {
     // Validate output
     validate(Accessor(_target), _reference, tolerance_f32);
 }
arm_compute::test::validation::FIXTURE_DATA_TEST_CASE (RunGlobalPooling , CLGlobalPoolingLayerFixture< float > , framework::DatasetMode::ALL , combine(GlobalPoolingLayerDataset, framework::dataset::make("DataType", DataType::F32)))
Definition at line 62 of file GlobalPoolingLayer.cpp.
References validate().
 {
     // Validate output
     validate(CLAccessor(_target), _reference, tolerance_f32);
 }
arm_compute::test::validation::FIXTURE_DATA_TEST_CASE (RunSmall , NEReshapeLayerFixture< int8_t > , framework::DatasetMode::ALL , combine(datasets::SmallReshapeLayerDataset(), framework::dataset::make("DataType", DataType::S8)))
Definition at line 62 of file ReshapeLayer.cpp.
References validate().
 {
     // Validate output
     validate(Accessor(_target), _reference);
 }
arm_compute::test::validation::FIXTURE_DATA_TEST_CASE (RunLarge , NEL2NormalizeFixture< float > , framework::DatasetMode::NIGHTLY , combine(combine(combine(datasets::LargeShapes(), framework::dataset::make("DataType", DataType::F32)), framework::dataset::make("Axis",{0})), framework::dataset::make("Epsilon",{1e-12})))
Definition at line 63 of file L2Normalize.cpp.
                                                                                                                                                    { 0 })), framework::dataset::make("Epsilon", { 1e-12 })))
 {
     // Validate output
     validate(Accessor(_target), _reference, tolerance_f32);
 }
arm_compute::test::validation::FIXTURE_DATA_TEST_CASE (RunLarge , NEReductionOperationFixture< float > , framework::DatasetMode::NIGHTLY , combine(combine(combine(datasets::LargeShapes(), framework::dataset::make("DataType", DataType::F32)), framework::dataset::make("Axis",{0})), datasets::ReductionOperations()))
Definition at line 63 of file ReductionOperation.cpp.
                                                                                                                                                    { 0 })), datasets::ReductionOperations()))
 {
     // Validate output
     validate(Accessor(_target), _reference, tolerance_f32);
 }
arm_compute::test::validation::FIXTURE_DATA_TEST_CASE (RunLarge , CLL2NormalizeFixture< float > , framework::DatasetMode::NIGHTLY , combine(combine(combine(datasets::LargeShapes(), framework::dataset::make("DataType", DataType::F32)), framework::dataset::make("Axis",{0})), framework::dataset::make("Epsilon",{1e-12})))
Definition at line 64 of file L2Normalize.cpp.
                                                                                                                                                    { 0 })), framework::dataset::make("Epsilon", { 1e-12 })))
 {
     // Validate output
     validate(CLAccessor(_target), _reference, tolerance_f32);
 }
arm_compute::test::validation::FIXTURE_DATA_TEST_CASE (RunSmall , NEFixedPointFixture< int8_t > , framework::DatasetMode::ALL , combine(combine(combine(datasets::Small1DShape(), framework::dataset::make("DataType",DataType::QS8)),framework::dataset::make("FixedPointOp", FixedPointOp::EXP)),framework::dataset::make("FractionalBits", 1, 7)))
Definition at line 64 of file FixedPoint.cpp.
References validate().
 {
     // Validate output
     validate(Accessor(_target), _reference, tolerance_exp_qs8, 0);
 }
arm_compute::test::validation::FIXTURE_DATA_TEST_CASE (RunLarge , CLReductionOperationFixture< float > , framework::DatasetMode::NIGHTLY , combine(combine(combine(datasets::LargeShapes(), framework::dataset::make("DataType", DataType::F32)), framework::dataset::make("Axis",{0})), datasets::ReductionOperations()))
Definition at line 64 of file ReductionOperation.cpp.
                                                                                                                                                    { 0 })), datasets::ReductionOperations()))
 {
     // Validate output
     validate(CLAccessor(_target), _reference, tolerance_f32);
 }
arm_compute::test::validation::FIXTURE_DATA_TEST_CASE (RunSmall , CLDepthConcatenateLayerFixture< float > , framework::DatasetMode::PRECOMMIT , combine(datasets::Small2DShapes(), framework::dataset::make("DataType",DataType::F32)))
Definition at line 65 of file DepthConcatenateLayer.cpp.
References validate().
 {
     // Validate output
     validate(CLAccessor(_target), _reference);
 }
arm_compute::test::validation::FIXTURE_DATA_TEST_CASE (RunSmall , CLFlattenLayerFixture< half > , framework::DatasetMode::ALL , combine(framework::dataset::concat(datasets::Small3DShapes(), datasets::Small4DShapes()),framework::dataset::make("DataType", DataType::F16)))
Definition at line 66 of file Flatten.cpp.
References validate().
 {
     // Validate output
     validate(CLAccessor(_target), _reference);
 }
arm_compute::test::validation::FIXTURE_DATA_TEST_CASE (RunSmall , CLIntegralImageFixture< uint8_t > , framework::DatasetMode::PRECOMMIT , combine(datasets::SmallShapes(), framework::dataset::make("DataType",DataType::U8)))
Definition at line 67 of file IntegralImage.cpp.
References validate().
 {
     // Validate output
     validate(CLAccessor(_target), _reference);
 }
arm_compute::test::validation::FIXTURE_DATA_TEST_CASE (RunSmall , NEDepthConcatenateLayerFixture< float > , framework::DatasetMode::PRECOMMIT , combine(datasets::Small2DShapes(), framework::dataset::make("DataType",DataType::F32)))
Definition at line 67 of file DepthConcatenateLayer.cpp.
References validate().
 {
     // Validate output
     validate(Accessor(_target), _reference);
 }
arm_compute::test::validation::FIXTURE_DATA_TEST_CASE (RunSmall , NEFlattenLayerFixture< half > , framework::DatasetMode::ALL , combine(framework::dataset::concat(datasets::Small3DShapes(), datasets::Small4DShapes()),framework::dataset::make("DataType", DataType::F16)))
Definition at line 67 of file Flatten.cpp.
References validate().
 {
     // Validate output
     validate(Accessor(_target), _reference);
 }
arm_compute::test::validation::FIXTURE_DATA_TEST_CASE (RunSmall , CLNormalizationLayerFixture< half > , framework::DatasetMode::PRECOMMIT , combine(NormalizationDataset, framework::dataset::make("DataType", DataType::F16)))
Definition at line 68 of file NormalizationLayer.cpp.
References validate().
 {
     // Validate output
     validate(CLAccessor(_target), _reference, tolerance_f16);
 }
arm_compute::test::validation::FIXTURE_DATA_TEST_CASE (RunSmall , CLPoolingLayerFixture< float > , framework::DatasetMode::ALL , combine(datasets::SmallShapes(), combine(PoolingLayerDatasetFP, framework::dataset::make("DataType",DataType::F32))))
Definition at line 68 of file PoolingLayer.cpp.
References validate().
 {
     // Validate output
     validate(CLAccessor(_target), _reference, tolerance_f32);
 }
arm_compute::test::validation::FIXTURE_DATA_TEST_CASE (RunSmall , NEIntegralImageFixture< uint8_t > , framework::DatasetMode::PRECOMMIT , combine(datasets::SmallShapes(), framework::dataset::make("DataType",DataType::U8)))
Definition at line 69 of file IntegralImage.cpp.
References validate().
 {
     // Validate output
     validate(Accessor(_target), _reference);
 }
arm_compute::test::validation::FIXTURE_DATA_TEST_CASE (RunSmall , NENormalizationLayerFixture< half > , framework::DatasetMode::PRECOMMIT , combine(NormalizationDataset, framework::dataset::make("DataType", DataType::F16)))
Definition at line 69 of file NormalizationLayer.cpp.
References validate().
 {
     // Validate output
     validate(Accessor(_target), _reference, tolerance_f16);
 }
arm_compute::test::validation::FIXTURE_DATA_TEST_CASE (RunGlobalPooling , CLGlobalPoolingLayerFixture< half > , framework::DatasetMode::ALL , combine(GlobalPoolingLayerDataset, framework::dataset::make("DataType",DataType::F16)))
Definition at line 70 of file GlobalPoolingLayer.cpp.
References validate().
 {
     // Validate output
     validate(CLAccessor(_target), _reference, tolerance_f16);
 }
arm_compute::test::validation::FIXTURE_DATA_TEST_CASE (RunSmall , NEMeanStdDevFixture< uint8_t > , framework::DatasetMode::PRECOMMIT , combine(datasets::Small2DShapes(), framework::dataset::make("DataType",DataType::U8)))
Definition at line 70 of file MeanStdDev.cpp.
References validate().
 {
     // Validate mean output
     validate(_target.first, _reference.first);
     // Validate std_dev output
     validate(_target.second, _reference.second, tolerance_rel_high_error);
 }
arm_compute::test::validation::FIXTURE_DATA_TEST_CASE (RunSmall , CLFixedPointFixture< int8_t > , framework::DatasetMode::ALL , combine(combine(combine(datasets::Small1DShape(), framework::dataset::make("DataType",DataType::QS8)),framework::dataset::make("FixedPointOp", FixedPointOp::LOG)),framework::dataset::make("FractionalBits", 3, 6)))
Definition at line 70 of file FixedPoint_QS8.cpp.
References validate().
 {
     // Validate output
     validate(CLAccessor(_target), _reference, tolerance_log);
 }
arm_compute::test::validation::FIXTURE_DATA_TEST_CASE (RunSmall , NEPoolingLayerFixture< float > , framework::DatasetMode::ALL , combine(datasets::SmallShapes(), combine(PoolingLayerDatasetFP, framework::dataset::make("DataType",DataType::F32))))
Definition at line 70 of file PoolingLayer.cpp.
References validate().
 {
     // Validate output
     validate(Accessor(_target), _reference, tolerance_f32);
 }
arm_compute::test::validation::FIXTURE_DATA_TEST_CASE (RunSmall , NEReshapeLayerFixture< int16_t > , framework::DatasetMode::ALL , combine(datasets::SmallReshapeLayerDataset(), framework::dataset::make("DataType", DataType::S16)))
Definition at line 70 of file ReshapeLayer.cpp.
References validate().
 {
     // Validate output
     validate(Accessor(_target), _reference);
 }
arm_compute::test::validation::FIXTURE_DATA_TEST_CASE (RunSmall , CLThresholdFixture< uint8_t > , framework::DatasetMode::PRECOMMIT , combine(combine(datasets::SmallShapes(), datasets::MixedThresholdDataset()),framework::dataset::make("DataType",DataType::U8)))
Definition at line 70 of file Threshold.cpp.
References validate().
 {
     // Validate output
     validate(CLAccessor(_target), _reference);
 }
arm_compute::test::validation::FIXTURE_DATA_TEST_CASE (RunSmall , CLReshapeLayerFixture< int8_t > , framework::DatasetMode::ALL , combine(datasets::SmallReshapeLayerDataset(), framework::dataset::make("DataType", DataType::S8)))
Definition at line 71 of file ReshapeLayer.cpp.
References validate().
 {
     // Validate output
     validate(CLAccessor(_target), _reference);
 }
arm_compute::test::validation::FIXTURE_DATA_TEST_CASE (RunSmall , ThresholdFixture< uint8_t > , framework::DatasetMode::PRECOMMIT , combine(combine(datasets::SmallShapes(), datasets::MixedThresholdDataset()),framework::dataset::make("DataType",DataType::U8)))
Definition at line 71 of file Threshold.cpp.
References validate().
 {
     // Validate output
     validate(Accessor(_target), _reference);
 }
arm_compute::test::validation::FIXTURE_DATA_TEST_CASE (RunLarge , CLDepthConcatenateLayerFixture< float > , framework::DatasetMode::NIGHTLY , combine(datasets::DepthConcatenateShapes(), framework::dataset::make("DataType",DataType::F32)))
Definition at line 71 of file DepthConcatenateLayer.cpp.
References validate().
 {
     // Validate output
     validate(CLAccessor(_target), _reference);
 }
arm_compute::test::validation::FIXTURE_DATA_TEST_CASE (RunLarge , CLFlattenLayerFixture< half > , framework::DatasetMode::NIGHTLY , combine(framework::dataset::concat(datasets::Large3DShapes(), datasets::Large4DShapes()),framework::dataset::make("DataType", DataType::F16)))
Definition at line 72 of file Flatten.cpp.
References validate().
 {
     // Validate output
     validate(CLAccessor(_target), _reference);
 }
arm_compute::test::validation::FIXTURE_DATA_TEST_CASE (RunLarge , CLIntegralImageFixture< uint8_t > , framework::DatasetMode::NIGHTLY , combine(datasets::LargeShapes(), framework::dataset::make("DataType",DataType::U8)))
Definition at line 73 of file IntegralImage.cpp.
References validate().
 {
     // Validate output
     validate(CLAccessor(_target), _reference);
 }
arm_compute::test::validation::FIXTURE_DATA_TEST_CASE (RunSmall , NEBitwiseNotFixture< uint8_t > , framework::DatasetMode::PRECOMMIT , combine(datasets::SmallShapes(), framework::dataset::make("DataType",DataType::U8)))
Definition at line 73 of file BitwiseNot.cpp.
References validate().
 {
     // Validate output
     validate(Accessor(_target), _reference);
 }
arm_compute::test::validation::FIXTURE_DATA_TEST_CASE (RunLarge , NEDepthConcatenateLayerFixture< float > , framework::DatasetMode::NIGHTLY , combine(datasets::DepthConcatenateShapes(), framework::dataset::make("DataType",DataType::F32)))
Definition at line 73 of file DepthConcatenateLayer.cpp.
References validate().
 {
     // Validate output
     validate(Accessor(_target), _reference);
 }
arm_compute::test::validation::FIXTURE_DATA_TEST_CASE (RunLarge , CLNormalizationLayerFixture< half > , framework::DatasetMode::NIGHTLY , combine(NormalizationDataset, framework::dataset::make("DataType", DataType::F16)))
Definition at line 73 of file NormalizationLayer.cpp.
References validate().
 {
     // Validate output
     validate(CLAccessor(_target), _reference, tolerance_f16);
 }
arm_compute::test::validation::FIXTURE_DATA_TEST_CASE (RunLarge , NEFlattenLayerFixture< half > , framework::DatasetMode::NIGHTLY , combine(framework::dataset::concat(datasets::Large3DShapes(), datasets::Large4DShapes()),framework::dataset::make("DataType", DataType::F16)))
Definition at line 73 of file Flatten.cpp.
References validate().
 {
     // Validate output
     validate(Accessor(_target), _reference);
 }
arm_compute::test::validation::FIXTURE_DATA_TEST_CASE (RunSmall , CLBitwiseNotFixture< uint8_t > , framework::DatasetMode::PRECOMMIT , combine(datasets::SmallShapes(), framework::dataset::make("DataType",DataType::U8)))
Definition at line 73 of file BitwiseNot.cpp.
References validate().
 {
     // Validate output
     validate(CLAccessor(_target), _reference);
 }
arm_compute::test::validation::FIXTURE_DATA_TEST_CASE (RunSmall , CLMeanStdDevFixture< uint8_t > , framework::DatasetMode::PRECOMMIT , combine(datasets::Small2DShapes(), framework::dataset::make("DataType",DataType::U8)))
Definition at line 74 of file MeanStdDev.cpp.
References validate().
 {
     // Validate mean output
     validate(_target.first, _reference.first);
     // Validate std_dev output
     validate(_target.second, _reference.second, tolerance_rel_high_error);
 }
arm_compute::test::validation::FIXTURE_DATA_TEST_CASE (RunSmall , CLMinMaxLocationFixture< uint8_t > , framework::DatasetMode::PRECOMMIT , combine(datasets::Small2DShapes(), framework::dataset::make("DataType",DataType::U8)))
Definition at line 74 of file MinMaxLocation.cpp.
References validate_min_max_loc().
 {
     validate_min_max_loc(_target, _reference);
 }
arm_compute::test::validation::FIXTURE_DATA_TEST_CASE (RunLarge , CLPoolingLayerFixture< float > , framework::DatasetMode::NIGHTLY , combine(datasets::LargeShapes(), combine(PoolingLayerDatasetFP, framework::dataset::make("DataType",DataType::F32))))
Definition at line 74 of file PoolingLayer.cpp.
References validate().
 {
     // Validate output
     validate(CLAccessor(_target), _reference, tolerance_f32);
 }
arm_compute::test::validation::FIXTURE_DATA_TEST_CASE (RunLarge , NENormalizationLayerFixture< half > , framework::DatasetMode::NIGHTLY , combine(NormalizationDataset, framework::dataset::make("DataType", DataType::F16)))
Definition at line 74 of file NormalizationLayer.cpp.
References validate().
 {
     // Validate output
     validate(Accessor(_target), _reference, tolerance_f16);
 }
arm_compute::test::validation::FIXTURE_DATA_TEST_CASE (RunSmall , NEFixedPointFixture< int8_t > , framework::DatasetMode::ALL , combine(combine(combine(datasets::Small1DShape(), framework::dataset::make("DataType",DataType::QS8)),framework::dataset::make("FixedPointOp", FixedPointOp::INV_SQRT)),framework::dataset::make("FractionalBits", 1, 6)))
Definition at line 75 of file FixedPoint.cpp.
References validate().
 {
     // Validate output
     validate(Accessor(_target), _reference, tolerance_invsqrt_qs8, 0);
 }
arm_compute::test::validation::FIXTURE_DATA_TEST_CASE (RunLarge , NEIntegralImageFixture< uint8_t > , framework::DatasetMode::NIGHTLY , combine(datasets::LargeShapes(), framework::dataset::make("DataType",DataType::U8)))
Definition at line 75 of file IntegralImage.cpp.
References validate().
 {
     // Validate output
     validate(Accessor(_target), _reference);
 }
arm_compute::test::validation::FIXTURE_DATA_TEST_CASE (RunSmall , NEMinMaxLocationFixture< uint8_t > , framework::DatasetMode::PRECOMMIT , combine(datasets::Small2DShapes(), framework::dataset::make("DataType",DataType::U8)))
Definition at line 75 of file MinMaxLocation.cpp.
References validate_min_max_loc().
 {
     validate_min_max_loc(_target, _reference);
 }
arm_compute::test::validation::FIXTURE_DATA_TEST_CASE (RunLarge , NEPoolingLayerFixture< float > , framework::DatasetMode::NIGHTLY , combine(datasets::LargeShapes(), combine(PoolingLayerDatasetFP, framework::dataset::make("DataType",DataType::F32))))
Definition at line 76 of file PoolingLayer.cpp.
References validate().
 {
     // Validate output
     validate(Accessor(_target), _reference, tolerance_f32);
 }
arm_compute::test::validation::FIXTURE_DATA_TEST_CASE (RunSmall , NEBitwiseAndFixture< uint8_t > , framework::DatasetMode::PRECOMMIT , combine(datasets::SmallShapes(), framework::dataset::make("DataType",DataType::U8)))
Definition at line 77 of file BitwiseAnd.cpp.
References validate().
 {
     // Validate output
     validate(Accessor(_target), _reference);
 }
arm_compute::test::validation::FIXTURE_DATA_TEST_CASE (RunSmall , NEBitwiseOrFixture< uint8_t > , framework::DatasetMode::PRECOMMIT , combine(datasets::SmallShapes(), framework::dataset::make("DataType",DataType::U8)))
Definition at line 77 of file BitwiseOr.cpp.
References validate().
 {
     // Validate output
     validate(Accessor(_target), _reference);
 }
arm_compute::test::validation::FIXTURE_DATA_TEST_CASE (RunSmall , NEBitwiseXorFixture< uint8_t > , framework::DatasetMode::PRECOMMIT , combine(datasets::SmallShapes(), framework::dataset::make("DataType",DataType::U8)))
Definition at line 77 of file BitwiseXor.cpp.
References validate().
 {
     // Validate output
     validate(Accessor(_target), _reference);
 }
arm_compute::test::validation::FIXTURE_DATA_TEST_CASE (RunSmall , CLBitwiseAndFixture< uint8_t > , framework::DatasetMode::PRECOMMIT , combine(datasets::SmallShapes(), framework::dataset::make("DataType",DataType::U8)))
Definition at line 77 of file BitwiseAnd.cpp.
References validate().
 {
     // Validate output
     validate(CLAccessor(_target), _reference);
 }
arm_compute::test::validation::FIXTURE_DATA_TEST_CASE (RunSmall , CLBitwiseOrFixture< uint8_t > , framework::DatasetMode::PRECOMMIT , combine(datasets::SmallShapes(), framework::dataset::make("DataType",DataType::U8)))
Definition at line 77 of file BitwiseOr.cpp.
References validate().
 {
     // Validate output
     validate(CLAccessor(_target), _reference);
 }
arm_compute::test::validation::FIXTURE_DATA_TEST_CASE (RunSmall , CLBitwiseXorFixture< uint8_t > , framework::DatasetMode::PRECOMMIT , combine(datasets::SmallShapes(), framework::dataset::make("DataType",DataType::U8)))
Definition at line 77 of file BitwiseXor.cpp.
References validate().
 {
     // Validate output
     validate(CLAccessor(_target), _reference);
 }
arm_compute::test::validation::FIXTURE_DATA_TEST_CASE (RunLarge , CLThresholdFixture< uint8_t > , framework::DatasetMode::NIGHTLY , combine(combine(datasets::LargeShapes(), datasets::MixedThresholdDataset()),framework::dataset::make("DataType",DataType::U8)))
Definition at line 78 of file Threshold.cpp.
References validate().
 {
     // Validate output
     validate(CLAccessor(_target), _reference);
 }
arm_compute::test::validation::FIXTURE_DATA_TEST_CASE (RunLarge , NEBitwiseNotFixture< uint8_t > , framework::DatasetMode::NIGHTLY , combine(datasets::LargeShapes(), framework::dataset::make("DataType",DataType::U8)))
Definition at line 79 of file BitwiseNot.cpp.
References validate().
 {
     // Validate output
     validate(Accessor(_target), _reference);
 }
arm_compute::test::validation::FIXTURE_DATA_TEST_CASE (RunLarge , CLBitwiseNotFixture< uint8_t > , framework::DatasetMode::NIGHTLY , combine(datasets::LargeShapes(), framework::dataset::make("DataType",DataType::U8)))
Definition at line 79 of file BitwiseNot.cpp.
References validate().
 {
     // Validate output
     validate(CLAccessor(_target), _reference);
 }
arm_compute::test::validation::FIXTURE_DATA_TEST_CASE (RunSmall , CLReshapeLayerFixture< int16_t > , framework::DatasetMode::ALL , combine(datasets::SmallReshapeLayerDataset(), framework::dataset::make("DataType", DataType::S16)))
Definition at line 79 of file ReshapeLayer.cpp.
References validate().
 {
     // Validate output
     validate(CLAccessor(_target), _reference);
 }
arm_compute::test::validation::FIXTURE_DATA_TEST_CASE (RunLarge , NEMeanStdDevFixture< uint8_t > , framework::DatasetMode::NIGHTLY , combine(datasets::Large2DShapes(), framework::dataset::make("DataType",DataType::U8)))
Definition at line 79 of file MeanStdDev.cpp.
References validate().
 {
     // Validate mean output
     validate(_target.first, _reference.first, tolerance_rel_low_error);
     // Validate std_dev output
     validate(_target.second, _reference.second, tolerance_rel_high_error);
 }
arm_compute::test::validation::FIXTURE_DATA_TEST_CASE (RunLarge , ThresholdFixture< uint8_t > , framework::DatasetMode::NIGHTLY , combine(combine(datasets::LargeShapes(), datasets::MixedThresholdDataset()),framework::dataset::make("DataType",DataType::U8)))
Definition at line 79 of file Threshold.cpp.
References validate().
 {
     // Validate output
     validate(Accessor(_target), _reference);
 }
arm_compute::test::validation::FIXTURE_DATA_TEST_CASE (RunLarge , CLMinMaxLocationFixture< uint8_t > , framework::DatasetMode::NIGHTLY , combine(datasets::Large2DShapes(), framework::dataset::make("DataType",DataType::U8)))
Definition at line 80 of file MinMaxLocation.cpp.
References validate_min_max_loc().
 {
     validate_min_max_loc(_target, _reference);
 }
arm_compute::test::validation::FIXTURE_DATA_TEST_CASE (RunSmall , CLNormalizationLayerFixture< float > , framework::DatasetMode::PRECOMMIT , combine(NormalizationDataset, framework::dataset::make("DataType", DataType::F32)))
Definition at line 81 of file NormalizationLayer.cpp.
References validate().
 {
     // Validate output
     validate(CLAccessor(_target), _reference, tolerance_f32);
 }
arm_compute::test::validation::FIXTURE_DATA_TEST_CASE (RunLarge , NEMinMaxLocationFixture< uint8_t > , framework::DatasetMode::NIGHTLY , combine(datasets::Large2DShapes(), framework::dataset::make("DataType",DataType::U8)))
Definition at line 81 of file MinMaxLocation.cpp.
References validate_min_max_loc().
 {
     validate_min_max_loc(_target, _reference);
 }
arm_compute::test::validation::FIXTURE_DATA_TEST_CASE (RunSmall , CLFixedPointFixture< int8_t > , framework::DatasetMode::ALL , combine(combine(combine(datasets::Small1DShape(), framework::dataset::make("DataType",DataType::QS8)),framework::dataset::make("FixedPointOp", FixedPointOp::INV_SQRT)),framework::dataset::make("FractionalBits", 1, 6)))
Definition at line 81 of file FixedPoint_QS8.cpp.
References validate().
 {
     // Validate output
     validate(CLAccessor(_target), _reference, tolerance_invsqrt);
 }
arm_compute::test::validation::FIXTURE_DATA_TEST_CASE (RunSmall , CLDepthConcatenateLayerFixture< int8_t > , framework::DatasetMode::PRECOMMIT , combine(datasets::Small2DShapes(),framework::dataset::make("DataType",DataType::QS8)))
Definition at line 82 of file DepthConcatenateLayer.cpp.
References validate().
 {
     // Validate output
     validate(CLAccessor(_target), _reference);
 }
arm_compute::test::validation::FIXTURE_DATA_TEST_CASE (Random , CLBatchNormalizationLayerFixture< float > , framework::DatasetMode::PRECOMMIT , combine(datasets::RandomBatchNormalizationLayerDataset(),framework::dataset::make("DataType", DataType::F32)))
Definition at line 83 of file BatchNormalizationLayer.cpp.
References validate().
 {
     // Validate output
     validate(CLAccessor(_target), _reference, tolerance_f32, 0);
 }
arm_compute::test::validation::FIXTURE_DATA_TEST_CASE (RunLarge , NEBitwiseAndFixture< uint8_t > , framework::DatasetMode::NIGHTLY , combine(datasets::LargeShapes(), framework::dataset::make("DataType",DataType::U8)))
Definition at line 83 of file BitwiseAnd.cpp.
References validate().
 {
     // Validate output
     validate(Accessor(_target), _reference);
 }
arm_compute::test::validation::FIXTURE_DATA_TEST_CASE (RunLarge , NEBitwiseOrFixture< uint8_t > , framework::DatasetMode::NIGHTLY , combine(datasets::LargeShapes(), framework::dataset::make("DataType",DataType::U8)))
Definition at line 83 of file BitwiseOr.cpp.
References validate().
 {
     // Validate output
     validate(Accessor(_target), _reference);
 }
arm_compute::test::validation::FIXTURE_DATA_TEST_CASE (RunLarge , NEBitwiseXorFixture< uint8_t > , framework::DatasetMode::NIGHTLY , combine(datasets::LargeShapes(), framework::dataset::make("DataType",DataType::U8)))
Definition at line 83 of file BitwiseXor.cpp.
References validate().
 {
     // Validate output
     validate(Accessor(_target), _reference);
 }
arm_compute::test::validation::FIXTURE_DATA_TEST_CASE (RunLarge , CLMeanStdDevFixture< uint8_t > , framework::DatasetMode::NIGHTLY , combine(datasets::Large2DShapes(), framework::dataset::make("DataType",DataType::U8)))
Definition at line 83 of file MeanStdDev.cpp.
References validate().
 {
     // Validate mean output
     validate(_target.first, _reference.first, tolerance_rel_low_error);
     // Validate std_dev output
     validate(_target.second, _reference.second, tolerance_rel_high_error);
 }
arm_compute::test::validation::FIXTURE_DATA_TEST_CASE (RunLarge , CLBitwiseAndFixture< uint8_t > , framework::DatasetMode::NIGHTLY , combine(datasets::LargeShapes(), framework::dataset::make("DataType",DataType::U8)))
Definition at line 83 of file BitwiseAnd.cpp.
References validate().
 {
     // Validate output
     validate(CLAccessor(_target), _reference);
 }
arm_compute::test::validation::FIXTURE_DATA_TEST_CASE (RunSmall , CLPoolingLayerFixture< half > , framework::DatasetMode::ALL , combine(datasets::SmallShapes(), combine(PoolingLayerDatasetFP,framework::dataset::make("DataType", DataType::F16))))
Definition at line 83 of file PoolingLayer.cpp.
References validate().
 {
     // Validate output
     validate(CLAccessor(_target), _reference, tolerance_f16);
 }
arm_compute::test::validation::FIXTURE_DATA_TEST_CASE (RunLarge , CLBitwiseOrFixture< uint8_t > , framework::DatasetMode::NIGHTLY , combine(datasets::LargeShapes(), framework::dataset::make("DataType",DataType::U8)))
Definition at line 83 of file BitwiseOr.cpp.
References validate().
 {
     // Validate output
     validate(CLAccessor(_target), _reference);
 }
arm_compute::test::validation::FIXTURE_DATA_TEST_CASE (RunLarge , CLBitwiseXorFixture< uint8_t > , framework::DatasetMode::NIGHTLY , combine(datasets::LargeShapes(), framework::dataset::make("DataType",DataType::U8)))
Definition at line 83 of file BitwiseXor.cpp.
References validate().
 {
     // Validate output
     validate(CLAccessor(_target), _reference);
 }
arm_compute::test::validation::FIXTURE_DATA_TEST_CASE (RunSmall , NENormalizationLayerFixture< float > , framework::DatasetMode::PRECOMMIT , combine(NormalizationDataset, framework::dataset::make("DataType", DataType::F32)))
Definition at line 83 of file NormalizationLayer.cpp.
References validate().
 {
     // Validate output
     validate(Accessor(_target), _reference, tolerance_f32);
 }
arm_compute::test::validation::FIXTURE_DATA_TEST_CASE (RunSmall , CLFlattenLayerFixture< int8_t > , framework::DatasetMode::ALL , combine(framework::dataset::concat(datasets::Small3DShapes(), datasets::Small4DShapes()),framework::dataset::make("DataType", DataType::QS8)))
Definition at line 83 of file Flatten.cpp.
References validate().
 {
     // Validate output
     validate(CLAccessor(_target), _reference);
 }
arm_compute::test::validation::FIXTURE_DATA_TEST_CASE (Random , NEBatchNormalizationLayerFixture< float > , framework::DatasetMode::PRECOMMIT , combine(datasets::RandomBatchNormalizationLayerDataset(),framework::dataset::make("DataType", DataType::F32)))
Definition at line 84 of file BatchNormalizationLayer.cpp.
References validate().
 {
     // Validate output
     validate(Accessor(_target), _reference, tolerance_f32, 0);
 }
arm_compute::test::validation::FIXTURE_DATA_TEST_CASE (RunSmall , NEDepthConcatenateLayerFixture< int8_t > , framework::DatasetMode::PRECOMMIT , combine(datasets::Small2DShapes(),framework::dataset::make("DataType",DataType::QS8)))
Definition at line 84 of file DepthConcatenateLayer.cpp.
References validate().
 {
     // Validate output
     validate(Accessor(_target), _reference);
 }
arm_compute::test::validation::FIXTURE_DATA_TEST_CASE (RunSmall , CLQuantizationLayerFixture< float > , framework::DatasetMode::PRECOMMIT , combine(concat(datasets::Small3DShapes(), datasets::Small4DShapes()),framework::dataset::make("DataType", DataType::F32)))
Definition at line 84 of file QuantizationLayer.cpp.
References validate().
 {
     // Validate output
     validate(CLAccessor(_target), _reference, tolerance_f32);
 }
arm_compute::test::validation::FIXTURE_DATA_TEST_CASE (RunSmall , NEFlattenLayerFixture< int8_t > , framework::DatasetMode::ALL , combine(framework::dataset::concat(datasets::Small3DShapes(), datasets::Small4DShapes()),framework::dataset::make("DataType", DataType::QS8)))
Definition at line 85 of file Flatten.cpp.
References validate().
 {
     // Validate output
     validate(Accessor(_target), _reference);
 }
arm_compute::test::validation::FIXTURE_DATA_TEST_CASE (Run , CLDirectConvolutionLayerFixture< half > , framework::DatasetMode::ALL , combine(data, framework::dataset::make("DataType", DataType::F16)))
Definition at line 85 of file DirectConvolutionLayer.cpp.
References validate().
 {
     // Validate output
     validate(CLAccessor(_target), _reference, tolerance_fp16, tolerance_num);
 }
arm_compute::test::validation::FIXTURE_DATA_TEST_CASE (RunLarge , CLNormalizationLayerFixture< float > , framework::DatasetMode::NIGHTLY , combine(NormalizationDataset, framework::dataset::make("DataType", DataType::F32)))
Definition at line 86 of file NormalizationLayer.cpp.
References validate().
 {
     // Validate output
     validate(CLAccessor(_target), _reference, tolerance_f32);
 }
arm_compute::test::validation::FIXTURE_DATA_TEST_CASE (RunSmall , NEFixedPointFixture< int8_t > , framework::DatasetMode::ALL , combine(combine(combine(datasets::Small1DShape(), framework::dataset::make("DataType",DataType::QS8)),framework::dataset::make("FixedPointOp", FixedPointOp::LOG)),framework::dataset::make("FractionalBits", 3, 6)))
Definition at line 86 of file FixedPoint.cpp.
References validate().
 {
     // Validate output
     validate(Accessor(_target), _reference, tolerance_log_qs8, 0);
 }
arm_compute::test::validation::FIXTURE_DATA_TEST_CASE (RunSmall , NEPoolingLayerFixture< half > , framework::DatasetMode::ALL , combine(datasets::SmallShapes(), combine(PoolingLayerDatasetFP,framework::dataset::make("DataType", DataType::F16))))
Definition at line 86 of file PoolingLayer.cpp.
References validate().
 {
     // Validate output
     validate(Accessor(_target), _reference, tolerance_f16);
 }
arm_compute::test::validation::FIXTURE_DATA_TEST_CASE (RunSmall , NEQuantizationLayerFixture< float > , framework::DatasetMode::PRECOMMIT , combine(concat(datasets::Small3DShapes(), datasets::Small4DShapes()),framework::dataset::make("DataType", DataType::F32)))
Definition at line 86 of file QuantizationLayer.cpp.
References validate().
 {
     // Validate output
     validate(Accessor(_target), _reference, tolerance_u8);
 }
arm_compute::test::validation::FIXTURE_DATA_TEST_CASE (RunLarge , NENormalizationLayerFixture< float > , framework::DatasetMode::NIGHTLY , combine(NormalizationDataset, framework::dataset::make("DataType", DataType::F32)))
Definition at line 88 of file NormalizationLayer.cpp.
References validate().
 {
     // Validate output
     validate(Accessor(_target), _reference, tolerance_f32);
 }
arm_compute::test::validation::FIXTURE_DATA_TEST_CASE (RunLarge , CLPoolingLayerFixture< half > , framework::DatasetMode::NIGHTLY , combine(datasets::LargeShapes(), combine(PoolingLayerDatasetFP,framework::dataset::make("DataType", DataType::F16))))
Definition at line 89 of file PoolingLayer.cpp.
References validate().
 {
     // Validate output
     validate(CLAccessor(_target), _reference, tolerance_f16);
 }
arm_compute::test::validation::FIXTURE_DATA_TEST_CASE (RunLarge , CLFlattenLayerFixture< int8_t > , framework::DatasetMode::NIGHTLY , combine(framework::dataset::concat(datasets::Large3DShapes(), datasets::Large4DShapes()),framework::dataset::make("DataType", DataType::QS8)))
Definition at line 89 of file Flatten.cpp.
References validate().
 {
     // Validate output
     validate(CLAccessor(_target), _reference);
 }
arm_compute::test::validation::FIXTURE_DATA_TEST_CASE (RunSmallU8 , NETableLookupFixture< uint8_t > , framework::DatasetMode::PRECOMMIT , combine(datasets::SmallShapes(), framework::dataset::make("DataType", DataType::U8)))
Definition at line 89 of file TableLookup.cpp.
References validate().
 {
     // Validate output
     validate(Accessor(_target), _reference);
 }
arm_compute::test::validation::FIXTURE_DATA_TEST_CASE (RunLarge , CLDepthConcatenateLayerFixture< int8_t > , framework::DatasetMode::NIGHTLY , combine(datasets::DepthConcatenateShapes(),framework::dataset::make("DataType",DataType::QS8)))
Definition at line 89 of file DepthConcatenateLayer.cpp.
References validate().
 {
     // Validate output
     validate(CLAccessor(_target), _reference);
 }
arm_compute::test::validation::FIXTURE_DATA_TEST_CASE (RunLarge , CLQuantizationLayerFixture< float > , framework::DatasetMode::NIGHTLY , combine(concat(datasets::Large3DShapes(), datasets::Large4DShapes()),framework::dataset::make("DataType", DataType::F32)))
Definition at line 90 of file QuantizationLayer.cpp.
References validate().
 {
     // Validate output
     validate(CLAccessor(_target), _reference, tolerance_f32);
 }
arm_compute::test::validation::FIXTURE_DATA_TEST_CASE (RunSmallU8 , CLTableLookupFixture< uint8_t > , framework::DatasetMode::PRECOMMIT , combine(datasets::SmallShapes(), framework::dataset::make("DataType", DataType::U8)))
Definition at line 90 of file TableLookup.cpp.
References validate().
 {
     // Validate output
     validate(CLAccessor(_target), _reference);
 }
arm_compute::test::validation::FIXTURE_DATA_TEST_CASE (RunSmall , NEBox3x3Fixture< uint8_t > , framework::DatasetMode::PRECOMMIT , combine(combine(datasets::SmallShapes(), framework::dataset::make("DataType",DataType::U8)),datasets::BorderModes()))
Definition at line 91 of file Box3x3.cpp.
References arm_compute::test::shape_to_valid_region(), arm_compute::UNDEFINED, and validate().
 {
     // Validate output
     validate(Accessor(_target), _reference, shape_to_valid_region(_reference.shape(), (_border_mode == BorderMode::UNDEFINED), border_size));
 }
arm_compute::test::validation::FIXTURE_DATA_TEST_CASE (RunLarge , NEDepthConcatenateLayerFixture< int8_t > , framework::DatasetMode::NIGHTLY , combine(datasets::DepthConcatenateShapes(),framework::dataset::make("DataType",DataType::QS8)))
Definition at line 91 of file DepthConcatenateLayer.cpp.
References validate().
 {
     // Validate output
     validate(Accessor(_target), _reference);
 }
arm_compute::test::validation::FIXTURE_DATA_TEST_CASE (RunSmall , CLArithmeticAdditionFixture< uint8_t > , framework::DatasetMode::PRECOMMIT , combine(combine(datasets::SmallShapes(), ArithmeticAdditionU8Dataset),framework::dataset::make("ConvertPolicy",{ConvertPolicy::SATURATE, ConvertPolicy::WRAP})))
Definition at line 91 of file ArithmeticAddition.cpp.
References arm_compute::SATURATE, and arm_compute::WRAP.
                                                                                                                                                         { ConvertPolicy::SATURATE, ConvertPolicy::WRAP })))
 {
     // Validate output
     validate(CLAccessor(_target), _reference);
 }
arm_compute::test::validation::FIXTURE_DATA_TEST_CASE (RunLarge , NEFlattenLayerFixture< int8_t > , framework::DatasetMode::NIGHTLY , combine(framework::dataset::concat(datasets::Large3DShapes(), datasets::Large4DShapes()),framework::dataset::make("DataType", DataType::QS8)))
Definition at line 91 of file Flatten.cpp.
References validate().
 {
     // Validate output
     validate(Accessor(_target), _reference);
 }
arm_compute::test::validation::FIXTURE_DATA_TEST_CASE (RunSmall , NEGaussian3x3Fixture< uint8_t > , framework::DatasetMode::PRECOMMIT , combine(combine(datasets::SmallShapes(), framework::dataset::make("DataType",DataType::U8)),datasets::BorderModes()))
Definition at line 91 of file Gaussian3x3.cpp.
References arm_compute::test::shape_to_valid_region(), arm_compute::UNDEFINED, and validate().
 {
     // Validate output
     validate(Accessor(_target), _reference, shape_to_valid_region(_reference.shape(), (_border_mode == BorderMode::UNDEFINED), border_size));
 }
arm_compute::test::validation::FIXTURE_DATA_TEST_CASE (RunSmall , NEGaussian5x5Fixture< uint8_t > , framework::DatasetMode::PRECOMMIT , combine(combine(datasets::SmallShapes(), framework::dataset::make("DataType",DataType::U8)),datasets::BorderModes()))
Definition at line 91 of file Gaussian5x5.cpp.
References arm_compute::test::shape_to_valid_region(), arm_compute::UNDEFINED, and validate().
 {
     // Validate output
     validate(Accessor(_target), _reference, shape_to_valid_region(_reference.shape(), (_border_mode == BorderMode::UNDEFINED), border_size));
 }
arm_compute::test::validation::FIXTURE_DATA_TEST_CASE (RunSmall , CLBox3x3Fixture< uint8_t > , framework::DatasetMode::PRECOMMIT , combine(combine(datasets::SmallShapes(), framework::dataset::make("DataType",DataType::U8)),datasets::BorderModes()))
Definition at line 91 of file Box3x3.cpp.
References arm_compute::test::shape_to_valid_region(), arm_compute::UNDEFINED, and validate().
 {
     // Validate output
     validate(CLAccessor(_target), _reference, shape_to_valid_region(_reference.shape(), (_border_mode == BorderMode::UNDEFINED), border_size));
 }
arm_compute::test::validation::FIXTURE_DATA_TEST_CASE (RunSmall , CLGaussian3x3Fixture< uint8_t > , framework::DatasetMode::PRECOMMIT , combine(combine(datasets::SmallShapes(), framework::dataset::make("DataType",DataType::U8)),datasets::BorderModes()))
Definition at line 91 of file Gaussian3x3.cpp.
References arm_compute::test::shape_to_valid_region(), arm_compute::UNDEFINED, and validate().
 {
     // Validate output
     validate(CLAccessor(_target), _reference, shape_to_valid_region(_reference.shape(), (_border_mode == BorderMode::UNDEFINED), border_size));
 }
arm_compute::test::validation::FIXTURE_DATA_TEST_CASE (RunSmall , CLGaussian5x5Fixture< uint8_t > , framework::DatasetMode::PRECOMMIT , combine(combine(datasets::SmallShapes(), framework::dataset::make("DataType",DataType::U8)),datasets::BorderModes()))
Definition at line 91 of file Gaussian5x5.cpp.
References arm_compute::test::shape_to_valid_region(), arm_compute::UNDEFINED, and validate().
 {
     // Validate output
     validate(CLAccessor(_target), _reference, shape_to_valid_region(_reference.shape(), (_border_mode == BorderMode::UNDEFINED), border_size));
 }
arm_compute::test::validation::FIXTURE_DATA_TEST_CASE (RunSmall , CLGEMMFixture< half > , framework::DatasetMode::PRECOMMIT , combine(datasets::SmallGEMMDataset(), framework::dataset::make("DataType", DataType::F16)))
Definition at line 91 of file GEMM.cpp.
References validate().
 {
     // Validate output
     validate(CLAccessor(_target), _reference, tolerance_f16, tolerance_num);
 }
arm_compute::test::validation::FIXTURE_DATA_TEST_CASE (Random , CLBatchNormalizationLayerFixture< half > , framework::DatasetMode::PRECOMMIT , combine(datasets::RandomBatchNormalizationLayerDataset(),framework::dataset::make("DataType", DataType::F16)))
Definition at line 92 of file BatchNormalizationLayer.cpp.
References validate().
 {
     // Validate output
     validate(CLAccessor(_target), _reference, tolerance_f16, 0);
 }
arm_compute::test::validation::FIXTURE_DATA_TEST_CASE (RunSmall , NEGEMMFixture< half > , framework::DatasetMode::PRECOMMIT , combine(datasets::SmallGEMMDataset(), framework::dataset::make("DataType", DataType::F16)))
Definition at line 92 of file GEMM.cpp.
References validate().
 {
     // Validate output
     validate(Accessor(_target), _reference, tolerance_f);
 }
arm_compute::test::validation::FIXTURE_DATA_TEST_CASE (RunSmall , CLArithmeticSubtractionFixture< uint8_t > , framework::DatasetMode::PRECOMMIT , combine(combine(datasets::SmallShapes(), ArithmeticSubtractionU8Dataset),framework::dataset::make("ConvertPolicy",{ConvertPolicy::SATURATE, ConvertPolicy::WRAP})))
Definition at line 92 of file ArithmeticSubtraction.cpp.
References arm_compute::SATURATE, and arm_compute::WRAP.
                                                                                                                                                            { ConvertPolicy::SATURATE, ConvertPolicy::WRAP })))
 {
     // Validate output
     validate(CLAccessor(_target), _reference);
 }
arm_compute::test::validation::FIXTURE_DATA_TEST_CASE (RunLarge , NEPoolingLayerFixture< half > , framework::DatasetMode::NIGHTLY , combine(datasets::LargeShapes(), combine(PoolingLayerDatasetFP,framework::dataset::make("DataType", DataType::F16))))
Definition at line 92 of file PoolingLayer.cpp.
References validate().
 {
     // Validate output
     validate(Accessor(_target), _reference, tolerance_f16);
 }
arm_compute::test::validation::FIXTURE_DATA_TEST_CASE (RunLarge , NEQuantizationLayerFixture< float > , framework::DatasetMode::NIGHTLY , combine(concat(datasets::Large3DShapes(), datasets::Large4DShapes()),framework::dataset::make("DataType", DataType::F32)))
Definition at line 92 of file QuantizationLayer.cpp.
References validate().
 {
     // Validate output
     validate(Accessor(_target), _reference, tolerance_u8);
 }
arm_compute::test::validation::FIXTURE_DATA_TEST_CASE (RunSmall , CLNonLinearFilterFixture< uint8_t > , framework::DatasetMode::PRECOMMIT , combine(combine(combine(combine(combine(datasets::SmallShapes(),datasets::NonLinearFilterFunctions()),framework::dataset::make("MaskSize",{3U, 5U})),datasets::MatrixPatterns()),datasets::BorderModes()),framework::dataset::make("DataType", DataType::U8)))
Definition at line 93 of file NonLinearFilter.cpp.
References arm_compute::U.
                                                                                                                                                         { 3U, 5U })),
                                                                                                                        datasets::MatrixPatterns()),
                                                                                                                        datasets::BorderModes()),
                                                                                                                framework::dataset::make("DataType", DataType::U8)))
 {
     // Validate output
     validate(CLAccessor(_target), _reference, shape_to_valid_region(_reference.shape(), (_border_mode == BorderMode::UNDEFINED), _border_size));
 }
arm_compute::test::validation::FIXTURE_DATA_TEST_CASE (Run , CLDirectConvolutionLayerFixture< float > , framework::DatasetMode::ALL , combine(data, framework::dataset::make("DataType", DataType::F32)))
Definition at line 93 of file DirectConvolutionLayer.cpp.
References validate().
 {
     // Validate output
     validate(CLAccessor(_target), _reference, tolerance_fp32);
 }
arm_compute::test::validation::FIXTURE_DATA_TEST_CASE (RunSmall , NENonLinearFilterFixture< uint8_t > , framework::DatasetMode::PRECOMMIT , combine(combine(combine(combine(combine(datasets::SmallShapes(),datasets::NonLinearFilterFunctions()),framework::dataset::make("MaskSize",{3U, 5U})),datasets::MatrixPatterns()),datasets::BorderModes()),framework::dataset::make("DataType", DataType::U8)))
Definition at line 93 of file NonLinearFilter.cpp.
References arm_compute::U.
                                                                                                                                                         { 3U, 5U })),
                                                                                                                        datasets::MatrixPatterns()),
                                                                                                                        datasets::BorderModes()),
                                                                                                                framework::dataset::make("DataType", DataType::U8)))
 {
     // Validate output
     validate(Accessor(_target), _reference, shape_to_valid_region(_reference.shape(), (_border_mode == BorderMode::UNDEFINED), _border_size));
 }
arm_compute::test::validation::FIXTURE_DATA_TEST_CASE (RunSmall , NEArithmeticAdditionFixture< uint8_t > , framework::DatasetMode::PRECOMMIT , combine(combine(datasets::SmallShapes(), ArithmeticAdditionU8Dataset),framework::dataset::make("ConvertPolicy",{ConvertPolicy::SATURATE, ConvertPolicy::WRAP})))
Definition at line 93 of file ArithmeticAddition.cpp.
References arm_compute::SATURATE, and arm_compute::WRAP.
                                                                                                                                                         { ConvertPolicy::SATURATE, ConvertPolicy::WRAP })))
 {
     // Validate output
     validate(Accessor(_target), _reference);
 }
arm_compute::test::validation::FIXTURE_DATA_TEST_CASE (RunSmall , NEArithmeticSubtractionFixture< uint8_t > , framework::DatasetMode::PRECOMMIT , combine(combine(datasets::SmallShapes(), ArithmeticSubtractionU8Dataset),framework::dataset::make("ConvertPolicy",{ConvertPolicy::SATURATE, ConvertPolicy::WRAP})))
Definition at line 94 of file ArithmeticSubtraction.cpp.
References arm_compute::SATURATE, and arm_compute::WRAP.
                                                                                                                                                            { ConvertPolicy::SATURATE, ConvertPolicy::WRAP })))
 {
     // Validate output
     validate(Accessor(_target), _reference);
 }
arm_compute::test::validation::FIXTURE_DATA_TEST_CASE (Random , NEBatchNormalizationLayerFixture< half > , framework::DatasetMode::PRECOMMIT , combine(datasets::RandomBatchNormalizationLayerDataset(),framework::dataset::make("DataType", DataType::F16)))
Definition at line 94 of file BatchNormalizationLayer.cpp.
References validate().
 {
     // Validate output
     validate(Accessor(_target), _reference, tolerance_f16, 0);
 }
arm_compute::test::validation::FIXTURE_DATA_TEST_CASE (RunLargeU8 , NETableLookupFixture< uint8_t > , framework::DatasetMode::NIGHTLY , combine(datasets::LargeShapes(), framework::dataset::make("DataType", DataType::U8)))
Definition at line 94 of file TableLookup.cpp.
References validate().
 {
     // Validate output
     validate(Accessor(_target), _reference);
 }
arm_compute::test::validation::FIXTURE_DATA_TEST_CASE (RunLargeU8 , CLTableLookupFixture< uint8_t > , framework::DatasetMode::NIGHTLY , combine(datasets::LargeShapes(), framework::dataset::make("DataType", DataType::U8)))
Definition at line 95 of file TableLookup.cpp.
References validate().
 {
     // Validate output
     validate(CLAccessor(_target), _reference);
 }
arm_compute::test::validation::FIXTURE_DATA_TEST_CASE (RunLarge , CLGEMMFixture< half > , framework::DatasetMode::NIGHTLY , combine(datasets::LargeGEMMDataset(), framework::dataset::make("DataType",DataType::F16)))
Definition at line 96 of file GEMM.cpp.
References validate().
 {
     // Validate output
     validate(CLAccessor(_target), _reference, tolerance_f16, tolerance_num);
 }
arm_compute::test::validation::FIXTURE_DATA_TEST_CASE (RunSmall , NEFixedPointFixture< int8_t > , framework::DatasetMode::ALL , combine(combine(combine(datasets::Small1DShape(), framework::dataset::make("DataType",DataType::QS8)),framework::dataset::make("FixedPointOp", FixedPointOp::RECIPROCAL)),framework::dataset::make("FractionalBits", 1, 6)))
Definition at line 97 of file FixedPoint.cpp.
References validate().
 {
     // Validate output
     validate(Accessor(_target), _reference, tolerance_reciprocal_qs8, 0);
 }
arm_compute::test::validation::FIXTURE_DATA_TEST_CASE (RunLarge , NEGEMMFixture< half > , framework::DatasetMode::NIGHTLY , combine(datasets::LargeGEMMDataset(), framework::dataset::make("DataType",DataType::F16)))
Definition at line 97 of file GEMM.cpp.
References validate().
 {
     // Validate output
     validate(Accessor(_target), _reference, tolerance_f);
 }
arm_compute::test::validation::FIXTURE_DATA_TEST_CASE (RunSmall , CLSoftmaxLayerFixture< half > , framework::DatasetMode::PRECOMMIT , combine(datasets::SmallShapes(), framework::dataset::make("DataType", DataType::F16)))
Definition at line 97 of file SoftmaxLayer.cpp.
References validate().
 {
     // Validate output
     validate(CLAccessor(_target), _reference, tolerance_f16);
 }
arm_compute::test::validation::FIXTURE_DATA_TEST_CASE (RunLarge , NEBox3x3Fixture< uint8_t > , framework::DatasetMode::NIGHTLY , combine(combine(datasets::LargeShapes(), framework::dataset::make("DataType",DataType::U8)),datasets::BorderModes()))
Definition at line 98 of file Box3x3.cpp.
References arm_compute::test::shape_to_valid_region(), arm_compute::UNDEFINED, and validate().
 {
     // Validate output
     validate(Accessor(_target), _reference, shape_to_valid_region(_reference.shape(), (_border_mode == BorderMode::UNDEFINED), border_size));
 }
arm_compute::test::validation::FIXTURE_DATA_TEST_CASE (RunSmall , CLMinMaxLocationFixture< int16_t > , framework::DatasetMode::PRECOMMIT , combine(datasets::Small2DShapes(), framework::dataset::make("DataType",DataType::S16)))
Definition at line 98 of file MinMaxLocation.cpp.
References validate_min_max_loc().
 {
     validate_min_max_loc(_target, _reference);
 }
arm_compute::test::validation::FIXTURE_DATA_TEST_CASE (RunLarge , NEGaussian3x3Fixture< uint8_t > , framework::DatasetMode::NIGHTLY , combine(combine(datasets::LargeShapes(), framework::dataset::make("DataType",DataType::U8)),datasets::BorderModes()))
Definition at line 98 of file Gaussian3x3.cpp.
References arm_compute::test::shape_to_valid_region(), arm_compute::UNDEFINED, and validate().
 {
     // Validate output
     validate(Accessor(_target), _reference, shape_to_valid_region(_reference.shape(), (_border_mode == BorderMode::UNDEFINED), border_size));
 }
arm_compute::test::validation::FIXTURE_DATA_TEST_CASE (RunLarge , NEGaussian5x5Fixture< uint8_t > , framework::DatasetMode::NIGHTLY , combine(combine(datasets::LargeShapes(), framework::dataset::make("DataType",DataType::U8)),datasets::BorderModes()))
Definition at line 98 of file Gaussian5x5.cpp.
References arm_compute::test::shape_to_valid_region(), arm_compute::UNDEFINED, and validate().
 {
     // Validate output
     validate(Accessor(_target), _reference, shape_to_valid_region(_reference.shape(), (_border_mode == BorderMode::UNDEFINED), border_size));
 }
arm_compute::test::validation::FIXTURE_DATA_TEST_CASE (RunSmall , CLFlattenLayerFixture< int16_t > , framework::DatasetMode::ALL , combine(framework::dataset::concat(datasets::Small3DShapes(), datasets::Small4DShapes()),framework::dataset::make("DataType", DataType::QS16)))
Definition at line 98 of file Flatten.cpp.
References validate().
 {
     // Validate output
     validate(CLAccessor(_target), _reference);
 }
arm_compute::test::validation::FIXTURE_DATA_TEST_CASE (RunLarge , CLBox3x3Fixture< uint8_t > , framework::DatasetMode::NIGHTLY , combine(combine(datasets::LargeShapes(), framework::dataset::make("DataType",DataType::U8)),datasets::BorderModes()))
Definition at line 98 of file Box3x3.cpp.
References arm_compute::test::shape_to_valid_region(), arm_compute::UNDEFINED, and validate().
 {
     // Validate output
     validate(CLAccessor(_target), _reference, shape_to_valid_region(_reference.shape(), (_border_mode == BorderMode::UNDEFINED), border_size));
 }
arm_compute::test::validation::FIXTURE_DATA_TEST_CASE (RunLarge , CLGaussian3x3Fixture< uint8_t > , framework::DatasetMode::NIGHTLY , combine(combine(datasets::LargeShapes(), framework::dataset::make("DataType",DataType::U8)),datasets::BorderModes()))
Definition at line 98 of file Gaussian3x3.cpp.
References arm_compute::test::shape_to_valid_region(), arm_compute::UNDEFINED, and validate().
 {
     // Validate output
     validate(CLAccessor(_target), _reference, shape_to_valid_region(_reference.shape(), (_border_mode == BorderMode::UNDEFINED), border_size));
 }
arm_compute::test::validation::FIXTURE_DATA_TEST_CASE (RunLarge , CLGaussian5x5Fixture< uint8_t > , framework::DatasetMode::NIGHTLY , combine(combine(datasets::LargeShapes(), framework::dataset::make("DataType",DataType::U8)),datasets::BorderModes()))
Definition at line 98 of file Gaussian5x5.cpp.
References arm_compute::test::shape_to_valid_region(), arm_compute::UNDEFINED, and validate().
 {
     // Validate output
     validate(CLAccessor(_target), _reference, shape_to_valid_region(_reference.shape(), (_border_mode == BorderMode::UNDEFINED), border_size));
 }
arm_compute::test::validation::FIXTURE_DATA_TEST_CASE (RunSmall , CLDepthConcatenateLayerFixture< int16_t > , framework::DatasetMode::PRECOMMIT , combine(datasets::Small2DShapes(),framework::dataset::make("DataType",DataType::QS16)))
Definition at line 99 of file DepthConcatenateLayer.cpp.
References validate().
 {
     // Validate output
     validate(CLAccessor(_target), _reference);
 }
arm_compute::test::validation::FIXTURE_DATA_TEST_CASE (RunSmall , NEMinMaxLocationFixture< int16_t > , framework::DatasetMode::PRECOMMIT , combine(datasets::Small2DShapes(), framework::dataset::make("DataType",DataType::S16)))
Definition at line 99 of file MinMaxLocation.cpp.
References validate_min_max_loc().
 {
     validate_min_max_loc(_target, _reference);
 }
arm_compute::test::validation::FIXTURE_DATA_TEST_CASE (Run , NEDirectConvolutionLayerFixture< half > , framework::DatasetMode::ALL , combine(data_f32, framework::dataset::make("DataType", DataType::F16)))
Definition at line 100 of file DirectConvolutionLayer.cpp.
References validate().
 {
     // Validate output
     validate(Accessor(_target), _reference, tolerance_fp16);
 }
arm_compute::test::validation::FIXTURE_DATA_TEST_CASE (RunSmall , CLNormalizationLayerFixedPointFixture< int8_t > , framework::DatasetMode::PRECOMMIT , combine(combine(NormalizationDataset, framework::dataset::make("DataType",DataType::QS8)),framework::dataset::make("FractionalBits", 1, 6)))
Definition at line 100 of file NormalizationLayer.cpp.
References validate().
 {
     // Validate output
     validate(CLAccessor(_target), _reference, tolerance_qs8);
 }
arm_compute::test::validation::FIXTURE_DATA_TEST_CASE (RunSmall , NEFlattenLayerFixture< int16_t > , framework::DatasetMode::ALL , combine(framework::dataset::concat(datasets::Small3DShapes(), datasets::Small4DShapes()),framework::dataset::make("DataType", DataType::QS16)))
Definition at line 100 of file Flatten.cpp.
References validate().
 {
     // Validate output
     validate(Accessor(_target), _reference);
 }
arm_compute::test::validation::FIXTURE_DATA_TEST_CASE (RunSmall , CLDequantizationLayerFixture< uint8_t > , framework::DatasetMode::PRECOMMIT , combine(concat(datasets::Small3DShapes(), datasets::Small4DShapes()),framework::dataset::make("DataType", DataType::U8)))
Definition at line 100 of file DequantizationLayer.cpp.
References validate().
 {
     // Validate output
     validate(CLAccessor(_target), _reference);
 }
arm_compute::test::validation::FIXTURE_DATA_TEST_CASE (RunSmall , NEDepthConcatenateLayerFixture< int16_t > , framework::DatasetMode::PRECOMMIT , combine(datasets::Small2DShapes(),framework::dataset::make("DataType",DataType::QS16)))
Definition at line 101 of file DepthConcatenateLayer.cpp.
References validate().
 {
     // Validate output
     validate(Accessor(_target), _reference);
 }
arm_compute::test::validation::FIXTURE_DATA_TEST_CASE (RunSmall , NEWarpAffineFixture< uint8_t > , framework::DatasetMode::PRECOMMIT , combine(combine(combine(datasets::SmallShapes(), framework::dataset::make("DataType", DataType::U8)),framework::dataset::make("InterpolationPolicy",{InterpolationPolicy::NEAREST_NEIGHBOR, InterpolationPolicy::BILINEAR})),datasets::BorderModes()))
Definition at line 101 of file WarpAffine.cpp.
References arm_compute::BILINEAR, and arm_compute::NEAREST_NEIGHBOR.
                                                                                                                                                               { InterpolationPolicy::NEAREST_NEIGHBOR, InterpolationPolicy::BILINEAR })),
                                                                                                           datasets::BorderModes()))
 {
     // Validate output
     validate(Accessor(_target), _reference, _valid_mask, tolerance, 0.02f);
 }
arm_compute::test::validation::FIXTURE_DATA_TEST_CASE (RunSmall , CLWarpAffineFixture< uint8_t > , framework::DatasetMode::PRECOMMIT , combine(combine(combine(datasets::SmallShapes(), framework::dataset::make("DataType", DataType::U8)),framework::dataset::make("InterpolationPolicy",{InterpolationPolicy::NEAREST_NEIGHBOR, InterpolationPolicy::BILINEAR})),datasets::BorderModes()))
Definition at line 101 of file WarpAffine.cpp.
References arm_compute::BILINEAR, and arm_compute::NEAREST_NEIGHBOR.
                                                                                                                                                               { InterpolationPolicy::NEAREST_NEIGHBOR, InterpolationPolicy::BILINEAR })),
                                                                                                           datasets::BorderModes()))
 {
     // Validate output
     validate(CLAccessor(_target), _reference, _valid_mask, tolerance, 0.02f);
 }
arm_compute::test::validation::FIXTURE_DATA_TEST_CASE (RunSmall , CLConvolutionLayerFixture< half > , framework::DatasetMode::PRECOMMIT , combine(combine(datasets::SmallConvolutionLayerDataset(),framework::dataset::make("ReshapeWeights",{true, false})),framework::dataset::make("DataType",DataType::F16)))
Definition at line 102 of file ConvolutionLayer.cpp.
                                                                                                                                                             { true, false })),
                                                                                                              framework::dataset::make("DataType",
                                                                                                                      DataType::F16)))
 {
     // Validate output
     validate(CLAccessor(_target), _reference, tolerance_f16, tolerance_num);
 }
arm_compute::test::validation::FIXTURE_DATA_TEST_CASE (RunSmall , NENormalizationLayerFixedPointFixture< int8_t > , framework::DatasetMode::PRECOMMIT , combine(combine(NormalizationDataset, framework::dataset::make("DataType",DataType::QS8)),framework::dataset::make("FractionalBits", 1, 6)))
Definition at line 102 of file NormalizationLayer.cpp.
References validate().
 {
     // Validate output
     validate(Accessor(_target), _reference, tolerance_qs8);
 }
arm_compute::test::validation::FIXTURE_DATA_TEST_CASE (RunSmall , NESoftmaxLayerFixture< half > , framework::DatasetMode::PRECOMMIT , combine(datasets::SmallShapes(), framework::dataset::make("DataType", DataType::F16)))
Definition at line 102 of file SoftmaxLayer.cpp.
References validate().
 {
     // Validate output
     validate(Accessor(_target), _reference, tolerance_f16);
 }
arm_compute::test::validation::FIXTURE_DATA_TEST_CASE (RunSmallS16 , NETableLookupFixture< int16_t > , framework::DatasetMode::PRECOMMIT , combine(datasets::SmallShapes(), framework::dataset::make("DataType", DataType::S16)))
Definition at line 102 of file TableLookup.cpp.
References validate().
 {
     // Validate output
     validate(Accessor(_target), _reference);
 }
arm_compute::test::validation::FIXTURE_DATA_TEST_CASE (RunLarge , CLSoftmaxLayerFixture< half > , framework::DatasetMode::NIGHTLY , combine(datasets::LargeShapes(), framework::dataset::make("DataType", DataType::F16)))
Definition at line 102 of file SoftmaxLayer.cpp.
References validate().
 {
     // Validate output
     validate(CLAccessor(_target), _reference, tolerance_f16);
 }
arm_compute::test::validation::FIXTURE_DATA_TEST_CASE (RunSmall , CLSobel3x3Fixture , framework::DatasetMode::PRECOMMIT , combine(combine(datasets::Small2DShapes(), datasets::BorderModes()), framework::dataset::make("Format",Format::U8)))
Definition at line 103 of file Sobel.cpp.
References arm_compute::test::shape_to_valid_region(), arm_compute::UNDEFINED, and validate().
 {
     // Validate output
     ValidRegion valid_region_x = shape_to_valid_region(_reference.first.shape(), (_border_mode == BorderMode::UNDEFINED), BorderSize(1));
     validate(CLAccessor(_target.first), _reference.first, valid_region_x);
     ValidRegion valid_region_y = shape_to_valid_region(_reference.second.shape(), (_border_mode == BorderMode::UNDEFINED), BorderSize(1));
     validate(CLAccessor(_target.second), _reference.second, valid_region_y);
 }
arm_compute::test::validation::FIXTURE_DATA_TEST_CASE (RunSmall , CLPoolingLayerFixedPointFixture< int8_t > , framework::DatasetMode::ALL , combine(combine(datasets::SmallShapes(), combine(PoolingLayerDatasetQS,framework::dataset::make("DataType", DataType::QS8))),framework::dataset::make("FractionalBits", 1, 4)))
Definition at line 103 of file PoolingLayer.cpp.
References validate().
 {
     // Validate output
     validate(CLAccessor(_target), _reference, tolerance_qs8);
 }
arm_compute::test::validation::FIXTURE_DATA_TEST_CASE (RunSmall , NESobel3x3Fixture , framework::DatasetMode::PRECOMMIT , combine(combine(datasets::Small2DShapes(), datasets::BorderModes()), framework::dataset::make("Format",Format::U8)))
Definition at line 103 of file Sobel.cpp.
References arm_compute::test::shape_to_valid_region(), arm_compute::UNDEFINED, and validate().
 {
     // Validate output
     ValidRegion valid_region_x = shape_to_valid_region(_reference.first.shape(), (_border_mode == BorderMode::UNDEFINED), BorderSize(1));
     validate(Accessor(_target.first), _reference.first, valid_region_x);
     ValidRegion valid_region_y = shape_to_valid_region(_reference.second.shape(), (_border_mode == BorderMode::UNDEFINED), BorderSize(1));
     validate(Accessor(_target.second), _reference.second, valid_region_y);
 }
arm_compute::test::validation::FIXTURE_DATA_TEST_CASE (RunSmallS16 , CLTableLookupFixture< int16_t > , framework::DatasetMode::PRECOMMIT , combine(datasets::SmallShapes(), framework::dataset::make("DataType", DataType::S16)))
Definition at line 103 of file TableLookup.cpp.
References validate().
 {
     // Validate output
     validate(CLAccessor(_target), _reference);
 }
arm_compute::test::validation::FIXTURE_DATA_TEST_CASE (RunSmall , CLWarpPerspectiveFixture< uint8_t > , framework::DatasetMode::PRECOMMIT , combine(combine(combine(datasets::SmallShapes(), framework::dataset::make("DataType",DataType::U8)),framework::dataset::make("InterpolationPolicy",{InterpolationPolicy::NEAREST_NEIGHBOR, InterpolationPolicy::BILINEAR})),datasets::BorderModes()))
Definition at line 103 of file WarpPerspective.cpp.
References arm_compute::BILINEAR, and arm_compute::NEAREST_NEIGHBOR.
                                                                                                                                                                    { InterpolationPolicy::NEAREST_NEIGHBOR, InterpolationPolicy::BILINEAR })),
                                                                                                                datasets::BorderModes()))
 {
     // Create the valid mask Tensor
     RawTensor valid_mask(_reference.shape(), _reference.data_type());
     validate(CLAccessor(_target), _reference, valid_mask, tolerance_value, tolerance_number);
 }
arm_compute::test::validation::FIXTURE_DATA_TEST_CASE (RunSmall , CLHarrisCornersFixture< uint8_t > , framework::DatasetMode::PRECOMMIT , combine(combine(datasets::Small2DShapes(), data), framework::dataset::make("Format", Format::U8)))
Definition at line 104 of file HarrisCorners.cpp.
References CLArrayAccessor< T >::buffer(), CLArrayAccessor< T >::num_values(), and validate_keypoints().
 {
     // Validate output
     CLArrayAccessor<KeyPoint> array(_target);
     validate_keypoints(array.buffer(), array.buffer() + array.num_values(), _reference.begin(), _reference.end(), RelativeTolerance<float>(0.0001f));
 }
arm_compute::test::validation::FIXTURE_DATA_TEST_CASE (RunSmall , NEWarpPerspectiveFixture< uint8_t > , framework::DatasetMode::PRECOMMIT , combine(combine(combine(datasets::SmallShapes(), framework::dataset::make("DataType",DataType::U8)),framework::dataset::make("InterpolationPolicy",{InterpolationPolicy::NEAREST_NEIGHBOR, InterpolationPolicy::BILINEAR})),datasets::BorderModes()))
Definition at line 104 of file WarpPerspective.cpp.
References arm_compute::BILINEAR, and arm_compute::NEAREST_NEIGHBOR.
                                                                                                                                                                    { InterpolationPolicy::NEAREST_NEIGHBOR, InterpolationPolicy::BILINEAR })),
                                                                                                                datasets::BorderModes()))
 {
     // Create the valid mask Tensor
     RawTensor valid_mask(_reference.shape(), _reference.data_type());
     validate(Accessor(_target), _reference, valid_mask, tolerance_value, tolerance_number);
 }
arm_compute::test::validation::FIXTURE_DATA_TEST_CASE (RunLarge , CLMinMaxLocationFixture< int16_t > , framework::DatasetMode::NIGHTLY , combine(datasets::Large2DShapes(), framework::dataset::make("DataType",DataType::S16)))
Definition at line 104 of file MinMaxLocation.cpp.
References validate_min_max_loc().
 {
     validate_min_max_loc(_target, _reference);
 }
arm_compute::test::validation::FIXTURE_DATA_TEST_CASE (RunLarge , CLNonLinearFilterFixture< uint8_t > , framework::DatasetMode::NIGHTLY , combine(combine(combine(combine(combine(datasets::LargeShapes(),datasets::NonLinearFilterFunctions()),framework::dataset::make("MaskSize",{3U, 5U})),datasets::MatrixPatterns()),datasets::BorderModes()),framework::dataset::make("DataType", DataType::U8)))
Definition at line 104 of file NonLinearFilter.cpp.
References arm_compute::U.
                                                                                                                                                       { 3U, 5U })),
                                                                                                                      datasets::MatrixPatterns()),
                                                                                                                      datasets::BorderModes()),
                                                                                                              framework::dataset::make("DataType", DataType::U8)))
 {
     // Validate output
     validate(CLAccessor(_target), _reference, shape_to_valid_region(_reference.shape(), (_border_mode == BorderMode::UNDEFINED), _border_size));
 }
arm_compute::test::validation::FIXTURE_DATA_TEST_CASE (RunSmall , NEDequantizationLayerFixture< uint8_t > , framework::DatasetMode::PRECOMMIT , combine(concat(datasets::Small3DShapes(), datasets::Small4DShapes()),framework::dataset::make("DataType", DataType::U8)))
Definition at line 104 of file DequantizationLayer.cpp.
References validate().
 {
     // Validate output
     validate(Accessor(_target), _reference, tolerance_f32);
 }
arm_compute::test::validation::FIXTURE_DATA_TEST_CASE (RunLarge , NENonLinearFilterFixture< uint8_t > , framework::DatasetMode::NIGHTLY , combine(combine(combine(combine(combine(datasets::LargeShapes(),datasets::NonLinearFilterFunctions()),framework::dataset::make("MaskSize",{3U, 5U})),datasets::MatrixPatterns()),datasets::BorderModes()),framework::dataset::make("DataType", DataType::U8)))
Definition at line 104 of file NonLinearFilter.cpp.
References arm_compute::U.
                                                                                                                                                       { 3U, 5U })),
                                                                                                                      datasets::MatrixPatterns()),
                                                                                                                      datasets::BorderModes()),
                                                                                                              framework::dataset::make("DataType", DataType::U8)))
 {
     // Validate output
     validate(Accessor(_target), _reference, shape_to_valid_region(_reference.shape(), (_border_mode == BorderMode::UNDEFINED), _border_size));
 }
arm_compute::test::validation::FIXTURE_DATA_TEST_CASE (RunLarge , CLFlattenLayerFixture< int16_t > , framework::DatasetMode::NIGHTLY , combine(framework::dataset::concat(datasets::Large3DShapes(), datasets::Large4DShapes()),framework::dataset::make("DataType", DataType::QS16)))
Definition at line 104 of file Flatten.cpp.
References validate().
 {
     // Validate output
     validate(CLAccessor(_target), _reference);
 }
arm_compute::test::validation::FIXTURE_DATA_TEST_CASE (RunSmall , NEHarrisCornersFixture< uint8_t > , framework::DatasetMode::PRECOMMIT , combine(combine(datasets::Small2DShapes(), data), framework::dataset::make("Format", Format::U8)))
Definition at line 105 of file HarrisCorners.cpp.
References ArrayAccessor< T >::buffer(), ArrayAccessor< T >::num_values(), and validate_keypoints().
 {
     // Validate output
     ArrayAccessor<KeyPoint> array(_target);
     validate_keypoints(array.buffer(), array.buffer() + array.num_values(), _reference.begin(), _reference.end(), RelativeTolerance<float>(0.0001f));
 }
arm_compute::test::validation::FIXTURE_DATA_TEST_CASE (RunLarge , NEMinMaxLocationFixture< int16_t > , framework::DatasetMode::NIGHTLY , combine(datasets::Large2DShapes(), framework::dataset::make("DataType",DataType::S16)))
Definition at line 105 of file MinMaxLocation.cpp.
References validate_min_max_loc().
 {
     validate_min_max_loc(_target, _reference);
 }
arm_compute::test::validation::FIXTURE_DATA_TEST_CASE (RunSmall , CLGEMMFixture< float > , framework::DatasetMode::PRECOMMIT , combine(datasets::SmallGEMMDataset(), framework::dataset::make("DataType", DataType::F32)))
Definition at line 105 of file GEMM.cpp.
References validate().
 {
     // Validate output
     validate(CLAccessor(_target), _reference, tolerance_f32);
 }
arm_compute::test::validation::FIXTURE_DATA_TEST_CASE (RunLarge , CLDepthConcatenateLayerFixture< int16_t > , framework::DatasetMode::NIGHTLY , combine(datasets::DepthConcatenateShapes(),framework::dataset::make("DataType",DataType::QS16)))
Definition at line 106 of file DepthConcatenateLayer.cpp.
References validate().
 {
     // Validate output
     validate(CLAccessor(_target), _reference);
 }
arm_compute::test::validation::FIXTURE_DATA_TEST_CASE (RunSmall , CLDepthConvertToU16Fixture< uint8_t > , framework::DatasetMode::PRECOMMIT , combine(combine(combine(datasets::SmallShapes(), DepthConvertU8toU16Dataset),framework::dataset::make("ConvertPolicy",{ConvertPolicy::SATURATE, ConvertPolicy::WRAP})),DepthConvertShiftDataset))
Definition at line 106 of file DepthConvert.cpp.
References arm_compute::SATURATE, and arm_compute::WRAP.
                                                                                                                                                        { ConvertPolicy::SATURATE, ConvertPolicy::WRAP })),
                                                                                                                  DepthConvertShiftDataset))
 {
     // Validate output
     validate(CLAccessor(_target), _reference);
 }
arm_compute::test::validation::FIXTURE_DATA_TEST_CASE (RunLarge , NEFlattenLayerFixture< int16_t > , framework::DatasetMode::NIGHTLY , combine(framework::dataset::concat(datasets::Large3DShapes(), datasets::Large4DShapes()),framework::dataset::make("DataType", DataType::QS16)))
Definition at line 106 of file Flatten.cpp.
References validate().
 {
     // Validate output
     validate(Accessor(_target), _reference);
 }
arm_compute::test::validation::FIXTURE_DATA_TEST_CASE (Random , CLBatchNormalizationLayerFixedPointFixture< int8_t > , framework::DatasetMode::PRECOMMIT , combine(combine(datasets::RandomBatchNormalizationLayerDataset(),framework::dataset::make("DataType", DataType::QS8)),framework::dataset::make("FractionalBits", 1, 6)))
Definition at line 106 of file BatchNormalizationLayer.cpp.
References validate().
 {
     // Validate output
     validate(CLAccessor(_target), _reference, tolerance_qs8, 0);
 }
arm_compute::test::validation::FIXTURE_DATA_TEST_CASE (RunSmall , NEConvolutionLayerFixture< half > , framework::DatasetMode::PRECOMMIT , combine(combine(datasets::SmallConvolutionLayerDataset(),framework::dataset::make("ReshapeWeights",{true, false})),framework::dataset::make("DataType", DataType::F16)))
Definition at line 106 of file ConvolutionLayer.cpp.
                                                                                                                                                             { true, false })),
                                                                                                              framework::dataset::make("DataType", DataType::F16)))
 {
     // Validate output
     validate(Accessor(_target), _reference, tolerance_f16);
 }
arm_compute::test::validation::FIXTURE_DATA_TEST_CASE (RunSmall , NEDepthConvertToU16Fixture< uint8_t > , framework::DatasetMode::PRECOMMIT , combine(combine(combine(datasets::SmallShapes(), DepthConvertU8toU16Dataset),framework::dataset::make("ConvertPolicy",{ConvertPolicy::SATURATE, ConvertPolicy::WRAP})),DepthConvertShiftDataset))
Definition at line 106 of file DepthConvert.cpp.
References arm_compute::SATURATE, and arm_compute::WRAP.
                                                                                                                                                        { ConvertPolicy::SATURATE, ConvertPolicy::WRAP })),
                                                                                                                  DepthConvertShiftDataset))
 {
     // Validate output
     validate(Accessor(_target), _reference);
 }
arm_compute::test::validation::FIXTURE_DATA_TEST_CASE (RunLarge , CLDequantizationLayerFixture< uint8_t > , framework::DatasetMode::NIGHTLY , combine(concat(datasets::Large3DShapes(), datasets::Large4DShapes()),framework::dataset::make("DataType", DataType::U8)))
Definition at line 106 of file DequantizationLayer.cpp.
References validate().
 {
     // Validate output
     validate(CLAccessor(_target), _reference);
 }
arm_compute::test::validation::FIXTURE_DATA_TEST_CASE (Run , CLDirectConvolutionLayerFixedPointFixture< int8_t > , framework::DatasetMode::ALL , combine(combine(data_quantized, framework::dataset::make("DataType", DataType::QS8)),framework::dataset::make("FractionalBits", 2, 7)))
Definition at line 106 of file DirectConvolutionLayer.cpp.
References validate().
 {
     // Validate output
     validate(CLAccessor(_target), _reference, tolerance_qs8);
 }
arm_compute::test::validation::FIXTURE_DATA_TEST_CASE (RunLargeS16 , NETableLookupFixture< int16_t > , framework::DatasetMode::NIGHTLY , combine(datasets::LargeShapes(), framework::dataset::make("DataType", DataType::S16)))
Definition at line 107 of file TableLookup.cpp.
References validate().
 {
     // Validate output
     validate(Accessor(_target), _reference);
 }
arm_compute::test::validation::FIXTURE_DATA_TEST_CASE (RunSmall , NEGEMMFixture< float > , framework::DatasetMode::PRECOMMIT , combine(datasets::SmallGEMMDataset(), framework::dataset::make("DataType", DataType::F32)))
Definition at line 107 of file GEMM.cpp.
References validate().
 {
     // Validate output
     validate(Accessor(_target), _reference, tolerance_f);
 }
arm_compute::test::validation::FIXTURE_DATA_TEST_CASE (RunSmall , NEPoolingLayerFixedPointFixture< int8_t > , framework::DatasetMode::ALL , combine(combine(datasets::SmallShapes(), combine(PoolingLayerDatasetQS,framework::dataset::make("DataType", DataType::QS8))),framework::dataset::make("FractionalBits", 1, 5)))
Definition at line 107 of file PoolingLayer.cpp.
References validate().
 {
     // Validate output
     validate(Accessor(_target), _reference, tolerance_qs8);
 }
arm_compute::test::validation::FIXTURE_DATA_TEST_CASE (RunLarge , CLNormalizationLayerFixedPointFixture< int8_t > , framework::DatasetMode::NIGHTLY , combine(combine(NormalizationDataset, framework::dataset::make("DataType",DataType::QS8)),framework::dataset::make("FractionalBits", 1, 6)))
Definition at line 107 of file NormalizationLayer.cpp.
References validate().
 {
     // Validate output
     validate(CLAccessor(_target), _reference, tolerance_qs8);
 }
arm_compute::test::validation::FIXTURE_DATA_TEST_CASE (RunLarge , NESoftmaxLayerFixture< half > , framework::DatasetMode::NIGHTLY , combine(datasets::LargeShapes(), framework::dataset::make("DataType", DataType::F16)))
Definition at line 107 of file SoftmaxLayer.cpp.
References validate().
 {
     // Validate output
     validate(Accessor(_target), _reference, tolerance_f16);
 }
arm_compute::test::validation::FIXTURE_DATA_TEST_CASE (RunLargeS16 , CLTableLookupFixture< int16_t > , framework::DatasetMode::NIGHTLY , combine(datasets::LargeShapes(), framework::dataset::make("DataType", DataType::S16)))
Definition at line 108 of file TableLookup.cpp.
References validate().
 {
     // Validate output
     validate(CLAccessor(_target), _reference);
 }
arm_compute::test::validation::FIXTURE_DATA_TEST_CASE (Random , NEBatchNormalizationLayerFixedPointFixture< int8_t > , framework::DatasetMode::PRECOMMIT , combine(combine(datasets::RandomBatchNormalizationLayerDataset(),framework::dataset::make("DataType", DataType::QS8)),framework::dataset::make("FractionalBits", 1, 6)))
Definition at line 108 of file BatchNormalizationLayer.cpp.
References validate().
 {
     // Validate output
     validate(Accessor(_target), _reference, tolerance_qs8, 0);
 }
arm_compute::test::validation::FIXTURE_DATA_TEST_CASE (RunLarge , NEDepthConcatenateLayerFixture< int16_t > , framework::DatasetMode::NIGHTLY , combine(datasets::DepthConcatenateShapes(),framework::dataset::make("DataType",DataType::QS16)))
Definition at line 108 of file DepthConcatenateLayer.cpp.
References validate().
 {
     // Validate output
     validate(Accessor(_target), _reference);
 }
arm_compute::test::validation::FIXTURE_DATA_TEST_CASE (RunLarge , CLWarpAffineFixture< uint8_t > , framework::DatasetMode::NIGHTLY , combine(combine(combine(datasets::LargeShapes(), framework::dataset::make("DataType", DataType::U8)),framework::dataset::make("InterpolationPolicy",{InterpolationPolicy::NEAREST_NEIGHBOR, InterpolationPolicy::BILINEAR})),datasets::BorderModes()))
Definition at line 108 of file WarpAffine.cpp.
References arm_compute::BILINEAR, and arm_compute::NEAREST_NEIGHBOR.
                                                                                                                                                             { InterpolationPolicy::NEAREST_NEIGHBOR, InterpolationPolicy::BILINEAR })),
                                                                                                         datasets::BorderModes()))
 {
     // Validate output
     validate(CLAccessor(_target), _reference, _valid_mask, tolerance, 0.02f);
 }
arm_compute::test::validation::FIXTURE_DATA_TEST_CASE (Run , NEDirectConvolutionLayerFixture< float > , framework::DatasetMode::ALL , combine(data_f32, framework::dataset::make("DataType", DataType::F32)))
Definition at line 109 of file DirectConvolutionLayer.cpp.
References validate().
 {
     // Validate output
     validate(Accessor(_target), _reference, tolerance_fp32);
 }
arm_compute::test::validation::FIXTURE_DATA_TEST_CASE (RunLarge , NENormalizationLayerFixedPointFixture< int8_t > , framework::DatasetMode::NIGHTLY , combine(combine(NormalizationDataset, framework::dataset::make("DataType",DataType::QS8)),framework::dataset::make("FractionalBits", 1, 6)))
Definition at line 109 of file NormalizationLayer.cpp.
References validate().
 {
     // Validate output
     validate(Accessor(_target), _reference, tolerance_qs8);
 }
arm_compute::test::validation::FIXTURE_DATA_TEST_CASE (RunLarge , CLGEMMFixture< float > , framework::DatasetMode::NIGHTLY , combine(datasets::LargeGEMMDataset(), framework::dataset::make("DataType", DataType::F32)))
Definition at line 110 of file GEMM.cpp.
References validate().
 {
     // Validate output
     validate(CLAccessor(_target), _reference, tolerance_f32);
 }
arm_compute::test::validation::FIXTURE_DATA_TEST_CASE (RunLarge , NEDequantizationLayerFixture< uint8_t > , framework::DatasetMode::NIGHTLY , combine(concat(datasets::Large3DShapes(), datasets::Large4DShapes()),framework::dataset::make("DataType", DataType::U8)))
Definition at line 110 of file DequantizationLayer.cpp.
References validate().
 {
     // Validate output
     validate(Accessor(_target), _reference, tolerance_f32);
 }
arm_compute::test::validation::FIXTURE_DATA_TEST_CASE (RunSmall , NEFixedPointFixture< int16_t > , framework::DatasetMode::ALL , combine(combine(combine(datasets::Small1DShape(), framework::dataset::make("DataType",DataType::QS16)),framework::dataset::make("FixedPointOp", FixedPointOp::EXP)),framework::dataset::make("FractionalBits", 1, 15)))
Definition at line 110 of file FixedPoint.cpp.
References validate().
 {
     // Validate output
     validate(Accessor(_target), _reference, tolerance_exp_qs16, 0);
 }
arm_compute::test::validation::FIXTURE_DATA_TEST_CASE (RunLarge , CLPoolingLayerFixedPointFixture< int8_t > , framework::DatasetMode::NIGHTLY , combine(combine(datasets::LargeShapes(), combine(PoolingLayerDatasetQS,framework::dataset::make("DataType", DataType::QS8))),framework::dataset::make("FractionalBits", 1, 4)))
Definition at line 110 of file PoolingLayer.cpp.
References validate().
 {
     // Validate output
     validate(CLAccessor(_target), _reference, tolerance_qs8);
 }
arm_compute::test::validation::FIXTURE_DATA_TEST_CASE (RunLarge , CLConvolutionLayerFixture< half > , framework::DatasetMode::NIGHTLY , combine(combine(datasets::LargeConvolutionLayerDataset(),framework::dataset::make("ReshapeWeights",{true, false})),framework::dataset::make("DataType",DataType::F16)))
Definition at line 110 of file ConvolutionLayer.cpp.
                                                                                                                                                           { true, false })),
                                                                                                            framework::dataset::make("DataType",
                                                                                                                    DataType::F16)))
 {
     // Validate output
     validate(CLAccessor(_target), _reference, tolerance_f16, tolerance_num);
 }
arm_compute::test::validation::FIXTURE_DATA_TEST_CASE (RunSmall , CLSoftmaxLayerFixture< float > , framework::DatasetMode::PRECOMMIT , combine(datasets::SmallShapes(), framework::dataset::make("DataType", DataType::F32)))
Definition at line 110 of file SoftmaxLayer.cpp.
References validate().
 {
     // Validate output
     validate(CLAccessor(_target), _reference, tolerance_f32);
 }
arm_compute::test::validation::FIXTURE_DATA_TEST_CASE (RunLarge , CLHarrisCornersFixture< uint8_t > , framework::DatasetMode::NIGHTLY , combine(combine(datasets::Large2DShapes(), data), framework::dataset::make("Format", Format::U8)))
Definition at line 111 of file HarrisCorners.cpp.
References CLArrayAccessor< T >::buffer(), CLArrayAccessor< T >::num_values(), and validate_keypoints().
 {
     // Validate output
     CLArrayAccessor<KeyPoint> array(_target);
     validate_keypoints(array.buffer(), array.buffer() + array.num_values(), _reference.begin(), _reference.end(), RelativeTolerance<float>(0.0001f));
 }
arm_compute::test::validation::FIXTURE_DATA_TEST_CASE (RunSmall , CLFullyConnectedLayerFixture< half > , framework::DatasetMode::PRECOMMIT , combine(combine(datasets::SmallFullyConnectedLayerDataset(),FullyConnectedParameters),framework::dataset::make("DataType", DataType::F16)))
Definition at line 111 of file FullyConnectedLayer.cpp.
References validate().
 {
     // Validate output
     validate(CLAccessor(_target), _reference, tolerance_f16, tolerance_num);
 }
arm_compute::test::validation::FIXTURE_DATA_TEST_CASE (RunLarge , NEGEMMFixture< float > , framework::DatasetMode::NIGHTLY , combine(datasets::LargeGEMMDataset(), framework::dataset::make("DataType", DataType::F32)))
Definition at line 112 of file GEMM.cpp.
References validate().
 {
     // Validate output
     validate(Accessor(_target), _reference, tolerance_f);
 }
arm_compute::test::validation::FIXTURE_DATA_TEST_CASE (RunLarge , NEHarrisCornersFixture< uint8_t > , framework::DatasetMode::NIGHTLY , combine(combine(datasets::Large2DShapes(), data), framework::dataset::make("Format", Format::U8)))
Definition at line 112 of file HarrisCorners.cpp.
References ArrayAccessor< T >::buffer(), ArrayAccessor< T >::num_values(), and validate_keypoints().
 {
     // Validate output
     ArrayAccessor<KeyPoint> array(_target);
     validate_keypoints(array.buffer(), array.buffer() + array.num_values(), _reference.begin(), _reference.end(), RelativeTolerance<float>(0.0001f));
 }
arm_compute::test::validation::FIXTURE_DATA_TEST_CASE (RunLarge , NEConvolutionLayerFixture< half > , framework::DatasetMode::NIGHTLY , combine(combine(datasets::LargeConvolutionLayerDataset(),framework::dataset::make("ReshapeWeights",{true, false})),framework::dataset::make("DataType", DataType::F16)))
Definition at line 113 of file ConvolutionLayer.cpp.
                                                                                                                                                           { true, false })),
                                                                                                            framework::dataset::make("DataType", DataType::F16)))
 {
     // Validate output
     validate(Accessor(_target), _reference, tolerance_f16);
 }
arm_compute::test::validation::FIXTURE_DATA_TEST_CASE (RunLarge , CLWarpPerspectiveFixture< uint8_t > , framework::DatasetMode::NIGHTLY , combine(combine(combine(datasets::LargeShapes(), framework::dataset::make("DataType",DataType::U8)),framework::dataset::make("InterpolationPolicy",{InterpolationPolicy::NEAREST_NEIGHBOR, InterpolationPolicy::BILINEAR})),datasets::BorderModes()))
Definition at line 113 of file WarpPerspective.cpp.
References arm_compute::BILINEAR, and arm_compute::NEAREST_NEIGHBOR.
                                                                                                                                                                  { InterpolationPolicy::NEAREST_NEIGHBOR, InterpolationPolicy::BILINEAR })),
                                                                                                              datasets::BorderModes()))
 {
     // Create the valid mask Tensor
     RawTensor valid_mask{ _reference.shape(), _reference.data_type() };
     validate(CLAccessor(_target), _reference, valid_mask, tolerance_value, tolerance_number);
 }
arm_compute::test::validation::FIXTURE_DATA_TEST_CASE (RunLarge , CLDepthConvertToU16Fixture< uint8_t > , framework::DatasetMode::NIGHTLY , combine(combine(combine(datasets::LargeShapes(), DepthConvertU8toU16Dataset),framework::dataset::make("ConvertPolicy",{ConvertPolicy::SATURATE, ConvertPolicy::WRAP})),DepthConvertShiftDataset))
Definition at line 114 of file DepthConvert.cpp.
References arm_compute::SATURATE, and arm_compute::WRAP.
                                                                                                                                                              { ConvertPolicy::SATURATE, ConvertPolicy::WRAP })),
                                                                                                                DepthConvertShiftDataset))
 {
     // Validate output
     validate(CLAccessor(_target), _reference);
 }
arm_compute::test::validation::FIXTURE_DATA_TEST_CASE (RunLarge , NEDepthConvertToU16Fixture< uint8_t > , framework::DatasetMode::NIGHTLY , combine(combine(combine(datasets::LargeShapes(), DepthConvertU8toU16Dataset),framework::dataset::make("ConvertPolicy",{ConvertPolicy::SATURATE, ConvertPolicy::WRAP})),DepthConvertShiftDataset))
Definition at line 114 of file DepthConvert.cpp.
References arm_compute::SATURATE, and arm_compute::WRAP.
                                                                                                                                                              { ConvertPolicy::SATURATE, ConvertPolicy::WRAP })),
                                                                                                                DepthConvertShiftDataset))
 {
     // Validate output
     validate(Accessor(_target), _reference);
 }
arm_compute::test::validation::FIXTURE_DATA_TEST_CASE (RunLarge , NEWarpPerspectiveFixture< uint8_t > , framework::DatasetMode::NIGHTLY , combine(combine(combine(datasets::LargeShapes(), framework::dataset::make("DataType",DataType::U8)),framework::dataset::make("InterpolationPolicy",{InterpolationPolicy::NEAREST_NEIGHBOR, InterpolationPolicy::BILINEAR})),datasets::BorderModes()))
Definition at line 114 of file WarpPerspective.cpp.
References arm_compute::BILINEAR, and arm_compute::NEAREST_NEIGHBOR.
                                                                                                                                                                  { InterpolationPolicy::NEAREST_NEIGHBOR, InterpolationPolicy::BILINEAR })),
                                                                                                              datasets::BorderModes()))
 {
     // Create the valid mask Tensor
     RawTensor valid_mask{ _reference.shape(), _reference.data_type() };
     validate(Accessor(_target), _reference, valid_mask, tolerance_value, tolerance_number);
 }
arm_compute::test::validation::FIXTURE_DATA_TEST_CASE (RunLarge , CLSobel3x3Fixture , framework::DatasetMode::NIGHTLY , combine(combine(datasets::Large2DShapes(), datasets::BorderModes()), framework::dataset::make("Format",Format::U8)))
Definition at line 114 of file Sobel.cpp.
References arm_compute::test::shape_to_valid_region(), arm_compute::UNDEFINED, and validate().
 {
     // Validate output
     ValidRegion valid_region_x = shape_to_valid_region(_reference.first.shape(), (_border_mode == BorderMode::UNDEFINED), BorderSize(1));
     validate(CLAccessor(_target.first), _reference.first, valid_region_x);
     ValidRegion valid_region_y = shape_to_valid_region(_reference.second.shape(), (_border_mode == BorderMode::UNDEFINED), BorderSize(1));
     validate(CLAccessor(_target.second), _reference.second, valid_region_y);
 }
arm_compute::test::validation::FIXTURE_DATA_TEST_CASE (RunLarge , NEPoolingLayerFixedPointFixture< int8_t > , framework::DatasetMode::NIGHTLY , combine(combine(datasets::LargeShapes(), combine(PoolingLayerDatasetQS,framework::dataset::make("DataType", DataType::QS8))),framework::dataset::make("FractionalBits", 1, 5)))
Definition at line 114 of file PoolingLayer.cpp.
References validate().
 {
     // Validate output
     validate(Accessor(_target), _reference, tolerance_qs8);
 }
arm_compute::test::validation::FIXTURE_DATA_TEST_CASE (RunLarge , NESobel3x3Fixture , framework::DatasetMode::NIGHTLY , combine(combine(datasets::Large2DShapes(), datasets::BorderModes()), framework::dataset::make("Format",Format::U8)))
Definition at line 114 of file Sobel.cpp.
References arm_compute::test::shape_to_valid_region(), arm_compute::UNDEFINED, and validate().
 {
     // Validate output
     ValidRegion valid_region_x = shape_to_valid_region(_reference.first.shape(), (_border_mode == BorderMode::UNDEFINED), BorderSize(1));
     validate(Accessor(_target.first), _reference.first, valid_region_x);
     ValidRegion valid_region_y = shape_to_valid_region(_reference.second.shape(), (_border_mode == BorderMode::UNDEFINED), BorderSize(1));
     validate(Accessor(_target.second), _reference.second, valid_region_y);
 }
arm_compute::test::validation::FIXTURE_DATA_TEST_CASE (RunLarge , CLSoftmaxLayerFixture< float > , framework::DatasetMode::NIGHTLY , combine(datasets::LargeShapes(), framework::dataset::make("DataType", DataType::F32)))
Definition at line 115 of file SoftmaxLayer.cpp.
References validate().
 {
     // Validate output
     validate(CLAccessor(_target), _reference, tolerance_f32);
 }
arm_compute::test::validation::FIXTURE_DATA_TEST_CASE (RunSmall , CLScaleFixture< float > , framework::DatasetMode::ALL , combine(combine(combine(datasets::SmallShapes(), framework::dataset::make("DataType", DataType::F32)),framework::dataset::make("InterpolationPolicy",{InterpolationPolicy::NEAREST_NEIGHBOR, InterpolationPolicy::BILINEAR})),datasets::BorderModes()))
Definition at line 115 of file Scale.cpp.
References arm_compute::BILINEAR, and arm_compute::NEAREST_NEIGHBOR.
                                                                                                                                                  { InterpolationPolicy::NEAREST_NEIGHBOR, InterpolationPolicy::BILINEAR })),
                                                                                              datasets::BorderModes()))
 {
     //Create valid region
     TensorInfo        src_info(_shape, 1, _data_type);
     const ValidRegion valid_region = calculate_valid_region_scale(src_info, _reference.shape(), _policy, BorderSize(1), (_border_mode == BorderMode::UNDEFINED));
     // Validate output
     validate(CLAccessor(_target), _reference, valid_region, tolerance_f32, tolerance_num_f32);
 }
arm_compute::test::validation::FIXTURE_DATA_TEST_CASE (Run , CLDirectConvolutionLayerFixedPointFixture< int16_t > , framework::DatasetMode::ALL , combine(combine(data_quantized, framework::dataset::make("DataType", DataType::QS16)),framework::dataset::make("FractionalBits", 2, 15)))
Definition at line 115 of file DirectConvolutionLayer.cpp.
References validate().
 {
     // Validate output
     validate(CLAccessor(_target), _reference, tolerance_qs16);
 }
arm_compute::test::validation::FIXTURE_DATA_TEST_CASE (Random , CLBatchNormalizationLayerFixedPointFixture< int16_t > , framework::DatasetMode::PRECOMMIT , combine(combine(datasets::RandomBatchNormalizationLayerDataset(),framework::dataset::make("DataType", DataType::QS16)),framework::dataset::make("FractionalBits", 1, 14)))
Definition at line 116 of file BatchNormalizationLayer.cpp.
References validate().
 {
     // Validate output
     validate(CLAccessor(_target), _reference, tolerance_qs16, 0);
 }
arm_compute::test::validation::FIXTURE_DATA_TEST_CASE (RunSmall , NESoftmaxLayerFixture< float > , framework::DatasetMode::PRECOMMIT , combine(datasets::SmallShapes(), framework::dataset::make("DataType", DataType::F32)))
Definition at line 116 of file SoftmaxLayer.cpp.
References validate().
 {
     // Validate output
     validate(Accessor(_target), _reference, tolerance_f32);
 }
arm_compute::test::validation::FIXTURE_DATA_TEST_CASE (RunSmall , CLNormalizationLayerFixedPointFixture< int16_t > , framework::DatasetMode::PRECOMMIT , combine(combine(NormalizationDataset, framework::dataset::make("DataType",DataType::QS16)),framework::dataset::make("FractionalBits", 1, 14)))
Definition at line 118 of file NormalizationLayer.cpp.
References validate().
 {
     // Validate output
     validate(CLAccessor(_target), _reference, tolerance_qs16);
 }
arm_compute::test::validation::FIXTURE_DATA_TEST_CASE (Random , NEBatchNormalizationLayerFixedPointFixture< int16_t > , framework::DatasetMode::PRECOMMIT , combine(combine(datasets::RandomBatchNormalizationLayerDataset(),framework::dataset::make("DataType", DataType::QS16)),framework::dataset::make("FractionalBits", 1, 14)))
Definition at line 118 of file BatchNormalizationLayer.cpp.
References validate().
 {
     // Validate output
     validate(Accessor(_target), _reference, tolerance_qs16, 0);
 }
arm_compute::test::validation::FIXTURE_DATA_TEST_CASE (RunLarge , CLFullyConnectedLayerFixture< half > , framework::DatasetMode::NIGHTLY , combine(combine(datasets::LargeFullyConnectedLayerDataset(),FullyConnectedParameters),framework::dataset::make("DataType", DataType::F16)))
Definition at line 118 of file FullyConnectedLayer.cpp.
References validate().
 {
     // Validate output
     validate(CLAccessor(_target), _reference, tolerance_f16, tolerance_num);
 }
arm_compute::test::validation::FIXTURE_DATA_TEST_CASE (RunSmall , NEScaleFixture< float > , framework::DatasetMode::ALL , combine(combine(combine(datasets::SmallShapes(), framework::dataset::make("DataType",DataType::F32)),framework::dataset::make("InterpolationPolicy",{InterpolationPolicy::NEAREST_NEIGHBOR, InterpolationPolicy::BILINEAR})),datasets::BorderModes()))
Definition at line 119 of file Scale.cpp.
References arm_compute::BILINEAR, and arm_compute::NEAREST_NEIGHBOR.
                                                                                                                                                  { InterpolationPolicy::NEAREST_NEIGHBOR, InterpolationPolicy::BILINEAR })),
                                                                                              datasets::BorderModes()))
 {
     //Create valid region
     TensorInfo  src_info(_shape, 1, _data_type);
     ValidRegion valid_region = calculate_valid_region_scale(src_info, _reference.shape(), _policy, BorderSize(1), (_border_mode == BorderMode::UNDEFINED));
     // Validate output
     validate(Accessor(_target), _reference, valid_region, tolerance_f32, tolerance_num_f32);
 }
arm_compute::test::validation::FIXTURE_DATA_TEST_CASE (RunSmall , NENormalizationLayerFixedPointFixture< int16_t > , framework::DatasetMode::PRECOMMIT , combine(combine(NormalizationDataset, framework::dataset::make("DataType",DataType::QS16)),framework::dataset::make("FractionalBits", 1, 14)))
Definition at line 120 of file NormalizationLayer.cpp.
References validate().
 {
     // Validate output
     validate(Accessor(_target), _reference, tolerance_qs16);
 }
arm_compute::test::validation::FIXTURE_DATA_TEST_CASE (RunSmall , CLPoolingLayerFixedPointFixture< int16_t > , framework::DatasetMode::ALL , combine(combine(datasets::SmallShapes(), combine(PoolingLayerDatasetQS,framework::dataset::make("DataType", DataType::QS16))),framework::dataset::make("FractionalBits", 1, 12)))
Definition at line 120 of file PoolingLayer.cpp.
References validate().
 {
     // Validate output
     validate(CLAccessor(_target), _reference, tolerance_qs16);
 }
arm_compute::test::validation::FIXTURE_DATA_TEST_CASE (RunSmall , NEFixedPointFixture< int16_t > , framework::DatasetMode::ALL , combine(combine(combine(framework::dataset::make("Shape", TensorShape(8192U)),framework::dataset::make("DataType",DataType::QS16)),framework::dataset::make("FixedPointOp", FixedPointOp::INV_SQRT)),framework::dataset::make("FractionalBits", 1, 14)))
Definition at line 121 of file FixedPoint.cpp.
References validate().
 {
     // Validate output
     validate(Accessor(_target), _reference, tolerance_invsqrt_qs16, 0);
 }
arm_compute::test::validation::FIXTURE_DATA_TEST_CASE (RunSmall , CLConvolutionLayerFixture< float > , framework::DatasetMode::PRECOMMIT , combine(combine(datasets::SmallConvolutionLayerDataset(),framework::dataset::make("ReshapeWeights",{true, false})),framework::dataset::make("DataType",DataType::F32)))
Definition at line 121 of file ConvolutionLayer.cpp.
                                                                                                                                                              { true, false })),
                                                                                                               framework::dataset::make("DataType",
                                                                                                                       DataType::F32)))
 {
     // Validate output
     validate(CLAccessor(_target), _reference, tolerance_f32);
 }
arm_compute::test::validation::FIXTURE_DATA_TEST_CASE (RunLarge , NESoftmaxLayerFixture< float > , framework::DatasetMode::NIGHTLY , combine(datasets::LargeShapes(), framework::dataset::make("DataType", DataType::F32)))
Definition at line 121 of file SoftmaxLayer.cpp.
References validate().
 {
     // Validate output
     validate(Accessor(_target), _reference, tolerance_f32);
 }
arm_compute::test::validation::FIXTURE_DATA_TEST_CASE (RunSmall , CLMinMaxLocationFixture< float > , framework::DatasetMode::PRECOMMIT , combine(datasets::Small2DShapes(), framework::dataset::make("DataType",DataType::F32)))
Definition at line 122 of file MinMaxLocation.cpp.
References validate_min_max_loc().
 {
     validate_min_max_loc(_target, _reference);
 }
arm_compute::test::validation::FIXTURE_DATA_TEST_CASE (RunSmall , CLGEMMFixedPointFixture< int8_t > , framework::DatasetMode::PRECOMMIT , combine(combine(datasets::SmallGEMMDataset(),framework::dataset::make("DataType",DataType::QS8)),framework::dataset::make("FractionalBits", 1, 7)))
Definition at line 123 of file GEMM.cpp.
References validate().
 {
     // Validate output
     validate(CLAccessor(_target), _reference, tolerance_q);
 }
arm_compute::test::validation::FIXTURE_DATA_TEST_CASE (Run , NEDirectConvolutionLayerFixedPointFixture< int8_t > , framework::DatasetMode::ALL , combine(combine(data_qs8, framework::dataset::make("DataType", DataType::QS8)),framework::dataset::make("FractionalBits", 4, 7)))
Definition at line 123 of file DirectConvolutionLayer.cpp.
References validate().
 {
     // Validate output
     validate(Accessor(_target), _reference, tolerance_qs);
 }
arm_compute::test::validation::FIXTURE_DATA_TEST_CASE (RunSmall , NEMinMaxLocationFixture< float > , framework::DatasetMode::PRECOMMIT , combine(datasets::Small2DShapes(), framework::dataset::make("DataType",DataType::F32)))
Definition at line 123 of file MinMaxLocation.cpp.
References validate_min_max_loc().
 {
     validate_min_max_loc(_target, _reference);
 }
arm_compute::test::validation::FIXTURE_DATA_TEST_CASE (RunSmall , NEConvolutionLayerFixture< float > , framework::DatasetMode::PRECOMMIT , combine(combine(datasets::SmallConvolutionLayerDataset(),framework::dataset::make("ReshapeWeights",{true, false})),framework::dataset::make("DataType", DataType::F32)))
Definition at line 124 of file ConvolutionLayer.cpp.
                                                                                                                                                              { true, false })),
                                                                                                               framework::dataset::make("DataType", DataType::F32)))
 {
     // Validate output
     validate(Accessor(_target), _reference, tolerance_f32);
 }
arm_compute::test::validation::FIXTURE_DATA_TEST_CASE (RunSmall , CLArithmeticAdditionFixture< int16_t > , framework::DatasetMode::PRECOMMIT , combine(combine(datasets::SmallShapes(), ArithmeticAdditionS16Dataset),framework::dataset::make("ConvertPolicy",{ConvertPolicy::SATURATE, ConvertPolicy::WRAP})))
Definition at line 124 of file ArithmeticAddition.cpp.
References arm_compute::SATURATE, and arm_compute::WRAP.
                                                                                                                                                         { ConvertPolicy::SATURATE, ConvertPolicy::WRAP })))
 {
     // Validate output
     validate(CLAccessor(_target), _reference);
 }
arm_compute::test::validation::FIXTURE_DATA_TEST_CASE (RunSmall , NEFullyConnectedLayerFixture< half > , framework::DatasetMode::PRECOMMIT , combine(combine(datasets::SmallFullyConnectedLayerDataset(),FullyConnectedParameters),framework::dataset::make("DataType", DataType::F16)))
Definition at line 124 of file FullyConnectedLayer.cpp.
References validate().
 {
     // Validate output
     validate(Accessor(_target), _reference, tolerance_f16);
 }
arm_compute::test::validation::FIXTURE_DATA_TEST_CASE (RunSmall , NEPoolingLayerFixedPointFixture< int16_t > , framework::DatasetMode::ALL , combine(combine(datasets::SmallShapes(), combine(PoolingLayerDatasetQS,framework::dataset::make("DataType", DataType::QS16))),framework::dataset::make("FractionalBits", 1, 13)))
Definition at line 124 of file PoolingLayer.cpp.
References validate().
 {
     // Validate output
     validate(Accessor(_target), _reference, tolerance_qs16);
 }
arm_compute::test::validation::FIXTURE_DATA_TEST_CASE (RunLarge , CLNormalizationLayerFixedPointFixture< int16_t > , framework::DatasetMode::NIGHTLY , combine(combine(NormalizationDataset, framework::dataset::make("DataType",DataType::QS16)),framework::dataset::make("FractionalBits", 1, 14)))
Definition at line 125 of file NormalizationLayer.cpp.
References validate().
 {
     // Validate output
     validate(CLAccessor(_target), _reference, tolerance_qs16);
 }
arm_compute::test::validation::FIXTURE_DATA_TEST_CASE (RunSmall , NEGEMMFixedPointFixture< int8_t > , framework::DatasetMode::PRECOMMIT , combine(combine(datasets::SmallGEMMDataset(),framework::dataset::make("DataType",DataType::QS8)),framework::dataset::make("FractionalBits", 1, 7)))
Definition at line 125 of file GEMM.cpp.
References validate().
 {
     // Validate output
     validate(Accessor(_target), _reference, tolerance_q);
 }
arm_compute::test::validation::FIXTURE_DATA_TEST_CASE (RunSmall , CLArithmeticSubtractionFixture< int16_t > , framework::DatasetMode::PRECOMMIT , combine(combine(datasets::SmallShapes(), ArithmeticSubtractionS16Dataset),framework::dataset::make("ConvertPolicy",{ConvertPolicy::SATURATE, ConvertPolicy::WRAP})))
Definition at line 125 of file ArithmeticSubtraction.cpp.
References arm_compute::SATURATE, and arm_compute::WRAP.
                                                                                                                                                            { ConvertPolicy::SATURATE, ConvertPolicy::WRAP })))
 {
     // Validate output
     validate(CLAccessor(_target), _reference);
 }
arm_compute::test::validation::FIXTURE_DATA_TEST_CASE (RunLarge , CLScaleFixture< float > , framework::DatasetMode::NIGHTLY , combine(combine(combine(datasets::LargeShapes(), framework::dataset::make("DataType", DataType::F32)),framework::dataset::make("InterpolationPolicy",{InterpolationPolicy::NEAREST_NEIGHBOR, InterpolationPolicy::BILINEAR})),datasets::BorderModes()))
Definition at line 126 of file Scale.cpp.
References arm_compute::BILINEAR, and arm_compute::NEAREST_NEIGHBOR.
                                                                                                                                                      { InterpolationPolicy::NEAREST_NEIGHBOR, InterpolationPolicy::BILINEAR })),
                                                                                                  datasets::BorderModes()))
 {
     //Create valid region
     TensorInfo        src_info(_shape, 1, _data_type);
     const ValidRegion valid_region = calculate_valid_region_scale(src_info, _reference.shape(), _policy, BorderSize(1), (_border_mode == BorderMode::UNDEFINED));
     // Validate output
     validate(CLAccessor(_target), _reference, valid_region, tolerance_f32, tolerance_num_f32);
 }
arm_compute::test::validation::FIXTURE_DATA_TEST_CASE (RunSmall , NEArithmeticAdditionFixture< int16_t > , framework::DatasetMode::PRECOMMIT , combine(combine(datasets::SmallShapes(), ArithmeticAdditionS16Dataset),framework::dataset::make("ConvertPolicy",{ConvertPolicy::SATURATE, ConvertPolicy::WRAP})))
Definition at line 126 of file ArithmeticAddition.cpp.
References arm_compute::SATURATE, and arm_compute::WRAP.
                                                                                                                                                         { ConvertPolicy::SATURATE, ConvertPolicy::WRAP })))
 {
     // Validate output
     validate(Accessor(_target), _reference);
 }
arm_compute::test::validation::FIXTURE_DATA_TEST_CASE (RunSmall , NEArithmeticSubtractionFixture< int16_t > , framework::DatasetMode::PRECOMMIT , combine(combine(datasets::SmallShapes(), ArithmeticSubtractionS16Dataset),framework::dataset::make("ConvertPolicy",{ConvertPolicy::SATURATE, ConvertPolicy::WRAP})))
Definition at line 127 of file ArithmeticSubtraction.cpp.
References arm_compute::SATURATE, and arm_compute::WRAP.
                                                                                                                                                            { ConvertPolicy::SATURATE, ConvertPolicy::WRAP })))
 {
     // Validate output
     validate(Accessor(_target), _reference);
 }
arm_compute::test::validation::FIXTURE_DATA_TEST_CASE (RunLarge , NENormalizationLayerFixedPointFixture< int16_t > , framework::DatasetMode::NIGHTLY , combine(combine(NormalizationDataset, framework::dataset::make("DataType",DataType::QS16)),framework::dataset::make("FractionalBits", 1, 14)))
Definition at line 127 of file NormalizationLayer.cpp.
References validate().
 {
     // Validate output
     validate(Accessor(_target), _reference, tolerance_qs16);
 }
arm_compute::test::validation::FIXTURE_DATA_TEST_CASE (RunLarge , CLPoolingLayerFixedPointFixture< int16_t > , framework::DatasetMode::NIGHTLY , combine(combine(datasets::LargeShapes(), combine(PoolingLayerDatasetQS,framework::dataset::make("DataType", DataType::QS16))),framework::dataset::make("FractionalBits", 1, 12)))
Definition at line 127 of file PoolingLayer.cpp.
References validate().
 {
     // Validate output
     validate(CLAccessor(_target), _reference, tolerance_qs16);
 }
arm_compute::test::validation::FIXTURE_DATA_TEST_CASE (RunLarge , CLMinMaxLocationFixture< float > , framework::DatasetMode::NIGHTLY , combine(datasets::Large2DShapes(), framework::dataset::make("DataType",DataType::F32)))
Definition at line 128 of file MinMaxLocation.cpp.
References validate_min_max_loc().
 {
     validate_min_max_loc(_target, _reference);
 }
arm_compute::test::validation::FIXTURE_DATA_TEST_CASE (RunSmall , CLFullyConnectedLayerFixture< float > , framework::DatasetMode::PRECOMMIT , combine(combine(datasets::SmallFullyConnectedLayerDataset(), FullyConnectedParameters),framework::dataset::make("DataType", DataType::F32)))
Definition at line 128 of file FullyConnectedLayer.cpp.
References validate().
 {
     // Validate output
     validate(CLAccessor(_target), _reference, tolerance_f32);
 }
arm_compute::test::validation::FIXTURE_DATA_TEST_CASE (RunLarge , NEMinMaxLocationFixture< float > , framework::DatasetMode::NIGHTLY , combine(datasets::Large2DShapes(), framework::dataset::make("DataType",DataType::F32)))
Definition at line 129 of file MinMaxLocation.cpp.
References validate_min_max_loc().
 {
     validate_min_max_loc(_target, _reference);
 }
arm_compute::test::validation::FIXTURE_DATA_TEST_CASE (RunSmall , CLSoftmaxLayerFixedPointFixture< int8_t > , framework::DatasetMode::PRECOMMIT , combine(combine(datasets::SmallShapes(), framework::dataset::make("DataType",DataType::QS8)),framework::dataset::make("FractionalBits", 1, 6)))
Definition at line 129 of file SoftmaxLayer.cpp.
References validate().
 {
     // Validate output
     validate(CLAccessor(_target), _reference, tolerance_fixed_point);
 }
arm_compute::test::validation::FIXTURE_DATA_TEST_CASE (RunLarge , CLConvolutionLayerFixture< float > , framework::DatasetMode::NIGHTLY , combine(combine(datasets::LargeConvolutionLayerDataset(),framework::dataset::make("ReshapeWeights",{true, false})),framework::dataset::make("DataType",DataType::F32)))
Definition at line 129 of file ConvolutionLayer.cpp.
                                                                                                                                                            { true, false })),
                                                                                                             framework::dataset::make("DataType",
                                                                                                                     DataType::F32)))
 {
     // Validate output
     validate(CLAccessor(_target), _reference, tolerance_f32);
 }
arm_compute::test::validation::FIXTURE_DATA_TEST_CASE (RunLarge , CLGEMMFixedPointFixture< int8_t > , framework::DatasetMode::NIGHTLY , combine(combine(datasets::LargeGEMMDataset(),framework::dataset::make("DataType",DataType::QS8)),framework::dataset::make("FractionalBits", 1, 7)))
Definition at line 131 of file GEMM.cpp.
References validate().
 {
     // Validate output
     validate(CLAccessor(_target), _reference, tolerance_q);
 }
arm_compute::test::validation::FIXTURE_DATA_TEST_CASE (RunLarge , NEPoolingLayerFixedPointFixture< int16_t > , framework::DatasetMode::NIGHTLY , combine(combine(datasets::LargeShapes(), combine(PoolingLayerDatasetQS,framework::dataset::make("DataType", DataType::QS16))),framework::dataset::make("FractionalBits", 1, 13)))
Definition at line 131 of file PoolingLayer.cpp.
References validate().
 {
     // Validate output
     validate(Accessor(_target), _reference, tolerance_qs16);
 }
arm_compute::test::validation::FIXTURE_DATA_TEST_CASE (RunLarge , NEFullyConnectedLayerFixture< half > , framework::DatasetMode::NIGHTLY , combine(combine(datasets::LargeFullyConnectedLayerDataset(),FullyConnectedParameters),framework::dataset::make("DataType", DataType::F16)))
Definition at line 131 of file FullyConnectedLayer.cpp.
References validate().
 {
     // Validate output
     validate(Accessor(_target), _reference, tolerance_f16);
 }
arm_compute::test::validation::FIXTURE_DATA_TEST_CASE (RunLarge , NEScaleFixture< float > , framework::DatasetMode::NIGHTLY , combine(combine(combine(datasets::LargeShapes(), framework::dataset::make("DataType",DataType::F32)),framework::dataset::make("InterpolationPolicy",{InterpolationPolicy::NEAREST_NEIGHBOR, InterpolationPolicy::BILINEAR})),datasets::BorderModes()))
Definition at line 131 of file Scale.cpp.
References arm_compute::BILINEAR, and arm_compute::NEAREST_NEIGHBOR.
                                                                                                                                                      { InterpolationPolicy::NEAREST_NEIGHBOR, InterpolationPolicy::BILINEAR })),
                                                                                                  datasets::BorderModes()))
 {
     //Create valid region
     TensorInfo  src_info(_shape, 1, _data_type);
     ValidRegion valid_region = calculate_valid_region_scale(src_info, _reference.shape(), _policy, BorderSize(1), (_border_mode == BorderMode::UNDEFINED));
     // Validate output
     validate(Accessor(_target), _reference, valid_region, tolerance_f32, tolerance_num_f32);
 }
arm_compute::test::validation::FIXTURE_DATA_TEST_CASE (RunLarge , CLArithmeticAdditionFixture< int16_t > , framework::DatasetMode::NIGHTLY , combine(combine(datasets::LargeShapes(), ArithmeticAdditionS16Dataset),framework::dataset::make("ConvertPolicy",{ConvertPolicy::SATURATE, ConvertPolicy::WRAP})))
Definition at line 131 of file ArithmeticAddition.cpp.
References arm_compute::SATURATE, and arm_compute::WRAP.
                                                                                                                                                       { ConvertPolicy::SATURATE, ConvertPolicy::WRAP })))
 {
     // Validate output
     validate(CLAccessor(_target), _reference);
 }
arm_compute::test::validation::FIXTURE_DATA_TEST_CASE (RunLarge , NEConvolutionLayerFixture< float > , framework::DatasetMode::NIGHTLY , combine(combine(datasets::LargeConvolutionLayerDataset(),framework::dataset::make("ReshapeWeights",{true, false})),framework::dataset::make("DataType", DataType::F32)))
Definition at line 131 of file ConvolutionLayer.cpp.
                                                                                                                                                            { true, false })),
                                                                                                             framework::dataset::make("DataType", DataType::F32)))
 {
     // Validate output
     validate(Accessor(_target), _reference, tolerance_f32);
 }
arm_compute::test::validation::FIXTURE_DATA_TEST_CASE (RunLarge , CLArithmeticSubtractionFixture< int16_t > , framework::DatasetMode::NIGHTLY , combine(combine(datasets::LargeShapes(), ArithmeticSubtractionS16Dataset),framework::dataset::make("ConvertPolicy",{ConvertPolicy::SATURATE, ConvertPolicy::WRAP})))
Definition at line 132 of file ArithmeticSubtraction.cpp.
References arm_compute::SATURATE, and arm_compute::WRAP.
                                                                                                                                                          { ConvertPolicy::SATURATE, ConvertPolicy::WRAP })))
 {
     // Validate output
     validate(CLAccessor(_target), _reference);
 }
arm_compute::test::validation::FIXTURE_DATA_TEST_CASE (RunSmall , NEFixedPointFixture< int16_t > , framework::DatasetMode::ALL , combine(combine(combine(datasets::Small1DShape(), framework::dataset::make("DataType",DataType::QS16)),framework::dataset::make("FixedPointOp", FixedPointOp::LOG)),framework::dataset::make("FractionalBits", 4, 14)))
Definition at line 133 of file FixedPoint.cpp.
References validate().
 {
     // Validate output
     validate(Accessor(_target), _reference, tolerance_log_qs16, 0);
 }
arm_compute::test::validation::FIXTURE_DATA_TEST_CASE (RunLarge , NEGEMMFixedPointFixture< int8_t > , framework::DatasetMode::NIGHTLY , combine(combine(datasets::LargeGEMMDataset(),framework::dataset::make("DataType",DataType::QS8)),framework::dataset::make("FractionalBits", 1, 7)))
Definition at line 133 of file GEMM.cpp.
References validate().
 {
     // Validate output
     validate(Accessor(_target), _reference, tolerance_q);
 }
arm_compute::test::validation::FIXTURE_DATA_TEST_CASE (Run , NEDirectConvolutionLayerFixedPointFixture< int16_t > , framework::DatasetMode::ALL , combine(combine(data_qs16, framework::dataset::make("DataType", DataType::QS16)),framework::dataset::make("FractionalBits", 4, 14)))
Definition at line 133 of file DirectConvolutionLayer.cpp.
References validate().
 {
     // Validate output
     validate(Accessor(_target), _reference, tolerance_qs);
 }
arm_compute::test::validation::FIXTURE_DATA_TEST_CASE (RunLarge , NEArithmeticAdditionFixture< int16_t > , framework::DatasetMode::NIGHTLY , combine(combine(datasets::LargeShapes(), ArithmeticAdditionS16Dataset),framework::dataset::make("ConvertPolicy",{ConvertPolicy::SATURATE, ConvertPolicy::WRAP})))
Definition at line 133 of file ArithmeticAddition.cpp.
References arm_compute::SATURATE, and arm_compute::WRAP.
                                                                                                                                                       { ConvertPolicy::SATURATE, ConvertPolicy::WRAP })))
 {
     // Validate output
     validate(Accessor(_target), _reference);
 }
arm_compute::test::validation::FIXTURE_DATA_TEST_CASE (RunLarge , NEArithmeticSubtractionFixture< int16_t > , framework::DatasetMode::NIGHTLY , combine(combine(datasets::LargeShapes(), ArithmeticSubtractionS16Dataset),framework::dataset::make("ConvertPolicy",{ConvertPolicy::SATURATE, ConvertPolicy::WRAP})))
Definition at line 134 of file ArithmeticSubtraction.cpp.
References arm_compute::SATURATE, and arm_compute::WRAP.
                                                                                                                                                          { ConvertPolicy::SATURATE, ConvertPolicy::WRAP })))
 {
     // Validate output
     validate(Accessor(_target), _reference);
 }
arm_compute::test::validation::FIXTURE_DATA_TEST_CASE (RunLarge , CLFullyConnectedLayerFixture< float > , framework::DatasetMode::NIGHTLY , combine(combine(datasets::LargeFullyConnectedLayerDataset(), FullyConnectedParameters),framework::dataset::make("DataType", DataType::F32)))
Definition at line 134 of file FullyConnectedLayer.cpp.
References validate().
 {
     // Validate output
     validate(CLAccessor(_target), _reference, tolerance_f32);
 }
arm_compute::test::validation::FIXTURE_DATA_TEST_CASE (RunSmall , NESoftmaxLayerFixedPointFixture< int8_t > , framework::DatasetMode::PRECOMMIT , combine(combine(datasets::SmallShapes(), framework::dataset::make("DataType",DataType::QS8)),framework::dataset::make("FractionalBits", 1, 6)))
Definition at line 135 of file SoftmaxLayer.cpp.
References validate().
 {
     // Validate output
     validate(Accessor(_target), _reference, tolerance_fixed_point);
 }
arm_compute::test::validation::FIXTURE_DATA_TEST_CASE (RunLarge , CLSoftmaxLayerFixedPointFixture< int8_t > , framework::DatasetMode::NIGHTLY , combine(combine(datasets::LargeShapes(), framework::dataset::make("DataType",DataType::QS8)),framework::dataset::make("FractionalBits", 1, 6)))
Definition at line 136 of file SoftmaxLayer.cpp.
References validate().
 {
     // Validate output
     validate(CLAccessor(_target), _reference, tolerance_fixed_point);
 }
arm_compute::test::validation::FIXTURE_DATA_TEST_CASE (RunSmall , CLScaleFixture< half > , framework::DatasetMode::ALL , combine(combine(combine(datasets::SmallShapes(), framework::dataset::make("DataType", DataType::F16)),framework::dataset::make("InterpolationPolicy",{InterpolationPolicy::NEAREST_NEIGHBOR, InterpolationPolicy::BILINEAR})),datasets::BorderModes()))
Definition at line 139 of file Scale.cpp.
References arm_compute::BILINEAR, and arm_compute::NEAREST_NEIGHBOR.
                                                                                                                                                 { InterpolationPolicy::NEAREST_NEIGHBOR, InterpolationPolicy::BILINEAR })),
                                                                                             datasets::BorderModes()))
 {
     //Create valid region
     TensorInfo        src_info(_shape, 1, _data_type);
     const ValidRegion valid_region = calculate_valid_region_scale(src_info, _reference.shape(), _policy, BorderSize(1), (_border_mode == BorderMode::UNDEFINED));
     // Validate output
     validate(CLAccessor(_target), _reference, valid_region, tolerance_f16);
 }
arm_compute::test::validation::FIXTURE_DATA_TEST_CASE (RunSmall , CLGEMMFixedPointFixture< int16_t > , framework::DatasetMode::PRECOMMIT , combine(combine(datasets::SmallGEMMDataset(),framework::dataset::make("DataType",DataType::QS16)),framework::dataset::make("FractionalBits", 1, 14)))
Definition at line 142 of file GEMM.cpp.
References validate().
 {
     // Validate output
     validate(CLAccessor(_target), _reference, tolerance_q);
 }
arm_compute::test::validation::FIXTURE_DATA_TEST_CASE (RunLarge , NESoftmaxLayerFixedPointFixture< int8_t > , framework::DatasetMode::NIGHTLY , combine(combine(datasets::LargeShapes(), framework::dataset::make("DataType",DataType::QS8)),framework::dataset::make("FractionalBits", 1, 6)))
Definition at line 142 of file SoftmaxLayer.cpp.
References validate().
 {
     // Validate output
     validate(Accessor(_target), _reference, tolerance_fixed_point);
 }
arm_compute::test::validation::FIXTURE_DATA_TEST_CASE (RunSmall , NEFullyConnectedLayerFixture< float > , framework::DatasetMode::PRECOMMIT , combine(combine(datasets::SmallFullyConnectedLayerDataset(), FullyConnectedParameters),framework::dataset::make("DataType", DataType::F32)))
Definition at line 142 of file FullyConnectedLayer.cpp.
References validate().
 {
     // Validate output
     validate(Accessor(_target), _reference, tolerance_f32);
 }
arm_compute::test::validation::FIXTURE_DATA_TEST_CASE (RunSmall , NEFixedPointFixture< int16_t > , framework::DatasetMode::ALL , combine(combine(combine(datasets::Small1DShape(), framework::dataset::make("DataType",DataType::QS16)),framework::dataset::make("FixedPointOp", FixedPointOp::RECIPROCAL)),framework::dataset::make("FractionalBits", 1, 14)))
Definition at line 144 of file FixedPoint.cpp.
References validate().
 {
     // Validate output
     validate(Accessor(_target), _reference, tolerance_reciprocal_qs16, 0);
 }
arm_compute::test::validation::FIXTURE_DATA_TEST_CASE (RunSmall , NEGEMMFixedPointFixture< int16_t > , framework::DatasetMode::PRECOMMIT , combine(combine(datasets::SmallGEMMDataset(),framework::dataset::make("DataType",DataType::QS16)),framework::dataset::make("FractionalBits", 1, 14)))
Definition at line 144 of file GEMM.cpp.
References validate().
 {
     // Validate output
     validate(Accessor(_target), _reference, tolerance_q);
 }
arm_compute::test::validation::FIXTURE_DATA_TEST_CASE (RunSmall , CLArithmeticAdditionFixedPointFixture< int8_t > , framework::DatasetMode::PRECOMMIT , combine(combine(combine(datasets::SmallShapes(), ArithmeticAdditionQS8Dataset),framework::dataset::make("ConvertPolicy",{ConvertPolicy::SATURATE, ConvertPolicy::WRAP})),framework::dataset::make("FractionalBits", 1, 7)))
Definition at line 144 of file ArithmeticAddition.cpp.
References arm_compute::SATURATE, and arm_compute::WRAP.
                                                              { ConvertPolicy::SATURATE, ConvertPolicy::WRAP })),
                        framework::dataset::make("FractionalBits", 1, 7)))
 {
     // Validate output
     validate(CLAccessor(_target), _reference);
 }
arm_compute::test::validation::FIXTURE_DATA_TEST_CASE (RunSmall , CLArithmeticSubtractionFixedPointFixture< int8_t > , framework::DatasetMode::PRECOMMIT , combine(combine(combine(datasets::SmallShapes(), ArithmeticSubtractionQS8Dataset),framework::dataset::make("ConvertPolicy",{ConvertPolicy::SATURATE, ConvertPolicy::WRAP})),framework::dataset::make("FractionalBits", 1, 7)))
Definition at line 145 of file ArithmeticSubtraction.cpp.
References arm_compute::SATURATE, and arm_compute::WRAP.
                                                              { ConvertPolicy::SATURATE, ConvertPolicy::WRAP })),
                        framework::dataset::make("FractionalBits", 1, 7)))
 {
     // Validate output
     validate(CLAccessor(_target), _reference);
 }
arm_compute::test::validation::FIXTURE_DATA_TEST_CASE (RunSmall , CLConvolutionLayerFixedPointFixture< int8_t > , framework::DatasetMode::PRECOMMIT , combine(combine(combine(datasets::SmallConvolutionLayerDataset(),framework::dataset::make("ReshapeWeights",{true, false})),framework::dataset::make("DataType",DataType::QS8)),framework::dataset::make("FractionalBits", 4, 7)))
Definition at line 146 of file ConvolutionLayer.cpp.
                                                               { true, false })),
                        framework::dataset::make("DataType",
                                                 DataType::QS8)),
                        framework::dataset::make("FractionalBits", 4, 7)))
 {
     // Validate output
     validate(CLAccessor(_target), _reference, tolerance_q);
 }
arm_compute::test::validation::FIXTURE_DATA_TEST_CASE (RunSmall , NEActivationLayerFixture< half > , framework::DatasetMode::PRECOMMIT , combine(combine(datasets::SmallShapes(), ActivationDataset),framework::dataset::make("DataType",DataType::F16)))
Definition at line 146 of file ActivationLayer.cpp.
References validate().
 {
     // Validate output
     validate(Accessor(_target), _reference, tolerance(_data_type, _function));
 }
arm_compute::test::validation::FIXTURE_DATA_TEST_CASE (RunSmall , NEArithmeticAdditionFixedPointFixture< int8_t > , framework::DatasetMode::PRECOMMIT , combine(combine(combine(datasets::SmallShapes(), ArithmeticAdditionQS8Dataset),framework::dataset::make("ConvertPolicy",{ConvertPolicy::SATURATE, ConvertPolicy::WRAP})),framework::dataset::make("FractionalBits", 1, 7)))
Definition at line 146 of file ArithmeticAddition.cpp.
References arm_compute::SATURATE, and arm_compute::WRAP.
                                                              { ConvertPolicy::SATURATE, ConvertPolicy::WRAP })),
                        framework::dataset::make("FractionalBits", 1, 7)))
 {
     // Validate output
     validate(Accessor(_target), _reference);
 }
arm_compute::test::validation::FIXTURE_DATA_TEST_CASE (RunSmall , NEConvolutionLayerFixedPointFixture< int8_t > , framework::DatasetMode::PRECOMMIT , combine(combine(combine(datasets::SmallConvolutionLayerDataset(),framework::dataset::make("ReshapeWeights",{true, false})),framework::dataset::make("DataType", DataType::QS8)),framework::dataset::make("FractionalBits", 4, 7)))
Definition at line 147 of file ConvolutionLayer.cpp.
                                                               { true, false })),
                        framework::dataset::make("DataType", DataType::QS8)),
                        framework::dataset::make("FractionalBits", 4, 7)))
 {
     // Validate output
     validate(Accessor(_target), _reference, tolerance_q);
 }
arm_compute::test::validation::FIXTURE_DATA_TEST_CASE (RunSmall , NEArithmeticSubtractionFixedPointFixture< int8_t > , framework::DatasetMode::PRECOMMIT , combine(combine(combine(datasets::SmallShapes(), ArithmeticSubtractionQS8Dataset),framework::dataset::make("ConvertPolicy",{ConvertPolicy::SATURATE, ConvertPolicy::WRAP})),framework::dataset::make("FractionalBits", 1, 7)))
Definition at line 147 of file ArithmeticSubtraction.cpp.
References arm_compute::SATURATE, and arm_compute::WRAP.
                                                              { ConvertPolicy::SATURATE, ConvertPolicy::WRAP })),
                        framework::dataset::make("FractionalBits", 1, 7)))
 {
     // Validate output
     validate(Accessor(_target), _reference);
 }
arm_compute::test::validation::FIXTURE_DATA_TEST_CASE (RunSmall , CLSoftmaxLayerFixedPointFixture< int16_t > , framework::DatasetMode::PRECOMMIT , combine(combine(datasets::SmallShapes(),framework::dataset::make("DataType",DataType::QS16)),framework::dataset::make("FractionalBits", 1, 14)))
Definition at line 147 of file SoftmaxLayer.cpp.
References validate().
 {
     // Validate output
     validate(CLAccessor(_target), _reference, tolerance_fixed_point);
 }
arm_compute::test::validation::FIXTURE_DATA_TEST_CASE (RunSmall , CLDepthConvertToS16Fixture< uint8_t > , framework::DatasetMode::PRECOMMIT , combine(combine(combine(datasets::SmallShapes(), DepthConvertU8toS16Dataset),framework::dataset::make("ConvertPolicy",{ConvertPolicy::SATURATE, ConvertPolicy::WRAP})),DepthConvertShiftDataset))
Definition at line 148 of file DepthConvert.cpp.
References arm_compute::SATURATE, and arm_compute::WRAP.
                                                                                                                                                        { ConvertPolicy::SATURATE, ConvertPolicy::WRAP })),
                                                                                                                  DepthConvertShiftDataset))
 {
     // Validate output
     validate(CLAccessor(_target), _reference);
 }
arm_compute::test::validation::FIXTURE_DATA_TEST_CASE (RunSmall , NEDepthConvertToS16Fixture< uint8_t > , framework::DatasetMode::PRECOMMIT , combine(combine(combine(datasets::SmallShapes(), DepthConvertU8toS16Dataset),framework::dataset::make("ConvertPolicy",{ConvertPolicy::SATURATE, ConvertPolicy::WRAP})),DepthConvertShiftDataset))
Definition at line 148 of file DepthConvert.cpp.
References arm_compute::SATURATE, and arm_compute::WRAP.
                                                                                                                                                        { ConvertPolicy::SATURATE, ConvertPolicy::WRAP })),
                                                                                                                  DepthConvertShiftDataset))
 {
     // Validate output
     validate(Accessor(_target), _reference);
 }
arm_compute::test::validation::FIXTURE_DATA_TEST_CASE (RunSmall , NEScaleFixture< uint8_t > , framework::DatasetMode::ALL , combine(combine(combine(datasets::SmallShapes(), framework::dataset::make("DataType",DataType::U8)),framework::dataset::make("InterpolationPolicy",{InterpolationPolicy::NEAREST_NEIGHBOR, InterpolationPolicy::BILINEAR})),datasets::BorderModes()))
Definition at line 148 of file Scale.cpp.
References arm_compute::BILINEAR, and arm_compute::NEAREST_NEIGHBOR.
                                                                                                                                                    { InterpolationPolicy::NEAREST_NEIGHBOR, InterpolationPolicy::BILINEAR })),
                                                                                                datasets::BorderModes()))
 {
     //Create valid region
     TensorInfo  src_info(_shape, 1, _data_type);
     ValidRegion valid_region = calculate_valid_region_scale(src_info, _reference.shape(), _policy, BorderSize(1), (_border_mode == BorderMode::UNDEFINED));
     // Validate output
     validate(Accessor(_target), _reference, valid_region, tolerance_u8);
 }
arm_compute::test::validation::FIXTURE_DATA_TEST_CASE (RunLarge , NEFullyConnectedLayerFixture< float > , framework::DatasetMode::NIGHTLY , combine(combine(datasets::LargeFullyConnectedLayerDataset(), FullyConnectedParameters),framework::dataset::make("DataType", DataType::F32)))
Definition at line 148 of file FullyConnectedLayer.cpp.
References validate().
 {
     // Validate output
     validate(Accessor(_target), _reference, tolerance_f32);
 }
arm_compute::test::validation::FIXTURE_DATA_TEST_CASE (RunSmall , CLFullyConnectedLayerFixedPointFixture< int8_t > , framework::DatasetMode::PRECOMMIT , combine(combine(combine(datasets::SmallFullyConnectedLayerDataset(),FullyConnectedParameters),framework::dataset::make("DataType",DataType::QS8)),framework::dataset::make("FractionalBits", 1, 6)))
Definition at line 149 of file FullyConnectedLayer.cpp.
References validate().
 {
     // Validate output
     validate(CLAccessor(_target), _reference, tolerance_fixed_point);
 }
arm_compute::test::validation::FIXTURE_DATA_TEST_CASE (RunLarge , CLGEMMFixedPointFixture< int16_t > , framework::DatasetMode::NIGHTLY , combine(combine(datasets::LargeGEMMDataset(),framework::dataset::make("DataType",DataType::QS16)),framework::dataset::make("FractionalBits", 1, 14)))
Definition at line 150 of file GEMM.cpp.
References validate().
 {
     // Validate output
     validate(CLAccessor(_target), _reference, tolerance_q);
 }
arm_compute::test::validation::FIXTURE_DATA_TEST_CASE (RunLarge , CLScaleFixture< half > , framework::DatasetMode::NIGHTLY , combine(combine(combine(datasets::LargeShapes(), framework::dataset::make("DataType",DataType::F16)),framework::dataset::make("InterpolationPolicy",{InterpolationPolicy::NEAREST_NEIGHBOR, InterpolationPolicy::BILINEAR})),datasets::BorderModes()))
Definition at line 150 of file Scale.cpp.
References arm_compute::BILINEAR, and arm_compute::NEAREST_NEIGHBOR.
                                                                                                                                                     { InterpolationPolicy::NEAREST_NEIGHBOR, InterpolationPolicy::BILINEAR })),
                                                                                                 datasets::BorderModes()))
 {
     //Create valid region
     TensorInfo        src_info(_shape, 1, _data_type);
     const ValidRegion valid_region = calculate_valid_region_scale(src_info, _reference.shape(), _policy, BorderSize(1), (_border_mode == BorderMode::UNDEFINED));
     // Validate output
     validate(CLAccessor(_target), _reference, valid_region, tolerance_f16);
 }
arm_compute::test::validation::FIXTURE_DATA_TEST_CASE (RunLarge , CLArithmeticAdditionFixedPointFixture< int8_t > , framework::DatasetMode::NIGHTLY , combine(combine(combine(datasets::LargeShapes(), ArithmeticAdditionQS8Dataset),framework::dataset::make("ConvertPolicy",{ConvertPolicy::SATURATE, ConvertPolicy::WRAP})),framework::dataset::make("FractionalBits", 1, 7)))
Definition at line 152 of file ArithmeticAddition.cpp.
References arm_compute::SATURATE, and arm_compute::WRAP.
                                                              { ConvertPolicy::SATURATE, ConvertPolicy::WRAP })),
                        framework::dataset::make("FractionalBits", 1, 7)))
 {
     // Validate output
     validate(CLAccessor(_target), _reference);
 }
arm_compute::test::validation::FIXTURE_DATA_TEST_CASE (RunLarge , NEGEMMFixedPointFixture< int16_t > , framework::DatasetMode::NIGHTLY , combine(combine(datasets::LargeGEMMDataset(),framework::dataset::make("DataType",DataType::QS16)),framework::dataset::make("FractionalBits", 1, 14)))
Definition at line 152 of file GEMM.cpp.
References validate().
 {
     // Validate output
     validate(Accessor(_target), _reference, tolerance_q);
 }
arm_compute::test::validation::FIXTURE_DATA_TEST_CASE (RunSmall , NESoftmaxLayerFixedPointFixture< int16_t > , framework::DatasetMode::PRECOMMIT , combine(combine(datasets::SmallShapes(),framework::dataset::make("DataType",DataType::QS16)),framework::dataset::make("FractionalBits", 1, 14)))
Definition at line 153 of file SoftmaxLayer.cpp.
References validate().
 {
     // Validate output
     validate(Accessor(_target), _reference, tolerance_fixed_point);
 }
arm_compute::test::validation::FIXTURE_DATA_TEST_CASE (RunLarge , CLArithmeticSubtractionFixedPointFixture< int8_t > , framework::DatasetMode::NIGHTLY , combine(combine(combine(datasets::LargeShapes(), ArithmeticSubtractionQS8Dataset),framework::dataset::make("ConvertPolicy",{ConvertPolicy::SATURATE, ConvertPolicy::WRAP})),framework::dataset::make("FractionalBits", 1, 7)))
Definition at line 153 of file ArithmeticSubtraction.cpp.
References arm_compute::SATURATE, and arm_compute::WRAP.
                                                              { ConvertPolicy::SATURATE, ConvertPolicy::WRAP })),
                        framework::dataset::make("FractionalBits", 1, 7)))
 {
     // Validate output
     validate(CLAccessor(_target), _reference);
 }
arm_compute::test::validation::FIXTURE_DATA_TEST_CASE (RunLarge , NEActivationLayerFixture< half > , framework::DatasetMode::NIGHTLY , combine(combine(datasets::LargeShapes(), ActivationDataset),framework::dataset::make("DataType",DataType::F16)))
Definition at line 153 of file ActivationLayer.cpp.
References validate().
 {
     // Validate output
     validate(Accessor(_target), _reference, tolerance(_data_type, _function));
 }
arm_compute::test::validation::FIXTURE_DATA_TEST_CASE (RunLarge , NEArithmeticAdditionFixedPointFixture< int8_t > , framework::DatasetMode::NIGHTLY , combine(combine(combine(datasets::LargeShapes(), ArithmeticAdditionQS8Dataset),framework::dataset::make("ConvertPolicy",{ConvertPolicy::SATURATE, ConvertPolicy::WRAP})),framework::dataset::make("FractionalBits", 1, 7)))
Definition at line 154 of file ArithmeticAddition.cpp.
References arm_compute::SATURATE, and arm_compute::WRAP.
                                                              { ConvertPolicy::SATURATE, ConvertPolicy::WRAP })),
                        framework::dataset::make("FractionalBits", 1, 7)))
 {
     // Validate output
     validate(Accessor(_target), _reference);
 }
arm_compute::test::validation::FIXTURE_DATA_TEST_CASE (RunLarge , CLConvolutionLayerFixedPointFixture< int8_t > , framework::DatasetMode::NIGHTLY , combine(combine(combine(datasets::LargeConvolutionLayerDataset(),framework::dataset::make("ReshapeWeights",{true, false})),framework::dataset::make("DataType",DataType::QS8)),framework::dataset::make("FractionalBits", 4, 7)))
Definition at line 155 of file ConvolutionLayer.cpp.
                                                                                                                                                               { true, false })),
                                                                                                                        framework::dataset::make("DataType",
                                                                                                                                DataType::QS8)),
                                                                                                                        framework::dataset::make("FractionalBits", 4, 7)))
 {
     // Validate output
     validate(CLAccessor(_target), _reference, tolerance_q);
 }
arm_compute::test::validation::FIXTURE_DATA_TEST_CASE (RunLarge , NEConvolutionLayerFixedPointFixture< int8_t > , framework::DatasetMode::NIGHTLY , combine(combine(combine(datasets::LargeConvolutionLayerDataset(),framework::dataset::make("ReshapeWeights",{true, false})),framework::dataset::make("DataType", DataType::QS8)),framework::dataset::make("FractionalBits", 4, 7)))
Definition at line 155 of file ConvolutionLayer.cpp.
                                                                                                                                                               { true, false })),
                                                                                                                        framework::dataset::make("DataType", DataType::QS8)),
                                                                                                                        framework::dataset::make("FractionalBits", 4, 7)))
 {
     // Validate output
     validate(Accessor(_target), _reference, tolerance_q);
 }
arm_compute::test::validation::FIXTURE_DATA_TEST_CASE (RunLarge , CLSoftmaxLayerFixedPointFixture< int16_t > , framework::DatasetMode::NIGHTLY , combine(combine(datasets::LargeShapes(),framework::dataset::make("DataType",DataType::QS16)),framework::dataset::make("FractionalBits", 1, 14)))
Definition at line 155 of file SoftmaxLayer.cpp.
References validate().
 {
     // Validate output
     validate(CLAccessor(_target), _reference, tolerance_fixed_point);
 }
arm_compute::test::validation::FIXTURE_DATA_TEST_CASE (RunLarge , NEArithmeticSubtractionFixedPointFixture< int8_t > , framework::DatasetMode::NIGHTLY , combine(combine(combine(datasets::LargeShapes(), ArithmeticSubtractionQS8Dataset),framework::dataset::make("ConvertPolicy",{ConvertPolicy::SATURATE, ConvertPolicy::WRAP})),framework::dataset::make("FractionalBits", 1, 7)))
Definition at line 155 of file ArithmeticSubtraction.cpp.
References arm_compute::SATURATE, and arm_compute::WRAP.
                                                              { ConvertPolicy::SATURATE, ConvertPolicy::WRAP })),
                        framework::dataset::make("FractionalBits", 1, 7)))
 {
     // Validate output
     validate(Accessor(_target), _reference);
 }
arm_compute::test::validation::FIXTURE_DATA_TEST_CASE (RunLarge , NEDepthConvertToS16Fixture< uint8_t > , framework::DatasetMode::NIGHTLY , combine(combine(combine(datasets::LargeShapes(), DepthConvertU8toS16Dataset),framework::dataset::make("ConvertPolicy",{ConvertPolicy::SATURATE, ConvertPolicy::WRAP})),DepthConvertShiftDataset))
Definition at line 156 of file DepthConvert.cpp.
References arm_compute::SATURATE, and arm_compute::WRAP.
                                                                                                                                                              { ConvertPolicy::SATURATE, ConvertPolicy::WRAP })),
                                                                                                                DepthConvertShiftDataset))
 {
     // Validate output
     validate(Accessor(_target), _reference);
 }
arm_compute::test::validation::FIXTURE_DATA_TEST_CASE (RunLarge , CLDepthConvertToS16Fixture< uint8_t > , framework::DatasetMode::NIGHTLY , combine(combine(combine(datasets::LargeShapes(), DepthConvertU8toS16Dataset),framework::dataset::make("ConvertPolicy",{ConvertPolicy::SATURATE, ConvertPolicy::WRAP})),DepthConvertShiftDataset))
Definition at line 156 of file DepthConvert.cpp.
References arm_compute::SATURATE, and arm_compute::WRAP.
                                                                                                                                                              { ConvertPolicy::SATURATE, ConvertPolicy::WRAP })),
                                                                                                                DepthConvertShiftDataset))
 {
     // Validate output
     validate(CLAccessor(_target), _reference);
 }
arm_compute::test::validation::FIXTURE_DATA_TEST_CASE (RunLarge , CLFullyConnectedLayerFixedPointFixture< int8_t > , framework::DatasetMode::NIGHTLY , combine(combine(combine(datasets::LargeFullyConnectedLayerDataset(),FullyConnectedParameters),framework::dataset::make("DataType",DataType::QS8)),framework::dataset::make("FractionalBits", 1, 6)))
Definition at line 158 of file FullyConnectedLayer.cpp.
References validate().
 {
     // Validate output
     validate(CLAccessor(_target), _reference, tolerance_fixed_point);
 }
arm_compute::test::validation::FIXTURE_DATA_TEST_CASE (RunLarge , NEScaleFixture< uint8_t > , framework::DatasetMode::NIGHTLY , combine(combine(combine(datasets::LargeShapes(), framework::dataset::make("DataType",DataType::U8)),framework::dataset::make("InterpolationPolicy",{InterpolationPolicy::NEAREST_NEIGHBOR, InterpolationPolicy::BILINEAR})),datasets::BorderModes()))
Definition at line 160 of file Scale.cpp.
References arm_compute::BILINEAR, and arm_compute::NEAREST_NEIGHBOR.
                                                                                                                                                        { InterpolationPolicy::NEAREST_NEIGHBOR, InterpolationPolicy::BILINEAR })),
                                                                                                    datasets::BorderModes()))
 {
     //Create valid region
     TensorInfo  src_info(_shape, 1, _data_type);
     ValidRegion valid_region = calculate_valid_region_scale(src_info, _reference.shape(), _policy, BorderSize(1), (_border_mode == BorderMode::UNDEFINED));
     // Validate output
     validate(Accessor(_target), _reference, valid_region, tolerance_u8);
 }
arm_compute::test::validation::FIXTURE_DATA_TEST_CASE (RunLarge , NESoftmaxLayerFixedPointFixture< int16_t > , framework::DatasetMode::NIGHTLY , combine(combine(datasets::LargeShapes(),framework::dataset::make("DataType",DataType::QS16)),framework::dataset::make("FractionalBits", 1, 14)))
Definition at line 161 of file SoftmaxLayer.cpp.
References validate().
 {
     // Validate output
     validate(Accessor(_target), _reference, tolerance_fixed_point);
 }
arm_compute::test::validation::FIXTURE_DATA_TEST_CASE (RunSmall , CLArithmeticAdditionFixedPointFixture< int16_t > , framework::DatasetMode::PRECOMMIT , combine(combine(combine(datasets::SmallShapes(), ArithmeticAdditionQS16Dataset),framework::dataset::make("ConvertPolicy",{ConvertPolicy::SATURATE, ConvertPolicy::WRAP})),framework::dataset::make("FractionalBits", 1, 15)))
Definition at line 162 of file ArithmeticAddition.cpp.
References arm_compute::SATURATE, and arm_compute::WRAP.
                                                              { ConvertPolicy::SATURATE, ConvertPolicy::WRAP })),
                        framework::dataset::make("FractionalBits", 1, 15)))
 {
     // Validate output
     validate(CLAccessor(_target), _reference);
 }
arm_compute::test::validation::FIXTURE_DATA_TEST_CASE (RunSmall , CLArithmeticSubtractionFixedPointFixture< int16_t > , framework::DatasetMode::PRECOMMIT , combine(combine(combine(datasets::SmallShapes(),ArithmeticSubtractionQS16Dataset),framework::dataset::make("ConvertPolicy",{ConvertPolicy::SATURATE, ConvertPolicy::WRAP})),framework::dataset::make("FractionalBits", 1, 15)))
Definition at line 163 of file ArithmeticSubtraction.cpp.
References arm_compute::SATURATE, and arm_compute::WRAP.
                                                              { ConvertPolicy::SATURATE, ConvertPolicy::WRAP })),
                        framework::dataset::make("FractionalBits", 1, 15)))
 {
     // Validate output
     validate(CLAccessor(_target), _reference);
 }
arm_compute::test::validation::FIXTURE_DATA_TEST_CASE (RunSmall , NEFullyConnectedLayerFixedPointFixture< int8_t > , framework::DatasetMode::PRECOMMIT , combine(combine(combine(datasets::SmallFullyConnectedLayerDataset(),FullyConnectedParameters),framework::dataset::make("DataType",DataType::QS8)),framework::dataset::make("FractionalBits", 1, 6)))
Definition at line 163 of file FullyConnectedLayer.cpp.
References validate().
 {
     // Validate output
     validate(Accessor(_target), _reference, tolerance_fixed_point);
 }
arm_compute::test::validation::FIXTURE_DATA_TEST_CASE (RunSmall , NEActivationLayerFixture< float > , framework::DatasetMode::PRECOMMIT , combine(combine(datasets::SmallShapes(), ActivationDataset), framework::dataset::make("DataType",DataType::F32)))
Definition at line 164 of file ActivationLayer.cpp.
References validate().
 {
     // Validate output
     validate(Accessor(_target), _reference, tolerance(_data_type, _function));
 }
arm_compute::test::validation::FIXTURE_DATA_TEST_CASE (RunSmall , CLActivationLayerFixture< half > , framework::DatasetMode::PRECOMMIT , combine(combine(datasets::SmallShapes(), ActivationDataset),framework::dataset::make("DataType",DataType::F16)))
Definition at line 164 of file ActivationLayer.cpp.
References validate().
 {
     // Validate output
     validate(CLAccessor(_target), _reference, tolerance(_function, _data_type));
 }
arm_compute::test::validation::FIXTURE_DATA_TEST_CASE (RunSmall , NEArithmeticAdditionFixedPointFixture< int16_t > , framework::DatasetMode::PRECOMMIT , combine(combine(combine(datasets::SmallShapes(), ArithmeticAdditionQS16Dataset),framework::dataset::make("ConvertPolicy",{ConvertPolicy::SATURATE, ConvertPolicy::WRAP})),framework::dataset::make("FractionalBits", 1, 15)))
Definition at line 164 of file ArithmeticAddition.cpp.
References arm_compute::SATURATE, and arm_compute::WRAP.
                                                              { ConvertPolicy::SATURATE, ConvertPolicy::WRAP })),
                        framework::dataset::make("FractionalBits", 1, 15)))
 {
     // Validate output
     validate(Accessor(_target), _reference);
 }
arm_compute::test::validation::FIXTURE_DATA_TEST_CASE (RunSmall , NEArithmeticSubtractionFixedPointFixture< int16_t > , framework::DatasetMode::PRECOMMIT , combine(combine(combine(datasets::SmallShapes(),ArithmeticSubtractionQS16Dataset),framework::dataset::make("ConvertPolicy",{ConvertPolicy::SATURATE, ConvertPolicy::WRAP})),framework::dataset::make("FractionalBits", 1, 15)))
Definition at line 165 of file ArithmeticSubtraction.cpp.
References arm_compute::SATURATE, and arm_compute::WRAP.
                                                              { ConvertPolicy::SATURATE, ConvertPolicy::WRAP })),
                        framework::dataset::make("FractionalBits", 1, 15)))
 {
     // Validate output
     validate(Accessor(_target), _reference);
 }
arm_compute::test::validation::FIXTURE_DATA_TEST_CASE (RunSmall , NEConvolutionLayerFixedPointFixture< int16_t > , framework::DatasetMode::PRECOMMIT , combine(combine(combine(datasets::SmallConvolutionLayerDataset(),framework::dataset::make("ReshapeWeights",{true, false})),framework::dataset::make("DataType", DataType::QS16)),framework::dataset::make("FractionalBits", 1, 14)))
Definition at line 167 of file ConvolutionLayer.cpp.
                                                               { true, false })),
                        framework::dataset::make("DataType", DataType::QS16)),
                        framework::dataset::make("FractionalBits", 1, 14)))
 {
     // Validate output
     validate(Accessor(_target), _reference, tolerance_q);
 }
arm_compute::test::validation::FIXTURE_DATA_TEST_CASE (RunSmall , CLScaleFixture< uint8_t > , framework::DatasetMode::ALL , combine(combine(combine(datasets::SmallShapes(), framework::dataset::make("DataType", DataType::U8)),framework::dataset::make("InterpolationPolicy",{InterpolationPolicy::NEAREST_NEIGHBOR, InterpolationPolicy::BILINEAR})),datasets::BorderModes()))
Definition at line 167 of file Scale.cpp.
References arm_compute::BILINEAR, and arm_compute::NEAREST_NEIGHBOR.
                                                                                                                                                    { InterpolationPolicy::NEAREST_NEIGHBOR, InterpolationPolicy::BILINEAR })),
                                                                                                datasets::BorderModes()))
 {
     //Create valid region
     TensorInfo        src_info(_shape, 1, _data_type);
     const ValidRegion valid_region = calculate_valid_region_scale(src_info, _reference.shape(), _policy, BorderSize(1), (_border_mode == BorderMode::UNDEFINED));
     // Validate output
     validate(CLAccessor(_target), _reference, valid_region, tolerance_u8);
 }
arm_compute::test::validation::FIXTURE_DATA_TEST_CASE (RunSmall , CLConvolutionLayerFixedPointFixture< int16_t > , framework::DatasetMode::PRECOMMIT , combine(combine(combine(datasets::SmallConvolutionLayerDataset(),framework::dataset::make("ReshapeWeights",{true, false})),framework::dataset::make("DataType",DataType::QS16)),framework::dataset::make("FractionalBits", 1, 14)))
Definition at line 168 of file ConvolutionLayer.cpp.
                                                               { true, false })),
                        framework::dataset::make("DataType",
                                                 DataType::QS16)),
                        framework::dataset::make("FractionalBits", 1, 14)))
 {
     // Validate output
     validate(CLAccessor(_target), _reference, tolerance_q);
 }
arm_compute::test::validation::FIXTURE_DATA_TEST_CASE (RunLarge , CLArithmeticAdditionFixedPointFixture< int16_t > , framework::DatasetMode::NIGHTLY , combine(combine(combine(datasets::LargeShapes(), ArithmeticAdditionQS16Dataset),framework::dataset::make("ConvertPolicy",{ConvertPolicy::SATURATE, ConvertPolicy::WRAP})),framework::dataset::make("FractionalBits", 1, 15)))
Definition at line 170 of file ArithmeticAddition.cpp.
References arm_compute::SATURATE, and arm_compute::WRAP.
                                                              { ConvertPolicy::SATURATE, ConvertPolicy::WRAP })),
                        framework::dataset::make("FractionalBits", 1, 15)))
 {
     // Validate output
     validate(CLAccessor(_target), _reference);
 }
arm_compute::test::validation::FIXTURE_DATA_TEST_CASE (RunLarge , NEActivationLayerFixture< float > , framework::DatasetMode::NIGHTLY , combine(combine(datasets::LargeShapes(), ActivationDataset), framework::dataset::make("DataType",DataType::F32)))
Definition at line 170 of file ActivationLayer.cpp.
References validate().
 {
     // Validate output
     validate(Accessor(_target), _reference, tolerance(_data_type, _function));
 }
arm_compute::test::validation::FIXTURE_DATA_TEST_CASE (RunLarge , CLActivationLayerFixture< half > , framework::DatasetMode::NIGHTLY , combine(combine(datasets::LargeShapes(), ActivationDataset),framework::dataset::make("DataType",DataType::F16)))
Definition at line 171 of file ActivationLayer.cpp.
References validate().
 {
     // Validate output
     validate(CLAccessor(_target), _reference, tolerance(_function, _data_type));
 }
arm_compute::test::validation::FIXTURE_DATA_TEST_CASE (RunSmall , CLFullyConnectedLayerFixedPointFixture< int16_t > , framework::DatasetMode::PRECOMMIT , combine(combine(combine(datasets::SmallFullyConnectedLayerDataset(),FullyConnectedParameters),framework::dataset::make("DataType",DataType::QS16)),framework::dataset::make("FractionalBits", 1, 14)))
Definition at line 171 of file FullyConnectedLayer.cpp.
References validate().
 {
     // Validate output
     validate(CLAccessor(_target), _reference, tolerance_fixed_point);
 }
arm_compute::test::validation::FIXTURE_DATA_TEST_CASE (RunLarge , NEFullyConnectedLayerFixedPointFixture< int8_t > , framework::DatasetMode::NIGHTLY , combine(combine(combine(datasets::LargeFullyConnectedLayerDataset(),FullyConnectedParameters),framework::dataset::make("DataType",DataType::QS8)),framework::dataset::make("FractionalBits", 1, 6)))
Definition at line 172 of file FullyConnectedLayer.cpp.
References validate().
 {
     // Validate output
     validate(Accessor(_target), _reference, tolerance_fixed_point);
 }
arm_compute::test::validation::FIXTURE_DATA_TEST_CASE (RunLarge , NEArithmeticAdditionFixedPointFixture< int16_t > , framework::DatasetMode::NIGHTLY , combine(combine(combine(datasets::LargeShapes(), ArithmeticAdditionQS16Dataset),framework::dataset::make("ConvertPolicy",{ConvertPolicy::SATURATE, ConvertPolicy::WRAP})),framework::dataset::make("FractionalBits", 1, 15)))
Definition at line 172 of file ArithmeticAddition.cpp.
References arm_compute::SATURATE, and arm_compute::WRAP.
                                                              { ConvertPolicy::SATURATE, ConvertPolicy::WRAP })),
                        framework::dataset::make("FractionalBits", 1, 15)))
 {
     // Validate output
     validate(Accessor(_target), _reference);
 }
arm_compute::test::validation::FIXTURE_DATA_TEST_CASE (RunLarge , CLArithmeticSubtractionFixedPointFixture< int16_t > , framework::DatasetMode::NIGHTLY , combine(combine(combine(datasets::LargeShapes(), ArithmeticSubtractionQS16Dataset),framework::dataset::make("ConvertPolicy",{ConvertPolicy::SATURATE, ConvertPolicy::WRAP})),framework::dataset::make("FractionalBits", 1, 15)))
Definition at line 172 of file ArithmeticSubtraction.cpp.
References arm_compute::SATURATE, and arm_compute::WRAP.
                                                              { ConvertPolicy::SATURATE, ConvertPolicy::WRAP })),
                        framework::dataset::make("FractionalBits", 1, 15)))
 {
     // Validate output
     validate(CLAccessor(_target), _reference);
 }
arm_compute::test::validation::FIXTURE_DATA_TEST_CASE (RunLarge , NEArithmeticSubtractionFixedPointFixture< int16_t > , framework::DatasetMode::NIGHTLY , combine(combine(combine(datasets::LargeShapes(), ArithmeticSubtractionQS16Dataset),framework::dataset::make("ConvertPolicy",{ConvertPolicy::SATURATE, ConvertPolicy::WRAP})),framework::dataset::make("FractionalBits", 1, 15)))
Definition at line 174 of file ArithmeticSubtraction.cpp.
References arm_compute::SATURATE, and arm_compute::WRAP.
                                                              { ConvertPolicy::SATURATE, ConvertPolicy::WRAP })),
                        framework::dataset::make("FractionalBits", 1, 15)))
 {
     // Validate output
     validate(Accessor(_target), _reference);
 }
arm_compute::test::validation::FIXTURE_DATA_TEST_CASE (RunSmall , NEScaleFixture< int16_t > , framework::DatasetMode::ALL , combine(combine(combine(datasets::SmallShapes(), framework::dataset::make("DataType",DataType::S16)),framework::dataset::make("InterpolationPolicy",{InterpolationPolicy::NEAREST_NEIGHBOR, InterpolationPolicy::BILINEAR})),datasets::BorderModes()))
Definition at line 174 of file Scale.cpp.
References arm_compute::BILINEAR, and arm_compute::NEAREST_NEIGHBOR.
                                                                                                                                                    { InterpolationPolicy::NEAREST_NEIGHBOR, InterpolationPolicy::BILINEAR })),
                                                                                                datasets::BorderModes()))
 {
     //Create valid region
     TensorInfo  src_info(_shape, 1, _data_type);
     ValidRegion valid_region = calculate_valid_region_scale(src_info, _reference.shape(), _policy, BorderSize(1), (_border_mode == BorderMode::UNDEFINED));
     // Validate output
     validate(Accessor(_target), _reference, valid_region, tolerance_s16, tolerance_num_s16);
 }
arm_compute::test::validation::FIXTURE_DATA_TEST_CASE (RunLarge , NEConvolutionLayerFixedPointFixture< int16_t > , framework::DatasetMode::NIGHTLY , combine(combine(combine(datasets::LargeConvolutionLayerDataset(),framework::dataset::make("ReshapeWeights",{true, false})),framework::dataset::make("DataType", DataType::QS16)),framework::dataset::make("FractionalBits", 1, 14)))
Definition at line 175 of file ConvolutionLayer.cpp.
                                                                                                                                                                { true, false })),
                                                                                                                         framework::dataset::make("DataType", DataType::QS16)),
                                                                                                                         framework::dataset::make("FractionalBits", 1, 14)))
 {
     // Validate output
     validate(Accessor(_target), _reference, tolerance_q);
 }
arm_compute::test::validation::FIXTURE_DATA_TEST_CASE (RunLarge , CLConvolutionLayerFixedPointFixture< int16_t > , framework::DatasetMode::NIGHTLY , combine(combine(combine(datasets::LargeConvolutionLayerDataset(),framework::dataset::make("ReshapeWeights",{true, false})),framework::dataset::make("DataType",DataType::QS16)),framework::dataset::make("FractionalBits", 1, 14)))
Definition at line 177 of file ConvolutionLayer.cpp.
                                                                                                                                                                { true, false })),
                                                                                                                         framework::dataset::make("DataType",
                                                                                                                                 DataType::QS16)),
                                                                                                                         framework::dataset::make("FractionalBits", 1, 14)))
 {
     // Validate output
     validate(CLAccessor(_target), _reference, tolerance_q);
 }
arm_compute::test::validation::FIXTURE_DATA_TEST_CASE (RunLarge , CLScaleFixture< uint8_t > , framework::DatasetMode::NIGHTLY , combine(combine(combine(datasets::LargeShapes(), framework::dataset::make("DataType", DataType::U8)),framework::dataset::make("InterpolationPolicy",{InterpolationPolicy::NEAREST_NEIGHBOR, InterpolationPolicy::BILINEAR})),datasets::BorderModes()))
Definition at line 178 of file Scale.cpp.
References arm_compute::BILINEAR, and arm_compute::NEAREST_NEIGHBOR.
                                                                                                                                                        { InterpolationPolicy::NEAREST_NEIGHBOR, InterpolationPolicy::BILINEAR })),
                                                                                                    datasets::BorderModes()))
 {
     //Create valid region
     TensorInfo        src_info(_shape, 1, _data_type);
     const ValidRegion valid_region = calculate_valid_region_scale(src_info, _reference.shape(), _policy, BorderSize(1), (_border_mode == BorderMode::UNDEFINED));
     // Validate output
     validate(CLAccessor(_target), _reference, valid_region, tolerance_u8);
 }
arm_compute::test::validation::FIXTURE_DATA_TEST_CASE (RunSmall , CLSobel5x5Fixture , framework::DatasetMode::PRECOMMIT , combine(combine(datasets::Small2DShapes(), datasets::BorderModes()), framework::dataset::make("Format",Format::U8)))
Definition at line 179 of file Sobel.cpp.
References arm_compute::test::shape_to_valid_region(), arm_compute::UNDEFINED, and validate().
 {
     // Validate output
     ValidRegion valid_region_x = shape_to_valid_region(_reference.first.shape(), (_border_mode == BorderMode::UNDEFINED), BorderSize(2));
     validate(CLAccessor(_target.first), _reference.first, valid_region_x);
     ValidRegion valid_region_y = shape_to_valid_region(_reference.second.shape(), (_border_mode == BorderMode::UNDEFINED), BorderSize(2));
     validate(CLAccessor(_target.second), _reference.second, valid_region_y);
 }
arm_compute::test::validation::FIXTURE_DATA_TEST_CASE (RunSmall , NESobel5x5Fixture , framework::DatasetMode::PRECOMMIT , combine(combine(datasets::Small2DShapes(), datasets::BorderModes()), framework::dataset::make("Format",Format::U8)))
Definition at line 180 of file Sobel.cpp.
References arm_compute::test::shape_to_valid_region(), arm_compute::UNDEFINED, and validate().
 {
     // Validate output
     ValidRegion valid_region_x = shape_to_valid_region(_reference.first.shape(), (_border_mode == BorderMode::UNDEFINED), BorderSize(2));
     validate(Accessor(_target.first), _reference.first, valid_region_x);
     ValidRegion valid_region_y = shape_to_valid_region(_reference.second.shape(), (_border_mode == BorderMode::UNDEFINED), BorderSize(2));
     validate(Accessor(_target.second), _reference.second, valid_region_y);
 }
arm_compute::test::validation::FIXTURE_DATA_TEST_CASE (RunLarge , CLFullyConnectedLayerFixedPointFixture< int16_t > , framework::DatasetMode::NIGHTLY , combine(combine(combine(datasets::LargeFullyConnectedLayerDataset(),FullyConnectedParameters),framework::dataset::make("DataType",DataType::QS16)),framework::dataset::make("FractionalBits", 1, 14)))
Definition at line 180 of file FullyConnectedLayer.cpp.
References validate().
 {
     // Validate output
     validate(CLAccessor(_target), _reference, tolerance_fixed_point);
 }
arm_compute::test::validation::FIXTURE_DATA_TEST_CASE (RunSmall , CLActivationLayerFixture< float > , framework::DatasetMode::PRECOMMIT , combine(combine(datasets::SmallShapes(), ActivationDataset), framework::dataset::make("DataType",DataType::F32)))
Definition at line 181 of file ActivationLayer.cpp.
References validate().
 {
     // Validate output
     validate(CLAccessor(_target), _reference, tolerance(_function, _data_type));
 }
arm_compute::test::validation::FIXTURE_DATA_TEST_CASE (RunSmall , CLArithmeticAdditionFixture< half > , framework::DatasetMode::ALL , combine(combine(datasets::SmallShapes(), ArithmeticAdditionFP16Dataset),framework::dataset::make("ConvertPolicy",{ConvertPolicy::SATURATE, ConvertPolicy::WRAP})))
Definition at line 182 of file ArithmeticAddition.cpp.
References arm_compute::SATURATE, and arm_compute::WRAP.
                                                                                                                                                { ConvertPolicy::SATURATE, ConvertPolicy::WRAP })))
 {
     // Validate output
     validate(CLAccessor(_target), _reference);
 }
arm_compute::test::validation::FIXTURE_DATA_TEST_CASE (RunSmall , CLArithmeticSubtractionFixture< half > , framework::DatasetMode::ALL , combine(combine(datasets::SmallShapes(), ArithmeticSubtractionFP16Dataset),framework::dataset::make("ConvertPolicy",{ConvertPolicy::SATURATE, ConvertPolicy::WRAP})))
Definition at line 184 of file ArithmeticSubtraction.cpp.
References arm_compute::SATURATE, and arm_compute::WRAP.
                                                                                                                                                   { ConvertPolicy::SATURATE, ConvertPolicy::WRAP })))
 {
     // Validate output
     validate(CLAccessor(_target), _reference);
 }
arm_compute::test::validation::FIXTURE_DATA_TEST_CASE (RunSmall , NEArithmeticAdditionFixture< half > , framework::DatasetMode::ALL , combine(combine(datasets::SmallShapes(), ArithmeticAdditionFP16Dataset),framework::dataset::make("ConvertPolicy",{ConvertPolicy::SATURATE, ConvertPolicy::WRAP})))
Definition at line 185 of file ArithmeticAddition.cpp.
References arm_compute::SATURATE, and arm_compute::WRAP.
                                                                                                                                                { ConvertPolicy::SATURATE, ConvertPolicy::WRAP })))
 {
     // Validate output
     validate(Accessor(_target), _reference);
 }
arm_compute::test::validation::FIXTURE_DATA_TEST_CASE (RunSmall , NEFullyConnectedLayerFixedPointFixture< int16_t > , framework::DatasetMode::PRECOMMIT , combine(combine(combine(datasets::SmallFullyConnectedLayerDataset(),FullyConnectedParameters),framework::dataset::make("DataType",DataType::QS16)),framework::dataset::make("FractionalBits", 1, 14)))
Definition at line 185 of file FullyConnectedLayer.cpp.
References validate().
 {
     // Validate output
     validate(Accessor(_target), _reference, tolerance_fixed_point);
 }
arm_compute::test::validation::FIXTURE_DATA_TEST_CASE (RunSmall , NEActivationLayerFixedPointFixture< int8_t > , framework::DatasetMode::PRECOMMIT , combine(combine(combine(datasets::SmallShapes(), ActivationDataset),framework::dataset::make("DataType",DataType::QS8)),framework::dataset::make("FractionalBits", 3, 6)))
Definition at line 186 of file ActivationLayer.cpp.
References validate().
 {
     // Validate output
     validate(Accessor(_target), _reference, tolerance(_data_type, _function));
 }
arm_compute::test::validation::FIXTURE_DATA_TEST_CASE (RunLarge , NEScaleFixture< int16_t > , framework::DatasetMode::NIGHTLY , combine(combine(combine(datasets::LargeShapes(), framework::dataset::make("DataType",DataType::S16)),framework::dataset::make("InterpolationPolicy",{InterpolationPolicy::NEAREST_NEIGHBOR, InterpolationPolicy::BILINEAR})),datasets::BorderModes()))
Definition at line 186 of file Scale.cpp.
References arm_compute::BILINEAR, and arm_compute::NEAREST_NEIGHBOR.
                                                                                                                                                        { InterpolationPolicy::NEAREST_NEIGHBOR, InterpolationPolicy::BILINEAR })),
                                                                                                    datasets::BorderModes()))
 {
     //Create valid region
     TensorInfo  src_info(_shape, 1, _data_type);
     ValidRegion valid_region = calculate_valid_region_scale(src_info, _reference.shape(), _policy, BorderSize(1), (_border_mode == BorderMode::UNDEFINED));
     // Validate output
     validate(Accessor(_target), _reference, valid_region, tolerance_s16, tolerance_num_s16);
 }
arm_compute::test::validation::FIXTURE_DATA_TEST_CASE (RunSmall , NEArithmeticSubtractionFixture< half > , framework::DatasetMode::ALL , combine(combine(datasets::SmallShapes(), ArithmeticSubtractionFP16Dataset),framework::dataset::make("ConvertPolicy",{ConvertPolicy::SATURATE, ConvertPolicy::WRAP})))
Definition at line 187 of file ArithmeticSubtraction.cpp.
References arm_compute::SATURATE, and arm_compute::WRAP.
                                                                                                                                                   { ConvertPolicy::SATURATE, ConvertPolicy::WRAP })))
 {
     // Validate output
     validate(Accessor(_target), _reference);
 }
arm_compute::test::validation::FIXTURE_DATA_TEST_CASE (RunLarge , CLActivationLayerFixture< float > , framework::DatasetMode::NIGHTLY , combine(combine(datasets::LargeShapes(), ActivationDataset), framework::dataset::make("DataType",DataType::F32)))
Definition at line 187 of file ActivationLayer.cpp.
References validate().
 {
     // Validate output
     validate(CLAccessor(_target), _reference, tolerance(_function, _data_type));
 }
arm_compute::test::validation::FIXTURE_DATA_TEST_CASE (RunSmall , CLDepthConvertToS32Fixture< uint8_t > , framework::DatasetMode::PRECOMMIT , combine(combine(combine(datasets::SmallShapes(), DepthConvertU8toS32Dataset),framework::dataset::make("ConvertPolicy",{ConvertPolicy::SATURATE, ConvertPolicy::WRAP})),DepthConvertShiftDataset))
Definition at line 189 of file DepthConvert.cpp.
References arm_compute::SATURATE, and arm_compute::WRAP.
                                                                                                                                                        { ConvertPolicy::SATURATE, ConvertPolicy::WRAP })),
                                                                                                                  DepthConvertShiftDataset))
 {
     // Validate output
     validate(CLAccessor(_target), _reference);
 }
arm_compute::test::validation::FIXTURE_DATA_TEST_CASE (RunSmall , NEDepthConvertToS32Fixture< uint8_t > , framework::DatasetMode::PRECOMMIT , combine(combine(combine(datasets::SmallShapes(), DepthConvertU8toS32Dataset),framework::dataset::make("ConvertPolicy",{ConvertPolicy::SATURATE, ConvertPolicy::WRAP})),DepthConvertShiftDataset))
Definition at line 189 of file DepthConvert.cpp.
References arm_compute::SATURATE, and arm_compute::WRAP.
                                                                                                                                                        { ConvertPolicy::SATURATE, ConvertPolicy::WRAP })),
                                                                                                                  DepthConvertShiftDataset))
 {
     // Validate output
     validate(Accessor(_target), _reference);
 }
arm_compute::test::validation::FIXTURE_DATA_TEST_CASE (RunLarge , CLSobel5x5Fixture , framework::DatasetMode::NIGHTLY , combine(combine(datasets::Large2DShapes(), datasets::BorderModes()), framework::dataset::make("Format",Format::U8)))
Definition at line 190 of file Sobel.cpp.
References arm_compute::test::shape_to_valid_region(), arm_compute::UNDEFINED, and validate().
 {
     // Validate output
     ValidRegion valid_region_x = shape_to_valid_region(_reference.first.shape(), (_border_mode == BorderMode::UNDEFINED), BorderSize(2));
     validate(CLAccessor(_target.first), _reference.first, valid_region_x);
     ValidRegion valid_region_y = shape_to_valid_region(_reference.second.shape(), (_border_mode == BorderMode::UNDEFINED), BorderSize(2));
     validate(CLAccessor(_target.second), _reference.second, valid_region_y);
 }
arm_compute::test::validation::FIXTURE_DATA_TEST_CASE (RunSmall , CLScaleFixture< int16_t > , framework::DatasetMode::ALL , combine(combine(combine(datasets::SmallShapes(), framework::dataset::make("DataType", DataType::S16)),framework::dataset::make("InterpolationPolicy",{InterpolationPolicy::NEAREST_NEIGHBOR, InterpolationPolicy::BILINEAR})),datasets::BorderModes()))
Definition at line 191 of file Scale.cpp.
References arm_compute::BILINEAR, and arm_compute::NEAREST_NEIGHBOR.
                                                                                                                                                    { InterpolationPolicy::NEAREST_NEIGHBOR, InterpolationPolicy::BILINEAR })),
                                                                                                datasets::BorderModes()))
 {
     //Create valid region
     TensorInfo        src_info(_shape, 1, _data_type);
     const ValidRegion valid_region = calculate_valid_region_scale(src_info, _reference.shape(), _policy, BorderSize(1), (_border_mode == BorderMode::UNDEFINED));
     // Validate output
     validate(CLAccessor(_target), _reference, valid_region, tolerance_s16);
 }
arm_compute::test::validation::FIXTURE_DATA_TEST_CASE (RunLarge , NESobel5x5Fixture , framework::DatasetMode::NIGHTLY , combine(combine(datasets::Large2DShapes(), datasets::BorderModes()), framework::dataset::make("Format",Format::U8)))
Definition at line 191 of file Sobel.cpp.
References arm_compute::test::shape_to_valid_region(), arm_compute::UNDEFINED, and validate().
 {
     // Validate output
     ValidRegion valid_region_x = shape_to_valid_region(_reference.first.shape(), (_border_mode == BorderMode::UNDEFINED), BorderSize(2));
     validate(Accessor(_target.first), _reference.first, valid_region_x);
     ValidRegion valid_region_y = shape_to_valid_region(_reference.second.shape(), (_border_mode == BorderMode::UNDEFINED), BorderSize(2));
     validate(Accessor(_target.second), _reference.second, valid_region_y);
 }
arm_compute::test::validation::FIXTURE_DATA_TEST_CASE (RunLarge , NEFullyConnectedLayerFixedPointFixture< int16_t > , framework::DatasetMode::NIGHTLY , combine(combine(combine(datasets::LargeFullyConnectedLayerDataset(),FullyConnectedParameters),framework::dataset::make("DataType",DataType::QS16)),framework::dataset::make("FractionalBits", 1, 14)))
Definition at line 194 of file FullyConnectedLayer.cpp.
References validate().
 {
     // Validate output
     validate(Accessor(_target), _reference, tolerance_fixed_point);
 }
arm_compute::test::validation::FIXTURE_DATA_TEST_CASE (RunLarge , NEActivationLayerFixedPointFixture< int8_t > , framework::DatasetMode::NIGHTLY , combine(combine(combine(datasets::LargeShapes(), ActivationDataset),framework::dataset::make("DataType",DataType::QS8)),framework::dataset::make("FractionalBits", 3, 6)))
Definition at line 194 of file ActivationLayer.cpp.
References validate().
 {
     // Validate output
     validate(Accessor(_target), _reference, tolerance(_data_type, _function));
 }
arm_compute::test::validation::FIXTURE_DATA_TEST_CASE (RunLarge , CLDepthConvertToS32Fixture< uint8_t > , framework::DatasetMode::NIGHTLY , combine(combine(combine(datasets::LargeShapes(), DepthConvertU8toS32Dataset),framework::dataset::make("ConvertPolicy",{ConvertPolicy::SATURATE, ConvertPolicy::WRAP})),DepthConvertShiftDataset))
Definition at line 197 of file DepthConvert.cpp.
References arm_compute::SATURATE, and arm_compute::WRAP.
                                                                                                                                                              { ConvertPolicy::SATURATE, ConvertPolicy::WRAP })),
                                                                                                                DepthConvertShiftDataset))
 {
     // Validate output
     validate(CLAccessor(_target), _reference);
 }
arm_compute::test::validation::FIXTURE_DATA_TEST_CASE (RunLarge , NEDepthConvertToS32Fixture< uint8_t > , framework::DatasetMode::NIGHTLY , combine(combine(combine(datasets::LargeShapes(), DepthConvertU8toS32Dataset),framework::dataset::make("ConvertPolicy",{ConvertPolicy::SATURATE, ConvertPolicy::WRAP})),DepthConvertShiftDataset))
Definition at line 197 of file DepthConvert.cpp.
References arm_compute::SATURATE, and arm_compute::WRAP.
                                                                                                                                                              { ConvertPolicy::SATURATE, ConvertPolicy::WRAP })),
                                                                                                                DepthConvertShiftDataset))
 {
     // Validate output
     validate(Accessor(_target), _reference);
 }
arm_compute::test::validation::FIXTURE_DATA_TEST_CASE (RunLarge , CLScaleFixture< int16_t > , framework::DatasetMode::NIGHTLY , combine(combine(combine(datasets::LargeShapes(), framework::dataset::make("DataType", DataType::S16)),framework::dataset::make("InterpolationPolicy",{InterpolationPolicy::NEAREST_NEIGHBOR, InterpolationPolicy::BILINEAR})),datasets::BorderModes()))
Definition at line 202 of file Scale.cpp.
References arm_compute::BILINEAR, and arm_compute::NEAREST_NEIGHBOR.
                                                                                                                                                        { InterpolationPolicy::NEAREST_NEIGHBOR, InterpolationPolicy::BILINEAR })),
                                                                                                    datasets::BorderModes()))
 {
     //Create valid region
     TensorInfo        src_info(_shape, 1, _data_type);
     const ValidRegion valid_region = calculate_valid_region_scale(src_info, _reference.shape(), _policy, BorderSize(1), (_border_mode == BorderMode::UNDEFINED));
     // Validate output
     validate(CLAccessor(_target), _reference, valid_region, tolerance_s16);
 }
arm_compute::test::validation::FIXTURE_DATA_TEST_CASE (RunSmall , CLActivationLayerFixedPointFixture< int8_t > , framework::DatasetMode::PRECOMMIT , combine(combine(combine(datasets::SmallShapes(), ActivationDataset),framework::dataset::make("DataType",DataType::QS8)),framework::dataset::make("FractionalBits", 3, 6)))
Definition at line 203 of file ActivationLayer.cpp.
References validate().
 {
     // Validate output
     validate(CLAccessor(_target), _reference, tolerance(_function, _data_type));
 }
arm_compute::test::validation::FIXTURE_DATA_TEST_CASE (RunSmall , NEActivationLayerFixedPointFixture< int16_t > , framework::DatasetMode::PRECOMMIT , combine(combine(combine(datasets::SmallShapes(), ActivationDataset),framework::dataset::make("DataType",DataType::QS16)),framework::dataset::make("FractionalBits", 1, 14)))
Definition at line 206 of file ActivationLayer.cpp.
References validate().
 {
     // Validate output
     validate(Accessor(_target), _reference, tolerance(_data_type, _function));
 }
arm_compute::test::validation::FIXTURE_DATA_TEST_CASE (RunLarge , CLActivationLayerFixedPointFixture< int8_t > , framework::DatasetMode::NIGHTLY , combine(combine(combine(datasets::LargeShapes(), ActivationDataset),framework::dataset::make("DataType",DataType::QS8)),framework::dataset::make("FractionalBits", 3, 6)))
Definition at line 211 of file ActivationLayer.cpp.
References validate().
 {
     // Validate output
     validate(CLAccessor(_target), _reference, tolerance(_function, _data_type));
 }
arm_compute::test::validation::FIXTURE_DATA_TEST_CASE (RunSmall , CLArithmeticAdditionFixture< float > , framework::DatasetMode::PRECOMMIT , combine(combine(datasets::SmallShapes(), ArithmeticAdditionFP32Dataset),framework::dataset::make("ConvertPolicy",{ConvertPolicy::SATURATE, ConvertPolicy::WRAP})))
Definition at line 214 of file ArithmeticAddition.cpp.
References arm_compute::SATURATE, and arm_compute::WRAP.
                                                                                                                                                       { ConvertPolicy::SATURATE, ConvertPolicy::WRAP })))
 {
     // Validate output
     validate(CLAccessor(_target), _reference);
 }
arm_compute::test::validation::FIXTURE_DATA_TEST_CASE (RunLarge , NEActivationLayerFixedPointFixture< int16_t > , framework::DatasetMode::NIGHTLY , combine(combine(combine(datasets::LargeShapes(), ActivationDataset),framework::dataset::make("DataType",DataType::QS16)),framework::dataset::make("FractionalBits", 1, 14)))
Definition at line 214 of file ActivationLayer.cpp.
References validate().
 {
     // Validate output
     validate(Accessor(_target), _reference, tolerance(_data_type, _function));
 }
arm_compute::test::validation::FIXTURE_DATA_TEST_CASE (RunSmall , CLArithmeticSubtractionFixture< float > , framework::DatasetMode::PRECOMMIT , combine(combine(datasets::SmallShapes(), ArithmeticSubtractionFP32Dataset),framework::dataset::make("ConvertPolicy",{ConvertPolicy::SATURATE, ConvertPolicy::WRAP})))
Definition at line 216 of file ArithmeticSubtraction.cpp.
References arm_compute::SATURATE, and arm_compute::WRAP.
                                                                                                                                                          { ConvertPolicy::SATURATE, ConvertPolicy::WRAP })))
 {
     // Validate output
     validate(CLAccessor(_target), _reference);
 }
arm_compute::test::validation::FIXTURE_DATA_TEST_CASE (RunSmall , NEArithmeticAdditionFixture< float > , framework::DatasetMode::PRECOMMIT , combine(combine(datasets::SmallShapes(), ArithmeticAdditionFP32Dataset),framework::dataset::make("ConvertPolicy",{ConvertPolicy::SATURATE, ConvertPolicy::WRAP})))
Definition at line 218 of file ArithmeticAddition.cpp.
References arm_compute::SATURATE, and arm_compute::WRAP.
                                                                                                                                                       { ConvertPolicy::SATURATE, ConvertPolicy::WRAP })))
 {
     // Validate output
     validate(Accessor(_target), _reference);
 }
arm_compute::test::validation::FIXTURE_DATA_TEST_CASE (RunSmall , NEArithmeticSubtractionFixture< float > , framework::DatasetMode::PRECOMMIT , combine(combine(datasets::SmallShapes(), ArithmeticSubtractionFP32Dataset),framework::dataset::make("ConvertPolicy",{ConvertPolicy::SATURATE, ConvertPolicy::WRAP})))
Definition at line 220 of file ArithmeticSubtraction.cpp.
References arm_compute::SATURATE, and arm_compute::WRAP.
                                                                                                                                                          { ConvertPolicy::SATURATE, ConvertPolicy::WRAP })))
 {
     // Validate output
     validate(Accessor(_target), _reference);
 }
arm_compute::test::validation::FIXTURE_DATA_TEST_CASE (RunLarge , CLArithmeticAdditionFixture< float > , framework::DatasetMode::NIGHTLY , combine(combine(datasets::LargeShapes(), ArithmeticAdditionFP32Dataset),framework::dataset::make("ConvertPolicy",{ConvertPolicy::SATURATE, ConvertPolicy::WRAP})))
Definition at line 221 of file ArithmeticAddition.cpp.
References arm_compute::SATURATE, and arm_compute::WRAP.
                                                                                                                                                     { ConvertPolicy::SATURATE, ConvertPolicy::WRAP })))
 {
     // Validate output
     validate(CLAccessor(_target), _reference);
 }
arm_compute::test::validation::FIXTURE_DATA_TEST_CASE (RunLarge , CLArithmeticSubtractionFixture< float > , framework::DatasetMode::NIGHTLY , combine(combine(datasets::LargeShapes(), ArithmeticSubtractionFP32Dataset),framework::dataset::make("ConvertPolicy",{ConvertPolicy::SATURATE, ConvertPolicy::WRAP})))
Definition at line 223 of file ArithmeticSubtraction.cpp.
References arm_compute::SATURATE, and arm_compute::WRAP.
                                                                                                                                                        { ConvertPolicy::SATURATE, ConvertPolicy::WRAP })))
 {
     // Validate output
     validate(CLAccessor(_target), _reference);
 }
arm_compute::test::validation::FIXTURE_DATA_TEST_CASE (RunSmall , CLActivationLayerFixedPointFixture< int16_t > , framework::DatasetMode::PRECOMMIT , combine(combine(combine(datasets::SmallShapes(), ActivationDataset),framework::dataset::make("DataType",DataType::QS16)),framework::dataset::make("FractionalBits", 1, 14)))
Definition at line 223 of file ActivationLayer.cpp.
References validate().
 {
     // Validate output
     validate(CLAccessor(_target), _reference, tolerance(_function, _data_type));
 }
arm_compute::test::validation::FIXTURE_DATA_TEST_CASE (RunLarge , NEArithmeticAdditionFixture< float > , framework::DatasetMode::NIGHTLY , combine(combine(datasets::LargeShapes(), ArithmeticAdditionFP32Dataset),framework::dataset::make("ConvertPolicy",{ConvertPolicy::SATURATE, ConvertPolicy::WRAP})))
Definition at line 225 of file ArithmeticAddition.cpp.
References arm_compute::SATURATE, and arm_compute::WRAP.
                                                                                                                                                     { ConvertPolicy::SATURATE, ConvertPolicy::WRAP })))
 {
     // Validate output
     validate(Accessor(_target), _reference);
 }
arm_compute::test::validation::FIXTURE_DATA_TEST_CASE (RunLarge , NEArithmeticSubtractionFixture< float > , framework::DatasetMode::NIGHTLY , combine(combine(datasets::LargeShapes(), ArithmeticSubtractionFP32Dataset),framework::dataset::make("ConvertPolicy",{ConvertPolicy::SATURATE, ConvertPolicy::WRAP})))
Definition at line 227 of file ArithmeticSubtraction.cpp.
References arm_compute::SATURATE, and arm_compute::WRAP.
                                                                                                                                                        { ConvertPolicy::SATURATE, ConvertPolicy::WRAP })))
 {
     // Validate output
     validate(Accessor(_target), _reference);
 }
arm_compute::test::validation::FIXTURE_DATA_TEST_CASE (RunSmall , NEDepthConvertToU8Fixture< uint16_t > , framework::DatasetMode::PRECOMMIT , combine(combine(combine(datasets::SmallShapes(), DepthConvertU16toU8Dataset),framework::dataset::make("ConvertPolicy",{ConvertPolicy::SATURATE, ConvertPolicy::WRAP})),DepthConvertShiftDataset))
Definition at line 231 of file DepthConvert.cpp.
References arm_compute::SATURATE, and arm_compute::WRAP.
                                                                                                                                                        { ConvertPolicy::SATURATE, ConvertPolicy::WRAP })),
                                                                                                                  DepthConvertShiftDataset))
 {
     // Validate output
     validate(Accessor(_target), _reference);
 }
arm_compute::test::validation::FIXTURE_DATA_TEST_CASE (RunSmall , CLDepthConvertToU8Fixture< uint16_t > , framework::DatasetMode::PRECOMMIT , combine(combine(combine(datasets::SmallShapes(), DepthConvertU16toU8Dataset),framework::dataset::make("ConvertPolicy",{ConvertPolicy::SATURATE, ConvertPolicy::WRAP})),DepthConvertShiftDataset))
Definition at line 231 of file DepthConvert.cpp.
References arm_compute::SATURATE, and arm_compute::WRAP.
                                                                                                                                                        { ConvertPolicy::SATURATE, ConvertPolicy::WRAP })),
                                                                                                                  DepthConvertShiftDataset))
 {
     // Validate output
     validate(CLAccessor(_target), _reference);
 }
arm_compute::test::validation::FIXTURE_DATA_TEST_CASE (RunLarge , CLActivationLayerFixedPointFixture< int16_t > , framework::DatasetMode::NIGHTLY , combine(combine(combine(datasets::LargeShapes(), ActivationDataset),framework::dataset::make("DataType",DataType::QS16)),framework::dataset::make("FractionalBits", 1, 14)))
Definition at line 231 of file ActivationLayer.cpp.
References validate().
 {
     // Validate output
     validate(CLAccessor(_target), _reference, tolerance(_function, _data_type));
 }
arm_compute::test::validation::FIXTURE_DATA_TEST_CASE (RunLarge , CLDepthConvertToU8Fixture< uint16_t > , framework::DatasetMode::NIGHTLY , combine(combine(combine(datasets::LargeShapes(), DepthConvertU16toU8Dataset),framework::dataset::make("ConvertPolicy",{ConvertPolicy::SATURATE, ConvertPolicy::WRAP})),DepthConvertShiftDataset))
Definition at line 238 of file DepthConvert.cpp.
References arm_compute::SATURATE, and arm_compute::WRAP.
                                                                                                                                                              { ConvertPolicy::SATURATE, ConvertPolicy::WRAP })),
                                                                                                                DepthConvertShiftDataset))
 {
     // Validate output
     validate(CLAccessor(_target), _reference);
 }
arm_compute::test::validation::FIXTURE_DATA_TEST_CASE (RunLarge , NEDepthConvertToU8Fixture< uint16_t > , framework::DatasetMode::NIGHTLY , combine(combine(combine(datasets::LargeShapes(), DepthConvertU16toU8Dataset),framework::dataset::make("ConvertPolicy",{ConvertPolicy::SATURATE, ConvertPolicy::WRAP})),DepthConvertShiftDataset))
Definition at line 238 of file DepthConvert.cpp.
References arm_compute::SATURATE, and arm_compute::WRAP.
                                                                                                                                                              { ConvertPolicy::SATURATE, ConvertPolicy::WRAP })),
                                                                                                                DepthConvertShiftDataset))
 {
     // Validate output
     validate(Accessor(_target), _reference);
 }
arm_compute::test::validation::FIXTURE_DATA_TEST_CASE (RunSmall , CLSobel7x7Fixture , framework::DatasetMode::PRECOMMIT , combine(combine(datasets::Small2DShapes(), datasets::BorderModes()), framework::dataset::make("Format",Format::U8)))
Definition at line 256 of file Sobel.cpp.
References arm_compute::test::shape_to_valid_region(), arm_compute::UNDEFINED, and validate().
 {
     // Validate output
     ValidRegion valid_region_x = shape_to_valid_region(_reference.first.shape(), (_border_mode == BorderMode::UNDEFINED), BorderSize(3));
     validate(CLAccessor(_target.first), _reference.first, valid_region_x);
     ValidRegion valid_region_y = shape_to_valid_region(_reference.second.shape(), (_border_mode == BorderMode::UNDEFINED), BorderSize(3));
     validate(CLAccessor(_target.second), _reference.second, valid_region_y);
 }
arm_compute::test::validation::FIXTURE_DATA_TEST_CASE (RunSmall , NESobel7x7Fixture , framework::DatasetMode::PRECOMMIT , combine(combine(datasets::Small2DShapes(), datasets::BorderModes()), framework::dataset::make("Format",Format::U8)))
Definition at line 257 of file Sobel.cpp.
References arm_compute::test::shape_to_valid_region(), arm_compute::UNDEFINED, and validate().
 {
     // Validate output
     ValidRegion valid_region_x = shape_to_valid_region(_reference.first.shape(), (_border_mode == BorderMode::UNDEFINED), BorderSize(3));
     validate(Accessor(_target.first), _reference.first, valid_region_x);
     ValidRegion valid_region_y = shape_to_valid_region(_reference.second.shape(), (_border_mode == BorderMode::UNDEFINED), BorderSize(3));
     validate(Accessor(_target.second), _reference.second, valid_region_y);
 }
arm_compute::test::validation::FIXTURE_DATA_TEST_CASE (RunLarge , CLSobel7x7Fixture , framework::DatasetMode::NIGHTLY , combine(combine(datasets::Large2DShapes(), datasets::BorderModes()), framework::dataset::make("Format",Format::U8)))
Definition at line 267 of file Sobel.cpp.
References arm_compute::test::shape_to_valid_region(), arm_compute::UNDEFINED, and validate().
 {
     // Validate output
     ValidRegion valid_region_x = shape_to_valid_region(_reference.first.shape(), (_border_mode == BorderMode::UNDEFINED), BorderSize(3));
     validate(CLAccessor(_target.first), _reference.first, valid_region_x);
     ValidRegion valid_region_y = shape_to_valid_region(_reference.second.shape(), (_border_mode == BorderMode::UNDEFINED), BorderSize(3));
     validate(CLAccessor(_target.second), _reference.second, valid_region_y);
 }
arm_compute::test::validation::FIXTURE_DATA_TEST_CASE (RunLarge , NESobel7x7Fixture , framework::DatasetMode::NIGHTLY , combine(combine(datasets::Large2DShapes(), datasets::BorderModes()), framework::dataset::make("Format",Format::U8)))
Definition at line 268 of file Sobel.cpp.
References arm_compute::test::shape_to_valid_region(), arm_compute::UNDEFINED, and validate().
 {
     // Validate output
     ValidRegion valid_region_x = shape_to_valid_region(_reference.first.shape(), (_border_mode == BorderMode::UNDEFINED), BorderSize(3));
     validate(Accessor(_target.first), _reference.first, valid_region_x);
     ValidRegion valid_region_y = shape_to_valid_region(_reference.second.shape(), (_border_mode == BorderMode::UNDEFINED), BorderSize(3));
     validate(Accessor(_target.second), _reference.second, valid_region_y);
 }
arm_compute::test::validation::FIXTURE_DATA_TEST_CASE (RunSmall , NEDepthConvertToU32Fixture< uint16_t > , framework::DatasetMode::PRECOMMIT , combine(combine(combine(datasets::SmallShapes(), DepthConvertU16toU32Dataset),framework::dataset::make("ConvertPolicy",{ConvertPolicy::SATURATE, ConvertPolicy::WRAP})),DepthConvertShiftDataset))
Definition at line 272 of file DepthConvert.cpp.
References arm_compute::SATURATE, and arm_compute::WRAP.
                                                                                                                                                         { ConvertPolicy::SATURATE, ConvertPolicy::WRAP })),
                                                                                                                   DepthConvertShiftDataset))
 {
     // Validate output
     validate(Accessor(_target), _reference);
 }
arm_compute::test::validation::FIXTURE_DATA_TEST_CASE (RunSmall , CLDepthConvertToU32Fixture< uint16_t > , framework::DatasetMode::PRECOMMIT , combine(combine(combine(datasets::SmallShapes(), DepthConvertU16toU32Dataset),framework::dataset::make("ConvertPolicy",{ConvertPolicy::SATURATE, ConvertPolicy::WRAP})),DepthConvertShiftDataset))
Definition at line 272 of file DepthConvert.cpp.
References arm_compute::SATURATE, and arm_compute::WRAP.
                                                                                                                                                         { ConvertPolicy::SATURATE, ConvertPolicy::WRAP })),
                                                                                                                   DepthConvertShiftDataset))
 {
     // Validate output
     validate(CLAccessor(_target), _reference);
 }
arm_compute::test::validation::FIXTURE_DATA_TEST_CASE (RunLarge , CLDepthConvertToU32Fixture< uint16_t > , framework::DatasetMode::NIGHTLY , combine(combine(combine(datasets::LargeShapes(), DepthConvertU16toU32Dataset),framework::dataset::make("ConvertPolicy",{ConvertPolicy::SATURATE, ConvertPolicy::WRAP})),DepthConvertShiftDataset))
Definition at line 279 of file DepthConvert.cpp.
References arm_compute::SATURATE, and arm_compute::WRAP.
                                                                                                                                                               { ConvertPolicy::SATURATE, ConvertPolicy::WRAP })),
                                                                                                                 DepthConvertShiftDataset))
 {
     // Validate output
     validate(CLAccessor(_target), _reference);
 }
arm_compute::test::validation::FIXTURE_DATA_TEST_CASE (RunLarge , NEDepthConvertToU32Fixture< uint16_t > , framework::DatasetMode::NIGHTLY , combine(combine(combine(datasets::LargeShapes(), DepthConvertU16toU32Dataset),framework::dataset::make("ConvertPolicy",{ConvertPolicy::SATURATE, ConvertPolicy::WRAP})),DepthConvertShiftDataset))
Definition at line 279 of file DepthConvert.cpp.
References arm_compute::SATURATE, and arm_compute::WRAP.
                                                                                                                                                               { ConvertPolicy::SATURATE, ConvertPolicy::WRAP })),
                                                                                                                 DepthConvertShiftDataset))
 {
     // Validate output
     validate(Accessor(_target), _reference);
 }
arm_compute::test::validation::FIXTURE_DATA_TEST_CASE (RunSmall , CLDepthConvertToU8Fixture< int16_t > , framework::DatasetMode::PRECOMMIT , combine(combine(combine(datasets::SmallShapes(), DepthConvertS16toU8Dataset),framework::dataset::make("ConvertPolicy",{ConvertPolicy::SATURATE, ConvertPolicy::WRAP})),DepthConvertShiftDataset))
Definition at line 313 of file DepthConvert.cpp.
References arm_compute::SATURATE, and arm_compute::WRAP.
                                                                                                                                                               { ConvertPolicy::SATURATE, ConvertPolicy::WRAP })),
                                                                                                                 DepthConvertShiftDataset))
 {
     // Validate output
     validate(CLAccessor(_target), _reference);
 }
arm_compute::test::validation::FIXTURE_DATA_TEST_CASE (RunSmall , NEDepthConvertToU8Fixture< int16_t > , framework::DatasetMode::PRECOMMIT , combine(combine(combine(datasets::SmallShapes(), DepthConvertS16toU8Dataset),framework::dataset::make("ConvertPolicy",{ConvertPolicy::SATURATE, ConvertPolicy::WRAP})),DepthConvertShiftDataset))
Definition at line 313 of file DepthConvert.cpp.
References arm_compute::SATURATE, and arm_compute::WRAP.
                                                                                                                                                               { ConvertPolicy::SATURATE, ConvertPolicy::WRAP })),
                                                                                                                 DepthConvertShiftDataset))
 {
     // Validate output
     validate(Accessor(_target), _reference);
 }
arm_compute::test::validation::FIXTURE_DATA_TEST_CASE (RunLarge , CLDepthConvertToU8Fixture< int16_t > , framework::DatasetMode::NIGHTLY , combine(combine(combine(datasets::LargeShapes(), DepthConvertS16toU8Dataset),framework::dataset::make("ConvertPolicy",{ConvertPolicy::SATURATE, ConvertPolicy::WRAP})),DepthConvertShiftDataset))
Definition at line 320 of file DepthConvert.cpp.
References arm_compute::SATURATE, and arm_compute::WRAP.
                                                                                                                                                             { ConvertPolicy::SATURATE, ConvertPolicy::WRAP })),
                                                                                                               DepthConvertShiftDataset))
 {
     // Validate output
     validate(CLAccessor(_target), _reference);
 }
arm_compute::test::validation::FIXTURE_DATA_TEST_CASE (RunLarge , NEDepthConvertToU8Fixture< int16_t > , framework::DatasetMode::NIGHTLY , combine(combine(combine(datasets::LargeShapes(), DepthConvertS16toU8Dataset),framework::dataset::make("ConvertPolicy",{ConvertPolicy::SATURATE, ConvertPolicy::WRAP})),DepthConvertShiftDataset))
Definition at line 320 of file DepthConvert.cpp.
References arm_compute::SATURATE, and arm_compute::WRAP.
                                                                                                                                                             { ConvertPolicy::SATURATE, ConvertPolicy::WRAP })),
                                                                                                               DepthConvertShiftDataset))
 {
     // Validate output
     validate(Accessor(_target), _reference);
 }
arm_compute::test::validation::FIXTURE_DATA_TEST_CASE (RunSmall , NEDepthConvertToS32Fixture< int16_t > , framework::DatasetMode::PRECOMMIT , combine(combine(combine(datasets::SmallShapes(), DepthConvertS16toS32Dataset),framework::dataset::make("ConvertPolicy",{ConvertPolicy::SATURATE, ConvertPolicy::WRAP})),DepthConvertShiftDataset))
Definition at line 354 of file DepthConvert.cpp.
References arm_compute::SATURATE, and arm_compute::WRAP.
                                                                                                                                                        { ConvertPolicy::SATURATE, ConvertPolicy::WRAP })),
                                                                                                                  DepthConvertShiftDataset))
 {
     // Validate output
     validate(Accessor(_target), _reference);
 }
arm_compute::test::validation::FIXTURE_DATA_TEST_CASE (RunSmall , CLDepthConvertToS32Fixture< int16_t > , framework::DatasetMode::PRECOMMIT , combine(combine(combine(datasets::SmallShapes(), DepthConvertS16toS32Dataset),framework::dataset::make("ConvertPolicy",{ConvertPolicy::SATURATE, ConvertPolicy::WRAP})),DepthConvertShiftDataset))
Definition at line 354 of file DepthConvert.cpp.
References arm_compute::SATURATE, and arm_compute::WRAP.
                                                                                                                                                        { ConvertPolicy::SATURATE, ConvertPolicy::WRAP })),
                                                                                                                  DepthConvertShiftDataset))
 {
     // Validate output
     validate(CLAccessor(_target), _reference);
 }
arm_compute::test::validation::FIXTURE_DATA_TEST_CASE (RunLarge , NEDepthConvertToS32Fixture< int16_t > , framework::DatasetMode::NIGHTLY , combine(combine(combine(datasets::LargeShapes(), DepthConvertS16toS32Dataset),framework::dataset::make("ConvertPolicy",{ConvertPolicy::SATURATE, ConvertPolicy::WRAP})),DepthConvertShiftDataset))
Definition at line 361 of file DepthConvert.cpp.
References arm_compute::SATURATE, and arm_compute::WRAP.
                                                                                                                                                              { ConvertPolicy::SATURATE, ConvertPolicy::WRAP })),
                                                                                                                DepthConvertShiftDataset))
 {
     // Validate output
     validate(Accessor(_target), _reference);
 }
arm_compute::test::validation::FIXTURE_DATA_TEST_CASE (RunLarge , CLDepthConvertToS32Fixture< int16_t > , framework::DatasetMode::NIGHTLY , combine(combine(combine(datasets::LargeShapes(), DepthConvertS16toS32Dataset),framework::dataset::make("ConvertPolicy",{ConvertPolicy::SATURATE, ConvertPolicy::WRAP})),DepthConvertShiftDataset))
Definition at line 361 of file DepthConvert.cpp.
References arm_compute::SATURATE, and arm_compute::WRAP.
                                                                                                                                                              { ConvertPolicy::SATURATE, ConvertPolicy::WRAP })),
                                                                                                                DepthConvertShiftDataset))
 {
     // Validate output
     validate(CLAccessor(_target), _reference);
 }
arm_compute::test::validation::FIXTURE_DATA_TEST_CASE (RunSmallQS8 , CLDepthConvertToFP32FixedPointFixture< int8_t > , framework::DatasetMode::PRECOMMIT , combine(combine(combine(datasets::SmallShapes(), DepthConvertQS8toFP32Dataset),framework::dataset::make("ConvertPolicy",{ConvertPolicy::SATURATE, ConvertPolicy::WRAP})),DepthConvertFixedPointQuantizedDataset))
Definition at line 395 of file DepthConvert.cpp.
References arm_compute::SATURATE, and arm_compute::WRAP.
                                                              { ConvertPolicy::SATURATE, ConvertPolicy::WRAP })),
                        DepthConvertFixedPointQuantizedDataset))
 {
     // Validate output
     validate(CLAccessor(_target), _reference);
 }
arm_compute::test::validation::FIXTURE_DATA_TEST_CASE (RunSmallQS8 , NEDepthConvertToFP32FixedPointFixture< int8_t > , framework::DatasetMode::PRECOMMIT , combine(combine(combine(datasets::SmallShapes(), DepthConvertQS8toFP32Dataset),framework::dataset::make("ConvertPolicy",{ConvertPolicy::SATURATE, ConvertPolicy::WRAP})),DepthConvertFixedPointQuantizedDataset))
Definition at line 395 of file DepthConvert.cpp.
References arm_compute::SATURATE, and arm_compute::WRAP.
                                                              { ConvertPolicy::SATURATE, ConvertPolicy::WRAP })),
                        DepthConvertFixedPointQuantizedDataset))
 {
     // Validate output
     validate(Accessor(_target), _reference);
 }
arm_compute::test::validation::FIXTURE_DATA_TEST_CASE (RunSmallQS16 , CLDepthConvertToFP32FixedPointFixture< int16_t > , framework::DatasetMode::PRECOMMIT , combine(combine(combine(datasets::SmallShapes(), DepthConvertQS16toFP32Dataset),framework::dataset::make("ConvertPolicy",{ConvertPolicy::SATURATE, ConvertPolicy::WRAP})),DepthConvertFixedPointQuantizedDataset))
Definition at line 402 of file DepthConvert.cpp.
References arm_compute::SATURATE, and arm_compute::WRAP.
                                                              { ConvertPolicy::SATURATE, ConvertPolicy::WRAP })),
                        DepthConvertFixedPointQuantizedDataset))
 {
     // Validate output
     validate(CLAccessor(_target), _reference);
 }
arm_compute::test::validation::FIXTURE_DATA_TEST_CASE (RunSmallQS16 , NEDepthConvertToFP32FixedPointFixture< int16_t > , framework::DatasetMode::PRECOMMIT , combine(combine(combine(datasets::SmallShapes(), DepthConvertQS16toFP32Dataset),framework::dataset::make("ConvertPolicy",{ConvertPolicy::SATURATE, ConvertPolicy::WRAP})),DepthConvertFixedPointQuantizedDataset))
Definition at line 402 of file DepthConvert.cpp.
References arm_compute::SATURATE, and arm_compute::WRAP.
                                                              { ConvertPolicy::SATURATE, ConvertPolicy::WRAP })),
                        DepthConvertFixedPointQuantizedDataset))
 {
     // Validate output
     validate(Accessor(_target), _reference);
 }
arm_compute::test::validation::FIXTURE_DATA_TEST_CASE (RunLargeQS8 , CLDepthConvertToFP32FixedPointFixture< int8_t > , framework::DatasetMode::NIGHTLY , combine(combine(combine(datasets::LargeShapes(), DepthConvertQS8toFP32Dataset),framework::dataset::make("ConvertPolicy",{ConvertPolicy::SATURATE, ConvertPolicy::WRAP})),DepthConvertFixedPointQuantizedDataset))
Definition at line 409 of file DepthConvert.cpp.
References arm_compute::SATURATE, and arm_compute::WRAP.
                                                              { ConvertPolicy::SATURATE, ConvertPolicy::WRAP })),
                        DepthConvertFixedPointQuantizedDataset))
 {
     // Validate output
     validate(CLAccessor(_target), _reference);
 }
arm_compute::test::validation::FIXTURE_DATA_TEST_CASE (RunLargeQS8 , NEDepthConvertToFP32FixedPointFixture< int8_t > , framework::DatasetMode::NIGHTLY , combine(combine(combine(datasets::LargeShapes(), DepthConvertQS8toFP32Dataset),framework::dataset::make("ConvertPolicy",{ConvertPolicy::SATURATE, ConvertPolicy::WRAP})),DepthConvertFixedPointQuantizedDataset))
Definition at line 409 of file DepthConvert.cpp.
References arm_compute::SATURATE, and arm_compute::WRAP.
                                                              { ConvertPolicy::SATURATE, ConvertPolicy::WRAP })),
                        DepthConvertFixedPointQuantizedDataset))
 {
     // Validate output
     validate(Accessor(_target), _reference);
 }
arm_compute::test::validation::FIXTURE_DATA_TEST_CASE (RunLargeQS16 , NEDepthConvertToFP32FixedPointFixture< int16_t > , framework::DatasetMode::NIGHTLY , combine(combine(combine(datasets::LargeShapes(), DepthConvertQS16toFP32Dataset),framework::dataset::make("ConvertPolicy",{ConvertPolicy::SATURATE, ConvertPolicy::WRAP})),DepthConvertFixedPointQuantizedDataset))
Definition at line 416 of file DepthConvert.cpp.
References arm_compute::SATURATE, and arm_compute::WRAP.
                                                              { ConvertPolicy::SATURATE, ConvertPolicy::WRAP })),
                        DepthConvertFixedPointQuantizedDataset))
 {
     // Validate output
     validate(Accessor(_target), _reference);
 }
arm_compute::test::validation::FIXTURE_DATA_TEST_CASE (RunLargeQS16 , CLDepthConvertToFP32FixedPointFixture< int16_t > , framework::DatasetMode::NIGHTLY , combine(combine(combine(datasets::LargeShapes(), DepthConvertQS16toFP32Dataset),framework::dataset::make("ConvertPolicy",{ConvertPolicy::SATURATE, ConvertPolicy::WRAP})),DepthConvertFixedPointQuantizedDataset))
Definition at line 416 of file DepthConvert.cpp.
References arm_compute::SATURATE, and arm_compute::WRAP.
                                                              { ConvertPolicy::SATURATE, ConvertPolicy::WRAP })),
                        DepthConvertFixedPointQuantizedDataset))
 {
     // Validate output
     validate(CLAccessor(_target), _reference);
 }
arm_compute::test::validation::FIXTURE_DATA_TEST_CASE (RunSmallQS8 , CLDepthConvertToQS8FixedPointFixture< float > , framework::DatasetMode::PRECOMMIT , combine(combine(combine(datasets::SmallShapes(), DepthConvertFP32toQS8Dataset),framework::dataset::make("ConvertPolicy",{ConvertPolicy::SATURATE, ConvertPolicy::WRAP})),DepthConvertFixedPointQuantizedDataset))
Definition at line 450 of file DepthConvert.cpp.
References arm_compute::SATURATE, and arm_compute::WRAP.
                                                              { ConvertPolicy::SATURATE, ConvertPolicy::WRAP })),
                        DepthConvertFixedPointQuantizedDataset))
 {
     // Validate output
     validate(CLAccessor(_target), _reference);
 }
arm_compute::test::validation::FIXTURE_DATA_TEST_CASE (RunSmallQS8 , NEDepthConvertToQS8FixedPointFixture< float > , framework::DatasetMode::PRECOMMIT , combine(combine(combine(datasets::SmallShapes(), DepthConvertFP32toQS8Dataset),framework::dataset::make("ConvertPolicy",{ConvertPolicy::SATURATE, ConvertPolicy::WRAP})),DepthConvertFixedPointQuantizedDataset))
Definition at line 450 of file DepthConvert.cpp.
References arm_compute::SATURATE, and arm_compute::WRAP.
                                                              { ConvertPolicy::SATURATE, ConvertPolicy::WRAP })),
                        DepthConvertFixedPointQuantizedDataset))
 {
     // Validate output
     validate(Accessor(_target), _reference);
 }
arm_compute::test::validation::FIXTURE_DATA_TEST_CASE (RunSmallQS16 , NEDepthConvertToQS16FixedPointFixture< float > , framework::DatasetMode::PRECOMMIT , combine(combine(combine(datasets::SmallShapes(), DepthConvertFP32toQS16Dataset),framework::dataset::make("ConvertPolicy",{ConvertPolicy::SATURATE, ConvertPolicy::WRAP})),DepthConvertFixedPointQuantizedDataset))
Definition at line 457 of file DepthConvert.cpp.
References arm_compute::SATURATE, and arm_compute::WRAP.
                                                              { ConvertPolicy::SATURATE, ConvertPolicy::WRAP })),
                        DepthConvertFixedPointQuantizedDataset))
 {
     // Validate output
     validate(Accessor(_target), _reference);
 }
arm_compute::test::validation::FIXTURE_DATA_TEST_CASE (RunSmallQS16 , CLDepthConvertToQS16FixedPointFixture< float > , framework::DatasetMode::PRECOMMIT , combine(combine(combine(datasets::SmallShapes(), DepthConvertFP32toQS16Dataset),framework::dataset::make("ConvertPolicy",{ConvertPolicy::SATURATE, ConvertPolicy::WRAP})),DepthConvertFixedPointQuantizedDataset))
Definition at line 457 of file DepthConvert.cpp.
References arm_compute::SATURATE, and arm_compute::WRAP.
                                                              { ConvertPolicy::SATURATE, ConvertPolicy::WRAP })),
                        DepthConvertFixedPointQuantizedDataset))
 {
     // Validate output
     validate(CLAccessor(_target), _reference);
 }
arm_compute::test::validation::FIXTURE_DATA_TEST_CASE (RunLargeQS8 , NEDepthConvertToQS8FixedPointFixture< float > , framework::DatasetMode::NIGHTLY , combine(combine(combine(datasets::LargeShapes(), DepthConvertFP32toQS8Dataset),framework::dataset::make("ConvertPolicy",{ConvertPolicy::SATURATE, ConvertPolicy::WRAP})),DepthConvertFixedPointQuantizedDataset))
Definition at line 464 of file DepthConvert.cpp.
References arm_compute::SATURATE, and arm_compute::WRAP.
                                                              { ConvertPolicy::SATURATE, ConvertPolicy::WRAP })),
                        DepthConvertFixedPointQuantizedDataset))
 {
     // Validate output
     validate(Accessor(_target), _reference);
 }
arm_compute::test::validation::FIXTURE_DATA_TEST_CASE (RunLargeQS8 , CLDepthConvertToQS8FixedPointFixture< float > , framework::DatasetMode::NIGHTLY , combine(combine(combine(datasets::LargeShapes(), DepthConvertFP32toQS8Dataset),framework::dataset::make("ConvertPolicy",{ConvertPolicy::SATURATE, ConvertPolicy::WRAP})),DepthConvertFixedPointQuantizedDataset))
Definition at line 464 of file DepthConvert.cpp.
References arm_compute::SATURATE, and arm_compute::WRAP.
                                                              { ConvertPolicy::SATURATE, ConvertPolicy::WRAP })),
                        DepthConvertFixedPointQuantizedDataset))
 {
     // Validate output
     validate(CLAccessor(_target), _reference);
 }
arm_compute::test::validation::FIXTURE_DATA_TEST_CASE (RunLargeQS16 , NEDepthConvertToQS16FixedPointFixture< float > , framework::DatasetMode::NIGHTLY , combine(combine(combine(datasets::LargeShapes(), DepthConvertFP32toQS16Dataset),framework::dataset::make("ConvertPolicy",{ConvertPolicy::SATURATE, ConvertPolicy::WRAP})),DepthConvertFixedPointQuantizedDataset))
Definition at line 471 of file DepthConvert.cpp.
References arm_compute::SATURATE, and arm_compute::WRAP.
                                                              { ConvertPolicy::SATURATE, ConvertPolicy::WRAP })),
                        DepthConvertFixedPointQuantizedDataset))
 {
     // Validate output
     validate(Accessor(_target), _reference);
 }
arm_compute::test::validation::FIXTURE_DATA_TEST_CASE (RunLargeQS16 , CLDepthConvertToQS16FixedPointFixture< float > , framework::DatasetMode::NIGHTLY , combine(combine(combine(datasets::LargeShapes(), DepthConvertFP32toQS16Dataset),framework::dataset::make("ConvertPolicy",{ConvertPolicy::SATURATE, ConvertPolicy::WRAP})),DepthConvertFixedPointQuantizedDataset))
Definition at line 471 of file DepthConvert.cpp.
References arm_compute::SATURATE, and arm_compute::WRAP.
                                                              { ConvertPolicy::SATURATE, ConvertPolicy::WRAP })),
                        DepthConvertFixedPointQuantizedDataset))
 {
     // Validate output
     validate(CLAccessor(_target), _reference);
 }
std::pair<T, T> arm_compute::test::validation::get_activation_layer_test_bounds (ActivationLayerInfo::ActivationFunction activation, DataType data_type, int fixed_point_position = 0)
Helper function to get the testing range for each activation layer.
Parameters
[in] activation Activation function to test.
[in] data_type Data type.
[in] fixed_point_position Number of bits for the fractional part. Defaults to 1.
Returns
A pair containing the lower upper testing bounds for a given function.
Definition at line 62 of file Helpers.h.
References ARM_COMPUTE_ERROR, arm_compute::F16, arm_compute::F32, ActivationLayerInfo::LOGISTIC, arm_compute::test::fixed_point_arithmetic::detail::max(), arm_compute::QS16, arm_compute::QS8, ActivationLayerInfo::SOFT_RELU, ActivationLayerInfo::SQRT, ActivationLayerInfo::SQUARE, and ActivationLayerInfo::TANH.
 {
     std::pair<T, T> bounds;
     switch(data_type)
     {
         case DataType::F16:
         {
             using namespace half_float::literal;
             switch(activation)
             {
                 case ActivationLayerInfo::ActivationFunction::SQUARE:
                 case ActivationLayerInfo::ActivationFunction::LOGISTIC:
                 case ActivationLayerInfo::ActivationFunction::SOFT_RELU:
                     // Reduce range as exponent overflows
                     bounds = std::make_pair(-10._h, 10._h);
                     break;
                 case ActivationLayerInfo::ActivationFunction::SQRT:
                     // Reduce range as sqrt should take a non-negative number
                     bounds = std::make_pair(0._h, 255._h);
                     break;
                 default:
                     bounds = std::make_pair(-255._h, 255._h);
                     break;
             }
             break;
         }
         case DataType::F32:
             switch(activation)
             {
                 case ActivationLayerInfo::ActivationFunction::LOGISTIC:
                 case ActivationLayerInfo::ActivationFunction::SOFT_RELU:
                     // Reduce range as exponent overflows
                     bounds = std::make_pair(-40.f, 40.f);
                     break;
                 case ActivationLayerInfo::ActivationFunction::SQRT:
                     // Reduce range as sqrt should take a non-negative number
                     bounds = std::make_pair(0.f, 255.f);
                     break;
                 default:
                     bounds = std::make_pair(-255.f, 255.f);
                     break;
             }
             break;
         case DataType::QS8:
         case DataType::QS16:
             switch(activation)
             {
                 case ActivationLayerInfo::ActivationFunction::LOGISTIC:
                 case ActivationLayerInfo::ActivationFunction::SOFT_RELU:
                 case ActivationLayerInfo::ActivationFunction::TANH:
                     // Reduce range as exponent overflows
                     bounds = std::make_pair(-(1 << fixed_point_position), 1 << fixed_point_position);
                     break;
                 case ActivationLayerInfo::ActivationFunction::SQRT:
                     // Reduce range as sqrt should take a non-negative number
                     // Can't be zero either as inv_sqrt is used in NEON.
                     bounds = std::make_pair(1, std::numeric_limits<T>::max());
                     break;
                 default:
                     bounds = std::make_pair(std::numeric_limits<T>::lowest(), std::numeric_limits<T>::max());
                     break;
             }
             break;
         default:
             ARM_COMPUTE_ERROR("Unsupported data type");
     }
     return bounds;
 }
std::pair<T, T> arm_compute::test::validation::get_batchnormalization_layer_test_bounds (int fixed_point_position = 1)
Helper function to get the testing range for batch normalization layer.
Parameters
[in] fixed_point_position (Optional) Number of bits for the fractional part. Defaults to 1.
Returns
A pair containing the lower upper testing bounds.
Definition at line 187 of file Helpers.h.
References value.
 {
     bool is_float = std::is_floating_point<T>::value;
     std::pair<T, T> bounds;
     // Set initial values
     if(is_float)
     {
         bounds = std::make_pair(-1.f, 1.f);
     }
     else
     {
         bounds = std::make_pair(1, 1 << (fixed_point_position));
     }
     return bounds;
 }
HarrisCornersParameters harris_corners_parameters ()
Generate parameters for Harris Corners algorithm.
Definition at line 98 of file Helpers.cpp.
References HarrisCornersParameters::constant_border_value, arm_compute::test::library, HarrisCornersParameters::min_dist, HarrisCornersParameters::sensitivity, and HarrisCornersParameters::threshold.
Referenced by HarrisCornersValidationFixture< TensorType, AccessorType, ArrayType, FunctionType, T >::setup().
 {
     HarrisCornersParameters params;
     std::mt19937                           gen(library->seed());
     std::uniform_real_distribution<float>  threshold_dist(0.f, 0.01f);
     std::uniform_real_distribution<float>  sensitivity(0.04f, 0.15f);
     std::uniform_real_distribution<float>  euclidean_distance(0.f, 30.f);
     std::uniform_int_distribution<uint8_t> int_dist(0, 255);
     params.threshold             = threshold_dist(gen);
     params.sensitivity           = sensitivity(gen);
     params.min_dist              = euclidean_distance(gen);
     params.constant_border_value = int_dist(gen);
     return params;
 }
src info () -> set_format(Format::S16)
Referenced by arm_compute::error_on_mismatching_shapes(), Iterator::Iterator(), Framework::log_test_skipped(), main(), arm_compute::test::validation::reference::pooling_layer(), DirectConvolutionValidationFixedPointFixture< TensorType, AccessorType, FunctionType, T >::setup(), ActivationValidationFixedPointFixture< TensorType, AccessorType, FunctionType, T >::setup(), PoolingLayerValidationFixedPointFixture< TensorType, AccessorType, FunctionType, T >::setup(), and NormalizationValidationFixedPointFixture< TensorType, AccessorType, FunctionType, T >::setup().
inline ::std::ostream& arm_compute::test::validation::operator<< (::std::ostream & os, const AbsoluteTolerance< T > & tolerance)
Print AbsoluteTolerance type.
Definition at line 116 of file Validation.h.
 {
     os << static_cast<typename AbsoluteTolerance<T>::value_type>(tolerance);
     return os;
 }
inline ::std::ostream& arm_compute::test::validation::operator<< (::std::ostream & os, const RelativeTolerance< T > & tolerance)
Print RelativeTolerance type.
Definition at line 125 of file Validation.h.
 {
     os << static_cast<typename RelativeTolerance<T>::value_type>(tolerance);
     return os;
 }
shape arm_compute::test::validation::set (dimension , 10)
T arm_compute::test::validation::tensor_elem_at (const SimpleTensor< T > & src, Coordinates coord, BorderMode border_mode, T constant_border_value)
Definition at line 46 of file Utils.h.
References arm_compute::test::coord2index(), arm_compute::test::fixed_point_arithmetic::detail::max(), arm_compute::test::fixed_point_arithmetic::detail::min(), arm_compute::REPLICATE, Dimensions< T >::set(), SimpleTensor< T >::shape(), Dimensions< T >::x(), and Dimensions< T >::y().
Referenced by apply_2d_spatial_filter(), bilinear_policy(), arm_compute::test::validation::reference::depthwise_convolution(), arm_compute::test::validation::reference::non_linear_filter(), arm_compute::test::validation::reference::non_maxima_suppression(), arm_compute::test::validation::reference::scale(), arm_compute::test::validation::reference::warp_affine(), and arm_compute::test::validation::reference::warp_perspective().
 {
     const int x      = coord.x();
     const int y      = coord.y();
     const int width  = src.shape().x();
     const int height = src.shape().y();
     // If coordinates beyond range of tensor's width or height
     if(x < 0 || y < 0 || x >= width || y >= height)
     {
         if(border_mode == BorderMode::REPLICATE)
         {
             coord.set(0, std::max(0, std::min(x, width - 1)));
             coord.set(1, std::max(0, std::min(y, height - 1)));
         }
         else
         {
             return constant_border_value;
         }
     }
     return src[coord2index(src.shape(), coord)];
 }
TEST_CASE (LeNet5 , framework::DatasetMode::PRECOMMIT)
Definition at line 81 of file LeNet5.cpp.
References validate().
 {
     // Compute alexnet
     std::vector<unsigned int> classified_labels = compute_lenet5(10, "cnn_data/mnist_data/input10.npy");
     // Expected labels
     std::vector<unsigned int> expected_labels = { 7, 2, 1, 0, 4, 1, 4, 9, 5, 9 };
     // Validate labels
     validate(classified_labels, expected_labels);
 }
TEST_CASE (AlexNet , framework::DatasetMode::PRECOMMIT)
Definition at line 96 of file AlexNet.cpp.
References arm_compute::F32, and validate().
 {
     // Compute alexnet
     std::vector<unsigned int> classified_labels = compute_alexnet(DataType::F32, 1, "cnn_data/imagenet_data/cat.npy");
     // Expected labels
     std::vector<unsigned int> expected_labels = { 281 };
     // Validate labels
     validate(classified_labels, expected_labels);
 }
TEST_SUITE_END ()
Referenced by DATA_TEST_CASE().
RawTensor transpose (const RawTensor & src, int chunk_width)
Definition at line 69 of file Utils.cpp.
References SimpleTensor< T >::data_type(), SimpleTensor< T >::element_size(), arm_compute::test::index2coord(), TensorShape::set(), Dimensions< T >::set(), SimpleTensor< T >::shape(), Dimensions< T >::x(), and Dimensions< T >::y().
 {
     // Create reference
     TensorShape dst_shape(src.shape());
     dst_shape.set(0, src.shape().y() * chunk_width);
     dst_shape.set(1, std::ceil(src.shape().x() / static_cast<float>(chunk_width)));
     RawTensor dst{ dst_shape, src.data_type() };
     // Compute reference
     uint8_t *out_ptr = dst.data();
     for(int i = 0; i < dst.num_elements(); i += chunk_width)
     {
         Coordinates coord   = index2coord(dst.shape(), i);
         size_t      coord_x = coord.x();
         coord.set(0, coord.y() * chunk_width);
         coord.set(1, coord_x / chunk_width);
         const int num_elements = std::min<int>(chunk_width, src.shape().x() - coord.x());
         std::copy_n(static_cast<const uint8_t *>(src(coord)), num_elements * src.element_size(), out_ptr);
         out_ptr += chunk_width * dst.element_size();
     }
     return dst;
 }
bool valid_bilinear_policy (float xn, float yn, int width, int height, BorderMode border_mode)
Definition at line 98 of file Utils.cpp.
References arm_compute::UNDEFINED.
 {
     if(border_mode != BorderMode::UNDEFINED)
     {
         return true;
     }
     if((0 <= yn + 1) && (yn + 1 < height) && (0 <= xn + 1) && (xn + 1 < width))
     {
         return true;
     }
     return false;
 }
void validate (const arm_compute::ValidRegion & region, const arm_compute::ValidRegion & reference)
Validate valid regions.
Dimensionality has to be the same.
Anchors have to match.
Shapes have to match.
Definition at line 149 of file Validation.cpp.
References ValidRegion::anchor, ARM_COMPUTE_EXPECT_EQUAL, arm_compute::test::framework::ERRORS, Dimensions< T >::num_dimensions(), and ValidRegion::shape.
Referenced by compare_keypoints(), DATA_TEST_CASE(), FIXTURE_DATA_TEST_CASE(), TEST_CASE(), validate(), and validate_configuration().
 {
     ARM_COMPUTE_EXPECT_EQUAL(region.anchor.num_dimensions(), reference.anchor.num_dimensions(), framework::LogLevel::ERRORS);
     ARM_COMPUTE_EXPECT_EQUAL(region.shape.num_dimensions(), reference.shape.num_dimensions(), framework::LogLevel::ERRORS);
     for(unsigned int d = 0; d < region.anchor.num_dimensions(); ++d)
     {
         ARM_COMPUTE_EXPECT_EQUAL(region.anchor[d], reference.anchor[d], framework::LogLevel::ERRORS);
     }
     for(unsigned int d = 0; d < region.shape.num_dimensions(); ++d)
     {
         ARM_COMPUTE_EXPECT_EQUAL(region.shape[d], reference.shape[d], framework::LogLevel::ERRORS);
     }
 }
void validate (const arm_compute::PaddingSize & padding, const arm_compute::PaddingSize & reference)
Validate padding.
Padding on all sides has to be the same.
Definition at line 165 of file Validation.cpp.
References ARM_COMPUTE_EXPECT_EQUAL, BorderSize::bottom, arm_compute::test::framework::ERRORS, BorderSize::left, BorderSize::right, and BorderSize::top.
 {
     ARM_COMPUTE_EXPECT_EQUAL(padding.top, reference.top, framework::LogLevel::ERRORS);
     ARM_COMPUTE_EXPECT_EQUAL(padding.right, reference.right, framework::LogLevel::ERRORS);
     ARM_COMPUTE_EXPECT_EQUAL(padding.bottom, reference.bottom, framework::LogLevel::ERRORS);
     ARM_COMPUTE_EXPECT_EQUAL(padding.left, reference.left, framework::LogLevel::ERRORS);
 }
void validate (const IAccessor & tensor, const void * reference_value)
Validate tensors against constant value.
All values have to match.
Definition at line 173 of file Validation.cpp.
References ARM_COMPUTE_ASSERT, ARM_COMPUTE_EXPECT_EQUAL, ARM_COMPUTE_TEST_INFO, IAccessor::data_type(), arm_compute::test::framework::DEBUG, arm_compute::element_size_from_data_type(), arm_compute::test::framework::ERRORS, arm_compute::test::index2coord(), IAccessor::num_channels(), IAccessor::num_elements(), and IAccessor::shape().
 {
     ARM_COMPUTE_ASSERT(reference_value != nullptr);
     int64_t      num_mismatches = 0;
     int64_t      num_elements   = 0;
     const size_t channel_size   = element_size_from_data_type(tensor.data_type());
     // Iterate over all elements, e.g. U8, S16, RGB888, ...
     for(int element_idx = 0; element_idx < tensor.num_elements(); ++element_idx)
     {
         const Coordinates id = index2coord(tensor.shape(), element_idx);
         const auto ptr = static_cast<const uint8_t *>(tensor(id));
         // Iterate over all channels within one element
         for(int channel = 0; channel < tensor.num_channels(); ++channel)
         {
             const size_t channel_offset = channel * channel_size;
             const double target         = get_double_data(ptr + channel_offset, tensor.data_type());
             const double reference      = get_double_data(reference_value, tensor.data_type());
             if(!compare<AbsoluteTolerance<double>>(target, reference))
             {
                 ARM_COMPUTE_TEST_INFO("id = " << id);
                 ARM_COMPUTE_TEST_INFO("channel = " << channel);
                 ARM_COMPUTE_TEST_INFO("target = " << std::setprecision(5) << target);
                 ARM_COMPUTE_TEST_INFO("reference = " << std::setprecision(5) << reference);
                 ARM_COMPUTE_EXPECT_EQUAL(target, reference, framework::LogLevel::DEBUG);
                 ++num_mismatches;
             }
             ++num_elements;
         }
     }
     if(num_elements > 0)
     {
         const float percent_mismatches = static_cast<float>(num_mismatches) / num_elements * 100.f;
         ARM_COMPUTE_TEST_INFO(num_mismatches << " values (" << std::fixed << std::setprecision(2) << percent_mismatches << "%) mismatched");
         ARM_COMPUTE_EXPECT_EQUAL(num_mismatches, 0, framework::LogLevel::ERRORS);
     }
 }
void validate (const IAccessor & tensor, const SimpleTensor< T > & reference, U tolerance_value = U(), float tolerance_number = 0.f)
Validate tensors.
Dimensionality has to be the same.
All values have to match.
Note
: wrap_range allows cases where reference tensor rounds up to the wrapping point, causing it to wrap around to zero while the test tensor stays at wrapping point to pass. This may permit true erroneous cases (difference between reference tensor and test tensor is multiple of wrap_range), but such errors would be detected by other test cases.
Definition at line 312 of file Validation.h.
References IAccessor::shape(), arm_compute::test::shape_to_valid_region(), and validate().
 {
     // Validate with valid region covering the entire shape
     validate(tensor, reference, shape_to_valid_region(tensor.shape()), tolerance_value, tolerance_number);
 }
void validate (const IAccessor & tensor, const SimpleTensor< T > & reference, const ValidRegion & valid_region, U tolerance_value = U(), float tolerance_number = 0.f)
Validate tensors with valid region.
Dimensionality has to be the same.
All values have to match.
Note
: wrap_range allows cases where reference tensor rounds up to the wrapping point, causing it to wrap around to zero while the test tensor stays at wrapping point to pass. This may permit true erroneous cases (difference between reference tensor and test tensor is multiple of wrap_range), but such errors would be detected by other test cases.
Definition at line 319 of file Validation.h.
References ARM_COMPUTE_EXPECT(), ARM_COMPUTE_EXPECT_EQUAL, arm_compute::test::framework::ARM_COMPUTE_PRINT_INFO(), ARM_COMPUTE_TEST_INFO, compare_dimensions(), IAccessor::data_type(), SimpleTensor< T >::data_type(), IAccessor::element_size(), SimpleTensor< T >::element_size(), arm_compute::test::framework::ERRORS, IAccessor::format(), SimpleTensor< T >::format(), arm_compute::test::index2coord(), arm_compute::test::is_in_valid_region(), arm_compute::test::framework::make_printable(), arm_compute::test::fixed_point_arithmetic::detail::min(), IAccessor::num_channels(), SimpleTensor< T >::num_channels(), IAccessor::num_elements(), SimpleTensor< T >::num_elements(), IAccessor::shape(), SimpleTensor< T >::shape(), and arm_compute::UNKNOWN.
 {
     int64_t num_mismatches = 0;
     int64_t num_elements   = 0;
     ARM_COMPUTE_EXPECT_EQUAL(tensor.element_size(), reference.element_size(), framework::LogLevel::ERRORS);
     ARM_COMPUTE_EXPECT_EQUAL(tensor.data_type(), reference.data_type(), framework::LogLevel::ERRORS);
     if(reference.format() != Format::UNKNOWN)
     {
         ARM_COMPUTE_EXPECT_EQUAL(tensor.format(), reference.format(), framework::LogLevel::ERRORS);
     }
     ARM_COMPUTE_EXPECT_EQUAL(tensor.num_channels(), reference.num_channels(), framework::LogLevel::ERRORS);
     ARM_COMPUTE_EXPECT(compare_dimensions(tensor.shape(), reference.shape()), framework::LogLevel::ERRORS);
     const int min_elements = std::min(tensor.num_elements(), reference.num_elements());
     const int min_channels = std::min(tensor.num_channels(), reference.num_channels());
     // Iterate over all elements within valid region, e.g. U8, S16, RGB888, ...
     for(int element_idx = 0; element_idx < min_elements; ++element_idx)
     {
         const Coordinates id = index2coord(reference.shape(), element_idx);
         if(is_in_valid_region(valid_region, id))
         {
             // Iterate over all channels within one element
             for(int c = 0; c < min_channels; ++c)
             {
                 const T &target_value    = reinterpret_cast<const T *>(tensor(id))[c];
                 const T &reference_value = reinterpret_cast<const T *>(reference(id))[c];
                 if(!compare<U>(target_value, reference_value, tolerance_value))
                 {
                     ARM_COMPUTE_TEST_INFO("id = " << id);
                     ARM_COMPUTE_TEST_INFO("channel = " << c);
                     ARM_COMPUTE_TEST_INFO("target = " << std::setprecision(5) << framework::make_printable(target_value));
                     ARM_COMPUTE_TEST_INFO("reference = " << std::setprecision(5) << framework::make_printable(reference_value));
                     ARM_COMPUTE_TEST_INFO("tolerance = " << std::setprecision(5) << framework::make_printable(static_cast<typename U::value_type>(tolerance_value)));
                     framework::ARM_COMPUTE_PRINT_INFO();
                     ++num_mismatches;
                 }
                 ++num_elements;
             }
         }
     }
     if(num_elements > 0)
     {
         const int64_t absolute_tolerance_number = tolerance_number * num_elements;
         const float   percent_mismatches        = static_cast<float>(num_mismatches) / num_elements * 100.f;
         ARM_COMPUTE_TEST_INFO(num_mismatches << " values (" << std::fixed << std::setprecision(2) << percent_mismatches
                               << "%) mismatched (maximum tolerated " << std::setprecision(2) << tolerance_number << "%)");
         ARM_COMPUTE_EXPECT(num_mismatches <= absolute_tolerance_number, framework::LogLevel::ERRORS);
     }
 }
void validate (const IAccessor & tensor, const SimpleTensor< T > & reference, const SimpleTensor< T > & valid_mask, U tolerance_value = U(), float tolerance_number = 0.f)
Validate tensors with valid mask.
Dimensionality has to be the same.
All values have to match.
Note
: wrap_range allows cases where reference tensor rounds up to the wrapping point, causing it to wrap around to zero while the test tensor stays at wrapping point to pass. This may permit true erroneous cases (difference between reference tensor and test tensor is multiple of wrap_range), but such errors would be detected by other test cases.
Definition at line 451 of file Validation.h.
References ARM_COMPUTE_EXPECT(), ARM_COMPUTE_EXPECT_EQUAL, arm_compute::test::framework::ARM_COMPUTE_PRINT_INFO(), ARM_COMPUTE_TEST_INFO, compare_dimensions(), IAccessor::data_type(), SimpleTensor< T >::data_type(), IAccessor::element_size(), SimpleTensor< T >::element_size(), arm_compute::test::framework::ERRORS, IAccessor::format(), SimpleTensor< T >::format(), arm_compute::test::index2coord(), arm_compute::test::framework::make_printable(), arm_compute::test::fixed_point_arithmetic::detail::min(), IAccessor::num_channels(), SimpleTensor< T >::num_channels(), IAccessor::num_elements(), SimpleTensor< T >::num_elements(), IAccessor::shape(), SimpleTensor< T >::shape(), and arm_compute::UNKNOWN.
 {
     int64_t num_mismatches = 0;
     int64_t num_elements   = 0;
     ARM_COMPUTE_EXPECT_EQUAL(tensor.element_size(), reference.element_size(), framework::LogLevel::ERRORS);
     ARM_COMPUTE_EXPECT_EQUAL(tensor.data_type(), reference.data_type(), framework::LogLevel::ERRORS);
     if(reference.format() != Format::UNKNOWN)
     {
         ARM_COMPUTE_EXPECT_EQUAL(tensor.format(), reference.format(), framework::LogLevel::ERRORS);
     }
     ARM_COMPUTE_EXPECT_EQUAL(tensor.num_channels(), reference.num_channels(), framework::LogLevel::ERRORS);
     ARM_COMPUTE_EXPECT(compare_dimensions(tensor.shape(), reference.shape()), framework::LogLevel::ERRORS);
     const int min_elements = std::min(tensor.num_elements(), reference.num_elements());
     const int min_channels = std::min(tensor.num_channels(), reference.num_channels());
     // Iterate over all elements within valid region, e.g. U8, S16, RGB888, ...
     for(int element_idx = 0; element_idx < min_elements; ++element_idx)
     {
         const Coordinates id = index2coord(reference.shape(), element_idx);
         if(valid_mask[element_idx] == 1)
         {
             // Iterate over all channels within one element
             for(int c = 0; c < min_channels; ++c)
             {
                 const T &target_value    = reinterpret_cast<const T *>(tensor(id))[c];
                 const T &reference_value = reinterpret_cast<const T *>(reference(id))[c];
                 if(!compare<U>(target_value, reference_value, tolerance_value))
                 {
                     ARM_COMPUTE_TEST_INFO("id = " << id);
                     ARM_COMPUTE_TEST_INFO("channel = " << c);
                     ARM_COMPUTE_TEST_INFO("target = " << std::setprecision(5) << framework::make_printable(target_value));
                     ARM_COMPUTE_TEST_INFO("reference = " << std::setprecision(5) << framework::make_printable(reference_value));
                     ARM_COMPUTE_TEST_INFO("tolerance = " << std::setprecision(5) << framework::make_printable(static_cast<typename U::value_type>(tolerance_value)));
                     framework::ARM_COMPUTE_PRINT_INFO();
                     ++num_mismatches;
                 }
                 ++num_elements;
             }
         }
         else
         {
             ++num_elements;
         }
     }
     if(num_elements > 0)
     {
         const int64_t absolute_tolerance_number = tolerance_number * num_elements;
         const float   percent_mismatches        = static_cast<float>(num_mismatches) / num_elements * 100.f;
         ARM_COMPUTE_TEST_INFO(num_mismatches << " values (" << std::fixed << std::setprecision(2) << percent_mismatches
                               << "%) mismatched (maximum tolerated " << std::setprecision(2) << tolerance_number << "%)");
         ARM_COMPUTE_EXPECT(num_mismatches <= absolute_tolerance_number, framework::LogLevel::ERRORS);
     }
 }
void validate (const IAccessor & tensor, BorderSize border_size, const BorderMode & border_mode, const void * border_value)
Validate border against a constant value.
All border values have to match the specified value if mode is CONSTANT.
All border values have to be replicated if mode is REPLICATE.
Nothing is validated for mode UNDEFINED.
Definition at line 219 of file Validation.cpp.
References ARM_COMPUTE_ASSERT, ARM_COMPUTE_EXPECT_EQUAL, ARM_COMPUTE_TEST_INFO, BorderSize::bottom, arm_compute::CONSTANT, arm_compute::test::framework::ERRORS, arm_compute::test::index2coord(), BorderSize::left, IAccessor::num_elements(), BorderSize::right, Dimensions< T >::set(), IAccessor::shape(), BorderSize::top, and arm_compute::UNDEFINED.
 {
     if(border_mode == BorderMode::UNDEFINED)
     {
         return;
     }
     else if(border_mode == BorderMode::CONSTANT)
     {
         ARM_COMPUTE_ASSERT(border_value != nullptr);
     }
     int64_t   num_mismatches = 0;
     int64_t   num_elements   = 0;
     const int slice_size     = tensor.shape()[0] * tensor.shape()[1];
     for(int element_idx = 0; element_idx < tensor.num_elements(); element_idx += slice_size)
     {
         Coordinates id = index2coord(tensor.shape(), element_idx);
         // Top border
         for(int y = -border_size.top; y < 0; ++y)
         {
             id.set(1, y);
             for(int x = -border_size.left; x < static_cast<int>(tensor.shape()[0]) + static_cast<int>(border_size.right); ++x)
             {
                 id.set(0, x);
                 check_border_element(tensor, id, border_mode, border_value, num_elements, num_mismatches);
             }
         }
         // Bottom border
         for(int y = tensor.shape()[1]; y < static_cast<int>(tensor.shape()[1]) + static_cast<int>(border_size.bottom); ++y)
         {
             id.set(1, y);
             for(int x = -border_size.left; x < static_cast<int>(tensor.shape()[0]) + static_cast<int>(border_size.right); ++x)
             {
                 id.set(0, x);
                 check_border_element(tensor, id, border_mode, border_value, num_elements, num_mismatches);
             }
         }
         // Left/right border
         for(int y = 0; y < static_cast<int>(tensor.shape()[1]); ++y)
         {
             id.set(1, y);
             // Left border
             for(int x = -border_size.left; x < 0; ++x)
             {
                 id.set(0, x);
                 check_border_element(tensor, id, border_mode, border_value, num_elements, num_mismatches);
             }
             // Right border
             for(int x = tensor.shape()[0]; x < static_cast<int>(tensor.shape()[0]) + static_cast<int>(border_size.right); ++x)
             {
                 id.set(0, x);
                 check_border_element(tensor, id, border_mode, border_value, num_elements, num_mismatches);
             }
         }
     }
     if(num_elements > 0)
     {
         const float percent_mismatches = static_cast<float>(num_mismatches) / num_elements * 100.f;
         ARM_COMPUTE_TEST_INFO(num_mismatches << " values (" << std::fixed << std::setprecision(2) << percent_mismatches << "%) mismatched");
         ARM_COMPUTE_EXPECT_EQUAL(num_mismatches, 0, framework::LogLevel::ERRORS);
     }
 }
bool validate (T target, T reference, U tolerance = AbsoluteTolerance<T>())
Validate float value.
All values should match
Definition at line 516 of file Validation.h.
References ARM_COMPUTE_EXPECT(), ARM_COMPUTE_TEST_INFO, arm_compute::test::framework::ERRORS, and arm_compute::test::framework::make_printable().
 {
     ARM_COMPUTE_TEST_INFO("reference = " << std::setprecision(5) << framework::make_printable(reference));
     ARM_COMPUTE_TEST_INFO("target = " << std::setprecision(5) << framework::make_printable(target));
     ARM_COMPUTE_TEST_INFO("tolerance = " << std::setprecision(5) << framework::make_printable(static_cast<typename U::value_type>(tolerance)));
     const bool equal = compare<U>(target, reference, tolerance);
     ARM_COMPUTE_EXPECT(equal, framework::LogLevel::ERRORS);
     return equal;
 }
void validate (std::vector< unsigned int > classified_labels, std::vector< unsigned int > expected_labels)
Validate classified labels against expected ones.
All values should match
Definition at line 296 of file Validation.cpp.
References ARM_COMPUTE_EXPECT_EQUAL, ARM_COMPUTE_TEST_INFO, arm_compute::test::framework::DEBUG, arm_compute::test::framework::ERRORS, and arm_compute::test::fixed_point_arithmetic::detail::min().
 {
     ARM_COMPUTE_EXPECT_EQUAL(classified_labels.size(), expected_labels.size(), framework::LogLevel::ERRORS);
     int64_t   num_mismatches = 0;
     const int num_elements   = std::min(classified_labels.size(), expected_labels.size());
     for(int i = 0; i < num_elements; ++i)
     {
         if(classified_labels[i] != expected_labels[i])
         {
             ++num_mismatches;
             ARM_COMPUTE_EXPECT_EQUAL(classified_labels[i], expected_labels[i], framework::LogLevel::DEBUG);
         }
     }
     if(num_elements > 0)
     {
         const float percent_mismatches = static_cast<float>(num_mismatches) / num_elements * 100.f;
         ARM_COMPUTE_TEST_INFO(num_mismatches << " values (" << std::fixed << std::setprecision(2) << percent_mismatches << "%) mismatched");
         ARM_COMPUTE_EXPECT_EQUAL(num_mismatches, 0, framework::LogLevel::ERRORS);
     }
 }
void arm_compute::test::validation::validate_configuration (const CLTensor & src, TensorShape shape)
Definition at line 45 of file MinMaxLocation.cpp.
References ARM_COMPUTE_EXPECT(), arm_compute::test::framework::ERRORS, arm_compute::test::fixed_point_arithmetic::detail::max(), arm_compute::test::fixed_point_arithmetic::detail::min(), padding, and validate().
 {
     ARM_COMPUTE_EXPECT(src.info()->is_resizable(), framework::LogLevel::ERRORS);
     // Create output storage
     int32_t              min = 0;
     int32_t              max = 0;
     CLCoordinates2DArray min_loc(shape.total_size());
     CLCoordinates2DArray max_loc(shape.total_size());
     // Create and configure function
     CLMinMaxLocation min_max_loc;
     min_max_loc.configure(&src, &min, &max, &min_loc, &max_loc);
     // Validate padding
     const PaddingSize padding = PaddingCalculator(shape.x(), 16).required_padding();
     validate(src.info()->padding(), padding);
 }
void arm_compute::test::validation::validate_configuration (const Tensor & src, TensorShape shape)
Definition at line 46 of file MinMaxLocation.cpp.
References ARM_COMPUTE_EXPECT(), arm_compute::test::framework::ERRORS, arm_compute::test::fixed_point_arithmetic::detail::max(), arm_compute::test::fixed_point_arithmetic::detail::min(), padding, and validate().
 {
     ARM_COMPUTE_EXPECT(src.info()->is_resizable(), framework::LogLevel::ERRORS);
     // Create output storage
     int32_t            min{};
     int32_t            max{};
     Coordinates2DArray min_loc(shape.total_size());
     Coordinates2DArray max_loc(shape.total_size());
     // Create and configure function
     NEMinMaxLocation min_max_loc;
     min_max_loc.configure(&src, &min, &max, &min_loc, &max_loc);
     // Validate padding
     const PaddingSize padding = PaddingCalculator(shape.x(), 1).required_padding();
     validate(src.info()->padding(), padding);
 }
validate_configuration (src , shape)
void validate_keypoints (T target_first, T target_last, U reference_first, U reference_last, V tolerance = AbsoluteTolerance<float>())
Validate key points.
Definition at line 415 of file Validation.h.
References ARM_COMPUTE_EXPECT_EQUAL, ARM_COMPUTE_TEST_INFO, compare_keypoints(), and arm_compute::test::framework::ERRORS.
Referenced by FIXTURE_DATA_TEST_CASE().
 {
     const int64_t num_elements_target    = std::distance(target_first, target_last);
     const int64_t num_elements_reference = std::distance(reference_first, reference_last);
     ARM_COMPUTE_EXPECT_EQUAL(num_elements_target, num_elements_reference, framework::LogLevel::ERRORS);
     int64_t num_missing    = 0;
     int64_t num_mismatches = 0;
     if(num_elements_reference > 0)
     {
         std::tie(num_missing, num_mismatches) = compare_keypoints(reference_first, reference_last, target_first, target_last, tolerance);
         const float percent_missing    = static_cast<float>(num_missing) / num_elements_reference * 100.f;
         const float percent_mismatches = static_cast<float>(num_mismatches) / num_elements_reference * 100.f;
         ARM_COMPUTE_TEST_INFO(num_missing << " keypoints (" << std::fixed << std::setprecision(2) << percent_missing << "%) are missing in target");
         ARM_COMPUTE_EXPECT_EQUAL(num_missing, 0, framework::LogLevel::ERRORS);
         ARM_COMPUTE_TEST_INFO(num_mismatches << " keypoints (" << std::fixed << std::setprecision(2) << percent_mismatches << "%) mismatched");
         ARM_COMPUTE_EXPECT_EQUAL(num_mismatches, 0, framework::LogLevel::ERRORS);
     }
     if(num_elements_target > 0)
     {
         std::tie(num_missing, num_mismatches) = compare_keypoints(target_first, target_last, reference_first, reference_last, tolerance);
         const float percent_missing = static_cast<float>(num_missing) / num_elements_target * 100.f;
         ARM_COMPUTE_TEST_INFO(num_missing << " keypoints (" << std::fixed << std::setprecision(2) << percent_missing << "%) are not part of target");
         ARM_COMPUTE_EXPECT_EQUAL(num_missing, 0, framework::LogLevel::ERRORS);
     }
 }
void arm_compute::test::validation::validate_min_max_loc (const MinMaxLocationValues< T > & target, const MinMaxLocationValues< U > & reference)
Definition at line 530 of file Validation.h.
References ARM_COMPUTE_EXPECT(), ARM_COMPUTE_EXPECT_EQUAL, arm_compute::test::framework::ERRORS, MinMaxLocationValues< MinMaxType >::max, MinMaxLocationValues< MinMaxType >::max_loc, MinMaxLocationValues< MinMaxType >::min, and MinMaxLocationValues< MinMaxType >::min_loc.
Referenced by FIXTURE_DATA_TEST_CASE().
 {
     ARM_COMPUTE_EXPECT_EQUAL(target.min, reference.min, framework::LogLevel::ERRORS);
     ARM_COMPUTE_EXPECT_EQUAL(target.max, reference.max, framework::LogLevel::ERRORS);
     ARM_COMPUTE_EXPECT_EQUAL(target.min_loc.size(), reference.min_loc.size(), framework::LogLevel::ERRORS);
     ARM_COMPUTE_EXPECT_EQUAL(target.max_loc.size(), reference.max_loc.size(), framework::LogLevel::ERRORS);
     for(uint32_t i = 0; i < target.min_loc.size(); ++i)
     {
         const auto same_coords = std::find_if(reference.min_loc.begin(), reference.min_loc.end(), [&target, i](Coordinates2D coord)
         {
             return coord.x == target.min_loc.at(i).x && coord.y == target.min_loc.at(i).y;
         });
         ARM_COMPUTE_EXPECT(same_coords != reference.min_loc.end(), framework::LogLevel::ERRORS);
     }
     for(uint32_t i = 0; i < target.max_loc.size(); ++i)
     {
         const auto same_coords = std::find_if(reference.max_loc.begin(), reference.max_loc.end(), [&target, i](Coordinates2D coord)
         {
             return coord.x == target.max_loc.at(i).x && coord.y == target.max_loc.at(i).y;
         });
         ARM_COMPUTE_EXPECT(same_coords != reference.max_loc.end(), framework::LogLevel::ERRORS);
     }
 }
Variable Documentation
const auto BorderSizesDataset = framework::dataset::make("BorderSize", 0, 6)
Definition at line 50 of file FillBorder.cpp.
data_type
Initial value:
{
    CLTensor src = create_tensor<CLTensor>(shape, data_type)
Definition at line 90 of file MinMaxLocation.cpp.
Referenced by DATA_TEST_CASE(), SimpleTensor< T >::element_size(), AssetsLibrary::get(), AlexNetNetwork< ITensorType, TensorType, SubTensorType, arm_compute::test::Accessor, ActivationLayerFunction, ConvolutionLayerFunction, DirectConvolutionLayerFunction, FullyConnectedLayerFunction, NormalizationLayerFunction, PoolingLayerFunction, SoftmaxLayerFunction >::init(), PoolingLayerFixture< TensorType, Function, Accessor >::setup(), DepthwiseConvolutionFixture< TensorType, Function, Accessor >::setup(), DepthwiseSeparableConvolutionLayerFixture< TensorType, Function, Accessor >::setup(), BatchNormalizationLayerFixture< TensorType, Function, Accessor >::setup(), FloorFixture< TensorType, Function, Accessor >::setup(), FullyConnectedLayerFixture< TensorType, Function, Accessor >::setup(), ActivationLayerFixture< TensorType, Function, Accessor >::setup(), ConvolutionLayerFixture< TensorType, Function, Accessor >::setup(), GEMMFixture< TensorType, Function, Accessor >::setup(), NormalizationLayerFixture< TensorType, Function, Accessor >::setup(), ROIPoolingLayerFixture< TensorType, Function, Accessor, Array_T, ArrayAccessor >::setup(), ScaleValidationFixture< TensorType, AccessorType, FunctionType, T >::setup(), DirectConvolutionValidationFixedPointFixture< TensorType, AccessorType, FunctionType, T >::setup(), ActivationValidationFixedPointFixture< TensorType, AccessorType, FunctionType, T >::setup(), WarpPerspectiveValidationFixture< TensorType, AccessorType, FunctionType, T >::setup(), GEMMValidationFixedPointFixture< TensorType, AccessorType, FunctionType, T >::setup(), FullyConnectedLayerValidationFixedPointFixture< TensorType, AccessorType, FunctionType, T, run_interleave >::setup(), ConvolutionValidationFixedPointFixture< TensorType, AccessorType, FunctionType, T >::setup(), GlobalPoolingLayerValidationFixture< TensorType, AccessorType, FunctionType, T >::setup(), and arm_compute::to_string().
const auto PaddingSizesDataset
Initial value:
= concat(concat(
                                 framework::dataset::make("PaddingSize", PaddingSize{ 0 }),
                                 framework::dataset::make("PaddingSize", PaddingSize{ 1, 0, 1, 2 })),
                                 framework::dataset::make("PaddingSize", PaddingSize{ 10 }))
Definition at line 45 of file FillBorder.cpp.
shape
Definition at line 89 of file MinMaxLocation.cpp.
Referenced by NumPyBinLoader::access_tensor(), calculate_depth_concatenate_shape(), arm_compute::calculate_depth_concatenate_shape(), arm_compute::compute_strides(), DATA_TEST_CASE(), AssetsLibrary::fill_borders_with_garbage(), AssetsLibrary::fill_layer_data(), main_neon_copy_objects(), FloorFixture< TensorType, Function, Accessor >::setup(), NormalizationLayerFixture< TensorType, Function, Accessor >::setup(), ActivationLayerFixture< TensorType, Function, Accessor >::setup(), ROIPoolingLayerFixture< TensorType, Function, Accessor, Array_T, ArrayAccessor >::setup(), ScaleValidationFixture< TensorType, AccessorType, FunctionType, T >::setup(), and arm_compute::to_string().