Compute Library: examples/neon_convolution.cpp File Reference
neon_convolution.cpp File Reference
#include "arm_compute/runtime/NEON/NEFunctions.h"
#include "arm_compute/core/Types.h"
#include "utils/Utils.h"
Functions
void main_neon_convolution (int argc, const char **argv)
int main (int argc, const char **argv)
Main program for convolution test.
Variables
const int16_t gaussian3x3 []
Gaussian 3x3 matrix.
const int16_t gaussian5x5 []
Gaussian 5x5 matrix.
Function Documentation
int main (int argc, const char ** argv)
Main program for convolution test.
Parameters
[in] argc Number of arguments
[in] argv Arguments ([optional] Path to PPM image to process)
Definition at line 114 of file neon_convolution.cpp.
References main_neon_convolution(), and arm_compute::utils::run_example().
 {
     return utils::run_example(argc, argv, main_neon_convolution);
 }
void main_neon_convolution (int argc, const char ** argv)
[Accurate padding]
[Accurate padding]
Definition at line 52 of file neon_convolution.cpp.
References NEConvolution3x3::configure(), NEConvolutionSquare< matrix_size >::configure(), PPMLoader::fill_image(), gaussian3x3, gaussian5x5, PPMLoader::init_image(), PPMLoader::is_open(), PPMLoader::open(), INESimpleFunction::run(), NEConvolutionSquare< matrix_size >::run(), arm_compute::utils::save_to_ppm(), arm_compute::U8, and arm_compute::UNDEFINED.
Referenced by main().
 {
     PPMLoader ppm;
     Image     src, tmp, dst;
     if(argc < 2)
     {
         // Print help
         std::cout << "Usage: ./build/neon_convolution [input_image.ppm]\n\n";
         std::cout << "No input_image provided, creating a dummy 640x480 image\n";
         // Initialize just the dimensions and format of your buffers:
         src.allocator()->init(TensorInfo(640, 480, Format::U8));
     }
     else
     {
         ppm.open(argv[1]);
         // Initialize just the dimensions and format of your buffers:
         ppm.init_image(src, Format::U8);
     }
     // Initialize just the dimensions and format of the temporary and destination images:
     tmp.allocator()->init(*src.info());
     dst.allocator()->init(*src.info());
     NEConvolution3x3 conv3x3;
     NEConvolution5x5 conv5x5;
     // Apply a Gaussian 3x3 filter to the source image followed by a Gaussian 5x5:
     // The function will automatically update the padding information inside input and output to match its requirements
     conv3x3.configure(&src, &tmp, gaussian3x3, 0 /* Let arm_compute calculate the scale */, BorderMode::UNDEFINED);
     conv5x5.configure(&tmp, &dst, gaussian5x5, 0 /* Let arm_compute calculate the scale */, BorderMode::UNDEFINED);
     // Now that the padding requirements are known we can allocate the images:
     src.allocator()->allocate();
     tmp.allocator()->allocate();
     dst.allocator()->allocate();
     // Fill the input image with the content of the PPM image if a filename was provided:
     if(ppm.is_open())
     {
         ppm.fill_image(src);
     }
     //Execute the functions:
     conv3x3.run();
     conv5x5.run();
     // Save the result to file:
     if(ppm.is_open())
     {
         const std::string output_filename = std::string(argv[1]) + "_out.ppm";
         save_to_ppm(dst, output_filename);
     }
 }
Variable Documentation
const int16_t gaussian3x3[]
Initial value:
=
{
    1, 2, 1,
    2, 4, 2,
    1, 2, 1
}
Gaussian 3x3 matrix.
Definition at line 34 of file neon_convolution.cpp.
Referenced by main_neon_convolution().
const int16_t gaussian5x5[]
Initial value:
=
{
    1, 4, 6, 4, 1,
    4, 16, 24, 16, 4,
    6, 24, 36, 24, 6,
    4, 16, 24, 16, 4,
    1, 4, 6, 4, 1
}
Gaussian 5x5 matrix.
Definition at line 43 of file neon_convolution.cpp.
Referenced by main_neon_convolution().