Compute Library: WeightsInfo Class Reference
WeightsInfo Class Reference
Convolution Layer Weights Information class.
#include <Types.h>
Public Member Functions
WeightsInfo ()
Default constructor.
WeightsInfo (bool are_reshaped, unsigned int kernel_width, unsigned int kernel_height, unsigned int num_kernels, bool retain_internal_weights=false, arm_compute::WeightFormat weight_format=arm_compute::WeightFormat::UNSPECIFIED)
Constructor.
bool are_reshaped () const
Flag which specifies if the weights tensor has been reshaped.
unsigned int num_kernels () const
Return the number of convolution kernels.
std::pair< unsigned int, unsigned int > kernel_size () const
Return the width and height of the kernel.
bool retain_internal_weights () const
arm_compute::WeightFormat weight_format () const
void set_weight_format (arm_compute::WeightFormat weight_format)
unsigned int kernel_width () const
unsigned int kernel_height () const
Detailed Description
Convolution Layer Weights Information class.
This class stores the necessary information to compute convolution layer when the weights are already reshaped
Definition at line 2075 of file Types.h.
Constructor & Destructor Documentation
WeightsInfo() [1/2]
WeightsInfo () inline
Default constructor.
Definition at line 2079 of file Types.h.
         : _are_reshaped(false), _kernel_width(0), _kernel_height(0), _num_kernels(0), _retain_internal_weights(false), _weight_format(arm_compute::WeightFormat::UNSPECIFIED)
     {
     }
WeightsInfo() [2/2]
WeightsInfo (bool are_reshaped, unsigned int kernel_width, unsigned int kernel_height, unsigned int num_kernels, bool retain_internal_weights = false, arm_compute::WeightFormat weight_format = arm_compute::WeightFormat::UNSPECIFIED) inline
Constructor.
Parameters
[in] are_reshaped True if the weights have been reshaped
[in] kernel_width Kernel width.
[in] kernel_height Kernel height.
[in] num_kernels Number of convolution kernels.
[in] retain_internal_weights (Optional) True if internal reshaped weights must be retained. Used for reconfiguration purposes. Default is false.
[in] weight_format (Optional) arm_gemm:WeightFormat enumeration requested by the user. Default is arm_compute::WeightFormat::UNSPECIFIED.
Definition at line 2092 of file Types.h.
         : _are_reshaped(are_reshaped), _kernel_width(kernel_width), _kernel_height(kernel_height), _num_kernels(num_kernels), _retain_internal_weights(retain_internal_weights), _weight_format(weight_format)
     {
     }
Member Function Documentation
are_reshaped()
bool are_reshaped () const inline
Flag which specifies if the weights tensor has been reshaped.
Returns
True if the weights tensors has been reshaped
Definition at line 2101 of file Types.h.
Referenced by arm_compute::operator<<(), ClGemmConv2d::validate(), and CpuGemmConv2d::validate().
     {
         return _are_reshaped;
     };
kernel_height()
unsigned int kernel_height () const inline
Definition at line 2138 of file Types.h.
     {
         return _kernel_height;
     }
kernel_size()
std::pair<unsigned int, unsigned int> kernel_size () const inline
Return the width and height of the kernel.
Returns
The width and height of the kernel
Definition at line 2117 of file Types.h.
Referenced by arm_compute::operator<<().
     {
         return std::make_pair(_kernel_width, _kernel_height);
     }
kernel_width()
unsigned int kernel_width () const inline
Definition at line 2134 of file Types.h.
     {
         return _kernel_width;
     }
num_kernels()
unsigned int num_kernels () const inline
Return the number of convolution kernels.
Returns
The number of convolution kernels
Definition at line 2109 of file Types.h.
Referenced by arm_compute::operator<<().
     {
         return _num_kernels;
     };
retain_internal_weights()
bool retain_internal_weights () const inline
Definition at line 2121 of file Types.h.
Referenced by ClGemmConv2d::configure(), CpuGemmConv2d::configure(), and CLDirectDeconvolutionLayer::configure().
     {
         return _retain_internal_weights;
     }
set_weight_format()
void set_weight_format (arm_compute::WeightFormat weight_format) inline
Definition at line 2129 of file Types.h.
     {
         _weight_format = weight_format;
     }
weight_format()
arm_compute::WeightFormat weight_format () const inline
Definition at line 2125 of file Types.h.
Referenced by CpuGemmDirectConv2d::configure(), CpuFullyConnected::configure(), CpuGemmConv2d::configure(), CpuFullyConnected::has_opt_impl(), CpuGemmConv2d::has_opt_impl(), CpuFullyConnected::validate(), and CpuGemmConv2d::validate().
     {
         return _weight_format;
     }
The documentation for this class was generated from the following file:
arm_compute/core/Types.h