Compute Library: IGraphMutator Class Reference
IGraphMutator Class Reference abstract
Graph mutator interface.
#include <IGraphMutator.h>
Public Types
enum MutationType { IR, Backend }
Mutation type.
Public Member Functions
virtual ~IGraphMutator ()=default
Virtual Destructor.
virtual void mutate (Graph &g)=0
Walk the graph and perform a specific mutation.
virtual MutationType type () const =0
Returns mutation type.
virtual const char * name ()=0
Returns mutator name.
Detailed Description
Graph mutator interface.
Definition at line 35 of file IGraphMutator.h.
Member Enumeration Documentation
MutationType
enum MutationType strong
Mutation type.
Enumerator
IR
Backend
IR specific mutation.
Backend specific mutation
Definition at line 39 of file IGraphMutator.h.
     {
         IR,     /** IR specific mutation */
         Backend /** Backend specific mutation */
     };
Constructor & Destructor Documentation
~IGraphMutator()
virtual ~IGraphMutator () virtual default
Virtual Destructor.
Member Function Documentation
mutate()
virtual void mutate (Graph & g) pure virtual
Walk the graph and perform a specific mutation.
Parameters
[in,out] g Graph to walk and mutate
Implemented in NodeExecutionMethodMutator, DepthConcatSubTensorMutator, GroupedConvolutionMutator, SplitLayerSubTensorMutator, SyntheticDataTypeMutator, NodeFusionMutator, and InPlaceOperationMutator.
Referenced by PassManager::run_all(), PassManager::run_index(), and PassManager::run_type().
name()
virtual const char* name () pure virtual
Returns mutator name.
Returns
Mutator name
Implemented in NodeExecutionMethodMutator, DepthConcatSubTensorMutator, GroupedConvolutionMutator, SplitLayerSubTensorMutator, SyntheticDataTypeMutator, NodeFusionMutator, and InPlaceOperationMutator.
Referenced by PassManager::run_all(), PassManager::run_index(), and PassManager::run_type().
type()
virtual MutationType type () const pure virtual
Returns mutation type.
Returns
Mutation type enumeration
Implemented in NodeExecutionMethodMutator, DepthConcatSubTensorMutator, GroupedConvolutionMutator, SplitLayerSubTensorMutator, SyntheticDataTypeMutator, NodeFusionMutator, and InPlaceOperationMutator.
Referenced by PassManager::run_type().
The documentation for this class was generated from the following file:
arm_compute/graph/IGraphMutator.h