Compute Library: ClComponentResize Class Reference
ClComponentResize Class Reference final
#include <ClComponentResize.h>
Public Types
using Attributes = ResizeAttributes
Attributes are a set of backend-agnostic parameters that define what a component does.
Public Types inherited from IGpuKernelComponent
using Properties = KernelProperties
Public Member Functions
ClComponentResize (ComponentId id, const Properties &properties, const ArgumentPack< ITensorInfo > &tensors, const Attributes &attributes)
Constructor.
~ClComponentResize () override
Destructor.
ClComponentResize (const ClComponentResize &component)=delete
Prevent instances of this class from being copy constructed.
ClComponentResize & operator= (const ClComponentResize &component)=delete
Prevent instances of this class from being copied.
ClComponentResize (ClComponentResize &&component)=default
Allow instances of this class to be move constructed.
ClComponentResize & operator= (ClComponentResize &&component)=default
Allow instances of this class to be moved.
const IGpuTemplateComponentWriter * template_writer () const override
Get template writer for the component.
GpuComponentType type () const override
Get component type.
Public Member Functions inherited from IGpuKernelComponent
IGpuKernelComponent (ComponentId id, const Properties &properties, const ArgumentPack< ITensorInfo > &tensors)
Constructor.
virtual ~IGpuKernelComponent ()
Destructor.
ComponentId id () const
Get component id.
ArgumentPack< ITensorInfo > tensors () const
Get tensor arguments.
Properties properties () const
Get properties.
Static Public Member Functions
static Status validate (const Properties &properties, const ArgumentPack< ITensorInfo > &tensors, const Attributes &attributes)
Validate the component.
Detailed Description
Definition at line 46 of file ClComponentResize.h.
Member Typedef Documentation
Attributes
using Attributes = ResizeAttributes
Attributes are a set of backend-agnostic parameters that define what a component does.
Definition at line 50 of file ClComponentResize.h.
Constructor & Destructor Documentation
ClComponentResize() [1/3]
ClComponentResize (ComponentId id, const Properties & properties, const ArgumentPack< ITensorInfo > & tensors, const Attributes & attributes)
Constructor.
Similar to ClComponentResize::validate()
Definition at line 65 of file ClComponentResize.cpp.
References IGpuKernelComponent::id(), IGpuKernelComponent::properties(), and IGpuKernelComponent::tensors().
     : IGpuKernelComponent{ id, properties, tensors },
       _component_writer{ std::make_unique<ClTemplateResize>(id, tensors, attributes) }
 {
 }
~ClComponentResize()
~ClComponentResize () override
Destructor.
Definition at line 74 of file ClComponentResize.cpp.
 {
 }
ClComponentResize() [2/3]
ClComponentResize (const ClComponentResize & component) delete
Prevent instances of this class from being copy constructed.
ClComponentResize() [3/3]
ClComponentResize (ClComponentResize && component) default
Allow instances of this class to be move constructed.
Member Function Documentation
operator=() [1/2]
ClComponentResize& operator= (const ClComponentResize & component) delete
Prevent instances of this class from being copied.
operator=() [2/2]
ClComponentResize& operator= (ClComponentResize && component) default
Allow instances of this class to be moved.
template_writer()
const IGpuTemplateComponentWriter * template_writer () const override virtual
Get template writer for the component.
Implements IGpuKernelComponent.
Definition at line 78 of file ClComponentResize.cpp.
 {
     return _component_writer.get();
 }
type()
GpuComponentType type () const inline override virtual
Get component type.
Implements IGpuKernelComponent.
Definition at line 114 of file ClComponentResize.h.
References arm_compute::experimental::dynamic_fusion::Complex.
     {
         return GpuComponentType::Complex;
     }
validate()
Status validate (const Properties & properties, const ArgumentPack< ITensorInfo > & tensors, const Attributes & attributes) static
Validate the component.
Parameters
[in] properties Component properties Properties
[in,out] tensors Tensor arguments to the component
[in] attributes Component attributes Attributes
Returns
Status Validation results
Tensor argument names:
ACL_SRC_0: Input
ACL_DST_0: Output
Tensor argument constness:
ACL_SRC_0: Const
ACL_DST_0: Const
Valid data layouts:
NHWC
Valid data type configurations:
ACL_SRC_0 ACL_DST_0
QASYMM8 QASYMM8
QASYMM8_SIGNED QASYMM8_SIGNED
F16 F16
F32 F32
U8 U8
S16 S16
Definition at line 39 of file ClComponentResize.cpp.
References arm_compute::ACL_DST_0, arm_compute::ACL_SRC_0, ResizeAttributes::align_corners(), ARM_COMPUTE_RETURN_ERROR_ON, ARM_COMPUTE_RETURN_ERROR_ON_F16_UNSUPPORTED, ARM_COMPUTE_RETURN_ERROR_ON_MISMATCHING_DATA_TYPES, ARM_COMPUTE_RETURN_ERROR_ON_MISMATCHING_QUANTIZATION_INFO, ARM_COMPUTE_UNUSED, arm_compute::test::validation::dst, ArgumentPack< T >::get_const_tensor(), arm_compute::scale_utils::is_align_corners_allowed_sampling_policy(), ResizeAttributes::sampling_policy(), arm_compute::test::validation::src, ITensorInfo::tensor_shape(), and TensorShape::total_size().
 {
     ARM_COMPUTE_UNUSED(properties);
     const ITensorInfo *src = tensors.get_const_tensor(TensorType::ACL_SRC_0);
     const ITensorInfo *dst = tensors.get_const_tensor(TensorType::ACL_DST_0);
     // Mismatching data types and quantization info
     ARM_COMPUTE_RETURN_ERROR_ON_MISMATCHING_DATA_TYPES(src, dst);
     ARM_COMPUTE_RETURN_ERROR_ON_MISMATCHING_QUANTIZATION_INFO(src, dst);
     // Device requirements met
     ARM_COMPUTE_RETURN_ERROR_ON_F16_UNSUPPORTED(src);
     // Align corners and sampling policy conformance
     ARM_COMPUTE_RETURN_ERROR_ON(attributes.align_corners() && !arm_compute::scale_utils::is_align_corners_allowed_sampling_policy(attributes.sampling_policy()));
     // All tensor infos are initialized
     ARM_COMPUTE_RETURN_ERROR_ON(src->tensor_shape().total_size() == 0);
     ARM_COMPUTE_RETURN_ERROR_ON(dst->tensor_shape().total_size() == 0);
     return Status();
 }
The documentation for this class was generated from the following files:
src/dynamic_fusion/sketch/gpu/components/cl/ClComponentResize.h
src/dynamic_fusion/sketch/gpu/components/cl/ClComponentResize.cpp