Compute Library: CpuConvertFullyConnectedWeightsKernel Class Reference
CpuConvertFullyConnectedWeightsKernel Class Reference
Interface to convert the 2D Fully Connected weights from NCHW to NHWC or vice versa.
#include <CpuConvertFullyConnectedWeightsKernel.h>
Public Member Functions
CpuConvertFullyConnectedWeightsKernel ()=default
ARM_COMPUTE_DISALLOW_COPY_ALLOW_MOVE (CpuConvertFullyConnectedWeightsKernel)
void configure (const ITensorInfo *src, ITensorInfo *dst, const TensorShape &original_input_shape, DataLayout data_layout)
Set the src and dst tensor.
void run_op (ITensorPack &tensors, const Window &window, const ThreadInfo &info) override
Execute the kernel on the passed window.
const char * name () const override
Name of the kernel.
Public Member Functions inherited from ICPPKernel
virtual ~ICPPKernel ()=default
Default destructor.
virtual void run (const Window &window, const ThreadInfo &info)
Execute the kernel on the passed window.
virtual void run_nd (const Window &window, const ThreadInfo &info, const Window &thread_locator)
legacy compatibility layer for implemantions which do not support thread_locator In these cases we simply narrow the interface down the legacy version
virtual size_t get_mws (const CPUInfo &platform, size_t thread_count) const
Return minimum workload size of the relevant kernel.
Public Member Functions inherited from IKernel
IKernel ()
Constructor.
virtual ~IKernel ()=default
Destructor.
virtual bool is_parallelisable () const
Indicates whether or not the kernel is parallelisable.
virtual BorderSize border_size () const
The size of the border for that kernel.
const Window & window () const
The maximum window the kernel can be executed on.
bool is_window_configured () const
Function to check if the embedded window of this kernel has been configured.
Static Public Member Functions
static Status validate (const ITensorInfo *src, const ITensorInfo *dst, const TensorShape &original_input_shape, DataLayout data_layout)
Static function to check if given info will lead to a valid configuration.
Static Public Member Functions inherited from ICpuKernel< CpuConvertFullyConnectedWeightsKernel >
static const auto * get_implementation (const SelectorType &selector, KernelSelectionType selection_type=KernelSelectionType::Supported)
Micro-kernel selector.
Additional Inherited Members
Static Public Attributes inherited from ICPPKernel
static constexpr size_t default_mws = 1
Detailed Description
Interface to convert the 2D Fully Connected weights from NCHW to NHWC or vice versa.
Note
This function can be applied to the 2D weights used by a Fully Connected layer if:
It follows a Convolution layer
The data layout used by the network does not match the one the model has been trained in.
This function assumes the weights are already reshaped (transposed)
Definition at line 44 of file CpuConvertFullyConnectedWeightsKernel.h.
Constructor & Destructor Documentation
CpuConvertFullyConnectedWeightsKernel()
CpuConvertFullyConnectedWeightsKernel () default
Member Function Documentation
ARM_COMPUTE_DISALLOW_COPY_ALLOW_MOVE()
ARM_COMPUTE_DISALLOW_COPY_ALLOW_MOVE (CpuConvertFullyConnectedWeightsKernel)
configure()
void configure (const ITensorInfo * src, ITensorInfo * dst, const TensorShape & original_input_shape, DataLayout data_layout)
Set the src and dst tensor.
Parameters
[in] src Source weights tensor info to convert. Must be 2 dimensional. Data types supported: All.
[in] dst The converted weights tensor info. Shape and Data Type: Same as src.
[in] original_input_shape Shape of the original src tensor (the one entering fully connected layer).
[in] data_layout The data layout the weights have been trained in.
Definition at line 37 of file CpuConvertFullyConnectedWeightsKernel.cpp.
References ARM_COMPUTE_ERROR_ON_NULLPTR, ARM_COMPUTE_ERROR_THROW_ON, arm_compute::auto_init_if_empty(), arm_compute::calculate_max_window(), arm_compute::CHANNEL, ICloneable< T >::clone(), arm_compute::get_data_layout_dimension_index(), arm_compute::HEIGHT, arm_compute::NCHW, arm_compute::NHWC, CpuConvertFullyConnectedWeightsKernel::validate(), and arm_compute::WIDTH.
 {
     ARM_COMPUTE_ERROR_ON_NULLPTR(src, dst);
     // Output tensor auto initialisation if not yet initialized
     auto_init_if_empty(*dst, *src->clone());
     ARM_COMPUTE_ERROR_THROW_ON(CpuConvertFullyConnectedWeightsKernel::validate(src, dst, original_input_shape, data_layout));
     const DataLayout input_data_layout = (data_layout == DataLayout::NCHW) ? DataLayout::NHWC : DataLayout::NCHW;
     const int width_idx   = get_data_layout_dimension_index(input_data_layout, DataLayoutDimension::WIDTH);
     const int height_idx  = get_data_layout_dimension_index(input_data_layout, DataLayoutDimension::HEIGHT);
     const int channel_idx = get_data_layout_dimension_index(input_data_layout, DataLayoutDimension::CHANNEL);
     const unsigned int num_elems_per_input_plane = original_input_shape[width_idx] * original_input_shape[height_idx];
     const unsigned int num_channels              = original_input_shape[channel_idx];
     _factor1 = (data_layout == DataLayout::NCHW) ? num_elems_per_input_plane : num_channels;
     _factor2 = (data_layout == DataLayout::NCHW) ? num_channels : num_elems_per_input_plane;
     // Configure kernel window
     Window win = calculate_max_window(*src, Steps());
     ICpuKernel::configure(win);
 }
name()
const char * name () const override virtual
Name of the kernel.
Returns
Kernel name
Implements ICPPKernel.
Definition at line 107 of file CpuConvertFullyConnectedWeightsKernel.cpp.
 {
     return "CpuConvertFullyConnectedWeightsKernel";
 }
run_op()
void run_op (ITensorPack & tensors, const Window & window, const ThreadInfo & info) override virtual
Execute the kernel on the passed window.
Warning
If is_parallelisable() returns false then the passed window must be equal to window()
Note
The window has to be a region within the window returned by the window() method
The width of the window has to be a multiple of num_elems_processed_per_iteration().
Parameters
[in] tensors A vector containing the tensors to operate on.
[in] window Region on which to execute the kernel. (Must be a region of the window returned by window())
[in] info Info about executing thread and CPU.
Reimplemented from ICPPKernel.
Definition at line 84 of file CpuConvertFullyConnectedWeightsKernel.cpp.
References arm_compute::ACL_DST, arm_compute::ACL_SRC, ARM_COMPUTE_ERROR_ON_INVALID_SUBWINDOW, ARM_COMPUTE_ERROR_ON_UNCONFIGURED_KERNEL, ARM_COMPUTE_UNUSED, arm_compute::test::validation::dst, arm_compute::execute_window_loop(), ITensorPack::get_const_tensor(), ITensorPack::get_tensor(), arm_compute::test::validation::input, Iterator::ptr(), arm_compute::test::validation::src, and IKernel::window().
 {
     ARM_COMPUTE_UNUSED(info);
     ARM_COMPUTE_ERROR_ON_UNCONFIGURED_KERNEL(this);
     ARM_COMPUTE_ERROR_ON_INVALID_SUBWINDOW(ICpuKernel::window(), window);
     const auto src = tensors.get_const_tensor(TensorType::ACL_SRC);
     auto       dst = tensors.get_tensor(TensorType::ACL_DST);
     const unsigned int dst_stride_x = dst->info()->strides_in_bytes().x();
     const unsigned int dst_stride_y = dst->info()->strides_in_bytes().y();
     const unsigned int element_size = src->info()->element_size();
     Iterator input(src, window);
     Iterator output(dst, window);
     execute_window_loop(window, [&](const Coordinates & id)
     {
         memcpy(output.ptr() + id.x() * dst_stride_x + (id.y() % _factor1 * _factor2 + id.y() / _factor1) * dst_stride_y, input.ptr(), element_size);
     },
     input);
 }
validate()
Status validate (const ITensorInfo * src, const ITensorInfo * dst, const TensorShape & original_input_shape, DataLayout data_layout) static
Static function to check if given info will lead to a valid configuration.
Similar to CpuConvertFullyConnectedWeightsKernel::configure()
Returns
a status
Definition at line 65 of file CpuConvertFullyConnectedWeightsKernel.cpp.
References ARM_COMPUTE_RETURN_ERROR_ON, ARM_COMPUTE_RETURN_ERROR_ON_MISMATCHING_DATA_TYPES, ARM_COMPUTE_RETURN_ERROR_ON_MISMATCHING_SHAPES, ARM_COMPUTE_RETURN_ERROR_ON_NULLPTR, ITensorInfo::data_type(), ITensorInfo::dimension(), ITensorInfo::num_dimensions(), ITensorInfo::total_size(), TensorShape::total_size_lower(), and arm_compute::UNKNOWN.
Referenced by CpuConvertFullyConnectedWeightsKernel::configure(), and CpuConvertFullyConnectedWeights::validate().
 {
     ARM_COMPUTE_RETURN_ERROR_ON_NULLPTR(src);
     ARM_COMPUTE_RETURN_ERROR_ON(src->data_type() == DataType::UNKNOWN);
     ARM_COMPUTE_RETURN_ERROR_ON(src->num_dimensions() != 2);
     ARM_COMPUTE_RETURN_ERROR_ON(src->dimension(1) != original_input_shape.total_size_lower(3));
     ARM_COMPUTE_RETURN_ERROR_ON(data_layout == DataLayout::UNKNOWN);
     // Checks performed when dst is configured
     if((dst != nullptr) && (dst->total_size() != 0))
     {
         ARM_COMPUTE_RETURN_ERROR_ON_MISMATCHING_DATA_TYPES(src, dst);
         ARM_COMPUTE_RETURN_ERROR_ON_MISMATCHING_SHAPES(src, dst);
     }
     return Status{};
 }
The documentation for this class was generated from the following files:
src/cpu/kernels/CpuConvertFullyConnectedWeightsKernel.h
src/cpu/kernels/CpuConvertFullyConnectedWeightsKernel.cpp