Compute Library: NEInstanceNormalizationLayerKernel Class Reference
NEInstanceNormalizationLayerKernel Class Reference
Interface for performing an instance normalization.
#include <NEInstanceNormalizationLayerKernel.h>
Public Member Functions
const char * name () const override
Name of the kernel.
NEInstanceNormalizationLayerKernel ()
Default constructor.
NEInstanceNormalizationLayerKernel (const NEInstanceNormalizationLayerKernel &)=delete
Prevent instances of this class from being copied (As this class contains pointers)
NEInstanceNormalizationLayerKernel & operator= (const NEInstanceNormalizationLayerKernel &)=delete
Prevent instances of this class from being copied (As this class contains pointers)
NEInstanceNormalizationLayerKernel (NEInstanceNormalizationLayerKernel &&)=default
Allow instances of this class to be moved.
NEInstanceNormalizationLayerKernel & operator= (NEInstanceNormalizationLayerKernel &&)=default
Allow instances of this class to be moved.
~NEInstanceNormalizationLayerKernel ()=default
Default destructor.
void configure (ITensor *input, ITensor *output, const InstanceNormalizationLayerKernelInfo &info)
Set the input and output tensors.
void run (const Window &window, const ThreadInfo &info) override
Execute the kernel on the passed window.
Public Member Functions inherited from ICPPKernel
virtual ~ICPPKernel ()=default
Default destructor.
virtual void run_nd (const Window &window, const ThreadInfo &info, const Window &thread_locator)
legacy compatibility layer for implemantions which do not support thread_locator In these cases we simply narrow the interface down the legacy version
virtual void run_op (ITensorPack &tensors, const Window &window, const ThreadInfo &info)
Execute the kernel on the passed window.
virtual size_t get_mws (const CPUInfo &platform, size_t thread_count) const
Return minimum workload size of the relevant kernel.
Public Member Functions inherited from IKernel
IKernel ()
Constructor.
virtual ~IKernel ()=default
Destructor.
virtual bool is_parallelisable () const
Indicates whether or not the kernel is parallelisable.
virtual BorderSize border_size () const
The size of the border for that kernel.
const Window & window () const
The maximum window the kernel can be executed on.
bool is_window_configured () const
Function to check if the embedded window of this kernel has been configured.
Static Public Member Functions
static Status validate (const ITensorInfo *input, const ITensorInfo *output, const InstanceNormalizationLayerKernelInfo &info)
Static function to check if given info will lead to a valid configuration of NEInstanceNormalizationLayer.
Additional Inherited Members
Static Public Attributes inherited from ICPPKernel
static constexpr size_t default_mws = 1
Detailed Description
Interface for performing an instance normalization.
Definition at line 35 of file NEInstanceNormalizationLayerKernel.h.
Constructor & Destructor Documentation
NEInstanceNormalizationLayerKernel() [1/3]
NEInstanceNormalizationLayerKernel ()
Default constructor.
Definition at line 130 of file NEInstanceNormalizationLayerKernel.cpp.
Referenced by NEInstanceNormalizationLayerKernel::name().
     : _input(nullptr), _output(nullptr), _gamma(1), _beta(0), _epsilon(1e-12)
 {
 }
NEInstanceNormalizationLayerKernel() [2/3]
NEInstanceNormalizationLayerKernel (const NEInstanceNormalizationLayerKernel &) delete
Prevent instances of this class from being copied (As this class contains pointers)
NEInstanceNormalizationLayerKernel() [3/3]
NEInstanceNormalizationLayerKernel (NEInstanceNormalizationLayerKernel &&) default
Allow instances of this class to be moved.
~NEInstanceNormalizationLayerKernel()
~NEInstanceNormalizationLayerKernel () default
Default destructor.
Referenced by NEInstanceNormalizationLayerKernel::name().
Member Function Documentation
configure()
void configure (ITensor * input, ITensor * output, const InstanceNormalizationLayerKernelInfo & info)
Set the input and output tensors.
Parameters
[in,out] input Source tensor. Data types supported: F16/F32. Data layout supported: NCHW In case of output tensor = nullptr this tensor will store the result of the normalization.
[out] output Destination tensor. Data types and data layouts supported: same as input.
[in] info Kernel meta-data descriptor
Definition at line 135 of file NEInstanceNormalizationLayerKernel.cpp.
References ARM_COMPUTE_ERROR_ON_NULLPTR, ARM_COMPUTE_ERROR_THROW_ON, InstanceNormalizationLayerKernelInfo::beta, InstanceNormalizationLayerKernelInfo::epsilon, InstanceNormalizationLayerKernelInfo::gamma, ITensor::info(), arm_compute::test::validation::input, InstanceNormalizationLayerKernelInfo::use_mixed_precision, arm_compute::cpu::kernels::validate_and_configure_window(), and arm_compute::cpu::kernels::validate_arguments().
Referenced by NEInstanceNormalizationLayerKernel::name().
 {
     ARM_COMPUTE_ERROR_ON_NULLPTR(input);
     _input               = input;
     _output              = output == nullptr ? input : output;
     _gamma               = info.gamma;
     _beta                = info.beta;
     _epsilon             = info.epsilon;
     _use_mixed_precision = info.use_mixed_precision;
     ARM_COMPUTE_ERROR_THROW_ON(validate_arguments(_input->info(), _output->info(), _gamma, _beta, _epsilon));
     // Configure kernel window
     auto win_config = validate_and_configure_window(_input->info(), _output->info());
     ARM_COMPUTE_ERROR_THROW_ON(std::get<0>(win_config));
     INEKernel::configure(std::get<1>(win_config));
 }
name()
const char* name () const inline override virtual
Name of the kernel.
Returns
Kernel name
Implements ICPPKernel.
Definition at line 38 of file NEInstanceNormalizationLayerKernel.h.
References NEInstanceNormalizationLayerKernel::configure(), arm_compute::quantization::epsilon, arm_compute::test::validation::info, arm_compute::test::validation::input, NEInstanceNormalizationLayerKernel::NEInstanceNormalizationLayerKernel(), NEInstanceNormalizationLayerKernel::operator=(), NEInstanceNormalizationLayerKernel::run(), NEInstanceNormalizationLayerKernel::validate(), IKernel::window(), and NEInstanceNormalizationLayerKernel::~NEInstanceNormalizationLayerKernel().
     {
         return "NEInstanceNormalizationLayerKernel";
     }
operator=() [1/2]
NEInstanceNormalizationLayerKernel& operator= (const NEInstanceNormalizationLayerKernel &) delete
Prevent instances of this class from being copied (As this class contains pointers)
Referenced by NEInstanceNormalizationLayerKernel::name().
operator=() [2/2]
NEInstanceNormalizationLayerKernel& operator= (NEInstanceNormalizationLayerKernel &&) default
Allow instances of this class to be moved.
run()
void run (const Window & window, const ThreadInfo & info) override virtual
Execute the kernel on the passed window.
Warning
If is_parallelisable() returns false then the passed window must be equal to window()
Note
The window has to be a region within the window returned by the window() method
The width of the window has to be a multiple of num_elems_processed_per_iteration().
Parameters
[in] window Region on which to execute the kernel. (Must be a region of the window returned by window())
[in] info Info about executing thread and CPU.
Reimplemented from ICPPKernel.
Definition at line 162 of file NEInstanceNormalizationLayerKernel.cpp.
References ARM_COMPUTE_ERROR_ON, ARM_COMPUTE_ERROR_ON_INVALID_SUBWINDOW, ARM_COMPUTE_ERROR_ON_UNCONFIGURED_KERNEL, ARM_COMPUTE_UNUSED, ITensorInfo::data_type(), ITensor::info(), and IKernel::window().
Referenced by NEInstanceNormalizationLayerKernel::name().
 {
     ARM_COMPUTE_UNUSED(info);
     ARM_COMPUTE_ERROR_ON_UNCONFIGURED_KERNEL(this);
     ARM_COMPUTE_ERROR_ON_INVALID_SUBWINDOW(INEKernel::window(), window);
     const auto *uk = get_implementation(InstanceNormSelectorData{ _input->info()->data_type() });
     ARM_COMPUTE_ERROR_ON(uk == nullptr || uk->ukernel == nullptr);
     uk->ukernel(_input, _output, _gamma, _beta, _epsilon, _use_mixed_precision, window);
 }
validate()
Status validate (const ITensorInfo * input, const ITensorInfo * output, const InstanceNormalizationLayerKernelInfo & info) static
Static function to check if given info will lead to a valid configuration of NEInstanceNormalizationLayer.
Parameters
[in] input Source tensor info. Data types supported: F16/F32. Data layout supported: NCHW
[in] output Destination tensor info. Data types and data layouts supported: same as input.
[in] info Kernel meta-data descriptor
Returns
a status
Definition at line 155 of file NEInstanceNormalizationLayerKernel.cpp.
References ARM_COMPUTE_RETURN_ON_ERROR, InstanceNormalizationLayerKernelInfo::beta, ICloneable< T >::clone(), InstanceNormalizationLayerKernelInfo::epsilon, InstanceNormalizationLayerKernelInfo::gamma, arm_compute::cpu::kernels::validate_and_configure_window(), and arm_compute::cpu::kernels::validate_arguments().
Referenced by NEInstanceNormalizationLayerKernel::name(), and NEInstanceNormalizationLayer::validate().
 {
     ARM_COMPUTE_RETURN_ON_ERROR(validate_arguments(input, output, info.gamma, info.beta, info.epsilon));
     ARM_COMPUTE_RETURN_ON_ERROR(std::get<0>(validate_and_configure_window(input->clone().get(), (output == nullptr ? input->clone().get() : output->clone().get()))));
     return Status{};
 }
The documentation for this class was generated from the following files:
src/core/NEON/kernels/NEInstanceNormalizationLayerKernel.h
src/core/NEON/kernels/NEInstanceNormalizationLayerKernel.cpp