Compute Library: NDRange< D > Class Template Reference
NDRange< D > Class Template Reference
#include <ndrange.hpp>
Public Member Functions
NDRange & operator= (const NDRange &rhs)=default
NDRange (const NDRange &rhs)=default
template<typename... T>
NDRange (T... ts)
NDRange (const std::array< unsigned int, D > &n)
NDRangeIterator iterator (unsigned int start, unsigned int end) const
unsigned int total_size () const
unsigned int get_size (unsigned int v) const
Detailed Description
template<unsigned int D>
class arm_gemm::NDRange< D >
Definition at line 34 of file ndrange.hpp.
Constructor & Destructor Documentation
NDRange() [1/3]
NDRange (const NDRange< D > & rhs) default
NDRange() [2/3]
NDRange (T... ts) inline
Definition at line 119 of file ndrange.hpp.
         : m_sizes{ ts... }
     {
         set_totalsizes();
     }
NDRange() [3/3]
NDRange (const std::array< unsigned int, D > & n) inline
Definition at line 125 of file ndrange.hpp.
         : m_sizes(n)
     {
         set_totalsizes();
     }
Member Function Documentation
get_size()
unsigned int get_size (unsigned int v) const inline
Definition at line 141 of file ndrange.hpp.
Referenced by GemmInterleavedPretransposed2d< strategy, To, Tr >::execute(), NDCoordinate< N >::get_position_end(), and arm_gemm::to_window().
     {
         return m_sizes[v];
     }
iterator()
NDRangeIterator iterator (unsigned int start, unsigned int end) const inline
Definition at line 131 of file ndrange.hpp.
Referenced by GemmHybrid< strategy, To, Tr >::execute(), GemmHybridQuantizedInline< strategy, To, Tr >::execute(), GemmHybridQuantized< strategy, To, Tr >::execute(), and GemmHybridIndirect< strategy, To, Tr, OutputStage, SeparateQuantize, FixedFormat >::execute().
     {
         return NDRangeIterator(*this, start, end);
     }
operator=()
NDRange& operator= (const NDRange< D > & rhs) default
total_size()
unsigned int total_size () const inline
Definition at line 136 of file ndrange.hpp.
Referenced by GemmHybrid< strategy, To, Tr >::get_window_size(), GemmHybridQuantizedInline< strategy, To, Tr >::get_window_size(), GemmHybridQuantized< strategy, To, Tr >::get_window_size(), and GemmHybridIndirect< strategy, To, Tr, OutputStage, SeparateQuantize, FixedFormat >::get_window_size().
     {
         return m_totalsizes[D - 1];
     }
The documentation for this class was generated from the following file:
src/cpu/kernels/assembly/ndrange.hpp