Compute Library: GEMMInfo Class Reference
GEMMInfo Class Reference
GEMM information class.
#include <Types.h>
Public Member Functions
GEMMInfo () noexcept
Default constructor.
GEMMInfo (bool is_a_reshaped, bool is_b_reshaped, bool reshape_b_only_on_first_run, int depth_output_gemm3d=0, bool reinterpret_input_as_3d=false, bool retain_internal_weights=false, GEMMLowpOutputStageInfo gemmlowp_output_stage=GEMMLowpOutputStageInfo(), bool fp_mixed_precision=false, bool fast_math=false, bool broadcast_bias=false, const ActivationLayerInfo &activation_info=ActivationLayerInfo(), const experimental::PostOpList< ITensorInfo *> &post_ops=experimental::PostOpList< ITensorInfo *>(), bool fixed_format=false, arm_compute::WeightFormat weight_format=arm_compute::WeightFormat::UNSPECIFIED) noexcept
Constructor.
bool is_a_reshaped () const
Flag which specifies if the matrix A has been reshaped.
bool is_b_reshaped () const
Flag which specifies if the matrix B has been reshaped.
bool reshape_b_only_on_first_run () const
Flag which specifies if the reshape of matrix B should executed only for the first.
int depth_output_gemm3d () const
Depth of the output when GEMM output is reinterpreted as 3D tensor.
bool reinterpret_input_as_3d () const
Flag which specifies if the input tensor has to be reinterpreted as 3D.
bool retain_internal_weights () const
Flag which specifies if the weights tensor has to be retained from previous run.
GEMMLowpOutputStageInfo gemmlowp_output_stage () const
GEMMLowp output stage.
void set_gemmlowp_output_stage (GEMMLowpOutputStageInfo &output_stage)
Sets GEMMLowp output stage.
bool fp_mixed_precision () const
Flag which specifies if a wider accumulator should be used.
bool fast_math () const
Flag which specifies if a shorter accumulator to be used.
void set_fast_math (bool fast_math)
Set fast math flag.
bool broadcast_bias () const
Flag which specifies whether to broadcast the shape of the bias tensor.
bool pretranspose_A () const
Flag which specifies whether A should be pre-transposed if supported.
void set_pretranspose_A (bool flag)
Set pre-transpose A flag.
bool pretranspose_B () const
Flag which specifies whether b should be pre-transposed if supported.
void set_pretranspose_B (bool flag)
Set pre-transpose b flag.
ActivationLayerInfo activation_info () const
Activation layer to apply after the matrix multiplication.
void set_activation_info (const ActivationLayerInfo &activation_info)
Set activation layer info.
const experimental::PostOpList< ITensorInfo * > & post_ops () const
Post operations to apply after the matrix multiplication.
void set_post_ops (const experimental::PostOpList< ITensorInfo *> &post_ops)
Set post ops.
bool fixed_format () const
Flag which specifies if the GEMM operation is running fixed-format kernels.
void set_fixed_format (bool fixed_format)
Set fixed-format flag.
arm_compute::WeightFormat weight_format () const
void set_weight_format (arm_compute::WeightFormat weight_format)
Set weight format to be used.
Detailed Description
GEMM information class.
This class stores the necessary information to compute GEMM functions
This object also contains the information about how matrix A and matrix B have been reshaped
Definition at line 2341 of file Types.h.
Constructor & Destructor Documentation
GEMMInfo() [1/2]
GEMMInfo () inline noexcept
Default constructor.
Definition at line 2345 of file Types.h.
         : _is_a_reshaped(false),
           _is_b_reshaped(false),
           _reshape_b_only_on_first_run(true),
           _depth_output_gemm3d(0),
           _reinterpret_input_as_3d(false),
           _retain_internal_weights(false),
           _gemmlowp_output_stage(),
           _fast_math(false),
           _fp_mixed_precision(false),
           _broadcast_bias(false),
           _pretranspose_A(false),
           _pretranspose_B(false),
           _activation_info(),
           _post_ops(),
           _fixed_format(false),
           _weight_format(arm_compute::WeightFormat::UNSPECIFIED)
     {
     }
GEMMInfo() [2/2]
GEMMInfo (bool is_a_reshaped, bool is_b_reshaped, bool reshape_b_only_on_first_run, int depth_output_gemm3d = 0, bool reinterpret_input_as_3d = false, bool retain_internal_weights = false, GEMMLowpOutputStageInfo gemmlowp_output_stage = GEMMLowpOutputStageInfo(), bool fp_mixed_precision = false, bool fast_math = false, bool broadcast_bias = false, const ActivationLayerInfo & activation_info = ActivationLayerInfo(), const experimental::PostOpList< ITensorInfo *> & post_ops = experimental::PostOpList<ITensorInfo *>(), bool fixed_format = false, arm_compute::WeightFormat weight_format = arm_compute::WeightFormat::UNSPECIFIED) inline noexcept
Constructor.
Parameters
[in] is_a_reshaped True if the matrix A has been reshaped
[in] is_b_reshaped True if the matrix B has been reshaped
[in] reshape_b_only_on_first_run Reshape matrix B only for the first run
[in] depth_output_gemm3d (Optional) Depth (third dimension) of the output tensor to be used with the GEMM3D kernel If 0 the output will not be reinterpreted as 3D. Default 0
[in] reinterpret_input_as_3d (Optional) Reinterpret the input as 3D tensor. (i.e. this flag should be set to true when GEMM is used to perform 1x1 convolutions with the NHWC data layout)
[in] retain_internal_weights (Optional) Retain the weights tensor from previous run
[in] gemmlowp_output_stage (Optional) GEMMLowp Output stage info
[in] fp_mixed_precision (Optional) Use wider accumulators (32 bit instead of 16 for FP16) to improve accuracy.
[in] fast_math (Optional) Use a data type of shorter width to improve performance
[in] broadcast_bias (Optional) Broadcast the shape of the bias tensor from a vector to a matrix.
[in] activation_info (Optional) Activation to apply after the matrix multiplication
[in] post_ops (Optional) A sequence of post operations that are performed after the main operation.
[in] fixed_format (Optional) Specify the selection of fixed format kernels for variable weights support in GEMM. These kernels expect the weights tensor to be in amemory format that is fixed by the kernel itself. For more information, see arm_compute::WeightFormat.
[in] weight_format (Optional) arm_gemm:WeightFormat enumeration requested by the user. Default is arm_compute::WeightFormat::UNSPECIFIED.
Definition at line 2383 of file Types.h.
         : _is_a_reshaped(is_a_reshaped),
           _is_b_reshaped(is_b_reshaped),
           _reshape_b_only_on_first_run(reshape_b_only_on_first_run),
           _depth_output_gemm3d(depth_output_gemm3d),
           _reinterpret_input_as_3d(reinterpret_input_as_3d),
           _retain_internal_weights(retain_internal_weights),
           _gemmlowp_output_stage(gemmlowp_output_stage),
           _fast_math(fast_math),
           _fp_mixed_precision(fp_mixed_precision),
           _broadcast_bias(broadcast_bias),
           _pretranspose_A(false),
           _pretranspose_B(false),
           _activation_info(activation_info),
           _post_ops(post_ops),
           _fixed_format(fixed_format),
           _weight_format(weight_format)
     {
     }
Member Function Documentation
activation_info()
ActivationLayerInfo activation_info () const inline
Activation layer to apply after the matrix multiplication.
Returns
ActivationLayerInfo object
Definition at line 2539 of file Types.h.
Referenced by CpuGemmLowpMatrixMultiplyCore::configure(), CpuGemm::validate(), and CpuGemmLowpMatrixMultiplyCore::validate().
     {
         return _activation_info;
     }
broadcast_bias()
bool broadcast_bias () const inline
Flag which specifies whether to broadcast the shape of the bias tensor.
Returns
True if the shape of the bias tensor is to be broadcasted.
Definition at line 2499 of file Types.h.
Referenced by arm_compute::operator<<().
     {
         return _broadcast_bias;
     };
depth_output_gemm3d()
int depth_output_gemm3d () const inline
Depth of the output when GEMM output is reinterpreted as 3D tensor.
Returns
the depth of the output tensor
Definition at line 2435 of file Types.h.
Referenced by ClGemmLowpMatrixMultiplyCore::configure(), arm_compute::operator<<(), ClGemmLowpMatrixMultiplyCore::validate(), and CpuGemm::validate().
     {
         return _depth_output_gemm3d;
     };
fast_math()
bool fast_math () const inline
Flag which specifies if a shorter accumulator to be used.
Returns
True if a shorter accumulator has to be used
Definition at line 2483 of file Types.h.
     {
         return _fast_math;
     };
fixed_format()
bool fixed_format () const inline
Flag which specifies if the GEMM operation is running fixed-format kernels.
Returns
True if the GEMM operation is running fixed-format kernel else false.
Definition at line 2571 of file Types.h.
Referenced by CpuGemm::validate().
     {
         return _fixed_format;
     }
fp_mixed_precision()
bool fp_mixed_precision () const inline
Flag which specifies if a wider accumulator should be used.
Returns
True if a wider accumulator has to be used
Definition at line 2475 of file Types.h.
Referenced by arm_compute::operator<<().
     {
         return _fp_mixed_precision;
     };
gemmlowp_output_stage()
GEMMLowpOutputStageInfo gemmlowp_output_stage () const inline
GEMMLowp output stage.
Returns
the GEMMLowp output stage info
Definition at line 2459 of file Types.h.
Referenced by ClGemmLowpMatrixMultiplyCore::configure(), CpuGemmLowpMatrixMultiplyCore::configure(), ClGemmLowpMatrixMultiplyCore::prepare(), CpuGemmLowpMatrixMultiplyCore::run(), ClGemmLowpMatrixMultiplyCore::validate(), and CpuGemmLowpMatrixMultiplyCore::validate().
     {
         return _gemmlowp_output_stage;
     };
is_a_reshaped()
bool is_a_reshaped () const inline
Flag which specifies if the matrix A has been reshaped.
Returns
True if the matrix A has been reshaped
Definition at line 2409 of file Types.h.
Referenced by arm_compute::operator<<(), ClGemmLowpMatrixMultiplyCore::validate(), CpuGemm::validate(), and CpuGemmLowpMatrixMultiplyCore::validate().
     {
         return _is_a_reshaped;
     };
is_b_reshaped()
bool is_b_reshaped () const inline
Flag which specifies if the matrix B has been reshaped.
Returns
True if the matrix B has been reshaped
Definition at line 2417 of file Types.h.
Referenced by arm_compute::operator<<(), ClGemmLowpMatrixMultiplyCore::validate(), CpuGemm::validate(), and CpuGemmLowpMatrixMultiplyCore::validate().
     {
         return _is_b_reshaped;
     };
post_ops()
const experimental::PostOpList<ITensorInfo *>& post_ops () const inline
Post operations to apply after the matrix multiplication.
Returns
experimental::PostOpList object
Definition at line 2555 of file Types.h.
Referenced by arm_compute::operator<<().
     {
         return _post_ops;
     }
pretranspose_A()
bool pretranspose_A () const inline
Flag which specifies whether A should be pre-transposed if supported.
Returns
True if A should be pre-transposed else false.
Definition at line 2507 of file Types.h.
     {
         return _pretranspose_A;
     };
pretranspose_B()
bool pretranspose_B () const inline
Flag which specifies whether b should be pre-transposed if supported.
Returns
True if b should be pre-transposed else false.
Definition at line 2523 of file Types.h.
Referenced by arm_compute::operator<<().
     {
         return _pretranspose_B;
     };
reinterpret_input_as_3d()
bool reinterpret_input_as_3d () const inline
Flag which specifies if the input tensor has to be reinterpreted as 3D.
Returns
True if the input tensor has to be reinterpreted as 3D tensor
Definition at line 2443 of file Types.h.
Referenced by ClGemm::configure(), ClGemmLowpMatrixMultiplyCore::configure(), arm_compute::operator<<(), ClGemm::validate(), ClGemmLowpMatrixMultiplyCore::validate(), and CpuGemm::validate().
     {
         return _reinterpret_input_as_3d;
     };
reshape_b_only_on_first_run()
bool reshape_b_only_on_first_run () const inline
Flag which specifies if the reshape of matrix B should executed only for the first.
Note
This flag could be set to TRUE when GEMM is used to accelerate convolution layer
Returns
True if the reshaped of matrix B happens only for the first run
Definition at line 2427 of file Types.h.
Referenced by ClGemm::configure(), CpuGemm::configure(), ClGemmLowpMatrixMultiplyCore::configure(), CpuGemmLowpMatrixMultiplyCore::configure(), arm_compute::operator<<(), ClGemm::validate(), ClGemmLowpMatrixMultiplyCore::validate(), and CpuGemm::validate().
     {
         return _reshape_b_only_on_first_run;
     };
retain_internal_weights()
bool retain_internal_weights () const inline
Flag which specifies if the weights tensor has to be retained from previous run.
Returns
True if the weights tensor has to be retained
Definition at line 2451 of file Types.h.
Referenced by ClGemm::configure(), CLGEMM::configure(), CLGEMMLowpMatrixMultiplyCore::configure(), and arm_compute::operator<<().
     {
         return _retain_internal_weights;
     };
set_activation_info()
void set_activation_info (const ActivationLayerInfo & activation_info) inline
Set activation layer info.
Parameters
[in] activation_info ActivationLayerInfo object to set
Definition at line 2547 of file Types.h.
Referenced by CpuFullyConnected::has_opt_impl().
     {
         _activation_info = activation_info;
     }
set_fast_math()
void set_fast_math (bool fast_math) inline
Set fast math flag.
Parameters
[in] fast_math Flag to set
Definition at line 2491 of file Types.h.
Referenced by CpuFullyConnected::has_opt_impl().
     {
         _fast_math = fast_math;
     }
set_fixed_format()
void set_fixed_format (bool fixed_format) inline
Set fixed-format flag.
Parameters
[in] fixed_format sets whether or not to use fixed-format kernels
Definition at line 2580 of file Types.h.
Referenced by CpuFullyConnected::has_opt_impl().
     {
         _fixed_format = fixed_format;
     }
set_gemmlowp_output_stage()
void set_gemmlowp_output_stage (GEMMLowpOutputStageInfo & output_stage) inline
Sets GEMMLowp output stage.
Parameters
[in] output_stage Output stage to set
Definition at line 2467 of file Types.h.
References output_stage.
Referenced by CpuGemmLowpMatrixMultiplyCore::configure().
     {
         _gemmlowp_output_stage = output_stage;
     };
set_post_ops()
void set_post_ops (const experimental::PostOpList< ITensorInfo *> & post_ops) inline
Set post ops.
Parameters
[in] post_ops experimental::PostOpList object to set
Definition at line 2563 of file Types.h.
References arm_compute::test::validation::post_ops.
     {
         _post_ops = post_ops;
     }
set_pretranspose_A()
void set_pretranspose_A (bool flag) inline
Set pre-transpose A flag.
Parameters
[in] flag Flag to set
Definition at line 2515 of file Types.h.
     {
         _pretranspose_A = flag;
     }
set_pretranspose_B()
void set_pretranspose_B (bool flag) inline
Set pre-transpose b flag.
Parameters
[in] flag Flag to set
Definition at line 2531 of file Types.h.
     {
         _pretranspose_B = flag;
     }
set_weight_format()
void set_weight_format (arm_compute::WeightFormat weight_format) inline
Set weight format to be used.
Parameters
[in] weight_format arm_compute::WeightFormat enumeration
Definition at line 2594 of file Types.h.
Referenced by CpuFullyConnected::has_opt_impl().
     {
         _weight_format = weight_format;
     }
weight_format()
arm_compute::WeightFormat weight_format () const inline
Definition at line 2585 of file Types.h.
Referenced by CpuGemm::validate().
     {
         return _weight_format;
     }
The documentation for this class was generated from the following file:
arm_compute/core/Types.h