Compute Library: DepthwiseDepthfirstStrategyCommon< TInput, TWeight, TOutput, TAccum, OutputStage > Class Template Reference
DepthwiseDepthfirstStrategyCommon< TInput, TWeight, TOutput, TAccum, OutputStage > Class Template Reference
#include <depthwise_depthfirst.hpp>
Public Member Functions
DepthwiseDepthfirstStrategyCommon (unsigned int output_rows, unsigned int output_cols, unsigned int kernel_rows, unsigned int kernel_cols, unsigned int stride_rows=1, unsigned int stride_cols=1)
DepthwiseDepthfirstStrategyCommon (unsigned int output_size, unsigned int kernel_size, unsigned int stride=1)
virtual ~DepthwiseDepthfirstStrategyCommon ()
unsigned int get_output_rows () const override
unsigned int get_output_cols () const override
unsigned int get_kernel_rows () const override
unsigned int get_kernel_cols () const override
unsigned int get_stride_rows () const override
unsigned int get_stride_cols () const override
Public Member Functions inherited from DepthfirstStrategy< TInput, TWeight, TOutput, TAccum, OutputStage >
virtual size_t get_storage_size (const DepthwiseArgs &args) const
virtual void pack_parameters (const DepthwiseArgs &args, void *buffer, const void *biases, const OutputStage &, const void *weights, size_t ld_weight_col, size_t ld_weight_row) const
Public Member Functions inherited from DepthfirstStrategyUntyped
virtual arm_gemm::VLType get_vl_type () const =0
virtual unsigned int get_input_rows () const override
virtual unsigned int get_input_cols () const override
virtual unsigned int get_n_input_points () const
virtual unsigned int get_n_output_points () const
virtual unsigned int get_n_kernel_points () const
virtual unsigned int get_accumulator_depth_vl () const
virtual bool get_kernel_packing_point (const unsigned int index, unsigned int &x, unsigned int &y) const
Public Member Functions inherited from IDepthfirstStrategy
virtual ~IDepthfirstStrategy ()=default
Detailed Description
template<typename TInput, typename TWeight, typename TOutput, typename TAccum, typename OutputStage>
class arm_conv::depthwise::DepthwiseDepthfirstStrategyCommon< TInput, TWeight, TOutput, TAccum, OutputStage >
Definition at line 42 of file depthwise_depthfirst.hpp.
Constructor & Destructor Documentation
DepthwiseDepthfirstStrategyCommon() [1/2]
DepthwiseDepthfirstStrategyCommon (unsigned int output_rows, unsigned int output_cols, unsigned int kernel_rows, unsigned int kernel_cols, unsigned int stride_rows = 1, unsigned int stride_cols = 1) inline
Definition at line 51 of file depthwise_depthfirst.hpp.
     : m_output_rows(output_rows), m_output_cols(output_cols),
       m_kernel_rows(kernel_rows), m_kernel_cols(kernel_cols),
       m_stride_rows(stride_rows), m_stride_cols(stride_cols)
   {
   }
DepthwiseDepthfirstStrategyCommon() [2/2]
DepthwiseDepthfirstStrategyCommon (unsigned int output_size, unsigned int kernel_size, unsigned int stride = 1) inline
Definition at line 61 of file depthwise_depthfirst.hpp.
   : DepthwiseDepthfirstStrategyCommon(output_size, output_size, kernel_size, kernel_size, stride, stride)
   {
   }
~DepthwiseDepthfirstStrategyCommon()
virtual ~DepthwiseDepthfirstStrategyCommon () inline virtual
Definition at line 66 of file depthwise_depthfirst.hpp.
 {}
Member Function Documentation
get_kernel_cols()
unsigned int get_kernel_cols () const inline override virtual
Implements DepthfirstStrategyUntyped.
Definition at line 72 of file depthwise_depthfirst.hpp.
Referenced by StrategyType< true, TInput, TWeight, TOutput, TAccum, OutputStage >::execute(), and StrategyType< true, TInput, TWeight, TOutput, int32_t, arm_gemm::Requantize32 >::execute().
 { return m_kernel_cols; }
get_kernel_rows()
unsigned int get_kernel_rows () const inline override virtual
Implements DepthfirstStrategyUntyped.
Definition at line 71 of file depthwise_depthfirst.hpp.
Referenced by StrategyType< true, TInput, TWeight, TOutput, TAccum, OutputStage >::execute(), and StrategyType< true, TInput, TWeight, TOutput, int32_t, arm_gemm::Requantize32 >::execute().
 { return m_kernel_rows; }
get_output_cols()
unsigned int get_output_cols () const inline override virtual
Implements IDepthfirstStrategy.
Definition at line 69 of file depthwise_depthfirst.hpp.
Referenced by DepthwiseDepthfirst< TInput, TWeight, TOutput, TAccum, OutputStage >::initialise_working_space().
 { return m_output_cols; }
get_output_rows()
unsigned int get_output_rows () const inline override virtual
Implements IDepthfirstStrategy.
Definition at line 68 of file depthwise_depthfirst.hpp.
Referenced by DepthwiseDepthfirst< TInput, TWeight, TOutput, TAccum, OutputStage >::initialise_working_space().
 { return m_output_rows; }
get_stride_cols()
unsigned int get_stride_cols () const inline override virtual
Implements DepthfirstStrategyUntyped.
Definition at line 75 of file depthwise_depthfirst.hpp.
 { return m_stride_cols; }
get_stride_rows()
unsigned int get_stride_rows () const inline override virtual
Implements DepthfirstStrategyUntyped.
Definition at line 74 of file depthwise_depthfirst.hpp.
 { return m_stride_rows; }
The documentation for this class was generated from the following file:
src/core/NEON/kernels/arm_conv/depthwise/depthwise_depthfirst.hpp