Compute Library: NEPadLayerKernel Class Reference
NEPadLayerKernel Class Reference
Basic kernel to pad the input tensor given padding information.
#include <NEPadLayerKernel.h>
Public Member Functions
const char * name () const override
Name of the kernel.
NEPadLayerKernel ()
Default constructor.
NEPadLayerKernel (const NEPadLayerKernel &)=delete
Prevent instances of this class from being copied (As this class contains pointers)
NEPadLayerKernel & operator= (const NEPadLayerKernel &)=delete
Prevent instances of this class from being copied (As this class contains pointers)
NEPadLayerKernel (NEPadLayerKernel &&)=default
Allow instances of this class to be moved.
NEPadLayerKernel & operator= (NEPadLayerKernel &&)=default
Allow instances of this class to be moved.
~NEPadLayerKernel ()=default
Default destructor.
void configure (ITensor *input, ITensor *output, const PaddingList &padding, const PixelValue constant_value=PixelValue(), const PaddingMode mode=PaddingMode::CONSTANT)
Initialize the function.
void run (const Window &window, const ThreadInfo &info) override
Execute the kernel on the passed window.
size_t get_mws (const CPUInfo &platform, size_t thread_count) const override
Return minimum workload size of the relevant kernel.
Public Member Functions inherited from ICPPKernel
virtual ~ICPPKernel ()=default
Default destructor.
virtual void run_nd (const Window &window, const ThreadInfo &info, const Window &thread_locator)
legacy compatibility layer for implemantions which do not support thread_locator In these cases we simply narrow the interface down the legacy version
virtual void run_op (ITensorPack &tensors, const Window &window, const ThreadInfo &info)
Execute the kernel on the passed window.
Public Member Functions inherited from IKernel
IKernel ()
Constructor.
virtual ~IKernel ()=default
Destructor.
virtual bool is_parallelisable () const
Indicates whether or not the kernel is parallelisable.
virtual BorderSize border_size () const
The size of the border for that kernel.
const Window & window () const
The maximum window the kernel can be executed on.
bool is_window_configured () const
Function to check if the embedded window of this kernel has been configured.
Static Public Member Functions
static Status validate (const ITensorInfo *input, const ITensorInfo *output, const PaddingList &padding, const PixelValue constant_value=PixelValue(), const PaddingMode mode=PaddingMode::CONSTANT)
Static function to check if given info will lead to a valid configuration of NEPadLayer.
Additional Inherited Members
Static Public Attributes inherited from ICPPKernel
static constexpr size_t default_mws = 1
Detailed Description
Basic kernel to pad the input tensor given padding information.
Definition at line 34 of file NEPadLayerKernel.h.
Constructor & Destructor Documentation
NEPadLayerKernel() [1/3]
NEPadLayerKernel ()
Default constructor.
Definition at line 181 of file NEPadLayerKernel.cpp.
Referenced by NEPadLayerKernel::name().
     : _func(), _input(nullptr), _output(nullptr), _padding(), _constant_value(), _mode()
 {
 }
NEPadLayerKernel() [2/3]
NEPadLayerKernel (const NEPadLayerKernel &) delete
Prevent instances of this class from being copied (As this class contains pointers)
NEPadLayerKernel() [3/3]
NEPadLayerKernel (NEPadLayerKernel &&) default
Allow instances of this class to be moved.
~NEPadLayerKernel()
~NEPadLayerKernel () default
Default destructor.
Referenced by NEPadLayerKernel::name().
Member Function Documentation
configure()
void configure (ITensor * input, ITensor * output, const PaddingList & padding, const PixelValue constant_value = PixelValue(), const PaddingMode mode = PaddingMode::CONSTANT)
Initialize the function.
Parameters
[in] input Source tensor. Data types supported: All.
[out] output Output tensor. Data type supported: same as input
[in] padding The padding for each spatial dimension of the input tensor. The pair padding[i] specifies the front and the end padding in the i-th dimension.
[in] constant_value (Optional) Constant value to be used for the padding
[in] mode (Optional) Controls whether the padding should be filled with constant_value using CONSTANT. Only CONSTANT padding mode is currently supported
Definition at line 186 of file NEPadLayerKernel.cpp.
References ARM_COMPUTE_ERROR, ARM_COMPUTE_ERROR_ON_NULLPTR, ARM_COMPUTE_ERROR_THROW_ON, arm_compute::auto_init_if_empty(), arm_compute::calculate_max_window(), ICloneable< T >::clone(), arm_compute::misc::shape_calculator::compute_padded_shape(), arm_compute::CONSTANT, ITensorInfo::element_size(), ITensorInfo::has_padding(), ITensor::info(), arm_compute::test::validation::input, clang_tidy_rules::mode, ITensorInfo::num_dimensions(), ITensorInfo::tensor_shape(), and arm_compute::cpu::kernels::validate_arguments().
Referenced by NEPadLayerKernel::name().
 {
     ARM_COMPUTE_ERROR_ON_NULLPTR(input, output);
     // Auto-init
     const TensorShape expected_output_shape = arm_compute::misc::shape_calculator::compute_padded_shape(input->info()->tensor_shape(), padding);
     const TensorInfo  expected_output_info  = input->info()->clone()->set_tensor_shape(expected_output_shape);
     auto_init_if_empty(*output->info(), expected_output_info);
     // Perform validation step
     ARM_COMPUTE_ERROR_THROW_ON(validate_arguments(input->info(), output->info(), padding, mode));
     _input          = input;
     _output         = output;
     _padding        = padding;
     _constant_value = constant_value;
     _mode           = mode;
     if(_mode == PaddingMode::CONSTANT)
     {
         switch(_input->info()->element_size())
         {
             case 1:
                 if(_input->info()->num_dimensions() == 3 &&                           // Is 3D
                    padding.size() <= 3 &&                                             // Has 3D padding
                    !_input->info()->has_padding() && !_output->info()->has_padding()) // Input & Output have no padding
                 {
                     _func = &NEPadLayerKernel::run_pad_constant_uint8_3Dinput_3Dpad;
                 }
                 else
                 {
                     _func = &NEPadLayerKernel::run_pad_constant<uint8_t>;
                 }
                 break;
             case 2:
                 _func = &NEPadLayerKernel::run_pad_constant<uint16_t>;
                 break;
             case 4:
                 _func = &NEPadLayerKernel::run_pad_constant<uint32_t>;
                 break;
             default:
                 ARM_COMPUTE_ERROR("Element size not supported");
                 break;
         }
     }
     else
     {
         ARM_COMPUTE_ERROR("Padding mode not supported");
     }
     // Configure kernel window
     Window win = calculate_max_window(*output->info(), Steps());
     // The NEPad doesn't need padding so update_window_and_padding() can be skipped
     ICPPKernel::configure(win);
 }
get_mws()
size_t get_mws (const CPUInfo & platform, size_t thread_count) const override virtual
Return minimum workload size of the relevant kernel.
Parameters
[in] platform The CPU platform used to create the context.
[in] thread_count Number of threads in the execution.
Returns
[out] small_network_mws Minimum workload size for requsted configuration.
Reimplemented from ICPPKernel.
Definition at line 262 of file NEPadLayerKernel.cpp.
References ARM_COMPUTE_UNUSED, and ICPPKernel::default_mws.
Referenced by NEPadLayerKernel::name().
 {
     ARM_COMPUTE_UNUSED(thread_count);
     ARM_COMPUTE_UNUSED(platform);
     return ICPPKernel::default_mws;
 }
name()
const char* name () const inline override virtual
Name of the kernel.
Returns
Kernel name
Implements ICPPKernel.
Definition at line 37 of file NEPadLayerKernel.h.
References NEPadLayerKernel::configure(), arm_compute::CONSTANT, NEPadLayerKernel::get_mws(), arm_compute::test::validation::info, arm_compute::test::validation::input, clang_tidy_rules::mode, NEPadLayerKernel::NEPadLayerKernel(), NEPadLayerKernel::operator=(), NEPadLayerKernel::run(), NEPadLayerKernel::validate(), IKernel::window(), and NEPadLayerKernel::~NEPadLayerKernel().
     {
         return "NEPadLayerKernel";
     }
operator=() [1/2]
NEPadLayerKernel& operator= (const NEPadLayerKernel &) delete
Prevent instances of this class from being copied (As this class contains pointers)
Referenced by NEPadLayerKernel::name().
operator=() [2/2]
NEPadLayerKernel& operator= (NEPadLayerKernel &&) default
Allow instances of this class to be moved.
run()
void run (const Window & window, const ThreadInfo & info) override virtual
Execute the kernel on the passed window.
Warning
If is_parallelisable() returns false then the passed window must be equal to window()
Note
The window has to be a region within the window returned by the window() method
The width of the window has to be a multiple of num_elems_processed_per_iteration().
Parameters
[in] window Region on which to execute the kernel. (Must be a region of the window returned by window())
[in] info Info about executing thread and CPU.
Reimplemented from ICPPKernel.
Definition at line 250 of file NEPadLayerKernel.cpp.
References ARM_COMPUTE_ERROR_ON_INVALID_SUBWINDOW, ARM_COMPUTE_ERROR_ON_UNCONFIGURED_KERNEL, ARM_COMPUTE_UNUSED, and IKernel::window().
Referenced by NEPadLayerKernel::name().
 {
     ARM_COMPUTE_UNUSED(info);
     ARM_COMPUTE_ERROR_ON_UNCONFIGURED_KERNEL(this);
     ARM_COMPUTE_ERROR_ON_INVALID_SUBWINDOW(INEKernel::window(), window);
     if(_func != nullptr)
     {
         (this->*_func)(window);
     }
 }
validate()
Status validate (const ITensorInfo * input, const ITensorInfo * output, const PaddingList & padding, const PixelValue constant_value = PixelValue(), const PaddingMode mode = PaddingMode::CONSTANT) static
Static function to check if given info will lead to a valid configuration of NEPadLayer.
Parameters
[in] input Source tensor info. Data types supported: All.
[in] output Output tensor info. Data type supported: same as input
[in] padding The padding for each spatial dimension of the input tensor. The pair padding[i] specifies the front and the end padding in the i-th dimension.
[in] constant_value (Optional) Constant value to be used for the padding
[in] mode (Optional) Controls whether the padding should be filled with constant_value using CONSTANT. Only CONSTANT padding mode is currently supported
Returns
a status
Definition at line 243 of file NEPadLayerKernel.cpp.
References ARM_COMPUTE_RETURN_ON_ERROR, ARM_COMPUTE_UNUSED, and arm_compute::cpu::kernels::validate_arguments().
Referenced by NEPadLayerKernel::name(), and NEPadLayer::validate().
 {
     ARM_COMPUTE_UNUSED(constant_value);
     ARM_COMPUTE_RETURN_ON_ERROR(validate_arguments(input, output, padding, mode));
     return Status{};
 }
The documentation for this class was generated from the following files:
src/core/NEON/kernels/NEPadLayerKernel.h
src/core/NEON/kernels/NEPadLayerKernel.cpp