Compute Library: ClComponentReshape Class Reference
ClComponentReshape Class Reference final
#include <ClComponentReshape.h>
Public Member Functions
ClComponentReshape (ComponentId id, const Properties &properties, const ArgumentPack< ITensorInfo > &tensors)
Constructor.
~ClComponentReshape () override
Destructor.
ClComponentReshape (const ClComponentReshape &component)=delete
Prevent instances of this class from being copy constructed.
ClComponentReshape & operator= (const ClComponentReshape &component)=delete
Prevent instances of this class from being copied.
ClComponentReshape (ClComponentReshape &&component)=default
Allow instances of this class to be move constructed.
ClComponentReshape & operator= (ClComponentReshape &&component)=default
Allow instances of this class to be moved.
const IGpuTemplateComponentWriter * template_writer () const override
Get template writer for the component.
GpuComponentType type () const override
Get component type.
Public Member Functions inherited from IGpuKernelComponent
IGpuKernelComponent (ComponentId id, const Properties &properties, const ArgumentPack< ITensorInfo > &tensors)
Constructor.
virtual ~IGpuKernelComponent ()
Destructor.
ComponentId id () const
Get component id.
ArgumentPack< ITensorInfo > tensors () const
Get tensor arguments.
Properties properties () const
Get properties.
Static Public Member Functions
static Status validate (const ArgumentPack< ITensorInfo > &tensors)
Validate the component.
Additional Inherited Members
Public Types inherited from IGpuKernelComponent
using Properties = KernelProperties
Detailed Description
Definition at line 44 of file ClComponentReshape.h.
Constructor & Destructor Documentation
ClComponentReshape() [1/3]
ClComponentReshape (ComponentId id, const Properties & properties, const ArgumentPack< ITensorInfo > & tensors)
Constructor.
Parameters
[in] id Component id
[in] properties Component properties Properties
[in] tensors Tensor arguments to the component
Definition at line 52 of file ClComponentReshape.cpp.
References IGpuKernelComponent::id(), IGpuKernelComponent::properties(), and IGpuKernelComponent::tensors().
     : IGpuKernelComponent{ id, properties, tensors },
       _component_writer{ std::make_unique<ClTemplateReshape>(id, tensors) }
 {
 }
~ClComponentReshape()
~ClComponentReshape () override
Destructor.
Definition at line 60 of file ClComponentReshape.cpp.
 {
 }
ClComponentReshape() [2/3]
ClComponentReshape (const ClComponentReshape & component) delete
Prevent instances of this class from being copy constructed.
ClComponentReshape() [3/3]
ClComponentReshape (ClComponentReshape && component) default
Allow instances of this class to be move constructed.
Member Function Documentation
operator=() [1/2]
ClComponentReshape& operator= (const ClComponentReshape & component) delete
Prevent instances of this class from being copied.
operator=() [2/2]
ClComponentReshape& operator= (ClComponentReshape && component) default
Allow instances of this class to be moved.
template_writer()
const IGpuTemplateComponentWriter * template_writer () const override virtual
Get template writer for the component.
Implements IGpuKernelComponent.
Definition at line 63 of file ClComponentReshape.cpp.
 {
     return _component_writer.get();
 }
type()
GpuComponentType type () const inline override virtual
Get component type.
Implements IGpuKernelComponent.
Definition at line 94 of file ClComponentReshape.h.
References arm_compute::experimental::dynamic_fusion::Complex.
     {
         return GpuComponentType::Complex;
     }
validate()
Status validate (const ArgumentPack< ITensorInfo > & tensors) static
Validate the component.
Parameters
[in,out] tensors Tensor arguments to the component
Returns
Status Validation results
Tensor argument names:
ACL_SRC_0: src
ACL_DST_0: dst
Tensor argument constness:
ACL_SRC_0: Const
ACL_DST_0: Const
Valid data layouts:
All
Valid data type configurations:
All
Definition at line 36 of file ClComponentReshape.cpp.
References arm_compute::ACL_DST_0, arm_compute::ACL_SRC_0, ARM_COMPUTE_RETURN_ERROR_ON, ARM_COMPUTE_RETURN_ERROR_ON_F16_UNSUPPORTED, ARM_COMPUTE_RETURN_ERROR_ON_MISMATCHING_DATA_TYPES, ARM_COMPUTE_RETURN_ERROR_ON_MISMATCHING_QUANTIZATION_INFO, ARM_COMPUTE_RETURN_ERROR_ON_NULLPTR, arm_compute::test::validation::dst, ArgumentPack< T >::get_const_tensor(), arm_compute::test::validation::src, and arm_compute::UNKNOWN.
 {
     const auto src = tensors.get_const_tensor(TensorType::ACL_SRC_0);
     const auto dst = tensors.get_const_tensor(TensorType::ACL_DST_0);
     ARM_COMPUTE_RETURN_ERROR_ON_NULLPTR(src, dst);
     ARM_COMPUTE_RETURN_ERROR_ON_F16_UNSUPPORTED(src);
     ARM_COMPUTE_RETURN_ERROR_ON(src->data_type() == DataType::UNKNOWN);
     ARM_COMPUTE_RETURN_ERROR_ON(src->tensor_shape().total_size() == 0);
     ARM_COMPUTE_RETURN_ERROR_ON(dst->tensor_shape().total_size() == 0);
     ARM_COMPUTE_RETURN_ERROR_ON_MISMATCHING_DATA_TYPES(src, dst);
     ARM_COMPUTE_RETURN_ERROR_ON_MISMATCHING_QUANTIZATION_INFO(src, dst);
     ARM_COMPUTE_RETURN_ERROR_ON(src->tensor_shape().total_size() != dst->tensor_shape().total_size());
     return Status{};
 }
The documentation for this class was generated from the following files:
src/dynamic_fusion/sketch/gpu/components/cl/ClComponentReshape.h
src/dynamic_fusion/sketch/gpu/components/cl/ClComponentReshape.cpp