Compute Library: NumPyAccessor Class Reference
NumPyAccessor Class Reference final
NumPy accessor class.
#include <GraphUtils.h>
Public Member Functions
NumPyAccessor (std::string npy_path, TensorShape shape, DataType data_type, DataLayout data_layout=DataLayout::NCHW, std::ostream &output_stream=std::cout)
Constructor.
NumPyAccessor (NumPyAccessor &&)=default
Allow instances of this class to be move constructed.
NumPyAccessor (const NumPyAccessor &)=delete
Prevent instances of this class from being copied (As this class contains pointers)
NumPyAccessor & operator= (const NumPyAccessor &)=delete
Prevent instances of this class from being copied (As this class contains pointers)
bool access_tensor (ITensor &tensor) override
Interface to be implemented to access a given tensor.
Public Member Functions inherited from ITensorAccessor
virtual ~ITensorAccessor ()=default
Default virtual destructor.
virtual bool access_tensor_data ()
Returns true if the tensor data is being accessed.
Detailed Description
NumPy accessor class.
Definition at line 147 of file GraphUtils.h.
Constructor & Destructor Documentation
NumPyAccessor() [1/3]
NumPyAccessor (std::string npy_path, TensorShape shape, DataType data_type, DataLayout data_layout = DataLayout::NCHW, std::ostream & output_stream = std::cout)
Constructor.
Parameters
[in] npy_path Path to npy file.
[in] shape Shape of the numpy tensor data.
[in] data_type DataType of the numpy tensor data.
[in] data_layout (Optional) DataLayout of the numpy tensor data.
[out] output_stream (Optional) Output stream
Definition at line 185 of file GraphUtils.cpp.
References NumPyBinLoader::access_tensor(), TensorAllocator::allocate(), Tensor::allocator(), ITensor::info(), arm_compute::test::validation::info, TensorAllocator::init(), TensorInfo::set_data_layout(), tensor, ITensorInfo::tensor_shape(), and TensorShape::total_size().
     : _npy_tensor(), _filename(std::move(npy_path)), _output_stream(output_stream)
 {
     NumPyBinLoader loader(_filename, data_layout);
     TensorInfo info(shape, 1, data_type);
     info.set_data_layout(data_layout);
     _npy_tensor.allocator()->init(info);
     _npy_tensor.allocator()->allocate();
     loader.access_tensor(_npy_tensor);
 }
NumPyAccessor() [2/3]
NumPyAccessor (NumPyAccessor &&) default
Allow instances of this class to be move constructed.
NumPyAccessor() [3/3]
NumPyAccessor (const NumPyAccessor &) delete
Prevent instances of this class from being copied (As this class contains pointers)
Member Function Documentation
access_tensor()
bool access_tensor (ITensor & tensor) override virtual
Interface to be implemented to access a given tensor.
Parameters
[in] tensor Tensor to be accessed
Returns
True if access is successful else false
Implements ITensorAccessor.
Definition at line 211 of file GraphUtils.cpp.
References PrintAccessor::access_tensor(), ARM_COMPUTE_ERROR, ARM_COMPUTE_ERROR_ON, ARM_COMPUTE_ERROR_ON_DATA_TYPE_CHANNEL_NOT_IN, ITensorInfo::data_type(), ITensorInfo::dimension(), arm_compute::F32, ITensor::info(), Tensor::info(), ITensor::print(), PrintAccessor::PrintAccessor(), arm_compute::QASYMM8, and tensor.
 {
     ARM_COMPUTE_ERROR_ON_DATA_TYPE_CHANNEL_NOT_IN(&tensor, 1, DataType::F32, DataType::QASYMM8);
     ARM_COMPUTE_ERROR_ON(_npy_tensor.info()->dimension(0) != tensor.info()->dimension(0));
     switch(tensor.info()->data_type())
     {
         case DataType::QASYMM8:
             access_numpy_tensor<qasymm8_t>(tensor, 0);
             break;
         case DataType::F32:
             access_numpy_tensor<float>(tensor, 0.0001f);
             break;
         default:
             ARM_COMPUTE_ERROR("NOT SUPPORTED!");
     }
     return false;
 }
operator=()
NumPyAccessor& operator= (const NumPyAccessor &) delete
Prevent instances of this class from being copied (As this class contains pointers)
The documentation for this class was generated from the following files:
utils/GraphUtils.h
utils/GraphUtils.cpp