Compute Library: deep_unique_ptr< Base > Class Template Reference
deep_unique_ptr< Base > Class Template Reference
A deep-copying unique pointer that also supports polymorphic cloning behavior.
#include <DeepCopy.h>
Public Types
using CopyFunc = std::function< Base *(const Base *)>
Public Member Functions
deep_unique_ptr (std::nullptr_t val=nullptr) noexcept
template<typename Derived , typename CopyFuncDerived >
deep_unique_ptr (Derived *value, const CopyFuncDerived &copy) noexcept
deep_unique_ptr (const deep_unique_ptr< Base > &ptr)
deep_unique_ptr & operator= (const deep_unique_ptr< Base > &ptr)
deep_unique_ptr (deep_unique_ptr< Base > &&ptr)=default
deep_unique_ptr & operator= (deep_unique_ptr< Base > &&ptr)=default
~deep_unique_ptr ()=default
Base & operator* () noexcept
const Base & operator* () const noexcept
Base * operator-> () noexcept
const Base * operator-> () const noexcept
Base * get () noexcept
const Base * get () const noexcept
operator bool () const noexcept
bool operator== (const deep_unique_ptr< Base > &rhs) const
Friends
void swap (deep_unique_ptr &ptr0, deep_unique_ptr< Base > &ptr1) noexcept
Detailed Description
template<typename Base>
class arm_compute::utils::memory::deep_unique_ptr< Base >
A deep-copying unique pointer that also supports polymorphic cloning behavior.
Note
The == operator compares the dereferenced value instead of the pointer itself.
Template Parameters
Base Base type
Definition at line 60 of file DeepCopy.h.
Member Typedef Documentation
CopyFunc
using CopyFunc = std::function<Base *(const Base *)>
Definition at line 63 of file DeepCopy.h.
Constructor & Destructor Documentation
deep_unique_ptr() [1/4]
deep_unique_ptr (std::nullptr_t val = nullptr) inline noexcept
Definition at line 65 of file DeepCopy.h.
Referenced by deep_unique_ptr< Base >::operator=().
         : _val{ val },
     _copy{}
     {
     }
deep_unique_ptr() [2/4]
deep_unique_ptr (Derived * value, const CopyFuncDerived & copy) inline noexcept
Definition at line 71 of file DeepCopy.h.
References arm_compute::test::validation::reference::copy().
         : _val{ value },
     _copy{ std::move(copy) }
     {
         static_assert(std::is_base_of<Base, Derived>::value,
                       "Derived is not a specialization of Base");
         static_assert(
             std::is_constructible<CopyFunc, CopyFuncDerived>::value,
             "CopyFuncDerived is not valid for a copy functor");
     }
deep_unique_ptr() [3/4]
deep_unique_ptr (const deep_unique_ptr< Base > & ptr) inline
Definition at line 82 of file DeepCopy.h.
         : deep_unique_ptr(ptr.clone())
     {
     }
deep_unique_ptr() [4/4]
deep_unique_ptr (deep_unique_ptr< Base > && ptr) default
~deep_unique_ptr()
~deep_unique_ptr () default
Referenced by deep_unique_ptr< Base >::operator=().
Member Function Documentation
get() [1/2]
Base* get () inline noexcept
Definition at line 122 of file DeepCopy.h.
Referenced by deep_unique_ptr< Base >::operator==().
     {
         return _val.get();
     }
get() [2/2]
const Base* get () const inline noexcept
Definition at line 126 of file DeepCopy.h.
     {
         return _val.get();
     }
operator bool()
operator bool () const inline explicit noexcept
Definition at line 131 of file DeepCopy.h.
     {
         return static_cast<bool>(_val);
     }
operator*() [1/2]
Base& operator* () inline noexcept
Definition at line 102 of file DeepCopy.h.
     {
         return *_val;
     }
operator*() [2/2]
const Base& operator* () const inline noexcept
Definition at line 107 of file DeepCopy.h.
     {
         return *_val;
     }
operator->() [1/2]
Base* operator-> () inline noexcept
Definition at line 112 of file DeepCopy.h.
     {
         return _val.operator->();
     }
operator->() [2/2]
const Base* operator-> () const inline noexcept
Definition at line 117 of file DeepCopy.h.
     {
         return _val.operator->();
     }
operator=() [1/2]
deep_unique_ptr& operator= (const deep_unique_ptr< Base > & ptr) inline
Definition at line 86 of file DeepCopy.h.
References deep_unique_ptr< Base >::deep_unique_ptr(), deep_unique_ptr< Base >::swap, and deep_unique_ptr< Base >::~deep_unique_ptr().
     {
         deep_unique_ptr<Base> tmp(ptr);
         swap(*this, tmp);
         return *this;
     }
operator=() [2/2]
deep_unique_ptr& operator= (deep_unique_ptr< Base > && ptr) default
operator==()
bool operator== (const deep_unique_ptr< Base > & rhs) const inline
Definition at line 136 of file DeepCopy.h.
References deep_unique_ptr< Base >::get().
     {
         if(rhs.get() == nullptr && _val == nullptr)
         {
             return true;
         }
         else if(rhs.get() == nullptr || _val == nullptr)
         {
             return false;
         }
         else
         {
             return (*_val == *rhs);
         }
     }
Friends And Related Function Documentation
swap
void swap (deep_unique_ptr< Base > & ptr0, deep_unique_ptr< Base > & ptr1) friend
Definition at line 96 of file DeepCopy.h.
Referenced by deep_unique_ptr< Base >::operator=().
     {
         using std::swap;
         swap(ptr0._val, ptr1._val);
         swap(ptr0._copy, ptr1._copy);
     }
The documentation for this class was generated from the following file:
support/DeepCopy.h