Compute Library: CpuPool3d Class Reference
CpuPool3d Class Reference
Basic function to simulate a pooling layer with the specified pooling operation.
#include <CpuPool3d.h>
Public Member Functions
CpuPool3d ()
ARM_COMPUTE_DISALLOW_COPY_ALLOW_MOVE (CpuPool3d)
~CpuPool3d ()
void configure (const ITensorInfo *src, ITensorInfo *dst, const Pooling3dLayerInfo &pool_info)
Set the src and dst tensors.
void run (ITensorPack &tensors) override
Run the kernels contained in the function.
experimental::MemoryRequirements workspace () const override
Return the memory requirements required by the workspace.
Public Member Functions inherited from INEOperator
INEOperator (IRuntimeContext *ctx=nullptr)
Constructor.
INEOperator (const INEOperator &)=delete
Prevent instances of this class from being copied (As this class contains pointers)
INEOperator (INEOperator &&)=default
Default move constructor.
INEOperator & operator= (const INEOperator &)=delete
Prevent instances of this class from being copied (As this class contains pointers)
INEOperator & operator= (INEOperator &&)=default
Default move assignment operator.
~INEOperator ()
Default destructor.
void prepare (ITensorPack &constants) override
Prepare the function for executing.
Public Member Functions inherited from IOperator
virtual ~IOperator ()=default
Destructor.
Static Public Member Functions
static Status validate (const ITensorInfo *src, const ITensorInfo *dst, const Pooling3dLayerInfo &pool_info)
Static function to check if given info will lead to a valid configuration.
Detailed Description
Basic function to simulate a pooling layer with the specified pooling operation.
This function calls the following kernels:
kernels::CpuPool3dKernel
Definition at line 41 of file CpuPool3d.h.
Constructor & Destructor Documentation
CpuPool3d()
CpuPool3d ()
Definition at line 38 of file CpuPool3d.cpp.
     : _aux_mem(1)
 {
 }
~CpuPool3d()
~CpuPool3d () default
Member Function Documentation
ARM_COMPUTE_DISALLOW_COPY_ALLOW_MOVE()
ARM_COMPUTE_DISALLOW_COPY_ALLOW_MOVE (CpuPool3d)
configure()
void configure (const ITensorInfo * src, ITensorInfo * dst, const Pooling3dLayerInfo & pool_info)
Set the src and dst tensors.
Parameters
[in] src Source tensor info. Data types supported: F16/F32/QASYMM8/QASYMM8_SIGNED.
[out] dst Destination tensor info. Data types supported: same as src.
[in] pool_info Contains pooling operation information described in Pooling3dLayerInfo.
Definition at line 45 of file CpuPool3d.cpp.
References ARM_COMPUTE_LOG_PARAMS, and arm_compute::test::validation::k.
 {
     ARM_COMPUTE_LOG_PARAMS(src, dst, pool_info);
     // Configure pooling kernel
     auto k = std::make_unique<kernels::CpuPool3dKernel>();
     k->configure(src, dst, pool_info);
     _kernel = std::move(k);
 }
run()
void run (ITensorPack & tensors) override virtual
Run the kernels contained in the function.
Parameters
[in] tensors Vector that contains the tensors to operate on.
Reimplemented from INEOperator.
Definition at line 60 of file CpuPool3d.cpp.
References ARM_COMPUTE_ERROR_ON_MSG, Window::DimY, ITensorPack::empty(), Scheduler::get(), and IScheduler::schedule_op().
 {
     ARM_COMPUTE_ERROR_ON_MSG(tensors.empty(), "No tensors provided");
     Scheduler::get().schedule_op(_kernel.get(), Window::DimY, _kernel->window(), tensors);
 }
validate()
Status validate (const ITensorInfo * src, const ITensorInfo * dst, const Pooling3dLayerInfo & pool_info) static
Static function to check if given info will lead to a valid configuration.
Similar to CpuPool3d::configure()
Returns
a status
Definition at line 55 of file CpuPool3d.cpp.
References CpuPool3dKernel::validate().
Referenced by NEPooling3dLayer::validate().
 {
     return kernels::CpuPool3dKernel::validate(src, dst, pool_info);
 }
workspace()
experimental::MemoryRequirements workspace () const override virtual
Return the memory requirements required by the workspace.
Reimplemented from INEOperator.
Definition at line 67 of file CpuPool3d.cpp.
 {
     return _aux_mem;
 }
The documentation for this class was generated from the following files:
src/cpu/operators/CpuPool3d.h
src/cpu/operators/CpuPool3d.cpp