Compute Library: NEUnstack Class Reference
NEUnstack Class Reference
Basic function to unpack a rank-R tensor into rank-(R-1) tensors.
#include <NEUnstack.h>
Public Member Functions
NEUnstack ()
Default constructor.
NEUnstack (const NEUnstack &)=delete
Prevent instances of this class from being copied (As this class contains pointers)
NEUnstack & operator= (const NEUnstack &)=delete
Prevent instances of this class from being copied (As this class contains pointers)
NEUnstack (NEUnstack &&)=delete
Prevent instances of this class from being moved (As this class contains non movable objects)
NEUnstack & operator= (NEUnstack &&)=delete
Prevent instances of this class from being moved (As this class contains non movable objects)
~NEUnstack ()=default
Default destructor.
void configure (const ITensor *input, const std::vector< ITensor *> &output_vector, int axis)
Set the input, output and unstacking axis.
void run () override
Run the kernels contained in the function.
Public Member Functions inherited from IFunction
virtual ~IFunction ()=default
Destructor.
virtual void prepare ()
Prepare the function for executing.
Static Public Member Functions
static Status validate (const ITensorInfo *input, const std::vector< ITensorInfo *> &output_vector, int axis)
Static function to check if given info will lead to a valid configuration of NEUnstack.
Detailed Description
Basic function to unpack a rank-R tensor into rank-(R-1) tensors.
This function calls the following functions:
NEStridedSlice
Definition at line 43 of file NEUnstack.h.
Constructor & Destructor Documentation
NEUnstack() [1/3]
NEUnstack ()
Default constructor.
Definition at line 57 of file NEUnstack.cpp.
     : _num_slices(0),
       _strided_slice_vector()
 {
 }
NEUnstack() [2/3]
NEUnstack (const NEUnstack &) delete
Prevent instances of this class from being copied (As this class contains pointers)
NEUnstack() [3/3]
NEUnstack (NEUnstack &&) delete
Prevent instances of this class from being moved (As this class contains non movable objects)
~NEUnstack()
~NEUnstack () default
Default destructor.
Member Function Documentation
configure()
void configure (const ITensor * input, const std::vector< ITensor *> & output_vector, int axis)
Set the input, output and unstacking axis.
Valid data layouts:
All
Valid data type configurations:
src dst
All All
Parameters
[in] input A tensor to be unstacked. Data type supported: All.
[in,out] output_vector A vector of tensors. Data types supported: same as input. Note: The number of elements of the vector will be used as the number of slices to be taken from the axis.
[in] axis The axis to unstack along. Valid values are [-R,R) where R is the input's rank. Negative values wrap around.
Definition at line 63 of file NEUnstack.cpp.
References ARM_COMPUTE_ERROR_ON_NULLPTR, ARM_COMPUTE_ERROR_THROW_ON, ARM_COMPUTE_LOG_PARAMS, ITensorInfo::dimension(), ITensor::info(), Dimensions< T >::num_dimensions(), Dimensions< T >::set(), arm_compute::test::validation::reference::slice(), tf_frozen_model_extractor::t, ITensorInfo::tensor_shape(), and NEUnstack::validate().
 {
     std::vector<ITensorInfo *> outputs_vector_info(output_vector.size());
     std::transform(output_vector.begin(), output_vector.end(), outputs_vector_info.begin(), [](ITensor * t)
     {
         ARM_COMPUTE_ERROR_ON_NULLPTR(t);
         return t->info();
     });
     ARM_COMPUTE_ERROR_ON_NULLPTR(input);
     ARM_COMPUTE_ERROR_THROW_ON(NEUnstack::validate(input->info(), outputs_vector_info, axis));
     ARM_COMPUTE_LOG_PARAMS(input, output_vector, axis);
     // Wrap around negative values
     const unsigned int axis_u = wrap_axis(axis, input->info());
     _num_slices               = std::min(outputs_vector_info.size(), input->info()->dimension(axis_u));
     _strided_slice_vector.resize(_num_slices);
     Coordinates slice_start;
     int32_t     slice_end_mask;
     setup_slice_coordinates_and_mask(slice_start, slice_end_mask, input->info()->tensor_shape().num_dimensions());
     for(unsigned int slice = 0; slice < _num_slices; ++slice)
     {
         // Adjusts start and end coordinates to take a 2D slice at a time
         slice_start.set(axis_u, slice);
         _strided_slice_vector[slice].configure(input, output_vector[slice], slice_start, Coordinates(), BiStrides(), 0, slice_end_mask, (1 << axis_u));
     }
 }
operator=() [1/2]
NEUnstack& operator= (const NEUnstack &) delete
Prevent instances of this class from being copied (As this class contains pointers)
operator=() [2/2]
NEUnstack& operator= (NEUnstack &&) delete
Prevent instances of this class from being moved (As this class contains non movable objects)
run()
void run () override virtual
Run the kernels contained in the function.
For CPU kernels:
Multi-threading is used for the kernels which are parallelisable.
By default std::thread::hardware_concurrency() threads are used.
Note
CPPScheduler::set_num_threads() can be used to manually set the number of threads
For OpenCL kernels:
All the kernels are enqueued on the queue associated with CLScheduler.
The queue is then flushed.
Note
The function will not block until the kernels are executed. It is the user's responsibility to wait.
Will call prepare() on first run if hasn't been done
Implements IFunction.
Definition at line 114 of file NEUnstack.cpp.
 {
     for(unsigned i = 0; i < _num_slices; ++i)
     {
         _strided_slice_vector[i].run();
     }
 }
validate()
Status validate (const ITensorInfo * input, const std::vector< ITensorInfo *> & output_vector, int axis) static
Static function to check if given info will lead to a valid configuration of NEUnstack.
Parameters
[in] input Input tensor info. Data type supported: All.
[in] output_vector Vector of output tensors' info. Data types supported: same as input.
[in] axis The axis to unstack along. Valid values are [-R,R) where R is the input's rank. Negative values wrap around.
Returns
a status
Definition at line 92 of file NEUnstack.cpp.
References ARM_COMPUTE_RETURN_ERROR_ON, ARM_COMPUTE_RETURN_ERROR_ON_NULLPTR, ARM_COMPUTE_RETURN_ON_ERROR, ITensorInfo::dimension(), arm_compute::test::validation::k, Dimensions< T >::num_dimensions(), Dimensions< T >::set(), ITensorInfo::tensor_shape(), and NEStridedSlice::validate().
Referenced by NEUnstack::configure().
 {
     ARM_COMPUTE_RETURN_ERROR_ON_NULLPTR(input);
     ARM_COMPUTE_RETURN_ERROR_ON(output_vector.empty());
     ARM_COMPUTE_RETURN_ERROR_ON(axis < (-static_cast<int>(input->tensor_shape().num_dimensions())));
     ARM_COMPUTE_RETURN_ERROR_ON(axis >= static_cast<int>(input->tensor_shape().num_dimensions()));
     const unsigned int num_slices = std::min(output_vector.size(), input->dimension(wrap_axis(axis, input)));
     ARM_COMPUTE_RETURN_ERROR_ON(num_slices > input->dimension(wrap_axis(axis, input)));
     ARM_COMPUTE_RETURN_ERROR_ON(num_slices > output_vector.size());
     Coordinates slice_start;
     int32_t     slice_end_mask;
     for(size_t k = 0; k < num_slices; ++k)
     {
         slice_start.set(wrap_axis(axis, input), k);
         setup_slice_coordinates_and_mask(slice_start, slice_end_mask, input->tensor_shape().num_dimensions());
         ARM_COMPUTE_RETURN_ON_ERROR(NEStridedSlice::validate(input, output_vector[k], slice_start, Coordinates(), BiStrides(), 0, slice_end_mask, (1 << wrap_axis(axis, input))));
     }
     return Status{};
 }
The documentation for this class was generated from the following files:
arm_compute/runtime/NEON/functions/NEUnstack.h
src/runtime/NEON/functions/NEUnstack.cpp