Compute Library: GemmInterleavedPretransposed2d< strategy, To, Tr > Class Template Reference
GemmInterleavedPretransposed2d< strategy, To, Tr > Class Template Reference
#include <gemm_interleaved_pretransposed_2d.hpp>
Public Member Functions
GemmInterleavedPretransposed2d (GemmInterleavedPretransposed2d &)=delete
GemmInterleavedPretransposed2d & operator= (GemmInterleavedPretransposed2d &)=delete
GemmInterleavedPretransposed2d (const GemmArgs &args)
ndrange_t get_window_size () const override
bool supports_dynamic_scheduling () const override
void set_nthreads (int nthreads) override
void execute (const ndcoord_t &work_range, const ndcoord_t &thread_locator, int threadid) override
Main execute member fucntion.
std::size_t get_working_size () const override
void set_working_space (void *working_space) override
bool B_is_pretransposed () const override
bool B_pretranspose_required () const override
size_t get_B_pretransposed_array_size () const override
void pretranspose_B_array (void *in_buffer, const To *B, const int ldb, const int B_multi_stride) override
void set_pretransposed_B_data (void *in_buffer) override
Public Member Functions inherited from GemmCommon< To, Tr >
virtual void set_arrays (const To *A, const int lda, const int A_batch_stride, const int A_multi_stride, const To *B, const int ldb, const int B_multi_stride, Tr *C, const int ldc, const int C_batch_stride, const int C_multi_stride, const Tr *bias, const int bias_multi_stride)
void set_arrays_generic (const void *A, const int lda, const int A_batch_stride, const int A_multi_stride, const void *B, const int ldb, const int B_multi_stride, void *C, const int ldc, const int C_batch_stride, const int C_multi_stride, const void *bias, const int bias_multi_stride) override
virtual void requantize_bias (void *, const To *, const int, const int)
void pretranspose_B_array_generic (void *out, const void *in, const int row_stride, const int multi_stride) override
virtual void set_indirect_parameters (size_t, const To *const *const *)
void set_indirect_parameters_generic (size_t sz, const void *const *const *ptr) override
Public Member Functions inherited from IGemmCommon
virtual void set_quantized_bias (const int32_t *, size_t)
virtual void set_convolution_parameters (ConvolutionParameters)
virtual GemmConfig get_config ()=0
virtual ~IGemmCommon ()
Static Public Member Functions
static uint64_t estimate_cycles (const GemmArgs &args, const PerformanceParameters &params)
Detailed Description
template<typename strategy, typename To, typename Tr>
class arm_gemm::GemmInterleavedPretransposed2d< strategy, To, Tr >
Definition at line 52 of file gemm_interleaved_pretransposed_2d.hpp.
Constructor & Destructor Documentation
GemmInterleavedPretransposed2d() [1/2]
GemmInterleavedPretransposed2d (GemmInterleavedPretransposed2d< strategy, To, Tr > &) delete
GemmInterleavedPretransposed2d() [2/2]
GemmInterleavedPretransposed2d (const GemmArgs & args) inline
Definition at line 341 of file gemm_interleaved_pretransposed_2d.hpp.
References GemmArgs::_cfg, CPUInfo::get_L2_cache_size(), arm_gemm::iceildiv(), and GemmConfig::outer_block_size.
     :    _ci(args._ci)
     ,    _Msize(args._Msize)
     ,    _Nsize(args._Nsize)
     ,    _Ksize(args._Ksize)
     ,    _nbatches(args._nbatches)
     ,    _nmulti(args._nmulti)
     ,    _act(args._act)
     ,    _maxthreads(args._maxthreads)
     ,    _nthreads(args._maxthreads)
     ,    _k_block(get_k_block_size(args))
     // Work out the rounded size of M - needed for some buffers.
     ,    _Mround_div ( iceildiv(_Msize, strategy::out_height()) )
     ,    _Mround     ( _Mround_div * strategy::out_height()     )
     ,    _Nround_div ( iceildiv(_Nsize, strategy::out_width()) )
     ,    _Nround     ( _Nround_div * strategy::out_width()     )
     {
         assert(_maxthreads > 0);
         const unsigned int L2_size = _ci->get_L2_cache_size();
         if (args._cfg && args._cfg->outer_block_size) {
             _x_block = args._cfg->outer_block_size;
         } else {
             // x_block: Work out how many rows (of length k_block) will fit in the L2
             // Don't allocate more than 90% of the L2 to allow for overheads, and subtract off the L1 contents.
             _x_block = (((L2_size * 9) / 10) - (_k_block * sizeof(Toi) * (strategy::out_width() + strategy::out_height()))) /
                       (sizeof(Toi) * _k_block);
             // Needs to be (at least a single) multiple of the kernel output width.
             _x_block /= strategy::out_width();
             _x_block = std::max(_x_block, 1U) * strategy::out_width();
             // And tune to the presented problem size.
             unsigned int num_x_blocks = iceildiv(_Nsize, _x_block);
             _x_block = iceildiv(_Nsize, num_x_blocks);
             _x_block = iceildiv(_x_block, strategy::out_width());
             _x_block *= strategy::out_width();
         }
     }
Member Function Documentation
B_is_pretransposed()
bool B_is_pretransposed () const inline override virtual
Reimplemented from IGemmCommon.
Definition at line 450 of file gemm_interleaved_pretransposed_2d.hpp.
{
         return true;
     }
B_pretranspose_required()
bool B_pretranspose_required () const inline override virtual
Reimplemented from IGemmCommon.
Definition at line 454 of file gemm_interleaved_pretransposed_2d.hpp.
{
         return _B_transposed==nullptr;
     }
estimate_cycles()
static uint64_t estimate_cycles (const GemmArgs & args, const PerformanceParameters & params) inline static
Definition at line 511 of file gemm_interleaved_pretransposed_2d.hpp.
References GemmArgs::_Ksize, GemmArgs::_maxthreads, GemmArgs::_Msize, GemmArgs::_nbatches, GemmArgs::_nmulti, GemmArgs::_Nsize, arm_gemm::iceildiv(), PerformanceParameters::kernel_macs_cycle, PerformanceParameters::merge_bytes_cycle, PerformanceParameters::prepare_bytes_cycle, and arm_gemm::roundup().
{
         unsigned int k_blocks = iceildiv(args._Ksize, get_k_block_size(args));
         unsigned int m_blocks = iceildiv(args._Msize, strategy::out_height()) * args._nbatches;
         unsigned int n_blocks = iceildiv(args._Nsize, strategy::out_width());
         uint64_t total_macs    = static_cast<uint64_t>(args._nbatches) * args._nmulti * roundup(args._Msize, strategy::out_height()) * roundup(args._Nsize, strategy::out_width()) * roundup(args._Ksize, strategy::k_unroll());
         uint64_t prepare_bytes = static_cast<uint64_t>(args._nbatches) * args._nmulti * roundup(args._Msize, strategy::out_height()) * roundup(args._Ksize, strategy::k_unroll()) * sizeof(Toi);
         uint64_t merge_bytes   = static_cast<uint64_t>(args._nbatches) * args._nmulti * k_blocks * roundup(args._Msize, strategy::out_height()) * roundup(args._Nsize, strategy::out_width()) * sizeof(Tr);
         // Wide problems incur extra preparation cost, as it is done per thread.
         // Duplicate the logic the scheduler will later use to figure out how much that will affect us
         float ratio = m_blocks / static_cast<float>(n_blocks);
         unsigned int ideal_height = static_cast<unsigned int>(std::sqrt(args._maxthreads * ratio) + 0.5);
         unsigned int height = 1;
         if (ideal_height == 0) {
             height = 1;
         } else {
             for (unsigned int adj=0; adj<ideal_height; adj++) {
                 const unsigned int round_down = ideal_height - adj;
                 if (args._maxthreads % round_down == 0) {
                     height = round_down;
                     break;
                 }
                 const unsigned int round_up = ideal_height + adj;
                 if (args._maxthreads % round_up == 0) {
                     height = round_up;
                     break;
                 }
             }
         }
         // We've computed the height here - we need to multiply the amount of preparation effort by the width (which is total threads / height)
         prepare_bytes *= (args._maxthreads / height);
         float mac_cycles     = static_cast<float>(total_macs) / params.kernel_macs_cycle;
         float prepare_cycles = static_cast<float>(prepare_bytes) / params.prepare_bytes_cycle;
         float merge_cycles   = static_cast<float>(merge_bytes) / params.merge_bytes_cycle;
         float total_cycles = mac_cycles + prepare_cycles + merge_cycles;
         // We can't thread over multis, which might be a problem in some
         // threaded cases.  Penalize that here.
         float parallelism_available = static_cast<float>(iceildiv(args._Msize, strategy::out_height()) * args._nbatches * iceildiv(args._Nsize, strategy::out_width())) * 0.9;
         if (parallelism_available < args._maxthreads) {
             total_cycles *= (static_cast<float>(args._maxthreads) / parallelism_available);
         }
         return static_cast<uint64_t>(total_cycles);
     }
execute()
void execute (const ndcoord_t & work_range, const ndcoord_t & thread_locator, int threadid) inline override virtual
Main execute member fucntion.
Parameters
[in] work_range specifies the range of work we want to be computed, total range defined by get_window_size()
[in] thread_locator where are we inside of the thread space
[in] threadid a unique threadid
Implements IGemmCommon.
Definition at line 401 of file gemm_interleaved_pretransposed_2d.hpp.
References NDCoordinate< N >::get_position(), and NDRange< D >::get_size().
{
         /* This particular GEMM implementation can only be broken up over the M & N
          * dimensions, we inform the frame work of this limitation via the get_window_size function
          */
         const auto m_start = work_range.get_position(0);
         const auto n_start = work_range.get_position(1);
         const auto m_size  = work_range.get_size(0);
         const auto n_size  = work_range.get_size(1);
         const auto m_end   = m_start + m_size;
         const auto n_end   = n_start + n_size;
         const auto m_threadid = thread_locator.get_position(0);
         const auto n_threadid = thread_locator.get_position(1);
         execute_pretranspose(m_start, m_end, n_start, n_end, threadid, m_threadid, n_threadid);
     }
get_B_pretransposed_array_size()
size_t get_B_pretransposed_array_size () const inline override virtual
Reimplemented from IGemmCommon.
Definition at line 459 of file gemm_interleaved_pretransposed_2d.hpp.
References arm_gemm::iceildiv().
{
         size_t total=0;
         blockwalker current(*this);
         do {
             /* Figure out the size of each block. */
             unsigned int x_size = (current.xmax() - current.x0());
             unsigned int k_size = (current.kmax() - current.k0());
             /* Round sizes up as needed. */
             x_size = iceildiv(x_size, strategy::out_width());
             x_size *= strategy::out_width();
             k_size = iceildiv(k_size, strategy::k_unroll());
             k_size *= strategy::k_unroll();
             total += x_size * k_size * sizeof(Toi);
         } while (current.advance());
         return total;
     }
get_window_size()
ndrange_t get_window_size () const inline override virtual
Returns
an ndrange containing ranges of the compute space which can be broken up and parallelised over
Implements IGemmCommon.
Definition at line 385 of file gemm_interleaved_pretransposed_2d.hpp.
References arm_compute::test::validation::m, and arm_compute::test::validation::n.
{
         unsigned m = (_Mround / strategy::out_height()) * _nbatches;
         unsigned n = _Nround_div;
         return { m, n };
     }
get_working_size()
std::size_t get_working_size (void) const inline override virtual
Reimplemented from IGemmCommon.
Definition at line 418 of file gemm_interleaved_pretransposed_2d.hpp.
{
         /* Because we do not know how schedular will break up
          * the task, we need to ensure that alloc enough
          * space to be able to handle the case where every thread
          * is parallelised across B AND also every thrread is parallelised across A
          *
          * If we parallelise across A, then we only need one buffer of A and 64 buffers of B
          * If we parallelise across B, then we only need 64 buffer of B and
          */
         return get_c_working_size() * _maxthreads
              + get_a_working_size() * _maxthreads
              + 64; //to account for cacheline alignment
     }
operator=()
GemmInterleavedPretransposed2d& operator= (GemmInterleavedPretransposed2d< strategy, To, Tr > &) delete
pretranspose_B_array()
void pretranspose_B_array (void * in_buffer, const To * B, const int ldb, const int B_multi_stride) inline override virtual
Reimplemented from GemmCommon< To, Tr >.
Definition at line 481 of file gemm_interleaved_pretransposed_2d.hpp.
References arm_gemm::iceildiv(), and strategy.
{
         blockwalker current(*this);
         Toi *buffer = reinterpret_cast<Toi *>(in_buffer);
         _B_transposed = buffer;
         strategy strat(_ci);
         do {
             /* Figure out the size of each block. */
             unsigned int x_size = (current.xmax() - current.x0());
             unsigned int k_size = (current.kmax() - current.k0());
             /* Round sizes up as needed. */
             x_size = iceildiv(x_size, strategy::out_width());
             x_size *= strategy::out_width();
             k_size = iceildiv(k_size, strategy::k_unroll());
             k_size *= strategy::k_unroll();
             strat.transforms.PrepareB(buffer, B + (current.multi() * B_multi_stride), ldb,
                                       current.x0(), current.xmax(), current.k0(), current.kmax());
             buffer += (x_size * k_size);
         } while (current.advance());
     }
set_nthreads()
void set_nthreads (int nthreads) inline override virtual
Reimplemented from IGemmCommon.
Definition at line 397 of file gemm_interleaved_pretransposed_2d.hpp.
{
         _nthreads = std::min(nthreads, _maxthreads);
     }
set_pretransposed_B_data()
void set_pretransposed_B_data (void * in_buffer) inline override virtual
Reimplemented from IGemmCommon.
Definition at line 506 of file gemm_interleaved_pretransposed_2d.hpp.
{
         _B_transposed = reinterpret_cast<Toi *>(in_buffer);
     }
set_working_space()
void set_working_space (void * working_space) inline override virtual
Reimplemented from IGemmCommon.
Definition at line 433 of file gemm_interleaved_pretransposed_2d.hpp.
{
         // Make sure everything ends up cache line aligned
         int8_t *working_space_bytes = reinterpret_cast<int8_t *>(working_space);
         intptr_t working_space_int  = reinterpret_cast<intptr_t>(working_space);
         size_t diff=0;
         if (working_space_int & 0x3F) {
             diff = 0x40 - (working_space_int & 0x3F);
         }
         working_space_bytes += diff;
         _working_space = reinterpret_cast<void *>(working_space_bytes);
     }
supports_dynamic_scheduling()
bool supports_dynamic_scheduling () const inline override virtual
Reimplemented from IGemmCommon.
Definition at line 392 of file gemm_interleaved_pretransposed_2d.hpp.
{
         return true;
     }
The documentation for this class was generated from the following file:
src/core/NEON/kernels/arm_gemm/gemm_interleaved_pretransposed_2d.hpp