Compute Library: CLRNNLayer Class Reference
CLRNNLayer Class Reference
Basic function to run CLRNNLayer.
#include <CLRNNLayer.h>
Public Member Functions
CLRNNLayer (std::shared_ptr< IMemoryManager > memory_manager=nullptr)
Default constructor.
CLRNNLayer (const CLRNNLayer &)=delete
Prevent instances of this class from being copied.
CLRNNLayer & operator= (const CLRNNLayer &)=delete
Prevent instances of this class from being copied.
~CLRNNLayer ()
Default destructor.
void configure (const ICLTensor *input, const ICLTensor *weights, const ICLTensor *recurrent_weights, const ICLTensor *bias, ICLTensor *hidden_state, ICLTensor *output, ActivationLayerInfo &info)
Initialize the function.
void configure (const CLCompileContext &compile_context, const ICLTensor *input, const ICLTensor *weights, const ICLTensor *recurrent_weights, const ICLTensor *bias, ICLTensor *hidden_state, ICLTensor *output, ActivationLayerInfo &info)
Initialize the function.
void run () override
Run the kernels contained in the function.
void prepare () override
Prepare the function for executing.
Public Member Functions inherited from IFunction
virtual ~IFunction ()=default
Destructor.
Static Public Member Functions
static Status validate (const ITensorInfo *input, const ITensorInfo *weights, const ITensorInfo *recurrent_weights, const ITensorInfo *bias, const ITensorInfo *hidden_state, const ITensorInfo *output, const ActivationLayerInfo &info)
Initialize the function.
Detailed Description
Basic function to run CLRNNLayer.
Definition at line 41 of file CLRNNLayer.h.
Constructor & Destructor Documentation
CLRNNLayer() [1/2]
CLRNNLayer (std::shared_ptr< IMemoryManager > memory_manager = nullptr)
Default constructor.
Definition at line 39 of file CLRNNLayer.cpp.
     : _memory_group(std::move(memory_manager)), _gemm_state_f(), _add_kernel(), _activation(), _fully_connected_kernel(), _copy(), _fully_connected_out(), _gemm_output(), _add_output(),
       _is_prepared(false)
 {
 }
CLRNNLayer() [2/2]
CLRNNLayer (const CLRNNLayer &) delete
Prevent instances of this class from being copied.
~CLRNNLayer()
~CLRNNLayer () default
Default destructor.
Member Function Documentation
configure() [1/2]
void configure (const ICLTensor * input, const ICLTensor * weights, const ICLTensor * recurrent_weights, const ICLTensor * bias, ICLTensor * hidden_state, ICLTensor * output, ActivationLayerInfo & info)
Initialize the function.
Valid data layouts:
NHWC
NCHW
Valid data type configurations:
src0 src1 src2 src3 dst0 dst1
F16 F16 F16 F16 F16 F16
F32 F32 F32 F32 F32 F32
Parameters
[in] input Input is a 2-D tensor of shape [input_size, batch_size]. Data types supported: F16/F32
[in] weights Weights tensor of shape [input_size, num_units] that multiplies the input. Data types supported: Same as input
[in] recurrent_weights Weights tensor of shape [num_units, num_units] that multiplies the current 'state'. Data types supported: Same as input
[in] bias Bias vector of shape [num_units]. Data types supported: Same as input
[out] output Output tensor of shape [num_units, batch_size]. Data types supported: Same as input
[in,out] hidden_state Output tensor of shape [num_units, batch_size]. Data types supported: Same as input
[in] info Activation layer parameter.
Definition at line 76 of file CLRNNLayer.cpp.
References CLKernelLibrary::get().
 {
     configure(CLKernelLibrary::get().get_compile_context(), input, weights, recurrent_weights, bias, hidden_state, output, info);
 }
configure() [2/2]
void configure (const CLCompileContext & compile_context, const ICLTensor * input, const ICLTensor * weights, const ICLTensor * recurrent_weights, const ICLTensor * bias, ICLTensor * hidden_state, ICLTensor * output, ActivationLayerInfo & info)
Initialize the function.
Parameters
[in] compile_context The compile context to be used.
[in] input Input is a 2-D tensor of shape [input_size, batch_size]. Data types supported: F16/F32
[in] weights Weights tensor of shape [input_size, num_units] that multiplies the input. Data types supported: Same as input
[in] recurrent_weights Weights tensor of shape [num_units, num_units] that multiplies the current 'state'. Data types supported: Same as input
[in] bias Bias vector of shape [num_units]. Data types supported: Same as input
[out] output Output tensor of shape [num_units, batch_size]. Data types supported: Same as input
[in,out] hidden_state Output tensor of shape [num_units, batch_size]. Data types supported: Same as input
[in] info Activation layer parameter.
Definition at line 82 of file CLRNNLayer.cpp.
References CLTensorAllocator::allocate(), CLTensor::allocator(), ARM_COMPUTE_ERROR_ON_NULLPTR, ARM_COMPUTE_ERROR_THROW_ON, ARM_COMPUTE_LOG_PARAMS, arm_compute::misc::shape_calculator::compute_rnn_shape(), CLCopy::configure(), CLActivationLayer::configure(), CLArithmeticAddition::configure(), CLFullyConnectedLayer::configure(), CLGEMM::configure(), ITensorInfo::data_layout(), ITensorInfo::data_type(), ITensorInfo::dimension(), arm_compute::get_data_layout_dimension_index(), arm_compute::HEIGHT, arm_compute::test::validation::idx_height, ITensor::info(), arm_compute::test::validation::info, ITensorAllocator::init(), MemoryGroup::manage(), arm_compute::SATURATE, arm_compute::test::validation::shape, and CLRNNLayer::validate().
 {
     ARM_COMPUTE_ERROR_ON_NULLPTR(input, weights, recurrent_weights, bias, hidden_state, output);
     ARM_COMPUTE_ERROR_THROW_ON(CLRNNLayer::validate(input->info(), weights->info(), recurrent_weights->info(), bias->info(), hidden_state->info(), output->info(), info));
     ARM_COMPUTE_LOG_PARAMS(input, weights, recurrent_weights, bias, hidden_state, output, info);
     const int   idx_height = get_data_layout_dimension_index(input->info()->data_layout(), DataLayoutDimension::HEIGHT);
     TensorShape shape      = compute_rnn_shape(recurrent_weights->info(), hidden_state->info()->dimension(idx_height));
     _is_prepared = false;
     _fully_connected_out.allocator()->init(TensorInfo(shape, 1, input->info()->data_type()));
     _gemm_output.allocator()->init(TensorInfo(shape, 1, input->info()->data_type()));
     // Manage intermediate buffers and configure
     _memory_group.manage(&_fully_connected_out);
     _fully_connected_kernel.configure(compile_context, input, weights, bias, &_fully_connected_out);
     _memory_group.manage(&_gemm_output);
     _gemm_state_f.configure(compile_context, hidden_state, recurrent_weights, nullptr, &_gemm_output, 1.f, 0.f);
     _add_output.allocator()->init(TensorInfo(shape, 1, input->info()->data_type()));
     _memory_group.manage(&_add_output);
     _add_kernel.configure(compile_context, &_fully_connected_out, &_gemm_output, &_add_output, ConvertPolicy::SATURATE);
     _fully_connected_out.allocator()->allocate();
     _gemm_output.allocator()->allocate();
     _activation.configure(compile_context, &_add_output, hidden_state, info);
     _add_output.allocator()->allocate();
     _copy.configure(compile_context, hidden_state, output);
 }
operator=()
CLRNNLayer& operator= (const CLRNNLayer &) delete
Prevent instances of this class from being copied.
prepare()
void prepare () override virtual
Prepare the function for executing.
Any one off pre-processing step required by the function is handled here
Note
Prepare stage might not need all the function's buffers' backing memory to be available in order to execute
Reimplemented from IFunction.
Definition at line 134 of file CLRNNLayer.cpp.
References CLFullyConnectedLayer::prepare(), and CLGEMM::prepare().
Referenced by CLRNNLayer::run().
 {
     if(!_is_prepared)
     {
         _fully_connected_kernel.prepare();
         _gemm_state_f.prepare();
         _is_prepared = true;
     }
 }
run()
void run () override virtual
Run the kernels contained in the function.
For CPU kernels:
Multi-threading is used for the kernels which are parallelisable.
By default std::thread::hardware_concurrency() threads are used.
Note
CPPScheduler::set_num_threads() can be used to manually set the number of threads
For OpenCL kernels:
All the kernels are enqueued on the queue associated with CLScheduler.
The queue is then flushed.
Note
The function will not block until the kernels are executed. It is the user's responsibility to wait.
Will call prepare() on first run if hasn't been done
Implements IFunction.
Definition at line 119 of file CLRNNLayer.cpp.
References CLRNNLayer::prepare(), CLCopy::run(), CLFullyConnectedLayer::run(), CLActivationLayer::run(), CLGEMM::run(), and CLArithmeticAddition::run().
 {
     prepare();
     MemoryGroupResourceScope scope_mg(_memory_group);
     _fully_connected_kernel.run();
     _gemm_state_f.run();
     _add_kernel.run();
     _activation.run();
     // copy hidden out to output
     _copy.run();
 }
validate()
Status validate (const ITensorInfo * input, const ITensorInfo * weights, const ITensorInfo * recurrent_weights, const ITensorInfo * bias, const ITensorInfo * hidden_state, const ITensorInfo * output, const ActivationLayerInfo & info) static
Initialize the function.
Parameters
[in] input Input is a 2-D tensor of shape [input_size, batch_size]. Data types supported: F16/F32
[in] weights Weights tensor of shape [input_size, num_units] that multiplies the input. Data types supported: Same as input
[in] recurrent_weights Weights tensor of shape [num_units, num_units] that multiplies the current 'state'. Data types supported: Same as input
[in] bias Bias vector of shape [num_units]. Data types supported: Same as input
[in] output Output tensor of shape [num_units, batch_size]. Data types supported: Same as input
[in] hidden_state Output tensor of shape [num_units, batch_size]. Data types supported: Same as input
[in] info Activation layer parameter.
Returns
a status
Definition at line 47 of file CLRNNLayer.cpp.
References ARM_COMPUTE_RETURN_ERROR_ON, ARM_COMPUTE_RETURN_ERROR_ON_DATA_TYPE_NOT_IN, ARM_COMPUTE_RETURN_ERROR_ON_MISMATCHING_DATA_TYPES, ARM_COMPUTE_RETURN_ERROR_ON_MISMATCHING_DIMENSIONS, ARM_COMPUTE_RETURN_ERROR_ON_NULLPTR, ARM_COMPUTE_RETURN_ON_ERROR, arm_compute::misc::shape_calculator::compute_rnn_shape(), ITensorInfo::data_layout(), ITensorInfo::data_type(), ITensorInfo::dimension(), arm_compute::F16, arm_compute::F32, arm_compute::get_data_layout_dimension_index(), arm_compute::HEIGHT, arm_compute::test::validation::idx_height, arm_compute::test::validation::idx_width, ITensorInfo::num_dimensions(), arm_compute::SATURATE, ITensorInfo::tensor_shape(), CLFullyConnectedLayer::validate(), CLActivationLayer::validate(), CLGEMM::validate(), CLArithmeticAddition::validate(), and arm_compute::WIDTH.
Referenced by CLRNNLayer::configure(), and arm_compute::test::validation::DATA_TEST_CASE().
 {
     ARM_COMPUTE_RETURN_ERROR_ON_NULLPTR(input, weights, recurrent_weights, bias, hidden_state, output);
     ARM_COMPUTE_RETURN_ERROR_ON_DATA_TYPE_NOT_IN(input, DataType::F16, DataType::F32);
     ARM_COMPUTE_RETURN_ERROR_ON_MISMATCHING_DATA_TYPES(input, weights, recurrent_weights, bias, hidden_state, output);
     const int idx_width  = get_data_layout_dimension_index(input->data_layout(), DataLayoutDimension::WIDTH);
     const int idx_height = get_data_layout_dimension_index(input->data_layout(), DataLayoutDimension::HEIGHT);
     ARM_COMPUTE_RETURN_ERROR_ON(input->dimension(idx_width) != weights->dimension(idx_width));
     ARM_COMPUTE_RETURN_ERROR_ON(weights->dimension(idx_height) != recurrent_weights->dimension(idx_width));
     ARM_COMPUTE_RETURN_ERROR_ON(recurrent_weights->dimension(idx_width) != recurrent_weights->dimension(1));
     ARM_COMPUTE_RETURN_ERROR_ON(bias->num_dimensions() != 1);
     ARM_COMPUTE_RETURN_ERROR_ON(bias->dimension(idx_width) != weights->dimension(idx_height));
     ARM_COMPUTE_RETURN_ERROR_ON(hidden_state->dimension(idx_width) != weights->dimension(idx_height));
     ARM_COMPUTE_RETURN_ERROR_ON(hidden_state->dimension(idx_height) != input->dimension(idx_height));
     ARM_COMPUTE_RETURN_ERROR_ON_MISMATCHING_DIMENSIONS(output->tensor_shape(), hidden_state->tensor_shape());
     auto shape_info = TensorInfo(compute_rnn_shape(recurrent_weights, hidden_state->dimension(idx_height)), 1, input->data_type());
     ARM_COMPUTE_RETURN_ON_ERROR(CLFullyConnectedLayer::validate(input, weights, bias, &shape_info));
     ARM_COMPUTE_RETURN_ON_ERROR(CLGEMM::validate(hidden_state, recurrent_weights, nullptr, &shape_info, 1.f, 0.f));
     ARM_COMPUTE_RETURN_ON_ERROR(CLArithmeticAddition::validate(&shape_info, &shape_info, &shape_info, ConvertPolicy::SATURATE));
     ARM_COMPUTE_RETURN_ON_ERROR(CLActivationLayer::validate(&shape_info, &shape_info, info));
     return Status{};
 }
The documentation for this class was generated from the following files:
arm_compute/runtime/CL/functions/CLRNNLayer.h
src/runtime/CL/functions/CLRNNLayer.cpp