Compute Library: ClContext Class Reference
ClContext Class Reference final
OpenCL context implementation class.
#include <ClContext.h>
Public Member Functions
ClContext (const AclContextOptions *options)
Default Constructor.
const mlgo::MLGOHeuristics & mlgo () const
Extract MLGO heuristics.
::cl::Context cl_ctx ()
Underlying cl context accessor.
::cl::Device cl_dev ()
Underlying cl device accessor.
bool set_cl_ctx (::cl::Context ctx)
Update/inject an underlying cl context object.
ITensorV2 * create_tensor (const AclTensorDescriptor &desc, bool allocate) override
Create a tensor object.
IQueue * create_queue (const AclQueueOptions *options) override
Create a queue object.
std::tuple< IOperator *, StatusCode > create_activation (const AclTensorDescriptor &src, const AclTensorDescriptor &dst, const AclActivationDescriptor &act, bool is_validate) override
Public Member Functions inherited from IContext
IContext (Target target)
virtual ~IContext ()
Virtual Destructor.
Target type () const
Target type accessor.
void inc_ref () const
Increment context refcount.
void dec_ref () const
Decrement context refcount.
int refcount () const
Reference counter accessor.
bool is_valid () const
Checks if an object is valid.
Additional Inherited Members
Data Fields inherited from AclContext_
arm_compute::detail::Header header { arm_compute::detail::ObjectType::Context, nullptr }
Detailed Description
OpenCL context implementation class.
Definition at line 39 of file ClContext.h.
Constructor & Destructor Documentation
ClContext()
ClContext (const AclContextOptions * options) explicit
Default Constructor.
Parameters
[in] options Creational options
Definition at line 52 of file ClContext.cpp.
References CLKernelLibrary::context(), CLKernelLibrary::get(), CLKernelLibrary::get_device(), and AclContextOptions::kernel_config_file.
     : IContext(Target::GpuOcl),
       _mlgo_heuristics(),
       _cl_ctx(),
       _cl_dev()
 {
     if(options != nullptr)
     {
         _mlgo_heuristics = populate_mlgo(options->kernel_config_file);
     }
     _cl_ctx = CLKernelLibrary::get().context();
     _cl_dev = CLKernelLibrary::get().get_device();
 }
Member Function Documentation
cl_ctx()
cl::Context cl_ctx ()
Underlying cl context accessor.
Returns
the cl context used
Definition at line 71 of file ClContext.cpp.
 {
     return _cl_ctx;
 }
cl_dev()
cl::Device cl_dev ()
Underlying cl device accessor.
Returns
the cl device used
Definition at line 76 of file ClContext.cpp.
 {
     return _cl_dev;
 }
create_activation()
std::tuple< IOperator *, StatusCode > create_activation (const AclTensorDescriptor & src, const AclTensorDescriptor & dst, const AclActivationDescriptor & act, bool is_validate) override virtual
Implements IContext.
Definition at line 56 of file ClActivation.cpp.
References ARM_COMPUTE_LOG_ERROR_ACL, arm_compute::detail::convert_to_activation_info(), arm_compute::detail::convert_to_legacy_tensor_info(), CLKernelLibrary::get(), arm_compute::test::validation::info, arm_compute::OutOfMemory, TensorInfo::set_is_resizable(), arm_compute::test::validation::src_info, arm_compute::Success, arm_compute::UnsupportedConfig, and ClActivation::validate().
 {
     TensorInfo src_info = detail::convert_to_legacy_tensor_info(src);
     TensorInfo dst_info = detail::convert_to_legacy_tensor_info(dst);
     auto       info     = detail::convert_to_activation_info(act);
     if(is_validate && !bool(arm_compute::opencl::ClActivation::validate(&src_info.set_is_resizable(false), &dst_info.set_is_resizable(false), info)))
     {
         return std::make_tuple(nullptr, StatusCode::UnsupportedConfig);
     }
     auto act_op = std::make_unique<arm_compute::opencl::ClActivation>();
     act_op->configure(CLKernelLibrary::get().get_compile_context(), &src_info, &dst_info, info);
     auto op = new arm_compute::IOperator(static_cast<IContext *>(this));
     if(op == nullptr)
     {
         ARM_COMPUTE_LOG_ERROR_ACL("Couldn't allocate internal resources");
         return std::make_tuple(nullptr, StatusCode::OutOfMemory);
     }
     op->set_internal_operator(std::move(act_op));
     return std::make_tuple(op, StatusCode::Success);
 }
create_queue()
IQueue * create_queue (const AclQueueOptions * options) override virtual
Create a queue object.
Parameters
[in] options Queue options to be used
Returns
A pointer to the created queue object
Implements IContext.
Definition at line 102 of file ClContext.cpp.
 {
     return new ClQueue(this, options);
 }
create_tensor()
ITensorV2 * create_tensor (const AclTensorDescriptor & desc, bool allocate) override virtual
Create a tensor object.
Parameters
[in] desc Descriptor to use
[in] allocate Flag to allocate tensor
Returns
A pointer to the created tensor object
Implements IContext.
Definition at line 92 of file ClContext.cpp.
References ClTensor::allocate(), and tensor.
 {
     ClTensor *tensor = new ClTensor(this, desc);
     if(tensor != nullptr && allocate)
     {
         tensor->allocate();
     }
     return tensor;
 }
mlgo()
const mlgo::MLGOHeuristics & mlgo () const
Extract MLGO heuristics.
Returns
Heuristics tree
Definition at line 66 of file ClContext.cpp.
Referenced by arm_compute::test::validation::TEST_CASE().
 {
     return _mlgo_heuristics;
 }
set_cl_ctx()
bool set_cl_ctx (::cl::Context ctx)
Update/inject an underlying cl context object.
Warning
Context will be able to set if the object doesn't have any pending reference to other objects
Parameters
[in] ctx Underlying cl context to be used
Returns
true if the context was set successfully else falseS
Definition at line 81 of file ClContext.cpp.
References CLScheduler::get(), IContext::refcount(), and CLScheduler::set_context().
 {
     if(this->refcount() == 0)
     {
         _cl_ctx = ctx;
         CLScheduler::get().set_context(ctx);
         return true;
     }
     return false;
 }
The documentation for this class was generated from the following files:
src/gpu/cl/ClContext.h
src/gpu/cl/ClContext.cpp
src/gpu/cl/operators/ClActivation.cpp