Compute Library: CLSelect Class Reference
CLSelect Class Reference
Basic function to run CLSelect.
#include <CLSelect.h>
Public Member Functions
void configure (const ICLTensor *c, const ICLTensor *x, const ICLTensor *y, ICLTensor *output)
Initialise the kernel's inputs and output.
void configure (const CLCompileContext &compile_context, const ICLTensor *c, const ICLTensor *x, const ICLTensor *y, ICLTensor *output)
Initialise the kernel's inputs and output.
Public Member Functions inherited from ICLSimpleFunction
ICLSimpleFunction (CLRuntimeContext *ctx=nullptr)
Constructor.
ICLSimpleFunction (const ICLSimpleFunction &)=delete
Prevent instances of this class from being copied (As this class contains pointers)
ICLSimpleFunction (ICLSimpleFunction &&)=default
Default move constructor.
ICLSimpleFunction & operator= (const ICLSimpleFunction &)=delete
Prevent instances of this class from being copied (As this class contains pointers)
ICLSimpleFunction & operator= (ICLSimpleFunction &&)=default
Default move assignment operator.
~ICLSimpleFunction ()
Default destructor.
void run () override final
Run the kernels contained in the function.
Public Member Functions inherited from IFunction
virtual ~IFunction ()=default
Destructor.
virtual void prepare ()
Prepare the function for executing.
Static Public Member Functions
static Status validate (const ITensorInfo *c, const ITensorInfo *x, const ITensorInfo *y, const ITensorInfo *output)
Static function to check if given info will lead to a valid configuration of CLSelect.
Detailed Description
Basic function to run CLSelect.
Definition at line 38 of file CLSelect.h.
Member Function Documentation
configure() [1/2]
void configure (const ICLTensor * c, const ICLTensor * x, const ICLTensor * y, ICLTensor * output)
Initialise the kernel's inputs and output.
Valid data layouts:
All
Valid data type configurations:
src0 src1 src2 dst
U8 All All All
Parameters
[in] c Condition input tensor. Data types supported: U8.
[in] x First input tensor. Data types supported: All.
[in] y Second input tensor. Data types supported: Same as x
[out] output Output tensor. Data types supported: Same as x.
Definition at line 36 of file CLSelect.cpp.
References CLKernelLibrary::get().
 {
     configure(CLKernelLibrary::get().get_compile_context(), c, x, y, output);
 }
configure() [2/2]
void configure (const CLCompileContext & compile_context, const ICLTensor * c, const ICLTensor * x, const ICLTensor * y, ICLTensor * output)
Initialise the kernel's inputs and output.
Parameters
[in] compile_context The compile context to be used.
[in] c Condition input tensor. Data types supported: U8.
[in] x First input tensor. Data types supported: All.
[in] y Second input tensor. Data types supported: Same as x
[out] output Output tensor. Data types supported: Same as x.
Definition at line 41 of file CLSelect.cpp.
References ARM_COMPUTE_LOG_PARAMS, and arm_compute::test::validation::k.
 {
     ARM_COMPUTE_LOG_PARAMS(c, x, y, output);
     auto k = std::make_unique<CLSelectKernel>();
     k->configure(compile_context, c, x, y, output);
     _kernel = std::move(k);
 }
validate()
Status validate (const ITensorInfo * c, const ITensorInfo * x, const ITensorInfo * y, const ITensorInfo * output) static
Static function to check if given info will lead to a valid configuration of CLSelect.
Parameters
[in] c Condition input tensor. Data types supported: U8.
[in] x First input tensor. Data types supported: All.
[in] y Second input tensor. Data types supported: Same as x
[in] output Output tensor. Data types supported: Same as x.
Returns
a status
Definition at line 49 of file CLSelect.cpp.
References CLSelectKernel::validate().
Referenced by arm_compute::test::validation::DATA_TEST_CASE().
 {
     return CLSelectKernel::validate(c, x, y, output);
 }
The documentation for this class was generated from the following files:
arm_compute/runtime/CL/functions/CLSelect.h
src/runtime/CL/functions/CLSelect.cpp