Compute Library: NodeFusionMutator Class Reference
NodeFusionMutator Class Reference final
Mutation pass to fuss nodes.
#include <NodeFusionMutator.h>
Public Member Functions
virtual void mutate (Graph &g) override
Walk the graph and perform a specific mutation.
MutationType type () const override
Returns mutation type.
const char * name () override
Returns mutator name.
Public Member Functions inherited from IGraphMutator
virtual ~IGraphMutator ()=default
Virtual Destructor.
Additional Inherited Members
Public Types inherited from IGraphMutator
enum MutationType { IR, Backend }
Mutation type.
Detailed Description
Mutation pass to fuss nodes.
Definition at line 35 of file NodeFusionMutator.h.
Member Function Documentation
mutate()
void mutate (Graph & g) override virtual
Walk the graph and perform a specific mutation.
Parameters
[in,out] g Graph to walk and mutate
Implements IGraphMutator.
Definition at line 805 of file NodeFusionMutator.cpp.
References ActivationLayerInfo::ABS, ARM_COMPUTE_ERROR_ON, ActivationLayerInfo::BOUNDED_RELU, arm_compute::graph::CL, Graph::edge(), ActivationLayerInfo::ELU, arm_compute::graph::detail::fuse_convolution_batch_normalization_with_post_ops(), arm_compute::graph::detail::fuse_convolution_with_batch_normalization(), arm_compute::graph::detail::fuse_convolution_with_post_ops(), arm_compute::graph::detail::fuse_depthwise_convolution_with_batch_normalization(), ActivationLayerInfo::HARD_SWISH, ActivationLayerInfo::IDENTITY, ActivationLayerInfo::LEAKY_RELU, ActivationLayerInfo::LINEAR, ActivationLayerInfo::LOGISTIC, ActivationLayerInfo::LU_BOUNDED_RELU, arm_compute::test::validation::n, arm_compute::QASYMM8, ActivationLayerInfo::RELU, ActivationLayerInfo::SOFT_RELU, ActivationLayerInfo::SQRT, ActivationLayerInfo::SQUARE, and ActivationLayerInfo::TANH.
 {
     // Supported activations when fusing
     const std::set<Activation> supported_fused_activations = { Activation::ABS, Activation::BOUNDED_RELU, Activation::ELU,
                                                                Activation::HARD_SWISH, Activation::IDENTITY, Activation::LEAKY_RELU,
                                                                Activation::LINEAR, Activation::LOGISTIC, Activation::LU_BOUNDED_RELU,
                                                                Activation::RELU, Activation::SOFT_RELU, Activation::SQRT,
                                                                Activation::SQUARE, Activation::TANH
                                                              };
     // Preconditions
     auto empty_prec = [](INode &)
     {
         return true;
     };
     auto cl_target_prec = [](INode & n)
     {
         return n.assigned_target() == Target::CL;
     };
     auto qs8_prec = [&g](INode & n)
     {
         ARM_COMPUTE_ERROR_ON(n.output(0) == nullptr);
         const auto output_edge_id = *n.output_edges().begin();
         const auto output_edge    = g.edge(output_edge_id);
         // To perform fusion the two nodes must have same output quantization information
         const bool same_qinfo     = n.output(0)->desc().quant_info == output_edge->producer()->output(0)->desc().quant_info;
         const bool output_qasymm8 = n.output(0)->desc().data_type == DataType::QASYMM8;
         return (output_qasymm8 && same_qinfo) || !output_qasymm8;
     };
     // Fusion mutations
     detail::fuse_layer<PadLayerNode, ConvolutionLayerNode>(g, empty_prec, detail::fuse_pad_with_convolution<ConvolutionLayerNode>);
     detail::fuse_layer<PadLayerNode, DepthwiseConvolutionLayerNode>(g, empty_prec, detail::fuse_pad_with_convolution<DepthwiseConvolutionLayerNode>);
     // The fusion of PostOps to ConvolutionLayer:
     // It must occur after the fusion of PadLayer into ConvolutionLayer
     // It must occur before the fusion of normal ActivationLayer into ConvolutionLayer as it takes precedence
     detail::fuse_layer<ConvolutionLayerNode>(g, cl_target_prec, detail::fuse_convolution_with_post_ops, supported_fused_activations);
     detail::fuse_layer<BatchNormalizationLayerNode, ActivationLayerNode>(g, empty_prec, detail::fuse_node_with_activation<BatchNormalizationLayerNode>, supported_fused_activations);
     detail::fuse_layer<ConvolutionLayerNode, ActivationLayerNode>(g, empty_prec, detail::fuse_node_with_activation<ConvolutionLayerNode>, supported_fused_activations);
     detail::fuse_layer<DepthwiseConvolutionLayerNode, ActivationLayerNode>(g, qs8_prec, detail::fuse_node_with_activation<DepthwiseConvolutionLayerNode>, supported_fused_activations);
     detail::fuse_layer<FullyConnectedLayerNode, ActivationLayerNode>(g, empty_prec, detail::fuse_node_with_activation<FullyConnectedLayerNode>, supported_fused_activations);
     detail::fuse_layer<EltwiseLayerNode, ActivationLayerNode>(g, cl_target_prec, detail::fuse_node_with_activation<EltwiseLayerNode>, supported_fused_activations);
     // The fusion of BatchNormalizationLayer must occur after the fusion of ActivationLayer. Because FusedConvolutionBatchNormalizationNode assumes the BatchNormalization is already fused with activation, if any
     detail::fuse_layer<ConvolutionLayerNode, BatchNormalizationLayerNode>(g, empty_prec, detail::fuse_convolution_with_batch_normalization);
     detail::fuse_layer<DepthwiseConvolutionLayerNode, BatchNormalizationLayerNode>(g, empty_prec, detail::fuse_depthwise_convolution_with_batch_normalization);
     detail::fuse_layer<FusedConvolutionBatchNormalizationNode>(g, cl_target_prec, detail::fuse_convolution_batch_normalization_with_post_ops, supported_fused_activations);
 }
name()
const char * name () override virtual
Returns mutator name.
Returns
Mutator name
Implements IGraphMutator.
Definition at line 795 of file NodeFusionMutator.cpp.
 {
     return "NodeFusionMutator";
 }
type()
IGraphMutator::MutationType type () const override virtual
Returns mutation type.
Returns
Mutation type enumeration
Implements IGraphMutator.
Definition at line 800 of file NodeFusionMutator.cpp.
References IGraphMutator::Backend.
 {
     return IGraphMutator::MutationType::Backend;
 }
The documentation for this class was generated from the following files:
arm_compute/graph/mutators/NodeFusionMutator.h
src/graph/mutators/NodeFusionMutator.cpp