Compute Library: PostOpAct< TensorRelatedT > Struct Template Reference
PostOpAct< TensorRelatedT > Struct Template Reference
(EXPERIMENTAL_POST_OPS) Implementation of specific IPostOps
#include <PostOps.h>
Public Member Functions
PostOpAct (const ActivationLayerInfo &act_info)
~PostOpAct () override=default
PostOpAct (const PostOpAct &)=default
PostOpAct & operator= (const PostOpAct &)=default
PostOpAct (PostOpAct &&)=default
PostOpAct & operator= (PostOpAct &&)=default
int prev_dst_pos () const override
The position of previous op's dst in current op's argument list.
PostOpType type () const override
The IPostOp type.
std::vector< TensorRelatedT * > arguments () override
The argument tensors The order of the argument tensor is strictly preserved.
std::vector< const TensorRelatedT * > arguments () const override
std::unique_ptr< IPostOp< TensorRelatedT > > clone () const override
Clone method used in cases where PostOps are owned by unique_ptr.
Public Member Functions inherited from IPostOp< TensorRelatedT >
size_t arity () const
Get the arity of the post op.
virtual ~IPostOp ()
Data Fields
ActivationLayerInfo _act_info
Detailed Description
template<typename TensorRelatedT>
struct arm_compute::experimental::PostOpAct< TensorRelatedT >
(EXPERIMENTAL_POST_OPS) Implementation of specific IPostOps
Definition at line 42 of file PostOps.h.
Constructor & Destructor Documentation
PostOpAct() [1/3]
PostOpAct (const ActivationLayerInfo & act_info) inline
Definition at line 45 of file PostOps.h.
References PostOpAct< TensorRelatedT >::operator=(), and PostOpAct< TensorRelatedT >::~PostOpAct().
         : _act_info{ act_info }
     {
     }
~PostOpAct()
~PostOpAct () override default
Referenced by PostOpAct< TensorRelatedT >::PostOpAct().
PostOpAct() [2/3]
PostOpAct (const PostOpAct< TensorRelatedT > &) default
PostOpAct() [3/3]
PostOpAct (PostOpAct< TensorRelatedT > &&) default
Member Function Documentation
arguments() [1/2]
std::vector<TensorRelatedT *> arguments () inline override virtual
The argument tensors The order of the argument tensor is strictly preserved.
Implements IPostOp< TensorRelatedT >.
Definition at line 64 of file PostOps.h.
     {
         return {};
     }
arguments() [2/2]
std::vector<const TensorRelatedT *> arguments () const inline override virtual
Implements IPostOp< TensorRelatedT >.
Definition at line 68 of file PostOps.h.
     {
         return {};
     }
clone()
std::unique_ptr<IPostOp<TensorRelatedT> > clone () const inline override virtual
Clone method used in cases where PostOps are owned by unique_ptr.
Note
: This performs a shallow copy of the TensorRelatedT if TensorRelatedT points to a resource
Implements IPostOp< TensorRelatedT >.
Definition at line 72 of file PostOps.h.
     {
         return std::make_unique<PostOpAct<TensorRelatedT>>(*this);
     }
operator=() [1/2]
PostOpAct& operator= (const PostOpAct< TensorRelatedT > &) default
Referenced by PostOpAct< TensorRelatedT >::PostOpAct(), PostOpEltwiseAdd< TensorRelatedT >::PostOpEltwiseAdd(), and PostOpEltwisePRelu< TensorRelatedT >::PostOpEltwisePRelu().
operator=() [2/2]
PostOpAct& operator= (PostOpAct< TensorRelatedT > &&) default
prev_dst_pos()
int prev_dst_pos () const inline override virtual
The position of previous op's dst in current op's argument list.
Implements IPostOp< TensorRelatedT >.
Definition at line 56 of file PostOps.h.
Referenced by PostOpEltwiseAdd< TensorRelatedT >::PostOpEltwiseAdd(), and PostOpEltwisePRelu< TensorRelatedT >::PostOpEltwisePRelu().
     {
         return 0;
     }
type()
PostOpType type () const inline override virtual
The IPostOp type.
Implements IPostOp< TensorRelatedT >.
Definition at line 60 of file PostOps.h.
References arm_compute::experimental::Activation.
     {
         return PostOpType::Activation;
     }
Field Documentation
_act_info
ActivationLayerInfo _act_info
Definition at line 76 of file PostOps.h.
The documentation for this struct was generated from the following file:
arm_compute/core/experimental/PostOps.h