Compute Library: src/core/CL/OpenCL.cpp File Reference
OpenCL.cpp File Reference
#include "arm_compute/core/CL/OpenCL.h"
#include "arm_compute/core/Error.h"
#include <algorithm>
#include <dlfcn.h>
#include <iostream>
#include <sstream>
Namespaces
arm_compute
Copyright (c) 2017-2023 Arm Limited.
Macros
#define LOAD_FUNCTION_PTR(func_name, handle) func_name##_ptr = reinterpret_cast<decltype(func_name) *>(dlsym(handle, #func_name));
Functions
bool opencl_is_available ()
Check if OpenCL is available.
cl_int clEnqueueMarker (cl_command_queue command_queue, cl_event *event)
cl_int clWaitForEvents (cl_uint num_events, const cl_event *event_list)
cl_int clEnqueueSVMMap (cl_command_queue command_queue, cl_bool blocking_map, cl_map_flags flags, void *svm_ptr, size_t size, cl_uint num_events_in_wait_list, const cl_event *event_wait_list, cl_event *event)
cl_int clEnqueueSVMUnmap (cl_command_queue command_queue, void *svm_ptr, cl_uint num_events_in_wait_list, const cl_event *event_wait_list, cl_event *event)
void * clSVMAlloc (cl_context context, cl_svm_mem_flags_arm flags, size_t size, cl_uint alignment)
void clSVMFree (cl_context context, void *svm_pointer)
cl_int clGetContextInfo (cl_context context, cl_context_info param_name, size_t param_value_size, void *param_value, size_t *param_value_size_ret)
cl_command_queue clCreateCommandQueue (cl_context context, cl_device_id device, cl_command_queue_properties properties, cl_int *errcode_ret)
cl_command_queue clCreateCommandQueueWithProperties (cl_context context, cl_device_id device, const cl_queue_properties *properties, cl_int *errcode_ret)
cl_context clCreateContext (const cl_context_properties *properties, cl_uint num_devices, const cl_device_id *devices, void(*pfn_notify)(const char *, const void *, size_t, void *), void *user_data, cl_int *errcode_ret)
cl_context clCreateContextFromType (const cl_context_properties *properties, cl_device_type device_type, void(*pfn_notify)(const char *, const void *, size_t, void *), void *user_data, cl_int *errcode_ret)
cl_int clBuildProgram (cl_program program, cl_uint num_devices, const cl_device_id *device_list, const char *options, void(CL_CALLBACK *pfn_notify)(cl_program program, void *user_data), void *user_data)
cl_int clEnqueueNDRangeKernel (cl_command_queue command_queue, cl_kernel kernel, cl_uint work_dim, const size_t *global_work_offset, const size_t *global_work_size, const size_t *local_work_size, cl_uint num_events_in_wait_list, const cl_event *event_wait_list, cl_event *event)
cl_int clSetKernelArg (cl_kernel kernel, cl_uint arg_index, size_t arg_size, const void *arg_value)
cl_int clRetainMemObject (cl_mem memobj)
cl_int clReleaseMemObject (cl_mem memobj)
cl_int clEnqueueUnmapMemObject (cl_command_queue command_queue, cl_mem memobj, void *mapped_ptr, cl_uint num_events_in_wait_list, const cl_event *event_wait_list, cl_event *event)
cl_int clRetainCommandQueue (cl_command_queue command_queue)
cl_int clReleaseContext (cl_context context)
cl_int clReleaseEvent (cl_event event)
cl_int clEnqueueWriteBuffer (cl_command_queue command_queue, cl_mem buffer, cl_bool blocking_write, size_t offset, size_t size, const void *ptr, cl_uint num_events_in_wait_list, const cl_event *event_wait_list, cl_event *event)
cl_int clEnqueueReadBuffer (cl_command_queue command_queue, cl_mem buffer, cl_bool blocking_read, size_t offset, size_t size, void *ptr, cl_uint num_events_in_wait_list, const cl_event *event_wait_list, cl_event *event)
cl_int clGetProgramBuildInfo (cl_program program, cl_device_id device, cl_program_build_info param_name, size_t param_value_size, void *param_value, size_t *param_value_size_ret)
cl_int clRetainProgram (cl_program program)
void * clEnqueueMapBuffer (cl_command_queue command_queue, cl_mem buffer, cl_bool blocking_map, cl_map_flags map_flags, size_t offset, size_t size, cl_uint num_events_in_wait_list, const cl_event *event_wait_list, cl_event *event, cl_int *errcode_ret)
cl_int clReleaseCommandQueue (cl_command_queue command_queue)
cl_program clCreateProgramWithBinary (cl_context context, cl_uint num_devices, const cl_device_id *device_list, const size_t *lengths, const unsigned char **binaries, cl_int *binary_status, cl_int *errcode_ret)
cl_int clRetainContext (cl_context context)
cl_int clReleaseProgram (cl_program program)
cl_int clFlush (cl_command_queue command_queue)
cl_int clFinish (cl_command_queue command_queue)
cl_int clGetProgramInfo (cl_program program, cl_program_info param_name, size_t param_value_size, void *param_value, size_t *param_value_size_ret)
cl_kernel clCreateKernel (cl_program program, const char *kernel_name, cl_int *errcode_ret)
cl_int clRetainKernel (cl_kernel kernel)
cl_mem clCreateBuffer (cl_context context, cl_mem_flags flags, size_t size, void *host_ptr, cl_int *errcode_ret)
cl_program clCreateProgramWithSource (cl_context context, cl_uint count, const char **strings, const size_t *lengths, cl_int *errcode_ret)
cl_int clReleaseKernel (cl_kernel kernel)
cl_int clGetDeviceIDs (cl_platform_id platform, cl_device_type device_type, cl_uint num_entries, cl_device_id *devices, cl_uint *num_devices)
cl_int clGetDeviceInfo (cl_device_id device, cl_device_info param_name, size_t param_value_size, void *param_value, size_t *param_value_size_ret)
cl_int clGetMemObjectInfo (cl_mem memobj, cl_mem_info param_name, size_t param_value_size, void *param_value, size_t *param_value_size_ret)
cl_int clRetainEvent (cl_event event)
cl_int clGetPlatformInfo (cl_platform_id platform, cl_platform_info param_name, size_t param_value_size, void *param_value, size_t *param_value_size_ret)
cl_int clGetPlatformIDs (cl_uint num_entries, cl_platform_id *platforms, cl_uint *num_platforms)
cl_int clGetKernelWorkGroupInfo (cl_kernel kernel, cl_device_id device, cl_kernel_work_group_info param_name, size_t param_value_size, void *param_value, size_t *param_value_size_ret)
cl_int clGetCommandQueueInfo (cl_command_queue command_queue, cl_command_queue_info param_name, size_t param_value_size, void *param_value, size_t *param_value_size_ret)
cl_int clGetKernelInfo (cl_kernel kernel, cl_kernel_info param_name, size_t param_value_size, void *param_value, size_t *param_value_size_ret)
cl_int clGetEventProfilingInfo (cl_event event, cl_profiling_info param_name, size_t param_value_size, void *param_value, size_t *param_value_size_ret)
cl_mem clCreateImage (cl_context context, cl_mem_flags flags, const cl_image_format *image_format, const cl_image_desc *image_desc, void *host_ptr, cl_int *errcode_ret)
cl_int clSetKernelExecInfo (cl_kernel kernel, cl_kernel_exec_info param_name, size_t param_value_size, const void *param_value)
cl_command_buffer_khr clCreateCommandBufferKHR (cl_uint num_queues, const cl_command_queue *queues, const cl_command_buffer_properties_khr *properties, cl_int *errcode_ret)
cl_int clFinalizeCommandBufferKHR (cl_command_buffer_khr command_buffer)
cl_int clRetainCommandBufferKHR (cl_command_buffer_khr command_buffer)
cl_int clReleaseCommandBufferKHR (cl_command_buffer_khr command_buffer)
cl_int clEnqueueCommandBufferKHR (cl_uint num_queues, cl_command_queue *queues, cl_command_buffer_khr command_buffer, cl_uint num_events_in_wait_list, const cl_event *event_wait_list, cl_event *event)
cl_int clCommandNDRangeKernelKHR (cl_command_buffer_khr command_buffer, cl_command_queue command_queue, const cl_ndrange_kernel_command_properties_khr *properties, cl_kernel kernel, cl_uint work_dim, const size_t *global_work_offset, const size_t *global_work_size, const size_t *local_work_size, cl_uint num_sync_points_in_wait_list, const cl_sync_point_khr *sync_point_wait_list, cl_sync_point_khr *sync_point, cl_mutable_command_khr *mutable_handle)
cl_int clUpdateMutableCommandsKHR (cl_command_buffer_khr command_buffer, const cl_mutable_base_config_khr *mutable_config)
cl_mem clImportMemoryARM (cl_context context, cl_mem_flags flags, const cl_import_properties_arm *properties, void *memory, size_t size, cl_int *errcode_ret)
Macro Definition Documentation
LOAD_FUNCTION_PTR
#define LOAD_FUNCTION_PTR (func_name, handle) func_name##_ptr = reinterpret_cast<decltype(func_name) *>(dlsym(handle, #func_name));
Function Documentation
clBuildProgram()
cl_int clBuildProgram (cl_program program, cl_uint num_devices, const cl_device_id * device_list, const char * options, void(CL_CALLBACK *pfn_notify)(cl_program program, void *user_data) , void * user_data)
Definition at line 412 of file OpenCL.cpp.
 {
     arm_compute::CLSymbols::get().load_default();
     auto func = arm_compute::CLSymbols::get().clBuildProgram_ptr;
     if (func != nullptr)
     {
         return func(program, num_devices, device_list, options, pfn_notify, user_data);
     }
     else
     {
         return CL_OUT_OF_RESOURCES;
     }
 }
References CLSymbols::clBuildProgram_ptr, CLSymbols::get(), and CLSymbols::load_default().
Referenced by CLSymbols::load().
clCommandNDRangeKernelKHR()
cl_int clCommandNDRangeKernelKHR (cl_command_buffer_khr command_buffer, cl_command_queue command_queue, const cl_ndrange_kernel_command_properties_khr * properties, cl_kernel kernel, cl_uint work_dim, const size_t * global_work_offset, const size_t * global_work_size, const size_t * local_work_size, cl_uint num_sync_points_in_wait_list, const cl_sync_point_khr * sync_point_wait_list, cl_sync_point_khr * sync_point, cl_mutable_command_khr * mutable_handle)
Definition at line 1154 of file OpenCL.cpp.
 {
     arm_compute::CLSymbols::get().load_default();
     const auto func = arm_compute::CLSymbols::get().clCommandNDRangeKernelKHR_ptr;
     if (func != nullptr)
     {
         return func(command_buffer, command_queue, properties, kernel, work_dim, global_work_offset, global_work_size,
                     local_work_size, num_sync_points_in_wait_list, sync_point_wait_list, sync_point, mutable_handle);
     }
     else
     {
         return CL_INVALID_OPERATION;
     }
 }
References CLSymbols::clCommandNDRangeKernelKHR_ptr, CLSymbols::get(), and CLSymbols::load_default().
Referenced by CLMutableCommandBuffer::add_kernel(), and CLSymbols::load().
clCreateBuffer()
cl_mem clCreateBuffer (cl_context context, cl_mem_flags flags, size_t size, void * host_ptr, cl_int * errcode_ret)
Definition at line 807 of file OpenCL.cpp.
 {
     arm_compute::CLSymbols::get().load_default();
     auto func = arm_compute::CLSymbols::get().clCreateBuffer_ptr;
     if (func != nullptr)
     {
         return func(context, flags, size, host_ptr, errcode_ret);
     }
     else
     {
         if (errcode_ret != nullptr)
         {
             *errcode_ret = CL_OUT_OF_RESOURCES;
         }
         return nullptr;
     }
 }
References CLSymbols::clCreateBuffer_ptr, arm_compute::test::validation::context, CLSymbols::get(), and CLSymbols::load_default().
Referenced by CLBufferAllocator::allocate(), and CLSymbols::load().
clCreateCommandBufferKHR()
cl_command_buffer_khr clCreateCommandBufferKHR (cl_uint num_queues, const cl_command_queue * queues, const cl_command_buffer_properties_khr * properties, cl_int * errcode_ret)
Definition at line 1066 of file OpenCL.cpp.
 {
     arm_compute::CLSymbols::get().load_default();
     const auto func = arm_compute::CLSymbols::get().clCreateCommandBufferKHR_ptr;
     if (func != nullptr)
     {
         return func(num_queues, queues, properties, errcode_ret);
     }
     else
     {
         if (errcode_ret != nullptr)
         {
             *errcode_ret = CL_INVALID_OPERATION;
         }
         return {};
     }
 }
References CLSymbols::clCreateCommandBufferKHR_ptr, CLSymbols::get(), and CLSymbols::load_default().
Referenced by CLMutableCommandBuffer::CLMutableCommandBuffer(), and CLSymbols::load().
clCreateCommandQueue()
cl_command_queue clCreateCommandQueue (cl_context context, cl_device_id device, cl_command_queue_properties properties, cl_int * errcode_ret)
Definition at line 341 of file OpenCL.cpp.
 {
     arm_compute::CLSymbols::get().load_default();
     auto func = arm_compute::CLSymbols::get().clCreateCommandQueue_ptr;
     if (func != nullptr)
     {
         return func(context, device, properties, errcode_ret);
     }
     else
     {
         return nullptr;
     }
 }
References CLSymbols::clCreateCommandQueue_ptr, arm_compute::test::validation::context, CLSymbols::get(), and CLSymbols::load_default().
Referenced by CLSymbols::load().
clCreateCommandQueueWithProperties()
cl_command_queue clCreateCommandQueueWithProperties (cl_context context, cl_device_id device, const cl_queue_properties * properties, cl_int * errcode_ret)
Definition at line 358 of file OpenCL.cpp.
 {
     arm_compute::CLSymbols::get().load_default();
     auto func = arm_compute::CLSymbols::get().clCreateCommandQueueWithProperties_ptr;
     if (func != nullptr)
     {
         return func(context, device, properties, errcode_ret);
     }
     else
     {
         return nullptr;
     }
 }
References CLSymbols::clCreateCommandQueueWithProperties_ptr, arm_compute::test::validation::context, CLSymbols::get(), and CLSymbols::load_default().
Referenced by CLSymbols::load(), and arm_compute::test::validation::TEST_CASE().
clCreateContext()
cl_context clCreateContext (const cl_context_properties * properties, cl_uint num_devices, const cl_device_id * devices, void(*)(const char *, const void *, size_t, void *) pfn_notify, void * user_data, cl_int * errcode_ret)
Definition at line 375 of file OpenCL.cpp.
 {
     arm_compute::CLSymbols::get().load_default();
     auto func = arm_compute::CLSymbols::get().clCreateContext_ptr;
     if (func != nullptr)
     {
         return func(properties, num_devices, devices, pfn_notify, user_data, errcode_ret);
     }
     else
     {
         return nullptr;
     }
 }
References CLSymbols::clCreateContext_ptr, CLSymbols::get(), and CLSymbols::load_default().
Referenced by CLSymbols::load().
clCreateContextFromType()
cl_context clCreateContextFromType (const cl_context_properties * properties, cl_device_type device_type, void(*)(const char *, const void *, size_t, void *) pfn_notify, void * user_data, cl_int * errcode_ret)
Definition at line 394 of file OpenCL.cpp.
 {
     arm_compute::CLSymbols::get().load_default();
     auto func = arm_compute::CLSymbols::get().clCreateContextFromType_ptr;
     if (func != nullptr)
     {
         return func(properties, device_type, pfn_notify, user_data, errcode_ret);
     }
     else
     {
         return nullptr;
     }
 }
References CLSymbols::clCreateContextFromType_ptr, CLSymbols::get(), and CLSymbols::load_default().
Referenced by CLSymbols::load().
clCreateImage()
cl_mem clCreateImage (cl_context context, cl_mem_flags flags, const cl_image_format * image_format, const cl_image_desc * image_desc, void * host_ptr, cl_int * errcode_ret)
Definition at line 1028 of file OpenCL.cpp.
 {
     arm_compute::CLSymbols::get().load_default();
     auto func = arm_compute::CLSymbols::get().clCreateImage_ptr;
     if (func != nullptr)
     {
         return func(context, flags, image_format, image_desc, host_ptr, errcode_ret);
     }
     else
     {
         if (errcode_ret != nullptr)
         {
             *errcode_ret = CL_OUT_OF_RESOURCES;
         }
         return nullptr;
     }
 }
References CLSymbols::clCreateImage_ptr, arm_compute::test::validation::context, CLSymbols::get(), and CLSymbols::load_default().
Referenced by arm_compute::create_image2d_from_buffer(), and CLSymbols::load().
clCreateKernel()
cl_kernel clCreateKernel (cl_program program, const char * kernel_name, cl_int * errcode_ret)
Definition at line 775 of file OpenCL.cpp.
 {
     arm_compute::CLSymbols::get().load_default();
     auto func = arm_compute::CLSymbols::get().clCreateKernel_ptr;
     if (func != nullptr)
     {
         return func(program, kernel_name, errcode_ret);
     }
     else
     {
         if (errcode_ret != nullptr)
         {
             *errcode_ret = CL_OUT_OF_RESOURCES;
         }
         return nullptr;
     }
 }
References CLSymbols::clCreateKernel_ptr, CLSymbols::get(), kernel_name, and CLSymbols::load_default().
Referenced by CLSymbols::load().
clCreateProgramWithBinary()
cl_program clCreateProgramWithBinary (cl_context context, cl_uint num_devices, const cl_device_id * device_list, const size_t * lengths, const unsigned char ** binaries, cl_int * binary_status, cl_int * errcode_ret)
Definition at line 677 of file OpenCL.cpp.
 {
     arm_compute::CLSymbols::get().load_default();
     auto func = arm_compute::CLSymbols::get().clCreateProgramWithBinary_ptr;
     if (func != nullptr)
     {
         return func(context, num_devices, device_list, lengths, binaries, binary_status, errcode_ret);
     }
     else
     {
         if (errcode_ret != nullptr)
         {
             *errcode_ret = CL_OUT_OF_RESOURCES;
         }
         return nullptr;
     }
 }
References CLSymbols::clCreateProgramWithBinary_ptr, arm_compute::test::validation::context, CLSymbols::get(), and CLSymbols::load_default().
Referenced by CLSymbols::load().
clCreateProgramWithSource()
cl_program clCreateProgramWithSource (cl_context context, cl_uint count, const char ** strings, const size_t * lengths, cl_int * errcode_ret)
Definition at line 825 of file OpenCL.cpp.
 {
     arm_compute::CLSymbols::get().load_default();
     auto func = arm_compute::CLSymbols::get().clCreateProgramWithSource_ptr;
     if (func != nullptr)
     {
         return func(context, count, strings, lengths, errcode_ret);
     }
     else
     {
         if (errcode_ret != nullptr)
         {
             *errcode_ret = CL_OUT_OF_RESOURCES;
         }
         return nullptr;
     }
 }
References CLSymbols::clCreateProgramWithSource_ptr, arm_compute::test::validation::context, CLSymbols::get(), and CLSymbols::load_default().
Referenced by CLSymbols::load().
clEnqueueCommandBufferKHR()
cl_int clEnqueueCommandBufferKHR (cl_uint num_queues, cl_command_queue * queues, cl_command_buffer_khr command_buffer, cl_uint num_events_in_wait_list, const cl_event * event_wait_list, cl_event * event)
Definition at line 1134 of file OpenCL.cpp.
 {
     arm_compute::CLSymbols::get().load_default();
     const auto func = arm_compute::CLSymbols::get().clEnqueueCommandBufferKHR_ptr;
     if (func != nullptr)
     {
         return func(num_queues, queues, command_buffer, num_events_in_wait_list, event_wait_list, event);
     }
     else
     {
         return CL_INVALID_OPERATION;
     }
 }
References CLSymbols::clEnqueueCommandBufferKHR_ptr, CLSymbols::get(), and CLSymbols::load_default().
Referenced by CLMutableCommandBuffer::enqueue(), and CLSymbols::load().
clEnqueueMapBuffer()
void* clEnqueueMapBuffer (cl_command_queue command_queue, cl_mem buffer, cl_bool blocking_map, cl_map_flags map_flags, size_t offset, size_t size, cl_uint num_events_in_wait_list, const cl_event * event_wait_list, cl_event * event, cl_int * errcode_ret)
Definition at line 635 of file OpenCL.cpp.
 {
     arm_compute::CLSymbols::get().load_default();
     auto func = arm_compute::CLSymbols::get().clEnqueueMapBuffer_ptr;
     if (func != nullptr)
     {
         return func(command_queue, buffer, blocking_map, map_flags, offset, size, num_events_in_wait_list,
                     event_wait_list, event, errcode_ret);
     }
     else
     {
         if (errcode_ret != nullptr)
         {
             *errcode_ret = CL_OUT_OF_RESOURCES;
         }
         return nullptr;
     }
 }
References CLSymbols::clEnqueueMapBuffer_ptr, CLSymbols::get(), CLSymbols::load_default(), and offset().
Referenced by CLSymbols::load().
clEnqueueMarker()
cl_int clEnqueueMarker (cl_command_queue command_queue, cl_event * event)
Definition at line 232 of file OpenCL.cpp.
 {
     arm_compute::CLSymbols::get().load_default();
     auto func = arm_compute::CLSymbols::get().clEnqueueMarker_ptr;
     if (func != nullptr)
     {
         return func(command_queue, event);
     }
     else
     {
         return CL_OUT_OF_RESOURCES;
     }
 }
References CLSymbols::clEnqueueMarker_ptr, CLSymbols::get(), and CLSymbols::load_default().
Referenced by CLSymbols::load().
clEnqueueNDRangeKernel()
cl_int clEnqueueNDRangeKernel (cl_command_queue command_queue, cl_kernel kernel, cl_uint work_dim, const size_t * global_work_offset, const size_t * global_work_size, const size_t * local_work_size, cl_uint num_events_in_wait_list, const cl_event * event_wait_list, cl_event * event)
Definition at line 431 of file OpenCL.cpp.
 {
     arm_compute::CLSymbols::get().load_default();
     auto func = arm_compute::CLSymbols::get().clEnqueueNDRangeKernel_ptr;
     if (func != nullptr)
     {
         return func(command_queue, kernel, work_dim, global_work_offset, global_work_size, local_work_size,
                     num_events_in_wait_list, event_wait_list, event);
     }
     else
     {
         return CL_OUT_OF_RESOURCES;
     }
 }
References CLSymbols::clEnqueueNDRangeKernel_ptr, CLSymbols::get(), and CLSymbols::load_default().
Referenced by CLCompatCommandBuffer::enqueue(), and CLSymbols::load().
clEnqueueReadBuffer()
cl_int clEnqueueReadBuffer (cl_command_queue command_queue, cl_mem buffer, cl_bool blocking_read, size_t offset, size_t size, void * ptr, cl_uint num_events_in_wait_list, const cl_event * event_wait_list, cl_event * event)
Definition at line 579 of file OpenCL.cpp.
 {
     arm_compute::CLSymbols::get().load_default();
     auto func = arm_compute::CLSymbols::get().clEnqueueReadBuffer_ptr;
     if (func != nullptr)
     {
         return func(command_queue, buffer, blocking_read, offset, size, ptr, num_events_in_wait_list, event_wait_list,
                     event);
     }
     else
     {
         return CL_OUT_OF_RESOURCES;
     }
 }
References CLSymbols::clEnqueueReadBuffer_ptr, CLSymbols::get(), CLSymbols::load_default(), and offset().
Referenced by CLSymbols::load().
clEnqueueSVMMap()
cl_int clEnqueueSVMMap (cl_command_queue command_queue, cl_bool blocking_map, cl_map_flags flags, void * svm_ptr, size_t size, cl_uint num_events_in_wait_list, const cl_event * event_wait_list, cl_event * event)
Definition at line 260 of file OpenCL.cpp.
 {
     arm_compute::CLSymbols::get().load_default();
     auto func = arm_compute::CLSymbols::get().clEnqueueSVMMap_ptr;
     if (func != nullptr)
     {
         return func(command_queue, blocking_map, flags, svm_ptr, size, num_events_in_wait_list, event_wait_list, event);
     }
     else
     {
         return CL_OUT_OF_RESOURCES;
     }
 }
References CLSymbols::clEnqueueSVMMap_ptr, CLSymbols::get(), and CLSymbols::load_default().
Referenced by CLSymbols::load(), and CLCoarseSVMMemoryRegion::map().
clEnqueueSVMUnmap()
cl_int clEnqueueSVMUnmap (cl_command_queue command_queue, void * svm_ptr, cl_uint num_events_in_wait_list, const cl_event * event_wait_list, cl_event * event)
Definition at line 281 of file OpenCL.cpp.
 {
     arm_compute::CLSymbols::get().load_default();
     auto func = arm_compute::CLSymbols::get().clEnqueueSVMUnmap_ptr;
     if (func != nullptr)
     {
         return func(command_queue, svm_ptr, num_events_in_wait_list, event_wait_list, event);
     }
     else
     {
         return CL_OUT_OF_RESOURCES;
     }
 }
References CLSymbols::clEnqueueSVMUnmap_ptr, CLSymbols::get(), and CLSymbols::load_default().
Referenced by CLSymbols::load(), and CLCoarseSVMMemoryRegion::unmap().
clEnqueueUnmapMemObject()
cl_int clEnqueueUnmapMemObject (cl_command_queue command_queue, cl_mem memobj, void * mapped_ptr, cl_uint num_events_in_wait_list, const cl_event * event_wait_list, cl_event * event)
Definition at line 496 of file OpenCL.cpp.
 {
     arm_compute::CLSymbols::get().load_default();
     auto func = arm_compute::CLSymbols::get().clEnqueueUnmapMemObject_ptr;
     if (func != nullptr)
     {
         return func(command_queue, memobj, mapped_ptr, num_events_in_wait_list, event_wait_list, event);
     }
     else
     {
         return CL_OUT_OF_RESOURCES;
     }
 }
References CLSymbols::clEnqueueUnmapMemObject_ptr, CLSymbols::get(), and CLSymbols::load_default().
Referenced by CLSymbols::load().
clEnqueueWriteBuffer()
cl_int clEnqueueWriteBuffer (cl_command_queue command_queue, cl_mem buffer, cl_bool blocking_write, size_t offset, size_t size, const void * ptr, cl_uint num_events_in_wait_list, const cl_event * event_wait_list, cl_event * event)
Definition at line 556 of file OpenCL.cpp.
 {
     arm_compute::CLSymbols::get().load_default();
     auto func = arm_compute::CLSymbols::get().clEnqueueWriteBuffer_ptr;
     if (func != nullptr)
     {
         return func(command_queue, buffer, blocking_write, offset, size, ptr, num_events_in_wait_list, event_wait_list,
                     event);
     }
     else
     {
         return CL_OUT_OF_RESOURCES;
     }
 }
References CLSymbols::clEnqueueWriteBuffer_ptr, CLSymbols::get(), CLSymbols::load_default(), and offset().
Referenced by CLSymbols::load().
clFinalizeCommandBufferKHR()
cl_int clFinalizeCommandBufferKHR (cl_command_buffer_khr command_buffer)
Definition at line 1089 of file OpenCL.cpp.
 {
     arm_compute::CLSymbols::get().load_default();
     const auto func = arm_compute::CLSymbols::get().clFinalizeCommandBufferKHR_ptr;
     if (func != nullptr)
     {
         return func(command_buffer);
     }
     else
     {
         return CL_INVALID_OPERATION;
     }
 }
References CLSymbols::clFinalizeCommandBufferKHR_ptr, CLSymbols::get(), and CLSymbols::load_default().
Referenced by CLMutableCommandBuffer::finalize(), and CLSymbols::load().
clFinish()
cl_int clFinish (cl_command_queue command_queue)
Definition at line 743 of file OpenCL.cpp.
 {
     arm_compute::CLSymbols::get().load_default();
     auto func = arm_compute::CLSymbols::get().clFinish_ptr;
     if (func != nullptr)
     {
         return func(command_queue);
     }
     else
     {
         return CL_OUT_OF_RESOURCES;
     }
 }
References CLSymbols::clFinish_ptr, CLSymbols::get(), and CLSymbols::load_default().
Referenced by CLSymbols::load(), and CLFineSVMMemoryRegion::map().
clFlush()
cl_int clFlush (cl_command_queue command_queue)
Definition at line 729 of file OpenCL.cpp.
 {
     arm_compute::CLSymbols::get().load_default();
     auto func = arm_compute::CLSymbols::get().clFlush_ptr;
     if (func != nullptr)
     {
         return func(command_queue);
     }
     else
     {
         return CL_OUT_OF_RESOURCES;
     }
 }
References CLSymbols::clFlush_ptr, CLSymbols::get(), and CLSymbols::load_default().
Referenced by CLSymbols::load().
clGetCommandQueueInfo()
cl_int clGetCommandQueueInfo (cl_command_queue command_queue, cl_command_queue_info param_name, size_t param_value_size, void * param_value, size_t * param_value_size_ret)
Definition at line 974 of file OpenCL.cpp.
 {
     arm_compute::CLSymbols::get().load_default();
     auto func = arm_compute::CLSymbols::get().clGetCommandQueueInfo_ptr;
     if (func != nullptr)
     {
         return func(command_queue, param_name, param_value_size, param_value, param_value_size_ret);
     }
     else
     {
         return CL_OUT_OF_RESOURCES;
     }
 }
References CLSymbols::clGetCommandQueueInfo_ptr, CLSymbols::get(), and CLSymbols::load_default().
Referenced by CLSymbols::load().
clGetContextInfo()
cl_int clGetContextInfo (cl_context context, cl_context_info param_name, size_t param_value_size, void * param_value, size_t * param_value_size_ret)
Definition at line 323 of file OpenCL.cpp.
 {
     arm_compute::CLSymbols::get().load_default();
     auto func = arm_compute::CLSymbols::get().clGetContextInfo_ptr;
     if (func != nullptr)
     {
         return func(context, param_name, param_value_size, param_value, param_value_size_ret);
     }
     else
     {
         return CL_OUT_OF_RESOURCES;
     }
 }
References CLSymbols::clGetContextInfo_ptr, arm_compute::test::validation::context, CLSymbols::get(), and CLSymbols::load_default().
Referenced by CLSymbols::load().
clGetDeviceIDs()
cl_int clGetDeviceIDs (cl_platform_id platform, cl_device_type device_type, cl_uint num_entries, cl_device_id * devices, cl_uint * num_devices)
Definition at line 858 of file OpenCL.cpp.
 {
     arm_compute::CLSymbols::get().load_default();
     auto func = arm_compute::CLSymbols::get().clGetDeviceIDs_ptr;
     if (func != nullptr)
     {
         return func(platform, device_type, num_entries, devices, num_devices);
     }
     else
     {
         return CL_OUT_OF_RESOURCES;
     }
 }
References CLSymbols::clGetDeviceIDs_ptr, CLSymbols::get(), and CLSymbols::load_default().
Referenced by CLSymbols::load().
clGetDeviceInfo()
cl_int clGetDeviceInfo (cl_device_id device, cl_device_info param_name, size_t param_value_size, void * param_value, size_t * param_value_size_ret)
Definition at line 876 of file OpenCL.cpp.
 {
     arm_compute::CLSymbols::get().load_default();
     auto func = arm_compute::CLSymbols::get().clGetDeviceInfo_ptr;
     if (func != nullptr)
     {
         return func(device, param_name, param_value_size, param_value, param_value_size_ret);
     }
     else
     {
         return CL_OUT_OF_RESOURCES;
     }
 }
References CLSymbols::clGetDeviceInfo_ptr, CLSymbols::get(), and CLSymbols::load_default().
Referenced by arm_compute::get_cl_image_pitch_alignment(), arm_compute::get_cl_non_uniform_work_group_supported(), arm_compute::get_wbsm_support_info(), and CLSymbols::load().
clGetEventProfilingInfo()
cl_int clGetEventProfilingInfo (cl_event event, cl_profiling_info param_name, size_t param_value_size, void * param_value, size_t * param_value_size_ret)
Definition at line 1010 of file OpenCL.cpp.
 {
     arm_compute::CLSymbols::get().load_default();
     auto func = arm_compute::CLSymbols::get().clGetEventProfilingInfo_ptr;
     if (func != nullptr)
     {
         return func(event, param_name, param_value_size, param_value, param_value_size_ret);
     }
     else
     {
         return CL_OUT_OF_RESOURCES;
     }
 }
References CLSymbols::clGetEventProfilingInfo_ptr, CLSymbols::get(), and CLSymbols::load_default().
Referenced by CLSymbols::load().
clGetKernelInfo()
cl_int clGetKernelInfo (cl_kernel kernel, cl_kernel_info param_name, size_t param_value_size, void * param_value, size_t * param_value_size_ret)
Definition at line 992 of file OpenCL.cpp.
 {
     arm_compute::CLSymbols::get().load_default();
     auto func = arm_compute::CLSymbols::get().clGetKernelInfo_ptr;
     if (func != nullptr)
     {
         return func(kernel, param_name, param_value_size, param_value, param_value_size_ret);
     }
     else
     {
         return CL_OUT_OF_RESOURCES;
     }
 }
References CLSymbols::clGetKernelInfo_ptr, CLSymbols::get(), and CLSymbols::load_default().
Referenced by CLSymbols::load().
clGetKernelWorkGroupInfo()
cl_int clGetKernelWorkGroupInfo (cl_kernel kernel, cl_device_id device, cl_kernel_work_group_info param_name, size_t param_value_size, void * param_value, size_t * param_value_size_ret)
Definition at line 955 of file OpenCL.cpp.
 {
     arm_compute::CLSymbols::get().load_default();
     auto func = arm_compute::CLSymbols::get().clGetKernelWorkGroupInfo_ptr;
     if (func != nullptr)
     {
         return func(kernel, device, param_name, param_value_size, param_value, param_value_size_ret);
     }
     else
     {
         return CL_OUT_OF_RESOURCES;
     }
 }
References CLSymbols::clGetKernelWorkGroupInfo_ptr, CLSymbols::get(), and CLSymbols::load_default().
Referenced by CLSymbols::load().
clGetMemObjectInfo()
cl_int clGetMemObjectInfo (cl_mem memobj, cl_mem_info param_name, size_t param_value_size, void * param_value, size_t * param_value_size_ret)
Definition at line 894 of file OpenCL.cpp.
 {
     arm_compute::CLSymbols::get().load_default();
     auto func = arm_compute::CLSymbols::get().clGetMemObjectInfo_ptr;
     if (func != nullptr)
     {
         return func(memobj, param_name, param_value_size, param_value, param_value_size_ret);
     }
     else
     {
         return CL_OUT_OF_RESOURCES;
     }
 }
References CLSymbols::clGetMemObjectInfo_ptr, CLSymbols::get(), and CLSymbols::load_default().
Referenced by CLSymbols::load().
clGetPlatformIDs()
cl_int clGetPlatformIDs (cl_uint num_entries, cl_platform_id * platforms, cl_uint * num_platforms)
Definition at line 941 of file OpenCL.cpp.
 {
     arm_compute::CLSymbols::get().load_default();
     auto func = arm_compute::CLSymbols::get().clGetPlatformIDs_ptr;
     if (func != nullptr)
     {
         return func(num_entries, platforms, num_platforms);
     }
     else
     {
         return CL_OUT_OF_RESOURCES;
     }
 }
References CLSymbols::clGetPlatformIDs_ptr, CLSymbols::get(), and CLSymbols::load_default().
Referenced by CLSymbols::load(), and arm_compute::opencl_is_available().
clGetPlatformInfo()
cl_int clGetPlatformInfo (cl_platform_id platform, cl_platform_info param_name, size_t param_value_size, void * param_value, size_t * param_value_size_ret)
Definition at line 923 of file OpenCL.cpp.
 {
     arm_compute::CLSymbols::get().load_default();
     auto func = arm_compute::CLSymbols::get().clGetPlatformInfo_ptr;
     if (func != nullptr)
     {
         return func(platform, param_name, param_value_size, param_value, param_value_size_ret);
     }
     else
     {
         return CL_OUT_OF_RESOURCES;
     }
 }
References CLSymbols::clGetPlatformInfo_ptr, CLSymbols::get(), and CLSymbols::load_default().
Referenced by CLSymbols::load().
clGetProgramBuildInfo()
cl_int clGetProgramBuildInfo (cl_program program, cl_device_id device, cl_program_build_info param_name, size_t param_value_size, void * param_value, size_t * param_value_size_ret)
Definition at line 602 of file OpenCL.cpp.
 {
     arm_compute::CLSymbols::get().load_default();
     auto func = arm_compute::CLSymbols::get().clGetProgramBuildInfo_ptr;
     if (func != nullptr)
     {
         return func(program, device, param_name, param_value_size, param_value, param_value_size_ret);
     }
     else
     {
         return CL_OUT_OF_RESOURCES;
     }
 }
References CLSymbols::clGetProgramBuildInfo_ptr, CLSymbols::get(), and CLSymbols::load_default().
Referenced by CLSymbols::load().
clGetProgramInfo()
cl_int clGetProgramInfo (cl_program program, cl_program_info param_name, size_t param_value_size, void * param_value, size_t * param_value_size_ret)
Definition at line 757 of file OpenCL.cpp.
 {
     arm_compute::CLSymbols::get().load_default();
     auto func = arm_compute::CLSymbols::get().clGetProgramInfo_ptr;
     if (func != nullptr)
     {
         return func(program, param_name, param_value_size, param_value, param_value_size_ret);
     }
     else
     {
         return CL_OUT_OF_RESOURCES;
     }
 }
References CLSymbols::clGetProgramInfo_ptr, CLSymbols::get(), and CLSymbols::load_default().
Referenced by CLSymbols::load().
clImportMemoryARM()
cl_mem clImportMemoryARM (cl_context context, cl_mem_flags flags, const cl_import_properties_arm * properties, void * memory, size_t size, cl_int * errcode_ret)
Definition at line 1197 of file OpenCL.cpp.
 {
     arm_compute::CLSymbols::get().load_default();
     auto func = arm_compute::CLSymbols::get().clImportMemoryARM_ptr;
     if (func != nullptr)
     {
         return func(context, flags, properties, memory, size, errcode_ret);
     }
     else
     {
         if (errcode_ret != nullptr)
         {
             *errcode_ret = CL_OUT_OF_RESOURCES;
         }
         return nullptr;
     }
 }
References CLSymbols::clImportMemoryARM_ptr, arm_compute::test::validation::context, CLSymbols::get(), and CLSymbols::load_default().
Referenced by CLSymbols::load().
clReleaseCommandBufferKHR()
cl_int clReleaseCommandBufferKHR (cl_command_buffer_khr command_buffer)
Definition at line 1119 of file OpenCL.cpp.
 {
     arm_compute::CLSymbols::get().load_default();
     const auto func = arm_compute::CLSymbols::get().clReleaseCommandBufferKHR_ptr;
     if (func != nullptr)
     {
         return func(command_buffer);
     }
     else
     {
         return CL_INVALID_OPERATION;
     }
 }
References CLSymbols::clReleaseCommandBufferKHR_ptr, CLSymbols::get(), and CLSymbols::load_default().
Referenced by CLSymbols::load(), and CLMutableCommandBuffer::~CLMutableCommandBuffer().
clReleaseCommandQueue()
cl_int clReleaseCommandQueue (cl_command_queue command_queue)
Definition at line 663 of file OpenCL.cpp.
 {
     arm_compute::CLSymbols::get().load_default();
     auto func = arm_compute::CLSymbols::get().clReleaseCommandQueue_ptr;
     if (func != nullptr)
     {
         return func(command_queue);
     }
     else
     {
         return CL_OUT_OF_RESOURCES;
     }
 }
References CLSymbols::clReleaseCommandQueue_ptr, CLSymbols::get(), and CLSymbols::load_default().
Referenced by CLSymbols::load(), and arm_compute::test::validation::TEST_CASE().
clReleaseContext()
cl_int clReleaseContext (cl_context context)
Definition at line 529 of file OpenCL.cpp.
 {
     arm_compute::CLSymbols::get().load_default();
     auto func = arm_compute::CLSymbols::get().clReleaseContext_ptr;
     if (func != nullptr)
     {
         return func(context);
     }
     else
     {
         return CL_OUT_OF_RESOURCES;
     }
 }
References CLSymbols::clReleaseContext_ptr, arm_compute::test::validation::context, CLSymbols::get(), and CLSymbols::load_default().
Referenced by CLSymbols::load().
clReleaseEvent()
cl_int clReleaseEvent (cl_event event)
Definition at line 542 of file OpenCL.cpp.
 {
     arm_compute::CLSymbols::get().load_default();
     auto func = arm_compute::CLSymbols::get().clReleaseEvent_ptr;
     if (func != nullptr)
     {
         return func(event);
     }
     else
     {
         return CL_OUT_OF_RESOURCES;
     }
 }
References CLSymbols::clReleaseEvent_ptr, CLSymbols::get(), and CLSymbols::load_default().
Referenced by CLSymbols::load().
clReleaseKernel()
cl_int clReleaseKernel (cl_kernel kernel)
Definition at line 844 of file OpenCL.cpp.
 {
     arm_compute::CLSymbols::get().load_default();
     auto func = arm_compute::CLSymbols::get().clReleaseKernel_ptr;
     if (func != nullptr)
     {
         return func(kernel);
     }
     else
     {
         return CL_OUT_OF_RESOURCES;
     }
 }
References CLSymbols::clReleaseKernel_ptr, CLSymbols::get(), and CLSymbols::load_default().
Referenced by CLSymbols::load().
clReleaseMemObject()
cl_int clReleaseMemObject (cl_mem memobj)
Definition at line 482 of file OpenCL.cpp.
 {
     arm_compute::CLSymbols::get().load_default();
     auto func = arm_compute::CLSymbols::get().clReleaseMemObject_ptr;
     if (func != nullptr)
     {
         return func(memobj);
     }
     else
     {
         return CL_OUT_OF_RESOURCES;
     }
 }
References CLSymbols::clReleaseMemObject_ptr, CLSymbols::get(), and CLSymbols::load_default().
Referenced by CLBufferAllocator::free(), and CLSymbols::load().
clReleaseProgram()
cl_int clReleaseProgram (cl_program program)
Definition at line 715 of file OpenCL.cpp.
 {
     arm_compute::CLSymbols::get().load_default();
     auto func = arm_compute::CLSymbols::get().clReleaseProgram_ptr;
     if (func != nullptr)
     {
         return func(program);
     }
     else
     {
         return CL_OUT_OF_RESOURCES;
     }
 }
References CLSymbols::clReleaseProgram_ptr, CLSymbols::get(), and CLSymbols::load_default().
Referenced by CLSymbols::load().
clRetainCommandBufferKHR()
cl_int clRetainCommandBufferKHR (cl_command_buffer_khr command_buffer)
Definition at line 1104 of file OpenCL.cpp.
 {
     arm_compute::CLSymbols::get().load_default();
     const auto func = arm_compute::CLSymbols::get().clRetainCommandBufferKHR_ptr;
     if (func != nullptr)
     {
         return func(command_buffer);
     }
     else
     {
         return CL_INVALID_OPERATION;
     }
 }
References CLSymbols::clRetainCommandBufferKHR_ptr, CLSymbols::get(), and CLSymbols::load_default().
Referenced by CLSymbols::load().
clRetainCommandQueue()
cl_int clRetainCommandQueue (cl_command_queue command_queue)
Definition at line 515 of file OpenCL.cpp.
 {
     arm_compute::CLSymbols::get().load_default();
     auto func = arm_compute::CLSymbols::get().clRetainCommandQueue_ptr;
     if (func != nullptr)
     {
         return func(command_queue);
     }
     else
     {
         return CL_OUT_OF_RESOURCES;
     }
 }
References CLSymbols::clRetainCommandQueue_ptr, CLSymbols::get(), and CLSymbols::load_default().
Referenced by CLSymbols::load().
clRetainContext()
cl_int clRetainContext (cl_context context)
Definition at line 701 of file OpenCL.cpp.
 {
     arm_compute::CLSymbols::get().load_default();
     auto func = arm_compute::CLSymbols::get().clRetainContext_ptr;
     if (func != nullptr)
     {
         return func(context);
     }
     else
     {
         return CL_OUT_OF_RESOURCES;
     }
 }
References CLSymbols::clRetainContext_ptr, arm_compute::test::validation::context, CLSymbols::get(), and CLSymbols::load_default().
Referenced by CLSymbols::load().
clRetainEvent()
cl_int clRetainEvent (cl_event event)
Definition at line 909 of file OpenCL.cpp.
 {
     arm_compute::CLSymbols::get().load_default();
     auto func = arm_compute::CLSymbols::get().clRetainEvent_ptr;
     if (func != nullptr)
     {
         return func(event);
     }
     else
     {
         return CL_OUT_OF_RESOURCES;
     }
 }
References CLSymbols::clRetainEvent_ptr, CLSymbols::get(), and CLSymbols::load_default().
Referenced by CLSymbols::load(), and OpenCLClock< output_timestamps >::test_start().
clRetainKernel()
cl_int clRetainKernel (cl_kernel kernel)
Definition at line 793 of file OpenCL.cpp.
 {
     arm_compute::CLSymbols::get().load_default();
     auto func = arm_compute::CLSymbols::get().clRetainKernel_ptr;
     if (func != nullptr)
     {
         return func(kernel);
     }
     else
     {
         return CL_OUT_OF_RESOURCES;
     }
 }
References CLSymbols::clRetainKernel_ptr, CLSymbols::get(), and CLSymbols::load_default().
Referenced by CLSymbols::load().
clRetainMemObject()
cl_int clRetainMemObject (cl_mem memobj)
Definition at line 468 of file OpenCL.cpp.
 {
     arm_compute::CLSymbols::get().load_default();
     auto func = arm_compute::CLSymbols::get().clRetainMemObject_ptr;
     if (func != nullptr)
     {
         return func(memobj);
     }
     else
     {
         return CL_OUT_OF_RESOURCES;
     }
 }
References CLSymbols::clRetainMemObject_ptr, CLSymbols::get(), and CLSymbols::load_default().
Referenced by CLSymbols::load().
clRetainProgram()
cl_int clRetainProgram (cl_program program)
Definition at line 621 of file OpenCL.cpp.
 {
     arm_compute::CLSymbols::get().load_default();
     auto func = arm_compute::CLSymbols::get().clRetainProgram_ptr;
     if (func != nullptr)
     {
         return func(program);
     }
     else
     {
         return CL_OUT_OF_RESOURCES;
     }
 }
References CLSymbols::clRetainProgram_ptr, CLSymbols::get(), and CLSymbols::load_default().
Referenced by CLSymbols::load().
clSetKernelArg()
cl_int clSetKernelArg (cl_kernel kernel, cl_uint arg_index, size_t arg_size, const void * arg_value)
Definition at line 454 of file OpenCL.cpp.
 {
     arm_compute::CLSymbols::get().load_default();
     auto func = arm_compute::CLSymbols::get().clSetKernelArg_ptr;
     if (func != nullptr)
     {
         return func(kernel, arg_index, arg_size, arg_value);
     }
     else
     {
         return CL_OUT_OF_RESOURCES;
     }
 }
References CLSymbols::clSetKernelArg_ptr, CLSymbols::get(), and CLSymbols::load_default().
Referenced by CLCompatCommandBuffer::enqueue(), and CLSymbols::load().
clSetKernelExecInfo()
cl_int clSetKernelExecInfo (cl_kernel kernel, cl_kernel_exec_info param_name, size_t param_value_size, const void * param_value)
Definition at line 1052 of file OpenCL.cpp.
 {
     arm_compute::CLSymbols::get().load_default();
     auto func = arm_compute::CLSymbols::get().clSetKernelExecInfo_ptr;
     if (func != nullptr)
     {
         return func(kernel, param_name, param_value_size, param_value);
     }
     else
     {
         return CL_OUT_OF_RESOURCES;
     }
 }
References CLSymbols::clSetKernelExecInfo_ptr, CLSymbols::get(), and CLSymbols::load_default().
Referenced by CLSymbols::load(), and arm_compute::set_wbsm().
clSVMAlloc()
void* clSVMAlloc (cl_context context, cl_svm_mem_flags_arm flags, size_t size, cl_uint alignment)
Definition at line 299 of file OpenCL.cpp.
 {
     arm_compute::CLSymbols::get().load_default();
     auto func = arm_compute::CLSymbols::get().clSVMAlloc_ptr;
     if (func != nullptr)
     {
         return func(context, flags, size, alignment);
     }
     else
     {
         return nullptr;
     }
 }
References CLSymbols::clSVMAlloc_ptr, arm_compute::test::validation::context, CLSymbols::get(), and CLSymbols::load_default().
Referenced by CLSymbols::load().
clSVMFree()
void clSVMFree (cl_context context, void * svm_pointer)
Definition at line 313 of file OpenCL.cpp.
 {
     arm_compute::CLSymbols::get().load_default();
     auto func = arm_compute::CLSymbols::get().clSVMFree_ptr;
     if (func != nullptr)
     {
         func(context, svm_pointer);
     }
 }
References CLSymbols::clSVMFree_ptr, arm_compute::test::validation::context, CLSymbols::get(), and CLSymbols::load_default().
Referenced by CLSymbols::load().
clUpdateMutableCommandsKHR()
cl_int clUpdateMutableCommandsKHR (cl_command_buffer_khr command_buffer, const cl_mutable_base_config_khr * mutable_config)
Definition at line 1181 of file OpenCL.cpp.
 {
     arm_compute::CLSymbols::get().load_default();
     const auto func = arm_compute::CLSymbols::get().clUpdateMutableCommandsKHR_ptr;
     if (func != nullptr)
     {
         return func(command_buffer, mutable_config);
     }
     else
     {
         return CL_INVALID_OPERATION;
     }
 }
References CLSymbols::clUpdateMutableCommandsKHR_ptr, CLSymbols::get(), and CLSymbols::load_default().
Referenced by CLSymbols::load(), and CLMutableCommandBuffer::update().
clWaitForEvents()
cl_int clWaitForEvents (cl_uint num_events, const cl_event * event_list)
Definition at line 246 of file OpenCL.cpp.
 {
     arm_compute::CLSymbols::get().load_default();
     auto func = arm_compute::CLSymbols::get().clWaitForEvents_ptr;
     if (func != nullptr)
     {
         return func(num_events, event_list);
     }
     else
     {
         return CL_OUT_OF_RESOURCES;
     }
 }
References CLSymbols::clWaitForEvents_ptr, CLSymbols::get(), and CLSymbols::load_default().
Referenced by CLSymbols::load().