Compute Library: CLFillBorderKernel Class Reference
CLFillBorderKernel Class Reference
Interface for filling the border of a kernel.
#include <CLFillBorderKernel.h>
Public Member Functions
CLFillBorderKernel ()
Default constructor.
CLFillBorderKernel (const CLFillBorderKernel &)=delete
Prevent instances of this class from being copied (As this class contains pointers)
CLFillBorderKernel & operator= (const CLFillBorderKernel &)=delete
Prevent instances of this class from being copied (As this class contains pointers)
CLFillBorderKernel (CLFillBorderKernel &&)=default
Allow instances of this class to be moved.
CLFillBorderKernel & operator= (CLFillBorderKernel &&)=default
Allow instances of this class to be moved.
~CLFillBorderKernel ()=default
Default destructor.
void configure (const CLCompileContext &compile_context, ICLTensor *tensor, BorderSize border_size, BorderMode border_mode, const PixelValue &constant_border_value=PixelValue())
Initialise the kernel's input, output and border mode.
void configure (ICLTensor *tensor, BorderSize border_size, BorderMode border_mode, const PixelValue &constant_border_value=PixelValue())
Initialise the kernel's input, output and border mode.
void configure (const CLCompileContext &compile_context, ITensorInfo *tensor, BorderSize border_size, BorderMode border_mode, const PixelValue &constant_border_value=PixelValue())
Initialise the kernel's input, output and border mode.
template<class T >
void set_constant_border (unsigned int idx, const PixelValue &constant_border_value)
Function to set the constant value on fill border kernel depending on type.
void run_op (ITensorPack &tensors, const Window &window, cl::CommandQueue &queue) override
Enqueue the OpenCL kernel to process the given window on the passed OpenCL command queue.
void run (const Window &window, cl::CommandQueue &queue) override
Enqueue the OpenCL kernel to process the given window on the passed OpenCL command queue.
bool is_parallelisable () const override
Indicates whether or not the kernel is parallelisable.
Public Member Functions inherited from ICLKernel
ICLKernel ()
Constructor.
cl::Kernel & kernel ()
Returns a reference to the OpenCL kernel of this object.
CLKernelType type () const
Returns the CL kernel type.
template<typename T >
void add_1D_array_argument (unsigned int &idx, const ICLArray< T > *array, const Strides &strides, unsigned int num_dimensions, const Window &window)
Add the passed 1D array's parameters to the object's kernel's arguments starting from the index idx.
void add_1D_tensor_argument (unsigned int &idx, const ICLTensor *tensor, const Window &window)
Add the passed 1D tensor's parameters to the object's kernel's arguments starting from the index idx.
void add_1D_tensor_argument_if (bool cond, unsigned int &idx, const ICLTensor *tensor, const Window &window)
Add the passed 1D tensor's parameters to the object's kernel's arguments starting from the index idx if the condition is true.
void add_2D_tensor_argument (unsigned int &idx, const ICLTensor *tensor, const Window &window)
Add the passed 2D tensor's parameters to the object's kernel's arguments starting from the index idx.
void add_2D_tensor_argument_if (bool cond, unsigned int &idx, const ICLTensor *tensor, const Window &window)
Add the passed 2D tensor's parameters to the object's kernel's arguments starting from the index idx if the condition is true.
void add_3D_tensor_argument (unsigned int &idx, const ICLTensor *tensor, const Window &window)
Add the passed 3D tensor's parameters to the object's kernel's arguments starting from the index idx.
void add_4D_tensor_argument (unsigned int &idx, const ICLTensor *tensor, const Window &window)
Add the passed 4D tensor's parameters to the object's kernel's arguments starting from the index idx.
void add_5D_tensor_argument (unsigned int &idx, const ICLTensor *tensor, const Window &window)
Add the passed 5D tensor's parameters to the object's kernel's arguments starting from the index idx.
void add_3d_tensor_nhw_argument (unsigned int &idx, const ICLTensor *tensor)
Add the passed NHW 3D tensor's parameters to the object's kernel's arguments by passing strides, dimensions and the offset to the first valid element in bytes.
void add_4d_tensor_nhwc_argument (unsigned int &idx, const ICLTensor *tensor)
Add the passed NHWC 4D tensor's parameters to the object's kernel's arguments by passing strides, dimensions and the offset to the first valid element in bytes.
template<typename T >
void add_argument (unsigned int &idx, T value)
Add the passed parameters to the object's kernel's arguments starting from the index idx.
void set_lws_hint (const cl::NDRange &lws_hint)
Set the Local-Workgroup-Size hint.
cl::NDRange lws_hint () const
Return the Local-Workgroup-Size hint.
void set_wbsm_hint (const cl_int &wbsm_hint)
Set the workgroup batch size modifier hint.
cl_int wbsm_hint () const
Return the workgroup batch size modifier hint.
const std::string & config_id () const
Get the configuration ID.
void set_target (GPUTarget target)
Set the targeted GPU architecture.
void set_target (cl::Device &device)
Set the targeted GPU architecture according to the CL device.
GPUTarget get_target () const
Get the targeted GPU architecture.
size_t get_max_workgroup_size ()
Get the maximum workgroup size for the device the CLKernelLibrary uses.
cl::NDRange get_cached_gws () const
Get the cached gws used to enqueue this kernel.
void cache_gws (const cl::NDRange &gws)
Cache the latest gws used to enqueue this kernel.
template<unsigned int dimension_size>
void add_tensor_argument (unsigned &idx, const ICLTensor *tensor, const Window &window)
template<typename T , unsigned int dimension_size>
void add_array_argument (unsigned &idx, const ICLArray< T > *array, const Strides &strides, unsigned int num_dimensions, const Window &window)
Add the passed array's parameters to the object's kernel's arguments starting from the index idx.
Public Member Functions inherited from IKernel
IKernel ()
Constructor.
virtual ~IKernel ()=default
Destructor.
virtual BorderSize border_size () const
The size of the border for that kernel.
const Window & window () const
The maximum window the kernel can be executed on.
bool is_window_configured () const
Function to check if the embedded window of this kernel has been configured.
Additional Inherited Members
Static Public Member Functions inherited from ICLKernel
constexpr static unsigned int num_arguments_per_3d_tensor_nhw ()
Returns the number of arguments enqueued per NHW 3D Tensor object.
constexpr static unsigned int num_arguments_per_4d_tensor_nhwc ()
Returns the number of arguments enqueued per NHWC 4D Tensor object.
constexpr static unsigned int num_arguments_per_1D_array ()
Returns the number of arguments enqueued per 1D array object.
constexpr static unsigned int num_arguments_per_1D_tensor ()
Returns the number of arguments enqueued per 1D tensor object.
constexpr static unsigned int num_arguments_per_2D_tensor ()
Returns the number of arguments enqueued per 2D tensor object.
constexpr static unsigned int num_arguments_per_3D_tensor ()
Returns the number of arguments enqueued per 3D tensor object.
constexpr static unsigned int num_arguments_per_4D_tensor ()
Returns the number of arguments enqueued per 4D tensor object.
static cl::NDRange gws_from_window (const Window &window, bool use_dummy_work_items)
Get the global work size given an execution window.
Detailed Description
Interface for filling the border of a kernel.
Definition at line 37 of file CLFillBorderKernel.h.
Constructor & Destructor Documentation
CLFillBorderKernel() [1/3]
CLFillBorderKernel ()
Default constructor.
Definition at line 41 of file CLFillBorderKernel.cpp.
                                        : ICLKernel(), _tensor(nullptr)
 {
     _type = CLKernelType::ELEMENTWISE;
 }
References arm_compute::ELEMENTWISE.
CLFillBorderKernel() [2/3]
CLFillBorderKernel (const CLFillBorderKernel &) delete
Prevent instances of this class from being copied (As this class contains pointers)
CLFillBorderKernel() [3/3]
CLFillBorderKernel (CLFillBorderKernel &&) default
Allow instances of this class to be moved.
~CLFillBorderKernel()
~CLFillBorderKernel () default
Default destructor.
Member Function Documentation
configure() [1/3]
void configure (const CLCompileContext & compile_context, ICLTensor * tensor, BorderSize border_size, BorderMode border_mode, const PixelValue & constant_border_value = PixelValue())
Initialise the kernel's input, output and border mode.
Parameters
[in] compile_context The compile context to be used.
[in,out] tensor Tensor to process Data types supported: U8/QASYMM8/S8/QASYMM8_SIGNED/U16/S16/U32/S32/F16/F32.
[in] border_size Size of the border to fill in elements.
[in] border_mode Border mode to use for the convolution.
[in] constant_border_value (Optional) Constant value to use for borders if border_mode is set to CONSTANT.
Definition at line 67 of file CLFillBorderKernel.cpp.
 {
     _tensor = tensor;
     configure(compile_context, tensor->info(), border_size, border_mode, constant_border_value);
 }
References IKernel::border_size(), and tensor.
Referenced by CLFillBorderKernel::configure(), CLSynthetizeOperatorInitOutputWithZeroAndWithZeroConstantBorder< K, bordersize >::configure(), ClWinogradConv2d::configure(), CLSynthetizeFunctionInitOutputWithZeroAndWithZeroConstantBorder< K, bordersize >::configure(), and arm_compute::test::validation::DATA_TEST_CASE().
configure() [2/3]
void configure (const CLCompileContext & compile_context, ITensorInfo * tensor, BorderSize border_size, BorderMode border_mode, const PixelValue & constant_border_value = PixelValue())
Initialise the kernel's input, output and border mode.
Parameters
[in] compile_context The compile context to be used.
[in,out] tensor Tensor to process Data types supported: U8/QASYMM8/S8/QASYMM8_SIGNED/U16/S16/U32/S32/F16/F32.
[in] border_size Size of the border to fill in elements.
[in] border_mode Border mode to use for the convolution.
[in] constant_border_value (Optional) Constant value to use for borders if border_mode is set to CONSTANT.
Definition at line 77 of file CLFillBorderKernel.cpp.
 {
     ARM_COMPUTE_ERROR_ON(tensor == nullptr);
     ARM_COMPUTE_ERROR_ON(tensor->num_channels() != 1);
     auto padding_info = get_padding_info({tensor});
     border_size.limit(tensor->padding());
     // If there is no border: early exit
     if (border_size.empty() || border_mode == BorderMode::UNDEFINED)
     {
         return;
     }
     // Select appropriate kernel
     std::string kernel_name = "fill_image_borders_" + lower_string(string_from_border_mode(border_mode));
     const DataType dt = tensor->data_type();
     // Define build options
     CLBuildOptions build_opts;
     build_opts.add_option("-DDATA_TYPE=" + get_cl_type_from_data_type(dt));
     build_opts.add_option("-DBORDER_SIZE_TOP=" + support::cpp11::to_string(border_size.top));
     build_opts.add_option("-DBORDER_SIZE_BOTTOM=" + support::cpp11::to_string(border_size.bottom));
     build_opts.add_option("-DBORDER_SIZE_LEFT=" + support::cpp11::to_string(border_size.left));
     build_opts.add_option("-DBORDER_SIZE_RIGHT=" + support::cpp11::to_string(border_size.right));
     // Create kernel
     _kernel = create_kernel(compile_context, kernel_name, build_opts.options());
     // Create static kernel arguments
     const unsigned int valid_width         = tensor->valid_region().shape[0];
     const unsigned int valid_height        = tensor->valid_region().shape[1];
     const cl_int2      valid_region_coords = {{
              static_cast<cl_int>(tensor->valid_region().anchor[0]),
              static_cast<cl_int>(tensor->valid_region().anchor[1]),
     }};
     const unsigned int total_valid_width   = border_size.left + valid_width + border_size.right;
     // Set static kernel arguments
     unsigned int idx = num_arguments_per_3D_tensor(); //Skip the tensor parameters
     ICLKernel::add_argument<cl_uint>(idx, valid_width);
     ICLKernel::add_argument<cl_uint>(idx, valid_height);
     ICLKernel::add_argument<cl_int2>(idx, valid_region_coords);
     if (BorderMode::CONSTANT == border_mode)
     {
         switch (dt)
         {
             case DataType::U8:
             case DataType::QASYMM8:
                 set_constant_border<uint8_t>(idx, constant_border_value);
                 break;
             case DataType::S8:
             case DataType::QASYMM8_SIGNED:
                 set_constant_border<int8_t>(idx, constant_border_value);
                 break;
             case DataType::U16:
                 set_constant_border<uint16_t>(idx, constant_border_value);
                 break;
             case DataType::S16:
                 set_constant_border<int16_t>(idx, constant_border_value);
                 break;
             case DataType::U32:
                 set_constant_border<uint32_t>(idx, constant_border_value);
                 break;
             case DataType::S32:
                 set_constant_border<int32_t>(idx, constant_border_value);
                 break;
             case DataType::F32:
                 static_assert(sizeof(float) == 4, "Float must be 32 bit");
                 set_constant_border<float>(idx, constant_border_value);
                 break;
             case DataType::F16:
                 static_assert(sizeof(cl_half) == sizeof(half), "Half must be same size as cl_half");
                 static_assert(sizeof(cl_half) == 2, "Half must be 16 bit");
                 set_constant_border<half>(idx, constant_border_value);
                 break;
             default:
                 ARM_COMPUTE_ERROR("Not handled");
         }
     }
     // Configure kernel window
     Window win;
     win.set(Window::DimX, Window::Dimension(0, total_valid_width + valid_height));
     win.set(Window::DimY, Window::Dimension(0, 1, 1));
     win.use_tensor_dimensions(tensor->tensor_shape(), Window::DimZ);
     ICLKernel::configure_internal(win);
     // Set config_id for enabling LWS tuning
     _config_id = kernel_name;
     _config_id += "_";
     _config_id += lower_string(string_from_data_type(dt));
     _config_id += "_";
     _config_id += support::cpp11::to_string(tensor->dimension(0));
     _config_id += "_";
     _config_id += support::cpp11::to_string(tensor->dimension(1));
     _config_id += "_";
     _config_id += lower_string(string_from_border_mode(border_mode));
     ARM_COMPUTE_ERROR_ON(has_padding_changed(padding_info));
 }
References CLBuildOptions::add_option(), ARM_COMPUTE_ERROR, ARM_COMPUTE_ERROR_ON, IKernel::border_size(), BorderSize::bottom, arm_compute::CONSTANT, arm_compute::create_kernel(), Window::DimX, Window::DimY, Window::DimZ, dt, BorderSize::empty(), arm_compute::F16, arm_compute::F32, arm_compute::get_cl_type_from_data_type(), arm_compute::get_padding_info(), arm_compute::has_padding_changed(), kernel_name, BorderSize::left, BorderSize::limit(), arm_compute::lower_string(), ICLKernel::num_arguments_per_3D_tensor(), CLBuildOptions::options(), arm_compute::QASYMM8, arm_compute::QASYMM8_SIGNED, BorderSize::right, arm_compute::S16, arm_compute::S32, arm_compute::S8, Window::set(), arm_compute::string_from_border_mode(), arm_compute::string_from_data_type(), tensor, arm_compute::support::cpp11::to_string(), BorderSize::top, arm_compute::U16, arm_compute::U32, arm_compute::U8, arm_compute::UNDEFINED, and Window::use_tensor_dimensions().
configure() [3/3]
void configure (ICLTensor * tensor, BorderSize border_size, BorderMode border_mode, const PixelValue & constant_border_value = PixelValue())
Initialise the kernel's input, output and border mode.
Parameters
[in,out] tensor Tensor to process Data types supported: U8/QASYMM8/S8/QASYMM8_SIGNED/U16/S16/U32/S32/F16/F32.
[in] border_size Size of the border to fill in elements.
[in] border_mode Border mode to use for the convolution.
[in] constant_border_value (Optional) Constant value to use for borders if border_mode is set to CONSTANT.
Definition at line 59 of file CLFillBorderKernel.cpp.
 {
     configure(CLKernelLibrary::get().get_compile_context(), tensor, border_size, border_mode, constant_border_value);
 }
References IKernel::border_size(), CLFillBorderKernel::configure(), CLKernelLibrary::get(), and tensor.
is_parallelisable()
bool is_parallelisable () const override virtual
Indicates whether or not the kernel is parallelisable.
If the kernel is parallelisable then the window returned by window() can be split into sub-windows which can then be run in parallel.
If the kernel is not parallelisable then only the window returned by window() can be passed to run()
Returns
True if the kernel is parallelisable
Reimplemented from IKernel.
Definition at line 46 of file CLFillBorderKernel.cpp.
 {
     return false;
 }
operator=() [1/2]
CLFillBorderKernel& operator= (CLFillBorderKernel &&) default
Allow instances of this class to be moved.
operator=() [2/2]
CLFillBorderKernel& operator= (const CLFillBorderKernel &) delete
Prevent instances of this class from being copied (As this class contains pointers)
run()
void run (const Window & window, cl::CommandQueue & queue) override virtual
Enqueue the OpenCL kernel to process the given window on the passed OpenCL command queue.
Note
The queue is not flushed by this method, and therefore the kernel will not have been executed by the time this method returns.
Parameters
[in] window Region on which to execute the kernel. (Must be a valid region of the window returned by window()).
[in,out] queue Command queue on which to enqueue the kernel.
Reimplemented from ICLKernel.
Definition at line 208 of file CLFillBorderKernel.cpp.
 {
     // Border mode undefined or border width == 0
     if (_kernel() == nullptr)
     {
         return;
     }
     ARM_COMPUTE_ERROR_ON_UNCONFIGURED_KERNEL(this);
     ARM_COMPUTE_ERROR_ON_MISMATCHING_WINDOWS(ICLKernel::window(), window);
     Window collapsed = window.collapse_if_possible(ICLKernel::window(), Window::DimZ);
     Window slice     = collapsed.first_slice_window_3D();
     do
     {
         unsigned int idx = 0;
         add_3D_tensor_argument(idx, _tensor, slice);
         enqueue(queue, *this, slice, lws_hint());
     } while (collapsed.slide_window_slice_3D(slice));
 }
References ICLKernel::add_3D_tensor_argument(), ARM_COMPUTE_ERROR_ON_MISMATCHING_WINDOWS, ARM_COMPUTE_ERROR_ON_UNCONFIGURED_KERNEL, Window::collapse_if_possible(), Window::DimZ, arm_compute::enqueue(), Window::first_slice_window_3D(), ICLKernel::lws_hint(), arm_compute::test::validation::reference::slice(), Window::slide_window_slice_3D(), and IKernel::window().
Referenced by arm_compute::test::validation::DATA_TEST_CASE().
run_op()
void run_op (ITensorPack & tensors, const Window & window, cl::CommandQueue & queue) override virtual
Enqueue the OpenCL kernel to process the given window on the passed OpenCL command queue.
Note
The queue is not flushed by this method, and therefore the kernel will not have been executed by the time this method returns.
Parameters
[in] tensors A vector containing the tensors to operato on.
[in] window Region on which to execute the kernel. (Must be a valid region of the window returned by window()).
[in,out] queue Command queue on which to enqueue the kernel.
Reimplemented from ICLKernel.
Definition at line 183 of file CLFillBorderKernel.cpp.
 {
     // Border mode undefined or border width == 0
     if (_kernel() == nullptr)
     {
         return;
     }
     const auto tensor =
         utils::cast::polymorphic_downcast<const ICLTensor *>(tensors.get_const_tensor(TensorType::ACL_SRC));
     ARM_COMPUTE_ERROR_ON_UNCONFIGURED_KERNEL(this);
     ARM_COMPUTE_ERROR_ON_MISMATCHING_WINDOWS(ICLKernel::window(), window);
     Window collapsed = window.collapse_if_possible(ICLKernel::window(), Window::DimZ);
     Window slice     = collapsed.first_slice_window_3D();
     do
     {
         unsigned int idx = 0;
         add_3D_tensor_argument(idx, tensor, slice);
         enqueue(queue, *this, slice, lws_hint());
     } while (collapsed.slide_window_slice_3D(slice));
 }
References arm_compute::ACL_SRC, ICLKernel::add_3D_tensor_argument(), ARM_COMPUTE_ERROR_ON_MISMATCHING_WINDOWS, ARM_COMPUTE_ERROR_ON_UNCONFIGURED_KERNEL, Window::collapse_if_possible(), Window::DimZ, arm_compute::enqueue(), Window::first_slice_window_3D(), ITensorPack::get_const_tensor(), ICLKernel::lws_hint(), arm_compute::test::validation::reference::slice(), Window::slide_window_slice_3D(), tensor, and IKernel::window().
set_constant_border()
void set_constant_border (unsigned int idx, const PixelValue & constant_border_value)
Function to set the constant value on fill border kernel depending on type.
Parameters
[in] idx Index of the kernel argument to set.
[in] constant_border_value Constant value to use for borders if border_mode is set to CONSTANT.
Definition at line 52 of file CLFillBorderKernel.cpp.
 {
     T value;
     constant_border_value.get(value);
     ICLKernel::add_argument<T>(idx, static_cast<T>(value));
 }
References PixelValue::get().
The documentation for this class was generated from the following files:
src/core/CL/kernels/CLFillBorderKernel.h
src/core/CL/kernels/CLFillBorderKernel.cpp