Compute Library: CLSynthetizeOperatorInitOutputWithZeroAndWithZeroConstantBorder< K, bordersize > Class Template Reference
CLSynthetizeOperatorInitOutputWithZeroAndWithZeroConstantBorder< K, bordersize > Class Template Reference
As above but this also initializes to zero the input tensor.
#include <Helper.h>
Public Member Functions
template<typename T , typename... Args>
void configure (T first, T second, Args &&... args)
Configure the kernel.
void run (ITensorPack &tensors) override final
Run the kernels contained in the function.
Public Member Functions inherited from ICLOperator
ICLOperator (IRuntimeContext *ctx=nullptr)
Constructor.
ICLOperator (const ICLOperator &)=delete
Prevent instances of this class from being copied (As this class contains pointers)
ICLOperator (ICLOperator &&)=default
Default move constructor.
ICLOperator & operator= (const ICLOperator &)=delete
Prevent instances of this class from being copied (As this class contains pointers)
ICLOperator & operator= (ICLOperator &&)=default
Default move assignment operator.
void prepare (ITensorPack &constants) override
Prepare the function for executing.
MemoryRequirements workspace () const override
Return the memory requirements required by the workspace.
Public Member Functions inherited from IOperator
virtual ~IOperator ()=default
Destructor.
Detailed Description
template<typename K, int bordersize>
class arm_compute::test::CLSynthetizeOperatorInitOutputWithZeroAndWithZeroConstantBorder< K, bordersize >
As above but this also initializes to zero the input tensor.
Definition at line 86 of file Helper.h.
Member Function Documentation
configure()
void configure (T first, T second, Args &&... args) inline
Configure the kernel.
Parameters
[in] first First input argument.
[in] second Second input argument.
[in] args Rest of the configuration arguments.
Definition at line 96 of file Helper.h.
     {
         auto cctx = CLKernelLibrary::get().get_compile_context();
         auto k    = std::make_unique<K>();
         k->set_target(CLScheduler::get().target());
         k->configure(cctx, first, second, std::forward<Args>(args)...);
         _kernel = std::move(k);
         _border_handler.configure(cctx, first, BorderSize(bordersize), BorderMode::CONSTANT, PixelValue());
         _fill.configure(cctx, second, PixelValue());
     }
References GemmTuner::args, ClFill::configure(), CLFillBorderKernel::configure(), arm_compute::CONSTANT, CLKernelLibrary::get(), CLScheduler::get(), and CLKernelLibrary::get_compile_context().
run()
void run (ITensorPack & tensors) inline final override virtual
Run the kernels contained in the function.
Parameters
[in] tensors Vector that contains the tensors to operate on.
Reimplemented from ICLOperator.
Definition at line 108 of file Helper.h.
     {
         ARM_COMPUTE_ERROR_ON_MSG(!_kernel, "The CL kernel or function isn't configured");
         ITensorPack fill_pack = { { ACL_SRC, tensors.get_tensor(TensorType::ACL_DST) } };
         _fill.run(fill_pack);
         CLScheduler::get().enqueue_op(_border_handler, tensors);
         CLScheduler::get().enqueue_op(*_kernel, tensors);
     }
References arm_compute::ACL_DST, arm_compute::ACL_SRC, ARM_COMPUTE_ERROR_ON_MSG, CLScheduler::enqueue_op(), CLScheduler::get(), and ICLOperator::run().
The documentation for this class was generated from the following file:
tests/CL/Helper.h