Compute Library: GpuElementwiseBinaryCommon Class Reference
GpuElementwiseBinaryCommon Class Reference final
Operator interface.
#include <GpuElementwiseBinaryCommon.h>
Static Public Member Functions
static ITensorInfo * create_op (GpuWorkloadSketch &sketch, ITensorInfo *lhs, ITensorInfo *rhs, const ElementwiseBinaryCommonAttributes &attributes)
Create an operator and fuse it into the workload sketch.
static Status is_supported_op (const GpuWorkloadContext &context, const ITensorInfo *lhs, const ITensorInfo *rhs, const ElementwiseBinaryCommonAttributes &attributes)
Check if the operator configuration is supported, irrespective of fusion.
static Status validate_op (const GpuWorkloadSketch &sketch, const ITensorInfo *rhs, const ITensorInfo *lhs, const ElementwiseBinaryCommonAttributes &attributes)
Validate the operator and check if it can be fused into the workload sketch.
Detailed Description
Operator interface.
Definition at line 67 of file GpuElementwiseBinaryCommon.h.
Member Function Documentation
create_op()
ITensorInfo * create_op (GpuWorkloadSketch & sketch, ITensorInfo * lhs, ITensorInfo * rhs, const ElementwiseBinaryCommonAttributes & attributes) static
Create an operator and fuse it into the workload sketch.
Note
If validate_op() fails, the creation also fails and may throw an error.
If validate_op() fails, sketch remains unchanged and valid.
Valid data type configurations are checked at the operator level i.e. GpuAdd::validate_op(), GpuSub::validate_op(), ... etc.
Valid data layouts:
Any
Parameters
[in,out] sketch Workload sketch into which the operator will be fused
[in] lhs Left hand side tensor info. Data types supported: U8/S16/S32/F16/F32.
[in] rhs Right hand side tensor info. Data types supported: U8/S16/S32/F16/F32.
[in] attributes ElementwiseBinaryCommonAttributes containing the operator type: ADD, SUB, DIV, ... etc.
Returns
Pointer for the destination tensor info
Definition at line 143 of file GpuElementwiseBinaryCommon.cpp.
 {
     ARM_COMPUTE_ERROR_ON_NULLPTR(lhs, rhs);
     ARM_COMPUTE_LOG_PARAMS(lhs, rhs);
     ARM_COMPUTE_ERROR_THROW_ON(GpuElementwiseBinaryCommon::validate_op(sketch, lhs, rhs, attributes));
     ITensorInfo *dst = sketch.implementation().create_virtual_tensor();
     ARM_COMPUTE_ERROR_ON_NULLPTR(dst);
     // Auto initialize dst tensor
     calculate_and_init_dst_if_empty(dst, lhs, rhs);
     // Translate into components and add to component graph
     auto &comp_graph = sketch.implementation().component_graph();
     const auto sketch_ctx = sketch.implementation().context();
     if (sketch_ctx->gpu_language() == GpuLanguage::OpenCL)
     {
         ARM_COMPUTE_ERROR_ON_NULLPTR(sketch_ctx->cl_compile_context());
         // Add ElementwiseBinary Component
         {
             auto properties = IGpuKernelComponent::Properties();
             properties.stage(UnitWorkloadStage{UnitWorkloadStage::Stage::Run});
             ArgumentPack<ITensorInfo> arguments;
             arguments.add_const_tensor(ACL_SRC_0, lhs);
             arguments.add_const_tensor(ACL_SRC_1, rhs);
             arguments.add_const_tensor(ACL_DST_0, dst);
             comp_graph.add_new_component<ClComponentElementwiseBinary>(properties, arguments, attributes);
         }
     }
     else
     {
         ARM_COMPUTE_ERROR("Unimplemented Gpu language");
     }
     // Set up fusion test by adding to the Operator Group
     // Note this has to be performed after all the components have been successfully added to the component graph
     // Pack tensor infos
     ArgumentPack<ITensorInfo> tensors;
     tensors.add_const_tensor(ACL_SRC_0, lhs);
     tensors.add_const_tensor(ACL_SRC_1, rhs);
     tensors.add_tensor(ACL_DST_0, dst);
     const auto op = sketch.implementation().operator_group().new_operator(operator_type, tensors);
     sketch.implementation().operator_group().add_operator(op);
     return dst;
 }
References arm_compute::ACL_DST_0, arm_compute::ACL_SRC_0, arm_compute::ACL_SRC_1, ArgumentPack< T >::add_const_tensor(), GpuOperatorGroup::add_operator(), ArgumentPack< T >::add_tensor(), ARM_COMPUTE_ERROR, ARM_COMPUTE_ERROR_ON_NULLPTR, ARM_COMPUTE_ERROR_THROW_ON, ARM_COMPUTE_LOG_PARAMS, GpuWorkloadSketch::Implementation::component_graph(), GpuWorkloadSketch::Implementation::context(), GpuWorkloadSketch::Implementation::create_virtual_tensor(), arm_compute::test::validation::dst, GpuWorkloadSketch::implementation(), GpuOperatorGroup::new_operator(), arm_compute::experimental::dynamic_fusion::OpenCL, GpuWorkloadSketch::Implementation::operator_group(), UnitWorkloadStage::Run, arm_compute::test::validation::sketch, and GpuElementwiseBinaryCommon::validate_op().
Referenced by GpuMul::create_op(), GpuSub::create_op(), and GpuAdd::create_op().
is_supported_op()
Status is_supported_op (const GpuWorkloadContext & context, const ITensorInfo * lhs, const ITensorInfo * rhs, const ElementwiseBinaryCommonAttributes & attributes) static
Check if the operator configuration is supported, irrespective of fusion.
Parameters
[in] context Workload context within which the operator is running
[in] lhs Left hand side tensor info. Data types supported: U8/S16/S32/F16/F32.
[in] rhs Right hand side tensor info. Data types supported: U8/S16/S32/F16/F32.
[in] attributes ElementwiseBinaryCommonAttributes containing the operator type: ADD, SUB, DIV, ... etc.
Returns
Status
Definition at line 107 of file GpuElementwiseBinaryCommon.cpp.
 {
     return is_supported_op_helper(context, lhs, rhs, nullptr, attributes);
 }
References arm_compute::test::validation::context.
Referenced by GpuMul::is_supported_op(), GpuAdd::is_supported_op(), and GpuSub::is_supported_op().
validate_op()
Status validate_op (const GpuWorkloadSketch & sketch, const ITensorInfo * rhs, const ITensorInfo * lhs, const ElementwiseBinaryCommonAttributes & attributes) static
Validate the operator and check if it can be fused into the workload sketch.
Parameters are similar to GpuElementwiseBinaryCommon::create_op()
Returns
Status
Definition at line 115 of file GpuElementwiseBinaryCommon.cpp.
 {
     ARM_COMPUTE_RETURN_ERROR_ON_NULLPTR(lhs, rhs);
     ARM_COMPUTE_RETURN_ERROR_ON(!lhs->has_valid_id() || !rhs->has_valid_id());
     // Refer to GpuConv2d::validate_op() for id-validness of this TensorInfo object
     TensorInfo dst_info_to_validate;
     // Auto initialize dst tensor info
     calculate_and_init_dst_if_empty(&dst_info_to_validate, lhs, rhs);
     // Perform fusion test
     // Pack tensor infos
     ArgumentPack<ITensorInfo> tensors;
     tensors.add_const_tensor(ACL_SRC_0, lhs);
     tensors.add_const_tensor(ACL_SRC_1, rhs);
     tensors.add_const_tensor(ACL_DST_0, &dst_info_to_validate);
     const auto op = sketch.implementation().operator_group().new_operator(operator_type, tensors);
     ARM_COMPUTE_RETURN_ERROR_ON_MSG(!sketch.implementation().operator_group().try_add_operator(op),
                                     "Operator fusion test failed. This operator cannot be fused into the workload");
     // Check if configuration is supported
     return is_supported_op_helper(*sketch.gpu_context(), lhs, rhs, &dst_info_to_validate, attributes);
 }
References arm_compute::ACL_DST_0, arm_compute::ACL_SRC_0, arm_compute::ACL_SRC_1, ArgumentPack< T >::add_const_tensor(), ARM_COMPUTE_RETURN_ERROR_ON, ARM_COMPUTE_RETURN_ERROR_ON_MSG, ARM_COMPUTE_RETURN_ERROR_ON_NULLPTR, GpuWorkloadSketch::gpu_context(), ITensorInfo::has_valid_id(), GpuWorkloadSketch::implementation(), GpuOperatorGroup::new_operator(), GpuWorkloadSketch::Implementation::operator_group(), arm_compute::test::validation::sketch, and GpuOperatorGroup::try_add_operator().
Referenced by GpuElementwiseBinaryCommon::create_op(), GpuMul::validate_op(), GpuAdd::validate_op(), and GpuSub::validate_op().
The documentation for this class was generated from the following files:
src/dynamic_fusion/sketch/gpu/operators/internal/GpuElementwiseBinaryCommon.h
src/dynamic_fusion/sketch/gpu/operators/internal/GpuElementwiseBinaryCommon.cpp