Compute Library: CpuGemmLowpOutputStage Class Reference
CpuGemmLowpOutputStage Class Reference
Basic function to execute GEMMLowpQuantizeDown kernels.
#include <CpuGemmLowpOutputStage.h>
Public Member Functions
void configure (ITensorInfo *src, ITensorInfo *bias, ITensorInfo *dst, const GEMMLowpOutputStageInfo &info)
Initialise the kernel's inputs, output.
void run (ITensorPack &tensors) override
Run the kernels contained in the function.
Public Member Functions inherited from INEOperator
INEOperator (IRuntimeContext *ctx=nullptr)
Constructor.
INEOperator (const INEOperator &)=delete
Prevent instances of this class from being copied (As this class contains pointers)
INEOperator (INEOperator &&)=default
Default move constructor.
INEOperator & operator= (const INEOperator &)=delete
Prevent instances of this class from being copied (As this class contains pointers)
INEOperator & operator= (INEOperator &&)=default
Default move assignment operator.
~INEOperator ()
Default destructor.
void prepare (ITensorPack &constants) override
Prepare the function for executing.
MemoryRequirements workspace () const override
Return the memory requirements required by the workspace.
Public Member Functions inherited from IOperator
virtual ~IOperator ()=default
Destructor.
Static Public Member Functions
static Status validate (const ITensorInfo *src, const ITensorInfo *bias, const ITensorInfo *dst, const GEMMLowpOutputStageInfo &info)
Static function to check if given info will lead to a valid configuration.
Detailed Description
Basic function to execute GEMMLowpQuantizeDown kernels.
This function calls the following kernels:
kernels::CpuGemmLowpQuantizeDownInt32ScaleKernel
kernels::CpuGemmLowpQuantizeDownInt32ToUint8ScaleByFixedPointKernel
kernels::CpuGemmLowpQuantizeDownInt32ToInt8ScaleByFixedPointKernel
kernels::CpuGemmLowpQuantizeDownInt32ToInt16ScaleByFixedPointKernel
Definition at line 52 of file CpuGemmLowpOutputStage.h.
Member Function Documentation
configure()
void configure (ITensorInfo * src, ITensorInfo * bias, ITensorInfo * dst, const GEMMLowpOutputStageInfo & info)
Initialise the kernel's inputs, output.
Valid data layouts:
All
Valid data type configurations:
src0 src1 dst
S32 S32 QASYMM8
S32 S32 QASYMM8_SIGNED
S32 S32 QSYMM16
Parameters
[in] src Input tensor info. Data type supported: S32
[in] bias Biases tensor info. Only shared biases supported and it can be a nullptr if the biases addition is not required. Biases are 1D tensor with dimensions [OFM]. Data type supported: Same as input.
[out] dst Output tensor info. Data type supported: Data type supported: QASYMM8/QASYMM8_SIGNED/QSYMM16
[in] info GEMMLowp output stage metadata.
Definition at line 40 of file CpuGemmLowpOutputStage.cpp.
 {
     // Perform validate step
     ARM_COMPUTE_ERROR_THROW_ON(CpuGemmLowpOutputStage::validate(src, bias, dst, info));
     ARM_COMPUTE_LOG_PARAMS(src, bias, dst, info);
     switch (info.type)
     {
         case GEMMLowpOutputStageType::QUANTIZE_DOWN_FIXEDPOINT:
         {
             switch (info.output_data_type)
             {
                 case DataType::QASYMM8:
                 {
                     auto k = std::make_unique<kernels::CpuGemmLowpQuantizeDownInt32ToUint8ScaleByFixedPointKernel>();
                     k->configure(src, bias, dst, info.gemmlowp_multiplier, info.gemmlowp_shift, info.gemmlowp_offset,
                                  info.gemmlowp_min_bound, info.gemmlowp_max_bound);
                     _kernel = std::move(k);
                     break;
                 }
                 case DataType::QASYMM8_SIGNED:
                 {
                     auto k = std::make_unique<kernels::CpuGemmLowpQuantizeDownInt32ToInt8ScaleByFixedPointKernel>();
                     k->configure(src, bias, dst, info.gemmlowp_multiplier, info.gemmlowp_shift, info.gemmlowp_offset,
                                  info.gemmlowp_min_bound, info.gemmlowp_max_bound);
                     _kernel = std::move(k);
                     break;
                 }
                 case DataType::QSYMM16:
                 {
                     auto k = std::make_unique<kernels::CpuGemmLowpQuantizeDownInt32ToInt16ScaleByFixedPointKernel>();
                     k->configure(src, bias, dst, info.gemmlowp_multiplier, info.gemmlowp_shift, info.gemmlowp_min_bound,
                                  info.gemmlowp_max_bound);
                     _kernel = std::move(k);
                     break;
                 }
                 default:
                 {
                     ARM_COMPUTE_ERROR("Unsupported output data type.");
                     break;
                 }
             }
             break;
         }
         case GEMMLowpOutputStageType::QUANTIZE_DOWN:
         {
             switch (info.output_data_type)
             {
                 case DataType::QASYMM8:
                 case DataType::QASYMM8_SIGNED:
                 {
                     auto k = std::make_unique<kernels::CpuGemmLowpQuantizeDownInt32ScaleKernel>();
                     k->configure(src, bias, dst, &info);
                     _kernel = std::move(k);
                     break;
                 }
                 default:
                 {
                     ARM_COMPUTE_ERROR("Unsupported output data type.");
                     break;
                 }
             }
             break;
         }
         default:
             ARM_COMPUTE_ERROR("Unsupported GEMMLowpOutputStage type.");
     }
 }
References ARM_COMPUTE_ERROR, ARM_COMPUTE_ERROR_THROW_ON, ARM_COMPUTE_LOG_PARAMS, bias, arm_compute::test::validation::dst, arm_compute::test::validation::info, arm_compute::QASYMM8, arm_compute::QASYMM8_SIGNED, arm_compute::QSYMM16, arm_compute::QUANTIZE_DOWN, arm_compute::QUANTIZE_DOWN_FIXEDPOINT, arm_compute::test::validation::src, and CpuGemmLowpOutputStage::validate().
run()
void run (ITensorPack & tensors) override virtual
Run the kernels contained in the function.
Parameters
[in] tensors Vector that contains the tensors to operate on.
Reimplemented from INEOperator.
Definition at line 160 of file CpuGemmLowpOutputStage.cpp.
 {
     NEScheduler::get().schedule_op(_kernel.get(), Window::DimY, _kernel->window(), tensors);
 }
References Window::DimY, Scheduler::get(), and IScheduler::schedule_op().
validate()
Status validate (const ITensorInfo * src, const ITensorInfo * bias, const ITensorInfo * dst, const GEMMLowpOutputStageInfo & info) static
Static function to check if given info will lead to a valid configuration.
Similar to CpuGemmLowpOutputStage::configure()
Returns
a status
Definition at line 112 of file CpuGemmLowpOutputStage.cpp.
 {
     ARM_COMPUTE_RETURN_ERROR_ON_NULLPTR(src, dst);
     ARM_COMPUTE_RETURN_ERROR_ON_MSG(dst->data_type() == DataType::UNKNOWN,
                                     "CpuGemmLowpOutputStage cannot be used with UNKNOWN output data type.");
     ARM_COMPUTE_RETURN_ERROR_ON_DATA_TYPE_CHANNEL_NOT_IN(dst, 1, DataType::QASYMM8, DataType::QASYMM8_SIGNED,
                                                          DataType::QSYMM16);
     ARM_COMPUTE_RETURN_ERROR_ON((info.type != GEMMLowpOutputStageType::QUANTIZE_DOWN) &&
                                 (info.type != GEMMLowpOutputStageType::QUANTIZE_DOWN_FIXEDPOINT));
     switch (info.type)
     {
         case GEMMLowpOutputStageType::QUANTIZE_DOWN_FIXEDPOINT:
         {
             switch (dst->data_type())
             {
                 case DataType::QASYMM8:
                     return kernels::CpuGemmLowpQuantizeDownInt32ToUint8ScaleByFixedPointKernel::validate(
                         src, bias, dst, info.gemmlowp_min_bound, info.gemmlowp_max_bound);
                 case DataType::QASYMM8_SIGNED:
                     return kernels::CpuGemmLowpQuantizeDownInt32ToInt8ScaleByFixedPointKernel::validate(
                         src, bias, dst, info.gemmlowp_min_bound, info.gemmlowp_max_bound);
                 case DataType::QSYMM16:
                     return kernels::CpuGemmLowpQuantizeDownInt32ToInt16ScaleByFixedPointKernel::validate(
                         src, bias, dst, info.gemmlowp_min_bound, info.gemmlowp_max_bound);
                 default:
                     return ARM_COMPUTE_CREATE_ERROR(ErrorCode::RUNTIME_ERROR, "Unsupported output data type.");
             }
         }
         case GEMMLowpOutputStageType::QUANTIZE_DOWN:
         {
             switch (dst->data_type())
             {
                 case DataType::QASYMM8:
                 case DataType::QASYMM8_SIGNED:
                     return kernels::CpuGemmLowpQuantizeDownInt32ScaleKernel::validate(src, bias, dst, &info);
                 default:
                     return ARM_COMPUTE_CREATE_ERROR(ErrorCode::RUNTIME_ERROR, "Unsupported output data type.");
             }
         }
         default:
             return ARM_COMPUTE_CREATE_ERROR(ErrorCode::RUNTIME_ERROR, "Unsupported GEMMLowpOutputStage type.");
     }
 }
References ARM_COMPUTE_CREATE_ERROR, ARM_COMPUTE_RETURN_ERROR_ON, ARM_COMPUTE_RETURN_ERROR_ON_DATA_TYPE_CHANNEL_NOT_IN, ARM_COMPUTE_RETURN_ERROR_ON_MSG, ARM_COMPUTE_RETURN_ERROR_ON_NULLPTR, bias, arm_compute::test::validation::dst, arm_compute::test::validation::info, arm_compute::QASYMM8, arm_compute::QASYMM8_SIGNED, arm_compute::QSYMM16, arm_compute::QUANTIZE_DOWN, arm_compute::QUANTIZE_DOWN_FIXEDPOINT, arm_compute::RUNTIME_ERROR, arm_compute::test::validation::src, arm_compute::UNKNOWN, CpuGemmLowpQuantizeDownInt32ScaleKernel::validate(), CpuGemmLowpQuantizeDownInt32ToInt16ScaleByFixedPointKernel::validate(), CpuGemmLowpQuantizeDownInt32ToUint8ScaleByFixedPointKernel::validate(), and CpuGemmLowpQuantizeDownInt32ToInt8ScaleByFixedPointKernel::validate().
Referenced by CpuGemmLowpOutputStage::configure(), and NEGEMMLowpOutputStage::validate().
The documentation for this class was generated from the following files:
src/cpu/operators/CpuGemmLowpOutputStage.h
src/cpu/operators/CpuGemmLowpOutputStage.cpp