Compute Library: ValidationInputAccessor Class Reference
ValidationInputAccessor Class Reference final
Input Accessor used for network validation.
#include <GraphUtils.h>
Public Member Functions
ValidationInputAccessor (const std::string &image_list, std::string images_path, std::unique_ptr< IPreprocessor > preprocessor=nullptr, bool bgr=true, unsigned int start=0, unsigned int end=0, std::ostream &output_stream=std::cout)
Constructor.
bool access_tensor (ITensor &tensor) override
Interface to be implemented to access a given tensor.
Public Member Functions inherited from ITensorAccessor
virtual ~ITensorAccessor ()=default
Default virtual destructor.
virtual bool access_tensor_data ()
Returns true if the tensor data is being accessed.
Detailed Description
Input Accessor used for network validation.
Definition at line 259 of file GraphUtils.h.
Constructor & Destructor Documentation
ValidationInputAccessor()
ValidationInputAccessor (const std::string & image_list, std::string images_path, std::unique_ptr< IPreprocessor > preprocessor = nullptr, bool bgr = true, unsigned int start = 0, unsigned int end = 0, std::ostream & output_stream = std::cout)
Constructor.
Parameters
[in] image_list File containing all the images to validate
[in] images_path Path to images.
[in] bgr (Optional) Fill the first plane with blue channel (default = false - RGB format)
[in] preprocessor (Optional) Image pre-processing object (default = nullptr)
[in] start (Optional) Start range
[in] end (Optional) End range
[out] output_stream (Optional) Output stream
Note
Range is defined as [start, end]
Definition at line 315 of file GraphUtils.cpp.
     : _path(std::move(images_path)),
       _images(),
       _preprocessor(std::move(preprocessor)),
       _bgr(bgr),
       _offset(0),
       _output_stream(output_stream)
 {
     ARM_COMPUTE_EXIT_ON_MSG(start > end, "Invalid validation range!");
     std::ifstream ifs;
     try
     {
         ifs.exceptions(std::ifstream::badbit);
         ifs.open(image_list, std::ios::in | std::ios::binary);
         // Parse image names
         unsigned int counter = 0;
         for (std::string line; !std::getline(ifs, line).fail() && counter <= end; ++counter)
         {
             // Add image to process if withing range
             if (counter >= start)
             {
                 std::stringstream linestream(line);
                 std::string       image_name;
                 linestream >> image_name;
                 _images.emplace_back(std::move(image_name));
             }
         }
     }
     catch (const std::ifstream::failure &e)
     {
         ARM_COMPUTE_ERROR_VAR("Accessing %s: %s", image_list.c_str(), e.what());
     }
 }
References ARM_COMPUTE_ERROR_VAR, ARM_COMPUTE_EXIT_ON_MSG, and arm_compute::mlgo::parser::end().
Member Function Documentation
access_tensor()
bool access_tensor (ITensor & tensor) override virtual
Interface to be implemented to access a given tensor.
Parameters
[in] tensor Tensor to be accessed
Returns
True if access is successful else false
Implements ITensorAccessor.
Definition at line 358 of file GraphUtils.cpp.
 {
     bool ret = _offset < _images.size();
     if (ret)
     {
         utils::JPEGLoader jpeg;
         // Open JPEG file
         std::string image_name = _path + _images[_offset++];
         jpeg.open(image_name);
         _output_stream << "[" << _offset << "/" << _images.size() << "] Validating " << image_name << std::endl;
         // Get permutated shape and permutation parameters
         TensorShape                    permuted_shape = tensor.info()->tensor_shape();
         arm_compute::PermutationVector perm;
         if (tensor.info()->data_layout() != DataLayout::NCHW)
         {
             std::tie(permuted_shape, perm) =
                 compute_permutation_parameters(tensor.info()->tensor_shape(), tensor.info()->data_layout());
         }
 #ifdef __arm__
         ARM_COMPUTE_EXIT_ON_MSG_VAR(jpeg.width() != permuted_shape.x() || jpeg.height() != permuted_shape.y(),
                                     "Failed to load image file: dimensions [%d,%d] not correct, expected [%" PRIu32
                                     ",%" PRIu32 "].",
                                     jpeg.width(), jpeg.height(), permuted_shape.x(), permuted_shape.y());
 #else  // __arm__
         ARM_COMPUTE_EXIT_ON_MSG_VAR(jpeg.width() != permuted_shape.x() || jpeg.height() != permuted_shape.y(),
                                     "Failed to load image file: dimensions [%d,%d] not correct, expected [%" PRIu64
                                     ",%" PRIu64 "].",
                                     jpeg.width(), jpeg.height(), static_cast<uint64_t>(permuted_shape.x()),
                                     static_cast<uint64_t>(permuted_shape.y()));
 #endif // __arm__
         // Fill the tensor with the JPEG content (BGR)
         jpeg.fill_planar_tensor(tensor, _bgr);
         // Preprocess tensor
         if (_preprocessor)
         {
             _preprocessor->preprocess(tensor);
         }
     }
     return ret;
 }
References ARM_COMPUTE_EXIT_ON_MSG_VAR, IImageLoader::fill_planar_tensor(), IImageLoader::height(), arm_compute::NCHW, JPEGLoader::open(), tensor, IImageLoader::width(), Dimensions< T >::x(), and Dimensions< T >::y().
The documentation for this class was generated from the following files:
utils/GraphUtils.h
utils/GraphUtils.cpp