Compute Library: GpuSoftmax Class Reference
GpuSoftmax Class Reference final
Operator interface.
#include <GpuSoftmax.h>
Public Types
using Attributes = SoftmaxAttributes
Attributes are a set of backend-agnostic parameters that define what an operator does.
Static Public Member Functions
static void create_op (GpuWorkloadSketch &sketch, ITensorInfo *src, ITensorInfo *dst, const Attributes &attributes)
Create an operator and fuse it into the workload sketch.
static Status is_supported_op (const GpuWorkloadContext &context, const ITensorInfo *src, const ITensorInfo *dst, const Attributes &attributes)
Check if the operator configuration is supported, irrespective of fusion.
static Status validate_op (const GpuWorkloadSketch &sketch, const ITensorInfo *src, const ITensorInfo *dst, const Attributes &attributes)
Validate the operator and check if the its configuration is supported and if it can be fused into the workload sketch.
Detailed Description
Operator interface.
Definition at line 41 of file GpuSoftmax.h.
Member Typedef Documentation
Attributes
using Attributes = SoftmaxAttributes
Attributes are a set of backend-agnostic parameters that define what an operator does.
Definition at line 45 of file GpuSoftmax.h.
Member Function Documentation
create_op()
void create_op (GpuWorkloadSketch & sketch, ITensorInfo * src, ITensorInfo * dst, const Attributes & attributes) static
Create an operator and fuse it into the workload sketch.
Note
If validate_op() fails, the creation also fails and may throw an error.
If validate_op() fails, sketch remains unchanged and valid.
Valid data type configurations:
src dst
F16 F16
F32 F32
Valid data layouts:
All
Parameters
[in,out] sketch Workload sketch into which the operator will be fused
[in] src Source tensor info.
[in] dst Destination tensor info.
[in] attributes Operator attributes
Definition at line 136 of file GpuSoftmax.cpp.
 {
     ARM_COMPUTE_ERROR_ON_NULLPTR(src, dst);
     ARM_COMPUTE_LOG_PARAMS(src, dst, attributes);
     TensorShape  logits_sum_shape = src->tensor_shape();
     ITensorInfo *logits           = sketch.implementation().create_auxiliary_tensor(
                   src->clone()->set_id(ITensorInfo::invalid_tensor_id).set_tensor_shape(logits_sum_shape));
     logits_sum_shape.set(0, 1);
     ITensorInfo *sum = sketch.implementation().create_auxiliary_tensor(
         src->clone()->set_id(ITensorInfo::invalid_tensor_id).set_tensor_shape(logits_sum_shape));
     // Auto initialize dst tensor info and the auxiliary tensor infos as well
     auto_init_if_empty(*dst, *src->clone());
     // Assert validation
     ARM_COMPUTE_ERROR_THROW_ON(GpuSoftmax::validate_op(sketch, src, dst, attributes));
     ARM_COMPUTE_ERROR_ON_NULLPTR(logits, sum);
     // Translate into components and add to component graph
     auto      &comp_graph = sketch.implementation().component_graph();
     const auto sketch_ctx = sketch.implementation().context();
     if (sketch_ctx->gpu_language() == GpuLanguage::OpenCL)
     {
         const auto cl_compile_ctx = sketch_ctx->cl_compile_context();
         ARM_COMPUTE_UNUSED(cl_compile_ctx);
         ARM_COMPUTE_ERROR_ON(cl_compile_ctx == nullptr);
         // Add Direct Conv2d Component
         {
             auto properties = IGpuKernelComponent::Properties();
             properties.stage(UnitWorkloadStage{UnitWorkloadStage::Stage::Run});
             ArgumentPack<ITensorInfo> arguments_exp_sum;
             ArgumentPack<ITensorInfo> arguments_norm;
             arguments_exp_sum.add_const_tensor(ACL_SRC_0, src);
             arguments_exp_sum.add_const_tensor(ACL_DST_0, sum);
             arguments_exp_sum.add_const_tensor(ACL_DST_1, logits);
             arguments_norm.add_const_tensor(ACL_SRC_0, logits);
             arguments_norm.add_const_tensor(ACL_SRC_1, sum);
             arguments_norm.add_const_tensor(ACL_DST_0, dst);
             comp_graph.add_new_component<ClComponentLogits1DMaxShiftExpSum>(properties, arguments_exp_sum, attributes);
             comp_graph.add_new_component<ClComponentLogits1DNorm>(properties, arguments_norm, attributes);
         }
     }
     else
     {
         ARM_COMPUTE_ERROR("Unimplemented Gpu language");
     }
     // Set up fusion test by adding to the Operator Group
     // Note this has to be performed after all the components have been successfully added to the component graph
     // Pack tensor infos
     ArgumentPack<ITensorInfo> tensors;
     tensors.add_const_tensor(ACL_SRC_0, src);
     tensors.add_const_tensor(ACL_DST_0, dst);
     const auto op = sketch.implementation().operator_group().new_operator(operator_type, tensors);
     sketch.implementation().operator_group().add_operator(op);
 }
References arm_compute::ACL_DST_0, arm_compute::ACL_DST_1, arm_compute::ACL_SRC_0, arm_compute::ACL_SRC_1, ArgumentPack< T >::add_const_tensor(), GpuOperatorGroup::add_operator(), ARM_COMPUTE_ERROR, ARM_COMPUTE_ERROR_ON, ARM_COMPUTE_ERROR_ON_NULLPTR, ARM_COMPUTE_ERROR_THROW_ON, ARM_COMPUTE_LOG_PARAMS, ARM_COMPUTE_UNUSED, arm_compute::auto_init_if_empty(), GpuWorkloadContext::cl_compile_context(), GpuWorkloadSketch::Implementation::component_graph(), GpuWorkloadSketch::Implementation::context(), GpuWorkloadSketch::Implementation::create_auxiliary_tensor(), arm_compute::test::validation::dst, GpuWorkloadSketch::implementation(), ITensorInfo::invalid_tensor_id, GpuOperatorGroup::new_operator(), arm_compute::experimental::dynamic_fusion::OpenCL, GpuWorkloadSketch::Implementation::operator_group(), UnitWorkloadStage::Run, TensorShape::set(), arm_compute::test::validation::sketch, arm_compute::test::validation::src, and GpuSoftmax::validate_op().
is_supported_op()
Status is_supported_op (const GpuWorkloadContext & context, const ITensorInfo * src, const ITensorInfo * dst, const Attributes & attributes) static
Check if the operator configuration is supported, irrespective of fusion.
Parameters
[in] context Workload context within which the operator is running
[in] src Source tensor info.
[in] dst Destination tensor info.
[in] attributes Operator attributes
Returns
Status
Definition at line 47 of file GpuSoftmax.cpp.
 {
     ARM_COMPUTE_RETURN_ERROR_ON_NULLPTR(src, dst);
     TensorInfo dst_info_to_validate;
     // Auto initialize dst tensor info
     if (dst != nullptr)
     {
         dst_info_to_validate = *dst;
     }
     else
     {
         auto_init_if_empty(dst_info_to_validate, *src->clone());
     }
     // Check components
     if (context.gpu_language() == GpuLanguage::OpenCL)
     {
         const auto cl_compile_ctx = context.cl_compile_context();
         ARM_COMPUTE_RETURN_ERROR_ON(cl_compile_ctx == nullptr);
         const KernelProperties properties =
             IGpuKernelComponent::Properties().stage(UnitWorkloadStage{UnitWorkloadStage::Stage::Run});
         TensorShape logits_sum_shape = src->tensor_shape();
         TensorInfo  logits(src->clone()->set_tensor_shape(logits_sum_shape));
         // The sum tensor dim0 only need one element
         logits_sum_shape.set(0, 1);
         TensorInfo sum(src->clone()->set_tensor_shape(logits_sum_shape));
         // Validate Component
         ArgumentPack<ITensorInfo> arguments_exp_sum;
         ArgumentPack<ITensorInfo> arguments_norm;
         arguments_exp_sum.add_const_tensor(ACL_SRC_0, src);
         arguments_exp_sum.add_const_tensor(ACL_DST_0, &sum);
         arguments_exp_sum.add_const_tensor(ACL_DST_1, &logits);
         arguments_norm.add_const_tensor(ACL_SRC_0, &logits);
         arguments_norm.add_const_tensor(ACL_SRC_1, &sum);
         arguments_norm.add_const_tensor(ACL_DST_0, &dst_info_to_validate);
         ARM_COMPUTE_RETURN_ON_ERROR(
             ClComponentLogits1DMaxShiftExpSum::validate(properties, arguments_exp_sum, attributes));
         ARM_COMPUTE_RETURN_ON_ERROR(ClComponentLogits1DNorm::validate(properties, arguments_norm, attributes));
     }
     else
     {
         ARM_COMPUTE_RETURN_ERROR_MSG("Unimplemented Gpu language");
     }
     return Status{};
 }
References arm_compute::ACL_DST_0, arm_compute::ACL_DST_1, arm_compute::ACL_SRC_0, arm_compute::ACL_SRC_1, ArgumentPack< T >::add_const_tensor(), ARM_COMPUTE_RETURN_ERROR_MSG, ARM_COMPUTE_RETURN_ERROR_ON, ARM_COMPUTE_RETURN_ERROR_ON_NULLPTR, ARM_COMPUTE_RETURN_ON_ERROR, arm_compute::auto_init_if_empty(), arm_compute::test::validation::context, arm_compute::test::validation::dst, arm_compute::experimental::dynamic_fusion::OpenCL, UnitWorkloadStage::Run, TensorShape::set(), arm_compute::test::validation::src, KernelProperties::stage(), ClComponentLogits1DNorm::validate(), and ClComponentLogits1DMaxShiftExpSum::validate().
Referenced by GpuSoftmax::validate_op().
validate_op()
Status validate_op (const GpuWorkloadSketch & sketch, const ITensorInfo * src, const ITensorInfo * dst, const Attributes & attributes) static
Validate the operator and check if the its configuration is supported and if it can be fused into the workload sketch.
Similar to GpuSoftmax::create_op()
Returns
a status
Definition at line 103 of file GpuSoftmax.cpp.
 {
     ARM_COMPUTE_RETURN_ERROR_ON_NULLPTR(src, dst);
     ARM_COMPUTE_RETURN_ERROR_ON(!src->has_valid_id() || !dst->has_valid_id());
     ARM_COMPUTE_RETURN_ERROR_ON_MSG(src->num_dimensions() > 4, "Only up to 4 dimensions are supported");
     ARM_COMPUTE_RETURN_ERROR_ON(attributes.axis() < static_cast<int32_t>(-src->num_dimensions()) ||
                                 static_cast<int32_t>(src->num_dimensions()) <= attributes.axis());
     // Auto initialize dst tensor info
     TensorInfo dst_info_to_validate = *dst;
     auto_init_if_empty(dst_info_to_validate, *src->clone());
     const size_t actual_axis =
         static_cast<size_t>(wrap_around(attributes.axis(), static_cast<int32_t>(src->num_dimensions())));
     const bool needs_permute = actual_axis != 0;
     ARM_COMPUTE_RETURN_ERROR_ON_MSG(needs_permute, "Dynamic fusion softmax on axis!=0 not supported yet.");
     // Perform fusion test and check if the operator meets the fusion constraints
     ArgumentPack<ITensorInfo> tensors;
     tensors.add_const_tensor(ACL_SRC_0, src);
     tensors.add_const_tensor(ACL_DST_0, &dst_info_to_validate);
     const auto op = sketch.implementation().operator_group().new_operator(operator_type, tensors);
     ARM_COMPUTE_RETURN_ERROR_ON_MSG(!sketch.implementation().operator_group().try_add_operator(op),
                                     "Operator fusion test failed. This operator cannot be fused into the workload");
     // Check if configuration is supported
     return is_supported_op(*sketch.gpu_context(), src, &dst_info_to_validate, attributes);
 }
References arm_compute::ACL_DST_0, arm_compute::ACL_SRC_0, ArgumentPack< T >::add_const_tensor(), ARM_COMPUTE_RETURN_ERROR_ON, ARM_COMPUTE_RETURN_ERROR_ON_MSG, ARM_COMPUTE_RETURN_ERROR_ON_NULLPTR, arm_compute::auto_init_if_empty(), SoftmaxAttributes::axis(), arm_compute::test::validation::dst, GpuWorkloadSketch::gpu_context(), GpuWorkloadSketch::implementation(), GpuSoftmax::is_supported_op(), GpuOperatorGroup::new_operator(), GpuWorkloadSketch::Implementation::operator_group(), arm_compute::test::validation::sketch, arm_compute::test::validation::src, GpuOperatorGroup::try_add_operator(), and arm_compute::wrap_around().
Referenced by GpuSoftmax::create_op().
The documentation for this class was generated from the following files:
arm_compute/dynamic_fusion/sketch/gpu/operators/GpuSoftmax.h
src/dynamic_fusion/sketch/gpu/operators/GpuSoftmax.cpp