Compute Library: GpuLogicalKernel Class Reference
GpuLogicalKernel Class Reference
A wrapper-processor of a GpuKernelComponentGroup It adds the load (if any) and store components to the component group The GpuLogicalKernel represents a complete kernel, and can proceed to invoke any kernel writer to generate the full kernel code.
#include <GpuLogicalKernel.h>
Public Member Functions
GpuLogicalKernel (GpuComponentServices *services, const GpuKernelComponentGroup &components)
Constructor.
GpuLogicalKernel (const GpuLogicalKernel &)=default
Allow instances of this class to be copy constructed.
GpuLogicalKernel & operator= (const GpuLogicalKernel &)=default
Allow instances of this class to be copied.
GpuLogicalKernel (GpuLogicalKernel &&)=default
Allow instances of this class to be move constructed.
GpuLogicalKernel & operator= (GpuLogicalKernel &&)=default
Allow instances of this class to be moved.
GpuKernelSourceCode write_kernel_code ()
Generate a GpuKernelSourceCode.
Detailed Description
A wrapper-processor of a GpuKernelComponentGroup It adds the load (if any) and store components to the component group The GpuLogicalKernel represents a complete kernel, and can proceed to invoke any kernel writer to generate the full kernel code.
Definition at line 47 of file GpuLogicalKernel.h.
Constructor & Destructor Documentation
GpuLogicalKernel() [1/3]
GpuLogicalKernel (GpuComponentServices * services, const GpuKernelComponentGroup & components) explicit
Constructor.
Parameters
[in] services GpuComponentServices to be used
[in] components Component group from which this logical kernel is initialized
Definition at line 44 of file GpuLogicalKernel.cpp.
     : _comp_group{components}, _store_components{}
 {
     ARM_COMPUTE_UNUSED(services);
 }
GpuLogicalKernel() [2/3]
GpuLogicalKernel (const GpuLogicalKernel &) default
Allow instances of this class to be copy constructed.
GpuLogicalKernel() [3/3]
GpuLogicalKernel (GpuLogicalKernel &&) default
Allow instances of this class to be move constructed.
Member Function Documentation
operator=() [1/2]
GpuLogicalKernel& operator= (const GpuLogicalKernel &) default
Allow instances of this class to be copied.
operator=() [2/2]
GpuLogicalKernel& operator= (GpuLogicalKernel &&) default
Allow instances of this class to be moved.
write_kernel_code()
GpuKernelSourceCode write_kernel_code ()
Generate a GpuKernelSourceCode.
Definition at line 50 of file GpuLogicalKernel.cpp.
 {
     GpuKernelSourceCode code;
 #ifndef ACL_INTERNAL_TEST_CKW_IN_DF
     ClTemplateWriter writer{_comp_group};
 #else  // ACL_INTERNAL_TEST_CKW_IN_DF
     GpuCkwDriver writer{_comp_group};
 #endif // ACL_INTERNAL_TEST_CKW_IN_DF
     code.name(writer.get_name());
     code.code(writer.get_code());
 #ifndef ACL_INTERNAL_TEST_CKW_IN_DF
     code.arguments(writer.get_tensors());
 #else  // ACL_INTERNAL_TEST_CKW_IN_DF
     code.arguments(writer.get_kernel_arguments());
 #endif // ACL_INTERNAL_TEST_CKW_IN_DF
     code.build_options(writer.get_build_options());
     code.config_id(writer.get_config_id());
     code.window(writer.get_window());
     return code;
 }
References GpuKernelSourceCode::arguments(), GpuKernelSourceCode::build_options(), GpuKernelSourceCode::code(), GpuKernelSourceCode::config_id(), GpuKernelSourceCode::name(), and GpuKernelSourceCode::window().
Referenced by GpuKernelComponentStream::write_workload_code().
The documentation for this class was generated from the following files:
src/dynamic_fusion/sketch/gpu/GpuLogicalKernel.h
src/dynamic_fusion/sketch/gpu/GpuLogicalKernel.cpp