Compute Library: CLDeconvolutionReshapeOutputKernel Class Reference
CLDeconvolutionReshapeOutputKernel Class Reference
Interface for the OpenCL kernel to be used for reshaping the tensor before returning the result of deconvolution.
#include <CLDeconvolutionReshapeOutputKernel.h>
Public Member Functions
CLDeconvolutionReshapeOutputKernel ()
Default constructor.
CLDeconvolutionReshapeOutputKernel (const CLDeconvolutionReshapeOutputKernel &)=delete
Prevent instances of this class from being copied (As this class contains pointers)
CLDeconvolutionReshapeOutputKernel & operator= (const CLDeconvolutionReshapeOutputKernel &)=delete
Prevent instances of this class from being copied (As this class contains pointers)
CLDeconvolutionReshapeOutputKernel (CLDeconvolutionReshapeOutputKernel &&)=default
Allow instances of this class to be moved.
CLDeconvolutionReshapeOutputKernel & operator= (CLDeconvolutionReshapeOutputKernel &&)=default
Allow instances of this class to be moved.
~CLDeconvolutionReshapeOutputKernel ()=default
Default destructor.
void configure (const ICLTensor *input, const ICLTensor *bias, ICLTensor *output, const ITensorInfo *input_info, const ITensorInfo *weights_info, const PadStrideInfo &deconv_info)
Initialise the kernel's source and destination.
void configure (const CLCompileContext &compile_context, const ICLTensor *input, const ICLTensor *bias, ICLTensor *output, const ITensorInfo *input_info, const ITensorInfo *weights_info, const PadStrideInfo &deconv_info)
Initialise the kernel's source and destination.
void run (const Window &window, cl::CommandQueue &queue) override
Enqueue the OpenCL kernel to process the given window on the passed OpenCL command queue.
Public Member Functions inherited from ICLSimpleKernel
ICLSimpleKernel ()
Constructor.
ICLSimpleKernel (const ICLSimpleKernel &)=delete
Prevent instances of this class from being copied (As this class contains pointers)
ICLSimpleKernel & operator= (const ICLSimpleKernel &)=delete
Prevent instances of this class from being copied (As this class contains pointers)
ICLSimpleKernel (ICLSimpleKernel &&)=default
Allow instances of this class to be moved.
ICLSimpleKernel & operator= (ICLSimpleKernel &&)=default
Allow instances of this class to be moved.
~ICLSimpleKernel ()=default
Default destructor.
void configure (const ICLTensor *input, ICLTensor *output, unsigned int num_elems_processed_per_iteration, bool border_undefined=false, const BorderSize &border_size=BorderSize())
Configure the kernel.
Public Member Functions inherited from ICLKernel
ICLKernel ()
Constructor.
cl::Kernel & kernel ()
Returns a reference to the OpenCL kernel of this object.
CLKernelType type () const
Returns the CL kernel type.
template<typename T >
void add_1D_array_argument (unsigned int &idx, const ICLArray< T > *array, const Strides &strides, unsigned int num_dimensions, const Window &window)
Add the passed 1D array's parameters to the object's kernel's arguments starting from the index idx.
void add_1D_tensor_argument (unsigned int &idx, const ICLTensor *tensor, const Window &window)
Add the passed 1D tensor's parameters to the object's kernel's arguments starting from the index idx.
void add_1D_tensor_argument_if (bool cond, unsigned int &idx, const ICLTensor *tensor, const Window &window)
Add the passed 1D tensor's parameters to the object's kernel's arguments starting from the index idx if the condition is true.
void add_2D_tensor_argument (unsigned int &idx, const ICLTensor *tensor, const Window &window)
Add the passed 2D tensor's parameters to the object's kernel's arguments starting from the index idx.
void add_2D_tensor_argument_if (bool cond, unsigned int &idx, const ICLTensor *tensor, const Window &window)
Add the passed 2D tensor's parameters to the object's kernel's arguments starting from the index idx if the condition is true.
void add_3D_tensor_argument (unsigned int &idx, const ICLTensor *tensor, const Window &window)
Add the passed 3D tensor's parameters to the object's kernel's arguments starting from the index idx.
void add_4D_tensor_argument (unsigned int &idx, const ICLTensor *tensor, const Window &window)
Add the passed 4D tensor's parameters to the object's kernel's arguments starting from the index idx.
void add_5D_tensor_argument (unsigned int &idx, const ICLTensor *tensor, const Window &window)
Add the passed 5D tensor's parameters to the object's kernel's arguments starting from the index idx.
void add_3d_tensor_nhw_argument (unsigned int &idx, const ICLTensor *tensor)
Add the passed NHW 3D tensor's parameters to the object's kernel's arguments by passing strides, dimensions and the offset to the first valid element in bytes.
void add_4d_tensor_nhwc_argument (unsigned int &idx, const ICLTensor *tensor)
Add the passed NHWC 4D tensor's parameters to the object's kernel's arguments by passing strides, dimensions and the offset to the first valid element in bytes.
virtual void run_op (ITensorPack &tensors, const Window &window, cl::CommandQueue &queue)
Enqueue the OpenCL kernel to process the given window on the passed OpenCL command queue.
template<typename T >
void add_argument (unsigned int &idx, T value)
Add the passed parameters to the object's kernel's arguments starting from the index idx.
void set_lws_hint (const cl::NDRange &lws_hint)
Set the Local-Workgroup-Size hint.
cl::NDRange lws_hint () const
Return the Local-Workgroup-Size hint.
void set_wbsm_hint (const cl_int &wbsm_hint)
Set the workgroup batch size modifier hint.
cl_int wbsm_hint () const
Return the workgroup batch size modifier hint.
const std::string & config_id () const
Get the configuration ID.
void set_target (GPUTarget target)
Set the targeted GPU architecture.
void set_target (cl::Device &device)
Set the targeted GPU architecture according to the CL device.
GPUTarget get_target () const
Get the targeted GPU architecture.
size_t get_max_workgroup_size ()
Get the maximum workgroup size for the device the CLKernelLibrary uses.
cl::NDRange get_cached_gws () const
Get the cached gws used to enqueue this kernel.
void cache_gws (const cl::NDRange &gws)
Cache the latest gws used to enqueue this kernel.
template<unsigned int dimension_size>
void add_tensor_argument (unsigned &idx, const ICLTensor *tensor, const Window &window)
template<typename T , unsigned int dimension_size>
void add_array_argument (unsigned &idx, const ICLArray< T > *array, const Strides &strides, unsigned int num_dimensions, const Window &window)
Add the passed array's parameters to the object's kernel's arguments starting from the index idx.
Public Member Functions inherited from IKernel
IKernel ()
Constructor.
virtual ~IKernel ()=default
Destructor.
virtual bool is_parallelisable () const
Indicates whether or not the kernel is parallelisable.
virtual BorderSize border_size () const
The size of the border for that kernel.
const Window & window () const
The maximum window the kernel can be executed on.
bool is_window_configured () const
Function to check if the embedded window of this kernel has been configured.
Static Public Member Functions
static Status validate (const ITensorInfo *input, const ITensorInfo *bias, const ITensorInfo *output, const ITensorInfo *input_info, const ITensorInfo *weights_info, const PadStrideInfo &deconv_info)
Static function to check if given info will lead to a valid configuration of CLDeconvolutionReshapeOutputKernel.
Static Public Member Functions inherited from ICLKernel
constexpr static unsigned int num_arguments_per_3d_tensor_nhw ()
Returns the number of arguments enqueued per NHW 3D Tensor object.
constexpr static unsigned int num_arguments_per_4d_tensor_nhwc ()
Returns the number of arguments enqueued per NHWC 4D Tensor object.
constexpr static unsigned int num_arguments_per_1D_array ()
Returns the number of arguments enqueued per 1D array object.
constexpr static unsigned int num_arguments_per_1D_tensor ()
Returns the number of arguments enqueued per 1D tensor object.
constexpr static unsigned int num_arguments_per_2D_tensor ()
Returns the number of arguments enqueued per 2D tensor object.
constexpr static unsigned int num_arguments_per_3D_tensor ()
Returns the number of arguments enqueued per 3D tensor object.
constexpr static unsigned int num_arguments_per_4D_tensor ()
Returns the number of arguments enqueued per 4D tensor object.
static cl::NDRange gws_from_window (const Window &window, bool use_dummy_work_items)
Get the global work size given an execution window.
Detailed Description
Interface for the OpenCL kernel to be used for reshaping the tensor before returning the result of deconvolution.
The input tensor to this OpenCL kernel is expected to be the result of a CLGEMM operation between the Deconvolution input and the Deconvolution filter.
The input tensor should have the following shape: [filter_width * filter_height * ofms, width, height, batch_size]
The output tensor should have the following shape: [stride_x * (input_width - 1) + filter_width - 2 * padx, stride_y * (input_height - 1) + filter_height - 2 * pady, ofms, batch_size]
For example, given a tensor with dimensions [4, 2, 2] this function returns a tensor with dimensions [1, 4, 4].
Definition at line 44 of file CLDeconvolutionReshapeOutputKernel.h.
Constructor & Destructor Documentation
CLDeconvolutionReshapeOutputKernel() [1/3]
CLDeconvolutionReshapeOutputKernel ()
Default constructor.
Definition at line 132 of file CLDeconvolutionReshapeOutputKernel.cpp.
                                                                        : _add_bias(false), _bias(nullptr)
 {
     _type = CLKernelType::ELEMENTWISE;
 }
References arm_compute::ELEMENTWISE.
CLDeconvolutionReshapeOutputKernel() [2/3]
CLDeconvolutionReshapeOutputKernel (const CLDeconvolutionReshapeOutputKernel &) delete
Prevent instances of this class from being copied (As this class contains pointers)
CLDeconvolutionReshapeOutputKernel() [3/3]
CLDeconvolutionReshapeOutputKernel (CLDeconvolutionReshapeOutputKernel &&) default
Allow instances of this class to be moved.
~CLDeconvolutionReshapeOutputKernel()
~CLDeconvolutionReshapeOutputKernel () default
Default destructor.
Member Function Documentation
configure() [1/2]
void configure (const CLCompileContext & compile_context, const ICLTensor * input, const ICLTensor * bias, ICLTensor * output, const ITensorInfo * input_info, const ITensorInfo * weights_info, const PadStrideInfo & deconv_info)
Initialise the kernel's source and destination.
Parameters
[in] compile_context The compile context to be used.
[in] input Input tensor. Supported data types: QASYMM8/QASYMM8_SIGNED/S32/F16/F32.
[in] bias Bias tensor to be added directly during the reshape operation. Supported data types: same as input. Supported data layouts: same as input.
[out] output Output tensor with the following shape: [stride_x * (input_width - 1) + filter_width - 2 * padx, stride_y * (input_height - 1) + filter_height - 2 * pady, ofms, batch_size] Supported data types: same as input. Supported data layouts: same as input.
[in] input_info Deconvolution input tensor info. Supported data types: same as input. Supported data layouts: same as input.
[in] weights_info Deconvolution weights tensor info. Supported data types: same as input. Supported data layouts: same as input.
[in] deconv_info Contains padding and policies to be used in the deconvolution, this is described in PadStrideInfo. This kernel supports only stride_x = weights.width && stride_y = weights.height. Moreover, padding is not supported.
Definition at line 147 of file CLDeconvolutionReshapeOutputKernel.cpp.
 {
     ARM_COMPUTE_ERROR_ON_NULLPTR(input, output, input_info, weights_info);
     ARM_COMPUTE_ERROR_THROW_ON(validate_arguments(input->info(), (bias != nullptr ? bias->info() : nullptr),
                                                   output->info(), input_info, weights_info, deconv_info));
     auto padding_info = get_padding_info({input, bias, output});
     // Configure kernel window
     auto win_config =
         validate_and_configure_window(input->info(), output->info(), input_info, weights_info, deconv_info);
     ARM_COMPUTE_ERROR_THROW_ON(win_config.first);
     const DataLayout data_layout = input_info->data_layout();
     const size_t     idx_w       = get_data_layout_dimension_index(data_layout, DataLayoutDimension::WIDTH);
     const size_t     idx_h       = get_data_layout_dimension_index(data_layout, DataLayoutDimension::HEIGHT);
     const size_t     idx_b       = get_data_layout_dimension_index(data_layout, DataLayoutDimension::BATCHES);
     _input    = input;
     _output   = output;
     _add_bias = (bias != nullptr);
     _bias     = bias;
     const int filter_w = weights_info->dimension(idx_w);
     const int filter_h = weights_info->dimension(idx_h);
     const int filter_b = weights_info->dimension(idx_b);
     const int img_w    = input_info->dimension(idx_w);
     const int img_h    = input_info->dimension(idx_h);
     CLBuildOptions build_opts;
     build_opts.add_option("-DDATA_TYPE=" + get_cl_type_from_data_type(input->info()->data_type()));
     build_opts.add_option("-DFILTER_WIDTH=" + support::cpp11::to_string(filter_w));
     build_opts.add_option("-DFILTER_HEIGHT=" + support::cpp11::to_string(filter_h));
     build_opts.add_option("-DSRC_WIDTH=" + support::cpp11::to_string(img_w));
     build_opts.add_option("-DSRC_HEIGHT=" + support::cpp11::to_string(img_h));
     build_opts.add_option_if(data_layout == DataLayout::NCHW, "-DNUM_FILTERS=" + support::cpp11::to_string(filter_b));
     build_opts.add_option_if(_add_bias, "-DADD_BIAS");
     _kernel = create_kernel(compile_context, "deconvolution_reshape", build_opts.options());
     ICLKernel::configure_internal(win_config.second);
     // Set config_id for enabling LWS tuning
     _config_id = "deconvolution_reshape_output_";
     _config_id += lower_string(string_from_data_type(input->info()->data_type()));
     _config_id += "_";
     _config_id += lower_string(string_from_data_layout(input->info()->data_layout()));
     _config_id += "_";
     _config_id += support::cpp11::to_string(input->info()->dimension(0));
     _config_id += "_";
     _config_id += support::cpp11::to_string(input->info()->dimension(1));
     _config_id += "_";
     _config_id += support::cpp11::to_string(output->info()->dimension(0));
     _config_id += "_";
     _config_id += support::cpp11::to_string(output->info()->dimension(1));
     ARM_COMPUTE_ERROR_ON(has_padding_changed(padding_info));
 }
References CLBuildOptions::add_option(), CLBuildOptions::add_option_if(), ARM_COMPUTE_ERROR_ON, ARM_COMPUTE_ERROR_ON_NULLPTR, ARM_COMPUTE_ERROR_THROW_ON, arm_compute::BATCHES, bias, arm_compute::create_kernel(), arm_compute::cpu::data_layout, ITensorInfo::dimension(), arm_compute::get_cl_type_from_data_type(), arm_compute::get_data_layout_dimension_index(), arm_compute::get_padding_info(), arm_compute::has_padding_changed(), arm_compute::HEIGHT, ITensor::info(), arm_compute::test::validation::input, arm_compute::test::validation::input_info, arm_compute::lower_string(), arm_compute::NCHW, CLBuildOptions::options(), arm_compute::string_from_data_layout(), arm_compute::string_from_data_type(), arm_compute::support::cpp11::to_string(), arm_compute::cpu::kernels::validate_and_configure_window(), arm_compute::cpu::kernels::validate_arguments(), arm_compute::test::validation::weights_info, and arm_compute::WIDTH.
configure() [2/2]
void configure (const ICLTensor * input, const ICLTensor * bias, ICLTensor * output, const ITensorInfo * input_info, const ITensorInfo * weights_info, const PadStrideInfo & deconv_info)
Initialise the kernel's source and destination.
Parameters
[in] input Input tensor. Supported data types: QASYMM8/QASYMM8_SIGNED/S32/F16/F32.
[in] bias Bias tensor to be added directly during the reshape operation. Supported data types: same as input. Supported data layouts: same as input.
[out] output Output tensor with the following shape: [stride_x * (input_width - 1) + filter_width - 2 * padx, stride_y * (input_height - 1) + filter_height - 2 * pady, ofms, batch_size] Supported data types: same as input. Supported data layouts: same as input.
[in] input_info Deconvolution input tensor info. Supported data types: same as input. Supported data layouts: same as input.
[in] weights_info Deconvolution weights tensor info. Supported data types: same as input. Supported data layouts: same as input.
[in] deconv_info Contains padding and policies to be used in the deconvolution, this is described in PadStrideInfo. This kernel supports only stride_x = weights.width && stride_y = weights.height. Moreover, padding is not supported.
Definition at line 137 of file CLDeconvolutionReshapeOutputKernel.cpp.
 {
     configure(CLKernelLibrary::get().get_compile_context(), input, bias, output, input_info, weights_info, deconv_info);
 }
References bias, CLKernelLibrary::get(), arm_compute::test::validation::input, arm_compute::test::validation::input_info, and arm_compute::test::validation::weights_info.
operator=() [1/2]
CLDeconvolutionReshapeOutputKernel& operator= (CLDeconvolutionReshapeOutputKernel &&) default
Allow instances of this class to be moved.
operator=() [2/2]
CLDeconvolutionReshapeOutputKernel& operator= (const CLDeconvolutionReshapeOutputKernel &) delete
Prevent instances of this class from being copied (As this class contains pointers)
run()
void run (const Window & window, cl::CommandQueue & queue) override virtual
Enqueue the OpenCL kernel to process the given window on the passed OpenCL command queue.
Note
The queue is not flushed by this method, and therefore the kernel will not have been executed by the time this method returns.
Parameters
[in] window Region on which to execute the kernel. (Must be a valid region of the window returned by window()).
[in,out] queue Command queue on which to enqueue the kernel.
Reimplemented from ICLKernel.
Definition at line 220 of file CLDeconvolutionReshapeOutputKernel.cpp.
 {
     ARM_COMPUTE_ERROR_ON_UNCONFIGURED_KERNEL(this);
     ARM_COMPUTE_ERROR_ON_INVALID_SUBWINDOW(ICLKernel::window(), window);
     Window collapsed = window.collapse_if_possible(ICLKernel::window(), Window::DimZ);
     unsigned int idx = 0;
     add_3D_tensor_argument(idx, _input, collapsed);
     add_3D_tensor_argument(idx, _output, collapsed);
     if (_add_bias)
     {
         add_1D_tensor_argument(idx, _bias, collapsed);
     }
     enqueue(queue, *this, collapsed, lws_hint());
 }
References ICLKernel::add_1D_tensor_argument(), ICLKernel::add_3D_tensor_argument(), ARM_COMPUTE_ERROR_ON_INVALID_SUBWINDOW, ARM_COMPUTE_ERROR_ON_UNCONFIGURED_KERNEL, Window::collapse_if_possible(), Window::DimZ, arm_compute::enqueue(), ICLKernel::lws_hint(), and IKernel::window().
validate()
Status validate (const ITensorInfo * input, const ITensorInfo * bias, const ITensorInfo * output, const ITensorInfo * input_info, const ITensorInfo * weights_info, const PadStrideInfo & deconv_info) static
Static function to check if given info will lead to a valid configuration of CLDeconvolutionReshapeOutputKernel.
Parameters
[in] input GEMM output tensor info to be reshaped. Supported data types: QASYMM8/QASYMM8_SIGNED/S32/F16/F32.
[in] bias (Optional) Optional bias tensor info to be added directly during the reshape operation. Supported data types: same as input. Supported data layouts: same as input.
[in] output Reshaped output tensor info. Supported data types: same as input. Supported data layouts: same as input.
[in] input_info Original input tensor info. Supported data types: same as input. Supported data layouts: same as input.
[in] weights_info Original weights tensor info output. Supported data types: same as input. Supported data layouts: same as input.
[in] deconv_info Contains padding and policies to be used in the deconvolution, this is described in PadStrideInfo. This kernel supports only stride_x = weights.width && stride_y = weights.height. Moreover, padding is not supported.
Returns
a Status
Definition at line 209 of file CLDeconvolutionReshapeOutputKernel.cpp.
 {
     ARM_COMPUTE_RETURN_ON_ERROR(validate_arguments(input, bias, output, input_info, weights_info, deconv_info));
     return Status{};
 }
References ARM_COMPUTE_RETURN_ON_ERROR, bias, arm_compute::test::validation::input, arm_compute::test::validation::input_info, arm_compute::cpu::kernels::validate_arguments(), and arm_compute::test::validation::weights_info.
Referenced by CLGEMMDeconvolutionLayer::validate().
The documentation for this class was generated from the following files:
src/core/CL/kernels/CLDeconvolutionReshapeOutputKernel.h
src/core/CL/kernels/CLDeconvolutionReshapeOutputKernel.cpp