Compute Library: CpuGemmLowpQuantizeDownInt32ScaleKernel Class Reference
CpuGemmLowpQuantizeDownInt32ScaleKernel Class Reference
Kernel used to quantize down the int32 accumulator values of GEMMLowp to QASYMM8/QASYMM8_SIGNED.
#include <CpuGemmLowpQuantizeDownInt32ScaleKernel.h>
Public Member Functions
CpuGemmLowpQuantizeDownInt32ScaleKernel ()=default
ARM_COMPUTE_DISALLOW_COPY_ALLOW_MOVE (CpuGemmLowpQuantizeDownInt32ScaleKernel)
void configure (ITensorInfo *src, ITensorInfo *bias, ITensorInfo *dst, const GEMMLowpOutputStageInfo *output_stage)
Initialise the kernel's input and output.
void run_op (ITensorPack &tensors, const Window &window, const ThreadInfo &info) override
Execute the kernel on the passed window.
const char * name () const override
Name of the kernel.
Public Member Functions inherited from ICPPKernel
virtual ~ICPPKernel ()=default
Default destructor.
virtual void run (const Window &window, const ThreadInfo &info)
Execute the kernel on the passed window.
virtual void run_nd (const Window &window, const ThreadInfo &info, const Window &thread_locator)
legacy compatibility layer for implemantions which do not support thread_locator In these cases we simply narrow the interface down the legacy version
virtual size_t get_mws (const CPUInfo &platform, size_t thread_count) const
Return minimum workload size of the relevant kernel.
Public Member Functions inherited from IKernel
IKernel ()
Constructor.
virtual ~IKernel ()=default
Destructor.
virtual bool is_parallelisable () const
Indicates whether or not the kernel is parallelisable.
virtual BorderSize border_size () const
The size of the border for that kernel.
const Window & window () const
The maximum window the kernel can be executed on.
bool is_window_configured () const
Function to check if the embedded window of this kernel has been configured.
Static Public Member Functions
static Status validate (const ITensorInfo *src, const ITensorInfo *bias, const ITensorInfo *dst, const GEMMLowpOutputStageInfo *output_stage)
Static function to check if given info will lead to a valid configuration.
Static Public Member Functions inherited from ICpuKernel< CpuGemmLowpQuantizeDownInt32ScaleKernel >
static const auto * get_implementation (const SelectorType &selector, KernelSelectionType selection_type=KernelSelectionType::Supported)
Micro-kernel selector.
Additional Inherited Members
Static Public Attributes inherited from ICPPKernel
static constexpr size_t default_mws = 1
Detailed Description
Kernel used to quantize down the int32 accumulator values of GEMMLowp to QASYMM8/QASYMM8_SIGNED.
This kernel takes a final int32 accumulator value (the output of CpuGemmLowpMatrixMultiplyKernel), and processes it to obtain the final QASYMM8/QASYMM8_SIGNED value. The following computations will be performed by the kernel:
Add offset terms to final result
Multiply each entry of result by result_mult_int
Add bias to final result if bias tensor is not a nullptr
Shift the int32 accumulator by result_shift
Clamp the value between the specified min and max bounds
Clamp the resulting int32 values:
-to the [0..255] range and cast to QASYMM8.
-to the [-128..127] range and cast to QASYMM8_SIGNED.
Definition at line 55 of file CpuGemmLowpQuantizeDownInt32ScaleKernel.h.
Constructor & Destructor Documentation
CpuGemmLowpQuantizeDownInt32ScaleKernel()
CpuGemmLowpQuantizeDownInt32ScaleKernel () default
Member Function Documentation
ARM_COMPUTE_DISALLOW_COPY_ALLOW_MOVE()
ARM_COMPUTE_DISALLOW_COPY_ALLOW_MOVE (CpuGemmLowpQuantizeDownInt32ScaleKernel)
configure()
void configure (ITensorInfo * src, ITensorInfo * bias, ITensorInfo * dst, const GEMMLowpOutputStageInfo * output_stage)
Initialise the kernel's input and output.
Parameters
[in] src Input tensor info. Data type supported: S32
[in] bias Biases tensor info. Only shared biases supported and it can be a nullptr if the biases addition is not required. Biases are 1D tensor with dimensions [OFM]. Data type supported: Same as input.
[out] dst Output tensor info. Data type supported: Data type supported: QASYMM8/QASYMM8_SIGNED
[out] output_stage GEMMLowp output stage metadata.
Definition at line 267 of file CpuGemmLowpQuantizeDownInt32ScaleKernel.cpp.
 {
     ARM_COMPUTE_UNUSED(bias);
     // Perform validate step
     ARM_COMPUTE_ERROR_ON_NULLPTR(src, dst, output_stage);
     // Output auto inizialitation if not yet initialized
     auto_init_if_empty(*dst, src->clone()->set_data_type(output_stage->output_data_type));
     ARM_COMPUTE_ERROR_THROW_ON(validate_arguments(src, bias, dst, output_stage));
     _output_stage = output_stage;
     // Configure kernel window
     Window win = calculate_max_window(*src, Steps());
     ICpuKernel::configure(win);
     // Check if we need to clamp the result using min and max
     _is_bounded_relu =
         ((_output_stage->gemmlowp_min_bound != _output_stage->gemmlowp_max_bound) &&
          !(_output_stage->gemmlowp_min_bound ==
                std::get<0>(quantization::get_min_max_values_from_quantized_data_type(output_stage->output_data_type)) &&
            _output_stage->gemmlowp_max_bound ==
                std::get<1>(quantization::get_min_max_values_from_quantized_data_type(output_stage->output_data_type))));
     if (_output_stage->output_data_type == DataType::QASYMM8)
     {
         _func = &CpuGemmLowpQuantizeDownInt32ScaleKernel::run_internal<uint8_t>;
     }
     else if (_output_stage->output_data_type == DataType::QASYMM8_SIGNED)
     {
         _func = &CpuGemmLowpQuantizeDownInt32ScaleKernel::run_internal<int8_t>;
     }
     else
     {
         ARM_COMPUTE_ERROR("Data type not supported");
     }
 }
References ARM_COMPUTE_ERROR, ARM_COMPUTE_ERROR_ON_NULLPTR, ARM_COMPUTE_ERROR_THROW_ON, ARM_COMPUTE_UNUSED, arm_compute::auto_init_if_empty(), bias, arm_compute::calculate_max_window(), arm_compute::test::validation::dst, GEMMLowpOutputStageInfo::gemmlowp_max_bound, GEMMLowpOutputStageInfo::gemmlowp_min_bound, arm_compute::quantization::get_min_max_values_from_quantized_data_type(), GEMMLowpOutputStageInfo::output_data_type, output_stage, arm_compute::QASYMM8, arm_compute::QASYMM8_SIGNED, arm_compute::test::validation::src, and arm_compute::cpu::kernels::validate_arguments().
name()
const char * name () const override virtual
Name of the kernel.
Returns
Kernel name
Implements ICPPKernel.
Definition at line 331 of file CpuGemmLowpQuantizeDownInt32ScaleKernel.cpp.
 {
     return "CpuGemmLowpQuantizeDownInt32ScaleKernel";
 }
run_op()
void run_op (ITensorPack & tensors, const Window & window, const ThreadInfo & info) override virtual
Execute the kernel on the passed window.
Warning
If is_parallelisable() returns false then the passed window must be equal to window()
Note
The window has to be a region within the window returned by the window() method
The width of the window has to be a multiple of num_elems_processed_per_iteration().
Parameters
[in] tensors A vector containing the tensors to operate on.
[in] window Region on which to execute the kernel. (Must be a region of the window returned by window())
[in] info Info about executing thread and CPU.
Reimplemented from ICPPKernel.
Definition at line 318 of file CpuGemmLowpQuantizeDownInt32ScaleKernel.cpp.
 {
     ARM_COMPUTE_UNUSED(info);
     ARM_COMPUTE_ERROR_ON_UNCONFIGURED_KERNEL(this);
     ARM_COMPUTE_ERROR_ON_INVALID_SUBWINDOW(ICpuKernel::window(), window);
     ARM_COMPUTE_ERROR_ON_MSG(tensors.empty(), "No inputs provided");
     auto src  = tensors.get_const_tensor(TensorType::ACL_SRC);
     auto bias = tensors.get_const_tensor(TensorType::ACL_BIAS);
     auto dst  = tensors.get_tensor(TensorType::ACL_DST);
     (this->*_func)(src, bias, dst, window);
 }
References arm_compute::ACL_BIAS, arm_compute::ACL_DST, arm_compute::ACL_SRC, ARM_COMPUTE_ERROR_ON_INVALID_SUBWINDOW, ARM_COMPUTE_ERROR_ON_MSG, ARM_COMPUTE_ERROR_ON_UNCONFIGURED_KERNEL, ARM_COMPUTE_UNUSED, bias, arm_compute::test::validation::dst, ITensorPack::empty(), ITensorPack::get_const_tensor(), ITensorPack::get_tensor(), arm_compute::test::validation::info, arm_compute::test::validation::src, and IKernel::window().
validate()
Status validate (const ITensorInfo * src, const ITensorInfo * bias, const ITensorInfo * dst, const GEMMLowpOutputStageInfo * output_stage) static
Static function to check if given info will lead to a valid configuration.
Similar to CpuGemmLowpQuantizeDownInt32ScaleKernel::configure()
Returns
a status
Definition at line 309 of file CpuGemmLowpQuantizeDownInt32ScaleKernel.cpp.
 {
     ARM_COMPUTE_RETURN_ON_ERROR(validate_arguments(src, bias, dst, output_stage));
     return Status{};
 }
References ARM_COMPUTE_RETURN_ON_ERROR, bias, arm_compute::test::validation::dst, output_stage, arm_compute::test::validation::src, and arm_compute::cpu::kernels::validate_arguments().
Referenced by CpuGemmLowpOutputStage::validate().
The documentation for this class was generated from the following files:
src/cpu/kernels/CpuGemmLowpQuantizeDownInt32ScaleKernel.h
src/cpu/kernels/CpuGemmLowpQuantizeDownInt32ScaleKernel.cpp