Compute Library: BoundingBoxTransformInfo Class Reference
BoundingBoxTransformInfo Class Reference final
Bounding Box Transform information class.
#include <Types.h>
Public Member Functions
BoundingBoxTransformInfo (float img_width, float img_height, float scale, bool apply_scale=false, const std::array< float, 4 > weights={{1.f, 1.f, 1.f, 1.f}}, bool correct_transform_coords=false, float bbox_xform_clip=4.135166556742356f)
Constructor.
std::array< float, 4 > weights () const
float bbox_xform_clip () const
float img_height () const
float img_width () const
float scale () const
bool apply_scale () const
bool correct_transform_coords () const
Detailed Description
Bounding Box Transform information class.
Definition at line 1453 of file Types.h.
Constructor & Destructor Documentation
BoundingBoxTransformInfo()
BoundingBoxTransformInfo (float img_width, float img_height, float scale, bool apply_scale = false, const std::array< float, 4 > weights = {{1.f, 1.f, 1.f, 1.f}}, bool correct_transform_coords = false, float bbox_xform_clip = 4.135166556742356f) inline
Constructor.
Parameters
[in] img_width Width of the original image
[in] img_height Height, of the original image
[in] scale Scale of the original image
[in] apply_scale (Optional)Re-apply scaling after transforming the boxes. Defaults to false
[in] weights (Optional)Weights [wx, wy, ww, wh] for the deltas. Defaults to all ones
[in] correct_transform_coords (Optional)Correct bounding box transform coordinates. Defaults to false
[in] bbox_xform_clip (Optional)Minimum bounding box width and height after bounding box transformation in log-space. Defaults to log(1000/16)
Definition at line 1466 of file Types.h.
                                                                                  {{1.f, 1.f, 1.f, 1.f}},
                              bool                       correct_transform_coords = false,
                              float                      bbox_xform_clip          = 4.135166556742356f)
         : _img_width(img_width),
           _img_height(img_height),
           _scale(scale),
           _apply_scale(apply_scale),
           _correct_transform_coords(correct_transform_coords),
           _weights(weights),
           _bbox_xform_clip(bbox_xform_clip)
     {
     }
Member Function Documentation
apply_scale()
bool apply_scale () const inline
Definition at line 1508 of file Types.h.
     {
         return _apply_scale;
     }
Referenced by arm_compute::cpu::bounding_box_transform(), and arm_compute::cpu::bounding_box_transform_qsymm16().
bbox_xform_clip()
float bbox_xform_clip () const inline
Definition at line 1488 of file Types.h.
     {
         return _bbox_xform_clip;
     }
Referenced by arm_compute::cpu::bounding_box_transform(), and arm_compute::cpu::bounding_box_transform_qsymm16().
correct_transform_coords()
bool correct_transform_coords () const inline
Definition at line 1513 of file Types.h.
     {
         return _correct_transform_coords;
     }
Referenced by arm_compute::cpu::bounding_box_transform(), and arm_compute::cpu::bounding_box_transform_qsymm16().
img_height()
float img_height () const inline
Definition at line 1493 of file Types.h.
     {
         return _img_height;
     }
Referenced by arm_compute::cpu::bounding_box_transform(), arm_compute::cpu::bounding_box_transform_qsymm16(), arm_compute::graph::backends::detail::create_bounding_box_transform_layer(), and arm_compute::operator<<().
img_width()
float img_width () const inline
Definition at line 1498 of file Types.h.
     {
         return _img_width;
     }
Referenced by arm_compute::cpu::bounding_box_transform(), arm_compute::cpu::bounding_box_transform_qsymm16(), arm_compute::graph::backends::detail::create_bounding_box_transform_layer(), and arm_compute::operator<<().
scale()
float scale () const inline
Definition at line 1503 of file Types.h.
     {
         return _scale;
     }
Referenced by arm_compute::cpu::bounding_box_transform(), arm_compute::cpu::bounding_box_transform_qsymm16(), and arm_compute::operator<<().
weights()
std::array<float, 4> weights () const inline
Definition at line 1483 of file Types.h.
     {
         return _weights;
     }
Referenced by arm_compute::cpu::bounding_box_transform(), arm_compute::cpu::bounding_box_transform_qsymm16(), and arm_compute::operator<<().
The documentation for this class was generated from the following file:
arm_compute/core/Types.h