Compute Library: CLSlice Class Reference
CLSlice Class Reference
Basic function to perform tensor slicing.
#include <CLSlice.h>
Public Member Functions
CLSlice ()
Default Constructor.
~CLSlice ()
Default Destructor.
CLSlice (const CLSlice &)=delete
Prevent instances of this class from being copied (As this class contains pointers)
CLSlice (CLSlice &&)
Default move constructor.
CLSlice & operator= (const CLSlice &)=delete
Prevent instances of this class from being copied (As this class contains pointers)
CLSlice & operator= (CLSlice &&)
Default move assignment operator.
void configure (const ICLTensor *input, ICLTensor *output, const Coordinates &starts, const Coordinates &ends)
Configure kernel.
void configure (const CLCompileContext &compile_context, const ICLTensor *input, ICLTensor *output, const Coordinates &starts, const Coordinates &ends)
Configure kernel.
void run () override
Run the kernels contained in the function.
Public Member Functions inherited from IFunction
virtual ~IFunction ()=default
Destructor.
virtual void prepare ()
Prepare the function for executing.
Static Public Member Functions
static Status validate (const ITensorInfo *input, const ITensorInfo *output, const Coordinates &starts, const Coordinates &ends)
Static function to check if given info will lead to a valid configuration of CLSlice.
Detailed Description
Basic function to perform tensor slicing.
Definition at line 38 of file CLSlice.h.
Constructor & Destructor Documentation
CLSlice() [1/3]
CLSlice ()
Default Constructor.
Definition at line 79 of file CLSlice.cpp.
                  : _impl(std::make_unique<Impl>())
 {
 }
~CLSlice()
~CLSlice () default
Default Destructor.
CLSlice() [2/3]
CLSlice (const CLSlice &) delete
Prevent instances of this class from being copied (As this class contains pointers)
CLSlice() [3/3]
CLSlice (CLSlice &&) default
Default move constructor.
Member Function Documentation
configure() [1/2]
void configure (const CLCompileContext & compile_context, const ICLTensor * input, ICLTensor * output, const Coordinates & starts, const Coordinates & ends)
Configure kernel.
Note
Supported tensor rank: up to 4
Start indices must be non-negative. 0 <= starts[i]
End coordinates can be negative, which represents the number of elements before the end of that dimension.
End indices are not inclusive unless negative.
Parameters
[in] compile_context The compile context to be used.
[in] input Source tensor. Data type supported: All.
[out] output Destination tensor. Data type supported: Same as input
[in] starts The starts of the dimensions of the input tensor to be sliced. The length must be of rank(input).
[in] ends The ends of the dimensions of the input tensor to be sliced. The length must be of rank(input).
Definition at line 99 of file CLSlice.cpp.
 {
     _impl->src = input;
     _impl->dst = output;
     _impl->op  = std::make_unique<experimental::CLSlice>();
     _impl->op->configure(compile_context, input->info(), output->info(), starts, ends);
 }
References ITensor::info(), and arm_compute::test::validation::input.
configure() [2/2]
void configure (const ICLTensor * input, ICLTensor * output, const Coordinates & starts, const Coordinates & ends)
Configure kernel.
Valid data layouts:
All
Valid data type configurations:
src dst
All All
Note
Supported tensor rank: up to 4
Start indices must be non-negative. 0 <= starts[i]
End coordinates can be negative, which represents the number of elements before the end of that dimension.
End indices are not inclusive unless negative.
Parameters
[in] input Source tensor. Data type supported: All.
[out] output Destination tensor. Data type supported: Same as input
[in] starts The starts of the dimensions of the input tensor to be sliced. The length must be of rank(input).
[in] ends The ends of the dimensions of the input tensor to be sliced. The length must be of rank(input).
Definition at line 94 of file CLSlice.cpp.
 {
     configure(CLKernelLibrary::get().get_compile_context(), input, output, starts, ends);
 }
References CLKernelLibrary::get(), and arm_compute::test::validation::input.
Referenced by CLFFTConvolutionLayer::configure(), CLGEMMDeconvolutionLayer::configure(), and CLLSTMLayerQuantized::configure().
operator=() [1/2]
CLSlice & operator= (CLSlice &&) default
Default move assignment operator.
operator=() [2/2]
CLSlice& operator= (const CLSlice &) delete
Prevent instances of this class from being copied (As this class contains pointers)
run()
void run () override virtual
Run the kernels contained in the function.
For CPU kernels:
Multi-threading is used for the kernels which are parallelisable.
By default std::thread::hardware_concurrency() threads are used.
Note
CPPScheduler::set_num_threads() can be used to manually set the number of threads
For OpenCL kernels:
All the kernels are enqueued on the queue associated with CLScheduler.
The queue is then flushed.
Note
The function will not block until the kernels are executed. It is the user's responsibility to wait.
Will call prepare() on first run if hasn't been done
Implements IFunction.
Definition at line 111 of file CLSlice.cpp.
 {
     ITensorPack pack;
     pack.add_tensor(TensorType::ACL_SRC, _impl->src);
     pack.add_tensor(TensorType::ACL_DST, _impl->dst);
     _impl->op->run(pack);
 }
References arm_compute::ACL_DST, arm_compute::ACL_SRC, ITensorPack::add_tensor(), and arm_compute::test::validation::pack.
Referenced by CLFFTConvolutionLayer::run(), CLGEMMDeconvolutionLayer::run(), and CLLSTMLayerQuantized::run().
validate()
Status validate (const ITensorInfo * input, const ITensorInfo * output, const Coordinates & starts, const Coordinates & ends) static
Static function to check if given info will lead to a valid configuration of CLSlice.
Note
Supported tensor rank: up to 4
Start indices must be non-negative. 0 <= starts[i]
End coordinates can be negative, which represents the number of elements before the end of that dimension.
End indices are not inclusive unless negative.
Parameters
[in] input Source tensor info. Data type supported: All.
[in] output Destination tensor info. Data type supported: Same as input
[in] starts The starts of the dimensions of the input tensor to be sliced. The length must be of rank(input).
[in] ends The ends of the dimensions of the input tensor to be sliced. The length must be of rank(input).
Returns
A status
Definition at line 86 of file CLSlice.cpp.
 {
     return experimental::CLSlice::validate(input, output, starts, ends);
 }
References arm_compute::test::validation::input, and CLSlice::validate().
Referenced by CLGEMMDeconvolutionLayer::validate(), and CLLSTMLayerQuantized::validate().
The documentation for this class was generated from the following files:
arm_compute/runtime/CL/functions/CLSlice.h
src/runtime/CL/functions/CLSlice.cpp