Compute Library: CLStridedSlice Class Reference
CLStridedSlice Class Reference
Basic function to run CLStridedSliceKernel.
#include <CLStridedSlice.h>
Public Member Functions
CLStridedSlice (CLRuntimeContext *ctx=nullptr)
Constructor.
~CLStridedSlice ()
Destructor.
CLStridedSlice (const CLStridedSlice &)=delete
Prevent instances of this class from being copied (As this class contains pointers)
CLStridedSlice (CLStridedSlice &&)
Default move constructor.
CLStridedSlice & operator= (const CLStridedSlice &)=delete
Prevent instances of this class from being copied (As this class contains pointers)
CLStridedSlice & operator= (CLStridedSlice &&)
Default move assignment operator.
void configure (const ICLTensor *input, ICLTensor *output, const Coordinates &starts, const Coordinates &ends, const BiStrides &strides, int32_t begin_mask=0, int32_t end_mask=0, int32_t shrink_axis_mask=0)
Configure kernel.
void configure (const CLCompileContext &compile_context, const ICLTensor *input, ICLTensor *output, const Coordinates &starts, const Coordinates &ends, const BiStrides &strides, int32_t begin_mask=0, int32_t end_mask=0, int32_t shrink_axis_mask=0)
Configure kernel.
void run () override
Run the kernels contained in the function.
Public Member Functions inherited from IFunction
virtual ~IFunction ()=default
Destructor.
virtual void prepare ()
Prepare the function for executing.
Static Public Member Functions
static Status validate (const ITensorInfo *input, const ITensorInfo *output, const Coordinates &starts, const Coordinates &ends, const BiStrides &strides, int32_t begin_mask=0, int32_t end_mask=0, int32_t shrink_axis_mask=0)
Static function to check if given info will lead to a valid configuration of CLStridedSlice.
Detailed Description
Basic function to run CLStridedSliceKernel.
Definition at line 37 of file CLStridedSlice.h.
Constructor & Destructor Documentation
CLStridedSlice() [1/3]
CLStridedSlice (CLRuntimeContext * ctx = nullptr)
Constructor.
Parameters
[in] ctx Runtime context to be used by the function
Definition at line 73 of file CLStridedSlice.cpp.
                                                     : _impl(std::make_unique<Impl>())
 {
     _impl->ctx = ctx;
 }
~CLStridedSlice()
~CLStridedSlice () default
Destructor.
CLStridedSlice() [2/3]
CLStridedSlice (const CLStridedSlice &) delete
Prevent instances of this class from being copied (As this class contains pointers)
CLStridedSlice() [3/3]
CLStridedSlice (CLStridedSlice &&) default
Default move constructor.
Member Function Documentation
configure() [1/2]
void configure (const CLCompileContext & compile_context, const ICLTensor * input, ICLTensor * output, const Coordinates & starts, const Coordinates & ends, const BiStrides & strides, int32_t begin_mask = 0, int32_t end_mask = 0, int32_t shrink_axis_mask = 0)
Configure kernel.
Note
Supported tensor rank: up to 4
Parameters
[in] compile_context The compile context to be used.
[in] input Source tensor. Data type supported: All.
[out] output Destination tensor. Data type supported: Same as input
[in] starts The starts of the dimensions of the input tensor to be sliced. The length must be of rank(input).
[in] ends The ends of the dimensions of the input tensor to be sliced. The length must be of rank(input).
[in] strides The strides of the dimensions of the input tensor to be sliced. The length must be of rank(input).
[in] begin_mask (Optional) If the ith bit of begin_mask is set, starts[i] is ignored and the fullest possible range in that dimension is used instead.
[in] end_mask (Optional) If the ith bit of end_mask is set, ends[i] is ignored and the fullest possible range in that dimension is used instead.
[in] shrink_axis_mask (Optional) If the ith bit of shrink_axis_mask is set, it implies that the ith specification shrinks the dimensionality by 1. A slice of size 1 starting from starts[i] in the dimension must be preserved.
Definition at line 95 of file CLStridedSlice.cpp.
 {
     ARM_COMPUTE_ERROR_ON_NULLPTR(input);
     _impl->src = input;
     _impl->dst = output;
     _impl->op = std::make_unique<experimental::CLStridedSlice>();
     _impl->op->configure(compile_context, _impl->src->info(), _impl->dst->info(), starts, ends, strides, begin_mask,
                          end_mask, shrink_axis_mask);
 }
References ARM_COMPUTE_ERROR_ON_NULLPTR, and arm_compute::test::validation::input.
configure() [2/2]
void configure (const ICLTensor * input, ICLTensor * output, const Coordinates & starts, const Coordinates & ends, const BiStrides & strides, int32_t begin_mask = 0, int32_t end_mask = 0, int32_t shrink_axis_mask = 0)
Configure kernel.
Valid data layouts:
All
Valid data type configurations:
src dst
All All
Note
Supported tensor rank: up to 4
Parameters
[in] input Source tensor. Data type supported: All.
[out] output Destination tensor. Data type supported: Same as input
[in] starts The starts of the dimensions of the input tensor to be sliced. The length must be of rank(input).
[in] ends The ends of the dimensions of the input tensor to be sliced. The length must be of rank(input).
[in] strides The strides of the dimensions of the input tensor to be sliced. The length must be of rank(input).
[in] begin_mask (Optional) If the ith bit of begin_mask is set, starts[i] is ignored and the fullest possible range in that dimension is used instead.
[in] end_mask (Optional) If the ith bit of end_mask is set, ends[i] is ignored and the fullest possible range in that dimension is used instead.
[in] shrink_axis_mask (Optional) If the ith bit of shrink_axis_mask is set, it implies that the ith specification shrinks the dimensionality by 1. A slice of size 1 starting from starts[i] in the dimension must be preserved.
Definition at line 82 of file CLStridedSlice.cpp.
 {
     configure(CLKernelLibrary::get().get_compile_context(), input, output, starts, ends, strides, begin_mask, end_mask,
               shrink_axis_mask);
 }
References CLKernelLibrary::get(), and arm_compute::test::validation::input.
operator=() [1/2]
CLStridedSlice & operator= (CLStridedSlice &&) default
Default move assignment operator.
operator=() [2/2]
CLStridedSlice& operator= (const CLStridedSlice &) delete
Prevent instances of this class from being copied (As this class contains pointers)
run()
void run () override virtual
Run the kernels contained in the function.
For CPU kernels:
Multi-threading is used for the kernels which are parallelisable.
By default std::thread::hardware_concurrency() threads are used.
Note
CPPScheduler::set_num_threads() can be used to manually set the number of threads
For OpenCL kernels:
All the kernels are enqueued on the queue associated with CLScheduler.
The queue is then flushed.
Note
The function will not block until the kernels are executed. It is the user's responsibility to wait.
Will call prepare() on first run if hasn't been done
Implements IFunction.
Definition at line 128 of file CLStridedSlice.cpp.
 {
     ITensorPack pack;
     pack.add_tensor(TensorType::ACL_SRC, _impl->src);
     pack.add_tensor(TensorType::ACL_DST, _impl->dst);
     _impl->op->run(pack);
 }
References arm_compute::ACL_DST, arm_compute::ACL_SRC, ITensorPack::add_tensor(), and arm_compute::test::validation::pack.
validate()
Status validate (const ITensorInfo * input, const ITensorInfo * output, const Coordinates & starts, const Coordinates & ends, const BiStrides & strides, int32_t begin_mask = 0, int32_t end_mask = 0, int32_t shrink_axis_mask = 0) static
Static function to check if given info will lead to a valid configuration of CLStridedSlice.
Note
Supported tensor rank: up to 4
Parameters
[in] input Source tensor. Data type supported: All.
[in] output Destination tensor. Data type supported: Same as input
[in] starts The starts of the dimensions of the input tensor to be sliced. The length must be of rank(input).
[in] ends The ends of the dimensions of the input tensor to be sliced. The length must be of rank(input).
[in] strides The strides of the dimensions of the input tensor to be sliced. The length must be of rank(input).
[in] begin_mask (Optional) If the ith bit of begin_mask is set, starts[i] is ignored and the fullest possible range in that dimension is used instead.
[in] end_mask (Optional) If the ith bit of end_mask is set, ends[i] is ignored and the fullest possible range in that dimension is used instead.
[in] shrink_axis_mask (Optional) If the ith bit of shrink_axis_mask is set, it implies that the ith specification shrinks the dimensionality by 1. A slice of size 1 starting from starts[i] in the dimension must be preserved.
Definition at line 115 of file CLStridedSlice.cpp.
 {
     return experimental::CLStridedSlice::validate(input, output, starts, ends, strides, begin_mask, end_mask,
                                                   shrink_axis_mask);
 }
References arm_compute::test::validation::input, and CLStridedSlice::validate().
Referenced by CLUnstack::validate().
The documentation for this class was generated from the following files:
arm_compute/runtime/CL/functions/CLStridedSlice.h
src/runtime/CL/functions/CLStridedSlice.cpp