Compute Library: ClTransposedConvolution Class Reference
ClTransposedConvolution Class Reference
Basic function to simulate a directly convolution layer.
#include <ClTransposedConvolution.h>
Public Member Functions
ClTransposedConvolution ()=default
Default constructor.
~ClTransposedConvolution ()=default
Default Destructor.
ClTransposedConvolution (const ClTransposedConvolution &)=delete
Prevent instances of this class from being copied (As this class contains pointers)
ClTransposedConvolution (ClTransposedConvolution &&)=default
Default move constructor.
ClTransposedConvolution & operator= (const ClTransposedConvolution &)=delete
Prevent instances of this class from being copied (As this class contains pointers)
ClTransposedConvolution & operator= (ClTransposedConvolution &&)=default
Default move assignment operator.
void configure (const CLCompileContext &compile_context, const ITensorInfo *input, const ITensorInfo *weights, const ITensorInfo *biases, ITensorInfo *output, const PadStrideInfo &deconv_info)
Set the input, weights, biases and output tensors.
void run (ITensorPack &tensors) override
Run the kernels contained in the function.
Public Member Functions inherited from ICLOperator
ICLOperator (IRuntimeContext *ctx=nullptr)
Constructor.
ICLOperator (const ICLOperator &)=delete
Prevent instances of this class from being copied (As this class contains pointers)
ICLOperator (ICLOperator &&)=default
Default move constructor.
ICLOperator & operator= (const ICLOperator &)=delete
Prevent instances of this class from being copied (As this class contains pointers)
ICLOperator & operator= (ICLOperator &&)=default
Default move assignment operator.
void prepare (ITensorPack &constants) override
Prepare the function for executing.
MemoryRequirements workspace () const override
Return the memory requirements required by the workspace.
Public Member Functions inherited from IOperator
virtual ~IOperator ()=default
Destructor.
Static Public Member Functions
static Status validate (const ITensorInfo *input, const ITensorInfo *weights, const ITensorInfo *biases, const ITensorInfo *output, const PadStrideInfo &deconv_info)
Static function to check if given info will lead to a valid configuration.
Detailed Description
Basic function to simulate a directly convolution layer.
This function calls the following OpenCL kernels:
opencl::ClTransposedConvolution
Definition at line 38 of file ClTransposedConvolution.h.
Constructor & Destructor Documentation
ClTransposedConvolution() [1/3]
ClTransposedConvolution () default
Default constructor.
~ClTransposedConvolution()
~ClTransposedConvolution () default
Default Destructor.
ClTransposedConvolution() [2/3]
ClTransposedConvolution (const ClTransposedConvolution &) delete
Prevent instances of this class from being copied (As this class contains pointers)
ClTransposedConvolution() [3/3]
ClTransposedConvolution (ClTransposedConvolution &&) default
Default move constructor.
Member Function Documentation
configure()
void configure (const CLCompileContext & compile_context, const ITensorInfo * input, const ITensorInfo * weights, const ITensorInfo * biases, ITensorInfo * output, const PadStrideInfo & deconv_info)
Set the input, weights, biases and output tensors.
Note
: Only NHWC data layout is supported
Parameters
[in] compile_context The compile context to be used.
[in] input Input tensor info with dimensions [IFM, width, height, batch] Data types supported: F16/F32/QASYMM8/QASYMM8_SIGNED.
[in] weights Weight tensor info with dimensions [IFM, width, height, OFM]. Data type supported: Same as input
[in] biases (Optional) Biases tensor info. Biases are 1D tensor with dimension [OFM]. Data type supported: Should match input data type if floating point, otherwise S32.
[out] output Output tensor info with dimensions [OFM, width, height, batch] The 1st dimension must be equal to the 4th dimension of the weights tensor. Data types supported: Same as input.
[in] deconv_info Contains padding and stride information described in PadStrideInfo.
Definition at line 36 of file ClTransposedConvolution.cpp.
 {
     ARM_COMPUTE_ERROR_ON_NULLPTR(input);
     ARM_COMPUTE_LOG_PARAMS(input, weights, biases, output, deconv_info);
     auto kernel_object = std::make_unique<kernels::ClTransposedConvolutionKernel>();
     kernel_object->set_target(CLScheduler::get().target());
     kernel_object->configure(compile_context, input, weights, biases, output, deconv_info);
     _transposed_conv_kernel = std::move(kernel_object);
 }
References ARM_COMPUTE_ERROR_ON_NULLPTR, ARM_COMPUTE_LOG_PARAMS, CLScheduler::get(), and arm_compute::test::validation::input.
operator=() [1/2]
ClTransposedConvolution& operator= (ClTransposedConvolution &&) default
Default move assignment operator.
operator=() [2/2]
ClTransposedConvolution& operator= (const ClTransposedConvolution &) delete
Prevent instances of this class from being copied (As this class contains pointers)
run()
void run (ITensorPack & tensors) override virtual
Run the kernels contained in the function.
Parameters
[in] tensors Vector that contains the tensors to operate on.
Reimplemented from ICLOperator.
Definition at line 62 of file ClTransposedConvolution.cpp.
 {
     CLScheduler::get().enqueue_op(*_transposed_conv_kernel.get(), tensors, false);
 }
References CLScheduler::enqueue_op(), and CLScheduler::get().
validate()
Status validate (const ITensorInfo * input, const ITensorInfo * weights, const ITensorInfo * biases, const ITensorInfo * output, const PadStrideInfo & deconv_info) static
Static function to check if given info will lead to a valid configuration.
Similar to ClTransposedConvolution::configure()
Returns
a status
Definition at line 51 of file ClTransposedConvolution.cpp.
 {
     ARM_COMPUTE_RETURN_ON_ERROR(
         kernels::ClTransposedConvolutionKernel::validate(input, weights, biases, output, deconv_info));
     return Status{};
 }
References ARM_COMPUTE_RETURN_ON_ERROR, arm_compute::test::validation::input, and ClTransposedConvolutionKernel::validate().
Referenced by CLDeconvolutionLayer::validate().
The documentation for this class was generated from the following files:
src/gpu/cl/operators/ClTransposedConvolution.h
src/gpu/cl/operators/ClTransposedConvolution.cpp