Compute Library: GpuWorkloadContext::Impl Class Reference
GpuWorkloadContext::Impl Class Reference
Internal implementation of workload context.
#include <GpuWorkloadContextImpl.h>
Public Member Functions
Impl (GpuLanguage gpu_language, CLCompileContext *cl_compile_ctx)
Constructor.
Impl (Impl &)=default
Copy constructor.
Impl & operator= (Impl &)=default
Assignment.
GpuLanguage gpu_language () const
Get target GPU language.
const CLCompileContext * cl_compile_context () const
Get CL compile context.
const MemoryDescriptorMap & mem_map () const
Get memory descriptor registry.
void register_user_tensor (ITensorInfo &tensor_info)
Set a new ID and register the user tensor info.
ITensorInfo * create_virtual_tensor ()
Create a virtual (see MemoryType) tensor info and save it.
ITensorInfo * create_auxiliary_tensor (const ITensorInfo &tensor_info)
Create an auxiliary (see MemoryType) tensor info and save it.
ITensorInfo * get_tensor_info (ITensorInfo::Id id)
Get tensor info created by this context, from id.
const ITensorInfo * get_tensor_info (ITensorInfo::Id id) const
Get tensor info created by this context, from id.
Detailed Description
Internal implementation of workload context.
Definition at line 40 of file GpuWorkloadContextImpl.h.
Constructor & Destructor Documentation
Impl() [1/2]
Impl (GpuLanguage gpu_language, CLCompileContext * cl_compile_ctx)
Constructor.
Parameters
[in] gpu_language Target GPU language.
[in] cl_compile_ctx CL compile context.
Definition at line 78 of file GpuWorkloadContext.cpp.
     : _gpu_language(gpu_language),
       _cl_compile_ctx(cl_compile_ctx),
       _next_tensor_id(1),
       _mem_map(),
       _managed_tensor_info()
 {
 }
Impl() [2/2]
Impl (Impl &) default
Copy constructor.
Member Function Documentation
cl_compile_context()
const CLCompileContext * cl_compile_context () const
Get CL compile context.
Definition at line 92 of file GpuWorkloadContext.cpp.
 {
     return _cl_compile_ctx;
 }
create_auxiliary_tensor()
ITensorInfo * create_auxiliary_tensor (const ITensorInfo & tensor_info)
Create an auxiliary (see MemoryType) tensor info and save it.
Parameters
[in] tensor_info ITensorInfo to copy from
Returns
ITensorInfo* The created auxiliary tensor info object pointer
Definition at line 125 of file GpuWorkloadContext.cpp.
 {
     auto       tensor_info = std::make_unique<TensorInfo>(itensor_info);
     const auto tensor_id   = next_tensor_id();
     tensor_info->set_id(tensor_id);
     _mem_map[tensor_id] = MemoryDescriptor{MemoryType::Auxiliary, AuxMemoryInfo{tensor_info->total_size()}};
     auto inserted       = _managed_tensor_info.emplace(tensor_info->id(), std::move(tensor_info));
     return inserted.first->second.get();
 }
References arm_compute::experimental::dynamic_fusion::Auxiliary, and tensor_info.
Referenced by GpuWorkloadSketch::Implementation::create_auxiliary_tensor().
create_virtual_tensor()
ITensorInfo * create_virtual_tensor ()
Create a virtual (see MemoryType) tensor info and save it.
Returns
ITensorInfo* The created virtual tensor info object pointer
Definition at line 115 of file GpuWorkloadContext.cpp.
 {
     auto       tensor_info = std::make_unique<TensorInfo>();
     const auto tensor_id   = -next_tensor_id();
     tensor_info->set_id(tensor_id);
     _mem_map[tensor_id] = MemoryDescriptor{MemoryType::Virtual};
     auto inserted       = _managed_tensor_info.emplace(tensor_info->id(), std::move(tensor_info));
     return inserted.first->second.get();
 }
References tensor_info, and arm_compute::experimental::dynamic_fusion::Virtual.
Referenced by GpuWorkloadSketch::Implementation::create_virtual_tensor().
get_tensor_info() [1/2]
ITensorInfo * get_tensor_info (ITensorInfo::Id id)
Get tensor info created by this context, from id.
Definition at line 135 of file GpuWorkloadContext.cpp.
 {
     return _managed_tensor_info.at(id).get();
 }
Referenced by GpuWorkloadSketch::Implementation::get_tensor_info().
get_tensor_info() [2/2]
const ITensorInfo * get_tensor_info (ITensorInfo::Id id) const
Get tensor info created by this context, from id.
Definition at line 140 of file GpuWorkloadContext.cpp.
 {
     return _managed_tensor_info.at(id).get();
 }
gpu_language()
GpuLanguage gpu_language () const
Get target GPU language.
Definition at line 87 of file GpuWorkloadContext.cpp.
 {
     return _gpu_language;
 }
mem_map()
const MemoryDescriptorMap & mem_map () const
Get memory descriptor registry.
Definition at line 97 of file GpuWorkloadContext.cpp.
 {
     return _mem_map;
 }
Referenced by GpuWorkloadSketch::Implementation::generate_source_code().
operator=()
Impl& operator= (Impl &) default
Assignment.
register_user_tensor()
void register_user_tensor (ITensorInfo & tensor_info)
Set a new ID and register the user tensor info.
Parameters
[in,out] tensor_info The tensor info to be registered.
Definition at line 102 of file GpuWorkloadContext.cpp.
 {
     ARM_COMPUTE_ERROR_ON(tensor_info.has_valid_id());
     const auto tensor_id = next_tensor_id();
     tensor_info.set_id(tensor_id);
     _mem_map[tensor_id] = MemoryDescriptor{MemoryType::User};
     // Save a *copy* of the user tensor info in workload context for future reference
     // Note that this means if the user modifies the @p tensor_info, the change will not be reflected in the context
     _managed_tensor_info.emplace(tensor_info.id(), std::make_unique<TensorInfo>(tensor_info));
 }
References ARM_COMPUTE_ERROR_ON, tensor_info, and arm_compute::experimental::dynamic_fusion::User.
The documentation for this class was generated from the following files:
src/dynamic_fusion/sketch/gpu/GpuWorkloadContextImpl.h
src/dynamic_fusion/sketch/gpu/GpuWorkloadContext.cpp