Compute Library: GpuCkwKernelWriter Class Reference
GpuCkwKernelWriter Class Reference
Extended implementation of kernel writer for dynamic fusion.
#include <GpuCkwKernelWriter.h>
Public Member Functions
GpuCkwKernelWriter (ckw::Kernel &kernel)
Initialize a new instance of GpuCkwKernelWriter class.
void op_load_once (GpuCkwComponentArgument *tensor_or_tile, const ckw::TensorTileSampler &sampler)
Load the user tensor to the tile in the same component argument if it hasn't been loaded.
Detailed Description
Extended implementation of kernel writer for dynamic fusion.
Definition at line 46 of file GpuCkwKernelWriter.h.
Constructor & Destructor Documentation
GpuCkwKernelWriter()
GpuCkwKernelWriter (ckw::Kernel & kernel) explicit
Initialize a new instance of GpuCkwKernelWriter class.
Parameters
[in] kernel The kernel to be generated.
Definition at line 39 of file GpuCkwKernelWriter.cpp.
                                                         : KernelWriter(kernel)
 {
 }
Member Function Documentation
op_load_once()
void op_load_once (GpuCkwComponentArgument * tensor_or_tile, const ckw::TensorTileSampler & sampler)
Load the user tensor to the tile in the same component argument if it hasn't been loaded.
Parameters
[in] tensor_or_tile The component argument that is either a user tensor or a virtual tensor.
[in] sampler The tensor sampling information to load the tile.
Definition at line 43 of file GpuCkwKernelWriter.cpp.
 {
     if (!tensor_or_tile->has_tile())
     {
         CKW_ASSERT(tensor_or_tile->has_tensor());
         auto &tensor = tensor_or_tile->tensor();
         const auto tile_name = tensor.name() + "_tile";
         auto      &tile =
             declare_tile(tile_name.c_str(), ckw::TileInfo(tensor.data_type(), sampler.height(), sampler.width()));
         op_load(tile, tensor, sampler);
         tensor_or_tile->init_virtual_tensor(tile, sampler);
     }
 }
References GpuCkwComponentArgument::has_tensor(), GpuCkwComponentArgument::has_tile(), GpuCkwComponentArgument::init_virtual_tensor(), tensor, GpuCkwComponentArgument::tensor(), and arm_compute::test::validation::reference::tile().
Referenced by arm_compute::experimental::dynamic_fusion::load_src_dst_tiles_and_prepare_sampler(), GpuCkwCast::write_component_code(), and GpuCkwElementwiseBinary::write_component_code().
The documentation for this class was generated from the following files:
src/dynamic_fusion/sketch/gpu/ckw_driver/GpuCkwKernelWriter.h
src/dynamic_fusion/sketch/gpu/ckw_driver/GpuCkwKernelWriter.cpp