Compute Library: GpuSub Class Reference
GpuSub Class Reference final
Operator interface.
#include <GpuSub.h>
Static Public Member Functions
static ITensorInfo * create_op (GpuWorkloadSketch &sketch, ITensorInfo *lhs, ITensorInfo *rhs)
Create an operator and fuse it into the workload sketch.
static Status is_supported_op (const GpuWorkloadContext &context, const ITensorInfo *lhs, const ITensorInfo *rhs)
Check if the operator configuration is supported, irrespective of fusion.
static Status validate_op (const GpuWorkloadSketch &sketch, const ITensorInfo *rhs, const ITensorInfo *lhs)
Validate the operator and check if its configuration is supported and if it can be fused into the workload sketch.
Detailed Description
Operator interface.
Definition at line 43 of file GpuSub.h.
Member Function Documentation
create_op()
ITensorInfo * create_op (GpuWorkloadSketch & sketch, ITensorInfo * lhs, ITensorInfo * rhs) static
Create an operator and fuse it into the workload sketch.
Note
If validate_op() fails, the creation also fails and may throw an error.
If validate_op() fails, sketch remains unchanged and valid.
Valid data type configurations:
lhs rhs dst
F16 F16 F16
F32 F32 F32
S32 S32 S32
S16 S16 S16
U8 U8 U8
Valid data layouts:
Any
Parameters
[in,out] sketch Workload sketch into which the operator will be fused
[in] lhs Left hand side tensor info. Data types supported: U8/S16/S32/F16/F32.
[in] rhs Right hand side tensor info. Same as lhs.
Returns
Pointer for the destination tensor info
Definition at line 62 of file GpuSub.cpp.
 {
     // No need to log or validate as they'll be handled inside GpuElementwiseBinaryCommon::create_op()
     // Set the elementwise operation to Sub then call the elementwise common create_op
     ElementwiseBinaryCommonAttributes common_attributes{};
     common_attributes.operation(ElementwiseBinaryCommonAttributes::ElementwiseOp::Sub);
     return GpuElementwiseBinaryCommon::create_op(sketch, lhs, rhs, common_attributes);
 }
References GpuElementwiseBinaryCommon::create_op(), ElementwiseBinaryCommonAttributes::operation(), arm_compute::test::validation::sketch, and ElementwiseBinaryCommonAttributes::Sub.
is_supported_op()
Status is_supported_op (const GpuWorkloadContext & context, const ITensorInfo * lhs, const ITensorInfo * rhs) static
Check if the operator configuration is supported, irrespective of fusion.
Parameters
[in] context Workload context within which the operator is running
[in] lhs Left hand side tensor info. Data types supported: U8/S16/S32/F16/F32.
[in] rhs Right hand side tensor info. Same as lhs.
Returns
Status
Definition at line 49 of file GpuSub.cpp.
 {
     ARM_COMPUTE_RETURN_ERROR_ON_NULLPTR(lhs, rhs);
     ARM_COMPUTE_RETURN_ERROR_ON_DATA_TYPE_CHANNEL_NOT_IN(lhs, 1, DataType::F16, DataType::F32, DataType::U8,
                                                          DataType::S16, DataType::S32);
     ARM_COMPUTE_RETURN_ERROR_ON_MSG(lhs->data_type() != rhs->data_type(), "Input tensors must be the same data type");
     // Set the elementwise operation to Sub then call the elementwise common is_supported_op
     ElementwiseBinaryCommonAttributes common_attributes{};
     common_attributes.operation(ElementwiseBinaryCommonAttributes::ElementwiseOp::Sub);
     return GpuElementwiseBinaryCommon::is_supported_op(context, lhs, rhs, common_attributes);
 }
References ARM_COMPUTE_RETURN_ERROR_ON_DATA_TYPE_CHANNEL_NOT_IN, ARM_COMPUTE_RETURN_ERROR_ON_MSG, ARM_COMPUTE_RETURN_ERROR_ON_NULLPTR, arm_compute::test::validation::context, ITensorInfo::data_type(), arm_compute::F16, arm_compute::F32, GpuElementwiseBinaryCommon::is_supported_op(), ElementwiseBinaryCommonAttributes::operation(), arm_compute::S16, arm_compute::S32, ElementwiseBinaryCommonAttributes::Sub, and arm_compute::U8.
validate_op()
Status validate_op (const GpuWorkloadSketch & sketch, const ITensorInfo * rhs, const ITensorInfo * lhs) static
Validate the operator and check if its configuration is supported and if it can be fused into the workload sketch.
Parameters are similar to GpuSub::create_op()
Returns
Status
Definition at line 36 of file GpuSub.cpp.
 {
     ARM_COMPUTE_RETURN_ERROR_ON_NULLPTR(lhs, rhs);
     ARM_COMPUTE_RETURN_ERROR_ON_DATA_TYPE_CHANNEL_NOT_IN(lhs, 1, DataType::F16, DataType::F32, DataType::U8,
                                                          DataType::S16, DataType::S32);
     ARM_COMPUTE_RETURN_ERROR_ON_MSG(lhs->data_type() != rhs->data_type(), "Input tensors must be the same data type");
     // Set the elementwise operation to Sub then call the elementwise common validate_op
     ElementwiseBinaryCommonAttributes common_attributes{};
     common_attributes.operation(ElementwiseBinaryCommonAttributes::ElementwiseOp::Sub);
     return GpuElementwiseBinaryCommon::validate_op(sketch, lhs, rhs, common_attributes);
 }
References ARM_COMPUTE_RETURN_ERROR_ON_DATA_TYPE_CHANNEL_NOT_IN, ARM_COMPUTE_RETURN_ERROR_ON_MSG, ARM_COMPUTE_RETURN_ERROR_ON_NULLPTR, ITensorInfo::data_type(), arm_compute::F16, arm_compute::F32, ElementwiseBinaryCommonAttributes::operation(), arm_compute::S16, arm_compute::S32, arm_compute::test::validation::sketch, ElementwiseBinaryCommonAttributes::Sub, arm_compute::U8, and GpuElementwiseBinaryCommon::validate_op().
The documentation for this class was generated from the following files:
arm_compute/dynamic_fusion/sketch/gpu/operators/GpuSub.h
src/dynamic_fusion/sketch/gpu/operators/GpuSub.cpp