Compute Library: CLConv3D Class Reference
CLConv3D Class Reference
Basic function to compute the convolution3d layer.
#include <CLConv3D.h>
Public Member Functions
CLConv3D ()
Construtor.
~CLConv3D ()
Destructor.
CLConv3D (const CLConv3D &)=delete
Prevent instances of this class from being copied (As this class contains pointers)
CLConv3D (CLConv3D &&)=default
Default move constructor.
CLConv3D & operator= (const CLConv3D &)=delete
Prevent instances of this class from being copied (As this class contains pointers)
CLConv3D & operator= (CLConv3D &&)=default
Default move assignment operator.
void configure (const CLCompileContext &compile_context, const ICLTensor *src, const ICLTensor *weights, const ICLTensor *biases, ICLTensor *dst, const Conv3dInfo &conv3d_info)
Set the src and dst tensors.
void configure (const ICLTensor *src, const ICLTensor *weights, const ICLTensor *biases, ICLTensor *dst, const Conv3dInfo &conv3d_info)
Set the src and dst tensors.
void run () override
Run the kernels contained in the function.
Public Member Functions inherited from IFunction
virtual ~IFunction ()=default
Destructor.
virtual void prepare ()
Prepare the function for executing.
Static Public Member Functions
static Status validate (const ITensorInfo *src, const ITensorInfo *weights, const ITensorInfo *biases, const ITensorInfo *dst, const Conv3dInfo &conv3d_info)
Static function to check if given info will lead to a valid configuration of CLConv3D.
Detailed Description
Basic function to compute the convolution3d layer.
This function calls the following OpenCL kernels/functions:
opencl::ClDirectConv3d
Definition at line 43 of file CLConv3D.h.
Constructor & Destructor Documentation
CLConv3D() [1/3]
CLConv3D ()
Construtor.
Definition at line 43 of file CLConv3D.cpp.
                    : _impl(std::make_unique<Impl>())
 {
 }
~CLConv3D()
~CLConv3D () default
Destructor.
CLConv3D() [2/3]
CLConv3D (const CLConv3D &) delete
Prevent instances of this class from being copied (As this class contains pointers)
CLConv3D() [3/3]
CLConv3D (CLConv3D &&) default
Default move constructor.
Member Function Documentation
configure() [1/2]
void configure (const CLCompileContext & compile_context, const ICLTensor * src, const ICLTensor * weights, const ICLTensor * biases, ICLTensor * dst, const Conv3dInfo & conv3d_info)
Set the src and dst tensors.
Valid data layouts:
NDHWC
Valid data type configurations:
src0 src1 src2 dst
F16 F16 F16 F16
F32 F32 F32 F32
QASYMM8 QASYMM8 S32 QASYMM8
QASYMM8_SIGNED QASYMM8_SIGNED S32 QASYMM8_SIGNED
Parameters
[in] compile_context The compile context to be used.
[in] src Source tensor. 4 lower dimensions represent a single src [IFM, width, height, depth], while every optional dimension from 5 and above represent a batch of srcs.
[in] weights Weights tensor. Weights are 5D tensor with dimensions [OFM, IFM, kernel_w, kernel_h, kernel_d].
[in] biases Biases tensor. Shared biases supported. Biases are 1D tensor with dimensions [OFM].
[out] dst Destination tensor. 4 lower dimensions represent a single dst [OFM, width, height, depth], while the rest represent batch of dsts.
[in] conv3d_info Contains strides, padding, rounding, activation, dilation and fast math information. Activation and fast math are currently unused.
Definition at line 58 of file CLConv3D.cpp.
 {
     ARM_COMPUTE_ERROR_ON_NULLPTR(src, weights, dst);
     ARM_COMPUTE_ERROR_THROW_ON(CLConv3D::validate(
         src->info(), weights->info(), ((biases != nullptr) ? biases->info() : nullptr), dst->info(), conv3d_info));
     _impl->src     = src;
     _impl->weights = weights;
     _impl->biases  = biases;
     _impl->dst     = dst;
     _impl->op = std::make_unique<opencl::ClDirectConv3d>();
     _impl->op->configure(compile_context, _impl->src->info(), _impl->weights->info(),
                          _impl->biases ? _impl->biases->info() : nullptr, _impl->dst->info(), conv3d_info);
 }
References ARM_COMPUTE_ERROR_ON_NULLPTR, ARM_COMPUTE_ERROR_THROW_ON, arm_compute::test::validation::dst, ITensor::info(), arm_compute::test::validation::src, and CLConv3D::validate().
Referenced by CLConv3D::configure().
configure() [2/2]
void configure (const ICLTensor * src, const ICLTensor * weights, const ICLTensor * biases, ICLTensor * dst, const Conv3dInfo & conv3d_info)
Set the src and dst tensors.
Similar to CLConv3D::configure() but using the default compile context
Definition at line 49 of file CLConv3D.cpp.
 {
     configure(CLKernelLibrary::get().get_compile_context(), src, weights, biases, dst, conv3d_info);
 }
References CLConv3D::configure(), arm_compute::test::validation::dst, CLKernelLibrary::get(), and arm_compute::test::validation::src.
operator=() [1/2]
CLConv3D& operator= (CLConv3D &&) default
Default move assignment operator.
operator=() [2/2]
CLConv3D& operator= (const CLConv3D &) delete
Prevent instances of this class from being copied (As this class contains pointers)
run()
void run () override virtual
Run the kernels contained in the function.
For CPU kernels:
Multi-threading is used for the kernels which are parallelisable.
By default std::thread::hardware_concurrency() threads are used.
Note
CPPScheduler::set_num_threads() can be used to manually set the number of threads
For OpenCL kernels:
All the kernels are enqueued on the queue associated with CLScheduler.
The queue is then flushed.
Note
The function will not block until the kernels are executed. It is the user's responsibility to wait.
Will call prepare() on first run if hasn't been done
Implements IFunction.
Definition at line 88 of file CLConv3D.cpp.
 {
     ITensorPack pack;
     pack.add_tensor(TensorType::ACL_SRC_0, _impl->src);
     pack.add_tensor(TensorType::ACL_SRC_1, _impl->weights);
     pack.add_tensor(TensorType::ACL_SRC_2, _impl->biases);
     pack.add_tensor(TensorType::ACL_DST, _impl->dst);
     _impl->op->run(pack);
 }
References arm_compute::ACL_DST, arm_compute::ACL_SRC_0, arm_compute::ACL_SRC_1, arm_compute::ACL_SRC_2, ITensorPack::add_tensor(), and arm_compute::test::validation::pack.
validate()
Status validate (const ITensorInfo * src, const ITensorInfo * weights, const ITensorInfo * biases, const ITensorInfo * dst, const Conv3dInfo & conv3d_info) static
Static function to check if given info will lead to a valid configuration of CLConv3D.
Similar to CLConv3D::configure()
Returns
a status
Definition at line 79 of file CLConv3D.cpp.
 {
     return opencl::ClDirectConv3d::validate(src, weights, biases, dst, conv3d_info);
 }
References arm_compute::test::validation::dst, arm_compute::test::validation::src, and ClDirectConv3d::validate().
Referenced by CLConv3D::configure().
The documentation for this class was generated from the following files:
arm_compute/runtime/CL/functions/CLConv3D.h
src/runtime/CL/functions/CLConv3D.cpp