Compute Library: ClDWCNativeKernelConfigurationFactory Class Reference
ClDWCNativeKernelConfigurationFactory Class Reference final
ClDWCNativeKernelConfigurationFactory factory class.
#include <ClDWCNativeKernelConfig.h>
Static Public Member Functions
static std::unique_ptr< IClDWCNativeKernelConfig > create (GPUTarget gpu)
Static method to call the ClDWCNative kernel configuration class accordingly with the GPU target.
Detailed Description
ClDWCNativeKernelConfigurationFactory factory class.
Definition at line 38 of file ClDWCNativeKernelConfig.h.
Member Function Documentation
create()
static std::unique_ptr<IClDWCNativeKernelConfig> create (GPUTarget gpu) inline static
Static method to call the ClDWCNative kernel configuration class accordingly with the GPU target.
Parameters
[in] gpu GPU target
Returns
IClDWCNativeKernelConfig
Definition at line 47 of file ClDWCNativeKernelConfig.h.
     {
         switch (get_arch_from_target(gpu))
         {
             case GPUTarget::MIDGARD:
                 // The heuristic for Midgard is the same as the one used for Arm Mali-G71
                 return std::make_unique<ClDWCNativeDefaultConfigBifrost>(GPUTarget::G71);
             case GPUTarget::BIFROST:
                 return std::make_unique<ClDWCNativeDefaultConfigBifrost>(gpu);
             case GPUTarget::VALHALL:
                 return std::make_unique<ClDWCNativeDefaultConfigValhall>(gpu);
             default:
                 ARM_COMPUTE_ERROR("Not supported GPU target");
         }
     }
References ARM_COMPUTE_ERROR, arm_compute::BIFROST, arm_compute::G71, arm_compute::get_arch_from_target(), arm_compute::MIDGARD, and arm_compute::VALHALL.
Referenced by CLDepthwiseConvolutionLayer::configure(), GpuDepthwiseConv2d::create_op(), and CLDepthwiseConvolutionLayer::validate().
The documentation for this class was generated from the following file:
src/runtime/heuristics/dwc_native/ClDWCNativeKernelConfig.h