Compute Library: CLGatherKernel Class Reference
CLGatherKernel Class Reference
Interface for the kernel to perform tensor reshaping.
#include <CLGatherKernel.h>
Public Member Functions
CLGatherKernel ()
Default constructor.
CLGatherKernel (const CLGatherKernel &)=delete
Prevent instances of this class from being copied (As this class contains pointers)
CLGatherKernel & operator= (const CLGatherKernel &)=delete
Prevent instances of this class from being copied (As this class contains pointers)
CLGatherKernel (CLGatherKernel &&)=default
Allow instances of this class to be moved.
CLGatherKernel & operator= (CLGatherKernel &&)=default
Allow instances of this class to be moved.
~CLGatherKernel ()=default
Default destructor.
void configure (const ICLTensor *input, const ICLTensor *indices, ICLTensor *output, int axis=0)
Initialise the kernel's inputs and outputs.
void configure (const CLCompileContext &compile_context, const ICLTensor *input, const ICLTensor *indices, ICLTensor *output, int axis=0)
Initialise the kernel's inputs and outputs.
void run (const Window &window, cl::CommandQueue &queue) override
Enqueue the OpenCL kernel to process the given window on the passed OpenCL command queue.
Public Member Functions inherited from ICLKernel
ICLKernel ()
Constructor.
cl::Kernel & kernel ()
Returns a reference to the OpenCL kernel of this object.
CLKernelType type () const
Returns the CL kernel type.
template<typename T >
void add_1D_array_argument (unsigned int &idx, const ICLArray< T > *array, const Strides &strides, unsigned int num_dimensions, const Window &window)
Add the passed 1D array's parameters to the object's kernel's arguments starting from the index idx.
void add_1D_tensor_argument (unsigned int &idx, const ICLTensor *tensor, const Window &window)
Add the passed 1D tensor's parameters to the object's kernel's arguments starting from the index idx.
void add_1D_tensor_argument_if (bool cond, unsigned int &idx, const ICLTensor *tensor, const Window &window)
Add the passed 1D tensor's parameters to the object's kernel's arguments starting from the index idx if the condition is true.
void add_2D_tensor_argument (unsigned int &idx, const ICLTensor *tensor, const Window &window)
Add the passed 2D tensor's parameters to the object's kernel's arguments starting from the index idx.
void add_2D_tensor_argument_if (bool cond, unsigned int &idx, const ICLTensor *tensor, const Window &window)
Add the passed 2D tensor's parameters to the object's kernel's arguments starting from the index idx if the condition is true.
void add_3D_tensor_argument (unsigned int &idx, const ICLTensor *tensor, const Window &window)
Add the passed 3D tensor's parameters to the object's kernel's arguments starting from the index idx.
void add_4D_tensor_argument (unsigned int &idx, const ICLTensor *tensor, const Window &window)
Add the passed 4D tensor's parameters to the object's kernel's arguments starting from the index idx.
void add_5D_tensor_argument (unsigned int &idx, const ICLTensor *tensor, const Window &window)
Add the passed 5D tensor's parameters to the object's kernel's arguments starting from the index idx.
void add_3d_tensor_nhw_argument (unsigned int &idx, const ICLTensor *tensor)
Add the passed NHW 3D tensor's parameters to the object's kernel's arguments by passing strides, dimensions and the offset to the first valid element in bytes.
void add_4d_tensor_nhwc_argument (unsigned int &idx, const ICLTensor *tensor)
Add the passed NHWC 4D tensor's parameters to the object's kernel's arguments by passing strides, dimensions and the offset to the first valid element in bytes.
virtual void run_op (ITensorPack &tensors, const Window &window, cl::CommandQueue &queue)
Enqueue the OpenCL kernel to process the given window on the passed OpenCL command queue.
template<typename T >
void add_argument (unsigned int &idx, T value)
Add the passed parameters to the object's kernel's arguments starting from the index idx.
void set_lws_hint (const cl::NDRange &lws_hint)
Set the Local-Workgroup-Size hint.
cl::NDRange lws_hint () const
Return the Local-Workgroup-Size hint.
void set_wbsm_hint (const cl_int &wbsm_hint)
Set the workgroup batch size modifier hint.
cl_int wbsm_hint () const
Return the workgroup batch size modifier hint.
const std::string & config_id () const
Get the configuration ID.
void set_target (GPUTarget target)
Set the targeted GPU architecture.
void set_target (cl::Device &device)
Set the targeted GPU architecture according to the CL device.
GPUTarget get_target () const
Get the targeted GPU architecture.
size_t get_max_workgroup_size ()
Get the maximum workgroup size for the device the CLKernelLibrary uses.
cl::NDRange get_cached_gws () const
Get the cached gws used to enqueue this kernel.
void cache_gws (const cl::NDRange &gws)
Cache the latest gws used to enqueue this kernel.
template<unsigned int dimension_size>
void add_tensor_argument (unsigned &idx, const ICLTensor *tensor, const Window &window)
template<typename T , unsigned int dimension_size>
void add_array_argument (unsigned &idx, const ICLArray< T > *array, const Strides &strides, unsigned int num_dimensions, const Window &window)
Add the passed array's parameters to the object's kernel's arguments starting from the index idx.
Public Member Functions inherited from IKernel
IKernel ()
Constructor.
virtual ~IKernel ()=default
Destructor.
virtual bool is_parallelisable () const
Indicates whether or not the kernel is parallelisable.
virtual BorderSize border_size () const
The size of the border for that kernel.
const Window & window () const
The maximum window the kernel can be executed on.
bool is_window_configured () const
Function to check if the embedded window of this kernel has been configured.
Static Public Member Functions
static Status validate (const ITensorInfo *input, const ITensorInfo *indices, const ITensorInfo *output, int axis=0)
Static function to check if given info will lead to a valid configuration of CLGatherKernel.
Static Public Member Functions inherited from ICLKernel
constexpr static unsigned int num_arguments_per_3d_tensor_nhw ()
Returns the number of arguments enqueued per NHW 3D Tensor object.
constexpr static unsigned int num_arguments_per_4d_tensor_nhwc ()
Returns the number of arguments enqueued per NHWC 4D Tensor object.
constexpr static unsigned int num_arguments_per_1D_array ()
Returns the number of arguments enqueued per 1D array object.
constexpr static unsigned int num_arguments_per_1D_tensor ()
Returns the number of arguments enqueued per 1D tensor object.
constexpr static unsigned int num_arguments_per_2D_tensor ()
Returns the number of arguments enqueued per 2D tensor object.
constexpr static unsigned int num_arguments_per_3D_tensor ()
Returns the number of arguments enqueued per 3D tensor object.
constexpr static unsigned int num_arguments_per_4D_tensor ()
Returns the number of arguments enqueued per 4D tensor object.
static cl::NDRange gws_from_window (const Window &window, bool use_dummy_work_items)
Get the global work size given an execution window.
Detailed Description
Interface for the kernel to perform tensor reshaping.
Definition at line 36 of file CLGatherKernel.h.
Constructor & Destructor Documentation
CLGatherKernel() [1/3]
CLGatherKernel ()
Default constructor.
Definition at line 81 of file CLGatherKernel.cpp.
                                : _input(nullptr), _indices(nullptr), _output(nullptr), _axis(0)
 {
     _type = CLKernelType::ELEMENTWISE;
 }
References arm_compute::ELEMENTWISE.
CLGatherKernel() [2/3]
CLGatherKernel (const CLGatherKernel &) delete
Prevent instances of this class from being copied (As this class contains pointers)
CLGatherKernel() [3/3]
CLGatherKernel (CLGatherKernel &&) default
Allow instances of this class to be moved.
~CLGatherKernel()
~CLGatherKernel () default
Default destructor.
Member Function Documentation
configure() [1/2]
void configure (const CLCompileContext & compile_context, const ICLTensor * input, const ICLTensor * indices, ICLTensor * output, int axis = 0)
Initialise the kernel's inputs and outputs.
Parameters
[in] compile_context The compile context to be used.
[in] input Source tensor. Supported tensor rank: up to 4. Data type supported: All.
[in] indices Indices tensor. Supported tensor rank: up to 1. Must be one of the following types: U32/S32. Each value must be in range [0, input.shape[axis])
[out] output Destination tensor. Data type supported: Same as input
[in] axis (Optional) The axis in input to gather indices from. Negative values wrap around. Defaults to 0
Definition at line 91 of file CLGatherKernel.cpp.
 {
     ARM_COMPUTE_ERROR_ON_NULLPTR(input, output, indices);
     auto padding_info = get_padding_info({input, output, indices});
     ARM_COMPUTE_ERROR_THROW_ON(validate_arguments(input->info(), indices->info(), output->info(), axis));
     // Configure kernel window
     auto win_config = validate_and_configure_window(input->info(), indices->info(), output->info(), axis);
     ARM_COMPUTE_ERROR_THROW_ON(win_config.first);
     _input   = input;
     _output  = output;
     _indices = indices;
     _axis    = wrap_around(axis, static_cast<int>(input->info()->num_dimensions()));
     // Set build options
     CLBuildOptions build_opts;
     build_opts.add_option("-DDATA_TYPE=" +
                           get_cl_unsigned_type_from_element_size(data_size_from_type(input->info()->data_type())));
     build_opts.add_option("-DOUTPUT_DIM_Z=" + support::cpp11::to_string(output->info()->dimension(2)));
     build_opts.add_option("-DINDICES_DIM_Z=" + support::cpp11::to_string(indices->info()->dimension(2)));
     build_opts.add_option("-DINPUT_DIM_Z=" + support::cpp11::to_string(input->info()->dimension(2)));
     build_opts.add_option("-DINDICES_DIMS=" + support::cpp11::to_string(indices->info()->num_dimensions()));
     build_opts.add_option("-DAXIS=" + support::cpp11::to_string(_axis));
     build_opts.add_option("-DINDEX_LIMIT=" + support::cpp11::to_string(input->info()->tensor_shape()[_axis]));
     // Create kernel
     _kernel = create_kernel(compile_context, "gather", build_opts.options());
     ICLKernel::configure_internal(win_config.second);
     ARM_COMPUTE_ERROR_ON(has_padding_changed(padding_info));
 }
References CLBuildOptions::add_option(), ARM_COMPUTE_ERROR_ON, ARM_COMPUTE_ERROR_ON_NULLPTR, ARM_COMPUTE_ERROR_THROW_ON, arm_compute::create_kernel(), arm_compute::data_size_from_type(), ITensorInfo::dimension(), arm_compute::get_cl_unsigned_type_from_element_size(), arm_compute::get_padding_info(), arm_compute::has_padding_changed(), ITensor::info(), arm_compute::test::validation::input, ITensorInfo::num_dimensions(), CLBuildOptions::options(), arm_compute::support::cpp11::to_string(), arm_compute::cpu::kernels::validate_and_configure_window(), arm_compute::cpu::kernels::validate_arguments(), and arm_compute::wrap_around().
configure() [2/2]
void configure (const ICLTensor * input, const ICLTensor * indices, ICLTensor * output, int axis = 0)
Initialise the kernel's inputs and outputs.
Parameters
[in] input Source tensor. Supported tensor rank: up to 4. Data type supported: All.
[in] indices Indices tensor. Supported tensor rank: up to 1. Must be one of the following types: U32/S32. Each value must be in range [0, input.shape[axis])
[out] output Destination tensor. Data type supported: Same as input
[in] axis (Optional) The axis in input to gather indices from. Negative values wrap around. Defaults to 0
Definition at line 86 of file CLGatherKernel.cpp.
 {
     configure(CLKernelLibrary::get().get_compile_context(), input, indices, output, axis);
 }
References CLKernelLibrary::get(), and arm_compute::test::validation::input.
operator=() [1/2]
CLGatherKernel& operator= (CLGatherKernel &&) default
Allow instances of this class to be moved.
operator=() [2/2]
CLGatherKernel& operator= (const CLGatherKernel &) delete
Prevent instances of this class from being copied (As this class contains pointers)
run()
void run (const Window & window, cl::CommandQueue & queue) override virtual
Enqueue the OpenCL kernel to process the given window on the passed OpenCL command queue.
Note
The queue is not flushed by this method, and therefore the kernel will not have been executed by the time this method returns.
Parameters
[in] window Region on which to execute the kernel. (Must be a valid region of the window returned by window()).
[in,out] queue Command queue on which to enqueue the kernel.
Reimplemented from ICLKernel.
Definition at line 136 of file CLGatherKernel.cpp.
 {
     ARM_COMPUTE_ERROR_ON_UNCONFIGURED_KERNEL(this);
     ARM_COMPUTE_ERROR_ON_INVALID_SUBWINDOW(IKernel::window(), window);
     Window       window_collapsed = window.collapse_if_possible(ICLKernel::window(), Window::DimZ);
     unsigned int idx              = 0;
     add_4D_tensor_argument(idx, _input, window_collapsed);
     add_4D_tensor_argument(idx, _indices, window_collapsed);
     add_4D_tensor_argument(idx, _output, window_collapsed);
     enqueue(queue, *this, window_collapsed, lws_hint());
 }
References ICLKernel::add_4D_tensor_argument(), ARM_COMPUTE_ERROR_ON_INVALID_SUBWINDOW, ARM_COMPUTE_ERROR_ON_UNCONFIGURED_KERNEL, Window::collapse_if_possible(), Window::DimZ, arm_compute::enqueue(), ICLKernel::lws_hint(), and IKernel::window().
validate()
Status validate (const ITensorInfo * input, const ITensorInfo * indices, const ITensorInfo * output, int axis = 0) static
Static function to check if given info will lead to a valid configuration of CLGatherKernel.
Parameters
[in] input Source tensor info. Supported tensor rank: up to 4. Data type supported: All.
[in] indices Indices tensor info. Supported tensor rank: up to 4. Must be one of the following types: U32/S32. Each value must be in range [0, input.shape[axis])
[in] output Destination tensor info. Data type supported: Same as input
[in] axis (Optional) The axis in input to gather indices from. Negative values wrap around. Defaults to 0
Returns
a status
Definition at line 128 of file CLGatherKernel.cpp.
 {
     ARM_COMPUTE_RETURN_ON_ERROR(validate_arguments(input, indices, output, axis));
     ARM_COMPUTE_RETURN_ON_ERROR(
         validate_and_configure_window(input->clone().get(), indices->clone().get(), output->clone().get(), axis).first);
     return Status{};
 }
References ARM_COMPUTE_RETURN_ON_ERROR, ICloneable< T >::clone(), arm_compute::test::validation::input, arm_compute::cpu::kernels::validate_and_configure_window(), and arm_compute::cpu::kernels::validate_arguments().
Referenced by CLGather::validate().
The documentation for this class was generated from the following files:
src/core/CL/kernels/CLGatherKernel.h
src/core/CL/kernels/CLGatherKernel.cpp