Compute Library: ClTemplateLogits1DMaxShiftExpSum Class Reference
ClTemplateLogits1DMaxShiftExpSum Class Reference final
#include <ClTemplateLogits1DMaxShiftExpSum.h>
Public Types
using Attributes = ClComponentLogits1DMaxShiftExpSum::Attributes
Public Types inherited from IGpuTemplateComponentWriter
using ComponentGroup = GpuKernelComponentGroup
Public Member Functions
ClTemplateLogits1DMaxShiftExpSum (ComponentId id, const ArgumentPack< ITensorInfo > &tensors, const Attributes &attributes)
Constructor.
ClTemplateLogits1DMaxShiftExpSum (const ClTemplateLogits1DMaxShiftExpSum &)=delete
Prevent instances of this class from being copy constructed.
ClTemplateLogits1DMaxShiftExpSum & operator= (const ClTemplateLogits1DMaxShiftExpSum &)=delete
Prevent instances of this class from being copied.
ClTemplateLogits1DMaxShiftExpSum (ClTemplateLogits1DMaxShiftExpSum &&)=default
Allow instances of this class to be move constructed.
ClTemplateLogits1DMaxShiftExpSum & operator= (ClTemplateLogits1DMaxShiftExpSum &&)=default
Allow instances of this class to be moved.
std::string get_name () const override
Generate kernel component name.
std::string get_component_code (const ComponentGroup &comp_group) const override
Generate kernel component code template.
void declare_variables (GpuKernelVariableTable &vtable, const ComponentGroup &comp_group) const override
Declare all variables used by the component in the vtable.
TagLUT get_tag_lut (const GpuKernelVariableTable &vtable, const ComponentGroup &comp_group) const override
Generate the tag look-up table used to instantiate the component code.
CLBuildOptions get_build_options (const ComponentGroup &comp_group) const override
Generate the build options used in the component.
std::string get_config_id () const override
Generate the component config id string used for tuning.
std::set< std::string > get_headers_list () const override
Generate the header list used in the component.
Window get_window () const override
Generate the execution window for the component.
Public Member Functions inherited from IGpuTemplateComponentWriter
IGpuTemplateComponentWriter (ComponentId id, const ArgumentPack< ITensorInfo > &tensors)
Constructor.
virtual ~IGpuTemplateComponentWriter ()
Destructor.
virtual std::string get_additional_macros () const
Generate additional macros used in the component.
ArgumentPack< ITensorInfo > tensors () const
Get tensor arguments.
ComponentId id () const
Get component id.
Additional Inherited Members
Static Public Attributes inherited from IGpuTemplateComponentWriter
static constexpr GpuKernelArgumentInfo::Type common_tensor_type = GpuKernelArgumentInfo::Type::Tensor_4D_t_Buffer
For now all kernel intermeditate/destination tensors are expected to be of type Tensor_4D_t_Buffer.
Detailed Description
Definition at line 38 of file ClTemplateLogits1DMaxShiftExpSum.h.
Member Typedef Documentation
Attributes
using Attributes = ClComponentLogits1DMaxShiftExpSum::Attributes
Definition at line 41 of file ClTemplateLogits1DMaxShiftExpSum.h.
Constructor & Destructor Documentation
ClTemplateLogits1DMaxShiftExpSum() [1/3]
ClTemplateLogits1DMaxShiftExpSum (ComponentId id, const ArgumentPack< ITensorInfo > & tensors, const Attributes & attributes)
Constructor.
Parameters
[in] id Component id
[in] tensors Tensor arguments to the components
[in] attributes Component attributes
Definition at line 44 of file ClTemplateLogits1DMaxShiftExpSum.cpp.
     : IGpuTemplateComponentWriter{id, tensors}, _src{}, _sum{}, _dst{}, _attributes{attributes}
 {
     _src = this->tensors().get_const_tensor(TensorType::ACL_SRC_0);
     _sum = this->tensors().get_const_tensor(TensorType::ACL_DST_0);
     _dst = this->tensors().get_const_tensor(TensorType::ACL_DST_1);
     ARM_COMPUTE_ERROR_ON_NULLPTR(_src);
     ARM_COMPUTE_ERROR_ON_NULLPTR(_sum);
     ARM_COMPUTE_ERROR_ON_NULLPTR(_dst);
 }
References IGpuTemplateComponentWriter::id(), and IGpuTemplateComponentWriter::tensors().
ClTemplateLogits1DMaxShiftExpSum() [2/3]
ClTemplateLogits1DMaxShiftExpSum (const ClTemplateLogits1DMaxShiftExpSum &) delete
Prevent instances of this class from being copy constructed.
ClTemplateLogits1DMaxShiftExpSum() [3/3]
ClTemplateLogits1DMaxShiftExpSum (ClTemplateLogits1DMaxShiftExpSum &&) default
Allow instances of this class to be move constructed.
Member Function Documentation
declare_variables()
void declare_variables (GpuKernelVariableTable & vtable, const ComponentGroup & comp_group) const override virtual
Declare all variables used by the component in the vtable.
Parameters
[out] vtable Variable table
[in] comp_group Component group of which the component is a part of
Implements IGpuTemplateComponentWriter.
Definition at line 191 of file ClTemplateLogits1DMaxShiftExpSum.cpp.
 {
     vtable.declare_variable(comp_group, _src, GpuKernelArgumentInfo(GpuKernelArgumentInfo::Type::Tensor_3D), "src");
     vtable.declare_variable(comp_group, _sum, GpuKernelArgumentInfo(GpuKernelArgumentInfo::Type::Tensor_3D), "sum");
     vtable.declare_variable(comp_group, _dst, GpuKernelArgumentInfo(GpuKernelArgumentInfo::Type::Tensor_3D), "dst");
 }
References GpuKernelVariableTable::declare_variable(), and GpuKernelArgumentInfo::Tensor_3D.
get_build_options()
CLBuildOptions get_build_options (const ComponentGroup & comp_group) const override virtual
Generate the build options used in the component.
Parameters
[in] comp_group Component group of which the component is a part of
Returns
CLBuildOptions Build options
Reimplemented from IGpuTemplateComponentWriter.
Definition at line 226 of file ClTemplateLogits1DMaxShiftExpSum.cpp.
 {
     ARM_COMPUTE_UNUSED(comp_group);
     CLBuildOptions build_opts{};
     const unsigned int reduction_dim_size = _src->dimension(0);
     const unsigned int vector_size        = adjust_vec_size(serial_vector_size, reduction_dim_size);
     build_opts.add_option("-DN0=" + support::cpp11::to_string(vector_size));
     build_opts.add_option("-DPARTIAL_N0=" + support::cpp11::to_string((reduction_dim_size % vector_size)));
     return build_opts;
 }
References arm_compute::adjust_vec_size(), ARM_COMPUTE_UNUSED, ITensorInfo::dimension(), arm_compute::support::cpp11::to_string(), and arm_compute::cpu::vector_size.
get_component_code()
std::string get_component_code (const ComponentGroup & comp_group) const override virtual
Generate kernel component code template.
Parameters
[in] comp_group Component group of which the component is a part of
Returns
std::string Component code
Implements IGpuTemplateComponentWriter.
Definition at line 62 of file ClTemplateLogits1DMaxShiftExpSum.cpp.
 {
     ARM_COMPUTE_UNUSED(comp_group);
     std::string code = R"_(
 //------------------ START KERNEL {{meta_kernel_id}} ---------------------
 #define VEC_TYPE VEC_DATA_TYPE({{DATA_TYPE}}, N0)
 #define SELECT_TYPE SELECT_VEC_DATA_TYPE({{DATA_TYPE}}, N0)
 {
     __global uchar *src_addr = {{src}}_ptr + {{src}}_offset_first_element_in_bytes + g_ind_1 * {{src}}_stride_y + g_ind_2 * {{src}}_stride_z;
     __global uchar *dst_addr = {{dst}}_ptr + {{dst}}_offset_first_element_in_bytes + g_ind_1 * {{dst}}_stride_y + g_ind_2 * {{dst}}_stride_z;
     Image sum = CONVERT_TENSOR3D_TO_IMAGE_STRUCT({{sum}});
     VEC_TYPE max_val_vec = (VEC_TYPE)({{MINVAL}});
 )_";
     const bool beta_defined = (_attributes.beta() != 1.f);
     if (beta_defined)
     {
         code += R"_(
     VEC_TYPE beta = (VEC_TYPE){{BETA}};
 )_";
     }
     constexpr unsigned int _serial_vector_size = 8;
     const unsigned int     reduction_dim_size  = _src->dimension(0);
     const unsigned int     vector_size         = adjust_vec_size(_serial_vector_size, reduction_dim_size);
     const bool             non_multiple_of_n0  = ((reduction_dim_size % vector_size) != 0);
     if (non_multiple_of_n0)
     {
         code += R"_(
     VEC_TYPE data    = VLOAD(N0)(0, (__global {{DATA_TYPE}} *)src_addr);
     SELECT_TYPE widx = (SELECT_TYPE)PARTIAL_N0 > VEC_OFFS(SELECT_DATA_TYPE({{DATA_TYPE}}), N0);
     max_val_vec      = max(max_val_vec, select((VEC_TYPE)({{MINVAL}}), data, widx));
 )_";
     }
     code += R"_(
     for(uint i = PARTIAL_N0; i < {{SRC_WIDTH}}; i += N0)
     {
         VEC_TYPE data = VLOAD(N0)(0, (__global {{DATA_TYPE}} *)(src_addr + i * sizeof({{DATA_TYPE}})));
         max_val_vec   = max(data, max_val_vec);
     }
     {{DATA_TYPE}} max_val = MAX_REDUCE(max_val_vec, N0);
     VEC_TYPE sum1D = 0;
 )_";
     if (non_multiple_of_n0)
     {
         code += R"_(
     data -= max_val;
 )_";
         if (beta_defined)
         {
             code += R"_(
     data *= beta;
 )_";
         }
         if (_attributes.is_log_softmax())
         {
             code += R"_(
     VSTORE_PARTIAL(N0, PARTIAL_N0)
     (data, 0, (__global {{DATA_TYPE}} *)dst_addr);
     data = exp(data);
     data = select(0, data, widx);
 )_";
         }
         else
         {
             code += R"_(
     data = exp(data);
     data = select(0, data, widx);
     VSTORE_PARTIAL(N0, PARTIAL_N0)
     (data, 0, (__global {{DATA_TYPE}} *)dst_addr);
 )_";
         }
         code += R"_(
     sum1D += data;
 )_";
     }
     code += R"_(
     for(uint i = PARTIAL_N0; i < {{SRC_WIDTH}}; i += N0)
     {
         VEC_TYPE data = VLOAD(N0)(0, (__global {{DATA_TYPE}} *)(src_addr + i * sizeof({{DATA_TYPE}})));
         data -= max_val;
 )_";
     if (beta_defined)
     {
         code += R"_(
     data *= beta;
 )_";
     }
     if (_attributes.is_log_softmax())
     {
         code += R"_(
     VSTORE(N0)
     (data, 0, (__global {{DATA_TYPE}} *)(dst_addr + i * sizeof({{DATA_TYPE}})));
     data = exp(data);
 )_";
     }
     else
     {
         code += R"_(
     data = exp(data);
     VSTORE(N0)
     (data, 0, (__global {{DATA_TYPE}} *)(dst_addr + i * sizeof({{DATA_TYPE}})));
 )_";
     }
     code += R"_(
     sum1D += data;
     }
 )_";
     code += R"_(
     *((__global {{DATA_TYPE}} *)sum.ptr) = SUM_REDUCE(sum1D, N0);
 }
 //------------------ END KERNEL {{meta_kernel_id}} ---------------------
 )_";
     return code;
 }
References arm_compute::adjust_vec_size(), ARM_COMPUTE_UNUSED, SoftmaxAttributes::beta(), ITensorInfo::dimension(), SoftmaxAttributes::is_log_softmax(), and arm_compute::cpu::vector_size.
get_config_id()
std::string get_config_id () const override virtual
Generate the component config id string used for tuning.
Reimplemented from IGpuTemplateComponentWriter.
Definition at line 240 of file ClTemplateLogits1DMaxShiftExpSum.cpp.
 {
     std::string config_id = get_name();
     config_id += "_";
     config_id += support::cpp11::to_string(_src->dimension(0));
     config_id += "_";
     config_id += string_from_data_type(_src->data_type());
     return config_id;
 }
References ITensorInfo::data_type(), ITensorInfo::dimension(), ClTemplateLogits1DMaxShiftExpSum::get_name(), arm_compute::string_from_data_type(), and arm_compute::support::cpp11::to_string().
get_headers_list()
std::set< std::string > get_headers_list () const override virtual
Generate the header list used in the component.
Reimplemented from IGpuTemplateComponentWriter.
Definition at line 252 of file ClTemplateLogits1DMaxShiftExpSum.cpp.
 {
     return std::set<std::string>{"helpers.h", "tile_helpers.h"};
 }
get_name()
std::string get_name () const override virtual
Generate kernel component name.
Implements IGpuTemplateComponentWriter.
Definition at line 57 of file ClTemplateLogits1DMaxShiftExpSum.cpp.
 {
     return "logits_1d_max_shift_exp_sum";
 }
Referenced by ClTemplateLogits1DMaxShiftExpSum::get_config_id().
get_tag_lut()
TagLUT get_tag_lut (const GpuKernelVariableTable & vtable, const ComponentGroup & comp_group) const override virtual
Generate the tag look-up table used to instantiate the component code.
Parameters
[in] vtable Variable table
[in] comp_group Component group of which the component is a part of
Returns
TagLUT Tag lookup table
Implements IGpuTemplateComponentWriter.
Definition at line 201 of file ClTemplateLogits1DMaxShiftExpSum.cpp.
 {
     ARM_COMPUTE_UNUSED(comp_group);
     TagLUT lut{};
     // Arguments and global shared variables
     lut["src"] = vtable.get_variable(_src);
     lut["sum"] = vtable.get_variable(_sum);
     lut["dst"] = vtable.get_variable(_dst);
     // Local build options
     lut["meta_kernel_id"] = id();
     const DataType data_type = _src->data_type();
     lut["DATA_TYPE"] = get_cl_type_from_data_type(data_type);
     lut["BETA"]      = float_to_string_with_full_precision(_attributes.beta());
     lut["MINVAL"]    = (data_type == DataType::F16) ? std::string("-HALF_MAX") : std::string("-FLT_MAX");
     lut["SRC_WIDTH"] = support::cpp11::to_string(_src->dimension(0));
     return lut;
 }
References ARM_COMPUTE_UNUSED, SoftmaxAttributes::beta(), arm_compute::test::validation::data_type, ITensorInfo::data_type(), ITensorInfo::dimension(), arm_compute::F16, arm_compute::float_to_string_with_full_precision(), arm_compute::get_cl_type_from_data_type(), GpuKernelVariableTable::get_variable(), IGpuTemplateComponentWriter::id(), and arm_compute::support::cpp11::to_string().
get_window()
Window get_window () const override virtual
Generate the execution window for the component.
Reimplemented from IGpuTemplateComponentWriter.
Definition at line 257 of file ClTemplateLogits1DMaxShiftExpSum.cpp.
 {
     ARM_COMPUTE_ERROR_ON_MSG(_dst->tensor_shape().total_size() == 0U, "Destination tensor is not initialized");
     Window win = calculate_max_window(*_dst, Steps(_src->dimension(0)));
     return win.collapse(win, Window::DimZ);
 }
References ARM_COMPUTE_ERROR_ON_MSG, arm_compute::calculate_max_window(), Window::collapse(), ITensorInfo::dimension(), Window::DimZ, ITensorInfo::tensor_shape(), TensorShape::total_size(), and arm_compute::utils::cast::U.
operator=() [1/2]
ClTemplateLogits1DMaxShiftExpSum& operator= (ClTemplateLogits1DMaxShiftExpSum &&) default
Allow instances of this class to be moved.
operator=() [2/2]
ClTemplateLogits1DMaxShiftExpSum& operator= (const ClTemplateLogits1DMaxShiftExpSum &) delete
Prevent instances of this class from being copied.
The documentation for this class was generated from the following files:
src/dynamic_fusion/sketch/gpu/template_writer/cl/ClTemplateLogits1DMaxShiftExpSum.h
src/dynamic_fusion/sketch/gpu/template_writer/cl/ClTemplateLogits1DMaxShiftExpSum.cpp