Compute Library: ClComponentDirectConv2dSettings Class Reference
ClComponentDirectConv2dSettings Class Reference
Component specific settings.
#include <ClComponentDirectConv2d.h>
Public Member Functions
bool export_to_cl_image () const
Get export_to_cl_image flag.
ClComponentDirectConv2dSettings & fast_relaxed_math (bool fast_relaxed_math)
Set fast_relaxed_math flag.
bool fast_relaxed_math () const
Get fast_relaxed_math flag.
ClComponentDirectConv2dSettings & direct_conv_descriptor (const DirectConvComputeKernelInfo &desc)
Set direct convolution descriptor.
DirectConvComputeKernelInfo direct_conv_descriptor () const
Get direct convolution descriptor.
Detailed Description
Component specific settings.
Definition at line 49 of file ClComponentDirectConv2d.h.
Member Function Documentation
direct_conv_descriptor() [1/2]
DirectConvComputeKernelInfo direct_conv_descriptor () const
Get direct convolution descriptor.
Definition at line 67 of file ClComponentDirectConv2d.cpp.
 {
     return _desc;
 }
direct_conv_descriptor() [2/2]
ClComponentDirectConv2dSettings & direct_conv_descriptor (const DirectConvComputeKernelInfo & desc)
Set direct convolution descriptor.
Definition at line 61 of file ClComponentDirectConv2d.cpp.
 {
     _desc = desc;
     return *this;
 }
Referenced by ClTemplateDirectConv2d::get_build_options(), ClTemplateDirectConv2d::get_component_code(), ClTemplateDirectConv2d::get_window(), ClComponentDirectConv2d::validate(), and GpuCkwDirectConv2d::write_component_code().
export_to_cl_image()
bool export_to_cl_image () const
Get export_to_cl_image flag.
Definition at line 44 of file ClComponentDirectConv2d.cpp.
 {
     return _desc.export_weights_to_cl_image;
 }
References DirectConvComputeKernelInfo::export_weights_to_cl_image.
Referenced by ClTemplateDirectConv2d::declare_variables().
fast_relaxed_math() [1/2]
bool fast_relaxed_math () const
Get fast_relaxed_math flag.
Definition at line 55 of file ClComponentDirectConv2d.cpp.
 {
     return _fast_relaxed_math;
 }
Referenced by ClComponentDirectConv2dSettings::fast_relaxed_math().
fast_relaxed_math() [2/2]
ClComponentDirectConv2dSettings & fast_relaxed_math (bool fast_relaxed_math)
Set fast_relaxed_math flag.
Definition at line 49 of file ClComponentDirectConv2d.cpp.
 {
     _fast_relaxed_math = fast_relaxed_math;
     return *this;
 }
References ClComponentDirectConv2dSettings::fast_relaxed_math().
Referenced by ClTemplateDirectConv2d::get_build_options().
The documentation for this class was generated from the following files:
src/dynamic_fusion/sketch/gpu/components/cl/ClComponentDirectConv2d.h
src/dynamic_fusion/sketch/gpu/components/cl/ClComponentDirectConv2d.cpp