Compute Library: ClMatMulNativeDefaultConfigValhall Class Reference
ClMatMulNativeDefaultConfigValhall Class Reference final
Valhall based OpenCL matmul configuration.
#include <ClMatMulNativeDefaultConfigValhall.h>
Public Member Functions
ClMatMulNativeDefaultConfigValhall (GPUTarget gpu)
Constructor.
MatMulKernelInfo configure (const ITensorInfo *lhs, const ITensorInfo *rhs, const MatMulInfo &info) override
This method returns the MatMulKernelInfo for the given inputs.
Public Member Functions inherited from IClMatMulNativeKernelConfig
IClMatMulNativeKernelConfig (GPUTarget arch)
Constructor.
ARM_COMPUTE_DISALLOW_COPY_ALLOW_MOVE (IClMatMulNativeKernelConfig)
virtual ~IClMatMulNativeKernelConfig ()=default
Virtual destructor.
Detailed Description
Valhall based OpenCL matmul configuration.
Definition at line 34 of file ClMatMulNativeDefaultConfigValhall.h.
Constructor & Destructor Documentation
ClMatMulNativeDefaultConfigValhall()
ClMatMulNativeDefaultConfigValhall (GPUTarget gpu)
Constructor.
Parameters
[in] gpu GPU target
Definition at line 41 of file ClMatMulNativeDefaultConfigValhall.cpp.
                                                                                     : IClMatMulNativeKernelConfig(gpu)
 {
 }
Member Function Documentation
configure()
MatMulKernelInfo configure (const ITensorInfo * lhs, const ITensorInfo * rhs, const MatMulInfo & info) override virtual
This method returns the MatMulKernelInfo for the given inputs.
Parameters
[in] lhs LHS tensor
[in] rhs RHS tensor
[in] info MatMul info
Implements IClMatMulNativeKernelConfig.
Definition at line 46 of file ClMatMulNativeDefaultConfigValhall.cpp.
 {
     using ConfigurationFunctionExecutorPtr = MatMulKernelInfo (ClMatMulNativeDefaultConfigValhall::*)(
         unsigned int m, unsigned int n, unsigned int k, unsigned int b, bool rhs_lock_padding, const MatMulInfo &info);
     ClMatMulNativeConfigArray<ConfigurationFunctionExecutorPtr> configs_G710(
         &ClMatMulNativeDefaultConfigValhall::configure_G710_f32,
         &ClMatMulNativeDefaultConfigValhall::configure_G710_f16,
         &ClMatMulNativeDefaultConfigValhall::configure_G710_u8);
     ClMatMulNativeConfigArray<ConfigurationFunctionExecutorPtr> configs_G715(
         &ClMatMulNativeDefaultConfigValhall::configure_G715_f32,
         &ClMatMulNativeDefaultConfigValhall::configure_G715_f16,
         &ClMatMulNativeDefaultConfigValhall::configure_G715_u8);
     ConfigurationFunctionExecutorPtr func = nullptr;
     switch (_target)
     {
         case GPUTarget::G715:
             func = configs_G715.get_function(lhs->data_type());
             break;
         case GPUTarget::G710:
         default:
             func = configs_G710.get_function(lhs->data_type());
             break;
     }
     const bool adj_lhs = info.adj_lhs();
     const bool adj_rhs = info.adj_rhs();
     TensorShape lhs_shape = lhs->tensor_shape();
     TensorShape rhs_shape = rhs->tensor_shape();
     const bool is_batched = lhs_shape.num_dimensions() > 2;
     if (is_batched == true)
     {
         lhs_shape.collapse_from(2);
     }
     const unsigned int m = adj_lhs ? lhs_shape.x() : lhs_shape.y();
     const unsigned int n = adj_rhs ? rhs_shape.y() : rhs_shape.x();
     const unsigned int k = adj_lhs ? lhs_shape.y() : lhs_shape.x();
     const unsigned int b = lhs_shape.z();
     ARM_COMPUTE_ERROR_ON_MSG(func == nullptr, "Data type not supported for matmul native");
     return (this->*func)(m, n, k, b, rhs->lock_paddings(), info);
 }
References ARM_COMPUTE_ERROR_ON_MSG, arm_compute::test::validation::b, Dimensions< T >::collapse_from(), ITensorInfo::data_type(), arm_compute::G710, arm_compute::G715, ClMatMulNativeConfigArray< T >::get_function(), arm_compute::test::validation::info, ITensorInfo::lock_paddings(), Dimensions< T >::num_dimensions(), ITensorInfo::tensor_shape(), Dimensions< T >::x(), Dimensions< T >::y(), and Dimensions< T >::z().
The documentation for this class was generated from the following files:
src/runtime/heuristics/matmul_native/ClMatMulNativeDefaultConfigValhall.h
src/runtime/heuristics/matmul_native/ClMatMulNativeDefaultConfigValhall.cpp