Compute Library: CLDeconvolutionLayer Class Reference
CLDeconvolutionLayer Class Reference
Basic function to compute the deconvolution layer.
#include <CLDeconvolutionLayer.h>
Public Member Functions
CLDeconvolutionLayer (std::shared_ptr< IMemoryManager > memory_manager=nullptr)
Default constructor.
~CLDeconvolutionLayer ()
void configure (ICLTensor *input, ICLTensor *weights, const ICLTensor *bias, ICLTensor *output, const PadStrideInfo &deconv_info, const WeightsInfo &weights_info=WeightsInfo())
Set the input, weights, biases and output tensors.
void configure (const CLCompileContext &compile_context, ICLTensor *input, ICLTensor *weights, const ICLTensor *bias, ICLTensor *output, const PadStrideInfo &deconv_info, const WeightsInfo &weights_info=WeightsInfo())
Set the input, weights, biases and output tensors.
void run () override
Run the kernels contained in the function.
void prepare () override
Prepare the function for executing.
Public Member Functions inherited from IFunction
virtual ~IFunction ()=default
Destructor.
Static Public Member Functions
static Status validate (const ITensorInfo *input, const ITensorInfo *weights, const ITensorInfo *bias, ITensorInfo *output, const PadStrideInfo &deconv_info, const WeightsInfo &weights_info=WeightsInfo())
Static function to check if given info will lead to a valid configuration of CLDeconvolutionLayer.
static DeconvolutionMethod get_deconvolution_method (const ITensorInfo *input, const ITensorInfo *weights, const ITensorInfo *bias, ITensorInfo *output, const PadStrideInfo &deconv_info, const WeightsInfo &weights_info)
Detailed Description
Basic function to compute the deconvolution layer.
This function calls the following OpenCL kernels/functions:
CLGEMMDeconvolutionLayer
CLDirectDeconvolutionLayer
Definition at line 41 of file CLDeconvolutionLayer.h.
Constructor & Destructor Documentation
CLDeconvolutionLayer()
CLDeconvolutionLayer (std::shared_ptr< IMemoryManager > memory_manager = nullptr)
Default constructor.
Definition at line 56 of file CLDeconvolutionLayer.cpp.
     : _memory_manager(std::move(memory_manager)), _function(), _impl(std::make_unique<Impl>())
 {
 }
~CLDeconvolutionLayer()
~CLDeconvolutionLayer () default
Member Function Documentation
configure() [1/2]
void configure (const CLCompileContext & compile_context, ICLTensor * input, ICLTensor * weights, const ICLTensor * bias, ICLTensor * output, const PadStrideInfo & deconv_info, const WeightsInfo & weights_info = WeightsInfo())
Set the input, weights, biases and output tensors.
Parameters
[in] compile_context The compile context to be used.
[in,out] input Input tensor. 3 lower dimensions represent a single input, and an optional 4th dimension for batch of inputs. Data types supported: QASYMM8_SIGNED/QASYMM8/F16/F32.
[in] weights The 4d weights with dimensions [width, height, IFM, OFM]. Data type supported: Same as input or QSYMM8_PER_CHANNEL if input is QASYMM8/QASYMM8_SIGNED.
[in] bias (Optional) The biases have one dimension. Data type supported: Should match input data type, except for input of QASYMM8 and QASYMM8_SIGNED type where biases should be of S32 type
[out] output Output tensor. The output has the same number of dimensions as the input.
[in] deconv_info Contains padding and policies to be used in the deconvolution, this is described in PadStrideInfo.
[in] weights_info (Optional) Weights information needed for CLConvolutionLayer, specifies if the weights tensor has been reshaped with opencl::kernels::ClWeightsReshapeKernel.
Definition at line 71 of file CLDeconvolutionLayer.cpp.
 {
     ARM_COMPUTE_ERROR_ON_NULLPTR(input, weights, output);
     ARM_COMPUTE_LOG_PARAMS(input, weights, bias, output, deconv_info, weights_info);
     switch (CLDeconvolutionLayer::get_deconvolution_method(input->info(), weights->info(), nullptr, output->info(),
                                                            deconv_info, weights_info))
     {
         case DeconvolutionMethod::DIRECT:
         {
             auto op = std::make_unique<opencl::ClTransposedConvolution>();
             op->configure(compile_context, input->info(), weights->info(), bias != nullptr ? bias->info() : nullptr,
                           output->info(), deconv_info);
             _impl->src     = input;
             _impl->weights = weights;
             _impl->biases  = bias;
             _impl->dst     = output;
             _impl->op = std::move(op);
             break;
         }
         case DeconvolutionMethod::UPSCALE_CONV2D:
         {
             auto f = std::make_unique<CLDirectDeconvolutionLayer>();
             f->configure(compile_context, input, weights, bias, output, deconv_info, weights_info);
             _function = std::move(f);
             break;
         }
         case DeconvolutionMethod::GEMM:
         {
             auto f = std::make_unique<CLGEMMDeconvolutionLayer>(_memory_manager);
             f->configure(compile_context, input, weights, bias, output, deconv_info);
             _function = std::move(f);
             break;
         }
         default:
             ARM_COMPUTE_ERROR("Not supported.");
             break;
     }
 }
References ARM_COMPUTE_ERROR, ARM_COMPUTE_ERROR_ON_NULLPTR, ARM_COMPUTE_LOG_PARAMS, bias, arm_compute::DIRECT, arm_compute::GEMM, CLDeconvolutionLayer::get_deconvolution_method(), ITensor::info(), arm_compute::test::validation::input, arm_compute::UPSCALE_CONV2D, and arm_compute::test::validation::weights_info.
configure() [2/2]
void configure (ICLTensor * input, ICLTensor * weights, const ICLTensor * bias, ICLTensor * output, const PadStrideInfo & deconv_info, const WeightsInfo & weights_info = WeightsInfo())
Set the input, weights, biases and output tensors.
Valid data layouts:
NHWC
NCHW
Valid data type configurations:
src0 src1 src2 dst
F16 F16 F16 F16
F32 F32 F32 F32
QASYMM8 QASYMM8 S32 QASYMM8
QASYMM8 QSYMM8_PER_CHANNEL S32 QASYMM8
QASYMM8_SIGNED QASYMM8_SIGNED S32 QASYMM8_SIGNED
QASYMM8_SIGNED QSYMM8_PER_CHANNEL S32 QASYMM8_SIGNED
Parameters
[in,out] input Input tensor. 3 lower dimensions represent a single input, and an optional 4th dimension for batch of inputs. Data types supported: QASYMM8_SIGNED/QASYMM8/F16/F32.
[in] weights The 4d weights with dimensions [width, height, IFM, OFM]. Data type supported: Same as input or QSYMM8_PER_CHANNEL if input is QASYMM8/QASYMM8_SIGNED.
[in] bias (Optional) The biases have one dimension. Data type supported: Should match input data type, except for input of QASYMM8 and QASYMM8_SIGNED type where biases should be of S32 type
[out] output Output tensor. The output has the same number of dimensions as the input.
[in] deconv_info Contains padding and policies to be used in the deconvolution, this is described in PadStrideInfo.
[in] weights_info (Optional) Weights information needed for CLConvolutionLayer, specifies if the weights tensor has been reshaped with opencl::kernels::ClWeightsReshapeKernel.
Definition at line 61 of file CLDeconvolutionLayer.cpp.
 {
     configure(CLKernelLibrary::get().get_compile_context(), input, weights, bias, output, deconv_info, weights_info);
 }
References bias, CLKernelLibrary::get(), arm_compute::test::validation::input, and arm_compute::test::validation::weights_info.
get_deconvolution_method()
DeconvolutionMethod get_deconvolution_method (const ITensorInfo * input, const ITensorInfo * weights, const ITensorInfo * bias, ITensorInfo * output, const PadStrideInfo & deconv_info, const WeightsInfo & weights_info) static
Definition at line 157 of file CLDeconvolutionLayer.cpp.
 {
     ARM_COMPUTE_UNUSED(output, bias, weights_info);
     if (is_data_type_quantized_per_channel(weights->data_type()))
     {
         return DeconvolutionMethod::UPSCALE_CONV2D;
     }
     const DataLayout data_layout = input->data_layout();
     const size_t idx_w = get_data_layout_dimension_index(data_layout, DataLayoutDimension::WIDTH);
     const size_t idx_h = get_data_layout_dimension_index(data_layout, DataLayoutDimension::HEIGHT);
     const size_t idx_n = get_data_layout_dimension_index(data_layout, DataLayoutDimension::BATCHES);
     const size_t ofm   = weights->tensor_shape()[idx_n];
     if (weights->dimension(idx_w) != deconv_info.stride().first ||
         weights->dimension(idx_h) != deconv_info.stride().second)
     {
         // We observe better performance for FP32 types only when ofm <= 16, and for FP16 only when ofm <= 32.
         if (input->data_layout() == DataLayout::NHWC && !((input->data_type() == DataType::F32) && (ofm > 16)) &&
             !((input->data_type() == DataType::F16) && (ofm > 32)))
         {
             return DeconvolutionMethod::DIRECT;
         }
         else
         {
             return DeconvolutionMethod::UPSCALE_CONV2D;
         }
     }
     return DeconvolutionMethod::GEMM;
 }
References ARM_COMPUTE_UNUSED, arm_compute::BATCHES, bias, arm_compute::cpu::data_layout, ITensorInfo::data_type(), ITensorInfo::dimension(), arm_compute::DIRECT, arm_compute::F16, arm_compute::F32, arm_compute::GEMM, arm_compute::get_data_layout_dimension_index(), arm_compute::HEIGHT, arm_compute::test::validation::input, arm_compute::is_data_type_quantized_per_channel(), arm_compute::NHWC, PadStrideInfo::stride(), ITensorInfo::tensor_shape(), arm_compute::UPSCALE_CONV2D, arm_compute::test::validation::weights_info, and arm_compute::WIDTH.
Referenced by CLDeconvolutionLayer::configure(), and CLDeconvolutionLayer::validate().
prepare()
void prepare () override virtual
Prepare the function for executing.
Any one off pre-processing step required by the function is handled here
Note
Prepare stage might not need all the function's buffers' backing memory to be available in order to execute
Reimplemented from IFunction.
Definition at line 218 of file CLDeconvolutionLayer.cpp.
 {
     if (_impl->op == nullptr)
     {
         _function->prepare();
     }
 }
Referenced by CLDeconvolutionLayer::run().
run()
void run () override virtual
Run the kernels contained in the function.
For CPU kernels:
Multi-threading is used for the kernels which are parallelisable.
By default std::thread::hardware_concurrency() threads are used.
Note
CPPScheduler::set_num_threads() can be used to manually set the number of threads
For OpenCL kernels:
All the kernels are enqueued on the queue associated with CLScheduler.
The queue is then flushed.
Note
The function will not block until the kernels are executed. It is the user's responsibility to wait.
Will call prepare() on first run if hasn't been done
Implements IFunction.
Definition at line 196 of file CLDeconvolutionLayer.cpp.
 {
     prepare();
     if (_impl->op != nullptr)
     {
         // Optimized Operator will be used
         ITensorPack pack;
         pack.add_tensor(TensorType::ACL_SRC_0, _impl->src);
         pack.add_tensor(TensorType::ACL_SRC_1, _impl->weights);
         pack.add_tensor(TensorType::ACL_SRC_2, _impl->biases);
         pack.add_tensor(TensorType::ACL_DST, _impl->dst);
         _impl->op->run(pack);
     }
     else
     {
         _function->run();
     }
 }
References arm_compute::ACL_DST, arm_compute::ACL_SRC_0, arm_compute::ACL_SRC_1, arm_compute::ACL_SRC_2, ITensorPack::add_tensor(), arm_compute::test::validation::pack, and CLDeconvolutionLayer::prepare().
validate()
Status validate (const ITensorInfo * input, const ITensorInfo * weights, const ITensorInfo * bias, ITensorInfo * output, const PadStrideInfo & deconv_info, const WeightsInfo & weights_info = WeightsInfo()) static
Static function to check if given info will lead to a valid configuration of CLDeconvolutionLayer.
Parameters
[in] input Input tensor info. 3 lower dimensions represent a single input, and an optional 4th dimension for batch of inputs. Data types supported: QASYMM8_SIGNED/QASYMM8/F16/F32.
[in] weights The 4d weights info with dimensions [width, height, IFM, OFM]. Data type supported: Same as input or QSYMM8_PER_CHANNEL if input is QASYMM8/QASYMM8_SIGNED.
[in] bias (Optional) The biases have one dimension. Data type supported: Should match input data type, except for input of QASYMM8 and QASYMM8_SIGNED type where biases should be of S32 type
[in] output Output tensor info. The output has the same number of dimensions as the input.
[in] deconv_info Contains padding and policies to be used in the deconvolution, this is described in PadStrideInfo.
[in] weights_info (Optional) Weights information needed for CLConvolutionLayer, specifies if the weights tensor has been reshaped with opencl::kernels::ClWeightsReshapeKernel.
Returns
a status
Definition at line 119 of file CLDeconvolutionLayer.cpp.
 {
     ARM_COMPUTE_RETURN_ERROR_ON_NULLPTR(input, weights, output);
     switch (CLDeconvolutionLayer::get_deconvolution_method(input, weights, bias, output, deconv_info, weights_info))
     {
         case DeconvolutionMethod::DIRECT:
         {
             // Validate transposed convolution operator
             ARM_COMPUTE_RETURN_ON_ERROR(
                 opencl::ClTransposedConvolution::validate(input, weights, bias, output, deconv_info));
             break;
         }
         case DeconvolutionMethod::UPSCALE_CONV2D:
         {
             // Validate direct convolution layer
             ARM_COMPUTE_RETURN_ON_ERROR(
                 CLDirectDeconvolutionLayer::validate(input, weights, bias, output, deconv_info, weights_info));
             break;
         }
         case DeconvolutionMethod::GEMM:
         {
             // Validate gemm-based convolution layer
             ARM_COMPUTE_RETURN_ON_ERROR(CLGEMMDeconvolutionLayer::validate(input, weights, bias, output, deconv_info));
             break;
         }
         default:
             ARM_COMPUTE_ERROR("Not supported.");
             break;
     }
     return Status{};
 }
References ARM_COMPUTE_ERROR, ARM_COMPUTE_RETURN_ERROR_ON_NULLPTR, ARM_COMPUTE_RETURN_ON_ERROR, bias, arm_compute::DIRECT, arm_compute::GEMM, CLDeconvolutionLayer::get_deconvolution_method(), arm_compute::test::validation::input, arm_compute::UPSCALE_CONV2D, ClTransposedConvolution::validate(), CLGEMMDeconvolutionLayer::validate(), CLDirectDeconvolutionLayer::validate(), and arm_compute::test::validation::weights_info.
The documentation for this class was generated from the following files:
arm_compute/runtime/CL/functions/CLDeconvolutionLayer.h
src/runtime/CL/functions/CLDeconvolutionLayer.cpp