Compute Library: CLMaxUnpoolingLayer Class Reference
CLMaxUnpoolingLayer Class Reference
Function to perform MaxUnpooling.
#include <CLMaxUnpoolingLayer.h>
Public Member Functions
CLMaxUnpoolingLayer ()
Constructor.
CLMaxUnpoolingLayer (const CLMaxUnpoolingLayer &)=delete
Prevent instances of this class from being copied.
CLMaxUnpoolingLayer & operator= (const CLMaxUnpoolingLayer &)=delete
Prevent instances of this class from being copied.
~CLMaxUnpoolingLayer ()
Default destructor.
void configure (ICLTensor *input, ICLTensor *indices, ICLTensor *output, const PoolingLayerInfo &pool_info)
Set the input and output tensors.
void configure (const CLCompileContext &compile_context, ICLTensor *input, ICLTensor *indices, ICLTensor *output, const PoolingLayerInfo &pool_info)
Set the input and output tensors.
void run () override
Run the kernels contained in the function.
Public Member Functions inherited from IFunction
virtual ~IFunction ()=default
Destructor.
virtual void prepare ()
Prepare the function for executing.
Static Public Member Functions
static Status validate (const ITensorInfo *input, const ITensorInfo *indices, const ITensorInfo *output, const PoolingLayerInfo &pool_info)
Static function to check if given info will lead to a valid configuration of CLMaxUnpoolingLayer.
Detailed Description
Function to perform MaxUnpooling.
This function calls the following OpenCL kernels:
CLFill
CLMaxUnpoolingLayerKernel
Definition at line 46 of file CLMaxUnpoolingLayer.h.
Constructor & Destructor Documentation
CLMaxUnpoolingLayer() [1/2]
CLMaxUnpoolingLayer ()
Constructor.
Definition at line 36 of file CLMaxUnpoolingLayer.cpp.
     : _fill(), _unpooling_layer_kernel(std::make_unique<CLMaxUnpoolingLayerKernel>())
 {
 }
CLMaxUnpoolingLayer() [2/2]
CLMaxUnpoolingLayer (const CLMaxUnpoolingLayer &) delete
Prevent instances of this class from being copied.
~CLMaxUnpoolingLayer()
~CLMaxUnpoolingLayer () default
Default destructor.
Member Function Documentation
configure() [1/2]
void configure (const CLCompileContext & compile_context, ICLTensor * input, ICLTensor * indices, ICLTensor * output, const PoolingLayerInfo & pool_info)
Set the input and output tensors.
Note
Output shape must be equal to the shape of the original input to pool.
Parameters
[in] compile_context The compile context to be used.
[in] input Source tensor. Data types supported: QASYMM8/QASYMM8_SIGNED/F16/F32.
[in] indices Tensor containing the offset to store the input elements in the output tensor. CLPoolingLayer with indices should precede this function in order to properly reconstruct the output tensor. The tensor shape of this tensor has to be equal to the input tensor shape. Data type supported: U32.
[out] output Destination tensor. Data types supported: Same as input.
[in] pool_info Contains pooling operation information described in PoolingLayerInfo.
Definition at line 51 of file CLMaxUnpoolingLayer.cpp.
 {
     ARM_COMPUTE_LOG_PARAMS(input, indices, output, pool_info);
     const PixelValue zero_value(0.f);
     _fill.configure(output, zero_value);
     _unpooling_layer_kernel->configure(compile_context, input, indices, output, pool_info);
 }
References ARM_COMPUTE_LOG_PARAMS, CLFill::configure(), and arm_compute::test::validation::input.
configure() [2/2]
void configure (ICLTensor * input, ICLTensor * indices, ICLTensor * output, const PoolingLayerInfo & pool_info)
Set the input and output tensors.
Valid data layouts:
NHWC
NCHW
Valid data type configurations:
src dst
QASYMM8 QASYMM8
QASYMM8_SIGNED QASYMM8_SIGNED
F16 F16
F32 F32
Note
Output shape must be equal to the shape of the original input to pool.
Parameters
[in] input Source tensor. Data types supported: QASYMM8/QASYMM8_SIGNED/F16/F32.
[in] indices Tensor containing the offset to store the input elements in the output tensor. CLPoolingLayer with indices should precede this function in order to properly reconstruct the output tensor. The tensor shape of this tensor has to be equal to the input tensor shape. Data type supported: U32.
[out] output Destination tensor. Data types supported: Same as input.
[in] pool_info Contains pooling operation information described in PoolingLayerInfo.
Definition at line 43 of file CLMaxUnpoolingLayer.cpp.
 {
     configure(CLKernelLibrary::get().get_compile_context(), input, indices, output, pool_info);
 }
References CLKernelLibrary::get(), and arm_compute::test::validation::input.
operator=()
CLMaxUnpoolingLayer& operator= (const CLMaxUnpoolingLayer &) delete
Prevent instances of this class from being copied.
run()
void run () override virtual
Run the kernels contained in the function.
For CPU kernels:
Multi-threading is used for the kernels which are parallelisable.
By default std::thread::hardware_concurrency() threads are used.
Note
CPPScheduler::set_num_threads() can be used to manually set the number of threads
For OpenCL kernels:
All the kernels are enqueued on the queue associated with CLScheduler.
The queue is then flushed.
Note
The function will not block until the kernels are executed. It is the user's responsibility to wait.
Will call prepare() on first run if hasn't been done
Implements IFunction.
Definition at line 72 of file CLMaxUnpoolingLayer.cpp.
 {
     // Run fill
     _fill.run();
     // Run max unpooling layer
     CLScheduler::get().enqueue(*_unpooling_layer_kernel);
 }
References CLScheduler::enqueue(), CLScheduler::get(), and CLFill::run().
validate()
Status validate (const ITensorInfo * input, const ITensorInfo * indices, const ITensorInfo * output, const PoolingLayerInfo & pool_info) static
Static function to check if given info will lead to a valid configuration of CLMaxUnpoolingLayer.
Parameters
[in] input Source tensor info. Data types supported: QASYMM8/QASYMM8_SIGNED/F16/F32.
[in] output Destination tensor info. Data types supported: Same as input.
[in] indices TensorInfo associated to the tensor containing the offset to store the input elements in the output tensor. CLPoolingLayer with indices should precede this function in order to properly reconstruct the output tensor. The tensor shape of this tensor has to be equal to the input tensor shape. Data type supported: U32.
[in] pool_info Contains pooling operation information described in PoolingLayerInfo.
Returns
a status
Definition at line 64 of file CLMaxUnpoolingLayer.cpp.
 {
     return CLMaxUnpoolingLayerKernel::validate(input, indices, output, pool_info);
 }
References arm_compute::test::validation::input, and CLMaxUnpoolingLayerKernel::validate().
The documentation for this class was generated from the following files:
arm_compute/runtime/CL/functions/CLMaxUnpoolingLayer.h
src/runtime/CL/functions/CLMaxUnpoolingLayer.cpp