Compute Library: Operator Class Reference
Operator Class Reference
An operator for the sole purpose of validating fusion.
#include <GpuOperatorGroup.h>
Public Member Functions
Operator ()=default
Default constructor.
OperatorId id () const
Get Operator Id.
GpuOperatorType operator_type () const
Get operator type.
ArgumentPack< ITensorInfo > tensors () const
Get tensor arguments.
Friends
class GpuOperatorGroup
Detailed Description
An operator for the sole purpose of validating fusion.
Definition at line 45 of file GpuOperatorGroup.h.
Constructor & Destructor Documentation
Operator()
Operator () default
Default constructor.
Member Function Documentation
id()
OperatorId id () const
Get Operator Id.
Definition at line 51 of file GpuOperatorGroup.cpp.
 {
     return _id;
 }
Referenced by GpuOperatorGroup::add_operator(), and GpuOperatorGroup::try_add_operator().
operator_type()
GpuOperatorType operator_type () const
Get operator type.
Definition at line 56 of file GpuOperatorGroup.cpp.
 {
     return _operator_type;
 }
Referenced by GpuOperatorGroup::try_add_operator().
tensors()
ArgumentPack< ITensorInfo > tensors () const
Get tensor arguments.
Definition at line 61 of file GpuOperatorGroup.cpp.
 {
     return _tensors;
 }
Referenced by GpuOperatorGroup::add_operator(), and GpuOperatorGroup::try_add_operator().
Friends And Related Function Documentation
GpuOperatorGroup
friend class GpuOperatorGroup friend
Definition at line 56 of file GpuOperatorGroup.h.
The documentation for this class was generated from the following files:
src/dynamic_fusion/sketch/gpu/GpuOperatorGroup.h
src/dynamic_fusion/sketch/gpu/GpuOperatorGroup.cpp