Compute Library: ITensorPack Class Reference
ITensorPack Class Reference
Tensor packing service.
#include <ITensorPack.h>
Data Structures
struct PackElement
Public Member Functions
ITensorPack ()=default
Default Constructor.
ITensorPack (std::initializer_list< PackElement > l)
Initializer list Constructor.
void add_tensor (int id, ITensor *tensor)
Add tensor to the pack.
void add_tensor (int id, const ITensor *tensor)
Add const tensor to the pack.
void add_const_tensor (int id, const ITensor *tensor)
Add const tensor to the pack.
ITensor * get_tensor (int id)
Get tensor of a given id from the pac.
const ITensor * get_const_tensor (int id) const
Get constant tensor of a given id.
void remove_tensor (int id)
Remove the tensor stored with the given id.
size_t size () const
Pack size accessor.
bool empty () const
Checks if pack is empty.
Detailed Description
Tensor packing service.
Definition at line 39 of file ITensorPack.h.
Constructor & Destructor Documentation
ITensorPack() [1/2]
ITensorPack () default
Default Constructor.
ITensorPack() [2/2]
ITensorPack (std::initializer_list< PackElement > l)
Initializer list Constructor.
Definition at line 30 of file ITensorPack.cpp.
                                                            : _pack()
 {
     for (auto &e : l)
     {
         _pack[e.id] = e;
     }
 }
Member Function Documentation
add_const_tensor()
void add_const_tensor (int id, const ITensor * tensor)
Add const tensor to the pack.
Parameters
[in] id ID/type of the tensor to add
[in] tensor Tensor to add
Definition at line 48 of file ITensorPack.cpp.
 {
     add_tensor(id, tensor);
 }
References ITensorPack::add_tensor(), and tensor.
Referenced by CpuGemmDirectConv2d::prepare(), CpuWinogradConv2d::prepare(), ClFullyConnected::prepare(), CpuFullyConnected::prepare(), ClGemmConv2d::prepare(), CpuGemmConv2d::prepare(), CpuMatMul::run(), CpuWinogradConv2d::run(), ClIndirectConv2d::run(), ClFullyConnected::run(), ClGemm::run(), ClWinogradConv2d::run(), CpuFullyConnected::run(), ClGemmConv2d::run(), CpuGemmLowpMatrixMultiplyCore::run(), CpuGemm::run(), and CpuGemmConv2d::run().
add_tensor() [1/2]
void add_tensor (int id, const ITensor * tensor)
Add const tensor to the pack.
Parameters
[in] id ID/type of the tensor to add
[in] tensor Tensor to add
Definition at line 43 of file ITensorPack.cpp.
 {
     _pack[id] = PackElement(id, tensor);
 }
References tensor.
add_tensor() [2/2]
void add_tensor (int id, ITensor * tensor)
Add tensor to the pack.
Parameters
[in] id ID/type of the tensor to add
[in] tensor Tensor to add
Definition at line 38 of file ITensorPack.cpp.
 {
     _pack[id] = PackElement(id, tensor);
 }
References tensor.
Referenced by ITensorPack::add_const_tensor(), TensorPack::add_tensor(), CLAuxTensorHandler::CLAuxTensorHandler(), CpuAuxTensorHandler::CpuAuxTensorHandler(), arm_compute::manage_workspace(), ClWinogradConv2d::prepare(), ClPRelu::run(), CpuConcatenate::run(), NEFill::run(), ClSoftmax::run(), ClConcatenate::run(), NECopy::run(), NEReshapeLayer::run(), NETranspose::run(), NEFloor::run(), NEElementwiseUnaryLayer< op >::run(), NEFlattenLayer::run(), NEQuantizationLayer::run(), NEDequantizationLayer::run(), CpuSoftmaxGeneric< IS_LOG >::run(), NEConvertFullyConnectedWeights::run(), NEPermute::run(), NEPReluLayer::run(), CLTranspose::run(), CLRsqrtLayer::run(), CLFloor::run(), CLReshapeLayer::run(), CLLogicalNot::run(), NEScale::run(), CLFlattenLayer::run(), CLLogicalAnd::run(), CLLogicalOr::run(), CLDequantizationLayer::run(), NESlice::run(), CLFill::run(), NEConcatenateLayer::run(), CLCopy::run(), NEElementwiseMax::run(), CpuDirectConv3d::run(), CLPReluLayer::run(), NEMaxUnpoolingLayer::run(), CLPermute::run(), CLQuantizationLayer::run(), NEActivationLayer::run(), CpuWinogradConv2d::run(), CpuDirectConv2d::run(), CLPooling3dLayer::run(), NEArithmeticAddition::run(), CLConvertFullyConnectedWeights::run(), CLScale::run(), NEArithmeticSubtraction::run(), CLPoolingLayer::run(), NEStridedSlice::run(), CLActivationLayer::run(), CLConv3D::run(), CLSlice::run(), CLConcatenateLayer::run(), ClWinogradConv2d::run(), NEDirectConvolutionLayer::run(), CLDeconvolutionLayer::run(), CLCrop::run(), ClGemmConv2d::run(), CLIndirectConvolutionLayer::run(), CpuGemmLowpMatrixMultiplyCore::run(), CLDirectConvolutionLayer::run(), CLStridedSlice::run(), CLPixelWiseMultiplication::run(), NEPixelWiseMultiplication::run(), CLExpLayer::run(), CpuGemmConv2d::run(), CLArithmeticAddition::run(), NEElementwiseMin::run(), NEComplexPixelWiseMultiplication::run(), CLNegLayer::run(), CLComplexPixelWiseMultiplication::run(), NEElementwiseSquaredDiff::run(), CLSinLayer::run(), CLLSTMLayer::run(), CLArithmeticSubtraction::run(), NEElementwiseDivision::run(), CLLogLayer::run(), NEElementwisePower::run(), CLArithmeticDivision::run(), CLAbsLayer::run(), NEElementwiseComparison::run(), CLRoundLayer::run(), CLElementwiseMax::run(), NEElementwiseComparisonStatic< op >::run(), CLElementwiseMin::run(), CLElementwiseSquaredDiff::run(), and CLElementwisePower::run().
empty()
bool empty () const
Checks if pack is empty.
Returns
True if empty else false
Definition at line 79 of file ITensorPack.cpp.
 {
     return _pack.empty();
 }
Referenced by TensorPack::empty(), CpuDequantize::run(), CpuQuantize::run(), CpuReshape::run(), ClDequantize::run(), CpuActivation::run(), ClQuantize::run(), ICLOperator::run(), INEOperator::run(), CpuScale::run(), ClScale::run(), CpuPool3d::run(), CpuConcatenate::run(), ClConcatenate::run(), CpuPool2d::run(), CpuDepthwiseConv2dAssemblyDispatch::run(), CpuSoftmaxGeneric< IS_LOG >::run(), CpuMul::run(), CpuComplexMul::run(), NELogicalKernel::run_op(), CpuFloorKernel::run_op(), CpuGemmInterleave4x4Kernel::run_op(), CpuActivationKernel::run_op(), CpuGemmMatrixAdditionKernel::run_op(), CpuGemmLowpQuantizeDownInt32ScaleKernel::run_op(), CpuPool2dAssemblyWrapperKernel::run_op(), CpuAddKernel::run_op(), CpuGemmLowpQuantizeDownInt32ToInt16ScaleByFixedPointKernel::run_op(), CpuGemmLowpQuantizeDownInt32ToUint8ScaleByFixedPointKernel::run_op(), CpuGemmLowpQuantizeDownInt32ToInt8ScaleByFixedPointKernel::run_op(), CpuDepthwiseConv2dAssemblyWrapperKernel::run_op(), CpuGemmTranspose1xWKernel::run_op(), CpuGemmMatrixMultiplyKernel::run_op(), CpuAddMulAddKernel::run_op(), and ClIm2ColKernel::run_op().
get_const_tensor()
const ITensor * get_const_tensor (int id) const
Get constant tensor of a given id.
Parameters
[in] id ID of tensor to extract
Returns
The pointer to the tensor if exist and is const else nullptr
Definition at line 53 of file ITensorPack.cpp.
 {
     auto it = _pack.find(id);
     if (it != _pack.end())
     {
         return it->second.ctensor != nullptr ? it->second.ctensor : it->second.tensor;
     }
     return nullptr;
 }
Referenced by CpuScale::prepare(), CpuReshapeKernel::prepare(), CpuDepthwiseConv2dAssemblyDispatch::prepare(), CpuGemmDirectConv2d::prepare(), CpuWinogradConv2d::prepare(), ClFullyConnected::prepare(), ClGemmLowpMatrixMultiplyCore::prepare(), ClGemm::prepare(), ClWinogradConv2d::prepare(), CpuFullyConnected::prepare(), ClGemmConv2d::prepare(), CpuGemmLowpMatrixMultiplyCore::prepare(), CpuGemmConv2d::prepare(), CpuElementwiseBase::run(), CpuElementwiseUnary::run(), ClPRelu::run(), CpuConcatenate::run(), CpuAddMulAdd::run(), ClConcatenate::run(), CpuSoftmaxGeneric< IS_LOG >::run(), CpuMatMul::run(), ClGemmLowpOutputStage::run(), CpuWinogradConv2d::run(), CpuDirectConv2d::run(), ClFullyConnected::run(), ClGemmLowpMatrixMultiplyCore::run(), ClGemm::run(), ClWinogradConv2d::run(), CpuFullyConnected::run(), ClGemmConv2d::run(), CpuGemmLowpMatrixMultiplyCore::run(), CpuGemm::run(), CpuGemmConv2d::run(), CpuElementwiseKernel< CpuArithmeticKernel >::run_op(), ClElementwiseKernel::run_op(), CpuConvertQuantizedSignednessKernel::run_op(), CpuDequantizeKernel::run_op(), CpuTransposeKernel::run_op(), CpuReshapeKernel::run_op(), CpuCopyKernel::run_op(), ClDequantizeKernel::run_op(), ClFloorKernel::run_op(), ClReshapeKernel::run_op(), ClTransposeKernel::run_op(), CpuPermuteKernel::run_op(), CpuConcatenateBatchKernel::run_op(), CpuLogits1DMaxKernel::run_op(), CpuConcatenateWidthKernel::run_op(), CpuConcatenateHeightKernel::run_op(), ClWidthConcatenate2TensorsKernel::run_op(), CpuQuantizeKernel::run_op(), CpuWinogradConv2dTransformInputKernel::run_op(), ClCopyKernel::run_op(), ClElementWiseUnaryKernel::run_op(), ClFillKernel::run_op(), ClWidthConcatenateKernel::run_op(), ClHeightConcatenateKernel::run_op(), ClQuantizeKernel::run_op(), ClScaleKernel::run_op(), NELogicalKernel::run_op(), ClPool3dKernel::run_op(), ClBatchConcatenateKernel::run_op(), ClDepthConcatenateKernel::run_op(), ClTransposedConvolutionKernel::run_op(), ClActivationKernel::run_op(), CpuConcatenateDepthKernel::run_op(), CpuFloorKernel::run_op(), ClPermuteKernel::run_op(), CpuGemmLowpMatrixAReductionKernel::run_op(), ClPool2dKernel::run_op(), ClSoftmaxKernel::run_op(), CpuPool2dKernel::run_op(), CpuGemmLowpMatrixMultiplyKernel::run_op(), CpuElementwiseUnaryKernel::run_op(), CpuConvertFullyConnectedWeightsKernel::run_op(), CpuPool3dKernel::run_op(), ClMatMulLowpNativeMMULKernel::run_op(), ClWidthConcatenate4TensorsKernel::run_op(), CpuDirectConv2dKernel::run_op(), CpuGemmInterleave4x4Kernel::run_op(), ClConvertFullyConnectedWeightsKernel::run_op(), ClWinogradInputTransformKernel::run_op(), ClWinogradFilterTransformKernel::run_op(), CpuActivationKernel::run_op(), CpuSubKernel::run_op(), CpuMaxUnpoolingLayerKernel::run_op(), CpuDirectConv2dOutputStageKernel::run_op(), ClGemmReshapeLhsMatrixKernel::run_op(), ClMatMulNativeKernel::run_op(), CpuGemmMatrixAdditionKernel::run_op(), ClCastKernel::run_op(), CpuCol2ImKernel::run_op(), ClCropKernel::run_op(), ClMatMulLowpNativeKernel::run_op(), CpuCastKernel::run_op(), ClGemmLowpMatrixMultiplyNativeKernel::run_op(), ClGemmLowpQuantizeDownInt32ScaleByFixedPointKernel::run_op(), CpuPool2dAssemblyWrapperKernel::run_op(), CpuGemmLowpQuantizeDownInt32ScaleKernel::run_op(), ClGemmLowpQuantizeDownInt32ScaleByFloatKernel::run_op(), ClGemmLowpQuantizeDownInt32ScaleKernel::run_op(), CpuAddKernel::run_op(), ClGemmReshapeRhsMatrixKernel::run_op(), ClWinogradOutputTransformKernel::run_op(), CpuWeightsReshapeKernel::run_op(), CpuGemmLowpOffsetContributionKernel::run_op(), CpuDirectConv3dKernel::run_op(), CpuGemmLowpQuantizeDownInt32ToInt16ScaleByFixedPointKernel::run_op(), CpuDepthwiseConv2dNativeKernel::run_op(), ClCol2ImKernel::run_op(), ClGemmMatrixMultiplyNativeKernel::run_op(), ClIndirectConv2dKernel::run_op(), ClGemmLowpMatrixMultiplyReshapedKernel::run_op(), CpuGemmLowpQuantizeDownInt32ToInt8ScaleByFixedPointKernel::run_op(), CpuGemmLowpQuantizeDownInt32ToUint8ScaleByFixedPointKernel::run_op(), ClGemmMatrixMultiplyReshapedOnlyRhsMMULKernel::run_op(), CpuDepthwiseConv2dAssemblyWrapperKernel::run_op(), CpuGemmTranspose1xWKernel::run_op(), CpuScaleKernel::run_op(), CpuGemmMatrixMultiplyKernel::run_op(), ClGemmLowpOffsetContributionKernel::run_op(), CLStridedSliceKernel::run_op(), ClDirectConv3dKernel::run_op(), CpuMulKernel::run_op(), CpuAddMulAddKernel::run_op(), ClWeightsReshapeKernel::run_op(), ClMatMulNativeMMULKernel::run_op(), CpuWinogradConv2dTransformOutputKernel::run_op(), ClGemmLowpMatrixAReductionKernel::run_op(), ClDirectConv2dKernel::run_op(), ClGemmLowpMatrixMultiplyReshapedOnlyRhsMMULKernel::run_op(), ClGemmLowpOffsetContributionOutputStageKernel::run_op(), ClMulKernel::run_op(), CLFillBorderKernel::run_op(), ClGemmLowpMatrixMultiplyReshapedOnlyRhsKernel::run_op(), ClGemmMatrixMultiplyReshapedOnlyRhsKernel::run_op(), ClIm2ColKernel::run_op(), NEStridedSliceKernel::run_op(), CpuIm2ColKernel::run_op(), ClGemmMatrixMultiplyReshapedKernel::run_op(), CpuLogits1DSoftmaxKernel< IS_LOG >::run_op(), CpuGemmLowpOffsetContributionOutputStageKernel::run_op(), CpuGemmLowpMatrixBReductionKernel::run_op(), ClGemmLowpMatrixBReductionKernel::run_op(), ClComplexMulKernel::run_op(), and CpuComplexMulKernel::run_op().
get_tensor()
ITensor * get_tensor (int id)
Get tensor of a given id from the pac.
Parameters
[in] id ID of tensor to extract
Returns
The pointer to the tensor if exist and is non-const else nullptr
Definition at line 63 of file ITensorPack.cpp.
 {
     auto it = _pack.find(id);
     return it != _pack.end() ? it->second.tensor : nullptr;
 }
Referenced by CLAuxTensorHandler::CLAuxTensorHandler(), CpuAuxTensorHandler::CpuAuxTensorHandler(), TensorPack::get_tensor(), CpuScale::prepare(), CpuReshapeKernel::prepare(), CpuDepthwiseConv2dAssemblyDispatch::prepare(), CpuGemmDirectConv2d::prepare(), CpuWinogradConv2d::prepare(), ClGemm::prepare(), ClWinogradConv2d::prepare(), ClGemmConv2d::prepare(), CpuGemmLowpMatrixMultiplyCore::prepare(), ClPRelu::run(), CpuConcatenate::run(), CpuAddMulAdd::run(), ClConcatenate::run(), CpuSoftmaxGeneric< IS_LOG >::run(), CpuMatMul::run(), CpuGemmDirectConv2d::run(), ClGemmLowpOutputStage::run(), CpuDirectConv3d::run(), CpuWinogradConv2d::run(), CpuDirectConv2d::run(), ClGemmLowpMatrixMultiplyCore::run(), ClGemm::run(), ClWinogradConv2d::run(), ClGemmConv2d::run(), CpuGemmLowpMatrixMultiplyCore::run(), CpuGemm::run(), CpuGemmConv2d::run(), CpuFillKernel::run_op(), CpuElementwiseKernel< CpuArithmeticKernel >::run_op(), ClElementwiseKernel::run_op(), CpuDequantizeKernel::run_op(), CpuConvertQuantizedSignednessKernel::run_op(), CpuTransposeKernel::run_op(), CpuCopyKernel::run_op(), CpuReshapeKernel::run_op(), ClKernelRuntime::run_op(), ClDequantizeKernel::run_op(), ClFloorKernel::run_op(), ClReshapeKernel::run_op(), ClTransposeKernel::run_op(), CpuConcatenateBatchKernel::run_op(), CpuPermuteKernel::run_op(), CpuLogits1DMaxKernel::run_op(), CpuConcatenateHeightKernel::run_op(), CpuConcatenateWidthKernel::run_op(), ClWidthConcatenate2TensorsKernel::run_op(), CpuQuantizeKernel::run_op(), ClCopyKernel::run_op(), ClElementWiseUnaryKernel::run_op(), ClWidthConcatenateKernel::run_op(), ClHeightConcatenateKernel::run_op(), ClQuantizeKernel::run_op(), ClScaleKernel::run_op(), NELogicalKernel::run_op(), ClPool3dKernel::run_op(), ClBatchConcatenateKernel::run_op(), ClDepthConcatenateKernel::run_op(), ClTransposedConvolutionKernel::run_op(), ClActivationKernel::run_op(), CpuConcatenateDepthKernel::run_op(), CpuFloorKernel::run_op(), ClPermuteKernel::run_op(), CpuGemmLowpMatrixAReductionKernel::run_op(), ClPool2dKernel::run_op(), CpuGemmLowpMatrixMultiplyKernel::run_op(), CpuPool2dKernel::run_op(), CpuElementwiseUnaryKernel::run_op(), ClSoftmaxKernel::run_op(), CpuConvertFullyConnectedWeightsKernel::run_op(), CpuPool3dKernel::run_op(), ClMatMulLowpNativeMMULKernel::run_op(), ClWidthConcatenate4TensorsKernel::run_op(), CpuDirectConv2dKernel::run_op(), CpuGemmInterleave4x4Kernel::run_op(), ClConvertFullyConnectedWeightsKernel::run_op(), ClWinogradInputTransformKernel::run_op(), CpuActivationKernel::run_op(), CpuSubKernel::run_op(), ClWinogradFilterTransformKernel::run_op(), CpuMaxUnpoolingLayerKernel::run_op(), CpuDirectConv2dOutputStageKernel::run_op(), ClGemmReshapeLhsMatrixKernel::run_op(), ClMatMulNativeKernel::run_op(), CpuGemmMatrixAdditionKernel::run_op(), ClCastKernel::run_op(), ClCropKernel::run_op(), CpuCol2ImKernel::run_op(), ClMatMulLowpNativeKernel::run_op(), CpuCastKernel::run_op(), ClGemmLowpMatrixMultiplyNativeKernel::run_op(), ClGemmLowpQuantizeDownInt32ScaleByFixedPointKernel::run_op(), CpuGemmLowpQuantizeDownInt32ScaleKernel::run_op(), CpuPool2dAssemblyWrapperKernel::run_op(), CpuAddKernel::run_op(), ClGemmReshapeRhsMatrixKernel::run_op(), ClGemmLowpQuantizeDownInt32ScaleByFloatKernel::run_op(), ClIndirectConv2dAddressPrecalculationKernel::run_op(), ClGemmLowpQuantizeDownInt32ScaleKernel::run_op(), ClWinogradOutputTransformKernel::run_op(), CpuGemmLowpOffsetContributionKernel::run_op(), CpuWeightsReshapeKernel::run_op(), CpuDirectConv3dKernel::run_op(), CpuGemmLowpQuantizeDownInt32ToInt16ScaleByFixedPointKernel::run_op(), CpuDepthwiseConv2dNativeKernel::run_op(), ClCol2ImKernel::run_op(), ClIndirectConv2dKernel::run_op(), NEFillBorderKernel::run_op(), ClGemmMatrixMultiplyNativeKernel::run_op(), ClGemmLowpMatrixMultiplyReshapedKernel::run_op(), CpuGemmLowpQuantizeDownInt32ToUint8ScaleByFixedPointKernel::run_op(), CpuGemmLowpQuantizeDownInt32ToInt8ScaleByFixedPointKernel::run_op(), CpuDepthwiseConv2dAssemblyWrapperKernel::run_op(), ClGemmMatrixMultiplyReshapedOnlyRhsMMULKernel::run_op(), CLStridedSliceKernel::run_op(), ClGemmLowpOffsetContributionKernel::run_op(), CpuGemmTranspose1xWKernel::run_op(), CpuScaleKernel::run_op(), CpuGemmMatrixMultiplyKernel::run_op(), ClDirectConv3dKernel::run_op(), CpuAddMulAddKernel::run_op(), CpuMulKernel::run_op(), ClWeightsReshapeKernel::run_op(), CpuWinogradConv2dTransformOutputKernel::run_op(), ClMatMulNativeMMULKernel::run_op(), ClGemmLowpMatrixAReductionKernel::run_op(), ClDirectConv2dKernel::run_op(), ClGemmLowpMatrixMultiplyReshapedOnlyRhsMMULKernel::run_op(), ClMulKernel::run_op(), ClGemmLowpOffsetContributionOutputStageKernel::run_op(), ClGemmLowpMatrixMultiplyReshapedOnlyRhsKernel::run_op(), ClGemmMatrixMultiplyReshapedOnlyRhsKernel::run_op(), ClIm2ColKernel::run_op(), NEStridedSliceKernel::run_op(), CpuIm2ColKernel::run_op(), ClGemmMatrixMultiplyReshapedKernel::run_op(), CpuGemmLowpOffsetContributionOutputStageKernel::run_op(), CpuLogits1DSoftmaxKernel< IS_LOG >::run_op(), CpuGemmLowpMatrixBReductionKernel::run_op(), ClGemmLowpMatrixBReductionKernel::run_op(), ClComplexMulKernel::run_op(), and CpuComplexMulKernel::run_op().
remove_tensor()
void remove_tensor (int id)
Remove the tensor stored with the given id.
Parameters
[in] id ID of tensor to remove
Definition at line 69 of file ITensorPack.cpp.
 {
     _pack.erase(id);
 }
Referenced by ClWinogradConv2d::run(), CLAuxTensorHandler::~CLAuxTensorHandler(), and CpuAuxTensorHandler::~CpuAuxTensorHandler().
size()
size_t size () const
Pack size accessor.
Returns
Number of tensors registered to the pack
Definition at line 74 of file ITensorPack.cpp.
 {
     return _pack.size();
 }
Referenced by CpuConcatenate::run(), ClConcatenate::run(), and TensorPack::size().
The documentation for this class was generated from the following files:
arm_compute/core/ITensorPack.h
src/core/ITensorPack.cpp