Compute Library: PassManager Class Reference
PassManager Class Reference final
Pass manager.
#include <PassManager.h>
Public Member Functions
PassManager ()
Constructor.
PassManager (const PassManager &)=delete
Prevent instances of this class from being copied (As this class contains pointers)
PassManager (PassManager &&)=default
Default move constructor.
PassManager & operator= (const PassManager &)=delete
Prevent instances of this class from being copied (As this class contains pointers)
PassManager & operator= (PassManager &&)=default
Default move assignment operator.
const std::vector< std::unique_ptr< IGraphMutator > > & passes () const
Mutation passes accessors.
IGraphMutator * pass (size_t index)
Accessor of a pass at a given index.
void append (std::unique_ptr< IGraphMutator > pass, bool conditional=true)
Appends a mutation pass.
void clear ()
Clears all the passes.
void run_all (Graph &g)
Runs all the mutation passes on a given graph.
void run_type (Graph &g, IGraphMutator::MutationType type)
Runs a mutation passes of a specific type on a given graph.
void run_index (Graph &g, size_t index)
Runs a specific mutation pass on a given graph.
Detailed Description
Pass manager.
Responsible for performing the mutating graph passes with a given order
Definition at line 43 of file PassManager.h.
Constructor & Destructor Documentation
PassManager() [1/3]
PassManager ()
Constructor.
Definition at line 32 of file PassManager.cpp.
                          : _passes()
 {
 }
PassManager() [2/3]
PassManager (const PassManager &) delete
Prevent instances of this class from being copied (As this class contains pointers)
PassManager() [3/3]
PassManager (PassManager &&) default
Default move constructor.
Member Function Documentation
append()
void append (std::unique_ptr< IGraphMutator > pass, bool conditional = true)
Appends a mutation pass.
Parameters
[in] pass Pass to append
[in] conditional (Optional) Append pass if true else false. Defaults to true.
Definition at line 46 of file PassManager.cpp.
 {
     if (pass && conditional)
     {
         ARM_COMPUTE_LOG_GRAPH_VERBOSE("Appending mutating pass : " << pass->name() << std::endl);
         _passes.push_back(std::move(pass));
     }
 }
References ARM_COMPUTE_LOG_GRAPH_VERBOSE, IGraphMutator::name(), and PassManager::pass().
Referenced by arm_compute::graph::create_default_pass_manager().
clear()
void clear ()
Clears all the passes.
Definition at line 55 of file PassManager.cpp.
 {
     _passes.clear();
 }
operator=() [1/2]
PassManager& operator= (const PassManager &) delete
Prevent instances of this class from being copied (As this class contains pointers)
operator=() [2/2]
PassManager& operator= (PassManager &&) default
Default move assignment operator.
pass()
IGraphMutator * pass (size_t index)
Accessor of a pass at a given index.
Parameters
[in] index Index of the requested pass
Returns
A pointer to the given pass if exists else nullptr
Definition at line 41 of file PassManager.cpp.
 {
     return (index >= _passes.size()) ? nullptr : _passes.at(index).get();
 }
Referenced by PassManager::append(), PassManager::run_all(), PassManager::run_index(), and PassManager::run_type().
passes()
const std::vector< std::unique_ptr< IGraphMutator > > & passes () const
Mutation passes accessors.
Returns
Returns the vector with the mutation passes that are to be executed on a graph
Definition at line 36 of file PassManager.cpp.
 {
     return _passes;
 }
run_all()
void run_all (Graph & g)
Runs all the mutation passes on a given graph.
Parameters
[in,out] g Graph to run the mutations on
Definition at line 60 of file PassManager.cpp.
 {
     for (auto &pass : _passes)
     {
         if (pass)
         {
             ARM_COMPUTE_LOG_GRAPH_INFO("Running mutating pass : " << pass->name() << std::endl);
             pass->mutate(g);
         }
     }
 }
References ARM_COMPUTE_LOG_GRAPH_INFO, IGraphMutator::mutate(), IGraphMutator::name(), and PassManager::pass().
run_index()
void run_index (Graph & g, size_t index)
Runs a specific mutation pass on a given graph.
Parameters
[in,out] g Graph to run the mutation on
[in] index Index of the mutation to execute
Definition at line 84 of file PassManager.cpp.
 {
     if (index >= _passes.size())
     {
         return;
     }
     auto &pass = _passes.at(index);
     if (pass != nullptr)
     {
         ARM_COMPUTE_LOG_GRAPH_INFO("Running mutating pass : " << pass->name() << std::endl);
         pass->mutate(g);
     }
 }
References ARM_COMPUTE_LOG_GRAPH_INFO, IGraphMutator::mutate(), IGraphMutator::name(), and PassManager::pass().
run_type()
void run_type (Graph & g, IGraphMutator::MutationType type)
Runs a mutation passes of a specific type on a given graph.
Parameters
[in,out] g Graph to run the mutation on
[in] type Type of the mutations to execute
Definition at line 72 of file PassManager.cpp.
 {
     for (auto &pass : _passes)
     {
         if (pass && (pass->type() == type))
         {
             ARM_COMPUTE_LOG_GRAPH_INFO("Running mutating pass : " << pass->name() << std::endl);
             pass->mutate(g);
         }
     }
 }
References ARM_COMPUTE_LOG_GRAPH_INFO, IGraphMutator::mutate(), IGraphMutator::name(), PassManager::pass(), IGraphMutator::type(), and type.
Referenced by GraphManager::finalize_graph().
The documentation for this class was generated from the following files:
arm_compute/graph/PassManager.h
src/graph/PassManager.cpp