Compute Library: ClampAttributes Class Reference
ClampAttributes Class Reference
Attributes are backend-agnostic parameters (in addition to the input/output tensors) of an operator.
#include <ClampAttributes.h>
Public Member Functions
ClampAttributes & min_val (const float &min_val)
Set the minimum clip value.
float min_val () const
Get the minimum clip value.
ClampAttributes & max_val (const float &max_val)
Set the maximum clip value.
float max_val () const
Get the maximum clip value.
Detailed Description
Attributes are backend-agnostic parameters (in addition to the input/output tensors) of an operator.
Clamp attributes
Definition at line 40 of file ClampAttributes.h.
Member Function Documentation
max_val() [1/2]
float max_val () const
Get the maximum clip value.
Definition at line 51 of file ClampAttributes.cpp.
 {
     return _max_val;
 }
Referenced by ClampAttributes::max_val().
max_val() [2/2]
ClampAttributes & max_val (const float & max_val)
Set the maximum clip value.
Definition at line 45 of file ClampAttributes.cpp.
 {
     _max_val = max_val;
     return *this;
 }
References ClampAttributes::max_val().
Referenced by arm_compute::test::validation::combine(), GpuClamp::create_op(), arm_compute::test::validation::FIXTURE_DATA_TEST_CASE(), and arm_compute::operator<<().
min_val() [1/2]
float min_val () const
Get the minimum clip value.
Definition at line 40 of file ClampAttributes.cpp.
 {
     return _min_val;
 }
Referenced by ClampAttributes::min_val().
min_val() [2/2]
ClampAttributes & min_val (const float & min_val)
Set the minimum clip value.
Definition at line 34 of file ClampAttributes.cpp.
 {
     _min_val = min_val;
     return *this;
 }
References ClampAttributes::min_val().
Referenced by arm_compute::test::validation::combine(), GpuClamp::create_op(), arm_compute::test::validation::FIXTURE_DATA_TEST_CASE(), and arm_compute::operator<<().
The documentation for this class was generated from the following files:
arm_compute/dynamic_fusion/sketch/attributes/ClampAttributes.h
src/dynamic_fusion/sketch/attributes/ClampAttributes.cpp