Compute Library: CLBuildOptions Class Reference
CLBuildOptions Class Reference final
Build options.
#include <CLCompileContext.h>
Public Member Functions
CLBuildOptions ()
Default constructor.
void add_option (std::string option)
Adds option to the existing build option list.
void add_option_if (bool cond, std::string option)
Adds option if a given condition is true;.
void add_option_if_else (bool cond, std::string option_true, std::string option_false)
Adds first option if condition is true else the second one.
void add_options (const StringSet &options)
Appends given build options to the current's objects options.
void add_options_if (bool cond, const StringSet &options)
Appends given build options to the current's objects options if a given condition is true.
const StringSet & options () const
Gets the current options list set.
bool operator== (const CLBuildOptions &other) const
Detailed Description
Build options.
Definition at line 38 of file CLCompileContext.h.
Constructor & Destructor Documentation
CLBuildOptions()
CLBuildOptions ()
Default constructor.
Definition at line 37 of file CLCompileContext.cpp.
                                : _build_opts()
 {
 }
Member Function Documentation
add_option()
void add_option (std::string option)
Adds option to the existing build option list.
Parameters
[in] option Option to add
Definition at line 41 of file CLCompileContext.cpp.
 {
     _build_opts.emplace(std::move(option));
 }
Referenced by CLBuildOptions::add_option_if(), CLBuildOptions::add_option_if_else(), ClTransposeKernel::configure(), ClDequantizeKernel::configure(), ClFloorKernel::configure(), ClElementWiseUnaryKernel::configure(), ClFillKernel::configure(), ClCopyKernel::configure(), ClMatMulLowpNativeMMULKernel::configure(), ClWidthConcatenate2TensorsKernel::configure(), ClPool3dKernel::configure(), ClPool2dKernel::configure(), ClHeightConcatenateKernel::configure(), ClQuantizeKernel::configure(), ClScaleKernel::configure(), ClWidthConcatenateKernel::configure(), ClPermuteKernel::configure(), ClWidthConcatenate4TensorsKernel::configure(), ClActivationKernel::configure(), ClMatMulNativeKernel::configure(), ClCropKernel::configure(), CLStridedSliceKernel::configure(), ClBatchConcatenateKernel::configure(), ClDepthConcatenateKernel::configure(), ClMatMulLowpNativeKernel::configure(), ClConvertFullyConnectedWeightsKernel::configure(), ClGemmLowpMatrixMultiplyNativeKernel::configure(), ClGemmReshapeLhsMatrixKernel::configure(), ClGemmMatrixMultiplyNativeKernel::configure(), CLInstanceNormalizationLayerKernel::configure(), CLBitwiseKernel::configure(), CLMaxUnpoolingLayerKernel::configure(), CLChannelShuffleLayerKernel::configure(), ClGemmLowpQuantizeDownInt32ScaleByFixedPointKernel::configure(), ClGemmMatrixMultiplyReshapedOnlyRhsMMULKernel::configure(), ClWinogradInputTransformKernel::configure(), CLSelectKernel::configure(), ClGemmLowpQuantizeDownInt32ScaleByFloatKernel::configure(), ClGemmLowpQuantizeDownInt32ScaleKernel::configure(), CLComputeAllAnchorsKernel::configure(), CLDeconvolutionLayerUpsampleKernel::configure(), ClWinogradOutputTransformKernel::configure(), CLFFTScaleKernel::configure(), CLSpaceToDepthLayerKernel::configure(), ClSoftmaxKernel::configure(), CLDepthToSpaceLayerKernel::configure(), CLNormalizationLayerKernel::configure(), CLQLSTMLayerNormalizationKernel::configure(), CLSpaceToBatchLayerKernel::configure(), CLTileKernel::configure(), CLGatherKernel::configure(), ClCastKernel::configure(), ClGemmLowpMatrixMultiplyReshapedKernel::configure(), ClGemmLowpOffsetContributionKernel::configure(), CLReorgLayerKernel::configure(), ClGemmLowpOffsetContributionOutputStageKernel::configure(), CLMeanStdDevNormalizationKernel::configure(), ClGemmReshapeRhsMatrixKernel::configure(), CLFFTDigitReverseKernel::configure(), CLBatchToSpaceLayerKernel::configure(), CLNormalizePlanarYUVLayerKernel::configure(), CLRangeKernel::configure(), CLReverseKernel::configure(), CLReductionOperationKernel::configure(), CLFFTRadixStageKernel::configure(), ClCol2ImKernel::configure(), ClGemmLowpMatrixMultiplyReshapedOnlyRhsKernel::configure(), CLL2NormalizeLayerKernel::configure(), ClMatMulNativeMMULKernel::configure(), CLPadLayerKernel::configure(), CLArgMinMaxLayerKernel::configure(), ClMulKernel::configure(), ClGemmMatrixMultiplyReshapedOnlyRhsKernel::configure(), CLBoundingBoxTransformKernel::configure(), CLDepthwiseConvolutionLayerNativeKernel::configure(), CLROIPoolingLayerKernel::configure(), CLPriorBoxLayerKernel::configure(), ClWeightsReshapeKernel::configure(), CLStackLayerKernel::configure(), ClGemmLowpMatrixAReductionKernel::configure(), CLROIAlignLayerKernel::configure(), CLFillBorderKernel::configure(), ClGemmMatrixMultiplyReshapedKernel::configure(), CLDeconvolutionReshapeOutputKernel::configure(), CLFuseBatchNormalizationKernel::configure(), CLBatchNormalizationLayerKernel::configure(), CLComputeMeanVariance::configure(), ClComplexMulKernel::configure(), ClGemmLowpMatrixBReductionKernel::configure(), ClTemplateCast::get_build_options(), ClTemplateDepthwiseConv2d::get_build_options(), ClTemplateDirectConv2d::get_build_options(), ClTemplateResize::get_build_options(), ClTemplatePool2d::get_build_options(), ClTemplateActivation::get_build_options(), and arm_compute::set_unroll_with_pragma().
add_option_if()
void add_option_if (bool cond, std::string option)
Adds option if a given condition is true;.
Parameters
[in] cond Condition to check
[in] option Option to add if condition is true
Definition at line 46 of file CLCompileContext.cpp.
 {
     if (cond)
     {
         add_option(std::move(option));
     }
 }
References CLBuildOptions::add_option().
Referenced by ClDequantizeKernel::configure(), ClFillKernel::configure(), ClMatMulLowpNativeMMULKernel::configure(), ClPool2dKernel::configure(), ClPool3dKernel::configure(), ClQuantizeKernel::configure(), ClScaleKernel::configure(), ClActivationKernel::configure(), ClMatMulNativeKernel::configure(), ClCropKernel::configure(), CLStridedSliceKernel::configure(), ClMatMulLowpNativeKernel::configure(), ClGemmLowpMatrixMultiplyNativeKernel::configure(), ClGemmReshapeLhsMatrixKernel::configure(), ClGemmMatrixMultiplyNativeKernel::configure(), CLInstanceNormalizationLayerKernel::configure(), ClGemmMatrixMultiplyReshapedOnlyRhsMMULKernel::configure(), CLChannelShuffleLayerKernel::configure(), ClWinogradInputTransformKernel::configure(), ClGemmLowpQuantizeDownInt32ScaleByFixedPointKernel::configure(), ClGemmLowpQuantizeDownInt32ScaleByFloatKernel::configure(), ClGemmLowpQuantizeDownInt32ScaleKernel::configure(), ClWinogradOutputTransformKernel::configure(), CLFFTScaleKernel::configure(), ClSoftmaxKernel::configure(), CLNormalizationLayerKernel::configure(), CLTileKernel::configure(), ClCastKernel::configure(), ClGemmLowpMatrixMultiplyReshapedKernel::configure(), ClGemmReshapeRhsMatrixKernel::configure(), CLFFTDigitReverseKernel::configure(), CLMeanStdDevNormalizationKernel::configure(), ClGemmLowpOffsetContributionKernel::configure(), ClGemmLowpOffsetContributionOutputStageKernel::configure(), CLReverseKernel::configure(), CLReductionOperationKernel::configure(), CLFFTRadixStageKernel::configure(), ClGemmLowpMatrixMultiplyReshapedOnlyRhsKernel::configure(), ClMatMulNativeMMULKernel::configure(), CLArgMinMaxLayerKernel::configure(), ClMulKernel::configure(), ClGemmMatrixMultiplyReshapedOnlyRhsKernel::configure(), CLBoundingBoxTransformKernel::configure(), CLDepthwiseConvolutionLayerNativeKernel::configure(), ClWeightsReshapeKernel::configure(), CLPriorBoxLayerKernel::configure(), CLROIAlignLayerKernel::configure(), ClGemmMatrixMultiplyReshapedKernel::configure(), CLDeconvolutionReshapeOutputKernel::configure(), CLFuseBatchNormalizationKernel::configure(), CLBatchNormalizationLayerKernel::configure(), CLComputeMeanVariance::configure(), and ClGemmLowpMatrixBReductionKernel::configure().
add_option_if_else()
void add_option_if_else (bool cond, std::string option_true, std::string option_false)
Adds first option if condition is true else the second one.
Parameters
[in] cond Condition to check
[in] option_true Option to add if condition is true
[in] option_false Option to add if condition is false
Definition at line 54 of file CLCompileContext.cpp.
 {
     (cond) ? add_option(std::move(option_true)) : add_option(std::move(option_false));
 }
References CLBuildOptions::add_option().
Referenced by ClScaleKernel::configure(), ClMatMulNativeKernel::configure(), CLStridedSliceKernel::configure(), ClGemmReshapeLhsMatrixKernel::configure(), ClMulKernel::configure(), CLArgMinMaxLayerKernel::configure(), and CLDepthwiseConvolutionLayerNativeKernel::configure().
add_options()
void add_options (const StringSet & options)
Appends given build options to the current's objects options.
Parameters
[in] options Build options to append
Definition at line 59 of file CLCompileContext.cpp.
 {
     _build_opts.insert(options.begin(), options.end());
 }
References CLBuildOptions::options().
Referenced by CLBuildOptions::add_options_if(), and ClTemplateWriter::get_build_options().
add_options_if()
void add_options_if (bool cond, const StringSet & options)
Appends given build options to the current's objects options if a given condition is true.
Parameters
[in] cond Condition to check
[in] options Option to add if condition is true
Definition at line 64 of file CLCompileContext.cpp.
 {
     if (cond)
     {
         add_options(options);
     }
 }
References CLBuildOptions::add_options(), and CLBuildOptions::options().
operator==()
bool operator== (const CLBuildOptions & other) const
Definition at line 77 of file CLCompileContext.cpp.
 {
     return _build_opts == other._build_opts;
 }
options()
const CLBuildOptions::StringSet & options () const
Gets the current options list set.
Returns
Build options set
Definition at line 72 of file CLCompileContext.cpp.
 {
     return _build_opts;
 }
Referenced by CLBuildOptions::add_options(), CLBuildOptions::add_options_if(), ClTransposeKernel::configure(), ClDequantizeKernel::configure(), ClFloorKernel::configure(), ClElementWiseUnaryKernel::configure(), ClFillKernel::configure(), ClMatMulLowpNativeMMULKernel::configure(), ClWidthConcatenate2TensorsKernel::configure(), ClPool2dKernel::configure(), ClPool3dKernel::configure(), ClHeightConcatenateKernel::configure(), ClQuantizeKernel::configure(), ClScaleKernel::configure(), ClWidthConcatenateKernel::configure(), ClPermuteKernel::configure(), ClActivationKernel::configure(), ClWidthConcatenate4TensorsKernel::configure(), ClMatMulNativeKernel::configure(), ClCropKernel::configure(), CLStridedSliceKernel::configure(), ClDepthConcatenateKernel::configure(), ClBatchConcatenateKernel::configure(), ClMatMulLowpNativeKernel::configure(), ClConvertFullyConnectedWeightsKernel::configure(), ClGemmLowpMatrixMultiplyNativeKernel::configure(), ClGemmReshapeLhsMatrixKernel::configure(), CLInstanceNormalizationLayerKernel::configure(), CLMaxUnpoolingLayerKernel::configure(), CLBitwiseKernel::configure(), ClGemmMatrixMultiplyNativeKernel::configure(), ClGemmMatrixMultiplyReshapedOnlyRhsMMULKernel::configure(), CLChannelShuffleLayerKernel::configure(), ClWinogradInputTransformKernel::configure(), ClGemmLowpQuantizeDownInt32ScaleByFixedPointKernel::configure(), CLSelectKernel::configure(), CLDeconvolutionLayerUpsampleKernel::configure(), CLComputeAllAnchorsKernel::configure(), ClWinogradOutputTransformKernel::configure(), ClGemmLowpQuantizeDownInt32ScaleByFloatKernel::configure(), ClGemmLowpQuantizeDownInt32ScaleKernel::configure(), ClSoftmaxKernel::configure(), CLSpaceToDepthLayerKernel::configure(), CLFFTScaleKernel::configure(), CLDepthToSpaceLayerKernel::configure(), CLNormalizationLayerKernel::configure(), CLQLSTMLayerNormalizationKernel::configure(), CLSpaceToBatchLayerKernel::configure(), CLGatherKernel::configure(), CLTileKernel::configure(), ClCastKernel::configure(), ClGemmLowpMatrixMultiplyReshapedKernel::configure(), ClGemmReshapeRhsMatrixKernel::configure(), CLBatchToSpaceLayerKernel::configure(), CLFFTDigitReverseKernel::configure(), CLMeanStdDevNormalizationKernel::configure(), ClGemmLowpOffsetContributionKernel::configure(), ClGemmLowpOffsetContributionOutputStageKernel::configure(), CLReorgLayerKernel::configure(), CLNormalizePlanarYUVLayerKernel::configure(), CLReverseKernel::configure(), CLRangeKernel::configure(), CLReductionOperationKernel::configure(), ClCol2ImKernel::configure(), CLFFTRadixStageKernel::configure(), ClGemmLowpMatrixMultiplyReshapedOnlyRhsKernel::configure(), CLL2NormalizeLayerKernel::configure(), ClMatMulNativeMMULKernel::configure(), CLArgMinMaxLayerKernel::configure(), ClMulKernel::configure(), ClGemmMatrixMultiplyReshapedOnlyRhsKernel::configure(), CLBoundingBoxTransformKernel::configure(), CLDepthwiseConvolutionLayerNativeKernel::configure(), CLPriorBoxLayerKernel::configure(), CLROIPoolingLayerKernel::configure(), ClWeightsReshapeKernel::configure(), CLStackLayerKernel::configure(), CLROIAlignLayerKernel::configure(), CLFillBorderKernel::configure(), ClGemmMatrixMultiplyReshapedKernel::configure(), CLDeconvolutionReshapeOutputKernel::configure(), CLFuseBatchNormalizationKernel::configure(), CLBatchNormalizationLayerKernel::configure(), CLComputeMeanVariance::configure(), ClComplexMulKernel::configure(), and ClGemmLowpMatrixBReductionKernel::configure().
The documentation for this class was generated from the following files:
arm_compute/core/CL/CLCompileContext.h
src/core/CL/CLCompileContext.cpp