Compute Library: arm_compute::mlgo::parser Namespace Reference
arm_compute::mlgo::parser Namespace Reference
Data Structures
struct CharPosition
struct Token
Token.
class TokenStream
A stream of token.
Enumerations
enum ComparatorType { Enum, Num, Var }
enum TokenType {
L_List = '[', R_List = ']', Int, Float,
Text, End
}
Type of Token.
Functions
void advance (CharPosition &pos, char ch)
void rewind (CharPosition &pos)
void end (TokenStream &in, bool &valid)
bool bool_val (TokenStream &in, bool &valid)
int int_val (TokenStream &in, bool &valid)
unsigned int uint_val (TokenStream &in, bool &valid)
float float_val (TokenStream &in, bool &valid)
std::string text_val (TokenStream &in, bool &valid)
bool accept_text (TokenStream &in, const std::string &c_str, bool take=true)
void expect_text (TokenStream &in, const std::string &str, bool &valid)
bool accept_l_list (TokenStream &in)
void expect_l_list (TokenStream &in, bool &valid)
bool accept_r_list (TokenStream &in)
void expect_r_list (TokenStream &in, bool &valid)
ConditionalOp conditional_op (TokenStream &in, bool &valid)
void gemm_version (TokenStream &in, bool &valid)
void ip_type (TokenStream &in, bool &valid)
void header (TokenStream &in, bool &valid)
DataType data_type (TokenStream &in, bool &valid)
ComparatorType comparator_type (TokenStream &in, bool &valid)
HeuristicType heuristic_type (TokenStream &in, bool &valid, bool take=true)
void expect_heuristic_type (TokenStream &in, HeuristicType expected_ht, bool &valid)
GEMMType gemm_type (TokenStream &in, bool &valid)
GEMMConfigNative gemm_config_native (TokenStream &in, bool &valid)
GEMMConfigReshapedOnlyRHS gemm_config_reshaped_only_rhs (TokenStream &in, bool &valid)
GEMMConfigReshaped gemm_config_reshaped (TokenStream &in, bool &valid)
void gpu_priority (TokenStream &in, bool &valid)
void gpu_behavior (TokenStream &in, bool &valid)
void free_vars (TokenStream &in, bool &valid)
void heuristics_table_entry (TokenStream &in, MLGOHeuristics &h, bool &valid)
void heuristics_table (TokenStream &in, MLGOHeuristics &h, bool &valid)
Condition condition (TokenStream &in, bool &valid)
void heuristic_tree (TokenStream &in, MLGOHeuristics &h, bool &valid)
MLGOHeuristics mlgo (TokenStream &in, bool &valid)
std::pair< bool, MLGOHeuristics > parse_mlgo (std::istream &in)
Parse and construct a MLGOHeuristics from input stream.
std::ostream & operator<< (std::ostream &os, const CharPosition &pos)
Enumeration Type Documentation
ComparatorType
enum ComparatorType strong
Enumerator
Enum
Num
Var
Definition at line 98 of file MLGOParser.cpp.
 {
     Enum,
     Num,
     Var
 };
TokenType
enum TokenType strong
Type of Token.
Enumerator
L_List
List open.
R_List
List close.
Int
Integral.
Float
Floating.
Text
Text/String.
End
End of stream.
Definition at line 84 of file MLGOParser.h.
 {
     L_List = '[', /**< List open */
     R_List = ']', /**< List close */
     Int,          /**< Integral */
     Float,        /**< Floating */
     Text,         /**< Text/String */
     End,          /**< End of stream */
 };
Function Documentation
accept_l_list()
bool arm_compute::mlgo::parser::accept_l_list (TokenStream & in)
Definition at line 377 of file MLGOParser.cpp.
 {
     auto tok = in.peek();
     if (tok.type == TokenType::L_List)
     {
         in.take();
         return true;
     }
     return false;
 }
References L_List, TokenStream::peek(), and TokenStream::take().
Referenced by expect_l_list().
accept_r_list()
bool arm_compute::mlgo::parser::accept_r_list (TokenStream & in)
Definition at line 397 of file MLGOParser.cpp.
 {
     auto tok = in.peek();
     if (tok.type == TokenType::R_List)
     {
         in.take();
         return true;
     }
     return false;
 }
References TokenStream::peek(), R_List, and TokenStream::take().
Referenced by expect_r_list(), and free_vars().
accept_text()
bool arm_compute::mlgo::parser::accept_text (TokenStream & in, const std::string & c_str, bool take = true)
Definition at line 354 of file MLGOParser.cpp.
 {
     auto tok = in.peek();
     if (tok.type == TokenType::Text && tok.value == c_str)
     {
         if (take)
         {
             in.take();
         }
         return true;
     }
     return false;
 }
References TokenStream::peek(), TokenStream::take(), and Text.
Referenced by comparator_type(), conditional_op(), data_type(), expect_text(), gemm_type(), gpu_behavior(), gpu_priority(), heuristic_tree(), heuristic_type(), heuristics_table(), ip_type(), and mlgo().
advance()
void arm_compute::mlgo::parser::advance (CharPosition & pos, char ch)
Definition at line 141 of file MLGOParser.cpp.
 {
     if (ch == '\n')
     {
         pos.ln += 1;
         pos.col = 0;
     }
     else
     {
         pos.col += 1;
     }
 }
References CharPosition::col, and CharPosition::ln.
bool_val()
bool arm_compute::mlgo::parser::bool_val (TokenStream & in, bool & valid)
Definition at line 293 of file MLGOParser.cpp.
 {
     LOG_TOKEN_POS(in, pos);
     auto tok = in.take();
     if (tok.type != TokenType::Int)
     {
         FAIL_WITH_MSG_DEFAULT(valid, false, pos, "Expect bool or int token");
     }
     bool val{};
     std::stringstream(tok.value) >> val;
     return val;
 }
References FAIL_WITH_MSG_DEFAULT, Int, LOG_TOKEN_POS, and TokenStream::take().
Referenced by gemm_config_reshaped(), and gemm_config_reshaped_only_rhs().
comparator_type()
ComparatorType arm_compute::mlgo::parser::comparator_type (TokenStream & in, bool & valid)
Definition at line 503 of file MLGOParser.cpp.
 {
     LOG_TOKEN_POS(in, pos);
     if (accept_text(in, "var"))
     {
         return ComparatorType::Var;
     }
     else if (accept_text(in, "num"))
     {
         return ComparatorType::Num;
     }
     else if (accept_text(in, "enum"))
     {
         return ComparatorType::Enum;
     }
     else
     {
         FAIL_WITH_MSG_DEFAULT(valid, ComparatorType::Num, pos, "Expect comparator type");
     }
 }
References accept_text(), Enum, FAIL_WITH_MSG_DEFAULT, LOG_TOKEN_POS, Num, and Var.
Referenced by condition().
condition()
Condition arm_compute::mlgo::parser::condition (TokenStream & in, bool & valid)
Definition at line 690 of file MLGOParser.cpp.
 {
     LOG_TOKEN_POS(in, pos);
     // NOTE: Only simplified Conditions are accepted, which means the lhs comparator type is fixed to Var and that of
     // the rhs is fixed to Num (float)
     const auto invalid_val = Condition{};
     const auto l_t         = CHECK_DEFAULT(comparator_type(in, valid), valid, invalid_val);
     const auto l_v         = CHECK_DEFAULT(text_val(in, valid), valid, invalid_val);
     const auto c_o         = CHECK_DEFAULT(conditional_op(in, valid), valid, invalid_val);
     const auto r_t         = CHECK_DEFAULT(comparator_type(in, valid), valid, invalid_val);
     const auto r_v         = CHECK_DEFAULT(float_val(in, valid), valid, invalid_val);
     if (l_t != ComparatorType::Var || r_t != ComparatorType::Num)
     {
         FAIL_WITH_MSG_DEFAULT(valid, invalid_val, pos,
                               "Only accept LHS type to be Var (string) and RHS type to be Num (float)");
     }
     return Condition{l_v, c_o, r_v};
 }
References CHECK_DEFAULT, comparator_type(), conditional_op(), FAIL_WITH_MSG_DEFAULT, float_val(), LOG_TOKEN_POS, Num, text_val(), and Var.
Referenced by heuristic_tree(), and arm_compute::cpu::select_op().
conditional_op()
ConditionalOp arm_compute::mlgo::parser::conditional_op (TokenStream & in, bool & valid)
Definition at line 417 of file MLGOParser.cpp.
 {
     LOG_TOKEN_POS(in, pos);
     if (accept_text(in, "<="))
     {
         return ConditionalOp::LE;
     }
     else if (accept_text(in, ">="))
     {
         return ConditionalOp::GE;
     }
     else if (accept_text(in, "=="))
     {
         return ConditionalOp::EQ;
     }
     else if (accept_text(in, "<"))
     {
         return ConditionalOp::LT;
     }
     else if (accept_text(in, ">"))
     {
         return ConditionalOp::GT;
     }
     else
     {
         FAIL_WITH_MSG_DEFAULT(valid, ConditionalOp::EQ, pos, "Expect conditional op");
     }
 }
References accept_text(), arm_compute::mlgo::EQ, FAIL_WITH_MSG_DEFAULT, arm_compute::mlgo::GE, arm_compute::mlgo::GT, arm_compute::mlgo::LE, LOG_TOKEN_POS, and arm_compute::mlgo::LT.
Referenced by condition().
data_type()
DataType arm_compute::mlgo::parser::data_type (TokenStream & in, bool & valid)
Definition at line 482 of file MLGOParser.cpp.
 {
     LOG_TOKEN_POS(in, pos);
     if (accept_text(in, "f16"))
     {
         return DataType::F16;
     }
     else if (accept_text(in, "f32"))
     {
         return DataType::F32;
     }
     else if (accept_text(in, "qasymm8"))
     {
         return DataType::QASYMM8;
     }
     else
     {
         FAIL_WITH_MSG_DEFAULT(valid, DataType::QASYMM8, pos, "Expect data type");
     }
 }
References accept_text(), arm_compute::F16, arm_compute::F32, FAIL_WITH_MSG_DEFAULT, LOG_TOKEN_POS, and arm_compute::QASYMM8.
Referenced by heuristics_table_entry().
end()
void arm_compute::mlgo::parser::end (TokenStream & in, bool & valid)
Definition at line 283 of file MLGOParser.cpp.
 {
     LOG_TOKEN_POS(in, pos);
     auto tok = in.take();
     if (tok.type != TokenType::End)
     {
         FAIL_WITH_MSG(valid, pos, "Unexpected token at the end of stream");
     }
 }
References End, FAIL_WITH_MSG, LOG_TOKEN_POS, and TokenStream::take().
Referenced by DependencyGraph::all_tensors(), ISimpleLifetimeManager::are_all_finalized(), CpuInfo::build(), arm_compute::graph::detail::call_all_input_node_accessors(), arm_compute::graph::detail::call_all_output_node_accessors(), Window::collapse_if_possible(), arm_compute::helpers::tensor_transform::compute_strided_slice_output_shape(), AccessWindowTranspose::compute_valid_region(), AccessWindowRectangle::compute_valid_region(), ClCrop::configure(), ClCropKernel::configure(), CLRangeKernel::configure(), NERangeKernel::configure(), CLRange::configure(), CLCrop::configure(), NERange::configure(), ClWinogradConv2d::configure(), CLCropResize::configure(), StackLayerNode::configure_output(), ConcatenateLayerNode::configure_output(), arm_compute::create_window_iterator(), arm_compute::test::validation::reference::crop_and_resize(), arm_compute::helpers::fft::digit_reverse_indices(), ISimpleLifetimeManager::end_lifetime(), arm_compute::enqueue(), arm_compute::error_on_invalid_subwindow(), arm_compute::error_on_mismatching_windows(), arm_compute::error_on_window_dimensions_gte(), arm_compute::error_on_window_not_collapsable_at_dimension(), GemvPretransposed< strategy, To, Tr, OutputStage >::execute(), GemmInterleaved< strategy, To, Tr, OutputStage, MergeStep, FixedFormat, ForceThreadColumns, ForceFloatAccumulate >::execute(), GraphManager::execute_graph(), NPYLoader::fill_tensor(), GraphManager::finalize_graph(), CpuArithmeticKernel::get_available_kernels(), CpuComparisonKernel::get_available_kernels(), Framework::init(), GraphContext::insert_memory_management_ctx(), GraphContext::insert_weights_management_ctx(), arm_compute::cpu::instance_normalization_nchw(), GraphManager::invalidate_graph(), NDRange< 4 >::iterator(), arm_compute::test::framework::dataset::make(), OpenCLClock< output_timestamps >::measurements(), GraphContext::memory_management_ctx(), mlgo(), InPlaceOperationMutator::mutate(), arm_compute::num_of_elements_in_range(), arm_compute::cpuinfo::num_threads_hint(), NEGEMMConv2d::prepare(), NEGEMMLowpMatrixMultiplyCore::prepare(), NEGEMM::prepare(), CLGEMM::prepare(), CLGEMMConvolutionLayer::prepare(), GemmHybridIndirect< strategy, To, Tr, OutputStage, SeparateQuantize, FixedFormat >::pretranspose_B_array_part(), GemmInterleaved< strategy, To, Tr, OutputStage, MergeStep, FixedFormat, ForceThreadColumns, ForceFloatAccumulate >::pretranspose_B_array_part(), GemmCommon< TypeInput, TypeOutput >::pretranspose_B_array_part_generic(), arm_compute::read_file(), CPPDetectionOutputLayer::run(), CPPNonMaximumSuppressionKernel::run(), Framework::run(), ClWinogradInputTransformKernel::run_op(), Window::shape(), Window::split_window(), ISimpleLifetimeManager::start_lifetime(), SchedulerClock< output_timestamps >::test_start(), SchedulerClock< output_timestamps >::test_stop(), arm_gemm::to_ndcoord(), arm_gemm::to_ndrange(), arm_compute::test::tolower(), arm_compute::utility::tolower(), PoolManager::unlock_pool(), AccessWindowTranspose::update_window_if_needed(), AccessWindowRectangle::update_window_if_needed(), ClCrop::validate(), ClCropKernel::validate(), NERangeKernel::validate(), CLRangeKernel::validate(), CLRange::validate(), NERange::validate(), CLCrop::validate(), Window::validate(), ValidationInputAccessor::ValidationInputAccessor(), ValidationOutputAccessor::ValidationOutputAccessor(), and GraphContext::weights_management_ctx().
expect_heuristic_type()
void arm_compute::mlgo::parser::expect_heuristic_type (TokenStream & in, HeuristicType expected_ht, bool & valid)
Definition at line 549 of file MLGOParser.cpp.
 {
     LOG_TOKEN_POS(in, pos);
     auto ht = CHECK(heuristic_type(in, valid, false), valid);
     if (ht != expected_ht)
     {
         FAIL_WITH_MSG(valid, pos, "Unexpected heuristic type");
     }
     CHECK(heuristic_type(in, valid, true), valid);
 }
References CHECK, FAIL_WITH_MSG, heuristic_type(), and LOG_TOKEN_POS.
Referenced by heuristic_tree().
expect_l_list()
void arm_compute::mlgo::parser::expect_l_list (TokenStream & in, bool & valid)
Definition at line 388 of file MLGOParser.cpp.
 {
     LOG_TOKEN_POS(in, pos);
     if (!accept_l_list(in))
     {
         FAIL_WITH_MSG(valid, pos, "Expect '['");
     }
 }
References accept_l_list(), FAIL_WITH_MSG, and LOG_TOKEN_POS.
Referenced by free_vars(), gemm_config_native(), gemm_config_reshaped(), gemm_config_reshaped_only_rhs(), and gemm_version().
expect_r_list()
void arm_compute::mlgo::parser::expect_r_list (TokenStream & in, bool & valid)
Definition at line 408 of file MLGOParser.cpp.
 {
     LOG_TOKEN_POS(in, pos);
     if (!accept_r_list(in))
     {
         FAIL_WITH_MSG(valid, pos, "Expect ']'");
     }
 }
References accept_r_list(), FAIL_WITH_MSG, and LOG_TOKEN_POS.
Referenced by gemm_config_native(), gemm_config_reshaped(), gemm_config_reshaped_only_rhs(), and gemm_version().
expect_text()
void arm_compute::mlgo::parser::expect_text (TokenStream & in, const std::string & str, bool & valid)
Definition at line 368 of file MLGOParser.cpp.
 {
     LOG_TOKEN_POS(in, pos);
     if (!accept_text(in, str))
     {
         FAIL_WITH_MSG(valid, pos, std::string("Expect text token: ") + str);
     }
 }
References accept_text(), FAIL_WITH_MSG, LOG_TOKEN_POS, and caffe_mnist_image_extractor::str.
Referenced by gemm_version(), header(), heuristic_tree(), heuristics_table(), and ip_type().
float_val()
float arm_compute::mlgo::parser::float_val (TokenStream & in, bool & valid)
Definition at line 330 of file MLGOParser.cpp.
 {
     LOG_TOKEN_POS(in, pos);
     auto tok = in.take();
     if (tok.type != TokenType::Float)
     {
         FAIL_WITH_MSG_DEFAULT(valid, 0.f, pos, "Expect float token");
     }
     float val{};
     std::stringstream(tok.value) >> val;
     return val;
 }
References FAIL_WITH_MSG_DEFAULT, Float, LOG_TOKEN_POS, and TokenStream::take().
Referenced by condition().
free_vars()
void arm_compute::mlgo::parser::free_vars (TokenStream & in, bool & valid)
Definition at line 658 of file MLGOParser.cpp.
 {
     CHECK(expect_l_list(in, valid), valid);
     while (!accept_r_list(in))
     {
         CHECK(text_val(in, valid), valid);
     }
 }
References accept_r_list(), CHECK, expect_l_list(), and text_val().
Referenced by heuristics_table_entry().
gemm_config_native()
GEMMConfigNative arm_compute::mlgo::parser::gemm_config_native (TokenStream & in, bool & valid)
Definition at line 581 of file MLGOParser.cpp.
 {
     const auto invalid_val = GEMMConfigNative{};
     CHECK_DEFAULT(expect_l_list(in, valid), valid, invalid_val);
     const auto m0 = CHECK_DEFAULT(uint_val(in, valid), valid, invalid_val);
     const auto n0 = CHECK_DEFAULT(uint_val(in, valid), valid, invalid_val);
     const auto k0 = CHECK_DEFAULT(uint_val(in, valid), valid, invalid_val);
     CHECK_DEFAULT(expect_r_list(in, valid), valid, invalid_val);
     return GEMMConfigNative{m0, n0, k0};
 }
References CHECK_DEFAULT, expect_l_list(), expect_r_list(), and uint_val().
Referenced by heuristic_tree().
gemm_config_reshaped()
GEMMConfigReshaped arm_compute::mlgo::parser::gemm_config_reshaped (TokenStream & in, bool & valid)
Definition at line 607 of file MLGOParser.cpp.
 {
     const auto invalid_val = GEMMConfigReshaped{};
     CHECK_DEFAULT(expect_l_list(in, valid), valid, invalid_val);
     const auto m0 = CHECK_DEFAULT(uint_val(in, valid), valid, invalid_val);
     const auto n0 = CHECK_DEFAULT(uint_val(in, valid), valid, invalid_val);
     const auto k0 = CHECK_DEFAULT(uint_val(in, valid), valid, invalid_val);
     const auto v0 = CHECK_DEFAULT(uint_val(in, valid), valid, invalid_val);
     const auto h0 = CHECK_DEFAULT(uint_val(in, valid), valid, invalid_val);
     const auto il = CHECK_DEFAULT(bool_val(in, valid), valid, invalid_val);
     const auto ir = CHECK_DEFAULT(bool_val(in, valid), valid, invalid_val);
     const auto tr = CHECK_DEFAULT(bool_val(in, valid), valid, invalid_val);
     const auto ex = CHECK_DEFAULT(bool_val(in, valid), valid, invalid_val);
     CHECK_DEFAULT(expect_r_list(in, valid), valid, invalid_val);
     return GEMMConfigReshaped{m0, n0, k0, v0, h0, il, ir, tr, ex};
 }
References bool_val(), CHECK_DEFAULT, expect_l_list(), expect_r_list(), and uint_val().
Referenced by heuristic_tree().
gemm_config_reshaped_only_rhs()
GEMMConfigReshapedOnlyRHS arm_compute::mlgo::parser::gemm_config_reshaped_only_rhs (TokenStream & in, bool & valid)
Definition at line 592 of file MLGOParser.cpp.
 {
     const auto invalid_val = GEMMConfigReshapedOnlyRHS{};
     CHECK_DEFAULT(expect_l_list(in, valid), valid, invalid_val);
     const auto m0 = CHECK_DEFAULT(uint_val(in, valid), valid, invalid_val);
     const auto n0 = CHECK_DEFAULT(uint_val(in, valid), valid, invalid_val);
     const auto k0 = CHECK_DEFAULT(uint_val(in, valid), valid, invalid_val);
     const auto h0 = CHECK_DEFAULT(uint_val(in, valid), valid, invalid_val);
     const auto ir = CHECK_DEFAULT(bool_val(in, valid), valid, invalid_val);
     const auto tr = CHECK_DEFAULT(bool_val(in, valid), valid, invalid_val);
     const auto ex = CHECK_DEFAULT(bool_val(in, valid), valid, invalid_val);
     CHECK_DEFAULT(expect_r_list(in, valid), valid, invalid_val);
     return GEMMConfigReshapedOnlyRHS{m0, n0, k0, h0, ir, tr, ex};
 }
References bool_val(), CHECK_DEFAULT, expect_l_list(), expect_r_list(), and uint_val().
Referenced by heuristic_tree().
gemm_type()
GEMMType arm_compute::mlgo::parser::gemm_type (TokenStream & in, bool & valid)
Definition at line 560 of file MLGOParser.cpp.
 {
     LOG_TOKEN_POS(in, pos);
     if (accept_text(in, "native"))
     {
         return GEMMType::NATIVE;
     }
     else if (accept_text(in, "reshaped-only-rhs"))
     {
         return GEMMType::RESHAPED_ONLY_RHS;
     }
     else if (accept_text(in, "reshaped"))
     {
         return GEMMType::RESHAPED;
     }
     else
     {
         FAIL_WITH_MSG_DEFAULT(valid, GEMMType::RESHAPED_ONLY_RHS, pos, "Expect gemm type");
     }
 }
References accept_text(), FAIL_WITH_MSG_DEFAULT, and LOG_TOKEN_POS.
Referenced by heuristic_tree(), arm_compute::operator<<(), arm_compute::cl_gemm::auto_heuristics::select_mlgo_gemm_kernel(), and arm_compute::to_string().
gemm_version()
void arm_compute::mlgo::parser::gemm_version (TokenStream & in, bool & valid)
Definition at line 446 of file MLGOParser.cpp.
 {
     CHECK(expect_text(in, "gemm-version", valid), valid);
     CHECK(expect_l_list(in, valid), valid);
     CHECK(uint_val(in, valid), valid);
     CHECK(uint_val(in, valid), valid);
     CHECK(uint_val(in, valid), valid);
     CHECK(expect_r_list(in, valid), valid);
 }
References CHECK, expect_l_list(), expect_r_list(), expect_text(), and uint_val().
Referenced by header().
gpu_behavior()
void arm_compute::mlgo::parser::gpu_behavior (TokenStream & in, bool & valid)
Definition at line 641 of file MLGOParser.cpp.
 {
     LOG_TOKEN_POS(in, pos);
     if (accept_text(in, "static"))
     {
         ;
     }
     else if (accept_text(in, "dynamic"))
     {
         ;
     }
     else
     {
         FAIL_WITH_MSG(valid, pos, "Expect ip type");
     }
 }
References accept_text(), FAIL_WITH_MSG, and LOG_TOKEN_POS.
Referenced by heuristics_table_entry().
gpu_priority()
void arm_compute::mlgo::parser::gpu_priority (TokenStream & in, bool & valid)
Definition at line 624 of file MLGOParser.cpp.
 {
     LOG_TOKEN_POS(in, pos);
     if (accept_text(in, "best-performance"))
     {
         ;
     }
     else if (accept_text(in, "best-memory-usage"))
     {
         ;
     }
     else
     {
         FAIL_WITH_MSG(valid, pos, "Expect gpu priority");
     }
 }
References accept_text(), FAIL_WITH_MSG, and LOG_TOKEN_POS.
Referenced by heuristics_table_entry().
header()
void arm_compute::mlgo::parser::header (TokenStream & in, bool & valid)
Definition at line 474 of file MLGOParser.cpp.
 {
     CHECK(expect_text(in, "<header>", valid), valid);
     CHECK(gemm_version(in, valid), valid);
     CHECK(ip_type(in, valid), valid);
     CHECK(expect_text(in, "</header>", valid), valid);
 }
References CHECK, expect_text(), gemm_version(), and ip_type().
Referenced by mlgo(), NPYLoader::open(), arm_compute::utils::parse_npy_header(), arm_compute::utils::save_to_npy(), and arm_compute::test::detail::validate_npy_header().
heuristic_tree()
void arm_compute::mlgo::parser::heuristic_tree (TokenStream & in, MLGOHeuristics & h, bool & valid)
Definition at line 709 of file MLGOParser.cpp.
 {
     CHECK(expect_text(in, "<heuristic", valid), valid);
     const auto tree_id = CHECK(uint_val(in, valid), valid);
     CHECK(expect_text(in, ">", valid), valid);
     HeuristicTree *t                     = nullptr;
     std::tie(valid, t)                   = CHECK(h.get_heuristic_tree(tree_id), valid);
     const HeuristicType t_heuristic_type = std::get<0>(t->index());
     while (!accept_text(in, "</heuristic>"))
     {
         LOG_TOKEN_POS(in, pos);
         if (accept_text(in, "b"))
         {
             // Branch node
             const auto id   = CHECK(uint_val(in, valid), valid);
             const auto cond = CHECK(condition(in, valid), valid);
             const auto t_id = CHECK(uint_val(in, valid), valid);
             const auto f_id = CHECK(uint_val(in, valid), valid);
             valid           = CHECK(t->add_branch(id, cond, t_id, f_id), valid);
         }
         else if (accept_text(in, "l"))
         {
             // Leaf node
             const auto id = CHECK(uint_val(in, valid), valid);
             // NOTE: Heuristic type within each tree appears to be redundant (same information can be obtained from the
             // heuristic table). For now it remains as a step for validation.
             LOG_TOKEN_POS(in, pos);
             CHECK(expect_heuristic_type(in, t_heuristic_type, valid), valid);
             switch (t_heuristic_type)
             {
                 case HeuristicType::GEMM_Type:
                 {
                     const auto g_type = CHECK(gemm_type(in, valid), valid);
                     valid             = CHECK(t->add_leaf(id, g_type), valid);
                     break;
                 }
                 case HeuristicType::GEMM_Config_Native:
                 {
                     const auto g_c = CHECK(gemm_config_native(in, valid), valid);
                     valid          = CHECK(t->add_leaf(id, g_c), valid);
                     break;
                 }
                 case HeuristicType::GEMM_Config_Reshaped_Only_RHS:
                 {
                     const auto g_c = CHECK(gemm_config_reshaped_only_rhs(in, valid), valid);
                     valid          = CHECK(t->add_leaf(id, g_c), valid);
                     break;
                 }
                 case HeuristicType::GEMM_Config_Reshaped:
                 {
                     const auto g_c = CHECK(gemm_config_reshaped(in, valid), valid);
                     valid          = CHECK(t->add_leaf(id, g_c), valid);
                     break;
                 }
                 default:
                 {
                     FAIL_WITH_MSG(valid, pos, "Unexpected heuristic type");
                 }
             }
         }
         else
         {
             FAIL_WITH_MSG(valid, pos, "Expect tree node type");
         }
     }
     // Perform semantic checks in the middle of parsing so that it can fail fast should there be any invalidities
     valid = CHECK(h.check_heuristic_tree(tree_id), valid);
 }
References accept_text(), CHECK, MLGOHeuristics::check_heuristic_tree(), condition(), expect_heuristic_type(), expect_text(), FAIL_WITH_MSG, arm_compute::mlgo::GEMM_Config_Native, gemm_config_native(), arm_compute::mlgo::GEMM_Config_Reshaped, gemm_config_reshaped(), arm_compute::mlgo::GEMM_Config_Reshaped_Only_RHS, gemm_config_reshaped_only_rhs(), arm_compute::mlgo::GEMM_Type, gemm_type(), MLGOHeuristics::get_heuristic_tree(), LOG_TOKEN_POS, tf_frozen_model_extractor::t, and uint_val().
Referenced by mlgo().
heuristic_type()
HeuristicType arm_compute::mlgo::parser::heuristic_type (TokenStream & in, bool & valid, bool take = true)
Definition at line 524 of file MLGOParser.cpp.
 {
     LOG_TOKEN_POS(in, pos);
     if (accept_text(in, "gemm-type", take))
     {
         return HeuristicType::GEMM_Type;
     }
     else if (accept_text(in, "gemm-config-native", take))
     {
         return HeuristicType::GEMM_Config_Native;
     }
     else if (accept_text(in, "gemm-config-reshaped-only-rhs", take))
     {
         return HeuristicType::GEMM_Config_Reshaped_Only_RHS;
     }
     else if (accept_text(in, "gemm-config-reshaped", take))
     {
         return HeuristicType::GEMM_Config_Reshaped;
     }
     else
     {
         FAIL_WITH_MSG_DEFAULT(valid, HeuristicType::GEMM_Config_Reshaped, pos, "Expect heuristic type");
     }
 }
References accept_text(), FAIL_WITH_MSG_DEFAULT, arm_compute::mlgo::GEMM_Config_Native, arm_compute::mlgo::GEMM_Config_Reshaped, arm_compute::mlgo::GEMM_Config_Reshaped_Only_RHS, arm_compute::mlgo::GEMM_Type, and LOG_TOKEN_POS.
Referenced by expect_heuristic_type(), and heuristics_table_entry().
heuristics_table()
void arm_compute::mlgo::parser::heuristics_table (TokenStream & in, MLGOHeuristics & h, bool & valid)
Definition at line 681 of file MLGOParser.cpp.
 {
     CHECK(expect_text(in, "<heuristics-table>", valid), valid);
     while (!accept_text(in, "</heuristics-table>"))
     {
         CHECK(heuristics_table_entry(in, h, valid), valid);
     }
 }
References accept_text(), CHECK, expect_text(), and heuristics_table_entry().
Referenced by mlgo().
heuristics_table_entry()
void arm_compute::mlgo::parser::heuristics_table_entry (TokenStream & in, MLGOHeuristics & h, bool & valid)
Definition at line 667 of file MLGOParser.cpp.
 {
     const auto id = CHECK(uint_val(in, valid), valid);
     const auto ip = CHECK(text_val(in, valid), valid);
     CHECK(uint_val(in, valid), valid); // Num cores
     const auto dt = CHECK(data_type(in, valid), valid);
     CHECK(gpu_priority(in, valid), valid);
     CHECK(gpu_behavior(in, valid), valid);
     const auto ht = CHECK(heuristic_type(in, valid), valid);
     CHECK(free_vars(in, valid), valid);
     HeuristicTree t(id, ht, ip, dt);
     valid = CHECK(h.add_heuristic_tree(std::move(t)), valid);
 }
References MLGOHeuristics::add_heuristic_tree(), CHECK, data_type(), dt, free_vars(), gpu_behavior(), gpu_priority(), heuristic_type(), tf_frozen_model_extractor::t, text_val(), and uint_val().
Referenced by heuristics_table().
int_val()
int arm_compute::mlgo::parser::int_val (TokenStream & in, bool & valid)
Definition at line 306 of file MLGOParser.cpp.
 {
     LOG_TOKEN_POS(in, pos);
     auto tok = in.take();
     if (tok.type != TokenType::Int)
     {
         FAIL_WITH_MSG_DEFAULT(valid, -1, pos, "Expect int token");
     }
     int val{};
     std::stringstream(tok.value) >> val;
     return val;
 }
References FAIL_WITH_MSG_DEFAULT, Int, LOG_TOKEN_POS, and TokenStream::take().
Referenced by uint_val().
ip_type()
void arm_compute::mlgo::parser::ip_type (TokenStream & in, bool & valid)
Definition at line 456 of file MLGOParser.cpp.
 {
     CHECK(expect_text(in, "ip-type", valid), valid);
     LOG_TOKEN_POS(in, pos);
     if (accept_text(in, "gpu"))
     {
         ;
     }
     else if (accept_text(in, "cpu"))
     {
         ;
     }
     else
     {
         FAIL_WITH_MSG(valid, pos, "Expect ip type");
     }
 }
References accept_text(), CHECK, expect_text(), FAIL_WITH_MSG, and LOG_TOKEN_POS.
Referenced by header().
mlgo()
MLGOHeuristics arm_compute::mlgo::parser::mlgo (TokenStream & in, bool & valid)
Definition at line 778 of file MLGOParser.cpp.
 {
     MLGOHeuristics h;
     CHECK_DEFAULT(header(in, valid), valid, h);
     CHECK_DEFAULT(heuristics_table(in, h, valid), valid, h);
     while (accept_text(in, "<heuristic", false))
     {
         CHECK_DEFAULT(heuristic_tree(in, h, valid), valid, h);
     }
     CHECK_DEFAULT(end(in, valid), valid, h);
     valid = CHECK_DEFAULT(h.check_all(), valid, h);
     return h;
 }
References accept_text(), MLGOHeuristics::check_all(), CHECK_DEFAULT, end(), header(), heuristic_tree(), and heuristics_table().
Referenced by parse_mlgo().
operator<<()
std::ostream & operator<< (std::ostream & os, const CharPosition & pos)
Definition at line 176 of file Utils.cpp.
 {
     os << "(Ln: " << pos.ln << ", Col: " << pos.col << ")";
     return os;
 }
References CharPosition::col, and CharPosition::ln.
parse_mlgo()
std::pair< bool, MLGOHeuristics > parse_mlgo (std::istream & in)
Parse and construct a MLGOHeuristics from input stream.
Parameters
[in] in Input stream
Returns
MLGOHeuristics
Definition at line 792 of file MLGOParser.cpp.
 {
     auto tokens = TokenStream(in);
     bool valid  = true;
     auto h      = mlgo(tokens, valid);
     return std::make_pair(std::move(valid), std::move(h));
 }
References mlgo().
Referenced by MLGOHeuristics::reload_from_stream().
rewind()
void arm_compute::mlgo::parser::rewind (CharPosition & pos)
Definition at line 153 of file MLGOParser.cpp.
 {
     pos.col -= 1;
 }
References CharPosition::col.
text_val()
std::string arm_compute::mlgo::parser::text_val (TokenStream & in, bool & valid)
Definition at line 343 of file MLGOParser.cpp.
 {
     LOG_TOKEN_POS(in, pos);
     auto tok = in.take();
     if (tok.type != TokenType::Text || tok.value.empty())
     {
         FAIL_WITH_MSG_DEFAULT(valid, "", pos, "Expect a non-empty text token");
     }
     return tok.value;
 }
References FAIL_WITH_MSG_DEFAULT, LOG_TOKEN_POS, TokenStream::take(), and Text.
Referenced by condition(), free_vars(), and heuristics_table_entry().
uint_val()
unsigned int arm_compute::mlgo::parser::uint_val (TokenStream & in, bool & valid)
Definition at line 319 of file MLGOParser.cpp.
 {
     LOG_TOKEN_POS(in, pos);
     int val = CHECK_DEFAULT(int_val(in, valid), valid, 0);
     if (val < 0)
     {
         FAIL_WITH_MSG_DEFAULT(valid, 0, pos, "Expect unsigned int token");
     }
     return static_cast<unsigned int>(val);
 }
References CHECK_DEFAULT, FAIL_WITH_MSG_DEFAULT, int_val(), and LOG_TOKEN_POS.
Referenced by gemm_config_native(), gemm_config_reshaped(), gemm_config_reshaped_only_rhs(), gemm_version(), heuristic_tree(), and heuristics_table_entry().