Compute Library: arm_gemm Namespace Reference
arm_gemm Namespace Reference
Namespaces
utils
Data Structures
struct Activation
class barrier
struct ConvolutionParameters
class convolver
struct GemmArgs
class GemmCommon
struct GemmConfig
class GemmHybrid
class GemmHybridIndirect
class GemmHybridQuantized
class GemmHybridQuantizedInline
struct GemmImplementation
struct GemmImplementation< Top, Tret, Nothing >
class GemmInterleaved
class GemvBatched
class GemvPretransposed
class IGemmCommon
struct IndirectInputArg
struct IndirectOutputArg
struct is_sme
struct KernelDescription
class NDCoordinate
NDCoordinate builds upon a range, but specifies a starting position in addition to a size which it inherits from NDRange.
class NDRange
struct Nothing
struct PerformanceParameters
class QuantizeWrapper
struct Requantize32
class StdTransformsFixed
class StdTransformsSME
class StdTransformsSVE
Typedefs
using bfloat16 = arm_compute::bfloat16
template<typename strategy , typename To , typename Tr , typename OutputStage = Nothing>
using GemmHybridIndirectFixedFormat = GemmHybridIndirect< strategy, To, Tr, OutputStage, false, true >
template<typename strategy , typename To , typename Tr , typename OutputStage = Nothing>
using GemmInterleavedNoMerge = GemmInterleaved< strategy, To, Tr, OutputStage, false >
template<typename strategy , typename To , typename Tr , typename OutputStage = Nothing>
using GemmInterleavedFixedFormat = GemmInterleaved< strategy, To, Tr, OutputStage, true, true >
template<typename strategy , typename To , typename Tr >
using GemmInterleavedPretransposedNoMergeQuantizedInline = GemmInterleaved< strategy, To, Tr, Requantize32, false >
template<typename strategy , typename To , typename Tr >
using GemmInterleavedQuantized = GemmInterleaved< strategy, To, Tr, Requantize32 >
template<typename Top , typename Tret >
using UniqueGemmCommon = std::unique_ptr< GemmCommon< Top, Tret > >
using ndrange_t = NDRange< ndrange_max >
using ndcoord_t = NDCoordinate< ndrange_max >
Enumerations
enum KernelWeightFormat {
NON_FIXED = 0, VL128_BL16 = 0x1200, VL128_BL32 = 0x1400, VL128_BL32_BF16 = 0x1410,
VL128_BL64 = 0x1800, VL256_BL64 = 0x2800, VL256_BL64_BF16 = 0x2810, VL1VL_BL16 = 0x1201,
VL1VL_BL32 = 0x1401, VL1VL_BL32_BF16 = 0x1411, VL1VL_BL64 = 0x1801, VL2VL_BL64 = 0x2801,
VL2VL_BL64_BF16 = 0x2811
}
enum VLType { None, SVE, SME, SME2 }
enum GemmMethod {
DEFAULT, GEMV_BATCHED, GEMV_PRETRANSPOSED, GEMV_NATIVE_TRANSPOSED,
GEMM_NATIVE, GEMM_HYBRID, GEMM_INTERLEAVED, GEMM_INTERLEAVED_2D,
QUANTIZE_WRAPPER, QUANTIZE_WRAPPER_2D, GEMM_HYBRID_QUANTIZED
}
enum WeightFormat {
UNSPECIFIED = 0x1, ANY = 0x2, OHWI = 0x100100, OHWIo2 = 0x100200,
OHWIo4 = 0x100400, OHWIo8 = 0x100800, OHWIo16 = 0x101000, OHWIo32 = 0x102000,
OHWIo64 = 0x104000, OHWIo128 = 0x108000, OHWIo4i2 = 0x200400, OHWIo4i2_bf16 = 0x200410,
OHWIo8i2 = 0x200800, OHWIo8i2_bf16 = 0x200810, OHWIo16i2 = 0x201000, OHWIo16i2_bf16 = 0x201010,
OHWIo32i2 = 0x202000, OHWIo32i2_bf16 = 0x202010, OHWIo64i2 = 0x204000, OHWIo64i2_bf16 = 0x204010,
OHWIo4i4 = 0x400400, OHWIo4i4_bf16 = 0x400410, OHWIo8i4 = 0x400800, OHWIo8i4_bf16 = 0x400810,
OHWIo16i4 = 0x401000, OHWIo16i4_bf16 = 0x401010, OHWIo32i4 = 0x402000, OHWIo32i4_bf16 = 0x402010,
OHWIo64i4 = 0x404000, OHWIo64i4_bf16 = 0x404010, OHWIo2i8 = 0x800200, OHWIo4i8 = 0x800400,
OHWIo8i8 = 0x800800, OHWIo16i8 = 0x801000, OHWIo32i8 = 0x802000, OHWIo64i8 = 0x804000
}
Functions
template<typename T >
void bias_adder (T *out, unsigned int stride, const T *bias, unsigned int rows, unsigned int cols)
template<bool DoBias, typename T >
void activator (T *out, unsigned int stride, const T *bias, Activation act, unsigned int rows, unsigned int cols)
template<>
const GemmImplementation< bfloat16, float > * gemm_implementation_list< bfloat16, float > ()
template UniqueGemmCommon< bfloat16, float > gemm< bfloat16, float, Nothing > (const GemmArgs &args, const Nothing &)
template bool has_opt_gemm< bfloat16, float, Nothing > (WeightFormat &weight_format, const GemmArgs &args, const Nothing &)
template KernelDescription get_gemm_method< bfloat16, float, Nothing > (const GemmArgs &args, const Nothing &)
template std::vector< KernelDescription > get_compatible_kernels< bfloat16, float, Nothing > (const GemmArgs &args, const Nothing &)
template<>
const GemmImplementation< float, float > * gemm_implementation_list< float, float > ()
template UniqueGemmCommon< float, float > gemm< float, float, Nothing > (const GemmArgs &args, const Nothing &)
template bool has_opt_gemm< float, float, Nothing > (WeightFormat &weight_format, const GemmArgs &args, const Nothing &)
template KernelDescription get_gemm_method< float, float, Nothing > (const GemmArgs &args, const Nothing &)
template std::vector< KernelDescription > get_compatible_kernels< float, float, Nothing > (const GemmArgs &args, const Nothing &)
template<typename Top , typename Tret , class OutputStage = Nothing>
const GemmImplementation< Top, Tret, OutputStage > * gemm_implementation_list ()
template<typename Top , typename Tret , class OutputStage >
bool find_implementation (const GemmArgs &args, const OutputStage &os, const GemmImplementation< Top, Tret, OutputStage > *&impl)
template<typename Top , typename Tret , class OutputStage >
std::vector< KernelDescription > get_compatible_kernels (const GemmArgs &args, const OutputStage &os)
template<typename Top , typename Tret , class OutputStage >
bool has_opt_gemm (WeightFormat &wf, const GemmArgs &args, const OutputStage &os)
template<typename Top , typename Tret , class OutputStage >
UniqueGemmCommon< Top, Tret > gemm (const GemmArgs &args, const OutputStage &os)
template<typename Top , typename Tret , class OutputStage >
KernelDescription get_gemm_method (const GemmArgs &args, const OutputStage &os)
template<unsigned int height_vectors, unsigned int block, VLType vlt, bool integrate_sums, typename TIn , typename TOut >
void interleave_block (TOut *&out, const TIn *const *in, size_t width, size_t height, size_t row_offset, bool first)
template<unsigned int height_vectors, unsigned int block, VLType vlt, typename TOut >
void FixupRowSums (TOut *&out, const int32_t row_sum_multiplier)
template<unsigned int height_vectors, unsigned int block, VLType vlt, typename TIn , typename TOut >
void IndirectInterleave (TOut *out, const TIn *const *const *ptr, unsigned int stringlen, unsigned int rounded_stringlen, const unsigned int y0, const unsigned int ymax, const unsigned int k0, const unsigned int kmax, bool integrate_sums, const int32_t row_sum_multiplier)
template<unsigned int height_vectors, unsigned int block, VLType vlt, typename TIn , typename TOut >
void ConvolutionInterleave (TOut *out, const TIn *in, size_t in_stride, const convolver< TIn > &conv, const unsigned int rounded_stringlen, const unsigned int y0, const unsigned int ymax, const unsigned int k0, const unsigned int kmax, bool integrate_sums, const int32_t row_sum_multiplier)
template<unsigned int height_vectors, unsigned int block, VLType vlt, typename TIn , typename TOut >
void Interleave (TOut *out, const TIn *in, size_t in_stride, const unsigned int y0, const unsigned int ymax, const unsigned int k0, const unsigned int kmax, bool integrate_sums, const int32_t row_sum_multiplier)
WeightFormat get_weight_format (const KernelWeightFormat, size_t)
template<unsigned int twidth, unsigned int height, bool sve = false, typename Tin , typename Tout >
void MergeResults (Tout *out, const Tin *in, int ldc, int y0, int ymax, int x0, int xmax, const Tout *bias, Activation act, bool append)
template<typename Tin , typename Tout >
void requantize_block_32 (const Requantize32 &qp, unsigned int width, unsigned int height, const Tin *input, unsigned int in_stride, Tout *output, unsigned int out_stride, const int32_t *row_bias, const int32_t *col_bias, unsigned int start_col)
template<typename T >
void compute_row_sums (const Requantize32 &qp, unsigned int width, unsigned int height, const T *input, unsigned int in_stride, int32_t *row_bias)
template<typename T >
void compute_col_sums (const Requantize32 &qp, unsigned int width, unsigned int height, const T *input, unsigned int in_stride, int32_t *col_bias, unsigned int depth, unsigned int multi, unsigned int first_col)
template<typename T >
void row_sums_indirect (size_t num_strings, const unsigned int *string_lengths, IndirectInputArg< T > A_arg, size_t M, int32_t *output_ptr, const Requantize32 *qp)
template<unsigned int IntBy, unsigned int BlockBy, bool Transposed, VLType vlt = VLType::None, typename TOut , typename TIn >
void Transform (TOut *out, const TIn *const in, const int stride, const int k0, const int kmax, const int x0, const int xmax)
template<typename T >
std::string get_type_name ()
template<typename T >
T iceildiv (const T a, const T b)
template<typename T >
T roundup (const T a, const T b)
bool quant_no_left_shift (const Requantize32 &qp)
bool quant_hybrid_symmetric (const Requantize32 &qp)
bool quant_hybrid_asymmetric (const Requantize32 &qp)
arm_compute::Window to_window (const ndrange_t &ndr)
arm_compute::Window to_window (const ndcoord_t &ndc)
ndrange_t to_ndrange (const arm_compute::Window &win)
Convert an arm_compute::Window to an arm_gemm::NDRange of the same max dimensions.
ndcoord_t to_ndcoord (const arm_compute::Window &win)
Convert an arm_compute::Window to an arm_gemm::NDCoord of the same max dimensions.
Variables
std::mutex report_mutex
constexpr std::size_t ndrange_max = arm_compute::Dimensions<unsigned int>::num_max_dimensions
Typedef Documentation
bfloat16
using bfloat16 = arm_compute::bfloat16
Definition at line 30 of file bfloat.hpp.
GemmHybridIndirectFixedFormat
using GemmHybridIndirectFixedFormat = GemmHybridIndirect<strategy, To, Tr, OutputStage, false, true>
Definition at line 832 of file gemm_hybrid_indirect.hpp.
GemmInterleavedFixedFormat
using GemmInterleavedFixedFormat = GemmInterleaved<strategy, To, Tr, OutputStage, true, true>
Definition at line 1235 of file gemm_interleaved.hpp.
GemmInterleavedNoMerge
using GemmInterleavedNoMerge = GemmInterleaved<strategy, To, Tr, OutputStage, false>
Definition at line 1232 of file gemm_interleaved.hpp.
GemmInterleavedPretransposedNoMergeQuantizedInline
using GemmInterleavedPretransposedNoMergeQuantizedInline = GemmInterleaved<strategy, To, Tr, Requantize32, false>
Definition at line 1238 of file gemm_interleaved.hpp.
GemmInterleavedQuantized
using GemmInterleavedQuantized = GemmInterleaved<strategy, To, Tr, Requantize32>
Definition at line 1241 of file gemm_interleaved.hpp.
ndcoord_t
typedef NDCoordinate< 6 > ndcoord_t
Definition at line 43 of file arm_gemm_compute_iface.hpp.
ndrange_t
typedef NDRange< 6 > ndrange_t
Definition at line 42 of file arm_gemm_compute_iface.hpp.
UniqueGemmCommon
using UniqueGemmCommon = std::unique_ptr<GemmCommon<Top, Tret> >
Definition at line 261 of file arm_gemm.hpp.
Enumeration Type Documentation
GemmMethod
enum GemmMethod strong
Enumerator
DEFAULT
GEMV_BATCHED
GEMV_PRETRANSPOSED
GEMV_NATIVE_TRANSPOSED
GEMM_NATIVE
GEMM_HYBRID
GEMM_INTERLEAVED
GEMM_INTERLEAVED_2D
QUANTIZE_WRAPPER
QUANTIZE_WRAPPER_2D
GEMM_HYBRID_QUANTIZED
Definition at line 34 of file arm_gemm.hpp.
 {
     DEFAULT,
     GEMV_BATCHED,
     GEMV_PRETRANSPOSED,
     GEMV_NATIVE_TRANSPOSED,
     GEMM_NATIVE,
     GEMM_HYBRID,
     GEMM_INTERLEAVED,
     GEMM_INTERLEAVED_2D,
     QUANTIZE_WRAPPER,
     QUANTIZE_WRAPPER_2D,
     GEMM_HYBRID_QUANTIZED
 };
KernelWeightFormat
enum KernelWeightFormat strong
Enumerator
NON_FIXED
VL128_BL16
VL128_BL32
VL128_BL32_BF16
VL128_BL64
VL256_BL64
VL256_BL64_BF16
VL1VL_BL16
VL1VL_BL32
VL1VL_BL32_BF16
VL1VL_BL64
VL2VL_BL64
VL2VL_BL64_BF16
Definition at line 42 of file kernel_weight_format.hpp.
{
     NON_FIXED        = 0,
     VL128_BL16       = 0x1200,
     VL128_BL32       = 0x1400,
     VL128_BL32_BF16  = 0x1410,
     VL128_BL64       = 0x1800,
     VL256_BL64       = 0x2800,
     VL256_BL64_BF16  = 0x2810,
     VL1VL_BL16       = 0x1201,
     VL1VL_BL32       = 0x1401,
     VL1VL_BL32_BF16  = 0x1411,
     VL1VL_BL64       = 0x1801,
     VL2VL_BL64       = 0x2801,
     VL2VL_BL64_BF16  = 0x2811
 };
VLType
enum VLType strong
Enumerator
None
SVE
SME
SME2
Definition at line 80 of file utils.hpp.
                   {
     None,
     SVE,
     SME,
     SME2
 };
WeightFormat
enum WeightFormat strong
Enumerator
UNSPECIFIED
ANY
OHWI
OHWIo2
OHWIo4
OHWIo8
OHWIo16
OHWIo32
OHWIo64
OHWIo128
OHWIo4i2
OHWIo4i2_bf16
OHWIo8i2
OHWIo8i2_bf16
OHWIo16i2
OHWIo16i2_bf16
OHWIo32i2
OHWIo32i2_bf16
OHWIo64i2
OHWIo64i2_bf16
OHWIo4i4
OHWIo4i4_bf16
OHWIo8i4
OHWIo8i4_bf16
OHWIo16i4
OHWIo16i4_bf16
OHWIo32i4
OHWIo32i4_bf16
OHWIo64i4
OHWIo64i4_bf16
OHWIo2i8
OHWIo4i8
OHWIo8i8
OHWIo16i8
OHWIo32i8
OHWIo64i8
Definition at line 49 of file arm_gemm.hpp.
 {
     UNSPECIFIED    = 0x1,
     ANY            = 0x2,
     OHWI           = 0x100100,
     OHWIo2         = 0x100200,
     OHWIo4         = 0x100400,
     OHWIo8         = 0x100800,
     OHWIo16        = 0x101000,
     OHWIo32        = 0x102000,
     OHWIo64        = 0x104000,
     OHWIo128       = 0x108000,
     OHWIo4i2       = 0x200400,
     OHWIo4i2_bf16  = 0x200410,
     OHWIo8i2       = 0x200800,
     OHWIo8i2_bf16  = 0x200810,
     OHWIo16i2      = 0x201000,
     OHWIo16i2_bf16 = 0x201010,
     OHWIo32i2      = 0x202000,
     OHWIo32i2_bf16 = 0x202010,
     OHWIo64i2      = 0x204000,
     OHWIo64i2_bf16 = 0x204010,
     OHWIo4i4       = 0x400400,
     OHWIo4i4_bf16  = 0x400410,
     OHWIo8i4       = 0x400800,
     OHWIo8i4_bf16  = 0x400810,
     OHWIo16i4      = 0x401000,
     OHWIo16i4_bf16 = 0x401010,
     OHWIo32i4      = 0x402000,
     OHWIo32i4_bf16 = 0x402010,
     OHWIo64i4      = 0x404000,
     OHWIo64i4_bf16 = 0x404010,
     OHWIo2i8       = 0x800200,
     OHWIo4i8       = 0x800400,
     OHWIo8i8       = 0x800800,
     OHWIo16i8      = 0x801000,
     OHWIo32i8      = 0x802000,
     OHWIo64i8      = 0x804000
 };
Function Documentation
activator()
void arm_gemm::activator (T * out, unsigned int stride, const T * bias, Activation act, unsigned int rows, unsigned int cols) inline
Definition at line 40 of file bias_adder.hpp.
{
     if (act.type == Activation::Type::None) {
         if (DoBias) {
             bias_adder(out, stride, bias, rows, cols);
         }
         return;
     }
     if (act.type == Activation::Type::ReLU) {
         for (unsigned int row=0; row<rows; row++) {
             for (unsigned int col=0; col<cols; col++) {
                 T &v = out[row * stride + col];
                 if (DoBias) {
                     v += bias[col];
                 }
                 v = std::max(static_cast<T>(0), v);
             }
         }
     }
     if (act.type == Activation::Type::BoundedReLU) {
         const T max = static_cast<T>(act.param1);
         for (unsigned int row=0; row<rows; row++) {
             for (unsigned int col=0; col<cols; col++) {
                 T &v = out[row * stride + col];
                 if (DoBias) {
                     v += bias[col];
                 }
                 v = std::max(static_cast<T>(0), std::min(v, max));
             }
         }
     }
 }
References bias, bias_adder(), Activation::BoundedReLU, caffe_mnist_image_extractor::cols, Activation::None, Activation::param1, Activation::ReLU, caffe_mnist_image_extractor::rows, and Activation::type.
bias_adder()
void arm_gemm::bias_adder (T * out, unsigned int stride, const T * bias, unsigned int rows, unsigned int cols) inline
Definition at line 31 of file bias_adder.hpp.
{
     for (unsigned int row=0; row<rows; row++) {
         for (unsigned int col=0; col<cols; col++) {
             out[row * stride + col] += bias[col];
         }
     }
 }
References bias, caffe_mnist_image_extractor::cols, and caffe_mnist_image_extractor::rows.
Referenced by activator(), and GemmHybrid< strategy, To, Tr >::execute().
compute_col_sums()
void arm_gemm::compute_col_sums (const Requantize32 & qp, unsigned int width, unsigned int height, const T * input, unsigned int in_stride, int32_t * col_bias, unsigned int depth, unsigned int multi, unsigned int first_col)
Referenced by GemvPretransposed< strategy, To, Tr, OutputStage >::requantize_bias(), GemmHybridQuantizedInline< strategy, To, Tr >::requantize_bias(), GemmHybridQuantized< strategy, To, Tr >::requantize_bias(), GemmHybridIndirect< strategy, To, Tr, OutputStage, SeparateQuantize, FixedFormat >::requantize_bias(), and GemmInterleaved< strategy, To, Tr, OutputStage, MergeStep, FixedFormat, ForceThreadColumns, ForceFloatAccumulate >::requantize_bias().
compute_row_sums()
void arm_gemm::compute_row_sums (const Requantize32 & qp, unsigned int width, unsigned int height, const T * input, unsigned int in_stride, int32_t * row_bias)
Referenced by GemmHybridQuantized< strategy, To, Tr >::execute().
ConvolutionInterleave()
void ConvolutionInterleave (TOut * out, const TIn * in, size_t in_stride, const convolver< TIn > & conv, const unsigned int rounded_stringlen, const unsigned int y0, const unsigned int ymax, const unsigned int k0, const unsigned int kmax, bool integrate_sums, const int32_t row_sum_multiplier)
Definition at line 226 of file interleave_indirect.cpp.
{
     const unsigned int height = height_vectors * (vlt == VLType::SVE ? get_vector_length<TOut>() / block : 1);
     auto conv_cols = conv.process_columns(in, in_stride, k0, kmax, rounded_stringlen);
     // Use alloca here as a std::vector can be expensive in highly threaded scenarios.
     const TIn **row_ptrs = reinterpret_cast<const TIn **>(alloca(height * sizeof(const TIn *)));
     for (unsigned int ybase = y0; ybase < ymax; ybase += height) {
         // How many of the rows are active - the rest will get padded in interleave_block.
         unsigned int active_height   = std::min(ymax - ybase, height);
         bool first = true;
         auto conv_rows = conv_cols.process_rows(ybase, active_height);
         while (!conv_rows.finished()) {
             unsigned int width, offset;
             // Get next set of parameters
             std::tie(width, offset) = conv_rows.next_block(row_ptrs);
             // Perform the interleave
             if (std::is_integral<TOut>::value && integrate_sums && row_sum_multiplier) {
                 interleave_block<height_vectors, block, vlt, true>(out, row_ptrs, width, active_height, offset, first);
             } else {
                 interleave_block<height_vectors, block, vlt, false>(out, row_ptrs, width, active_height, offset, first);
             }
             first=false;
         }
         if (std::is_integral<TOut>::value && integrate_sums) {
             FixupRowSums<height_vectors, block, vlt>(out, row_sum_multiplier);
         }
     }
 }
References offset(), convolver< T >::process_columns(), and SVE.
find_implementation()
bool arm_gemm::find_implementation (const GemmArgs & args, const OutputStage & os, const GemmImplementation< Top, Tret, OutputStage > *& impl)
Definition at line 238 of file gemm_implementation.hpp.
{
     auto gemms = gemm_implementation_list<Top, Tret, OutputStage>();
     const GemmConfig *cfg = args._cfg;
     const GemmImplementation<Top, Tret, OutputStage> *saved_impl = nullptr;
     uint64_t best_estimate = 0;
     for (const GemmImplementation<Top, Tret, OutputStage> *i = gemms; i->method != GemmMethod::DEFAULT; i++) {
         /* Skip if this implementation doesn't support these args. */
         if (!i->do_is_supported(args, os)) {
             continue;
         }
         /* Skip if a specific method is requested and this is a different one. */
         if (cfg && cfg->method != GemmMethod::DEFAULT && i->method != cfg->method) {
             continue;
         }
         /* Skip if a filter is to be applied and it doesn't match. */
         if (cfg && cfg->filter != "" && !strstr(i->name, cfg->filter.c_str())) {
             continue;
         }
         /* Test the cycle estimate */
         uint64_t estimate = i->do_cycle_estimate(args, os);
         /* Short circuit - if the estimate is zero, return this one immediately. */
         if (estimate==0) {
             impl=i;
             return true;
         }
         /* Otherwise, remember this is our best so far if we don't yet have
          * a valid candidate, or we beat the estimate.  */
         if ((saved_impl == nullptr) || (estimate < best_estimate)) {
             saved_impl = i;
             best_estimate = estimate;
         }
     }
     /* Return whichever method gave the best estimate. */
     if (saved_impl != nullptr) {
         impl = saved_impl;
         return true;
     }
     return false;
 }
References GemmTuner::args, DEFAULT, GemmImplementation< Top, Tret, OutputStage >::do_cycle_estimate(), GemmConfig::filter, GemmImplementation< Top, Tret, OutputStage >::method, and GemmConfig::method.
Referenced by get_compatible_kernels().
FixupRowSums()
void arm_gemm::FixupRowSums (TOut *& out, const int32_t row_sum_multiplier) inline
Definition at line 125 of file interleave_indirect.cpp.
{
     const unsigned int height = height_vectors * (vlt == VLType::SVE ? get_vector_length<TOut>() / block : 1);
     // If we are integrating row sums, we need to do some fix up, depending on whether the multiplier is non-zero or not.
     if (row_sum_multiplier) {
         // Non-zero: interleave_block<>() will have done the sums, so 'out' will point to the start of the
         // next block (post sums).
         // We need to go back and apply the multiplier to the computed sums.  We don't need to change 'out'.
         int32_t *out_int32 = reinterpret_cast<int32_t *>(out);
         out_int32 -= height;
         for (unsigned int i=0; i<height; i++) {
             out_int32[i] *= row_sum_multiplier;
         }
     } else {
         // Zero: interleave_block<>() will *not* have done the sums, so 'out' will point to the start of the
         // sum block.  We need to insert the (zero) sums, and advance 'out'.
         int32_t *out_int32 = reinterpret_cast<int32_t *>(out);
         for (unsigned int i=0; i<height; i++) {
             out_int32[i] = 0;
         }
         out_int32 += height;
         out = reinterpret_cast<TOut *>(out_int32);
     }
 }
References SVE.
gemm()
UniqueGemmCommon< Top, Tret > gemm (const GemmArgs & args, const OutputStage & os)
Definition at line 320 of file gemm_implementation.hpp.
{
     const GemmImplementation<Top, Tret, OutputStage> *impl;
     if (find_implementation<Top, Tret, OutputStage>(args, os, impl)) {
         return UniqueGemmCommon<Top, Tret>(impl->do_instantiate(args, os));
     }
     return UniqueGemmCommon<Top, Tret>(nullptr);
 }
References GemmTuner::args, and GemmImplementation< Top, Tret, OutputStage >::do_instantiate().
Referenced by arm_compute::test::validation::TEST_CASE().
gemm< bfloat16, float, Nothing >()
template UniqueGemmCommon<bfloat16, float> arm_gemm::gemm< bfloat16, float, Nothing > (const GemmArgs & args, const Nothing &)
gemm< float, float, Nothing >()
template UniqueGemmCommon<float, float> arm_gemm::gemm< float, float, Nothing > (const GemmArgs & args, const Nothing &)
gemm_implementation_list()
const GemmImplementation<Top, Tret, OutputStage>* arm_gemm::gemm_implementation_list ()
gemm_implementation_list< bfloat16, float >()
const GemmImplementation<bfloat16, float>* arm_gemm::gemm_implementation_list< bfloat16, float > ()
Definition at line 253 of file gemm_bf16.cpp.
{
     return gemm_bf16_methods;
 }
gemm_implementation_list< float, float >()
const GemmImplementation<float, float>* arm_gemm::gemm_implementation_list< float, float > ()
Definition at line 393 of file gemm_fp32.cpp.
{
     return gemm_fp32_methods;
 }
get_compatible_kernels()
std::vector< KernelDescription > get_compatible_kernels (const GemmArgs & args, const OutputStage & os)
Definition at line 288 of file gemm_implementation.hpp.
{
     std::vector<KernelDescription> res;
     /* Find out what the default implementation in so we can set the flag accordingly later. */
     const GemmImplementation<Top, Tret, OutputStage> *default_impl;
     find_implementation(args, os, default_impl);
     auto gemms = gemm_implementation_list<Top, Tret, OutputStage>();
     for (const GemmImplementation<Top, Tret, OutputStage> *i = gemms; i->method != GemmMethod::DEFAULT; i++) {
         /* Check that this implementation supports the presented problem. */
         if (!i->do_is_supported(args, os)) {
             continue;
         }
         res.push_back(KernelDescription(i->method, i->name, i==default_impl, i->do_cycle_estimate(args, os)));
     }
     return res;
 }
References GemmTuner::args, DEFAULT, GemmImplementation< Top, Tret, OutputStage >::do_cycle_estimate(), find_implementation(), and GemmImplementation< Top, Tret, OutputStage >::method.
get_compatible_kernels< bfloat16, float, Nothing >()
template std::vector<KernelDescription> arm_gemm::get_compatible_kernels< bfloat16, float, Nothing > (const GemmArgs & args, const Nothing &)
get_compatible_kernels< float, float, Nothing >()
template std::vector<KernelDescription> arm_gemm::get_compatible_kernels< float, float, Nothing > (const GemmArgs & args, const Nothing &)
get_gemm_method()
KernelDescription get_gemm_method (const GemmArgs & args, const OutputStage & os)
Definition at line 331 of file gemm_implementation.hpp.
{
     const GemmImplementation<Top, Tret, OutputStage> *impl;
     if (find_implementation<Top, Tret>(args, os, impl)) {
         return KernelDescription(impl->method, impl->name);
     }
     /* This shouldn't happen - there should always be at least one valid implementation. */
     return KernelDescription();
 }
References GemmTuner::args, GemmImplementation< Top, Tret, OutputStage >::method, and GemmImplementation< Top, Tret, OutputStage >::name.
get_gemm_method< bfloat16, float, Nothing >()
template KernelDescription arm_gemm::get_gemm_method< bfloat16, float, Nothing > (const GemmArgs & args, const Nothing &)
get_gemm_method< float, float, Nothing >()
template KernelDescription arm_gemm::get_gemm_method< float, float, Nothing > (const GemmArgs & args, const Nothing &)
get_type_name()
std::string arm_gemm::get_type_name ()
Definition at line 42 of file utils.hpp.
{
 #ifdef __GNUC__
     std::string s = __PRETTY_FUNCTION__;
     auto start = s.find("cls_");
     if (start==std::string::npos) {
         return "(unknown)";
     }
     for(size_t x = start+4; x<s.size(); x++) {
         if (s[x] == ';' || s[x] == ']') {
             return s.substr(start+4, x-(start+4));
         }
     }
     return "(unknown)";
 #else
     return "(unsupported)";
 #endif
 }
get_weight_format()
WeightFormat get_weight_format (const KernelWeightFormat kwf, size_t element_size)
Definition at line 40 of file misc.cpp.
{
     if (kwf==KernelWeightFormat::NON_FIXED) {
         return WeightFormat::UNSPECIFIED;
     }
     uint32_t kwf_i = static_cast<uint32_t>(kwf);
     uint32_t wf_i = 0;
     const auto block_bytes = (kwf_i >> 8) & 0xf;
     const auto vector_count = (kwf_i >> 12) & 0xf;
     uint32_t vector_bytes;
     // For fast mode BF16 kernels set the appropriate bit and override element size to 2.
     if (kwf_i & 0x10) {
         element_size = 2;
         wf_i |= 0x10;
     }
 #ifdef ARM_COMPUTE_ENABLE_SVE
     // Get total bytes in vector output
     if (kwf_i & 0x1) {
         vector_bytes = vector_count * get_vector_length<uint8_t>();
     } else {
 #else
     if (1) {
 #endif
         vector_bytes = vector_count * 16;
     }
     auto input_blocking = block_bytes / element_size;
     auto output_blocking = vector_bytes / block_bytes;
     wf_i |= (input_blocking << 20);
     wf_i |= (output_blocking << 8);
     return static_cast<WeightFormat>(wf_i);
 }
References NON_FIXED, and UNSPECIFIED.
Referenced by GemmImplementation< Top, Tret, OutputStage >::do_is_supported(), GemmImplementation< Top, Tret, Nothing >::do_is_supported(), GemmHybridIndirect< strategy, To, Tr, OutputStage, SeparateQuantize, FixedFormat >::get_config(), and GemmInterleaved< strategy, To, Tr, OutputStage, MergeStep, FixedFormat, ForceThreadColumns, ForceFloatAccumulate >::get_config().
has_opt_gemm()
bool has_opt_gemm (WeightFormat & wf, const GemmArgs & args, const OutputStage & os)
Definition at line 311 of file gemm_implementation.hpp.
{
     const GemmImplementation<Top, Tret, OutputStage> *impl;
     const bool success =  find_implementation<Top, Tret, OutputStage>(args, os, impl);
     if (success)
       wf = UniqueGemmCommon<Top, Tret>(impl->do_instantiate(args, os))->get_config().weight_format;
     return success;
 }
References GemmTuner::args, and GemmImplementation< Top, Tret, OutputStage >::do_instantiate().
has_opt_gemm< bfloat16, float, Nothing >()
template bool arm_gemm::has_opt_gemm< bfloat16, float, Nothing > (WeightFormat & weight_format, const GemmArgs & args, const Nothing &)
has_opt_gemm< float, float, Nothing >()
template bool arm_gemm::has_opt_gemm< float, float, Nothing > (WeightFormat & weight_format, const GemmArgs & args, const Nothing &)
iceildiv()
T arm_gemm::iceildiv (const T a, const T b) inline
Definition at line 65 of file utils.hpp.
{
     return (a + b - 1) / b;
 }
References arm_compute::test::validation::b.
Referenced by GemmInterleaved< strategy, To, Tr, OutputStage, MergeStep, FixedFormat, ForceThreadColumns, ForceFloatAccumulate >::estimate_cycles(), GemvPretransposed< strategy, To, Tr, OutputStage >::execute(), GemmHybridIndirect< strategy, To, Tr, OutputStage, SeparateQuantize, FixedFormat >::get_B_pretranspose_window_size(), GemmInterleaved< strategy, To, Tr, OutputStage, MergeStep, FixedFormat, ForceThreadColumns, ForceFloatAccumulate >::get_B_pretranspose_window_size(), arm_conv::depthwise::get_reduced_view_for_dilation(), arm_conv::depthwise::interleaves::quantized::get_storage_size(), arm_conv::depthwise::interleaves::get_storage_size_generic(), GemvPretransposed< strategy, To, Tr, OutputStage >::get_window_size(), GemmInterleaved< strategy, To, Tr, OutputStage, MergeStep, FixedFormat, ForceThreadColumns, ForceFloatAccumulate >::get_window_size(), arm_conv::depthwise::interleaves::quantized::pack_parameters(), and GemmHybridIndirect< strategy, To, Tr, OutputStage, SeparateQuantize, FixedFormat >::pretranspose_B_array_part().
IndirectInterleave()
void IndirectInterleave (TOut * out, const TIn *const *const * ptr, unsigned int stringlen, unsigned int rounded_stringlen, const unsigned int y0, const unsigned int ymax, const unsigned int k0, const unsigned int kmax, bool integrate_sums, const int32_t row_sum_multiplier)
Definition at line 155 of file interleave_indirect.cpp.
{
     const unsigned int height = height_vectors * (vlt == VLType::SVE ? get_vector_length<TOut>() / block : 1);
     // 'interleave_block' implementations are entitled to read a pointer for each row they handle from the input
     // pointer array, even for out of range rows (although they must not subsequently dereference those pointers for
     // out of range rows).  This allows interleave_block to use techniques like row predication, or loading all
     // pointers and conditionally overriding the out of range ones.
     // This is problematic in the "pure" indirect case when we get to the last rows, where it can lead to out of
     // range reads.  Avoid this with a local buffer to use in last-rows cases.  Use alloca as a std::vector can be
     // expensive in highly threaded scenarios.
     const TIn **row_ptrs = reinterpret_cast<const TIn **>(alloca(height * sizeof(const TIn *)));
     // Figure out the starting position based on k0 (with rounded length)
     unsigned int start_string      = k0 / rounded_stringlen;
     unsigned int start_stringpos   = k0 % rounded_stringlen;
     // Process blocks of 'height' height...
     for (unsigned int ybase = y0; ybase < ymax; ybase+=height) {
         // Height to process
         unsigned int active_height = std::min(ymax - ybase, height);
         // Track our progress through the various strings
         unsigned int k_left    = (kmax - k0);
         unsigned int string    = start_string;
         unsigned int stringpos = start_stringpos;
         bool first = true;
         // Prepare to call 'interleave_block' above for each string encompassed by K range
         while (k_left > 0) {
             // Width to process - and the width we will generate (with padding)
             unsigned int in_width   = std::min(k_left, stringlen - stringpos);
             unsigned int out_width  = std::min(k_left, rounded_stringlen - stringpos);
             const TIn * const *row_base = ptr[string] + ybase;
             // If not all rows are valid, copy the ones that are into local array (see above comment).
             if (active_height < height) {
                 for (unsigned int i=0; i<active_height; i++) {
                     row_ptrs[i] = ptr[string][ybase + i];
                 }
                 row_base = row_ptrs;
             }
             // 'integrate_sums' is a function parameter rather than a template parameter to prevent duplicating too
             // much code.  However, integrated sums make no sense for non-integral types and won't ever be
             // requested.  So put a type trait check here to avoid generating pointless code.
             if (std::is_integral<TOut>::value && integrate_sums && row_sum_multiplier) {
                 interleave_block<height_vectors, block, vlt, true>(out, row_base, in_width, active_height, stringpos, first);
             } else {
                 interleave_block<height_vectors, block, vlt, false>(out, row_base, in_width, active_height, stringpos, first);
             }
             k_left -= out_width;
             string++;
             stringpos=0;
             first=false;
         }
         if (std::is_integral<TOut>::value && integrate_sums) {
             FixupRowSums<height_vectors, block, vlt>(out, row_sum_multiplier);
         }
     }
 }
References SVE.
Interleave()
void Interleave (TOut * out, const TIn * in, size_t in_stride, const unsigned int y0, const unsigned int ymax, const unsigned int k0, const unsigned int kmax, bool integrate_sums, const int32_t row_sum_multiplier)
Definition at line 265 of file interleave_indirect.cpp.
{
     const unsigned int height = height_vectors * (vlt == VLType::SVE ? get_vector_length<TOut>() / block : 1);
     // Use alloca here as a std::vector can be expensive in highly threaded scenarios.
     const TIn **row_ptrs = reinterpret_cast<const TIn **>(alloca(height * sizeof(const TIn *)));
     const unsigned int width=kmax-k0;
     for (unsigned int y=y0; y<ymax; y+=height) {
         for (unsigned int r=0; r<height; r++) {
             row_ptrs[r] = in + ((y + r) * in_stride);
         }
         if (std::is_integral<TOut>::value && integrate_sums && row_sum_multiplier) {
             interleave_block<height_vectors, block, vlt, true>(out, row_ptrs, width, std::min(height, ymax-y), k0, true);
         } else {
             interleave_block<height_vectors, block, vlt, false>(out, row_ptrs, width, std::min(height, ymax-y), k0, true);
         }
         if (std::is_integral<TOut>::value && integrate_sums) {
             FixupRowSums<height_vectors, block, vlt>(out, row_sum_multiplier);
         }
     }
 }
References SVE.
interleave_block()
void arm_gemm::interleave_block (TOut *& out, const TIn *const * in, size_t width, size_t height, size_t row_offset, bool first)
Definition at line 61 of file interleave_indirect.cpp.
{
     const unsigned int int_by = height_vectors * (vlt == VLType::SVE ? get_vector_length<TOut>() / block : 1);
     std::vector<int32_t> the_sums;
     if (integrate_sums) {
         the_sums = std::vector<int32_t>(int_by, 0);
         if (!first) {
             // In 'integrate sums' mode, we dump the sums at the end on each pass.
             // On the last pass this is correct, but on other passes it is not -
             // so on the subsequent pass we need to take the output written by
             // the previous pass as starting point for the sums, and then
             // overwrite them with new interleaved data.
             int32_t *out_int32 = reinterpret_cast<int32_t *>(out);
             // Rewind pointer to where we wrote out the sums last time.
             out_int32 -= int_by;
             // Restore the running sums.
             memcpy(the_sums.data(), out_int32, int_by * sizeof(int32_t));
             // Update the "real" pointer so that the next output will clobber the old sums.
             out = reinterpret_cast<TOut *>(out_int32);
         }
     }
     for (unsigned int pos=0; pos<width; pos+=block) {
         for (unsigned int row=0; row<int_by; row++) {
             // Row out of range - pad 'block' entries.
             if (row >= height) {
                 for (unsigned int col=0; col<block; col++) {
                     *out++ = 0;
                 }
                 continue;
             }
             for (unsigned int col=0; col<block; col++) {
                 // Column out of range - pad a single entry
                 if (pos + col >= width) {
                     *out++ = 0;
                     continue;
                 }
                 if (integrate_sums) {
                     the_sums[row] += in[row][row_offset + pos + col];
                 }
                 *out++ = in[row][row_offset + pos + col];
             }
         }
     }
     if (integrate_sums) {
         int32_t *out_int32 = reinterpret_cast<int32_t *>(out);
         memcpy(out_int32, the_sums.data(), int_by * sizeof(int32_t));
         out = reinterpret_cast<TOut *>(out_int32 + int_by);
     }
 }
References SVE.
MergeResults()
void MergeResults (Tout * out, const Tin * in, int ldc, int y0, int ymax, int x0, int xmax, const Tout * bias, Activation act, bool append)
Definition at line 38 of file mergeresults.cpp.
{
     // NOTE: The following code is disabled to avoid calling get_vector_length(), so templated MergeResults will not
     // be correct for SVE cases.  This is OK as we have specialisations for all needed SVE cases anyway.
     //
     // For SVE cases, multiply the width up by the vector length.
     // Use the *input* type to determine this, since this will be what the kernel operated on.
     // const int width = twidth * (sve ? get_vector_length<Tin>() : 1);
     const int width = twidth;
     const int full_y_blocks = (ymax - y0) / height;
     const int y_remainder = (ymax - y0) % height;
     const int y_blocks = full_y_blocks + (y_remainder ? 1 : 0);
     const int full_x_blocks = (xmax - x0) / width;
     const int x_remainder = (xmax - x0) % width;
     const int x_blocks = full_x_blocks + (x_remainder ? 1 : 0);
     for (int y_block = 0; y_block < y_blocks; y_block++) {
         int ybase = y0 + (y_block * height);
         int fill_rows = (y_block < full_y_blocks) ? height : y_remainder;
         for (int x_block = 0; x_block < x_blocks; x_block++) {
             int xbase = x0 + (x_block * width);
             int fill_cols = (x_block < full_x_blocks) ? width : x_remainder;
             for (int row=0; row < fill_rows; row++) {
                 for (int col=0; col < fill_cols; col++) {
                     Tout &r = out[(ybase + row) * ldc + xbase + col];
                     Tout v = in[row * width + col];
                     if (append) {
                         v += r;
                     }
                     if (bias) {
                         v += bias[xbase + col];
                     }
                     switch(act.type) {
                         default:
                         case Activation::Type::None:
                             break;
                         case Activation::Type::ReLU:
                             v = std::max(v, static_cast<Tout>(0));
                             break;
                         case Activation::Type::BoundedReLU:
                             v = std::max(std::min(v, static_cast<Tout>(act.param1)), static_cast<Tout>(0));
                             break;
                     }
                     r = v;
                 }
             }
             in += (width * height);
         }
     }
 }
References bias, Activation::BoundedReLU, Activation::None, Activation::param1, Activation::ReLU, and Activation::type.
Referenced by StdTransformsSVE< TOperand, TResult, height, width_vectors, block, mmla, integrate_sums >::Merge().
quant_hybrid_asymmetric()
bool arm_gemm::quant_hybrid_asymmetric (const Requantize32 & qp) inline
Definition at line 134 of file utils.hpp.
{
     return quant_no_left_shift(qp) /*  && qp.b_offset != 0 */ && qp.per_channel_requant==false;
 }
References Requantize32::per_channel_requant, and quant_no_left_shift().
quant_hybrid_symmetric()
bool arm_gemm::quant_hybrid_symmetric (const Requantize32 & qp) inline
Definition at line 128 of file utils.hpp.
{
     return quant_no_left_shift(qp) && qp.b_offset == 0;
 }
References Requantize32::b_offset, and quant_no_left_shift().
quant_no_left_shift()
bool arm_gemm::quant_no_left_shift (const Requantize32 & qp) inline
Definition at line 118 of file utils.hpp.
{
     if (qp.per_channel_requant) {
         return (qp.per_channel_left_shifts == nullptr);
     } else {
         return (qp.per_layer_left_shift == 0);
     }
 }
References Requantize32::per_channel_left_shifts, Requantize32::per_channel_requant, and Requantize32::per_layer_left_shift.
Referenced by quant_hybrid_asymmetric(), and quant_hybrid_symmetric().
requantize_block_32()
void arm_gemm::requantize_block_32 (const Requantize32 & qp, unsigned int width, unsigned int height, const Tin * input, unsigned int in_stride, Tout * output, unsigned int out_stride, const int32_t * row_bias, const int32_t * col_bias, unsigned int start_col)
Referenced by GemmHybridQuantized< strategy, To, Tr >::execute().
roundup()
T arm_gemm::roundup (const T a, const T b) inline
Definition at line 70 of file utils.hpp.
{
     T rem = a % b;
     if (rem) {
         return a + b - rem;
     } else {
         return a;
     }
 }
References arm_compute::test::validation::b.
Referenced by GemmHybrid< strategy, To, Tr >::estimate_cycles(), GemmInterleaved< strategy, To, Tr, OutputStage, MergeStep, FixedFormat, ForceThreadColumns, ForceFloatAccumulate >::estimate_cycles(), GemvPretransposed< strategy, To, Tr, OutputStage >::execute(), GemmHybrid< strategy, To, Tr >::execute(), GemmHybridQuantizedInline< strategy, To, Tr >::execute(), GemmHybridQuantized< strategy, To, Tr >::execute(), GemmHybridIndirect< strategy, To, Tr, OutputStage, SeparateQuantize, FixedFormat >::execute(), GemmInterleaved< strategy, To, Tr, OutputStage, MergeStep, FixedFormat, ForceThreadColumns, ForceFloatAccumulate >::execute(), GemmHybridQuantizedInline< strategy, To, Tr >::get_B_pretransposed_array_size(), GemmHybrid< strategy, To, Tr >::get_B_pretransposed_array_size(), GemmHybridQuantized< strategy, To, Tr >::get_B_pretransposed_array_size(), GemmHybridIndirect< strategy, To, Tr, OutputStage, SeparateQuantize, FixedFormat >::get_B_pretransposed_array_size(), GemmInterleaved< strategy, To, Tr, OutputStage, MergeStep, FixedFormat, ForceThreadColumns, ForceFloatAccumulate >::get_B_pretransposed_array_size(), GemmHybrid< strategy, To, Tr >::pretranspose_B_array(), GemmHybridQuantizedInline< strategy, To, Tr >::pretranspose_B_array(), GemmHybridQuantized< strategy, To, Tr >::pretranspose_B_array(), GemmHybridIndirect< strategy, To, Tr, OutputStage, SeparateQuantize, FixedFormat >::pretranspose_B_array_part(), and GemmInterleaved< strategy, To, Tr, OutputStage, MergeStep, FixedFormat, ForceThreadColumns, ForceFloatAccumulate >::pretranspose_B_array_part().
row_sums_indirect()
void arm_gemm::row_sums_indirect (size_t num_strings, const unsigned int * string_lengths, IndirectInputArg< T > A_arg, size_t M, int32_t * output_ptr, const Requantize32 * qp)
to_ndcoord()
ndcoord_t arm_gemm::to_ndcoord (const arm_compute::Window & win) inline
Convert an arm_compute::Window to an arm_gemm::NDCoord of the same max dimensions.
Parameters
[win] the arm_compute::Window we want to convert to arm_gemm::ndcoord_t
Returns
the resultant ndcoord_t
Definition at line 112 of file arm_gemm_compute_iface.hpp.
 {
     return {{static_cast<unsigned int>(win[0].start()), static_cast<unsigned int>(win[0].end() - win[0].start())},
             {static_cast<unsigned int>(win[1].start()), static_cast<unsigned int>(win[1].end() - win[1].start())},
             {static_cast<unsigned int>(win[2].start()), static_cast<unsigned int>(win[2].end() - win[2].start())},
             {static_cast<unsigned int>(win[3].start()), static_cast<unsigned int>(win[3].end() - win[3].start())},
             {static_cast<unsigned int>(win[4].start()), static_cast<unsigned int>(win[4].end() - win[4].start())},
             {static_cast<unsigned int>(win[5].start()), static_cast<unsigned int>(win[5].end() - win[5].start())}};
 }
References arm_compute::mlgo::parser::end().
Referenced by CpuGemmAssemblyWrapperKernel< TypeInput, TypeOutput >::run(), and CpuGemmAssemblyWrapperKernel< TypeInput, TypeOutput >::run_nd().
to_ndrange()
ndrange_t arm_gemm::to_ndrange (const arm_compute::Window & win) inline
Convert an arm_compute::Window to an arm_gemm::NDRange of the same max dimensions.
It should be noted that arm_compute::Window specifies a start() and an end() where as arm_gemm::ndrange_t only has a size, as a result we store the delta between the range
Parameters
[win] the arm_compute::Window we want to convert to arm_gemm::ndrange_t
Returns
the resultant ndrange_t
Definition at line 97 of file arm_gemm_compute_iface.hpp.
 {
     return {static_cast<unsigned int>(win[0].end() - win[0].start()),
             static_cast<unsigned int>(win[1].end() - win[1].start()),
             static_cast<unsigned int>(win[2].end() - win[2].start()),
             static_cast<unsigned int>(win[3].end() - win[3].start()),
             static_cast<unsigned int>(win[4].end() - win[4].start()),
             static_cast<unsigned int>(win[5].end() - win[5].start())};
 }
References arm_compute::mlgo::parser::end().
to_window() [1/2]
arm_compute::Window arm_gemm::to_window (const ndcoord_t & ndc) inline
Definition at line 72 of file arm_gemm_compute_iface.hpp.
 {
     arm_compute::Window win;
     for (unsigned int i = 0; i != ndrange_max; ++i)
     {
         const auto start = ndc.get_position(i);
         const auto size  = ndc.get_size(i);
         const auto stop  = start + size;
         //populate the window with the dimensions of the NDRange
         win.set(i, arm_compute::Window::Dimension(start, stop));
     }
     return win;
 }
References NDCoordinate< N >::get_position(), NDRange< D >::get_size(), ndrange_max, and Window::set().
to_window() [2/2]
arm_compute::Window arm_gemm::to_window (const ndrange_t & ndr) inline
Definition at line 53 of file arm_gemm_compute_iface.hpp.
 {
     arm_compute::Window win;
     for (unsigned int i = 0; i != ndrange_max; ++i)
     {
         //populate the window with the dimensions of the NDRange
         win.set(i, arm_compute::Window::Dimension(0, ndr.get_size(i)));
     }
     return win;
 }
References NDRange< D >::get_size(), ndrange_max, and Window::set().
Referenced by CpuGemmAssemblyWrapperKernel< TypeInput, TypeOutput >::configure().
Transform()
void Transform (TOut * out, const TIn *const in, const int stride, const int k0, const int kmax, const int x0, const int xmax)
Definition at line 116 of file transform.cpp.
   {
   // Redirect to a specialised implementation predicated on argument size.
   TransformImpl<IntBy, BlockBy, Transposed, sizeof(TOut), sizeof(TIn), vlt>::Transform(
     out, in, stride, k0, kmax, x0, xmax
   );
 }
Variable Documentation
ndrange_max
constexpr std::size_t ndrange_max = arm_compute::Dimensions<unsigned int>::num_max_dimensions constexpr
Definition at line 40 of file arm_gemm_compute_iface.hpp.
Referenced by to_window().
report_mutex
std::mutex report_mutex
Definition at line 37 of file misc.cpp.