Compute Library: arm_compute::cl_gemm::auto_heuristics Namespace Reference
arm_compute::cl_gemm::auto_heuristics Namespace Reference
Data Structures
struct CommonQuery
A collection of adaptor functions that enable the auto selection between mlgo-based heuristics and default heuristics.
struct GEMMConfigResult
Result of querying about GEMM config (GEMMLHSMatrixInfo and GEMMRHSMatrixInfo)
struct GEMMTypeResult
Result of querying about GEMM type (CLGEMMKernelType)
Functions
GEMMTypeResult select_mlgo_gemm_kernel (const CommonQuery &query, bool reshape_b_only_on_first_run)
Select gemm type based on mlgo heuristics.
GEMMTypeResult select_default_gemm_kernel (const CommonQuery &query, bool reshape_b_only_on_first_run)
Select gemm type based on default heuristics.
GEMMConfigResult select_default_gemm_config_reshaped_only_rhs (const CommonQuery &query)
Select gemm config based on default heuristics.
GEMMConfigResult select_mlgo_gemm_config_reshaped_only_rhs (const CommonQuery &query)
Select gemm config based on mlgo heuristics.
GEMMConfigResult select_default_gemm_config_reshaped (const CommonQuery &query)
Select gemm config based on default heuristics.
GEMMConfigResult select_mlgo_gemm_config_reshaped (const CommonQuery &query)
Select gemm config based on mlgo heuristics.
GEMMConfigResult select_default_gemm_config_native (const CommonQuery &query)
Select gemm config based on default heuristics.
GEMMConfigResult select_mlgo_gemm_config_native (const CommonQuery &query)
Select gemm config based on mlgo heuristics.
Function Documentation
select_default_gemm_config_native()
GEMMConfigResult select_default_gemm_config_native (const CommonQuery & query)
Select gemm config based on default heuristics.
Parameters
query Query
Returns
GEMMConfigResult. Result is valid if bool(GEMMConfigResult) == true and invalid otherwise
Definition at line 166 of file CLGEMMAutoHeuristics.cpp.
 {
     GEMMLHSMatrixInfo                    lhs_info;
     GEMMRHSMatrixInfo                    rhs_info;
     std::unique_ptr<IClGemmKernelConfig> gemm_config = ClGemmNativeKernelConfigurationFactory::create(query.gpu_target);
     ARM_COMPUTE_ERROR_ON_NULLPTR(gemm_config.get());
     std::tie(lhs_info, rhs_info) = gemm_config->configure(query.m, query.n, query.k, query.b, query.data_type);
     return GEMMConfigResult{true, lhs_info, rhs_info};
 }
References ARM_COMPUTE_ERROR_ON_NULLPTR, CommonQuery::b, ClGemmNativeKernelConfigurationFactory::create(), CommonQuery::data_type, CommonQuery::gpu_target, CommonQuery::k, CommonQuery::m, and CommonQuery::n.
Referenced by ClGemmLowpMatrixMultiplyCore::validate().
select_default_gemm_config_reshaped()
GEMMConfigResult select_default_gemm_config_reshaped (const CommonQuery & query)
Select gemm config based on default heuristics.
Parameters
query Query
Returns
GEMMConfigResult. Result is valid if bool(GEMMConfigResult) == true and invalid otherwise
Definition at line 128 of file CLGEMMAutoHeuristics.cpp.
 {
     GEMMLHSMatrixInfo                    lhs_info;
     GEMMRHSMatrixInfo                    rhs_info;
     std::unique_ptr<IClGemmKernelConfig> gemm_config =
         ClGemmReshapedKernelConfigurationFactory::create(query.gpu_target);
     ARM_COMPUTE_ERROR_ON_NULLPTR(gemm_config.get());
     std::tie(lhs_info, rhs_info) = gemm_config->configure(query.m, query.n, query.k, query.b, query.data_type);
     return GEMMConfigResult{true, lhs_info, rhs_info};
 }
References ARM_COMPUTE_ERROR_ON_NULLPTR, CommonQuery::b, ClGemmReshapedKernelConfigurationFactory::create(), CommonQuery::data_type, CommonQuery::gpu_target, CommonQuery::k, CommonQuery::m, and CommonQuery::n.
select_default_gemm_config_reshaped_only_rhs()
GEMMConfigResult select_default_gemm_config_reshaped_only_rhs (const CommonQuery & query)
Select gemm config based on default heuristics.
Parameters
query Query
Returns
GEMMConfigResult. Result is valid if bool(GEMMConfigResult) == true and invalid otherwise
Definition at line 89 of file CLGEMMAutoHeuristics.cpp.
 {
     GEMMLHSMatrixInfo                    lhs_info;
     GEMMRHSMatrixInfo                    rhs_info;
     std::unique_ptr<IClGemmKernelConfig> gemm_config =
         ClGemmReshapedOnlyRhsKernelConfigurationFactory::create(query.gpu_target);
     ARM_COMPUTE_ERROR_ON_NULLPTR(gemm_config.get());
     std::tie(lhs_info, rhs_info) = gemm_config->configure(query.m, query.n, query.k, query.b, query.data_type);
     return GEMMConfigResult{true, lhs_info, rhs_info};
 }
References ARM_COMPUTE_ERROR_ON_NULLPTR, CommonQuery::b, ClGemmReshapedOnlyRhsKernelConfigurationFactory::create(), CommonQuery::data_type, CommonQuery::gpu_target, CommonQuery::k, CommonQuery::m, and CommonQuery::n.
Referenced by ClGemmLowpMatrixMultiplyCore::validate().
select_default_gemm_kernel()
GEMMTypeResult select_default_gemm_kernel (const CommonQuery & query, bool reshape_b_only_on_first_run)
Select gemm type based on default heuristics.
Parameters
query Query
reshape_b_only_on_first_run Additional query parameter if reshape b only on first run
Returns
GEMMTypeResult. Result is valid if bool(GEMMTypeResult) == true and invalid otherwise
Definition at line 72 of file CLGEMMAutoHeuristics.cpp.
 {
     std::unique_ptr<ICLGEMMKernelSelection> default_heuristics = CLGEMMKernelSelectionFactory::create(query.gpu_target);
     ARM_COMPUTE_ERROR_ON_NULLPTR(default_heuristics.get());
     CLGEMMKernelSelectionParams params;
     params.m               = query.m;
     params.n               = query.n;
     params.k               = query.k;
     params.b               = query.b;
     params.is_rhs_constant = reshape_b_only_on_first_run;
     params.data_type       = query.data_type;
     const auto kernel_type = default_heuristics->select_kernel(params);
     return GEMMTypeResult(true, kernel_type);
 }
References ARM_COMPUTE_ERROR_ON_NULLPTR, CommonQuery::b, CLGEMMKernelSelectionParams::b, CLGEMMKernelSelectionFactory::create(), CommonQuery::data_type, CLGEMMKernelSelectionParams::data_type, CommonQuery::gpu_target, CLGEMMKernelSelectionParams::is_rhs_constant, CommonQuery::k, CLGEMMKernelSelectionParams::k, CommonQuery::m, CLGEMMKernelSelectionParams::m, CommonQuery::n, and CLGEMMKernelSelectionParams::n.
select_mlgo_gemm_config_native()
GEMMConfigResult select_mlgo_gemm_config_native (const CommonQuery & query)
Select gemm config based on mlgo heuristics.
Parameters
query Query
Returns
GEMMConfigResult. Result is valid if bool(GEMMConfigResult) == true and invalid otherwise
Definition at line 176 of file CLGEMMAutoHeuristics.cpp.
 {
     bool                   valid = false;
     GEMMLHSMatrixInfo      lhs_info;
     GEMMRHSMatrixInfo      rhs_info;
     mlgo::GEMMConfigNative config{};
     const auto             mlgo_heuristics = CLScheduler::get().gemm_heuristics();
     if (mlgo_heuristics != nullptr)
     {
         std::tie(valid, config) = mlgo_heuristics->get()->query_gemm_config_native(
             mlgo::Query{string_from_target(query.gpu_target), query.data_type, query.m, query.n, query.k, query.b});
     }
     if (valid)
     {
         ARM_COMPUTE_LOG_INFO_MSG_WITH_FORMAT_CORE("MLGOHeuristics query returns gemm config: %s.",
                                                   to_string(config).c_str());
         // Setting irrelevant unsigned int parameters to 1 and bool parameters to false as they do no matter
         std::tie(lhs_info, rhs_info) = opencl::kernels::gemm::configure_lhs_rhs_info(
             query.m, query.n, config.m0, config.n0, config.k0, 1, 1, false, false, false, false, false);
     }
     else
     {
         ARM_COMPUTE_LOG_INFO_MSG_CORE("MLGOHeuristics query failed");
     }
     return GEMMConfigResult{valid, lhs_info, rhs_info};
 }
References ARM_COMPUTE_LOG_INFO_MSG_CORE, ARM_COMPUTE_LOG_INFO_MSG_WITH_FORMAT_CORE, CommonQuery::b, arm_compute::opencl::kernels::gemm::configure_lhs_rhs_info(), CommonQuery::data_type, CLScheduler::gemm_heuristics(), CLScheduler::get(), CLGEMMHeuristicsHandle::get(), CommonQuery::gpu_target, CommonQuery::k, CommonQuery::m, CommonQuery::n, MLGOHeuristics::query_gemm_config_native(), arm_compute::string_from_target(), and arm_compute::to_string().
select_mlgo_gemm_config_reshaped()
GEMMConfigResult select_mlgo_gemm_config_reshaped (const CommonQuery & query)
Select gemm config based on mlgo heuristics.
Parameters
query Query
Returns
GEMMConfigResult. Result is valid if bool(GEMMConfigResult) == true and invalid otherwise
Definition at line 139 of file CLGEMMAutoHeuristics.cpp.
 {
     bool                     valid = false;
     GEMMLHSMatrixInfo        lhs_info;
     GEMMRHSMatrixInfo        rhs_info;
     mlgo::GEMMConfigReshaped config{};
     const auto               mlgo_heuristics = CLScheduler::get().gemm_heuristics();
     if (mlgo_heuristics != nullptr)
     {
         std::tie(valid, config) = mlgo_heuristics->get()->query_gemm_config_reshaped(
             mlgo::Query{string_from_target(query.gpu_target), query.data_type, query.m, query.n, query.k, query.b});
     }
     if (valid)
     {
         ARM_COMPUTE_LOG_INFO_MSG_WITH_FORMAT_CORE("MLGOHeuristics query returns gemm config: %s.",
                                                   to_string(config).c_str());
         std::tie(lhs_info, rhs_info) = configure_lhs_rhs_info(
             query.m, query.n, config.m0, config.n0, config.k0, config.v0, config.h0, config.interleave_lhs,
             config.interleave_rhs, !config.transpose_rhs, config.transpose_rhs, config.export_cl_image);
     }
     else
     {
         ARM_COMPUTE_LOG_INFO_MSG_CORE("MLGOHeuristics query failed");
     }
     return GEMMConfigResult{valid, lhs_info, rhs_info};
 }
References ARM_COMPUTE_LOG_INFO_MSG_CORE, ARM_COMPUTE_LOG_INFO_MSG_WITH_FORMAT_CORE, CommonQuery::b, arm_compute::opencl::kernels::gemm::configure_lhs_rhs_info(), CommonQuery::data_type, CLScheduler::gemm_heuristics(), CLScheduler::get(), CLGEMMHeuristicsHandle::get(), CommonQuery::gpu_target, CommonQuery::k, CommonQuery::m, CommonQuery::n, MLGOHeuristics::query_gemm_config_reshaped(), arm_compute::string_from_target(), and arm_compute::to_string().
select_mlgo_gemm_config_reshaped_only_rhs()
GEMMConfigResult select_mlgo_gemm_config_reshaped_only_rhs (const CommonQuery & query)
Select gemm config based on mlgo heuristics.
Parameters
query Query
Returns
GEMMConfigResult. Result is valid if bool(GEMMConfigResult) == true and invalid otherwise
Definition at line 100 of file CLGEMMAutoHeuristics.cpp.
 {
     bool                            valid = false;
     GEMMLHSMatrixInfo               lhs_info;
     GEMMRHSMatrixInfo               rhs_info;
     mlgo::GEMMConfigReshapedOnlyRHS config{};
     const auto                      mlgo_heuristics = CLScheduler::get().gemm_heuristics();
     if (mlgo_heuristics != nullptr)
     {
         std::tie(valid, config) = mlgo_heuristics->get()->query_gemm_config_reshaped_only_rhs(
             mlgo::Query{string_from_target(query.gpu_target), query.data_type, query.m, query.n, query.k, query.b});
     }
     if (valid)
     {
         ARM_COMPUTE_LOG_INFO_MSG_WITH_FORMAT_CORE("MLGOHeuristics query returns gemm config: %s.",
                                                   to_string(config).c_str());
         // Setting irrelevant unsigned int parameters to 1 and bool parameters to false as they do no matter
         std::tie(lhs_info, rhs_info) = configure_lhs_rhs_info(
             query.m, query.n, config.m0, config.n0, config.k0, 1, config.h0, false, config.interleave_rhs,
             !config.transpose_rhs, config.transpose_rhs, config.export_cl_image);
     }
     else
     {
         ARM_COMPUTE_LOG_INFO_MSG_CORE("MLGOHeuristics query failed");
     }
     return GEMMConfigResult{valid, lhs_info, rhs_info};
 }
References ARM_COMPUTE_LOG_INFO_MSG_CORE, ARM_COMPUTE_LOG_INFO_MSG_WITH_FORMAT_CORE, CommonQuery::b, arm_compute::opencl::kernels::gemm::configure_lhs_rhs_info(), CommonQuery::data_type, CLScheduler::gemm_heuristics(), CLScheduler::get(), CLGEMMHeuristicsHandle::get(), CommonQuery::gpu_target, CommonQuery::k, CommonQuery::m, CommonQuery::n, MLGOHeuristics::query_gemm_config_reshaped_only_rhs(), arm_compute::string_from_target(), and arm_compute::to_string().
select_mlgo_gemm_kernel()
GEMMTypeResult select_mlgo_gemm_kernel (const CommonQuery & query, bool reshape_b_only_on_first_run)
Select gemm type based on mlgo heuristics.
Parameters
query Query
reshape_b_only_on_first_run Additional query parameter if reshape b only on first run
Returns
GEMMTypeResult. Result is valid if bool(GEMMTypeResult) == true and invalid otherwise
Definition at line 49 of file CLGEMMAutoHeuristics.cpp.
 {
     ARM_COMPUTE_UNUSED(reshape_b_only_on_first_run);
     bool             valid = false;
     CLGEMMKernelType gemm_type{};
     const auto       mlgo_heuristics = CLScheduler::get().gemm_heuristics();
     if (mlgo_heuristics != nullptr)
     {
         std::tie(valid, gemm_type) = mlgo_heuristics->get()->query_gemm_type(
             mlgo::Query{string_from_target(query.gpu_target), query.data_type, query.m, query.n, query.k, query.b});
     }
     if (valid)
     {
         ARM_COMPUTE_LOG_INFO_MSG_WITH_FORMAT_CORE("MLGOHeuristics query returns gemm type: %s.",
                                                   to_string(gemm_type).c_str());
     }
     else
     {
         ARM_COMPUTE_LOG_INFO_MSG_CORE("MLGOHeuristics query failed");
     }
     return GEMMTypeResult(valid, gemm_type);
 }
References ARM_COMPUTE_LOG_INFO_MSG_CORE, ARM_COMPUTE_LOG_INFO_MSG_WITH_FORMAT_CORE, ARM_COMPUTE_UNUSED, CommonQuery::b, CommonQuery::data_type, CLScheduler::gemm_heuristics(), arm_compute::mlgo::parser::gemm_type(), CLScheduler::get(), CLGEMMHeuristicsHandle::get(), CommonQuery::gpu_target, CommonQuery::k, CommonQuery::m, CommonQuery::n, MLGOHeuristics::query_gemm_type(), arm_compute::string_from_target(), and arm_compute::to_string().