Compute Library: arm_compute/AclOperators.h File Reference
AclOperators.h File Reference
#include "arm_compute/AclDescriptors.h"
#include "arm_compute/AclTypes.h"
Macros
#define ARM_COMPUTE_VALIDATE_OPERATOR_SUPPORT ((AclOperator *)(size_t)-1)
Used during an operator creation to validate its support.
Functions
AclStatus AclActivation (AclOperator *op, AclContext ctx, const AclTensorDescriptor *src, const AclTensorDescriptor *dst, const AclActivationDescriptor info)
__cplusplus
Macro Definition Documentation
ARM_COMPUTE_VALIDATE_OPERATOR_SUPPORT
#define ARM_COMPUTE_VALIDATE_OPERATOR_SUPPORT ((AclOperator *)(size_t)-1)
Used during an operator creation to validate its support.
Definition at line 31 of file AclOperators.h.
Function Documentation
AclActivation()
AclStatus AclActivation (AclOperator * op, AclContext ctx, const AclTensorDescriptor * src, const AclTensorDescriptor * dst, const AclActivationDescriptor info)
__cplusplus
Create an activation operator
Applies an activation function to a given tensor . Compute Library supports a wide list of activation functions AclActivationType.
A summarized table is the following:
Activation Function Mathematical Expression
Identity \(f(x)= x \)
Logistic \(f(x) = \frac{1}{1 + e^{-x}} \)
Tanh \(f(x) = a \cdot tanh(b \cdot x) \)
Relu \(f(x) = max(0,x) \)
Bounded Relu \(f(x) = min(a, max(0,x)) \)
Lower-Upper Bounded Relu \(f(x) = min(a, max(b,x)) \)
Leaky Relu \(f(x) = \begin{cases} \alpha x & \quad \text{if } x \text{ < 0}\\ x & \quad \text{if } x \geq \text{ 0 } \end{cases} \)
Soft Relu \(f(x)= log(1+e^x) \)
Soft Elu \(f(x) = \begin{cases} \alpha (exp(x) - 1) & \quad \text{if } x \text{ < 0}\\ x & \quad \text{if } x \geq \text{ 0 } \end{cases} \)
Abs | \(f(x)= |x| \) | Square | \(f(x)= x^2 \) | Sqrt | \(f(x) = \sqrt{x} \) | Linear | \(f(x)= ax + b \) | Hard Swish | \(f(x) = (x * relu6(x+3))/6 \) |
Backends:
OpenCL: ClActivationLayer
Cpu : CpuActivationLayer
Parameters
[in,out] op Operator construct to be created if creation was successful
[in] ctx Context to be used for the creation of the operator
[in] src Source tensor descriptor. Slot id: ACL_SRC
[in] dst Destination tensor descriptor. Slot id: ACL_DST
[in] info Activation meta-data
Returns
Status code
Returns:
AclSuccess if function was completed successfully
AclOutOfMemory if there was a failure allocating memory resources
AclUnsupportedTarget if operator for the requested target is unsupported
AclInvalidArgument if a given argument is invalid
Definition at line 30 of file AclActivation.cpp.
 {
     using namespace arm_compute;
     // Extract internal context
     auto       ctx    = get_internal(external_ctx);
     StatusCode status = detail::validate_internal_context(ctx);
     ARM_COMPUTE_RETURN_CENUM_ON_FAILURE(status);
     bool is_validate = (external_op == ARM_COMPUTE_VALIDATE_OPERATOR_SUPPORT);
     std::tie(*external_op, status) = ctx->create_activation(*src, *dst, info, is_validate);
     ARM_COMPUTE_RETURN_CENUM_ON_FAILURE(status);
     return AclSuccess;
 }
References AclSuccess, ARM_COMPUTE_RETURN_CENUM_ON_FAILURE, ARM_COMPUTE_VALIDATE_OPERATOR_SUPPORT, arm_compute::test::validation::dst, arm_compute::get_internal(), arm_compute::test::validation::info, arm_compute::test::validation::src, and arm_compute::detail::validate_internal_context().
Referenced by Activation::Activation().