Compute Library: arm_compute/AclEntrypoints.h File Reference
AclEntrypoints.h File Reference
#include "arm_compute/AclTypes.h"
Functions
AclStatus AclCreateContext (AclContext *ctx, AclTarget target, const AclContextOptions *options)
__cplusplus
AclStatus AclDestroyContext (AclContext ctx)
Destroy a given context object.
AclStatus AclCreateQueue (AclQueue *queue, AclContext ctx, const AclQueueOptions *options)
Create an operator queue.
AclStatus AclQueueFinish (AclQueue queue)
Wait until all elements on the queue have been completed.
AclStatus AclDestroyQueue (AclQueue queue)
Destroy a given queue object.
AclStatus AclCreateTensor (AclTensor *tensor, AclContext ctx, const AclTensorDescriptor *desc, bool allocate)
Create a Tensor object.
AclStatus AclMapTensor (AclTensor tensor, void **handle)
Map a tensor's backing memory to the host.
AclStatus AclUnmapTensor (AclTensor tensor, void *handle)
Unmap the tensor's backing memory.
AclStatus AclTensorImport (AclTensor tensor, void *handle, AclImportMemoryType type)
Import external memory to a given tensor object.
AclStatus AclDestroyTensor (AclTensor tensor)
Destroy a given tensor object.
AclStatus AclCreateTensorPack (AclTensorPack *pack, AclContext ctx)
Creates a tensor pack.
AclStatus AclPackTensor (AclTensorPack pack, AclTensor tensor, int32_t slot_id)
Add a tensor to a tensor pack.
AclStatus AclPackTensors (AclTensorPack pack, AclTensor *tensors, int32_t *slot_ids, size_t num_tensors)
A list of tensors to a tensor pack.
AclStatus AclDestroyTensorPack (AclTensorPack pack)
Destroy a given tensor pack object.
AclStatus AclRunOperator (AclOperator op, AclQueue queue, AclTensorPack tensors)
Eager execution of a given operator on a list of inputs and outputs.
AclStatus AclDestroyOperator (AclOperator op)
Destroy a given operator object.
Function Documentation
AclCreateContext()
AclStatus AclCreateContext (AclContext * ctx, AclTarget target, const AclContextOptions * options)
__cplusplus
Create a context object
Context is responsible for retaining internal information and work as an aggregate service mechanism
Parameters
[in,out] ctx A valid non-zero context object if no failure occurs
[in] target Target to create the context for
[in] options Context options to be used for all the kernels that are created under the context
Returns
Status code
Returns:
AclSuccess if function was completed successfully
AclOutOfMemory if there was a failure allocating memory resources
AclUnsupportedTarget if the requested target is unsupported
AclInvalidArgument if a given argument is invalid
Definition at line 78 of file AclContext.cpp.
 {
     if(!is_target_valid(target))
     {
         ARM_COMPUTE_LOG_ERROR_WITH_FUNCNAME_ACL("Target is invalid!");
         return AclUnsupportedTarget;
     }
     if(options != nullptr && !are_context_options_valid(options))
     {
         ARM_COMPUTE_LOG_ERROR_WITH_FUNCNAME_ACL("Context options are invalid!");
         return AclInvalidArgument;
     }
     auto ctx = create_context(target, options);
     if(ctx == nullptr)
     {
         ARM_COMPUTE_LOG_ERROR_WITH_FUNCNAME_ACL("Couldn't allocate internal resources for context creation!");
         return AclOutOfMemory;
     }
     *external_ctx = ctx;
     return AclSuccess;
 }
References AclInvalidArgument, AclOutOfMemory, AclSuccess, AclUnsupportedTarget, and ARM_COMPUTE_LOG_ERROR_WITH_FUNCNAME_ACL.
Referenced by Context::Context(), and arm_compute::test::validation::TEST_CASE().
AclCreateQueue()
AclStatus AclCreateQueue (AclQueue * queue, AclContext ctx, const AclQueueOptions * options)
Create an operator queue.
Queue is responsible for any scheduling related activities
Parameters
[in,out] queue A valid non-zero queue object is not failures occur
[in] ctx Context to be used
[in] options Queue options to be used for the operators using the queue
Returns
Status code
Returns:
AclSuccess if function was completed successfully
AclOutOfMemory if there was a failure allocating memory resources
AclUnsupportedTarget if the requested target is unsupported
AclInvalidArgument if a given argument is invalid
Definition at line 45 of file AclQueue.cpp.
 {
     using namespace arm_compute;
     auto ctx = get_internal(external_ctx);
     StatusCode status = detail::validate_internal_context(ctx);
     ARM_COMPUTE_RETURN_CENUM_ON_FAILURE(status);
     if(options != nullptr && !is_mode_valid(options))
     {
         ARM_COMPUTE_LOG_ERROR_ACL("Queue options are invalid");
         return AclInvalidArgument;
     }
     auto queue = ctx->create_queue(options);
     if(queue == nullptr)
     {
         ARM_COMPUTE_LOG_ERROR_ACL("Couldn't allocate internal resources");
         return AclOutOfMemory;
     }
     *external_queue = queue;
     return AclSuccess;
 }
References AclInvalidArgument, AclOutOfMemory, AclSuccess, ARM_COMPUTE_LOG_ERROR_ACL, ARM_COMPUTE_RETURN_CENUM_ON_FAILURE, arm_compute::get_internal(), and arm_compute::detail::validate_internal_context().
Referenced by Queue::Queue().
AclCreateTensor()
AclStatus AclCreateTensor (AclTensor * tensor, AclContext ctx, const AclTensorDescriptor * desc, bool allocate)
Create a Tensor object.
Tensor is a generalized matrix construct that can represent up to ND dimensionality (where N = 6 for Compute Library) The object holds a backing memory along-side to operate on
Parameters
[in,out] tensor A valid non-zero tensor object if no failures occur
[in] ctx Context to be used
[in] desc Tensor representation meta-data
[in] allocate Instructs allocation of the tensor objects
Returns:
AclSuccess if function was completed successfully
AclOutOfMemory if there was a failure allocating memory resources
AclUnsupportedTarget if the requested target is unsupported
AclInvalidArgument if a given argument is invalid
Definition at line 68 of file AclTensor.cpp.
 {
     using namespace arm_compute;
     IContext *ctx = get_internal(external_ctx);
     StatusCode status = detail::validate_internal_context(ctx);
     ARM_COMPUTE_RETURN_CENUM_ON_FAILURE(status);
     if(desc == nullptr || !is_desc_valid(*desc))
     {
         ARM_COMPUTE_LOG_ERROR_ACL("[AclCreateTensor]: Descriptor is invalid!");
         return AclInvalidArgument;
     }
     auto tensor = ctx->create_tensor(*desc, allocate);
     if(tensor == nullptr)
     {
         ARM_COMPUTE_LOG_ERROR_ACL("[AclCreateTensor]: Couldn't allocate internal resources for tensor creation!");
         return AclOutOfMemory;
     }
     *external_tensor = tensor;
     return AclSuccess;
 }
References AclInvalidArgument, AclOutOfMemory, AclSuccess, ARM_COMPUTE_LOG_ERROR_ACL, ARM_COMPUTE_RETURN_CENUM_ON_FAILURE, IContext::create_tensor(), arm_compute::get_internal(), tensor, and arm_compute::detail::validate_internal_context().
Referenced by Tensor::Tensor().
AclCreateTensorPack()
AclStatus AclCreateTensorPack (AclTensorPack * pack, AclContext ctx)
Creates a tensor pack.
Tensor packs are used to create a collection of tensors that can be passed around for operator execution
Parameters
[in,out] pack A valid non-zero tensor pack object if no failures occur
[in] ctx Context to be used
Returns
Status code
Returns:
AclSuccess if function was completed successfully
AclOutOfMemory if there was a failure allocating memory resources
AclInvalidArgument if a given argument is invalid
Definition at line 50 of file AclTensorPack.cpp.
 {
     using namespace arm_compute;
     IContext *ctx = get_internal(external_ctx);
     const StatusCode status = detail::validate_internal_context(ctx);
     ARM_COMPUTE_RETURN_CENUM_ON_FAILURE(status);
     auto pack = new TensorPack(ctx);
     if(pack == nullptr)
     {
         ARM_COMPUTE_LOG_ERROR_WITH_FUNCNAME_ACL("Couldn't allocate internal resources!");
         return AclOutOfMemory;
     }
     *external_pack = pack;
     return AclSuccess;
 }
References AclOutOfMemory, AclSuccess, ARM_COMPUTE_LOG_ERROR_WITH_FUNCNAME_ACL, ARM_COMPUTE_RETURN_CENUM_ON_FAILURE, arm_compute::get_internal(), arm_compute::test::validation::pack, and arm_compute::detail::validate_internal_context().
Referenced by TensorPack::TensorPack().
AclDestroyContext()
AclStatus AclDestroyContext (AclContext ctx)
Destroy a given context object.
Parameters
[in] ctx A valid context object to destroy
Returns
Status code
Returns:
AclSuccess if functions was completed successfully
AclInvalidArgument if the provided context is invalid
Definition at line 105 of file AclContext.cpp.
 {
     using namespace arm_compute;
     IContext *ctx = get_internal(external_ctx);
     StatusCode status = detail::validate_internal_context(ctx);
     ARM_COMPUTE_RETURN_CENUM_ON_FAILURE(status);
     if(ctx->refcount() != 0)
     {
         ARM_COMPUTE_LOG_ERROR_WITH_FUNCNAME_ACL("Context has references on it that haven't been released!");
         // TODO: Fix the refcount with callback when reaches 0
     }
     delete ctx;
     return utils::as_cenum<AclStatus>(status);
 }
References ARM_COMPUTE_LOG_ERROR_WITH_FUNCNAME_ACL, ARM_COMPUTE_RETURN_CENUM_ON_FAILURE, arm_compute::get_internal(), IContext::refcount(), and arm_compute::detail::validate_internal_context().
AclDestroyOperator()
AclStatus AclDestroyOperator (AclOperator op)
Destroy a given operator object.
Parameters
[in,out] op A valid operator object to destroy
Returns
Status code
Returns:
AclSuccess if functions was completed successfully
AclInvalidArgument if the provided context is invalid
Definition at line 53 of file AclOperator.cpp.
 {
     using namespace arm_compute;
     auto op = get_internal(external_op);
     StatusCode status = detail::validate_internal_operator(op);
     ARM_COMPUTE_RETURN_CENUM_ON_FAILURE(status);
     delete op;
     return AclSuccess;
 }
References AclSuccess, ARM_COMPUTE_RETURN_CENUM_ON_FAILURE, arm_compute::get_internal(), and arm_compute::detail::validate_internal_operator().
AclDestroyQueue()
AclStatus AclDestroyQueue (AclQueue queue)
Destroy a given queue object.
Parameters
[in] queue A valid context object to destroy
Returns
Status code
Returns:
AclSuccess if functions was completed successfully
AclInvalidArgument if the provided context is invalid
Definition at line 87 of file AclQueue.cpp.
 {
     using namespace arm_compute;
     auto queue = get_internal(external_queue);
     StatusCode status = detail::validate_internal_queue(queue);
     ARM_COMPUTE_RETURN_CENUM_ON_FAILURE(status);
     delete queue;
     return AclSuccess;
 }
References AclSuccess, ARM_COMPUTE_RETURN_CENUM_ON_FAILURE, arm_compute::get_internal(), and arm_compute::detail::validate_internal_queue().
AclDestroyTensor()
AclStatus AclDestroyTensor (AclTensor tensor)
Destroy a given tensor object.
Parameters
[in,out] tensor A valid tensor object to be destroyed
Returns
Status code
Returns:
AclSuccess if function was completed successfully
AclInvalidArgument if the provided tensor is invalid
Definition at line 144 of file AclTensor.cpp.
 {
     using namespace arm_compute;
     auto tensor = get_internal(external_tensor);
     StatusCode status = detail::validate_internal_tensor(tensor);
     ARM_COMPUTE_RETURN_CENUM_ON_FAILURE(status);
     delete tensor;
     return AclSuccess;
 }
References AclSuccess, ARM_COMPUTE_RETURN_CENUM_ON_FAILURE, arm_compute::get_internal(), tensor, and arm_compute::detail::validate_internal_tensor().
AclDestroyTensorPack()
AclStatus AclDestroyTensorPack (AclTensorPack pack)
Destroy a given tensor pack object.
Parameters
[in,out] pack A valid tensor pack object to destroy
Returns
Status code
Returns:
AclSuccess if functions was completed successfully
AclInvalidArgument if the provided context is invalid
Definition at line 94 of file AclTensorPack.cpp.
 {
     using namespace arm_compute;
     auto       pack   = get_internal(external_pack);
     StatusCode status = detail::validate_internal_pack(pack);
     ARM_COMPUTE_RETURN_CENUM_ON_FAILURE(status);
     delete pack;
     return AclSuccess;
 }
References AclSuccess, ARM_COMPUTE_RETURN_CENUM_ON_FAILURE, arm_compute::get_internal(), arm_compute::test::validation::pack, and arm_compute::detail::validate_internal_pack().
AclMapTensor()
AclStatus AclMapTensor (AclTensor tensor, void ** handle)
Map a tensor's backing memory to the host.
Parameters
[in] tensor Tensor to be mapped
[in,out] handle A handle to the underlying backing memory
Returns
Status code
Returns:
AclSuccess if function was completed successfully
AclInvalidArgument if a given argument is invalid
Definition at line 97 of file AclTensor.cpp.
 {
     using namespace arm_compute;
     auto       tensor = get_internal(external_tensor);
     StatusCode status = detail::validate_internal_tensor(tensor);
     ARM_COMPUTE_RETURN_CENUM_ON_FAILURE(status);
     if(handle == nullptr)
     {
         ARM_COMPUTE_LOG_ERROR_ACL("[AclMapTensor]: Handle object is nullptr!");
         return AclInvalidArgument;
     }
     *handle = tensor->map();
     return AclSuccess;
 }
References AclInvalidArgument, AclSuccess, ARM_COMPUTE_LOG_ERROR_ACL, ARM_COMPUTE_RETURN_CENUM_ON_FAILURE, arm_compute::get_internal(), CLTensor::map(), tensor, and arm_compute::detail::validate_internal_tensor().
Referenced by Tensor::map().
AclPackTensor()
AclStatus AclPackTensor (AclTensorPack pack, AclTensor tensor, int32_t slot_id)
Add a tensor to a tensor pack.
Parameters
[in,out] pack Pack to append a tensor to
[in] tensor Tensor to pack
[in] slot_id Slot of the operator that the tensors corresponds to
Returns
Status code
Returns:
AclSuccess if function was completed successfully
AclOutOfMemory if there was a failure allocating memory resources
AclInvalidArgument if a given argument is invalid
Definition at line 70 of file AclTensorPack.cpp.
 {
     using namespace arm_compute;
     auto pack = get_internal(external_pack);
     ARM_COMPUTE_RETURN_CENUM_ON_FAILURE(detail::validate_internal_pack(pack));
     ARM_COMPUTE_RETURN_CENUM_ON_FAILURE(PackTensorInternal(*pack, external_tensor, slot_id));
     return AclStatus::AclSuccess;
 }
References AclSuccess, ARM_COMPUTE_RETURN_CENUM_ON_FAILURE, arm_compute::get_internal(), arm_compute::test::validation::pack, and arm_compute::detail::validate_internal_pack().
Referenced by TensorPack::add().
AclPackTensors()
AclStatus AclPackTensors (AclTensorPack pack, AclTensor * tensors, int32_t * slot_ids, size_t num_tensors)
A list of tensors to a tensor pack.
Parameters
[in,out] pack Pack to append the tensors to
[in] tensors Tensors to append to the pack
[in] slot_ids Slot IDs of each tensors to the operators
[in] num_tensors Number of tensors that are passed
Returns
Status code
Returns:
AclSuccess if function was completed successfully
AclOutOfMemory if there was a failure allocating memory resources
AclInvalidArgument if a given argument is invalid
Definition at line 80 of file AclTensorPack.cpp.
 {
     using namespace arm_compute;
     auto pack = get_internal(external_pack);
     ARM_COMPUTE_RETURN_CENUM_ON_FAILURE(detail::validate_internal_pack(pack));
     for(unsigned i = 0; i < num_tensors; ++i)
     {
         ARM_COMPUTE_RETURN_CENUM_ON_FAILURE(PackTensorInternal(*pack, external_tensors[i], slot_ids[i]));
     }
     return AclStatus::AclSuccess;
 }
References AclSuccess, ARM_COMPUTE_RETURN_CENUM_ON_FAILURE, arm_compute::get_internal(), arm_compute::test::validation::pack, and arm_compute::detail::validate_internal_pack().
Referenced by TensorPack::add().
AclQueueFinish()
AclStatus AclQueueFinish (AclQueue queue)
Wait until all elements on the queue have been completed.
Parameters
[in] queue Queue to wait on completion
Returns
Status code
Returns:
AclSuccess if functions was completed successfully
AclInvalidArgument if the provided queue is invalid
AclRuntimeError on any other runtime related error
Definition at line 72 of file AclQueue.cpp.
 {
     using namespace arm_compute;
     auto queue = get_internal(external_queue);
     StatusCode status = detail::validate_internal_queue(queue);
     ARM_COMPUTE_RETURN_CENUM_ON_FAILURE(status);
     status = queue->finish();
     ARM_COMPUTE_RETURN_CENUM_ON_FAILURE(status);
     return AclSuccess;
 }
References AclSuccess, ARM_COMPUTE_RETURN_CENUM_ON_FAILURE, arm_compute::get_internal(), and arm_compute::detail::validate_internal_queue().
Referenced by Queue::finish().
AclRunOperator()
AclStatus AclRunOperator (AclOperator op, AclQueue queue, AclTensorPack tensors)
Eager execution of a given operator on a list of inputs and outputs.
Parameters
[in] op Operator to execute
[in] queue Queue to schedule the operator on
[in,out] tensors A list of input and outputs tensors to execute the operator on
Returns
Status Code
Returns:
AclSuccess if function was completed successfully
AclOutOfMemory if there was a failure allocating memory resources
AclUnsupportedTarget if the requested target is unsupported
AclInvalidArgument if a given argument is invalid
AclRuntimeError on any other runtime related error
Definition at line 31 of file AclOperator.cpp.
 {
     using namespace arm_compute;
     auto op    = get_internal(external_op);
     auto queue = get_internal(external_queue);
     auto pack  = get_internal(external_tensors);
     StatusCode status = StatusCode::Success;
     status            = detail::validate_internal_operator(op);
     ARM_COMPUTE_RETURN_CENUM_ON_FAILURE(status);
     status = detail::validate_internal_queue(queue);
     ARM_COMPUTE_RETURN_CENUM_ON_FAILURE(status);
     status = detail::validate_internal_pack(pack);
     ARM_COMPUTE_RETURN_CENUM_ON_FAILURE(status);
     status = op->run(*queue, pack->get_tensor_pack());
     ARM_COMPUTE_RETURN_CENUM_ON_FAILURE(status);
     return AclSuccess;
 }
References AclSuccess, ARM_COMPUTE_RETURN_CENUM_ON_FAILURE, arm_compute::get_internal(), arm_compute::test::validation::pack, arm_compute::Success, arm_compute::detail::validate_internal_operator(), arm_compute::detail::validate_internal_pack(), and arm_compute::detail::validate_internal_queue().
Referenced by Operator::run().
AclTensorImport()
AclStatus AclTensorImport (AclTensor tensor, void * handle, AclImportMemoryType type)
Import external memory to a given tensor object.
Parameters
[in,out] tensor Tensor to import memory to
[in] handle Backing memory to be imported
[in] type Type of the imported memory
Returns:
AclSuccess if function was completed successfully
AclInvalidArgument if a given argument is invalid
Definition at line 130 of file AclTensor.cpp.
 {
     using namespace arm_compute;
     auto       tensor = get_internal(external_tensor);
     StatusCode status = detail::validate_internal_tensor(tensor);
     ARM_COMPUTE_RETURN_CENUM_ON_FAILURE(status);
     status = tensor->import(handle, utils::as_enum<ImportMemoryType>(type));
     ARM_COMPUTE_RETURN_CENUM_ON_FAILURE(status);
     return AclSuccess;
 }
References AclSuccess, ARM_COMPUTE_RETURN_CENUM_ON_FAILURE, arm_compute::get_internal(), tensor, type, and arm_compute::detail::validate_internal_tensor().
Referenced by Tensor::import().
AclUnmapTensor()
AclStatus AclUnmapTensor (AclTensor tensor, void * handle)
Unmap the tensor's backing memory.
Parameters
[in] tensor tensor to unmap memory from
[in] handle Backing memory to be unmapped
Returns
Status code
Returns:
AclSuccess if function was completed successfully
AclInvalidArgument if a given argument is invalid
Definition at line 116 of file AclTensor.cpp.
 {
     ARM_COMPUTE_UNUSED(handle);
     using namespace arm_compute;
     auto       tensor = get_internal(external_tensor);
     StatusCode status = detail::validate_internal_tensor(tensor);
     ARM_COMPUTE_RETURN_CENUM_ON_FAILURE(status);
     status = tensor->unmap();
     return AclSuccess;
 }
References AclSuccess, ARM_COMPUTE_RETURN_CENUM_ON_FAILURE, ARM_COMPUTE_UNUSED, arm_compute::get_internal(), tensor, CLTensor::unmap(), and arm_compute::detail::validate_internal_tensor().
Referenced by Tensor::unmap().