Compute Library: DepthwiseDepthfirstCommon< TInput, TWeight, TOutput, TAccum, OutputStage > Class Template Reference
DepthwiseDepthfirstCommon< TInput, TWeight, TOutput, TAccum, OutputStage > Class Template Reference
#include <depthwise_depthfirst.hpp>
Public Member Functions
DepthwiseDepthfirstCommon (StratType *const strat, const DepthwiseArgs &args, const OutputStage &os)
DepthwiseDepthfirstCommon (DepthwiseDepthfirstCommon &)=delete
DepthwiseDepthfirstCommon & operator= (DepthwiseDepthfirstCommon &)=delete
size_t get_storage_size (void) const override
void pack_parameters (void *buffer, const void *biases, const void *weights, size_t ld_weight_col, size_t ld_weight_row) override
Public Member Functions inherited from DepthfirstDriver< TInput, TWeight, TOutput >
DepthfirstDriver (IDepthfirstStrategy *strategy, const DepthwiseArgs &args)
size_t get_working_size (unsigned int n_threads, unsigned int n_input_channels) const override final
Detailed Description
template<typename TInput, typename TWeight, typename TOutput, typename TAccum, typename OutputStage>
class arm_conv::depthwise::DepthwiseDepthfirstCommon< TInput, TWeight, TOutput, TAccum, OutputStage >
Definition at line 156 of file depthwise_depthfirst.hpp.
Constructor & Destructor Documentation
DepthwiseDepthfirstCommon() [1/2]
DepthwiseDepthfirstCommon (StratType *const strat, const DepthwiseArgs & args, const OutputStage & os) inline
Definition at line 166 of file depthwise_depthfirst.hpp.
   : DepthfirstDriver<TInput, TWeight, TOutput>(strat, args), m_os(os)
   {
   }
DepthwiseDepthfirstCommon() [2/2]
DepthwiseDepthfirstCommon (DepthwiseDepthfirstCommon< TInput, TWeight, TOutput, TAccum, OutputStage > &) delete
Member Function Documentation
get_storage_size()
size_t get_storage_size (void) const inline override
Definition at line 174 of file depthwise_depthfirst.hpp.
   {
     return reinterpret_cast<const StratType *>(this->m_strat.get())->
       get_storage_size(this->m_args);
   }
Referenced by DepthwiseDepthfirstCommon< TInput, TInput, TInput, typename DefaultTAccum< TInput >::Type, typename DefaultOutputStage< TInput >::Type >::get_storage_size().
operator=()
DepthwiseDepthfirstCommon& operator= (DepthwiseDepthfirstCommon< TInput, TWeight, TOutput, TAccum, OutputStage > &) delete
pack_parameters()
void pack_parameters (void * buffer, const void * biases, const void * weights, size_t ld_weight_col, size_t ld_weight_row) inline override
Definition at line 180 of file depthwise_depthfirst.hpp.
   {
     reinterpret_cast<const StratType *>(this->m_strat.get())->
       pack_parameters(this->m_args, buffer, biases, m_os, weights, ld_weight_col, ld_weight_row);
   }
Referenced by DepthwiseDepthfirstCommon< TInput, TInput, TInput, typename DefaultTAccum< TInput >::Type, typename DefaultOutputStage< TInput >::Type >::pack_parameters(), and DepthwiseDepthfirstGeneric< TInput, TWeight, TOutput, TAccum, OutputStage >::pack_parameters().
The documentation for this class was generated from the following file:
src/core/NEON/kernels/arm_conv/depthwise/depthwise_depthfirst.hpp