Compute Library: TensorInfo Class Reference
TensorInfo Class Reference final
Store the tensor's metadata.
#include <TensorInfo.h>
Public Member Functions
TensorInfo ()
Default constructor.
~TensorInfo ()=default
Default destructor.
TensorInfo (const ITensorInfo &info)
Allow instances of this class to be copy constructed.
TensorInfo (const TensorInfo &)
Allow instances of this class to be copy constructed.
TensorInfo & operator= (const TensorInfo &)=default
Allow instances of this class to be copied.
TensorInfo (TensorInfo &&)=default
Allow instances of this class to be move constructed.
TensorInfo & operator= (TensorInfo &&)=default
Allow instances of this class to be moved.
TensorInfo (Format format)
Construct a tensor info with a format.
TensorInfo (unsigned int width, unsigned int height, Format format)
2D tensor constructor
TensorInfo (const TensorShape &tensor_shape, Format format)
Constructor.
TensorInfo (size_t num_channels, DataType data_type)
Construct a tensor info with a data type and number of channels.
TensorInfo (const TensorShape &tensor_shape, size_t num_channels, DataType data_type)
Constructor.
TensorInfo (const TensorShape &tensor_shape, size_t num_channels, DataType data_type, DataLayout data_layout)
Constructor.
TensorInfo (const TensorShape &tensor_shape, size_t num_channels, DataType data_type, QuantizationInfo quantization_info)
Constructor.
void init (Format format)
Initialize the tensor info with just a format.
void init (const TensorShape &tensor_shape, Format format)
Initialize the metadata structure with the given parameters.
void init (const TensorShape &tensor_shape, Format format, const Strides &strides_in_bytes, size_t offset_first_element_in_bytes, size_t total_size_in_bytes)
Initialize the metadata structure with the given parameters.
void init (size_t num_channels, DataType data_type)
Initialize the tensor info with just a format.
void init (const TensorShape &tensor_shape, size_t num_channels, DataType data_type)
Initialize the metadata structure with the given parameters.
void init (const TensorShape &tensor_shape, size_t num_channels, DataType data_type, const Strides &strides_in_bytes, size_t offset_first_element_in_bytes, size_t total_size_in_bytes)
Initialize the metadata structure with the given parameters.
size_t init_auto_padding (const TensorShape &tensor_shape, Format format)
Initialize the metadata structure for the given tensor shape and single-plane format, (Padding is automatically calculated)
size_t init_auto_padding (const TensorShape &tensor_shape, size_t num_channels, DataType data_type)
Initialize the metadata structure for the given tensor shape, number of channels and data type.
std::unique_ptr< ITensorInfo > clone () const override
ITensorInfo & set_data_type (DataType data_type) override
Set the data type to the specified value.
ITensorInfo & set_num_channels (int num_channels) override
Set the number of channels to the specified value.
ITensorInfo & set_format (Format format) override
Set the format of an already initialized tensor.
ITensorInfo & set_tensor_shape (const TensorShape &shape) override
Set the shape of an already initialized tensor.
ITensorInfo & set_tensor_dims_state (const TensorDimsState &state) override
Set the state for each dimension of the tensor.
ITensorInfo & set_quantization_info (const QuantizationInfo &quantization_info) override
Set the quantization settings (scale and offset) of the tensor.
ITensorInfo & set_data_layout (const DataLayout &data_layout) override
Set the data layout of the tensor.
ITensorInfo & reset_padding () override
Resets the padding settings of the tensor.
bool auto_padding () override
Update the offset to the first element and the strides to automatically computed values.
ITensorInfo & set_lock_paddings (bool flag) override
Set the lock paddings flag of the tensor.
bool lock_paddings () const override
Get the lock paddings flag value.
bool extend_padding (const PaddingSize &padding) override
Update the offset to the first element, the strides and the total size.
size_t dimension (size_t index) const override
Return the size of the requested dimension.
size_t dimension (DataLayoutDimension dimension) const override
Return the size of the requested data layout dimension.
const Strides & strides_in_bytes () const override
The strides in bytes for accessing each dimension of the tensor.
size_t offset_first_element_in_bytes () const override
The offset from the beginning of the memory allocation to the first element of the tensor.
int32_t offset_element_in_bytes (const Coordinates &pos) const override
The offset in bytes from the beginning of the memory allocation to access the element at position (x, y, z ...)
size_t element_size () const override
Element size in bytes calculated as data_size() * num_channels()
size_t num_dimensions () const override
The number of dimensions of the tensor (rank)
size_t num_channels () const override
The number of channels for each tensor element.
const TensorShape & tensor_shape () const override
Size for each dimension of the tensor.
const TensorDimsState & tensor_dims_state () const override
State of each dimension of the tensor shape.
DataType data_type () const override
Data type used for each element of the tensor.
Format format () const override
Colour format of the image.
size_t total_size () const override
Returns the total size of the tensor in bytes.
PaddingSize padding () const override
Padding of tensor.
bool has_padding () const override
Checks if the tensor has been allocated with padding or not.
bool is_resizable () const override
Flag indicating whether the size of the tensor can be changed.
bool is_dynamic () const override
Flag indicating whether the shape of the tensor is dynamic, meaning that it can change on kernel/function execution.
bool are_values_constant () const override
Flag indicating whether the values of the tensor are constant, meaning that they can change on kernel/function execution.
ITensorInfo & set_is_resizable (bool is_resizable) override
Set the flag whether the tensor size can be changed.
ValidRegion valid_region () const override
Valid region of the tensor.
void set_valid_region (const ValidRegion &valid_region) override
Set the valid region of the tensor.
QuantizationInfo quantization_info () const override
Get the quantization settings (scale and offset) of the tensor.
DataLayout data_layout () const override
Get the data layout of the tensor.
ITensorInfo & set_are_values_constant (bool are_values_constant) override
Set the flag whether the tensor values can change during kernel/function execution.
ITensorInfo::Id id () const override
Get the workload tensor id of the tensor.
ITensorInfo & set_id (ITensorInfo::Id id) override
Set the tensor id.
Public Member Functions inherited from ITensorInfo
virtual ~ITensorInfo ()=default
Default virtual destructor.
bool has_valid_id () const
Check if the tensor id is valid.
Public Member Functions inherited from ICloneable< ITensorInfo >
virtual ~ICloneable ()=default
Default virtual desctructor.
virtual std::unique_ptr< ITensorInfo > clone () const=0
Provide a clone of the current object of class T.
Friends
bool operator== (const TensorInfo &lhs, const TensorInfo &rhs)
Check whether two tensor info are equal.
Additional Inherited Members
Public Types inherited from ITensorInfo
using TensorDimsState = std::vector< int >
using Id = int32_t
An id that uniquely identifies an ITensorInfo within some domain (e.g.
Static Public Member Functions inherited from ITensorInfo
static constexpr int32_t get_dynamic_state_value ()
Get the value representing dynamic dimension state.
static constexpr int32_t get_static_state_value ()
Get the value representing static dimension state.
template<typename... Infos>
static std::pair< TensorShape, ValidRegion > broadcast_shape_and_valid_region (const Infos &... infos)
If infos are broadcast compatible tensor info's, return the broadcasted shape and the intersection of the broadcasted valid regions of the tensors.
Static Public Attributes inherited from ITensorInfo
static constexpr Id invalid_tensor_id = 0
An invalid tensor id within a domain.
Detailed Description
Store the tensor's metadata.
Definition at line 43 of file TensorInfo.h.
Constructor & Destructor Documentation
TensorInfo() [1/11]
TensorInfo ()
Default constructor.
Definition at line 36 of file TensorInfo.cpp.
     : _total_size(0), _offset_first_element_in_bytes(0), _strides_in_bytes(), _num_channels(0), _tensor_shape(), _dims_state(), _data_type(DataType::UNKNOWN), _format(Format::UNKNOWN), _is_resizable{ true },
       _valid_region{ Coordinates(), _tensor_shape }, _padding{ 0 }, _quantization_info(), _data_layout(DataLayout::NCHW), _are_values_constant(true), _id(invalid_tensor_id), _lock_paddings(false)
 {
 }
~TensorInfo()
~TensorInfo () default
Default destructor.
TensorInfo() [2/11]
TensorInfo (const ITensorInfo & info)
Allow instances of this class to be copy constructed.
Definition at line 42 of file TensorInfo.cpp.
     : TensorInfo()
 {
     _total_size                    = info.total_size();
     _offset_first_element_in_bytes = info.offset_first_element_in_bytes();
     _strides_in_bytes              = info.strides_in_bytes();
     _num_channels                  = info.num_channels();
     _tensor_shape                  = info.tensor_shape();
     _dims_state                    = info.tensor_dims_state();
     _data_type                     = info.data_type();
     _format                        = info.format();
     _is_resizable                  = info.is_resizable();
     _valid_region                  = info.valid_region();
     _padding                       = info.padding();
     _quantization_info             = info.quantization_info();
     _data_layout                   = info.data_layout();
     _are_values_constant           = info.are_values_constant();
     _id                            = info.id();
     _lock_paddings                 = info.lock_paddings();
 }
References ScaleKernelInfo::data_layout, and arm_compute::test::validation::info.
TensorInfo() [3/11]
TensorInfo (const TensorInfo & info)
Allow instances of this class to be copy constructed.
Definition at line 63 of file TensorInfo.cpp.
     : TensorInfo()
 {
     _total_size                    = info.total_size();
     _offset_first_element_in_bytes = info.offset_first_element_in_bytes();
     _strides_in_bytes              = info.strides_in_bytes();
     _num_channels                  = info.num_channels();
     _tensor_shape                  = info.tensor_shape();
     _dims_state                    = info.tensor_dims_state();
     _data_type                     = info.data_type();
     _format                        = info.format();
     _is_resizable                  = info.is_resizable();
     _valid_region                  = info.valid_region();
     _padding                       = info.padding();
     _quantization_info             = info.quantization_info();
     _data_layout                   = info.data_layout();
     _are_values_constant           = info.are_values_constant();
     _id                            = info.id();
     _lock_paddings                 = false;
 }
References ScaleKernelInfo::data_layout, and arm_compute::test::validation::info.
TensorInfo() [4/11]
TensorInfo (TensorInfo &&) default
Allow instances of this class to be move constructed.
TensorInfo() [5/11]
TensorInfo (Format format)
Construct a tensor info with a format.
Can be used for automatic derivation of the shape by the function.
Parameters
[in] format Format of the tensor.
Definition at line 83 of file TensorInfo.cpp.
     : TensorInfo(TensorShape(), format)
 {
 }
TensorInfo() [6/11]
TensorInfo (unsigned int width, unsigned int height, Format format)
2D tensor constructor
Parameters
[in] width Width of the 2D tensor
[in] height Height of the 2D tensor
[in] format Single plane format of the tensor.
Definition at line 88 of file TensorInfo.cpp.
     : TensorInfo(TensorShape(width, height), format)
 {
 }
TensorInfo() [7/11]
TensorInfo (const TensorShape & tensor_shape, Format format)
Constructor.
Parameters
[in] tensor_shape It specifies the size for each dimension of the tensor in number of elements.
[in] format Single plane format of the tensor.
Definition at line 93 of file TensorInfo.cpp.
     : TensorInfo()
 {
     init(tensor_shape, format);
 }
References TensorInfo::format(), TensorInfo::init(), and TensorInfo::tensor_shape().
TensorInfo() [8/11]
TensorInfo (size_t num_channels, DataType data_type)
Construct a tensor info with a data type and number of channels.
Can be used for automatic derivation of the shape by the function.
Parameters
[in] num_channels It indicates the number of channels for each tensor element
[in] data_type Data type to use for each tensor element
Definition at line 99 of file TensorInfo.cpp.
     : TensorInfo()
 {
     init(TensorShape(), num_channels, data_type);
 }
References TensorInfo::data_type(), TensorInfo::init(), and TensorInfo::num_channels().
TensorInfo() [9/11]
TensorInfo (const TensorShape & tensor_shape, size_t num_channels, DataType data_type)
Constructor.
Parameters
[in] tensor_shape It specifies the size for each dimension of the tensor in number of elements.
[in] num_channels It indicates the number of channels for each tensor element
[in] data_type Data type to use for each tensor element
Definition at line 105 of file TensorInfo.cpp.
     : TensorInfo()
 {
     init(tensor_shape, num_channels, data_type);
 }
References TensorInfo::data_type(), TensorInfo::init(), TensorInfo::num_channels(), and TensorInfo::tensor_shape().
TensorInfo() [10/11]
TensorInfo (const TensorShape & tensor_shape, size_t num_channels, DataType data_type, DataLayout data_layout)
Constructor.
Parameters
[in] tensor_shape It specifies the size for each dimension of the tensor in number of elements.
[in] num_channels It indicates the number of channels for each tensor element
[in] data_type Data type to use for each tensor element
[in] data_layout The data layout setting for the tensor data.
Definition at line 118 of file TensorInfo.cpp.
     : TensorInfo()
 {
     init(tensor_shape, num_channels, data_type);
     _data_layout = data_layout;
 }
References TensorInfo::data_layout(), TensorInfo::data_type(), TensorInfo::init(), TensorInfo::num_channels(), and TensorInfo::tensor_shape().
TensorInfo() [11/11]
TensorInfo (const TensorShape & tensor_shape, size_t num_channels, DataType data_type, QuantizationInfo quantization_info)
Constructor.
Parameters
[in] tensor_shape It specifies the size for each dimension of the tensor in number of elements.
[in] num_channels It indicates the number of channels for each tensor element
[in] data_type Data type to use for each tensor element
[in] quantization_info The quantization settings for the tensor data.
Definition at line 111 of file TensorInfo.cpp.
     : TensorInfo()
 {
     init(tensor_shape, num_channels, data_type);
     _quantization_info = std::move(quantization_info);
 }
References TensorInfo::data_type(), TensorInfo::init(), TensorInfo::num_channels(), TensorInfo::quantization_info(), and TensorInfo::tensor_shape().
Member Function Documentation
are_values_constant()
bool are_values_constant () const inline override virtual
Flag indicating whether the values of the tensor are constant, meaning that they can change on kernel/function execution.
Returns
True if values are constant else false
Implements ITensorInfo.
Definition at line 272 of file TensorInfo.h.
     {
         return _are_values_constant;
     }
Referenced by TensorInfo::set_are_values_constant().
auto_padding()
bool auto_padding () override virtual
Update the offset to the first element and the strides to automatically computed values.
Note
The padding used by this method is really conservative so that the tensor can be used for most functions.
Returns
True if the strides or the offset to the first element have changed.
Implements ITensorInfo.
Definition at line 212 of file TensorInfo.cpp.
 {
     ARM_COMPUTE_ERROR_ON(!_is_resizable);
     // Some kernels compute 32 elements at the time, worst case scenario they
     // will read 32 values after the last element
     const size_t extra_pad_x = _tensor_shape.num_dimensions() < 1 ? 0 : 32;
     const size_t pad_x       = _tensor_shape.num_dimensions() < 1 ? 0 : 4;
     const size_t pad_y       = _tensor_shape.num_dimensions() < 2 ? 0 : 4;
     return extend_padding(PaddingSize(pad_y, pad_x + extra_pad_x, pad_y, pad_x));
 }
References ARM_COMPUTE_ERROR_ON, TensorInfo::extend_padding(), and Dimensions< T >::num_dimensions().
Referenced by TensorInfo::init_auto_padding().
clone()
std::unique_ptr< ITensorInfo > clone () const override
Definition at line 316 of file TensorInfo.cpp.
 {
     return std::make_unique<TensorInfo>(*this);
 }
Referenced by CLFFTConvolutionLayer::configure(), arm_compute::test::validation::TEST_CASE(), CPPSplit< CLSlice, ICLTensor >::validate(), NELSTMLayerQuantized::validate(), CLGEMMDeconvolutionLayer::validate(), and CLLSTMLayerQuantized::validate().
data_layout()
DataLayout data_layout () const inline override virtual
Get the data layout of the tensor.
Returns
A DataLayout containing the layout data information.
Implements ITensorInfo.
Definition at line 293 of file TensorInfo.h.
     {
         return _data_layout;
     }
Referenced by arm_compute::calculate_valid_region_scale(), CLAccessor::data_layout(), arm_compute::error_on_data_layout_not_in(), arm_compute::error_on_mismatching_data_layouts(), TensorInfo::set_data_layout(), and TensorInfo::TensorInfo().
data_type()
DataType data_type () const inline override virtual
Data type used for each element of the tensor.
Returns
Tensor data type
Implements ITensorInfo.
Definition at line 244 of file TensorInfo.h.
     {
         return _data_type;
     }
Referenced by CLLSTMLayer::configure(), CLAccessor::data_type(), arm_compute::error_on_data_type_not_in(), arm_compute::error_on_mismatching_data_types(), arm_compute::error_on_unsupported_cpu_bf16(), arm_compute::error_on_unsupported_cpu_fp16(), arm_compute::error_on_unsupported_fp16(), TensorInfo::init(), TensorInfo::init_auto_padding(), TensorInfo::set_data_type(), TensorInfo::TensorInfo(), NEQLSTMLayer::validate(), and CLQLSTMLayer::validate().
dimension() [1/2]
size_t dimension (DataLayoutDimension dimension) const inline override virtual
Return the size of the requested data layout dimension.
Parameters
[in] dimension DataLayoutDimension of the dimension
Returns
Dimension of the requested dimension
Implements ITensorInfo.
Definition at line 211 of file TensorInfo.h.
     {
         return get_data_layout_dimension_index(_data_layout, dimension);
     }
References TensorInfo::dimension(), and arm_compute::get_data_layout_dimension_index().
dimension() [2/2]
size_t dimension (size_t index) const inline override virtual
Return the size of the requested dimension.
Parameters
[in] index Index of the dimension
Returns
Dimension of the requested dimension
Implements ITensorInfo.
Definition at line 207 of file TensorInfo.h.
     {
         return _tensor_shape[index];
     }
Referenced by ITensor::copy_from(), TensorInfo::dimension(), and NEDeconvolutionLayer::validate().
element_size()
size_t element_size () const inline override virtual
Element size in bytes calculated as data_size() * num_channels()
Returns
The size of one element in bytes
Implements ITensorInfo.
Definition at line 224 of file TensorInfo.h.
     {
         return data_size_from_type(_data_type) * _num_channels;
     }
References arm_compute::data_size_from_type().
Referenced by ITensor::copy_from(), CLAccessor::element_size(), and CLQLSTMLayer::prepare().
extend_padding()
bool extend_padding (const PaddingSize & padding) override virtual
Update the offset to the first element, the strides and the total size.
Note
This function can only increase the offset, strides and total size.
Parameters
[in] padding Padding around the XY plane in number of elements.
Returns
True if the strides, offset and total size have changed.
Implements ITensorInfo.
Definition at line 280 of file TensorInfo.cpp.
 {
     ARM_COMPUTE_ERROR_ON(_lock_paddings);
     ARM_COMPUTE_ERROR_ON(!_is_resizable);
     bool updated = false;
     if(padding.top > _padding.top)
     {
         _padding.top = padding.top;
         updated      = true;
     }
     if(padding.right > _padding.right)
     {
         _padding.right = padding.right;
         updated        = true;
     }
     if(padding.bottom > _padding.bottom)
     {
         _padding.bottom = padding.bottom;
         updated         = true;
     }
     if(padding.left > _padding.left)
     {
         _padding.left = padding.left;
         updated       = true;
     }
     std::tie(_strides_in_bytes, _offset_first_element_in_bytes, _total_size) = calculate_padding_requirements(_padding);
     return updated;
 }
References ARM_COMPUTE_ERROR_ON, BorderSize::bottom, BorderSize::left, TensorInfo::padding(), BorderSize::right, and BorderSize::top.
Referenced by TensorInfo::auto_padding(), and CpuGemmConv2d::run().
format()
Format format () const inline override virtual
Colour format of the image.
Returns
Colour format of the image
Implements ITensorInfo.
Definition at line 248 of file TensorInfo.h.
     {
         return _format;
     }
Referenced by CLAccessor::format(), TensorAllocator::init(), TensorInfo::init(), TensorInfo::init_auto_padding(), TensorInfo::set_format(), and TensorInfo::TensorInfo().
has_padding()
bool has_padding () const inline override virtual
Checks if the tensor has been allocated with padding or not.
Returns
True if padding is allocated in the tensor, otherwise false.
Implements ITensorInfo.
Definition at line 260 of file TensorInfo.h.
     {
         return !_padding.empty();
     }
References BorderSize::empty().
id()
ITensorInfo::Id id () const inline override virtual
Get the workload tensor id of the tensor.
Returns
Workload tensor id of the tensor
Implements ITensorInfo.
Definition at line 302 of file TensorInfo.h.
     {
         return _id;
     }
Referenced by GpuWorkloadArgument::id(), GpuKernelArgument::id(), and TensorInfo::set_id().
init() [1/6]
void init (const TensorShape & tensor_shape, Format format)
Initialize the metadata structure with the given parameters.
Parameters
[in] tensor_shape Size for each dimension of the tensor in number of elements.
[in] format Single plane format of the tensor.
Definition at line 130 of file TensorInfo.cpp.
 {
     size_t         num_channels = num_channels_from_format(format);
     const DataType type         = data_type_from_format(format);
     init(tensor_shape, num_channels, type);
     _format = format;
 }
References arm_compute::data_type_from_format(), TensorInfo::format(), TensorInfo::init(), TensorInfo::num_channels(), arm_compute::num_channels_from_format(), TensorInfo::tensor_shape(), and type.
init() [2/6]
void init (const TensorShape & tensor_shape, Format format, const Strides & strides_in_bytes, size_t offset_first_element_in_bytes, size_t total_size_in_bytes)
Initialize the metadata structure with the given parameters.
Parameters
[in] tensor_shape Size for each dimension of the tensor in number of elements.
[in] format Single plane format of the tensor.
[in] strides_in_bytes Stride in bytes for accessing each dimension of the tensor.
[in] offset_first_element_in_bytes Offset in bytes from the beginning of memory allocation to access the first element.
[in] total_size_in_bytes Size in bytes of the memory allocation (including the offset to the first element).
Definition at line 140 of file TensorInfo.cpp.
 {
     size_t         num_channels = num_channels_from_format(format);
     const DataType type         = data_type_from_format(format);
     init(tensor_shape, num_channels, type, strides_in_bytes, offset_first_element_in_bytes, total_size_in_bytes);
     _format = format;
 }
References arm_compute::data_type_from_format(), TensorInfo::format(), TensorInfo::init(), TensorInfo::num_channels(), arm_compute::num_channels_from_format(), TensorInfo::offset_first_element_in_bytes(), TensorInfo::strides_in_bytes(), TensorInfo::tensor_shape(), and type.
init() [3/6]
void init (const TensorShape & tensor_shape, size_t num_channels, DataType data_type)
Initialize the metadata structure with the given parameters.
Parameters
[in] tensor_shape Size for each dimension of the tensor in number of elements.
[in] num_channels Desired number of channels for each tensor element.
[in] data_type Data type to use for each tensor element.
Definition at line 157 of file TensorInfo.cpp.
 {
     ARM_COMPUTE_ERROR_ON(num_channels == 0);
     _data_type    = data_type;
     _num_channels = num_channels;
     _format       = Format::UNKNOWN;
     set_tensor_shape(tensor_shape);
 }
References ARM_COMPUTE_ERROR_ON, TensorInfo::data_type(), TensorInfo::num_channels(), TensorInfo::set_tensor_shape(), TensorInfo::tensor_shape(), and arm_compute::UNKNOWN.
init() [4/6]
void init (const TensorShape & tensor_shape, size_t num_channels, DataType data_type, const Strides & strides_in_bytes, size_t offset_first_element_in_bytes, size_t total_size_in_bytes)
Initialize the metadata structure with the given parameters.
Parameters
[in] tensor_shape Size for each dimension of the tensor in number of elements.
[in] num_channels Desired number of channels for each tensor element.
[in] data_type Data type to use for each tensor element.
[in] strides_in_bytes Stride in bytes for accessing each dimension of the tensor.
[in] offset_first_element_in_bytes Offset in bytes from the beginning of memory allocation to access the first element.
[in] total_size_in_bytes Size in bytes of the memory allocation (including the offset to the first element).
Definition at line 168 of file TensorInfo.cpp.
 {
     ARM_COMPUTE_ERROR_ON(num_channels == 0);
     _data_type                     = data_type;
     _num_channels                  = num_channels;
     _format                        = Format::UNKNOWN;
     _tensor_shape                  = tensor_shape;
     _offset_first_element_in_bytes = offset_first_element_in_bytes;
     _strides_in_bytes              = strides_in_bytes;
     _total_size                    = total_size_in_bytes;
     _valid_region = ValidRegion{ Coordinates(), _tensor_shape };
 }
References ARM_COMPUTE_ERROR_ON, TensorInfo::data_type(), TensorInfo::num_channels(), TensorInfo::offset_first_element_in_bytes(), TensorInfo::strides_in_bytes(), TensorInfo::tensor_shape(), and arm_compute::UNKNOWN.
init() [5/6]
void init (Format format)
Initialize the tensor info with just a format.
Can be used for automatic derivation of the shape by the function.
Parameters
[in] format Single plane format of the tensor.
Definition at line 125 of file TensorInfo.cpp.
 {
     init(TensorShape(), format);
 }
References TensorInfo::format().
Referenced by CpuWinogradConv2d::configure(), arm_compute::detail::convert_to_legacy_tensor_info(), TensorAllocator::init(), TensorInfo::init(), and TensorInfo::TensorInfo().
init() [6/6]
void init (size_t num_channels, DataType data_type)
Initialize the tensor info with just a format.
Can be used for automatic derivation of the shape by the function.
Parameters
[in] num_channels Desired number of channels for each tensor element.
[in] data_type Data type to use for each tensor element.
Definition at line 152 of file TensorInfo.cpp.
 {
     init(TensorShape(), num_channels, data_type);
 }
References TensorInfo::data_type(), TensorInfo::init(), and TensorInfo::num_channels().
init_auto_padding() [1/2]
size_t init_auto_padding (const TensorShape & tensor_shape, Format format)
Initialize the metadata structure for the given tensor shape and single-plane format, (Padding is automatically calculated)
Note
The padding used by this method is really conservative so that the tensor can be used for most functions.
Parameters
[in] tensor_shape It specifies the size for each dimension of the tensor in number of elements
[in] format Single plane format of the image.
Returns
Total allocation size including padding in bytes.
Definition at line 185 of file TensorInfo.cpp.
 {
     const size_t   num_channels = num_channels_from_format(format);
     const DataType type         = data_type_from_format(format);
     size_t         total_size   = init_auto_padding(tensor_shape, num_channels, type);
     _format = format;
     return total_size;
 }
References arm_compute::data_type_from_format(), TensorInfo::format(), TensorInfo::num_channels(), arm_compute::num_channels_from_format(), TensorInfo::tensor_shape(), TensorInfo::total_size(), and type.
init_auto_padding() [2/2]
size_t init_auto_padding (const TensorShape & tensor_shape, size_t num_channels, DataType data_type)
Initialize the metadata structure for the given tensor shape, number of channels and data type.
(Padding is automatically calculated)
Note
The padding used by this method is really conservative so that the tensor can be used for most functions.
Parameters
[in] tensor_shape It specifies the size for each dimension of the tensor in number of elements
[in] num_channels It indicates the number of channels for each tensor element
[in] data_type Data type to use for each tensor element
Returns
Total allocation size including padding in bytes.
Definition at line 196 of file TensorInfo.cpp.
 {
     ARM_COMPUTE_ERROR_ON(num_channels == 0);
     _data_type    = data_type;
     _num_channels = num_channels;
     _format       = Format::UNKNOWN;
     _tensor_shape = tensor_shape;
     _valid_region = ValidRegion{ Coordinates(), _tensor_shape };
     auto_padding();
     return _total_size;
 }
References ARM_COMPUTE_ERROR_ON, TensorInfo::auto_padding(), TensorInfo::data_type(), TensorInfo::num_channels(), TensorInfo::tensor_shape(), and arm_compute::UNKNOWN.
is_dynamic()
bool is_dynamic () const inline override virtual
Flag indicating whether the shape of the tensor is dynamic, meaning that it can change on kernel/function execution.
Returns
True if its dynamic else false
Implements ITensorInfo.
Definition at line 268 of file TensorInfo.h.
     {
         return std::find(std::cbegin(_dims_state), std::cend(_dims_state), get_dynamic_state_value()) != std::cend(_dims_state);
     }
References ITensorInfo::get_dynamic_state_value().
is_resizable()
bool is_resizable () const inline override virtual
Flag indicating whether the size of the tensor can be changed.
Returns
True if the tensor size can be changed.
Implements ITensorInfo.
Definition at line 264 of file TensorInfo.h.
     {
         return _is_resizable;
     }
Referenced by TensorInfo::set_is_resizable(), and arm_compute::test::validation::TEST_CASE().
lock_paddings()
bool lock_paddings () const override virtual
Get the lock paddings flag value.
Returns
lock paddings flag value
Implements ITensorInfo.
Definition at line 275 of file TensorInfo.cpp.
 {
     return _lock_paddings;
 }
num_channels()
size_t num_channels () const inline override virtual
The number of channels for each tensor element.
Returns
The number of channels for each tensor element
Implements ITensorInfo.
Definition at line 232 of file TensorInfo.h.
     {
         return _num_channels;
     }
Referenced by ITensor::copy_from(), arm_compute::error_on_data_type_channel_not_in(), TensorInfo::init(), TensorInfo::init_auto_padding(), CLAccessor::num_channels(), TensorInfo::set_num_channels(), and TensorInfo::TensorInfo().
num_dimensions()
size_t num_dimensions () const inline override virtual
The number of dimensions of the tensor (rank)
Returns
The number of dimensions of the tensor (rank)
Implements ITensorInfo.
Definition at line 228 of file TensorInfo.h.
     {
         return _tensor_shape.num_dimensions();
     }
References Dimensions< T >::num_dimensions().
Referenced by ITensor::copy_from().
offset_element_in_bytes()
int32_t offset_element_in_bytes (const Coordinates & pos) const override virtual
The offset in bytes from the beginning of the memory allocation to access the element at position (x, y, z ...)
Parameters
[in] pos Vector with the coordinates of the element to access. The size of this vector must be equal to the number of dimensions of the tensor
Returns
Offset in bytes from the beginning of the memory allocation to access the element (x, y, z, ...)
Implements ITensorInfo.
Definition at line 402 of file TensorInfo.cpp.
 {
     ARM_COMPUTE_ERROR_ON_COORDINATES_DIMENSIONS_GTE(pos, _tensor_shape.num_dimensions());
     int32_t offset = _offset_first_element_in_bytes;
     for(size_t i = 0; i < _tensor_shape.num_dimensions(); ++i)
     {
         offset += pos[i] * _strides_in_bytes[i];
     }
     return offset;
 }
References ARM_COMPUTE_ERROR_ON_COORDINATES_DIMENSIONS_GTE, Dimensions< T >::num_dimensions(), and offset().
Referenced by TensorAllocator::init().
offset_first_element_in_bytes()
size_t offset_first_element_in_bytes () const inline override virtual
The offset from the beginning of the memory allocation to the first element of the tensor.
This can be used to access efficiently elements in a 2D tensor
Returns
The offset in bytes to access the first element of the tensor.
Implements ITensorInfo.
Definition at line 219 of file TensorInfo.h.
     {
         return _offset_first_element_in_bytes;
     }
Referenced by TensorAllocator::init(), and TensorInfo::init().
operator=() [1/2]
TensorInfo& operator= (const TensorInfo &) default
Allow instances of this class to be copied.
operator=() [2/2]
TensorInfo& operator= (TensorInfo &&) default
Allow instances of this class to be moved.
padding()
PaddingSize padding () const inline override virtual
Padding of tensor.
Returns
Padding.
Implements ITensorInfo.
Definition at line 256 of file TensorInfo.h.
     {
         return _padding;
     }
Referenced by TensorInfo::extend_padding(), arm_compute::get_padding_info(), and CLAccessor::padding().
quantization_info()
QuantizationInfo quantization_info () const inline override virtual
Get the quantization settings (scale and offset) of the tensor.
Returns
A QuantizationInfo containing the scale and offset.
Implements ITensorInfo.
Definition at line 289 of file TensorInfo.h.
     {
         return _quantization_info;
     }
Referenced by CpuGemmLowpMatrixMultiplyCore::configure(), CLQLSTMLayer::configure(), CLAccessor::quantization_info(), TensorInfo::set_quantization_info(), and TensorInfo::TensorInfo().
reset_padding()
ITensorInfo & reset_padding () override virtual
Resets the padding settings of the tensor.
Returns
Reference to this ITensorInfo object
Implements ITensorInfo.
Definition at line 392 of file TensorInfo.cpp.
 {
     _padding = PaddingSize();
     if(((_format != Format::UNKNOWN) || (_data_type != DataType::UNKNOWN)) && _total_size != 0)
     {
         std::tie(_strides_in_bytes, _offset_first_element_in_bytes, _total_size) = calculate_padding_requirements(_padding);
     }
     return *this;
 }
References arm_compute::UNKNOWN.
set_are_values_constant()
ITensorInfo& set_are_values_constant (bool are_values_constant) inline override virtual
Set the flag whether the tensor values can change during kernel/function execution.
Parameters
[in] are_values_constant Flag that marks the tensor values if they can be changed or not.
Returns
Reference to this ITensorInfo object
Implements ITensorInfo.
Definition at line 297 of file TensorInfo.h.
     {
         _are_values_constant = are_values_constant;
         return *this;
     }
References TensorInfo::are_values_constant().
Referenced by CpuFullyConnected::configure().
set_data_layout()
ITensorInfo & set_data_layout (const DataLayout & data_layout) override virtual
Set the data layout of the tensor.
Parameters
[in] data_layout DataLayout containing the layout data information.
Returns
Reference to this ITensorInfo object
Implements ITensorInfo.
Definition at line 386 of file TensorInfo.cpp.
 {
     _data_layout = data_layout;
     return *this;
 }
References TensorInfo::data_layout().
Referenced by NECropResize::configure(), CLDepthwiseConvolutionLayer::configure(), CLCropResize::configure(), CLFFTConvolutionLayer::configure(), NEDeconvolutionLayer::configure(), CLDirectDeconvolutionLayer::configure(), and NEQLSTMLayer::configure().
set_data_type()
ITensorInfo & set_data_type (DataType data_type) override virtual
Set the data type to the specified value.
Warning
This resets the format to UNKNOWN.
Parameters
[in] data_type The new data type.
Returns
Reference to this ITensorInfo object
Implements ITensorInfo.
Definition at line 321 of file TensorInfo.cpp.
 {
     _data_type = data_type;
     _format    = Format::UNKNOWN;
     return set_tensor_shape(tensor_shape()); // Force total size and strides to update
 }
References TensorInfo::data_type(), TensorInfo::set_tensor_shape(), TensorInfo::tensor_shape(), and arm_compute::UNKNOWN.
Referenced by CLReduceMean::configure(), ClGemmLowpMatrixMultiplyCore::configure(), CpuLogits1DSoftmaxKernel< IS_LOG >::configure(), CpuGemmConv2d::configure(), NEL2NormalizeLayer::validate(), NEReductionOperation::validate(), CLL2NormalizeLayer::validate(), CLArgMinMaxLayer::validate(), CLReductionOperation::validate(), NEGenerateProposalsLayer::validate(), CLGenerateProposalsLayer::validate(), and CLGEMMDeconvolutionLayer::validate().
set_format()
ITensorInfo & set_format (Format format) override virtual
Set the format of an already initialized tensor.
Note
If the data type has already been configured (i.e. not UNKNOWN) it must match the new format. If data type hasn't been configured it will be based on the format.
Parameters
[in] format Single-plane format of the tensor.
Returns
Reference to this ITensorInfo object
Implements ITensorInfo.
Definition at line 335 of file TensorInfo.cpp.
 {
     _format = format;
     if(_data_type == DataType::UNKNOWN)
     {
         _num_channels = num_channels_from_format(format);
         _data_type    = data_type_from_format(format);
     }
     else
     {
         ARM_COMPUTE_ERROR_ON(num_channels_from_format(format) != _num_channels);
         ARM_COMPUTE_ERROR_ON(data_type_from_format(format) != _data_type);
     }
     return *this;
 }
References ARM_COMPUTE_ERROR_ON, arm_compute::data_type_from_format(), TensorInfo::format(), arm_compute::num_channels_from_format(), and arm_compute::UNKNOWN.
set_id()
ITensorInfo& set_id (ITensorInfo::Id id) inline override virtual
Set the tensor id.
Implements ITensorInfo.
Definition at line 306 of file TensorInfo.h.
     {
         _id = id;
         return *this;
     }
References TensorInfo::id().
set_is_resizable()
ITensorInfo& set_is_resizable (bool is_resizable) inline override virtual
Set the flag whether the tensor size can be changed.
Parameters
[in] is_resizable Flag that marks the tensor if it can be changed or not.
Returns
Reference to this ITensorInfo object
Implements ITensorInfo.
Definition at line 276 of file TensorInfo.h.
     {
         _is_resizable = is_resizable;
         return *this;
     }
References TensorInfo::is_resizable().
Referenced by TensorAllocator::allocate(), CLTensorAllocator::allocate(), CpuContext::create_activation(), ClContext::create_activation(), TensorAllocator::free(), CLTensorAllocator::free(), TensorAllocator::import_memory(), CLTensorAllocator::import_memory(), and TensorAllocator::~TensorAllocator().
set_lock_paddings()
ITensorInfo & set_lock_paddings (bool flag) override virtual
Set the lock paddings flag of the tensor.
It should be set to True, when the tensor could be mapped to camera or frame buffer.
Returns
Reference to this ITensorInfo object
Implements ITensorInfo.
Definition at line 269 of file TensorInfo.cpp.
 {
     _lock_paddings = flag;
     return *this;
 }
set_num_channels()
ITensorInfo & set_num_channels (int num_channels) override virtual
Set the number of channels to the specified value.
Warning
This resets the format to UNKNOWN.
Parameters
[in] num_channels New number of channels.
Returns
Reference to this ITensorInfo object
Implements ITensorInfo.
Definition at line 328 of file TensorInfo.cpp.
 {
     _num_channels = num_channels;
     _format       = Format::UNKNOWN;
     return *this;
 }
References TensorInfo::num_channels(), and arm_compute::UNKNOWN.
set_quantization_info()
ITensorInfo & set_quantization_info (const QuantizationInfo & quantization_info) override virtual
Set the quantization settings (scale and offset) of the tensor.
Parameters
[in] quantization_info QuantizationInfo containing the scale and offset
Returns
Reference to this ITensorInfo object
Implements ITensorInfo.
Definition at line 380 of file TensorInfo.cpp.
 {
     _quantization_info = quantization_info;
     return *this;
 }
References TensorInfo::quantization_info().
Referenced by CLDepthwiseConvolutionLayer::configure(), CpuLogits1DSoftmaxKernel< IS_LOG >::configure(), ClGemmConv2d::configure(), CpuGemmConv2d::configure(), CLGEMMDeconvolutionLayer::configure(), CLLSTMLayerQuantized::configure(), NELSTMLayerQuantized::validate(), and CLLSTMLayerQuantized::validate().
set_tensor_dims_state()
ITensorInfo & set_tensor_dims_state (const TensorDimsState & state) override virtual
Set the state for each dimension of the tensor.
This sets the state of each dimension of the shape in terms of dynamic behavior using -1 where appropriate. The index in the state is a 1 to 1 mapping with the shape dimension index. For example if you want to express [?, 3, 3] as a dynamic input then [-1, 3, 3] has to be set as a state
Parameters
[in] state Tensor dimensions state
Returns
Reference to this ITensorInfo object
Implements ITensorInfo.
Definition at line 374 of file TensorInfo.cpp.
 {
     _dims_state = state;
     return *this;
 }
set_tensor_shape()
ITensorInfo & set_tensor_shape (const TensorShape & shape) override virtual
Set the shape of an already initialized tensor.
Warning
Changing the shape requires to recompute the strides and is therefore only possible if the tensor hasn't been allocated yet.
Parameters
[in] shape New tensor shape.
Returns
Reference to this ITensorInfo object
Implements ITensorInfo.
Definition at line 352 of file TensorInfo.cpp.
 {
     _tensor_shape                  = shape;
     _offset_first_element_in_bytes = 0;
     _strides_in_bytes              = compute_strides(*this);
     if(_tensor_shape.num_dimensions() == 0)
     {
         _total_size = _strides_in_bytes[0];
     }
     else
     {
         const unsigned int idx_last_dimension = _tensor_shape.num_dimensions() - 1;
         _total_size                           = static_cast<size_t>(_tensor_shape[idx_last_dimension]) * _strides_in_bytes[idx_last_dimension];
     }
     std::tie(_strides_in_bytes, _offset_first_element_in_bytes, _total_size) = calculate_padding_requirements(_padding);
     _valid_region = ValidRegion{ Coordinates(), _tensor_shape };
     return *this;
 }
References arm_compute::compute_strides(), Dimensions< T >::num_dimensions(), and arm_compute::test::validation::shape.
Referenced by CpuMatMul::configure(), NEQLSTMLayer::configure(), CLQLSTMLayer::configure(), TensorInfo::init(), TensorInfo::set_data_type(), NEL2NormalizeLayer::validate(), CLL2NormalizeLayer::validate(), CLDepthwiseConvolutionLayer::validate(), NEQLSTMLayer::validate(), and CLQLSTMLayer::validate().
set_valid_region()
void set_valid_region (const ValidRegion & valid_region) inline override virtual
Set the valid region of the tensor.
Parameters
[in] valid_region Valid region to set.
Implements ITensorInfo.
Definition at line 285 of file TensorInfo.h.
     {
         _valid_region = valid_region;
     }
References TensorInfo::valid_region().
strides_in_bytes()
const Strides& strides_in_bytes () const inline override virtual
The strides in bytes for accessing each dimension of the tensor.
Returns
Strides in bytes for each tensor dimension
Implements ITensorInfo.
Definition at line 215 of file TensorInfo.h.
     {
         return _strides_in_bytes;
     }
Referenced by TensorAllocator::init(), and TensorInfo::init().
tensor_dims_state()
const TensorDimsState& tensor_dims_state () const inline override virtual
State of each dimension of the tensor shape.
Returns
A vector with the state for each dimension of the tensor, where -1 specifies dynamic dimension
Implements ITensorInfo.
Definition at line 240 of file TensorInfo.h.
     {
         return _dims_state;
     }
tensor_shape()
const TensorShape& tensor_shape () const inline override virtual
Size for each dimension of the tensor.
Returns
A vector with the size for each dimension of the tensor
Implements ITensorInfo.
Definition at line 236 of file TensorInfo.h.
     {
         return _tensor_shape;
     }
Referenced by arm_compute::calculate_valid_region_scale(), CpuMatMul::configure(), ClGemmConv2d::configure(), CpuGemmConv2d::configure(), CLFFTConvolutionLayer::configure(), CLGenerateProposalsLayer::configure(), CLLSTMLayerQuantized::configure(), NEQLSTMLayer::configure(), CLLSTMLayer::configure(), CLQLSTMLayer::configure(), ITensor::copy_from(), TensorAllocator::init(), TensorInfo::init(), TensorInfo::init_auto_padding(), CLAccessor::num_elements(), CpuElementwiseUnary::run(), TensorInfo::set_data_type(), CLAccessor::shape(), TensorInfo::TensorInfo(), CPPSplit< CLSlice, ICLTensor >::validate(), NELSTMLayerQuantized::validate(), and CLLSTMLayerQuantized::validate().
total_size()
size_t total_size () const inline override virtual
Returns the total size of the tensor in bytes.
Returns
Total size of the tensor in bytes.
Implements ITensorInfo.
Definition at line 252 of file TensorInfo.h.
     {
         return _total_size;
     }
Referenced by TensorAllocator::allocate(), CpuAddMulAdd::configure(), ClSoftmax::configure(), CpuWinogradConv2d::configure(), ClFullyConnected::configure(), CpuFullyConnected::configure(), ClGemmLowpMatrixMultiplyCore::configure(), ClWinogradConv2d::configure(), ClGemmConv2d::configure(), CpuGemmConv2d::configure(), CpuGemmLowpMatrixMultiplyCore::configure(), TensorAllocator::init(), TensorInfo::init_auto_padding(), CLQLSTMLayer::prepare(), and CLAccessor::size().
valid_region()
ValidRegion valid_region () const inline override virtual
Valid region of the tensor.
All elements in the valid region have defined values, i.e. are not undefined.
Returns
The valid region.
Implements ITensorInfo.
Definition at line 281 of file TensorInfo.h.
     {
         return _valid_region;
     }
Referenced by arm_compute::calculate_valid_region_scale(), ITensor::copy_from(), and TensorInfo::set_valid_region().
Friends And Related Function Documentation
operator==
bool operator== (const TensorInfo & lhs, const TensorInfo & rhs) friend
Check whether two tensor info are equal.
Parameters
[in] lhs LHS tensor info.
[in] rhs RHS tensor info.
Returns
True if the given tensor infos are the same.
Definition at line 345 of file TensorInfo.h.
 {
     return (lhs._total_size == rhs._total_size) && (lhs._offset_first_element_in_bytes == rhs._offset_first_element_in_bytes) && (lhs._strides_in_bytes == rhs._strides_in_bytes)
            && (lhs._num_channels == rhs._num_channels) && (lhs._tensor_shape == rhs._tensor_shape) && (lhs._dims_state == rhs._dims_state) && (lhs._data_type == rhs._data_type) && (lhs._format == rhs._format)
            && (lhs._is_resizable == rhs._is_resizable) && (lhs._valid_region == rhs._valid_region) && (lhs._padding == rhs._padding) && (lhs._quantization_info == rhs._quantization_info)
            && (lhs._data_layout == rhs._data_layout) && (lhs._are_values_constant == rhs._are_values_constant)
            && (lhs._id == rhs._id);
 }
The documentation for this class was generated from the following files:
arm_compute/core/TensorInfo.h
src/core/TensorInfo.cpp