Compute Library: GpuOperatorGroup Class Reference
GpuOperatorGroup Class Reference
A linear sequence of operators to be fused in a workload For the time being, this class is only used for validating operator fusion INVARIANTS:
#include <GpuOperatorGroup.h>
Public Member Functions
bool try_add_operator (const Operator &op, bool is_output=false) const
Try adding (without actually adding) an operator to the group.
void add_operator (const Operator &op, bool is_output=false)
Add an operator to the group.
Operator new_operator (const GpuOperatorType &operator_type, const ArgumentPack< ITensorInfo > &tensors) const
Create a new operator.
const Operator * get_root_operator () const
Get the "root operator" of the group, which is the first operator in a linear sequence.
Static Public Attributes
static constexpr size_t max_fused_operators = 32
Detailed Description
A linear sequence of operators to be fused in a workload For the time being, this class is only used for validating operator fusion INVARIANTS:
Note
These invariants are exactly the same as operator fusion constraints
Fusion is limited to a linear sequence of operators
Max number of operators that can be fused is GpuOperatorGroup::max_fused_operators
The fusion is subject to the pattern: Complex + Simple * | Simple + Simple * | Un-fusable
All operator but unfusable, have exactly 1 dst tensor
All fused operators share the same dst tensor shape
All fused operators' tensors share the same DataLayout
Definition at line 74 of file GpuOperatorGroup.h.
Member Function Documentation
add_operator()
void add_operator (const Operator & op, bool is_output = false)
Add an operator to the group.
Parameters
[in] op Operator to be added
[in] is_output Whether this operator is the output operator.
Definition at line 146 of file GpuOperatorGroup.cpp.
 {
     ARM_COMPUTE_ERROR_ON(!try_add_operator(op, is_output));
     const auto src_tensor_ids = get_tensor_ids(op.tensors().get_const_src_tensors());
     const auto dst_tensor_ids = get_tensor_ids(op.tensors().get_const_dst_tensors());
     _graph.add_operator_as_linear(op.id(), src_tensor_ids, dst_tensor_ids, is_output);
     _operators[op.id()] = op;
 }
References DependencyGraph::add_operator_as_linear(), ARM_COMPUTE_ERROR_ON, Operator::id(), Operator::tensors(), and GpuOperatorGroup::try_add_operator().
get_root_operator()
const Operator * get_root_operator () const
Get the "root operator" of the group, which is the first operator in a linear sequence.
Returns
const Operator* Pointer to the root operator
Definition at line 159 of file GpuOperatorGroup.cpp.
 {
     const auto roots = _graph.get_root_ops();
     ARM_COMPUTE_ERROR_ON(roots.size() > 1);
     if(roots.empty())
     {
         return nullptr;
     }
     return &_operators.at(roots[0]);
 }
References ARM_COMPUTE_ERROR_ON, and DependencyGraph::get_root_ops().
Referenced by GpuOperatorGroup::try_add_operator().
new_operator()
Operator new_operator (const GpuOperatorType & operator_type, const ArgumentPack< ITensorInfo > & tensors) const
Create a new operator.
Parameters
[in] operator_type GpuOperatorType of the new operator
[in] tensors Tensor arguments to the new operator
Returns
Operator
Definition at line 154 of file GpuOperatorGroup.cpp.
 {
     auto new_id = static_cast<OperatorId>(_operators.size());
     return Operator{ new_id, operator_type, tensors };
 }
try_add_operator()
bool try_add_operator (const Operator & op, bool is_output = false) const
Try adding (without actually adding) an operator to the group.
Parameters
[in] op Operator to be added
[in] is_output Whether this operator is the output operator.
Returns
true If op can be added while maintaining the invariants
false Otherwise
Definition at line 71 of file GpuOperatorGroup.cpp.
 {
     const auto src_tensor_ids = get_tensor_ids(op.tensors().get_const_src_tensors());
     const auto dst_tensor_ids = get_tensor_ids(op.tensors().get_const_dst_tensors());
     // Constraint 1
     if(!_graph.try_add_operator_as_linear(op.id(), src_tensor_ids, dst_tensor_ids, is_output))
     {
         return false;
     }
     // Constraint 2
     if(_operators.size() >= max_fused_operators)
     {
         return false;
     }
     // Constraint 3.1: Pattern: (Unfusable)
     if(_operators.size() > 0 && get_root_operator()->operator_type() == GpuOperatorType::Unfusable)
     {
         return false;
     }
     // Constraint 3.2
     if(_operators.size() > 0 && (op.operator_type() != GpuOperatorType::Simple))
     {
         return false;
     }
     // Constraint 4
     if(op.operator_type() != GpuOperatorType::Unfusable && op.tensors().get_const_dst_tensors().size() != 1U)
     {
         return false;
     }
     // Constraint 5
     if(_operators.size() > 0)
     {
         const auto root_dst_tensors = get_root_operator()->tensors().get_const_dst_tensors();
         ARM_COMPUTE_ERROR_ON(root_dst_tensors.empty());
         const auto first_dst_tensor = root_dst_tensors[0];
         const auto dst_tensors      = op.tensors().get_const_dst_tensors();
         for(const auto &t : root_dst_tensors)
         {
             if(detail::have_different_dimensions(t->tensor_shape(), first_dst_tensor->tensor_shape(), 0))
             {
                 return false;
             }
         }
         for(const auto &t : dst_tensors)
         {
             if(detail::have_different_dimensions(t->tensor_shape(), first_dst_tensor->tensor_shape(), 0))
             {
                 return false;
             }
         }
     }
     // Constraint 6
     if(_operators.size() > 0)
     {
         const auto root_dst_tensors = get_root_operator()->tensors().get_const_dst_tensors();
         ARM_COMPUTE_ERROR_ON(root_dst_tensors.empty());
         const auto first_dst_tensor_layout = root_dst_tensors[0]->data_layout();
         const auto dst_tensors             = op.tensors().get_const_dst_tensors();
         for(const auto &t : root_dst_tensors)
         {
             if(t->data_layout() != first_dst_tensor_layout)
             {
                 return false;
             }
         }
         for(const auto &t : dst_tensors)
         {
             if(t->data_layout() != first_dst_tensor_layout)
             {
                 return false;
             }
         }
     }
     return true;
 }
References ARM_COMPUTE_ERROR_ON, GpuOperatorGroup::get_root_operator(), arm_compute::detail::have_different_dimensions(), Operator::id(), GpuOperatorGroup::max_fused_operators, Operator::operator_type(), arm_compute::experimental::dynamic_fusion::Simple, tf_frozen_model_extractor::t, Operator::tensors(), DependencyGraph::try_add_operator_as_linear(), arm_compute::utils::cast::U, and arm_compute::experimental::dynamic_fusion::Unfusable.
Referenced by GpuOperatorGroup::add_operator().
Field Documentation
max_fused_operators
constexpr size_t max_fused_operators = 32 static constexpr
Definition at line 77 of file GpuOperatorGroup.h.
Referenced by GpuOperatorGroup::try_add_operator().
The documentation for this class was generated from the following files:
src/dynamic_fusion/sketch/gpu/GpuOperatorGroup.h
src/dynamic_fusion/sketch/gpu/GpuOperatorGroup.cpp