Compute Library: CpuCol2ImKernel Class Reference
CpuCol2ImKernel Class Reference
Kernel to perform col2im reshaping.
#include <CpuCol2ImKernel.h>
Public Member Functions
CpuCol2ImKernel ()=default
Default constructor.
ARM_COMPUTE_DISALLOW_COPY_ALLOW_MOVE (CpuCol2ImKernel)
void configure (const ITensorInfo *src, ITensorInfo *dst, const Size2D &convolved_dims)
Set the input and output of the kernel.
void run_op (ITensorPack &tensors, const Window &window, const ThreadInfo &info) override
Execute the kernel on the passed window.
const char * name () const override
Name of the kernel.
Public Member Functions inherited from ICPPKernel
virtual ~ICPPKernel ()=default
Default destructor.
virtual void run (const Window &window, const ThreadInfo &info)
Execute the kernel on the passed window.
virtual void run_nd (const Window &window, const ThreadInfo &info, const Window &thread_locator)
legacy compatibility layer for implemantions which do not support thread_locator In these cases we simply narrow the interface down the legacy version
virtual size_t get_mws (const CPUInfo &platform, size_t thread_count) const
Return minimum workload size of the relevant kernel.
Public Member Functions inherited from IKernel
IKernel ()
Constructor.
virtual ~IKernel ()=default
Destructor.
virtual bool is_parallelisable () const
Indicates whether or not the kernel is parallelisable.
virtual BorderSize border_size () const
The size of the border for that kernel.
const Window & window () const
The maximum window the kernel can be executed on.
bool is_window_configured () const
Function to check if the embedded window of this kernel has been configured.
Static Public Member Functions
static Status validate (const ITensorInfo *src, const ITensorInfo *dst, const Size2D &convolved_dims)
Static function to check if given info will lead to a valid configuration.
Static Public Member Functions inherited from ICpuKernel< CpuCol2ImKernel >
static const auto * get_implementation (const SelectorType &selector, KernelSelectionType selection_type=KernelSelectionType::Supported)
Micro-kernel selector.
Additional Inherited Members
Static Public Attributes inherited from ICPPKernel
static constexpr size_t default_mws = 1
Detailed Description
Kernel to perform col2im reshaping.
Rearranges each matrix column into image blocks. It's the inverse operation of CpuIm2ColKernel.
For example, a vector of 9 elements can be reshaped to a block(image) of 3x3:
\[ \left(\begin{array}{ccccccccc} a0 & a1 & a2 & a3 & a4 & a5 & a6 & a7 & a8 \\ \end{array} \right) \rightarrow \left(\begin{array}{ccc} a0 & a1 & a2 \\ a3 & a4 & a5 \\ a6 & a7 & a8 \\ \end{array} \right) \]
Definition at line 55 of file CpuCol2ImKernel.h.
Constructor & Destructor Documentation
CpuCol2ImKernel()
CpuCol2ImKernel () default
Default constructor.
Member Function Documentation
ARM_COMPUTE_DISALLOW_COPY_ALLOW_MOVE()
ARM_COMPUTE_DISALLOW_COPY_ALLOW_MOVE (CpuCol2ImKernel)
configure()
void configure (const ITensorInfo * src, ITensorInfo * dst, const Size2D & convolved_dims)
Set the input and output of the kernel.
Parameters
[in] src The input tensor info to convert. Data types supported: All
[out] dst The output tensor info. 3 lower dimensions represent a single output [width, height, OFM], while the rest represent batch of outputs. Data types supported: Same as input
[in] convolved_dims Output convolved dimensions.
Definition at line 63 of file CpuCol2ImKernel.cpp.
 {
     ARM_COMPUTE_ERROR_ON_NULLPTR(src, dst);
     ARM_COMPUTE_ERROR_THROW_ON(validate_arguments(src, dst, convolved_dims));
     _convolved_dims = convolved_dims;
     // Configure kernel window
     // Output auto inizialitation if not yet initialized
     auto_init_if_empty(*dst, src->clone()->set_tensor_shape(compute_col2im_shape(*src, convolved_dims, false)));
     // Configure kernel window
     Window win = calculate_max_window(*src, Steps());
     ICpuKernel::configure(win);
 }
References ARM_COMPUTE_ERROR_ON_NULLPTR, ARM_COMPUTE_ERROR_THROW_ON, arm_compute::auto_init_if_empty(), arm_compute::calculate_max_window(), arm_compute::misc::shape_calculator::compute_col2im_shape(), arm_compute::test::validation::configure(), arm_compute::test::validation::dst, arm_compute::test::validation::src, and arm_compute::cpu::kernels::validate_arguments().
name()
const char * name () const override virtual
Name of the kernel.
Returns
Kernel name
Implements ICPPKernel.
Definition at line 118 of file CpuCol2ImKernel.cpp.
 {
     return "CpuCol2ImKernel";
 }
run_op()
void run_op (ITensorPack & tensors, const Window & window, const ThreadInfo & info) override virtual
Execute the kernel on the passed window.
Warning
If is_parallelisable() returns false then the passed window must be equal to window()
Note
The window has to be a region within the window returned by the window() method
The width of the window has to be a multiple of num_elems_processed_per_iteration().
Parameters
[in] tensors A vector containing the tensors to operate on.
[in] window Region on which to execute the kernel. (Must be a region of the window returned by window())
[in] info Info about executing thread and CPU.
Reimplemented from ICPPKernel.
Definition at line 86 of file CpuCol2ImKernel.cpp.
 {
     ARM_COMPUTE_UNUSED(info);
     ARM_COMPUTE_ERROR_ON_UNCONFIGURED_KERNEL(this);
     ARM_COMPUTE_ERROR_ON_INVALID_SUBWINDOW(ICpuKernel::window(), window);
     auto src = tensors.get_const_tensor(TensorType::ACL_SRC);
     auto dst = tensors.get_tensor(TensorType::ACL_DST);
     const uint8_t el_size         = src->info()->element_size();
     const int     output_stride_x = dst->info()->strides_in_bytes().x();
     const int     output_stride_y = dst->info()->strides_in_bytes().y();
     const int     output_stride_z = dst->info()->strides_in_bytes().z();
     Window window_out(window);
     window_out.set(Window::DimX, Window::Dimension(0, 0, 0));
     window_out.set(Window::DimY, Window::Dimension(0, 0, 0));
     window_out.set(Window::DimZ, Window::Dimension(0, 0, 0));
     // Create iterators
     Iterator in(src, window);
     Iterator out(dst, window_out);
     execute_window_loop(window, [&](const Coordinates & id)
     {
         const int hidx = id.y();
         const int idx  = id.x() * output_stride_z + (hidx / _convolved_dims.width) * output_stride_y + (hidx % _convolved_dims.width) * output_stride_x;
         std::memcpy(out.ptr() + idx, in.ptr(), el_size);
     },
     in, out);
 }
References arm_compute::ACL_DST, arm_compute::ACL_SRC, ARM_COMPUTE_ERROR_ON_INVALID_SUBWINDOW, ARM_COMPUTE_ERROR_ON_UNCONFIGURED_KERNEL, ARM_COMPUTE_UNUSED, Window::DimX, Window::DimY, Window::DimZ, arm_compute::test::validation::dst, arm_compute::execute_window_loop(), ITensorPack::get_const_tensor(), ITensorPack::get_tensor(), arm_compute::test::validation::info, Iterator::ptr(), Window::set(), arm_compute::test::validation::src, and Window::y().
validate()
Status validate (const ITensorInfo * src, const ITensorInfo * dst, const Size2D & convolved_dims) static
Static function to check if given info will lead to a valid configuration.
Similar to CpuCol2ImKernel::configure()
Returns
a status
Definition at line 80 of file CpuCol2ImKernel.cpp.
 {
     ARM_COMPUTE_RETURN_ON_ERROR(validate_arguments(src, output, convolved_dims));
     return Status{};
 }
References ARM_COMPUTE_RETURN_ON_ERROR, arm_compute::test::validation::src, and arm_compute::cpu::kernels::validate_arguments().
Referenced by CpuGemmConv2d::validate().
The documentation for this class was generated from the following files:
src/cpu/kernels/CpuCol2ImKernel.h
src/cpu/kernels/CpuCol2ImKernel.cpp