Compute Library: GpuKernelComponentGroup Class Reference
GpuKernelComponentGroup Class Reference
A group of gpu kernel components to be fused together PRECONDITIONS:
#include <GpuKernelComponentGroup.h>
Public Types
using ComponentPtr = IGpuKernelComponent *
Public Member Functions
GpuKernelComponentGroup ()=default
Default constructor.
GpuKernelComponentGroup (const GpuKernelComponentGroup &)=default
Allow instances of this class to be copy constructed.
GpuKernelComponentGroup & operator= (const GpuKernelComponentGroup &)=default
Allow instances of this class to be copied.
GpuKernelComponentGroup (GpuKernelComponentGroup &&)=default
Allow instances of this class to be move constructed.
GpuKernelComponentGroup & operator= (GpuKernelComponentGroup &&)=default
Allow instances of this class to be moved.
bool add_component (ComponentPtr component)
Add a component pointer into the group If the operation fails, then no change is made to the group.
void finalize ()
Optimize and pre-compute information about the component group.
const ITensorInfo * get_any_dst_tensor () const
Get one of the destination tensors of this group.
std::vector< const ITensorInfo * > get_argument_tensors () const
Get tensor argument of this group A tensor is an argument if it is a source or destination tensor to the group.
ComponentPtr get_root_component () const
Get the root (first) component of this group.
bool is_intermediate_tensor (const ITensorInfo *tensor) const
Check if a ITensorInfo is an "intermediate" tensor of the group.
bool is_input_tensor (const ITensorInfo *tensor) const
Check if an ITensorInfo is an input tensor of the group.
std::vector< const ITensorInfo * > get_tiles () const
Get the list of temporary tiles that need to be declared.
const ITensorInfo * get_tile_for_tensor (const ITensorInfo *tensor) const
Get the shared tile that can be used to store temporary data of the specified tensor.
size_t size () const
Get the number of components within the group.
bool empty () const
Check if the component group is empty.
ComponentPtr & operator[] (size_t index)
const ComponentPtr & operator[] (size_t index) const
std::vector< ComponentPtr >::iterator begin ()
std::vector< ComponentPtr >::iterator end ()
std::vector< ComponentPtr >::const_iterator begin () const
std::vector< ComponentPtr >::const_iterator end () const
std::vector< ComponentPtr >::const_iterator cbegin () const
std::vector< ComponentPtr >::const_iterator cend () const
Static Public Attributes
static constexpr size_t max_fused_components = 64
Maximum number of components that can be fused into the same component group.
static constexpr size_t max_dst_tensors = 8
Maximum number of dst tensors allowed for a component / component.
Detailed Description
A group of gpu kernel components to be fused together PRECONDITIONS:
Fusion is limited to a linear sequence of kernel components INVARIANTS:
Note
These preconditions and invariants are exactly the same as fusion constraints for kernel components
Max number of components that can be fused is GpuKernelComponentGroup::max_fused_components (excluding any output or input (if any) components. The max number of output components are bound by the maximum number of dst tensors allowed for a component / component group)
The fusion is subject to the pattern: (Complex + Simple * | Simple + Simple * | Un-fusable) + Output?
All components but unfusable, have exactly 1 dst tensor
All fused components share the same IGpuKernelComponent::Properties (UnitWorkloadStage etc.)
All fused components share the same tunable parameters like tile size
All fused components share the same dst tensor shape
All fused components' tensors share the same DataLayout
Maximum number of dst tensors allowed for an component (including unfusable) / component group is GpuKernelComponentGroup::max_dst_tensors This has an impact on the total number of components supported, which = max_fused_components + max_dst_tensors
Definition at line 62 of file GpuKernelComponentGroup.h.
Member Typedef Documentation
ComponentPtr
using ComponentPtr = IGpuKernelComponent *
Definition at line 65 of file GpuKernelComponentGroup.h.
Constructor & Destructor Documentation
GpuKernelComponentGroup() [1/3]
GpuKernelComponentGroup () default
Default constructor.
GpuKernelComponentGroup() [2/3]
GpuKernelComponentGroup (const GpuKernelComponentGroup &) default
Allow instances of this class to be copy constructed.
GpuKernelComponentGroup() [3/3]
GpuKernelComponentGroup (GpuKernelComponentGroup &&) default
Allow instances of this class to be move constructed.
Member Function Documentation
add_component()
bool add_component (ComponentPtr component)
Add a component pointer into the group If the operation fails, then no change is made to the group.
Parameters
[in] component Pointer to the component to be added
Returns
true If the operation is successful
false If the operation fails
Definition at line 38 of file GpuKernelComponentGroup.cpp.
 {
     ARM_COMPUTE_ERROR_ON_MSG(
         _finalized, "The component group has been finalized and cannot be altered.");
     // note: Constraint 1 is guaranteed as a precondition
     // Constraint 2
     if(component->type() != GpuComponentType::Output && _components.size() >= max_fused_components)
     {
         return false;
     }
     // Constraint 3.1: Pattern: (Unfusable + Output)
     if(!_components.empty() && get_root_component()->type() == GpuComponentType::Unfusable && component->type() != GpuComponentType::Output)
     {
         return false;
     }
     // Constraint 3.2
     if(!_components.empty() && (component->type() != GpuComponentType::Simple && component->type() != GpuComponentType::Output))
     {
         return false;
     }
     // Constraint 4
     if(component->type() != GpuComponentType::Unfusable && component->tensors().get_const_dst_tensors().size() != 1U)
     {
         return false;
     }
     // Constraint 5
     if(!_components.empty() && !(get_root_component()->properties() == component->properties()))
     {
         return false;
     }
     // Constraint 7
     if(!_components.empty())
     {
         const auto root_dst_tensors = get_root_component()->tensors().get_const_dst_tensors();
         ARM_COMPUTE_ERROR_ON(root_dst_tensors.empty());
         const auto first_dst_tensor = root_dst_tensors[0];
         const auto dst_tensors      = component->tensors().get_const_dst_tensors();
         for(const auto &t : root_dst_tensors)
         {
             if(detail::have_different_dimensions(t->tensor_shape(), first_dst_tensor->tensor_shape(), 0))
             {
                 return false;
             }
         }
         for(const auto &t : dst_tensors)
         {
             if(detail::have_different_dimensions(t->tensor_shape(), first_dst_tensor->tensor_shape(), 0))
             {
                 return false;
             }
         }
     }
     // Constraint 8
     if(!_components.empty())
     {
         const auto root_dst_tensors = get_root_component()->tensors().get_const_dst_tensors();
         ARM_COMPUTE_ERROR_ON(root_dst_tensors.empty());
         const auto first_dst_tensor_layout = root_dst_tensors[0]->data_layout();
         const auto dst_tensors             = component->tensors().get_const_dst_tensors();
         for(const auto &t : root_dst_tensors)
         {
             if(t->data_layout() != first_dst_tensor_layout)
             {
                 return false;
             }
         }
         for(const auto &t : dst_tensors)
         {
             if(t->data_layout() != first_dst_tensor_layout)
             {
                 return false;
             }
         }
     }
     // Constraint 9
     if(component->tensors().get_const_dst_tensors().size() >= max_dst_tensors)
     {
         return false;
     }
     // Constraint 9 corollary
     if(component->type() == GpuComponentType::Output && _components.size() >= max_fused_components + max_dst_tensors)
     {
         return false;
     }
     _components.push_back(component);
     return true;
 }
References ARM_COMPUTE_ERROR_ON, ARM_COMPUTE_ERROR_ON_MSG, GpuKernelComponentGroup::get_root_component(), arm_compute::detail::have_different_dimensions(), GpuKernelComponentGroup::max_dst_tensors, GpuKernelComponentGroup::max_fused_components, arm_compute::experimental::dynamic_fusion::Output, IGpuKernelComponent::properties(), arm_compute::experimental::dynamic_fusion::Simple, tf_frozen_model_extractor::t, IGpuKernelComponent::tensors(), IGpuKernelComponent::type(), type, arm_compute::utils::cast::U, and arm_compute::experimental::dynamic_fusion::Unfusable.
begin() [1/2]
std::vector< GpuKernelComponentGroup::ComponentPtr >::const_iterator begin ()
Definition at line 342 of file GpuKernelComponentGroup.cpp.
 {
     return _components.begin();
 }
begin() [2/2]
std::vector<ComponentPtr>::const_iterator begin () const
cbegin()
std::vector< GpuKernelComponentGroup::ComponentPtr >::const_iterator cbegin () const
Definition at line 358 of file GpuKernelComponentGroup.cpp.
 {
     return _components.cbegin();
 }
cend()
std::vector< GpuKernelComponentGroup::ComponentPtr >::const_iterator cend () const
Definition at line 362 of file GpuKernelComponentGroup.cpp.
 {
     return _components.cend();
 }
empty()
bool empty () const
Check if the component group is empty.
Definition at line 330 of file GpuKernelComponentGroup.cpp.
 {
     return _components.empty();
 }
Referenced by GpuKernelComponentGroup::get_root_component().
end() [1/2]
std::vector< GpuKernelComponentGroup::ComponentPtr >::const_iterator end ()
Definition at line 346 of file GpuKernelComponentGroup.cpp.
 {
     return _components.end();
 }
end() [2/2]
std::vector<ComponentPtr>::const_iterator end () const
finalize()
void finalize ()
Optimize and pre-compute information about the component group.
Definition at line 127 of file GpuKernelComponentGroup.cpp.
 {
     if(_finalized)
     {
         return;
     }
     _finalized = true;
     std::set<const ITensorInfo *> output_tensors;
     std::map<const ITensorInfo *, std::vector<const ITensorInfo *>> possible_tile_map;
     std::map<const ITensorInfo *, int32_t> tile_usages;
     for(auto component : _components)
     {
         const auto tensors = component->tensors();
         const auto src_tensors = tensors.get_const_src_tensors();
         const auto dst_tensors = tensors.get_const_dst_tensors();
         // Detect input, output and intermediate tensors.
         for(auto tensor : src_tensors)
         {
             const auto output_tensors_it = output_tensors.find(tensor);
             if(output_tensors_it != output_tensors.end())
             {
                 // This tensor is the output of another operator.
                 // It must be marked as intermediate tensor.
                 output_tensors.erase(output_tensors_it);
                 _interm_tensors.insert(tensor);
             }
             else if(_interm_tensors.find(tensor) == _interm_tensors.end())
             {
                 _input_tensors.insert(tensor);
                 tile_usages[tensor] = 0;
                 possible_tile_map.emplace(tensor, std::vector<const ITensorInfo *>());
             }
         }
         for(auto tensor : dst_tensors)
         {
             ARM_COMPUTE_ERROR_ON(_input_tensors.find(tensor) != _input_tensors.end());
             ARM_COMPUTE_ERROR_ON(output_tensors.find(tensor) != output_tensors.end());
             ARM_COMPUTE_ERROR_ON(_interm_tensors.find(tensor) != _interm_tensors.end());
             output_tensors.insert(tensor);
             tile_usages[tensor] = 0;
             possible_tile_map.emplace(tensor, std::vector<const ITensorInfo *>());
         }
         // Check if the output can overwrite the input tile.
         const auto component_type = component->type();
         if(component_type == GpuComponentType::Simple || component_type == GpuComponentType::Output)
         {
             ARM_COMPUTE_ERROR_ON(dst_tensors.size() != 1);
             const auto dst_tensor = dst_tensors[0];
             const auto &dst_shape = dst_tensor->tensor_shape();
             const auto &dst_type = dst_tensor->data_type();
             tile_usages[dst_tensor] = 0;
             for(auto src_tensor : src_tensors)
             {
                 const auto &src_shape = src_tensor->tensor_shape();
                 const auto &src_type = src_tensor->data_type();
                 if(src_shape == dst_shape && src_type == dst_type)
                 {
                     const auto tile_usages_it = tile_usages.find(src_tensor);
                     ARM_COMPUTE_ERROR_ON(tile_usages_it == tile_usages.end());
                     if(component_type == GpuComponentType::Simple || tile_usages_it->second > 0)
                     {
                         // Increase the number of tile usages unless this component is an output
                         // and the tile has not been shared with any component.
                         // (Reason: output component doesn't change the content of the tile)
                         ++tile_usages_it->second;
                     }
                     possible_tile_map[dst_tensor].push_back(src_tensor);
                 }
             }
         }
         else
         {
             // Outputs of complex and unfusable components need dedicated tile.
             for(auto tensor : dst_tensors)
             {
                 tile_usages[tensor] = 0;
             }
         }
     }
     // Find the smallest list of tiles that the intermediate tensors need to write to.
     for(auto tensor : _input_tensors)
     {
         _tile_map[tensor] = tensor;
     }
     for(auto component : _components)
     {
         const auto dst_tensors = component->tensors().get_const_dst_tensors();
         for(auto tensor : dst_tensors)
         {
             const auto target_tiles = possible_tile_map.at(tensor);
             _tile_map[tensor] = tensor;
             for(auto target : target_tiles)
             {
                 const auto num_usage = tile_usages[target];
                 if(num_usage <= 1)
                 {
                     // The target tile is consumed by only this operator, so we can reuse it
                     // for the destination tensor data.
                     _tile_map[tensor] = _tile_map.at(target);
                     break;
                 }
             }
         }
     }
     for(auto tensor : output_tensors)
     {
         _tile_map[tensor] = tensor;
     }
     // All intermediate tensors that cannot be shared with any previous tensor
     // will need to be declared as tile variable.
     for(auto tensor_tile : _tile_map)
     {
         if(tensor_tile.first == tensor_tile.second &&
            _interm_tensors.find(tensor_tile.first) != _interm_tensors.end())
         {
             _tiles.push_back(tensor_tile.first);
         }
     }
     std::set_union(
         _input_tensors.begin(), _input_tensors.end(),
         output_tensors.begin(), output_tensors.end(),
         std::back_inserter(_argument_tensors));
     _any_output_tensor = *output_tensors.begin();
 }
References ARM_COMPUTE_ERROR_ON, arm_compute::test::validation::dst_shape, arm_compute::experimental::dynamic_fusion::Output, arm_compute::experimental::dynamic_fusion::Simple, and tensor.
get_any_dst_tensor()
const ITensorInfo * get_any_dst_tensor () const
Get one of the destination tensors of this group.
Definition at line 293 of file GpuKernelComponentGroup.cpp.
 {
     ARM_COMPUTE_ERROR_ON_MSG(!_finalized, "The component group must have been finalized.");
     return _any_output_tensor;
 }
References ARM_COMPUTE_ERROR_ON_MSG.
Referenced by ClTemplateCast::get_tag_lut(), ClTemplateReshape::get_tag_lut(), ClTemplateDepthwiseConv2d::get_tag_lut(), ClTemplateDirectConv2d::get_tag_lut(), ClTemplateResize::get_tag_lut(), and ClTemplateActivation::get_tag_lut().
get_argument_tensors()
std::vector< const ITensorInfo * > get_argument_tensors () const
Get tensor argument of this group A tensor is an argument if it is a source or destination tensor to the group.
Definition at line 299 of file GpuKernelComponentGroup.cpp.
 {
     ARM_COMPUTE_ERROR_ON_MSG(!_finalized, "The component group must have been finalized.");
     return _argument_tensors;
 }
References ARM_COMPUTE_ERROR_ON_MSG.
Referenced by ClTemplateWriter::get_tensors().
get_root_component()
GpuKernelComponentGroup::ComponentPtr get_root_component () const
Get the root (first) component of this group.
Definition at line 305 of file GpuKernelComponentGroup.cpp.
 {
     if(empty())
     {
         return nullptr;
     }
     return _components[0];
 }
References GpuKernelComponentGroup::empty().
Referenced by GpuKernelComponentGroup::add_component(), ClTemplateCast::get_build_options(), ClTemplateLogits1DNorm::get_build_options(), ClTemplateReshape::get_build_options(), ClTemplateDirectConv2d::get_build_options(), ClTemplatePool2d::get_build_options(), ClTemplateResize::get_build_options(), ClTemplateActivation::get_build_options(), ClTemplateCast::get_component_code(), ClTemplateElementwiseBinary::get_component_code(), ClTemplateActivation::get_component_code(), ClTemplateCast::get_tag_lut(), and ClTemplateWriter::get_window().
get_tile_for_tensor()
const ITensorInfo * get_tile_for_tensor (const ITensorInfo * tensor) const
Get the shared tile that can be used to store temporary data of the specified tensor.
Parameters
[in] tensor ITensorInfo to be looked up.
Returns
ITensorInfo that is used to store temporary data of tensor.
Definition at line 281 of file GpuKernelComponentGroup.cpp.
 {
     ARM_COMPUTE_ERROR_ON_MSG(!_finalized, "The component group must have been finalized.");
     if(_tile_map.find(tensor) != _tile_map.end())
     {
         return _tile_map.at(tensor);
     }
     return tensor;
 }
References ARM_COMPUTE_ERROR_ON_MSG, and tensor.
Referenced by GpuKernelVariableTable::declare_variable().
get_tiles()
std::vector< const ITensorInfo * > get_tiles () const
Get the list of temporary tiles that need to be declared.
Definition at line 275 of file GpuKernelComponentGroup.cpp.
 {
     ARM_COMPUTE_ERROR_ON_MSG(!_finalized, "The component group must have been finalized.");
     return _tiles;
 }
References ARM_COMPUTE_ERROR_ON_MSG.
is_input_tensor()
bool is_input_tensor (const ITensorInfo * tensor) const
Check if an ITensorInfo is an input tensor of the group.
Parameters
[in] tensor ITensorInfo to be looked up.
Returns
true if tensor is an input tensor of the group, otherwise false.
Definition at line 320 of file GpuKernelComponentGroup.cpp.
 {
     ARM_COMPUTE_ERROR_ON_MSG(!_finalized, "The component group must have been finalized.");
     return _input_tensors.find(tensor) != _input_tensors.end();
 }
References ARM_COMPUTE_ERROR_ON_MSG, and tensor.
Referenced by ClTemplateElementwiseBinary::get_component_code().
is_intermediate_tensor()
bool is_intermediate_tensor (const ITensorInfo * tensor) const
Check if a ITensorInfo is an "intermediate" tensor of the group.
An intermediate tensor is any tensor that is not an argument.
Parameters
[in] tensor ITensorInfo to be looked up
Returns
true If tensor is an intermediate tensor
false Otherwise
Definition at line 314 of file GpuKernelComponentGroup.cpp.
 {
     ARM_COMPUTE_ERROR_ON_MSG(!_finalized, "The component group must have been finalized.");
     return _interm_tensors.find(tensor) != _interm_tensors.end();
 }
References ARM_COMPUTE_ERROR_ON_MSG, and tensor.
operator=() [1/2]
GpuKernelComponentGroup& operator= (const GpuKernelComponentGroup &) default
Allow instances of this class to be copied.
operator=() [2/2]
GpuKernelComponentGroup& operator= (GpuKernelComponentGroup &&) default
Allow instances of this class to be moved.
operator[]() [1/2]
GpuKernelComponentGroup::ComponentPtr & operator[] (size_t index)
Definition at line 334 of file GpuKernelComponentGroup.cpp.
 {
     return _components[index];
 }
operator[]() [2/2]
const GpuKernelComponentGroup::ComponentPtr & operator[] (size_t index) const
Definition at line 338 of file GpuKernelComponentGroup.cpp.
 {
     return _components[index];
 }
size()
size_t size () const
Get the number of components within the group.
Definition at line 326 of file GpuKernelComponentGroup.cpp.
 {
     return _components.size();
 }
Field Documentation
max_dst_tensors
constexpr size_t max_dst_tensors = 8 static constexpr
Maximum number of dst tensors allowed for a component / component.
Definition at line 71 of file GpuKernelComponentGroup.h.
Referenced by GpuKernelComponentGroup::add_component().
max_fused_components
constexpr size_t max_fused_components = 64 static constexpr
Maximum number of components that can be fused into the same component group.
Definition at line 68 of file GpuKernelComponentGroup.h.
Referenced by GpuKernelComponentGroup::add_component().
The documentation for this class was generated from the following files:
src/dynamic_fusion/sketch/gpu/GpuKernelComponentGroup.h
src/dynamic_fusion/sketch/gpu/GpuKernelComponentGroup.cpp