Compute Library: NENormalizationLayer Class Reference
NENormalizationLayer Class Reference
Basic function to compute a normalization layer.
#include <NENormalizationLayer.h>
Public Member Functions
NENormalizationLayer (std::shared_ptr< IMemoryManager > memory_manager=nullptr)
Default constructor.
NENormalizationLayer (const NENormalizationLayer &)=delete
Prevent instances of this class from being copied (As this class contains pointers)
NENormalizationLayer & operator= (const NENormalizationLayer &)=delete
Prevent instances of this class from being copied (As this class contains pointers)
NENormalizationLayer (NENormalizationLayer &&)=delete
Prevent instances of this class from being moved (As this class contains non movable objects)
NENormalizationLayer & operator= (NENormalizationLayer &&)=delete
Prevent instances of this class from being moved (As this class contains non movable objects)
~NENormalizationLayer ()
Default destructor.
void configure (const ITensor *input, ITensor *output, const NormalizationLayerInfo &norm_info)
Set the input and output tensors.
void run () override
Run the kernels contained in the function.
Public Member Functions inherited from IFunction
virtual ~IFunction ()=default
Destructor.
virtual void prepare ()
Prepare the function for executing.
Static Public Member Functions
static Status validate (const ITensorInfo *input, const ITensorInfo *output, const NormalizationLayerInfo &norm_info)
Static function to check if given info will lead to a valid configuration of NENormalizationLayer.
Detailed Description
Basic function to compute a normalization layer.
This function calls the following kernels:
NEPixelWiseMultiplication
NEFillBorderKernel
NENormalizationLayerKernel
Definition at line 49 of file NENormalizationLayer.h.
Constructor & Destructor Documentation
NENormalizationLayer() [1/3]
NENormalizationLayer (std::shared_ptr< IMemoryManager > memory_manager = nullptr)
Default constructor.
Definition at line 39 of file NENormalizationLayer.cpp.
     : _memory_group(std::move(memory_manager)), _norm_kernel(), _multiply_f(), _input_squared()
 {
 }
NENormalizationLayer() [2/3]
NENormalizationLayer (const NENormalizationLayer &) delete
Prevent instances of this class from being copied (As this class contains pointers)
NENormalizationLayer() [3/3]
NENormalizationLayer (NENormalizationLayer &&) delete
Prevent instances of this class from being moved (As this class contains non movable objects)
~NENormalizationLayer()
~NENormalizationLayer () default
Default destructor.
Member Function Documentation
configure()
void configure (const ITensor * input, ITensor * output, const NormalizationLayerInfo & norm_info)
Set the input and output tensors.
Valid data layouts:
NHWC
NCHW
Valid data type configurations:
src dst
F32 F32
F16 F16
Parameters
[in] input Source tensor. 3 lower dims represent a single input with dimensions [width, height, IFM], and an optional 4th dimension for batch of inputs. Data type supported: F16/F32. Data layouts supported: NCHW/NHWC.
[out] output Destination with the same dimensions, data type, data layout and number of channels of input
[in] norm_info Normalization layer information like the normalization type, normalization size and other parameters.
Definition at line 44 of file NENormalizationLayer.cpp.
 {
     ARM_COMPUTE_ERROR_ON_NULLPTR(input, output);
     ARM_COMPUTE_LOG_PARAMS(input, output, norm_info);
     TensorInfo tensor_info(input->info()->tensor_shape(), 1, input->info()->data_type());
     _input_squared.allocator()->init(tensor_info);
     // Manage intermediate buffers
     _memory_group.manage(&_input_squared);
     // Configure kernels
     _norm_kernel = std::make_unique<NENormalizationLayerKernel>();
     _norm_kernel->configure(input, &_input_squared, output, norm_info);
     _multiply_f.configure(input, input, &_input_squared, 1.0f, ConvertPolicy::SATURATE, RoundingPolicy::TO_ZERO);
     // Allocate the tensor once the configure methods have been called
     _input_squared.allocator()->allocate();
 }
References TensorAllocator::allocate(), Tensor::allocator(), ARM_COMPUTE_ERROR_ON_NULLPTR, ARM_COMPUTE_LOG_PARAMS, NEPixelWiseMultiplication::configure(), TensorAllocator::init(), arm_compute::test::validation::input, MemoryGroup::manage(), arm_compute::SATURATE, tensor_info, and arm_compute::TO_ZERO.
Referenced by arm_compute::test::validation::TEST_CASE().
operator=() [1/2]
NENormalizationLayer& operator= (const NENormalizationLayer &) delete
Prevent instances of this class from being copied (As this class contains pointers)
operator=() [2/2]
NENormalizationLayer& operator= (NENormalizationLayer &&) delete
Prevent instances of this class from being moved (As this class contains non movable objects)
run()
void run () override virtual
Run the kernels contained in the function.
For CPU kernels:
Multi-threading is used for the kernels which are parallelisable.
By default std::thread::hardware_concurrency() threads are used.
Note
CPPScheduler::set_num_threads() can be used to manually set the number of threads
For OpenCL kernels:
All the kernels are enqueued on the queue associated with CLScheduler.
The queue is then flushed.
Note
The function will not block until the kernels are executed. It is the user's responsibility to wait.
Will call prepare() on first run if hasn't been done
Implements IFunction.
Definition at line 75 of file NENormalizationLayer.cpp.
 {
     MemoryGroupResourceScope scope_mg(_memory_group);
     _multiply_f.run();
     NEScheduler::get().schedule(_norm_kernel.get(), Window::DimY);
 }
References Window::DimY, Scheduler::get(), NEPixelWiseMultiplication::run(), and IScheduler::schedule().
Referenced by arm_compute::test::validation::TEST_CASE().
validate()
Status validate (const ITensorInfo * input, const ITensorInfo * output, const NormalizationLayerInfo & norm_info) static
Static function to check if given info will lead to a valid configuration of NENormalizationLayer.
Parameters
[in] input Source tensor. 3 lower dims represent a single input with dimensions [width, height, IFM], and an optional 4th dimension for batch of inputs. Data type supported: F16/F32. Data layouts supported: NCHW/NHWC.
[in] output Destination with the same dimensions, data type, data layout and number of channels of input
[in] norm_info Normalization layer information like the normalization type, normalization size and other parameters.
Returns
a status
Definition at line 64 of file NENormalizationLayer.cpp.
 {
     // Perform validation step
     ARM_COMPUTE_RETURN_ERROR_ON_NULLPTR(input, output);
     ARM_COMPUTE_RETURN_ON_ERROR(NENormalizationLayerKernel::validate(input, input, output, norm_info));
     ARM_COMPUTE_RETURN_ON_ERROR(NEPixelWiseMultiplication::validate(input, input, output, 1.0f, ConvertPolicy::SATURATE, RoundingPolicy::TO_ZERO));
     return Status{};
 }
References ARM_COMPUTE_RETURN_ERROR_ON_NULLPTR, ARM_COMPUTE_RETURN_ON_ERROR, arm_compute::test::validation::input, arm_compute::SATURATE, arm_compute::TO_ZERO, NENormalizationLayerKernel::validate(), and NEPixelWiseMultiplication::validate().
The documentation for this class was generated from the following files:
arm_compute/runtime/NEON/functions/NENormalizationLayer.h
src/runtime/NEON/functions/NENormalizationLayer.cpp