Compute Library: MatMulInfo Class Reference
MatMulInfo Class Reference
Class for holding information related to matrix multiplication function.
#include <Types.h>
Public Member Functions
bool adj_lhs () const
bool adj_rhs () const
ActivationLayerInfo fused_activation () const
MatMulInfo & adj_lhs (bool adj_lhs)
MatMulInfo & adj_rhs (bool adj_rhs)
MatMulInfo & fused_activation (const ActivationLayerInfo &act_info)
Detailed Description
Class for holding information related to matrix multiplication function.
Definition at line 2718 of file Types.h.
Member Function Documentation
adj_lhs() [1/2]
bool adj_lhs () const inline
Definition at line 2722 of file Types.h.
     {
         return _adj_lhs;
     }
Referenced by MatMulInfo::adj_lhs(), and arm_compute::operator<<().
adj_lhs() [2/2]
MatMulInfo& adj_lhs (bool adj_lhs) inline
Definition at line 2737 of file Types.h.
     {
         _adj_lhs = adj_lhs;
         return *this;
     }
References MatMulInfo::adj_lhs().
adj_rhs() [1/2]
bool adj_rhs () const inline
Definition at line 2727 of file Types.h.
     {
         return _adj_rhs;
     }
Referenced by MatMulInfo::adj_rhs(), and arm_compute::operator<<().
adj_rhs() [2/2]
MatMulInfo& adj_rhs (bool adj_rhs) inline
Definition at line 2743 of file Types.h.
     {
         _adj_rhs = adj_rhs;
         return *this;
     }
References MatMulInfo::adj_rhs().
fused_activation() [1/2]
ActivationLayerInfo fused_activation () const inline
Definition at line 2732 of file Types.h.
     {
         return _fused_act;
     }
Referenced by arm_compute::operator<<().
fused_activation() [2/2]
MatMulInfo& fused_activation (const ActivationLayerInfo & act_info) inline
Definition at line 2749 of file Types.h.
     {
         _fused_act = act_info;
         return *this;
     }
References arm_compute::test::validation::act_info.
The documentation for this class was generated from the following file:
arm_compute/core/Types.h