Compute Library: CpuMatMul Class Reference
CpuMatMul Class Reference
Function to execute MatMul Operation.
#include <CpuMatMul.h>
Public Member Functions
CpuMatMul ()
~CpuMatMul ()=default
ARM_COMPUTE_DISALLOW_COPY_ALLOW_MOVE (CpuMatMul)
void configure (ITensorInfo *lhs, ITensorInfo *rhs, ITensorInfo *dst, const MatMulInfo &info, const CpuMatMulSettings &settings)
Configure operator for a given list of arguments.
void run (ITensorPack &tensors) override
Run the kernels contained in the function.
experimental::MemoryRequirements workspace () const override
Return the memory requirements required by the workspace.
Public Member Functions inherited from INEOperator
INEOperator (IRuntimeContext *ctx=nullptr)
Constructor.
INEOperator (const INEOperator &)=delete
Prevent instances of this class from being copied (As this class contains pointers)
INEOperator (INEOperator &&)=default
Default move constructor.
INEOperator & operator= (const INEOperator &)=delete
Prevent instances of this class from being copied (As this class contains pointers)
INEOperator & operator= (INEOperator &&)=default
Default move assignment operator.
~INEOperator ()
Default destructor.
void prepare (ITensorPack &constants) override
Prepare the function for executing.
Public Member Functions inherited from IOperator
virtual ~IOperator ()=default
Destructor.
Static Public Member Functions
static Status validate (const ITensorInfo *lhs, const ITensorInfo *rhs, const ITensorInfo *dst, const MatMulInfo &info, const CpuMatMulSettings &settings)
Static function to check if given info will lead to a valid configuration.
Detailed Description
Function to execute MatMul Operation.
This function calls the following functions/kernels:
If adjoint/adj flag is enabled for either input lhs or rhs (or both) :
cpu::kernels::CpuTransposeKernel Then :
cpu::CpuGemmAssemblyDispatch
Definition at line 48 of file CpuMatMul.h.
Constructor & Destructor Documentation
CpuMatMul()
CpuMatMul ()
Definition at line 80 of file CpuMatMul.cpp.
     : _transpose_kernel_lhs(), _transpose_kernel_rhs(), _asm_glue(), _lhs_transposed(), _rhs_transposed(), _original_lhs_shape(), _original_rhs_shape(), _original_dst_shape()
 {
 }
~CpuMatMul()
~CpuMatMul () default
Member Function Documentation
ARM_COMPUTE_DISALLOW_COPY_ALLOW_MOVE()
ARM_COMPUTE_DISALLOW_COPY_ALLOW_MOVE (CpuMatMul)
configure()
void configure (ITensorInfo * lhs, ITensorInfo * rhs, ITensorInfo * dst, const MatMulInfo & info, const CpuMatMulSettings & settings)
Configure operator for a given list of arguments.
Note: Check documentation of NEMatMul for a list of supported datatypes and layouts
Parameters
[in] lhs Left-hand side tensor info.
[in] rhs Right-hand side tensor info.
[out] dst Output tensor to store the result of the batched matrix multiplication. Data types supported: same as lhs / rhs.
[in] info Contains MatMul operation information described in MatMulInfo.
[in] settings The settings for matmul operation (i.e fast math)
Definition at line 142 of file CpuMatMul.cpp.
 {
     ARM_COMPUTE_ERROR_ON_NULLPTR(lhs, rhs, dst);
     ARM_COMPUTE_LOG_PARAMS(lhs, rhs, dst, info, settings);
     ARM_COMPUTE_ERROR_THROW_ON(CpuMatMul::validate(lhs, rhs, dst, info, settings));
     _adj_lhs   = info.adj_lhs();
     _adj_rhs   = info.adj_rhs();
     _fast_math = settings.fast_math();
     // 1. Create and reshape tensors
     // ------------------------------------------------------
     // a. Clone TensorInfo to prevent changing original tensor values during setup
     // b. Change shape of lhs/dst to [x, y, 1, collapsed(z)] to match assembly kernel configuration
     // c. For rhs collapse all dimensions larger than 3 to z dimension
     TensorInfo lhs_to_use = *lhs->clone();
     TensorInfo dst_to_use = *dst->clone();
     TensorInfo rhs_to_use = *rhs->clone();
     // Save starting shape of tensors
     _original_lhs_shape = lhs_to_use.tensor_shape();
     _original_dst_shape = dst_to_use.tensor_shape();
     _original_rhs_shape = rhs_to_use.tensor_shape();
     // Reshape lhs for use with assembly kernels.
     lhs_to_use.set_tensor_shape(TensorShape(_original_lhs_shape.x(), _original_lhs_shape.y(), 1, _original_lhs_shape.collapsed_from(2).z()));
     dst_to_use.set_tensor_shape(TensorShape(_original_dst_shape.x(), _original_dst_shape.y(), 1, _original_dst_shape.collapsed_from(2).z()));
     rhs_to_use.set_tensor_shape(_original_rhs_shape.collapsed_from(2));
     // 2.  Configuration for transpose of lhs/rhs
     // ------------------------------------------------------
     // Initialise transposed TensorInfo class for aux tensors (intermediary tensors)
     if(_adj_lhs)
     {
         // Setup transpose LHS
         _transpose_kernel_lhs = std::make_unique<cpu::kernels::CpuTransposeKernel>();
         _transpose_kernel_lhs->configure(&lhs_to_use, &_lhs_transposed);
     }
     if(_adj_rhs)
     {
         // Setup transpose RHS
         _transpose_kernel_rhs = std::make_unique<cpu::kernels::CpuTransposeKernel>();
         _transpose_kernel_rhs->configure(&rhs_to_use, &_rhs_transposed);
     }
     // 3. Configure assembly kernel using transposed tensors.
     // -----------------------------------------------------
     // Use transposed tensors if the corresponding transpose flags are set
     // Fill AsmGemmInfo class object before configuration
     _gemm_info.activation_info = info.fused_activation();
     _gemm_info.fast_mode       = settings.fast_math();
     _gemm_info.negated_offsets = false;
     lhs_to_use = (_adj_lhs) ? _lhs_transposed : lhs_to_use;
     rhs_to_use = (_adj_rhs) ? _rhs_transposed : rhs_to_use;
     // Quantized-specific configuration
     if(is_data_type_quantized(lhs->data_type()))
     {
         get_gemmlowp_output_stage_info(&lhs_to_use, &rhs_to_use, &dst_to_use, _gemm_info.activation_info, _gemm_info.output_stage);
     }
     // Configure Asm Kernel
     _asm_glue = std::make_unique<cpu::CpuGemmAssemblyDispatch>();
     _asm_glue->configure(&lhs_to_use, &rhs_to_use, nullptr, &dst_to_use, _gemm_info); // c is nullptr as bias not supported in MatMul
     // Specify memory requirements for intermediate tensors
     auto asm_mem_req = _asm_glue->workspace();
     // Specify memory required by gemm kernel
     int idx = 0;
     for(const auto &aux : asm_mem_req)
     {
         _aux_mem[idx] = aux;
         idx++;
     }
     // Memory requirements for transposed tensors
     _aux_mem[TransposeLHS] = MemoryInfo(offset_int_vec(TransposeLHS), MemoryLifetime::Temporary, lhs->total_size());
     _aux_mem[TransposeRHS] = MemoryInfo(offset_int_vec(TransposeRHS), MemoryLifetime::Temporary, rhs->total_size());
 }
References AsmGemmInfo::activation_info, ARM_COMPUTE_ERROR_ON_NULLPTR, ARM_COMPUTE_ERROR_THROW_ON, ARM_COMPUTE_LOG_PARAMS, ICloneable< T >::clone(), TensorShape::collapsed_from(), ITensorInfo::data_type(), arm_compute::test::validation::dst, CpuMatMulSettings::fast_math(), AsmGemmInfo::fast_mode, arm_compute::test::validation::info, arm_compute::is_data_type_quantized(), AsmGemmInfo::negated_offsets, arm_compute::offset_int_vec(), AsmGemmInfo::output_stage, TensorInfo::set_tensor_shape(), TensorInfo::tensor_shape(), ITensorInfo::total_size(), CpuMatMul::validate(), Dimensions< T >::x(), Dimensions< T >::y(), and Dimensions< T >::z().
run()
void run (ITensorPack & tensors) override virtual
Run the kernels contained in the function.
Parameters
[in] tensors Vector that contains the tensors to operate on.
Reimplemented from INEOperator.
Definition at line 223 of file CpuMatMul.cpp.
 {
     // Retrieve tensors from tensor pack
     auto lhs = tensors.get_tensor(ACL_SRC_0);
     auto rhs = tensors.get_const_tensor(ACL_SRC_1);
     auto dst = tensors.get_tensor(ACL_DST);
     // Reshape LHS and DST to ensure compatibility with GEMM asm kernel (Batch dimensions is 4th for lhs and dst within asm)
     // Collapse RHS (necessary to support dimensions larger than 3 in gemm assembly)
     lhs->info()->set_tensor_shape(TensorShape(_original_lhs_shape.x(), _original_lhs_shape.y(), 1, _original_lhs_shape.collapsed_from(2).z())); // Collapsed 3+ dimensions into z
     dst->info()->set_tensor_shape(TensorShape(_original_dst_shape.x(), _original_dst_shape.y(), 1, _original_dst_shape.collapsed_from(2).z())); // Collapsed 3+ dimensions into z
     rhs->info()->set_tensor_shape(_original_rhs_shape.collapsed_from(2));
     // Initialise object to handle stored transposed tensors in auxillary memory
     CpuAuxTensorHandler lhs_transposed(offset_int_vec(TransposeLHS), _lhs_transposed, tensors, true);
     CpuAuxTensorHandler rhs_transposed(offset_int_vec(TransposeRHS), _rhs_transposed, tensors, true);
     // Create tensor pack for asm kernel
     ITensorPack asm_tensors(tensors);
     // Run transpose lhs if necessary
     if(_adj_lhs)
     {
         ITensorPack lhs_transpose_pack = { { TensorType::ACL_SRC, lhs }, { TensorType::ACL_DST, lhs_transposed.get() } };
         NEScheduler::get().schedule_op(_transpose_kernel_lhs.get(), Window::DimY, _transpose_kernel_lhs->window(), lhs_transpose_pack);
         asm_tensors.add_const_tensor(TensorType::ACL_SRC_0, lhs_transposed.get());
     }
     // Run transpose rhs if necessary
     if(_adj_rhs)
     {
         ITensorPack rhs_transpose_pack = { { TensorType::ACL_SRC, rhs }, { TensorType::ACL_DST, rhs_transposed.get() } };
         NEScheduler::get().schedule_op(_transpose_kernel_rhs.get(), Window::DimY, _transpose_kernel_rhs->window(), rhs_transpose_pack);
         asm_tensors.add_const_tensor(TensorType::ACL_SRC_1, rhs_transposed.get());
     }
     // Run asm kernel
     _asm_glue->run(asm_tensors);
     // Undo reshape of tensors
     dst->info()->set_tensor_shape(_original_dst_shape);
     lhs->info()->set_tensor_shape(_original_lhs_shape);
     rhs->info()->set_tensor_shape(_original_rhs_shape);
 }
References arm_compute::ACL_DST, arm_compute::ACL_SRC, arm_compute::ACL_SRC_0, arm_compute::ACL_SRC_1, ITensorPack::add_const_tensor(), TensorShape::collapsed_from(), Window::DimY, arm_compute::test::validation::dst, Scheduler::get(), CpuAuxTensorHandler::get(), ITensorPack::get_const_tensor(), ITensorPack::get_tensor(), ITensor::info(), arm_compute::offset_int_vec(), IScheduler::schedule_op(), ITensorInfo::set_tensor_shape(), Dimensions< T >::x(), Dimensions< T >::y(), and Dimensions< T >::z().
validate()
Status validate (const ITensorInfo * lhs, const ITensorInfo * rhs, const ITensorInfo * dst, const MatMulInfo & info, const CpuMatMulSettings & settings) static
Static function to check if given info will lead to a valid configuration.
Similar to CpuMatMul::configure()
Returns
a status
Definition at line 85 of file CpuMatMul.cpp.
 {
     ARM_COMPUTE_RETURN_ERROR_ON_MISMATCHING_DATA_TYPES(lhs, rhs, dst);
     ARM_COMPUTE_RETURN_ERROR_ON_DATA_TYPE_CHANNEL_NOT_IN(lhs, 1, DataType::F32, DataType::F16, DataType::QASYMM8, DataType::QASYMM8_SIGNED);
     ARM_COMPUTE_RETURN_ERROR_ON_MSG(lhs->are_values_constant(), "LHS Tensor must be dynamic.");
     ARM_COMPUTE_RETURN_ERROR_ON_MSG(rhs->are_values_constant(), "RHS Tensor must be dynamic.");
     ARM_COMPUTE_RETURN_ERROR_ON_CPU_F16_UNSUPPORTED(lhs);
     ARM_COMPUTE_RETURN_ERROR_ON_CPU_BF16_UNSUPPORTED(lhs);
     const auto adj_lhs = info.adj_lhs();
     const auto adj_rhs = info.adj_rhs();
     const ITensorInfo *lhs_to_use = lhs;
     const ITensorInfo *rhs_to_use = rhs;
     TensorInfo         lhs_transposed{};
     TensorInfo         rhs_transposed{};
     auto gemm_info            = AsmGemmInfo();
     gemm_info.activation_info = info.fused_activation();
     gemm_info.fast_mode       = settings.fast_math();
     // Validate and then permute a/b
     if(adj_lhs)
     {
         auto_init_if_empty(lhs_transposed, lhs->clone()->set_tensor_shape(misc::shape_calculator::compute_transposed_shape(*lhs)));
         ARM_COMPUTE_RETURN_ON_ERROR(cpu::kernels::CpuTransposeKernel::validate(lhs_to_use, &lhs_transposed));
         // Assign lhs_to_use pointer to use transposed TensorInfo
         lhs_to_use = &lhs_transposed;
     }
     if(adj_rhs)
     {
         auto_init_if_empty(rhs_transposed, rhs->clone()->set_tensor_shape(misc::shape_calculator::compute_transposed_shape(*rhs)));
         ARM_COMPUTE_RETURN_ON_ERROR(cpu::kernels::CpuTransposeKernel::validate(rhs_to_use, &rhs_transposed));
         // Assign rhs_to_use pointer to use transposed TensorInfo
         rhs_to_use = &rhs_transposed;
     }
     ARM_COMPUTE_RETURN_ERROR_ON_MSG(lhs_to_use->dimension(0) != rhs_to_use->dimension(1),
                                     "The product AB is defined only if the number of columns in A is equal to the number of rows in B (after transpose)");
     // Iterate over dimensions to be collapsed in operator - check dimensions are equivalent between tensors
     for(unsigned int i = 2; i < Coordinates::num_max_dimensions; i++)
     {
         ARM_COMPUTE_RETURN_ERROR_ON_MSG(lhs_to_use->dimension(i) != rhs_to_use->dimension(i), "Broadcasting in Batch dimension is unsupported by this operator.");
     }
     // Quantized-specific configuration
     if(is_data_type_quantized(lhs->data_type()))
     {
         ARM_COMPUTE_RETURN_ON_ERROR(get_gemmlowp_output_stage_info(lhs_to_use, rhs_to_use, dst, gemm_info.activation_info, gemm_info.output_stage));
     }
     cpu::CpuGemmAssemblyDispatch::validate(lhs_to_use, rhs_to_use, nullptr, dst, gemm_info);
     return Status{};
 }
References ITensorInfo::are_values_constant(), ARM_COMPUTE_RETURN_ERROR_ON_CPU_BF16_UNSUPPORTED, ARM_COMPUTE_RETURN_ERROR_ON_CPU_F16_UNSUPPORTED, ARM_COMPUTE_RETURN_ERROR_ON_DATA_TYPE_CHANNEL_NOT_IN, ARM_COMPUTE_RETURN_ERROR_ON_MISMATCHING_DATA_TYPES, ARM_COMPUTE_RETURN_ERROR_ON_MSG, ARM_COMPUTE_RETURN_ON_ERROR, arm_compute::auto_init_if_empty(), ICloneable< T >::clone(), arm_compute::misc::shape_calculator::compute_transposed_shape(), ITensorInfo::data_type(), ITensorInfo::dimension(), arm_compute::test::validation::dst, arm_compute::F16, arm_compute::F32, CpuMatMulSettings::fast_math(), arm_compute::test::validation::gemm_info, arm_compute::test::validation::info, arm_compute::is_data_type_quantized(), Dimensions< int >::num_max_dimensions, arm_compute::QASYMM8, arm_compute::QASYMM8_SIGNED, CpuTransposeKernel::validate(), and CpuGemmAssemblyDispatch::validate().
Referenced by CpuMatMul::configure(), and NEMatMul::validate().
workspace()
experimental::MemoryRequirements workspace () const override virtual
Return the memory requirements required by the workspace.
Reimplemented from INEOperator.
Definition at line 266 of file CpuMatMul.cpp.
 {
     return _aux_mem;
 }
The documentation for this class was generated from the following files:
src/cpu/operators/CpuMatMul.h
src/cpu/operators/CpuMatMul.cpp