Compute Library: GpuKernelSourceCode Class Reference
GpuKernelSourceCode Class Reference
Container of kernel code to be compiled and run in a GpuUnitWorkload.
#include <GpuKernelSourceCode.h>
Public Member Functions
GpuKernelSourceCode & name (const std::string &n)
Set kernel name.
GpuKernelSourceCode & code (const std::string &c)
Set kernel code.
GpuKernelSourceCode & config_id (const std::string &c_id)
Set kernel config id string.
GpuKernelSourceCode & build_options (const CLBuildOptions &b_options)
Set kernel build options.
GpuKernelSourceCode & window (const Window &window)
Set kernel execution window.
GpuKernelSourceCode & arguments (const GpuKernelArgumentList &arguments)
Set kernel argument list.
std::string name () const
Get kernel name.
std::string code () const
Get kernel code.
std::string config_id () const
Get kernel config id string.
const CLBuildOptions & build_options () const
Get kernel build options.
const Window & window () const
Get kernel execution window.
const GpuKernelArgumentList & arguments () const
Get kernel argument list.
Detailed Description
Container of kernel code to be compiled and run in a GpuUnitWorkload.
Definition at line 45 of file GpuKernelSourceCode.h.
Member Function Documentation
arguments() [1/2]
const GpuKernelArgumentList& arguments () const inline
Get kernel argument list.
Definition at line 110 of file GpuKernelSourceCode.h.
     {
         return _arguments;
     }
Referenced by GpuKernelSourceCode::arguments().
arguments() [2/2]
GpuKernelSourceCode& arguments (const GpuKernelArgumentList & arguments) inline
Set kernel argument list.
Definition at line 79 of file GpuKernelSourceCode.h.
     {
         _arguments = arguments;
         return *this;
     }
References GpuKernelSourceCode::arguments().
Referenced by GpuWorkloadSourceCode::add_unit_workload(), ClKernelRuntime::configure(), and GpuLogicalKernel::write_kernel_code().
build_options() [1/2]
const CLBuildOptions& build_options () const inline
Get kernel build options.
Definition at line 100 of file GpuKernelSourceCode.h.
     {
         return _build_options;
     }
build_options() [2/2]
GpuKernelSourceCode& build_options (const CLBuildOptions & b_options) inline
Set kernel build options.
Definition at line 67 of file GpuKernelSourceCode.h.
     {
         _build_options = b_options;
         return *this;
     }
Referenced by ClKernelRuntime::configure(), and GpuLogicalKernel::write_kernel_code().
code() [1/2]
std::string code () const inline
Get kernel code.
Definition at line 90 of file GpuKernelSourceCode.h.
     {
         return _code;
     }
code() [2/2]
GpuKernelSourceCode& code (const std::string & c) inline
Set kernel code.
Definition at line 55 of file GpuKernelSourceCode.h.
     {
         _code = c;
         return *this;
     }
Referenced by ClKernelRuntime::configure(), and GpuLogicalKernel::write_kernel_code().
config_id() [1/2]
std::string config_id () const inline
Get kernel config id string.
Definition at line 95 of file GpuKernelSourceCode.h.
     {
         return _config_id;
     }
config_id() [2/2]
GpuKernelSourceCode& config_id (const std::string & c_id) inline
Set kernel config id string.
Definition at line 61 of file GpuKernelSourceCode.h.
     {
         _config_id = c_id;
         return *this;
     }
Referenced by ClKernelRuntime::configure(), and GpuLogicalKernel::write_kernel_code().
name() [1/2]
std::string name () const inline
Get kernel name.
Definition at line 85 of file GpuKernelSourceCode.h.
     {
         return _name;
     }
name() [2/2]
GpuKernelSourceCode& name (const std::string & n) inline
Set kernel name.
Definition at line 49 of file GpuKernelSourceCode.h.
     {
         _name = n;
         return *this;
     }
References arm_compute::test::validation::n.
Referenced by ClKernelRuntime::configure(), and GpuLogicalKernel::write_kernel_code().
window() [1/2]
const Window& window () const inline
Get kernel execution window.
Definition at line 105 of file GpuKernelSourceCode.h.
     {
         return _window;
     }
Referenced by GpuKernelSourceCode::window().
window() [2/2]
GpuKernelSourceCode& window (const Window & window) inline
Set kernel execution window.
Definition at line 73 of file GpuKernelSourceCode.h.
     {
         _window = window;
         return *this;
     }
References GpuKernelSourceCode::window().
Referenced by ClKernelRuntime::configure(), and GpuLogicalKernel::write_kernel_code().
The documentation for this class was generated from the following file:
src/dynamic_fusion/sketch/gpu/GpuKernelSourceCode.h