Compute Library: CLReverseKernel Class Reference
CLReverseKernel Class Reference
Interface for the reverse kernel.
#include <CLReverseKernel.h>
Public Member Functions
CLReverseKernel ()
Default constructor.
CLReverseKernel (const CLReverseKernel &)=delete
Prevent instances of this class from being copied (As this class contains pointers)
CLReverseKernel & operator= (const CLReverseKernel &)=delete
Prevent instances of this class from being copied (As this class contains pointers)
CLReverseKernel (CLReverseKernel &&)=default
Allow instances of this class to be moved.
CLReverseKernel & operator= (CLReverseKernel &&)=default
Allow instances of this class to be moved.
~CLReverseKernel ()=default
Default destructor.
void configure (const ICLTensor *input, ICLTensor *output, const ICLTensor *axis)
Initialise the kernel's inputis and output.
void configure (const CLCompileContext &compile_context, const ICLTensor *input, ICLTensor *output, const ICLTensor *axis)
Initialise the kernel's inputis and output.
void run (const Window &window, cl::CommandQueue &queue) override
Enqueue the OpenCL kernel to process the given window on the passed OpenCL command queue.
Public Member Functions inherited from ICLKernel
ICLKernel ()
Constructor.
cl::Kernel & kernel ()
Returns a reference to the OpenCL kernel of this object.
CLKernelType type () const
Returns the CL kernel type.
template<typename T >
void add_1D_array_argument (unsigned int &idx, const ICLArray< T > *array, const Strides &strides, unsigned int num_dimensions, const Window &window)
Add the passed 1D array's parameters to the object's kernel's arguments starting from the index idx.
void add_1D_tensor_argument (unsigned int &idx, const ICLTensor *tensor, const Window &window)
Add the passed 1D tensor's parameters to the object's kernel's arguments starting from the index idx.
void add_1D_tensor_argument_if (bool cond, unsigned int &idx, const ICLTensor *tensor, const Window &window)
Add the passed 1D tensor's parameters to the object's kernel's arguments starting from the index idx if the condition is true.
void add_2D_tensor_argument (unsigned int &idx, const ICLTensor *tensor, const Window &window)
Add the passed 2D tensor's parameters to the object's kernel's arguments starting from the index idx.
void add_2D_tensor_argument_if (bool cond, unsigned int &idx, const ICLTensor *tensor, const Window &window)
Add the passed 2D tensor's parameters to the object's kernel's arguments starting from the index idx if the condition is true.
void add_3D_tensor_argument (unsigned int &idx, const ICLTensor *tensor, const Window &window)
Add the passed 3D tensor's parameters to the object's kernel's arguments starting from the index idx.
void add_4D_tensor_argument (unsigned int &idx, const ICLTensor *tensor, const Window &window)
Add the passed 4D tensor's parameters to the object's kernel's arguments starting from the index idx.
void add_5D_tensor_argument (unsigned int &idx, const ICLTensor *tensor, const Window &window)
Add the passed 5D tensor's parameters to the object's kernel's arguments starting from the index idx.
void add_3d_tensor_nhw_argument (unsigned int &idx, const ICLTensor *tensor)
Add the passed NHW 3D tensor's parameters to the object's kernel's arguments by passing strides, dimensions and the offset to the first valid element in bytes.
void add_4d_tensor_nhwc_argument (unsigned int &idx, const ICLTensor *tensor)
Add the passed NHWC 4D tensor's parameters to the object's kernel's arguments by passing strides, dimensions and the offset to the first valid element in bytes.
virtual void run_op (ITensorPack &tensors, const Window &window, cl::CommandQueue &queue)
Enqueue the OpenCL kernel to process the given window on the passed OpenCL command queue.
template<typename T >
void add_argument (unsigned int &idx, T value)
Add the passed parameters to the object's kernel's arguments starting from the index idx.
void set_lws_hint (const cl::NDRange &lws_hint)
Set the Local-Workgroup-Size hint.
cl::NDRange lws_hint () const
Return the Local-Workgroup-Size hint.
void set_wbsm_hint (const cl_int &wbsm_hint)
Set the workgroup batch size modifier hint.
cl_int wbsm_hint () const
Return the workgroup batch size modifier hint.
const std::string & config_id () const
Get the configuration ID.
void set_target (GPUTarget target)
Set the targeted GPU architecture.
void set_target (cl::Device &device)
Set the targeted GPU architecture according to the CL device.
GPUTarget get_target () const
Get the targeted GPU architecture.
size_t get_max_workgroup_size ()
Get the maximum workgroup size for the device the CLKernelLibrary uses.
cl::NDRange get_cached_gws () const
Get the cached gws used to enqueue this kernel.
void cache_gws (const cl::NDRange &gws)
Cache the latest gws used to enqueue this kernel.
template<unsigned int dimension_size>
void add_tensor_argument (unsigned &idx, const ICLTensor *tensor, const Window &window)
template<typename T , unsigned int dimension_size>
void add_array_argument (unsigned &idx, const ICLArray< T > *array, const Strides &strides, unsigned int num_dimensions, const Window &window)
Add the passed array's parameters to the object's kernel's arguments starting from the index idx.
Public Member Functions inherited from IKernel
IKernel ()
Constructor.
virtual ~IKernel ()=default
Destructor.
virtual bool is_parallelisable () const
Indicates whether or not the kernel is parallelisable.
virtual BorderSize border_size () const
The size of the border for that kernel.
const Window & window () const
The maximum window the kernel can be executed on.
bool is_window_configured () const
Function to check if the embedded window of this kernel has been configured.
Static Public Member Functions
static Status validate (const ITensorInfo *input, const ITensorInfo *output, const ITensorInfo *axis)
Static function to check if given info will lead to a valid configuration of CLReverseKernel.
Static Public Member Functions inherited from ICLKernel
constexpr static unsigned int num_arguments_per_3d_tensor_nhw ()
Returns the number of arguments enqueued per NHW 3D Tensor object.
constexpr static unsigned int num_arguments_per_4d_tensor_nhwc ()
Returns the number of arguments enqueued per NHWC 4D Tensor object.
constexpr static unsigned int num_arguments_per_1D_array ()
Returns the number of arguments enqueued per 1D array object.
constexpr static unsigned int num_arguments_per_1D_tensor ()
Returns the number of arguments enqueued per 1D tensor object.
constexpr static unsigned int num_arguments_per_2D_tensor ()
Returns the number of arguments enqueued per 2D tensor object.
constexpr static unsigned int num_arguments_per_3D_tensor ()
Returns the number of arguments enqueued per 3D tensor object.
constexpr static unsigned int num_arguments_per_4D_tensor ()
Returns the number of arguments enqueued per 4D tensor object.
static cl::NDRange gws_from_window (const Window &window, bool use_dummy_work_items)
Get the global work size given an execution window.
Data Fields
const ICLTensor * _input
ICLTensor * _output
const ICLTensor * _axis
Detailed Description
Interface for the reverse kernel.
Definition at line 34 of file CLReverseKernel.h.
Constructor & Destructor Documentation
CLReverseKernel() [1/3]
CLReverseKernel ()
Default constructor.
Definition at line 61 of file CLReverseKernel.cpp.
     : _input(nullptr), _output(nullptr), _axis(nullptr)
 {
     _type = CLKernelType::ELEMENTWISE;
 }
References arm_compute::ELEMENTWISE.
CLReverseKernel() [2/3]
CLReverseKernel (const CLReverseKernel &) delete
Prevent instances of this class from being copied (As this class contains pointers)
CLReverseKernel() [3/3]
CLReverseKernel (CLReverseKernel &&) default
Allow instances of this class to be moved.
~CLReverseKernel()
~CLReverseKernel () default
Default destructor.
Member Function Documentation
configure() [1/2]
void configure (const CLCompileContext & compile_context, const ICLTensor * input, ICLTensor * output, const ICLTensor * axis)
Initialise the kernel's inputis and output.
Parameters
[in] compile_context The compile context to be used.
[in] input Input tensor. Data types supported: All.
[out] output Output tensor. Data type supported: Same as input
[in] axis Axis tensor. Contains the indices of the dimensions to reverse. Data type supported: U32
Definition at line 72 of file CLReverseKernel.cpp.
 {
     ARM_COMPUTE_ERROR_ON_NULLPTR(input, output, axis);
     auto padding_info = get_padding_info({ input, output, axis });
     _input  = input;
     _output = output;
     _axis   = axis;
     // Output tensor auto initialization if not yet initialized
     auto_init_if_empty(*output->info(), *input->info()->clone());
     ARM_COMPUTE_ERROR_THROW_ON(validate_arguments(input->info(), output->info(), axis->info()));
     // Set kernel build options
     CLBuildOptions build_opts;
     build_opts.add_option("-DNUM_REVERSE_DIMS=" + support::cpp11::to_string(axis->info()->dimension(0)));
     build_opts.add_option("-DDATA_TYPE=" + get_cl_unsigned_type_from_element_size(input->info()->element_size()));
     // Create kernel
     _kernel = create_kernel(compile_context, "reverse", build_opts.options());
     // Set static kernel arguments
     unsigned int idx = 2 * num_arguments_per_4D_tensor() + num_arguments_per_1D_tensor();
     add_argument<cl_uint>(idx, input->info()->dimension(0));
     add_argument<cl_uint>(idx, input->info()->dimension(1));
     add_argument<cl_uint>(idx, input->info()->dimension(2));
     add_argument<cl_uint>(idx, input->info()->dimension(3));
     // Configure kernel window
     Window win = calculate_max_window(*output->info(), Steps());
     ICLKernel::configure_internal(win);
     // Set config_id for enabling LWS tuning
     _config_id += "reverse_";
     _config_id += lower_string(string_from_data_type(input->info()->data_type()));
     _config_id += "_";
     _config_id += support::cpp11::to_string(input->info()->dimension(0));
     _config_id += "_";
     _config_id += support::cpp11::to_string(input->info()->dimension(1));
     _config_id += "_";
     _config_id += support::cpp11::to_string(input->info()->dimension(2));
     ARM_COMPUTE_ERROR_ON(has_padding_changed(padding_info));
 }
References CLReverseKernel::_axis, CLReverseKernel::_input, CLReverseKernel::_output, CLBuildOptions::add_option(), ARM_COMPUTE_ERROR_ON, ARM_COMPUTE_ERROR_ON_NULLPTR, ARM_COMPUTE_ERROR_THROW_ON, arm_compute::auto_init_if_empty(), arm_compute::calculate_max_window(), arm_compute::create_kernel(), ITensorInfo::dimension(), arm_compute::get_cl_unsigned_type_from_element_size(), arm_compute::get_padding_info(), arm_compute::has_padding_changed(), ITensor::info(), arm_compute::test::validation::input, arm_compute::lower_string(), ICLKernel::num_arguments_per_1D_tensor(), ICLKernel::num_arguments_per_4D_tensor(), CLBuildOptions::options(), arm_compute::string_from_data_type(), arm_compute::support::cpp11::to_string(), and arm_compute::cpu::kernels::validate_arguments().
configure() [2/2]
void configure (const ICLTensor * input, ICLTensor * output, const ICLTensor * axis)
Initialise the kernel's inputis and output.
Parameters
[in] input Input tensor. Data types supported: All.
[out] output Output tensor. Data type supported: Same as input
[in] axis Axis tensor. Contains the indices of the dimensions to reverse. Data type supported: U32
Definition at line 67 of file CLReverseKernel.cpp.
 {
     configure(CLKernelLibrary::get().get_compile_context(), input, output, axis);
 }
References CLKernelLibrary::get(), and arm_compute::test::validation::input.
operator=() [1/2]
CLReverseKernel& operator= (CLReverseKernel &&) default
Allow instances of this class to be moved.
operator=() [2/2]
CLReverseKernel& operator= (const CLReverseKernel &) delete
Prevent instances of this class from being copied (As this class contains pointers)
run()
void run (const Window & window, cl::CommandQueue & queue) override virtual
Enqueue the OpenCL kernel to process the given window on the passed OpenCL command queue.
Note
The queue is not flushed by this method, and therefore the kernel will not have been executed by the time this method returns.
Parameters
[in] window Region on which to execute the kernel. (Must be a valid region of the window returned by window()).
[in,out] queue Command queue on which to enqueue the kernel.
Reimplemented from ICLKernel.
Definition at line 123 of file CLReverseKernel.cpp.
 {
     ARM_COMPUTE_ERROR_ON_UNCONFIGURED_KERNEL(this);
     ARM_COMPUTE_ERROR_ON_INVALID_SUBWINDOW(ICLKernel::window(), window);
     Window collapsed  = window.collapse(ICLKernel::window(), Window::DimZ);
     Window slice      = collapsed.first_slice_window_4D();
     Window axis_slice = collapsed.first_slice_window_1D();
     do
     {
         unsigned int idx = 0;
         add_4D_tensor_argument(idx, _input, slice);
         add_1D_tensor_argument(idx, _axis, axis_slice);
         add_4D_tensor_argument(idx, _output, slice);
         enqueue(queue, *this, slice, lws_hint());
     }
     while(collapsed.slide_window_slice_4D(slice));
 }
References CLReverseKernel::_axis, CLReverseKernel::_input, CLReverseKernel::_output, ICLKernel::add_1D_tensor_argument(), ICLKernel::add_4D_tensor_argument(), ARM_COMPUTE_ERROR_ON_INVALID_SUBWINDOW, ARM_COMPUTE_ERROR_ON_UNCONFIGURED_KERNEL, Window::collapse(), Window::DimZ, arm_compute::enqueue(), Window::first_slice_window_1D(), Window::first_slice_window_4D(), ICLKernel::lws_hint(), arm_compute::test::validation::reference::slice(), Window::slide_window_slice_4D(), and IKernel::window().
validate()
Status validate (const ITensorInfo * input, const ITensorInfo * output, const ITensorInfo * axis) static
Static function to check if given info will lead to a valid configuration of CLReverseKernel.
Parameters
[in] input Input tensor info. Data types supported: All.
[in] output Output tensor info. Data type supported: Same as input
[in] axis Axis tensor info. Contains the indices of the dimensions to reverse. Data type supported: U32
Returns
a status
Definition at line 117 of file CLReverseKernel.cpp.
 {
     ARM_COMPUTE_RETURN_ON_ERROR(validate_arguments(input, output, axis));
     return Status{};
 }
References ARM_COMPUTE_RETURN_ON_ERROR, arm_compute::test::validation::input, and arm_compute::cpu::kernels::validate_arguments().
Referenced by CLReverse::validate().
Field Documentation
_axis
const ICLTensor* _axis
Definition at line 81 of file CLReverseKernel.h.
Referenced by CLReverseKernel::configure(), and CLReverseKernel::run().
_input
const ICLTensor* _input
Definition at line 79 of file CLReverseKernel.h.
Referenced by CLReverseKernel::configure(), and CLReverseKernel::run().
_output
ICLTensor* _output
Definition at line 80 of file CLReverseKernel.h.
Referenced by CLReverseKernel::configure(), and CLReverseKernel::run().
The documentation for this class was generated from the following files:
src/core/CL/kernels/CLReverseKernel.h
src/core/CL/kernels/CLReverseKernel.cpp