Compute Library: Window Class Reference
Window Class Reference
Describe a multidimensional execution window.
#include <Window.h>
Data Structures
class Dimension
Describe one of the image's dimensions with a start, end and step.
Public Member Functions
constexpr Window ()
Default constructor: create a window containing a single element.
Window (const Window &src)
Copy constructor.
Window & operator= (const Window &rhs)
Copy assignment operator.
constexpr const Dimension & operator[] (size_t dimension) const
Read only access to a given dimension of the window.
constexpr const Dimension & x () const
Alias to access the first dimension of the window.
constexpr const Dimension & y () const
Alias to access the second dimension of the window.
constexpr const Dimension & z () const
Alias to access the third dimension of the window.
void set (size_t dimension, const Dimension &dim)
Set the values of a given dimension.
void set_broadcasted (size_t dimension)
Set the dimension as broadcasted dimension.
bool is_broadcasted (size_t dimension) const
Return whether a dimension has been broadcasted.
void use_tensor_dimensions (const TensorShape &shape, size_t first_dimension=Window::DimX)
Use the tensor's dimensions to fill the window dimensions.
void shift (size_t dimension, int shift_value)
Shift the values of a given dimension by the given shift_value.
Window shift_dimensions (unsigned int shift_value) const
Shift down all the dimensions of a window.
void adjust (size_t dimension, int adjust_value, bool is_at_start)
Adjust the start or end of a given dimension by the given value.
void scale (size_t dimension, float scale_value)
Scale the values of a given dimension by the given scale_value.
void set_dimension_step (size_t dimension, int step)
Set the step of a given dimension.
void validate () const
Will validate all the window's dimensions' values when asserts are enabled.
constexpr size_t num_iterations (size_t dimension) const
Return the number of iterations needed to iterate through a given dimension.
size_t num_iterations_total () const
Return the total number of iterations needed to iterate through the entire window.
TensorShape shape () const
Return the shape of the window in number of steps.
Window split_window (size_t dimension, size_t id, size_t total) const
Split a window into a set of sub windows along a given dimension.
Window first_slice_window_1D () const
First 1D slice of the window.
Window first_slice_window_2D () const
First 2D slice of the window.
Window first_slice_window_3D () const
First 3D slice of the window.
Window first_slice_window_4D () const
First 4D slice of the window.
bool slide_window_slice_1D (Window &slice) const
Slide the passed 1D window slice.
bool slide_window_slice_2D (Window &slice) const
Slide the passed 2D window slice.
bool slide_window_slice_3D (Window &slice) const
Slide the passed 3D window slice.
bool slide_window_slice_4D (Window &slice) const
Slide the passed 4D window slice.
Window collapse_if_possible (const Window &full_window, size_t first, size_t last, bool *has_collapsed=nullptr) const
Collapse the dimensions between first and last if possible.
Window collapse_if_possible (const Window &full_window, size_t first, bool *has_collapsed=nullptr) const
Collapse the dimensions higher than first if possible.
Window collapse (const Window &full_window, size_t first, size_t last=Coordinates::num_max_dimensions) const
Collapse the dimensions between first and last.
Window broadcast_if_dimension_le_one (const TensorShape &shape) const
Don't advance in the dimension where shape is less equal to 1.
Window broadcast_if_dimension_le_one (const ITensorInfo &info) const
Don't advance in the dimension where shape of info is less equal to 1.
Static Public Attributes
static constexpr size_t DimX = 0
Alias for dimension 0 also known as X dimension.
static constexpr size_t DimY = 1
Alias for dimension 1 also known as Y dimension.
static constexpr size_t DimZ = 2
Alias for dimension 2 also known as Z dimension.
static constexpr size_t DimW = 3
Alias for dimension 3 also known as W dimension.
static constexpr size_t DimV = 4
Alias for dimension 4 also known as V dimension.
Friends
void swap (Window &lhs, Window &rhs)
Friend function that swaps the contents of two windows.
bool operator== (const Window &lhs, const Window &rhs)
Check whether two Windows are equal.
Detailed Description
Describe a multidimensional execution window.
Definition at line 39 of file Window.h.
Constructor & Destructor Documentation
Window() [1/2]
constexpr Window () inline constexpr
Default constructor: create a window containing a single element.
Definition at line 54 of file Window.h.
         : _dims(), _is_broadcasted(utility::generate_array<bool, Coordinates::num_max_dimensions, false>::value)
     {
     }
Window() [2/2]
Window (const Window & src) inline
Copy constructor.
Parameters
[in] src Copy the values from src to a new object
Definition at line 26 of file Window.inl.
     : _dims(), _is_broadcasted(utility::generate_array<bool, Coordinates::num_max_dimensions, false>::value)
 {
     for(size_t i = 0; i < Coordinates::num_max_dimensions; ++i)
     {
         set(i, src[i]);
         _is_broadcasted[i] = src.is_broadcasted(i);
     }
 }
References Dimensions< int >::num_max_dimensions, Window::set(), and arm_compute::test::validation::src.
Member Function Documentation
adjust()
void adjust (size_t dimension, int adjust_value, bool is_at_start) inline
Adjust the start or end of a given dimension by the given value.
Parameters
[in] dimension The dimension to adjust
[in] adjust_value The adjusted value.
[in] is_at_start The flag to indicate whether adjust the start or end of the dimension.
Definition at line 140 of file Window.inl.
 {
     ARM_COMPUTE_ERROR_ON(dimension >= Coordinates::num_max_dimensions);
     Window::Dimension &d = _dims[dimension];
     if(is_at_start)
     {
         d = Window::Dimension(d.start() + adjust_value, d.end(), d.step());
     }
     else
     {
         d = Window::Dimension(d.start(), d.end() + adjust_value, d.step());
     }
 }
References ARM_COMPUTE_ERROR_ON, Window::Dimension::end(), Dimensions< int >::num_max_dimensions, Window::Dimension::start(), and Window::Dimension::step().
broadcast_if_dimension_le_one() [1/2]
Window broadcast_if_dimension_le_one (const ITensorInfo & info) const inline
Don't advance in the dimension where shape of info is less equal to 1.
Parameters
[in] info An ITensorInfo.
Returns
Broadcast window.
Definition at line 419 of file Window.h.
     {
         return broadcast_if_dimension_le_one(info.tensor_shape());
     }
References Window::broadcast_if_dimension_le_one(), and arm_compute::test::validation::info.
broadcast_if_dimension_le_one() [2/2]
Window broadcast_if_dimension_le_one (const TensorShape & shape) const inline
Don't advance in the dimension where shape is less equal to 1.
Parameters
[in] shape A TensorShape.
Returns
Broadcast window.
Definition at line 120 of file Window.inl.
 {
     Window broadcastWin(*this);
     for(size_t d = 0; d < TensorShape::num_max_dimensions; ++d)
     {
         if(shape[d] <= 1)
         {
             broadcastWin.set_broadcasted(d);
         }
     }
     return broadcastWin;
 }
References Dimensions< size_t >::num_max_dimensions, Window::set_broadcasted(), and Window::shape().
Referenced by arm_compute::cpu::add_qasymm8_signed_sve2(), arm_compute::cpu::add_qasymm8_sve2(), arm_compute::cpu::add_qsymm16_neon(), arm_compute::cpu::add_qsymm16_sve2(), arm_compute::cpu::add_same_neon(), arm_compute::cpu::add_same_sve(), arm_compute::cpu::add_sub_q8_neon_fixedpoint(), arm_compute::cpu::add_sub_qasymm8_neon(), arm_compute::cpu::add_sub_qasymm8_signed_neon(), Window::broadcast_if_dimension_le_one(), arm_compute::cpu::elementwise_arithmetic_op(), arm_compute::cpu::elementwise_arithmetic_quantized_op(), arm_compute::cpu::elementwise_comp_quantized_signed(), arm_compute::cpu::elementwise_comparison_op(), arm_compute::cpu::elementwise_comparison_quantized_op(), arm_compute::cpu::elementwise_op(), arm_compute::cpu::elementwise_op_quantized(), arm_compute::cpu::elementwise_op_quantized_signed(), arm_compute::cpu::sub_qsymm16_neon(), and arm_compute::cpu::sub_same_neon().
collapse()
Window collapse (const Window & full_window, size_t first, size_t last = Coordinates::num_max_dimensions) const inline
Collapse the dimensions between first and last.
A dimension is collapsable if it starts from 0 and matches the corresponding dimension in the full_window
Parameters
[in] full_window Full window window has been created from.
[in] first Start dimension into which the following are collapsed.
[in] last End (exclusive) dimension to collapse.
Returns
Collapsed window if successful.
Definition at line 111 of file Window.inl.
 {
     bool   has_collapsed = false;
     Window collapsed     = collapse_if_possible(full_window, first, last, &has_collapsed);
     // Make sure that the window has collapsed
     ARM_COMPUTE_ERROR_ON(!has_collapsed);
     return collapsed;
 }
References ARM_COMPUTE_ERROR_ON, and Window::collapse_if_possible().
Referenced by ClWidthConcatenate2TensorsKernel::configure(), ClHeightConcatenateKernel::configure(), ClMatMulNativeKernel::configure(), ClWidthConcatenateKernel::configure(), ClMatMulLowpNativeKernel::configure(), ClWidthConcatenate4TensorsKernel::configure(), ClTemplateCast::get_window(), ClTemplateLogits1DMaxShiftExpSum::get_window(), ClTemplateLogits1DNorm::get_window(), ClTemplateDepthwiseConv2d::get_window(), ClTemplateReshape::get_window(), ClTemplateActivation::get_window(), ClTemplateResize::get_window(), CLInstanceNormalizationLayerKernel::run(), CLReverseKernel::run(), CLComputeAllAnchorsKernel::run(), CLStackLayerKernel::run(), CLDepthwiseConvolutionLayerNativeKernel::run(), CLFuseBatchNormalizationKernel::run(), CLComputeMeanVariance::run(), ClScaleKernel::run_op(), ClMatMulNativeKernel::run_op(), ClMatMulLowpNativeKernel::run_op(), and ClPermuteKernel::run_op().
collapse_if_possible() [1/2]
Window collapse_if_possible (const Window & full_window, size_t first, bool * has_collapsed = nullptr) const inline
Collapse the dimensions higher than first if possible.
A dimension is collapsable if it starts from 0 and matches the corresponding dimension in the full_window
Parameters
[in] full_window Full window window has been created from.
[in] first Start dimension into which the following are collapsed.
[out] has_collapsed (Optional) Whether the window was collapsed.
Returns
Collapsed window.
Definition at line 388 of file Window.h.
     {
         return collapse_if_possible(full_window, first, Coordinates::num_max_dimensions, has_collapsed);
     }
References Window::collapse_if_possible(), and Dimensions< int >::num_max_dimensions.
collapse_if_possible() [2/2]
Window collapse_if_possible (const Window & full_window, size_t first, size_t last, bool * has_collapsed = nullptr) const inline
Collapse the dimensions between first and last if possible.
A dimension is collapsable if it starts from 0 and matches the corresponding dimension in the full_window
Parameters
[in] full_window Full window window has been created from.
[in] first Start dimension into which the following are collapsed.
[in] last End (exclusive) dimension to collapse.
[out] has_collapsed (Optional) Whether the window was collapsed.
Returns
Collapsed window.
Definition at line 68 of file Window.inl.
 {
     Window collapsed(*this);
     bool is_collapsable = true;
     int  collapsed_end  = _dims[first].end();
     for(size_t d = first + 1; is_collapsable && (d < last); ++d)
     {
         // The _dims's dimension must match the full _dims dimension to be collapsable:
         is_collapsable = (_dims[d].start() == 0) && (full_window[d].start() == 0) && (_dims[d].step() <= 1)
                          && (full_window[d].end() == _dims[d].end());
         collapsed_end *= _dims[d].end();
     }
     if(is_collapsable)
     {
         collapsed._dims.at(first).set_end(collapsed_end);
         for(size_t d = first + 1; is_collapsable && (d < last); ++d)
         {
             collapsed.set(d, Dimension());
         }
     }
     if(has_collapsed != nullptr)
     {
         *has_collapsed = is_collapsable;
     }
     return collapsed;
 }
References arm_compute::mlgo::parser::end(), Window::set(), and arm_compute::cpu::step.
Referenced by Window::collapse(), Window::collapse_if_possible(), ClCastKernel::configure(), arm_compute::cpu::fp_neon_activation_impl(), arm_compute::cpu::l2_normalize_x(), arm_compute::cpu::matrix_addition_f32(), arm_compute::cpu::neon_qasymm8_activation(), arm_compute::cpu::neon_qasymm8_signed_activation(), arm_compute::cpu::neon_qsymm16_activation(), NEReorgLayerKernel::run(), CLSelectKernel::run(), CLDeconvolutionLayerUpsampleKernel::run(), CLFFTScaleKernel::run(), CLGatherKernel::run(), CLNormalizationLayerKernel::run(), CLComparisonKernel::run(), CLTileKernel::run(), CLFFTDigitReverseKernel::run(), CLNormalizePlanarYUVLayerKernel::run(), CLReductionOperationKernel::run(), CLFillBorderKernel::run(), CLFFTRadixStageKernel::run(), CLDeconvolutionReshapeOutputKernel::run(), CpuFillKernel::run_op(), ClElementwiseKernel::run_op(), CpuConvertQuantizedSignednessKernel::run_op(), ClDequantizeKernel::run_op(), ClFloorKernel::run_op(), ClReshapeKernel::run_op(), ClCopyKernel::run_op(), ClElementWiseUnaryKernel::run_op(), ClFillKernel::run_op(), ClPool2dKernel::run_op(), ClPool3dKernel::run_op(), ClActivationKernel::run_op(), ClQuantizeKernel::run_op(), ClWinogradInputTransformKernel::run_op(), ClGemmLowpQuantizeDownInt32ScaleByFixedPointKernel::run_op(), ClWinogradOutputTransformKernel::run_op(), ClCastKernel::run_op(), ClGemmLowpQuantizeDownInt32ScaleByFloatKernel::run_op(), ClGemmLowpQuantizeDownInt32ScaleKernel::run_op(), CLStridedSliceKernel::run_op(), ClCol2ImKernel::run_op(), ClGemmLowpOffsetContributionKernel::run_op(), ClGemmLowpOffsetContributionOutputStageKernel::run_op(), ClLogits1DMaxShiftExpSumKernel::run_op(), ClMulKernel::run_op(), ClGemmLowpMatrixAReductionKernel::run_op(), CLFillBorderKernel::run_op(), ClIm2ColKernel::run_op(), ClLogits1DNormKernel::run_op(), ClComplexMulKernel::run_op(), ClGemmLowpMatrixBReductionKernel::run_op(), arm_compute::cpu::sve2_qasymm8_activation(), arm_compute::cpu::sve2_qasymm8_signed_activation(), arm_compute::cpu::sve2_qsymm16_activation(), and arm_compute::cpu::sve_fp32_activation().
first_slice_window_1D()
Window first_slice_window_1D () const inline
First 1D slice of the window.
Returns
The first slice of the window.
Definition at line 289 of file Window.h.
     {
         return first_slice_window<1>();
     };
Referenced by NETileKernel::run(), CLReverseKernel::run(), CLSelectKernel::run(), CLQLSTMLayerNormalizationKernel::run(), CLNormalizePlanarYUVLayerKernel::run(), CLReductionOperationKernel::run(), CLBatchNormalizationLayerKernel::run(), CLFuseBatchNormalizationKernel::run(), CLBatchToSpaceLayerKernel::run(), CLSpaceToBatchLayerKernel::run(), CpuCopyKernel::run_op(), and ClWeightsReshapeKernel::run_op().
first_slice_window_2D()
Window first_slice_window_2D () const inline
First 2D slice of the window.
Returns
The first slice of the window.
Definition at line 297 of file Window.h.
     {
         return first_slice_window<2>();
     };
Referenced by ICLSimple2DKernel::run(), CLBitwiseKernel::run(), NEDepthToSpaceLayerKernel::run(), CLQLSTMLayerNormalizationKernel::run(), CLMeanStdDevNormalizationKernel::run(), CLReductionOperationKernel::run(), CLPriorBoxLayerKernel::run(), CLL2NormalizeLayerKernel::run(), CLBoundingBoxTransformKernel::run(), CLArgMinMaxLayerKernel::run(), CLSpaceToBatchLayerKernel::run(), ClTransposeKernel::run_op(), ClScaleKernel::run_op(), ClGemmLowpMatrixAReductionKernel::run_op(), ClWeightsReshapeKernel::run_op(), ClIm2ColKernel::run_op(), and ClGemmLowpMatrixBReductionKernel::run_op().
first_slice_window_3D()
Window first_slice_window_3D () const inline
First 3D slice of the window.
Returns
The first slice of the window.
Definition at line 305 of file Window.h.
     {
         return first_slice_window<3>();
     };
Referenced by ICLSimple3DKernel::run(), NEDepthToSpaceLayerKernel::run(), NESpaceToDepthLayerKernel::run(), CLSelectKernel::run(), CLDepthToSpaceLayerKernel::run(), CLSpaceToDepthLayerKernel::run(), CLDeconvolutionLayerUpsampleKernel::run(), CLFFTScaleKernel::run(), CLMaxUnpoolingLayerKernel::run(), CLNormalizationLayerKernel::run(), CLComparisonKernel::run(), CLROIPoolingLayerKernel::run(), CLFFTDigitReverseKernel::run(), CLReorgLayerKernel::run(), CLNormalizePlanarYUVLayerKernel::run(), CLReductionOperationKernel::run(), CLPadLayerKernel::run(), CLFFTRadixStageKernel::run(), CLFillBorderKernel::run(), CLL2NormalizeLayerKernel::run(), CLArgMinMaxLayerKernel::run(), NEBatchToSpaceLayerKernel::run(), NESpaceToBatchLayerKernel::run(), CLROIAlignLayerKernel::run(), CLBatchNormalizationLayerKernel::run(), CLFuseBatchNormalizationKernel::run(), CLBatchToSpaceLayerKernel::run(), CLSpaceToBatchLayerKernel::run(), ClElementwiseKernel::run_op(), ClKernelRuntime::run_op(), ClReshapeKernel::run_op(), ClDequantizeKernel::run_op(), ClFloorKernel::run_op(), ClTransposedConvolutionKernel::run_op(), ClCopyKernel::run_op(), ClElementWiseUnaryKernel::run_op(), ClFillKernel::run_op(), ClPool2dKernel::run_op(), ClActivationKernel::run_op(), ClQuantizeKernel::run_op(), ClDepthConcatenateKernel::run_op(), ClBatchConcatenateKernel::run_op(), ClGemmLowpMatrixMultiplyNativeKernel::run_op(), ClGemmReshapeLhsMatrixKernel::run_op(), ClWinogradInputTransformKernel::run_op(), ClGemmLowpQuantizeDownInt32ScaleByFixedPointKernel::run_op(), ClIndirectConv2dKernel::run_op(), ClGemmLowpQuantizeDownInt32ScaleKernel::run_op(), ClCastKernel::run_op(), ClGemmLowpQuantizeDownInt32ScaleByFloatKernel::run_op(), ClIndirectConv2dAddressPrecalculationKernel::run_op(), ClGemmMatrixMultiplyNativeKernel::run_op(), ClGemmMatrixMultiplyReshapedOnlyRhsMMULKernel::run_op(), ClGemmReshapeRhsMatrixKernel::run_op(), ClGemmLowpMatrixMultiplyReshapedKernel::run_op(), ClGemmLowpOffsetContributionKernel::run_op(), ClCol2ImKernel::run_op(), ClGemmLowpOffsetContributionOutputStageKernel::run_op(), ClDirectConv2dKernel::run_op(), ClGemmLowpMatrixMultiplyReshapedOnlyRhsMMULKernel::run_op(), ClDirectConv3dKernel::run_op(), ClLogits1DMaxShiftExpSumKernel::run_op(), ClMulKernel::run_op(), ClGemmLowpMatrixMultiplyReshapedOnlyRhsKernel::run_op(), CLFillBorderKernel::run_op(), ClWeightsReshapeKernel::run_op(), ClGemmMatrixMultiplyReshapedOnlyRhsKernel::run_op(), ClIm2ColKernel::run_op(), ClGemmMatrixMultiplyReshapedKernel::run_op(), ClLogits1DNormKernel::run_op(), and ClComplexMulKernel::run_op().
first_slice_window_4D()
Window first_slice_window_4D () const inline
First 4D slice of the window.
Returns
The first slice of the window.
Definition at line 313 of file Window.h.
     {
         return first_slice_window<4>();
     };
Referenced by CLDepthToSpaceLayerKernel::run(), CLSpaceToDepthLayerKernel::run(), CLReverseKernel::run(), CLTileKernel::run(), CLReductionOperationKernel::run(), CLStackLayerKernel::run(), CLDepthwiseConvolutionLayerNativeKernel::run(), CLArgMinMaxLayerKernel::run(), CLBatchToSpaceLayerKernel::run(), CLSpaceToBatchLayerKernel::run(), ClScaleKernel::run_op(), ClWidthConcatenate2TensorsKernel::run_op(), ClPool2dKernel::run_op(), ClPermuteKernel::run_op(), ClWidthConcatenate4TensorsKernel::run_op(), ClWinogradOutputTransformKernel::run_op(), CLStridedSliceKernel::run_op(), and ClCol2ImKernel::run_op().
is_broadcasted()
bool is_broadcasted (size_t dimension) const inline
Return whether a dimension has been broadcasted.
Parameters
[in] dimension The requested dimension
Returns
true if the dimension has been broadcasted
Definition at line 62 of file Window.inl.
 {
     ARM_COMPUTE_ERROR_ON(dimension >= Coordinates::num_max_dimensions);
     return _is_broadcasted[dimension];
 }
References ARM_COMPUTE_ERROR_ON, and Dimensions< int >::num_max_dimensions.
Referenced by ICLKernel::add_tensor_argument().
num_iterations()
constexpr size_t num_iterations (size_t dimension) const inline constexpr
Return the number of iterations needed to iterate through a given dimension.
Parameters
[in] dimension The requested dimension
Returns
The number of iterations
Definition at line 182 of file Window.inl.
 {
     // Precondition: dimension < Coordinates::num_max_dimensions
     // Precondition: (end - start) % step == 0
     return (_dims.at(dimension).end() - _dims.at(dimension).start()) / _dims.at(dimension).step();
 }
Referenced by ClCopyKernel::configure(), ClFillKernel::configure(), ClCropKernel::configure(), CpuSubKernel::get_mws(), CpuAddKernel::get_mws(), CpuMulKernel::get_mws(), CpuArithmeticKernel::get_mws(), CpuDivisionKernel::get_mws(), Window::num_iterations_total(), SingleThreadScheduler::schedule(), OMPScheduler::schedule_op(), and Window::split_window().
num_iterations_total()
size_t num_iterations_total () const inline
Return the total number of iterations needed to iterate through the entire window.
Returns
Number of total iterations
Definition at line 294 of file Window.inl.
 {
     size_t total = 1;
     for(size_t d = 0; d < Coordinates::num_max_dimensions; ++d)
     {
         total *= num_iterations(d);
     }
     return total;
 }
References Window::num_iterations(), and Dimensions< int >::num_max_dimensions.
Referenced by CpuSubKernel::get_mws(), CpuMulKernel::get_mws(), CpuAddKernel::get_mws(), CpuArithmeticKernel::get_mws(), and CpuDivisionKernel::get_mws().
operator=()
Window & operator= (const Window & rhs) inline
Copy assignment operator.
Parameters
[in] rhs Copy the values from rhs to the current object
Returns
Reference to the updated object
Definition at line 36 of file Window.inl.
 {
     Window tmp(rhs);
     swap(*this, tmp);
     return *this;
 }
References Window::swap.
operator[]()
constexpr const Window::Dimension & operator[] (size_t dimension) const inline constexpr
Read only access to a given dimension of the window.
Note
Precondition: dimension < Coordinates::num_max_dimensions
Parameters
[in] dimension The dimension to access
Returns
The requested dimension
Definition at line 43 of file Window.inl.
 {
     // Precondition: dimension < Coordinates::num_max_dimensions
     return _dims.at(dimension);
 }
scale()
void scale (size_t dimension, float scale_value) inline
Scale the values of a given dimension by the given scale_value.
Note
The end of the window is rounded up to be a multiple of step after the scaling.
Parameters
[in] dimension The dimension to scale
[in] scale_value Value to scale the start, end and step values of.
Definition at line 155 of file Window.inl.
 {
     ARM_COMPUTE_ERROR_ON(dimension >= Coordinates::num_max_dimensions);
     Window::Dimension &d            = _dims[dimension];
     const int          scaled_step  = d.step() * scale_value;
     const int          scaled_start = d.start() * scale_value;
     const int          scaled_diff  = (d.end() - d.start()) * scale_value;
     const int          scaled_end   = scaled_start + ceil_to_multiple(scaled_diff, scaled_step);
     d = Window::Dimension(scaled_start, scaled_end, scaled_step);
 }
References ARM_COMPUTE_ERROR_ON, arm_compute::ceil_to_multiple(), Window::Dimension::end(), Dimensions< int >::num_max_dimensions, Window::Dimension::start(), and Window::Dimension::step().
Referenced by CpuGemmInterleave4x4Kernel::run_op().
set()
void set (size_t dimension, const Dimension & dim) inline
Set the values of a given dimension.
Parameters
[in] dimension The dimension to set
[in] dim The values to set the dimension to
Definition at line 49 of file Window.inl.
 {
     ARM_COMPUTE_ERROR_ON(dimension >= Coordinates::num_max_dimensions);
     _dims[dimension] = dim;
 }
References ARM_COMPUTE_ERROR_ON, and Dimensions< int >::num_max_dimensions.
Referenced by arm_compute::cpu::add_qasymm8_signed_sve2(), arm_compute::cpu::add_qasymm8_sve2(), arm_compute::cpu::add_qsymm16_neon(), arm_compute::cpu::add_qsymm16_sve2(), arm_compute::cpu::add_same_neon(), arm_compute::cpu::add_same_sve(), arm_compute::cpu::add_sub_q8_neon_fixedpoint(), arm_compute::cpu::add_sub_qasymm8_neon(), arm_compute::cpu::add_sub_qasymm8_signed_neon(), arm_compute::cpu::bilinear_neon_scale(), arm_compute::calculate_max_enlarged_window(), arm_compute::calculate_max_window(), arm_compute::calculate_max_window_horizontal(), arm_compute::calculate_squashed_or_max_window(), Window::collapse_if_possible(), arm_compute::colorconvert_iyuv_to_nv12(), arm_compute::colorconvert_iyuv_to_rgb(), arm_compute::colorconvert_iyuv_to_yuv4(), arm_compute::colorconvert_nv12_to_iyuv(), arm_compute::colorconvert_nv12_to_rgb(), arm_compute::colorconvert_nv12_to_yuv4(), arm_compute::colorconvert_rgb_to_iyuv(), arm_compute::colorconvert_rgb_to_nv12(), arm_compute::colorconvert_yuyv_to_iyuv(), arm_compute::colorconvert_yuyv_to_nv12(), ClDequantizeKernel::configure(), ClCopyKernel::configure(), ClElementWiseUnaryKernel::configure(), ClFillKernel::configure(), ClQuantizeKernel::configure(), ClCropKernel::configure(), CLStridedSliceKernel::configure(), NEBoundingBoxTransformKernel::configure(), NEROIPoolingLayerKernel::configure(), CLTileKernel::configure(), CLReductionOperationKernel::configure(), NEROIAlignLayerKernel::configure(), CpuWeightsReshapeKernel::configure(), CLFillBorderKernel::configure(), NEFillBorderKernel::configure(), CpuIm2ColKernel::configure(), CLCropResize::configure(), arm_compute::cpu::kernels::convolve_nchw(), arm_compute::cpu::kernels::convolve_nhwc(), create_window(), arm_compute::cpu::directconv3d_float_neon_ndhwc(), arm_compute::cpu::directconv3d_quantized_neon_ndhwc(), arm_compute::cpu::elementwise_arithmetic_op(), arm_compute::cpu::elementwise_arithmetic_quantized_op(), arm_compute::cpu::elementwise_comp_quantized_signed(), arm_compute::cpu::elementwise_comparison_op(), arm_compute::cpu::elementwise_comparison_quantized_op(), arm_compute::cpu::elementwise_op(), arm_compute::cpu::elementwise_op< int8_t >(), arm_compute::cpu::elementwise_op< uint8_t >(), arm_compute::cpu::elementwise_op_quantized(), arm_compute::cpu::elementwise_op_quantized_signed(), arm_compute::cpu::elementwise_sve_op(), AssetsLibrary::fill_borders_with_garbage(), IImageLoader::fill_image(), IImageLoader::fill_planar_tensor(), arm_compute::cpu::fp_neon_activation_impl(), arm_compute::cpu::fused_batch_normalization_conv(), arm_compute::cpu::fused_batch_normalization_dwc_nchw(), arm_compute::cpu::fused_batch_normalization_dwc_nhwc(), ClTemplateDirectConv2d::get_window(), IKernel::IKernel(), arm_compute::cpu::instance_normalization_nchw(), arm_compute::cpu::l2_normalize_x(), arm_compute::cpu::l2_normalize_yz(), arm_compute::utils::load_trained_data(), arm_compute::cpu::matrix_addition_f32(), arm_compute::cpu::matrix_matrix_multiply_f32(), arm_compute::cpu::mean_stddev_normalization(), arm_compute::cpu::nearest_neon_scale(), arm_compute::cpu::neon_logits_1d_max(), arm_compute::cpu::neon_qasymm8_activation(), arm_compute::cpu::neon_qasymm8_meanstddevnorm(), arm_compute::cpu::neon_qasymm8_signed_activation(), arm_compute::cpu::neon_qsymm16_activation(), arm_compute::cpu::neon_range_function(), arm_compute::cpu::poolingMxN_fp32_neon_nhwc(), arm_compute::cpu::poolingMxN_fp32_neon_nhwc_kernel_indices(), arm_compute::cpu::poolingMxN_q8_neon_nhwc(), arm_compute::cpu::poolingMxNxD_fp_neon_ndhwc(), arm_compute::cpu::poolingMxNxD_q8_neon_ndhwc(), CPPUpsampleKernel::run(), NETileKernel::run(), NEDepthToSpaceLayerKernel::run(), NEFFTScaleKernel::run(), CLInstanceNormalizationLayerKernel::run(), CLSelectKernel::run(), CLSpaceToDepthLayerKernel::run(), CLDepthToSpaceLayerKernel::run(), CLDeconvolutionLayerUpsampleKernel::run(), NEFFTRadixStageKernel::run(), CLNormalizePlanarYUVLayerKernel::run(), CLReductionOperationKernel::run(), CLL2NormalizeLayerKernel::run(), CpuWinogradConv2d::run(), CLArgMinMaxLayerKernel::run(), NEBatchToSpaceLayerKernel::run(), CLBatchNormalizationLayerKernel::run(), CLBatchToSpaceLayerKernel::run(), CLSpaceToBatchLayerKernel::run(), CLComputeMeanVariance::run(), CpuFillKernel::run_op(), ClKernelRuntime::run_op(), CpuConvertQuantizedSignednessKernel::run_op(), CpuCopyKernel::run_op(), CpuConcatenateWidthKernel::run_op(), CpuConcatenateHeightKernel::run_op(), ClPool2dKernel::run_op(), CpuPool2dKernel::run_op(), ClPermuteKernel::run_op(), ClCropKernel::run_op(), CpuFloorKernel::run_op(), ClGemmLowpMatrixMultiplyNativeKernel::run_op(), CpuGemmLowpMatrixMultiplyKernel::run_op(), ClGemmLowpQuantizeDownInt32ScaleByFixedPointKernel::run_op(), CpuGemmInterleave4x4Kernel::run_op(), ClGemmLowpQuantizeDownInt32ScaleByFloatKernel::run_op(), ClWinogradOutputTransformKernel::run_op(), ClGemmLowpQuantizeDownInt32ScaleKernel::run_op(), ClGemmMatrixMultiplyNativeKernel::run_op(), CpuCastKernel::run_op(), CpuCol2ImKernel::run_op(), ClGemmLowpMatrixMultiplyReshapedKernel::run_op(), ClGemmLowpOffsetContributionKernel::run_op(), ClGemmLowpOffsetContributionOutputStageKernel::run_op(), ClLogits1DMaxShiftExpSumKernel::run_op(), ClGemmLowpMatrixAReductionKernel::run_op(), ClGemmLowpMatrixMultiplyReshapedOnlyRhsKernel::run_op(), ClGemmMatrixMultiplyReshapedOnlyRhsKernel::run_op(), CpuGemmTranspose1xWKernel::run_op(), ClIm2ColKernel::run_op(), NEStridedSliceKernel::run_op(), ClGemmMatrixMultiplyReshapedKernel::run_op(), ClLogits1DNormKernel::run_op(), ClGemmLowpMatrixBReductionKernel::run_op(), arm_compute::run_reverse(), arm_compute::utils::save_to_ppm(), arm_compute::cpu::select_op(), Window::set_broadcasted(), Window::shift_dimensions(), arm_compute::test::validation::reference::softmax_layer_generic(), Window::split_window(), arm_compute::cpu::sub_qsymm16_neon(), arm_compute::cpu::sub_same_neon(), arm_compute::cpu::sve2_qasymm8_activation(), arm_compute::cpu::sve2_qasymm8_signed_activation(), arm_compute::cpu::sve2_qsymm16_activation(), arm_compute::cpu::sve_fp32_activation(), arm_compute::cpu::sve_logits_1d_max(), arm_gemm::to_window(), AccessWindowTranspose::update_window_if_needed(), AccessWindowStatic::update_window_if_needed(), AccessWindowRectangle::update_window_if_needed(), Window::use_tensor_dimensions(), arm_compute::cpu::vector_matrix_multiply_f32(), and Window::Window().
set_broadcasted()
void set_broadcasted (size_t dimension) inline
Set the dimension as broadcasted dimension.
Parameters
[in] dimension The dimension to set
Definition at line 55 of file Window.inl.
 {
     ARM_COMPUTE_ERROR_ON(dimension >= Coordinates::num_max_dimensions);
     set(dimension, Dimension(0, 0, 0));
     _is_broadcasted[dimension] = true;
 }
References ARM_COMPUTE_ERROR_ON, Dimensions< int >::num_max_dimensions, and Window::set().
Referenced by Window::broadcast_if_dimension_le_one().
set_dimension_step()
void set_dimension_step (size_t dimension, int step) inline
Set the step of a given dimension.
Parameters
[in] dimension Dimension to update
[in] step The new dimension's step value
Definition at line 167 of file Window.inl.
 {
     ARM_COMPUTE_ERROR_ON(dimension >= Coordinates::num_max_dimensions);
     _dims[dimension].set_step(step);
 }
References ARM_COMPUTE_ERROR_ON, Dimensions< int >::num_max_dimensions, and arm_compute::cpu::step.
Referenced by CLROIPoolingLayerKernel::run(), CLROIAlignLayerKernel::run(), ClIm2ColKernel::run_op(), and WindowIterator< L >::set_step().
shape()
TensorShape shape () const inline
Return the shape of the window in number of steps.
Definition at line 284 of file Window.inl.
 {
     TensorShape shape;
     for(size_t d = 0; d < TensorShape::num_max_dimensions; ++d)
     {
         shape.set(d, (_dims[d].end() - _dims[d].start()) / _dims[d].step());
     }
     return shape;
 }
References arm_compute::mlgo::parser::end(), Dimensions< size_t >::num_max_dimensions, TensorShape::set(), and arm_compute::cpu::step.
Referenced by Window::broadcast_if_dimension_le_one(), ClWinogradInputTransformKernel::run_op(), NEStridedSliceKernel::run_op(), and Window::use_tensor_dimensions().
shift()
void shift (size_t dimension, int shift_value) inline
Shift the values of a given dimension by the given shift_value.
Parameters
[in] dimension The dimension to shift
[in] shift_value Value to shift the start and end values of.
Definition at line 133 of file Window.inl.
 {
     ARM_COMPUTE_ERROR_ON(dimension >= Coordinates::num_max_dimensions);
     Window::Dimension &d = _dims[dimension];
     d                    = Window::Dimension(d.start() + shift_value, d.end() + shift_value, d.step());
 }
References ARM_COMPUTE_ERROR_ON, Window::Dimension::end(), Dimensions< int >::num_max_dimensions, Window::Dimension::start(), and Window::Dimension::step().
shift_dimensions()
Window shift_dimensions (unsigned int shift_value) const inline
Shift down all the dimensions of a window.
i.e new_dims[n] = old_dims[n+shift_value].
Parameters
[in] shift_value Number of dimensions to shift the window by.
Returns
The window with the shifted dimensions.
Definition at line 101 of file Window.inl.
 {
     Window shifted_window;
     for(size_t n = 0; n < (Coordinates::num_max_dimensions - shift_value); n++)
     {
         shifted_window.set(n, _dims[n + shift_value]);
     }
     return shifted_window;
 }
References arm_compute::test::validation::n, Dimensions< int >::num_max_dimensions, and Window::set().
slide_window_slice_1D()
bool slide_window_slice_1D (Window & slice) const inline
Slide the passed 1D window slice.
If slice contains the last slice then it will remain unchanged and false will be returned.
Parameters
[in,out] slice Current slice, to be updated to the next slice.
Returns
true if slice contains a new slice, false if slice already contained the last slice
Definition at line 325 of file Window.h.
     {
         return slide_window_slice<1>(slice);
     }
References arm_compute::test::validation::reference::slice().
Referenced by ClWeightsReshapeKernel::run_op().
slide_window_slice_2D()
bool slide_window_slice_2D (Window & slice) const inline
Slide the passed 2D window slice.
If slice contains the last slice then it will remain unchanged and false will be returned.
Parameters
[in,out] slice Current slice, to be updated to the next slice.
Returns
true if slice contains a new slice, false if slice already contained the last slice
Definition at line 337 of file Window.h.
     {
         return slide_window_slice<2>(slice);
     }
References arm_compute::test::validation::reference::slice().
Referenced by ICLSimple2DKernel::run(), CLBitwiseKernel::run(), NEDepthToSpaceLayerKernel::run(), CLQLSTMLayerNormalizationKernel::run(), CLMeanStdDevNormalizationKernel::run(), CLReductionOperationKernel::run(), CLL2NormalizeLayerKernel::run(), CLArgMinMaxLayerKernel::run(), ClTransposeKernel::run_op(), ClScaleKernel::run_op(), ClGemmLowpMatrixAReductionKernel::run_op(), ClWeightsReshapeKernel::run_op(), ClIm2ColKernel::run_op(), and ClGemmLowpMatrixBReductionKernel::run_op().
slide_window_slice_3D()
bool slide_window_slice_3D (Window & slice) const inline
Slide the passed 3D window slice.
If slice contains the last slice then it will remain unchanged and false will be returned.
Parameters
[in,out] slice Current slice, to be updated to the next slice.
Returns
true if slice contains a new slice, false if slice already contained the last slice
Definition at line 349 of file Window.h.
     {
         return slide_window_slice<3>(slice);
     }
References arm_compute::test::validation::reference::slice().
Referenced by ICLSimple3DKernel::run(), NEDepthToSpaceLayerKernel::run(), NESpaceToDepthLayerKernel::run(), CLSelectKernel::run(), CLSpaceToDepthLayerKernel::run(), CLDepthToSpaceLayerKernel::run(), CLDeconvolutionLayerUpsampleKernel::run(), CLFFTScaleKernel::run(), CLMaxUnpoolingLayerKernel::run(), CLComparisonKernel::run(), CLNormalizationLayerKernel::run(), CLFFTDigitReverseKernel::run(), CLReorgLayerKernel::run(), CLNormalizePlanarYUVLayerKernel::run(), CLReductionOperationKernel::run(), CLPadLayerKernel::run(), CLFFTRadixStageKernel::run(), CLFillBorderKernel::run(), CLL2NormalizeLayerKernel::run(), CLArgMinMaxLayerKernel::run(), NEBatchToSpaceLayerKernel::run(), NESpaceToBatchLayerKernel::run(), CLBatchNormalizationLayerKernel::run(), CLBatchToSpaceLayerKernel::run(), CLSpaceToBatchLayerKernel::run(), ClElementwiseKernel::run_op(), ClKernelRuntime::run_op(), ClDequantizeKernel::run_op(), ClFloorKernel::run_op(), ClCopyKernel::run_op(), ClElementWiseUnaryKernel::run_op(), ClFillKernel::run_op(), ClActivationKernel::run_op(), ClPool2dKernel::run_op(), ClQuantizeKernel::run_op(), ClDepthConcatenateKernel::run_op(), ClBatchConcatenateKernel::run_op(), ClGemmLowpMatrixMultiplyNativeKernel::run_op(), ClGemmReshapeLhsMatrixKernel::run_op(), ClWinogradInputTransformKernel::run_op(), ClGemmLowpQuantizeDownInt32ScaleByFixedPointKernel::run_op(), ClGemmLowpQuantizeDownInt32ScaleKernel::run_op(), ClGemmLowpQuantizeDownInt32ScaleByFloatKernel::run_op(), ClCastKernel::run_op(), ClWinogradOutputTransformKernel::run_op(), ClGemmMatrixMultiplyNativeKernel::run_op(), ClGemmMatrixMultiplyReshapedOnlyRhsMMULKernel::run_op(), ClGemmLowpMatrixMultiplyReshapedKernel::run_op(), ClGemmReshapeRhsMatrixKernel::run_op(), ClCol2ImKernel::run_op(), ClGemmLowpOffsetContributionKernel::run_op(), ClDirectConv2dKernel::run_op(), ClGemmLowpOffsetContributionOutputStageKernel::run_op(), ClLogits1DMaxShiftExpSumKernel::run_op(), ClMulKernel::run_op(), ClGemmLowpMatrixMultiplyReshapedOnlyRhsKernel::run_op(), CLFillBorderKernel::run_op(), ClGemmMatrixMultiplyReshapedOnlyRhsKernel::run_op(), ClIm2ColKernel::run_op(), ClGemmMatrixMultiplyReshapedKernel::run_op(), ClComplexMulKernel::run_op(), and ClLogits1DNormKernel::run_op().
slide_window_slice_4D()
bool slide_window_slice_4D (Window & slice) const inline
Slide the passed 4D window slice.
If slice contains the last slice then it will remain unchanged and false will be returned.
Parameters
[in,out] slice Current slice, to be updated to the next slice.
Returns
true if slice contains a new slice, false if slice already contained the last slice
Definition at line 361 of file Window.h.
     {
         return slide_window_slice<4>(slice);
     }
References arm_compute::test::validation::reference::slice().
Referenced by CLReverseKernel::run(), CLTileKernel::run(), CLReductionOperationKernel::run(), CLArgMinMaxLayerKernel::run(), ClWidthConcatenate2TensorsKernel::run_op(), ClPool2dKernel::run_op(), ClPermuteKernel::run_op(), ClWidthConcatenate4TensorsKernel::run_op(), CLStridedSliceKernel::run_op(), ClCol2ImKernel::run_op(), and ClWeightsReshapeKernel::run_op().
split_window()
Window split_window (size_t dimension, size_t id, size_t total) const inline
Split a window into a set of sub windows along a given dimension.
For example to split a window into 3 sub-windows along the Y axis, you would have to do:
Window sub0 = window.split_window(1, 0, 3);
Window sub1 = window.split_window(1, 1, 3);
Window sub2 = window.split_window(1, 2, 3);
Parameters
[in] dimension Dimension along which the split will be performed
[in] id Id of the sub-window to return. Must be in the range (0, total-1)
[in] total Total number of sub-windows the window will be split into.
Returns
The subwindow "id" out of "total"
Definition at line 189 of file Window.inl.
 {
     ARM_COMPUTE_ERROR_ON(id >= total);
     ARM_COMPUTE_ERROR_ON(dimension >= Coordinates::num_max_dimensions);
     Window out;
     for(size_t d = 0; d < Coordinates::num_max_dimensions; ++d)
     {
         if(d == dimension)
         {
             int       start = _dims[d].start();
             int       end   = _dims[d].end();
             const int step  = _dims[d].step();
             const int num_it = num_iterations(d);
             const int rem    = num_it % total;
             int       work   = num_it / total;
             int it_start = work * id;
             if(int(id) < rem)
             {
                 ++work;
                 it_start += id;
             }
             else
             {
                 it_start += rem;
             }
             start += it_start * step;
             end = std::min(end, start + work * step);
             out.set(d, Dimension(start, end, step));
         }
         else
         {
             out.set(d, _dims[d]);
         }
     }
     return out;
 }
References ARM_COMPUTE_ERROR_ON, arm_compute::mlgo::parser::end(), Window::num_iterations(), Dimensions< int >::num_max_dimensions, Window::set(), and arm_compute::cpu::step.
Referenced by OMPScheduler::schedule_op().
use_tensor_dimensions()
void use_tensor_dimensions (const TensorShape & shape, size_t first_dimension = Window::DimX) inline
Use the tensor's dimensions to fill the window dimensions.
Parameters
[in] shape TensorShape to copy the dimensions from.
[in] first_dimension Only copy dimensions which are greater or equal to this value.
Definition at line 276 of file Window.inl.
 {
     for(unsigned int n = first_dimension; n < shape.num_dimensions(); ++n)
     {
         set(n, Window::Dimension(0, std::max(shape[n], static_cast<size_t>(1))));
     }
 }
References arm_compute::test::validation::n, Dimensions< T >::num_dimensions(), Window::set(), and Window::shape().
Referenced by arm_compute::utils::compare_tensor(), CLFillBorderKernel::configure(), NEFillBorderKernel::configure(), ITensor::copy_from(), AssetsLibrary::fill_layer_data(), arm_compute::utils::fill_random_tensor(), NPYLoader::fill_tensor(), arm_compute::utils::fill_tensor_value(), arm_compute::utils::fill_tensor_vector(), arm_compute::test::validation::reference::gather(), CpuFloorKernel::infer_window(), CLQLSTMLayerNormalizationKernel::run(), NEStackLayerKernel::run(), CLStackLayerKernel::run(), ClCropKernel::run_op(), ClWinogradFilterTransformKernel::run_op(), ClWinogradOutputTransformKernel::run_op(), ClCol2ImKernel::run_op(), ClDirectConv2dKernel::run_op(), ClWeightsReshapeKernel::run_op(), ClIm2ColKernel::run_op(), arm_compute::utils::save_to_npy(), arm_compute::test::validation::reference::slice(), arm_compute::test::validation::reference::softmax_layer_generic(), arm_compute::test::validation::reference::strided_slice(), and arm_compute::test::validation::TEST_CASE().
validate()
void validate () const inline
Will validate all the window's dimensions' values when asserts are enabled.
No-op when asserts are disabled
Definition at line 173 of file Window.inl.
 {
     for(size_t i = 0; i < Coordinates::num_max_dimensions; ++i)
     {
         ARM_COMPUTE_ERROR_ON(_dims[i].end() < _dims[i].start());
         ARM_COMPUTE_ERROR_ON((_dims[i].step() != 0) && (((_dims[i].end() - _dims[i].start()) % _dims[i].step()) != 0));
     }
 }
References ARM_COMPUTE_ERROR_ON, arm_compute::mlgo::parser::end(), Dimensions< int >::num_max_dimensions, and arm_compute::cpu::step.
Referenced by arm_compute::colorconvert_iyuv_to_nv12(), arm_compute::colorconvert_iyuv_to_rgb(), arm_compute::colorconvert_iyuv_to_yuv4(), arm_compute::colorconvert_nv12_to_iyuv(), arm_compute::colorconvert_nv12_to_rgb(), arm_compute::colorconvert_nv12_to_yuv4(), arm_compute::colorconvert_rgb_to_iyuv(), arm_compute::colorconvert_rgb_to_nv12(), arm_compute::colorconvert_rgb_to_yuv4(), arm_compute::colorconvert_yuyv_to_iyuv(), arm_compute::colorconvert_yuyv_to_nv12(), arm_compute::error_on_invalid_subwindow(), arm_compute::error_on_mismatching_windows(), arm_compute::error_on_window_not_collapsable_at_dimension(), OMPScheduler::schedule_op(), AccessWindowTranspose::update_window_if_needed(), and AccessWindowRectangle::update_window_if_needed().
x()
constexpr const Dimension& x () const inline constexpr
Alias to access the first dimension of the window.
Returns
First dimension of the window
Definition at line 159 of file Window.h.
     {
         return _dims.at(Window::DimX);
     }
References Window::DimX.
Referenced by arm_compute::cpu::add_qasymm8_signed_sve2(), arm_compute::cpu::add_qasymm8_sve2(), arm_compute::cpu::add_qsymm16_neon(), arm_compute::cpu::add_qsymm16_sve2(), arm_compute::cpu::add_same_neon(), arm_compute::cpu::add_same_sve(), arm_compute::cpu::add_sub_q8_neon_fixedpoint(), arm_compute::cpu::add_sub_qasymm8_neon(), arm_compute::cpu::add_sub_qasymm8_signed_neon(), arm_compute::colorconvert_iyuv_to_nv12(), arm_compute::colorconvert_iyuv_to_rgb(), arm_compute::colorconvert_iyuv_to_yuv4(), arm_compute::colorconvert_nv12_to_iyuv(), arm_compute::colorconvert_nv12_to_rgb(), arm_compute::colorconvert_nv12_to_yuv4(), arm_compute::colorconvert_rgb_to_iyuv(), arm_compute::colorconvert_rgb_to_nv12(), arm_compute::colorconvert_yuyv_to_iyuv(), arm_compute::colorconvert_yuyv_to_nv12(), AccessWindowTranspose::compute_valid_region(), AccessWindowRectangle::compute_valid_region(), ClDequantizeKernel::configure(), ClCopyKernel::configure(), ClElementWiseUnaryKernel::configure(), ClFillKernel::configure(), ClQuantizeKernel::configure(), ClCropKernel::configure(), CLStridedSliceKernel::configure(), CLTileKernel::configure(), ClDirectConv2dKernel::configure(), CLReductionOperationKernel::configure(), arm_compute::cpu::elementwise_arithmetic_op(), arm_compute::cpu::elementwise_arithmetic_quantized_op(), arm_compute::cpu::elementwise_comp_quantized_signed(), arm_compute::cpu::elementwise_comparison_op(), arm_compute::cpu::elementwise_comparison_quantized_op(), arm_compute::cpu::elementwise_op(), arm_compute::cpu::elementwise_op< int8_t >(), arm_compute::cpu::elementwise_op< uint8_t >(), arm_compute::cpu::elementwise_op_quantized(), arm_compute::cpu::elementwise_op_quantized_signed(), arm_compute::cpu::elementwise_sve_op(), arm_compute::cpu::fp_neon_activation_impl(), arm_compute::cpu::fused_batch_normalization_conv(), arm_compute::cpu::fused_batch_normalization_dwc_nchw(), arm_compute::cpu::fused_batch_normalization_dwc_nhwc(), ClTemplateCast::get_build_options(), ClTemplateLogits1DNorm::get_build_options(), ClTemplateReshape::get_build_options(), ClTemplateDirectConv2d::get_build_options(), ClTemplatePool2d::get_build_options(), ClTemplateResize::get_build_options(), ClTemplateActivation::get_build_options(), ICLKernel::gws_from_window(), arm_compute::cpu::instance_normalization_nchw(), IKernel::is_window_configured(), WindowIterator< L >::iterate_3D(), arm_compute::cpu::l2_normalize_x(), arm_compute::cpu::l2_normalize_yz(), arm_compute::cpu::matrix_addition_f32(), arm_compute::cpu::matrix_matrix_multiply_f32(), arm_compute::cpu::mean_stddev_normalization(), arm_compute::cpu::neon_logits_1d_max(), arm_compute::cpu::neon_qasymm8_activation(), arm_compute::cpu::neon_qasymm8_meanstddevnorm(), arm_compute::cpu::neon_qasymm8_signed_activation(), arm_compute::cpu::neon_qsymm16_activation(), arm_compute::cpu::neon_range_function(), arm_compute::cpu::poolingMxN_fp32_neon_nhwc(), arm_compute::cpu::poolingMxN_fp32_neon_nhwc_kernel_indices(), arm_compute::cpu::poolingMxN_q8_neon_nhwc(), arm_compute::cpu::poolingMxNxD_fp_neon_ndhwc(), arm_compute::cpu::roi_align(), NEROIPoolingLayerKernel::run(), NETileKernel::run(), NESpaceToDepthLayerKernel::run(), NEDepthToSpaceLayerKernel::run(), NEBatchToSpaceLayerKernel::run(), NESpaceToBatchLayerKernel::run(), CpuFillKernel::run_op(), CpuConvertQuantizedSignednessKernel::run_op(), CpuCopyKernel::run_op(), CpuConcatenateHeightKernel::run_op(), CpuConcatenateWidthKernel::run_op(), CpuPool2dKernel::run_op(), CpuFloorKernel::run_op(), ClCropKernel::run_op(), CpuGemmLowpMatrixMultiplyKernel::run_op(), CpuGemmInterleave4x4Kernel::run_op(), CpuCastKernel::run_op(), arm_compute::run_reverse(), arm_compute::cpu::select_op_16(), arm_compute::cpu::select_op_32(), arm_compute::cpu::select_op_8(), arm_compute::cpu::sub_qsymm16_neon(), arm_compute::cpu::sub_same_neon(), arm_compute::cpu::sve2_q8_elementwise_unary(), arm_compute::cpu::sve2_qasymm8_activation(), arm_compute::cpu::sve2_qasymm8_signed_activation(), arm_compute::cpu::sve2_qsymm16_activation(), arm_compute::cpu::sve_fp32_activation(), arm_compute::cpu::sve_logits_1d_max(), AccessWindowTranspose::update_padding_if_needed(), AccessWindowTranspose::update_window_if_needed(), AccessWindowRectangle::update_window_if_needed(), ClFillKernel::validate(), and ClCropKernel::validate().
y()
constexpr const Dimension& y () const inline constexpr
Alias to access the second dimension of the window.
Returns
Second dimension of the window
Definition at line 168 of file Window.h.
     {
         return _dims.at(Window::DimY);
     }
References Window::DimY.
Referenced by arm_compute::cpu::bilinear_neon_scale(), arm_compute::colorconvert_iyuv_to_nv12(), arm_compute::colorconvert_iyuv_to_rgb(), arm_compute::colorconvert_iyuv_to_yuv4(), arm_compute::colorconvert_nv12_to_iyuv(), arm_compute::colorconvert_nv12_to_rgb(), arm_compute::colorconvert_nv12_to_yuv4(), arm_compute::colorconvert_rgb_to_iyuv(), arm_compute::colorconvert_rgb_to_nv12(), arm_compute::colorconvert_yuyv_to_iyuv(), arm_compute::colorconvert_yuyv_to_nv12(), arm_compute::cpu::compute_all_anchors(), arm_compute::cpu::compute_all_anchors_qasymm16(), AccessWindowTranspose::compute_valid_region(), AccessWindowRectangle::compute_valid_region(), ClDirectConv2dKernel::configure(), ClTemplateResize::get_build_options(), ICLKernel::gws_from_window(), WindowIterator< L >::iterate_3D(), arm_compute::cpu::matrix_matrix_multiply_f32(), arm_compute::cpu::nearest_neon_scale(), arm_compute::cpu::poolingMxN_fp32_neon_nhwc(), arm_compute::cpu::poolingMxN_q8_neon_nhwc(), NEDepthToSpaceLayerKernel::run(), NEBatchToSpaceLayerKernel::run(), NESpaceToBatchLayerKernel::run(), CpuPool2dKernel::run_op(), CpuGemmLowpMatrixMultiplyKernel::run_op(), CpuCol2ImKernel::run_op(), AccessWindowTranspose::update_padding_if_needed(), AccessWindowTranspose::update_window_if_needed(), and AccessWindowRectangle::update_window_if_needed().
z()
constexpr const Dimension& z () const inline constexpr
Alias to access the third dimension of the window.
Returns
Third dimension of the window
Definition at line 177 of file Window.h.
     {
         return _dims.at(Window::DimZ);
     }
References Window::DimZ.
Referenced by arm_compute::cpu::bilinear_neon_scale(), ICLKernel::gws_from_window(), WindowIterator< L >::iterate_3D(), arm_compute::cpu::nearest_neon_scale(), arm_compute::cpu::poolingMxN_fp32_neon_nhwc(), arm_compute::cpu::poolingMxN_q8_neon_nhwc(), and NESpaceToDepthLayerKernel::run().
Friends And Related Function Documentation
operator==
bool operator== (const Window & lhs, const Window & rhs) friend
Check whether two Windows are equal.
Parameters
[in] lhs LHS window
[in] rhs RHS window
Returns
True if the given windows are the same.
Definition at line 309 of file Window.inl.
 {
     return (lhs._dims == rhs._dims) && (lhs._is_broadcasted == rhs._is_broadcasted);
 }
swap
void swap (Window & lhs, Window & rhs) friend
Friend function that swaps the contents of two windows.
Parameters
[in] lhs First window to swap.
[in] rhs Second window to swap.
Definition at line 304 of file Window.inl.
 {
     lhs._dims.swap(rhs._dims);
 }
Referenced by Window::operator=().
Field Documentation
DimV
constexpr size_t DimV = 4 static constexpr
Alias for dimension 4 also known as V dimension.
Definition at line 51 of file Window.h.
DimW
constexpr size_t DimW = 3 static constexpr
Alias for dimension 3 also known as W dimension.
Definition at line 49 of file Window.h.
Referenced by arm_compute::cpu::directconv3d_float_neon_ndhwc(), and arm_compute::cpu::directconv3d_quantized_neon_ndhwc().
DimX
constexpr size_t DimX = 0 static constexpr
Alias for dimension 0 also known as X dimension.
Definition at line 43 of file Window.h.
Referenced by arm_compute::cpu::add_qasymm8_signed_sve2(), arm_compute::cpu::add_qasymm8_sve2(), arm_compute::cpu::add_qsymm16_neon(), arm_compute::cpu::add_qsymm16_sve2(), arm_compute::cpu::add_same_neon(), arm_compute::cpu::add_same_sve(), arm_compute::cpu::add_sub_q8_neon_fixedpoint(), arm_compute::cpu::add_sub_qasymm8_neon(), arm_compute::cpu::add_sub_qasymm8_signed_neon(), arm_compute::cpu::bilinear_neon_scale(), arm_compute::calculate_squashed_or_max_window(), arm_compute::colorconvert_iyuv_to_nv12(), arm_compute::colorconvert_iyuv_to_rgb(), arm_compute::colorconvert_iyuv_to_yuv4(), arm_compute::colorconvert_nv12_to_iyuv(), arm_compute::colorconvert_nv12_to_rgb(), arm_compute::colorconvert_nv12_to_yuv4(), arm_compute::colorconvert_rgb_to_iyuv(), arm_compute::colorconvert_rgb_to_nv12(), arm_compute::colorconvert_yuyv_to_iyuv(), arm_compute::colorconvert_yuyv_to_nv12(), arm_compute::misc::shape_calculator::compute_min_max_shape(), arm_compute::misc::shape_calculator::compute_reductionB_shape(), arm_compute::misc::shape_calculator::compute_winograd_filter_transform_shape(), arm_compute::test::validation::reference::concatenate_layer(), ClDequantizeKernel::configure(), ClCopyKernel::configure(), ClElementWiseUnaryKernel::configure(), ClFillKernel::configure(), ClQuantizeKernel::configure(), ClCropKernel::configure(), CLStridedSliceKernel::configure(), CpuConcatenate::configure(), ClConcatenate::configure(), NEBoundingBoxTransformKernel::configure(), NEROIPoolingLayerKernel::configure(), CLTileKernel::configure(), CLReductionOperationKernel::configure(), NEROIAlignLayerKernel::configure(), CpuWeightsReshapeKernel::configure(), CLROIPoolingLayerKernel::configure(), CLFillBorderKernel::configure(), NEFillBorderKernel::configure(), NELSTMLayerQuantized::configure(), NELSTMLayer::configure(), CLLSTMLayerQuantized::configure(), CLLSTMLayer::configure(), arm_compute::cpu::kernels::convolve_nchw(), arm_compute::cpu::kernels::convolve_nhwc(), arm_compute::cpu::directconv3d_float_neon_ndhwc(), arm_compute::cpu::directconv3d_quantized_neon_ndhwc(), arm_compute::cpu::elementwise_arithmetic_op(), arm_compute::cpu::elementwise_arithmetic_quantized_op(), arm_compute::cpu::elementwise_comp_quantized_signed(), arm_compute::cpu::elementwise_comparison_op(), arm_compute::cpu::elementwise_comparison_quantized_op(), arm_compute::cpu::elementwise_op(), arm_compute::cpu::elementwise_op< int8_t >(), arm_compute::cpu::elementwise_op< uint8_t >(), arm_compute::cpu::elementwise_op_quantized(), arm_compute::cpu::elementwise_op_quantized_signed(), arm_compute::cpu::elementwise_sve_op(), IImageLoader::fill_image(), IImageLoader::fill_planar_tensor(), arm_compute::cpu::fp_neon_activation_impl(), arm_compute::cpu::fused_batch_normalization_conv(), arm_compute::cpu::fused_batch_normalization_dwc_nchw(), arm_compute::cpu::fused_batch_normalization_dwc_nhwc(), CpuActivationKernel::get_mws(), CpuMulKernel::get_mws(), IKernel::IKernel(), arm_compute::cpu::instance_normalization_nchw(), arm_compute::cpu::l2_normalize_x(), arm_compute::cpu::l2_normalize_yz(), arm_compute::utils::load_trained_data(), arm_compute::cpu::matrix_addition_f32(), arm_compute::cpu::matrix_matrix_multiply_f32(), arm_compute::cpu::mean_stddev_normalization(), arm_compute::cpu::nearest_neon_scale(), arm_compute::cpu::neon_logits_1d_max(), arm_compute::cpu::neon_qasymm8_activation(), arm_compute::cpu::neon_qasymm8_meanstddevnorm(), arm_compute::cpu::neon_qasymm8_signed_activation(), arm_compute::cpu::neon_qsymm16_activation(), arm_compute::cpu::neon_range_function(), arm_compute::cpu::poolingMxN_fp32_neon_nhwc(), arm_compute::cpu::poolingMxN_fp32_neon_nhwc_kernel_indices(), arm_compute::cpu::poolingMxN_q8_neon_nhwc(), arm_compute::cpu::poolingMxNxD_fp_neon_ndhwc(), arm_compute::cpu::poolingMxNxD_q8_neon_ndhwc(), CpuGemmLowpMatrixMultiplyCore::prepare(), CPPUpsampleKernel::run(), NEROIPoolingLayerKernel::run(), ClConcatenate::run(), CpuPool2d::run(), NETileKernel::run(), NEDepthToSpaceLayerKernel::run(), NEFFTScaleKernel::run(), CLInstanceNormalizationLayerKernel::run(), CLDepthToSpaceLayerKernel::run(), CLSelectKernel::run(), CLSpaceToDepthLayerKernel::run(), CLDeconvolutionLayerUpsampleKernel::run(), CLComputeAllAnchorsKernel::run(), CLQLSTMLayerNormalizationKernel::run(), NEROIPoolingLayer::run(), CLROIPoolingLayerKernel::run(), CLMeanStdDevNormalizationKernel::run(), CLNormalizePlanarYUVLayerKernel::run(), CLReductionOperationKernel::run(), CLL2NormalizeLayerKernel::run(), CpuWinogradConv2d::run(), NEFFT1D::run(), NERange::run(), CLArgMinMaxLayerKernel::run(), CLROIAlignLayerKernel::run(), CLBatchNormalizationLayerKernel::run(), CLBatchToSpaceLayerKernel::run(), CLSpaceToBatchLayerKernel::run(), CpuGemm::run(), CpuGemmLowpMatrixMultiplyCore::run(), CLComputeMeanVariance::run(), CpuFillKernel::run_op(), ClKernelRuntime::run_op(), CpuConvertQuantizedSignednessKernel::run_op(), CpuCopyKernel::run_op(), CpuConcatenateWidthKernel::run_op(), CpuConcatenateHeightKernel::run_op(), ClPool2dKernel::run_op(), ClPermuteKernel::run_op(), CpuPool2dKernel::run_op(), CpuFloorKernel::run_op(), ClCropKernel::run_op(), ClGemmLowpMatrixMultiplyNativeKernel::run_op(), CpuGemmLowpMatrixMultiplyKernel::run_op(), CpuGemmInterleave4x4Kernel::run_op(), ClWinogradOutputTransformKernel::run_op(), ClGemmMatrixMultiplyNativeKernel::run_op(), CpuCol2ImKernel::run_op(), CpuCastKernel::run_op(), ClGemmLowpMatrixMultiplyReshapedKernel::run_op(), ClGemmLowpOffsetContributionKernel::run_op(), ClGemmLowpOffsetContributionOutputStageKernel::run_op(), ClLogits1DMaxShiftExpSumKernel::run_op(), ClGemmLowpMatrixMultiplyReshapedOnlyRhsKernel::run_op(), ClGemmLowpMatrixAReductionKernel::run_op(), ClGemmMatrixMultiplyReshapedOnlyRhsKernel::run_op(), CpuGemmTranspose1xWKernel::run_op(), ClIm2ColKernel::run_op(), NEStridedSliceKernel::run_op(), ClGemmMatrixMultiplyReshapedKernel::run_op(), ClLogits1DNormKernel::run_op(), arm_compute::run_reverse(), arm_compute::utils::save_to_ppm(), arm_compute::cpu::select_op(), arm_compute::cpu::sub_qsymm16_neon(), arm_compute::cpu::sub_same_neon(), arm_compute::cpu::sve2_qasymm8_activation(), arm_compute::cpu::sve2_qasymm8_signed_activation(), arm_compute::cpu::sve2_qsymm16_activation(), arm_compute::cpu::sve_fp32_activation(), arm_compute::cpu::sve_logits_1d_max(), CpuConcatenate::validate(), ClConcatenate::validate(), NELSTMLayerQuantized::validate(), NEDeconvolutionLayer::validate(), NELSTMLayer::validate(), CLLSTMLayerQuantized::validate(), CLLSTMLayer::validate(), arm_compute::cpu::vector_matrix_multiply_f32(), and Window::x().
DimY
constexpr size_t DimY = 1 static constexpr
Alias for dimension 1 also known as Y dimension.
Definition at line 45 of file Window.h.
Referenced by arm_compute::cpu::bilinear_neon_scale(), arm_compute::calculate_squashed_or_max_window(), arm_compute::colorconvert_iyuv_to_nv12(), arm_compute::colorconvert_iyuv_to_rgb(), arm_compute::colorconvert_iyuv_to_yuv4(), arm_compute::colorconvert_nv12_to_iyuv(), arm_compute::colorconvert_nv12_to_rgb(), arm_compute::colorconvert_nv12_to_yuv4(), arm_compute::colorconvert_rgb_to_iyuv(), arm_compute::colorconvert_rgb_to_nv12(), arm_compute::colorconvert_yuyv_to_iyuv(), arm_compute::colorconvert_yuyv_to_nv12(), arm_compute::misc::shape_calculator::compute_winograd_filter_transform_shape(), arm_compute::test::validation::reference::concatenate_layer(), CpuConcatenate::configure(), ClConcatenate::configure(), NEBoundingBoxTransformKernel::configure(), NEROIPoolingLayerKernel::configure(), NEROIAlignLayerKernel::configure(), CpuWeightsReshapeKernel::configure(), CLFillBorderKernel::configure(), CLROIPoolingLayerKernel::configure(), NEFillBorderKernel::configure(), CpuDirectConv2d::configure(), CpuDirectConv3d::configure(), NELSTMLayerQuantized::configure(), CLLSTMLayerQuantized::configure(), arm_compute::cpu::kernels::convolve_nchw(), arm_compute::cpu::kernels::convolve_nhwc(), ITensor::copy_from(), arm_compute::cpu::directconv3d_float_neon_ndhwc(), arm_compute::cpu::directconv3d_quantized_neon_ndhwc(), arm_compute::utils::draw_detection_rectangle(), IImageLoader::fill_image(), IImageLoader::fill_planar_tensor(), ClTemplateDirectConv2d::get_window(), IKernel::IKernel(), arm_compute::cpu::instance_normalization_nchw(), arm_compute::cpu::matrix_matrix_multiply_f32(), arm_compute::cpu::nearest_neon_scale(), CpuFullyConnected::prepare(), CpuGemmLowpMatrixMultiplyCore::prepare(), NEQLSTMLayer::prepare(), ICPPSimpleFunction::run(), CpuQuantize::run(), CpuDequantize::run(), INESimpleFunction::run(), INESimpleFunctionNoBorder::run(), CpuAddMulAdd::run(), CpuScale::run(), CpuPool3d::run(), CPPUpsampleKernel::run(), CpuConcatenate::run(), NEROIPoolingLayerKernel::run(), CpuDepthwiseConv2dAssemblyDispatch::run(), CpuPool2d::run(), NEDepthToSpaceLayerKernel::run(), CLInstanceNormalizationLayerKernel::run(), CLSpaceToDepthLayerKernel::run(), CLDepthToSpaceLayerKernel::run(), CLDeconvolutionLayerUpsampleKernel::run(), CpuMatMul::run(), CpuSoftmaxGeneric< IS_LOG >::run(), NESpaceToDepthLayer::run(), NELogicalAnd::run(), CpuGemmLowpOutputStage::run(), CLReductionOperationKernel::run(), CLPriorBoxLayerKernel::run(), CPPBoxWithNonMaximaSuppressionLimit::run(), CpuDirectConv2d::run(), CLL2NormalizeLayerKernel::run(), NEStackLayer::run(), NEFFT1D::run(), NEL2NormalizeLayer::run(), NENormalizationLayer::run(), CLArgMinMaxLayerKernel::run(), CpuComplexMul::run(), NEFuseBatchNormalization::run(), NEBatchNormalizationLayer::run(), NESpaceToBatchLayer::run(), CLBatchToSpaceLayerKernel::run(), CLSpaceToBatchLayerKernel::run(), CpuGemm::run(), CpuGemmLowpMatrixMultiplyCore::run(), NEGenerateProposalsLayer::run(), CLComputeMeanVariance::run(), NESynthetizeFunctionWithZeroConstantKernelBorder< K >::run(), NELogicalOr::run(), CpuGemmConv2d::run(), NELogicalNot::run(), NEQLSTMLayer::run(), ClKernelRuntime::run_op(), CpuConcatenateHeightKernel::run_op(), ClPool2dKernel::run_op(), CpuPool2dKernel::run_op(), ClPermuteKernel::run_op(), ClGemmLowpMatrixMultiplyNativeKernel::run_op(), CpuGemmLowpMatrixMultiplyKernel::run_op(), ClGemmLowpQuantizeDownInt32ScaleByFixedPointKernel::run_op(), CpuGemmInterleave4x4Kernel::run_op(), ClGemmLowpQuantizeDownInt32ScaleKernel::run_op(), ClWinogradOutputTransformKernel::run_op(), ClGemmLowpQuantizeDownInt32ScaleByFloatKernel::run_op(), ClGemmMatrixMultiplyNativeKernel::run_op(), CpuCol2ImKernel::run_op(), ClGemmLowpMatrixMultiplyReshapedKernel::run_op(), ClGemmLowpOffsetContributionKernel::run_op(), ClGemmLowpOffsetContributionOutputStageKernel::run_op(), ClDirectConv3dKernel::run_op(), ClGemmLowpMatrixMultiplyReshapedOnlyRhsKernel::run_op(), ClGemmLowpMatrixAReductionKernel::run_op(), ClGemmMatrixMultiplyReshapedOnlyRhsKernel::run_op(), CpuGemmTranspose1xWKernel::run_op(), ClIm2ColKernel::run_op(), ClGemmMatrixMultiplyReshapedKernel::run_op(), ClGemmLowpMatrixBReductionKernel::run_op(), arm_compute::utils::save_to_ppm(), CpuConcatenate::validate(), ClConcatenate::validate(), NELSTMLayerQuantized::validate(), NEDeconvolutionLayer::validate(), CLLSTMLayerQuantized::validate(), arm_compute::cpu::vector_matrix_multiply_f32(), and Window::y().
DimZ
constexpr size_t DimZ = 2 static constexpr
Alias for dimension 2 also known as Z dimension.
Definition at line 47 of file Window.h.
Referenced by arm_compute::cpu::bilinear_neon_scale(), arm_compute::misc::shape_calculator::compute_winograd_filter_transform_shape(), arm_compute::test::validation::reference::concatenate_layer(), ClWidthConcatenate2TensorsKernel::configure(), ClHeightConcatenateKernel::configure(), ClMatMulNativeKernel::configure(), ClWidthConcatenateKernel::configure(), ClMatMulLowpNativeKernel::configure(), ClWidthConcatenate4TensorsKernel::configure(), ClDepthConcatenateKernel::configure(), CpuConcatenate::configure(), ClConcatenate::configure(), ClCastKernel::configure(), CpuWeightsReshapeKernel::configure(), CLROIPoolingLayerKernel::configure(), CLFillBorderKernel::configure(), NEFillBorderKernel::configure(), CpuDirectConv2d::configure(), arm_compute::cpu::kernels::convolve_nchw(), arm_compute::cpu::kernels::convolve_nhwc(), arm_compute::cpu::directconv3d_float_neon_ndhwc(), arm_compute::cpu::directconv3d_quantized_neon_ndhwc(), IImageLoader::fill_planar_tensor(), arm_compute::cpu::fp_neon_activation_impl(), ClTemplateCast::get_window(), ClTemplateLogits1DMaxShiftExpSum::get_window(), ClTemplateLogits1DNorm::get_window(), ClTemplateDepthwiseConv2d::get_window(), ClTemplateReshape::get_window(), ClTemplateDirectConv2d::get_window(), ClTemplateActivation::get_window(), ClTemplatePool2d::get_window(), ClTemplateResize::get_window(), arm_compute::cpu::instance_normalization_nchw(), arm_compute::cpu::l2_normalize_x(), arm_compute::cpu::matrix_addition_f32(), arm_compute::cpu::nearest_neon_scale(), arm_compute::cpu::neon_qasymm8_activation(), arm_compute::cpu::neon_qasymm8_signed_activation(), arm_compute::cpu::neon_qsymm16_activation(), CpuConvertFullyConnectedWeights::run(), INESimpleFunction::run(), NEFillBorder::run(), CPPUpsampleKernel::run(), NEROIPoolingLayerKernel::run(), CpuPool2d::run(), NEDepthToSpaceLayerKernel::run(), CLInstanceNormalizationLayerKernel::run(), CLDepthToSpaceLayerKernel::run(), CLSpaceToDepthLayerKernel::run(), CLReverseKernel::run(), CLSelectKernel::run(), CLDeconvolutionLayerUpsampleKernel::run(), CLFFTScaleKernel::run(), CLGatherKernel::run(), CLComparisonKernel::run(), CLNormalizationLayerKernel::run(), CLROIPoolingLayerKernel::run(), CLTileKernel::run(), CLFFTDigitReverseKernel::run(), CLNormalizePlanarYUVLayerKernel::run(), CLReductionOperationKernel::run(), CLFFTRadixStageKernel::run(), CLFillBorderKernel::run(), CpuDirectConv2d::run(), CLL2NormalizeLayerKernel::run(), NEFFT1D::run(), CLStackLayerKernel::run(), NEInstanceNormalizationLayer::run(), CLDepthwiseConvolutionLayerNativeKernel::run(), CLArgMinMaxLayerKernel::run(), CLDeconvolutionReshapeOutputKernel::run(), NEPadLayer::run(), NECropResize::run(), CLFuseBatchNormalizationKernel::run(), CLBatchToSpaceLayerKernel::run(), CLSpaceToBatchLayerKernel::run(), CLComputeMeanVariance::run(), NESynthetizeFunctionWithZeroConstantKernelBorder< K >::run(), CpuFillKernel::run_op(), ClElementwiseKernel::run_op(), CpuConvertQuantizedSignednessKernel::run_op(), ClFloorKernel::run_op(), ClReshapeKernel::run_op(), ClCopyKernel::run_op(), ClElementWiseUnaryKernel::run_op(), ClFillKernel::run_op(), ClScaleKernel::run_op(), ClMatMulNativeKernel::run_op(), ClActivationKernel::run_op(), ClPool3dKernel::run_op(), ClPool2dKernel::run_op(), ClMatMulLowpNativeKernel::run_op(), ClPermuteKernel::run_op(), CpuPool2dKernel::run_op(), ClWinogradInputTransformKernel::run_op(), ClGemmLowpQuantizeDownInt32ScaleByFixedPointKernel::run_op(), ClWinogradOutputTransformKernel::run_op(), ClCastKernel::run_op(), ClGemmLowpQuantizeDownInt32ScaleKernel::run_op(), ClGemmLowpQuantizeDownInt32ScaleByFloatKernel::run_op(), CpuCol2ImKernel::run_op(), CLStridedSliceKernel::run_op(), ClCol2ImKernel::run_op(), ClGemmLowpOffsetContributionKernel::run_op(), ClGemmLowpOffsetContributionOutputStageKernel::run_op(), ClDirectConv3dKernel::run_op(), ClLogits1DMaxShiftExpSumKernel::run_op(), ClMulKernel::run_op(), ClGemmLowpMatrixAReductionKernel::run_op(), ClGemmLowpMatrixMultiplyReshapedOnlyRhsKernel::run_op(), CLFillBorderKernel::run_op(), ClIm2ColKernel::run_op(), ClComplexMulKernel::run_op(), ClLogits1DNormKernel::run_op(), ClGemmLowpMatrixBReductionKernel::run_op(), arm_compute::cpu::sve2_qasymm8_activation(), arm_compute::cpu::sve2_qasymm8_signed_activation(), arm_compute::cpu::sve2_qsymm16_activation(), arm_compute::cpu::sve_fp32_activation(), CpuConcatenate::validate(), ClConcatenate::validate(), NEDeconvolutionLayer::validate(), and Window::z().
The documentation for this class was generated from the following files:
arm_compute/core/Window.h
arm_compute/core/Window.inl