Compute Library: CLFuseBatchNormalization Class Reference
CLFuseBatchNormalization Class Reference
Basic function to fuse the batch normalization node to a preceding convolution node.
#include <CLFuseBatchNormalization.h>
Public Member Functions
CLFuseBatchNormalization ()
Default constructor.
CLFuseBatchNormalization (const CLFuseBatchNormalization &)=delete
Prevent instances of this class from being copied (As this class contains pointers)
CLFuseBatchNormalization & operator= (const CLFuseBatchNormalization &)=delete
Prevent instances of this class from being copied (As this class contains pointers)
CLFuseBatchNormalization (CLFuseBatchNormalization &&)=default
Allow instances of this class to be moved.
CLFuseBatchNormalization & operator= (CLFuseBatchNormalization &&)=default
Allow instances of this class to be moved.
~CLFuseBatchNormalization ()
Default destructor.
void configure (const ICLTensor *input_weights, const ICLTensor *bn_mean, const ICLTensor *bn_var, ICLTensor *fused_weights, ICLTensor *fused_bias, const ICLTensor *input_bias=nullptr, const ICLTensor *bn_beta=nullptr, const ICLTensor *bn_gamma=nullptr, float epsilon=0.001f, FuseBatchNormalizationType fbn_type=FuseBatchNormalizationType::CONVOLUTION)
Set the input and output tensors.
void configure (const CLCompileContext &compile_context, const ICLTensor *input_weights, const ICLTensor *bn_mean, const ICLTensor *bn_var, ICLTensor *fused_weights, ICLTensor *fused_bias, const ICLTensor *input_bias=nullptr, const ICLTensor *bn_beta=nullptr, const ICLTensor *bn_gamma=nullptr, float epsilon=0.001f, FuseBatchNormalizationType fbn_type=FuseBatchNormalizationType::CONVOLUTION)
Set the input and output tensors.
void run () override
Run the kernels contained in the function.
Public Member Functions inherited from IFunction
virtual ~IFunction ()=default
Destructor.
virtual void prepare ()
Prepare the function for executing.
Static Public Member Functions
static Status validate (const ITensorInfo *input_weights, const ITensorInfo *bn_mean, const ITensorInfo *bn_var, const ITensorInfo *fused_weights, const ITensorInfo *fused_bias, const ITensorInfo *input_bias=nullptr, const ITensorInfo *bn_beta=nullptr, const ITensorInfo *bn_gamma=nullptr, float epsilon=0.001f, FuseBatchNormalizationType fbn_type=FuseBatchNormalizationType::CONVOLUTION)
Static function to check if given info will lead to a valid configuration of CLFuseBatchNormalization.
Detailed Description
Basic function to fuse the batch normalization node to a preceding convolution node.
Definition at line 41 of file CLFuseBatchNormalization.h.
Constructor & Destructor Documentation
CLFuseBatchNormalization() [1/3]
CLFuseBatchNormalization ()
Default constructor.
Definition at line 37 of file CLFuseBatchNormalization.cpp.
     : _fuse_bn_kernel(std::make_unique<CLFuseBatchNormalizationKernel>())
 {
 }
CLFuseBatchNormalization() [2/3]
CLFuseBatchNormalization (const CLFuseBatchNormalization &) delete
Prevent instances of this class from being copied (As this class contains pointers)
CLFuseBatchNormalization() [3/3]
CLFuseBatchNormalization (CLFuseBatchNormalization &&) default
Allow instances of this class to be moved.
~CLFuseBatchNormalization()
~CLFuseBatchNormalization () default
Default destructor.
Member Function Documentation
configure() [1/2]
void configure (const CLCompileContext & compile_context, const ICLTensor * input_weights, const ICLTensor * bn_mean, const ICLTensor * bn_var, ICLTensor * fused_weights, ICLTensor * fused_bias, const ICLTensor * input_bias = nullptr, const ICLTensor * bn_beta = nullptr, const ICLTensor * bn_gamma = nullptr, float epsilon = 0.001f, FuseBatchNormalizationType fbn_type = FuseBatchNormalizationType::CONVOLUTION)
Set the input and output tensors.
Parameters
[in] compile_context The compile context to be used.
[in] input_weights Input weights tensor for convolution or depthwise convolution layer. Data type supported: F16/F32. Data layout supported: NCHW, NHWC
[in] bn_mean Batch normalization layer mean tensor. Same as input_weights
[in] bn_var Batch normalization layer variance tensor. Same as input_weights
[out] fused_weights Output fused weights tensor. It can be a nullptr in case of in-place computation. Same as input_weights
[out] fused_bias Output fused bias tensor. It can be a nullptr in case of in-place computation and input_bias != nullptr. Same as input_weights
[in] input_bias (Optional) Input bias tensor for convolution or depthwise convolution layer. It can be a nullptr in case the bias tensor is not required. Same as input_weights
[in] bn_beta (Optional) Batch normalization layer beta tensor. It can be a nullptr in case the beta tensor is not required. Same as input_weights
Note
if nullptr, bn_beta is set to 0.0
Parameters
[in] bn_gamma (Optional) Batch normalization layer gamma tensor. It can be a nullptr in case the gamma tensor is not required. Same as input_weights
Note
if nullptr, bn_gamma is set to 1.0
Parameters
[in] epsilon (Optional) Batch normalization layer epsilon parameter. Defaults to 0.001f.
[in] fbn_type (Optional) Fused batch normalization type. Defaults to Convolution.
Definition at line 52 of file CLFuseBatchNormalization.cpp.
 {
     ARM_COMPUTE_LOG_PARAMS(input_weights, bn_mean, bn_var, fused_weights, fused_bias, input_bias, bn_beta, bn_gamma, epsilon, fbn_type);
     _fuse_bn_kernel->configure(compile_context, input_weights, bn_mean, bn_var, fused_weights, fused_bias, input_bias, bn_beta, bn_gamma, epsilon, fbn_type);
 }
References ARM_COMPUTE_LOG_PARAMS, arm_compute::quantization::epsilon, and fbn_type.
configure() [2/2]
void configure (const ICLTensor * input_weights, const ICLTensor * bn_mean, const ICLTensor * bn_var, ICLTensor * fused_weights, ICLTensor * fused_bias, const ICLTensor * input_bias = nullptr, const ICLTensor * bn_beta = nullptr, const ICLTensor * bn_gamma = nullptr, float epsilon = 0.001f, FuseBatchNormalizationType fbn_type = FuseBatchNormalizationType::CONVOLUTION)
Set the input and output tensors.
Valid data layouts:
NHWC
NCHW
Valid data type configurations:
src dst
F32 F32
F16 F16
Parameters
[in] input_weights Input weights tensor for convolution or depthwise convolution layer. Data type supported: F16/F32. Data layout supported: NCHW, NHWC
[in] bn_mean Batch normalization layer mean tensor. Same as input_weights
[in] bn_var Batch normalization layer variance tensor. Same as input_weights
[out] fused_weights Output fused weights tensor. It can be a nullptr in case of in-place computation. Same as input_weights
[out] fused_bias Output fused bias tensor. It can be a nullptr in case of in-place computation and input_bias != nullptr. Same as input_weights
[in] input_bias (Optional) Input bias tensor for convolution or depthwise convolution layer. It can be a nullptr in case the bias tensor is not required. Same as input_weights
[in] bn_beta (Optional) Batch normalization layer beta tensor. It can be a nullptr in case the beta tensor is not required. Same as input_weights
Note
if nullptr, bn_beta is set to 0.0
Parameters
[in] bn_gamma (Optional) Batch normalization layer gamma tensor. It can be a nullptr in case the gamma tensor is not required. Same as input_weights
Note
if nullptr, bn_gamma is set to 1.0
Parameters
[in] epsilon (Optional) Batch normalization layer epsilon parameter. Defaults to 0.001f.
[in] fbn_type (Optional) Fused batch normalization type. Defaults to Convolution.
Definition at line 44 of file CLFuseBatchNormalization.cpp.
 {
     configure(CLKernelLibrary::get().get_compile_context(), input_weights, bn_mean, bn_var, fused_weights, fused_bias, input_bias, bn_beta, bn_gamma, epsilon, fbn_type);
 }
References arm_compute::quantization::epsilon, fbn_type, and CLKernelLibrary::get().
operator=() [1/2]
CLFuseBatchNormalization& operator= (CLFuseBatchNormalization &&) default
Allow instances of this class to be moved.
operator=() [2/2]
CLFuseBatchNormalization& operator= (const CLFuseBatchNormalization &) delete
Prevent instances of this class from being copied (As this class contains pointers)
run()
void run () override virtual
Run the kernels contained in the function.
For CPU kernels:
Multi-threading is used for the kernels which are parallelisable.
By default std::thread::hardware_concurrency() threads are used.
Note
CPPScheduler::set_num_threads() can be used to manually set the number of threads
For OpenCL kernels:
All the kernels are enqueued on the queue associated with CLScheduler.
The queue is then flushed.
Note
The function will not block until the kernels are executed. It is the user's responsibility to wait.
Will call prepare() on first run if hasn't been done
Implements IFunction.
Definition at line 69 of file CLFuseBatchNormalization.cpp.
 {
     CLScheduler::get().enqueue(*_fuse_bn_kernel, true);
 }
References CLScheduler::enqueue(), and CLScheduler::get().
validate()
Status validate (const ITensorInfo * input_weights, const ITensorInfo * bn_mean, const ITensorInfo * bn_var, const ITensorInfo * fused_weights, const ITensorInfo * fused_bias, const ITensorInfo * input_bias = nullptr, const ITensorInfo * bn_beta = nullptr, const ITensorInfo * bn_gamma = nullptr, float epsilon = 0.001f, FuseBatchNormalizationType fbn_type = FuseBatchNormalizationType::CONVOLUTION) static
Static function to check if given info will lead to a valid configuration of CLFuseBatchNormalization.
Parameters
[in] input_weights Input weights tensor info for convolution or depthwise convolution layer. Data type supported: F16/F32. Data layout supported: NCHW, NHWC
[in] bn_mean Batch normalization layer mean tensor info. Same as input_weights
[in] bn_var Batch normalization layer variance tensor info. Same as input_weights
[in] fused_weights Output fused weights tensor info. It can be a nullptr in case of in-place computation. Same as input_weights
[in] fused_bias Output fused bias tensor info. It can be a nullptr in case of in-place computation and input_bias != nullptr. Same as input_weights
[in] input_bias (Optional) Input bias tensor info for convolution or depthwise convolution layer. It can be a nullptr in case the bias tensor is not required. Same as input_weights
[in] bn_beta (Optional) Batch normalization layer beta tensor info. It can be a nullptr in case the beta tensor is not required. Same as input_weights
Note
if nullptr, bn_beta is set to 0.0
Parameters
[in] bn_gamma (Optional) Batch normalization layer gamma tensor info. It can be a nullptr in case the gamma tensor is not required. Same as input_weights
Note
if nullptr, bn_gamma is set to 1.0
Parameters
[in] epsilon (Optional) Batch normalization layer epsilon parameter. Defaults to 0.001f.
[in] fbn_type (Optional) Fused batch normalization type. Defaults to Convolution.
Returns
a status
Definition at line 61 of file CLFuseBatchNormalization.cpp.
 {
     return CLFuseBatchNormalizationKernel::validate(input_weights, bn_mean, bn_var, fused_weights, fused_bias, input_bias, bn_beta, bn_gamma, epsilon, fbn_type);
 }
References arm_compute::quantization::epsilon, fbn_type, and CLFuseBatchNormalizationKernel::validate().
The documentation for this class was generated from the following files:
arm_compute/runtime/CL/functions/CLFuseBatchNormalization.h
src/runtime/CL/functions/CLFuseBatchNormalization.cpp