Compute Library: CLPooling3dLayer Class Reference
CLPooling3dLayer Class Reference
Basic function to run opencl::ClPool3d.
#include <CLPooling3dLayer.h>
Public Member Functions
CLPooling3dLayer ()
Default Constructor.
~CLPooling3dLayer ()
Default Destructor.
CLPooling3dLayer (const CLPooling3dLayer &)=delete
Prevent instances of this class from being copied (As this class contains pointers)
CLPooling3dLayer (CLPooling3dLayer &&)=default
Default move constructor.
CLPooling3dLayer & operator= (const CLPooling3dLayer &)=delete
Prevent instances of this class from being copied (As this class contains pointers)
CLPooling3dLayer & operator= (CLPooling3dLayer &&)=default
Default move assignment operator.
void configure (const ICLTensor *input, ICLTensor *output, const Pooling3dLayerInfo &pool_info)
Set the input and output tensors.
void configure (const CLCompileContext &compile_context, const ICLTensor *input, ICLTensor *output, const Pooling3dLayerInfo &pool_info)
Set the input and output tensors.
void run () override
Run the kernels contained in the function.
Public Member Functions inherited from IFunction
virtual ~IFunction ()=default
Destructor.
virtual void prepare ()
Prepare the function for executing.
Static Public Member Functions
static Status validate (const ITensorInfo *input, const ITensorInfo *output, const Pooling3dLayerInfo &pool_info)
Static function to check if given info will lead to a valid configuration of CLPooling3dLayer.
Detailed Description
Basic function to run opencl::ClPool3d.
Definition at line 40 of file CLPooling3dLayer.h.
Constructor & Destructor Documentation
CLPooling3dLayer() [1/3]
CLPooling3dLayer ()
Default Constructor.
Definition at line 41 of file CLPooling3dLayer.cpp.
     : _impl(std::make_unique<Impl>())
 {
 }
~CLPooling3dLayer()
~CLPooling3dLayer () default
Default Destructor.
CLPooling3dLayer() [2/3]
CLPooling3dLayer (const CLPooling3dLayer &) delete
Prevent instances of this class from being copied (As this class contains pointers)
CLPooling3dLayer() [3/3]
CLPooling3dLayer (CLPooling3dLayer &&) default
Default move constructor.
Member Function Documentation
configure() [1/2]
void configure (const CLCompileContext & compile_context, const ICLTensor * input, ICLTensor * output, const Pooling3dLayerInfo & pool_info)
Set the input and output tensors.
Parameters
[in] compile_context The compile context to be used.
[in,out] input Source tensor. Data types supported: F16/F32/QASYMM8/QASYMM8_SIGNED.
[out] output Destination tensor. Data types supported: Same as input.
[in] pool_info Contains 3d pooling operation information described in Pooling3dLayerInfo.
Definition at line 52 of file CLPooling3dLayer.cpp.
 {
     _impl->src = input;
     _impl->dst = output;
     _impl->op = std::make_unique<opencl::ClPool3d>();
     _impl->op->configure(compile_context, input->info(), output->info(), pool_info);
 }
References ITensor::info(), and arm_compute::test::validation::input.
configure() [2/2]
void configure (const ICLTensor * input, ICLTensor * output, const Pooling3dLayerInfo & pool_info)
Set the input and output tensors.
Valid data layouts:
NDHWC
Valid data type configurations:
src dst
F16 F16
F32 F32
QASYMM8 QASYMM8
QASYMM8_SIGNED QASYMM8_SIGNED
Note
Source tensor is padded with -inf for MAX pooling and 0 otherwise Cases where pooling region is completely outside input tensor are not supported
Asymmetric padding is not supported when dimension rounding type == CEIL.
Parameters
[in,out] input Source tensor. Data types supported: F16/F32/QASYMM8/QASYMM8_SIGNED.
[out] output Destination tensor. Data types supported: Same as input.
[in] pool_info Contains 3d pooling operation information described in Pooling3dLayerInfo.
Definition at line 47 of file CLPooling3dLayer.cpp.
 {
     configure(CLKernelLibrary::get().get_compile_context(), input, output, pool_info);
 }
References CLKernelLibrary::get(), and arm_compute::test::validation::input.
operator=() [1/2]
CLPooling3dLayer& operator= (CLPooling3dLayer &&) default
Default move assignment operator.
operator=() [2/2]
CLPooling3dLayer& operator= (const CLPooling3dLayer &) delete
Prevent instances of this class from being copied (As this class contains pointers)
run()
void run () override virtual
Run the kernels contained in the function.
For CPU kernels:
Multi-threading is used for the kernels which are parallelisable.
By default std::thread::hardware_concurrency() threads are used.
Note
CPPScheduler::set_num_threads() can be used to manually set the number of threads
For OpenCL kernels:
All the kernels are enqueued on the queue associated with CLScheduler.
The queue is then flushed.
Note
The function will not block until the kernels are executed. It is the user's responsibility to wait.
Will call prepare() on first run if hasn't been done
Implements IFunction.
Definition at line 66 of file CLPooling3dLayer.cpp.
 {
     ITensorPack pack;
     pack.add_tensor(TensorType::ACL_SRC, _impl->src);
     pack.add_tensor(TensorType::ACL_DST_0, _impl->dst);
     _impl->op->run(pack);
 }
References arm_compute::ACL_DST_0, arm_compute::ACL_SRC, ITensorPack::add_tensor(), and arm_compute::test::validation::pack.
validate()
Status validate (const ITensorInfo * input, const ITensorInfo * output, const Pooling3dLayerInfo & pool_info) static
Static function to check if given info will lead to a valid configuration of CLPooling3dLayer.
Parameters
[in] input Source tensor info. Data types supported: F16/F32/QASYMM8/QASYMM8_SIGNED.
[in] output Destination tensor info. Data types supported: Same as input.
[in] pool_info Contains 3d pooling operation information described in Pooling3dLayerInfo.
Returns
a status
Definition at line 61 of file CLPooling3dLayer.cpp.
 {
     return opencl::ClPool3d::validate(input, output, pool_info);
 }
References arm_compute::test::validation::input, and ClPool3d::validate().
The documentation for this class was generated from the following files:
arm_compute/runtime/CL/functions/CLPooling3dLayer.h
src/runtime/CL/functions/CLPooling3dLayer.cpp