Compute Library: CpuLogits1DSoftmaxKernel< IS_LOG > Class Template Reference
CpuLogits1DSoftmaxKernel< IS_LOG > Class Template Reference
Interface for softmax computation for QASYMM8 with pre-computed max.
#include <CpuSoftmaxKernel.h>
Data Structures
struct SoftmaxLogits1DKernel
Public Member Functions
CpuLogits1DSoftmaxKernel ()=default
ARM_COMPUTE_DISALLOW_COPY_ALLOW_MOVE (CpuLogits1DSoftmaxKernel)
void configure (const ITensorInfo *src, const ITensorInfo *max, ITensorInfo *dst, const float beta, ITensorInfo *tmp)
Set the input and output tensors.
void run_op (ITensorPack &tensors, const Window &window, const ThreadInfo &info) override
Execute the kernel on the passed window.
const char * name () const override
Name of the kernel.
Public Member Functions inherited from ICPPKernel
virtual ~ICPPKernel ()=default
Default destructor.
virtual void run (const Window &window, const ThreadInfo &info)
Execute the kernel on the passed window.
virtual void run_nd (const Window &window, const ThreadInfo &info, const Window &thread_locator)
legacy compatibility layer for implemantions which do not support thread_locator In these cases we simply narrow the interface down the legacy version
virtual size_t get_mws (const CPUInfo &platform, size_t thread_count) const
Return minimum workload size of the relevant kernel.
Public Member Functions inherited from IKernel
IKernel ()
Constructor.
virtual ~IKernel ()=default
Destructor.
virtual bool is_parallelisable () const
Indicates whether or not the kernel is parallelisable.
virtual BorderSize border_size () const
The size of the border for that kernel.
const Window & window () const
The maximum window the kernel can be executed on.
bool is_window_configured () const
Function to check if the embedded window of this kernel has been configured.
Static Public Member Functions
static Status validate (const ITensorInfo *src, const ITensorInfo *max, const ITensorInfo *dst, const float beta, const ITensorInfo *tmp)
Static function to check if given info will lead to a valid configuration.
static const std::vector< SoftmaxLogits1DKernel > & get_available_kernels ()
Static Public Member Functions inherited from ICpuKernel< CpuLogits1DSoftmaxKernel< false > >
static const auto * get_implementation (const SelectorType &selector, KernelSelectionType selection_type=KernelSelectionType::Supported)
Micro-kernel selector.
Additional Inherited Members
Static Public Attributes inherited from ICPPKernel
static constexpr size_t default_mws = 1
Detailed Description
template<bool IS_LOG = false>
class arm_compute::cpu::kernels::CpuLogits1DSoftmaxKernel< IS_LOG >
Interface for softmax computation for QASYMM8 with pre-computed max.
Definition at line 79 of file CpuSoftmaxKernel.h.
Constructor & Destructor Documentation
CpuLogits1DSoftmaxKernel()
CpuLogits1DSoftmaxKernel () default
Member Function Documentation
ARM_COMPUTE_DISALLOW_COPY_ALLOW_MOVE()
ARM_COMPUTE_DISALLOW_COPY_ALLOW_MOVE (CpuLogits1DSoftmaxKernel< IS_LOG >)
configure()
void configure (const ITensorInfo * src, const ITensorInfo * max, ITensorInfo * dst, const float beta, ITensorInfo * tmp)
Set the input and output tensors.
Parameters
[in] src Source tensor info. Data types supported: QASYMM8/QASYMM8_SIGNED/F16/F32.
[in] max Max values tensor info. Same shape as input with dimension 0 set to 1. Data types supported: same as input.
[out] dst Destination tensor info. Data types supported: same as input.
[in] beta A scaling factor for the exponent.
tmp Auxiliary tensor info. Must be type F32 and same shape as the input.
Definition at line 252 of file CpuSoftmaxKernel.cpp.
 {
     ARM_COMPUTE_ERROR_ON_NULLPTR(src, max, dst, tmp);
     ARM_COMPUTE_ERROR_THROW_ON(validate_arguments_logits_softmax(*src, *max, *dst, beta, *tmp, IS_LOG));
     // Configure kernel window
     const bool is_quantized_asymmetric = is_data_type_quantized_asymmetric(src->data_type());
     // Output auto initialization if not yet initialized
     const QuantizationInfo output_quantization = is_quantized_asymmetric ? arm_compute::get_softmax_output_quantization_info(src->data_type(), IS_LOG) : dst->quantization_info();
     auto_init_if_empty(*dst, TensorInfo(*src).set_quantization_info(output_quantization).reset_padding());
     // Tmp auto initialization if not yet initialized
     const DataType tmp_data_type = is_quantized_asymmetric ? DataType::F32 : src->data_type();
     auto_init_if_empty(*tmp, TensorInfo(*src).set_data_type(tmp_data_type).reset_padding());
     const auto *uk = CpuLogits1DSoftmaxKernel<IS_LOG>::get_implementation(DataTypeISASelectorData{ src->data_type(), CPUInfo::get().get_isa() });
     ARM_COMPUTE_ERROR_ON(uk == nullptr || uk->ukernel == nullptr);
     std::string kernel_name = IS_LOG ? std::string("CpuLogits1DLogSoftmaxKernel") : std::string("CpuLogits1DSoftmaxKernel");
     _beta       = beta;
     _run_method = uk->ukernel;
     _name       = kernel_name.append("/").append(uk->name);
     // Configure kernel window
     Window win = calculate_max_window(*max, Steps());
     ICpuKernel<CpuLogits1DSoftmaxKernel<IS_LOG>>::configure(win);
 }
References ARM_COMPUTE_ERROR_ON, ARM_COMPUTE_ERROR_ON_NULLPTR, ARM_COMPUTE_ERROR_THROW_ON, arm_compute::auto_init_if_empty(), arm_compute::calculate_max_window(), arm_compute::test::validation::configure(), arm_compute::test::validation::dst, arm_compute::F32, CPUInfo::get(), ICpuKernel< CpuLogits1DSoftmaxKernel< false > >::get_implementation(), arm_compute::get_softmax_output_quantization_info(), arm_compute::is_data_type_quantized_asymmetric(), kernel_name, ITensorInfo::reset_padding(), TensorInfo::set_data_type(), TensorInfo::set_quantization_info(), and arm_compute::test::validation::src.
get_available_kernels()
const std::vector< typename CpuLogits1DSoftmaxKernel< IS_LOG >::SoftmaxLogits1DKernel > & get_available_kernels static
Definition at line 246 of file CpuSoftmaxKernel.cpp.
 {
     return available_kernels_logits<IS_LOG>;
 }
name()
const char * name () const override virtual
Name of the kernel.
Returns
Kernel name
Implements ICPPKernel.
Definition at line 316 of file CpuSoftmaxKernel.cpp.
 {
     return _name.c_str();
 }
run_op()
void run_op (ITensorPack & tensors, const Window & window, const ThreadInfo & info) override virtual
Execute the kernel on the passed window.
Warning
If is_parallelisable() returns false then the passed window must be equal to window()
Note
The window has to be a region within the window returned by the window() method
The width of the window has to be a multiple of num_elems_processed_per_iteration().
Parameters
[in] tensors A vector containing the tensors to operate on.
[in] window Region on which to execute the kernel. (Must be a region of the window returned by window())
[in] info Info about executing thread and CPU.
Reimplemented from ICPPKernel.
Definition at line 294 of file CpuSoftmaxKernel.cpp.
 {
     ARM_COMPUTE_UNUSED(info);
     ARM_COMPUTE_ERROR_ON_UNCONFIGURED_KERNEL(this);
     ARM_COMPUTE_ERROR_ON_INVALID_SUBWINDOW(ICpuKernel<CpuLogits1DSoftmaxKernel<IS_LOG>>::window(), window);
     ARM_COMPUTE_ERROR_ON(_run_method == nullptr);
     const auto src = tensors.get_const_tensor(TensorType::ACL_SRC_0);
     auto       max = tensors.get_tensor(TensorType::ACL_SRC_1);
     auto       dst = tensors.get_tensor(TensorType::ACL_DST_0);
     auto       tmp = tensors.get_tensor(TensorType::ACL_DST_1);
     const unsigned int num_elems_processed_per_iteration = src->info()->valid_region().shape.x();
     const unsigned int tmp_size_for_thread               = tmp->info()->element_size() * num_elems_processed_per_iteration;
     ARM_COMPUTE_ERROR_ON(tmp->info()->total_size() < (info.num_threads * tmp_size_for_thread));
     void *tmp_for_thread = tmp->buffer() + (info.thread_id * tmp_size_for_thread);
     _run_method(src, max, tmp_for_thread, dst, _beta, IS_LOG, window);
 }
References arm_compute::ACL_DST_0, arm_compute::ACL_DST_1, arm_compute::ACL_SRC_0, arm_compute::ACL_SRC_1, ARM_COMPUTE_ERROR_ON, ARM_COMPUTE_ERROR_ON_INVALID_SUBWINDOW, ARM_COMPUTE_ERROR_ON_UNCONFIGURED_KERNEL, ARM_COMPUTE_UNUSED, arm_compute::test::validation::dst, ITensorPack::get_const_tensor(), ITensorPack::get_tensor(), arm_compute::test::validation::info, num_elems_processed_per_iteration, and arm_compute::test::validation::src.
validate()
Status validate (const ITensorInfo * src, const ITensorInfo * max, const ITensorInfo * dst, const float beta, const ITensorInfo * tmp) static
Static function to check if given info will lead to a valid configuration.
Similar to CpuLogits1DSoftmaxKernel::configure()
Returns
a status
Definition at line 284 of file CpuSoftmaxKernel.cpp.
 {
     ARM_COMPUTE_ERROR_ON_NULLPTR(src, max, dst, tmp);
     ARM_COMPUTE_RETURN_ON_ERROR(validate_arguments_logits_softmax(*src, *max, *dst, beta, *tmp, IS_LOG));
     return Status{};
 }
References ARM_COMPUTE_ERROR_ON_NULLPTR, ARM_COMPUTE_RETURN_ON_ERROR, arm_compute::test::validation::dst, and arm_compute::test::validation::src.
The documentation for this class was generated from the following files:
src/cpu/kernels/CpuSoftmaxKernel.h
src/cpu/kernels/CpuSoftmaxKernel.cpp