Compute Library: TokenStream Class Reference
TokenStream Class Reference
A stream of token.
#include <MLGOParser.h>
Public Member Functions
TokenStream (std::istream &s, const std::string &delims=",\n")
Constructor.
operator bool () const
Check if there're more (non-End) Tokens.
Token take ()
Get and pop off the current token.
Token peek (size_t i=0)
Peek the next ith token.
CharPosition current_pos () const
Get the position of the current token.
Static Public Attributes
static constexpr size_t max_look_ahead = 10
Detailed Description
A stream of token.
Definition at line 124 of file MLGOParser.h.
Constructor & Destructor Documentation
TokenStream()
TokenStream (std::istream & s, const std::string & delims = ",\n")
Constructor.
Parameters
[in] s Input stream
[in] delims Delimiter characters packed in a string. Each char from the string can be used as a delim on its own
Definition at line 111 of file MLGOParser.cpp.
     : _delims{ delims }, _istream{ s }, _tokens{}, _lookahead_pos{}
 {
     read();
 }
Member Function Documentation
current_pos()
CharPosition current_pos () const inline
Get the position of the current token.
Returns
CharPosition
Definition at line 162 of file MLGOParser.h.
     {
         return _tokens.front().pos;
     }
operator bool()
operator bool () const explicit
Check if there're more (non-End) Tokens.
Returns
true If there are more tokens
false If reached end of stream (only End token)
Definition at line 117 of file MLGOParser.cpp.
 {
     ARM_COMPUTE_ERROR_ON_MSG(_tokens.empty(), "TokenStream can never be empty");
     return !reached_end();
 }
References ARM_COMPUTE_ERROR_ON_MSG.
peek()
Token peek (size_t i = 0)
Peek the next ith token.
Parameters
[in] i The next ith token. i < max_look_ahead.
Returns
Token
Definition at line 134 of file MLGOParser.cpp.
 {
     ARM_COMPUTE_ERROR_ON_MSG(_tokens.empty(), "TokenStream can never be empty");
     ARM_COMPUTE_ERROR_ON_MSG(i >= max_look_ahead, "TokenStream: Exceeding max look ahead");
     // NOTE: If i exceeds the stream (_istream.eof()), read() automatically appends a End token at the end
     while(_istream && _tokens.size() <= i)
     {
         read();
     }
     size_t ind = std::min(i, _tokens.size() - 1);
     return _tokens[ind];
 }
References ARM_COMPUTE_ERROR_ON_MSG, and TokenStream::max_look_ahead.
Referenced by arm_compute::mlgo::parser::accept_l_list(), arm_compute::mlgo::parser::accept_r_list(), and arm_compute::mlgo::parser::accept_text().
take()
Token take ()
Get and pop off the current token.
Returns
Token
Definition at line 123 of file MLGOParser.cpp.
 {
     ARM_COMPUTE_ERROR_ON_MSG(_tokens.empty(), "TokenStream can never be empty");
     Token t = _tokens.front();
     _tokens.pop_front();
     if(_tokens.empty())
     {
         read();
     }
     return t;
 }
References ARM_COMPUTE_ERROR_ON_MSG, and tf_frozen_model_extractor::t.
Referenced by arm_compute::mlgo::parser::accept_l_list(), arm_compute::mlgo::parser::accept_r_list(), arm_compute::mlgo::parser::accept_text(), arm_compute::mlgo::parser::bool_val(), arm_compute::mlgo::parser::end(), arm_compute::mlgo::parser::float_val(), arm_compute::mlgo::parser::int_val(), and arm_compute::mlgo::parser::text_val().
Field Documentation
max_look_ahead
constexpr size_t max_look_ahead = 10 static constexpr
Definition at line 128 of file MLGOParser.h.
Referenced by TokenStream::peek().
The documentation for this class was generated from the following files:
src/runtime/CL/mlgo/MLGOParser.h
src/runtime/CL/mlgo/MLGOParser.cpp