Compute Library: CpuGemmLowpQuantizeDownInt32ToUint8ScaleByFixedPointKernel Class Reference
CpuGemmLowpQuantizeDownInt32ToUint8ScaleByFixedPointKernel Class Reference
Kernel used to quantize down the int32 accumulator values of GEMMLowp to QASYMM8.
#include <CpuGemmLowpQuantizeDownInt32ToUint8ScaleByFixedPointKernel.h>
Public Member Functions
CpuGemmLowpQuantizeDownInt32ToUint8ScaleByFixedPointKernel ()=default
ARM_COMPUTE_DISALLOW_COPY_ALLOW_MOVE (CpuGemmLowpQuantizeDownInt32ToUint8ScaleByFixedPointKernel)
void configure (ITensorInfo *src, ITensorInfo *bias, ITensorInfo *dst, int result_fixedpoint_multiplier, int result_shift, int result_offset_after_shift, int min=0, int max=0)
Initialise the kernel's input and output.
void run_op (ITensorPack &tensors, const Window &window, const ThreadInfo &info) override
Execute the kernel on the passed window.
const char * name () const override
Name of the kernel.
Public Member Functions inherited from ICPPKernel
virtual ~ICPPKernel ()=default
Default destructor.
virtual void run (const Window &window, const ThreadInfo &info)
Execute the kernel on the passed window.
virtual void run_nd (const Window &window, const ThreadInfo &info, const Window &thread_locator)
legacy compatibility layer for implemantions which do not support thread_locator In these cases we simply narrow the interface down the legacy version
virtual size_t get_mws (const CPUInfo &platform, size_t thread_count) const
Return minimum workload size of the relevant kernel.
Public Member Functions inherited from IKernel
IKernel ()
Constructor.
virtual ~IKernel ()=default
Destructor.
virtual bool is_parallelisable () const
Indicates whether or not the kernel is parallelisable.
virtual BorderSize border_size () const
The size of the border for that kernel.
const Window & window () const
The maximum window the kernel can be executed on.
bool is_window_configured () const
Function to check if the embedded window of this kernel has been configured.
Static Public Member Functions
static Status validate (const ITensorInfo *src, const ITensorInfo *bias, const ITensorInfo *dst, int min=0, int max=0)
Static function to check if given info will lead to a valid configuration.
Static Public Member Functions inherited from ICpuKernel< CpuGemmLowpQuantizeDownInt32ToUint8ScaleByFixedPointKernel >
static const auto * get_implementation (const SelectorType &selector, KernelSelectionType selection_type=KernelSelectionType::Supported)
Micro-kernel selector.
Additional Inherited Members
Static Public Attributes inherited from ICPPKernel
static constexpr size_t default_mws = 1
Detailed Description
Kernel used to quantize down the int32 accumulator values of GEMMLowp to QASYMM8.
This kernel takes a final int32 accumulator value (the output of CpuGemmLowpMatrixMultiplyKernel), and processes it to obtain the final QASYMM8 value. The following computations will be performed by the kernel:
Compute fixed point multiplication between each entry of input by result_fixedpoint_multiplier
Add bias to final result if bias tensor is not a nullptr
Round to nearest division by a power-of-two using result_shift
Add offset to each result
Clamp the value between the specified min and max bounds
Clamp the resulting int32 values to the [0..255] range and cast to QASYMM8.
Definition at line 52 of file CpuGemmLowpQuantizeDownInt32ToUint8ScaleByFixedPointKernel.h.
Constructor & Destructor Documentation
CpuGemmLowpQuantizeDownInt32ToUint8ScaleByFixedPointKernel()
CpuGemmLowpQuantizeDownInt32ToUint8ScaleByFixedPointKernel () default
Member Function Documentation
ARM_COMPUTE_DISALLOW_COPY_ALLOW_MOVE()
ARM_COMPUTE_DISALLOW_COPY_ALLOW_MOVE (CpuGemmLowpQuantizeDownInt32ToUint8ScaleByFixedPointKernel)
configure()
void configure (ITensorInfo * src, ITensorInfo * bias, ITensorInfo * dst, int result_fixedpoint_multiplier, int result_shift, int result_offset_after_shift, int min = 0, int max = 0)
Initialise the kernel's input and output.
Parameters
[in] src Input tensor info. Data type supported: S32
[in] bias Biases tensor info. Only shared biases supported and it can be a nullptr if the biases addition is not required. Biases are 1D tensor with dimensions [OFM]. Data type supported: Same as input.
[out] dst Output tensor info. Data type supported: Data type supported: QASYMM8
[in] result_fixedpoint_multiplier Fixed point value to be multiplied to each element of the input matrix when once the result_offset has been add
[in] result_shift Integer value used to round to nearest division by a power-of-two the result after the fixed point multiplication
[in] result_offset_after_shift Offset to be applied to result before converting it back to QASYMM8
[in] min (Optional) Min value used to saturate down the output result before converting back to QASYMM8
[in] max (Optional) Max value used to saturate up the output result before converting back to QASYMM8, Along with min, this value can be used to implement "rectified linear unit" activation functions
Definition at line 182 of file CpuGemmLowpQuantizeDownInt32ToUint8ScaleByFixedPointKernel.cpp.
 {
     ARM_COMPUTE_UNUSED(bias);
     // Perform validate step
     ARM_COMPUTE_ERROR_ON_NULLPTR(src, dst);
     ARM_COMPUTE_ERROR_THROW_ON(validate_arguments(src, bias, dst, min, max));
     _result_fixedpoint_multiplier = result_fixedpoint_multiplier;
     _result_shift                 = result_shift;
     _result_offset_after_shift    = result_offset_after_shift;
     _min                          = min;
     _max                          = max;
     // Output auto inizialitation if not yet initialized
     auto_init_if_empty(*dst, src->clone()->set_data_type(DataType::QASYMM8));
     // Configure kernel window
     auto win_config = calculate_max_window(*src, Steps());
     ICpuKernel::configure(win_config);
     // Check if we need to clamp the result using min and max
     const bool is_bounded_relu = !(min <= 0 && max >= 255);
     _func                      = is_bounded_relu ? &CpuGemmLowpQuantizeDownInt32ToUint8ScaleByFixedPointKernel::run_internal<true> :
                                  &CpuGemmLowpQuantizeDownInt32ToUint8ScaleByFixedPointKernel::run_internal<false>;
 }
References ARM_COMPUTE_ERROR_ON_NULLPTR, ARM_COMPUTE_ERROR_THROW_ON, ARM_COMPUTE_UNUSED, arm_compute::auto_init_if_empty(), bias, arm_compute::calculate_max_window(), arm_compute::test::validation::dst, arm_compute::QASYMM8, arm_compute::test::validation::src, and arm_compute::cpu::kernels::validate_arguments().
name()
const char * name () const override virtual
Name of the kernel.
Returns
Kernel name
Implements ICPPKernel.
Definition at line 230 of file CpuGemmLowpQuantizeDownInt32ToUint8ScaleByFixedPointKernel.cpp.
 {
     return "CpuGemmLowpQuantizeDownInt32ToUint8ScaleByFixedPointKernel";
 }
run_op()
void run_op (ITensorPack & tensors, const Window & window, const ThreadInfo & info) override virtual
Execute the kernel on the passed window.
Warning
If is_parallelisable() returns false then the passed window must be equal to window()
Note
The window has to be a region within the window returned by the window() method
The width of the window has to be a multiple of num_elems_processed_per_iteration().
Parameters
[in] tensors A vector containing the tensors to operate on.
[in] window Region on which to execute the kernel. (Must be a region of the window returned by window())
[in] info Info about executing thread and CPU.
Reimplemented from ICPPKernel.
Definition at line 216 of file CpuGemmLowpQuantizeDownInt32ToUint8ScaleByFixedPointKernel.cpp.
 {
     ARM_COMPUTE_UNUSED(info);
     ARM_COMPUTE_ERROR_ON_UNCONFIGURED_KERNEL(this);
     ARM_COMPUTE_ERROR_ON_INVALID_SUBWINDOW(ICpuKernel::window(), window);
     ARM_COMPUTE_ERROR_ON_MSG(tensors.empty(), "No inputs provided");
     auto src  = tensors.get_const_tensor(TensorType::ACL_SRC);
     auto bias = tensors.get_const_tensor(TensorType::ACL_BIAS);
     auto dst  = tensors.get_tensor(TensorType::ACL_DST);
     (this->*_func)(src, bias, dst, window);
 }
References arm_compute::ACL_BIAS, arm_compute::ACL_DST, arm_compute::ACL_SRC, ARM_COMPUTE_ERROR_ON_INVALID_SUBWINDOW, ARM_COMPUTE_ERROR_ON_MSG, ARM_COMPUTE_ERROR_ON_UNCONFIGURED_KERNEL, ARM_COMPUTE_UNUSED, bias, arm_compute::test::validation::dst, ITensorPack::empty(), ITensorPack::get_const_tensor(), ITensorPack::get_tensor(), arm_compute::test::validation::info, arm_compute::test::validation::src, and IKernel::window().
validate()
Status validate (const ITensorInfo * src, const ITensorInfo * bias, const ITensorInfo * dst, int min = 0, int max = 0) static
Static function to check if given info will lead to a valid configuration.
Similar to CpuGemmLowpQuantizeDownInt32ToUint8ScaleByFixedPointKernel::configure()
Returns
a status
Definition at line 209 of file CpuGemmLowpQuantizeDownInt32ToUint8ScaleByFixedPointKernel.cpp.
 {
     ARM_COMPUTE_ERROR_ON_NULLPTR(src, dst);
     ARM_COMPUTE_RETURN_ON_ERROR(validate_arguments(src, bias, dst, min, max));
     return Status{};
 }
References ARM_COMPUTE_ERROR_ON_NULLPTR, ARM_COMPUTE_RETURN_ON_ERROR, bias, arm_compute::test::validation::dst, arm_compute::test::validation::src, and arm_compute::cpu::kernels::validate_arguments().
Referenced by CpuGemmLowpOutputStage::validate().
The documentation for this class was generated from the following files:
src/cpu/kernels/CpuGemmLowpQuantizeDownInt32ToUint8ScaleByFixedPointKernel.h
src/cpu/kernels/CpuGemmLowpQuantizeDownInt32ToUint8ScaleByFixedPointKernel.cpp