Compute Library: CpuPool3dKernel Class Reference
CpuPool3dKernel Class Reference
Interface for the kernel to perform Pooling 3D.
#include <CpuPool3dKernel.h>
Data Structures
struct Pooling3dKernel
Public Member Functions
CpuPool3dKernel ()=default
ARM_COMPUTE_DISALLOW_COPY_ALLOW_MOVE (CpuPool3dKernel)
void configure (const ITensorInfo *src, ITensorInfo *dst, const Pooling3dLayerInfo &pool_info)
Set the src, dst tensor and pooling info.
void run_op (ITensorPack &tensors, const Window &window, const ThreadInfo &info) override
Execute the kernel on the passed window.
const char * name () const override
Name of the kernel.
Public Member Functions inherited from ICPPKernel
virtual ~ICPPKernel ()=default
Default destructor.
virtual void run (const Window &window, const ThreadInfo &info)
Execute the kernel on the passed window.
virtual void run_nd (const Window &window, const ThreadInfo &info, const Window &thread_locator)
legacy compatibility layer for implemantions which do not support thread_locator In these cases we simply narrow the interface down the legacy version
virtual size_t get_mws (const CPUInfo &platform, size_t thread_count) const
Return minimum workload size of the relevant kernel.
Public Member Functions inherited from IKernel
IKernel ()
Constructor.
virtual ~IKernel ()=default
Destructor.
virtual bool is_parallelisable () const
Indicates whether or not the kernel is parallelisable.
virtual BorderSize border_size () const
The size of the border for that kernel.
const Window & window () const
The maximum window the kernel can be executed on.
bool is_window_configured () const
Function to check if the embedded window of this kernel has been configured.
Static Public Member Functions
static Status validate (const ITensorInfo *src, const ITensorInfo *dst, const Pooling3dLayerInfo &pool_info)
Static function to check if given info will lead to a valid configuration.
static const std::vector< Pooling3dKernel > & get_available_kernels ()
Static Public Member Functions inherited from ICpuKernel< CpuPool3dKernel >
static const auto * get_implementation (const SelectorType &selector, KernelSelectionType selection_type=KernelSelectionType::Supported)
Micro-kernel selector.
Additional Inherited Members
Static Public Attributes inherited from ICPPKernel
static constexpr size_t default_mws = 1
Detailed Description
Interface for the kernel to perform Pooling 3D.
Definition at line 38 of file CpuPool3dKernel.h.
Constructor & Destructor Documentation
CpuPool3dKernel()
CpuPool3dKernel () default
Member Function Documentation
ARM_COMPUTE_DISALLOW_COPY_ALLOW_MOVE()
ARM_COMPUTE_DISALLOW_COPY_ALLOW_MOVE (CpuPool3dKernel)
configure()
void configure (const ITensorInfo * src, ITensorInfo * dst, const Pooling3dLayerInfo & pool_info)
Set the src, dst tensor and pooling info.
Valid data type configurations:
src dst
F16 F16
F32 F32
QASYMM8 QASYMM8
QASYMM8_SIGNED QASYMM8_SIGNED
Parameters
[in] src Source tensor info. Data types supported: F16/F32/QASYMM8/QASYMM8_SIGNED.
[out] dst Destination tensor info. Data types supported: Same as src.
[in] pool_info Contains pooling operation information described in Pooling3dLayerInfo.
Definition at line 121 of file CpuPool3dKernel.cpp.
 {
     ARM_COMPUTE_ERROR_ON_NULLPTR(src, dst);
     // Perform validation step
     ARM_COMPUTE_ERROR_THROW_ON(validate_arguments(src, dst, pool_info));
     // dst auto inizialitation if not yet initialized
     auto_init_if_empty(*dst, src->clone()->set_tensor_shape(compute_pool3d_shape(src->tensor_shape(), pool_info)));
     // Get data layout
     const auto data_layout = src->data_layout();
     const int  idx_width   = get_data_layout_dimension_index(data_layout, DataLayoutDimension::WIDTH);
     const int  idx_height  = get_data_layout_dimension_index(data_layout, DataLayoutDimension::HEIGHT);
     const int  idx_depth   = get_data_layout_dimension_index(data_layout, DataLayoutDimension::DEPTH);
     // Update pool size in case of global pooling
     const bool   is_global_pooling = pool_info.is_global_pooling;
     const Size3D pool_size(
         is_global_pooling ? src->dimension(idx_width) : pool_info.pool_size.width,
         is_global_pooling ? src->dimension(idx_height) : pool_info.pool_size.height,
         is_global_pooling ? src->dimension(idx_depth) : pool_info.pool_size.depth);
     const auto *uk = CpuPool3dKernel::get_implementation(DataTypeISASelectorData{ src->data_type(), CPUInfo::get().get_isa() });
     ARM_COMPUTE_ERROR_ON(uk == nullptr);
     // Set instance variables
     _pool_info  = pool_info;
     _run_method = uk->ukernel;
     _name       = std::string("CpuPool3dKernel").append("/").append(uk->name);
     // Configure kernel window
     Window win = calculate_max_window(*dst, Steps());
     ICpuKernel::configure(win);
 }
References ARM_COMPUTE_ERROR_ON, ARM_COMPUTE_ERROR_ON_NULLPTR, ARM_COMPUTE_ERROR_THROW_ON, arm_compute::auto_init_if_empty(), arm_compute::calculate_max_window(), arm_compute::misc::shape_calculator::compute_pool3d_shape(), arm_compute::test::validation::data_layout, Size3D::depth, arm_compute::DEPTH, arm_compute::test::validation::dst, CPUInfo::get(), arm_compute::get_data_layout_dimension_index(), ICpuKernel< CpuPool3dKernel >::get_implementation(), Size3D::height, arm_compute::HEIGHT, arm_compute::test::validation::idx_height, arm_compute::test::validation::idx_width, Pooling3dLayerInfo::is_global_pooling, Pooling3dLayerInfo::pool_size, arm_compute::test::validation::src, arm_compute::cpu::kernels::validate_arguments(), Size3D::width, and arm_compute::WIDTH.
get_available_kernels()
const std::vector< CpuPool3dKernel::Pooling3dKernel > & get_available_kernels () static
Definition at line 184 of file CpuPool3dKernel.cpp.
 {
     return available_kernels;
 }
name()
const char * name () const override virtual
Name of the kernel.
Returns
Kernel name
Implements ICPPKernel.
Definition at line 179 of file CpuPool3dKernel.cpp.
 {
     return _name.c_str();
 }
run_op()
void run_op (ITensorPack & tensors, const Window & window, const ThreadInfo & info) override virtual
Execute the kernel on the passed window.
Warning
If is_parallelisable() returns false then the passed window must be equal to window()
Note
The window has to be a region within the window returned by the window() method
The width of the window has to be a multiple of num_elems_processed_per_iteration().
Parameters
[in] tensors A vector containing the tensors to operate on.
[in] window Region on which to execute the kernel. (Must be a region of the window returned by window())
[in] info Info about executing thread and CPU.
Reimplemented from ICPPKernel.
Definition at line 166 of file CpuPool3dKernel.cpp.
 {
     ARM_COMPUTE_UNUSED(info);
     ARM_COMPUTE_ERROR_ON_UNCONFIGURED_KERNEL(this);
     ARM_COMPUTE_ERROR_ON_INVALID_SUBWINDOW(ICpuKernel::window(), window);
     ARM_COMPUTE_ERROR_ON(_run_method == nullptr);
     const ITensor *src = tensors.get_const_tensor(TensorType::ACL_SRC_0);
     ITensor       *dst = tensors.get_tensor(TensorType::ACL_DST_0);
     _run_method(src, dst, _pool_info, window);
 }
References arm_compute::ACL_DST_0, arm_compute::ACL_SRC_0, ARM_COMPUTE_ERROR_ON, ARM_COMPUTE_ERROR_ON_INVALID_SUBWINDOW, ARM_COMPUTE_ERROR_ON_UNCONFIGURED_KERNEL, ARM_COMPUTE_UNUSED, arm_compute::test::validation::dst, ITensorPack::get_const_tensor(), ITensorPack::get_tensor(), arm_compute::test::validation::info, arm_compute::test::validation::src, and IKernel::window().
validate()
Status validate (const ITensorInfo * src, const ITensorInfo * dst, const Pooling3dLayerInfo & pool_info) static
Static function to check if given info will lead to a valid configuration.
Similar to CpuPool3dKernel::configure()
Returns
a status
Definition at line 157 of file CpuPool3dKernel.cpp.
 {
     ARM_COMPUTE_RETURN_ERROR_ON_NULLPTR(src);
     ARM_COMPUTE_RETURN_ON_ERROR(validate_arguments(src, dst, pool_info));
     return Status{};
 }
References ARM_COMPUTE_RETURN_ERROR_ON_NULLPTR, ARM_COMPUTE_RETURN_ON_ERROR, arm_compute::test::validation::dst, arm_compute::test::validation::src, and arm_compute::cpu::kernels::validate_arguments().
Referenced by CpuPool3d::validate().
The documentation for this class was generated from the following files:
src/cpu/kernels/CpuPool3dKernel.h
src/cpu/kernels/CpuPool3dKernel.cpp