Compute Library: CpuPool2d Class Reference
CpuPool2d Class Reference
Basic function to simulate a pooling layer with the specified pooling operation.
#include <CpuPool2d.h>
Public Member Functions
CpuPool2d ()
ARM_COMPUTE_DISALLOW_COPY_ALLOW_MOVE (CpuPool2d)
~CpuPool2d ()
void configure (ITensorInfo *src, ITensorInfo *dst, const PoolingLayerInfo &pool_info, ITensorInfo *indices=nullptr)
Set the src and dst tensors.
void run (ITensorPack &tensors) override
Run the kernels contained in the function.
experimental::MemoryRequirements workspace () const override
Return the memory requirements required by the workspace.
Public Member Functions inherited from INEOperator
INEOperator (IRuntimeContext *ctx=nullptr)
Constructor.
INEOperator (const INEOperator &)=delete
Prevent instances of this class from being copied (As this class contains pointers)
INEOperator (INEOperator &&)=default
Default move constructor.
INEOperator & operator= (const INEOperator &)=delete
Prevent instances of this class from being copied (As this class contains pointers)
INEOperator & operator= (INEOperator &&)=default
Default move assignment operator.
~INEOperator ()
Default destructor.
void prepare (ITensorPack &constants) override
Prepare the function for executing.
Public Member Functions inherited from IOperator
virtual ~IOperator ()=default
Destructor.
Static Public Member Functions
static Status validate (const ITensorInfo *src, const ITensorInfo *dst, const PoolingLayerInfo &pool_info, const ITensorInfo *indices=nullptr)
Static function to check if given info will lead to a valid configuration.
Detailed Description
Basic function to simulate a pooling layer with the specified pooling operation.
This function calls the following kernels:
NEFillBorderKernel (executed if padding size is different from zero)
kernels::CpuPool2dKernel
kernels::CpuPool2dAssemblyWrapperKernel
Definition at line 46 of file CpuPool2d.h.
Constructor & Destructor Documentation
CpuPool2d()
CpuPool2d ()
Definition at line 39 of file CpuPool2d.cpp.
     : _pooling_layer_kernel(),
       _asm_glue(),
       _is_global_pooling_layer(false),
       _use_kernel_indices(false),
       _data_layout(DataLayout::NCHW),
       _aux_mem(1)
 {
 }
References arm_compute::NCHW.
~CpuPool2d()
~CpuPool2d () default
Member Function Documentation
ARM_COMPUTE_DISALLOW_COPY_ALLOW_MOVE()
ARM_COMPUTE_DISALLOW_COPY_ALLOW_MOVE (CpuPool2d)
configure()
void configure (ITensorInfo * src, ITensorInfo * dst, const PoolingLayerInfo & pool_info, ITensorInfo * indices = nullptr)
Set the src and dst tensors.
Note
F16 is supported for pool sizes 2 and 3 only
Parameters
[in,out] src Source tensor info. (Written to only when padding != 0) Data types supported: QASYMM8/QASYMM8_SIGNED/F16/F32.
[out] dst Destination tensor info. Data types supported: same as src.
[in] pool_info Contains pooling operation information described in PoolingLayerInfo.
[out] indices (optional) The indices of the maximal values. Data type supported: U32.
Definition at line 51 of file CpuPool2d.cpp.
 {
     ARM_COMPUTE_LOG_PARAMS(src, dst, pool_info, indices);
     // Check if we can run assembly kernels. Currently, indices are not supported by those kernels
     const bool run_optimised = bool(kernels::CpuPool2dAssemblyWrapperKernel::validate(src, dst, pool_info)) && (indices == nullptr);
     // Get data layout
     _data_layout = pool_info.data_layout == DataLayout::UNKNOWN ? src->data_layout() : pool_info.data_layout;
     // Check if we have Global Pooling Layer
     const unsigned int idx_width  = get_data_layout_dimension_index(_data_layout, DataLayoutDimension::WIDTH);
     const unsigned int idx_height = get_data_layout_dimension_index(_data_layout, DataLayoutDimension::HEIGHT);
     _is_global_pooling_layer      = (src->dimension(idx_width) == pool_info.pool_size.width) && (src->dimension(idx_height) == pool_info.pool_size.height);
     _use_kernel_indices           = pool_info.use_kernel_indices;
     if(run_optimised)
     {
         const CPUInfo     &ci          = NEScheduler::get().cpu_info();
         const unsigned int num_threads = NEScheduler::get().num_threads();
         auto pooling_wrapper = std::make_unique<kernels::CpuPool2dAssemblyWrapperKernel>();
         ARM_COMPUTE_ERROR_ON(pooling_wrapper == nullptr);
         pooling_wrapper->configure(src, dst, pool_info, ci);
         // Get kernel's memory requirements
         constexpr size_t alignment      = 4096;
         const size_t     workspace_size = pooling_wrapper->get_working_size(num_threads);
         _aux_mem[0]                     = MemoryInfo(TensorType::ACL_INT_0, MemoryLifetime::Temporary, workspace_size, alignment);
         _asm_glue = std::move(pooling_wrapper);
     }
     else
     {
         // Configure pooling kernel
         auto k = std::make_unique<kernels::CpuPool2dKernel>();
         k->configure(src, dst, pool_info, indices);
         _pooling_layer_kernel = std::move(k);
     }
 }
References arm_compute::ACL_INT_0, ARM_COMPUTE_ERROR_ON, ARM_COMPUTE_LOG_PARAMS, ci, IScheduler::cpu_info(), PoolingLayerInfo::data_layout, arm_compute::test::validation::dst, Scheduler::get(), arm_compute::get_data_layout_dimension_index(), Size2D::height, arm_compute::HEIGHT, arm_compute::test::validation::idx_height, arm_compute::test::validation::idx_width, arm_compute::test::validation::k, IScheduler::num_threads(), PoolingLayerInfo::pool_size, arm_compute::test::validation::src, arm_compute::UNKNOWN, PoolingLayerInfo::use_kernel_indices, CpuPool2dAssemblyWrapperKernel::validate(), Size2D::width, and arm_compute::WIDTH.
run()
void run (ITensorPack & tensors) override virtual
Run the kernels contained in the function.
Parameters
[in] tensors Vector that contains the tensors to operate on.
Reimplemented from INEOperator.
Definition at line 104 of file CpuPool2d.cpp.
 {
     ARM_COMPUTE_ERROR_ON_MSG(tensors.empty(), "No tensors provided");
     if(_asm_glue)
     {
         const auto hints = (_is_global_pooling_layer) ? Window::DimX : Window::DimY;
         NEScheduler::get().schedule_op(_asm_glue.get(), hints, _asm_glue->window(), tensors);
     }
     else
     {
         switch(_data_layout)
         {
             case DataLayout::NCHW:
                 NEScheduler::get().schedule_op(_pooling_layer_kernel.get(), _is_global_pooling_layer ? Window::DimZ : Window::DimY, _pooling_layer_kernel->window(), tensors);
                 break;
             case DataLayout::NHWC:
                 NEScheduler::get().schedule_op(_pooling_layer_kernel.get(), (_use_kernel_indices ? Window::DimY : Window::DimX), _pooling_layer_kernel->window(), tensors);
                 break;
             default:
                 ARM_COMPUTE_ERROR("Data layout not supported");
         }
     }
 }
References ARM_COMPUTE_ERROR, ARM_COMPUTE_ERROR_ON_MSG, Window::DimX, Window::DimY, Window::DimZ, ITensorPack::empty(), Scheduler::get(), arm_compute::NCHW, arm_compute::NHWC, and IScheduler::schedule_op().
validate()
Status validate (const ITensorInfo * src, const ITensorInfo * dst, const PoolingLayerInfo & pool_info, const ITensorInfo * indices = nullptr) static
Static function to check if given info will lead to a valid configuration.
Similar to CpuPool2d::configure()
Returns
a status
Definition at line 92 of file CpuPool2d.cpp.
 {
     const bool run_optimised = bool(kernels::CpuPool2dAssemblyWrapperKernel::validate(src, dst, pool_info)) && (indices == nullptr);
     if(run_optimised)
     {
         return Status{};
     }
     return kernels::CpuPool2dKernel::validate(src, dst, pool_info, indices);
 }
References arm_compute::test::validation::dst, arm_compute::test::validation::src, CpuPool2dKernel::validate(), and CpuPool2dAssemblyWrapperKernel::validate().
Referenced by NEPoolingLayer::validate().
workspace()
experimental::MemoryRequirements workspace () const override virtual
Return the memory requirements required by the workspace.
Reimplemented from INEOperator.
Definition at line 129 of file CpuPool2d.cpp.
 {
     return _aux_mem;
 }
The documentation for this class was generated from the following files:
src/cpu/operators/CpuPool2d.h
src/cpu/operators/CpuPool2d.cpp