Compute Library: ReductionLayerNode Class Reference
ReductionLayerNode Class Reference final
Reduction Operation node.
#include <ReductionLayerNode.h>
Public Member Functions
ReductionLayerNode (ReductionOperation op, unsigned int axis, bool keep_dims=true)
Default Constructor.
ReductionOperation op () const
op accessor
unsigned int axis () const
axis accessor
bool keep_dims () const
keep_dims accessor
NodeType type () const override
Returns node's type.
bool forward_descriptors () override
Forwards descriptor information to outputs if possible.
TensorDescriptor configure_output (size_t idx) const override
Calculates output configuration.
void accept (INodeVisitor &v) override
Accepts a node visitor.
Public Member Functions inherited from INode
INode ()
Constructor.
virtual ~INode ()=default
Destructor.
INode (const INode &)=delete
Prevent instances of this class from being copied (As this class contains pointers)
INode & operator= (const INode &)=delete
Prevent instances of this class from being copy assigned (As this class contains pointers)
INode (INode &&)=default
Allow instances of this class to be moved.
INode & operator= (INode &&)=default
Allow instances of this class to be move assigned.
virtual Status validate () const
Validate node.
std::string name () const
Returns node's name.
NodeID id () const
Returns node's ID.
const Graph * graph () const
Returns node's Graph.
Graph * graph ()
Returns node's Graph.
void set_graph (Graph *g)
Sets the graph that this node is registered to.
void set_id (NodeID id)
Sets the node id.
void set_common_node_parameters (NodeParams common_params)
Sets common node parameters.
void set_requested_target (Target target)
Sets target preference.
void set_assigned_target (Target target)
Sets the final execution target.
void set_output_tensor (TensorID tid, size_t idx)
Sets the output tensor of at a given index.
const std::vector< TensorID > & inputs () const
Returns inputs of the node.
const std::vector< TensorID > & outputs () const
Returns outputs of the node.
const std::vector< EdgeID > & input_edges () const
Returns input edge set.
const std::set< EdgeID > & output_edges () const
Returns output edge set.
TensorID input_id (size_t idx) const
Returns the tensor ID of a given input of the node.
TensorID output_id (size_t idx) const
Returns the tensor ID of a given output of the node.
Tensor * input (size_t idx) const
Returns the tensor of a given input of the node.
Tensor * output (size_t idx) const
Returns the tensor of a given output of the node.
EdgeID input_edge_id (size_t idx) const
Returns the edge ID of a given input of the node.
Edge * input_edge (size_t idx) const
Returns the edge of a given input of the node.
size_t num_inputs () const
Returns number of inputs of the node.
size_t num_outputs () const
Returns number of outputs of the node.
NodeParams common_node_params () const
Returns common node parameters.
Target requested_target () const
Returns requested target for this node.
Target assigned_target () const
Returns assigned target for this node.
const std::list< std::unique_ptr< ConvPostOpInfo > > & post_op_info_list () const
Post operator info list.
std::list< std::unique_ptr< ConvPostOpInfo > > & post_op_info_list ()
Post operator info list.
Detailed Description
Reduction Operation node.
Definition at line 34 of file ReductionLayerNode.h.
Constructor & Destructor Documentation
ReductionLayerNode()
ReductionLayerNode (ReductionOperation op, unsigned int axis, bool keep_dims = true)
Default Constructor.
Definition at line 35 of file ReductionLayerNode.cpp.
     : _op(op), _axis(axis), _keep_dims(keep_dims)
 {
     _input_edges.resize(1, EmptyEdgeID);
     _outputs.resize(1, NullTensorID);
 }
References arm_compute::graph::EmptyEdgeID, and arm_compute::graph::NullTensorID.
Member Function Documentation
accept()
void accept (INodeVisitor & v) override virtual
Accepts a node visitor.
Parameters
[in] v Visitor to accept
Implements INode.
Definition at line 89 of file ReductionLayerNode.cpp.
 {
     v.visit(*this);
 }
References INodeVisitor::visit().
axis()
unsigned int axis () const
axis accessor
Returns
axis
Definition at line 47 of file ReductionLayerNode.cpp.
 {
     return _axis;
 }
Referenced by arm_compute::graph::backends::detail::create_reduction_operation_layer(), and arm_compute::graph::backends::detail::validate_reduction_operation_layer().
configure_output()
TensorDescriptor configure_output (size_t idx) const override virtual
Calculates output configuration.
Parameters
[in] idx Output index to configure
Returns
Output descriptor configuration
Implements INode.
Definition at line 69 of file ReductionLayerNode.cpp.
 {
     ARM_COMPUTE_UNUSED(idx);
     ARM_COMPUTE_ERROR_ON(idx >= _outputs.size());
     const Tensor *src = input(0);
     ARM_COMPUTE_ERROR_ON(src == nullptr);
     TensorDescriptor output_info  = src->desc();
     TensorShape      output_shape = arm_compute::misc::shape_calculator::compute_reduced_shape(output_info.shape, _axis, _keep_dims);
     output_info.set_shape(output_shape);
     return output_info;
 }
References ARM_COMPUTE_ERROR_ON, ARM_COMPUTE_UNUSED, arm_compute::misc::shape_calculator::compute_reduced_shape(), INode::input(), arm_compute::test::validation::output_info, arm_compute::test::validation::output_shape, and arm_compute::test::validation::src.
Referenced by ReductionLayerNode::forward_descriptors().
forward_descriptors()
bool forward_descriptors () override virtual
Forwards descriptor information to outputs if possible.
Returns
True if descriptor information could be forwarded otherwise false
Implements INode.
Definition at line 57 of file ReductionLayerNode.cpp.
 {
     if((input_id(0) != NullTensorID) && (output_id(0) != NullTensorID))
     {
         Tensor *dst = output(0);
         ARM_COMPUTE_ERROR_ON(dst == nullptr);
         dst->desc() = configure_output(0);
         return true;
     }
     return false;
 }
References ARM_COMPUTE_ERROR_ON, ReductionLayerNode::configure_output(), arm_compute::test::validation::dst, INode::input_id(), arm_compute::graph::NullTensorID, INode::output(), and INode::output_id().
keep_dims()
bool keep_dims () const
keep_dims accessor
Returns
keep_dims
Definition at line 52 of file ReductionLayerNode.cpp.
 {
     return _keep_dims;
 }
Referenced by arm_compute::graph::backends::detail::create_reduction_operation_layer(), and arm_compute::graph::backends::detail::validate_reduction_operation_layer().
op()
ReductionOperation op () const
op accessor
Returns
op
Definition at line 42 of file ReductionLayerNode.cpp.
 {
     return _op;
 }
Referenced by arm_compute::graph::backends::detail::create_reduction_operation_layer(), and arm_compute::graph::backends::detail::validate_reduction_operation_layer().
type()
NodeType type () const override virtual
Returns node's type.
Returns
Node's type
Implements INode.
Definition at line 84 of file ReductionLayerNode.cpp.
 {
     return NodeType::ReductionOperationLayer;
 }
References arm_compute::graph::ReductionOperationLayer.
Referenced by arm_compute::graph::backends::detail::create_reduction_operation_layer().
The documentation for this class was generated from the following files:
arm_compute/graph/nodes/ReductionLayerNode.h
src/graph/nodes/ReductionLayerNode.cpp