Compute Library: arm_compute::experimental Namespace Reference
arm_compute::experimental Namespace Reference
Namespaces
dynamic_fusion
Data Structures
class CLLogicalAnd
class CLLogicalOr
class CLSlice
Basic function to perform tensor slicing.
class CLStridedSlice
Basic function to run CLStridedSliceKernel.
class ICLOperator
Basic interface for functions which have a single async CL kernel.
class INEOperator
Basic interface for functions which have a single async CPU kernel.
class IOperator
Base class for all async functions.
struct IPostOp
An elementwise n-ary operation that can be appended to and fused with (at kernel-level) other operators It contains:
struct MemoryInfo
class NESlice
Basic function to perform tensor slicing.
class NEStridedSlice
Basic function to run NEStridedSliceKernel.
class OperatorTensor
Basic implementation of the tensor interface.
struct PostOpAct
(EXPERIMENTAL_POST_OPS) Implementation of specific IPostOps
class PostOpCLKernelUtils
Manage validation, building and configurations of PostOp CL kernels.
struct PostOpEltwiseAdd
struct PostOpEltwisePRelu
class PostOpList
A sequence of PostOps that can be appended to the end of other operators.
Typedefs
using PostOpTypeSequence = std::vector< PostOpType >
An ordered sequence of type of Post Ops.
using MemoryRequirements = std::vector< MemoryInfo >
Enumerations
enum PostOpType { Activation, Eltwise_Add, Eltwise_PRelu }
Type of Post Op.
enum MemoryLifetime { Temporary = 0, Persistent = 1, Prepare = 2 }
enum MemoryType { CPU, CL }
Memory type.
Functions
template<typename FromTensorT , typename ToTensorT >
PostOpList< ToTensorT > transform_post_op_list_arguments (const PostOpList< FromTensorT > &post_ops, std::function< ToTensorT(FromTensorT)> transform_arg)
Transform a PostOpList of type FromTensorT to one of type ToTensorT.
TensorType get_post_op_arg_type (size_t index)
Get post op argument TensorType from post op argument index in a flattened, ordered post op argument list.
template<typename T >
PostOpTypeSequence get_post_op_sequence (const PostOpList< T > &post_ops)
Get a sequence of PostOp Types from PostOpList.
Typedef Documentation
MemoryRequirements
using MemoryRequirements = std::vector<MemoryInfo>
Definition at line 134 of file Types.h.
PostOpTypeSequence
using PostOpTypeSequence = std::vector<PostOpType>
An ordered sequence of type of Post Ops.
Definition at line 43 of file IPostOp.h.
Enumeration Type Documentation
MemoryLifetime
enum MemoryLifetime strong
Enumerator
Temporary
Persistent
Prepare
Definition at line 90 of file Types.h.
 {
     Temporary  = 0,
     Persistent = 1,
     Prepare    = 2,
 };
MemoryType
enum MemoryType strong
Memory type.
Enumerator
CPU
CL
Definition at line 34 of file Types.h.
 {
     CPU,
     CL,
 };
PostOpType
enum PostOpType strong
Type of Post Op.
Enumerator
Activation
Eltwise_Add
Eltwise_PRelu
Definition at line 36 of file IPostOp.h.
 {
     Activation,
     Eltwise_Add,
     Eltwise_PRelu
 };
Function Documentation
get_post_op_arg_type()
TensorType arm_compute::experimental::get_post_op_arg_type (size_t index) inline
Get post op argument TensorType from post op argument index in a flattened, ordered post op argument list.
Definition at line 77 of file PostOpUtils.h.
 {
     ARM_COMPUTE_ERROR_ON_MSG(static_cast<int>(index) > EXPERIMENTAL_ACL_POST_OP_ARG_LAST - EXPERIMENTAL_ACL_POST_OP_ARG_FIRST, "Post Op argument index is out of range");
     return static_cast<TensorType>(EXPERIMENTAL_ACL_POST_OP_ARG_FIRST + static_cast<int>(index));
 }
References ARM_COMPUTE_ERROR_ON_MSG, arm_compute::EXPERIMENTAL_ACL_POST_OP_ARG_FIRST, and arm_compute::EXPERIMENTAL_ACL_POST_OP_ARG_LAST.
Referenced by CLGEMMConvolutionLayer::configure(), CLConvolutionLayer::configure(), ClGemmMatrixMultiplyNativeKernel::run_op(), ClGemmMatrixMultiplyReshapedOnlyRhsKernel::run_op(), and ClGemmMatrixMultiplyReshapedKernel::run_op().
get_post_op_sequence()
PostOpTypeSequence arm_compute::experimental::get_post_op_sequence (const PostOpList< T > & post_ops)
Get a sequence of PostOp Types from PostOpList.
Definition at line 85 of file PostOpUtils.h.
 {
     PostOpTypeSequence post_op_sequence;
     for(const auto &op : post_ops.get_list())
     {
         post_op_sequence.push_back(op->type());
     }
     return post_op_sequence;
 }
References arm_compute::test::validation::post_ops.
Referenced by PostOpCLKernelUtils::is_post_op_sequence_supported(), PostOpCLKernelUtils::set_post_ops_cl_build_options(), and PostOpCLKernelUtils::set_post_ops_cl_kernel_name().
transform_post_op_list_arguments()
PostOpList<ToTensorT> arm_compute::experimental::transform_post_op_list_arguments (const PostOpList< FromTensorT > & post_ops, std::function< ToTensorT(FromTensorT)> transform_arg)
Transform a PostOpList of type FromTensorT to one of type ToTensorT.
Definition at line 42 of file PostOpUtils.h.
 {
     PostOpList<ToTensorT> transformed_post_ops;
     for(const auto &post_op : post_ops.get_list())
     {
         switch(post_op->type())
         {
             case PostOpType::Activation:
             {
                 const auto _post_op = utils::cast::polymorphic_downcast<const PostOpAct<FromTensorT> *>(post_op.get());
                 transformed_post_ops.template push_back_op<PostOpAct<ToTensorT>>(_post_op->_act_info);
                 break;
             }
             case PostOpType::Eltwise_Add:
             {
                 const auto _post_op = utils::cast::polymorphic_downcast<const PostOpEltwiseAdd<FromTensorT> *>(post_op.get());
                 transformed_post_ops.template push_back_op<PostOpEltwiseAdd<ToTensorT>>(transform_arg(_post_op->_addend), _post_op->_prev_dst_pos, _post_op->_policy);
                 break;
             }
             case PostOpType::Eltwise_PRelu:
             {
                 const auto _post_op = utils::cast::polymorphic_downcast<const PostOpEltwisePRelu<FromTensorT> *>(post_op.get());
                 transformed_post_ops.template push_back_op<PostOpEltwisePRelu<ToTensorT>>(transform_arg(_post_op->_alpha_param), _post_op->_prev_dst_pos, _post_op->_policy);
                 break;
             }
             default:
             {
                 ARM_COMPUTE_ERROR("Unsupported PostOpType");
             }
         }
     }
     return transformed_post_ops;
 }
References Activation, ARM_COMPUTE_ERROR, Eltwise_Add, Eltwise_PRelu, and arm_compute::test::validation::post_ops.