Compute Library: src/c/AclQueue.cpp File Reference
AclQueue.cpp File Reference
#include "arm_compute/AclEntrypoints.h"
#include "src/common/IQueue.h"
#include "src/common/utils/Macros.h"
#include "src/common/utils/Validate.h"
Functions
AclStatus AclCreateQueue (AclQueue *external_queue, AclContext external_ctx, const AclQueueOptions *options)
Create an operator queue.
AclStatus AclQueueFinish (AclQueue external_queue)
Wait until all elements on the queue have been completed.
AclStatus AclDestroyQueue (AclQueue external_queue)
Destroy a given queue object.
Function Documentation
AclCreateQueue()
AclStatus AclCreateQueue (AclQueue * queue, AclContext ctx, const AclQueueOptions * options)
Create an operator queue.
Queue is responsible for any scheduling related activities
Parameters
[in,out] queue A valid non-zero queue object is not failures occur
[in] ctx Context to be used
[in] options Queue options to be used for the operators using the queue
Returns
Status code
Returns:
AclSuccess if function was completed successfully
AclOutOfMemory if there was a failure allocating memory resources
AclUnsupportedTarget if the requested target is unsupported
AclInvalidArgument if a given argument is invalid
Definition at line 45 of file AclQueue.cpp.
 {
     using namespace arm_compute;
     auto ctx = get_internal(external_ctx);
     StatusCode status = detail::validate_internal_context(ctx);
     ARM_COMPUTE_RETURN_CENUM_ON_FAILURE(status);
     if (options != nullptr && !is_mode_valid(options))
     {
         ARM_COMPUTE_LOG_ERROR_ACL("Queue options are invalid");
         return AclInvalidArgument;
     }
     auto queue = ctx->create_queue(options);
     if (queue == nullptr)
     {
         ARM_COMPUTE_LOG_ERROR_ACL("Couldn't allocate internal resources");
         return AclOutOfMemory;
     }
     *external_queue = queue;
     return AclSuccess;
 }
References AclInvalidArgument, AclOutOfMemory, AclSuccess, ARM_COMPUTE_LOG_ERROR_ACL, ARM_COMPUTE_RETURN_CENUM_ON_FAILURE, arm_compute::get_internal(), and arm_compute::detail::validate_internal_context().
Referenced by Queue::Queue().
AclDestroyQueue()
AclStatus AclDestroyQueue (AclQueue queue)
Destroy a given queue object.
Parameters
[in] queue A valid context object to destroy
Returns
Status code
Returns:
AclSuccess if functions was completed successfully
AclInvalidArgument if the provided context is invalid
Definition at line 87 of file AclQueue.cpp.
 {
     using namespace arm_compute;
     auto queue = get_internal(external_queue);
     StatusCode status = detail::validate_internal_queue(queue);
     ARM_COMPUTE_RETURN_CENUM_ON_FAILURE(status);
     delete queue;
     return AclSuccess;
 }
References AclSuccess, ARM_COMPUTE_RETURN_CENUM_ON_FAILURE, arm_compute::get_internal(), and arm_compute::detail::validate_internal_queue().
AclQueueFinish()
AclStatus AclQueueFinish (AclQueue queue)
Wait until all elements on the queue have been completed.
Parameters
[in] queue Queue to wait on completion
Returns
Status code
Returns:
AclSuccess if functions was completed successfully
AclInvalidArgument if the provided queue is invalid
AclRuntimeError on any other runtime related error
Definition at line 72 of file AclQueue.cpp.
 {
     using namespace arm_compute;
     auto queue = get_internal(external_queue);
     StatusCode status = detail::validate_internal_queue(queue);
     ARM_COMPUTE_RETURN_CENUM_ON_FAILURE(status);
     status = queue->finish();
     ARM_COMPUTE_RETURN_CENUM_ON_FAILURE(status);
     return AclSuccess;
 }
References AclSuccess, ARM_COMPUTE_RETURN_CENUM_ON_FAILURE, arm_compute::get_internal(), and arm_compute::detail::validate_internal_queue().
Referenced by Queue::finish().