Compute Library: NEElementwiseComparisonStatic< op > Class Template Reference
NEElementwiseComparisonStatic< op > Class Template Reference
Basic function to run cpu::kernels::CpuComparisonKernel.
#include <NEElementwiseOperations.h>
Public Member Functions
NEElementwiseComparisonStatic ()
Default Constructor.
~NEElementwiseComparisonStatic ()
Default Destructor.
NEElementwiseComparisonStatic (const NEElementwiseComparisonStatic &)=delete
Prevent instances of this class from being copied (As this class contains pointers)
NEElementwiseComparisonStatic (NEElementwiseComparisonStatic &&)
Default move constructor.
NEElementwiseComparisonStatic & operator= (const NEElementwiseComparisonStatic &)=delete
Prevent instances of this class from being copied (As this class contains pointers)
NEElementwiseComparisonStatic & operator= (NEElementwiseComparisonStatic &&)
Default move assignment operator.
void configure (ITensor *input1, ITensor *input2, ITensor *output)
Initialise the kernel's inputs, output and conversion policy.
void run () override
Run the kernels contained in the function.
Public Member Functions inherited from IFunction
virtual ~IFunction ()=default
Destructor.
virtual void prepare ()
Prepare the function for executing.
Static Public Member Functions
static Status validate (const ITensorInfo *input1, const ITensorInfo *input2, const ITensorInfo *output)
Static function to check if given info will lead to a valid configuration of cpu::kernels::CpuComparisonKernel.
Detailed Description
template<ComparisonOperation op>
class arm_compute::NEElementwiseComparisonStatic< op >
Basic function to run cpu::kernels::CpuComparisonKernel.
Note
The tensor data type for the inputs must be U8/QASYMM8/QASYMM8_SIGNED/S16/F16/S32/F32.
The function performs a comparison operation between two tensors.
Definition at line 427 of file NEElementwiseOperations.h.
Constructor & Destructor Documentation
NEElementwiseComparisonStatic() [1/3]
NEElementwiseComparisonStatic
Default Constructor.
Definition at line 269 of file NEElementwiseOperations.cpp.
                                                                   : _impl(std::make_unique<Impl>())
 {
 }
~NEElementwiseComparisonStatic()
~NEElementwiseComparisonStatic () default
Default Destructor.
NEElementwiseComparisonStatic() [2/3]
NEElementwiseComparisonStatic (const NEElementwiseComparisonStatic< op > &) delete
Prevent instances of this class from being copied (As this class contains pointers)
NEElementwiseComparisonStatic() [3/3]
NEElementwiseComparisonStatic (NEElementwiseComparisonStatic< op > &&) default
Default move constructor.
Member Function Documentation
configure()
void configure (ITensor * input1, ITensor * input2, ITensor * output)
Initialise the kernel's inputs, output and conversion policy.
Parameters
[in,out] input1 First tensor input. Data types supported: U8/QASYMM8/QASYMM8_SIGNED/S16/F16/S32/F32.
[in,out] input2 Second tensor input. Data types supported: Same as input1.
[out] output Output tensor. Data types supported: U16/U32.
Definition at line 281 of file NEElementwiseOperations.cpp.
 {
     _impl->src_0 = input1;
     _impl->src_1 = input2;
     _impl->dst   = output;
     _impl->op    = std::make_unique<cpu::CpuElementwiseComparisonStatic<COP>>();
     _impl->op->configure(input1->info(), input2->info(), output->info());
 }
References ITensor::info().
operator=() [1/2]
NEElementwiseComparisonStatic& operator= (const NEElementwiseComparisonStatic< op > &) delete
Prevent instances of this class from being copied (As this class contains pointers)
operator=() [2/2]
NEElementwiseComparisonStatic< COP > & operator= (NEElementwiseComparisonStatic< op > &&) default
Default move assignment operator.
run()
void run () override virtual
Run the kernels contained in the function.
For CPU kernels:
Multi-threading is used for the kernels which are parallelisable.
By default std::thread::hardware_concurrency() threads are used.
Note
CPPScheduler::set_num_threads() can be used to manually set the number of threads
For OpenCL kernels:
All the kernels are enqueued on the queue associated with CLScheduler.
The queue is then flushed.
Note
The function will not block until the kernels are executed. It is the user's responsibility to wait.
Will call prepare() on first run if hasn't been done
Implements IFunction.
Definition at line 299 of file NEElementwiseOperations.cpp.
 {
     ITensorPack pack;
     pack.add_tensor(TensorType::ACL_SRC_0, _impl->src_0);
     pack.add_tensor(TensorType::ACL_SRC_1, _impl->src_1);
     pack.add_tensor(TensorType::ACL_DST, _impl->dst);
     _impl->op->run(pack);
 }
References arm_compute::ACL_DST, arm_compute::ACL_SRC_0, arm_compute::ACL_SRC_1, ITensorPack::add_tensor(), and arm_compute::test::validation::pack.
validate()
Status validate (const ITensorInfo * input1, const ITensorInfo * input2, const ITensorInfo * output) static
Static function to check if given info will lead to a valid configuration of cpu::kernels::CpuComparisonKernel.
Parameters
[in] input1 First tensor input info. Data types supported: U8/QASYMM8/QASYMM8_SIGNED/S16/F16/S32/F32.
[in] input2 Second tensor input info. Data types supported: Same as input1.
[in] output Output tensor info. Data types supported: U16/U32.
Returns
a status
Definition at line 291 of file NEElementwiseOperations.cpp.
 {
     return cpu::CpuElementwiseComparisonStatic<COP>::validate(input1, input2, output);
 }
References CpuElementwiseComparisonStatic< op >::validate().
The documentation for this class was generated from the following files:
arm_compute/runtime/NEON/functions/NEElementwiseOperations.h
src/runtime/NEON/functions/NEElementwiseOperations.cpp