Compute Library: CpuFlatten Class Reference
CpuFlatten Class Reference
Basic function to flatten a given input.
#include <CpuFlatten.h>
Public Member Functions
CpuFlatten ()
Constructor.
~CpuFlatten ()
Destructor.
void configure (const ITensorInfo *src, ITensorInfo *dst)
Configure operator for a given list of arguments.
void run (ITensorPack &tensors) override
Run the kernels contained in the function.
Public Member Functions inherited from INEOperator
INEOperator (IRuntimeContext *ctx=nullptr)
Constructor.
INEOperator (const INEOperator &)=delete
Prevent instances of this class from being copied (As this class contains pointers)
INEOperator (INEOperator &&)=default
Default move constructor.
INEOperator & operator= (const INEOperator &)=delete
Prevent instances of this class from being copied (As this class contains pointers)
INEOperator & operator= (INEOperator &&)=default
Default move assignment operator.
~INEOperator ()
Default destructor.
void prepare (ITensorPack &constants) override
Prepare the function for executing.
MemoryRequirements workspace () const override
Return the memory requirements required by the workspace.
Public Member Functions inherited from IOperator
virtual ~IOperator ()=default
Destructor.
Static Public Member Functions
static Status validate (const ITensorInfo *src, const ITensorInfo *dst)
Static function to check if given info will lead to a valid configuration.
Detailed Description
Basic function to flatten a given input.
Definition at line 35 of file CpuFlatten.h.
Constructor & Destructor Documentation
CpuFlatten()
CpuFlatten ()
Constructor.
Definition at line 33 of file CpuFlatten.cpp.
                        : _reshape(nullptr)
 {
 }
~CpuFlatten()
~CpuFlatten () default
Destructor.
Member Function Documentation
configure()
void configure (const ITensorInfo * src, ITensorInfo * dst)
Configure operator for a given list of arguments.
Valid data layouts:
All
Valid data type configurations:
src dst
All All
Parameters
[in] src Source tensor to flatten with at least 3 dimensions. The dimensions above the third will be interpreted as batches. Data types supported: All
[in] dst Destination tensor with shape [w*h*d, input_batches] where: w = width input tensor, h = height input tensor and d = depth input tensor. Data type supported: same as src
Definition at line 39 of file CpuFlatten.cpp.
 {
     ARM_COMPUTE_LOG_PARAMS(src, dst);
     _reshape = std::make_unique<CpuReshape>();
     _reshape->configure(src, dst);
 }
References ARM_COMPUTE_LOG_PARAMS, arm_compute::test::validation::dst, and arm_compute::test::validation::src.
run()
void run (ITensorPack & tensors) override virtual
Run the kernels contained in the function.
Parameters
[in] tensors Vector that contains the tensors to operate on.
Reimplemented from INEOperator.
Definition at line 51 of file CpuFlatten.cpp.
 {
     _reshape->run(tensors);
 }
validate()
Status validate (const ITensorInfo * src, const ITensorInfo * dst) static
Static function to check if given info will lead to a valid configuration.
Similar to CpuFlatten::configure()
Returns
a status
Definition at line 46 of file CpuFlatten.cpp.
 {
     return CpuReshape::validate(src, dst);
 }
References arm_compute::test::validation::dst, arm_compute::test::validation::src, and CpuReshape::validate().
Referenced by NEFlattenLayer::validate(), and CpuFullyConnected::validate().
The documentation for this class was generated from the following files:
src/cpu/operators/CpuFlatten.h
src/cpu/operators/CpuFlatten.cpp