Compute Library: CLDepthwiseConvolutionLayerNativeKernel Class Reference
CLDepthwiseConvolutionLayerNativeKernel Class Reference
Interface for the kernel to run a MxN depthwise convolution.
#include <CLDepthwiseConvolutionLayerNativeKernel.h>
Public Member Functions
CLDepthwiseConvolutionLayerNativeKernel ()
Default Constructor.
CLDepthwiseConvolutionLayerNativeKernel (const CLDepthwiseConvolutionLayerNativeKernel &)=delete
Prevent instances of this class from being copied (As this class contains pointers)
CLDepthwiseConvolutionLayerNativeKernel & operator= (const CLDepthwiseConvolutionLayerNativeKernel &)=delete
Prevent instances of this class from being copied (As this class contains pointers)
CLDepthwiseConvolutionLayerNativeKernel (CLDepthwiseConvolutionLayerNativeKernel &&)=default
Allow instances of this class to be moved.
CLDepthwiseConvolutionLayerNativeKernel & operator= (CLDepthwiseConvolutionLayerNativeKernel &&)=default
Allow instances of this class to be moved.
void configure (const CLCompileContext &compile_context, ICLTensor *input, const ICLTensor *weights, const ICLTensor *biases, ICLTensor *output, const DWCComputeKernelInfo &dwc_info, const ConvolutionInfo &conv_info, const ICLTensor *output_multipliers=nullptr, const ICLTensor *output_shifts=nullptr)
Initialize the function's source, destination and parameters.
void configure (ICLTensor *input, const ICLTensor *weights, const ICLTensor *biases, ICLTensor *output, const DWCComputeKernelInfo &dwc_info, const ConvolutionInfo &conv_info, const ICLTensor *output_multipliers=nullptr, const ICLTensor *output_shifts=nullptr)
Static function to check if given info will lead to a valid configuration of CLDepthwiseConvolutionLayerNativeKernel.
void run (const Window &window, cl::CommandQueue &queue) override
Enqueue the OpenCL kernel to process the given window on the passed OpenCL command queue.
Public Member Functions inherited from ICLKernel
ICLKernel ()
Constructor.
cl::Kernel & kernel ()
Returns a reference to the OpenCL kernel of this object.
CLKernelType type () const
Returns the CL kernel type.
template<typename T >
void add_1D_array_argument (unsigned int &idx, const ICLArray< T > *array, const Strides &strides, unsigned int num_dimensions, const Window &window)
Add the passed 1D array's parameters to the object's kernel's arguments starting from the index idx.
void add_1D_tensor_argument (unsigned int &idx, const ICLTensor *tensor, const Window &window)
Add the passed 1D tensor's parameters to the object's kernel's arguments starting from the index idx.
void add_1D_tensor_argument_if (bool cond, unsigned int &idx, const ICLTensor *tensor, const Window &window)
Add the passed 1D tensor's parameters to the object's kernel's arguments starting from the index idx if the condition is true.
void add_2D_tensor_argument (unsigned int &idx, const ICLTensor *tensor, const Window &window)
Add the passed 2D tensor's parameters to the object's kernel's arguments starting from the index idx.
void add_2D_tensor_argument_if (bool cond, unsigned int &idx, const ICLTensor *tensor, const Window &window)
Add the passed 2D tensor's parameters to the object's kernel's arguments starting from the index idx if the condition is true.
void add_3D_tensor_argument (unsigned int &idx, const ICLTensor *tensor, const Window &window)
Add the passed 3D tensor's parameters to the object's kernel's arguments starting from the index idx.
void add_4D_tensor_argument (unsigned int &idx, const ICLTensor *tensor, const Window &window)
Add the passed 4D tensor's parameters to the object's kernel's arguments starting from the index idx.
void add_5D_tensor_argument (unsigned int &idx, const ICLTensor *tensor, const Window &window)
Add the passed 5D tensor's parameters to the object's kernel's arguments starting from the index idx.
void add_3d_tensor_nhw_argument (unsigned int &idx, const ICLTensor *tensor)
Add the passed NHW 3D tensor's parameters to the object's kernel's arguments by passing strides, dimensions and the offset to the first valid element in bytes.
void add_4d_tensor_nhwc_argument (unsigned int &idx, const ICLTensor *tensor)
Add the passed NHWC 4D tensor's parameters to the object's kernel's arguments by passing strides, dimensions and the offset to the first valid element in bytes.
virtual void run_op (ITensorPack &tensors, const Window &window, cl::CommandQueue &queue)
Enqueue the OpenCL kernel to process the given window on the passed OpenCL command queue.
template<typename T >
void add_argument (unsigned int &idx, T value)
Add the passed parameters to the object's kernel's arguments starting from the index idx.
void set_lws_hint (const cl::NDRange &lws_hint)
Set the Local-Workgroup-Size hint.
cl::NDRange lws_hint () const
Return the Local-Workgroup-Size hint.
void set_wbsm_hint (const cl_int &wbsm_hint)
Set the workgroup batch size modifier hint.
cl_int wbsm_hint () const
Return the workgroup batch size modifier hint.
const std::string & config_id () const
Get the configuration ID.
void set_target (GPUTarget target)
Set the targeted GPU architecture.
void set_target (cl::Device &device)
Set the targeted GPU architecture according to the CL device.
GPUTarget get_target () const
Get the targeted GPU architecture.
size_t get_max_workgroup_size ()
Get the maximum workgroup size for the device the CLKernelLibrary uses.
cl::NDRange get_cached_gws () const
Get the cached gws used to enqueue this kernel.
void cache_gws (const cl::NDRange &gws)
Cache the latest gws used to enqueue this kernel.
template<unsigned int dimension_size>
void add_tensor_argument (unsigned &idx, const ICLTensor *tensor, const Window &window)
template<typename T , unsigned int dimension_size>
void add_array_argument (unsigned &idx, const ICLArray< T > *array, const Strides &strides, unsigned int num_dimensions, const Window &window)
Add the passed array's parameters to the object's kernel's arguments starting from the index idx.
Public Member Functions inherited from IKernel
IKernel ()
Constructor.
virtual ~IKernel ()=default
Destructor.
virtual bool is_parallelisable () const
Indicates whether or not the kernel is parallelisable.
virtual BorderSize border_size () const
The size of the border for that kernel.
const Window & window () const
The maximum window the kernel can be executed on.
bool is_window_configured () const
Function to check if the embedded window of this kernel has been configured.
Static Public Member Functions
static Status validate (const ITensorInfo *input, const ITensorInfo *weights, const ITensorInfo *biases, const ITensorInfo *output, const DWCComputeKernelInfo &dwc_info, const ConvolutionInfo &conv_info, const ITensorInfo *output_multipliers=nullptr, const ITensorInfo *output_shifts=nullptr)
Static function to check if given info will lead to a valid configuration of CLDepthwiseConvolutionLayerNativeKernel.
Static Public Member Functions inherited from ICLKernel
constexpr static unsigned int num_arguments_per_3d_tensor_nhw ()
Returns the number of arguments enqueued per NHW 3D Tensor object.
constexpr static unsigned int num_arguments_per_4d_tensor_nhwc ()
Returns the number of arguments enqueued per NHWC 4D Tensor object.
constexpr static unsigned int num_arguments_per_1D_array ()
Returns the number of arguments enqueued per 1D array object.
constexpr static unsigned int num_arguments_per_1D_tensor ()
Returns the number of arguments enqueued per 1D tensor object.
constexpr static unsigned int num_arguments_per_2D_tensor ()
Returns the number of arguments enqueued per 2D tensor object.
constexpr static unsigned int num_arguments_per_3D_tensor ()
Returns the number of arguments enqueued per 3D tensor object.
constexpr static unsigned int num_arguments_per_4D_tensor ()
Returns the number of arguments enqueued per 4D tensor object.
static cl::NDRange gws_from_window (const Window &window, bool use_dummy_work_items)
Get the global work size given an execution window.
Detailed Description
Interface for the kernel to run a MxN depthwise convolution.
M and N are respectively the rows and columns of the filter This kernel assumes that tensor for the weights is NOT reshaped (Native version)
Definition at line 38 of file CLDepthwiseConvolutionLayerNativeKernel.h.
Constructor & Destructor Documentation
CLDepthwiseConvolutionLayerNativeKernel() [1/3]
CLDepthwiseConvolutionLayerNativeKernel ()
Default Constructor.
Definition at line 178 of file CLDepthwiseConvolutionLayerNativeKernel.cpp.
     : _input(nullptr),
       _weights(nullptr),
       _biases(nullptr),
       _output(nullptr),
       _depth_multiplier(1),
       _output_multipliers(nullptr),
       _output_shifts(nullptr),
       _export_input_to_cl_image(false),
       _export_weights_to_cl_image(false),
       _is_quantized(false)
 {
     _type = CLKernelType::DEPTHWISE;
 }
References arm_compute::DEPTHWISE.
CLDepthwiseConvolutionLayerNativeKernel() [2/3]
CLDepthwiseConvolutionLayerNativeKernel (const CLDepthwiseConvolutionLayerNativeKernel &) delete
Prevent instances of this class from being copied (As this class contains pointers)
CLDepthwiseConvolutionLayerNativeKernel() [3/3]
CLDepthwiseConvolutionLayerNativeKernel (CLDepthwiseConvolutionLayerNativeKernel &&) default
Allow instances of this class to be moved.
Member Function Documentation
configure() [1/2]
void configure (const CLCompileContext & compile_context, ICLTensor * input, const ICLTensor * weights, const ICLTensor * biases, ICLTensor * output, const DWCComputeKernelInfo & dwc_info, const ConvolutionInfo & conv_info, const ICLTensor * output_multipliers = nullptr, const ICLTensor * output_shifts = nullptr)
Initialize the function's source, destination and parameters.
Parameters
[in] compile_context The compile context to be used.
[in] input Source tensor. Data type supported: QASYMM8/QASYMM8_SIGNED/FP32/FP16. Data layout supported: NHWC
[in] weights Weights tensor. A 3D tensor with dimensions [IFM, N, M]. Data type supported: Same as input or QASYMM8/QASYMM8_SIGNED/QSYMM8_PER_CHANNEL when input is QASYMM8.
[in] biases Biases tensor. A 1D tensor with dimensions [IFM]. Must be nullptr if not needed. Data type supported: Same as input, S32 when input is QASYMM8/QASYMM8_SIGNED.
[out] output Destination tensor. Pass in nullptr or input for in-place operation. Data type supported: Same as input.
[in] dwc_info Depthwise convolution layer info
[in] conv_info Convolution info (padding, stride, dilation, ...)
[in] output_multipliers (Optional) Output multipliers tensor for quantized computations. In case of per-channel quantization, the number of multipliers must be equal to the number of filters (IFM). Supported data types: S32
[in] output_shifts (Optional) Output shifts tensor for quantized computations. In case of per-channel quantization, the number of multipliers must be equal to the number of filters (IFM). Supported data types: S32
Note
: In-place is only supported when
data layout: NHWC
filter: 1x1
depth_multiplier: 1
strides: 1
dilation: 1
no padding
no change of data layout after configure
Definition at line 206 of file CLDepthwiseConvolutionLayerNativeKernel.cpp.
 {
     ARM_COMPUTE_ERROR_ON_NULLPTR(input, weights);
     if (output == nullptr)
     {
         // In-place
         output = input;
     }
     ARM_COMPUTE_ERROR_THROW_ON(validate_arguments(
         input->info(), weights->info(), (biases != nullptr) ? biases->info() : nullptr, output->info(), dwc_info,
         conv_info, (output_multipliers != nullptr) ? output_multipliers->info() : nullptr,
         (output_shifts != nullptr) ? output_shifts->info() : nullptr));
     auto padding_info = get_padding_info({input, output});
     const TensorShape output_shape = arm_compute::misc::shape_calculator::compute_depthwise_convolution_shape(
         *(input->info()), *(weights->info()), conv_info);
     auto_init_if_empty(*(output->info()), input->info()
                                               ->clone()
                                               ->set_tensor_shape(output_shape)
                                               .set_quantization_info(output->info()->quantization_info()));
     _input                      = input;
     _output                     = output;
     _weights                    = weights;
     _biases                     = biases;
     _depth_multiplier           = conv_info.depth_multiplier;
     _output_multipliers         = output_multipliers;
     _output_shifts              = output_shifts;
     _export_input_to_cl_image   = dwc_info.export_input_to_cl_image;
     _export_weights_to_cl_image = dwc_info.export_weights_to_cl_image;
     _is_quantized               = is_data_type_quantized(input->info()->data_type());
     const unsigned int n0          = adjust_vec_size(dwc_info.n0, output->info()->dimension(0));
     const unsigned int m0          = std::min(dwc_info.m0, (unsigned int)output->info()->dimension(1));
     std::string        kernel_name = "";
     CLBuildOptions build_opts;
     // Update the padding for the input/weights tensor if we can export to cl_image
     if (_export_input_to_cl_image)
     {
         arm_compute::opencl::kernels::gemm::update_padding_for_cl_image(input->info());
     }
     if (_export_weights_to_cl_image)
     {
         arm_compute::opencl::kernels::gemm::update_padding_for_cl_image(weights->info());
     }
     // Conditions of -cl-fast-relaxed-math causing accuracy issues can be traced from COMPMID-5324
     const GPUTarget gpu_target    = get_target();
     const auto      act_function  = conv_info.act_info.activation();
     const auto      dst_data_type = _output->info()->data_type();
     if ((gpu_target != GPUTarget::G71 && (gpu_target & GPUTarget::GPU_ARCH_MASK) == GPUTarget::BIFROST) &&
         (act_function == ActivationLayerInfo::ActivationFunction::BOUNDED_RELU ||
          act_function == ActivationLayerInfo::ActivationFunction::LU_BOUNDED_RELU) &&
         (dst_data_type == DataType::F32 || dst_data_type == DataType::F16))
     {
         // -cl-fast-relaxed-math also sets -cl-finite-math-only and -cl-unsafe-math-optimizations
         // to disable -cl-finite-math-only, we only include -cl-unsafe-math-optimizations
         build_opts.add_option("-cl-unsafe-math-optimizations");
     }
     else
     {
         build_opts.add_option("-cl-fast-relaxed-math");
     }
     build_opts.add_option("-DACTIVATION_TYPE=" + lower_string(string_from_activation_func(act_function)));
     build_opts.add_option("-DDEPTH_MULTIPLIER=" + support::cpp11::to_string(conv_info.depth_multiplier));
     build_opts.add_option_if_else(_export_input_to_cl_image, "-DSRC_TENSOR_TYPE=IMAGE", "-DSRC_TENSOR_TYPE=BUFFER");
     // Note: SRC_DATA_TYPE must have the same data type of WEI_DATA_TYPE. In quantized, we could
     // have a case where the data types for the activation and weights are different. However, since the implementation
     // only works when both have same data type, we have to change the offset to take into account this aspect
     build_opts.add_option("-DSRC_DATA_TYPE=" + get_cl_type_from_data_type(_input->info()->data_type()));
     build_opts.add_option("-DDST_TENSOR_TYPE=BUFFER");
     build_opts.add_option("-DDST_DATA_TYPE=" + get_cl_type_from_data_type(dst_data_type));
     build_opts.add_option_if_else(_export_weights_to_cl_image, "-DWEI_TENSOR_TYPE=IMAGE", "-DWEI_TENSOR_TYPE=BUFFER");
     build_opts.add_option("-DSRC_WIDTH=" + support::cpp11::to_string(_input->info()->dimension(1)));
     build_opts.add_option("-DSRC_HEIGHT=" + support::cpp11::to_string(_input->info()->dimension(2)));
     build_opts.add_option("-DDST_WIDTH=" + support::cpp11::to_string(_output->info()->dimension(1)));
     build_opts.add_option("-DDST_HEIGHT=" + support::cpp11::to_string(_output->info()->dimension(2)));
     build_opts.add_option("-DWEI_WIDTH=" + support::cpp11::to_string(_weights->info()->dimension(1)));
     build_opts.add_option("-DWEI_HEIGHT=" + support::cpp11::to_string(_weights->info()->dimension(2)));
     build_opts.add_option("-DWEI_DATA_TYPE=" + get_cl_type_from_data_type(_weights->info()->data_type()));
     build_opts.add_option("-DPAD_TOP=" + support::cpp11::to_string(conv_info.pad_stride_info.pad_top()));
     build_opts.add_option("-DPAD_LEFT=" + support::cpp11::to_string(conv_info.pad_stride_info.pad_left()));
     build_opts.add_option("-DSTRIDE_X=" + support::cpp11::to_string(conv_info.pad_stride_info.stride().first));
     build_opts.add_option("-DSTRIDE_Y=" + support::cpp11::to_string(conv_info.pad_stride_info.stride().second));
     build_opts.add_option("-DDILATION_X=" + support::cpp11::to_string(conv_info.dilation.x()));
     build_opts.add_option("-DDILATION_Y=" + support::cpp11::to_string(conv_info.dilation.y()));
     build_opts.add_option("-DN0=" + support::cpp11::to_string(n0));
     build_opts.add_option("-DM0=" + support::cpp11::to_string(m0));
     build_opts.add_option("-DM0_A=" + support::cpp11::to_string(_weights->info()->dimension(1) + m0 - 1));
     build_opts.add_option_if_else(conv_info.depth_multiplier > 1, "-DN0_A=1",
                                   "-DN0_A=" + support::cpp11::to_string(n0));
     build_opts.add_option("-DPARTIAL_N0=" + support::cpp11::to_string(_output->info()->dimension(0) % n0));
     build_opts.add_option_if(_input->info()->num_dimensions() > 3, "-DBATCHED_EXECUTION");
     // Force unroll with pragma when any of the following values exceed the maximum number of manual unroll
     set_unroll_with_pragma(build_opts, {static_cast<int>(_weights->info()->dimension(1) + m0 - 1),
                                         static_cast<int>(_weights->info()->dimension(1)),
                                         static_cast<int>(_weights->info()->dimension(2))});
     if (biases != nullptr)
     {
         build_opts.add_option(std::string("-DHAS_BIAS"));
         build_opts.add_option(
             std::string("-DBIA_DATA_TYPE=" + get_cl_type_from_data_type(biases->info()->data_type())));
     }
     if (_is_quantized)
     {
         kernel_name                          = "dwc_native_quantized_nhwc";
         const UniformQuantizationInfo iqinfo = input->info()->quantization_info().uniform();
         const UniformQuantizationInfo wqinfo = weights->info()->quantization_info().uniform();
         const UniformQuantizationInfo oqinfo = output->info()->quantization_info().uniform();
         PixelValue zero_value = PixelValue(0, input->info()->data_type(), input->info()->quantization_info());
         int        zero_value_s32;
         zero_value.get(zero_value_s32);
         float multiplier        = iqinfo.scale * wqinfo.scale / oqinfo.scale;
         int   output_multiplier = 0;
         int   output_shift      = 0;
         quantization::calculate_quantized_multiplier(multiplier, &output_multiplier, &output_shift);
         build_opts.add_option("-DDST_MULTIPLIER=" + support::cpp11::to_string(output_multiplier));
         build_opts.add_option("-DDST_SHIFT=" + support::cpp11::to_string(output_shift));
         build_opts.add_option("-DSRC_OFFSET=" + support::cpp11::to_string(-iqinfo.offset));
         build_opts.add_option("-DWEI_OFFSET=" + support::cpp11::to_string(-wqinfo.offset));
         build_opts.add_option("-DDST_OFFSET=" + support::cpp11::to_string(oqinfo.offset));
         build_opts.add_option("-DZERO_VALUE=" + support::cpp11::to_string(zero_value_s32));
         build_opts.add_option("-DACC_DATA_TYPE=" + get_cl_type_from_data_type(DataType::S32));
         build_opts.add_option("-DDST_MULTIPLIERS_DATA_TYPE=" +
                               get_cl_type_from_data_type(_output_multipliers->info()->data_type()));
         build_opts.add_option("-DDST_SHIFTS_DATA_TYPE=" +
                               get_cl_type_from_data_type(_output_shifts->info()->data_type()));
         build_opts.add_option_if_else(weights->info()->data_type() == DataType::QSYMM8_PER_CHANNEL,
                                       "-DQUANTIZATION_TYPE=PER_CHANNEL", "-DQUANTIZATION_TYPE=PER_TENSOR");
         // Note: We expect the input and output tensors to always adopt a per-tensor quantization approach
         int a_val{};
         int b_val{};
         std::tie(b_val, a_val) =
             get_quantized_activation_min_max(conv_info.act_info, input->info()->data_type(), oqinfo);
         build_opts.add_option_if(conv_info.act_info.enabled(), "-DA_VAL=" + support::cpp11::to_string(a_val));
         build_opts.add_option_if(conv_info.act_info.enabled(), "-DB_VAL=" + support::cpp11::to_string(b_val));
     }
     else
     {
         kernel_name = "dwc_native_fp_nhwc";
         build_opts.add_option("-DACC_DATA_TYPE=" + get_cl_type_from_data_type(input->info()->data_type()));
         build_opts.add_option_if(conv_info.act_info.enabled(),
                                  "-DA_VAL=" + float_to_string_with_full_precision(conv_info.act_info.a()));
         build_opts.add_option_if(conv_info.act_info.enabled(),
                                  "-DB_VAL=" + float_to_string_with_full_precision(conv_info.act_info.b()));
     }
     Window win = calculate_max_window(*(output->info()), Steps(n0, m0));
     ICLKernel::configure_internal(win);
     _kernel = create_kernel(compile_context, kernel_name, build_opts.options());
     ARM_COMPUTE_ERROR_ON(has_padding_changed(padding_info));
     // Set config_id for enabling LWS tuning
     _config_id = kernel_name;
     _config_id += "_";
     _config_id += support::cpp11::to_string(input->info()->dimension(0));
     _config_id += "_";
     _config_id += support::cpp11::to_string(input->info()->dimension(1));
     _config_id += "_";
     _config_id += support::cpp11::to_string(input->info()->dimension(2));
     _config_id += "_";
     _config_id += support::cpp11::to_string(output->info()->dimension(0));
     _config_id += "_";
     _config_id += support::cpp11::to_string(output->info()->dimension(1));
     _config_id += "_";
     _config_id += support::cpp11::to_string(output->info()->dimension(2));
     _config_id += "_";
     _config_id += string_from_data_type(input->info()->data_type());
 }
References CLBuildOptions::add_option(), CLBuildOptions::add_option_if(), CLBuildOptions::add_option_if_else(), arm_compute::adjust_vec_size(), ARM_COMPUTE_ERROR_ON, ARM_COMPUTE_ERROR_ON_NULLPTR, ARM_COMPUTE_ERROR_THROW_ON, arm_compute::auto_init_if_empty(), arm_compute::BIFROST, arm_compute::calculate_max_window(), arm_compute::quantization::calculate_quantized_multiplier(), arm_compute::misc::shape_calculator::compute_depthwise_convolution_shape(), arm_compute::test::validation::conv_info, arm_compute::create_kernel(), ITensorInfo::data_type(), ITensorInfo::dimension(), DWCComputeKernelInfo::export_input_to_cl_image, DWCComputeKernelInfo::export_weights_to_cl_image, arm_compute::F16, arm_compute::F32, arm_compute::float_to_string_with_full_precision(), arm_compute::G71, PixelValue::get(), arm_compute::get_cl_type_from_data_type(), arm_compute::get_padding_info(), arm_compute::get_quantized_activation_min_max(), ICLKernel::get_target(), arm_compute::GPU_ARCH_MASK, arm_compute::has_padding_changed(), ITensor::info(), arm_compute::test::validation::input, arm_compute::is_data_type_quantized(), kernel_name, arm_compute::lower_string(), DWCComputeKernelInfo::m0, DWCComputeKernelInfo::n0, ITensorInfo::num_dimensions(), UniformQuantizationInfo::offset, CLBuildOptions::options(), arm_compute::test::validation::output_shape, arm_compute::QSYMM8_PER_CHANNEL, ITensorInfo::quantization_info(), arm_compute::S32, UniformQuantizationInfo::scale, arm_compute::set_unroll_with_pragma(), arm_compute::string_from_activation_func(), arm_compute::string_from_data_type(), arm_compute::support::cpp11::to_string(), QuantizationInfo::uniform(), arm_compute::opencl::kernels::gemm::update_padding_for_cl_image(), and arm_compute::cpu::kernels::validate_arguments().
Referenced by CLDepthwiseConvolutionLayerNativeKernel::configure().
configure() [2/2]
void configure (ICLTensor * input, const ICLTensor * weights, const ICLTensor * biases, ICLTensor * output, const DWCComputeKernelInfo & dwc_info, const ConvolutionInfo & conv_info, const ICLTensor * output_multipliers = nullptr, const ICLTensor * output_shifts = nullptr)
Static function to check if given info will lead to a valid configuration of CLDepthwiseConvolutionLayerNativeKernel.
Similar to CLDepthwiseConvolutionLayerNativeKernel::configure()
Definition at line 193 of file CLDepthwiseConvolutionLayerNativeKernel.cpp.
 {
     configure(CLKernelLibrary::get().get_compile_context(), input, weights, biases, output, dwc_info, conv_info,
               output_multipliers, output_shifts);
 }
References CLDepthwiseConvolutionLayerNativeKernel::configure(), arm_compute::test::validation::conv_info, CLKernelLibrary::get(), and arm_compute::test::validation::input.
operator=() [1/2]
CLDepthwiseConvolutionLayerNativeKernel& operator= (CLDepthwiseConvolutionLayerNativeKernel &&) default
Allow instances of this class to be moved.
operator=() [2/2]
CLDepthwiseConvolutionLayerNativeKernel& operator= (const CLDepthwiseConvolutionLayerNativeKernel &) delete
Prevent instances of this class from being copied (As this class contains pointers)
run()
void run (const Window & window, cl::CommandQueue & queue) override virtual
Enqueue the OpenCL kernel to process the given window on the passed OpenCL command queue.
Note
The queue is not flushed by this method, and therefore the kernel will not have been executed by the time this method returns.
Parameters
[in] window Region on which to execute the kernel. (Must be a valid region of the window returned by window()).
[in,out] queue Command queue on which to enqueue the kernel.
Reimplemented from ICLKernel.
Definition at line 412 of file CLDepthwiseConvolutionLayerNativeKernel.cpp.
 {
     ARM_COMPUTE_ERROR_ON_UNCONFIGURED_KERNEL(this);
     ARM_COMPUTE_ERROR_ON_INVALID_SUBWINDOW(IKernel::window(), window);
     // Collapse window
     Window window_collapsed = window.collapse(ICLKernel::window(), Window::DimZ);
     Window slice = window_collapsed.first_slice_window_4D();
     cl::Image2D input_cl_image;
     cl::Image2D weights_cl_image;
     if (_export_input_to_cl_image || _export_weights_to_cl_image)
     {
         // Export cl_buffer to cl_image
         if (_export_input_to_cl_image)
         {
             const size_t image_w = _input->info()->dimension(0) / 4;
             const size_t image_h =
                 _input->info()->dimension(1) * _input->info()->dimension(2) * _input->info()->dimension(3);
             const TensorShape shape2d(image_w, image_h);
             const size_t      image_row_pitch = _input->info()->strides_in_bytes()[1];
             input_cl_image =
                 create_image2d_from_buffer(CLKernelLibrary::get().context(), _input->cl_buffer(), shape2d,
                                            _input->info()->data_type(), image_row_pitch, CLImage2DType::ReadOnly);
         }
         if (_export_weights_to_cl_image)
         {
             const size_t image_w = _weights->info()->dimension(0) / 4;
             const size_t image_h =
                 _weights->info()->dimension(1) * _weights->info()->dimension(2) * _weights->info()->dimension(3);
             const TensorShape shape2d(image_w, image_h);
             const size_t      image_row_pitch = _weights->info()->strides_in_bytes()[1];
             weights_cl_image =
                 create_image2d_from_buffer(CLKernelLibrary::get().context(), _weights->cl_buffer(), shape2d,
                                            _weights->info()->data_type(), image_row_pitch, CLImage2DType::ReadOnly);
         }
     }
     unsigned int idx = 0;
     if (_export_input_to_cl_image)
     {
         _kernel.setArg(idx++, input_cl_image);
     }
     add_4d_tensor_nhwc_argument(idx, _input);
     add_4d_tensor_nhwc_argument(idx, _output);
     if (_export_weights_to_cl_image)
     {
         _kernel.setArg(idx++, weights_cl_image);
     }
     add_4d_tensor_nhwc_argument(idx, _weights);
     if (_is_quantized)
     {
         add_1D_tensor_argument(idx, _output_multipliers, slice);
         add_1D_tensor_argument(idx, _output_shifts, slice);
     }
     if (_biases != nullptr)
     {
         add_1D_tensor_argument(idx, _biases, slice);
     }
     enqueue(queue, *this, slice, lws_hint());
 }
References ICLKernel::add_1D_tensor_argument(), ICLKernel::add_4d_tensor_nhwc_argument(), ARM_COMPUTE_ERROR_ON_INVALID_SUBWINDOW, ARM_COMPUTE_ERROR_ON_UNCONFIGURED_KERNEL, ICLTensor::cl_buffer(), Window::collapse(), arm_compute::test::validation::context, arm_compute::create_image2d_from_buffer(), ITensorInfo::data_type(), ITensorInfo::dimension(), Window::DimZ, arm_compute::enqueue(), Window::first_slice_window_4D(), CLKernelLibrary::get(), ITensor::info(), ICLKernel::lws_hint(), arm_compute::ReadOnly, arm_compute::test::validation::reference::slice(), ITensorInfo::strides_in_bytes(), and IKernel::window().
validate()
Status validate (const ITensorInfo * input, const ITensorInfo * weights, const ITensorInfo * biases, const ITensorInfo * output, const DWCComputeKernelInfo & dwc_info, const ConvolutionInfo & conv_info, const ITensorInfo * output_multipliers = nullptr, const ITensorInfo * output_shifts = nullptr) static
Static function to check if given info will lead to a valid configuration of CLDepthwiseConvolutionLayerNativeKernel.
Similar to CLDepthwiseConvolutionLayerNativeKernel::configure()
Returns
a status
Definition at line 398 of file CLDepthwiseConvolutionLayerNativeKernel.cpp.
 {
     ARM_COMPUTE_RETURN_ON_ERROR(
         validate_arguments(input, weights, biases, output, dwc_info, conv_info, output_multipliers, output_shifts));
     return Status{};
 }
References ARM_COMPUTE_RETURN_ON_ERROR, arm_compute::test::validation::conv_info, arm_compute::test::validation::input, and arm_compute::cpu::kernels::validate_arguments().
Referenced by CLDepthwiseConvolutionLayer::validate().
The documentation for this class was generated from the following files:
src/core/CL/kernels/CLDepthwiseConvolutionLayerNativeKernel.h
src/core/CL/kernels/CLDepthwiseConvolutionLayerNativeKernel.cpp