Compute Library: ITensorV2 Class Reference
ITensorV2 Class Reference abstract
Base class specifying the tensor interface.
#include <ITensorV2.h>
Public Member Functions
ITensorV2 (IContext *ctx)
Explict Operator Constructor.
virtual ~ITensorV2 ()
Destructor.
bool is_valid () const
Checks if a queue is valid.
virtual void * map ()=0
Map tensor to a host pointer.
virtual StatusCode unmap ()=0
Unmap tensor.
virtual StatusCode import (void *handle, ImportMemoryType type)=0
Import external memory handle.
virtual arm_compute::ITensor * tensor () const =0
Get the legacy tensor object.
size_t get_size () const
Get the size of the tensor in byte.
AclTensorDescriptor get_descriptor () const
Get the descriptor of this tensor.
Additional Inherited Members
Data Fields inherited from AclTensor_
arm_compute::detail::Header header {arm_compute::detail::ObjectType::Tensor, nullptr}
Detailed Description
Base class specifying the tensor interface.
Definition at line 45 of file ITensorV2.h.
Constructor & Destructor Documentation
ITensorV2()
ITensorV2 (IContext * ctx) inline explicit
Explict Operator Constructor.
Parameters
[in] ctx Context to be used by the operator
Definition at line 52 of file ITensorV2.h.
                                       : AclTensor_()
     {
         ARM_COMPUTE_ASSERT_NOT_NULLPTR(ctx);
         this->header.ctx = ctx;
         this->header.ctx->inc_ref();
     }
References ARM_COMPUTE_ASSERT_NOT_NULLPTR, Header::ctx, AclTensor_::header, and IContext::inc_ref().
~ITensorV2()
virtual ~ITensorV2 () inline virtual
Destructor.
Definition at line 59 of file ITensorV2.h.
     {
         this->header.ctx->dec_ref();
         this->header.type = detail::ObjectType::Invalid;
     };
References Header::ctx, IContext::dec_ref(), AclTensor_::header, arm_compute::detail::Invalid, and Header::type.
Member Function Documentation
get_descriptor()
AclTensorDescriptor get_descriptor () const
Get the descriptor of this tensor.
Returns
The descriptor describing the characteristics of this tensor
Definition at line 37 of file ITensorV2.cpp.
 {
     return detail::convert_to_descriptor(*tensor()->info());
 }
References arm_compute::detail::convert_to_descriptor(), arm_compute::test::validation::info, and ITensorV2::tensor().
get_size()
size_t get_size () const
Get the size of the tensor in byte.
Note
The size isn't based on allocated memory, but based on information in its descriptor (dimensions, data type, etc.).
Returns
The size of the tensor in byte
Definition at line 32 of file ITensorV2.cpp.
 {
     return tensor()->info()->total_size();
 }
References ITensor::info(), ITensorV2::tensor(), and ITensorInfo::total_size().
import()
virtual StatusCode import (void * handle, ImportMemoryType type) pure virtual
Import external memory handle.
Parameters
[in] handle Memory to import
[in] type Type of imported memory
Returns
Status code
Implemented in ClTensor, and CpuTensor.
is_valid()
bool is_valid () const inline
Checks if a queue is valid.
Returns
True if successful otherwise false
Definition at line 68 of file ITensorV2.h.
     {
         return this->header.type == detail::ObjectType::Tensor;
     };
References AclTensor_::header, arm_compute::detail::Tensor, and Header::type.
map()
virtual void* map () pure virtual
Map tensor to a host pointer.
Returns
A pointer to the underlying backing memory if successful else nullptr
Implemented in ClTensor, and CpuTensor.
tensor()
virtual arm_compute::ITensor* tensor () const pure virtual
Get the legacy tensor object.
Returns
The legacy underlying tensor object
Implemented in ClTensor, and CpuTensor.
Referenced by ITensorV2::get_descriptor(), and ITensorV2::get_size().
unmap()
virtual StatusCode unmap () pure virtual
Unmap tensor.
Returns
AclStatus A status cod
Implemented in ClTensor, and CpuTensor.
The documentation for this class was generated from the following files:
src/common/ITensorV2.h
src/common/ITensorV2.cpp