Compute Library: CPPDetectionPostProcessLayer Class Reference
CPPDetectionPostProcessLayer Class Reference
CPP Function to generate the detection output based on center size encoded boxes, class prediction and anchors by doing non maximum suppression.
#include <CPPDetectionPostProcessLayer.h>
Public Member Functions
CPPDetectionPostProcessLayer (std::shared_ptr< IMemoryManager > memory_manager=nullptr)
Constructor.
CPPDetectionPostProcessLayer (const CPPDetectionPostProcessLayer &)=delete
Prevent instances of this class from being copied (As this class contains pointers)
CPPDetectionPostProcessLayer & operator= (const CPPDetectionPostProcessLayer &)=delete
Prevent instances of this class from being copied (As this class contains pointers)
void configure (const ITensor *input_box_encoding, const ITensor *input_score, const ITensor *input_anchors, ITensor *output_boxes, ITensor *output_classes, ITensor *output_scores, ITensor *num_detection, DetectionPostProcessLayerInfo info=DetectionPostProcessLayerInfo())
Configure the detection output layer CPP function.
void run () override
Run the kernels contained in the function.
Public Member Functions inherited from IFunction
virtual ~IFunction ()=default
Destructor.
virtual void prepare ()
Prepare the function for executing.
Static Public Member Functions
static Status validate (const ITensorInfo *input_box_encoding, const ITensorInfo *input_class_score, const ITensorInfo *input_anchors, ITensorInfo *output_boxes, ITensorInfo *output_classes, ITensorInfo *output_scores, ITensorInfo *num_detection, DetectionPostProcessLayerInfo info=DetectionPostProcessLayerInfo())
Static function to check if given info will lead to a valid configuration of CPPDetectionPostProcessLayer.
Detailed Description
CPP Function to generate the detection output based on center size encoded boxes, class prediction and anchors by doing non maximum suppression.
Note
Intended for use with MultiBox detection method.
Definition at line 45 of file CPPDetectionPostProcessLayer.h.
Constructor & Destructor Documentation
CPPDetectionPostProcessLayer() [1/2]
CPPDetectionPostProcessLayer (std::shared_ptr< IMemoryManager > memory_manager = nullptr)
Constructor.
Definition at line 263 of file CPPDetectionPostProcessLayer.cpp.
     : _memory_group(std::move(memory_manager)),
       _nms(),
       _input_box_encoding(nullptr),
       _input_scores(nullptr),
       _input_anchors(nullptr),
       _output_boxes(nullptr),
       _output_classes(nullptr),
       _output_scores(nullptr),
       _num_detection(nullptr),
       _info(),
       _num_boxes(),
       _num_classes_with_background(),
       _num_max_detected_boxes(),
       _dequantize_scores(false),
       _decoded_boxes(),
       _decoded_scores(),
       _selected_indices(),
       _class_scores(),
       _input_scores_to_use(nullptr)
 {
 }
CPPDetectionPostProcessLayer() [2/2]
CPPDetectionPostProcessLayer (const CPPDetectionPostProcessLayer &) delete
Prevent instances of this class from being copied (As this class contains pointers)
Member Function Documentation
configure()
void configure (const ITensor * input_box_encoding, const ITensor * input_score, const ITensor * input_anchors, ITensor * output_boxes, ITensor * output_classes, ITensor * output_scores, ITensor * num_detection, DetectionPostProcessLayerInfo info = DetectionPostProcessLayerInfo())
Configure the detection output layer CPP function.
Parameters
[in] input_box_encoding The bounding box input tensor. Data types supported: F32/QASYMM8/QASYMM8_SIGNED.
[in] input_score The class prediction input tensor. Data types supported: Same as input_box_encoding.
[in] input_anchors The anchors input tensor. Data types supported: Same as input_box_encoding.
[out] output_boxes The boxes output tensor. Data types supported: F32.
[out] output_classes The classes output tensor. Data types supported: Same as output_boxes.
[out] output_scores The scores output tensor. Data types supported: Same as output_boxes.
[out] num_detection The number of output detection. Data types supported: Same as output_boxes.
[in] info (Optional) DetectionPostProcessLayerInfo information.
Note
Output contains all the detections. Of those, only the ones selected by the valid region are valid.
Definition at line 286 of file CPPDetectionPostProcessLayer.cpp.
 {
     ARM_COMPUTE_ERROR_ON_NULLPTR(input_box_encoding, input_scores, input_anchors, output_boxes, output_classes,
                                  output_scores);
     ARM_COMPUTE_LOG_PARAMS(input_box_encoding, input_scores, input_anchors, output_boxes, output_classes, output_scores,
                            num_detection, info);
     _num_max_detected_boxes = info.max_detections() * info.max_classes_per_detection();
     auto_init_if_empty(*output_boxes->info(),
                        TensorInfo(TensorShape(_kNumCoordBox, _num_max_detected_boxes, _kBatchSize), 1, DataType::F32));
     auto_init_if_empty(*output_classes->info(),
                        TensorInfo(TensorShape(_num_max_detected_boxes, _kBatchSize), 1, DataType::F32));
     auto_init_if_empty(*output_scores->info(),
                        TensorInfo(TensorShape(_num_max_detected_boxes, _kBatchSize), 1, DataType::F32));
     auto_init_if_empty(*num_detection->info(), TensorInfo(TensorShape(1U), 1, DataType::F32));
     // Perform validation step
     ARM_COMPUTE_ERROR_THROW_ON(validate_arguments(
         input_box_encoding->info(), input_scores->info(), input_anchors->info(), output_boxes->info(),
         output_classes->info(), output_scores->info(), num_detection->info(), info, _kBatchSize, _kNumCoordBox));
     _input_box_encoding          = input_box_encoding;
     _input_scores                = input_scores;
     _input_anchors               = input_anchors;
     _output_boxes                = output_boxes;
     _output_classes              = output_classes;
     _output_scores               = output_scores;
     _num_detection               = num_detection;
     _info                        = info;
     _num_boxes                   = input_box_encoding->info()->dimension(1);
     _num_classes_with_background = _input_scores->info()->dimension(0);
     _dequantize_scores = (info.dequantize_scores() && is_data_type_quantized(input_box_encoding->info()->data_type()));
     auto_init_if_empty(*_decoded_boxes.info(),
                        TensorInfo(TensorShape(_kNumCoordBox, _input_box_encoding->info()->dimension(1), _kBatchSize), 1,
                                   DataType::F32));
     auto_init_if_empty(
         *_decoded_scores.info(),
         TensorInfo(TensorShape(_input_scores->info()->dimension(0), _input_scores->info()->dimension(1), _kBatchSize),
                    1, DataType::F32));
     auto_init_if_empty(
         *_selected_indices.info(),
         TensorInfo(TensorShape(info.use_regular_nms() ? info.detection_per_class() : info.max_detections()), 1,
                    DataType::S32));
     const unsigned int num_classes_per_box = std::min(info.max_classes_per_detection(), info.num_classes());
     auto_init_if_empty(
         *_class_scores.info(),
         TensorInfo(info.use_regular_nms() ? TensorShape(_num_boxes) : TensorShape(_num_boxes * num_classes_per_box), 1,
                    DataType::F32));
     _input_scores_to_use = _dequantize_scores ? &_decoded_scores : _input_scores;
     // Manage intermediate buffers
     _memory_group.manage(&_decoded_boxes);
     _memory_group.manage(&_decoded_scores);
     _memory_group.manage(&_selected_indices);
     _memory_group.manage(&_class_scores);
     _nms.configure(&_decoded_boxes, &_class_scores, &_selected_indices,
                    info.use_regular_nms() ? info.detection_per_class() : info.max_detections(),
                    info.nms_score_threshold(), info.iou_threshold());
     // Allocate and reserve intermediate tensors and vectors
     _decoded_boxes.allocator()->allocate();
     _decoded_scores.allocator()->allocate();
     _selected_indices.allocator()->allocate();
     _class_scores.allocator()->allocate();
 }
References TensorAllocator::allocate(), Tensor::allocator(), ARM_COMPUTE_ERROR_ON_NULLPTR, ARM_COMPUTE_ERROR_THROW_ON, ARM_COMPUTE_LOG_PARAMS, arm_compute::auto_init_if_empty(), CPPNonMaximumSuppression::configure(), ITensorInfo::data_type(), ITensorInfo::dimension(), arm_compute::F32, ITensor::info(), Tensor::info(), arm_compute::test::validation::info, arm_compute::is_data_type_quantized(), MemoryGroup::manage(), arm_compute::S32, arm_compute::utils::cast::U, and arm_compute::cpu::kernels::validate_arguments().
Referenced by NEDetectionPostProcessLayer::configure().
operator=()
CPPDetectionPostProcessLayer& operator= (const CPPDetectionPostProcessLayer &) delete
Prevent instances of this class from being copied (As this class contains pointers)
run()
void run () override virtual
Run the kernels contained in the function.
For CPU kernels:
Multi-threading is used for the kernels which are parallelisable.
By default std::thread::hardware_concurrency() threads are used.
Note
CPPScheduler::set_num_threads() can be used to manually set the number of threads
For OpenCL kernels:
All the kernels are enqueued on the queue associated with CLScheduler.
The queue is then flushed.
Note
The function will not block until the kernels are executed. It is the user's responsibility to wait.
Will call prepare() on first run if hasn't been done
Implements IFunction.
Definition at line 388 of file CPPDetectionPostProcessLayer.cpp.
 {
     const unsigned int num_classes    = _info.num_classes();
     const unsigned int max_detections = _info.max_detections();
     DecodeCenterSizeBoxes(_input_box_encoding, _input_anchors, _info, &_decoded_boxes);
     // Decode scores if necessary
     if (_dequantize_scores)
     {
         if (_input_box_encoding->info()->data_type() == DataType::QASYMM8)
         {
             for (unsigned int idx_c = 0; idx_c < _num_classes_with_background; ++idx_c)
             {
                 for (unsigned int idx_b = 0; idx_b < _num_boxes; ++idx_b)
                 {
                     *(reinterpret_cast<float *>(_decoded_scores.ptr_to_element(Coordinates(idx_c, idx_b)))) =
                         dequantize_qasymm8(
                             *(reinterpret_cast<qasymm8_t *>(_input_scores->ptr_to_element(Coordinates(idx_c, idx_b)))),
                             _input_scores->info()->quantization_info());
                 }
             }
         }
         else if (_input_box_encoding->info()->data_type() == DataType::QASYMM8_SIGNED)
         {
             for (unsigned int idx_c = 0; idx_c < _num_classes_with_background; ++idx_c)
             {
                 for (unsigned int idx_b = 0; idx_b < _num_boxes; ++idx_b)
                 {
                     *(reinterpret_cast<float *>(_decoded_scores.ptr_to_element(Coordinates(idx_c, idx_b)))) =
                         dequantize_qasymm8_signed(*(reinterpret_cast<qasymm8_signed_t *>(
                                                       _input_scores->ptr_to_element(Coordinates(idx_c, idx_b)))),
                                                   _input_scores->info()->quantization_info());
                 }
             }
         }
     }
     // Regular NMS
     if (_info.use_regular_nms())
     {
         std::vector<int>          result_idx_boxes_after_nms;
         std::vector<int>          result_classes_after_nms;
         std::vector<float>        result_scores_after_nms;
         std::vector<unsigned int> sorted_indices;
         for (unsigned int c = 0; c < num_classes; ++c)
         {
             // For each boxes get scores of the boxes for the class c
             for (unsigned int i = 0; i < _num_boxes; ++i)
             {
                 *(reinterpret_cast<float *>(_class_scores.ptr_to_element(Coordinates(i)))) =
                     *(reinterpret_cast<float *>(_input_scores_to_use->ptr_to_element(
                         Coordinates(c + 1, i)))); // i * _num_classes_with_background + c + 1
             }
             // Run Non-maxima Suppression
             _nms.run();
             for (unsigned int i = 0; i < _info.detection_per_class(); ++i)
             {
                 const auto selected_index =
                     *(reinterpret_cast<int *>(_selected_indices.ptr_to_element(Coordinates(i))));
                 if (selected_index == -1)
                 {
                     // Nms will return -1 for all the last M-elements not valid
                     break;
                 }
                 result_idx_boxes_after_nms.emplace_back(selected_index);
                 result_scores_after_nms.emplace_back(
                     (reinterpret_cast<float *>(_class_scores.buffer()))[selected_index]);
                 result_classes_after_nms.emplace_back(c);
             }
         }
         // We select the max detection numbers of the highest score of all classes
         const auto num_selected = result_scores_after_nms.size();
         const auto num_output   = std::min<unsigned int>(max_detections, num_selected);
         // Sort selected indices based on result scores
         sorted_indices.resize(num_selected);
         std::iota(sorted_indices.begin(), sorted_indices.end(), 0);
         std::partial_sort(sorted_indices.data(), sorted_indices.data() + num_output,
                           sorted_indices.data() + num_selected,
                           [&](unsigned int first, unsigned int second)
                           { return result_scores_after_nms[first] > result_scores_after_nms[second]; });
         SaveOutputs(&_decoded_boxes, result_idx_boxes_after_nms, result_scores_after_nms, result_classes_after_nms,
                     sorted_indices, num_output, max_detections, _output_boxes, _output_classes, _output_scores,
                     _num_detection);
     }
     // Fast NMS
     else
     {
         const unsigned int num_classes_per_box =
             std::min<unsigned int>(_info.max_classes_per_detection(), _info.num_classes());
         std::vector<float> max_scores;
         std::vector<int>   box_indices;
         std::vector<int>   max_score_classes;
         for (unsigned int b = 0; b < _num_boxes; ++b)
         {
             std::vector<float> box_scores;
             for (unsigned int c = 0; c < num_classes; ++c)
             {
                 box_scores.emplace_back(
                     *(reinterpret_cast<float *>(_input_scores_to_use->ptr_to_element(Coordinates(c + 1, b)))));
             }
             std::vector<unsigned int> max_score_indices;
             max_score_indices.resize(_info.num_classes());
             std::iota(max_score_indices.data(), max_score_indices.data() + _info.num_classes(), 0);
             std::partial_sort(max_score_indices.data(), max_score_indices.data() + num_classes_per_box,
                               max_score_indices.data() + num_classes,
                               [&](unsigned int first, unsigned int second)
                               { return box_scores[first] > box_scores[second]; });
             for (unsigned int i = 0; i < num_classes_per_box; ++i)
             {
                 const float score_to_add = box_scores[max_score_indices[i]];
                 *(reinterpret_cast<float *>(_class_scores.ptr_to_element(Coordinates(b * num_classes_per_box + i)))) =
                     score_to_add;
                 max_scores.emplace_back(score_to_add);
                 box_indices.emplace_back(b);
                 max_score_classes.emplace_back(max_score_indices[i]);
             }
         }
         // Run Non-maxima Suppression
         _nms.run();
         std::vector<unsigned int> selected_indices;
         for (unsigned int i = 0; i < max_detections; ++i)
         {
             // NMS returns M valid indices, the not valid tail is filled with -1
             if (*(reinterpret_cast<int *>(_selected_indices.ptr_to_element(Coordinates(i)))) == -1)
             {
                 // Nms will return -1 for all the last M-elements not valid
                 break;
             }
             selected_indices.emplace_back(*(reinterpret_cast<int *>(_selected_indices.ptr_to_element(Coordinates(i)))));
         }
         // We select the max detection numbers of the highest score of all classes
         const auto num_output = std::min<unsigned int>(_info.max_detections(), selected_indices.size());
         SaveOutputs(&_decoded_boxes, box_indices, max_scores, max_score_classes, selected_indices, num_output,
                     max_detections, _output_boxes, _output_classes, _output_scores, _num_detection);
     }
 }
References arm_compute::test::validation::b, Tensor::buffer(), ITensorInfo::data_type(), arm_compute::dequantize_qasymm8(), arm_compute::dequantize_qasymm8_signed(), DetectionPostProcessLayerInfo::detection_per_class(), ITensor::info(), DetectionPostProcessLayerInfo::max_classes_per_detection(), DetectionPostProcessLayerInfo::max_detections(), DetectionPostProcessLayerInfo::num_classes(), ITensor::ptr_to_element(), arm_compute::QASYMM8, arm_compute::QASYMM8_SIGNED, ITensorInfo::quantization_info(), ICPPSimpleFunction::run(), and DetectionPostProcessLayerInfo::use_regular_nms().
Referenced by NEDetectionPostProcessLayer::run().
validate()
Status validate (const ITensorInfo * input_box_encoding, const ITensorInfo * input_class_score, const ITensorInfo * input_anchors, ITensorInfo * output_boxes, ITensorInfo * output_classes, ITensorInfo * output_scores, ITensorInfo * num_detection, DetectionPostProcessLayerInfo info = DetectionPostProcessLayerInfo()) static
Static function to check if given info will lead to a valid configuration of CPPDetectionPostProcessLayer.
Parameters
[in] input_box_encoding The bounding box input tensor info. Data types supported: F32/QASYMM8/QASYMM8_SIGNED.
[in] input_class_score The class prediction input tensor info. Data types supported: Same as input_box_encoding.
[in] input_anchors The anchors input tensor. Data types supported: F32, QASYMM8.
[out] output_boxes The output tensor. Data types supported: F32.
[out] output_classes The output tensor. Data types supported: Same as output_boxes.
[out] output_scores The output tensor. Data types supported: Same as output_boxes.
[out] num_detection The number of output detection. Data types supported: Same as output_boxes.
[in] info (Optional) DetectionPostProcessLayerInfo information.
Returns
a status
Definition at line 362 of file CPPDetectionPostProcessLayer.cpp.
 {
     constexpr unsigned int kBatchSize   = 1;
     constexpr unsigned int kNumCoordBox = 4;
     const TensorInfo       _decoded_boxes_info =
         TensorInfo(TensorShape(kNumCoordBox, input_box_encoding->dimension(1)), 1, DataType::F32);
     const TensorInfo _decoded_scores_info = TensorInfo(TensorShape(input_box_encoding->dimension(1)), 1, DataType::F32);
     const TensorInfo _selected_indices_info = TensorInfo(TensorShape(info.max_detections()), 1, DataType::S32);
     ARM_COMPUTE_RETURN_ON_ERROR(CPPNonMaximumSuppression::validate(&_decoded_boxes_info, &_decoded_scores_info,
                                                                    &_selected_indices_info, info.max_detections(),
                                                                    info.nms_score_threshold(), info.iou_threshold()));
     ARM_COMPUTE_RETURN_ON_ERROR(validate_arguments(input_box_encoding, input_class_score, input_anchors, output_boxes,
                                                    output_classes, output_scores, num_detection, info, kBatchSize,
                                                    kNumCoordBox));
     return Status{};
 }
References ARM_COMPUTE_RETURN_ON_ERROR, ITensorInfo::dimension(), arm_compute::F32, arm_compute::test::validation::info, arm_compute::S32, CPPNonMaximumSuppression::validate(), and arm_compute::cpu::kernels::validate_arguments().
Referenced by NEDetectionPostProcessLayer::validate().
The documentation for this class was generated from the following files:
arm_compute/runtime/CPP/functions/CPPDetectionPostProcessLayer.h
src/runtime/CPP/functions/CPPDetectionPostProcessLayer.cpp