Compute Library: NPYLoader Class Reference
NPYLoader Class Reference
Numpy data loader.
#include <Utils.h>
Public Member Functions
NPYLoader ()
Default constructor.
void open (const std::string &npy_filename, DataLayout file_layout=DataLayout::NCHW)
Open a NPY file and reads its metadata.
bool is_open ()
Return true if a NPY file is currently open.
bool is_fortran ()
Return true if a NPY file is in fortran order.
template<typename T >
void init_tensor (T &tensor, arm_compute::DataType dt)
Initialise the tensor's metadata with the dimensions of the NPY file currently open.
template<typename T >
void fill_tensor (T &tensor)
Fill a tensor with the content of the currently open NPY file.
Detailed Description
Numpy data loader.
Definition at line 285 of file Utils.h.
Constructor & Destructor Documentation
NPYLoader()
NPYLoader () inline
Default constructor.
Definition at line 289 of file Utils.h.
                 : _fs(), _shape(), _fortran_order(false), _typestring(), _file_layout(DataLayout::NCHW)
     {
     }
References arm_compute::NCHW.
Member Function Documentation
fill_tensor()
void fill_tensor (T & tensor) inline
Fill a tensor with the content of the currently open NPY file.
Note
If the tensor is a CLTensor, the function maps and unmaps the tensor
Parameters
[in,out] tensor Tensor to fill (Must be allocated, and of matching dimensions with the opened NPY).
Definition at line 365 of file Utils.h.
     {
         ARM_COMPUTE_ERROR_ON(!is_open());
         ARM_COMPUTE_ERROR_ON_DATA_TYPE_NOT_IN(&tensor, arm_compute::DataType::QASYMM8, arm_compute::DataType::S32,
                                               arm_compute::DataType::F32, arm_compute::DataType::F16);
         try
         {
             // Map buffer if creating a CLTensor
             map(tensor, true);
             // Check if the file is large enough to fill the tensor
             const size_t current_position = _fs.tellg();
             _fs.seekg(0, std::ios_base::end);
             const size_t end_position = _fs.tellg();
             _fs.seekg(current_position, std::ios_base::beg);
             ARM_COMPUTE_ERROR_ON_MSG((end_position - current_position) <
                                          tensor.info()->tensor_shape().total_size() * tensor.info()->element_size(),
                                      "Not enough data in file");
             ARM_COMPUTE_UNUSED(end_position);
             // Check if the typestring matches the given one
             std::string expect_typestr = get_typestring(tensor.info()->data_type());
             bool enable_f32_to_f16_conversion = false;
             if (_typestring != expect_typestr)
             {
                 const std::string f32_typestring = "<f4";
                 const std::string f16_typestring = "<f2";
                 // if typestring does not match, check whether _typestring is F32 and can be downcasted to expect_typestr
                 if (_typestring == f32_typestring && expect_typestr == f16_typestring)
                 {
                     enable_f32_to_f16_conversion = true;
                 }
                 else
                 {
                     ARM_COMPUTE_ERROR("Typestrings mismatch");
                 }
             }
             bool are_layouts_different = (_file_layout != tensor.info()->data_layout());
             // Correct dimensions (Needs to match TensorShape dimension corrections)
             if (_shape.size() != tensor.info()->tensor_shape().num_dimensions())
             {
                 for (int i = static_cast<int>(_shape.size()) - 1; i > 0; --i)
                 {
                     if (_shape[i] == 1)
                     {
                         _shape.pop_back();
                     }
                     else
                     {
                         break;
                     }
                 }
             }
             TensorShape                    permuted_shape = tensor.info()->tensor_shape();
             arm_compute::PermutationVector perm;
             if (are_layouts_different && tensor.info()->tensor_shape().num_dimensions() > 2)
             {
                 perm = (tensor.info()->data_layout() == arm_compute::DataLayout::NHWC)
                            ? arm_compute::PermutationVector(2U, 0U, 1U)
                            : arm_compute::PermutationVector(1U, 2U, 0U);
                 arm_compute::PermutationVector perm_vec =
                     (tensor.info()->data_layout() == arm_compute::DataLayout::NCHW)
                         ? arm_compute::PermutationVector(2U, 0U, 1U)
                         : arm_compute::PermutationVector(1U, 2U, 0U);
                 arm_compute::permute(permuted_shape, perm_vec);
             }
             // Validate tensor shape
             ARM_COMPUTE_ERROR_ON_MSG(_shape.size() != tensor.info()->tensor_shape().num_dimensions(),
                                      "Tensor ranks mismatch");
             for (size_t i = 0; i < _shape.size(); ++i)
             {
                 ARM_COMPUTE_ERROR_ON_MSG(permuted_shape[i] != _shape[i], "Tensor dimensions mismatch");
             }
             switch (tensor.info()->data_type())
             {
                 case arm_compute::DataType::QASYMM8:
                 case arm_compute::DataType::S32:
                 case arm_compute::DataType::F32:
                 case arm_compute::DataType::F16:
                 {
                     // Read data
                     if (!are_layouts_different && !_fortran_order && tensor.info()->padding().empty() &&
                         !enable_f32_to_f16_conversion)
                     {
                         // If tensor has no padding read directly from stream.
                         _fs.read(reinterpret_cast<char *>(tensor.buffer()), tensor.info()->total_size());
                     }
                     else
                     {
                         // If tensor has padding or is in fortran order accessing tensor elements through execution window.
                         Window             window;
                         const unsigned int num_dims = _shape.size();
                         if (_fortran_order)
{
                             for (unsigned int dim = 0; dim < num_dims; dim++)
{
                                 permuted_shape.set(dim, _shape[num_dims - dim - 1]);
                                 perm.set(dim, num_dims - dim - 1);
                             }
                             if (are_layouts_different)
{
                                 // Permute only if num_dimensions greater than 2
                                 if (num_dims > 2)
{
                                     if (_file_layout == DataLayout::NHWC) // i.e destination is NCHW --> permute(1,2,0)
{
                                         arm_compute::permute(perm, arm_compute::PermutationVector(1U, 2U, 0U));
                                     }
                                     else
{
                                         arm_compute::permute(perm, arm_compute::PermutationVector(2U, 0U, 1U));
                                     }
                                 }
                             }
                         }
                         window.use_tensor_dimensions(permuted_shape);
                         execute_window_loop(window,
                                             [&](const Coordinates &id)
{
                                                 Coordinates dst(id);
                                                 arm_compute::permute(dst, perm);
                                                 if (enable_f32_to_f16_conversion)
{
                                                     float f32_val = 0;
                                                     _fs.read(reinterpret_cast<char *>(&f32_val), 4u);
                                                     half f16_val =
                                                         half_float::half_cast<half, std::round_to_nearest>(f32_val);
                                                     *(reinterpret_cast<half *>(tensor.ptr_to_element(dst))) = f16_val;
                                                 }
                                                 else
{
                                                     _fs.read(reinterpret_cast<char *>(tensor.ptr_to_element(dst)),
                                                              tensor.info()->element_size());
                                                 }
                                             });
                     }
                     break;
                 }
                 default:
                     ARM_COMPUTE_ERROR("Unsupported data type");
             }
             // Unmap buffer if creating a CLTensor
             unmap(tensor);
         }
         catch (const std::ifstream::failure &e)
         {
             ARM_COMPUTE_ERROR_VAR("Loading NPY file: %s", e.what());
         }
     }
References ARM_COMPUTE_ERROR, ARM_COMPUTE_ERROR_ON, ARM_COMPUTE_ERROR_ON_DATA_TYPE_NOT_IN, ARM_COMPUTE_ERROR_ON_MSG, ARM_COMPUTE_ERROR_VAR, ARM_COMPUTE_UNUSED, arm_compute::test::validation::dst, arm_compute::mlgo::parser::end(), arm_compute::execute_window_loop(), arm_compute::F16, arm_compute::F32, arm_compute::utils::get_typestring(), NPYLoader::is_open(), arm_compute::utils::map(), arm_compute::NCHW, arm_compute::NHWC, arm_compute::permute(), arm_compute::QASYMM8, arm_compute::S32, Dimensions< T >::set(), TensorShape::set(), tensor, arm_compute::utils::cast::U, arm_compute::utils::unmap(), and Window::use_tensor_dimensions().
Referenced by NumPyBinLoader::access_tensor().
init_tensor()
void init_tensor (T & tensor, arm_compute::DataType dt) inline
Initialise the tensor's metadata with the dimensions of the NPY file currently open.
Parameters
[out] tensor Tensor to initialise
[in] dt Data type to use for the tensor
Definition at line 336 of file Utils.h.
     {
         ARM_COMPUTE_ERROR_ON(!is_open());
         ARM_COMPUTE_ERROR_ON(dt != arm_compute::DataType::F32);
         // Use the size of the input NPY tensor
         TensorShape shape;
         shape.set_num_dimensions(_shape.size());
         for (size_t i = 0; i < _shape.size(); ++i)
         {
             size_t src = i;
             if (_fortran_order)
             {
                 src = _shape.size() - 1 - i;
             }
             shape.set(i, _shape.at(src));
         }
         arm_compute::TensorInfo tensor_info(shape, 1, dt);
         tensor.allocator()->init(tensor_info);
     }
References ARM_COMPUTE_ERROR_ON, dt, arm_compute::F32, NPYLoader::is_open(), arm_compute::test::validation::shape, arm_compute::test::validation::src, tensor, and tensor_info.
is_fortran()
bool is_fortran () inline
Return true if a NPY file is in fortran order.
Definition at line 325 of file Utils.h.
     {
         return _fortran_order;
     }
is_open()
bool is_open () inline
Return true if a NPY file is currently open.
Definition at line 319 of file Utils.h.
     {
         return _fs.is_open();
     }
Referenced by NPYLoader::fill_tensor(), NPYLoader::init_tensor(), and NPYLoader::open().
open()
void open (const std::string & npy_filename, DataLayout file_layout = DataLayout::NCHW) inline
Open a NPY file and reads its metadata.
Parameters
[in] npy_filename File to open
[in] file_layout (Optional) Layout in which the weights are stored in the file.
Definition at line 298 of file Utils.h.
     {
         ARM_COMPUTE_ERROR_ON(is_open());
         try
         {
             _fs.open(npy_filename, std::ios::in | std::ios::binary);
             ARM_COMPUTE_EXIT_ON_MSG_VAR(!_fs.good(), "Failed to load binary data from %s", npy_filename.c_str());
             _fs.exceptions(std::ifstream::failbit | std::ifstream::badbit);
             _file_layout = file_layout;
             npy::header_t header = parse_npy_header(_fs);
             _shape               = header.shape;
             _fortran_order       = header.fortran_order;
             _typestring          = header.dtype.str();
         }
         catch (const std::ifstream::failure &e)
         {
             ARM_COMPUTE_ERROR_VAR("Accessing %s: %s", npy_filename.c_str(), e.what());
         }
     }
References ARM_COMPUTE_ERROR_ON, ARM_COMPUTE_ERROR_VAR, ARM_COMPUTE_EXIT_ON_MSG_VAR, arm_compute::mlgo::parser::header(), NPYLoader::is_open(), and arm_compute::utils::parse_npy_header().
Referenced by NumPyBinLoader::access_tensor().
The documentation for this class was generated from the following file:
utils/Utils.h