Compute Library: GpuPool2dSettings Class Reference
GpuPool2dSettings Class Reference
Operator backend specific settings.
#include <GpuPool2d.h>
Public Member Functions
bool use_inf_as_limit () const
GpuPool2dSettings use_inf_as_limit (bool use_inf_as_limit)
Detailed Description
Operator backend specific settings.
Definition at line 42 of file GpuPool2d.h.
Member Function Documentation
use_inf_as_limit() [1/2]
bool use_inf_as_limit () const
Definition at line 75 of file GpuPool2d.cpp.
 {
     return _use_inf_as_limit;
 }
Referenced by ClTemplatePool2d::get_tag_lut(), arm_compute::operator<<(), GpuPool2dSettings::use_inf_as_limit(), and GpuCkwPool2d::write_component_code().
use_inf_as_limit() [2/2]
GpuPool2dSettings use_inf_as_limit (bool use_inf_as_limit)
Definition at line 69 of file GpuPool2d.cpp.
 {
     _use_inf_as_limit = use_inf_as_limit;
     return *this;
 }
References GpuPool2dSettings::use_inf_as_limit().
The documentation for this class was generated from the following files:
arm_compute/dynamic_fusion/sketch/gpu/operators/GpuPool2d.h
src/dynamic_fusion/sketch/gpu/operators/GpuPool2d.cpp