Compute Library: IGemmCommon Class Reference
IGemmCommon Class Reference abstract
#include <gemm_common.hpp>
Public Member Functions
virtual void set_arrays_generic (const void *A, const int lda, const int A_batch_stride, const int A_multi_stride, const void *B, const int ldb, const int B_multi_stride, void *C, const int ldc, const int C_batch_stride, const int C_multi_stride, const void *bias, const int bias_multi_stride)=0
virtual ndrange_t get_window_size () const =0
virtual void set_nthreads (int)
virtual bool supports_dynamic_scheduling () const
virtual void execute (const ndcoord_t &work_range, const ndcoord_t &thread_locator, int threadid)=0
Main execute member fucntion.
virtual size_t get_working_size () const
virtual void set_working_space (void *)
virtual bool B_is_pretransposed () const
virtual bool B_pretranspose_required () const
virtual size_t get_B_pretransposed_array_size () const
virtual size_t get_B_pretranspose_window_size () const
virtual void pretranspose_B_array_generic (void *, const void *, const int, const int)=0
virtual void pretranspose_B_array_part_generic (void *, const void *, const int, const int, const size_t, const size_t)=0
virtual void set_pretransposed_B_data (void *)
virtual void set_quantized_bias (const int32_t *, size_t)
virtual void set_indirect_parameters_generic (size_t, const void *const *const *)
virtual void set_convolution_parameters (ConvolutionParameters)
virtual GemmConfig get_config ()=0
virtual ~IGemmCommon ()
Detailed Description
Definition at line 44 of file gemm_common.hpp.
Constructor & Destructor Documentation
~IGemmCommon()
virtual ~IGemmCommon () inline virtual
Definition at line 165 of file gemm_common.hpp.
     {
     }
Member Function Documentation
B_is_pretransposed()
virtual bool B_is_pretransposed () const inline virtual
Reimplemented in GemmInterleaved< strategy, To, Tr, OutputStage, MergeStep, FixedFormat, ForceThreadColumns, ForceFloatAccumulate >, GemmHybridIndirect< strategy, To, Tr, OutputStage, SeparateQuantize, FixedFormat >, GemmHybridQuantized< strategy, To, Tr >, GemmHybrid< strategy, To, Tr >, GemmHybridQuantizedInline< strategy, To, Tr >, GemvPretransposed< strategy, To, Tr, OutputStage >, QuantizeWrapper< To, Tr, Tgemm >, and GemvBatched< To, Tr >.
Definition at line 110 of file gemm_common.hpp.
     {
         return false;
     }
B_pretranspose_required()
virtual bool B_pretranspose_required () const inline virtual
Reimplemented in GemmInterleaved< strategy, To, Tr, OutputStage, MergeStep, FixedFormat, ForceThreadColumns, ForceFloatAccumulate >, GemmHybridIndirect< strategy, To, Tr, OutputStage, SeparateQuantize, FixedFormat >, GemmHybridQuantized< strategy, To, Tr >, GemmHybrid< strategy, To, Tr >, GemmHybridQuantizedInline< strategy, To, Tr >, GemvPretransposed< strategy, To, Tr, OutputStage >, QuantizeWrapper< To, Tr, Tgemm >, and GemvBatched< To, Tr >.
Definition at line 115 of file gemm_common.hpp.
     {
         return false;
     }
execute()
virtual void execute (const ndcoord_t & work_range, const ndcoord_t & thread_locator, int threadid) pure virtual
Main execute member fucntion.
Parameters
[in] work_range specifies the range of work we want to be computed, total range defined by get_window_size()
[in] thread_locator where are we inside of the thread space
[in] threadid a unique threadid
Implemented in QuantizeWrapper< To, Tr, Tgemm >, GemvBatched< To, Tr >, GemmHybridIndirect< strategy, To, Tr, OutputStage, SeparateQuantize, FixedFormat >, GemmHybridQuantizedInline< strategy, To, Tr >, GemmHybrid< strategy, To, Tr >, GemvPretransposed< strategy, To, Tr, OutputStage >, GemmInterleaved< strategy, To, Tr, OutputStage, MergeStep, FixedFormat, ForceThreadColumns, ForceFloatAccumulate >, and GemmHybridQuantized< strategy, To, Tr >.
Referenced by CpuGemmAssemblyWrapperKernel< TypeInput, TypeOutput >::run(), and CpuGemmAssemblyWrapperKernel< TypeInput, TypeOutput >::run_nd().
get_B_pretranspose_window_size()
virtual size_t get_B_pretranspose_window_size () const inline virtual
Reimplemented in GemmInterleaved< strategy, To, Tr, OutputStage, MergeStep, FixedFormat, ForceThreadColumns, ForceFloatAccumulate >, and GemmHybridIndirect< strategy, To, Tr, OutputStage, SeparateQuantize, FixedFormat >.
Definition at line 125 of file gemm_common.hpp.
     {
         return 1;
     }
get_B_pretransposed_array_size()
virtual size_t get_B_pretransposed_array_size () const inline virtual
Reimplemented in GemmInterleaved< strategy, To, Tr, OutputStage, MergeStep, FixedFormat, ForceThreadColumns, ForceFloatAccumulate >, GemmHybridIndirect< strategy, To, Tr, OutputStage, SeparateQuantize, FixedFormat >, GemmHybridQuantized< strategy, To, Tr >, GemmHybrid< strategy, To, Tr >, GemmHybridQuantizedInline< strategy, To, Tr >, GemvPretransposed< strategy, To, Tr, OutputStage >, QuantizeWrapper< To, Tr, Tgemm >, and GemvBatched< To, Tr >.
Definition at line 120 of file gemm_common.hpp.
     {
         return 0;
     }
get_config()
virtual GemmConfig get_config () pure virtual
Implemented in GemmInterleaved< strategy, To, Tr, OutputStage, MergeStep, FixedFormat, ForceThreadColumns, ForceFloatAccumulate >, GemmHybridIndirect< strategy, To, Tr, OutputStage, SeparateQuantize, FixedFormat >, GemmHybridQuantized< strategy, To, Tr >, GemmHybrid< strategy, To, Tr >, GemvPretransposed< strategy, To, Tr, OutputStage >, QuantizeWrapper< To, Tr, Tgemm >, and GemvBatched< To, Tr >.
get_window_size()
virtual ndrange_t get_window_size () const pure virtual
Returns
an ndrange containing ranges of the compute space which can be broken up and parallelised over
Implemented in GemmInterleaved< strategy, To, Tr, OutputStage, MergeStep, FixedFormat, ForceThreadColumns, ForceFloatAccumulate >, GemmHybridIndirect< strategy, To, Tr, OutputStage, SeparateQuantize, FixedFormat >, GemmHybridQuantized< strategy, To, Tr >, GemmHybridQuantizedInline< strategy, To, Tr >, GemmHybrid< strategy, To, Tr >, GemvPretransposed< strategy, To, Tr, OutputStage >, QuantizeWrapper< To, Tr, Tgemm >, and GemvBatched< To, Tr >.
Referenced by CpuGemmAssemblyWrapperKernel< TypeInput, TypeOutput >::configure().
get_working_size()
virtual size_t get_working_size () const inline virtual
Reimplemented in GemmInterleaved< strategy, To, Tr, OutputStage, MergeStep, FixedFormat, ForceThreadColumns, ForceFloatAccumulate >, GemmHybridQuantized< strategy, To, Tr >, QuantizeWrapper< To, Tr, Tgemm >, and GemvBatched< To, Tr >.
Definition at line 101 of file gemm_common.hpp.
     {
         return 0;
     }
pretranspose_B_array_generic()
virtual void pretranspose_B_array_generic (void * , const void * , const int , const int) pure virtual
Implemented in GemmCommon< To, Tr >, and GemmCommon< TypeInput, TypeOutput >.
pretranspose_B_array_part_generic()
virtual void pretranspose_B_array_part_generic (void * , const void * , const int , const int , const size_t, const size_t) pure virtual
Implemented in GemmCommon< To, Tr >, and GemmCommon< TypeInput, TypeOutput >.
set_arrays_generic()
virtual void set_arrays_generic (const void * A, const int lda, const int A_batch_stride, const int A_multi_stride, const void * B, const int ldb, const int B_multi_stride, void * C, const int ldc, const int C_batch_stride, const int C_multi_stride, const void * bias, const int bias_multi_stride) pure virtual
Implemented in GemmCommon< To, Tr >, and GemmCommon< TypeInput, TypeOutput >.
set_convolution_parameters()
virtual void set_convolution_parameters (ConvolutionParameters) inline virtual
Reimplemented in GemmInterleaved< strategy, To, Tr, OutputStage, MergeStep, FixedFormat, ForceThreadColumns, ForceFloatAccumulate >, and GemmHybridIndirect< strategy, To, Tr, OutputStage, SeparateQuantize, FixedFormat >.
Definition at line 156 of file gemm_common.hpp.
     {
     }
set_indirect_parameters_generic()
virtual void set_indirect_parameters_generic (size_t , const void *const *const *) inline virtual
Reimplemented in GemmCommon< To, Tr >, and GemmCommon< TypeInput, TypeOutput >.
Definition at line 150 of file gemm_common.hpp.
     {
     }
set_nthreads()
virtual void set_nthreads (int) inline virtual
Reimplemented in GemmInterleaved< strategy, To, Tr, OutputStage, MergeStep, FixedFormat, ForceThreadColumns, ForceFloatAccumulate >, QuantizeWrapper< To, Tr, Tgemm >, and GemvBatched< To, Tr >.
Definition at line 84 of file gemm_common.hpp.
 {};
set_pretransposed_B_data()
virtual void set_pretransposed_B_data (void *) inline virtual
Reimplemented in GemmInterleaved< strategy, To, Tr, OutputStage, MergeStep, FixedFormat, ForceThreadColumns, ForceFloatAccumulate >, GemmHybridIndirect< strategy, To, Tr, OutputStage, SeparateQuantize, FixedFormat >, GemmHybridQuantized< strategy, To, Tr >, GemmHybridQuantizedInline< strategy, To, Tr >, GemmHybrid< strategy, To, Tr >, GemvPretransposed< strategy, To, Tr, OutputStage >, QuantizeWrapper< To, Tr, Tgemm >, and GemvBatched< To, Tr >.
Definition at line 137 of file gemm_common.hpp.
     {
     }
set_quantized_bias()
virtual void set_quantized_bias (const int32_t * , size_t) inline virtual
Reimplemented in GemmInterleaved< strategy, To, Tr, OutputStage, MergeStep, FixedFormat, ForceThreadColumns, ForceFloatAccumulate >, GemmHybridIndirect< strategy, To, Tr, OutputStage, SeparateQuantize, FixedFormat >, GemmHybridQuantized< strategy, To, Tr >, GemmHybridQuantizedInline< strategy, To, Tr >, and QuantizeWrapper< To, Tr, Tgemm >.
Definition at line 143 of file gemm_common.hpp.
     {
     }
set_working_space()
virtual void set_working_space (void *) inline virtual
Reimplemented in GemmInterleaved< strategy, To, Tr, OutputStage, MergeStep, FixedFormat, ForceThreadColumns, ForceFloatAccumulate >, QuantizeWrapper< To, Tr, Tgemm >, GemvBatched< To, Tr >, and GemmHybridQuantized< strategy, To, Tr >.
Definition at line 106 of file gemm_common.hpp.
 {};
supports_dynamic_scheduling()
virtual bool supports_dynamic_scheduling () const inline virtual
Reimplemented in GemmHybridIndirect< strategy, To, Tr, OutputStage, SeparateQuantize, FixedFormat >, GemmHybridQuantized< strategy, To, Tr >, GemmHybridQuantizedInline< strategy, To, Tr >, and GemmHybrid< strategy, To, Tr >.
Definition at line 87 of file gemm_common.hpp.
     {
         return false;
     }
The documentation for this class was generated from the following file:
src/cpu/kernels/assembly/gemm_common.hpp