Compute Library: ClComponentStore Class Reference
ClComponentStore Class Reference final
#include <ClComponentStore.h>
Public Member Functions
ClComponentStore (ComponentId id, const Properties &properties, const ArgumentPack< ITensorInfo > &tensors)
Constructor.
~ClComponentStore () override
Destructor.
ClComponentStore (const ClComponentStore &component)=delete
Prevent instances of this class from being copy constructed.
ClComponentStore & operator= (const ClComponentStore &component)=delete
Prevent instances of this class from being copied.
ClComponentStore (ClComponentStore &&component)=default
Allow instances of this class to be move constructed.
ClComponentStore & operator= (ClComponentStore &&component)=default
Allow instances of this class to be moved.
const IGpuTemplateComponentWriter * template_writer () const override
Get writer for the component.
GpuComponentType type () const override
Get component type.
Public Member Functions inherited from IGpuKernelComponent
IGpuKernelComponent (ComponentId id, const Properties &properties, const ArgumentPack< ITensorInfo > &tensors)
Constructor.
virtual ~IGpuKernelComponent ()
Destructor.
ComponentId id () const
Get component id.
ArgumentPack< ITensorInfo > tensors () const
Get tensor arguments.
Properties properties () const
Get properties.
virtual const IGpuCkwComponentDriver * ckw_component_driver () const
Static Public Member Functions
static Status validate (const Properties &properties, const ArgumentPack< ITensorInfo > &tensors)
Validate the component.
Additional Inherited Members
Public Types inherited from IGpuKernelComponent
using Properties = KernelProperties
Detailed Description
Definition at line 48 of file ClComponentStore.h.
Constructor & Destructor Documentation
ClComponentStore() [1/3]
ClComponentStore (ComponentId id, const Properties & properties, const ArgumentPack< ITensorInfo > & tensors)
Constructor.
Similar to ClComponentStore::validate()
Definition at line 46 of file ClComponentStore.cpp.
     : IGpuKernelComponent{id, properties, tensors},
 #ifndef ACL_INTERNAL_TEST_CKW_IN_DF
       _component_writer{std::make_unique<ClTemplateStore>(id, tensors)}
 #else  //ACL_INTERNAL_TEST_CKW_IN_DF
       _component_writer{std::make_unique<GpuCkwStore>(id, tensors)}
 #endif //ACL_INTERNAL_TEST_CKW_IN_DF
 {
 }
References IGpuKernelComponent::id(), IGpuKernelComponent::properties(), and IGpuKernelComponent::tensors().
~ClComponentStore()
~ClComponentStore () override
Destructor.
Definition at line 57 of file ClComponentStore.cpp.
 {
 }
ClComponentStore() [2/3]
ClComponentStore (const ClComponentStore & component) delete
Prevent instances of this class from being copy constructed.
ClComponentStore() [3/3]
ClComponentStore (ClComponentStore && component) default
Allow instances of this class to be move constructed.
Member Function Documentation
operator=() [1/2]
ClComponentStore& operator= (ClComponentStore && component) default
Allow instances of this class to be moved.
operator=() [2/2]
ClComponentStore& operator= (const ClComponentStore & component) delete
Prevent instances of this class from being copied.
template_writer()
const IGpuTemplateComponentWriter * template_writer () const override virtual
Get writer for the component.
Reimplemented from IGpuKernelComponent.
Definition at line 61 of file ClComponentStore.cpp.
 {
     return _component_writer.get();
 }
type()
GpuComponentType type () const inline override virtual
Get component type.
Implements IGpuKernelComponent.
Definition at line 97 of file ClComponentStore.h.
     {
         return GpuComponentType::Output;
     }
References arm_compute::experimental::dynamic_fusion::Output.
validate()
Status validate (const Properties & properties, const ArgumentPack< ITensorInfo > & tensors) static
Validate the component.
Parameters
[in] properties Component properties
[in] tensors Tensor arguments to the components
Returns
Status Validation results
Tensor argument names:
ACL_SRC_0: Input
ACL_DST_0: Output
Tensor argument constness:
ACL_SRC_0: Const
ACL_DST_0: Const
Valid data layouts:
NHWC
Valid data type configurations:
ACL_SRC_0 ACL_DST_0
All All
Definition at line 41 of file ClComponentStore.cpp.
 {
     ARM_COMPUTE_UNUSED(properties, tensors);
     return Status{};
 }
References ARM_COMPUTE_UNUSED, IGpuKernelComponent::properties(), and IGpuKernelComponent::tensors().
The documentation for this class was generated from the following files:
src/dynamic_fusion/sketch/gpu/components/cl/ClComponentStore.h
src/dynamic_fusion/sketch/gpu/components/cl/ClComponentStore.cpp