Compute Library: CastAttributes Class Reference
CastAttributes Class Reference
Attributes are backend-agnostic parameters (in addition to the input/output tensors) of an operator.
#include <CastAttributes.h>
Public Member Functions
CastAttributes & data_type (const DataType &data_type)
Set Data Type to be casted to.
DataType data_type () const
Get Data Type to be casted to.
CastAttributes & convert_policy (const ConvertPolicy &policy)
Set Policy.
ConvertPolicy convert_policy () const
Get Policy.
Detailed Description
Attributes are backend-agnostic parameters (in addition to the input/output tensors) of an operator.
Cast attributes
Definition at line 39 of file CastAttributes.h.
Member Function Documentation
convert_policy() [1/2]
ConvertPolicy convert_policy () const
Get Policy.
Definition at line 50 of file CastAttributes.cpp.
 {
     return _convert_policy;
 }
Referenced by CastAttributes::convert_policy().
convert_policy() [2/2]
CastAttributes & convert_policy (const ConvertPolicy & policy)
Set Policy.
Definition at line 44 of file CastAttributes.cpp.
 {
     _convert_policy = convert_policy;
     return *this;
 }
References CastAttributes::convert_policy().
Referenced by ClTemplateCast::get_component_code(), and arm_compute::operator<<().
data_type() [1/2]
DataType data_type () const
Get Data Type to be casted to.
Definition at line 39 of file CastAttributes.cpp.
 {
     return _data_type;
 }
Referenced by CastAttributes::data_type().
data_type() [2/2]
CastAttributes & data_type (const DataType & data_type)
Set Data Type to be casted to.
Definition at line 33 of file CastAttributes.cpp.
 {
     _data_type = data_type;
     return *this;
 }
References CastAttributes::data_type().
Referenced by GpuCast::create_op(), arm_compute::operator<<(), arm_compute::test::validation::TEST_CASE(), ClComponentCast::validate(), and GpuCast::validate_op().
The documentation for this class was generated from the following files:
arm_compute/dynamic_fusion/sketch/attributes/CastAttributes.h
src/dynamic_fusion/sketch/attributes/CastAttributes.cpp