Compute Library: ElementwiseBinaryCommonAttributes Class Reference
ElementwiseBinaryCommonAttributes Class Reference
#include <GpuElementwiseBinaryCommon.h>
Public Types
enum ElementwiseOp {
Add, Sub, Div, Mul,
Min, Max, SquaredDiff, Power,
Prelu
}
Public Member Functions
ElementwiseBinaryCommonAttributes & operation (const ElementwiseBinaryCommonAttributes::ElementwiseOp &operation)
Set operation.
ElementwiseOp operation () const
Get operation.
Detailed Description
Definition at line 38 of file GpuElementwiseBinaryCommon.h.
Member Enumeration Documentation
ElementwiseOp
enum ElementwiseOp strong
Enumerator
Add
(x + y)
Sub
(x - y)
Div
(x / y)
Mul
(x * y)
Min
Min(x, y)
Max
Max(x, y)
SquaredDiff
(x - y)^2
Power
x ^ y
Prelu
y*x if x < 0, x otherwise
Definition at line 41 of file GpuElementwiseBinaryCommon.h.
     {
         Add,         /**< (x + y) */
         Sub,         /**< (x - y) */
         Div,         /**< (x / y) */
         Mul,         /**< (x * y) */
         Min,         /**< Min(x, y) */
         Max,         /**< Max(x, y) */
         SquaredDiff, /**< (x - y)^2 */
         Power,       /**< x ^ y */
         Prelu,       /**< y*x if x < 0, x otherwise */
     };
Member Function Documentation
operation() [1/2]
ElementwiseBinaryCommonAttributes::ElementwiseOp operation () const
Get operation.
Definition at line 102 of file GpuElementwiseBinaryCommon.cpp.
 {
     return _operation;
 }
Referenced by ElementwiseBinaryCommonAttributes::operation().
operation() [2/2]
ElementwiseBinaryCommonAttributes & operation (const ElementwiseBinaryCommonAttributes::ElementwiseOp & operation)
Set operation.
Definition at line 96 of file GpuElementwiseBinaryCommon.cpp.
 {
     _operation = operation;
     return *this;
 }
References ElementwiseBinaryCommonAttributes::operation().
Referenced by GpuAdd::create_op(), GpuMul::create_op(), GpuSub::create_op(), GpuCkwElementwiseBinary::get_name(), GpuAdd::is_supported_op(), GpuMul::is_supported_op(), GpuSub::is_supported_op(), arm_compute::experimental::dynamic_fusion::to_ckw(), ClComponentElementwiseBinary::validate(), GpuAdd::validate_op(), GpuSub::validate_op(), and GpuMul::validate_op().
The documentation for this class was generated from the following files:
src/dynamic_fusion/sketch/gpu/operators/internal/GpuElementwiseBinaryCommon.h
src/dynamic_fusion/sketch/gpu/operators/internal/GpuElementwiseBinaryCommon.cpp