Compute Library: NELogicalAnd Class Reference
NELogicalAnd Class Reference
Basic function to perform logical AND.
#include <NELogical.h>
Public Member Functions
NELogicalAnd ()
Constructor.
NELogicalAnd (const NELogicalAnd &)=delete
Prevent instances of this class from being copied (As this class contains pointers)
NELogicalAnd (NELogicalAnd &&)=delete
Prevent instances of this class from being moved (As this class contains non movable objects)
NELogicalAnd & operator= (const NELogicalAnd &)=delete
Prevent instances of this class from being copied (As this class contains pointers)
NELogicalAnd & operator= (NELogicalAnd &&)=delete
Prevent instances of this class from being moved (As this class contains non movable objects)
~NELogicalAnd ()
Destructor.
void configure (const ITensor *input1, const ITensor *input2, ITensor *output)
Initialise the kernel's inputs and output.
void run () override
Run the kernels contained in the function.
Public Member Functions inherited from IFunction
virtual ~IFunction ()=default
Destructor.
virtual void prepare ()
Prepare the function for executing.
Static Public Member Functions
static Status validate (const ITensorInfo *input1, const ITensorInfo *input2, const ITensorInfo *output)
Static function to check if given info will lead to a valid configuration of NELogicalAnd.
Detailed Description
Basic function to perform logical AND.
Definition at line 39 of file NELogical.h.
Constructor & Destructor Documentation
NELogicalAnd() [1/3]
NELogicalAnd ()
Constructor.
Definition at line 43 of file NELogical.cpp.
                            : _impl(std::make_unique<Impl>())
 {
 }
NELogicalAnd() [2/3]
NELogicalAnd (const NELogicalAnd &) delete
Prevent instances of this class from being copied (As this class contains pointers)
NELogicalAnd() [3/3]
NELogicalAnd (NELogicalAnd &&) delete
Prevent instances of this class from being moved (As this class contains non movable objects)
~NELogicalAnd()
~NELogicalAnd () default
Destructor.
Member Function Documentation
configure()
void configure (const ITensor * input1, const ITensor * input2, ITensor * output)
Initialise the kernel's inputs and output.
Valid data layouts:
All
Valid data type configurations:
src0 src1 dst
U8 U8 U8
Parameters
[in] input1 First tensor input. Data type supported: U8.
[in] input2 Second tensor input. Data type supported: U8.
[out] output Output tensor. Data type supported: U8.
Definition at line 48 of file NELogical.cpp.
 {
     ARM_COMPUTE_ERROR_ON_NULLPTR(input1, input2, output);
     ARM_COMPUTE_LOG_PARAMS(input1, input2, output);
     _impl->kernel = std::make_unique<kernels::NELogicalKernel>();
     _impl->kernel->configure(input1->info(), input2->info(), output->info(), LogicalOperation::And);
     _impl->pack = ITensorPack();
     _impl->pack.add_tensor(TensorType::ACL_SRC_0, input1);
     _impl->pack.add_tensor(TensorType::ACL_SRC_1, input2);
     _impl->pack.add_tensor(TensorType::ACL_DST, output);
 }
References arm_compute::ACL_DST, arm_compute::ACL_SRC_0, arm_compute::ACL_SRC_1, arm_compute::And, ARM_COMPUTE_ERROR_ON_NULLPTR, ARM_COMPUTE_LOG_PARAMS, and ITensor::info().
operator=() [1/2]
NELogicalAnd& operator= (const NELogicalAnd &) delete
Prevent instances of this class from being copied (As this class contains pointers)
operator=() [2/2]
NELogicalAnd& operator= (NELogicalAnd &&) delete
Prevent instances of this class from being moved (As this class contains non movable objects)
run()
void run () override virtual
Run the kernels contained in the function.
For CPU kernels:
Multi-threading is used for the kernels which are parallelisable.
By default std::thread::hardware_concurrency() threads are used.
Note
CPPScheduler::set_num_threads() can be used to manually set the number of threads
For OpenCL kernels:
All the kernels are enqueued on the queue associated with CLScheduler.
The queue is then flushed.
Note
The function will not block until the kernels are executed. It is the user's responsibility to wait.
Will call prepare() on first run if hasn't been done
Implements IFunction.
Definition at line 67 of file NELogical.cpp.
 {
     NEScheduler::get().schedule_op(_impl->kernel.get(), Window::DimY, _impl->kernel->window(), _impl->pack);
 }
References Window::DimY, Scheduler::get(), and IScheduler::schedule_op().
validate()
Status validate (const ITensorInfo * input1, const ITensorInfo * input2, const ITensorInfo * output) static
Static function to check if given info will lead to a valid configuration of NELogicalAnd.
Parameters
[in] input1 First input tensor info. Data types supported: U8.
[in] input2 Second input tensor info. Data types supported: U8.
[in] output Output tensor info. Data type supported: U8
Returns
a status
Definition at line 62 of file NELogical.cpp.
 {
     return kernels::NELogicalKernel::validate(input1, input2, output, LogicalOperation::And);
 }
References arm_compute::And, and NELogicalKernel::validate().
The documentation for this class was generated from the following files:
arm_compute/runtime/NEON/functions/NELogical.h
src/runtime/NEON/functions/NELogical.cpp