Compute Library: ClTemplateDepthwiseConv2d Class Reference
ClTemplateDepthwiseConv2d Class Reference final
#include <ClTemplateDepthwiseConv2d.h>
Public Types
using Attributes = ClComponentDepthwiseConv2d::Attributes
using Settings = ClComponentDepthwiseConv2d::Settings
Public Types inherited from IGpuTemplateComponentWriter
using ComponentGroup = GpuKernelComponentGroup
Public Member Functions
ClTemplateDepthwiseConv2d (ComponentId id, const ArgumentPack< ITensorInfo > &tensors, const Attributes &attributes, const Settings &settings)
Constructor.
ClTemplateDepthwiseConv2d (const ClTemplateDepthwiseConv2d &depthwise_conv2d)=delete
Prevent instances of this class from being copy constructed.
ClTemplateDepthwiseConv2d & operator= (const ClTemplateDepthwiseConv2d &depthwise_conv2d)=delete
Prevent instances of this class from being copied.
ClTemplateDepthwiseConv2d (ClTemplateDepthwiseConv2d &&depthwise_conv2d)=default
Allow instances of this class to be move constructed.
ClTemplateDepthwiseConv2d & operator= (ClTemplateDepthwiseConv2d &&depthwise_conv2d)=default
Allow instances of this class to be moved.
std::string get_name () const override
Generate kernel component name.
std::string get_component_code (const ComponentGroup &comp_group) const override
Generate kernel component code template.
void declare_variables (GpuKernelVariableTable &vtable, const ComponentGroup &comp_group) const override
Declare all variables used by the component in the vtable.
TagLUT get_tag_lut (const GpuKernelVariableTable &vtable, const ComponentGroup &comp_group) const override
Generate the tag look-up table used to instantiate the component code.
CLBuildOptions get_build_options (const ComponentGroup &comp_group) const override
Generate the build options used in the component.
std::string get_config_id () const override
Generate the component config id string used for tuning.
std::set< std::string > get_headers_list () const override
Generate the header list used in the component.
Window get_window () const override
Generate the execution window for the component.
Public Member Functions inherited from IGpuTemplateComponentWriter
IGpuTemplateComponentWriter (ComponentId id, const ArgumentPack< ITensorInfo > &tensors)
Constructor.
virtual ~IGpuTemplateComponentWriter ()
Destructor.
virtual std::string get_additional_macros () const
Generate additional macros used in the component.
ArgumentPack< ITensorInfo > tensors () const
Get tensor arguments.
ComponentId id () const
Get component id.
Additional Inherited Members
Static Public Attributes inherited from IGpuTemplateComponentWriter
static constexpr GpuKernelArgumentInfo::Type common_tensor_type = GpuKernelArgumentInfo::Type::Tensor_4D_t_Buffer
For now all kernel intermeditate/destination tensors are expected to be of type Tensor_4D_t_Buffer.
Detailed Description
Definition at line 38 of file ClTemplateDepthwiseConv2d.h.
Member Typedef Documentation
Attributes
using Attributes = ClComponentDepthwiseConv2d::Attributes
Definition at line 41 of file ClTemplateDepthwiseConv2d.h.
Settings
using Settings = ClComponentDepthwiseConv2d::Settings
Definition at line 42 of file ClTemplateDepthwiseConv2d.h.
Constructor & Destructor Documentation
ClTemplateDepthwiseConv2d() [1/3]
ClTemplateDepthwiseConv2d (ComponentId id, const ArgumentPack< ITensorInfo > & tensors, const Attributes & attributes, const Settings & settings)
Constructor.
Similar to ClComponentDepthwiseConv2d::validate()
Parameters
[in] id Component id
[in] tensors Tensor arguments to the components
[in] attributes Component attributes
[in] settings Component settings
Definition at line 35 of file ClTemplateDepthwiseConv2d.cpp.
     : IGpuTemplateComponentWriter{id, tensors},
       _src{},
       _weight{},
       _bias{},
       _dst{},
       _attributes{attributes},
       _settings{settings}
 {
     _src    = this->tensors().get_const_tensor(TensorType::ACL_SRC_0);
     _weight = this->tensors().get_const_tensor(TensorType::ACL_SRC_1);
     if (this->tensors().get_const_tensor(TensorType::ACL_SRC_2))
     {
         _bias = this->tensors().get_const_tensor(TensorType::ACL_SRC_2);
     }
     _dst = this->tensors().get_const_tensor(TensorType::ACL_DST_0);
     ARM_COMPUTE_ERROR_ON_NULLPTR(_src, _weight, _dst);
 }
References IGpuTemplateComponentWriter::id(), and IGpuTemplateComponentWriter::tensors().
ClTemplateDepthwiseConv2d() [2/3]
ClTemplateDepthwiseConv2d (const ClTemplateDepthwiseConv2d & depthwise_conv2d) delete
Prevent instances of this class from being copy constructed.
ClTemplateDepthwiseConv2d() [3/3]
ClTemplateDepthwiseConv2d (ClTemplateDepthwiseConv2d && depthwise_conv2d) default
Allow instances of this class to be move constructed.
Member Function Documentation
declare_variables()
void declare_variables (GpuKernelVariableTable & vtable, const ComponentGroup & comp_group) const override virtual
Declare all variables used by the component in the vtable.
Parameters
[out] vtable Variable table
[in] comp_group Component group of which the component is a part of
Implements IGpuTemplateComponentWriter.
Definition at line 201 of file ClTemplateDepthwiseConv2d.cpp.
 {
     const GpuKernelArgumentInfo::Type input_type = _settings.export_input_to_cl_image()
                                                        ? GpuKernelArgumentInfo::Type::Tensor_4D_t_Image
                                                        : GpuKernelArgumentInfo::Type::Tensor_4D_t_Buffer;
     vtable.declare_variable(comp_group, _src, GpuKernelArgumentInfo(input_type), "src");
     const GpuKernelArgumentInfo::Type weight_type = _settings.export_weights_to_cl_image()
                                                         ? GpuKernelArgumentInfo::Type::Tensor_4D_t_Image
                                                         : GpuKernelArgumentInfo::Type::Tensor_4D_t_Buffer;
     vtable.declare_variable(comp_group, _weight, GpuKernelArgumentInfo(weight_type), "weight");
     if (_bias != nullptr && _bias->has_valid_id()) // optional bias
     {
         vtable.declare_variable(comp_group, _bias, GpuKernelArgumentInfo(GpuKernelArgumentInfo::Type::Vector), "bias");
     }
     vtable.declare_variable(comp_group, _dst, GpuKernelArgumentInfo(GpuKernelArgumentInfo::Type::Tensor_4D_t_Buffer),
                             "dst");
 }
References GpuKernelVariableTable::declare_variable(), ClComponentDepthwiseConv2dSettings::export_input_to_cl_image(), ClComponentDepthwiseConv2dSettings::export_weights_to_cl_image(), ITensorInfo::has_valid_id(), GpuKernelArgumentInfo::Tensor_4D_t_Buffer, GpuKernelArgumentInfo::Tensor_4D_t_Image, and GpuKernelArgumentInfo::Vector.
get_build_options()
CLBuildOptions get_build_options (const ComponentGroup & comp_group) const override virtual
Generate the build options used in the component.
Parameters
[in] comp_group Component group of which the component is a part of
Returns
CLBuildOptions Build options
Reimplemented from IGpuTemplateComponentWriter.
Definition at line 294 of file ClTemplateDepthwiseConv2d.cpp.
 {
     ARM_COMPUTE_UNUSED(comp_group);
     constexpr unsigned int width_idx = 1; // Data Layout is NHWC
     const unsigned int n0               = _settings.n0();
     const unsigned int m0               = _settings.m0();
     const unsigned int m0_a             = _weight->dimension(width_idx) + m0 - 1;
     const unsigned int n0_a             = _attributes.depth_multiplier() > 1 ? 1 : n0;
     const unsigned int partial_store_n0 = _dst->dimension(0) % n0;
     CLBuildOptions build_opts{};
     if (_settings.fast_relaxed_math())
     {
         build_opts.add_option("-cl-fast-relaxed-math");
     }
     else
     {
         // -cl-fast-relaxed-math also sets -cl-finite-math-only and -cl-unsafe-math-optimizations
         // to disable -cl-finite-math-only, we only include -cl-unsafe-math-optimizations
         build_opts.add_option("-cl-unsafe-math-optimizations");
     }
     build_opts.add_option("-DN0=" + support::cpp11::to_string(n0));
     build_opts.add_option("-DM0=" + support::cpp11::to_string(m0));
     build_opts.add_option("-DN0_A=" + support::cpp11::to_string(n0_a));
     build_opts.add_option("-DM0_A=" + support::cpp11::to_string(m0_a));
     build_opts.add_option("-DPARTIAL_N0=" + support::cpp11::to_string(partial_store_n0));
     return build_opts;
 }
References CLBuildOptions::add_option(), ARM_COMPUTE_UNUSED, DepthwiseConv2dAttributes::depth_multiplier(), ITensorInfo::dimension(), ClComponentDepthwiseConv2dSettings::fast_relaxed_math(), ClComponentDepthwiseConv2dSettings::m0(), ClComponentDepthwiseConv2dSettings::n0(), arm_compute::support::cpp11::to_string(), and arm_compute::cpu::width_idx.
get_component_code()
std::string get_component_code (const ComponentGroup & comp_group) const override virtual
Generate kernel component code template.
Parameters
[in] comp_group Component group of which the component is a part of
Returns
std::string Component code
Implements IGpuTemplateComponentWriter.
Definition at line 62 of file ClTemplateDepthwiseConv2d.cpp.
 {
     ARM_COMPUTE_UNUSED(comp_group);
     constexpr int height_idx = 2; // Data Layout is NHWC
     std::string code = R"_(
 //------------------ START KERNEL {{meta_kernel_id}} ---------------------
 // IN_0(src)            {{src}}
 // IN_1(wei)            {{weight}}
 )_";
     if (_bias != nullptr && _bias->has_valid_id())
     {
         code += R"_(
 // IN_1(bia)            {{bias}}
 )_";
     }
     code += R"_(
 // OUT(dst, accum)      {{dst}}
 TILE(uint, M0, 1, g_dst_indirect_y);
 {
 #define _IWEI_WIDTH {{WEI_WIDTH}}
 #define _IWEI_HEIGHT {{WEI_HEIGHT}}
 #define _IDST_WIDTH {{arg_dst}}_w
 #define _IDST_HEIGHT {{arg_dst}}_h
 #define _IM0_A M0_A
 #define _IN0_A N0_A
 #define _IM0_B _IWEI_WIDTH
 #define _IN0_B N0
 #define _IBOUNDARY_CHECK (!((_IWEI_WIDTH == 1 && _IWEI_HEIGHT == 1 && {{PAD_LEFT}} == 0 && {{PAD_TOP}} == 0 && M0 == 1)))
 )_";
     code += R"_(
     const int yo = g_ind_2 % {{arg_dst}}_h;
     const int bout = g_ind_2 / {{arg_dst}}_h;
 )_";
     code += R"_(
     int xi = g_ind_1 * {{STRIDE_X}};
     int yi = yo * {{STRIDE_Y}};
     xi -= {{PAD_LEFT}};
     yi -= {{PAD_TOP}};
     LOOP_UNROLLING(int, i, 0, 1, M0,
     {
         {{dst}}[i].v = 0;
     })
 )_";
     if (_weight->dimension(height_idx) < 5)
     {
         code += R"_(
     LOOP_UNROLLING(int, yk, 0, 1, _IWEI_HEIGHT,
 )_";
     }
     else
     {
         code += R"_(
     for(int yk = 0; yk < _IWEI_HEIGHT; ++yk)
 )_";
     }
     code += R"_(
     {
         TILE({{SRC_DATA_TYPE}}, _IM0_A, _IN0_A, a);
         LOOP_UNROLLING(int, i, 0, 1, _IM0_A,
         {
             a[i].v = 0;
         })
         T_LOAD_NHWC_WITH_DILATION({{SRC_DATA_TYPE}}, 1, _IM0_A, _IN0_A, {{SRC_TENSOR_TYPE}}, {{src}}, bout, yi + yk * {{DILATION_Y}}, xi, (g_ind_0 / {{DEPTH_MULTIPLIER}}), {{src}}_w, {{src}}_h, {{DILATION_X}}, 1, _IBOUNDARY_CHECK, a);
         TILE({{WEI_DATA_TYPE}}, _IM0_B, _IN0_B, b);
         T_LOAD({{WEI_DATA_TYPE}}, _IM0_B, _IN0_B, {{WEI_TENSOR_TYPE}}, {{weight}}, g_ind_0, yk * _IM0_B, 1, {{weight}}_stride_y, b);
         LOOP_UNROLLING(int, m0, 0, 1, M0,
         {
             LOOP_UNROLLING(int, xk, 0, 1, _IWEI_WIDTH,
             {
 )_";
     if (!_settings.is_fma_available())
     {
         code += R"_(
                 {{dst}}[m0].v += a[xk + m0].v * b[xk].v;
 )_";
     }
     else
     {
         code += R"_(
                 {{dst}}[m0].v = fma(a[xk + m0].v, b[xk].v, {{dst}}[m0].v);
 )_";
     }
     code += R"_(
             })
         })
     }
 )_";
     if (_weight->dimension(height_idx) < 5)
     {
         code += R"_(
     )
 )_";
     }
     if (_bias && _bias->has_valid_id())
     {
         code += R"_(
         TILE({{BIA_DATA_TYPE}}, 1, N0, {{bias}});
         T_LOAD({{BIA_DATA_TYPE}}, 1, N0, BUFFER, {{bias}}, g_ind_0, 0, 0, 0, {{bias}});
         T_ELTWISE_BROADCAST_ADD_X({{ACC_DATA_TYPE}}, M0, N0, {{dst}}, {{bias}}, {{dst}});
 )_";
     }
     code += R"_(
     LOOP_UNROLLING(int, i, 0, 1, M0,
     {
         g_dst_indirect_y[i].v = (uint)min((int)(g_ind_1 + i), (int)({{arg_dst}}_w) - 1);
         g_dst_indirect_y[i].v += (int)(g_ind_2 % {{arg_dst}}_h) * (int)({{arg_dst}}_w);
         g_dst_indirect_y[i].v += (int)(g_ind_2 / {{arg_dst}}_h) * (int)({{arg_dst}}_w * {{arg_dst}}_h);
     })
 }
 //------------------ END KERNEL {{meta_kernel_id}} ---------------------
 )_";
     return code;
 }
References ARM_COMPUTE_UNUSED, ITensorInfo::dimension(), ITensorInfo::has_valid_id(), arm_compute::cpu::height_idx, and ClComponentDepthwiseConv2dSettings::is_fma_available().
get_config_id()
std::string get_config_id () const override virtual
Generate the component config id string used for tuning.
Reimplemented from IGpuTemplateComponentWriter.
Definition at line 328 of file ClTemplateDepthwiseConv2d.cpp.
 {
     std::string config_id{};
     config_id += support::cpp11::to_string(_src->dimension(0));
     config_id += "_";
     config_id += support::cpp11::to_string(_src->dimension(1));
     config_id += "_";
     config_id += support::cpp11::to_string(_src->dimension(2));
     config_id += "_";
     config_id += support::cpp11::to_string(_dst->dimension(0));
     config_id += "_";
     config_id += support::cpp11::to_string(_dst->dimension(1));
     config_id += "_";
     config_id += support::cpp11::to_string(_dst->dimension(2));
     config_id += "_";
     config_id += string_from_data_type(_src->data_type());
     return config_id;
 }
References ITensorInfo::data_type(), ITensorInfo::dimension(), arm_compute::string_from_data_type(), and arm_compute::support::cpp11::to_string().
get_headers_list()
std::set< std::string > get_headers_list () const override virtual
Generate the header list used in the component.
Reimplemented from IGpuTemplateComponentWriter.
Definition at line 349 of file ClTemplateDepthwiseConv2d.cpp.
 {
     return std::set<std::string>{"helpers.h", "tile_helpers.h"};
 }
get_name()
std::string get_name () const override virtual
Generate kernel component name.
Implements IGpuTemplateComponentWriter.
Definition at line 57 of file ClTemplateDepthwiseConv2d.cpp.
 {
     return "depthwise_conv2d";
 }
get_tag_lut()
TagLUT get_tag_lut (const GpuKernelVariableTable & vtable, const ComponentGroup & comp_group) const override virtual
Generate the tag look-up table used to instantiate the component code.
Parameters
[in] vtable Variable table
[in] comp_group Component group of which the component is a part of
Returns
TagLUT Tag lookup table
Implements IGpuTemplateComponentWriter.
Definition at line 224 of file ClTemplateDepthwiseConv2d.cpp.
 {
     TagLUT lut{};
     // Arguments and global shared variables
     lut["src"]    = vtable.get_variable(_src);
     lut["weight"] = vtable.get_variable(_weight);
     if (_bias != nullptr && _bias->has_valid_id()) // optional bias
     {
         lut["bias"]          = vtable.get_variable(_bias);
         lut["BIA_DATA_TYPE"] = get_cl_type_from_data_type(_bias->data_type());
     }
     lut["dst"] = vtable.get_variable(_dst);
     const auto dst_argument = vtable.get_variable(comp_group.get_any_dst_tensor());
     lut["arg_dst"]          = dst_argument.uniq_name;
     // Local build options
     lut["meta_kernel_id"] = id();
     lut["ACC_DATA_TYPE"]  = _src->data_type();
     lut["SRC_DATA_TYPE"]  = _src->data_type();
     lut["WEI_DATA_TYPE"]  = _weight->data_type();
     switch (vtable.get_variable(_src).kernel_argument_info.type)
     {
         case GpuKernelArgumentInfo::Type::Image_Export_To_ClImage2D:
         case GpuKernelArgumentInfo::Type::Image_3D_Export_To_ClImage2D:
         case GpuKernelArgumentInfo::Type::Tensor_4D_t_Image:
             lut["SRC_TENSOR_TYPE"] = "IMAGE";
             break;
         default:
             lut["SRC_TENSOR_TYPE"] = "BUFFER";
             break;
     }
     switch (vtable.get_variable(_weight).kernel_argument_info.type)
     {
         case GpuKernelArgumentInfo::Type::Image_Export_To_ClImage2D:
         case GpuKernelArgumentInfo::Type::Image_3D_Export_To_ClImage2D:
         case GpuKernelArgumentInfo::Type::Tensor_4D_t_Image:
             lut["WEI_TENSOR_TYPE"] = "IMAGE";
             break;
         default:
             lut["WEI_TENSOR_TYPE"] = "BUFFER";
             break;
     }
     // Data Layout is NHWC
     constexpr int width_idx  = 1;
     constexpr int height_idx = 2;
     lut["WEI_WIDTH"]  = _weight->dimension(width_idx);
     lut["WEI_HEIGHT"] = _weight->dimension(height_idx);
     lut["STRIDE_X"] = _attributes.stride().x();
     lut["STRIDE_Y"] = _attributes.stride().y();
     lut["PAD_LEFT"] = _attributes.pad().left;
     lut["PAD_TOP"]  = _attributes.pad().top;
     lut["DILATION_X"] = _attributes.dilation().x();
     lut["DILATION_Y"] = _attributes.dilation().y();
     lut["DEPTH_MULTIPLIER"] = _attributes.depth_multiplier();
     return lut;
 }
References ITensorInfo::data_type(), DepthwiseConv2dAttributes::depth_multiplier(), DepthwiseConv2dAttributes::dilation(), ITensorInfo::dimension(), GpuKernelComponentGroup::get_any_dst_tensor(), arm_compute::get_cl_type_from_data_type(), GpuKernelVariableTable::get_variable(), ITensorInfo::has_valid_id(), arm_compute::cpu::height_idx, IGpuTemplateComponentWriter::id(), GpuKernelArgumentInfo::Image_3D_Export_To_ClImage2D, GpuKernelArgumentInfo::Image_Export_To_ClImage2D, GpuKernelVariableTable::TensorVariable::kernel_argument_info, DepthwiseConv2dAttributes::pad(), DepthwiseConv2dAttributes::stride(), GpuKernelArgumentInfo::Tensor_4D_t_Image, GpuKernelArgumentInfo::type, GpuKernelVariableTable::TensorVariable::uniq_name, and arm_compute::cpu::width_idx.
get_window()
Window get_window () const override virtual
Generate the execution window for the component.
Reimplemented from IGpuTemplateComponentWriter.
Definition at line 354 of file ClTemplateDepthwiseConv2d.cpp.
 {
     ARM_COMPUTE_ERROR_ON_MSG(_dst->tensor_shape().total_size() == 0U, "Destination tensor is not initialized");
     Window win = calculate_max_window(*_dst, Steps(_settings.n0(), _settings.m0()));
     return win.collapse(win, Window::DimZ);
 }
References ARM_COMPUTE_ERROR_ON_MSG, arm_compute::calculate_max_window(), Window::collapse(), Window::DimZ, ClComponentDepthwiseConv2dSettings::m0(), ClComponentDepthwiseConv2dSettings::n0(), ITensorInfo::tensor_shape(), TensorShape::total_size(), and arm_compute::utils::cast::U.
operator=() [1/2]
ClTemplateDepthwiseConv2d& operator= (ClTemplateDepthwiseConv2d && depthwise_conv2d) default
Allow instances of this class to be moved.
operator=() [2/2]
ClTemplateDepthwiseConv2d& operator= (const ClTemplateDepthwiseConv2d & depthwise_conv2d) delete
Prevent instances of this class from being copied.
The documentation for this class was generated from the following files:
src/dynamic_fusion/sketch/gpu/template_writer/cl/ClTemplateDepthwiseConv2d.h
src/dynamic_fusion/sketch/gpu/template_writer/cl/ClTemplateDepthwiseConv2d.cpp