Compute Library: GpuCkwComponentArgument Class Reference
GpuCkwComponentArgument Class Reference
The argument of a dynamic fusion component which can be either user tensor or virtual tensor.
#include <GpuCkwComponentArgument.h>
Public Member Functions
GpuCkwComponentArgument ()=default
Default constructor.
GpuCkwComponentArgument (ckw::TensorOperand tensor)
Initialize a new instance of GpuCkwComponentArgument class for user tensor.
GpuCkwComponentArgument & init_virtual_tensor (ckw::TileOperand &tile, const ckw::TensorSampler &sampler)
Bind the tile and sampler to the tensor argument.
bool has_tensor () const
Get whether the argument is a user tensor.
ckw::TensorOperand & tensor ()
Get the tensor operand.
const ckw::TensorOperand & tensor () const
Get the tensor operand.
bool has_tile () const
Get whether the argument contains a tile.
ckw::TileOperand & tile ()
Get the tile operand.
const ckw::TileOperand & tile () const
Get the tile operand.
ckw::TensorSampler & tensor_sampler ()
Get the tensor sampling information for the tile.
const ckw::TensorSampler & tensor_sampler () const
Get the tensor sampling information for the tile.
Detailed Description
The argument of a dynamic fusion component which can be either user tensor or virtual tensor.
Definition at line 40 of file GpuCkwComponentArgument.h.
Constructor & Destructor Documentation
GpuCkwComponentArgument() [1/2]
GpuCkwComponentArgument () default
Default constructor.
GpuCkwComponentArgument() [2/2]
GpuCkwComponentArgument (ckw::TensorOperand tensor) explicit
Initialize a new instance of GpuCkwComponentArgument class for user tensor.
Parameters
[in] tensor The user tensor.
Definition at line 36 of file GpuCkwComponentArgument.cpp.
                                                                         : _tensor(tensor)
 {
 }
Member Function Documentation
has_tensor()
bool has_tensor () const
Get whether the argument is a user tensor.
Definition at line 51 of file GpuCkwComponentArgument.cpp.
 {
     return _tensor.is_valid();
 }
has_tile()
bool has_tile () const
Get whether the argument contains a tile.
The argument can be either a user tensor that has been loaded, or a virtual tensor (i.e. a tile with tensor sampling information).
Definition at line 70 of file GpuCkwComponentArgument.cpp.
 {
     return _tile.is_valid();
 }
Referenced by GpuCkwElementwiseBinary::write_component_code(), and GpuCkwDirectConv2d::write_component_code().
init_virtual_tensor()
GpuCkwComponentArgument & init_virtual_tensor (ckw::TileOperand & tile, const ckw::TensorSampler & sampler)
Bind the tile and sampler to the tensor argument.
This method can be used to share a tile and sampler associated to a tensor among different kernel components. For example, when we create the destination tile and destination sampler for the first time (root component), this method can be used to bind these two information to the destination tensor so that the following simple components know the tile size and how to access the elements from memory.
Parameters
[in] tile The tile that has been loaded.
[in] sampler The tensor sampling information that has been used to load the tile.
Definition at line 40 of file GpuCkwComponentArgument.cpp.
 {
     CKW_ASSERT(_tile == nullptr);
     _tile    = tile;
     _sampler = sampler;
     return *this;
 }
References GpuCkwComponentArgument::tile().
Referenced by GpuCkwElementwiseBinary::write_component_code(), and GpuCkwDirectConv2d::write_component_code().
tensor() [1/2]
const ckw::TensorOperand & tensor ()
Get the tensor operand.
If the tensor is not available, throw an error.
Definition at line 56 of file GpuCkwComponentArgument.cpp.
 {
     CKW_ASSERT(_tensor.is_valid());
     return _tensor;
 }
Referenced by GpuCkwElementwiseBinary::write_component_code(), GpuCkwDepthwiseConv2d::write_component_code(), GpuCkwDirectConv2d::write_component_code(), and GpuCkwMatMul::write_component_code().
tensor() [2/2]
const ckw::TensorOperand& tensor () const
Get the tensor operand.
If the tensor is not available, throw an error.
tensor_sampler() [1/2]
const ckw::TensorSampler & tensor_sampler ()
Get the tensor sampling information for the tile.
If the tile is not available, throw an error.
Definition at line 89 of file GpuCkwComponentArgument.cpp.
 {
     CKW_ASSERT(_tile.is_valid());
     return _sampler;
 }
tensor_sampler() [2/2]
const ckw::TensorSampler& tensor_sampler () const
Get the tensor sampling information for the tile.
If the tile is not available, throw an error.
tile() [1/2]
const ckw::TileOperand & tile ()
Get the tile operand.
If the tile is not available, throw an error.
Definition at line 75 of file GpuCkwComponentArgument.cpp.
 {
     CKW_ASSERT(_tile.is_valid());
     return _tile;
 }
Referenced by GpuCkwComponentArgument::init_virtual_tensor(), GpuCkwElementwiseBinary::write_component_code(), and GpuCkwDirectConv2d::write_component_code().
tile() [2/2]
const ckw::TileOperand& tile () const
Get the tile operand.
If the tile is not available, throw an error.
The documentation for this class was generated from the following files:
src/dynamic_fusion/sketch/gpu/ckw_driver/GpuCkwComponentArgument.h
src/dynamic_fusion/sketch/gpu/ckw_driver/GpuCkwComponentArgument.cpp