Compute Library: TensorShape Class Reference
TensorShape Class Reference
Shape of a tensor.
#include <TensorShape.h>
Public Member Functions
template<typename... Ts>
TensorShape (Ts... dims)
Constructor to initialize the tensor shape.
TensorShape (const TensorShape &)=default
Allow instances of this class to be copy constructed.
TensorShape & operator= (const TensorShape &)=default
Allow instances of this class to be copied.
TensorShape (TensorShape &&)=default
Allow instances of this class to be move constructed.
TensorShape & operator= (TensorShape &&)=default
Allow instances of this class to be moved.
~TensorShape ()=default
Default destructor.
TensorShape & set (size_t dimension, size_t value, bool apply_dim_correction=true, bool increase_dim_unit=true)
Accessor to set the value of one of the dimensions.
void remove_dimension (size_t n, bool apply_dim_correction=true)
Accessor to remove the dimension n from the tensor shape.
void collapse (size_t n, size_t first=0)
Collapse the first n dimensions.
void shift_right (size_t step)
Shifts right the tensor shape increasing its dimensions.
TensorShape collapsed_from (size_t start) const
Return a copy with collapsed dimensions starting from a given point.
size_t total_size () const
Collapses all dimensions to a single linear total size.
size_t total_size_upper (size_t dimension) const
Collapses given dimension and above.
size_t total_size_lower (size_t dimension) const
Compute size of dimensions lower than the given one.
Public Member Functions inherited from Dimensions< size_t >
Dimensions (Ts... dims)
Constructor to initialize the tensor shape.
Dimensions (const Dimensions &)=default
Allow instances of this class to be copy constructed.
Dimensions (Dimensions &&)=default
Allow instances of this class to be move constructed.
Dimensions & operator= (const Dimensions &)=default
Allow instances of this class to be copied.
Dimensions & operator= (Dimensions &&)=default
Allow instances of this class to be moved.
void set (size_t dimension, size_t value, bool increase_dim_unit=true)
Accessor to set the value of one of the dimensions.
size_t x () const
Alias to access the size of the first dimension.
size_t y () const
Alias to access the size of the second dimension.
size_t z () const
Alias to access the size of the third dimension.
void increment (size_t dim, size_t step=1)
Increments the given dimension by a step size, avoiding overflows.
const size_t & operator[] (size_t dimension) const
Generic accessor to get the size of any dimension.
size_t & operator[] (size_t dimension)
Generic accessor to get the size of any dimension.
unsigned int num_dimensions () const
Returns the effective dimensionality of the tensor.
void set_num_dimensions (size_t num_dimensions)
Set number of dimensions.
void collapse (const size_t n, const size_t first=0)
Collapse dimensions.
void collapse_from (size_t start)
Collapse dimensions starting from a given point.
void remove (size_t idx)
Remove dimension of a given index.
std::array< size_t, num_max_dimensions >::iterator begin ()
Returns a read/write iterator that points to the first element in the dimension array.
std::array< size_t, num_max_dimensions >::const_iterator begin () const
Returns a read-only (constant) iterator that points to the first element in the dimension array.
std::array< size_t, num_max_dimensions >::const_iterator cbegin () const
Returns a read-only (constant) iterator that points to the first element in the dimension array.
std::array< size_t, num_max_dimensions >::iterator end ()
Returns a read/write iterator that points one past the last element in the dimension array.
std::array< size_t, num_max_dimensions >::const_iterator end () const
Returns a read-only (constant) iterator that points one past the last element in the dimension array.
std::array< size_t, num_max_dimensions >::const_iterator cend () const
Returns a read-only (constant) iterator that points one past the last element in the dimension array.
Static Public Member Functions
template<typename... Shapes>
static TensorShape broadcast_shape (const Shapes &...shapes)
If shapes are broadcast compatible, return the broadcasted shape.
Additional Inherited Members
Static Public Attributes inherited from Dimensions< size_t >
static constexpr size_t num_max_dimensions
Number of dimensions the tensor has.
Detailed Description
Shape of a tensor.
Definition at line 39 of file TensorShape.h.
Constructor & Destructor Documentation
TensorShape() [1/3]
TensorShape (Ts... dims) inline
Constructor to initialize the tensor shape.
Parameters
[in] dims Values to initialize the dimensions.
Definition at line 47 of file TensorShape.h.
                             : Dimensions{dims...}
     {
         // Initialize unspecified dimensions to 1
         if (_num_dimensions > 0)
         {
             std::fill(_id.begin() + _num_dimensions, _id.end(), 1);
         }
         // Correct number dimensions to ignore trailing dimensions of size 1
         apply_dimension_correction();
     }
TensorShape() [2/3]
TensorShape (const TensorShape &) default
Allow instances of this class to be copy constructed.
TensorShape() [3/3]
TensorShape (TensorShape &&) default
Allow instances of this class to be move constructed.
~TensorShape()
~TensorShape () default
Default destructor.
Member Function Documentation
broadcast_shape()
static TensorShape broadcast_shape (const Shapes &... shapes) inline static
If shapes are broadcast compatible, return the broadcasted shape.
Two tensor shapes are broadcast compatible if for each dimension, they're equal or one of them is 1.
If two shapes are compatible, each dimension in the broadcasted shape is the max of the original dimensions.
Parameters
[in] shapes Tensor shapes.
Returns
The broadcasted shape or an empty shape if the shapes are not broadcast compatible.
Definition at line 214 of file TensorShape.h.
     {
         TensorShape bc_shape;
         auto broadcast = [&bc_shape](const TensorShape &other)
         {
             if (bc_shape.num_dimensions() == 0)
             {
                 bc_shape = other;
             }
             else if (other.num_dimensions() != 0)
             {
                 for (size_t d = 0; d < TensorShape::num_max_dimensions; ++d)
                 {
                     const size_t dim_min = std::min(bc_shape[d], other[d]);
                     const size_t dim_max = std::max(bc_shape[d], other[d]);
                     if ((dim_min != 1) && (dim_min != dim_max))
                     {
                         bc_shape = TensorShape{0U};
                         break;
                     }
                     bc_shape.set(d, dim_max);
                 }
             }
         };
         utility::for_each(broadcast, shapes...);
         return bc_shape;
     }
References arm_compute::utility::for_each(), Dimensions< T >::num_dimensions(), Dimensions< size_t >::num_max_dimensions, TensorShape::set(), and arm_compute::utils::cast::U.
Referenced by arm_compute::test::validation::reference::arithmetic_division(), arm_compute::test::validation::reference::arithmetic_operation(), ITensorInfo::broadcast_shape_and_valid_region(), arm_compute::test::validation::reference::compare(), NELogicalKernel::configure(), CpuSubKernel::configure(), CpuAddKernel::configure(), CpuMulKernel::configure(), ClMulKernel::configure(), ClComplexMulKernel::configure(), CpuComplexMulKernel::configure(), EltwiseLayerNode::configure_output(), arm_compute::test::validation::reference::logical_and(), arm_compute::test::validation::reference::logical_or(), arm_compute::test::validation::reference::pixel_wise_multiplication(), NELogicalKernel::validate(), and ClComponentElementwiseBinary::validate().
collapse()
void collapse (size_t n, size_t first = 0) inline
Collapse the first n dimensions.
Parameters
[in] n Number of dimensions to collapse into first
[in] first Dimensions into which the following n are collapsed.
Definition at line 136 of file TensorShape.h.
     {
         Dimensions::collapse(n, first);
         // Make sure all empty dimensions are filled with 1
         std::fill(_id.begin() + _num_dimensions, _id.end(), 1);
     }
References Dimensions< T >::collapse(), and arm_compute::test::validation::fill().
Referenced by arm_compute::misc::shape_calculator::compute_flatten_shape(), arm_compute::misc::shape_calculator::compute_softmax_shape(), arm_compute::misc::shape_calculator::compute_weights_reshaped_shape(), ClTransposedConvolutionKernel::configure(), CpuGemmLowpMatrixMultiplyKernel::configure(), ClIndirectConv2dKernel::configure(), ClDirectConv2dKernel::configure(), FlattenLayerNode::configure_output(), GpuCkwElementwiseBinary::get_window(), GpuCkwActivation::get_window(), and GpuCkwCast::get_window().
collapsed_from()
TensorShape collapsed_from (size_t start) const inline
Return a copy with collapsed dimensions starting from a given point.
Parameters
[in] start Starting point of collapsing dimensions.
Returns
A copy with collapse dimensions starting from start.
Definition at line 164 of file TensorShape.h.
     {
         TensorShape copy(*this);
         copy.collapse(num_dimensions() - start, start);
         return copy;
     }
References arm_compute::test::validation::reference::copy(), and Dimensions< size_t >::num_dimensions().
Referenced by CpuMatMul::configure(), CLComparisonKernel::run(), CpuMatMul::run(), ClElementwiseKernel::run_op(), ClMulKernel::run_op(), and ClComplexMulKernel::run_op().
operator=() [1/2]
TensorShape& operator= (const TensorShape &) default
Allow instances of this class to be copied.
operator=() [2/2]
TensorShape& operator= (TensorShape &&) default
Allow instances of this class to be moved.
remove_dimension()
void remove_dimension (size_t n, bool apply_dim_correction = true) inline
Accessor to remove the dimension n from the tensor shape.
Note
The upper dimensions of the tensor shape will be shifted down by 1
Parameters
[in] n Dimension to remove
[in] apply_dim_correction (Optional) Flag to state whether apply dimension correction (removing trailing dimensions with size of 1) after removing a dimension.
Definition at line 111 of file TensorShape.h.
     {
         ARM_COMPUTE_ERROR_ON(_num_dimensions < 1);
         ARM_COMPUTE_ERROR_ON(n >= _num_dimensions);
         std::copy(_id.begin() + n + 1, _id.end(), _id.begin() + n);
         // Reduce number of dimensions
         _num_dimensions--;
         // Make sure all empty dimensions are filled with 1
         std::fill(_id.begin() + _num_dimensions, _id.end(), 1);
         // Correct number dimensions to ignore trailing dimensions of size 1
         if (apply_dim_correction)
         {
             apply_dimension_correction();
         }
     }
References ARM_COMPUTE_ERROR_ON, arm_compute::test::validation::reference::copy(), and arm_compute::test::validation::fill().
Referenced by arm_compute::misc::shape_calculator::calculate_reduce_mean_shape(), arm_compute::misc::shape_calculator::calculate_unstack_shape(), arm_compute::misc::shape_calculator::compute_im2col_conv_shape(), arm_compute::misc::shape_calculator::compute_lhs_reshaped_shape(), arm_compute::misc::shape_calculator::compute_min_max_shape(), arm_compute::misc::shape_calculator::compute_reduced_shape(), arm_compute::misc::shape_calculator::compute_reductionB_shape(), NEReduceMean::configure(), CLReduceMean::configure(), NEFFTConvolutionLayer::configure(), and CLFFTConvolutionLayer::configure().
set()
TensorShape& set (size_t dimension, size_t value, bool apply_dim_correction = true, bool increase_dim_unit = true) inline
Accessor to set the value of one of the dimensions.
Parameters
[in] dimension Dimension for which the value is set.
[in] value Value to be set for the dimension.
[in] apply_dim_correction (Optional) Flag to state whether apply dimension correction after setting one dimension. E.g. when permuting NCHW -> NHWC, 1x1x2 would become 2x1x1, but _num_dimensions should be 3 rather than 1.
[in] increase_dim_unit (Optional) Set to true if new unit dimensions increase the number of dimensions of the shape.
Returns
*this.
Definition at line 78 of file TensorShape.h.
     {
         // Clear entire shape if one dimension is zero
         if (value == 0)
         {
             _num_dimensions = 0;
             std::fill(_id.begin(), _id.end(), 0);
         }
         else
         {
             // Make sure all empty dimensions are filled with 1
             std::fill(_id.begin() + _num_dimensions, _id.end(), 1);
             // Set the specified dimension and increase the number of dimensions if
             // necessary
             Dimensions::set(dimension, value, increase_dim_unit);
             // Correct number dimensions to ignore trailing dimensions of size 1
             if (apply_dim_correction)
             {
                 apply_dimension_correction();
             }
         }
         return *this;
     }
References arm_compute::test::validation::fill(), and Dimensions< T >::set().
Referenced by GraphBuilder::add_convolution_node(), GraphBuilder::add_deconvolution_node(), GraphBuilder::add_depthwise_convolution_node(), GraphBuilder::add_scale_layer(), TensorShape::broadcast_shape(), arm_compute::misc::shape_calculator::calculate_concatenate_shape(), arm_compute::misc::shape_calculator::calculate_reduce_mean_shape(), arm_compute::calculate_valid_region_scale(), arm_compute::misc::shape_calculator::compute_conv3d_shape(), arm_compute::misc::shape_calculator::compute_deconvolution_output_shape(), arm_compute::misc::shape_calculator::compute_deconvolution_upsampled_shape(), arm_compute::misc::shape_calculator::compute_deep_convolution_shape(), arm_compute::misc::shape_calculator::compute_depth_to_space_shape(), arm_compute::misc::shape_calculator::compute_depthwise_convolution_shape(), arm_compute::misc::shape_calculator::compute_gather_shape(), arm_compute::misc::shape_calculator::compute_im2col_conv_shape(), arm_compute::misc::shape_calculator::compute_interleaved_shape(), arm_compute::misc::shape_calculator::compute_lhs_reshaped_shape(), arm_compute::misc::shape_calculator::compute_matmul_shape(), arm_compute::misc::shape_calculator::compute_min_max_shape(), arm_compute::misc::shape_calculator::compute_mm_shape(), PoolingLayerNode::compute_output_descriptor(), PriorBoxLayerNode::compute_output_descriptor(), ReorgLayerNode::compute_output_descriptor(), DetectionOutputLayerNode::compute_output_descriptor(), DeconvolutionLayerNode::compute_output_descriptor(), SplitLayerNode::compute_output_descriptor(), FusedConvolutionBatchNormalizationNode::compute_output_descriptor(), FusedDepthwiseConvolutionBatchNormalizationNode::compute_output_descriptor(), DepthwiseConvolutionLayerNode::compute_output_descriptor(), ConvolutionLayerNode::compute_output_descriptor(), arm_compute::misc::shape_calculator::compute_output_stage_shape(), arm_compute::misc::shape_calculator::compute_padded_shape(), arm_compute::misc::shape_calculator::compute_pool3d_shape(), arm_compute::misc::shape_calculator::compute_pool_shape(), arm_compute::misc::shape_calculator::compute_prior_box_shape(), arm_compute::misc::shape_calculator::compute_reduced_shape(), arm_compute::misc::shape_calculator::compute_reductionB_shape(), arm_compute::misc::shape_calculator::compute_reorg_output_shape(), arm_compute::misc::shape_calculator::compute_rhs_reshaped_shape(), arm_compute::misc::shape_calculator::compute_rnn_shape(), arm_compute::misc::shape_calculator::compute_roi_align_shape(), arm_compute::misc::shape_calculator::compute_space_to_batch_shape(), arm_compute::misc::shape_calculator::compute_space_to_depth_shape(), arm_compute::misc::shape_calculator::compute_split_shape(), arm_compute::misc::shape_calculator::compute_stack_shape(), arm_compute::helpers::tensor_transform::compute_strided_slice_output_shape(), arm_compute::misc::shape_calculator::compute_tiled_shape(), arm_compute::misc::shape_calculator::compute_unpool_shape(), arm_compute::misc::shape_calculator::compute_upsample_shape(), arm_compute::misc::shape_calculator::compute_vector_to_tensor_output_shape(), arm_compute::misc::shape_calculator::compute_weights_reshaped_shape(), arm_compute::misc::shape_calculator::compute_winograd_input_transform_shape(), ClSoftmaxKernel::configure(), CpuGemmMatrixMultiplyKernel::configure(), NEReduceMean::configure(), CLArgMinMaxLayerKernel::configure(), CLReduceMean::configure(), CpuGemmConv2d::configure(), ClGemmConv2d::configure(), ResizeLayerNode::configure_output(), ROIAlignLayerNode::configure_output(), PadLayerNode::configure_output(), SplitLayerNode::configure_output(), GpuSoftmax::create_op(), arm_compute::test::validation::reference::deconvolution_layer(), NPYLoader::fill_tensor(), arm_compute::intersect_valid_regions(), GpuSoftmax::is_supported_op(), arm_compute::test::validation::reference::scale_core(), ValidRegion::set(), GraphEdsr::setup(), Window::shape(), arm_compute::test::validation::transpose(), CLReductionOperation::validate(), CpuGemmConv2d::validate(), ClGemmConv2d::validate(), and CpuGemmLowpMatrixMultiplyCore::validate().
shift_right()
void shift_right (size_t step) inline
Shifts right the tensor shape increasing its dimensions.
Parameters
[in] step Rotation step
Definition at line 147 of file TensorShape.h.
     {
         ARM_COMPUTE_ERROR_ON(step > TensorShape::num_max_dimensions - num_dimensions());
         std::rotate(begin(), begin() + TensorShape::num_max_dimensions - step, end());
         _num_dimensions += step;
         // Correct number dimensions to ignore trailing dimensions of size 1
         apply_dimension_correction();
     }
References ARM_COMPUTE_ERROR_ON, Dimensions< size_t >::begin(), Dimensions< size_t >::end(), Dimensions< size_t >::num_dimensions(), Dimensions< size_t >::num_max_dimensions, and arm_compute::cpu::step.
Referenced by arm_compute::misc::shape_calculator::compute_output_stage_shape(), and arm_compute::misc::shape_calculator::compute_softmax_shape().
total_size()
size_t total_size () const inline
Collapses all dimensions to a single linear total size.
Returns
The total tensor size in terms of elements.
Definition at line 175 of file TensorShape.h.
     {
         return std::accumulate(_id.begin(), _id.end(), 1, std::multiplies<size_t>());
     }
References arm_compute::test::validation::reference::accumulate().
Referenced by arm_compute::auto_init_if_empty(), arm_compute::test::validation::reference::col2im(), arm_compute::misc::shape_calculator::compute_gather_shape(), CLSelectKernel::configure(), NESpaceToBatchLayer::configure(), CLSpaceToBatchLayer::configure(), EltwiseLayerNode::configure_output(), GpuCkwActivation::get_window(), GpuCkwCast::get_window(), GpuCkwElementwiseBinary::get_window(), GpuCkwResize::get_window(), GpuCkwPool2d::get_window(), GpuCkwDirectConv2d::get_window(), GpuCkwMatMul::get_window(), ClTemplateCast::get_window(), ClTemplateLogits1DNorm::get_window(), ClTemplateLogits1DMaxShiftExpSum::get_window(), ClTemplateReshape::get_window(), ClTemplateDepthwiseConv2d::get_window(), ClTemplateDirectConv2d::get_window(), ClTemplateResize::get_window(), ClTemplatePool2d::get_window(), ClTemplateActivation::get_window(), Accessor::num_elements(), CLAccessor::num_elements(), arm_compute::test::validation::reference::reshape_layer(), CLComparisonKernel::run(), ClElementwiseKernel::run_op(), ClMatMulNativeKernel::run_op(), ClMulKernel::run_op(), ClComplexMulKernel::run_op(), SubTensorInfo::set_tensor_shape(), SubTensorInfo::set_valid_region(), CPPSplit< CLSlice, ICLTensor >::validate(), NELogicalKernel::validate(), CpuConcatenate::validate(), ClConcatenate::validate(), ClComponentElementwiseBinary::validate(), ClComponentLogits1DNorm::validate(), ClComponentLogits1DMaxShiftExpSum::validate(), NEDeconvolutionLayer::validate(), and arm_compute::opencl::kernels::validate_matmul_input_shapes().
total_size_lower()
size_t total_size_lower (size_t dimension) const inline
Compute size of dimensions lower than the given one.
Parameters
[in] dimension Upper boundary.
Returns
The linear size of the collapsed dimensions.
Definition at line 197 of file TensorShape.h.
     {
         ARM_COMPUTE_ERROR_ON(dimension > TensorShape::num_max_dimensions);
         return std::accumulate(_id.begin(), _id.begin() + dimension, 1, std::multiplies<size_t>());
     }
References arm_compute::test::validation::reference::accumulate(), ARM_COMPUTE_ERROR_ON, and Dimensions< size_t >::num_max_dimensions.
Referenced by CpuConvertFullyConnectedWeightsKernel::validate(), and ClConvertFullyConnectedWeightsKernel::validate().
total_size_upper()
size_t total_size_upper (size_t dimension) const inline
Collapses given dimension and above.
Parameters
[in] dimension Size of the wanted dimension
Returns
The linear size of the collapsed dimensions
Definition at line 185 of file TensorShape.h.
     {
         ARM_COMPUTE_ERROR_ON(dimension >= TensorShape::num_max_dimensions);
         return std::accumulate(_id.begin() + dimension, _id.end(), 1, std::multiplies<size_t>());
     }
References arm_compute::test::validation::reference::accumulate(), ARM_COMPUTE_ERROR_ON, and Dimensions< size_t >::num_max_dimensions.
Referenced by arm_compute::test::validation::reference::fully_connected_layer(), GpuCkwDirectConv2d::get_window(), ClTemplateDirectConv2d::get_window(), and ClWinogradInputTransformKernel::run_op().
The documentation for this class was generated from the following file:
arm_compute/core/TensorShape.h