Compute Library: GenericDepthfirstStrategy< TInput, TWeight, TOutput, TAccum, OutputStage > Class Template Reference
GenericDepthfirstStrategy< TInput, TWeight, TOutput, TAccum, OutputStage > Class Template Reference
#include <depthwise_depthfirst_generic.hpp>
Public Member Functions
GenericDepthfirstStrategy (KernelStrategyType *strat, unsigned int n_output_rows, unsigned int n_output_cols, const DepthwiseArgs &args)
GenericDepthfirstStrategy (GenericDepthfirstStrategy &)=delete
GenericDepthfirstStrategy operator= (GenericDepthfirstStrategy &)=delete
arm_gemm::VLType get_vl_type (void) const override
unsigned int get_accumulator_depth_vl (void) const override
size_t get_storage_size (const DepthwiseArgs &args) const override
void pack_parameters (const DepthwiseArgs &args, void *buffer, const void *biases, const OutputStage &, const void *weights, size_t ld_weight_col, size_t ld_weight_row) const override
const KernelStrategyType::KernelType get_kernel () const
Public Member Functions inherited from DepthwiseDepthfirstStrategyCommon< TInput, TInput, TInput, typename DefaultTAccum< TInput >::Type, typename DefaultOutputStage< TInput >::Type >
DepthwiseDepthfirstStrategyCommon (unsigned int output_rows, unsigned int output_cols, unsigned int kernel_rows, unsigned int kernel_cols, unsigned int stride_rows=1, unsigned int stride_cols=1)
DepthwiseDepthfirstStrategyCommon (unsigned int output_size, unsigned int kernel_size, unsigned int stride=1)
virtual ~DepthwiseDepthfirstStrategyCommon ()
unsigned int get_output_rows () const override
unsigned int get_output_cols () const override
unsigned int get_kernel_rows () const override
unsigned int get_kernel_cols () const override
unsigned int get_stride_rows () const override
unsigned int get_stride_cols () const override
Public Member Functions inherited from DepthfirstStrategy< TInput, TInput, TInput, typename DefaultTAccum< TInput >::Type, typename DefaultOutputStage< TInput >::Type >
virtual void pack_parameters (const DepthwiseArgs &args, void *buffer, const void *biases, const typename DefaultOutputStage< TInput >::Type &, const void *weights, size_t ld_weight_col, size_t ld_weight_row) const
Public Member Functions inherited from DepthfirstStrategyUntyped
virtual unsigned int get_kernel_rows () const =0
virtual unsigned int get_kernel_cols () const =0
virtual unsigned int get_stride_rows () const =0
virtual unsigned int get_stride_cols () const =0
virtual unsigned int get_input_rows () const override
virtual unsigned int get_input_cols () const override
virtual unsigned int get_n_input_points () const
virtual unsigned int get_n_output_points () const
virtual unsigned int get_n_kernel_points () const
virtual bool uses_premultiply () const
virtual bool get_kernel_packing_point (const unsigned int index, unsigned int &x, unsigned int &y) const
Public Member Functions inherited from IDepthfirstStrategy
virtual ~IDepthfirstStrategy ()=default
virtual unsigned int get_output_rows () const =0
virtual unsigned int get_output_cols () const =0
Detailed Description
template<typename TInput, typename TWeight = TInput, typename TOutput = TInput, typename TAccum = typename DefaultTAccum<TInput>::Type, typename OutputStage = typename DefaultOutputStage<TOutput>::Type>
class arm_conv::depthwise::GenericDepthfirstStrategy< TInput, TWeight, TOutput, TAccum, OutputStage >
Definition at line 72 of file depthwise_depthfirst_generic.hpp.
Constructor & Destructor Documentation
GenericDepthfirstStrategy() [1/2]
GenericDepthfirstStrategy (KernelStrategyType * strat, unsigned int n_output_rows, unsigned int n_output_cols, const DepthwiseArgs & args) inline
Definition at line 79 of file depthwise_depthfirst_generic.hpp.
   : DepthwiseDepthfirstStrategyCommon<TInput, TWeight, TOutput, TAccum, OutputStage>(
       n_output_rows, n_output_cols,
       args.kernel_rows, args.kernel_cols,
       args.stride_rows, args.stride_cols
     ),
     m_strategy(strat)
   {
   }
GenericDepthfirstStrategy() [2/2]
GenericDepthfirstStrategy (GenericDepthfirstStrategy< TInput, TWeight, TOutput, TAccum, OutputStage > &) delete
Member Function Documentation
get_accumulator_depth_vl()
unsigned int get_accumulator_depth_vl (void) const inline override virtual
Reimplemented from DepthfirstStrategyUntyped.
Definition at line 96 of file depthwise_depthfirst_generic.hpp.
 { return m_strategy->get_accumulator_depth_vl(); }
Referenced by GenericDepthfirstStrategy< TInput, TWeight, TOutput, TAccum, OutputStage >::get_storage_size(), and GenericDepthfirstStrategy< TInput, TWeight, TOutput, TAccum, OutputStage >::pack_parameters().
get_kernel()
const KernelStrategyType::KernelType get_kernel () const inline
Definition at line 127 of file depthwise_depthfirst_generic.hpp.
 { return m_strategy->get_kernel(); }
get_storage_size()
size_t get_storage_size (const DepthwiseArgs & args) const inline override virtual
Reimplemented from DepthfirstStrategy< TInput, TInput, TInput, typename DefaultTAccum< TInput >::Type, typename DefaultOutputStage< TInput >::Type >.
Definition at line 98 of file depthwise_depthfirst_generic.hpp.
   {
     interleaves::PackingArguments packing_args(
       this->get_kernel_rows(), this->get_kernel_cols(), sizeof(TWeight),
       false, sizeof(TAccum), this->uses_premultiply(),  // Don't pack the bias
       this->get_vl_type(), sizeof(TAccum), this->get_accumulator_depth_vl(),
       [this] (unsigned int idx, unsigned int &x, unsigned int &y) -> bool
       { return this->get_kernel_packing_point(idx, x, y); }
     );
     return interleaves::get_storage_size_generic(packing_args, args);
   }
References GemmTuner::args, GenericDepthfirstStrategy< TInput, TWeight, TOutput, TAccum, OutputStage >::get_accumulator_depth_vl(), DepthwiseDepthfirstStrategyCommon< TInput, TInput, TInput, typename DefaultTAccum< TInput >::Type, typename DefaultOutputStage< TInput >::Type >::get_kernel_cols(), DepthfirstStrategyUntyped::get_kernel_packing_point(), DepthwiseDepthfirstStrategyCommon< TInput, TInput, TInput, typename DefaultTAccum< TInput >::Type, typename DefaultOutputStage< TInput >::Type >::get_kernel_rows(), arm_conv::depthwise::interleaves::get_storage_size_generic(), GenericDepthfirstStrategy< TInput, TWeight, TOutput, TAccum, OutputStage >::get_vl_type(), and DepthfirstStrategyUntyped::uses_premultiply().
get_vl_type()
arm_gemm::VLType get_vl_type (void) const inline override virtual
Implements DepthfirstStrategyUntyped.
Definition at line 95 of file depthwise_depthfirst_generic.hpp.
 { return m_strategy->get_vl_type(); }
Referenced by GenericDepthfirstStrategy< TInput, TWeight, TOutput, TAccum, OutputStage >::get_storage_size(), and GenericDepthfirstStrategy< TInput, TWeight, TOutput, TAccum, OutputStage >::pack_parameters().
operator=()
GenericDepthfirstStrategy operator= (GenericDepthfirstStrategy< TInput, TWeight, TOutput, TAccum, OutputStage > &) delete
pack_parameters()
void pack_parameters (const DepthwiseArgs & args, void * buffer, const void * biases, const OutputStage & , const void * weights, size_t ld_weight_col, size_t ld_weight_row) const inline override
Definition at line 110 of file depthwise_depthfirst_generic.hpp.
   {
     interleaves::PackingArguments packing_args(
       this->get_kernel_rows(), this->get_kernel_cols(), sizeof(TWeight),
       false, sizeof(TAccum), this->uses_premultiply(),  // Don't pack the bias
       this->get_vl_type(), sizeof(TAccum), this->get_accumulator_depth_vl(),
       [this] (unsigned int idx, unsigned int &x, unsigned int &y) -> bool
       { return this->get_kernel_packing_point(idx, x, y); }
     );
     interleaves::pack_parameters_generic(
       packing_args, args, buffer, biases, weights, ld_weight_col, ld_weight_row);
   }
References GemmTuner::args, GenericDepthfirstStrategy< TInput, TWeight, TOutput, TAccum, OutputStage >::get_accumulator_depth_vl(), DepthwiseDepthfirstStrategyCommon< TInput, TInput, TInput, typename DefaultTAccum< TInput >::Type, typename DefaultOutputStage< TInput >::Type >::get_kernel_cols(), DepthfirstStrategyUntyped::get_kernel_packing_point(), DepthwiseDepthfirstStrategyCommon< TInput, TInput, TInput, typename DefaultTAccum< TInput >::Type, typename DefaultOutputStage< TInput >::Type >::get_kernel_rows(), GenericDepthfirstStrategy< TInput, TWeight, TOutput, TAccum, OutputStage >::get_vl_type(), arm_conv::depthwise::interleaves::pack_parameters_generic(), and DepthfirstStrategyUntyped::uses_premultiply().
The documentation for this class was generated from the following file:
src/core/NEON/kernels/arm_conv/depthwise/depthwise_depthfirst_generic.hpp