Compute Library: GemmHybridIndirect< strategy, To, Tr, OutputStage, SeparateQuantize, FixedFormat > Class Template Reference
GemmHybridIndirect< strategy, To, Tr, OutputStage, SeparateQuantize, FixedFormat > Class Template Reference
#include <gemm_hybrid_indirect.hpp>
Public Member Functions
GemmHybridIndirect (GemmHybridIndirect &)=delete
GemmHybridIndirect & operator= (GemmHybridIndirect &)=delete
GemmHybridIndirect (const GemmArgs &args, const OutputStage &os)
GemmHybridIndirect (const GemmArgs &args)
ndrange_t get_window_size () const override
bool supports_dynamic_scheduling () const override
void execute (const ndcoord_t &work_range, const ndcoord_t &, int) override
Main execute member fucntion.
bool B_is_pretransposed () const override
bool B_pretranspose_required () const override
size_t get_B_pretransposed_array_size () const override
size_t get_B_pretranspose_window_size () const override
void requantize_bias (void *in_buffer, const To *B, const int ldb, const int B_multi_stride) override
void pretranspose_B_array (void *in_buffer, const To *B, const int ldb, const int B_multi_stride) override
void pretranspose_B_array_part (void *in_buffer, const To *B, const int ldb, const int B_multi_stride, size_t start, size_t end) override
void set_pretransposed_B_data (void *in_buffer) override
void set_quantized_bias (const int32_t *bias, size_t bias_multi_stride) override
void set_indirect_parameters (size_t string_len, const To *const *const *ptr) override
void set_convolution_parameters (ConvolutionParameters parms) override
GemmConfig get_config () override
Public Member Functions inherited from GemmCommon< To, Tr >
virtual void set_arrays (const To *A, const int lda, const int A_batch_stride, const int A_multi_stride, const To *B, const int ldb, const int B_multi_stride, Tr *C, const int ldc, const int C_batch_stride, const int C_multi_stride, const Tr *bias, const int bias_multi_stride)
void set_arrays_generic (const void *A, const int lda, const int A_batch_stride, const int A_multi_stride, const void *B, const int ldb, const int B_multi_stride, void *C, const int ldc, const int C_batch_stride, const int C_multi_stride, const void *bias, const int bias_multi_stride) override
void pretranspose_B_array_generic (void *out, const void *in, const int row_stride, const int multi_stride) override
void pretranspose_B_array_part_generic (void *out, const void *in, const int row_stride, const int multi_stride, size_t start, size_t end) override
void set_indirect_parameters_generic (size_t sz, const void *const *const *ptr) override
Public Member Functions inherited from IGemmCommon
virtual void set_nthreads (int)
virtual size_t get_working_size () const
virtual void set_working_space (void *)
virtual ~IGemmCommon ()
Static Public Member Functions
template<typename perf_type >
static uint64_t estimate_cycles (const GemmArgs &args, const OutputStage &os={})
Detailed Description
template<typename strategy, typename To, typename Tr, typename OutputStage = Nothing, bool SeparateQuantize = false, bool FixedFormat = false>
class arm_gemm::GemmHybridIndirect< strategy, To, Tr, OutputStage, SeparateQuantize, FixedFormat >
Definition at line 264 of file gemm_hybrid_indirect.hpp.
Constructor & Destructor Documentation
GemmHybridIndirect() [1/3]
GemmHybridIndirect (GemmHybridIndirect< strategy, To, Tr, OutputStage, SeparateQuantize, FixedFormat > &) delete
GemmHybridIndirect() [2/3]
GemmHybridIndirect (const GemmArgs & args, const OutputStage & os) inline
Definition at line 389 of file gemm_hybrid_indirect.hpp.
               : _args(args), _os(os), _Ktotal(get_ktotal(args)),
                 _rounded_Ksize(roundup(args._Ksize, strategy::k_unroll())),
                 _k_block(compute_k_block(args)), _n_block(compute_n_block(args, os)),
                 _Mround(roundup(args._Msize, strategy::out_height())),
                 _window_range(iceildiv(args._Msize, strategy::out_height()), args._nbatches,
                               iceildiv(args._Nsize, _n_block), args._nmulti)
     {
         // We take a copy of the arguments (not a pointer or reference), but there is no lifetime requirement on the
         // GemmConfig.  Clear out the pointer to avoid accidents.
         _args._cfg = nullptr;
     }
References GemmArgs::_cfg.
GemmHybridIndirect() [3/3]
GemmHybridIndirect (const GemmArgs & args) inline
Definition at line 403 of file gemm_hybrid_indirect.hpp.
               : _args(args), _Ktotal(get_ktotal(args)),
                 _rounded_Ksize(roundup(args._Ksize, strategy::k_unroll())),
                 _k_block(compute_k_block(args)), _n_block(compute_n_block(args)),
                 _Mround(roundup(args._Msize, strategy::out_height())),
                 _window_range(iceildiv(args._Msize, strategy::out_height()), args._nbatches,
                               iceildiv(args._Nsize, _n_block), args._nmulti)
     {
         // We take a copy of the arguments (not a pointer or reference), but there is no lifetime requirement on the
         // GemmConfig.  Clear out the pointer to avoid accidents.
         _args._cfg = nullptr;
     }
References GemmArgs::_cfg.
Member Function Documentation
B_is_pretransposed()
bool B_is_pretransposed () const inline override virtual
Reimplemented from IGemmCommon.
Definition at line 591 of file gemm_hybrid_indirect.hpp.
{
         return (FixedFormat == false);
     }
B_pretranspose_required()
bool B_pretranspose_required () const inline override virtual
Reimplemented from IGemmCommon.
Definition at line 595 of file gemm_hybrid_indirect.hpp.
{
         return (FixedFormat == false) && (_B_transposed==nullptr);
     }
estimate_cycles()
static uint64_t estimate_cycles (const GemmArgs & args, const OutputStage & os = {}) inline static
Definition at line 751 of file gemm_hybrid_indirect.hpp.
                                                                                   {}) {
         const PerformanceParameters params = strategy::template get_performance_parameters<perf_type>(args._ci);
         // Note: Current hybrid kernels don't actually round up height (they
         // have paths for each possible height).  Might need to make this
         // configurable in future.
         uint64_t total_macs = static_cast<uint64_t>(args._nbatches) * args._nmulti * args._Msize * roundup(args._Nsize, strategy::out_width()) * get_ktotal(args);
         float mac_cycles = static_cast<float>(total_macs) / params.kernel_macs_cycle;
         // TODO: A bit of a kludge here: current hybrid kernels incur extra
         // overhead where the width is not a multiple of kernel width.  It's
         // most noticable where the overall width is quite low, so add 15%
         // penalty for such widths.
         if ((args._Nsize < strategy::out_width()) || (args._Nsize > strategy::out_width() && args._Nsize < 2*strategy::out_width())) {
             mac_cycles *= 1.15f;
         }
         uint64_t total_cycles = mac_cycles;
         // Quantizing kernels with separate quantize need to add in the extra stages.
         if (std::is_same<OutputStage, Requantize32>::value && SeparateQuantize) {
             const Requantize32 *qp = reinterpret_cast<const Requantize32 *>(&os);
             // Row sums: need to consider each value in A (batch * multi * M * K)...
             uint64_t rowsum_bytes = static_cast<uint64_t>(args._nbatches) * args._nmulti * args._Msize * get_ktotal(args);
             // ... but row sums are skipped if B offset==0.
             if (qp->b_offset == 0) {
                 rowsum_bytes = 0;
             }
             // Use "prepare bytes per cycle" to store "row sum values per cycle".
             float rowsum_cycles = static_cast<float>(rowsum_bytes) / params.prepare_bytes_cycle;
             // Requantize: need to consider each value in C (batch * multi * M * N)
             uint64_t requantize_bytes = static_cast<uint64_t>(args._nbatches) * args._nmulti * args._Msize * args._Nsize;
             // Use "merge bytes per cycle" to store "requantize values per cycle".
             float requantize_cycles = static_cast<float>(requantize_bytes) / params.merge_bytes_cycle;
             // Recalculate total_cycles with the extra components.
             total_cycles = mac_cycles + rowsum_cycles + requantize_cycles;
         }
         return total_cycles;
     }
execute()
void execute (const ndcoord_t & work_range, const ndcoord_t & thread_locator, int threadid) inline override virtual
Main execute member fucntion.
Parameters
[in] work_range specifies the range of work we want to be computed, total range defined by get_window_size()
[in] thread_locator where are we inside of the thread space
[in] threadid a unique threadid
Implements IGemmCommon.
Definition at line 427 of file gemm_hybrid_indirect.hpp.
{
 #ifdef CYCLE_PROFILING
         profiler prof;
 #endif
         strategy strat(_args._ci);
         std::vector<const To *>         in_row_ptrs;
         std::vector<const To * const *> in_row_strings;
         std::vector<unsigned int>       string_lengths;
         // In convolution mode, we need input pointers.
         if (_convolver) {
             in_row_ptrs = std::vector<const To *>(strategy::out_height() * _args._Ksections, nullptr);
             in_row_strings = std::vector<const To * const *>(_args._Ksections, nullptr);
             for (unsigned int i=0; i<_args._Ksections; i++) {
                 in_row_strings[i] = &(in_row_ptrs.data()[i * strategy::out_height()]);
             }
         }
         // In any indirect mode, we need the string lengths.
         if (_args._indirect_input) {
             string_lengths = std::vector<unsigned int>(_args._Ksections, 0);
         }
         /* Make sure we've been set up correctly. */
         assert(FixedFormat || _B_transposed);
         static_assert(std::is_same<To, Tloi>::value, "gemm_native: Operand types must be the same.");
 //        static_assert(std::is_same<Tr, Tri>::value, "gemm_native: Result types must be the same.");
         /* For now, each work item implies all the K for a given output
          * pixel (so we don't need to synchronize access to the output
          * array).  So separate the loop over K blocks here.  */
         for (unsigned int k0=0; k0<_Ktotal; k0+=_k_block) {
             unsigned int kmax   = std::min(k0 + _k_block, _Ktotal);
             unsigned int kern_k = roundup(kmax-k0, strategy::k_unroll());
             const bool first_pass = (k0 == 0);
             const bool last_pass = (kmax == _Ktotal);
             unsigned int first_section = (k0 / _rounded_Ksize);
             unsigned int first_offset  = (k0 % _rounded_Ksize);
             unsigned int kleft = kern_k;
             unsigned int sections=0;
             unsigned int offset = first_offset;
             if (_args._indirect_input) {
                 while (kleft) {
                     // When chopping into sections: the amount that goes into 'string_lengths' is the amount to be
                     // processed (excluding padding).  But the amount we subtract from 'kleft' takes account of any
                     // padding applied.
                     string_lengths[sections] = std::min(kleft, _args._Ksize - offset);
                     kleft -= std::min(kleft, _rounded_Ksize - offset);
                     sections++;
                     offset=0;
                 }
             }
             auto p = _window_range.iterator(work_range.get_position(0), work_range.get_position_end(0));
             if (p.done()) {
                 return;
             }
             // Process rows either 'out_height' rows at a time, or do all valid rows at once with a single kernel call.
             // The separate quantizer path only handles one block of rows at a time (as it has to store sums and intermediate results).
             // THe convolution path only generates the pointers for one block of rows at a time.
             const bool process_all_rows = (!SeparateQuantize && !_convolver);
             do {
                 const unsigned int m_start = p.dim(0) * strategy::out_height();
                 const unsigned int m_end   = process_all_rows ? std::min(p.dim0_max() * strategy::out_height(), _args._Msize) : std::min(m_start + strategy::out_height(), _args._Msize);
 //                const unsigned int m_end   = std::min(m_start + strategy::out_height(), _args._Msize);
                 const unsigned int batch   = p.dim(1);
                 const unsigned int n0      = p.dim(2) * _n_block;
                 const unsigned int nmax    = std::min(n0 + _n_block, _args._Nsize);
                 const unsigned int multi   = p.dim(3);
                 const Troi *b_panel;
                 if (FixedFormat) {
                     b_panel = reinterpret_cast<const Troi *>(this->_Bptr) +
                                (multi * this->_B_multi_stride) +
                                ((n0 / stripe_width<strategy, FixedFormat>::get()) * this->_ldb) +
                                (k0 * stripe_width<strategy, FixedFormat>::get());
                 } else {
                     b_panel = _B_transposed +
                                (multi * roundup(_args._Nsize, strategy::out_width()) * _Ktotal) +
                                (k0 * roundup(_args._Nsize, strategy::out_width())) +
                                (n0 * kern_k);
                 }
                 IndirectOutputArg<Tr> out_arg(this->_Cptr + (multi * this->_C_multi_stride) + (batch * this->_C_batch_stride) + (m_start * this->_ldc) + n0, this->_ldc);
 #ifdef CYCLE_PROFILING
                 auto p = prof.ScopedProfiler(PROFILE_KERNEL, (unsigned long)(m_end - m_start) * kern_k * roundup(nmax-n0, strategy::out_width()));
 #endif
                 if (_indirect_buf) {
                     run_hybrid_kernel<OutputStage, SeparateQuantize, FixedFormat>::run(
 #ifdef CYCLE_PROFILING
                                  prof,
 #endif
                                  strat, sections, string_lengths.data(),
                                  IndirectInputArg<To>(_indirect_buf + (multi * _args._nbatches * _args._Ksections) + (batch * _args._Ksections) + first_section, m_start, first_offset),
                                  (m_end - m_start), (nmax - n0), kern_k, b_panel, this->_ldb, out_arg,
                                  (this->_bias && first_pass) ? this->_bias + (multi * this->_bias_multi_stride) + n0 : nullptr,
                                  last_pass ? _args._act : Activation(),
                                  !first_pass,
                                  // Quantization parameters
                                  _os, _col_bias+(multi * _args._Nsize), n0);
                 } else if (_convolver) {
                     auto conv_cols = _convolver->process_columns(this->_Aptr + (multi * this->_A_multi_stride) + (batch * this->_A_batch_stride), this->_lda, k0, kmax, _rounded_Ksize);
                     unsigned int pos=0;
                     auto conv_rows = conv_cols.process_rows(m_start, m_end - m_start);
                     while (!conv_rows.finished()) {
                         unsigned int width, conv_offset;
                         assert(pos < sections);
                         std::tie(width, conv_offset) = conv_rows.next_block(&(in_row_ptrs[pos * strategy::out_height()]));
                         if (pos==0) {
                             assert(conv_offset == first_offset);
                         }
                         assert(width == string_lengths[pos]);
                         pos++;
                     }
                     assert(pos == sections);
                     run_hybrid_kernel<OutputStage, SeparateQuantize, FixedFormat>::run(
 #ifdef CYCLE_PROFILING
                                  prof,
 #endif
                                  strat, sections, string_lengths.data(),
                                  IndirectInputArg<To>(in_row_strings.data(), 0, first_offset),
                                  (m_end - m_start), (nmax - n0), kern_k, b_panel, this->_ldb, out_arg,
                                  (this->_bias && first_pass) ? this->_bias + (multi * this->_bias_multi_stride) + n0 : nullptr,
                                  last_pass ? _args._act : Activation(),
                                  !first_pass,
                                  // Quantization parameters
                                  _os, _col_bias+(multi * _args._Nsize), n0);
                 } else {
                     // Length to process.  This needs to exclude padding, but 'kmax' potentially includes it.
                     const unsigned int len = (std::min(_args._Ksize, kmax) - k0);
                     run_hybrid_kernel<OutputStage, SeparateQuantize, FixedFormat>::run(
 #ifdef CYCLE_PROFILING
                                  prof,
 #endif
                                  strat, 1, &len,
                                  IndirectInputArg<To>(this->_Aptr + (multi * this->_A_multi_stride) + (batch * this->_A_batch_stride) + m_start * this->_lda + k0, this->_lda),
                                  (m_end - m_start), (nmax - n0), kern_k, b_panel, this->_ldb, out_arg,
                                  (this->_bias && first_pass) ? this->_bias + (multi * this->_bias_multi_stride) + n0 : nullptr,
                                  last_pass ? _args._act : Activation(),
                                  !first_pass,
                                  // Quantization parameters
                                  _os, _col_bias+(multi * _args._Nsize), n0);
                 }
             } while (process_all_rows ? p.next_dim1() : p.next_dim0());
         }
     }
References GemmArgs::_act, GemmArgs::_ci, GemmArgs::_indirect_input, GemmArgs::_Ksections, GemmArgs::_Ksize, GemmArgs::_Msize, GemmArgs::_nbatches, GemmArgs::_Nsize, NDCoordinate< N >::get_position(), NDCoordinate< N >::get_position_end(), NDRange< D >::iterator(), offset(), arm_gemm::roundup(), arm_compute::test::validation::run(), sections, and strategy.
get_B_pretranspose_window_size()
size_t get_B_pretranspose_window_size () const inline override virtual
Reimplemented from IGemmCommon.
Definition at line 617 of file gemm_hybrid_indirect.hpp.
{
         return _args._nmulti * iceildiv(_args._Nsize, strategy::out_width());
     }
References GemmArgs::_nmulti, GemmArgs::_Nsize, and arm_gemm::iceildiv().
Referenced by GemmHybridIndirect< strategy, To, Tr, OutputStage, SeparateQuantize, FixedFormat >::pretranspose_B_array(), and GemmHybridIndirect< strategy, To, Tr, OutputStage, SeparateQuantize, FixedFormat >::pretranspose_B_array_part().
get_B_pretransposed_array_size()
size_t get_B_pretransposed_array_size () const inline override virtual
Reimplemented from IGemmCommon.
Definition at line 599 of file gemm_hybrid_indirect.hpp.
{
         if (FixedFormat) {
             return 0;
         }
         // Start with actual pretransposed buffer...
         size_t size = roundup(_args._Nsize, strategy::out_width()) * _Ktotal * _args._nmulti * sizeof(Troi);
         // Space for result row pointers (not strictly needed any more but retained for indirect output testing)
         size += _args._Msize * _args._nbatches * _args._nmulti * sizeof(const Tr *);
         if (std::is_same<OutputStage, Requantize32>::value) {
             size += get_col_sum_size();
         }
         return size;
     }
References GemmArgs::_Msize, GemmArgs::_nbatches, GemmArgs::_nmulti, GemmArgs::_Nsize, and arm_gemm::roundup().
get_config()
GemmConfig get_config () inline override virtual
Implements IGemmCommon.
Definition at line 818 of file gemm_hybrid_indirect.hpp.
{
         GemmConfig c;
         c.method = GemmMethod::GEMM_HYBRID;
         c.inner_block_size = _k_block;
         c.outer_block_size = _n_block;
         c.filter = get_type_name<strategy>();
         c.weight_format = get_weight_format(kernel_weight_format<strategy, FixedFormat>::get(), sizeof(To));
         return c;
     }
References GemmConfig::filter, arm_gemm::GEMM_HYBRID, arm_gemm::get_weight_format(), GemmConfig::inner_block_size, GemmConfig::method, GemmConfig::outer_block_size, and GemmConfig::weight_format.
get_window_size()
ndrange_t get_window_size () const inline override virtual
Returns
an ndrange containing ranges of the compute space which can be broken up and parallelised over
Implements IGemmCommon.
Definition at line 417 of file gemm_hybrid_indirect.hpp.
{
         return { _window_range.total_size() };
     }
References NDRange< D >::total_size().
operator=()
GemmHybridIndirect& operator= (GemmHybridIndirect< strategy, To, Tr, OutputStage, SeparateQuantize, FixedFormat > &) delete
pretranspose_B_array()
void pretranspose_B_array (void * in_buffer, const To * B, const int ldb, const int B_multi_stride) inline override virtual
Reimplemented from GemmCommon< To, Tr >.
Definition at line 634 of file gemm_hybrid_indirect.hpp.
{
         pretranspose_B_array_part(in_buffer, B, ldb, B_multi_stride, 0, get_B_pretranspose_window_size());
     }
References GemmHybridIndirect< strategy, To, Tr, OutputStage, SeparateQuantize, FixedFormat >::get_B_pretranspose_window_size(), and GemmHybridIndirect< strategy, To, Tr, OutputStage, SeparateQuantize, FixedFormat >::pretranspose_B_array_part().
pretranspose_B_array_part()
void pretranspose_B_array_part (void * in_buffer, const To * B, const int ldb, const int B_multi_stride, size_t start, size_t end) inline override virtual
Reimplemented from GemmCommon< To, Tr >.
Definition at line 638 of file gemm_hybrid_indirect.hpp.
{
         if (end >= get_B_pretranspose_window_size()) {
             requantize_bias(in_buffer, B, ldb, B_multi_stride);
         }
         // Put the transposed data after the column sums - in non-transposing cases get_col_sum_size() == 0
         uintptr_t buffer_int = reinterpret_cast<uintptr_t>(in_buffer);
         Troi *buffer_base = reinterpret_cast<Troi *>(buffer_int + get_col_sum_size());
         _B_transposed = buffer_base;
         strategy strat(_args._ci);
         size_t work_per_multi = iceildiv(_args._Nsize, strategy::out_width());
         for (unsigned int multi=(start / work_per_multi); multi<_args._nmulti; multi++) {
             // Work out which part of the window space this multi occupies,
             // skip to the next multi or exit as needed.
             size_t wk_start = multi * work_per_multi;
             size_t wk_end = (multi + 1) * work_per_multi;
             assert(wk_end > start);
             if (wk_start >= end) {
                 break;
             }
             for (unsigned int k0=0; k0<_Ktotal; k0+=_k_block) {
                 const unsigned int kmax=std::min(k0 + _k_block, _Ktotal);
                 /* Figure out the size of each block. */
                 unsigned int k_size = kmax - k0;
                 // Correct the N range and buffer base if we are not processing the whole block.
                 size_t n_start = 0;
                 size_t n_end = _args._Nsize;
                 // If we are not doing the first columns, update the buffer write position and starting N value.
                 if (start > wk_start) {
                     n_start = (start - wk_start) * strategy::out_width();
                 }
                 // If we are not doing the last items, update the final N value.
                 if (end < wk_end) {
                     n_end = (end - wk_start) * strategy::out_width();
                 }
                 // Set the buffer pointer
                 Troi *buffer = buffer_base +
                                (roundup(_args._Nsize, strategy::out_width()) * (multi * _Ktotal + k0)) +
                                (n_start * roundup(k_size, strategy::k_unroll()));
                 if (_args._Ksections > 1) {
                     // We need to insert padding at the end of each K section.
                     // The computation needed is a little delicate - the k0/kmax coordinates are expressed in
                     // terms of the full, padded, _Ktotal.
                     // But we need to transform each section with reference to the original, unpadded, input, letting the
                     // transform pad each section as needed.
                     // This is needed for computations below.
                     const unsigned int rounded_section_size = roundup(_args._Ksize, strategy::k_unroll());
                     // The expected output format is also an entire <out_width> columns interleaved, then the next set of
                     // columns, and so on.  This means, as we are breaking it up vertically, we have to do it one column at
                     // a time.
                     for (unsigned int x0 = n_start; x0 < n_end; x0 += strategy::out_width()) {
                         unsigned int xmax = std::min(x0 + strategy::out_width(), _args._Nsize);
                         // Track where we are and how much work is left.
                         unsigned int kpos  = k0;
                         unsigned int kleft = k_size;
                         while (kleft) {
                             // Which section are we in?  Based on the rounded-up section size.
                             unsigned int k_section_base = kpos / rounded_section_size;
                             // How far into the section are we?
                             unsigned int k_offset = kpos - (k_section_base * rounded_section_size);
                             // We will either copy the rest of this section, or to the end of the requested length.
                             unsigned int k_length = std::min(_args._Ksize - k_offset, kleft);
                             strat.transforms.PrepareB(buffer, B + (multi * B_multi_stride), ldb,
                                                       x0, xmax,
                                                       (k_section_base * _args._Ksize) + k_offset,               // K starting point - compute row to read based on our section and the true section length.
                                                       (k_section_base * _args._Ksize) + k_offset + k_length);   // K end point - starting point plus length computed above.
                             // We need to modify our position based on the ROUNDED version of what we just did.
                             unsigned int padded_length = roundup(k_length, strategy::k_unroll());
                             buffer += strategy::out_width() * padded_length;
                             kpos  += padded_length;
                             kleft -= padded_length;
                         }
                     }
                 } else {
                     // In the single K section case, can process the whole lot in one go.
                     strat.transforms.PrepareB(buffer, B + (multi * B_multi_stride), ldb,
                                               n_start, n_end, k0, std::min(kmax, _args._Ksize));
                 }
             }
         }
     }
References GemmArgs::_ci, GemmArgs::_Ksections, GemmArgs::_Ksize, GemmArgs::_nmulti, GemmArgs::_Nsize, arm_compute::mlgo::parser::end(), GemmHybridIndirect< strategy, To, Tr, OutputStage, SeparateQuantize, FixedFormat >::get_B_pretranspose_window_size(), arm_gemm::iceildiv(), GemmHybridIndirect< strategy, To, Tr, OutputStage, SeparateQuantize, FixedFormat >::requantize_bias(), arm_gemm::roundup(), and strategy.
Referenced by GemmHybridIndirect< strategy, To, Tr, OutputStage, SeparateQuantize, FixedFormat >::pretranspose_B_array().
requantize_bias()
void requantize_bias (void * in_buffer, const To * B, const int ldb, const int B_multi_stride) inline override virtual
Reimplemented from GemmCommon< To, Tr >.
Definition at line 621 of file gemm_hybrid_indirect.hpp.
{
         if (std::is_same<OutputStage, Requantize32>::value) {
             _col_bias = reinterpret_cast<int32_t *>(in_buffer);
             Requantize32 *qp_ptr = reinterpret_cast<Requantize32 *>(&_os);
             for (unsigned int i=0; i<_args._nmulti; i++) {
                 // The input is assumed not to have any padding between sections, so straightforward Ksize * Ksections computation gets the total size.
                 compute_col_sums(*qp_ptr, _args._Nsize, _args._Ksize * _args._Ksections, B + (i * B_multi_stride), ldb, _col_bias + (i * _args._Nsize), _args._Ksize * _args._Ksections, i, 0);
             }
         }
     }
References GemmArgs::_Ksections, GemmArgs::_Ksize, GemmArgs::_nmulti, GemmArgs::_Nsize, and arm_gemm::compute_col_sums().
Referenced by GemmHybridIndirect< strategy, To, Tr, OutputStage, SeparateQuantize, FixedFormat >::pretranspose_B_array_part().
set_convolution_parameters()
void set_convolution_parameters (ConvolutionParameters parms) inline override virtual
Reimplemented from IGemmCommon.
Definition at line 813 of file gemm_hybrid_indirect.hpp.
{
         assert(parms.input_channels == _args._Ksize);
         _convolver = std::unique_ptr<convolver<To>>(new convolver<To>(parms));
     }
References GemmArgs::_Ksize, and ConvolutionParameters::input_channels.
set_indirect_parameters()
void set_indirect_parameters (size_t string_len, const To *const *const * ptr) inline override virtual
Reimplemented from GemmCommon< To, Tr >.
Definition at line 808 of file gemm_hybrid_indirect.hpp.
{
         assert(string_len == _args._Ksize);
         _indirect_buf = ptr;
     }
References GemmArgs::_Ksize.
set_pretransposed_B_data()
void set_pretransposed_B_data (void * in_buffer) inline override virtual
Reimplemented from IGemmCommon.
Definition at line 740 of file gemm_hybrid_indirect.hpp.
{
         // Put the transposed data after the column sums - in non-transposing cases get_col_sum_size() == 0
         uintptr_t buffer_int = reinterpret_cast<uintptr_t>(in_buffer);
         _B_transposed = reinterpret_cast<Troi *>(buffer_int + get_col_sum_size());
         _col_bias = reinterpret_cast<int32_t *>(in_buffer);
     }
set_quantized_bias()
void set_quantized_bias (const int32_t * bias, size_t bias_multi_stride) inline override virtual
Reimplemented from IGemmCommon.
Definition at line 799 of file gemm_hybrid_indirect.hpp.
{
         if (std::is_same<OutputStage, Requantize32>::value) {
             Requantize32 *qp = reinterpret_cast<Requantize32 *>(&_os);
             qp->bias = bias;
             qp->bias_multi_stride = bias_multi_stride;
         }
     }
References Requantize32::bias, bias, and Requantize32::bias_multi_stride.
supports_dynamic_scheduling()
bool supports_dynamic_scheduling () const inline override virtual
Reimplemented from IGemmCommon.
Definition at line 422 of file gemm_hybrid_indirect.hpp.
{
         return true;
     }
The documentation for this class was generated from the following file:
src/core/NEON/kernels/arm_gemm/gemm_hybrid_indirect.hpp