Compute Library: ClComponentLogits1DMaxShiftExpSum Class Reference
ClComponentLogits1DMaxShiftExpSum Class Reference final
Component to calculate max-shifted exponentials and their sum.
#include <ClComponentLogits1DMaxShiftExpSum.h>
Public Types
using Attributes = SoftmaxAttributes
Attributes are a set of backend-agnostic parameters that define what a component does.
Public Types inherited from IGpuKernelComponent
using Properties = KernelProperties
Public Member Functions
ClComponentLogits1DMaxShiftExpSum (ComponentId id, const Properties &properties, const ArgumentPack< ITensorInfo > &tensors, const Attributes &attributes)
Constructor.
~ClComponentLogits1DMaxShiftExpSum () override
Destructor.
ClComponentLogits1DMaxShiftExpSum (const ClComponentLogits1DMaxShiftExpSum &component)=delete
Prevent instances of this class from being copy constructed.
ClComponentLogits1DMaxShiftExpSum & operator= (const ClComponentLogits1DMaxShiftExpSum &component)=delete
Prevent instances of this class from being copied.
ClComponentLogits1DMaxShiftExpSum (ClComponentLogits1DMaxShiftExpSum &&component)=default
Allow instances of this class to be move constructed.
ClComponentLogits1DMaxShiftExpSum & operator= (ClComponentLogits1DMaxShiftExpSum &&component)=default
Allow instances of this class to be moved.
const IGpuTemplateComponentWriter * template_writer () const override
Get template writer for the component.
GpuComponentType type () const override
Get component type.
Public Member Functions inherited from IGpuKernelComponent
IGpuKernelComponent (ComponentId id, const Properties &properties, const ArgumentPack< ITensorInfo > &tensors)
Constructor.
virtual ~IGpuKernelComponent ()
Destructor.
ComponentId id () const
Get component id.
ArgumentPack< ITensorInfo > tensors () const
Get tensor arguments.
Properties properties () const
Get properties.
virtual const IGpuCkwComponentDriver * ckw_component_driver () const
Static Public Member Functions
static Status validate (const Properties &properties, const ArgumentPack< ITensorInfo > &tensors, const Attributes &attributes)
Validate the component.
Detailed Description
Component to calculate max-shifted exponentials and their sum.
1D example: input: [x1, x2, ... , xn], shape: (1 x d)
Let max(x1...xn) = m
(output) sum: [exp(x1-m) + ... + exp(xn-m)], shape: (1 x 1) (output) dst: [exp(x1-m) ... exp(xn-m)], shape: (1 x d)
This component is used by the softmax operator. The subsequent operation normalizes dst with sum, therefore the max-shifting since exp(m) will be cancelled in numerator and denominator.
Definition at line 60 of file ClComponentLogits1DMaxShiftExpSum.h.
Member Typedef Documentation
Attributes
using Attributes = SoftmaxAttributes
Attributes are a set of backend-agnostic parameters that define what a component does.
Definition at line 64 of file ClComponentLogits1DMaxShiftExpSum.h.
Constructor & Destructor Documentation
ClComponentLogits1DMaxShiftExpSum() [1/3]
ClComponentLogits1DMaxShiftExpSum (ComponentId id, const Properties & properties, const ArgumentPack< ITensorInfo > & tensors, const Attributes & attributes)
Constructor.
Similar to ClComponentLogits1DMaxShiftExpSum::validate()
Definition at line 74 of file ClComponentLogits1DMaxShiftExpSum.cpp.
     : IGpuKernelComponent{id, properties, tensors},
       _component_writer{std::make_unique<ClTemplateLogits1DMaxShiftExpSum>(id, tensors, attributes)}
 {
 }
References IGpuKernelComponent::id(), IGpuKernelComponent::properties(), and IGpuKernelComponent::tensors().
~ClComponentLogits1DMaxShiftExpSum()
~ClComponentLogits1DMaxShiftExpSum () override
Destructor.
Definition at line 83 of file ClComponentLogits1DMaxShiftExpSum.cpp.
 {
 }
ClComponentLogits1DMaxShiftExpSum() [2/3]
ClComponentLogits1DMaxShiftExpSum (const ClComponentLogits1DMaxShiftExpSum & component) delete
Prevent instances of this class from being copy constructed.
ClComponentLogits1DMaxShiftExpSum() [3/3]
ClComponentLogits1DMaxShiftExpSum (ClComponentLogits1DMaxShiftExpSum && component) default
Allow instances of this class to be move constructed.
Member Function Documentation
operator=() [1/2]
ClComponentLogits1DMaxShiftExpSum& operator= (ClComponentLogits1DMaxShiftExpSum && component) default
Allow instances of this class to be moved.
operator=() [2/2]
ClComponentLogits1DMaxShiftExpSum& operator= (const ClComponentLogits1DMaxShiftExpSum & component) delete
Prevent instances of this class from being copied.
template_writer()
const IGpuTemplateComponentWriter * template_writer () const override virtual
Get template writer for the component.
Reimplemented from IGpuKernelComponent.
Definition at line 87 of file ClComponentLogits1DMaxShiftExpSum.cpp.
 {
     return _component_writer.get();
 }
type()
GpuComponentType type () const inline override virtual
Get component type.
Implements IGpuKernelComponent.
Definition at line 118 of file ClComponentLogits1DMaxShiftExpSum.h.
     {
         return GpuComponentType::Unfusable;
     }
References arm_compute::experimental::dynamic_fusion::Unfusable.
validate()
Status validate (const Properties & properties, const ArgumentPack< ITensorInfo > & tensors, const Attributes & attributes) static
Validate the component.
Parameters
[in] properties Component properties Properties
[in] tensors Tensor arguments to the component
[in] attributes Component attributes Attributes
Returns
Status Validation results
Tensor argument names:
ACL_SRC_0: Input
ACL_DST_0: Output
ACL_DST_1: Output
Tensor argument constness:
ACL_SRC_0: Const
ACL_DST_0: Const
ACL_DST_1: Const
Valid data layouts:
All
Valid data type configurations:
ACL_SRC_0 ACL_DST_0 ACL_DST_1
F16 F16 F16
F32 F32 F32
Definition at line 41 of file ClComponentLogits1DMaxShiftExpSum.cpp.
 {
     ARM_COMPUTE_UNUSED(properties, attributes);
     const ITensorInfo *src = tensors.get_const_tensor(TensorType::ACL_SRC_0);
     const ITensorInfo *sum = tensors.get_const_tensor(TensorType::ACL_DST_0);
     const ITensorInfo *dst = tensors.get_const_tensor(TensorType::ACL_DST_1);
     ARM_COMPUTE_RETURN_ERROR_ON_NULLPTR(src);
     ARM_COMPUTE_RETURN_ERROR_ON_NULLPTR(sum);
     ARM_COMPUTE_RETURN_ERROR_ON_NULLPTR(dst);
     // 1. Check validity
     // All tensor infos are initialized
     ARM_COMPUTE_RETURN_ERROR_ON(src->tensor_shape().total_size() == 0);
     ARM_COMPUTE_RETURN_ERROR_ON(sum->tensor_shape().total_size() == 0);
     ARM_COMPUTE_RETURN_ERROR_ON(dst->tensor_shape().total_size() == 0);
     // Check for mismatches in shapes and data types
     ARM_COMPUTE_RETURN_ERROR_ON_MISMATCHING_DATA_TYPES(src, dst, sum);
     ARM_COMPUTE_RETURN_ERROR_ON_MISMATCHING_SHAPES(src, dst);
     // Device requirements are met
     ARM_COMPUTE_RETURN_ERROR_ON_F16_UNSUPPORTED(src);
     // 2. Check support level
     ARM_COMPUTE_RETURN_ERROR_ON_DATA_TYPE_CHANNEL_NOT_IN(src, 1, DataType::F16, DataType::F32);
     return Status{};
 }
References arm_compute::ACL_DST_0, arm_compute::ACL_DST_1, arm_compute::ACL_SRC_0, ARM_COMPUTE_RETURN_ERROR_ON, ARM_COMPUTE_RETURN_ERROR_ON_DATA_TYPE_CHANNEL_NOT_IN, ARM_COMPUTE_RETURN_ERROR_ON_F16_UNSUPPORTED, ARM_COMPUTE_RETURN_ERROR_ON_MISMATCHING_DATA_TYPES, ARM_COMPUTE_RETURN_ERROR_ON_MISMATCHING_SHAPES, ARM_COMPUTE_RETURN_ERROR_ON_NULLPTR, ARM_COMPUTE_UNUSED, arm_compute::test::validation::dst, arm_compute::F16, arm_compute::F32, IGpuKernelComponent::properties(), arm_compute::test::validation::src, ITensorInfo::tensor_shape(), IGpuKernelComponent::tensors(), and TensorShape::total_size().
Referenced by GpuSoftmax::is_supported_op().
The documentation for this class was generated from the following files:
src/dynamic_fusion/sketch/gpu/components/cl/ClComponentLogits1DMaxShiftExpSum.h
src/dynamic_fusion/sketch/gpu/components/cl/ClComponentLogits1DMaxShiftExpSum.cpp