Compute Library: NESynthetizeFunctionWithZeroConstantKernelBorder< K > Class Template Reference
NESynthetizeFunctionWithZeroConstantKernelBorder< K > Class Template Reference
As above but this also setups a Zero border on the input tensor of the kernel's bordersize.
#include <Helper.h>
Public Member Functions
template<typename T , typename... Args>
void configure (T first, Args &&... args)
Configure the kernel.
void run (ITensorPack &tensors)
Run the kernels contained in the function.
Public Member Functions inherited from INEOperator
INEOperator (IRuntimeContext *ctx=nullptr)
Constructor.
INEOperator (const INEOperator &)=delete
Prevent instances of this class from being copied (As this class contains pointers)
INEOperator (INEOperator &&)=default
Default move constructor.
INEOperator & operator= (const INEOperator &)=delete
Prevent instances of this class from being copied (As this class contains pointers)
INEOperator & operator= (INEOperator &&)=default
Default move assignment operator.
~INEOperator ()
Default destructor.
void prepare (ITensorPack &constants) override
Prepare the function for executing.
MemoryRequirements workspace () const override
Return the memory requirements required by the workspace.
Public Member Functions inherited from IOperator
virtual ~IOperator ()=default
Destructor.
Detailed Description
template<typename K>
class arm_compute::test::NESynthetizeFunctionWithZeroConstantKernelBorder< K >
As above but this also setups a Zero border on the input tensor of the kernel's bordersize.
Definition at line 109 of file Helper.h.
Member Function Documentation
configure()
void configure (T first, Args &&... args) inline
Configure the kernel.
Parameters
[in] first First configuration argument.
[in] args Rest of the configuration arguments.
Definition at line 118 of file Helper.h.
     {
         auto k = std::make_unique<K>();
         k->configure(first, std::forward<Args>(args)...);
         _kernel = std::move(k);
         auto b = std::make_unique<NEFillBorderKernel>();
         b->configure(first, BorderSize(_kernel->border_size()), BorderMode::CONSTANT, PixelValue());
         _border_handler = std::move(b);
     }
References GemmTuner::args, arm_compute::test::validation::b, and arm_compute::CONSTANT.
run()
void run (ITensorPack & tensors) inline virtual
Run the kernels contained in the function.
Parameters
[in] tensors Vector that contains the tensors to operate on.
Reimplemented from INEOperator.
Definition at line 129 of file Helper.h.
     {
         NEScheduler::get().schedule(_border_handler.get(), Window::DimZ);
         NEScheduler::get().schedule_op(_kernel.get(), Window::DimY, _kernel->window(), tensors);
     }
References Window::DimY, Window::DimZ, Scheduler::get(), IScheduler::schedule(), and IScheduler::schedule_op().
The documentation for this class was generated from the following file:
tests/NEON/Helper.h