Compute Library: IGpuKernelComponent Class Reference
IGpuKernelComponent Class Reference abstract
An abstract interface of a component.
#include <IGpuKernelComponent.h>
Public Types
using Properties = KernelProperties
Public Member Functions
IGpuKernelComponent (ComponentId id, const Properties &properties, const ArgumentPack< ITensorInfo > &tensors)
Constructor.
virtual ~IGpuKernelComponent ()
Destructor.
ComponentId id () const
Get component id.
ArgumentPack< ITensorInfo > tensors () const
Get tensor arguments.
Properties properties () const
Get properties.
virtual const IGpuTemplateComponentWriter * template_writer () const
Get writer for the component.
virtual const IGpuCkwComponentDriver * ckw_component_driver () const
virtual GpuComponentType type () const =0
Get component type.
Detailed Description
An abstract interface of a component.
It enables manipulation by the component graph for purposes like fusion
Definition at line 67 of file IGpuKernelComponent.h.
Member Typedef Documentation
Properties
using Properties = KernelProperties
Definition at line 70 of file IGpuKernelComponent.h.
Constructor & Destructor Documentation
IGpuKernelComponent()
IGpuKernelComponent (ComponentId id, const Properties & properties, const ArgumentPack< ITensorInfo > & tensors) inline
Constructor.
Parameters
[in] id Component id
[in] properties Kernel component properties
[in] tensors Tensor arguments to the components
Definition at line 79 of file IGpuKernelComponent.h.
         : _id{id}, _properties{properties}, _tensors{tensors}
     {
     }
~IGpuKernelComponent()
virtual ~IGpuKernelComponent () inline virtual
Destructor.
Definition at line 84 of file IGpuKernelComponent.h.
     {
     }
Member Function Documentation
ckw_component_driver()
virtual const IGpuCkwComponentDriver* ckw_component_driver () const inline virtual
Reimplemented in ClComponentMatMul.
Definition at line 107 of file IGpuKernelComponent.h.
     {
         return nullptr;
     }
Referenced by GpuCkwActivation::write_component_code(), GpuCkwCast::write_component_code(), GpuCkwElementwiseBinary::write_component_code(), GpuCkwPool2d::write_component_code(), GpuCkwDepthwiseConv2d::write_component_code(), GpuCkwDirectConv2d::write_component_code(), and GpuCkwMatMul::write_component_code().
id()
ComponentId id () const inline
Get component id.
Definition at line 88 of file IGpuKernelComponent.h.
     {
         return _id;
     }
Referenced by ClComponentActivation::ClComponentActivation(), ClComponentCast::ClComponentCast(), ClComponentDepthwiseConv2d::ClComponentDepthwiseConv2d(), ClComponentDirectConv2d::ClComponentDirectConv2d(), ClComponentElementwiseBinary::ClComponentElementwiseBinary(), ClComponentLogits1DMaxShiftExpSum::ClComponentLogits1DMaxShiftExpSum(), ClComponentLogits1DNorm::ClComponentLogits1DNorm(), ClComponentPool2d::ClComponentPool2d(), ClComponentReshape::ClComponentReshape(), ClComponentResize::ClComponentResize(), ClComponentStore::ClComponentStore(), ClTemplateCast::get_component_code(), ClTemplateElementwiseBinary::get_component_code(), ClTemplateActivation::get_component_code(), and ClTemplateCast::get_tag_lut().
properties()
Properties properties () const inline
Get properties.
Definition at line 98 of file IGpuKernelComponent.h.
     {
         return _properties;
     }
Referenced by GpuKernelComponentGroup::add_component(), ClComponentActivation::ClComponentActivation(), ClComponentCast::ClComponentCast(), ClComponentDepthwiseConv2d::ClComponentDepthwiseConv2d(), ClComponentDirectConv2d::ClComponentDirectConv2d(), ClComponentElementwiseBinary::ClComponentElementwiseBinary(), ClComponentLogits1DMaxShiftExpSum::ClComponentLogits1DMaxShiftExpSum(), ClComponentLogits1DNorm::ClComponentLogits1DNorm(), ClComponentPool2d::ClComponentPool2d(), ClComponentReshape::ClComponentReshape(), ClComponentResize::ClComponentResize(), ClComponentStore::ClComponentStore(), ClComponentStore::validate(), ClComponentActivation::validate(), ClComponentPool2d::validate(), ClComponentResize::validate(), ClComponentLogits1DNorm::validate(), ClComponentLogits1DMaxShiftExpSum::validate(), ClComponentCast::validate(), ClComponentDirectConv2d::validate(), and ClComponentDepthwiseConv2d::validate().
template_writer()
virtual const IGpuTemplateComponentWriter* template_writer () const inline virtual
Get writer for the component.
Reimplemented in ClComponentDepthwiseConv2d, ClComponentDirectConv2d, ClComponentCast, ClComponentPool2d, ClComponentLogits1DMaxShiftExpSum, ClComponentResize, ClComponentLogits1DNorm, ClComponentActivation, ClComponentElementwiseBinary, ClComponentStore, and ClComponentReshape.
Definition at line 103 of file IGpuKernelComponent.h.
     {
         return nullptr;
     }
Referenced by ClTemplateCast::get_build_options(), ClTemplateLogits1DNorm::get_build_options(), ClTemplateReshape::get_build_options(), ClTemplateDirectConv2d::get_build_options(), ClTemplateResize::get_build_options(), ClTemplatePool2d::get_build_options(), and ClTemplateActivation::get_build_options().
tensors()
ArgumentPack<ITensorInfo> tensors () const inline
Get tensor arguments.
Definition at line 93 of file IGpuKernelComponent.h.
     {
         return _tensors;
     }
Referenced by GpuKernelComponentGroup::add_component(), ClComponentActivation::ClComponentActivation(), ClComponentCast::ClComponentCast(), ClComponentDepthwiseConv2d::ClComponentDepthwiseConv2d(), ClComponentDirectConv2d::ClComponentDirectConv2d(), ClComponentElementwiseBinary::ClComponentElementwiseBinary(), ClComponentLogits1DMaxShiftExpSum::ClComponentLogits1DMaxShiftExpSum(), ClComponentLogits1DNorm::ClComponentLogits1DNorm(), ClComponentPool2d::ClComponentPool2d(), ClComponentReshape::ClComponentReshape(), ClComponentResize::ClComponentResize(), ClComponentStore::ClComponentStore(), ClComponentReshape::validate(), ClComponentStore::validate(), ClComponentActivation::validate(), ClComponentElementwiseBinary::validate(), ClComponentPool2d::validate(), ClComponentResize::validate(), ClComponentLogits1DNorm::validate(), ClComponentLogits1DMaxShiftExpSum::validate(), ClComponentCast::validate(), ClComponentDirectConv2d::validate(), and ClComponentDepthwiseConv2d::validate().
type()
virtual GpuComponentType type () const pure virtual
Get component type.
Implemented in ClComponentDepthwiseConv2d, ClComponentDirectConv2d, ClComponentCast, ClComponentPool2d, ClComponentResize, ClComponentLogits1DMaxShiftExpSum, ClComponentActivation, ClComponentElementwiseBinary, ClComponentLogits1DNorm, ClComponentMatMul, ClComponentStore, and ClComponentReshape.
Referenced by GpuKernelComponentGroup::add_component().
The documentation for this class was generated from the following file:
src/dynamic_fusion/sketch/gpu/components/IGpuKernelComponent.h