Compute Library: ICLKernel Class Reference
ICLKernel Class Reference
Common interface for all the OpenCL kernels.
#include <ICLKernel.h>
Public Member Functions
ICLKernel ()
Constructor.
cl::Kernel & kernel ()
Returns a reference to the OpenCL kernel of this object.
CLKernelType type () const
Returns the CL kernel type.
template<typename T >
void add_1D_array_argument (unsigned int &idx, const ICLArray< T > *array, const Strides &strides, unsigned int num_dimensions, const Window &window)
Add the passed 1D array's parameters to the object's kernel's arguments starting from the index idx.
void add_1D_tensor_argument (unsigned int &idx, const ICLTensor *tensor, const Window &window)
Add the passed 1D tensor's parameters to the object's kernel's arguments starting from the index idx.
void add_1D_tensor_argument_if (bool cond, unsigned int &idx, const ICLTensor *tensor, const Window &window)
Add the passed 1D tensor's parameters to the object's kernel's arguments starting from the index idx if the condition is true.
void add_2D_tensor_argument (unsigned int &idx, const ICLTensor *tensor, const Window &window)
Add the passed 2D tensor's parameters to the object's kernel's arguments starting from the index idx.
void add_2D_tensor_argument_if (bool cond, unsigned int &idx, const ICLTensor *tensor, const Window &window)
Add the passed 2D tensor's parameters to the object's kernel's arguments starting from the index idx if the condition is true.
void add_3D_tensor_argument (unsigned int &idx, const ICLTensor *tensor, const Window &window)
Add the passed 3D tensor's parameters to the object's kernel's arguments starting from the index idx.
void add_4D_tensor_argument (unsigned int &idx, const ICLTensor *tensor, const Window &window)
Add the passed 4D tensor's parameters to the object's kernel's arguments starting from the index idx.
void add_5D_tensor_argument (unsigned int &idx, const ICLTensor *tensor, const Window &window)
Add the passed 5D tensor's parameters to the object's kernel's arguments starting from the index idx.
void add_3d_tensor_nhw_argument (unsigned int &idx, const ICLTensor *tensor)
Add the passed NHW 3D tensor's parameters to the object's kernel's arguments by passing strides, dimensions and the offset to the first valid element in bytes.
void add_4d_tensor_nhwc_argument (unsigned int &idx, const ICLTensor *tensor)
Add the passed NHWC 4D tensor's parameters to the object's kernel's arguments by passing strides, dimensions and the offset to the first valid element in bytes.
virtual void run (const Window &window, cl::CommandQueue &queue)
Enqueue the OpenCL kernel to process the given window on the passed OpenCL command queue.
virtual void run_op (ITensorPack &tensors, const Window &window, cl::CommandQueue &queue)
Enqueue the OpenCL kernel to process the given window on the passed OpenCL command queue.
template<typename T >
void add_argument (unsigned int &idx, T value)
Add the passed parameters to the object's kernel's arguments starting from the index idx.
void set_lws_hint (const cl::NDRange &lws_hint)
Set the Local-Workgroup-Size hint.
cl::NDRange lws_hint () const
Return the Local-Workgroup-Size hint.
void set_wbsm_hint (const cl_int &wbsm_hint)
Set the workgroup batch size modifier hint.
cl_int wbsm_hint () const
Return the workgroup batch size modifier hint.
const std::string & config_id () const
Get the configuration ID.
void set_target (GPUTarget target)
Set the targeted GPU architecture.
void set_target (cl::Device &device)
Set the targeted GPU architecture according to the CL device.
GPUTarget get_target () const
Get the targeted GPU architecture.
size_t get_max_workgroup_size ()
Get the maximum workgroup size for the device the CLKernelLibrary uses.
cl::NDRange get_cached_gws () const
Get the cached gws used to enqueue this kernel.
void cache_gws (const cl::NDRange &gws)
Cache the latest gws used to enqueue this kernel.
template<unsigned int dimension_size>
void add_tensor_argument (unsigned &idx, const ICLTensor *tensor, const Window &window)
template<typename T , unsigned int dimension_size>
void add_array_argument (unsigned &idx, const ICLArray< T > *array, const Strides &strides, unsigned int num_dimensions, const Window &window)
Add the passed array's parameters to the object's kernel's arguments starting from the index idx.
Public Member Functions inherited from IKernel
IKernel ()
Constructor.
virtual ~IKernel ()=default
Destructor.
virtual bool is_parallelisable () const
Indicates whether or not the kernel is parallelisable.
virtual BorderSize border_size () const
The size of the border for that kernel.
const Window & window () const
The maximum window the kernel can be executed on.
bool is_window_configured () const
Function to check if the embedded window of this kernel has been configured.
Static Public Member Functions
constexpr static unsigned int num_arguments_per_3d_tensor_nhw ()
Returns the number of arguments enqueued per NHW 3D Tensor object.
constexpr static unsigned int num_arguments_per_4d_tensor_nhwc ()
Returns the number of arguments enqueued per NHWC 4D Tensor object.
constexpr static unsigned int num_arguments_per_1D_array ()
Returns the number of arguments enqueued per 1D array object.
constexpr static unsigned int num_arguments_per_1D_tensor ()
Returns the number of arguments enqueued per 1D tensor object.
constexpr static unsigned int num_arguments_per_2D_tensor ()
Returns the number of arguments enqueued per 2D tensor object.
constexpr static unsigned int num_arguments_per_3D_tensor ()
Returns the number of arguments enqueued per 3D tensor object.
constexpr static unsigned int num_arguments_per_4D_tensor ()
Returns the number of arguments enqueued per 4D tensor object.
static cl::NDRange gws_from_window (const Window &window, bool use_dummy_work_items)
Get the global work size given an execution window.
Detailed Description
Common interface for all the OpenCL kernels.
Definition at line 67 of file ICLKernel.h.
Constructor & Destructor Documentation
ICLKernel()
ICLKernel () inline
Constructor.
Definition at line 137 of file ICLKernel.h.
         : _kernel(nullptr),
           _target(GPUTarget::MIDGARD),
           _config_id(arm_compute::default_config_id),
           _max_workgroup_size(0),
           _type(CLKernelType::UNKNOWN),
           _tuning_params_hint(),
           _cached_gws(cl::NullRange)
     {
     }
References arm_compute::MIDGARD.
Member Function Documentation
add_1D_array_argument()
void add_1D_array_argument (unsigned int & idx, const ICLArray< T > * array, const Strides & strides, unsigned int num_dimensions, const Window & window) inline
Add the passed 1D array's parameters to the object's kernel's arguments starting from the index idx.
Parameters
[in,out] idx Index at which to start adding the array's arguments. Will be incremented by the number of kernel arguments set.
[in] array Array to set as an argument of the object's kernel.
[in] strides Strides object containing stride of each dimension in bytes.
[in] num_dimensions Number of dimensions of the array.
[in] window Window the kernel will be executed on.
Definition at line 172 of file ICLKernel.h.
     {
         add_array_argument<T, 1>(idx, array, strides, num_dimensions, window);
     }
References IKernel::window().
add_1D_tensor_argument()
void add_1D_tensor_argument (unsigned int & idx, const ICLTensor * tensor, const Window & window) inline
Add the passed 1D tensor's parameters to the object's kernel's arguments starting from the index idx.
Parameters
[in,out] idx Index at which to start adding the tensor's arguments. Will be incremented by the number of kernel arguments set.
[in] tensor Tensor to set as an argument of the object's kernel.
[in] window Window the kernel will be executed on.
Definition at line 186 of file ICLKernel.h.
     {
         add_tensor_argument<1>(idx, tensor, window);
     }
References tensor, and IKernel::window().
Referenced by ICLKernel::add_1D_tensor_argument_if(), CLComputeAllAnchorsKernel::run(), CLSelectKernel::run(), CLQLSTMLayerNormalizationKernel::run(), CLRangeKernel::run(), CLFFTDigitReverseKernel::run(), CLNormalizePlanarYUVLayerKernel::run(), CLReverseKernel::run(), CLReductionOperationKernel::run(), CLBoundingBoxTransformKernel::run(), CLDeconvolutionReshapeOutputKernel::run(), CLDepthwiseConvolutionLayerNativeKernel::run(), CLBatchNormalizationLayerKernel::run(), CLBatchToSpaceLayerKernel::run(), CLFuseBatchNormalizationKernel::run(), ClTransposedConvolutionKernel::run_op(), ClGemmLowpQuantizeDownInt32ScaleByFixedPointKernel::run_op(), ClGemmLowpQuantizeDownInt32ScaleByFloatKernel::run_op(), ClGemmLowpQuantizeDownInt32ScaleKernel::run_op(), ClIndirectConv2dKernel::run_op(), ClDirectConv3dKernel::run_op(), and ClDirectConv2dKernel::run_op().
add_1D_tensor_argument_if()
void add_1D_tensor_argument_if (bool cond, unsigned int & idx, const ICLTensor * tensor, const Window & window) inline
Add the passed 1D tensor's parameters to the object's kernel's arguments starting from the index idx if the condition is true.
Parameters
[in] cond Condition to check
[in,out] idx Index at which to start adding the tensor's arguments. Will be incremented by the number of kernel arguments set.
[in] tensor Tensor to set as an argument of the object's kernel.
[in] window Window the kernel will be executed on.
Definition at line 197 of file ICLKernel.h.
     {
         if (cond)
         {
             add_1D_tensor_argument(idx, tensor, window);
         }
     }
References ICLKernel::add_1D_tensor_argument(), tensor, and IKernel::window().
Referenced by CLSpaceToBatchLayerKernel::run(), ClGemmLowpOffsetContributionKernel::run_op(), and ClGemmLowpOffsetContributionOutputStageKernel::run_op().
add_2D_tensor_argument()
void add_2D_tensor_argument (unsigned int & idx, const ICLTensor * tensor, const Window & window) inline
Add the passed 2D tensor's parameters to the object's kernel's arguments starting from the index idx.
Parameters
[in,out] idx Index at which to start adding the tensor's arguments. Will be incremented by the number of kernel arguments set.
[in] tensor Tensor to set as an argument of the object's kernel.
[in] window Window the kernel will be executed on.
Definition at line 210 of file ICLKernel.h.
     {
         add_tensor_argument<2>(idx, tensor, window);
     }
References tensor, and IKernel::window().
Referenced by ICLKernel::add_2D_tensor_argument_if(), ICLSimple2DKernel::run(), CLBitwiseKernel::run(), CLQLSTMLayerNormalizationKernel::run(), CLROIPoolingLayerKernel::run(), CLMeanStdDevNormalizationKernel::run(), CLArgMinMaxLayerKernel::run(), CLL2NormalizeLayerKernel::run(), CLPriorBoxLayerKernel::run(), CLBoundingBoxTransformKernel::run(), CLROIAlignLayerKernel::run(), ClScaleKernel::run_op(), ClConvertFullyConnectedWeightsKernel::run_op(), ClGemmLowpMatrixMultiplyNativeKernel::run_op(), ClGemmMatrixMultiplyNativeKernel::run_op(), ClGemmLowpMatrixAReductionKernel::run_op(), ClIm2ColKernel::run_op(), ClGemmMatrixMultiplyReshapedOnlyRhsKernel::run_op(), ClGemmMatrixMultiplyReshapedKernel::run_op(), and ClGemmLowpMatrixBReductionKernel::run_op().
add_2D_tensor_argument_if()
void add_2D_tensor_argument_if (bool cond, unsigned int & idx, const ICLTensor * tensor, const Window & window) inline
Add the passed 2D tensor's parameters to the object's kernel's arguments starting from the index idx if the condition is true.
Parameters
[in] cond Condition to check
[in,out] idx Index at which to start adding the tensor's arguments. Will be incremented by the number of kernel arguments set.
[in] tensor Tensor to set as an argument of the object's kernel.
[in] window Window the kernel will be executed on.
Definition at line 221 of file ICLKernel.h.
     {
         if (cond)
         {
             add_2D_tensor_argument(idx, tensor, window);
         }
     }
References ICLKernel::add_2D_tensor_argument(), tensor, and IKernel::window().
Referenced by CLMeanStdDevNormalizationKernel::run(), CLSpaceToBatchLayerKernel::run(), ClGemmLowpOffsetContributionKernel::run_op(), ClGemmLowpOffsetContributionOutputStageKernel::run_op(), ClGemmMatrixMultiplyReshapedOnlyRhsKernel::run_op(), and ClGemmMatrixMultiplyReshapedKernel::run_op().
add_3D_tensor_argument()
void add_3D_tensor_argument (unsigned int & idx, const ICLTensor * tensor, const Window & window) inline
Add the passed 3D tensor's parameters to the object's kernel's arguments starting from the index idx.
Parameters
[in,out] idx Index at which to start adding the tensor's arguments. Will be incremented by the number of kernel arguments set.
[in] tensor Tensor to set as an argument of the object's kernel.
[in] window Window the kernel will be executed on.
Definition at line 234 of file ICLKernel.h.
     {
         add_tensor_argument<3>(idx, tensor, window);
     }
References tensor, and IKernel::window().
Referenced by ICLSimple3DKernel::run(), CLDepthToSpaceLayerKernel::run(), CLSpaceToDepthLayerKernel::run(), CLInstanceNormalizationLayerKernel::run(), CLDeconvolutionLayerUpsampleKernel::run(), CLFFTScaleKernel::run(), CLSelectKernel::run(), CLNormalizationLayerKernel::run(), CLReorgLayerKernel::run(), CLMaxUnpoolingLayerKernel::run(), CLROIPoolingLayerKernel::run(), CLComparisonKernel::run(), CLFFTDigitReverseKernel::run(), CLNormalizePlanarYUVLayerKernel::run(), CLReductionOperationKernel::run(), CLFFTRadixStageKernel::run(), CLArgMinMaxLayerKernel::run(), CLL2NormalizeLayerKernel::run(), CLPadLayerKernel::run(), CLFillBorderKernel::run(), CLROIAlignLayerKernel::run(), CLDeconvolutionReshapeOutputKernel::run(), CLBatchNormalizationLayerKernel::run(), CLComputeMeanVariance::run(), CLBatchToSpaceLayerKernel::run(), CLFuseBatchNormalizationKernel::run(), CLSpaceToBatchLayerKernel::run(), ClElementwiseKernel::run_op(), ClDequantizeKernel::run_op(), ClFloorKernel::run_op(), ClReshapeKernel::run_op(), ClTransposeKernel::run_op(), ClCopyKernel::run_op(), ClElementWiseUnaryKernel::run_op(), ClFillKernel::run_op(), ClQuantizeKernel::run_op(), ClDepthConcatenateKernel::run_op(), ClBatchConcatenateKernel::run_op(), ClActivationKernel::run_op(), ClWinogradInputTransformKernel::run_op(), ClCastKernel::run_op(), ClCropKernel::run_op(), ClGemmLowpQuantizeDownInt32ScaleByFixedPointKernel::run_op(), ClGemmLowpQuantizeDownInt32ScaleByFloatKernel::run_op(), ClGemmLowpQuantizeDownInt32ScaleKernel::run_op(), ClCol2ImKernel::run_op(), ClGemmLowpOffsetContributionKernel::run_op(), ClGemmLowpMatrixAReductionKernel::run_op(), ClDirectConv2dKernel::run_op(), ClGemmLowpOffsetContributionOutputStageKernel::run_op(), ClMulKernel::run_op(), CLFillBorderKernel::run_op(), ClIm2ColKernel::run_op(), ClGemmLowpMatrixBReductionKernel::run_op(), and ClComplexMulKernel::run_op().
add_3d_tensor_nhw_argument()
void add_3d_tensor_nhw_argument (unsigned int & idx, const ICLTensor * tensor)
Add the passed NHW 3D tensor's parameters to the object's kernel's arguments by passing strides, dimensions and the offset to the first valid element in bytes.
Parameters
[in,out] idx Index at which to start adding the tensor's arguments. Will be incremented by the number of kernel arguments set.
[in] tensor Tensor to set as an argument of the object's kernel.
Definition at line 120 of file ICLKernel.cpp.
 {
     ARM_COMPUTE_ERROR_ON(tensor == nullptr);
     const ITensorInfo *info = tensor->info();
     ARM_COMPUTE_ERROR_ON(info == nullptr);
     const Strides &strides = info->strides_in_bytes();
     // Tensor poniter
     _kernel.setArg(idx++, tensor->cl_buffer());
     // Add stride_y, stride_z
     _kernel.setArg<cl_uint>(idx++, strides[1]);
     _kernel.setArg<cl_uint>(idx++, strides[2]);
     // Tensor dimensions
     _kernel.setArg<cl_uint>(idx++, info->dimension(0));
     _kernel.setArg<cl_uint>(idx++, info->dimension(1));
     _kernel.setArg<cl_uint>(idx++, info->dimension(2));
     // Offset of first element
     unsigned int offset_first_element = info->offset_first_element_in_bytes();
     _kernel.setArg<cl_uint>(idx++, offset_first_element);
 }
References ARM_COMPUTE_ERROR_ON, arm_compute::test::validation::info, and tensor.
Referenced by ClMatMulLowpNativeMMULKernel::run_op(), ClGemmReshapeLhsMatrixKernel::run_op(), ClMatMulNativeKernel::run_op(), ClMatMulLowpNativeKernel::run_op(), ClGemmReshapeRhsMatrixKernel::run_op(), ClGemmMatrixMultiplyReshapedOnlyRhsMMULKernel::run_op(), and ClMatMulNativeMMULKernel::run_op().
add_4D_tensor_argument()
void add_4D_tensor_argument (unsigned int & idx, const ICLTensor * tensor, const Window & window) inline
Add the passed 4D tensor's parameters to the object's kernel's arguments starting from the index idx.
Parameters
[in,out] idx Index at which to start adding the tensor's arguments. Will be incremented by the number of kernel arguments set.
[in] tensor Tensor to set as an argument of the object's kernel.
[in] window Window the kernel will be executed on.
Definition at line 244 of file ICLKernel.h.
     {
         add_tensor_argument<4>(idx, tensor, window);
     }
References tensor, and IKernel::window().
Referenced by CLChannelShuffleLayerKernel::run(), CLDepthToSpaceLayerKernel::run(), CLSpaceToDepthLayerKernel::run(), CLInstanceNormalizationLayerKernel::run(), CLTileKernel::run(), CLGatherKernel::run(), CLReverseKernel::run(), CLArgMinMaxLayerKernel::run(), CLStackLayerKernel::run(), CLComputeMeanVariance::run(), CLBatchToSpaceLayerKernel::run(), CLSpaceToBatchLayerKernel::run(), ClWidthConcatenate2TensorsKernel::run_op(), ClHeightConcatenateKernel::run_op(), ClWidthConcatenateKernel::run_op(), ClPermuteKernel::run_op(), ClWidthConcatenate4TensorsKernel::run_op(), ClWinogradInputTransformKernel::run_op(), ClCol2ImKernel::run_op(), CLStridedSliceKernel::run_op(), and ClDirectConv3dKernel::run_op().
add_4d_tensor_nhwc_argument()
void add_4d_tensor_nhwc_argument (unsigned int & idx, const ICLTensor * tensor)
Add the passed NHWC 4D tensor's parameters to the object's kernel's arguments by passing strides, dimensions and the offset to the first valid element in bytes.
Parameters
[in,out] idx Index at which to start adding the tensor's arguments. Will be incremented by the number of kernel arguments set.
[in] tensor Tensor to set as an argument of the object's kernel.
Definition at line 145 of file ICLKernel.cpp.
 {
     ARM_COMPUTE_ERROR_ON(tensor == nullptr);
     const ITensorInfo *info = tensor->info();
     ARM_COMPUTE_ERROR_ON(info == nullptr);
     const Strides &strides = info->strides_in_bytes();
     // Tensor poniter
     _kernel.setArg(idx++, tensor->cl_buffer());
     // Add stride_y, stride_z and stride_w
     _kernel.setArg<cl_uint>(idx++, strides[1]);
     _kernel.setArg<cl_uint>(idx++, strides[2]);
     _kernel.setArg<cl_uint>(idx++, strides[3]);
     // Tensor dimensions
     _kernel.setArg<cl_uint>(idx++, info->dimension(0));
     _kernel.setArg<cl_uint>(idx++, info->dimension(1));
     _kernel.setArg<cl_uint>(idx++, info->dimension(2));
     _kernel.setArg<cl_uint>(idx++, info->dimension(3));
     // Offset of first element
     unsigned int offset_first_element = info->offset_first_element_in_bytes();
     _kernel.setArg<cl_uint>(idx++, offset_first_element);
 }
References ARM_COMPUTE_ERROR_ON, arm_compute::test::validation::info, and tensor.
Referenced by CLDepthwiseConvolutionLayerNativeKernel::run(), ClScaleKernel::run_op(), ClTransposedConvolutionKernel::run_op(), ClIndirectConv2dAddressPrecalculationKernel::run_op(), ClIndirectConv2dKernel::run_op(), and ClDirectConv2dKernel::run_op().
add_5D_tensor_argument()
void add_5D_tensor_argument (unsigned int & idx, const ICLTensor * tensor, const Window & window) inline
Add the passed 5D tensor's parameters to the object's kernel's arguments starting from the index idx.
Parameters
[in,out] idx Index at which to start adding the tensor's arguments. Will be incremented by the number of kernel arguments set.
[in] tensor Tensor to set as an argument of the object's kernel.
[in] window Window the kernel will be executed on.
Definition at line 254 of file ICLKernel.h.
     {
         add_tensor_argument<5>(idx, tensor, window);
     }
References tensor, and IKernel::window().
add_argument()
void add_argument (unsigned int & idx, T value) inline
Add the passed parameters to the object's kernel's arguments starting from the index idx.
Parameters
[in,out] idx Index at which to start adding the arguments. Will be incremented by the number of kernel arguments set.
[in] value Value to set as an argument of the object's kernel.
Definition at line 362 of file ICLKernel.h.
     {
         _kernel.setArg(idx++, value);
     }
Referenced by CLDepthToSpaceLayerKernel::run(), CLSpaceToDepthLayerKernel::run(), CLBatchToSpaceLayerKernel::run(), CLSpaceToBatchLayerKernel::run(), and ClCropKernel::run_op().
add_array_argument()
void add_array_argument (unsigned & idx, const ICLArray< T > * array, const Strides & strides, unsigned int num_dimensions, const Window & window)
Add the passed array's parameters to the object's kernel's arguments starting from the index idx.
Parameters
[in,out] idx Index at which to start adding the array's arguments. Will be incremented by the number of kernel arguments set.
[in] array Array to set as an argument of the object's kernel.
[in] strides Strides object containing stride of each dimension in bytes.
[in] num_dimensions Number of dimensions of the array.
[in] window Window the kernel will be executed on.
Definition at line 539 of file ICLKernel.h.
 {
     ARM_COMPUTE_ERROR_ON(array == nullptr);
     // Calculate offset to the start of the window
     unsigned int offset_first_element = 0;
     for (unsigned int n = 0; n < num_dimensions; ++n)
     {
         offset_first_element += window[n].start() * strides[n];
     }
     unsigned int idx_start = idx;
     _kernel.setArg(idx++, array->cl_buffer());
     for (unsigned int dimension = 0; dimension < dimension_size; dimension++)
     {
         _kernel.setArg<cl_uint>(idx++, strides[dimension]);
         _kernel.setArg<cl_uint>(idx++, strides[dimension] * window[dimension].step());
     }
     _kernel.setArg<cl_uint>(idx++, offset_first_element);
     ARM_COMPUTE_ERROR_ON_MSG_VAR(idx_start + num_arguments_per_array<dimension_size>() != idx,
                                  "add_%dD_array_argument() is supposed to add exactly %d arguments to the kernel",
                                  dimension_size, num_arguments_per_array<dimension_size>());
     ARM_COMPUTE_UNUSED(idx_start);
 }
References ARM_COMPUTE_ERROR_ON, ARM_COMPUTE_ERROR_ON_MSG_VAR, ARM_COMPUTE_UNUSED, ICLArray< T >::cl_buffer(), and IKernel::window().
add_tensor_argument()
void add_tensor_argument (unsigned & idx, const ICLTensor * tensor, const Window & window)
Definition at line 88 of file ICLKernel.cpp.
 {
     ARM_COMPUTE_ERROR_ON(tensor == nullptr);
     const ITensorInfo *info    = tensor->info();
     const Strides     &strides = info->strides_in_bytes();
     // Calculate offset to the start of the window
     unsigned int offset_first_element = info->offset_first_element_in_bytes();
     for (unsigned int n = 0; n < info->num_dimensions(); ++n)
     {
         offset_first_element += (window.is_broadcasted(n) ? 0 : window[n].start()) * strides[n];
     }
     unsigned int idx_start = idx;
     _kernel.setArg(idx++, tensor->cl_buffer());
     for (unsigned int d = 0; d < dimension_size; ++d)
     {
         _kernel.setArg<cl_uint>(idx++, window.is_broadcasted(d) ? 0 : strides[d]);
         _kernel.setArg<cl_uint>(idx++, window.is_broadcasted(d) ? 0 : (strides[d] * window[d].step()));
     }
     _kernel.setArg<cl_uint>(idx++, offset_first_element);
     ARM_COMPUTE_ERROR_ON_MSG_VAR(idx_start + num_arguments_per_tensor<dimension_size>() != idx,
                                  "add_%dD_tensor_argument() is supposed to add exactly %d arguments to the kernel",
                                  dimension_size, num_arguments_per_tensor<dimension_size>());
     ARM_COMPUTE_UNUSED(idx_start);
 }
References ARM_COMPUTE_ERROR_ON, ARM_COMPUTE_ERROR_ON_MSG_VAR, ARM_COMPUTE_UNUSED, arm_compute::test::validation::info, Window::is_broadcasted(), tensor, and IKernel::window().
cache_gws()
void cache_gws (const cl::NDRange & gws)
Cache the latest gws used to enqueue this kernel.
Parameters
[in] gws Latest global work size of the kernel
Definition at line 219 of file ICLKernel.cpp.
 {
     _cached_gws = gws;
 }
Referenced by arm_compute::enqueue().
config_id()
const std::string& config_id () const inline
Get the configuration ID.
Note
The configuration ID can be used by the caller to distinguish different calls of the same OpenCL kernel In particular, this method can be used by CLScheduler to keep track of the best LWS for each configuration of the same kernel. The configuration ID should be provided only for the kernels potentially affected by the LWS geometry
This method should be called after the configuration of the kernel
Returns
configuration id string
Definition at line 419 of file ICLKernel.h.
     {
         return _config_id;
     }
get_cached_gws()
cl::NDRange get_cached_gws () const
Get the cached gws used to enqueue this kernel.
Returns
Latest global work size of the kernel
Definition at line 214 of file ICLKernel.cpp.
 {
     return _cached_gws;
 }
get_max_workgroup_size()
size_t get_max_workgroup_size ()
Get the maximum workgroup size for the device the CLKernelLibrary uses.
Returns
The maximum workgroup size value.
Definition at line 185 of file ICLKernel.cpp.
 {
     if (_max_workgroup_size == 0)
     {
         _max_workgroup_size = CLKernelLibrary::get().max_local_workgroup_size(_kernel);
     }
     return _max_workgroup_size;
 }
References CLKernelLibrary::get(), and CLKernelLibrary::max_local_workgroup_size().
Referenced by arm_compute::enqueue().
get_target()
GPUTarget get_target () const inline
Get the targeted GPU architecture.
Returns
The targeted GPU architecture.
Definition at line 443 of file ICLKernel.h.
     {
         return _target;
     }
Referenced by ClIndirectConv2dKernel::configure(), ClDirectConv2dKernel::configure(), and CLDepthwiseConvolutionLayerNativeKernel::configure().
gws_from_window()
cl::NDRange gws_from_window (const Window & window, bool use_dummy_work_items) static
Get the global work size given an execution window.
Parameters
[in] window Execution window
[in] use_dummy_work_items If the kernel uses dummy work items
Returns
Global work size of the given execution window
Definition at line 194 of file ICLKernel.cpp.
 {
     if ((window.x().end() - window.x().start()) == 0 || (window.y().end() - window.y().start()) == 0)
     {
         return cl::NullRange;
     }
     cl::NDRange gws((window.x().end() - window.x().start()) / window.x().step(),
                     (window.y().end() - window.y().start()) / window.y().step(),
                     (window.z().end() - window.z().start()) / window.z().step());
     if (use_dummy_work_items)
     {
         gws.get()[0] = get_next_power_two(gws[0]);
         gws.get()[1] = get_next_power_two(gws[1]);
     }
     return gws;
 }
References Window::Dimension::end(), arm_compute::get_next_power_two(), Window::Dimension::start(), Window::Dimension::step(), IKernel::window(), Window::x(), Window::y(), and Window::z().
kernel()
cl::Kernel& kernel () inline
Returns a reference to the OpenCL kernel of this object.
Returns
A reference to the OpenCL kernel of this object.
Definition at line 151 of file ICLKernel.h.
     {
         return _kernel;
     }
Referenced by arm_compute::enqueue().
lws_hint()
cl::NDRange lws_hint () const inline
Return the Local-Workgroup-Size hint.
Returns
Current lws hint
Definition at line 383 of file ICLKernel.h.
     {
         return _tuning_params_hint.get_lws();
     }
References CLTuningParams::get_lws().
Referenced by ICLSimple2DKernel::run(), ICLSimple3DKernel::run(), CLBitwiseKernel::run(), CLChannelShuffleLayerKernel::run(), CLSpaceToDepthLayerKernel::run(), CLDepthToSpaceLayerKernel::run(), CLDeconvolutionLayerUpsampleKernel::run(), CLInstanceNormalizationLayerKernel::run(), CLFFTScaleKernel::run(), CLSelectKernel::run(), CLComputeAllAnchorsKernel::run(), CLNormalizationLayerKernel::run(), CLQLSTMLayerNormalizationKernel::run(), CLRangeKernel::run(), CLReorgLayerKernel::run(), CLTileKernel::run(), CLROIPoolingLayerKernel::run(), CLMaxUnpoolingLayerKernel::run(), CLMeanStdDevNormalizationKernel::run(), CLGatherKernel::run(), CLComparisonKernel::run(), CLFFTDigitReverseKernel::run(), CLReverseKernel::run(), CLNormalizePlanarYUVLayerKernel::run(), CLFFTRadixStageKernel::run(), CLArgMinMaxLayerKernel::run(), CLL2NormalizeLayerKernel::run(), CLPadLayerKernel::run(), CLBoundingBoxTransformKernel::run(), CLFillBorderKernel::run(), CLPriorBoxLayerKernel::run(), CLStackLayerKernel::run(), CLROIAlignLayerKernel::run(), CLDeconvolutionReshapeOutputKernel::run(), CLDepthwiseConvolutionLayerNativeKernel::run(), CLBatchNormalizationLayerKernel::run(), CLComputeMeanVariance::run(), CLBatchToSpaceLayerKernel::run(), CLFuseBatchNormalizationKernel::run(), CLSpaceToBatchLayerKernel::run(), ClElementwiseKernel::run_op(), ClReshapeKernel::run_op(), ClTransposeKernel::run_op(), ClDequantizeKernel::run_op(), ClFloorKernel::run_op(), ClWidthConcatenate2TensorsKernel::run_op(), ClCopyKernel::run_op(), ClFillKernel::run_op(), ClElementWiseUnaryKernel::run_op(), ClScaleKernel::run_op(), ClQuantizeKernel::run_op(), ClHeightConcatenateKernel::run_op(), ClWidthConcatenateKernel::run_op(), ClBatchConcatenateKernel::run_op(), ClDepthConcatenateKernel::run_op(), ClTransposedConvolutionKernel::run_op(), ClActivationKernel::run_op(), ClPermuteKernel::run_op(), ClSoftmaxKernel::run_op(), ClWidthConcatenate4TensorsKernel::run_op(), ClConvertFullyConnectedWeightsKernel::run_op(), ClWinogradInputTransformKernel::run_op(), ClGemmReshapeLhsMatrixKernel::run_op(), ClMatMulNativeKernel::run_op(), ClCastKernel::run_op(), ClMatMulLowpNativeKernel::run_op(), ClCropKernel::run_op(), ClGemmLowpMatrixMultiplyNativeKernel::run_op(), ClGemmLowpQuantizeDownInt32ScaleByFixedPointKernel::run_op(), ClGemmLowpQuantizeDownInt32ScaleKernel::run_op(), ClGemmLowpQuantizeDownInt32ScaleByFloatKernel::run_op(), ClGemmReshapeRhsMatrixKernel::run_op(), ClCol2ImKernel::run_op(), ClGemmMatrixMultiplyNativeKernel::run_op(), ClIndirectConv2dKernel::run_op(), CLStridedSliceKernel::run_op(), ClGemmLowpOffsetContributionKernel::run_op(), ClDirectConv3dKernel::run_op(), ClGemmLowpMatrixAReductionKernel::run_op(), ClDirectConv2dKernel::run_op(), ClGemmLowpOffsetContributionOutputStageKernel::run_op(), ClMulKernel::run_op(), CLFillBorderKernel::run_op(), ClIm2ColKernel::run_op(), ClGemmMatrixMultiplyReshapedOnlyRhsKernel::run_op(), ClGemmMatrixMultiplyReshapedKernel::run_op(), ClGemmLowpMatrixBReductionKernel::run_op(), ClComplexMulKernel::run_op(), and ICLKernel::set_lws_hint().
num_arguments_per_1D_array()
constexpr static unsigned int num_arguments_per_1D_array () inline static constexpr
Returns the number of arguments enqueued per 1D array object.
Returns
The number of arguments enqueues per 1D array object.
Definition at line 297 of file ICLKernel.h.
     {
         return num_arguments_per_array<1>();
     }
num_arguments_per_1D_tensor()
constexpr static unsigned int num_arguments_per_1D_tensor () inline static constexpr
Returns the number of arguments enqueued per 1D tensor object.
Returns
The number of arguments enqueues per 1D tensor object.
Definition at line 305 of file ICLKernel.h.
     {
         return num_arguments_per_tensor<1>();
     }
Referenced by CLReverseKernel::configure(), CLBatchNormalizationLayerKernel::configure(), and CLSelectKernel::run().
num_arguments_per_2D_tensor()
constexpr static unsigned int num_arguments_per_2D_tensor () inline static constexpr
Returns the number of arguments enqueued per 2D tensor object.
Returns
The number of arguments enqueues per 2D tensor object.
Definition at line 313 of file ICLKernel.h.
     {
         return num_arguments_per_tensor<2>();
     }
Referenced by CLL2NormalizeLayerKernel::configure(), CLPriorBoxLayerKernel::configure(), ClGemmLowpMatrixMultiplyNativeKernel::run_op(), ClGemmMatrixMultiplyNativeKernel::run_op(), and ClIm2ColKernel::run_op().
num_arguments_per_3D_tensor()
constexpr static unsigned int num_arguments_per_3D_tensor () inline static constexpr
Returns the number of arguments enqueued per 3D tensor object.
Returns
The number of arguments enqueues per 3D tensor object.
Definition at line 321 of file ICLKernel.h.
     {
         return num_arguments_per_tensor<3>();
     }
Referenced by ClReshapeKernel::configure(), CLFFTScaleKernel::configure(), CLFFTRadixStageKernel::configure(), CLL2NormalizeLayerKernel::configure(), ClMulKernel::configure(), CLFillBorderKernel::configure(), CLBatchNormalizationLayerKernel::configure(), CLNormalizePlanarYUVLayerKernel::run(), CLBatchNormalizationLayerKernel::run(), ClDequantizeKernel::run_op(), ClBatchConcatenateKernel::run_op(), ClDepthConcatenateKernel::run_op(), ClWinogradInputTransformKernel::run_op(), ClGemmLowpQuantizeDownInt32ScaleByFixedPointKernel::run_op(), ClGemmLowpQuantizeDownInt32ScaleKernel::run_op(), ClGemmLowpQuantizeDownInt32ScaleByFloatKernel::run_op(), ClDirectConv2dKernel::run_op(), and ClIm2ColKernel::run_op().
num_arguments_per_3d_tensor_nhw()
constexpr static unsigned int num_arguments_per_3d_tensor_nhw () inline static constexpr
Returns the number of arguments enqueued per NHW 3D Tensor object.
Returns
The number of arguments enqueued per NHW 3D Tensor object.
Definition at line 270 of file ICLKernel.h.
     {
         constexpr unsigned int no_args_per_3d_tensor_nhw = 7u;
         return no_args_per_3d_tensor_nhw;
     }
Referenced by ClGemmReshapeLhsMatrixKernel::configure(), and ClGemmReshapeRhsMatrixKernel::configure().
num_arguments_per_4D_tensor()
constexpr static unsigned int num_arguments_per_4D_tensor () inline static constexpr
Returns the number of arguments enqueued per 4D tensor object.
Returns
The number of arguments enqueues per 4D tensor object.
Definition at line 329 of file ICLKernel.h.
     {
         return num_arguments_per_tensor<4>();
     }
Referenced by CLReverseKernel::configure(), and CLStackLayerKernel::configure().
num_arguments_per_4d_tensor_nhwc()
constexpr static unsigned int num_arguments_per_4d_tensor_nhwc () inline static constexpr
Returns the number of arguments enqueued per NHWC 4D Tensor object.
Returns
The number of arguments enqueued per NHWC 4D Tensor object.
Definition at line 287 of file ICLKernel.h.
     {
         constexpr unsigned int no_args_per_4d_tensor_nhwc = 9u;
         return no_args_per_4d_tensor_nhwc;
     }
Referenced by ClScaleKernel::configure().
run()
virtual void run (const Window & window, cl::CommandQueue & queue) inline virtual
Enqueue the OpenCL kernel to process the given window on the passed OpenCL command queue.
Note
The queue is not flushed by this method, and therefore the kernel will not have been executed by the time this method returns.
Parameters
[in] window Region on which to execute the kernel. (Must be a valid region of the window returned by window()).
[in,out] queue Command queue on which to enqueue the kernel.
Reimplemented in CLSpaceToBatchLayerKernel, CLFuseBatchNormalizationKernel, CLBatchToSpaceLayerKernel, CLComputeMeanVariance, CLBatchNormalizationLayerKernel, CLDepthwiseConvolutionLayerNativeKernel, CLDeconvolutionReshapeOutputKernel, CLStackLayerKernel, CLBoundingBoxTransformKernel, CLFillBorderKernel, CLPriorBoxLayerKernel, CLPadLayerKernel, CLL2NormalizeLayerKernel, CLArgMinMaxLayerKernel, CLFFTRadixStageKernel, CLReductionOperationKernel, CLNormalizePlanarYUVLayerKernel, CLReverseKernel, CLFFTDigitReverseKernel, CLComparisonKernel, CLGatherKernel, CLMaxUnpoolingLayerKernel, CLMeanStdDevNormalizationKernel, CLROIPoolingLayerKernel, CLQLSTMLayerNormalizationKernel, CLRangeKernel, CLReorgLayerKernel, CLTileKernel, CLNormalizationLayerKernel, CLFFTScaleKernel, CLComputeAllAnchorsKernel, CLSelectKernel, CLDeconvolutionLayerUpsampleKernel, CLInstanceNormalizationLayerKernel, CLChannelShuffleLayerKernel, CLDepthToSpaceLayerKernel, CLSpaceToDepthLayerKernel, CLBitwiseKernel, ICLSimple3DKernel, ICLSimple2DKernel, and CLROIAlignLayerKernel.
Definition at line 340 of file ICLKernel.h.
     {
         ARM_COMPUTE_UNUSED(window, queue);
     }
References ARM_COMPUTE_UNUSED, and IKernel::window().
run_op()
virtual void run_op (ITensorPack & tensors, const Window & window, cl::CommandQueue & queue) inline virtual
Enqueue the OpenCL kernel to process the given window on the passed OpenCL command queue.
Note
The queue is not flushed by this method, and therefore the kernel will not have been executed by the time this method returns.
Parameters
[in] tensors A vector containing the tensors to operato on.
[in] window Region on which to execute the kernel. (Must be a valid region of the window returned by window()).
[in,out] queue Command queue on which to enqueue the kernel.
Reimplemented in ClComplexMulKernel, ClGemmLowpMatrixBReductionKernel, ClGemmMatrixMultiplyReshapedKernel, ClGemmMatrixMultiplyReshapedOnlyRhsKernel, ClIm2ColKernel, ClGemmLowpMatrixMultiplyReshapedOnlyRhsKernel, CLFillBorderKernel, ClGemmLowpOffsetContributionOutputStageKernel, ClMulKernel, ClGemmLowpMatrixMultiplyReshapedOnlyRhsMMULKernel, ClDirectConv2dKernel, ClGemmLowpMatrixAReductionKernel, ClMatMulNativeMMULKernel, ClWeightsReshapeKernel, ClDirectConv3dKernel, CLStridedSliceKernel, ClGemmLowpOffsetContributionKernel, ClGemmMatrixMultiplyReshapedOnlyRhsMMULKernel, ClGemmLowpMatrixMultiplyReshapedKernel, ClGemmMatrixMultiplyNativeKernel, ClIndirectConv2dKernel, ClCol2ImKernel, ClWinogradOutputTransformKernel, ClGemmLowpQuantizeDownInt32ScaleByFloatKernel, ClGemmLowpQuantizeDownInt32ScaleKernel, ClGemmReshapeRhsMatrixKernel, ClIndirectConv2dAddressPrecalculationKernel, ClGemmLowpMatrixMultiplyNativeKernel, ClGemmLowpQuantizeDownInt32ScaleByFixedPointKernel, ClCropKernel, ClMatMulLowpNativeKernel, ClGemmReshapeLhsMatrixKernel, ClMatMulNativeKernel, ClWinogradFilterTransformKernel, ClWinogradInputTransformKernel, ClMatMulLowpNativeMMULKernel, ClSoftmaxKernel, ClPool2dKernel, ClPermuteKernel, ClTransposedConvolutionKernel, ClPool3dKernel, ClQuantizeKernel, ClScaleKernel, ClCopyKernel, ClElementWiseUnaryKernel, ClFillKernel, ClKernelRuntime, ClDequantizeKernel, ClFloorKernel, ClReshapeKernel, and ClTransposeKernel.
Definition at line 352 of file ICLKernel.h.
     {
         ARM_COMPUTE_UNUSED(tensors, window, queue);
     }
References ARM_COMPUTE_UNUSED, and IKernel::window().
set_lws_hint()
void set_lws_hint (const cl::NDRange & lws_hint) inline
Set the Local-Workgroup-Size hint.
Note
This method should be called after the configuration of the kernel
Parameters
[in] lws_hint Local-Workgroup-Size to use
Definition at line 373 of file ICLKernel.h.
     {
         ARM_COMPUTE_ERROR_ON_UNCONFIGURED_KERNEL(this); // lws_hint will be overwritten by configure()
         _tuning_params_hint.set_lws(lws_hint);
     }
References ARM_COMPUTE_ERROR_ON_UNCONFIGURED_KERNEL, ICLKernel::lws_hint(), and CLTuningParams::set_lws().
set_target() [1/2]
void set_target (cl::Device & device)
Set the targeted GPU architecture according to the CL device.
Parameters
[in] device A CL device
Definition at line 180 of file ICLKernel.cpp.
 {
     _target = get_target_from_device(device);
 }
References arm_compute::get_target_from_device().
set_target() [2/2]
void set_target (GPUTarget target) inline
Set the targeted GPU architecture.
Parameters
[in] target The targeted GPU architecture
Definition at line 428 of file ICLKernel.h.
     {
         _target = target;
     }
set_wbsm_hint()
void set_wbsm_hint (const cl_int & wbsm_hint) inline
Set the workgroup batch size modifier hint.
Note
This method should be called after the configuration of the kernel
Parameters
[in] wbsm_hint workgroup batch size modifier value
Definition at line 394 of file ICLKernel.h.
     {
         ARM_COMPUTE_ERROR_ON_UNCONFIGURED_KERNEL(this); // wbsm_hint will be overwritten by configure()
         _tuning_params_hint.set_wbsm(wbsm_hint);
     }
References ARM_COMPUTE_ERROR_ON_UNCONFIGURED_KERNEL, CLTuningParams::set_wbsm(), and ICLKernel::wbsm_hint().
type()
CLKernelType type () const inline
Returns the CL kernel type.
Returns
The CL kernel type
Definition at line 159 of file ICLKernel.h.
     {
         return _type;
     }
wbsm_hint()
cl_int wbsm_hint () const inline
Return the workgroup batch size modifier hint.
Returns
Current wbsm hint
Definition at line 404 of file ICLKernel.h.
     {
         return _tuning_params_hint.get_wbsm();
     }
References CLTuningParams::get_wbsm().
Referenced by arm_compute::enqueue(), and ICLKernel::set_wbsm_hint().
The documentation for this class was generated from the following files:
src/core/CL/ICLKernel.h
src/core/CL/ICLKernel.cpp