Compute Library: CpuFillKernel Class Reference
CpuFillKernel Class Reference
Kernel for filling a tensor with a given constant value.
#include <CpuFillKernel.h>
Public Member Functions
CpuFillKernel ()=default
ARM_COMPUTE_DISALLOW_COPY_ALLOW_MOVE (CpuFillKernel)
void configure (const ITensorInfo *tensor, const PixelValue &constant_value)
Configure kernel for a given list of arguments.
void run_op (ITensorPack &tensors, const Window &window, const ThreadInfo &info) override
Execute the kernel on the passed window.
const char * name () const override
Name of the kernel.
Public Member Functions inherited from ICPPKernel
virtual ~ICPPKernel ()=default
Default destructor.
virtual void run (const Window &window, const ThreadInfo &info)
Execute the kernel on the passed window.
virtual void run_nd (const Window &window, const ThreadInfo &info, const Window &thread_locator)
legacy compatibility layer for implemantions which do not support thread_locator In these cases we simply narrow the interface down the legacy version
virtual size_t get_mws (const CPUInfo &platform, size_t thread_count) const
Return minimum workload size of the relevant kernel.
Public Member Functions inherited from IKernel
IKernel ()
Constructor.
virtual ~IKernel ()=default
Destructor.
virtual bool is_parallelisable () const
Indicates whether or not the kernel is parallelisable.
virtual BorderSize border_size () const
The size of the border for that kernel.
const Window & window () const
The maximum window the kernel can be executed on.
bool is_window_configured () const
Function to check if the embedded window of this kernel has been configured.
Additional Inherited Members
Static Public Member Functions inherited from ICpuKernel< CpuFillKernel >
static const auto * get_implementation (const SelectorType &selector, KernelSelectionType selection_type=KernelSelectionType::Supported)
Micro-kernel selector.
Static Public Attributes inherited from ICPPKernel
static constexpr size_t default_mws = 1
Detailed Description
Kernel for filling a tensor with a given constant value.
Definition at line 39 of file CpuFillKernel.h.
Constructor & Destructor Documentation
CpuFillKernel()
CpuFillKernel () default
Member Function Documentation
ARM_COMPUTE_DISALLOW_COPY_ALLOW_MOVE()
ARM_COMPUTE_DISALLOW_COPY_ALLOW_MOVE (CpuFillKernel)
configure()
void configure (const ITensorInfo * tensor, const PixelValue & constant_value)
Configure kernel for a given list of arguments.
Parameters
[in,out] tensor Tensor to fill. Supported data types: All
[in] constant_value The value used to fill the planes of the tensor
Definition at line 41 of file CpuFillKernel.cpp.
 {
     ARM_COMPUTE_ERROR_ON_NULLPTR(tensor);
     _constant_value = constant_value;
     // Configure kernel window
     Window win = calculate_max_window(*tensor, Steps());
     ICpuKernel::configure(win);
 }
References ARM_COMPUTE_ERROR_ON_NULLPTR, arm_compute::calculate_max_window(), and tensor.
name()
const char * name () const override virtual
Name of the kernel.
Returns
Kernel name
Implements ICPPKernel.
Definition at line 86 of file CpuFillKernel.cpp.
 {
     return "CpuFillKernel";
 }
run_op()
void run_op (ITensorPack & tensors, const Window & window, const ThreadInfo & info) override virtual
Execute the kernel on the passed window.
Warning
If is_parallelisable() returns false then the passed window must be equal to window()
Note
The window has to be a region within the window returned by the window() method
The width of the window has to be a multiple of num_elems_processed_per_iteration().
Parameters
[in] tensors A vector containing the tensors to operate on.
[in] window Region on which to execute the kernel. (Must be a region of the window returned by window())
[in] info Info about executing thread and CPU.
Reimplemented from ICPPKernel.
Definition at line 51 of file CpuFillKernel.cpp.
 {
     ARM_COMPUTE_UNUSED(info);
     ARM_COMPUTE_ERROR_ON_UNCONFIGURED_KERNEL(this);
     ARM_COMPUTE_ERROR_ON_INVALID_SUBWINDOW(ICpuKernel::window(), window);
     auto inout = tensors.get_tensor(TensorType::ACL_SRC_DST);
     // Collapse all the batches on the third dimension
     bool   has_collapsed = true;
     Window collapsed     = window.collapse_if_possible(window, Window::DimZ, &has_collapsed);
     ARM_COMPUTE_ERROR_ON(!has_collapsed);
     uint8_t *const start_valid_region = inout->ptr_to_element(inout->info()->valid_region().anchor);
     const auto     window_width       = static_cast<int>(collapsed.x().end()) - static_cast<int>(collapsed.x().start());
     const size_t   element_size       = inout->info()->element_size();
     // Unroll X dimension
     collapsed.set(Window::DimX, Window::Dimension(0, 1, 1));
     Iterator tensor_it(inout, collapsed);
     execute_window_loop(
         collapsed,
         [&](const Coordinates &)
         {
             uint8_t *base_addr = start_valid_region + tensor_it.offset();
             // Set memory
             for (int i = 0; i < window_width; ++i)
             {
                 std::memcpy(base_addr + i * element_size, &_constant_value.value, element_size);
             }
         },
         tensor_it);
 }
References arm_compute::ACL_SRC_DST, ARM_COMPUTE_ERROR_ON, ARM_COMPUTE_ERROR_ON_INVALID_SUBWINDOW, ARM_COMPUTE_ERROR_ON_UNCONFIGURED_KERNEL, ARM_COMPUTE_UNUSED, Window::collapse_if_possible(), Window::DimX, Window::DimZ, Window::Dimension::end(), arm_compute::execute_window_loop(), ITensorPack::get_tensor(), arm_compute::test::validation::info, Iterator::offset(), Window::set(), Window::Dimension::start(), PixelValue::value, IKernel::window(), and Window::x().
The documentation for this class was generated from the following files:
src/cpu/kernels/CpuFillKernel.h
src/cpu/kernels/CpuFillKernel.cpp