Compute Library: CpuDequantize Class Reference
CpuDequantize Class Reference
Basic function to run kernels::CpuDequantizeKernel that dequantizes an input tensor.
#include <CpuDequantize.h>
Public Member Functions
void configure (const ITensorInfo *src, ITensorInfo *dst)
Configure the kernel.
void run (ITensorPack &tensors) override
Run the kernels contained in the function.
Public Member Functions inherited from INEOperator
INEOperator (IRuntimeContext *ctx=nullptr)
Constructor.
INEOperator (const INEOperator &)=delete
Prevent instances of this class from being copied (As this class contains pointers)
INEOperator (INEOperator &&)=default
Default move constructor.
INEOperator & operator= (const INEOperator &)=delete
Prevent instances of this class from being copied (As this class contains pointers)
INEOperator & operator= (INEOperator &&)=default
Default move assignment operator.
~INEOperator ()
Default destructor.
void prepare (ITensorPack &constants) override
Prepare the function for executing.
MemoryRequirements workspace () const override
Return the memory requirements required by the workspace.
Public Member Functions inherited from IOperator
virtual ~IOperator ()=default
Destructor.
Static Public Member Functions
static Status validate (const ITensorInfo *src, const ITensorInfo *dst)
Static function to check if given info will lead to a valid configuration.
Detailed Description
Basic function to run kernels::CpuDequantizeKernel that dequantizes an input tensor.
Definition at line 34 of file CpuDequantize.h.
Member Function Documentation
configure()
void configure (const ITensorInfo * src, ITensorInfo * dst)
Configure the kernel.
Parameters
[in] src Source tensor info. Data types supported: QASYMM8/QASYMM8_SIGNED/QSYMM8_PER_CHANNEL/QSYMM8/QSYMM16.
[out] dst Destination tensor info with the same dimensions of input. Data type supported: F16/F32.
Definition at line 37 of file CpuDequantize.cpp.
 {
     ARM_COMPUTE_LOG_PARAMS(src, dst);
     auto k = std::make_unique<kernels::CpuDequantizeKernel>();
     k->configure(src, dst);
     _kernel = std::move(k);
 }
References ARM_COMPUTE_LOG_PARAMS, arm_compute::test::validation::dst, and arm_compute::test::validation::src.
Referenced by CpuAddMulAdd::configure().
run()
void run (ITensorPack & tensors) override virtual
Run the kernels contained in the function.
Parameters
[in] tensors Vector that contains the tensors to operate on.
Reimplemented from INEOperator.
Definition at line 50 of file CpuDequantize.cpp.
 {
     ARM_COMPUTE_ERROR_ON_MSG(tensors.empty(), "No inputs provided");
     prepare(tensors);
     NEScheduler::get().schedule_op(_kernel.get(), Window::DimY, _kernel->window(), tensors);
 }
References ARM_COMPUTE_ERROR_ON_MSG, Window::DimY, ITensorPack::empty(), Scheduler::get(), INEOperator::prepare(), and IScheduler::schedule_op().
Referenced by CpuAddMulAdd::run().
validate()
Status validate (const ITensorInfo * src, const ITensorInfo * dst) static
Static function to check if given info will lead to a valid configuration.
Similar to CpuDequantize::configure()
Returns
a status
Definition at line 45 of file CpuDequantize.cpp.
 {
     return kernels::CpuDequantizeKernel::validate(src, dst);
 }
References arm_compute::test::validation::dst, arm_compute::test::validation::src, and CpuDequantizeKernel::validate().
Referenced by CpuAddMulAdd::validate(), and NEDequantizationLayer::validate().
The documentation for this class was generated from the following files:
src/cpu/operators/CpuDequantize.h
src/cpu/operators/CpuDequantize.cpp