Compute Library: CLElementwisePower Class Reference
CLElementwisePower Class Reference
Basic function to run opencl::kernels::ClArithmeticKernel for power.
#include <CLElementwiseOperations.h>
Public Member Functions
CLElementwisePower ()
Default Constructor.
~CLElementwisePower ()
Default Destructor.
CLElementwisePower (const CLElementwisePower &)=delete
Prevent instances of this class from being copied (As this class contains pointers)
CLElementwisePower (CLElementwisePower &&)
Default move constructor.
CLElementwisePower & operator= (const CLElementwisePower &)=delete
Prevent instances of this class from being copied (As this class contains pointers)
CLElementwisePower & operator= (CLElementwisePower &&)
Default move assignment operator.
void configure (ICLTensor *input1, ICLTensor *input2, ICLTensor *output, const ActivationLayerInfo &act_info=ActivationLayerInfo())
Initialise the kernel's inputs, output and conversion policy.
void configure (const CLCompileContext &compile_context, ICLTensor *input1, ICLTensor *input2, ICLTensor *output, const ActivationLayerInfo &act_info=ActivationLayerInfo())
Initialise the kernel's inputs, output and conversion policy.
void run () override
Run the kernels contained in the function.
Public Member Functions inherited from IFunction
virtual ~IFunction ()=default
Destructor.
virtual void prepare ()
Prepare the function for executing.
Static Public Member Functions
static Status validate (const ITensorInfo *input1, const ITensorInfo *input2, const ITensorInfo *output, const ActivationLayerInfo &act_info=ActivationLayerInfo())
Static function to check if given info will lead to a valid configuration of opencl::kernels::ClArithmeticKernel for power.
Detailed Description
Basic function to run opencl::kernels::ClArithmeticKernel for power.
Note
The tensor data type for the inputs must be F16/F32.
The function performs an elementwise power of in1 to in2 (i.e., out[i] = in1[i] ^ in2[i])
Definition at line 621 of file CLElementwiseOperations.h.
Constructor & Destructor Documentation
CLElementwisePower() [1/3]
CLElementwisePower ()
Default Constructor.
Definition at line 372 of file CLElementwiseOperations.cpp.
                                        : _impl(std::make_unique<Impl>())
 {
 }
~CLElementwisePower()
~CLElementwisePower () default
Default Destructor.
CLElementwisePower() [2/3]
CLElementwisePower (const CLElementwisePower &) delete
Prevent instances of this class from being copied (As this class contains pointers)
CLElementwisePower() [3/3]
CLElementwisePower (CLElementwisePower &&) default
Default move constructor.
Member Function Documentation
configure() [1/2]
void configure (const CLCompileContext & compile_context, ICLTensor * input1, ICLTensor * input2, ICLTensor * output, const ActivationLayerInfo & act_info = ActivationLayerInfo())
Initialise the kernel's inputs, output and conversion policy.
Parameters
[in] compile_context The compile context to be used.
[in,out] input1 First tensor input. Data types supported: F16/F32. The input tensor is [in, out] because its TensorInfo might be modified inside the kernel in case of broadcasting of dimension 0.
[in,out] input2 Second tensor input. Data types supported: F16/F32. The input tensor is [in, out] because its TensorInfo might be modified inside the kernel in case of broadcasting of dimension 0.
[out] output Output tensor. Data types supported:F16/F32.
[in] act_info (Optional) Activation layer information in case of a fused activation.
Definition at line 387 of file CLElementwiseOperations.cpp.
 {
     _impl->src_0 = input1;
     _impl->src_1 = input2;
     _impl->dst   = output;
     _impl->op    = std::make_unique<opencl::ClElementwisePower>();
     _impl->op->configure(compile_context, input1->info(), input2->info(), output->info(), act_info);
 }
References arm_compute::test::validation::act_info, and ITensor::info().
configure() [2/2]
void configure (ICLTensor * input1, ICLTensor * input2, ICLTensor * output, const ActivationLayerInfo & act_info = ActivationLayerInfo())
Initialise the kernel's inputs, output and conversion policy.
Valid data layouts:
All
Valid data type configurations:
src0 src1 dst
F16 F16 F16
F32 F32 F32
Parameters
[in,out] input1 First tensor input. Data types supported: F16/F32. The input tensor is [in, out] because its TensorInfo might be modified inside the kernel in case of broadcasting of dimension 0.
[in,out] input2 Second tensor input. Data types supported: F16/F32. The input tensor is [in, out] because its TensorInfo might be modified inside the kernel in case of broadcasting of dimension 0.
[out] output Output tensor. Data types supported:F16/F32.
[in] act_info (Optional) Activation layer information in case of a fused activation.
Definition at line 379 of file CLElementwiseOperations.cpp.
 {
     configure(CLKernelLibrary::get().get_compile_context(), input1, input2, output, act_info);
 }
References arm_compute::test::validation::act_info, and CLKernelLibrary::get().
operator=() [1/2]
CLElementwisePower & operator= (CLElementwisePower &&) default
Default move assignment operator.
operator=() [2/2]
CLElementwisePower& operator= (const CLElementwisePower &) delete
Prevent instances of this class from being copied (As this class contains pointers)
run()
void run () override virtual
Run the kernels contained in the function.
For CPU kernels:
Multi-threading is used for the kernels which are parallelisable.
By default std::thread::hardware_concurrency() threads are used.
Note
CPPScheduler::set_num_threads() can be used to manually set the number of threads
For OpenCL kernels:
All the kernels are enqueued on the queue associated with CLScheduler.
The queue is then flushed.
Note
The function will not block until the kernels are executed. It is the user's responsibility to wait.
Will call prepare() on first run if hasn't been done
Implements IFunction.
Definition at line 408 of file CLElementwiseOperations.cpp.
 {
     ITensorPack pack;
     pack.add_tensor(TensorType::ACL_SRC_0, _impl->src_0);
     pack.add_tensor(TensorType::ACL_SRC_1, _impl->src_1);
     pack.add_tensor(TensorType::ACL_DST, _impl->dst);
     _impl->op->run(pack);
 }
References arm_compute::ACL_DST, arm_compute::ACL_SRC_0, arm_compute::ACL_SRC_1, ITensorPack::add_tensor(), and arm_compute::test::validation::pack.
validate()
Status validate (const ITensorInfo * input1, const ITensorInfo * input2, const ITensorInfo * output, const ActivationLayerInfo & act_info = ActivationLayerInfo()) static
Static function to check if given info will lead to a valid configuration of opencl::kernels::ClArithmeticKernel for power.
Parameters
[in] input1 First tensor input info. Data types supported: F16/F32.
[in] input2 Second tensor input info. Data types supported: F16/F32.
[in] output Output tensor info. Data types supported: F16/F32.
[in] act_info (Optional) Activation layer information in case of a fused activation.
Returns
a status
Definition at line 400 of file CLElementwiseOperations.cpp.
 {
     return opencl::ClElementwisePower::validate(input1, input2, output, act_info);
 }
References arm_compute::test::validation::act_info, and ClElementwisePower::validate().
The documentation for this class was generated from the following files:
arm_compute/runtime/CL/functions/CLElementwiseOperations.h
src/runtime/CL/functions/CLElementwiseOperations.cpp