Compute Library: CLMatMul Class Reference
CLMatMul Class Reference
Basic function to execute MatMul (Matrix Multiplication) on OpenCL.
#include <CLMatMul.h>
Public Member Functions
CLMatMul ()
Default constructor.
~CLMatMul ()
Default destructor.
CLMatMul (const CLMatMul &)=delete
Prevent instances of this class from being copied (As this class contains pointers)
CLMatMul (CLMatMul &&)
Default move constructor.
CLMatMul & operator= (const CLMatMul &)=delete
Prevent instances of this class from being copied (As this class contains pointers)
CLMatMul & operator= (CLMatMul &&)
Default move assignment operator.
void configure (const CLCompileContext &compile_context, ICLTensor *rhs, ICLTensor *lhs, ICLTensor *dst, const MatMulInfo &matmul_info, const GpuMatMulSettings &settings=GpuMatMulSettings{}, const ActivationLayerInfo &act_info=ActivationLayerInfo{})
Initialise the kernel's inputs and output.
void configure (ICLTensor *lhs, ICLTensor *rhs, ICLTensor *dst, const MatMulInfo &matmul_info, const GpuMatMulSettings &settings=GpuMatMulSettings{}, const ActivationLayerInfo &act_info=ActivationLayerInfo{})
Initialise the kernel's inputs and output.
void run () override
Run the kernels contained in the function.
Public Member Functions inherited from IFunction
virtual ~IFunction ()=default
Destructor.
virtual void prepare ()
Prepare the function for executing.
Static Public Member Functions
static Status validate (const ITensorInfo *lhs, const ITensorInfo *rhs, const ITensorInfo *output, const MatMulInfo &matmul_info, const ActivationLayerInfo &act_info=ActivationLayerInfo{})
Static function to check if given info will lead to a valid configuration of CLMatMul.
Detailed Description
Basic function to execute MatMul (Matrix Multiplication) on OpenCL.
Definition at line 50 of file CLMatMul.h.
Constructor & Destructor Documentation
CLMatMul() [1/3]
CLMatMul ()
Default constructor.
Definition at line 40 of file CLMatMul.cpp.
                    : _impl(std::make_unique<Impl>())
 {
 }
~CLMatMul()
~CLMatMul () default
Default destructor.
CLMatMul() [2/3]
CLMatMul (const CLMatMul &) delete
Prevent instances of this class from being copied (As this class contains pointers)
CLMatMul() [3/3]
CLMatMul (CLMatMul &&)
Default move constructor.
Member Function Documentation
configure() [1/2]
void configure (const CLCompileContext & compile_context, ICLTensor * rhs, ICLTensor * lhs, ICLTensor * dst, const MatMulInfo & matmul_info, const GpuMatMulSettings & settings = GpuMatMulSettings{}, const ActivationLayerInfo & act_info = ActivationLayerInfo{})
Initialise the kernel's inputs and output.
Valid data layouts:
All
Valid data type configurations:
lhs rhs dst
F32 F32 F32
F16 F16 F16
QASYMM8_SIGNED QASYMM8_SIGNED QASYMM8_SIGNED
QASYMM8 QASYMM8 QASYMM8
Note
BatchMatMul: Batched Matrix Multiply - [A * B], Multiplies all slices (slice is an element of a batch) of Tensors A and B and stores the result in the dst tensor of the same batch size. Batch here is number of slices from A and B multiplied at a time, do not confuse with the batch dimension 'N' of NHWC/NCHW For NHWC for example: the batch is the higher dimensions H * N, and in general it is H * all higher dimensions.
All tensors must have the same data type.
Parameters
[in] compile_context The compile context to be used.
[in] lhs Left-hand side tensor info containing the input activations as Matrix A. Data types supported: F16/F32/QASYMM8_SIGNED/QASYMM8.
[in] rhs Right-hand side tensor info containing the input weights as Matrix B. Data types supported: same as lhs.
[out] dst Output tensor to store the result of the batched matrix multiplication. Data types supported: same as lhs.
[in] matmul_info Contains MatMul operation information described in MatMulInfo.
[in] settings Contains flags for function level settings
[in] act_info (Optional) Contains activation function and lower and upper bound values for bounded activation functions.
Definition at line 57 of file CLMatMul.cpp.
 {
     ARM_COMPUTE_ERROR_ON_NULLPTR(lhs, rhs, output);
     ARM_COMPUTE_UNUSED(settings);
     _impl->op = std::make_unique<OperatorType>();
     _impl->op->configure(compile_context, lhs->info(), rhs->info(), output->info(), matmul_info, act_info);
     _impl->run_pack = {{ACL_SRC_0, lhs}, {ACL_SRC_1, rhs}, {ACL_DST, output}};
 }
References arm_compute::ACL_DST, arm_compute::ACL_SRC_0, arm_compute::ACL_SRC_1, arm_compute::test::validation::act_info, ARM_COMPUTE_ERROR_ON_NULLPTR, ARM_COMPUTE_UNUSED, and ITensor::info().
Referenced by CLMatMul::configure().
configure() [2/2]
void configure (ICLTensor * lhs, ICLTensor * rhs, ICLTensor * dst, const MatMulInfo & matmul_info, const GpuMatMulSettings & settings = GpuMatMulSettings{}, const ActivationLayerInfo & act_info = ActivationLayerInfo{})
Initialise the kernel's inputs and output.
Similar to CLMatMul::configure()
Definition at line 46 of file CLMatMul.cpp.
 {
     ARM_COMPUTE_UNUSED(settings);
     configure(CLKernelLibrary::get().get_compile_context(), lhs, rhs, output, matmul_info, settings, act_info);
 }
References arm_compute::test::validation::act_info, ARM_COMPUTE_UNUSED, CLMatMul::configure(), and CLKernelLibrary::get().
operator=() [1/2]
CLMatMul& operator= (CLMatMul &&)
Default move assignment operator.
operator=() [2/2]
CLMatMul& operator= (const CLMatMul &) delete
Prevent instances of this class from being copied (As this class contains pointers)
run()
void run () override virtual
Run the kernels contained in the function.
For CPU kernels:
Multi-threading is used for the kernels which are parallelisable.
By default std::thread::hardware_concurrency() threads are used.
Note
CPPScheduler::set_num_threads() can be used to manually set the number of threads
For OpenCL kernels:
All the kernels are enqueued on the queue associated with CLScheduler.
The queue is then flushed.
Note
The function will not block until the kernels are executed. It is the user's responsibility to wait.
Will call prepare() on first run if hasn't been done
Implements IFunction.
Definition at line 82 of file CLMatMul.cpp.
 {
     _impl->op->run(_impl->run_pack);
 }
validate()
Status validate (const ITensorInfo * lhs, const ITensorInfo * rhs, const ITensorInfo * output, const MatMulInfo & matmul_info, const ActivationLayerInfo & act_info = ActivationLayerInfo{}) static
Static function to check if given info will lead to a valid configuration of CLMatMul.
Note
All tensors must have the same data type.
Parameters
[in] lhs Left-hand side (Matrix A) tensor info. Data types supported: F16/F32/QASYMM8_SIGNED/QASYMM8.
[in] rhs Right-hand side (Matrix B) tensor info. Data types supported: same as lhs.
[out] output Output tensor info to store the result of the batched matrix multiplication. Data types supported: same as lhs.
[in] matmul_info Contains MatMul operation information described in MatMulInfo.
[in] act_info (Optional) Contains activation function and lower and upper bound values for bounded activation functions.
Definition at line 73 of file CLMatMul.cpp.
 {
     return OperatorType::validate(lhs, rhs, output, matmul_info, act_info);
 }
References arm_compute::test::validation::act_info, and ClGemm::validate().
The documentation for this class was generated from the following files:
arm_compute/runtime/CL/functions/CLMatMul.h
src/runtime/CL/functions/CLMatMul.cpp