Compute Library: SubTensorInfo Class Reference
SubTensorInfo Class Reference final
Store the sub tensor's metadata.
#include <SubTensorInfo.h>
Public Member Functions
SubTensorInfo ()
Default constructor.
SubTensorInfo (ITensorInfo *parent, TensorShape tensor_shape, Coordinates coords, bool extend_parent=false)
Default constructor.
~SubTensorInfo ()=default
Default destructor.
SubTensorInfo (const SubTensorInfo &)=default
Allow instances of this class to be copy constructed.
SubTensorInfo & operator= (const SubTensorInfo &)=default
Allow instances of this class to be copied.
SubTensorInfo (SubTensorInfo &&)=default
Allow instances of this class to be move constructed.
SubTensorInfo & operator= (SubTensorInfo &&)=default
Allow instances of this class to be moved.
Coordinates coords () const
Returns the coordinates of the sub-tensor inside the parent tensor.
std::unique_ptr< ITensorInfo > clone () const override
ITensorInfo & set_data_type (DataType data_type) override
Set the data type to the specified value.
ITensorInfo & set_data_layout (const DataLayout &data_layout) override
Set the data layout of the tensor.
ITensorInfo & set_num_channels (int num_channels) override
Set the number of channels to the specified value.
ITensorInfo & set_format (Format format) override
Set the format of an already initialized tensor.
ITensorInfo & set_tensor_shape (const TensorShape &shape) override
Set the shape of an already initialized tensor.
ITensorInfo & set_tensor_dims_state (const TensorDimsState &state) override
Set the state for each dimension of the tensor.
ITensorInfo & set_quantization_info (const QuantizationInfo &quantization_info) override
Set the quantization settings (scale and offset) of the tensor.
ITensorInfo & reset_padding () override
Resets the padding settings of the tensor.
bool auto_padding () override
Update the offset to the first element and the strides to automatically computed values.
ITensorInfo & set_lock_paddings (bool flag) override
Set the lock paddings flag of the tensor.
bool lock_paddings () const override
Get the lock paddings flag value.
bool extend_padding (const PaddingSize &padding) override
Update the offset to the first element, the strides and the total size.
size_t dimension (size_t index) const override
Return the size of the requested dimension.
size_t dimension (DataLayoutDimension dimension) const override
Return the size of the requested data layout dimension.
const Strides & strides_in_bytes () const override
The strides in bytes for accessing each dimension of the tensor.
size_t offset_first_element_in_bytes () const override
The offset from the beginning of the memory allocation to the first element of the tensor.
int32_t offset_element_in_bytes (const Coordinates &pos) const override
The offset in bytes from the beginning of the memory allocation to access the element at position (x, y, z ...)
size_t element_size () const override
Element size in bytes calculated as data_size() * num_channels()
size_t num_dimensions () const override
The number of dimensions of the tensor (rank)
size_t num_channels () const override
The number of channels for each tensor element.
const TensorShape & tensor_shape () const override
Size for each dimension of the tensor.
const TensorDimsState & tensor_dims_state () const override
State of each dimension of the tensor shape.
DataType data_type () const override
Data type used for each element of the tensor.
Format format () const override
Colour format of the image.
size_t total_size () const override
Returns the total size of the tensor in bytes.
PaddingSize padding () const override
Padding of tensor.
bool has_padding () const override
Checks if the tensor has been allocated with padding or not.
bool is_resizable () const override
Flag indicating whether the size of the tensor can be changed.
bool is_dynamic () const override
Flag indicating whether the shape of the tensor is dynamic, meaning that it can change on kernel/function execution.
bool are_values_constant () const override
Flag indicating whether the values of the tensor are constant, meaning that they can change on kernel/function execution.
ITensorInfo & set_is_resizable (bool is_resizable) override
Set the flag whether the tensor size can be changed.
ITensorInfo & set_are_values_constant (bool are_values_constant) override
Set the flag whether the tensor values can change during kernel/function execution.
ValidRegion valid_region () const override
Valid region of the tensor.
void set_valid_region (const ValidRegion &valid_region) override
Set the valid region of the tensor.
QuantizationInfo quantization_info () const override
Get the quantization settings (scale and offset) of the tensor.
DataLayout data_layout () const override
Get the data layout of the tensor.
ITensorInfo::Id id () const override
Get the workload tensor id of the tensor.
ITensorInfo & set_id (ITensorInfo::Id id) override
Set the tensor id.
Public Member Functions inherited from ITensorInfo
virtual ~ITensorInfo ()=default
Default virtual destructor.
bool has_valid_id () const
Check if the tensor id is valid.
Public Member Functions inherited from ICloneable< ITensorInfo >
virtual ~ICloneable ()=default
Default virtual desctructor.
virtual std::unique_ptr< ITensorInfo > clone () const=0
Provide a clone of the current object of class T.
Additional Inherited Members
Public Types inherited from ITensorInfo
using TensorDimsState = std::vector< int >
using Id = int32_t
An id that uniquely identifies an ITensorInfo within some domain (e.g.
Static Public Member Functions inherited from ITensorInfo
static constexpr int32_t get_dynamic_state_value ()
Get the value representing dynamic dimension state.
static constexpr int32_t get_static_state_value ()
Get the value representing static dimension state.
template<typename... Infos>
static std::pair< TensorShape, ValidRegion > broadcast_shape_and_valid_region (const Infos &...infos)
If infos are broadcast compatible tensor info's, return the broadcasted shape and the intersection of the broadcasted valid regions of the tensors.
Static Public Attributes inherited from ITensorInfo
static constexpr Id invalid_tensor_id = 0
An invalid tensor id within a domain.
Detailed Description
Store the sub tensor's metadata.
Definition at line 40 of file SubTensorInfo.h.
Constructor & Destructor Documentation
SubTensorInfo() [1/4]
SubTensorInfo ()
Default constructor.
Definition at line 58 of file SubTensorInfo.cpp.
     : _parent(nullptr),
       _tensor_shape(),
       _dims_state(),
       _coords(),
       _valid_region{Coordinates(), _tensor_shape},
       _extend_parent(false),
       _lock_paddings(false)
 {
 }
SubTensorInfo() [2/4]
SubTensorInfo (ITensorInfo * parent, TensorShape tensor_shape, Coordinates coords, bool extend_parent = false)
Default constructor.
Parameters
[in] parent Metadata of parent tensor.
[in] tensor_shape Tensor shape. Shape must fit inside parent's shape. X and Y dimensions must match the parent's ones.
[in] coords Coordinates of starting element inside parent tensor.
[in] extend_parent (Optional) Extend parent with subtensor shape if subtensor indexes out of bounds
Definition at line 69 of file SubTensorInfo.cpp.
     : _parent(parent),
       _tensor_shape(tensor_shape),
       _dims_state(),
       _coords(coords),
       _valid_region{Coordinates(), _tensor_shape},
       _extend_parent(extend_parent),
       _lock_paddings(false)
 {
     ARM_COMPUTE_ERROR_ON(parent == nullptr);
     // Check if subtensor is valid if parent is configured
     if (parent->tensor_shape().total_size() != 0 && !_extend_parent)
     {
         ARM_COMPUTE_ERROR_ON_INVALID_SUBTENSOR(parent->tensor_shape(), coords, tensor_shape);
     }
     // Initialize valid region
     _valid_region = ValidRegion{Coordinates(), _tensor_shape};
 }
~SubTensorInfo()
~SubTensorInfo () default
Default destructor.
SubTensorInfo() [3/4]
SubTensorInfo (const SubTensorInfo &) default
Allow instances of this class to be copy constructed.
SubTensorInfo() [4/4]
SubTensorInfo (SubTensorInfo &&) default
Allow instances of this class to be move constructed.
Member Function Documentation
are_values_constant()
bool are_values_constant () const inline override virtual
Flag indicating whether the values of the tensor are constant, meaning that they can change on kernel/function execution.
Returns
True if values are constant else false
Implements ITensorInfo.
Definition at line 204 of file SubTensorInfo.h.
     {
         ARM_COMPUTE_ERROR_ON(_parent == nullptr);
         return _parent->are_values_constant();
     }
References ITensorInfo::are_values_constant(), and ARM_COMPUTE_ERROR_ON.
Referenced by SubTensorInfo::set_are_values_constant().
auto_padding()
bool auto_padding () inline override virtual
Update the offset to the first element and the strides to automatically computed values.
Note
The padding used by this method is really conservative so that the tensor can be used for most functions.
Returns
True if the strides or the offset to the first element have changed.
Implements ITensorInfo.
Definition at line 113 of file SubTensorInfo.h.
     {
         ARM_COMPUTE_ERROR_ON(_parent == nullptr);
         return _parent->auto_padding();
     };
References ARM_COMPUTE_ERROR_ON, and ITensorInfo::auto_padding().
clone()
std::unique_ptr< ITensorInfo > clone () const override
Definition at line 90 of file SubTensorInfo.cpp.
 {
     // Clone creates a TensorInfo object from SubTensorInfo's parent which will conclude to a TensorInfo
     // For now it does not make sense to copy a SubTensorInfo explicitly
     ARM_COMPUTE_ERROR_ON(_parent == nullptr);
     auto clone_obj = _parent->clone();
     clone_obj->set_tensor_shape(_tensor_shape);
     clone_obj->set_valid_region(_valid_region);
     return clone_obj;
 }
References ARM_COMPUTE_ERROR_ON, and ICloneable< T >::clone().
coords()
Coordinates coords () const inline
Returns the coordinates of the sub-tensor inside the parent tensor.
Returns
Sub-tensor coordinates
Definition at line 68 of file SubTensorInfo.h.
     {
         return _coords;
     }
data_layout()
DataLayout data_layout () const inline override virtual
Get the data layout of the tensor.
Returns
A DataLayout containing the layout data information.
Implements ITensorInfo.
Definition at line 240 of file SubTensorInfo.h.
     {
         ARM_COMPUTE_ERROR_ON(_parent == nullptr);
         return _parent->data_layout();
     }
References ARM_COMPUTE_ERROR_ON, and ITensorInfo::data_layout().
Referenced by SubTensorInfo::set_data_layout().
data_type()
DataType data_type () const inline override virtual
Data type used for each element of the tensor.
Returns
Tensor data type
Implements ITensorInfo.
Definition at line 169 of file SubTensorInfo.h.
     {
         ARM_COMPUTE_ERROR_ON(_parent == nullptr);
         return _parent->data_type();
     }
References ARM_COMPUTE_ERROR_ON, and ITensorInfo::data_type().
Referenced by SubTensorInfo::set_data_type().
dimension() [1/2]
size_t dimension (DataLayoutDimension dimension) const inline override virtual
Return the size of the requested data layout dimension.
Parameters
[in] dimension DataLayoutDimension of the dimension
Returns
Dimension of the requested dimension
Implements ITensorInfo.
Definition at line 129 of file SubTensorInfo.h.
     {
         ARM_COMPUTE_ERROR_ON(_parent == nullptr);
         return get_data_layout_dimension_index(_parent->data_layout(), dimension);
     }
References ARM_COMPUTE_ERROR_ON, ITensorInfo::data_layout(), SubTensorInfo::dimension(), and arm_compute::get_data_layout_dimension_index().
dimension() [2/2]
size_t dimension (size_t index) const inline override virtual
Return the size of the requested dimension.
Parameters
[in] index Index of the dimension
Returns
Dimension of the requested dimension
Implements ITensorInfo.
Definition at line 125 of file SubTensorInfo.h.
     {
         return _tensor_shape[index];
     }
Referenced by SubTensorInfo::dimension().
element_size()
size_t element_size () const inline override virtual
Element size in bytes calculated as data_size() * num_channels()
Returns
The size of one element in bytes
Implements ITensorInfo.
Definition at line 145 of file SubTensorInfo.h.
     {
         ARM_COMPUTE_ERROR_ON(_parent == nullptr);
         return _parent->element_size();
     }
References ARM_COMPUTE_ERROR_ON, and ITensorInfo::element_size().
extend_padding()
bool extend_padding (const PaddingSize & padding) override virtual
Update the offset to the first element, the strides and the total size.
Note
This function can only increase the offset, strides and total size.
Parameters
[in] padding Padding around the XY plane in number of elements.
Returns
True if the strides, offset and total size have changed.
Implements ITensorInfo.
Definition at line 140 of file SubTensorInfo.cpp.
 {
     ARM_COMPUTE_ERROR_ON(_lock_paddings);
     ARM_COMPUTE_ERROR_ON(_parent == nullptr);
     ARM_COMPUTE_ERROR_ON(!_parent->is_resizable());
     ARM_COMPUTE_ERROR_ON(_parent->total_size() == 0);
     // Check that you do not extend padding on sub-tensors unless XY shape matches parent tensor
     if (!_extend_parent && (padding.left || padding.right))
     {
         ARM_COMPUTE_ERROR_ON(_parent->tensor_shape().x() != tensor_shape().x());
     }
     if (!_extend_parent && (padding.top || padding.bottom))
     {
         ARM_COMPUTE_ERROR_ON(_parent->tensor_shape().y() != tensor_shape().y());
     }
     // Extend parent padding if required
     return _parent->extend_padding(padding);
 }
References ARM_COMPUTE_ERROR_ON, BorderSize::bottom, ITensorInfo::extend_padding(), ITensorInfo::is_resizable(), BorderSize::left, SubTensorInfo::padding(), BorderSize::right, SubTensorInfo::tensor_shape(), ITensorInfo::tensor_shape(), BorderSize::top, ITensorInfo::total_size(), Dimensions< T >::x(), and Dimensions< T >::y().
Referenced by arm_compute::test::validation::TEST_CASE().
format()
Format format () const inline override virtual
Colour format of the image.
Returns
Colour format of the image
Implements ITensorInfo.
Definition at line 174 of file SubTensorInfo.h.
     {
         ARM_COMPUTE_ERROR_ON(_parent == nullptr);
         return _parent->format();
     }
References ARM_COMPUTE_ERROR_ON, and ITensorInfo::format().
Referenced by SubTensorInfo::set_format().
has_padding()
bool has_padding () const inline override virtual
Checks if the tensor has been allocated with padding or not.
Returns
True if padding is allocated in the tensor, otherwise false.
Implements ITensorInfo.
Definition at line 189 of file SubTensorInfo.h.
     {
         ARM_COMPUTE_ERROR_ON(_parent == nullptr);
         return _parent->has_padding();
     }
References ARM_COMPUTE_ERROR_ON, and ITensorInfo::has_padding().
id()
ITensorInfo::Id id () const inline override virtual
Get the workload tensor id of the tensor.
Returns
Workload tensor id of the tensor
Implements ITensorInfo.
Definition at line 245 of file SubTensorInfo.h.
     {
         ARM_COMPUTE_ERROR_ON(_parent == nullptr);
         return _parent->id();
     }
References ARM_COMPUTE_ERROR_ON, and ITensorInfo::id().
is_dynamic()
bool is_dynamic () const inline override virtual
Flag indicating whether the shape of the tensor is dynamic, meaning that it can change on kernel/function execution.
Returns
True if its dynamic else false
Implements ITensorInfo.
Definition at line 199 of file SubTensorInfo.h.
     {
         ARM_COMPUTE_ERROR_ON(_parent == nullptr);
         return _parent->is_dynamic();
     }
References ARM_COMPUTE_ERROR_ON, and ITensorInfo::is_dynamic().
is_resizable()
bool is_resizable () const inline override virtual
Flag indicating whether the size of the tensor can be changed.
Returns
True if the tensor size can be changed.
Implements ITensorInfo.
Definition at line 194 of file SubTensorInfo.h.
     {
         ARM_COMPUTE_ERROR_ON(_parent == nullptr);
         return _parent->is_resizable();
     }
References ARM_COMPUTE_ERROR_ON, and ITensorInfo::is_resizable().
Referenced by SubTensorInfo::set_is_resizable().
lock_paddings()
bool lock_paddings () const override virtual
Get the lock paddings flag value.
Returns
lock paddings flag value
Implements ITensorInfo.
Definition at line 135 of file SubTensorInfo.cpp.
 {
     return _lock_paddings;
 }
num_channels()
size_t num_channels () const inline override virtual
The number of channels for each tensor element.
Returns
The number of channels for each tensor element
Implements ITensorInfo.
Definition at line 154 of file SubTensorInfo.h.
     {
         ARM_COMPUTE_ERROR_ON(_parent == nullptr);
         return _parent->num_channels();
     }
References ARM_COMPUTE_ERROR_ON, and ITensorInfo::num_channels().
Referenced by SubTensorInfo::set_num_channels().
num_dimensions()
size_t num_dimensions () const inline override virtual
The number of dimensions of the tensor (rank)
Returns
The number of dimensions of the tensor (rank)
Implements ITensorInfo.
Definition at line 150 of file SubTensorInfo.h.
     {
         return _tensor_shape.num_dimensions();
     }
References Dimensions< T >::num_dimensions().
offset_element_in_bytes()
int32_t offset_element_in_bytes (const Coordinates & pos) const override virtual
The offset in bytes from the beginning of the memory allocation to access the element at position (x, y, z ...)
Parameters
[in] pos Vector with the coordinates of the element to access. The size of this vector must be equal to the number of dimensions of the tensor
Returns
Offset in bytes from the beginning of the memory allocation to access the element (x, y, z, ...)
Implements ITensorInfo.
Definition at line 161 of file SubTensorInfo.cpp.
 {
     ARM_COMPUTE_ERROR_ON_COORDINATES_DIMENSIONS_GTE(pos, _tensor_shape.num_dimensions());
     int32_t        offset  = offset_first_element_in_bytes();
     const Strides &strides = strides_in_bytes();
     for (size_t i = 0; i < _tensor_shape.num_dimensions(); ++i)
     {
         offset += pos[i] * strides[i];
     }
     return offset;
 }
References ARM_COMPUTE_ERROR_ON_COORDINATES_DIMENSIONS_GTE, Dimensions< T >::num_dimensions(), offset(), SubTensorInfo::offset_first_element_in_bytes(), and SubTensorInfo::strides_in_bytes().
offset_first_element_in_bytes()
size_t offset_first_element_in_bytes () const inline override virtual
The offset from the beginning of the memory allocation to the first element of the tensor.
This can be used to access efficiently elements in a 2D tensor
Returns
The offset in bytes to access the first element of the tensor.
Implements ITensorInfo.
Definition at line 139 of file SubTensorInfo.h.
     {
         ARM_COMPUTE_ERROR_ON(_parent == nullptr);
         return _parent->offset_element_in_bytes(_coords);
     }
References ARM_COMPUTE_ERROR_ON, and ITensorInfo::offset_element_in_bytes().
Referenced by SubTensorInfo::offset_element_in_bytes().
operator=() [1/2]
SubTensorInfo& operator= (const SubTensorInfo &) default
Allow instances of this class to be copied.
operator=() [2/2]
SubTensorInfo& operator= (SubTensorInfo &&) default
Allow instances of this class to be moved.
padding()
PaddingSize padding () const inline override virtual
Padding of tensor.
Returns
Padding.
Implements ITensorInfo.
Definition at line 184 of file SubTensorInfo.h.
     {
         ARM_COMPUTE_ERROR_ON(_parent == nullptr);
         return _parent->padding();
     }
References ARM_COMPUTE_ERROR_ON, and ITensorInfo::padding().
Referenced by SubTensorInfo::extend_padding().
quantization_info()
QuantizationInfo quantization_info () const inline override virtual
Get the quantization settings (scale and offset) of the tensor.
Returns
A QuantizationInfo containing the scale and offset.
Implements ITensorInfo.
Definition at line 235 of file SubTensorInfo.h.
     {
         ARM_COMPUTE_ERROR_ON(_parent == nullptr);
         return _parent->quantization_info();
     }
References ARM_COMPUTE_ERROR_ON, and ITensorInfo::quantization_info().
Referenced by SubTensorInfo::set_quantization_info().
reset_padding()
ITensorInfo& reset_padding () inline override virtual
Resets the padding settings of the tensor.
Returns
Reference to this ITensorInfo object
Implements ITensorInfo.
Definition at line 107 of file SubTensorInfo.h.
     {
         ARM_COMPUTE_ERROR_ON(_parent == nullptr);
         _parent->reset_padding();
         return *this;
     }
References ARM_COMPUTE_ERROR_ON, and ITensorInfo::reset_padding().
set_are_values_constant()
ITensorInfo& set_are_values_constant (bool are_values_constant) inline override virtual
Set the flag whether the tensor values can change during kernel/function execution.
Parameters
[in] are_values_constant Flag that marks the tensor values if they can be changed or not.
Returns
Reference to this ITensorInfo object
Implements ITensorInfo.
Definition at line 215 of file SubTensorInfo.h.
     {
         ARM_COMPUTE_ERROR_ON(_parent == nullptr);
         _parent->set_are_values_constant(are_values_constant);
         return *this;
     }
References SubTensorInfo::are_values_constant(), ARM_COMPUTE_ERROR_ON, and ITensorInfo::set_are_values_constant().
set_data_layout()
ITensorInfo& set_data_layout (const DataLayout & data_layout) inline override virtual
Set the data layout of the tensor.
Parameters
[in] data_layout DataLayout containing the layout data information.
Returns
Reference to this ITensorInfo object
Implements ITensorInfo.
Definition at line 81 of file SubTensorInfo.h.
     {
         ARM_COMPUTE_ERROR_ON(_parent == nullptr);
         _parent->set_data_layout(data_layout);
         return *this;
     };
References ARM_COMPUTE_ERROR_ON, SubTensorInfo::data_layout(), and ITensorInfo::set_data_layout().
set_data_type()
ITensorInfo& set_data_type (DataType data_type) inline override virtual
Set the data type to the specified value.
Warning
This resets the format to UNKNOWN.
Parameters
[in] data_type The new data type.
Returns
Reference to this ITensorInfo object
Implements ITensorInfo.
Definition at line 75 of file SubTensorInfo.h.
     {
         ARM_COMPUTE_ERROR_ON(_parent == nullptr);
         _parent->set_data_type(data_type);
         return *this;
     };
References ARM_COMPUTE_ERROR_ON, SubTensorInfo::data_type(), and ITensorInfo::set_data_type().
set_format()
ITensorInfo& set_format (Format format) inline override virtual
Set the format of an already initialized tensor.
Note
If the data type has already been configured (i.e. not UNKNOWN) it must match the new format. If data type hasn't been configured it will be based on the format.
Parameters
[in] format Single-plane format of the tensor.
Returns
Reference to this ITensorInfo object
Implements ITensorInfo.
Definition at line 93 of file SubTensorInfo.h.
     {
         ARM_COMPUTE_ERROR_ON(_parent == nullptr);
         _parent->set_format(format);
         return *this;
     };
References ARM_COMPUTE_ERROR_ON, SubTensorInfo::format(), and ITensorInfo::set_format().
set_id()
ITensorInfo& set_id (ITensorInfo::Id id) inline override virtual
Set the tensor id.
Implements ITensorInfo.
Definition at line 250 of file SubTensorInfo.h.
     {
         ARM_COMPUTE_ERROR_ON(_parent == nullptr);
         _parent->set_id(id);
         return *this;
     }
References ARM_COMPUTE_ERROR_ON, and ITensorInfo::set_id().
set_is_resizable()
ITensorInfo& set_is_resizable (bool is_resizable) inline override virtual
Set the flag whether the tensor size can be changed.
Parameters
[in] is_resizable Flag that marks the tensor if it can be changed or not.
Returns
Reference to this ITensorInfo object
Implements ITensorInfo.
Definition at line 209 of file SubTensorInfo.h.
     {
         ARM_COMPUTE_ERROR_ON(_parent == nullptr);
         _parent->set_is_resizable(is_resizable);
         return *this;
     }
References ARM_COMPUTE_ERROR_ON, SubTensorInfo::is_resizable(), and ITensorInfo::set_is_resizable().
set_lock_paddings()
ITensorInfo & set_lock_paddings (bool flag) override virtual
Set the lock paddings flag of the tensor.
It should be set to True, when the tensor could be mapped to camera or frame buffer.
Returns
Reference to this ITensorInfo object
Implements ITensorInfo.
Definition at line 129 of file SubTensorInfo.cpp.
 {
     _lock_paddings = flag;
     return *this;
 }
Referenced by arm_compute::test::validation::TEST_CASE().
set_num_channels()
ITensorInfo& set_num_channels (int num_channels) inline override virtual
Set the number of channels to the specified value.
Warning
This resets the format to UNKNOWN.
Parameters
[in] num_channels New number of channels.
Returns
Reference to this ITensorInfo object
Implements ITensorInfo.
Definition at line 87 of file SubTensorInfo.h.
     {
         ARM_COMPUTE_ERROR_ON(_parent == nullptr);
         _parent->set_num_channels(num_channels);
         return *this;
     };
References ARM_COMPUTE_ERROR_ON, SubTensorInfo::num_channels(), and ITensorInfo::set_num_channels().
set_quantization_info()
ITensorInfo& set_quantization_info (const QuantizationInfo & quantization_info) inline override virtual
Set the quantization settings (scale and offset) of the tensor.
Parameters
[in] quantization_info QuantizationInfo containing the scale and offset
Returns
Reference to this ITensorInfo object
Implements ITensorInfo.
Definition at line 101 of file SubTensorInfo.h.
     {
         ARM_COMPUTE_ERROR_ON(_parent == nullptr);
         _parent->set_quantization_info(quantization_info);
         return *this;
     }
References ARM_COMPUTE_ERROR_ON, SubTensorInfo::quantization_info(), and ITensorInfo::set_quantization_info().
set_tensor_dims_state()
ITensorInfo & set_tensor_dims_state (const TensorDimsState & state) override virtual
Set the state for each dimension of the tensor.
This sets the state of each dimension of the shape in terms of dynamic behavior using -1 where appropriate. The index in the state is a 1 to 1 mapping with the shape dimension index. For example if you want to express [?, 3, 3] as a dynamic input then [-1, 3, 3] has to be set as a state
Parameters
[in] state Tensor dimensions state
Returns
Reference to this ITensorInfo object
Implements ITensorInfo.
Definition at line 122 of file SubTensorInfo.cpp.
 {
     ARM_COMPUTE_ERROR_ON(_parent == nullptr);
     _dims_state = state;
     return *this;
 }
References ARM_COMPUTE_ERROR_ON.
set_tensor_shape()
ITensorInfo & set_tensor_shape (const TensorShape & shape) override virtual
Set the shape of an already initialized tensor.
Warning
Changing the shape requires to recompute the strides and is therefore only possible if the tensor hasn't been allocated yet.
Parameters
[in] shape New tensor shape.
Returns
Reference to this ITensorInfo object
Implements ITensorInfo.
Definition at line 101 of file SubTensorInfo.cpp.
 {
     ARM_COMPUTE_ERROR_ON(_parent == nullptr);
     // Check if subtensor is valid if parent is configured
     if (_parent->tensor_shape().total_size() != 0 && !_extend_parent)
     {
         ARM_COMPUTE_ERROR_ON_INVALID_SUBTENSOR(_parent->tensor_shape(), _coords, shape);
         _valid_region = ValidRegion{_coords, shape};
     }
     else if (_extend_parent) // Extend parent shape, configure if specified
     {
         ARM_COMPUTE_ERROR_ON((_parent->data_type() == DataType::UNKNOWN) && (_parent->format() == Format::UNKNOWN));
         TensorShape parent_extended_shape = extend_parent_shape(_parent->tensor_shape(), shape, _coords);
         _parent->set_tensor_shape(parent_extended_shape);
         _parent->set_valid_region(ValidRegion{Coordinates(), parent_extended_shape});
     }
     _tensor_shape = shape;
     return *this;
 }
References ARM_COMPUTE_ERROR_ON, ARM_COMPUTE_ERROR_ON_INVALID_SUBTENSOR, ITensorInfo::data_type(), ITensorInfo::format(), ITensorInfo::set_tensor_shape(), ITensorInfo::set_valid_region(), arm_compute::test::validation::shape, ITensorInfo::tensor_shape(), TensorShape::total_size(), and arm_compute::UNKNOWN.
set_valid_region()
void set_valid_region (const ValidRegion & valid_region) inline override virtual
Set the valid region of the tensor.
Parameters
[in] valid_region Valid region to set.
Implements ITensorInfo.
Definition at line 225 of file SubTensorInfo.h.
     {
         ARM_COMPUTE_ERROR_ON(_parent == nullptr);
         // Check if subtensor is valid if parent is configured
         if (_parent->tensor_shape().total_size() != 0)
         {
             ARM_COMPUTE_ERROR_ON_INVALID_SUBTENSOR_VALID_REGION(_parent->valid_region(), valid_region);
         }
         _valid_region = valid_region;
     }
References ARM_COMPUTE_ERROR_ON, ARM_COMPUTE_ERROR_ON_INVALID_SUBTENSOR_VALID_REGION, ITensorInfo::tensor_shape(), TensorShape::total_size(), SubTensorInfo::valid_region(), and ITensorInfo::valid_region().
strides_in_bytes()
const Strides& strides_in_bytes () const inline override virtual
The strides in bytes for accessing each dimension of the tensor.
Returns
Strides in bytes for each tensor dimension
Implements ITensorInfo.
Definition at line 134 of file SubTensorInfo.h.
     {
         ARM_COMPUTE_ERROR_ON(_parent == nullptr);
         return _parent->strides_in_bytes();
     }
References ARM_COMPUTE_ERROR_ON, and ITensorInfo::strides_in_bytes().
Referenced by SubTensorInfo::offset_element_in_bytes().
tensor_dims_state()
const TensorDimsState& tensor_dims_state () const inline override virtual
State of each dimension of the tensor shape.
Returns
A vector with the state for each dimension of the tensor, where -1 specifies dynamic dimension
Implements ITensorInfo.
Definition at line 164 of file SubTensorInfo.h.
     {
         ARM_COMPUTE_ERROR_ON(_parent == nullptr);
         return _dims_state;
     }
References ARM_COMPUTE_ERROR_ON.
tensor_shape()
const TensorShape& tensor_shape () const inline override virtual
Size for each dimension of the tensor.
Returns
A vector with the size for each dimension of the tensor
Implements ITensorInfo.
Definition at line 159 of file SubTensorInfo.h.
     {
         ARM_COMPUTE_ERROR_ON(_parent == nullptr);
         return _tensor_shape;
     }
References ARM_COMPUTE_ERROR_ON.
Referenced by SubTensorInfo::extend_padding().
total_size()
size_t total_size () const inline override virtual
Returns the total size of the tensor in bytes.
Returns
Total size of the tensor in bytes.
Implements ITensorInfo.
Definition at line 179 of file SubTensorInfo.h.
     {
         ARM_COMPUTE_ERROR_ON(_parent == nullptr);
         return _parent->total_size();
     }
References ARM_COMPUTE_ERROR_ON, and ITensorInfo::total_size().
valid_region()
ValidRegion valid_region () const inline override virtual
Valid region of the tensor.
All elements in the valid region have defined values, i.e. are not undefined.
Returns
The valid region.
Implements ITensorInfo.
Definition at line 221 of file SubTensorInfo.h.
     {
         return _valid_region;
     }
Referenced by SubTensorInfo::set_valid_region().
The documentation for this class was generated from the following files:
arm_compute/core/SubTensorInfo.h
src/core/SubTensorInfo.cpp