Compute Library: Activation Class Reference
Activation Class Reference
#include <Acl.hpp>
Public Member Functions
Activation (Context &ctx, const TensorDescriptor &src, const TensorDescriptor &dst, const ActivationDesc &desc, StatusCode *status=nullptr)
Public Member Functions inherited from Operator
StatusCode run (Queue &queue, TensorPack &pack)
Run an operator on a given input list.
Public Member Functions inherited from ObjectBase< AclOperator_ >
~ObjectBase ()=default
Destructor.
ObjectBase (const ObjectBase< AclOperator_ > &)=default
Copy constructor.
ObjectBase (ObjectBase< AclOperator_ > &&)=default
Move Constructor.
ObjectBase< AclOperator_ > & operator= (const ObjectBase< AclOperator_ > &)=default
Copy assignment operator.
ObjectBase< AclOperator_ > & operator= (ObjectBase< AclOperator_ > &&)=default
Move assignment operator.
void reset (AclOperator_ *val)
Reset object value.
const AclOperator_ * get () const
Access uderlying object.
AclOperator_ * get ()
Access uderlying object.
Detailed Description
Definition at line 775 of file Acl.hpp.
Constructor & Destructor Documentation
Activation()
Activation (Context & ctx, const TensorDescriptor & src, const TensorDescriptor & dst, const ActivationDesc & desc, StatusCode * status = nullptr) inline
Definition at line 778 of file Acl.hpp.
     {
         AclOperator op;
         const auto  st = detail::as_enum<StatusCode>(AclActivation(&op, ctx.get(), src.get(), dst.get(), desc));
         reset(op);
         report_status(st, "[Compute Library] Failure during Activation operator creation");
         if (status)
         {
             *status = st;
         }
     }
References AclActivation(), arm_compute::test::validation::dst, ObjectBase< T >::get(), ObjectBase< AclOperator_ >::reset(), and arm_compute::test::validation::src.
The documentation for this class was generated from the following file:
arm_compute/Acl.hpp