Compute Library: CLNormalizationLayer Class Reference
CLNormalizationLayer Class Reference
Basic function to compute a normalization layer.
#include <CLNormalizationLayer.h>
Public Member Functions
CLNormalizationLayer ()
Default constructor.
CLNormalizationLayer (const CLNormalizationLayer &)=delete
Prevent instances of this class from being copied.
CLNormalizationLayer & operator= (const CLNormalizationLayer &)=delete
Prevent instances of this class from being copied.
CLNormalizationLayer (CLNormalizationLayer &&)=delete
Prevent instances of this class to be moved.
CLNormalizationLayer & operator= (CLNormalizationLayer &&)=delete
Prevent instances of this class to be moved.
~CLNormalizationLayer ()
Default destructor.
void configure (ICLTensor *input, ICLTensor *output, const NormalizationLayerInfo &norm_info)
Set the input and output tensors.
void configure (const CLCompileContext &compile_context, ICLTensor *input, ICLTensor *output, const NormalizationLayerInfo &norm_info)
Set the input and output tensors.
void run () override
Run the kernels contained in the function.
Public Member Functions inherited from IFunction
virtual ~IFunction ()=default
Destructor.
virtual void prepare ()
Prepare the function for executing.
Static Public Member Functions
static Status validate (const ITensorInfo *input, const ITensorInfo *output, const NormalizationLayerInfo &norm_info)
Static function to check if given info will lead to a valid configuration of CLNormalizationLayer.
Detailed Description
Basic function to compute a normalization layer.
This function calls the following CL kernels:
CLFillBorderKernel
CLNormalizationLayerKernel
Definition at line 47 of file CLNormalizationLayer.h.
Constructor & Destructor Documentation
CLNormalizationLayer() [1/3]
CLNormalizationLayer ()
Default constructor.
Definition at line 40 of file CLNormalizationLayer.cpp.
     : _norm_kernel(std::make_unique<CLNormalizationLayerKernel>()),
       _border_handler(std::make_unique<CLFillBorderKernel>())
 {
 }
CLNormalizationLayer() [2/3]
CLNormalizationLayer (const CLNormalizationLayer &) delete
Prevent instances of this class from being copied.
CLNormalizationLayer() [3/3]
CLNormalizationLayer (CLNormalizationLayer &&) delete
Prevent instances of this class to be moved.
~CLNormalizationLayer()
~CLNormalizationLayer () default
Default destructor.
Member Function Documentation
configure() [1/2]
void configure (const CLCompileContext & compile_context, ICLTensor * input, ICLTensor * output, const NormalizationLayerInfo & norm_info)
Set the input and output tensors.
Parameters
[in] compile_context The compile context to be used.
[in,out] input Source tensor. 3 lower dims represent a single input with dimensions [width, height, IFM], and an optional 4th dimension for batch of inputs. Data types supported: F16/F32 (Written to by the border handler). Data layouts supported: NCHW/NHWC.
[out] output Destination tensor. Dimensions, data type and number of channels must match the input ones. Data types supported: same as input. Data layouts supported: same as input.
[in] norm_info Normalization layer information like the normalization type, normalization size and other parameters.
Definition at line 53 of file CLNormalizationLayer.cpp.
 {
     ARM_COMPUTE_ERROR_ON(input == nullptr);
     ARM_COMPUTE_LOG_PARAMS(input, output, norm_info);
     // Configure normalization kernel
     _norm_kernel->configure(compile_context, input, output, norm_info);
     if (!_norm_kernel->border_size().empty())
     {
         // Fill the border by 3 elements since we need vload4 in the IN_MAP normalization kernel
         _border_handler->configure(compile_context, input, _norm_kernel->border_size(), BorderMode::CONSTANT,
                                    PixelValue());
     }
 }
References ARM_COMPUTE_ERROR_ON, ARM_COMPUTE_LOG_PARAMS, arm_compute::CONSTANT, and arm_compute::test::validation::input.
configure() [2/2]
void configure (ICLTensor * input, ICLTensor * output, const NormalizationLayerInfo & norm_info)
Set the input and output tensors.
Valid data layouts:
NHWC
NCHW
Valid data type configurations:
src dst
F32 F32
F16 F16
Parameters
[in,out] input Source tensor. 3 lower dims represent a single input with dimensions [width, height, IFM], and an optional 4th dimension for batch of inputs. Data types supported: F16/F32 (Written to by the border handler). Data layouts supported: NCHW/NHWC.
[out] output Destination tensor. Dimensions, data type and number of channels must match the input ones. Data types supported: same as input. Data layouts supported: same as input.
[in] norm_info Normalization layer information like the normalization type, normalization size and other parameters.
Definition at line 48 of file CLNormalizationLayer.cpp.
 {
     configure(CLKernelLibrary::get().get_compile_context(), input, output, norm_info);
 }
References CLKernelLibrary::get(), and arm_compute::test::validation::input.
operator=() [1/2]
CLNormalizationLayer& operator= (CLNormalizationLayer &&) delete
Prevent instances of this class to be moved.
operator=() [2/2]
CLNormalizationLayer& operator= (const CLNormalizationLayer &) delete
Prevent instances of this class from being copied.
run()
void run () override virtual
Run the kernels contained in the function.
For CPU kernels:
Multi-threading is used for the kernels which are parallelisable.
By default std::thread::hardware_concurrency() threads are used.
Note
CPPScheduler::set_num_threads() can be used to manually set the number of threads
For OpenCL kernels:
All the kernels are enqueued on the queue associated with CLScheduler.
The queue is then flushed.
Note
The function will not block until the kernels are executed. It is the user's responsibility to wait.
Will call prepare() on first run if hasn't been done
Implements IFunction.
Definition at line 79 of file CLNormalizationLayer.cpp.
 {
     if (!_norm_kernel->border_size().empty())
     {
         // Run border handler
         CLScheduler::get().enqueue(*_border_handler, false);
     }
     // Run normalization kernel
     CLScheduler::get().enqueue(*_norm_kernel);
 }
References CLScheduler::enqueue(), and CLScheduler::get().
validate()
Status validate (const ITensorInfo * input, const ITensorInfo * output, const NormalizationLayerInfo & norm_info) static
Static function to check if given info will lead to a valid configuration of CLNormalizationLayer.
Parameters
[in] input Source tensor. 3 lower dims represent a single input with dimensions [width, height, IFM], and an optional 4th dimension for batch of inputs. Data types supported: F16/F32. Data layouts supported: NCHW/NHWC.
[in] output Destination tensor. Dimensions, data type and number of channels must match the input ones. Data layouts supported: same as input.
[in] norm_info Normalization layer information like the normalization type, normalization size and other parameters.
Returns
a status
Definition at line 72 of file CLNormalizationLayer.cpp.
 {
     return CLNormalizationLayerKernel::validate(input, output, norm_info);
 }
References arm_compute::test::validation::input, and CLNormalizationLayerKernel::validate().
The documentation for this class was generated from the following files:
arm_compute/runtime/CL/functions/CLNormalizationLayer.h
src/runtime/CL/functions/CLNormalizationLayer.cpp