Compute Library: Shell Class Reference
Shell Class Reference
Public Member Functions
def __init__ (self, is_interactive=False)
def reset_path (self)
def set_env (self, key, value)
def append_env (self, key, value)
def prepend_env (self, key, value)
def run (self, cmd)
def run_to_str (self, cmd)
def cd (self, dirname)
def save_cwd (self)
def restore_cwd (self)
def run_single_interactive (self, cmd)
def run_single (self, cmd)
def run_single_to_str_no_output_check (self, cmd)
def run_single_to_str (self, cmd)
Data Fields
line
env
initial_path
is_interactive
cwd
Detailed Description
Definition at line 31 of file Shell.py.
Constructor & Destructor Documentation
__init__()
def __init__ (self, is_interactive = False)
Definition at line 32 of file Shell.py.
     def __init__(self, is_interactive=False):
         self.line=""
         self.env=os.environ.copy()
         self.initial_path = self.env["PATH"]
         self.save_cwd()
         self.is_interactive = is_interactive
Member Function Documentation
append_env()
def append_env (self, key, value)
Definition at line 45 of file Shell.py.
     def append_env(self, key, value):
         logger.debug("Appending '%s' to '%s'" % (value, key))
         if key not in list(self.env.keys()):
             self.set_env(key,value)
         else:
             self.env[key] += ":"+value
References Shell.env, and Shell.set_env().
cd()
def cd (self, dirname)
Definition at line 71 of file Shell.py.
     def cd(self, dirname):
         os.chdir(dirname)
Referenced by Shell.restore_cwd().
prepend_env()
def prepend_env (self, key, value)
Definition at line 51 of file Shell.py.
     def prepend_env(self, key, value):
         logger.debug("Prepending '%s' to '%s'" % (value, key))
         if key not in list(self.env.keys()):
             self.set_env(key,value)
         else:
             self.env[key] = value+":"+self.env[key]
References Shell.env, and Shell.set_env().
reset_path()
def reset_path (self)
Definition at line 39 of file Shell.py.
     def reset_path(self):
         self.env["PATH"]=self.initial_path
References Shell.env, and Shell.initial_path.
restore_cwd()
def restore_cwd (self)
Definition at line 77 of file Shell.py.
     def restore_cwd(self):
         self.cd( self.cwd )
References Shell.cd(), and Shell.cwd.
run()
def run (self, cmd)
Definition at line 57 of file Shell.py.
     def run(self, cmd):
         if isinstance(cmd, list):
             for c in cmd:
                 self.run_single(c)
         else:
             self.run_single(cmd)
References Shell.run_single().
run_single()
def run_single (self, cmd)
Definition at line 84 of file Shell.py.
     def run_single(self,cmd):
         if self.is_interactive:
             self.run_single_interactive(cmd)
         else:
             self.run_single_to_str(cmd)
References Shell.is_interactive, Shell.run_single_interactive(), and Shell.run_single_to_str().
Referenced by Shell.run().
run_single_interactive()
def run_single_interactive (self, cmd)
Definition at line 80 of file Shell.py.
     def run_single_interactive(self,cmd):
         subprocess.check_call(cmd, env=self.env,stderr=subprocess.STDOUT, shell=True)
         logger.debug("%s returned" % cmd)
References Shell.env.
Referenced by Shell.run_single().
run_single_to_str()
def run_single_to_str (self, cmd)
Definition at line 100 of file Shell.py.
     def run_single_to_str(self,cmd):
         out = subprocess.check_output(cmd, env=self.env, stderr=subprocess.STDOUT, shell=True).decode('utf-8')
         if (len(out.strip()) > 0):
             logger.debug(out)
         logger.debug("%s returned" % cmd)
         return out
References Shell.env.
Referenced by Shell.run_single(), and Shell.run_to_str().
run_single_to_str_no_output_check()
def run_single_to_str_no_output_check (self, cmd)
Definition at line 90 of file Shell.py.
     def run_single_to_str_no_output_check(self,cmd):
         try:
             out = subprocess.check_output(cmd, env=self.env, stderr=subprocess.STDOUT, shell=True)
         except subprocess.CalledProcessError as cpe:
             out = cpe.output
         if (len(out.strip()) > 0):
             logger.debug(out)
         logger.debug("%s returned" % cmd)
         return out
References Shell.env.
run_to_str()
def run_to_str (self, cmd)
Definition at line 63 of file Shell.py.
     def run_to_str(self, cmd):
         out = ""
         if isinstance(cmd, list):
             for c in cmd:
                 out += self.run_single_to_str(c)
         else:
             out = self.run_single_to_str(cmd)
         return out
References Shell.run_single_to_str().
save_cwd()
def save_cwd (self)
Definition at line 74 of file Shell.py.
     def save_cwd(self):
         self.cwd = os.getcwd()
set_env()
def set_env (self, key, value)
Definition at line 42 of file Shell.py.
     def set_env(self, key, value):
         self.env[key] = value
References Shell.env.
Referenced by Shell.append_env(), and Shell.prepend_env().
Field Documentation
cwd
cwd
Definition at line 75 of file Shell.py.
Referenced by Shell.restore_cwd().
env
env
Definition at line 34 of file Shell.py.
Referenced by Shell.append_env(), Shell.prepend_env(), Shell.reset_path(), Shell.run_single_interactive(), Shell.run_single_to_str(), Shell.run_single_to_str_no_output_check(), and Shell.set_env().
initial_path
initial_path
Definition at line 35 of file Shell.py.
Referenced by Shell.reset_path().
is_interactive
is_interactive
Definition at line 37 of file Shell.py.
Referenced by Shell.run_single().
line
line
Definition at line 33 of file Shell.py.
The documentation for this class was generated from the following file:
scripts/modules/Shell.py