Compute Library: NEReverseKernel Class Reference
NEReverseKernel Class Reference
Interface for the reverse layer kernel.
#include <NEReverseKernel.h>
Public Member Functions
const char * name () const override
Name of the kernel.
NEReverseKernel ()
Default constructor.
NEReverseKernel (const NEReverseKernel &)=delete
Prevent instances of this class from being copied (As this class contains pointers)
NEReverseKernel & operator= (const NEReverseKernel &)=delete
Prevent instances of this class from being copied (As this class contains pointers)
NEReverseKernel (NEReverseKernel &&)=default
Allow instances of this class to be moved.
NEReverseKernel & operator= (NEReverseKernel &&)=default
Allow instances of this class to be moved.
~NEReverseKernel ()=default
Default destructor.
void configure (const ITensor *input, ITensor *output, const ITensor *axis, bool use_inverted_axis)
Initialise the kernel's inputs and output.
void run (const Window &window, const ThreadInfo &info) override
Execute the kernel on the passed window.
Public Member Functions inherited from ICPPKernel
virtual ~ICPPKernel ()=default
Default destructor.
virtual void run_nd (const Window &window, const ThreadInfo &info, const Window &thread_locator)
legacy compatibility layer for implemantions which do not support thread_locator In these cases we simply narrow the interface down the legacy version
virtual void run_op (ITensorPack &tensors, const Window &window, const ThreadInfo &info)
Execute the kernel on the passed window.
virtual size_t get_mws (const CPUInfo &platform, size_t thread_count) const
Return minimum workload size of the relevant kernel.
Public Member Functions inherited from IKernel
IKernel ()
Constructor.
virtual ~IKernel ()=default
Destructor.
virtual bool is_parallelisable () const
Indicates whether or not the kernel is parallelisable.
virtual BorderSize border_size () const
The size of the border for that kernel.
const Window & window () const
The maximum window the kernel can be executed on.
bool is_window_configured () const
Function to check if the embedded window of this kernel has been configured.
Static Public Member Functions
static Status validate (const ITensorInfo *input, const ITensorInfo *output, const ITensorInfo *axis, bool use_inverted_axis)
Static function to check if given info will lead to a valid configuration of NEReverseKernel.
Additional Inherited Members
Static Public Attributes inherited from ICPPKernel
static constexpr size_t default_mws = 1
Detailed Description
Interface for the reverse layer kernel.
Definition at line 34 of file NEReverseKernel.h.
Constructor & Destructor Documentation
NEReverseKernel() [1/3]
NEReverseKernel ()
Default constructor.
Definition at line 63 of file NEReverseKernel.cpp.
                                  : _input(nullptr), _output(nullptr), _axis(nullptr), _use_inverted_axis(false)
 {
 }
NEReverseKernel() [2/3]
NEReverseKernel (const NEReverseKernel &) delete
Prevent instances of this class from being copied (As this class contains pointers)
NEReverseKernel() [3/3]
NEReverseKernel (NEReverseKernel &&) default
Allow instances of this class to be moved.
~NEReverseKernel()
~NEReverseKernel () default
Default destructor.
Member Function Documentation
configure()
void configure (const ITensor * input, ITensor * output, const ITensor * axis, bool use_inverted_axis)
Initialise the kernel's inputs and output.
Parameters
[in] input Input tensor. Data types supported: All
[out] output Output tensor. Data type supported: Same as input
[in] axis Axis tensor. Contains the indices of the dimensions to reverse. Data type supported: U32/S32
[in] use_inverted_axis Reverse ACL axis indices convention i.e. acl.dim(0) = tensor_rank -1
Definition at line 67 of file NEReverseKernel.cpp.
 {
     ARM_COMPUTE_ERROR_ON_NULLPTR(input, output, axis);
     _input             = input;
     _output            = output;
     _axis              = axis;
     _use_inverted_axis = use_inverted_axis;
     // Output tensor auto initialization if not yet initialized
     auto_init_if_empty(*output->info(), *input->info()->clone());
     ARM_COMPUTE_ERROR_THROW_ON(validate_arguments(input->info(), output->info(), axis->info(), use_inverted_axis));
     // Configure kernel window
     INEKernel::configure(calculate_max_window(*output->info()));
 }
References ARM_COMPUTE_ERROR_ON_NULLPTR, ARM_COMPUTE_ERROR_THROW_ON, arm_compute::auto_init_if_empty(), arm_compute::calculate_max_window(), ITensor::info(), arm_compute::test::validation::input, and arm_compute::cpu::kernels::validate_arguments().
name()
const char* name () const inline override virtual
Name of the kernel.
Returns
Kernel name
Implements ICPPKernel.
Definition at line 37 of file NEReverseKernel.h.
     {
         return "NEReverseKernel";
     }
operator=() [1/2]
NEReverseKernel& operator= (const NEReverseKernel &) delete
Prevent instances of this class from being copied (As this class contains pointers)
operator=() [2/2]
NEReverseKernel& operator= (NEReverseKernel &&) default
Allow instances of this class to be moved.
run()
void run (const Window & window, const ThreadInfo & info) override virtual
Execute the kernel on the passed window.
Warning
If is_parallelisable() returns false then the passed window must be equal to window()
Note
The window has to be a region within the window returned by the window() method
The width of the window has to be a multiple of num_elems_processed_per_iteration().
Parameters
[in] window Region on which to execute the kernel. (Must be a region of the window returned by window())
[in] info Info about executing thread and CPU.
Reimplemented from ICPPKernel.
Definition at line 179 of file NEReverseKernel.cpp.
 {
     ARM_COMPUTE_UNUSED(info);
     ARM_COMPUTE_ERROR_ON_UNCONFIGURED_KERNEL(this);
     ARM_COMPUTE_ERROR_ON_INVALID_SUBWINDOW(INEKernel::window(), window);
     switch (_input->info()->element_size())
     {
         case 4:
             run_reverse<uint32_t>(window, _input, _axis, _output, _use_inverted_axis);
             break;
         case 2:
             run_reverse<uint16_t>(window, _input, _axis, _output, _use_inverted_axis);
             break;
         case 1:
             run_reverse<uint8_t>(window, _input, _axis, _output, _use_inverted_axis);
             break;
         default:
             ARM_COMPUTE_ERROR("Element size not supported");
     }
 }
References ARM_COMPUTE_ERROR, ARM_COMPUTE_ERROR_ON_INVALID_SUBWINDOW, ARM_COMPUTE_ERROR_ON_UNCONFIGURED_KERNEL, ARM_COMPUTE_UNUSED, ITensorInfo::element_size(), ITensor::info(), arm_compute::test::validation::info, and IKernel::window().
validate()
Status validate (const ITensorInfo * input, const ITensorInfo * output, const ITensorInfo * axis, bool use_inverted_axis) static
Static function to check if given info will lead to a valid configuration of NEReverseKernel.
Parameters
[in] input Input tensor info. Data types supported: All
[in] output Output tensor info. Data type supported: Same as input
[in] axis Axis tensor info. Contains the indices of the dimensions to reverse. Data type supported: U32/S32
[in] use_inverted_axis Reverse ACL axis indices convention i.e. acl.dim(0) = tensor_rank -1
Returns
a status
Definition at line 85 of file NEReverseKernel.cpp.
 {
     ARM_COMPUTE_RETURN_ON_ERROR(validate_arguments(input, output, axis, use_inverted_axis));
     return Status{};
 }
References ARM_COMPUTE_RETURN_ON_ERROR, arm_compute::test::validation::input, and arm_compute::cpu::kernels::validate_arguments().
Referenced by NEReverse::validate().
The documentation for this class was generated from the following files:
src/core/NEON/kernels/NEReverseKernel.h
src/core/NEON/kernels/NEReverseKernel.cpp