Compute Library: CLCompatCommandBuffer Class Reference
CLCompatCommandBuffer Class Reference final
Command buffer implementation for platform without mutable dispatch command buffer extension.
#include <CLCompatCommandBuffer.h>
Public Member Functions
CLCompatCommandBuffer (cl_command_queue queue)
Create a new command buffer targeting the specified command queue.
virtual ~CLCompatCommandBuffer ()
Destructor.
CLCompatCommandBuffer (const CLCompatCommandBuffer &)=delete
Disallow copy constructor.
CLCompatCommandBuffer & operator= (const CLCompatCommandBuffer &)=delete
Disallow copy assignment.
CLCompatCommandBuffer (CLCompatCommandBuffer &&)=delete
Disallow move constructor.
CLCompatCommandBuffer & operator= (CLCompatCommandBuffer &&)=delete
Disallow move assignment.
void add_kernel (cl_kernel kernel, const cl::NDRange &offset, const cl::NDRange &global, const cl::NDRange &local) override
Add a kernel enqueue command to the command queue.
void finalize () override
Finalize the command buffer.
void update () override
Update the command buffer with new kernel argument values.
void enqueue () override
Enqueue the command buffer.
bool is_finalized () const override
Check if the command buffer has been finalized.
Public Member Functions inherited from CLCommandBuffer
CLCommandBuffer ()
Constructor.
virtual ~CLCommandBuffer ()
Destructor.
CLCommandBuffer (const CLCommandBuffer &)=delete
Disallow copy constructor.
CLCommandBuffer & operator= (const CLCommandBuffer &)=delete
Disallow copy assignment.
CLCommandBuffer (CLCommandBuffer &&other)=delete
Disallow move constructor.
CLCommandBuffer & operator= (CLCommandBuffer &&other)=delete
Disallow move assignment.
template<typename T , typename = std::enable_if_t<std::is_arithmetic<T>::value || std::is_pointer<T>::value>>
void add_mutable_argument (cl_uint arg_idx, const T *value)
Add the mutable argument to the current kernel enqueue command.
Additional Inherited Members
Static Public Member Functions inherited from CLCommandBuffer
static std::unique_ptr< CLCommandBuffer > create (cl_command_queue queue)
Create a new command buffer targeting the specified command queue.
Detailed Description
Command buffer implementation for platform without mutable dispatch command buffer extension.
Definition at line 36 of file CLCompatCommandBuffer.h.
Constructor & Destructor Documentation
CLCompatCommandBuffer() [1/3]
CLCompatCommandBuffer (cl_command_queue queue)
Create a new command buffer targeting the specified command queue.
Parameters
[in] queue The command queue to execute the command buffer.
Definition at line 34 of file CLCompatCommandBuffer.cpp.
                                                                    : _queue(queue)
 {
 }
~CLCompatCommandBuffer()
~CLCompatCommandBuffer () virtual
Destructor.
Definition at line 38 of file CLCompatCommandBuffer.cpp.
 {
 }
CLCompatCommandBuffer() [2/3]
CLCompatCommandBuffer (const CLCompatCommandBuffer &) delete
Disallow copy constructor.
CLCompatCommandBuffer() [3/3]
CLCompatCommandBuffer (CLCompatCommandBuffer &&) delete
Disallow move constructor.
Member Function Documentation
add_kernel()
void add_kernel (cl_kernel kernel, const cl::NDRange & offset, const cl::NDRange & global, const cl::NDRange & local) override virtual
Add a kernel enqueue command to the command queue.
This function must be called before the command buffer has been finalized.
Parameters
[in] kernel The CL kernel.
[in] offset The global work offset.
[in] global The global work size.
[in] local The local work size.
Implements CLCommandBuffer.
Definition at line 42 of file CLCompatCommandBuffer.cpp.
 {
     ARM_COMPUTE_ERROR_ON(state() != State::Created);
     _kernel_cmds.push_back(KernelCommand{kernel, offset, global, local, {}});
 }
References ARM_COMPUTE_ERROR_ON, and offset().
enqueue()
void enqueue () override virtual
Enqueue the command buffer.
This function must be called after the command buffer has been finalized.
Implements CLCommandBuffer.
Definition at line 81 of file CLCompatCommandBuffer.cpp.
 {
     ARM_COMPUTE_ERROR_ON(state() != State::Finalized);
     for (const auto &cmd : _kernel_cmds)
     {
         for (const auto &arg : cmd.mutable_args)
         {
             const auto error = clSetKernelArg(cmd.kernel, arg.arg_index, arg.arg_size, arg.arg_value);
             handle_cl_error("clSetKernelArg", error);
         }
         const auto error =
             clEnqueueNDRangeKernel(_queue, cmd.kernel, static_cast<cl_uint>(cmd.global.dimensions()),
                                    cmd.offset.dimensions() != 0 ? cmd.offset.get() : nullptr, cmd.global.get(),
                                    cmd.local.dimensions() != 0 ? cmd.local.get() : nullptr, 0, nullptr, nullptr);
         handle_cl_error("clEnqueueNDRangeKernel", error);
     }
 }
References ARM_COMPUTE_ERROR_ON, clEnqueueNDRangeKernel(), clSetKernelArg(), and arm_compute::handle_cl_error().
finalize()
void finalize () override virtual
Finalize the command buffer.
Implements CLCommandBuffer.
Definition at line 60 of file CLCompatCommandBuffer.cpp.
 {
     ARM_COMPUTE_ERROR_ON(state() != State::Created);
     _kernel_cmds.shrink_to_fit();
     for (auto &cmd : _kernel_cmds)
     {
         cmd.mutable_args.shrink_to_fit();
     }
     state(State::Finalized);
 }
References ARM_COMPUTE_ERROR_ON.
is_finalized()
bool is_finalized () const override virtual
Check if the command buffer has been finalized.
Returns
true if the command buffer has been finalized.
Implements CLCommandBuffer.
Definition at line 103 of file CLCompatCommandBuffer.cpp.
 {
     return state() == State::Finalized;
 }
operator=() [1/2]
CLCompatCommandBuffer& operator= (CLCompatCommandBuffer &&) delete
Disallow move assignment.
operator=() [2/2]
CLCompatCommandBuffer& operator= (const CLCompatCommandBuffer &) delete
Disallow copy assignment.
update()
void update () override virtual
Update the command buffer with new kernel argument values.
This function must be called after the command buffer has been finalized.
All the value pointed by the mutable argument will be applied to the command buffer.
Implements CLCommandBuffer.
Definition at line 74 of file CLCompatCommandBuffer.cpp.
 {
     ARM_COMPUTE_ERROR_ON(state() != State::Finalized);
     // Nothing to do here - The kernel arguments will be updated when each command is enqueued.
 }
References ARM_COMPUTE_ERROR_ON.
The documentation for this class was generated from the following files:
src/core/CL/CLCompatCommandBuffer.h
src/core/CL/CLCompatCommandBuffer.cpp