Compute Library: CLDeviceBackend Class Reference
CLDeviceBackend Class Reference final
OpenCL device backend.
#include <CLDeviceBackend.h>
Public Member Functions
CLDeviceBackend ()
Default Constructor.
~CLDeviceBackend ()
Destructor.
void set_kernel_tuning (bool enable_tuning)
Switchs on or off the kernel tuning.
void set_kernel_tuning_mode (CLTunerMode tuning_mode)
Set kernel tuning mode.
void initialize_backend () override
Initializes the backend.
void setup_backend_context (GraphContext &ctx) override
Setups the given graph context.
void release_backend_context (GraphContext &ctx) override
Release the backend specific resources associated to a given graph context.
bool is_backend_supported () override
Checks if an instantiated backend is actually supported.
IAllocator * backend_allocator () override
Gets a backend memory allocator.
std::unique_ptr< ITensorHandle > create_tensor (const Tensor &tensor) override
Create a backend Tensor.
std::unique_ptr< ITensorHandle > create_subtensor (ITensorHandle *parent, TensorShape shape, Coordinates coords, bool extend_parent) override
Create a backend Sub-Tensor.
std::unique_ptr< arm_compute::IFunction > configure_node (INode &node, GraphContext &ctx) override
Configure a backend Node.
Status validate_node (INode &node) override
Validate a node.
std::shared_ptr< arm_compute::IMemoryManager > create_memory_manager (MemoryManagerAffinity affinity) override
Create a backend memory manager given its affinity.
std::shared_ptr< arm_compute::IWeightsManager > create_weights_manager () override
Create a backend weights manager.
void sync () override
Synchronize kernels execution on the backend.
Public Member Functions inherited from IDeviceBackend
virtual ~IDeviceBackend ()=default
Virtual Destructor.
Detailed Description
OpenCL device backend.
Definition at line 40 of file CLDeviceBackend.h.
Constructor & Destructor Documentation
CLDeviceBackend()
CLDeviceBackend ()
Default Constructor.
Definition at line 65 of file CLDeviceBackend.cpp.
     : _context_count(0),
       _tuner(),
       _gemm_heuristics(),
       _allocator(nullptr),
       _tuner_file(),
       _backend_type(CLBackendType::Native)
 {
 }
References arm_compute::Native.
~CLDeviceBackend()
~CLDeviceBackend ()
Destructor.
Definition at line 75 of file CLDeviceBackend.cpp.
 {
     _tuner.save_to_file(_tuner_file);
 }
References CLTuner::save_to_file().
Member Function Documentation
backend_allocator()
IAllocator * backend_allocator () override virtual
Gets a backend memory allocator.
Returns
Backend memory allocator
Implements IDeviceBackend.
Definition at line 163 of file CLDeviceBackend.cpp.
 {
     return _allocator.get();
 }
configure_node()
std::unique_ptr< arm_compute::IFunction > configure_node (INode & node, GraphContext & ctx) override virtual
Configure a backend Node.
Note
This creates an appropriate configured backend function for the given node
Parameters
[in] node The node we want to configure
[in] ctx Context to use
Returns
Backend execution function
Implements IDeviceBackend.
Definition at line 192 of file CLDeviceBackend.cpp.
 {
     ARM_COMPUTE_LOG_GRAPH_VERBOSE("Configuring CL node with ID : " << node.id() << std::endl);
     ARM_COMPUTE_ERROR_ON(node.assigned_target() != Target::CL);
     // Configure node
     return CLFunctionFactory::create(&node, ctx);
 }
References ARM_COMPUTE_ERROR_ON, ARM_COMPUTE_LOG_GRAPH_VERBOSE, INode::assigned_target(), arm_compute::graph::CL, CLFunctionFactory::create(), and INode::id().
create_memory_manager()
std::shared_ptr< arm_compute::IMemoryManager > create_memory_manager (MemoryManagerAffinity affinity) override virtual
Create a backend memory manager given its affinity.
Parameters
[in] affinity Memory Manager affinity
Returns
Memory manager
Implements IDeviceBackend.
Definition at line 209 of file CLDeviceBackend.cpp.
 {
     if (affinity == MemoryManagerAffinity::Offset)
     {
         ARM_COMPUTE_LOG_GRAPH_WARNING("CL Backend does not support offset affinity memory management!");
         return nullptr;
     }
     auto lifetime_mgr = std::make_shared<BlobLifetimeManager>();
     auto pool_mgr     = std::make_shared<PoolManager>();
     auto mm           = std::make_shared<MemoryManagerOnDemand>(lifetime_mgr, pool_mgr);
     return mm;
 }
References ARM_COMPUTE_LOG_GRAPH_WARNING, and arm_compute::graph::Offset.
Referenced by CLDeviceBackend::setup_backend_context().
create_subtensor()
std::unique_ptr< ITensorHandle > create_subtensor (ITensorHandle * parent, TensorShape shape, Coordinates coords, bool extend_parent) override virtual
Create a backend Sub-Tensor.
Parameters
[in] parent Parent sub-tensor handle
[in] shape Shape of the sub-tensor
[in] coords Starting coordinates of the sub-tensor
[in] extend_parent Extends parent shape if true
Returns
Backend sub-tensor handle
Implements IDeviceBackend.
Definition at line 182 of file CLDeviceBackend.cpp.
 {
     if (parent == nullptr)
     {
         return nullptr;
     }
     return std::make_unique<CLSubTensorHandle>(parent, shape, coords, extend_parent);
 }
References arm_compute::test::validation::shape.
create_tensor()
std::unique_ptr< ITensorHandle > create_tensor (const Tensor & tensor) override virtual
Create a backend Tensor.
Parameters
[in] tensor The tensor we want to create a backend tensor for
Returns
Backend tensor handle
Implements IDeviceBackend.
Definition at line 168 of file CLDeviceBackend.cpp.
 {
     // Get tensor descriptor
     const TensorDescriptor &tensor_desc = tensor.desc();
     ARM_COMPUTE_ERROR_ON(tensor_desc.target != Target::CL);
     // Create backend tensor handle
     TensorInfo info(tensor_desc.shape, 1, tensor_desc.data_type, tensor_desc.quant_info);
     info.set_data_layout(tensor_desc.layout);
     return std::make_unique<CLTensorHandle>(info);
 }
References ARM_COMPUTE_ERROR_ON, arm_compute::graph::CL, TensorDescriptor::data_type, arm_compute::test::validation::info, TensorDescriptor::layout, TensorDescriptor::quant_info, TensorDescriptor::shape, TensorDescriptor::target, and tensor.
create_weights_manager()
std::shared_ptr< arm_compute::IWeightsManager > create_weights_manager () override virtual
Create a backend weights manager.
Returns
Weights manager
Implements IDeviceBackend.
Definition at line 224 of file CLDeviceBackend.cpp.
 {
     auto weights_mgr = std::make_shared<IWeightsManager>();
     return weights_mgr;
 }
Referenced by CLDeviceBackend::setup_backend_context().
initialize_backend()
void initialize_backend () override virtual
Initializes the backend.
Implements IDeviceBackend.
Definition at line 90 of file CLDeviceBackend.cpp.
 {
     // Setup Scheduler
     CLScheduler::get().default_init(&_tuner, &_gemm_heuristics, _backend_type);
     // Create allocator with new context
     _allocator = std::make_unique<CLBufferAllocator>();
 }
References CLScheduler::default_init(), and CLScheduler::get().
Referenced by CLDeviceBackend::setup_backend_context().
is_backend_supported()
bool is_backend_supported () override virtual
Checks if an instantiated backend is actually supported.
Returns
True if the backend is supported else false
Implements IDeviceBackend.
Definition at line 158 of file CLDeviceBackend.cpp.
 {
     return arm_compute::opencl_is_available();
 }
References arm_compute::opencl_is_available().
release_backend_context()
void release_backend_context (GraphContext & ctx) override virtual
Release the backend specific resources associated to a given graph context.
Parameters
[in,out] ctx Graph context
Implements IDeviceBackend.
Definition at line 98 of file CLDeviceBackend.cpp.
 {
     ARM_COMPUTE_UNUSED(ctx);
     _context_count--;
     if (_context_count == 0) // No more context using the backend: free resources
     {
         _allocator = nullptr;
     }
 }
References ARM_COMPUTE_UNUSED.
set_kernel_tuning()
void set_kernel_tuning (bool enable_tuning)
Switchs on or off the kernel tuning.
Note
When true the tuner set is used, if no tuner is set a new default one is created
Parameters
[in] enable_tuning Enables tuning if false else true
Definition at line 80 of file CLDeviceBackend.cpp.
 {
     _tuner.set_tune_new_kernels(enable_tuning);
 }
References CLTuner::set_tune_new_kernels().
Referenced by CLDeviceBackend::setup_backend_context().
set_kernel_tuning_mode()
void set_kernel_tuning_mode (CLTunerMode tuning_mode)
Set kernel tuning mode.
Parameters
[in] tuning_mode Indicates how exhaustive the search for the optimal LWS should be while tuning
Definition at line 85 of file CLDeviceBackend.cpp.
 {
     _tuner.set_tuner_mode(tuning_mode);
 }
References CLTuner::set_tuner_mode().
Referenced by CLDeviceBackend::setup_backend_context().
setup_backend_context()
void setup_backend_context (GraphContext & ctx) override virtual
Setups the given graph context.
Parameters
[in,out] ctx Graph context
Implements IDeviceBackend.
Definition at line 108 of file CLDeviceBackend.cpp.
 {
     // Force backend initialization
     _context_count++;
     if (_context_count == 1)
     {
         _backend_type = ctx.config().backend_type;
         initialize_backend();
     }
     // Setup tuner
     _tuner_file = ctx.config().tuner_file;
     // Load tuner data if available
     if (file_exists(_tuner_file))
     {
         _tuner.load_from_file(_tuner_file);
     }
     set_kernel_tuning(ctx.config().use_tuner);
     set_kernel_tuning_mode(ctx.config().tuner_mode);
     // Attempt to load mlgo heuristics
     ARM_COMPUTE_ERROR_ON(CLScheduler::get().gemm_heuristics() == nullptr);
     CLScheduler::get().gemm_heuristics()->reload_from_file(ctx.config().mlgo_file);
     // Setup a management backend
     if (ctx.memory_management_ctx(Target::CL) == nullptr)
     {
         MemoryManagerContext mm_ctx;
         mm_ctx.target      = Target::CL;
         mm_ctx.intra_mm    = create_memory_manager(MemoryManagerAffinity::Buffer);
         mm_ctx.cross_mm    = create_memory_manager(MemoryManagerAffinity::Buffer);
         mm_ctx.cross_group = std::make_shared<MemoryGroup>(mm_ctx.cross_mm);
         mm_ctx.allocator   = _allocator.get();
         ctx.insert_memory_management_ctx(std::move(mm_ctx));
     }
     // Create function level weights manager
     if (ctx.weights_management_ctx(Target::CL) == nullptr)
     {
         WeightsManagerContext wm_ctx;
         wm_ctx.target = Target::CL;
         wm_ctx.wm     = create_weights_manager();
         ctx.insert_weights_management_ctx(std::move(wm_ctx));
     }
 }
References MemoryManagerContext::allocator, ARM_COMPUTE_ERROR_ON, GraphConfig::backend_type, arm_compute::graph::Buffer, arm_compute::graph::CL, GraphContext::config(), CLDeviceBackend::create_memory_manager(), CLDeviceBackend::create_weights_manager(), MemoryManagerContext::cross_group, MemoryManagerContext::cross_mm, CLScheduler::gemm_heuristics(), CLScheduler::get(), CLDeviceBackend::initialize_backend(), GraphContext::insert_memory_management_ctx(), GraphContext::insert_weights_management_ctx(), MemoryManagerContext::intra_mm, CLTuner::load_from_file(), GraphContext::memory_management_ctx(), GraphConfig::mlgo_file, CLGEMMHeuristicsHandle::reload_from_file(), CLDeviceBackend::set_kernel_tuning(), CLDeviceBackend::set_kernel_tuning_mode(), MemoryManagerContext::target, WeightsManagerContext::target, GraphConfig::tuner_file, GraphConfig::tuner_mode, GraphConfig::use_tuner, GraphContext::weights_management_ctx(), and WeightsManagerContext::wm.
sync()
void sync () override virtual
Synchronize kernels execution on the backend.
On GPU, this results in a blocking call waiting for all kernels to be completed.
Implements IDeviceBackend.
Definition at line 230 of file CLDeviceBackend.cpp.
 {
     CLScheduler::get().sync();
 }
References CLScheduler::get(), and CLScheduler::sync().
validate_node()
arm_compute::Status validate_node (INode & node) override virtual
Validate a node.
Parameters
[in] node The node we want to validate
Returns
An error status
Implements IDeviceBackend.
Definition at line 201 of file CLDeviceBackend.cpp.
 {
     ARM_COMPUTE_LOG_GRAPH_VERBOSE("Validating CL node with ID : " << node.id() << std::endl);
     ARM_COMPUTE_ERROR_ON(node.assigned_target() != Target::CL);
     return CLNodeValidator::validate(&node);
 }
References ARM_COMPUTE_ERROR_ON, ARM_COMPUTE_LOG_GRAPH_VERBOSE, INode::assigned_target(), arm_compute::graph::CL, INode::id(), and CLNodeValidator::validate().
The documentation for this class was generated from the following files:
arm_compute/graph/backends/CL/CLDeviceBackend.h
src/graph/backends/CL/CLDeviceBackend.cpp