Compute Library: arm_compute::opencl::kernels Namespace Reference
arm_compute::opencl::kernels Namespace Reference
Namespaces
gemm
Data Structures
class ClActivationKernel
Interface for the activation kernel.
class ClArithmeticKernel
class ClBatchConcatenateKernel
Interface for the batch concatenate kernel.
class ClCastKernel
Casts a given tensor to a new type.
class ClCol2ImKernel
Interface for the col2im reshaping kernel.
class ClComplexMulKernel
Interface for the complex pixelwise multiplication kernel.
class ClConvertFullyConnectedWeightsKernel
class ClCopyKernel
OpenCL kernel to perform a copy between two tensors.
class ClCropKernel
OpenCL kernel to perform a copy between two tensors.
class ClDepthConcatenateKernel
Interface for the depth concatenate kernel.
class ClDequantizeKernel
Interface for the dequantization layer kernel.
class ClDirectConv2dKernel
Interface for the direct convolution kernel.
class ClDirectConv3dKernel
Interface for the direct convolution 3d kernel.
class ClElementwiseKernel
Interface for an element-wise operation kernel.
class ClElementWiseUnaryKernel
Interface for the elementwise unary operator.
class ClFillKernel
Interface for filling the planes of a tensor.
class ClFloorKernel
OpenCL kernel to perform a floor operation.
class ClGemmLowpMatrixAReductionKernel
OpenCL kernel used to compute the row-vectors of sums of all the entries in each row of Matrix A.
class ClGemmLowpMatrixBReductionKernel
OpenCL kernel used to compute the row-vectors of sums of all the entries in each column of Matrix B.
class ClGemmLowpMatrixMultiplyNativeKernel
OpenCL kernel to multiply matrices with QASYMM8/QASYMM8_SIGNED data type.
class ClGemmLowpMatrixMultiplyReshapedKernel
OpenCL kernel to multiply matrices when both the input matrices LHS (src0) and RHS (src1) have been reshaped.
class ClGemmLowpMatrixMultiplyReshapedOnlyRhsKernel
OpenCL kernel to multiply matrices with QASYMM8 data type when only the input matrix RHS (src1) has been reshaped.
class ClGemmLowpMatrixMultiplyReshapedOnlyRhsMMULKernel
OpenCL kernel to multiply matrices with QASYMM8/QASYMM8_SIGNED data types when only the input matrix RHS (src1) has been reshaped using the MMUL instruction.
class ClGemmLowpOffsetContributionKernel
OpenCL kernel used to add the offset contribution after the matrix multiplication.
class ClGemmLowpOffsetContributionOutputStageKernel
OpenCL kernel used to add the offset contribution after the matrix multiplication and perform the output stage.
class ClGemmLowpQuantizeDownInt32ScaleByFixedPointKernel
OpenCL kernel used to quantize down the int32 accumulator values of GEMMLowp to QASYMM8/QASYMM8_SIGNED/QSYMM16.
class ClGemmLowpQuantizeDownInt32ScaleByFloatKernel
OpenCL kernel used to quantize down the int32 accumulator values of GEMMLowp to QASYMM8/QASYMM8_SIGNED.
class ClGemmLowpQuantizeDownInt32ScaleKernel
OpenCL kernel used to quantize down the int32 accumulator values of GEMMLowp to QASYMM8/QASYMM8_SIGNED.
class ClGemmMatrixMultiplyNativeKernel
OpenCL kernel to multiply matrices when neither of the input matrices have been reshaped.
class ClGemmMatrixMultiplyReshapedKernel
OpenCL kernel to multiply matrices when both the input matrices LHS (src0) and RHS (src1) have been reshaped.
class ClGemmMatrixMultiplyReshapedOnlyRhsKernel
OpenCL kernel to multiply matrices when only the input matrix RHS (src1) has been reshaped.
class ClGemmMatrixMultiplyReshapedOnlyRhsMMULKernel
OpenCL kernel to multiply matrices using MMUL when only the input matrix RHS (src1) has been reshaped.
class ClGemmReshapeLhsMatrixKernel
OpenCL kernel to reshape the LHS matrix when performing the matrix multiplication.
class ClGemmReshapeRhsMatrixKernel
OpenCL kernel to reshape the RHS matrix when performing the matrix multiplication In particular, this kernel splits the src matrix in blocks of size K0xN0 and stores each one in the dst matrix unrolling the values.
class ClHeightConcatenateKernel
Interface for the height concatenate kernel.
class ClIm2ColKernel
Interface for the im2col reshape kernel.
class ClIndirectConv2dAddressPrecalculationKernel
Interface for the direct convolution kernel.
class ClIndirectConv2dKernel
Interface for the indirect convolution kernel.
class ClLogicalBinaryKernel
class ClMatMulLowpNativeKernel
class ClMatMulLowpNativeMMULKernel
class ClMatMulNativeKernel
class ClMatMulNativeMMULKernel
class ClMulKernel
Interface for the pixelwise multiplication kernel.
class ClPermuteKernel
OpenCL kernel to perform tensor permutation.
class ClPool2dKernel
Interface for the pooling layer kernel.
class ClPool3dKernel
Interface for the pooling layer kernel.
class ClQuantizeKernel
Interface for the quantization layer kernel.
class ClReshapeKernel
Interface for the kernel to perform tensor reshaping.
class ClSaturatedArithmeticKernel
Addition operation.
class ClScaleKernel
Interface for the scale kernel.
class ClSoftmaxKernel
The CL kernel that performs softmax function.
class ClTransposedConvolutionKernel
OpenCL kernel for transposed convolution.
class ClTransposeKernel
OpenCL kernel to transpose a tensor.
class ClWeightsReshapeKernel
OpenCL kernel to perform reshaping on the weights used by convolution and locally connected layer.
class ClWidthConcatenate2TensorsKernel
Interface for the width concatenate kernel of 2 tensors.
class ClWidthConcatenate4TensorsKernel
Interface for the width concatenate kernel of 4 tensors.
class ClWidthConcatenateKernel
Interface for the width concatenate kernel.
class ClWinogradFilterTransformKernel
Interface for the Winograd filter transform kernel.
class ClWinogradInputTransformKernel
OpenCL kernel to perform Winograd input transform.
class ClWinogradOutputTransformKernel
Interface for the Winograd output transform kernel.
class IClGemmLowpReductionKernel
Common interface for all OpenCL reduction kernels.
Functions
Status validate_matmul_input_shapes (const TensorShape &lhs_shape, const TensorShape &rhs_shape, const MatMulKernelInfo &matmul_kernel_info)
Validate the input shapes of Matmul operation.
std::pair< Status, Window > validate_and_configure_window_for_mmul_kernels (const ITensorInfo *lhs, const ITensorInfo *rhs, const ITensorInfo *dst, const MatMulKernelInfo &matmul_kernel_info, int mmul_m0, int mmul_n0)
Validate and configure window for Matmul MMUL kernels.
Function Documentation
validate_and_configure_window_for_mmul_kernels()
std::pair< Status, Window > validate_and_configure_window_for_mmul_kernels (const ITensorInfo * lhs, const ITensorInfo * rhs, const ITensorInfo * dst, const MatMulKernelInfo & matmul_kernel_info, int mmul_m0, int mmul_n0)
Validate and configure window for Matmul MMUL kernels.
Parameters
[in] lhs Lhs tensor info
[in] rhs Rhs tensor info
[in] dst Dst tensor info
[in] matmul_kernel_info Matmul kernel info
[in] mmul_m0 Number of rows in the MMUL block
[in] mmul_n0 Number of columns in the MMUL block
Returns
a pair of Status and Window object
Definition at line 59 of file MatMulKernelHelpers.cpp.
 {
     ARM_COMPUTE_UNUSED(lhs, rhs);
     const Window win = calculate_max_window(*dst, Steps(1, 1));
     // Collapse along the Z direction
     // This collapse needs to be here in order to tune the Z dimension of LWS
     Window collapsed = win.collapse(win, Window::DimZ);
     // Reconfigure window size, one arm_matrix_multiply call needs 16 threads to finish.
     Window::Dimension x_dimension = collapsed.x();
     Window::Dimension y_dimension = collapsed.y();
     const int m = dst->dimension(1);
     const int n = dst->dimension(0);
     const int m0 = std::min(matmul_kernel_info.m0, m);
     const int n0 = adjust_vec_size(matmul_kernel_info.n0, n);
     // Make M and N multiple of M0 and N0 respectively
     const unsigned int ceil_to_multiple_n_n0 = ceil_to_multiple(n, n0);
     const unsigned int ceil_to_multiple_m_m0 = ceil_to_multiple(m, m0);
     // Divide M and N by M0 and N0 respectively
     const unsigned int n_div_n0 = ceil_to_multiple_n_n0 / n0;
     const unsigned int m_div_m0 = ceil_to_multiple_m_m0 / m0;
     // Make n_div_n0 and m_div_m0 multiple of mmul_n0 and mmul_m0 respectively
     const unsigned int ceil_to_multiple_n_div_n0_mmul_n0 = ceil_to_multiple(n_div_n0, mmul_n0);
     const unsigned int ceil_to_multiple_m_div_m0_mmul_m0 = ceil_to_multiple(m_div_m0, mmul_m0);
     // Ensure x_dimension is multiple of MMUL block size (mmul_m0 * mmul_n0)
     x_dimension.set_end(ceil_to_multiple_n_div_n0_mmul_n0 * mmul_m0);
     y_dimension.set_end(ceil_to_multiple_m_div_m0_mmul_m0 / mmul_m0);
     collapsed.set(Window::DimX, x_dimension);
     collapsed.set(Window::DimY, y_dimension);
     return std::make_pair(Status{}, collapsed);
 }
References arm_compute::adjust_vec_size(), ARM_COMPUTE_UNUSED, arm_compute::calculate_max_window(), arm_compute::ceil_to_multiple(), Window::collapse(), Window::DimX, Window::DimY, Window::DimZ, arm_compute::test::validation::dst, MatMulKernelInfo::m0, MatMulKernelInfo::n0, Window::set(), Window::Dimension::set_end(), Window::x(), and Window::y().
Referenced by ClMatMulLowpNativeMMULKernel::configure(), and ClMatMulNativeMMULKernel::configure().
validate_matmul_input_shapes()
Status validate_matmul_input_shapes (const TensorShape & lhs_shape, const TensorShape & rhs_shape, const MatMulKernelInfo & matmul_kernel_info)
Validate the input shapes of Matmul operation.
Parameters
[in] lhs_shape Lhs tensor shape
[in] rhs_shape Rhs tensor shape
[in] matmul_kernel_info Matmul kernel info
Returns
true if the shapes and matmul kernel info matches
Definition at line 39 of file MatMulKernelHelpers.cpp.
 {
     const size_t lhs_k = matmul_kernel_info.adj_lhs ? lhs_shape.y() : lhs_shape.x();
     const size_t rhs_k = matmul_kernel_info.adj_rhs ? rhs_shape.x() : rhs_shape.y();
     ARM_COMPUTE_RETURN_ERROR_ON_MSG(lhs_k != rhs_k, "K dimension in Lhs and Rhs matrices must match.");
     ARM_COMPUTE_RETURN_ERROR_ON_MSG(lhs_shape.total_size() == 0, "Lhs tensor can't be empty");
     ARM_COMPUTE_RETURN_ERROR_ON_MSG(rhs_shape.total_size() == 0, "Rhs tensor can't be empty");
     constexpr size_t batch_dim_start = 2;
     for (size_t i = batch_dim_start; i < Coordinates::num_max_dimensions; ++i)
     {
         ARM_COMPUTE_RETURN_ERROR_ON_MSG(lhs_shape[i] != rhs_shape[i], "Batch dimension broadcasting is not supported");
     }
     return Status{};
 }
References MatMulKernelInfo::adj_lhs, MatMulKernelInfo::adj_rhs, ARM_COMPUTE_RETURN_ERROR_ON_MSG, Dimensions< int >::num_max_dimensions, TensorShape::total_size(), Dimensions< T >::x(), and Dimensions< T >::y().
Referenced by ClMatMulLowpNativeMMULKernel::validate(), ClMatMulNativeKernel::validate(), ClMatMulLowpNativeKernel::validate(), and ClMatMulNativeMMULKernel::validate().