Compute Library: check_header_guards Namespace Reference
check_header_guards Namespace Reference
Functions
(int, int) find_code_boundaries (List[str] lines)
bool is_define (str line)
bool is_endif (str line)
bool is_ifndef (str line)
str strip_comments (str line)
bool looks_like_header_guard (str line)
Tuple[List[str], bool] fix_header_guard (List[str] lines, str expected_header_guard, str comment_style)
str find_expected_header_guard (str filepath, str prefix, str add_extension, str drop_outermost_subdir)
bool skip_file (str filepath, List[str] extensions, List[str] exclude, List[str] include)
Variables
logger = logging.getLogger("check_header_guards")
parser
type
str
nargs
help
required
choices
default
action
args = parser.parse_args()
files = args.files
extensions = args.extensions.split(",")
string exclude = '' else []
string include = '' else []
prefix = args.prefix
add_extension = args.add_extension
drop_outermost_subdir = args.drop_outermost_subdir
comment_style = args.comment_style
logging_level = logging.INFO
level
int retval = 0
List
new_lines
guards_updated
Function Documentation
find_code_boundaries()
(int, int) check_header_guards.find_code_boundaries (List[str] lines)
Definition at line 33 of file check_header_guards.py.
 def find_code_boundaries(lines: List[str]) -> (int, int):
     inside_comment : bool = False
     start = len(lines)
     end = -1
     line_num = 0
     for line in lines:
         stripped_line : str = line.strip()
         if stripped_line.startswith("/*"):    # block comment start
             inside_comment = True
         if not inside_comment and not stripped_line.startswith("//") and stripped_line != "":
             start = min(line_num, start)
             end = line_num
         if inside_comment and stripped_line.endswith("*/"):
             inside_comment = False
         line_num += 1
     return start, end
Referenced by fix_header_guard().
find_expected_header_guard()
str check_header_guards.find_expected_header_guard (str filepath, str prefix, str add_extension, str drop_outermost_subdir)
Definition at line 127 of file check_header_guards.py.
 def find_expected_header_guard(filepath: str, prefix: str, add_extension: str, drop_outermost_subdir: str) -> str:
     if drop_outermost_subdir:
         arr : List[str] = filepath.split("/")
         arr = arr[min(1, len(arr)-1):]
         filepath = "/".join(arr)
     if not add_extension:
         filepath = ".".join(filepath.split(".")[:-1])
     guard = filepath.replace("/", "_").replace(".", "_").upper()    # snake case full path
     return prefix + "_" + guard
References arm_compute.join().
fix_header_guard()
Tuple[List[str], bool] check_header_guards.fix_header_guard (List[str] lines, str expected_header_guard, str comment_style)
Definition at line 84 of file check_header_guards.py.
 def fix_header_guard(lines: List[str], expected_header_guard: str, comment_style: str) -> Tuple[List[str], bool]:
     start_line, next_line, last_line = "", "", ""
     start_index, last_index = find_code_boundaries(lines)
     guards_updated: bool = True
     if start_index < len(lines):
         # if not, the file is full of comments
         start_line = lines[start_index]
     if start_index + 1 < len(lines):
         # if not, the file has only one line of code
         next_line = lines[start_index + 1]
     if last_index < len(lines) and last_index > start_index + 1:
         # if not, either the file is full of comments OR it has less than three code lines
         last_line = lines[last_index]
     expected_start_line = f"#ifndef {expected_header_guard}\n"
     expected_next_line = f"#define {expected_header_guard}\n"
     if comment_style == 'double_slash':
         expected_last_line = f"#endif // {expected_header_guard}\n"
     elif comment_style == 'slash_asterix':
         expected_last_line = f"#endif /* {expected_header_guard} */\n"
     empty_line = "\n"
     if looks_like_header_guard(start_line) and is_define(next_line) and is_endif(last_line):
         # modify the current header guard if necessary
         lines = lines[:start_index] + [expected_start_line, expected_next_line] + \
             lines[start_index+2:last_index] + [expected_last_line] + lines[last_index+1:]
         guards_updated = (start_line != expected_start_line) or (next_line != expected_next_line) \
             or (last_line != expected_last_line)
     else:
         # header guard could not be detected, add header guards
         lines = lines[:start_index] + [empty_line, expected_start_line, expected_next_line] + \
             [empty_line] + lines[start_index:] + [empty_line, expected_last_line]
     return lines, guards_updated
References find_code_boundaries(), is_define(), is_endif(), and looks_like_header_guard().
is_define()
bool check_header_guards.is_define (str line)
Definition at line 56 of file check_header_guards.py.
 def is_define(line: str) -> bool:
     return line.strip().startswith("#define")
Referenced by fix_header_guard().
is_endif()
bool check_header_guards.is_endif (str line)
Definition at line 59 of file check_header_guards.py.
 def is_endif(line: str) -> bool:
     return line.strip().startswith("#endif")
Referenced by fix_header_guard().
is_ifndef()
bool check_header_guards.is_ifndef (str line)
Definition at line 62 of file check_header_guards.py.
 def is_ifndef(line: str) -> bool:
     return line.strip().startswith("#ifndef")
 # Strips the given line from // and /* */ blocks
Referenced by looks_like_header_guard().
looks_like_header_guard()
bool check_header_guards.looks_like_header_guard (str line)
Definition at line 77 of file check_header_guards.py.
 def looks_like_header_guard(line: str) -> bool:
     sline = line.strip()
     guard_candidate = strip_comments(sline[len("#ifndef"):])
     return is_ifndef(sline) and not guard_candidate.startswith("__") and guard_candidate.isupper()
References is_ifndef(), and strip_comments().
Referenced by fix_header_guard().
skip_file()
bool check_header_guards.skip_file (str filepath, List[str] extensions, List[str] exclude, List[str] include)
Definition at line 140 of file check_header_guards.py.
 def skip_file(filepath: str, extensions: List[str], exclude: List[str], include: List[str]) -> bool:
     extension = filepath.split(".")[-1]
     if extension.lower() not in extensions:
         return True
     if exclude and any([filepath.startswith(exc) for exc in exclude]):
         print(exclude)
         return True
     if include:
         return not any([filepath.startswith(inc) for inc in include])
     return False
strip_comments()
str check_header_guards.strip_comments (str line)
Definition at line 66 of file check_header_guards.py.
 def strip_comments(line: str) -> str:
     line = re.sub(r"/\*.*\*/", "", line)
     line = re.sub(r"//.*", "", line)
     return line.strip()
 # If the line
 #   1) startswith #ifndef
 #   2) is all uppercase
 #   3) does not start with double underscore, i.e. __
 # Then
 #   It "looks" like a header guard
Referenced by looks_like_header_guard().
Variable Documentation
action
action
Definition at line 170 of file check_header_guards.py.
add_extension
add_extension = args.add_extension
Definition at line 181 of file check_header_guards.py.
args
args = parser.parse_args()
Definition at line 174 of file check_header_guards.py.
choices
choices
Definition at line 165 of file check_header_guards.py.
comment_style
comment_style = args.comment_style
Definition at line 183 of file check_header_guards.py.
default
default
Definition at line 166 of file check_header_guards.py.
drop_outermost_subdir
drop_outermost_subdir = args.drop_outermost_subdir
Definition at line 182 of file check_header_guards.py.
exclude
string exclude = '' else []
Definition at line 178 of file check_header_guards.py.
extensions
extensions = args.extensions.split(",")
Definition at line 177 of file check_header_guards.py.
Referenced by CLDevice.CLDevice(), arm_compute.device_supports_extension(), and arm_compute::test::validation.TEST_CASE().
files
files = args.files
Definition at line 176 of file check_header_guards.py.
guards_updated
guards_updated
Definition at line 199 of file check_header_guards.py.
help
help
Definition at line 162 of file check_header_guards.py.
include
string include = '' else []
Definition at line 179 of file check_header_guards.py.
level
level
Definition at line 186 of file check_header_guards.py.
List
List
Definition at line 197 of file check_header_guards.py.
logger
logger = logging.getLogger("check_header_guards")
Definition at line 31 of file check_header_guards.py.
logging_level
logging_level = logging.INFO
Definition at line 185 of file check_header_guards.py.
nargs
nargs
Definition at line 162 of file check_header_guards.py.
new_lines
new_lines
Definition at line 199 of file check_header_guards.py.
parser
parser
Initial value:
 =  argparse.ArgumentParser(
             formatter_class=argparse.RawDescriptionHelpFormatter,
             description="Header Guard Checker. It adds full path snake case header guards with or without extension.",
     )
Definition at line 157 of file check_header_guards.py.
prefix
prefix = args.prefix
Definition at line 180 of file check_header_guards.py.
Referenced by PrettyPrinter.print_error().
required
required
Definition at line 164 of file check_header_guards.py.
retval
int retval = 0
Definition at line 188 of file check_header_guards.py.
Referenced by Tensor.call_accessor(), WallClock< output_timestamps >.start(), WallClock< output_timestamps >.stop(), OpenCLMemoryUsage.test_start(), and OpenCLClock< output_timestamps >.test_start().
str
str
Definition at line 162 of file check_header_guards.py.
type
type
Definition at line 162 of file check_header_guards.py.