Compute Library: StrategyType< true, TInput, TWeight, TOutput, int32_t, arm_gemm::Requantize32 > Struct Template Reference
StrategyType< true, TInput, TWeight, TOutput, int32_t, arm_gemm::Requantize32 > Struct Template Reference
#include <depthwise_depthfirst_multiplier.hpp>
Public Types
using Type = GenericDepthfirstMultiplierStrategy< TInput, TWeight, TOutput, int32_t, arm_gemm::Requantize32 >
Static Public Member Functions
template<typename WorkspaceType >
static void execute (const DepthwiseArgs &args, const WorkspaceType *ws, const Type *strat, const arm_gemm::Requantize32 &qp, const unsigned int start_output_channel, const void *parameters, const void *)
Detailed Description
template<typename TInput, typename TWeight, typename TOutput>
struct arm_conv::depthwise::depthfirst_multiplier::StrategyType< true, TInput, TWeight, TOutput, int32_t, arm_gemm::Requantize32 >
Definition at line 397 of file depthwise_depthfirst_multiplier.hpp.
Member Typedef Documentation
Type
using Type = GenericDepthfirstMultiplierStrategy<TInput, TWeight, TOutput, int32_t, arm_gemm::Requantize32>
Definition at line 399 of file depthwise_depthfirst_multiplier.hpp.
Member Function Documentation
execute()
static void execute (const DepthwiseArgs & args, const WorkspaceType * ws, const Type * strat, const arm_gemm::Requantize32 & qp, const unsigned int start_output_channel, const void * parameters, const void *) inline static
Definition at line 402 of file depthwise_depthfirst_multiplier.hpp.
   {
     auto get_ptr = [start_output_channel] (const int32_t *ptr) -> const int32_t *
     {
       return ptr == nullptr ? nullptr : ptr + start_output_channel;
     };
     strat->get_kernel()(
       ws->input_rows, ws->outptr_array,
       reinterpret_cast<const TWeight *>(parameters),
       get_ptr(qp.bias),
       strat->get_kernel_rows() * strat->get_kernel_cols(),
       args.channel_multiplier,
       get_ptr(qp.per_channel_left_shifts),
       get_ptr(qp.per_channel_muls),
       get_ptr(qp.per_channel_right_shifts),
       qp
     );
   }
References GemmTuner::args, Requantize32::bias, GenericDepthfirstMultiplierStrategy< TInput, TWeight, TOutput, TAccum, OutputStage >::get_kernel(), DepthwiseDepthfirstStrategyCommon< TInput, TWeight, TOutput, TAccum, OutputStage >::get_kernel_cols(), DepthwiseDepthfirstStrategyCommon< TInput, TWeight, TOutput, TAccum, OutputStage >::get_kernel_rows(), arm_compute::test::parameters, Requantize32::per_channel_left_shifts, Requantize32::per_channel_muls, and Requantize32::per_channel_right_shifts.
The documentation for this struct was generated from the following file:
src/core/NEON/kernels/arm_conv/depthwise/depthwise_depthfirst_multiplier.hpp