var searchData=
[
  ['q8_2ecpp_15667',['q8.cpp',['../neon_2q8_8cpp.xhtml',1,'(Global Namespace)'],['../sve2_2q8_8cpp.xhtml',1,'(Global Namespace)']]],
  ['qasymm8_2ecpp_15668',['qasymm8.cpp',['../activation_2generic_2neon_2qasymm8_8cpp.xhtml',1,'(Global Namespace)'],['../activation_2generic_2sve2_2qasymm8_8cpp.xhtml',1,'(Global Namespace)'],['../add_2generic_2neon_2qasymm8_8cpp.xhtml',1,'(Global Namespace)'],['../add_2generic_2sve2_2qasymm8_8cpp.xhtml',1,'(Global Namespace)'],['../addmuladd_2generic_2neon_2qasymm8_8cpp.xhtml',1,'(Global Namespace)'],['../depthwiseconv2d_2generic_2neon_2qasymm8_8cpp.xhtml',1,'(Global Namespace)'],['../directconv2d_2nhwc_2neon_2qasymm8_8cpp.xhtml',1,'(Global Namespace)'],['../elementwise__binary_2generic_2neon_2qasymm8_8cpp.xhtml',1,'(Global Namespace)'],['../elementwise__binary_2generic_2sve2_2qasymm8_8cpp.xhtml',1,'(Global Namespace)'],['../elementwise__unary_2generic_2neon_2qasymm8_8cpp.xhtml',1,'(Global Namespace)'],['../maxunpool_2generic_2neon_2qasymm8_8cpp.xhtml',1,'(Global Namespace)'],['../meanstddevnorm_2generic_2neon_2qasymm8_8cpp.xhtml',1,'(Global Namespace)'],['../pool2d_2neon_2qasymm8_8cpp.xhtml',1,'(Global Namespace)'],['../pool3d_2neon_2qasymm8_8cpp.xhtml',1,'(Global Namespace)'],['../roialign_2generic_2neon_2qasymm8_8cpp.xhtml',1,'(Global Namespace)'],['../scale_2neon_2qasymm8_8cpp.xhtml',1,'(Global Namespace)'],['../scale_2sve_2qasymm8_8cpp.xhtml',1,'(Global Namespace)'],['../softmax_2generic_2neon_2qasymm8_8cpp.xhtml',1,'(Global Namespace)'],['../sub_2neon_2qasymm8_8cpp.xhtml',1,'(Global Namespace)']]],
  ['qasymm8_5fsigned_2ecpp_15669',['qasymm8_signed.cpp',['../activation_2generic_2neon_2qasymm8__signed_8cpp.xhtml',1,'(Global Namespace)'],['../activation_2generic_2sve2_2qasymm8__signed_8cpp.xhtml',1,'(Global Namespace)'],['../add_2generic_2neon_2qasymm8__signed_8cpp.xhtml',1,'(Global Namespace)'],['../add_2generic_2sve2_2qasymm8__signed_8cpp.xhtml',1,'(Global Namespace)'],['../addmuladd_2generic_2neon_2qasymm8__signed_8cpp.xhtml',1,'(Global Namespace)'],['../depthwiseconv2d_2generic_2neon_2qasymm8__signed_8cpp.xhtml',1,'(Global Namespace)'],['../elementwise__binary_2generic_2neon_2qasymm8__signed_8cpp.xhtml',1,'(Global Namespace)'],['../elementwise__binary_2generic_2sve2_2qasymm8__signed_8cpp.xhtml',1,'(Global Namespace)'],['../elementwise__unary_2generic_2neon_2qasymm8__signed_8cpp.xhtml',1,'(Global Namespace)'],['../maxunpool_2generic_2neon_2qasymm8__signed_8cpp.xhtml',1,'(Global Namespace)'],['../pool2d_2neon_2qasymm8__signed_8cpp.xhtml',1,'(Global Namespace)'],['../pool3d_2neon_2qasymm8__signed_8cpp.xhtml',1,'(Global Namespace)'],['../roialign_2generic_2neon_2qasymm8__signed_8cpp.xhtml',1,'(Global Namespace)'],['../scale_2neon_2qasymm8__signed_8cpp.xhtml',1,'(Global Namespace)'],['../scale_2sve_2qasymm8__signed_8cpp.xhtml',1,'(Global Namespace)'],['../softmax_2generic_2neon_2qasymm8__signed_8cpp.xhtml',1,'(Global Namespace)'],['../sub_2neon_2qasymm8__signed_8cpp.xhtml',1,'(Global Namespace)']]],
  ['qlstm_5flayer_5fnormalization_2ecl_15670',['qlstm_layer_normalization.cl',['../qlstm__layer__normalization_8cl.xhtml',1,'']]],
  ['qlstmlayernormalization_2ecpp_15671',['QLSTMLayerNormalization.cpp',['../_c_l_2_q_l_s_t_m_layer_normalization_8cpp.xhtml',1,'(Global Namespace)'],['../_n_e_o_n_2_q_l_s_t_m_layer_normalization_8cpp.xhtml',1,'(Global Namespace)'],['../reference_2_q_l_s_t_m_layer_normalization_8cpp.xhtml',1,'(Global Namespace)']]],
  ['qlstmlayernormalization_2eh_15672',['QLSTMLayerNormalization.h',['../_q_l_s_t_m_layer_normalization_8h.xhtml',1,'']]],
  ['qmov_2eh_15673',['qmov.h',['../qmov_8h.xhtml',1,'']]],
  ['qmovun_2eh_15674',['qmovun.h',['../qmovun_8h.xhtml',1,'']]],
  ['qsymm16_2ecpp_15675',['qsymm16.cpp',['../activation_2generic_2neon_2qsymm16_8cpp.xhtml',1,'(Global Namespace)'],['../activation_2generic_2sve2_2qsymm16_8cpp.xhtml',1,'(Global Namespace)'],['../add_2generic_2neon_2qsymm16_8cpp.xhtml',1,'(Global Namespace)'],['../add_2generic_2sve2_2qsymm16_8cpp.xhtml',1,'(Global Namespace)'],['../boundingboxtransform_2generic_2neon_2qsymm16_8cpp.xhtml',1,'(Global Namespace)'],['../genproposals_2generic_2neon_2qsymm16_8cpp.xhtml',1,'(Global Namespace)'],['../sub_2neon_2qsymm16_8cpp.xhtml',1,'(Global Namespace)']]],
  ['quantization_5flayer_2ecl_15676',['quantization_layer.cl',['../quantization__layer_8cl.xhtml',1,'']]],
  ['quantizationinfo_2eh_15677',['QuantizationInfo.h',['../_quantization_info_8h.xhtml',1,'']]],
  ['quantizationlayer_2ecpp_15678',['QuantizationLayer.cpp',['../_c_l_2_quantization_layer_8cpp.xhtml',1,'(Global Namespace)'],['../_n_e_o_n_2_quantization_layer_8cpp.xhtml',1,'(Global Namespace)'],['../reference_2_quantization_layer_8cpp.xhtml',1,'(Global Namespace)']]],
  ['quantizationlayer_2eh_15679',['QuantizationLayer.h',['../_quantization_layer_8h.xhtml',1,'']]],
  ['quantizationlayernode_2ecpp_15680',['QuantizationLayerNode.cpp',['../_quantization_layer_node_8cpp.xhtml',1,'']]],
  ['quantizationlayernode_2eh_15681',['QuantizationLayerNode.h',['../_quantization_layer_node_8h.xhtml',1,'']]],
  ['quantize_5fwrapper_2ehpp_15682',['quantize_wrapper.hpp',['../quantize__wrapper_8hpp.xhtml',1,'']]],
  ['quantized_2ecpp_15683',['quantized.cpp',['../quantized_8cpp.xhtml',1,'']]],
  ['quantized_2eh_15684',['quantized.h',['../conv3d_2neon_2quantized_8h.xhtml',1,'(Global Namespace)'],['../pool2d_2neon_2quantized_8h.xhtml',1,'(Global Namespace)'],['../pool3d_2neon_2quantized_8h.xhtml',1,'(Global Namespace)']]],
  ['quantized_2ehpp_15685',['quantized.hpp',['../quantized_8hpp.xhtml',1,'']]],
  ['queue_2ecpp_15686',['Queue.cpp',['../cpu_2unit_2_queue_8cpp.xhtml',1,'(Global Namespace)'],['../gpu_2unit_2_queue_8cpp.xhtml',1,'(Global Namespace)']]]
];
