Compute Library: ClScaleKernel Class Reference
ClScaleKernel Class Reference
Interface for the scale kernel.
#include <ClScaleKernel.h>
Public Member Functions
ClScaleKernel ()=default
Default constructor.
ARM_COMPUTE_DISALLOW_COPY_ALLOW_MOVE (ClScaleKernel)
void configure (const CLCompileContext &compile_context, ITensorInfo *src, ITensorInfo *dst, const ScaleKernelInfo &info)
Initialise the kernel's inputs, output and interpolation policy.
BorderSize border_size () const override
The size of the border for that kernel.
void run_op (ITensorPack &tensors, const Window &window, cl::CommandQueue &queue) override
Enqueue the OpenCL kernel to process the given window on the passed OpenCL command queue.
Public Member Functions inherited from ICLKernel
ICLKernel ()
Constructor.
cl::Kernel & kernel ()
Returns a reference to the OpenCL kernel of this object.
template<typename T >
void add_1D_array_argument (unsigned int &idx, const ICLArray< T > *array, const Strides &strides, unsigned int num_dimensions, const Window &window)
Add the passed 1D array's parameters to the object's kernel's arguments starting from the index idx.
void add_1D_tensor_argument (unsigned int &idx, const ICLTensor *tensor, const Window &window)
Add the passed 1D tensor's parameters to the object's kernel's arguments starting from the index idx.
void add_1D_tensor_argument_if (bool cond, unsigned int &idx, const ICLTensor *tensor, const Window &window)
Add the passed 1D tensor's parameters to the object's kernel's arguments starting from the index idx if the condition is true.
void add_2D_tensor_argument (unsigned int &idx, const ICLTensor *tensor, const Window &window)
Add the passed 2D tensor's parameters to the object's kernel's arguments starting from the index idx.
void add_2D_tensor_argument_if (bool cond, unsigned int &idx, const ICLTensor *tensor, const Window &window)
Add the passed 2D tensor's parameters to the object's kernel's arguments starting from the index idx if the condition is true.
void add_3D_tensor_argument (unsigned int &idx, const ICLTensor *tensor, const Window &window)
Add the passed 3D tensor's parameters to the object's kernel's arguments starting from the index idx.
void add_4D_tensor_argument (unsigned int &idx, const ICLTensor *tensor, const Window &window)
Add the passed 4D tensor's parameters to the object's kernel's arguments starting from the index idx.
virtual void run (const Window &window, cl::CommandQueue &queue)
Enqueue the OpenCL kernel to process the given window on the passed OpenCL command queue.
template<typename T >
void add_argument (unsigned int &idx, T value)
Add the passed parameters to the object's kernel's arguments starting from the index idx.
void set_lws_hint (const cl::NDRange &lws_hint)
Set the Local-Workgroup-Size hint.
cl::NDRange lws_hint () const
Return the Local-Workgroup-Size hint.
void set_wbsm_hint (const cl_int &wbsm_hint)
Set the workgroup batch size modifier hint.
cl_int wbsm_hint () const
Return the workgroup batch size modifier hint.
const std::string & config_id () const
Get the configuration ID.
void set_target (GPUTarget target)
Set the targeted GPU architecture.
void set_target (cl::Device &device)
Set the targeted GPU architecture according to the CL device.
GPUTarget get_target () const
Get the targeted GPU architecture.
size_t get_max_workgroup_size ()
Get the maximum workgroup size for the device the CLKernelLibrary uses.
template<unsigned int dimension_size>
void add_tensor_argument (unsigned &idx, const ICLTensor *tensor, const Window &window)
template<typename T , unsigned int dimension_size>
void add_array_argument (unsigned &idx, const ICLArray< T > *array, const Strides &strides, unsigned int num_dimensions, const Window &window)
Add the passed array's parameters to the object's kernel's arguments starting from the index idx.
Public Member Functions inherited from IKernel
IKernel ()
Constructor.
virtual ~IKernel ()=default
Destructor.
virtual bool is_parallelisable () const
Indicates whether or not the kernel is parallelisable.
const Window & window () const
The maximum window the kernel can be executed on.
bool is_window_configured () const
Function to check if the embedded window of this kernel has been configured.
Static Public Member Functions
static Status validate (const ITensorInfo *src, const ITensorInfo *dst, const ScaleKernelInfo &info)
Static function to check if given info will lead to a valid configuration of ClScaleKernel.
Static Public Member Functions inherited from ICLKernel
static constexpr unsigned int num_arguments_per_1D_array ()
Returns the number of arguments enqueued per 1D array object.
static constexpr unsigned int num_arguments_per_1D_tensor ()
Returns the number of arguments enqueued per 1D tensor object.
static constexpr unsigned int num_arguments_per_2D_tensor ()
Returns the number of arguments enqueued per 2D tensor object.
static constexpr unsigned int num_arguments_per_3D_tensor ()
Returns the number of arguments enqueued per 3D tensor object.
static constexpr unsigned int num_arguments_per_4D_tensor ()
Returns the number of arguments enqueued per 4D tensor object.
static cl::NDRange gws_from_window (const Window &window)
Get the global work size given an execution window.
Detailed Description
Interface for the scale kernel.
Definition at line 41 of file ClScaleKernel.h.
Constructor & Destructor Documentation
ClScaleKernel()
ClScaleKernel () default
Default constructor.
Member Function Documentation
ARM_COMPUTE_DISALLOW_COPY_ALLOW_MOVE()
ARM_COMPUTE_DISALLOW_COPY_ALLOW_MOVE (ClScaleKernel)
border_size()
BorderSize border_size () const override virtual
The size of the border for that kernel.
Returns
The width in number of elements of the border.
Reimplemented from IKernel.
Definition at line 128 of file ClScaleKernel.cpp.
 {
     return BorderSize(static_cast<size_t>(_data_layout == DataLayout::NCHW));
 }
References arm_compute::NCHW.
Referenced by ClScaleKernel::configure().
configure()
void configure (const CLCompileContext & compile_context, ITensorInfo * src, ITensorInfo * dst, const ScaleKernelInfo & info)
Initialise the kernel's inputs, output and interpolation policy.
Parameters
[in] compile_context The compile context to be used.
[in] src Source tensor info. Data types supported: U8/QASYMM8/QASYMM8_SIGNED/S16/F16/F32
[out] dst Destination tensor info. Data types supported: Same as src All but the lowest two dimensions must be the same size as in the input tensor, i.e. scaling is only performed within the XY-plane.
[in] info ScaleKernelInfo Kernel descriptor to be used to configure.
Definition at line 143 of file ClScaleKernel.cpp.
 {
     ARM_COMPUTE_ERROR_THROW_ON(validate_arguments(src, dst, info));
     auto padding_info = get_padding_info({ src, dst });
     // Info required for the static tuning
     _data_layout = info.data_layout == DataLayout::UNKNOWN ? src->data_layout() : info.data_layout;
     float wr = 0.f;
     float hr = 0.f;
     std::tie(wr, hr) = calculate_scale_factors(src, dst, _data_layout, info.align_corners);
     const bool call_quantized_kernel = is_data_type_quantized_asymmetric(src->data_type()) && info.interpolation_policy == InterpolationPolicy::BILINEAR;
     // Compute actual border size
     BorderSize border  = border_size();
     const bool is_nhwc = _data_layout == DataLayout::NHWC;
     // Area interpolation behaves as Nearest Neighbour in case of up-sampling
     auto interpolation_policy_to_use = info.interpolation_policy;
     if(info.interpolation_policy == InterpolationPolicy::AREA && wr <= 1.f && hr <= 1.f)
     {
         interpolation_policy_to_use = InterpolationPolicy::NEAREST_NEIGHBOR;
     }
     // Configure kernel window
     auto win_config = validate_and_configure_window(src, dst, info, border);
     ARM_COMPUTE_ERROR_THROW_ON(win_config.first);
     ICLKernel::configure_internal(win_config.second);
     // Create kernel
     CLBuildOptions build_opts;
     build_opts.add_option("-DDATA_TYPE=" + get_cl_type_from_data_type(src->data_type()));
     build_opts.add_option("-DCONSTANT_VALUE=" + string_from_pixel_value(info.constant_border_value, src->data_type()));
     build_opts.add_option("-DBORDER_SIZE=" + support::cpp11::to_string(border.right));
     build_opts.add_option_if(info.border_mode == BorderMode::REPLICATE, "-DBORDER_MODE_REPLICATE");
     build_opts.add_option_if(is_nhwc, "-DDEPTH_OUT=" + support::cpp11::to_string(dst->dimension(2)));
     build_opts.add_option_if_else(info.sampling_policy == SamplingPolicy::CENTER, "-DSAMPLING_POLICY_CENTER", "-DSAMPLING_POLICY_TOP_LEFT");
     build_opts.add_option_if(info.align_corners, "-DALIGN_CORNERS");
     if(call_quantized_kernel)
     {
         const UniformQuantizationInfo qinfo = src->quantization_info().uniform();
         build_opts.add_option("-DSCALE=" + support::cpp11::to_string(qinfo.scale));
         build_opts.add_option("-DOFFSET=" + support::cpp11::to_string(qinfo.offset));
     }
     std::string interpolation_name = string_from_interpolation_policy(interpolation_policy_to_use);
     std::transform(interpolation_name.begin(), interpolation_name.end(), interpolation_name.begin(), ::tolower);
     std::string kernel_name = "scale_" + interpolation_name;
     kernel_name += call_quantized_kernel ? "_quantized_" : "_";
     kernel_name += lower_string(string_from_data_layout(_data_layout));
     _kernel = create_kernel(compile_context, kernel_name, build_opts.options());
     if(is_nhwc)
     {
         ARM_COMPUTE_ERROR_ON(has_padding_changed(padding_info));
     }
     const int          idx_width  = get_data_layout_dimension_index(_data_layout, DataLayoutDimension::WIDTH);
     const int          idx_height = get_data_layout_dimension_index(_data_layout, DataLayoutDimension::HEIGHT);
     unsigned int       idx        = is_nhwc ? 2 * num_arguments_per_4D_tensor() : 2 * num_arguments_per_2D_tensor(); //Skip the input and output parameters
     const unsigned int src_width  = src->dimension(idx_width);
     const unsigned int dst_height = src->dimension(idx_height);
     _kernel.setArg<float>(idx++, src_width);
     _kernel.setArg<float>(idx++, dst_height);
     _kernel.setArg<float>(idx++, wr);
     _kernel.setArg<float>(idx++, hr);
     // Set config_id for enabling LWS tuning
     _config_id = "scale_";
     _config_id += (info.border_mode == BorderMode::REPLICATE ? "Bord_rep" : "");
     _config_id += (info.sampling_policy == SamplingPolicy::CENTER ? "center" : "topleft");
     _config_id += (is_nhwc ? "nhwc" : "nchw");
     _config_id += "_";
     _config_id += support::cpp11::to_string(dst->dimension(0));
     _config_id += "_";
     _config_id += support::cpp11::to_string(dst->dimension(1));
     _config_id += "_";
     _config_id += support::cpp11::to_string(dst->dimension(2));
     _config_id += "_";
     _config_id += support::cpp11::to_string(dst->dimension(3));
 }
References CLBuildOptions::add_option(), CLBuildOptions::add_option_if(), CLBuildOptions::add_option_if_else(), ScaleKernelInfo::align_corners, arm_compute::AREA, ARM_COMPUTE_ERROR_ON, ARM_COMPUTE_ERROR_THROW_ON, arm_compute::BILINEAR, ScaleKernelInfo::border_mode, ClScaleKernel::border_size(), arm_compute::CENTER, ScaleKernelInfo::constant_border_value, arm_compute::create_kernel(), ScaleKernelInfo::data_layout, arm_compute::test::validation::dst, arm_compute::get_cl_type_from_data_type(), arm_compute::get_data_layout_dimension_index(), arm_compute::get_padding_info(), arm_compute::has_padding_changed(), arm_compute::HEIGHT, arm_compute::test::validation::idx_height, arm_compute::test::validation::idx_width, arm_compute::test::validation::info, ScaleKernelInfo::interpolation_policy, arm_compute::is_data_type_quantized_asymmetric(), kernel_name, arm_compute::lower_string(), arm_compute::NEAREST_NEIGHBOR, arm_compute::NHWC, ICLKernel::num_arguments_per_2D_tensor(), ICLKernel::num_arguments_per_4D_tensor(), QuantizationInfo::offset(), CLBuildOptions::options(), arm_compute::test::validation::qinfo, arm_compute::REPLICATE, ScaleKernelInfo::sampling_policy, QuantizationInfo::scale(), arm_compute::test::validation::src, arm_compute::string_from_data_layout(), arm_compute::string_from_interpolation_policy(), arm_compute::string_from_pixel_value(), arm_compute::support::cpp11::to_string(), arm_compute::utility::tolower(), arm_compute::UNKNOWN, arm_compute::validate_arguments(), and arm_compute::WIDTH.
run_op()
void run_op (ITensorPack & tensors, const Window & window, cl::CommandQueue & queue) override virtual
Enqueue the OpenCL kernel to process the given window on the passed OpenCL command queue.
Note
The queue is not flushed by this method, and therefore the kernel will not have been executed by the time this method returns.
Parameters
[in] tensors A vector containing the tensors to operato on.
[in] window Region on which to execute the kernel. (Must be a valid region of the window returned by window()).
[in,out] queue Command queue on which to enqueue the kernel.
Reimplemented from ICLKernel.
Definition at line 225 of file ClScaleKernel.cpp.
 {
     ARM_COMPUTE_ERROR_ON_UNCONFIGURED_KERNEL(this);
     ARM_COMPUTE_ERROR_ON_INVALID_SUBWINDOW(ICLKernel::window(), window);
     auto src = utils::cast::polymorphic_downcast<const ICLTensor *>(tensors.get_const_tensor(TensorType::ACL_SRC));
     auto dst = utils::cast::polymorphic_downcast<ICLTensor *>(tensors.get_tensor(TensorType::ACL_DST));
     switch(_data_layout)
     {
         case DataLayout::NCHW:
         {
             Window slice = window.first_slice_window_2D();
             do
             {
                 unsigned int idx = 0;
                 add_2D_tensor_argument(idx, src, slice);
                 add_2D_tensor_argument(idx, dst, slice);
                 enqueue(queue, *this, slice, lws_hint());
             }
             while(window.slide_window_slice_2D(slice));
             break;
         }
         case DataLayout::NHWC:
         {
             Window collapsed = window.collapse(ICLKernel::window(), Window::DimZ);
             Window slice     = collapsed.first_slice_window_4D();
             unsigned int idx = 0;
             add_4D_tensor_argument(idx, src, slice);
             add_4D_tensor_argument(idx, dst, slice);
             enqueue(queue, *this, slice, lws_hint());
             break;
         }
         default:
             ARM_COMPUTE_ERROR("Data layout not supported");
     }
 }
References arm_compute::ACL_DST, arm_compute::ACL_SRC, ICLKernel::add_2D_tensor_argument(), ICLKernel::add_4D_tensor_argument(), ARM_COMPUTE_ERROR, ARM_COMPUTE_ERROR_ON_INVALID_SUBWINDOW, ARM_COMPUTE_ERROR_ON_UNCONFIGURED_KERNEL, Window::collapse(), Window::DimZ, arm_compute::test::validation::dst, arm_compute::enqueue(), Window::first_slice_window_2D(), Window::first_slice_window_4D(), ITensorPack::get_const_tensor(), ITensorPack::get_tensor(), ICLKernel::lws_hint(), arm_compute::NCHW, arm_compute::NHWC, arm_compute::test::validation::reference::slice(), Window::slide_window_slice_2D(), arm_compute::test::validation::src, and IKernel::window().
validate()
Status validate (const ITensorInfo * src, const ITensorInfo * dst, const ScaleKernelInfo & info) static
Static function to check if given info will lead to a valid configuration of ClScaleKernel.
Parameters
[in] src Source tensor info. Data types supported: U8/QASYMM8/QASYMM8_SIGNED/S16/F16/F32
[in] dst Destination tensor info. Data types supported: Same as src All but the lowest two dimensions must be the same size as in the input tensor, i.e. scaling is only performed within the XY-plane.
[in] info ScaleKernelInfo Kernel descriptor to be used to validate
Returns
a status
Definition at line 133 of file ClScaleKernel.cpp.
 {
     ARM_COMPUTE_RETURN_ON_ERROR(validate_arguments(src, dst, info));
     const DataLayout data_layout = info.data_layout == DataLayout::UNKNOWN ? src->data_layout() : info.data_layout;
     BorderSize       border      = BorderSize(static_cast<size_t>(data_layout == DataLayout::NCHW));
     ARM_COMPUTE_RETURN_ON_ERROR(validate_and_configure_window(src->clone().get(), dst->clone().get(), info, border).first);
     return Status{};
 }
References ARM_COMPUTE_RETURN_ON_ERROR, arm_compute::test::validation::data_layout, ScaleKernelInfo::data_layout, arm_compute::test::validation::dst, arm_compute::test::validation::info, arm_compute::NCHW, arm_compute::test::validation::src, arm_compute::UNKNOWN, and arm_compute::validate_arguments().
Referenced by ClScale::validate().
The documentation for this class was generated from the following files:
src/core/gpu/cl/kernels/ClScaleKernel.h
src/core/gpu/cl/kernels/ClScaleKernel.cpp