Compute Library: CLRange Class Reference
CLRange Class Reference
Basic function to run CLRangeKernel.
#include <CLRange.h>
Public Member Functions
void configure (ICLTensor *output, float start, float end, float step=1.f)
Initialize the kernel's start, end, step and output tensor.
void configure (const CLCompileContext &compile_context, ICLTensor *output, float start, float end, float step=1.f)
Initialize the kernel's start, end, step and output tensor.
Public Member Functions inherited from ICLSimpleFunction
ICLSimpleFunction (CLRuntimeContext *ctx=nullptr)
Constructor.
ICLSimpleFunction (const ICLSimpleFunction &)=delete
Prevent instances of this class from being copied (As this class contains pointers)
ICLSimpleFunction (ICLSimpleFunction &&)=default
Default move constructor.
ICLSimpleFunction & operator= (const ICLSimpleFunction &)=delete
Prevent instances of this class from being copied (As this class contains pointers)
ICLSimpleFunction & operator= (ICLSimpleFunction &&)=default
Default move assignment operator.
~ICLSimpleFunction ()
Default destructor.
void run () override final
Run the kernels contained in the function.
Public Member Functions inherited from IFunction
virtual ~IFunction ()=default
Destructor.
virtual void prepare ()
Prepare the function for executing.
Static Public Member Functions
static Status validate (const ITensorInfo *output, float start, float end, float step=1.f)
Static function to check if given info will lead to a valid configuration of CLRange.
Detailed Description
Basic function to run CLRangeKernel.
Note
The tensor data type for the output must be U8/S8/QASYMM8/U16/S16/U32/S32/F16/F32.
The function performs generates a sequence with the given start, end and step.
Definition at line 41 of file CLRange.h.
Member Function Documentation
configure() [1/2]
void configure (ICLTensor * output, float start, float end, float step = 1.f)
Initialize the kernel's start, end, step and output tensor.
Valid data layouts:
All
Valid data type configurations:
dst
U8
S8
QASYMM8
U16
S16
U32
S32
F16
F32
Parameters
[out] output Output tensor. Data types supported: U8/S8/QASYMM8/U16/S16/U32/S32/F16/F32.
[in] start The starting value of the sequence.
[in] end The ending (not including) value of the sequence.
[in] step The gap between each pair of values in the sequence. Default is 1.
Definition at line 34 of file CLRange.cpp.
 {
     configure(CLKernelLibrary::get().get_compile_context(), output, start, end, step);
 }
References arm_compute::mlgo::parser::end(), CLKernelLibrary::get(), and arm_compute::cpu::step.
configure() [2/2]
void configure (const CLCompileContext & compile_context, ICLTensor * output, float start, float end, float step = 1.f)
Initialize the kernel's start, end, step and output tensor.
Parameters
[in] compile_context The compile context to be used.
[out] output Output tensor. Data types supported: U8/S8/QASYMM8/U16/S16/U32/S32/F16/F32.
[in] start The starting value of the sequence.
[in] end The ending (not including) value of the sequence.
[in] step The gap between each pair of values in the sequence. Default is 1.
Definition at line 39 of file CLRange.cpp.
 {
     auto k = std::make_unique<CLRangeKernel>();
     k->set_target(CLScheduler::get().target());
     k->configure(compile_context, output, start, end, step);
     _kernel = std::move(k);
     // Tune kernels
     CLScheduler::get().tune_kernel_static(*_kernel);
 }
References arm_compute::mlgo::parser::end(), CLScheduler::get(), arm_compute::cpu::step, and CLScheduler::tune_kernel_static().
validate()
Status validate (const ITensorInfo * output, float start, float end, float step = 1.f) static
Static function to check if given info will lead to a valid configuration of CLRange.
Parameters
[in] output Output tensor info. Data types supported: U8/S8/QASYMM8/U16/S16/U32/S32/F16/F32.
[in] start The starting value of the sequence.
[in] end The ending (not including) value of the sequence.
[in] step The gap between each pair of values in the sequence. Default is 1.
Returns
a status
Definition at line 50 of file CLRange.cpp.
 {
     return CLRangeKernel::validate(output, start, end, step);
 }
References arm_compute::mlgo::parser::end(), arm_compute::cpu::step, and CLRangeKernel::validate().
The documentation for this class was generated from the following files:
arm_compute/runtime/CL/functions/CLRange.h
src/runtime/CL/functions/CLRange.cpp