Compute Library: NEGEMMLowpOffsetContributionOutputStageKernel Class Reference
NEGEMMLowpOffsetContributionOutputStageKernel Class Reference
Kernel used to add the offset contribution and perform the output stage after NEGEMMLowpMatrixMultiplyKernel.
#include <NEGEMMLowpOffsetContributionOutputStageKernel.h>
Public Member Functions
const char * name () const override
Name of the kernel.
NEGEMMLowpOffsetContributionOutputStageKernel ()
Constructor.
NEGEMMLowpOffsetContributionOutputStageKernel (const NEGEMMLowpOffsetContributionOutputStageKernel &)=delete
Prevent instances of this class from being copied (As this class contains pointers)
NEGEMMLowpOffsetContributionOutputStageKernel & operator= (const NEGEMMLowpOffsetContributionOutputStageKernel &)=delete
Prevent instances of this class from being copied (As this class contains pointers)
NEGEMMLowpOffsetContributionOutputStageKernel (NEGEMMLowpOffsetContributionOutputStageKernel &&)=default
Allow instances of this class to be moved.
NEGEMMLowpOffsetContributionOutputStageKernel & operator= (NEGEMMLowpOffsetContributionOutputStageKernel &&)=default
Allow instances of this class to be moved.
~NEGEMMLowpOffsetContributionOutputStageKernel ()=default
Default destructor.
void configure (const ITensor *mm_result, const ITensor *vector_sum_col, const ITensor *vector_sum_row, const ITensor *bias, ITensor *output, int32_t k, int32_t a_offset, int32_t b_offset, GEMMLowpOutputStageInfo output_stage)
Initialise the kernel's input and output.
void run (const Window &window, const ThreadInfo &info) override
Execute the kernel on the passed window.
Public Member Functions inherited from ICPPKernel
virtual ~ICPPKernel ()=default
Default destructor.
virtual void run_nd (const Window &window, const ThreadInfo &info, const Window &thread_locator)
legacy compatibility layer for implemantions which do not support thread_locator In these cases we simply narrow the interface down the legacy version
virtual void run_op (ITensorPack &tensors, const Window &window, const ThreadInfo &info)
Execute the kernel on the passed window.
Public Member Functions inherited from IKernel
IKernel ()
Constructor.
virtual ~IKernel ()=default
Destructor.
virtual bool is_parallelisable () const
Indicates whether or not the kernel is parallelisable.
virtual BorderSize border_size () const
The size of the border for that kernel.
const Window & window () const
The maximum window the kernel can be executed on.
bool is_window_configured () const
Function to check if the embedded window of this kernel has been configured.
Static Public Member Functions
static Status validate (const ITensorInfo *mm_result, const ITensorInfo *vector_sum_col, const ITensorInfo *vector_sum_row, const ITensorInfo *bias, const ITensorInfo *output, int32_t a_offset, int32_t b_offset, GEMMLowpOutputStageInfo output_stage)
Static function to check if given info will lead to a valid configuration of NEGEMMLowpOffsetContributionOutputStageKernel.
Detailed Description
Kernel used to add the offset contribution and perform the output stage after NEGEMMLowpMatrixMultiplyKernel.
The computation is performed in-place
This kernel takes a final int32 accumulator value (the output of NEGEMMLowpMatrixMultiplyKernel), and adds to it the offset contribution of matrix A and matrix B in-place.
The output stage can perform either QuantizeDownInt32ToUint8Scale or QuantizeDownInt32ToUint8ScaleByFixedPoint for Uint8. The output stage can perform either QuantizeDownInt32ToInt8Scale or QuantizeDownInt32ToInt8ScaleByFixedPoint for Int8.
For QuantizeDownInt32ToUint8Scale/QuantizeDownInt32ToInt8Scale the final result is:
((mm_result'[i][k] + result_offset) * result_mult_int) >> result_shift
For QuantizeDownInt32ToUint8ScaleByFixedPoint/QuantizeDownInt32ToInt8ScaleByFixedPoint the final result is:
(FixedPointMul(mm_result'[i][k], result_fixedpoint_multiplier) >> result_shift) + result_offset_after_shift
where FixedPointMul(x, y) is the nearest integer to the following mathematical expression, evaluated without overflow or intermediate rounding:
(x * y) / 2^31
and mm_result'[i][k] = mm_result[i][k] + (vector_sum_col[k] * a_offset) + (vector_sum_row[i] * b_offset) + (a_offset * b_offset * k)
Definition at line 62 of file NEGEMMLowpOffsetContributionOutputStageKernel.h.
Constructor & Destructor Documentation
NEGEMMLowpOffsetContributionOutputStageKernel() [1/3]
NEGEMMLowpOffsetContributionOutputStageKernel ()
Constructor.
Definition at line 856 of file NEGEMMLowpOffsetContributionOutputStageKernel.cpp.
     : _vector_sum_col(nullptr), _vector_sum_row(nullptr), _bias(nullptr), _mm_result(nullptr), _output(nullptr), _a_offset(0), _b_offset(0), _k_offset(0), _slide_vector_sum_col(true),
       _output_stage(GEMMLowpOutputStageInfo())
 {
 }
NEGEMMLowpOffsetContributionOutputStageKernel() [2/3]
NEGEMMLowpOffsetContributionOutputStageKernel (const NEGEMMLowpOffsetContributionOutputStageKernel &) delete
Prevent instances of this class from being copied (As this class contains pointers)
NEGEMMLowpOffsetContributionOutputStageKernel() [3/3]
NEGEMMLowpOffsetContributionOutputStageKernel (NEGEMMLowpOffsetContributionOutputStageKernel &&) default
Allow instances of this class to be moved.
~NEGEMMLowpOffsetContributionOutputStageKernel()
~NEGEMMLowpOffsetContributionOutputStageKernel () default
Default destructor.
Member Function Documentation
configure()
void configure (const ITensor * mm_result, const ITensor * vector_sum_col, const ITensor * vector_sum_row, const ITensor * bias, ITensor * output, int32_t k, int32_t a_offset, int32_t b_offset, GEMMLowpOutputStageInfo output_stage)
Initialise the kernel's input and output.
Parameters
[in] mm_result Input tensor containing the result of NEGEMMLowpMatrixMultiplyKernel. Data type supported: S32
[in] vector_sum_col Input row-vector of sums of all the entries in each column of matrix B. Note: vector_sum_col can be a nullptr in case a_offset = 0. Data type supported: same as mm_result
[in] vector_sum_row Input row-vector of sums of all the entries in each row of matrix A.
[in] bias Biases tensor. Only shared biases supported and it can be a nullptr if the addition of biases is not required. Biases are 1D tensor with dimensions [OFM]. Data type supported: Same as mm_result.
[out] output Output tensor containing the final quantized result. Data type supported: QASYMM8/QASYMM8_SIGNED
[in] k Number of matrix A columns or Matrix B rows
[in] a_offset Offset to be added to each element of the matrix A.
[in] b_offset Offset to be added to each element of the matrix B.
[in] output_stage GEMMLowp output stage info, providing the type of quantization and the necessary parameters.
Definition at line 863 of file NEGEMMLowpOffsetContributionOutputStageKernel.cpp.
 {
     // Perform validate step
     ARM_COMPUTE_ERROR_ON_NULLPTR(mm_result, output);
     ARM_COMPUTE_ERROR_THROW_ON(validate_arguments(mm_result->info(),
                                                   vector_sum_col != nullptr ? vector_sum_col->info() : nullptr, // NOLINT
                                                   vector_sum_row != nullptr ? vector_sum_row->info() : nullptr, // NOLINT
                                                   bias != nullptr ? bias->info() : nullptr,                     // NOLINT
                                                   output->info(), a_offset, b_offset, output_stage));           // NOLINT
     _vector_sum_col = vector_sum_col;
     _vector_sum_row = vector_sum_row;
     _bias           = bias;
     _mm_result      = mm_result;
     _output         = output;
     _a_offset       = a_offset;
     _b_offset       = b_offset;
     _k_offset       = a_offset * b_offset * k;
     _output_stage   = output_stage;
     // If a_offset == 0, vector_sum_col can be a nullptr
     if(a_offset != 0)
     {
         // Check if vector_sum_col_shape should be slidden or not
         // Don't slide vector_sum_col_shape along the y dimension if vector_sum_col_shape has just 1 dimension and vector_sum_row_shape more than 1
         // This scenario can happen when the the matrix multiplication is used to perform a convolution operation
         _slide_vector_sum_col = vector_sum_col->info()->tensor_shape().num_dimensions() > 1;
     }
     // Configure kernel window
     auto win_config = validate_and_configure_window(mm_result->info(), output->info());
     ARM_COMPUTE_ERROR_THROW_ON(win_config.first);
     INEKernel::configure(win_config.second);
 }
References ARM_COMPUTE_ERROR_ON_NULLPTR, ARM_COMPUTE_ERROR_THROW_ON, ITensor::info(), Dimensions< T >::num_dimensions(), ITensorInfo::tensor_shape(), and arm_compute::validate_arguments().
name()
const char* name () const inline override virtual
Name of the kernel.
Returns
Kernel name
Implements ICPPKernel.
Definition at line 65 of file NEGEMMLowpOffsetContributionOutputStageKernel.h.
     {
         return "NEGEMMLowpOffsetContributionOutputStageKernel";
     }
operator=() [1/2]
NEGEMMLowpOffsetContributionOutputStageKernel& operator= (const NEGEMMLowpOffsetContributionOutputStageKernel &) delete
Prevent instances of this class from being copied (As this class contains pointers)
operator=() [2/2]
NEGEMMLowpOffsetContributionOutputStageKernel& operator= (NEGEMMLowpOffsetContributionOutputStageKernel &&) default
Allow instances of this class to be moved.
run()
void run (const Window & window, const ThreadInfo & info) override virtual
Execute the kernel on the passed window.
Warning
If is_parallelisable() returns false then the passed window must be equal to window()
Note
The window has to be a region within the window returned by the window() method
The width of the window has to be a multiple of num_elems_processed_per_iteration().
Parameters
[in] window Region on which to execute the kernel. (Must be a region of the window returned by window())
[in] info Info about executing thread and CPU.
Reimplemented from ICPPKernel.
Definition at line 912 of file NEGEMMLowpOffsetContributionOutputStageKernel.cpp.
 {
     ARM_COMPUTE_UNUSED(info);
     ARM_COMPUTE_ERROR_ON_UNCONFIGURED_KERNEL(this);
     ARM_COMPUTE_ERROR_ON_INVALID_SUBWINDOW(INEKernel::window(), window);
     PixelValue type_min{};
     PixelValue type_max{};
     std::tie(type_min, type_max) = get_min_max(_output->info()->data_type());
     int32_t type_min_int = type_min.get<int32_t>();
     int32_t type_max_int = type_max.get<int32_t>();
     const bool reinterpret_as_3d = _vector_sum_row != nullptr
                                    && _mm_result->info()->num_dimensions() > 1
                                    && _mm_result->info()->tensor_shape().y() != _vector_sum_row->info()->tensor_shape().x();
     const bool is_bounded_relu = !(_output_stage.gemmlowp_min_bound <= type_min_int && _output_stage.gemmlowp_max_bound >= type_max_int);
     // Check if we need to perform fixed point requantization
     const bool is_fixed_point = _output_stage.type != GEMMLowpOutputStageType::QUANTIZE_DOWN;
     // Check if symmetric per-channel execution
     const bool is_signed = _output->info()->data_type() == DataType::QASYMM8_SIGNED;
     // Check if symmetric per-channel execution
     const bool is_symm = _output_stage.is_quantized_per_channel;
     if(is_symm)
     {
         run_offset_contribution_output_stage_symm(window, _mm_result, _vector_sum_col, _vector_sum_row, _bias, _output, _a_offset, _b_offset, _k_offset, _slide_vector_sum_col, _output_stage,
                                                   reinterpret_as_3d, is_bounded_relu, is_fixed_point);
     }
     else
     {
         if(is_signed)
         {
             run_offset_contribution_output_stage<int8_t>(window, _mm_result, _vector_sum_col, _vector_sum_row, _bias, _output, _a_offset, _b_offset, _k_offset, _slide_vector_sum_col, _output_stage,
                                                          reinterpret_as_3d, is_bounded_relu, is_fixed_point);
         }
         else
         {
             run_offset_contribution_output_stage<uint8_t>(window, _mm_result, _vector_sum_col, _vector_sum_row, _bias, _output, _a_offset, _b_offset, _k_offset, _slide_vector_sum_col, _output_stage,
                                                           reinterpret_as_3d, is_bounded_relu, is_fixed_point);
         }
     }
 }
References ARM_COMPUTE_ERROR_ON_INVALID_SUBWINDOW, ARM_COMPUTE_ERROR_ON_UNCONFIGURED_KERNEL, ARM_COMPUTE_UNUSED, ITensorInfo::data_type(), GEMMLowpOutputStageInfo::gemmlowp_max_bound, GEMMLowpOutputStageInfo::gemmlowp_min_bound, arm_compute::get_min_max(), ITensor::info(), arm_compute::test::validation::info, GEMMLowpOutputStageInfo::is_quantized_per_channel, ITensorInfo::num_dimensions(), arm_compute::QASYMM8_SIGNED, arm_compute::QUANTIZE_DOWN, ITensorInfo::tensor_shape(), GEMMLowpOutputStageInfo::type, IKernel::window(), Dimensions< T >::x(), and Dimensions< T >::y().
validate()
Status validate (const ITensorInfo * mm_result, const ITensorInfo * vector_sum_col, const ITensorInfo * vector_sum_row, const ITensorInfo * bias, const ITensorInfo * output, int32_t a_offset, int32_t b_offset, GEMMLowpOutputStageInfo output_stage) static
Static function to check if given info will lead to a valid configuration of NEGEMMLowpOffsetContributionOutputStageKernel.
Parameters
[in] mm_result Input tensor info containing the result of NEGEMMLowpMatrixMultiplyKernel. Data type supported: S32
[in] vector_sum_col Tensor info for the input row-vector of sums of all the entries in each column of matrix B. Note: vector_sum_col can be a nullptr in case a_offset = 0. Data type supported: same as mm_result
[in] vector_sum_row Tensor info for the input row-vector of sums of all the entries in each row of matrix A. Note: vector_sum_row can be a nullptr in case b_offset = 0. Data type supported: same as mm_result
[in] bias Biases tensor info. Only shared biases supported and it can be a nullptr if the addition of biases is not required. Biases are 1D tensor with dimensions [OFM]. Data type supported: Same as mm_result.
[in] output Output tensor info containing the final quantized result. Data type supported: QASYMM8/QASYMM8_SIGNED
[in] a_offset Offset to be added to each element of the matrix A.
[in] b_offset Offset to be added to each element of the matrix B.
[in] output_stage GEMMLowp output stage info, providing the type of quantization and the necessary parameters.
Returns
a status
Definition at line 902 of file NEGEMMLowpOffsetContributionOutputStageKernel.cpp.
 {
     ARM_COMPUTE_ERROR_ON_NULLPTR(mm_result, output);
     ARM_COMPUTE_RETURN_ON_ERROR(validate_arguments(mm_result, vector_sum_col, vector_sum_row, bias, output, a_offset, b_offset, output_stage));
     ARM_COMPUTE_RETURN_ON_ERROR(validate_and_configure_window(mm_result->clone().get(), output->clone().get()).first);
     return Status{};
 }
References ARM_COMPUTE_ERROR_ON_NULLPTR, ARM_COMPUTE_RETURN_ON_ERROR, ICloneable< T >::clone(), and arm_compute::validate_arguments().
Referenced by NEGEMMLowpMatrixMultiplyCore::validate().
The documentation for this class was generated from the following files:
src/core/NEON/kernels/NEGEMMLowpOffsetContributionOutputStageKernel.h
src/core/NEON/kernels/NEGEMMLowpOffsetContributionOutputStageKernel.cpp