Compute Library: CLGEMMLowpMatrixBReductionKernel Class Reference
CLGEMMLowpMatrixBReductionKernel Class Reference
OpenCL kernel used to compute the row-vectors of sums of all the entries in each column of Matrix B.
#include <CLGEMMLowpReductionKernel.h>
Public Member Functions
void configure (const ICLTensor *mtx_b, ICLTensor *vector_sum_col, const GEMMLowpReductionKernelInfo &info) override
Initialise the kernel's input and output.
void configure (const CLCompileContext &compile_context, const ICLTensor *mtx_b, ICLTensor *vector_sum_col, const GEMMLowpReductionKernelInfo &info) override
Initialise the kernel's input and output.
void run (const Window &window, cl::CommandQueue &queue) override
Enqueue the OpenCL kernel to process the given window on the passed OpenCL command queue.
Public Member Functions inherited from ICLGEMMLowpReductionKernel
ICLGEMMLowpReductionKernel ()
Constructor.
ICLGEMMLowpReductionKernel (const ICLGEMMLowpReductionKernel &)=delete
Prevent instances of this class from being copied (As this class contains pointers)
ICLGEMMLowpReductionKernel & operator= (const ICLGEMMLowpReductionKernel &)=delete
Prevent instances of this class from being copied (As this class contains pointers)
ICLGEMMLowpReductionKernel (ICLGEMMLowpReductionKernel &&)=default
Allow instances of this class to be moved.
ICLGEMMLowpReductionKernel & operator= (ICLGEMMLowpReductionKernel &&)=default
Allow instances of this class to be moved.
Public Member Functions inherited from ICLKernel
ICLKernel ()
Constructor.
cl::Kernel & kernel ()
Returns a reference to the OpenCL kernel of this object.
template<typename T >
void add_1D_array_argument (unsigned int &idx, const ICLArray< T > *array, const Strides &strides, unsigned int num_dimensions, const Window &window)
Add the passed 1D array's parameters to the object's kernel's arguments starting from the index idx.
void add_1D_tensor_argument (unsigned int &idx, const ICLTensor *tensor, const Window &window)
Add the passed 1D tensor's parameters to the object's kernel's arguments starting from the index idx.
void add_1D_tensor_argument_if (bool cond, unsigned int &idx, const ICLTensor *tensor, const Window &window)
Add the passed 1D tensor's parameters to the object's kernel's arguments starting from the index idx if the condition is true.
void add_2D_tensor_argument (unsigned int &idx, const ICLTensor *tensor, const Window &window)
Add the passed 2D tensor's parameters to the object's kernel's arguments starting from the index idx.
void add_2D_tensor_argument_if (bool cond, unsigned int &idx, const ICLTensor *tensor, const Window &window)
Add the passed 2D tensor's parameters to the object's kernel's arguments starting from the index idx if the condition is true.
void add_3D_tensor_argument (unsigned int &idx, const ICLTensor *tensor, const Window &window)
Add the passed 3D tensor's parameters to the object's kernel's arguments starting from the index idx.
void add_4D_tensor_argument (unsigned int &idx, const ICLTensor *tensor, const Window &window)
Add the passed 4D tensor's parameters to the object's kernel's arguments starting from the index idx.
virtual void run_op (ITensorPack &tensors, const Window &window, cl::CommandQueue &queue)
Enqueue the OpenCL kernel to process the given window on the passed OpenCL command queue.
template<typename T >
void add_argument (unsigned int &idx, T value)
Add the passed parameters to the object's kernel's arguments starting from the index idx.
void set_lws_hint (const cl::NDRange &lws_hint)
Set the Local-Workgroup-Size hint.
cl::NDRange lws_hint () const
Return the Local-Workgroup-Size hint.
void set_wbsm_hint (const cl_int &wbsm_hint)
Set the workgroup batch size modifier hint.
cl_int wbsm_hint () const
Return the workgroup batch size modifier hint.
const std::string & config_id () const
Get the configuration ID.
void set_target (GPUTarget target)
Set the targeted GPU architecture.
void set_target (cl::Device &device)
Set the targeted GPU architecture according to the CL device.
GPUTarget get_target () const
Get the targeted GPU architecture.
size_t get_max_workgroup_size ()
Get the maximum workgroup size for the device the CLKernelLibrary uses.
template<unsigned int dimension_size>
void add_tensor_argument (unsigned &idx, const ICLTensor *tensor, const Window &window)
template<typename T , unsigned int dimension_size>
void add_array_argument (unsigned &idx, const ICLArray< T > *array, const Strides &strides, unsigned int num_dimensions, const Window &window)
Add the passed array's parameters to the object's kernel's arguments starting from the index idx.
Public Member Functions inherited from IKernel
IKernel ()
Constructor.
virtual ~IKernel ()=default
Destructor.
virtual bool is_parallelisable () const
Indicates whether or not the kernel is parallelisable.
virtual BorderSize border_size () const
The size of the border for that kernel.
const Window & window () const
The maximum window the kernel can be executed on.
bool is_window_configured () const
Function to check if the embedded window of this kernel has been configured.
Static Public Member Functions
static Status validate (const ITensorInfo *mtx_b, const ITensorInfo *vector_sum_col, const GEMMLowpReductionKernelInfo &info)
Static function to check if given info will lead to a valid configuration of CLGEMMLowpMatrixBReductionKernel.
Static Public Member Functions inherited from ICLKernel
static constexpr unsigned int num_arguments_per_1D_array ()
Returns the number of arguments enqueued per 1D array object.
static constexpr unsigned int num_arguments_per_1D_tensor ()
Returns the number of arguments enqueued per 1D tensor object.
static constexpr unsigned int num_arguments_per_2D_tensor ()
Returns the number of arguments enqueued per 2D tensor object.
static constexpr unsigned int num_arguments_per_3D_tensor ()
Returns the number of arguments enqueued per 3D tensor object.
static constexpr unsigned int num_arguments_per_4D_tensor ()
Returns the number of arguments enqueued per 4D tensor object.
static cl::NDRange gws_from_window (const Window &window)
Get the global work size given an execution window.
Detailed Description
OpenCL kernel used to compute the row-vectors of sums of all the entries in each column of Matrix B.
Note
This stage is needed to handle the offset of matrix product https://github.com/google/gemmlowp/blob/master/doc/low-precision.md
Definition at line 132 of file CLGEMMLowpReductionKernel.h.
Member Function Documentation
configure() [1/2]
void configure (const ICLTensor * mtx_b, ICLTensor * vector_sum_col, const GEMMLowpReductionKernelInfo & info) override virtual
Initialise the kernel's input and output.
Parameters
[in] mtx_b Input tensor. Data type supported: Data type supported: QASYMM8/QASYMM8_SIGNED/QSYMM8/QSYMM8_PER_CHANNEL.
[out] vector_sum_col Output row-vector of sums of all the entries in each column of mtx_b. Data type supported: S32
[in] info Kernel metadata:
k Number of matrix columns/rows depending on the type of reduction.
is_reshaped True if the matrix has been reshaped.
scalar Scalar value to multiply each reduced column/row by.
mul_byscalar True if each reduced column/row must be multiplied by a scalar value.
Implements ICLGEMMLowpReductionKernel.
Definition at line 150 of file CLGEMMLowpReductionKernel.cpp.
 {
     configure(CLKernelLibrary::get().get_compile_context(), mtx_b, vector_sum_col, info);
 }
References CLKernelLibrary::get(), and arm_compute::test::validation::info.
configure() [2/2]
void configure (const CLCompileContext & compile_context, const ICLTensor * mtx_b, ICLTensor * vector_sum_col, const GEMMLowpReductionKernelInfo & info) override virtual
Initialise the kernel's input and output.
Parameters
[in] compile_context The compile context to be used.
[in] mtx_b Input tensor. Data type supported: Data type supported: QASYMM8/QASYMM8_SIGNED/QSYMM8/QSYMM8_PER_CHANNEL.
[out] vector_sum_col Output row-vector of sums of all the entries in each column of mtx_b. Data type supported: S32
[in] info Kernel metadata:
k Number of matrix columns/rows depending on the type of reduction.
is_reshaped True if the matrix has been reshaped.
scalar Scalar value to multiply each reduced column/row by.
mul_byscalar True if each reduced column/row must be multiplied by a scalar value.
Implements ICLGEMMLowpReductionKernel.
Definition at line 155 of file CLGEMMLowpReductionKernel.cpp.
 {
     ARM_COMPUTE_ERROR_ON_NULLPTR(mtx_b, vector_sum_col);
     ARM_COMPUTE_ERROR_THROW_ON(validate_arguments_matrix_b_reduction(mtx_b->info(), vector_sum_col->info()));
     _input  = mtx_b;
     _output = vector_sum_col;
     // Output auto initialization if not yet initialized
     auto_init_if_empty(*_output->info(), TensorShape(mtx_b->info()->dimension(0)), 1, DataType::S32);
     auto padding_info = get_padding_info({ mtx_b, vector_sum_col });
     const unsigned int num_elems_processed_per_iteration = adjust_vec_size(16, mtx_b->info()->dimension(0));
     // Set the arguments to pass at compile time
     CLBuildOptions build_opts;
     build_opts.add_option("-DVEC_SIZE=" + support::cpp11::to_string(num_elems_processed_per_iteration));
     build_opts.add_option("-DVEC_SIZE_LEFTOVER=" + support::cpp11::to_string(mtx_b->info()->dimension(0) % num_elems_processed_per_iteration));
     build_opts.add_option("-DCOLS_B=" + support::cpp11::to_string(mtx_b->info()->dimension(0)));
     build_opts.add_option("-DROWS_B=" + support::cpp11::to_string(mtx_b->info()->dimension(1)));
     build_opts.add_option("-DDATA_TYPE=" + get_cl_type_from_data_type(mtx_b->info()->data_type()));
     build_opts.add_option("-DACC_DATA_TYPE=" + get_cl_dot8_acc_type_from_data_type(mtx_b->info()->data_type()));
     build_opts.add_option_if(info.mul_by_scalar, "-DSCALAR=" + support::cpp11::to_string(info.scalar));
     // Create kernel
     _kernel = create_kernel(compile_context, "gemmlowp_matrix_b_reduction", build_opts.options());
     // Configure kernel window
     Window win = calculate_max_window(*_output->info(), Steps(num_elems_processed_per_iteration));
     ICLKernel::configure_internal(win);
     ARM_COMPUTE_ERROR_ON(has_padding_changed(padding_info));
 }
References CLBuildOptions::add_option(), arm_compute::adjust_vec_size(), ARM_COMPUTE_ERROR_ON, ARM_COMPUTE_ERROR_ON_NULLPTR, ARM_COMPUTE_ERROR_THROW_ON, arm_compute::auto_init_if_empty(), arm_compute::calculate_max_window(), arm_compute::create_kernel(), ITensorInfo::data_type(), ITensorInfo::dimension(), arm_compute::get_cl_dot8_acc_type_from_data_type(), arm_compute::get_cl_type_from_data_type(), arm_compute::get_padding_info(), arm_compute::has_padding_changed(), ITensor::info(), arm_compute::test::validation::info, num_elems_processed_per_iteration, arm_compute::S32, and arm_compute::support::cpp11::to_string().
run()
void run (const Window & window, cl::CommandQueue & queue) override virtual
Enqueue the OpenCL kernel to process the given window on the passed OpenCL command queue.
Note
The queue is not flushed by this method, and therefore the kernel will not have been executed by the time this method returns.
Parameters
[in] window Region on which to execute the kernel. (Must be a valid region of the window returned by window()).
[in,out] queue Command queue on which to enqueue the kernel.
Reimplemented from ICLKernel.
Definition at line 198 of file CLGEMMLowpReductionKernel.cpp.
 {
     ARM_COMPUTE_ERROR_ON_UNCONFIGURED_KERNEL(this);
     ARM_COMPUTE_ERROR_ON_INVALID_SUBWINDOW(ICLKernel::window(), window);
     Window collapsed = window.collapse_if_possible(IKernel::window(), Window::DimY);
     Window slice_out = collapsed.first_slice_window_2D();
     Window slice_in  = slice_out;
     slice_in.set(Window::DimY, Window::Dimension(0, 0, 0));
     slice_in.set(Window::DimZ, Window::Dimension(0, 0, 0));
     do
     {
         unsigned int idx = 0;
         add_3D_tensor_argument(idx, _input, slice_in);
         add_2D_tensor_argument(idx, _output, slice_out);
         enqueue(queue, *this, slice_out, lws_hint());
     }
     while(collapsed.slide_window_slice_2D(slice_out));
 }
References ICLKernel::add_2D_tensor_argument(), ICLKernel::add_3D_tensor_argument(), ARM_COMPUTE_ERROR_ON_INVALID_SUBWINDOW, ARM_COMPUTE_ERROR_ON_UNCONFIGURED_KERNEL, Window::collapse_if_possible(), Window::DimY, Window::DimZ, arm_compute::enqueue(), Window::first_slice_window_2D(), ICLKernel::lws_hint(), Window::set(), Window::slide_window_slice_2D(), and IKernel::window().
validate()
Status validate (const ITensorInfo * mtx_b, const ITensorInfo * vector_sum_col, const GEMMLowpReductionKernelInfo & info) static
Static function to check if given info will lead to a valid configuration of CLGEMMLowpMatrixBReductionKernel.
Parameters
[in] mtx_b Input tensor. Data type supported: Data type supported: QASYMM8/QASYMM8_SIGNED/QSYMM8/QSYMM8_PER_CHANNEL.
[in] vector_sum_col Output row-vector of sums of all the entries in each column of mtx_b. Data type supported: S32
[in] info Kernel metadata:
k Number of matrix columns/rows depending on the type of reduction.
is_reshaped True if the matrix has been reshaped.
scalar Scalar value to multiply each reduced column/row by.
mul_byscalar True if each reduced column/row must be multiplied by a scalar value.
Returns
a status
Definition at line 190 of file CLGEMMLowpReductionKernel.cpp.
 {
     ARM_COMPUTE_UNUSED(info);
     ARM_COMPUTE_RETURN_ON_ERROR(validate_arguments_matrix_b_reduction(mtx_b, vector_sum_col));
     return Status{};
 }
References ARM_COMPUTE_RETURN_ON_ERROR, ARM_COMPUTE_UNUSED, and arm_compute::test::validation::info.
Referenced by CLGEMMLowpMatrixMultiplyCore::validate().
The documentation for this class was generated from the following files:
src/core/CL/kernels/CLGEMMLowpReductionKernel.h
src/core/CL/kernels/CLGEMMLowpReductionKernel.cpp