Compute Library: IQueue Class Reference
IQueue Class Reference abstract
Base class specifying the queue interface.
#include <IQueue.h>
Public Member Functions
IQueue (IContext *ctx)
Explict Operator Constructor.
virtual ~IQueue ()
Destructor.
bool is_valid () const
Checks if a queue is valid.
virtual StatusCode finish ()=0
Additional Inherited Members
Data Fields inherited from AclQueue_
arm_compute::detail::Header header { arm_compute::detail::ObjectType::Queue, nullptr }
Detailed Description
Base class specifying the queue interface.
Definition at line 41 of file IQueue.h.
Constructor & Destructor Documentation
IQueue()
IQueue (IContext * ctx) inline explicit
Explict Operator Constructor.
Parameters
[in] ctx Context to be used by the operator
Definition at line 48 of file IQueue.h.
     {
         this->header.ctx = ctx;
         this->header.ctx->inc_ref();
     }
References Header::ctx, AclQueue_::header, and IContext::inc_ref().
~IQueue()
virtual ~IQueue () inline virtual
Destructor.
Definition at line 54 of file IQueue.h.
     {
         this->header.ctx->dec_ref();
         this->header.type = detail::ObjectType::Invalid;
     };
References Header::ctx, IContext::dec_ref(), AclQueue_::header, arm_compute::detail::Invalid, and Header::type.
Member Function Documentation
finish()
virtual StatusCode finish () pure virtual
Implemented in ClQueue, and CpuQueue.
is_valid()
bool is_valid () const inline
Checks if a queue is valid.
Returns
True if successful otherwise false
Definition at line 63 of file IQueue.h.
     {
         return this->header.type == detail::ObjectType::Queue;
     };
References AclQueue_::header, arm_compute::detail::Queue, and Header::type.
Referenced by arm_compute::detail::validate_internal_queue().
The documentation for this class was generated from the following file:
src/common/IQueue.h