Compute Library: NEGEMMAssemblyDispatch Class Reference
NEGEMMAssemblyDispatch Class Reference
Assembly kernel glue.
#include <NEGEMMAssemblyDispatch.h>
Data Structures
class IFallback
Public Member Functions
NEGEMMAssemblyDispatch (std::shared_ptr< IMemoryManager > memory_manager=nullptr, IWeightsManager *weights_manager=nullptr)
Constructor.
NEGEMMAssemblyDispatch (const NEGEMMAssemblyDispatch &)=delete
Prevent instances of this class from being copy constructed.
NEGEMMAssemblyDispatch & operator= (const NEGEMMAssemblyDispatch &)=delete
Prevent instances of this class from being copied.
NEGEMMAssemblyDispatch (NEGEMMAssemblyDispatch &&)=default
NEGEMMAssemblyDispatch & operator= (NEGEMMAssemblyDispatch &&)=default
~NEGEMMAssemblyDispatch ()=default
void configure (const ITensor *a, const ITensor *b, const ITensor *c, ITensor *d, const AsmGemmInfo &info)
If supported create a Compute Library function else fallback to the arm_gemm function.
bool is_configured () const
Was the function successfully configured ?
void prepare () override
Prepare the function for executing.
void run () override
Run the kernels contained in the function.
Public Member Functions inherited from IFunction
virtual ~IFunction ()=default
Destructor.
Static Public Member Functions
static Status validate (const ITensorInfo *a, const ITensorInfo *b, const ITensorInfo *c, const ITensorInfo *d, const AsmGemmInfo &info)
Indicates whether or not this function can be used to process the given parameters.
static bool is_activation_supported (const ActivationLayerInfo &activation)
Checks if activation is supported by the gemm assembly dispatcher.
Detailed Description
Assembly kernel glue.
Definition at line 58 of file NEGEMMAssemblyDispatch.h.
Constructor & Destructor Documentation
NEGEMMAssemblyDispatch() [1/3]
NEGEMMAssemblyDispatch (std::shared_ptr< IMemoryManager > memory_manager = nullptr, IWeightsManager * weights_manager = nullptr)
Constructor.
Definition at line 745 of file NEGEMMAssemblyDispatch.cpp.
     : _arm_gemm(nullptr), _memory_group(std::move(memory_manager)), _weights_manager(weights_manager)
 {
 }
NEGEMMAssemblyDispatch() [2/3]
NEGEMMAssemblyDispatch (const NEGEMMAssemblyDispatch &) delete
Prevent instances of this class from being copy constructed.
NEGEMMAssemblyDispatch() [3/3]
NEGEMMAssemblyDispatch (NEGEMMAssemblyDispatch &&) default
~NEGEMMAssemblyDispatch()
~NEGEMMAssemblyDispatch () default
Member Function Documentation
configure()
void configure (const ITensor * a, const ITensor * b, const ITensor * c, ITensor * d, const AsmGemmInfo & info)
If supported create a Compute Library function else fallback to the arm_gemm function.
Parameters
[in] a Input tensor (Matrix A)
[in] b Input tensor (Matrix B)
[in] c Input tensor (Matrix C) used to pass the bias for quantized calculations
[out] d Output tensor to store the result of matrix multiplication. Data type supported: same as input0.
[in] info GEMM meta-data
Definition at line 787 of file NEGEMMAssemblyDispatch.cpp.
 {
     ARM_COMPUTE_ERROR_ON_NULLPTR(a, b, d);
     arm_gemm::Activation act = map_to_arm_gemm_activation(info.activation_info);
     //If we don't support a combination of data types, silently return: it is the caller's responsibility to check if configure() was successful via is_configured()
     if(!NEGEMMAssemblyDispatch::validate(a->info(), b->info(), c != nullptr ? c->info() : nullptr, d->info(), info))
     {
         return;
     }
     switch(a->info()->data_type())
     {
         case DataType::F32:
             create_arm_gemm<float, float>(_arm_gemm, _memory_group, a, b, c, d, act, info, _weights_manager);
             break;
 #ifdef __aarch64__
         case DataType::U8:
         case DataType::QASYMM8:
             if(d->info()->data_type() == DataType::S32)
             {
                 create_arm_gemm<uint8_t, uint32_t>(_arm_gemm, _memory_group, a, b, c, d, act, info, _weights_manager);
             }
             else
             {
                 create_arm_gemm_quant<uint8_t, uint8_t>(_arm_gemm, _memory_group, a, b, c, d, act, info, _weights_manager);
             }
             break;
         case DataType::S8:
         case DataType::QASYMM8_SIGNED:
             if(d->info()->data_type() == DataType::S32)
             {
                 create_arm_gemm<int8_t, int32_t>(_arm_gemm, _memory_group, a, b, c, d, act, info, _weights_manager);
             }
             else
             {
                 create_arm_gemm_quant<int8_t, int8_t>(_arm_gemm, _memory_group, a, b, c, d, act, info, _weights_manager);
             }
             break;
 #endif /* __aarch64__ */
 #if defined(__ARM_FEATURE_BF16_VECTOR_ARITHMETIC) || defined(ARM_COMPUTE_FORCE_BF16)
         case DataType::BFLOAT16:
             create_arm_gemm<bfloat16, float>(_arm_gemm, _memory_group, a, b, c, d, act, info, _weights_manager);
             break;
 #endif /* defined(__ARM_FEATURE_BF16_VECTOR_ARITHMETIC) || defined(ARM_COMPUTE_FORCE_BF16) */
 #ifdef __ARM_FEATURE_FP16_VECTOR_ARITHMETIC
         case DataType::F16:
             create_arm_gemm<float16_t, float16_t>(_arm_gemm, _memory_group, a, b, c, d, act, info, _weights_manager);
             break;
 #endif /* __ARM_FEATURE_FP16_VECTOR_ARITHMETIC */
         default:
             break;
     }
 }
References ARM_COMPUTE_ERROR_ON_NULLPTR, arm_compute::test::validation::b, arm_compute::BFLOAT16, ITensorInfo::data_type(), arm_compute::F16, arm_compute::F32, ITensor::info(), arm_compute::test::validation::info, arm_compute::QASYMM8, arm_compute::QASYMM8_SIGNED, arm_compute::S32, arm_compute::S8, arm_compute::U8, and NEGEMMAssemblyDispatch::validate().
is_activation_supported()
bool is_activation_supported (const ActivationLayerInfo & activation) static
Checks if activation is supported by the gemm assembly dispatcher.
Parameters
[in] activation Activation to check
Returns
True if activation is supported else false
Definition at line 781 of file NEGEMMAssemblyDispatch.cpp.
 {
     arm_gemm::Activation act = map_to_arm_gemm_activation(activation);
     return act.type != arm_gemm::Activation::Type::None;
 }
References tf_frozen_model_extractor::None.
Referenced by NEGEMM::configure(), and NEGEMMLowpMatrixMultiplyCore::configure().
is_configured()
bool is_configured () const
Was the function successfully configured ?
Returns
True if the function is configured and ready to run
Definition at line 848 of file NEGEMMAssemblyDispatch.cpp.
 {
     return _arm_gemm != nullptr && _arm_gemm->is_configured();
 }
operator=() [1/2]
NEGEMMAssemblyDispatch& operator= (const NEGEMMAssemblyDispatch &) delete
Prevent instances of this class from being copied.
operator=() [2/2]
NEGEMMAssemblyDispatch& operator= (NEGEMMAssemblyDispatch &&) default
prepare()
void prepare () override virtual
Prepare the function for executing.
Any one off pre-processing step required by the function is handled here
Note
Prepare stage might not need all the function's buffers' backing memory to be available in order to execute
Reimplemented from IFunction.
Definition at line 842 of file NEGEMMAssemblyDispatch.cpp.
 {
     ARM_COMPUTE_ERROR_ON(_arm_gemm == nullptr);
     _arm_gemm->prepare();
 }
References ARM_COMPUTE_ERROR_ON.
run()
void run () override virtual
Run the kernels contained in the function.
For CPU kernels:
Multi-threading is used for the kernels which are parallelisable.
By default std::thread::hardware_concurrency() threads are used.
Note
CPPScheduler::set_num_threads() can be used to manually set the number of threads
For OpenCL kernels:
All the kernels are enqueued on the queue associated with CLScheduler.
The queue is then flushed.
Note
The function will not block until the kernels are executed. It is the user's responsibility to wait.
Will call prepare() on first run if hasn't been done
Implements IFunction.
Definition at line 853 of file NEGEMMAssemblyDispatch.cpp.
 {
     MemoryGroupResourceScope scope_mg(_memory_group);
     ARM_COMPUTE_ERROR_ON(_arm_gemm == nullptr);
     _arm_gemm->run();
 }
References ARM_COMPUTE_ERROR_ON.
validate()
Status validate (const ITensorInfo * a, const ITensorInfo * b, const ITensorInfo * c, const ITensorInfo * d, const AsmGemmInfo & info) static
Indicates whether or not this function can be used to process the given parameters.
Parameters
[in] a Input tensor info (Matrix A)
[in] b Input tensor info (Matrix B)
[in] c Input tensor info (Matrix C) used to pass the bias for quantized calculations
[in] d Output tensor to store the result of matrix multiplication. Data type supported: same as input0.
[in] info GEMM meta-data
Returns
a status.
Definition at line 750 of file NEGEMMAssemblyDispatch.cpp.
 {
     ARM_COMPUTE_UNUSED(c, info);
     ARM_COMPUTE_RETURN_ERROR_ON_NULLPTR(a, b, d);
     ARM_COMPUTE_RETURN_ERROR_ON_CPU_F16_UNSUPPORTED(a);
     ARM_COMPUTE_RETURN_ERROR_ON_CPU_BF16_UNSUPPORTED(a);
 #ifndef __aarch64__
     ARM_COMPUTE_RETURN_ERROR_ON_MSG(a->element_size() == 1, "8bit integer types only supported for aarch64");
 #endif /* __aarch64__ */
     ARM_COMPUTE_RETURN_ERROR_ON_DATA_TYPE_CHANNEL_NOT_IN(a, 1, DataType::U8, DataType::QASYMM8, DataType::QASYMM8_SIGNED, DataType::S8,
                                                          DataType::BFLOAT16, DataType::F16, DataType::F32);
     ARM_COMPUTE_RETURN_ERROR_ON_DATA_TYPE_CHANNEL_NOT_IN(b, 1, DataType::U8, DataType::QASYMM8, DataType::QASYMM8_SIGNED, DataType::QSYMM8_PER_CHANNEL, DataType::S8,
                                                          DataType::BFLOAT16, DataType::F16, DataType::F32);
     if(is_data_type_quantized_per_channel(b->data_type()))
     {
         ARM_COMPUTE_RETURN_ERROR_ON_DATA_TYPE_CHANNEL_NOT_IN(a, 1, DataType::QASYMM8_SIGNED, DataType::S8);
     }
     else
     {
         ARM_COMPUTE_RETURN_ERROR_ON_MISMATCHING_DATA_TYPES(a, b);
     }
     ARM_COMPUTE_RETURN_ERROR_ON_MSG(a->data_type() == DataType::F32 && d->data_type() != DataType::F32, "Only F32 output supported for F32 input");
     ARM_COMPUTE_RETURN_ERROR_ON_MSG(a->data_type() == DataType::F16 && d->data_type() != DataType::F16, "Only F16 output supported for F16 input");
     ARM_COMPUTE_RETURN_ERROR_ON_MSG(a->data_type() == DataType::BFLOAT16 && d->data_type() != DataType::F32, "Only F32 output supported for BFLOAT16 input");
     ARM_COMPUTE_RETURN_ERROR_ON_MSG(a->data_type() == DataType::U8 && d->data_type() != DataType::U32, "Only U32 output supported for U8 input");
     ARM_COMPUTE_RETURN_ERROR_ON_MSG(a->data_type() == DataType::S8 && d->data_type() != DataType::S32, "Only S32 output supported for S8 input");
     ARM_COMPUTE_RETURN_ERROR_ON_MSG(a->data_type() == DataType::QASYMM8 && d->data_type() != DataType::QASYMM8, "Only QASYMM8 output supported for QASYMM8 input");
     return Status{};
 }
References ARM_COMPUTE_RETURN_ERROR_ON_CPU_BF16_UNSUPPORTED, ARM_COMPUTE_RETURN_ERROR_ON_CPU_F16_UNSUPPORTED, ARM_COMPUTE_RETURN_ERROR_ON_DATA_TYPE_CHANNEL_NOT_IN, ARM_COMPUTE_RETURN_ERROR_ON_MISMATCHING_DATA_TYPES, ARM_COMPUTE_RETURN_ERROR_ON_MSG, ARM_COMPUTE_RETURN_ERROR_ON_NULLPTR, ARM_COMPUTE_UNUSED, arm_compute::test::validation::b, arm_compute::BFLOAT16, ITensorInfo::data_type(), ITensorInfo::element_size(), arm_compute::F16, arm_compute::F32, arm_compute::test::validation::info, arm_compute::is_data_type_quantized_per_channel(), arm_compute::QASYMM8, arm_compute::QASYMM8_SIGNED, arm_compute::QSYMM8_PER_CHANNEL, arm_compute::S32, arm_compute::S8, arm_compute::U32, and arm_compute::U8.
Referenced by NEGEMMAssemblyDispatch::configure(), NEGEMM::configure(), NEGEMMConv2d::validate(), NEGEMM::validate(), and NEGEMMLowpMatrixMultiplyCore::validate().
The documentation for this class was generated from the following files:
src/runtime/NEON/functions/NEGEMMAssemblyDispatch.h
src/runtime/NEON/functions/NEGEMMAssemblyDispatch.cpp