Compute Library: CLMaxUnpoolingLayerKernel Class Reference
CLMaxUnpoolingLayerKernel Class Reference
Interface for the pooling layer kernel.
#include <CLMaxUnpoolingLayerKernel.h>
Public Member Functions
CLMaxUnpoolingLayerKernel ()
Default constructor.
CLMaxUnpoolingLayerKernel (const CLMaxUnpoolingLayerKernel &)=delete
Prevent instances of this class from being copied (As this class contains pointers)
CLMaxUnpoolingLayerKernel & operator= (const CLMaxUnpoolingLayerKernel &)=delete
Prevent instances of this class from being copied (As this class contains pointers)
CLMaxUnpoolingLayerKernel (CLMaxUnpoolingLayerKernel &&)=default
Allow instances of this class to be moved.
CLMaxUnpoolingLayerKernel & operator= (CLMaxUnpoolingLayerKernel &&)=default
Allow instances of this class to be moved.
~CLMaxUnpoolingLayerKernel ()=default
Default destructor.
void configure (const CLCompileContext &compile_context, const ICLTensor *input, const ICLTensor *indices, ICLTensor *output, const PoolingLayerInfo &pool_info)
Set the input and output tensors.
void run (const Window &window, cl::CommandQueue &queue) override
Enqueue the OpenCL kernel to process the given window on the passed OpenCL command queue.
Public Member Functions inherited from ICLKernel
ICLKernel ()
Constructor.
cl::Kernel & kernel ()
Returns a reference to the OpenCL kernel of this object.
template<typename T >
void add_1D_array_argument (unsigned int &idx, const ICLArray< T > *array, const Strides &strides, unsigned int num_dimensions, const Window &window)
Add the passed 1D array's parameters to the object's kernel's arguments starting from the index idx.
void add_1D_tensor_argument (unsigned int &idx, const ICLTensor *tensor, const Window &window)
Add the passed 1D tensor's parameters to the object's kernel's arguments starting from the index idx.
void add_1D_tensor_argument_if (bool cond, unsigned int &idx, const ICLTensor *tensor, const Window &window)
Add the passed 1D tensor's parameters to the object's kernel's arguments starting from the index idx if the condition is true.
void add_2D_tensor_argument (unsigned int &idx, const ICLTensor *tensor, const Window &window)
Add the passed 2D tensor's parameters to the object's kernel's arguments starting from the index idx.
void add_2D_tensor_argument_if (bool cond, unsigned int &idx, const ICLTensor *tensor, const Window &window)
Add the passed 2D tensor's parameters to the object's kernel's arguments starting from the index idx if the condition is true.
void add_3D_tensor_argument (unsigned int &idx, const ICLTensor *tensor, const Window &window)
Add the passed 3D tensor's parameters to the object's kernel's arguments starting from the index idx.
void add_4D_tensor_argument (unsigned int &idx, const ICLTensor *tensor, const Window &window)
Add the passed 4D tensor's parameters to the object's kernel's arguments starting from the index idx.
virtual void run_op (ITensorPack &tensors, const Window &window, cl::CommandQueue &queue)
Enqueue the OpenCL kernel to process the given window on the passed OpenCL command queue.
template<typename T >
void add_argument (unsigned int &idx, T value)
Add the passed parameters to the object's kernel's arguments starting from the index idx.
void set_lws_hint (const cl::NDRange &lws_hint)
Set the Local-Workgroup-Size hint.
cl::NDRange lws_hint () const
Return the Local-Workgroup-Size hint.
void set_wbsm_hint (const cl_int &wbsm_hint)
Set the workgroup batch size modifier hint.
cl_int wbsm_hint () const
Return the workgroup batch size modifier hint.
const std::string & config_id () const
Get the configuration ID.
void set_target (GPUTarget target)
Set the targeted GPU architecture.
void set_target (cl::Device &device)
Set the targeted GPU architecture according to the CL device.
GPUTarget get_target () const
Get the targeted GPU architecture.
size_t get_max_workgroup_size ()
Get the maximum workgroup size for the device the CLKernelLibrary uses.
template<unsigned int dimension_size>
void add_tensor_argument (unsigned &idx, const ICLTensor *tensor, const Window &window)
template<typename T , unsigned int dimension_size>
void add_array_argument (unsigned &idx, const ICLArray< T > *array, const Strides &strides, unsigned int num_dimensions, const Window &window)
Add the passed array's parameters to the object's kernel's arguments starting from the index idx.
Public Member Functions inherited from IKernel
IKernel ()
Constructor.
virtual ~IKernel ()=default
Destructor.
virtual bool is_parallelisable () const
Indicates whether or not the kernel is parallelisable.
virtual BorderSize border_size () const
The size of the border for that kernel.
const Window & window () const
The maximum window the kernel can be executed on.
bool is_window_configured () const
Function to check if the embedded window of this kernel has been configured.
Static Public Member Functions
static Status validate (const ITensorInfo *input, const ITensorInfo *indices, const ITensorInfo *output, const PoolingLayerInfo &pool_info)
Static function to check if given info will lead to a valid configuration of CLMaxUnpoolingLayerKernel.
Static Public Member Functions inherited from ICLKernel
static constexpr unsigned int num_arguments_per_1D_array ()
Returns the number of arguments enqueued per 1D array object.
static constexpr unsigned int num_arguments_per_1D_tensor ()
Returns the number of arguments enqueued per 1D tensor object.
static constexpr unsigned int num_arguments_per_2D_tensor ()
Returns the number of arguments enqueued per 2D tensor object.
static constexpr unsigned int num_arguments_per_3D_tensor ()
Returns the number of arguments enqueued per 3D tensor object.
static constexpr unsigned int num_arguments_per_4D_tensor ()
Returns the number of arguments enqueued per 4D tensor object.
static cl::NDRange gws_from_window (const Window &window)
Get the global work size given an execution window.
Detailed Description
Interface for the pooling layer kernel.
Definition at line 34 of file CLMaxUnpoolingLayerKernel.h.
Constructor & Destructor Documentation
CLMaxUnpoolingLayerKernel() [1/3]
CLMaxUnpoolingLayerKernel ()
Default constructor.
Definition at line 74 of file CLMaxUnpoolingLayerKernel.cpp.
     : _input(nullptr), _output(nullptr), _indices(nullptr)
 {
 }
CLMaxUnpoolingLayerKernel() [2/3]
CLMaxUnpoolingLayerKernel (const CLMaxUnpoolingLayerKernel &) delete
Prevent instances of this class from being copied (As this class contains pointers)
CLMaxUnpoolingLayerKernel() [3/3]
CLMaxUnpoolingLayerKernel (CLMaxUnpoolingLayerKernel &&) default
Allow instances of this class to be moved.
~CLMaxUnpoolingLayerKernel()
~CLMaxUnpoolingLayerKernel () default
Default destructor.
Member Function Documentation
configure()
void configure (const CLCompileContext & compile_context, const ICLTensor * input, const ICLTensor * indices, ICLTensor * output, const PoolingLayerInfo & pool_info)
Set the input and output tensors.
Note
Output shape must be equal to the shape of the original input to pool.
Parameters
[in] compile_context The compile context to be used.
[in] input Source tensor. Data types supported: QASYMM8/QASYMM8_SIGNED/F16/F32.
[in] indices Tensor containing the offset to store the input elements in the output tensor. opencl::ClPooling with indices should precede this function in order to properly reconstruct the output tensor. The tensor shape of this tensor has to be equal to the input tensor shape. Data type supported: U32.
[out] output Destination tensor. Data types supported: Same as input.
[in] pool_info Contains pooling operation information described in PoolingLayerInfo.
Definition at line 79 of file CLMaxUnpoolingLayerKernel.cpp.
 {
     ARM_COMPUTE_ERROR_ON_NULLPTR(input, output);
     ARM_COMPUTE_ERROR_THROW_ON(validate_arguments(input->info(), output->info(), pool_info, indices->info()));
     auto padding_info = get_padding_info({ input, indices, output });
     _input   = input;
     _output  = output;
     _indices = indices;
     // Create build options
     CLBuildOptions build_opts;
     build_opts.add_option("-DDATA_TYPE=" + get_cl_unsigned_type_from_element_size(input->info()->element_size()));
     build_opts.add_option("-DWIDTH_DST=" + support::cpp11::to_string(output->info()->dimension(0)));
     build_opts.add_option("-DHEIGHT_DST=" + support::cpp11::to_string(output->info()->dimension(1)));
     build_opts.add_option("-DDEPTH_DST=" + support::cpp11::to_string(output->info()->dimension(2)));
     const std::string kernel_name("max_unpooling_layer_2");
     // Create kernel
     _kernel = create_kernel(compile_context, kernel_name, build_opts.options());
     const TensorShape output_shape = compute_unpool_shape(*input->info(), pool_info);
     auto_init_if_empty(*output->info(), input->info()->clone()->set_tensor_shape(output_shape));
     auto window = calculate_max_window(*input->info(), Steps());
     ICLKernel::configure_internal(window);
     // Set config_id for enabling LWS tuning
     _config_id = kernel_name;
     _config_id += lower_string(string_from_data_type(input->info()->data_type()));
     _config_id += "_";
     _config_id += support::cpp11::to_string(output->info()->dimension(0));
     _config_id += "_";
     _config_id += support::cpp11::to_string(output->info()->dimension(1));
     _config_id += "_";
     _config_id += support::cpp11::to_string(output->info()->dimension(2));
     _config_id += "_";
     _config_id += support::cpp11::to_string(output->info()->dimension(3));
     ARM_COMPUTE_ERROR_ON(has_padding_changed(padding_info));
 }
References CLBuildOptions::add_option(), ARM_COMPUTE_ERROR_ON, ARM_COMPUTE_ERROR_ON_NULLPTR, ARM_COMPUTE_ERROR_THROW_ON, arm_compute::auto_init_if_empty(), arm_compute::calculate_max_window(), arm_compute::misc::shape_calculator::compute_unpool_shape(), arm_compute::create_kernel(), ITensorInfo::dimension(), arm_compute::get_cl_unsigned_type_from_element_size(), arm_compute::get_padding_info(), arm_compute::has_padding_changed(), ITensor::info(), arm_compute::test::validation::input, kernel_name, arm_compute::lower_string(), CLBuildOptions::options(), arm_compute::test::validation::output_shape, arm_compute::string_from_data_type(), arm_compute::support::cpp11::to_string(), arm_compute::validate_arguments(), and IKernel::window().
operator=() [1/2]
CLMaxUnpoolingLayerKernel& operator= (const CLMaxUnpoolingLayerKernel &) delete
Prevent instances of this class from being copied (As this class contains pointers)
operator=() [2/2]
CLMaxUnpoolingLayerKernel& operator= (CLMaxUnpoolingLayerKernel &&) default
Allow instances of this class to be moved.
run()
void run (const Window & window, cl::CommandQueue & queue) override virtual
Enqueue the OpenCL kernel to process the given window on the passed OpenCL command queue.
Note
The queue is not flushed by this method, and therefore the kernel will not have been executed by the time this method returns.
Parameters
[in] window Region on which to execute the kernel. (Must be a valid region of the window returned by window()).
[in,out] queue Command queue on which to enqueue the kernel.
Reimplemented from ICLKernel.
Definition at line 128 of file CLMaxUnpoolingLayerKernel.cpp.
 {
     ARM_COMPUTE_ERROR_ON_UNCONFIGURED_KERNEL(this);
     ARM_COMPUTE_ERROR_ON_INVALID_SUBWINDOW(ICLKernel::window(), window);
     Window slice = window.first_slice_window_3D();
     do
     {
         unsigned int idx = 0;
         add_3D_tensor_argument(idx, _input, slice);
         add_3D_tensor_argument(idx, _output, slice);
         add_3D_tensor_argument(idx, _indices, slice);
         enqueue(queue, *this, slice, lws_hint());
     }
     while(window.slide_window_slice_3D(slice));
 }
References ICLKernel::add_3D_tensor_argument(), ARM_COMPUTE_ERROR_ON_INVALID_SUBWINDOW, ARM_COMPUTE_ERROR_ON_UNCONFIGURED_KERNEL, arm_compute::enqueue(), Window::first_slice_window_3D(), ICLKernel::lws_hint(), arm_compute::test::validation::reference::slice(), Window::slide_window_slice_3D(), and IKernel::window().
validate()
Status validate (const ITensorInfo * input, const ITensorInfo * indices, const ITensorInfo * output, const PoolingLayerInfo & pool_info) static
Static function to check if given info will lead to a valid configuration of CLMaxUnpoolingLayerKernel.
Parameters
[in] input Source tensor info. Data types supported: QASYMM8/QASYMM8_SIGNED/F16/F32.
[in] output Destination tensor info. Data types supported: Same as input.
[in] indices TensorInfo associated to the tensor containing the offset to store the input elements in the output tensor. opencl::ClPooling with indices should precede this function in order to properly reconstruct the output tensor. The tensor shape of this tensor has to be equal to the input tensor shape. Data type supported: U32.
[in] pool_info Contains pooling operation information described in PoolingLayerInfo.
Returns
a status
Definition at line 121 of file CLMaxUnpoolingLayerKernel.cpp.
 {
     ARM_COMPUTE_RETURN_ERROR_ON_NULLPTR(input, indices, output);
     ARM_COMPUTE_RETURN_ON_ERROR(validate_arguments(input, output, pool_info, indices));
     return Status{};
 }
References ARM_COMPUTE_RETURN_ERROR_ON_NULLPTR, ARM_COMPUTE_RETURN_ON_ERROR, arm_compute::test::validation::input, and arm_compute::validate_arguments().
Referenced by CLMaxUnpoolingLayer::validate().
The documentation for this class was generated from the following files:
src/core/CL/kernels/CLMaxUnpoolingLayerKernel.h
src/core/CL/kernels/CLMaxUnpoolingLayerKernel.cpp