Compute Library: NEInstanceNormalizationLayer Class Reference
NEInstanceNormalizationLayer Class Reference
Basic function to perform a Instance normalization.
#include <NEInstanceNormalizationLayer.h>
Public Member Functions
NEInstanceNormalizationLayer (std::shared_ptr< IMemoryManager > memory_manager=nullptr)
Constructor.
NEInstanceNormalizationLayer (const NEInstanceNormalizationLayer &)=delete
Prevent instances of this class from being copied (As this class contains pointers)
NEInstanceNormalizationLayer & operator= (const NEInstanceNormalizationLayer &)=delete
Prevent instances of this class from being copied (As this class contains pointers)
NEInstanceNormalizationLayer (NEInstanceNormalizationLayer &&)=delete
Prevent instances of this class from being moved (As this class contains non movable objects)
NEInstanceNormalizationLayer & operator= (NEInstanceNormalizationLayer &&)=delete
Prevent instances of this class from being moved (As this class contains non movable objects)
~NEInstanceNormalizationLayer ()
Default destructor.
void configure (ITensor *input, ITensor *output, float gamma=1.0f, float beta=0.0f, float epsilon=1e-12f)
Set the input and output tensors.
void run () override
Run the kernels contained in the function.
Public Member Functions inherited from IFunction
virtual ~IFunction ()=default
Destructor.
virtual void prepare ()
Prepare the function for executing.
Static Public Member Functions
static Status validate (const ITensorInfo *input, const ITensorInfo *output, float gamma=1.0f, float beta=0.0f, float epsilon=1e-12f)
Static function to check if given info will lead to a valid configuration of NEInstanceNormalizationLayer.
Detailed Description
Basic function to perform a Instance normalization.
This function runs the following kernels:
NEInstanceNormalizationLayerKernel
Definition at line 46 of file NEInstanceNormalizationLayer.h.
Constructor & Destructor Documentation
NEInstanceNormalizationLayer() [1/3]
NEInstanceNormalizationLayer (std::shared_ptr< IMemoryManager > memory_manager = nullptr)
Constructor.
Definition at line 35 of file NEInstanceNormalizationLayer.cpp.
     : _memory_group(std::move(memory_manager)), _normalization_kernel(), _is_nchw(false), _permute_input(), _permute_output(), _permuted_input(), _permuted_output()
 {
 }
NEInstanceNormalizationLayer() [2/3]
NEInstanceNormalizationLayer (const NEInstanceNormalizationLayer &) delete
Prevent instances of this class from being copied (As this class contains pointers)
NEInstanceNormalizationLayer() [3/3]
NEInstanceNormalizationLayer (NEInstanceNormalizationLayer &&) delete
Prevent instances of this class from being moved (As this class contains non movable objects)
~NEInstanceNormalizationLayer()
~NEInstanceNormalizationLayer () default
Default destructor.
Member Function Documentation
configure()
void configure (ITensor * input, ITensor * output, float gamma = 1.0f, float beta = 0.0f, float epsilon = 1e-12f)
Set the input and output tensors.
Valid data layouts:
NHWC
NCHW
Valid data type configurations:
src dst
F16 F16
F32 F32
Parameters
[in,out] input Source tensor. In case of output tensor = nullptr this tensor will store the result of the normalization. Data types supported: F16/F32. Data layout supported: NHWC, NCHW
[out] output Destination tensor. Data types and data layouts supported: same as input.
[in] gamma (Optional) The scale scalar value applied to the normalized tensor. Defaults to 1.0
[in] beta (Optional) The offset scalar value applied to the normalized tensor. Defaults to 0.0
[in] epsilon (Optional) Lower bound value for the normalization. Defaults to 1e-12
Definition at line 40 of file NEInstanceNormalizationLayer.cpp.
 {
     const DataLayout data_layout       = input->info()->data_layout();
     const auto       kernel_descriptor = InstanceNormalizationLayerKernelInfo{ gamma, beta, epsilon, true };
     // Configure Kernels
     _is_nchw = data_layout == DataLayout::NCHW;
     _normalization_kernel = std::make_unique<NEInstanceNormalizationLayerKernel>();
     if(!_is_nchw)
     {
         _memory_group.manage(&_permuted_input);
         _memory_group.manage(&_permuted_output);
         // Configure the function to transform the input tensor from NHWC -> NCHW
         _permute_input.configure(input, &_permuted_input, PermutationVector(1U, 2U, 0U));
         _permuted_input.info()->set_data_layout(DataLayout::NCHW);
         _normalization_kernel->configure(&_permuted_input, &_permuted_output, kernel_descriptor);
         _permuted_output.info()->set_data_layout(DataLayout::NCHW);
         _permute_output.configure(&_permuted_output, output != nullptr ? output : input, PermutationVector(2U, 0U, 1U));
         _permuted_input.allocator()->allocate();
         _permuted_output.allocator()->allocate();
     }
     else
     {
         _normalization_kernel->configure(input, output, kernel_descriptor);
     }
 }
References TensorAllocator::allocate(), Tensor::allocator(), NEPermute::configure(), arm_compute::test::validation::data_layout, arm_compute::quantization::epsilon, Tensor::info(), arm_compute::test::validation::input, MemoryGroup::manage(), arm_compute::NCHW, ITensorInfo::set_data_layout(), and arm_compute::U.
operator=() [1/2]
NEInstanceNormalizationLayer& operator= (const NEInstanceNormalizationLayer &) delete
Prevent instances of this class from being copied (As this class contains pointers)
operator=() [2/2]
NEInstanceNormalizationLayer& operator= (NEInstanceNormalizationLayer &&) delete
Prevent instances of this class from being moved (As this class contains non movable objects)
run()
void run () override virtual
Run the kernels contained in the function.
For CPU kernels:
Multi-threading is used for the kernels which are parallelisable.
By default std::thread::hardware_concurrency() threads are used.
Note
CPPScheduler::set_num_threads() can be used to manually set the number of threads
For OpenCL kernels:
All the kernels are enqueued on the queue associated with CLScheduler.
The queue is then flushed.
Note
The function will not block until the kernels are executed. It is the user's responsibility to wait.
Will call prepare() on first run if hasn't been done
Implements IFunction.
Definition at line 79 of file NEInstanceNormalizationLayer.cpp.
 {
     MemoryGroupResourceScope scope_mg(_memory_group);
     // Permute input
     if(!_is_nchw)
     {
         _permute_input.run();
     }
     NEScheduler::get().schedule(_normalization_kernel.get(), Window::DimZ);
     // Permute output
     if(!_is_nchw)
     {
         _permute_output.run();
     }
 }
References Window::DimZ, Scheduler::get(), NEPermute::run(), and IScheduler::schedule().
validate()
Status validate (const ITensorInfo * input, const ITensorInfo * output, float gamma = 1.0f, float beta = 0.0f, float epsilon = 1e-12f) static
Static function to check if given info will lead to a valid configuration of NEInstanceNormalizationLayer.
Parameters
[in] input Source tensor info. Data types supported: F16/F32. Data layout supported: NHWC, NCHW
[in] output Destination tensor info. Data types and data layouts supported: same as input.
[in] gamma (Optional) The scale scalar value applied to the normalized tensor. Defaults to 1.0
[in] beta (Optional) The offset scalar value applied to the normalized tensor. Defaults to 0.0
[in] epsilon (Optional) Lower bound value for the normalization. Defaults to 1e-12
Returns
a status
Definition at line 72 of file NEInstanceNormalizationLayer.cpp.
 {
     return NEInstanceNormalizationLayerKernel::validate(&input->clone()->set_data_layout(DataLayout::NCHW),
                                                         &output->clone()->set_data_layout(DataLayout::NCHW),
                                                         InstanceNormalizationLayerKernelInfo{ gamma, beta, epsilon, true });
 }
References ICloneable< T >::clone(), arm_compute::quantization::epsilon, arm_compute::test::validation::input, arm_compute::NCHW, and NEInstanceNormalizationLayerKernel::validate().
The documentation for this class was generated from the following files:
arm_compute/runtime/NEON/functions/NEInstanceNormalizationLayer.h
src/runtime/NEON/functions/NEInstanceNormalizationLayer.cpp