Compute Library: PixelValue Class Reference
PixelValue Class Reference
Class describing the value of a pixel for any image format.
#include <PixelValue.h>
Public Member Functions
PixelValue () noexcept
Default constructor: value initialized to 0.
PixelValue (double v, DataType datatype, QuantizationInfo qinfo=QuantizationInfo())
Initialize the union with a pixel value of chosen datatype.
PixelValue (int8_t v)
Initialize the union with a S8 pixel value.
PixelValue (uint8_t v)
Initialize the union with a U8 pixel value.
PixelValue (uint16_t v)
Initialize the union with a U16 pixel value.
PixelValue (int16_t v)
Initialize the union with a S16 pixel value.
PixelValue (uint32_t v)
Initialize the union with a U32 pixel value.
PixelValue (int32_t v)
Initialize the union with a S32 pixel value.
PixelValue (uint64_t v)
Initialize the union with a U64 pixel value.
PixelValue (int64_t v)
Initialize the union with a S64 pixel value.
PixelValue (bfloat16 v)
Initialize the union with a BFLOAT16 pixel value.
PixelValue (half v)
Initialize the union with a F16 pixel value.
PixelValue (float v)
Initialize the union with a F32 pixel value.
PixelValue (double v)
Initialize the union with a F64 pixel value.
void get (uint8_t &v) const
Interpret the pixel value as a U8.
void get (int8_t &v) const
Interpret the pixel value as a S8.
void get (uint16_t &v) const
Interpret the pixel value as a U16.
void get (int16_t &v) const
Interpret the pixel value as a S16.
void get (uint32_t &v) const
Interpret the pixel value as a U32.
void get (int32_t &v) const
Interpret the pixel value as a S32.
void get (uint64_t &v) const
Interpret the pixel value as a U64.
void get (int64_t &v) const
Interpret the pixel value as a S64.
void get (bfloat16 &v) const
Interpret the pixel value as a BFLOAT16.
void get (half &v) const
Interpret the pixel value as a F16.
void get (float &v) const
Interpret the pixel value as a F32.
void get (double &v) const
Interpret the pixel value as a double.
template<typename T >
T get () const
Get the pixel value.
Data Fields
union {
uint64_t u64
Single channel U64.
int64_t s64
Single channel S64.
uint8_t rgb [3]
3 channels: RGB888
uint8_t yuv [3]
3 channels: Any YUV format
uint8_t rgbx [4]
4 channels: RGBX8888
double f64
Single channel double.
float f32
Single channel float 32.
half f16
Single channel F16.
bfloat16 bf16
Single channel brain floating-point number.
uint8_t u8
Single channel U8.
int8_t s8
Single channel S8.
uint16_t u16
Single channel U16.
int16_t s16
Single channel S16.
uint32_t u32
Single channel U32.
int32_t s32
Single channel S32.
} value
Union which describes the value of a pixel for any image format.
Detailed Description
Class describing the value of a pixel for any image format.
Definition at line 34 of file PixelValue.h.
Constructor & Destructor Documentation
PixelValue() [1/14]
PixelValue () inline noexcept
Default constructor: value initialized to 0.
Definition at line 38 of file PixelValue.h.
         : value
     {
         int64_t(0)
     }
     {
     }
PixelValue() [2/14]
PixelValue (double v, DataType datatype, QuantizationInfo qinfo = QuantizationInfo()) inline
Initialize the union with a pixel value of chosen datatype.
Parameters
[in] v value.
[in] datatype DataType that v have to be stored
[in] qinfo (Optional) QuantizationInfo to apply in case of quantized data types to v
Definition at line 51 of file PixelValue.h.
         : PixelValue()
     {
         switch(datatype)
         {
             case DataType::U8:
                 value.u8 = static_cast<uint8_t>(v);
                 break;
             case DataType::S8:
                 value.s8 = static_cast<int8_t>(v);
                 break;
             case DataType::QASYMM8:
                 value.u8 = quantize_qasymm8(static_cast<float>(v), qinfo);
                 break;
             case DataType::QASYMM8_SIGNED:
                 value.s8 = quantize_qasymm8_signed(static_cast<float>(v), qinfo);
                 break;
             case DataType::QSYMM8:
                 value.s8 = quantize_qsymm8(static_cast<float>(v), qinfo);
                 break;
             case DataType::U16:
                 value.u16 = static_cast<uint16_t>(v);
                 break;
             case DataType::S16:
                 value.s16 = static_cast<int16_t>(v);
                 break;
             case DataType::QASYMM16:
                 value.u16 = quantize_qasymm16(static_cast<float>(v), qinfo);
                 break;
             case DataType::QSYMM16:
                 value.s16 = quantize_qsymm16(static_cast<float>(v), qinfo);
                 break;
             case DataType::U32:
                 value.u32 = static_cast<uint32_t>(v);
                 break;
             case DataType::S32:
                 value.s32 = static_cast<int32_t>(v);
                 break;
             case DataType::U64:
                 value.u64 = static_cast<uint64_t>(v);
                 break;
             case DataType::S64:
                 value.s64 = static_cast<int64_t>(v);
                 break;
             case DataType::BFLOAT16:
                 value.bf16 = static_cast<bfloat16>(v);
                 break;
             case DataType::F16:
                 value.f16 = static_cast<half>(v);
                 break;
             case DataType::F32:
                 value.f32 = static_cast<float>(v);
                 break;
             case DataType::F64:
             default:
                 value.f64 = v;
                 break;
         }
     }
References arm_compute::BFLOAT16, arm_compute::F16, arm_compute::F32, arm_compute::F64, arm_compute::QASYMM16, arm_compute::QASYMM8, arm_compute::QASYMM8_SIGNED, arm_compute::test::validation::qinfo, arm_compute::QSYMM16, arm_compute::QSYMM8, arm_compute::quantize_qasymm16(), arm_compute::quantize_qasymm8(), arm_compute::quantize_qasymm8_signed(), arm_compute::quantize_qsymm16(), arm_compute::quantize_qsymm8(), arm_compute::S16, arm_compute::S32, arm_compute::S64, arm_compute::S8, arm_compute::U16, arm_compute::U32, arm_compute::U64, arm_compute::U8, and PixelValue::value.
PixelValue() [3/14]
PixelValue (int8_t v) inline
Initialize the union with a S8 pixel value.
Parameters
[in] v S8 value.
Definition at line 114 of file PixelValue.h.
         : PixelValue()
     {
         value.s8 = v;
     }
References PixelValue::value.
PixelValue() [4/14]
PixelValue (uint8_t v) inline
Initialize the union with a U8 pixel value.
Parameters
[in] v U8 value.
Definition at line 123 of file PixelValue.h.
         : PixelValue()
     {
         value.u8 = v;
     }
References PixelValue::value.
PixelValue() [5/14]
PixelValue (uint16_t v) inline
Initialize the union with a U16 pixel value.
Parameters
[in] v U16 value.
Definition at line 132 of file PixelValue.h.
         : PixelValue()
     {
         value.u16 = v;
     }
References PixelValue::value.
PixelValue() [6/14]
PixelValue (int16_t v) inline
Initialize the union with a S16 pixel value.
Parameters
[in] v S16 value.
Definition at line 141 of file PixelValue.h.
         : PixelValue()
     {
         value.s16 = v;
     }
References PixelValue::value.
PixelValue() [7/14]
PixelValue (uint32_t v) inline
Initialize the union with a U32 pixel value.
Parameters
[in] v U32 value.
Definition at line 150 of file PixelValue.h.
         : PixelValue()
     {
         value.u32 = v;
     }
References PixelValue::value.
PixelValue() [8/14]
PixelValue (int32_t v) inline
Initialize the union with a S32 pixel value.
Parameters
[in] v S32 value.
Definition at line 159 of file PixelValue.h.
         : PixelValue()
     {
         value.s32 = v;
     }
References PixelValue::value.
PixelValue() [9/14]
PixelValue (uint64_t v) inline
Initialize the union with a U64 pixel value.
Parameters
[in] v U64 value.
Definition at line 169 of file PixelValue.h.
         : PixelValue()
     {
         value.u64 = v;
     }
References PixelValue::value.
PixelValue() [10/14]
PixelValue (int64_t v) inline
Initialize the union with a S64 pixel value.
Parameters
[in] v S64 value.
Definition at line 178 of file PixelValue.h.
         : PixelValue()
     {
         value.s64 = v;
     }
References PixelValue::value.
PixelValue() [11/14]
PixelValue (bfloat16 v) inline
Initialize the union with a BFLOAT16 pixel value.
Parameters
[in] v F16 value.
Definition at line 187 of file PixelValue.h.
         : PixelValue()
     {
         value.bf16 = v;
     }
References PixelValue::value.
PixelValue() [12/14]
PixelValue (half v) inline
Initialize the union with a F16 pixel value.
Parameters
[in] v F16 value.
Definition at line 196 of file PixelValue.h.
         : PixelValue()
     {
         value.f16 = v;
     }
References PixelValue::value.
PixelValue() [13/14]
PixelValue (float v) inline
Initialize the union with a F32 pixel value.
Parameters
[in] v F32 value.
Definition at line 205 of file PixelValue.h.
         : PixelValue()
     {
         value.f32 = v;
     }
References PixelValue::value.
PixelValue() [14/14]
PixelValue (double v) inline
Initialize the union with a F64 pixel value.
Parameters
[in] v F64 value.
Definition at line 214 of file PixelValue.h.
         : PixelValue()
     {
         value.f64 = v;
     }
References PixelValue::value.
Member Function Documentation
get() [1/13]
void get (uint8_t & v) const inline
Interpret the pixel value as a U8.
Parameters
[out] v Returned value
Definition at line 244 of file PixelValue.h.
     {
         v = value.u8;
     }
References PixelValue::value.
Referenced by RandomAccessor::access_tensor(), arm_compute::cpu::bilinear_neon_scale(), ClDirectConvolutionKernel::configure(), arm_compute::test::validation::reference::pad_layer(), CLFillBorderKernel::set_constant_border(), and arm_compute::string_from_pixel_value().
get() [2/13]
void get (int8_t & v) const inline
Interpret the pixel value as a S8.
Parameters
[out] v Returned value
Definition at line 252 of file PixelValue.h.
     {
         v = value.s8;
     }
References PixelValue::value.
get() [3/13]
void get (uint16_t & v) const inline
Interpret the pixel value as a U16.
Parameters
[out] v Returned value
Definition at line 260 of file PixelValue.h.
     {
         v = value.u16;
     }
References PixelValue::value.
get() [4/13]
void get (int16_t & v) const inline
Interpret the pixel value as a S16.
Parameters
[out] v Returned value
Definition at line 268 of file PixelValue.h.
     {
         v = value.s16;
     }
References PixelValue::value.
get() [5/13]
void get (uint32_t & v) const inline
Interpret the pixel value as a U32.
Parameters
[out] v Returned value
Definition at line 276 of file PixelValue.h.
     {
         v = value.u32;
     }
References PixelValue::value.
get() [6/13]
void get (int32_t & v) const inline
Interpret the pixel value as a S32.
Parameters
[out] v Returned value
Definition at line 284 of file PixelValue.h.
     {
         v = value.s32;
     }
References PixelValue::value.
get() [7/13]
void get (uint64_t & v) const inline
Interpret the pixel value as a U64.
Parameters
[out] v Returned value
Definition at line 292 of file PixelValue.h.
     {
         v = value.u64;
     }
References PixelValue::value.
get() [8/13]
void get (int64_t & v) const inline
Interpret the pixel value as a S64.
Parameters
[out] v Returned value
Definition at line 300 of file PixelValue.h.
     {
         v = value.s64;
     }
References PixelValue::value.
get() [9/13]
void get (bfloat16 & v) const inline
Interpret the pixel value as a BFLOAT16.
Parameters
[out] v Returned value
Definition at line 308 of file PixelValue.h.
     {
         v = value.bf16;
     }
References PixelValue::value.
get() [10/13]
void get (half & v) const inline
Interpret the pixel value as a F16.
Parameters
[out] v Returned value
Definition at line 316 of file PixelValue.h.
     {
         v = value.f16;
     }
References PixelValue::value.
get() [11/13]
void get (float & v) const inline
Interpret the pixel value as a F32.
Parameters
[out] v Returned value
Definition at line 324 of file PixelValue.h.
     {
         v = value.f32;
     }
References PixelValue::value.
get() [12/13]
void get (double & v) const inline
Interpret the pixel value as a double.
Parameters
[out] v Returned value
Definition at line 332 of file PixelValue.h.
     {
         v = value.f64;
     }
References PixelValue::value.
get() [13/13]
T get () const inline
Get the pixel value.
Returns
Pixel value
Definition at line 341 of file PixelValue.h.
     {
         T val;
         get(val);
         return val;
     }
Field Documentation
bf16
bfloat16 bf16
Single channel brain floating-point number.
Definition at line 232 of file PixelValue.h.
f16
half f16
Single channel F16.
Definition at line 231 of file PixelValue.h.
f32
float f32
Single channel float 32.
Definition at line 230 of file PixelValue.h.
f64
double f64
Single channel double.
Definition at line 229 of file PixelValue.h.
rgb
uint8_t rgb[3]
3 channels: RGB888
Definition at line 226 of file PixelValue.h.
rgbx
uint8_t rgbx[4]
4 channels: RGBX8888
Definition at line 228 of file PixelValue.h.
s16
int16_t s16
Single channel S16.
Definition at line 236 of file PixelValue.h.
s32
int32_t s32
Single channel S32.
Definition at line 238 of file PixelValue.h.
s64
int64_t s64
Single channel S64.
Definition at line 225 of file PixelValue.h.
s8
int8_t s8
Single channel S8.
Definition at line 234 of file PixelValue.h.
u16
uint16_t u16
Single channel U16.
Definition at line 235 of file PixelValue.h.
u32
uint32_t u32
Single channel U32.
Definition at line 237 of file PixelValue.h.
u64
uint64_t u64
Single channel U64.
Definition at line 224 of file PixelValue.h.
u8
uint8_t u8
Single channel U8.
Definition at line 233 of file PixelValue.h.
value
union { ... } value
Union which describes the value of a pixel for any image format.
Use the field corresponding to the image format
Referenced by PixelValue::get(), PixelValue::PixelValue(), and CpuFillKernel::run_op().
yuv
uint8_t yuv[3]
3 channels: Any YUV format
Definition at line 227 of file PixelValue.h.
The documentation for this class was generated from the following file:
arm_compute/core/PixelValue.h