Compute Library: CpuPoolingAssemblyDispatch Class Reference
CpuPoolingAssemblyDispatch Class Reference
Basic function to run pooling assembly kernels.
#include <CpuPoolingAssemblyDispatch.h>
Public Member Functions
CpuPoolingAssemblyDispatch (std::shared_ptr< IMemoryManager > memory_manager=nullptr)
Constructor.
CpuPoolingAssemblyDispatch (const CpuPoolingAssemblyDispatch &)=delete
Prevent instances of this class from being copied.
CpuPoolingAssemblyDispatch (CpuPoolingAssemblyDispatch &&)=default
Default move constructor.
CpuPoolingAssemblyDispatch & operator= (const CpuPoolingAssemblyDispatch &)=delete
Prevent instances of this class from being copied.
CpuPoolingAssemblyDispatch & operator= (CpuPoolingAssemblyDispatch &&)=default
Default move assignment operator.
~CpuPoolingAssemblyDispatch ()
Destructor.
void configure (const ITensorInfo *src, ITensorInfo *dst, const PoolingLayerInfo &info)
If supported create an assembly routine, else fallback to Compute Library function.
bool is_configured () const
Was the function successfully configured ?
void run (ITensorPack &tensors) override
Run the kernels contained in the function.
Public Member Functions inherited from INEOperator
INEOperator (IRuntimeContext *ctx=nullptr)
Constructor.
INEOperator (const INEOperator &)=delete
Prevent instances of this class from being copied (As this class contains pointers)
INEOperator (INEOperator &&)=default
Default move constructor.
INEOperator & operator= (const INEOperator &)=delete
Prevent instances of this class from being copied (As this class contains pointers)
INEOperator & operator= (INEOperator &&)=default
Default move assignment operator.
~INEOperator ()
Default destructor.
void prepare (ITensorPack &constants) override
Prepare the function for executing.
MemoryRequirements workspace () const override
Return the memory requirements required by the workspace.
Public Member Functions inherited from IOperator
virtual ~IOperator ()=default
Destructor.
Static Public Member Functions
static Status validate (const ITensorInfo *src, const ITensorInfo *dst, const PoolingLayerInfo &info)
Indicates whether or not this function can be used to process the given parameters.
Detailed Description
Basic function to run pooling assembly kernels.
Definition at line 40 of file CpuPoolingAssemblyDispatch.h.
Constructor & Destructor Documentation
CpuPoolingAssemblyDispatch() [1/3]
CpuPoolingAssemblyDispatch (std::shared_ptr< IMemoryManager > memory_manager = nullptr)
Constructor.
Definition at line 35 of file CpuPoolingAssemblyDispatch.cpp.
     : _memory_group(std::move(memory_manager)),
       _workspace(),
       _is_global_pooling_layer(false)
 {
 }
CpuPoolingAssemblyDispatch() [2/3]
CpuPoolingAssemblyDispatch (const CpuPoolingAssemblyDispatch &) delete
Prevent instances of this class from being copied.
CpuPoolingAssemblyDispatch() [3/3]
CpuPoolingAssemblyDispatch (CpuPoolingAssemblyDispatch &&) default
Default move constructor.
~CpuPoolingAssemblyDispatch()
~CpuPoolingAssemblyDispatch () default
Destructor.
Member Function Documentation
configure()
void configure (const ITensorInfo * src, ITensorInfo * dst, const PoolingLayerInfo & info)
If supported create an assembly routine, else fallback to Compute Library function.
Parameters
[in] src Source tensor info. Data types supported: QASYMM8/QASYMM8_SIGNED/F16/F32.
[out] dst Destination tensor info to store the result of pooling. Data types supported: same as src.
[in] info Pooling meta-data
Definition at line 44 of file CpuPoolingAssemblyDispatch.cpp.
 {
     const CPUInfo     &ci          = NEScheduler::get().cpu_info();
     const unsigned int num_threads = NEScheduler::get().num_threads();
     // If we don't support a combination of data types, silently return: it is the caller's responsibility to check if configure() was successful via is_configured()
     if(!CpuPoolingAssemblyDispatch::validate(src, dst, info))
     {
         return;
     }
     auto pooling_wrapper = std::make_unique<kernels::CpuPoolingAssemblyWrapperKernel>();
     ARM_COMPUTE_ERROR_ON(pooling_wrapper == nullptr);
     pooling_wrapper->configure(src, dst, info, ci);
     // Check if we have Global Pooling Layer
     _is_global_pooling_layer = (src->dimension(2) == info.pool_size.width) && (src->dimension(1) == info.pool_size.height);
     // Allocate workspace based on kernel's memory requirements
     constexpr size_t alignment      = 4096;
     const size_t     workspace_size = pooling_wrapper->get_working_size(num_threads);
     _workspace.allocator()->init(TensorInfo(TensorShape{ (workspace_size + alignment) }, 1, DataType::S8), alignment);
     _memory_group.manage(&_workspace);
     _workspace.allocator()->allocate();
     _kernel = std::move(pooling_wrapper);
 }
References TensorAllocator::allocate(), Tensor::allocator(), ARM_COMPUTE_ERROR_ON, IScheduler::cpu_info(), arm_compute::test::validation::dst, Scheduler::get(), arm_compute::test::validation::info, TensorAllocator::init(), MemoryGroup::manage(), IScheduler::num_threads(), arm_compute::S8, arm_compute::test::validation::src, and CpuPoolingAssemblyDispatch::validate().
is_configured()
bool is_configured () const
Was the function successfully configured ?
Returns
True if the function is configured and ready to run
Definition at line 77 of file CpuPoolingAssemblyDispatch.cpp.
 {
     return _kernel != nullptr;
 }
operator=() [1/2]
CpuPoolingAssemblyDispatch& operator= (const CpuPoolingAssemblyDispatch &) delete
Prevent instances of this class from being copied.
operator=() [2/2]
CpuPoolingAssemblyDispatch& operator= (CpuPoolingAssemblyDispatch &&) default
Default move assignment operator.
run()
void run (ITensorPack & tensors) override virtual
Run the kernels contained in the function.
Parameters
[in] tensors Vector that contains the tensors to operate on.
Reimplemented from INEOperator.
Definition at line 82 of file CpuPoolingAssemblyDispatch.cpp.
 {
     ARM_COMPUTE_ERROR_ON_MSG(tensors.empty(), "No srcs provided");
     tensors.add_tensor(TensorType::ACL_DST_1, &_workspace);
     if(_is_global_pooling_layer)
     {
         NEScheduler::get().schedule_op(_kernel.get(), Window::DimX, _kernel->window(), tensors);
     }
     else
     {
         NEScheduler::get().schedule_op(_kernel.get(), Window::DimY, _kernel->window(), tensors);
     }
 }
References arm_compute::ACL_DST_1, ITensorPack::add_tensor(), ARM_COMPUTE_ERROR_ON_MSG, Window::DimX, Window::DimY, ITensorPack::empty(), Scheduler::get(), and IScheduler::schedule_op().
validate()
Status validate (const ITensorInfo * src, const ITensorInfo * dst, const PoolingLayerInfo & info) static
Indicates whether or not this function can be used to process the given parameters.
Parameters
[in] src Source tensor info. Data types supported: QASYMM8/QASYMM8_SIGNED/F16/F32.
[in] dst Destination tensor to store the result of pooling. Data types supported: same as src.
[in] info Pooling meta-data
Returns
a status.
Definition at line 72 of file CpuPoolingAssemblyDispatch.cpp.
 {
     return kernels::CpuPoolingAssemblyWrapperKernel::validate(src, dst, info);
 }
References arm_compute::test::validation::dst, arm_compute::test::validation::info, arm_compute::test::validation::src, and CpuPoolingAssemblyWrapperKernel::validate().
Referenced by CpuPoolingAssemblyDispatch::configure(), CpuPooling::configure(), and CpuPooling::validate().
The documentation for this class was generated from the following files:
src/runtime/cpu/operators/CpuPoolingAssemblyDispatch.h
src/runtime/cpu/operators/CpuPoolingAssemblyDispatch.cpp