Compute Library: NEConvolutionLayerReshapeWeightsTransform Class Reference
NEConvolutionLayerReshapeWeightsTransform Class Reference
Basic function to manage the reshape weights generated from NEConvolutionLayerReshapeWeights.
#include <NEGEMMConvolutionLayer.h>
Public Member Functions
NEConvolutionLayerReshapeWeightsTransform ()=default
Constructor.
NEConvolutionLayerReshapeWeightsTransform (const NEConvolutionLayerReshapeWeightsTransform &)=delete
Prevent instances of this class from being copied (As this class contains pointers)
NEConvolutionLayerReshapeWeightsTransform & operator= (const NEConvolutionLayerReshapeWeightsTransform &)=delete
Prevent instances of this class from being copied (As this class contains pointers)
NEConvolutionLayerReshapeWeightsTransform (NEConvolutionLayerReshapeWeightsTransform &&)=delete
Prevent instances of this class from being moved (As this class contains non movable objects)
NEConvolutionLayerReshapeWeightsTransform & operator= (NEConvolutionLayerReshapeWeightsTransform &&)=delete
Prevent instances of this class from being moved (As this class contains non movable objects)
~NEConvolutionLayerReshapeWeightsTransform ()=default
Default destructor.
void configure (const ITensor *input, const ITensor *biases)
void run () override
Run the transformation function.
ITensor * get_weights () override
Get a pointer to the transformed weights.
void release () override
Release transformed weights memory.
uint32_t uid () override
Function that returns a unique id of the reshape function.
bool is_reshape_run ()
Public Member Functions inherited from ITransformWeights
ITransformWeights ()=default
Default Constructor.
virtual ~ITransformWeights ()=default
Default Destructor.
ITransformWeights (const ITransformWeights &)=delete
Prevent instances of this class to be copy constructed.
ITransformWeights & operator= (const ITransformWeights &)=delete
Prevent instances of this class to be copied.
ITransformWeights (ITransformWeights &&other)
Allow instances of this class to be move constructed.
ITransformWeights & operator= (ITransformWeights &&other)
Allow instances of this class to be moved.
void increase_refcount ()
Increase the object's refcount.
int32_t decrease_refcount ()
Decrease the object's refcount and return the updated value.
bool is_reshape_run ()
Function that returns a flag on whether the weights are reshaped or not.
Detailed Description
Basic function to manage the reshape weights generated from NEConvolutionLayerReshapeWeights.
Definition at line 98 of file NEGEMMConvolutionLayer.h.
Constructor & Destructor Documentation
NEConvolutionLayerReshapeWeightsTransform() [1/3]
NEConvolutionLayerReshapeWeightsTransform () default
Constructor.
NEConvolutionLayerReshapeWeightsTransform() [2/3]
NEConvolutionLayerReshapeWeightsTransform (const NEConvolutionLayerReshapeWeightsTransform &) delete
Prevent instances of this class from being copied (As this class contains pointers)
NEConvolutionLayerReshapeWeightsTransform() [3/3]
NEConvolutionLayerReshapeWeightsTransform (NEConvolutionLayerReshapeWeightsTransform &&) delete
Prevent instances of this class from being moved (As this class contains non movable objects)
~NEConvolutionLayerReshapeWeightsTransform()
~NEConvolutionLayerReshapeWeightsTransform () default
Default destructor.
Member Function Documentation
configure()
void configure (const ITensor * input, const ITensor * biases) inline
Definition at line 113 of file NEGEMMConvolutionLayer.h.
     {
         _bias_bit = (biases != nullptr) ? 1 : 0;
         _func.configure(input, biases, &_output);
     }
References NEConvolutionLayerReshapeWeights::configure(), and arm_compute::test::validation::input.
Referenced by NEGEMMConvolutionLayer::configure().
get_weights()
ITensor* get_weights () inline override virtual
Get a pointer to the transformed weights.
Returns
The pointer to the transformed ITensor weights
Implements ITransformWeights.
Definition at line 126 of file NEGEMMConvolutionLayer.h.
     {
         return &_output;
     }
is_reshape_run()
bool is_reshape_run () inline
Definition at line 141 of file NEGEMMConvolutionLayer.h.
     {
         return _reshape_run;
     }
operator=() [1/2]
NEConvolutionLayerReshapeWeightsTransform& operator= (const NEConvolutionLayerReshapeWeightsTransform &) delete
Prevent instances of this class from being copied (As this class contains pointers)
operator=() [2/2]
NEConvolutionLayerReshapeWeightsTransform& operator= (NEConvolutionLayerReshapeWeightsTransform &&) delete
Prevent instances of this class from being moved (As this class contains non movable objects)
release()
void release () inline override virtual
Release transformed weights memory.
Implements ITransformWeights.
Definition at line 131 of file NEGEMMConvolutionLayer.h.
     {
         _output.allocator()->free();
     }
References Tensor::allocator(), and TensorAllocator::free().
run()
void run () inline override virtual
Run the transformation function.
Implements ITransformWeights.
Definition at line 119 of file NEGEMMConvolutionLayer.h.
     {
         _output.allocator()->allocate();
         _func.run();
         _reshape_run = true;
     }
References TensorAllocator::allocate(), Tensor::allocator(), and NEConvolutionLayerReshapeWeights::run().
uid()
uint32_t uid () inline override virtual
Function that returns a unique id of the reshape function.
Returns
The computed unique id
Implements ITransformWeights.
Definition at line 136 of file NEGEMMConvolutionLayer.h.
     {
         return ((0x8) | (_bias_bit << 7));
     }
The documentation for this class was generated from the following file:
arm_compute/runtime/NEON/functions/NEGEMMConvolutionLayer.h