Compute Library: CpuDepthwiseConvolution Class Reference
CpuDepthwiseConvolution Class Reference
Function to execute a depthwise convolution.
#include <CpuDepthwiseConvolution.h>
Public Member Functions
CpuDepthwiseConvolution ()
Default constructor.
void configure (ITensorInfo *input, const ITensorInfo *weights, const ITensorInfo *biases, ITensorInfo *output, const ConvolutionInfo &info)
Initialize the function's source, destination, weights and convolution information.
void run (ITensorPack &tensors) override
Run the kernels contained in the function.
void prepare (ITensorPack &tensors) override
Prepare the function for executing.
Public Member Functions inherited from INEOperator
INEOperator (IRuntimeContext *ctx=nullptr)
Constructor.
INEOperator (const INEOperator &)=delete
Prevent instances of this class from being copied (As this class contains pointers)
INEOperator (INEOperator &&)=default
Default move constructor.
INEOperator & operator= (const INEOperator &)=delete
Prevent instances of this class from being copied (As this class contains pointers)
INEOperator & operator= (INEOperator &&)=default
Default move assignment operator.
~INEOperator ()
Default destructor.
MemoryRequirements workspace () const override
Return the memory requirements required by the workspace.
Public Member Functions inherited from IOperator
virtual ~IOperator ()=default
Destructor.
Static Public Member Functions
static Status validate (const ITensorInfo *input, const ITensorInfo *weights, const ITensorInfo *biases, const ITensorInfo *output, const ConvolutionInfo &info)
Static function to check if given info will lead to a valid configuration of CpuDepthwiseConvolution.
static DepthwiseConvolutionFunction get_depthwiseconvolution_function (const ITensorInfo *input, const ITensorInfo *weights, const ITensorInfo *biases, const ITensorInfo *output, const ConvolutionInfo &info)
Static function to choose the best depthwise convolution function for CpuDepthwiseConvolution.
Detailed Description
Function to execute a depthwise convolution.
Definition at line 44 of file CpuDepthwiseConvolution.h.
Constructor & Destructor Documentation
CpuDepthwiseConvolution()
CpuDepthwiseConvolution ()
Default constructor.
Definition at line 443 of file CpuDepthwiseConvolution.cpp.
     : _depth_conv_func(DepthwiseConvolutionFunction::GENERIC), _func_optimized(), _func_generic()
 {
 }
References arm_compute::GENERIC.
Member Function Documentation
configure()
void configure (ITensorInfo * input, const ITensorInfo * weights, const ITensorInfo * biases, ITensorInfo * output, const ConvolutionInfo & info)
Initialize the function's source, destination, weights and convolution information.
Parameters
[in,out] input Source tensor info. Data type supported: QASYMM8/QASYMM8_SIGNED/F16/F32
[out] output Destination tensor info. Data type supported: same as input.
[in] weights Weights tensor info. These are 3D tensor infos with shape [kernel_x, kernel_y, IFM]. Data type supported: Same as input or QASYMM8/QASYMM8_SIGNED/QSYMM8_PER_CHANNEL when input is QASYMM8/QASYMM8_SIGNED.
[in] biases Biases tensor info. A 1D tensor with shape [IFM]. Must be nullptr if not needed. Data type supported: Same as input, S32 when input is QASYMM8/QASYMM8_SIGNED.
[in] info Depthwise convolution meta-data.
Definition at line 448 of file CpuDepthwiseConvolution.cpp.
 {
     _depth_conv_func = get_depthwiseconvolution_function(input, weights, (biases != nullptr) ? biases : nullptr, output, info);
     switch(_depth_conv_func)
     {
         case DepthwiseConvolutionFunction::OPTIMIZED:
             _func_optimized.configure(input, weights, biases, output, info);
             break;
         case DepthwiseConvolutionFunction::GENERIC:
             _func_generic.configure(input, weights, biases, output, info);
             break;
         default:
             ARM_COMPUTE_ERROR("Unsupported DepthwiseConvolutionFunction");
     }
 }
References ARM_COMPUTE_ERROR, arm_compute::GENERIC, CpuDepthwiseConvolution::get_depthwiseconvolution_function(), arm_compute::test::validation::info, arm_compute::test::validation::input, and arm_compute::OPTIMIZED.
get_depthwiseconvolution_function()
DepthwiseConvolutionFunction get_depthwiseconvolution_function (const ITensorInfo * input, const ITensorInfo * weights, const ITensorInfo * biases, const ITensorInfo * output, const ConvolutionInfo & info) static
Static function to choose the best depthwise convolution function for CpuDepthwiseConvolution.
Parameters
[in] input Source tensor info. Data type supported: QASYMM8/QASYMM8_SIGNED/F16/F32
[in] weights Weights tensor info. These are 3D tensors with shape [kernel_x, kernel_y, IFM]. Data type supported: Same as input or QASYMM8/QASYMM8_SIGNED/QSYMM8_PER_CHANNEL when input is QASYMM8/QASYMM8_SIGNED.
[in] biases Biases tensor info. A 1D tensor with shape [IFM]. Must be nullptr if not needed. Data type supported: Same as input, S32 when input is QASYMM8/QASYMM8_SIGNED.
[in] output Destination tensor. Data type supported: same as input.
[in] info Depthwise convolution meta-data.
Returns
a Depthwise Convolution Function
Definition at line 480 of file CpuDepthwiseConvolution.cpp.
 {
     if(bool(CpuDepthwiseConvolutionOptimizedInternal::validate(input, weights, biases, output, info)))
     {
         return DepthwiseConvolutionFunction::OPTIMIZED;
     }
     else
     {
         return DepthwiseConvolutionFunction::GENERIC;
     }
 }
References arm_compute::GENERIC, arm_compute::test::validation::info, arm_compute::test::validation::input, arm_compute::OPTIMIZED, and arm_compute::validate().
Referenced by CpuDepthwiseConvolution::configure(), and CpuDepthwiseConvolution::validate().
prepare()
void prepare (ITensorPack & constants) override virtual
Prepare the function for executing.
Any one off pre-processing step required by the function is handled here
Parameters
[in] constants Vector that contains the constants tensors.
Note
Prepare stage might not need all the function's buffers' backing memory to be available in order to execute
Reimplemented from INEOperator.
Definition at line 508 of file CpuDepthwiseConvolution.cpp.
 {
     switch(_depth_conv_func)
     {
         case DepthwiseConvolutionFunction::OPTIMIZED:
             _func_optimized.prepare(tensors);
             break;
         case DepthwiseConvolutionFunction::GENERIC:
             _func_generic.prepare(tensors);
             break;
         default:
             ARM_COMPUTE_ERROR("DepthwiseConvolutionFunction not properly configured");
     }
 }
References ARM_COMPUTE_ERROR, arm_compute::GENERIC, and arm_compute::OPTIMIZED.
run()
void run (ITensorPack & tensors) override virtual
Run the kernels contained in the function.
Parameters
[in] tensors Vector that contains the tensors to operate on.
Reimplemented from INEOperator.
Definition at line 493 of file CpuDepthwiseConvolution.cpp.
 {
     switch(_depth_conv_func)
     {
         case DepthwiseConvolutionFunction::OPTIMIZED:
             _func_optimized.run(tensors);
             break;
         case DepthwiseConvolutionFunction::GENERIC:
             _func_generic.run(tensors);
             break;
         default:
             ARM_COMPUTE_ERROR("DepthwiseConvolutionFunction not properly configured");
     }
 }
References ARM_COMPUTE_ERROR, arm_compute::GENERIC, and arm_compute::OPTIMIZED.
validate()
Status validate (const ITensorInfo * input, const ITensorInfo * weights, const ITensorInfo * biases, const ITensorInfo * output, const ConvolutionInfo & info) static
Static function to check if given info will lead to a valid configuration of CpuDepthwiseConvolution.
Parameters
[in] input Source tensor info. Data type supported: QASYMM8/QASYMM8_SIGNED/F16/F32
[in] output Destination tensor info. Data type supported: same as input.
[in] weights Weights tensor info. These are 3D tensors info with shape [kernel_x, kernel_y, IFM]. Data type supported: Same as input or QASYMM8/QASYMM8_SIGNED/QSYMM8_PER_CHANNEL when input is QASYMM8/QASYMM8_SIGNED.
[in] biases Biases tensor info. A 1D tensor with shape [IFM]. Must be nullptr if not needed. Data type supported: Same as input, S32 when input is QASYMM8/QASYMM8_SIGNED.
[in] info Depthwise convolution meta-data.
Returns
a status
Definition at line 464 of file CpuDepthwiseConvolution.cpp.
 {
     DepthwiseConvolutionFunction depth_conv_func = get_depthwiseconvolution_function(input, weights, biases, output, info);
     switch(depth_conv_func)
     {
         case DepthwiseConvolutionFunction::OPTIMIZED:
             return CpuDepthwiseConvolutionOptimizedInternal::validate(input, weights, biases, output, info);
             break;
         case DepthwiseConvolutionFunction::GENERIC:
             return CpuDepthwiseConvolutionGeneric::validate(input, weights, biases, output, info);
             break;
         default:
             ARM_COMPUTE_ERROR("Unsupported DepthwiseConvolutionFunction");
     }
 }
References ARM_COMPUTE_ERROR, arm_compute::GENERIC, CpuDepthwiseConvolution::get_depthwiseconvolution_function(), arm_compute::test::validation::info, arm_compute::test::validation::input, arm_compute::OPTIMIZED, and arm_compute::validate().
Referenced by NEDepthwiseConvolutionLayer::validate().
The documentation for this class was generated from the following files:
src/runtime/cpu/operators/CpuDepthwiseConvolution.h
src/runtime/cpu/operators/CpuDepthwiseConvolution.cpp