Compute Library: NERangeKernel Class Reference
NERangeKernel Class Reference
Kernel class for Range.
#include <NERangeKernel.h>
Public Member Functions
const char * name () const override
Name of the kernel.
NERangeKernel ()
Default constructor.
NERangeKernel (const NERangeKernel &)=delete
Prevent instances of this class from being copied (As this class contains pointers)
NERangeKernel & operator= (const NERangeKernel &)=delete
Prevent instances of this class from being copied (As this class contains pointers)
NERangeKernel (NERangeKernel &&)=default
Allow instances of this class to be moved.
NERangeKernel & operator= (NERangeKernel &&)=default
Allow instances of this class to be moved.
~NERangeKernel ()=default
Default destructor.
void configure (ITensor *output, float start, float end, float step)
Initialize the kernel's output tensor, start, end and step of the sequence.
void run (const Window &window, const ThreadInfo &info) override
Execute the kernel on the passed window.
Public Member Functions inherited from ICPPKernel
virtual ~ICPPKernel ()=default
Default destructor.
virtual void run_nd (const Window &window, const ThreadInfo &info, const Window &thread_locator)
legacy compatibility layer for implemantions which do not support thread_locator In these cases we simply narrow the interface down the legacy version
virtual void run_op (ITensorPack &tensors, const Window &window, const ThreadInfo &info)
Execute the kernel on the passed window.
Public Member Functions inherited from IKernel
IKernel ()
Constructor.
virtual ~IKernel ()=default
Destructor.
virtual bool is_parallelisable () const
Indicates whether or not the kernel is parallelisable.
virtual BorderSize border_size () const
The size of the border for that kernel.
const Window & window () const
The maximum window the kernel can be executed on.
bool is_window_configured () const
Function to check if the embedded window of this kernel has been configured.
Static Public Member Functions
static Status validate (const ITensorInfo *output, float start, float end, float step)
Static function to check if given info will lead to a valid configuration of NERangeKernel.
Detailed Description
Kernel class for Range.
range generates a 1-D tensor containing a sequence of numbers that begins at 'start' and extends by increments of 'step' up to but not including 'end'.
Definition at line 39 of file NERangeKernel.h.
Constructor & Destructor Documentation
NERangeKernel() [1/3]
NERangeKernel ()
Default constructor.
Definition at line 113 of file NERangeKernel.cpp.
     : _func(nullptr), _start(0), _end(1), _step(1), _output(nullptr)
 {
 }
NERangeKernel() [2/3]
NERangeKernel (const NERangeKernel &) delete
Prevent instances of this class from being copied (As this class contains pointers)
NERangeKernel() [3/3]
NERangeKernel (NERangeKernel &&) default
Allow instances of this class to be moved.
~NERangeKernel()
~NERangeKernel () default
Default destructor.
Member Function Documentation
configure()
void configure (ITensor * output, float start, float end, float step)
Initialize the kernel's output tensor, start, end and step of the sequence.
Parameters
[out] output Output tensor. Data types supported: U8/S8/U16/S16/U32/S32/F16/F32.
[in] start The starting value of the sequence.
[in] end The ending (not including) value of the sequence.
[in] step The gap between each pair of values in the sequence.
Definition at line 118 of file NERangeKernel.cpp.
 {
     ARM_COMPUTE_ERROR_ON_NULLPTR(output);
     ARM_COMPUTE_ERROR_THROW_ON(validate_arguments(*(output->info()), start, end, step));
     // Auto initialize output if not initialized
     auto_init_if_empty(*output->info(), TensorShape(num_of_elements_in_range(start, end, step)), 1, output->info()->data_type(), output->info()->quantization_info());
     // Configure kernel window
     Window win = calculate_max_window(*output->info(), Steps());
     _start  = start;
     _end    = end;
     _step   = step;
     _output = output;
     switch(_output->info()->data_type())
     {
         case DataType::U8:
             _func = &range_function<uint8_t>;
             break;
         case DataType::U16:
             _func = &range_function<uint16_t>;
             break;
         case DataType::U32:
             _func = &range_function<uint32_t>;
             break;
         case DataType::S8:
             _func = &range_function<int8_t>;
             break;
         case DataType::S16:
             _func = &range_function<int16_t>;
             break;
         case DataType::S32:
             _func = &range_function<int32_t>;
             break;
         case DataType::F32:
             _func = &range_function<float>;
             break;
 #ifdef __ARM_FEATURE_FP16_VECTOR_ARITHMETIC
         case DataType::F16:
             _func = &range_function<float16_t>;
             break;
 #endif // __ARM_FEATURE_FP16_VECTOR_ARITHMETIC
         default:
             ARM_COMPUTE_ERROR("Unsupported data type.");
             break;
     }
     INEKernel::configure(win);
 }
References ARM_COMPUTE_ERROR, ARM_COMPUTE_ERROR_ON_NULLPTR, ARM_COMPUTE_ERROR_THROW_ON, arm_compute::auto_init_if_empty(), arm_compute::calculate_max_window(), ITensorInfo::data_type(), arm_compute::mlgo::parser::end(), arm_compute::F16, arm_compute::F32, ITensor::info(), arm_compute::num_of_elements_in_range(), ITensorInfo::quantization_info(), arm_compute::S16, arm_compute::S32, arm_compute::S8, arm_compute::cpu::step, arm_compute::U16, arm_compute::U32, arm_compute::U8, and arm_compute::validate_arguments().
name()
const char* name () const inline override virtual
Name of the kernel.
Returns
Kernel name
Implements ICPPKernel.
Definition at line 42 of file NERangeKernel.h.
     {
         return "NERangeKernel";
     }
operator=() [1/2]
NERangeKernel& operator= (const NERangeKernel &) delete
Prevent instances of this class from being copied (As this class contains pointers)
operator=() [2/2]
NERangeKernel& operator= (NERangeKernel &&) default
Allow instances of this class to be moved.
run()
void run (const Window & window, const ThreadInfo & info) override virtual
Execute the kernel on the passed window.
Warning
If is_parallelisable() returns false then the passed window must be equal to window()
Note
The window has to be a region within the window returned by the window() method
The width of the window has to be a multiple of num_elems_processed_per_iteration().
Parameters
[in] window Region on which to execute the kernel. (Must be a region of the window returned by window())
[in] info Info about executing thread and CPU.
Reimplemented from ICPPKernel.
Definition at line 179 of file NERangeKernel.cpp.
 {
     ARM_COMPUTE_UNUSED(info);
     ARM_COMPUTE_ERROR_ON_UNCONFIGURED_KERNEL(this);
     ARM_COMPUTE_ERROR_ON_INVALID_SUBWINDOW(INEKernel::window(), window);
     ARM_COMPUTE_ERROR_ON(_func == nullptr);
     (*_func)(_output, _start, _step, window);
 }
References ARM_COMPUTE_ERROR_ON, ARM_COMPUTE_ERROR_ON_INVALID_SUBWINDOW, ARM_COMPUTE_ERROR_ON_UNCONFIGURED_KERNEL, ARM_COMPUTE_UNUSED, arm_compute::test::validation::info, and IKernel::window().
validate()
Status validate (const ITensorInfo * output, float start, float end, float step) static
Static function to check if given info will lead to a valid configuration of NERangeKernel.
Parameters
[in] output Output tensor info. Data types supported: U8/S8/U16/S16/U32/S32/F16/F32.
[in] start The starting value of the sequence.
[in] end The ending (not including) value of the sequence.
[in] step The gap between each pair of values in the sequence.
Returns
a status
Definition at line 170 of file NERangeKernel.cpp.
 {
     ARM_COMPUTE_RETURN_ERROR_ON_NULLPTR(output);
     ARM_COMPUTE_RETURN_ON_ERROR(validate_arguments(*output, start, end, step));
     return Status{};
 }
References ARM_COMPUTE_RETURN_ERROR_ON_NULLPTR, ARM_COMPUTE_RETURN_ON_ERROR, arm_compute::mlgo::parser::end(), arm_compute::cpu::step, and arm_compute::validate_arguments().
Referenced by NERange::validate().
The documentation for this class was generated from the following files:
src/core/NEON/kernels/NERangeKernel.h
src/core/NEON/kernels/NERangeKernel.cpp