Compute Library: CLAbsLayer Class Reference
CLAbsLayer Class Reference
Basic function to get the absolute value of an input tensor.
#include <CLElementWiseUnaryLayer.h>
Public Member Functions
CLAbsLayer ()
Default Constructor.
~CLAbsLayer ()
Default Destructor.
CLAbsLayer (const CLAbsLayer &)=delete
Prevent instances of this class from being copied (As this class contains pointers)
CLAbsLayer (CLAbsLayer &&)
Default move constructor.
CLAbsLayer & operator= (const CLAbsLayer &)=delete
Prevent instances of this class from being copied (As this class contains pointers)
CLAbsLayer & operator= (CLAbsLayer &&)
Default move assignment operator.
void configure (const ICLTensor *input, ICLTensor *output)
Initialize the function.
void configure (const CLCompileContext &compile_context, const ICLTensor *input, ICLTensor *output)
Initialize the function.
void run () override
Run the kernels contained in the function.
Public Member Functions inherited from IFunction
virtual ~IFunction ()=default
Destructor.
virtual void prepare ()
Prepare the function for executing.
Static Public Member Functions
static Status validate (const ITensorInfo *input, const ITensorInfo *output)
Static function to check if given info will lead to a valid configuration of CLAbsLayer.
Detailed Description
Basic function to get the absolute value of an input tensor.
Definition at line 315 of file CLElementWiseUnaryLayer.h.
Constructor & Destructor Documentation
CLAbsLayer() [1/3]
CLAbsLayer ()
Default Constructor.
Definition at line 206 of file CLElementWiseUnaryLayer.cpp.
     : _impl(std::make_unique<Impl>())
 {
 }
~CLAbsLayer()
~CLAbsLayer () default
Default Destructor.
CLAbsLayer() [2/3]
CLAbsLayer (const CLAbsLayer &) delete
Prevent instances of this class from being copied (As this class contains pointers)
CLAbsLayer() [3/3]
CLAbsLayer (CLAbsLayer &&) default
Default move constructor.
Member Function Documentation
configure() [1/2]
void configure (const ICLTensor * input, ICLTensor * output)
Initialize the function.
Valid data layouts:
All
Valid data type configurations:
src dst
F16 F16
F32 F32
Parameters
[in] input Input tensor. Data types supported: F16/F32.
[out] output Output tensor. Data types supported: same as input.
Definition at line 215 of file CLElementWiseUnaryLayer.cpp.
 {
     configure(CLKernelLibrary::get().get_compile_context(), input, output);
 }
References CLKernelLibrary::get(), and arm_compute::test::validation::input.
configure() [2/2]
void configure (const CLCompileContext & compile_context, const ICLTensor * input, ICLTensor * output)
Initialize the function.
Parameters
[in] compile_context The compile context to be used.
[in] input Input tensor. Data types supported: F16/F32.
[out] output Output tensor. Data types supported: same as input.
Definition at line 220 of file CLElementWiseUnaryLayer.cpp.
 {
     _impl->src = input;
     _impl->dst = output;
     _impl->op  = std::make_unique<opencl::ClAbs>();
     _impl->op->configure(compile_context, input->info(), output->info());
 }
References ITensor::info(), and arm_compute::test::validation::input.
operator=() [1/2]
CLAbsLayer& operator= (const CLAbsLayer &) delete
Prevent instances of this class from being copied (As this class contains pointers)
operator=() [2/2]
CLAbsLayer & operator= (CLAbsLayer &&) default
Default move assignment operator.
run()
void run () override virtual
Run the kernels contained in the function.
For CPU kernels:
Multi-threading is used for the kernels which are parallelisable.
By default std::thread::hardware_concurrency() threads are used.
Note
CPPScheduler::set_num_threads() can be used to manually set the number of threads
For OpenCL kernels:
All the kernels are enqueued on the queue associated with CLScheduler.
The queue is then flushed.
Note
The function will not block until the kernels are executed. It is the user's responsibility to wait.
Will call prepare() on first run if hasn't been done
Implements IFunction.
Definition at line 232 of file CLElementWiseUnaryLayer.cpp.
 {
     ITensorPack pack;
     pack.add_tensor(TensorType::ACL_SRC, _impl->src);
     pack.add_tensor(TensorType::ACL_DST, _impl->dst);
     _impl->op->run(pack);
 }
References arm_compute::ACL_DST, arm_compute::ACL_SRC, and ITensorPack::add_tensor().
validate()
Status validate (const ITensorInfo * input, const ITensorInfo * output) static
Static function to check if given info will lead to a valid configuration of CLAbsLayer.
Parameters
[in] input First tensor input info. Data types supported: F16/F32.
[in] output Output tensor info. Data types supported: Same as input.
Returns
a status
Definition at line 227 of file CLElementWiseUnaryLayer.cpp.
 {
     return opencl::ClAbs::validate(input, output);
 }
References arm_compute::test::validation::input, and ClAbs::validate().
The documentation for this class was generated from the following files:
arm_compute/runtime/CL/functions/CLElementWiseUnaryLayer.h
src/runtime/CL/functions/CLElementWiseUnaryLayer.cpp