Compute Library: ActivationLayerInfo Class Reference
ActivationLayerInfo Class Reference
Activation Layer Information class.
#include <Types.h>
Public Types
enum ActivationFunction {
LOGISTIC, TANH, RELU, BOUNDED_RELU,
LU_BOUNDED_RELU, LEAKY_RELU, SOFT_RELU, ELU,
ABS, SQUARE, SQRT, LINEAR,
IDENTITY, HARD_SWISH
}
Available activation functions.
Public Member Functions
ActivationLayerInfo ()=default
ActivationLayerInfo (ActivationFunction f, float a=0.0f, float b=0.0f)
Default Constructor.
ActivationFunction activation () const
Get the type of activation function.
float a () const
Get the alpha value.
float b () const
Get the beta value.
bool enabled () const
Check if initialised.
Detailed Description
Activation Layer Information class.
Definition at line 1478 of file Types.h.
Member Enumeration Documentation
ActivationFunction
enum ActivationFunction strong
Available activation functions.
Enumerator
LOGISTIC
Logistic (\(f(x) = \frac{1}{1 + e^{-x}} \))
TANH
Hyperbolic tangent (\(f(x) = a \cdot tanh(b \cdot x) \))
RELU
Rectifier (\(f(x) = max(0,x) \))
BOUNDED_RELU
Upper Bounded Rectifier (\(f(x) = min(a, max(0,x)) \))
LU_BOUNDED_RELU
Lower and Upper Bounded Rectifier (\(f(x) = min(a, max(b,x)) \))
LEAKY_RELU
Leaky Rectifier (\(f(x) = \begin{cases} \alpha x & \quad \text{if } x \text{ < 0}\\ x & \quad \text{if } x \geq \text{ 0 } \end{cases} \))
SOFT_RELU
Soft Rectifier (\(f(x)= log(1+e^x) \))
ELU
Exponential Linear Unit (\(f(x) = \begin{cases} \alpha (exp(x) - 1) & \quad \text{if } x \text{ < 0}\\ x & \quad \text{if } x \geq \text{ 0 } \end{cases} \))
ABS
Absolute (\(f(x)= |x| \))
SQUARE
Square (\(f(x)= x^2 \))
SQRT
Square root (\(f(x) = \sqrt{x} \))
LINEAR
Linear (\(f(x)= ax + b \))
IDENTITY
Identity (\(f(x)= x \))
HARD_SWISH
Hard-swish (\(f(x) = (x * relu6(x+3))/6 \))
Definition at line 1482 of file Types.h.
     {
         LOGISTIC,        /**< Logistic ( \f$ f(x) = \frac{1}{1 + e^{-x}} \f$ ) */
         TANH,            /**< Hyperbolic tangent ( \f$ f(x) = a \cdot tanh(b \cdot x) \f$ ) */
         RELU,            /**< Rectifier ( \f$ f(x) = max(0,x) \f$ ) */
         BOUNDED_RELU,    /**< Upper Bounded Rectifier ( \f$ f(x) = min(a, max(0,x)) \f$ ) */
         LU_BOUNDED_RELU, /**< Lower and Upper Bounded Rectifier ( \f$ f(x) = min(a, max(b,x)) \f$ ) */
         LEAKY_RELU,      /**< Leaky Rectifier ( \f$ f(x) = \begin{cases}  \alpha x & \quad \text{if } x \text{ < 0}\\  x & \quad \text{if } x \geq \text{ 0 } \end{cases} \f$ ) */
         SOFT_RELU,       /**< Soft Rectifier ( \f$ f(x)= log(1+e^x) \f$ ) */
         ELU,             /**< Exponential Linear Unit ( \f$ f(x) = \begin{cases}  \alpha (exp(x) - 1) & \quad \text{if } x \text{ < 0}\\  x & \quad \text{if } x \geq \text{ 0 } \end{cases} \f$ ) */
         ABS,             /**< Absolute ( \f$ f(x)= |x| \f$ ) */
         SQUARE,          /**< Square ( \f$ f(x)= x^2 \f$ )*/
         SQRT,            /**< Square root ( \f$ f(x) = \sqrt{x} \f$ )*/
         LINEAR,          /**< Linear ( \f$ f(x)= ax + b \f$ ) */
         IDENTITY,        /**< Identity ( \f$ f(x)= x \f$ ) */
         HARD_SWISH       /**< Hard-swish ( \f$ f(x) = (x * relu6(x+3))/6 \f$ ) */
     };
Constructor & Destructor Documentation
ActivationLayerInfo() [1/2]
ActivationLayerInfo () default
ActivationLayerInfo() [2/2]
ActivationLayerInfo (ActivationFunction f, float a = 0.0f, float b = 0.0f) inline
Default Constructor.
Parameters
[in] f The activation function to use.
[in] a (Optional) The alpha parameter used by some activation functions (ActivationFunction::BOUNDED_RELU, ActivationFunction::LU_BOUNDED_RELU, ActivationFunction::LINEAR, ActivationFunction::TANH).
[in] b (Optional) The beta parameter used by some activation functions (ActivationFunction::LINEAR, ActivationFunction::LU_BOUNDED_RELU, ActivationFunction::TANH).
Definition at line 1508 of file Types.h.
         : _act(f), _a(a), _b(b), _enabled(true)
     {
     }
Member Function Documentation
a()
float a () const inline
Get the alpha value.
Definition at line 1518 of file Types.h.
     {
         return _a;
     }
Referenced by ClActivationKernel::configure(), ClMulKernel::configure(), CLBatchNormalizationLayerKernel::configure(), CLGEMMMatrixMultiplyKernel::configure(), CLWinogradOutputTransformKernel::configure(), ClComplexMulKernel::configure(), arm_compute::cpu::fp32_neon_activation(), arm_compute::get_quantized_activation_min_max(), arm_compute::utils::info_helpers::is_relu6(), arm_compute::cpu::qasymm8_neon_activation(), arm_compute::cpu::qasymm8_signed_neon_activation(), arm_compute::cpu::qsymm16_neon_activation(), and CLGEMMConvolutionLayer::validate().
activation()
ActivationFunction activation () const inline
Get the type of activation function.
Definition at line 1513 of file Types.h.
     {
         return _act;
     }
Referenced by ClActivationKernel::configure(), ClMulKernel::configure(), CLBatchNormalizationLayerKernel::configure(), CLGEMMMatrixMultiplyKernel::configure(), CLWinogradOutputTransformKernel::configure(), ClComplexMulKernel::configure(), arm_compute::graph::backends::detail::create_batch_normalization_layer(), arm_compute::graph::backends::detail::create_convolution_layer(), arm_compute::graph::backends::detail::create_depthwise_convolution_layer(), arm_compute::graph::backends::detail::create_fused_convolution_batch_normalization_layer(), arm_compute::graph::backends::detail::create_fused_depthwise_convolution_batch_normalization_layer(), arm_compute::cpu::fp32_neon_activation(), arm_compute::cpu::fp32_neon_batch_normalization(), arm_compute::get_quantized_activation_min_max(), arm_compute::utils::info_helpers::is_relu(), arm_compute::utils::info_helpers::is_relu6(), arm_compute::cpu::qasymm8_neon_activation(), arm_compute::cpu::qasymm8_signed_neon_activation(), arm_compute::cpu::qsymm16_neon_activation(), NEFullyConnectedLayer::validate(), CLFullyConnectedLayer::validate(), CLGEMMConvolutionLayer::validate(), and DotGraphVisitor::visit().
b()
float b () const inline
Get the beta value.
Definition at line 1523 of file Types.h.
     {
         return _b;
     }
Referenced by ClActivationKernel::configure(), ClMulKernel::configure(), CLBatchNormalizationLayerKernel::configure(), CLGEMMMatrixMultiplyKernel::configure(), CLWinogradOutputTransformKernel::configure(), ClComplexMulKernel::configure(), arm_compute::cpu::fp32_neon_activation(), arm_compute::get_quantized_activation_min_max(), arm_compute::utils::info_helpers::is_relu6(), arm_compute::cpu::qasymm8_neon_activation(), arm_compute::cpu::qasymm8_signed_neon_activation(), arm_compute::cpu::qsymm16_neon_activation(), and CLGEMMConvolutionLayer::validate().
enabled()
bool enabled () const inline
Check if initialised.
Definition at line 1528 of file Types.h.
     {
         return _enabled;
     }
Referenced by arm_compute::test::validation::reference::batch_normalization_layer(), ClDirectConvolution::configure(), NEBatchNormalizationLayerKernel::configure(), ClMulKernel::configure(), FusedDepthwiseConvolutionBatchNormalizationFunction< TargetInfo, FusedLayerTypes >::configure(), CpuDirectConvolution::configure(), CLBatchNormalizationLayerKernel::configure(), CLGEMMMatrixMultiplyKernel::configure(), CLWinogradOutputTransformKernel::configure(), NEWinogradConvolutionLayer::configure(), NEFFTConvolutionLayer::configure(), ClComplexMulKernel::configure(), NEGEMM::configure(), NEGEMMLowpMatrixMultiplyCore::configure(), arm_compute::graph::backends::detail::create_batch_normalization_layer(), arm_compute::graph::backends::detail::create_convolution_layer(), arm_compute::graph::backends::detail::create_depthwise_convolution_layer(), arm_compute::graph::backends::detail::create_fused_convolution_batch_normalization_layer(), arm_compute::graph::backends::detail::create_fused_depthwise_convolution_batch_normalization_layer(), arm_compute::cpu::fp32_neon_batch_normalization(), arm_compute::utils::info_helpers::is_relu(), arm_compute::utils::info_helpers::is_relu6(), CpuActivationKernel::run_op(), CpuAdd::validate(), CpuMul::validate(), ClDirectConvolution::validate(), CpuSub::validate(), NEElementwiseMax::validate(), CpuDirectConvolution::validate(), CpuComplexMul::validate(), NEGEMM::validate(), NEFFTConvolutionLayer::validate(), NEGEMMLowpMatrixMultiplyCore::validate(), CLFFTConvolutionLayer::validate(), NEElementwiseMin::validate(), NEFullyConnectedLayer::validate(), ClSaturatedArithmeticKernel::validate(), CLFullyConnectedLayer::validate(), ClArithmeticKernel::validate(), NEElementwiseSquaredDiff::validate(), NEElementwiseDivision::validate(), CLGEMMConvolutionLayer::validate(), NEElementwisePower::validate(), and DotGraphVisitor::visit().
The documentation for this class was generated from the following file:
arm_compute/core/Types.h