Compute Library: CpuDepthwiseConvolutionAssemblyDispatch Class Reference
CpuDepthwiseConvolutionAssemblyDispatch Class Reference
Depthwise convolution assembly kernel glue.
#include <CpuDepthwiseConvolutionAssemblyDispatch.h>
Public Member Functions
CpuDepthwiseConvolutionAssemblyDispatch ()
CpuDepthwiseConvolutionAssemblyDispatch (const CpuDepthwiseConvolutionAssemblyDispatch &)=delete
Prevent instances of this class from being copied (As this class contains pointers)
CpuDepthwiseConvolutionAssemblyDispatch (CpuDepthwiseConvolutionAssemblyDispatch &&)=default
Default move constructor.
CpuDepthwiseConvolutionAssemblyDispatch & operator= (const CpuDepthwiseConvolutionAssemblyDispatch &)=delete
Prevent instances of this class from being copied (As this class contains pointers)
CpuDepthwiseConvolutionAssemblyDispatch & operator= (CpuDepthwiseConvolutionAssemblyDispatch &&)=default
Default move assignment operator.
~CpuDepthwiseConvolutionAssemblyDispatch ()
Default destructor.
void configure (const ITensorInfo *input, const ITensorInfo *weights, const ITensorInfo *bias, ITensorInfo *output, const ConvolutionInfo &info)
Initialize the function's source, destination, kernels and border_size.
void run (ITensorPack &tensors) override
Run the kernels contained in the function.
void prepare (ITensorPack &tensors) override
Prepare the function for executing.
experimental::MemoryRequirements workspace () const override
Return the memory requirements required by the workspace.
Public Member Functions inherited from INEOperator
INEOperator (IRuntimeContext *ctx=nullptr)
Constructor.
INEOperator (const INEOperator &)=delete
Prevent instances of this class from being copied (As this class contains pointers)
INEOperator (INEOperator &&)=default
Default move constructor.
INEOperator & operator= (const INEOperator &)=delete
Prevent instances of this class from being copied (As this class contains pointers)
INEOperator & operator= (INEOperator &&)=default
Default move assignment operator.
~INEOperator ()
Default destructor.
Public Member Functions inherited from IOperator
virtual ~IOperator ()=default
Destructor.
Static Public Member Functions
static Status validate (const ITensorInfo *input, const ITensorInfo *weights, const ITensorInfo *bias, const ITensorInfo *output, const ConvolutionInfo &info)
Static function to check if given info will lead to a valid configuration of CpuDepthwiseConvolutionAssemblyDispatch.
static bool is_optimized_supported (const ITensorInfo *input, const ITensorInfo *weights, const ConvolutionInfo &info)
Check if the optimized kernel can be used for the given kernel sizes and strides.
Detailed Description
Depthwise convolution assembly kernel glue.
Definition at line 34 of file CpuDepthwiseConvolutionAssemblyDispatch.h.
Constructor & Destructor Documentation
CpuDepthwiseConvolutionAssemblyDispatch() [1/3]
CpuDepthwiseConvolutionAssemblyDispatch ()
CpuDepthwiseConvolutionAssemblyDispatch() [2/3]
CpuDepthwiseConvolutionAssemblyDispatch (const CpuDepthwiseConvolutionAssemblyDispatch &) delete
Prevent instances of this class from being copied (As this class contains pointers)
CpuDepthwiseConvolutionAssemblyDispatch() [3/3]
CpuDepthwiseConvolutionAssemblyDispatch (CpuDepthwiseConvolutionAssemblyDispatch &&) default
Default move constructor.
~CpuDepthwiseConvolutionAssemblyDispatch()
~CpuDepthwiseConvolutionAssemblyDispatch () default
Default destructor.
Member Function Documentation
configure()
void configure (const ITensorInfo * input, const ITensorInfo * weights, const ITensorInfo * bias, ITensorInfo * output, const ConvolutionInfo & info)
Initialize the function's source, destination, kernels and border_size.
Note
Supports only NHWC format
Parameters
[in] input Source tensor info. Data type supported: QASYMM8/F16/F32. (Written to only for border filling).
[in] weights Weights tensor info. These are 3D tensors with shape [W, H, IFM]. Data type supported: Same as input.
[in] bias (Optional) Biases tensor info. A 1D tensor with shape [IFM]. Must be nullptr if not needed. Data type supported: Same as input.
[out] output Destination tensor info. Data type supported: same as input.
[in] info Depthwise convolution meta-data.
Definition at line 347 of file CpuDepthwiseConvolutionAssemblyDispatch.cpp.
 {
     ARM_COMPUTE_ERROR_ON_NULLPTR(input, weights, output);
     ARM_COMPUTE_UNUSED(bias);
     ARM_COMPUTE_ERROR_THROW_ON(CpuDepthwiseConvolutionAssemblyDispatch::validate(input,
                                                                                  weights,
                                                                                  bias != nullptr ? bias : nullptr,
                                                                                  output,
                                                                                  info));
     // Output auto inizialitation if not yet initialized
     const TensorShape output_shape = misc::shape_calculator::compute_depthwise_convolution_shape(*input, *weights, info);
     auto_init_if_empty(*output, input->clone()->set_is_resizable(true).reset_padding().set_tensor_shape(output_shape).set_quantization_info(output->quantization_info()));
     _pImpl->is_prepared = false;
     // Create convolver
     _pImpl->dwc_assembly_kernel = create_convolver(input, weights, output, info);
     ARM_COMPUTE_ERROR_ON(_pImpl->dwc_assembly_kernel == nullptr);
     // Create assembly kernel wrapper
     _pImpl->dwc_acl_kernel.configure(_pImpl->dwc_assembly_kernel.get());
     constexpr size_t alignment = 128;
     // Create workspace
     const unsigned int num_threads    = NEScheduler::get().num_threads();
     const size_t       workspace_size = _pImpl->dwc_assembly_kernel->get_working_space_size(num_threads);
     ARM_COMPUTE_ERROR_ON_MSG(workspace_size == 0, "Workspace size cannot be 0 !");
     _pImpl->mem_req.push_back({ TensorType::ACL_INT_0, workspace_size, alignment });
     // Create packing tensor
     const size_t pack_tensor_size = _pImpl->dwc_assembly_kernel->get_packed_params_size();
     ARM_COMPUTE_ERROR_ON_MSG(pack_tensor_size == 0, "Pack tensor size cannot be 0 !");
     _pImpl->mem_req.push_back({ TensorType::ACL_INT_1, pack_tensor_size, alignment });
 }
References arm_compute::ACL_INT_0, arm_compute::ACL_INT_1, ARM_COMPUTE_ERROR_ON, ARM_COMPUTE_ERROR_ON_MSG, ARM_COMPUTE_ERROR_ON_NULLPTR, ARM_COMPUTE_ERROR_THROW_ON, ARM_COMPUTE_UNUSED, arm_compute::auto_init_if_empty(), arm_compute::misc::shape_calculator::compute_depthwise_convolution_shape(), Scheduler::get(), arm_compute::test::validation::info, arm_compute::test::validation::input, IScheduler::num_threads(), arm_compute::test::validation::output_shape, ITensorInfo::quantization_info(), and CpuDepthwiseConvolutionAssemblyDispatch::validate().
is_optimized_supported()
bool is_optimized_supported (const ITensorInfo * input, const ITensorInfo * weights, const ConvolutionInfo & info) static
Check if the optimized kernel can be used for the given kernel sizes and strides.
Warning
Even if this return true the inputs and outputs might need to get permuted as the only layout supported is NHWC
Parameters
[in] input Input tensor info.
[in] weights Weights tensor info.
[in] info Depthwise convolution meta-data.
Returns
True if the assembly kernel could be used else false. Note that transformations of input/output could be needed.
Definition at line 445 of file CpuDepthwiseConvolutionAssemblyDispatch.cpp.
 {
     ARM_COMPUTE_ERROR_ON_NULLPTR(input, weights);
     // Reshape input shape if in NHWC format
     const DataLayout data_layout = input->data_layout();
     TensorShape      in_shape{ input->tensor_shape() };
     if(data_layout == DataLayout::NHWC)
     {
         in_shape.set(Window::DimX, input->tensor_shape().y());
         in_shape.set(Window::DimY, input->tensor_shape().z());
         in_shape.set(Window::DimZ, input->tensor_shape().x());
     }
     // Check data type
     const DataType input_type            = input->data_type();
     const bool     is_input_type_valid   = is_data_type_float(input_type) || input_type == DataType::QASYMM8;
     const DataType weights_type          = weights->data_type();
     const bool     is_weights_type_valid = is_data_type_float(weights_type) || weights_type == DataType::QASYMM8 || weights_type == DataType::QASYMM8_SIGNED
                                            || weights_type == DataType::QSYMM8_PER_CHANNEL;
     // Check weighs size
     std::set<unsigned int> supported_kernel_sizes = { 3, 5 };
     const unsigned int     width_idx              = get_data_layout_dimension_index(data_layout, DataLayoutDimension::WIDTH);
     const unsigned int     height_idx             = get_data_layout_dimension_index(data_layout, DataLayoutDimension::HEIGHT);
     const unsigned int     kernel_w               = weights->dimension(width_idx);
     const unsigned int     kernel_h               = weights->dimension(height_idx);
     bool                   weights_supported      = (kernel_w == kernel_h) && (supported_kernel_sizes.count(kernel_w) != 0);
     // Check for supported strides
     const auto &strides           = info.pad_stride_info.stride();
     bool        supported_strides = (strides.first == strides.second) && ((strides.first == 1) || (strides.first == 2));
     // Check for supported padding
     const auto    pad_top           = info.pad_stride_info.pad_top();
     const auto    pad_right         = info.pad_stride_info.pad_right();
     const auto    pad_bottom        = info.pad_stride_info.pad_bottom();
     const auto    pad_left          = info.pad_stride_info.pad_left();
     PadStrideInfo same_pad          = calculate_same_pad(in_shape, TensorShape(kernel_w, kernel_h), info.pad_stride_info, DataLayout::NCHW, info.dilation);
     bool          is_same_padding   = (pad_top == same_pad.pad_top()) && (pad_right == same_pad.pad_right()) && (pad_bottom == same_pad.pad_bottom()) && (pad_left == same_pad.pad_left());
     bool          is_valid_padding  = (pad_top == 0) && (pad_right == 0) && (pad_bottom == 0) && (pad_left == 0);
     bool          supported_padding = is_same_padding || is_valid_padding;
     // TODO(COMPMID-2464): Enable once dilated conv with stride 2 is supported
     bool is_dilation_supported = ((info.dilation == Size2D(1U, 1U)) || ((info.dilation.x() == info.dilation.y()) && strides.first == 1));
     if(weights_type == DataType::QSYMM8_PER_CHANNEL)
     {
         is_dilation_supported = is_dilation_supported && (info.dilation == Size2D(1U, 1U));
     }
     return is_input_type_valid && is_weights_type_valid && weights_supported && supported_strides && supported_padding && (info.depth_multiplier == 1) && is_dilation_supported;
 }
References ARM_COMPUTE_ERROR_ON_NULLPTR, arm_compute::calculate_same_pad(), arm_compute::test::validation::data_layout, ITensorInfo::data_type(), ITensorInfo::dimension(), Window::DimX, Window::DimY, Window::DimZ, arm_compute::get_data_layout_dimension_index(), arm_compute::HEIGHT, arm_compute::test::validation::info, arm_compute::test::validation::input, arm_compute::is_data_type_float(), arm_compute::NCHW, arm_compute::NHWC, PadStrideInfo::pad_bottom(), PadStrideInfo::pad_left(), PadStrideInfo::pad_right(), PadStrideInfo::pad_top(), arm_compute::QASYMM8, arm_compute::QASYMM8_SIGNED, arm_compute::QSYMM8_PER_CHANNEL, arm_compute::utils::cast::U, and arm_compute::WIDTH.
Referenced by CpuDepthwiseConvolutionAssemblyDispatch::validate().
operator=() [1/2]
CpuDepthwiseConvolutionAssemblyDispatch& operator= (const CpuDepthwiseConvolutionAssemblyDispatch &) delete
Prevent instances of this class from being copied (As this class contains pointers)
operator=() [2/2]
CpuDepthwiseConvolutionAssemblyDispatch& operator= (CpuDepthwiseConvolutionAssemblyDispatch &&) default
Default move assignment operator.
prepare()
void prepare (ITensorPack & constants) override virtual
Prepare the function for executing.
Any one off pre-processing step required by the function is handled here
Parameters
[in] constants Vector that contains the constants tensors.
Note
Prepare stage might not need all the function's buffers' backing memory to be available in order to execute
Reimplemented from INEOperator.
Definition at line 533 of file CpuDepthwiseConvolutionAssemblyDispatch.cpp.
 {
     if(!_pImpl->is_prepared)
     {
         auto weights        = tensors.get_const_tensor(TensorType::ACL_SRC_1);
         auto bias           = tensors.get_const_tensor(TensorType::ACL_SRC_2);
         auto packed_weights = tensors.get_tensor(TensorType::ACL_INT_1);
         ARM_COMPUTE_ERROR_ON(packed_weights->buffer() == nullptr);
         // Pack weights and bias
         const int weights_element_size = weights->info()->element_size();
         const int weights_row_stride   = weights->info()->strides_in_bytes().z() / weights_element_size;
         const int weights_col_stride   = weights->info()->strides_in_bytes().y() / weights_element_size;
         _pImpl->dwc_assembly_kernel->pack_params(packed_weights->buffer(),
                                                  weights->buffer() + weights->info()->offset_first_element_in_bytes(),
                                                  weights_row_stride,
                                                  weights_col_stride,
                                                  (bias != nullptr) ? bias->buffer() : nullptr);
         _pImpl->dwc_assembly_kernel->set_packed_params_buffer(packed_weights->buffer());
         weights->mark_as_unused();
         if(bias != nullptr)
         {
             bias->mark_as_unused();
         }
         _pImpl->is_prepared = true;
     }
 }
References arm_compute::ACL_INT_1, arm_compute::ACL_SRC_1, arm_compute::ACL_SRC_2, ARM_COMPUTE_ERROR_ON, ITensorPack::get_const_tensor(), and ITensorPack::get_tensor().
Referenced by CpuDepthwiseConvolutionAssemblyDispatch::run().
run()
void run (ITensorPack & tensors) override virtual
Run the kernels contained in the function.
Parameters
[in] tensors Vector that contains the tensors to operate on.
Reimplemented from INEOperator.
Definition at line 500 of file CpuDepthwiseConvolutionAssemblyDispatch.cpp.
 {
     // Prepare assembly kernel
     prepare(tensors);
     auto src       = tensors.get_tensor(TensorType::ACL_SRC_0);
     auto workspace = tensors.get_tensor(TensorType::ACL_INT_0);
     auto dst       = tensors.get_tensor(TensorType::ACL_DST);
     // Setup inputs/outputs
     ARM_COMPUTE_ERROR_ON(workspace == nullptr && workspace->buffer() == nullptr);
     _pImpl->dwc_assembly_kernel->set_working_space(static_cast<void *>(workspace->buffer()));
     ARM_COMPUTE_ERROR_ON(workspace->buffer() == nullptr);
     const int   input_element_size = src->info()->element_size();
     const int   input_batch_stride = src->info()->strides_in_bytes()[3] / input_element_size;
     const int   input_row_stride   = src->info()->strides_in_bytes().z() / input_element_size;
     const int   input_col_stride   = src->info()->strides_in_bytes().y() / input_element_size;
     const void *input_ptr          = src->buffer() + src->info()->offset_first_element_in_bytes();
     _pImpl->dwc_assembly_kernel->set_input(input_ptr, input_batch_stride, input_row_stride, input_col_stride);
     ARM_COMPUTE_ERROR_ON(dst->buffer() == nullptr);
     const int output_element_size = dst->info()->element_size();
     const int output_batch_stride = dst->info()->strides_in_bytes()[3] / output_element_size;
     const int output_row_stride   = dst->info()->strides_in_bytes().z() / output_element_size;
     const int output_col_stride   = dst->info()->strides_in_bytes().y() / output_element_size;
     void     *output_ptr          = dst->buffer() + dst->info()->offset_first_element_in_bytes();
     _pImpl->dwc_assembly_kernel->set_output(output_ptr, output_batch_stride, output_row_stride, output_col_stride);
     // Schedule assembly kernel
     NEScheduler::get().schedule(&_pImpl->dwc_acl_kernel, Window::DimX);
 }
References arm_compute::ACL_DST, arm_compute::ACL_INT_0, arm_compute::ACL_SRC_0, ARM_COMPUTE_ERROR_ON, Window::DimX, arm_compute::test::validation::dst, Scheduler::get(), ITensorPack::get_tensor(), CpuDepthwiseConvolutionAssemblyDispatch::prepare(), IScheduler::schedule(), arm_compute::test::validation::src, and CpuDepthwiseConvolutionAssemblyDispatch::workspace().
validate()
Status validate (const ITensorInfo * input, const ITensorInfo * weights, const ITensorInfo * bias, const ITensorInfo * output, const ConvolutionInfo & info) static
Static function to check if given info will lead to a valid configuration of CpuDepthwiseConvolutionAssemblyDispatch.
Note
Supports only NHWC format
Parameters
[in] input Source tensor info. Data type supported: QASYMM8/F16/F32. (Written to only for border filling).
[in] weights Weights tensor info. These are 3D tensors with shape [W, H, IFM]. Data type supported: Same as input.
[in] bias (Optional) Biases tensor info. A 1D tensor with shape [IFM]. Must be nullptr if not needed. Data type supported: Same as input.
[out] output Destination tensor info. Data type supported: same as input.
[in] info Depthwise convolution meta-data.
Returns
An error status
Definition at line 394 of file CpuDepthwiseConvolutionAssemblyDispatch.cpp.
 {
     ARM_COMPUTE_RETURN_ERROR_ON_CPU_F16_UNSUPPORTED(input);
     ARM_COMPUTE_RETURN_ERROR_ON_DATA_TYPE_CHANNEL_NOT_IN(input, 1, DataType::QASYMM8, DataType::F16, DataType::F32);
     if(weights->data_type() != DataType::QSYMM8_PER_CHANNEL)
     {
         ARM_COMPUTE_RETURN_ERROR_ON_MISMATCHING_DATA_TYPES(input, weights);
     }
     ARM_COMPUTE_RETURN_ERROR_ON_MISMATCHING_DATA_LAYOUT(input, weights);
     // Validate convolver
     ARM_COMPUTE_RETURN_ERROR_ON(!is_optimized_supported(input, weights, info));
     // Validate activation
     const bool is_relu  = arm_compute::utils::info_helpers::is_relu(info.act_info);
     const bool is_relu6 = arm_compute::utils::info_helpers::is_relu6(info.act_info);
     ARM_COMPUTE_RETURN_ERROR_ON(info.act_info.enabled() && !(is_relu || is_relu6));
     // Check bias
     if(bias != nullptr)
     {
         unsigned int channel_idx = get_data_layout_dimension_index(input->data_layout(), DataLayoutDimension::CHANNEL);
         ARM_COMPUTE_RETURN_ERROR_ON(bias->num_dimensions() > 1);
         ARM_COMPUTE_RETURN_ERROR_ON(bias->dimension(0) != weights->dimension(channel_idx));
     }
     // Check output
     if(output->total_size() != 0)
     {
         const TensorShape output_shape = misc::shape_calculator::compute_depthwise_convolution_shape(*input, *weights, info);
         ARM_COMPUTE_RETURN_ERROR_ON_MISMATCHING_DIMENSIONS(output->tensor_shape(), output_shape);
         ARM_COMPUTE_RETURN_ERROR_ON_MISMATCHING_DATA_TYPES(input, output);
     }
     // The uniform quantization case will only have 1 scale value in the weights quantization info
     const UniformQuantizationInfo input_qinfo   = input->quantization_info().uniform();
     const QuantizationInfo        weights_qinfo = weights->quantization_info();
     const UniformQuantizationInfo output_qinfo  = output->quantization_info().uniform();
     for(auto const s : weights_qinfo.scale())
     {
         const float fmultipler = input_qinfo.scale * s / output_qinfo.scale;
         ARM_COMPUTE_RETURN_ERROR_ON(fmultipler > 1.f);
     }
     return Status{};
 }
References ARM_COMPUTE_RETURN_ERROR_ON, ARM_COMPUTE_RETURN_ERROR_ON_CPU_F16_UNSUPPORTED, ARM_COMPUTE_RETURN_ERROR_ON_DATA_TYPE_CHANNEL_NOT_IN, ARM_COMPUTE_RETURN_ERROR_ON_MISMATCHING_DATA_LAYOUT, ARM_COMPUTE_RETURN_ERROR_ON_MISMATCHING_DATA_TYPES, ARM_COMPUTE_RETURN_ERROR_ON_MISMATCHING_DIMENSIONS, arm_compute::CHANNEL, arm_compute::misc::shape_calculator::compute_depthwise_convolution_shape(), ITensorInfo::data_type(), ITensorInfo::dimension(), arm_compute::F16, arm_compute::F32, arm_compute::get_data_layout_dimension_index(), arm_compute::test::validation::info, arm_compute::test::validation::input, CpuDepthwiseConvolutionAssemblyDispatch::is_optimized_supported(), arm_compute::utils::info_helpers::is_relu(), arm_compute::utils::info_helpers::is_relu6(), ITensorInfo::num_dimensions(), arm_compute::test::validation::output_shape, arm_compute::QASYMM8, arm_compute::QSYMM8_PER_CHANNEL, ITensorInfo::quantization_info(), UniformQuantizationInfo::scale, QuantizationInfo::scale(), ITensorInfo::tensor_shape(), ITensorInfo::total_size(), and QuantizationInfo::uniform().
Referenced by CpuDepthwiseConvolutionAssemblyDispatch::configure().
workspace()
experimental::MemoryRequirements workspace () const override virtual
Return the memory requirements required by the workspace.
Reimplemented from INEOperator.
Definition at line 389 of file CpuDepthwiseConvolutionAssemblyDispatch.cpp.
 {
     return _pImpl->mem_req;
 }
Referenced by CpuDepthwiseConvolutionAssemblyDispatch::run().
The documentation for this class was generated from the following files:
src/runtime/cpu/operators/CpuDepthwiseConvolutionAssemblyDispatch.h
src/runtime/cpu/operators/CpuDepthwiseConvolutionAssemblyDispatch.cpp