Compute Library: CpuConcatenateHeightKernel Class Reference
CpuConcatenateHeightKernel Class Reference
Interface for the height concatenate kernel.
#include <CpuConcatenateHeightKernel.h>
Public Member Functions
CpuConcatenateHeightKernel ()
ARM_COMPUTE_DISALLOW_COPY_ALLOW_MOVE (CpuConcatenateHeightKernel)
void configure (const ITensorInfo *src, unsigned int height_offset, ITensorInfo *dst)
Configure kernel for a given list of arguments.
void run_op (ITensorPack &tensors, const Window &window, const ThreadInfo &info) override
Execute the kernel on the passed window.
const char * name () const override
Name of the kernel.
Public Member Functions inherited from ICPPKernel
virtual ~ICPPKernel ()=default
Default destructor.
virtual void run (const Window &window, const ThreadInfo &info)
Execute the kernel on the passed window.
virtual void run_nd (const Window &window, const ThreadInfo &info, const Window &thread_locator)
legacy compatibility layer for implemantions which do not support thread_locator In these cases we simply narrow the interface down the legacy version
Public Member Functions inherited from IKernel
IKernel ()
Constructor.
virtual ~IKernel ()=default
Destructor.
virtual bool is_parallelisable () const
Indicates whether or not the kernel is parallelisable.
virtual BorderSize border_size () const
The size of the border for that kernel.
const Window & window () const
The maximum window the kernel can be executed on.
bool is_window_configured () const
Function to check if the embedded window of this kernel has been configured.
Static Public Member Functions
static Status validate (const ITensorInfo *src, unsigned int height_offset, const ITensorInfo *dst)
Static function to check if given info will lead to a valid configuration of CpuConcatenateHeightKernel.
Detailed Description
Interface for the height concatenate kernel.
The source tensor will be concatenated into the destination tensor.
Definition at line 39 of file CpuConcatenateHeightKernel.h.
Constructor & Destructor Documentation
CpuConcatenateHeightKernel()
CpuConcatenateHeightKernel ()
Definition at line 65 of file CpuConcatenateHeightKernel.cpp.
     : _height_offset(0)
 {
 }
Member Function Documentation
ARM_COMPUTE_DISALLOW_COPY_ALLOW_MOVE()
ARM_COMPUTE_DISALLOW_COPY_ALLOW_MOVE (CpuConcatenateHeightKernel)
configure()
void configure (const ITensorInfo * src, unsigned int height_offset, ITensorInfo * dst)
Configure kernel for a given list of arguments.
Parameters
[in] src Source tensor info. Data types supported: All
[in] height_offset The starting offset on the Y axis for the output tensor.
[in,out] dst Destination tensor info. Data types supported: Same as src.
Definition at line 70 of file CpuConcatenateHeightKernel.cpp.
 {
     ARM_COMPUTE_UNUSED(src);
     ARM_COMPUTE_ERROR_ON_NULLPTR(src, dst);
     ARM_COMPUTE_ERROR_THROW_ON(validate_arguments(src, height_offset, dst));
     _height_offset = height_offset;
     // Configure kernel window
     Window win = calculate_max_window(*dst, Steps());
     ICpuKernel::configure(win);
 }
References ARM_COMPUTE_ERROR_ON_NULLPTR, ARM_COMPUTE_ERROR_THROW_ON, ARM_COMPUTE_UNUSED, arm_compute::calculate_max_window(), arm_compute::test::validation::dst, arm_compute::test::validation::src, and arm_compute::validate_arguments().
name()
const char * name () const override virtual
Name of the kernel.
Returns
Kernel name
Implements ICPPKernel.
Definition at line 177 of file CpuConcatenateHeightKernel.cpp.
 {
     return "CpuConcatenateHeightKernel";
 }
run_op()
void run_op (ITensorPack & tensors, const Window & window, const ThreadInfo & info) override virtual
Execute the kernel on the passed window.
Warning
If is_parallelisable() returns false then the passed window must be equal to window()
Note
The window has to be a region within the window returned by the window() method
The width of the window has to be a multiple of num_elems_processed_per_iteration().
Parameters
[in] tensors A vector containing the tensors to operate on.
[in] window Region on which to execute the kernel. (Must be a region of the window returned by window())
[in] info Info about executing thread and CPU.
Reimplemented from ICPPKernel.
Definition at line 89 of file CpuConcatenateHeightKernel.cpp.
 {
     ARM_COMPUTE_UNUSED(info);
     ARM_COMPUTE_ERROR_ON_UNCONFIGURED_KERNEL(this);
     ARM_COMPUTE_ERROR_ON_INVALID_SUBWINDOW(ICpuKernel::window(), window);
     const auto src = tensors.get_const_tensor(TensorType::ACL_SRC);
     auto       dst = tensors.get_tensor(TensorType::ACL_DST);
     // Offset destination pointer to the correct position
     uint8_t *dst_ptr = dst->buffer() + dst->info()->offset_first_element_in_bytes() + _height_offset * dst->info()->strides_in_bytes()[Window::DimY];
     const auto window_start_x = static_cast<int>(window.x().start());
     const auto window_end_x   = static_cast<int>(window.x().end()) * static_cast<int>(dst->info()->element_size());
     const int  window_step_x  = 16;
     Window win{ window };
     win.set(Window::DimX, Window::Dimension(0, 1, 1));
     win.set(Window::DimY, Window::Dimension(0, src->info()->tensor_shape().y(), 1));
     // Create iterators
     Iterator src_it(src, win);
     Iterator dst_it(dst, win);
     const DataType                 dt        = src->info()->data_type();
     const UniformQuantizationInfo &src_qinfo = src->info()->quantization_info().uniform();
     const UniformQuantizationInfo &dst_qinfo = dst->info()->quantization_info().uniform();
     if(dt == DataType::QASYMM8 && src_qinfo != dst_qinfo)
     {
         execute_window_loop(win, [&](const Coordinates &)
         {
             int x = window_start_x;
             for(; x <= (window_end_x - window_step_x); x += window_step_x)
             {
                 vst1q_u8(dst_ptr + dst_it.offset() + x, vquantize(vdequantize(vld1q_u8(src_it.ptr() + x), src_qinfo), dst_qinfo));
             }
             // Compute left-over elements
             for(; x < window_end_x; ++x)
             {
                 *(dst_ptr + dst_it.offset() + x) = quantize_qasymm8(dequantize_qasymm8(*(src_it.ptr() + x), src_qinfo), dst_qinfo);
             }
         },
         src_it, dst_it);
     }
     else if(dt == DataType::QASYMM8_SIGNED && src_qinfo != dst_qinfo)
     {
         execute_window_loop(win, [&](const Coordinates &)
         {
             int x = window_start_x;
             for(; x <= (window_end_x - window_step_x); x += window_step_x)
             {
                 vst1q_s8(reinterpret_cast<int8_t *>(dst_ptr + dst_it.offset() + x),
                          vquantize_signed(vdequantize(vld1q_s8(reinterpret_cast<int8_t *>(src_it.ptr()) + x), src_qinfo), dst_qinfo));
             }
             // Compute left-over elements
             for(; x < window_end_x; ++x)
             {
                 *(dst_ptr + dst_it.offset() + x) = quantize_qasymm8_signed(dequantize_qasymm8_signed(*(src_it.ptr() + x), src_qinfo), dst_qinfo);
             }
         },
         src_it, dst_it);
     }
     else
     {
         execute_window_loop(win, [&](const Coordinates &)
         {
             const auto in_ptr  = src_it.ptr();
             const auto out_ptr = dst_ptr + dst_it.offset();
             int x = window_start_x;
             for(; x <= (window_end_x - window_step_x); x += window_step_x)
             {
                 wrapper::vstore(out_ptr + x, wrapper::vloadq(in_ptr + x));
             }
             // Compute left-over elements
             for(; x < window_end_x; ++x)
             {
                 *(out_ptr + x) = *(in_ptr + x);
             }
         },
         src_it, dst_it);
     }
 }
References arm_compute::ACL_DST, arm_compute::ACL_SRC, ARM_COMPUTE_ERROR_ON_INVALID_SUBWINDOW, ARM_COMPUTE_ERROR_ON_UNCONFIGURED_KERNEL, ARM_COMPUTE_UNUSED, arm_compute::dequantize_qasymm8(), arm_compute::dequantize_qasymm8_signed(), Window::DimX, Window::DimY, arm_compute::test::validation::dst, dt, Window::Dimension::end(), arm_compute::execute_window_loop(), ITensorPack::get_const_tensor(), ITensorPack::get_tensor(), arm_compute::test::validation::info, Iterator::offset(), Iterator::ptr(), arm_compute::QASYMM8, arm_compute::QASYMM8_SIGNED, arm_compute::quantize_qasymm8(), arm_compute::quantize_qasymm8_signed(), Window::set(), arm_compute::test::validation::src, Window::Dimension::start(), arm_compute::vdequantize(), arm_compute::wrapper::vloadq(), arm_compute::vquantize(), arm_compute::vquantize_signed(), arm_compute::wrapper::vstore(), IKernel::window(), and Window::x().
validate()
Status validate (const ITensorInfo * src, unsigned int height_offset, const ITensorInfo * dst) static
Static function to check if given info will lead to a valid configuration of CpuConcatenateHeightKernel.
Parameters
[in] src Source tensor info. Data types supported: All
[in] height_offset The starting offset on the Y axis for the output tensor.
[in] dst Destination tensor info. Data types supported: Same as src.
Returns
a status
Definition at line 83 of file CpuConcatenateHeightKernel.cpp.
 {
     ARM_COMPUTE_RETURN_ON_ERROR(validate_arguments(src, height_offset, dst));
     return Status{};
 }
References ARM_COMPUTE_RETURN_ON_ERROR, arm_compute::test::validation::dst, arm_compute::test::validation::src, and arm_compute::validate_arguments().
Referenced by CpuConcatenate::validate().
The documentation for this class was generated from the following files:
src/core/cpu/kernels/CpuConcatenateHeightKernel.h
src/core/cpu/kernels/CpuConcatenateHeightKernel.cpp