Compute Library: CLFullyConnectedLayer Class Reference
CLFullyConnectedLayer Class Reference
Basic function to compute a Fully Connected layer on OpenCL.
#include <CLFullyConnectedLayer.h>
Public Member Functions
CLFullyConnectedLayer (std::shared_ptr< IMemoryManager > memory_manager=nullptr, IWeightsManager *weights_manager=nullptr)
Constructor.
CLFullyConnectedLayer (const CLFullyConnectedLayer &)=delete
Prevent instances of this class from being copied (As this class contains pointers)
CLFullyConnectedLayer (CLFullyConnectedLayer &&)=default
Default move constructor.
CLFullyConnectedLayer & operator= (const CLFullyConnectedLayer &)=delete
Prevent instances of this class from being copied (As this class contains pointers)
CLFullyConnectedLayer & operator= (CLFullyConnectedLayer &&)=default
Default move assignment operator.
void configure (const ICLTensor *input, const ICLTensor *weights, const ICLTensor *biases, ICLTensor *output, FullyConnectedLayerInfo fc_info=FullyConnectedLayerInfo())
Set the input and output tensors.
void configure (const CLCompileContext &compile_context, const ICLTensor *input, const ICLTensor *weights, const ICLTensor *biases, ICLTensor *output, FullyConnectedLayerInfo fc_info=FullyConnectedLayerInfo())
Set the input and output tensors.
void run () override
Run the kernels contained in the function.
void prepare () override
Prepare the function for executing.
Public Member Functions inherited from IFunction
virtual ~IFunction ()=default
Destructor.
Static Public Member Functions
static Status validate (const ITensorInfo *input, const ITensorInfo *weights, const ITensorInfo *biases, const ITensorInfo *output, FullyConnectedLayerInfo fc_info=FullyConnectedLayerInfo())
Static function to check if given info will lead to a valid configuration of CLFullyConnectedLayer.
Detailed Description
Basic function to compute a Fully Connected layer on OpenCL.
This function calls the following OpenCL kernels:
CLIm2ColKernel (called when the input comes from a convolutional layer)
CLTranspose (if are_weights_reshaped is set to false and transpose_weights is set to true) (called once)
CLGEMMMatrixMultiplyKernel or CLGEMMLowpMatrixMultiplyCore (if quantized asymmetric)
Note
The fully connected layer accepts "weights" tensors only with 2 dimensions.
Definition at line 105 of file CLFullyConnectedLayer.h.
Constructor & Destructor Documentation
CLFullyConnectedLayer() [1/3]
CLFullyConnectedLayer (std::shared_ptr< IMemoryManager > memory_manager = nullptr, IWeightsManager * weights_manager = nullptr)
Constructor.
Definition at line 144 of file CLFullyConnectedLayer.cpp.
     : _memory_group(memory_manager), _weights_manager(weights_manager), _convert_weights(), _convert_weights_managed(), _reshape_weights_managed_function(), _flatten_layer(), _reshape_weights_function(),
       _mm_gemm(memory_manager, weights_manager), _mm_gemmlowp(memory_manager), _flatten_output(), _converted_weights_output(), _reshape_weights_output(), _are_weights_converted(true),
       _are_weights_reshaped(true), _is_fc_after_conv(true), _is_quantized(false), _is_prepared(false), _original_weights(nullptr)
 {
 }
CLFullyConnectedLayer() [2/3]
CLFullyConnectedLayer (const CLFullyConnectedLayer &) delete
Prevent instances of this class from being copied (As this class contains pointers)
CLFullyConnectedLayer() [3/3]
CLFullyConnectedLayer (CLFullyConnectedLayer &&) default
Default move constructor.
Member Function Documentation
configure() [1/2]
void configure (const ICLTensor * input, const ICLTensor * weights, const ICLTensor * biases, ICLTensor * output, FullyConnectedLayerInfo fc_info = FullyConnectedLayerInfo())
Set the input and output tensors.
Valid data layouts:
NHWC
NCHW
Valid data type configurations:
src0 src1 src2 dst
F16 F16 F16 F16
F32 F32 F32 F32
QASYMM8 QASYMM8 S32 QASYMM8
QASYMM8_SIGNED QASYMM8_SIGNED S32 QASYMM8_SIGNED
Parameters
[in] input Source tensor. Data type supported: QASYMM8/QASYMM8_SIGNED/F16/F32.
[in] weights Weights tensor. The weights must be 2 dimensional. If this function is called after a Convolution Layer, the (transposed) weights will have as many rows as the product of the first 3 input's dimensions. If it is called after another FullyConnected Layer, the (transposed) weights will have as many rows as the input's first dimension. Data type supported: Same as input.
[in] biases Bias tensor. Can be nullptr. Data type supported:Same as input.
[out] output Destination tensor. Its shape should be equal to the output of a matrix multiplication between:
The output of im2col on the input and the (transposed) 2D weights, if the function is called after a Convolution Layer
The input tensor and the (transposed) 2D weights, if the function is called after another FullyConnected Layer. Data type supported: Same as input.
[in] fc_info (Optional) Fully connected layer additional info
Definition at line 223 of file CLFullyConnectedLayer.cpp.
 {
     configure(CLKernelLibrary::get().get_compile_context(), input, weights, biases, output, fc_info);
 }
References CLKernelLibrary::get(), and arm_compute::test::validation::input.
Referenced by CLRNNLayer::configure(), and CLLSTMLayer::configure().
configure() [2/2]
void configure (const CLCompileContext & compile_context, const ICLTensor * input, const ICLTensor * weights, const ICLTensor * biases, ICLTensor * output, FullyConnectedLayerInfo fc_info = FullyConnectedLayerInfo())
Set the input and output tensors.
Parameters
[in] compile_context The compile context to be used.
[in] input Source tensor. Data type supported: QASYMM8/QASYMM8_SIGNED/F16/F32.
[in] weights Weights tensor. The weights must be 2 dimensional. If this function is called after a Convolution Layer, the (transposed) weights will have as many rows as the product of the first 3 input's dimensions. If it is called after another FullyConnected Layer, the (transposed) weights will have as many rows as the input's first dimension. Data type supported: Same as input.
[in] biases Bias tensor. Can be nullptr. Data type supported:Same as input.
[out] output Destination tensor. Its shape should be equal to the output of a matrix multiplication between:
The output of im2col on the input and the (transposed) 2D weights, if the function is called after a Convolution Layer
The input tensor and the (transposed) 2D weights, if the function is called after another FullyConnected Layer. Data type supported: Same as input.
[in] fc_info (Optional) Fully connected layer additional info
Definition at line 229 of file CLFullyConnectedLayer.cpp.
 {
     ARM_COMPUTE_ERROR_ON_NULLPTR(input, weights, output);
     // Perform validate step
     ARM_COMPUTE_ERROR_THROW_ON(CLFullyConnectedLayer::validate(input->info(),
                                                                weights->info(),
                                                                biases != nullptr ? biases->info() : nullptr,
                                                                output->info(),
                                                                fc_info));
     _are_weights_converted = true;
     _are_weights_reshaped  = fc_info.transpose_weights ? fc_info.are_weights_reshaped : true;
     _is_fc_after_conv      = true;
     _is_quantized          = is_data_type_quantized_asymmetric(input->info()->data_type());
     _is_prepared           = fc_info.retain_internal_weights;
     _original_weights      = weights;
     if(_weights_manager)
     {
         _weights_manager->manage(weights);
     }
     const ICLTensor *weights_to_use = weights;
     // With the Fully Connected layer we can have 4 different cases:
     //  1) Convolution layer -> Fully Connected layer without batches
     //  2) Fully Connected layer -> Fully Connected layer without batches
     //  3) Convolution layer -> Fully Connected layer with batches
     //  4) Fully Connected layer -> Fully Connected layer with batches
     // Check if we have a fully connected layer with batches
     const bool is_batched_fc_layer = output->info()->dimension(1) > 1;
     if(is_batched_fc_layer)
     {
         _is_fc_after_conv = (TensorShape::num_max_dimensions >= 4) && (std::equal(input->info()->tensor_shape().cbegin() + 3,
                                                                                   input->info()->tensor_shape().cend(),
                                                                                   output->info()->tensor_shape().cbegin() + 1));
     }
     else
     {
         _is_fc_after_conv = input->info()->num_dimensions() > 1;
     }
     // Reshape weights if needed
     if(!_are_weights_reshaped)
     {
         if(_weights_manager && _weights_manager->are_weights_managed(weights))
         {
             _reshape_weights_managed_function.configure(compile_context, weights);
             weights_to_use = utils::cast::polymorphic_downcast<ICLTensor *>(_weights_manager->acquire(weights, &_reshape_weights_managed_function));
         }
         else
         {
             // Reshape the weights
             _reshape_weights_function.configure(compile_context, weights, &_reshape_weights_output);
             weights_to_use = &_reshape_weights_output;
         }
     }
     // Convert weights if needed
     if(_is_fc_after_conv && (input->info()->data_layout() != fc_info.weights_trained_layout))
     {
         if(_weights_manager && _weights_manager->are_weights_managed(weights_to_use))
         {
             _convert_weights_managed.configure(compile_context, weights_to_use,
                                                input->info()->tensor_shape(),
                                                fc_info.weights_trained_layout);
             weights_to_use = utils::cast::polymorphic_downcast<ICLTensor *>(_weights_manager->acquire(weights, &_convert_weights_managed));
         }
         else
         {
             // Convert weights
             _convert_weights.configure(compile_context, weights_to_use,
                                        &_converted_weights_output,
                                        input->info()->tensor_shape(),
                                        fc_info.weights_trained_layout);
             weights_to_use = &_converted_weights_output;
         }
         _are_weights_converted = false;
     }
     if(_is_fc_after_conv)
     {
         // Fully Connected layer after a Convolution Layer without batches
         configure_conv_fc(compile_context, input, weights_to_use, biases, output, fc_info);
     }
     else
     {
         // Fully Connected layer after a Fully Connected Layer without batches
         configure_fc_fc(compile_context, input, weights_to_use, biases, output, fc_info);
     }
 }
References IWeightsManager::acquire(), IWeightsManager::are_weights_managed(), FullyConnectedLayerInfo::are_weights_reshaped, ARM_COMPUTE_ERROR_ON_NULLPTR, ARM_COMPUTE_ERROR_THROW_ON, Dimensions< T >::cbegin(), CLTranspose::configure(), CLConvertFullyConnectedWeights::configure(), CLFullyConnectedLayerReshapeWeightsManaged::configure(), CLConvertFullyConnectedWeightsManaged::configure(), ITensorInfo::dimension(), ITensor::info(), arm_compute::test::validation::input, arm_compute::is_data_type_quantized_asymmetric(), IWeightsManager::manage(), Dimensions< size_t >::num_max_dimensions, FullyConnectedLayerInfo::retain_internal_weights, ITensorInfo::tensor_shape(), FullyConnectedLayerInfo::transpose_weights, CLFullyConnectedLayer::validate(), and FullyConnectedLayerInfo::weights_trained_layout.
operator=() [1/2]
CLFullyConnectedLayer& operator= (const CLFullyConnectedLayer &) delete
Prevent instances of this class from being copied (As this class contains pointers)
operator=() [2/2]
CLFullyConnectedLayer& operator= (CLFullyConnectedLayer &&) default
Default move assignment operator.
prepare()
void prepare () override virtual
Prepare the function for executing.
Any one off pre-processing step required by the function is handled here
Note
Prepare stage might not need all the function's buffers' backing memory to be available in order to execute
Reimplemented from IFunction.
Definition at line 425 of file CLFullyConnectedLayer.cpp.
 {
     if(!_is_prepared)
     {
         if(!_weights_manager)
         {
             ARM_COMPUTE_ERROR_ON(!_original_weights->is_used());
         }
         auto release_unused = [](CLTensor * w)
         {
             if(!w->is_used())
             {
                 CLScheduler::get().queue().finish();
                 w->allocator()->free();
             }
         };
         // Pointer to current weights
         const ICLTensor *cur_weights = _original_weights;
         // Reshape of the weights if needed (happens only once)
         if(!_are_weights_reshaped)
         {
             if(_weights_manager && _weights_manager->are_weights_managed(_original_weights))
             {
                 cur_weights = utils::cast::polymorphic_downcast<ICLTensor *>(_weights_manager->run(cur_weights, &_reshape_weights_managed_function));
             }
             else
             {
                 // Run reshape weights kernel and mark weights as unused
                 _reshape_weights_output.allocator()->allocate();
                 _reshape_weights_function.run();
                 cur_weights->mark_as_unused();
                 cur_weights = &_reshape_weights_output;
             }
             _are_weights_reshaped = true;
         }
         // Convert weights if needed (happens only once)
         if(!_are_weights_converted)
         {
             if(_weights_manager && _weights_manager->are_weights_managed(cur_weights))
             {
                 _weights_manager->run(cur_weights, &_convert_weights_managed);
             }
             else
             {
                 _converted_weights_output.allocator()->allocate();
                 _convert_weights.run();
                 cur_weights->mark_as_unused();
             }
             _are_weights_converted = true;
         }
         // Release reshaped weights if unused
         release_unused(&_reshape_weights_output);
         // Prepare GEMM prepare and release unused weights
         if(!_is_quantized)
         {
             _mm_gemm.prepare();
         }
         // Release converted weights if unused
         release_unused(&_reshape_weights_output);
         release_unused(&_converted_weights_output);
         _is_prepared = true;
     }
 }
References CLTensorAllocator::allocate(), CLTensor::allocator(), IWeightsManager::are_weights_managed(), ARM_COMPUTE_ERROR_ON, CLScheduler::get(), ITensor::is_used(), ITensor::mark_as_unused(), CLGEMM::prepare(), CLScheduler::queue(), IWeightsManager::run(), CLTranspose::run(), CLConvertFullyConnectedWeights::run(), and arm_compute::test::validation::w.
Referenced by CLRNNLayer::prepare(), and CLFullyConnectedLayer::run().
run()
void run () override virtual
Run the kernels contained in the function.
For CPU kernels:
Multi-threading is used for the kernels which are parallelisable.
By default std::thread::hardware_concurrency() threads are used.
Note
CPPScheduler::set_num_threads() can be used to manually set the number of threads
For OpenCL kernels:
All the kernels are enqueued on the queue associated with CLScheduler.
The queue is then flushed.
Note
The function will not block until the kernels are executed. It is the user's responsibility to wait.
Will call prepare() on first run if hasn't been done
Implements IFunction.
Definition at line 402 of file CLFullyConnectedLayer.cpp.
 {
     prepare();
     MemoryGroupResourceScope scope_mg(_memory_group);
     // Linearize input if it comes from a convolutional layer
     if(_is_fc_after_conv)
     {
         _flatten_layer.run();
     }
     // Run matrix multiply
     if(_is_quantized)
     {
         _mm_gemmlowp.run();
     }
     else
     {
         _mm_gemm.run();
     }
 }
References CLFullyConnectedLayer::prepare(), CLFlattenLayer::run(), CLGEMMLowpMatrixMultiplyCore::run(), and CLGEMM::run().
Referenced by CLRNNLayer::run(), and CLLSTMLayer::run().
validate()
Status validate (const ITensorInfo * input, const ITensorInfo * weights, const ITensorInfo * biases, const ITensorInfo * output, FullyConnectedLayerInfo fc_info = FullyConnectedLayerInfo()) static
Static function to check if given info will lead to a valid configuration of CLFullyConnectedLayer.
Parameters
[in] input Source tensor info. Data type supported: QASYMM8/QASYMM8_SIGNED/F16/F32.
[in] weights Weights tensor info. The weights must be 2 dimensional. If this function is called after a Convolution Layer, the (transposed) weights will have as many rows as the product of the first 3 input's dimensions. If it is called after another FullyConnected Layer, the (transposed) weights will have as many rows as the input's first dimension. Data type supported: Same as input.
[in] biases Bias tensor info. Can be nullptr. Data type supported:Same as input.
[out] output Destination tensor info. Its shape should be equal to the output of a matrix multiplication between:
The output of im2col on the input and the (transposed) 2D weights, if the function is called after a Convolution Layer
The input tensor and the (transposed) 2D weights, if the function is called after another FullyConnected Layer. Data type supported: Same as input.
[in] fc_info (Optional) Fully connected layer additional info
Returns
a status
Definition at line 325 of file CLFullyConnectedLayer.cpp.
 {
     ARM_COMPUTE_RETURN_ERROR_ON_NULLPTR(input, weights, output);
     ARM_COMPUTE_RETURN_ERROR_ON_DATA_TYPE_CHANNEL_NOT_IN(input, 1, DataType::QASYMM8, DataType::QASYMM8_SIGNED, DataType::F16, DataType::F32);
     ARM_COMPUTE_RETURN_ERROR_ON_MISMATCHING_DATA_TYPES(input, weights, output);
     ARM_COMPUTE_RETURN_ERROR_ON(weights->num_dimensions() > 2);
     ARM_COMPUTE_RETURN_ERROR_ON(fc_info.activation_info.enabled() && is_data_type_quantized(input->data_type()) && fc_info.activation_info.activation() != ActivationLayerInfo::ActivationFunction::RELU
                                 && fc_info.activation_info.activation() != ActivationLayerInfo::ActivationFunction::BOUNDED_RELU && fc_info.activation_info.activation() != ActivationLayerInfo::ActivationFunction::LU_BOUNDED_RELU);
     bool weights_reshaped = fc_info.transpose_weights ? fc_info.are_weights_reshaped : true;
     bool is_fc_after_conv = true;
     const ITensorInfo &flatten_input     = TensorInfo(input->clone()->set_is_resizable(true).reset_padding().set_tensor_shape(compute_flatten_shape(input)).set_data_layout(DataLayout::NCHW));
     const ITensorInfo &reshaped_weights  = TensorInfo(weights->clone()->set_is_resizable(true).reset_padding().set_tensor_shape(compute_transposed_shape(*weights)));
     const ITensorInfo &converted_weights = weights_reshaped ? TensorInfo(weights->clone()->set_is_resizable(true).reset_padding()) : TensorInfo(*reshaped_weights.clone());
     // With the Fully Connected layer we can have 4 different cases:
     //  1) Convolution layer -> Fully Connected layer without batches
     //  2) Fully Connected layer -> Fully Connected layer without batches
     //  3) Convolution layer -> Fully Connected layer with batches
     //  4) Fully Connected layer -> Fully Connected layer with batches
     const ITensorInfo *input_to_use   = input;
     const ITensorInfo *weights_to_use = weights;
     // Check if we have a fully connected layer with batches
     const bool is_batched_fc_layer = output->dimension(1) > 1;
     if(is_batched_fc_layer)
     {
         is_fc_after_conv = (TensorShape::num_max_dimensions >= 4) && (std::equal(input->tensor_shape().cbegin() + 3,
                                                                                  input->tensor_shape().cend(),
                                                                                  output->tensor_shape().cbegin() + 1));
     }
     else
     {
         is_fc_after_conv = input->num_dimensions() > 1;
     }
     if(!weights_reshaped)
     {
         // Validate reshape weights kernel
         ARM_COMPUTE_RETURN_ON_ERROR(CLTranspose::validate(weights, &reshaped_weights));
         weights_to_use = &reshaped_weights;
     }
     if(is_fc_after_conv && (input->data_layout() != fc_info.weights_trained_layout))
     {
         // Validate convert weights kernel
         ARM_COMPUTE_RETURN_ON_ERROR(CLConvertFullyConnectedWeights::validate(weights_to_use,
                                                                              &converted_weights,
                                                                              input->tensor_shape(),
                                                                              fc_info.weights_trained_layout));
         weights_to_use = &converted_weights;
     }
     if(is_fc_after_conv)
     {
         // Fully Connected layer after a Convolution Layer without batches
         ARM_COMPUTE_RETURN_ERROR_ON((weights_to_use->dimension(1) != (input->dimension(0) * input->dimension(1) * input->dimension(2))));
         // Validate flatten kernel
         ARM_COMPUTE_RETURN_ON_ERROR(CLFlattenLayer::validate(input, &flatten_input));
         input_to_use = &flatten_input;
     }
     else
     {
         // Fully Connected layer after a Fully Connected Layer without batches
         ARM_COMPUTE_RETURN_ERROR_ON(input->dimension(0) != weights_to_use->dimension(1));
     }
     // Validate matrix multiply kernel
     ARM_COMPUTE_RETURN_ON_ERROR(validate_mm(*input_to_use, *weights_to_use, biases, *output, fc_info));
     return Status{};
 }
References ActivationLayerInfo::activation(), FullyConnectedLayerInfo::activation_info, FullyConnectedLayerInfo::are_weights_reshaped, ARM_COMPUTE_RETURN_ERROR_ON, ARM_COMPUTE_RETURN_ERROR_ON_DATA_TYPE_CHANNEL_NOT_IN, ARM_COMPUTE_RETURN_ERROR_ON_MISMATCHING_DATA_TYPES, ARM_COMPUTE_RETURN_ERROR_ON_NULLPTR, ARM_COMPUTE_RETURN_ON_ERROR, ActivationLayerInfo::BOUNDED_RELU, Dimensions< T >::cbegin(), ICloneable< T >::clone(), arm_compute::misc::shape_calculator::compute_flatten_shape(), arm_compute::misc::shape_calculator::compute_transposed_shape(), ITensorInfo::dimension(), ActivationLayerInfo::enabled(), arm_compute::F16, arm_compute::F32, arm_compute::test::validation::input, arm_compute::is_data_type_quantized(), ActivationLayerInfo::LU_BOUNDED_RELU, arm_compute::NCHW, ITensorInfo::num_dimensions(), Dimensions< size_t >::num_max_dimensions, arm_compute::QASYMM8, arm_compute::QASYMM8_SIGNED, ActivationLayerInfo::RELU, ITensorInfo::tensor_shape(), FullyConnectedLayerInfo::transpose_weights, CLFlattenLayer::validate(), CLTranspose::validate(), CLConvertFullyConnectedWeights::validate(), and FullyConnectedLayerInfo::weights_trained_layout.
Referenced by CLFullyConnectedLayer::configure(), CLRNNLayer::validate(), and CLLSTMLayer::validate().
The documentation for this class was generated from the following files:
arm_compute/runtime/CL/functions/CLFullyConnectedLayer.h
src/runtime/CL/functions/CLFullyConnectedLayer.cpp