Compute Library: ClCrop Class Reference
ClCrop Class Reference
Basic function to run kernels::ClCropKernel.
#include <ClCrop.h>
Public Member Functions
ClCrop ()=default
Constructor.
void configure (const CLCompileContext &compile_context, const ITensorInfo *src, ITensorInfo *dst, Coordinates2D start, Coordinates2D end, uint32_t batch_index, float extrapolation_value=0, Window *dst_window=nullptr)
Initialise the function's source and destination.
Public Member Functions inherited from ICLOperator
ICLOperator (IRuntimeContext *ctx=nullptr)
Constructor.
ICLOperator (const ICLOperator &)=delete
Prevent instances of this class from being copied (As this class contains pointers)
ICLOperator (ICLOperator &&)=default
Default move constructor.
ICLOperator & operator= (const ICLOperator &)=delete
Prevent instances of this class from being copied (As this class contains pointers)
ICLOperator & operator= (ICLOperator &&)=default
Default move assignment operator.
void run (ITensorPack &tensors) override
Run the kernels contained in the function.
void prepare (ITensorPack &constants) override
Prepare the function for executing.
MemoryRequirements workspace () const override
Return the memory requirements required by the workspace.
Public Member Functions inherited from IOperator
virtual ~IOperator ()=default
Destructor.
Static Public Member Functions
static Status validate (const ITensorInfo *src, const ITensorInfo *dst, Coordinates2D start, Coordinates2D end, uint32_t batch_index, float extrapolation_value=0, Window *dst_window=nullptr)
Static function to check if given info will lead to a valid configuration of kernels::ClCropKernel.
Detailed Description
Basic function to run kernels::ClCropKernel.
Definition at line 36 of file ClCrop.h.
Constructor & Destructor Documentation
ClCrop()
ClCrop () default
Constructor.
Member Function Documentation
configure()
void configure (const CLCompileContext & compile_context, const ITensorInfo * src, ITensorInfo * dst, Coordinates2D start, Coordinates2D end, uint32_t batch_index, float extrapolation_value = 0, Window * dst_window = nullptr)
Initialise the function's source and destination.
Note
Supported tensor rank: up to 4
Parameters
[in] compile_context The compile context to be used.
[in] src Source tensor info. Data type supported: All. Data layouts supported: NHWC.
[out] dst Destination tensor info. Data type supported: F32
[in] start Coordinates of where to start cropping the image.
[in] end Coordinates of where to end cropping the image.
[in] batch_index Fourth dimension index of the 3D image to crop in src.
[in] extrapolation_value Value to be used for values outside of the image. Default is 0.
[in] dst_window Output window to be used in case cropped image is being copied into a tensor. Default is nullptr.
Definition at line 33 of file ClCrop.cpp.
 {
     auto k = std::make_unique<kernels::ClCropKernel>();
     k->configure(compile_context, src, dst, start, end, batch_index, extrapolation_value, dst_window);
     _kernel = std::move(k);
 }
References arm_compute::test::validation::dst, arm_compute::mlgo::parser::end(), and arm_compute::test::validation::src.
validate()
Status validate (const ITensorInfo * src, const ITensorInfo * dst, Coordinates2D start, Coordinates2D end, uint32_t batch_index, float extrapolation_value = 0, Window * dst_window = nullptr) static
Static function to check if given info will lead to a valid configuration of kernels::ClCropKernel.
Note
Supported tensor rank: up to 4
Parameters
[in] src Source tensor info. Data type supported: All. Data layouts supported: NHWC.
[in] dst Destination tensor info. Data type supported: F32
[in] start Coordinates of where to start cropping the image.
[in] end Coordinates of where to end cropping the image.
[in] batch_index Fourth dimension index of the 3D image to crop in src.
[in] extrapolation_value Value to be used for values outside of the image. Default is 0.
[in] dst_window Output window to be used in case cropped image is being copied into a tensor. Default is nullptr.
Definition at line 41 of file ClCrop.cpp.
 {
     return kernels::ClCropKernel::validate(src, dst, start, end, batch_index, extrapolation_value, dst_window);
 }
References arm_compute::test::validation::dst, arm_compute::mlgo::parser::end(), arm_compute::test::validation::src, and ClCropKernel::validate().
Referenced by CLCrop::validate().
The documentation for this class was generated from the following files:
src/runtime/gpu/cl/operators/ClCrop.h
src/runtime/gpu/cl/operators/ClCrop.cpp