Compute Library: NEElementwiseDivision Class Reference
NEElementwiseDivision Class Reference
Basic function to run cpu::kernels::CpuArithmeticKernel for division.
#include <NEElementwiseOperations.h>
Public Member Functions
NEElementwiseDivision ()
Default Constructor.
~NEElementwiseDivision ()
Default Destructor.
NEElementwiseDivision (const NEElementwiseDivision &)=delete
Prevent instances of this class from being copied (As this class contains pointers)
NEElementwiseDivision (NEElementwiseDivision &&)
Default move constructor.
NEElementwiseDivision & operator= (const NEElementwiseDivision &)=delete
Prevent instances of this class from being copied (As this class contains pointers)
NEElementwiseDivision & operator= (NEElementwiseDivision &&)
Default move assignment operator.
void configure (ITensor *input1, ITensor *input2, ITensor *output, const ActivationLayerInfo &act_info=ActivationLayerInfo())
Initialise the kernel's inputs, output and conversion policy.
void run () override
Run the kernels contained in the function.
Public Member Functions inherited from IFunction
virtual ~IFunction ()=default
Destructor.
virtual void prepare ()
Prepare the function for executing.
Static Public Member Functions
static Status validate (const ITensorInfo *input1, const ITensorInfo *input2, const ITensorInfo *output, const ActivationLayerInfo &act_info=ActivationLayerInfo())
Static function to check if given info will lead to a valid configuration of cpu::kernels::CpuArithmeticKernel for division.
Detailed Description
Basic function to run cpu::kernels::CpuArithmeticKernel for division.
Note
The tensor data type for the inputs must be F16/F32.
The function performs a squared different operation between two tensors (i.e., out[i] = in1[i] / in2[i])
Definition at line 220 of file NEElementwiseOperations.h.
Constructor & Destructor Documentation
NEElementwiseDivision() [1/3]
NEElementwiseDivision ()
Default Constructor.
Definition at line 165 of file NEElementwiseOperations.cpp.
     : _impl(std::make_unique<Impl>())
 {
 }
~NEElementwiseDivision()
~NEElementwiseDivision () default
Default Destructor.
NEElementwiseDivision() [2/3]
NEElementwiseDivision (const NEElementwiseDivision &) delete
Prevent instances of this class from being copied (As this class contains pointers)
NEElementwiseDivision() [3/3]
NEElementwiseDivision (NEElementwiseDivision &&) default
Default move constructor.
Member Function Documentation
configure()
void configure (ITensor * input1, ITensor * input2, ITensor * output, const ActivationLayerInfo & act_info = ActivationLayerInfo())
Initialise the kernel's inputs, output and conversion policy.
Valid data layouts:
All
Valid data type configurations:
src0 src1 dst
F16 F16 F16
F32 F32 F32
Parameters
[in,out] input1 First tensor input. Data types supported: F16/F32.
[in,out] input2 Second tensor input. Data types supported: Same as input1.
[out] output Output tensor. Data types supported: Same as input1.
[in] act_info (Optional) Activation layer information in case of a fused activation. Currently not supported.
Definition at line 173 of file NEElementwiseOperations.cpp.
 {
     ARM_COMPUTE_UNUSED(act_info);
     _impl->src_0 = input1;
     _impl->src_1 = input2;
     _impl->dst   = output;
     _impl->op    = std::make_unique<cpu::CpuElementwiseDivision>();
     _impl->op->configure(input1->info(), input2->info(), output->info());
 }
References ARM_COMPUTE_UNUSED, and ITensor::info().
operator=() [1/2]
NEElementwiseDivision& operator= (const NEElementwiseDivision &) delete
Prevent instances of this class from being copied (As this class contains pointers)
operator=() [2/2]
NEElementwiseDivision & operator= (NEElementwiseDivision &&) default
Default move assignment operator.
run()
void run () override virtual
Run the kernels contained in the function.
For CPU kernels:
Multi-threading is used for the kernels which are parallelisable.
By default std::thread::hardware_concurrency() threads are used.
Note
CPPScheduler::set_num_threads() can be used to manually set the number of threads
For OpenCL kernels:
All the kernels are enqueued on the queue associated with CLScheduler.
The queue is then flushed.
Note
The function will not block until the kernels are executed. It is the user's responsibility to wait.
Will call prepare() on first run if hasn't been done
Implements IFunction.
Definition at line 189 of file NEElementwiseOperations.cpp.
 {
     ITensorPack pack;
     pack.add_tensor(TensorType::ACL_SRC_0, _impl->src_0);
     pack.add_tensor(TensorType::ACL_SRC_1, _impl->src_1);
     pack.add_tensor(TensorType::ACL_DST, _impl->dst);
     _impl->op->run(pack);
 }
References arm_compute::ACL_DST, arm_compute::ACL_SRC_0, arm_compute::ACL_SRC_1, and ITensorPack::add_tensor().
validate()
Status validate (const ITensorInfo * input1, const ITensorInfo * input2, const ITensorInfo * output, const ActivationLayerInfo & act_info = ActivationLayerInfo()) static
Static function to check if given info will lead to a valid configuration of cpu::kernels::CpuArithmeticKernel for division.
Parameters
[in] input1 First tensor input info. Data types supported: F16/F32.
[in] input2 Second tensor input info. Data types supported: Same as input1.
[in] output Output tensor info. Data types supported: Same as input1.
[in] act_info (Optional) Activation layer information in case of a fused activation. Currently not supported.
Returns
a status
Definition at line 183 of file NEElementwiseOperations.cpp.
 {
     ARM_COMPUTE_RETURN_ERROR_ON(act_info.enabled());
     return cpu::CpuElementwiseDivision::validate(input1, input2, output);
 }
References ARM_COMPUTE_RETURN_ERROR_ON, ActivationLayerInfo::enabled(), and CpuElementwiseDivision::validate().
The documentation for this class was generated from the following files:
arm_compute/runtime/NEON/functions/NEElementwiseOperations.h
src/runtime/NEON/functions/NEElementwiseOperations.cpp