Compute Library: TensorPack Class Reference
TensorPack Class Reference
Tensor pack class.
#include <Acl.hpp>
Data Structures
struct PackPair
Pack pair construct.
Public Member Functions
TensorPack (Context &ctx, StatusCode *status=nullptr)
Constructor.
StatusCode add (Tensor &tensor, int32_t slot_id)
Add tensor to tensor pack.
StatusCode add (std::initializer_list< PackPair > packed)
Add a list of tensors to a tensor pack.
Public Member Functions inherited from ObjectBase< AclTensorPack_ >
~ObjectBase ()=default
Destructor.
ObjectBase (const ObjectBase< AclTensorPack_ > &)=default
Copy constructor.
ObjectBase (ObjectBase< AclTensorPack_ > &&)=default
Move Constructor.
ObjectBase< AclTensorPack_ > & operator= (const ObjectBase< AclTensorPack_ > &)=default
Copy assignment operator.
ObjectBase< AclTensorPack_ > & operator= (ObjectBase< AclTensorPack_ > &&)=default
Move assignment operator.
void reset (AclTensorPack_ *val)
Reset object value.
const AclTensorPack_ * get () const
Access uderlying object.
AclTensorPack_ * get ()
Access uderlying object.
Detailed Description
Tensor pack class.
Pack is a utility construct that is used to create a collection of tensors that can then be passed into operator as inputs.
Definition at line 683 of file Acl.hpp.
Constructor & Destructor Documentation
TensorPack()
TensorPack (Context & ctx, StatusCode * status = nullptr) inline explicit
Constructor.
Parameters
[in] ctx Context from where the tensor pack will be created from
[out] status Status information if requested
Definition at line 709 of file Acl.hpp.
     {
         AclTensorPack pack;
         const auto    st = detail::as_enum<StatusCode>(AclCreateTensorPack(&pack, ctx.get()));
         reset(pack);
         report_status(st, "[Compute Library] Failure during tensor pack creation");
         if(status)
         {
             *status = st;
         }
     }
References AclCreateTensorPack(), ObjectBase< T >::get(), and ObjectBase< AclTensorPack_ >::reset().
Member Function Documentation
add() [1/2]
StatusCode add (Tensor & tensor, int32_t slot_id) inline
Add tensor to tensor pack.
Parameters
[in] slot_id Slot id of the tensor in respect with the operator
[in] tensor Tensor to be added in the pack
Returns
Status code
Definition at line 727 of file Acl.hpp.
     {
         return detail::as_enum<StatusCode>(AclPackTensor(_object.get(), tensor.get(), slot_id));
     }
References AclPackTensor(), and ObjectBase< T >::get().
add() [2/2]
StatusCode add (std::initializer_list< PackPair > packed) inline
Add a list of tensors to a tensor pack.
Parameters
[in] packed Pair packs to be added
Returns
Status code
Definition at line 737 of file Acl.hpp.
     {
         const size_t           size = packed.size();
         std::vector<int32_t>   slots(size);
         std::vector<AclTensor> tensors(size);
         int                    i = 0;
         for(auto &p : packed)
         {
             slots[i]   = p.slot_id;
             tensors[i] = AclTensor(p.tensor);
             ++i;
         }
         return detail::as_enum<StatusCode>(AclPackTensors(_object.get(), tensors.data(), slots.data(), size));
     }
References AclPackTensors().
The documentation for this class was generated from the following file:
arm_compute/Acl.hpp