Compute Library: NEGEMMLowpOutputStage Class Reference
NEGEMMLowpOutputStage Class Reference
Basic function to execute GEMMLowpQuantizeDown kernels.
#include <NEGEMMLowpOutputStage.h>
Public Member Functions
NEGEMMLowpOutputStage ()=default
Constructor.
NEGEMMLowpOutputStage (const NEGEMMLowpOutputStage &)=delete
Prevent instances of this class from being copied (As this class contains pointers)
NEGEMMLowpOutputStage & operator= (const NEGEMMLowpOutputStage &)=delete
Prevent instances of this class from being copied (As this class contains pointers)
NEGEMMLowpOutputStage (NEGEMMLowpOutputStage &&)=delete
Prevent instances of this class from being moved (As this class contains non movable objects)
NEGEMMLowpOutputStage & operator= (NEGEMMLowpOutputStage &&)=delete
Prevent instances of this class from being moved (As this class contains non movable objects)
~NEGEMMLowpOutputStage ()
Default destructor.
void configure (const ITensor *input, const ITensor *bias, ITensor *output, const GEMMLowpOutputStageInfo &info)
Initialise the kernel's inputs, output.
Public Member Functions inherited from INESimpleFunctionNoBorder
INESimpleFunctionNoBorder (IRuntimeContext *ctx=nullptr)
Constructor.
INESimpleFunctionNoBorder (const INESimpleFunctionNoBorder &)=delete
Prevent instances of this class from being copied (As this class contains pointers)
INESimpleFunctionNoBorder (INESimpleFunctionNoBorder &&)=default
Default move constructor.
INESimpleFunctionNoBorder & operator= (const INESimpleFunctionNoBorder &)=delete
Prevent instances of this class from being copied (As this class contains pointers)
INESimpleFunctionNoBorder & operator= (INESimpleFunctionNoBorder &&)=default
Default move assignment operator.
~INESimpleFunctionNoBorder ()
Default destructor.
void run () override final
Run the kernels contained in the function.
Public Member Functions inherited from IFunction
virtual ~IFunction ()=default
Destructor.
virtual void prepare ()
Prepare the function for executing.
Static Public Member Functions
static Status validate (const ITensorInfo *input, const ITensorInfo *bias, const ITensorInfo *output, const GEMMLowpOutputStageInfo &info)
Static function to check if given info will lead to a valid configuration of NEGEMMLowpOutputStage.
Detailed Description
Basic function to execute GEMMLowpQuantizeDown kernels.
This function calls the following kernels:
NEGEMMLowpQuantizeDownInt32ScaleKernel
NEGEMMLowpQuantizeDownInt32ToUint8ScaleByFixedPointKernel
NEGEMMLowpQuantizeDownInt32ToInt8ScaleByFixedPointKernel
NEGEMMLowpQuantizeDownInt32ToInt16ScaleByFixedPointKernel
Definition at line 268 of file NEGEMMLowpOutputStage.h.
Constructor & Destructor Documentation
NEGEMMLowpOutputStage() [1/3]
NEGEMMLowpOutputStage () default
Constructor.
NEGEMMLowpOutputStage() [2/3]
NEGEMMLowpOutputStage (const NEGEMMLowpOutputStage &) delete
Prevent instances of this class from being copied (As this class contains pointers)
NEGEMMLowpOutputStage() [3/3]
NEGEMMLowpOutputStage (NEGEMMLowpOutputStage &&) delete
Prevent instances of this class from being moved (As this class contains non movable objects)
~NEGEMMLowpOutputStage()
~NEGEMMLowpOutputStage () default
Default destructor.
Member Function Documentation
configure()
void configure (const ITensor * input, const ITensor * bias, ITensor * output, const GEMMLowpOutputStageInfo & info)
Initialise the kernel's inputs, output.
Valid data layouts:
All
Valid data type configurations:
src0 src1 dst
S32 S32 QASYMM8
S32 S32 QASYMM8_SIGNED
S32 S32 QSYMM16
Parameters
[in] input Input tensor. Data type supported: S32
[in] bias Biases tensor. Only shared biases supported and it can be a nullptr if the biases addition is not required. Biases are 1D tensor with dimensions [OFM]. Data type supported: Same as input.
[out] output Output tensor. Data type supported: Data type supported: QASYMM8/QASYMM8_SIGNED/QSYMM16
[in] info GEMMLowp output stage metadata.
Definition at line 81 of file NEGEMMLowpOutputStage.cpp.
 {
     // Perform validate step
     ARM_COMPUTE_ERROR_ON_NULLPTR(input, output);
     ARM_COMPUTE_ERROR_THROW_ON(NEGEMMLowpOutputStage::validate(input->info(), bias != nullptr ? bias->info() : nullptr, output->info(), info));
     switch(info.type)
     {
         case GEMMLowpOutputStageType::QUANTIZE_DOWN_FIXEDPOINT:
         {
             switch(info.output_data_type)
             {
                 case DataType::QASYMM8:
                 {
                     auto k = std::make_unique<NEGEMMLowpQuantizeDownInt32ToUint8ScaleByFixedPointKernel>();
                     k->configure(input, bias, output, info.gemmlowp_multiplier, info.gemmlowp_shift, info.gemmlowp_offset, info.gemmlowp_min_bound, info.gemmlowp_max_bound);
                     _kernel = std::move(k);
                     break;
                 }
                 case DataType::QASYMM8_SIGNED:
                 {
                     auto k = std::make_unique<NEGEMMLowpQuantizeDownInt32ToInt8ScaleByFixedPointKernel>();
                     k->configure(input, bias, output, info.gemmlowp_multiplier, info.gemmlowp_shift, info.gemmlowp_offset, info.gemmlowp_min_bound, info.gemmlowp_max_bound);
                     _kernel = std::move(k);
                     break;
                 }
                 case DataType::QSYMM16:
                 {
                     auto k = std::make_unique<NEGEMMLowpQuantizeDownInt32ToInt16ScaleByFixedPointKernel>();
                     k->configure(input, bias, output, info.gemmlowp_multiplier, info.gemmlowp_shift, info.gemmlowp_min_bound, info.gemmlowp_max_bound);
                     _kernel = std::move(k);
                     break;
                 }
                 default:
                 {
                     ARM_COMPUTE_ERROR("Unsupported output data type.");
                     break;
                 }
             }
             break;
         }
         case GEMMLowpOutputStageType::QUANTIZE_DOWN:
         {
             switch(info.output_data_type)
             {
                 case DataType::QASYMM8:
                 case DataType::QASYMM8_SIGNED:
                 {
                     auto k = std::make_unique<NEGEMMLowpQuantizeDownInt32ScaleKernel>();
                     k->configure(input, bias, output, &info);
                     _kernel = std::move(k);
                     break;
                 }
                 default:
                 {
                     ARM_COMPUTE_ERROR("Unsupported output data type.");
                     break;
                 }
             }
             break;
         }
         default:
             ARM_COMPUTE_ERROR("Unsupported GEMMLowpOutputStage type.");
     }
 }
References ARM_COMPUTE_ERROR, ARM_COMPUTE_ERROR_ON_NULLPTR, ARM_COMPUTE_ERROR_THROW_ON, ITensor::info(), arm_compute::test::validation::info, arm_compute::test::validation::input, arm_compute::QASYMM8, arm_compute::QASYMM8_SIGNED, arm_compute::QSYMM16, arm_compute::QUANTIZE_DOWN, arm_compute::QUANTIZE_DOWN_FIXEDPOINT, and NEGEMMLowpOutputStage::validate().
Referenced by NEQLSTMLayer::configure().
operator=() [1/2]
NEGEMMLowpOutputStage& operator= (const NEGEMMLowpOutputStage &) delete
Prevent instances of this class from being copied (As this class contains pointers)
operator=() [2/2]
NEGEMMLowpOutputStage& operator= (NEGEMMLowpOutputStage &&) delete
Prevent instances of this class from being moved (As this class contains non movable objects)
validate()
Status validate (const ITensorInfo * input, const ITensorInfo * bias, const ITensorInfo * output, const GEMMLowpOutputStageInfo & info) static
Static function to check if given info will lead to a valid configuration of NEGEMMLowpOutputStage.
Parameters
[in] input Input tensor info. It is the output of NEGEMMLowpMatrixMultiplyCore function. Data type supported: S32
[in] bias Biases tensor info. Only shared biases supported and it can be a nullptr if the addition of biases is not required. Biases are 1D tensor with dimensions [OFM]. Data type supported: Same as input.
[in] output Output tensor info. Data type supported: Data type supported: QASYMM8/QASYMM8_SIGNED/QSYMM16
[in] info GEMMLowp output stage metadata.
Returns
a status
Definition at line 147 of file NEGEMMLowpOutputStage.cpp.
 {
     ARM_COMPUTE_RETURN_ERROR_ON_NULLPTR(output);
     ARM_COMPUTE_RETURN_ERROR_ON_MSG(output->data_type() == DataType::UNKNOWN, "NEGEMMLowpQuantizeDownScaleByFixedPoint cannot be used with UNKNOWN output data type.");
     ARM_COMPUTE_RETURN_ERROR_ON_DATA_TYPE_CHANNEL_NOT_IN(output, 1, DataType::QASYMM8, DataType::QASYMM8_SIGNED, DataType::QSYMM16);
     ARM_COMPUTE_RETURN_ERROR_ON((info.type != GEMMLowpOutputStageType::QUANTIZE_DOWN) && (info.type != GEMMLowpOutputStageType::QUANTIZE_DOWN_FIXEDPOINT));
     switch(info.type)
     {
         case GEMMLowpOutputStageType::QUANTIZE_DOWN_FIXEDPOINT:
         {
             switch(output->data_type())
             {
                 case DataType::QASYMM8:
                     return NEGEMMLowpQuantizeDownInt32ToUint8ScaleByFixedPointKernel::validate(input, bias, output, info.gemmlowp_min_bound, info.gemmlowp_max_bound);
                 case DataType::QASYMM8_SIGNED:
                     return NEGEMMLowpQuantizeDownInt32ToInt8ScaleByFixedPointKernel::validate(input, bias, output, info.gemmlowp_min_bound, info.gemmlowp_max_bound);
                 case DataType::QSYMM16:
                     return NEGEMMLowpQuantizeDownInt32ToInt16ScaleByFixedPointKernel::validate(input, bias, output, info.gemmlowp_min_bound, info.gemmlowp_max_bound);
                 default:
                     return ARM_COMPUTE_CREATE_ERROR(ErrorCode::RUNTIME_ERROR, "Unsupported output data type.");
             }
         }
         case GEMMLowpOutputStageType::QUANTIZE_DOWN:
         {
             switch(output->data_type())
             {
                 case DataType::QASYMM8:
                 case DataType::QASYMM8_SIGNED:
                     return NEGEMMLowpQuantizeDownInt32ScaleKernel::validate(input, bias, output, &info);
                 default:
                     return ARM_COMPUTE_CREATE_ERROR(ErrorCode::RUNTIME_ERROR, "Unsupported output data type.");
             }
         }
         default:
             return ARM_COMPUTE_CREATE_ERROR(ErrorCode::RUNTIME_ERROR, "Unsupported GEMMLowpOutputStage type.");
     }
 }
References ARM_COMPUTE_CREATE_ERROR, ARM_COMPUTE_RETURN_ERROR_ON, ARM_COMPUTE_RETURN_ERROR_ON_DATA_TYPE_CHANNEL_NOT_IN, ARM_COMPUTE_RETURN_ERROR_ON_MSG, ARM_COMPUTE_RETURN_ERROR_ON_NULLPTR, ITensorInfo::data_type(), arm_compute::test::validation::info, arm_compute::test::validation::input, arm_compute::QASYMM8, arm_compute::QASYMM8_SIGNED, arm_compute::QSYMM16, arm_compute::QUANTIZE_DOWN, arm_compute::QUANTIZE_DOWN_FIXEDPOINT, arm_compute::RUNTIME_ERROR, arm_compute::UNKNOWN, NEGEMMLowpQuantizeDownInt32ScaleKernel::validate(), NEGEMMLowpQuantizeDownInt32ToInt16ScaleByFixedPointKernel::validate(), NEGEMMLowpQuantizeDownInt32ToUint8ScaleByFixedPointKernel::validate(), and NEGEMMLowpQuantizeDownInt32ToInt8ScaleByFixedPointKernel::validate().
Referenced by NEGEMMLowpOutputStage::configure(), and NEQLSTMLayer::validate().
The documentation for this class was generated from the following files:
arm_compute/runtime/NEON/functions/NEGEMMLowpOutputStage.h
src/runtime/NEON/functions/NEGEMMLowpOutputStage.cpp