var namespacearm__compute_1_1opencl =
[
    [ "kernels", "namespacearm__compute_1_1opencl_1_1kernels.xhtml", "namespacearm__compute_1_1opencl_1_1kernels" ],
    [ "ClAbs", "classarm__compute_1_1opencl_1_1_cl_abs.xhtml", "classarm__compute_1_1opencl_1_1_cl_abs" ],
    [ "ClActivation", "classarm__compute_1_1opencl_1_1_cl_activation.xhtml", "classarm__compute_1_1opencl_1_1_cl_activation" ],
    [ "ClAdd", "classarm__compute_1_1opencl_1_1_cl_add.xhtml", "classarm__compute_1_1opencl_1_1_cl_add" ],
    [ "ClComplexMul", "classarm__compute_1_1opencl_1_1_cl_complex_mul.xhtml", "classarm__compute_1_1opencl_1_1_cl_complex_mul" ],
    [ "ClConcatenate", "classarm__compute_1_1opencl_1_1_cl_concatenate.xhtml", "classarm__compute_1_1opencl_1_1_cl_concatenate" ],
    [ "ClConvertFullyConnectedWeights", "classarm__compute_1_1opencl_1_1_cl_convert_fully_connected_weights.xhtml", "classarm__compute_1_1opencl_1_1_cl_convert_fully_connected_weights" ],
    [ "ClCopy", "classarm__compute_1_1opencl_1_1_cl_copy.xhtml", "classarm__compute_1_1opencl_1_1_cl_copy" ],
    [ "ClCrop", "classarm__compute_1_1opencl_1_1_cl_crop.xhtml", "classarm__compute_1_1opencl_1_1_cl_crop" ],
    [ "ClDequantization", "classarm__compute_1_1opencl_1_1_cl_dequantization.xhtml", "classarm__compute_1_1opencl_1_1_cl_dequantization" ],
    [ "ClDirectConvolution", "classarm__compute_1_1opencl_1_1_cl_direct_convolution.xhtml", "classarm__compute_1_1opencl_1_1_cl_direct_convolution" ],
    [ "ClElementwiseDivision", "classarm__compute_1_1opencl_1_1_cl_elementwise_division.xhtml", "classarm__compute_1_1opencl_1_1_cl_elementwise_division" ],
    [ "ClElementwiseMax", "classarm__compute_1_1opencl_1_1_cl_elementwise_max.xhtml", "classarm__compute_1_1opencl_1_1_cl_elementwise_max" ],
    [ "ClElementwiseMin", "classarm__compute_1_1opencl_1_1_cl_elementwise_min.xhtml", "classarm__compute_1_1opencl_1_1_cl_elementwise_min" ],
    [ "ClElementwisePower", "classarm__compute_1_1opencl_1_1_cl_elementwise_power.xhtml", "classarm__compute_1_1opencl_1_1_cl_elementwise_power" ],
    [ "ClElementwiseSquaredDiff", "classarm__compute_1_1opencl_1_1_cl_elementwise_squared_diff.xhtml", "classarm__compute_1_1opencl_1_1_cl_elementwise_squared_diff" ],
    [ "ClExp", "classarm__compute_1_1opencl_1_1_cl_exp.xhtml", "classarm__compute_1_1opencl_1_1_cl_exp" ],
    [ "ClFill", "classarm__compute_1_1opencl_1_1_cl_fill.xhtml", "classarm__compute_1_1opencl_1_1_cl_fill" ],
    [ "ClFloor", "classarm__compute_1_1opencl_1_1_cl_floor.xhtml", "classarm__compute_1_1opencl_1_1_cl_floor" ],
    [ "ClLog", "classarm__compute_1_1opencl_1_1_cl_log.xhtml", "classarm__compute_1_1opencl_1_1_cl_log" ],
    [ "ClLogicalNot", "classarm__compute_1_1opencl_1_1_cl_logical_not.xhtml", "classarm__compute_1_1opencl_1_1_cl_logical_not" ],
    [ "ClMul", "classarm__compute_1_1opencl_1_1_cl_mul.xhtml", "classarm__compute_1_1opencl_1_1_cl_mul" ],
    [ "ClNeg", "classarm__compute_1_1opencl_1_1_cl_neg.xhtml", "classarm__compute_1_1opencl_1_1_cl_neg" ],
    [ "ClPermute", "classarm__compute_1_1opencl_1_1_cl_permute.xhtml", "classarm__compute_1_1opencl_1_1_cl_permute" ],
    [ "ClPooling", "classarm__compute_1_1opencl_1_1_cl_pooling.xhtml", "classarm__compute_1_1opencl_1_1_cl_pooling" ],
    [ "ClPRelu", "classarm__compute_1_1opencl_1_1_cl_p_relu.xhtml", "classarm__compute_1_1opencl_1_1_cl_p_relu" ],
    [ "ClQuantization", "classarm__compute_1_1opencl_1_1_cl_quantization.xhtml", "classarm__compute_1_1opencl_1_1_cl_quantization" ],
    [ "ClReshape", "classarm__compute_1_1opencl_1_1_cl_reshape.xhtml", "classarm__compute_1_1opencl_1_1_cl_reshape" ],
    [ "ClRound", "classarm__compute_1_1opencl_1_1_cl_round.xhtml", "classarm__compute_1_1opencl_1_1_cl_round" ],
    [ "ClRsqrt", "classarm__compute_1_1opencl_1_1_cl_rsqrt.xhtml", "classarm__compute_1_1opencl_1_1_cl_rsqrt" ],
    [ "ClScale", "classarm__compute_1_1opencl_1_1_cl_scale.xhtml", "classarm__compute_1_1opencl_1_1_cl_scale" ],
    [ "ClSin", "classarm__compute_1_1opencl_1_1_cl_sin.xhtml", "classarm__compute_1_1opencl_1_1_cl_sin" ],
    [ "ClSoftmax", "classarm__compute_1_1opencl_1_1_cl_softmax.xhtml", "classarm__compute_1_1opencl_1_1_cl_softmax" ],
    [ "ClSub", "classarm__compute_1_1opencl_1_1_cl_sub.xhtml", "classarm__compute_1_1opencl_1_1_cl_sub" ],
    [ "ClTranspose", "classarm__compute_1_1opencl_1_1_cl_transpose.xhtml", "classarm__compute_1_1opencl_1_1_cl_transpose" ]
];