Compute Library: arm_compute::utils::cpu Namespace Reference
arm_compute::utils::cpu Namespace Reference
Functions
void get_cpu_configuration (CPUInfo &cpuinfo)
This function will try to detect the CPU configuration on the system and will fill the cpuinfo object accordingly to reflect this.
unsigned int get_threads_hint ()
Some systems have both big and small cores, this fuction computes the minimum number of cores that are exactly the same on the system.
Function Documentation
get_cpu_configuration()
void get_cpu_configuration (CPUInfo & cpuinfo)
This function will try to detect the CPU configuration on the system and will fill the cpuinfo object accordingly to reflect this.
Parameters
[out] cpuinfo CPUInfo to be used to hold the system's cpu configuration.
Definition at line 405 of file CPUUtils.cpp.
 {
 #if !defined(BARE_METAL) && !defined(__APPLE__) && (defined(__arm__) || defined(__aarch64__))
     bool           cpuid               = false;
     bool           hwcaps_fp16_support = false;
     bool           hwcaps_dot_support  = false;
     bool           hwcaps_sve          = false;
     const uint32_t hwcaps              = getauxval(AT_HWCAP);
     if((hwcaps & HWCAP_CPUID) != 0)
     {
         cpuid = true;
     }
     if((hwcaps & HWCAP_ASIMDHP) != 0)
     {
         hwcaps_fp16_support = true;
     }
 #if defined(__aarch64__)
     if((hwcaps & HWCAP_ASIMDDP) != 0)
     {
         hwcaps_dot_support = true;
     }
     if((hwcaps & HWCAP_SVE) != 0)
     {
         hwcaps_sve = true;
     }
 #endif /* defined(__aarch64__) */
     const unsigned int max_cpus = get_max_cpus();
     cpuinfo.set_cpu_num(max_cpus);
     std::vector<CPUModel> percpu(max_cpus, CPUModel::GENERIC);
     if(cpuid)
     {
         populate_models_cpuid(percpu);
     }
     else
     {
         populate_models_cpuinfo(percpu);
     }
     int j(0);
     // Update dot product and FP16 support if one of the CPUs support these features
     // We assume that the system does not have mixed architectures
     bool one_supports_dot  = false;
     bool one_supports_fp16 = false;
     bool one_supports_sve  = false;
     for(const auto &v : percpu)
     {
         one_supports_dot  = one_supports_dot || model_supports_dot(v);
         one_supports_fp16 = one_supports_fp16 || model_supports_fp16(v);
         one_supports_sve  = one_supports_sve || model_supports_sve(v);
         cpuinfo.set_cpu_model(j++, v);
     }
     cpuinfo.set_dotprod(one_supports_dot || hwcaps_dot_support);
     cpuinfo.set_fp16(one_supports_fp16 || hwcaps_fp16_support);
     cpuinfo.set_sve(one_supports_sve || hwcaps_sve);
 #elif(BARE_METAL) && defined(__aarch64__) /* !defined(BARE_METAL) && !defined(__APPLE__) && (defined(__arm__) || defined(__aarch64__)) */
     cpuinfo.set_cpu_num(1);
     const CPUModel cpumodel{ CPUModel::GENERIC };
     cpuinfo.set_cpu_model(0, cpumodel);
     // Assume single CPU in bare metal mode.  Just read the ID register and feature bits directly.
     uint64_t fr0, pfr0, midr;
     __asm __volatile(
         "MRS  %0, ID_AA64ISAR0_EL1\n"
         "MRS  %1, ID_AA64PFR0_EL1\n"
         "MRS  %2, midr_el1"
         : "=r"(fr0), "=r"(pfr0), "=r"(midr));
     if((fr0 >> 44) & 0xf)
     {
         cpuinfo.set_dotprod(true);
     }
     if((pfr0 >> 16) & 0xf)
     {
         cpuinfo.set_fp16(true);
     }
     if((pfr0 >> 32) & 0xf)
     {
         cpuinfo.set_sve(true);
     }
 #else                                     /* #elif(BARE_METAL) && defined(__aarch64__)  */
     ARM_COMPUTE_UNUSED(cpuinfo);
 #endif                                    /* !defined(BARE_METAL) && !defined(__APPLE__) && (defined(__arm__) || defined(__aarch64__)) */
 }
References ARM_COMPUTE_UNUSED, arm_compute::GENERIC, HWCAP_ASIMDDP, HWCAP_ASIMDHP, HWCAP_CPUID, HWCAP_SVE, CPUInfo::set_cpu_model(), CPUInfo::set_cpu_num(), CPUInfo::set_dotprod(), CPUInfo::set_fp16(), and CPUInfo::set_sve().
Referenced by DeviceProperties::DeviceProperties(), and IScheduler::IScheduler().
get_threads_hint()
unsigned int get_threads_hint ()
Some systems have both big and small cores, this fuction computes the minimum number of cores that are exactly the same on the system.
To maximize performance the library attempts to process workloads concurrently using as many threads as big cores are available on the system.
Returns
The minumum number of common cores.
Definition at line 491 of file CPUUtils.cpp.
 {
     unsigned int num_threads_hint = 1;
 #if !defined(BARE_METAL)
     std::map<std::string, unsigned int> cpu_part_occurrence_map;
     // CPU part regex
     regex_t cpu_part_rgx;
     memset(&cpu_part_rgx, 0, sizeof(regex_t));
     int ret_status = regcomp(&cpu_part_rgx, R"(.*CPU part.+/?\:[[:space:]]+([[:alnum:]]+).*)", REG_EXTENDED);
     ARM_COMPUTE_UNUSED(ret_status);
     ARM_COMPUTE_ERROR_ON_MSG(ret_status != 0, "Regex compilation failed.");
     // Read cpuinfo and get occurrence of each core
     std::ifstream cpuinfo;
     cpuinfo.open("/proc/cpuinfo", std::ios::in);
     if(cpuinfo.is_open())
     {
         std::string line;
         while(bool(getline(cpuinfo, line)))
         {
             std::array<regmatch_t, 2> match;
             ret_status = regexec(&cpu_part_rgx, line.c_str(), 2, match.data(), 0);
             if(ret_status == 0)
             {
                 std::string cpu_part = line.substr(match[1].rm_so, (match[1].rm_eo - match[1].rm_so));
                 if(cpu_part_occurrence_map.find(cpu_part) != cpu_part_occurrence_map.end())
                 {
                     cpu_part_occurrence_map[cpu_part]++;
                 }
                 else
                 {
                     cpu_part_occurrence_map[cpu_part] = 1;
                 }
             }
         }
     }
     regfree(&cpu_part_rgx);
     // Get min number of threads
     auto min_common_cores = std::min_element(cpu_part_occurrence_map.begin(), cpu_part_occurrence_map.end(),
                                              [](const std::pair<std::string, unsigned int> &p1, const std::pair<std::string, unsigned int> &p2)
     {
         return p1.second < p2.second;
     });
     // Set thread hint
     num_threads_hint = cpu_part_occurrence_map.empty() ? std::thread::hardware_concurrency() : min_common_cores->second;
 #endif /* !defined(BARE_METAL) */
     return num_threads_hint;
 }
References ARM_COMPUTE_ERROR_ON_MSG, and ARM_COMPUTE_UNUSED.
Referenced by IScheduler::IScheduler().