Compute Library: arm_compute::graph_utils Namespace Reference
arm_compute::graph_utils Namespace Reference
Data Structures
class CaffePreproccessor
Caffe preproccessor.
class DetectionOutputAccessor
Detection output accessor class.
class DummyAccessor
Dummy accessor class.
class ImageAccessor
Image accessor class.
class IPreprocessor
Preprocessor interface.
class NumPyAccessor
NumPy accessor class.
class NumPyBinLoader
Numpy Binary loader class.
class PPMWriter
PPM writer class.
class PrintAccessor
Print accessor class.
class RandomAccessor
Random accessor class.
class SaveNumPyAccessor
SaveNumPy accessor class.
class TFPreproccessor
TF preproccessor.
class TopNPredictionsAccessor
Result accessor class.
class ValidationInputAccessor
Input Accessor used for network validation.
class ValidationOutputAccessor
Output Accessor used for network validation.
Functions
std::unique_ptr< graph::ITensorAccessor > get_random_accessor (PixelValue lower, PixelValue upper, const std::random_device::result_type seed=0)
Generates appropriate random accessor.
std::unique_ptr< graph::ITensorAccessor > get_weights_accessor (const std::string &path, const std::string &data_file, DataLayout file_layout=DataLayout::NCHW)
Generates appropriate weights accessor according to the specified path.
std::unique_ptr< graph::ITensorAccessor > get_input_accessor (const arm_compute::utils::CommonGraphParams &graph_parameters, std::unique_ptr< IPreprocessor > preprocessor=nullptr, bool bgr=true)
Generates appropriate input accessor according to the specified graph parameters.
std::unique_ptr< graph::ITensorAccessor > get_output_accessor (const arm_compute::utils::CommonGraphParams &graph_parameters, size_t top_n=5, bool is_validation=false, std::ostream &output_stream=std::cout)
Generates appropriate output accessor according to the specified graph parameters.
std::unique_ptr< graph::ITensorAccessor > get_detection_output_accessor (const arm_compute::utils::CommonGraphParams &graph_parameters, std::vector< TensorShape > tensor_shapes, bool is_validation=false, std::ostream &output_stream=std::cout)
Generates appropriate output accessor according to the specified graph parameters.
std::unique_ptr< graph::ITensorAccessor > get_npy_output_accessor (const std::string &npy_path, TensorShape shape, DataType data_type, DataLayout data_layout=DataLayout::NCHW, std::ostream &output_stream=std::cout)
Generates appropriate npy output accessor according to the specified npy_path.
std::unique_ptr< graph::ITensorAccessor > get_save_npy_output_accessor (const std::string &npy_name, const bool is_fortran=false)
Generates appropriate npy output accessor according to the specified npy_path.
std::unique_ptr< graph::ITensorAccessor > get_print_output_accessor (std::ostream &output_stream=std::cout)
Generates print tensor accessor.
TensorShape permute_shape (TensorShape tensor_shape, DataLayout in_data_layout, DataLayout out_data_layout)
Permutes a given tensor shape given the input and output data layout.
graph::Target set_target_hint (int target)
Utility function to return the TargetHint.
Function Documentation
get_detection_output_accessor()
std::unique_ptr<graph::ITensorAccessor> arm_compute::graph_utils::get_detection_output_accessor (const arm_compute::utils::CommonGraphParams & graph_parameters, std::vector< TensorShape > tensor_shapes, bool is_validation = false, std::ostream & output_stream = std::cout) inline
Generates appropriate output accessor according to the specified graph parameters.
Note
If the output accessor is requested to validate the graph then ValidationOutputAccessor is generated else if output_accessor_file is empty will generate a DummyAccessor else will generate a TopNPredictionsAccessor
Parameters
[in] graph_parameters Graph parameters
[in] tensor_shapes Network input images tensor shapes.
[in] is_validation (Optional) Validation flag (default = false)
[out] output_stream (Optional) Output stream (default = std::cout)
Returns
An appropriate tensor accessor
Definition at line 577 of file GraphUtils.h.
 {
     ARM_COMPUTE_UNUSED(is_validation);
     if(!graph_parameters.validation_file.empty())
     {
         return std::make_unique<ValidationOutputAccessor>(graph_parameters.validation_file,
                                                           output_stream,
                                                           graph_parameters.validation_range_start,
                                                           graph_parameters.validation_range_end);
     }
     else if(graph_parameters.labels.empty())
     {
         return std::make_unique<DummyAccessor>(0);
     }
     else
     {
         return std::make_unique<DetectionOutputAccessor>(graph_parameters.labels, tensor_shapes, output_stream);
     }
 }
References ARM_COMPUTE_UNUSED, CommonGraphParams::labels, CommonGraphParams::validation_file, CommonGraphParams::validation_range_end, and CommonGraphParams::validation_range_start.
get_input_accessor()
std::unique_ptr<graph::ITensorAccessor> arm_compute::graph_utils::get_input_accessor (const arm_compute::utils::CommonGraphParams & graph_parameters, std::unique_ptr< IPreprocessor > preprocessor = nullptr, bool bgr = true) inline
Generates appropriate input accessor according to the specified graph parameters.
Parameters
[in] graph_parameters Graph parameters
[in] preprocessor (Optional) Preproccessor object
[in] bgr (Optional) Fill the first plane with blue channel (default = true)
Returns
An appropriate tensor accessor
Definition at line 497 of file GraphUtils.h.
 {
     if(!graph_parameters.validation_file.empty())
     {
         return std::make_unique<ValidationInputAccessor>(graph_parameters.validation_file,
                                                          graph_parameters.validation_path,
                                                          std::move(preprocessor),
                                                          bgr,
                                                          graph_parameters.validation_range_start,
                                                          graph_parameters.validation_range_end);
     }
     else
     {
         const std::string &image_file       = graph_parameters.image;
         const std::string &image_file_lower = lower_string(image_file);
         if(arm_compute::utility::endswith(image_file_lower, ".npy"))
         {
             return std::make_unique<NumPyBinLoader>(image_file, graph_parameters.data_layout);
         }
         else if(arm_compute::utility::endswith(image_file_lower, ".jpeg")
                 || arm_compute::utility::endswith(image_file_lower, ".jpg")
                 || arm_compute::utility::endswith(image_file_lower, ".ppm"))
         {
             return std::make_unique<ImageAccessor>(image_file, bgr, std::move(preprocessor));
         }
         else
         {
             return std::make_unique<DummyAccessor>();
         }
     }
 }
References CommonGraphParams::data_layout, arm_compute::utility::endswith(), CommonGraphParams::image, arm_compute::lower_string(), CommonGraphParams::validation_file, CommonGraphParams::validation_path, CommonGraphParams::validation_range_end, and CommonGraphParams::validation_range_start.
Referenced by GraphEdsr::setup().
get_npy_output_accessor()
std::unique_ptr<graph::ITensorAccessor> arm_compute::graph_utils::get_npy_output_accessor (const std::string & npy_path, TensorShape shape, DataType data_type, DataLayout data_layout = DataLayout::NCHW, std::ostream & output_stream = std::cout) inline
Generates appropriate npy output accessor according to the specified npy_path.
Note
If npy_path is empty will generate a DummyAccessor else will generate a NpyAccessor
Parameters
[in] npy_path Path to npy file.
[in] shape Shape of the numpy tensor data.
[in] data_type DataType of the numpy tensor data.
[in] data_layout DataLayout of the numpy tensor data.
[out] output_stream (Optional) Output stream
Returns
An appropriate tensor accessor
Definition at line 611 of file GraphUtils.h.
 {
     if(npy_path.empty())
     {
         return std::make_unique<DummyAccessor>(0);
     }
     else
     {
         return std::make_unique<NumPyAccessor>(npy_path, shape, data_type, data_layout, output_stream);
     }
 }
References arm_compute::test::validation::data_layout, arm_compute::test::validation::data_type, and arm_compute::test::validation::shape.
Referenced by GraphEdsr::setup().
get_output_accessor()
std::unique_ptr<graph::ITensorAccessor> arm_compute::graph_utils::get_output_accessor (const arm_compute::utils::CommonGraphParams & graph_parameters, size_t top_n = 5, bool is_validation = false, std::ostream & output_stream = std::cout) inline
Generates appropriate output accessor according to the specified graph parameters.
Note
If the output accessor is requested to validate the graph then ValidationOutputAccessor is generated else if output_accessor_file is empty will generate a DummyAccessor else will generate a TopNPredictionsAccessor
Parameters
[in] graph_parameters Graph parameters
[in] top_n (Optional) Number of output classes to print (default = 5)
[in] is_validation (Optional) Validation flag (default = false)
[out] output_stream (Optional) Output stream (default = std::cout)
Returns
An appropriate tensor accessor
Definition at line 543 of file GraphUtils.h.
 {
     ARM_COMPUTE_UNUSED(is_validation);
     if(!graph_parameters.validation_file.empty())
     {
         return std::make_unique<ValidationOutputAccessor>(graph_parameters.validation_file,
                                                           output_stream,
                                                           graph_parameters.validation_range_start,
                                                           graph_parameters.validation_range_end);
     }
     else if(graph_parameters.labels.empty())
     {
         return std::make_unique<DummyAccessor>(0);
     }
     else
     {
         return std::make_unique<TopNPredictionsAccessor>(graph_parameters.labels, top_n, output_stream);
     }
 }
References ARM_COMPUTE_UNUSED, CommonGraphParams::labels, CommonGraphParams::validation_file, CommonGraphParams::validation_range_end, and CommonGraphParams::validation_range_start.
get_print_output_accessor()
std::unique_ptr<graph::ITensorAccessor> arm_compute::graph_utils::get_print_output_accessor (std::ostream & output_stream = std::cout) inline
Generates print tensor accessor.
Parameters
[out] output_stream (Optional) Output stream
Returns
A print tensor accessor
Definition at line 651 of file GraphUtils.h.
 {
     return std::make_unique<PrintAccessor>(output_stream);
 }
get_random_accessor()
std::unique_ptr<graph::ITensorAccessor> arm_compute::graph_utils::get_random_accessor (PixelValue lower, PixelValue upper, const std::random_device::result_type seed = 0) inline
Generates appropriate random accessor.
Parameters
[in] lower Lower random values bound
[in] upper Upper random values bound
[in] seed Random generator seed
Returns
A ramdom accessor
Definition at line 460 of file GraphUtils.h.
 {
     return std::make_unique<RandomAccessor>(lower, upper, seed);
 }
get_save_npy_output_accessor()
std::unique_ptr<graph::ITensorAccessor> arm_compute::graph_utils::get_save_npy_output_accessor (const std::string & npy_name, const bool is_fortran = false) inline
Generates appropriate npy output accessor according to the specified npy_path.
Note
If npy_path is empty will generate a DummyAccessor else will generate a SaveNpyAccessor
Parameters
[in] npy_name Npy filename.
[in] is_fortran (Optional) If true, save tensor in fortran order.
Returns
An appropriate tensor accessor
Definition at line 633 of file GraphUtils.h.
 {
     if(npy_name.empty())
     {
         return std::make_unique<DummyAccessor>(0);
     }
     else
     {
         return std::make_unique<SaveNumPyAccessor>(npy_name, is_fortran);
     }
 }
get_weights_accessor()
std::unique_ptr<graph::ITensorAccessor> arm_compute::graph_utils::get_weights_accessor (const std::string & path, const std::string & data_file, DataLayout file_layout = DataLayout::NCHW) inline
Generates appropriate weights accessor according to the specified path.
Note
If path is empty will generate a DummyAccessor else will generate a NumPyBinLoader
Parameters
[in] path Path to the data files
[in] data_file Relative path to the data files from path
[in] file_layout (Optional) Layout of file. Defaults to NCHW
Returns
An appropriate tensor accessor
Definition at line 475 of file GraphUtils.h.
 {
     if(path.empty())
     {
         return std::make_unique<DummyAccessor>();
     }
     else
     {
         return std::make_unique<NumPyBinLoader>(path + data_file, file_layout);
     }
 }
References add_copyright::path.
Referenced by GraphEdsr::setup().
permute_shape()
TensorShape arm_compute::graph_utils::permute_shape (TensorShape tensor_shape, DataLayout in_data_layout, DataLayout out_data_layout) inline
Permutes a given tensor shape given the input and output data layout.
Parameters
[in] tensor_shape Tensor shape to permute
[in] in_data_layout Input tensor shape data layout
[in] out_data_layout Output tensor shape data layout
Returns
Permuted tensor shape
Definition at line 664 of file GraphUtils.h.
 {
     if(in_data_layout != out_data_layout)
     {
         arm_compute::PermutationVector perm_vec = (in_data_layout == DataLayout::NCHW) ? arm_compute::PermutationVector(2U, 0U, 1U) : arm_compute::PermutationVector(1U, 2U, 0U);
         arm_compute::permute(tensor_shape, perm_vec);
     }
     return tensor_shape;
 }
References arm_compute::NCHW, arm_compute::permute(), and arm_compute::utils::cast::U.
Referenced by GraphValidateExample< DepthwiseConvolutionLayer, DepthConvolutionOptions, DepthConvolutionVerifyAccessor >::do_setup(), and VerifyAccessor< D >::output_shape().
set_target_hint()
graph::Target arm_compute::graph_utils::set_target_hint (int target) inline
Utility function to return the TargetHint.
Parameters
[in] target Integer value which expresses the selected target. Must be 0 for Arm Neon or 1 for OpenCL or 2 (OpenCL with Tuner)
Returns
the TargetHint
Definition at line 680 of file GraphUtils.h.
 {
     ARM_COMPUTE_ERROR_ON_MSG(target > 2, "Invalid target. Target must be 0 (NEON), 1 (OpenCL), 2 (OpenCL + Tuner)");
     if((target == 1 || target == 2))
     {
         return graph::Target::CL;
     }
     else
     {
         return graph::Target::NEON;
     }
 }
References ARM_COMPUTE_ERROR_ON_MSG, arm_compute::graph::CL, and arm_compute::graph::NEON.