Compute Library: arm_compute::mlgo Namespace Reference
arm_compute::mlgo Namespace Reference
Namespaces
parser
Data Structures
struct Condition
A branch condition expression evaluating: feature op threshold.
struct GEMMConfigNative
GEMM Configuration for Native kernel.
struct GEMMConfigReshaped
GEMM Configuration for Reshaped kernel.
struct GEMMConfigReshapedOnlyRHS
GEMM Configuration for Reshaped Only RHS kernel.
struct GEMMShape
GEMM Shape used for query.
class HeuristicTree
A binary decision tree based heuristic.
class MLGOHeuristics
MLGOHeuristics for configuring GEMM kernels.
struct Query
Query interface.
Typedefs
using GEMMType = CLGEMMKernelType
Enumerations
enum HeuristicType { GEMM_Type, GEMM_Config_Native, GEMM_Config_Reshaped_Only_RHS, GEMM_Config_Reshaped }
Types of Heuristic (tree)
enum ConditionalOp {
EQ, LT, LE, GT,
GE
}
Conditional ops.
Functions
bool operator== (const GEMMConfigNative &lhs, const GEMMConfigNative &rhs)
bool operator== (const GEMMConfigReshapedOnlyRHS &lhs, const GEMMConfigReshapedOnlyRHS &rhs)
bool operator== (const GEMMConfigReshaped &lhs, const GEMMConfigReshaped &rhs)
std::ostream & operator<< (std::ostream &os, const GEMMConfigNative &config)
std::ostream & operator<< (std::ostream &os, const GEMMConfigReshapedOnlyRHS &config)
std::ostream & operator<< (std::ostream &os, const GEMMConfigReshaped &config)
std::ostream & operator<< (std::ostream &os, HeuristicType ht)
std::ostream & operator<< (std::ostream &os, DataType dt)
std::ostream & operator<< (std::ostream &os, const HeuristicTree::Index &index)
std::ostream & operator<< (std::ostream &os, const Query &query)
std::string to_string (const GEMMConfigNative &config)
std::string to_string (const GEMMConfigReshapedOnlyRHS &config)
std::string to_string (const GEMMConfigReshaped &config)
std::string to_string (const Query &query)
Typedef Documentation
GEMMType
using GEMMType = CLGEMMKernelType
Definition at line 43 of file Common.h.
Enumeration Type Documentation
ConditionalOp
enum ConditionalOp strong
Conditional ops.
Enumerator
EQ
Equal.
LT
Less than.
LE
Less than or equal to.
GT
Greater than.
GE
Greater than or equal to.
Definition at line 40 of file HeuristicTree.h.
 {
     EQ, /**< Equal */
     LT, /**< Less than */
     LE, /**< Less than or equal to */
     GT, /**< Greater than */
     GE, /**< Greater than or equal to */
 };
HeuristicType
enum HeuristicType strong
Types of Heuristic (tree)
Enumerator
GEMM_Type
About the type of gemm.
GEMM_Config_Native
About the gemm config for native kernel.
GEMM_Config_Reshaped_Only_RHS
About the gemm config for reshaped only rhs kernel.
GEMM_Config_Reshaped
About the gemm config for reshaped kernel.
Definition at line 35 of file Common.h.
 {
     GEMM_Type,                     /**< About the type of gemm */
     GEMM_Config_Native,            /**< About the gemm config for native kernel */
     GEMM_Config_Reshaped_Only_RHS, /**< About the gemm config for reshaped only rhs kernel */
     GEMM_Config_Reshaped           /**< About the gemm config for reshaped kernel */
 };
Function Documentation
operator<<() [1/7]
std::ostream & operator<< (std::ostream & os, const GEMMConfigNative & config)
Definition at line 43 of file Utils.cpp.
 {
     return os << "Native:{"
            << "m0: " << config.m0 << ", "
            << "n0: " << config.n0 << ", "
            << "k0: " << config.k0 << ", "
            << "}";
 }
References GEMMConfigNative::k0, GEMMConfigNative::m0, and GEMMConfigNative::n0.
operator<<() [2/7]
std::ostream & operator<< (std::ostream & os, const GEMMConfigReshapedOnlyRHS & config)
Definition at line 51 of file Utils.cpp.
 {
     return os << "ReshapedOnlyRHS:{"
            << "m0: " << config.m0 << ", "
            << "n0: " << config.n0 << ", "
            << "k0: " << config.k0 << ", "
            << "h0: " << config.h0 << ", "
            << "interleave_rhs: " << config.interleave_rhs << ", "
            << "transpose_rhs: " << config.transpose_rhs << ", "
            << "export_cl_image: " << config.export_cl_image
            << "}";
 }
References GEMMConfigReshapedOnlyRHS::export_cl_image, GEMMConfigReshapedOnlyRHS::h0, GEMMConfigReshapedOnlyRHS::interleave_rhs, GEMMConfigReshapedOnlyRHS::k0, GEMMConfigReshapedOnlyRHS::m0, GEMMConfigReshapedOnlyRHS::n0, and GEMMConfigReshapedOnlyRHS::transpose_rhs.
operator<<() [3/7]
std::ostream & operator<< (std::ostream & os, const GEMMConfigReshaped & config)
Definition at line 63 of file Utils.cpp.
 {
     return os << "Reshaped:{"
            << "m0: " << config.m0 << ", "
            << "n0: " << config.n0 << ", "
            << "k0: " << config.k0 << ", "
            << "v0: " << config.v0 << ", "
            << "h0: " << config.h0 << ", "
            << "interleave_lhs: " << config.interleave_lhs << ", "
            << "interleave_rhs: " << config.interleave_rhs << ", "
            << "transpose_rhs: " << config.transpose_rhs << ", "
            << "export_cl_image: " << config.export_cl_image
            << "}";
 }
References GEMMConfigReshaped::export_cl_image, GEMMConfigReshaped::h0, GEMMConfigReshaped::interleave_lhs, GEMMConfigReshaped::interleave_rhs, GEMMConfigReshaped::k0, GEMMConfigReshaped::m0, GEMMConfigReshaped::n0, GEMMConfigReshaped::transpose_rhs, and GEMMConfigReshaped::v0.
operator<<() [4/7]
std::ostream & operator<< (std::ostream & os, HeuristicType ht)
Definition at line 77 of file Utils.cpp.
 {
     switch(ht)
     {
         case HeuristicType::GEMM_Type:
         {
             os << "GEMM_Type";
             break;
         }
         case HeuristicType::GEMM_Config_Reshaped_Only_RHS:
         {
             os << "GEMM_Config_Reshaped_Only_RHS";
             break;
         }
         case HeuristicType::GEMM_Config_Reshaped:
         {
             os << "GEMM_Config_Reshaped";
             break;
         }
         default:
         {
             os << "Unknown";
             break;
         }
     }
     return os;
 }
References GEMM_Config_Reshaped, GEMM_Config_Reshaped_Only_RHS, and GEMM_Type.
operator<<() [5/7]
std::ostream & operator<< (std::ostream & os, DataType dt)
Definition at line 104 of file Utils.cpp.
 {
     switch(dt)
     {
         case DataType::F32:
         {
             os << "F32";
             break;
         }
         case DataType::F16:
         {
             os << "F16";
             break;
         }
         case DataType::QASYMM8:
         {
             os << "QASYMM8";
             break;
         }
         default:
         {
             os << "Unknown";
             break;
         }
     }
     return os;
 }
References dt, arm_compute::F16, arm_compute::F32, and arm_compute::QASYMM8.
operator<<() [6/7]
std::ostream & operator<< (std::ostream & os, const HeuristicTree::Index & index)
Definition at line 131 of file Utils.cpp.
 {
     HeuristicType ht;
     std::string   ip;
     DataType      dt;
     std::tie(ht, ip, dt) = index;
     os << "Index(";
     os << "HeuristicType=" << ht << ",";
     os << "IP=" << ip << ",";
     os << "DataType=" << dt;
     os << ")";
     return os;
 }
References dt.
operator<<() [7/7]
std::ostream & operator<< (std::ostream & os, const Query & query)
Definition at line 144 of file Utils.cpp.
 {
     os << "Query(";
     os << "IP=" << query.ip_target << ",";
     os << "DataType=" << query.data_type << ",";
     os << "M=" << query.m << ",";
     os << "N=" << query.n << ",";
     os << "K=" << query.k << ",";
     os << "B=" << query.b << ")";
     return os;
 }
References Query::b, Query::data_type, Query::ip_target, Query::k, Query::m, and Query::n.
operator==() [1/3]
bool operator== (const GEMMConfigNative & lhs, const GEMMConfigNative & rhs)
Definition at line 36 of file MLGOHeuristics.cpp.
 {
     return std::tie(lhs.m0, lhs.n0, lhs.k0) == std::tie(rhs.m0, rhs.n0, rhs.k0);
 }
References GEMMConfigNative::k0, GEMMConfigNative::m0, and GEMMConfigNative::n0.
operator==() [2/3]
bool operator== (const GEMMConfigReshapedOnlyRHS & lhs, const GEMMConfigReshapedOnlyRHS & rhs)
Definition at line 40 of file MLGOHeuristics.cpp.
 {
     return std::tie(lhs.m0, lhs.n0, lhs.k0, lhs.h0, lhs.interleave_rhs, lhs.transpose_rhs, lhs.export_cl_image) == std::tie(rhs.m0, rhs.n0, rhs.k0, rhs.h0, rhs.interleave_rhs, rhs.transpose_rhs,
                                                                                                                             rhs.export_cl_image);
 }
References GEMMConfigReshapedOnlyRHS::export_cl_image, GEMMConfigReshapedOnlyRHS::h0, GEMMConfigReshapedOnlyRHS::interleave_rhs, GEMMConfigReshapedOnlyRHS::k0, GEMMConfigReshapedOnlyRHS::m0, GEMMConfigReshapedOnlyRHS::n0, and GEMMConfigReshapedOnlyRHS::transpose_rhs.
operator==() [3/3]
bool operator== (const GEMMConfigReshaped & lhs, const GEMMConfigReshaped & rhs)
Definition at line 45 of file MLGOHeuristics.cpp.
 {
     return std::tie(lhs.m0, lhs.n0, lhs.k0, lhs.v0, lhs.h0, lhs.interleave_lhs, lhs.interleave_rhs, lhs.transpose_rhs, lhs.export_cl_image) == std::tie(rhs.m0, rhs.n0, rhs.k0, rhs.v0, rhs.h0,
             rhs.interleave_lhs, rhs.interleave_rhs, rhs.transpose_rhs, rhs.export_cl_image);
 }
References GEMMConfigReshaped::export_cl_image, GEMMConfigReshaped::h0, GEMMConfigReshaped::interleave_lhs, GEMMConfigReshaped::interleave_rhs, GEMMConfigReshaped::k0, GEMMConfigReshaped::m0, GEMMConfigReshaped::n0, GEMMConfigReshaped::transpose_rhs, and GEMMConfigReshaped::v0.
to_string() [1/4]
std::string to_string (const GEMMConfigNative & config)
Definition at line 156 of file Utils.cpp.
 {
     return to_str(config);
 }
Referenced by MLGOHeuristics::query_gemm_config_native(), MLGOHeuristics::query_gemm_config_reshaped(), MLGOHeuristics::query_gemm_config_reshaped_only_rhs(), and MLGOHeuristics::query_gemm_type().
to_string() [2/4]
std::string to_string (const GEMMConfigReshapedOnlyRHS & config)
Definition at line 161 of file Utils.cpp.
 {
     return to_str(config);
 }
to_string() [3/4]
std::string to_string (const GEMMConfigReshaped & config)
Definition at line 166 of file Utils.cpp.
 {
     return to_str(config);
 }
to_string() [4/4]
std::string to_string (const Query & query)
Definition at line 171 of file Utils.cpp.
 {
     return to_str(query);
 }