Compute Library: src/core/GLES_COMPUTE/OpenGLES.cpp File Reference
OpenGLES.cpp File Reference
#include "arm_compute/core/GLES_COMPUTE/OpenGLES.h"
#include <dlfcn.h>
#include <iostream>
#include <vector>
#include "./egl_entries.in"
#include "./gl_entries.in"
Macros
#define EGL_ENTRY(_api) _api = reinterpret_cast<_api##_func>(dlsym(egl_handle, #_api));
#define EGL_ENTRY(_api)
#define GL_ENTRY(_api) _api = reinterpret_cast<_api##_func>(eglGetProcAddress(#_api));
#define GL_ENTRY(_api)
#define EGL_ENTRY(_api) _api##_func _api = nullptr;
#define GL_ENTRY(_api) EGL_ENTRY(_api)
Typedefs
using eglGetProcAddress_func = __eglMustCastToProperFunctionPointerType EGLAPIENTRY(*)(const char *procname)
using eglBindAPI_func = EGLBoolean EGLAPIENTRY(*)(EGLenum api)
using eglChooseConfig_func = EGLBoolean EGLAPIENTRY(*)(EGLDisplay dpy, const EGLint *attrib_list, EGLConfig *configs, EGLint config_size, EGLint *num_config)
using eglCreateContext_func = EGLContext EGLAPIENTRY(*)(EGLDisplay dpy, EGLConfig config, EGLContext share_context, const EGLint *attrib_list)
using eglDestroyContext_func = EGLBoolean EGLAPIENTRY(*)(EGLDisplay dpy, EGLContext ctx)
using eglGetDisplay_func = EGLDisplay EGLAPIENTRY(*)(EGLNativeDisplayType display_id)
using eglInitialize_func = EGLBoolean EGLAPIENTRY(*)(EGLDisplay dpy, EGLint *major, EGLint *minor)
using eglMakeCurrent_func = EGLBoolean EGLAPIENTRY(*)(EGLDisplay dpy, EGLSurface draw, EGLSurface read, EGLContext ctx)
using eglTerminate_func = EGLBoolean EGLAPIENTRY(*)(EGLDisplay dpy)
using eglGetError_func = EGLint EGLAPIENTRY(*)()
using eglQueryString_func = char const *EGLAPIENTRY(*)(EGLDisplay dpy, EGLint name)
using glAttachShader_func = void GL_APIENTRY(*)(GLuint program, GLuint shader)
using glCompileShader_func = void GL_APIENTRY(*)(GLuint shader)
using glCreateProgram_func = GLuint GL_APIENTRY(*)()
using glCreateShader_func = GLuint GL_APIENTRY(*)(GLenum type)
using glDeleteProgram_func = void GL_APIENTRY(*)(GLuint program)
using glDeleteShader_func = void GL_APIENTRY(*)(GLuint shader)
using glDetachShader_func = void GL_APIENTRY(*)(GLuint program, GLuint shader)
using glGetProgramInfoLog_func = void GL_APIENTRY(*)(GLuint program, GLsizei bufsize, GLsizei *length, GLchar *infolog)
using glGetProgramiv_func = void GL_APIENTRY(*)(GLuint program, GLenum pname, GLint *params)
using glGetShaderInfoLog_func = void GL_APIENTRY(*)(GLuint shader, GLsizei bufsize, GLsizei *length, GLchar *infolog)
using glGetShaderiv_func = void GL_APIENTRY(*)(GLuint shader, GLenum pname, GLint *params)
using glLinkProgram_func = void GL_APIENTRY(*)(GLuint program)
using glShaderSource_func = void GL_APIENTRY(*)(GLuint shader, GLsizei count, const GLchar *const *string, const GLint *length)
using glUseProgram_func = void GL_APIENTRY(*)(GLuint program)
using glBindBuffer_func = void GL_APIENTRY(*)(GLenum target, GLuint buffer)
using glBindBufferBase_func = void GL_APIENTRY(*)(GLenum target, GLuint index, GLuint buffer)
using glBufferData_func = void GL_APIENTRY(*)(GLenum target, GLsizeiptr size, const GLvoid *data, GLenum usage)
using glDeleteBuffers_func = void GL_APIENTRY(*)(GLsizei n, const GLuint *buffers)
using glDispatchCompute_func = void GL_APIENTRY(*)(GLuint num_groups_x, GLuint num_groups_y, GLuint num_groups_z)
using glFlush_func = void GL_APIENTRY(*)()
using glGenBuffers_func = void GL_APIENTRY(*)(GLsizei n, GLuint *buffers)
using glGetProgramResourceIndex_func = GLuint GL_APIENTRY(*)(GLuint program, GLenum programInterface, const GLchar *name)
using glGetUniformLocation_func = GLint GL_APIENTRY(*)(GLuint program, const GLchar *name)
using glMapBufferRange_func = void *GL_APIENTRY(*)(GLenum target, GLintptr offset, GLsizeiptr length, GLbitfield access)
using glMemoryBarrier_func = void GL_APIENTRY(*)(GLbitfield barriers)
using glUniform1ui_func = void GL_APIENTRY(*)(GLint location, GLuint v0)
using glUnmapBuffer_func = GLboolean GL_APIENTRY(*)(GLenum target)
using glGetError_func = GLenum GL_APIENTRY(*)()
using glGetString_func = const GLubyte *GL_APIENTRY(*)(GLenum name)
using glGetActiveUniformBlockiv_func = void GL_APIENTRY(*)(GLuint program, GLuint uniformBlockIndex, GLenum pname, GLint *params)
using glUniformBlockBinding_func = void GL_APIENTRY(*)(GLuint program, GLuint uniformBlockIndex, GLuint uniformBlockBinding)
using glGetUniformBlockIndex_func = GLuint GL_APIENTRY(*)(GLuint program, const GLchar *uniformBlockName)
using glGenTextures_func = void GL_APIENTRY(*)(GLsizei n, GLuint *textures)
using glDeleteTextures_func = void GL_APIENTRY(*)(GLsizei n, const GLuint *textures)
using glBindTexture_func = void GL_APIENTRY(*)(GLenum target, GLuint texture)
using glTexImage2D_func = void GL_APIENTRY(*)(GLenum target, GLint level, GLint internalformat, GLsizei width, GLsizei height, GLint border, GLenum format, GLenum type, const GLvoid *pixels)
using glGenFramebuffers_func = void GL_APIENTRY(*)(GLsizei n, GLuint *framebuffers)
using glDeleteFramebuffers_func = void GL_APIENTRY(*)(GLsizei n, const GLuint *framebuffers)
using glBindFramebuffer_func = void GL_APIENTRY(*)(GLenum target, GLuint framebuffer)
using glFramebufferTexture2D_func = void GL_APIENTRY(*)(GLenum target, GLenum attachment, GLenum textarget, GLuint texture, GLint level)
Functions
__eglMustCastToProperFunctionPointerType EGLAPIENTRY eglGetProcAddress (const char *procname)
EGLBoolean EGLAPIENTRY eglBindAPI (EGLenum api)
EGLBoolean EGLAPIENTRY eglChooseConfig (EGLDisplay dpy, const EGLint *attrib_list, EGLConfig *configs, EGLint config_size, EGLint *num_config)
EGLContext EGLAPIENTRY eglCreateContext (EGLDisplay dpy, EGLConfig config, EGLContext share_context, const EGLint *attrib_list)
EGLBoolean EGLAPIENTRY eglDestroyContext (EGLDisplay dpy, EGLContext ctx)
EGLDisplay EGLAPIENTRY eglGetDisplay (EGLNativeDisplayType display_id)
EGLBoolean EGLAPIENTRY eglInitialize (EGLDisplay dpy, EGLint *major, EGLint *minor)
EGLBoolean EGLAPIENTRY eglMakeCurrent (EGLDisplay dpy, EGLSurface draw, EGLSurface read, EGLContext ctx)
EGLBoolean EGLAPIENTRY eglTerminate (EGLDisplay dpy)
EGLint EGLAPIENTRY eglGetError ()
char const *EGLAPIENTRY eglQueryString (EGLDisplay dpy, EGLint name)
void GL_APIENTRY glAttachShader (GLuint program, GLuint shader)
void GL_APIENTRY glCompileShader (GLuint shader)
GLuint GL_APIENTRY glCreateProgram ()
GLuint GL_APIENTRY glCreateShader (GLenum type)
void GL_APIENTRY glDeleteProgram (GLuint program)
void GL_APIENTRY glDeleteShader (GLuint shader)
void GL_APIENTRY glDetachShader (GLuint program, GLuint shader)
void GL_APIENTRY glGetProgramInfoLog (GLuint program, GLsizei bufSize, GLsizei *length, GLchar *infoLog)
void GL_APIENTRY glGetProgramiv (GLuint program, GLenum pname, GLint *params)
void GL_APIENTRY glGetShaderInfoLog (GLuint shader, GLsizei bufSize, GLsizei *length, GLchar *infoLog)
void GL_APIENTRY glGetShaderiv (GLuint shader, GLenum pname, GLint *params)
void GL_APIENTRY glLinkProgram (GLuint program)
void GL_APIENTRY glShaderSource (GLuint shader, GLsizei count, const GLchar *const *string, const GLint *length)
void GL_APIENTRY glUseProgram (GLuint program)
void GL_APIENTRY glBindBuffer (GLenum target, GLuint buffer)
void GL_APIENTRY glBindBufferBase (GLenum target, GLuint index, GLuint buffer)
void GL_APIENTRY glBufferData (GLenum target, GLsizeiptr size, const GLvoid *data, GLenum usage)
void GL_APIENTRY glDeleteBuffers (GLsizei n, const GLuint *buffers)
void GL_APIENTRY glDispatchCompute (GLuint num_groups_x, GLuint num_groups_y, GLuint num_groups_z)
void GL_APIENTRY glFlush (void)
void GL_APIENTRY glGenBuffers (GLsizei n, GLuint *buffers)
GLuint GL_APIENTRY glGetProgramResourceIndex (GLuint program, GLenum programInterface, const GLchar *name)
GLint GL_APIENTRY glGetUniformLocation (GLuint program, const GLchar *name)
void *GL_APIENTRY glMapBufferRange (GLenum target, GLintptr offset, GLsizeiptr length, GLbitfield access)
void GL_APIENTRY glMemoryBarrier (GLbitfield barriers)
void GL_APIENTRY glUniform1ui (GLint location, GLuint v0)
GLboolean GL_APIENTRY glUnmapBuffer (GLenum target)
GLenum GL_APIENTRY glGetError (void)
const GLubyte *GL_APIENTRY glGetString (GLenum name)
void GL_APIENTRY glGetActiveUniformBlockiv (GLuint program, GLuint uniformBlockIndex, GLenum pname, GLint *params)
void GL_APIENTRY glUniformBlockBinding (GLuint program, GLuint uniformBlockIndex, GLuint uniformBlockBinding)
GLuint GL_APIENTRY glGetUniformBlockIndex (GLuint program, const GLchar *uniformBlockName)
void GL_APIENTRY glGenTextures (GLsizei n, GLuint *textures)
void GL_APIENTRY glDeleteTextures (GLsizei n, const GLuint *textures)
void GL_APIENTRY glBindTexture (GLenum target, GLuint texture)
void GL_APIENTRY glTexImage2D (GLenum target, GLint level, GLint internalformat, GLsizei width, GLsizei height, GLint border, GLenum format, GLenum type, const GLvoid *pixels)
void GL_APIENTRY glGenFramebuffers (GLsizei n, GLuint *framebuffers)
void GL_APIENTRY glDeleteFramebuffers (GLsizei n, const GLuint *framebuffers)
void GL_APIENTRY glBindFramebuffer (GLenum target, GLuint framebuffer)
void GL_APIENTRY glFramebufferTexture2D (GLenum target, GLenum attachment, GLenum textarget, GLuint texture, GLint level)
Macro Definition Documentation
EGL_ENTRY [1/3]
#define EGL_ENTRY (_api) _api = reinterpret_cast<_api##_func>(dlsym(egl_handle, #_api));
Definition at line 152 of file OpenGLES.cpp.
EGL_ENTRY [2/3]
#define EGL_ENTRY (_api)
Value:
if((_api) == nullptr) \
        (_api) = reinterpret_cast<_api##_func>(eglGetProcAddress(#_api));
Definition at line 152 of file OpenGLES.cpp.
EGL_ENTRY [3/3]
#define EGL_ENTRY (_api) _api##_func _api = nullptr;
Definition at line 152 of file OpenGLES.cpp.
GL_ENTRY [1/3]
#define GL_ENTRY (_api) _api = reinterpret_cast<_api##_func>(eglGetProcAddress(#_api));
Definition at line 153 of file OpenGLES.cpp.
GL_ENTRY [2/3]
#define GL_ENTRY (_api)
Value:
if((_api) == nullptr) \
        (_api) = reinterpret_cast<_api##_func>(dlsym(handle, #_api));
Definition at line 153 of file OpenGLES.cpp.
GL_ENTRY [3/3]
#define GL_ENTRY (_api) EGL_ENTRY(_api)
Definition at line 153 of file OpenGLES.cpp.
Typedef Documentation
eglBindAPI_func
using eglBindAPI_func = EGLBoolean EGLAPIENTRY (*)(EGLenum api)
Definition at line 32 of file OpenGLES.cpp.
eglChooseConfig_func
using eglChooseConfig_func = EGLBoolean EGLAPIENTRY (*)(EGLDisplay dpy, const EGLint *attrib_list, EGLConfig *configs, EGLint config_size, EGLint *num_config)
Definition at line 33 of file OpenGLES.cpp.
eglCreateContext_func
using eglCreateContext_func = EGLContext EGLAPIENTRY (*)(EGLDisplay dpy, EGLConfig config, EGLContext share_context, const EGLint *attrib_list)
Definition at line 34 of file OpenGLES.cpp.
eglDestroyContext_func
using eglDestroyContext_func = EGLBoolean EGLAPIENTRY (*)(EGLDisplay dpy, EGLContext ctx)
Definition at line 35 of file OpenGLES.cpp.
eglGetDisplay_func
using eglGetDisplay_func = EGLDisplay EGLAPIENTRY (*)(EGLNativeDisplayType display_id)
Definition at line 36 of file OpenGLES.cpp.
eglGetError_func
using eglGetError_func = EGLint EGLAPIENTRY (*)()
Definition at line 40 of file OpenGLES.cpp.
eglGetProcAddress_func
using eglGetProcAddress_func = __eglMustCastToProperFunctionPointerType EGLAPIENTRY (*)(const char *procname)
Definition at line 31 of file OpenGLES.cpp.
eglInitialize_func
using eglInitialize_func = EGLBoolean EGLAPIENTRY (*)(EGLDisplay dpy, EGLint *major, EGLint *minor)
Definition at line 37 of file OpenGLES.cpp.
eglMakeCurrent_func
using eglMakeCurrent_func = EGLBoolean EGLAPIENTRY (*)(EGLDisplay dpy, EGLSurface draw, EGLSurface read, EGLContext ctx)
Definition at line 38 of file OpenGLES.cpp.
eglQueryString_func
using eglQueryString_func = char const * EGLAPIENTRY (*)(EGLDisplay dpy, EGLint name)
Definition at line 41 of file OpenGLES.cpp.
eglTerminate_func
using eglTerminate_func = EGLBoolean EGLAPIENTRY (*)(EGLDisplay dpy)
Definition at line 39 of file OpenGLES.cpp.
glAttachShader_func
using glAttachShader_func = void GL_APIENTRY (*)(GLuint program, GLuint shader)
Definition at line 42 of file OpenGLES.cpp.
glBindBuffer_func
using glBindBuffer_func = void GL_APIENTRY (*)(GLenum target, GLuint buffer)
Definition at line 56 of file OpenGLES.cpp.
glBindBufferBase_func
using glBindBufferBase_func = void GL_APIENTRY (*)(GLenum target, GLuint index, GLuint buffer)
Definition at line 57 of file OpenGLES.cpp.
glBindFramebuffer_func
using glBindFramebuffer_func = void GL_APIENTRY (*)(GLenum target, GLuint framebuffer)
Definition at line 81 of file OpenGLES.cpp.
glBindTexture_func
using glBindTexture_func = void GL_APIENTRY (*)(GLenum target, GLuint texture)
Definition at line 76 of file OpenGLES.cpp.
glBufferData_func
using glBufferData_func = void GL_APIENTRY (*)(GLenum target, GLsizeiptr size, const GLvoid *data, GLenum usage)
Definition at line 58 of file OpenGLES.cpp.
glCompileShader_func
using glCompileShader_func = void GL_APIENTRY (*)(GLuint shader)
Definition at line 43 of file OpenGLES.cpp.
glCreateProgram_func
using glCreateProgram_func = GLuint GL_APIENTRY (*)()
Definition at line 44 of file OpenGLES.cpp.
glCreateShader_func
using glCreateShader_func = GLuint GL_APIENTRY (*)(GLenum type)
Definition at line 45 of file OpenGLES.cpp.
glDeleteBuffers_func
using glDeleteBuffers_func = void GL_APIENTRY (*)(GLsizei n, const GLuint *buffers)
Definition at line 59 of file OpenGLES.cpp.
glDeleteFramebuffers_func
using glDeleteFramebuffers_func = void GL_APIENTRY (*)(GLsizei n, const GLuint *framebuffers)
Definition at line 80 of file OpenGLES.cpp.
glDeleteProgram_func
using glDeleteProgram_func = void GL_APIENTRY (*)(GLuint program)
Definition at line 46 of file OpenGLES.cpp.
glDeleteShader_func
using glDeleteShader_func = void GL_APIENTRY (*)(GLuint shader)
Definition at line 47 of file OpenGLES.cpp.
glDeleteTextures_func
using glDeleteTextures_func = void GL_APIENTRY (*)(GLsizei n, const GLuint *textures)
Definition at line 75 of file OpenGLES.cpp.
glDetachShader_func
using glDetachShader_func = void GL_APIENTRY (*)(GLuint program, GLuint shader)
Definition at line 48 of file OpenGLES.cpp.
glDispatchCompute_func
using glDispatchCompute_func = void GL_APIENTRY (*)(GLuint num_groups_x, GLuint num_groups_y, GLuint num_groups_z)
Definition at line 60 of file OpenGLES.cpp.
glFlush_func
using glFlush_func = void GL_APIENTRY (*)()
Definition at line 61 of file OpenGLES.cpp.
glFramebufferTexture2D_func
using glFramebufferTexture2D_func = void GL_APIENTRY (*)(GLenum target, GLenum attachment, GLenum textarget, GLuint texture, GLint level)
Definition at line 82 of file OpenGLES.cpp.
glGenBuffers_func
using glGenBuffers_func = void GL_APIENTRY (*)(GLsizei n, GLuint *buffers)
Definition at line 62 of file OpenGLES.cpp.
glGenFramebuffers_func
using glGenFramebuffers_func = void GL_APIENTRY (*)(GLsizei n, GLuint *framebuffers)
Definition at line 79 of file OpenGLES.cpp.
glGenTextures_func
using glGenTextures_func = void GL_APIENTRY (*)(GLsizei n, GLuint *textures)
Definition at line 74 of file OpenGLES.cpp.
glGetActiveUniformBlockiv_func
using glGetActiveUniformBlockiv_func = void GL_APIENTRY (*)(GLuint program, GLuint uniformBlockIndex, GLenum pname, GLint *params)
Definition at line 71 of file OpenGLES.cpp.
glGetError_func
using glGetError_func = GLenum GL_APIENTRY (*)()
Definition at line 69 of file OpenGLES.cpp.
glGetProgramInfoLog_func
using glGetProgramInfoLog_func = void GL_APIENTRY (*)(GLuint program, GLsizei bufsize, GLsizei *length, GLchar *infolog)
Definition at line 49 of file OpenGLES.cpp.
glGetProgramiv_func
using glGetProgramiv_func = void GL_APIENTRY (*)(GLuint program, GLenum pname, GLint *params)
Definition at line 50 of file OpenGLES.cpp.
glGetProgramResourceIndex_func
using glGetProgramResourceIndex_func = GLuint GL_APIENTRY (*)(GLuint program, GLenum programInterface, const GLchar *name)
Definition at line 63 of file OpenGLES.cpp.
glGetShaderInfoLog_func
using glGetShaderInfoLog_func = void GL_APIENTRY (*)(GLuint shader, GLsizei bufsize, GLsizei *length, GLchar *infolog)
Definition at line 51 of file OpenGLES.cpp.
glGetShaderiv_func
using glGetShaderiv_func = void GL_APIENTRY (*)(GLuint shader, GLenum pname, GLint *params)
Definition at line 52 of file OpenGLES.cpp.
glGetString_func
using glGetString_func = const GLubyte * GL_APIENTRY (*)(GLenum name)
Definition at line 70 of file OpenGLES.cpp.
glGetUniformBlockIndex_func
using glGetUniformBlockIndex_func = GLuint GL_APIENTRY (*)(GLuint program, const GLchar *uniformBlockName)
Definition at line 73 of file OpenGLES.cpp.
glGetUniformLocation_func
using glGetUniformLocation_func = GLint GL_APIENTRY (*)(GLuint program, const GLchar *name)
Definition at line 64 of file OpenGLES.cpp.
glLinkProgram_func
using glLinkProgram_func = void GL_APIENTRY (*)(GLuint program)
Definition at line 53 of file OpenGLES.cpp.
glMapBufferRange_func
using glMapBufferRange_func = void *GL_APIENTRY (*)(GLenum target, GLintptr offset, GLsizeiptr length, GLbitfield access)
Definition at line 65 of file OpenGLES.cpp.
glMemoryBarrier_func
using glMemoryBarrier_func = void GL_APIENTRY (*)(GLbitfield barriers)
Definition at line 66 of file OpenGLES.cpp.
glShaderSource_func
using glShaderSource_func = void GL_APIENTRY (*)(GLuint shader, GLsizei count, const GLchar *const *string, const GLint *length)
Definition at line 54 of file OpenGLES.cpp.
glTexImage2D_func
using glTexImage2D_func = void GL_APIENTRY (*)(GLenum target, GLint level, GLint internalformat, GLsizei width, GLsizei height, GLint border, GLenum format, GLenum type, const GLvoid *pixels)
Definition at line 78 of file OpenGLES.cpp.
glUniform1ui_func
using glUniform1ui_func = void GL_APIENTRY (*)(GLint location, GLuint v0)
Definition at line 67 of file OpenGLES.cpp.
glUniformBlockBinding_func
using glUniformBlockBinding_func = void GL_APIENTRY (*)(GLuint program, GLuint uniformBlockIndex, GLuint uniformBlockBinding)
Definition at line 72 of file OpenGLES.cpp.
glUnmapBuffer_func
using glUnmapBuffer_func = GLboolean GL_APIENTRY (*)(GLenum target)
Definition at line 68 of file OpenGLES.cpp.
glUseProgram_func
using glUseProgram_func = void GL_APIENTRY (*)(GLuint program)
Definition at line 55 of file OpenGLES.cpp.
Function Documentation
eglBindAPI()
EGLBoolean EGLAPIENTRY eglBindAPI (EGLenum api)
Definition at line 178 of file OpenGLES.cpp.
 {
     auto func = GLESSymbols::get().eglBindAPI;
     if(func != nullptr)
     {
         return func(api);
     }
     else
     {
         return EGL_FALSE;
     }
 }
eglChooseConfig()
EGLBoolean EGLAPIENTRY eglChooseConfig (EGLDisplay dpy, const EGLint * attrib_list, EGLConfig * configs, EGLint config_size, EGLint * num_config)
Definition at line 191 of file OpenGLES.cpp.
 {
     auto func = GLESSymbols::get().eglChooseConfig;
     if(func != nullptr)
     {
         return func(dpy, attrib_list, configs, config_size, num_config);
     }
     else
     {
         return EGL_FALSE;
     }
 }
eglCreateContext()
EGLContext EGLAPIENTRY eglCreateContext (EGLDisplay dpy, EGLConfig config, EGLContext share_context, const EGLint * attrib_list)
Definition at line 204 of file OpenGLES.cpp.
 {
     auto func = GLESSymbols::get().eglCreateContext;
     if(func != nullptr)
     {
         return func(dpy, config, share_context, attrib_list);
     }
     else
     {
         return nullptr;
     }
 }
eglDestroyContext()
EGLBoolean EGLAPIENTRY eglDestroyContext (EGLDisplay dpy, EGLContext ctx)
Definition at line 217 of file OpenGLES.cpp.
 {
     auto func = GLESSymbols::get().eglDestroyContext;
     if(func != nullptr)
     {
         return func(dpy, ctx);
     }
     else
     {
         return EGL_FALSE;
     }
 }
eglGetDisplay()
EGLDisplay EGLAPIENTRY eglGetDisplay (EGLNativeDisplayType display_id)
Definition at line 230 of file OpenGLES.cpp.
 {
     auto func = GLESSymbols::get().eglGetDisplay;
     if(func != nullptr)
     {
         return func(display_id);
     }
     else
     {
         return nullptr;
     }
 }
eglGetError()
EGLint EGLAPIENTRY eglGetError ()
Definition at line 282 of file OpenGLES.cpp.
 {
     auto func = GLESSymbols::get().eglGetError;
     if(func != nullptr)
     {
         return func();
     }
     else
     {
         return GL_NO_ERROR;
     }
 }
eglGetProcAddress()
__eglMustCastToProperFunctionPointerType EGLAPIENTRY eglGetProcAddress (const char * procname)
Definition at line 165 of file OpenGLES.cpp.
 {
     auto func = GLESSymbols::get().eglGetProcAddress;
     if(func != nullptr)
     {
         return func(procname);
     }
     else
     {
         return nullptr;
     }
 }
eglInitialize()
EGLBoolean EGLAPIENTRY eglInitialize (EGLDisplay dpy, EGLint * major, EGLint * minor)
Definition at line 243 of file OpenGLES.cpp.
 {
     auto func = GLESSymbols::get().eglInitialize;
     if(func != nullptr)
     {
         return func(dpy, major, minor);
     }
     else
     {
         return EGL_FALSE;
     }
 }
eglMakeCurrent()
EGLBoolean EGLAPIENTRY eglMakeCurrent (EGLDisplay dpy, EGLSurface draw, EGLSurface read, EGLContext ctx)
Definition at line 256 of file OpenGLES.cpp.
 {
     auto func = GLESSymbols::get().eglMakeCurrent;
     if(func != nullptr)
     {
         return func(dpy, draw, read, ctx);
     }
     else
     {
         return EGL_FALSE;
     }
 }
Referenced by GCKernelLibrary::init(), and GCKernelLibrary::set_context().
eglQueryString()
char const* EGLAPIENTRY eglQueryString (EGLDisplay dpy, EGLint name)
Definition at line 295 of file OpenGLES.cpp.
 {
     auto func = GLESSymbols::get().eglQueryString;
     if(func != nullptr)
     {
         return func(dpy, name);
     }
     else
     {
         return nullptr;
     }
 }
eglTerminate()
EGLBoolean EGLAPIENTRY eglTerminate (EGLDisplay dpy)
Definition at line 269 of file OpenGLES.cpp.
 {
     auto func = GLESSymbols::get().eglTerminate;
     if(func != nullptr)
     {
         return func(dpy);
     }
     else
     {
         return EGL_FALSE;
     }
 }
glAttachShader()
void GL_APIENTRY glAttachShader (GLuint program, GLuint shader)
Definition at line 308 of file OpenGLES.cpp.
 {
     auto func = GLESSymbols::get().glAttachShader;
     if(func != nullptr)
     {
         return func(program, shader);
     }
     else
     {
         return;
     }
 }
Referenced by GCProgram::link_program().
glBindBuffer()
void GL_APIENTRY glBindBuffer (GLenum target, GLuint buffer)
Definition at line 490 of file OpenGLES.cpp.
 {
     auto func = GLESSymbols::get().glBindBuffer;
     if(func != nullptr)
     {
         return func(target, buffer);
     }
     else
     {
         return;
     }
 }
Referenced by GCBufferAllocator::allocate(), GCKernel::cleanup(), GCBufferMemoryRegion::GCBufferMemoryRegion(), GCBufferMemoryRegion::map(), GCBufferMemoryRegion::unmap(), and GCKernel::update_shader_params().
glBindBufferBase()
void GL_APIENTRY glBindBufferBase (GLenum target, GLuint index, GLuint buffer)
Definition at line 503 of file OpenGLES.cpp.
 {
     auto func = GLESSymbols::get().glBindBufferBase;
     if(func != nullptr)
     {
         return func(target, index, buffer);
     }
     else
     {
         return;
     }
 }
Referenced by GCKernel::update_shader_params().
glBindFramebuffer()
void GL_APIENTRY glBindFramebuffer (GLenum target, GLuint framebuffer)
Definition at line 802 of file OpenGLES.cpp.
 {
     auto func = GLESSymbols::get().glBindFramebuffer;
     if(func != nullptr)
     {
         return func(target, framebuffer);
     }
     else
     {
         return;
     }
 }
Referenced by GCKernelLibrary::setup_dummy_fbo().
glBindTexture()
void GL_APIENTRY glBindTexture (GLenum target, GLuint texture)
Definition at line 750 of file OpenGLES.cpp.
 {
     auto func = GLESSymbols::get().glBindTexture;
     if(func != nullptr)
     {
         return func(target, texture);
     }
     else
     {
         return;
     }
 }
Referenced by GCKernelLibrary::setup_dummy_fbo().
glBufferData()
void GL_APIENTRY glBufferData (GLenum target, GLsizeiptr size, const GLvoid * data, GLenum usage)
Definition at line 516 of file OpenGLES.cpp.
 {
     auto func = GLESSymbols::get().glBufferData;
     if(func != nullptr)
     {
         return func(target, size, data, usage);
     }
     else
     {
         return;
     }
 }
Referenced by GCBufferAllocator::allocate(), GCBufferMemoryRegion::GCBufferMemoryRegion(), and GCKernel::update_shader_params().
glCompileShader()
void GL_APIENTRY glCompileShader (GLuint shader)
Definition at line 321 of file OpenGLES.cpp.
 {
     auto func = GLESSymbols::get().glCompileShader;
     if(func != nullptr)
     {
         return func(shader);
     }
     else
     {
         return;
     }
 }
Referenced by GCProgram::compile_shader().
glCreateProgram()
GLuint GL_APIENTRY glCreateProgram ()
Definition at line 334 of file OpenGLES.cpp.
 {
     auto func = GLESSymbols::get().glCreateProgram;
     if(func != nullptr)
     {
         return func();
     }
     else
     {
         return 0;
     }
 }
Referenced by GCProgram::link_program().
glCreateShader()
GLuint GL_APIENTRY glCreateShader (GLenum type)
Definition at line 347 of file OpenGLES.cpp.
 {
     auto func = GLESSymbols::get().glCreateShader;
     if(func != nullptr)
     {
         return func(type);
     }
     else
     {
         return 0;
     }
 }
Referenced by GCProgram::compile_shader().
glDeleteBuffers()
void GL_APIENTRY glDeleteBuffers (GLsizei n, const GLuint * buffers)
Definition at line 529 of file OpenGLES.cpp.
 {
     auto func = GLESSymbols::get().glDeleteBuffers;
     if(func != nullptr)
     {
         return func(n, buffers);
     }
     else
     {
         return;
     }
 }
Referenced by GCKernel::cleanup(), GCBufferAllocator::free(), and GCBufferMemoryRegion::~GCBufferMemoryRegion().
glDeleteFramebuffers()
void GL_APIENTRY glDeleteFramebuffers (GLsizei n, const GLuint * framebuffers)
Definition at line 789 of file OpenGLES.cpp.
 {
     auto func = GLESSymbols::get().glDeleteFramebuffers;
     if(func != nullptr)
     {
         return func(n, framebuffers);
     }
     else
     {
         return;
     }
 }
glDeleteProgram()
void GL_APIENTRY glDeleteProgram (GLuint program)
Definition at line 360 of file OpenGLES.cpp.
 {
     auto func = GLESSymbols::get().glDeleteProgram;
     if(func != nullptr)
     {
         return func(program);
     }
     else
     {
         return;
     }
 }
Referenced by GCKernel::cleanup().
glDeleteShader()
void GL_APIENTRY glDeleteShader (GLuint shader)
Definition at line 373 of file OpenGLES.cpp.
 {
     auto func = GLESSymbols::get().glDeleteShader;
     if(func != nullptr)
     {
         return func(shader);
     }
     else
     {
         return;
     }
 }
Referenced by GCProgram::link_program().
glDeleteTextures()
void GL_APIENTRY glDeleteTextures (GLsizei n, const GLuint * textures)
Definition at line 737 of file OpenGLES.cpp.
 {
     auto func = GLESSymbols::get().glDeleteTextures;
     if(func != nullptr)
     {
         return func(n, textures);
     }
     else
     {
         return;
     }
 }
glDetachShader()
void GL_APIENTRY glDetachShader (GLuint program, GLuint shader)
Definition at line 386 of file OpenGLES.cpp.
 {
     auto func = GLESSymbols::get().glDetachShader;
     if(func != nullptr)
     {
         return func(program, shader);
     }
     else
     {
         return;
     }
 }
Referenced by GCProgram::link_program().
glDispatchCompute()
void GL_APIENTRY glDispatchCompute (GLuint num_groups_x, GLuint num_groups_y, GLuint num_groups_z)
Definition at line 542 of file OpenGLES.cpp.
 {
     auto func = GLESSymbols::get().glDispatchCompute;
     if(func != nullptr)
     {
         return func(num_groups_x, num_groups_y, num_groups_z);
     }
     else
     {
         return;
     }
 }
Referenced by arm_compute::enqueue().
glFlush()
void GL_APIENTRY glFlush (void)
Definition at line 555 of file OpenGLES.cpp.
 {
     auto func = GLESSymbols::get().glFlush;
     if(func != nullptr)
     {
         return func();
     }
     else
     {
         return;
     }
 }
Referenced by GCScheduler::dispatch().
glFramebufferTexture2D()
void GL_APIENTRY glFramebufferTexture2D (GLenum target, GLenum attachment, GLenum textarget, GLuint texture, GLint level)
Definition at line 815 of file OpenGLES.cpp.
 {
     auto func = GLESSymbols::get().glFramebufferTexture2D;
     if(func != nullptr)
     {
         return func(target, attachment, textarget, texture, level);
     }
     else
     {
         return;
     }
 }
Referenced by GCKernelLibrary::setup_dummy_fbo().
glGenBuffers()
void GL_APIENTRY glGenBuffers (GLsizei n, GLuint * buffers)
Definition at line 568 of file OpenGLES.cpp.
 {
     auto func = GLESSymbols::get().glGenBuffers;
     if(func != nullptr)
     {
         return func(n, buffers);
     }
     else
     {
         return;
     }
 }
Referenced by GCBufferMemoryRegion::GCBufferMemoryRegion(), and GCKernel::GCKernel().
glGenFramebuffers()
void GL_APIENTRY glGenFramebuffers (GLsizei n, GLuint * framebuffers)
Definition at line 776 of file OpenGLES.cpp.
 {
     auto func = GLESSymbols::get().glGenFramebuffers;
     if(func != nullptr)
     {
         return func(n, framebuffers);
     }
     else
     {
         return;
     }
 }
Referenced by GCKernelLibrary::setup_dummy_fbo().
glGenTextures()
void GL_APIENTRY glGenTextures (GLsizei n, GLuint * textures)
Definition at line 724 of file OpenGLES.cpp.
 {
     auto func = GLESSymbols::get().glGenTextures;
     if(func != nullptr)
     {
         return func(n, textures);
     }
     else
     {
         return;
     }
 }
Referenced by GCKernelLibrary::setup_dummy_fbo().
glGetActiveUniformBlockiv()
void GL_APIENTRY glGetActiveUniformBlockiv (GLuint program, GLuint uniformBlockIndex, GLenum pname, GLint * params)
Definition at line 685 of file OpenGLES.cpp.
 {
     auto func = GLESSymbols::get().glGetActiveUniformBlockiv;
     if(func != nullptr)
     {
         return func(program, uniformBlockIndex, pname, params);
     }
     else
     {
         return;
     }
 }
Referenced by GCKernel::GCKernel().
glGetError()
GLenum GL_APIENTRY glGetError (void)
Definition at line 659 of file OpenGLES.cpp.
 {
     auto func = GLESSymbols::get().glGetError;
     if(func != nullptr)
     {
         return func();
     }
     else
     {
         return GL_NO_ERROR;
     }
 }
glGetProgramInfoLog()
void GL_APIENTRY glGetProgramInfoLog (GLuint program, GLsizei bufSize, GLsizei * length, GLchar * infoLog)
Definition at line 399 of file OpenGLES.cpp.
 {
     auto func = GLESSymbols::get().glGetProgramInfoLog;
     if(func != nullptr)
     {
         return func(program, bufSize, length, infoLog);
     }
     else
     {
         return;
     }
 }
Referenced by GCProgram::link_program().
glGetProgramiv()
void GL_APIENTRY glGetProgramiv (GLuint program, GLenum pname, GLint * params)
Definition at line 412 of file OpenGLES.cpp.
 {
     auto func = GLESSymbols::get().glGetProgramiv;
     if(func != nullptr)
     {
         return func(program, pname, params);
     }
     else
     {
         return;
     }
 }
Referenced by GCProgram::link_program().
glGetProgramResourceIndex()
GLuint GL_APIENTRY glGetProgramResourceIndex (GLuint program, GLenum programInterface, const GLchar * name)
Definition at line 581 of file OpenGLES.cpp.
 {
     auto func = GLESSymbols::get().glGetProgramResourceIndex;
     if(func != nullptr)
     {
         return func(program, programInterface, name);
     }
     else
     {
         return GL_INVALID_INDEX;
     }
 }
glGetShaderInfoLog()
void GL_APIENTRY glGetShaderInfoLog (GLuint shader, GLsizei bufSize, GLsizei * length, GLchar * infoLog)
Definition at line 425 of file OpenGLES.cpp.
 {
     auto func = GLESSymbols::get().glGetShaderInfoLog;
     if(func != nullptr)
     {
         return func(shader, bufSize, length, infoLog);
     }
     else
     {
         return;
     }
 }
Referenced by GCProgram::compile_shader().
glGetShaderiv()
void GL_APIENTRY glGetShaderiv (GLuint shader, GLenum pname, GLint * params)
Definition at line 438 of file OpenGLES.cpp.
 {
     auto func = GLESSymbols::get().glGetShaderiv;
     if(func != nullptr)
     {
         return func(shader, pname, params);
     }
     else
     {
         return;
     }
 }
Referenced by GCProgram::compile_shader().
glGetString()
const GLubyte* GL_APIENTRY glGetString (GLenum name)
Definition at line 672 of file OpenGLES.cpp.
 {
     auto func = GLESSymbols::get().glGetString;
     if(func != nullptr)
     {
         return func(name);
     }
     else
     {
         return nullptr;
     }
 }
Referenced by arm_compute::get_target_from_device().
glGetUniformBlockIndex()
GLuint GL_APIENTRY glGetUniformBlockIndex (GLuint program, const GLchar * uniformBlockName)
Definition at line 711 of file OpenGLES.cpp.
 {
     auto func = GLESSymbols::get().glGetUniformBlockIndex;
     if(func != nullptr)
     {
         return func(program, uniformBlockName);
     }
     else
     {
         return GL_INVALID_INDEX;
     }
 }
Referenced by GCKernel::GCKernel().
glGetUniformLocation()
GLint GL_APIENTRY glGetUniformLocation (GLuint program, const GLchar * name)
Definition at line 594 of file OpenGLES.cpp.
 {
     auto func = GLESSymbols::get().glGetUniformLocation;
     if(func != nullptr)
     {
         return func(program, name);
     }
     else
     {
         return -1;
     }
 }
glLinkProgram()
void GL_APIENTRY glLinkProgram (GLuint program)
Definition at line 451 of file OpenGLES.cpp.
 {
     auto func = GLESSymbols::get().glLinkProgram;
     if(func != nullptr)
     {
         return func(program);
     }
     else
     {
         return;
     }
 }
Referenced by GCProgram::link_program().
glMapBufferRange()
void* GL_APIENTRY glMapBufferRange (GLenum target, GLintptr offset, GLsizeiptr length, GLbitfield access)
Definition at line 607 of file OpenGLES.cpp.
 {
     auto func = GLESSymbols::get().glMapBufferRange;
     if(func != nullptr)
     {
         return func(target, offset, length, access);
     }
     else
     {
         return nullptr;
     }
 }
References offset().
Referenced by GCBufferMemoryRegion::map().
glMemoryBarrier()
void GL_APIENTRY glMemoryBarrier (GLbitfield barriers)
Definition at line 620 of file OpenGLES.cpp.
 {
     auto func = GLESSymbols::get().glMemoryBarrier;
     if(func != nullptr)
     {
         return func(barriers);
     }
     else
     {
         return;
     }
 }
Referenced by GCScheduler::memory_barrier().
glShaderSource()
void GL_APIENTRY glShaderSource (GLuint shader, GLsizei count, const GLchar *const * string, const GLint * length)
Definition at line 464 of file OpenGLES.cpp.
 {
     auto func = GLESSymbols::get().glShaderSource;
     if(func != nullptr)
     {
         return func(shader, count, string, length);
     }
     else
     {
         return;
     }
 }
Referenced by GCProgram::compile_shader().
glTexImage2D()
void GL_APIENTRY glTexImage2D (GLenum target, GLint level, GLint internalformat, GLsizei width, GLsizei height, GLint border, GLenum format, GLenum type, const GLvoid * pixels)
Definition at line 763 of file OpenGLES.cpp.
 {
     auto func = GLESSymbols::get().glTexImage2D;
     if(func != nullptr)
     {
         return func(target, level, internalformat, width, height, border, format, type, pixels);
     }
     else
     {
         return;
     }
 }
Referenced by GCKernelLibrary::setup_dummy_fbo().
glUniform1ui()
void GL_APIENTRY glUniform1ui (GLint location, GLuint v0)
Definition at line 633 of file OpenGLES.cpp.
 {
     auto func = GLESSymbols::get().glUniform1ui;
     if(func != nullptr)
     {
         return func(location, v0);
     }
     else
     {
         return;
     }
 }
glUniformBlockBinding()
void GL_APIENTRY glUniformBlockBinding (GLuint program, GLuint uniformBlockIndex, GLuint uniformBlockBinding)
Definition at line 698 of file OpenGLES.cpp.
 {
     auto func = GLESSymbols::get().glUniformBlockBinding;
     if(func != nullptr)
     {
         return func(program, uniformBlockIndex, uniformBlockBinding);
     }
     else
     {
         return;
     }
 }
Referenced by GCKernel::update_shader_params().
glUnmapBuffer()
GLboolean GL_APIENTRY glUnmapBuffer (GLenum target)
Definition at line 646 of file OpenGLES.cpp.
 {
     auto func = GLESSymbols::get().glUnmapBuffer;
     if(func != nullptr)
     {
         return func(target);
     }
     else
     {
         return GL_FALSE;
     }
 }
Referenced by GCBufferMemoryRegion::unmap().
glUseProgram()
void GL_APIENTRY glUseProgram (GLuint program)
Definition at line 477 of file OpenGLES.cpp.
 {
     auto func = GLESSymbols::get().glUseProgram;
     if(func != nullptr)
     {
         return func(program);
     }
     else
     {
         return;
     }
 }
Referenced by GCKernel::cleanup(), GCProgram::link_program(), GCKernel::unuse(), and GCKernel::use().