Compute Library: CPPNonMaximumSuppression Class Reference
CPPNonMaximumSuppression Class Reference
CPP Function to perform non maximum suppression on the bounding boxes and scores.
#include <CPPDetectionOutputLayer.h>
Public Member Functions
CPPNonMaximumSuppression ()
Default constructor.
void configure (const ITensor *bboxes, const ITensor *scores, ITensor *indices, unsigned int max_output_size, const float score_threshold, const float nms_threshold)
Configure the function to perform non maximal suppression.
void run () override
Run the kernels contained in the function.
CPPNonMaximumSuppression (const CPPNonMaximumSuppression &)=delete
Prevent instances of this class from being copied (As this class contains pointers)
CPPNonMaximumSuppression & operator= (const CPPNonMaximumSuppression &)=delete
Prevent instances of this class from being copied (As this class contains pointers)
Public Member Functions inherited from IFunction
virtual ~IFunction ()=default
Destructor.
virtual void prepare ()
Prepare the function for executing.
Static Public Member Functions
static Status validate (const ITensorInfo *bboxes, const ITensorInfo *scores, const ITensorInfo *indices, unsigned int max_output_size, const float score_threshold, const float nms_threshold)
Static function to check if given arguments will lead to a valid configuration of CPPNonMaximumSuppression.
Detailed Description
CPP Function to perform non maximum suppression on the bounding boxes and scores.
Definition at line 45 of file CPPDetectionOutputLayer.h.
Constructor & Destructor Documentation
CPPNonMaximumSuppression() [1/2]
CPPNonMaximumSuppression ()
Default constructor.
Definition at line 405 of file CPPDetectionOutputLayer.cpp.
     : _bboxes(nullptr), _scores(nullptr), _indices(nullptr), _max_output_size(0), _score_threshold(0.f), _nms_threshold(0.f)
 {
 }
CPPNonMaximumSuppression() [2/2]
CPPNonMaximumSuppression (const CPPNonMaximumSuppression &) delete
Prevent instances of this class from being copied (As this class contains pointers)
Member Function Documentation
configure()
void configure (const ITensor * bboxes, const ITensor * scores, ITensor * indices, unsigned int max_output_size, const float score_threshold, const float nms_threshold)
Configure the function to perform non maximal suppression.
Parameters
[in] bboxes The input bounding boxes. Data types supported: F32.
[in] scores The corresponding input confidence. Same as scores.
[out] indices The kept indices of bboxes after nms. Data types supported: S32.
[in] max_output_size An integer tensor representing the maximum number of boxes to be selected by non max suppression.
[in] score_threshold The threshold used to filter detection results.
[in] nms_threshold The threshold used in non maximum suppression.
Definition at line 410 of file CPPDetectionOutputLayer.cpp.
 {
     ARM_COMPUTE_ERROR_ON_NULLPTR(bboxes, scores, indices);
     ARM_COMPUTE_ERROR_THROW_ON(non_max_suppression_validate_arguments(bboxes->info(), scores->info(), indices->info(), max_output_size, score_threshold, nms_threshold));
     // copy scores also to a vector
     _bboxes  = bboxes;
     _scores  = scores;
     _indices = indices;
     _nms_threshold   = nms_threshold;
     _max_output_size = max_output_size;
     _score_threshold = score_threshold;
 }
References ARM_COMPUTE_ERROR_ON_NULLPTR, ARM_COMPUTE_ERROR_THROW_ON, and ITensor::info().
operator=()
CPPNonMaximumSuppression& operator= (const CPPNonMaximumSuppression &) delete
Prevent instances of this class from being copied (As this class contains pointers)
run()
void run () override virtual
Run the kernels contained in the function.
For NEON kernels:
Multi-threading is used for the kernels which are parallelisable.
By default std::thread::hardware_concurrency() threads are used.
Note
CPPScheduler::set_num_threads() can be used to manually set the number of threads
For OpenCL kernels:
All the kernels are enqueued on the queue associated with CLScheduler.
The queue is then flushed.
Note
The function will not block until the kernels are executed. It is the user's responsibility to wait.
Will call prepare() on first run if hasn't been done
Implements IFunction.
Definition at line 463 of file CPPDetectionOutputLayer.cpp.
 {
     std::vector<NormalizedBBox> bboxes_vector;
     std::vector<float>          scores_vector;
     std::vector<int>            indices_vector;
     extract_bounding_boxes_from_tensor(_bboxes, bboxes_vector);
     extract_scores_from_tensor(_scores, scores_vector);
     ApplyNMSFast(bboxes_vector, scores_vector, _score_threshold, _nms_threshold, 1, -1 /* disable top_k */, indices_vector);
     std::copy_n(indices_vector.begin(), std::min(indices_vector.size(), _indices->info()->dimension(0)), reinterpret_cast<int *>(_indices->ptr_to_element(Coordinates(0))));
 }
References ITensorInfo::dimension(), arm_compute::extract_bounding_boxes_from_tensor(), arm_compute::extract_scores_from_tensor(), ITensor::info(), and ITensor::ptr_to_element().
validate()
Status validate (const ITensorInfo * bboxes, const ITensorInfo * scores, const ITensorInfo * indices, unsigned int max_output_size, const float score_threshold, const float nms_threshold) static
Static function to check if given arguments will lead to a valid configuration of CPPNonMaximumSuppression.
Parameters
[in] bboxes The input bounding boxes. Data types supported: F32.
[in] scores The corresponding input confidence. Same as scores.
[out] indices The kept indices of bboxes after nms. Data types supported: S32.
[in] max_output_size An integer tensor representing the maximum number of boxes to be selected by non max suppression.
[in] score_threshold The threshold used to filter detection results.
[in] nms_threshold The threshold used in non maximum suppression.
Definition at line 427 of file CPPDetectionOutputLayer.cpp.
 {
     ARM_COMPUTE_RETURN_ON_ERROR(non_max_suppression_validate_arguments(bboxes, scores, indices, max_output_size, score_threshold, nms_threshold));
     return Status{};
 }
References ARM_COMPUTE_RETURN_ON_ERROR.
The documentation for this class was generated from the following files:
arm_compute/runtime/CPP/functions/CPPDetectionOutputLayer.h
src/runtime/CPP/functions/CPPDetectionOutputLayer.cpp