Compute Library: CLGEMM Class Reference
CLGEMM Class Reference
Basic function to execute GEMM on OpenCL.
#include <CLGEMM.h>
Public Member Functions
CLGEMM (std::shared_ptr< IMemoryManager > memory_manager=nullptr)
Default constructor.
CLGEMM (const CLGEMM &)=delete
Prevent instances of this class from being copied (As this class contains pointers)
CLGEMM (CLGEMM &&)=default
Default move constructor.
CLGEMM & operator= (const CLGEMM &)=delete
Prevent instances of this class from being copied (As this class contains pointers)
CLGEMM & operator= (CLGEMM &&)=default
Default move assignment operator.
void configure (const ICLTensor *a, const ICLTensor *b, const ICLTensor *c, ICLTensor *output, float alpha, float beta, const GEMMInfo &gemm_info=GEMMInfo())
Initialise the kernel's inputs and output.
void run () override
Run the kernels contained in the function.
void prepare () override
Prepare the function for executing.
Public Member Functions inherited from IFunction
virtual ~IFunction ()=default
Destructor.
Static Public Member Functions
static Status validate (const ITensorInfo *a, const ITensorInfo *b, const ITensorInfo *c, const ITensorInfo *output, float alpha, float beta, const GEMMInfo &gemm_info=GEMMInfo())
Static function to check if given info will lead to a valid configuration of CLGEMM.
Detailed Description
Basic function to execute GEMM on OpenCL.
This function calls the following OpenCL kernels:
CLGEMMReshapeLHSMatrixKernel (only if the reshaped GEMM is selected by the heuristic model)
CLGEMMReshapeRHSMatrixKernel (only if the reshaped GEMM is selected by the heuristic model)
CLGEMMMatrixMultiplyKernel (if GPU target is NOT G76 or if the reshaped GEMM is NOT selected)
CLGEMMMatrixMultiplyReshapedKernel (only if the reshaped GEMM is selected by the heuristic model and the GPU target IS Mali-G76)
CLGEMMMatrixAdditionKernel (if c != nullptr and beta != 0.0)
Definition at line 50 of file CLGEMM.h.
Constructor & Destructor Documentation
CLGEMM() [1/3]
CLGEMM (std::shared_ptr< IMemoryManager > memory_manager = nullptr)
Default constructor.
Parameters
[in] memory_manager (Optional) Memory manager.
Definition at line 84 of file CLGEMM.cpp.
     : _memory_group(std::move(memory_manager)),
       _mm_kernel(),
       _ma_kernel(),
       _reshape_lhs_kernel(),
       _reshape_rhs_kernel(),
       _mm_reshaped_kernel(),
       _tmp_a(),
       _tmp_b(),
       _original_b(nullptr),
       _is_interleaved_transposed(false),
       _run_addition(false),
       _reshape_b_only_on_first_run(false),
       _is_prepared(false),
       _is_new_gemm_reshaped(false)
 {
 }
CLGEMM() [2/3]
CLGEMM (const CLGEMM &) delete
Prevent instances of this class from being copied (As this class contains pointers)
CLGEMM() [3/3]
CLGEMM (CLGEMM &&) default
Default move constructor.
Member Function Documentation
configure()
void configure (const ICLTensor * a, const ICLTensor * b, const ICLTensor * c, ICLTensor * output, float alpha, float beta, const GEMMInfo & gemm_info = GEMMInfo())
Initialise the kernel's inputs and output.
Note
GEMM: General Matrix Multiply - [alpha * A * B + beta * C].
All tensors must have the same data type.
Whilst the first input tensor can be a vector, the second input tensor must be at least a matrix
Parameters
[in] a First input tensor (Matrix or Vector A). Data types supported: F16/F32
[in] b Second input tensor (Matrix B). Data type supported: same as a.
[in] c Third input tensor (Matrix C). It can be a nullptr if just the multiplication between a and b is needed. Data type supported: same as a.
[out] output Output tensor. Data type supported: same as a
[in] alpha Weight of the matrix product
[in] beta Weight of matrix C
[in] gemm_info (Optional) Specifies if the matrix A and/or matrix B have been reshaped and if the reshape of matrix B should happen only for the first run. GEMMInfo also contains information about the reshaping in case matrix A and matrix B have been already transformed.
Definition at line 102 of file CLGEMM.cpp.
 {
     ARM_COMPUTE_ERROR_ON_NULLPTR(a, b, output);
     // Perform validation step
     ARM_COMPUTE_ERROR_THROW_ON(validate(a->info(), b->info(), c != nullptr ? c->info() : nullptr, output->info(), alpha, beta, gemm_info));
     // Check if we need to reshape the matrix B only on the first run
     _reshape_b_only_on_first_run = gemm_info.reshape_b_only_on_first_run();
     _is_prepared                 = gemm_info.retain_internal_weights();
     _original_b                  = b;
     const ICLTensor *matrix_a = a;
     const ICLTensor *matrix_b = b;
     // Get the GPU target
     const GPUTarget gpu_target = CLScheduler::get().target();
     // Set the target for the kernels
     _reshape_lhs_kernel.set_target(gpu_target);
     _mm_kernel.set_target(gpu_target);
     // Arguments used by GEMMReshapeInfo
     // If we pass the matrix A and matrix B reshaped to CLGEMMMatrixMultiplyKernel, we need to pass m, n, k, mult_transpose1xW_width and mult_interleave4x4_height to CLGEMMReshapeInfo
     // in order to know how the matrices have been reshaped
     DataType           data_type                 = a->info()->data_type();
     bool               reinterpret_input_as_3d   = gemm_info.reinterpret_input_as_3d();
     const unsigned int m                         = reinterpret_input_as_3d ? (a->info()->dimension(1) * a->info()->dimension(2)) : a->info()->dimension(1);
     const unsigned int n                         = b->info()->dimension(0);
     const unsigned int k                         = a->info()->dimension(0);
     const unsigned int batch_size                = reinterpret_input_as_3d ? a->info()->dimension(3) : a->info()->dimension(2);
     const int          depth_output_gemm3d       = gemm_info.depth_output_gemm3d();
     int                mult_transpose1xW_width   = 1;
     int                mult_interleave4x4_height = 1;
     if(get_arch_from_target(gpu_target) == GPUTarget::BIFROST)
     {
         mult_transpose1xW_width   = 4;
         mult_interleave4x4_height = 2;
     }
     GEMMRHSMatrixInfo rhs_info;
     rhs_info.n0         = 16 / b->info()->element_size();
     rhs_info.k0         = 1;
     rhs_info.h0         = mult_transpose1xW_width;
     rhs_info.interleave = false;
     rhs_info.transpose  = false;
     GEMMLHSMatrixInfo lhs_info;
     lhs_info.m0         = 4;
     lhs_info.k0         = 4;
     lhs_info.v0         = mult_interleave4x4_height;
     lhs_info.interleave = true;
     lhs_info.transpose  = true;
     // Check if we need to reshape the matrix A and matrix B
     _is_interleaved_transposed = is_interleaved_transposed(m, n, k, a->info()->data_type(), _reshape_b_only_on_first_run, gpu_target);
     // Check if we can run the new reshaped GEMM
     const auto workload   = static_cast<float>((m * n) / 20.0f);
     _is_new_gemm_reshaped = (workload > 1600.0f) && (get_arch_from_target(gpu_target) == GPUTarget::BIFROST) && _is_interleaved_transposed && (data_type == DataType::F32);
     const bool add_matrix_c  = (beta != 0.f && c != nullptr);
     const bool is_beta_one   = std::abs(1.0f - beta) < 0.00001f;
     const bool use_fused_add = is_beta_one && (c != nullptr && c->info()->num_dimensions() == 1) && !_is_new_gemm_reshaped;
     // if _is_interleaved_transposed is set, force reinterpret_input_as_3d to be false as the output of CLGEMMInterleaveKernel will be 2D
     if(_is_interleaved_transposed)
     {
         reinterpret_input_as_3d = false;
         matrix_a = &_tmp_a;
         matrix_b = &_tmp_b;
         // Manage intermediate buffers
         _memory_group.manage(&_tmp_a);
         if(!_reshape_b_only_on_first_run)
         {
             _memory_group.manage(&_tmp_b);
         }
         // _tmp_a and _tmp_b will be auto configured in _interleave_kernel and in _transpose_kernel
         if(_is_new_gemm_reshaped)
         {
             GEMMLHSMatrixInfo lhs_info;
             // Pick up the GEMM configuration
             std::tie(lhs_info, rhs_info) = CLGEMMReshapedConfigurationFactory::create()->configure(m, n, k, batch_size, data_type);
             _reshape_lhs_kernel.configure(a, &_tmp_a, lhs_info, gemm_info.reinterpret_input_as_3d());
             _reshape_rhs_kernel.configure(b, &_tmp_b, rhs_info);
             // Configure and tune matrix multiply kernel
             _mm_reshaped_kernel.configure(matrix_a, matrix_b, output, alpha, lhs_info, rhs_info, GEMMReshapeInfo(m, n, k, 1, 1,
                                                                                                                  depth_output_gemm3d, reinterpret_input_as_3d));
         }
         else
         {
             // Configure interleave kernel
             _reshape_lhs_kernel.configure(a, &_tmp_a, lhs_info, gemm_info.reinterpret_input_as_3d());
             // Configure transpose kernel
             _reshape_rhs_kernel.configure(b, &_tmp_b, rhs_info);
         }
     }
     if(!_is_new_gemm_reshaped)
     {
         // Configure and tune matrix multiply kernel
         _mm_kernel.configure(matrix_a, matrix_b, (add_matrix_c && !use_fused_add) ? nullptr : c, output, alpha, beta, _is_interleaved_transposed,
                              GEMMReshapeInfo(m, n, k, mult_transpose1xW_width, mult_interleave4x4_height, depth_output_gemm3d, reinterpret_input_as_3d),
                              gemm_info.fp_mixed_precision());
         CLScheduler::get().tune_kernel_static(_mm_kernel);
     }
     if(_is_interleaved_transposed)
     {
         // Allocate intermediate tensors
         _tmp_a.allocator()->allocate();
         if(!_reshape_b_only_on_first_run)
         {
             _tmp_b.allocator()->allocate();
         }
     }
     // Configure matrix addition kernel
     if(add_matrix_c && !use_fused_add)
     {
         _ma_kernel.configure(c, output, beta);
         _run_addition = true;
     }
 }
References CLTensorAllocator::allocate(), CLTensor::allocator(), arm_compute::test::validation::alpha, ARM_COMPUTE_ERROR_ON_NULLPTR, ARM_COMPUTE_ERROR_THROW_ON, arm_compute::BIFROST, CLGEMMMatrixAdditionKernel::configure(), CLGEMMMatrixMultiplyReshapedKernel::configure(), CLGEMMReshapeRHSMatrixKernel::configure(), CLGEMMReshapeLHSMatrixKernel::configure(), CLGEMMMatrixMultiplyKernel::configure(), CLGEMMReshapedConfigurationFactory::create(), arm_compute::test::validation::data_type, ITensorInfo::data_type(), GEMMInfo::depth_output_gemm3d(), ITensorInfo::dimension(), ITensorInfo::element_size(), arm_compute::F32, GEMMInfo::fp_mixed_precision(), CLScheduler::get(), arm_compute::get_arch_from_target(), GEMMRHSMatrixInfo::h0, ITensor::info(), GEMMLHSMatrixInfo::interleave, GEMMRHSMatrixInfo::interleave, GEMMLHSMatrixInfo::k0, GEMMRHSMatrixInfo::k0, GEMMLHSMatrixInfo::m0, MemoryGroupBase< TensorType >::manage(), GEMMRHSMatrixInfo::n0, ITensorInfo::num_dimensions(), GEMMInfo::reinterpret_input_as_3d(), GEMMInfo::reshape_b_only_on_first_run(), GEMMInfo::retain_internal_weights(), ICLKernel::set_target(), CLScheduler::target(), GEMMLHSMatrixInfo::transpose, GEMMRHSMatrixInfo::transpose, CLScheduler::tune_kernel_static(), GEMMLHSMatrixInfo::v0, and CLGEMM::validate().
Referenced by CLRNNLayer::configure(), CLWinogradConvolutionLayer::configure(), and CLLSTMLayer::configure().
operator=() [1/2]
CLGEMM& operator= (const CLGEMM &) delete
Prevent instances of this class from being copied (As this class contains pointers)
operator=() [2/2]
CLGEMM& operator= (CLGEMM &&) default
Default move assignment operator.
prepare()
void prepare () override virtual
Prepare the function for executing.
Any one off pre-processing step required by the function is handled here
Note
Prepare stage might not need all the function's buffers' backing memory to be available in order to execute
Reimplemented from IFunction.
Definition at line 388 of file CLGEMM.cpp.
 {
     if(!_is_prepared)
     {
         if(_is_interleaved_transposed && _reshape_b_only_on_first_run)
         {
             // Run transpose kernel and mark original weights tensor as unused
             _tmp_b.allocator()->allocate();
             CLScheduler::get().enqueue(_reshape_rhs_kernel, false);
             _original_b->mark_as_unused();
         }
         CLScheduler::get().queue().finish();
         _is_prepared = true;
     }
 }
References CLTensorAllocator::allocate(), CLTensor::allocator(), CLScheduler::enqueue(), CLScheduler::get(), ITensor::mark_as_unused(), and CLScheduler::queue().
Referenced by CLRNNLayer::prepare(), CLWinogradConvolutionLayer::prepare(), CLFullyConnectedLayer::prepare(), CLGEMMConvolutionLayer::prepare(), and CLGEMM::run().
run()
void run () override virtual
Run the kernels contained in the function.
For NEON kernels:
Multi-threading is used for the kernels which are parallelisable.
By default std::thread::hardware_concurrency() threads are used.
Note
CPPScheduler::set_num_threads() can be used to manually set the number of threads
For OpenCL kernels:
All the kernels are enqueued on the queue associated with CLScheduler.
The queue is then flushed.
Note
The function will not block until the kernels are executed. It is the user's responsibility to wait.
Will call prepare() on first run if hasn't been done
Implements IFunction.
Definition at line 351 of file CLGEMM.cpp.
 {
     prepare();
     _memory_group.acquire();
     if(_is_interleaved_transposed)
     {
         // Run interleave kernel
         CLScheduler::get().enqueue(_reshape_lhs_kernel, false);
         if(!_reshape_b_only_on_first_run)
         {
             // Run transpose kernel
             CLScheduler::get().enqueue(_reshape_rhs_kernel, false);
         }
     }
     // Run matrix multiply kernel
     if(_is_new_gemm_reshaped)
     {
         CLScheduler::get().enqueue(_mm_reshaped_kernel, !_run_addition);
     }
     else
     {
         CLScheduler::get().enqueue(_mm_kernel, !_run_addition);
     }
     // Run matrix addition kernel
     if(_run_addition)
     {
         CLScheduler::get().enqueue(_ma_kernel);
     }
     _memory_group.release();
 }
References MemoryGroupBase< TensorType >::acquire(), CLScheduler::enqueue(), CLScheduler::get(), CLGEMM::prepare(), and MemoryGroupBase< TensorType >::release().
Referenced by CLRNNLayer::run(), CLWinogradConvolutionLayer::run(), CLFullyConnectedLayer::run(), CLLSTMLayer::run(), and CLGEMMConvolutionLayer::run().
validate()
Status validate (const ITensorInfo * a, const ITensorInfo * b, const ITensorInfo * c, const ITensorInfo * output, float alpha, float beta, const GEMMInfo & gemm_info = GEMMInfo()) static
Static function to check if given info will lead to a valid configuration of CLGEMM.
Parameters
[in] a First input tensor info (Matrix or Vector A). Data types supported: F16/F32
[in] b Second input tensor info (Matrix B). Data type supported: same as a.
[in] c Third input tensor info (Matrix C). It can be a nullptr if just the multiplication between a and b is needed. Data type supported: same as a.
[in] output Output tensor info. Data type supported: same as a
[in] alpha Weight of the matrix product
[in] beta Weight of matrix C
[in] gemm_info (Optional) Specifies if the matrix A and/or matrix B have been reshaped and if the reshape of matrix B should happen only for the first run
Returns
a status
Definition at line 233 of file CLGEMM.cpp.
 {
     ARM_COMPUTE_UNUSED(alpha);
     ARM_COMPUTE_UNUSED(output);
     // Check if we need to reshape the matrix B only on the first run
     const bool reshape_b_only_on_first_run = gemm_info.reshape_b_only_on_first_run();
     const ITensorInfo *matrix_a_info = a;
     const ITensorInfo *matrix_b_info = b;
     TensorInfo tmp_a_info{};
     TensorInfo tmp_b_info{};
     // Get the GPU target
     const GPUTarget gpu_target = CLScheduler::get().target();
     // Arguments used by GEMMReshapeInfo
     // If we pass the matrix A and matrix B reshaped to CLGEMMMatrixMultiplyKernel, we need to pass m, n, k, mult_transpose1xW_width and mult_interleave4x4_height to CLGEMMReshapeInfo
     // in order to know how the matrices have been reshaped
     DataType           data_type                 = a->data_type();
     bool               reinterpret_input_as_3d   = gemm_info.reinterpret_input_as_3d();
     const unsigned int m                         = reinterpret_input_as_3d ? (a->dimension(1) * a->dimension(2)) : a->dimension(1);
     const unsigned int n                         = b->dimension(0);
     const unsigned int k                         = a->dimension(0);
     const unsigned int batch_size                = reinterpret_input_as_3d ? a->dimension(3) : a->dimension(2);
     int                mult_transpose1xW_width   = 1;
     int                mult_interleave4x4_height = 1;
     const int          depth_output_gemm3d       = gemm_info.depth_output_gemm3d();
     if(get_arch_from_target(gpu_target) == GPUTarget::BIFROST)
     {
         mult_transpose1xW_width   = 4;
         mult_interleave4x4_height = 2;
     }
     GEMMRHSMatrixInfo rhs_info;
     rhs_info.n0         = 16 / b->element_size();
     rhs_info.k0         = 1;
     rhs_info.h0         = mult_transpose1xW_width;
     rhs_info.interleave = false;
     rhs_info.transpose  = false;
     GEMMLHSMatrixInfo lhs_info;
     lhs_info.m0         = 4;
     lhs_info.k0         = 4;
     lhs_info.v0         = mult_interleave4x4_height;
     lhs_info.interleave = true;
     lhs_info.transpose  = true;
     // Check if we need to reshape the matrix A and matrix B
     const bool run_interleave_transpose = is_interleaved_transposed(m, n, k, a->data_type(), reshape_b_only_on_first_run, gpu_target);
     // Check if we can run the new reshaped GEMM
     const auto workload             = static_cast<float>((m * n) / 20.0f);
     const bool is_new_gemm_reshaped = (workload > 1600.f) && (get_arch_from_target(gpu_target) == GPUTarget::BIFROST) && run_interleave_transpose && (data_type == DataType::F32);
     const bool add_matrix_c  = (beta != 0.f && c != nullptr);
     const bool is_beta_one   = std::abs(1.0f - beta) < 0.00001f;
     const bool use_fused_add = is_beta_one && (c != nullptr && c->num_dimensions() == 1) && !is_new_gemm_reshaped;
     // if _is_interleaved_transposed is set, force reinterpret_input_as_3d to be false as the output of CLGEMMInterleaveKernel will be 2D
     if(run_interleave_transpose)
     {
         reinterpret_input_as_3d = false;
     }
     const GEMMReshapeInfo reshape_info = GEMMReshapeInfo(m, n, k, mult_transpose1xW_width, mult_interleave4x4_height, depth_output_gemm3d, reinterpret_input_as_3d);
     if(run_interleave_transpose)
     {
         matrix_a_info = &tmp_a_info;
         matrix_b_info = &tmp_b_info;
         if(is_new_gemm_reshaped)
         {
             GEMMLHSMatrixInfo lhs_info;
             // Pick up the GEMM configuration
             std::tie(lhs_info, rhs_info) = CLGEMMReshapedConfigurationFactory::create()->configure(m, n, k, batch_size, data_type);
             auto_init_if_empty(tmp_a_info, a->clone()->set_tensor_shape(compute_lhs_reshaped_shape(*a, lhs_info, gemm_info.reinterpret_input_as_3d())));
             ARM_COMPUTE_RETURN_ON_ERROR(CLGEMMReshapeLHSMatrixKernel::validate(a, &tmp_a_info, lhs_info, gemm_info.reinterpret_input_as_3d()));
             auto_init_if_empty(tmp_b_info, b->clone()->set_tensor_shape(compute_rhs_reshaped_shape(*b, rhs_info)));
             ARM_COMPUTE_RETURN_ON_ERROR(CLGEMMReshapeRHSMatrixKernel::validate(b, &tmp_b_info, rhs_info));
             // Validate matrix multiply
             ARM_COMPUTE_RETURN_ON_ERROR(CLGEMMMatrixMultiplyReshapedKernel::validate(matrix_a_info, matrix_b_info, output, alpha, lhs_info, rhs_info, GEMMReshapeInfo(m, n, k, 1, 1,
                                                                                      depth_output_gemm3d, reinterpret_input_as_3d)));
         }
         else
         {
             // Validate interleave kernel
             auto_init_if_empty(tmp_a_info, a->clone()->set_tensor_shape(compute_lhs_reshaped_shape(*a, lhs_info, gemm_info.reinterpret_input_as_3d())));
             ARM_COMPUTE_RETURN_ON_ERROR(CLGEMMReshapeLHSMatrixKernel::validate(a, &tmp_a_info, lhs_info, gemm_info.reinterpret_input_as_3d()));
             // Validate transpose kernel
             auto_init_if_empty(tmp_b_info, b->clone()->set_tensor_shape(compute_rhs_reshaped_shape(*b, rhs_info)));
             ARM_COMPUTE_RETURN_ON_ERROR(CLGEMMReshapeRHSMatrixKernel::validate(b, &tmp_b_info, rhs_info));
         }
     }
     if(!is_new_gemm_reshaped)
     {
         // Validate matrix multiply
         ARM_COMPUTE_RETURN_ON_ERROR(CLGEMMMatrixMultiplyKernel::validate(matrix_a_info, matrix_b_info, (add_matrix_c && !use_fused_add) ? nullptr : c, output, alpha, beta,
                                                                          run_interleave_transpose, reshape_info, gpu_target, gemm_info.fp_mixed_precision()));
     }
     if(add_matrix_c && !use_fused_add)
     {
         // Validate matrix addition kernel
         ARM_COMPUTE_RETURN_ON_ERROR(CLGEMMMatrixAdditionKernel::validate(c, output, beta));
     }
     return Status{};
 }
References arm_compute::test::validation::alpha, ARM_COMPUTE_RETURN_ON_ERROR, ARM_COMPUTE_UNUSED, arm_compute::auto_init_if_empty(), arm_compute::BIFROST, ICloneable< T >::clone(), arm_compute::misc::shape_calculator::compute_lhs_reshaped_shape(), arm_compute::misc::shape_calculator::compute_rhs_reshaped_shape(), CLGEMMReshapedConfigurationFactory::create(), arm_compute::test::validation::data_type, ITensorInfo::data_type(), GEMMInfo::depth_output_gemm3d(), ITensorInfo::dimension(), ITensorInfo::element_size(), arm_compute::F32, GEMMInfo::fp_mixed_precision(), CLScheduler::get(), arm_compute::get_arch_from_target(), GEMMRHSMatrixInfo::h0, GEMMLHSMatrixInfo::interleave, GEMMRHSMatrixInfo::interleave, GEMMLHSMatrixInfo::k0, GEMMRHSMatrixInfo::k0, GEMMLHSMatrixInfo::m0, GEMMRHSMatrixInfo::n0, ITensorInfo::num_dimensions(), GEMMInfo::reinterpret_input_as_3d(), GEMMInfo::reshape_b_only_on_first_run(), CLScheduler::target(), GEMMLHSMatrixInfo::transpose, GEMMRHSMatrixInfo::transpose, GEMMLHSMatrixInfo::v0, CLGEMMMatrixAdditionKernel::validate(), CLGEMMMatrixMultiplyReshapedKernel::validate(), CLGEMMReshapeRHSMatrixKernel::validate(), CLGEMMReshapeLHSMatrixKernel::validate(), and CLGEMMMatrixMultiplyKernel::validate().
Referenced by CLGEMM::configure(), CLRNNLayer::validate(), CLWinogradConvolutionLayer::validate(), and CLLSTMLayer::validate().
The documentation for this class was generated from the following files:
arm_compute/runtime/CL/functions/CLGEMM.h
src/runtime/CL/functions/CLGEMM.cpp