Compute Library: DotGraphVisitor Class Reference
DotGraphVisitor Class Reference final
Graph printer visitor.
#include <DotGraphPrinter.h>
Public Member Functions
DotGraphVisitor ()=default
Default Constructor.
const std::string & info () const
Returns the output information of the last visited node.
void visit (ActivationLayerNode &n) override
Visit ActivationLayerNode.
void visit (BatchNormalizationLayerNode &n) override
Visit BatchNormalizationLayerNode.
void visit (ConcatenateLayerNode &n) override
Visit ConcatenateLayerNode.
void visit (ConvolutionLayerNode &n) override
Visit ConvolutionLayerNode.
void visit (DepthwiseConvolutionLayerNode &n) override
Visit DepthwiseConvolutionLayerNode.
void visit (EltwiseLayerNode &n) override
Visit EltwiseLayerNode.
void visit (NormalizationLayerNode &n) override
Visit NormalizationLayerNode.
void visit (PoolingLayerNode &n) override
Visit PoolingLayerNode.
void default_visit () override
Function to be overloaded by the client and implement default behavior for the non-overloaded visitors.
Public Member Functions inherited from DefaultNodeVisitor
virtual ~DefaultNodeVisitor ()=default
Default destructor.
Public Member Functions inherited from INodeVisitor
virtual ~INodeVisitor ()=default
Default destructor.
virtual void visit (INode &n)=0
Visit INode.
virtual void visit (ConstNode &n)=0
Visit ConstNode.
virtual void visit (DetectionOutputLayerNode &n)=0
Visit DetectionOutputLayerNode.
virtual void visit (FlattenLayerNode &n)=0
Visit FlattenLayerNode.
virtual void visit (FullyConnectedLayerNode &n)=0
Visit FullyConnectedLayerNode.
virtual void visit (InputNode &n)=0
Visit InputNode.
virtual void visit (OutputNode &n)=0
Visit OutputNode.
virtual void visit (PermuteLayerNode &n)=0
Visit PermuteLayerNode.
virtual void visit (PriorBoxLayerNode &n)=0
Visit PriorBoxLayerNode.
virtual void visit (ReshapeLayerNode &n)=0
Visit ReshapeLayerNode.
virtual void visit (SoftmaxLayerNode &n)=0
Visit SoftmaxLayerNode.
virtual void visit (SplitLayerNode &n)=0
Visit SplitLayerNode.
Detailed Description
Graph printer visitor.
Definition at line 38 of file DotGraphPrinter.h.
Constructor & Destructor Documentation
DotGraphVisitor()
DotGraphVisitor () default
Default Constructor.
Member Function Documentation
default_visit()
void default_visit () override virtual
Function to be overloaded by the client and implement default behavior for the non-overloaded visitors.
Implements DefaultNodeVisitor.
Definition at line 98 of file DotGraphPrinter.cpp.
 {
     _info.clear();
 }
info()
const std::string & info () const
Returns the output information of the last visited node.
Returns
Information of the last visited node
Definition at line 103 of file DotGraphPrinter.cpp.
 {
     return _info;
 }
visit() [1/8]
void visit (ActivationLayerNode & n) override virtual
Visit ActivationLayerNode.
Parameters
[in] n Node to visit.
Implements INodeVisitor.
Definition at line 36 of file DotGraphPrinter.cpp.
 {
     std::stringstream ss;
     ss << n.activation_info().activation();
     _info = ss.str();
 }
References ActivationLayerInfo::activation(), and ActivationLayerNode::activation_info().
visit() [2/8]
void visit (BatchNormalizationLayerNode & n) override virtual
Visit BatchNormalizationLayerNode.
Parameters
[in] n Node to visit.
Implements INodeVisitor.
Definition at line 43 of file DotGraphPrinter.cpp.
 {
     std::stringstream ss;
     ss << (n.fused_activation().enabled() ? to_string(n.fused_activation().activation()) : "");
     _info = ss.str();
 }
References ActivationLayerInfo::activation(), ActivationLayerInfo::enabled(), BatchNormalizationLayerNode::fused_activation(), and arm_compute::to_string().
visit() [3/8]
void visit (ConcatenateLayerNode & n) override virtual
Visit ConcatenateLayerNode.
Parameters
[in] n Node to visit.
Implements INodeVisitor.
Definition at line 50 of file DotGraphPrinter.cpp.
 {
     std::stringstream ss;
     ss << "Enabled: " << n.is_enabled();
     ss << R"( \n )";
     ss << "Axis: " << n.concatenation_axis();
     _info = ss.str();
 }
References ConcatenateLayerNode::concatenation_axis(), and ConcatenateLayerNode::is_enabled().
visit() [4/8]
void visit (ConvolutionLayerNode & n) override virtual
Visit ConvolutionLayerNode.
Parameters
[in] n Node to visit.
Implements INodeVisitor.
Definition at line 59 of file DotGraphPrinter.cpp.
 {
     std::stringstream ss;
     ss << n.convolution_method();
     _info = ss.str();
 }
References ConvolutionLayerNode::convolution_method().
visit() [5/8]
void visit (DepthwiseConvolutionLayerNode & n) override virtual
Visit DepthwiseConvolutionLayerNode.
Parameters
[in] n Node to visit.
Implements INodeVisitor.
Definition at line 66 of file DotGraphPrinter.cpp.
 {
     std::stringstream ss;
     ss << n.depthwise_convolution_method();
     _info = ss.str();
 }
References DepthwiseConvolutionLayerNode::depthwise_convolution_method().
visit() [6/8]
void visit (EltwiseLayerNode & n) override virtual
Visit EltwiseLayerNode.
Parameters
[in] n Node to visit.
Implements INodeVisitor.
Definition at line 73 of file DotGraphPrinter.cpp.
 {
     std::stringstream ss;
     ss << n.eltwise_operation();
     _info = ss.str();
 }
References EltwiseLayerNode::eltwise_operation().
visit() [7/8]
void visit (NormalizationLayerNode & n) override virtual
Visit NormalizationLayerNode.
Parameters
[in] n Node to visit.
Implements INodeVisitor.
Definition at line 80 of file DotGraphPrinter.cpp.
 {
     std::stringstream ss;
     ss << n.normalization_info().type();
     _info = ss.str();
 }
References NormalizationLayerNode::normalization_info(), and NormalizationLayerInfo::type().
visit() [8/8]
void visit (PoolingLayerNode & n) override virtual
Visit PoolingLayerNode.
Parameters
[in] n Node to visit.
Implements INodeVisitor.
Definition at line 87 of file DotGraphPrinter.cpp.
 {
     std::stringstream ss;
     ss << n.pooling_info().pool_type();
     ss << R"( \n )";
     ss << n.pooling_info().pool_size();
     ss << R"( \n )";
     ss << n.pooling_info().pad_stride_info();
     _info = ss.str();
 }
References PoolingLayerInfo::pad_stride_info(), PoolingLayerInfo::pool_size(), PoolingLayerInfo::pool_type(), and PoolingLayerNode::pooling_info().
The documentation for this class was generated from the following files:
arm_compute/graph/printers/DotGraphPrinter.h
src/graph/printers/DotGraphPrinter.cpp