Compute Library: MemoryRegion Class Reference
MemoryRegion Class Reference final
Memory region CPU implementation.
#include <MemoryRegion.h>
Public Member Functions
MemoryRegion (size_t size, size_t alignment=0)
Constructor.
MemoryRegion (void *ptr, size_t size)
MemoryRegion (const MemoryRegion &)=delete
Prevent instances of this class from being copied (As this class contains pointers)
MemoryRegion (MemoryRegion &&)=default
Default move constructor.
MemoryRegion & operator= (const MemoryRegion &)=delete
Prevent instances of this class from being copied (As this class contains pointers)
MemoryRegion & operator= (MemoryRegion &&)=default
Default move assignment operator.
void * buffer () final
Returns the pointer to the allocated data.
void * buffer () const final
Returns the pointer to the allocated data.
std::unique_ptr< IMemoryRegion > extract_subregion (size_t offset, size_t size) final
Extract a sub-region from the memory.
Public Member Functions inherited from IMemoryRegion
IMemoryRegion (size_t size)
Default constructor.
virtual ~IMemoryRegion ()=default
Virtual Destructor.
size_t size () const
Memory region size accessor.
void set_size (size_t size)
Sets size of region.
Detailed Description
Memory region CPU implementation.
Definition at line 37 of file MemoryRegion.h.
Constructor & Destructor Documentation
MemoryRegion() [1/4]
MemoryRegion (size_t size, size_t alignment = 0) inline
Constructor.
Parameters
[in] size Region size
[in] alignment Alignment in bytes of the base pointer. Defaults to 0
Definition at line 45 of file MemoryRegion.h.
         : IMemoryRegion(size), _mem(nullptr), _ptr(nullptr)
     {
         if(size != 0)
         {
             // Allocate backing memory
             size_t space = size + alignment;
             _mem         = std::shared_ptr<uint8_t>(new uint8_t[space](), [](uint8_t *ptr)
             {
                 delete[] ptr;
             });
             _ptr = _mem.get();
             // Calculate alignment offset
             if(alignment != 0)
             {
                 void *aligned_ptr = _mem.get();
                 support::cpp11::align(alignment, size, aligned_ptr, space);
                 _ptr = aligned_ptr;
             }
         }
     }
References arm_compute::support::cpp11::align(), and IMemoryRegion::size().
MemoryRegion() [2/4]
MemoryRegion (void * ptr, size_t size) inline
Definition at line 67 of file MemoryRegion.h.
         : IMemoryRegion(size), _mem(nullptr), _ptr(nullptr)
     {
         if(size != 0)
         {
             _ptr = ptr;
         }
     }
References IMemoryRegion::size().
MemoryRegion() [3/4]
MemoryRegion (const MemoryRegion &) delete
Prevent instances of this class from being copied (As this class contains pointers)
MemoryRegion() [4/4]
MemoryRegion (MemoryRegion &&) default
Default move constructor.
Member Function Documentation
buffer() [1/2]
void* buffer () inline final virtual
Returns the pointer to the allocated data.
Returns
Pointer to the allocated data
Implements IMemoryRegion.
Definition at line 85 of file MemoryRegion.h.
     {
         return _ptr;
     }
buffer() [2/2]
void* buffer () const inline final virtual
Returns the pointer to the allocated data.
Returns
Pointer to the allocated data
Implements IMemoryRegion.
Definition at line 89 of file MemoryRegion.h.
     {
         return _ptr;
     }
extract_subregion()
std::unique_ptr<IMemoryRegion> extract_subregion (size_t offset, size_t size) inline final virtual
Extract a sub-region from the memory.
Warning
Ownership is maintained by the parent memory, while a wrapped raw memory region is returned by this function. Thus parent memory should not be released before this.
Parameters
[in] offset Offset to the region
[in] size Size of the region
Returns
A wrapped memory sub-region with no ownership of the underlying memory
Implements IMemoryRegion.
Definition at line 93 of file MemoryRegion.h.
     {
         if(_ptr != nullptr && (offset < _size) && (_size - offset >= size))
         {
             return support::cpp14::make_unique<MemoryRegion>(static_cast<uint8_t *>(_ptr) + offset, size);
         }
         else
         {
             return nullptr;
         }
     }
References offset(), and IMemoryRegion::size().
operator=() [1/2]
MemoryRegion& operator= (const MemoryRegion &) delete
Prevent instances of this class from being copied (As this class contains pointers)
operator=() [2/2]
MemoryRegion& operator= (MemoryRegion &&) default
Default move assignment operator.
The documentation for this class was generated from the following file:
arm_compute/runtime/MemoryRegion.h