Compute Library: UpsampleLayerNode Class Reference
UpsampleLayerNode Class Reference final
Upsample Layer node.
#include <UpsampleLayerNode.h>
Public Member Functions
UpsampleLayerNode (Size2D info, InterpolationPolicy upsampling_policy)
Constructor.
Size2D info () const
Stride info metadata accessor.
InterpolationPolicy upsampling_policy () const
Upsampling policy metadata accessor.
NodeType type () const override
Returns node's type.
bool forward_descriptors () override
Forwards descriptor information to outputs if possible.
TensorDescriptor configure_output (size_t idx) const override
Calculates output configuration.
void accept (INodeVisitor &v) override
Accepts a node visitor.
Public Member Functions inherited from INode
INode ()
Constructor.
virtual ~INode ()=default
Destructor.
INode (const INode &)=delete
Prevent instances of this class from being copied (As this class contains pointers)
INode & operator= (const INode &)=delete
Prevent instances of this class from being copy assigned (As this class contains pointers)
INode (INode &&)=default
Allow instances of this class to be moved.
INode & operator= (INode &&)=default
Allow instances of this class to be move assigned.
virtual Status validate () const
Validate node.
std::string name () const
Returns node's name.
NodeID id () const
Returns node's ID.
const Graph * graph () const
Returns node's Graph.
Graph * graph ()
Returns node's Graph.
void set_graph (Graph *g)
Sets the graph that this node is registered to.
void set_id (NodeID id)
Sets the node id.
void set_common_node_parameters (NodeParams common_params)
Sets common node parameters.
void set_requested_target (Target target)
Sets target preference.
void set_assigned_target (Target target)
Sets the final execution target.
void set_output_tensor (TensorID tid, size_t idx)
Sets the output tensor of at a given index.
const std::vector< TensorID > & inputs () const
Returns inputs of the node.
const std::vector< TensorID > & outputs () const
Returns outputs of the node.
const std::vector< EdgeID > & input_edges () const
Returns input edge set.
const std::set< EdgeID > & output_edges () const
Returns output edge set.
TensorID input_id (size_t idx) const
Returns the tensor ID of a given input of the node.
TensorID output_id (size_t idx) const
Returns the tensor ID of a given output of the node.
Tensor * input (size_t idx) const
Returns the tensor of a given input of the node.
Tensor * output (size_t idx) const
Returns the tensor of a given output of the node.
EdgeID input_edge_id (size_t idx) const
Returns the edge ID of a given input of the node.
Edge * input_edge (size_t idx) const
Returns the edge of a given input of the node.
size_t num_inputs () const
Returns number of inputs of the node.
size_t num_outputs () const
Returns number of outputs of the node.
NodeParams common_node_params () const
Returns common node parameters.
Target requested_target () const
Returns requested target for this node.
Target assigned_target () const
Returns assigned target for this node.
Static Public Member Functions
static TensorDescriptor compute_output_descriptor (const TensorDescriptor &input_descriptor, Size2D info)
Computes upsample output descriptor.
Detailed Description
Upsample Layer node.
Definition at line 34 of file UpsampleLayerNode.h.
Constructor & Destructor Documentation
UpsampleLayerNode()
UpsampleLayerNode (Size2D info, InterpolationPolicy upsampling_policy)
Constructor.
Parameters
[in] info Stride info
[in] upsampling_policy Upsampling policy
Definition at line 34 of file UpsampleLayerNode.cpp.
     : _info(info), _upsampling_policy(upsampling_policy)
 {
     _input_edges.resize(1, EmptyEdgeID);
     _outputs.resize(1, NullTensorID);
 }
References arm_compute::graph::EmptyEdgeID, and arm_compute::graph::NullTensorID.
Member Function Documentation
accept()
void accept (INodeVisitor & v) override virtual
Accepts a node visitor.
Parameters
[in] v Visitor to accept
Implements INode.
Definition at line 92 of file UpsampleLayerNode.cpp.
 {
     v.visit(*this);
 }
References INodeVisitor::visit().
compute_output_descriptor()
TensorDescriptor compute_output_descriptor (const TensorDescriptor & input_descriptor, Size2D info) static
Computes upsample output descriptor.
Parameters
[in] input_descriptor Input descriptor
[in] info Stride information
Returns
Output descriptor
Definition at line 51 of file UpsampleLayerNode.cpp.
 {
     const unsigned int input_width  = get_dimension_size(input_descriptor, DataLayoutDimension::WIDTH);
     const unsigned int input_height = get_dimension_size(input_descriptor, DataLayoutDimension::HEIGHT);
     TensorDescriptor output_descriptor = input_descriptor;
     output_descriptor.shape.set(get_dimension_idx(output_descriptor, DataLayoutDimension::WIDTH), input_width * info.x());
     output_descriptor.shape.set(get_dimension_idx(output_descriptor, DataLayoutDimension::HEIGHT), input_height * info.y());
     return output_descriptor;
 }
References arm_compute::graph::get_dimension_idx(), arm_compute::graph::get_dimension_size(), arm_compute::HEIGHT, UpsampleLayerNode::info(), TensorShape::set(), TensorDescriptor::shape, arm_compute::WIDTH, Size2D::x(), and Size2D::y().
Referenced by UpsampleLayerNode::configure_output().
configure_output()
TensorDescriptor configure_output (size_t idx) const override virtual
Calculates output configuration.
Parameters
[in] idx Output index to configure
Returns
Output descriptor configuration
Implements INode.
Definition at line 76 of file UpsampleLayerNode.cpp.
 {
     ARM_COMPUTE_UNUSED(idx);
     ARM_COMPUTE_ERROR_ON(idx >= _outputs.size());
     const Tensor *src = input(0);
     ARM_COMPUTE_ERROR_ON(src == nullptr);
     return compute_output_descriptor(src->desc(), _info);
 }
References ARM_COMPUTE_ERROR_ON, ARM_COMPUTE_UNUSED, UpsampleLayerNode::compute_output_descriptor(), INode::input(), and arm_compute::test::validation::src.
Referenced by UpsampleLayerNode::forward_descriptors().
forward_descriptors()
bool forward_descriptors () override virtual
Forwards descriptor information to outputs if possible.
Returns
True if descriptor information could be forwarded otherwise false
Implements INode.
Definition at line 64 of file UpsampleLayerNode.cpp.
 {
     if((input_id(0) != NullTensorID) && (output_id(0) != NullTensorID))
     {
         Tensor *dst = output(0);
         ARM_COMPUTE_ERROR_ON(dst == nullptr);
         dst->desc() = configure_output(0);
         return true;
     }
     return false;
 }
References ARM_COMPUTE_ERROR_ON, UpsampleLayerNode::configure_output(), arm_compute::test::validation::dst, INode::input_id(), arm_compute::graph::NullTensorID, INode::output(), and INode::output_id().
info()
Size2D info () const
Stride info metadata accessor.
Returns
The stride info of the layer
Definition at line 41 of file UpsampleLayerNode.cpp.
 {
     return _info;
 }
Referenced by UpsampleLayerNode::compute_output_descriptor(), arm_compute::graph::backends::detail::create_upsample_layer(), and arm_compute::graph::backends::detail::validate_upsample_layer().
type()
NodeType type () const override virtual
Returns node's type.
Returns
Node's type
Implements INode.
Definition at line 87 of file UpsampleLayerNode.cpp.
 {
     return NodeType::UpsampleLayer;
 }
References arm_compute::graph::UpsampleLayer.
Referenced by arm_compute::graph::backends::detail::create_upsample_layer().
upsampling_policy()
InterpolationPolicy upsampling_policy () const
Upsampling policy metadata accessor.
Returns
The upsampling policy of the layer
Definition at line 46 of file UpsampleLayerNode.cpp.
 {
     return _upsampling_policy;
 }
Referenced by arm_compute::graph::backends::detail::create_upsample_layer(), and arm_compute::graph::backends::detail::validate_upsample_layer().
The documentation for this class was generated from the following files:
arm_compute/graph/nodes/UpsampleLayerNode.h
src/graph/nodes/UpsampleLayerNode.cpp