Compute Library: IGCKernel Class Reference
IGCKernel Class Reference abstract
Common interface for all the GLES kernels.
#include <IGCKernel.h>
Public Member Functions
IGCKernel ()
Constructor.
GCKernel & kernel ()
Returns a reference to the GLES kernel of this object.
void add_1D_tensor_argument (unsigned int &idx, const IGCTensor *tensor, const unsigned int binding_point, const Window &window)
Add the passed 1D tensor's parameters to the object's kernel's arguments starting from the index idx.
void add_2D_tensor_argument (unsigned int &idx, const IGCTensor *tensor, const unsigned int binding_point, const Window &window)
Add the passed 2D tensor's parameters to the object's kernel's arguments starting from the index idx.
void add_3D_tensor_argument (unsigned int &idx, const IGCTensor *tensor, const unsigned int binding_point, const Window &window)
Add the passed 3D tensor's parameters to the object's kernel's arguments starting from the index idx.
unsigned int num_arguments_per_1D_tensor () const
Returns the number of arguments enqueued per 1D tensor object.
unsigned int num_arguments_per_2D_tensor () const
Returns the number of arguments enqueued per 2D tensor object.
unsigned int num_arguments_per_3D_tensor () const
Returns the number of arguments enqueued per 3D tensor object.
virtual void run (const Window &window)=0
Enqueue the OpenGL ES shader to process the given window.
void set_lws_hint (gles::NDRange &lws_hint)
Set the Local-Workgroup-Size hint.
void set_target (GPUTarget target)
Set the targeted GPU architecture.
GPUTarget get_target () const
Get the targeted GPU architecture.
Public Member Functions inherited from IKernel
IKernel ()
Constructor.
virtual ~IKernel ()=default
Destructor.
virtual bool is_parallelisable () const
Indicates whether or not the kernel is parallelisable.
virtual BorderSize border_size () const
The size of the border for that kernel.
const Window & window () const
The maximum window the kernel can be executed on.
Detailed Description
Common interface for all the GLES kernels.
Definition at line 39 of file IGCKernel.h.
Constructor & Destructor Documentation
IGCKernel()
IGCKernel ()
Constructor.
Definition at line 64 of file IGCKernel.cpp.
     : _kernel(), _lws_hint(gles::NDRange(1U, 1U, 1U)), _target(GPUTarget::MIDGARD)
 {
 }
References arm_compute::MIDGARD.
Member Function Documentation
add_1D_tensor_argument()
void add_1D_tensor_argument (unsigned int & idx, const IGCTensor * tensor, const unsigned int binding_point, const Window & window)
Add the passed 1D tensor's parameters to the object's kernel's arguments starting from the index idx.
Parameters
[in] idx Index at which to start adding the tensor's arguments.Input and output tensor will have sperated index, multiple indices start from 1, single index have to be set to 0.
[in] tensor Tensor to set as an argument of the object's kernel.
[in] binding_point Tensor's binding point in this kernel.
[in] window Window the kernel will be executed on.
Definition at line 122 of file IGCKernel.cpp.
 {
     add_tensor_argument<1>(idx, tensor, binding_point, window);
 }
References IKernel::window().
Referenced by GCGEMMMatrixAccumulateBiasesKernel::run(), GCDepthwiseConvolutionLayer3x3Kernel::run(), GCNormalizePlanarYUVLayerKernel::run(), GCWeightsReshapeKernel::run(), and GCBatchNormalizationLayerKernel::run().
add_2D_tensor_argument()
void add_2D_tensor_argument (unsigned int & idx, const IGCTensor * tensor, const unsigned int binding_point, const Window & window)
Add the passed 2D tensor's parameters to the object's kernel's arguments starting from the index idx.
Parameters
[in] idx Index at which to start adding the tensor's arguments.Input and output tensor will have sperated index, multiple indices start from 1, single index have to be set to 0.
[in] tensor Tensor to set as an argument of the object's kernel.
[in] binding_point Tensor's binding point in this kernel.
[in] window Window the kernel will be executed on.
Definition at line 127 of file IGCKernel.cpp.
 {
     add_tensor_argument<2>(idx, tensor, binding_point, window);
 }
References IKernel::window().
Referenced by IGCSimple2DKernel::run(), GCTransposeKernel::run(), GCGEMMMatrixAccumulateBiasesKernel::run(), GCGEMMMatrixAdditionKernel::run(), GCAbsoluteDifferenceKernel::run(), GCGEMMTranspose1xWKernel::run(), GCGEMMInterleave4x4Kernel::run(), GCWeightsReshapeKernel::run(), GCCol2ImKernel::run(), and GCGEMMMatrixMultiplyKernel::run().
add_3D_tensor_argument()
void add_3D_tensor_argument (unsigned int & idx, const IGCTensor * tensor, const unsigned int binding_point, const Window & window)
Add the passed 3D tensor's parameters to the object's kernel's arguments starting from the index idx.
Parameters
[in] idx Index at which to start adding the tensor's arguments.Input and output tensor will have sperated index, multiple indices start from 1, single index have to be set to 0.
[in] tensor Tensor to set as an argument of the object's kernel.
[in] binding_point Tensor's binding point in this kernel.
[in] window Window the kernel will be executed on.
Definition at line 132 of file IGCKernel.cpp.
 {
     add_tensor_argument<3>(idx, tensor, binding_point, window);
 }
References IKernel::window().
Referenced by IGCSimple3DKernel::run(), GCScaleKernel::run(), GCActivationLayerKernel::run(), GCPixelWiseMultiplicationKernel::run(), GCDepthwiseConvolutionLayer3x3Kernel::run(), GCNormalizationLayerKernel::run(), GCDepthConcatenateLayerKernel::run(), GCDropoutLayerKernel::run(), GCLogits1DShiftExpSumKernel::run(), GCFillBorderKernel::run(), GCPoolingLayerKernel::run(), GCArithmeticAdditionKernel::run(), GCNormalizePlanarYUVLayerKernel::run(), GCTensorShiftKernel::run(), GCWeightsReshapeKernel::run(), GCCol2ImKernel::run(), GCBatchNormalizationLayerKernel::run(), and GCLogits1DNormKernel::run().
get_target()
GPUTarget get_target () const inline
Get the targeted GPU architecture.
Returns
The targeted GPU architecture.
Definition at line 122 of file IGCKernel.h.
     {
         return _target;
     }
Referenced by GCGEMMMatrixMultiplyKernel::configure().
kernel()
GCKernel & kernel ()
Returns a reference to the GLES kernel of this object.
Returns
A reference to the GLES kernel of this object.
Definition at line 69 of file IGCKernel.cpp.
 {
     return _kernel;
 }
Referenced by arm_compute::enqueue().
num_arguments_per_1D_tensor()
unsigned int num_arguments_per_1D_tensor () const
Returns the number of arguments enqueued per 1D tensor object.
Returns
The number of arguments enqueues per 1D tensor object.
Definition at line 137 of file IGCKernel.cpp.
 {
     return num_arguments_per_tensor<1>();
 }
Referenced by GCWeightsReshapeKernel::configure().
num_arguments_per_2D_tensor()
unsigned int num_arguments_per_2D_tensor () const
Returns the number of arguments enqueued per 2D tensor object.
Returns
The number of arguments enqueues per 2D tensor object.
Definition at line 142 of file IGCKernel.cpp.
 {
     return num_arguments_per_tensor<2>();
 }
Referenced by GCWeightsReshapeKernel::configure().
num_arguments_per_3D_tensor()
unsigned int num_arguments_per_3D_tensor () const
Returns the number of arguments enqueued per 3D tensor object.
Returns
The number of arguments enqueues per 3D tensor object.
Definition at line 147 of file IGCKernel.cpp.
 {
     return num_arguments_per_tensor<3>();
 }
Referenced by GCLogits1DMaxKernel::configure(), GCScaleKernel::configure(), GCFillBorderKernel::configure(), GCLogits1DShiftExpSumKernel::configure(), GCWeightsReshapeKernel::configure(), GCDepthwiseConvolutionLayer3x3Kernel::run(), GCNormalizePlanarYUVLayerKernel::run(), GCCol2ImKernel::run(), and GCBatchNormalizationLayerKernel::run().
run()
virtual void run (const Window & window) pure virtual
Enqueue the OpenGL ES shader to process the given window.
Parameters
[in] window Region on which to execute the kernel. (Must be a valid region of the window returned by window()).
Implemented in GCLogits1DNormKernel, GCBatchNormalizationLayerKernel, GCGEMMMatrixMultiplyKernel, GCIm2ColKernel, GCCol2ImKernel, GCWeightsReshapeKernel, GCTensorShiftKernel, GCNormalizePlanarYUVLayerKernel, GCArithmeticAdditionKernel, GCGEMMInterleave4x4Kernel, GCPoolingLayerKernel, GCDirectConvolutionLayerKernel< kernel_size >, GCFillBorderKernel, GCDropoutLayerKernel, GCLogits1DShiftExpSumKernel, GCDepthConcatenateLayerKernel, GCGEMMTranspose1xWKernel, GCAbsoluteDifferenceKernel, GCGEMMMatrixAdditionKernel, GCNormalizationLayerKernel, GCActivationLayerKernel, GCDepthwiseConvolutionLayer3x3Kernel, GCPixelWiseMultiplicationKernel, GCGEMMMatrixAccumulateBiasesKernel, GCScaleKernel, GCTransposeKernel, IGCSimple3DKernel, and IGCSimple2DKernel.
Referenced by GCScheduler::dispatch().
set_lws_hint()
void set_lws_hint (gles::NDRange & lws_hint) inline
Set the Local-Workgroup-Size hint.
Note
This method should be called after the configuration of the kernel
Parameters
[in] lws_hint Local-Workgroup-Size to use
Definition at line 104 of file IGCKernel.h.
     {
         _lws_hint = lws_hint;
     }
set_target()
void set_target (GPUTarget target) inline
Set the targeted GPU architecture.
Parameters
[in] target The targeted GPU architecture
Definition at line 113 of file IGCKernel.h.
     {
         _target = target;
     }
Referenced by GCGEMM::configure(), and GCConvolutionLayer::configure().
The documentation for this class was generated from the following files:
arm_compute/core/GLES_COMPUTE/IGCKernel.h
src/core/GLES_COMPUTE/IGCKernel.cpp