Compute Library: GCIm2ColKernel Class Reference
GCIm2ColKernel Class Reference
Interface for the im2col reshape kernel.
#include <GCIm2ColKernel.h>
Public Member Functions
GCIm2ColKernel ()
Default constructor.
GCIm2ColKernel (const GCIm2ColKernel &)=delete
Prevent instances of this class from being copied (As this class contains pointers)
GCIm2ColKernel & operator= (const GCIm2ColKernel &)=delete
Prevent instances of this class from being copied (As this class contains pointers)
GCIm2ColKernel (GCIm2ColKernel &&)=default
Allow instances of this class to be moved.
GCIm2ColKernel & operator= (GCIm2ColKernel &&)=default
Allow instances of this class to be moved.
void configure (const IGCTensor *input, IGCTensor *output, const Size2D &kernel_dims, const PadStrideInfo &conv_info, bool has_bias, const Size2D &dilation=Size2D(1U, 1U))
Set the input and output of the kernel.
void run (const Window &window) override
Enqueue the OpenGL ES shader to process the given window.
Public Member Functions inherited from IGCKernel
IGCKernel ()
Constructor.
GCKernel & kernel ()
Returns a reference to the GLES kernel of this object.
void add_1D_tensor_argument (unsigned int &idx, const IGCTensor *tensor, const unsigned int binding_point, const Window &window)
Add the passed 1D tensor's parameters to the object's kernel's arguments starting from the index idx.
void add_2D_tensor_argument (unsigned int &idx, const IGCTensor *tensor, const unsigned int binding_point, const Window &window)
Add the passed 2D tensor's parameters to the object's kernel's arguments starting from the index idx.
void add_3D_tensor_argument (unsigned int &idx, const IGCTensor *tensor, const unsigned int binding_point, const Window &window)
Add the passed 3D tensor's parameters to the object's kernel's arguments starting from the index idx.
unsigned int num_arguments_per_1D_tensor () const
Returns the number of arguments enqueued per 1D tensor object.
unsigned int num_arguments_per_2D_tensor () const
Returns the number of arguments enqueued per 2D tensor object.
unsigned int num_arguments_per_3D_tensor () const
Returns the number of arguments enqueued per 3D tensor object.
void set_lws_hint (gles::NDRange &lws_hint)
Set the Local-Workgroup-Size hint.
void set_target (GPUTarget target)
Set the targeted GPU architecture.
GPUTarget get_target () const
Get the targeted GPU architecture.
Public Member Functions inherited from IKernel
IKernel ()
Constructor.
virtual ~IKernel ()=default
Destructor.
virtual bool is_parallelisable () const
Indicates whether or not the kernel is parallelisable.
virtual BorderSize border_size () const
The size of the border for that kernel.
const Window & window () const
The maximum window the kernel can be executed on.
Static Public Member Functions
static Status validate (const ITensorInfo *input, const ITensorInfo *output, const Size2D &kernel_dims, const PadStrideInfo &conv_info, bool has_bias, const Size2D &dilation=Size2D(1U, 1U))
Static function to check if given info will lead to a valid configuration of CLIm2ColKernel.
Detailed Description
Interface for the im2col reshape kernel.
Rearranges image blocks into columns. It is used to strip out each convolution block to a single column. It is used to transform a convolution to a plain matrix multiplication.
For example taking into account the image below and assuming 3x3 image blocks with stride of 1 we have:
\[ \left(\begin{array}{cccc} a00 & a01 & a02 & a03 \\ a10 & a11 & a12 & a13 \\ a20 & a21 & a22 & a23 \\ a30 & a31 & a32 & a33 \\ \end{array} \right) = \left(\begin{array}{ccccccccc} a00 & a01 & a02 & a10 & a11 & a12 & a20 & a21 & a22 \\ a01 & a02 & a03 & a11 & a12 & a13 & a21 & a22 & a23 \\ a10 & a11 & a12 & a20 & a21 & a22 & a30 & a31 & a32 \\ a11 & a12 & a13 & a21 & a22 & a23 & a31 & a32 & a33 \\ \end{array} \right) \]
Definition at line 57 of file GCIm2ColKernel.h.
Constructor & Destructor Documentation
GCIm2ColKernel() [1/3]
GCIm2ColKernel ()
Default constructor.
Definition at line 62 of file GCIm2ColKernel.cpp.
     : _input(nullptr), _output(nullptr), _convolved_dims(), _kernel_dims(), _num_elems_processed_per_iteration(1), _run_func(nullptr)
 {
 }
GCIm2ColKernel() [2/3]
GCIm2ColKernel (const GCIm2ColKernel &) delete
Prevent instances of this class from being copied (As this class contains pointers)
GCIm2ColKernel() [3/3]
GCIm2ColKernel (GCIm2ColKernel &&) default
Allow instances of this class to be moved.
Member Function Documentation
configure()
void configure (const IGCTensor * input, IGCTensor * output, const Size2D & kernel_dims, const PadStrideInfo & conv_info, bool has_bias, const Size2D & dilation = Size2D(1U, 1U))
Set the input and output of the kernel.
Parameters
[in] input The input tensor to convert. 3 lower dimensions represent a single input [width, height, IFM], while every optional dimension from 4 and above represent a batch of inputs. Data types supported: F16/F32
[out] output The output tensor. First 2 lower dimensions represent a transform of each 3D input, while every dimension above represents a batch. Data types supported: Same as input
[in] kernel_dims The kernel dimensions (width and height).
[in] conv_info Contains padding and stride information described in PadStrideInfo.
[in] has_bias In case biases are provided expands the matrix with 1.
[in] dilation (Optional) Dilation, in elements, across x and y. Defaults to (1, 1).
Definition at line 67 of file GCIm2ColKernel.cpp.
 {
     ARM_COMPUTE_ERROR_ON_NULLPTR(input, output);
     // Perform validation step
     ARM_COMPUTE_ERROR_THROW_ON(validate_arguments(input->info(), output->info()));
     _input  = input;
     _output = output;
     // Create kernel
     std::set<std::string> build_opts;
     std::string           dt_name = (input->info()->data_type() == DataType::F32) ? "DATA_TYPE_FP32" : "DATA_TYPE_FP16";
     build_opts.emplace("#define LOCAL_SIZE_X " + support::cpp11::to_string(1));
     build_opts.emplace("#define LOCAL_SIZE_Y " + support::cpp11::to_string(1));
     build_opts.emplace("#define LOCAL_SIZE_Z " + support::cpp11::to_string(1));
     build_opts.insert("#define " + dt_name);
     if(has_bias)
     {
         build_opts.emplace("#define HAS_BIAS");
     }
     int stride_x = 0;
     int stride_y = 0;
     std::tie(stride_x, stride_y) = conv_info.stride();
     _kernel_dims = std::make_pair(kernel_dims.width, kernel_dims.height);
     const bool run_img2col_reduced = (output->info()->dimension(0) == (input->info()->dimension(0) * input->info()->dimension(1) * input->info()->dimension(2))) && (TensorShape::num_max_dimensions >= 4)
                                      && (std::equal(input->info()->tensor_shape().cbegin() + 3,
                                                     input->info()->tensor_shape().cend(),
                                                     output->info()->tensor_shape().cbegin() + 1))
                                      && ((stride_x == 1) && (stride_y == 1) && !conv_info.has_padding())
                                      && (dilation == Size2D(1U, 1U));
     std::string kernel_name = "im2col_generic";
     if(!run_img2col_reduced)
     {
         if(input->info()->data_type() == DataType::F16 && _kernel_dims == std::pair<unsigned int, unsigned int>(1, 1))
         {
             build_opts.emplace("#define KERNEL_1x1");
         }
         build_opts.emplace("#define IM2COL_GENERIC");
         _convolved_dims = scaled_dimensions(input->info()->dimension(0), input->info()->dimension(1),
                                             kernel_dims.width, kernel_dims.height,
                                             conv_info, dilation);
         _num_elems_processed_per_iteration = (input->info()->data_type() == DataType::F32) ? 1 : 2;
         build_opts.emplace("#define KERNEL_WIDTH " + support::cpp11::to_string(kernel_dims.width));
         build_opts.emplace("#define KERNEL_HEIGHT " + support::cpp11::to_string(kernel_dims.height));
         build_opts.emplace("#define KERNEL_DEPTH " + support::cpp11::to_string(input->info()->dimension(2)));
         build_opts.emplace("#define CONVOLVED_WIDTH " + support::cpp11::to_string(_convolved_dims.first));
         build_opts.emplace("#define CONVOLVED_HEIGHT " + support::cpp11::to_string(_convolved_dims.second));
         build_opts.emplace("#define STRIDE_X " + support::cpp11::to_string(conv_info.stride().first));
         build_opts.emplace("#define STRIDE_Y " + support::cpp11::to_string(conv_info.stride().second));
         build_opts.emplace("#define PAD_LEFT " + support::cpp11::to_string(conv_info.pad_left()));
         build_opts.emplace("#define PAD_TOP " + support::cpp11::to_string(conv_info.pad_top()));
         build_opts.emplace("#define PAD_RIGHT " + support::cpp11::to_string(conv_info.pad_right()));
         build_opts.emplace("#define PAD_BOTTOM " + support::cpp11::to_string(conv_info.pad_bottom()));
         build_opts.emplace("#define SRC_WIDTH " + support::cpp11::to_string(input->info()->dimension(0)));
         build_opts.emplace("#define SRC_HEIGHT " + support::cpp11::to_string(input->info()->dimension(1)));
         build_opts.emplace("#define DILATION_X " + support::cpp11::to_string(dilation.x()));
         build_opts.emplace("#define DILATION_Y " + support::cpp11::to_string(dilation.y()));
         _run_func = &GCIm2ColKernel::run_generic;
     }
     else
     {
         build_opts.emplace("#define IM2COL_REDUCED");
         kernel_name = "im2col_reduced";
         if(input->info()->data_type() == DataType::F32)
         {
             _num_elems_processed_per_iteration = 4 / input->info()->element_size();
         }
         else if(input->info()->data_type() == DataType::F16)
         {
             int input_width  = input->info()->dimension(0);
             int input_height = input->info()->dimension(1);
             build_opts.emplace("#define IMAGE_SIZE " + support::cpp11::to_string(input_width * input_height));
             if(input_width % 8 == 0)
             {
                 _num_elems_processed_per_iteration = 8;
                 build_opts.emplace("#define IM2COL_REDUCED_8X");
             }
             else if(input_width % 4 == 0)
             {
                 _num_elems_processed_per_iteration = 4;
                 build_opts.emplace("#define IM2COL_REDUCED_4X");
             }
             else if(input_width % 2 == 0)
             {
                 _num_elems_processed_per_iteration = 2;
                 build_opts.emplace("#define IM2COL_REDUCED_2X");
             }
             else
             {
                 _num_elems_processed_per_iteration = 2;
                 build_opts.emplace("#define IM2COL_REDUCED_GENERIC");
             }
         }
         _run_func = &GCIm2ColKernel::run_reduced;
     }
     // Create kernel
     _kernel = static_cast<GCKernel>(GCKernelLibrary::get().create_kernel(kernel_name, build_opts));
     // Configure kernel window
     Window win = calculate_max_window(*input->info(), Steps(_num_elems_processed_per_iteration));
     if(input->info()->data_type() == DataType::F16)
     {
         // Calculate input right and bottom border
         const int input_width         = input->info()->dimension(0);
         const int input_height        = input->info()->dimension(1);
         int       input_total_width   = input->info()->padding().left + input_width + input->info()->padding().right;
         int       input_padding_right = ceil_to_multiple(input_total_width, _num_elems_processed_per_iteration) - input_total_width;
         input_total_width             = input_width + input_padding_right + input->info()->padding().right;
         AccessWindowStatic input_access(input->info(), 0, 0, input_total_width, input_height);
         // Calculate output right and bottom border
         const int          output_width         = output->info()->dimension(0);
         const int          output_height        = output->info()->dimension(1);
         const int          output_padding_right = ceil_to_multiple(output_width, _num_elems_processed_per_iteration) - output_width;
         AccessWindowStatic output_access(output->info(), 0, 0, output_width + output_padding_right, output_height);
         update_window_and_padding(win, input_access, output_access);
     }
     output->info()->set_valid_region(ValidRegion(Coordinates(), output->info()->tensor_shape()));
     if(!run_img2col_reduced)
     {
         // set the Z dimension's step same size as the whole dimension so that one can't split across the Z dimension
         win.set_dimension_step(Window::DimZ, win[Window::DimZ].end() - win[Window::DimZ].start());
     }
     IGCKernel::configure(win);
 }
References ARM_COMPUTE_ERROR_ON_NULLPTR, ARM_COMPUTE_ERROR_THROW_ON, arm_compute::calculate_max_window(), Dimensions< T >::cbegin(), arm_compute::ceil_to_multiple(), Dimensions< T >::cend(), arm_compute::test::validation::conv_info, arm_compute::create_kernel(), ITensorInfo::data_type(), arm_compute::test::validation::dilation, ITensorInfo::dimension(), Window::DimZ, ITensorInfo::element_size(), arm_compute::F16, arm_compute::F32, GCKernelLibrary::get(), Size2D::height, ITensor::info(), BorderSize::left, Dimensions< size_t >::num_max_dimensions, ITensorInfo::padding(), BorderSize::right, arm_compute::scaled_dimensions(), Window::set_dimension_step(), ITensorInfo::set_valid_region(), ITensorInfo::tensor_shape(), arm_compute::support::cpp11::to_string(), arm_compute::U, arm_compute::update_window_and_padding(), and Size2D::width.
Referenced by GCConvolutionLayer::configure().
operator=() [1/2]
GCIm2ColKernel& operator= (const GCIm2ColKernel &) delete
Prevent instances of this class from being copied (As this class contains pointers)
operator=() [2/2]
GCIm2ColKernel& operator= (GCIm2ColKernel &&) default
Allow instances of this class to be moved.
run()
void run (const Window & window) override virtual
Enqueue the OpenGL ES shader to process the given window.
Parameters
[in] window Region on which to execute the kernel. (Must be a valid region of the window returned by window()).
Implements IGCKernel.
Definition at line 221 of file GCIm2ColKernel.cpp.
 {
     ARM_COMPUTE_ERROR_ON(_run_func == nullptr);
     (this->*_run_func)(window);
 }
References ARM_COMPUTE_ERROR_ON, and IKernel::window().
validate()
Status validate (const ITensorInfo * input, const ITensorInfo * output, const Size2D & kernel_dims, const PadStrideInfo & conv_info, bool has_bias, const Size2D & dilation = Size2D(1U, 1U)) static
Static function to check if given info will lead to a valid configuration of CLIm2ColKernel.
Parameters
[in] input The input tensor to convert. 3 lower dimensions represent a single input [width, height, IFM], while every optional dimension from 4 and above represent a batch of inputs. Data types supported: F16/F32
[in] output The output tensor. First 2 lower dimensions represent a transform of each 3D input, while every dimension above represents a batch. Data types supported: Same as input
[in] kernel_dims The kernel dimensions (width and height).
[in] conv_info Contains padding and stride information described in PadStrideInfo.
[in] has_bias In case biases are provided expands the matrix with 1.
[in] dilation (Optional) Dilation, in elements, across x and y. Defaults to (1, 1).
Returns
a status
Definition at line 211 of file GCIm2ColKernel.cpp.
 {
     ARM_COMPUTE_UNUSED(kernel_dims);
     ARM_COMPUTE_UNUSED(conv_info);
     ARM_COMPUTE_UNUSED(has_bias);
     ARM_COMPUTE_UNUSED(dilation);
     ARM_COMPUTE_RETURN_ON_ERROR(validate_arguments(input, output));
     return Status{};
 }
References ARM_COMPUTE_RETURN_ON_ERROR, ARM_COMPUTE_UNUSED, arm_compute::test::validation::conv_info, and arm_compute::test::validation::dilation.
The documentation for this class was generated from the following files:
arm_compute/core/GLES_COMPUTE/kernels/GCIm2ColKernel.h
src/core/GLES_COMPUTE/kernels/GCIm2ColKernel.cpp