Compute Library: CLTileKernel Class Reference
CLTileKernel Class Reference
OpenCL kernel to perform a Tile operation.
#include <CLTileKernel.h>
Public Member Functions
CLTileKernel ()
Default constructor.
CLTileKernel (const CLTileKernel &)=delete
Prevent instances of this class from being copied (As this class contains pointers)
CLTileKernel & operator= (const CLTileKernel &)=delete
Prevent instances of this class from being copied (As this class contains pointers)
CLTileKernel (CLTileKernel &&)=default
Allow instances of this class to be moved.
CLTileKernel & operator= (CLTileKernel &&)=default
Allow instances of this class to be moved.
~CLTileKernel ()=default
Default destructor.
void configure (const ICLTensor *input, ICLTensor *output, const Multiples &multiples)
Set the source, destination of the kernel.
void run (const Window &window, cl::CommandQueue &queue) override
Enqueue the OpenCL kernel to process the given window on the passed OpenCL command queue.
Public Member Functions inherited from ICLKernel
ICLKernel ()
Constructor.
cl::Kernel & kernel ()
Returns a reference to the OpenCL kernel of this object.
template<typename T >
void add_1D_array_argument (unsigned int &idx, const ICLArray< T > *array, const Strides &strides, unsigned int num_dimensions, const Window &window)
Add the passed 1D array's parameters to the object's kernel's arguments starting from the index idx.
void add_1D_tensor_argument (unsigned int &idx, const ICLTensor *tensor, const Window &window)
Add the passed 1D tensor's parameters to the object's kernel's arguments starting from the index idx.
void add_2D_tensor_argument (unsigned int &idx, const ICLTensor *tensor, const Window &window)
Add the passed 2D tensor's parameters to the object's kernel's arguments starting from the index idx.
void add_3D_tensor_argument (unsigned int &idx, const ICLTensor *tensor, const Window &window)
Add the passed 3D tensor's parameters to the object's kernel's arguments starting from the index idx.
void add_4D_tensor_argument (unsigned int &idx, const ICLTensor *tensor, const Window &window)
Add the passed 4D tensor's parameters to the object's kernel's arguments starting from the index idx.
template<typename T >
void add_argument (unsigned int &idx, T value)
Add the passed parameters to the object's kernel's arguments starting from the index idx.
void set_lws_hint (const cl::NDRange &lws_hint)
Set the Local-Workgroup-Size hint.
cl::NDRange lws_hint () const
Return the Local-Workgroup-Size hint.
const std::string & config_id () const
Get the configuration ID.
void set_target (GPUTarget target)
Set the targeted GPU architecture.
void set_target (cl::Device &device)
Set the targeted GPU architecture according to the CL device.
GPUTarget get_target () const
Get the targeted GPU architecture.
size_t get_max_workgroup_size ()
Get the maximum workgroup size for the device the CLKernelLibrary uses.
template<typename T , unsigned int dimension_size>
void add_array_argument (unsigned &idx, const ICLArray< T > *array, const Strides &strides, unsigned int num_dimensions, const Window &window)
Add the passed array's parameters to the object's kernel's arguments starting from the index idx.
template<unsigned int dimension_size>
void add_tensor_argument (unsigned &idx, const ICLTensor *tensor, const Window &window)
Public Member Functions inherited from IKernel
IKernel ()
Constructor.
virtual ~IKernel ()=default
Destructor.
virtual bool is_parallelisable () const
Indicates whether or not the kernel is parallelisable.
virtual BorderSize border_size () const
The size of the border for that kernel.
const Window & window () const
The maximum window the kernel can be executed on.
Static Public Member Functions
static Status validate (const ITensorInfo *input, const ITensorInfo *output, const Multiples &multiples)
Static function to check if given info will lead to a valid configuration of CLTileKernel.
Static Public Member Functions inherited from ICLKernel
static constexpr unsigned int num_arguments_per_1D_array ()
Returns the number of arguments enqueued per 1D array object.
static constexpr unsigned int num_arguments_per_1D_tensor ()
Returns the number of arguments enqueued per 1D tensor object.
static constexpr unsigned int num_arguments_per_2D_tensor ()
Returns the number of arguments enqueued per 2D tensor object.
static constexpr unsigned int num_arguments_per_3D_tensor ()
Returns the number of arguments enqueued per 3D tensor object.
static constexpr unsigned int num_arguments_per_4D_tensor ()
Returns the number of arguments enqueued per 4D tensor object.
static cl::NDRange gws_from_window (const Window &window)
Get the global work size given an execution window.
Detailed Description
OpenCL kernel to perform a Tile operation.
Definition at line 34 of file CLTileKernel.h.
Constructor & Destructor Documentation
CLTileKernel() [1/3]
CLTileKernel ()
Default constructor.
Definition at line 63 of file CLTileKernel.cpp.
     : _input(nullptr), _output(nullptr)
 {
 }
CLTileKernel() [2/3]
CLTileKernel (const CLTileKernel &) delete
Prevent instances of this class from being copied (As this class contains pointers)
CLTileKernel() [3/3]
CLTileKernel (CLTileKernel &&) default
Allow instances of this class to be moved.
~CLTileKernel()
~CLTileKernel () default
Default destructor.
Member Function Documentation
configure()
void configure (const ICLTensor * input, ICLTensor * output, const Multiples & multiples)
Set the source, destination of the kernel.
Parameters
[in] input Source tensor. Data type supported: U8/S8/QASYMM8/U16/S16/F16/U32/S32/F32.
[in] multiples Contains the number of times the input tensor should be replicated on the given dimension. Cannot have more than 4 elements (tiling in dimensions greater than 4 is not supported).
[out] output Destination tensor. Same as input
Definition at line 68 of file CLTileKernel.cpp.
 {
     ARM_COMPUTE_ERROR_ON_NULLPTR(input, output);
     // Auto initialize output
     TensorShape tiled_shape = misc::shape_calculator::compute_tiled_shape(input->info()->tensor_shape(), multiples);
     auto_init_if_empty(*output->info(), tiled_shape, 1, input->info()->data_type());
     // Validate
     ARM_COMPUTE_ERROR_THROW_ON(validate_arguments(input->info(), output->info(), multiples));
     _input  = input;
     _output = output;
     const DataType     data_type      = input->info()->data_type();
     const int          vec_size_x     = 16 / input->info()->element_size();
     const int          input_width_x  = input->info()->tensor_shape().x();
     const unsigned int offset         = ceil_to_multiple(input_width_x, vec_size_x) - input_width_x;
     const bool         multi_access_x = (input_width_x / vec_size_x > 0);
     // Create kernel
     CLBuildOptions build_opts;
     build_opts.add_option("-DDATA_TYPE=" + get_cl_type_from_data_type(data_type));
     build_opts.add_option("-DSRC_WIDTH=" + support::cpp11::to_string(input_width_x));
     build_opts.add_option("-DSRC_HEIGHT=" + support::cpp11::to_string(input->info()->dimension(1)));
     build_opts.add_option("-DSRC_DEPTH=" + support::cpp11::to_string(input->info()->dimension(2)));
     build_opts.add_option("-DSRC_BATCHES=" + support::cpp11::to_string(input->info()->dimension(3)));
     build_opts.add_option("-DDST_DEPTH=" + support::cpp11::to_string(output->info()->dimension(2)));
     build_opts.add_option_if(multi_access_x, "-DOFFSET=" + support::cpp11::to_string(offset));
     build_opts.add_option_if(multi_access_x, "-DVEC_SIZE=" + support::cpp11::to_string(vec_size_x));
     _kernel = static_cast<cl::Kernel>(CLKernelLibrary::get().create_kernel("tile", build_opts.options()));
     // Configure window without padding
     Window win = calculate_max_window(*output->info());
     if(multi_access_x)
     {
         // If multi-access is enabled, no thread should cross the tile boundaries. This means we need
         // as many threads as those to cover a single tile times multiples[0]. Note that if threads
         // do not cross the boundaries of the tiles, they won't cross the boundaries of the last tile, and
         // we don't need to pad the output
         const unsigned int size_win_x = ceil_to_multiple(input->info()->dimension(0), vec_size_x) * multiples[0];
         win.set(Window::DimX,
                 Window::Dimension(win.x().start(), size_win_x, vec_size_x));
     }
     ICLKernel::configure_internal(win);
     // Set config_id for enabling LWS tuning
     _config_id = "tile";
     _config_id += "_";
     _config_id += lower_string(string_from_data_type(input->info()->data_type()));
     for(unsigned int i = 0; i < multiples.size(); ++i)
     {
         _config_id += "_";
         _config_id += support::cpp11::to_string(input->info()->dimension(i));
         _config_id += "_";
         _config_id += support::cpp11::to_string(multiples[i]);
     }
 }
References CLBuildOptions::add_option(), CLBuildOptions::add_option_if(), ARM_COMPUTE_ERROR_ON_NULLPTR, ARM_COMPUTE_ERROR_THROW_ON, arm_compute::auto_init_if_empty(), arm_compute::calculate_max_window(), arm_compute::ceil_to_multiple(), arm_compute::misc::shape_calculator::compute_tiled_shape(), arm_compute::create_kernel(), arm_compute::test::validation::data_type, ITensorInfo::data_type(), ITensorInfo::dimension(), Window::DimX, ITensorInfo::element_size(), CLKernelLibrary::get(), arm_compute::get_cl_type_from_data_type(), ITensor::info(), arm_compute::lower_string(), offset(), CLBuildOptions::options(), Window::set(), Window::Dimension::start(), arm_compute::string_from_data_type(), ITensorInfo::tensor_shape(), arm_compute::support::cpp11::to_string(), Dimensions< T >::x(), and Window::x().
operator=() [1/2]
CLTileKernel& operator= (const CLTileKernel &) delete
Prevent instances of this class from being copied (As this class contains pointers)
operator=() [2/2]
CLTileKernel& operator= (CLTileKernel &&) default
Allow instances of this class to be moved.
run()
void run (const Window & window, cl::CommandQueue & queue) override virtual
Enqueue the OpenCL kernel to process the given window on the passed OpenCL command queue.
Note
The queue is not flushed by this method, and therefore the kernel will not have been executed by the time this method returns.
Parameters
[in] window Region on which to execute the kernel. (Must be a valid region of the window returned by window()).
[in,out] queue Command queue on which to enqueue the kernel.
Implements ICLKernel.
Definition at line 135 of file CLTileKernel.cpp.
 {
     ARM_COMPUTE_ERROR_ON_UNCONFIGURED_KERNEL(this);
     ARM_COMPUTE_ERROR_ON_INVALID_SUBWINDOW(ICLKernel::window(), window);
     Window collapsed = window.collapse_if_possible(ICLKernel::window(), Window::DimZ);
     Window slice     = collapsed.first_slice_window_4D();
     do
     {
         unsigned int idx = 0;
         add_4D_tensor_argument(idx, _input, slice);
         add_4D_tensor_argument(idx, _output, slice);
         enqueue(queue, *this, slice);
     }
     while(collapsed.slide_window_slice_4D(slice));
 }
References ICLKernel::add_4D_tensor_argument(), ARM_COMPUTE_ERROR_ON_INVALID_SUBWINDOW, ARM_COMPUTE_ERROR_ON_UNCONFIGURED_KERNEL, Window::collapse_if_possible(), Window::DimZ, arm_compute::enqueue(), Window::first_slice_window_4D(), arm_compute::test::validation::reference::slice(), Window::slide_window_slice_4D(), and IKernel::window().
validate()
Status validate (const ITensorInfo * input, const ITensorInfo * output, const Multiples & multiples) static
Static function to check if given info will lead to a valid configuration of CLTileKernel.
Parameters
[in] input Source tensor info. Data type supported: U8/S8/QASYMM8/U16/S16/F16/U32/S32/F32.
[in] multiples Contains the number of times the input tensor should be replicated on the given dimension. Cannot have more than 4 elements (tiling in dimensions greater than 4 is not supported).
[in] output Destination tensor info. Same as input
Returns
a status
Definition at line 129 of file CLTileKernel.cpp.
 {
     ARM_COMPUTE_RETURN_ON_ERROR(validate_arguments(input, output, multiples));
     return Status{};
 }
References ARM_COMPUTE_RETURN_ON_ERROR.
Referenced by CLTile::validate().
The documentation for this class was generated from the following files:
arm_compute/core/CL/kernels/CLTileKernel.h
src/core/CL/kernels/CLTileKernel.cpp