Compute Library: GCFunctionFactory Class Reference
GCFunctionFactory Class Reference final
Factory for generating GLES compute backend functions.
#include <GCFunctionFactory.h>
Static Public Member Functions
static std::unique_ptr< arm_compute::IFunction > create (INode *node, GraphContext &ctx)
Create a backend execution function depending on the node type.
Detailed Description
Factory for generating GLES compute backend functions.
Definition at line 42 of file GCFunctionFactory.h.
Member Function Documentation
create()
std::unique_ptr< IFunction > create (INode * node, GraphContext & ctx) static
Create a backend execution function depending on the node type.
Parameters
[in] node Node to create the backend function for
[in] ctx Context to use
Returns
Backend function
Definition at line 268 of file GCFunctionsFactory.cpp.
 {
     if(node == nullptr)
     {
         return nullptr;
     }
     NodeType type = node->type();
     switch(type)
     {
         case NodeType::ActivationLayer:
             return detail::create_activation_layer<GCActivationLayer, GCTargetInfo>(*polymorphic_downcast<ActivationLayerNode *>(node));
         case NodeType::BatchNormalizationLayer:
             return detail::create_batch_normalization_layer<GCBatchNormalizationLayer, GCTargetInfo>(*polymorphic_downcast<BatchNormalizationLayerNode *>(node));
         case NodeType::ConvolutionLayer:
             return detail::create_convolution_layer<GCConvolutionLayerFunctions, GCTargetInfo>(*polymorphic_downcast<ConvolutionLayerNode *>(node), ctx);
         case NodeType::ConcatenateLayer:
             return detail::create_concatenate_layer<GCDepthConcatenateLayer, GCTargetInfo>(*polymorphic_downcast<ConcatenateLayerNode *>(node));
         case NodeType::DepthwiseConvolutionLayer:
             return detail::create_depthwise_convolution_layer<GCDepthwiseConvolutionLayerFunctions, GCTargetInfo>(*polymorphic_downcast<DepthwiseConvolutionLayerNode *>(node));
         case NodeType::EltwiseLayer:
             return detail::create_eltwise_layer<GCEltwiseFunctions, GCTargetInfo>(*polymorphic_downcast<EltwiseLayerNode *>(node));
         case NodeType::FullyConnectedLayer:
             return detail::create_fully_connected_layer<GCFullyConnectedLayer, GCTargetInfo>(*polymorphic_downcast<FullyConnectedLayerNode *>(node), ctx);
         case NodeType::NormalizationLayer:
             return detail::create_normalization_layer<GCNormalizationLayer, GCTargetInfo>(*polymorphic_downcast<NormalizationLayerNode *>(node), ctx);
         case NodeType::NormalizePlanarYUVLayer:
             return detail::create_normalize_planar_yuv_layer<GCNormalizePlanarYUVLayer, GCTargetInfo>(*polymorphic_downcast<NormalizePlanarYUVLayerNode *>(node));
         case NodeType::PoolingLayer:
             return detail::create_pooling_layer<GCPoolingLayer, GCTargetInfo>(*polymorphic_downcast<PoolingLayerNode *>(node));
         case NodeType::ResizeLayer:
             return detail::create_resize_layer<GCScale, GCTargetInfo>(*polymorphic_downcast<ResizeLayerNode *>(node));
         case NodeType::SoftmaxLayer:
             return detail::create_softmax_layer<GCSoftmaxLayer, GCTargetInfo>(*polymorphic_downcast<SoftmaxLayerNode *>(node), ctx);
         default:
             return nullptr;
     }
 }
References arm_compute::graph::backends::detail::create_concatenate_layer< GCDepthConcatenateLayer, GCTargetInfo >(), arm_compute::graph::backends::detail::create_convolution_layer< GCConvolutionLayerFunctions, GCTargetInfo >(), arm_compute::graph::backends::detail::create_depthwise_convolution_layer< GCDepthwiseConvolutionLayerFunctions, GCTargetInfo >(), arm_compute::graph::backends::detail::create_eltwise_layer< GCEltwiseFunctions, GCTargetInfo >(), and INode::type().
Referenced by GCDeviceBackend::configure_node().
The documentation for this class was generated from the following files:
arm_compute/graph/backends/GLES/GCFunctionFactory.h
src/graph/backends/GLES/GCFunctionsFactory.cpp