Compute Library: CLHistogramKernel Class Reference
CLHistogramKernel Class Reference
Interface to run the histogram kernel.
#include <CLHistogramKernel.h>
Public Member Functions
CLHistogramKernel ()
Constructor.
CLHistogramKernel (const CLHistogramKernel &)=delete
Prevent instances of this class from being copied (As this class contains pointers)
CLHistogramKernel & operator= (const CLHistogramKernel &)=delete
Prevent instances of this class from being copied (As this class contains pointers)
CLHistogramKernel (CLHistogramKernel &&)=default
Allow instances of this class to be moved.
CLHistogramKernel & operator= (CLHistogramKernel &&)=default
Allow instances of this class to be moved.
void configure (const ICLImage *input, ICLDistribution1D *output)
Initialise the kernel's input, output and border mode.
void run (const Window &window, cl::CommandQueue &queue) override
Enqueue the OpenCL kernel to process the given window on the passed OpenCL command queue.
Public Member Functions inherited from ICLKernel
ICLKernel ()
Constructor.
cl::Kernel & kernel ()
Returns a reference to the OpenCL kernel of this object.
template<typename T >
void add_1D_array_argument (unsigned int &idx, const ICLArray< T > *array, const Strides &strides, unsigned int num_dimensions, const Window &window)
Add the passed 1D array's parameters to the object's kernel's arguments starting from the index idx.
void add_1D_tensor_argument (unsigned int &idx, const ICLTensor *tensor, const Window &window)
Add the passed 1D tensor's parameters to the object's kernel's arguments starting from the index idx.
void add_2D_tensor_argument (unsigned int &idx, const ICLTensor *tensor, const Window &window)
Add the passed 2D tensor's parameters to the object's kernel's arguments starting from the index idx.
void add_3D_tensor_argument (unsigned int &idx, const ICLTensor *tensor, const Window &window)
Add the passed 3D tensor's parameters to the object's kernel's arguments starting from the index idx.
void add_4D_tensor_argument (unsigned int &idx, const ICLTensor *tensor, const Window &window)
Add the passed 4D tensor's parameters to the object's kernel's arguments starting from the index idx.
template<typename T >
void add_argument (unsigned int &idx, T value)
Add the passed parameters to the object's kernel's arguments starting from the index idx.
void set_lws_hint (const cl::NDRange &lws_hint)
Set the Local-Workgroup-Size hint.
cl::NDRange lws_hint () const
Return the Local-Workgroup-Size hint.
const std::string & config_id () const
Get the configuration ID.
void set_target (GPUTarget target)
Set the targeted GPU architecture.
void set_target (cl::Device &device)
Set the targeted GPU architecture according to the CL device.
GPUTarget get_target () const
Get the targeted GPU architecture.
size_t get_max_workgroup_size ()
Get the maximum workgroup size for the device the CLKernelLibrary uses.
template<typename T , unsigned int dimension_size>
void add_array_argument (unsigned &idx, const ICLArray< T > *array, const Strides &strides, unsigned int num_dimensions, const Window &window)
Add the passed array's parameters to the object's kernel's arguments starting from the index idx.
template<unsigned int dimension_size>
void add_tensor_argument (unsigned &idx, const ICLTensor *tensor, const Window &window)
Public Member Functions inherited from IKernel
IKernel ()
Constructor.
virtual ~IKernel ()=default
Destructor.
virtual bool is_parallelisable () const
Indicates whether or not the kernel is parallelisable.
virtual BorderSize border_size () const
The size of the border for that kernel.
const Window & window () const
The maximum window the kernel can be executed on.
Additional Inherited Members
Static Public Member Functions inherited from ICLKernel
static constexpr unsigned int num_arguments_per_1D_array ()
Returns the number of arguments enqueued per 1D array object.
static constexpr unsigned int num_arguments_per_1D_tensor ()
Returns the number of arguments enqueued per 1D tensor object.
static constexpr unsigned int num_arguments_per_2D_tensor ()
Returns the number of arguments enqueued per 2D tensor object.
static constexpr unsigned int num_arguments_per_3D_tensor ()
Returns the number of arguments enqueued per 3D tensor object.
static constexpr unsigned int num_arguments_per_4D_tensor ()
Returns the number of arguments enqueued per 4D tensor object.
static cl::NDRange gws_from_window (const Window &window)
Get the global work size given an execution window.
Detailed Description
Interface to run the histogram kernel.
This kernel processes the part of image with width can be divided by 16. If the image width is not a multiple of 16, remaining pixels have to be processed with the CLHistogramBorderKernel
Definition at line 38 of file CLHistogramKernel.h.
Constructor & Destructor Documentation
CLHistogramKernel() [1/3]
CLHistogramKernel ()
Constructor.
Definition at line 48 of file CLHistogramKernel.cpp.
     : _input(nullptr), _output(nullptr)
 {
 }
CLHistogramKernel() [2/3]
CLHistogramKernel (const CLHistogramKernel &) delete
Prevent instances of this class from being copied (As this class contains pointers)
CLHistogramKernel() [3/3]
CLHistogramKernel (CLHistogramKernel &&) default
Allow instances of this class to be moved.
Member Function Documentation
configure()
void configure (const ICLImage * input, ICLDistribution1D * output)
Initialise the kernel's input, output and border mode.
Parameters
[in] input Source image. Data types supported: U8.
[out] output Destination distribution.
Definition at line 53 of file CLHistogramKernel.cpp.
 {
     ARM_COMPUTE_ERROR_ON_TENSOR_NOT_2D(input);
     ARM_COMPUTE_ERROR_ON(nullptr == output);
     // Check input size
     ARM_COMPUTE_ERROR_ON_DATA_TYPE_CHANNEL_NOT_IN(input, 1, DataType::U8);
     // Check offset
     ARM_COMPUTE_ERROR_ON_MSG(0 > output->offset() || output->offset() > 256, "Offset is larger than the image value range.");
     // Check range
     ARM_COMPUTE_ERROR_ON_MSG(output->range() > 256 /* max range */, "Range larger than the image value range.");
     _input  = input;
     _output = output;
     if(_input->info()->dimension(0) < pixels_per_item)
     {
         return;
     }
     unsigned int num_bins    = _output->num_bins();
     unsigned int window_size = _output->window();
     unsigned int offset      = _output->offset();
     unsigned int range       = _output->range();
     unsigned int offrange    = offset + range;
     unsigned int bin_size    = _output->size();
     unsigned int buffer_size = bin_size + 1; // We need one extra place for pixels that don't meet the conditions
     // Create kernel
     bool        is_fixed_size = (256 == num_bins) && (1 == window_size) && (0 == offset) && (256 == offrange);
     std::string kernel_name   = is_fixed_size ? "hist_local_kernel_fixed" : "hist_local_kernel";
     _kernel                   = static_cast<cl::Kernel>(CLKernelLibrary::get().create_kernel(kernel_name));
     // Set static kernel arguments
     unsigned int idx = num_arguments_per_2D_tensor(); //Skip the input and output parameters
     _kernel.setArg(idx++, buffer_size, nullptr);
     _kernel.setArg(idx++, _output->cl_buffer());
     if(!is_fixed_size)
     {
         _kernel.setArg<cl_uint>(idx++, num_bins);
         _kernel.setArg<cl_uint>(idx++, offset);
         _kernel.setArg<cl_uint>(idx++, range);
         _kernel.setArg<cl_uint>(idx++, offrange);
     }
     // We only run histogram on Image, therefore only 2 dimensions here
     unsigned int end_position = (_input->info()->dimension(0) / pixels_per_item) * pixels_per_item;
     // Configure kernel window
     Window win;
     win.set(0, Window::Dimension(0, end_position, pixels_per_item));
     win.set(1, Window::Dimension(0, _input->info()->dimension(1)));
     update_window_and_padding(win, AccessWindowHorizontal(input->info(), 0, pixels_per_item));
     ICLKernel::configure_internal(win);
 }
References ARM_COMPUTE_ERROR_ON, ARM_COMPUTE_ERROR_ON_DATA_TYPE_CHANNEL_NOT_IN, ARM_COMPUTE_ERROR_ON_MSG, ARM_COMPUTE_ERROR_ON_TENSOR_NOT_2D, ICLDistribution1D::cl_buffer(), arm_compute::create_kernel(), CLKernelLibrary::get(), ITensor::info(), ICLKernel::num_arguments_per_2D_tensor(), IDistribution1D::num_bins(), IDistribution1D::offset(), offset(), pixels_per_item, arm_compute::test::validation::reference::range(), IDistribution1D::range(), Window::set(), IDistribution1D::size(), arm_compute::U8, arm_compute::update_window_and_padding(), and IDistribution1D::window().
Referenced by CLEqualizeHistogram::configure(), and CLHistogram::configure().
operator=() [1/2]
CLHistogramKernel& operator= (const CLHistogramKernel &) delete
Prevent instances of this class from being copied (As this class contains pointers)
operator=() [2/2]
CLHistogramKernel& operator= (CLHistogramKernel &&) default
Allow instances of this class to be moved.
run()
void run (const Window & window, cl::CommandQueue & queue) override virtual
Enqueue the OpenCL kernel to process the given window on the passed OpenCL command queue.
Note
The queue is not flushed by this method, and therefore the kernel will not have been executed by the time this method returns.
Parameters
[in] window Region on which to execute the kernel. (Must be a valid region of the window returned by window()).
[in,out] queue Command queue on which to enqueue the kernel.
Implements ICLKernel.
Definition at line 113 of file CLHistogramKernel.cpp.
 {
     ARM_COMPUTE_ERROR_ON_UNCONFIGURED_KERNEL(this);
     ARM_COMPUTE_ERROR_ON_MISMATCHING_WINDOWS(ICLKernel::window(), window);
     // TODO (COMPMID-679): Add CLMemFill
     _output->map(queue, true);
     ARM_COMPUTE_ERROR_ON(_output->buffer() == nullptr);
     memset(_output->buffer(), 0, _output->size());
     _output->unmap(queue);
     if(_input->info()->dimension(0) < pixels_per_item)
     {
         return;
     }
     Window             slice = window.first_slice_window_2D();
     const unsigned int gws_x = (window.x().end() - window.x().start()) / window.x().step();
     cl::NDRange        lws   = (local_x_size < gws_x) ? cl::NDRange(local_x_size, 1) : cl::NDRange(1, 1);
     do
     {
         /* Run the core part which has width can be divided by 16 */
         unsigned int idx = 0;
         add_2D_tensor_argument(idx, _input, slice);
         enqueue(queue, *this, slice, lws);
     }
     while(window.slide_window_slice_2D(slice));
 }
References ICLKernel::add_2D_tensor_argument(), ARM_COMPUTE_ERROR_ON, ARM_COMPUTE_ERROR_ON_MISMATCHING_WINDOWS, ARM_COMPUTE_ERROR_ON_UNCONFIGURED_KERNEL, ICLDistribution1D::buffer(), ITensorInfo::dimension(), Window::Dimension::end(), arm_compute::enqueue(), Window::first_slice_window_2D(), ITensor::info(), local_x_size, ICLDistribution1D::map(), pixels_per_item, IDistribution1D::size(), arm_compute::test::validation::reference::slice(), Window::slide_window_slice_2D(), Window::Dimension::start(), Window::Dimension::step(), ICLDistribution1D::unmap(), IKernel::window(), and Window::x().
The documentation for this class was generated from the following files:
arm_compute/core/CL/kernels/CLHistogramKernel.h
src/core/CL/kernels/CLHistogramKernel.cpp