Compute Library: IDistribution Class Reference
IDistribution Class Reference abstract
Interface for distribution objects.
#include <IDistribution.h>
Public Member Functions
virtual ~IDistribution ()=default
Default virtual destructor.
virtual size_t dimensions () const =0
Returns the dimensions of the distribution.
virtual size_t size () const =0
Returns the total size in bytes of the distribution.
virtual uint32_t * buffer () const =0
Returns a pointer to the start of the distribution.
void clear () const
Clears the distribution by setting every element to zero.
Detailed Description
Interface for distribution objects.
Definition at line 33 of file IDistribution.h.
Constructor & Destructor Documentation
~IDistribution()
virtual ~IDistribution () virtual default
Default virtual destructor.
Member Function Documentation
buffer()
virtual uint32_t* buffer () const pure virtual
Returns a pointer to the start of the distribution.
Other elements of the array can be accessed using buffer()[idx] for 0 <= idx < num_bins()
Returns
Pointer to the start of the distribution.
Implemented in ICLDistribution1D, and Distribution1D.
Referenced by IDistribution::clear(), and NECumulativeDistributionKernel::run().
clear()
void clear () const
Clears the distribution by setting every element to zero.
Definition at line 32 of file IDistribution.cpp.
 {
     ARM_COMPUTE_ERROR_ON(nullptr == buffer());
     std::memset(buffer(), 0, size());
 }
References ARM_COMPUTE_ERROR_ON, IDistribution::buffer(), and IDistribution::size().
dimensions()
virtual size_t dimensions () const pure virtual
Returns the dimensions of the distribution.
Note
This is fixed to 1-dimensional distribution for now.
Returns
Dimensions of the distribution.
Implemented in IDistribution1D.
size()
virtual size_t size () const pure virtual
Returns the total size in bytes of the distribution.
Returns
Total size of the distribution in bytes.
Implemented in IDistribution1D.
Referenced by IDistribution::clear().
The documentation for this class was generated from the following files:
arm_compute/core/IDistribution.h
src/core/IDistribution.cpp