Compute Library: CLGaussianPyramidHalf Class Reference
CLGaussianPyramidHalf Class Reference
Basic function to execute gaussian pyramid with HALF scale factor.
#include <CLGaussianPyramid.h>
Public Member Functions
CLGaussianPyramidHalf ()
Constructor.
void configure (ICLTensor *input, CLPyramid *pyramid, BorderMode border_mode, uint8_t constant_border_value) override
Initialise the function's source, destinations and border mode.
void run () override
Run the kernels contained in the function.
Public Member Functions inherited from CLGaussianPyramid
CLGaussianPyramid ()
Constructor.
CLGaussianPyramid (const CLGaussianPyramid &)=delete
Prevent instances of this class from being copied (As this class contains pointers)
CLGaussianPyramid & operator= (const CLGaussianPyramid &)=delete
Prevent instances of this class from being copied (As this class contains pointers)
CLGaussianPyramid (CLGaussianPyramid &&)=default
Allow instances of this class to be moved.
CLGaussianPyramid & operator= (CLGaussianPyramid &&)=default
Allow instances of this class to be moved.
virtual ~CLGaussianPyramid ()=default
Default destructor.
Public Member Functions inherited from IFunction
virtual ~IFunction ()=default
Destructor.
virtual void prepare ()
Prepare the function for executing.
Detailed Description
Basic function to execute gaussian pyramid with HALF scale factor.
This function calls the following OpenCL kernels:
CLFillBorderKernel (executed if border_mode == CONSTANT or border_mode == REPLICATE)
CLGaussianPyramidHorKernel
CLGaussianPyramidVertKernel
Definition at line 82 of file CLGaussianPyramid.h.
Constructor & Destructor Documentation
CLGaussianPyramidHalf()
CLGaussianPyramidHalf ()
Constructor.
Definition at line 51 of file CLGaussianPyramid.cpp.
     : _horizontal_border_handler(),
       _vertical_border_handler(),
       _horizontal_reduction(),
       _vertical_reduction()
 {
 }
Member Function Documentation
configure()
void configure (ICLTensor * input, CLPyramid * pyramid, BorderMode border_mode, uint8_t constant_border_value) override virtual
Initialise the function's source, destinations and border mode.
Parameters
[in,out] input Source tensor. Data types supported: U8. (Written to only for border_mode != UNDEFINED)
[out] pyramid Destination pyramid tensors, Data types supported at each level: U8.
[in] border_mode Border mode to use.
[in] constant_border_value (Optional) Constant value to use for borders if border_mode is set to CONSTANT.
Implements CLGaussianPyramid.
Definition at line 59 of file CLGaussianPyramid.cpp.
 {
     ARM_COMPUTE_ERROR_ON_DATA_TYPE_CHANNEL_NOT_IN(input, 1, DataType::U8);
     ARM_COMPUTE_ERROR_ON(pyramid == nullptr);
     ARM_COMPUTE_ERROR_ON(input->info()->num_dimensions() != pyramid->get_pyramid_level(0)->info()->num_dimensions());
     ARM_COMPUTE_ERROR_ON(input->info()->dimension(0) != pyramid->info()->width());
     ARM_COMPUTE_ERROR_ON(input->info()->dimension(1) != pyramid->info()->height());
     ARM_COMPUTE_ERROR_ON(SCALE_PYRAMID_HALF != pyramid->info()->scale());
     // Constant value to use for vertical fill border when the border mode is CONSTANT
     const uint16_t pixel_value_u16 = static_cast<uint16_t>(constant_border_value) * 2 + static_cast<uint16_t>(constant_border_value) * 8 + static_cast<uint16_t>(constant_border_value) * 6;
     /* Get number of pyramid levels */
     const size_t num_levels = pyramid->info()->num_levels();
     _input   = input;
     _pyramid = pyramid;
     if(num_levels > 1)
     {
         _horizontal_border_handler = arm_compute::support::cpp14::make_unique<CLFillBorderKernel[]>(num_levels - 1);
         _vertical_border_handler   = arm_compute::support::cpp14::make_unique<CLFillBorderKernel[]>(num_levels - 1);
         _horizontal_reduction      = arm_compute::support::cpp14::make_unique<CLGaussianPyramidHorKernel[]>(num_levels - 1);
         _vertical_reduction        = arm_compute::support::cpp14::make_unique<CLGaussianPyramidVertKernel[]>(num_levels - 1);
         // Apply half scale to the X dimension of the tensor shape
         TensorShape tensor_shape = pyramid->info()->tensor_shape();
         tensor_shape.set(0, (pyramid->info()->width() + 1) * SCALE_PYRAMID_HALF);
         PyramidInfo pyramid_info(num_levels - 1, SCALE_PYRAMID_HALF, tensor_shape, Format::U16);
         _tmp.init(pyramid_info);
         for(size_t i = 0; i < num_levels - 1; ++i)
         {
             /* Configure horizontal kernel */
             _horizontal_reduction[i].configure(_pyramid->get_pyramid_level(i), _tmp.get_pyramid_level(i));
             /* Configure vertical kernel */
             _vertical_reduction[i].configure(_tmp.get_pyramid_level(i), _pyramid->get_pyramid_level(i + 1));
             /* Configure border */
             _horizontal_border_handler[i].configure(_pyramid->get_pyramid_level(i), _horizontal_reduction[i].border_size(), border_mode, PixelValue(constant_border_value));
             /* Configure border */
             _vertical_border_handler[i].configure(_tmp.get_pyramid_level(i), _vertical_reduction[i].border_size(), border_mode, PixelValue(pixel_value_u16));
         }
         _tmp.allocate();
     }
 }
References ARM_COMPUTE_ERROR_ON, ARM_COMPUTE_ERROR_ON_DATA_TYPE_CHANNEL_NOT_IN, arm_compute::test::validation::border_mode, ITensorInfo::dimension(), CLPyramid::get_pyramid_level(), PyramidInfo::height(), ITensor::info(), CLTensor::info(), CLPyramid::info(), ITensorInfo::num_dimensions(), TensorInfo::num_dimensions(), PyramidInfo::num_levels(), PyramidInfo::scale(), arm_compute::SCALE_PYRAMID_HALF, TensorShape::set(), PyramidInfo::tensor_shape(), arm_compute::U16, arm_compute::U8, and PyramidInfo::width().
Referenced by CLLaplacianPyramid::configure().
run()
void run () override virtual
Run the kernels contained in the function.
For NEON kernels:
Multi-threading is used for the kernels which are parallelisable.
By default std::thread::hardware_concurrency() threads are used.
Note
CPPScheduler::set_num_threads() can be used to manually set the number of threads
For OpenCL kernels:
All the kernels are enqueued on the queue associated with CLScheduler.
The queue is then flushed.
Note
The function will not block until the kernels are executed. It is the user's responsibility to wait.
Will call prepare() on first run if hasn't been done
Implements IFunction.
Definition at line 109 of file CLGaussianPyramid.cpp.
 {
     ARM_COMPUTE_ERROR_ON_MSG(_pyramid == nullptr, "Unconfigured function");
     /* Get number of pyramid levels */
     const size_t num_levels = _pyramid->info()->num_levels();
     /* The first level of the pyramid has the input image */
     _pyramid->get_pyramid_level(0)->map(CLScheduler::get().queue(), true /* blocking */);
     _input->map(CLScheduler::get().queue(), true /* blocking */);
     _pyramid->get_pyramid_level(0)->copy_from(*_input);
     _input->unmap(CLScheduler::get().queue());
     _pyramid->get_pyramid_level(0)->unmap(CLScheduler::get().queue());
     for(unsigned int i = 0; i < num_levels - 1; ++i)
     {
         CLScheduler::get().enqueue(_horizontal_border_handler[i], false);
         CLScheduler::get().enqueue(_horizontal_reduction[i], false);
         CLScheduler::get().enqueue(_vertical_border_handler[i], false);
         CLScheduler::get().enqueue(_vertical_reduction[i], false);
     }
 }
References ARM_COMPUTE_ERROR_ON_MSG, CLScheduler::enqueue(), and CLScheduler::get().
Referenced by CLLaplacianPyramid::run().
The documentation for this class was generated from the following files:
arm_compute/runtime/CL/functions/CLGaussianPyramid.h
src/runtime/CL/functions/CLGaussianPyramid.cpp