Compute Library: NEDepthwiseConvolutionLayer3x3Kernel Class Reference
NEDepthwiseConvolutionLayer3x3Kernel Class Reference
Interface for the kernel to run a 3x3 depthwise convolution on a tensor.
#include <NEDepthwiseConvolutionLayer3x3Kernel.h>
Public Member Functions
const char * name () const override
Name of the kernel.
NEDepthwiseConvolutionLayer3x3Kernel ()
Default constructor.
NEDepthwiseConvolutionLayer3x3Kernel (const NEDepthwiseConvolutionLayer3x3Kernel &)=delete
Prevent instances of this class from being copied (As this class contains pointers)
NEDepthwiseConvolutionLayer3x3Kernel & operator= (const NEDepthwiseConvolutionLayer3x3Kernel &)=delete
Prevent instances of this class from being copied (As this class contains pointers)
NEDepthwiseConvolutionLayer3x3Kernel (NEDepthwiseConvolutionLayer3x3Kernel &&)=default
Default Move Constructor.
NEDepthwiseConvolutionLayer3x3Kernel & operator= (NEDepthwiseConvolutionLayer3x3Kernel &&)=default
Default move assignment operator.
void configure (const ITensor *input, const ITensor *weights, ITensor *output, const PadStrideInfo &conv_info, unsigned int depth_multiplier=1, DataLayout data_layout=DataLayout::NCHW)
Initialize the function's source, destination, conv and border_size.
void generate_convolver ()
Generates the convolver object.
void run (const Window &window, const ThreadInfo &info) override
Execute the kernel on the passed window.
BorderSize border_size () const override
The size of the border for that kernel.
Public Member Functions inherited from ICPPKernel
virtual ~ICPPKernel ()=default
Default destructor.
Public Member Functions inherited from IKernel
IKernel ()
Constructor.
virtual ~IKernel ()=default
Destructor.
virtual bool is_parallelisable () const
Indicates whether or not the kernel is parallelisable.
const Window & window () const
The maximum window the kernel can be executed on.
Static Public Member Functions
static bool is_optimized_execution_possible (TensorShape input_shape, PadStrideInfo conv_info, DataType dt, unsigned int depth_multiplier=1, DataLayout data_layout=DataLayout::NCHW)
Static method that checks if optimized execution is supported for the given parameters.
static Status validate (const ITensorInfo *input, const ITensorInfo *weights, const ITensorInfo *output, const PadStrideInfo &conv_info, unsigned int depth_multiplier=1)
Static function to check if given info will lead to a valid configuration of NEDepthwiseConvolutionLayer3x3Kernel.
Detailed Description
Interface for the kernel to run a 3x3 depthwise convolution on a tensor.
Definition at line 37 of file NEDepthwiseConvolutionLayer3x3Kernel.h.
Constructor & Destructor Documentation
NEDepthwiseConvolutionLayer3x3Kernel() [1/3]
NEDepthwiseConvolutionLayer3x3Kernel ()
Default constructor.
Definition at line 270 of file NEDepthwiseConvolutionLayer3x3Kernel.cpp.
     : _border_size(0), _input(), _output(), _weights(), _conv_info(), _convolver(nullptr), _num_elems_written_per_iteration(0), _run_optimized(false), _depth_multiplier(1)
 {
 }
NEDepthwiseConvolutionLayer3x3Kernel() [2/3]
NEDepthwiseConvolutionLayer3x3Kernel (const NEDepthwiseConvolutionLayer3x3Kernel &) delete
Prevent instances of this class from being copied (As this class contains pointers)
NEDepthwiseConvolutionLayer3x3Kernel() [3/3]
NEDepthwiseConvolutionLayer3x3Kernel (NEDepthwiseConvolutionLayer3x3Kernel &&) default
Default Move Constructor.
Member Function Documentation
border_size()
BorderSize border_size () const override virtual
The size of the border for that kernel.
Returns
The width in number of elements of the border.
Reimplemented from IKernel.
Definition at line 275 of file NEDepthwiseConvolutionLayer3x3Kernel.cpp.
 {
     return _border_size;
 }
Referenced by NEDepthwiseConvolutionLayer3x3::configure().
configure()
void configure (const ITensor * input, const ITensor * weights, ITensor * output, const PadStrideInfo & conv_info, unsigned int depth_multiplier = 1, DataLayout data_layout = DataLayout::NCHW)
Initialize the function's source, destination, conv and border_size.
Note
Supported data layouts: NCHW and NHWC
Parameters
[in] input Source tensor. DataType supported: QASYMM8/F16/F32.
[in] weights Weights tensor. This is a 3D tensor with dimensions [3, 3, IFM] for NCHW or [IFM, 3, 3] if NHWC data layout. Data type supported: Same as input.
[out] output Destination tensor. Data type supported: Same as input.
[in] conv_info Padding and stride information to use for the convolution.
[in] depth_multiplier (Optional) Multiplier to apply to the input's depth in order to retrieve the output's depth. Defaults to 1.
[in] data_layout (Optional) Data layout of the input and weights tensor
Definition at line 280 of file NEDepthwiseConvolutionLayer3x3Kernel.cpp.
 {
     ARM_COMPUTE_ERROR_ON_NULLPTR(input, weights, output);
     _input            = input;
     _output           = output;
     _weights          = weights;
     _conv_info        = conv_info;
     _depth_multiplier = depth_multiplier;
     _convolver        = nullptr;
     _run_optimized = NEDepthwiseConvolutionLayer3x3Kernel::is_optimized_execution_possible(input->info()->tensor_shape(),
                                                                                            conv_info,
                                                                                            input->info()->data_type(), depth_multiplier,
                                                                                            data_layout);
     (_run_optimized) ? configure_optimized() : configure_generic();
 }
References ARM_COMPUTE_ERROR_ON_NULLPTR, arm_compute::test::validation::conv_info, ITensorInfo::data_type(), ITensor::info(), NEDepthwiseConvolutionLayer3x3Kernel::is_optimized_execution_possible(), ITensorInfo::tensor_shape(), and arm_compute::test::validation::weights.
Referenced by NEDepthwiseConvolutionLayer3x3::configure().
generate_convolver()
void generate_convolver ()
Generates the convolver object.
Definition at line 350 of file NEDepthwiseConvolutionLayer3x3Kernel.cpp.
 {
     ARM_COMPUTE_ERROR_ON_CPU_F16_UNSUPPORTED(_input);
     ARM_COMPUTE_ERROR_ON_DATA_TYPE_CHANNEL_NOT_IN(_input, 1, DataType::QASYMM8, DataType::F16, DataType::F32);
     ARM_COMPUTE_ERROR_ON_MISMATCHING_DATA_TYPES(_input, _weights);
     ARM_COMPUTE_ERROR_ON(_weights->info()->dimension(1) != 3 || _weights->info()->dimension(2) != 3);
     _convolver = create_convolver_object(_conv_info, _weights, _input, _output, true);
     if(_convolver)
     {
         _convolver->set_offsets(-_input->info()->quantization_info().offset, -_weights->info()->quantization_info().offset);
     }
 }
References ARM_COMPUTE_ERROR_ON, ARM_COMPUTE_ERROR_ON_CPU_F16_UNSUPPORTED, ARM_COMPUTE_ERROR_ON_DATA_TYPE_CHANNEL_NOT_IN, ARM_COMPUTE_ERROR_ON_MISMATCHING_DATA_TYPES, ITensorInfo::dimension(), arm_compute::F16, arm_compute::F32, ITensor::info(), QuantizationInfo::offset, arm_compute::QASYMM8, and ITensorInfo::quantization_info().
Referenced by NEDepthwiseConvolutionLayer3x3::run().
is_optimized_execution_possible()
bool is_optimized_execution_possible (TensorShape input_shape, PadStrideInfo conv_info, DataType dt, unsigned int depth_multiplier = 1, DataLayout data_layout = DataLayout::NCHW) static
Static method that checks if optimized execution is supported for the given parameters.
Parameters
[in] input_shape Input shape
[in] conv_info Padding and stride information to use for the convolution.
[in] dt Data type of the input and weights
[in] depth_multiplier (Optional) Multiplier to apply to the input's depth in order to retrieve the output's depth. Defaults to 1.
[in] data_layout (Optional) Data layout of the input and weights tensor
Returns
True if the optimized kernels can be executed else false
Definition at line 319 of file NEDepthwiseConvolutionLayer3x3Kernel.cpp.
 {
     // Reshape input shape if in NHWC format
     TensorShape in_shape{ input_shape };
     if(data_layout == DataLayout::NHWC)
     {
         in_shape.set(Window::DimX, input_shape.y());
         in_shape.set(Window::DimY, input_shape.z());
         in_shape.set(Window::DimZ, input_shape.x());
     }
     // Check supported data type
     bool supported_datatype = is_data_type_float(dt) || is_data_type_quantized(dt);
     // Check for supported strides
     const auto &strides           = conv_info.stride();
     bool        supported_strides = (strides.first == strides.second) && ((strides.first == 1) || (strides.first == 2));
     // Check for supported padding
     const auto    pad_top           = conv_info.pad_top();
     const auto    pad_right         = conv_info.pad_right();
     const auto    pad_bottom        = conv_info.pad_bottom();
     const auto    pad_left          = conv_info.pad_left();
     PadStrideInfo same_pad          = calculate_same_pad(in_shape, TensorShape(3U, 3U), conv_info);
     bool          is_same_padding   = (pad_top == same_pad.pad_top()) && (pad_right == same_pad.pad_right()) && (pad_bottom == same_pad.pad_bottom()) && (pad_left == same_pad.pad_left());
     bool          is_valid_padding  = (pad_top == 0) && (pad_right == 0) && (pad_bottom == 0) && (pad_left == 0);
     bool          supported_padding = is_same_padding || is_valid_padding;
     return supported_datatype && supported_strides && supported_padding && (depth_multiplier == 1);
 }
References arm_compute::calculate_same_pad(), arm_compute::test::validation::conv_info, Window::DimX, Window::DimY, Window::DimZ, arm_compute::test::validation::input_shape, arm_compute::is_data_type_float(), arm_compute::is_data_type_quantized(), arm_compute::NHWC, PadStrideInfo::pad_bottom(), PadStrideInfo::pad_left(), PadStrideInfo::pad_right(), PadStrideInfo::pad_top(), and arm_compute::U.
Referenced by NEDepthwiseConvolutionLayer3x3Kernel::configure(), NEDepthwiseConvolutionLayer3x3::configure(), and NEDepthwiseConvolutionLayer3x3Kernel::validate().
name()
const char* name () const inline override virtual
Name of the kernel.
Returns
Kernel name
Implements ICPPKernel.
Definition at line 40 of file NEDepthwiseConvolutionLayer3x3Kernel.h.
     {
         return "NEDepthwiseConvolutionLayer3x3Kernel";
     }
operator=() [1/2]
NEDepthwiseConvolutionLayer3x3Kernel& operator= (const NEDepthwiseConvolutionLayer3x3Kernel &) delete
Prevent instances of this class from being copied (As this class contains pointers)
operator=() [2/2]
NEDepthwiseConvolutionLayer3x3Kernel& operator= (NEDepthwiseConvolutionLayer3x3Kernel &&) default
Default move assignment operator.
run()
void run (const Window & window, const ThreadInfo & info) override virtual
Execute the kernel on the passed window.
Warning
If is_parallelisable() returns false then the passed window must be equal to window()
Note
The window has to be a region within the window returned by the window() method
The width of the window has to be a multiple of num_elems_processed_per_iteration().
Parameters
[in] window Region on which to execute the kernel. (Must be a region of the window returned by window())
[in] info Info about executing thread and CPU.
Implements ICPPKernel.
Definition at line 311 of file NEDepthwiseConvolutionLayer3x3Kernel.cpp.
 {
     ARM_COMPUTE_ERROR_ON_UNCONFIGURED_KERNEL(this);
     ARM_COMPUTE_UNUSED(info);
     (_run_optimized) ? run_optimized(window, info) : run_generic(window, info);
 }
References ARM_COMPUTE_ERROR_ON_UNCONFIGURED_KERNEL, ARM_COMPUTE_UNUSED, arm_compute::test::validation::info, and IKernel::window().
validate()
Status validate (const ITensorInfo * input, const ITensorInfo * weights, const ITensorInfo * output, const PadStrideInfo & conv_info, unsigned int depth_multiplier = 1) static
Static function to check if given info will lead to a valid configuration of NEDepthwiseConvolutionLayer3x3Kernel.
Note
Supported data layouts: NCHW and NHWC
Parameters
[in] input Source tensor. DataType supported: QASYMM8/F16/F32.
[in] weights Weights tensor. This is a 3D tensor with dimensions [3, 3, IFM] for NCHW or [IFM, 3, 3] if NHWC data layout. Data type supported: Same as input.
[in] output Destination tensor. Data type supported: Same as input.
[in] conv_info Padding and stride information to use for the convolution.
[in] depth_multiplier (Optional) Multiplier to apply to the input's depth in order to retrieve the output's depth. Defaults to 1.
Returns
a status
Definition at line 300 of file NEDepthwiseConvolutionLayer3x3Kernel.cpp.
 {
     ARM_COMPUTE_RETURN_ERROR_ON_NULLPTR(input, weights, output);
     bool is_optimized = NEDepthwiseConvolutionLayer3x3Kernel::is_optimized_execution_possible(input->tensor_shape(), conv_info, input->data_type(), depth_multiplier, input->data_layout());
     ARM_COMPUTE_RETURN_ON_ERROR(validate_arguments(input, weights, output, conv_info, depth_multiplier, is_optimized));
     ARM_COMPUTE_RETURN_ON_ERROR(validate_and_configure_window(input->clone().get(), weights->clone().get(), output->clone().get(), conv_info, depth_multiplier, is_optimized).first);
     return Status{};
 }
References ARM_COMPUTE_RETURN_ERROR_ON_NULLPTR, ARM_COMPUTE_RETURN_ON_ERROR, ICloneable< T >::clone(), arm_compute::test::validation::conv_info, ITensorInfo::data_layout(), ITensorInfo::data_type(), NEDepthwiseConvolutionLayer3x3Kernel::is_optimized_execution_possible(), ITensorInfo::tensor_shape(), and arm_compute::test::validation::weights.
Referenced by NEDepthwiseConvolutionLayer3x3::validate().
The documentation for this class was generated from the following files:
arm_compute/core/NEON/kernels/NEDepthwiseConvolutionLayer3x3Kernel.h
src/core/NEON/kernels/NEDepthwiseConvolutionLayer3x3Kernel.cpp