Compute Library: NEScale Class Reference
NEScale Class Reference
Basic function to run NEScaleKernel.
#include <NEScale.h>
Public Member Functions
NEScale ()
Constructor.
void configure (ITensor *input, ITensor *output, InterpolationPolicy policy, BorderMode border_mode, PixelValue constant_border_value=PixelValue(), SamplingPolicy sampling_policy=SamplingPolicy::CENTER)
Initialize the function's source, destination, interpolation type and border_mode.
void run () override
Run the kernels contained in the function.
Public Member Functions inherited from IFunction
virtual ~IFunction ()=default
Destructor.
virtual void prepare ()
Prepare the function for executing.
Static Public Member Functions
static Status validate (const ITensorInfo *input, const ITensorInfo *output, InterpolationPolicy policy, BorderMode border_mode, PixelValue constant_border_value=PixelValue(), SamplingPolicy sampling_policy=SamplingPolicy::CENTER)
Static function to check if given info will lead to a valid configuration of NEScale.
Detailed Description
Basic function to run NEScaleKernel.
Definition at line 40 of file NEScale.h.
Constructor & Destructor Documentation
NEScale()
NEScale ()
Constructor.
Initialize NEScale
Definition at line 95 of file NEScale.cpp.
     : _offsets(),
       _dx(),
       _dy(),
       _scale_kernel(),
       _border_handler()
 {
 }
Member Function Documentation
configure()
void configure (ITensor * input, ITensor * output, InterpolationPolicy policy, BorderMode border_mode, PixelValue constant_border_value = PixelValue(), SamplingPolicy sampling_policy = SamplingPolicy::CENTER)
Initialize the function's source, destination, interpolation type and border_mode.
Parameters
[in,out] input Source tensor. Data type supported: U8/S16/F16/F32. (Written to only for border_mode != UNDEFINED)
[out] output Destination tensor. Data type supported: Same as input. All but the lowest two dimensions must be the same size as in the input tensor, i.e. scaling is only performed within the XY-plane.
[in] policy The interpolation type.
[in] border_mode Strategy to use for borders.
[in] constant_border_value (Optional) Constant value to use for borders if border_mode is set to CONSTANT.
[in] sampling_policy (Optional) Sampling policy used by the interpolation. Defaults to SamplingPolicy::CENTER
Definition at line 104 of file NEScale.cpp.
 {
     ARM_COMPUTE_ERROR_ON_NULLPTR(input, output);
     ARM_COMPUTE_ERROR_THROW_ON(NEScale::validate(input->info(), output->info(), policy, border_mode, constant_border_value, sampling_policy));
     // Get data layout and width/height indices
     const DataLayout data_layout = input->info()->data_layout();
     const int        idx_width   = get_data_layout_dimension_index(data_layout, DataLayoutDimension::WIDTH);
     const int        idx_height  = get_data_layout_dimension_index(data_layout, DataLayoutDimension::HEIGHT);
     // Get the tensor shape
     const TensorShape shape(output->info()->dimension(idx_width), output->info()->dimension(idx_height));
     // Compute the ratio between source width/height and destination width/height
     const auto wr = static_cast<float>(input->info()->dimension(idx_width)) / static_cast<float>(output->info()->dimension(idx_width));
     const auto hr = static_cast<float>(input->info()->dimension(idx_height)) / static_cast<float>(output->info()->dimension(idx_height));
     // Get the element size of the input image
     const size_t input_element_size = input->info()->element_size();
     // Area interpolation behaves as Nearest Neighbour in case of up-sampling
     if(policy == InterpolationPolicy::AREA && wr <= 1.f && hr <= 1.f)
     {
         policy = InterpolationPolicy::NEAREST_NEIGHBOR;
     }
     switch(policy)
     {
         case InterpolationPolicy::NEAREST_NEIGHBOR:
         {
             TensorInfo tensor_info_offsets(shape, Format::S32);
             _offsets.allocator()->init(tensor_info_offsets);
             _scale_kernel.configure(input, nullptr, nullptr, &_offsets, output, policy, border_mode, sampling_policy);
             // Allocate once the configure methods have been called
             _offsets.allocator()->allocate();
             // Pre-compute offsets for nearest interpolation
             precompute_dx_dy_offsets(nullptr, nullptr, &_offsets, wr, hr, input_element_size, sampling_policy);
             break;
         }
         case InterpolationPolicy::BILINEAR:
         {
             TensorInfo tensor_info_offsets(shape, Format::S32);
             TensorInfo tensor_info_dxdy(shape, Format::F32);
             _offsets.allocator()->init(tensor_info_offsets);
             _dx.allocator()->init(tensor_info_dxdy);
             _dy.allocator()->init(tensor_info_dxdy);
             _scale_kernel.configure(input, &_dx, &_dy, &_offsets, output, policy, border_mode, sampling_policy);
             // Allocate once the configure methods have been called
             _offsets.allocator()->allocate();
             _dx.allocator()->allocate();
             _dy.allocator()->allocate();
             // Pre-compute dx, dy and offsets for bilinear interpolation
             precompute_dx_dy_offsets(&_dx, &_dy, &_offsets, wr, hr, input_element_size, sampling_policy);
             break;
         }
         case InterpolationPolicy::AREA:
         {
             _scale_kernel.configure(input, nullptr, nullptr, nullptr, output, policy, border_mode);
             break;
         }
         default:
             ARM_COMPUTE_ERROR("Unsupported interpolation mode");
     }
     _border_handler.configure(input, _scale_kernel.border_size(), border_mode, constant_border_value);
 }
References TensorAllocator::allocate(), Tensor::allocator(), arm_compute::AREA, ARM_COMPUTE_ERROR, ARM_COMPUTE_ERROR_ON_NULLPTR, ARM_COMPUTE_ERROR_THROW_ON, arm_compute::BILINEAR, arm_compute::test::validation::border_mode, NEScaleKernel::border_size(), NEFillBorderKernel::configure(), NEScaleKernel::configure(), ITensorInfo::data_layout(), ITensorInfo::dimension(), ITensorInfo::element_size(), arm_compute::F32, arm_compute::get_data_layout_dimension_index(), arm_compute::HEIGHT, ITensor::info(), TensorAllocator::init(), arm_compute::NEAREST_NEIGHBOR, arm_compute::test::validation::policy, arm_compute::S32, arm_compute::test::validation::shape, NEScale::validate(), and arm_compute::WIDTH.
run()
void run () override virtual
Run the kernels contained in the function.
For NEON kernels:
Multi-threading is used for the kernels which are parallelisable.
By default std::thread::hardware_concurrency() threads are used.
Note
CPPScheduler::set_num_threads() can be used to manually set the number of threads
For OpenCL kernels:
All the kernels are enqueued on the queue associated with CLScheduler.
The queue is then flushed.
Note
The function will not block until the kernels are executed. It is the user's responsibility to wait.
Will call prepare() on first run if hasn't been done
Implements IFunction.
Definition at line 220 of file NEScale.cpp.
 {
     NEScheduler::get().schedule(&_border_handler, Window::DimZ);
     NEScheduler::get().schedule(&_scale_kernel, Window::DimY);
 }
References Window::DimY, Window::DimZ, Scheduler::get(), and IScheduler::schedule().
validate()
Status validate (const ITensorInfo * input, const ITensorInfo * output, InterpolationPolicy policy, BorderMode border_mode, PixelValue constant_border_value = PixelValue(), SamplingPolicy sampling_policy = SamplingPolicy::CENTER) static
Static function to check if given info will lead to a valid configuration of NEScale.
Parameters
[in] input Source tensor. Data type supported: U8/S16/F16/F32. (Written to only for border_mode != UNDEFINED)
[in] output Destination tensor. Data type supported: Same as input. All but the lowest two dimensions must be the same size as in the input tensor, i.e. scaling is only performed within the XY-plane.
[in] policy The interpolation type.
[in] border_mode Strategy to use for borders.
[in] constant_border_value (Optional) Constant value to use for borders if border_mode is set to CONSTANT.
[in] sampling_policy (Optional) Sampling policy used by the interpolation. Defaults to SamplingPolicy::CENTER
Returns
a status
Definition at line 178 of file NEScale.cpp.
 {
     ARM_COMPUTE_RETURN_ERROR_ON_NULLPTR(input, output);
     ARM_COMPUTE_RETURN_ERROR_ON(sampling_policy != SamplingPolicy::CENTER && sampling_policy != SamplingPolicy::TOP_LEFT);
     ARM_COMPUTE_UNUSED(border_mode, constant_border_value);
     ITensorInfo *offsets = nullptr;
     ITensorInfo *dx      = nullptr;
     ITensorInfo *dy      = nullptr;
     // Get data layout and width/height indices
     const DataLayout data_layout = input->data_layout();
     const int        idx_width   = get_data_layout_dimension_index(data_layout, DataLayoutDimension::WIDTH);
     const int        idx_height  = get_data_layout_dimension_index(data_layout, DataLayoutDimension::HEIGHT);
     // Get the tensor shape of auxilary buffers
     const TensorShape shape(output->dimension(idx_width), output->dimension(idx_height));
     TensorInfo tensor_info_offsets(shape, Format::S32);
     TensorInfo tensor_info_dx(shape, Format::F32);
     TensorInfo tensor_info_dy(shape, Format::F32);
     switch(policy)
     {
         case InterpolationPolicy::NEAREST_NEIGHBOR:
             offsets = &tensor_info_offsets;
             break;
         case InterpolationPolicy::BILINEAR:
             offsets = &tensor_info_offsets;
             dx      = &tensor_info_dx;
             dy      = &tensor_info_dy;
             break;
         default:
             break;
     }
     ARM_COMPUTE_RETURN_ON_ERROR(NEScaleKernel::validate(input->clone().get(), dx, dy, offsets, output->clone().get(),
                                                         policy, border_mode, sampling_policy));
     return Status{};
 }
References ARM_COMPUTE_RETURN_ERROR_ON, ARM_COMPUTE_RETURN_ERROR_ON_NULLPTR, ARM_COMPUTE_RETURN_ON_ERROR, ARM_COMPUTE_UNUSED, arm_compute::BILINEAR, arm_compute::test::validation::border_mode, arm_compute::CENTER, ICloneable< T >::clone(), ITensorInfo::data_layout(), ITensorInfo::dimension(), arm_compute::F32, arm_compute::get_data_layout_dimension_index(), arm_compute::HEIGHT, arm_compute::NEAREST_NEIGHBOR, arm_compute::test::validation::policy, arm_compute::S32, arm_compute::test::validation::shape, arm_compute::TOP_LEFT, NEScaleKernel::validate(), and arm_compute::WIDTH.
Referenced by NEScale::configure().
The documentation for this class was generated from the following files:
arm_compute/runtime/NEON/functions/NEScale.h
src/runtime/NEON/functions/NEScale.cpp