Compute Library: CLGEMMReshapedConfigurationFactory Class Reference
CLGEMMReshapedConfigurationFactory Class Reference final
Tuner factory class.
#include <CLGEMMReshapedConfiguration.h>
Static Public Member Functions
static std::unique_ptr< ICLGEMMReshapedConfiguration > create ()
Detailed Description
Tuner factory class.
Definition at line 38 of file CLGEMMReshapedConfiguration.h.
Member Function Documentation
create()
static std::unique_ptr<ICLGEMMReshapedConfiguration> create () inline static
Definition at line 41 of file CLGEMMReshapedConfiguration.h.
     {
         GPUTarget arch = get_arch_from_target(CLScheduler::get().target());
         switch(arch)
         {
             case GPUTarget::BIFROST:
                 return support::cpp14::make_unique<CLGEMMReshapedConfigurationBifrost>();
             default:
                 return nullptr;
         }
     }
References arm_compute::BIFROST, CLScheduler::get(), and arm_compute::get_arch_from_target().
Referenced by CLGEMM::configure(), CLGEMMLowpMatrixMultiplyCore::configure(), CLGEMMLowpMatrixMultiplyCore::validate(), and CLGEMM::validate().
The documentation for this class was generated from the following file:
arm_compute/runtime/CL/gemm_reshaped/CLGEMMReshapedConfiguration.h