Compute Library: NEGEMMLowpQuantizeDownInt32ToUint8ScaleByFixedPoint Class Reference
NEGEMMLowpQuantizeDownInt32ToUint8ScaleByFixedPoint Class Reference
Basic function to execute NEGEMMLowpQuantizeDownInt32ToUint8ScaleByFixedPoint on NEON.
#include <NEGEMMLowpOutputStage.h>
Public Member Functions
void configure (const ITensor *input, const ITensor *bias, ITensor *output, int result_fixedpoint_multiplier, int result_shift, int result_offset_after_shift, int min=0, int max=0)
Initialise the kernel's inputs, output.
Public Member Functions inherited from INESimpleFunctionNoBorder
INESimpleFunctionNoBorder ()
Constructor.
void run () override final
Run the kernels contained in the function.
Public Member Functions inherited from IFunction
virtual ~IFunction ()=default
Destructor.
virtual void prepare ()
Prepare the function for executing.
Static Public Member Functions
static Status validate (const ITensorInfo *input, const ITensorInfo *bias, const ITensorInfo *output, int min=0, int max=0)
Static function to check if given info will lead to a valid configuration of NEGEMMLowpQuantizeDownInt32ToUint8ScaleByFixedPoint.
Detailed Description
Basic function to execute NEGEMMLowpQuantizeDownInt32ToUint8ScaleByFixedPoint on NEON.
NEGEMMLowpQuantizeDownInt32ToUint8ScaleByFixedPoint depends on 3 parameters:
result_fixedpoint_multiplier, result_shift, result_offset_after_shift
The final result is:
(FixedPointMul(input[i][k], result_fixedpoint_multiplier) >> result_shift) + result_offset_after_shift
where FixedPointMul(x, y) is the nearest integer to the following mathematical expression, evaluated without overflow or intermediate rounding:
(x * y) / 2^31
For more information: https://github.com/google/gemmlowp/blob/master/public/output_stages.h#L68
In case the bias tensor is provided, the final result is:
((FixedPointMul(input[i][k] + bias[k], result_fixedpoint_multiplier)) >> result_shift) + result_offset_after_shift
This function calls the following NEON kernels:
NEGEMMLowpQuantizeDownInt32ToUint8ScaleByFixedPointKernel
Note
The function accepts also 2 optional input arguments (min and max) which can be used to implement "rectified linear unit" activation functions after the result is shifted right by result_shift
Definition at line 119 of file NEGEMMLowpOutputStage.h.
Member Function Documentation
configure()
void configure (const ITensor * input, const ITensor * bias, ITensor * output, int result_fixedpoint_multiplier, int result_shift, int result_offset_after_shift, int min = 0, int max = 0)
Initialise the kernel's inputs, output.
Parameters
[in] input Input tensor. Data type supported: S32
[in] bias Biases tensor. Only shared biases supported and it can be a nullptr if the biases addition is not required. Biases are 1D tensor with dimensions [OFM]. Data type supported: Same as input.
[out] output Output tensor. Data type supported: Data type supported: QASYMM8
[in] result_fixedpoint_multiplier Fixed point value to be multiplied to each element of the input matrix when once the result_offset has been add
[in] result_shift Number of bits to shift right the result after the fixed point multiplication
[in] result_offset_after_shift Offset to be applied to result before converting it back to QASYMM8
[in] min (Optional) Min value used to saturate down the output result before converting back to QASYMM8
[in] max (Optional) Max value used to saturate up the output result before converting back to QASYMM8, Along with min, this value can be used to implement "rectified linear unit" activation functions
Definition at line 45 of file NEGEMMLowpOutputStage.cpp.
 {
     auto k = arm_compute::support::cpp14::make_unique<NEGEMMLowpQuantizeDownInt32ToUint8ScaleByFixedPointKernel>();
     k->configure(input, bias, output, result_fixedpoint_multiplier, result_shift, result_offset_after_shift, min, max);
     _kernel = std::move(k);
 }
References arm_compute::test::validation::bias.
Referenced by NEFullyConnectedLayer::configure(), and NEGEMMConvolutionLayer::configure().
validate()
Status validate (const ITensorInfo * input, const ITensorInfo * bias, const ITensorInfo * output, int min = 0, int max = 0) static
Static function to check if given info will lead to a valid configuration of NEGEMMLowpQuantizeDownInt32ToUint8ScaleByFixedPoint.
Parameters
[in] input Input tensor. It is the output of NEGEMMLowpMatrixMultiplyCore function. Data type supported: S32
[in] bias Biases tensor. Only shared biases supported and it can be a nullptr if the addition of biases is not required. Biases are 1D tensor with dimensions [OFM]. Data type supported: Same as input.
[in] output Output tensor. Data type supported: Data type supported: QASYMM8
[in] min (Optional) Min value used to saturate down the output result before converting back to QASYMM8
[in] max (Optional) Max value used to saturate up the output result before converting back to QASYMM8, Along with min, this value can be used to implement "rectified linear unit" activation functions
Returns
a status
Definition at line 53 of file NEGEMMLowpOutputStage.cpp.
 {
     return NEGEMMLowpQuantizeDownInt32ToUint8ScaleByFixedPointKernel::validate(input, bias, output, min, max);
 }
References arm_compute::test::validation::bias, and NEGEMMLowpQuantizeDownInt32ToUint8ScaleByFixedPointKernel::validate().
Referenced by NEFullyConnectedLayer::validate(), and NEGEMMConvolutionLayer::validate().
The documentation for this class was generated from the following files:
arm_compute/runtime/NEON/functions/NEGEMMLowpOutputStage.h
src/runtime/NEON/functions/NEGEMMLowpOutputStage.cpp