Compute Library: NEDepthwiseConvolutionLayer3x3 Class Reference
NEDepthwiseConvolutionLayer3x3 Class Reference
Basic function to execute a depthwise convolution for kernel size 3x3xC.
#include <NEDepthwiseConvolutionLayer.h>
Public Member Functions
NEDepthwiseConvolutionLayer3x3 ()
Default constructor.
void configure (ITensor *input, const ITensor *weights, const ITensor *biases, ITensor *output, const PadStrideInfo &conv_info, unsigned int depth_multiplier=1, const ActivationLayerInfo &act_info=ActivationLayerInfo())
Initialize the function's source, destination, kernels and border_size.
void run () override
Run the kernels contained in the function.
Public Member Functions inherited from IFunction
virtual ~IFunction ()=default
Destructor.
virtual void prepare ()
Prepare the function for executing.
Static Public Member Functions
static Status validate (const ITensorInfo *input, const ITensorInfo *weights, const ITensorInfo *biases, const ITensorInfo *output, const PadStrideInfo &conv_info, unsigned int depth_multiplier=1, const ActivationLayerInfo &act_info=ActivationLayerInfo())
Static function to check if given info will lead to a valid configuration of NEDepthwiseConvolutionLayer3x3.
Detailed Description
Basic function to execute a depthwise convolution for kernel size 3x3xC.
This function calls the following NEON kernels:
NEDepthwiseConvolutionLayer3x3
NEFillBorderKernel (if pad_x or pad_y > 0)
Definition at line 52 of file NEDepthwiseConvolutionLayer.h.
Constructor & Destructor Documentation
NEDepthwiseConvolutionLayer3x3()
NEDepthwiseConvolutionLayer3x3 ()
Default constructor.
Definition at line 38 of file NEDepthwiseConvolutionLayer.cpp.
     : _dwc_kernel(), _output_stage_kernel(), _border_handler(), _permute_input(), _permute_weights(), _permute_output(), _activationlayer_function(), _accumulator(), _permuted_input(),
       _permuted_weights(), _permuted_output(), _has_bias(false), _is_quantized(false), _is_optimized(false), _are_weights_reshaped(false), _is_nchw(true), _is_first_run(true), _permute(false),
       _is_activationlayer_enabled(false)
 {
 }
Member Function Documentation
configure()
void configure (ITensor * input, const ITensor * weights, const ITensor * biases, ITensor * output, const PadStrideInfo & conv_info, unsigned int depth_multiplier = 1, const ActivationLayerInfo & act_info = ActivationLayerInfo())
Initialize the function's source, destination, kernels and border_size.
Parameters
[in,out] input Source tensor. Data type supported: QASYMM8/F16/F32. (Written to only for border filling).
[in] weights Weights tensor. These are 3D tensors with shape [3, 3, IFM]. Data type supported: Same as input.
[in] biases (Optional) Biases tensor. A 1D tensor with shape [IFM]. Must be nullptr if not needed. Data type supported: Same as input.
[out] output Destination tensor. Data type supported: same as input.
[in] conv_info Padding and stride information to use for the convolution.
[in] depth_multiplier (Optional) Multiplier to apply to the input's depth in order to retrieve the output's depth. Defaults to 1.
[in] act_info (Optional) Activation layer information in case of a fused activation.
Definition at line 45 of file NEDepthwiseConvolutionLayer.cpp.
 {
     ARM_COMPUTE_ERROR_ON_DATA_TYPE_CHANNEL_NOT_IN(input, 1, DataType::QASYMM8, DataType::F16, DataType::F32);
     ARM_COMPUTE_ERROR_ON_MISMATCHING_DATA_TYPES(input, weights);
     PixelValue zero_value(0.f);
     _is_quantized = is_data_type_quantized_asymmetric(input->info()->data_type());
     _has_bias     = biases != nullptr;
     _is_optimized = NEDepthwiseConvolutionLayer3x3Kernel::is_optimized_execution_possible(input->info()->tensor_shape(),
                                                                                           conv_info,
                                                                                           input->info()->data_type(),
                                                                                           depth_multiplier,
                                                                                           input->info()->data_layout());
     _are_weights_reshaped = false;
     _is_nchw              = input->info()->data_layout() == DataLayout::NCHW;
     _permute              = _is_optimized == _is_nchw;
     // Initialize the intermediate accumulator tensor in case of quantized input
     if(_is_quantized)
     {
         TensorShape accum_shape  = output->info()->tensor_shape();
         DataLayout  accum_layout = output->info()->data_layout();
         if(!_is_optimized && !_is_nchw)
         {
             permute(accum_shape, PermutationVector(1U, 2U, 0U));
             accum_layout = DataLayout::NCHW;
         }
         _accumulator.allocator()->init(TensorInfo(accum_shape, 1, DataType::S32, output->info()->quantization_info()));
         _accumulator.info()->set_data_layout(accum_layout);
         zero_value = PixelValue(static_cast<uint32_t>(input->info()->quantization_info().offset));
     }
     if(_is_optimized)
     {
         ITensor *optimized_output = (_is_quantized) ? &_accumulator : output;
         if(_is_nchw)
         {
             // Configure the function to transform the input tensor from NCHW -> NHWC
             _permute_input.configure(input, &_permuted_input, PermutationVector(2U, 0U, 1U));
             _permuted_input.info()->set_data_layout(DataLayout::NHWC);
             // Configure the function to transform the weights tensor from IHW -> HWI
             _permute_weights.configure(weights, &_permuted_weights, PermutationVector(2U, 0U, 1U));
             _permuted_weights.info()->set_data_layout(DataLayout::NHWC);
             // Configure optimized depthwise
             _dwc_kernel.configure(&_permuted_input, &_permuted_weights, &_permuted_output, conv_info, depth_multiplier, DataLayout::NHWC);
             // Configure the function to transform the convoluted output to ACL's native ordering format NCHW
             _permuted_output.info()->set_data_layout(DataLayout::NHWC);
             _permute_output.configure(&_permuted_output, optimized_output, PermutationVector(1U, 2U, 0U));
             // Allocate tensors
             _permuted_input.allocator()->allocate();
             _permuted_weights.allocator()->allocate();
             _permuted_output.allocator()->allocate();
         }
         else
         {
             _dwc_kernel.configure(input, weights, optimized_output, conv_info, depth_multiplier, DataLayout::NHWC);
         }
     }
     else
     {
         if(!_is_nchw)
         {
             // Configure the function to transform the input tensor from NHWC -> NCHW
             _permute_input.configure(input, &_permuted_input, PermutationVector(1U, 2U, 0U));
             _permuted_input.info()->set_data_layout(DataLayout::NCHW);
             // Configure the function to transform the weights tensor from HWI -> IHW
             _permute_weights.configure(weights, &_permuted_weights, PermutationVector(1U, 2U, 0U));
             _permuted_weights.info()->set_data_layout(DataLayout::NCHW);
             // Configure optimized depthwise
             _dwc_kernel.configure(&_permuted_input, &_permuted_weights, (_is_quantized) ? &_accumulator : &_permuted_output, conv_info, depth_multiplier);
             // Configure border handler
             _border_handler.configure(&_permuted_input, _dwc_kernel.border_size(), BorderMode::CONSTANT, zero_value);
             // Allocate tensors
             _permuted_input.allocator()->allocate();
             _permuted_weights.allocator()->allocate();
         }
         else
         {
             // Configure depthwise convolution kernel
             _dwc_kernel.configure(input, weights, (_is_quantized) ? &_accumulator : output, conv_info, depth_multiplier);
             // Configure border handler
             _border_handler.configure(input, _dwc_kernel.border_size(), BorderMode::CONSTANT, zero_value);
         }
     }
     // Configure biases accumulation
     if(_is_quantized)
     {
         const QuantizationInfo output_quant_info = (output->info()->total_size() == 0) ? input->info()->quantization_info() : output->info()->quantization_info();
         float multiplier = input->info()->quantization_info().scale * weights->info()->quantization_info().scale / output_quant_info.scale;
         int   output_multiplier, output_shift;
         quantization::calculate_quantized_multiplier_less_than_one(multiplier, &output_multiplier, &output_shift);
         _output_stage_kernel.configure(&_accumulator, biases, (_is_nchw || _is_optimized) ? output : &_permuted_output, output_multiplier, output_shift, output_quant_info.offset);
         _accumulator.allocator()->allocate();
     }
     else if(_has_bias)
     {
         _output_stage_kernel.configure((_is_nchw || _is_optimized) ? output : &_permuted_output, biases);
     }
     if(!_is_optimized && !_is_nchw)
     {
         // Configure the function to transform the convoluted output to NHWC
         _permute_output.configure(&_permuted_output, output, PermutationVector(2U, 0U, 1U));
         _permuted_output.allocator()->allocate();
     }
     //Configure Activation Layer
     _is_activationlayer_enabled = act_info.enabled();
     if(_is_activationlayer_enabled)
     {
         _activationlayer_function.configure(output, nullptr, act_info);
     }
 }
References arm_compute::test::validation::act_info, TensorAllocator::allocate(), Tensor::allocator(), ARM_COMPUTE_ERROR_ON_DATA_TYPE_CHANNEL_NOT_IN, ARM_COMPUTE_ERROR_ON_MISMATCHING_DATA_TYPES, NEDepthwiseConvolutionLayer3x3Kernel::border_size(), arm_compute::quantization::calculate_quantized_multiplier_less_than_one(), NEPermute::configure(), NEActivationLayer::configure(), NEDepthwiseConvolutionLayer3x3Kernel::configure(), NEDirectConvolutionLayerOutputStageKernel::configure(), NEFillBorderKernel::configure(), arm_compute::CONSTANT, arm_compute::test::validation::conv_info, ITensorInfo::data_layout(), ITensorInfo::data_type(), arm_compute::F16, arm_compute::F32, ITensor::info(), Tensor::info(), CLTensor::info(), TensorAllocator::init(), arm_compute::is_data_type_quantized_asymmetric(), NEDepthwiseConvolutionLayer3x3Kernel::is_optimized_execution_possible(), arm_compute::NCHW, arm_compute::NHWC, QuantizationInfo::offset, arm_compute::permute(), arm_compute::QASYMM8, ITensorInfo::quantization_info(), TensorInfo::quantization_info(), arm_compute::S32, QuantizationInfo::scale, ITensorInfo::set_data_layout(), ITensorInfo::tensor_shape(), ITensorInfo::total_size(), arm_compute::U, and arm_compute::test::validation::weights.
run()
void run () override virtual
Run the kernels contained in the function.
For NEON kernels:
Multi-threading is used for the kernels which are parallelisable.
By default std::thread::hardware_concurrency() threads are used.
Note
CPPScheduler::set_num_threads() can be used to manually set the number of threads
For OpenCL kernels:
All the kernels are enqueued on the queue associated with CLScheduler.
The queue is then flushed.
Note
The function will not block until the kernels are executed. It is the user's responsibility to wait.
Will call prepare() on first run if hasn't been done
Implements IFunction.
Definition at line 206 of file NEDepthwiseConvolutionLayer.cpp.
 {
     if(_is_first_run && _is_optimized)
     {
         _is_first_run = false;
         // Create convolver (deferred)
         _dwc_kernel.generate_convolver();
     }
     // Permute weights
     if(_permute)
     {
         if(!_are_weights_reshaped)
         {
             _are_weights_reshaped = true;
             _permute_weights.run();
         }
         _permute_input.run();
     }
     // Handle input
     if(!_is_optimized)
     {
         // Fill border
         NEScheduler::get().schedule(&_border_handler, Window::DimX);
     }
     // Execute depthwise convolution
     NEScheduler::get().schedule(&_dwc_kernel, Window::DimX);
     // Permute output
     if(_is_optimized && _is_nchw)
     {
         _permute_output.run();
     }
     // Add biases
     if(_has_bias || _is_quantized)
     {
         NEScheduler::get().schedule(&_output_stage_kernel, Window::DimX);
     }
     // Permute output
     if(!_is_optimized && !_is_nchw)
     {
         _permute_output.run();
     }
     if(_is_activationlayer_enabled)
     {
         _activationlayer_function.run();
     }
 }
References Window::DimX, NEDepthwiseConvolutionLayer3x3Kernel::generate_convolver(), Scheduler::get(), INESimpleFunctionNoBorder::run(), and IScheduler::schedule().
validate()
Status validate (const ITensorInfo * input, const ITensorInfo * weights, const ITensorInfo * biases, const ITensorInfo * output, const PadStrideInfo & conv_info, unsigned int depth_multiplier = 1, const ActivationLayerInfo & act_info = ActivationLayerInfo()) static
Static function to check if given info will lead to a valid configuration of NEDepthwiseConvolutionLayer3x3.
Parameters
[in] input Source tensor. Data type supported: QASYMM8/F16/F32. (Written to only for border filling).
[in] weights Weights tensor. These are 3D tensors with shape [3, 3, IFM]. Data type supported: Same as input.
[in] biases (Optional) Biases tensor. A 1D tensor with shape [IFM]. Must be nullptr if not needed. Data type supported: Same as input.
[in] output Destination tensor. Data type supported: same as input.
[in] conv_info Padding and stride information to use for the convolution.
[in] depth_multiplier (Optional) Multiplier to apply to the input's depth in order to retrieve the output's depth. Defaults to 1.
[in] act_info (Optional) Activation layer information in case of a fused activation.
Returns
a status
Definition at line 174 of file NEDepthwiseConvolutionLayer.cpp.
 {
     ARM_COMPUTE_RETURN_ERROR_ON_NULLPTR(input, weights, output);
     ARM_COMPUTE_RETURN_ERROR_ON(input->data_layout() == DataLayout::UNKNOWN);
     if(biases != nullptr)
     {
         const unsigned int channel_idx = get_data_layout_dimension_index(input->data_layout(), DataLayoutDimension::CHANNEL);
         ARM_COMPUTE_RETURN_ERROR_ON(biases->num_dimensions() > 1);
         ARM_COMPUTE_RETURN_ERROR_ON(biases->dimension(0) != weights->dimension(channel_idx));
     }
     const bool is_quantized = is_data_type_quantized_asymmetric(input->data_type());
     TensorInfo accumulator  = TensorInfo(output->clone()->set_is_resizable(true).reset_padding().set_data_type(DataType::S32));
     ARM_COMPUTE_RETURN_ON_ERROR(NEDepthwiseConvolutionLayer3x3Kernel::validate(input, weights, is_quantized ? &accumulator : output, conv_info, depth_multiplier));
     if(is_quantized)
     {
         ARM_COMPUTE_RETURN_ON_ERROR(NEDirectConvolutionLayerOutputStageKernel::validate(&accumulator, biases, output));
     }
     //Validate Activation Layer
     if(act_info.enabled())
     {
         ARM_COMPUTE_RETURN_ON_ERROR(NEActivationLayer::validate(output, nullptr, act_info));
     }
     return Status{};
 }
References arm_compute::test::validation::act_info, ARM_COMPUTE_RETURN_ERROR_ON, ARM_COMPUTE_RETURN_ERROR_ON_NULLPTR, ARM_COMPUTE_RETURN_ON_ERROR, arm_compute::CHANNEL, ICloneable< T >::clone(), arm_compute::test::validation::conv_info, ITensorInfo::data_layout(), ITensorInfo::data_type(), ITensorInfo::dimension(), arm_compute::get_data_layout_dimension_index(), arm_compute::is_data_type_quantized_asymmetric(), ITensorInfo::num_dimensions(), arm_compute::S32, arm_compute::UNKNOWN, NEActivationLayer::validate(), NEDirectConvolutionLayerOutputStageKernel::validate(), NEDepthwiseConvolutionLayer3x3Kernel::validate(), and arm_compute::test::validation::weights.
The documentation for this class was generated from the following files:
arm_compute/runtime/NEON/functions/NEDepthwiseConvolutionLayer.h
src/runtime/NEON/functions/NEDepthwiseConvolutionLayer.cpp