Compute Library: NESobel7x7HorKernel Class Reference
NESobel7x7HorKernel Class Reference
Interface for the kernel to run the horizontal pass of 7x7 Sobel filter on a tensor.
#include <NESobel7x7Kernel.h>
Public Member Functions
const char * name () const override
Name of the kernel.
NESobel7x7HorKernel ()
Default constructor.
NESobel7x7HorKernel (const NESobel7x7HorKernel &)=delete
Prevent instances of this class from being copied (As this class contains pointers)
NESobel7x7HorKernel & operator= (const NESobel7x7HorKernel &)=delete
Prevent instances of this class from being copied (As this class contains pointers)
NESobel7x7HorKernel (NESobel7x7HorKernel &&)=default
Allow instances of this class to be moved.
NESobel7x7HorKernel & operator= (NESobel7x7HorKernel &&)=default
Allow instances of this class to be moved.
~NESobel7x7HorKernel ()=default
Default destructor.
void configure (const ITensor *input, ITensor *output_x, ITensor *output_y, bool border_undefined)
Initialise the kernel's source, destination and border mode.
void run (const Window &window, const ThreadInfo &info) override
Execute the kernel on the passed window.
BorderSize border_size () const override
The size of the border for that kernel.
Public Member Functions inherited from ICPPKernel
virtual ~ICPPKernel ()=default
Default destructor.
Public Member Functions inherited from IKernel
IKernel ()
Constructor.
virtual ~IKernel ()=default
Destructor.
virtual bool is_parallelisable () const
Indicates whether or not the kernel is parallelisable.
const Window & window () const
The maximum window the kernel can be executed on.
Detailed Description
Interface for the kernel to run the horizontal pass of 7x7 Sobel filter on a tensor.
Definition at line 36 of file NESobel7x7Kernel.h.
Constructor & Destructor Documentation
NESobel7x7HorKernel() [1/3]
NESobel7x7HorKernel ()
Default constructor.
Definition at line 143 of file NESobel7x7Kernel.cpp.
     : _input(nullptr), _output_x(nullptr), _output_y(nullptr), _run_sobel_x(false), _run_sobel_y(false), _border_size(0)
 {
 }
NESobel7x7HorKernel() [2/3]
NESobel7x7HorKernel (const NESobel7x7HorKernel &) delete
Prevent instances of this class from being copied (As this class contains pointers)
NESobel7x7HorKernel() [3/3]
NESobel7x7HorKernel (NESobel7x7HorKernel &&) default
Allow instances of this class to be moved.
~NESobel7x7HorKernel()
~NESobel7x7HorKernel () default
Default destructor.
Member Function Documentation
border_size()
BorderSize border_size () const override virtual
The size of the border for that kernel.
Returns
The width in number of elements of the border.
Reimplemented from IKernel.
Definition at line 148 of file NESobel7x7Kernel.cpp.
 {
     return _border_size;
 }
Referenced by NESobel7x7HorKernel::configure(), and NESobel7x7::configure().
configure()
void configure (const ITensor * input, ITensor * output_x, ITensor * output_y, bool border_undefined)
Initialise the kernel's source, destination and border mode.
Note
At least one of output_x or output_y must be set.
Parameters
[in] input Source tensor. Data type supported: U8.
[out] output_x (Optional) Destination tensor for the X gradient. Data type supported: S32.
[out] output_y (Optional) Destination tensor for the Y gradient. Data type supported: S32.
[in] border_undefined True if the border mode is undefined. False if it's replicate or constant.
Definition at line 153 of file NESobel7x7Kernel.cpp.
 {
     ARM_COMPUTE_ERROR_ON_FORMAT_NOT_IN(input, Format::U8);
     ARM_COMPUTE_ERROR_ON((output_x == nullptr) && (output_y == nullptr));
     _run_sobel_x = output_x != nullptr;
     _run_sobel_y = output_y != nullptr;
     if(_run_sobel_x)
     {
         ARM_COMPUTE_ERROR_ON_FORMAT_NOT_IN(output_x, Format::S32);
     }
     if(_run_sobel_y)
     {
         ARM_COMPUTE_ERROR_ON_FORMAT_NOT_IN(output_y, Format::S32);
     }
     _input       = input;
     _output_x    = output_x;
     _output_y    = output_y;
     _border_size = BorderSize(border_undefined ? 0 : 3, 3);
     // Configure kernel window
     constexpr unsigned int num_elems_processed_per_iteration = 8;
     constexpr unsigned int num_elems_read_per_iteration      = 16;
     constexpr unsigned int num_elems_written_per_iteration   = 8;
     Window                 win = calculate_max_window_horizontal(*input->info(), Steps(num_elems_processed_per_iteration), border_undefined, border_size());
     AccessWindowHorizontal output_x_access(output_x == nullptr ? nullptr : output_x->info(), 0, num_elems_written_per_iteration);
     AccessWindowHorizontal output_y_access(output_y == nullptr ? nullptr : output_y->info(), 0, num_elems_written_per_iteration);
     update_window_and_padding(win,
                               AccessWindowHorizontal(input->info(), -border_size().left, num_elems_read_per_iteration),
                               output_x_access,
                               output_y_access);
     output_x_access.set_valid_region(win, input->info()->valid_region(), border_undefined, border_size());
     output_y_access.set_valid_region(win, input->info()->valid_region(), border_undefined, border_size());
     INEKernel::configure(win);
 }
References ARM_COMPUTE_ERROR_ON, ARM_COMPUTE_ERROR_ON_FORMAT_NOT_IN, NESobel7x7HorKernel::border_size(), arm_compute::calculate_max_window_horizontal(), ITensor::info(), BorderSize::left, arm_compute::S32, arm_compute::U8, arm_compute::update_window_and_padding(), and ITensorInfo::valid_region().
Referenced by NESobel7x7::configure().
name()
const char* name () const inline override virtual
Name of the kernel.
Returns
Kernel name
Implements ICPPKernel.
Definition at line 39 of file NESobel7x7Kernel.h.
     {
         return "NESobel7x7HorKernel";
     }
operator=() [1/2]
NESobel7x7HorKernel& operator= (const NESobel7x7HorKernel &) delete
Prevent instances of this class from being copied (As this class contains pointers)
operator=() [2/2]
NESobel7x7HorKernel& operator= (NESobel7x7HorKernel &&) default
Allow instances of this class to be moved.
run()
void run (const Window & window, const ThreadInfo & info) override virtual
Execute the kernel on the passed window.
Warning
If is_parallelisable() returns false then the passed window must be equal to window()
Note
The window has to be a region within the window returned by the window() method
The width of the window has to be a multiple of num_elems_processed_per_iteration().
Parameters
[in] window Region on which to execute the kernel. (Must be a region of the window returned by window())
[in] info Info about executing thread and CPU.
Implements ICPPKernel.
Definition at line 196 of file NESobel7x7Kernel.cpp.
 {
     ARM_COMPUTE_UNUSED(info);
     ARM_COMPUTE_ERROR_ON_UNCONFIGURED_KERNEL(this);
     ARM_COMPUTE_ERROR_ON_INVALID_SUBWINDOW(INEKernel::window(), window);
     Iterator input(_input, window);
     Iterator output_x;
     Iterator output_y;
     if(_run_sobel_x)
     {
         output_x = Iterator(_output_x, window);
     }
     if(_run_sobel_y)
     {
         output_y = Iterator(_output_y, window);
     }
     if(_run_sobel_y && _run_sobel_x)
     {
         execute_window_loop(window, [&](const Coordinates & id)
         {
             const uint8x16_t data = vld1q_u8(input.ptr() - 3);
             const uint16x8_t tmp_low_u16  = vmovl_u8(vget_low_u8(data));
             const uint16x8_t tmp_high_u16 = vmovl_u8(vget_high_u8(data));
             const int32x4x4_t data_s32 =
             {
                 {
                     vreinterpretq_s32_u32(vmovl_u16(vget_low_u16(tmp_low_u16))),
                     vreinterpretq_s32_u32(vmovl_u16(vget_high_u16(tmp_low_u16))),
                     vreinterpretq_s32_u32(vmovl_u16(vget_low_u16(tmp_high_u16))),
                     vreinterpretq_s32_u32(vmovl_u16(vget_high_u16(tmp_high_u16)))
                 }
             };
             const int32x4x2_t out_y = compute_hor_sobel_y(data_s32);
             vst1q_s32(reinterpret_cast<int32_t *>(output_y.ptr()), out_y.val[0]);
             vst1q_s32(reinterpret_cast<int32_t *>(output_y.ptr()) + 4, out_y.val[1]);
             const int32x4x2_t out_x = compute_hor_sobel_x(data_s32);
             vst1q_s32(reinterpret_cast<int32_t *>(output_x.ptr()), out_x.val[0]);
             vst1q_s32(reinterpret_cast<int32_t *>(output_x.ptr()) + 4, out_x.val[1]);
         },
         input, output_x, output_y);
     }
     else if(_run_sobel_x)
     {
         execute_window_loop(window, [&](const Coordinates & id)
         {
             const uint8x16_t data = vld1q_u8(input.ptr() - 3);
             const uint16x8_t tmp_low_u16  = vmovl_u8(vget_low_u8(data));
             const uint16x8_t tmp_high_u16 = vmovl_u8(vget_high_u8(data));
             const int32x4x4_t data_s32 =
             {
                 {
                     vreinterpretq_s32_u32(vmovl_u16(vget_low_u16(tmp_low_u16))),
                     vreinterpretq_s32_u32(vmovl_u16(vget_high_u16(tmp_low_u16))),
                     vreinterpretq_s32_u32(vmovl_u16(vget_low_u16(tmp_high_u16))),
                     vreinterpretq_s32_u32(vmovl_u16(vget_high_u16(tmp_high_u16)))
                 }
             };
             const int32x4x2_t out = compute_hor_sobel_x(data_s32);
             vst1q_s32(reinterpret_cast<int32_t *>(output_x.ptr()), out.val[0]);
             vst1q_s32(reinterpret_cast<int32_t *>(output_x.ptr()) + 4, out.val[1]);
         },
         input, output_x);
     }
     else if(_run_sobel_y)
     {
         execute_window_loop(window, [&](const Coordinates & id)
         {
             const uint8x16_t data = vld1q_u8(input.ptr() - 3);
             const uint16x8_t tmp_low_u16  = vmovl_u8(vget_low_u8(data));
             const uint16x8_t tmp_high_u16 = vmovl_u8(vget_high_u8(data));
             const int32x4x4_t data_s32 =
             {
                 {
                     vreinterpretq_s32_u32(vmovl_u16(vget_low_u16(tmp_low_u16))),
                     vreinterpretq_s32_u32(vmovl_u16(vget_high_u16(tmp_low_u16))),
                     vreinterpretq_s32_u32(vmovl_u16(vget_low_u16(tmp_high_u16))),
                     vreinterpretq_s32_u32(vmovl_u16(vget_high_u16(tmp_high_u16)))
                 }
             };
             const int32x4x2_t out = compute_hor_sobel_y(data_s32);
             vst1q_s32(reinterpret_cast<int32_t *>(output_y.ptr()), out.val[0]);
             vst1q_s32(reinterpret_cast<int32_t *>(output_y.ptr()) + 4, out.val[1]);
         },
         input, output_y);
     }
 }
References ARM_COMPUTE_ERROR_ON_INVALID_SUBWINDOW, ARM_COMPUTE_ERROR_ON_UNCONFIGURED_KERNEL, ARM_COMPUTE_UNUSED, arm_compute::execute_window_loop(), arm_compute::test::validation::info, Iterator::ptr(), and IKernel::window().
The documentation for this class was generated from the following files:
arm_compute/core/NEON/kernels/NESobel7x7Kernel.h
src/core/NEON/kernels/NESobel7x7Kernel.cpp