Compute Library: GCMemory Class Reference
GCMemory Class Reference
GLES implementation of memory object.
#include <GCMemory.h>
Public Member Functions
GCMemory ()
Default Constructor.
GCMemory (std::shared_ptr< IGCMemoryRegion > memory)
Default Constructor.
GCMemory (IGCMemoryRegion *memory)
Default Constructor.
GCMemory (const GCMemory &)=default
Allow instances of this class to be copied.
GCMemory & operator= (const GCMemory &)=default
Allow instances of this class to be copy assigned.
GCMemory (GCMemory &&) noexcept=default
Allow instances of this class to be moved.
GCMemory & operator= (GCMemory &&) noexcept=default
Allow instances of this class to be move assigned.
IGCMemoryRegion * gc_region ()
GLES Region accessor.
IGCMemoryRegion * gc_region () const
GLES Region accessor.
IMemoryRegion * region () final
Region accessor.
IMemoryRegion * region () const final
Region accessor.
void set_region (IMemoryRegion *region) final
Sets a memory region.
void set_owned_region (std::unique_ptr< IMemoryRegion > region) final
Sets a memory region.
Public Member Functions inherited from IMemory
virtual ~IMemory ()=default
Virtual default destructor.
Detailed Description
GLES implementation of memory object.
Definition at line 37 of file GCMemory.h.
Constructor & Destructor Documentation
GCMemory() [1/5]
GCMemory ()
Default Constructor.
Definition at line 31 of file GCMemory.cpp.
     : _region(nullptr), _region_owned(nullptr)
 {
 }
GCMemory() [2/5]
GCMemory (std::shared_ptr< IGCMemoryRegion > memory)
Default Constructor.
Parameters
[in] memory Memory to be imported
Definition at line 36 of file GCMemory.cpp.
     : _region(nullptr), _region_owned(std::move(memory))
 {
     _region_owned = memory;
     _region       = _region_owned.get();
 }
GCMemory() [3/5]
GCMemory (IGCMemoryRegion * memory)
Default Constructor.
Note
Ownership of the memory is not transferred to this object. Thus management (allocate/free) should be done by the client.
Parameters
[in] memory Memory to be imported
Definition at line 43 of file GCMemory.cpp.
     : _region(memory), _region_owned(nullptr)
 {
     _region = memory;
 }
GCMemory() [4/5]
GCMemory (const GCMemory &) default
Allow instances of this class to be copied.
GCMemory() [5/5]
GCMemory (GCMemory &&) default noexcept
Allow instances of this class to be moved.
Member Function Documentation
gc_region() [1/2]
IGCMemoryRegion * gc_region ()
GLES Region accessor.
Returns
Memory region
Definition at line 49 of file GCMemory.cpp.
 {
     return _region;
 }
Referenced by GCTensorAllocator::get_gl_ssbo_name(), GCTensorAllocator::map(), GCTensorAllocator::set_associated_memory_group(), GCMemory::set_region(), and GCTensorAllocator::unmap().
gc_region() [2/2]
IGCMemoryRegion * gc_region () const
GLES Region accessor.
Returns
Memory region
Definition at line 54 of file GCMemory.cpp.
 {
     return _region;
 }
operator=() [1/2]
GCMemory& operator= (const GCMemory &) default
Allow instances of this class to be copy assigned.
operator=() [2/2]
GCMemory& operator= (GCMemory &&) default noexcept
Allow instances of this class to be move assigned.
region() [1/2]
IMemoryRegion * region () final virtual
Region accessor.
Returns
Memory region
Implements IMemory.
Definition at line 59 of file GCMemory.cpp.
 {
     return _region;
 }
Referenced by GCTensorAllocator::get_gl_ssbo_name(), GCTensorAllocator::map(), GCTensorAllocator::set_associated_memory_group(), GCMemory::set_owned_region(), GCMemory::set_region(), and GCTensorAllocator::unmap().
region() [2/2]
IMemoryRegion * region () const final virtual
Region accessor.
Returns
Memory region
Implements IMemory.
Definition at line 64 of file GCMemory.cpp.
 {
     return _region;
 }
set_owned_region()
void set_owned_region (std::unique_ptr< IMemoryRegion > region) final virtual
Sets a memory region.
Warning
Ownership of the memory region is transfered along
Parameters
region Memory region
Implements IMemory.
Definition at line 76 of file GCMemory.cpp.
 {
     _region_owned = utils::cast::polymorphic_downcast_unique_ptr<IGCMemoryRegion>(std::move(region));
     _region       = _region_owned.get();
 }
References GCMemory::region().
Referenced by GCTensorAllocator::allocate().
set_region()
void set_region (IMemoryRegion * region) final virtual
Sets a memory region.
Warning
Ownership of the memory region remains to the caller
Parameters
region Memory region
Implements IMemory.
Definition at line 69 of file GCMemory.cpp.
 {
     auto gc_region = utils::cast::polymorphic_downcast<IGCMemoryRegion *>(region);
     _region_owned  = nullptr;
     _region        = gc_region;
 }
References GCMemory::gc_region(), and GCMemory::region().
Referenced by GCTensorAllocator::free().
The documentation for this class was generated from the following files:
arm_compute/runtime/GLES_COMPUTE/GCMemory.h
src/runtime/GLES_COMPUTE/GCMemory.cpp