Compute Library: CPPTopKVKernel Class Reference
CPPTopKVKernel Class Reference
CPP kernel to perform tensor TopKV operation.
#include <CPPTopKVKernel.h>
Public Member Functions
const char * name () const override
Name of the kernel.
CPPTopKVKernel ()
Default constructor.
CPPTopKVKernel (const CPPTopKVKernel &)=delete
Prevent instances of this class from being copied (As this class contains pointers)
CPPTopKVKernel & operator= (const CPPTopKVKernel &)=delete
Prevent instances of this class from being copied (As this class contains pointers)
CPPTopKVKernel (CPPTopKVKernel &&)=default
Allow instances of this class to be moved.
CPPTopKVKernel & operator= (CPPTopKVKernel &&)=default
Allow instances of this class to be moved.
~CPPTopKVKernel ()=default
Default destructor.
void configure (const ITensor *predictions, const ITensor *targets, ITensor *output, const unsigned int k)
Set the input and output of the kernel.
void run (const Window &window, const ThreadInfo &info) override
Execute the kernel on the passed window.
bool is_parallelisable () const override
Indicates whether or not the kernel is parallelisable.
Public Member Functions inherited from ICPPKernel
virtual ~ICPPKernel ()=default
Default destructor.
Public Member Functions inherited from IKernel
IKernel ()
Constructor.
virtual ~IKernel ()=default
Destructor.
virtual BorderSize border_size () const
The size of the border for that kernel.
const Window & window () const
The maximum window the kernel can be executed on.
Static Public Member Functions
static Status validate (const ITensorInfo *predictions, const ITensorInfo *targets, ITensorInfo *output, const unsigned int k)
Static function to check if given info will lead to a valid configuration of CPPTopKVKernel.
Detailed Description
CPP kernel to perform tensor TopKV operation.
Definition at line 34 of file CPPTopKVKernel.h.
Constructor & Destructor Documentation
CPPTopKVKernel() [1/3]
CPPTopKVKernel ()
Default constructor.
Definition at line 96 of file CPPTopKVKernel.cpp.
     : _predictions(nullptr), _targets(nullptr), _output(nullptr), _k(), _batch_size(), _num_classes()
 {
 }
CPPTopKVKernel() [2/3]
CPPTopKVKernel (const CPPTopKVKernel &) delete
Prevent instances of this class from being copied (As this class contains pointers)
CPPTopKVKernel() [3/3]
CPPTopKVKernel (CPPTopKVKernel &&) default
Allow instances of this class to be moved.
~CPPTopKVKernel()
~CPPTopKVKernel () default
Default destructor.
Member Function Documentation
configure()
void configure (const ITensor * predictions, const ITensor * targets, ITensor * output, const unsigned int k)
Set the input and output of the kernel.
Parameters
[in] predictions A batch_size x classes tensor. Data types supported: F16/S32/F32/QASYMM8
[in] targets A batch_size 1D tensor of class ids. Data types supported: S32
[out] output Computed precision at k as a bool 1D tensor. Data types supported: U8
[in] k Number of top elements to look at for computing precision.
Definition at line 101 of file CPPTopKVKernel.cpp.
 {
     ARM_COMPUTE_ERROR_ON_NULLPTR(predictions, targets, output);
     // Perform validation step
     ARM_COMPUTE_ERROR_THROW_ON(validate_arguments(predictions->info(), targets->info(), output->info(), k));
     auto_init_if_empty(*output->info(), targets->info()->tensor_shape(), 1, DataType::U8);
     _predictions = predictions;
     _targets     = targets;
     _output      = output;
     _k           = k;
     _batch_size  = predictions->info()->dimension(1);
     _num_classes = predictions->info()->dimension(0);
     ICPPKernel::configure(Window()); // Default 1 iteration window
 }
References ARM_COMPUTE_ERROR_ON_NULLPTR, ARM_COMPUTE_ERROR_THROW_ON, arm_compute::auto_init_if_empty(), ITensorInfo::dimension(), ITensor::info(), ITensorInfo::tensor_shape(), and arm_compute::U8.
is_parallelisable()
bool is_parallelisable () const override virtual
Indicates whether or not the kernel is parallelisable.
If the kernel is parallelisable then the window returned by window() can be split into sub-windows which can then be run in parallel.
If the kernel is not parallelisable then only the window returned by window() can be passed to run()
Returns
True if the kernel is parallelisable
Reimplemented from IKernel.
Definition at line 126 of file CPPTopKVKernel.cpp.
 {
     return false;
 }
name()
const char* name () const inline override virtual
Name of the kernel.
Returns
Kernel name
Implements ICPPKernel.
Definition at line 37 of file CPPTopKVKernel.h.
     {
         return "CPPTopKVKernel";
     }
operator=() [1/2]
CPPTopKVKernel& operator= (const CPPTopKVKernel &) delete
Prevent instances of this class from being copied (As this class contains pointers)
operator=() [2/2]
CPPTopKVKernel& operator= (CPPTopKVKernel &&) default
Allow instances of this class to be moved.
run()
void run (const Window & window, const ThreadInfo & info) override virtual
Execute the kernel on the passed window.
Warning
If is_parallelisable() returns false then the passed window must be equal to window()
Note
The window has to be a region within the window returned by the window() method
The width of the window has to be a multiple of num_elems_processed_per_iteration().
Parameters
[in] window Region on which to execute the kernel. (Must be a region of the window returned by window())
[in] info Info about executing thread and CPU.
Implements ICPPKernel.
Definition at line 131 of file CPPTopKVKernel.cpp.
 {
     ARM_COMPUTE_UNUSED(window, info);
     switch(_predictions->info()->data_type())
     {
         case DataType::F32:
             run_topkv<float>();
             break;
         case DataType::F16:
             run_topkv<half>();
             break;
         case DataType::S32:
             run_topkv<int>();
             break;
         case DataType::QASYMM8:
             run_topkv<uint8_t>();
             break;
         default:
             ARM_COMPUTE_ERROR("Not supported");
     }
 }
References ARM_COMPUTE_ERROR, ARM_COMPUTE_UNUSED, ITensorInfo::data_type(), arm_compute::F16, arm_compute::F32, ITensor::info(), arm_compute::test::validation::info, arm_compute::QASYMM8, arm_compute::S32, and IKernel::window().
validate()
Status validate (const ITensorInfo * predictions, const ITensorInfo * targets, ITensorInfo * output, const unsigned int k) static
Static function to check if given info will lead to a valid configuration of CPPTopKVKernel.
Parameters
[in] predictions A batch_size x classes tensor info. Data types supported: F16/S32/F32/QASYMM8
[in] targets A batch_size 1D tensor info of class ids. Data types supported: S32
[in] output Computed precision at k as a bool 1D tensor info. Data types supported: U8
[in] k Number of top elements to look at for computing precision.
Returns
a status
Definition at line 120 of file CPPTopKVKernel.cpp.
 {
     ARM_COMPUTE_RETURN_ON_ERROR(validate_arguments(predictions, targets, output, k));
     return Status{};
 }
References ARM_COMPUTE_RETURN_ON_ERROR.
Referenced by CPPTopKV::validate().
The documentation for this class was generated from the following files:
arm_compute/core/CPP/kernels/CPPTopKVKernel.h
src/core/CPP/kernels/CPPTopKVKernel.cpp