Compute Library: DetectionOutputLayerInfo Class Reference
DetectionOutputLayerInfo Class Reference final
Detection Output layer info.
#include <Types.h>
Public Member Functions
DetectionOutputLayerInfo ()
Default Constructor.
DetectionOutputLayerInfo (int num_classes, bool share_location, DetectionOutputLayerCodeType code_type, int keep_top_k, float nms_threshold, int top_k=-1, int background_label_id=-1, float confidence_threshold=std::numeric_limits< float >::lowest(), bool variance_encoded_in_target=false, float eta=1)
Constructor.
int num_classes () const
Get num classes.
bool share_location () const
Get share location.
DetectionOutputLayerCodeType code_type () const
Get detection output code type.
bool variance_encoded_in_target () const
Get if variance encoded in target.
int keep_top_k () const
Get the number of total bounding boxes to be kept per image.
float nms_threshold () const
Get nms threshold.
float eta () const
Get eta.
int background_label_id () const
Get background label ID.
float confidence_threshold () const
Get confidence threshold.
int top_k () const
Get top K.
int num_loc_classes () const
Get number of location classes.
Detailed Description
Detection Output layer info.
Definition at line 1002 of file Types.h.
Constructor & Destructor Documentation
DetectionOutputLayerInfo() [1/2]
DetectionOutputLayerInfo () inline
Default Constructor.
Definition at line 1006 of file Types.h.
         : _num_classes(),
           _share_location(),
           _code_type(DetectionOutputLayerCodeType::CORNER),
           _keep_top_k(),
           _nms_threshold(),
           _top_k(),
           _background_label_id(),
           _confidence_threshold(),
           _variance_encoded_in_target(false),
           _eta(),
           _num_loc_classes()
     {
         _num_loc_classes = _share_location ? 1 : _num_classes;
     }
DetectionOutputLayerInfo() [2/2]
DetectionOutputLayerInfo (int num_classes, bool share_location, DetectionOutputLayerCodeType code_type, int keep_top_k, float nms_threshold, int top_k = -1, int background_label_id = -1, float confidence_threshold = std::numeric_limits<float>::lowest(), bool variance_encoded_in_target = false, float eta = 1) inline
Constructor.
Parameters
[in] num_classes Number of classes to be predicted.
[in] share_location If true, bounding box are shared among different classes.
[in] code_type Type of coding method for bbox.
[in] keep_top_k Number of total bounding boxes to be kept per image after NMS step.
[in] nms_threshold Threshold to be used in NMS.
[in] top_k (Optional) Number of boxes per image with top confidence scores that are fed into the NMS algorithm. Default set to -1.
[in] background_label_id (Optional) Background label ID. If there is no background class, set it as -1.
[in] confidence_threshold (Optional) Only consider detections whose confidences are larger than a threshold. Default set to -FLT_MAX.
[in] variance_encoded_in_target (Optional) If true, variance is encoded in target. Otherwise we need to adjust the predicted offset accordingly.Default set to false.
[in] eta (Optional) Eta.
Definition at line 1034 of file Types.h.
         : _num_classes(num_classes),
           _share_location(share_location),
           _code_type(code_type),
           _keep_top_k(keep_top_k),
           _nms_threshold(nms_threshold),
           _top_k(top_k),
           _background_label_id(background_label_id),
           _confidence_threshold(confidence_threshold),
           _variance_encoded_in_target(variance_encoded_in_target),
           _eta(eta),
           _num_loc_classes()
     {
         _num_loc_classes = _share_location ? 1 : _num_classes;
     }
Member Function Documentation
background_label_id()
int background_label_id () const inline
Get background label ID.
Definition at line 1086 of file Types.h.
     {
         return _background_label_id;
     }
Referenced by CPPDetectionOutputLayer::configure(), arm_compute::operator<<(), and CPPDetectionOutputLayer::run().
code_type()
DetectionOutputLayerCodeType code_type () const inline
Get detection output code type.
Definition at line 1061 of file Types.h.
     {
         return _code_type;
     }
Referenced by arm_compute::operator<<(), and CPPDetectionOutputLayer::run().
confidence_threshold()
float confidence_threshold () const inline
Get confidence threshold.
Definition at line 1091 of file Types.h.
     {
         return _confidence_threshold;
     }
Referenced by arm_compute::operator<<(), and CPPDetectionOutputLayer::run().
eta()
float eta () const inline
Get eta.
Definition at line 1081 of file Types.h.
     {
         return _eta;
     }
Referenced by arm_compute::operator<<(), and CPPDetectionOutputLayer::run().
keep_top_k()
int keep_top_k () const inline
Get the number of total bounding boxes to be kept per image.
Definition at line 1071 of file Types.h.
     {
         return _keep_top_k;
     }
Referenced by arm_compute::operator<<(), and CPPDetectionOutputLayer::run().
nms_threshold()
float nms_threshold () const inline
Get nms threshold.
Definition at line 1076 of file Types.h.
     {
         return _nms_threshold;
     }
Referenced by arm_compute::operator<<(), and CPPDetectionOutputLayer::run().
num_classes()
int num_classes () const inline
Get num classes.
Definition at line 1051 of file Types.h.
     {
         return _num_classes;
     }
Referenced by arm_compute::operator<<(), and CPPDetectionOutputLayer::run().
num_loc_classes()
int num_loc_classes () const inline
Get number of location classes.
Definition at line 1101 of file Types.h.
     {
         return _num_loc_classes;
     }
Referenced by CPPDetectionOutputLayer::configure(), arm_compute::operator<<(), and CPPDetectionOutputLayer::run().
share_location()
bool share_location () const inline
Get share location.
Definition at line 1056 of file Types.h.
     {
         return _share_location;
     }
Referenced by CPPDetectionOutputLayer::configure(), arm_compute::operator<<(), and CPPDetectionOutputLayer::run().
top_k()
int top_k () const inline
Get top K.
Definition at line 1096 of file Types.h.
     {
         return _top_k;
     }
Referenced by arm_compute::operator<<(), and CPPDetectionOutputLayer::run().
variance_encoded_in_target()
bool variance_encoded_in_target () const inline
Get if variance encoded in target.
Definition at line 1066 of file Types.h.
     {
         return _variance_encoded_in_target;
     }
Referenced by arm_compute::operator<<(), and CPPDetectionOutputLayer::run().
The documentation for this class was generated from the following file:
arm_compute/core/Types.h