Compute Library: NESoftmaxLayer Class Reference
NESoftmaxLayer Class Reference
Basic function to compute a SoftmaxLayer.
#include <NESoftmaxLayer.h>
Public Member Functions
NESoftmaxLayer (std::shared_ptr< IMemoryManager > memory_manager=nullptr)
Constructor.
NESoftmaxLayer (const NESoftmaxLayer &)=delete
Prevent instances of this class from being copied (As this class contains pointers)
NESoftmaxLayer (NESoftmaxLayer &&)=default
Default move constructor.
NESoftmaxLayer & operator= (const NESoftmaxLayer &)=delete
Prevent instances of this class from being copied (As this class contains pointers)
NESoftmaxLayer & operator= (NESoftmaxLayer &&)=default
Default move assignment operator.
void configure (ITensor *input, ITensor *output, float beta=1.0f, size_t axis=1)
Set the input and output tensors.
void run () override
Run the kernels contained in the function.
Public Member Functions inherited from IFunction
virtual ~IFunction ()=default
Destructor.
virtual void prepare ()
Prepare the function for executing.
Static Public Member Functions
static Status validate (const ITensorInfo *input, const ITensorInfo *output, float beta=1.0f, size_t axis=1)
Static function to check if given info will lead to a valid configuration of NESoftmaxLayer.
Detailed Description
Basic function to compute a SoftmaxLayer.
Softmax is calculated by :
\[ out = \frac{e^{x - max(x)}}{\sum{e^{x - max(x)}}} \]
This function runs the following kernels:
NEFillBorderKernel
NELogits1DMaxKernel
NELogits1DSoftmaxKernel
Definition at line 49 of file NESoftmaxLayer.h.
Constructor & Destructor Documentation
NESoftmaxLayer() [1/3]
NESoftmaxLayer (std::shared_ptr< IMemoryManager > memory_manager = nullptr)
Constructor.
Definition at line 36 of file NESoftmaxLayer.cpp.
     : _memory_group(std::move(memory_manager)), _max_kernel(), _softmax_kernel(), _flat_or_reshape_kernel_ptr(nullptr), _fill_border_kernel(), _reshape_kernel(), _max(), _tmp(), _input_flattened(),
       _output_flattened(), _needs_flattening(false)
 {
 }
NESoftmaxLayer() [2/3]
NESoftmaxLayer (const NESoftmaxLayer &) delete
Prevent instances of this class from being copied (As this class contains pointers)
NESoftmaxLayer() [3/3]
NESoftmaxLayer (NESoftmaxLayer &&) default
Default move constructor.
Member Function Documentation
configure()
void configure (ITensor * input, ITensor * output, float beta = 1.0f, size_t axis = 1)
Set the input and output tensors.
Parameters
[in,out] input Source tensor. Data types supported: QASYMM8/F16/F32. If the width is not a multiple of the internal processing block size, NEFillBorderKernel replicates the last value of each row to the nearest multiple.
[out] output Destination tensor. Data types supported: same as input.
[in] beta (Optional) A scaling factor for the exponent.
[in] axis (Optional) Reduction axis. Defaults to 1. Must be in range [1, input_num_dimensions). It has the purpose of squashing the first axis dimensions together. For instance, given a [4x4x4x4] image, when axis is 2, the Softmax reduction will be applied on each of the [4x4] planes of the input image.
Definition at line 71 of file NESoftmaxLayer.cpp.
 {
     // Perform validation step
     ARM_COMPUTE_ERROR_ON_NULLPTR(input, output);
     ARM_COMPUTE_ERROR_THROW_ON(NESoftmaxLayer::validate(input->info(), output->info(), beta, axis));
     // We don't need flattening only in the case the input is 2D and axis is 1
     _needs_flattening = axis != 1;
     // If we are dealing with a 4D tensor, we will:
     // - Flatten the input, so that we end up with a [width*height*depth] * batches 2D tensor
     // - Execute all the pipeline (reduction + normalization) on the flattened tensor
     // - Reshape the flattened output into the real output
     if(_needs_flattening)
     {
         // Add to the memory manager _input_flattened
         _memory_group.manage(&_input_flattened);
         // Configure  _flatten_kernel and _input_flattened
         configure_reshape_input_kernel(input, output, axis);
     }
     // We want to deal with a 2D input. Either it is the flattened version of the original input (4D case)
     // or it is the original input case (2D case)
     ITensor *input_2D = (_needs_flattening ? &_input_flattened : input);
     // Create intermediate tensors shapes
     const TensorInfo input_info    = input_2D->info()->clone()->reset_padding().set_is_resizable(true);
     DataType         tmp_data_type = is_data_type_quantized_asymmetric(input_2D->info()->data_type()) ? DataType::F32 : input_2D->info()->data_type();
     TensorInfo       tensor_info_tmp(input_info.clone()->set_data_type(tmp_data_type));
     // Init intermediate tensors
     TensorShape max_sum_shape = input_2D->info()->tensor_shape();
     max_sum_shape.set(0, 1);
     _max.allocator()->init(input_info.clone()->set_tensor_shape(max_sum_shape));
     _tmp.allocator()->init(tensor_info_tmp);
     // Manage intermediate buffers
     _memory_group.manage(&_max);
     _memory_group.manage(&_tmp);
     // Configure Kernels
     _max_kernel.configure(input_2D, &_max);
     if(_needs_flattening)
     {
         // Add to the memory manager _output_flattened
         _memory_group.manage(&_output_flattened);
         // The normalization kernel stores the result in a flat output tensor
         _softmax_kernel.configure(input_2D, &_max, &_output_flattened, beta, &_tmp);
         _input_flattened.allocator()->allocate();
         // Reshape the flat output into the requested (4D) output
         _reshape_kernel.configure(&_output_flattened, output);
         // Allocate the intermediate flat tensors
         _output_flattened.allocator()->allocate();
     }
     else
     {
         // Softmax 2D case
         _fill_border_kernel.configure(input_2D, _max_kernel.border_size(), BorderMode::REPLICATE);
         _softmax_kernel.configure(input_2D, &_max, output, beta, &_tmp);
     }
     // Allocate intermediate buffers
     _max.allocator()->allocate();
     _tmp.allocator()->allocate();
 }
References TensorAllocator::allocate(), Tensor::allocator(), ARM_COMPUTE_ERROR_ON_NULLPTR, ARM_COMPUTE_ERROR_THROW_ON, arm_compute::test::validation::axis, NELogits1DMaxKernel::border_size(), ICloneable< T >::clone(), NEReshapeLayerKernel::configure(), NELogits1DMaxKernel::configure(), NEFillBorderKernel::configure(), NELogits1DSoftmaxKernel::configure(), ITensorInfo::data_type(), arm_compute::F32, ITensor::info(), TensorAllocator::init(), arm_compute::test::validation::input_info, arm_compute::is_data_type_quantized_asymmetric(), MemoryGroupBase< TensorType >::manage(), arm_compute::REPLICATE, TensorShape::set(), ITensorInfo::tensor_shape(), and NESoftmaxLayer::validate().
Referenced by arm_compute::test::validation::DATA_TEST_CASE().
operator=() [1/2]
NESoftmaxLayer& operator= (const NESoftmaxLayer &) delete
Prevent instances of this class from being copied (As this class contains pointers)
operator=() [2/2]
NESoftmaxLayer& operator= (NESoftmaxLayer &&) default
Default move assignment operator.
run()
void run () override virtual
Run the kernels contained in the function.
For NEON kernels:
Multi-threading is used for the kernels which are parallelisable.
By default std::thread::hardware_concurrency() threads are used.
Note
CPPScheduler::set_num_threads() can be used to manually set the number of threads
For OpenCL kernels:
All the kernels are enqueued on the queue associated with CLScheduler.
The queue is then flushed.
Note
The function will not block until the kernels are executed. It is the user's responsibility to wait.
Will call prepare() on first run if hasn't been done
Implements IFunction.
Definition at line 181 of file NESoftmaxLayer.cpp.
 {
     _memory_group.acquire();
     if(_needs_flattening)
     {
         NEScheduler::get().schedule(_flat_or_reshape_kernel_ptr.get(), Window::DimY);
     }
     NEScheduler::get().schedule(&_fill_border_kernel, Window::DimY);
     NEScheduler::get().schedule(&_max_kernel, Window::DimY);
     NEScheduler::get().schedule(&_softmax_kernel, Window::DimY);
     if(_needs_flattening)
     {
         NEScheduler::get().schedule(&_reshape_kernel, Window::DimY);
     }
     _memory_group.release();
 }
References MemoryGroupBase< TensorType >::acquire(), Window::DimY, Scheduler::get(), MemoryGroupBase< TensorType >::release(), and IScheduler::schedule().
validate()
Status validate (const ITensorInfo * input, const ITensorInfo * output, float beta = 1.0f, size_t axis = 1) static
Static function to check if given info will lead to a valid configuration of NESoftmaxLayer.
Parameters
[in] input Source tensor info. Data types supported: QASYMM8/F16/F32.
[in] output Destination tensor info. Data types supported: same as input
[in] beta (Optional) A scaling factor for the exponent.
[in] axis (Optional) Reduction axis. Defaults to 1. Must be in range [1, input_num_dimensions). It has the purpose of squashing the first axis dimensions together. For instance, given a [4x4x4x4] image, when axis is 2, the Softmax reduction will be applied on each of the [4x4] planes of the input image.
Returns
a status
Definition at line 141 of file NESoftmaxLayer.cpp.
 {
     // Perform validation step
     ARM_COMPUTE_RETURN_ERROR_ON_NULLPTR(input, output);
     ARM_COMPUTE_RETURN_ERROR_ON_MSG(input->num_dimensions() > 4, "Only up to 4 dimensions are supported");
     ARM_COMPUTE_UNUSED(beta);
     ARM_COMPUTE_RETURN_ERROR_ON(axis < 1 || input->num_dimensions() < axis);
     // Create intermediate tensor info
     DataType         tmp_data_type = input->data_type();
     const TensorInfo tensor_info_tmp(input->clone()->set_data_type(tmp_data_type).set_is_resizable(true));
     TensorShape max_sum_shape = input->tensor_shape();
     max_sum_shape.set(0, 1);
     const TensorInfo tensor_info_max_sum(input->clone()->set_tensor_shape(max_sum_shape).set_data_type(tmp_data_type).set_quantization_info(input->quantization_info()).set_is_resizable(true));
     const TensorInfo dont_care;
     const bool needs_flattening = (axis != 1);
     if(needs_flattening)
     {
         const TensorShape shape_flatten = misc::shape_calculator::compute_softmax_shape(input, axis);
         TensorInfo        tensor_info_flat(input->clone()->set_tensor_shape(shape_flatten).set_is_resizable(true));
         if(axis != 3)
         {
             ARM_COMPUTE_RETURN_ON_ERROR(NEReshapeLayerKernel::validate(input, &tensor_info_flat));
         }
         else
         {
             ARM_COMPUTE_RETURN_ON_ERROR(NEFlattenLayerKernel::validate(input, &tensor_info_flat));
         }
     }
     ARM_COMPUTE_RETURN_ON_ERROR(NELogits1DMaxKernel::validate(input, &tensor_info_max_sum));
     ARM_COMPUTE_RETURN_ON_ERROR(NELogits1DSoftmaxKernel::validate(&tensor_info_tmp, &tensor_info_max_sum, output, beta, &dont_care));
     return Status{};
 }
References ARM_COMPUTE_RETURN_ERROR_ON, ARM_COMPUTE_RETURN_ERROR_ON_MSG, ARM_COMPUTE_RETURN_ERROR_ON_NULLPTR, ARM_COMPUTE_RETURN_ON_ERROR, ARM_COMPUTE_UNUSED, arm_compute::test::validation::axis, ICloneable< T >::clone(), arm_compute::misc::shape_calculator::compute_softmax_shape(), ITensorInfo::data_type(), ITensorInfo::num_dimensions(), ITensorInfo::quantization_info(), TensorShape::set(), ITensorInfo::tensor_shape(), NEReshapeLayerKernel::validate(), NELogits1DMaxKernel::validate(), NEFlattenLayerKernel::validate(), and NELogits1DSoftmaxKernel::validate().
Referenced by NESoftmaxLayer::configure().
The documentation for this class was generated from the following files:
arm_compute/runtime/NEON/functions/NESoftmaxLayer.h
src/runtime/NEON/functions/NESoftmaxLayer.cpp