Compute Library: CLIm2ColKernel Class Reference
CLIm2ColKernel Class Reference
Interface for the im2col reshape kernel.
#include <CLIm2ColKernel.h>
Public Member Functions
CLIm2ColKernel ()
Default constructor.
CLIm2ColKernel (const CLIm2ColKernel &)=delete
Prevent instances of this class from being copied (As this class contains pointers)
CLIm2ColKernel & operator= (const CLIm2ColKernel &)=delete
Prevent instances of this class from being copied (As this class contains pointers)
CLIm2ColKernel (CLIm2ColKernel &&)=default
Allow instances of this class to be moved.
CLIm2ColKernel & operator= (CLIm2ColKernel &&)=default
Allow instances of this class to be moved.
void configure (const ICLTensor *input, ICLTensor *output, const Size2D &kernel_dims, const PadStrideInfo &conv_info, bool has_bias, const Size2D &dilation=Size2D(1U, 1U), unsigned int num_groups=1)
Set the input and output of the kernel.
void run (const Window &window, cl::CommandQueue &queue) override
Enqueue the OpenCL kernel to process the given window on the passed OpenCL command queue.
Public Member Functions inherited from ICLKernel
ICLKernel ()
Constructor.
cl::Kernel & kernel ()
Returns a reference to the OpenCL kernel of this object.
template<typename T >
void add_1D_array_argument (unsigned int &idx, const ICLArray< T > *array, const Strides &strides, unsigned int num_dimensions, const Window &window)
Add the passed 1D array's parameters to the object's kernel's arguments starting from the index idx.
void add_1D_tensor_argument (unsigned int &idx, const ICLTensor *tensor, const Window &window)
Add the passed 1D tensor's parameters to the object's kernel's arguments starting from the index idx.
void add_2D_tensor_argument (unsigned int &idx, const ICLTensor *tensor, const Window &window)
Add the passed 2D tensor's parameters to the object's kernel's arguments starting from the index idx.
void add_3D_tensor_argument (unsigned int &idx, const ICLTensor *tensor, const Window &window)
Add the passed 3D tensor's parameters to the object's kernel's arguments starting from the index idx.
void add_4D_tensor_argument (unsigned int &idx, const ICLTensor *tensor, const Window &window)
Add the passed 4D tensor's parameters to the object's kernel's arguments starting from the index idx.
template<typename T >
void add_argument (unsigned int &idx, T value)
Add the passed parameters to the object's kernel's arguments starting from the index idx.
void set_lws_hint (const cl::NDRange &lws_hint)
Set the Local-Workgroup-Size hint.
cl::NDRange lws_hint () const
Return the Local-Workgroup-Size hint.
const std::string & config_id () const
Get the configuration ID.
void set_target (GPUTarget target)
Set the targeted GPU architecture.
void set_target (cl::Device &device)
Set the targeted GPU architecture according to the CL device.
GPUTarget get_target () const
Get the targeted GPU architecture.
size_t get_max_workgroup_size ()
Get the maximum workgroup size for the device the CLKernelLibrary uses.
template<typename T , unsigned int dimension_size>
void add_array_argument (unsigned &idx, const ICLArray< T > *array, const Strides &strides, unsigned int num_dimensions, const Window &window)
Add the passed array's parameters to the object's kernel's arguments starting from the index idx.
template<unsigned int dimension_size>
void add_tensor_argument (unsigned &idx, const ICLTensor *tensor, const Window &window)
Public Member Functions inherited from IKernel
IKernel ()
Constructor.
virtual ~IKernel ()=default
Destructor.
virtual bool is_parallelisable () const
Indicates whether or not the kernel is parallelisable.
virtual BorderSize border_size () const
The size of the border for that kernel.
const Window & window () const
The maximum window the kernel can be executed on.
Static Public Member Functions
static Status validate (const ITensorInfo *input, const ITensorInfo *output, const Size2D &kernel_dims, const PadStrideInfo &conv_info, bool has_bias, const Size2D &dilation=Size2D(1U, 1U), unsigned int num_groups=1)
Static function to check if given info will lead to a valid configuration of CLIm2ColKernel.
Static Public Member Functions inherited from ICLKernel
static constexpr unsigned int num_arguments_per_1D_array ()
Returns the number of arguments enqueued per 1D array object.
static constexpr unsigned int num_arguments_per_1D_tensor ()
Returns the number of arguments enqueued per 1D tensor object.
static constexpr unsigned int num_arguments_per_2D_tensor ()
Returns the number of arguments enqueued per 2D tensor object.
static constexpr unsigned int num_arguments_per_3D_tensor ()
Returns the number of arguments enqueued per 3D tensor object.
static constexpr unsigned int num_arguments_per_4D_tensor ()
Returns the number of arguments enqueued per 4D tensor object.
static cl::NDRange gws_from_window (const Window &window)
Get the global work size given an execution window.
Data Fields
const ICLTensor * _input
ICLTensor * _output
std::pair< unsigned int, unsigned int > _convolved_dims
unsigned int _num_elems_processed_per_iteration
Size2D _kernel_dims
PadStrideInfo _conv_info
unsigned int _num_groups
Detailed Description
Interface for the im2col reshape kernel.
Rearranges image blocks into columns. It is used to strip out each convolution block to a single column. It is used to transform a convolution to a plain matrix multiplication.
For example taking into account the image below and assuming 3x3 image blocks with stride of 1 we have:
\[ \left(\begin{array}{cccc} a00 & a01 & a02 & a03 \\ a10 & a11 & a12 & a13 \\ a20 & a21 & a22 & a23 \\ a30 & a31 & a32 & a33 \\ \end{array} \right) = \left(\begin{array}{ccccccccc} a00 & a01 & a02 & a10 & a11 & a12 & a20 & a21 & a22 \\ a01 & a02 & a03 & a11 & a12 & a13 & a21 & a22 & a23 \\ a10 & a11 & a12 & a20 & a21 & a22 & a30 & a31 & a32 \\ a11 & a12 & a13 & a21 & a22 & a23 & a31 & a32 & a33 \\ \end{array} \right) \]
Definition at line 56 of file CLIm2ColKernel.h.
Constructor & Destructor Documentation
CLIm2ColKernel() [1/3]
CLIm2ColKernel ()
Default constructor.
Definition at line 288 of file CLIm2ColKernel.cpp.
     : _input(nullptr), _output(nullptr), _convolved_dims(), _num_elems_processed_per_iteration(1), _kernel_dims(), _conv_info(), _num_groups()
 {
 }
CLIm2ColKernel() [2/3]
CLIm2ColKernel (const CLIm2ColKernel &) delete
Prevent instances of this class from being copied (As this class contains pointers)
CLIm2ColKernel() [3/3]
CLIm2ColKernel (CLIm2ColKernel &&) default
Allow instances of this class to be moved.
Member Function Documentation
configure()
void configure (const ICLTensor * input, ICLTensor * output, const Size2D & kernel_dims, const PadStrideInfo & conv_info, bool has_bias, const Size2D & dilation = Size2D(1U, 1U), unsigned int num_groups = 1)
Set the input and output of the kernel.
Parameters
[in] input The input tensor to convert. 3 lower dimensions represent a single input [width, height, IFM], while every optional dimension from 4 and above represent a batch of inputs. Data types supported: QASYMM8/F16/F32
[out] output The output tensor. First 2 lower dimensions represent a transform of each 3D input, while every dimension above represents a batch. Data types supported: Same as input
[in] kernel_dims The kernel dimensions (width and height).
[in] conv_info Contains padding and stride information described in PadStrideInfo.
[in] has_bias In case biases are provided expands the matrix with 1.
[in] dilation (Optional) Dilation, in elements, across x and y. Defaults to (1, 1).
[in] num_groups (Optional) Number of groups when performing a grouped convolution. num_groups != 1 is only supported for NCHW data layout
Definition at line 293 of file CLIm2ColKernel.cpp.
 {
     ARM_COMPUTE_ERROR_ON_NULLPTR(input, output);
     ARM_COMPUTE_ERROR_THROW_ON(validate_arguments(input->info(), output->info(), kernel_dims, conv_info, has_bias, dilation, num_groups));
     const DataLayout   data_layout  = input->info()->data_layout();
     const unsigned int width_idx    = get_data_layout_dimension_index(data_layout, DataLayoutDimension::WIDTH);
     const unsigned int height_idx   = get_data_layout_dimension_index(data_layout, DataLayoutDimension::HEIGHT);
     const unsigned int input_width  = input->info()->dimension(width_idx);
     const unsigned int input_height = input->info()->dimension(height_idx);
     // Select and configure the optimal OpenCL kernel to run.
     // This function returns the OpenCL kernel's name, the arguments to pass at compile time, the number of elements processed per iteration
     // and the padding requirement flag
     Im2ColConfiguration im2col_config = configure_opencl_kernel(input->info(), kernel_dims, conv_info, has_bias, dilation, num_groups);
     // Create kernel
     _kernel = static_cast<cl::Kernel>(CLKernelLibrary::get().create_kernel(im2col_config.kernel_name, im2col_config.build_options));
     _input                             = input;
     _output                            = output;
     _convolved_dims                    = scaled_dimensions(input_width, input_height, kernel_dims.width, kernel_dims.height, conv_info, dilation);
     _num_elems_processed_per_iteration = im2col_config.num_elems_processed_per_iteration;
     _kernel_dims                       = kernel_dims; // Only needed by the Tuner
     _conv_info                         = conv_info;   // Only needed by the Tuner
     _num_groups                        = num_groups;
     // Configure kernel window
     auto win_config = validate_and_configure_window(input->info(), output->info(), kernel_dims, conv_info, has_bias, dilation, im2col_config.num_elems_processed_per_iteration,
                                                     im2col_config.is_padding_required_nchw, num_groups);
     ARM_COMPUTE_ERROR_THROW_ON(win_config.first);
     ICLKernel::configure_internal(win_config.second);
     // Set config_id for enabling LWS tuning
     _config_id = im2col_config.kernel_name;
     _config_id += "_";
     _config_id += lower_string(string_from_data_type(input->info()->data_type()));
     _config_id += "_";
     _config_id += support::cpp11::to_string(num_groups);
     _config_id += "_";
     _config_id += support::cpp11::to_string(output->info()->dimension(0));
     _config_id += "_";
     _config_id += support::cpp11::to_string(output->info()->dimension(1));
     _config_id += "_";
     _config_id += lower_string(string_from_data_layout(input->info()->data_layout()));
 }
References CLIm2ColKernel::_conv_info, CLIm2ColKernel::_convolved_dims, CLIm2ColKernel::_input, CLIm2ColKernel::_kernel_dims, CLIm2ColKernel::_num_elems_processed_per_iteration, CLIm2ColKernel::_num_groups, CLIm2ColKernel::_output, ARM_COMPUTE_ERROR_ON_NULLPTR, ARM_COMPUTE_ERROR_THROW_ON, arm_compute::test::validation::conv_info, arm_compute::create_kernel(), ITensorInfo::data_layout(), ITensorInfo::data_type(), arm_compute::test::validation::dilation, ITensorInfo::dimension(), CLKernelLibrary::get(), arm_compute::get_data_layout_dimension_index(), Size2D::height, arm_compute::HEIGHT, ITensor::info(), arm_compute::lower_string(), arm_compute::scaled_dimensions(), arm_compute::string_from_data_layout(), arm_compute::string_from_data_type(), arm_compute::support::cpp11::to_string(), Size2D::width, and arm_compute::WIDTH.
Referenced by CLLocallyConnectedLayer::configure(), and CLGEMMConvolutionLayer::configure().
operator=() [1/2]
CLIm2ColKernel& operator= (const CLIm2ColKernel &) delete
Prevent instances of this class from being copied (As this class contains pointers)
operator=() [2/2]
CLIm2ColKernel& operator= (CLIm2ColKernel &&) default
Allow instances of this class to be moved.
run()
void run (const Window & window, cl::CommandQueue & queue) override virtual
Enqueue the OpenCL kernel to process the given window on the passed OpenCL command queue.
Note
The queue is not flushed by this method, and therefore the kernel will not have been executed by the time this method returns.
Parameters
[in] window Region on which to execute the kernel. (Must be a valid region of the window returned by window()).
[in,out] queue Command queue on which to enqueue the kernel.
Implements ICLKernel.
Definition at line 352 of file CLIm2ColKernel.cpp.
 {
     ARM_COMPUTE_ERROR_ON_UNCONFIGURED_KERNEL(this);
     ARM_COMPUTE_ERROR_ON_MISMATCHING_WINDOWS(ICLKernel::window(), window);
     // Get initial windows
     // Collapse in order to have (SRC_DEPTH * BATCH_SIZE) on the 3rd dimension
     Window window_collapsed = window.collapse_if_possible(ICLKernel::window(), Window::DimZ);
     window_collapsed.set_dimension_step(Window::DimZ, 1);
     Window window_output;
     window_output.use_tensor_dimensions(_output->info()->tensor_shape());
     const Window first_slice_3d = window_collapsed.first_slice_window_3D();
     Window slice     = first_slice_3d;
     Window slice_in  = first_slice_3d;
     Window slice_out = window_output.first_slice_window_2D();
     if(_input->info()->data_layout() == DataLayout::NHWC)
     {
         const Window tmp_win     = window.collapse_if_possible(ICLKernel::window(), 3);
         const int    num_batches = tmp_win[3].end();
         slice.set(1, Window::Dimension(0, static_cast<int>(_output->info()->tensor_shape()[1]), 1));
         slice.set(2, Window::Dimension(0, static_cast<int>(num_batches), 1));
     }
     else
     {
         slice.set(0, Window::Dimension(0, static_cast<int>(ceil_to_multiple(_convolved_dims.first, _num_elems_processed_per_iteration)), _num_elems_processed_per_iteration));
         slice.set(1, Window::Dimension(0, static_cast<int>(_convolved_dims.second), 1));
         // Note: In case of NCHW the 3rd dimension is already set collapsing the input window
     }
     // Setup input slice
     // The dimensions of the input are increased within the OpenCL kernel
     slice_in.set(Window::DimX, Window::Dimension(0, 0, 0));
     slice_in.set(Window::DimY, Window::Dimension(0, 0, 0));
     slice_in.set(Window::DimZ, Window::Dimension(0, 0, 0));
     // Setup output slice
     // The dimensions of the output are increased within the OpenCL kernel
     slice_out.set(Window::DimX, Window::Dimension(0, 0, 0));
     slice_out.set(Window::DimY, Window::Dimension(0, 0, 0));
     unsigned int idx = num_arguments_per_3D_tensor() + (_num_groups == 1 ? num_arguments_per_2D_tensor() : num_arguments_per_3D_tensor());
     _kernel.setArg<cl_uint>(idx++, static_cast<unsigned int>(_input->info()->strides_in_bytes()[3]));
     _kernel.setArg<cl_uint>(idx++, static_cast<unsigned int>(_output->info()->strides_in_bytes()[((_num_groups == 1) ? 2 : 3)]));
     do
     {
         unsigned int idx = 0;
         add_3D_tensor_argument(idx, _input, slice_in);
         if(_num_groups == 1)
         {
             add_2D_tensor_argument(idx, _output, slice_out);
         }
         else
         {
             add_3D_tensor_argument(idx, _output, slice_out);
         }
         enqueue(queue, *this, slice, lws_hint());
     }
     while(window_collapsed.slide_window_slice_3D(slice) && window_output.slide_window_slice_2D(slice_out) && window_collapsed.slide_window_slice_3D(slice_in));
 }
References CLIm2ColKernel::_convolved_dims, CLIm2ColKernel::_input, CLIm2ColKernel::_num_elems_processed_per_iteration, CLIm2ColKernel::_num_groups, CLIm2ColKernel::_output, ICLKernel::add_2D_tensor_argument(), ICLKernel::add_3D_tensor_argument(), ARM_COMPUTE_ERROR_ON_MISMATCHING_WINDOWS, ARM_COMPUTE_ERROR_ON_UNCONFIGURED_KERNEL, arm_compute::ceil_to_multiple(), Window::collapse_if_possible(), ITensorInfo::data_layout(), Window::DimX, Window::DimY, Window::DimZ, arm_compute::enqueue(), Window::first_slice_window_2D(), Window::first_slice_window_3D(), ITensor::info(), ICLKernel::lws_hint(), arm_compute::NHWC, ICLKernel::num_arguments_per_2D_tensor(), ICLKernel::num_arguments_per_3D_tensor(), Window::set(), Window::set_dimension_step(), arm_compute::test::validation::reference::slice(), Window::slide_window_slice_2D(), Window::slide_window_slice_3D(), ITensorInfo::strides_in_bytes(), ITensorInfo::tensor_shape(), Window::use_tensor_dimensions(), and IKernel::window().
validate()
Status validate (const ITensorInfo * input, const ITensorInfo * output, const Size2D & kernel_dims, const PadStrideInfo & conv_info, bool has_bias, const Size2D & dilation = Size2D(1U, 1U), unsigned int num_groups = 1) static
Static function to check if given info will lead to a valid configuration of CLIm2ColKernel.
Parameters
[in] input The input tensor to convert. 3 lower dimensions represent a single input [width, height, IFM], while every optional dimension from 4 and above represent a batch of inputs. Data types supported: QASYMM8/F16/F32
[in] output The output tensor. First 2 lower dimensions represent a transform of each 3D input, while every dimension above represents a batch. Data types supported: Same as input
[in] kernel_dims The kernel dimensions (width and height).
[in] conv_info Contains padding and stride information described in PadStrideInfo.
[in] has_bias In case biases are provided expands the matrix with 1.
[in] dilation (Optional) Dilation, in elements, across x and y. Defaults to (1, 1).
[in] num_groups (Optional) Number of groups when performing a grouped convolution. num_groups != 1 is only supported for NCHW data layout
Returns
a status
Definition at line 341 of file CLIm2ColKernel.cpp.
 {
     ARM_COMPUTE_RETURN_ON_ERROR(validate_arguments(input, output, kernel_dims, conv_info, has_bias, dilation, num_groups));
     Im2ColConfiguration im2col_config = configure_opencl_kernel(input, kernel_dims, conv_info, has_bias, dilation, num_groups);
     ARM_COMPUTE_RETURN_ON_ERROR(validate_and_configure_window(input->clone().get(), output->clone().get(), kernel_dims, conv_info, has_bias, dilation, im2col_config.num_elems_processed_per_iteration,
                                                               im2col_config.is_padding_required_nchw, num_groups)
                                 .first);
     return Status{};
 }
References ARM_COMPUTE_RETURN_ON_ERROR, ICloneable< T >::clone(), arm_compute::test::validation::conv_info, and arm_compute::test::validation::dilation.
Referenced by CLLocallyConnectedLayer::validate(), and CLGEMMConvolutionLayer::validate().
Field Documentation
_conv_info
PadStrideInfo _conv_info
Definition at line 109 of file CLIm2ColKernel.h.
Referenced by CLIm2ColKernel::configure().
_convolved_dims
std::pair<unsigned int, unsigned int> _convolved_dims
Definition at line 106 of file CLIm2ColKernel.h.
Referenced by CLIm2ColKernel::configure(), and CLIm2ColKernel::run().
_input
const ICLTensor* _input
Definition at line 104 of file CLIm2ColKernel.h.
Referenced by CLIm2ColKernel::configure(), and CLIm2ColKernel::run().
_kernel_dims
Size2D _kernel_dims
Definition at line 108 of file CLIm2ColKernel.h.
Referenced by CLIm2ColKernel::configure().
_num_elems_processed_per_iteration
unsigned int _num_elems_processed_per_iteration
Definition at line 107 of file CLIm2ColKernel.h.
Referenced by CLIm2ColKernel::configure(), and CLIm2ColKernel::run().
_num_groups
unsigned int _num_groups
Definition at line 110 of file CLIm2ColKernel.h.
Referenced by CLIm2ColKernel::configure(), and CLIm2ColKernel::run().
_output
ICLTensor* _output
Definition at line 105 of file CLIm2ColKernel.h.
Referenced by CLIm2ColKernel::configure(), and CLIm2ColKernel::run().
The documentation for this class was generated from the following files:
arm_compute/core/CL/kernels/CLIm2ColKernel.h
src/core/CL/kernels/CLIm2ColKernel.cpp