Compute Library: ComputeAnchorsInfo Class Reference
ComputeAnchorsInfo Class Reference
ComputeAnchors information class.
#include <Types.h>
Public Member Functions
ComputeAnchorsInfo (float feat_width, float feat_height, float spatial_scale, size_t values_per_roi=4)
Constructor.
float feat_height () const
float feat_width () const
float spatial_scale () const
size_t values_per_roi () const
Detailed Description
ComputeAnchors information class.
Definition at line 1330 of file Types.h.
Constructor & Destructor Documentation
ComputeAnchorsInfo()
ComputeAnchorsInfo (float feat_width, float feat_height, float spatial_scale, size_t values_per_roi = 4) inline
Constructor.
Parameters
[in] feat_width Feature map width
[in] feat_height Feature map height
[in] spatial_scale Feature map scale
[in] values_per_roi (Optional)Values used to represent a ROI(Region Of Interest). Defaults to 4
Definition at line 1340 of file Types.h.
         : _feat_height(feat_height),
           _feat_width(feat_width),
           _spatial_scale(spatial_scale),
           _values_per_roi(values_per_roi)
     {
     }
Member Function Documentation
feat_height()
float feat_height () const inline
Definition at line 1349 of file Types.h.
     {
         return _feat_height;
     }
Referenced by arm_compute::operator<<().
feat_width()
float feat_width () const inline
Definition at line 1355 of file Types.h.
     {
         return _feat_width;
     }
Referenced by arm_compute::operator<<().
spatial_scale()
float spatial_scale () const inline
Definition at line 1361 of file Types.h.
     {
         return _spatial_scale;
     }
Referenced by arm_compute::operator<<().
values_per_roi()
size_t values_per_roi () const inline
Definition at line 1367 of file Types.h.
     {
         return _values_per_roi;
     }
The documentation for this class was generated from the following file:
arm_compute/core/Types.h