Compute Library: GEMMReshapeInfo Class Reference
GEMMReshapeInfo Class Reference final
GEMM reshape information class.
#include <Types.h>
Public Member Functions
GEMMReshapeInfo ()
Default constructor.
GEMMReshapeInfo (int m, int n, int k, int mult_transpose1xW_width=1, int mult_interleave4x4_height=1, int depth_output_gemm3d=0, bool reinterpret_input_as_3d=false)
Constructor.
int m () const
Number of matrix A rows.
int n () const
Number of matrix B columns.
int k () const
Number of matrix A columns or matrix B rows.
int mult_transpose1xW_width () const
Multiplication factor for the width of the 1xW transposed block.
int mult_interleave4x4_height () const
Multiplication factor for the height of the 4x4 interleaved block.
int depth_output_gemm3d () const
Depth (third dimension) of the output tensor to be used with the GEMM3D kernel.
bool reinterpret_input_as_3d () const
Flag which specifies if the input tensor has to be reinterpreted as 3D.
Detailed Description
GEMM reshape information class.
This class stores the necessary information about matrix A and matrix B reshape.
The matrix A can only be reshaped through CLGEMMInterleave4x4Kernel or NEGEMMInterleave4x4Kernel or GCGEMMInterleave4x4Kernel Note: Optionally just for CLGEMMInterleave4x4Kernel is it possible to set mult_interleave4x4_height, the multiplication factor for the height of the 4x4 interleaved block
The matrix B can only be reshaped through CLGEMMReshapeRHSMatrixKernel or NEGEMMTranspose1xWKernel or GCGEMMTranspose1xWKernel Note: Optionally just for CLGEMMReshapeRHSMatrixKernel is it possible to set mult_transpose1xW_width, the multiplication factor for the width of the 1xW transposed block
Definition at line 1653 of file Types.h.
Constructor & Destructor Documentation
GEMMReshapeInfo() [1/2]
GEMMReshapeInfo () inline
Default constructor.
Definition at line 1657 of file Types.h.
         : _m(1), _n(1), _k(1), _mult_transpose1xW_width(1), _mult_interleave4x4_height(1), _depth_output_gemm3d(0), _reinterpret_input_as_3d(false)
     {
     }
GEMMReshapeInfo() [2/2]
GEMMReshapeInfo (int m, int n, int k, int mult_transpose1xW_width = 1, int mult_interleave4x4_height = 1, int depth_output_gemm3d = 0, bool reinterpret_input_as_3d = false) inline
Constructor.
Parameters
[in] m Number of matrix A rows
[in] n Number of matrix B columns
[in] k Number of matrix A columns or matrix B rows
[in] mult_transpose1xW_width (Optional) Multiplication factor for the width of the 1xW transposed block
[in] mult_interleave4x4_height (Optional) Multiplication factor for the height of the 4x4 interleaved block
[in] depth_output_gemm3d (Optional) Depth (third dimension) of the output tensor to be used with the GEMM3D kernel. If 0 the output will not be reinterpreted as 3D. Default 0
[in] reinterpret_input_as_3d (Optional) Reinterpret the input as 3D tensor. (i.e. this flag should be set to true when GEMM is used to perform 1x1 convolutions with the NHWC data layout)
Definition at line 1673 of file Types.h.
         : _m(m), _n(n), _k(k), _mult_transpose1xW_width(mult_transpose1xW_width), _mult_interleave4x4_height(mult_interleave4x4_height), _depth_output_gemm3d(depth_output_gemm3d),
           _reinterpret_input_as_3d(reinterpret_input_as_3d)
     {
     }
Member Function Documentation
depth_output_gemm3d()
int depth_output_gemm3d () const inline
Depth (third dimension) of the output tensor to be used with the GEMM3D kernel.
Note
GEMM3D kernel is used when the output has to be reinterpret as 3D tensor. In that case: m = depth_output_gemm3d * output_height
Returns
the depth of the output tensor to be used with the GEMM3D kernel
Definition at line 1725 of file Types.h.
     {
         return _depth_output_gemm3d;
     }
Referenced by arm_compute::misc::shape_calculator::compute_mm_shape(), CLGEMMLowpMatrixMultiplyReshapedKernel::configure(), CLGEMMMatrixMultiplyReshapedKernel::configure(), and CLGEMMLowpMatrixMultiplyKernel::configure().
k()
int k () const inline
Number of matrix A columns or matrix B rows.
Returns
the number of matrix A columns or matrix B rows
Definition at line 1698 of file Types.h.
     {
         return _k;
     }
Referenced by CLGEMMLowpMatrixMultiplyReshapedKernel::configure(), and CLGEMMMatrixMultiplyReshapedKernel::configure().
m()
int m () const inline
Number of matrix A rows.
Returns
the number of matrix A rows
Definition at line 1682 of file Types.h.
     {
         return _m;
     }
Referenced by arm_compute::misc::shape_calculator::compute_mm_shape(), and NEGEMMMatrixMultiplyKernel::configure().
mult_interleave4x4_height()
int mult_interleave4x4_height () const inline
Multiplication factor for the height of the 4x4 interleaved block.
Returns
the multiplication factor for the height of the 4x4 interleaved block
Definition at line 1714 of file Types.h.
     {
         return _mult_interleave4x4_height;
     }
mult_transpose1xW_width()
int mult_transpose1xW_width () const inline
Multiplication factor for the width of the 1xW transposed block.
Returns
the multiplication factor for the width of the 1xW transposed block
Definition at line 1706 of file Types.h.
     {
         return _mult_transpose1xW_width;
     }
n()
int n () const inline
Number of matrix B columns.
Returns
the number of matrix B columns
Definition at line 1690 of file Types.h.
     {
         return _n;
     }
Referenced by arm_compute::misc::shape_calculator::compute_mm_shape(), and NEGEMMMatrixMultiplyKernel::configure().
reinterpret_input_as_3d()
bool reinterpret_input_as_3d () const inline
Flag which specifies if the input tensor has to be reinterpreted as 3D.
Returns
True if the input tensor has to be reinterpreted as 3D tensor
Definition at line 1733 of file Types.h.
     {
         return _reinterpret_input_as_3d;
     };
Referenced by arm_compute::misc::shape_calculator::compute_mm_shape(), and CLGEMMLowpMatrixMultiplyKernel::configure().
The documentation for this class was generated from the following file:
arm_compute/core/Types.h