Compute Library: SplitLayerSubTensorMutator Class Reference
SplitLayerSubTensorMutator Class Reference final
Mutation pass to optimize split operations by using sub-tensors.
#include <SplitLayerSubTensorMutator.h>
Public Member Functions
virtual void mutate (Graph &g) override
Walk the graph and perform a specific mutation.
const char * name () override
Returns mutator name.
Public Member Functions inherited from IGraphMutator
virtual ~IGraphMutator ()=default
Virtual Destructor.
Detailed Description
Mutation pass to optimize split operations by using sub-tensors.
Warning
This is compulsory to run in case Split layers are present in the model
Definition at line 37 of file SplitLayerSubTensorMutator.h.
Member Function Documentation
mutate()
void mutate (Graph & g) override virtual
Walk the graph and perform a specific mutation.
Parameters
[in,out] g Graph to walk and mutate
Implements IGraphMutator.
Definition at line 45 of file SplitLayerSubTensorMutator.cpp.
 {
     // Early exit if no Split layers exist in graph
     if(g.nodes(NodeType::SplitLayer).empty())
     {
         return;
     }
     // Perform topological sort
     std::vector<NodeID> topological_sorted_node_ids = dfs(g);
     // Should be in reverse order of execution
     for(auto &node_id : arm_compute::utils::iterable::reverse_iterate(topological_sorted_node_ids))
     {
         INode *node = g.node(node_id);
         if(node != nullptr && node->type() == NodeType::SplitLayer && node->input(0) != nullptr)
         {
             // Get output tensor
             Tensor *input_tensor = node->input(0);
             // Check that all tensor have the same target and are valid
             bool is_valid = std::all_of(node->outputs().cbegin(), node->outputs().cend(),
                                         [&](const TensorID & tid)
             {
                 return (g.tensor(tid) != nullptr) && (g.tensor(tid)->desc().target == input_tensor->desc().target);
             });
             // Create subtensors
             if(is_valid && is_target_supported(input_tensor->desc().target))
             {
                 ARM_COMPUTE_LOG_GRAPH_VERBOSE("Using sub-tensors for the node with ID : "
                                               << node->id() << " and name : " << node->name() << std::endl);
                 auto *split_node = arm_compute::utils::cast::polymorphic_downcast<SplitLayerNode *>(node);
                 const unsigned int axis          = split_node->axis();
                 const unsigned int num_splits    = split_node->num_splits();
                 const bool         extend_parent = (axis < 2);
                 // Create sub-tensor handles
                 for(unsigned int i = 0; i < node->outputs().size(); ++i)
                 {
                     Tensor           *output_tensor = node->output(i);
                     const TensorShape output_shape  = output_tensor->desc().shape;
                     Coordinates       coords;
                     std::tie(std::ignore, coords) = SplitLayerNode::compute_output_descriptor(input_tensor->desc(), num_splits, axis, i);
                     backends::IDeviceBackend      &backend = backends::BackendRegistry::get().get_backend(output_tensor->desc().target);
                     std::unique_ptr<ITensorHandle> handle  = backend.create_subtensor(input_tensor->handle(), output_shape, coords, extend_parent);
                     output_tensor->set_handle(std::move(handle));
                 }
             }
         }
     }
 }
References ARM_COMPUTE_LOG_GRAPH_VERBOSE, arm_compute::test::validation::axis, SplitLayerNode::compute_output_descriptor(), IDeviceBackend::create_subtensor(), Tensor::desc(), arm_compute::graph::dfs(), BackendRegistry::get(), BackendRegistry::get_backend(), Tensor::handle(), INode::id(), INode::input(), arm_compute::graph::is_target_supported(), INode::name(), Graph::node(), Graph::nodes(), INode::output(), arm_compute::test::validation::output_shape, INode::outputs(), arm_compute::utils::iterable::reverse_iterate(), Tensor::set_handle(), TensorDescriptor::shape, arm_compute::graph::SplitLayer, TensorDescriptor::target, Graph::tensor(), and INode::type().
name()
const char * name () override virtual
Returns mutator name.
Returns
Mutator name
Implements IGraphMutator.
Definition at line 40 of file SplitLayerSubTensorMutator.cpp.
 {
     return "SplitLayerSubTensorMutator";
 }
The documentation for this class was generated from the following files:
arm_compute/graph/mutators/SplitLayerSubTensorMutator.h
src/graph/mutators/SplitLayerSubTensorMutator.cpp