Compute Library: GCConvolutionLayerReshapeWeights Class Reference
GCConvolutionLayerReshapeWeights Class Reference
Function to reshape and transpose the weights.
#include <GCConvolutionLayer.h>
Public Member Functions
GCConvolutionLayerReshapeWeights ()
Constructor.
void configure (const IGCTensor *weights, const IGCTensor *biases, IGCTensor *output)
Set the input and output tensors.
void run () override
Run the kernels contained in the function.
Public Member Functions inherited from IFunction
virtual ~IFunction ()=default
Destructor.
virtual void prepare ()
Prepare the function for executing.
Detailed Description
Function to reshape and transpose the weights.
This function calls the following kernels:
GCWeightsReshapeKernel
Definition at line 48 of file GCConvolutionLayer.h.
Constructor & Destructor Documentation
GCConvolutionLayerReshapeWeights()
GCConvolutionLayerReshapeWeights ()
Constructor.
Definition at line 39 of file GCConvolutionLayer.cpp.
     : _weights_reshape_kernel()
 {
 }
Member Function Documentation
configure()
void configure (const IGCTensor * weights, const IGCTensor * biases, IGCTensor * output)
Set the input and output tensors.
Parameters
[in] weights Weights tensor. Weights are 4D tensor with dimensions [kernel_x, kernel_y, IFM, OFM]. Data type supported: F16/F32.
[in] biases Biases tensor. Shared biases supported. Biases are 1D tensor with dimensions [OFM]. Data type supported: Same as weights.
[out] output Destination tensor. Data types supported: Same as weights.
Definition at line 44 of file GCConvolutionLayer.cpp.
 {
     ARM_COMPUTE_ERROR_ON_NULLPTR(weights, output);
     ARM_COMPUTE_ERROR_ON_DATA_TYPE_CHANNEL_NOT_IN(weights, 1, DataType::F16, DataType::F32);
     ARM_COMPUTE_ERROR_ON(weights->info()->num_dimensions() > 4);
     if(biases != nullptr)
     {
         ARM_COMPUTE_ERROR_ON(is_data_type_quantized_asymmetric(weights->info()->data_type()));
         ARM_COMPUTE_ERROR_ON_MISMATCHING_DATA_TYPES(weights, biases);
         ARM_COMPUTE_ERROR_ON(biases->info()->dimension(0) != weights->info()->dimension(3));
         ARM_COMPUTE_ERROR_ON(biases->info()->num_dimensions() > 1);
     }
     const bool       append_biases = (biases != nullptr) && !is_data_type_quantized_asymmetric(weights->info()->data_type());
     const IGCTensor *biases_to_use = (append_biases) ? biases : nullptr;
     _weights_reshape_kernel.configure(weights, biases_to_use, output);
 }
References ARM_COMPUTE_ERROR_ON, ARM_COMPUTE_ERROR_ON_DATA_TYPE_CHANNEL_NOT_IN, ARM_COMPUTE_ERROR_ON_MISMATCHING_DATA_TYPES, ARM_COMPUTE_ERROR_ON_NULLPTR, GCWeightsReshapeKernel::configure(), TensorInfo::data_type(), ITensorInfo::dimension(), TensorInfo::dimension(), arm_compute::F16, arm_compute::F32, ITensor::info(), CLTensor::info(), arm_compute::is_data_type_quantized_asymmetric(), ITensorInfo::num_dimensions(), TensorInfo::num_dimensions(), and arm_compute::test::validation::weights.
Referenced by GCConvolutionLayer::configure().
run()
void run () override virtual
Run the kernels contained in the function.
For NEON kernels:
Multi-threading is used for the kernels which are parallelisable.
By default std::thread::hardware_concurrency() threads are used.
Note
CPPScheduler::set_num_threads() can be used to manually set the number of threads
For OpenCL kernels:
All the kernels are enqueued on the queue associated with CLScheduler.
The queue is then flushed.
Note
The function will not block until the kernels are executed. It is the user's responsibility to wait.
Will call prepare() on first run if hasn't been done
Implements IFunction.
Definition at line 64 of file GCConvolutionLayer.cpp.
 {
     GCScheduler::get().dispatch(_weights_reshape_kernel);
 }
References GCScheduler::dispatch(), and GCScheduler::get().
Referenced by GCConvolutionLayer::prepare().
The documentation for this class was generated from the following files:
arm_compute/runtime/GLES_COMPUTE/functions/GCConvolutionLayer.h
src/runtime/GLES_COMPUTE/functions/GCConvolutionLayer.cpp