Compute Library: JPEGLoader Class Reference
JPEGLoader Class Reference
Class to load the content of a JPEG file into an Image.
#include <ImageLoader.h>
Public Member Functions
JPEGLoader ()
Default Constructor.
bool is_open () override
Return true if the image file is currently open.
void open (const std::string &filename) override
Open an image file and reads its metadata (Width, height)
void close () override
Closes an image file.
void release ()
Explicitly Releases the memory of the loaded data.
Public Member Functions inherited from IImageLoader
IImageLoader ()
Default Constructor.
virtual ~IImageLoader ()=default
Virtual base destructor.
unsigned int width () const
Return the width of the currently open image file.
unsigned int height () const
Return the height of the currently open image file.
template<typename T >
void init_image (T &image, Format format)
Initialise an image's metadata with the dimensions of the image file currently open.
template<typename T >
void fill_image (T &image)
Fill an image with the content of the currently open image file.
template<typename T >
void fill_planar_tensor (T &tensor, bool bgr=false)
Fill a tensor with 3 planes (one for each channel) with the content of the currently open image file.
Detailed Description
Class to load the content of a JPEG file into an Image.
Definition at line 422 of file ImageLoader.h.
Constructor & Destructor Documentation
JPEGLoader()
JPEGLoader () inline
Default Constructor.
Definition at line 436 of file ImageLoader.h.
         : IImageLoader(), _is_loaded(false), _data(nullptr)
     {
     }
Member Function Documentation
close()
void close () inline override virtual
Closes an image file.
Implements IImageLoader.
Definition at line 463 of file ImageLoader.h.
     {
         if(is_open())
         {
             _width  = 0;
             _height = 0;
             release();
         }
         ARM_COMPUTE_ERROR_ON(is_open());
     }
References ARM_COMPUTE_ERROR_ON, JPEGLoader::is_open(), and JPEGLoader::release().
is_open()
bool is_open () inline override virtual
Return true if the image file is currently open.
Implements IImageLoader.
Definition at line 442 of file ImageLoader.h.
     {
         return _is_loaded;
     }
Referenced by JPEGLoader::close().
open()
void open (const std::string & filename) inline override virtual
Open an image file and reads its metadata (Width, height)
Parameters
[in] filename File to open
Implements IImageLoader.
Definition at line 446 of file ImageLoader.h.
     {
         int      bpp, width, height;
         uint8_t *rgb_image = stbi_load(filename.c_str(), &width, &height, &bpp, 3);
         if(rgb_image == NULL)
         {
             ARM_COMPUTE_ERROR("Accessing %s failed", filename.c_str());
         }
         else
         {
             _width     = width;
             _height    = height;
             _data      = std::unique_ptr<uint8_t, malloc_deleter>(rgb_image);
             _is_loaded = true;
             _feeder    = support::cpp14::make_unique<MemoryImageFeeder>(_data.get());
         }
     }
References ARM_COMPUTE_ERROR, IImageLoader::height(), and IImageLoader::width().
Referenced by ValidationInputAccessor::access_tensor().
release()
void release (void) inline
Explicitly Releases the memory of the loaded data.
Definition at line 474 of file ImageLoader.h.
     {
         if(_is_loaded)
         {
             _data.reset();
             _is_loaded = false;
             _feeder    = nullptr;
         }
     }
Referenced by JPEGLoader::close().
The documentation for this class was generated from the following file:
utils/ImageLoader.h