Compute Library: CLHOGDetector Class Reference
CLHOGDetector Class Reference
Basic function to execute HOG detector based on linear SVM.
#include <CLHOGDetector.h>
Public Member Functions
CLHOGDetector ()
Default constructor.
CLHOGDetector (const CLHOGDetector &)=delete
Prevent instances of this class from being copied (As this class contains pointers)
CLHOGDetector & operator= (const CLHOGDetector &)=delete
Prevent instances of this class from being copied (As this class contains pointers)
CLHOGDetector (CLHOGDetector &&)=default
Allow instances of this class to be moved.
CLHOGDetector & operator= (CLHOGDetector &&)=default
Allow instances of this class to be moved.
~CLHOGDetector ()=default
Default destructor.
void configure (const ICLTensor *input, const ICLHOG *hog, ICLDetectionWindowArray *detection_windows, const Size2D &detection_window_stride, float threshold=0.0f, size_t idx_class=0)
Initialise the kernel's input, output, HOG data object, detection window stride, threshold and index class.
void run () override
Run the kernels contained in the function.
Public Member Functions inherited from IFunction
virtual ~IFunction ()=default
Destructor.
virtual void prepare ()
Prepare the function for executing.
Detailed Description
Basic function to execute HOG detector based on linear SVM.
This function calls the following OpenCL kernel:
CLHOGDetectorKernel
Definition at line 39 of file CLHOGDetector.h.
Constructor & Destructor Documentation
CLHOGDetector() [1/3]
CLHOGDetector ()
Default constructor.
Definition at line 34 of file CLHOGDetector.cpp.
     : _hog_detector_kernel(), _detection_windows(nullptr), _num_detection_windows()
 {
 }
CLHOGDetector() [2/3]
CLHOGDetector (const CLHOGDetector &) delete
Prevent instances of this class from being copied (As this class contains pointers)
CLHOGDetector() [3/3]
CLHOGDetector (CLHOGDetector &&) default
Allow instances of this class to be moved.
~CLHOGDetector()
~CLHOGDetector () default
Default destructor.
Member Function Documentation
configure()
void configure (const ICLTensor * input, const ICLHOG * hog, ICLDetectionWindowArray * detection_windows, const Size2D & detection_window_stride, float threshold = 0.0f, size_t idx_class = 0)
Initialise the kernel's input, output, HOG data object, detection window stride, threshold and index class.
Attention
The function does not reset the number of values in IDetectionWindowArray so it is caller's responsibility to clear it.
Parameters
[in] input Input tensor. It is the output of CLHOGDescriptor. Data type supported: F32
[in] hog HOG data-object that describes the HOG descriptor
[out] detection_windows Array of DetectionWindow used to store the detected objects
[in] detection_window_stride Distance in pixels between 2 consecutive detection windows in x and y directions. It must be multiple of the block stride stored in hog
[in] threshold (Optional) Threshold for the distance between features and SVM classifying plane
[in] idx_class (Optional) Index of the class used for evaluating which class the detection window belongs to
Definition at line 39 of file CLHOGDetector.cpp.
 {
     _detection_windows = detection_windows;
     // Allocate buffer for storing the number of detected objects
     _num_detection_windows = cl::Buffer(CLScheduler::get().context(), CL_MEM_ALLOC_HOST_PTR | CL_MEM_READ_WRITE, sizeof(unsigned int));
     // Configure HOGDetectorKernel
     _hog_detector_kernel.configure(input, hog, detection_windows, &_num_detection_windows, detection_window_stride, threshold, idx_class);
 }
References CLHOGDetectorKernel::configure(), CLScheduler::get(), and arm_compute::test::validation::reference::threshold().
operator=() [1/2]
CLHOGDetector& operator= (const CLHOGDetector &) delete
Prevent instances of this class from being copied (As this class contains pointers)
operator=() [2/2]
CLHOGDetector& operator= (CLHOGDetector &&) default
Allow instances of this class to be moved.
run()
void run () override virtual
Run the kernels contained in the function.
For NEON kernels:
Multi-threading is used for the kernels which are parallelisable.
By default std::thread::hardware_concurrency() threads are used.
Note
CPPScheduler::set_num_threads() can be used to manually set the number of threads
For OpenCL kernels:
All the kernels are enqueued on the queue associated with CLScheduler.
The queue is then flushed.
Note
The function will not block until the kernels are executed. It is the user's responsibility to wait.
Will call prepare() on first run if hasn't been done
Implements IFunction.
Definition at line 50 of file CLHOGDetector.cpp.
 {
     cl::CommandQueue q = CLScheduler::get().queue();
     // Reset number of detections
     const unsigned int init_num_detection_windows = _detection_windows->num_values();
     q.enqueueWriteBuffer(_num_detection_windows, CL_FALSE, 0, sizeof(unsigned int), &init_num_detection_windows);
     // Run CLHOGDetectorKernel
     CLScheduler::get().enqueue(_hog_detector_kernel);
     // Read number of detections
     unsigned int num_detection_windows = 0;
     q.enqueueReadBuffer(_num_detection_windows, CL_TRUE, 0, sizeof(unsigned int), &num_detection_windows);
     // Update the number of values stored in _detection_windows
     _detection_windows->resize(static_cast<size_t>(num_detection_windows));
     q.flush();
 }
References CLScheduler::enqueue(), CLScheduler::get(), IArray< T >::num_values(), CLScheduler::queue(), and IArray< T >::resize().
The documentation for this class was generated from the following files:
arm_compute/runtime/CL/functions/CLHOGDetector.h
src/runtime/CL/functions/CLHOGDetector.cpp