Compute Library: GCAccessor Class Reference
GCAccessor Class Reference
Accessor implementation for GCTensor objects.
#include <GCAccessor.h>
Public Member Functions
GCAccessor (GCTensor &tensor)
Create an accessor for the given tensor.
GCAccessor (const GCAccessor &)=delete
Prevent instances of this class from being copy constructed.
GCAccessor & operator= (const GCAccessor &)=delete
Prevent instances of this class from being copied.
GCAccessor (GCAccessor &&)=default
Allow instances of this class to be move constructed.
GCAccessor & operator= (GCAccessor &&)=default
Allow instances of this class to be moved.
~GCAccessor ()
Destructor that unmaps the GLES memory.
TensorShape shape () const override
Shape of the tensor.
size_t element_size () const override
Size of each element in the tensor in bytes.
size_t size () const override
Total size of the tensor in bytes.
Format format () const override
Image format of the tensor.
DataLayout data_layout () const override
Data layout of the tensor.
DataType data_type () const override
Data type of the tensor.
int num_channels () const override
Number of channels of the tensor.
int num_elements () const override
Number of elements of the tensor.
PaddingSize padding () const override
Available padding around the tensor.
QuantizationInfo quantization_info () const override
Quantization info in case of asymmetric quantized type.
const void * operator() (const Coordinates &coord) const override
Read only access to the specified element.
void * operator() (const Coordinates &coord) override
Access to the specified element.
Public Member Functions inherited from IAccessor
virtual ~IAccessor ()=default
Virtual destructor.
Detailed Description
Accessor implementation for GCTensor objects.
Definition at line 35 of file GCAccessor.h.
Constructor & Destructor Documentation
GCAccessor() [1/3]
GCAccessor (GCTensor & tensor) inline
Create an accessor for the given tensor.
Parameters
[in,out] tensor To be accessed tensor.
Note
The GLES memory is mapped by the constructor.
Definition at line 76 of file GCAccessor.h.
     : _tensor{ tensor }
 {
     _tensor.map();
 }
GCAccessor() [2/3]
GCAccessor (const GCAccessor &) delete
Prevent instances of this class from being copy constructed.
GCAccessor() [3/3]
GCAccessor (GCAccessor &&) default
Allow instances of this class to be move constructed.
~GCAccessor()
~GCAccessor () inline
Destructor that unmaps the GLES memory.
Definition at line 82 of file GCAccessor.h.
 {
     _tensor.unmap();
 }
References GCTensor::unmap().
Member Function Documentation
data_layout()
DataLayout data_layout () const inline override virtual
Data layout of the tensor.
Returns
the data layout of the tensor.
Implements IAccessor.
Definition at line 107 of file GCAccessor.h.
 {
     return _tensor.info()->data_layout();
 }
References TensorInfo::data_layout(), and GCTensor::info().
data_type()
DataType data_type () const inline override virtual
Data type of the tensor.
Returns
the data type of the tensor.
Implements IAccessor.
Definition at line 112 of file GCAccessor.h.
 {
     return _tensor.info()->data_type();
 }
References TensorInfo::data_type(), and GCTensor::info().
element_size()
size_t element_size () const inline override virtual
Size of each element in the tensor in bytes.
Returns
the size of each element in the tensor in bytes.
Implements IAccessor.
Definition at line 92 of file GCAccessor.h.
 {
     return _tensor.info()->element_size();
 }
References TensorInfo::element_size(), and GCTensor::info().
format()
Format format () const inline override virtual
Image format of the tensor.
Returns
the format of the tensor.
Implements IAccessor.
Definition at line 102 of file GCAccessor.h.
 {
     return _tensor.info()->format();
 }
References TensorInfo::format(), and GCTensor::info().
num_channels()
int num_channels () const inline override virtual
Number of channels of the tensor.
Returns
the number of channels of the tensor.
Implements IAccessor.
Definition at line 117 of file GCAccessor.h.
 {
     return _tensor.info()->num_channels();
 }
References GCTensor::info(), and TensorInfo::num_channels().
num_elements()
int num_elements () const inline override virtual
Number of elements of the tensor.
Returns
the number of elements of the tensor.
Implements IAccessor.
Definition at line 122 of file GCAccessor.h.
 {
     return _tensor.info()->tensor_shape().total_size();
 }
References GCTensor::info(), TensorInfo::tensor_shape(), and TensorShape::total_size().
operator()() [1/2]
const void * operator() (const Coordinates & coord) const inline override virtual
Read only access to the specified element.
Parameters
[in] coord Coordinates of the desired element.
Returns
A pointer to the desired element.
Implements IAccessor.
Definition at line 137 of file GCAccessor.h.
 {
     return _tensor.ptr_to_element(coord);
 }
References ITensor::ptr_to_element().
operator()() [2/2]
void * operator() (const Coordinates & coord) inline override virtual
Access to the specified element.
Parameters
[in] coord Coordinates of the desired element.
Returns
A pointer to the desired element.
Implements IAccessor.
Definition at line 142 of file GCAccessor.h.
 {
     return _tensor.ptr_to_element(coord);
 }
References ITensor::ptr_to_element().
operator=() [1/2]
GCAccessor& operator= (const GCAccessor &) delete
Prevent instances of this class from being copied.
operator=() [2/2]
GCAccessor& operator= (GCAccessor &&) default
Allow instances of this class to be moved.
padding()
PaddingSize padding () const inline override virtual
Available padding around the tensor.
Returns
the available padding around the tensor.
Implements IAccessor.
Definition at line 127 of file GCAccessor.h.
 {
     return _tensor.info()->padding();
 }
References GCTensor::info(), and TensorInfo::padding().
quantization_info()
QuantizationInfo quantization_info () const inline override virtual
Quantization info in case of asymmetric quantized type.
Returns
Implements IAccessor.
Definition at line 132 of file GCAccessor.h.
 {
     return _tensor.info()->quantization_info();
 }
References GCTensor::info(), and TensorInfo::quantization_info().
shape()
TensorShape shape () const inline override virtual
Shape of the tensor.
Returns
the shape of the tensor.
Implements IAccessor.
Definition at line 87 of file GCAccessor.h.
 {
     return _tensor.info()->tensor_shape();
 }
References GCTensor::info(), and TensorInfo::tensor_shape().
size()
size_t size () const inline override virtual
Total size of the tensor in bytes.
Returns
the total size of the tensor in bytes.
Implements IAccessor.
Definition at line 97 of file GCAccessor.h.
 {
     return _tensor.info()->total_size();
 }
References GCTensor::info(), and TensorInfo::total_size().
The documentation for this class was generated from the following file:
tests/GLES_COMPUTE/GCAccessor.h