Compute Library: NEDilateKernel Class Reference
NEDilateKernel Class Reference
Interface for the kernel to perform boolean image dilatation.
#include <NEDilateKernel.h>
Public Member Functions
const char * name () const override
Name of the kernel.
void configure (const ITensor *input, ITensor *output, bool border_undefined)
Set the source, destination and border mode of the kernel.
void run (const Window &window, const ThreadInfo &info) override
Execute the kernel on the passed window.
BorderSize border_size () const override
The size of the border for that kernel.
Public Member Functions inherited from ICPPSimpleKernel
ICPPSimpleKernel ()
Constructor.
ICPPSimpleKernel (const ICPPSimpleKernel &)=delete
Prevent instances of this class from being copied (As this class contains pointers)
ICPPSimpleKernel & operator= (const ICPPSimpleKernel &)=delete
Prevent instances of this class from being copied (As this class contains pointers)
ICPPSimpleKernel (ICPPSimpleKernel &&)=default
Allow instances of this class to be moved.
ICPPSimpleKernel & operator= (ICPPSimpleKernel &&)=default
Allow instances of this class to be moved.
~ICPPSimpleKernel ()=default
Default destructor.
Public Member Functions inherited from ICPPKernel
virtual ~ICPPKernel ()=default
Default destructor.
Public Member Functions inherited from IKernel
IKernel ()
Constructor.
virtual ~IKernel ()=default
Destructor.
virtual bool is_parallelisable () const
Indicates whether or not the kernel is parallelisable.
const Window & window () const
The maximum window the kernel can be executed on.
Detailed Description
Interface for the kernel to perform boolean image dilatation.
Definition at line 34 of file NEDilateKernel.h.
Member Function Documentation
border_size()
BorderSize border_size () const override virtual
The size of the border for that kernel.
Returns
The width in number of elements of the border.
Reimplemented from IKernel.
Definition at line 43 of file NEDilateKernel.cpp.
 {
     return BorderSize(1);
 }
Referenced by NEDilateKernel::configure().
configure()
void configure (const ITensor * input, ITensor * output, bool border_undefined)
Set the source, destination and border mode of the kernel.
Parameters
[in] input Source tensor. Data type supported: U8
[out] output Destination tensor. Data type supported: U8
[in] border_undefined True if the border mode is undefined. False if it's replicate or constant.
Definition at line 48 of file NEDilateKernel.cpp.
 {
     _input  = input;
     _output = output;
     constexpr unsigned int num_elems_processed_per_iteration = 8;
     constexpr unsigned int num_elems_read_per_iteration      = 16;
     constexpr unsigned int num_elems_written_per_iteration   = 8;
     constexpr unsigned int num_rows_read_per_iteration       = 3;
     // Configure kernel window
     Window                 win = calculate_max_window(*input->info(), Steps(num_elems_processed_per_iteration), border_undefined, border_size());
     AccessWindowHorizontal output_access(output->info(), 0, num_elems_written_per_iteration);
     AccessWindowRectangle  input_access(input->info(), -border_size().left, -border_size().top, num_elems_read_per_iteration, num_rows_read_per_iteration);
     update_window_and_padding(win, input_access, output_access);
     output_access.set_valid_region(win, input->info()->valid_region(), border_undefined, border_size());
     INEKernel::configure(win);
 }
References NEDilateKernel::border_size(), arm_compute::calculate_max_window(), ITensor::info(), BorderSize::left, BorderSize::top, arm_compute::update_window_and_padding(), and ITensorInfo::valid_region().
name()
const char* name () const inline override virtual
Name of the kernel.
Returns
Kernel name
Implements ICPPKernel.
Definition at line 37 of file NEDilateKernel.h.
     {
         return "NEDilateKernel";
     }
run()
void run (const Window & window, const ThreadInfo & info) override virtual
Execute the kernel on the passed window.
Warning
If is_parallelisable() returns false then the passed window must be equal to window()
Note
The window has to be a region within the window returned by the window() method
The width of the window has to be a multiple of num_elems_processed_per_iteration().
Parameters
[in] window Region on which to execute the kernel. (Must be a region of the window returned by window())
[in] info Info about executing thread and CPU.
Implements ICPPKernel.
Definition at line 70 of file NEDilateKernel.cpp.
 {
     ARM_COMPUTE_UNUSED(info);
     ARM_COMPUTE_ERROR_ON_UNCONFIGURED_KERNEL(this);
     ARM_COMPUTE_ERROR_ON_INVALID_SUBWINDOW(INESimpleKernel::window(), window);
     Iterator in(_input, window);
     Iterator out(_output, window);
     const size_t in_stride = _input->info()->strides_in_bytes()[1];
     execute_window_loop(window, [&](const Coordinates &)
     {
         uint8_t         *in_ptr   = in.ptr() - 1;
         const uint8x16_t top_data = vld1q_u8(in_ptr - in_stride);
         const uint8x16_t mid_data = vld1q_u8(in_ptr);
         const uint8x16_t bot_data = vld1q_u8(in_ptr + in_stride);
         uint8x8_t top_high_data = vget_high_u8(top_data);
         uint8x8_t top_low_data  = vget_low_u8(top_data);
         uint8x8_t mid_high_data = vget_high_u8(mid_data);
         uint8x8_t mid_low_data  = vget_low_u8(mid_data);
         uint8x8_t bot_high_data = vget_high_u8(bot_data);
         uint8x8_t bot_low_data  = vget_low_u8(bot_data);
         uint8x8_t p0, p1;
         p0 = top_low_data;
         p1 = vext_u8(top_low_data, top_high_data, 1);
         p0 = vmax_u8(p0, p1);
         p1 = vext_u8(top_low_data, top_high_data, 2);
         p0 = vmax_u8(p0, p1);
         p1 = mid_low_data;
         p0 = vmax_u8(p0, p1);
         p1 = vext_u8(mid_low_data, mid_high_data, 1);
         p0 = vmax_u8(p0, p1);
         p1 = vext_u8(mid_low_data, mid_high_data, 2);
         p0 = vmax_u8(p0, p1);
         p1 = bot_low_data;
         p0 = vmax_u8(p0, p1);
         p1 = vext_u8(bot_low_data, bot_high_data, 1);
         p0 = vmax_u8(p0, p1);
         p1 = vext_u8(bot_low_data, bot_high_data, 2);
         p0 = vmax_u8(p0, p1);
         vst1_u8(out.ptr(), p0);
     },
     in, out);
 }
References ARM_COMPUTE_ERROR_ON_INVALID_SUBWINDOW, ARM_COMPUTE_ERROR_ON_UNCONFIGURED_KERNEL, ARM_COMPUTE_UNUSED, arm_compute::execute_window_loop(), arm_compute::test::validation::info, Iterator::ptr(), and IKernel::window().
The documentation for this class was generated from the following files:
arm_compute/core/NEON/kernels/NEDilateKernel.h
src/core/NEON/kernels/NEDilateKernel.cpp