Compute Library: PMU Class Reference
PMU Class Reference
Class provides access to CPU hardware counters.
#include <PMU.h>
Public Member Functions
PMU ()
Default constructor.
PMU (uint64_t config)
Create PMU with specified counter.
~PMU ()
Default destructor.
template<typename T >
T get_value () const
Get the counter value.
void open (uint64_t config)
Open the specified counter based on the default configuration.
void open (const perf_event_attr &perf_config)
Open the specified configuration.
void close ()
Close the currently open counter.
void reset ()
Reset counter.
Detailed Description
Class provides access to CPU hardware counters.
Definition at line 43 of file PMU.h.
Constructor & Destructor Documentation
PMU() [1/2]
PMU ()
Default constructor.
Definition at line 37 of file PMU.cpp.
     : _perf_config()
 {
     _perf_config.type = PERF_TYPE_HARDWARE;
     _perf_config.size = sizeof(perf_event_attr);
     // Start disabled
     _perf_config.disabled = 1;
     // The inherit bit specifies that this counter should count events of child
     // tasks as well as the task specified
     _perf_config.inherit = 1;
     // Enables saving of event counts on context switch for inherited tasks
     _perf_config.inherit_stat = 1;
 }
PMU() [2/2]
PMU (uint64_t config) explicit
Create PMU with specified counter.
This constructor automatically calls open with the default configuration.
Parameters
[in] config Counter identifier.
Definition at line 52 of file PMU.cpp.
     : PMU()
 {
     open(config);
 }
References PMU::open().
~PMU()
~PMU ()
Default destructor.
Definition at line 58 of file PMU.cpp.
 {
     close();
 }
References PMU::close().
Member Function Documentation
close()
void close ()
Close the currently open counter.
Definition at line 83 of file PMU.cpp.
 {
     if(_fd != -1)
     {
         ::close(_fd);
         _fd = -1;
     }
 }
Referenced by PMU::~PMU().
get_value()
T get_value () const
Get the counter value.
Returns
Counter value casted to the specified type.
Definition at line 91 of file PMU.h.
 {
     T             value{};
     const ssize_t result = read(_fd, &value, sizeof(T));
     if(result == -1)
     {
         ARM_COMPUTE_ERROR("Can't get PMU counter value: %d", errno);
     }
     return value;
 }
Referenced by PMUCounter::stop().
open() [1/2]
void open (uint64_t config)
Open the specified counter based on the default configuration.
Parameters
[in] config The default configuration.
Definition at line 63 of file PMU.cpp.
 {
     _perf_config.config = config;
     open(_perf_config);
 }
Referenced by PMU::PMU().
open() [2/2]
void open (const perf_event_attr & perf_config)
Open the specified configuration.
Parameters
[in] perf_config The specified configuration.
Definition at line 69 of file PMU.cpp.
 {
     // Measure this process/thread (+ children) on any CPU
     _fd = syscall(__NR_perf_event_open, &perf_config, 0, -1, -1, 0);
     ARM_COMPUTE_ERROR_ON_MSG(_fd < 0, "perf_event_open failed");
     const int result = ioctl(_fd, PERF_EVENT_IOC_ENABLE, 0);
     if(result == -1)
     {
         ARM_COMPUTE_ERROR("Failed to enable PMU counter: %d", errno);
     }
 }
References ARM_COMPUTE_ERROR, and ARM_COMPUTE_ERROR_ON_MSG.
reset()
void reset ()
Reset counter.
Definition at line 92 of file PMU.cpp.
 {
     const int result = ioctl(_fd, PERF_EVENT_IOC_RESET, 0);
     if(result == -1)
     {
         ARM_COMPUTE_ERROR("Failed to reset PMU counter: %d", errno);
     }
 }
References ARM_COMPUTE_ERROR.
Referenced by PMUCounter::start().
The documentation for this class was generated from the following files:
tests/framework/instruments/PMU.h
tests/framework/instruments/PMU.cpp