Compute Library: CPPFlipWeightsKernel Class Reference
CPPFlipWeightsKernel Class Reference
CPP kernel to perform 180 degrees flipping on deconvolution weights.
#include <CPPFlipWeightsKernel.h>
Public Types
using FlipWeightsFunction = void(CPPFlipWeightsKernel::*)(const Window &window_input)
Common signature for all the specialised Flip functions.
Public Member Functions
const char * name () const override
Name of the kernel.
CPPFlipWeightsKernel ()
Default constructor.
CPPFlipWeightsKernel (const CPPFlipWeightsKernel &)=delete
Prevent instances of this class from being copied (As this class contains pointers)
CPPFlipWeightsKernel & operator= (const CPPFlipWeightsKernel &)=delete
Prevent instances of this class from being copied (As this class contains pointers)
CPPFlipWeightsKernel (CPPFlipWeightsKernel &&)=default
Allow instances of this class to be moved.
CPPFlipWeightsKernel & operator= (CPPFlipWeightsKernel &&)=default
Allow instances of this class to be moved.
~CPPFlipWeightsKernel ()=default
Default destructor.
void configure (const ITensor *input, ITensor *output)
Set the input and output of the kernel.
void run (const Window &window, const ThreadInfo &info) override
Execute the kernel on the passed window.
template<typename T >
void flip_weights (const Window &window_input)
Function to perform flipping.
Public Member Functions inherited from ICPPKernel
virtual ~ICPPKernel ()=default
Default destructor.
Public Member Functions inherited from IKernel
IKernel ()
Constructor.
virtual ~IKernel ()=default
Destructor.
virtual bool is_parallelisable () const
Indicates whether or not the kernel is parallelisable.
virtual BorderSize border_size () const
The size of the border for that kernel.
const Window & window () const
The maximum window the kernel can be executed on.
Detailed Description
CPP kernel to perform 180 degrees flipping on deconvolution weights.
Definition at line 34 of file CPPFlipWeightsKernel.h.
Member Typedef Documentation
FlipWeightsFunction
using FlipWeightsFunction = void (CPPFlipWeightsKernel::*)(const Window &window_input)
Common signature for all the specialised Flip functions.
Parameters
[in] window_input Input region on which to execute the kernel.
Definition at line 75 of file CPPFlipWeightsKernel.h.
Constructor & Destructor Documentation
CPPFlipWeightsKernel() [1/3]
CPPFlipWeightsKernel ()
Default constructor.
Definition at line 39 of file CPPFlipWeightsKernel.cpp.
     : _input(nullptr), _output(nullptr), _func(nullptr)
 {
 }
CPPFlipWeightsKernel() [2/3]
CPPFlipWeightsKernel (const CPPFlipWeightsKernel &) delete
Prevent instances of this class from being copied (As this class contains pointers)
CPPFlipWeightsKernel() [3/3]
CPPFlipWeightsKernel (CPPFlipWeightsKernel &&) default
Allow instances of this class to be moved.
~CPPFlipWeightsKernel()
~CPPFlipWeightsKernel () default
Default destructor.
Member Function Documentation
configure()
void configure (const ITensor * input, ITensor * output)
Set the input and output of the kernel.
Parameters
[in] input The input tensor to flip. Data types supported: QASYMM8/F16/F32. Data layouts supported: NCHW/NHWC.
[out] output The output tensor. Data types supported: Same as input
Definition at line 69 of file CPPFlipWeightsKernel.cpp.
 {
     ARM_COMPUTE_ERROR_ON_NULLPTR(input, output);
     ARM_COMPUTE_ERROR_ON_DATA_TYPE_CHANNEL_NOT_IN(input, 1, DataType::QASYMM8, DataType::F16, DataType::F32);
     ARM_COMPUTE_ERROR_ON_MISMATCHING_DATA_LAYOUT(input, output);
     ARM_COMPUTE_ERROR_ON_MISMATCHING_DATA_TYPES(input, output);
     _input  = input;
     _output = output;
     // Configure kernel window
     Window win = calculate_max_window(*input->info(), Steps());
     // The CPPFlipWeightsKernel doesn't need padding so update_window_and_padding() can be skipped
     Coordinates coord;
     coord.set_num_dimensions(output->info()->num_dimensions());
     output->info()->set_valid_region(ValidRegion(coord, output->info()->tensor_shape()));
     ICPPKernel::configure(win);
     switch(input->info()->data_type())
     {
         case DataType::F32:
             _func = &CPPFlipWeightsKernel::flip_weights<float>;
             break;
         case DataType::F16:
             _func = &CPPFlipWeightsKernel::flip_weights<half>;
             break;
         case DataType::QASYMM8:
             _func = &CPPFlipWeightsKernel::flip_weights<uint8_t>;
             break;
         default:
             ARM_COMPUTE_ERROR("Not supported");
     }
 }
References ARM_COMPUTE_ERROR, ARM_COMPUTE_ERROR_ON_DATA_TYPE_CHANNEL_NOT_IN, ARM_COMPUTE_ERROR_ON_MISMATCHING_DATA_LAYOUT, ARM_COMPUTE_ERROR_ON_MISMATCHING_DATA_TYPES, ARM_COMPUTE_ERROR_ON_NULLPTR, arm_compute::calculate_max_window(), ITensorInfo::data_type(), arm_compute::F16, arm_compute::F32, ITensor::info(), ITensorInfo::num_dimensions(), arm_compute::QASYMM8, Dimensions< T >::set_num_dimensions(), ITensorInfo::set_valid_region(), and ITensorInfo::tensor_shape().
Referenced by CLDeconvolutionLayer::configure(), and NEDeconvolutionLayer::configure().
flip_weights()
void flip_weights (const Window & window_input)
Function to perform flipping.
Parameters
[in] window_input Input region on which to execute the kernel.
Definition at line 45 of file CPPFlipWeightsKernel.cpp.
 {
     // Create iterators
     Iterator in(_input, window_input);
     const DataLayout data_layout = _input->info()->data_layout();
     const size_t     idx_w       = get_data_layout_dimension_index(data_layout, DataLayoutDimension::WIDTH);
     const size_t     idx_h       = get_data_layout_dimension_index(data_layout, DataLayoutDimension::HEIGHT);
     const int kernel_width  = _input->info()->dimension(idx_w);
     const int kernel_height = _input->info()->dimension(idx_h);
     execute_window_loop(window_input, [&](const Coordinates & id)
     {
         const unsigned int x = kernel_width - id[idx_w] - 1;
         const unsigned int y = kernel_height - id[idx_h] - 1;
         Coordinates        output_coord(id);
         output_coord.set(idx_w, x);
         output_coord.set(idx_h, y);
         *(reinterpret_cast<T *>(_output->ptr_to_element(output_coord))) = *(reinterpret_cast<const T *>(in.ptr()));
     },
     in);
 }
References ITensorInfo::data_layout(), ITensorInfo::dimension(), arm_compute::execute_window_loop(), arm_compute::get_data_layout_dimension_index(), arm_compute::HEIGHT, ITensor::info(), Iterator::ptr(), ITensor::ptr_to_element(), Dimensions< T >::set(), and arm_compute::WIDTH.
name()
const char* name () const inline override virtual
Name of the kernel.
Returns
Kernel name
Implements ICPPKernel.
Definition at line 37 of file CPPFlipWeightsKernel.h.
     {
         return "CPPFlipWeightsKernel";
     }
operator=() [1/2]
CPPFlipWeightsKernel& operator= (const CPPFlipWeightsKernel &) delete
Prevent instances of this class from being copied (As this class contains pointers)
operator=() [2/2]
CPPFlipWeightsKernel& operator= (CPPFlipWeightsKernel &&) default
Allow instances of this class to be moved.
run()
void run (const Window & window, const ThreadInfo & info) override virtual
Execute the kernel on the passed window.
Warning
If is_parallelisable() returns false then the passed window must be equal to window()
Note
The window has to be a region within the window returned by the window() method
The width of the window has to be a multiple of num_elems_processed_per_iteration().
Parameters
[in] window Region on which to execute the kernel. (Must be a region of the window returned by window())
[in] info Info about executing thread and CPU.
Implements ICPPKernel.
Definition at line 105 of file CPPFlipWeightsKernel.cpp.
 {
     ARM_COMPUTE_UNUSED(info);
     ARM_COMPUTE_ERROR_ON_UNCONFIGURED_KERNEL(this);
     ARM_COMPUTE_ERROR_ON_INVALID_SUBWINDOW(ICPPKernel::window(), window);
     ARM_COMPUTE_ERROR_ON(_func == nullptr);
     (this->*_func)(window);
 }
References ARM_COMPUTE_ERROR_ON, ARM_COMPUTE_ERROR_ON_INVALID_SUBWINDOW, ARM_COMPUTE_ERROR_ON_UNCONFIGURED_KERNEL, ARM_COMPUTE_UNUSED, arm_compute::test::validation::info, and IKernel::window().
The documentation for this class was generated from the following files:
arm_compute/core/CPP/kernels/CPPFlipWeightsKernel.h
src/core/CPP/kernels/CPPFlipWeightsKernel.cpp