Compute Library: NEConvertFullyConnectedWeights Class Reference
NEConvertFullyConnectedWeights Class Reference
Basic function to run NEConvertFullyConnectedWeightsKernel.
#include <NEConvertFullyConnectedWeights.h>
Public Member Functions
NEConvertFullyConnectedWeights ()
Default constructor.
void configure (const ITensor *input, ITensor *output, const TensorShape &original_input_shape, DataLayout data_layout)
Initialize the function.
void run () override
Run the kernels contained in the function.
Public Member Functions inherited from IFunction
virtual ~IFunction ()=default
Destructor.
virtual void prepare ()
Prepare the function for executing.
Static Public Member Functions
static Status validate (const ITensorInfo *input, const ITensorInfo *output, const TensorShape &original_input_shape, DataLayout data_layout)
Static function to check if given info will lead to a valid configuration of NEConvertFullyConnectedWeights.
Detailed Description
Basic function to run NEConvertFullyConnectedWeightsKernel.
Definition at line 36 of file NEConvertFullyConnectedWeights.h.
Constructor & Destructor Documentation
NEConvertFullyConnectedWeights()
NEConvertFullyConnectedWeights ()
Default constructor.
Definition at line 28 of file NEConvertFullyConnectedWeights.cpp.
     : _kernel()
 {
 }
Member Function Documentation
configure()
void configure (const ITensor * input, ITensor * output, const TensorShape & original_input_shape, DataLayout data_layout)
Initialize the function.
Parameters
[in] input Source weights tensor to convert. Must be 2 dimensional. Data types supported: U8/S8/QASYMM8/U16/S16/U32/S32/F16/F32.
[out] output The converted weights tensor. Shape and Data Type: Same as input.
[in] original_input_shape Shape of the original input tensor (the one entering fully connected layer).
[in] data_layout The data layout the weights have been trained in.
Definition at line 33 of file NEConvertFullyConnectedWeights.cpp.
 {
     _kernel.configure(input, output, original_input_shape, data_layout);
 }
References NEConvertFullyConnectedWeightsKernel::configure().
Referenced by NEFullyConnectedLayer::configure().
run()
void run () override virtual
Run the kernels contained in the function.
For NEON kernels:
Multi-threading is used for the kernels which are parallelisable.
By default std::thread::hardware_concurrency() threads are used.
Note
CPPScheduler::set_num_threads() can be used to manually set the number of threads
For OpenCL kernels:
All the kernels are enqueued on the queue associated with CLScheduler.
The queue is then flushed.
Note
The function will not block until the kernels are executed. It is the user's responsibility to wait.
Will call prepare() on first run if hasn't been done
Implements IFunction.
Definition at line 45 of file NEConvertFullyConnectedWeights.cpp.
 {
     NEScheduler::get().schedule(&_kernel, Window::DimZ);
 }
References Window::DimZ, Scheduler::get(), and IScheduler::schedule().
Referenced by NEFullyConnectedLayer::prepare().
validate()
Status validate (const ITensorInfo * input, const ITensorInfo * output, const TensorShape & original_input_shape, DataLayout data_layout) static
Static function to check if given info will lead to a valid configuration of NEConvertFullyConnectedWeights.
Parameters
[in] input Source weights tensor info to convert. Must be 2 dimensional. Data types supported: U8/S8/QASYMM8/U16/S16/U32/S32/F16/F32.
[in] output The converted weights tensor info. Shape and Data Type: Same as input.
[in] original_input_shape Shape of the original input tensor (the one entering fully connected layer).
[in] data_layout The data layout the weights have been trained in.
Definition at line 39 of file NEConvertFullyConnectedWeights.cpp.
 {
     return NEConvertFullyConnectedWeightsKernel::validate(input, output, original_input_shape, data_layout);
 }
References NEConvertFullyConnectedWeightsKernel::validate().
Referenced by NEFullyConnectedLayer::validate().
The documentation for this class was generated from the following files:
arm_compute/runtime/NEON/functions/NEConvertFullyConnectedWeights.h
src/runtime/NEON/functions/NEConvertFullyConnectedWeights.cpp