Compute Library: NEQuantizationLayer Class Reference
NEQuantizationLayer Class Reference
Basic function to simulate a quantization layer.
#include <NEQuantizationLayer.h>
Public Member Functions
NEQuantizationLayer ()
Default constructor.
void configure (const ITensor *input, ITensor *output)
Set the input and output tensors.
void run () override
Run the kernels contained in the function.
Public Member Functions inherited from IFunction
virtual ~IFunction ()=default
Destructor.
virtual void prepare ()
Prepare the function for executing.
Static Public Member Functions
static Status validate (const ITensorInfo *input, const ITensorInfo *output)
Static function to check if given info will lead to a valid configuration of NEQuantizationLayer.
Detailed Description
Basic function to simulate a quantization layer.
This function calls the following NEON kernels:
Note
The implementation supports only 3D input tensors
NEMinMaxLayerKernel
NEQuantizationLayerKernel
Definition at line 47 of file NEQuantizationLayer.h.
Constructor & Destructor Documentation
NEQuantizationLayer()
NEQuantizationLayer ()
Default constructor.
Definition at line 33 of file NEQuantizationLayer.cpp.
     : _quantize_kernel(), _min_max_kernel(), _min_max()
 {
 }
Member Function Documentation
configure()
void configure (const ITensor * input, ITensor * output)
Set the input and output tensors.
Parameters
[in] input Source tensor with at least 3 dimensions. The dimensions over the third will be interpreted as batches. Data types supported: F32
[out] output Destination tensor with the same dimensions of input. Data types supported: U8
Definition at line 49 of file NEQuantizationLayer.cpp.
 {
     ARM_COMPUTE_ERROR_ON_NULLPTR(input, output);
     // Configure min-max kernel. _min_max tensor will be auto-configured within the kernel
     _min_max_kernel.configure(input, &_min_max);
     // Configure quantize kernel
     _quantize_kernel.configure(input, output, &_min_max);
     // Allocate min_max tensor
     _min_max.allocator()->allocate();
 }
References TensorAllocator::allocate(), Tensor::allocator(), ARM_COMPUTE_ERROR_ON_NULLPTR, NEQuantizationLayerKernel::configure(), and NEMinMaxLayerKernel::configure().
run()
void run () override virtual
Run the kernels contained in the function.
For NEON kernels:
Multi-threading is used for the kernels which are parallelisable.
By default std::thread::hardware_concurrency() threads are used.
Note
CPPScheduler::set_num_threads() can be used to manually set the number of threads
For OpenCL kernels:
All the kernels are enqueued on the queue associated with CLScheduler.
The queue is then flushed.
Note
The function will not block until the kernels are executed. It is the user's responsibility to wait.
Will call prepare() on first run if hasn't been done
Implements IFunction.
Definition at line 63 of file NEQuantizationLayer.cpp.
 {
     // Reset min and max
     _min_max_kernel.reset();
     // Run min and max kernel
     NEScheduler::get().schedule(&_min_max_kernel, Window::DimY);
     // Run quantize kernel
     NEScheduler::get().schedule(&_quantize_kernel, Window::DimY);
 }
References Window::DimY, Scheduler::get(), NEMinMaxLayerKernel::reset(), and IScheduler::schedule().
validate()
Status validate (const ITensorInfo * input, const ITensorInfo * output) static
Static function to check if given info will lead to a valid configuration of NEQuantizationLayer.
Parameters
[in] input Input tensor info. The dimensions over the third will be interpreted as batches. Data types supported: F32.
[in] output Output tensor info. Data types supported: U8
Returns
a status
Definition at line 38 of file NEQuantizationLayer.cpp.
 {
     ARM_COMPUTE_RETURN_ERROR_ON_NULLPTR(input, output);
     TensorInfo min_max{ input->num_channels(), input->data_type() };
     ARM_COMPUTE_RETURN_ON_ERROR(NEMinMaxLayerKernel::validate(input, &min_max));
     ARM_COMPUTE_RETURN_ON_ERROR(NEQuantizationLayerKernel::validate(input, output, &min_max));
     return Status{};
 }
References ARM_COMPUTE_RETURN_ERROR_ON_NULLPTR, ARM_COMPUTE_RETURN_ON_ERROR, ITensorInfo::data_type(), ITensorInfo::num_channels(), NEQuantizationLayerKernel::validate(), and NEMinMaxLayerKernel::validate().
The documentation for this class was generated from the following files:
arm_compute/runtime/NEON/functions/NEQuantizationLayer.h
src/runtime/NEON/functions/NEQuantizationLayer.cpp