Compute Library: ConcatenateLayerNode Class Reference
ConcatenateLayerNode Class Reference final
Concatenation Layer node.
#include <ConcatenateLayerNode.h>
Public Member Functions
ConcatenateLayerNode (unsigned int total_nodes, DataLayoutDimension axis)
Constructor.
void set_enabled (bool is_enabled)
Disables or not the depth concatenate node.
bool is_enabled () const
Enabled parameter accessor.
DataLayoutDimension concatenation_axis () const
Concatenation axis parameter accessor.
NodeType type () const override
Returns node's type.
bool forward_descriptors () override
Forwards descriptor information to outputs if possible.
TensorDescriptor configure_output (size_t idx) const override
Calculates output configuration.
void accept (INodeVisitor &v) override
Accepts a node visitor.
Public Member Functions inherited from INode
INode ()
Constructor.
virtual ~INode ()=default
Destructor.
INode (const INode &)=delete
Prevent instances of this class from being copied (As this class contains pointers)
INode & operator= (const INode &)=delete
Prevent instances of this class from being copy assigned (As this class contains pointers)
INode (INode &&)=default
Allow instances of this class to be moved.
INode & operator= (INode &&)=default
Allow instances of this class to be move assigned.
virtual Status validate () const
Validate node.
std::string name () const
Returns node's name.
NodeID id () const
Returns node's ID.
const Graph * graph () const
Returns node's Graph.
Graph * graph ()
Returns node's Graph.
void set_graph (Graph *g)
Sets the graph that this node is registered to.
void set_id (NodeID id)
Sets the node id.
void set_common_node_parameters (NodeParams common_params)
Sets common node parameters.
void set_requested_target (Target target)
Sets target preference.
void set_assigned_target (Target target)
Sets the final execution target.
void set_output_tensor (TensorID tid, size_t idx)
Sets the output tensor of at a given index.
const std::vector< TensorID > & inputs () const
Returns inputs of the node.
const std::vector< TensorID > & outputs () const
Returns outputs of the node.
const std::vector< EdgeID > & input_edges () const
Returns input edge set.
const std::set< EdgeID > & output_edges () const
Returns output edge set.
TensorID input_id (size_t idx) const
Returns the tensor ID of a given input of the node.
TensorID output_id (size_t idx) const
Returns the tensor ID of a given output of the node.
Tensor * input (size_t idx) const
Returns the tensor of a given input of the node.
Tensor * output (size_t idx) const
Returns the tensor of a given output of the node.
EdgeID input_edge_id (size_t idx) const
Returns the edge ID of a given input of the node.
Edge * input_edge (size_t idx) const
Returns the edge of a given input of the node.
size_t num_inputs () const
Returns number of inputs of the node.
size_t num_outputs () const
Returns number of outputs of the node.
NodeParams common_node_params () const
Returns common node parameters.
Target requested_target () const
Returns requested target for this node.
Target assigned_target () const
Returns assigned target for this node.
Static Public Member Functions
static TensorDescriptor compute_output_descriptor (const std::vector< TensorDescriptor > &input_descriptors, DataLayoutDimension axis)
Computes concatenations output descriptor.
Detailed Description
Concatenation Layer node.
Definition at line 34 of file ConcatenateLayerNode.h.
Constructor & Destructor Documentation
ConcatenateLayerNode()
ConcatenateLayerNode (unsigned int total_nodes, DataLayoutDimension axis)
Constructor.
Parameters
[in] total_nodes Number of nodes that will get concatenated
[in] axis Concatenation axis
Definition at line 37 of file ConcatenateLayerNode.cpp.
     : _total_nodes(total_nodes), _axis(axis), _is_enabled(true)
 {
     _input_edges.resize(_total_nodes, EmptyEdgeID);
     _outputs.resize(1, NullTensorID);
 }
References arm_compute::graph::EmptyEdgeID, and arm_compute::graph::NullTensorID.
Member Function Documentation
accept()
void accept (INodeVisitor & v) override virtual
Accepts a node visitor.
Parameters
[in] v Visitor to accept
Implements INode.
Definition at line 136 of file ConcatenateLayerNode.cpp.
 {
     v.visit(*this);
 }
References INodeVisitor::visit().
compute_output_descriptor()
TensorDescriptor compute_output_descriptor (const std::vector< TensorDescriptor > & input_descriptors, DataLayoutDimension axis) static
Computes concatenations output descriptor.
Parameters
[in] input_descriptors Input descriptors
[in] axis Concatenation axis
Returns
Expected output descriptor
Definition at line 59 of file ConcatenateLayerNode.cpp.
 {
     ARM_COMPUTE_ERROR_ON(input_descriptors.size() == 0);
     TensorDescriptor output_descriptor = input_descriptors[0];
     const int        axis_idx          = get_dimension_idx(output_descriptor, axis);
     // Extract shapes
     std::vector<const TensorShape *> shapes;
     for(auto &input_descriptor : input_descriptors)
     {
         shapes.emplace_back(&input_descriptor.shape);
     }
     // Calculate output shape
     if(axis_idx == 0)
     {
         output_descriptor.shape = arm_compute::misc::shape_calculator::calculate_width_concatenate_shape(shapes);
     }
     else if(axis_idx == 2)
     {
         output_descriptor.shape = arm_compute::misc::shape_calculator::calculate_depth_concatenate_shape(shapes);
     }
     else
     {
         ARM_COMPUTE_ERROR("Unsupported concatenation axis!");
     }
     return output_descriptor;
 }
References ARM_COMPUTE_ERROR, ARM_COMPUTE_ERROR_ON, arm_compute::test::validation::axis, arm_compute::misc::shape_calculator::calculate_depth_concatenate_shape(), arm_compute::misc::shape_calculator::calculate_width_concatenate_shape(), and arm_compute::graph::get_dimension_idx().
Referenced by ConcatenateLayerNode::configure_output().
concatenation_axis()
DataLayoutDimension concatenation_axis () const
Concatenation axis parameter accessor.
Returns
Concatenation axis
Definition at line 54 of file ConcatenateLayerNode.cpp.
 {
     return _axis;
 }
Referenced by arm_compute::graph::backends::detail::create_concatenate_layer(), and DotGraphVisitor::visit().
configure_output()
TensorDescriptor configure_output (size_t idx) const override virtual
Calculates output configuration.
Parameters
[in] idx Output index to configure
Returns
Output descriptor configuration
Implements INode.
Definition at line 103 of file ConcatenateLayerNode.cpp.
 {
     ARM_COMPUTE_UNUSED(idx);
     ARM_COMPUTE_ERROR_ON(idx >= _outputs.size());
     // Check if all input tensors are set
     bool are_all_inputs_set = std::all_of(std::begin(_input_edges), std::end(_input_edges), [](const EdgeID & eid)
     {
         return eid != EmptyEdgeID;
     });
     TensorDescriptor output_info = {};
     if(are_all_inputs_set)
     {
         std::vector<TensorDescriptor> inputs_descriptors;
         for(unsigned int i = 0; i < _input_edges.size(); ++i)
         {
             const Tensor *t = _graph->tensor(input_id(i));
             ARM_COMPUTE_ERROR_ON(t == nullptr);
             inputs_descriptors.push_back(t->desc());
         }
         output_info = compute_output_descriptor(inputs_descriptors, _axis);
     }
     return output_info;
 }
References ARM_COMPUTE_ERROR_ON, ARM_COMPUTE_UNUSED, ConcatenateLayerNode::compute_output_descriptor(), Tensor::desc(), arm_compute::graph::EmptyEdgeID, INode::input_id(), and arm_compute::test::validation::output_info.
Referenced by ConcatenateLayerNode::forward_descriptors().
forward_descriptors()
bool forward_descriptors () override virtual
Forwards descriptor information to outputs if possible.
Returns
True if descriptor information could be forwarded otherwise false
Implements INode.
Definition at line 91 of file ConcatenateLayerNode.cpp.
 {
     if(_outputs[0] != NullTensorID)
     {
         Tensor *dst = output(0);
         ARM_COMPUTE_ERROR_ON(dst == nullptr);
         dst->desc() = configure_output(0);
         return true;
     }
     return false;
 }
References ARM_COMPUTE_ERROR_ON, ConcatenateLayerNode::configure_output(), arm_compute::test::validation::dst, arm_compute::graph::NullTensorID, and INode::output().
is_enabled()
bool is_enabled () const
Enabled parameter accessor.
Returns
True if a backend function is to be created else false
Definition at line 49 of file ConcatenateLayerNode.cpp.
 {
     return _is_enabled;
 }
Referenced by arm_compute::graph::backends::detail::create_concatenate_layer(), arm_compute::graph::backends::detail::create_concatenate_layer< GCDepthConcatenateLayer, GCTargetInfo >(), ConcatenateLayerNode::set_enabled(), and DotGraphVisitor::visit().
set_enabled()
void set_enabled (bool is_enabled)
Disables or not the depth concatenate node.
Warning
This is used when concatenate is performed using sub-tensors, where this node is used as a placeholder.
Parameters
[in] is_enabled If true a backend function is created to perform the concatenation (involves copying), while if false, no function is created and we assume that sub-tensors are properly set to simulate a zero copy operation.
Definition at line 44 of file ConcatenateLayerNode.cpp.
 {
     _is_enabled = is_enabled;
 }
References ConcatenateLayerNode::is_enabled().
type()
NodeType type () const override virtual
Returns node's type.
Returns
Node's type
Implements INode.
Definition at line 131 of file ConcatenateLayerNode.cpp.
 {
     return NodeType::ConcatenateLayer;
 }
References arm_compute::graph::ConcatenateLayer.
Referenced by arm_compute::graph::backends::detail::create_concatenate_layer().
The documentation for this class was generated from the following files:
arm_compute/graph/nodes/ConcatenateLayerNode.h
src/graph/nodes/ConcatenateLayerNode.cpp