Compute Library: CLMemory Class Reference
CLMemory Class Reference
OpenCL implementation of memory object.
#include <CLMemory.h>
Public Member Functions
CLMemory ()
Default Constructor.
CLMemory (std::shared_ptr< ICLMemoryRegion > memory)
Default Constructor.
CLMemory (ICLMemoryRegion *memory)
Default Constructor.
CLMemory (const CLMemory &)=default
Allow instances of this class to be copied.
CLMemory & operator= (const CLMemory &)=default
Allow instances of this class to be copy assigned.
CLMemory (CLMemory &&) noexcept=default
Allow instances of this class to be moved.
CLMemory & operator= (CLMemory &&) noexcept=default
Allow instances of this class to be move assigned.
ICLMemoryRegion * cl_region ()
OpenCL Region accessor.
ICLMemoryRegion * cl_region () const
OpenCL Region accessor.
IMemoryRegion * region () final
Region accessor.
IMemoryRegion * region () const final
Region accessor.
void set_region (IMemoryRegion *region) final
Sets a memory region.
void set_owned_region (std::unique_ptr< IMemoryRegion > region) final
Sets a memory region.
Public Member Functions inherited from IMemory
virtual ~IMemory ()=default
Virtual default destructor.
Detailed Description
OpenCL implementation of memory object.
Definition at line 38 of file CLMemory.h.
Constructor & Destructor Documentation
CLMemory() [1/5]
CLMemory ()
Default Constructor.
Definition at line 31 of file CLMemory.cpp.
     : _region(nullptr), _region_owned(nullptr)
 {
 }
CLMemory() [2/5]
CLMemory (std::shared_ptr< ICLMemoryRegion > memory)
Default Constructor.
Parameters
[in] memory Memory to be imported
Definition at line 36 of file CLMemory.cpp.
     : _region(nullptr), _region_owned(std::move(memory))
 {
     _region_owned = memory;
     _region       = _region_owned.get();
 }
CLMemory() [3/5]
CLMemory (ICLMemoryRegion * memory)
Default Constructor.
Note
Ownership of the memory is not transferred to this object. Thus management (allocate/free) should be done by the client.
Parameters
[in] memory Memory to be imported
Definition at line 43 of file CLMemory.cpp.
     : _region(memory), _region_owned(nullptr)
 {
     _region = memory;
 }
CLMemory() [4/5]
CLMemory (const CLMemory &) default
Allow instances of this class to be copied.
CLMemory() [5/5]
CLMemory (CLMemory &&) default noexcept
Allow instances of this class to be moved.
Member Function Documentation
cl_region() [1/2]
ICLMemoryRegion * cl_region ()
OpenCL Region accessor.
Returns
Memory region
Definition at line 49 of file CLMemory.cpp.
 {
     return _region;
 }
Referenced by CLTensorAllocator::allocate(), CLTensorAllocator::cl_data(), CLTensorAllocator::map(), CLTensorAllocator::set_associated_memory_group(), CLMemory::set_region(), and CLTensorAllocator::unmap().
cl_region() [2/2]
ICLMemoryRegion * cl_region () const
OpenCL Region accessor.
Returns
Memory region
Definition at line 54 of file CLMemory.cpp.
 {
     return _region;
 }
operator=() [1/2]
CLMemory& operator= (const CLMemory &) default
Allow instances of this class to be copy assigned.
operator=() [2/2]
CLMemory& operator= (CLMemory &&) default noexcept
Allow instances of this class to be move assigned.
region() [1/2]
IMemoryRegion * region () final virtual
Region accessor.
Returns
Memory region
Implements IMemory.
Definition at line 59 of file CLMemory.cpp.
 {
     return _region;
 }
Referenced by CLTensorAllocator::allocate(), CLTensorAllocator::cl_data(), CLTensorAllocator::map(), CLTensorAllocator::set_associated_memory_group(), CLMemory::set_owned_region(), CLMemory::set_region(), and CLTensorAllocator::unmap().
region() [2/2]
IMemoryRegion * region () const final virtual
Region accessor.
Returns
Memory region
Implements IMemory.
Definition at line 64 of file CLMemory.cpp.
 {
     return _region;
 }
set_owned_region()
void set_owned_region (std::unique_ptr< IMemoryRegion > region) final virtual
Sets a memory region.
Warning
Ownership of the memory region is transfered along
Parameters
region Memory region
Implements IMemory.
Definition at line 76 of file CLMemory.cpp.
 {
     _region_owned = utils::cast::polymorphic_downcast_unique_ptr<ICLMemoryRegion>(std::move(region));
     _region       = _region_owned.get();
 }
References CLMemory::region().
Referenced by CLTensorAllocator::allocate(), and CLTensorAllocator::import_memory().
set_region()
void set_region (IMemoryRegion * region) final virtual
Sets a memory region.
Warning
Ownership of the memory region remains to the caller
Parameters
region Memory region
Implements IMemory.
Definition at line 69 of file CLMemory.cpp.
 {
     auto cl_region = utils::cast::polymorphic_downcast<ICLMemoryRegion *>(region);
     _region_owned  = nullptr;
     _region        = cl_region;
 }
References CLMemory::cl_region(), and CLMemory::region().
Referenced by CLTensorAllocator::free().
The documentation for this class was generated from the following files:
arm_compute/runtime/CL/CLMemory.h
src/runtime/CL/CLMemory.cpp