Compute Library: GCDepthConcatenateLayerKernel Class Reference
GCDepthConcatenateLayerKernel Class Reference
Interface for the depth concatenate kernel.
#include <GCDepthConcatenateLayerKernel.h>
Public Member Functions
GCDepthConcatenateLayerKernel ()
Default constructor.
GCDepthConcatenateLayerKernel (const GCDepthConcatenateLayerKernel &)=delete
Prevent instances of this class from being copied (As this class contains pointers)
GCDepthConcatenateLayerKernel & operator= (const GCDepthConcatenateLayerKernel &)=delete
Prevent instances of this class from being copied (As this class contains pointers)
GCDepthConcatenateLayerKernel (GCDepthConcatenateLayerKernel &&)=default
Allow instances of this class to be moved.
GCDepthConcatenateLayerKernel & operator= (GCDepthConcatenateLayerKernel &&)=default
Allow instances of this class to be moved.
~GCDepthConcatenateLayerKernel ()=default
Default destructor.
void configure (const IGCTensor *input, unsigned int depth_offset, IGCTensor *output)
Initialise the kernel's inputs and output.
void run (const Window &window) override
Enqueue the OpenGL ES shader to process the given window.
BorderSize border_size () const override
The size of the border for that kernel.
Public Member Functions inherited from IGCKernel
IGCKernel ()
Constructor.
GCKernel & kernel ()
Returns a reference to the GLES kernel of this object.
void add_1D_tensor_argument (unsigned int &idx, const IGCTensor *tensor, const unsigned int binding_point, const Window &window)
Add the passed 1D tensor's parameters to the object's kernel's arguments starting from the index idx.
void add_2D_tensor_argument (unsigned int &idx, const IGCTensor *tensor, const unsigned int binding_point, const Window &window)
Add the passed 2D tensor's parameters to the object's kernel's arguments starting from the index idx.
void add_3D_tensor_argument (unsigned int &idx, const IGCTensor *tensor, const unsigned int binding_point, const Window &window)
Add the passed 3D tensor's parameters to the object's kernel's arguments starting from the index idx.
unsigned int num_arguments_per_1D_tensor () const
Returns the number of arguments enqueued per 1D tensor object.
unsigned int num_arguments_per_2D_tensor () const
Returns the number of arguments enqueued per 2D tensor object.
unsigned int num_arguments_per_3D_tensor () const
Returns the number of arguments enqueued per 3D tensor object.
void set_lws_hint (gles::NDRange &lws_hint)
Set the Local-Workgroup-Size hint.
void set_target (GPUTarget target)
Set the targeted GPU architecture.
GPUTarget get_target () const
Get the targeted GPU architecture.
Public Member Functions inherited from IKernel
IKernel ()
Constructor.
virtual ~IKernel ()=default
Destructor.
virtual bool is_parallelisable () const
Indicates whether or not the kernel is parallelisable.
const Window & window () const
The maximum window the kernel can be executed on.
Detailed Description
Interface for the depth concatenate kernel.
The input tensor will be concatenated into the output tensor.
Definition at line 38 of file GCDepthConcatenateLayerKernel.h.
Constructor & Destructor Documentation
GCDepthConcatenateLayerKernel() [1/3]
GCDepthConcatenateLayerKernel ()
Default constructor.
Definition at line 40 of file GCDepthConcatenateLayerKernel.cpp.
     : _input(nullptr), _output(nullptr), _top_bottom(0), _left_right(0), _depth_offset(0)
 {
 }
GCDepthConcatenateLayerKernel() [2/3]
GCDepthConcatenateLayerKernel (const GCDepthConcatenateLayerKernel &) delete
Prevent instances of this class from being copied (As this class contains pointers)
GCDepthConcatenateLayerKernel() [3/3]
GCDepthConcatenateLayerKernel (GCDepthConcatenateLayerKernel &&) default
Allow instances of this class to be moved.
~GCDepthConcatenateLayerKernel()
~GCDepthConcatenateLayerKernel () default
Default destructor.
Member Function Documentation
border_size()
BorderSize border_size () const override virtual
The size of the border for that kernel.
Returns
The width in number of elements of the border.
Reimplemented from IKernel.
Definition at line 45 of file GCDepthConcatenateLayerKernel.cpp.
 {
     return BorderSize(_top_bottom, _left_right);
 }
configure()
void configure (const IGCTensor * input, unsigned int depth_offset, IGCTensor * output)
Initialise the kernel's inputs and output.
Parameters
[in] input Input tensor. Data types supported: F16/F32.
[in] depth_offset The offset on the Z axis.
[in,out] output Output tensor. Data types supported: Same as input.
Note
: The output tensor's low two dimensions can't be smaller than the input one's.
: The gaps between the two lowest dimensions of input and output need to be divisible by 2.
Definition at line 50 of file GCDepthConcatenateLayerKernel.cpp.
 {
     ARM_COMPUTE_ERROR_ON_DATA_TYPE_CHANNEL_NOT_IN(input, 1, DataType::F16, DataType::F32);
     ARM_COMPUTE_ERROR_ON_MISMATCHING_DATA_TYPES(input, output);
     ARM_COMPUTE_ERROR_ON(input->info()->dimension(2) + depth_offset > output->info()->dimension(2));
     ARM_COMPUTE_ERROR_ON(input->info()->dimension(0) > output->info()->dimension(0));
     ARM_COMPUTE_ERROR_ON(input->info()->dimension(1) > output->info()->dimension(1));
     ARM_COMPUTE_ERROR_ON_MISMATCHING_SHAPES(3, input, output);
     // The gaps between the two lowest dimensions of input and output need to be divisible by 2
     // Otherwise it is not clear how the padding should be added onto the input tensor
     ARM_COMPUTE_ERROR_ON((output->info()->dimension(0) - input->info()->dimension(0)) % 2);
     ARM_COMPUTE_ERROR_ON((output->info()->dimension(1) - input->info()->dimension(1)) % 2);
     _input        = input;
     _output       = output;
     _depth_offset = depth_offset;
     // Add build options
     std::set<std::string> build_opts;
     std::string           dt_name = (input->info()->data_type() == DataType::F32) ? "DATA_TYPE_FP32" : "DATA_TYPE_FP16";
     build_opts.emplace(("#define " + dt_name));
     build_opts.emplace("#define LOCAL_SIZE_X " + support::cpp11::to_string(1));
     build_opts.emplace("#define LOCAL_SIZE_Y " + support::cpp11::to_string(1));
     build_opts.emplace("#define LOCAL_SIZE_Z " + support::cpp11::to_string(1));
     // Configure kernel window
     _left_right = (output->info()->dimension(0) - input->info()->dimension(0)) / 2;
     _top_bottom = (output->info()->dimension(1) - input->info()->dimension(1)) / 2;
     build_opts.emplace("#define OFFSET_X " + support::cpp11::to_string(_left_right));
     build_opts.emplace("#define OFFSET_Y " + support::cpp11::to_string(_top_bottom));
     // Create kernel
     _kernel = static_cast<GCKernel>(GCKernelLibrary::get().create_kernel("concatenate_depth", build_opts));
     unsigned int num_elems_processed_per_iteration = 1;
     unsigned int num_elems_read_per_iteration      = 1;
     if(input->info()->data_type() == DataType::F32)
     {
         num_elems_processed_per_iteration = 1;
         num_elems_read_per_iteration      = 1;
     }
     else if(input->info()->data_type() == DataType::F16)
     {
         num_elems_processed_per_iteration = 4;
         num_elems_read_per_iteration      = 4;
     }
     const unsigned int num_rows_read_per_iteration = 1;
     // The window needs to be based on input as we copy all the depths of input
     Window win = calculate_max_window(*output->info(), Steps(num_elems_processed_per_iteration));
     win.set(Window::DimZ, Window::Dimension(0, input->info()->tensor_shape().z(), 1));
     AccessWindowRectangle  input_access(input->info(), -_left_right, -_top_bottom, num_elems_read_per_iteration, num_rows_read_per_iteration);
     AccessWindowHorizontal output_access(output->info(), 0, num_elems_processed_per_iteration);
     update_window_and_padding(win, input_access, output_access);
     output_access.set_valid_region(win, ValidRegion(Coordinates(), output->info()->tensor_shape()));
     IGCKernel::configure(win);
 }
References ARM_COMPUTE_ERROR_ON, ARM_COMPUTE_ERROR_ON_DATA_TYPE_CHANNEL_NOT_IN, ARM_COMPUTE_ERROR_ON_MISMATCHING_DATA_TYPES, ARM_COMPUTE_ERROR_ON_MISMATCHING_SHAPES, arm_compute::calculate_max_window(), arm_compute::create_kernel(), ITensorInfo::data_type(), ITensorInfo::dimension(), Window::DimZ, arm_compute::F16, arm_compute::F32, GCKernelLibrary::get(), ITensor::info(), Window::set(), ITensorInfo::tensor_shape(), arm_compute::support::cpp11::to_string(), arm_compute::update_window_and_padding(), and Dimensions< T >::z().
operator=() [1/2]
GCDepthConcatenateLayerKernel& operator= (const GCDepthConcatenateLayerKernel &) delete
Prevent instances of this class from being copied (As this class contains pointers)
operator=() [2/2]
GCDepthConcatenateLayerKernel& operator= (GCDepthConcatenateLayerKernel &&) default
Allow instances of this class to be moved.
run()
void run (const Window & window) override virtual
Enqueue the OpenGL ES shader to process the given window.
Parameters
[in] window Region on which to execute the kernel. (Must be a valid region of the window returned by window()).
Implements IGCKernel.
Definition at line 112 of file GCDepthConcatenateLayerKernel.cpp.
 {
     ARM_COMPUTE_ERROR_ON_UNCONFIGURED_KERNEL(this);
     ARM_COMPUTE_ERROR_ON_INVALID_SUBWINDOW(IGCKernel::window(), window);
     _kernel.use();
     _output->set_needs_shifting(true);
     Window slice     = window.first_slice_window_3D();
     Window slice_in  = window.first_slice_window_3D();
     Window slice_out = window.first_slice_window_3D();
     slice.shift(Window::DimX, -(_output->info()->padding()).left);
     slice_out.set(Window::DimZ, Window::Dimension(_depth_offset));
     do
     {
         unsigned int idx = 0;
         add_3D_tensor_argument(idx, _input, 1, slice_in);
         add_3D_tensor_argument(idx, _output, 2, slice_out);
         _kernel.update_shader_params();
         enqueue(*this, slice);
     }
     while(window.slide_window_slice_3D(slice) && window.slide_window_slice_3D(slice_in));
 }
References IGCKernel::add_3D_tensor_argument(), ARM_COMPUTE_ERROR_ON_INVALID_SUBWINDOW, ARM_COMPUTE_ERROR_ON_UNCONFIGURED_KERNEL, Window::DimX, Window::DimZ, arm_compute::enqueue(), Window::first_slice_window_3D(), ITensor::info(), ITensorInfo::padding(), Window::set(), IGCTensor::set_needs_shifting(), arm_compute::test::validation::reference::slice(), Window::slide_window_slice_3D(), and IKernel::window().
The documentation for this class was generated from the following files:
arm_compute/core/GLES_COMPUTE/kernels/GCDepthConcatenateLayerKernel.h
src/core/GLES_COMPUTE/kernels/GCDepthConcatenateLayerKernel.cpp