Compute Library: CLUpsampleLayer Class Reference
CLUpsampleLayer Class Reference
Basic function to run CLUpsampleLayerKernel.
#include <CLUpsampleLayer.h>
Public Member Functions
CLUpsampleLayer ()
Default constructor.
CLUpsampleLayer (const CLUpsampleLayer &)=delete
Prevent instances of this class from being copied (As this class contains pointers)
CLUpsampleLayer & operator= (const CLUpsampleLayer &)=delete
Prevent instances of this class from being copied (As this class contains pointers)
CLUpsampleLayer (CLUpsampleLayer &&)=default
Allow instances of this class to be moved.
CLUpsampleLayer & operator= (CLUpsampleLayer &&)=default
Allow instances of this class to be moved.
virtual ~CLUpsampleLayer ()=default
Default destructor.
void configure (ICLTensor *input, ICLTensor *output, const Size2D &info, const InterpolationPolicy upsampling_policy)
Initialize the function's source, destination, interpolation type and border_mode.
void run () override
Run the kernels contained in the function.
Public Member Functions inherited from IFunction
virtual ~IFunction ()=default
Destructor.
virtual void prepare ()
Prepare the function for executing.
Static Public Member Functions
static Status validate (const ITensorInfo *input, const ITensorInfo *output, const Size2D &info, const InterpolationPolicy upsampling_policy)
Static function to check if given info will lead to a valid configuration of CLDeconvolutionLayerUpsample.
Detailed Description
Basic function to run CLUpsampleLayerKernel.
Definition at line 38 of file CLUpsampleLayer.h.
Constructor & Destructor Documentation
CLUpsampleLayer() [1/3]
CLUpsampleLayer ()
Default constructor.
Definition at line 32 of file CLUpsampleLayer.cpp.
     : _upsample(),
       _output(nullptr)
 {
 }
CLUpsampleLayer() [2/3]
CLUpsampleLayer (const CLUpsampleLayer &) delete
Prevent instances of this class from being copied (As this class contains pointers)
CLUpsampleLayer() [3/3]
CLUpsampleLayer (CLUpsampleLayer &&) default
Allow instances of this class to be moved.
~CLUpsampleLayer()
virtual ~CLUpsampleLayer () virtual default
Default destructor.
Member Function Documentation
configure()
void configure (ICLTensor * input, ICLTensor * output, const Size2D & info, const InterpolationPolicy upsampling_policy)
Initialize the function's source, destination, interpolation type and border_mode.
Parameters
[in] input Source tensor. Data type supported: U8/S8/QASYMM8/U16/S16/F16/U32/S32/F32.
[out] output Destination tensor. Data types supported: same as input.
[in] info Contains stride information described in Size2D.
[in] upsampling_policy Defines the policy to fill the intermediate pixels.
Definition at line 44 of file CLUpsampleLayer.cpp.
 {
     ARM_COMPUTE_ERROR_ON_NULLPTR(input, output);
     _output = output;
     _upsample.configure(input, _output, info, upsampling_policy);
 }
References ARM_COMPUTE_ERROR_ON_NULLPTR, CLUpsampleLayerKernel::configure(), and arm_compute::test::validation::info.
operator=() [1/2]
CLUpsampleLayer& operator= (const CLUpsampleLayer &) delete
Prevent instances of this class from being copied (As this class contains pointers)
operator=() [2/2]
CLUpsampleLayer& operator= (CLUpsampleLayer &&) default
Allow instances of this class to be moved.
run()
void run () override virtual
Run the kernels contained in the function.
For NEON kernels:
Multi-threading is used for the kernels which are parallelisable.
By default std::thread::hardware_concurrency() threads are used.
Note
CPPScheduler::set_num_threads() can be used to manually set the number of threads
For OpenCL kernels:
All the kernels are enqueued on the queue associated with CLScheduler.
The queue is then flushed.
Note
The function will not block until the kernels are executed. It is the user's responsibility to wait.
Will call prepare() on first run if hasn't been done
Implements IFunction.
Definition at line 53 of file CLUpsampleLayer.cpp.
 {
     CLScheduler::get().enqueue(_upsample, false);
 }
References CLScheduler::enqueue(), and CLScheduler::get().
validate()
Status validate (const ITensorInfo * input, const ITensorInfo * output, const Size2D & info, const InterpolationPolicy upsampling_policy) static
Static function to check if given info will lead to a valid configuration of CLDeconvolutionLayerUpsample.
Parameters
[in] input Source tensor info. Data types supported: U8/S8/QASYMM8/U16/S16/F16/U32/S32/F32.
[in] output Destination tensor info. Data types supported: same as input.
[in] info Contains stride information described in Size2D.
[in] upsampling_policy Defines the policy to fill the intermediate pixels.
Returns
a status
Definition at line 38 of file CLUpsampleLayer.cpp.
 {
     return CLUpsampleLayerKernel::validate(input, output, info, upsampling_policy);
 }
References arm_compute::test::validation::info, and CLUpsampleLayerKernel::validate().
The documentation for this class was generated from the following files:
arm_compute/runtime/CL/functions/CLUpsampleLayer.h
src/runtime/CL/functions/CLUpsampleLayer.cpp