Compute Library: ICLMultiImage Class Reference
ICLMultiImage Class Reference abstract
Interface for OpenCL multi-planar images.
#include <ICLMultiImage.h>
Public Member Functions
virtual ICLImage * cl_plane (unsigned int index)=0
Return a pointer to the requested OpenCL plane of the image.
virtual const ICLImage * cl_plane (unsigned int index) const =0
Return a constant pointer to the requested OpenCL plane of the image.
IImage * plane (unsigned int index) override
Return a pointer to the requested plane of the image.
const IImage * plane (unsigned int index) const override
Return a constant pointer to the requested plane of the image.
Public Member Functions inherited from IMultiImage
virtual ~IMultiImage ()=default
Destructor.
virtual const MultiImageInfo * info () const =0
Interface to be implemented by the child class to return the multi-planar image's metadata.
Detailed Description
Interface for OpenCL multi-planar images.
Definition at line 36 of file ICLMultiImage.h.
Member Function Documentation
cl_plane() [1/2]
virtual ICLImage* cl_plane (unsigned int index) pure virtual
Return a pointer to the requested OpenCL plane of the image.
Parameters
[in] index The index of the wanted planed.
Returns
A pointer pointed to the OpenCL plane
Implemented in CLMultiImage.
Referenced by CLChannelExtractKernel::configure(), CLColorConvertKernel::configure(), ICLMultiImage::plane(), CLChannelCombineKernel::run(), and CLColorConvertKernel::run().
cl_plane() [2/2]
virtual const ICLImage* cl_plane (unsigned int index) const pure virtual
Return a constant pointer to the requested OpenCL plane of the image.
Parameters
[in] index The index of the wanted planed.
Returns
A constant pointer pointed to the OpenCL plane
Implemented in CLMultiImage.
plane() [1/2]
IImage * plane (unsigned int index) override virtual
Return a pointer to the requested plane of the image.
Parameters
[in] index The index of the wanted planed.
Returns
A pointer pointed to the plane
Implements IMultiImage.
Definition at line 31 of file ICLMultiImage.cpp.
 {
     return cl_plane(index);
 }
References ICLMultiImage::cl_plane().
Referenced by CLColorConvertKernel::configure(), and CLChannelCombineKernel::configure().
plane() [2/2]
const IImage * plane (unsigned int index) const override virtual
Return a constant pointer to the requested plane of the image.
Parameters
[in] index The index of the wanted planed.
Returns
A constant pointer pointed to the plane
Implements IMultiImage.
Definition at line 36 of file ICLMultiImage.cpp.
 {
     return cl_plane(index);
 }
References ICLMultiImage::cl_plane().
The documentation for this class was generated from the following files:
arm_compute/core/CL/ICLMultiImage.h
src/core/CL/ICLMultiImage.cpp