Compute Library: CLSymbols Class Reference
CLSymbols Class Reference final
Class for loading OpenCL symbols.
#include <OpenCL.h>
Public Member Functions
bool load (const std::string &library)
Load symbols from the given OpenCL library path.
bool load_default ()
Load symbols from any of the default OpenCL library names.
Static Public Member Functions
static CLSymbols & get ()
Get the static instance of CLSymbols.
Data Fields
std::function< decltype(clCreateContext)> clCreateContext_ptr = nullptr
std::function< decltype(clCreateContextFromType)> clCreateContextFromType_ptr = nullptr
std::function< decltype(clCreateCommandQueue)> clCreateCommandQueue_ptr = nullptr
std::function< decltype(clGetContextInfo)> clGetContextInfo_ptr = nullptr
std::function< decltype(clBuildProgram)> clBuildProgram_ptr = nullptr
std::function< decltype(clEnqueueNDRangeKernel)> clEnqueueNDRangeKernel_ptr = nullptr
std::function< decltype(clSetKernelArg)> clSetKernelArg_ptr = nullptr
std::function< decltype(clReleaseKernel)> clReleaseKernel_ptr = nullptr
std::function< decltype(clCreateProgramWithSource)> clCreateProgramWithSource_ptr = nullptr
std::function< decltype(clCreateBuffer)> clCreateBuffer_ptr = nullptr
std::function< decltype(clRetainKernel)> clRetainKernel_ptr = nullptr
std::function< decltype(clCreateKernel)> clCreateKernel_ptr = nullptr
std::function< decltype(clGetProgramInfo)> clGetProgramInfo_ptr = nullptr
std::function< decltype(clFlush)> clFlush_ptr = nullptr
std::function< decltype(clFinish)> clFinish_ptr = nullptr
std::function< decltype(clReleaseProgram)> clReleaseProgram_ptr = nullptr
std::function< decltype(clRetainContext)> clRetainContext_ptr = nullptr
std::function< decltype(clCreateProgramWithBinary)> clCreateProgramWithBinary_ptr = nullptr
std::function< decltype(clReleaseCommandQueue)> clReleaseCommandQueue_ptr = nullptr
std::function< decltype(clEnqueueMapBuffer)> clEnqueueMapBuffer_ptr = nullptr
std::function< decltype(clRetainProgram)> clRetainProgram_ptr = nullptr
std::function< decltype(clGetProgramBuildInfo)> clGetProgramBuildInfo_ptr = nullptr
std::function< decltype(clEnqueueReadBuffer)> clEnqueueReadBuffer_ptr = nullptr
std::function< decltype(clEnqueueWriteBuffer)> clEnqueueWriteBuffer_ptr = nullptr
std::function< decltype(clReleaseEvent)> clReleaseEvent_ptr = nullptr
std::function< decltype(clReleaseContext)> clReleaseContext_ptr = nullptr
std::function< decltype(clRetainCommandQueue)> clRetainCommandQueue_ptr = nullptr
std::function< decltype(clEnqueueUnmapMemObject)> clEnqueueUnmapMemObject_ptr = nullptr
std::function< decltype(clRetainMemObject)> clRetainMemObject_ptr = nullptr
std::function< decltype(clReleaseMemObject)> clReleaseMemObject_ptr = nullptr
std::function< decltype(clGetDeviceInfo)> clGetDeviceInfo_ptr = nullptr
std::function< decltype(clGetDeviceIDs)> clGetDeviceIDs_ptr = nullptr
std::function< decltype(clGetMemObjectInfo)> clGetMemObjectInfo_ptr = nullptr
std::function< decltype(clRetainEvent)> clRetainEvent_ptr = nullptr
std::function< decltype(clGetPlatformIDs)> clGetPlatformIDs_ptr = nullptr
std::function< decltype(clGetKernelWorkGroupInfo)> clGetKernelWorkGroupInfo_ptr = nullptr
std::function< decltype(clGetCommandQueueInfo)> clGetCommandQueueInfo_ptr = nullptr
std::function< decltype(clGetKernelInfo)> clGetKernelInfo_ptr = nullptr
std::function< decltype(clGetEventProfilingInfo)> clGetEventProfilingInfo_ptr = nullptr
std::function< decltype(clSVMAlloc)> clSVMAlloc_ptr = nullptr
std::function< decltype(clSVMFree)> clSVMFree_ptr = nullptr
std::function< decltype(clEnqueueSVMMap)> clEnqueueSVMMap_ptr = nullptr
std::function< decltype(clEnqueueSVMUnmap)> clEnqueueSVMUnmap_ptr = nullptr
std::function< decltype(clEnqueueMarker)> clEnqueueMarker_ptr = nullptr
std::function< decltype(clWaitForEvents)> clWaitForEvents_ptr = nullptr
Detailed Description
Class for loading OpenCL symbols.
Definition at line 60 of file OpenCL.h.
Member Function Documentation
get()
CLSymbols & get () static
Get the static instance of CLSymbols.
Returns
The static instance of CLSymbols.
Definition at line 32 of file OpenCL.cpp.
 {
     static CLSymbols symbols;
     return symbols;
 }
Referenced by clBuildProgram(), clCreateBuffer(), clCreateCommandQueue(), clCreateContext(), clCreateContextFromType(), clCreateKernel(), clCreateProgramWithBinary(), clCreateProgramWithSource(), clEnqueueMapBuffer(), clEnqueueMarker(), clEnqueueNDRangeKernel(), clEnqueueReadBuffer(), clEnqueueSVMMap(), clEnqueueSVMUnmap(), clEnqueueUnmapMemObject(), clEnqueueWriteBuffer(), clFinish(), clFlush(), clGetCommandQueueInfo(), clGetContextInfo(), clGetDeviceIDs(), clGetDeviceInfo(), clGetEventProfilingInfo(), clGetKernelInfo(), clGetKernelWorkGroupInfo(), clGetMemObjectInfo(), clGetPlatformIDs(), clGetProgramBuildInfo(), clGetProgramInfo(), clReleaseCommandQueue(), clReleaseContext(), clReleaseEvent(), clReleaseKernel(), clReleaseMemObject(), clReleaseProgram(), clRetainCommandQueue(), clRetainContext(), clRetainEvent(), clRetainKernel(), clRetainMemObject(), clRetainProgram(), clSetKernelArg(), clSVMAlloc(), clSVMFree(), clWaitForEvents(), arm_compute::opencl_is_available(), OpenCLMemoryUsage::test_start(), OpenCLClock< output_timestamps >::test_start(), OpenCLMemoryUsage::test_stop(), and OpenCLClock< output_timestamps >::test_stop().
load()
bool load (const std::string & library)
Load symbols from the given OpenCL library path.
Parameters
[in] library Path to the OpenCL library.
Returns
True if loading the library is successful.
Definition at line 62 of file OpenCL.cpp.
 {
     void *handle = dlopen(library.c_str(), RTLD_LAZY | RTLD_LOCAL);
     if(handle == nullptr)
     {
         std::cerr << "Can't load " << library << ": " << dlerror() << "\n";
         // Set status of loading to failed
         _loaded.second = false;
         return false;
     }
 #define LOAD_FUNCTION_PTR(func_name, handle) \
     func_name##_ptr = reinterpret_cast<decltype(func_name) *>(dlsym(handle, #func_name));
     LOAD_FUNCTION_PTR(clCreateContext, handle);
     LOAD_FUNCTION_PTR(clCreateContextFromType, handle);
     LOAD_FUNCTION_PTR(clCreateCommandQueue, handle);
     LOAD_FUNCTION_PTR(clGetContextInfo, handle);
     LOAD_FUNCTION_PTR(clBuildProgram, handle);
     LOAD_FUNCTION_PTR(clEnqueueNDRangeKernel, handle);
     LOAD_FUNCTION_PTR(clSetKernelArg, handle);
     LOAD_FUNCTION_PTR(clReleaseKernel, handle);
     LOAD_FUNCTION_PTR(clCreateProgramWithSource, handle);
     LOAD_FUNCTION_PTR(clCreateBuffer, handle);
     LOAD_FUNCTION_PTR(clRetainKernel, handle);
     LOAD_FUNCTION_PTR(clCreateKernel, handle);
     LOAD_FUNCTION_PTR(clGetProgramInfo, handle);
     LOAD_FUNCTION_PTR(clFlush, handle);
     LOAD_FUNCTION_PTR(clFinish, handle);
     LOAD_FUNCTION_PTR(clReleaseProgram, handle);
     LOAD_FUNCTION_PTR(clRetainContext, handle);
     LOAD_FUNCTION_PTR(clCreateProgramWithBinary, handle);
     LOAD_FUNCTION_PTR(clReleaseCommandQueue, handle);
     LOAD_FUNCTION_PTR(clEnqueueMapBuffer, handle);
     LOAD_FUNCTION_PTR(clRetainProgram, handle);
     LOAD_FUNCTION_PTR(clGetProgramBuildInfo, handle);
     LOAD_FUNCTION_PTR(clEnqueueReadBuffer, handle);
     LOAD_FUNCTION_PTR(clEnqueueWriteBuffer, handle);
     LOAD_FUNCTION_PTR(clReleaseEvent, handle);
     LOAD_FUNCTION_PTR(clReleaseContext, handle);
     LOAD_FUNCTION_PTR(clRetainCommandQueue, handle);
     LOAD_FUNCTION_PTR(clEnqueueUnmapMemObject, handle);
     LOAD_FUNCTION_PTR(clRetainMemObject, handle);
     LOAD_FUNCTION_PTR(clReleaseMemObject, handle);
     LOAD_FUNCTION_PTR(clGetDeviceInfo, handle);
     LOAD_FUNCTION_PTR(clGetDeviceIDs, handle);
     LOAD_FUNCTION_PTR(clGetMemObjectInfo, handle);
     LOAD_FUNCTION_PTR(clRetainEvent, handle);
     LOAD_FUNCTION_PTR(clGetPlatformIDs, handle);
     LOAD_FUNCTION_PTR(clGetKernelWorkGroupInfo, handle);
     LOAD_FUNCTION_PTR(clGetCommandQueueInfo, handle);
     LOAD_FUNCTION_PTR(clGetKernelInfo, handle);
     LOAD_FUNCTION_PTR(clGetEventProfilingInfo, handle);
     LOAD_FUNCTION_PTR(clSVMAlloc, handle);
     LOAD_FUNCTION_PTR(clSVMFree, handle);
     LOAD_FUNCTION_PTR(clEnqueueSVMMap, handle);
     LOAD_FUNCTION_PTR(clEnqueueSVMUnmap, handle);
     LOAD_FUNCTION_PTR(clEnqueueMarker, handle);
     LOAD_FUNCTION_PTR(clWaitForEvents, handle);
 #undef LOAD_FUNCTION_PTR
     //Don't call dlclose(handle) or all the symbols will be unloaded !
     // Disable default loading and set status to successful
     _loaded = std::make_pair(true, true);
     return true;
 }
References clBuildProgram(), clCreateBuffer(), clCreateCommandQueue(), clCreateContext(), clCreateContextFromType(), clCreateKernel(), clCreateProgramWithBinary(), clCreateProgramWithSource(), clEnqueueMapBuffer(), clEnqueueMarker(), clEnqueueNDRangeKernel(), clEnqueueReadBuffer(), clEnqueueSVMMap(), clEnqueueSVMUnmap(), clEnqueueUnmapMemObject(), clEnqueueWriteBuffer(), clFinish(), clFlush(), clGetCommandQueueInfo(), clGetContextInfo(), clGetDeviceIDs(), clGetDeviceInfo(), clGetEventProfilingInfo(), clGetKernelInfo(), clGetKernelWorkGroupInfo(), clGetMemObjectInfo(), clGetPlatformIDs(), clGetProgramBuildInfo(), clGetProgramInfo(), clReleaseCommandQueue(), clReleaseContext(), clReleaseEvent(), clReleaseKernel(), clReleaseMemObject(), clReleaseProgram(), clRetainCommandQueue(), clRetainContext(), clRetainEvent(), clRetainKernel(), clRetainMemObject(), clRetainProgram(), clSetKernelArg(), clSVMAlloc(), clSVMFree(), clWaitForEvents(), arm_compute::test::library, and LOAD_FUNCTION_PTR.
Referenced by CLSymbols::load_default().
load_default()
bool load_default ()
Load symbols from any of the default OpenCL library names.
Returns
True if loading any library is successful.
Definition at line 38 of file OpenCL.cpp.
 {
     static const std::vector<std::string> libraries{ "libOpenCL.so", "libGLES_mali.so", "libmali.so" };
     if(_loaded.first)
     {
         return _loaded.second;
     }
     // Indicate that default loading has been tried
     _loaded.first = true;
     for(const auto &lib : libraries)
     {
         if(load(lib))
         {
             return true;
         }
     }
     std::cerr << "Couldn't find any OpenCL library.\n";
     return false;
 }
References CLSymbols::load().
Referenced by clBuildProgram(), clCreateBuffer(), clCreateCommandQueue(), clCreateContext(), clCreateContextFromType(), clCreateKernel(), clCreateProgramWithBinary(), clCreateProgramWithSource(), clEnqueueMapBuffer(), clEnqueueMarker(), clEnqueueNDRangeKernel(), clEnqueueReadBuffer(), clEnqueueSVMMap(), clEnqueueSVMUnmap(), clEnqueueUnmapMemObject(), clEnqueueWriteBuffer(), clFinish(), clFlush(), clGetCommandQueueInfo(), clGetContextInfo(), clGetDeviceIDs(), clGetDeviceInfo(), clGetEventProfilingInfo(), clGetKernelInfo(), clGetKernelWorkGroupInfo(), clGetMemObjectInfo(), clGetPlatformIDs(), clGetProgramBuildInfo(), clGetProgramInfo(), clReleaseCommandQueue(), clReleaseContext(), clReleaseEvent(), clReleaseKernel(), clReleaseMemObject(), clReleaseProgram(), clRetainCommandQueue(), clRetainContext(), clRetainEvent(), clRetainKernel(), clRetainMemObject(), clRetainProgram(), clSetKernelArg(), clSVMAlloc(), clSVMFree(), clWaitForEvents(), and arm_compute::opencl_is_available().
Field Documentation
clBuildProgram_ptr
std::function<decltype(clBuildProgram)> clBuildProgram_ptr = nullptr
Definition at line 92 of file OpenCL.h.
Referenced by clBuildProgram(), and arm_compute::opencl_is_available().
clCreateBuffer_ptr
std::function<decltype(clCreateBuffer)> clCreateBuffer_ptr = nullptr
Definition at line 97 of file OpenCL.h.
Referenced by clCreateBuffer(), OpenCLMemoryUsage::test_start(), and OpenCLMemoryUsage::test_stop().
clCreateCommandQueue_ptr
std::function<decltype(clCreateCommandQueue)> clCreateCommandQueue_ptr = nullptr
Definition at line 90 of file OpenCL.h.
Referenced by clCreateCommandQueue().
clCreateContext_ptr
std::function<decltype(clCreateContext)> clCreateContext_ptr = nullptr
Definition at line 88 of file OpenCL.h.
Referenced by clCreateContext().
clCreateContextFromType_ptr
std::function<decltype(clCreateContextFromType)> clCreateContextFromType_ptr = nullptr
Definition at line 89 of file OpenCL.h.
Referenced by clCreateContextFromType().
clCreateKernel_ptr
std::function<decltype(clCreateKernel)> clCreateKernel_ptr = nullptr
Definition at line 99 of file OpenCL.h.
Referenced by clCreateKernel().
clCreateProgramWithBinary_ptr
std::function<decltype(clCreateProgramWithBinary)> clCreateProgramWithBinary_ptr = nullptr
Definition at line 105 of file OpenCL.h.
Referenced by clCreateProgramWithBinary().
clCreateProgramWithSource_ptr
std::function<decltype(clCreateProgramWithSource)> clCreateProgramWithSource_ptr = nullptr
Definition at line 96 of file OpenCL.h.
Referenced by clCreateProgramWithSource().
clEnqueueMapBuffer_ptr
std::function<decltype(clEnqueueMapBuffer)> clEnqueueMapBuffer_ptr = nullptr
Definition at line 107 of file OpenCL.h.
Referenced by clEnqueueMapBuffer().
clEnqueueMarker_ptr
std::function<decltype(clEnqueueMarker)> clEnqueueMarker_ptr = nullptr
Definition at line 131 of file OpenCL.h.
Referenced by clEnqueueMarker().
clEnqueueNDRangeKernel_ptr
std::function<decltype(clEnqueueNDRangeKernel)> clEnqueueNDRangeKernel_ptr = nullptr
Definition at line 93 of file OpenCL.h.
Referenced by clEnqueueNDRangeKernel(), OpenCLClock< output_timestamps >::test_start(), and OpenCLClock< output_timestamps >::test_stop().
clEnqueueReadBuffer_ptr
std::function<decltype(clEnqueueReadBuffer)> clEnqueueReadBuffer_ptr = nullptr
Definition at line 110 of file OpenCL.h.
Referenced by clEnqueueReadBuffer().
clEnqueueSVMMap_ptr
std::function<decltype(clEnqueueSVMMap)> clEnqueueSVMMap_ptr = nullptr
Definition at line 129 of file OpenCL.h.
Referenced by clEnqueueSVMMap().
clEnqueueSVMUnmap_ptr
std::function<decltype(clEnqueueSVMUnmap)> clEnqueueSVMUnmap_ptr = nullptr
Definition at line 130 of file OpenCL.h.
Referenced by clEnqueueSVMUnmap().
clEnqueueUnmapMemObject_ptr
std::function<decltype(clEnqueueUnmapMemObject)> clEnqueueUnmapMemObject_ptr = nullptr
Definition at line 115 of file OpenCL.h.
Referenced by clEnqueueUnmapMemObject().
clEnqueueWriteBuffer_ptr
std::function<decltype(clEnqueueWriteBuffer)> clEnqueueWriteBuffer_ptr = nullptr
Definition at line 111 of file OpenCL.h.
Referenced by clEnqueueWriteBuffer().
clFinish_ptr
std::function<decltype(clFinish)> clFinish_ptr = nullptr
Definition at line 102 of file OpenCL.h.
Referenced by clFinish().
clFlush_ptr
std::function<decltype(clFlush)> clFlush_ptr = nullptr
Definition at line 101 of file OpenCL.h.
Referenced by clFlush().
clGetCommandQueueInfo_ptr
std::function<decltype(clGetCommandQueueInfo)> clGetCommandQueueInfo_ptr = nullptr
Definition at line 124 of file OpenCL.h.
Referenced by clGetCommandQueueInfo().
clGetContextInfo_ptr
std::function<decltype(clGetContextInfo)> clGetContextInfo_ptr = nullptr
Definition at line 91 of file OpenCL.h.
Referenced by clGetContextInfo().
clGetDeviceIDs_ptr
std::function<decltype(clGetDeviceIDs)> clGetDeviceIDs_ptr = nullptr
Definition at line 119 of file OpenCL.h.
Referenced by clGetDeviceIDs().
clGetDeviceInfo_ptr
std::function<decltype(clGetDeviceInfo)> clGetDeviceInfo_ptr = nullptr
Definition at line 118 of file OpenCL.h.
Referenced by clGetDeviceInfo().
clGetEventProfilingInfo_ptr
std::function<decltype(clGetEventProfilingInfo)> clGetEventProfilingInfo_ptr = nullptr
Definition at line 126 of file OpenCL.h.
Referenced by clGetEventProfilingInfo().
clGetKernelInfo_ptr
std::function<decltype(clGetKernelInfo)> clGetKernelInfo_ptr = nullptr
Definition at line 125 of file OpenCL.h.
Referenced by clGetKernelInfo().
clGetKernelWorkGroupInfo_ptr
std::function<decltype(clGetKernelWorkGroupInfo)> clGetKernelWorkGroupInfo_ptr = nullptr
Definition at line 123 of file OpenCL.h.
Referenced by clGetKernelWorkGroupInfo().
clGetMemObjectInfo_ptr
std::function<decltype(clGetMemObjectInfo)> clGetMemObjectInfo_ptr = nullptr
Definition at line 120 of file OpenCL.h.
Referenced by clGetMemObjectInfo().
clGetPlatformIDs_ptr
std::function<decltype(clGetPlatformIDs)> clGetPlatformIDs_ptr = nullptr
Definition at line 122 of file OpenCL.h.
Referenced by clGetPlatformIDs().
clGetProgramBuildInfo_ptr
std::function<decltype(clGetProgramBuildInfo)> clGetProgramBuildInfo_ptr = nullptr
Definition at line 109 of file OpenCL.h.
Referenced by clGetProgramBuildInfo().
clGetProgramInfo_ptr
std::function<decltype(clGetProgramInfo)> clGetProgramInfo_ptr = nullptr
Definition at line 100 of file OpenCL.h.
Referenced by clGetProgramInfo().
clReleaseCommandQueue_ptr
std::function<decltype(clReleaseCommandQueue)> clReleaseCommandQueue_ptr = nullptr
Definition at line 106 of file OpenCL.h.
Referenced by clReleaseCommandQueue().
clReleaseContext_ptr
std::function<decltype(clReleaseContext)> clReleaseContext_ptr = nullptr
Definition at line 113 of file OpenCL.h.
Referenced by clReleaseContext().
clReleaseEvent_ptr
std::function<decltype(clReleaseEvent)> clReleaseEvent_ptr = nullptr
Definition at line 112 of file OpenCL.h.
Referenced by clReleaseEvent().
clReleaseKernel_ptr
std::function<decltype(clReleaseKernel)> clReleaseKernel_ptr = nullptr
Definition at line 95 of file OpenCL.h.
Referenced by clReleaseKernel().
clReleaseMemObject_ptr
std::function<decltype(clReleaseMemObject)> clReleaseMemObject_ptr = nullptr
Definition at line 117 of file OpenCL.h.
Referenced by clReleaseMemObject(), OpenCLMemoryUsage::test_start(), and OpenCLMemoryUsage::test_stop().
clReleaseProgram_ptr
std::function<decltype(clReleaseProgram)> clReleaseProgram_ptr = nullptr
Definition at line 103 of file OpenCL.h.
Referenced by clReleaseProgram().
clRetainCommandQueue_ptr
std::function<decltype(clRetainCommandQueue)> clRetainCommandQueue_ptr = nullptr
Definition at line 114 of file OpenCL.h.
Referenced by clRetainCommandQueue().
clRetainContext_ptr
std::function<decltype(clRetainContext)> clRetainContext_ptr = nullptr
Definition at line 104 of file OpenCL.h.
Referenced by clRetainContext().
clRetainEvent_ptr
std::function<decltype(clRetainEvent)> clRetainEvent_ptr = nullptr
Definition at line 121 of file OpenCL.h.
Referenced by clRetainEvent().
clRetainKernel_ptr
std::function<decltype(clRetainKernel)> clRetainKernel_ptr = nullptr
Definition at line 98 of file OpenCL.h.
Referenced by clRetainKernel().
clRetainMemObject_ptr
std::function<decltype(clRetainMemObject)> clRetainMemObject_ptr = nullptr
Definition at line 116 of file OpenCL.h.
Referenced by clRetainMemObject(), OpenCLMemoryUsage::test_start(), and OpenCLMemoryUsage::test_stop().
clRetainProgram_ptr
std::function<decltype(clRetainProgram)> clRetainProgram_ptr = nullptr
Definition at line 108 of file OpenCL.h.
Referenced by clRetainProgram().
clSetKernelArg_ptr
std::function<decltype(clSetKernelArg)> clSetKernelArg_ptr = nullptr
Definition at line 94 of file OpenCL.h.
Referenced by clSetKernelArg().
clSVMAlloc_ptr
std::function<decltype(clSVMAlloc)> clSVMAlloc_ptr = nullptr
Definition at line 127 of file OpenCL.h.
Referenced by clSVMAlloc(), OpenCLMemoryUsage::test_start(), and OpenCLMemoryUsage::test_stop().
clSVMFree_ptr
std::function<decltype(clSVMFree)> clSVMFree_ptr = nullptr
Definition at line 128 of file OpenCL.h.
Referenced by clSVMFree(), OpenCLMemoryUsage::test_start(), and OpenCLMemoryUsage::test_stop().
clWaitForEvents_ptr
std::function<decltype(clWaitForEvents)> clWaitForEvents_ptr = nullptr
Definition at line 132 of file OpenCL.h.
Referenced by clWaitForEvents().
The documentation for this class was generated from the following files:
arm_compute/core/CL/OpenCL.h
src/core/CL/OpenCL.cpp