Compute Library: arm_compute::utils::iterable Namespace Reference
arm_compute::utils::iterable Namespace Reference
Data Structures
class reverse_iterable
Reverse range iterable class.
Functions
template<typename T >
reverse_iterable< T > reverse_iterate (T &val)
Creates a reverse iterable for a given type.
Function Documentation
reverse_iterate()
reverse_iterable<T> arm_compute::utils::iterable::reverse_iterate (T & val)
Creates a reverse iterable for a given type.
Template Parameters
T Type to create a reverse iterable on
Parameters
[in] val Iterable input
Returns
Reverse iterable container
Definition at line 101 of file Iterable.h.
 {
     return reverse_iterable<T>(val);
 }
Referenced by arm_compute::graph::dfs(), SplitLayerSubTensorMutator::mutate(), and DepthConcatSubTensorMutator::mutate().