Compute Library: src/core/CL/cl_kernels/sobel_filter.cl File Reference
sobel_filter.cl File Reference
#include "helpers.h"
Macros
#define X0 -1
#define X1 -4
#define X2 -5
#define X3 0
#define X4 5
#define X5 4
#define X6 1
#define Y0 1
#define Y1 6
#define Y2 15
#define Y3 20
#define Y4 15
#define Y5 6
#define Y6 1
#define SOBEL1x1_HOR(src, gx, gy, idx)
#define SOBEL1x1_VERT(src, g, direction, idx)
#define SOBEL1x7(ptr, gx, gy)
#define SOBEL7x1(ptr, g, direction)
Functions
__kernel void sobel3x3 (__global uchar *src_ptr, uint src_stride_x, uint src_step_x, uint src_stride_y, uint src_step_y, uint src_offset_first_element_in_bytes, __global uchar *dst_gx_ptr, uint dst_gx_stride_x, uint dst_gx_step_x, uint dst_gx_stride_y, uint dst_gx_step_y, uint dst_gx_offset_first_element_in_bytes, __global uchar *dst_gy_ptr, uint dst_gy_stride_x, uint dst_gy_step_x, uint dst_gy_stride_y, uint dst_gy_step_y, uint dst_gy_offset_first_element_in_bytes)
This OpenCL kernel that computes a Sobel3x3 filter.
short16 sobel1x5 (Image *src, const short left1_coeff_gx, const short left2_coeff_gx, const short middle_coeff_gx, const short right1_coeff_gx, const short right2_coeff_gx, const short left1_coeff_gy, const short left2_coeff_gy, const short middle_coeff_gy, const short right1_coeff_gy, const short right2_coeff_gy)
Compute a 1D horizontal sobel filter 1x5 for 8 bytes assuming the input is made of 1 channel of 1 byte (i.e 8 pixels).
short8 sobel5x1 (Image *src, const short up1_coeff, const short up2_coeff, const short middle_coeff, const short down1_coeff, const short down2_coeff)
Compute a 1D vertical sobel filter 5x1 for 8 bytes assuming the input is made of 1 channel of 1 byte (i.e 8 pixels).
__kernel void sobel_separable1x5 (__global uchar *src_ptr, uint src_stride_x, uint src_step_x, uint src_stride_y, uint src_step_y, uint src_offset_first_element_in_bytes, __global uchar *dst_gx_ptr, uint dst_gx_stride_x, uint dst_gx_step_x, uint dst_gx_stride_y, uint dst_gx_step_y, uint dst_gx_offset_first_element_in_bytes, __global uchar *dst_gy_ptr, uint dst_gy_stride_x, uint dst_gy_step_x, uint dst_gy_stride_y, uint dst_gy_step_y, uint dst_gy_offset_first_element_in_bytes)
Apply a 1x5 sobel matrix to a single channel U8 input image and output two temporary channel S16 images.
__kernel void sobel_separable5x1 (__global uchar *src_x_ptr, uint src_x_stride_x, uint src_x_step_x, uint src_x_stride_y, uint src_x_step_y, uint src_x_offset_first_element_in_bytes, __global uchar *dst_gx_ptr, uint dst_gx_stride_x, uint dst_gx_step_x, uint dst_gx_stride_y, uint dst_gx_step_y, uint dst_gx_offset_first_element_in_bytes, __global uchar *src_y_ptr, uint src_y_stride_x, uint src_y_step_x, uint src_y_stride_y, uint src_y_step_y, uint src_y_offset_first_element_in_bytes, __global uchar *dst_gy_ptr, uint dst_gy_stride_x, uint dst_gy_step_x, uint dst_gy_stride_y, uint dst_gy_step_y, uint dst_gy_offset_first_element_in_bytes, int dummy)
Apply a 5x1 convolution matrix to two single channel S16 input temporary images and output two single channel S16 images.
__kernel void sobel_separable1x7 (__global uchar *src_ptr, uint src_stride_x, uint src_step_x, uint src_stride_y, uint src_step_y, uint src_offset_first_element_in_bytes, __global uchar *dst_gx_ptr, uint dst_gx_stride_x, uint dst_gx_step_x, uint dst_gx_stride_y, uint dst_gx_step_y, uint dst_gx_offset_first_element_in_bytes, __global uchar *dst_gy_ptr, uint dst_gy_stride_x, uint dst_gy_step_x, uint dst_gy_stride_y, uint dst_gy_step_y, uint dst_gy_offset_first_element_in_bytes)
Apply a 1x7 sobel matrix to a single channel U8 input image and output two temporary channel S16 images and leave the borders undefined.
__kernel void sobel_separable7x1 (__global uchar *src_x_ptr, uint src_x_stride_x, uint src_x_step_x, uint src_x_stride_y, uint src_x_step_y, uint src_x_offset_first_element_in_bytes, __global uchar *dst_gx_ptr, uint dst_gx_stride_x, uint dst_gx_step_x, uint dst_gx_stride_y, uint dst_gx_step_y, uint dst_gx_offset_first_element_in_bytes, __global uchar *src_y_ptr, uint src_y_stride_x, uint src_y_step_x, uint src_y_stride_y, uint src_y_step_y, uint src_y_offset_first_element_in_bytes, __global uchar *dst_gy_ptr, uint dst_gy_stride_x, uint dst_gy_step_x, uint dst_gy_stride_y, uint dst_gy_step_y, uint dst_gy_offset_first_element_in_bytes, int dummy)
Apply a 7x1 convolution matrix to two single channel S16 input temporary images and output two single channel S16 images and leave the borders undefined.
Macro Definition Documentation
SOBEL1x1_HOR
#define SOBEL1x1_HOR (src, gx, gy, idx)
Value:
{                                                                \
        int8 val = convert_int8(vload8(0, offset(src, idx - 3, 0))); \
        gx += val * X##idx;                                          \
        gy += val * Y##idx;                                          \
    }
Definition at line 384 of file sobel_filter.cl.
SOBEL1x1_VERT
#define SOBEL1x1_VERT (src, g, direction, idx)
Value:
{                                                                  \
        int8 val = vload8(0, (__global int *)offset(src, 0, idx - 3)); \
        g += val * (int8)direction##idx;                               \
    }
Definition at line 392 of file sobel_filter.cl.
SOBEL1x7
#define SOBEL1x7 (ptr, gx, gy)
Value:
SOBEL1x1_HOR(ptr, gx, gy, 0)                     \
    SOBEL1x1_HOR(ptr, gx, gy, 1)                 \
    SOBEL1x1_HOR(ptr, gx, gy, 2)             \
    SOBEL1x1_HOR(ptr, gx, gy, 3)         \
    SOBEL1x1_HOR(ptr, gx, gy, 4)     \
    SOBEL1x1_HOR(ptr, gx, gy, 5) \
    SOBEL1x1_HOR(ptr, gx, gy, 6)
Definition at line 399 of file sobel_filter.cl.
SOBEL7x1
#define SOBEL7x1 (ptr, g, direction)
Value:
SOBEL1x1_VERT(ptr, g, direction, 0)                     \
    SOBEL1x1_VERT(ptr, g, direction, 1)                 \
    SOBEL1x1_VERT(ptr, g, direction, 2)             \
    SOBEL1x1_VERT(ptr, g, direction, 3)         \
    SOBEL1x1_VERT(ptr, g, direction, 4)     \
    SOBEL1x1_VERT(ptr, g, direction, 5) \
    SOBEL1x1_VERT(ptr, g, direction, 6)
Definition at line 409 of file sobel_filter.cl.
X0
#define X0 -1
Definition at line 366 of file sobel_filter.cl.
X1
#define X1 -4
Definition at line 367 of file sobel_filter.cl.
X2
#define X2 -5
Definition at line 368 of file sobel_filter.cl.
X3
#define X3 0
Definition at line 369 of file sobel_filter.cl.
X4
#define X4 5
Definition at line 370 of file sobel_filter.cl.
X5
#define X5 4
Definition at line 371 of file sobel_filter.cl.
X6
#define X6 1
Definition at line 372 of file sobel_filter.cl.
Y0
#define Y0 1
Definition at line 375 of file sobel_filter.cl.
Y1
#define Y1 6
Definition at line 376 of file sobel_filter.cl.
Y2
#define Y2 15
Definition at line 377 of file sobel_filter.cl.
Y3
#define Y3 20
Definition at line 378 of file sobel_filter.cl.
Y4
#define Y4 15
Definition at line 379 of file sobel_filter.cl.
Y5
#define Y5 6
Definition at line 380 of file sobel_filter.cl.
Y6
#define Y6 1
Definition at line 381 of file sobel_filter.cl.
Function Documentation
sobel1x5()
short16 sobel1x5 (Image * src, const short left1_coeff_gx, const short left2_coeff_gx, const short middle_coeff_gx, const short right1_coeff_gx, const short right2_coeff_gx, const short left1_coeff_gy, const short left2_coeff_gy, const short middle_coeff_gy, const short right1_coeff_gy, const short right2_coeff_gy)
Compute a 1D horizontal sobel filter 1x5 for 8 bytes assuming the input is made of 1 channel of 1 byte (i.e 8 pixels).
Parameters
[in] src Pointer to source image.
[in] left1_coeff_gx Weight of the most left pixel for gx
[in] left2_coeff_gx Weight of the left pixel for gx
[in] middle_coeff_gx Weight of the middle pixel for gx
[in] right1_coeff_gx Weight of the right pixel for gx
[in] right2_coeff_gx Weight of the most right pixel for gx
[in] left1_coeff_gy Weight of the most left pixel for gy
[in] left2_coeff_gy Weight of the left pixel for gy
[in] middle_coeff_gy Weight of the middle pixel for gy
[in] right1_coeff_gy Weight of the right pixel for gy
[in] right2_coeff_gy Weight of the most right pixel for gy
Returns
a short16 containing short8 gx and short8 gy values.
Definition at line 154 of file sobel_filter.cl.
 {
     uchar16 temp = vload16(0, offset(src, -2, 0));
     short8  gx   = 0;
     short8  gy   = 0;
     short8  val;
     val = convert_short8(temp.s01234567);
     gx += val * (short8)left1_coeff_gx;
     gy += val * (short8)left1_coeff_gy;
     val = convert_short8(temp.s12345678);
     gx += val * (short8)left2_coeff_gx;
     gy += val * (short8)left2_coeff_gy;
     val = convert_short8(temp.s23456789);
     gx += val * (short8)middle_coeff_gx;
     gy += val * (short8)middle_coeff_gy;
     val = convert_short8(temp.s3456789a);
     gx += val * (short8)right1_coeff_gx;
     gy += val * (short8)right1_coeff_gy;
     val = convert_short8(temp.s456789ab);
     gx += val * (short8)right2_coeff_gx;
     gy += val * (short8)right2_coeff_gy;
     return (short16)(gx, gy);
 }
References offset(), and arm_compute::test::validation::src.
Referenced by sobel_separable1x5().
sobel3x3()
__kernel void sobel3x3 (__global uchar * src_ptr, uint src_stride_x, uint src_step_x, uint src_stride_y, uint src_step_y, uint src_offset_first_element_in_bytes, __global uchar * dst_gx_ptr, uint dst_gx_stride_x, uint dst_gx_step_x, uint dst_gx_stride_y, uint dst_gx_step_y, uint dst_gx_offset_first_element_in_bytes, __global uchar * dst_gy_ptr, uint dst_gy_stride_x, uint dst_gy_step_x, uint dst_gy_stride_y, uint dst_gy_step_y, uint dst_gy_offset_first_element_in_bytes)
This OpenCL kernel that computes a Sobel3x3 filter.
Attention
To enable computation of the X gradient -DGRAD_X must be passed at compile time, while computation of the Y gradient is performed when -DGRAD_Y is used. You can use both when computation of both gradients is required.
Parameters
[in] src_ptr Pointer to the source image. Supported data types: U8
[in] src_stride_x Stride of the source image in X dimension (in bytes)
[in] src_step_x src_stride_x * number of elements along X processed per workitem(in bytes)
[in] src_stride_y Stride of the source image in Y dimension (in bytes)
[in] src_step_y src_stride_y * number of elements along Y processed per workitem(in bytes)
[in] src_offset_first_element_in_bytes The offset of the first element in the source image
[out] dst_gx_ptr Pointer to the destination image. Supported data types: S16
[in] dst_gx_stride_x Stride of the destination image in X dimension (in bytes)
[in] dst_gx_step_x dst_gx_stride_x * number of elements along X processed per workitem(in bytes)
[in] dst_gx_stride_y Stride of the destination image in Y dimension (in bytes)
[in] dst_gx_step_y dst_gx_stride_y * number of elements along Y processed per workitem(in bytes)
[in] dst_gx_offset_first_element_in_bytes The offset of the first element in the destination image
[out] dst_gy_ptr Pointer to the destination image. Supported data types: S16
[in] dst_gy_stride_x Stride of the destination image in X dimension (in bytes)
[in] dst_gy_step_x dst_gy_stride_x * number of elements along X processed per workitem(in bytes)
[in] dst_gy_stride_y Stride of the destination image in Y dimension (in bytes)
[in] dst_gy_step_y dst_gy_stride_y * number of elements along Y processed per workitem(in bytes)
[in] dst_gy_offset_first_element_in_bytes The offset of the first element in the destination image
Definition at line 54 of file sobel_filter.cl.
 {
     Image src = CONVERT_TO_IMAGE_STRUCT(src);
 #ifdef GRAD_X
     Image dst_gx = CONVERT_TO_IMAGE_STRUCT(dst_gx);
 #endif /* GRAD_X */
 #ifdef GRAD_Y
     Image dst_gy = CONVERT_TO_IMAGE_STRUCT(dst_gy);
 #endif /* GRAD_Y */
     // Output pixels
 #ifdef GRAD_X
     short8 gx = (short8)0;
 #endif /* GRAD_X */
 #ifdef GRAD_Y
     short8 gy = (short8)0;
 #endif /* GRAD_Y */
     // Row0
     uchar16 temp   = vload16(0, offset(&src, -1, -1));
     short8  left   = convert_short8(temp.s01234567);
     short8  middle = convert_short8(temp.s12345678);
     short8  right  = convert_short8(temp.s23456789);
 #ifdef GRAD_X
     gx += left * (short8)(-1);
     gx += right * (short8)(+1);
 #endif /* GRAD_X */
 #ifdef GRAD_Y
     gy += left * (short8)(-1);
     gy += middle * (short8)(-2);
     gy += right * (short8)(-1);
 #endif /* GRAD_Y */
     // Row1
     temp  = vload16(0, offset(&src, -1, 0));
     left  = convert_short8(temp.s01234567);
     right = convert_short8(temp.s23456789);
 #ifdef GRAD_X
     gx += left * (short8)(-2);
     gx += right * (short8)(+2);
 #endif /* GRAD_X */
     // Row2
     temp   = vload16(0, offset(&src, -1, 1));
     left   = convert_short8(temp.s01234567);
     middle = convert_short8(temp.s12345678);
     right  = convert_short8(temp.s23456789);
 #ifdef GRAD_X
     gx += left * (short8)(-1);
     gx += right * (short8)(+1);
 #endif /* GRAD_X */
 #ifdef GRAD_Y
     gy += left * (short8)(+1);
     gy += middle * (short8)(+2);
     gy += right * (short8)(+1);
 #endif /* GRAD_Y */
     // Store results
 #ifdef GRAD_X
     vstore8(gx, 0, ((__global short *)dst_gx.ptr));
 #endif /* GRAD_X */
 #ifdef GRAD_Y
     vstore8(gy, 0, ((__global short *)dst_gy.ptr));
 #endif /* GRAD_Y */
 }
References CONVERT_TO_IMAGE_STRUCT, offset(), Image::ptr, and arm_compute::test::validation::src.
sobel5x1()
short8 sobel5x1 (Image * src, const short up1_coeff, const short up2_coeff, const short middle_coeff, const short down1_coeff, const short down2_coeff)
Compute a 1D vertical sobel filter 5x1 for 8 bytes assuming the input is made of 1 channel of 1 byte (i.e 8 pixels).
Parameters
[in] src Pointer to source image.
[in] up1_coeff Weight of the most up pixel
[in] up2_coeff Weight of the up pixel
[in] middle_coeff Weight of the middle pixel
[in] down1_coeff Weight of the down pixel
[in] down2_coeff Weight of the most down pixel
Returns
a short8 containing 8 convoluted values.
Definition at line 206 of file sobel_filter.cl.
 {
     short8 val;
     short8 out = (short8)0;
     val = vload8(0, (__global short *)offset(src, 0, -2));
     out += val * (short8)up1_coeff;
     val = vload8(0, (__global short *)offset(src, 0, -1));
     out += val * (short8)up2_coeff;
     val = vload8(0, (__global short *)offset(src, 0, 0));
     out += val * (short8)middle_coeff;
     val = vload8(0, (__global short *)offset(src, 0, 1));
     out += val * (short8)down1_coeff;
     val = vload8(0, (__global short *)offset(src, 0, 2));
     out += val * (short8)down2_coeff;
     return (short8)(out);
 }
References offset(), and arm_compute::test::validation::src.
Referenced by sobel_separable5x1().
sobel_separable1x5()
__kernel void sobel_separable1x5 (__global uchar * src_ptr, uint src_stride_x, uint src_step_x, uint src_stride_y, uint src_step_y, uint src_offset_first_element_in_bytes, __global uchar * dst_gx_ptr, uint dst_gx_stride_x, uint dst_gx_step_x, uint dst_gx_stride_y, uint dst_gx_step_y, uint dst_gx_offset_first_element_in_bytes, __global uchar * dst_gy_ptr, uint dst_gy_stride_x, uint dst_gy_step_x, uint dst_gy_stride_y, uint dst_gy_step_y, uint dst_gy_offset_first_element_in_bytes)
Apply a 1x5 sobel matrix to a single channel U8 input image and output two temporary channel S16 images.
Attention
To enable computation of the X gradient -DGRAD_X must be passed at compile time, while computation of the Y gradient is performed when -DGRAD_Y is used. You can use both when computation of both gradients is required.
Parameters
[in] src_ptr Pointer to the source image.. Supported data types: U8
[in] src_stride_x Stride of the source image in X dimension (in bytes)
[in] src_step_x src_stride_x * number of elements along X processed per workitem(in bytes)
[in] src_stride_y Stride of the source image in Y dimension (in bytes)
[in] src_step_y src_stride_y * number of elements along Y processed per workitem(in bytes)
[in] src_offset_first_element_in_bytes The offset of the first element in the source image
[out] dst_gx_ptr Pointer to the destination image.. Supported data types: S16
[in] dst_gx_stride_x Stride of the destination image in X dimension (in bytes)
[in] dst_gx_step_x dst_gx_stride_x * number of elements along X processed per workitem(in bytes)
[in] dst_gx_stride_y Stride of the destination image in Y dimension (in bytes)
[in] dst_gx_step_y dst_gx_stride_y * number of elements along Y processed per workitem(in bytes)
[in] dst_gx_offset_first_element_in_bytes The offset of the first element in the destination image
[out] dst_gy_ptr Pointer to the destination image. Supported data types: S16
[in] dst_gy_stride_x Stride of the destination image in X dimension (in bytes)
[in] dst_gy_step_x dst_gy_stride_x * number of elements along X processed per workitem(in bytes)
[in] dst_gy_stride_y Stride of the destination image in Y dimension (in bytes)
[in] dst_gy_step_y dst_gy_stride_y * number of elements along Y processed per workitem(in bytes)
[in] dst_gy_offset_first_element_in_bytes The offset of the first element in the destination image
Definition at line 259 of file sobel_filter.cl.
 {
     Image src = CONVERT_TO_IMAGE_STRUCT(src);
 #ifdef GRAD_X
     Image dst_gx = CONVERT_TO_IMAGE_STRUCT(dst_gx);
 #endif /* GRAD_X */
 #ifdef GRAD_Y
     Image dst_gy = CONVERT_TO_IMAGE_STRUCT(dst_gy);
 #endif /* GRAD_Y */
     // Output pixels
     short16 gx_gy = sobel1x5(&src,
                              -1, -2, 0, 2, 1,
                              1, 4, 6, 4, 1);
     // Store result in dst
 #ifdef GRAD_X
     vstore8(gx_gy.s01234567, 0, ((__global short *)dst_gx.ptr));
 #endif /* GRAD_X */
 #ifdef GRAD_Y
     vstore8(gx_gy.s89ABCDEF, 0, ((__global short *)dst_gy.ptr));
 #endif /* GRAD_Y */
 }
References CONVERT_TO_IMAGE_STRUCT, Image::ptr, sobel1x5(), and arm_compute::test::validation::src.
sobel_separable1x7()
__kernel void sobel_separable1x7 (__global uchar * src_ptr, uint src_stride_x, uint src_step_x, uint src_stride_y, uint src_step_y, uint src_offset_first_element_in_bytes, __global uchar * dst_gx_ptr, uint dst_gx_stride_x, uint dst_gx_step_x, uint dst_gx_stride_y, uint dst_gx_step_y, uint dst_gx_offset_first_element_in_bytes, __global uchar * dst_gy_ptr, uint dst_gy_stride_x, uint dst_gy_step_x, uint dst_gy_stride_y, uint dst_gy_step_y, uint dst_gy_offset_first_element_in_bytes)
Apply a 1x7 sobel matrix to a single channel U8 input image and output two temporary channel S16 images and leave the borders undefined.
Attention
To enable computation of the X gradient -DGRAD_X must be passed at compile time, while computation of the Y gradient is performed when -DGRAD_Y is used. You can use both when computation of both gradients is required.
Parameters
[in] src_ptr Pointer to the source image. Supported data types: U8
[in] src_stride_x Stride of the source image in X dimension (in bytes)
[in] src_step_x src_stride_x * number of elements along X processed per workitem(in bytes)
[in] src_stride_y Stride of the source image in Y dimension (in bytes)
[in] src_step_y src_stride_y * number of elements along Y processed per workitem(in bytes)
[in] src_offset_first_element_in_bytes The offset of the first element in the source image
[out] dst_gx_ptr Pointer to the destination image. Supported data types: S32
[in] dst_gx_stride_x Stride of the destination image in X dimension (in bytes)
[in] dst_gx_step_x dst_gx_stride_x * number of elements along X processed per workitem(in bytes)
[in] dst_gx_stride_y Stride of the destination image in Y dimension (in bytes)
[in] dst_gx_step_y dst_gx_stride_y * number of elements along Y processed per workitem(in bytes)
[in] dst_gx_offset_first_element_in_bytes The offset of the first element in the destination image
[out] dst_gy_ptr Pointer to the destination image. Supported data types: S32
[in] dst_gy_stride_x Stride of the destination image in X dimension (in bytes)
[in] dst_gy_step_x dst_gy_stride_x * number of elements along X processed per workitem(in bytes)
[in] dst_gy_stride_y Stride of the destination image in Y dimension (in bytes)
[in] dst_gy_step_y dst_gy_stride_y * number of elements along Y processed per workitem(in bytes)
[in] dst_gy_offset_first_element_in_bytes The offset of the first element in the destination image
Definition at line 442 of file sobel_filter.cl.
 {
     Image src = CONVERT_TO_IMAGE_STRUCT(src);
 #ifdef GRAD_X
     Image dst_gx = CONVERT_TO_IMAGE_STRUCT(dst_gx);
 #endif /* GRAD_X */
 #ifdef GRAD_Y
     Image dst_gy = CONVERT_TO_IMAGE_STRUCT(dst_gy);
 #endif /* GRAD_Y */
     int8 gx = (int8)0;
     int8 gy = (int8)0;
     SOBEL1x7(&src, gx, gy);
     // Store result in dst
 #ifdef GRAD_X
     vstore8(gx, 0, ((__global int *)dst_gx.ptr));
 #endif /* GRAD_X */
 #ifdef GRAD_Y
     vstore8(gy, 0, ((__global int *)dst_gy.ptr));
 #endif /* GRAD_Y */
 }
References CONVERT_TO_IMAGE_STRUCT, Image::ptr, SOBEL1x7, and arm_compute::test::validation::src.
sobel_separable5x1()
__kernel void sobel_separable5x1 (__global uchar * src_x_ptr, uint src_x_stride_x, uint src_x_step_x, uint src_x_stride_y, uint src_x_step_y, uint src_x_offset_first_element_in_bytes, __global uchar * dst_gx_ptr, uint dst_gx_stride_x, uint dst_gx_step_x, uint dst_gx_stride_y, uint dst_gx_step_y, uint dst_gx_offset_first_element_in_bytes, __global uchar * src_y_ptr, uint src_y_stride_x, uint src_y_step_x, uint src_y_stride_y, uint src_y_step_y, uint src_y_offset_first_element_in_bytes, __global uchar * dst_gy_ptr, uint dst_gy_stride_x, uint dst_gy_step_x, uint dst_gy_stride_y, uint dst_gy_step_y, uint dst_gy_offset_first_element_in_bytes, int dummy)
Apply a 5x1 convolution matrix to two single channel S16 input temporary images and output two single channel S16 images.
Attention
To enable computation of the X gradient -DGRAD_X must be passed at compile time, while computation of the Y gradient is performed when -DGRAD_Y is used. You can use both when computation of both gradients is required.
Parameters
[in] src_x_ptr Pointer to the source image.. Supported data types: S16
[in] src_x_stride_x Stride of the source image in X dimension (in bytes)
[in] src_x_step_x src_x_stride_x * number of elements along X processed per workitem(in bytes)
[in] src_x_stride_y Stride of the source image in Y dimension (in bytes)
[in] src_x_step_y src_x_stride_y * number of elements along Y processed per workitem(in bytes)
[in] src_x_offset_first_element_in_bytes The offset of the first element in the source image
[out] dst_gx_ptr Pointer to the destination image. Supported data types: S16
[in] dst_gx_stride_x Stride of the destination image in X dimension (in bytes)
[in] dst_gx_step_x dst_gx_stride_x * number of elements along X processed per workitem(in bytes)
[in] dst_gx_stride_y Stride of the destination image in Y dimension (in bytes)
[in] dst_gx_step_y dst_gx_stride_y * number of elements along Y processed per workitem(in bytes)
[in] dst_gx_offset_first_element_in_bytes The offset of the first element in the destination image
[in] src_y_ptr Pointer to the source image. Supported data types: S16
[in] src_y_stride_x Stride of the source image in X dimension (in bytes)
[in] src_y_step_x src_y_stride_x * number of elements along X processed per workitem(in bytes)
[in] src_y_stride_y Stride of the source image in Y dimension (in bytes)
[in] src_y_step_y src_y_stride_y * number of elements along Y processed per workitem(in bytes)
[in] src_y_offset_first_element_in_bytes The offset of the first element in the source image
[out] dst_gy_ptr Pointer to the destination image. Supported data types: S16
[in] dst_gy_stride_x Stride of the destination image in X dimension (in bytes)
[in] dst_gy_step_x dst_gy_stride_x * number of elements along X processed per workitem(in bytes)
[in] dst_gy_stride_y Stride of the destination image in Y dimension (in bytes)
[in] dst_gy_step_y dst_gy_stride_y * number of elements along Y processed per workitem(in bytes)
[in] dst_gy_offset_first_element_in_bytes The offset of the first element in the destination image
[in] dummy Dummy parameter to easy conditional inclusion
Definition at line 325 of file sobel_filter.cl.
 {
 #ifdef GRAD_X
     Image src_x  = CONVERT_TO_IMAGE_STRUCT(src_x);
     Image dst_gx = CONVERT_TO_IMAGE_STRUCT(dst_gx);
 #endif /* GRAD_X */
 #ifdef GRAD_Y
     Image src_y  = CONVERT_TO_IMAGE_STRUCT(src_y);
     Image dst_gy = CONVERT_TO_IMAGE_STRUCT(dst_gy);
 #endif /* GRAD_Y */
 #ifdef GRAD_X
     short8 gx = sobel5x1(&src_x,
                          1, 4, 6, 4, 1);
     vstore8(gx, 0, ((__global short *)dst_gx.ptr));
 #endif /* GRAD_X */
 #ifdef GRAD_Y
     short8 gy = sobel5x1(&src_y,
                          -1, -2, 0, 2, 1);
     vstore8(gy, 0, ((__global short *)dst_gy.ptr));
 #endif /* GRAD_Y */
 }
References CONVERT_TO_IMAGE_STRUCT, Image::ptr, and sobel5x1().
sobel_separable7x1()
__kernel void sobel_separable7x1 (__global uchar * src_x_ptr, uint src_x_stride_x, uint src_x_step_x, uint src_x_stride_y, uint src_x_step_y, uint src_x_offset_first_element_in_bytes, __global uchar * dst_gx_ptr, uint dst_gx_stride_x, uint dst_gx_step_x, uint dst_gx_stride_y, uint dst_gx_step_y, uint dst_gx_offset_first_element_in_bytes, __global uchar * src_y_ptr, uint src_y_stride_x, uint src_y_step_x, uint src_y_stride_y, uint src_y_step_y, uint src_y_offset_first_element_in_bytes, __global uchar * dst_gy_ptr, uint dst_gy_stride_x, uint dst_gy_step_x, uint dst_gy_stride_y, uint dst_gy_step_y, uint dst_gy_offset_first_element_in_bytes, int dummy)
Apply a 7x1 convolution matrix to two single channel S16 input temporary images and output two single channel S16 images and leave the borders undefined.
Attention
To enable computation of the X gradient -DGRAD_X must be passed at compile time, while computation of the Y gradient is performed when -DGRAD_Y is used. You can use both when computation of both gradients is required.
Parameters
[in] src_x_ptr Pointer to the source image. Supported data types: S32
[in] src_x_stride_x Stride of the source image in X dimension (in bytes)
[in] src_x_step_x src_x_stride_x * number of elements along X processed per workitem(in bytes)
[in] src_x_stride_y Stride of the source image in Y dimension (in bytes)
[in] src_x_step_y src_x_stride_y * number of elements along Y processed per workitem(in bytes)
[in] src_x_offset_first_element_in_bytes The offset of the first element in the source image
[out] dst_gx_ptr Pointer to the destination image. Supported data types: S16
[in] dst_gx_stride_x Stride of the destination image in X dimension (in bytes)
[in] dst_gx_step_x dst_gx_stride_x * number of elements along X processed per workitem(in bytes)
[in] dst_gx_stride_y Stride of the destination image in Y dimension (in bytes)
[in] dst_gx_step_y dst_gx_stride_y * number of elements along Y processed per workitem(in bytes)
[in] dst_gx_offset_first_element_in_bytes The offset of the first element in the destination image
[in] src_y_ptr Pointer to the source image. Supported data types: S32
[in] src_y_stride_x Stride of the source image in X dimension (in bytes)
[in] src_y_step_x src_y_stride_x * number of elements along X processed per workitem(in bytes)
[in] src_y_stride_y Stride of the source image in Y dimension (in bytes)
[in] src_y_step_y src_y_stride_y * number of elements along Y processed per workitem(in bytes)
[in] src_y_offset_first_element_in_bytes The offset of the first element in the source image
[out] dst_gy_ptr Pointer to the destination image. Supported data types: S16
[in] dst_gy_stride_x Stride of the destination image in X dimension (in bytes)
[in] dst_gy_step_x dst_gy_stride_x * number of elements along X processed per workitem(in bytes)
[in] dst_gy_stride_y Stride of the destination image in Y dimension (in bytes)
[in] dst_gy_step_y dst_gy_stride_y * number of elements along Y processed per workitem(in bytes)
[in] dst_gy_offset_first_element_in_bytes The offset of the first element in the destination image
[in] dummy Dummy parameter to easy conditional inclusion
Definition at line 506 of file sobel_filter.cl.
 {
 #ifdef GRAD_X
     Image src_x  = CONVERT_TO_IMAGE_STRUCT(src_x);
     Image dst_gx = CONVERT_TO_IMAGE_STRUCT(dst_gx);
 #endif /* GRAD_X */
 #ifdef GRAD_Y
     Image src_y  = CONVERT_TO_IMAGE_STRUCT(src_y);
     Image dst_gy = CONVERT_TO_IMAGE_STRUCT(dst_gy);
 #endif /* GRAD_Y */
     // Output pixels
 #ifdef GRAD_X
     int8 gx = 0;
     SOBEL7x1(&src_x, gx, Y);
     vstore8(gx, 0, (__global int *)dst_gx.ptr);
 #endif /* GRAD_X */
 #ifdef GRAD_Y
     int8 gy = 0;
     SOBEL7x1(&src_y, gy, X);
     vstore8(gy, 0, (__global int *)dst_gy.ptr);
 #endif /* GRAD_Y */
 }
References CONVERT_TO_IMAGE_STRUCT, Image::ptr, and SOBEL7x1.