Compute Library: CLArithmeticSubtractionKernel Class Reference
CLArithmeticSubtractionKernel Class Reference
Interface for the arithmetic subtraction kernel.
#include <CLArithmeticSubtractionKernel.h>
Public Member Functions
CLArithmeticSubtractionKernel ()
Default constructor.
CLArithmeticSubtractionKernel (const CLArithmeticSubtractionKernel &)=delete
Prevent instances of this class from being copied (As this class contains pointers)
CLArithmeticSubtractionKernel & operator= (const CLArithmeticSubtractionKernel &)=delete
Prevent instances of this class from being copied (As this class contains pointers)
CLArithmeticSubtractionKernel (CLArithmeticSubtractionKernel &&)=default
Allow instances of this class to be moved.
CLArithmeticSubtractionKernel & operator= (CLArithmeticSubtractionKernel &&)=default
Allow instances of this class to be moved.
~CLArithmeticSubtractionKernel ()=default
Default destructor.
void configure (const ICLTensor *input1, const ICLTensor *input2, ICLTensor *output, ConvertPolicy policy)
Initialise the kernel's inputs, output and conversion policy.
void run (const Window &window, cl::CommandQueue &queue) override
Enqueue the OpenCL kernel to process the given window on the passed OpenCL command queue.
BorderSize border_size () const override
The size of the border for that kernel.
Public Member Functions inherited from ICLKernel
ICLKernel ()
Constructor.
cl::Kernel & kernel ()
Returns a reference to the OpenCL kernel of this object.
template<typename T >
void add_1D_array_argument (unsigned int &idx, const ICLArray< T > *array, const Strides &strides, unsigned int num_dimensions, const Window &window)
Add the passed 1D array's parameters to the object's kernel's arguments starting from the index idx.
void add_1D_tensor_argument (unsigned int &idx, const ICLTensor *tensor, const Window &window)
Add the passed 1D tensor's parameters to the object's kernel's arguments starting from the index idx.
void add_2D_tensor_argument (unsigned int &idx, const ICLTensor *tensor, const Window &window)
Add the passed 2D tensor's parameters to the object's kernel's arguments starting from the index idx.
void add_3D_tensor_argument (unsigned int &idx, const ICLTensor *tensor, const Window &window)
Add the passed 3D tensor's parameters to the object's kernel's arguments starting from the index idx.
void add_4D_tensor_argument (unsigned int &idx, const ICLTensor *tensor, const Window &window)
Add the passed 4D tensor's parameters to the object's kernel's arguments starting from the index idx.
template<typename T >
void add_argument (unsigned int &idx, T value)
Add the passed parameters to the object's kernel's arguments starting from the index idx.
void set_lws_hint (const cl::NDRange &lws_hint)
Set the Local-Workgroup-Size hint.
cl::NDRange lws_hint () const
Return the Local-Workgroup-Size hint.
const std::string & config_id () const
Get the configuration ID.
void set_target (GPUTarget target)
Set the targeted GPU architecture.
void set_target (cl::Device &device)
Set the targeted GPU architecture according to the CL device.
GPUTarget get_target () const
Get the targeted GPU architecture.
size_t get_max_workgroup_size ()
Get the maximum workgroup size for the device the CLKernelLibrary uses.
template<typename T , unsigned int dimension_size>
void add_array_argument (unsigned &idx, const ICLArray< T > *array, const Strides &strides, unsigned int num_dimensions, const Window &window)
Add the passed array's parameters to the object's kernel's arguments starting from the index idx.
template<unsigned int dimension_size>
void add_tensor_argument (unsigned &idx, const ICLTensor *tensor, const Window &window)
Public Member Functions inherited from IKernel
IKernel ()
Constructor.
virtual ~IKernel ()=default
Destructor.
virtual bool is_parallelisable () const
Indicates whether or not the kernel is parallelisable.
const Window & window () const
The maximum window the kernel can be executed on.
Static Public Member Functions
static Status validate (const ITensorInfo *input1, const ITensorInfo *input2, const ITensorInfo *output, ConvertPolicy policy)
Static function to check if given info will lead to a valid configuration of CLArithmeticSubtractionKernel.
Static Public Member Functions inherited from ICLKernel
static constexpr unsigned int num_arguments_per_1D_array ()
Returns the number of arguments enqueued per 1D array object.
static constexpr unsigned int num_arguments_per_1D_tensor ()
Returns the number of arguments enqueued per 1D tensor object.
static constexpr unsigned int num_arguments_per_2D_tensor ()
Returns the number of arguments enqueued per 2D tensor object.
static constexpr unsigned int num_arguments_per_3D_tensor ()
Returns the number of arguments enqueued per 3D tensor object.
static constexpr unsigned int num_arguments_per_4D_tensor ()
Returns the number of arguments enqueued per 4D tensor object.
static cl::NDRange gws_from_window (const Window &window)
Get the global work size given an execution window.
Detailed Description
Interface for the arithmetic subtraction kernel.
Arithmetic subtraction is computed by:
\[ output(x,y) = input1(x,y) - input2(x,y) \]
Definition at line 40 of file CLArithmeticSubtractionKernel.h.
Constructor & Destructor Documentation
CLArithmeticSubtractionKernel() [1/3]
CLArithmeticSubtractionKernel ()
Default constructor.
Definition at line 123 of file CLArithmeticSubtractionKernel.cpp.
     : _input1(nullptr), _input2(nullptr), _output(nullptr)
 {
 }
CLArithmeticSubtractionKernel() [2/3]
CLArithmeticSubtractionKernel (const CLArithmeticSubtractionKernel &) delete
Prevent instances of this class from being copied (As this class contains pointers)
CLArithmeticSubtractionKernel() [3/3]
CLArithmeticSubtractionKernel (CLArithmeticSubtractionKernel &&) default
Allow instances of this class to be moved.
~CLArithmeticSubtractionKernel()
~CLArithmeticSubtractionKernel () default
Default destructor.
Member Function Documentation
border_size()
BorderSize border_size () const override virtual
The size of the border for that kernel.
Returns
The width in number of elements of the border.
Reimplemented from IKernel.
Definition at line 226 of file CLArithmeticSubtractionKernel.cpp.
References ITensorInfo::dimension(), ITensor::info(), and arm_compute::U.
 {
     const unsigned int replicateSize = _output->info()->dimension(0) - std::min(_input1->info()->dimension(0), _input2->info()->dimension(0));
     const unsigned int border        = std::min<unsigned int>(num_elems_processed_per_iteration - 1U, replicateSize);
     return BorderSize(0, border, 0, 0);
 }
configure()
void configure (const ICLTensor * input1, const ICLTensor * input2, ICLTensor * output, ConvertPolicy policy)
Initialise the kernel's inputs, output and conversion policy.
Parameters
[in] input1 First tensor input. Data types supported: U8/QASYMM8/S16/F16/F32.
[in] input2 Second tensor input. Data types supported: U8/QASYMM8/S16/F16/F32.
[out] output Output tensor. Data types supported: U8 (Only if both inputs are U8), QASYMM8/S16/F16/F32.
[in] policy Policy to use to handle overflow.
Definition at line 128 of file CLArithmeticSubtractionKernel.cpp.
References CLBuildOptions::add_option(), CLBuildOptions::add_option_if_else(), ARM_COMPUTE_ERROR_ON_NULLPTR, ARM_COMPUTE_ERROR_THROW_ON, CLKernelLibrary::create_kernel(), ITensorInfo::data_type(), CLKernelLibrary::get(), arm_compute::get_cl_type_from_data_type(), ITensor::info(), arm_compute::is_data_type_float(), arm_compute::is_data_type_quantized_asymmetric(), QuantizationInfo::offset, CLBuildOptions::options(), arm_compute::test::validation::policy, ITensorInfo::quantization_info(), QuantizationInfo::scale, arm_compute::support::cpp11::to_string(), and arm_compute::WRAP.
Referenced by CLLSTMLayer::configure().
 {
     ARM_COMPUTE_ERROR_ON_NULLPTR(input1, input2, output);
     ARM_COMPUTE_ERROR_THROW_ON(validate_arguments(*input1->info(), *input2->info(), *output->info(), policy));
     // Configure kernel window
     auto win_config = validate_and_configure_window(*input1->info(), *input2->info(), *output->info());
     ARM_COMPUTE_ERROR_THROW_ON(win_config.first);
     _input1 = input1;
     _input2 = input2;
     _output = output;
     bool has_float_out = is_data_type_float(output->info()->data_type());
     // Setup kernel
     std::string kernel_name = "arithmetic_sub";
     // Set kernel build options
     CLBuildOptions build_opts;
     build_opts.add_option_if_else(policy == ConvertPolicy::WRAP || has_float_out, "-DWRAP", "-DSATURATE");
     build_opts.add_option("-DDATA_TYPE_IN1=" + get_cl_type_from_data_type(input1->info()->data_type()));
     build_opts.add_option("-DDATA_TYPE_IN2=" + get_cl_type_from_data_type(input2->info()->data_type()));
     build_opts.add_option("-DDATA_TYPE_OUT=" + get_cl_type_from_data_type(output->info()->data_type()));
     if(is_data_type_quantized_asymmetric(input1->info()->data_type()))
     {
         build_opts.add_option("-DOFFSET_IN1=" + support::cpp11::to_string(input1->info()->quantization_info().offset));
         build_opts.add_option("-DOFFSET_IN2=" + support::cpp11::to_string(input2->info()->quantization_info().offset));
         build_opts.add_option("-DOFFSET_OUT=" + support::cpp11::to_string(output->info()->quantization_info().offset));
         build_opts.add_option("-DSCALE_IN1=" + support::cpp11::to_string(input1->info()->quantization_info().scale));
         build_opts.add_option("-DSCALE_IN2=" + support::cpp11::to_string(input2->info()->quantization_info().scale));
         build_opts.add_option("-DSCALE_OUT=" + support::cpp11::to_string(output->info()->quantization_info().scale));
         kernel_name += "_quantized";
     }
     // Create kernel
     _kernel = static_cast<cl::Kernel>(CLKernelLibrary::get().create_kernel(kernel_name, build_opts.options()));
     // Configure kernel window
     ICLKernel::configure_internal(win_config.second);
 }
operator=() [1/2]
CLArithmeticSubtractionKernel& operator= (const CLArithmeticSubtractionKernel &) delete
Prevent instances of this class from being copied (As this class contains pointers)
operator=() [2/2]
CLArithmeticSubtractionKernel& operator= (CLArithmeticSubtractionKernel &&) default
Allow instances of this class to be moved.
run()
void run (const Window & window, cl::CommandQueue & queue) override virtual
Enqueue the OpenCL kernel to process the given window on the passed OpenCL command queue.
Note
The queue is not flushed by this method, and therefore the kernel will not have been executed by the time this method returns.
Parameters
[in] window Region on which to execute the kernel. (Must be a valid region of the window returned by window()).
[in,out] queue Command queue on which to enqueue the kernel.
Implements ICLKernel.
Definition at line 180 of file CLArithmeticSubtractionKernel.cpp.
References ICLKernel::add_3D_tensor_argument(), ARM_COMPUTE_ERROR_ON_INVALID_SUBWINDOW, ARM_COMPUTE_ERROR_ON_UNCONFIGURED_KERNEL, Window::broadcast_if_dimension_le_one(), Window::collapse_if_possible(), TensorShape::collapsed_from(), Window::DimZ, arm_compute::enqueue(), Window::first_slice_window_3D(), ITensor::info(), Dimensions< T >::num_dimensions(), arm_compute::test::validation::reference::slice(), Window::slide_window_slice_3D(), ITensorInfo::tensor_shape(), TensorShape::total_size(), and IKernel::window().
 {
     ARM_COMPUTE_ERROR_ON_UNCONFIGURED_KERNEL(this);
     ARM_COMPUTE_ERROR_ON_INVALID_SUBWINDOW(ICLKernel::window(), window);
     const TensorShape &in_shape1 = _input1->info()->tensor_shape();
     const TensorShape &in_shape2 = _input2->info()->tensor_shape();
     const TensorShape &out_shape = _output->info()->tensor_shape();
     // Collapse only if broadcast dimensions is less than 2, or in case of no broadcasting
     bool can_collapse = true;
     if(std::min(in_shape1.total_size(), in_shape2.total_size()) > 1)
     {
         can_collapse = (std::min(in_shape1.num_dimensions(), in_shape2.num_dimensions()) > Window::DimZ);
         for(size_t d = Window::DimZ; can_collapse && (d < out_shape.num_dimensions()); d++)
         {
             can_collapse = (in_shape1[d] == in_shape2[d]);
         }
     }
     bool   has_collapsed = false;
     Window collapsed     = can_collapse ? window.collapse_if_possible(ICLKernel::window(), Window::DimZ, &has_collapsed) : window;
     const TensorShape &in_shape1_collapsed = has_collapsed ? in_shape1.collapsed_from(Window::DimZ) : in_shape1;
     const TensorShape &in_shape2_collapsed = has_collapsed ? in_shape2.collapsed_from(Window::DimZ) : in_shape2;
     Window slice        = collapsed.first_slice_window_3D();
     Window slice_input1 = slice.broadcast_if_dimension_le_one(in_shape1_collapsed);
     Window slice_input2 = slice.broadcast_if_dimension_le_one(in_shape2_collapsed);
     do
     {
         unsigned int idx = 0;
         add_3D_tensor_argument(idx, _input1, slice_input1);
         add_3D_tensor_argument(idx, _input2, slice_input2);
         add_3D_tensor_argument(idx, _output, slice);
         enqueue(queue, *this, slice);
         collapsed.slide_window_slice_3D(slice_input1);
         collapsed.slide_window_slice_3D(slice_input2);
     }
     while(collapsed.slide_window_slice_3D(slice));
 }
validate()
Status validate (const ITensorInfo * input1, const ITensorInfo * input2, const ITensorInfo * output, ConvertPolicy policy) static
Static function to check if given info will lead to a valid configuration of CLArithmeticSubtractionKernel.
Parameters
[in] input1 First tensor input info. Data types supported: U8/QASYMM8/S16/F16/F32.
[in] input2 Second tensor input info. Data types supported: U8/QASYMM8/S16/F16/F32.
[in] output Output tensor info. Data types supported: U8 (Only if both inputs are U8), QASYMM8/S16/F16/F32.
[in] policy Policy to use to handle overflow.
Returns
a status
Definition at line 170 of file CLArithmeticSubtractionKernel.cpp.
References ARM_COMPUTE_RETURN_ERROR_ON_NULLPTR, ARM_COMPUTE_RETURN_ON_ERROR, and ICloneable< T >::clone().
Referenced by CLArithmeticSubtraction::validate(), and CLLSTMLayer::validate().
 {
     ARM_COMPUTE_RETURN_ERROR_ON_NULLPTR(input1, input2, output);
     ARM_COMPUTE_RETURN_ON_ERROR(validate_arguments(*input1, *input2, *output, policy));
     ARM_COMPUTE_RETURN_ON_ERROR(validate_and_configure_window(*input1->clone(), *input2->clone(), *output->clone()).first);
     return Status{};
 }
The documentation for this class was generated from the following files:
arm_compute/core/CL/kernels/CLArithmeticSubtractionKernel.h
src/core/CL/kernels/CLArithmeticSubtractionKernel.cpp