Compute Library: NEPriorBoxLayerKernel Class Reference
NEPriorBoxLayerKernel Class Reference
Interface for the kernel to calculate prior boxes.
#include <NEPriorBoxLayerKernel.h>
Public Member Functions
const char * name () const override
Name of the kernel.
NEPriorBoxLayerKernel ()
Default constructor.
NEPriorBoxLayerKernel (const NEPriorBoxLayerKernel &)=delete
Prevent instances of this class from being copied (As this class contains pointers)
NEPriorBoxLayerKernel & operator= (const NEPriorBoxLayerKernel &)=delete
Prevent instances of this class from being copied (As this class contains pointers)
NEPriorBoxLayerKernel (NEPriorBoxLayerKernel &&)=default
Allow instances of this class to be moved.
NEPriorBoxLayerKernel & operator= (NEPriorBoxLayerKernel &&)=default
Allow instances of this class to be moved.
void configure (const ITensor *input1, const ITensor *input2, ITensor *output, const PriorBoxLayerInfo &info)
Set the input and output tensors.
void run (const Window &window, const ThreadInfo &info) override
Execute the kernel on the passed window.
Public Member Functions inherited from ICPPKernel
virtual ~ICPPKernel ()=default
Default destructor.
Public Member Functions inherited from IKernel
IKernel ()
Constructor.
virtual ~IKernel ()=default
Destructor.
virtual bool is_parallelisable () const
Indicates whether or not the kernel is parallelisable.
virtual BorderSize border_size () const
The size of the border for that kernel.
const Window & window () const
The maximum window the kernel can be executed on.
Static Public Member Functions
static Status validate (const ITensorInfo *input1, const ITensorInfo *input2, const ITensorInfo *output, const PriorBoxLayerInfo &info)
Static function to check if given info will lead to a valid configuration of NEPriorBoxLayerKernel.
Detailed Description
Interface for the kernel to calculate prior boxes.
Definition at line 34 of file NEPriorBoxLayerKernel.h.
Constructor & Destructor Documentation
NEPriorBoxLayerKernel() [1/3]
NEPriorBoxLayerKernel ()
Default constructor.
Definition at line 108 of file NEPriorBoxLayerKernel.cpp.
References ARM_COMPUTE_ERROR, PriorBoxLayerInfo::aspect_ratios(), PriorBoxLayerInfo::clip(), ITensorInfo::dimension(), Window::DimY, Window::DimZ, ITensorInfo::element_size(), arm_compute::execute_window_loop(), Window::first_slice_window_2D(), Window::first_slice_window_3D(), arm_compute::get_data_layout_dimension_index(), arm_compute::HEIGHT, PriorBoxLayerInfo::img_size(), ITensor::info(), PriorBoxLayerInfo::max_sizes(), PriorBoxLayerInfo::min_sizes(), arm_compute::NCHW, arm_compute::NHWC, offset(), PriorBoxLayerInfo::offset(), arm_compute::test::validation::out, Iterator::ptr(), ITensor::ptr_to_element(), Window::set(), arm_compute::test::validation::reference::slice(), PriorBoxLayerInfo::steps(), ITensorInfo::strides_in_bytes(), PriorBoxLayerInfo::variances(), arm_compute::WIDTH, IKernel::window(), Coordinates2D::x, and Coordinates2D::y.
Referenced by NEPriorBoxLayerKernel::name().
     : _func(nullptr), _input1(nullptr), _input2(nullptr), _output(nullptr), _info()
 {
 }
NEPriorBoxLayerKernel() [2/3]
NEPriorBoxLayerKernel (const NEPriorBoxLayerKernel &) delete
Prevent instances of this class from being copied (As this class contains pointers)
NEPriorBoxLayerKernel() [3/3]
NEPriorBoxLayerKernel (NEPriorBoxLayerKernel &&) default
Allow instances of this class to be moved.
Member Function Documentation
configure()
void configure (const ITensor * input1, const ITensor * input2, ITensor * output, const PriorBoxLayerInfo & info)
Set the input and output tensors.
Parameters
[in] input1 First source tensor. Data types supported: F32. Data layouts supported: NCHW/NHWC.
[in] input2 Second source tensor. Data types and layouts supported: same as input1
[out] output Destination tensor. Output dimensions are [W * H * num_priors * 4, 2]. Data type supported: same as input
[in] info Prior box layer info.
Definition at line 306 of file NEPriorBoxLayerKernel.cpp.
References ARM_COMPUTE_ERROR, ARM_COMPUTE_ERROR_ON_NULLPTR, ARM_COMPUTE_ERROR_THROW_ON, ITensorInfo::data_layout(), ITensor::info(), arm_compute::test::validation::info(), arm_compute::NCHW, and arm_compute::NHWC.
Referenced by NEPriorBoxLayerKernel::name().
 {
     ARM_COMPUTE_ERROR_ON_NULLPTR(input1, input2, output);
     ARM_COMPUTE_ERROR_THROW_ON(validate_arguments(input1->info(), input2->info(), output->info(), info));
     _input1 = input1;
     _input2 = input2;
     _info   = info;
     _output = output;
     switch(input1->info()->data_layout())
     {
         case DataLayout::NCHW:
         {
             _func = &NEPriorBoxLayerKernel::calculate_prior_boxes<DataLayout::NCHW>;
             break;
         }
         case DataLayout::NHWC:
         {
             _func = &NEPriorBoxLayerKernel::calculate_prior_boxes<DataLayout::NHWC>;
             break;
         }
         default:
             ARM_COMPUTE_ERROR("Not implemented.");
     }
     // Configure kernel window
     auto win_config = validate_and_configure_window(input1->info(), input2->info(), output->info(), info);
     ARM_COMPUTE_ERROR_THROW_ON(win_config.first);
     INEKernel::configure(win_config.second);
 }
name()
const char* name () const inline override virtual
Name of the kernel.
Returns
Kernel name
Implements ICPPKernel.
Definition at line 37 of file NEPriorBoxLayerKernel.h.
References NEPriorBoxLayerKernel::configure(), arm_compute::test::validation::info(), NEPriorBoxLayerKernel::NEPriorBoxLayerKernel(), offset(), NEPriorBoxLayerKernel::operator=(), arm_compute::test::validation::out, NEPriorBoxLayerKernel::run(), NEPriorBoxLayerKernel::validate(), and IKernel::window().
     {
         return "NEPriorBoxLayerKernel";
     }
operator=() [1/2]
NEPriorBoxLayerKernel& operator= (const NEPriorBoxLayerKernel &) delete
Prevent instances of this class from being copied (As this class contains pointers)
Referenced by NEPriorBoxLayerKernel::name().
operator=() [2/2]
NEPriorBoxLayerKernel& operator= (NEPriorBoxLayerKernel &&) default
Allow instances of this class to be moved.
run()
void run (const Window & window, const ThreadInfo & info) override virtual
Execute the kernel on the passed window.
Warning
If is_parallelisable() returns false then the passed window must be equal to window()
Note
The window has to be a region within the window returned by the window() method
The width of the window has to be a multiple of num_elems_processed_per_iteration().
Parameters
[in] window Region on which to execute the kernel. (Must be a region of the window returned by window())
[in] info Info about executing thread and CPU.
Implements ICPPKernel.
Definition at line 348 of file NEPriorBoxLayerKernel.cpp.
References ARM_COMPUTE_ERROR_ON, ARM_COMPUTE_ERROR_ON_INVALID_SUBWINDOW, ARM_COMPUTE_ERROR_ON_UNCONFIGURED_KERNEL, ARM_COMPUTE_UNUSED, and IKernel::window().
Referenced by NEPriorBoxLayerKernel::name().
 {
     ARM_COMPUTE_UNUSED(info);
     ARM_COMPUTE_ERROR_ON_UNCONFIGURED_KERNEL(this);
     ARM_COMPUTE_ERROR_ON_INVALID_SUBWINDOW(INEKernel::window(), window);
     ARM_COMPUTE_ERROR_ON(_func == nullptr);
     // Run function
     (this->*_func)(window);
 }
validate()
Status validate (const ITensorInfo * input1, const ITensorInfo * input2, const ITensorInfo * output, const PriorBoxLayerInfo & info) static
Static function to check if given info will lead to a valid configuration of NEPriorBoxLayerKernel.
Parameters
[in] input1 First source tensor info. Data types supported: F32. Data layouts supported: NCHW/NHWC.
[in] input2 Second source tensor info. Data types and layouts supported: same as input1
[in] output Destination tensor info. Output dimensions are [W * H * num_priors * 4, 2]. Data type supported: same as input
[in] info Prior box layer info.
Returns
a status
Definition at line 339 of file NEPriorBoxLayerKernel.cpp.
References ARM_COMPUTE_RETURN_ERROR_ON_NULLPTR, ARM_COMPUTE_RETURN_ON_ERROR, ICloneable< T >::clone(), and arm_compute::test::validation::info().
Referenced by NEPriorBoxLayerKernel::name(), and NEPriorBoxLayer::validate().
 {
     ARM_COMPUTE_RETURN_ERROR_ON_NULLPTR(input1, input2, output);
     ARM_COMPUTE_RETURN_ON_ERROR(validate_arguments(input1, input2, output, info));
     ARM_COMPUTE_RETURN_ON_ERROR(validate_and_configure_window(input1->clone().get(), input2->clone().get(), output->clone().get(), info)
                                 .first);
     return Status{};
 }
The documentation for this class was generated from the following files:
arm_compute/core/NEON/kernels/NEPriorBoxLayerKernel.h
src/core/NEON/kernels/NEPriorBoxLayerKernel.cpp