Compute Library: src/core/CL/cl_kernels/reduction_operation.cl File Reference
reduction_operation.cl File Reference
#include "helpers.h"
Functions
DATA_TYPE square_sum (__global const DATA_TYPE *input)
Calculate square sum of a vector.
DATA_TYPE sum (__global const DATA_TYPE *input)
Calculate sum of a vector.
__kernel void reduction_operation_x (__global uchar *src_ptr, uint src_stride_x, uint src_step_x, uint src_stride_y, uint src_step_y, uint src_offset_first_element_in_bytes, __global uchar *partial_sum_ptr, uint partial_sum_stride_x, uint partial_sum_step_x, uint partial_sum_stride_y, uint partial_sum_step_y, uint partial_sum_offset_first_element_in_bytes, __local DATA_TYPE *local_sums)
This kernel performs parallel reduction given an operation on x-axis.
Function Documentation
reduction_operation_x()
__kernel void reduction_operation_x (__global uchar * src_ptr, uint src_stride_x, uint src_step_x, uint src_stride_y, uint src_step_y, uint src_offset_first_element_in_bytes, __global uchar * partial_sum_ptr, uint partial_sum_stride_x, uint partial_sum_step_x, uint partial_sum_stride_y, uint partial_sum_step_y, uint partial_sum_offset_first_element_in_bytes, __local DATA_TYPE * local_sums)
This kernel performs parallel reduction given an operation on x-axis.
Note
The data type must be passed at compile time using -DDATA_TYPE: e.g. -DDATA_TYPE=float
The operation we want to perform must be passed at compile time using -DOPERATION e.g. -DOPERATION=square_sum
The mean flag must be passed at compile time using -DMEAN if we want to compute the mean value
The width size must be passed at compile time using -DWIDTH e.g. -DWIDTH=128 if we want to compute the mean value
Parameters
[in] src_ptr Pointer to the source tensor. Supported data types: F16/F32
[in] src_stride_x Stride of the source tensor in X dimension (in bytes)
[in] src_step_x src_stride_x * number of elements along X processed per workitem(in bytes)
[in] src_stride_y Stride of the source tensor in Y dimension (in bytes)
[in] src_step_y src_stride_y * number of elements along Y processed per workitem(in bytes)
[in] src_offset_first_element_in_bytes The offset of the first element in the source tensor
[in] partial_sum_ptr The local buffer to hold sumed values. Supported data types: same as src_ptt
[in] partial_sum_stride_x Stride of the output tensor in X dimension (in bytes)
[in] partial_sum_step_x partial_sum_stride_x * number of elements along X processed per workitem(in bytes)
[in] partial_sum_stride_y Stride of the output tensor in Y dimension (in bytes)
[in] partial_sum_step_y partial_sum_stride_y * number of elements along Y processed per workitem(in bytes)
[in] partial_sum_offset_first_element_in_bytes The offset of the first element in the source tensor
[in] local_sums Local buffer for storing the partial sum
Definition at line 85 of file reduction_operation.cl.
References CONVERT, CONVERT_TO_IMAGE_STRUCT, CONVERT_TO_TENSOR3D_STRUCT, CONVERT_TO_TENSOR4D_STRUCT, CONVERT_TO_VECTOR_STRUCT, DATA_TYPE, IMAGE_DECLARATION, arm_compute::test::validation::in, offset(), Vector::ptr, Image::ptr, Tensor3D::ptr, Tensor4D::ptr, arm_compute::test::validation::src, TENSOR3D_DECLARATION, tensor3D_offset(), TENSOR4D_DECLARATION, tensor4D_offset(), VEC_DATA_TYPE, VECTOR_DECLARATION, and vector_offset().
 {
     Image src         = CONVERT_TO_IMAGE_STRUCT(src);
     Image partial_sum = CONVERT_TO_IMAGE_STRUCT(partial_sum);
     unsigned int lsize = get_local_size(0);
     unsigned int lid   = get_local_id(0);
     for(unsigned int y = 0; y < get_local_size(1); ++y)
     {
         local_sums[lid] = OPERATION((__global DATA_TYPE *)offset(&src, 0, y));
         barrier(CLK_LOCAL_MEM_FENCE);
         // Perform parallel reduction
         for(unsigned int i = lsize >> 1; i > 0; i >>= 1)
         {
             if(lid < i)
             {
                 local_sums[lid] += local_sums[lid + i];
             }
             barrier(CLK_LOCAL_MEM_FENCE);
         }
         if(lid == 0)
         {
 #if defined(MEAN) && defined(WIDTH)
             if(y == get_local_size(1) - 1)
             {
                 local_sums[0] /= WIDTH;
             }
 #endif /* defined(MEAN) && defined(WIDTH) */
             ((__global DATA_TYPE *)offset(&partial_sum, get_group_id(0), y))[0] = local_sums[0];
         }
     }
 }
square_sum()
DATA_TYPE square_sum (__global const DATA_TYPE * input) inline
Calculate square sum of a vector.
Parameters
[in] input Pointer to the first pixel.
Returns
square sum of vector.
Definition at line 32 of file reduction_operation.cl.
References DATA_TYPE, arm_compute::test::validation::in, and VEC_DATA_TYPE.
 {
     VEC_DATA_TYPE(DATA_TYPE, 16)
     in = vload16(0, input);
     in *= in;
     in.s01234567 += in.s89ABCDEF;
     in.s0123 += in.s4567;
     in.s01 += in.s23;
     return (in.s0 + in.s1);
 }
sum()
DATA_TYPE sum (__global const DATA_TYPE * input) inline
Calculate sum of a vector.
Parameters
[in] input Pointer to the first pixel.
Returns
sum of vector.
Definition at line 52 of file reduction_operation.cl.
References DATA_TYPE, arm_compute::test::validation::in, and VEC_DATA_TYPE.
Referenced by arm_compute::test::validation::calculate_width_concatenate_shape(), CLL2NormalizeLayerKernel::CLL2NormalizeLayerKernel(), CLL2NormalizeLayerKernel::configure(), GCLogits1DShiftExpSumKernel::configure(), GCLogits1DNormKernel::configure(), CLLogits1DMaxShiftExpSumKernel::configure(), CLLogits1DNormKernel::configure(), arm_compute::test::validation::reference::convolution(), arm_compute::test::validation::reference::l2_normalize(), l2_normalize_x(), l2_normalize_y(), l2_normalize_z(), arm_compute::test::validation::reference::magnitude(), NEL2NormalizeLayerKernel::name(), arm_compute::pixel_area_c1u8_clamp(), NELogits1DMaxKernel::run(), arm_compute::test::validation::reference::scale_core(), arm_compute::test::validation::reference::softmax_layer(), softmax_layer_max_shift_exp_sum_parallel(), and softmax_layer_max_shift_exp_sum_serial().
 {
     VEC_DATA_TYPE(DATA_TYPE, 16)
     in = vload16(0, input);
     in.s01234567 += in.s89ABCDEF;
     in.s0123 += in.s4567;
     in.s01 += in.s23;
     return (in.s0 + in.s1);
 }