Compute Library: src/core/NEON/kernels/arm_gemm/utils.hpp File Reference
utils.hpp File Reference
Macros
#define UNREACHABLE(why) __builtin_unreachable()
Functions
int iceildiv (const int a, const int b)
template<typename T >
T roundup (const T a, const T b)
template<typename T >
unsigned long get_vector_length ()
Macro Definition Documentation
UNREACHABLE
#define UNREACHABLE (why) __builtin_unreachable()
Definition at line 32 of file utils.hpp.
Function Documentation
get_vector_length()
unsigned long get_vector_length () inline
Definition at line 53 of file utils.hpp.
{
 #ifdef __ARM_FEATURE_SVE
     const unsigned long length = svcntb();
 #else
     const unsigned long length = 16;
 #endif
     return length / sizeof(T);
 }
iceildiv()
int iceildiv (const int a, const int b) inline
Definition at line 37 of file utils.hpp.
References arm_compute::test::validation::b.
Referenced by NEWinogradConvolutionLayer::configure(), GemvNativeTransposed< strategy, To, Tr >::execute(), GemvPretransposed< strategy, To, Tr >::execute(), GemmInterleaved< strategy, To, Tr >::GemmInterleaved(), GemmInterleaved< strategy, To, Tr >::get_B_pretransposed_array_size(), GemvNativeTransposed< strategy, To, Tr >::get_window_size(), GemvPretransposed< strategy, To, Tr >::get_window_size(), and GemmInterleaved< strategy, To, Tr >::pretranspose_B_array().
{
     return (a + b - 1) / b;
 }
roundup()
T roundup (const T a, const T b) inline
Definition at line 42 of file utils.hpp.
References arm_compute::test::validation::a, and arm_compute::test::validation::b.
Referenced by NEWinogradConvolutionLayer::configure(), NEWinogradLayerTransformOutputKernel< T, OutputTileRows, OutputTileCols, KernelRows, KernelCols >::configure(), NEWinogradLayerTransformWeightsKernel< T, OutputTileRows, OutputTileCols, KernelRows, KernelCols >::get_matrix_stride(), and NEWinogradLayerTransformWeightsKernel< T, OutputTileRows, OutputTileCols, KernelRows, KernelCols >::run().
{
     T rem = a % b;
     if (rem) {
         return a + b - rem;
     } else {
         return a;
     }
 }