Compute Library: ICLTensor Class Reference
ICLTensor Class Reference abstract
Interface for OpenCL tensor.
#include <ICLTensor.h>
Public Member Functions
ICLTensor ()
Default constructor.
ICLTensor (const ICLTensor &)=delete
Prevent instances of this class from being copy constructed.
ICLTensor & operator= (const ICLTensor &)=delete
Prevent instances of this class from being copied.
ICLTensor (ICLTensor &&)=default
Allow instances of this class to be move constructed.
ICLTensor & operator= (ICLTensor &&)=default
Allow instances of this class to be copied.
virtual ~ICLTensor ()=default
Default virtual destructor.
virtual CLQuantization quantization () const =0
Interface to be implemented by the child class to return the wrapped quantization info data.
virtual const cl::Buffer & cl_buffer () const =0
Interface to be implemented by the child class to return a reference to the OpenCL buffer containing the image's data.
void map (cl::CommandQueue &q, bool blocking=true)
Enqueue a map operation of the allocated buffer on the given queue.
void unmap (cl::CommandQueue &q)
Enqueue an unmap operation of the allocated and mapped buffer on the given queue.
void clear (cl::CommandQueue &q)
Clear the contents of the tensor synchronously.
uint8_t * buffer () const override
Interface to be implemented by the child class to return a pointer to CPU memory.
Public Member Functions inherited from ITensor
virtual ITensorInfo * info () const =0
Interface to be implemented by the child class to return the tensor's metadata.
virtual ITensorInfo * info ()=0
Interface to be implemented by the child class to return the tensor's metadata.
virtual ~ITensor ()=default
Default virtual destructor.
uint8_t * ptr_to_element (const Coordinates &id) const
Return a pointer to the element at the passed coordinates.
void copy_from (const ITensor &src)
Copy the content of another tensor.
void print (std::ostream &s, IOFormatInfo io_fmt=IOFormatInfo()) const
Print a tensor to a given stream using user defined formatting information.
bool is_used () const
Flags if the tensor is used or not.
void mark_as_unused () const
Marks a tensor as unused.
Detailed Description
Interface for OpenCL tensor.
Definition at line 42 of file ICLTensor.h.
Constructor & Destructor Documentation
ICLTensor() [1/3]
ICLTensor ()
Default constructor.
Definition at line 30 of file ICLTensor.cpp.
     : _mapping(nullptr)
 {
 }
ICLTensor() [2/3]
ICLTensor (const ICLTensor &) delete
Prevent instances of this class from being copy constructed.
ICLTensor() [3/3]
ICLTensor (ICLTensor &&) default
Allow instances of this class to be move constructed.
~ICLTensor()
virtual ~ICLTensor () virtual default
Default virtual destructor.
Member Function Documentation
buffer()
uint8_t * buffer () const override virtual
Interface to be implemented by the child class to return a pointer to CPU memory.
Returns
A CPU pointer to the beginning of the image's allocation.
Implements ITensor.
Definition at line 53 of file ICLTensor.cpp.
 {
     return _mapping;
 }
Referenced by CLFFT1D::configure(), CLFFTConvolutionLayer::configure(), CLDirectDeconvolutionLayer::configure(), and CLAccessor::data().
cl_buffer()
virtual const cl::Buffer& cl_buffer () const pure virtual
Interface to be implemented by the child class to return a reference to the OpenCL buffer containing the image's data.
Returns
A reference to an OpenCL buffer containing the image's data.
Implemented in CLSubTensor, and CLTensor.
Referenced by ICLKernel::add_tensor_argument(), and CLSubTensor::cl_buffer().
clear()
void clear (cl::CommandQueue & q)
Clear the contents of the tensor synchronously.
Parameters
[in,out] q The CL command queue to use for the clear operation.
Definition at line 46 of file ICLTensor.cpp.
 {
     this->map(q);
     std::memset(static_cast<void *>(_mapping), 0, this->info()->total_size());
     this->unmap(q);
 }
References ITensor::info(), ICLTensor::map(), and ICLTensor::unmap().
Referenced by CLCannyEdge::run().
map()
void map (cl::CommandQueue & q, bool blocking = true)
Enqueue a map operation of the allocated buffer on the given queue.
Parameters
[in,out] q The CL command queue to use for the mapping operation.
[in] blocking If true, then the mapping will be ready to use by the time this method returns, else it is the caller's responsibility to flush the queue and wait for the mapping operation to have completed before using the returned mapping pointer.
Returns
The mapping address.
Definition at line 35 of file ICLTensor.cpp.
 {
     _mapping = do_map(q, blocking);
 }
Referenced by ICLTensor::clear(), CLTensor::map(), CLSubTensor::map(), CLMinMaxLayerKernel::reset(), and CLCropResize::run().
operator=() [1/2]
ICLTensor& operator= (const ICLTensor &) delete
Prevent instances of this class from being copied.
operator=() [2/2]
ICLTensor& operator= (ICLTensor &&) default
Allow instances of this class to be copied.
quantization()
virtual CLQuantization quantization () const pure virtual
Interface to be implemented by the child class to return the wrapped quantization info data.
Returns
A wrapped quantization info object.
Implemented in CLSubTensor, and CLTensor.
Referenced by CLSubTensor::quantization().
unmap()
void unmap (cl::CommandQueue & q)
Enqueue an unmap operation of the allocated and mapped buffer on the given queue.
Note
This method simply enqueues the unmap operation, it is the caller's responsibility to flush the queue and make sure the unmap is finished before the memory is accessed by the device.
Parameters
[in,out] q The CL command queue to use for the mapping operation.
Definition at line 40 of file ICLTensor.cpp.
 {
     do_unmap(q);
     _mapping = nullptr;
 }
Referenced by ICLTensor::clear(), CLMinMaxLayerKernel::reset(), CLCropResize::run(), CLTensor::unmap(), and CLSubTensor::unmap().
The documentation for this class was generated from the following files:
arm_compute/core/CL/ICLTensor.h
src/core/CL/ICLTensor.cpp