Compute Library: GCBatchNormalizationLayerKernel Class Reference
GCBatchNormalizationLayerKernel Class Reference
Interface for the BatchNormalization layer kernel.
#include <GCBatchNormalizationLayerKernel.h>
Public Member Functions
GCBatchNormalizationLayerKernel ()
Constructor.
GCBatchNormalizationLayerKernel (const GCBatchNormalizationLayerKernel &)=delete
Prevent instances of this class from being copied (As this class contains pointers)
GCBatchNormalizationLayerKernel & operator= (const GCBatchNormalizationLayerKernel &)=delete
Prevent instances of this class from being copied (As this class contains pointers)
GCBatchNormalizationLayerKernel (GCBatchNormalizationLayerKernel &&)=default
Default Move Constructor.
GCBatchNormalizationLayerKernel & operator= (GCBatchNormalizationLayerKernel &&)=default
Default move assignment operator.
~GCBatchNormalizationLayerKernel ()=default
Default destructor.
void configure (const IGCTensor *input, IGCTensor *output, const IGCTensor *mean, const IGCTensor *var, const IGCTensor *beta=nullptr, const IGCTensor *gamma=nullptr, float epsilon=0.001f, ActivationLayerInfo act_info=ActivationLayerInfo())
Set the input and output tensors.
void run (const Window &window) override
Enqueue the OpenGL ES shader to process the given window.
Public Member Functions inherited from IGCKernel
IGCKernel ()
Constructor.
GCKernel & kernel ()
Returns a reference to the GLES kernel of this object.
void add_1D_tensor_argument (unsigned int &idx, const IGCTensor *tensor, const unsigned int binding_point, const Window &window)
Add the passed 1D tensor's parameters to the object's kernel's arguments starting from the index idx.
void add_2D_tensor_argument (unsigned int &idx, const IGCTensor *tensor, const unsigned int binding_point, const Window &window)
Add the passed 2D tensor's parameters to the object's kernel's arguments starting from the index idx.
void add_3D_tensor_argument (unsigned int &idx, const IGCTensor *tensor, const unsigned int binding_point, const Window &window)
Add the passed 3D tensor's parameters to the object's kernel's arguments starting from the index idx.
unsigned int num_arguments_per_1D_tensor () const
Returns the number of arguments enqueued per 1D tensor object.
unsigned int num_arguments_per_2D_tensor () const
Returns the number of arguments enqueued per 2D tensor object.
unsigned int num_arguments_per_3D_tensor () const
Returns the number of arguments enqueued per 3D tensor object.
void set_lws_hint (gles::NDRange &lws_hint)
Set the Local-Workgroup-Size hint.
void set_target (GPUTarget target)
Set the targeted GPU architecture.
GPUTarget get_target () const
Get the targeted GPU architecture.
Public Member Functions inherited from IKernel
IKernel ()
Constructor.
virtual ~IKernel ()=default
Destructor.
virtual bool is_parallelisable () const
Indicates whether or not the kernel is parallelisable.
virtual BorderSize border_size () const
The size of the border for that kernel.
const Window & window () const
The maximum window the kernel can be executed on.
Static Public Member Functions
static Status validate (const ITensorInfo *input, const ITensorInfo *output, const ITensorInfo *mean, const ITensorInfo *var, const ITensorInfo *beta=nullptr, const ITensorInfo *gamma=nullptr, float epsilon=0.001f, ActivationLayerInfo act_info=ActivationLayerInfo())
Static function to check if given info will lead to a valid configuration of GCBatchNormalizationLayerKernel.
Detailed Description
Interface for the BatchNormalization layer kernel.
Definition at line 35 of file GCBatchNormalizationLayerKernel.h.
Constructor & Destructor Documentation
GCBatchNormalizationLayerKernel() [1/3]
GCBatchNormalizationLayerKernel ()
Constructor.
Definition at line 134 of file GCBatchNormalizationLayerKernel.cpp.
     : _input(nullptr), _output(nullptr), _mean(nullptr), _var(nullptr), _beta(nullptr), _gamma(nullptr), _epsilon(0.0f)
 {
 }
GCBatchNormalizationLayerKernel() [2/3]
GCBatchNormalizationLayerKernel (const GCBatchNormalizationLayerKernel &) delete
Prevent instances of this class from being copied (As this class contains pointers)
GCBatchNormalizationLayerKernel() [3/3]
GCBatchNormalizationLayerKernel (GCBatchNormalizationLayerKernel &&) default
Default Move Constructor.
~GCBatchNormalizationLayerKernel()
~GCBatchNormalizationLayerKernel () default
Default destructor.
Member Function Documentation
configure()
void configure (const IGCTensor * input, IGCTensor * output, const IGCTensor * mean, const IGCTensor * var, const IGCTensor * beta = nullptr, const IGCTensor * gamma = nullptr, float epsilon = 0.001f, ActivationLayerInfo act_info = ActivationLayerInfo())
Set the input and output tensors.
Parameters
[in] input Source tensor. 3 lower dimensions represent a single input with dimensions [width, height, FM]. The rest are optional and used for representing batches. Data types supported: F16/F32.
[out] output Destination tensor. Output will have the same number of dimensions as input. Data type supported: same as input
[in] mean Mean values tensor. 1 dimension with size equal to the feature maps [FM]. Data types supported: Same as input
[in] var Variance values tensor. 1 dimension with size equal to the feature maps [FM]. Data types supported: Same as input
[in] beta (Optional) Beta values tensor info. 1 dimension with size equal to the feature maps [FM]. If not provided, default value for beta is 0. Data types supported: Same as input
[in] gamma (Optional) Gamma values tensor info. 1 dimension with size equal to the feature maps [FM]. If not provided, default value for gamma is 1. Data types supported: Same as input
[in] epsilon (optional) Small value to avoid division with zero.
[in] act_info (Optional) Activation layer information in case of a fused activation. Only RELU, BOUNDED_RELU and LU_BOUNDED_RELU supported.
Definition at line 139 of file GCBatchNormalizationLayerKernel.cpp.
 {
     ARM_COMPUTE_ERROR_ON_NULLPTR(input, output, mean, var);
     ARM_COMPUTE_ERROR_THROW_ON(validate_arguments(input->info(), output->info(), mean->info(), var->info(),
                                                   (beta != nullptr) ? beta->info() : nullptr, (gamma != nullptr) ? gamma->info() : nullptr,
                                                   epsilon, act_info));
     _input   = input;
     _output  = output;
     _mean    = mean;
     _var     = var;
     _beta    = beta;
     _gamma   = gamma;
     _epsilon = epsilon;
     // Set build options
     std::set<std::string> build_opts;
     std::string           dt_name = (input->info()->data_type() == DataType::F32) ? "DATA_TYPE_FP32" : "DATA_TYPE_FP16";
     build_opts.emplace(("#define " + dt_name));
     build_opts.emplace(("#define ESPILON " + float_to_string_with_full_precision(_epsilon)));
     build_opts.emplace(("#define LOCAL_SIZE_X " + support::cpp11::to_string(1)));
     build_opts.emplace(("#define LOCAL_SIZE_Y " + support::cpp11::to_string(1)));
     build_opts.emplace(("#define LOCAL_SIZE_Z " + support::cpp11::to_string(1)));
     if(beta == nullptr)
     {
         build_opts.emplace("#define USE_DEFAULT_BETA");
     }
     if(gamma == nullptr)
     {
         build_opts.emplace("#define USE_DEFAULT_GAMMA");
     }
     if(act_info.enabled())
     {
         build_opts.emplace("#define " + string_from_activation_func(act_info.activation()));
         build_opts.emplace("#define A_VAL " + float_to_string_with_full_precision(act_info.a()));
         build_opts.emplace("#define B_VAL " + float_to_string_with_full_precision(act_info.b()));
     }
     // Create kernel
     _kernel = static_cast<GCKernel>(GCKernelLibrary::get().create_kernel("batchnormalization_layer", build_opts));
     // Configure kernel window
     auto win_config = validate_and_configure_window(input->info(), output->info(), mean->info(), var->info(),
                                                     (beta != nullptr) ? beta->info() : nullptr, (gamma != nullptr) ? gamma->info() : nullptr);
     ARM_COMPUTE_ERROR_THROW_ON(win_config.first);
     IGCKernel::configure(win_config.second);
 }
References arm_compute::test::validation::act_info, ARM_COMPUTE_ERROR_ON_NULLPTR, ARM_COMPUTE_ERROR_THROW_ON, arm_compute::create_kernel(), ITensorInfo::data_type(), epsilon, arm_compute::F32, arm_compute::float_to_string_with_full_precision(), GCKernelLibrary::get(), ITensor::info(), arm_compute::string_from_activation_func(), arm_compute::support::cpp11::to_string(), and arm_compute::validate_and_configure_window().
Referenced by GCBatchNormalizationLayer::configure().
operator=() [1/2]
GCBatchNormalizationLayerKernel& operator= (const GCBatchNormalizationLayerKernel &) delete
Prevent instances of this class from being copied (As this class contains pointers)
operator=() [2/2]
GCBatchNormalizationLayerKernel& operator= (GCBatchNormalizationLayerKernel &&) default
Default move assignment operator.
run()
void run (const Window & window) override virtual
Enqueue the OpenGL ES shader to process the given window.
Parameters
[in] window Region on which to execute the kernel. (Must be a valid region of the window returned by window()).
Implements IGCKernel.
Definition at line 205 of file GCBatchNormalizationLayerKernel.cpp.
 {
     ARM_COMPUTE_ERROR_ON_UNCONFIGURED_KERNEL(this);
     ARM_COMPUTE_ERROR_ON_INVALID_SUBWINDOW(IKernel::window(), window);
     _kernel.use();
     _output->set_needs_shifting(true);
     Window slice    = window.first_slice_window_3D();
     Window slice_in = window.first_slice_window_3D();
     Window vector_slice = window.first_slice_window_1D();
     vector_slice.set(Window::DimX, Window::Dimension(0, 0, 0));
     unsigned int idx           = 2 * num_arguments_per_3D_tensor();
     unsigned int binding_point = 3;
     add_1D_tensor_argument(idx, _mean, binding_point, vector_slice);
     add_1D_tensor_argument(idx, _var, ++binding_point, vector_slice);
     if(_beta != nullptr)
     {
         add_1D_tensor_argument(idx, _beta, ++binding_point, vector_slice);
     }
     if(_gamma != nullptr)
     {
         add_1D_tensor_argument(idx, _gamma, ++binding_point, vector_slice);
     }
     slice.shift(Window::DimX, -(_output->info()->padding()).left);
     do
     {
         idx = 0;
         add_3D_tensor_argument(idx, _input, 1, slice_in);
         add_3D_tensor_argument(idx, _output, 2, slice);
         _kernel.update_shader_params();
         enqueue(*this, slice);
     }
     while(window.slide_window_slice_3D(slice) && window.slide_window_slice_3D(slice_in));
 }
References IGCKernel::add_1D_tensor_argument(), IGCKernel::add_3D_tensor_argument(), ARM_COMPUTE_ERROR_ON_INVALID_SUBWINDOW, ARM_COMPUTE_ERROR_ON_UNCONFIGURED_KERNEL, Window::DimX, arm_compute::enqueue(), Window::first_slice_window_1D(), Window::first_slice_window_3D(), ITensor::info(), IGCKernel::num_arguments_per_3D_tensor(), ITensorInfo::padding(), Window::set(), IGCTensor::set_needs_shifting(), arm_compute::test::validation::reference::slice(), Window::slide_window_slice_3D(), and IKernel::window().
validate()
Status validate (const ITensorInfo * input, const ITensorInfo * output, const ITensorInfo * mean, const ITensorInfo * var, const ITensorInfo * beta = nullptr, const ITensorInfo * gamma = nullptr, float epsilon = 0.001f, ActivationLayerInfo act_info = ActivationLayerInfo()) static
Static function to check if given info will lead to a valid configuration of GCBatchNormalizationLayerKernel.
Parameters
[in] input Source tensor info. In case of output tensor info = nullptr, this tensor will store the result. 3 lower dimensions represent a single input with dimensions [width, height, FM]. The rest are optional and used for representing batches. Data types supported: F16/F32.
[in] output Destination tensor info. Output will have the same number of dimensions as input. Data type supported: same as input
[in] mean Mean values tensor info. 1 dimension with size equal to the feature maps [FM]. Data types supported: Same as input
[in] var Variance values tensor info. 1 dimension with size equal to the feature maps [FM]. Data types supported: Same as input
[in] beta (Optional) Beta values tensor info. 1 dimension with size equal to the feature maps [FM]. If not provided, default value for beta is 0. Data types supported: Same as input
[in] gamma (Optional) Gamma values tensor info. 1 dimension with size equal to the feature maps [FM]. If not provided, default value for gamma is 1. Data types supported: Same as input
[in] epsilon (Optional) Small value to avoid division with zero. Default value is 0.001f.
[in] act_info (Optional) Activation layer information in case of a fused activation. Only RELU, BOUNDED_RELU and LU_BOUNDED_RELU supported.
Returns
a status
Definition at line 191 of file GCBatchNormalizationLayerKernel.cpp.
 {
     ARM_COMPUTE_RETURN_ON_ERROR(validate_arguments(input, output, mean, var, beta, gamma, epsilon, act_info));
     ARM_COMPUTE_RETURN_ON_ERROR(validate_and_configure_window(input->clone().get(), output->clone().get(),
                                                               mean->clone().get(), var->clone().get(),
                                                               beta->clone().get(), gamma->clone().get())
                                 .first);
     return Status{};
 }
References arm_compute::test::validation::act_info, ARM_COMPUTE_RETURN_ON_ERROR, ICloneable< T >::clone(), epsilon, and arm_compute::validate_and_configure_window().
The documentation for this class was generated from the following files:
arm_compute/core/GLES_COMPUTE/kernels/GCBatchNormalizationLayerKernel.h
src/core/GLES_COMPUTE/kernels/GCBatchNormalizationLayerKernel.cpp