Compute Library: NEIntegralImageKernel Class Reference
NEIntegralImageKernel Class Reference
Kernel to perform an image integral on an image.
#include <NEIntegralImageKernel.h>
Public Member Functions
const char * name () const override
Name of the kernel.
void configure (const ITensor *input, ITensor *output)
Set the source, destination and border mode of the kernel.
void run (const Window &window, const ThreadInfo &info) override
Execute the kernel on the passed window.
BorderSize border_size () const override
The size of the border for that kernel.
bool is_parallelisable () const override
Indicates whether or not the kernel is parallelisable.
Public Member Functions inherited from ICPPSimpleKernel
ICPPSimpleKernel ()
Constructor.
ICPPSimpleKernel (const ICPPSimpleKernel &)=delete
Prevent instances of this class from being copied (As this class contains pointers)
ICPPSimpleKernel & operator= (const ICPPSimpleKernel &)=delete
Prevent instances of this class from being copied (As this class contains pointers)
ICPPSimpleKernel (ICPPSimpleKernel &&)=default
Allow instances of this class to be moved.
ICPPSimpleKernel & operator= (ICPPSimpleKernel &&)=default
Allow instances of this class to be moved.
~ICPPSimpleKernel ()=default
Default destructor.
Public Member Functions inherited from ICPPKernel
virtual ~ICPPKernel ()=default
Default destructor.
Public Member Functions inherited from IKernel
IKernel ()
Constructor.
virtual ~IKernel ()=default
Destructor.
const Window & window () const
The maximum window the kernel can be executed on.
Detailed Description
Kernel to perform an image integral on an image.
Definition at line 34 of file NEIntegralImageKernel.h.
Member Function Documentation
border_size()
BorderSize border_size () const override virtual
The size of the border for that kernel.
Returns
The width in number of elements of the border.
Reimplemented from IKernel.
Definition at line 64 of file NEIntegralImageKernel.cpp.
 {
     return BorderSize{ 1, 0, 0, 1 };
 }
configure()
void configure (const ITensor * input, ITensor * output)
Set the source, destination and border mode of the kernel.
Parameters
[in] input Source tensor. Data type supported: U8
[out] output Destination tensor. Data type supported: U32
Definition at line 38 of file NEIntegralImageKernel.cpp.
 {
     ARM_COMPUTE_ERROR_ON_DATA_TYPE_CHANNEL_NOT_IN(input, 1, DataType::U8);
     ARM_COMPUTE_ERROR_ON_DATA_TYPE_CHANNEL_NOT_IN(output, 1, DataType::U32);
     _input  = input;
     _output = output;
     constexpr unsigned int num_elems_processed_per_iteration = 16;
     // Configure kernel window
     Window win = calculate_max_window(*input->info(), Steps(num_elems_processed_per_iteration));
     // The kernel is effectively reading 17 values from -1 as it loads 16
     // starting at -1 and also 16 starting at 0
     AccessWindowRectangle  output_read_access(output->info(), -1, -1, num_elems_processed_per_iteration + 1, 1);
     AccessWindowHorizontal output_write_access(output->info(), 0, num_elems_processed_per_iteration);
     update_window_and_padding(win,
                               AccessWindowHorizontal(input->info(), 0, num_elems_processed_per_iteration),
                               output_read_access, output_write_access);
     output_write_access.set_valid_region(win, input->info()->valid_region());
     IKernel::configure(win);
 }
References ARM_COMPUTE_ERROR_ON_DATA_TYPE_CHANNEL_NOT_IN, arm_compute::calculate_max_window(), ITensor::info(), arm_compute::U32, arm_compute::U8, arm_compute::update_window_and_padding(), and ITensorInfo::valid_region().
is_parallelisable()
bool is_parallelisable () const override virtual
Indicates whether or not the kernel is parallelisable.
If the kernel is parallelisable then the window returned by window() can be split into sub-windows which can then be run in parallel.
If the kernel is not parallelisable then only the window returned by window() can be passed to run()
Returns
True if the kernel is parallelisable
Reimplemented from IKernel.
Definition at line 69 of file NEIntegralImageKernel.cpp.
 {
     return false;
 }
name()
const char* name () const inline override virtual
Name of the kernel.
Returns
Kernel name
Implements ICPPKernel.
Definition at line 37 of file NEIntegralImageKernel.h.
     {
         return "NEIntegralImageKernel";
     }
run()
void run (const Window & window, const ThreadInfo & info) override virtual
Execute the kernel on the passed window.
Warning
If is_parallelisable() returns false then the passed window must be equal to window()
Note
The window has to be a region within the window returned by the window() method
The width of the window has to be a multiple of num_elems_processed_per_iteration().
Parameters
[in] window Region on which to execute the kernel. (Must be a region of the window returned by window())
[in] info Info about executing thread and CPU.
Implements ICPPKernel.
Definition at line 74 of file NEIntegralImageKernel.cpp.
 {
     ARM_COMPUTE_UNUSED(info);
     ARM_COMPUTE_ERROR_ON_UNCONFIGURED_KERNEL(this);
     ARM_COMPUTE_ERROR_ON_INVALID_SUBWINDOW(INESimpleKernel::window(), window);
     Iterator input(_input, window);
     Iterator output(_output, window);
     const auto output_top_left = reinterpret_cast<const uint32_t *>(_output->ptr_to_element(Coordinates(-1, -1)));
     const auto output_top_mid  = reinterpret_cast<const uint32_t *>(_output->ptr_to_element(Coordinates(0, -1)));
     execute_window_loop(window, [&](const Coordinates &)
     {
         const uint8x16_t input_pixels = vld1q_u8(input.ptr());
         const uint16x8x2_t tmp =
         {
             {
                 vmovl_u8(vget_low_u8(input_pixels)),
                 vmovl_u8(vget_high_u8(input_pixels))
             }
         };
         uint32x4x4_t pixels =
         {
             {
                 vmovl_u16(vget_low_u16(tmp.val[0])),
                 vmovl_u16(vget_high_u16(tmp.val[0])),
                 vmovl_u16(vget_low_u16(tmp.val[1])),
                 vmovl_u16(vget_high_u16(tmp.val[1]))
             }
         };
         // Divide by four as pointer is now uint32 instead of uint8!
         const size_t off = output.offset() / 4;
         // Add top mid pixel values
         const uint32_t *const top_mid_ptr = output_top_mid + off;
         pixels.val[0] = vaddq_u32(vld1q_u32(top_mid_ptr), pixels.val[0]);
         pixels.val[1] = vaddq_u32(vld1q_u32(top_mid_ptr + 4), pixels.val[1]);
         pixels.val[2] = vaddq_u32(vld1q_u32(top_mid_ptr + 8), pixels.val[2]);
         pixels.val[3] = vaddq_u32(vld1q_u32(top_mid_ptr + 12), pixels.val[3]);
         // Subtract top left diagonal values
         const auto            outptr       = reinterpret_cast<uint32_t *>(output.ptr());
         const uint32_t *const top_left_ptr = output_top_left + off;
         pixels.val[0] = vsubq_u32(pixels.val[0], vld1q_u32(top_left_ptr));
         vst1q_u32(outptr, pixels.val[0]);
         pixels.val[1] = vsubq_u32(pixels.val[1], vld1q_u32(top_left_ptr + 4));
         vst1q_u32(outptr + 4, pixels.val[1]);
         pixels.val[2] = vsubq_u32(pixels.val[2], vld1q_u32(top_left_ptr + 8));
         vst1q_u32(outptr + 8, pixels.val[2]);
         pixels.val[3] = vsubq_u32(pixels.val[3], vld1q_u32(top_left_ptr + 12));
         vst1q_u32(outptr + 12, pixels.val[3]);
         // Perform prefix summation
         for(auto i = 0; i < 16; ++i)
         {
             outptr[i] += outptr[i - 1];
         }
     },
     input, output);
 }
References ARM_COMPUTE_ERROR_ON_INVALID_SUBWINDOW, ARM_COMPUTE_ERROR_ON_UNCONFIGURED_KERNEL, ARM_COMPUTE_UNUSED, arm_compute::execute_window_loop(), arm_compute::test::validation::info, Iterator::offset(), Iterator::ptr(), and IKernel::window().
The documentation for this class was generated from the following files:
arm_compute/core/NEON/kernels/NEIntegralImageKernel.h
src/core/NEON/kernels/NEIntegralImageKernel.cpp