Compute Library: CLGaussianPyramidOrb Class Reference
CLGaussianPyramidOrb Class Reference
Basic function to execute gaussian pyramid with ORB scale factor.
#include <CLGaussianPyramid.h>
Public Member Functions
CLGaussianPyramidOrb ()
Constructor.
void configure (ICLTensor *input, CLPyramid *pyramid, BorderMode border_mode, uint8_t constant_border_value) override
Initialise the function's source, destinations and border mode.
void run () override
Run the kernels contained in the function.
Public Member Functions inherited from CLGaussianPyramid
CLGaussianPyramid ()
Constructor.
CLGaussianPyramid (const CLGaussianPyramid &)=delete
Prevent instances of this class from being copied (As this class contains pointers)
CLGaussianPyramid & operator= (const CLGaussianPyramid &)=delete
Prevent instances of this class from being copied (As this class contains pointers)
CLGaussianPyramid (CLGaussianPyramid &&)=default
Allow instances of this class to be moved.
CLGaussianPyramid & operator= (CLGaussianPyramid &&)=default
Allow instances of this class to be moved.
virtual ~CLGaussianPyramid ()=default
Default destructor.
Public Member Functions inherited from IFunction
virtual ~IFunction ()=default
Destructor.
virtual void prepare ()
Prepare the function for executing.
Detailed Description
Basic function to execute gaussian pyramid with ORB scale factor.
This function calls the following OpenCL kernels and functions:
CLFillBorderKernel (executed if border_mode == CONSTANT or border_mode == REPLICATE)
CLGaussian5x5
CLScaleKernel
Definition at line 105 of file CLGaussianPyramid.h.
Constructor & Destructor Documentation
CLGaussianPyramidOrb()
CLGaussianPyramidOrb ()
Constructor.
Definition at line 133 of file CLGaussianPyramid.cpp.
     : _gauss5x5(),
       _scale_nearest()
 {
 }
Member Function Documentation
configure()
void configure (ICLTensor * input, CLPyramid * pyramid, BorderMode border_mode, uint8_t constant_border_value) override virtual
Initialise the function's source, destinations and border mode.
Parameters
[in,out] input Source tensor. Data types supported: U8. (Written to only for border_mode != UNDEFINED)
[out] pyramid Destination pyramid tensors, Data types supported at each level: U8.
[in] border_mode Border mode to use.
[in] constant_border_value (Optional) Constant value to use for borders if border_mode is set to CONSTANT.
Implements CLGaussianPyramid.
Definition at line 139 of file CLGaussianPyramid.cpp.
 {
     ARM_COMPUTE_ERROR_ON_DATA_TYPE_CHANNEL_NOT_IN(input, 1, DataType::U8);
     ARM_COMPUTE_ERROR_ON(nullptr == pyramid);
     ARM_COMPUTE_ERROR_ON(input->info()->num_dimensions() != pyramid->get_pyramid_level(0)->info()->num_dimensions());
     ARM_COMPUTE_ERROR_ON(input->info()->dimension(0) != pyramid->info()->width());
     ARM_COMPUTE_ERROR_ON(input->info()->dimension(1) != pyramid->info()->height());
     ARM_COMPUTE_ERROR_ON(SCALE_PYRAMID_ORB != pyramid->info()->scale());
     /* Get number of pyramid levels */
     const size_t num_levels = pyramid->info()->num_levels();
     _input   = input;
     _pyramid = pyramid;
     if(num_levels > 1)
     {
         _gauss5x5.resize(num_levels - 1);
         _scale_nearest.resize(num_levels - 1);
         PyramidInfo pyramid_info(num_levels - 1, SCALE_PYRAMID_ORB, pyramid->info()->tensor_shape(), Format::U8);
         _tmp.init(pyramid_info);
         for(size_t i = 0; i < num_levels - 1; ++i)
         {
             /* Configure gaussian 5x5 */
             _gauss5x5[i].configure(_pyramid->get_pyramid_level(i), _tmp.get_pyramid_level(i), border_mode, constant_border_value);
             /* Configure scale image kernel */
             _scale_nearest[i].configure(_tmp.get_pyramid_level(i), _pyramid->get_pyramid_level(i + 1), InterpolationPolicy::NEAREST_NEIGHBOR, border_mode, SamplingPolicy::CENTER);
         }
         _tmp.allocate();
     }
 }
References ARM_COMPUTE_ERROR_ON, ARM_COMPUTE_ERROR_ON_DATA_TYPE_CHANNEL_NOT_IN, arm_compute::test::validation::border_mode, arm_compute::CENTER, ITensorInfo::dimension(), CLPyramid::get_pyramid_level(), PyramidInfo::height(), ITensor::info(), CLPyramid::info(), CLTensor::info(), PyramidInfo::init(), arm_compute::NEAREST_NEIGHBOR, ITensorInfo::num_dimensions(), TensorInfo::num_dimensions(), PyramidInfo::num_levels(), PyramidInfo::scale(), arm_compute::SCALE_PYRAMID_ORB, PyramidInfo::tensor_shape(), arm_compute::U8, and PyramidInfo::width().
run()
void run () override virtual
Run the kernels contained in the function.
For NEON kernels:
Multi-threading is used for the kernels which are parallelisable.
By default std::thread::hardware_concurrency() threads are used.
Note
CPPScheduler::set_num_threads() can be used to manually set the number of threads
For OpenCL kernels:
All the kernels are enqueued on the queue associated with CLScheduler.
The queue is then flushed.
Note
The function will not block until the kernels are executed. It is the user's responsibility to wait.
Will call prepare() on first run if hasn't been done
Implements IFunction.
Definition at line 176 of file CLGaussianPyramid.cpp.
 {
     ARM_COMPUTE_ERROR_ON_MSG(_pyramid == nullptr, "Unconfigured function");
     /* Get number of pyramid levels */
     const size_t num_levels = _pyramid->info()->num_levels();
     /* The first level of the pyramid has the input image */
     _pyramid->get_pyramid_level(0)->map(CLScheduler::get().queue(), true /* blocking */);
     _input->map(CLScheduler::get().queue(), true /* blocking */);
     _pyramid->get_pyramid_level(0)->copy_from(*_input);
     _input->unmap(CLScheduler::get().queue());
     _pyramid->get_pyramid_level(0)->unmap(CLScheduler::get().queue());
     for(unsigned int i = 0; i < num_levels - 1; ++i)
     {
         _gauss5x5[i].run();
         CLScheduler::get().enqueue(_scale_nearest[i]);
     }
 }
References ARM_COMPUTE_ERROR_ON_MSG, CLScheduler::enqueue(), and CLScheduler::get().
The documentation for this class was generated from the following files:
arm_compute/runtime/CL/functions/CLGaussianPyramid.h
src/runtime/CL/functions/CLGaussianPyramid.cpp