Compute Library: GCDropoutLayerKernel Class Reference
GCDropoutLayerKernel Class Reference
Interface for the dropout layer kernel.
#include <GCDropoutLayerKernel.h>
Public Member Functions
GCDropoutLayerKernel ()
Default constructor.
GCDropoutLayerKernel (const GCDropoutLayerKernel &)=delete
Prevent instances of this class from being copied (As this class contains pointers)
GCDropoutLayerKernel & operator= (const GCDropoutLayerKernel &)=delete
Prevent instances of this class from being copied (As this class contains pointers)
GCDropoutLayerKernel (GCDropoutLayerKernel &&)=default
Allow instances of this class to be moved.
GCDropoutLayerKernel & operator= (GCDropoutLayerKernel &&)=default
Allow instances of this class to be moved.
void configure (const IGCTensor *input, IGCTensor *mask, IGCTensor *output, float ratio, bool forward)
Set the input and output of the kernel.
void run (const Window &window) override
Enqueue the OpenGL ES shader to process the given window.
Public Member Functions inherited from IGCKernel
IGCKernel ()
Constructor.
GCKernel & kernel ()
Returns a reference to the GLES kernel of this object.
void add_1D_tensor_argument (unsigned int &idx, const IGCTensor *tensor, const unsigned int binding_point, const Window &window)
Add the passed 1D tensor's parameters to the object's kernel's arguments starting from the index idx.
void add_2D_tensor_argument (unsigned int &idx, const IGCTensor *tensor, const unsigned int binding_point, const Window &window)
Add the passed 2D tensor's parameters to the object's kernel's arguments starting from the index idx.
void add_3D_tensor_argument (unsigned int &idx, const IGCTensor *tensor, const unsigned int binding_point, const Window &window)
Add the passed 3D tensor's parameters to the object's kernel's arguments starting from the index idx.
unsigned int num_arguments_per_1D_tensor () const
Returns the number of arguments enqueued per 1D tensor object.
unsigned int num_arguments_per_2D_tensor () const
Returns the number of arguments enqueued per 2D tensor object.
unsigned int num_arguments_per_3D_tensor () const
Returns the number of arguments enqueued per 3D tensor object.
void set_lws_hint (gles::NDRange &lws_hint)
Set the Local-Workgroup-Size hint.
void set_target (GPUTarget target)
Set the targeted GPU architecture.
GPUTarget get_target () const
Get the targeted GPU architecture.
Public Member Functions inherited from IKernel
IKernel ()
Constructor.
virtual ~IKernel ()=default
Destructor.
virtual bool is_parallelisable () const
Indicates whether or not the kernel is parallelisable.
virtual BorderSize border_size () const
The size of the border for that kernel.
const Window & window () const
The maximum window the kernel can be executed on.
Detailed Description
Interface for the dropout layer kernel.
Dropout is used to improve over-fit on neural networks.
Definition at line 39 of file GCDropoutLayerKernel.h.
Constructor & Destructor Documentation
GCDropoutLayerKernel() [1/3]
GCDropoutLayerKernel ()
Default constructor.
Definition at line 43 of file GCDropoutLayerKernel.cpp.
     : _input(nullptr), _mask(nullptr), _output(nullptr), _num_elems_processed_per_iteration(0)
 {
 }
GCDropoutLayerKernel() [2/3]
GCDropoutLayerKernel (const GCDropoutLayerKernel &) delete
Prevent instances of this class from being copied (As this class contains pointers)
GCDropoutLayerKernel() [3/3]
GCDropoutLayerKernel (GCDropoutLayerKernel &&) default
Allow instances of this class to be moved.
Member Function Documentation
configure()
void configure (const IGCTensor * input, IGCTensor * mask, IGCTensor * output, float ratio, bool forward)
Set the input and output of the kernel.
Parameters
[in] input The input tensor for this op. Data types supported: F16/F32
[out] mask The mask tensor. Data types supported: Same as input
[out] output The output tensor. Data types supported: Same as input
[in] ratio Dropout ratio
[in] forward Forward or backward propagation
Definition at line 48 of file GCDropoutLayerKernel.cpp.
 {
     ARM_COMPUTE_ERROR_ON_DATA_TYPE_CHANNEL_NOT_IN(input, 1, DataType::F16, DataType::F32);
     ARM_COMPUTE_ERROR_ON_MISMATCHING_DATA_TYPES(input, mask, output);
     _input  = input;
     _mask   = mask;
     _output = output;
     std::set<std::string>                 build_opts;
     std::string                           dt_name = (input->info()->data_type() == DataType::F32) ? "DATA_TYPE_FP32" : "DATA_TYPE_FP16";
     std::string                           fporbp  = forward ? "FORWARD" : "BACKWARD";
     std::random_device                    rd;
     std::mt19937                          mt(rd());
     std::uniform_real_distribution<float> dist(0.f, 1.f);
     build_opts.emplace("#define LOCAL_SIZE_X " + support::cpp11::to_string(1));
     build_opts.emplace("#define LOCAL_SIZE_Y " + support::cpp11::to_string(1));
     build_opts.emplace("#define LOCAL_SIZE_Z " + support::cpp11::to_string(1));
     build_opts.emplace("#define RATIO " + support::cpp11::to_string(ratio));
     build_opts.emplace("#define SCALE " + support::cpp11::to_string(1. / (1. - ratio)));
     build_opts.emplace("#define SEED " + support::cpp11::to_string(dist(mt)));
     build_opts.emplace("#define " + dt_name);
     build_opts.emplace("#define " + fporbp);
     _num_elems_processed_per_iteration = 4 / input->info()->element_size();
     // Create kernel
     _kernel = static_cast<GCKernel>(GCKernelLibrary::get().create_kernel("dropout", build_opts));
     // Configure kernel window
     Window win = calculate_max_window(*input->info(), Steps(_num_elems_processed_per_iteration));
     output->info()->set_valid_region(ValidRegion(Coordinates(), output->info()->tensor_shape()));
     IGCKernel::configure(win);
 }
References ARM_COMPUTE_ERROR_ON_DATA_TYPE_CHANNEL_NOT_IN, ARM_COMPUTE_ERROR_ON_MISMATCHING_DATA_TYPES, arm_compute::calculate_max_window(), arm_compute::create_kernel(), ITensorInfo::data_type(), ITensorInfo::element_size(), arm_compute::F16, arm_compute::F32, arm_compute::test::validation::forward, GCKernelLibrary::get(), ITensor::info(), ITensorInfo::set_valid_region(), ITensorInfo::tensor_shape(), and arm_compute::support::cpp11::to_string().
Referenced by GCDropoutLayer::configure().
operator=() [1/2]
GCDropoutLayerKernel& operator= (const GCDropoutLayerKernel &) delete
Prevent instances of this class from being copied (As this class contains pointers)
operator=() [2/2]
GCDropoutLayerKernel& operator= (GCDropoutLayerKernel &&) default
Allow instances of this class to be moved.
run()
void run (const Window & window) override virtual
Enqueue the OpenGL ES shader to process the given window.
Parameters
[in] window Region on which to execute the kernel. (Must be a valid region of the window returned by window()).
Implements IGCKernel.
Definition at line 86 of file GCDropoutLayerKernel.cpp.
 {
     ARM_COMPUTE_ERROR_ON_UNCONFIGURED_KERNEL(this);
     ARM_COMPUTE_ERROR_ON_MISMATCHING_WINDOWS(IGCKernel::window(), window);
     _kernel.use();
     Window slice = window.first_slice_window_3D();
     do
     {
         unsigned int idx = 0;
         add_3D_tensor_argument(idx, _input, 1, slice);
         add_3D_tensor_argument(idx, _mask, 2, slice);
         add_3D_tensor_argument(idx, _output, 3, slice);
         _kernel.update_shader_params();
         enqueue(*this, slice);
     }
     while(window.slide_window_slice_3D(slice));
 }
References IGCKernel::add_3D_tensor_argument(), ARM_COMPUTE_ERROR_ON_MISMATCHING_WINDOWS, ARM_COMPUTE_ERROR_ON_UNCONFIGURED_KERNEL, arm_compute::enqueue(), Window::first_slice_window_3D(), arm_compute::test::validation::reference::slice(), Window::slide_window_slice_3D(), and IKernel::window().
The documentation for this class was generated from the following files:
arm_compute/core/GLES_COMPUTE/kernels/GCDropoutLayerKernel.h
src/core/GLES_COMPUTE/kernels/GCDropoutLayerKernel.cpp