Compute Library: CLConvertFullyConnectedWeightsKernel Class Reference
CLConvertFullyConnectedWeightsKernel Class Reference
Interface to convert the 2D Fully Connected weights from NCHW to NHWC or vice versa.
#include <CLConvertFullyConnectedWeightsKernel.h>
Public Member Functions
CLConvertFullyConnectedWeightsKernel ()
Default constructor.
CLConvertFullyConnectedWeightsKernel (const CLConvertFullyConnectedWeightsKernel &)=delete
Prevent instances of this class from being copied (As this class contains pointers)
CLConvertFullyConnectedWeightsKernel & operator= (const CLConvertFullyConnectedWeightsKernel &)=delete
Prevent instances of this class from being copied (As this class contains pointers)
CLConvertFullyConnectedWeightsKernel (CLConvertFullyConnectedWeightsKernel &&)=default
Allow instances of this class to be moved.
CLConvertFullyConnectedWeightsKernel & operator= (CLConvertFullyConnectedWeightsKernel &&)=default
Allow instances of this class to be moved.
~CLConvertFullyConnectedWeightsKernel ()=default
Default destructor.
void configure (const ICLTensor *input, ICLTensor *output, const TensorShape &original_input_shape, DataLayout data_layout)
Set the input and output tensor.
void run (const Window &window, cl::CommandQueue &queue) override
Enqueue the OpenCL kernel to process the given window on the passed OpenCL command queue.
Public Member Functions inherited from ICLKernel
ICLKernel ()
Constructor.
cl::Kernel & kernel ()
Returns a reference to the OpenCL kernel of this object.
template<typename T >
void add_1D_array_argument (unsigned int &idx, const ICLArray< T > *array, const Strides &strides, unsigned int num_dimensions, const Window &window)
Add the passed 1D array's parameters to the object's kernel's arguments starting from the index idx.
void add_1D_tensor_argument (unsigned int &idx, const ICLTensor *tensor, const Window &window)
Add the passed 1D tensor's parameters to the object's kernel's arguments starting from the index idx.
void add_1D_tensor_argument_if (bool cond, unsigned int &idx, const ICLTensor *tensor, const Window &window)
Add the passed 1D tensor's parameters to the object's kernel's arguments starting from the index idx if the condition is true.
void add_2D_tensor_argument (unsigned int &idx, const ICLTensor *tensor, const Window &window)
Add the passed 2D tensor's parameters to the object's kernel's arguments starting from the index idx.
void add_2D_tensor_argument_if (bool cond, unsigned int &idx, const ICLTensor *tensor, const Window &window)
Add the passed 2D tensor's parameters to the object's kernel's arguments starting from the index idx if the condition is true.
void add_3D_tensor_argument (unsigned int &idx, const ICLTensor *tensor, const Window &window)
Add the passed 3D tensor's parameters to the object's kernel's arguments starting from the index idx.
void add_4D_tensor_argument (unsigned int &idx, const ICLTensor *tensor, const Window &window)
Add the passed 4D tensor's parameters to the object's kernel's arguments starting from the index idx.
template<typename T >
void add_argument (unsigned int &idx, T value)
Add the passed parameters to the object's kernel's arguments starting from the index idx.
void set_lws_hint (const cl::NDRange &lws_hint)
Set the Local-Workgroup-Size hint.
cl::NDRange lws_hint () const
Return the Local-Workgroup-Size hint.
const std::string & config_id () const
Get the configuration ID.
void set_target (GPUTarget target)
Set the targeted GPU architecture.
void set_target (cl::Device &device)
Set the targeted GPU architecture according to the CL device.
GPUTarget get_target () const
Get the targeted GPU architecture.
size_t get_max_workgroup_size ()
Get the maximum workgroup size for the device the CLKernelLibrary uses.
template<typename T , unsigned int dimension_size>
void add_array_argument (unsigned &idx, const ICLArray< T > *array, const Strides &strides, unsigned int num_dimensions, const Window &window)
Add the passed array's parameters to the object's kernel's arguments starting from the index idx.
template<unsigned int dimension_size>
void add_tensor_argument (unsigned &idx, const ICLTensor *tensor, const Window &window)
Public Member Functions inherited from IKernel
IKernel ()
Constructor.
virtual ~IKernel ()=default
Destructor.
virtual bool is_parallelisable () const
Indicates whether or not the kernel is parallelisable.
virtual BorderSize border_size () const
The size of the border for that kernel.
const Window & window () const
The maximum window the kernel can be executed on.
Static Public Member Functions
static Status validate (const ITensorInfo *input, const ITensorInfo *output, const TensorShape &original_input_shape, DataLayout data_layout)
Static function to check if given info will lead to a valid configuration of CLConvertFullyConnectedWeightsKernel.
Static Public Member Functions inherited from ICLKernel
static constexpr unsigned int num_arguments_per_1D_array ()
Returns the number of arguments enqueued per 1D array object.
static constexpr unsigned int num_arguments_per_1D_tensor ()
Returns the number of arguments enqueued per 1D tensor object.
static constexpr unsigned int num_arguments_per_2D_tensor ()
Returns the number of arguments enqueued per 2D tensor object.
static constexpr unsigned int num_arguments_per_3D_tensor ()
Returns the number of arguments enqueued per 3D tensor object.
static constexpr unsigned int num_arguments_per_4D_tensor ()
Returns the number of arguments enqueued per 4D tensor object.
static cl::NDRange gws_from_window (const Window &window)
Get the global work size given an execution window.
Detailed Description
Interface to convert the 2D Fully Connected weights from NCHW to NHWC or vice versa.
Note
This function can be applied to the 2D weights used by a Fully Connected layer if:
It follows a Convolution layer
The data layout used by the network does not match the one the model has been trained in.
This function assumes the weights are already reshaped (transposed)
Definition at line 41 of file CLConvertFullyConnectedWeightsKernel.h.
Constructor & Destructor Documentation
CLConvertFullyConnectedWeightsKernel() [1/3]
CLConvertFullyConnectedWeightsKernel ()
Default constructor.
Definition at line 35 of file CLConvertFullyConnectedWeightsKernel.cpp.
     : _input(nullptr), _output(nullptr)
 {
 }
CLConvertFullyConnectedWeightsKernel() [2/3]
CLConvertFullyConnectedWeightsKernel (const CLConvertFullyConnectedWeightsKernel &) delete
Prevent instances of this class from being copied (As this class contains pointers)
CLConvertFullyConnectedWeightsKernel() [3/3]
CLConvertFullyConnectedWeightsKernel (CLConvertFullyConnectedWeightsKernel &&) default
Allow instances of this class to be moved.
~CLConvertFullyConnectedWeightsKernel()
~CLConvertFullyConnectedWeightsKernel () default
Default destructor.
Member Function Documentation
configure()
void configure (const ICLTensor * input, ICLTensor * output, const TensorShape & original_input_shape, DataLayout data_layout)
Set the input and output tensor.
Parameters
[in] input Source weights tensor to convert. Must be 2 dimensional. Data types supported: U8/S8/QASYMM8/U16/S16/U32/S32/F16/F32.
[out] output The converted weights tensor. Shape and Data Type: Same as input.
[in] original_input_shape Shape of the original input tensor (the one entering fully connected layer).
[in] data_layout The data layout the weights have been trained in.
Definition at line 40 of file CLConvertFullyConnectedWeightsKernel.cpp.
 {
     ARM_COMPUTE_ERROR_ON_NULLPTR(input, output);
     // Output tensor auto initialisation if not yet initialized
     auto_init_if_empty(*output->info(), *input->info()->clone());
     ARM_COMPUTE_ERROR_THROW_ON(CLConvertFullyConnectedWeightsKernel::validate(input->info(), output->info(), original_input_shape, data_layout));
     _input  = input;
     _output = output;
     const DataLayout input_data_layout = (data_layout == DataLayout::NCHW) ? DataLayout::NHWC : DataLayout::NCHW;
     const int width_idx   = get_data_layout_dimension_index(input_data_layout, DataLayoutDimension::WIDTH);
     const int height_idx  = get_data_layout_dimension_index(input_data_layout, DataLayoutDimension::HEIGHT);
     const int channel_idx = get_data_layout_dimension_index(input_data_layout, DataLayoutDimension::CHANNEL);
     const unsigned int num_elems_per_input_plane = original_input_shape[width_idx] * original_input_shape[height_idx];
     const unsigned int num_channels              = original_input_shape[channel_idx];
     const unsigned int factor_1 = (data_layout == DataLayout::NCHW) ? num_elems_per_input_plane : num_channels;
     const unsigned int factor_2 = (data_layout == DataLayout::NCHW) ? num_channels : num_elems_per_input_plane;
     // Set build options
     CLBuildOptions build_opts;
     build_opts.add_option("-DDATA_TYPE=" + get_cl_type_from_data_type(input->info()->data_type()));
     build_opts.add_option("-DFACTOR_1=" + support::cpp11::to_string(factor_1));
     build_opts.add_option("-DFACTOR_2=" + support::cpp11::to_string(factor_2));
     // Create kernel
     _kernel = static_cast<cl::Kernel>(CLKernelLibrary::get().create_kernel("convert_fc_weights", build_opts.options()));
     // Configure kernel window
     Window win = calculate_max_window(*input->info(), Steps());
     ICLKernel::configure_internal(win);
 }
References CLBuildOptions::add_option(), ARM_COMPUTE_ERROR_ON_NULLPTR, ARM_COMPUTE_ERROR_THROW_ON, arm_compute::auto_init_if_empty(), arm_compute::calculate_max_window(), arm_compute::CHANNEL, ICloneable< T >::clone(), arm_compute::create_kernel(), arm_compute::test::validation::data_layout, ITensorInfo::data_type(), CLKernelLibrary::get(), arm_compute::get_cl_type_from_data_type(), arm_compute::get_data_layout_dimension_index(), arm_compute::HEIGHT, ITensor::info(), arm_compute::NCHW, arm_compute::NHWC, CLBuildOptions::options(), arm_compute::support::cpp11::to_string(), CLConvertFullyConnectedWeightsKernel::validate(), and arm_compute::WIDTH.
operator=() [1/2]
CLConvertFullyConnectedWeightsKernel& operator= (const CLConvertFullyConnectedWeightsKernel &) delete
Prevent instances of this class from being copied (As this class contains pointers)
operator=() [2/2]
CLConvertFullyConnectedWeightsKernel& operator= (CLConvertFullyConnectedWeightsKernel &&) default
Allow instances of this class to be moved.
run()
void run (const Window & window, cl::CommandQueue & queue) override virtual
Enqueue the OpenCL kernel to process the given window on the passed OpenCL command queue.
Note
The queue is not flushed by this method, and therefore the kernel will not have been executed by the time this method returns.
Parameters
[in] window Region on which to execute the kernel. (Must be a valid region of the window returned by window()).
[in,out] queue Command queue on which to enqueue the kernel.
Implements ICLKernel.
Definition at line 102 of file CLConvertFullyConnectedWeightsKernel.cpp.
 {
     ARM_COMPUTE_ERROR_ON_UNCONFIGURED_KERNEL(this);
     ARM_COMPUTE_ERROR_ON_INVALID_SUBWINDOW(ICLKernel::window(), window);
     unsigned int idx = 0;
     add_2D_tensor_argument(idx, _input, window);
     add_2D_tensor_argument(idx, _output, window);
     enqueue(queue, *this, window);
 }
References ICLKernel::add_2D_tensor_argument(), ARM_COMPUTE_ERROR_ON_INVALID_SUBWINDOW, ARM_COMPUTE_ERROR_ON_UNCONFIGURED_KERNEL, arm_compute::enqueue(), and IKernel::window().
validate()
Status validate (const ITensorInfo * input, const ITensorInfo * output, const TensorShape & original_input_shape, DataLayout data_layout) static
Static function to check if given info will lead to a valid configuration of CLConvertFullyConnectedWeightsKernel.
Parameters
[in] input Source weights tensor info to convert. Must be 2 dimensional. Data types supported: U8/S8/QASYMM8/U16/S16/U32/S32/F16/F32.
[in] output The converted weights tensor info. Shape and Data Type: Same as input.
[in] original_input_shape Shape of the original input tensor (the one entering fully connected layer).
[in] data_layout The data layout the weights have been trained in.
Definition at line 79 of file CLConvertFullyConnectedWeightsKernel.cpp.
 {
     ARM_COMPUTE_RETURN_ERROR_ON_F16_UNSUPPORTED(input);
     ARM_COMPUTE_RETURN_ERROR_ON_DATA_TYPE_CHANNEL_NOT_IN(input, 1,
                                                          DataType::U8, DataType::S8, DataType::QASYMM8,
                                                          DataType::U16, DataType::S16,
                                                          DataType::U32, DataType::S32,
                                                          DataType::F16, DataType::F32);
     ARM_COMPUTE_RETURN_ERROR_ON(input->num_dimensions() != 2);
     ARM_COMPUTE_RETURN_ERROR_ON(input->dimension(1) != original_input_shape.total_size_lower(3));
     ARM_COMPUTE_RETURN_ERROR_ON(data_layout == DataLayout::UNKNOWN);
     // Checks performed when output is configured
     if((output != nullptr) && (output->total_size() != 0))
     {
         ARM_COMPUTE_RETURN_ERROR_ON_MISMATCHING_DATA_TYPES(input, output);
         ARM_COMPUTE_RETURN_ERROR_ON_MISMATCHING_SHAPES(input, output);
     }
     return Status{};
 }
References ARM_COMPUTE_RETURN_ERROR_ON, ARM_COMPUTE_RETURN_ERROR_ON_DATA_TYPE_CHANNEL_NOT_IN, ARM_COMPUTE_RETURN_ERROR_ON_F16_UNSUPPORTED, ARM_COMPUTE_RETURN_ERROR_ON_MISMATCHING_DATA_TYPES, ARM_COMPUTE_RETURN_ERROR_ON_MISMATCHING_SHAPES, arm_compute::test::validation::data_layout, ITensorInfo::dimension(), arm_compute::F16, arm_compute::F32, ITensorInfo::num_dimensions(), arm_compute::QASYMM8, arm_compute::S16, arm_compute::S32, arm_compute::S8, ITensorInfo::total_size(), TensorShape::total_size_lower(), arm_compute::U16, arm_compute::U32, arm_compute::U8, and arm_compute::UNKNOWN.
Referenced by CLConvertFullyConnectedWeightsKernel::configure(), and CLConvertFullyConnectedWeights::validate().
The documentation for this class was generated from the following files:
arm_compute/core/CL/kernels/CLConvertFullyConnectedWeightsKernel.h
src/core/CL/kernels/CLConvertFullyConnectedWeightsKernel.cpp