Compute Library: NESpaceToDepthLayerKernel Class Reference
NESpaceToDepthLayerKernel Class Reference
Interface for the space to depth kernel.
#include <NESpaceToDepthLayerKernel.h>
Public Member Functions
const char * name () const override
Name of the kernel.
NESpaceToDepthLayerKernel ()
Default constructor.
NESpaceToDepthLayerKernel (const NESpaceToDepthLayerKernel &)=delete
Prevent instances of this class from being copied (As this class contains pointers)
NESpaceToDepthLayerKernel & operator= (const NESpaceToDepthLayerKernel &)=delete
Prevent instances of this class from being copied (As this class contains pointers)
NESpaceToDepthLayerKernel (NESpaceToDepthLayerKernel &&)=default
Allow instances of this class to be moved.
NESpaceToDepthLayerKernel & operator= (NESpaceToDepthLayerKernel &&)=default
Allow instances of this class to be moved.
~NESpaceToDepthLayerKernel ()=default
Default destructor.
void configure (const ITensor *input, ITensor *output, int32_t block_shape)
Initialise the kernel's inputs and output.
void run (const Window &window, const ThreadInfo &info) override
Execute the kernel on the passed window.
Public Member Functions inherited from ICPPKernel
virtual ~ICPPKernel ()=default
Default destructor.
Public Member Functions inherited from IKernel
IKernel ()
Constructor.
virtual ~IKernel ()=default
Destructor.
virtual bool is_parallelisable () const
Indicates whether or not the kernel is parallelisable.
virtual BorderSize border_size () const
The size of the border for that kernel.
const Window & window () const
The maximum window the kernel can be executed on.
Static Public Member Functions
static Status validate (const ITensorInfo *input, const ITensorInfo *output, int32_t block_shape)
Static function to check if given info will lead to a valid configuration of NESpaceToDepthLayerKernel.
Detailed Description
Interface for the space to depth kernel.
Definition at line 35 of file NESpaceToDepthLayerKernel.h.
Constructor & Destructor Documentation
NESpaceToDepthLayerKernel() [1/3]
NESpaceToDepthLayerKernel ()
Default constructor.
Definition at line 68 of file NESpaceToDepthLayerKernel.cpp.
     : _input(nullptr), _output(nullptr), _block_shape()
 {
 }
NESpaceToDepthLayerKernel() [2/3]
NESpaceToDepthLayerKernel (const NESpaceToDepthLayerKernel &) delete
Prevent instances of this class from being copied (As this class contains pointers)
NESpaceToDepthLayerKernel() [3/3]
NESpaceToDepthLayerKernel (NESpaceToDepthLayerKernel &&) default
Allow instances of this class to be moved.
~NESpaceToDepthLayerKernel()
~NESpaceToDepthLayerKernel () default
Default destructor.
Member Function Documentation
configure()
void configure (const ITensor * input, ITensor * output, int32_t block_shape)
Initialise the kernel's inputs and output.
Parameters
[in] input Tensor input. Supported tensor rank: 4. Data types supported: U8/S8/QASYMM8/U16/S16/F16/U32/S32/F32.
[out] output Tensor output. Data types supported: same as input
[in] block_shape Block shape value
Definition at line 73 of file NESpaceToDepthLayerKernel.cpp.
 {
     ARM_COMPUTE_ERROR_ON_NULLPTR(input, output);
     TensorShape output_shape = misc::shape_calculator::compute_space_to_depth_shape(input->info(), block_shape);
     auto_init_if_empty(*output->info(), output_shape, 1, input->info()->data_type());
     ARM_COMPUTE_ERROR_THROW_ON(validate_arguments(input->info(), output->info(), block_shape));
     _input       = input;
     _block_shape = block_shape;
     _output      = output;
     // Configure kernel window
     Window win = calculate_max_window(*output->info(), Steps());
     INEKernel::configure(win);
 }
References ARM_COMPUTE_ERROR_ON_NULLPTR, ARM_COMPUTE_ERROR_THROW_ON, arm_compute::auto_init_if_empty(), arm_compute::calculate_max_window(), arm_compute::misc::shape_calculator::compute_space_to_depth_shape(), ITensorInfo::data_type(), ITensor::info(), and arm_compute::test::validation::output_shape.
Referenced by NESpaceToDepthLayer::configure().
name()
const char* name () const inline override virtual
Name of the kernel.
Returns
Kernel name
Implements ICPPKernel.
Definition at line 38 of file NESpaceToDepthLayerKernel.h.
     {
         return "NESpaceToDepthLayerKernel";
     }
operator=() [1/2]
NESpaceToDepthLayerKernel& operator= (const NESpaceToDepthLayerKernel &) delete
Prevent instances of this class from being copied (As this class contains pointers)
operator=() [2/2]
NESpaceToDepthLayerKernel& operator= (NESpaceToDepthLayerKernel &&) default
Allow instances of this class to be moved.
run()
void run (const Window & window, const ThreadInfo & info) override virtual
Execute the kernel on the passed window.
Warning
If is_parallelisable() returns false then the passed window must be equal to window()
Note
The window has to be a region within the window returned by the window() method
The width of the window has to be a multiple of num_elems_processed_per_iteration().
Parameters
[in] window Region on which to execute the kernel. (Must be a region of the window returned by window())
[in] info Info about executing thread and CPU.
Implements ICPPKernel.
Definition at line 97 of file NESpaceToDepthLayerKernel.cpp.
 {
     ARM_COMPUTE_UNUSED(info);
     ARM_COMPUTE_ERROR_ON_UNCONFIGURED_KERNEL(this);
     ARM_COMPUTE_ERROR_ON_INVALID_SUBWINDOW(ICPPKernel::window(), window);
     const DataLayout data_layout  = _input->info()->data_layout();
     const int        channel_idx  = get_data_layout_dimension_index(data_layout, DataLayoutDimension::CHANNEL);
     const int        element_size = _input->info()->element_size();
     const size_t channel_size = _input->info()->dimension(channel_idx);
     Window slice_out = window.first_slice_window_3D();
     int batch_id = 0;
     // Main loop for NCHW and NHWC
     if(_output->info()->data_layout() == DataLayout::NCHW)
     {
         do
         {
             Iterator out(_output, slice_out);
             execute_window_loop(slice_out, [&](const Coordinates & id)
             {
                 const size_t channel_id = id.z();
                 const size_t in_x       = id.x() * _block_shape + (channel_id / channel_size) % _block_shape;
                 const size_t in_y       = id.y() * _block_shape + (channel_id / channel_size) / _block_shape;
                 const int    z          = channel_id % channel_size;
                 Coordinates  input_coords{ in_x, in_y, z, batch_id };
                 memcpy(out.ptr(), _input->ptr_to_element(input_coords), element_size);
             },
             out);
             ++batch_id;
         }
         while(window.slide_window_slice_3D(slice_out));
     }
     else
     {
         do
         {
             Iterator out(_output, slice_out);
             execute_window_loop(slice_out, [&](const Coordinates & id)
             {
                 const size_t channel_id = id.x();
                 const size_t in_x       = id.y() * _block_shape + (channel_id / channel_size) % _block_shape;
                 const size_t in_y       = id.z() * _block_shape + (channel_id / channel_size) / _block_shape;
                 const int    z          = channel_id % channel_size;
                 Coordinates  input_coords{ z, in_x, in_y, batch_id };
                 memcpy(out.ptr(), _input->ptr_to_element(input_coords), element_size);
             },
             out);
             ++batch_id;
         }
         while(window.slide_window_slice_3D(slice_out));
     }
 }
References ARM_COMPUTE_ERROR_ON_INVALID_SUBWINDOW, ARM_COMPUTE_ERROR_ON_UNCONFIGURED_KERNEL, ARM_COMPUTE_UNUSED, arm_compute::CHANNEL, arm_compute::test::validation::data_layout, ITensorInfo::data_layout(), ITensorInfo::dimension(), ITensorInfo::element_size(), arm_compute::execute_window_loop(), Window::first_slice_window_3D(), arm_compute::get_data_layout_dimension_index(), ITensor::info(), arm_compute::test::validation::info, arm_compute::NCHW, Iterator::ptr(), ITensor::ptr_to_element(), Window::slide_window_slice_3D(), IKernel::window(), Window::x(), and Window::z().
validate()
Status validate (const ITensorInfo * input, const ITensorInfo * output, int32_t block_shape) static
Static function to check if given info will lead to a valid configuration of NESpaceToDepthLayerKernel.
Parameters
[in] input Tensor input info. Supported tensor rank: 4. Data types supported: U8/S8/QASYMM8/U16/S16/F16/U32/S32/F32.
[in] output Tensor output info. Data types supported: same as input
[in] block_shape Block shape value
Returns
a status
Definition at line 91 of file NESpaceToDepthLayerKernel.cpp.
 {
     ARM_COMPUTE_RETURN_ON_ERROR(validate_arguments(input, output, block_shape));
     return Status{};
 }
References ARM_COMPUTE_RETURN_ON_ERROR.
Referenced by NESpaceToDepthLayer::validate().
The documentation for this class was generated from the following files:
arm_compute/core/NEON/kernels/NESpaceToDepthLayerKernel.h
src/core/NEON/kernels/NESpaceToDepthLayerKernel.cpp