Compute Library: NormalizePlanarYUVLayer Class Reference
NormalizePlanarYUVLayer Class Reference final
Normalize planar YUV Layer.
#include <Layers.h>
Public Member Functions
NormalizePlanarYUVLayer (ITensorAccessorUPtr mean, ITensorAccessorUPtr std)
Construct a normalize planar YUV layer.
NodeID create_layer (IStream &s) override
Create layer and add to the given stream.
Public Member Functions inherited from ILayer
virtual ~ILayer ()=default
Default destructor.
ILayer & set_name (std::string name)
Sets the name of the layer.
const std::string & name () const
Layer name accessor.
Detailed Description
Normalize planar YUV Layer.
Definition at line 755 of file Layers.h.
Constructor & Destructor Documentation
NormalizePlanarYUVLayer()
NormalizePlanarYUVLayer (ITensorAccessorUPtr mean, ITensorAccessorUPtr std) inline
Construct a normalize planar YUV layer.
Parameters
[in] mean Accessor to get mean tensor data from.
[in] std Accessor to get std tensor data from.
Definition at line 763 of file Layers.h.
         : _mean(std::move(mean)), _std(std::move(std))
     {
     }
Member Function Documentation
create_layer()
NodeID create_layer (IStream & s) inline override virtual
Create layer and add to the given stream.
Parameters
[in] s Stream to add layer to.
Returns
ID of the created node.
Implements ILayer.
Definition at line 769 of file Layers.h.
     {
         ARM_COMPUTE_ERROR_ON(_mean == nullptr);
         ARM_COMPUTE_ERROR_ON(_std == nullptr);
         NodeParams  common_params = { name(), s.hints().target_hint };
         NodeIdxPair input         = { s.tail_node(), 0 };
         return GraphBuilder::add_normalize_planar_yuv_node(s.graph(), common_params, input,
                                                            std::move(_mean), std::move(_std));
     }
References GraphBuilder::add_normalize_planar_yuv_node(), ARM_COMPUTE_ERROR_ON, IStream::graph(), IStream::hints(), ILayer::name(), IStream::tail_node(), and StreamHints::target_hint.
The documentation for this class was generated from the following file:
arm_compute/graph/frontend/Layers.h