Compute Library: ResizeLayer Class Reference
ResizeLayer Class Reference final
Resize Layer.
#include <Layers.h>
Public Member Functions
ResizeLayer (InterpolationPolicy policy, float width_scale, float height_scale)
NodeID create_layer (IStream &s) override
Create layer and add to the given stream.
Public Member Functions inherited from ILayer
virtual ~ILayer ()=default
Default destructor.
ILayer & set_name (std::string name)
Sets the name of the layer.
const std::string & name () const
Layer name accessor.
Detailed Description
Resize Layer.
Definition at line 962 of file Layers.h.
Constructor & Destructor Documentation
ResizeLayer()
ResizeLayer (InterpolationPolicy policy, float width_scale, float height_scale) inline
Definition at line 965 of file Layers.h.
         : _policy(policy), _width_scale(width_scale), _height_scale(height_scale)
     {
     }
Member Function Documentation
create_layer()
NodeID create_layer (IStream & s) inline override virtual
Create layer and add to the given stream.
Parameters
[in] s Stream to add layer to.
Returns
ID of the created node.
Implements ILayer.
Definition at line 970 of file Layers.h.
     {
         NodeParams  common_params = { name(), s.hints().target_hint };
         NodeIdxPair input         = { s.tail_node(), 0 };
         return GraphBuilder::add_resize_node(s.graph(), common_params, input, _policy, _width_scale, _height_scale);
     }
References GraphBuilder::add_resize_node(), IStream::graph(), IStream::hints(), ILayer::name(), IStream::tail_node(), and StreamHints::target_hint.
The documentation for this class was generated from the following file:
arm_compute/graph/frontend/Layers.h