Compute Library: ICLMemoryRegion Class Reference
ICLMemoryRegion Class Reference abstract
OpenCL memory region interface.
#include <CLMemoryRegion.h>
Public Member Functions
ICLMemoryRegion (cl::Context ctx, size_t size)
Constructor.
virtual ~ICLMemoryRegion ()=default
Default Destructor.
ICLMemoryRegion (const ICLMemoryRegion &)=delete
Prevent instances of this class from being copied (As this class contains pointers)
ICLMemoryRegion (ICLMemoryRegion &&)=default
Default move constructor.
ICLMemoryRegion & operator= (const ICLMemoryRegion &)=delete
Prevent instances of this class from being copied (As this class contains pointers)
ICLMemoryRegion & operator= (ICLMemoryRegion &&)=default
Default move assignment operator.
const cl::Buffer & cl_data () const
Returns the underlying CL buffer.
virtual void * ptr ()=0
Host/SVM pointer accessor.
virtual void * map (cl::CommandQueue &q, bool blocking)=0
Enqueue a map operation of the allocated buffer on the given queue.
virtual void unmap (cl::CommandQueue &q)=0
Enqueue an unmap operation of the allocated buffer on the given queue.
void * buffer () override
Returns the pointer to the allocated data.
void * buffer () const override
Returns the pointer to the allocated data.
std::unique_ptr< IMemoryRegion > extract_subregion (size_t offset, size_t size) override
Extract a sub-region from the memory.
Public Member Functions inherited from IMemoryRegion
IMemoryRegion (size_t size)
Default constructor.
virtual ~IMemoryRegion ()=default
Virtual Destructor.
size_t size () const
Memory region size accessor.
void set_size (size_t size)
Sets size of region.
Detailed Description
OpenCL memory region interface.
Definition at line 35 of file CLMemoryRegion.h.
Constructor & Destructor Documentation
ICLMemoryRegion() [1/3]
ICLMemoryRegion (cl::Context ctx, size_t size)
Constructor.
Parameters
[in] ctx OpenCL context
[in] size Region size
Definition at line 31 of file CLMemoryRegion.cpp.
     : IMemoryRegion(size), _ctx(std::move(ctx)), _mapping(nullptr), _mem()
 {
 }
~ICLMemoryRegion()
virtual ~ICLMemoryRegion () virtual default
Default Destructor.
ICLMemoryRegion() [2/3]
ICLMemoryRegion (const ICLMemoryRegion &) delete
Prevent instances of this class from being copied (As this class contains pointers)
ICLMemoryRegion() [3/3]
ICLMemoryRegion (ICLMemoryRegion &&) default
Default move constructor.
Member Function Documentation
buffer() [1/2]
void * buffer () override virtual
Returns the pointer to the allocated data.
Returns
Pointer to the allocated data
Implements IMemoryRegion.
Definition at line 41 of file CLMemoryRegion.cpp.
 {
     return _mapping;
 }
Referenced by CLBufferMemoryRegion::CLBufferMemoryRegion().
buffer() [2/2]
void * buffer () const override virtual
Returns the pointer to the allocated data.
Returns
Pointer to the allocated data
Implements IMemoryRegion.
Definition at line 46 of file CLMemoryRegion.cpp.
 {
     return _mapping;
 }
cl_data()
const cl::Buffer & cl_data () const
Returns the underlying CL buffer.
Returns
CL memory buffer object
Definition at line 36 of file CLMemoryRegion.cpp.
 {
     return _mem;
 }
Referenced by CLTensorAllocator::allocate(), CLTensorAllocator::cl_data(), and CLTensorAllocator::set_associated_memory_group().
extract_subregion()
std::unique_ptr< IMemoryRegion > extract_subregion (size_t offset, size_t size) override virtual
Extract a sub-region from the memory.
Warning
Ownership is maintained by the parent memory, while a wrapped raw memory region is returned by this function. Thus parent memory should not be released before this.
Parameters
[in] offset Offset to the region
[in] size Size of the region
Returns
A wrapped memory sub-region with no ownership of the underlying memory
Implements IMemoryRegion.
Definition at line 51 of file CLMemoryRegion.cpp.
 {
     ARM_COMPUTE_UNUSED(offset, size);
     return nullptr;
 }
References ARM_COMPUTE_UNUSED, offset(), and IMemoryRegion::size().
map()
virtual void* map (cl::CommandQueue & q, bool blocking) pure virtual
Enqueue a map operation of the allocated buffer on the given queue.
Parameters
[in,out] q The CL command queue to use for the mapping operation.
[in] blocking If true, then the mapping will be ready to use by the time this method returns, else it is the caller's responsibility to flush the queue and wait for the mapping operation to have completed before using the returned mapping pointer.
Returns
The mapping address.
Implemented in CLFineSVMMemoryRegion, CLCoarseSVMMemoryRegion, and CLBufferMemoryRegion.
Referenced by CLTensorAllocator::map().
operator=() [1/2]
ICLMemoryRegion& operator= (const ICLMemoryRegion &) delete
Prevent instances of this class from being copied (As this class contains pointers)
operator=() [2/2]
ICLMemoryRegion& operator= (ICLMemoryRegion &&) default
Default move assignment operator.
ptr()
virtual void* ptr () pure virtual
Host/SVM pointer accessor.
Returns
Host/SVM pointer base
Implemented in CLBufferMemoryRegion.
unmap()
virtual void unmap (cl::CommandQueue & q) pure virtual
Enqueue an unmap operation of the allocated buffer on the given queue.
Note
This method simply enqueue the unmap operation, it is the caller's responsibility to flush the queue and make sure the unmap is finished before the memory is accessed by the device.
Parameters
[in,out] q The CL command queue to use for the mapping operation.
Implemented in CLFineSVMMemoryRegion, CLCoarseSVMMemoryRegion, and CLBufferMemoryRegion.
Referenced by CLTensorAllocator::unmap().
The documentation for this class was generated from the following files:
arm_compute/runtime/CL/CLMemoryRegion.h
src/runtime/CL/CLMemoryRegion.cpp