Compute Library: NEDepthwiseConvolutionLayerOptimized Class Reference
NEDepthwiseConvolutionLayerOptimized Class Reference
Basic function to execute optimized depthwise convolution routines.
#include <NEDepthwiseConvolutionLayer.h>
Public Member Functions
NEDepthwiseConvolutionLayerOptimized (std::shared_ptr< IMemoryManager > memory_manager=nullptr)
Default constructor.
NEDepthwiseConvolutionLayerOptimized (const NEDepthwiseConvolutionLayerOptimized &)=delete
Prevent instances of this class from being copied (As this class contains pointers)
NEDepthwiseConvolutionLayerOptimized (NEDepthwiseConvolutionLayerOptimized &&)=default
Default move constructor.
NEDepthwiseConvolutionLayerOptimized & operator= (const NEDepthwiseConvolutionLayerOptimized &)=delete
Prevent instances of this class from being copied (As this class contains pointers)
NEDepthwiseConvolutionLayerOptimized & operator= (NEDepthwiseConvolutionLayerOptimized &&)=default
Default move assignment operator.
void configure (ITensor *input, const ITensor *weights, const ITensor *biases, ITensor *output, const PadStrideInfo &conv_info, unsigned int depth_multiplier=1, const ActivationLayerInfo &act_info=ActivationLayerInfo(), const Size2D &dilation=Size2D(1U, 1U))
Initialize the function's source, destination, kernels and border_size.
void run () override
Run the kernels contained in the function.
void prepare () override
Prepare the function for executing.
Public Member Functions inherited from IFunction
virtual ~IFunction ()=default
Destructor.
Static Public Member Functions
static Status validate (const ITensorInfo *input, const ITensorInfo *weights, const ITensorInfo *biases, const ITensorInfo *output, const PadStrideInfo &conv_info, unsigned int depth_multiplier=1, const ActivationLayerInfo &act_info=ActivationLayerInfo(), const Size2D &dilation=Size2D(1U, 1U))
Static function to check if given info will lead to a valid configuration of NEDepthwiseConvolutionLayer3x3.
Detailed Description
Basic function to execute optimized depthwise convolution routines.
This function calls the following NEON kernels:
Note
At the moment 3x3 and 5x5 convolution of stride 1, 2 are supported
NEFillBorderKernel (if pad_x or pad_y > 0) and no assembly kernel implementation is present
NEDepthwiseConvolutionLayer3x3Kernel if 3x3 and no assembly kernel implementation is present
NEDepthwiseConvolutionAssemblyDispatch if assembly kernel implementation is present
NEDirectConvolutionLayerOutputStageKernel if re-quantization of output is required
NEActivationLayer if fused activation is required
Definition at line 175 of file NEDepthwiseConvolutionLayer.h.
Constructor & Destructor Documentation
NEDepthwiseConvolutionLayerOptimized() [1/3]
NEDepthwiseConvolutionLayerOptimized (std::shared_ptr< IMemoryManager > memory_manager = nullptr)
Default constructor.
Definition at line 369 of file NEDepthwiseConvolutionLayer.cpp.
     : _memory_group(memory_manager), _dwc_kernel(), _dwc_optimized_func(memory_manager), _output_stage_kernel(), _border_handler(), _permute_input(), _permute_weights(), _permute_output(),
       _activationlayer_function(), _accumulator(), _permuted_input(), _permuted_weights(), _permuted_output(), _original_weights(nullptr), _has_bias(false), _is_quantized(false), _is_optimized(false),
       _is_nchw(true), _permute(false), _is_activationlayer_enabled(false), _is_prepared(false)
 {
 }
NEDepthwiseConvolutionLayerOptimized() [2/3]
NEDepthwiseConvolutionLayerOptimized (const NEDepthwiseConvolutionLayerOptimized &) delete
Prevent instances of this class from being copied (As this class contains pointers)
NEDepthwiseConvolutionLayerOptimized() [3/3]
NEDepthwiseConvolutionLayerOptimized (NEDepthwiseConvolutionLayerOptimized &&) default
Default move constructor.
Member Function Documentation
configure()
void configure (ITensor * input, const ITensor * weights, const ITensor * biases, ITensor * output, const PadStrideInfo & conv_info, unsigned int depth_multiplier = 1, const ActivationLayerInfo & act_info = ActivationLayerInfo(), const Size2D & dilation = Size2D(1U, 1U))
Initialize the function's source, destination, kernels and border_size.
Parameters
[in,out] input Source tensor. Data type supported: QASYMM8/F16/F32. (Written to only for border filling).
[in] weights Weights tensor. These are 3D tensors with shape [W, H, IFM]. Data type supported: Same as input.
[in] biases Biases tensor. A 1D tensor with shape [IFM]. Must be nullptr if not needed. Data type supported: Same as input.
[out] output Destination tensor. Data type supported: same as input.
[in] conv_info Padding and stride information to use for the convolution.
[in] depth_multiplier (Optional) Multiplier to apply to the input's depth in order to retrieve the output's depth. Defaults to 1.
[in] act_info (Optional) Activation layer information in case of a fused activation.
[in] dilation (Optional) Dilation, in elements, across x and y. Defaults to (1, 1).
Definition at line 517 of file NEDepthwiseConvolutionLayer.cpp.
 {
     ARM_COMPUTE_ERROR_ON_NULLPTR(input, weights, output);
     // Perform validation step
     ARM_COMPUTE_ERROR_THROW_ON(NEDepthwiseConvolutionLayerOptimized::validate(input->info(), weights->info(), (biases == nullptr) ? nullptr : biases->info(),
                                                                               output->info(), conv_info, depth_multiplier, act_info, dilation));
     _original_weights = weights;
     _is_quantized     = is_data_type_quantized_asymmetric(input->info()->data_type());
     _has_bias         = biases != nullptr;
     _is_optimized     = NEDepthwiseConvolutionAssemblyDispatch::is_optimized_supported(input->info(),
                                                                                        weights->info(),
                                                                                        conv_info,
                                                                                        depth_multiplier,
                                                                                        dilation);
     _is_nchw                    = input->info()->data_layout() == DataLayout::NCHW;
     _permute                    = _is_optimized == _is_nchw;
     _is_prepared                = false;
     _is_activationlayer_enabled = act_info.enabled();
     // Configure appropriate pipeline
     if(_is_optimized)
     {
         configure_optimized(input, weights, biases, output, conv_info, depth_multiplier, act_info, dilation);
     }
     else
     {
         configure_generic(input, weights, biases, output, conv_info, depth_multiplier, act_info, dilation);
     }
     // Configure activation
     if(_is_activationlayer_enabled)
     {
         _activationlayer_function.configure(output, nullptr, act_info);
     }
 }
References arm_compute::test::validation::act_info, ARM_COMPUTE_ERROR_ON_NULLPTR, ARM_COMPUTE_ERROR_THROW_ON, NEActivationLayer::configure(), arm_compute::test::validation::conv_info, ITensorInfo::data_layout(), ITensorInfo::data_type(), arm_compute::test::validation::dilation, ITensor::info(), CLTensor::info(), arm_compute::is_data_type_quantized_asymmetric(), NEDepthwiseConvolutionAssemblyDispatch::is_optimized_supported(), arm_compute::NCHW, NEDepthwiseConvolutionLayerOptimized::validate(), and arm_compute::test::validation::weights.
operator=() [1/2]
NEDepthwiseConvolutionLayerOptimized& operator= (const NEDepthwiseConvolutionLayerOptimized &) delete
Prevent instances of this class from being copied (As this class contains pointers)
operator=() [2/2]
NEDepthwiseConvolutionLayerOptimized& operator= (NEDepthwiseConvolutionLayerOptimized &&) default
Default move assignment operator.
prepare()
void prepare () override virtual
Prepare the function for executing.
Any one off pre-processing step required by the function is handled here
Note
Prepare stage might not need all the function's buffers' backing memory to be available in order to execute
Reimplemented from IFunction.
Definition at line 677 of file NEDepthwiseConvolutionLayer.cpp.
 {
     if(!_is_prepared)
     {
         // Permute weights
         if(_permute)
         {
             _permuted_weights.allocator()->allocate();
             _permute_weights.run();
             _original_weights->mark_as_unused();
         }
         // Prepare optimized function
         if(_is_optimized)
         {
             _dwc_optimized_func.prepare();
             if(!_permuted_weights.is_used())
             {
                 _permuted_weights.allocator()->free();
             }
         }
         _is_prepared = true;
     }
 }
References TensorAllocator::allocate(), Tensor::allocator(), TensorAllocator::free(), ITensor::is_used(), ITensor::mark_as_unused(), NEDepthwiseConvolutionAssemblyDispatch::prepare(), and INESimpleFunctionNoBorder::run().
Referenced by NEDepthwiseConvolutionLayerOptimized::run().
run()
void run () override virtual
Run the kernels contained in the function.
For NEON kernels:
Multi-threading is used for the kernels which are parallelisable.
By default std::thread::hardware_concurrency() threads are used.
Note
CPPScheduler::set_num_threads() can be used to manually set the number of threads
For OpenCL kernels:
All the kernels are enqueued on the queue associated with CLScheduler.
The queue is then flushed.
Note
The function will not block until the kernels are executed. It is the user's responsibility to wait.
Will call prepare() on first run if hasn't been done
Implements IFunction.
Definition at line 656 of file NEDepthwiseConvolutionLayer.cpp.
 {
     prepare();
     MemoryGroupResourceScope scope_mg(_memory_group);
     // Permute input
     if(_permute)
     {
         _permute_input.run();
     }
     _is_optimized ? run_optimized() : run_generic();
     // Run activation
     if(_is_activationlayer_enabled)
     {
         _activationlayer_function.run();
     }
 }
References NEDepthwiseConvolutionLayerOptimized::prepare(), and INESimpleFunctionNoBorder::run().
validate()
Status validate (const ITensorInfo * input, const ITensorInfo * weights, const ITensorInfo * biases, const ITensorInfo * output, const PadStrideInfo & conv_info, unsigned int depth_multiplier = 1, const ActivationLayerInfo & act_info = ActivationLayerInfo(), const Size2D & dilation = Size2D(1U, 1U)) static
Static function to check if given info will lead to a valid configuration of NEDepthwiseConvolutionLayer3x3.
Parameters
[in] input Source tensor. Data type supported: QASYMM8/F16/F32. (Written to only for border filling).
[in] weights Weights tensor. These are 3D tensors with shape [W, H, IFM]. Data type supported: Same as input.
[in] biases Biases tensor. A 1D tensor with shape [IFM]. Must be nullptr if not needed. Data type supported: Same as input.
[in] output Destination tensor. Data type supported: same as input.
[in] conv_info Padding and stride information to use for the convolution.
[in] depth_multiplier (Optional) Multiplier to apply to the input's depth in order to retrieve the output's depth. Defaults to 1.
[in] act_info (Optional) Activation layer information in case of a fused activation.
[in] dilation (Optional) Dilation, in elements, across x and y. Defaults to (1, 1).
Returns
a status
Definition at line 560 of file NEDepthwiseConvolutionLayer.cpp.
 {
     ARM_COMPUTE_RETURN_ERROR_ON_NULLPTR(input, weights, output);
     ARM_COMPUTE_RETURN_ERROR_ON_DATA_TYPE_CHANNEL_NOT_IN(input, 1, DataType::QASYMM8, DataType::F16, DataType::F32);
     ARM_COMPUTE_RETURN_ERROR_ON_MISMATCHING_DATA_TYPES(input, weights);
     ARM_COMPUTE_RETURN_ERROR_ON(input->data_layout() == DataLayout::UNKNOWN);
     ARM_COMPUTE_RETURN_ERROR_ON(dilation.x() < 1 || dilation.y() < 1);
     const size_t idx_w = get_data_layout_dimension_index(input->data_layout(), DataLayoutDimension::WIDTH);
     const size_t idx_h = get_data_layout_dimension_index(input->data_layout(), DataLayoutDimension::HEIGHT);
     ARM_COMPUTE_RETURN_ERROR_ON(weights->dimension(idx_w) + (weights->dimension(idx_w) - 1) * (dilation.x() - 1) > input->dimension(idx_w) + conv_info.pad_left() + conv_info.pad_right());
     ARM_COMPUTE_RETURN_ERROR_ON(weights->dimension(idx_h) + (weights->dimension(idx_h) - 1) * (dilation.y() - 1) > input->dimension(idx_h) + conv_info.pad_top() + conv_info.pad_bottom());
     if(biases != nullptr)
     {
         const unsigned int channel_idx = get_data_layout_dimension_index(input->data_layout(), DataLayoutDimension::CHANNEL);
         ARM_COMPUTE_RETURN_ERROR_ON(biases->num_dimensions() > 1);
         ARM_COMPUTE_RETURN_ERROR_ON(biases->dimension(0) != weights->dimension(channel_idx));
     }
     const bool is_quantized = is_data_type_quantized_asymmetric(input->data_type());
     if(is_quantized)
     {
         const UniformQuantizationInfo iq_info = input->quantization_info().uniform();
         const UniformQuantizationInfo wq_info = weights->quantization_info().uniform();
         const UniformQuantizationInfo oq_info = output->quantization_info().uniform();
         float multiplier = (iq_info.scale * wq_info.scale) / oq_info.scale;
         ARM_COMPUTE_UNUSED(multiplier);
         ARM_COMPUTE_RETURN_ERROR_ON(multiplier > 1.0f);
     }
     if(!NEDepthwiseConvolutionAssemblyDispatch::is_optimized_supported(input, weights, conv_info, depth_multiplier, dilation))
     {
         TensorInfo accumulator = TensorInfo(output->clone()->set_is_resizable(true).reset_padding().set_data_type(DataType::S32));
         ARM_COMPUTE_RETURN_ON_ERROR(NEDepthwiseConvolutionLayer3x3Kernel::validate(input, weights, is_quantized ? &accumulator : output, conv_info, depth_multiplier, dilation));
         if(is_quantized)
         {
             ARM_COMPUTE_RETURN_ON_ERROR(NEDirectConvolutionLayerOutputStageKernel::validate(&accumulator, biases, output));
         }
     }
     else
     {
         ARM_COMPUTE_RETURN_ON_ERROR(NEDepthwiseConvolutionAssemblyDispatch::validate(input, weights, biases, output, conv_info, depth_multiplier, act_info, dilation));
     }
     //Validate Activation Layer
     if(act_info.enabled())
     {
         ARM_COMPUTE_RETURN_ON_ERROR(NEActivationLayer::validate(output, nullptr, act_info));
     }
     return Status{};
 }
References arm_compute::test::validation::act_info, ARM_COMPUTE_RETURN_ERROR_ON, ARM_COMPUTE_RETURN_ERROR_ON_DATA_TYPE_CHANNEL_NOT_IN, ARM_COMPUTE_RETURN_ERROR_ON_MISMATCHING_DATA_TYPES, ARM_COMPUTE_RETURN_ERROR_ON_NULLPTR, ARM_COMPUTE_RETURN_ON_ERROR, ARM_COMPUTE_UNUSED, arm_compute::CHANNEL, ICloneable< T >::clone(), arm_compute::test::validation::conv_info, ITensorInfo::data_layout(), ITensorInfo::data_type(), arm_compute::test::validation::dilation, ITensorInfo::dimension(), arm_compute::F16, arm_compute::F32, arm_compute::get_data_layout_dimension_index(), arm_compute::HEIGHT, arm_compute::is_data_type_quantized_asymmetric(), NEDepthwiseConvolutionAssemblyDispatch::is_optimized_supported(), ITensorInfo::num_dimensions(), arm_compute::QASYMM8, ITensorInfo::quantization_info(), arm_compute::S32, UniformQuantizationInfo::scale, QuantizationInfo::uniform(), arm_compute::UNKNOWN, NEActivationLayer::validate(), NEDepthwiseConvolutionLayer3x3Kernel::validate(), NEDirectConvolutionLayerOutputStageKernel::validate(), NEDepthwiseConvolutionAssemblyDispatch::validate(), arm_compute::test::validation::weights, and arm_compute::WIDTH.
Referenced by NEDepthwiseConvolutionLayerOptimized::configure().
The documentation for this class was generated from the following files:
arm_compute/runtime/NEON/functions/NEDepthwiseConvolutionLayer.h
src/runtime/NEON/functions/NEDepthwiseConvolutionLayer.cpp