Compute Library: GCLogits1DShiftExpSumKernel Class Reference
GCLogits1DShiftExpSumKernel Class Reference
Interface for shifting the logits values around the max value and exponentiating the result.
#include <GCSoftmaxLayerKernel.h>
Public Member Functions
GCLogits1DShiftExpSumKernel ()
Default constructor.
GCLogits1DShiftExpSumKernel (const GCLogits1DShiftExpSumKernel &)=delete
Prevent instances of this class from being copied (As this class contains pointers)
GCLogits1DShiftExpSumKernel & operator= (const GCLogits1DShiftExpSumKernel &)=delete
Prevent instances of this class from being copied (As this class contains pointers)
GCLogits1DShiftExpSumKernel (GCLogits1DShiftExpSumKernel &&)=default
Allow instances of this class to be moved.
GCLogits1DShiftExpSumKernel & operator= (GCLogits1DShiftExpSumKernel &&)=default
Allow instances of this class to be moved.
void configure (const IGCTensor *input, const IGCTensor *max, IGCTensor *output, IGCTensor *sum)
Set the input and output tensors.
void run (const Window &window) override
Enqueue the OpenGL ES shader to process the given window.
Public Member Functions inherited from IGCKernel
IGCKernel ()
Constructor.
GCKernel & kernel ()
Returns a reference to the GLES kernel of this object.
void add_1D_tensor_argument (unsigned int &idx, const IGCTensor *tensor, const unsigned int binding_point, const Window &window)
Add the passed 1D tensor's parameters to the object's kernel's arguments starting from the index idx.
void add_2D_tensor_argument (unsigned int &idx, const IGCTensor *tensor, const unsigned int binding_point, const Window &window)
Add the passed 2D tensor's parameters to the object's kernel's arguments starting from the index idx.
void add_3D_tensor_argument (unsigned int &idx, const IGCTensor *tensor, const unsigned int binding_point, const Window &window)
Add the passed 3D tensor's parameters to the object's kernel's arguments starting from the index idx.
unsigned int num_arguments_per_1D_tensor () const
Returns the number of arguments enqueued per 1D tensor object.
unsigned int num_arguments_per_2D_tensor () const
Returns the number of arguments enqueued per 2D tensor object.
unsigned int num_arguments_per_3D_tensor () const
Returns the number of arguments enqueued per 3D tensor object.
void set_lws_hint (gles::NDRange &lws_hint)
Set the Local-Workgroup-Size hint.
void set_target (GPUTarget target)
Set the targeted GPU architecture.
GPUTarget get_target () const
Get the targeted GPU architecture.
Public Member Functions inherited from IKernel
IKernel ()
Constructor.
virtual ~IKernel ()=default
Destructor.
virtual bool is_parallelisable () const
Indicates whether or not the kernel is parallelisable.
virtual BorderSize border_size () const
The size of the border for that kernel.
const Window & window () const
The maximum window the kernel can be executed on.
Detailed Description
Interface for shifting the logits values around the max value and exponentiating the result.
Definition at line 46 of file GCSoftmaxLayerKernel.h.
Constructor & Destructor Documentation
GCLogits1DShiftExpSumKernel() [1/3]
GCLogits1DShiftExpSumKernel ()
Default constructor.
Definition at line 102 of file GCSoftmaxLayerKernel.cpp.
     : _input(nullptr), _max(nullptr), _output(nullptr), _sum(nullptr)
 {
 }
GCLogits1DShiftExpSumKernel() [2/3]
GCLogits1DShiftExpSumKernel (const GCLogits1DShiftExpSumKernel &) delete
Prevent instances of this class from being copied (As this class contains pointers)
GCLogits1DShiftExpSumKernel() [3/3]
GCLogits1DShiftExpSumKernel (GCLogits1DShiftExpSumKernel &&) default
Allow instances of this class to be moved.
Member Function Documentation
configure()
void configure (const IGCTensor * input, const IGCTensor * max, IGCTensor * output, IGCTensor * sum)
Set the input and output tensors.
Parameters
[in] input Source tensor. Data types supported: F16/F32
[in] max Max values tensor. Data types supported: same as input
[out] output Destination tensor. Data types supported: same as input
[out] sum Sum of 1D logits tensor. Data types supported: same as input
Definition at line 107 of file GCSoftmaxLayerKernel.cpp.
 {
     ARM_COMPUTE_ERROR_ON_DATA_TYPE_CHANNEL_NOT_IN(input, 1, DataType::F16, DataType::F32);
     ARM_COMPUTE_ERROR_ON_NULLPTR(max, sum, output);
     // Output auto initialization if not yet initialized
     auto_init_if_empty(*sum->info(), max->info()->tensor_shape(), 1, input->info()->data_type());
     auto_init_if_empty(*output->info(), input->info()->tensor_shape(), 1, input->info()->data_type());
     ARM_COMPUTE_ERROR_ON_MISMATCHING_DATA_TYPES(input, output, max, sum);
     ARM_COMPUTE_ERROR_ON_MISMATCHING_SHAPES(input, output);
     ARM_COMPUTE_ERROR_ON_MISMATCHING_SHAPES(max, sum);
     _input  = input;
     _max    = max;
     _output = output;
     _sum    = sum;
     // Set build options
     std::set<std::string> build_opts;
     std::string           dt_name = (input->info()->data_type() == DataType::F32) ? "DATA_TYPE_FP32" : "DATA_TYPE_FP16";
     build_opts.insert("#define " + dt_name);
     build_opts.emplace("#define LOCAL_SIZE_X " + support::cpp11::to_string(1));
     build_opts.emplace("#define LOCAL_SIZE_Y " + support::cpp11::to_string(1));
     build_opts.emplace("#define LOCAL_SIZE_Z " + support::cpp11::to_string(1));
     build_opts.insert("#define SOFTMAX_LAYER_SHIFT_EXP_SUM");
     // Tell the kernel that the width is not a multiple of 8
     if((input->info()->dimension(0) % 8) != 0)
     {
         build_opts.insert("#define NON_MULTIPLE_OF_8");
     }
     // Create kernel
     _kernel = static_cast<GCKernel>(GCKernelLibrary::get().create_kernel("softmax_layer_shift_exp_sum", build_opts));
     // Set fixed arguments
     unsigned int idx = 4 * num_arguments_per_3D_tensor(); //Skip the input and output parameters
     _kernel.set_argument(idx++, input->info()->dimension(0));
     // Configure window
     // The kernel loops over all elements in steps of 8
     const unsigned int num_elems_processed_per_iteration = ceil_to_multiple(input->info()->dimension(0), 8);
     unsigned int       num_elems_written_per_iteration   = 1;
     if(input->info()->data_type() == DataType::F16)
     {
         num_elems_written_per_iteration = 2;
     }
     Window win = calculate_max_window(*input->info(), Steps(num_elems_processed_per_iteration));
     AccessWindowHorizontal input_access(input->info(), 0, num_elems_processed_per_iteration);
     AccessWindowHorizontal max_access(max->info(), 0, num_elems_written_per_iteration);
     AccessWindowHorizontal output_access(output->info(), 0, num_elems_processed_per_iteration);
     AccessWindowHorizontal sum_access(sum->info(), 0, num_elems_written_per_iteration);
     update_window_and_padding(win, input_access, max_access, output_access, sum_access);
     output_access.set_valid_region(win, input->info()->valid_region());
     sum_access.set_valid_region(win, ValidRegion(Coordinates(), sum->info()->tensor_shape()));
     IGCKernel::configure(win);
 }
References ARM_COMPUTE_ERROR_ON_DATA_TYPE_CHANNEL_NOT_IN, ARM_COMPUTE_ERROR_ON_MISMATCHING_DATA_TYPES, ARM_COMPUTE_ERROR_ON_MISMATCHING_SHAPES, ARM_COMPUTE_ERROR_ON_NULLPTR, arm_compute::auto_init_if_empty(), arm_compute::calculate_max_window(), arm_compute::ceil_to_multiple(), arm_compute::create_kernel(), ITensorInfo::data_type(), ITensorInfo::dimension(), arm_compute::F16, arm_compute::F32, GCKernelLibrary::get(), ITensor::info(), IGCKernel::num_arguments_per_3D_tensor(), sum(), ITensorInfo::tensor_shape(), arm_compute::support::cpp11::to_string(), arm_compute::update_window_and_padding(), and ITensorInfo::valid_region().
Referenced by GCSoftmaxLayer::configure().
operator=() [1/2]
GCLogits1DShiftExpSumKernel& operator= (const GCLogits1DShiftExpSumKernel &) delete
Prevent instances of this class from being copied (As this class contains pointers)
operator=() [2/2]
GCLogits1DShiftExpSumKernel& operator= (GCLogits1DShiftExpSumKernel &&) default
Allow instances of this class to be moved.
run()
void run (const Window & window) override virtual
Enqueue the OpenGL ES shader to process the given window.
Parameters
[in] window Region on which to execute the kernel. (Must be a valid region of the window returned by window()).
Implements IGCKernel.
Definition at line 171 of file GCSoftmaxLayerKernel.cpp.
 {
     ARM_COMPUTE_ERROR_ON_UNCONFIGURED_KERNEL(this);
     ARM_COMPUTE_ERROR_ON_INVALID_SUBWINDOW(IKernel::window(), window);
     Window window_collapsed = window.collapse_if_possible(IGCKernel::window(), Window::DimZ);
     Window slice            = window_collapsed.first_slice_window_3D();
     _kernel.use();
     do
     {
         unsigned int idx     = 0;
         unsigned int binding = 1; // SSBO binding starts from 1.
         // Set inputs
         add_3D_tensor_argument(idx, _input, binding++, slice);
         add_3D_tensor_argument(idx, _max, binding++, slice);
         add_3D_tensor_argument(idx, _output, binding++, slice);
         add_3D_tensor_argument(idx, _sum, binding++, slice);
         _kernel.update_shader_params();
         enqueue(*this, slice);
     }
     while(window_collapsed.slide_window_slice_3D(slice));
 }
References IGCKernel::add_3D_tensor_argument(), ARM_COMPUTE_ERROR_ON_INVALID_SUBWINDOW, ARM_COMPUTE_ERROR_ON_UNCONFIGURED_KERNEL, Window::collapse_if_possible(), Window::DimZ, arm_compute::enqueue(), Window::first_slice_window_3D(), arm_compute::test::validation::reference::slice(), Window::slide_window_slice_3D(), and IKernel::window().
The documentation for this class was generated from the following files:
arm_compute/core/GLES_COMPUTE/kernels/GCSoftmaxLayerKernel.h
src/core/GLES_COMPUTE/kernels/GCSoftmaxLayerKernel.cpp