Compute Library: TensorAccessor< T > Class Template Reference
TensorAccessor< T > Class Template Reference
Tensor accessors to make it easier to interface with arm_gemm.
#include <WindowIterator.h>
Public Member Functions
TensorAccessor (const ITensor &tensor)
Constructor:
size_t stride (size_t dim) const
Get the stride of the dimension dim expressed in number of Ts.
void set_stride (size_t dim, size_t size)
Manually set the stride of a dimension.
void set_strides (const Strides &strides)
Manually set the strides.
T * get_ptr (unsigned int x, unsigned int y=0, unsigned int z=0, unsigned int w=0)
Returns a pointer to the element at coordinates (x,y,z,w)
T * operator() (unsigned int x, unsigned int y=0, unsigned int z=0, unsigned int w=0)
Returns a pointer to the element at coordinates (x,y,z,w)
T * first_element ()
Returns a pointer to the first element of the tensor.
T * operator() ()
Returns a pointer to the first element of the tensor.
Detailed Description
template<typename T>
class arm_compute::TensorAccessor< T >
Tensor accessors to make it easier to interface with arm_gemm.
Definition at line 56 of file WindowIterator.h.
Constructor & Destructor Documentation
TensorAccessor()
TensorAccessor (const ITensor & tensor) inline
Constructor:
Parameters
[in] tensor Source tensor, must be allocated.
Definition at line 63 of file WindowIterator.h.
         : _first(tensor.ptr_to_element(Coordinates())), _strides(tensor.info()->strides_in_bytes())
     {
     }
Member Function Documentation
first_element()
T* first_element () inline
Returns a pointer to the first element of the tensor.
Returns
Pointer to the first element.
Definition at line 126 of file WindowIterator.h.
     {
         return reinterpret_cast<T *>(_first);
     }
Referenced by TensorAccessor< T >::operator()().
get_ptr()
T* get_ptr (unsigned int x, unsigned int y = 0, unsigned int z = 0, unsigned int w = 0) inline
Returns a pointer to the element at coordinates (x,y,z,w)
Parameters
[in] x X coordinates
[in] y (optional) Y coordinates
[in] z (optional) Z coordinates
[in] w (optional) W coordinates
Definition at line 105 of file WindowIterator.h.
     {
         return reinterpret_cast<T *>(_first + x * _strides[0] + y * _strides[1] + z * _strides[2] + w * _strides[3]);
     }
References arm_compute::test::validation::w.
Referenced by TensorAccessor< T >::operator()().
operator()() [1/2]
T* operator() (unsigned int x, unsigned int y = 0, unsigned int z = 0, unsigned int w = 0) inline
Returns a pointer to the element at coordinates (x,y,z,w)
Parameters
[in] x X coordinates
[in] y (optional) Y coordinates
[in] z (optional) Z coordinates
[in] w (optional) W coordinates
Definition at line 117 of file WindowIterator.h.
     {
         return get_ptr(x, y, z, w);
     }
References TensorAccessor< T >::get_ptr(), and arm_compute::test::validation::w.
operator()() [2/2]
T* operator() () inline
Returns a pointer to the first element of the tensor.
Returns
Pointer to the first element.
Definition at line 135 of file WindowIterator.h.
     {
         return first_element();
     }
References TensorAccessor< T >::first_element().
set_stride()
void set_stride (size_t dim, size_t size) inline
Manually set the stride of a dimension.
Parameters
[in] dim Dimension of the stride to set.
[in] size Value to set the stride to (in bytes).
Definition at line 84 of file WindowIterator.h.
     {
         _strides[dim] = size;
     }
set_strides()
void set_strides (const Strides & strides) inline
Manually set the strides.
Parameters
[in] strides Strides to set
Definition at line 93 of file WindowIterator.h.
     {
         _strides = strides;
     }
stride()
size_t stride (size_t dim) const inline
Get the stride of the dimension dim expressed in number of Ts.
Parameters
[in] dim Dimension of the wanted stride.
Returns
Stride in number of Ts.
Definition at line 73 of file WindowIterator.h.
     {
         ARM_COMPUTE_ERROR_ON(_strides[dim] % sizeof(T) != 0);
         return _strides[dim] / sizeof(T);
     }
References ARM_COMPUTE_ERROR_ON.
The documentation for this class was generated from the following file:
arm_compute/core/WindowIterator.h