Compute Library: NEEdgeTraceKernel Class Reference
NEEdgeTraceKernel Class Reference
NEON kernel to perform Edge tracing.
#include <NECannyEdgeKernel.h>
Public Member Functions
const char * name () const override
Name of the kernel.
NEEdgeTraceKernel ()
Default constructor.
NEEdgeTraceKernel (const NEEdgeTraceKernel &)=delete
Prevent instances of this class from being copied (As this class contains pointers)
NEEdgeTraceKernel & operator= (const NEEdgeTraceKernel &)=delete
Prevent instances of this class from being copied (As this class contains pointers)
NEEdgeTraceKernel (NEEdgeTraceKernel &&)=default
Allow instances of this class to be moved.
NEEdgeTraceKernel & operator= (NEEdgeTraceKernel &&)=default
Allow instances of this class to be moved.
~NEEdgeTraceKernel ()=default
Default constructor.
void configure (ITensor *input, ITensor *output)
Initialise the kernel's source, destination and border mode.
void run (const Window &window, const ThreadInfo &info) override
Execute the kernel on the passed window.
BorderSize border_size () const override
The size of the border for that kernel.
bool is_parallelisable () const override
Indicates whether or not the kernel is parallelisable.
Public Member Functions inherited from ICPPKernel
virtual ~ICPPKernel ()=default
Default destructor.
Public Member Functions inherited from IKernel
IKernel ()
Constructor.
virtual ~IKernel ()=default
Destructor.
const Window & window () const
The maximum window the kernel can be executed on.
Detailed Description
NEON kernel to perform Edge tracing.
Definition at line 152 of file NECannyEdgeKernel.h.
Constructor & Destructor Documentation
NEEdgeTraceKernel() [1/3]
NEEdgeTraceKernel ()
Default constructor.
Definition at line 1044 of file NECannyEdgeKernel.cpp.
     : _input(nullptr), _output(nullptr)
 {
 }
NEEdgeTraceKernel() [2/3]
NEEdgeTraceKernel (const NEEdgeTraceKernel &) delete
Prevent instances of this class from being copied (As this class contains pointers)
NEEdgeTraceKernel() [3/3]
NEEdgeTraceKernel (NEEdgeTraceKernel &&) default
Allow instances of this class to be moved.
~NEEdgeTraceKernel()
~NEEdgeTraceKernel () default
Default constructor.
Member Function Documentation
border_size()
BorderSize border_size () const override virtual
The size of the border for that kernel.
Returns
The width in number of elements of the border.
Reimplemented from IKernel.
Definition at line 1049 of file NECannyEdgeKernel.cpp.
 {
     return BorderSize(1);
 }
Referenced by NECannyEdge::configure(), and NEEdgeTraceKernel::configure().
configure()
void configure (ITensor * input, ITensor * output)
Initialise the kernel's source, destination and border mode.
Parameters
[in,out] input Source tensor. Data type supported: U8. Must contain 0 for "no edge", 127 for "maybe", 255 for "edge"
[in,out] output Destination tensor. Data type supported: U8. Must be initialized to 0 (No edge).
Definition at line 1059 of file NECannyEdgeKernel.cpp.
 {
     ARM_COMPUTE_ERROR_ON_NULLPTR(input, output);
     set_shape_if_empty(*output->info(), input->info()->tensor_shape());
     set_format_if_unknown(*input->info(), Format::U8);
     set_format_if_unknown(*output->info(), Format::U8);
     ARM_COMPUTE_ERROR_ON_MISMATCHING_SHAPES(input, output);
     ARM_COMPUTE_ERROR_ON_DATA_TYPE_CHANNEL_NOT_IN(input, 1, DataType::U8);
     ARM_COMPUTE_ERROR_ON_DATA_TYPE_CHANNEL_NOT_IN(output, 1, DataType::U8);
     ARM_COMPUTE_ERROR_ON_MISMATCHING_DATA_TYPES(input, output);
     _input  = input;
     _output = output;
     constexpr unsigned int num_elems_processed_per_iteration = 1;
     // Configure kernel window
     Window win = calculate_max_window(*_input->info(), Steps(num_elems_processed_per_iteration));
     const ValidRegion &input_valid_region  = input->info()->valid_region();
     const ValidRegion &output_valid_region = output->info()->valid_region();
     // Reads can occur within the valid region of the input + border
     AccessWindowStatic input_access(input->info(),
                                     input_valid_region.anchor[0] - border_size().left,
                                     input_valid_region.anchor[1] - border_size().top,
                                     input_valid_region.anchor[0] + input_valid_region.shape[0] + border_size().right,
                                     input_valid_region.anchor[1] + input_valid_region.shape[1] + border_size().bottom);
     // Writes can occur within the valid region of the output + border
     AccessWindowStatic output_access(output->info(),
                                      output_valid_region.anchor[0] - border_size().left,
                                      output_valid_region.anchor[1] - border_size().top,
                                      output_valid_region.anchor[0] + output_valid_region.shape[0] + border_size().right,
                                      output_valid_region.anchor[1] + output_valid_region.shape[1] + border_size().bottom);
     update_window_and_padding(win, input_access, output_access);
     output_access.set_valid_region(win, _input->info()->valid_region());
     INEKernel::configure(win);
 }
References ValidRegion::anchor, ARM_COMPUTE_ERROR_ON_DATA_TYPE_CHANNEL_NOT_IN, ARM_COMPUTE_ERROR_ON_MISMATCHING_DATA_TYPES, ARM_COMPUTE_ERROR_ON_MISMATCHING_SHAPES, ARM_COMPUTE_ERROR_ON_NULLPTR, NEEdgeTraceKernel::border_size(), BorderSize::bottom, arm_compute::calculate_max_window(), ITensor::info(), BorderSize::left, BorderSize::right, arm_compute::set_format_if_unknown(), arm_compute::set_shape_if_empty(), ValidRegion::shape, ITensorInfo::tensor_shape(), BorderSize::top, arm_compute::U8, arm_compute::update_window_and_padding(), and ITensorInfo::valid_region().
Referenced by NECannyEdge::configure().
is_parallelisable()
bool is_parallelisable () const override virtual
Indicates whether or not the kernel is parallelisable.
If the kernel is parallelisable then the window returned by window() can be split into sub-windows which can then be run in parallel.
If the kernel is not parallelisable then only the window returned by window() can be passed to run()
Returns
True if the kernel is parallelisable
Reimplemented from IKernel.
Definition at line 1054 of file NECannyEdgeKernel.cpp.
 {
     return false;
 }
name()
const char* name () const inline override virtual
Name of the kernel.
Returns
Kernel name
Implements ICPPKernel.
Definition at line 155 of file NECannyEdgeKernel.h.
     {
         return "NEEdgeTraceKernel";
     }
operator=() [1/2]
NEEdgeTraceKernel& operator= (const NEEdgeTraceKernel &) delete
Prevent instances of this class from being copied (As this class contains pointers)
operator=() [2/2]
NEEdgeTraceKernel& operator= (NEEdgeTraceKernel &&) default
Allow instances of this class to be moved.
run()
void run (const Window & window, const ThreadInfo & info) override virtual
Execute the kernel on the passed window.
Warning
If is_parallelisable() returns false then the passed window must be equal to window()
Note
The window has to be a region within the window returned by the window() method
The width of the window has to be a multiple of num_elems_processed_per_iteration().
Parameters
[in] window Region on which to execute the kernel. (Must be a region of the window returned by window())
[in] info Info about executing thread and CPU.
Implements ICPPKernel.
Definition at line 1105 of file NECannyEdgeKernel.cpp.
 {
     ARM_COMPUTE_UNUSED(info);
     ARM_COMPUTE_ERROR_ON_UNCONFIGURED_KERNEL(this);
     ARM_COMPUTE_ERROR_ON_INVALID_SUBWINDOW(INEKernel::window(), window);
     Iterator input(_input, window);
     Iterator output(_output, window);
     const size_t input_stride  = _input->info()->strides_in_bytes()[1];
     const size_t output_stride = _output->info()->strides_in_bytes()[1];
     execute_window_loop(window, [&](const Coordinates &)
     {
         edge_trace_U8_U8(input.ptr(), output.ptr(), input_stride, output_stride);
     },
     input, output);
 }
References ARM_COMPUTE_ERROR_ON_INVALID_SUBWINDOW, ARM_COMPUTE_ERROR_ON_UNCONFIGURED_KERNEL, ARM_COMPUTE_UNUSED, arm_compute::execute_window_loop(), ITensor::info(), arm_compute::test::validation::info, Iterator::ptr(), ITensorInfo::strides_in_bytes(), and IKernel::window().
The documentation for this class was generated from the following files:
arm_compute/core/NEON/kernels/NECannyEdgeKernel.h
src/core/NEON/kernels/NECannyEdgeKernel.cpp