Compute Library: Lut Class Reference
Lut Class Reference
Basic implementation of the LUT interface.
#include <Lut.h>
Public Member Functions
Lut ()
Constructor.
Lut (size_t num_elements, DataType data_type)
Constructor: initializes a LUT which can contain num_values values of data_type type.
ILutAllocator * allocator ()
Return a pointer to the lut's allocator.
size_t num_elements () const override
Returns the total number of elements in the LUT.
uint32_t index_offset () const override
Indicates the offset that needs to be applied to the raw index before performing a lookup in the LUT.
size_t size_in_bytes () const override
Returns the total size in bytes of the LUT.
DataType type () const override
Returns the type of the LUT.
uint8_t * buffer () const override
Returns a pointer to the start of the LUT.
void clear () override
Clears the LUT by setting every element to zero.
Public Member Functions inherited from ILut
virtual ~ILut ()=default
Default virtual destructor.
Detailed Description
Basic implementation of the LUT interface.
Definition at line 39 of file Lut.h.
Constructor & Destructor Documentation
Lut() [1/2]
Lut ()
Constructor.
Definition at line 30 of file Lut.cpp.
     : _allocator()
 {
 }
Lut() [2/2]
Lut (size_t num_elements, DataType data_type)
Constructor: initializes a LUT which can contain num_values values of data_type type.
Parameters
[in] num_elements Number of elements of the LUT.
[in] data_type Data type of each element.
Definition at line 35 of file Lut.cpp.
     : _allocator()
 {
     _allocator.init(num_elements, data_type);
 }
References arm_compute::test::validation::data_type, ILutAllocator::init(), and Lut::num_elements().
Member Function Documentation
allocator()
ILutAllocator * allocator ()
Return a pointer to the lut's allocator.
Returns
A pointer to the lut's allocator
Definition at line 72 of file Lut.cpp.
 {
     return &_allocator;
 }
buffer()
uint8_t * buffer () const override virtual
Returns a pointer to the start of the LUT.
Other elements of the LUT can be accessed using buffer()[idx] for 0 <= idx < num_elements().
Returns
Pointer to the start of the lut.
Implements ILut.
Definition at line 61 of file Lut.cpp.
 {
     return _allocator.data();
 }
References LutAllocator::data().
Referenced by Lut::clear().
clear()
void clear () override virtual
Clears the LUT by setting every element to zero.
Implements ILut.
Definition at line 66 of file Lut.cpp.
 {
     ARM_COMPUTE_ERROR_ON(this->buffer() == nullptr);
     std::memset(this->buffer(), 0, this->size_in_bytes());
 }
References ARM_COMPUTE_ERROR_ON, Lut::buffer(), and Lut::size_in_bytes().
index_offset()
uint32_t index_offset () const override virtual
Indicates the offset that needs to be applied to the raw index before performing a lookup in the LUT.
Returns
The normalization offset.
Implements ILut.
Definition at line 46 of file Lut.cpp.
 {
     return (DataType::S16 == _allocator.type()) ? num_elements() / 2 : 0;
 }
References Lut::num_elements(), arm_compute::S16, and ILutAllocator::type().
num_elements()
size_t num_elements () const override virtual
Returns the total number of elements in the LUT.
Returns
Total number of elements.
Implements ILut.
Definition at line 41 of file Lut.cpp.
 {
     return _allocator.num_elements();
 }
References ILutAllocator::num_elements().
Referenced by Lut::index_offset(), and Lut::Lut().
size_in_bytes()
size_t size_in_bytes () const override virtual
Returns the total size in bytes of the LUT.
Returns
Total size of the LUT in bytes.
Implements ILut.
Definition at line 51 of file Lut.cpp.
 {
     return _allocator.size();
 }
References ILutAllocator::size().
Referenced by Lut::clear().
type()
DataType type () const override virtual
Returns the type of the LUT.
Returns
The type of the LUT.
Implements ILut.
Definition at line 56 of file Lut.cpp.
 {
     return _allocator.type();
 }
References ILutAllocator::type().
The documentation for this class was generated from the following files:
arm_compute/runtime/Lut.h
src/runtime/Lut.cpp