Compute Library: GCLogits1DNormKernel Class Reference
GCLogits1DNormKernel Class Reference
Interface for calculating the final step of the Softmax Layer where each logit value is multiplied by the inverse of the sum of the logits.
#include <GCSoftmaxLayerKernel.h>
Public Member Functions
GCLogits1DNormKernel ()
Default constructor.
GCLogits1DNormKernel (const GCLogits1DNormKernel &)=delete
Prevent instances of this class from being copied (As this class contains pointers)
GCLogits1DNormKernel & operator= (const GCLogits1DNormKernel &)=delete
Prevent instances of this class from being copied (As this class contains pointers)
GCLogits1DNormKernel (GCLogits1DNormKernel &&)=default
Allow instances of this class to be moved.
GCLogits1DNormKernel & operator= (GCLogits1DNormKernel &&)=default
Allow instances of this class to be moved.
void configure (const IGCTensor *input, const IGCTensor *sum, IGCTensor *output)
Set the input and output tensors.
void run (const Window &window) override
Enqueue the OpenGL ES shader to process the given window.
Public Member Functions inherited from IGCKernel
IGCKernel ()
Constructor.
GCKernel & kernel ()
Returns a reference to the GLES kernel of this object.
void add_1D_tensor_argument (unsigned int &idx, const IGCTensor *tensor, const unsigned int binding_point, const Window &window)
Add the passed 1D tensor's parameters to the object's kernel's arguments starting from the index idx.
void add_2D_tensor_argument (unsigned int &idx, const IGCTensor *tensor, const unsigned int binding_point, const Window &window)
Add the passed 2D tensor's parameters to the object's kernel's arguments starting from the index idx.
void add_3D_tensor_argument (unsigned int &idx, const IGCTensor *tensor, const unsigned int binding_point, const Window &window)
Add the passed 3D tensor's parameters to the object's kernel's arguments starting from the index idx.
unsigned int num_arguments_per_1D_tensor () const
Returns the number of arguments enqueued per 1D tensor object.
unsigned int num_arguments_per_2D_tensor () const
Returns the number of arguments enqueued per 2D tensor object.
unsigned int num_arguments_per_3D_tensor () const
Returns the number of arguments enqueued per 3D tensor object.
void set_lws_hint (gles::NDRange &lws_hint)
Set the Local-Workgroup-Size hint.
void set_target (GPUTarget target)
Set the targeted GPU architecture.
GPUTarget get_target () const
Get the targeted GPU architecture.
Public Member Functions inherited from IKernel
IKernel ()
Constructor.
virtual ~IKernel ()=default
Destructor.
virtual bool is_parallelisable () const
Indicates whether or not the kernel is parallelisable.
virtual BorderSize border_size () const
The size of the border for that kernel.
const Window & window () const
The maximum window the kernel can be executed on.
Detailed Description
Interface for calculating the final step of the Softmax Layer where each logit value is multiplied by the inverse of the sum of the logits.
Definition at line 79 of file GCSoftmaxLayerKernel.h.
Constructor & Destructor Documentation
GCLogits1DNormKernel() [1/3]
GCLogits1DNormKernel ()
Default constructor.
Definition at line 196 of file GCSoftmaxLayerKernel.cpp.
     : _input(nullptr), _sum(nullptr), _output(nullptr)
 {
 }
GCLogits1DNormKernel() [2/3]
GCLogits1DNormKernel (const GCLogits1DNormKernel &) delete
Prevent instances of this class from being copied (As this class contains pointers)
GCLogits1DNormKernel() [3/3]
GCLogits1DNormKernel (GCLogits1DNormKernel &&) default
Allow instances of this class to be moved.
Member Function Documentation
configure()
void configure (const IGCTensor * input, const IGCTensor * sum, IGCTensor * output)
Set the input and output tensors.
Parameters
[in] input Source tensor. Data types supported: F16/F32
[in] sum Sum tensor. Dimensions should be dim(input)-1. Data types supported: same as input
[out] output Destination tensor. Data types supported: same as input
Definition at line 201 of file GCSoftmaxLayerKernel.cpp.
 {
     ARM_COMPUTE_ERROR_ON_DATA_TYPE_CHANNEL_NOT_IN(input, 1, DataType::F16, DataType::F32);
     ARM_COMPUTE_ERROR_ON_NULLPTR(sum, output);
     // Output auto initialization if not yet initialized
     auto_init_if_empty(*output->info(), input->info()->tensor_shape(), 1, input->info()->data_type());
     ARM_COMPUTE_ERROR_ON_MISMATCHING_DATA_TYPES(input, sum, output);
     ARM_COMPUTE_ERROR_ON_MISMATCHING_SHAPES(input, output);
     _input  = input;
     _sum    = sum;
     _output = output;
     // Set build options
     std::set<std::string> build_opts;
     std::string           dt_name = (input->info()->data_type() == DataType::F32) ? "DATA_TYPE_FP32" : "DATA_TYPE_FP16";
     build_opts.insert("#define " + dt_name);
     build_opts.emplace("#define LOCAL_SIZE_X " + support::cpp11::to_string(1));
     build_opts.emplace("#define LOCAL_SIZE_Y " + support::cpp11::to_string(1));
     build_opts.emplace("#define LOCAL_SIZE_Z " + support::cpp11::to_string(1));
     build_opts.insert("#define SOFTMAX_LAYER_NORM");
     // Create kernel
     _kernel = static_cast<GCKernel>(GCKernelLibrary::get().create_kernel("softmax_layer_norm", build_opts));
     // Configure window
     constexpr unsigned int num_elems_processed_per_iteration = 8;
     unsigned int           num_elems_written_per_iteration   = 1;
     if(input->info()->data_type() == DataType::F16)
     {
         num_elems_written_per_iteration = 2;
     }
     Window win = calculate_max_window(*input->info(), Steps(num_elems_processed_per_iteration));
     AccessWindowHorizontal input_access(input->info(), 0, num_elems_processed_per_iteration);
     AccessWindowStatic     sum_access(sum->info(), 0, 0, num_elems_written_per_iteration, sum->info()->dimension(1));
     AccessWindowHorizontal output_access(output->info(), 0, num_elems_processed_per_iteration);
     update_window_and_padding(win, input_access, sum_access, output_access);
     output_access.set_valid_region(win, input->info()->valid_region());
     IGCKernel::configure(win);
 }
References ARM_COMPUTE_ERROR_ON_DATA_TYPE_CHANNEL_NOT_IN, ARM_COMPUTE_ERROR_ON_MISMATCHING_DATA_TYPES, ARM_COMPUTE_ERROR_ON_MISMATCHING_SHAPES, ARM_COMPUTE_ERROR_ON_NULLPTR, arm_compute::auto_init_if_empty(), arm_compute::calculate_max_window(), arm_compute::create_kernel(), ITensorInfo::data_type(), arm_compute::F16, arm_compute::F32, GCKernelLibrary::get(), ITensor::info(), sum(), ITensorInfo::tensor_shape(), arm_compute::support::cpp11::to_string(), arm_compute::update_window_and_padding(), and ITensorInfo::valid_region().
Referenced by GCSoftmaxLayer::configure().
operator=() [1/2]
GCLogits1DNormKernel& operator= (const GCLogits1DNormKernel &) delete
Prevent instances of this class from being copied (As this class contains pointers)
operator=() [2/2]
GCLogits1DNormKernel& operator= (GCLogits1DNormKernel &&) default
Allow instances of this class to be moved.
run()
void run (const Window & window) override virtual
Enqueue the OpenGL ES shader to process the given window.
Parameters
[in] window Region on which to execute the kernel. (Must be a valid region of the window returned by window()).
Implements IGCKernel.
Definition at line 249 of file GCSoftmaxLayerKernel.cpp.
 {
     ARM_COMPUTE_ERROR_ON_UNCONFIGURED_KERNEL(this);
     ARM_COMPUTE_ERROR_ON_INVALID_SUBWINDOW(IKernel::window(), window);
     Window window_collapsed = window.collapse_if_possible(IGCKernel::window(), Window::DimZ);
     Window slice            = window_collapsed.first_slice_window_3D();
     _kernel.use();
     do
     {
         Window sum_slice = slice;
         sum_slice.set(Window::DimX, Window::Dimension(0, 1, 1));
         unsigned int idx     = 0;
         unsigned int binding = 1; // SSBO binding starts from 1.
         // Set inputs
         add_3D_tensor_argument(idx, _input, binding++, slice);
         add_3D_tensor_argument(idx, _sum, binding++, slice);
         add_3D_tensor_argument(idx, _output, binding++, slice);
         _kernel.update_shader_params();
         enqueue(*this, slice);
     }
     while(window_collapsed.slide_window_slice_3D(slice));
 }
References IGCKernel::add_3D_tensor_argument(), ARM_COMPUTE_ERROR_ON_INVALID_SUBWINDOW, ARM_COMPUTE_ERROR_ON_UNCONFIGURED_KERNEL, Window::collapse_if_possible(), Window::DimX, Window::DimZ, arm_compute::enqueue(), Window::first_slice_window_3D(), Window::set(), arm_compute::test::validation::reference::slice(), Window::slide_window_slice_3D(), and IKernel::window().
The documentation for this class was generated from the following files:
arm_compute/core/GLES_COMPUTE/kernels/GCSoftmaxLayerKernel.h
src/core/GLES_COMPUTE/kernels/GCSoftmaxLayerKernel.cpp