Compute Library: NEFuseBatchNormalizationKernel Class Reference
NEFuseBatchNormalizationKernel Class Reference
OpenNE kernel to fuse the batch normalization node to a preceding convolution node.
#include <NEFuseBatchNormalizationKernel.h>
Public Member Functions
const char * name () const override
Name of the kernel.
NEFuseBatchNormalizationKernel ()
Default constructor.
NEFuseBatchNormalizationKernel (const NEFuseBatchNormalizationKernel &)=delete
Prevent instances of this class from being copied (As this class contains pointers)
NEFuseBatchNormalizationKernel & operator= (const NEFuseBatchNormalizationKernel &)=delete
Prevent instances of this class from being copied (As this class contains pointers)
NEFuseBatchNormalizationKernel (NEFuseBatchNormalizationKernel &&)=default
Allow instances of this class to be moved.
NEFuseBatchNormalizationKernel & operator= (NEFuseBatchNormalizationKernel &&)=default
Allow instances of this class to be moved.
~NEFuseBatchNormalizationKernel ()=default
Default destructor.
void configure (const ITensor *input_weights, const ITensor *bn_mean, const ITensor *bn_var, ITensor *fused_weights, ITensor *fused_bias, const ITensor *input_bias=nullptr, const ITensor *bn_beta=nullptr, const ITensor *bn_gamma=nullptr, float epsilon=0.001f, FuseBatchNormalizationType fbn_type=FuseBatchNormalizationType::CONVOLUTION)
Set the source, destination of the kernel.
void run (const Window &window, const ThreadInfo &info) override
Execute the kernel on the passed window.
Public Member Functions inherited from ICPPKernel
virtual ~ICPPKernel ()=default
Default destructor.
Public Member Functions inherited from IKernel
IKernel ()
Constructor.
virtual ~IKernel ()=default
Destructor.
virtual bool is_parallelisable () const
Indicates whether or not the kernel is parallelisable.
virtual BorderSize border_size () const
The size of the border for that kernel.
const Window & window () const
The maximum window the kernel can be executed on.
Static Public Member Functions
static Status validate (const ITensorInfo *input_weights, const ITensorInfo *bn_mean, const ITensorInfo *bn_var, const ITensorInfo *fused_weights, const ITensorInfo *fused_bias, const ITensorInfo *input_bias=nullptr, const ITensorInfo *bn_beta=nullptr, const ITensorInfo *bn_gamma=nullptr, float epsilon=0.001f, FuseBatchNormalizationType fbn_type=FuseBatchNormalizationType::CONVOLUTION)
Static function to check if given info will lead to a valid configuration of NEFuseBatchNormalizationKernel.
Detailed Description
OpenNE kernel to fuse the batch normalization node to a preceding convolution node.
Definition at line 35 of file NEFuseBatchNormalizationKernel.h.
Constructor & Destructor Documentation
NEFuseBatchNormalizationKernel() [1/3]
NEFuseBatchNormalizationKernel ()
Default constructor.
Definition at line 416 of file NEFuseBatchNormalizationKernel.cpp.
     : _input_weights(nullptr), _input_bias(nullptr), _bn_mean(nullptr), _bn_var(nullptr), _bn_gamma(nullptr), _bn_beta(nullptr), _fused_weights(nullptr), _fused_bias(nullptr), _epsilon(),
       _run_in_place_weights(false), _run_in_place_bias(false), _func(nullptr)
 {
 }
NEFuseBatchNormalizationKernel() [2/3]
NEFuseBatchNormalizationKernel (const NEFuseBatchNormalizationKernel &) delete
Prevent instances of this class from being copied (As this class contains pointers)
NEFuseBatchNormalizationKernel() [3/3]
NEFuseBatchNormalizationKernel (NEFuseBatchNormalizationKernel &&) default
Allow instances of this class to be moved.
~NEFuseBatchNormalizationKernel()
~NEFuseBatchNormalizationKernel () default
Default destructor.
Member Function Documentation
configure()
void configure (const ITensor * input_weights, const ITensor * bn_mean, const ITensor * bn_var, ITensor * fused_weights, ITensor * fused_bias, const ITensor * input_bias = nullptr, const ITensor * bn_beta = nullptr, const ITensor * bn_gamma = nullptr, float epsilon = 0.001f, FuseBatchNormalizationType fbn_type = FuseBatchNormalizationType::CONVOLUTION)
Set the source, destination of the kernel.
Parameters
[in] input_weights Input weights tensor for convolution or depthwise convolution layer. Data type supported: F16/F32. Data layout supported: NCHW, NHWC
[in] bn_mean Batch normalization layer mean tensor. Same as input_weights
[in] bn_var Batch normalization layer variance tensor. Same as input_weights
[out] fused_weights (Optional) Output fused weights tensor. It can be a nullptr in case of in-place computation. Same as input_weights
[out] fused_bias (Optional) Output fused bias tensor. It can be a nullptr in case of in-place computation and input_bias != nullptr. Same as input_weights
[in] input_bias (Optional) Input bias tensor for convolution or depthwise convolution layer. It can be a nullptr in case the bias tensor is not required. Same as input_weights
[in] bn_beta (Optional) Batch normalization layer beta tensor. It can be a nullptr in case the beta tensor is not required. Same as input_weights
Note
if nullptr, bn_beta is set to 0.0
Parameters
[in] bn_gamma (Optional) Batch normalization layer gamma tensor. It can be a nullptr in case the gamma tensor is not required. Same as input_weights
Note
if nullptr, bn_gamma is set to 1.0
Parameters
[in] epsilon (Optional) Batch normalization layer epsilon parameter. Defaults to 0.001f.
[in] fbn_type (Optional) Fused batch normalization type. Defaults to CONVOLUTION.
Definition at line 422 of file NEFuseBatchNormalizationKernel.cpp.
 {
     ARM_COMPUTE_ERROR_ON_NULLPTR(input_weights, bn_mean, bn_var);
     _input_weights = input_weights;
     _input_bias    = input_bias;
     _bn_mean       = bn_mean;
     _bn_var        = bn_var;
     _bn_beta       = bn_beta;
     _bn_gamma      = bn_gamma;
     _fused_weights = fused_weights;
     _fused_bias    = fused_bias;
     _epsilon       = epsilon;
     _run_in_place_weights = (fused_weights == nullptr) || (fused_weights == input_weights);
     _run_in_place_bias    = (fused_bias == nullptr) || (input_bias != nullptr && fused_bias == input_bias);
     // Auto initialize outputs
     if(_fused_weights != nullptr)
     {
         // Output tensor auto initialization if not yet initialized
         auto_init_if_empty(*_fused_weights->info(), *_input_weights->info()->clone());
         fused_weights->info()->set_valid_region(input_weights->info()->valid_region());
     }
     if(_fused_bias != nullptr)
     {
         // Output tensor auto initialization if not yet initialized
         auto_init_if_empty(*_fused_bias->info(), *_bn_mean->info()->clone());
         _fused_bias->info()->set_valid_region(bn_mean->info()->valid_region());
     }
     // Validate arguments
     ARM_COMPUTE_ERROR_THROW_ON(validate_arguments(input_weights->info(), bn_mean->info(), bn_var->info(),
                                                   (fused_weights != nullptr) ? fused_weights->info() : nullptr,
                                                   (fused_bias != nullptr) ? fused_bias->info() : nullptr,
                                                   (input_bias != nullptr) ? input_bias->info() : nullptr,
                                                   (bn_beta != nullptr) ? bn_beta->info() : nullptr,
                                                   (bn_gamma != nullptr) ? bn_gamma->info() : nullptr,
                                                   epsilon, fbn_type));
     // Configure kernel window
     Window win = calculate_max_window(*input_weights->info());
     INEKernel::configure(win);
     // Configure function
     static std::map<std::string, FuseBatchNormFunction *> map_function =
     {
         { "fused_batch_normalization_conv_NHWC_F32", &fused_batch_normalization_conv<wrapper::traits::neon_vector<float, 4>> },
         { "fused_batch_normalization_conv_NCHW_F32", &fused_batch_normalization_conv<wrapper::traits::neon_vector<float, 4>> },
         { "fused_batch_normalization_dwc_NHWC_F32", &fused_batch_normalization_dwc_nhwc<wrapper::traits::neon_vector<float, 4>> },
         { "fused_batch_normalization_dwc_NCHW_F32", &fused_batch_normalization_dwc_nchw<wrapper::traits::neon_vector<float, 4>> },
 #ifdef __ARM_FEATURE_FP16_VECTOR_ARITHMETIC
         { "fused_batch_normalization_conv_NHWC_F16", &fused_batch_normalization_conv<wrapper::traits::neon_vector<float16_t, 8>> },
         { "fused_batch_normalization_conv_NCHW_F16", &fused_batch_normalization_conv<wrapper::traits::neon_vector<float16_t, 8>> },
         { "fused_batch_normalization_dwc_NHWC_F16", &fused_batch_normalization_dwc_nhwc<wrapper::traits::neon_vector<float16_t, 8>> },
         { "fused_batch_normalization_dwc_NCHW_F16", &fused_batch_normalization_dwc_nchw<wrapper::traits::neon_vector<float16_t, 8>> },
 #endif /* __ARM_FEATURE_FP16_VECTOR_ARITHMETIC */
     };
     std::string function_to_call("fused_batch_normalization_");
     function_to_call += fbn_type == FuseBatchNormalizationType::CONVOLUTION ? "conv_" : "dwc_";
     function_to_call += string_from_data_layout(_input_weights->info()->data_layout());
     function_to_call += "_";
     function_to_call += string_from_data_type(_input_weights->info()->data_type());
     auto it = map_function.find(function_to_call);
     if(it != map_function.end())
     {
         _func = it->second;
     }
 }
References ARM_COMPUTE_ERROR_ON_NULLPTR, ARM_COMPUTE_ERROR_THROW_ON, arm_compute::auto_init_if_empty(), arm_compute::calculate_max_window(), ICloneable< T >::clone(), arm_compute::CONVOLUTION, ITensorInfo::data_layout(), ITensorInfo::data_type(), epsilon, ITensor::info(), ITensorInfo::set_valid_region(), arm_compute::string_from_data_layout(), arm_compute::string_from_data_type(), and ITensorInfo::valid_region().
Referenced by NEFuseBatchNormalization::configure().
name()
const char* name () const inline override virtual
Name of the kernel.
Returns
Kernel name
Implements ICPPKernel.
Definition at line 38 of file NEFuseBatchNormalizationKernel.h.
     {
         return "NEFuseBatchNormalizationKernel";
     }
operator=() [1/2]
NEFuseBatchNormalizationKernel& operator= (const NEFuseBatchNormalizationKernel &) delete
Prevent instances of this class from being copied (As this class contains pointers)
operator=() [2/2]
NEFuseBatchNormalizationKernel& operator= (NEFuseBatchNormalizationKernel &&) default
Allow instances of this class to be moved.
run()
void run (const Window & window, const ThreadInfo & info) override virtual
Execute the kernel on the passed window.
Warning
If is_parallelisable() returns false then the passed window must be equal to window()
Note
The window has to be a region within the window returned by the window() method
The width of the window has to be a multiple of num_elems_processed_per_iteration().
Parameters
[in] window Region on which to execute the kernel. (Must be a region of the window returned by window())
[in] info Info about executing thread and CPU.
Implements ICPPKernel.
Definition at line 507 of file NEFuseBatchNormalizationKernel.cpp.
 {
     ARM_COMPUTE_UNUSED(info);
     ARM_COMPUTE_ERROR_ON_UNCONFIGURED_KERNEL(this);
     ARM_COMPUTE_ERROR_ON_INVALID_SUBWINDOW(IKernel::window(), window);
     (*_func)(_input_weights, _input_bias, _fused_weights, _fused_bias, _bn_mean, _bn_var, _bn_beta, _bn_gamma, _epsilon, window);
 }
References ARM_COMPUTE_ERROR_ON_INVALID_SUBWINDOW, ARM_COMPUTE_ERROR_ON_UNCONFIGURED_KERNEL, ARM_COMPUTE_UNUSED, arm_compute::test::validation::info, and IKernel::window().
validate()
Status validate (const ITensorInfo * input_weights, const ITensorInfo * bn_mean, const ITensorInfo * bn_var, const ITensorInfo * fused_weights, const ITensorInfo * fused_bias, const ITensorInfo * input_bias = nullptr, const ITensorInfo * bn_beta = nullptr, const ITensorInfo * bn_gamma = nullptr, float epsilon = 0.001f, FuseBatchNormalizationType fbn_type = FuseBatchNormalizationType::CONVOLUTION) static
Static function to check if given info will lead to a valid configuration of NEFuseBatchNormalizationKernel.
Parameters
[in] input_weights Input weights tensor info for convolution or depthwise convolution layer. Data type supported: F16/F32. Data layout supported: NCHW, NHWC
[in] bn_mean Batch normalization layer mean tensor info. Same as input_weights
[in] bn_var Batch normalization layer variance tensor info. Same as input_weights
[in] fused_weights (Optional) Output fused weights tensor info. It can be a nullptr in case of in-place computation. Same as input_weights
[in] fused_bias (Optional) Output fused bias tensor info. It can be a nullptr in case of in-place computation and input_bias != nullptr. Same as input_weights
[in] input_bias (Optional) Input bias tensor info for convolution or depthwise convolution layer. It can be a nullptr in case the bias tensor is not required. Same as input_weights
[in] bn_beta (Optional) Batch normalization layer beta tensor info. It can be a nullptr in case the beta tensor is not required. Same as input_weights
Note
if nullptr, bn_beta is set to 0.0
Parameters
[in] bn_gamma (Optional) Batch normalization layer gamma tensor info. It can be a nullptr in case the gamma tensor is not required. Same as input_weights
Note
if nullptr, bn_gamma is set to 1.0
Parameters
[in] epsilon (Optional) Batch normalization layer epsilon parameter. Defaults to 0.001f.
[in] fbn_type (Optional) Fused batch normalization type. Defaults to CONVOLUTION.
Returns
a status
Definition at line 498 of file NEFuseBatchNormalizationKernel.cpp.
 {
     ARM_COMPUTE_RETURN_ON_ERROR(validate_arguments(input_weights, bn_mean, bn_var, fused_weights, fused_bias, input_bias, bn_beta, bn_gamma, epsilon, fbn_type));
     return Status{};
 }
References ARM_COMPUTE_RETURN_ON_ERROR, and epsilon.
Referenced by NEFuseBatchNormalization::validate().
The documentation for this class was generated from the following files:
arm_compute/core/NEON/kernels/NEFuseBatchNormalizationKernel.h
src/core/NEON/kernels/NEFuseBatchNormalizationKernel.cpp