Compute Library: GCTensorAllocator Class Reference
GCTensorAllocator Class Reference
Basic implementation of a GLES memory tensor allocator.
#include <GCTensorAllocator.h>
Public Member Functions
GCTensorAllocator (GCTensor *owner=nullptr)
Default constructor.
GCTensorAllocator (const GCTensorAllocator &)=delete
Prevent instances of this class from being copied (As this class contains pointers)
GCTensorAllocator & operator= (const GCTensorAllocator &)=delete
Prevent instances of this class from being copy assigned (As this class contains pointers)
GCTensorAllocator (GCTensorAllocator &&)=default
Allow instances of this class to be moved.
GCTensorAllocator & operator= (GCTensorAllocator &&)=default
Allow instances of this class to be moved.
~GCTensorAllocator ()=default
Default destructor.
uint8_t * data ()
Interface to be implemented by the child class to return the pointer to the mapped data.
GLuint get_gl_ssbo_name () const
Get the OpenGL ES buffer object name.
uint8_t * map (bool blocking)
Enqueue a map operation of the allocated buffer on the given queue.
void unmap ()
Enqueue an unmap operation of the allocated buffer on the given queue.
void allocate () override
Allocate size specified by TensorInfo of GLES memory.
void free () override
Free allocated GLES memory.
void set_associated_memory_group (GCMemoryGroup *associated_memory_group)
Associates the tensor with a memory group.
Public Member Functions inherited from ITensorAllocator
ITensorAllocator ()
Default constructor.
ITensorAllocator (const ITensorAllocator &)=default
Allow instances of this class to be copy constructed.
ITensorAllocator & operator= (const ITensorAllocator &)=default
Allow instances of this class to be copied.
ITensorAllocator (ITensorAllocator &&)=default
Allow instances of this class to be move constructed.
ITensorAllocator & operator= (ITensorAllocator &&)=default
Allow instances of this class to be moved.
virtual ~ITensorAllocator ()=default
Default virtual destructor.
void init (const TensorInfo &input, size_t alignment=0)
Initialize a tensor based on the passed TensorInfo.
TensorInfo & info ()
Return a reference to the tensor's metadata.
const TensorInfo & info () const
Return a constant reference to the tensor's metadata.
size_t alignment () const
Return underlying's tensor buffer alignment.
Detailed Description
Basic implementation of a GLES memory tensor allocator.
Definition at line 43 of file GCTensorAllocator.h.
Constructor & Destructor Documentation
GCTensorAllocator() [1/3]
GCTensorAllocator (GCTensor * owner = nullptr)
Default constructor.
Definition at line 35 of file GCTensorAllocator.cpp.
     : _associated_memory_group(nullptr), _memory(), _mapping(nullptr), _owner(owner)
 {
 }
GCTensorAllocator() [2/3]
GCTensorAllocator (const GCTensorAllocator &) delete
Prevent instances of this class from being copied (As this class contains pointers)
GCTensorAllocator() [3/3]
GCTensorAllocator (GCTensorAllocator &&) default
Allow instances of this class to be moved.
~GCTensorAllocator()
~GCTensorAllocator () default
Default destructor.
Member Function Documentation
allocate()
void allocate () override virtual
Allocate size specified by TensorInfo of GLES memory.
Note
: The tensor must not already be allocated when calling this function.
Implements ITensorAllocator.
Definition at line 45 of file GCTensorAllocator.cpp.
 {
     if(_associated_memory_group == nullptr)
     {
         _memory.set_owned_region(support::cpp14::make_unique<GCBufferMemoryRegion>(info().total_size()));
     }
     else
     {
         _associated_memory_group->finalize_memory(_owner, _memory, info().total_size());
     }
     info().set_is_resizable(false);
 }
References MemoryGroupBase< TensorType >::finalize_memory(), ITensorAllocator::info(), TensorInfo::set_is_resizable(), and GCMemory::set_owned_region().
data()
uint8_t * data ()
Interface to be implemented by the child class to return the pointer to the mapped data.
Returns
a pointer to the data.
Definition at line 40 of file GCTensorAllocator.cpp.
 {
     return _mapping;
 }
Referenced by GCTensor::buffer().
free()
void free () override virtual
Free allocated GLES memory.
Note
The tensor must have been allocated when calling this function.
Implements ITensorAllocator.
Definition at line 58 of file GCTensorAllocator.cpp.
 {
     _mapping = nullptr;
     _memory.set_region(nullptr);
     info().set_is_resizable(true);
 }
References ITensorAllocator::info(), TensorInfo::set_is_resizable(), and GCMemory::set_region().
get_gl_ssbo_name()
GLuint get_gl_ssbo_name () const
Get the OpenGL ES buffer object name.
Returns
The buffer object name
Definition at line 84 of file GCTensorAllocator.cpp.
 {
     return (_memory.region() == nullptr) ? static_cast<GLuint>(0) : _memory.gc_region()->gc_ssbo_name();
 }
References GCMemory::gc_region(), IGCMemoryRegion::gc_ssbo_name(), and GCMemory::region().
Referenced by GCTensor::gc_buffer().
map()
uint8_t * map (bool blocking)
Enqueue a map operation of the allocated buffer on the given queue.
Parameters
[in] blocking If true, then the mapping will be ready to use by the time this method returns, else it is the caller's responsibility to flush the queue and wait for the mapping operation to have completed before using the returned mapping pointer.
Returns
The mapping address.
Definition at line 89 of file GCTensorAllocator.cpp.
 {
     ARM_COMPUTE_ERROR_ON(_mapping != nullptr);
     ARM_COMPUTE_ERROR_ON(_memory.region() == nullptr);
     _mapping = reinterpret_cast<uint8_t *>(_memory.gc_region()->map(blocking));
     return _mapping;
 }
References ARM_COMPUTE_ERROR_ON, GCMemory::gc_region(), IGCMemoryRegion::map(), and GCMemory::region().
operator=() [1/2]
GCTensorAllocator& operator= (const GCTensorAllocator &) delete
Prevent instances of this class from being copy assigned (As this class contains pointers)
operator=() [2/2]
GCTensorAllocator& operator= (GCTensorAllocator &&) default
Allow instances of this class to be moved.
set_associated_memory_group()
void set_associated_memory_group (GCMemoryGroup * associated_memory_group)
Associates the tensor with a memory group.
Parameters
[in] associated_memory_group Memory group to associate the tensor with
Definition at line 65 of file GCTensorAllocator.cpp.
 {
     ARM_COMPUTE_ERROR_ON(associated_memory_group == nullptr);
     ARM_COMPUTE_ERROR_ON(_associated_memory_group != nullptr);
     ARM_COMPUTE_ERROR_ON(_memory.region() != nullptr && _memory.gc_region()->gc_ssbo_name() != 0);
     _associated_memory_group = associated_memory_group;
 }
References ARM_COMPUTE_ERROR_ON, GCMemory::gc_region(), IGCMemoryRegion::gc_ssbo_name(), and GCMemory::region().
unmap()
void unmap ()
Enqueue an unmap operation of the allocated buffer on the given queue.
Note
This method simply enqueue the unmap operation, it is the caller's responsibility to flush the queue and make sure the unmap is finished before the memory is accessed by the device.
Definition at line 98 of file GCTensorAllocator.cpp.
 {
     ARM_COMPUTE_ERROR_ON(_mapping == nullptr);
     ARM_COMPUTE_ERROR_ON(_memory.region() == nullptr);
     _memory.gc_region()->unmap();
     _mapping = nullptr;
 }
References ARM_COMPUTE_ERROR_ON, GCMemory::gc_region(), GCMemory::region(), and IGCMemoryRegion::unmap().
The documentation for this class was generated from the following files:
arm_compute/runtime/GLES_COMPUTE/GCTensorAllocator.h
src/runtime/GLES_COMPUTE/GCTensorAllocator.cpp