Compute Library: INESimpleFunction Class Reference
INESimpleFunction Class Reference
Basic interface for functions which have a single NEON kernel.
#include <INESimpleFunction.h>
Public Member Functions
INESimpleFunction ()
Constructor.
void run () override final
Run the kernels contained in the function.
Public Member Functions inherited from IFunction
virtual ~IFunction ()=default
Destructor.
virtual void prepare ()
Prepare the function for executing.
Detailed Description
Basic interface for functions which have a single NEON kernel.
Definition at line 36 of file INESimpleFunction.h.
Constructor & Destructor Documentation
INESimpleFunction()
INESimpleFunction ()
Constructor.
Definition at line 30 of file INESimpleFunction.cpp.
     : _kernel(),
       _border_handler()
 {
 }
Member Function Documentation
run()
void run () final override virtual
Run the kernels contained in the function.
For NEON kernels:
Multi-threading is used for the kernels which are parallelisable.
By default std::thread::hardware_concurrency() threads are used.
Note
CPPScheduler::set_num_threads() can be used to manually set the number of threads
For OpenCL kernels:
All the kernels are enqueued on the queue associated with CLScheduler.
The queue is then flushed.
Note
The function will not block until the kernels are executed. It is the user's responsibility to wait.
Will call prepare() on first run if hasn't been done
Implements IFunction.
Definition at line 36 of file INESimpleFunction.cpp.
 {
     NEScheduler::get().schedule(&_border_handler, Window::DimZ);
     NEScheduler::get().schedule(_kernel.get(), Window::DimY);
 }
References Window::DimY, Window::DimZ, Scheduler::get(), and IScheduler::schedule().
Referenced by NEHarrisCorners::run(), NEFFTConvolutionLayer::run(), NELSTMLayerQuantized::run(), and NELSTMLayer::run().
The documentation for this class was generated from the following files:
arm_compute/runtime/NEON/INESimpleFunction.h
src/runtime/NEON/INESimpleFunction.cpp