Compute Library: NENonMaximaSuppression3x3Kernel Class Reference
NENonMaximaSuppression3x3Kernel Class Reference
Interface to perform Non-Maxima suppression over a 3x3 window using NEON.
#include <NENonMaximaSuppression3x3Kernel.h>
Public Member Functions
const char * name () const override
Name of the kernel.
NENonMaximaSuppression3x3Kernel ()
Default constructor.
NENonMaximaSuppression3x3Kernel (const NENonMaximaSuppression3x3Kernel &)=delete
Prevent instances of this class from being copied (As this class contains pointers)
NENonMaximaSuppression3x3Kernel & operator= (const NENonMaximaSuppression3x3Kernel &)=delete
Prevent instances of this class from being copied (As this class contains pointers)
NENonMaximaSuppression3x3Kernel (NENonMaximaSuppression3x3Kernel &&)=default
Allow instances of this class to be moved.
NENonMaximaSuppression3x3Kernel & operator= (NENonMaximaSuppression3x3Kernel &&)=default
Allow instances of this class to be moved.
~NENonMaximaSuppression3x3Kernel ()=default
Default destructor.
void configure (const ITensor *input, ITensor *output, bool border_undefined)
Initialise the kernel's sources, destinations and border mode.
void run (const Window &window, const ThreadInfo &info) override
Execute the kernel on the passed window.
BorderSize border_size () const override
The size of the border for that kernel.
Public Member Functions inherited from ICPPKernel
virtual ~ICPPKernel ()=default
Default destructor.
Public Member Functions inherited from IKernel
IKernel ()
Constructor.
virtual ~IKernel ()=default
Destructor.
virtual bool is_parallelisable () const
Indicates whether or not the kernel is parallelisable.
const Window & window () const
The maximum window the kernel can be executed on.
Detailed Description
Interface to perform Non-Maxima suppression over a 3x3 window using NEON.
Note
Used by NEFastCorners and NEHarrisCorners
Definition at line 39 of file NENonMaximaSuppression3x3Kernel.h.
Constructor & Destructor Documentation
NENonMaximaSuppression3x3Kernel() [1/3]
NENonMaximaSuppression3x3Kernel ()
Default constructor.
Definition at line 452 of file NENonMaximaSuppression3x3Kernel.cpp.
     : _func(nullptr), _input(nullptr), _output(nullptr)
 {
 }
NENonMaximaSuppression3x3Kernel() [2/3]
NENonMaximaSuppression3x3Kernel (const NENonMaximaSuppression3x3Kernel &) delete
Prevent instances of this class from being copied (As this class contains pointers)
NENonMaximaSuppression3x3Kernel() [3/3]
NENonMaximaSuppression3x3Kernel (NENonMaximaSuppression3x3Kernel &&) default
Allow instances of this class to be moved.
~NENonMaximaSuppression3x3Kernel()
~NENonMaximaSuppression3x3Kernel () default
Default destructor.
Member Function Documentation
border_size()
BorderSize border_size () const override virtual
The size of the border for that kernel.
Returns
The width in number of elements of the border.
Reimplemented from IKernel.
Definition at line 457 of file NENonMaximaSuppression3x3Kernel.cpp.
 {
     return BorderSize(1);
 }
Referenced by NENonMaximaSuppression3x3Kernel::configure().
configure()
void configure (const ITensor * input, ITensor * output, bool border_undefined)
Initialise the kernel's sources, destinations and border mode.
Parameters
[in] input Source tensor. Data types supported: U8/F32
[out] output Destination tensor. Data types supported: same as input
[in] border_undefined True if the border mode is undefined. False if it's replicate or constant.
Definition at line 462 of file NENonMaximaSuppression3x3Kernel.cpp.
 {
     ARM_COMPUTE_ERROR_ON_DATA_TYPE_CHANNEL_NOT_IN(input, 1, DataType::U8, DataType::F32);
     ARM_COMPUTE_ERROR_ON_DATA_TYPE_CHANNEL_NOT_IN(output, 1, DataType::U8, DataType::F32);
     ARM_COMPUTE_ERROR_ON_MISMATCHING_DATA_TYPES(input, output);
     _input  = input;
     _output = output;
     if(input->info()->data_type() == DataType::U8)
     {
         _func = &non_maxima_suppression3x3_U8_U8;
     }
     else
     {
         _func = &non_maxima_suppression3x3_FLOAT_FLOAT;
     }
     constexpr unsigned int num_elems_processed_per_iteration = 16;
     const unsigned int     num_elems_read_per_iteration      = 16 + 2 * border_size().left + (input->info()->data_type() == DataType::U8 ? 0 : 3);
     constexpr unsigned int num_elems_written_per_iteration   = 16;
     constexpr unsigned int num_rows_read_per_iteration       = 3;
     // Configure kernel window
     Window                 win = calculate_max_window(*input->info(), Steps(num_elems_processed_per_iteration), border_undefined, border_size());
     AccessWindowHorizontal output_access(output->info(), 0, num_elems_written_per_iteration);
     update_window_and_padding(win,
                               AccessWindowRectangle(input->info(), -border_size().left, -border_size().top, num_elems_read_per_iteration, num_rows_read_per_iteration),
                               output_access);
     output_access.set_valid_region(win, input->info()->valid_region(), border_undefined, border_size());
     INEKernel::configure(win);
 }
References ARM_COMPUTE_ERROR_ON_DATA_TYPE_CHANNEL_NOT_IN, ARM_COMPUTE_ERROR_ON_MISMATCHING_DATA_TYPES, NENonMaximaSuppression3x3Kernel::border_size(), arm_compute::calculate_max_window(), ITensorInfo::data_type(), arm_compute::F32, ITensor::info(), BorderSize::left, BorderSize::top, arm_compute::U8, arm_compute::update_window_and_padding(), and ITensorInfo::valid_region().
Referenced by NEFastCorners::configure().
name()
const char* name () const inline override virtual
Name of the kernel.
Returns
Kernel name
Implements ICPPKernel.
Definition at line 42 of file NENonMaximaSuppression3x3Kernel.h.
     {
         return "NENonMaximaSuppression3x3Kernel";
     }
operator=() [1/2]
NENonMaximaSuppression3x3Kernel& operator= (const NENonMaximaSuppression3x3Kernel &) delete
Prevent instances of this class from being copied (As this class contains pointers)
operator=() [2/2]
NENonMaximaSuppression3x3Kernel& operator= (NENonMaximaSuppression3x3Kernel &&) default
Allow instances of this class to be moved.
run()
void run (const Window & window, const ThreadInfo & info) override virtual
Execute the kernel on the passed window.
Warning
If is_parallelisable() returns false then the passed window must be equal to window()
Note
The window has to be a region within the window returned by the window() method
The width of the window has to be a multiple of num_elems_processed_per_iteration().
Parameters
[in] window Region on which to execute the kernel. (Must be a region of the window returned by window())
[in] info Info about executing thread and CPU.
Implements ICPPKernel.
Definition at line 498 of file NENonMaximaSuppression3x3Kernel.cpp.
 {
     ARM_COMPUTE_UNUSED(info);
     ARM_COMPUTE_ERROR_ON_UNCONFIGURED_KERNEL(this);
     ARM_COMPUTE_ERROR_ON_INVALID_SUBWINDOW(INEKernel::window(), window);
     ARM_COMPUTE_ERROR_ON(_func == nullptr);
     Iterator input(_input, window);
     Iterator output(_output, window);
     const size_t input_stride = _input->info()->strides_in_bytes()[1] / element_size_from_data_type(_input->info()->data_type());
     execute_window_loop(window, [&](const Coordinates &)
     {
         _func(input.ptr(), output.ptr(), input_stride);
     },
     input, output);
 }
References ARM_COMPUTE_ERROR_ON, ARM_COMPUTE_ERROR_ON_INVALID_SUBWINDOW, ARM_COMPUTE_ERROR_ON_UNCONFIGURED_KERNEL, ARM_COMPUTE_UNUSED, ITensorInfo::data_type(), arm_compute::element_size_from_data_type(), arm_compute::execute_window_loop(), ITensor::info(), arm_compute::test::validation::info, Iterator::ptr(), ITensorInfo::strides_in_bytes(), and IKernel::window().
The documentation for this class was generated from the following files:
arm_compute/core/NEON/kernels/NENonMaximaSuppression3x3Kernel.h
src/core/NEON/kernels/NENonMaximaSuppression3x3Kernel.cpp