Compute Library: CLLogits1DMaxShiftExpSumKernel Class Reference
CLLogits1DMaxShiftExpSumKernel Class Reference
Interface for max, shifting, exponentiating and summing the logits.
#include <CLSoftmaxLayerKernel.h>
Public Types
using ParallelReductionInfo = std::tuple< bool, unsigned int >
Info for whether a parallel reduction will be run and the vector size of the execution.
Public Member Functions
CLLogits1DMaxShiftExpSumKernel ()
Default constructor.
CLLogits1DMaxShiftExpSumKernel (const CLLogits1DMaxShiftExpSumKernel &)=delete
Prevent instances of this class from being copied (As this class contains pointers)
CLLogits1DMaxShiftExpSumKernel & operator= (const CLLogits1DMaxShiftExpSumKernel &)=delete
Prevent instances of this class from being copied (As this class contains pointers)
CLLogits1DMaxShiftExpSumKernel (CLLogits1DMaxShiftExpSumKernel &&)=default
Allow instances of this class to be moved.
CLLogits1DMaxShiftExpSumKernel & operator= (CLLogits1DMaxShiftExpSumKernel &&)=default
Allow instances of this class to be moved.
void configure (const ICLTensor *input, ICLTensor *max, ICLTensor *output, ICLTensor *sum, float beta=1.0f)
Set the input and output tensors.
void run (const Window &window, cl::CommandQueue &queue) override
Enqueue the OpenCL kernel to process the given window on the passed OpenCL command queue.
Public Member Functions inherited from ICLKernel
ICLKernel ()
Constructor.
cl::Kernel & kernel ()
Returns a reference to the OpenCL kernel of this object.
template<typename T >
void add_1D_array_argument (unsigned int &idx, const ICLArray< T > *array, const Strides &strides, unsigned int num_dimensions, const Window &window)
Add the passed 1D array's parameters to the object's kernel's arguments starting from the index idx.
void add_1D_tensor_argument (unsigned int &idx, const ICLTensor *tensor, const Window &window)
Add the passed 1D tensor's parameters to the object's kernel's arguments starting from the index idx.
void add_1D_tensor_argument_if (bool cond, unsigned int &idx, const ICLTensor *tensor, const Window &window)
Add the passed 1D tensor's parameters to the object's kernel's arguments starting from the index idx if the condition is true.
void add_2D_tensor_argument (unsigned int &idx, const ICLTensor *tensor, const Window &window)
Add the passed 2D tensor's parameters to the object's kernel's arguments starting from the index idx.
void add_2D_tensor_argument_if (bool cond, unsigned int &idx, const ICLTensor *tensor, const Window &window)
Add the passed 2D tensor's parameters to the object's kernel's arguments starting from the index idx if the condition is true.
void add_3D_tensor_argument (unsigned int &idx, const ICLTensor *tensor, const Window &window)
Add the passed 3D tensor's parameters to the object's kernel's arguments starting from the index idx.
void add_4D_tensor_argument (unsigned int &idx, const ICLTensor *tensor, const Window &window)
Add the passed 4D tensor's parameters to the object's kernel's arguments starting from the index idx.
template<typename T >
void add_argument (unsigned int &idx, T value)
Add the passed parameters to the object's kernel's arguments starting from the index idx.
void set_lws_hint (const cl::NDRange &lws_hint)
Set the Local-Workgroup-Size hint.
cl::NDRange lws_hint () const
Return the Local-Workgroup-Size hint.
const std::string & config_id () const
Get the configuration ID.
void set_target (GPUTarget target)
Set the targeted GPU architecture.
void set_target (cl::Device &device)
Set the targeted GPU architecture according to the CL device.
GPUTarget get_target () const
Get the targeted GPU architecture.
size_t get_max_workgroup_size ()
Get the maximum workgroup size for the device the CLKernelLibrary uses.
template<typename T , unsigned int dimension_size>
void add_array_argument (unsigned &idx, const ICLArray< T > *array, const Strides &strides, unsigned int num_dimensions, const Window &window)
Add the passed array's parameters to the object's kernel's arguments starting from the index idx.
template<unsigned int dimension_size>
void add_tensor_argument (unsigned &idx, const ICLTensor *tensor, const Window &window)
Public Member Functions inherited from IKernel
IKernel ()
Constructor.
virtual ~IKernel ()=default
Destructor.
virtual bool is_parallelisable () const
Indicates whether or not the kernel is parallelisable.
virtual BorderSize border_size () const
The size of the border for that kernel.
const Window & window () const
The maximum window the kernel can be executed on.
Static Public Member Functions
static Status validate (const ITensorInfo *input, const ITensorInfo *max, const ITensorInfo *output, const ITensorInfo *sum)
Static function to check if given info will lead to a valid configuration of CLLogits1DMaxShiftExpSumKernel.
static ParallelReductionInfo is_parallel_reduction (size_t size)
Checks if the given size is eligible for parallel reduction.
Static Public Member Functions inherited from ICLKernel
static constexpr unsigned int num_arguments_per_1D_array ()
Returns the number of arguments enqueued per 1D array object.
static constexpr unsigned int num_arguments_per_1D_tensor ()
Returns the number of arguments enqueued per 1D tensor object.
static constexpr unsigned int num_arguments_per_2D_tensor ()
Returns the number of arguments enqueued per 2D tensor object.
static constexpr unsigned int num_arguments_per_3D_tensor ()
Returns the number of arguments enqueued per 3D tensor object.
static constexpr unsigned int num_arguments_per_4D_tensor ()
Returns the number of arguments enqueued per 4D tensor object.
static cl::NDRange gws_from_window (const Window &window)
Get the global work size given an execution window.
Detailed Description
Interface for max, shifting, exponentiating and summing the logits.
Definition at line 100 of file CLSoftmaxLayerKernel.h.
Member Typedef Documentation
ParallelReductionInfo
using ParallelReductionInfo = std::tuple<bool, unsigned int>
Info for whether a parallel reduction will be run and the vector size of the execution.
Definition at line 104 of file CLSoftmaxLayerKernel.h.
Constructor & Destructor Documentation
CLLogits1DMaxShiftExpSumKernel() [1/3]
CLLogits1DMaxShiftExpSumKernel ()
Default constructor.
Definition at line 215 of file CLSoftmaxLayerKernel.cpp.
     : _input(nullptr), _max(nullptr), _output(nullptr), _sum(nullptr)
 {
 }
CLLogits1DMaxShiftExpSumKernel() [2/3]
CLLogits1DMaxShiftExpSumKernel (const CLLogits1DMaxShiftExpSumKernel &) delete
Prevent instances of this class from being copied (As this class contains pointers)
CLLogits1DMaxShiftExpSumKernel() [3/3]
CLLogits1DMaxShiftExpSumKernel (CLLogits1DMaxShiftExpSumKernel &&) default
Allow instances of this class to be moved.
Member Function Documentation
configure()
void configure (const ICLTensor * input, ICLTensor * max, ICLTensor * output, ICLTensor * sum, float beta = 1.0f)
Set the input and output tensors.
Parameters
[in] input Source tensor. Data types supported: F16/F32
[in,out] max Max values tensor. Data types supported: same as input
[out] output Destination tensor. Data types supported: same as input
[out] sum Sum of 1D logits tensor. Data types supported: same as input
[in] beta (Optional) A scaling factor for the exponent. Defaults to 1.f
Definition at line 220 of file CLSoftmaxLayerKernel.cpp.
 {
     ARM_COMPUTE_ERROR_ON_NULLPTR(input, max, sum, output);
     // Output auto initialization if not yet initialized
     auto_init_if_empty(*sum->info(), input->info()->clone()->set_tensor_shape(max->info()->tensor_shape()));
     auto_init_if_empty(*output->info(), *input->info()->clone());
     // Perform validation step
     ARM_COMPUTE_ERROR_THROW_ON(validate_arguments_1DMaxShiftExpSum(input->info(), max->info(), output->info(), sum->info()));
     _input  = input;
     _max    = max;
     _output = output;
     _sum    = sum;
     const DataType                dt                 = input->info()->data_type();
     const UniformQuantizationInfo qinfo              = input->info()->quantization_info().uniform();
     const size_t                  reduction_dim_size = input->info()->dimension(0);
     // Set build options
     CLBuildOptions build_opts;
     build_opts.add_option("-DDATA_TYPE=" + get_cl_type_from_data_type(dt));
     build_opts.add_option_if(dt == DataType::F16, "-DUSE_F16");
     build_opts.add_option_if(is_data_type_float(dt) && (beta != 1.0f), "-DBETA=" + float_to_string_with_full_precision(beta));
     build_opts.add_options_if(is_data_type_quantized_asymmetric(dt), prepare_quantized_softmax_build_options(qinfo.scale, beta).options());
     cl::NDRange lws_hint(cl::NullRange);
     std::string kernel_name = is_data_type_quantized_asymmetric(dt) ? std::string("softmax_layer_max_shift_exp_sum_quantized_serial") :
                               std::string("softmax_layer_max_shift_exp_sum_serial");
     ParallelReductionInfo parallel_reduction_info = is_parallel_reduction(reduction_dim_size);
     unsigned int          vector_size             = std::get<1>(parallel_reduction_info);
     build_opts.add_option("-DVECTOR_SIZE=" + support::cpp11::to_string(vector_size));
     build_opts.add_option("-DLOG_VECTOR_SIZE=" + support::cpp11::to_string(lround(log2(vector_size))));
     build_opts.add_option_if((reduction_dim_size % vector_size) != 0, "-DNON_MULTIPLE_OF_VECTOR_SIZE");
     // Configure parallel kernel if needed
     if(std::get<0>(parallel_reduction_info))
     {
         kernel_name            = is_data_type_quantized_asymmetric(dt) ? std::string("softmax_layer_max_shift_exp_sum_quantized_parallel") : std::string("softmax_layer_max_shift_exp_sum_parallel");
         bool is_grid_size_pow2 = (_grid_size != 0) && ((_grid_size & (_grid_size - 1)) == 0);
         build_opts.add_option_if(is_grid_size_pow2 && _grid_size <= 256, "-DGRID_SIZE=" + support::cpp11::to_string(_grid_size));
         // Handle boundary conditions.
         const unsigned int multiple_grid_size = (reduction_dim_size / vector_size) % _grid_size;
         build_opts.add_option_if((multiple_grid_size != 0) || ((reduction_dim_size % vector_size) != 0), "-DNON_MULTIPLE_OF_GRID_SIZE");
         // Setting _lws_hint in this way can also communicate grid_size to CLLogits1DMaxShiftExpSumKernel::run().
         // A single workgroup performs reduction in dimension 0 in the parallel case, hence lws[0]==gws[0].
         lws_hint = cl::NDRange(_grid_size);
     }
     // Create kernel.
     _kernel = static_cast<cl::Kernel>(CLKernelLibrary::get().create_kernel(kernel_name, build_opts.options()));
     // Set static arguments. Both the kernels use the same arguments
     unsigned int idx = 4 * num_arguments_per_3D_tensor(); //Skip the input and output parameters
     _kernel.setArg<cl_uint>(idx++, reduction_dim_size);
     // Configure window
     auto win_config = validate_and_configure_window_1DMaxShiftExpSum(input->info(), max->info(), output->info(), sum->info());
     ARM_COMPUTE_ERROR_THROW_ON(win_config.first);
     ICLKernel::configure_internal(win_config.second, lws_hint);
 }
References CLBuildOptions::add_option(), CLBuildOptions::add_option_if(), CLBuildOptions::add_options_if(), ARM_COMPUTE_ERROR_ON_NULLPTR, ARM_COMPUTE_ERROR_THROW_ON, arm_compute::auto_init_if_empty(), ICloneable< T >::clone(), ITensorInfo::data_type(), ITensorInfo::dimension(), arm_compute::F16, arm_compute::float_to_string_with_full_precision(), arm_compute::get_cl_type_from_data_type(), ITensor::info(), arm_compute::is_data_type_float(), arm_compute::is_data_type_quantized_asymmetric(), ICLKernel::lws_hint(), arm_compute::test::validation::qinfo, ITensorInfo::quantization_info(), QuantizationInfo::scale(), sum(), ITensorInfo::tensor_shape(), and QuantizationInfo::uniform().
Referenced by CLSoftmaxLayer::configure().
is_parallel_reduction()
CLLogits1DMaxShiftExpSumKernel::ParallelReductionInfo is_parallel_reduction (size_t size) static
Checks if the given size is eligible for parallel reduction.
Note
Serial reduction is launched for width < (_grid_size * _serial_vector_size).
Parallel reduction is launched for width >= (_grid_size * _serial_vector_size) and vector_size is forced to 4.
Parameters
[in] size Size to check
Returns
A two-element tuple where the first element is a boolean specifying if a parallel reduction will be run, while the second element is the vector size of the execution.
Definition at line 293 of file CLSoftmaxLayerKernel.cpp.
 {
     bool         is_parallel_reduction = (size >= (_grid_size * _serial_vector_size)) && (_grid_size > 1);
     unsigned int vector_size           = is_parallel_reduction ? _parallel_vector_size : _serial_vector_size;
     return std::make_tuple(is_parallel_reduction, vector_size);
 }
Referenced by arm_compute::test::validation::DATA_TEST_CASE(), and CLLogits1DMaxShiftExpSumKernel::run().
operator=() [1/2]
CLLogits1DMaxShiftExpSumKernel& operator= (const CLLogits1DMaxShiftExpSumKernel &) delete
Prevent instances of this class from being copied (As this class contains pointers)
operator=() [2/2]
CLLogits1DMaxShiftExpSumKernel& operator= (CLLogits1DMaxShiftExpSumKernel &&) default
Allow instances of this class to be moved.
run()
void run (const Window & window, cl::CommandQueue & queue) override virtual
Enqueue the OpenCL kernel to process the given window on the passed OpenCL command queue.
Note
The queue is not flushed by this method, and therefore the kernel will not have been executed by the time this method returns.
Parameters
[in] window Region on which to execute the kernel. (Must be a valid region of the window returned by window()).
[in,out] queue Command queue on which to enqueue the kernel.
Implements ICLKernel.
Definition at line 300 of file CLSoftmaxLayerKernel.cpp.
 {
     ARM_COMPUTE_ERROR_ON_UNCONFIGURED_KERNEL(this);
     ARM_COMPUTE_ERROR_ON_INVALID_SUBWINDOW(IKernel::window(), window);
     // Collapse window in Z dimension
     Window window_collapsed = window.collapse_if_possible(ICLKernel::window(), Window::DimZ);
     // Reconfigure window in case of parallel reduction
     ParallelReductionInfo parallel_reduction_info = is_parallel_reduction(_input->info()->dimension(0));
     if(std::get<0>(parallel_reduction_info))
     {
         // To launch grid_size parallel workitems, steps.x should be modified as follows.
         const unsigned int step = std::get<1>(parallel_reduction_info);
         window_collapsed.set(Window::DimX, Window::Dimension(0, _grid_size * step, step));
     }
     // Get slices
     Window slice = window_collapsed.first_slice_window_3D();
     do
     {
         unsigned int idx = 0;
         // Set inputs
         add_3D_tensor_argument(idx, _input, slice);
         add_3D_tensor_argument(idx, _max, slice);
         add_3D_tensor_argument(idx, _output, slice);
         add_3D_tensor_argument(idx, _sum, slice);
         enqueue(queue, *this, slice, lws_hint());
     }
     while(window_collapsed.slide_window_slice_3D(slice));
 }
References ICLKernel::add_3D_tensor_argument(), ARM_COMPUTE_ERROR_ON_INVALID_SUBWINDOW, ARM_COMPUTE_ERROR_ON_UNCONFIGURED_KERNEL, Window::collapse_if_possible(), ITensorInfo::dimension(), Window::DimX, Window::DimZ, arm_compute::enqueue(), Window::first_slice_window_3D(), ITensor::info(), CLLogits1DMaxShiftExpSumKernel::is_parallel_reduction(), ICLKernel::lws_hint(), Window::set(), arm_compute::test::validation::reference::slice(), Window::slide_window_slice_3D(), arm_compute::test::validation::step, and IKernel::window().
validate()
Status validate (const ITensorInfo * input, const ITensorInfo * max, const ITensorInfo * output, const ITensorInfo * sum) static
Static function to check if given info will lead to a valid configuration of CLLogits1DMaxShiftExpSumKernel.
Parameters
[in] input Source tensor. Data types supported: F16/F32
[in] max Max values tensor. Data types supported: same as input
[in] output Destination tensor. Data types supported: same as input
[in] sum Sum of 1D logits tensor. Data types supported: same as input
Returns
a status
Definition at line 285 of file CLSoftmaxLayerKernel.cpp.
 {
     ARM_COMPUTE_RETURN_ON_ERROR(validate_arguments_1DMaxShiftExpSum(input, max, output, sum));
     ARM_COMPUTE_RETURN_ON_ERROR(validate_and_configure_window_1DMaxShiftExpSum(input->clone().get(), max->clone().get(), output->clone().get(), sum->clone().get()).first);
     return Status{};
 }
References ARM_COMPUTE_RETURN_ON_ERROR, ICloneable< T >::clone(), and sum().
Referenced by CLSoftmaxLayer::validate().
The documentation for this class was generated from the following files:
arm_compute/core/CL/kernels/CLSoftmaxLayerKernel.h
src/core/CL/kernels/CLSoftmaxLayerKernel.cpp