Compute Library: CLGenerateProposalsLayer Class Reference
CLGenerateProposalsLayer Class Reference
Basic function to generate proposals for a RPN (Region Proposal Network)
#include <CLGenerateProposalsLayer.h>
Public Member Functions
CLGenerateProposalsLayer (std::shared_ptr< IMemoryManager > memory_manager=nullptr)
Default constructor.
CLGenerateProposalsLayer (const CLGenerateProposalsLayer &)=delete
Prevent instances of this class from being copied (As this class contains pointers)
CLGenerateProposalsLayer (CLGenerateProposalsLayer &&)=default
Default move constructor.
CLGenerateProposalsLayer & operator= (const CLGenerateProposalsLayer &)=delete
Prevent instances of this class from being copied (As this class contains pointers)
CLGenerateProposalsLayer & operator= (CLGenerateProposalsLayer &&)=default
Default move assignment operator.
void configure (const ICLTensor *scores, const ICLTensor *deltas, const ICLTensor *anchors, ICLTensor *proposals, ICLTensor *scores_out, ICLTensor *num_valid_proposals, const GenerateProposalsInfo &info)
Set the input and output tensors.
void run () override
Run the kernels contained in the function.
Public Member Functions inherited from IFunction
virtual ~IFunction ()=default
Destructor.
virtual void prepare ()
Prepare the function for executing.
Static Public Member Functions
static Status validate (const ITensorInfo *scores, const ITensorInfo *deltas, const ITensorInfo *anchors, const ITensorInfo *proposals, const ITensorInfo *scores_out, const ITensorInfo *num_valid_proposals, const GenerateProposalsInfo &info)
Static function to check if given info will lead to a valid configuration of CLGenerateProposalsLayer.
Detailed Description
Basic function to generate proposals for a RPN (Region Proposal Network)
This function calls the following OpenCL kernels:
CLComputeAllAnchors
CLPermute x 2
CLReshapeLayer x 2
CLStridedSlice x 3
CLBoundingBoxTransform
CLCopyKernel
CLMemsetKernel And the following CPP kernels:
CPPBoxWithNonMaximaSuppressionLimit
Definition at line 58 of file CLGenerateProposalsLayer.h.
Constructor & Destructor Documentation
CLGenerateProposalsLayer() [1/3]
CLGenerateProposalsLayer (std::shared_ptr< IMemoryManager > memory_manager = nullptr)
Default constructor.
Parameters
[in] memory_manager (Optional) Memory manager.
Definition at line 32 of file CLGenerateProposalsLayer.cpp.
     : _memory_group(std::move(memory_manager)),
       _permute_deltas_kernel(),
       _flatten_deltas_kernel(),
       _permute_scores_kernel(),
       _flatten_scores_kernel(),
       _compute_anchors_kernel(),
       _bounding_box_kernel(),
       _memset_kernel(),
       _padded_copy_kernel(),
       _cpp_nms_kernel(),
       _is_nhwc(false),
       _deltas_permuted(),
       _deltas_flattened(),
       _scores_permuted(),
       _scores_flattened(),
       _all_anchors(),
       _all_proposals(),
       _keeps_nms_unused(),
       _classes_nms_unused(),
       _proposals_4_roi_values(),
       _num_valid_proposals(nullptr),
       _scores_out(nullptr)
 {
 }
CLGenerateProposalsLayer() [2/3]
CLGenerateProposalsLayer (const CLGenerateProposalsLayer &) delete
Prevent instances of this class from being copied (As this class contains pointers)
CLGenerateProposalsLayer() [3/3]
CLGenerateProposalsLayer (CLGenerateProposalsLayer &&) default
Default move constructor.
Member Function Documentation
configure()
void configure (const ICLTensor * scores, const ICLTensor * deltas, const ICLTensor * anchors, ICLTensor * proposals, ICLTensor * scores_out, ICLTensor * num_valid_proposals, const GenerateProposalsInfo & info)
Set the input and output tensors.
Parameters
[in] scores Scores from convolution layer of size (W, H, A), where H and W are the height and width of the feature map, and A is the number of anchors. Data types supported: F16/F32
[in] deltas Bounding box deltas from convolution layer of size (W, H, 4*A). Data types supported: Same as scores
[in] anchors Anchors tensor of size (4, A). Data types supported: Same as input
[out] proposals Box proposals output tensor of size (5, W*H*A). Data types supported: Same as input
[out] scores_out Box scores output tensor of size (W*H*A). Data types supported: Same as input
[out] num_valid_proposals Scalar output tensor which says which of the first proposals are valid. Data types supported: U32
[in] info Contains GenerateProposals operation information described in GenerateProposalsInfo
Note
Only single image prediction is supported. Height and Width (and scale) of the image will be contained in the GenerateProposalsInfo struct.
Proposals contains all the proposals. Of those, only the first num_valid_proposals are valid.
Definition at line 58 of file CLGenerateProposalsLayer.cpp.
 {
     ARM_COMPUTE_ERROR_ON_NULLPTR(scores, deltas, anchors, proposals, scores_out, num_valid_proposals);
     ARM_COMPUTE_ERROR_THROW_ON(CLGenerateProposalsLayer::validate(scores->info(), deltas->info(), anchors->info(), proposals->info(), scores_out->info(), num_valid_proposals->info(), info));
     _is_nhwc                         = scores->info()->data_layout() == DataLayout::NHWC;
     const DataType data_type         = deltas->info()->data_type();
     const int      num_anchors       = scores->info()->dimension(get_data_layout_dimension_index(scores->info()->data_layout(), DataLayoutDimension::CHANNEL));
     const int      feat_width        = scores->info()->dimension(get_data_layout_dimension_index(scores->info()->data_layout(), DataLayoutDimension::WIDTH));
     const int      feat_height       = scores->info()->dimension(get_data_layout_dimension_index(scores->info()->data_layout(), DataLayoutDimension::HEIGHT));
     const int      total_num_anchors = num_anchors * feat_width * feat_height;
     const int      pre_nms_topN      = info.pre_nms_topN();
     const int      post_nms_topN     = info.post_nms_topN();
     const size_t   values_per_roi    = info.values_per_roi();
     // Compute all the anchors
     _memory_group.manage(&_all_anchors);
     _compute_anchors_kernel.configure(anchors, &_all_anchors, ComputeAnchorsInfo(feat_width, feat_height, info.spatial_scale()));
     const TensorShape flatten_shape_deltas(values_per_roi, total_num_anchors);
     _deltas_flattened.allocator()->init(TensorInfo(flatten_shape_deltas, 1, data_type));
     // Permute and reshape deltas
     if(!_is_nhwc)
     {
         _memory_group.manage(&_deltas_permuted);
         _memory_group.manage(&_deltas_flattened);
         _permute_deltas_kernel.configure(deltas, &_deltas_permuted, PermutationVector{ 2, 0, 1 });
         _flatten_deltas_kernel.configure(&_deltas_permuted, &_deltas_flattened);
         _deltas_permuted.allocator()->allocate();
     }
     else
     {
         _memory_group.manage(&_deltas_flattened);
         _flatten_deltas_kernel.configure(deltas, &_deltas_flattened);
     }
     const TensorShape flatten_shape_scores(1, total_num_anchors);
     _scores_flattened.allocator()->init(TensorInfo(flatten_shape_scores, 1, data_type));
     // Permute and reshape scores
     if(!_is_nhwc)
     {
         _memory_group.manage(&_scores_permuted);
         _memory_group.manage(&_scores_flattened);
         _permute_scores_kernel.configure(scores, &_scores_permuted, PermutationVector{ 2, 0, 1 });
         _flatten_scores_kernel.configure(&_scores_permuted, &_scores_flattened);
         _scores_permuted.allocator()->allocate();
     }
     else
     {
         _memory_group.manage(&_scores_flattened);
         _flatten_scores_kernel.configure(scores, &_scores_flattened);
     }
     // Bounding box transform
     _memory_group.manage(&_all_proposals);
     BoundingBoxTransformInfo bbox_info(info.im_width(), info.im_height(), 1.f);
     _bounding_box_kernel.configure(&_all_anchors, &_all_proposals, &_deltas_flattened, bbox_info);
     _deltas_flattened.allocator()->allocate();
     _all_anchors.allocator()->allocate();
     // The original layer implementation first selects the best pre_nms_topN anchors (thus having a lightweight sort)
     // that are then transformed by bbox_transform. The boxes generated are then fed into a non-sorting NMS operation.
     // Since we are reusing the NMS layer and we don't implement any CL/sort, we let NMS do the sorting (of all the input)
     // and the filtering
     const int   scores_nms_size = std::min<int>(std::min<int>(post_nms_topN, pre_nms_topN), total_num_anchors);
     const float min_size_scaled = info.min_size() * info.im_scale();
     _memory_group.manage(&_classes_nms_unused);
     _memory_group.manage(&_keeps_nms_unused);
     // Note that NMS needs outputs preinitialized.
     auto_init_if_empty(*scores_out->info(), TensorShape(scores_nms_size), 1, data_type);
     auto_init_if_empty(*_proposals_4_roi_values.info(), TensorShape(values_per_roi, scores_nms_size), 1, data_type);
     auto_init_if_empty(*num_valid_proposals->info(), TensorShape(1), 1, DataType::U32);
     // Initialize temporaries (unused) outputs
     _classes_nms_unused.allocator()->init(TensorInfo(TensorShape(1, 1), 1, data_type));
     _keeps_nms_unused.allocator()->init(*scores_out->info());
     // Save the output (to map and unmap them at run)
     _scores_out          = scores_out;
     _num_valid_proposals = num_valid_proposals;
     _memory_group.manage(&_proposals_4_roi_values);
     _cpp_nms_kernel.configure(&_scores_flattened, &_all_proposals, nullptr, scores_out, &_proposals_4_roi_values, &_classes_nms_unused, nullptr, &_keeps_nms_unused, num_valid_proposals,
                               BoxNMSLimitInfo(0.0f, info.nms_thres(), scores_nms_size, false, NMSType::LINEAR, 0.5f, 0.001f, true, min_size_scaled, info.im_width(), info.im_height()));
     _keeps_nms_unused.allocator()->allocate();
     _classes_nms_unused.allocator()->allocate();
     _all_proposals.allocator()->allocate();
     _scores_flattened.allocator()->allocate();
     // Add the first column that represents the batch id. This will be all zeros, as we don't support multiple images
     _padded_copy_kernel.configure(&_proposals_4_roi_values, proposals, PaddingList{ { 1, 0 } });
     _proposals_4_roi_values.allocator()->allocate();
     _memset_kernel.configure(proposals, PixelValue());
 }
References CLTensorAllocator::allocate(), CLTensor::allocator(), ARM_COMPUTE_ERROR_ON_NULLPTR, ARM_COMPUTE_ERROR_THROW_ON, arm_compute::auto_init_if_empty(), arm_compute::CHANNEL, CLReshapeLayerKernel::configure(), CLCopyKernel::configure(), CLComputeAllAnchorsKernel::configure(), CLPermuteKernel::configure(), CLMemsetKernel::configure(), CLBoundingBoxTransformKernel::configure(), CPPBoxWithNonMaximaSuppressionLimitKernel::configure(), ITensorInfo::data_layout(), arm_compute::test::validation::data_type, ITensorInfo::data_type(), ITensorInfo::dimension(), arm_compute::get_data_layout_dimension_index(), arm_compute::HEIGHT, ITensor::info(), CLTensor::info(), arm_compute::test::validation::info, ITensorAllocator::init(), arm_compute::LINEAR, MemoryGroupBase< TensorType >::manage(), arm_compute::NHWC, arm_compute::U32, CLGenerateProposalsLayer::validate(), and arm_compute::WIDTH.
operator=() [1/2]
CLGenerateProposalsLayer& operator= (const CLGenerateProposalsLayer &) delete
Prevent instances of this class from being copied (As this class contains pointers)
operator=() [2/2]
CLGenerateProposalsLayer& operator= (CLGenerateProposalsLayer &&) default
Default move assignment operator.
run()
void run () override virtual
Run the kernels contained in the function.
For NEON kernels:
Multi-threading is used for the kernels which are parallelisable.
By default std::thread::hardware_concurrency() threads are used.
Note
CPPScheduler::set_num_threads() can be used to manually set the number of threads
For OpenCL kernels:
All the kernels are enqueued on the queue associated with CLScheduler.
The queue is then flushed.
Note
The function will not block until the kernels are executed. It is the user's responsibility to wait.
Will call prepare() on first run if hasn't been done
Implements IFunction.
Definition at line 256 of file CLGenerateProposalsLayer.cpp.
 {
     // Acquire all the temporaries
     MemoryGroupResourceScope scope_mg(_memory_group);
     // Compute all the anchors
     CLScheduler::get().enqueue(_compute_anchors_kernel, false);
     // Transpose and reshape the inputs
     if(!_is_nhwc)
     {
         CLScheduler::get().enqueue(_permute_deltas_kernel, false);
         CLScheduler::get().enqueue(_permute_scores_kernel, false);
     }
     CLScheduler::get().enqueue(_flatten_deltas_kernel, false);
     CLScheduler::get().enqueue(_flatten_scores_kernel, false);
     // Build the boxes
     CLScheduler::get().enqueue(_bounding_box_kernel, false);
     // Non maxima suppression
     run_cpp_nms_kernel();
     // Add dummy batch indexes
     CLScheduler::get().enqueue(_memset_kernel, true);
     CLScheduler::get().enqueue(_padded_copy_kernel, true);
 }
References CLScheduler::enqueue(), and CLScheduler::get().
validate()
Status validate (const ITensorInfo * scores, const ITensorInfo * deltas, const ITensorInfo * anchors, const ITensorInfo * proposals, const ITensorInfo * scores_out, const ITensorInfo * num_valid_proposals, const GenerateProposalsInfo & info) static
Static function to check if given info will lead to a valid configuration of CLGenerateProposalsLayer.
Parameters
[in] scores Scores info from convolution layer of size (W, H, A), where H and W are the height and width of the feature map, and A is the number of anchors. Data types supported: F16/F32
[in] deltas Bounding box deltas info from convolution layer of size (W, H, 4*A). Data types supported: Same as scores
[in] anchors Anchors tensor info of size (4, A). Data types supported: Same as input
[in] proposals Box proposals info output tensor of size (5, W*H*A). Data types supported: Data types supported: U32
[in] scores_out Box scores output tensor info of size (W*H*A). Data types supported: Same as input
[in] num_valid_proposals Scalar output tensor info which says which of the first proposals are valid. Data types supported: Same as input
[in] info Contains GenerateProposals operation information described in GenerateProposalsInfo
Returns
a Status
Definition at line 158 of file CLGenerateProposalsLayer.cpp.
 {
     ARM_COMPUTE_RETURN_ERROR_ON_NULLPTR(scores, deltas, anchors, proposals, scores_out, num_valid_proposals);
     ARM_COMPUTE_RETURN_ERROR_ON_DATA_LAYOUT_NOT_IN(scores, DataLayout::NCHW, DataLayout::NHWC);
     ARM_COMPUTE_RETURN_ERROR_ON_MISMATCHING_DATA_LAYOUT(scores, deltas);
     const int num_anchors       = scores->dimension(get_data_layout_dimension_index(scores->data_layout(), DataLayoutDimension::CHANNEL));
     const int feat_width        = scores->dimension(get_data_layout_dimension_index(scores->data_layout(), DataLayoutDimension::WIDTH));
     const int feat_height       = scores->dimension(get_data_layout_dimension_index(scores->data_layout(), DataLayoutDimension::HEIGHT));
     const int num_images        = scores->dimension(3);
     const int total_num_anchors = num_anchors * feat_width * feat_height;
     const int values_per_roi    = info.values_per_roi();
     ARM_COMPUTE_RETURN_ERROR_ON(num_images > 1);
     TensorInfo all_anchors_info(anchors->clone()->set_tensor_shape(TensorShape(values_per_roi, total_num_anchors)).set_is_resizable(true));
     ARM_COMPUTE_RETURN_ON_ERROR(CLComputeAllAnchorsKernel::validate(anchors, &all_anchors_info, ComputeAnchorsInfo(feat_width, feat_height, info.spatial_scale())));
     TensorInfo deltas_permuted_info = deltas->clone()->set_tensor_shape(TensorShape(values_per_roi * num_anchors, feat_width, feat_height)).set_is_resizable(true);
     TensorInfo scores_permuted_info = scores->clone()->set_tensor_shape(TensorShape(num_anchors, feat_width, feat_height)).set_is_resizable(true);
     if(scores->data_layout() == DataLayout::NHWC)
     {
         ARM_COMPUTE_RETURN_ERROR_ON_MISMATCHING_SHAPES(deltas, &deltas_permuted_info);
         ARM_COMPUTE_RETURN_ERROR_ON_MISMATCHING_SHAPES(scores, &scores_permuted_info);
     }
     else
     {
         ARM_COMPUTE_RETURN_ON_ERROR(CLPermuteKernel::validate(deltas, &deltas_permuted_info, PermutationVector{ 2, 0, 1 }));
         ARM_COMPUTE_RETURN_ON_ERROR(CLPermuteKernel::validate(scores, &scores_permuted_info, PermutationVector{ 2, 0, 1 }));
     }
     TensorInfo deltas_flattened_info(deltas->clone()->set_tensor_shape(TensorShape(values_per_roi, total_num_anchors)).set_is_resizable(true));
     ARM_COMPUTE_RETURN_ON_ERROR(CLReshapeLayerKernel::validate(&deltas_permuted_info, &deltas_flattened_info));
     TensorInfo scores_flattened_info(deltas->clone()->set_tensor_shape(TensorShape(1, total_num_anchors)).set_is_resizable(true));
     TensorInfo proposals_4_roi_values(deltas->clone()->set_tensor_shape(TensorShape(values_per_roi, total_num_anchors)).set_is_resizable(true));
     ARM_COMPUTE_RETURN_ON_ERROR(CLReshapeLayerKernel::validate(&scores_permuted_info, &scores_flattened_info));
     ARM_COMPUTE_RETURN_ON_ERROR(CLBoundingBoxTransformKernel::validate(&all_anchors_info, &proposals_4_roi_values, &deltas_flattened_info, BoundingBoxTransformInfo(info.im_width(), info.im_height(),
                                                                        1.f)));
     ARM_COMPUTE_RETURN_ON_ERROR(CLCopyKernel::validate(&proposals_4_roi_values, proposals, PaddingList{ { 0, 1 } }));
     ARM_COMPUTE_RETURN_ON_ERROR(CLMemsetKernel::validate(proposals, PixelValue()));
     if(num_valid_proposals->total_size() > 0)
     {
         ARM_COMPUTE_RETURN_ERROR_ON(num_valid_proposals->num_dimensions() > 1);
         ARM_COMPUTE_RETURN_ERROR_ON(num_valid_proposals->dimension(0) > 1);
         ARM_COMPUTE_RETURN_ERROR_ON_DATA_TYPE_CHANNEL_NOT_IN(num_valid_proposals, 1, DataType::U32);
     }
     if(proposals->total_size() > 0)
     {
         ARM_COMPUTE_RETURN_ERROR_ON(proposals->num_dimensions() > 2);
         ARM_COMPUTE_RETURN_ERROR_ON(proposals->dimension(0) != size_t(values_per_roi) + 1);
         ARM_COMPUTE_RETURN_ERROR_ON(proposals->dimension(1) != size_t(total_num_anchors));
         ARM_COMPUTE_RETURN_ERROR_ON_MISMATCHING_DATA_TYPES(proposals, deltas);
     }
     if(scores_out->total_size() > 0)
     {
         ARM_COMPUTE_RETURN_ERROR_ON(scores_out->num_dimensions() > 1);
         ARM_COMPUTE_RETURN_ERROR_ON(scores_out->dimension(0) != size_t(total_num_anchors));
         ARM_COMPUTE_RETURN_ERROR_ON_MISMATCHING_DATA_TYPES(scores_out, scores);
     }
     return Status{};
 }
References ARM_COMPUTE_RETURN_ERROR_ON, ARM_COMPUTE_RETURN_ERROR_ON_DATA_LAYOUT_NOT_IN, ARM_COMPUTE_RETURN_ERROR_ON_DATA_TYPE_CHANNEL_NOT_IN, ARM_COMPUTE_RETURN_ERROR_ON_MISMATCHING_DATA_LAYOUT, ARM_COMPUTE_RETURN_ERROR_ON_MISMATCHING_DATA_TYPES, ARM_COMPUTE_RETURN_ERROR_ON_MISMATCHING_SHAPES, ARM_COMPUTE_RETURN_ERROR_ON_NULLPTR, ARM_COMPUTE_RETURN_ON_ERROR, arm_compute::CHANNEL, ICloneable< T >::clone(), ITensorInfo::data_layout(), ITensorInfo::dimension(), arm_compute::get_data_layout_dimension_index(), arm_compute::HEIGHT, arm_compute::test::validation::info, arm_compute::NCHW, arm_compute::NHWC, ITensorInfo::num_dimensions(), ITensorInfo::total_size(), arm_compute::U32, CLReshapeLayerKernel::validate(), CLCopyKernel::validate(), CLPermuteKernel::validate(), CLComputeAllAnchorsKernel::validate(), CLMemsetKernel::validate(), CLBoundingBoxTransformKernel::validate(), and arm_compute::WIDTH.
Referenced by CLGenerateProposalsLayer::configure().
The documentation for this class was generated from the following files:
arm_compute/runtime/CL/functions/CLGenerateProposalsLayer.h
src/runtime/CL/functions/CLGenerateProposalsLayer.cpp