Compute Library: NERange Class Reference
NERange Class Reference
Basic function to run NERangeKernel.
#include <NERange.h>
Public Member Functions
NERange ()
Default constructor.
void configure (ITensor *output, float start, float end, float step=1.f)
Initialize the kernel's start, end, step and output tensor.
void run () override
Run the kernels contained in the function.
Public Member Functions inherited from IFunction
virtual ~IFunction ()=default
Destructor.
virtual void prepare ()
Prepare the function for executing.
Static Public Member Functions
static Status validate (const ITensorInfo *output, float start, float end, float step=1.f)
Static function to check if given info will lead to a valid configuration of NERange.
Detailed Description
Basic function to run NERangeKernel.
Note
The tensor data type for the output must be U8/S8/U16/S16/U32/S32/F16/F32.
The function performs generates a sequence with the given start, end and step.
Definition at line 40 of file NERange.h.
Constructor & Destructor Documentation
NERange()
NERange ()
Default constructor.
Definition at line 30 of file NERange.cpp.
     : _kernel()
 {
 }
Member Function Documentation
configure()
void configure (ITensor * output, float start, float end, float step = 1.f)
Initialize the kernel's start, end, step and output tensor.
Parameters
[out] output Output tensor. Data types supported: U8/S8/U16/S16/U32/S32/F16/F32.
[in] start The starting value of the sequence.
[in] end The ending (not including) value of the sequence.
[in] step The gap between each pair of values in the sequence. Default is 1.
Definition at line 35 of file NERange.cpp.
 {
     _kernel.configure(output, start, end, step);
 }
References NERangeKernel::configure(), and arm_compute::test::validation::step.
run()
void run () override virtual
Run the kernels contained in the function.
For NEON kernels:
Multi-threading is used for the kernels which are parallelisable.
By default std::thread::hardware_concurrency() threads are used.
Note
CPPScheduler::set_num_threads() can be used to manually set the number of threads
For OpenCL kernels:
All the kernels are enqueued on the queue associated with CLScheduler.
The queue is then flushed.
Note
The function will not block until the kernels are executed. It is the user's responsibility to wait.
Will call prepare() on first run if hasn't been done
Implements IFunction.
Definition at line 45 of file NERange.cpp.
 {
     NEScheduler::get().schedule(&_kernel, Window::DimX);
 }
References Window::DimX, Scheduler::get(), and IScheduler::schedule().
validate()
Status validate (const ITensorInfo * output, float start, float end, float step = 1.f) static
Static function to check if given info will lead to a valid configuration of NERange.
Parameters
[in] output Output tensor info. Data types supported: U8/S8/U16/S16/U32/S32/F16/F32.
[in] start The starting value of the sequence.
[in] end The ending (not including) value of the sequence.
[in] step The gap between each pair of values in the sequence. Default is 1.
Returns
a status
Definition at line 40 of file NERange.cpp.
 {
     return NERangeKernel::validate(output, start, end, step);
 }
References arm_compute::test::validation::step, and NERangeKernel::validate().
The documentation for this class was generated from the following files:
arm_compute/runtime/NEON/functions/NERange.h
src/runtime/NEON/functions/NERange.cpp