Compute Library: NEHistogramKernel Class Reference
NEHistogramKernel Class Reference
Interface for the histogram kernel.
#include <NEHistogramKernel.h>
Public Member Functions
const char * name () const override
Name of the kernel.
NEHistogramKernel ()
Default constructor.
~NEHistogramKernel ()=default
Default destructor.
NEHistogramKernel (const NEHistogramKernel &)=delete
Prevent instances of this class from being copied (As this class contains pointers)
NEHistogramKernel & operator= (const NEHistogramKernel &)=delete
Prevent instances of this class from being copied (As this class contains pointers)
NEHistogramKernel (NEHistogramKernel &&)=default
Allow instances of this class to be moved.
NEHistogramKernel & operator= (NEHistogramKernel &&)=default
Allow instances of this class to be moved.
void configure (const IImage *input, IDistribution1D *output, uint32_t *local_hist, uint32_t *window_lut)
Set the input image and the distribution output.
void configure (const IImage *input, IDistribution1D *output)
Set the input image and the distribution output.
void run (const Window &window, const ThreadInfo &info) override
Execute the kernel on the passed window.
Public Member Functions inherited from ICPPKernel
virtual ~ICPPKernel ()=default
Default destructor.
Public Member Functions inherited from IKernel
IKernel ()
Constructor.
virtual ~IKernel ()=default
Destructor.
virtual bool is_parallelisable () const
Indicates whether or not the kernel is parallelisable.
virtual BorderSize border_size () const
The size of the border for that kernel.
const Window & window () const
The maximum window the kernel can be executed on.
Detailed Description
Interface for the histogram kernel.
Definition at line 40 of file NEHistogramKernel.h.
Constructor & Destructor Documentation
NEHistogramKernel() [1/3]
NEHistogramKernel ()
Default constructor.
Definition at line 61 of file NEHistogramKernel.cpp.
     : _func(nullptr), _input(nullptr), _output(nullptr), _local_hist(nullptr), _window_lut(nullptr), _hist_mtx()
 {
 }
~NEHistogramKernel()
~NEHistogramKernel () default
Default destructor.
NEHistogramKernel() [2/3]
NEHistogramKernel (const NEHistogramKernel &) delete
Prevent instances of this class from being copied (As this class contains pointers)
NEHistogramKernel() [3/3]
NEHistogramKernel (NEHistogramKernel &&) default
Allow instances of this class to be moved.
Member Function Documentation
configure() [1/2]
void configure (const IImage * input, IDistribution1D * output, uint32_t * local_hist, uint32_t * window_lut)
Set the input image and the distribution output.
Parameters
[in] input Source image. Data type supported: U8.
[out] output Destination distribution.
[in,out] local_hist Array that the threads use to save their local histograms. It's size should be equal to (number_of_threads * num_bins), and the Window::thread_id() is used to determine the part of the array used by each thread.
[out] window_lut LUT with pre-calculated possible window values. The size of the LUT should be equal to max_range_size and it will be filled during the configure stage, while it re-used in every run, therefore can be safely shared among threads.
Definition at line 192 of file NEHistogramKernel.cpp.
 {
     ARM_COMPUTE_ERROR_ON_TENSOR_NOT_2D(input);
     ARM_COMPUTE_ERROR_ON_DATA_TYPE_CHANNEL_NOT_IN(input, 1, DataType::U8);
     ARM_COMPUTE_ERROR_ON(nullptr == output);
     ARM_COMPUTE_ERROR_ON(nullptr == local_hist);
     ARM_COMPUTE_ERROR_ON(nullptr == window_lut);
     _input      = input;
     _output     = output;
     _local_hist = local_hist;
     _window_lut = window_lut;
     //Check offset
     ARM_COMPUTE_ERROR_ON_MSG(0 > _output->offset() || _output->offset() > static_cast<int32_t>(_max_range_size), "Offset is larger than the image value range.");
     //Check range
     ARM_COMPUTE_ERROR_ON_MSG(static_cast<int32_t>(_output->range()) > static_cast<int32_t>(_max_range_size) /* max range */, "Range larger than the image value range.");
     // Calculate LUT
     calculate_window_lut();
     // Set appropriate function
     _func = &NEHistogramKernel::histogram_U8;
     Window win = calculate_max_window(*input->info(), Steps());
     INEKernel::configure(win);
 }
References ARM_COMPUTE_ERROR_ON, ARM_COMPUTE_ERROR_ON_DATA_TYPE_CHANNEL_NOT_IN, ARM_COMPUTE_ERROR_ON_MSG, ARM_COMPUTE_ERROR_ON_TENSOR_NOT_2D, arm_compute::calculate_max_window(), ITensor::info(), IDistribution1D::offset(), IDistribution1D::range(), and arm_compute::U8.
Referenced by NEHistogram::configure(), and NEEqualizeHistogram::configure().
configure() [2/2]
void configure (const IImage * input, IDistribution1D * output)
Set the input image and the distribution output.
Note
Used for histogram of fixed size equal to 256
Parameters
[in] input Source image. Data type supported: U8.
[out] output Destination distribution which must be of 256 bins..
Definition at line 222 of file NEHistogramKernel.cpp.
 {
     ARM_COMPUTE_ERROR_ON_TENSOR_NOT_2D(input);
     ARM_COMPUTE_ERROR_ON_DATA_TYPE_CHANNEL_NOT_IN(input, 1, DataType::U8);
     ARM_COMPUTE_ERROR_ON(nullptr == output);
     _input  = input;
     _output = output;
     // Set appropriate function
     _func = &NEHistogramKernel::histogram_fixed_U8;
     Window win = calculate_max_window(*input->info(), Steps());
     INEKernel::configure(win);
 }
References ARM_COMPUTE_ERROR_ON, ARM_COMPUTE_ERROR_ON_DATA_TYPE_CHANNEL_NOT_IN, ARM_COMPUTE_ERROR_ON_TENSOR_NOT_2D, arm_compute::calculate_max_window(), ITensor::info(), and arm_compute::U8.
name()
const char* name () const inline override virtual
Name of the kernel.
Returns
Kernel name
Implements ICPPKernel.
Definition at line 43 of file NEHistogramKernel.h.
     {
         return "NEHistogramKernel";
     }
operator=() [1/2]
NEHistogramKernel& operator= (const NEHistogramKernel &) delete
Prevent instances of this class from being copied (As this class contains pointers)
operator=() [2/2]
NEHistogramKernel& operator= (NEHistogramKernel &&) default
Allow instances of this class to be moved.
run()
void run (const Window & window, const ThreadInfo & info) override virtual
Execute the kernel on the passed window.
Warning
If is_parallelisable() returns false then the passed window must be equal to window()
Note
The window has to be a region within the window returned by the window() method
The width of the window has to be a multiple of num_elems_processed_per_iteration().
Parameters
[in] window Region on which to execute the kernel. (Must be a region of the window returned by window())
[in] info Info about executing thread and CPU.
Implements ICPPKernel.
Definition at line 239 of file NEHistogramKernel.cpp.
 {
     ARM_COMPUTE_ERROR_ON_UNCONFIGURED_KERNEL(this);
     ARM_COMPUTE_ERROR_ON_INVALID_SUBWINDOW(INEKernel::window(), window);
     ARM_COMPUTE_ERROR_ON(_func == nullptr);
     (this->*_func)(window, info);
 }
References ARM_COMPUTE_ERROR_ON, ARM_COMPUTE_ERROR_ON_INVALID_SUBWINDOW, ARM_COMPUTE_ERROR_ON_UNCONFIGURED_KERNEL, arm_compute::test::validation::info, and IKernel::window().
The documentation for this class was generated from the following files:
arm_compute/core/NEON/kernels/NEHistogramKernel.h
src/core/NEON/kernels/NEHistogramKernel.cpp