Compute Library: NESobel7x7 Class Reference
NESobel7x7 Class Reference
Basic function to execute sobel 7x7 filter.
#include <NESobel7x7.h>
Public Member Functions
NESobel7x7 (std::shared_ptr< IMemoryManager > memory_manager=nullptr)
Default constructor.
void configure (ITensor *input, ITensor *output_x, ITensor *output_y, BorderMode border_mode, uint8_t constant_border_value=0)
Initialise the function's source, destinations and border mode.
void run () override
Run the kernels contained in the function.
Public Member Functions inherited from IFunction
virtual ~IFunction ()=default
Destructor.
virtual void prepare ()
Prepare the function for executing.
Detailed Description
Basic function to execute sobel 7x7 filter.
This function calls the following NEON kernels:
NEFillBorderKernel (executed if border_mode == CONSTANT or border_mode == REPLICATE)
NESobel7x7HorKernel
NESobel7x7VertKernel
Definition at line 49 of file NESobel7x7.h.
Constructor & Destructor Documentation
NESobel7x7()
NESobel7x7 (std::shared_ptr< IMemoryManager > memory_manager = nullptr)
Default constructor.
Definition at line 35 of file NESobel7x7.cpp.
     : _memory_group(std::move(memory_manager)), _sobel_hor(), _sobel_vert(), _tmp_x(), _tmp_y(), _border_handler()
 {
 }
Member Function Documentation
configure()
void configure (ITensor * input, ITensor * output_x, ITensor * output_y, BorderMode border_mode, uint8_t constant_border_value = 0)
Initialise the function's source, destinations and border mode.
Note
At least one of output_x or output_y must be not NULL.
Parameters
[in,out] input Source tensor. Data type supported: U8. (Written to only for border_mode != UNDEFINED)
[out] output_x (optional) Destination for the Sobel 7x7 convolution along the X axis. Data type supported: S32.
[out] output_y (optional) Destination for the Sobel 7x7 convolution along the Y axis. Data type supported: S32.
[in] border_mode Border mode to use for the convolution.
[in] constant_border_value (Optional) Constant value to use for borders if border_mode is set to CONSTANT.
Definition at line 40 of file NESobel7x7.cpp.
 {
     ARM_COMPUTE_ERROR_ON_DATA_TYPE_CHANNEL_NOT_IN(input, 1, DataType::U8);
     const bool run_sobel_x = output_x != nullptr;
     const bool run_sobel_y = output_y != nullptr;
     TensorInfo tensor_info(input->info()->tensor_shape(), Format::S32);
     if(run_sobel_x && run_sobel_y)
     {
         _tmp_x.allocator()->init(tensor_info);
         _tmp_y.allocator()->init(tensor_info);
         _memory_group.manage(&_tmp_x);
         _memory_group.manage(&_tmp_y);
         _sobel_hor.configure(input, &_tmp_x, &_tmp_y, border_mode == BorderMode::UNDEFINED);
         _sobel_vert.configure(&_tmp_x, &_tmp_y, output_x, output_y, border_mode == BorderMode::UNDEFINED);
         _tmp_x.allocator()->allocate();
         _tmp_y.allocator()->allocate();
     }
     else if(run_sobel_x)
     {
         _tmp_x.allocator()->init(tensor_info);
         _memory_group.manage(&_tmp_x);
         _sobel_hor.configure(input, &_tmp_x, nullptr, border_mode == BorderMode::UNDEFINED);
         _sobel_vert.configure(&_tmp_x, nullptr, output_x, nullptr, border_mode == BorderMode::UNDEFINED);
         _tmp_x.allocator()->allocate();
     }
     else if(run_sobel_y)
     {
         _tmp_y.allocator()->init(tensor_info);
         _memory_group.manage(&_tmp_y);
         _sobel_hor.configure(input, nullptr, &_tmp_y, border_mode == BorderMode::UNDEFINED);
         _sobel_vert.configure(nullptr, &_tmp_y, nullptr, output_y, border_mode == BorderMode::UNDEFINED);
         _tmp_y.allocator()->allocate();
     }
     _border_handler.configure(input, _sobel_hor.border_size(), border_mode, PixelValue(constant_border_value));
 }
References TensorAllocator::allocate(), Tensor::allocator(), ARM_COMPUTE_ERROR_ON_DATA_TYPE_CHANNEL_NOT_IN, arm_compute::test::validation::border_mode, NESobel7x7HorKernel::border_size(), NESobel7x7HorKernel::configure(), NEFillBorderKernel::configure(), NESobel7x7VertKernel::configure(), ITensor::info(), TensorAllocator::init(), MemoryGroupBase< TensorType >::manage(), arm_compute::S32, ITensorInfo::tensor_shape(), arm_compute::U8, and arm_compute::UNDEFINED.
run()
void run () override virtual
Run the kernels contained in the function.
For NEON kernels:
Multi-threading is used for the kernels which are parallelisable.
By default std::thread::hardware_concurrency() threads are used.
Note
CPPScheduler::set_num_threads() can be used to manually set the number of threads
For OpenCL kernels:
All the kernels are enqueued on the queue associated with CLScheduler.
The queue is then flushed.
Note
The function will not block until the kernels are executed. It is the user's responsibility to wait.
Will call prepare() on first run if hasn't been done
Implements IFunction.
Definition at line 80 of file NESobel7x7.cpp.
 {
     NEScheduler::get().schedule(&_border_handler, Window::DimZ);
     MemoryGroupResourceScope scope_mg(_memory_group);
     NEScheduler::get().schedule(&_sobel_hor, Window::DimY);
     NEScheduler::get().schedule(&_sobel_vert, Window::DimY);
 }
References Window::DimY, Window::DimZ, Scheduler::get(), and IScheduler::schedule().
The documentation for this class was generated from the following files:
arm_compute/runtime/NEON/functions/NESobel7x7.h
src/runtime/NEON/functions/NESobel7x7.cpp