Compute Library: NEFFT2D Class Reference
NEFFT2D Class Reference
Basic function to execute two dimensional FFT.
#include <NEFFT2D.h>
Public Member Functions
NEFFT2D (std::shared_ptr< IMemoryManager > memory_manager=nullptr)
Default Constructor.
void configure (const ITensor *input, ITensor *output, const FFT2DInfo &config)
Initialise the function's source and destinations.
void run () override
Run the kernels contained in the function.
Public Member Functions inherited from IFunction
virtual ~IFunction ()=default
Destructor.
virtual void prepare ()
Prepare the function for executing.
Static Public Member Functions
static Status validate (const ITensorInfo *input, const ITensorInfo *output, const FFT2DInfo &config)
Static function to check if given info will lead to a valid configuration of NEFFT2D.
Detailed Description
Basic function to execute two dimensional FFT.
This function calls the following NEON kernels:
NEFFT1D 1D FFT is performed on the first given axis
NEFFT1D 1D FFT is performed on the second given axis
Definition at line 44 of file NEFFT2D.h.
Constructor & Destructor Documentation
NEFFT2D()
NEFFT2D (std::shared_ptr< IMemoryManager > memory_manager = nullptr)
Default Constructor.
Definition at line 32 of file NEFFT2D.cpp.
     : _memory_group(memory_manager), _first_pass_func(memory_manager), _second_pass_func(memory_manager), _first_pass_tensor()
 {
 }
Member Function Documentation
configure()
void configure (const ITensor * input, ITensor * output, const FFT2DInfo & config)
Initialise the function's source and destinations.
Parameters
[in] input Source tensor. Data types supported: F32.
[out] output Destination tensor. Data types and data layouts supported: Same as input.
[in] config FFT related configuration
Definition at line 37 of file NEFFT2D.cpp.
 {
     ARM_COMPUTE_ERROR_ON_NULLPTR(input, output);
     ARM_COMPUTE_ERROR_THROW_ON(NEFFT2D::validate(input->info(), output->info(), config));
     // Setup first pass
     FFT1DInfo first_pass_config;
     first_pass_config.axis      = config.axes.first;
     first_pass_config.direction = config.direction;
     _memory_group.manage(&_first_pass_tensor);
     _first_pass_func.configure(input, &_first_pass_tensor, first_pass_config);
     // Setup second pass
     FFT1DInfo second_pass_config;
     second_pass_config.axis      = config.axes.second;
     second_pass_config.direction = config.direction;
     _second_pass_func.configure(&_first_pass_tensor, output, second_pass_config);
     _first_pass_tensor.allocator()->allocate();
 }
References TensorAllocator::allocate(), Tensor::allocator(), ARM_COMPUTE_ERROR_ON_NULLPTR, ARM_COMPUTE_ERROR_THROW_ON, FFT2DInfo::axes, FFT1DInfo::axis, NEFFT1D::configure(), FFT1DInfo::direction, FFT2DInfo::direction, ITensor::info(), MemoryGroupBase< TensorType >::manage(), and NEFFT2D::validate().
Referenced by NEFFTConvolutionLayer::configure().
run()
void run () override virtual
Run the kernels contained in the function.
For NEON kernels:
Multi-threading is used for the kernels which are parallelisable.
By default std::thread::hardware_concurrency() threads are used.
Note
CPPScheduler::set_num_threads() can be used to manually set the number of threads
For OpenCL kernels:
All the kernels are enqueued on the queue associated with CLScheduler.
The queue is then flushed.
Note
The function will not block until the kernels are executed. It is the user's responsibility to wait.
Will call prepare() on first run if hasn't been done
Implements IFunction.
Definition at line 86 of file NEFFT2D.cpp.
 {
     _memory_group.acquire();
     _first_pass_func.run();
     _second_pass_func.run();
     _memory_group.release();
 }
References MemoryGroupBase< TensorType >::acquire(), MemoryGroupBase< TensorType >::release(), and NEFFT1D::run().
Referenced by NEFFTConvolutionLayer::run().
validate()
Status validate (const ITensorInfo * input, const ITensorInfo * output, const FFT2DInfo & config) static
Static function to check if given info will lead to a valid configuration of NEFFT2D.
Parameters
[in] input Source tensor info. Data types supported: F32.
[in] output Destination tensor info. Data types and data layouts supported: Same as input.
[in] config FFT related configuration
Returns
a status
Definition at line 57 of file NEFFT2D.cpp.
 {
     ARM_COMPUTE_RETURN_ERROR_ON_NULLPTR(input, output);
     // Create intermediate tensor info
     TensorInfo first_pass_tensor(input->clone()->set_is_resizable(true).reset_padding().set_num_channels(2));
     // Validate first pass
     FFT1DInfo first_pass_config;
     first_pass_config.axis      = config.axes.first;
     first_pass_config.direction = config.direction;
     ARM_COMPUTE_RETURN_ON_ERROR(NEFFT1D::validate(input, &first_pass_tensor, first_pass_config));
     // Validate second pass
     FFT1DInfo second_pass_config;
     second_pass_config.axis      = config.axes.second;
     second_pass_config.direction = config.direction;
     ARM_COMPUTE_RETURN_ON_ERROR(NEFFT1D::validate(&first_pass_tensor, output, second_pass_config));
     // Checks performed when output is configured
     if((output != nullptr) && (output->total_size() != 0))
     {
         ARM_COMPUTE_RETURN_ERROR_ON_MISMATCHING_SHAPES(input, output);
         ARM_COMPUTE_RETURN_ERROR_ON_MISMATCHING_DATA_TYPES(input, output);
     }
     return Status{};
 }
References ARM_COMPUTE_RETURN_ERROR_ON_MISMATCHING_DATA_TYPES, ARM_COMPUTE_RETURN_ERROR_ON_MISMATCHING_SHAPES, ARM_COMPUTE_RETURN_ERROR_ON_NULLPTR, ARM_COMPUTE_RETURN_ON_ERROR, FFT2DInfo::axes, FFT1DInfo::axis, ICloneable< T >::clone(), FFT1DInfo::direction, FFT2DInfo::direction, ITensorInfo::total_size(), and NEFFT1D::validate().
Referenced by NEFFT2D::configure().
The documentation for this class was generated from the following files:
arm_compute/runtime/NEON/functions/NEFFT2D.h
src/runtime/NEON/functions/NEFFT2D.cpp