Compute Library: NEIm2ColKernel Class Reference
NEIm2ColKernel Class Reference
Interface for the im2col reshape kernel.
#include <NEIm2ColKernel.h>
Public Member Functions
const char * name () const override
Name of the kernel.
NEIm2ColKernel ()
Default constructor.
NEIm2ColKernel (const NEIm2ColKernel &)=delete
Prevent instances of this class from being copied (As this class contains pointers)
NEIm2ColKernel & operator= (const NEIm2ColKernel &)=delete
Prevent instances of this class from being copied (As this class contains pointers)
NEIm2ColKernel (NEIm2ColKernel &&)=default
Allow instances of this class to be moved.
NEIm2ColKernel & operator= (NEIm2ColKernel &&)=default
Allow instances of this class to be moved.
~NEIm2ColKernel ()=default
Default destructor.
void configure (const ITensor *input, ITensor *output, const Size2D &kernel_dims, const PadStrideInfo &conv_info, bool has_bias, const Size2D &dilation=Size2D(1U, 1U), unsigned int num_groups=1)
Set the input and output of the kernel.
void run (const Window &window, const ThreadInfo &info) override
Execute the kernel on the passed window.
Public Member Functions inherited from ICPPKernel
virtual ~ICPPKernel ()=default
Default destructor.
Public Member Functions inherited from IKernel
IKernel ()
Constructor.
virtual ~IKernel ()=default
Destructor.
virtual bool is_parallelisable () const
Indicates whether or not the kernel is parallelisable.
virtual BorderSize border_size () const
The size of the border for that kernel.
const Window & window () const
The maximum window the kernel can be executed on.
Static Public Member Functions
static Status validate (const ITensorInfo *input, const ITensorInfo *output, const Size2D &kernel_dims, const PadStrideInfo &conv_info, bool has_bias, const Size2D &dilation=Size2D(1U, 1U), unsigned int num_groups=1)
Static function to check if given info will lead to a valid configuration of NEIm2ColKernel.
Detailed Description
Interface for the im2col reshape kernel.
Rearranges image blocks into columns. It is used to strip out each convolution block to a single column. It is used to transform a convolution to a plain matrix multiplication.
For example taking into account the image below and assuming 3x3 image blocks with stride of 1 we have:
\[ \left(\begin{array}{cccc} a00 & a01 & a02 & a03 \\ a10 & a11 & a12 & a13 \\ a20 & a21 & a22 & a23 \\ a30 & a31 & a32 & a33 \\ \end{array} \right) \rightarrow \left(\begin{array}{ccccccccc} a00 & a01 & a02 & a10 & a11 & a12 & a20 & a21 & a22 \\ a01 & a02 & a03 & a11 & a12 & a13 & a21 & a22 & a23 \\ a10 & a11 & a12 & a20 & a21 & a22 & a30 & a31 & a32 \\ a11 & a12 & a13 & a21 & a22 & a23 & a31 & a32 & a33 \\ \end{array} \right) \]
Definition at line 57 of file NEIm2ColKernel.h.
Constructor & Destructor Documentation
NEIm2ColKernel() [1/3]
NEIm2ColKernel ()
Default constructor.
Definition at line 346 of file NEIm2ColKernel.cpp.
     : _func(), _input(nullptr), _output(nullptr), _convolved_dims(), _conv_info(), _kernel_width(0), _kernel_height(0), _has_bias(false), _dilation(1U, 1U)
 {
 }
NEIm2ColKernel() [2/3]
NEIm2ColKernel (const NEIm2ColKernel &) delete
Prevent instances of this class from being copied (As this class contains pointers)
NEIm2ColKernel() [3/3]
NEIm2ColKernel (NEIm2ColKernel &&) default
Allow instances of this class to be moved.
~NEIm2ColKernel()
~NEIm2ColKernel () default
Default destructor.
Member Function Documentation
configure()
void configure (const ITensor * input, ITensor * output, const Size2D & kernel_dims, const PadStrideInfo & conv_info, bool has_bias, const Size2D & dilation = Size2D(1U, 1U), unsigned int num_groups = 1)
Set the input and output of the kernel.
Parameters
[in] input The input tensor to convert. 3 lower dimensions represent a single input [width, height, IFM], while every optional dimension from 4 and above represent a batch of inputs. Data types supported: QASYMM8/F16/F32 Note: QASYMM8 works only for has_bias = false
[out] output The output tensor. Data types supported: Same as input
[in] kernel_dims The kernel dimensions (width and height).
[in] conv_info Contains padding and stride information described in PadStrideInfo.
[in] has_bias In case biases are provided expands the matrix with 1.
[in] dilation (Optional) Dilation, in elements, across x and y. Defaults to (1, 1).
[in] num_groups (Optional) Number of groups when performing a grouped convolution. num_groups != 1 is not supported
Definition at line 351 of file NEIm2ColKernel.cpp.
 {
     ARM_COMPUTE_ERROR_ON_NULLPTR(input, output);
     ARM_COMPUTE_ERROR_THROW_ON(validate_arguments(input->info(), output->info(), kernel_dims, conv_info, has_bias, dilation, num_groups));
     ARM_COMPUTE_UNUSED(num_groups);
     const DataLayout   data_layout = input->info()->data_layout();
     const unsigned int width_idx   = get_data_layout_dimension_index(data_layout, DataLayoutDimension::WIDTH);
     const unsigned int height_idx  = get_data_layout_dimension_index(data_layout, DataLayoutDimension::HEIGHT);
     _input          = input;
     _output         = output;
     _conv_info      = conv_info;
     _kernel_width   = kernel_dims.width;
     _kernel_height  = kernel_dims.height;
     _dilation       = dilation;
     _convolved_dims = scaled_dimensions(input->info()->dimension(width_idx), input->info()->dimension(height_idx),
                                         _kernel_width, _kernel_height,
                                         _conv_info, _dilation);
     _has_bias = has_bias;
     if(data_layout == DataLayout::NCHW)
     {
         switch(_input->info()->data_type())
         {
             case DataType::F32:
                 _func = (!conv_info.has_padding()) ? &NEIm2ColKernel::run_im2col<float, false, true> : &NEIm2ColKernel::run_im2col<float, true, true>;
                 break;
 #ifdef __ARM_FEATURE_FP16_VECTOR_ARITHMETIC
             case DataType::F16:
                 _func = (!conv_info.has_padding()) ? &NEIm2ColKernel::run_im2col<float16_t, false, true> : &NEIm2ColKernel::run_im2col<float16_t, true, true>;
                 break;
 #endif /* __ARM_FEATURE_FP16_VECTOR_ARITHMETIC */
             case DataType::QASYMM8:
                 _func = (!conv_info.has_padding()) ? &NEIm2ColKernel::run_im2col<qasymm8_t, false, true> : &NEIm2ColKernel::run_im2col<qasymm8_t, true, true>;
                 break;
             default:
                 ARM_COMPUTE_ERROR("Data type not supported");
                 break;
         }
     }
     else
     {
         switch(_input->info()->data_type())
         {
             case DataType::F32:
                 _func = (!conv_info.has_padding()) ? &NEIm2ColKernel::run_im2col<float, false, false> : &NEIm2ColKernel::run_im2col<float, true, false>;
                 break;
 #ifdef __ARM_FEATURE_FP16_VECTOR_ARITHMETIC
             case DataType::F16:
                 _func = (!conv_info.has_padding()) ? &NEIm2ColKernel::run_im2col<float16_t, false, false> : &NEIm2ColKernel::run_im2col<float16_t, true, false>;
                 break;
 #endif /* __ARM_FEATURE_FP16_VECTOR_ARITHMETIC */
             case DataType::QASYMM8:
                 _func = (!conv_info.has_padding()) ? &NEIm2ColKernel::run_im2col<qasymm8_t, false, false> : &NEIm2ColKernel::run_im2col<qasymm8_t, true, false>;
                 break;
             default:
                 ARM_COMPUTE_ERROR("Data type not supported");
                 break;
         }
     }
     // Configure kernel window
     auto win_config = validate_and_configure_window(input->info(), output->info(), kernel_dims, conv_info, has_bias, dilation);
     ARM_COMPUTE_ERROR_THROW_ON(win_config.first);
     INEKernel::configure(win_config.second);
 }
References ARM_COMPUTE_ERROR, ARM_COMPUTE_ERROR_ON_NULLPTR, ARM_COMPUTE_ERROR_THROW_ON, ARM_COMPUTE_UNUSED, arm_compute::test::validation::conv_info, arm_compute::test::validation::data_layout, ITensorInfo::data_layout(), ITensorInfo::data_type(), arm_compute::test::validation::dilation, ITensorInfo::dimension(), arm_compute::F16, arm_compute::F32, arm_compute::get_data_layout_dimension_index(), arm_compute::test::validation::has_bias, Size2D::height, arm_compute::HEIGHT, ITensor::info(), arm_compute::NCHW, arm_compute::test::validation::num_groups, arm_compute::QASYMM8, arm_compute::scaled_dimensions(), arm_compute::validate_and_configure_window(), Size2D::width, and arm_compute::WIDTH.
Referenced by NEIm2Col::configure(), NELocallyConnectedLayer::configure(), and NEGEMMConvolutionLayer::configure().
name()
const char* name () const inline override virtual
Name of the kernel.
Returns
Kernel name
Implements ICPPKernel.
Definition at line 60 of file NEIm2ColKernel.h.
     {
         return "NEIm2ColKernel";
     }
operator=() [1/2]
NEIm2ColKernel& operator= (const NEIm2ColKernel &) delete
Prevent instances of this class from being copied (As this class contains pointers)
operator=() [2/2]
NEIm2ColKernel& operator= (NEIm2ColKernel &&) default
Allow instances of this class to be moved.
run()
void run (const Window & window, const ThreadInfo & info) override virtual
Execute the kernel on the passed window.
Warning
If is_parallelisable() returns false then the passed window must be equal to window()
Note
The window has to be a region within the window returned by the window() method
The width of the window has to be a multiple of num_elems_processed_per_iteration().
Parameters
[in] window Region on which to execute the kernel. (Must be a region of the window returned by window())
[in] info Info about executing thread and CPU.
Implements ICPPKernel.
Definition at line 428 of file NEIm2ColKernel.cpp.
 {
     ARM_COMPUTE_UNUSED(info);
     ARM_COMPUTE_ERROR_ON_UNCONFIGURED_KERNEL(this);
     ARM_COMPUTE_ERROR_ON_INVALID_SUBWINDOW(INEKernel::window(), window);
     (this->*_func)(window);
 }
References ARM_COMPUTE_ERROR_ON_INVALID_SUBWINDOW, ARM_COMPUTE_ERROR_ON_UNCONFIGURED_KERNEL, ARM_COMPUTE_UNUSED, arm_compute::test::validation::info, and IKernel::window().
validate()
Status validate (const ITensorInfo * input, const ITensorInfo * output, const Size2D & kernel_dims, const PadStrideInfo & conv_info, bool has_bias, const Size2D & dilation = Size2D(1U, 1U), unsigned int num_groups = 1) static
Static function to check if given info will lead to a valid configuration of NEIm2ColKernel.
Parameters
[in] input The input tensor to convert. 3 lower dimensions represent a single input [width, height, IFM], while every optional dimension from 4 and above represent a batch of inputs. Data types supported: QASYMM8/F16/F32 Note: QASYMM8 works only for has_bias = false
[in] output The output tensor. Data types supported: Same as input
[in] kernel_dims The kernel dimensions (width and height).
[in] conv_info Contains padding and stride information described in PadStrideInfo.
[in] has_bias In case biases are provided expands the matrix with 1.
[in] dilation (Optional) Dilation, in elements, across x and y. Defaults to (1, 1).
[in] num_groups (Optional) Number of groups when performing a grouped convolution. num_groups != 1 is not supported
Returns
a status
Definition at line 420 of file NEIm2ColKernel.cpp.
 {
     ARM_COMPUTE_RETURN_ON_ERROR(validate_arguments(input, output, kernel_dims, conv_info, has_bias, dilation, num_groups));
     ARM_COMPUTE_RETURN_ON_ERROR(validate_and_configure_window(input->clone().get(), output->clone().get(), kernel_dims, conv_info, has_bias, dilation).first);
     return Status{};
 }
References ARM_COMPUTE_RETURN_ON_ERROR, ICloneable< T >::clone(), arm_compute::test::validation::conv_info, arm_compute::test::validation::dilation, arm_compute::test::validation::has_bias, arm_compute::test::validation::num_groups, and arm_compute::validate_and_configure_window().
Referenced by NEIm2Col::validate(), NELocallyConnectedLayer::validate(), and NEGEMMConvolutionLayer::validate().
The documentation for this class was generated from the following files:
arm_compute/core/NEON/kernels/NEIm2ColKernel.h
src/core/NEON/kernels/NEIm2ColKernel.cpp