Compute Library: NEGaussianPyramidVertKernel Class Reference
NEGaussianPyramidVertKernel Class Reference
NEON kernel to perform a GaussianPyramid (vertical pass)
#include <NEGaussianPyramidKernel.h>
Public Member Functions
const char * name () const override
Name of the kernel.
NEGaussianPyramidVertKernel ()
Default constructor.
NEGaussianPyramidVertKernel (NEGaussianPyramidVertKernel &)=delete
Prevent instances of this class from being copied (As this class contains pointers)
NEGaussianPyramidVertKernel & operator= (NEGaussianPyramidVertKernel &)=delete
Prevent instances of this class from being copied (As this class contains pointers)
NEGaussianPyramidVertKernel (NEGaussianPyramidVertKernel &&)=default
Allow instances of this class to be moved.
NEGaussianPyramidVertKernel & operator= (NEGaussianPyramidVertKernel &&)=default
Allow instances of this class to be moved.
~NEGaussianPyramidVertKernel ()=default
Default destructor.
void configure (const ITensor *input, ITensor *output)
Initialise the kernel's source, destination and border mode.
void run (const Window &window, const ThreadInfo &info) override
Execute the kernel on the passed window.
BorderSize border_size () const override
The size of the border for that kernel.
Public Member Functions inherited from ICPPSimpleKernel
ICPPSimpleKernel ()
Constructor.
ICPPSimpleKernel (const ICPPSimpleKernel &)=delete
Prevent instances of this class from being copied (As this class contains pointers)
ICPPSimpleKernel & operator= (const ICPPSimpleKernel &)=delete
Prevent instances of this class from being copied (As this class contains pointers)
ICPPSimpleKernel (ICPPSimpleKernel &&)=default
Allow instances of this class to be moved.
ICPPSimpleKernel & operator= (ICPPSimpleKernel &&)=default
Allow instances of this class to be moved.
~ICPPSimpleKernel ()=default
Default destructor.
Public Member Functions inherited from ICPPKernel
virtual ~ICPPKernel ()=default
Default destructor.
Public Member Functions inherited from IKernel
IKernel ()
Constructor.
virtual ~IKernel ()=default
Destructor.
virtual bool is_parallelisable () const
Indicates whether or not the kernel is parallelisable.
const Window & window () const
The maximum window the kernel can be executed on.
Detailed Description
NEON kernel to perform a GaussianPyramid (vertical pass)
Definition at line 70 of file NEGaussianPyramidKernel.h.
Constructor & Destructor Documentation
NEGaussianPyramidVertKernel() [1/3]
NEGaussianPyramidVertKernel ()
Default constructor.
Definition at line 151 of file NEGaussianPyramidKernel.cpp.
     : _t2_load_offset(0)
 {
 }
NEGaussianPyramidVertKernel() [2/3]
NEGaussianPyramidVertKernel (NEGaussianPyramidVertKernel &) delete
Prevent instances of this class from being copied (As this class contains pointers)
NEGaussianPyramidVertKernel() [3/3]
NEGaussianPyramidVertKernel (NEGaussianPyramidVertKernel &&) default
Allow instances of this class to be moved.
~NEGaussianPyramidVertKernel()
~NEGaussianPyramidVertKernel () default
Default destructor.
Member Function Documentation
border_size()
BorderSize border_size () const override virtual
The size of the border for that kernel.
Returns
The width in number of elements of the border.
Reimplemented from IKernel.
Definition at line 156 of file NEGaussianPyramidKernel.cpp.
 {
     return BorderSize{ 2, 0 };
 }
Referenced by NEGaussianPyramidVertKernel::configure().
configure()
void configure (const ITensor * input, ITensor * output)
Initialise the kernel's source, destination and border mode.
Parameters
[in] input Source tensor. Data type supported: S16.
[out] output Destination tensor. Output should have half the input height. Data type supported: U8.
Definition at line 161 of file NEGaussianPyramidKernel.cpp.
 {
     ARM_COMPUTE_ERROR_ON_DATA_TYPE_CHANNEL_NOT_IN(input, 1, DataType::S16);
     ARM_COMPUTE_ERROR_ON_DATA_TYPE_CHANNEL_NOT_IN(output, 1, DataType::U8);
     ARM_COMPUTE_ERROR_ON(input->info()->dimension(0) != output->info()->dimension(0));
     for(size_t i = 2; i < Coordinates::num_max_dimensions; ++i)
     {
         ARM_COMPUTE_ERROR_ON(input->info()->dimension(i) != output->info()->dimension(i));
     }
     _input  = input;
     _output = output;
     // Configure kernel window
     constexpr unsigned int num_elems_processed_per_iteration = 16;
     constexpr unsigned int num_rows_processed_per_iteration  = 2;
     constexpr unsigned int num_elems_written_per_iteration = 16;
     constexpr unsigned int num_rows_written_per_iteration  = 1;
     constexpr unsigned int num_elems_read_per_iteration = 16;
     constexpr unsigned int num_rows_read_per_iteration  = 5;
     const float scale_y = static_cast<float>(output->info()->dimension(1)) / input->info()->dimension(1);
     Window                win = calculate_max_window(*input->info(), Steps(num_elems_processed_per_iteration, num_rows_processed_per_iteration));
     AccessWindowRectangle output_access(output->info(), 0, 0, num_elems_written_per_iteration, num_rows_written_per_iteration, 1.f, scale_y);
     // Determine whether we need to load even or odd rows. See above for a
     // detailed explanation.
     _t2_load_offset = -border_size().top;
     if((_input->info()->valid_region().anchor[1] + _input->info()->valid_region().shape[1]) % 2 == 0)
     {
         _t2_load_offset += 1;
     }
     update_window_and_padding(win,
                               AccessWindowRectangle(input->info(), 0, _t2_load_offset, num_elems_read_per_iteration, num_rows_read_per_iteration),
                               output_access);
     output->info()->set_valid_region(ValidRegion(Coordinates(), output->info()->tensor_shape()));
     INEKernel::configure(win);
 }
References ARM_COMPUTE_ERROR_ON, ARM_COMPUTE_ERROR_ON_DATA_TYPE_CHANNEL_NOT_IN, NEGaussianPyramidVertKernel::border_size(), arm_compute::calculate_max_window(), ITensorInfo::dimension(), ITensor::info(), Dimensions< int >::num_max_dimensions, arm_compute::S16, ITensorInfo::set_valid_region(), ITensorInfo::tensor_shape(), BorderSize::top, arm_compute::U8, and arm_compute::update_window_and_padding().
name()
const char* name () const inline override virtual
Name of the kernel.
Returns
Kernel name
Implements ICPPKernel.
Definition at line 73 of file NEGaussianPyramidKernel.h.
     {
         return "NEGaussianPyramidVertKernel";
     }
operator=() [1/2]
NEGaussianPyramidVertKernel& operator= (NEGaussianPyramidVertKernel &) delete
Prevent instances of this class from being copied (As this class contains pointers)
operator=() [2/2]
NEGaussianPyramidVertKernel& operator= (NEGaussianPyramidVertKernel &&) default
Allow instances of this class to be moved.
run()
void run (const Window & window, const ThreadInfo & info) override virtual
Execute the kernel on the passed window.
Warning
If is_parallelisable() returns false then the passed window must be equal to window()
Note
The window has to be a region within the window returned by the window() method
The width of the window has to be a multiple of num_elems_processed_per_iteration().
Parameters
[in] window Region on which to execute the kernel. (Must be a region of the window returned by window())
[in] info Info about executing thread and CPU.
Implements ICPPKernel.
Definition at line 208 of file NEGaussianPyramidKernel.cpp.
 {
     ARM_COMPUTE_UNUSED(info);
     ARM_COMPUTE_ERROR_ON_UNCONFIGURED_KERNEL(this);
     ARM_COMPUTE_ERROR_ON_INVALID_SUBWINDOW(INEKernel::window(), window);
     ARM_COMPUTE_ERROR_ON(window.x().step() != 16);
     ARM_COMPUTE_ERROR_ON(window.y().step() % 2);
     ARM_COMPUTE_ERROR_ON(_input->buffer() == nullptr);
     static const uint16x8_t six  = vdupq_n_u16(6);
     static const uint16x8_t four = vdupq_n_u16(4);
     Window win_in(window);
     // Need to load two times 8 values instead of 16 values once
     win_in.set_dimension_step(Window::DimX, 8);
     win_in.shift(Window::DimY, _t2_load_offset);
     Iterator in(_input, win_in);
     // Output's height is half of input's
     Window win_out(window);
     win_out.scale(Window::DimY, 0.5f);
     Iterator out(_output, win_out);
     const uint8_t *input_top2_ptr = _input->buffer() + _input->info()->offset_element_in_bytes(Coordinates(0, 0));
     const uint8_t *input_top_ptr  = _input->buffer() + _input->info()->offset_element_in_bytes(Coordinates(0, 1));
     const uint8_t *input_mid_ptr  = _input->buffer() + _input->info()->offset_element_in_bytes(Coordinates(0, 2));
     const uint8_t *input_low_ptr  = _input->buffer() + _input->info()->offset_element_in_bytes(Coordinates(0, 3));
     const uint8_t *input_low2_ptr = _input->buffer() + _input->info()->offset_element_in_bytes(Coordinates(0, 4));
     execute_window_loop(window, [&](const Coordinates &)
     {
         // Low data
         const uint16x8_t data_low_t2 = vreinterpretq_u16_s16(vld1q_s16(reinterpret_cast<const int16_t *>(input_top2_ptr + in.offset())));
         const uint16x8_t data_low_t1 = vreinterpretq_u16_s16(vld1q_s16(reinterpret_cast<const int16_t *>(input_top_ptr + in.offset())));
         const uint16x8_t data_low_m  = vreinterpretq_u16_s16(vld1q_s16(reinterpret_cast<const int16_t *>(input_mid_ptr + in.offset())));
         const uint16x8_t data_low_b1 = vreinterpretq_u16_s16(vld1q_s16(reinterpret_cast<const int16_t *>(input_low_ptr + in.offset())));
         const uint16x8_t data_low_b2 = vreinterpretq_u16_s16(vld1q_s16(reinterpret_cast<const int16_t *>(input_low2_ptr + in.offset())));
         uint16x8_t out_low = vaddq_u16(data_low_t2, data_low_b2);
         out_low            = vmlaq_u16(out_low, data_low_t1, four);
         out_low            = vmlaq_u16(out_low, data_low_m, six);
         out_low            = vmlaq_u16(out_low, data_low_b1, four);
         in.increment(Window::DimX);
         // High data
         const uint16x8_t data_high_t2 = vreinterpretq_u16_s16(vld1q_s16(reinterpret_cast<const int16_t *>(input_top2_ptr + in.offset())));
         const uint16x8_t data_high_t1 = vreinterpretq_u16_s16(vld1q_s16(reinterpret_cast<const int16_t *>(input_top_ptr + in.offset())));
         const uint16x8_t data_high_m  = vreinterpretq_u16_s16(vld1q_s16(reinterpret_cast<const int16_t *>(input_mid_ptr + in.offset())));
         const uint16x8_t data_high_b1 = vreinterpretq_u16_s16(vld1q_s16(reinterpret_cast<const int16_t *>(input_low_ptr + in.offset())));
         const uint16x8_t data_high_b2 = vreinterpretq_u16_s16(vld1q_s16(reinterpret_cast<const int16_t *>(input_low2_ptr + in.offset())));
         uint16x8_t out_high = vaddq_u16(data_high_t2, data_high_b2);
         out_high            = vmlaq_u16(out_high, data_high_t1, four);
         out_high            = vmlaq_u16(out_high, data_high_m, six);
         out_high            = vmlaq_u16(out_high, data_high_b1, four);
         vst1q_u8(out.ptr(), vcombine_u8(vqshrn_n_u16(out_low, 8), vqshrn_n_u16(out_high, 8)));
     },
     in, out);
 }
References ARM_COMPUTE_ERROR_ON, ARM_COMPUTE_ERROR_ON_INVALID_SUBWINDOW, ARM_COMPUTE_ERROR_ON_UNCONFIGURED_KERNEL, ARM_COMPUTE_UNUSED, Window::DimX, Window::DimY, arm_compute::execute_window_loop(), Iterator::increment(), arm_compute::test::validation::info, Iterator::offset(), Iterator::ptr(), Window::scale(), Window::set_dimension_step(), Window::shift(), Window::Dimension::step(), IKernel::window(), Window::x(), and Window::y().
The documentation for this class was generated from the following files:
arm_compute/core/NEON/kernels/NEGaussianPyramidKernel.h
src/core/NEON/kernels/NEGaussianPyramidKernel.cpp