Compute Library: CLTensor Class Reference
CLTensor Class Reference
Basic implementation of the OpenCL tensor interface.
#include <CLTensor.h>
Public Member Functions
CLTensor ()
Constructor.
CLTensorAllocator * allocator ()
Return a pointer to the tensor's allocator.
void map (bool blocking=true)
Enqueue a map operation of the allocated buffer.
void unmap ()
Enqueue an unmap operation of the allocated and mapped buffer.
TensorInfo * info () const override
Interface to be implemented by the child class to return the tensor's metadata.
TensorInfo * info () override
Interface to be implemented by the child class to return the tensor's metadata.
const cl::Buffer & cl_buffer () const override
Interface to be implemented by the child class to return a reference to the OpenCL buffer containing the image's data.
CLQuantization quantization () const override
Interface to be implemented by the child class to return the wrapped quantization info data.
void map (cl::CommandQueue &q, bool blocking=true)
Enqueue a map operation of the allocated buffer on the given queue.
void unmap (cl::CommandQueue &q)
Enqueue an unmap operation of the allocated and mapped buffer on the given queue.
Public Member Functions inherited from ICLTensor
ICLTensor ()
Default constructor.
ICLTensor (const ICLTensor &)=delete
Prevent instances of this class from being copy constructed.
ICLTensor & operator= (const ICLTensor &)=delete
Prevent instances of this class from being copied.
ICLTensor (ICLTensor &&)=default
Allow instances of this class to be move constructed.
ICLTensor & operator= (ICLTensor &&)=default
Allow instances of this class to be copied.
virtual ~ICLTensor ()=default
Default virtual destructor.
void map (cl::CommandQueue &q, bool blocking=true)
Enqueue a map operation of the allocated buffer on the given queue.
void unmap (cl::CommandQueue &q)
Enqueue an unmap operation of the allocated and mapped buffer on the given queue.
void clear (cl::CommandQueue &q)
Clear the contents of the tensor synchronously.
uint8_t * buffer () const override
Interface to be implemented by the child class to return a pointer to CPU memory.
Public Member Functions inherited from ITensor
virtual ~ITensor ()=default
Default virtual destructor.
uint8_t * ptr_to_element (const Coordinates &id) const
Return a pointer to the element at the passed coordinates.
void copy_from (const ITensor &src)
Copy the content of another tensor.
void print (std::ostream &s, IOFormatInfo io_fmt=IOFormatInfo()) const
Print a tensor to a given stream using user defined formatting information.
bool is_used () const
Flags if the tensor is used or not.
void mark_as_unused () const
Marks a tensor as unused.
Detailed Description
Basic implementation of the OpenCL tensor interface.
Definition at line 40 of file CLTensor.h.
Constructor & Destructor Documentation
CLTensor()
CLTensor ()
Constructor.
Definition at line 30 of file CLTensor.cpp.
     : _allocator(this)
 {
 }
Member Function Documentation
allocator()
CLTensorAllocator * allocator ()
Return a pointer to the tensor's allocator.
Returns
A pointer to the tensor's allocator
Definition at line 55 of file CLTensor.cpp.
 {
     return &_allocator;
 }
Referenced by CLTensorHandle::allocate(), CLTensorHandle::CLTensorHandle(), CLRNNLayer::configure(), CLFFT2D::configure(), CLFFT1D::configure(), CLMeanStdDev::configure(), CLL2NormalizeLayer::configure(), CLHOGDescriptor::configure(), CLHOGGradient::configure(), CLGaussian5x5::configure(), CLSoftmaxLayer::configure(), CLSobel5x5::configure(), CLSobel7x7::configure(), CLCannyEdge::configure(), CLFastCorners::configure(), CLLocallyConnectedLayer::configure(), CLWinogradConvolutionLayer::configure(), CLDepthwiseConvolutionLayer3x3::configure(), CLHarrisCorners::configure(), CLHOGMultiDetection::configure(), CLGEMMLowpMatrixMultiplyCore::configure(), CLFFTConvolutionLayer::configure(), CLGenerateProposalsLayer::configure(), CLLSTMLayerQuantized::configure(), CLLSTMLayer::configure(), CLDirectDeconvolutionLayer::configure(), CLGEMMDeconvolutionLayer::configure(), CLFullyConnectedLayer::configure(), CLGEMMConvolutionLayer::configure(), CLDepthwiseConvolutionLayer::configure(), CLTensorHandle::free(), arm_compute::utils::init_sgemm_output(), CLLocallyConnectedLayer::prepare(), CLGEMMLowpMatrixMultiplyCore::prepare(), CLWinogradConvolutionLayer::prepare(), CLDepthwiseConvolutionLayer3x3::prepare(), CLGEMM::prepare(), CLFFTConvolutionLayer::prepare(), CLGEMMDeconvolutionLayer::prepare(), CLDirectDeconvolutionLayer::prepare(), CLFullyConnectedLayer::prepare(), CLLSTMLayerQuantized::prepare(), CLGEMMConvolutionLayer::prepare(), CLDepthwiseConvolutionLayer::prepare(), CLTensorHandle::release_if_unused(), CLFFTConvolutionLayer::run(), and arm_compute::test::validation::TEST_CASE().
cl_buffer()
const cl::Buffer & cl_buffer () const override virtual
Interface to be implemented by the child class to return a reference to the OpenCL buffer containing the image's data.
Returns
A reference to an OpenCL buffer containing the image's data.
Implements ICLTensor.
Definition at line 45 of file CLTensor.cpp.
 {
     return _allocator.cl_data();
 }
References CLTensorAllocator::cl_data().
Referenced by CLFastCorners::run(), and CLFFTConvolutionLayer::run().
info() [1/2]
TensorInfo * info () const override virtual
Interface to be implemented by the child class to return the tensor's metadata.
Returns
A pointer to the tensor's metadata.
Implements ITensor.
Definition at line 35 of file CLTensor.cpp.
 {
     return &_allocator.info();
 }
References ITensorAllocator::info().
Referenced by CLDepthwiseConvolutionLayer3x3NCHWKernel::configure(), CLDepthwiseConvolutionLayer3x3NHWCKernel::configure(), CLRNNLayer::configure(), CLDeconvolutionLayer::configure(), GCDepthwiseConvolutionLayer3x3Kernel::configure(), GCConvolutionLayerReshapeWeights::configure(), NEConvolutionLayerReshapeWeights::configure(), GCDirectConvolutionLayerKernel< kernel_size >::configure(), NERNNLayer::configure(), NEDepthwiseConvolutionLayer3x3Kernel::configure(), NEDepthwiseConvolutionLayerNativeKernel::configure(), CLDirectConvolutionLayerOutputStageKernel::configure(), CLConvolutionLayerReshapeWeights::configure(), NEDirectConvolutionLayerOutputStageKernel::configure(), CLGEMMLowpOffsetContributionOutputStageKernel::configure(), CLWinogradOutputTransformKernel::configure(), NEDirectConvolutionLayerKernel::configure(), GCDirectConvolutionLayer::configure(), NEDepthwiseConvolutionAssemblyDispatch::configure(), CLDeconvolutionReshapeOutputKernel::configure(), CLDirectConvolutionLayerKernel::configure(), CLGEMMLowpQuantizeDownInt32ToInt16ScaleByFixedPointKernel::configure(), CLGEMMLowpQuantizeDownInt32ToUint8ScaleByFloatKernel::configure(), CLGEMMLowpQuantizeDownInt32ToUint8ScaleByFixedPointKernel::configure(), CLGEMMLowpQuantizeDownInt32ToUint8ScaleKernel::configure(), CLGEMMLowpOffsetContributionKernel::configure(), NEWinogradConvolutionLayer::configure(), NEGEMMLowpQuantizeDownInt32ToInt16ScaleByFixedPointKernel::configure(), NELocallyConnectedLayer::configure(), CLLocallyConnectedLayer::configure(), CLWinogradConvolutionLayer::configure(), NEGEMMLowpQuantizeDownInt32ToUint8ScaleByFixedPointKernel::configure(), NEGEMMLowpQuantizeDownInt32ToUint8ScaleKernel::configure(), CLLaplacianReconstruct::configure(), CLDepthwiseConvolutionLayer3x3::configure(), NEDepthwiseConvolutionLayer3x3::configure(), GCFullyConnectedLayer::configure(), NEWeightsReshapeKernel::configure(), NEFFTConvolutionLayer::configure(), CLFFTConvolutionLayer::configure(), CLGenerateProposalsLayer::configure(), CLGaussianPyramidHalf::configure(), NEGEMMLowpOffsetContributionOutputStageKernel::configure(), CLConvolutionLayer::configure(), CLLSTMLayerQuantized::configure(), CLLSTMLayer::configure(), NEConvolutionLayer::configure(), CLDirectDeconvolutionLayer::configure(), CLGEMMDeconvolutionLayer::configure(), NEDeconvolutionLayer::configure(), NEFullyConnectedLayer::configure(), CLFullyConnectedLayer::configure(), GCConvolutionLayer::configure(), CLGaussianPyramidOrb::configure(), NEGEMMConvolutionLayer::configure(), CLGEMMConvolutionLayer::configure(), CLDepthwiseConvolutionLayer::configure(), NEDepthwiseConvolutionLayerOptimized::configure(), NEDepthwiseConvolutionLayer::configure(), arm_compute::graph::backends::detail::create_convolution_layer(), arm_compute::graph::backends::detail::create_convolution_layer< GCConvolutionLayerFunctions, GCTargetInfo >(), arm_compute::graph::backends::detail::create_convolution_layer< NEConvolutionLayerFunctions, NETargetInfo >(), arm_compute::graph::backends::detail::create_deconvolution_layer(), arm_compute::graph::backends::detail::create_depthwise_convolution_layer(), arm_compute::graph::backends::detail::create_depthwise_convolution_layer< GCDepthwiseConvolutionLayerFunctions, GCTargetInfo >(), arm_compute::graph::backends::detail::create_fully_connected_layer(), arm_compute::graph::backends::detail::create_fused_convolution_batch_normalization_layer(), arm_compute::graph::backends::detail::create_fused_depthwise_convolution_batch_normalization_layer(), CLAccessor::data_layout(), arm_compute::test::validation::DATA_TEST_CASE(), CLAccessor::data_type(), CLAccessor::element_size(), CLAccessor::format(), arm_compute::test::validation::if(), CLAccessor::num_channels(), CLAccessor::num_elements(), CLAccessor::padding(), CLAccessor::quantization_info(), CLFastCorners::run(), CLAccessor::shape(), CLAccessor::size(), and arm_compute::test::validation::TEST_CASE().
info() [2/2]
TensorInfo * info () override virtual
Interface to be implemented by the child class to return the tensor's metadata.
Returns
A pointer to the tensor's metadata.
Implements ITensor.
Definition at line 40 of file CLTensor.cpp.
 {
     return &_allocator.info();
 }
References ITensorAllocator::info().
map() [1/2]
void map (bool blocking = true)
Enqueue a map operation of the allocated buffer.
Parameters
[in] blocking If true, then the mapping will be ready to use by the time this method returns, else it is the caller's responsibility to flush the queue and wait for the mapping operation to have completed.
Definition at line 60 of file CLTensor.cpp.
 {
     ICLTensor::map(CLScheduler::get().queue(), blocking);
 }
References CLScheduler::get(), and ICLTensor::map().
Referenced by CLFFT1D::configure(), CLFFTConvolutionLayer::configure(), CLDirectDeconvolutionLayer::configure(), CLTensorHandle::map(), and CLHarrisCorners::run().
map() [2/2]
void map
Enqueue a map operation of the allocated buffer on the given queue.
Parameters
[in,out] q The CL command queue to use for the mapping operation.
[in] blocking If true, then the mapping will be ready to use by the time this method returns, else it is the caller's responsibility to flush the queue and wait for the mapping operation to have completed before using the returned mapping pointer.
Returns
The mapping address.
Definition at line 35 of file ICLTensor.cpp.
 {
     _mapping = do_map(q, blocking);
 }
quantization()
CLQuantization quantization () const override virtual
Interface to be implemented by the child class to return the wrapped quantization info data.
Returns
A wrapped quantization info object.
Implements ICLTensor.
Definition at line 50 of file CLTensor.cpp.
 {
     return _allocator.quantization();
 }
References CLTensorAllocator::quantization().
Referenced by arm_compute::test::validation::TEST_CASE().
unmap() [1/2]
void unmap ()
Enqueue an unmap operation of the allocated and mapped buffer.
Note
This method simply enqueues the unmap operation, it is the caller's responsibility to flush the queue and make sure the unmap is finished before the memory is accessed by the device.
Definition at line 65 of file CLTensor.cpp.
 {
     ICLTensor::unmap(CLScheduler::get().queue());
 }
References CLScheduler::get(), and ICLTensor::unmap().
Referenced by CLFFT1D::configure(), CLFFTConvolutionLayer::configure(), CLDirectDeconvolutionLayer::configure(), CLHarrisCorners::run(), CLTensorHandle::unmap(), and CLAccessor::~CLAccessor().
unmap() [2/2]
void unmap
Enqueue an unmap operation of the allocated and mapped buffer on the given queue.
Note
This method simply enqueues the unmap operation, it is the caller's responsibility to flush the queue and make sure the unmap is finished before the memory is accessed by the device.
Parameters
[in,out] q The CL command queue to use for the mapping operation.
Definition at line 40 of file ICLTensor.cpp.
 {
     do_unmap(q);
     _mapping = nullptr;
 }
The documentation for this class was generated from the following files:
arm_compute/runtime/CL/CLTensor.h
src/runtime/CL/CLTensor.cpp