Compute Library: IGCSimple2DKernel Class Reference
IGCSimple2DKernel Class Reference
Interface for simple OpenGL ES kernels having 1 tensor input and 1 tensor output.
#include <IGCSimple2DKernel.h>
Public Member Functions
void run (const Window &window) override
Enqueue the OpenGL ES shader to process the given window.
Public Member Functions inherited from IGCSimpleKernel
IGCSimpleKernel ()
Constructor.
IGCSimpleKernel (const IGCSimpleKernel &)=delete
Prevent instances of this class from being copied (As this class contains pointers)
IGCSimpleKernel & operator= (const IGCSimpleKernel &)=delete
Prevent instances of this class from being copied (As this class contains pointers)
IGCSimpleKernel (IGCSimpleKernel &&)=default
Allow instances of this class to be moved.
IGCSimpleKernel & operator= (IGCSimpleKernel &&)=default
Allow instances of this class to be moved.
~IGCSimpleKernel ()=default
Default destructor.
void configure (const IGCTensor *input, IGCTensor *output, unsigned int num_elems_processed_per_iteration, bool border_undefined=false, const BorderSize &border_size=BorderSize())
Configure the kernel.
Public Member Functions inherited from IGCKernel
IGCKernel ()
Constructor.
GCKernel & kernel ()
Returns a reference to the GLES kernel of this object.
void add_1D_tensor_argument (unsigned int &idx, const IGCTensor *tensor, const unsigned int binding_point, const Window &window)
Add the passed 1D tensor's parameters to the object's kernel's arguments starting from the index idx.
void add_2D_tensor_argument (unsigned int &idx, const IGCTensor *tensor, const unsigned int binding_point, const Window &window)
Add the passed 2D tensor's parameters to the object's kernel's arguments starting from the index idx.
void add_3D_tensor_argument (unsigned int &idx, const IGCTensor *tensor, const unsigned int binding_point, const Window &window)
Add the passed 3D tensor's parameters to the object's kernel's arguments starting from the index idx.
unsigned int num_arguments_per_1D_tensor () const
Returns the number of arguments enqueued per 1D tensor object.
unsigned int num_arguments_per_2D_tensor () const
Returns the number of arguments enqueued per 2D tensor object.
unsigned int num_arguments_per_3D_tensor () const
Returns the number of arguments enqueued per 3D tensor object.
void set_lws_hint (gles::NDRange &lws_hint)
Set the Local-Workgroup-Size hint.
void set_target (GPUTarget target)
Set the targeted GPU architecture.
GPUTarget get_target () const
Get the targeted GPU architecture.
Public Member Functions inherited from IKernel
IKernel ()
Constructor.
virtual ~IKernel ()=default
Destructor.
virtual bool is_parallelisable () const
Indicates whether or not the kernel is parallelisable.
virtual BorderSize border_size () const
The size of the border for that kernel.
const Window & window () const
The maximum window the kernel can be executed on.
Detailed Description
Interface for simple OpenGL ES kernels having 1 tensor input and 1 tensor output.
This interface can be used when the work-item processes a 2D tile
Definition at line 34 of file IGCSimple2DKernel.h.
Member Function Documentation
run()
void run (const Window & window) override virtual
Enqueue the OpenGL ES shader to process the given window.
Parameters
[in] window Region on which to execute the kernel. (Must be a valid region of the window returned by window()).
Implements IGCKernel.
Reimplemented in GCGEMMTranspose1xWKernel, GCScaleKernel, GCTransposeKernel, and IGCSimple3DKernel.
Definition at line 33 of file IGCSimple2DKernel.cpp.
 {
     ARM_COMPUTE_ERROR_ON_UNCONFIGURED_KERNEL(this);
     ARM_COMPUTE_ERROR_ON_INVALID_SUBWINDOW(IGCKernel::window(), window);
     _kernel.use();
     Window slice = window.first_slice_window_2D();
     do
     {
         unsigned int idx = 0;
         add_2D_tensor_argument(idx, _input, 1, slice);
         add_2D_tensor_argument(idx, _output, 2, slice);
         _kernel.update_shader_params();
         enqueue(*this, slice);
     }
     while(window.slide_window_slice_2D(slice));
 }
References IGCKernel::add_2D_tensor_argument(), ARM_COMPUTE_ERROR_ON_INVALID_SUBWINDOW, ARM_COMPUTE_ERROR_ON_UNCONFIGURED_KERNEL, arm_compute::enqueue(), Window::first_slice_window_2D(), arm_compute::test::validation::reference::slice(), Window::slide_window_slice_2D(), and IKernel::window().
The documentation for this class was generated from the following files:
arm_compute/core/GLES_COMPUTE/IGCSimple2DKernel.h
src/core/GLES_COMPUTE/IGCSimple2DKernel.cpp