Compute Library: CLMinMaxKernel Class Reference
CLMinMaxKernel Class Reference
Interface for the kernel to perform min max search on an image.
#include <CLMinMaxLocationKernel.h>
Public Member Functions
CLMinMaxKernel ()
Default constructor.
CLMinMaxKernel (const CLMinMaxKernel &)=delete
Prevent instances of this class from being copied (As this class contains pointers)
CLMinMaxKernel & operator= (const CLMinMaxKernel &)=delete
Prevent instances of this class from being copied (As this class contains pointers)
CLMinMaxKernel (CLMinMaxKernel &&)=default
Allow instances of this class to be moved.
CLMinMaxKernel & operator= (CLMinMaxKernel &&)=default
Allow instances of this class to be moved.
void configure (const ICLImage *input, cl::Buffer *min_max)
Initialise the kernel's input and output.
void run (const Window &window, cl::CommandQueue &queue) override
Enqueue the OpenCL kernel to process the given window on the passed OpenCL command queue.
Public Member Functions inherited from ICLKernel
ICLKernel ()
Constructor.
cl::Kernel & kernel ()
Returns a reference to the OpenCL kernel of this object.
template<typename T >
void add_1D_array_argument (unsigned int &idx, const ICLArray< T > *array, const Strides &strides, unsigned int num_dimensions, const Window &window)
Add the passed 1D array's parameters to the object's kernel's arguments starting from the index idx.
void add_1D_tensor_argument (unsigned int &idx, const ICLTensor *tensor, const Window &window)
Add the passed 1D tensor's parameters to the object's kernel's arguments starting from the index idx.
void add_1D_tensor_argument_if (bool cond, unsigned int &idx, const ICLTensor *tensor, const Window &window)
Add the passed 1D tensor's parameters to the object's kernel's arguments starting from the index idx if the condition is true.
void add_2D_tensor_argument (unsigned int &idx, const ICLTensor *tensor, const Window &window)
Add the passed 2D tensor's parameters to the object's kernel's arguments starting from the index idx.
void add_2D_tensor_argument_if (bool cond, unsigned int &idx, const ICLTensor *tensor, const Window &window)
Add the passed 2D tensor's parameters to the object's kernel's arguments starting from the index idx if the condition is true.
void add_3D_tensor_argument (unsigned int &idx, const ICLTensor *tensor, const Window &window)
Add the passed 3D tensor's parameters to the object's kernel's arguments starting from the index idx.
void add_4D_tensor_argument (unsigned int &idx, const ICLTensor *tensor, const Window &window)
Add the passed 4D tensor's parameters to the object's kernel's arguments starting from the index idx.
template<typename T >
void add_argument (unsigned int &idx, T value)
Add the passed parameters to the object's kernel's arguments starting from the index idx.
void set_lws_hint (const cl::NDRange &lws_hint)
Set the Local-Workgroup-Size hint.
cl::NDRange lws_hint () const
Return the Local-Workgroup-Size hint.
const std::string & config_id () const
Get the configuration ID.
void set_target (GPUTarget target)
Set the targeted GPU architecture.
void set_target (cl::Device &device)
Set the targeted GPU architecture according to the CL device.
GPUTarget get_target () const
Get the targeted GPU architecture.
size_t get_max_workgroup_size ()
Get the maximum workgroup size for the device the CLKernelLibrary uses.
template<typename T , unsigned int dimension_size>
void add_array_argument (unsigned &idx, const ICLArray< T > *array, const Strides &strides, unsigned int num_dimensions, const Window &window)
Add the passed array's parameters to the object's kernel's arguments starting from the index idx.
template<unsigned int dimension_size>
void add_tensor_argument (unsigned &idx, const ICLTensor *tensor, const Window &window)
Public Member Functions inherited from IKernel
IKernel ()
Constructor.
virtual ~IKernel ()=default
Destructor.
virtual bool is_parallelisable () const
Indicates whether or not the kernel is parallelisable.
virtual BorderSize border_size () const
The size of the border for that kernel.
const Window & window () const
The maximum window the kernel can be executed on.
Additional Inherited Members
Static Public Member Functions inherited from ICLKernel
static constexpr unsigned int num_arguments_per_1D_array ()
Returns the number of arguments enqueued per 1D array object.
static constexpr unsigned int num_arguments_per_1D_tensor ()
Returns the number of arguments enqueued per 1D tensor object.
static constexpr unsigned int num_arguments_per_2D_tensor ()
Returns the number of arguments enqueued per 2D tensor object.
static constexpr unsigned int num_arguments_per_3D_tensor ()
Returns the number of arguments enqueued per 3D tensor object.
static constexpr unsigned int num_arguments_per_4D_tensor ()
Returns the number of arguments enqueued per 4D tensor object.
static cl::NDRange gws_from_window (const Window &window)
Get the global work size given an execution window.
Detailed Description
Interface for the kernel to perform min max search on an image.
Definition at line 39 of file CLMinMaxLocationKernel.h.
Constructor & Destructor Documentation
CLMinMaxKernel() [1/3]
CLMinMaxKernel ()
Default constructor.
Definition at line 57 of file CLMinMaxLocationKernel.cpp.
     : _input(nullptr), _min_max(), _data_type_max_min()
 {
 }
CLMinMaxKernel() [2/3]
CLMinMaxKernel (const CLMinMaxKernel &) delete
Prevent instances of this class from being copied (As this class contains pointers)
CLMinMaxKernel() [3/3]
CLMinMaxKernel (CLMinMaxKernel &&) default
Allow instances of this class to be moved.
Member Function Documentation
configure()
void configure (const ICLImage * input, cl::Buffer * min_max)
Initialise the kernel's input and output.
Parameters
[in] input Input Image. Data types supported: U8/S16/F32.
[out] min_max Buffer of 2 elements to store the min value at position 0 and the max value at position 1. Data type supported: S32 if input type is U8/S16, F32 if input type is F32.
Definition at line 62 of file CLMinMaxLocationKernel.cpp.
 {
     ARM_COMPUTE_ERROR_ON_DATA_TYPE_CHANNEL_NOT_IN(input, 1, DataType::U8, DataType::S16, DataType::F32);
     ARM_COMPUTE_ERROR_ON_TENSOR_NOT_2D(input);
     ARM_COMPUTE_ERROR_ON(min_max == nullptr);
     _input                                               = input;
     _min_max                                             = min_max;
     const unsigned int num_elems_processed_per_iteration = input->info()->dimension(0);
     switch(input->info()->data_type())
     {
         case DataType::U8:
             _data_type_max_min[0] = UCHAR_MAX;
             _data_type_max_min[1] = 0;
             break;
         case DataType::S16:
             _data_type_max_min[0] = SHRT_MAX;
             _data_type_max_min[1] = SHRT_MIN;
             break;
         case DataType::F32:
             _data_type_max_min[0] = FloatFlip(std::numeric_limits<float>::max());
             _data_type_max_min[1] = FloatFlip(std::numeric_limits<float>::lowest());
             break;
         default:
             ARM_COMPUTE_ERROR("You called with the wrong image data types");
     }
     // Set kernel build options
     std::set<std::string> build_opts{ "-DDATA_TYPE=" + get_cl_type_from_data_type(input->info()->data_type()) };
     if(num_elems_processed_per_iteration % max_cl_vector_width != 0)
     {
         build_opts.emplace("-DNON_MULTIPLE_OF_16");
     }
     if(input->info()->data_type() == DataType::F32)
     {
         build_opts.emplace("-DDATA_TYPE_MAX=" + support::cpp11::to_string(std::numeric_limits<float>::max()));
         build_opts.emplace("-DDATA_TYPE_MIN=" + support::cpp11::to_string(std::numeric_limits<float>::lowest()));
         build_opts.emplace("-DIS_DATA_TYPE_FLOAT");
     }
     else
     {
         build_opts.emplace("-DDATA_TYPE_MAX=" + support::cpp11::to_string(_data_type_max_min[0]));
         build_opts.emplace("-DDATA_TYPE_MIN=" + support::cpp11::to_string(_data_type_max_min[1]));
     }
     // Create kernel
     _kernel = static_cast<cl::Kernel>(CLKernelLibrary::get().create_kernel("minmax", build_opts));
     // Set fixed arguments
     unsigned int idx = num_arguments_per_2D_tensor(); //Skip the input and output parameters
     _kernel.setArg(idx++, *_min_max);
     _kernel.setArg<cl_int>(idx++, static_cast<cl_int>(input->info()->dimension(0)));
     // Configure kernel window
     Window win = calculate_max_window(*input->info(), Steps(num_elems_processed_per_iteration));
     update_window_and_padding(win, AccessWindowHorizontal(input->info(), 0, ceil_to_multiple(num_elems_processed_per_iteration, 16)));
     ICLKernel::configure_internal(win);
 }
References ARM_COMPUTE_ERROR, ARM_COMPUTE_ERROR_ON, ARM_COMPUTE_ERROR_ON_DATA_TYPE_CHANNEL_NOT_IN, ARM_COMPUTE_ERROR_ON_TENSOR_NOT_2D, arm_compute::calculate_max_window(), arm_compute::ceil_to_multiple(), arm_compute::create_kernel(), ITensorInfo::data_type(), ITensorInfo::dimension(), arm_compute::F32, arm_compute::FloatFlip(), CLKernelLibrary::get(), arm_compute::get_cl_type_from_data_type(), ITensor::info(), arm_compute::support::cpp11::lowest(), ICLKernel::num_arguments_per_2D_tensor(), arm_compute::S16, arm_compute::support::cpp11::to_string(), arm_compute::U8, and arm_compute::update_window_and_padding().
Referenced by CLMinMaxLocation::configure().
operator=() [1/2]
CLMinMaxKernel& operator= (const CLMinMaxKernel &) delete
Prevent instances of this class from being copied (As this class contains pointers)
operator=() [2/2]
CLMinMaxKernel& operator= (CLMinMaxKernel &&) default
Allow instances of this class to be moved.
run()
void run (const Window & window, cl::CommandQueue & queue) override virtual
Enqueue the OpenCL kernel to process the given window on the passed OpenCL command queue.
Note
The queue is not flushed by this method, and therefore the kernel will not have been executed by the time this method returns.
Parameters
[in] window Region on which to execute the kernel. (Must be a valid region of the window returned by window()).
[in,out] queue Command queue on which to enqueue the kernel.
Implements ICLKernel.
Definition at line 124 of file CLMinMaxLocationKernel.cpp.
 {
     ARM_COMPUTE_ERROR_ON_UNCONFIGURED_KERNEL(this);
     ARM_COMPUTE_ERROR_ON_INVALID_SUBWINDOW(IKernel::window(), window);
     // Reset mininum and maximum values
     queue.enqueueWriteBuffer(*_min_max, CL_FALSE /* blocking */, 0, _data_type_max_min.size() * sizeof(int), _data_type_max_min.data());
     Window slice = window.first_slice_window_2D();
     do
     {
         unsigned int idx = 0;
         add_2D_tensor_argument(idx, _input, slice);
         enqueue(queue, *this, slice);
     }
     while(window.slide_window_slice_2D(slice));
     cl_int min = 0;
     cl_int max = 0;
     queue.enqueueReadBuffer(*_min_max, CL_TRUE /* blocking */, 0 * sizeof(cl_int), sizeof(cl_int), static_cast<int *>(&min));
     queue.enqueueReadBuffer(*_min_max, CL_TRUE /* blocking */, 1 * sizeof(cl_int), sizeof(cl_int), static_cast<int *>(&max));
     if(_input->info()->data_type() == DataType::F32)
     {
         std::array<float, 2> min_max =
         {
             {
                 IFloatFlip(min),
                 IFloatFlip(max)
             }
         };
         queue.enqueueWriteBuffer(*_min_max, CL_TRUE /* blocking */, 0, min_max.size() * sizeof(float), min_max.data());
     }
     else
     {
         std::array<int32_t, 2> min_max = { { min, max } };
         queue.enqueueWriteBuffer(*_min_max, CL_TRUE /* blocking */, 0, min_max.size() * sizeof(int32_t), min_max.data());
     }
 }
References ICLKernel::add_2D_tensor_argument(), ARM_COMPUTE_ERROR_ON_INVALID_SUBWINDOW, ARM_COMPUTE_ERROR_ON_UNCONFIGURED_KERNEL, ITensorInfo::data_type(), arm_compute::enqueue(), arm_compute::F32, Window::first_slice_window_2D(), arm_compute::IFloatFlip(), ITensor::info(), arm_compute::test::validation::reference::slice(), Window::slide_window_slice_2D(), and IKernel::window().
The documentation for this class was generated from the following files:
arm_compute/core/CL/kernels/CLMinMaxLocationKernel.h
src/core/CL/kernels/CLMinMaxLocationKernel.cpp