Compute Library: CPPUpsampleKernel Class Reference
CPPUpsampleKernel Class Reference
CPP kernel to perform tensor upsample.
#include <CPPUpsampleKernel.h>
Public Member Functions
const char * name () const override
Name of the kernel.
CPPUpsampleKernel ()
Default constructor.
CPPUpsampleKernel (const CPPUpsampleKernel &)=delete
Prevent instances of this class from being copied (As this class contains pointers)
CPPUpsampleKernel & operator= (const CPPUpsampleKernel &)=delete
Prevent instances of this class from being copied (As this class contains pointers)
CPPUpsampleKernel (CPPUpsampleKernel &&)=default
Allow instances of this class to be moved.
CPPUpsampleKernel & operator= (CPPUpsampleKernel &&)=default
Allow instances of this class to be moved.
~CPPUpsampleKernel ()=default
Default destructor.
void configure (const ITensor *input, ITensor *output, const PadStrideInfo &info)
Set the input and output of the kernel.
void run (const Window &window, const ThreadInfo &info) override
Execute the kernel on the passed window.
bool is_parallelisable () const override
Indicates whether or not the kernel is parallelisable.
Public Member Functions inherited from ICPPKernel
virtual ~ICPPKernel ()=default
Default destructor.
Public Member Functions inherited from IKernel
IKernel ()
Constructor.
virtual ~IKernel ()=default
Destructor.
virtual BorderSize border_size () const
The size of the border for that kernel.
const Window & window () const
The maximum window the kernel can be executed on.
Detailed Description
CPP kernel to perform tensor upsample.
Definition at line 36 of file CPPUpsampleKernel.h.
Constructor & Destructor Documentation
CPPUpsampleKernel() [1/3]
CPPUpsampleKernel ()
Default constructor.
Definition at line 39 of file CPPUpsampleKernel.cpp.
     : _input(nullptr), _output(nullptr), _info()
 {
 }
CPPUpsampleKernel() [2/3]
CPPUpsampleKernel (const CPPUpsampleKernel &) delete
Prevent instances of this class from being copied (As this class contains pointers)
CPPUpsampleKernel() [3/3]
CPPUpsampleKernel (CPPUpsampleKernel &&) default
Allow instances of this class to be moved.
~CPPUpsampleKernel()
~CPPUpsampleKernel () default
Default destructor.
Member Function Documentation
configure()
void configure (const ITensor * input, ITensor * output, const PadStrideInfo & info)
Set the input and output of the kernel.
Parameters
[in] input The input tensor to upsample. Data types supported: F32/F16/QASYMM8
[out] output The output tensor. Data types supported: Same as input
[in] info Padding info.
Definition at line 49 of file CPPUpsampleKernel.cpp.
 {
     ARM_COMPUTE_ERROR_ON_NULLPTR(input, output);
     _input  = input;
     _output = output;
     _info   = info;
     // Configure kernel window
     Window win = calculate_max_window(*input->info(), Steps());
     // The CPPUpsampleKernel doesn't need padding so update_window_and_padding() can be skipped
     Coordinates coord;
     coord.set_num_dimensions(output->info()->num_dimensions());
     output->info()->set_valid_region(ValidRegion(coord, output->info()->tensor_shape()));
     ICPPKernel::configure(win);
 }
References ARM_COMPUTE_ERROR_ON_NULLPTR, arm_compute::calculate_max_window(), ITensor::info(), arm_compute::test::validation::info, ITensorInfo::num_dimensions(), Dimensions< T >::set_num_dimensions(), ITensorInfo::set_valid_region(), and ITensorInfo::tensor_shape().
is_parallelisable()
bool is_parallelisable () const override virtual
Indicates whether or not the kernel is parallelisable.
If the kernel is parallelisable then the window returned by window() can be split into sub-windows which can then be run in parallel.
If the kernel is not parallelisable then only the window returned by window() can be passed to run()
Returns
True if the kernel is parallelisable
Reimplemented from IKernel.
Definition at line 44 of file CPPUpsampleKernel.cpp.
 {
     return false;
 }
name()
const char* name () const inline override virtual
Name of the kernel.
Returns
Kernel name
Implements ICPPKernel.
Definition at line 39 of file CPPUpsampleKernel.h.
     {
         return "CPPUpsampleKernel";
     }
operator=() [1/2]
CPPUpsampleKernel& operator= (const CPPUpsampleKernel &) delete
Prevent instances of this class from being copied (As this class contains pointers)
operator=() [2/2]
CPPUpsampleKernel& operator= (CPPUpsampleKernel &&) default
Allow instances of this class to be moved.
run()
void run (const Window & window, const ThreadInfo & info) override virtual
Execute the kernel on the passed window.
Warning
If is_parallelisable() returns false then the passed window must be equal to window()
Note
The window has to be a region within the window returned by the window() method
The width of the window has to be a multiple of num_elems_processed_per_iteration().
Parameters
[in] window Region on which to execute the kernel. (Must be a region of the window returned by window())
[in] info Info about executing thread and CPU.
Implements ICPPKernel.
Definition at line 68 of file CPPUpsampleKernel.cpp.
 {
     ARM_COMPUTE_UNUSED(info);
     ARM_COMPUTE_ERROR_ON_UNCONFIGURED_KERNEL(this);
     ARM_COMPUTE_ERROR_ON_INVALID_SUBWINDOW(ICPPKernel::window(), window);
     // Initialize _scaled_output buffer
     const int    width_scaled  = _output->info()->dimension(0);
     const int    height_scaled = _output->info()->dimension(1);
     const int    stride_x      = _info.stride().first;
     const int    stride_y      = _info.stride().second;
     const int    start_x       = _info.pad().first;
     const int    start_y       = _info.pad().second;
     const int    end_y         = height_scaled - _info.pad().second;
     const int    end_x         = width_scaled - _info.pad().first;
     const size_t element_size  = _input->info()->element_size();
     //The fill value is normally 0, but for QASYMM8 the '0' corresponds to the offset
     const uint8_t fill_value = _output->info()->data_type() == DataType::QASYMM8 ? utility::clamp<uint8_t>(_output->info()->quantization_info().uniform().offset) : 0;
     //Filling a value different than 0 works only for QASYMM8 datatype since we are filling 1byte values in a buffer of uint8_ts
     std::fill_n(_output->buffer(), _output->info()->total_size(), fill_value);
     // Create window
     Window window_out(window);
     window_out.set(Window::DimX, Window::Dimension(start_x, end_x, stride_x));
     window_out.set(Window::DimY, Window::Dimension(start_y, end_y, stride_y));
     // Create iterators
     Iterator in(_input, window);
     Iterator out(_output, window_out);
     execute_window_loop(window, [&](const Coordinates &)
     {
         memcpy(out.ptr(), in.ptr(), element_size);
     },
     in, out);
 }
References ARM_COMPUTE_ERROR_ON_INVALID_SUBWINDOW, ARM_COMPUTE_ERROR_ON_UNCONFIGURED_KERNEL, ARM_COMPUTE_UNUSED, ITensor::buffer(), ITensorInfo::data_type(), ITensorInfo::dimension(), Window::DimX, Window::DimY, ITensorInfo::element_size(), arm_compute::execute_window_loop(), ITensor::info(), arm_compute::test::validation::info, UniformQuantizationInfo::offset, PadStrideInfo::pad(), Iterator::ptr(), arm_compute::QASYMM8, ITensorInfo::quantization_info(), PadStrideInfo::stride(), ITensorInfo::total_size(), QuantizationInfo::uniform(), and IKernel::window().
The documentation for this class was generated from the following files:
arm_compute/core/CPP/kernels/CPPUpsampleKernel.h
src/core/CPP/kernels/CPPUpsampleKernel.cpp