Compute Library: LutAccessor< T > Class Template Reference
LutAccessor< T > Class Template Reference
Accessor implementation for Lut objects.
#include <LutAccessor.h>
Public Member Functions
LutAccessor (Lut &lut)
Create an accessor for the given Lut.
LutAccessor (const LutAccessor &)=delete
Prevent instances of this class from being copy constructed.
LutAccessor & operator= (const LutAccessor &)=delete
Prevent instances of this class from being copied.
LutAccessor (LutAccessor &&)=default
Allow instances of this class to be move constructed.
LutAccessor & operator= (LutAccessor &&)=default
Allow instances of this class to be moved.
int num_elements () const override
Number of elements of the Lut.
const T & operator[] (T input_value) const override
Read access to the specified element.
T & operator[] (T input_value) override
Write access to the specified element.
Public Member Functions inherited from ILutAccessor< T >
virtual ~ILutAccessor ()=default
Pure virtual destructor.
Additional Inherited Members
Public Types inherited from ILutAccessor< T >
using value_type = T
Lut value type.
Detailed Description
template<typename T>
class arm_compute::test::LutAccessor< T >
Accessor implementation for Lut objects.
Definition at line 37 of file LutAccessor.h.
Constructor & Destructor Documentation
LutAccessor() [1/3]
LutAccessor (Lut & lut) inline
Create an accessor for the given Lut.
Definition at line 42 of file LutAccessor.h.
         : _lut{ lut }
     {
     }
LutAccessor() [2/3]
LutAccessor (const LutAccessor< T > &) delete
Prevent instances of this class from being copy constructed.
LutAccessor() [3/3]
LutAccessor (LutAccessor< T > &&) default
Allow instances of this class to be move constructed.
Member Function Documentation
num_elements()
int num_elements () const inline override virtual
Number of elements of the Lut.
Returns
the number of elements.
Implements ILutAccessor< T >.
Definition at line 56 of file LutAccessor.h.
     {
         return _lut.num_elements();
     }
References ILut::num_elements().
Referenced by LutAccessor< T >::operator[]().
operator=() [1/2]
LutAccessor& operator= (const LutAccessor< T > &) delete
Prevent instances of this class from being copied.
operator=() [2/2]
LutAccessor& operator= (LutAccessor< T > &&) default
Allow instances of this class to be moved.
operator[]() [1/2]
const T& operator[] (T input_value) const inline override virtual
Read access to the specified element.
Parameters
[in] input_value Lut input value, from numericlimits<T>:min to numericlimits<T>:max.
Returns
Output desired element.
Implements ILutAccessor< T >.
Definition at line 61 of file LutAccessor.h.
     {
         auto    lut        = reinterpret_cast<T *>(_lut.buffer());
         int32_t real_index = _lut.index_offset() + static_cast<int32_t>(input_value);
         if(0 <= real_index && real_index < num_elements())
         {
             return lut[real_index];
         }
         ARM_COMPUTE_ERROR("Error index not in range.");
     }
References ARM_COMPUTE_ERROR, ILut::buffer(), ILut::index_offset(), and LutAccessor< T >::num_elements().
operator[]() [2/2]
T& operator[] (T input_value) inline override virtual
Write access to the specified element.
Parameters
[in] input_value Lut input value, from numericlimits<T>:min to numericlimits<T>:max.
Returns
Output desired element.
Implements ILutAccessor< T >.
Definition at line 73 of file LutAccessor.h.
     {
         auto    lut        = reinterpret_cast<T *>(_lut.buffer());
         int32_t real_index = _lut.index_offset() + static_cast<int32_t>(input_value);
         if(0 <= real_index && real_index < num_elements())
         {
             return lut[real_index];
         }
         ARM_COMPUTE_ERROR("Error index not in range.");
     }
References ARM_COMPUTE_ERROR, ILut::buffer(), ILut::index_offset(), and LutAccessor< T >::num_elements().
The documentation for this class was generated from the following file:
tests/NEON/LutAccessor.h