Compute Library: IGCMemoryRegion Class Reference
IGCMemoryRegion Class Reference abstract
GLES memory region interface.
#include <GCMemoryRegion.h>
Public Member Functions
IGCMemoryRegion (size_t size)
Constructor.
virtual ~IGCMemoryRegion ()=default
Default Destructor.
IGCMemoryRegion (const IGCMemoryRegion &)=delete
Prevent instances of this class from being copied (As this class contains pointers)
IGCMemoryRegion (IGCMemoryRegion &&)=default
Default move constructor.
IGCMemoryRegion & operator= (const IGCMemoryRegion &)=delete
Prevent instances of this class from being copied (As this class contains pointers)
IGCMemoryRegion & operator= (IGCMemoryRegion &&)=default
Default move assignment operator.
const GLuint & gc_ssbo_name () const
Returns the underlying CL buffer.
virtual void * ptr ()=0
Host/SVM pointer accessor.
virtual void * map (bool blocking)=0
Enqueue a map operation of the allocated buffer on the given queue.
virtual void unmap ()=0
Enqueue an unmap operation of the allocated buffer on the given queue.
void * buffer () override
Returns the pointer to the allocated data.
void * buffer () const override
Returns the pointer to the allocated data.
Public Member Functions inherited from IMemoryRegion
IMemoryRegion (size_t size)
Default constructor.
virtual ~IMemoryRegion ()=default
Virtual Destructor.
virtual std::unique_ptr< IMemoryRegion > extract_subregion (size_t offset, size_t size)=0
Extract a sub-region from the memory.
size_t size () const
Memory region size accessor.
void set_size (size_t size)
Sets size of region.
Detailed Description
GLES memory region interface.
Definition at line 35 of file GCMemoryRegion.h.
Constructor & Destructor Documentation
IGCMemoryRegion() [1/3]
IGCMemoryRegion (size_t size)
Constructor.
Parameters
[in] size Region size
Definition at line 30 of file GCMemoryRegion.cpp.
     : IMemoryRegion(size), _mapping(nullptr), _ssbo_name(0)
 {
 }
~IGCMemoryRegion()
virtual ~IGCMemoryRegion () virtual default
Default Destructor.
IGCMemoryRegion() [2/3]
IGCMemoryRegion (const IGCMemoryRegion &) delete
Prevent instances of this class from being copied (As this class contains pointers)
IGCMemoryRegion() [3/3]
IGCMemoryRegion (IGCMemoryRegion &&) default
Default move constructor.
Member Function Documentation
buffer() [1/2]
void * buffer () override virtual
Returns the pointer to the allocated data.
Returns
Pointer to the allocated data
Implements IMemoryRegion.
Definition at line 40 of file GCMemoryRegion.cpp.
 {
     return _mapping;
 }
buffer() [2/2]
void * buffer () const override virtual
Returns the pointer to the allocated data.
Returns
Pointer to the allocated data
Implements IMemoryRegion.
Definition at line 45 of file GCMemoryRegion.cpp.
 {
     return _mapping;
 }
gc_ssbo_name()
const GLuint & gc_ssbo_name () const
Returns the underlying CL buffer.
Returns
CL memory buffer object
Definition at line 35 of file GCMemoryRegion.cpp.
 {
     return _ssbo_name;
 }
Referenced by GCTensorAllocator::get_gl_ssbo_name(), and GCTensorAllocator::set_associated_memory_group().
map()
virtual void* map (bool blocking) pure virtual
Enqueue a map operation of the allocated buffer on the given queue.
Parameters
[in] blocking If true, then the mapping will be ready to use by the time this method returns, else it is the caller's responsibility to flush the queue and wait for the mapping operation to have completed before using the returned mapping pointer.
Returns
The mapping address.
Implemented in GCBufferMemoryRegion.
Referenced by GCTensorAllocator::map().
operator=() [1/2]
IGCMemoryRegion& operator= (const IGCMemoryRegion &) delete
Prevent instances of this class from being copied (As this class contains pointers)
operator=() [2/2]
IGCMemoryRegion& operator= (IGCMemoryRegion &&) default
Default move assignment operator.
ptr()
virtual void* ptr () pure virtual
Host/SVM pointer accessor.
Returns
Host/SVM pointer base
Implemented in GCBufferMemoryRegion.
unmap()
virtual void unmap () pure virtual
Enqueue an unmap operation of the allocated buffer on the given queue.
Note
This method simply enqueue the unmap operation, it is the caller's responsibility to flush the queue and make sure the unmap is finished before the memory is accessed by the device.
Implemented in GCBufferMemoryRegion.
Referenced by GCTensorAllocator::unmap().
The documentation for this class was generated from the following files:
arm_compute/runtime/GLES_COMPUTE/GCMemoryRegion.h
src/runtime/GLES_COMPUTE/GCMemoryRegion.cpp