Compute Library: GCGEMMMatrixAdditionKernel Class Reference
GCGEMMMatrixAdditionKernel Class Reference
OpenGL ES kernel to perform the in-place matrix addition between 2 matrices, taking into account that the second matrix might be weighted by a scalar value beta.
#include <GCGEMMMatrixAdditionKernel.h>
Public Member Functions
GCGEMMMatrixAdditionKernel ()
Default constructor.
GCGEMMMatrixAdditionKernel (const GCGEMMMatrixAdditionKernel &)=delete
Prevent instances of this class from being copied (As this class contains pointers)
GCGEMMMatrixAdditionKernel & operator= (const GCGEMMMatrixAdditionKernel &)=delete
Prevent instances of this class from being copied (As this class contains pointers)
GCGEMMMatrixAdditionKernel (GCGEMMMatrixAdditionKernel &&)=default
Allow instances of this class to be moved.
GCGEMMMatrixAdditionKernel & operator= (GCGEMMMatrixAdditionKernel &&)=default
Allow instances of this class to be moved.
void configure (const IGCTensor *input, IGCTensor *output, float beta)
Initialise the kernel's input, output and beta value.
void run (const Window &window) override
Enqueue the OpenGL ES shader to process the given window.
Public Member Functions inherited from IGCKernel
IGCKernel ()
Constructor.
GCKernel & kernel ()
Returns a reference to the GLES kernel of this object.
void add_1D_tensor_argument (unsigned int &idx, const IGCTensor *tensor, const unsigned int binding_point, const Window &window)
Add the passed 1D tensor's parameters to the object's kernel's arguments starting from the index idx.
void add_2D_tensor_argument (unsigned int &idx, const IGCTensor *tensor, const unsigned int binding_point, const Window &window)
Add the passed 2D tensor's parameters to the object's kernel's arguments starting from the index idx.
void add_3D_tensor_argument (unsigned int &idx, const IGCTensor *tensor, const unsigned int binding_point, const Window &window)
Add the passed 3D tensor's parameters to the object's kernel's arguments starting from the index idx.
unsigned int num_arguments_per_1D_tensor () const
Returns the number of arguments enqueued per 1D tensor object.
unsigned int num_arguments_per_2D_tensor () const
Returns the number of arguments enqueued per 2D tensor object.
unsigned int num_arguments_per_3D_tensor () const
Returns the number of arguments enqueued per 3D tensor object.
void set_lws_hint (gles::NDRange &lws_hint)
Set the Local-Workgroup-Size hint.
void set_target (GPUTarget target)
Set the targeted GPU architecture.
GPUTarget get_target () const
Get the targeted GPU architecture.
Public Member Functions inherited from IKernel
IKernel ()
Constructor.
virtual ~IKernel ()=default
Destructor.
virtual bool is_parallelisable () const
Indicates whether or not the kernel is parallelisable.
virtual BorderSize border_size () const
The size of the border for that kernel.
const Window & window () const
The maximum window the kernel can be executed on.
Detailed Description
OpenGL ES kernel to perform the in-place matrix addition between 2 matrices, taking into account that the second matrix might be weighted by a scalar value beta.
The matrices must have the same dimensions
Note
This kernel is computed if and only if beta != 0.0.
Definition at line 38 of file GCGEMMMatrixAdditionKernel.h.
Constructor & Destructor Documentation
GCGEMMMatrixAdditionKernel() [1/3]
GCGEMMMatrixAdditionKernel ()
Default constructor.
Definition at line 38 of file GCGEMMMatrixAdditionKernel.cpp.
     : _input(nullptr), _output(nullptr)
 {
 }
GCGEMMMatrixAdditionKernel() [2/3]
GCGEMMMatrixAdditionKernel (const GCGEMMMatrixAdditionKernel &) delete
Prevent instances of this class from being copied (As this class contains pointers)
GCGEMMMatrixAdditionKernel() [3/3]
GCGEMMMatrixAdditionKernel (GCGEMMMatrixAdditionKernel &&) default
Allow instances of this class to be moved.
Member Function Documentation
configure()
void configure (const IGCTensor * input, IGCTensor * output, float beta)
Initialise the kernel's input, output and beta value.
Note
The input and output tensors must have the same dimensions
Parameters
[in] input Input tensor (Matrix C). Data types supported: F32
[in,out] output Output tensor. If this kernel is used to finalize the GEMM result (alpha * AB + beta * C), output must contain the result obtained by GCGEMMMatrixMultiplyKernel. Data type supported: same as input
[in] beta Weight of matrix C
Definition at line 43 of file GCGEMMMatrixAdditionKernel.cpp.
 {
     ARM_COMPUTE_ERROR_ON_DATA_TYPE_CHANNEL_NOT_IN(input, 1, DataType::F32);
     ARM_COMPUTE_ERROR_ON_MISMATCHING_DATA_TYPES(input, output);
     ARM_COMPUTE_ERROR_ON(input->info()->dimension(0) != output->info()->dimension(0));
     ARM_COMPUTE_ERROR_ON(input->info()->dimension(1) != output->info()->dimension(1));
     _input                                               = input;
     _output                                              = output;
     const unsigned int num_elems_processed_per_iteration = max_gc_vector_width / data_size_from_type(input->info()->data_type());
     std::set<std::string> build_opts;
     std::string           dt_name = (input->info()->data_type() == DataType::F32) ? "DATA_TYPE_FP32" : "DATA_TYPE_FP16";
     build_opts.emplace(("#define " + dt_name));
     build_opts.emplace("#define LOCAL_SIZE_X " + support::cpp11::to_string(1));
     build_opts.emplace("#define LOCAL_SIZE_Y " + support::cpp11::to_string(1));
     build_opts.emplace("#define LOCAL_SIZE_Z " + support::cpp11::to_string(1));
     build_opts.emplace("#define BETA " + float_to_string_with_full_precision(beta));
     // Create kernel
     build_opts.emplace("#define GEMM_MATRIXADDITION");
     std::string data_type_name = lower_string(string_from_data_type(input->info()->data_type()));
     _kernel                    = GCKernelLibrary::get().create_kernel(("gemm_ma"), build_opts);
     // Configure kernel window
     Window win = calculate_max_window(*_input->info(), Steps(num_elems_processed_per_iteration));
     AccessWindowHorizontal input_access(input->info(), 0, num_elems_processed_per_iteration);
     AccessWindowHorizontal output_access(output->info(), 0, num_elems_processed_per_iteration);
     update_window_and_padding(win, input_access, output_access);
     output_access.set_valid_region(win, input->info()->valid_region());
     IGCKernel::configure(win);
 }
References ARM_COMPUTE_ERROR_ON, ARM_COMPUTE_ERROR_ON_DATA_TYPE_CHANNEL_NOT_IN, ARM_COMPUTE_ERROR_ON_MISMATCHING_DATA_TYPES, arm_compute::calculate_max_window(), GCKernelLibrary::create_kernel(), arm_compute::data_size_from_type(), ITensorInfo::data_type(), ITensorInfo::dimension(), arm_compute::F32, arm_compute::float_to_string_with_full_precision(), GCKernelLibrary::get(), ITensor::info(), arm_compute::lower_string(), arm_compute::string_from_data_type(), arm_compute::support::cpp11::to_string(), arm_compute::update_window_and_padding(), and ITensorInfo::valid_region().
Referenced by GCGEMM::configure().
operator=() [1/2]
GCGEMMMatrixAdditionKernel& operator= (const GCGEMMMatrixAdditionKernel &) delete
Prevent instances of this class from being copied (As this class contains pointers)
operator=() [2/2]
GCGEMMMatrixAdditionKernel& operator= (GCGEMMMatrixAdditionKernel &&) default
Allow instances of this class to be moved.
run()
void run (const Window & window) override virtual
Enqueue the OpenGL ES shader to process the given window.
Parameters
[in] window Region on which to execute the kernel. (Must be a valid region of the window returned by window()).
Implements IGCKernel.
Definition at line 80 of file GCGEMMMatrixAdditionKernel.cpp.
 {
     ARM_COMPUTE_ERROR_ON_UNCONFIGURED_KERNEL(this);
     ARM_COMPUTE_ERROR_ON_INVALID_SUBWINDOW(IGCKernel::window(), window);
     _kernel.use();
     Window slice = window.first_slice_window_2D();
     do
     {
         unsigned int idx = 0;
         add_2D_tensor_argument(idx, _input, 1, slice);
         add_2D_tensor_argument(idx, _output, 2, slice);
         _kernel.update_shader_params();
         enqueue(*this, slice);
     }
     while(window.slide_window_slice_2D(slice));
 }
References IGCKernel::add_2D_tensor_argument(), ARM_COMPUTE_ERROR_ON_INVALID_SUBWINDOW, ARM_COMPUTE_ERROR_ON_UNCONFIGURED_KERNEL, arm_compute::enqueue(), Window::first_slice_window_2D(), arm_compute::test::validation::reference::slice(), Window::slide_window_slice_2D(), and IKernel::window().
The documentation for this class was generated from the following files:
arm_compute/core/GLES_COMPUTE/kernels/GCGEMMMatrixAdditionKernel.h
src/core/GLES_COMPUTE/kernels/GCGEMMMatrixAdditionKernel.cpp