Compute Library: CLHOGBlockNormalizationKernel Class Reference
CLHOGBlockNormalizationKernel Class Reference
OpenCL kernel to perform HOG block normalization.
#include <CLHOGDescriptorKernel.h>
Public Member Functions
CLHOGBlockNormalizationKernel ()
Default constructor.
CLHOGBlockNormalizationKernel (const CLHOGBlockNormalizationKernel &)=delete
Prevent instances of this class from being copied (As this class contains pointers)
CLHOGBlockNormalizationKernel & operator= (const CLHOGBlockNormalizationKernel &)=delete
Prevent instances of this class from being copied (As this class contains pointers)
CLHOGBlockNormalizationKernel (CLHOGBlockNormalizationKernel &&)=default
Allow instances of this class to be moved.
CLHOGBlockNormalizationKernel & operator= (CLHOGBlockNormalizationKernel &&)=default
Allow instances of this class to be moved.
~CLHOGBlockNormalizationKernel ()=default
Default destructor.
void configure (const ICLTensor *input, ICLTensor *output, const HOGInfo *hog_info)
Initialise the kernel's input, output and HOG's metadata.
void run (const Window &window, cl::CommandQueue &queue) override
Enqueue the OpenCL kernel to process the given window on the passed OpenCL command queue.
Public Member Functions inherited from ICLKernel
ICLKernel ()
Constructor.
cl::Kernel & kernel ()
Returns a reference to the OpenCL kernel of this object.
template<typename T >
void add_1D_array_argument (unsigned int &idx, const ICLArray< T > *array, const Strides &strides, unsigned int num_dimensions, const Window &window)
Add the passed 1D array's parameters to the object's kernel's arguments starting from the index idx.
void add_1D_tensor_argument (unsigned int &idx, const ICLTensor *tensor, const Window &window)
Add the passed 1D tensor's parameters to the object's kernel's arguments starting from the index idx.
void add_1D_tensor_argument_if (bool cond, unsigned int &idx, const ICLTensor *tensor, const Window &window)
Add the passed 1D tensor's parameters to the object's kernel's arguments starting from the index idx if the condition is true.
void add_2D_tensor_argument (unsigned int &idx, const ICLTensor *tensor, const Window &window)
Add the passed 2D tensor's parameters to the object's kernel's arguments starting from the index idx.
void add_2D_tensor_argument_if (bool cond, unsigned int &idx, const ICLTensor *tensor, const Window &window)
Add the passed 2D tensor's parameters to the object's kernel's arguments starting from the index idx if the condition is true.
void add_3D_tensor_argument (unsigned int &idx, const ICLTensor *tensor, const Window &window)
Add the passed 3D tensor's parameters to the object's kernel's arguments starting from the index idx.
void add_4D_tensor_argument (unsigned int &idx, const ICLTensor *tensor, const Window &window)
Add the passed 4D tensor's parameters to the object's kernel's arguments starting from the index idx.
template<typename T >
void add_argument (unsigned int &idx, T value)
Add the passed parameters to the object's kernel's arguments starting from the index idx.
void set_lws_hint (const cl::NDRange &lws_hint)
Set the Local-Workgroup-Size hint.
cl::NDRange lws_hint () const
Return the Local-Workgroup-Size hint.
const std::string & config_id () const
Get the configuration ID.
void set_target (GPUTarget target)
Set the targeted GPU architecture.
void set_target (cl::Device &device)
Set the targeted GPU architecture according to the CL device.
GPUTarget get_target () const
Get the targeted GPU architecture.
size_t get_max_workgroup_size ()
Get the maximum workgroup size for the device the CLKernelLibrary uses.
template<typename T , unsigned int dimension_size>
void add_array_argument (unsigned &idx, const ICLArray< T > *array, const Strides &strides, unsigned int num_dimensions, const Window &window)
Add the passed array's parameters to the object's kernel's arguments starting from the index idx.
template<unsigned int dimension_size>
void add_tensor_argument (unsigned &idx, const ICLTensor *tensor, const Window &window)
Public Member Functions inherited from IKernel
IKernel ()
Constructor.
virtual ~IKernel ()=default
Destructor.
virtual bool is_parallelisable () const
Indicates whether or not the kernel is parallelisable.
virtual BorderSize border_size () const
The size of the border for that kernel.
const Window & window () const
The maximum window the kernel can be executed on.
Additional Inherited Members
Static Public Member Functions inherited from ICLKernel
static constexpr unsigned int num_arguments_per_1D_array ()
Returns the number of arguments enqueued per 1D array object.
static constexpr unsigned int num_arguments_per_1D_tensor ()
Returns the number of arguments enqueued per 1D tensor object.
static constexpr unsigned int num_arguments_per_2D_tensor ()
Returns the number of arguments enqueued per 2D tensor object.
static constexpr unsigned int num_arguments_per_3D_tensor ()
Returns the number of arguments enqueued per 3D tensor object.
static constexpr unsigned int num_arguments_per_4D_tensor ()
Returns the number of arguments enqueued per 4D tensor object.
static cl::NDRange gws_from_window (const Window &window)
Get the global work size given an execution window.
Detailed Description
OpenCL kernel to perform HOG block normalization.
Definition at line 72 of file CLHOGDescriptorKernel.h.
Constructor & Destructor Documentation
CLHOGBlockNormalizationKernel() [1/3]
CLHOGBlockNormalizationKernel ()
Default constructor.
Definition at line 134 of file CLHOGDescriptorKernel.cpp.
     : _input(nullptr), _output(nullptr), _num_cells_per_block_stride()
 {
 }
CLHOGBlockNormalizationKernel() [2/3]
CLHOGBlockNormalizationKernel (const CLHOGBlockNormalizationKernel &) delete
Prevent instances of this class from being copied (As this class contains pointers)
CLHOGBlockNormalizationKernel() [3/3]
CLHOGBlockNormalizationKernel (CLHOGBlockNormalizationKernel &&) default
Allow instances of this class to be moved.
~CLHOGBlockNormalizationKernel()
~CLHOGBlockNormalizationKernel () default
Default destructor.
Member Function Documentation
configure()
void configure (const ICLTensor * input, ICLTensor * output, const HOGInfo * hog_info)
Initialise the kernel's input, output and HOG's metadata.
Parameters
[in] input Input tensor which stores the local HOG for each cell. Data type supported: F32. Number of channels supported: equal to the number of histogram bins per cell
[out] output Output tensor which stores the normalised blocks. Data type supported: F32. Number of channels supported: equal to the number of histogram bins per block
[in] hog_info HOG's metadata
Definition at line 139 of file CLHOGDescriptorKernel.cpp.
 {
     ARM_COMPUTE_ERROR_ON(hog_info == nullptr);
     ARM_COMPUTE_ERROR_ON_DATA_TYPE_CHANNEL_NOT_IN(input, hog_info->num_bins(), DataType::F32);
     ARM_COMPUTE_ERROR_ON_DATA_TYPE_NOT_IN(output, DataType::F32);
     // Number of cells per block
     const Size2D num_cells_per_block(hog_info->block_size().width / hog_info->cell_size().width,
                                      hog_info->block_size().height / hog_info->cell_size().height);
     ARM_COMPUTE_ERROR_ON_DATA_TYPE_CHANNEL_NOT_IN(output, hog_info->num_bins() * num_cells_per_block.area(), DataType::F32);
     // Number of cells per block stride
     const Size2D num_cells_per_block_stride(hog_info->block_stride().width / hog_info->cell_size().width,
                                             hog_info->block_stride().height / hog_info->cell_size().height);
     _input                      = input;
     _output                     = output;
     _num_cells_per_block_stride = num_cells_per_block_stride;
     std::stringstream args_str;
     args_str << "-DL2_HYST_THRESHOLD=" << hog_info->l2_hyst_threshold() << " ";
     args_str << "-DNUM_CELLS_PER_BLOCK_HEIGHT=" << num_cells_per_block.height << " ";
     args_str << "-DNUM_BINS_PER_BLOCK_X=" << num_cells_per_block.width *hog_info->num_bins() << " ";
     args_str << "-DNUM_BINS_PER_BLOCK=" << _output->info()->num_channels() << " ";
     args_str << "-DL2_NORM=" << static_cast<int>(HOGNormType::L2_NORM) << " ";
     args_str << "-DL1_NORM=" << static_cast<int>(HOGNormType::L1_NORM) << " ";
     args_str << "-DL2HYS_NORM=" << static_cast<int>(HOGNormType::L2HYS_NORM) << " ";
     args_str << "-DHOG_NORM_TYPE=" << static_cast<int>(hog_info->normalization_type()) << " ";
     // Construct kernel name
     std::set<std::string> build_opts = {};
     build_opts.insert(args_str.str());
     const std::string kernel_name = std::string("hog_block_normalization");
     _kernel                       = static_cast<cl::Kernel>(CLKernelLibrary::get().create_kernel(kernel_name, build_opts));
     constexpr unsigned int num_elems_processed_per_iteration = 1;
     constexpr unsigned int num_elems_read_per_iteration      = 1;
     const unsigned int     num_rows_read_per_iteration       = num_cells_per_block.height;
     constexpr unsigned int num_elems_written_per_iteration   = 1;
     const unsigned int     num_rows_written_per_iteration    = num_cells_per_block.height;
     // Configure kernel window
     Window                win = calculate_max_window(*output->info(), Steps(num_elems_processed_per_iteration));
     AccessWindowRectangle output_access(output->info(), 0, 0, num_elems_written_per_iteration, num_rows_written_per_iteration);
     update_window_and_padding(win,
                               AccessWindowRectangle(input->info(), 0, 0, num_elems_read_per_iteration, num_rows_read_per_iteration),
                               output_access);
     output_access.set_valid_region(win, ValidRegion(Coordinates(), output->info()->tensor_shape()));
     ICLKernel::configure_internal(win);
     // Set config_id for enabling LWS tuning
     _config_id = kernel_name;
     _config_id += "_";
     _config_id += lower_string(string_from_data_type(input->info()->data_type()));
     _config_id += "_";
     _config_id += support::cpp11::to_string(input->info()->dimension(0));
     _config_id += "_";
     _config_id += support::cpp11::to_string(input->info()->dimension(1));
     _config_id += "_";
     _config_id += support::cpp11::to_string(output->info()->dimension(0));
     _config_id += "_";
     _config_id += support::cpp11::to_string(output->info()->dimension(1));
 }
References ARM_COMPUTE_ERROR_ON, ARM_COMPUTE_ERROR_ON_DATA_TYPE_CHANNEL_NOT_IN, ARM_COMPUTE_ERROR_ON_DATA_TYPE_NOT_IN, HOGInfo::block_size(), HOGInfo::block_stride(), arm_compute::calculate_max_window(), HOGInfo::cell_size(), arm_compute::create_kernel(), ITensorInfo::data_type(), ITensorInfo::dimension(), arm_compute::F32, CLKernelLibrary::get(), Size2D::height, ITensor::info(), arm_compute::L1_NORM, HOGInfo::l2_hyst_threshold(), arm_compute::L2_NORM, arm_compute::L2HYS_NORM, arm_compute::lower_string(), HOGInfo::normalization_type(), HOGInfo::num_bins(), ITensorInfo::num_channels(), arm_compute::string_from_data_type(), ITensorInfo::tensor_shape(), arm_compute::support::cpp11::to_string(), arm_compute::update_window_and_padding(), and Size2D::width.
Referenced by CLHOGDescriptor::configure().
operator=() [1/2]
CLHOGBlockNormalizationKernel& operator= (const CLHOGBlockNormalizationKernel &) delete
Prevent instances of this class from being copied (As this class contains pointers)
operator=() [2/2]
CLHOGBlockNormalizationKernel& operator= (CLHOGBlockNormalizationKernel &&) default
Allow instances of this class to be moved.
run()
void run (const Window & window, cl::CommandQueue & queue) override virtual
Enqueue the OpenCL kernel to process the given window on the passed OpenCL command queue.
Note
The queue is not flushed by this method, and therefore the kernel will not have been executed by the time this method returns.
Parameters
[in] window Region on which to execute the kernel. (Must be a valid region of the window returned by window()).
[in,out] queue Command queue on which to enqueue the kernel.
Implements ICLKernel.
Definition at line 208 of file CLHOGDescriptorKernel.cpp.
 {
     ARM_COMPUTE_ERROR_ON_UNCONFIGURED_KERNEL(this);
     ARM_COMPUTE_ERROR_ON_INVALID_SUBWINDOW(ICLKernel::window(), window);
     Window slice = window.first_slice_window_2D();
     do
     {
         // Compute slice for the magnitude and phase tensors
         Window slice_in = window.first_slice_window_2D();
         slice_in.set_dimension_step(Window::DimX, _num_cells_per_block_stride.width);
         slice_in.set_dimension_step(Window::DimY, _num_cells_per_block_stride.height);
         unsigned int idx = 0;
         add_2D_tensor_argument(idx, _input, slice_in);
         add_2D_tensor_argument(idx, _output, slice);
         enqueue(queue, *this, slice, lws_hint());
     }
     while(window.slide_window_slice_2D(slice));
 }
References ICLKernel::add_2D_tensor_argument(), ARM_COMPUTE_ERROR_ON_INVALID_SUBWINDOW, ARM_COMPUTE_ERROR_ON_UNCONFIGURED_KERNEL, Window::DimX, Window::DimY, arm_compute::enqueue(), Window::first_slice_window_2D(), Size2D::height, ICLKernel::lws_hint(), Window::set_dimension_step(), arm_compute::test::validation::reference::slice(), Window::slide_window_slice_2D(), Size2D::width, and IKernel::window().
The documentation for this class was generated from the following files:
arm_compute/core/CL/kernels/CLHOGDescriptorKernel.h
src/core/CL/kernels/CLHOGDescriptorKernel.cpp