Compute Library: ICLHOG Class Reference
ICLHOG Class Reference abstract
Interface for OpenCL HOG data-object.
#include <ICLHOG.h>
Public Member Functions
ICLHOG ()
Default constructor.
ICLHOG (const ICLHOG &)=delete
Prevent instances of this class from being copied (As this class contains pointers)
ICLHOG & operator= (const ICLHOG &)=delete
Prevent instances of this class from being copied (As this class contains pointers)
ICLHOG (ICLHOG &&)=default
Allow instances of this class to be moved.
ICLHOG & operator= (ICLHOG &&)=default
Allow instances of this class to be moved.
virtual ~ICLHOG ()=default
Default destructor.
virtual const cl::Buffer & cl_buffer () const =0
Interface to be implemented by the child class to return a reference to the OpenCL buffer containing the hog's descriptor.
void map (cl::CommandQueue &q, bool blocking=true)
Enqueue a map operation of the allocated buffer on the given queue.
void unmap (cl::CommandQueue &q)
Enqueue an unmap operation of the allocated and mapped buffer on the given queue.
virtual void free ()=0
Interface to be implemented by the child class to free the allocated cl buffer.
float * descriptor () const override
Pointer to the first element of the array which stores the linear SVM coefficients of HOG descriptor.
Public Member Functions inherited from IHOG
virtual const HOGInfo * info () const =0
Interface to be implemented by the child class to return the HOG's metadata.
virtual ~IHOG ()=default
Default virtual destructor.
Detailed Description
Interface for OpenCL HOG data-object.
Definition at line 40 of file ICLHOG.h.
Constructor & Destructor Documentation
ICLHOG() [1/3]
ICLHOG ()
Default constructor.
Definition at line 28 of file ICLHOG.cpp.
     : _mapping(nullptr)
 {
 }
ICLHOG() [2/3]
ICLHOG (const ICLHOG &) delete
Prevent instances of this class from being copied (As this class contains pointers)
ICLHOG() [3/3]
ICLHOG (ICLHOG &&) default
Allow instances of this class to be moved.
~ICLHOG()
virtual ~ICLHOG () virtual default
Default destructor.
Member Function Documentation
cl_buffer()
virtual const cl::Buffer& cl_buffer () const pure virtual
Interface to be implemented by the child class to return a reference to the OpenCL buffer containing the hog's descriptor.
Returns
A reference to an OpenCL buffer containing the hog's descriptor
Implemented in CLHOG.
Referenced by CLHOGDetectorKernel::configure().
descriptor()
float * descriptor () const override virtual
Pointer to the first element of the array which stores the linear SVM coefficients of HOG descriptor.
Note
Other elements of the array can be accessed using descriptor()[idx] for idx=[0, descriptor_size() - 1]
Returns
A pointer to the first element of the array which stores the linear SVM coefficients of HOG descriptor
Implements IHOG.
Definition at line 44 of file ICLHOG.cpp.
 {
     return reinterpret_cast<float *>(_mapping);
 }
Referenced by CLHOGAccessor::descriptor(), CLHOG::map(), and CLHOG::unmap().
free()
virtual void free () pure virtual
Interface to be implemented by the child class to free the allocated cl buffer.
Warning
The buffer must have been allocated previously. Otherwise calling the function will fail.
Implemented in CLHOG.
map()
void map (cl::CommandQueue & q, bool blocking = true)
Enqueue a map operation of the allocated buffer on the given queue.
Parameters
[in,out] q The CL command queue to use for the mapping operation.
[in] blocking If true, then the mapping will be ready to use by the time this method returns, else it is the caller's responsibility to flush the queue and wait for the mapping operation to have completed before using the returned mapping pointer.
Returns
The mapping address.
Definition at line 33 of file ICLHOG.cpp.
 {
     _mapping = do_map(q, blocking);
 }
Referenced by CLHOG::map().
operator=() [1/2]
ICLHOG& operator= (const ICLHOG &) delete
Prevent instances of this class from being copied (As this class contains pointers)
operator=() [2/2]
ICLHOG& operator= (ICLHOG &&) default
Allow instances of this class to be moved.
unmap()
void unmap (cl::CommandQueue & q)
Enqueue an unmap operation of the allocated and mapped buffer on the given queue.
Note
This method simply enqueues the unmap operation, it is the caller's responsibility to flush the queue and make sure the unmap is finished before the memory is accessed by the device.
Parameters
[in,out] q The CL command queue to use for the mapping operation.
Definition at line 38 of file ICLHOG.cpp.
 {
     do_unmap(q);
     _mapping = nullptr;
 }
Referenced by CLHOG::unmap().
The documentation for this class was generated from the following files:
arm_compute/core/CL/ICLHOG.h
src/core/CL/ICLHOG.cpp