Compute Library: CLDirectConvolutionLayerOutputStageKernel Class Reference
CLDirectConvolutionLayerOutputStageKernel Class Reference
OpenCL kernel to accumulate the biases, if provided, or downscale in case of quantized input.
#include <CLDirectConvolutionLayerOutputStageKernel.h>
Public Member Functions
CLDirectConvolutionLayerOutputStageKernel ()
Default constructor.
CLDirectConvolutionLayerOutputStageKernel (const CLDirectConvolutionLayerOutputStageKernel &)=delete
Prevent instances of this class from being copied (As this class contains pointers)
CLDirectConvolutionLayerOutputStageKernel & operator= (const CLDirectConvolutionLayerOutputStageKernel &)=delete
Prevent instances of this class from being copied (As this class contains pointers)
CLDirectConvolutionLayerOutputStageKernel (CLDirectConvolutionLayerOutputStageKernel &&)=default
Allow instances of this class to be moved.
CLDirectConvolutionLayerOutputStageKernel & operator= (CLDirectConvolutionLayerOutputStageKernel &&)=default
Allow instances of this class to be moved.
~CLDirectConvolutionLayerOutputStageKernel ()=default
Default destructor.
void configure (ICLTensor *input, const ICLTensor *bias=nullptr, ICLTensor *output=nullptr, int result_fixedpoint_multiplier=0, int result_shift=0, int result_offset_after_shift=0)
Set the accumulate buffer and the biases of the kernel.
void run (const Window &window, cl::CommandQueue &queue) override
Enqueue the OpenCL kernel to process the given window on the passed OpenCL command queue.
Public Member Functions inherited from ICLKernel
ICLKernel ()
Constructor.
cl::Kernel & kernel ()
Returns a reference to the OpenCL kernel of this object.
template<typename T >
void add_1D_array_argument (unsigned int &idx, const ICLArray< T > *array, const Strides &strides, unsigned int num_dimensions, const Window &window)
Add the passed 1D array's parameters to the object's kernel's arguments starting from the index idx.
void add_1D_tensor_argument (unsigned int &idx, const ICLTensor *tensor, const Window &window)
Add the passed 1D tensor's parameters to the object's kernel's arguments starting from the index idx.
void add_1D_tensor_argument_if (bool cond, unsigned int &idx, const ICLTensor *tensor, const Window &window)
Add the passed 1D tensor's parameters to the object's kernel's arguments starting from the index idx if the condition is true.
void add_2D_tensor_argument (unsigned int &idx, const ICLTensor *tensor, const Window &window)
Add the passed 2D tensor's parameters to the object's kernel's arguments starting from the index idx.
void add_2D_tensor_argument_if (bool cond, unsigned int &idx, const ICLTensor *tensor, const Window &window)
Add the passed 2D tensor's parameters to the object's kernel's arguments starting from the index idx if the condition is true.
void add_3D_tensor_argument (unsigned int &idx, const ICLTensor *tensor, const Window &window)
Add the passed 3D tensor's parameters to the object's kernel's arguments starting from the index idx.
void add_4D_tensor_argument (unsigned int &idx, const ICLTensor *tensor, const Window &window)
Add the passed 4D tensor's parameters to the object's kernel's arguments starting from the index idx.
template<typename T >
void add_argument (unsigned int &idx, T value)
Add the passed parameters to the object's kernel's arguments starting from the index idx.
void set_lws_hint (const cl::NDRange &lws_hint)
Set the Local-Workgroup-Size hint.
cl::NDRange lws_hint () const
Return the Local-Workgroup-Size hint.
const std::string & config_id () const
Get the configuration ID.
void set_target (GPUTarget target)
Set the targeted GPU architecture.
void set_target (cl::Device &device)
Set the targeted GPU architecture according to the CL device.
GPUTarget get_target () const
Get the targeted GPU architecture.
size_t get_max_workgroup_size ()
Get the maximum workgroup size for the device the CLKernelLibrary uses.
template<typename T , unsigned int dimension_size>
void add_array_argument (unsigned &idx, const ICLArray< T > *array, const Strides &strides, unsigned int num_dimensions, const Window &window)
Add the passed array's parameters to the object's kernel's arguments starting from the index idx.
template<unsigned int dimension_size>
void add_tensor_argument (unsigned &idx, const ICLTensor *tensor, const Window &window)
Public Member Functions inherited from IKernel
IKernel ()
Constructor.
virtual ~IKernel ()=default
Destructor.
virtual bool is_parallelisable () const
Indicates whether or not the kernel is parallelisable.
virtual BorderSize border_size () const
The size of the border for that kernel.
const Window & window () const
The maximum window the kernel can be executed on.
Static Public Member Functions
static Status validate (const ITensorInfo *input, const ITensorInfo *bias=nullptr, const ITensorInfo *output=nullptr)
Static function to check if given info will lead to a valid configuration of CLDirectConvolutionLayerOutputStageKernel.
Static Public Member Functions inherited from ICLKernel
static constexpr unsigned int num_arguments_per_1D_array ()
Returns the number of arguments enqueued per 1D array object.
static constexpr unsigned int num_arguments_per_1D_tensor ()
Returns the number of arguments enqueued per 1D tensor object.
static constexpr unsigned int num_arguments_per_2D_tensor ()
Returns the number of arguments enqueued per 2D tensor object.
static constexpr unsigned int num_arguments_per_3D_tensor ()
Returns the number of arguments enqueued per 3D tensor object.
static constexpr unsigned int num_arguments_per_4D_tensor ()
Returns the number of arguments enqueued per 4D tensor object.
static cl::NDRange gws_from_window (const Window &window)
Get the global work size given an execution window.
Detailed Description
OpenCL kernel to accumulate the biases, if provided, or downscale in case of quantized input.
Deprecated:
This kernel is deprecated and will be removed in release 19.05
Note
We assume bias to be shared
Definition at line 39 of file CLDirectConvolutionLayerOutputStageKernel.h.
Constructor & Destructor Documentation
CLDirectConvolutionLayerOutputStageKernel() [1/3]
CLDirectConvolutionLayerOutputStageKernel ()
Default constructor.
Definition at line 124 of file CLDirectConvolutionOutputStageKernel.cpp.
     : _input(nullptr), _bias(nullptr), _output(nullptr), _result_fixedpoint_multiplier(0), _result_shift(0), _result_offset_after_shift(0)
 {
 }
CLDirectConvolutionLayerOutputStageKernel() [2/3]
CLDirectConvolutionLayerOutputStageKernel (const CLDirectConvolutionLayerOutputStageKernel &) delete
Prevent instances of this class from being copied (As this class contains pointers)
CLDirectConvolutionLayerOutputStageKernel() [3/3]
CLDirectConvolutionLayerOutputStageKernel (CLDirectConvolutionLayerOutputStageKernel &&) default
Allow instances of this class to be moved.
~CLDirectConvolutionLayerOutputStageKernel()
~CLDirectConvolutionLayerOutputStageKernel () default
Default destructor.
Member Function Documentation
configure()
void configure (ICLTensor * input, const ICLTensor * bias = nullptr, ICLTensor * output = nullptr, int result_fixedpoint_multiplier = 0, int result_shift = 0, int result_offset_after_shift = 0)
Set the accumulate buffer and the biases of the kernel.
Parameters
[in,out] input Input to add the bias to. If output is not specified then accumulation is done in-place. Data type supported: S32/F16/F32
[in] bias (Optional) The shared bias tensor to add. It must be 1D Tensor. Data type supported: Same as input
[out] output (Optional) If the output tensor is specified the accumulation is done out-of-place. (Defaults to nullptr) Required parameter if output is of QASYMM8 type. Data types supported: QASYMM8/F16/F32
[in] result_fixedpoint_multiplier (Optional)Fixed point value to be multiplied to each element of the input matrix when once the result_offset has been add
[in] result_shift (Optional)Integer value used to round to nearest division by a power-of-two the result after the fixed point multiplication
[in] result_offset_after_shift (Optional)Offset to be applied to result before converting it back to QASYMM8
Definition at line 129 of file CLDirectConvolutionOutputStageKernel.cpp.
 {
     ARM_COMPUTE_ERROR_ON_NULLPTR(input);
     // Auto-initialize output if required
     if(output != nullptr)
     {
         // Work out expected output data type
         const DataType output_dt = (input->info()->data_type() == DataType::S32) ? DataType::QASYMM8 : input->info()->data_type();
         // Output tensor auto initialization if not yet initialized
         auto_init_if_empty(*output->info(), input->info()->clone()->set_data_type(output_dt));
     }
     // Perform validation step
     ARM_COMPUTE_ERROR_THROW_ON(validate_arguments(input->info(), (bias == nullptr) ? nullptr : bias->info(), (output == nullptr) ? nullptr : output->info()));
     _bias                         = bias;
     _input                        = input;
     _output                       = output;
     _result_fixedpoint_multiplier = result_fixedpoint_multiplier;
     _result_shift                 = result_shift;
     _result_offset_after_shift    = result_offset_after_shift;
     const unsigned int num_elems_accessed_per_iteration = 16 / element_size_from_data_type(input->info()->data_type());
     // Create kernel
     CLBuildOptions build_opts;
     build_opts.add_option_if(bias != nullptr, "-DHAS_BIAS");
     build_opts.add_option("-D" + string_from_data_layout(input->info()->data_layout()));
     build_opts.add_option("-DVEC_SIZE=" + support::cpp11::to_string(num_elems_accessed_per_iteration));
     _kernel = static_cast<cl::Kernel>(CLKernelLibrary::get().create_kernel("output_stage_quantized", build_opts.options()));
     // Set static kernel arguments
     int idx = 2 * num_arguments_per_3D_tensor() + ((bias != nullptr) ? num_arguments_per_1D_tensor() : 0);
     _kernel.setArg<int>(idx++, _result_offset_after_shift);
     _kernel.setArg<int>(idx++, _result_fixedpoint_multiplier);
     _kernel.setArg<int>(idx++, _result_shift);
     // Configure kernel window
     auto win_config = validate_and_configure_window(input->info(), (bias == nullptr) ? nullptr : bias->info(), (output == nullptr) ? nullptr : output->info());
     ARM_COMPUTE_ERROR_THROW_ON(win_config.first);
     ICLKernel::configure_internal(win_config.second);
 }
References CLBuildOptions::add_option_if(), ARM_COMPUTE_ERROR_ON_NULLPTR, ARM_COMPUTE_ERROR_THROW_ON, arm_compute::auto_init_if_empty(), arm_compute::test::validation::bias, ICloneable< T >::clone(), arm_compute::create_kernel(), ITensorInfo::data_layout(), ITensorInfo::data_type(), arm_compute::element_size_from_data_type(), CLKernelLibrary::get(), ITensor::info(), CLTensor::info(), ICLKernel::num_arguments_per_1D_tensor(), ICLKernel::num_arguments_per_3D_tensor(), arm_compute::QASYMM8, arm_compute::S32, arm_compute::string_from_data_layout(), arm_compute::support::cpp11::to_string(), and arm_compute::validate_and_configure_window().
Referenced by CLDepthwiseConvolutionLayer::configure().
operator=() [1/2]
CLDirectConvolutionLayerOutputStageKernel& operator= (const CLDirectConvolutionLayerOutputStageKernel &) delete
Prevent instances of this class from being copied (As this class contains pointers)
operator=() [2/2]
CLDirectConvolutionLayerOutputStageKernel& operator= (CLDirectConvolutionLayerOutputStageKernel &&) default
Allow instances of this class to be moved.
run()
void run (const Window & window, cl::CommandQueue & queue) override virtual
Enqueue the OpenCL kernel to process the given window on the passed OpenCL command queue.
Note
The queue is not flushed by this method, and therefore the kernel will not have been executed by the time this method returns.
Parameters
[in] window Region on which to execute the kernel. (Must be a valid region of the window returned by window()).
[in,out] queue Command queue on which to enqueue the kernel.
Implements ICLKernel.
Definition at line 182 of file CLDirectConvolutionOutputStageKernel.cpp.
 {
     ARM_COMPUTE_ERROR_ON_UNCONFIGURED_KERNEL(this);
     ARM_COMPUTE_ERROR_ON_MISMATCHING_WINDOWS(ICLKernel::window(), window);
     Window slice = window.first_slice_window_3D();
     // Set bias vector
     if(_bias != nullptr)
     {
         unsigned int idx1 = 2 * num_arguments_per_3D_tensor();
         Window       slice_biases;
         slice_biases.use_tensor_dimensions(_bias->info()->tensor_shape());
         add_1D_tensor_argument(idx1, _bias, slice_biases);
     }
     // Run kernel
     do
     {
         // Set arguments
         unsigned int idx = 0;
         add_3D_tensor_argument(idx, _input, slice);
         add_3D_tensor_argument(idx, _output, slice);
         enqueue(queue, *this, slice, lws_hint());
     }
     while(window.slide_window_slice_3D(slice));
 }
References ICLKernel::add_1D_tensor_argument(), ICLKernel::add_3D_tensor_argument(), ARM_COMPUTE_ERROR_ON_MISMATCHING_WINDOWS, ARM_COMPUTE_ERROR_ON_UNCONFIGURED_KERNEL, arm_compute::enqueue(), Window::first_slice_window_3D(), ITensor::info(), ICLKernel::lws_hint(), ICLKernel::num_arguments_per_3D_tensor(), arm_compute::test::validation::reference::slice(), Window::slide_window_slice_3D(), ITensorInfo::tensor_shape(), Window::use_tensor_dimensions(), and IKernel::window().
validate()
Status validate (const ITensorInfo * input, const ITensorInfo * bias = nullptr, const ITensorInfo * output = nullptr) static
Static function to check if given info will lead to a valid configuration of CLDirectConvolutionLayerOutputStageKernel.
Parameters
[in] input Input to add the bias to. If output is not specified then accumulation is done in-place. Data type supported: F16/F32
[in] bias (Optional) The shared bias tensor to add. It must be 1D Tensor. Data type supported: Same as input
[in] output (Optional) If the output tensor is specified the accumulation is done out-of-place. (Defaults to nullptr) Data type supported: F16/F32
Returns
a status
Definition at line 174 of file CLDirectConvolutionOutputStageKernel.cpp.
 {
     ARM_COMPUTE_RETURN_ON_ERROR(validate_arguments(input, bias, output));
     ARM_COMPUTE_RETURN_ON_ERROR(validate_and_configure_window(input->clone().get(), bias == nullptr ? nullptr : bias->clone().get(), output == nullptr ? nullptr : output->clone().get()).first);
     return Status{};
 }
References ARM_COMPUTE_RETURN_ON_ERROR, arm_compute::test::validation::bias, ICloneable< T >::clone(), and arm_compute::validate_and_configure_window().
Referenced by CLDepthwiseConvolutionLayer::validate().
The documentation for this class was generated from the following files:
arm_compute/core/CL/kernels/CLDirectConvolutionLayerOutputStageKernel.h
src/core/CL/kernels/CLDirectConvolutionOutputStageKernel.cpp