Compute Library: CLSoftmaxLayer Class Reference
CLSoftmaxLayer Class Reference
Basic function to compute a SoftmaxLayer.
#include <CLSoftmaxLayer.h>
Public Member Functions
CLSoftmaxLayer (std::shared_ptr< IMemoryManager > memory_manager=nullptr)
Constructor.
void configure (const ICLTensor *input, ICLTensor *output, float beta=1.0f, size_t axis=1)
Set the input and output tensors.
void run () override
Run the kernels contained in the function.
Public Member Functions inherited from IFunction
virtual ~IFunction ()=default
Destructor.
virtual void prepare ()
Prepare the function for executing.
Static Public Member Functions
static Status validate (const ITensorInfo *input, const ITensorInfo *output, float beta=1.0f, size_t axis=1)
Static function to check if given info will lead to a valid configuration of CLSoftmaxLayer.
Detailed Description
Basic function to compute a SoftmaxLayer.
Softmax is calculated by :
\[ out = exp((x - max(x)) * beta) / sum(exp((x - max(x)) * beta)) \]
This function runs the following kernels:
CLLogits1DMaxKernel
CLLogits1DShiftExpSumKernel
CLLogits1DNormKernel
Definition at line 51 of file CLSoftmaxLayer.h.
Constructor & Destructor Documentation
CLSoftmaxLayer()
CLSoftmaxLayer (std::shared_ptr< IMemoryManager > memory_manager = nullptr)
Constructor.
Definition at line 38 of file CLSoftmaxLayer.cpp.
     : _memory_group(std::move(memory_manager)), _max_shift_exp_sum_kernel(), _norm_kernel(), _flatten_kernel_ptr(), _reshape_kernel(), _max(), _sum(), _tmp(), _input_flattened(), _output_flattened(),
       _needs_flattening(false)
 {
 }
Member Function Documentation
configure()
void configure (const ICLTensor * input, ICLTensor * output, float beta = 1.0f, size_t axis = 1)
Set the input and output tensors.
Parameters
[in] input Source tensor. Data types supported: QASYMM8/F16/F32
[out] output Destination tensor. Data types supported: same as input
[in] beta (Optional) A scaling factor for the exponent. Defaults to 1.f
[in] axis (Optional) Reduction axis. It has the purpose of squashing the first axis dimensions together. For instance, given a [4x4x4x4] image, when axis is 2, the Softmax reduction will be applied on each of the [4x4] planes of the input image.
Definition at line 73 of file CLSoftmaxLayer.cpp.
 {
     // Perform validation step
     ARM_COMPUTE_ERROR_ON_NULLPTR(input, output);
     ARM_COMPUTE_ERROR_THROW_ON(CLSoftmaxLayer::validate(input->info(), output->info(), beta, axis));
     // We don't need flattening only in the case the input is 2D and axis is 1
     _needs_flattening = axis != 1;
     // If we are dealing with a 4D tensor, we will:
     // - Flatten the input, so that we end up with a [width*height*depth] * batches 2D tensor
     // - Execute all the pipeline (reduction + normalization) on the flattened tensor
     // - Reshape the flattened output into the real output
     if(_needs_flattening)
     {
         // Add to the memory manager _input_flattened
         _memory_group.manage(&_input_flattened);
         // Cofigure  _flatten_kernel and _input_flattened
         configure_reshape_input_kernel(input, output, axis);
     }
     // We want to deal with a 2D input. Either it is the flattened version of the original input (4D case)
     // or it is the original input case (2D case)
     const ICLTensor *input_2D = (_needs_flattening ? &_input_flattened : input);
     // Create intermediate tensors shapes
     TensorInfo input_info    = input_2D->info()->clone()->reset_padding().set_is_resizable(true);
     DataType   tmp_data_type = is_data_type_quantized_asymmetric(input_2D->info()->data_type()) ? DataType::S32 : input_2D->info()->data_type();
     TensorInfo tensor_info_tmp(input_info.clone()->set_data_type(tmp_data_type));
     _tmp.allocator()->init(tensor_info_tmp);
     TensorShape max_sum_shape = input_2D->info()->tensor_shape();
     max_sum_shape.set(0, 1);
     _max.allocator()->init(input_info.clone()->set_tensor_shape(max_sum_shape));
     _sum.allocator()->init(input_info.clone()->set_tensor_shape(max_sum_shape).set_data_type(tmp_data_type));
     // Set GPU target to kernels
     _max_shift_exp_sum_kernel.set_target(CLScheduler::get().target());
     // Manage intermediate buffers
     _memory_group.manage(&_tmp);
     _memory_group.manage(&_max);
     _memory_group.manage(&_sum);
     // Configure kernels
     _max_shift_exp_sum_kernel.configure(input_2D, &_max, &_tmp, &_sum, beta);
     if(_needs_flattening)
     {
         // Add to the memory manager _output_flattened
         _memory_group.manage(&_output_flattened);
         // The normalization kernel stores the result in a flat output tensor
         _norm_kernel.configure(&_tmp, &_sum, &_output_flattened, beta);
         // Reshape the flat output into a the requested (4D) output
         _reshape_kernel.configure(&_output_flattened, output);
         // Allocate the intermediate flat tensors
         _input_flattened.allocator()->allocate();
         _output_flattened.allocator()->allocate();
     }
     else
     {
         // Softmax 2D case
         _norm_kernel.configure(&_tmp, &_sum, output, beta);
     }
     // Allocate intermediate buffers
     _tmp.allocator()->allocate();
     _max.allocator()->allocate();
     _sum.allocator()->allocate();
 }
References CLTensorAllocator::allocate(), CLTensor::allocator(), ARM_COMPUTE_ERROR_ON_NULLPTR, ARM_COMPUTE_ERROR_THROW_ON, arm_compute::test::validation::axis, ICloneable< T >::clone(), CLReshapeLayerKernel::configure(), CLLogits1DMaxShiftExpSumKernel::configure(), CLLogits1DNormKernel::configure(), ITensorInfo::data_type(), CLScheduler::get(), ITensor::info(), ITensorAllocator::init(), arm_compute::test::validation::input_info, arm_compute::is_data_type_quantized_asymmetric(), MemoryGroupBase< TensorType >::manage(), arm_compute::S32, TensorShape::set(), ICLKernel::set_target(), ITensorInfo::tensor_shape(), and CLSoftmaxLayer::validate().
Referenced by arm_compute::test::validation::DATA_TEST_CASE().
run()
void run () override virtual
Run the kernels contained in the function.
For NEON kernels:
Multi-threading is used for the kernels which are parallelisable.
By default std::thread::hardware_concurrency() threads are used.
Note
CPPScheduler::set_num_threads() can be used to manually set the number of threads
For OpenCL kernels:
All the kernels are enqueued on the queue associated with CLScheduler.
The queue is then flushed.
Note
The function will not block until the kernels are executed. It is the user's responsibility to wait.
Will call prepare() on first run if hasn't been done
Implements IFunction.
Definition at line 192 of file CLSoftmaxLayer.cpp.
 {
     MemoryGroupResourceScope scope_mg(_memory_group);
     if(_needs_flattening)
     {
         CLScheduler::get().enqueue(*_flatten_kernel_ptr, false);
     }
     CLScheduler::get().enqueue(_max_shift_exp_sum_kernel, false);
     CLScheduler::get().enqueue(_norm_kernel, !_needs_flattening);
     if(_needs_flattening)
     {
         CLScheduler::get().enqueue(_reshape_kernel, true);
     }
 }
References CLScheduler::enqueue(), and CLScheduler::get().
validate()
Status validate (const ITensorInfo * input, const ITensorInfo * output, float beta = 1.0f, size_t axis = 1) static
Static function to check if given info will lead to a valid configuration of CLSoftmaxLayer.
Parameters
[in] input Source tensor. Data types supported: QASYMM8/F16/F32
[in] output Destination tensor. Data types supported: same as input
[in] beta (Optional) A scaling factor for the exponent. Defaults to 1.f
[in] axis (Optional) Reduction axis. It has the purpose of squashing the first axis dimensions together. For instance, given a [4x4x4x4] image, when axis is 2, the Softmax reduction will be applied on each of the [4x4] planes of the input image.
Returns
a status
Definition at line 148 of file CLSoftmaxLayer.cpp.
 {
     ARM_COMPUTE_RETURN_ERROR_ON_NULLPTR(input, output);
     ARM_COMPUTE_RETURN_ERROR_ON_MSG(input->num_dimensions() > 4, "Only up to 4 dimensions are supported");
     ARM_COMPUTE_UNUSED(beta);
     // Create intermediate tensor info
     DataType   tmp_data_type = is_data_type_quantized_asymmetric(input->data_type()) ? DataType::S32 : input->data_type();
     TensorInfo tensor_info_tmp(input->clone()->set_data_type(tmp_data_type).set_is_resizable(true));
     TensorShape max_sum_shape = input->tensor_shape();
     max_sum_shape.set(0, 1);
     TensorInfo tensor_info_max(input->clone()->set_tensor_shape(max_sum_shape).set_is_resizable(true));
     TensorInfo tensor_info_sum(input->clone()->set_tensor_shape(max_sum_shape).set_data_type(tmp_data_type).set_quantization_info(QuantizationInfo()).set_is_resizable(true));
     const bool needs_flattening = (axis != 1);
     if(needs_flattening)
     {
         const TensorShape shape_flatten = misc::shape_calculator::compute_softmax_shape(input, axis);
         TensorInfo        tensor_info_flat(input->clone()->set_tensor_shape(shape_flatten).set_is_resizable(true));
         if(axis != 3)
         {
             ARM_COMPUTE_RETURN_ON_ERROR(CLReshapeLayerKernel::validate(input, &tensor_info_flat));
         }
         else
         {
             ARM_COMPUTE_RETURN_ON_ERROR(CLFlattenLayerKernel::validate(input, &tensor_info_flat));
         }
     }
     ARM_COMPUTE_RETURN_ON_ERROR(CLLogits1DMaxShiftExpSumKernel::validate(input, &tensor_info_max, &tensor_info_tmp, &tensor_info_sum));
     ARM_COMPUTE_RETURN_ON_ERROR(CLLogits1DNormKernel::validate(&tensor_info_tmp, &tensor_info_sum, output));
     if(needs_flattening)
     {
         const TensorShape shape_flatten = misc::shape_calculator::compute_softmax_shape(input);
         TensorInfo        tensor_info_flat(input->clone()->set_tensor_shape(shape_flatten).set_is_resizable(true));
     }
     return Status{};
 }
References ARM_COMPUTE_RETURN_ERROR_ON_MSG, ARM_COMPUTE_RETURN_ERROR_ON_NULLPTR, ARM_COMPUTE_RETURN_ON_ERROR, ARM_COMPUTE_UNUSED, arm_compute::test::validation::axis, ICloneable< T >::clone(), arm_compute::misc::shape_calculator::compute_softmax_shape(), ITensorInfo::data_type(), arm_compute::is_data_type_quantized_asymmetric(), ITensorInfo::num_dimensions(), arm_compute::S32, TensorShape::set(), ITensorInfo::tensor_shape(), CLReshapeLayerKernel::validate(), CLFlattenLayerKernel::validate(), CLLogits1DMaxShiftExpSumKernel::validate(), and CLLogits1DNormKernel::validate().
Referenced by CLSoftmaxLayer::configure().
The documentation for this class was generated from the following files:
arm_compute/runtime/CL/functions/CLSoftmaxLayer.h
src/runtime/CL/functions/CLSoftmaxLayer.cpp