Compute Library: AccessWindowStatic Class Reference
AccessWindowStatic Class Reference
Implementation of a static rectangular access pattern.
#include <AccessWindowStatic.h>
Public Member Functions
AccessWindowStatic (ITensorInfo *info, int start_x, int start_y, int end_x, int end_y)
Constructor for a static access pattern.
AccessWindowStatic (const AccessWindowStatic &)=delete
Prevent instances of this class from being copied (As this class contains pointers)
AccessWindowStatic & operator= (const AccessWindowStatic &)=delete
Prevent instances of this class from being copied (As this class contains pointers)
AccessWindowStatic (AccessWindowStatic &&)=default
Allow instances of this class to be move constructed.
AccessWindowStatic & operator= (AccessWindowStatic &&)=default
Allow instances of this class to be moved.
~AccessWindowStatic ()=default
Default destructor.
void set_valid_region (const Window &window, const ValidRegion &input_valid_region)
Set the valid region based on the static access pattern and valid region of the inputs.
ValidRegion compute_valid_region (const Window &window, ValidRegion input_valid_region) const
Compute the valid region based on the static access pattern and valid region of the inputs.
bool update_window_if_needed (Window &window) const override
Shrink the window if padding is not large enough.
bool update_padding_if_needed (const Window &window) override
Increase the padding to be large enough for the window.
ValidRegion compute_valid_region (const Window &window, ValidRegion input_valid_region, bool border_undefined, BorderSize border_size) const override
Compute the valid region based on access pattern and valid region of the inputs.
Public Member Functions inherited from IAccessWindow
virtual ~IAccessWindow ()=default
Default virtual destructor.
Detailed Description
Implementation of a static rectangular access pattern.
In this implementation the access offsets and sizes are not relative to the current element. Instead they are considered to be absolute coordinates within the accessed tensor's shape.
Definition at line 46 of file AccessWindowStatic.h.
Constructor & Destructor Documentation
AccessWindowStatic() [1/3]
AccessWindowStatic (ITensorInfo * info, int start_x, int start_y, int end_x, int end_y)
Constructor for a static access pattern.
Parameters
[in,out] info Tensor info of the accessed kernel.
[in] start_x Start of the access in X direction.
[in] start_y Start of the access in Y direction.
[in] end_x End of the access in X direction.
[in] end_y End of the access in Y direction.
Definition at line 32 of file AccessWindowStatic.cpp.
     : _info(info), _start_x(start_x), _start_y(start_y), _end_x(end_x), _end_y(end_y)
 {
 }
AccessWindowStatic() [2/3]
AccessWindowStatic (const AccessWindowStatic &) delete
Prevent instances of this class from being copied (As this class contains pointers)
AccessWindowStatic() [3/3]
AccessWindowStatic (AccessWindowStatic &&) default
Allow instances of this class to be move constructed.
~AccessWindowStatic()
~AccessWindowStatic () default
Default destructor.
Member Function Documentation
compute_valid_region() [1/2]
ValidRegion compute_valid_region (const Window & window, ValidRegion input_valid_region) const
Compute the valid region based on the static access pattern and valid region of the inputs.
Parameters
[in] window Execution window of the kernel.
[in] input_valid_region Combined valid region of all inputs.
Returns
a valid region.
Definition at line 45 of file AccessWindowStatic.cpp.
 {
     if(_info == nullptr)
     {
         return input_valid_region;
     }
     ARM_COMPUTE_UNUSED(window);
     Coordinates &anchor = input_valid_region.anchor;
     TensorShape &shape  = input_valid_region.shape;
     // Start of the valid region is equal to the start of the static access but
     // never outside of the tensor.
     anchor.set(0, std::max<int>(0, _start_x));
     if(_info->num_dimensions() > 1)
     {
         anchor.set(1, std::max<int>(0, _start_y));
     }
     // End of the valid region is equal to the end of the static access but
     // never outside of the tensor.
     shape.set(0, std::min<int>(_end_x, _info->tensor_shape()[0]));
     if(_info->num_dimensions() > 1)
     {
         shape.set(1, std::min<int>(_end_y, _info->tensor_shape()[1]));
     }
     return input_valid_region;
 }
References ValidRegion::anchor, ARM_COMPUTE_UNUSED, ITensorInfo::num_dimensions(), Dimensions< T >::set(), arm_compute::test::validation::shape, ValidRegion::shape, and ITensorInfo::tensor_shape().
Referenced by AccessWindowStatic::compute_valid_region(), and AccessWindowStatic::set_valid_region().
compute_valid_region() [2/2]
ValidRegion compute_valid_region (const Window & window, ValidRegion input_valid_region, bool border_undefined, BorderSize border_size) const override virtual
Compute the valid region based on access pattern and valid region of the inputs.
Note
This method assumes that there is no border.
Parameters
[in] window Execution window of the kernel.
[in] input_valid_region Combined valid region of all inputs.
[in] border_undefined Undefined borders are excluded from the valid region.
[in] border_size Size of the border around the XY-plane of the tensor.
Returns
a valid region.
Implements IAccessWindow.
Definition at line 37 of file AccessWindowStatic.cpp.
 {
     ARM_COMPUTE_UNUSED(border_undefined);
     ARM_COMPUTE_UNUSED(border_size);
     return compute_valid_region(window, input_valid_region);
 }
References ARM_COMPUTE_UNUSED, and AccessWindowStatic::compute_valid_region().
operator=() [1/2]
AccessWindowStatic& operator= (const AccessWindowStatic &) delete
Prevent instances of this class from being copied (As this class contains pointers)
operator=() [2/2]
AccessWindowStatic& operator= (AccessWindowStatic &&) default
Allow instances of this class to be moved.
set_valid_region()
void set_valid_region (const Window & window, const ValidRegion & input_valid_region)
Set the valid region based on the static access pattern and valid region of the inputs.
Parameters
[in] window Execution window of the kernel.
[in] input_valid_region Combined valid region of all inputs.
Definition at line 76 of file AccessWindowStatic.cpp.
 {
     if(_info != nullptr)
     {
         _info->set_valid_region(compute_valid_region(window, input_valid_region));
     }
 }
References AccessWindowStatic::compute_valid_region(), and ITensorInfo::set_valid_region().
Referenced by GCTransposeKernel::configure().
update_padding_if_needed()
bool update_padding_if_needed (const Window & window) override virtual
Increase the padding to be large enough for the window.
Parameters
[in] window Window used by the kernel.
Returns
True if the padding has been changed.
Implements IAccessWindow.
Definition at line 160 of file AccessWindowStatic.cpp.
 {
     ARM_COMPUTE_UNUSED(window);
     // Only update the padding if the tensor allows it
     if(_info == nullptr || !_info->is_resizable())
     {
         return false;
     }
     const TensorShape &shape = _info->tensor_shape();
     PaddingSize padding;
     padding.left   = std::max(0, -_start_x);
     padding.right  = std::max<int>(0, _end_x - shape[0]);
     padding.top    = std::max(0, -_start_y);
     padding.bottom = std::max<int>(0, _end_y - shape[1]);
     // Update strides in tensor info
     return _info->extend_padding(padding);
 }
References ARM_COMPUTE_UNUSED, BorderSize::bottom, ITensorInfo::extend_padding(), ITensorInfo::is_resizable(), BorderSize::left, arm_compute::test::validation::padding, BorderSize::right, arm_compute::test::validation::shape, ITensorInfo::tensor_shape(), and BorderSize::top.
update_window_if_needed()
bool update_window_if_needed (Window & window) const override virtual
Shrink the window if padding is not large enough.
Parameters
[in] window Window used by the kernel.
Returns
True if the window has been changed.
Implements IAccessWindow.
Definition at line 84 of file AccessWindowStatic.cpp.
 {
     // If the padding is not enough and the tensor is not resizable, shrink the window to size 0
     if(_info == nullptr || _info->is_resizable())
     {
         return false;
     }
     const TensorShape &shape                = _info->tensor_shape();
     const Strides     &strides              = _info->strides_in_bytes();
     const size_t       offset_first_element = _info->offset_first_element_in_bytes();
     bool window_modified = false;
     // Calculate if padding is enough
     if(_start_y < 0)
     {
         const int front_pad_y_available = -static_cast<int>(offset_first_element / strides[1]);
         if(_start_y < front_pad_y_available)
         {
             window_modified = true;
         }
     }
     if(!window_modified)
     {
         if(_end_y > static_cast<int>(shape[1]))
         {
             const int stride_z             = _info->num_dimensions() > 2 ? strides[2] : _info->total_size();
             const int tail_pad_y_available = (stride_z / strides[1]) - shape[1];
             if(static_cast<int>(shape[1]) + tail_pad_y_available < _end_y)
             {
                 window_modified = true;
             }
         }
         if(!window_modified)
         {
             const int stride_y = _info->num_dimensions() > 1 ? strides[1] : _info->total_size();
             if(_start_x < 0)
             {
                 const int front_pad_x_available = -std::min<int>(static_cast<int>(offset_first_element), stride_y - shape[0] * strides[0]) / static_cast<int>(strides[0]);
                 if(_start_x < front_pad_x_available)
                 {
                     window_modified = true;
                 }
             }
             if(!window_modified && _end_x > static_cast<int>(shape[0]))
             {
                 const int tail_pad_x_available = (stride_y / strides[0]) - shape[0];
                 if(static_cast<int>(shape[0]) + tail_pad_x_available < _end_x)
                 {
                     window_modified = true;
                 }
             }
         }
     }
     // If padding is not enough
     if(window_modified)
     {
         for(size_t i = 0; i < Coordinates::num_max_dimensions; ++i)
         {
             window.set(i, Window::Dimension(0, 0, 1));
         }
     }
     return window_modified;
 }
References ITensorInfo::is_resizable(), ITensorInfo::num_dimensions(), Dimensions< int >::num_max_dimensions, ITensorInfo::offset_first_element_in_bytes(), Window::set(), arm_compute::test::validation::shape, ITensorInfo::strides_in_bytes(), ITensorInfo::tensor_shape(), and ITensorInfo::total_size().
The documentation for this class was generated from the following files:
arm_compute/core/AccessWindowStatic.h
src/core/AccessWindowStatic.cpp