Compute Library: Stream Class Reference
Stream Class Reference final
Stream frontend class to construct simple graphs in a stream fashion.
#include <Stream.h>
Public Member Functions
Stream (size_t id, std::string name)
Constructor.
Stream (const Stream &)=delete
Prevent instances of this class from being copied (As this class contains pointers)
Stream (Stream &&)=default
Default move constructor.
Stream & operator= (const Stream &)=delete
Prevent instances of this class from being copied (As this class contains pointers)
Stream & operator= (Stream &&)=default
Default move assignment operator.
void finalize (Target target, const GraphConfig &config)
Finalizes the stream for an execution target.
void run ()
Executes the stream.
void add_layer (ILayer &layer) override
Adds a layer to the stream.
Graph & graph () override
Returns the underlying graph.
const Graph & graph () const override
Returns the underlying graph.
Public Member Functions inherited from IStream
virtual ~IStream ()=default
NodeID tail_node ()
Returns the tail node of the Stream.
StreamHints & hints ()
Returns the stream hints that are currently used.
void forward_tail (NodeID nid)
Forwards tail of stream to a given nid.
Detailed Description
Stream frontend class to construct simple graphs in a stream fashion.
Definition at line 45 of file Stream.h.
Constructor & Destructor Documentation
Stream() [1/3]
Stream (size_t id, std::string name)
Constructor.
Parameters
[in] id Stream id
[in] name Stream name
Definition at line 35 of file Stream.cpp.
     : _ctx(), _manager(), _g(id, std::move(name))
 {
 }
Stream() [2/3]
Stream (const Stream &) delete
Prevent instances of this class from being copied (As this class contains pointers)
Stream() [3/3]
Stream (Stream &&) default
Default move constructor.
Member Function Documentation
add_layer()
void add_layer (ILayer & layer) override virtual
Adds a layer to the stream.
Parameters
[in] layer Layer to add
Implements IStream.
Definition at line 52 of file Stream.cpp.
 {
     auto nid   = layer.create_layer(*this);
     _tail_node = nid;
 }
References ILayer::create_layer().
finalize()
void finalize (Target target, const GraphConfig & config)
Finalizes the stream for an execution target.
Parameters
[in] target Execution target
[in] config (Optional) Graph configuration to use
Definition at line 40 of file Stream.cpp.
 {
     PassManager pm = create_default_pass_manager(target);
     _ctx.set_config(config);
     _manager.finalize_graph(_g, _ctx, pm, target);
 }
References arm_compute::graph::create_default_pass_manager(), GraphManager::finalize_graph(), and GraphContext::set_config().
graph() [1/2]
Graph & graph () override virtual
Returns the underlying graph.
Returns
Underlying graph
Implements IStream.
Definition at line 63 of file Stream.cpp.
 {
     return _g;
 }
graph() [2/2]
const Graph & graph () const override virtual
Returns the underlying graph.
Returns
Underlying graph
Implements IStream.
Definition at line 58 of file Stream.cpp.
 {
     return _g;
 }
operator=() [1/2]
Stream& operator= (const Stream &) delete
Prevent instances of this class from being copied (As this class contains pointers)
operator=() [2/2]
Stream& operator= (Stream &&) default
Default move assignment operator.
run()
void run ()
Executes the stream.
Definition at line 47 of file Stream.cpp.
 {
     _manager.execute_graph(_g);
 }
References GraphManager::execute_graph().
The documentation for this class was generated from the following files:
arm_compute/graph/frontend/Stream.h
src/graph/frontend/Stream.cpp