Compute Library: NEDepthwiseConvolutionLayer Class Reference
NEDepthwiseConvolutionLayer Class Reference
Basic function to execute a generic depthwise convolution.
#include <NEDepthwiseConvolutionLayer.h>
Public Member Functions
NEDepthwiseConvolutionLayer ()
Default constructor.
NEDepthwiseConvolutionLayer (const NEDepthwiseConvolutionLayer &)=delete
Prevent instances of this class from being copied (As this class contains pointers)
NEDepthwiseConvolutionLayer (NEDepthwiseConvolutionLayer &&)=default
Default move constructor.
NEDepthwiseConvolutionLayer & operator= (const NEDepthwiseConvolutionLayer &)=delete
Prevent instances of this class from being copied (As this class contains pointers)
NEDepthwiseConvolutionLayer & operator= (NEDepthwiseConvolutionLayer &&)=default
Default move assignment operator.
void configure (ITensor *input, const ITensor *weights, const ITensor *biases, ITensor *output, const PadStrideInfo &conv_info, unsigned int depth_multiplier=1, const ActivationLayerInfo &act_info=ActivationLayerInfo(), const Size2D &dilation=Size2D(1U, 1U))
Initialize the function's source, destination, weights and convolution information.
void run () override
Run the kernels contained in the function.
void prepare () override
Prepare the function for executing.
Public Member Functions inherited from IFunction
virtual ~IFunction ()=default
Destructor.
Static Public Member Functions
static Status validate (const ITensorInfo *input, const ITensorInfo *weights, const ITensorInfo *biases, const ITensorInfo *output, const PadStrideInfo &conv_info, unsigned int depth_multiplier=1, const ActivationLayerInfo &act_info=ActivationLayerInfo(), const Size2D &dilation=Size2D(1U, 1U))
Static function to check if given info will lead to a valid configuration of NEDepthwiseConvolutionLayer.
Detailed Description
Basic function to execute a generic depthwise convolution.
This function calls the following NEON kernels:
If data type is F32 and data layout is NHWC:
NEDepthwiseConvolutionLayerNativeKernel
Otherwise:
NEDepthwiseIm2ColKernel
NEDepthwiseWeightsReshapeKernel
NEGEMMMatrixVectorMultiplyKernel
NEFillBorderKernel (if pad_x or pad_y > 0)
Definition at line 294 of file NEDepthwiseConvolutionLayer.h.
Constructor & Destructor Documentation
NEDepthwiseConvolutionLayer() [1/3]
NEDepthwiseConvolutionLayer ()
Default constructor.
Definition at line 703 of file NEDepthwiseConvolutionLayer.cpp.
     : _im2col_kernel(), _weights_reshape_kernel(), _v2mm_kernel(), _depthwise_conv_kernel(), _vector_to_tensor_kernel(), _output_stage_kernel(), _fill_border(), _v2mm_input_fill_border(),
       _v2mm_weights_fill_border(), _permute_input(), _permute_weights(), _permute_output(), _activationlayer_function(), _input_reshaped(), _weights_reshaped(), _v2mm_output(), _output_reshaped(),
       _permuted_input(), _permuted_weights(), _permuted_output(), _is_prepared(false), _is_quantized(false), _is_nhwc(false), _is_activationlayer_enabled(false), _is_optimized(false),
       _original_weights(nullptr)
 {
 }
NEDepthwiseConvolutionLayer() [2/3]
NEDepthwiseConvolutionLayer (const NEDepthwiseConvolutionLayer &) delete
Prevent instances of this class from being copied (As this class contains pointers)
NEDepthwiseConvolutionLayer() [3/3]
NEDepthwiseConvolutionLayer (NEDepthwiseConvolutionLayer &&) default
Default move constructor.
Member Function Documentation
configure()
void configure (ITensor * input, const ITensor * weights, const ITensor * biases, ITensor * output, const PadStrideInfo & conv_info, unsigned int depth_multiplier = 1, const ActivationLayerInfo & act_info = ActivationLayerInfo(), const Size2D & dilation = Size2D(1U, 1U))
Initialize the function's source, destination, weights and convolution information.
Parameters
[in,out] input Source tensor. Data type supported: QASYMM8/F16/F32. (Written to only for border filling).
[out] output Destination tensor. Data type supported: same as input.
[in] weights Weights tensor. These are 3D tensors with shape [kernel_x, kernel_y, IFM]. Data type supported: Same as input.
[in] biases (Optional) Biases tensor. A 1D tensor with shape [IFM]. Must be nullptr if not needed. Data type supported: Same as input, S32 when input is QASYMM8.
[in] conv_info Padding and stride information to use for the convolution.
[in] depth_multiplier (Optional) Multiplier to apply to the input's depth in order to retrieve the output's depth. Defaults to 1.
[in] act_info (Optional) Activation layer information in case of a fused activation.
[in] dilation (Optional) Dilation, in elements, across x and y. Defaults to (1, 1).
Definition at line 711 of file NEDepthwiseConvolutionLayer.cpp.
 {
     ARM_COMPUTE_ERROR_ON_NULLPTR(input, weights, output);
     // Perform validation step
     ARM_COMPUTE_ERROR_THROW_ON(NEDepthwiseConvolutionLayer::validate(input->info(), weights->info(), (biases == nullptr) ? nullptr : biases->info(),
                                                                      output->info(), conv_info, depth_multiplier, act_info, dilation));
     _is_nhwc      = input->info()->data_layout() == DataLayout::NHWC;
     _is_optimized = _is_nhwc && input->info()->data_type() == DataType::F32;
     if(!_is_optimized)
     {
         ITensor       *input_to_use   = input;
         const ITensor *weights_to_use = weights;
         ITensor       *output_to_use  = output;
         if(_is_nhwc)
         {
             _permute_input.configure(input, &_permuted_input, PermutationVector(1U, 2U, 0U));
             _permuted_input.info()->set_data_layout(DataLayout::NCHW);
             input_to_use = &_permuted_input;
             _permute_weights.configure(weights, &_permuted_weights, PermutationVector(1U, 2U, 0U));
             _permuted_weights.info()->set_data_layout(DataLayout::NCHW);
             weights_to_use = &_permuted_weights;
         }
         const size_t weights_w = weights_to_use->info()->dimension(0);
         const size_t weights_h = weights_to_use->info()->dimension(1);
         const size_t weights_z = weights_to_use->info()->dimension(2);
         _is_quantized     = is_data_type_quantized_asymmetric(input->info()->data_type());
         _is_prepared      = false;
         _original_weights = weights_to_use;
         // Should bias be appended ?
         bool append_bias = (biases != nullptr) && !_is_quantized;
         // Calculate output shape
         TensorShape output_shape = shape_calculator::compute_depthwise_convolution_shape(*input->info(), *weights->info(), conv_info, depth_multiplier, dilation);
         // Output auto inizialitation if not yet initialized
         auto_init_if_empty(*output->info(), input->info()->clone()->set_tensor_shape(output_shape));
         ARM_COMPUTE_ERROR_ON_MISMATCHING_DIMENSIONS(output->info()->tensor_shape(), output_shape);
         if(_is_nhwc)
         {
             permute(output_shape, PermutationVector(1U, 2U, 0U));
             _permuted_output.allocator()->init(output->info()->clone()->set_is_resizable(true).reset_padding().set_tensor_shape(output_shape));
             _permuted_output.info()->set_data_layout(DataLayout::NCHW);
             _permuted_output.info()->set_quantization_info(output->info()->quantization_info());
             output_to_use = &_permuted_output;
         }
         // Output width and height
         const unsigned int conv_w = output_shape.x();
         const unsigned int conv_h = output_shape.y();
         // Set up intermediate tensors
         const size_t patch_size = weights_w * weights_h + (append_bias ? 1 : 0);
         const size_t conv_size  = conv_w * conv_h;
         // Im2Col configuration
         TensorShape shape_im2col = input_to_use->info()->tensor_shape();
         shape_im2col.set(0, patch_size);
         shape_im2col.set(1, conv_size);
         shape_im2col.set(2, weights_z);
         _input_reshaped.allocator()->init(input->info()->clone()->set_is_resizable(true).reset_padding().set_tensor_shape(shape_im2col).set_data_layout(DataLayout::NCHW));
         _im2col_kernel.configure(input_to_use, &_input_reshaped, Size2D(weights_w, weights_h), conv_info, append_bias, depth_multiplier, dilation);
         // Weights reshape configuration
         const TensorShape shape_weights_reshape(patch_size, weights_z);
         _weights_reshaped.allocator()->init(weights->info()->clone()->set_is_resizable(true).reset_padding().set_tensor_shape(shape_weights_reshape).set_data_layout(DataLayout::NCHW));
         _weights_reshape_kernel.configure(weights_to_use, &_weights_reshaped, append_bias ? biases : nullptr);
         // GEMV configuration
         DataType    v2mm_dt        = (input->info()->data_type() == DataType::QASYMM8) ? DataType::S32 : input->info()->data_type();
         TensorShape shape_v2mm_out = input_to_use->info()->tensor_shape();
         shape_v2mm_out.set(0, conv_size * weights_z);
         shape_v2mm_out.set(1, 1);
         shape_v2mm_out.set(2, 1);
         _v2mm_output.allocator()->init(input->info()->clone()->set_is_resizable(true).reset_padding().set_data_type(v2mm_dt).set_tensor_shape(shape_v2mm_out).set_data_layout(DataLayout::NCHW));
         _v2mm_kernel.configure(&_input_reshaped, &_weights_reshaped, &_v2mm_output);
         _output_reshaped.allocator()->init(_v2mm_output.info()->clone()->set_is_resizable(true).reset_padding().set_tensor_shape(output_shape));
         _vector_to_tensor_kernel.configure(&_v2mm_output, (_is_quantized) ? &_output_reshaped : output_to_use, conv_w, conv_h);
         // Output staged configuration
         if(_is_quantized)
         {
             const UniformQuantizationInfo iq_info = input->info()->quantization_info().uniform();
             const UniformQuantizationInfo wq_info = weights->info()->quantization_info().uniform();
             const UniformQuantizationInfo oq_info = output->info()->quantization_info().uniform();
             float multiplier = (iq_info.scale * wq_info.scale) / oq_info.scale;
             int   output_multiplier;
             int   output_shift;
             quantization::calculate_quantized_multiplier_less_than_one(multiplier, &output_multiplier, &output_shift);
             _output_stage_kernel.configure(&_output_reshaped, biases, output_to_use, output_multiplier, output_shift, oq_info.offset);
             _output_reshaped.allocator()->allocate();
         }
         if(_is_nhwc)
         {
             _permute_output.configure(&_permuted_output, output, PermutationVector(2U, 0U, 1U));
             _permuted_input.allocator()->allocate();
             _permuted_weights.allocator()->allocate();
             _permuted_output.allocator()->allocate();
         }
         // Fill borders on inputs
         PixelValue zero_in(static_cast<int32_t>(0));
         PixelValue zero_w(static_cast<int32_t>(0));
         if(_is_quantized)
         {
             zero_in = PixelValue(static_cast<int32_t>(input->info()->quantization_info().uniform().offset));
             zero_w  = PixelValue(static_cast<int32_t>(weights->info()->quantization_info().uniform().offset));
         }
         BorderSize border_size = _v2mm_kernel.border_size();
         _v2mm_input_fill_border.configure(&_input_reshaped, border_size, BorderMode::CONSTANT, zero_in);
         border_size.bottom = 0;
         _v2mm_weights_fill_border.configure(&_weights_reshaped, border_size, BorderMode::CONSTANT, zero_w);
         // Allocate intermediate tensors
         _input_reshaped.allocator()->allocate();
         _v2mm_output.allocator()->allocate();
     }
     else
     {
         // Configure kernel
         _depthwise_conv_kernel.configure(input, weights, biases, output, conv_info, depth_multiplier, dilation);
         // Fill input borders
         _fill_border.configure(input, _depthwise_conv_kernel.border_size(), BorderMode::CONSTANT, PixelValue(static_cast<uint64_t>(0), input->info()->data_type()));
     }
     //Configure Activation Layer
     _is_activationlayer_enabled = act_info.enabled();
     if(_is_activationlayer_enabled)
     {
         _activationlayer_function.configure(output, nullptr, act_info);
     }
 }
References arm_compute::test::validation::act_info, TensorAllocator::allocate(), Tensor::allocator(), ARM_COMPUTE_ERROR_ON_MISMATCHING_DIMENSIONS, ARM_COMPUTE_ERROR_ON_NULLPTR, ARM_COMPUTE_ERROR_THROW_ON, arm_compute::auto_init_if_empty(), NEGEMMMatrixVectorMultiplyKernel::border_size(), NEDepthwiseConvolutionLayerNativeKernel::border_size(), BorderSize::bottom, arm_compute::quantization::calculate_quantized_multiplier_less_than_one(), ICloneable< T >::clone(), TensorInfo::clone(), arm_compute::misc::shape_calculator::compute_depthwise_convolution_shape(), NEPermute::configure(), NEActivationLayer::configure(), NEGEMMMatrixVectorMultiplyKernel::configure(), NEDepthwiseWeightsReshapeKernel::configure(), NEDepthwiseVectorToTensorKernel::configure(), NEDepthwiseConvolutionLayerNativeKernel::configure(), NEDirectConvolutionLayerOutputStageKernel::configure(), NEFillBorderKernel::configure(), NEDepthwiseIm2ColKernel::configure(), arm_compute::CONSTANT, arm_compute::test::validation::conv_info, ITensorInfo::data_layout(), ITensorInfo::data_type(), arm_compute::test::validation::dilation, ITensorInfo::dimension(), arm_compute::F32, ITensor::info(), Tensor::info(), CLTensor::info(), TensorAllocator::init(), arm_compute::is_data_type_quantized_asymmetric(), arm_compute::NCHW, arm_compute::NHWC, UniformQuantizationInfo::offset, arm_compute::test::validation::output_shape, arm_compute::permute(), arm_compute::QASYMM8, ITensorInfo::quantization_info(), TensorInfo::quantization_info(), arm_compute::S32, UniformQuantizationInfo::scale, TensorShape::set(), ITensorInfo::set_data_layout(), ITensorInfo::tensor_shape(), arm_compute::U, QuantizationInfo::uniform(), NEDepthwiseConvolutionLayer::validate(), and arm_compute::test::validation::weights.
Referenced by NEDepthwiseSeparableConvolutionLayer::configure().
operator=() [1/2]
NEDepthwiseConvolutionLayer& operator= (const NEDepthwiseConvolutionLayer &) delete
Prevent instances of this class from being copied (As this class contains pointers)
operator=() [2/2]
NEDepthwiseConvolutionLayer& operator= (NEDepthwiseConvolutionLayer &&) default
Default move assignment operator.
prepare()
void prepare () override virtual
Prepare the function for executing.
Any one off pre-processing step required by the function is handled here
Note
Prepare stage might not need all the function's buffers' backing memory to be available in order to execute
Reimplemented from IFunction.
Definition at line 1011 of file NEDepthwiseConvolutionLayer.cpp.
 {
     if(!_is_prepared && !_is_optimized)
     {
         ARM_COMPUTE_ERROR_ON(!_original_weights->is_used());
         if(_is_nhwc)
         {
             _permute_weights.run();
         }
         // Run reshape and mark original weights as unused
         _weights_reshaped.allocator()->allocate();
         NEScheduler::get().schedule(&_weights_reshape_kernel, Window::DimX);
         NEScheduler::get().schedule(&_v2mm_weights_fill_border, Window::DimX);
         _original_weights->mark_as_unused();
         _is_prepared = true;
     }
 }
References TensorAllocator::allocate(), Tensor::allocator(), ARM_COMPUTE_ERROR_ON, Window::DimX, Scheduler::get(), ITensor::is_used(), ITensor::mark_as_unused(), INESimpleFunctionNoBorder::run(), and IScheduler::schedule().
Referenced by NEDepthwiseSeparableConvolutionLayer::prepare(), and NEDepthwiseConvolutionLayer::run().
run()
void run () override virtual
Run the kernels contained in the function.
For NEON kernels:
Multi-threading is used for the kernels which are parallelisable.
By default std::thread::hardware_concurrency() threads are used.
Note
CPPScheduler::set_num_threads() can be used to manually set the number of threads
For OpenCL kernels:
All the kernels are enqueued on the queue associated with CLScheduler.
The queue is then flushed.
Note
The function will not block until the kernels are executed. It is the user's responsibility to wait.
Will call prepare() on first run if hasn't been done
Implements IFunction.
Definition at line 974 of file NEDepthwiseConvolutionLayer.cpp.
 {
     if(!_is_optimized)
     {
         prepare();
         if(_is_nhwc)
         {
             _permute_input.run();
         }
         NEScheduler::get().schedule(&_im2col_kernel, Window::DimX);
         NEScheduler::get().schedule(&_v2mm_input_fill_border, Window::DimX);
         NEScheduler::get().schedule(&_v2mm_kernel, Window::DimX);
         NEScheduler::get().schedule(&_vector_to_tensor_kernel, Window::DimX);
         if(_is_quantized)
         {
             NEScheduler::get().schedule(&_output_stage_kernel, Window::DimX);
         }
         if(_is_nhwc)
         {
             _permute_output.run();
         }
     }
     else
     {
         NEScheduler::get().schedule(&_fill_border, Window::DimX);
         NEScheduler::get().schedule(&_depthwise_conv_kernel, Window::DimY);
     }
     if(_is_activationlayer_enabled)
     {
         _activationlayer_function.run();
     }
 }
References Window::DimX, Window::DimY, Scheduler::get(), NEDepthwiseConvolutionLayer::prepare(), INESimpleFunctionNoBorder::run(), and IScheduler::schedule().
Referenced by NEDepthwiseSeparableConvolutionLayer::run().
validate()
Status validate (const ITensorInfo * input, const ITensorInfo * weights, const ITensorInfo * biases, const ITensorInfo * output, const PadStrideInfo & conv_info, unsigned int depth_multiplier = 1, const ActivationLayerInfo & act_info = ActivationLayerInfo(), const Size2D & dilation = Size2D(1U, 1U)) static
Static function to check if given info will lead to a valid configuration of NEDepthwiseConvolutionLayer.
Parameters
[in] input Source tensor. Data type supported: QASYMM8/F16/F32. (Written to only for border filling).
[in] output Destination tensor. Data type supported: same as input.
[in] weights Weights tensor. These are 3D tensors with shape [kernel_x, kernel_y, IFM]. Data type supported: Same as input.
[in] biases (Optional) Biases tensor. A 1D tensor with shape [IFM]. Must be nullptr if not needed. Data type supported: Same as input, S32 when input is QASYMM8.
[in] conv_info Padding and stride information to use for the convolution.
[in] depth_multiplier (Optional) Multiplier to apply to the input's depth in order to retrieve the output's depth. Defaults to 1.
[in] act_info (Optional) Activation layer information in case of a fused activation.
[in] dilation (Optional) Dilation, in elements, across x and y. Defaults to (1, 1).
Returns
a status
Definition at line 858 of file NEDepthwiseConvolutionLayer.cpp.
 {
     ARM_COMPUTE_RETURN_ERROR_ON_NULLPTR(input, weights, output);
     ARM_COMPUTE_RETURN_ERROR_ON(input->data_layout() == DataLayout::UNKNOWN);
     ARM_COMPUTE_RETURN_ERROR_ON(dilation.x() < 1 || dilation.y() < 1);
     const unsigned int width_idx   = get_data_layout_dimension_index(input->data_layout(), DataLayoutDimension::WIDTH);
     const unsigned int height_idx  = get_data_layout_dimension_index(input->data_layout(), DataLayoutDimension::HEIGHT);
     const unsigned int channel_idx = get_data_layout_dimension_index(input->data_layout(), DataLayoutDimension::CHANNEL);
     ARM_COMPUTE_RETURN_ERROR_ON(weights->dimension(width_idx) + (weights->dimension(width_idx) - 1) * (dilation.x() - 1) > input->dimension(width_idx) + conv_info.pad_left() + conv_info.pad_right());
     ARM_COMPUTE_RETURN_ERROR_ON(weights->dimension(height_idx) + (weights->dimension(height_idx) - 1) * (dilation.y() - 1) > input->dimension(height_idx) + conv_info.pad_top() + conv_info.pad_bottom());
     ARM_COMPUTE_RETURN_ERROR_ON((input->dimension(channel_idx) * depth_multiplier) != weights->dimension(channel_idx));
     if(input->data_layout() != DataLayout::NHWC || input->data_type() != DataType::F32)
     {
         // Clone output to use auto init
         auto output_clone = output->clone();
         const ITensorInfo *input_to_use   = input;
         const ITensorInfo *weights_to_use = weights;
         const ITensorInfo *output_to_use  = output_clone.get();
         TensorShape permuted_input_shape   = input->tensor_shape();
         TensorShape permuted_weights_shape = weights->tensor_shape();
         TensorInfo  permuted_input;
         TensorInfo  permuted_weights;
         if(input->data_layout() == DataLayout::NHWC)
         {
             permute(permuted_input_shape, PermutationVector(1U, 2U, 0U));
             permute(permuted_weights_shape, PermutationVector(1U, 2U, 0U));
             permuted_input   = TensorInfo(input->clone()->set_is_resizable(true).reset_padding().set_tensor_shape(permuted_input_shape).set_data_layout(DataLayout::NCHW));
             permuted_weights = TensorInfo(weights->clone()->set_is_resizable(true).reset_padding().set_tensor_shape(permuted_weights_shape).set_data_layout(DataLayout::NCHW));
             input_to_use   = &permuted_input;
             weights_to_use = &permuted_weights;
         }
         const bool         is_quantized = is_data_type_quantized_asymmetric(input->data_type());
         const bool         append_bias  = (biases != nullptr) && !is_quantized;
         TensorShape        output_shape = shape_calculator::compute_depthwise_convolution_shape(*input, *weights, conv_info, depth_multiplier, dilation);
         const size_t       weights_w    = weights_to_use->dimension(0);
         const size_t       weights_h    = weights_to_use->dimension(1);
         const size_t       weights_z    = weights_to_use->dimension(2);
         const unsigned int conv_w       = output_shape[width_idx];
         const unsigned int conv_h       = output_shape[height_idx];
         const size_t       patch_size   = weights_w * weights_h + (append_bias ? 1 : 0);
         const size_t       conv_size    = conv_w * conv_h;
         // Output auto inizialitation if not yet initialized
         auto_init_if_empty(*output_clone, input->clone()->set_tensor_shape(output_shape));
         ARM_COMPUTE_RETURN_ERROR_ON_MISMATCHING_DIMENSIONS(output->tensor_shape(), output_shape);
         TensorInfo permuted_output;
         if(input->data_layout() == DataLayout::NHWC)
         {
             permute(output_shape, PermutationVector(1U, 2U, 0U));
             permuted_output = TensorInfo(output_clone->clone()->set_is_resizable(true).reset_padding().set_tensor_shape(output_shape).set_data_layout(DataLayout::NCHW));
             output_to_use   = &permuted_output;
         }
         // Im2Col configuration
         TensorShape shape_im2col = input_to_use->tensor_shape();
         shape_im2col.set(0, patch_size);
         shape_im2col.set(1, conv_size);
         shape_im2col.set(2, weights_z);
         TensorInfo input_reshaped(input->clone()->set_is_resizable(true).reset_padding().set_tensor_shape(shape_im2col).set_data_layout(DataLayout::NCHW));
         ARM_COMPUTE_RETURN_ON_ERROR(NEDepthwiseIm2ColKernel::validate(input_to_use, &input_reshaped, Size2D(weights_w, weights_h), conv_info, append_bias, depth_multiplier, dilation));
         // Weights reshape configuration
         const TensorShape shape_weights_reshape(patch_size, weights_z);
         TensorInfo        weights_reshaped(weights->clone()->set_is_resizable(true).reset_padding().set_tensor_shape(shape_weights_reshape).set_data_layout(DataLayout::NCHW));
         ARM_COMPUTE_RETURN_ON_ERROR(NEDepthwiseWeightsReshapeKernel::validate(weights_to_use, &weights_reshaped, append_bias ? biases : nullptr));
         // GEMV configuration
         DataType    v2mm_dt        = (input->data_type() == DataType::QASYMM8) ? DataType::S32 : input->data_type();
         TensorShape shape_v2mm_out = input_to_use->tensor_shape();
         shape_v2mm_out.set(0, conv_size * weights_z);
         shape_v2mm_out.set(1, 1);
         shape_v2mm_out.set(2, 1);
         TensorInfo v2mm_output(input->clone()->set_is_resizable(true).reset_padding().set_data_type(v2mm_dt).set_tensor_shape(shape_v2mm_out).set_data_layout(DataLayout::NCHW));
         ARM_COMPUTE_RETURN_ON_ERROR(NEGEMMMatrixVectorMultiplyKernel::validate(&input_reshaped, &weights_reshaped, &v2mm_output));
         TensorInfo output_reshaped(v2mm_output.clone()->set_is_resizable(true).reset_padding().set_tensor_shape(output_to_use->tensor_shape()));
         ARM_COMPUTE_RETURN_ON_ERROR(NEDepthwiseVectorToTensorKernel::validate(&v2mm_output, (is_quantized) ? &output_reshaped : output_to_use, conv_w, conv_h));
         if(is_quantized)
         {
             const UniformQuantizationInfo iq_info = input->quantization_info().uniform();
             const UniformQuantizationInfo wq_info = weights->quantization_info().uniform();
             const UniformQuantizationInfo oq_info = output->quantization_info().uniform();
             float multiplier = (iq_info.scale * wq_info.scale) / oq_info.scale;
             int   output_multiplier;
             int   output_shift;
             ARM_COMPUTE_RETURN_ON_ERROR(quantization::calculate_quantized_multiplier_less_than_one(multiplier, &output_multiplier, &output_shift));
             ARM_COMPUTE_RETURN_ON_ERROR(NEDirectConvolutionLayerOutputStageKernel::validate(&output_reshaped, biases, output_to_use, output_multiplier, output_shift, oq_info.offset));
         }
     }
     else
     {
         ARM_COMPUTE_RETURN_ON_ERROR(NEDepthwiseConvolutionLayerNativeKernel::validate(input, weights, biases, output, conv_info, depth_multiplier, dilation));
     }
     // Validate Activation Layer
     if(act_info.enabled())
     {
         ARM_COMPUTE_RETURN_ON_ERROR(NEActivationLayer::validate(output, nullptr, act_info));
     }
     return Status{};
 }
References arm_compute::test::validation::act_info, ARM_COMPUTE_RETURN_ERROR_ON, ARM_COMPUTE_RETURN_ERROR_ON_MISMATCHING_DIMENSIONS, ARM_COMPUTE_RETURN_ERROR_ON_NULLPTR, ARM_COMPUTE_RETURN_ON_ERROR, arm_compute::auto_init_if_empty(), arm_compute::quantization::calculate_quantized_multiplier_less_than_one(), arm_compute::CHANNEL, ICloneable< T >::clone(), arm_compute::misc::shape_calculator::compute_depthwise_convolution_shape(), arm_compute::test::validation::conv_info, ITensorInfo::data_layout(), ITensorInfo::data_type(), arm_compute::test::validation::dilation, ITensorInfo::dimension(), arm_compute::F32, arm_compute::get_data_layout_dimension_index(), arm_compute::HEIGHT, arm_compute::is_data_type_quantized_asymmetric(), arm_compute::NCHW, arm_compute::NHWC, UniformQuantizationInfo::offset, arm_compute::test::validation::output_shape, arm_compute::permute(), arm_compute::QASYMM8, ITensorInfo::quantization_info(), arm_compute::S32, UniformQuantizationInfo::scale, TensorShape::set(), ITensorInfo::tensor_shape(), arm_compute::U, QuantizationInfo::uniform(), arm_compute::UNKNOWN, NEActivationLayer::validate(), NEGEMMMatrixVectorMultiplyKernel::validate(), NEDepthwiseWeightsReshapeKernel::validate(), NEDepthwiseVectorToTensorKernel::validate(), NEDepthwiseConvolutionLayerNativeKernel::validate(), NEDirectConvolutionLayerOutputStageKernel::validate(), NEDepthwiseIm2ColKernel::validate(), arm_compute::test::validation::weights, and arm_compute::WIDTH.
Referenced by NEDepthwiseConvolutionLayer::configure().
The documentation for this class was generated from the following files:
arm_compute/runtime/NEON/functions/NEDepthwiseConvolutionLayer.h
src/runtime/NEON/functions/NEDepthwiseConvolutionLayer.cpp