Compute Library: Profiler Class Reference
Profiler Class Reference
Profiler class to collect benchmark numbers.
#include <Profiler.h>
Public Types
using MeasurementsMap = std::map< std::string, std::vector< Measurement > >
Mapping from instrument ids to their measurements.
Public Member Functions
void add (std::unique_ptr< Instrument > instrument)
Add instrument to the performance monitor.
void test_start ()
Call test_start() on all the added instruments.
void start ()
Call start() on all the added instruments.
void stop ()
Call stop() on all the added instruments.
void test_stop ()
Call test_stop() on all the added instruments.
const MeasurementsMap & measurements () const
Return measurements for all instruments.
Detailed Description
Profiler class to collect benchmark numbers.
A profiler manages multiple instruments that can collect different types of benchmarking numbers.
Definition at line 45 of file Profiler.h.
Member Typedef Documentation
MeasurementsMap
using MeasurementsMap = std::map<std::string, std::vector<Measurement> >
Mapping from instrument ids to their measurements.
Definition at line 49 of file Profiler.h.
Member Function Documentation
add()
void add (std::unique_ptr< Instrument > instrument)
Add instrument to the performance monitor.
All added instruments will be used when start or stop are called to make measurements.
Parameters
[in] instrument Instrument to be used to measure performance.
Definition at line 35 of file Profiler.cpp.
 {
     _instruments.emplace_back(std::move(instrument));
 }
Referenced by Framework::get_profiler().
measurements()
const Profiler::MeasurementsMap & measurements () const
Return measurements for all instruments.
Returns
measurements for all instruments.
Definition at line 87 of file Profiler.cpp.
 {
     return _measurements;
 }
Referenced by main().
start()
void start ()
Call start() on all the added instruments.
Called just before the run of the test starts
Definition at line 48 of file Profiler.cpp.
 {
     for(auto &instrument : _instruments)
     {
         instrument->start();
     }
 }
Referenced by main().
stop()
void stop ()
Call stop() on all the added instruments.
Called just after the run of the test ends
Definition at line 56 of file Profiler.cpp.
 {
     for(auto instrument = _instruments.rbegin(); instrument != _instruments.rend(); instrument++)
     {
         (*instrument)->stop();
     }
     for(const auto &instrument : _instruments)
     {
         for(const auto &measurement : instrument->measurements())
         {
             _measurements[instrument->id() + "/" + measurement.first].push_back(measurement.second);
         }
     }
 }
Referenced by main().
test_start()
void test_start ()
Call test_start() on all the added instruments.
Called before the test set up starts
Definition at line 40 of file Profiler.cpp.
 {
     for(auto &instrument : _instruments)
     {
         instrument->test_start();
     }
 }
test_stop()
void test_stop ()
Call test_stop() on all the added instruments.
Called after the test teardown ended
Definition at line 71 of file Profiler.cpp.
 {
     for(auto instrument = _instruments.rbegin(); instrument != _instruments.rend(); instrument++)
     {
         (*instrument)->test_stop();
     }
     for(const auto &instrument : _instruments)
     {
         for(const auto &measurement : instrument->test_measurements())
         {
             _measurements[instrument->id() + "/" + measurement.first].push_back(measurement.second);
         }
     }
 }
The documentation for this class was generated from the following files:
tests/framework/Profiler.h
tests/framework/Profiler.cpp