Compute Library: DepthwiseConvolutionLayer Class Reference
DepthwiseConvolutionLayer Class Reference final
Depthwise Convolution Layer.
#include <Layers.h>
Public Member Functions
DepthwiseConvolutionLayer (unsigned int conv_width, unsigned int conv_height, ITensorAccessorUPtr weights, ITensorAccessorUPtr bias, PadStrideInfo conv_info, int depth_multiplier=1, const QuantizationInfo weights_quant_info=QuantizationInfo(), const QuantizationInfo out_quant_info=QuantizationInfo())
Construct a depthwise convolution layer.
NodeID create_layer (IStream &s) override
Create layer and add to the given stream.
Public Member Functions inherited from ILayer
virtual ~ILayer ()=default
Default destructor.
ILayer & set_name (std::string name)
Sets the name of the layer.
const std::string & name () const
Layer name accessor.
Detailed Description
Depthwise Convolution Layer.
Definition at line 414 of file Layers.h.
Constructor & Destructor Documentation
DepthwiseConvolutionLayer()
DepthwiseConvolutionLayer (unsigned int conv_width, unsigned int conv_height, ITensorAccessorUPtr weights, ITensorAccessorUPtr bias, PadStrideInfo conv_info, int depth_multiplier = 1, const QuantizationInfo weights_quant_info = QuantizationInfo(), const QuantizationInfo out_quant_info = QuantizationInfo()) inline
Construct a depthwise convolution layer.
Parameters
[in] conv_width Convolution width.
[in] conv_height Convolution height.
[in] weights Accessor to get kernel weights from.
[in] bias Accessor to get kernel bias from.
[in] conv_info Padding and stride information.
[in] depth_multiplier (Optional) Depth multiplier parameter.
[in] weights_quant_info (Optional) Quantization info used for weights
[in] out_quant_info (Optional) Output quantization info
Definition at line 428 of file Layers.h.
         : _conv_width(conv_width),
           _conv_height(conv_height),
           _conv_info(std::move(conv_info)),
           _weights(std::move(weights)),
           _bias(std::move(bias)),
           _depth_multiplier(depth_multiplier),
           _weights_quant_info(std::move(weights_quant_info)),
           _out_quant_info(std::move(out_quant_info))
     {
     }
Member Function Documentation
create_layer()
NodeID create_layer (IStream & s) inline override virtual
Create layer and add to the given stream.
Parameters
[in] s Stream to add layer to.
Returns
ID of the created node.
Implements ILayer.
Definition at line 447 of file Layers.h.
     {
         NodeIdxPair input         = { s.tail_node(), 0 };
         NodeParams  common_params = { name(), s.hints().target_hint };
         return GraphBuilder::add_depthwise_convolution_node(s.graph(), common_params,
                                                             input, Size2D(_conv_width, _conv_height), _conv_info, _depth_multiplier,
                                                             s.hints().depthwise_convolution_method_hint,
                                                             std::move(_weights), std::move(_bias), std::move(_weights_quant_info), std::move(_out_quant_info));
     }
References GraphBuilder::add_depthwise_convolution_node(), StreamHints::depthwise_convolution_method_hint, IStream::graph(), IStream::hints(), ILayer::name(), IStream::tail_node(), and StreamHints::target_hint.
The documentation for this class was generated from the following file:
arm_compute/graph/frontend/Layers.h