Compute Library: NESpaceToBatchLayer Class Reference
NESpaceToBatchLayer Class Reference
Basic function to spatial divide a tensor.
#include <NESpaceToBatchLayer.h>
Public Member Functions
NESpaceToBatchLayer ()
Default constructor.
NESpaceToBatchLayer (const NESpaceToBatchLayer &)=delete
Prevent instances of this class from being copied (As this class contains pointers)
NESpaceToBatchLayer & operator= (const NESpaceToBatchLayer &)=delete
Prevent instances of this class from being copied (As this class contains pointers)
NESpaceToBatchLayer (NESpaceToBatchLayer &&)=default
Allow instances of this class to be moved.
NESpaceToBatchLayer & operator= (NESpaceToBatchLayer &&)=default
Allow instances of this class to be moved.
virtual ~NESpaceToBatchLayer ()=default
Default destructor.
void configure (const ITensor *input, const ITensor *block_shape, const ITensor *paddings, ITensor *output)
Set the input and output tensors.
void configure (const ITensor *input, const int block_shape_x, const int block_shape_y, const Size2D &padding_left, const Size2D &padding_right, ITensor *output)
Set the input and output tensors.
void run () override
Run the kernels contained in the function.
Public Member Functions inherited from IFunction
virtual ~IFunction ()=default
Destructor.
virtual void prepare ()
Prepare the function for executing.
Static Public Member Functions
static Status validate (const ITensorInfo *input, const ITensorInfo *block_shape, const ITensorInfo *paddings, const ITensorInfo *output)
Static function to check if given info will lead to a valid configuration of NESpaceToBatchLayer.
static Status validate (const ITensorInfo *input, const int block_shape_x, const int block_shape_y, const Size2D &padding_left, const Size2D &padding_right, const ITensorInfo *output)
Static function to check if given info will lead to a valid configuration of NESpaceToBatchLayer (Static block shape and paddings)
Detailed Description
Basic function to spatial divide a tensor.
This function calls the following NEON kernels/functions:
NEMemsetKernel
NESpaceToBatchLayerKernel
Definition at line 42 of file NESpaceToBatchLayer.h.
Constructor & Destructor Documentation
NESpaceToBatchLayer() [1/3]
NESpaceToBatchLayer ()
Default constructor.
Definition at line 35 of file NESpaceToBatchLayer.cpp.
     : _space_to_batch_kernel(), _memset_kernel(), _has_padding(false)
 {
 }
NESpaceToBatchLayer() [2/3]
NESpaceToBatchLayer (const NESpaceToBatchLayer &) delete
Prevent instances of this class from being copied (As this class contains pointers)
NESpaceToBatchLayer() [3/3]
NESpaceToBatchLayer (NESpaceToBatchLayer &&) default
Allow instances of this class to be moved.
~NESpaceToBatchLayer()
virtual ~NESpaceToBatchLayer () virtual default
Default destructor.
Member Function Documentation
configure() [1/2]
void configure (const ITensor * input, const ITensor * block_shape, const ITensor * paddings, ITensor * output)
Set the input and output tensors.
Parameters
[in] input Tensor input. Supported tensor rank: 4. Data types supported: U8/S8/QASYMM8/U16/S16/F16/U32/S32/F32.
[in] block_shape 1-D tensor with shape [M]. Data types supported: S32
[in] paddings 2-D tensor with shape [2, M]. Data types supported: S32
[out] output Tensor output. Data types supported: same as input
Definition at line 40 of file NESpaceToBatchLayer.cpp.
 {
     ARM_COMPUTE_ERROR_ON_NULLPTR(input, block_shape, paddings, output);
     if(input->info()->tensor_shape().total_size() != output->info()->tensor_shape().total_size())
     {
         _has_padding = true;
         _memset_kernel.configure(output, PixelValue(0, input->info()->data_type(), input->info()->quantization_info()));
     }
     _space_to_batch_kernel.configure(input, block_shape, paddings, output);
 }
References ARM_COMPUTE_ERROR_ON_NULLPTR, NEMemsetKernel::configure(), NESpaceToBatchLayerKernel::configure(), ITensorInfo::data_type(), ITensor::info(), ITensorInfo::quantization_info(), ITensorInfo::tensor_shape(), and TensorShape::total_size().
configure() [2/2]
void configure (const ITensor * input, const int block_shape_x, const int block_shape_y, const Size2D & padding_left, const Size2D & padding_right, ITensor * output)
Set the input and output tensors.
(Static block shape and paddings)
Parameters
[in] input Tensor input. Supported tensor rank: 4. Data types supported: U8/S8/QASYMM8/U16/S16/F16/U32/S32/F32.
[in] block_shape_x Block shape x value.
[in] block_shape_y Block shape y value.
[in] padding_left The left padding of the output tensor.
[in] padding_right The right padding of the output tensor.
[out] output Tensor output. Data types supported: same as input
Definition at line 52 of file NESpaceToBatchLayer.cpp.
 {
     ARM_COMPUTE_ERROR_ON_NULLPTR(input, output);
     if(input->info()->tensor_shape().total_size() != output->info()->tensor_shape().total_size())
     {
         _has_padding = true;
         _memset_kernel.configure(output, PixelValue(0, input->info()->data_type(), input->info()->quantization_info()));
     }
     _space_to_batch_kernel.configure(input, block_shape_x, block_shape_y, padding_left, padding_right, output);
 }
References ARM_COMPUTE_ERROR_ON_NULLPTR, NEMemsetKernel::configure(), NESpaceToBatchLayerKernel::configure(), ITensorInfo::data_type(), ITensor::info(), ITensorInfo::quantization_info(), ITensorInfo::tensor_shape(), and TensorShape::total_size().
operator=() [1/2]
NESpaceToBatchLayer& operator= (const NESpaceToBatchLayer &) delete
Prevent instances of this class from being copied (As this class contains pointers)
operator=() [2/2]
NESpaceToBatchLayer& operator= (NESpaceToBatchLayer &&) default
Allow instances of this class to be moved.
run()
void run () override virtual
Run the kernels contained in the function.
For NEON kernels:
Multi-threading is used for the kernels which are parallelisable.
By default std::thread::hardware_concurrency() threads are used.
Note
CPPScheduler::set_num_threads() can be used to manually set the number of threads
For OpenCL kernels:
All the kernels are enqueued on the queue associated with CLScheduler.
The queue is then flushed.
Note
The function will not block until the kernels are executed. It is the user's responsibility to wait.
Will call prepare() on first run if hasn't been done
Implements IFunction.
Definition at line 79 of file NESpaceToBatchLayer.cpp.
 {
     // Zero out output only if we have paddings
     if(_has_padding)
     {
         NEScheduler::get().schedule(&_memset_kernel, Window::DimY);
     }
     NEScheduler::get().schedule(&_space_to_batch_kernel, Window::DimY);
 }
References Window::DimY, Scheduler::get(), and IScheduler::schedule().
validate() [1/2]
Status validate (const ITensorInfo * input, const ITensorInfo * block_shape, const ITensorInfo * paddings, const ITensorInfo * output) static
Static function to check if given info will lead to a valid configuration of NESpaceToBatchLayer.
Parameters
[in] input Tensor input info. Supported tensor rank: 4. Data types supported: U8/S8/QASYMM8/U16/S16/F16/U32/S32/F32.
[in] block_shape block shape tensor info with shape [M]. Data types supported: S32
[in] paddings paddings tensor info with shape [2, M]. Data types supported: S32
[in] output Tensor output info. Data types supported: same as input
Returns
a status
Definition at line 64 of file NESpaceToBatchLayer.cpp.
 {
     ARM_COMPUTE_RETURN_ON_ERROR(NESpaceToBatchLayerKernel::validate(input, block_shape, paddings, output));
     return Status{};
 }
References ARM_COMPUTE_RETURN_ON_ERROR, and NESpaceToBatchLayerKernel::validate().
validate() [2/2]
Status validate (const ITensorInfo * input, const int block_shape_x, const int block_shape_y, const Size2D & padding_left, const Size2D & padding_right, const ITensorInfo * output) static
Static function to check if given info will lead to a valid configuration of NESpaceToBatchLayer (Static block shape and paddings)
Parameters
[in] input Tensor input info. Supported tensor rank: 4. Data types supported: U8/S8/QASYMM8/U16/S16/F16/U32/S32/F32.
[in] block_shape_x Block shape x value.
[in] block_shape_y Block shape y value.
[in] padding_left The left padding of the output tensor.
[in] padding_right The right padding of the output tensor.
[in] output Tensor output info. Data types supported: same as input
Returns
a status
Definition at line 71 of file NESpaceToBatchLayer.cpp.
 {
     ARM_COMPUTE_RETURN_ON_ERROR(NESpaceToBatchLayerKernel::validate(input, block_shape_x, block_shape_y, padding_left, padding_right, output));
     return Status{};
 }
References ARM_COMPUTE_RETURN_ON_ERROR, and NESpaceToBatchLayerKernel::validate().
The documentation for this class was generated from the following files:
arm_compute/runtime/NEON/functions/NESpaceToBatchLayer.h
src/runtime/NEON/functions/NESpaceToBatchLayer.cpp