Compute Library: NEComplexPixelWiseMultiplication Class Reference
NEComplexPixelWiseMultiplication Class Reference
Basic function to run NEComplexPixelWiseMultiplicationKernel.
#include <NEPixelWiseMultiplication.h>
Public Member Functions
void configure (ITensor *input1, ITensor *input2, ITensor *output)
Initialise the kernel's inputs, output.
Public Member Functions inherited from INESimpleFunction
INESimpleFunction ()
Constructor.
void run () override final
Run the kernels contained in the function.
Public Member Functions inherited from IFunction
virtual ~IFunction ()=default
Destructor.
virtual void prepare ()
Prepare the function for executing.
Static Public Member Functions
static Status validate (const ITensorInfo *input1, const ITensorInfo *input2, const ITensorInfo *output)
Static function to check if given info will lead to a valid configuration of NEComplexPixelWiseMultiplication.
Detailed Description
Basic function to run NEComplexPixelWiseMultiplicationKernel.
Definition at line 73 of file NEPixelWiseMultiplication.h.
Member Function Documentation
configure()
void configure (ITensor * input1, ITensor * input2, ITensor * output)
Initialise the kernel's inputs, output.
Parameters
[in,out] input1 An input tensor. Data types supported: F32. Number of channels supported: 2 (complex tensor). The input tensor is [in, out] because its TensorInfo might be modified inside the kernel in case of broadcasting of dimension 0.
[in,out] input2 An input tensor. Data types supported: same as input1. Number of channels supported: same as input1. The input tensor is [in, out] because its TensorInfo might be modified inside the kernel in case of broadcasting of dimension 0.
[out] output The output tensor. Data types supported: same as input1. Number of channels: same as input1.
Definition at line 55 of file NEPixelWiseMultiplication.cpp.
 {
     auto k = arm_compute::support::cpp14::make_unique<NEComplexPixelWiseMultiplicationKernel>();
     k->configure(input1, input2, output);
     _kernel = std::move(k);
     if(output->info()->dimension(0) > 1)
     {
         ITensor *broadcasted_info = (input1->info()->dimension(0) == 1) ? input1 : input2;
         if(broadcasted_info->info()->dimension(0) == 1)
         {
             _border_handler.configure(broadcasted_info, _kernel->border_size(), BorderMode::REPLICATE);
         }
     }
 }
References ITensorInfo::dimension(), ITensor::info(), and arm_compute::REPLICATE.
Referenced by NEFFTConvolutionLayer::configure().
validate()
Status validate (const ITensorInfo * input1, const ITensorInfo * input2, const ITensorInfo * output) static
Static function to check if given info will lead to a valid configuration of NEComplexPixelWiseMultiplication.
Parameters
[in] input1 An input tensor info. Data types supported: F32. Number of channels supported: 2 (complex tensor).
[in] input2 An input tensor info. Data types supported: same as input1. Number of channels supported: same as input1.
[in] output The output tensor info. Data types supported: same as input1. Number of channels supported: same as input1.
Definition at line 72 of file NEPixelWiseMultiplication.cpp.
 {
     return NEComplexPixelWiseMultiplicationKernel::validate(input1, input2, output);
 }
References NEComplexPixelWiseMultiplicationKernel::validate().
The documentation for this class was generated from the following files:
arm_compute/runtime/NEON/functions/NEPixelWiseMultiplication.h
src/runtime/NEON/functions/NEPixelWiseMultiplication.cpp