Compute Library: src/core/CL/cl_kernels/minmaxloc.cl File Reference
minmaxloc.cl File Reference
#include "helpers.h"
#include "types.h"
Macros
#define DATA_TYPE_MIN 0x0
#define DATA_TYPE_MAX 0xFF
Functions
int FloatFlip (float val)
__kernel void minmax (__global uchar *src_ptr, uint src_stride_x, uint src_step_x, uint src_stride_y, uint src_step_y, uint src_offset_first_element_in_bytes, __global int *min_max, int width)
This function identifies the min and maximum value of an input image.
__kernel void minmaxloc (__global uchar *src_ptr, uint src_stride_x, uint src_step_x, uint src_stride_y, uint src_step_y, uint src_offset_first_element_in_bytes, __global int *min_max, __global uint *min_max_count, __global Coordinates2D *min_loc, uint max_min_loc_count, __global Coordinates2D *max_loc, uint max_max_loc_count)
This function counts the min and max occurrences in an image and tags their position.
Variables
__constant DATA_TYPE16 type_min = (DATA_TYPE16)(0x0)
__constant DATA_TYPE16 type_max = (DATA_TYPE16)(0xFF)
__constant int16 idx16 = (int16)(0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15)
Macro Definition Documentation
DATA_TYPE_MAX
#define DATA_TYPE_MAX 0xFF
Definition at line 32 of file minmaxloc.cl.
DATA_TYPE_MIN
#define DATA_TYPE_MIN 0x0
Definition at line 28 of file minmaxloc.cl.
Function Documentation
FloatFlip()
int FloatFlip (float val) inline
Definition at line 35 of file minmaxloc.cl.
 {
     union
     {
         int   int_val;
         float flt_val;
     } u_val;
     u_val.flt_val = val;
     return (u_val.int_val >= 0) ? u_val.int_val : u_val.int_val ^ 0x7FFFFFFF;
 }
Referenced by minmax().
minmax()
__kernel void minmax (__global uchar * src_ptr, uint src_stride_x, uint src_step_x, uint src_stride_y, uint src_step_y, uint src_offset_first_element_in_bytes, __global int * min_max, int width)
This function identifies the min and maximum value of an input image.
Note
Input image data type must be passed as a preprocessor argument using -DDATA_TYPE. Moreover, the minimum and maximum value of the given data type must be provided using -DDATA_TYPE_MIN and -DDATA_TYPE_MAX respectively.
In case image width is not a multiple of 16 then -DNON_MULTIPLE_OF_16 must be passed.
Parameters
[in] src_ptr Pointer to the source image. Supported data types: U8
[in] src_stride_x Stride of the source image in X dimension (in bytes)
[in] src_step_x src_stride_x * number of elements along X processed per workitem(in bytes)
[in] src_stride_y Stride of the source image in Y dimension (in bytes)
[in] src_step_y src_stride_y * number of elements along Y processed per workitem(in bytes)
[in] src_offset_first_element_in_bytes The offset of the first element in the source image
[out] min_max Pointer to buffer with minimum value in position 0 and maximum value in position 1
[in] width Input image width
Definition at line 65 of file minmaxloc.cl.
 {
     Image src = CONVERT_TO_IMAGE_STRUCT(src);
     // Initialize local minimum and local maximum
     VEC_DATA_TYPE(DATA_TYPE, 16)
     local_min = type_max;
     VEC_DATA_TYPE(DATA_TYPE, 16)
     local_max = type_min;
     // Calculate min/max of row
     int i = 0;
     for(; i + 16 <= width; i += 16)
     {
         VEC_DATA_TYPE(DATA_TYPE, 16)
         data      = vload16(0, (__global DATA_TYPE *)offset(&src, i, 0));
         local_min = min(data, local_min);
         local_max = max(data, local_max);
     }
 #ifdef NON_MULTIPLE_OF_16
     // Handle non multiple of 16
     VEC_DATA_TYPE(DATA_TYPE, 16)
     data = vload16(0, (__global DATA_TYPE *)offset(&src, i, 0));
 #ifdef IS_DATA_TYPE_FLOAT
     int16 valid_indices = (i + idx16) < width;
 #else  /* IS_DATA_TYPE_FLOAT */
     VEC_DATA_TYPE(DATA_TYPE, 16)
     valid_indices = CONVERT((i + idx16) < width, VEC_DATA_TYPE(DATA_TYPE, 16));
 #endif /* IS_DATA_TYPE_FLOAT */
     local_max = max(local_max, select(type_min, data, valid_indices));
     local_min = min(local_min, select(type_max, data, valid_indices));
 #endif /* NON_MULTIPLE_OF_16 */
     // Perform min/max reduction
     local_min.s01234567 = min(local_min.s01234567, local_min.s89ABCDEF);
     local_max.s01234567 = max(local_max.s01234567, local_max.s89ABCDEF);
     local_min.s0123 = min(local_min.s0123, local_min.s4567);
     local_max.s0123 = max(local_max.s0123, local_max.s4567);
     local_min.s01 = min(local_min.s01, local_min.s23);
     local_max.s01 = max(local_max.s01, local_max.s23);
     local_min.s0 = min(local_min.s0, local_min.s1);
     local_max.s0 = max(local_max.s0, local_max.s1);
     // Update global min/max
 #ifdef IS_DATA_TYPE_FLOAT
     atomic_min(&min_max[0], FloatFlip(local_min.s0));
     atomic_max(&min_max[1], FloatFlip(local_max.s0));
 #else  /* IS_DATA_TYPE_FLOAT */
     atomic_min(&min_max[0], local_min.s0);
     atomic_max(&min_max[1], local_max.s0);
 #endif /* IS_DATA_TYPE_FLOAT */
 }
References CONVERT, CONVERT_TO_IMAGE_STRUCT, DATA_TYPE, FloatFlip(), idx16, offset(), arm_compute::test::validation::select, arm_compute::test::validation::src, type_max, type_min, and VEC_DATA_TYPE.
minmaxloc()
__kernel void minmaxloc (__global uchar * src_ptr, uint src_stride_x, uint src_step_x, uint src_stride_y, uint src_step_y, uint src_offset_first_element_in_bytes, __global int * min_max, __global uint * min_max_count, __global Coordinates2D * min_loc, uint max_min_loc_count, __global Coordinates2D * max_loc, uint max_max_loc_count)
This function counts the min and max occurrences in an image and tags their position.
Note
-DCOUNT_MIN_MAX should be specified if we want to count the occurrences of the minimum and maximum values.
-DLOCATE_MIN and/or -DLOCATE_MAX should be specified if we want to store the position of each occurrence on the given array.
Parameters
[in] src_ptr Pointer to the source image. Supported data types: U8
[in] src_stride_x Stride of the source image in X dimension (in bytes)
[in] src_step_x src_stride_x * number of elements along X processed per workitem(in bytes)
[in] src_stride_y Stride of the source image in Y dimension (in bytes)
[in] src_step_y src_stride_y * number of elements along Y processed per workitem(in bytes)
[in] src_offset_first_element_in_bytes The offset of the first element in the source image
[in] min_max Pointer to buffer with minimum value in position 0 and maximum value in position 1
[out] min_max_count Pointer to buffer with minimum value occurrences in position 0 and maximum value occurrences in position 1
[out] min_loc Array that holds the location of the minimum value occurrences
[in] max_min_loc_count The maximum number of min value occurrences coordinates the array can hold
[out] max_loc Array that holds the location of the maximum value occurrences
[in] max_max_loc_count The maximum number of max value occurrences coordinates the array can hold
Definition at line 143 of file minmaxloc.cl.
 {
     Image src = CONVERT_TO_IMAGE_STRUCT(src);
 #ifdef IS_DATA_TYPE_FLOAT
     __global float *min_max_ptr = (__global float *)min_max;
     float           min_value   = min_max_ptr[0];
     float           max_value   = min_max_ptr[1];
 #else  /* IS_DATA_TYPE_FLOAT */
     int min_value = min_max[0];
     int max_value = min_max[1];
 #endif /* IS_DATA_TYPE_FLOAT */
     DATA_TYPE value = *((__global DATA_TYPE *)src.ptr);
 #ifdef COUNT_MIN_MAX
     if(value == min_value)
     {
         uint idx = atomic_inc(&min_max_count[0]);
 #ifdef LOCATE_MIN
         if(idx < max_min_loc_count)
         {
             min_loc[idx].x = get_global_id(0);
             min_loc[idx].y = get_global_id(1);
         }
 #endif /* LOCATE_MIN */
     }
     if(value == max_value)
     {
         uint idx = atomic_inc(&min_max_count[1]);
 #ifdef LOCATE_MAX
         if(idx < max_max_loc_count)
         {
             max_loc[idx].x = get_global_id(0);
             max_loc[idx].y = get_global_id(1);
         }
 #endif /* LOCATE_MAX */
     }
 #endif /* COUNT_MIN_MAX */
 }
References CONVERT_TO_IMAGE_STRUCT, DATA_TYPE, and arm_compute::test::validation::src.
Variable Documentation
idx16
__constant int16 idx16 = (int16)(0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15)
Definition at line 48 of file minmaxloc.cl.
Referenced by minmax().
type_max
__constant DATA_TYPE16 type_max = (DATA_TYPE16)(0xFF)
Definition at line 47 of file minmaxloc.cl.
Referenced by minmax().
type_min
__constant DATA_TYPE16 type_min = (DATA_TYPE16)(0x0)
Definition at line 46 of file minmaxloc.cl.
Referenced by minmax().