Compute Library: arm_compute::test::validation::reference Namespace Reference
arm_compute::test::validation::reference Namespace Reference
Enumerations
enum ArithmeticOperation { ADD, SUB }
Arithmetic operation types.
enum FFTDirection { Forward, Inverse }
enum WinogradTransformType { INPUT, FILTER, OUTPUT }
Winograd transform type.
Functions
template<typename T >
SimpleTensor< T > absolute_difference (const SimpleTensor< T > &src1, const SimpleTensor< T > &src2, DataType dst_data_type)
template SimpleTensor< uint8_t > absolute_difference (const SimpleTensor< uint8_t > &src1, const SimpleTensor< uint8_t > &src2, DataType dst_data_type)
template SimpleTensor< int16_t > absolute_difference (const SimpleTensor< int16_t > &src1, const SimpleTensor< int16_t > &src2, DataType dst_data_type)
template SimpleTensor< int8_t > absolute_difference (const SimpleTensor< int8_t > &src1, const SimpleTensor< int8_t > &src2, DataType dst_data_type)
template<typename T1 , typename T2 >
SimpleTensor< T2 > accumulate (const SimpleTensor< T1 > &src, DataType output_data_type)
template<typename T1 , typename T2 >
SimpleTensor< T2 > accumulate_weighted (const SimpleTensor< T1 > &src, float alpha, DataType output_data_type)
template<typename T1 , typename T2 >
SimpleTensor< T2 > accumulate_squared (const SimpleTensor< T1 > &src, uint32_t shift, DataType output_data_type)
template SimpleTensor< int16_t > accumulate (const SimpleTensor< uint8_t > &src, DataType output_data_type)
template SimpleTensor< uint8_t > accumulate_weighted (const SimpleTensor< uint8_t > &src, float alpha, DataType output_data_type)
template SimpleTensor< int16_t > accumulate_squared (const SimpleTensor< uint8_t > &src, uint32_t shift, DataType output_data_type)
template<typename T >
SimpleTensor< T > activation_layer (const SimpleTensor< T > &src, ActivationLayerInfo info, const QuantizationInfo &oq_info)
template<>
SimpleTensor< uint8_t > activation_layer< uint8_t > (const SimpleTensor< uint8_t > &src, ActivationLayerInfo info, const QuantizationInfo &oq_info)
template<>
SimpleTensor< int16_t > activation_layer< int16_t > (const SimpleTensor< int16_t > &src, ActivationLayerInfo info, const QuantizationInfo &oq_info)
template SimpleTensor< float > activation_layer (const SimpleTensor< float > &src, ActivationLayerInfo info, const QuantizationInfo &oq_info)
template SimpleTensor< half > activation_layer (const SimpleTensor< half > &src, ActivationLayerInfo info, const QuantizationInfo &oq_info)
template<typename T >
T activate_float (T x, T a, T b, ActivationLayerInfo::ActivationFunction activation)
template<typename T >
SimpleTensor< T > arithmetic_division (const SimpleTensor< T > &src1, const SimpleTensor< T > &src2, DataType data_type)
template SimpleTensor< half > arithmetic_division (const SimpleTensor< half > &src1, const SimpleTensor< half > &src2, DataType data_type)
template SimpleTensor< float > arithmetic_division (const SimpleTensor< float > &src1, const SimpleTensor< float > &src2, DataType data_type)
template<typename T >
SimpleTensor< T > arithmetic_operation (ArithmeticOperation op, const SimpleTensor< T > &src1, const SimpleTensor< T > &src2, SimpleTensor< T > &dst, ConvertPolicy convert_policy)
template<>
SimpleTensor< uint8_t > arithmetic_operation (ArithmeticOperation op, const SimpleTensor< uint8_t > &src1, const SimpleTensor< uint8_t > &src2, SimpleTensor< uint8_t > &dst, ConvertPolicy convert_policy)
template<>
SimpleTensor< int16_t > arithmetic_operation (ArithmeticOperation op, const SimpleTensor< int16_t > &src1, const SimpleTensor< int16_t > &src2, SimpleTensor< int16_t > &dst, ConvertPolicy convert_policy)
template SimpleTensor< int8_t > arithmetic_operation (ArithmeticOperation op, const SimpleTensor< int8_t > &src1, const SimpleTensor< int8_t > &src2, SimpleTensor< int8_t > &dst, ConvertPolicy convert_policy)
template SimpleTensor< half > arithmetic_operation (ArithmeticOperation op, const SimpleTensor< half > &src1, const SimpleTensor< half > &src2, SimpleTensor< half > &dst, ConvertPolicy convert_policy)
template SimpleTensor< float > arithmetic_operation (ArithmeticOperation op, const SimpleTensor< float > &src1, const SimpleTensor< float > &src2, SimpleTensor< float > &dst, ConvertPolicy convert_policy)
template<typename T >
SimpleTensor< T > arithmetic_operation (ArithmeticOperation op, const SimpleTensor< T > &src1, const SimpleTensor< T > &src2, DataType dst_data_type, ConvertPolicy convert_policy)
template SimpleTensor< int16_t > arithmetic_operation (ArithmeticOperation op, const SimpleTensor< int16_t > &src1, const SimpleTensor< int16_t > &src2, DataType dst_data_type, ConvertPolicy convert_policy)
template SimpleTensor< int8_t > arithmetic_operation (ArithmeticOperation op, const SimpleTensor< int8_t > &src1, const SimpleTensor< int8_t > &src2, DataType dst_data_type, ConvertPolicy convert_policy)
template SimpleTensor< half > arithmetic_operation (ArithmeticOperation op, const SimpleTensor< half > &src1, const SimpleTensor< half > &src2, DataType dst_data_type, ConvertPolicy convert_policy)
template SimpleTensor< float > arithmetic_operation (ArithmeticOperation op, const SimpleTensor< float > &src1, const SimpleTensor< float > &src2, DataType dst_data_type, ConvertPolicy convert_policy)
template<typename T , typename std::enable_if< is_floating_point< T >::value, int >::type * >
SimpleTensor< T > batch_normalization_layer (const SimpleTensor< T > &src, const SimpleTensor< T > &mean, const SimpleTensor< T > &var, const SimpleTensor< T > &beta, const SimpleTensor< T > &gamma, float epsilon, ActivationLayerInfo act_info)
template SimpleTensor< float > batch_normalization_layer (const SimpleTensor< float > &src, const SimpleTensor< float > &mean, const SimpleTensor< float > &var, const SimpleTensor< float > &beta, const SimpleTensor< float > &gamma, float epsilon, ActivationLayerInfo act_info)
template SimpleTensor< half > batch_normalization_layer (const SimpleTensor< half > &src, const SimpleTensor< half > &mean, const SimpleTensor< half > &var, const SimpleTensor< half > &beta, const SimpleTensor< half > &gamma, float epsilon, ActivationLayerInfo act_info)
template<typename T >
SimpleTensor< T > batch_to_space (const SimpleTensor< T > &src, const SimpleTensor< int32_t > &block_shape, const TensorShape &dst_shape)
template SimpleTensor< float > batch_to_space (const SimpleTensor< float > &src, const SimpleTensor< int32_t > &block_shape, const TensorShape &dst_shape)
template SimpleTensor< half > batch_to_space (const SimpleTensor< half > &src, const SimpleTensor< int32_t > &block_shape, const TensorShape &dst_shape)
template<typename T >
SimpleTensor< T > bitwise_and (const SimpleTensor< T > &src1, const SimpleTensor< T > &src2)
template SimpleTensor< uint8_t > bitwise_and (const SimpleTensor< uint8_t > &src1, const SimpleTensor< uint8_t > &src2)
template<typename T >
SimpleTensor< T > bitwise_not (const SimpleTensor< T > &src)
template SimpleTensor< uint8_t > bitwise_not (const SimpleTensor< uint8_t > &src)
template<typename T >
SimpleTensor< T > bitwise_or (const SimpleTensor< T > &src1, const SimpleTensor< T > &src2)
template SimpleTensor< uint8_t > bitwise_or (const SimpleTensor< uint8_t > &src1, const SimpleTensor< uint8_t > &src2)
template<typename T >
SimpleTensor< T > bitwise_xor (const SimpleTensor< T > &src1, const SimpleTensor< T > &src2)
template SimpleTensor< uint8_t > bitwise_xor (const SimpleTensor< uint8_t > &src1, const SimpleTensor< uint8_t > &src2)
template<typename T >
SimpleTensor< T > bounding_box_transform (const SimpleTensor< T > &boxes, const SimpleTensor< T > &deltas, const BoundingBoxTransformInfo &info)
template SimpleTensor< float > bounding_box_transform (const SimpleTensor< float > &boxes, const SimpleTensor< float > &deltas, const BoundingBoxTransformInfo &info)
template SimpleTensor< half > bounding_box_transform (const SimpleTensor< half > &boxes, const SimpleTensor< half > &deltas, const BoundingBoxTransformInfo &info)
template<typename T >
SimpleTensor< T > box3x3 (const SimpleTensor< T > &src, BorderMode border_mode, T constant_border_value)
template SimpleTensor< uint8_t > box3x3 (const SimpleTensor< uint8_t > &src, BorderMode border_mode, uint8_t constant_border_value)
template<typename T >
SimpleTensor< T > canny_edge_detector (const SimpleTensor< T > &src, int32_t upper_thresh, int32_t lower_thresh, int gradient_size, MagnitudeType norm_type, BorderMode border_mode, T constant_border_value)
template SimpleTensor< uint8_t > canny_edge_detector (const SimpleTensor< uint8_t > &src, int32_t upper_thresh, int32_t lower_thresh, int gradient_size, MagnitudeType norm_type, BorderMode border_mode, uint8_t constant_border_value)
template<typename T >
std::vector< SimpleTensor< T > > channel_combine (const TensorShape &shape, const std::vector< SimpleTensor< T >> &image_planes, Format format)
template std::vector< SimpleTensor< uint8_t > > channel_combine (const TensorShape &shape, const std::vector< SimpleTensor< uint8_t >> &image_planes, Format format)
template<typename T >
SimpleTensor< uint8_t > channel_extract (const TensorShape &shape, const std::vector< SimpleTensor< T >> &tensor_planes, Format format, Channel channel)
template SimpleTensor< uint8_t > channel_extract (const TensorShape &shape, const std::vector< SimpleTensor< uint8_t >> &tensor_planes, Format format, Channel channel)
template<typename T >
SimpleTensor< T > channel_shuffle (const SimpleTensor< T > &src, int num_groups)
template SimpleTensor< uint8_t > channel_shuffle (const SimpleTensor< uint8_t > &src, int num_groups)
template SimpleTensor< uint16_t > channel_shuffle (const SimpleTensor< uint16_t > &src, int num_groups)
template SimpleTensor< uint32_t > channel_shuffle (const SimpleTensor< uint32_t > &src, int num_groups)
template SimpleTensor< half > channel_shuffle (const SimpleTensor< half > &src, int num_groups)
template SimpleTensor< float > channel_shuffle (const SimpleTensor< float > &src, int num_groups)
template<typename T >
SimpleTensor< T > col2im (const SimpleTensor< T > &src, const TensorShape &dst_shape, unsigned int num_groups)
template SimpleTensor< float > col2im (const SimpleTensor< float > &src, const TensorShape &dst_shape, unsigned int num_groups)
template SimpleTensor< half > col2im (const SimpleTensor< half > &src, const TensorShape &dst_shape, unsigned int num_groups)
template SimpleTensor< uint8_t > col2im (const SimpleTensor< uint8_t > &src, const TensorShape &dst_shape, unsigned int num_groups)
template<typename T >
std::vector< SimpleTensor< T > > color_convert (const TensorShape &shape, const std::vector< SimpleTensor< T >> &tensor_planes, Format src_format, Format dst_format)
template std::vector< SimpleTensor< uint8_t > > color_convert (const TensorShape &shape, const std::vector< SimpleTensor< uint8_t >> &tensor_planes, Format src_format, Format dst_format)
template<typename T >
SimpleTensor< uint8_t > compare (ComparisonOperation op, const SimpleTensor< T > &src1, const SimpleTensor< T > &src2)
template<>
SimpleTensor< uint8_t > compare (ComparisonOperation op, const SimpleTensor< uint8_t > &src1, const SimpleTensor< uint8_t > &src2)
template SimpleTensor< uint8_t > compare (ComparisonOperation op, const SimpleTensor< half > &src1, const SimpleTensor< half > &src2)
template SimpleTensor< uint8_t > compare (ComparisonOperation op, const SimpleTensor< float > &src1, const SimpleTensor< float > &src2)
template<typename T >
SimpleTensor< T > compute_all_anchors (const SimpleTensor< T > &anchors, const ComputeAnchorsInfo &info)
template SimpleTensor< float > compute_all_anchors (const SimpleTensor< float > &anchors, const ComputeAnchorsInfo &info)
template SimpleTensor< half > compute_all_anchors (const SimpleTensor< half > &anchors, const ComputeAnchorsInfo &info)
template<typename T >
SimpleTensor< T > concatenate_layer (std::vector< SimpleTensor< T >> &srcs, SimpleTensor< T > &dst, unsigned int axis)
template SimpleTensor< float > concatenate_layer (std::vector< SimpleTensor< float >> &srcs, SimpleTensor< float > &dst, unsigned int axis)
template SimpleTensor< half > concatenate_layer (std::vector< SimpleTensor< half >> &srcs, SimpleTensor< half > &dst, unsigned int axis)
template SimpleTensor< uint8_t > concatenate_layer (std::vector< SimpleTensor< uint8_t >> &srcs, SimpleTensor< uint8_t > &dst, unsigned int axis)
template<typename T >
SimpleTensor< T > convert_fully_connected_weights (const SimpleTensor< T > &src, const TensorShape &original_input_shape, const DataLayout training_data_layout)
template SimpleTensor< uint8_t > convert_fully_connected_weights (const SimpleTensor< uint8_t > &src, const TensorShape &original_input_shape, const DataLayout training_data_layout)
template SimpleTensor< half > convert_fully_connected_weights (const SimpleTensor< half > &src, const TensorShape &original_input_shape, const DataLayout training_data_layout)
template SimpleTensor< float > convert_fully_connected_weights (const SimpleTensor< float > &src, const TensorShape &original_input_shape, const DataLayout training_data_layout)
template<typename T >
SimpleTensor< T > convolution (const SimpleTensor< uint8_t > &src, DataType output_data_type, const int16_t *conv, uint32_t scale, BorderMode border_mode, uint8_t constant_border_value, const unsigned int width, const unsigned int height)
template<typename T , typename TB >
SimpleTensor< T > convolution_layer_nchw (const SimpleTensor< T > &src, const SimpleTensor< T > &weights, const SimpleTensor< TB > &bias, SimpleTensor< T > &dst, const PadStrideInfo &info, const Size2D &dilation, unsigned int num_groups)
template<typename T , typename TB >
SimpleTensor< T > convolution_layer (const SimpleTensor< T > &src, const SimpleTensor< T > &weights, const SimpleTensor< TB > &bias, const TensorShape &output_shape, const PadStrideInfo &info, const Size2D &dilation, unsigned int num_groups, QuantizationInfo out_quant_info)
template SimpleTensor< float > convolution_layer (const SimpleTensor< float > &src, const SimpleTensor< float > &weights, const SimpleTensor< float > &bias, const TensorShape &output_shape, const PadStrideInfo &info, const Size2D &dilation, unsigned int num_groups, QuantizationInfo out_quant_info)
template SimpleTensor< half > convolution_layer (const SimpleTensor< half > &src, const SimpleTensor< half > &weights, const SimpleTensor< half > &bias, const TensorShape &output_shape, const PadStrideInfo &info, const Size2D &dilation, unsigned int num_groups, QuantizationInfo out_quant_info)
template SimpleTensor< uint8_t > convolution_layer (const SimpleTensor< uint8_t > &src, const SimpleTensor< uint8_t > &weights, const SimpleTensor< int32_t > &bias, const TensorShape &output_shape, const PadStrideInfo &info, const Size2D &dilation, unsigned int num_groups, QuantizationInfo out_quant_info)
template<typename T >
SimpleTensor< T > copy (const SimpleTensor< T > &src, const TensorShape &output_shape)
template SimpleTensor< uint8_t > copy (const SimpleTensor< uint8_t > &src, const TensorShape &output_shape)
template SimpleTensor< int8_t > copy (const SimpleTensor< int8_t > &src, const TensorShape &output_shape)
template SimpleTensor< uint16_t > copy (const SimpleTensor< uint16_t > &src, const TensorShape &output_shape)
template SimpleTensor< int16_t > copy (const SimpleTensor< int16_t > &src, const TensorShape &output_shape)
template SimpleTensor< uint32_t > copy (const SimpleTensor< uint32_t > &src, const TensorShape &output_shape)
template SimpleTensor< int32_t > copy (const SimpleTensor< int32_t > &src, const TensorShape &output_shape)
template SimpleTensor< half > copy (const SimpleTensor< half > &src, const TensorShape &output_shape)
template SimpleTensor< float > copy (const SimpleTensor< float > &src, const TensorShape &output_shape)
template<typename T >
SimpleTensor< float > crop_and_resize (const SimpleTensor< T > &src, const SimpleTensor< float > &boxes, SimpleTensor< int32_t > box_ind, Coordinates2D crop_size, InterpolationPolicy method, float extrapolation_value)
template SimpleTensor< float > crop_and_resize (const SimpleTensor< float > &src, const SimpleTensor< float > &boxes, SimpleTensor< int32_t > box_ind, Coordinates2D crop_size, InterpolationPolicy method, float extrapolation_value)
template SimpleTensor< float > crop_and_resize (const SimpleTensor< uint16_t > &src, const SimpleTensor< float > &boxes, SimpleTensor< int32_t > box_ind, Coordinates2D crop_size, InterpolationPolicy method, float extrapolation_value)
template SimpleTensor< float > crop_and_resize (const SimpleTensor< uint32_t > &src, const SimpleTensor< float > &boxes, SimpleTensor< int32_t > box_ind, Coordinates2D crop_size, InterpolationPolicy method, float extrapolation_value)
template SimpleTensor< float > crop_and_resize (const SimpleTensor< int16_t > &src, const SimpleTensor< float > &boxes, SimpleTensor< int32_t > box_ind, Coordinates2D crop_size, InterpolationPolicy method, float extrapolation_value)
template SimpleTensor< float > crop_and_resize (const SimpleTensor< int32_t > &src, const SimpleTensor< float > &boxes, SimpleTensor< int32_t > box_ind, Coordinates2D crop_size, InterpolationPolicy method, float extrapolation_value)
template SimpleTensor< float > crop_and_resize (const SimpleTensor< half > &src, const SimpleTensor< float > &boxes, SimpleTensor< int32_t > box_ind, Coordinates2D crop_size, InterpolationPolicy method, float extrapolation_value)
template<typename T , typename TB >
SimpleTensor< T > deconvolution_layer (const SimpleTensor< T > &src, const SimpleTensor< T > &weights, const SimpleTensor< TB > &bias, const TensorShape &output_shape, const PadStrideInfo &info)
Deconvolution reference implementation.
template SimpleTensor< uint8_t > deconvolution_layer (const SimpleTensor< uint8_t > &src, const SimpleTensor< uint8_t > &weights, const SimpleTensor< int32_t > &bias, const TensorShape &output_shape, const PadStrideInfo &info)
template SimpleTensor< float > deconvolution_layer (const SimpleTensor< float > &src, const SimpleTensor< float > &weights, const SimpleTensor< float > &bias, const TensorShape &output_shape, const PadStrideInfo &info)
template SimpleTensor< half > deconvolution_layer (const SimpleTensor< half > &src, const SimpleTensor< half > &weights, const SimpleTensor< half > &bias, const TensorShape &output_shape, const PadStrideInfo &info)
template<typename T >
SimpleTensor< T > depthconcatenate_layer (const std::vector< SimpleTensor< T >> &srcs, SimpleTensor< T > &dst)
template SimpleTensor< uint8_t > depthconcatenate_layer (const std::vector< SimpleTensor< uint8_t >> &srcs, SimpleTensor< uint8_t > &dst)
template SimpleTensor< float > depthconcatenate_layer (const std::vector< SimpleTensor< float >> &srcs, SimpleTensor< float > &dst)
template SimpleTensor< half > depthconcatenate_layer (const std::vector< SimpleTensor< half >> &srcs, SimpleTensor< half > &dst)
template<typename T1 , typename T2 , typename std::enable_if< std::is_integral< T1 >::value &&!std::is_same< T1, T2 >::value, int >::type >
SimpleTensor< T2 > depth_convert (const SimpleTensor< T1 > &src, DataType dt_out, ConvertPolicy policy, uint32_t shift)
template SimpleTensor< int8_t > depth_convert (const SimpleTensor< uint8_t > &src, DataType dt_out, ConvertPolicy policy, uint32_t shift)
template SimpleTensor< uint8_t > depth_convert (const SimpleTensor< int8_t > &src, DataType dt_out, ConvertPolicy policy, uint32_t shift)
template SimpleTensor< uint8_t > depth_convert (const SimpleTensor< uint16_t > &src, DataType dt_out, ConvertPolicy policy, uint32_t shift)
template SimpleTensor< uint8_t > depth_convert (const SimpleTensor< int16_t > &src, DataType dt_out, ConvertPolicy policy, uint32_t shift)
template SimpleTensor< uint8_t > depth_convert (const SimpleTensor< uint32_t > &src, DataType dt_out, ConvertPolicy policy, uint32_t shift)
template SimpleTensor< uint8_t > depth_convert (const SimpleTensor< int32_t > &src, DataType dt_out, ConvertPolicy policy, uint32_t shift)
template SimpleTensor< uint8_t > depth_convert (const SimpleTensor< half > &src, DataType dt_out, ConvertPolicy policy, uint32_t shift)
template SimpleTensor< uint8_t > depth_convert (const SimpleTensor< float > &src, DataType dt_out, ConvertPolicy policy, uint32_t shift)
template<typename T >
SimpleTensor< T > depth_to_space (const SimpleTensor< T > &src, const TensorShape &dst_shape, int32_t block_shape)
template SimpleTensor< float > depth_to_space (const SimpleTensor< float > &src, const TensorShape &dst_shape, int32_t block_shape)
template SimpleTensor< half > depth_to_space (const SimpleTensor< half > &src, const TensorShape &dst_shape, int32_t block_shape)
template<typename T , typename TB >
SimpleTensor< T > depthwise_convolution (const SimpleTensor< T > &src, const SimpleTensor< T > &weights, const SimpleTensor< TB > &biases, const TensorShape &dst_shape, const PadStrideInfo &conv_info, unsigned int depth_multiplier, const Size2D &dilation, const QuantizationInfo &out_quant_info)
Perform a depthwise convolution.
template<>
SimpleTensor< uint8_t > depthwise_convolution (const SimpleTensor< uint8_t > &src, const SimpleTensor< uint8_t > &weights, const SimpleTensor< int32_t > &biases, const TensorShape &dst_shape, const PadStrideInfo &conv_info, unsigned int depth_multiplier, const Size2D &dilation, const QuantizationInfo &out_quant_info)
template SimpleTensor< float > depthwise_convolution (const SimpleTensor< float > &src, const SimpleTensor< float > &weights, const SimpleTensor< float > &biases, const TensorShape &dst_shape, const PadStrideInfo &conv_info, unsigned int depth_multiplier, const Size2D &dilation, const QuantizationInfo &out_quant_info)
template SimpleTensor< half > depthwise_convolution (const SimpleTensor< half > &src, const SimpleTensor< half > &weights, const SimpleTensor< half > &biases, const TensorShape &dst_shape, const PadStrideInfo &conv_info, unsigned int depth_multiplier, const Size2D &dilation, const QuantizationInfo &out_quant_info)
template<typename T >
SimpleTensor< T > depthwise_separable_convolution_layer (const SimpleTensor< T > &src, const SimpleTensor< T > &depthwise_weights, const SimpleTensor< T > &depthwise_biases, const TensorShape &depthwise_out_shape, const SimpleTensor< T > &pointwise_weights, const SimpleTensor< T > &pointwise_biases, const TensorShape &dst_shape, const PadStrideInfo &depthwise_conv_info, const PadStrideInfo &pointwise_conv_info)
template SimpleTensor< float > depthwise_separable_convolution_layer (const SimpleTensor< float > &in, const SimpleTensor< float > &depthwise_weights, const SimpleTensor< float > &depthwise_biases, const TensorShape &depthwise_out_shape, const SimpleTensor< float > &pointwise_weights, const SimpleTensor< float > &pointwise_biases, const TensorShape &dst_shape, const PadStrideInfo &depthwise_conv_info, const PadStrideInfo &pointwise_conv_info)
template<typename TOut , typename TIn >
SimpleTensor< TOut > dequantization_layer (const SimpleTensor< TIn > &src)
template SimpleTensor< half > dequantization_layer (const SimpleTensor< uint8_t > &src)
template SimpleTensor< half > dequantization_layer (const SimpleTensor< int8_t > &src)
template SimpleTensor< half > dequantization_layer (const SimpleTensor< int16_t > &src)
template<typename T , typename U >
std::pair< SimpleTensor< T >, SimpleTensor< T > > derivative (const SimpleTensor< U > &src, BorderMode border_mode, uint8_t constant_border_value, GradientDimension gradient_dimension)
template std::pair< SimpleTensor< int16_t >, SimpleTensor< int16_t > > derivative (const SimpleTensor< uint8_t > &src, BorderMode border_mode, uint8_t constant_border_value, GradientDimension gradient_dimension)
template<typename T >
SimpleTensor< T > rdft_1d (const SimpleTensor< T > &src)
Performs an one dimensional DFT on a real input.
template<typename T >
SimpleTensor< T > ridft_1d (const SimpleTensor< T > &src, bool is_odd=false)
Performs an one dimensional inverse DFT on a real input.
template<typename T >
SimpleTensor< T > dft_1d (const SimpleTensor< T > &src, FFTDirection direction)
Performs an one dimensional DFT on a complex input.
template<typename T >
SimpleTensor< T > rdft_2d (const SimpleTensor< T > &src)
Performs a two dimensional DFT on a real input.
template<typename T >
SimpleTensor< T > ridft_2d (const SimpleTensor< T > &src, bool is_odd=false)
Performs a two dimensional inverse DFT on a real input.
template<typename T >
SimpleTensor< T > dft_2d (const SimpleTensor< T > &src, FFTDirection direction)
Performs a two dimensional DFT on a complex input.
template<typename T >
SimpleTensor< T > conv2d_dft (const SimpleTensor< T > &src, const SimpleTensor< T > &w, const PadStrideInfo &conv_info)
Performs and DFT based convolution on a real input.
template SimpleTensor< float > rdft_1d (const SimpleTensor< float > &src)
template SimpleTensor< float > ridft_1d (const SimpleTensor< float > &src, bool is_odd)
template SimpleTensor< float > dft_1d (const SimpleTensor< float > &src, FFTDirection direction)
template SimpleTensor< float > rdft_2d (const SimpleTensor< float > &src)
template SimpleTensor< float > ridft_2d (const SimpleTensor< float > &src, bool is_odd)
template SimpleTensor< float > dft_2d (const SimpleTensor< float > &src, FFTDirection direction)
template SimpleTensor< float > conv2d_dft (const SimpleTensor< float > &src, const SimpleTensor< float > &w, const PadStrideInfo &conv_info)
template<typename T >
SimpleTensor< T > dilate (const SimpleTensor< T > &src, BorderMode border_mode, T constant_border_value)
template SimpleTensor< uint8_t > dilate (const SimpleTensor< uint8_t > &src, BorderMode border_mode, uint8_t constant_border_value)
template SimpleTensor< int32_t > arithmetic_operation (ArithmeticOperation op, const SimpleTensor< int32_t > &src1, const SimpleTensor< int32_t > &src2, SimpleTensor< int32_t > &dst, ConvertPolicy convert_policy)
template SimpleTensor< int32_t > arithmetic_operation (ArithmeticOperation op, const SimpleTensor< int32_t > &src1, const SimpleTensor< int32_t > &src2, DataType dst_data_type, ConvertPolicy convert_policy)
template<typename T >
SimpleTensor< T > elementwise_unary (const SimpleTensor< T > &src, ElementWiseUnary op)
template SimpleTensor< float > elementwise_unary (const SimpleTensor< float > &src, ElementWiseUnary op)
template SimpleTensor< half > elementwise_unary (const SimpleTensor< half > &src, ElementWiseUnary op)
template SimpleTensor< int32_t > elementwise_unary (const SimpleTensor< int32_t > &src, ElementWiseUnary op)
template<typename T >
SimpleTensor< T > equalize_histogram (const SimpleTensor< T > &src)
template SimpleTensor< uint8_t > equalize_histogram (const SimpleTensor< uint8_t > &src)
template<typename T >
SimpleTensor< T > erode (const SimpleTensor< T > &src, BorderMode border_mode, T constant_border_value)
template SimpleTensor< uint8_t > erode (const SimpleTensor< uint8_t > &src, BorderMode border_mode, uint8_t constant_border_value)
template<typename T >
std::vector< KeyPoint > fast_corners (const SimpleTensor< T > &src, float input_thresh, bool suppress_nonmax, BorderMode border_mode, T constant_border_value)
template std::vector< KeyPoint > fast_corners (const SimpleTensor< uint8_t > &src, float threshold, bool suppress_nonmax, BorderMode border_mode, uint8_t constant_border_value)
template<typename T >
SimpleTensor< T > flatten_layer (const SimpleTensor< T > &src, const TensorShape &shape_flatten)
template SimpleTensor< float > flatten_layer (const SimpleTensor< float > &src, const TensorShape &shape_flatten)
template SimpleTensor< half > flatten_layer (const SimpleTensor< half > &src, const TensorShape &shape_flatten)
template<typename T >
SimpleTensor< T > floor_layer (const SimpleTensor< T > &src)
template SimpleTensor< half > floor_layer (const SimpleTensor< half > &src)
template SimpleTensor< float > floor_layer (const SimpleTensor< float > &src)
template<typename T , typename TB >
SimpleTensor< T > fully_connected_layer (const SimpleTensor< T > &src, const SimpleTensor< T > &weights, const SimpleTensor< TB > &bias, const TensorShape &dst_shape, QuantizationInfo out_quant_info)
template SimpleTensor< float > fully_connected_layer (const SimpleTensor< float > &src, const SimpleTensor< float > &weights, const SimpleTensor< float > &bias, const TensorShape &dst_shape, QuantizationInfo out_quant_info)
template SimpleTensor< half > fully_connected_layer (const SimpleTensor< half > &src, const SimpleTensor< half > &weights, const SimpleTensor< half > &bias, const TensorShape &dst_shape, QuantizationInfo out_quant_info)
template SimpleTensor< uint8_t > fully_connected_layer (const SimpleTensor< uint8_t > &src, const SimpleTensor< uint8_t > &weights, const SimpleTensor< int32_t > &bias, const TensorShape &dst_shape, QuantizationInfo out_quant_info)
template<typename T >
void fuse_batch_normalization_dwc_layer (const SimpleTensor< T > &w, const SimpleTensor< T > &mean, const SimpleTensor< T > &var, SimpleTensor< T > &w_fused, SimpleTensor< T > &b_fused, const SimpleTensor< T > &b, const SimpleTensor< T > &beta, const SimpleTensor< T > &gamma, float epsilon)
template<typename T >
void fuse_batch_normalization_conv_layer (const SimpleTensor< T > &w, const SimpleTensor< T > &mean, const SimpleTensor< T > &var, SimpleTensor< T > &w_fused, SimpleTensor< T > &b_fused, const SimpleTensor< T > &b, const SimpleTensor< T > &beta, const SimpleTensor< T > &gamma, float epsilon)
template void fuse_batch_normalization_dwc_layer (const SimpleTensor< float > &w, const SimpleTensor< float > &mean, const SimpleTensor< float > &var, SimpleTensor< float > &w_fused, SimpleTensor< float > &b_fused, const SimpleTensor< float > &b, const SimpleTensor< float > &beta, const SimpleTensor< float > &gamma, float epsilon)
template void fuse_batch_normalization_dwc_layer (const SimpleTensor< half > &w, const SimpleTensor< half > &mean, const SimpleTensor< half > &var, SimpleTensor< half > &w_fused, SimpleTensor< half > &b_fused, const SimpleTensor< half > &b, const SimpleTensor< half > &beta, const SimpleTensor< half > &gamma, float epsilon)
template void fuse_batch_normalization_conv_layer (const SimpleTensor< float > &w, const SimpleTensor< float > &mean, const SimpleTensor< float > &var, SimpleTensor< float > &w_fused, SimpleTensor< float > &b_fused, const SimpleTensor< float > &b, const SimpleTensor< float > &beta, const SimpleTensor< float > &gamma, float epsilon)
template void fuse_batch_normalization_conv_layer (const SimpleTensor< half > &w, const SimpleTensor< half > &mean, const SimpleTensor< half > &var, SimpleTensor< half > &w_fused, SimpleTensor< half > &b_fused, const SimpleTensor< half > &b, const SimpleTensor< half > &beta, const SimpleTensor< half > &gamma, float epsilon)
template<typename T >
SimpleTensor< T > gather (const SimpleTensor< T > &src, const SimpleTensor< uint32_t > &indices, uint32_t actual_axis)
template SimpleTensor< float > gather (const SimpleTensor< float > &src, const SimpleTensor< uint32_t > &indices, uint32_t actual_axis)
template SimpleTensor< half > gather (const SimpleTensor< half > &src, const SimpleTensor< uint32_t > &indices, uint32_t actual_axis)
template SimpleTensor< uint16_t > gather (const SimpleTensor< uint16_t > &src, const SimpleTensor< uint32_t > &indices, uint32_t actual_axis)
template SimpleTensor< uint8_t > gather (const SimpleTensor< uint8_t > &src, const SimpleTensor< uint32_t > &indices, uint32_t actual_axis)
template<typename T >
SimpleTensor< T > gaussian3x3 (const SimpleTensor< T > &src, BorderMode border_mode, T constant_border_value)
template SimpleTensor< uint8_t > gaussian3x3 (const SimpleTensor< uint8_t > &src, BorderMode border_mode, uint8_t constant_border_value)
template<typename T >
SimpleTensor< T > gaussian5x5 (const SimpleTensor< T > &src, BorderMode border_mode, T constant_border_value)
template SimpleTensor< uint8_t > gaussian5x5 (const SimpleTensor< uint8_t > &src, BorderMode border_mode, uint8_t constant_border_value)
template<typename T >
std::vector< SimpleTensor< T > > gaussian_pyramid_half (const SimpleTensor< T > &src, BorderMode border_mode, uint8_t constant_border_value, size_t num_levels)
template std::vector< SimpleTensor< uint8_t > > gaussian_pyramid_half (const SimpleTensor< uint8_t > &src, BorderMode border_mode, uint8_t constant_border_value, size_t num_levels)
template<typename T , typename std::enable_if< is_floating_point< T >::value, int >::type >
SimpleTensor< T > gemm (const SimpleTensor< T > &a, const SimpleTensor< T > &b, const SimpleTensor< T > &c, float alpha, float beta)
template SimpleTensor< float > gemm (const SimpleTensor< float > &a, const SimpleTensor< float > &b, const SimpleTensor< float > &c, float alpha, float beta)
template SimpleTensor< half > gemm (const SimpleTensor< half > &a, const SimpleTensor< half > &b, const SimpleTensor< half > &c, float alpha, float beta)
template<typename T >
SimpleTensor< T > gemm_interleave_4x4 (const SimpleTensor< T > &in, SimpleTensor< T > &out)
template<typename T >
T safe_read (const SimpleTensor< T > &t, int y, int x)
template<typename T >
SimpleTensor< T > gemm_interleave_blocked (const SimpleTensor< T > &in, SimpleTensor< T > &out, int int_by, int block, bool transposed)
template SimpleTensor< uint8_t > gemm_interleave_blocked (const SimpleTensor< uint8_t > &in, SimpleTensor< uint8_t > &out, int int_by, int block, bool transposed)
template<typename T_out , typename T_in >
SimpleTensor< T_out > gemmlowp_matrix_multiply_core (const SimpleTensor< T_in > &a, const SimpleTensor< T_in > &b, TensorShape shape_c, int32_t a_offset, int32_t b_offset)
template<typename T1 , typename T2 >
SimpleTensor< T1 > gemmlowp (const SimpleTensor< T2 > &a, const SimpleTensor< T2 > &b, TensorShape shape_c)
template<typename T >
SimpleTensor< uint8_t > gemmlowp_quantize_down_int32_to_uint8_scale (const SimpleTensor< T > &in, int32_t result_offset, int32_t result_mult_int, int32_t result_shift, int32_t min, int32_t max)
template<typename T >
SimpleTensor< uint8_t > gemmlowp_quantize_down_int32_to_uint8_scale (const SimpleTensor< T > &in, const SimpleTensor< T > &bias, int32_t result_offset, int32_t result_mult_int, int32_t result_shift, int32_t min, int32_t max)
template<typename T >
SimpleTensor< uint8_t > gemmlowp_quantize_down_int32_to_uint8_scale_by_fixedpoint (const SimpleTensor< T > &in, int32_t result_fixedpoint_multiplier, int32_t result_shift, int32_t result_offset_after_shift, int32_t min, int32_t max)
template<typename T >
SimpleTensor< uint8_t > gemmlowp_quantize_down_int32_to_uint8_scale_by_fixedpoint (const SimpleTensor< T > &in, const SimpleTensor< T > &bias, int32_t result_fixedpoint_multiplier, int32_t result_shift, int32_t result_offset_after_shift, int32_t min, int32_t max)
template<typename T >
SimpleTensor< int16_t > gemmlowp_quantize_down_int32_to_int16_scale_by_fixedpoint (const SimpleTensor< T > &in, int32_t result_fixedpoint_multiplier, int32_t result_shift, int32_t min, int32_t max)
template<typename T >
SimpleTensor< int16_t > gemmlowp_quantize_down_int32_to_int16_scale_by_fixedpoint (const SimpleTensor< T > &in, const SimpleTensor< T > &bias, int32_t result_fixedpoint_multiplier, int32_t result_shift, int32_t min, int32_t max)
template SimpleTensor< uint8_t > gemmlowp_quantize_down_int32_to_uint8_scale_by_fixedpoint (const SimpleTensor< int32_t > &a, int32_t result_fixedpoint_multiplier, int32_t result_shift, int32_t result_offset_after_shift, int32_t min, int32_t max)
template SimpleTensor< uint8_t > gemmlowp_quantize_down_int32_to_uint8_scale_by_fixedpoint (const SimpleTensor< int32_t > &a, const SimpleTensor< int32_t > &b, int32_t result_fixedpoint_multiplier, int32_t result_shift, int32_t result_offset_after_shift, int32_t min, int32_t max)
template SimpleTensor< int16_t > gemmlowp_quantize_down_int32_to_int16_scale_by_fixedpoint (const SimpleTensor< int32_t > &a, int32_t result_fixedpoint_multiplier, int32_t result_shift, int32_t min, int32_t max)
template SimpleTensor< int16_t > gemmlowp_quantize_down_int32_to_int16_scale_by_fixedpoint (const SimpleTensor< int32_t > &a, const SimpleTensor< int32_t > &b, int32_t result_fixedpoint_multiplier, int32_t result_shift, int32_t min, int32_t max)
template SimpleTensor< uint8_t > gemmlowp_quantize_down_int32_to_uint8_scale (const SimpleTensor< int32_t > &a, int32_t result_offset, int32_t result_mult_int, int32_t result_shift, int32_t min, int32_t max)
template SimpleTensor< uint8_t > gemmlowp_quantize_down_int32_to_uint8_scale (const SimpleTensor< int32_t > &a, const SimpleTensor< int32_t > &b, int32_t result_offset, int32_t result_mult_int, int32_t result_shift, int32_t min, int32_t max)
template SimpleTensor< int32_t > gemmlowp_matrix_multiply_core (const SimpleTensor< int8_t > &a, const SimpleTensor< int8_t > &b, TensorShape shape_c, int32_t a_offset, int32_t b_offset)
template SimpleTensor< int32_t > gemmlowp_matrix_multiply_core (const SimpleTensor< uint8_t > &a, const SimpleTensor< uint8_t > &b, TensorShape shape_c, int32_t a_offset, int32_t b_offset)
template SimpleTensor< int32_t > gemmlowp (const SimpleTensor< int8_t > &a, const SimpleTensor< int8_t > &b, TensorShape shape_c)
template SimpleTensor< int32_t > gemmlowp (const SimpleTensor< uint8_t > &a, const SimpleTensor< uint8_t > &b, TensorShape shape_c)
template<typename T1 , typename T2 >
SimpleTensor< T1 > gemmlowp_matrix_multiply_core (const SimpleTensor< T2 > &a, const SimpleTensor< T2 > &b, TensorShape shape_c, int32_t a_offset, int32_t b_offset)
template<typename T >
SimpleTensor< uint8_t > gemmlowp_quantize_down_int32_to_uint8_scale (const SimpleTensor< T > &in, int32_t result_offset, int32_t result_mult_int, int32_t result_shift)
template<typename T >
SimpleTensor< T > gemm_reshape_lhs_matrix (const SimpleTensor< T > &in, const TensorShape &output_shape, const GEMMLHSMatrixInfo &lhs_info)
template SimpleTensor< int > gemm_reshape_lhs_matrix (const SimpleTensor< int > &in, const TensorShape &output_shape, const GEMMLHSMatrixInfo &lhs_info)
template SimpleTensor< short > gemm_reshape_lhs_matrix (const SimpleTensor< short > &in, const TensorShape &output_shape, const GEMMLHSMatrixInfo &lhs_info)
template SimpleTensor< char > gemm_reshape_lhs_matrix (const SimpleTensor< char > &in, const TensorShape &output_shape, const GEMMLHSMatrixInfo &lhs_info)
template<typename T >
SimpleTensor< T > gemm_reshape_rhs_matrix (const SimpleTensor< T > &in, const TensorShape &output_shape, const GEMMRHSMatrixInfo &rhs_info)
template SimpleTensor< int > gemm_reshape_rhs_matrix (const SimpleTensor< int > &in, const TensorShape &output_shape, const GEMMRHSMatrixInfo &rhs_info)
template SimpleTensor< short > gemm_reshape_rhs_matrix (const SimpleTensor< short > &in, const TensorShape &output_shape, const GEMMRHSMatrixInfo &rhs_info)
template SimpleTensor< char > gemm_reshape_rhs_matrix (const SimpleTensor< char > &in, const TensorShape &output_shape, const GEMMRHSMatrixInfo &rhs_info)
template<typename T >
SimpleTensor< T > gemm_transpose_1xW (const SimpleTensor< T > &in)
template<typename T >
std::vector< KeyPoint > harris_corner_detector (const SimpleTensor< T > &src, float threshold, float min_dist, float sensitivity, int gradient_size, int block_size, BorderMode border_mode, T constant_border_value)
template std::vector< KeyPoint > harris_corner_detector (const SimpleTensor< uint8_t > &src, float threshold, float min_dist, float sensitivity, int gradient_size, int block_size, BorderMode border_mode, uint8_t constant_border_value)
template<typename T >
SimpleTensor< uint32_t > histogram (const SimpleTensor< T > &src, size_t num_bins, int32_t offset, uint32_t range)
template SimpleTensor< uint32_t > histogram (const SimpleTensor< uint8_t > &src, size_t num_bins, int32_t offset, uint32_t range)
template<typename T , typename U , typename V >
void hog_orientation_binning (const SimpleTensor< T > &mag, const SimpleTensor< U > &phase, SimpleTensor< V > &hog_space, const HOGInfo &hog_info)
template<typename T >
void hog_block_normalization (SimpleTensor< T > &desc, const SimpleTensor< T > &hog_space, const HOGInfo &hog_info)
template<typename T , typename U >
SimpleTensor< T > hog_descriptor (const SimpleTensor< U > &src, BorderMode border_mode, U constant_border_value, const HOGInfo &hog_info)
template void hog_orientation_binning (const SimpleTensor< int16_t > &mag, const SimpleTensor< uint8_t > &phase, SimpleTensor< float > &hog_space, const HOGInfo &hog_info)
template void hog_block_normalization (SimpleTensor< float > &desc, const SimpleTensor< float > &hog_space, const HOGInfo &hog_info)
template SimpleTensor< float > hog_descriptor (const SimpleTensor< uint8_t > &src, BorderMode border_mode, uint8_t constant_border_value, const HOGInfo &hog_info)
template<typename T >
std::vector< DetectionWindow > hog_detector (const SimpleTensor< T > &src, const std::vector< T > &descriptor, unsigned int max_num_detection_windows, const HOGInfo &hog_info, const Size2D &detection_window_stride, float threshold, uint16_t idx_class)
template std::vector< DetectionWindow > hog_detector (const SimpleTensor< float > &src, const std::vector< float > &descriptor, unsigned int max_num_detection_windows, const HOGInfo &hog_info, const Size2D &detection_window_stride, float threshold, uint16_t idx_class)
void detection_windows_non_maxima_suppression (std::vector< DetectionWindow > &multi_windows, float min_distance)
template<typename T >
std::vector< DetectionWindow > hog_multi_detection (const SimpleTensor< T > &src, BorderMode border_mode, T constant_border_value, const std::vector< HOGInfo > &models, std::vector< std::vector< float >> descriptors, unsigned int max_num_detection_windows, float threshold, bool non_maxima_suppression, float min_distance)
template std::vector< DetectionWindow > hog_multi_detection (const SimpleTensor< uint8_t > &src, BorderMode border_mode, uint8_t constant_border_value, const std::vector< HOGInfo > &models, std::vector< std::vector< float >> descriptors, unsigned int max_num_detection_windows, float threshold, bool non_maxima_suppression, float min_distance)
template<typename T >
void im2col_nchw (const SimpleTensor< T > &src, SimpleTensor< T > &dst, const Size2D &kernel_dims, const PadStrideInfo &conv_info, bool has_bias, unsigned int num_groups)
template<typename T >
void im2col_nhwc (const SimpleTensor< T > &src, SimpleTensor< T > &dst, const Size2D &kernel_dims, const PadStrideInfo &conv_info, bool has_bias)
template<typename T >
void im2col (const SimpleTensor< T > &src, SimpleTensor< T > &dst, const Size2D &kernel_dims, const PadStrideInfo &conv_info, bool has_bias, unsigned int num_groups)
template void im2col (const SimpleTensor< uint8_t > &src, SimpleTensor< uint8_t > &dst, const Size2D &kernel_dims, const PadStrideInfo &conv_info, bool has_bias, unsigned int num_groups)
template void im2col (const SimpleTensor< half > &src, SimpleTensor< half > &dst, const Size2D &kernel_dims, const PadStrideInfo &conv_info, bool has_bias, unsigned int num_groups)
template void im2col (const SimpleTensor< float > &src, SimpleTensor< float > &dst, const Size2D &kernel_dims, const PadStrideInfo &conv_info, bool has_bias, unsigned int num_groups)
template<typename T >
SimpleTensor< uint32_t > integral_image (const SimpleTensor< T > &src)
template SimpleTensor< uint32_t > integral_image (const SimpleTensor< uint8_t > &src)
template<typename T >
SimpleTensor< T > l2_normalize (const SimpleTensor< T > &src, unsigned int axis, float epsilon)
template SimpleTensor< float > l2_normalize (const SimpleTensor< float > &src, unsigned int axis, float epsilon)
template SimpleTensor< half > l2_normalize (const SimpleTensor< half > &src, unsigned int axis, float epsilon)
template<typename T , typename U >
std::vector< SimpleTensor< U > > laplacian_pyramid (const SimpleTensor< T > &src, SimpleTensor< U > &dst, size_t num_levels, BorderMode border_mode, uint8_t constant_border_value)
template std::vector< SimpleTensor< int16_t > > laplacian_pyramid (const SimpleTensor< uint8_t > &src, SimpleTensor< int16_t > &dst, size_t num_levels, BorderMode border_mode, uint8_t constant_border_value)
template<typename T , typename U >
SimpleTensor< U > laplacian_reconstruct (const std::vector< SimpleTensor< T >> &pyramid, const SimpleTensor< T > &low_res, BorderMode border_mode, T constant_border_value)
template SimpleTensor< uint8_t > laplacian_reconstruct (const std::vector< SimpleTensor< int16_t >> &pyramid, const SimpleTensor< int16_t > &low_res, BorderMode border_mode, int16_t constant_border_value)
template<typename T , typename TB >
SimpleTensor< T > locally_connected (const SimpleTensor< T > &src, const SimpleTensor< T > &weights, const SimpleTensor< TB > &bias, const TensorShape &output_shape, const PadStrideInfo &info)
template SimpleTensor< float > locally_connected (const SimpleTensor< float > &src, const SimpleTensor< float > &weights, const SimpleTensor< float > &bias, const TensorShape &output_shape, const PadStrideInfo &info)
template<typename T >
SimpleTensor< T > magnitude (const SimpleTensor< T > &gx, const SimpleTensor< T > &gy, MagnitudeType magnitude_type)
template SimpleTensor< int16_t > magnitude (const SimpleTensor< int16_t > &gx, const SimpleTensor< int16_t > &gy, MagnitudeType magnitude_type)
template SimpleTensor< int32_t > magnitude (const SimpleTensor< int32_t > &gx, const SimpleTensor< int32_t > &gy, MagnitudeType magnitude_type)
template SimpleTensor< half_float::half > magnitude (const SimpleTensor< half_float::half > &gx, const SimpleTensor< half_float::half > &gy, MagnitudeType magnitude_type)
template<typename T >
std::pair< float, float > mean_and_standard_deviation (const SimpleTensor< T > &in)
template std::pair< float, float > mean_and_standard_deviation (const SimpleTensor< uint8_t > &in)
template std::pair< float, float > mean_and_standard_deviation (const SimpleTensor< half > &in)
template std::pair< float, float > mean_and_standard_deviation (const SimpleTensor< float > &in)
template<typename T >
SimpleTensor< T > mean_std_normalization_layer (const SimpleTensor< T > &src, float epsilon)
template SimpleTensor< float > mean_std_normalization_layer (const SimpleTensor< float > &src, float epsilon)
template SimpleTensor< half > mean_std_normalization_layer (const SimpleTensor< half > &src, float epsilon)
template<typename T >
SimpleTensor< T > median3x3 (const SimpleTensor< T > &src, BorderMode border_mode, T constant_border_value)
template SimpleTensor< uint8_t > median3x3 (const SimpleTensor< uint8_t > &src, BorderMode border_mode, uint8_t constant_border_value)
template<typename T >
void compute_min_max (const SimpleTensor< T > &src, T &min, T &max)
template<typename T >
MinMaxLocationValues< T > min_max_location (const SimpleTensor< T > &src)
template MinMaxLocationValues< uint8_t > min_max_location (const SimpleTensor< uint8_t > &src)
template MinMaxLocationValues< int16_t > min_max_location (const SimpleTensor< int16_t > &src)
template MinMaxLocationValues< float > min_max_location (const SimpleTensor< float > &src)
template<typename T >
SimpleTensor< T > non_linear_filter (const SimpleTensor< T > &src, NonLinearFilterFunction function, unsigned int mask_size, MatrixPattern pattern, const uint8_t *mask, BorderMode border_mode, uint8_t constant_border_value)
template SimpleTensor< uint8_t > non_linear_filter (const SimpleTensor< uint8_t > &src, NonLinearFilterFunction function, unsigned int mask_size, MatrixPattern pattern, const uint8_t *mask, BorderMode border_mode, uint8_t constant_border_value)
template<typename T >
SimpleTensor< T > non_maxima_suppression (const SimpleTensor< T > &src, BorderMode border_mode, T constant_border_value)
template SimpleTensor< float > non_maxima_suppression (const SimpleTensor< float > &src, BorderMode border_mode, float constant_border_value)
template SimpleTensor< uint8_t > non_maxima_suppression (const SimpleTensor< uint8_t > &src, BorderMode border_mode, uint8_t constant_border_value)
SimpleTensor< int > non_max_suppression (const SimpleTensor< float > &bboxes, const SimpleTensor< float > &scores, SimpleTensor< int > &indices, unsigned int max_output_size, float score_threshold, float nms_threshold)
template<typename T >
SimpleTensor< T > normalization_layer (const SimpleTensor< T > &src, NormalizationLayerInfo info)
template SimpleTensor< float > normalization_layer (const SimpleTensor< float > &src, NormalizationLayerInfo info)
template SimpleTensor< half > normalization_layer (const SimpleTensor< half > &src, NormalizationLayerInfo info)
template<typename T >
SimpleTensor< T > normalize_planar_yuv_layer (const SimpleTensor< T > &src, const SimpleTensor< T > &mean, const SimpleTensor< T > &std)
template<>
SimpleTensor< uint8_t > normalize_planar_yuv_layer< uint8_t > (const SimpleTensor< uint8_t > &src, const SimpleTensor< uint8_t > &mean, const SimpleTensor< uint8_t > &std)
template SimpleTensor< half > normalize_planar_yuv_layer (const SimpleTensor< half > &src, const SimpleTensor< half > &mean, const SimpleTensor< half > &std)
template SimpleTensor< float > normalize_planar_yuv_layer (const SimpleTensor< float > &src, const SimpleTensor< float > &mean, const SimpleTensor< float > &std)
template<typename T >
std::vector< KeyPoint > optical_flow (const SimpleTensor< T > &old_input, const SimpleTensor< T > &new_input, const OpticalFlowParameters &params, size_t num_levels, const std::vector< KeyPoint > &old_points, const std::vector< KeyPoint > &new_points_estimates, BorderMode border_mode, uint8_t constant_border_value)
template std::vector< KeyPoint > optical_flow (const SimpleTensor< uint8_t > &old_input, const SimpleTensor< uint8_t > &new_input, const OpticalFlowParameters &params, size_t num_levels, const std::vector< KeyPoint > &old_points, const std::vector< KeyPoint > &new_points_estimates, BorderMode border_mode, uint8_t constant_border_value)
template<typename T >
SimpleTensor< T > pad_layer (const SimpleTensor< T > &src, const PaddingList &paddings, const PixelValue const_value=PixelValue(), const PaddingMode mode=PaddingMode::CONSTANT)
Reference function to pad an ND tensor.
template SimpleTensor< float > pad_layer (const SimpleTensor< float > &src, const PaddingList &paddings, const PixelValue const_value=PixelValue(), const PaddingMode mode)
template SimpleTensor< half > pad_layer (const SimpleTensor< half > &src, const PaddingList &paddings, const PixelValue const_value=PixelValue(), const PaddingMode mode)
template SimpleTensor< uint32_t > pad_layer (const SimpleTensor< uint32_t > &src, const PaddingList &paddings, const PixelValue const_value=PixelValue(), const PaddingMode mode)
template SimpleTensor< uint8_t > pad_layer (const SimpleTensor< uint8_t > &src, const PaddingList &paddings, const PixelValue const_value=PixelValue(), const PaddingMode mode)
template SimpleTensor< int8_t > pad_layer (const SimpleTensor< int8_t > &src, const PaddingList &paddings, const PixelValue const_value=PixelValue(), const PaddingMode mode)
template SimpleTensor< uint16_t > pad_layer (const SimpleTensor< uint16_t > &src, const PaddingList &paddings, const PixelValue const_value=PixelValue(), const PaddingMode mode)
template SimpleTensor< int16_t > pad_layer (const SimpleTensor< int16_t > &src, const PaddingList &paddings, const PixelValue const_value=PixelValue(), const PaddingMode mode)
template<typename T >
SimpleTensor< T > permute (const SimpleTensor< T > &src, PermutationVector perm)
template SimpleTensor< int8_t > permute (const SimpleTensor< int8_t > &src, PermutationVector perm)
template SimpleTensor< uint8_t > permute (const SimpleTensor< uint8_t > &src, PermutationVector perm)
template SimpleTensor< int16_t > permute (const SimpleTensor< int16_t > &src, PermutationVector perm)
template SimpleTensor< uint16_t > permute (const SimpleTensor< uint16_t > &src, PermutationVector perm)
template SimpleTensor< uint32_t > permute (const SimpleTensor< uint32_t > &src, PermutationVector perm)
template SimpleTensor< float > permute (const SimpleTensor< float > &src, PermutationVector perm)
template SimpleTensor< half > permute (const SimpleTensor< half > &src, PermutationVector perm)
template<typename T >
SimpleTensor< uint8_t > phase (const SimpleTensor< T > &gx, const SimpleTensor< T > &gy, PhaseType phase_type)
template SimpleTensor< uint8_t > phase (const SimpleTensor< int16_t > &gx, const SimpleTensor< int16_t > &gy, PhaseType phase_type)
template SimpleTensor< uint8_t > phase (const SimpleTensor< int32_t > &gx, const SimpleTensor< int32_t > &gy, PhaseType phase_type)
template<typename T1 , typename T2 >
SimpleTensor< T2 > pixel_wise_multiplication (const SimpleTensor< T1 > &src1, const SimpleTensor< T2 > &src2, float scale, ConvertPolicy convert_policy, RoundingPolicy rounding_policy, const QuantizationInfo &qout)
template<>
SimpleTensor< uint8_t > pixel_wise_multiplication (const SimpleTensor< uint8_t > &src1, const SimpleTensor< uint8_t > &src2, float scale, ConvertPolicy convert_policy, RoundingPolicy rounding_policy, const QuantizationInfo &qout)
template<>
SimpleTensor< int16_t > pixel_wise_multiplication (const SimpleTensor< int16_t > &src1, const SimpleTensor< int16_t > &src2, float scale, ConvertPolicy convert_policy, RoundingPolicy rounding_policy, const QuantizationInfo &qout)
template SimpleTensor< int16_t > pixel_wise_multiplication (const SimpleTensor< uint8_t > &src1, const SimpleTensor< int16_t > &src2, float scale, ConvertPolicy convert_policy, RoundingPolicy rounding_policy, const QuantizationInfo &qout)
template SimpleTensor< float > pixel_wise_multiplication (const SimpleTensor< float > &src1, const SimpleTensor< float > &src2, float scale, ConvertPolicy convert_policy, RoundingPolicy rounding_policy, const QuantizationInfo &qout)
template SimpleTensor< half_float::half > pixel_wise_multiplication (const SimpleTensor< half_float::half > &src1, const SimpleTensor< half_float::half > &src2, float scale, ConvertPolicy convert_policy, RoundingPolicy rounding_policy, const QuantizationInfo &qout)
template<typename T >
SimpleTensor< T > pooling_layer (const SimpleTensor< T > &src, const PoolingLayerInfo &info, const QuantizationInfo &output_qinfo)
template<>
SimpleTensor< uint8_t > pooling_layer< uint8_t > (const SimpleTensor< uint8_t > &src, const PoolingLayerInfo &info, const QuantizationInfo &output_qinfo)
template SimpleTensor< float > pooling_layer (const SimpleTensor< float > &src, const PoolingLayerInfo &info, const QuantizationInfo &output_qinfo)
template SimpleTensor< half > pooling_layer (const SimpleTensor< half > &src, const PoolingLayerInfo &info, const QuantizationInfo &output_qinfo)
template<typename T >
SimpleTensor< T > prior_box_layer (const SimpleTensor< T > &src1, const SimpleTensor< T > &src2, const PriorBoxLayerInfo &info, const TensorShape &output_shape)
template SimpleTensor< float > prior_box_layer (const SimpleTensor< float > &src1, const SimpleTensor< float > &src2, const PriorBoxLayerInfo &info, const TensorShape &output_shape)
template<typename T >
SimpleTensor< uint8_t > quantization_layer (const SimpleTensor< T > &src, const QuantizationInfo &quantization_info)
template SimpleTensor< uint8_t > quantization_layer (const SimpleTensor< half > &src, const QuantizationInfo &quantization_info)
template SimpleTensor< uint8_t > quantization_layer (const SimpleTensor< float > &src, const QuantizationInfo &quantization_info)
template<typename T >
SimpleTensor< T > range (SimpleTensor< T > &dst, float start, const size_t num_of_elements, float step)
template<>
SimpleTensor< uint8_t > range (SimpleTensor< uint8_t > &dst, float start, const size_t num_of_elements, float step)
template SimpleTensor< float > range (SimpleTensor< float > &dst, float start, const size_t num_of_elements, float step)
template SimpleTensor< half > range (SimpleTensor< half > &dst, float start, const size_t num_of_elements, float step)
template SimpleTensor< int8_t > range (SimpleTensor< int8_t > &dst, float start, const size_t num_of_elements, float step)
template SimpleTensor< uint16_t > range (SimpleTensor< uint16_t > &dst, float start, const size_t num_of_elements, float step)
template SimpleTensor< int16_t > range (SimpleTensor< int16_t > &dst, float start, const size_t num_of_elements, float step)
template<typename T , typename OT >
SimpleTensor< OT > compute_reduction_operation (const SimpleTensor< T > &src, const TensorShape &dst_shape, unsigned int axis, ReductionOperation op)
template<typename T , typename OT >
SimpleTensor< OT > reduction_operation (const SimpleTensor< T > &src, const TensorShape &dst_shape, unsigned int axis, ReductionOperation op)
template<>
SimpleTensor< uint8_t > reduction_operation (const SimpleTensor< uint8_t > &src, const TensorShape &dst_shape, unsigned int axis, ReductionOperation op)
template SimpleTensor< float > reduction_operation (const SimpleTensor< float > &src, const TensorShape &dst_shape, unsigned int axis, ReductionOperation op)
template SimpleTensor< half > reduction_operation (const SimpleTensor< half > &src, const TensorShape &dst_shape, unsigned int axis, ReductionOperation op)
template SimpleTensor< uint32_t > reduction_operation (const SimpleTensor< int32_t > &src, const TensorShape &dst_shape, unsigned int axis, ReductionOperation op)
template<typename T >
SimpleTensor< T > remap (const SimpleTensor< T > &in, SimpleTensor< float > &map_x, SimpleTensor< float > &map_y, SimpleTensor< T > &valid_mask, InterpolationPolicy policy, BorderMode border_mode, T constant_border_value)
template SimpleTensor< uint8_t > remap (const SimpleTensor< uint8_t > &src, SimpleTensor< float > &map_x, SimpleTensor< float > &map_y, SimpleTensor< uint8_t > &valid_mask, InterpolationPolicy policy, BorderMode border_mode, uint8_t constant_border_value)
template<typename T >
SimpleTensor< T > reorg_layer (const SimpleTensor< T > &src, int32_t stride)
template SimpleTensor< int32_t > reorg_layer (const SimpleTensor< int32_t > &src, int32_t stride)
template SimpleTensor< int16_t > reorg_layer (const SimpleTensor< int16_t > &src, int32_t stride)
template SimpleTensor< int8_t > reorg_layer (const SimpleTensor< int8_t > &src, int32_t stride)
template<typename T >
SimpleTensor< T > reshape_layer (const SimpleTensor< T > &src, const TensorShape &output_shape)
[ReshapeLayer]
template SimpleTensor< uint8_t > reshape_layer (const SimpleTensor< uint8_t > &src, const TensorShape &output_shape)
template SimpleTensor< int8_t > reshape_layer (const SimpleTensor< int8_t > &src, const TensorShape &output_shape)
template SimpleTensor< uint16_t > reshape_layer (const SimpleTensor< uint16_t > &src, const TensorShape &output_shape)
template SimpleTensor< int16_t > reshape_layer (const SimpleTensor< int16_t > &src, const TensorShape &output_shape)
template SimpleTensor< uint32_t > reshape_layer (const SimpleTensor< uint32_t > &src, const TensorShape &output_shape)
template SimpleTensor< int32_t > reshape_layer (const SimpleTensor< int32_t > &src, const TensorShape &output_shape)
template SimpleTensor< half > reshape_layer (const SimpleTensor< half > &src, const TensorShape &output_shape)
template SimpleTensor< float > reshape_layer (const SimpleTensor< float > &src, const TensorShape &output_shape)
template<typename T >
SimpleTensor< T > reverse (const SimpleTensor< T > &src, const SimpleTensor< uint32_t > &axis)
template SimpleTensor< uint8_t > reverse (const SimpleTensor< uint8_t > &src, const SimpleTensor< uint32_t > &axis)
template SimpleTensor< half > reverse (const SimpleTensor< half > &src, const SimpleTensor< uint32_t > &axis)
template SimpleTensor< float > reverse (const SimpleTensor< float > &src, const SimpleTensor< uint32_t > &axis)
template<typename T >
SimpleTensor< T > roi_align_layer (const SimpleTensor< T > &src, const SimpleTensor< T > &rois, const ROIPoolingLayerInfo &pool_info)
template SimpleTensor< float > roi_align_layer (const SimpleTensor< float > &src, const SimpleTensor< float > &rois, const ROIPoolingLayerInfo &pool_info)
template SimpleTensor< half > roi_align_layer (const SimpleTensor< half > &src, const SimpleTensor< half > &rois, const ROIPoolingLayerInfo &pool_info)
template<typename T >
SimpleTensor< T > scale_core (const SimpleTensor< T > &in, float scale_x, float scale_y, InterpolationPolicy policy, BorderMode border_mode, T constant_border_value, SamplingPolicy sampling_policy, bool ceil_policy_scale)
template<typename T >
SimpleTensor< T > scale (const SimpleTensor< T > &src, float scale_x, float scale_y, InterpolationPolicy policy, BorderMode border_mode, T constant_border_value, SamplingPolicy sampling_policy, bool ceil_policy_scale)
template<>
SimpleTensor< uint8_t > scale (const SimpleTensor< uint8_t > &src, float scale_x, float scale_y, InterpolationPolicy policy, BorderMode border_mode, uint8_t constant_border_value, SamplingPolicy sampling_policy, bool ceil_policy_scale)
template SimpleTensor< int16_t > scale (const SimpleTensor< int16_t > &src, float scale_x, float scale_y, InterpolationPolicy policy, BorderMode border_mode, int16_t constant_border_value, SamplingPolicy sampling_policy, bool ceil_policy_scale)
template SimpleTensor< half > scale (const SimpleTensor< half > &src, float scale_x, float scale_y, InterpolationPolicy policy, BorderMode border_mode, half constant_border_value, SamplingPolicy sampling_policy, bool ceil_policy_scale)
template SimpleTensor< float > scale (const SimpleTensor< float > &src, float scale_x, float scale_y, InterpolationPolicy policy, BorderMode border_mode, float constant_border_value, SamplingPolicy sampling_policy, bool ceil_policy_scale)
template<typename T , typename U >
std::pair< SimpleTensor< T >, SimpleTensor< T > > scharr (const SimpleTensor< U > &src, int filter_size, BorderMode border_mode, uint8_t constant_border_value, GradientDimension gradient_dimension)
template std::pair< SimpleTensor< int16_t >, SimpleTensor< int16_t > > scharr (const SimpleTensor< uint8_t > &src, int filter_size, BorderMode border_mode, uint8_t constant_border_value, GradientDimension gradient_dimension)
template<typename T >
SimpleTensor< T > select (const SimpleTensor< uint8_t > &c, const SimpleTensor< T > &x, const SimpleTensor< T > &y)
template SimpleTensor< uint8_t > select (const SimpleTensor< uint8_t > &c, const SimpleTensor< uint8_t > &x, const SimpleTensor< uint8_t > &y)
template SimpleTensor< half > select (const SimpleTensor< uint8_t > &c, const SimpleTensor< half > &x, const SimpleTensor< half > &y)
template SimpleTensor< float > select (const SimpleTensor< uint8_t > &c, const SimpleTensor< float > &x, const SimpleTensor< float > &y)
template<typename T >
SimpleTensor< T > slice (const SimpleTensor< T > &src, Coordinates starts, Coordinates ends)
template SimpleTensor< float > slice (const SimpleTensor< float > &src, Coordinates starts, Coordinates ends)
template SimpleTensor< half_float::half > slice (const SimpleTensor< half_float::half > &src, Coordinates starts, Coordinates ends)
template<typename T >
SimpleTensor< T > strided_slice (const SimpleTensor< T > &src, Coordinates starts, Coordinates ends, BiStrides strides, int32_t begin_mask, int32_t end_mask, int32_t shrink_axis_mask)
template SimpleTensor< float > strided_slice (const SimpleTensor< float > &src, Coordinates starts, Coordinates ends, BiStrides strides, int32_t begin_mask, int32_t end_mask, int32_t shrink_axis_mask)
template SimpleTensor< half_float::half > strided_slice (const SimpleTensor< half_float::half > &src, Coordinates starts, Coordinates ends, BiStrides strides, int32_t begin_mask, int32_t end_mask, int32_t shrink_axis_mask)
template<typename T , typename U >
std::pair< SimpleTensor< T >, SimpleTensor< T > > sobel (const SimpleTensor< U > &src, int filter_size, BorderMode border_mode, uint8_t constant_border_value, GradientDimension gradient_dimension)
template std::pair< SimpleTensor< int16_t >, SimpleTensor< int16_t > > sobel (const SimpleTensor< uint8_t > &src, int filter_size, BorderMode border_mode, uint8_t constant_border_value, GradientDimension gradient_dimension)
template<typename T , typename std::enable_if< is_floating_point< T >::value, int >::type >
SimpleTensor< T > softmax_layer (const SimpleTensor< T > &src, float beta, size_t axis)
template SimpleTensor< float > softmax_layer (const SimpleTensor< float > &src, float beta, size_t axis)
template SimpleTensor< half > softmax_layer (const SimpleTensor< half > &src, float beta, size_t axis)
template SimpleTensor< uint8_t > softmax_layer (const SimpleTensor< uint8_t > &src, float beta, size_t axis)
template<typename T >
SimpleTensor< T > space_to_batch (const SimpleTensor< T > &src, const SimpleTensor< int32_t > &block_shape, const SimpleTensor< int32_t > &paddings, const TensorShape &dst_shape)
template SimpleTensor< float > space_to_batch (const SimpleTensor< float > &src, const SimpleTensor< int32_t > &block_shape, const SimpleTensor< int32_t > &paddings, const TensorShape &dst_shape)
template SimpleTensor< half > space_to_batch (const SimpleTensor< half > &src, const SimpleTensor< int32_t > &block_shape, const SimpleTensor< int32_t > &paddings, const TensorShape &dst_shape)
template SimpleTensor< uint8_t > space_to_batch (const SimpleTensor< uint8_t > &src, const SimpleTensor< int32_t > &block_shape, const SimpleTensor< int32_t > &paddings, const TensorShape &dst_shape)
template<typename T >
SimpleTensor< T > space_to_depth (const SimpleTensor< T > &src, const TensorShape &dst_shape, const int block_shape)
template SimpleTensor< float > space_to_depth (const SimpleTensor< float > &src, const TensorShape &dst_shape, const int block_shape)
template SimpleTensor< half > space_to_depth (const SimpleTensor< half > &src, const TensorShape &dst_shape, const int block_shape)
template<typename T >
SimpleTensor< T > stack_layer (const std::vector< SimpleTensor< T >> &in, const TensorShape &output_shape, DataType data_type, unsigned int axis)
template SimpleTensor< int > stack_layer (const std::vector< SimpleTensor< int >> &in, const TensorShape &output_shape, DataType data_type, unsigned int axis)
template SimpleTensor< short > stack_layer (const std::vector< SimpleTensor< short >> &in, const TensorShape &output_shape, DataType data_type, unsigned int axis)
template SimpleTensor< char > stack_layer (const std::vector< SimpleTensor< char >> &in, const TensorShape &output_shape, DataType data_type, unsigned int axis)
template<typename T >
SimpleTensor< T > table_lookup (const SimpleTensor< T > &src, const std::map< T, T > &rawlut)
template SimpleTensor< uint8_t > table_lookup (const SimpleTensor< uint8_t > &src, const std::map< uint8_t, uint8_t > &rawlut)
template SimpleTensor< int16_t > table_lookup (const SimpleTensor< int16_t > &src, const std::map< int16_t, int16_t > &rawlut)
template<typename T >
SimpleTensor< T > threshold (const SimpleTensor< T > &src, T threshold, T false_value, T true_value, ThresholdType type, T upper)
template SimpleTensor< uint8_t > threshold (const SimpleTensor< uint8_t > &src, uint8_t threshold, uint8_t false_value, uint8_t true_value, ThresholdType type, uint8_t upper)
template<typename T >
SimpleTensor< T > tile (const SimpleTensor< T > &src, const Multiples &multiples)
template SimpleTensor< uint8_t > tile (const SimpleTensor< uint8_t > &src, const Multiples &multiples)
template SimpleTensor< int8_t > tile (const SimpleTensor< int8_t > &src, const Multiples &multiples)
template SimpleTensor< uint16_t > tile (const SimpleTensor< uint16_t > &src, const Multiples &multiples)
template SimpleTensor< int16_t > tile (const SimpleTensor< int16_t > &src, const Multiples &multiples)
template SimpleTensor< uint32_t > tile (const SimpleTensor< uint32_t > &src, const Multiples &multiples)
template SimpleTensor< int32_t > tile (const SimpleTensor< int32_t > &src, const Multiples &multiples)
template SimpleTensor< half > tile (const SimpleTensor< half > &src, const Multiples &multiples)
template SimpleTensor< float > tile (const SimpleTensor< float > &src, const Multiples &multiples)
template<typename T >
SimpleTensor< T > transpose (const SimpleTensor< T > &src)
template SimpleTensor< uint8_t > transpose (const SimpleTensor< uint8_t > &src)
template SimpleTensor< uint16_t > transpose (const SimpleTensor< uint16_t > &src)
template SimpleTensor< uint32_t > transpose (const SimpleTensor< uint32_t > &src)
template SimpleTensor< half > transpose (const SimpleTensor< half > &src)
template SimpleTensor< float > transpose (const SimpleTensor< float > &src)
template<typename T >
std::vector< SimpleTensor< T > > unstack (const SimpleTensor< T > &input_tensor, std::vector< SimpleTensor< T >> &output_tensors, int axis)
template std::vector< SimpleTensor< float > > unstack (const SimpleTensor< float > &input_tensor, std::vector< SimpleTensor< float >> &output_tensors, int axis)
template std::vector< SimpleTensor< half > > unstack (const SimpleTensor< half > &input_tensor, std::vector< SimpleTensor< half >> &output_tensors, int axis)
template std::vector< SimpleTensor< uint8_t > > unstack (const SimpleTensor< uint8_t > &input_tensor, std::vector< SimpleTensor< uint8_t >> &output_tensors, int axis)
template<typename T >
SimpleTensor< T > upsample_layer (const SimpleTensor< T > &src, const Size2D &info, const InterpolationPolicy policy)
template<>
SimpleTensor< uint8_t > upsample_layer (const SimpleTensor< uint8_t > &src, const Size2D &info, const InterpolationPolicy policy)
template SimpleTensor< float > upsample_layer (const SimpleTensor< float > &src, const Size2D &info, const InterpolationPolicy policy)
template SimpleTensor< half > upsample_layer (const SimpleTensor< half > &src, const Size2D &info, const InterpolationPolicy policy)
bool valid_bilinear_policy (float xn, float yn, int width, int height, BorderMode border_mode)
template<typename T >
SimpleTensor< T > warp_affine (const SimpleTensor< T > &src, SimpleTensor< T > &valid_mask, const float *matrix, InterpolationPolicy policy, BorderMode border_mode, uint8_t constant_border_value)
template SimpleTensor< uint8_t > warp_affine (const SimpleTensor< uint8_t > &src, SimpleTensor< uint8_t > &valid_mask, const float *matrix, InterpolationPolicy policy, BorderMode border_mode, uint8_t constant_border_value)
template<typename T >
SimpleTensor< T > warp_perspective (const SimpleTensor< T > &src, SimpleTensor< T > &valid_mask, const float *matrix, InterpolationPolicy policy, BorderMode border_mode, uint8_t constant_border_value)
template SimpleTensor< uint8_t > warp_perspective (const SimpleTensor< uint8_t > &src, SimpleTensor< uint8_t > &valid_mask, const float *matrix, InterpolationPolicy policy, BorderMode border_mode, uint8_t constant_border_value)
template<typename T >
SimpleTensor< T > weights_reshape (const SimpleTensor< T > &src, const SimpleTensor< T > &biases, const TensorShape &dst_shape, const unsigned int num_groups)
template SimpleTensor< float > weights_reshape (const SimpleTensor< float > &src, const SimpleTensor< float > &biases, const TensorShape &dst_shape, const unsigned int num_groups)
template SimpleTensor< half > weights_reshape (const SimpleTensor< half > &src, const SimpleTensor< half > &biases, const TensorShape &dst_shape, const unsigned int num_groups)
template SimpleTensor< uint8_t > weights_reshape (const SimpleTensor< uint8_t > &src, const SimpleTensor< uint8_t > &biases, const TensorShape &dst_shape, const unsigned int num_groups)
template<typename T >
SimpleTensor< T > winograd_input_transform (const SimpleTensor< T > &in, const TensorShape &output_shape, const WinogradInfo &winograd_info)
template<typename T >
SimpleTensor< T > winograd_filter_transform (const SimpleTensor< T > &in, const TensorShape &output_shape, const WinogradInfo &winograd_info)
template<typename T >
SimpleTensor< T > winograd_output_transform (const SimpleTensor< T > &in, const SimpleTensor< T > &b, const TensorShape &output_shape, const WinogradInfo &winograd_info)
template SimpleTensor< float > winograd_filter_transform (const SimpleTensor< float > &in, const TensorShape &output_shape, const WinogradInfo &winograd_info)
template SimpleTensor< float > winograd_input_transform (const SimpleTensor< float > &in, const TensorShape &output_shape, const WinogradInfo &winograd_info)
template SimpleTensor< float > winograd_output_transform (const SimpleTensor< float > &in, const SimpleTensor< float > &b, const TensorShape &output_shape, const WinogradInfo &winograd_info)
template SimpleTensor< half > winograd_filter_transform (const SimpleTensor< half > &in, const TensorShape &output_shape, const WinogradInfo &winograd_info)
template SimpleTensor< half > winograd_input_transform (const SimpleTensor< half > &in, const TensorShape &output_shape, const WinogradInfo &winograd_info)
template SimpleTensor< half > winograd_output_transform (const SimpleTensor< half > &in, const SimpleTensor< half > &b, const TensorShape &output_shape, const WinogradInfo &winograd_info)
template<typename T , typename std::enable_if< is_floating_point< T >::value, int >::type >
SimpleTensor< T > yolo_layer (const SimpleTensor< T > &src, const ActivationLayerInfo &info, int32_t num_classes)
template<>
SimpleTensor< uint8_t > yolo_layer< uint8_t > (const SimpleTensor< uint8_t > &src, const ActivationLayerInfo &info, int32_t num_classes)
template SimpleTensor< float > yolo_layer (const SimpleTensor< float > &src, const ActivationLayerInfo &info, int32_t num_classes)
template SimpleTensor< half > yolo_layer (const SimpleTensor< half > &src, const ActivationLayerInfo &info, int32_t num_classes)
Enumeration Type Documentation
ArithmeticOperation
enum ArithmeticOperation strong
Arithmetic operation types.
Enumerator
ADD
SUB
Definition at line 39 of file ArithmeticOperations.h.
 {
     ADD,
     SUB
 };
FFTDirection
enum FFTDirection strong
Enumerator
Forward
Inverse
Definition at line 38 of file DFT.h.
 {
     Forward,
     Inverse
 };
WinogradTransformType
enum WinogradTransformType strong
Winograd transform type.
Enumerator
INPUT
Winograd input transform.
FILTER
Winograd filter transform.
OUTPUT
Winograd output transform.
Definition at line 40 of file Winograd.h.
 {
     INPUT,
     FILTER,
     OUTPUT
 };
Function Documentation
absolute_difference() [1/4]
SimpleTensor< T > absolute_difference (const SimpleTensor< T > & src1, const SimpleTensor< T > & src2, DataType dst_data_type)
Definition at line 38 of file AbsoluteDifference.cpp.
 {
     SimpleTensor<T> result(src1.shape(), dst_data_type);
     using intermediate_type = typename common_promoted_signed_type<T>::intermediate_type;
     for(int i = 0; i < src1.num_elements(); ++i)
     {
         intermediate_type val = std::abs(static_cast<intermediate_type>(src1[i]) - static_cast<intermediate_type>(src2[i]));
         result[i]             = saturate_cast<T>(val);
     }
     return result;
 }
References SimpleTensor< T >::num_elements(), and SimpleTensor< T >::shape().
absolute_difference() [2/4]
template SimpleTensor<uint8_t> arm_compute::test::validation::reference::absolute_difference (const SimpleTensor< uint8_t > & src1, const SimpleTensor< uint8_t > & src2, DataType dst_data_type)
absolute_difference() [3/4]
template SimpleTensor<int16_t> arm_compute::test::validation::reference::absolute_difference (const SimpleTensor< int16_t > & src1, const SimpleTensor< int16_t > & src2, DataType dst_data_type)
absolute_difference() [4/4]
template SimpleTensor<int8_t> arm_compute::test::validation::reference::absolute_difference (const SimpleTensor< int8_t > & src1, const SimpleTensor< int8_t > & src2, DataType dst_data_type)
accumulate() [1/2]
SimpleTensor< T2 > accumulate (const SimpleTensor< T1 > & src, DataType output_data_type)
Definition at line 38 of file Accumulate.cpp.
 {
     SimpleTensor<T2> dst{ src.shape(), output_data_type };
     library->fill_tensor_uniform(dst, 1, static_cast<T2>(0), static_cast<T2>(std::numeric_limits<T1>::max()));
     using intermediate_type = typename common_promoted_signed_type<T1, T2>::intermediate_type;
     for(int i = 0; i < src.num_elements(); ++i)
     {
         intermediate_type val = static_cast<intermediate_type>(src[i]) + static_cast<intermediate_type>(dst[i]);
         dst[i]                = saturate_cast<T2>(val);
     }
     return dst;
 }
References arm_compute::test::validation::dst, arm_compute::test::library, arm_compute::test::validation::output_data_type, and arm_compute::test::validation::src.
accumulate() [2/2]
template SimpleTensor<int16_t> arm_compute::test::validation::reference::accumulate (const SimpleTensor< uint8_t > & src, DataType output_data_type)
accumulate_squared() [1/2]
SimpleTensor< T2 > accumulate_squared (const SimpleTensor< T1 > & src, uint32_t shift, DataType output_data_type)
Definition at line 76 of file Accumulate.cpp.
 {
     ARM_COMPUTE_ERROR_ON_MSG(shift > 15, "Shift in accumulate_squared must be within the range [0, 15]");
     SimpleTensor<T2> dst{ src.shape(), output_data_type };
     library->fill_tensor_uniform(dst, 1, static_cast<T2>(0), static_cast<T2>(std::numeric_limits<T1>::max()));
     using intermediate_type = typename common_promoted_signed_type<T1, T2>::intermediate_type;
     intermediate_type denom = 1 << shift;
     for(int i = 0; i < src.num_elements(); ++i)
     {
         intermediate_type val = static_cast<intermediate_type>(dst[i]) + (static_cast<intermediate_type>(src[i]) * static_cast<intermediate_type>(src[i]) / denom);
         dst[i]                = saturate_cast<T2>(val);
     }
     return dst;
 }
References ARM_COMPUTE_ERROR_ON_MSG, arm_compute::test::validation::dst, arm_compute::test::library, arm_compute::test::validation::output_data_type, arm_compute::test::validation::shift, and arm_compute::test::validation::src.
accumulate_squared() [2/2]
template SimpleTensor<int16_t> arm_compute::test::validation::reference::accumulate_squared (const SimpleTensor< uint8_t > & src, uint32_t shift, DataType output_data_type)
accumulate_weighted() [1/2]
SimpleTensor< T2 > accumulate_weighted (const SimpleTensor< T1 > & src, float alpha, DataType output_data_type)
Definition at line 56 of file Accumulate.cpp.
 {
     ARM_COMPUTE_ERROR_ON_MSG(alpha < 0.f || alpha > 1.f, "Weight (alpha) specified in accumulate_weighted must be within the range [0, 1]");
     SimpleTensor<T2> dst{ src.shape(), output_data_type };
     library->fill_tensor_uniform(dst, 1, static_cast<T2>(0), static_cast<T2>(std::numeric_limits<T1>::max()));
     using intermediate_type = typename common_promoted_signed_type<T1, T2>::intermediate_type;
     for(int i = 0; i < src.num_elements(); ++i)
     {
         double val = (1. - static_cast<double>(alpha)) * static_cast<intermediate_type>(dst[i]) + static_cast<double>(alpha) * static_cast<intermediate_type>(src[i]);
         dst[i]     = static_cast<T2>(val);
     }
     return dst;
 }
References arm_compute::test::validation::alpha, ARM_COMPUTE_ERROR_ON_MSG, arm_compute::test::validation::dst, arm_compute::test::library, arm_compute::test::validation::output_data_type, and arm_compute::test::validation::src.
accumulate_weighted() [2/2]
template SimpleTensor<uint8_t> arm_compute::test::validation::reference::accumulate_weighted (const SimpleTensor< uint8_t > & src, float alpha, DataType output_data_type)
activate_float()
T arm_compute::test::validation::reference::activate_float (T x, T a, T b, ActivationLayerInfo::ActivationFunction activation) inline
Definition at line 39 of file ActivationLayer.h.
 {
     T ret;
     switch(activation)
     {
         case ActivationLayerInfo::ActivationFunction::ABS:
             ret = std::abs(x);
             break;
         case ActivationLayerInfo::ActivationFunction::LINEAR:
             ret = a * x + b;
             break;
         case ActivationLayerInfo::ActivationFunction::LOGISTIC:
             ret = static_cast<T>(1) / (static_cast<T>(1) + std::exp(-x));
             break;
         case ActivationLayerInfo::ActivationFunction::RELU:
             ret = std::max<T>(static_cast<T>(0), x);
             break;
         case ActivationLayerInfo::ActivationFunction::BOUNDED_RELU:
             ret = std::min<T>(a, std::max(static_cast<T>(0), x));
             break;
         case ActivationLayerInfo::ActivationFunction::LU_BOUNDED_RELU:
             ret = std::min<T>(a, std::max<T>(b, x));
             break;
         case ActivationLayerInfo::ActivationFunction::LEAKY_RELU:
             ret = (x > 0) ? x : a * x;
             break;
         case ActivationLayerInfo::ActivationFunction::SOFT_RELU:
             ret = std::log(static_cast<T>(1) + std::exp(x));
             break;
         case ActivationLayerInfo::ActivationFunction::SQRT:
             ret = std::sqrt(x);
             break;
         case ActivationLayerInfo::ActivationFunction::SQUARE:
             ret = x * x;
             break;
         case ActivationLayerInfo::ActivationFunction::TANH:
             ret = a * std::tanh(b * x);
             break;
         case ActivationLayerInfo::ActivationFunction::IDENTITY:
             ret = x;
             break;
         default:
             ARM_COMPUTE_ERROR("Unsupported activation function");
             break;
     }
     return ret;
 }
References ActivationLayerInfo::ABS, ARM_COMPUTE_ERROR, arm_compute::test::validation::b, ActivationLayerInfo::BOUNDED_RELU, ActivationLayerInfo::IDENTITY, ActivationLayerInfo::LEAKY_RELU, ActivationLayerInfo::LINEAR, ActivationLayerInfo::LOGISTIC, ActivationLayerInfo::LU_BOUNDED_RELU, ActivationLayerInfo::RELU, ActivationLayerInfo::SOFT_RELU, ActivationLayerInfo::SQRT, ActivationLayerInfo::SQUARE, and ActivationLayerInfo::TANH.
activation_layer() [1/3]
SimpleTensor< T > activation_layer (const SimpleTensor< T > & src, ActivationLayerInfo info, const QuantizationInfo & oq_info)
Definition at line 38 of file ActivationLayer.cpp.
 {
     ARM_COMPUTE_UNUSED(oq_info);
     // Create reference
     SimpleTensor<T> dst{ src.shape(), src.data_type(), 1 };
     // Compute reference
     const T a(info.a());
     const T b(info.b());
     for(int i = 0; i < src.num_elements(); ++i)
     {
         dst[i] = activate_float<T>(src[i], a, b, info.activation());
     }
     return dst;
 }
References ARM_COMPUTE_UNUSED, arm_compute::test::validation::b, arm_compute::test::validation::dst, arm_compute::test::validation::info, and arm_compute::test::validation::src.
Referenced by batch_normalization_layer().
activation_layer() [2/3]
template SimpleTensor<float> arm_compute::test::validation::reference::activation_layer (const SimpleTensor< float > & src, ActivationLayerInfo info, const QuantizationInfo & oq_info)
activation_layer() [3/3]
template SimpleTensor<half> arm_compute::test::validation::reference::activation_layer (const SimpleTensor< half > & src, ActivationLayerInfo info, const QuantizationInfo & oq_info)
activation_layer< int16_t >()
SimpleTensor<int16_t> arm_compute::test::validation::reference::activation_layer< int16_t > (const SimpleTensor< int16_t > & src, ActivationLayerInfo info, const QuantizationInfo & oq_info)
Definition at line 69 of file ActivationLayer.cpp.
 {
     const QuantizationInfo dst_qinfo = oq_info.empty() ? src.quantization_info() : oq_info;
     SimpleTensor<float>   src_tmp = convert_from_symmetric(src);
     SimpleTensor<float>   dst_tmp = activation_layer<float>(src_tmp, info);
     SimpleTensor<int16_t> dst     = convert_to_symmetric<int16_t>(dst_tmp, dst_qinfo);
     return dst;
 }
References arm_compute::test::validation::convert_from_symmetric(), arm_compute::test::validation::dst, QuantizationInfo::empty(), arm_compute::test::validation::info, and arm_compute::test::validation::src.
activation_layer< uint8_t >()
SimpleTensor<uint8_t> arm_compute::test::validation::reference::activation_layer< uint8_t > (const SimpleTensor< uint8_t > & src, ActivationLayerInfo info, const QuantizationInfo & oq_info)
Definition at line 58 of file ActivationLayer.cpp.
 {
     const QuantizationInfo dst_qinfo = oq_info.empty() ? src.quantization_info() : oq_info;
     SimpleTensor<float>   src_tmp = convert_from_asymmetric(src);
     SimpleTensor<float>   dst_tmp = activation_layer<float>(src_tmp, info);
     SimpleTensor<uint8_t> dst     = convert_to_asymmetric(dst_tmp, dst_qinfo);
     return dst;
 }
References arm_compute::test::validation::convert_from_asymmetric(), arm_compute::test::validation::convert_to_asymmetric(), arm_compute::test::validation::dst, QuantizationInfo::empty(), arm_compute::test::validation::info, and arm_compute::test::validation::src.
arithmetic_division() [1/3]
SimpleTensor< T > arithmetic_division (const SimpleTensor< T > & src1, const SimpleTensor< T > & src2, DataType data_type)
Definition at line 76 of file ArithmeticDivision.cpp.
 {
     SimpleTensor<T> dst(TensorShape::broadcast_shape(src1.shape(), src2.shape()), data_type);
     Coordinates id_src1{};
     Coordinates id_src2{};
     Coordinates id_dst{};
     BroadcastUnroll<Coordinates::num_max_dimensions>::unroll(src1, src2, dst, id_src1, id_src2, id_dst);
     return dst;
 }
References TensorShape::broadcast_shape(), arm_compute::test::validation::data_type, arm_compute::test::validation::dst, and SimpleTensor< T >::shape().
arithmetic_division() [2/3]
template SimpleTensor<half> arm_compute::test::validation::reference::arithmetic_division (const SimpleTensor< half > & src1, const SimpleTensor< half > & src2, DataType data_type)
arithmetic_division() [3/3]
template SimpleTensor<float> arm_compute::test::validation::reference::arithmetic_division (const SimpleTensor< float > & src1, const SimpleTensor< float > & src2, DataType data_type)
arithmetic_operation() [1/13]
SimpleTensor< T > arithmetic_operation (ArithmeticOperation op, const SimpleTensor< T > & src1, const SimpleTensor< T > & src2, SimpleTensor< T > & dst, ConvertPolicy convert_policy)
Definition at line 89 of file ArithmeticOperations.cpp.
 {
     Coordinates id_src1{};
     Coordinates id_src2{};
     Coordinates id_dst{};
     BroadcastUnroll<Coordinates::num_max_dimensions>::unroll(op, src1, src2, dst, convert_policy, id_src1, id_src2, id_dst);
     return dst;
 }
References arm_compute::test::validation::convert_policy, and arm_compute::test::validation::dst.
Referenced by laplacian_reconstruct().
arithmetic_operation() [2/13]
SimpleTensor< uint8_t > arithmetic_operation (ArithmeticOperation op, const SimpleTensor< uint8_t > & src1, const SimpleTensor< uint8_t > & src2, SimpleTensor< uint8_t > & dst, ConvertPolicy convert_policy)
Definition at line 101 of file ArithmeticOperations.cpp.
 {
     Coordinates id_src1{};
     Coordinates id_src2{};
     Coordinates id_dst{};
     if(dst.data_type() == DataType::QASYMM8)
     {
         SimpleTensor<float> src1_tmp = convert_from_asymmetric(src1);
         SimpleTensor<float> src2_tmp = convert_from_asymmetric(src2);
         SimpleTensor<float> dst_tmp(TensorShape::broadcast_shape(src1.shape(), src2.shape()), dst.data_type());
         BroadcastUnroll<Coordinates::num_max_dimensions>::unroll(op, src1_tmp, src2_tmp, dst_tmp, convert_policy, id_src1, id_src2, id_dst);
         dst = convert_to_asymmetric(dst_tmp, dst.quantization_info());
         return dst;
     }
     else
     {
         // DataType::U8
         BroadcastUnroll<Coordinates::num_max_dimensions>::unroll(op, src1, src2, dst, convert_policy, id_src1, id_src2, id_dst);
         return dst;
     }
 }
References TensorShape::broadcast_shape(), arm_compute::test::validation::convert_from_asymmetric(), arm_compute::test::validation::convert_policy, arm_compute::test::validation::convert_to_asymmetric(), arm_compute::test::validation::dst, arm_compute::QASYMM8, and SimpleTensor< T >::shape().
arithmetic_operation() [3/13]
SimpleTensor< int16_t > arithmetic_operation (ArithmeticOperation op, const SimpleTensor< int16_t > & src1, const SimpleTensor< int16_t > & src2, SimpleTensor< int16_t > & dst, ConvertPolicy convert_policy)
Definition at line 128 of file ArithmeticOperations.cpp.
 {
     Coordinates id_src1{};
     Coordinates id_src2{};
     Coordinates id_dst{};
     if(dst.data_type() == DataType::QSYMM16)
     {
         SimpleTensor<float> src1_tmp = convert_from_symmetric<int16_t>(src1);
         SimpleTensor<float> src2_tmp = convert_from_symmetric<int16_t>(src2);
         SimpleTensor<float> dst_tmp(TensorShape::broadcast_shape(src1.shape(), src2.shape()), dst.data_type());
         BroadcastUnroll<Coordinates::num_max_dimensions>::unroll(op, src1_tmp, src2_tmp, dst_tmp, convert_policy, id_src1, id_src2, id_dst);
         dst = convert_to_symmetric<int16_t>(dst_tmp, dst.quantization_info());
         return dst;
     }
     else
     {
         // DataType::S16
         BroadcastUnroll<Coordinates::num_max_dimensions>::unroll(op, src1, src2, dst, convert_policy, id_src1, id_src2, id_dst);
         return dst;
     }
 }
References TensorShape::broadcast_shape(), arm_compute::test::validation::convert_policy, arm_compute::test::validation::dst, arm_compute::QSYMM16, and SimpleTensor< T >::shape().
arithmetic_operation() [4/13]
template SimpleTensor< int8_t > arithmetic_operation (ArithmeticOperation op, const SimpleTensor< int8_t > & src1, const SimpleTensor< int8_t > & src2, SimpleTensor< int8_t > & dst, ConvertPolicy convert_policy)
arithmetic_operation() [5/13]
template SimpleTensor< half > arithmetic_operation (ArithmeticOperation op, const SimpleTensor< half > & src1, const SimpleTensor< half > & src2, SimpleTensor< half > & dst, ConvertPolicy convert_policy)
arithmetic_operation() [6/13]
template SimpleTensor< float > arithmetic_operation (ArithmeticOperation op, const SimpleTensor< float > & src1, const SimpleTensor< float > & src2, SimpleTensor< float > & dst, ConvertPolicy convert_policy)
arithmetic_operation() [7/13]
SimpleTensor< T > arithmetic_operation (ArithmeticOperation op, const SimpleTensor< T > & src1, const SimpleTensor< T > & src2, DataType dst_data_type, ConvertPolicy convert_policy)
Definition at line 158 of file ArithmeticOperations.cpp.
 {
     ARM_COMPUTE_ERROR_ON_MSG(is_data_type_quantized(dst_data_type), "For quantized input data types, the quantized output tensor should be passed directly.");
     SimpleTensor<T> dst(TensorShape::broadcast_shape(src1.shape(), src2.shape()), dst_data_type);
     arithmetic_operation<T>(op, src1, src2, dst, convert_policy);
     return dst;
 }
References ARM_COMPUTE_ERROR_ON_MSG, TensorShape::broadcast_shape(), arm_compute::test::validation::convert_policy, arm_compute::test::validation::dst, arm_compute::is_data_type_quantized(), and SimpleTensor< T >::shape().
arithmetic_operation() [8/13]
template SimpleTensor< int16_t > arithmetic_operation (ArithmeticOperation op, const SimpleTensor< int16_t > & src1, const SimpleTensor< int16_t > & src2, DataType dst_data_type, ConvertPolicy convert_policy)
arithmetic_operation() [9/13]
template SimpleTensor< int8_t > arithmetic_operation (ArithmeticOperation op, const SimpleTensor< int8_t > & src1, const SimpleTensor< int8_t > & src2, DataType dst_data_type, ConvertPolicy convert_policy)
arithmetic_operation() [10/13]
template SimpleTensor< half > arithmetic_operation (ArithmeticOperation op, const SimpleTensor< half > & src1, const SimpleTensor< half > & src2, DataType dst_data_type, ConvertPolicy convert_policy)
arithmetic_operation() [11/13]
template SimpleTensor< float > arithmetic_operation (ArithmeticOperation op, const SimpleTensor< float > & src1, const SimpleTensor< float > & src2, DataType dst_data_type, ConvertPolicy convert_policy)
arithmetic_operation() [12/13]
template SimpleTensor<int32_t> arm_compute::test::validation::reference::arithmetic_operation (ArithmeticOperation op, const SimpleTensor< int32_t > & src1, const SimpleTensor< int32_t > & src2, SimpleTensor< int32_t > & dst, ConvertPolicy convert_policy)
arithmetic_operation() [13/13]
template SimpleTensor<int32_t> arm_compute::test::validation::reference::arithmetic_operation (ArithmeticOperation op, const SimpleTensor< int32_t > & src1, const SimpleTensor< int32_t > & src2, DataType dst_data_type, ConvertPolicy convert_policy)
batch_normalization_layer() [1/3]
SimpleTensor< T > batch_normalization_layer (const SimpleTensor< T > & src, const SimpleTensor< T > & mean, const SimpleTensor< T > & var, const SimpleTensor< T > & beta, const SimpleTensor< T > & gamma, float epsilon, ActivationLayerInfo act_info)
Definition at line 40 of file BatchNormalizationLayer.cpp.
 {
     SimpleTensor<T> result(src.shape(), src.data_type());
     const auto cols       = static_cast<int>(src.shape()[0]);
     const auto rows       = static_cast<int>(src.shape()[1]);
     const auto depth      = static_cast<int>(src.shape()[2]);
     const int  upper_dims = src.shape().total_size() / (cols * rows * depth);
     for(int r = 0; r < upper_dims; ++r)
     {
         for(int i = 0; i < depth; ++i)
         {
             for(int k = 0; k < rows; ++k)
             {
                 for(int l = 0; l < cols; ++l)
                 {
                     const int   pos         = l + k * cols + i * rows * cols + r * cols * rows * depth;
                     const float denominator = sqrt(var[i] + epsilon);
                     const float numerator   = src[pos] - mean[i];
                     const float x_bar       = numerator / denominator;
                     result[pos]             = beta[i] + x_bar * gamma[i];
                 }
             }
         }
     }
     if(act_info.enabled())
     {
         result = activation_layer(result, act_info);
     }
     return result;
 }
References arm_compute::test::validation::act_info, activation_layer(), epsilon, and arm_compute::test::validation::src.
batch_normalization_layer() [2/3]
template SimpleTensor<float> arm_compute::test::validation::reference::batch_normalization_layer (const SimpleTensor< float > & src, const SimpleTensor< float > & mean, const SimpleTensor< float > & var, const SimpleTensor< float > & beta, const SimpleTensor< float > & gamma, float epsilon, ActivationLayerInfo act_info)
batch_normalization_layer() [3/3]
template SimpleTensor<half> arm_compute::test::validation::reference::batch_normalization_layer (const SimpleTensor< half > & src, const SimpleTensor< half > & mean, const SimpleTensor< half > & var, const SimpleTensor< half > & beta, const SimpleTensor< half > & gamma, float epsilon, ActivationLayerInfo act_info)
batch_to_space() [1/3]
SimpleTensor< T > batch_to_space (const SimpleTensor< T > & src, const SimpleTensor< int32_t > & block_shape, const TensorShape & dst_shape)
Definition at line 38 of file BatchToSpaceLayer.cpp.
 {
     ARM_COMPUTE_ERROR_ON(block_shape[0] <= 0);
     ARM_COMPUTE_ERROR_ON(block_shape[1] <= 0);
     SimpleTensor<T> result(dst_shape, src.data_type());
     int        in_pos    = 0;
     const auto width_in  = static_cast<int>(src.shape()[0]);
     const auto height_in = static_cast<int>(src.shape()[1]);
     const auto z_in      = static_cast<int>(src.shape()[2]);
     const auto batch_in  = static_cast<int>(src.shape()[3]);
     for(int batch = 0; batch < batch_in; ++batch)
     {
         for(int z = 0; z < z_in; ++z)
         {
             for(int y = 0; y < height_in; ++y)
             {
                 for(int x = 0; x < width_in; ++x)
                 {
                     const int r       = src.shape()[3] / (block_shape[0] * block_shape[1]);
                     const int out_x   = (block_shape[0] * x + (batch / r) % block_shape[0]);
                     const int out_y   = (block_shape[1] * y + (batch / r) / block_shape[0]);
                     const int out_pos = out_x + dst_shape[0] * out_y + z * dst_shape[0] * dst_shape[1] + (batch % r) * dst_shape[0] * dst_shape[1] * dst_shape[2];
                     result[out_pos]   = src[in_pos];
                     ++in_pos;
                 }
             }
         }
     }
     return result;
 }
References ARM_COMPUTE_ERROR_ON, arm_compute::test::validation::dst_shape, and arm_compute::test::validation::src.
batch_to_space() [2/3]
template SimpleTensor<float> arm_compute::test::validation::reference::batch_to_space (const SimpleTensor< float > & src, const SimpleTensor< int32_t > & block_shape, const TensorShape & dst_shape)
batch_to_space() [3/3]
template SimpleTensor<half> arm_compute::test::validation::reference::batch_to_space (const SimpleTensor< half > & src, const SimpleTensor< int32_t > & block_shape, const TensorShape & dst_shape)
bitwise_and() [1/2]
SimpleTensor< T > bitwise_and (const SimpleTensor< T > & src1, const SimpleTensor< T > & src2)
Definition at line 35 of file BitwiseAnd.cpp.
 {
     SimpleTensor<T> dst(src1.shape(), src1.data_type());
     for(int i = 0; i < src1.num_elements(); ++i)
     {
         dst[i] = src1[i] & src2[i];
     }
     return dst;
 }
References SimpleTensor< T >::data_type(), arm_compute::test::validation::dst, SimpleTensor< T >::num_elements(), and SimpleTensor< T >::shape().
bitwise_and() [2/2]
template SimpleTensor<uint8_t> arm_compute::test::validation::reference::bitwise_and (const SimpleTensor< uint8_t > & src1, const SimpleTensor< uint8_t > & src2)
bitwise_not() [1/2]
SimpleTensor< T > bitwise_not (const SimpleTensor< T > & src)
Definition at line 35 of file BitwiseNot.cpp.
 {
     SimpleTensor<T> dst(src.shape(), src.data_type());
     for(int i = 0; i < src.num_elements(); ++i)
     {
         dst[i] = ~src[i];
     }
     return dst;
 }
References arm_compute::test::validation::dst, and arm_compute::test::validation::src.
bitwise_not() [2/2]
template SimpleTensor<uint8_t> arm_compute::test::validation::reference::bitwise_not (const SimpleTensor< uint8_t > & src)
bitwise_or() [1/2]
SimpleTensor< T > bitwise_or (const SimpleTensor< T > & src1, const SimpleTensor< T > & src2)
Definition at line 35 of file BitwiseOr.cpp.
 {
     SimpleTensor<T> dst(src1.shape(), src1.data_type());
     for(int i = 0; i < src1.num_elements(); ++i)
     {
         dst[i] = src1[i] | src2[i];
     }
     return dst;
 }
References SimpleTensor< T >::data_type(), arm_compute::test::validation::dst, SimpleTensor< T >::num_elements(), and SimpleTensor< T >::shape().
bitwise_or() [2/2]
template SimpleTensor<uint8_t> arm_compute::test::validation::reference::bitwise_or (const SimpleTensor< uint8_t > & src1, const SimpleTensor< uint8_t > & src2)
bitwise_xor() [1/2]
SimpleTensor< T > bitwise_xor (const SimpleTensor< T > & src1, const SimpleTensor< T > & src2)
Definition at line 35 of file BitwiseXor.cpp.
 {
     SimpleTensor<T> dst(src1.shape(), src1.data_type());
     for(int i = 0; i < src1.num_elements(); ++i)
     {
         dst[i] = src1[i] ^ src2[i];
     }
     return dst;
 }
References SimpleTensor< T >::data_type(), arm_compute::test::validation::dst, SimpleTensor< T >::num_elements(), and SimpleTensor< T >::shape().
bitwise_xor() [2/2]
template SimpleTensor<uint8_t> arm_compute::test::validation::reference::bitwise_xor (const SimpleTensor< uint8_t > & src1, const SimpleTensor< uint8_t > & src2)
bounding_box_transform() [1/3]
SimpleTensor< T > bounding_box_transform (const SimpleTensor< T > & boxes, const SimpleTensor< T > & deltas, const BoundingBoxTransformInfo & info)
Definition at line 40 of file BoundingBoxTransform.cpp.
 {
     const DataType  boxes_data_type = deltas.data_type();
     SimpleTensor<T> pred_boxes(deltas.shape(), boxes_data_type);
     const size_t num_classes    = deltas.shape()[0] / 4;
     const size_t num_boxes      = deltas.shape()[1];
     const T     *deltas_ptr     = deltas.data();
     T           *pred_boxes_ptr = pred_boxes.data();
     const int img_h = floor(info.img_height() / info.scale() + 0.5f);
     const int img_w = floor(info.img_width() / info.scale() + 0.5f);
     const auto scale_after  = (info.apply_scale() ? T(info.scale()) : T(1));
     const auto scale_before = T(info.scale());
     ARM_COMPUTE_ERROR_ON(scale_before <= 0);
     const auto offset = (info.correct_transform_coords() ? T(1.f) : T(0.f));
     const size_t box_fields   = 4;
     const size_t class_fields = 4;
     for(size_t i = 0; i < num_boxes; ++i)
     {
         // Extract ROI information
         const size_t start_box = box_fields * i;
         const T      width     = (boxes[start_box + 2] / scale_before) - (boxes[start_box] / scale_before) + T(1.f);
         const T      height    = (boxes[start_box + 3] / scale_before) - (boxes[start_box + 1] / scale_before) + T(1.f);
         const T      ctr_x     = (boxes[start_box] / scale_before) + T(0.5f) * width;
         const T      ctr_y     = (boxes[start_box + 1] / scale_before) + T(0.5f) * height;
         for(size_t j = 0; j < num_classes; ++j)
         {
             // Extract deltas
             const size_t start_delta = i * num_classes * class_fields + class_fields * j;
             const T      dx          = deltas_ptr[start_delta] / T(info.weights()[0]);
             const T      dy          = deltas_ptr[start_delta + 1] / T(info.weights()[1]);
             T            dw          = deltas_ptr[start_delta + 2] / T(info.weights()[2]);
             T            dh          = deltas_ptr[start_delta + 3] / T(info.weights()[3]);
             // Clip dw and dh
             dw = std::min(dw, T(info.bbox_xform_clip()));
             dh = std::min(dh, T(info.bbox_xform_clip()));
             // Determine the predictions
             const T pred_ctr_x = dx * width + ctr_x;
             const T pred_ctr_y = dy * height + ctr_y;
             const T pred_w     = T(std::exp(dw)) * width;
             const T pred_h     = T(std::exp(dh)) * height;
             // Store the prediction into the output tensor
             pred_boxes_ptr[start_delta]     = scale_after * utility::clamp<T>(pred_ctr_x - T(0.5f) * pred_w, T(0), T(img_w - 1));
             pred_boxes_ptr[start_delta + 1] = scale_after * utility::clamp<T>(pred_ctr_y - T(0.5f) * pred_h, T(0), T(img_h - 1));
             pred_boxes_ptr[start_delta + 2] = scale_after * utility::clamp<T>(pred_ctr_x + T(0.5f) * pred_w - offset, T(0), T(img_w - 1));
             pred_boxes_ptr[start_delta + 3] = scale_after * utility::clamp<T>(pred_ctr_y + T(0.5f) * pred_h - offset, T(0), T(img_h - 1));
         }
     }
     return pred_boxes;
 }
References ARM_COMPUTE_ERROR_ON, SimpleTensor< T >::data(), SimpleTensor< T >::data_type(), arm_compute::test::validation::info, offset(), and SimpleTensor< T >::shape().
bounding_box_transform() [2/3]
template SimpleTensor<float> arm_compute::test::validation::reference::bounding_box_transform (const SimpleTensor< float > & boxes, const SimpleTensor< float > & deltas, const BoundingBoxTransformInfo & info)
bounding_box_transform() [3/3]
template SimpleTensor<half> arm_compute::test::validation::reference::bounding_box_transform (const SimpleTensor< half > & boxes, const SimpleTensor< half > & deltas, const BoundingBoxTransformInfo & info)
box3x3() [1/2]
SimpleTensor< T > box3x3 (const SimpleTensor< T > & src, BorderMode border_mode, T constant_border_value)
Definition at line 38 of file Box3x3.cpp.
 {
     SimpleTensor<T> dst(src.shape(), src.data_type());
     const std::array<T, 9> filter{ { 1, 1, 1, 1, 1, 1, 1, 1, 1 } };
     const float scale = 1.f / static_cast<float>(filter.size());
     for(int element_idx = 0; element_idx < src.num_elements(); ++element_idx)
     {
         const Coordinates id = index2coord(src.shape(), element_idx);
         apply_2d_spatial_filter(id, src, dst, TensorShape(3U, 3U), filter.data(), scale, border_mode, constant_border_value);
     }
     return dst;
 }
References arm_compute::test::validation::apply_2d_spatial_filter(), arm_compute::test::validation::border_mode, arm_compute::test::validation::dst, arm_compute::test::index2coord(), scale(), and arm_compute::test::validation::src.
box3x3() [2/2]
template SimpleTensor<uint8_t> arm_compute::test::validation::reference::box3x3 (const SimpleTensor< uint8_t > & src, BorderMode border_mode, uint8_t constant_border_value)
Referenced by arm_compute::test::validation::DATA_TEST_CASE().
canny_edge_detector() [1/2]
SimpleTensor< T > canny_edge_detector (const SimpleTensor< T > & src, int32_t upper_thresh, int32_t lower_thresh, int gradient_size, MagnitudeType norm_type, BorderMode border_mode, T constant_border_value)
Definition at line 234 of file CannyEdgeDetector.cpp.
 {
     if(gradient_size < 7)
     {
         return canny_edge_detector_impl<int16_t>(src, upper_thresh, lower_thresh, gradient_size, norm_type, border_mode, constant_border_value);
     }
     else
     {
         return canny_edge_detector_impl<int32_t>(src, upper_thresh, lower_thresh, gradient_size, norm_type, border_mode, constant_border_value);
     }
 }
References arm_compute::test::validation::border_mode, and arm_compute::test::validation::src.
canny_edge_detector() [2/2]
template SimpleTensor<uint8_t> arm_compute::test::validation::reference::canny_edge_detector (const SimpleTensor< uint8_t > & src, int32_t upper_thresh, int32_t lower_thresh, int gradient_size, MagnitudeType norm_type, BorderMode border_mode, uint8_t constant_border_value)
channel_combine() [1/2]
std::vector< SimpleTensor< T > > channel_combine (const TensorShape & shape, const std::vector< SimpleTensor< T >> & image_planes, Format format)
Definition at line 91 of file ChannelCombine.cpp.
 {
     std::vector<SimpleTensor<T>> dst = create_image_planes<T>(shape, format);
     for(unsigned int plane_idx = 0; plane_idx < dst.size(); ++plane_idx)
     {
         SimpleTensor<T> &dst_tensor = dst[plane_idx];
         for(int element_idx = 0; element_idx < dst_tensor.num_elements(); ++element_idx)
         {
             Coordinates coord = index2coord(dst_tensor.shape(), element_idx);
             switch(format)
             {
                 case Format::RGB888:
                 case Format::RGBA8888:
                 {
                     // Copy R/G/B or A channel
                     for(int channel_idx = 0; channel_idx < dst_tensor.num_channels(); ++channel_idx)
                     {
                         const T &src_value = reinterpret_cast<const T *>(image_planes[channel_idx](coord))[0];
                         T       &dst_value = reinterpret_cast<T *>(dst_tensor(coord))[channel_idx];
                         dst_value = src_value;
                     }
                     break;
                 }
                 case Format::YUYV422:
                 case Format::UYVY422:
                 {
                     // Find coordinates of the sub-sampled pixel
                     const Coordinates coord_hori(coord.x() / 2, coord.y());
                     const T &src0 = reinterpret_cast<const T *>(image_planes[0](coord))[0];
                     const T &src1 = reinterpret_cast<const T *>(image_planes[1](coord_hori))[0];
                     const int shift = (Format::YUYV422 == format) ? 1 : 0;
                     T        &dst0  = reinterpret_cast<T *>(dst_tensor(coord))[1 - shift];
                     T        &dst1  = reinterpret_cast<T *>(dst_tensor(coord))[0 + shift];
                     dst0 = src0;
                     dst1 = src1;
                     Coordinates coord2 = index2coord(dst_tensor.shape(), ++element_idx);
                     const T &src2 = reinterpret_cast<const T *>(image_planes[0](coord2))[0];
                     const T &src3 = reinterpret_cast<const T *>(image_planes[2](coord_hori))[0];
                     T &dst2 = reinterpret_cast<T *>(dst_tensor(coord2))[1 - shift];
                     T &dst3 = reinterpret_cast<T *>(dst_tensor(coord2))[0 + shift];
                     dst2 = src2;
                     dst3 = src3;
                     break;
                 }
                 case Format::NV12:
                 case Format::NV21:
                 {
                     if(0U == plane_idx)
                     {
                         // Get and combine Y channel from plane0 of destination multi-image
                         dst_tensor[element_idx] = image_planes[0][element_idx];
                     }
                     else
                     {
                         const int shift = (Format::NV12 == format) ? 0 : 1;
                         // Get U channel from plane1 and V channel from plane2 of the source
                         const T &src_u0 = reinterpret_cast<const T *>(image_planes[1](coord))[0];
                         const T &src_v0 = reinterpret_cast<const T *>(image_planes[2](coord))[0];
                         // Get U and V channel from plane1 of destination multi-image
                         T &dst_u0 = reinterpret_cast<T *>(dst_tensor(coord))[0 + shift];
                         T &dst_v0 = reinterpret_cast<T *>(dst_tensor(coord))[1 - shift];
                         // Combine channel U and V
                         dst_u0 = src_u0;
                         dst_v0 = src_v0;
                     }
                     break;
                 }
                 case Format::IYUV:
                 case Format::YUV444:
                 {
                     // Get Y/U/V element
                     const T &src = reinterpret_cast<const T *>(image_planes[plane_idx](coord))[0];
                     T       &dst = reinterpret_cast<T *>(dst_tensor(coord))[0];
                     // Copy Y/U/V plane
                     dst = src;
                     break;
                 }
                 default:
                     ARM_COMPUTE_ERROR("Not supported");
                     break;
             }
         }
     }
     return dst;
 }
References ARM_COMPUTE_ERROR, arm_compute::test::validation::dst, arm_compute::test::index2coord(), arm_compute::IYUV, SimpleTensor< T >::num_channels(), SimpleTensor< T >::num_elements(), arm_compute::NV12, arm_compute::NV21, arm_compute::RGB888, arm_compute::RGBA8888, arm_compute::test::validation::shape, SimpleTensor< T >::shape(), arm_compute::test::validation::shift, arm_compute::test::validation::src, arm_compute::UYVY422, Dimensions< T >::x(), Dimensions< T >::y(), arm_compute::YUV444, and arm_compute::YUYV422.
channel_combine() [2/2]
template std::vector<SimpleTensor<uint8_t> > arm_compute::test::validation::reference::channel_combine (const TensorShape & shape, const std::vector< SimpleTensor< uint8_t >> & image_planes, Format format)
channel_extract() [1/2]
SimpleTensor< uint8_t > channel_extract (const TensorShape & shape, const std::vector< SimpleTensor< T >> & tensor_planes, Format format, Channel channel)
Definition at line 38 of file ChannelExtract.cpp.
 {
     // Find plane and channel index
     const unsigned int plane_idx   = plane_idx_from_channel(format, channel);
     const unsigned int channel_idx = channel_idx_from_format(format, channel);
     // Create dst and get src tensor
     SimpleTensor<T> src = tensor_planes[plane_idx];
     SimpleTensor<T> dst{ calculate_subsampled_shape(shape, format, channel), Format::U8 };
     // Single planar formats with subsampling require a double horizontal step
     const int step_x = ((Format::YUYV422 == format || Format::UYVY422 == format) && Channel::Y != channel) ? 2 : 1;
     const int width  = dst.shape().x();
     const int height = dst.shape().y();
     // Loop over each pixel and extract channel
     for(int y = 0; y < height; ++y)
     {
         for(int x = 0; x < width; ++x)
         {
             const Coordinates src_coord{ x * step_x, y };
             const Coordinates dst_coord{ x, y };
             const auto *src_pixel = reinterpret_cast<const T *>(src(src_coord));
             auto       *dst_pixel = reinterpret_cast<T *>(dst(dst_coord));
             dst_pixel[0] = src_pixel[channel_idx]; // NOLINT
         }
     }
     return dst;
 }
References arm_compute::calculate_subsampled_shape(), arm_compute::channel_idx_from_format(), arm_compute::test::validation::dst, arm_compute::plane_idx_from_channel(), arm_compute::test::validation::shape, arm_compute::test::validation::src, arm_compute::U8, arm_compute::UYVY422, arm_compute::Y, and arm_compute::YUYV422.
channel_extract() [2/2]
template SimpleTensor<uint8_t> arm_compute::test::validation::reference::channel_extract (const TensorShape & shape, const std::vector< SimpleTensor< uint8_t >> & tensor_planes, Format format, Channel channel)
channel_shuffle() [1/6]
SimpleTensor< T > channel_shuffle (const SimpleTensor< T > & src, int num_groups)
Definition at line 39 of file ChannelShuffle.cpp.
 {
     // Create reference
     SimpleTensor<T> dst{ src.shape(), src.data_type(), src.num_channels(), src.quantization_info() };
     const int M                 = src.shape()[0];
     const int N                 = src.shape()[1];
     const int num_channels      = src.shape()[2];
     const int batches           = src.shape()[3];
     const int MxN               = M * N;
     const int channels_in_group = num_channels / num_groups;
     const T *src_ref = src.data();
     T       *dst_ref = dst.data();
     for(int n = 0; n < batches; ++n)
     {
         for(int g = 0; g < num_groups; ++g)
         {
             // Gather the group g block (of size channels_in_group * MxN) from output channels
             // g + 0 * G, g + 1 * G, g + 2 * G, g + G * (K - 1) etc.
             const T *src_ptr = src_ref + g * channels_in_group * MxN + n * num_channels * MxN;
             T       *dst_ptr = dst_ref + g * MxN + n * num_channels * MxN;
             for(int i = 0; i < channels_in_group; ++i)
             {
                 std::copy(src_ptr + i * MxN,
                           src_ptr + (i + 1) * MxN,
                           dst_ptr + i * num_groups * MxN);
             }
         }
     }
     return dst;
 }
References copy(), arm_compute::test::validation::dst, arm_compute::test::validation::dst_ref, arm_compute::test::validation::num_groups, arm_compute::test::validation::src, and arm_compute::test::validation::src_ref.
channel_shuffle() [2/6]
template SimpleTensor<uint8_t> arm_compute::test::validation::reference::channel_shuffle (const SimpleTensor< uint8_t > & src, int num_groups)
channel_shuffle() [3/6]
template SimpleTensor<uint16_t> arm_compute::test::validation::reference::channel_shuffle (const SimpleTensor< uint16_t > & src, int num_groups)
channel_shuffle() [4/6]
template SimpleTensor<uint32_t> arm_compute::test::validation::reference::channel_shuffle (const SimpleTensor< uint32_t > & src, int num_groups)
channel_shuffle() [5/6]
template SimpleTensor<half> arm_compute::test::validation::reference::channel_shuffle (const SimpleTensor< half > & src, int num_groups)
channel_shuffle() [6/6]
template SimpleTensor<float> arm_compute::test::validation::reference::channel_shuffle (const SimpleTensor< float > & src, int num_groups)
col2im() [1/4]
SimpleTensor< T > col2im (const SimpleTensor< T > & src, const TensorShape & dst_shape, unsigned int num_groups)
Definition at line 38 of file Col2Im.cpp.
 {
     SimpleTensor<T> dst{ dst_shape, src.data_type(), 1 };
     // Compute reference
     const size_t batches    = dst_shape.total_size() / (dst_shape.x() * dst_shape.y() * dst_shape.z());
     const size_t src_width  = src.shape().x();
     const size_t src_height = src.shape().y();
     if(num_groups == 1)
     {
         // Batches are on the 3rd dimension of the input tensor
         int dst_idx = 0;
         for(size_t b = 0; b < batches; ++b)
         {
             for(size_t x = 0; x < src_width; ++x)
             {
                 for(size_t y = 0; y < src_height; ++y)
                 {
                     dst[dst_idx++] = src[coord2index(src.shape(), Coordinates(x, y, b))];
                 }
             }
         }
     }
     else
     {
         int dst_idx = 0;
         for(size_t b = 0; b < batches; ++b)
         {
             for(size_t g = 0; g < num_groups; ++g)
             {
                 for(size_t x = 0; x < src_width; ++x)
                 {
                     for(size_t y = 0; y < src_height; ++y)
                     {
                         dst[dst_idx++] = src[coord2index(src.shape(), Coordinates(x, y, g, b))];
                     }
                 }
             }
         }
     }
     return dst;
 }
References arm_compute::test::validation::b, arm_compute::test::coord2index(), arm_compute::test::validation::dst, arm_compute::test::validation::dst_shape, arm_compute::test::validation::num_groups, arm_compute::test::validation::src, TensorShape::total_size(), Dimensions< T >::x(), Dimensions< T >::y(), and Dimensions< T >::z().
col2im() [2/4]
template SimpleTensor<float> arm_compute::test::validation::reference::col2im (const SimpleTensor< float > & src, const TensorShape & dst_shape, unsigned int num_groups)
col2im() [3/4]
template SimpleTensor<half> arm_compute::test::validation::reference::col2im (const SimpleTensor< half > & src, const TensorShape & dst_shape, unsigned int num_groups)
col2im() [4/4]
template SimpleTensor<uint8_t> arm_compute::test::validation::reference::col2im (const SimpleTensor< uint8_t > & src, const TensorShape & dst_shape, unsigned int num_groups)
color_convert() [1/2]
std::vector< SimpleTensor< T > > color_convert (const TensorShape & shape, const std::vector< SimpleTensor< T >> & tensor_planes, Format src_format, Format dst_format)
Definition at line 93 of file ColorConvert.cpp.
 {
     std::vector<SimpleTensor<T>> dst = create_image_planes<T>(shape, dst_format);
     switch(src_format)
     {
         case Format::RGB888:
         {
             switch(dst_format)
             {
                 case Format::RGBA8888:
                     colorconvert_helper::detail::colorconvert_rgb_to_rgbx(tensor_planes[0], dst[0]);
                     break;
                 case Format::U8:
                     colorconvert_helper::detail::colorconvert_rgb_to_u8(tensor_planes[0], dst[0]);
                     break;
                 case Format::NV12:
                     colorconvert_helper::detail::colorconvert_rgb_to_nv12(tensor_planes[0], dst);
                     break;
                 case Format::IYUV:
                     colorconvert_helper::detail::colorconvert_rgb_to_iyuv(tensor_planes[0], dst);
                     break;
                 case Format::YUV444:
                     colorconvert_helper::detail::colorconvert_rgb_to_yuv4(tensor_planes[0], dst);
                     break;
                 default:
                     ARM_COMPUTE_ERROR("Not Supported");
                     break;
             }
             break;
         }
         case Format::RGBA8888:
         {
             switch(dst_format)
             {
                 case Format::RGB888:
                     colorconvert_helper::detail::colorconvert_rgbx_to_rgb(tensor_planes[0], dst[0]);
                     break;
                 case Format::NV12:
                     colorconvert_helper::detail::colorconvert_rgb_to_nv12(tensor_planes[0], dst);
                     break;
                 case Format::IYUV:
                     colorconvert_helper::detail::colorconvert_rgb_to_iyuv(tensor_planes[0], dst);
                     break;
                 case Format::YUV444:
                     colorconvert_helper::detail::colorconvert_rgb_to_yuv4(tensor_planes[0], dst);
                     break;
                 default:
                     ARM_COMPUTE_ERROR("Not Supported");
                     break;
             }
             break;
         }
         case Format::UYVY422:
         case Format::YUYV422:
         {
             switch(dst_format)
             {
                 case Format::RGB888:
                 case Format::RGBA8888:
                     colorconvert_helper::detail::colorconvert_yuyv_to_rgb(tensor_planes[0], src_format, dst[0]);
                     break;
                 case Format::NV12:
                     colorconvert_helper::detail::colorconvert_yuyv_to_nv12(tensor_planes[0], src_format, dst);
                     break;
                 case Format::IYUV:
                     colorconvert_helper::detail::colorconvert_yuyv_to_iyuv(tensor_planes[0], src_format, dst);
                     break;
                 default:
                     ARM_COMPUTE_ERROR("Not Supported");
                     break;
             }
             break;
         }
         case Format::IYUV:
         {
             switch(dst_format)
             {
                 case Format::RGB888:
                 case Format::RGBA8888:
                     colorconvert_helper::detail::colorconvert_iyuv_to_rgb(shape, tensor_planes, dst[0]);
                     break;
                 default:
                     ARM_COMPUTE_ERROR("Not Supported");
                     break;
             }
             break;
         }
         case Format::NV12:
         case Format::NV21:
         {
             switch(dst_format)
             {
                 case Format::RGB888:
                 case Format::RGBA8888:
                     colorconvert_helper::detail::colorconvert_nv12_to_rgb(shape, src_format, tensor_planes, dst[0]);
                     break;
                 case Format::IYUV:
                     colorconvert_helper::detail::colorconvert_nv_to_iyuv(tensor_planes, src_format, dst);
                     break;
                 case Format::YUV444:
                     colorconvert_helper::detail::colorconvert_nv_to_yuv4(tensor_planes, src_format, dst);
                     break;
                 default:
                     ARM_COMPUTE_ERROR("Not Supported");
                     break;
             }
             break;
         }
         default:
             ARM_COMPUTE_ERROR("Not supported");
             break;
     }
     return dst;
 }
References ARM_COMPUTE_ERROR, arm_compute::test::colorconvert_helper::detail::colorconvert_iyuv_to_rgb(), arm_compute::test::colorconvert_helper::detail::colorconvert_nv12_to_rgb(), arm_compute::test::colorconvert_helper::detail::colorconvert_nv_to_iyuv(), arm_compute::test::colorconvert_helper::detail::colorconvert_nv_to_yuv4(), arm_compute::test::colorconvert_helper::detail::colorconvert_rgb_to_iyuv(), arm_compute::test::colorconvert_helper::detail::colorconvert_rgb_to_nv12(), arm_compute::test::colorconvert_helper::detail::colorconvert_rgb_to_rgbx(), arm_compute::test::colorconvert_helper::detail::colorconvert_rgb_to_u8(), arm_compute::test::colorconvert_helper::detail::colorconvert_rgb_to_yuv4(), arm_compute::test::colorconvert_helper::detail::colorconvert_rgbx_to_rgb(), arm_compute::test::colorconvert_helper::detail::colorconvert_yuyv_to_iyuv(), arm_compute::test::colorconvert_helper::detail::colorconvert_yuyv_to_nv12(), arm_compute::test::colorconvert_helper::detail::colorconvert_yuyv_to_rgb(), arm_compute::test::validation::dst, arm_compute::IYUV, arm_compute::NV12, arm_compute::NV21, arm_compute::RGB888, arm_compute::RGBA8888, arm_compute::test::validation::shape, arm_compute::U8, arm_compute::UYVY422, arm_compute::YUV444, and arm_compute::YUYV422.
color_convert() [2/2]
template std::vector<SimpleTensor<uint8_t> > arm_compute::test::validation::reference::color_convert (const TensorShape & shape, const std::vector< SimpleTensor< uint8_t >> & tensor_planes, Format src_format, Format dst_format)
compare() [1/4]
SimpleTensor< uint8_t > compare (ComparisonOperation op, const SimpleTensor< T > & src1, const SimpleTensor< T > & src2)
Definition at line 108 of file Comparisons.cpp.
 {
     SimpleTensor<uint8_t> dst(TensorShape::broadcast_shape(src1.shape(), src2.shape()), DataType::U8);
     Coordinates id_src1{};
     Coordinates id_src2{};
     Coordinates id_dst{};
     BroadcastUnroll<Coordinates::num_max_dimensions>::unroll(op, src1, src2, dst, id_src1, id_src2, id_dst);
     return dst;
 }
References TensorShape::broadcast_shape(), arm_compute::test::validation::dst, SimpleTensor< T >::shape(), and arm_compute::U8.
compare() [2/4]
SimpleTensor<uint8_t> arm_compute::test::validation::reference::compare (ComparisonOperation op, const SimpleTensor< uint8_t > & src1, const SimpleTensor< uint8_t > & src2)
Definition at line 120 of file Comparisons.cpp.
 {
     SimpleTensor<uint8_t> dst(TensorShape::broadcast_shape(src1.shape(), src2.shape()), DataType::U8);
     Coordinates id_src1{};
     Coordinates id_src2{};
     Coordinates id_dst{};
     if(src1.data_type() == DataType::QASYMM8)
     {
         SimpleTensor<float> src1_tmp = convert_from_asymmetric(src1);
         SimpleTensor<float> src2_tmp = convert_from_asymmetric(src2);
         BroadcastUnroll<Coordinates::num_max_dimensions>::unroll(op, src1_tmp, src2_tmp, dst, id_src1, id_src2, id_dst);
     }
     else
     {
         // DataType::U8
         BroadcastUnroll<Coordinates::num_max_dimensions>::unroll(op, src1, src2, dst, id_src1, id_src2, id_dst);
     }
     return dst;
 }
References TensorShape::broadcast_shape(), arm_compute::test::validation::convert_from_asymmetric(), SimpleTensor< T >::data_type(), arm_compute::test::validation::dst, arm_compute::QASYMM8, SimpleTensor< T >::shape(), and arm_compute::U8.
compare() [3/4]
template SimpleTensor<uint8_t> arm_compute::test::validation::reference::compare (ComparisonOperation op, const SimpleTensor< half > & src1, const SimpleTensor< half > & src2)
compare() [4/4]
template SimpleTensor<uint8_t> arm_compute::test::validation::reference::compare (ComparisonOperation op, const SimpleTensor< float > & src1, const SimpleTensor< float > & src2)
Referenced by arm_compute::test::validation::DATA_TEST_CASE().
compute_all_anchors() [1/3]
SimpleTensor< T > compute_all_anchors (const SimpleTensor< T > & anchors, const ComputeAnchorsInfo & info)
Definition at line 40 of file ComputeAllAnchors.cpp.
 {
     const int   num_anchors = anchors.shape()[1];
     const auto  width       = int(info.feat_width());
     const auto  height      = int(info.feat_height());
     const float stride      = 1. / info.spatial_scale();
     SimpleTensor<T> all_anchors(TensorShape(4, width * height * num_anchors), anchors.data_type());
     const T        *anchors_ptr     = anchors.data();
     T              *all_anchors_ptr = all_anchors.data();
     // Iterate over the input grid and anchors
     for(int y = 0; y < height; y++)
     {
         for(int x = 0; x < width; x++)
         {
             for(int a = 0; a < num_anchors; a++)
             {
                 const T      shift_x   = T(x) * T(stride);
                 const T      shift_y   = T(y) * T(stride);
                 const size_t anchor_id = a + x * num_anchors + y * width * num_anchors;
                 // x1
                 all_anchors_ptr[anchor_id * 4] = anchors_ptr[4 * a] + shift_x;
                 // y1
                 all_anchors_ptr[anchor_id * 4 + 1] = anchors_ptr[4 * a + 1] + shift_y;
                 // x2
                 all_anchors_ptr[anchor_id * 4 + 2] = anchors_ptr[4 * a + 2] + shift_x;
                 // y2
                 all_anchors_ptr[anchor_id * 4 + 3] = anchors_ptr[4 * a + 3] + shift_y;
             }
         }
     }
     return all_anchors;
 }
References SimpleTensor< T >::data(), SimpleTensor< T >::data_type(), arm_compute::test::validation::info, and SimpleTensor< T >::shape().
compute_all_anchors() [2/3]
template SimpleTensor<float> arm_compute::test::validation::reference::compute_all_anchors (const SimpleTensor< float > & anchors, const ComputeAnchorsInfo & info)
compute_all_anchors() [3/3]
template SimpleTensor<half> arm_compute::test::validation::reference::compute_all_anchors (const SimpleTensor< half > & anchors, const ComputeAnchorsInfo & info)
compute_min_max()
void arm_compute::test::validation::reference::compute_min_max (const SimpleTensor< T > & src, T & min, T & max)
Definition at line 35 of file MinMaxLocation.cpp.
 {
     // Set min and max to first pixel
     min = src[0];
     max = src[0];
     ARM_COMPUTE_ERROR_ON(src.num_elements() == 0);
     // Look for min and max values
     for(int i = 1; i < src.num_elements(); ++i)
     {
         if(src[i] < min)
         {
             min = src[i];
         }
         if(src[i] > max)
         {
             max = src[i];
         }
     }
 }
References ARM_COMPUTE_ERROR_ON, and arm_compute::test::validation::src.
compute_reduction_operation()
SimpleTensor<OT> arm_compute::test::validation::reference::compute_reduction_operation (const SimpleTensor< T > & src, const TensorShape & dst_shape, unsigned int axis, ReductionOperation op)
Definition at line 178 of file ReductionOperation.cpp.
 {
     // Create reference
     const bool         is_arg_min_max   = (op == ReductionOperation::ARG_IDX_MIN || op == ReductionOperation::ARG_IDX_MAX);
     DataType           output_data_type = is_arg_min_max ? DataType::U32 : src.data_type();
     SimpleTensor<OT>   dst{ dst_shape, output_data_type, 1, src.quantization_info() };
     const unsigned int src_width    = src.shape().x();
     const unsigned int src_height   = src.shape().y();
     const unsigned int src_depth    = src.shape().z();
     const unsigned int src_batch    = src.shape()[3];
     const int          reduce_elems = src.shape()[axis];
     switch(axis)
     {
         case 0:
         {
             const unsigned int upper_dims = src.shape().total_size_upper(1);
             for(unsigned int du = 0; du < upper_dims; ++du)
             {
                 const T *src_row_ptr = src.data() + du * reduce_elems;
                 dst[du]              = is_arg_min_max ?
                                        reduce_operation_arg_min_max<T, OT>(src_row_ptr, reduce_elems, op, 1) :
                                        reduce_operation<T, OT>(src_row_ptr, reduce_elems, op, 1);
             }
         }
         break;
         case 1:
         {
             const unsigned int upper_dims = src.shape().total_size_upper(2);
             for(unsigned int du = 0; du < upper_dims; ++du)
             {
                 for(unsigned int x = 0; x < src_width; ++x)
                 {
                     const int in_offset   = du * src_height * src_width + x;
                     const int out_offset  = du * src_width + x;
                     const T *src_row_ptr = src.data() + in_offset;
                     dst[out_offset]       = is_arg_min_max ?
                                             reduce_operation_arg_min_max<T, OT>(src_row_ptr, reduce_elems, op, src_width) :
                                             reduce_operation<T, OT>(src_row_ptr, reduce_elems, op, src_width);
                 }
             }
         }
         break;
         case 2:
         {
             const unsigned int upper_dims = src.shape().total_size_upper(3);
             for(unsigned int du = 0; du < upper_dims; ++du)
             {
                 for(unsigned int x = 0; x < src_width; ++x)
                 {
                     for(unsigned int y = 0; y < src_height; ++y)
                     {
                         const int in_offset   = du * src_depth * src_height * src_width + y * src_width + x;
                         const int out_offset  = du * src_width * src_height + y * src_width + x;
                         const T *src_row_ptr = src.data() + in_offset;
                         dst[out_offset]       = is_arg_min_max ?
                                                 reduce_operation_arg_min_max<T, OT>(src_row_ptr, reduce_elems, op, src_width * src_height) :
                                                 reduce_operation<T, OT>(src_row_ptr, reduce_elems, op, src_width * src_height);
                     }
                 }
             }
         }
         break;
         case 3:
         {
             const unsigned int upper_dims = src.shape().total_size_upper(4);
             for(unsigned int du = 0; du < upper_dims; ++du)
             {
                 for(unsigned int z = 0; z < src_depth; ++z)
                 {
                     for(unsigned int y = 0; y < src_height; ++y)
                     {
                         for(unsigned int x = 0; x < src_width; ++x)
{
                             const int in_offset   = du * src_batch * src_depth * src_height * src_width + z * src_width * src_height + y * src_width + x;
                             const int out_offset  = du * src_depth * src_height * src_width + z * src_width * src_height + y * src_width + x;
                             const T *src_row_ptr = src.data() + in_offset;
                             dst[out_offset]       = is_arg_min_max ?
                                                     reduce_operation_arg_min_max<T, OT>(src_row_ptr, reduce_elems, op, src_width * src_height * src_depth) :
                                                     reduce_operation<T, OT>(src_row_ptr, reduce_elems, op, src_width * src_height * src_depth);
                         }
                     }
                 }
             }
         }
         break;
         default:
             ARM_COMPUTE_ERROR("Unsupported reduction axis");
     }
     return dst;
 }
References arm_compute::ARG_IDX_MAX, arm_compute::ARG_IDX_MIN, ARM_COMPUTE_ERROR, arm_compute::test::validation::axis, arm_compute::test::validation::dst, arm_compute::test::validation::dst_shape, arm_compute::test::validation::output_data_type, arm_compute::test::validation::src, and arm_compute::U32.
concatenate_layer() [1/4]
SimpleTensor< T > concatenate_layer (std::vector< SimpleTensor< T >> & srcs, SimpleTensor< T > & dst, unsigned int axis)
Definition at line 104 of file ConcatenateLayer.cpp.
 {
     switch(axis)
     {
         case Window::DimX:
         {
             return widthconcatenate_layer(srcs, dst);
         }
         case Window::DimY:
         {
             for(auto &t : srcs)
             {
                 t = reference::permute<T>(t, PermutationVector(1U, 0U));
             }
             dst = reference::permute<T>(dst, PermutationVector(1U, 0U));
             return reference::permute<T>(widthconcatenate_layer(srcs, dst), PermutationVector(1U, 0U));
         }
         case Window::DimZ:
         {
             for(auto &t : srcs)
             {
                 t = reference::permute<T>(t, PermutationVector(2U, 1U, 0U));
             }
             dst = reference::permute<T>(dst, PermutationVector(2U, 1U, 0U));
             return reference::permute<T>(widthconcatenate_layer(srcs, dst), PermutationVector(2U, 1U, 0U));
         }
         case 3:
         {
             for(auto &t : srcs)
             {
                 t = reference::permute<T>(t, PermutationVector(3U, 2U, 1U, 0U));
             }
             dst      = reference::permute<T>(dst, PermutationVector(3U, 2U, 1U, 0U));
             auto ret = reference::permute<T>(widthconcatenate_layer(srcs, dst), PermutationVector(3U, 2U, 1U, 0U));
             return ret;
         }
         default:
         {
             ARM_COMPUTE_ERROR("Not supported");
             return dst;
         }
     }
 }
References ARM_COMPUTE_ERROR, arm_compute::test::validation::axis, Window::DimX, Window::DimY, Window::DimZ, and arm_compute::test::validation::dst.
concatenate_layer() [2/4]
template SimpleTensor<float> arm_compute::test::validation::reference::concatenate_layer (std::vector< SimpleTensor< float >> & srcs, SimpleTensor< float > & dst, unsigned int axis)
concatenate_layer() [3/4]
template SimpleTensor<half> arm_compute::test::validation::reference::concatenate_layer (std::vector< SimpleTensor< half >> & srcs, SimpleTensor< half > & dst, unsigned int axis)
concatenate_layer() [4/4]
template SimpleTensor<uint8_t> arm_compute::test::validation::reference::concatenate_layer (std::vector< SimpleTensor< uint8_t >> & srcs, SimpleTensor< uint8_t > & dst, unsigned int axis)
conv2d_dft() [1/2]
SimpleTensor< T > conv2d_dft (const SimpleTensor< T > & src, const SimpleTensor< T > & w, const PadStrideInfo & conv_info)
Performs and DFT based convolution on a real input.
Parameters
[in] src Source tensor.
[in] w Weights tensor.
[in] conv_info Convolution related metadata.
Returns
The output tensor.
Definition at line 374 of file DFT.cpp.
 {
     // Pad input to full padding
     const PaddingList padding_in = { { 0, w.shape()[0] - 1 }, { 0, w.shape()[1] - 1 } };
     auto              padded_src = pad_layer(src, padding_in);
     // Flip weights
     std::vector<uint32_t>  axis_v = { 0, 1 };
     SimpleTensor<uint32_t> axis{ TensorShape(2U), DataType::U32 };
     std::copy(axis_v.begin(), axis_v.begin() + axis.shape().x(), axis.data());
     auto flipped_w = reverse(w, axis);
     // Pad weights to have the same size as input
     const PaddingList paddings_w = { { 0, src.shape()[0] - 1 }, { 0, src.shape()[1] - 1 } };
     auto              padded_w   = pad_layer(flipped_w, paddings_w);
     // Transform input and weights to frequency domain
     auto Fsrc = rdft_2d(padded_src);
     auto Fw   = rdft_2d(padded_w);
     // Perform dot product
     auto Fdst = complex_mul_and_reduce(Fsrc, Fw);
     // Transform output back to frequency domain
     auto conv_res = ridft_2d(Fdst);
     // Slice output
     const int start_left = w.shape().x() - conv_info.pad_left() - 1;
     const int start_top  = w.shape().y() - conv_info.pad_top() - 1;
     const int end_right  = conv_res.shape().x() - (w.shape().x() - conv_info.pad_right() - 1);
     const int end_botton = conv_res.shape().y() - (w.shape().y() - conv_info.pad_bottom() - 1);
     return slice(conv_res, Coordinates(start_left, start_top), Coordinates(end_right, end_botton));
 }
References arm_compute::test::validation::axis, arm_compute::test::validation::conv_info, copy(), pad_layer(), rdft_2d(), reverse(), ridft_2d(), slice(), arm_compute::test::validation::src, arm_compute::U32, and arm_compute::test::validation::w.
conv2d_dft() [2/2]
template SimpleTensor<float> arm_compute::test::validation::reference::conv2d_dft (const SimpleTensor< float > & src, const SimpleTensor< float > & w, const PadStrideInfo & conv_info)
convert_fully_connected_weights() [1/4]
SimpleTensor< T > convert_fully_connected_weights (const SimpleTensor< T > & src, const TensorShape & original_input_shape, const DataLayout training_data_layout)
Definition at line 35 of file ConvertFullyConnectedWeights.cpp.
 {
     SimpleTensor<T> dst(src.shape(), src.data_type());
     const DataLayout original_input_data_layout = (training_data_layout == DataLayout::NCHW) ? DataLayout::NHWC : DataLayout::NCHW;
     const int width_idx   = get_data_layout_dimension_index(original_input_data_layout, DataLayoutDimension::WIDTH);
     const int height_idx  = get_data_layout_dimension_index(original_input_data_layout, DataLayoutDimension::HEIGHT);
     const int channel_idx = get_data_layout_dimension_index(original_input_data_layout, DataLayoutDimension::CHANNEL);
     const bool         is_nchw_to_nhwc           = training_data_layout == DataLayout::NCHW;
     const unsigned int num_elems_per_input_plane = original_input_shape[width_idx] * original_input_shape[height_idx];
     const unsigned int num_channels              = original_input_shape[channel_idx];
     const unsigned int factor_1                  = is_nchw_to_nhwc ? num_elems_per_input_plane : num_channels;
     const unsigned int factor_2                  = is_nchw_to_nhwc ? num_channels : num_elems_per_input_plane;
     for(int i = 0; i < src.num_elements(); ++i)
     {
         const Coordinates coords_in = index2coords(src.shape(), i);
         const Coordinates coords_out(coords_in.x(), coords_in.y() % factor_1 * factor_2 + coords_in.y() / factor_1);
         dst[coords2index(dst.shape(), coords_out)] = src[i];
     }
     return dst;
 }
References arm_compute::CHANNEL, arm_compute::coords2index(), arm_compute::test::validation::dst, arm_compute::get_data_layout_dimension_index(), arm_compute::HEIGHT, arm_compute::index2coords(), arm_compute::NCHW, arm_compute::NHWC, arm_compute::test::validation::src, arm_compute::WIDTH, Dimensions< T >::x(), and Dimensions< T >::y().
convert_fully_connected_weights() [2/4]
template SimpleTensor<uint8_t> arm_compute::test::validation::reference::convert_fully_connected_weights (const SimpleTensor< uint8_t > & src, const TensorShape & original_input_shape, const DataLayout training_data_layout)
convert_fully_connected_weights() [3/4]
template SimpleTensor<half> arm_compute::test::validation::reference::convert_fully_connected_weights (const SimpleTensor< half > & src, const TensorShape & original_input_shape, const DataLayout training_data_layout)
convert_fully_connected_weights() [4/4]
template SimpleTensor<float> arm_compute::test::validation::reference::convert_fully_connected_weights (const SimpleTensor< float > & src, const TensorShape & original_input_shape, const DataLayout training_data_layout)
convolution()
SimpleTensor< T > convolution (const SimpleTensor< uint8_t > & src, DataType output_data_type, const int16_t * conv, uint32_t scale, BorderMode border_mode, uint8_t constant_border_value, const unsigned int width, const unsigned int height)
Definition at line 38 of file Convolution.cpp.
 {
     ARM_COMPUTE_ERROR_ON(scale == 0);
     ARM_COMPUTE_ERROR_ON(scale >= std::numeric_limits<int32_t>::max());
     SimpleTensor<T>       dst(src.shape(), output_data_type);
     SimpleTensor<int32_t> sum(src.shape(), output_data_type);
     for(int element_idx = 0; element_idx < src.num_elements(); ++element_idx)
     {
         const Coordinates id = index2coord(src.shape(), element_idx);
         apply_2d_spatial_filter(id, src, sum, TensorShape(width, height), conv, 1, border_mode, constant_border_value);
         dst[element_idx] = saturate_cast<T>(tensor_elem_at<int32_t>(sum, id, border_mode, constant_border_value) / static_cast<int>(scale));
     }
     return dst;
 }
References arm_compute::test::validation::apply_2d_spatial_filter(), ARM_COMPUTE_ERROR_ON, arm_compute::test::validation::border_mode, arm_compute::test::validation::conv, arm_compute::test::validation::dst, arm_compute::test::index2coord(), arm_compute::test::validation::output_data_type, scale(), arm_compute::test::validation::src, and sum().
convolution_layer() [1/4]
SimpleTensor< T > convolution_layer (const SimpleTensor< T > & src, const SimpleTensor< T > & weights, const SimpleTensor< TB > & bias, const TensorShape & output_shape, const PadStrideInfo & info, const Size2D & dilation, unsigned int num_groups, QuantizationInfo out_quant_info)
Definition at line 113 of file ConvolutionLayer.cpp.
 {
     // if no explicit quantization has been set you the same as src
     if(out_quant_info == QuantizationInfo())
     {
         out_quant_info = src.quantization_info();
     }
     // Create reference
     SimpleTensor<T> dst{ output_shape, src.data_type(), 1, out_quant_info };
     if(src.data_layout() == DataLayout::NHWC)
     {
         SimpleTensor<T> src_nchw     = reference::permute<T>(src, PermutationVector(1U, 2U, 0U));
         SimpleTensor<T> weights_nchw = reference::permute<T>(weights, PermutationVector(1U, 2U, 0U));
         SimpleTensor<T> dst_nchw     = reference::permute<T>(dst, PermutationVector(1U, 2U, 0U));
         return reference::permute<T>(convolution_layer_nchw(src_nchw, weights_nchw, bias, dst_nchw, info, dilation, num_groups), PermutationVector(2U, 0U, 1U));
     }
     else
     {
         return convolution_layer_nchw(src, weights, bias, dst, info, dilation, num_groups);
     }
 }
References arm_compute::test::validation::bias, convolution_layer_nchw(), arm_compute::test::validation::dilation, arm_compute::test::validation::dst, arm_compute::test::validation::info, arm_compute::NHWC, arm_compute::test::validation::num_groups, arm_compute::test::validation::output_shape, arm_compute::test::validation::src, and arm_compute::test::validation::weights.
Referenced by deconvolution_layer(), and depthwise_separable_convolution_layer().
convolution_layer() [2/4]
template SimpleTensor<float> arm_compute::test::validation::reference::convolution_layer (const SimpleTensor< float > & src, const SimpleTensor< float > & weights, const SimpleTensor< float > & bias, const TensorShape & output_shape, const PadStrideInfo & info, const Size2D & dilation, unsigned int num_groups, QuantizationInfo out_quant_info)
convolution_layer() [3/4]
template SimpleTensor<half> arm_compute::test::validation::reference::convolution_layer (const SimpleTensor< half > & src, const SimpleTensor< half > & weights, const SimpleTensor< half > & bias, const TensorShape & output_shape, const PadStrideInfo & info, const Size2D & dilation, unsigned int num_groups, QuantizationInfo out_quant_info)
convolution_layer() [4/4]
template SimpleTensor<uint8_t> arm_compute::test::validation::reference::convolution_layer (const SimpleTensor< uint8_t > & src, const SimpleTensor< uint8_t > & weights, const SimpleTensor< int32_t > & bias, const TensorShape & output_shape, const PadStrideInfo & info, const Size2D & dilation, unsigned int num_groups, QuantizationInfo out_quant_info)
convolution_layer_nchw()
SimpleTensor<T> arm_compute::test::validation::reference::convolution_layer_nchw (const SimpleTensor< T > & src, const SimpleTensor< T > & weights, const SimpleTensor< TB > & bias, SimpleTensor< T > & dst, const PadStrideInfo & info, const Size2D & dilation, unsigned int num_groups)
Definition at line 49 of file ConvolutionLayer.cpp.
 {
     ARM_COMPUTE_ERROR_ON((src.shape()[2] / num_groups) != weights.shape()[2]);
     // Compute reference
     const int width_in       = src.shape().x();
     const int height_in      = src.shape().y();
     const int depth_in       = src.shape().z();
     const int width_out      = dst.shape().x();
     const int height_out     = dst.shape().y();
     const int depth_out      = dst.shape().z();
     const int width_weights  = weights.shape().x();
     const int height_weights = weights.shape().y();
     const int depth_weights  = weights.shape().z();
     const int pad_left       = info.pad_left();
     const int pad_top        = info.pad_top();
     const int stride_xi      = info.stride().first;
     const int stride_yi      = info.stride().second;
     auto output_wh = scaled_dimensions(width_in, height_in, width_weights, height_weights, info, dilation);
     const int start_xi    = (dilation.x() * (width_weights - 1) + 1) / 2 - pad_left;
     const int start_yi    = (dilation.y() * (height_weights - 1) + 1) / 2 - pad_top;
     const int end_xi      = output_wh.first * stride_xi;
     const int end_yi      = output_wh.second * stride_yi;
     const int num_batches = src.shape().total_size() / (width_in * height_in * depth_in);
     for(int r = 0; r < num_batches; ++r)
     {
         for(int yi = start_yi; yi < start_yi + end_yi; yi += stride_yi)
         {
             for(int xi = start_xi; xi < start_xi + end_xi; xi += stride_xi)
             {
                 for(int group = 0; group < static_cast<int>(num_groups); ++group)
                 {
                     for(int ofm = 0; ofm < static_cast<int>(depth_out / num_groups); ++ofm)
                     {
                         // Compute input and output offsets
                         const int offset_in  = r * width_in * height_in * depth_in + (group * (depth_in / num_groups) * width_in * height_in);
                         const int xo         = (xi - start_xi) / stride_xi;
                         const int yo         = (yi - start_yi) / stride_yi;
                         const int offset_out = xo + yo * width_out + ((ofm + group * (depth_out / num_groups)) * width_out * height_out) + (r * width_out * height_out * depth_out);
                         const int offset_w   = (ofm + group * (depth_out / num_groups)) * width_weights * height_weights * depth_weights;
                         const int offset_b   = (ofm + group * (depth_out / num_groups));
                         ARM_COMPUTE_ASSERT(xo < width_out);
                         ARM_COMPUTE_ASSERT(yo < height_out);
                         // Compute 3D convolution
                         convolution_3d::detail::convolution3d(src, weights, bias, dst,
                                                               offset_in, offset_w, offset_b, offset_out,
                                                               xi, yi,
                                                               width_in, height_in, (depth_in / num_groups),
                                                               width_weights, height_weights, dilation.x(), dilation.y());
                     }
                 }
             }
         }
     }
     return dst;
 }
References ARM_COMPUTE_ASSERT, ARM_COMPUTE_ERROR_ON, arm_compute::test::validation::bias, arm_compute::test::convolution_3d::detail::convolution3d(), arm_compute::test::validation::dilation, arm_compute::test::validation::dst, arm_compute::test::validation::info, arm_compute::test::validation::num_groups, arm_compute::test::validation::output_wh, arm_compute::scaled_dimensions(), arm_compute::test::validation::src, and arm_compute::test::validation::weights.
Referenced by convolution_layer().
copy() [1/9]
SimpleTensor< T > copy (const SimpleTensor< T > & src, const TensorShape & output_shape)
Definition at line 37 of file Copy.cpp.
 {
     ARM_COMPUTE_ERROR_ON_MISMATCHING_DIMENSIONS(src.shape(), output_shape);
     SimpleTensor<T> dst(output_shape, src.data_type());
     std::copy_n(src.data(), src.num_elements(), dst.data());
     return dst;
 }
References ARM_COMPUTE_ERROR_ON_MISMATCHING_DIMENSIONS, arm_compute::test::validation::dst, arm_compute::test::validation::output_shape, and arm_compute::test::validation::src.
Referenced by channel_shuffle(), Dimensions< size_t >::collapse(), TensorShape::collapsed_from(), conv2d_dft(), depthconcatenate_layer(), flatten_layer(), gemm_reshape_lhs_matrix(), gemm_reshape_rhs_matrix(), arm_compute::test::validation::get_tile(), Dimensions< size_t >::remove(), and TensorShape::remove_dimension().
copy() [2/9]
template SimpleTensor<uint8_t> arm_compute::test::validation::reference::copy (const SimpleTensor< uint8_t > & src, const TensorShape & output_shape)
copy() [3/9]
template SimpleTensor<int8_t> arm_compute::test::validation::reference::copy (const SimpleTensor< int8_t > & src, const TensorShape & output_shape)
copy() [4/9]
template SimpleTensor<uint16_t> arm_compute::test::validation::reference::copy (const SimpleTensor< uint16_t > & src, const TensorShape & output_shape)
copy() [5/9]
template SimpleTensor<int16_t> arm_compute::test::validation::reference::copy (const SimpleTensor< int16_t > & src, const TensorShape & output_shape)
copy() [6/9]
template SimpleTensor<uint32_t> arm_compute::test::validation::reference::copy (const SimpleTensor< uint32_t > & src, const TensorShape & output_shape)
copy() [7/9]
template SimpleTensor<int32_t> arm_compute::test::validation::reference::copy (const SimpleTensor< int32_t > & src, const TensorShape & output_shape)
copy() [8/9]
template SimpleTensor<half> arm_compute::test::validation::reference::copy (const SimpleTensor< half > & src, const TensorShape & output_shape)
copy() [9/9]
template SimpleTensor<float> arm_compute::test::validation::reference::copy (const SimpleTensor< float > & src, const TensorShape & output_shape)
crop_and_resize() [1/7]
SimpleTensor< float > crop_and_resize (const SimpleTensor< T > & src, const SimpleTensor< float > & boxes, SimpleTensor< int32_t > box_ind, Coordinates2D crop_size, InterpolationPolicy method, float extrapolation_value)
Definition at line 160 of file CropResize.cpp.
 {
     ARM_COMPUTE_ERROR_ON(src.shape().num_dimensions() > 4);
     ARM_COMPUTE_ERROR_ON(src.data_layout() != DataLayout::NHWC);
     const TensorShape   out_shape(src.shape()[0], crop_size.x, crop_size.y, boxes.shape()[1]);
     SimpleTensor<float> out{ out_shape, DataType::F32, 1, QuantizationInfo(), DataLayout::NHWC };
     const TensorShape scaled_image_shape(src.shape()[0], crop_size.x, crop_size.y);
     for(uint32_t i = 0; i < boxes.shape()[1]; ++i)
     {
         Coordinates start = Coordinates(std::floor((*reinterpret_cast<const float *>(boxes(Coordinates(1, i)))) * (src.shape()[1] - 1) + 0.5f),
                                         std::floor((*reinterpret_cast<const float *>(boxes(Coordinates(0, i)))) * (src.shape()[2] - 1) + 0.5f));
         Coordinates end = Coordinates(std::floor((*reinterpret_cast<const float *>(boxes(Coordinates(3, i)))) * (src.shape()[1] - 1) + 0.5f),
                                       std::floor((*reinterpret_cast<const float *>(boxes(Coordinates(2, i)))) * (src.shape()[2] - 1) + 0.5f));
         SimpleTensor<float> cropped = crop_image(src, start, end, box_ind[i], extrapolation_value);
         SimpleTensor<float> scaled  = scale_image(cropped, scaled_image_shape, method, extrapolation_value);
         std::copy_n(reinterpret_cast<float *>(scaled.data()), scaled.num_elements(), reinterpret_cast<float *>(out(Coordinates(0, 0, 0, i))));
     }
     return out;
 }
References ARM_COMPUTE_ERROR_ON, SimpleTensor< T >::data(), arm_compute::F32, arm_compute::NHWC, SimpleTensor< T >::num_elements(), SimpleTensor< T >::shape(), arm_compute::test::validation::src, Coordinates2D::x, and Coordinates2D::y.
crop_and_resize() [2/7]
template SimpleTensor<float> arm_compute::test::validation::reference::crop_and_resize (const SimpleTensor< float > & src, const SimpleTensor< float > & boxes, SimpleTensor< int32_t > box_ind, Coordinates2D crop_size, InterpolationPolicy method, float extrapolation_value)
crop_and_resize() [3/7]
template SimpleTensor<float> arm_compute::test::validation::reference::crop_and_resize (const SimpleTensor< uint16_t > & src, const SimpleTensor< float > & boxes, SimpleTensor< int32_t > box_ind, Coordinates2D crop_size, InterpolationPolicy method, float extrapolation_value)
crop_and_resize() [4/7]
template SimpleTensor<float> arm_compute::test::validation::reference::crop_and_resize (const SimpleTensor< uint32_t > & src, const SimpleTensor< float > & boxes, SimpleTensor< int32_t > box_ind, Coordinates2D crop_size, InterpolationPolicy method, float extrapolation_value)
crop_and_resize() [5/7]
template SimpleTensor<float> arm_compute::test::validation::reference::crop_and_resize (const SimpleTensor< int16_t > & src, const SimpleTensor< float > & boxes, SimpleTensor< int32_t > box_ind, Coordinates2D crop_size, InterpolationPolicy method, float extrapolation_value)
crop_and_resize() [6/7]
template SimpleTensor<float> arm_compute::test::validation::reference::crop_and_resize (const SimpleTensor< int32_t > & src, const SimpleTensor< float > & boxes, SimpleTensor< int32_t > box_ind, Coordinates2D crop_size, InterpolationPolicy method, float extrapolation_value)
crop_and_resize() [7/7]
template SimpleTensor<float> arm_compute::test::validation::reference::crop_and_resize (const SimpleTensor< half > & src, const SimpleTensor< float > & boxes, SimpleTensor< int32_t > box_ind, Coordinates2D crop_size, InterpolationPolicy method, float extrapolation_value)
deconvolution_layer() [1/4]
SimpleTensor< T > deconvolution_layer (const SimpleTensor< T > & src, const SimpleTensor< T > & weights, const SimpleTensor< TB > & bias, const TensorShape & output_shape, const PadStrideInfo & info)
Deconvolution reference implementation.
src Input tensor. 3 lower dimensions represent a single input, and an optional 4th dimension for batch of inputs. Data types supported: F32. weights The 4d weights with dimensions [width, height, OFM, IFM]. Data type supported: Same as input. bias Optional, ignored if NULL. The biases have one dimension. Data type supported: Same as input. output_shape Output tensor shape. The output has the same number of dimensions as the input. info Contains padding and policies to be used in the deconvolution, this is decribed in PadStrideInfo. a The number of zeros added to right and top edges of the input.
Definition at line 37 of file DeconvolutionLayer.cpp.
 {
     // Create reference
     const int stride_x           = info.stride().first;
     const int stride_y           = info.stride().second;
     const int weights_width      = weights.shape().x();
     const int weights_height     = weights.shape().y();
     const int weights_upper_dims = weights.shape().total_size() / (weights_width * weights_height);
     // Find the upsampled dimensions
     unsigned int out_x = (src.shape().x() - 1) * stride_x + 1;
     unsigned int out_y = (src.shape().y() - 1) * stride_y + 1;
     // Find the padding needed for the convolution with stride 1 in order to match output shape
     unsigned int padx = output_shape.x() - (out_x - weights_width + 1);
     unsigned int pady = output_shape.y() - (out_y - weights_height + 1);
     out_x += padx;
     out_y += pady;
     TensorShape scaled_shape = src.shape();
     scaled_shape.set(0, out_x);
     scaled_shape.set(1, out_y);
     SimpleTensor<T> scaled{ scaled_shape, src.data_type(), 1, src.quantization_info() };
     const int width_in      = src.shape().x();
     const int height_in     = src.shape().y();
     const int width_scaled  = scaled.shape().x();
     const int height_scaled = scaled.shape().y();
     const int num_2d_slices = src.shape().total_size() / (width_in * height_in);
     ARM_COMPUTE_ERROR_ON(info.pad().first > (weights.shape().x() - 1));
     if(src.data_type() == DataType::QASYMM8)
     {
         const uint8_t quantized_zero = src.quantization_info().uniform().offset;
         std::fill_n(scaled.data(), scaled.num_elements(), quantized_zero);
     }
     else
     {
         std::fill_n(scaled.data(), scaled.num_elements(), T(0));
     }
     // Flip weights by 180 degrees
     SimpleTensor<T> weights_flipped{ weights.shape(), weights.data_type(), 1, weights.quantization_info() };
     for(int ud = 0; ud < weights_upper_dims; ++ud)
     {
         const int offset = ud * weights_width * weights_height;
         for(int y = 0; y < weights_height; ++y)
         {
             for(int x = 0; x < weights_width; ++x)
             {
                 weights_flipped[offset + (weights_height - 1 - y) * weights_width + (weights_width - 1 - x)] = weights[offset + y * weights_width + x];
             }
         }
     }
     for(int slice = 0; slice < num_2d_slices; ++slice)
     {
         const int offset_slice_in  = slice * width_in * height_in;
         const int offset_slice_out = slice * width_scaled * height_scaled;
         const int start_x          = padx / 2;
         const int start_y          = pady / 2;
         const int end_y            = height_scaled - pady / 2;
         const int end_x            = width_scaled - padx / 2;
         for(int yi = start_y, in_y = 0; yi < end_y; yi += stride_y, in_y++)
         {
             for(int xi = start_x, in_x = 0; xi < end_x; xi += stride_x, in_x++)
             {
                 const T *in  = src.data() + offset_slice_in + in_y * width_in + in_x;
                 T       *out = scaled.data() + offset_slice_out + xi + yi * width_scaled;
                 *out         = *in;
             }
         }
     }
     const PadStrideInfo conv_info(1, 1, 0, 0, 0, 0, DimensionRoundingType::CEIL);
     return convolution_layer(scaled, weights_flipped, bias, output_shape, conv_info);
 }
References ARM_COMPUTE_ERROR_ON, arm_compute::test::validation::bias, arm_compute::CEIL, arm_compute::test::validation::conv_info, convolution_layer(), arm_compute::test::validation::info, offset(), arm_compute::test::validation::output_shape, arm_compute::QASYMM8, TensorShape::set(), slice(), arm_compute::test::validation::src, and arm_compute::test::validation::weights.
deconvolution_layer() [2/4]
template SimpleTensor<uint8_t> arm_compute::test::validation::reference::deconvolution_layer (const SimpleTensor< uint8_t > & src, const SimpleTensor< uint8_t > & weights, const SimpleTensor< int32_t > & bias, const TensorShape & output_shape, const PadStrideInfo & info)
deconvolution_layer() [3/4]
template SimpleTensor<float> arm_compute::test::validation::reference::deconvolution_layer (const SimpleTensor< float > & src, const SimpleTensor< float > & weights, const SimpleTensor< float > & bias, const TensorShape & output_shape, const PadStrideInfo & info)
deconvolution_layer() [4/4]
template SimpleTensor<half> arm_compute::test::validation::reference::deconvolution_layer (const SimpleTensor< half > & src, const SimpleTensor< half > & weights, const SimpleTensor< half > & bias, const TensorShape & output_shape, const PadStrideInfo & info)
depth_convert() [1/9]
SimpleTensor< T2 > depth_convert (const SimpleTensor< T1 > & src, DataType dt_out, ConvertPolicy policy, uint32_t shift)
Definition at line 42 of file DepthConvertLayer.cpp.
 {
     SimpleTensor<T2> result(src.shape(), dt_out);
     // Up-casting
     if(element_size_from_data_type(src.data_type()) < element_size_from_data_type(dt_out))
     {
         for(int i = 0; i < src.num_elements(); ++i)
         {
             result[i] = src[i] << shift;
         }
     }
     // Down-casting
     else
     {
         for(int i = 0; i < src.num_elements(); ++i)
         {
             T1 val    = src[i] >> shift;
             result[i] = (policy == ConvertPolicy::SATURATE) ? utils::cast::saturate_cast<T2>(val) : static_cast<T2>(val);
         }
     }
     return result;
 }
References arm_compute::element_size_from_data_type(), arm_compute::test::validation::policy, arm_compute::SATURATE, arm_compute::test::validation::shift, and arm_compute::test::validation::src.
depth_convert() [2/9]
template SimpleTensor< float > depth_convert (const SimpleTensor< uint8_t > & src, DataType dt_out, ConvertPolicy policy, uint32_t shift)
depth_convert() [3/9]
template SimpleTensor< float > depth_convert (const SimpleTensor< int8_t > & src, DataType dt_out, ConvertPolicy policy, uint32_t shift)
depth_convert() [4/9]
template SimpleTensor< float > depth_convert (const SimpleTensor< uint16_t > & src, DataType dt_out, ConvertPolicy policy, uint32_t shift)
depth_convert() [5/9]
template SimpleTensor< float > depth_convert (const SimpleTensor< int16_t > & src, DataType dt_out, ConvertPolicy policy, uint32_t shift)
depth_convert() [6/9]
template SimpleTensor< float > depth_convert (const SimpleTensor< uint32_t > & src, DataType dt_out, ConvertPolicy policy, uint32_t shift)
depth_convert() [7/9]
template SimpleTensor< float > depth_convert (const SimpleTensor< int32_t > & src, DataType dt_out, ConvertPolicy policy, uint32_t shift)
depth_convert() [8/9]
template SimpleTensor< float > depth_convert (const SimpleTensor< half > & src, DataType dt_out, ConvertPolicy policy, uint32_t shift)
depth_convert() [9/9]
template SimpleTensor< half > depth_convert (const SimpleTensor< float > & src, DataType dt_out, ConvertPolicy policy, uint32_t shift)
depth_to_space() [1/3]
SimpleTensor< T > depth_to_space (const SimpleTensor< T > & src, const TensorShape & dst_shape, int32_t block_shape)
Definition at line 38 of file DepthToSpaceLayer.cpp.
 {
     ARM_COMPUTE_ERROR_ON(block_shape <= 0);
     SimpleTensor<T> result(dst_shape, src.data_type());
     int        in_pos     = 0;
     const auto width_in   = static_cast<int>(src.shape()[0]);
     const auto height_in  = static_cast<int>(src.shape()[1]);
     const auto channel_in = static_cast<int>(src.shape()[2]);
     const auto batch_in   = static_cast<int>(src.shape()[3]);
     const int  r          = channel_in / (block_shape * block_shape);
     for(int b = 0; b < batch_in; ++b)
     {
         for(int z = 0; z < channel_in; ++z)
         {
             for(int y = 0; y < height_in; ++y)
             {
                 for(int x = 0; x < width_in; ++x)
                 {
                     const int out_x   = (block_shape * x + (z / r) % block_shape);
                     const int out_y   = (block_shape * y + (z / r) / block_shape);
                     const int out_pos = out_x + dst_shape[0] * out_y + (z % r) * dst_shape[0] * dst_shape[1] + b * dst_shape[0] * dst_shape[1] * dst_shape[2];
                     result[out_pos]   = src[in_pos];
                     ++in_pos;
                 }
             }
         }
     }
     return result;
 }
References ARM_COMPUTE_ERROR_ON, arm_compute::test::validation::b, arm_compute::test::validation::dst_shape, and arm_compute::test::validation::src.
depth_to_space() [2/3]
template SimpleTensor<float> arm_compute::test::validation::reference::depth_to_space (const SimpleTensor< float > & src, const TensorShape & dst_shape, int32_t block_shape)
depth_to_space() [3/3]
template SimpleTensor<half> arm_compute::test::validation::reference::depth_to_space (const SimpleTensor< half > & src, const TensorShape & dst_shape, int32_t block_shape)
depthconcatenate_layer() [1/4]
SimpleTensor< T > depthconcatenate_layer (const std::vector< SimpleTensor< T >> & srcs, SimpleTensor< T > & dst)
Definition at line 37 of file DepthConcatenateLayer.cpp.
 {
     // Create reference
     std::vector<TensorShape> shapes;
     shapes.reserve(srcs.size());
     for(const auto &src : srcs)
     {
         shapes.emplace_back(src.shape());
     }
     // Compute reference
     int       depth_offset                = 0;
     const int width_out                   = dst.shape().x();
     const int height_out                  = dst.shape().y();
     const int depth_out                   = dst.shape().z();
     const int out_stride_z                = width_out * height_out;
     const int batches                     = dst.shape().total_size_upper(3);
     auto have_different_quantization_info = [&](const SimpleTensor<T> &tensor)
     {
         return tensor.quantization_info() != dst.quantization_info();
     };
     if(srcs[0].data_type() == DataType::QASYMM8 && std::any_of(srcs.cbegin(), srcs.cend(), have_different_quantization_info))
     {
         for(int b = 0; b < batches; ++b)
         {
             // input tensors can have smaller width and height than the output, so for each output's slice we need to requantize 0 (as this is the value
             // used in NEFillBorderKernel by NEDepthConcatenateLayer) using the corresponding quantization info for that particular slice/input tensor.
             int slice = 0;
             for(const auto &src : srcs)
             {
                 auto                          ptr_slice = static_cast<T *>(dst(Coordinates(0, 0, slice, b)));
                 const auto                    num_elems_in_slice((dst.num_elements() / depth_out) * src.shape().z());
                 const UniformQuantizationInfo iq_info = src.quantization_info().uniform();
                 const UniformQuantizationInfo oq_info = dst.quantization_info().uniform();
                 std::transform(ptr_slice, ptr_slice + num_elems_in_slice, ptr_slice, [&](T)
                 {
                     return quantize_qasymm8(dequantize_qasymm8(0, iq_info), oq_info);
                 });
                 slice += src.shape().z();
             }
         }
     }
     else
     {
         std::fill_n(dst.data(), dst.num_elements(), 0);
     }
     for(const auto &src : srcs)
     {
         ARM_COMPUTE_ERROR_ON(depth_offset >= depth_out);
         ARM_COMPUTE_ERROR_ON(batches != static_cast<int>(src.shape().total_size_upper(3)));
         const int width  = src.shape().x();
         const int height = src.shape().y();
         const int depth  = src.shape().z();
         const int x_diff = (width_out - width) / 2;
         const int y_diff = (height_out - height) / 2;
         const T *src_ptr = src.data();
         for(int b = 0; b < batches; ++b)
         {
             const size_t offset_to_first_element = b * out_stride_z * depth_out + depth_offset * out_stride_z + y_diff * width_out + x_diff;
             for(int d = 0; d < depth; ++d)
             {
                 for(int r = 0; r < height; ++r)
                 {
                     if(src.data_type() == DataType::QASYMM8 && src.quantization_info() != dst.quantization_info())
                     {
                         const UniformQuantizationInfo iq_info = src.quantization_info().uniform();
                         const UniformQuantizationInfo oq_info = dst.quantization_info().uniform();
                         std::transform(src_ptr, src_ptr + width, dst.data() + offset_to_first_element + d * out_stride_z + r * width_out, [&](T t)
{
                             const float dequantized_input = dequantize_qasymm8(t, iq_info);
                             return quantize_qasymm8(dequantized_input, oq_info);
                         });
                         src_ptr += width;
                     }
                     else
                     {
                         std::copy(src_ptr, src_ptr + width, dst.data() + offset_to_first_element + d * out_stride_z + r * width_out);
                         src_ptr += width;
                     }
                 }
             }
         }
         depth_offset += depth;
     }
     return dst;
 }
References ARM_COMPUTE_ERROR_ON, arm_compute::test::validation::b, copy(), arm_compute::test::validation::data_type, arm_compute::dequantize_qasymm8(), arm_compute::test::validation::dst, out_stride_z, arm_compute::QASYMM8, arm_compute::quantize_qasymm8(), slice(), and arm_compute::test::validation::src.
depthconcatenate_layer() [2/4]
template SimpleTensor<uint8_t> arm_compute::test::validation::reference::depthconcatenate_layer (const std::vector< SimpleTensor< uint8_t >> & srcs, SimpleTensor< uint8_t > & dst)
depthconcatenate_layer() [3/4]
template SimpleTensor<float> arm_compute::test::validation::reference::depthconcatenate_layer (const std::vector< SimpleTensor< float >> & srcs, SimpleTensor< float > & dst)
depthconcatenate_layer() [4/4]
template SimpleTensor<half> arm_compute::test::validation::reference::depthconcatenate_layer (const std::vector< SimpleTensor< half >> & srcs, SimpleTensor< half > & dst)
depthwise_convolution() [1/4]
SimpleTensor< T > depthwise_convolution (const SimpleTensor< T > & src, const SimpleTensor< T > & weights, const SimpleTensor< TB > & biases, const TensorShape & dst_shape, const PadStrideInfo & conv_info, unsigned int depth_multiplier, const Size2D & dilation, const QuantizationInfo & out_quant_info)
Perform a depthwise convolution.
Three dimensions tensors
Third dimention is number of channels
Depths of input tensor and filter are equals
Padding, stride and output shape "match"
Definition at line 52 of file DepthwiseConvolutionLayer.cpp.
 {
     ARM_COMPUTE_UNUSED(out_quant_info);
     SimpleTensor<T> dst{ dst_shape, src.data_type(), 1 };
     // Compute reference
     const int filter_width  = weights.shape().x();
     const int filter_height = weights.shape().y();
     const int filter_plane  = filter_width * filter_height;
     const int input_width   = src.shape().x();
     const int input_height  = src.shape().y();
     const int input_depth   = src.shape().z();
     const int num_batches   = src.shape().total_size() / (input_width * input_height * input_depth);
     const int pad_left   = conv_info.pad_left();
     const int pad_top    = conv_info.pad_top();
     const int pad_right  = conv_info.pad_right();
     const int pad_bottom = conv_info.pad_bottom();
     const float patch_width  = (filter_width + (dilation.x() - 1) * (filter_width - 1));
     const float patch_height = (filter_height + (dilation.y() - 1) * (filter_height - 1));
     const int patch_half_width_floor  = patch_width / 2;
     const int patch_half_height_floor = patch_height / 2;
     const auto patch_half_width_ceil  = static_cast<int>(std::ceil(patch_width / 2));
     const auto patch_half_height_ceil = static_cast<int>(std::ceil(patch_height / 2));
     const int minimum_x = -pad_left + patch_half_width_floor;
     const int minimum_y = -pad_top + patch_half_height_floor;
     const int maximum_x = input_width + pad_left + pad_right - static_cast<int>(patch_width);
     const int maximum_y = input_height + pad_top + pad_bottom - static_cast<int>(patch_height);
     const T border_value(0);
     int out_pos = 0;
     for(int r = 0; r < num_batches; ++r)
     {
         for(int z = 0; z < input_depth; ++z)
         {
             for(unsigned int m = 0; m < depth_multiplier; ++m)
             {
                 const int out_z = z * depth_multiplier + m;
                 for(int y = minimum_y; y <= minimum_y + maximum_y; y += conv_info.stride().second)
                 {
                     for(int x = minimum_x; x <= minimum_x + maximum_x; x += conv_info.stride().first)
                     {
                         Coordinates coords(static_cast<int>(x), static_cast<int>(y), static_cast<int>(z), static_cast<int>(r));
                         size_t      filter_offset = filter_plane * out_z;
                         T val(0);
                         for(int j = y - patch_half_height_floor; j < y + patch_half_height_ceil; j += dilation.y())
{
                             for(int i = x - patch_half_width_floor; i < x + patch_half_width_ceil; i += dilation.x())
{
                                 coords.set(0, i);
                                 coords.set(1, j);
                                 val += *(weights.data() + filter_offset) * tensor_elem_at(src, coords, BorderMode::CONSTANT, border_value);
                                 ++filter_offset;
                             }
                         }
                         dst[out_pos++] = saturate_cast<T>(val + *static_cast<const TB *>(biases(Coordinates(out_z))));
                     }
                 }
             }
         }
     }
     return dst;
 }
References ARM_COMPUTE_UNUSED, arm_compute::CONSTANT, arm_compute::test::validation::conv_info, arm_compute::test::validation::dilation, arm_compute::test::validation::dst, arm_compute::test::validation::dst_shape, arm_compute::test::validation::filter_height, arm_compute::test::validation::filter_width, Dimensions< T >::set(), arm_compute::test::validation::src, arm_compute::test::validation::tensor_elem_at(), and arm_compute::test::validation::weights.
Referenced by depthwise_separable_convolution_layer().
depthwise_convolution() [2/4]
SimpleTensor<uint8_t> arm_compute::test::validation::reference::depthwise_convolution (const SimpleTensor< uint8_t > & src, const SimpleTensor< uint8_t > & weights, const SimpleTensor< int32_t > & biases, const TensorShape & dst_shape, const PadStrideInfo & conv_info, unsigned int depth_multiplier, const Size2D & dilation, const QuantizationInfo & out_quant_info)
Definition at line 128 of file DepthwiseConvolutionLayer.cpp.
 {
     // if no explicit quantization has been set you the same as src
     const QuantizationInfo &dst_qinfo = out_quant_info.uniform().empty() ? src.quantization_info() : out_quant_info;
     SimpleTensor<uint8_t>   dst{ dst_shape, src.data_type(), 1, dst_qinfo };
     // Create reference
     const int   input_offset   = -src.quantization_info().uniform().offset;
     const float input_scale    = src.quantization_info().uniform().scale;
     const int   weights_offset = -weights.quantization_info().uniform().offset;
     const float weights_scale  = weights.quantization_info().uniform().scale;
     const int   output_offset  = dst_qinfo.uniform().offset;
     const float output_scale   = dst_qinfo.uniform().scale;
     int         output_multiplier = 0;
     int         output_shift      = 0;
     const float multiplier        = input_scale * weights_scale / output_scale;
     arm_compute::quantization::calculate_quantized_multiplier_less_than_one(multiplier, &output_multiplier, &output_shift);
     // Compute reference
     const int filter_width  = weights.shape().x();
     const int filter_height = weights.shape().y();
     const int filter_plane  = filter_width * filter_height;
     const int input_width   = src.shape().x();
     const int input_height  = src.shape().y();
     const int input_depth   = src.shape().z();
     const int num_batches   = src.shape().total_size() / (input_width * input_height * input_depth);
     const int pad_left   = conv_info.pad_left();
     const int pad_top    = conv_info.pad_top();
     const int pad_right  = conv_info.pad_right();
     const int pad_bottom = conv_info.pad_bottom();
     const float patch_width  = (filter_width + (dilation.x() - 1) * (filter_width - 1));
     const float patch_height = (filter_height + (dilation.y() - 1) * (filter_height - 1));
     const int patch_half_width_floor  = patch_width / 2;
     const int patch_half_height_floor = patch_height / 2;
     const auto patch_half_width_ceil  = static_cast<int>(std::ceil(patch_width / 2));
     const auto patch_half_height_ceil = static_cast<int>(std::ceil(patch_height / 2));
     const int minimum_x = -pad_left + patch_half_width_floor;
     const int minimum_y = -pad_top + patch_half_height_floor;
     const int maximum_x = input_width + pad_left + pad_right - static_cast<int>(patch_width);
     const int maximum_y = input_height + pad_top + pad_bottom - static_cast<int>(patch_height);
     int out_pos = 0;
     for(int r = 0; r < num_batches; ++r)
     {
         for(int z = 0; z < input_depth; ++z)
         {
             for(unsigned int m = 0; m < depth_multiplier; ++m)
             {
                 const int     out_z    = z * depth_multiplier + m;
                 const int32_t bias_val = *static_cast<const int32_t *>(biases(Coordinates(out_z)));
                 for(int y = minimum_y; y <= minimum_y + maximum_y; y += conv_info.stride().second)
                 {
                     for(int x = minimum_x; x <= minimum_x + maximum_x; x += conv_info.stride().first)
                     {
                         Coordinates coords(x, y, z, r);
                         int         filter_offset = filter_plane * out_z;
                         int32_t val = 0;
                         for(int j = y - patch_half_height_floor; j < y + patch_half_height_ceil; j += dilation.y())
{
                             for(int i = x - patch_half_width_floor; i < x + patch_half_width_ceil; i += dilation.x())
{
                                 coords.set(0, i);
                                 coords.set(1, j);
                                 const auto    in_val = tensor_elem_at<uint8_t>(src, coords, BorderMode::CONSTANT, -input_offset);
                                 const uint8_t w_val  = *(weights.data() + filter_offset);
                                 val += (in_val + input_offset) * (w_val + weights_offset);
                                 ++filter_offset;
                             }
                         }
                         val += bias_val;
                         val = asymm_rounding_divide_by_pow2(asymm_int_mult(val, output_multiplier), output_shift);
                         val += output_offset;
                         val = std::max<int32_t>(val, 0);
                         val = std::min<int32_t>(val, 255);
                         // Store the result
                         dst[out_pos++] = val;
                     }
                 }
             }
         }
     }
     return dst;
 }
References arm_compute::test::validation::asymm_int_mult(), arm_compute::test::validation::asymm_rounding_divide_by_pow2(), arm_compute::quantization::calculate_quantized_multiplier_less_than_one(), arm_compute::CONSTANT, arm_compute::test::validation::conv_info, arm_compute::test::validation::dilation, arm_compute::test::validation::dst, arm_compute::test::validation::dst_shape, UniformQuantizationInfo::empty(), arm_compute::test::validation::filter_height, arm_compute::test::validation::filter_width, UniformQuantizationInfo::offset, UniformQuantizationInfo::scale, Dimensions< T >::set(), arm_compute::test::validation::src, QuantizationInfo::uniform(), and arm_compute::test::validation::weights.
depthwise_convolution() [3/4]
template SimpleTensor<float> arm_compute::test::validation::reference::depthwise_convolution (const SimpleTensor< float > & src, const SimpleTensor< float > & weights, const SimpleTensor< float > & biases, const TensorShape & dst_shape, const PadStrideInfo & conv_info, unsigned int depth_multiplier, const Size2D & dilation, const QuantizationInfo & out_quant_info)
depthwise_convolution() [4/4]
template SimpleTensor<half> arm_compute::test::validation::reference::depthwise_convolution (const SimpleTensor< half > & src, const SimpleTensor< half > & weights, const SimpleTensor< half > & biases, const TensorShape & dst_shape, const PadStrideInfo & conv_info, unsigned int depth_multiplier, const Size2D & dilation, const QuantizationInfo & out_quant_info)
depthwise_separable_convolution_layer() [1/2]
SimpleTensor< T > depthwise_separable_convolution_layer (const SimpleTensor< T > & src, const SimpleTensor< T > & depthwise_weights, const SimpleTensor< T > & depthwise_biases, const TensorShape & depthwise_out_shape, const SimpleTensor< T > & pointwise_weights, const SimpleTensor< T > & pointwise_biases, const TensorShape & dst_shape, const PadStrideInfo & depthwise_conv_info, const PadStrideInfo & pointwise_conv_info)
Definition at line 43 of file DepthwiseSeparableConvolutionLayer.cpp.
 {
     // Compute reference
     SimpleTensor<T> depthwise_out = depthwise_convolution(src, depthwise_weights, depthwise_biases, depthwise_out_shape, depthwise_conv_info, 1);
     SimpleTensor<T> dst           = convolution_layer(depthwise_out, pointwise_weights, pointwise_biases, dst_shape, pointwise_conv_info);
     return dst;
 }
References convolution_layer(), depthwise_convolution(), arm_compute::test::validation::dst, arm_compute::test::validation::dst_shape, and arm_compute::test::validation::src.
depthwise_separable_convolution_layer() [2/2]
template SimpleTensor<float> arm_compute::test::validation::reference::depthwise_separable_convolution_layer (const SimpleTensor< float > & in, const SimpleTensor< float > & depthwise_weights, const SimpleTensor< float > & depthwise_biases, const TensorShape & depthwise_out_shape, const SimpleTensor< float > & pointwise_weights, const SimpleTensor< float > & pointwise_biases, const TensorShape & dst_shape, const PadStrideInfo & depthwise_conv_info, const PadStrideInfo & pointwise_conv_info)
dequantization_layer() [1/4]
SimpleTensor< TOut > dequantization_layer (const SimpleTensor< TIn > & src)
Definition at line 100 of file DequantizationLayer.cpp.
 {
     if(src.data_layout() == DataLayout::NHWC && src.data_type() == DataType::QSYMM8_PER_CHANNEL)
     {
         SimpleTensor<TIn> src_nchw = reference::permute<TIn>(src, PermutationVector(1U, 2U, 0U));
         return reference::permute<TOut>(dequantization_layer_nchw<TOut>(src_nchw), PermutationVector(2U, 0U, 1U));
     }
     else
     {
         return dequantization_layer_nchw<TOut>(src);
     }
 }
References arm_compute::NHWC, arm_compute::QSYMM8_PER_CHANNEL, and arm_compute::test::validation::src.
dequantization_layer() [2/4]
template SimpleTensor< float > dequantization_layer (const SimpleTensor< uint8_t > & src)
dequantization_layer() [3/4]
template SimpleTensor< float > dequantization_layer (const SimpleTensor< int8_t > & src)
dequantization_layer() [4/4]
template SimpleTensor< float > dequantization_layer (const SimpleTensor< int16_t > & src)
derivative() [1/2]
std::pair< SimpleTensor< T >, SimpleTensor< T > > derivative (const SimpleTensor< U > & src, BorderMode border_mode, uint8_t constant_border_value, GradientDimension gradient_dimension)
Definition at line 55 of file Derivative.cpp.
 {
     const unsigned int filter_size = 3;
     SimpleTensor<T> dst_x(src.shape(), data_type<T>::value, src.num_channels());
     SimpleTensor<T> dst_y(src.shape(), data_type<T>::value, src.num_channels());
     ValidRegion valid_region = shape_to_valid_region(src.shape(), border_mode == BorderMode::UNDEFINED, BorderSize(filter_size / 2));
     for(int i = 0; i < src.num_elements(); ++i)
     {
         Coordinates coord = index2coord(src.shape(), i);
         if(!is_in_valid_region(valid_region, coord))
         {
             continue;
         }
         switch(gradient_dimension)
         {
             case GradientDimension::GRAD_X:
                 apply_2d_spatial_filter(coord, src, dst_x, TensorShape{ filter_size, filter_size }, derivative_3_x.data(), 1.f, border_mode,
                                         constant_border_value);
                 break;
             case GradientDimension::GRAD_Y:
                 apply_2d_spatial_filter(coord, src, dst_y, TensorShape{ filter_size, filter_size }, derivative_3_y.data(), 1.f, border_mode,
                                         constant_border_value);
                 break;
             case GradientDimension::GRAD_XY:
                 apply_2d_spatial_filter(coord, src, dst_x, TensorShape{ filter_size, filter_size }, derivative_3_x.data(), 1.f, border_mode,
                                         constant_border_value);
                 apply_2d_spatial_filter(coord, src, dst_y, TensorShape{ filter_size, filter_size }, derivative_3_y.data(), 1.f, border_mode,
                                         constant_border_value);
                 break;
             default:
                 ARM_COMPUTE_ERROR("Gradient dimension not supported");
         }
     }
     return std::make_pair(dst_x, dst_y);
 }
References arm_compute::test::validation::filter_size, and arm_compute::test::validation::src.
derivative() [2/2]
template std::pair<SimpleTensor<int16_t>, SimpleTensor<int16_t> > arm_compute::test::validation::reference::derivative (const SimpleTensor< uint8_t > & src, BorderMode border_mode, uint8_t constant_border_value, GradientDimension gradient_dimension)
detection_windows_non_maxima_suppression()
void arm_compute::test::validation::reference::detection_windows_non_maxima_suppression (std::vector< DetectionWindow > & multi_windows, float min_distance)
Definition at line 60 of file HOGMultiDetection.cpp.
 {
     const size_t num_candidates = multi_windows.size();
     size_t       num_detections = 0;
     // Sort by idx_class first and by score second
     std::sort(multi_windows.begin(), multi_windows.end(), [](const DetectionWindow & lhs, const DetectionWindow & rhs)
     {
         if(lhs.idx_class < rhs.idx_class)
         {
             return true;
         }
         if(rhs.idx_class < lhs.idx_class)
         {
             return false;
         }
         // idx_classes are equal so compare by score
         if(lhs.score > rhs.score)
         {
             return true;
         }
         if(rhs.score > lhs.score)
         {
             return false;
         }
         return false;
     });
     const float min_distance_pow2 = min_distance * min_distance;
     // Euclidean distance
     for(size_t i = 0; i < num_candidates; ++i)
     {
         if(0.0f != multi_windows.at(i).score)
         {
             DetectionWindow cur;
             cur.x         = multi_windows.at(i).x;
             cur.y         = multi_windows.at(i).y;
             cur.width     = multi_windows.at(i).width;
             cur.height    = multi_windows.at(i).height;
             cur.idx_class = multi_windows.at(i).idx_class;
             cur.score     = multi_windows.at(i).score;
             // Store window
             multi_windows.at(num_detections) = cur;
             ++num_detections;
             const float xc = cur.x + cur.width * 0.5f;
             const float yc = cur.y + cur.height * 0.5f;
             for(size_t k = i + 1; k < (num_candidates) && (cur.idx_class == multi_windows.at(k).idx_class); ++k)
             {
                 const float xn = multi_windows.at(k).x + multi_windows.at(k).width * 0.5f;
                 const float yn = multi_windows.at(k).y + multi_windows.at(k).height * 0.5f;
                 const float dx = std::fabs(xn - xc);
                 const float dy = std::fabs(yn - yc);
                 if(dx < min_distance && dy < min_distance)
                 {
                     const float d = dx * dx + dy * dy;
                     if(d < min_distance_pow2)
                     {
                         // Invalidate detection window
                         multi_windows.at(k).score = 0.0f;
                     }
                 }
             }
         }
     }
     multi_windows.resize(num_detections);
 }
References DetectionWindow::height, DetectionWindow::idx_class, DetectionWindow::score, DetectionWindow::width, DetectionWindow::x, and DetectionWindow::y.
Referenced by hog_multi_detection().
dft_1d() [1/2]
SimpleTensor< T > dft_1d (const SimpleTensor< T > & src, FFTDirection direction)
Performs an one dimensional DFT on a complex input.
Parameters
[in] src Source tensor.
[in] direction Direction of the DFT.
Returns
Complex output of same length as input.
Definition at line 308 of file DFT.cpp.
 {
     auto dst = dft_1d_core(src, direction);
     if(direction == FFTDirection::Inverse)
     {
         const T scaling_factor = dst.shape()[0];
         scale(dst, scaling_factor);
     }
     return dst;
 }
References arm_compute::test::validation::dst, Inverse, scale(), and arm_compute::test::validation::src.
Referenced by arm_compute::test::validation::DATA_TEST_CASE().
dft_1d() [2/2]
template SimpleTensor<float> arm_compute::test::validation::reference::dft_1d (const SimpleTensor< float > & src, FFTDirection direction)
dft_2d() [1/2]
SimpleTensor< T > dft_2d (const SimpleTensor< T > & src, FFTDirection direction)
Performs a two dimensional DFT on a complex input.
Parameters
[in] src Source tensor.
[in] direction Direction of the DFT.
Returns
Complex output of same length as input.
Definition at line 348 of file DFT.cpp.
 {
     ARM_COMPUTE_ERROR_ON(src.num_channels() != 2);
     if(direction == FFTDirection::Forward)
     {
         auto first_pass  = dft_1d_core(src, direction);
         auto transposed  = permute(first_pass, PermutationVector(1U, 0U));
         auto second_pass = dft_1d_core(transposed, direction);
         return permute(second_pass, PermutationVector(1U, 0U));
     }
     else
     {
         auto transposed   = permute(src, PermutationVector(1U, 0U));
         auto first_pass   = dft_1d_core(transposed, direction);
         auto transposed_2 = permute(first_pass, PermutationVector(1U, 0U));
         auto dst          = dft_1d_core(transposed_2, direction);
         const T scaling_factor = dst.shape()[0] * dst.shape()[1];
         scale(dst, scaling_factor);
         return dst;
     }
 }
References ARM_COMPUTE_ERROR_ON, arm_compute::test::validation::dst, Forward, permute(), scale(), and arm_compute::test::validation::src.
Referenced by arm_compute::test::validation::DATA_TEST_CASE().
dft_2d() [2/2]
template SimpleTensor<float> arm_compute::test::validation::reference::dft_2d (const SimpleTensor< float > & src, FFTDirection direction)
dilate() [1/2]
SimpleTensor< T > dilate (const SimpleTensor< T > & src, BorderMode border_mode, T constant_border_value)
Definition at line 41 of file Dilate.cpp.
 {
     /*
              -1   x  +1
          -1 [tl][tc][tr] -1
           y [ml][xy][mr]  y
          +1 [bl][bc][br] +1
              -1   x  +1
         dilate:
         dst(x, y) = max[ src(x', y') for x-1<=x'<=x+1, y-1<=y'<=y+1 ] = max({tl, tc, tr, ml, xy, mr, bl, bc, br})
     */
     SimpleTensor<T> dst(src.shape(), src.data_type());
     for(int i = 0; i < src.num_elements(); ++i)
     {
         Coordinates coord = index2coord(src.shape(), i);
         const int   x     = coord.x();
         const int   y     = coord.y();
         std::array<T, 9> neighbours = { { 0 } };
         for(int row = y - 1, j = 0; row <= y + 1; ++row)
         {
             for(int col = x - 1; col <= x + 1; ++col, ++j)
             {
                 coord.set(0, col);
                 coord.set(1, row);
                 neighbours[j] = tensor_elem_at(src, coord, border_mode, constant_border_value);
             }
         }
         dst[i] = *std::max_element(neighbours.cbegin(), neighbours.cend());
     }
     return dst;
 }
References arm_compute::test::validation::border_mode, arm_compute::test::validation::dst, arm_compute::test::index2coord(), Dimensions< T >::set(), arm_compute::test::validation::src, arm_compute::test::validation::tensor_elem_at(), Dimensions< T >::x(), and Dimensions< T >::y().
dilate() [2/2]
template SimpleTensor<uint8_t> arm_compute::test::validation::reference::dilate (const SimpleTensor< uint8_t > & src, BorderMode border_mode, uint8_t constant_border_value)
elementwise_unary() [1/4]
SimpleTensor< T > elementwise_unary (const SimpleTensor< T > & src, ElementWiseUnary op)
Definition at line 35 of file ElementWiseUnary.cpp.
 {
     SimpleTensor<T> dst(src.shape(), src.data_type());
     for(int i = 0; i < src.num_elements(); ++i)
     {
         switch(op)
         {
             case ElementWiseUnary::RSQRT:
                 dst[i] = 1.f / std::sqrt(src[i]);
                 break;
             case ElementWiseUnary::EXP:
                 dst[i] = std::exp(src[i]);
                 break;
             case ElementWiseUnary::NEG:
                 dst[i] = -src[i];
                 break;
             case ElementWiseUnary::LOG:
                 dst[i] = std::log(src[i]);
                 break;
             case ElementWiseUnary::ABS:
                 dst[i] = std::abs(src[i]);
                 break;
             case ElementWiseUnary::SIN:
                 dst[i] = std::sin(src[i]);
                 break;
             case ElementWiseUnary::ROUND:
                 dst[i] = std::nearbyint(src[i]);
                 break;
             default:
                 ARM_COMPUTE_ERROR("Not implemented");
         }
     }
     return dst;
 }
References arm_compute::ABS, ARM_COMPUTE_ERROR, arm_compute::test::validation::dst, arm_compute::EXP, arm_compute::LOG, arm_compute::support::cpp11::nearbyint(), arm_compute::NEG, arm_compute::ROUND, arm_compute::RSQRT, arm_compute::SIN, and arm_compute::test::validation::src.
elementwise_unary() [2/4]
template SimpleTensor<float> arm_compute::test::validation::reference::elementwise_unary (const SimpleTensor< float > & src, ElementWiseUnary op)
elementwise_unary() [3/4]
template SimpleTensor<half> arm_compute::test::validation::reference::elementwise_unary (const SimpleTensor< half > & src, ElementWiseUnary op)
elementwise_unary() [4/4]
template SimpleTensor<int32_t> arm_compute::test::validation::reference::elementwise_unary (const SimpleTensor< int32_t > & src, ElementWiseUnary op)
equalize_histogram() [1/2]
SimpleTensor< T > equalize_histogram (const SimpleTensor< T > & src)
Definition at line 35 of file EqualizeHistogram.cpp.
 {
     const size_t num_bins = 256; // 0-255 inclusive
     std::vector<T>        lut(num_bins);
     std::vector<uint32_t> hist(num_bins);
     std::vector<uint32_t> cd(num_bins); // cumulative distribution
     SimpleTensor<T> dst(src.shape(), src.data_type());
     // Create the histogram
     for(int element_idx = 0; element_idx < src.num_elements(); ++element_idx)
     {
         hist[src[element_idx]]++;
     }
     // Calculate cumulative distribution
     std::partial_sum(hist.begin(), hist.end(), cd.begin());
     // Get the number of pixels that have the lowest non-zero value
     const uint32_t cd_min = *std::find_if(hist.begin(), hist.end(), [](const uint32_t &x)
     {
         return x > 0;
     });
     const size_t total_num_pixels = cd.back();
     // Single color - create linear distribution
     if(total_num_pixels == cd_min)
     {
         std::iota(lut.begin(), lut.end(), 0);
     }
     else
     {
         const float diff = total_num_pixels - cd_min;
         for(size_t i = 0; i < num_bins; ++i)
         {
             lut[i] = lround((cd[i] - cd_min) / diff * 255.f);
         }
     }
     // Fill output tensor with equalized values
     for(int i = 0; i < src.num_elements(); ++i)
     {
         dst[i] = lut[src[i]];
     }
     return dst;
 }
References arm_compute::test::validation::dst, and arm_compute::test::validation::src.
equalize_histogram() [2/2]
template SimpleTensor<uint8_t> arm_compute::test::validation::reference::equalize_histogram (const SimpleTensor< uint8_t > & src)
Referenced by arm_compute::test::validation::DATA_TEST_CASE().
erode() [1/2]
SimpleTensor< T > erode (const SimpleTensor< T > & src, BorderMode border_mode, T constant_border_value)
Definition at line 41 of file Erode.cpp.
 {
     /*
              -1   x  +1
          -1 [tl][tc][tr] -1
           y [ml][xy][mr]  y
          +1 [bl][bc][br] +1
              -1   x  +1
         erode:
         dst(x, y) = min[ src(x', y') for x-1<=x'<=x+1, y-1<=y'<=y+1 ] = min({tl, tc, tr, ml, xy, mr, bl, bc, br})
     */
     SimpleTensor<T> dst(src.shape(), src.data_type());
     for(int i = 0; i < src.num_elements(); ++i)
     {
         Coordinates coord = index2coord(src.shape(), i);
         const int   x     = coord.x();
         const int   y     = coord.y();
         std::array<T, 9> neighbours = { { 0 } };
         for(int row = y - 1, j = 0; row <= y + 1; ++row)
         {
             for(int col = x - 1; col <= x + 1; ++col, ++j)
             {
                 coord.set(0, col);
                 coord.set(1, row);
                 neighbours[j] = tensor_elem_at(src, coord, border_mode, constant_border_value);
             }
         }
         dst[i] = *std::min_element(neighbours.cbegin(), neighbours.cend());
     }
     return dst;
 }
References arm_compute::test::validation::border_mode, arm_compute::test::validation::dst, arm_compute::test::index2coord(), Dimensions< T >::set(), arm_compute::test::validation::src, arm_compute::test::validation::tensor_elem_at(), Dimensions< T >::x(), and Dimensions< T >::y().
erode() [2/2]
template SimpleTensor<uint8_t> arm_compute::test::validation::reference::erode (const SimpleTensor< uint8_t > & src, BorderMode border_mode, uint8_t constant_border_value)
fast_corners() [1/2]
std::vector< KeyPoint > fast_corners (const SimpleTensor< T > & src, float input_thresh, bool suppress_nonmax, BorderMode border_mode, T constant_border_value)
Definition at line 152 of file FastCorners.cpp.
 {
     // Get intensity of pixel at given index on the Bresenham circle around a candidate point
     const auto intensity_at = [&](const Coordinates & point, const unsigned int idx)
     {
         const auto  offset = circle_offsets[idx];
         Coordinates px{ point.x() + offset[0], point.y() + offset[1] };
         return tensor_elem_at(src, px, border_mode, constant_border_value);
     };
     const auto            threshold = static_cast<uint8_t>(input_thresh);
     std::vector<KeyPoint> corners;
     // 1. Detect potential corners (the segment test)
     std::vector<Coordinates> corner_candidates;
     SimpleTensor<uint8_t>    scores(src.shape(), DataType::U8);
     ValidRegion              valid_region = shape_to_valid_region(src.shape(), BorderMode::UNDEFINED == border_mode, BorderSize(bresenham_radius));
     for(int i = 0; i < src.num_elements(); ++i)
     {
         Coordinates candidate = index2coord(src.shape(), i);
         scores[i]             = 0;
         if(!is_in_valid_region(valid_region, candidate))
         {
             continue;
         }
         if(is_a_corner(candidate, src, threshold, border_mode, constant_border_value, intensity_at))
         {
             corner_candidates.emplace_back(candidate);
             scores[i] = 1;
         }
     }
     // 2. Calculate corner scores if necessary
     if(suppress_nonmax)
     {
         for(const auto &candidate : corner_candidates)
         {
             const auto index      = coord2index(scores.shape(), candidate);
             uint8_t    thresh_max = UINT8_MAX;
             uint8_t    thresh_min = threshold;
             uint8_t    response   = (thresh_min + thresh_max) / 2;
             // Corner score (response) is the largest threshold for which the pixel remains a corner
             while(thresh_max - thresh_min > 1)
             {
                 response = (thresh_min + thresh_max) / 2;
                 if(is_a_corner(candidate, src, response, border_mode, constant_border_value, intensity_at))
                 {
                     thresh_min = response; // raise threshold
                 }
                 else
                 {
                     thresh_max = response; // lower threshold
                 }
             }
             scores[index] = thresh_min;
         }
         scores       = non_maxima_suppression(scores, border_mode, constant_border_value);
         valid_region = shape_to_valid_region(scores.shape(), BorderMode::UNDEFINED == border_mode, BorderSize(bresenham_radius + 1));
     }
     for(const auto &candidate : corner_candidates)
     {
         const auto index = coord2index(scores.shape(), candidate);
         if(scores[index] > 0.f && is_in_valid_region(valid_region, candidate))
         {
             KeyPoint corner;
             corner.x               = candidate.x();
             corner.y               = candidate.y();
             corner.strength        = scores[index];
             corner.tracking_status = 1;
             corner.scale           = 0.f;
             corner.orientation     = 0.f;
             corner.error           = 0.f;
             corners.emplace_back(corner);
         }
     }
     return corners;
 }
References arm_compute::test::validation::border_mode, arm_compute::test::coord2index(), KeyPoint::error, arm_compute::test::index2coord(), arm_compute::test::is_in_valid_region(), non_maxima_suppression(), offset(), KeyPoint::orientation, KeyPoint::scale, arm_compute::test::shape_to_valid_region(), arm_compute::test::validation::src, KeyPoint::strength, arm_compute::test::validation::tensor_elem_at(), threshold(), KeyPoint::tracking_status, arm_compute::U8, arm_compute::UNDEFINED, arm_compute::test::validation::valid_region, Dimensions< T >::x(), KeyPoint::x, Dimensions< T >::y(), and KeyPoint::y.
fast_corners() [2/2]
template std::vector<KeyPoint> arm_compute::test::validation::reference::fast_corners (const SimpleTensor< uint8_t > & src, float threshold, bool suppress_nonmax, BorderMode border_mode, uint8_t constant_border_value)
flatten_layer() [1/3]
SimpleTensor< T > flatten_layer (const SimpleTensor< T > & src, const TensorShape & shape_flatten)
Definition at line 35 of file FlattenLayer.cpp.
 {
     SimpleTensor<T> dst(shape_flatten, src.data_type(), 1);
     // Note: Since the reference implementation does not use padding bytes, we can copy directly the content of the source tensor
     std::copy(src.data(), src.data() + src.num_elements(), dst.data());
     return dst;
 }
References copy(), arm_compute::test::validation::dst, and arm_compute::test::validation::src.
flatten_layer() [2/3]
template SimpleTensor<float> arm_compute::test::validation::reference::flatten_layer (const SimpleTensor< float > & src, const TensorShape & shape_flatten)
flatten_layer() [3/3]
template SimpleTensor<half> arm_compute::test::validation::reference::flatten_layer (const SimpleTensor< half > & src, const TensorShape & shape_flatten)
floor_layer() [1/3]
SimpleTensor< T > floor_layer (const SimpleTensor< T > & src)
Definition at line 39 of file Floor.cpp.
 {
     // Create reference
     SimpleTensor<T> dst{ src.shape(), src.data_type() };
     // Compute reference
     for(int i = 0; i < src.num_elements(); ++i)
     {
         dst[i] = std::floor(src[i]);
     }
     return dst;
 }
References arm_compute::test::validation::dst, and arm_compute::test::validation::src.
floor_layer() [2/3]
template SimpleTensor<half> arm_compute::test::validation::reference::floor_layer (const SimpleTensor< half > & src)
floor_layer() [3/3]
template SimpleTensor<float> arm_compute::test::validation::reference::floor_layer (const SimpleTensor< float > & src)
fully_connected_layer() [1/4]
SimpleTensor< T > fully_connected_layer (const SimpleTensor< T > & src, const SimpleTensor< T > & weights, const SimpleTensor< TB > & bias, const TensorShape & dst_shape, QuantizationInfo out_quant_info)
Definition at line 112 of file FullyConnectedLayer.cpp.
 {
     // if no explicit quantization has been set you the same as src
     if(out_quant_info == QuantizationInfo())
     {
         out_quant_info = src.quantization_info();
     }
     // Create reference
     SimpleTensor<T> dst{ TensorShape{ dst_shape }, src.data_type(), 1, out_quant_info };
     // Sanity checks
     const int          num_batch_dimensions = std::max(0, static_cast<int>(dst_shape.num_dimensions()) - 1);
     const int          num_input_dimensions = src.shape().num_dimensions() - num_batch_dimensions;
     const unsigned int linear_input_size    = src.shape().total_size_lower(num_input_dimensions);
     ARM_COMPUTE_UNUSED(num_batch_dimensions);
     ARM_COMPUTE_UNUSED(num_input_dimensions);
     ARM_COMPUTE_UNUSED(linear_input_size);
     ARM_COMPUTE_ERROR_ON(weights.shape().x() != linear_input_size);
     ARM_COMPUTE_ERROR_ON(weights.shape().y() != bias.shape().x());
     ARM_COMPUTE_ERROR_ON(weights.shape().y() != dst.shape().x());
     // Compute reference
     const int cols_weights = weights.shape().x();
     const int rows_weights = weights.shape().y();
     const int num_batches  = dst_shape.total_size_upper(1);
     for(int k = 0; k < num_batches; ++k)
     {
         const int offset_in  = k * cols_weights;
         const int offset_out = k * rows_weights;
         vector_matrix_multiply<T>(src,
                                   weights,
                                   bias,
                                   dst,
                                   offset_in,
                                   offset_out,
                                   cols_weights,
                                   rows_weights);
     }
     return dst;
 }
References ARM_COMPUTE_ERROR_ON, ARM_COMPUTE_UNUSED, arm_compute::test::validation::bias, arm_compute::test::validation::dst, arm_compute::test::validation::dst_shape, Dimensions< T >::num_dimensions(), arm_compute::test::validation::src, TensorShape::total_size_upper(), and arm_compute::test::validation::weights.
fully_connected_layer() [2/4]
template SimpleTensor<float> arm_compute::test::validation::reference::fully_connected_layer (const SimpleTensor< float > & src, const SimpleTensor< float > & weights, const SimpleTensor< float > & bias, const TensorShape & dst_shape, QuantizationInfo out_quant_info)
fully_connected_layer() [3/4]
template SimpleTensor<half> arm_compute::test::validation::reference::fully_connected_layer (const SimpleTensor< half > & src, const SimpleTensor< half > & weights, const SimpleTensor< half > & bias, const TensorShape & dst_shape, QuantizationInfo out_quant_info)
fully_connected_layer() [4/4]
template SimpleTensor<uint8_t> arm_compute::test::validation::reference::fully_connected_layer (const SimpleTensor< uint8_t > & src, const SimpleTensor< uint8_t > & weights, const SimpleTensor< int32_t > & bias, const TensorShape & dst_shape, QuantizationInfo out_quant_info)
fuse_batch_normalization_conv_layer() [1/3]
void fuse_batch_normalization_conv_layer (const SimpleTensor< T > & w, const SimpleTensor< T > & mean, const SimpleTensor< T > & var, SimpleTensor< T > & w_fused, SimpleTensor< T > & b_fused, const SimpleTensor< T > & b, const SimpleTensor< T > & beta, const SimpleTensor< T > & gamma, float epsilon)
Definition at line 67 of file FuseBatchNormalization.cpp.
 {
     const auto *w_data = w.data();
     const auto *b_data = b.data();
     auto *w_fused_data = w_fused.data();
     auto *b_fused_data = b_fused.data();
     const unsigned int width  = w.shape()[0];
     const unsigned int height = w.shape()[1];
     const unsigned int dim2   = w.shape()[2];
     const unsigned int dim3   = w.shape()[3];
     for(unsigned int b = 0; b < dim3; ++b)
     {
         const auto mean_val  = mean.data()[b];
         const auto var_val   = var.data()[b];
         const auto beta_val  = beta.data()[b];
         const auto gamma_val = gamma.data()[b];
         for(unsigned int i = 0; i < width * height * dim2; ++i)
         {
             unsigned int index = i + b * width * height * dim2;
             w_fused_data[index] = (gamma_val * (w_data[index])) / sqrt(var_val + epsilon);
         }
         b_fused_data[b] = (b_data[b] - mean_val) / sqrt(var_val + epsilon) * gamma_val + beta_val;
     }
 }
References arm_compute::test::validation::b, SimpleTensor< T >::data(), epsilon, and arm_compute::test::validation::w.
fuse_batch_normalization_conv_layer() [2/3]
template void arm_compute::test::validation::reference::fuse_batch_normalization_conv_layer (const SimpleTensor< float > & w, const SimpleTensor< float > & mean, const SimpleTensor< float > & var, SimpleTensor< float > & w_fused, SimpleTensor< float > & b_fused, const SimpleTensor< float > & b, const SimpleTensor< float > & beta, const SimpleTensor< float > & gamma, float epsilon)
fuse_batch_normalization_conv_layer() [3/3]
template void arm_compute::test::validation::reference::fuse_batch_normalization_conv_layer (const SimpleTensor< half > & w, const SimpleTensor< half > & mean, const SimpleTensor< half > & var, SimpleTensor< half > & w_fused, SimpleTensor< half > & b_fused, const SimpleTensor< half > & b, const SimpleTensor< half > & beta, const SimpleTensor< half > & gamma, float epsilon)
fuse_batch_normalization_dwc_layer() [1/3]
void fuse_batch_normalization_dwc_layer (const SimpleTensor< T > & w, const SimpleTensor< T > & mean, const SimpleTensor< T > & var, SimpleTensor< T > & w_fused, SimpleTensor< T > & b_fused, const SimpleTensor< T > & b, const SimpleTensor< T > & beta, const SimpleTensor< T > & gamma, float epsilon)
Definition at line 35 of file FuseBatchNormalization.cpp.
 {
     const auto *w_data = w.data();
     const auto *b_data = b.data();
     auto *w_fused_data = w_fused.data();
     auto *b_fused_data = b_fused.data();
     const unsigned int width  = w.shape()[0];
     const unsigned int height = w.shape()[1];
     const unsigned int dim2   = w.shape()[2];
     for(unsigned int b = 0; b < dim2; ++b)
     {
         const auto mean_val  = mean.data()[b];
         const auto var_val   = var.data()[b];
         const auto beta_val  = beta.data()[b];
         const auto gamma_val = gamma.data()[b];
         for(unsigned int i = 0; i < width * height; ++i)
         {
             unsigned int index = i + b * width * height;
             w_fused_data[index] = (gamma_val * (w_data[index])) / sqrt(var_val + epsilon);
         }
         b_fused_data[b] = (b_data[b] - mean_val) / sqrt(var_val + epsilon) * gamma_val + beta_val;
     }
 }
References arm_compute::test::validation::b, SimpleTensor< T >::data(), epsilon, and arm_compute::test::validation::w.
fuse_batch_normalization_dwc_layer() [2/3]
template void arm_compute::test::validation::reference::fuse_batch_normalization_dwc_layer (const SimpleTensor< float > & w, const SimpleTensor< float > & mean, const SimpleTensor< float > & var, SimpleTensor< float > & w_fused, SimpleTensor< float > & b_fused, const SimpleTensor< float > & b, const SimpleTensor< float > & beta, const SimpleTensor< float > & gamma, float epsilon)
fuse_batch_normalization_dwc_layer() [3/3]
template void arm_compute::test::validation::reference::fuse_batch_normalization_dwc_layer (const SimpleTensor< half > & w, const SimpleTensor< half > & mean, const SimpleTensor< half > & var, SimpleTensor< half > & w_fused, SimpleTensor< half > & b_fused, const SimpleTensor< half > & b, const SimpleTensor< half > & beta, const SimpleTensor< half > & gamma, float epsilon)
gather() [1/5]
SimpleTensor< T > gather (const SimpleTensor< T > & src, const SimpleTensor< uint32_t > & indices, uint32_t actual_axis)
Definition at line 40 of file Gather.cpp.
 {
     const auto       *indices_ptr = static_cast<const uint32_t *>(indices.data());
     const TensorShape dst_shape   = arm_compute::misc::shape_calculator::compute_gather_shape(src.shape(), indices.shape(), actual_axis);
     SimpleTensor<T>   dst(dst_shape, src.data_type());
     Window win;
     win.use_tensor_dimensions(dst_shape);
     execute_window_loop(win, [&](const Coordinates & id)
     {
         Coordinates offset;
         for(unsigned int dim = 0; dim < id.num_dimensions(); ++dim)
         {
             if(dim == actual_axis)
             {
                 offset.set(dim, indices_ptr[id[dim]]);
             }
             else
             {
                 offset.set(dim, id[dim]);
             }
         }
         *reinterpret_cast<T *>(dst(id)) = *reinterpret_cast<const T *>(src(offset));
     });
     return dst;
 }
References arm_compute::misc::shape_calculator::compute_gather_shape(), SimpleTensor< T >::data(), arm_compute::test::validation::dst, arm_compute::test::validation::dst_shape, arm_compute::execute_window_loop(), offset(), SimpleTensor< T >::shape(), arm_compute::test::validation::src, and Window::use_tensor_dimensions().
gather() [2/5]
template SimpleTensor<float> arm_compute::test::validation::reference::gather (const SimpleTensor< float > & src, const SimpleTensor< uint32_t > & indices, uint32_t actual_axis)
gather() [3/5]
template SimpleTensor<half> arm_compute::test::validation::reference::gather (const SimpleTensor< half > & src, const SimpleTensor< uint32_t > & indices, uint32_t actual_axis)
gather() [4/5]
template SimpleTensor<uint16_t> arm_compute::test::validation::reference::gather (const SimpleTensor< uint16_t > & src, const SimpleTensor< uint32_t > & indices, uint32_t actual_axis)
gather() [5/5]
template SimpleTensor<uint8_t> arm_compute::test::validation::reference::gather (const SimpleTensor< uint8_t > & src, const SimpleTensor< uint32_t > & indices, uint32_t actual_axis)
gaussian3x3() [1/2]
SimpleTensor< T > gaussian3x3 (const SimpleTensor< T > & src, BorderMode border_mode, T constant_border_value)
Definition at line 38 of file Gaussian3x3.cpp.
 {
     SimpleTensor<T> dst(src.shape(), src.data_type());
     const std::array<T, 9> filter{ { 1, 2, 1, 2, 4, 2, 1, 2, 1 } };
     const float scale = 1.f / 16.f;
     for(int element_idx = 0; element_idx < src.num_elements(); ++element_idx)
     {
         const Coordinates id = index2coord(src.shape(), element_idx);
         apply_2d_spatial_filter(id, src, dst, TensorShape(3U, 3U), filter.data(), scale, border_mode, constant_border_value);
     }
     return dst;
 }
References arm_compute::test::validation::apply_2d_spatial_filter(), arm_compute::test::validation::border_mode, arm_compute::test::validation::dst, arm_compute::test::index2coord(), scale(), and arm_compute::test::validation::src.
gaussian3x3() [2/2]
template SimpleTensor<uint8_t> arm_compute::test::validation::reference::gaussian3x3 (const SimpleTensor< uint8_t > & src, BorderMode border_mode, uint8_t constant_border_value)
gaussian5x5() [1/2]
SimpleTensor< T > gaussian5x5 (const SimpleTensor< T > & src, BorderMode border_mode, T constant_border_value)
Definition at line 38 of file Gaussian5x5.cpp.
 {
     SimpleTensor<T> dst(src.shape(), src.data_type());
     const std::array<T, 25> filter{ {
             1, 4, 6, 4, 1,
             4, 16, 24, 16, 4,
             6, 24, 36, 24, 6,
             4, 16, 24, 16, 4,
             1, 4, 6, 4, 1
         } };
     const float scale = 1.f / 256.f;
     for(int element_idx = 0; element_idx < src.num_elements(); ++element_idx)
     {
         const Coordinates id = index2coord(src.shape(), element_idx);
         apply_2d_spatial_filter(id, src, dst, TensorShape(5U, 5U), filter.data(), scale, border_mode, constant_border_value);
     }
     return dst;
 }
References arm_compute::test::validation::apply_2d_spatial_filter(), arm_compute::test::validation::border_mode, arm_compute::test::validation::dst, arm_compute::test::index2coord(), scale(), and arm_compute::test::validation::src.
Referenced by gaussian_pyramid_half(), and laplacian_pyramid().
gaussian5x5() [2/2]
template SimpleTensor<uint8_t> arm_compute::test::validation::reference::gaussian5x5 (const SimpleTensor< uint8_t > & src, BorderMode border_mode, uint8_t constant_border_value)
gaussian_pyramid_half() [1/2]
std::vector< SimpleTensor< T > > gaussian_pyramid_half (const SimpleTensor< T > & src, BorderMode border_mode, uint8_t constant_border_value, size_t num_levels)
Definition at line 41 of file GaussianPyramidHalf.cpp.
 {
     std::vector<SimpleTensor<T>> dst;
     // Level0 is equal to src
     dst.push_back(src);
     for(size_t i = 1; i < num_levels; ++i)
     {
         // Gaussian Filter
         const SimpleTensor<T> out_gaus5x5 = reference::gaussian5x5(dst[i - 1], border_mode, constant_border_value);
         // Scale down by 2 with nearest interpolation
         const SimpleTensor<T> out = reference::scale(out_gaus5x5, SCALE_PYRAMID_HALF, SCALE_PYRAMID_HALF, InterpolationPolicy::NEAREST_NEIGHBOR, border_mode, constant_border_value, SamplingPolicy::CENTER,
                                                      true);
         dst.push_back(out);
     }
     return dst;
 }
References arm_compute::test::validation::border_mode, arm_compute::CENTER, arm_compute::test::validation::dst, gaussian5x5(), arm_compute::NEAREST_NEIGHBOR, scale(), arm_compute::SCALE_PYRAMID_HALF, and arm_compute::test::validation::src.
Referenced by arm_compute::test::validation::DATA_TEST_CASE(), laplacian_pyramid(), and optical_flow().
gaussian_pyramid_half() [2/2]
template std::vector<SimpleTensor<uint8_t> > arm_compute::test::validation::reference::gaussian_pyramid_half (const SimpleTensor< uint8_t > & src, BorderMode border_mode, uint8_t constant_border_value, size_t num_levels)
gemm() [1/3]
SimpleTensor< T > gemm (const SimpleTensor< T > & a, const SimpleTensor< T > & b, const SimpleTensor< T > & c, float alpha, float beta)
Definition at line 37 of file GEMM.cpp.
 {
     // Create reference
     SimpleTensor<T> dst{ c.shape(), c.data_type(), 1 };
     // Compute reference
     const int M = a.shape().y();
     const int N = b.shape().x();
     const int K = a.shape().x();
     const int D = a.shape().z(); // Number of matrices in a batch
     const int W = a.shape()[3];  // Number of batched-gemm (Winograd case)
     const int a_stride_z = K * M;
     const int a_stride_w = K * M * D;
     const int b_stride_z = b.shape().num_dimensions() > 2 ? N * K : 0;     // Do not slide the matrix B along the 3th dimension in case matrix B has less than 3 dimensions
     const int b_stride_w = b.shape().num_dimensions() > 3 ? K * N * D : 0; // Do not slide the matrix B along the 4th dimension in case matrix B has less than 4 dimensions
     const int c_stride_z = N * M;
     const int c_stride_w = N * M * D;
     for(int w = 0; w < W; ++w)
     {
         for(int depth = 0; depth < D; ++depth)
         {
             const int base_addr_a = depth * a_stride_z + w * a_stride_w;
             const int base_addr_b = depth * b_stride_z + w * b_stride_w;
             const int base_addr_c = depth * c_stride_z + w * c_stride_w;
             for(int row = 0; row < M; ++row)
             {
                 for(int col = 0; col < N; ++col)
                 {
                     T acc(0);
                     for(int k = 0; k < K; ++k)
                     {
                         acc += a[base_addr_a + k + row * K] * b[base_addr_b + col + k * N];
                     }
                     // Finalize the result: alpha * A * B + beta * C
                     dst[base_addr_c + col + row * N] = alpha * acc + beta * c[base_addr_c + col + row * N];
                 }
             }
         }
     }
     return dst;
 }
References arm_compute::test::validation::alpha, arm_compute::test::validation::b, SimpleTensor< T >::data_type(), arm_compute::test::validation::dst, SimpleTensor< T >::shape(), and arm_compute::test::validation::w.
gemm() [2/3]
template SimpleTensor<float> arm_compute::test::validation::reference::gemm (const SimpleTensor< float > & a, const SimpleTensor< float > & b, const SimpleTensor< float > & c, float alpha, float beta)
gemm() [3/3]
template SimpleTensor<half> arm_compute::test::validation::reference::gemm (const SimpleTensor< half > & a, const SimpleTensor< half > & b, const SimpleTensor< half > & c, float alpha, float beta)
Referenced by arm_compute::test::validation::DATA_TEST_CASE().
gemm_interleave_4x4()
SimpleTensor<T> arm_compute::test::validation::reference::gemm_interleave_4x4 (const SimpleTensor< T > & in, SimpleTensor< T > & out)
Definition at line 37 of file GEMMInterleave4x4.h.
 {
     const T      *mtx_in     = reinterpret_cast<const T *>(in.data());
     T            *mtx_ref    = reinterpret_cast<T *>(out.data());
     const int32_t in_rows    = in.shape().y();
     const int32_t in_cols    = in.shape().x();
     const int32_t out_stride = out.shape().x();
     int32_t       y          = 0;
     for(; y <= (in_rows - 4); y += 4)
     {
         const T *in_ptr = &mtx_in[y * in_cols];
         for(int32_t x = 0; x < in_cols; x++)
         {
             const T tmp[4] = { in_ptr[x + 0 * in_cols],
                                in_ptr[x + 1 * in_cols],
                                in_ptr[x + 2 * in_cols],
                                in_ptr[x + 3 * in_cols]
                              };
             T *dst = &mtx_ref[static_cast<size_t>(x * 4.f) + static_cast<size_t>(std::ceil(y / 4.f)) * out_stride];
             memcpy(dst, tmp, sizeof(T) * 4);
         }
     }
     // Leftover along the Y direction
     const int32_t leftover_y = in_rows - y;
     if(leftover_y != 0)
     {
         const T *in_ptr = &mtx_in[y * in_cols];
         for(int32_t x = 0; x < in_cols; x++)
         {
             T tmp[4] = { 0, 0, 0, 0 };
             for(int32_t k = 0; k < leftover_y; k++)
             {
                 tmp[k] = in_ptr[k * in_cols + x];
             }
             T *dst = &mtx_ref[static_cast<size_t>(x * 4.f) + static_cast<size_t>(std::ceil(y / 4.f)) * out_stride];
             memcpy(dst, tmp, sizeof(T) * 4);
         }
     }
     return out;
 }
References SimpleTensor< T >::data(), arm_compute::test::validation::dst, and SimpleTensor< T >::shape().
gemm_interleave_blocked() [1/2]
SimpleTensor<T> arm_compute::test::validation::reference::gemm_interleave_blocked (const SimpleTensor< T > & in, SimpleTensor< T > & out, int int_by, int block, bool transposed)
Definition at line 50 of file GEMMInterleaveBlocked.h.
 {
     const int M = out.shape().y();
     const int N = out.shape().x();
     for(int y = 0; y < M; y++)
     {
         T *out_ptr = &out[y * N];
         for(int x = 0; x < (N / int_by); x += block)
         {
             for(int z = 0; z < int_by; z++)
             {
                 for(int a = 0; (out_ptr <= &out[y * N + (N - 1)]) && a < block; a++)
                 {
                     if(!transposed)
                         *out_ptr++ = safe_read(in, (y * int_by) + z, x + a);
                     else
                     {
                         const T value = safe_read(in, x + a, (y * int_by) + z);
                         *out_ptr++    = value;
                     }
                 }
             }
         }
     }
     return out;
 }
References safe_read(), and SimpleTensor< T >::shape().
gemm_interleave_blocked() [2/2]
template SimpleTensor<uint8_t> arm_compute::test::validation::reference::gemm_interleave_blocked (const SimpleTensor< uint8_t > & in, SimpleTensor< uint8_t > & out, int int_by, int block, bool transposed)
gemm_reshape_lhs_matrix() [1/4]
SimpleTensor< T > gemm_reshape_lhs_matrix (const SimpleTensor< T > & in, const TensorShape & output_shape, const GEMMLHSMatrixInfo & lhs_info)
Definition at line 43 of file GEMMReshapeLHSMatrix.cpp.
 {
     ARM_COMPUTE_ERROR_ON(in.shape().num_dimensions() > 3);
     SimpleTensor<T> out{ output_shape, in.data_type() };
     // Initialize the output tensor with zero
     std::memset(&out[0], 0, out.num_elements() * sizeof(T));
     const unsigned int K = in.shape()[0];
     const unsigned int M = in.shape()[1];
     const unsigned int B = in.shape()[2];
     const unsigned int num_tiles_x = std::ceil(K / static_cast<float>(lhs_info.k0));
     const unsigned int num_tiles_y = std::ceil(M / static_cast<float>(lhs_info.m0));
     const TensorShape tile_dims(lhs_info.k0, lhs_info.m0);
     const TensorShape tile_dims_transposed(lhs_info.m0, lhs_info.k0);
     // Simple tensor for the input tile
     SimpleTensor<T> src_tile{ tile_dims, in.data_type() };
     // Simple tensor for the input tile
     SimpleTensor<T> src_tile_transposed{ tile_dims_transposed, in.data_type() };
     // Simple tensor to use when storing the values
     SimpleTensor<T> *tile_to_use = lhs_info.transpose ? &src_tile_transposed : &src_tile;
     const unsigned int offset_output_x = lhs_info.interleave ? tile_to_use->shape()[0] : tile_to_use->shape()[0] * tile_to_use->shape()[1];
     const unsigned int step_output_x   = lhs_info.interleave ? tile_to_use->shape()[0] * lhs_info.v0 : tile_to_use->shape()[0];
     for(unsigned int z = 0; z < B; ++z)
     {
         for(unsigned int y = 0; y < num_tiles_y; ++y)
         {
             for(unsigned int x = 0; x < num_tiles_x; ++x)
             {
                 // Get the tile from the input tensor
                 get_tile<T>(in, src_tile, Coordinates(x * lhs_info.k0, y * lhs_info.m0, z, 0));
                 if(lhs_info.transpose)
                 {
                     // Transpose matrix
                     transpose_matrix<T>(src_tile, src_tile_transposed);
                 }
                 // Store
                 const unsigned int offset_output = (x * lhs_info.k0 * lhs_info.m0 * lhs_info.v0) + ((y % lhs_info.v0) * offset_output_x) + ((y / lhs_info.v0) * out.shape()[0]) + (z * out.shape()[0] * out.shape()[1]);
                 for(unsigned int i = 0; i < tile_to_use->shape()[1]; ++i)
                 {
                     const unsigned int offset_tile = i * tile_to_use->shape()[0];
                     // Copy per row
                     std::copy(&(*tile_to_use)[offset_tile], &(*tile_to_use)[offset_tile + tile_to_use->shape()[0]], &out[offset_output + i * step_output_x]);
                 }
             }
         }
     }
     return out;
 }
References ARM_COMPUTE_ERROR_ON, arm_compute::B, copy(), SimpleTensor< T >::data_type(), GEMMLHSMatrixInfo::interleave, GEMMLHSMatrixInfo::k0, GEMMLHSMatrixInfo::m0, arm_compute::test::validation::output_shape, SimpleTensor< T >::shape(), GEMMLHSMatrixInfo::transpose, and GEMMLHSMatrixInfo::v0.
gemm_reshape_lhs_matrix() [2/4]
template SimpleTensor<int> arm_compute::test::validation::reference::gemm_reshape_lhs_matrix (const SimpleTensor< int > & in, const TensorShape & output_shape, const GEMMLHSMatrixInfo & lhs_info)
gemm_reshape_lhs_matrix() [3/4]
template SimpleTensor<short> arm_compute::test::validation::reference::gemm_reshape_lhs_matrix (const SimpleTensor< short > & in, const TensorShape & output_shape, const GEMMLHSMatrixInfo & lhs_info)
gemm_reshape_lhs_matrix() [4/4]
template SimpleTensor<char> arm_compute::test::validation::reference::gemm_reshape_lhs_matrix (const SimpleTensor< char > & in, const TensorShape & output_shape, const GEMMLHSMatrixInfo & lhs_info)
gemm_reshape_rhs_matrix() [1/4]
SimpleTensor< T > gemm_reshape_rhs_matrix (const SimpleTensor< T > & in, const TensorShape & output_shape, const GEMMRHSMatrixInfo & rhs_info)
Definition at line 43 of file GEMMReshapeRHSMatrix.cpp.
 {
     ARM_COMPUTE_ERROR_ON(in.shape().num_dimensions() > 3);
     SimpleTensor<T> out{ output_shape, in.data_type() };
     // Initialize the output tensor with zero
     std::memset(&out[0], 0, out.num_elements() * sizeof(T));
     const unsigned int N = in.shape()[0];
     const unsigned int K = in.shape()[1];
     const unsigned int B = in.shape()[2];
     const unsigned int num_tiles_x = std::ceil(N / static_cast<float>(rhs_info.n0));
     const unsigned int num_tiles_y = std::ceil(K / static_cast<float>(rhs_info.k0));
     const TensorShape tile_dims(rhs_info.n0, rhs_info.k0);
     const TensorShape tile_dims_transposed(rhs_info.k0, rhs_info.n0);
     // Simple tensor for the input tile
     SimpleTensor<T> src_tile{ tile_dims, in.data_type() };
     // Simple tensor for the input tile
     SimpleTensor<T> src_tile_transposed{ tile_dims_transposed, in.data_type() };
     // Simple tensor to use when storing the values
     SimpleTensor<T> *tile_to_use = rhs_info.transpose ? &src_tile_transposed : &src_tile;
     const unsigned int offset_output_x = rhs_info.interleave ? tile_to_use->shape()[0] : tile_to_use->shape()[0] * tile_to_use->shape()[1];
     const unsigned int step_output_x   = rhs_info.interleave ? tile_to_use->shape()[0] * rhs_info.h0 : tile_to_use->shape()[0];
     for(unsigned int z = 0; z < B; ++z)
     {
         for(unsigned int y = 0; y < num_tiles_y; ++y)
         {
             for(unsigned int x = 0; x < num_tiles_x; ++x)
             {
                 // Get the tile from the input tensor
                 get_tile<T>(in, src_tile, Coordinates(x * rhs_info.n0, y * rhs_info.k0, z, 0));
                 if(rhs_info.transpose)
                 {
                     // Transpose matrix
                     transpose_matrix<T>(src_tile, src_tile_transposed);
                 }
                 // Store
                 const unsigned int offset_output = (y * rhs_info.k0 * rhs_info.n0 * rhs_info.h0) + ((x % rhs_info.h0) * offset_output_x) + ((x / rhs_info.h0) * out.shape()[0]) + (z * out.shape()[0] * out.shape()[1]);
                 for(unsigned int i = 0; i < tile_to_use->shape()[1]; ++i)
                 {
                     const unsigned int offset_tile = i * tile_to_use->shape()[0];
                     // Copy per row
                     std::copy(&(*tile_to_use)[offset_tile], &(*tile_to_use)[offset_tile + tile_to_use->shape()[0]], &out[offset_output + i * step_output_x]);
                 }
             }
         }
     }
     return out;
 }
References ARM_COMPUTE_ERROR_ON, arm_compute::B, copy(), SimpleTensor< T >::data_type(), GEMMRHSMatrixInfo::h0, GEMMRHSMatrixInfo::interleave, GEMMRHSMatrixInfo::k0, GEMMRHSMatrixInfo::n0, arm_compute::test::validation::output_shape, SimpleTensor< T >::shape(), and GEMMRHSMatrixInfo::transpose.
gemm_reshape_rhs_matrix() [2/4]
template SimpleTensor<int> arm_compute::test::validation::reference::gemm_reshape_rhs_matrix (const SimpleTensor< int > & in, const TensorShape & output_shape, const GEMMRHSMatrixInfo & rhs_info)
gemm_reshape_rhs_matrix() [3/4]
template SimpleTensor<short> arm_compute::test::validation::reference::gemm_reshape_rhs_matrix (const SimpleTensor< short > & in, const TensorShape & output_shape, const GEMMRHSMatrixInfo & rhs_info)
gemm_reshape_rhs_matrix() [4/4]
template SimpleTensor<char> arm_compute::test::validation::reference::gemm_reshape_rhs_matrix (const SimpleTensor< char > & in, const TensorShape & output_shape, const GEMMRHSMatrixInfo & rhs_info)
gemm_transpose_1xW()
SimpleTensor<T> arm_compute::test::validation::reference::gemm_transpose_1xW (const SimpleTensor< T > & in)
Definition at line 37 of file GEMMTranspose1xW.h.
 {
     const int         W = 16 / sizeof(T);
     const TensorShape shape_out(static_cast<size_t>(in.shape().y() * W), static_cast<size_t>(std::ceil(in.shape().x() / static_cast<float>(W))));
     SimpleTensor<T>   out(shape_out, in.data_type());
     const int32_t     in_height     = in.shape().y();
     const int32_t     in_width      = in.shape().x();
     const int32_t     out_width     = out.shape().x();
     const T          *in_base_addr  = reinterpret_cast<const T *>(in.data());
     T                *out_base_addr = reinterpret_cast<T *>(out.data());
     int               x             = 0;
     for(; x < in_width; x += W)
     {
         for(int y = 0; y < in_height; y++)
         {
             const T *in_addr  = (in_base_addr + x + y * in_width);
             T       *out_addr = (out_base_addr + y * W + (x / W) * out_width);
             for(int k = 0; k < W; ++k)
             {
                 // If the input width is not multiple of W, we fill the reference with 0s
                 if((x + k) >= in_width)
                 {
                     out_addr[k] = T(0);
                 }
                 else
                 {
                     out_addr[k] = in_addr[k];
                 }
             }
         }
     }
     return out;
 }
References SimpleTensor< T >::data(), SimpleTensor< T >::data_type(), and SimpleTensor< T >::shape().
gemmlowp() [1/3]
SimpleTensor< T1 > gemmlowp (const SimpleTensor< T2 > & a, const SimpleTensor< T2 > & b, TensorShape shape_c)
Definition at line 183 of file GEMMLowp.cpp.
 {
     return gemmlowp_matrix_multiply_core<T1, T2>(a, b, shape_c, 0, 0);
 }
References arm_compute::test::validation::b.
gemmlowp() [2/3]
template SimpleTensor<int32_t> arm_compute::test::validation::reference::gemmlowp (const SimpleTensor< int8_t > & a, const SimpleTensor< int8_t > & b, TensorShape shape_c)
gemmlowp() [3/3]
template SimpleTensor<int32_t> arm_compute::test::validation::reference::gemmlowp (const SimpleTensor< uint8_t > & a, const SimpleTensor< uint8_t > & b, TensorShape shape_c)
gemmlowp_matrix_multiply_core() [1/4]
SimpleTensor<T1> arm_compute::test::validation::reference::gemmlowp_matrix_multiply_core (const SimpleTensor< T2 > & a, const SimpleTensor< T2 > & b, TensorShape shape_c, int32_t a_offset, int32_t b_offset)
gemmlowp_matrix_multiply_core() [2/4]
SimpleTensor<T_out> arm_compute::test::validation::reference::gemmlowp_matrix_multiply_core (const SimpleTensor< T_in > & a, const SimpleTensor< T_in > & b, TensorShape shape_c, int32_t a_offset, int32_t b_offset)
Definition at line 129 of file GEMMLowp.cpp.
 {
     static_assert(std::is_same<typename std::decay<T_out>::type, int32_t>::value, "Only int32_t is allowed for the output");
     DataType            dt = std::is_same<T_out, int32_t>::value ? DataType::S32 : DataType::U32;
     SimpleTensor<T_out> c(shape_c, dt);
     const int K = a.shape().x();
     const int M = a.shape().y();
     const int N = b.shape().x();
     const int D = a.shape().z(); // Number of matrices in a batch
     const int a_stride_z = K * M;
     // Do not slide the matrix B along the 3rd dimension in case matrix B has less than 3 dimensions
     const int b_stride_z = b.shape().num_dimensions() > 2 ? N * K : 0;
     const int c_stride_z = N * M;
     std::vector<T_out> acc;
     acc.resize(N);
     for(int depth = 0; depth < D; ++depth)
     {
         const int base_addr_a = depth * a_stride_z;
         const int base_addr_b = depth * b_stride_z;
         const int base_addr_c = depth * c_stride_z;
         for(int i = 0; i < M; ++i)
         {
             for(int j = 0; j < N; ++j)
             {
                 acc[j] = 0;
             }
             for(int k = 0; k < K; ++k)
             {
                 const T_out tmp_a = a_offset + static_cast<T_out>(a[base_addr_a + k + i * K]);
                 for(int j = 0; j < N; ++j)
                 {
                     const T_out tmp_b       = b_offset + static_cast<T_out>(b[base_addr_b + j + k * N]);
                     const T_out mult_as_int = tmp_a * tmp_b;
                     acc[j] += mult_as_int;
                 }
             }
             for(int j = 0; j < N; ++j)
             {
                 c[base_addr_c + j + i * N] = acc[j];
             }
         }
     }
     return c;
 }
gemmlowp_matrix_multiply_core() [3/4]
template SimpleTensor<int32_t> arm_compute::test::validation::reference::gemmlowp_matrix_multiply_core (const SimpleTensor< int8_t > & a, const SimpleTensor< int8_t > & b, TensorShape shape_c, int32_t a_offset, int32_t b_offset)
gemmlowp_matrix_multiply_core() [4/4]
template SimpleTensor<int32_t> arm_compute::test::validation::reference::gemmlowp_matrix_multiply_core (const SimpleTensor< uint8_t > & a, const SimpleTensor< uint8_t > & b, TensorShape shape_c, int32_t a_offset, int32_t b_offset)
gemmlowp_quantize_down_int32_to_int16_scale_by_fixedpoint() [1/4]
SimpleTensor< int16_t > gemmlowp_quantize_down_int32_to_int16_scale_by_fixedpoint (const SimpleTensor< T > & in, int32_t result_fixedpoint_multiplier, int32_t result_shift, int32_t min, int32_t max)
Definition at line 233 of file GEMMLowp.cpp.
 {
     SimpleTensor<int16_t> dst(in.shape(), DataType::QSYMM16);
     quantize_down_int32_to_int16_scale_by_fixedpoint<T>(&in, nullptr, &dst, result_fixedpoint_multiplier, result_shift, min, max);
     return dst;
 }
References arm_compute::test::validation::dst, arm_compute::QSYMM16, and SimpleTensor< T >::shape().
gemmlowp_quantize_down_int32_to_int16_scale_by_fixedpoint() [2/4]
SimpleTensor< int16_t > gemmlowp_quantize_down_int32_to_int16_scale_by_fixedpoint (const SimpleTensor< T > & in, const SimpleTensor< T > & bias, int32_t result_fixedpoint_multiplier, int32_t result_shift, int32_t min, int32_t max)
Definition at line 244 of file GEMMLowp.cpp.
 {
     SimpleTensor<int16_t> dst(in.shape(), DataType::QSYMM16);
     quantize_down_int32_to_int16_scale_by_fixedpoint<T>(&in, &bias, &dst, result_fixedpoint_multiplier, result_shift, min, max);
     return dst;
 }
References arm_compute::test::validation::bias, arm_compute::test::validation::dst, arm_compute::QSYMM16, and SimpleTensor< T >::shape().
gemmlowp_quantize_down_int32_to_int16_scale_by_fixedpoint() [3/4]
template SimpleTensor<int16_t> arm_compute::test::validation::reference::gemmlowp_quantize_down_int32_to_int16_scale_by_fixedpoint (const SimpleTensor< int32_t > & a, int32_t result_fixedpoint_multiplier, int32_t result_shift, int32_t min, int32_t max)
gemmlowp_quantize_down_int32_to_int16_scale_by_fixedpoint() [4/4]
template SimpleTensor<int16_t> arm_compute::test::validation::reference::gemmlowp_quantize_down_int32_to_int16_scale_by_fixedpoint (const SimpleTensor< int32_t > & a, const SimpleTensor< int32_t > & b, int32_t result_fixedpoint_multiplier, int32_t result_shift, int32_t min, int32_t max)
gemmlowp_quantize_down_int32_to_uint8_scale() [1/5]
SimpleTensor<uint8_t> arm_compute::test::validation::reference::gemmlowp_quantize_down_int32_to_uint8_scale (const SimpleTensor< T > & in, int32_t result_offset, int32_t result_mult_int, int32_t result_shift)
gemmlowp_quantize_down_int32_to_uint8_scale() [2/5]
SimpleTensor< uint8_t > gemmlowp_quantize_down_int32_to_uint8_scale (const SimpleTensor< T > & in, int32_t result_offset, int32_t result_mult_int, int32_t result_shift, int32_t min, int32_t max)
Definition at line 189 of file GEMMLowp.cpp.
 {
     SimpleTensor<uint8_t> dst(in.shape(), DataType::QASYMM8);
     quantize_down_int32_to_uint8_scale<T>(&in, nullptr, &dst, result_offset, result_mult_int, result_shift, min, max);
     return dst;
 }
References arm_compute::test::validation::dst, arm_compute::QASYMM8, and SimpleTensor< T >::shape().
gemmlowp_quantize_down_int32_to_uint8_scale() [3/5]
SimpleTensor< uint8_t > gemmlowp_quantize_down_int32_to_uint8_scale (const SimpleTensor< T > & in, const SimpleTensor< T > & bias, int32_t result_offset, int32_t result_mult_int, int32_t result_shift, int32_t min, int32_t max)
Definition at line 199 of file GEMMLowp.cpp.
 {
     SimpleTensor<uint8_t> dst(in.shape(), DataType::QASYMM8);
     quantize_down_int32_to_uint8_scale<T>(&in, &bias, &dst, result_offset, result_mult_int, result_shift, min, max);
     return dst;
 }
References arm_compute::test::validation::bias, arm_compute::test::validation::dst, arm_compute::QASYMM8, and SimpleTensor< T >::shape().
gemmlowp_quantize_down_int32_to_uint8_scale() [4/5]
template SimpleTensor<uint8_t> arm_compute::test::validation::reference::gemmlowp_quantize_down_int32_to_uint8_scale (const SimpleTensor< int32_t > & a, int32_t result_offset, int32_t result_mult_int, int32_t result_shift, int32_t min, int32_t max)
gemmlowp_quantize_down_int32_to_uint8_scale() [5/5]
template SimpleTensor<uint8_t> arm_compute::test::validation::reference::gemmlowp_quantize_down_int32_to_uint8_scale (const SimpleTensor< int32_t > & a, const SimpleTensor< int32_t > & b, int32_t result_offset, int32_t result_mult_int, int32_t result_shift, int32_t min, int32_t max)
gemmlowp_quantize_down_int32_to_uint8_scale_by_fixedpoint() [1/4]
SimpleTensor< uint8_t > gemmlowp_quantize_down_int32_to_uint8_scale_by_fixedpoint (const SimpleTensor< T > & in, int32_t result_fixedpoint_multiplier, int32_t result_shift, int32_t result_offset_after_shift, int32_t min, int32_t max)
Definition at line 210 of file GEMMLowp.cpp.
 {
     SimpleTensor<uint8_t> dst(in.shape(), DataType::QASYMM8);
     quantize_down_int32_to_uint8_scale_by_fixedpoint<T>(&in, nullptr, &dst, result_fixedpoint_multiplier, result_shift, result_offset_after_shift, min, max);
     return dst;
 }
References arm_compute::test::validation::dst, arm_compute::QASYMM8, and SimpleTensor< T >::shape().
gemmlowp_quantize_down_int32_to_uint8_scale_by_fixedpoint() [2/4]
SimpleTensor< uint8_t > gemmlowp_quantize_down_int32_to_uint8_scale_by_fixedpoint (const SimpleTensor< T > & in, const SimpleTensor< T > & bias, int32_t result_fixedpoint_multiplier, int32_t result_shift, int32_t result_offset_after_shift, int32_t min, int32_t max)
Definition at line 222 of file GEMMLowp.cpp.
 {
     SimpleTensor<uint8_t> dst(in.shape(), DataType::QASYMM8);
     quantize_down_int32_to_uint8_scale_by_fixedpoint<T>(&in, &bias, &dst, result_fixedpoint_multiplier, result_shift, result_offset_after_shift, min, max);
     return dst;
 }
References arm_compute::test::validation::bias, arm_compute::test::validation::dst, arm_compute::QASYMM8, and SimpleTensor< T >::shape().
gemmlowp_quantize_down_int32_to_uint8_scale_by_fixedpoint() [3/4]
template SimpleTensor<uint8_t> arm_compute::test::validation::reference::gemmlowp_quantize_down_int32_to_uint8_scale_by_fixedpoint (const SimpleTensor< int32_t > & a, int32_t result_fixedpoint_multiplier, int32_t result_shift, int32_t result_offset_after_shift, int32_t min, int32_t max)
gemmlowp_quantize_down_int32_to_uint8_scale_by_fixedpoint() [4/4]
template SimpleTensor<uint8_t> arm_compute::test::validation::reference::gemmlowp_quantize_down_int32_to_uint8_scale_by_fixedpoint (const SimpleTensor< int32_t > & a, const SimpleTensor< int32_t > & b, int32_t result_fixedpoint_multiplier, int32_t result_shift, int32_t result_offset_after_shift, int32_t min, int32_t max)
harris_corner_detector() [1/2]
std::vector< KeyPoint > harris_corner_detector (const SimpleTensor< T > & src, float threshold, float min_dist, float sensitivity, int gradient_size, int block_size, BorderMode border_mode, T constant_border_value)
Definition at line 187 of file HarrisCornerDetector.cpp.
 {
     if(gradient_size < 7)
     {
         return harris_corner_detector_impl<int16_t>(src, threshold, min_dist, sensitivity, gradient_size, block_size, border_mode, constant_border_value);
     }
     else
     {
         return harris_corner_detector_impl<int32_t>(src, threshold, min_dist, sensitivity, gradient_size, block_size, border_mode, constant_border_value);
     }
 }
References arm_compute::test::validation::border_mode, arm_compute::test::validation::src, and threshold().
harris_corner_detector() [2/2]
template std::vector<KeyPoint> arm_compute::test::validation::reference::harris_corner_detector (const SimpleTensor< uint8_t > & src, float threshold, float min_dist, float sensitivity, int gradient_size, int block_size, BorderMode border_mode, uint8_t constant_border_value)
histogram() [1/2]
SimpleTensor< uint32_t > histogram (const SimpleTensor< T > & src, size_t num_bins, int32_t offset, uint32_t range)
Definition at line 38 of file Histogram.cpp.
 {
     SimpleTensor<uint32_t> dst(TensorShape(num_bins), DataType::U32);
     // Clear the distribution
     for(size_t element_idx = 0; element_idx < num_bins; ++element_idx)
     {
         dst[element_idx] = 0;
     }
     // Create the histogram
     for(int element_idx = 0; element_idx < src.num_elements(); ++element_idx)
     {
         if((offset <= src[element_idx]) && (src[element_idx] < (offset + range)))
         {
             const int index = (src[element_idx] - offset) * num_bins / range;
             dst[index]++;
         }
     }
     return dst;
 }
References arm_compute::test::validation::dst, offset(), range(), arm_compute::test::validation::src, and arm_compute::U32.
Referenced by hist_border_kernel(), hist_border_kernel_fixed(), hist_local_kernel(), and hist_local_kernel_fixed().
histogram() [2/2]
template SimpleTensor<uint32_t> arm_compute::test::validation::reference::histogram (const SimpleTensor< uint8_t > & src, size_t num_bins, int32_t offset, uint32_t range)
Referenced by arm_compute::test::validation::DATA_TEST_CASE().
hog_block_normalization() [1/2]
void hog_block_normalization (SimpleTensor< T > & desc, const SimpleTensor< T > & hog_space, const HOGInfo & hog_info)
Definition at line 174 of file HOGDescriptor.cpp.
 {
     const Size2D  cells_per_block        = hog_info.num_cells_per_block();
     const Size2D  cells_per_block_stride = hog_info.num_cells_per_block_stride();
     const Size2D &block_size             = hog_info.block_size();
     const Size2D &block_stride           = hog_info.block_stride();
     const size_t  num_bins               = hog_info.num_bins();
     const size_t shape_width          = hog_space.shape().x() * hog_info.cell_size().width;
     const size_t shape_height         = hog_space.shape().y() * hog_info.cell_size().height;
     const size_t num_bins_per_block_x = cells_per_block.width * num_bins;
     // Tensor representing single block
     SimpleTensor<T> block(TensorShape{ 1u, 1u }, DataType::F32, cells_per_block.area() * num_bins);
     int block_idx      = 0;
     int block_y_offset = 0;
     // Traverse shape
     for(auto sy = block_size.height; sy <= shape_height; sy += block_stride.height)
     {
         int block_x_offset = 0;
         for(auto sx = block_size.width; sx <= shape_width; sx += block_stride.width)
         {
             int cell_y_offset = 0;
             int elem_idx      = 0;
             // Traverse block
             for(auto y = 0u; y < cells_per_block.height; ++y)
             {
                 for(auto x = 0u; x < num_bins_per_block_x; ++x)
                 {
                     int idx         = x + cell_y_offset + block_x_offset + block_y_offset;
                     block[elem_idx] = hog_space[idx];
                     elem_idx++;
                 }
                 cell_y_offset += hog_space.shape().x() * num_bins;
             }
             // Normalize block and write to descriptor
             hog_block_normalization_compute(block, desc, hog_info, block_idx);
             block_x_offset += cells_per_block_stride.width * num_bins;
             block_idx++;
         }
         block_y_offset += cells_per_block_stride.height * num_bins * hog_space.shape().x();
     }
 }
References Size2D::area(), HOGInfo::block_size(), HOGInfo::block_stride(), HOGInfo::cell_size(), arm_compute::F32, Size2D::height, HOGInfo::num_bins(), HOGInfo::num_cells_per_block(), HOGInfo::num_cells_per_block_stride(), SimpleTensor< T >::shape(), and Size2D::width.
Referenced by hog_descriptor(), and hog_multi_detection().
hog_block_normalization() [2/2]
template void arm_compute::test::validation::reference::hog_block_normalization (SimpleTensor< float > & desc, const SimpleTensor< float > & hog_space, const HOGInfo & hog_info)
hog_descriptor() [1/2]
SimpleTensor< T > hog_descriptor (const SimpleTensor< U > & src, BorderMode border_mode, U constant_border_value, const HOGInfo & hog_info)
Definition at line 226 of file HOGDescriptor.cpp.
 {
     SimpleTensor<int16_t> grad_x;
     SimpleTensor<int16_t> grad_y;
     // Create tensor info for HOG descriptor
     TensorInfo      desc_info(hog_info, src.shape().x(), src.shape().y());
     SimpleTensor<T> desc(desc_info.tensor_shape(), DataType::F32, desc_info.num_channels());
     // Create HOG space tensor (num_cells_x, num_cells_y)
     TensorShape hog_space_shape(src.shape().x() / hog_info.cell_size().width,
                                 src.shape().y() / hog_info.cell_size().height);
     // For each cell a histogram with a num_bins is created
     TensorInfo      info_hog_space(hog_space_shape, hog_info.num_bins(), DataType::F32);
     SimpleTensor<T> hog_space(info_hog_space.tensor_shape(), DataType::F32, info_hog_space.num_channels());
     // Calculate derivative
     std::tie(grad_x, grad_y) = derivative<int16_t>(src, border_mode, constant_border_value, GradientDimension::GRAD_XY);
     // For each cell create histogram based on magnitude and phase
     hog_orientation_binning(magnitude(grad_x, grad_y, MagnitudeType::L2NORM),
                             phase(grad_x, grad_y, hog_info.phase_type()),
                             hog_space,
                             hog_info);
     // Normalize histograms based on block size
     hog_block_normalization(desc, hog_space, hog_info);
     return desc;
 }
References arm_compute::test::validation::border_mode, HOGInfo::cell_size(), arm_compute::F32, arm_compute::GRAD_XY, Size2D::height, hog_block_normalization(), hog_orientation_binning(), arm_compute::L2NORM, magnitude(), HOGInfo::num_bins(), phase(), HOGInfo::phase_type(), arm_compute::test::validation::src, and Size2D::width.
hog_descriptor() [2/2]
template SimpleTensor<float> arm_compute::test::validation::reference::hog_descriptor (const SimpleTensor< uint8_t > & src, BorderMode border_mode, uint8_t constant_border_value, const HOGInfo & hog_info)
hog_detector() [1/2]
std::vector< DetectionWindow > hog_detector (const SimpleTensor< T > & src, const std::vector< T > & descriptor, unsigned int max_num_detection_windows, const HOGInfo & hog_info, const Size2D & detection_window_stride, float threshold, uint16_t idx_class)
Definition at line 48 of file HOGDetector.cpp.
 {
     ARM_COMPUTE_ERROR_ON_MSG((detection_window_stride.width % hog_info.block_stride().width != 0),
                              "Detection window stride width must be multiple of block stride width");
     ARM_COMPUTE_ERROR_ON_MSG((detection_window_stride.height % hog_info.block_stride().height != 0),
                              "Detection window stride height must be multiple of block stride height");
     // Create vector for identifying each detection window
     std::vector<DetectionWindow> windows;
     // Calculate detection window step
     const Size2D window_step(detection_window_stride.width / hog_info.block_stride().width,
                              detection_window_stride.height / hog_info.block_stride().height);
     // Calculate number of detection windows
     const Size2D num_windows = num_detection_windows(src.shape(), window_step, hog_info);
     // Calculate detection window and row offsets in feature vector
     const size_t src_offset_x   = window_step.width * hog_info.num_bins() * hog_info.num_cells_per_block().area();
     const size_t src_offset_y   = window_step.height * hog_info.num_bins() * hog_info.num_cells_per_block().area() * src.shape().x();
     const size_t src_offset_row = src.num_channels() * src.shape().x();
     // Calculate detection window attributes
     const Size2D       num_block_positions_per_detection_window = hog_info.num_block_positions_per_image(hog_info.detection_window_size());
     const unsigned int num_bins_per_descriptor_x                = num_block_positions_per_detection_window.width * src.num_channels();
     const unsigned int num_blocks_per_descriptor_y              = num_block_positions_per_detection_window.height;
     ARM_COMPUTE_ERROR_ON((num_bins_per_descriptor_x * num_blocks_per_descriptor_y + 1) != hog_info.descriptor_size());
     size_t win_id = 0;
     // Traverse feature vector in detection window steps
     for(auto win_y = 0u, offset_y = 0u; win_y < num_windows.height; win_y += window_step.height, offset_y += src_offset_y)
     {
         for(auto win_x = 0u, offset_x = 0u; win_x < num_windows.width; win_x += window_step.width, offset_x += src_offset_x)
         {
             // Reset the score
             float score = 0.0f;
             // Traverse detection window
             for(auto y = 0u, offset_row = 0u; y < num_blocks_per_descriptor_y; ++y, offset_row += src_offset_row)
             {
                 const int bin_offset = y * num_bins_per_descriptor_x;
                 for(auto x = 0u; x < num_bins_per_descriptor_x; ++x)
                 {
                     // Compute Linear SVM
                     const float a = src[x + offset_x + offset_y + offset_row];
                     const float b = descriptor[x + bin_offset];
                     score += a * b;
                 }
             }
             // Add the bias. The bias is located at the position (descriptor_size() - 1)
             score += descriptor[num_bins_per_descriptor_x * num_blocks_per_descriptor_y];
             if(score > threshold)
             {
                 DetectionWindow window;
                 if(win_id++ < max_num_detection_windows)
                 {
                     window.x         = win_x * hog_info.block_stride().width;
                     window.y         = win_y * hog_info.block_stride().height;
                     window.width     = hog_info.detection_window_size().width;
                     window.height    = hog_info.detection_window_size().height;
                     window.idx_class = idx_class;
                     window.score     = score;
                     windows.push_back(window);
                 }
             }
         }
     }
     return windows;
 }
References Size2D::area(), ARM_COMPUTE_ERROR_ON, ARM_COMPUTE_ERROR_ON_MSG, arm_compute::test::validation::b, HOGInfo::block_stride(), HOGInfo::descriptor_size(), HOGInfo::detection_window_size(), Size2D::height, DetectionWindow::height, DetectionWindow::idx_class, HOGInfo::num_bins(), HOGInfo::num_block_positions_per_image(), HOGInfo::num_cells_per_block(), DetectionWindow::score, arm_compute::test::validation::src, threshold(), Size2D::width, DetectionWindow::width, DetectionWindow::x, and DetectionWindow::y.
Referenced by hog_multi_detection().
hog_detector() [2/2]
template std::vector<DetectionWindow> arm_compute::test::validation::reference::hog_detector (const SimpleTensor< float > & src, const std::vector< float > & descriptor, unsigned int max_num_detection_windows, const HOGInfo & hog_info, const Size2D & detection_window_stride, float threshold, uint16_t idx_class)
hog_multi_detection() [1/2]
std::vector< DetectionWindow > hog_multi_detection (const SimpleTensor< T > & src, BorderMode border_mode, T constant_border_value, const std::vector< HOGInfo > & models, std::vector< std::vector< float >> descriptors, unsigned int max_num_detection_windows, float threshold, bool non_maxima_suppression, float min_distance)
Definition at line 138 of file HOGMultiDetection.cpp.
 {
     ARM_COMPUTE_ERROR_ON(descriptors.size() != models.size());
     validate_models(models);
     const size_t width      = src.shape().x();
     const size_t height     = src.shape().y();
     const size_t num_models = models.size();
     // Initialize previous values
     size_t prev_num_bins     = models[0].num_bins();
     Size2D prev_cell_size    = models[0].cell_size();
     Size2D prev_block_size   = models[0].block_size();
     Size2D prev_block_stride = models[0].block_stride();
     std::vector<size_t> input_orient_bin;
     std::vector<size_t> input_hog_detect;
     std::vector<std::pair<size_t, size_t>> input_block_norm;
     input_orient_bin.push_back(0);
     input_hog_detect.push_back(0);
     input_block_norm.emplace_back(0, 0);
     // Iterate through the number of models and check if orientation binning
     // and block normalization steps can be skipped
     for(size_t i = 1; i < num_models; ++i)
     {
         size_t cur_num_bins     = models[i].num_bins();
         Size2D cur_cell_size    = models[i].cell_size();
         Size2D cur_block_size   = models[i].block_size();
         Size2D cur_block_stride = models[i].block_stride();
         // Check if binning and normalization steps are required
         if((cur_num_bins != prev_num_bins) || (cur_cell_size.width != prev_cell_size.width) || (cur_cell_size.height != prev_cell_size.height))
         {
             prev_num_bins     = cur_num_bins;
             prev_cell_size    = cur_cell_size;
             prev_block_size   = cur_block_size;
             prev_block_stride = cur_block_stride;
             // Compute orientation binning and block normalization. Update input to process
             input_orient_bin.push_back(i);
             input_block_norm.emplace_back(i, input_orient_bin.size() - 1);
         }
         else if((cur_block_size.width != prev_block_size.width) || (cur_block_size.height != prev_block_size.height) || (cur_block_stride.width != prev_block_stride.width)
                 || (cur_block_stride.height != prev_block_stride.height))
         {
             prev_block_size   = cur_block_size;
             prev_block_stride = cur_block_stride;
             // Compute block normalization. Update input to process
             input_block_norm.emplace_back(i, input_orient_bin.size() - 1);
         }
         // Update input to process for hog detector
         input_hog_detect.push_back(input_block_norm.size() - 1);
     }
     size_t num_orient_bin = input_orient_bin.size();
     size_t num_block_norm = input_block_norm.size();
     size_t num_hog_detect = input_hog_detect.size();
     std::vector<SimpleTensor<float>> hog_spaces(num_orient_bin);
     std::vector<SimpleTensor<float>> hog_norm_spaces(num_block_norm);
     // Calculate derivative
     SimpleTensor<int16_t> grad_x;
     SimpleTensor<int16_t> grad_y;
     std::tie(grad_x, grad_y) = derivative<int16_t>(src, border_mode, constant_border_value, GradientDimension::GRAD_XY);
     // Calculate magnitude and phase
     SimpleTensor<int16_t> _mag   = magnitude(grad_x, grad_y, MagnitudeType::L2NORM);
     SimpleTensor<uint8_t> _phase = phase(grad_x, grad_y, models[0].phase_type());
     // Calculate Tensors for the HOG space and orientation binning
     for(size_t i = 0; i < num_orient_bin; ++i)
     {
         const size_t idx_multi_hog = input_orient_bin[i];
         const size_t num_bins    = models[idx_multi_hog].num_bins();
         const size_t num_cells_x = width / models[idx_multi_hog].cell_size().width;
         const size_t num_cells_y = height / models[idx_multi_hog].cell_size().height;
         // TensorShape of hog space
         TensorShape hog_space_shape(num_cells_x, num_cells_y);
         // Initialise HOG space
         TensorInfo info_hog_space(hog_space_shape, num_bins, DataType::F32);
         hog_spaces.at(i) = SimpleTensor<float>(info_hog_space.tensor_shape(), DataType::F32, info_hog_space.num_channels());
         // For each cell create histogram based on magnitude and phase
         hog_orientation_binning(_mag, _phase, hog_spaces[i], models[idx_multi_hog]);
     }
     // Calculate Tensors for the normalized HOG space and block normalization
     for(size_t i = 0; i < num_block_norm; ++i)
     {
         const size_t idx_multi_hog  = input_block_norm[i].first;
         const size_t idx_orient_bin = input_block_norm[i].second;
         // Create tensor info for HOG descriptor
         TensorInfo tensor_info(models[idx_multi_hog], src.shape().x(), src.shape().y());
         hog_norm_spaces.at(i) = SimpleTensor<float>(tensor_info.tensor_shape(), DataType::F32, tensor_info.num_channels());
         // Normalize histograms based on block size
         hog_block_normalization(hog_norm_spaces[i], hog_spaces[idx_orient_bin], models[idx_multi_hog]);
     }
     std::vector<DetectionWindow> multi_windows;
     // Calculate Detection Windows for HOG detector
     for(size_t i = 0; i < num_hog_detect; ++i)
     {
         const size_t idx_block_norm = input_hog_detect[i];
         // NOTE: Detection window stride fixed to block stride
         const Size2D detection_window_stride = models[i].block_stride();
         std::vector<DetectionWindow> windows = hog_detector(hog_norm_spaces[idx_block_norm], descriptors[i],
                                                             max_num_detection_windows, models[i], detection_window_stride, threshold, i);
         multi_windows.insert(multi_windows.end(), windows.begin(), windows.end());
     }
     // Suppress Non-maxima detection windows
     if(non_maxima_suppression)
     {
         detection_windows_non_maxima_suppression(multi_windows, min_distance);
     }
     return multi_windows;
 }
References ARM_COMPUTE_ERROR_ON, arm_compute::test::validation::border_mode, detection_windows_non_maxima_suppression(), arm_compute::F32, arm_compute::GRAD_XY, Size2D::height, hog_block_normalization(), hog_detector(), hog_orientation_binning(), arm_compute::L2NORM, magnitude(), non_maxima_suppression(), TensorInfo::num_channels(), phase(), arm_compute::test::validation::src, TensorInfo::tensor_shape(), threshold(), and Size2D::width.
hog_multi_detection() [2/2]
template std::vector<DetectionWindow> arm_compute::test::validation::reference::hog_multi_detection (const SimpleTensor< uint8_t > & src, BorderMode border_mode, uint8_t constant_border_value, const std::vector< HOGInfo > & models, std::vector< std::vector< float >> descriptors, unsigned int max_num_detection_windows, float threshold, bool non_maxima_suppression, float min_distance)
hog_orientation_binning() [1/2]
void hog_orientation_binning (const SimpleTensor< T > & mag, const SimpleTensor< U > & phase, SimpleTensor< V > & hog_space, const HOGInfo & hog_info)
Definition at line 117 of file HOGDescriptor.cpp.
 {
     const Size2D &cell_size = hog_info.cell_size();
     const size_t num_bins     = hog_info.num_bins();
     const size_t shape_width  = hog_space.shape().x() * hog_info.cell_size().width;
     const size_t shape_height = hog_space.shape().y() * hog_info.cell_size().height;
     TensorShape cell_shape(cell_size.width, cell_size.height);
     SimpleTensor<V> mag_cell(cell_shape, DataType::F32);
     SimpleTensor<V> phase_cell(cell_shape, DataType::F32);
     int cell_idx = 0;
     int y_offset = 0;
     // Traverse shape
     for(auto sy = cell_size.height; sy <= shape_height; sy += cell_size.height)
     {
         int x_offset = 0;
         for(auto sx = cell_size.width; sx <= shape_width; sx += cell_size.width)
         {
             int row_idx  = 0;
             int elem_idx = 0;
             // Traverse cell
             for(auto y = 0u; y < cell_size.height; ++y)
             {
                 for(auto x = 0u; x < cell_size.width; ++x)
                 {
                     int shape_idx        = x + row_idx + x_offset + y_offset;
                     mag_cell[elem_idx]   = mag[shape_idx];
                     phase_cell[elem_idx] = phase[shape_idx];
                     elem_idx++;
                 }
                 row_idx += shape_width;
             }
             // Partition magnitude values into bins based on phase values
             std::vector<V> bins(num_bins);
             hog_orientation_compute(mag_cell, phase_cell, bins, hog_info);
             for(size_t i = 0; i < num_bins; ++i)
             {
                 hog_space[cell_idx * num_bins + i] = bins[i];
             }
             x_offset += cell_size.width;
             cell_idx++;
         }
         y_offset += (cell_size.height * shape_width);
     }
 }
References HOGInfo::cell_size(), arm_compute::F32, Size2D::height, HOGInfo::num_bins(), phase(), SimpleTensor< T >::shape(), and Size2D::width.
Referenced by hog_descriptor(), and hog_multi_detection().
hog_orientation_binning() [2/2]
template void arm_compute::test::validation::reference::hog_orientation_binning (const SimpleTensor< int16_t > & mag, const SimpleTensor< uint8_t > & phase, SimpleTensor< float > & hog_space, const HOGInfo & hog_info)
im2col() [1/4]
void im2col (const SimpleTensor< T > & src, SimpleTensor< T > & dst, const Size2D & kernel_dims, const PadStrideInfo & conv_info, bool has_bias, unsigned int num_groups)
Definition at line 142 of file Im2Col.cpp.
 {
     switch(src.data_layout())
     {
         case DataLayout::NCHW:
         {
             im2col_nchw(src, dst, kernel_dims, conv_info, has_bias, num_groups);
             break;
         }
         case DataLayout::NHWC:
         {
             im2col_nhwc(src, dst, kernel_dims, conv_info, has_bias);
             break;
         }
         default:
         {
             ARM_COMPUTE_ERROR("Not supported.");
             break;
         }
     }
 }
References ARM_COMPUTE_ERROR, arm_compute::test::validation::conv_info, arm_compute::test::validation::dst, arm_compute::test::validation::has_bias, im2col_nchw(), im2col_nhwc(), arm_compute::NCHW, arm_compute::NHWC, arm_compute::test::validation::num_groups, and arm_compute::test::validation::src.
im2col() [2/4]
template void arm_compute::test::validation::reference::im2col (const SimpleTensor< uint8_t > & src, SimpleTensor< uint8_t > & dst, const Size2D & kernel_dims, const PadStrideInfo & conv_info, bool has_bias, unsigned int num_groups)
im2col() [3/4]
template void arm_compute::test::validation::reference::im2col (const SimpleTensor< half > & src, SimpleTensor< half > & dst, const Size2D & kernel_dims, const PadStrideInfo & conv_info, bool has_bias, unsigned int num_groups)
im2col() [4/4]
template void arm_compute::test::validation::reference::im2col (const SimpleTensor< float > & src, SimpleTensor< float > & dst, const Size2D & kernel_dims, const PadStrideInfo & conv_info, bool has_bias, unsigned int num_groups)
im2col_nchw()
void arm_compute::test::validation::reference::im2col_nchw (const SimpleTensor< T > & src, SimpleTensor< T > & dst, const Size2D & kernel_dims, const PadStrideInfo & conv_info, bool has_bias, unsigned int num_groups)
Definition at line 39 of file Im2Col.cpp.
 {
     ARM_COMPUTE_ERROR_ON(src.data_layout() != DataLayout::NCHW);
     const int stride_x      = conv_info.stride().first;
     const int stride_y      = conv_info.stride().second;
     const int kernel_width  = kernel_dims.width;
     const int kernel_height = kernel_dims.height;
     const int pad_x         = conv_info.pad().first;
     const int pad_y         = conv_info.pad().second;
     const int src_width     = src.shape().x();
     const int src_height    = src.shape().y();
     const int src_channels  = src.shape().z();
     const int batches       = src.shape().total_size_upper(3);
     const int dst_height    = dst.shape().y();
     const int pad_val       = is_data_type_quantized_asymmetric(src.data_type()) ? src.quantization_info().uniform().offset : 0;
     int       dst_idx       = 0;
     // Compute width and height of the convolved tensors
     std::pair<unsigned int, unsigned int> convolved_dims = scaled_dimensions(src_width, src_height, kernel_dims.width, kernel_dims.height, conv_info);
     for(int b = 0; b < batches; ++b)
     {
         for(int g = 0; g < static_cast<int>(num_groups); ++g)
         {
             const int first_group_ch = g * (src_channels / num_groups);
             const int last_group_ch  = (g + 1) * (src_channels / num_groups);
             for(int yo = 0; yo < dst_height; ++yo)
             {
                 // Compute input spatial coordinates
                 const int xi = (yo % convolved_dims.first) * stride_x;
                 const int yi = (yo / convolved_dims.first) * stride_y;
                 for(int ci = first_group_ch; ci < last_group_ch; ++ci)
                 {
                     for(int yk = 0; yk < kernel_height; ++yk)
                     {
                         for(int xk = 0; xk < kernel_width; ++xk)
{
                             dst[dst_idx++] = tensor_elem_at(src, Coordinates(xi + xk - pad_x, yi + yk - pad_y, ci, b), BorderMode::CONSTANT, static_cast<T>(pad_val));
                         }
                     }
                 }
                 if(has_bias)
                 {
                     dst[dst_idx++] = static_cast<T>(1);
                 }
             }
         }
     }
 }
References ARM_COMPUTE_ERROR_ON, arm_compute::test::validation::b, arm_compute::CONSTANT, arm_compute::test::validation::conv_info, arm_compute::test::validation::dst, arm_compute::test::validation::has_bias, Size2D::height, arm_compute::is_data_type_quantized_asymmetric(), arm_compute::NCHW, arm_compute::test::validation::num_groups, arm_compute::scaled_dimensions(), arm_compute::test::validation::src, arm_compute::test::validation::tensor_elem_at(), and Size2D::width.
Referenced by im2col().
im2col_nhwc()
void arm_compute::test::validation::reference::im2col_nhwc (const SimpleTensor< T > & src, SimpleTensor< T > & dst, const Size2D & kernel_dims, const PadStrideInfo & conv_info, bool has_bias)
Definition at line 93 of file Im2Col.cpp.
 {
     ARM_COMPUTE_ERROR_ON(src.data_layout() != DataLayout::NHWC);
     const int stride_x      = conv_info.stride().first;
     const int stride_y      = conv_info.stride().second;
     const int kernel_width  = kernel_dims.width;
     const int kernel_height = kernel_dims.height;
     const int pad_x         = conv_info.pad().first;
     const int pad_y         = conv_info.pad().second;
     const int src_width     = src.shape().y();
     const int src_height    = src.shape().z();
     const int src_channels  = src.shape().x();
     const int batches       = src.shape().total_size_upper(3);
     const int dst_width     = has_bias ? dst.shape().x() - 1 : dst.shape().x();
     const int dst_height    = dst.shape().y();
     const int pad_val       = is_data_type_quantized_asymmetric(src.data_type()) ? src.quantization_info().uniform().offset : 0;
     // Compute width and height of the convolved tensors
     std::pair<unsigned int, unsigned int> convolved_dims = scaled_dimensions(src_width, src_height, kernel_dims.width, kernel_dims.height, conv_info);
     for(int b = 0; b < batches; ++b)
     {
         for(int yo = 0; yo < dst_height; ++yo)
         {
             // Compute input spatial coordinates
             const int xi = (yo % convolved_dims.first) * stride_x;
             const int yi = (yo / convolved_dims.first) * stride_y;
             for(int ci = 0; ci < src_channels; ++ci)
             {
                 for(int yk = 0; yk < kernel_height; ++yk)
                 {
                     for(int xk = 0; xk < kernel_width; ++xk)
                     {
                         dst[ci + (xk + yk * kernel_width) * src_channels + yo * dst.shape().x() + b * dst.shape().x() * dst.shape().y()] = tensor_elem_at(src, Coordinates(ci, xi + xk - pad_x, yi + yk - pad_y, b),
                                                                                                                                            BorderMode::CONSTANT, static_cast<T>(pad_val));
                     }
                 }
             }
             if(has_bias)
             {
                 dst[dst_width + yo * dst.shape().x() + b * dst.shape().x() * dst.shape().y()] = static_cast<T>(1);
             }
         }
     }
 }
References ARM_COMPUTE_ERROR_ON, arm_compute::test::validation::b, arm_compute::CONSTANT, arm_compute::test::validation::conv_info, arm_compute::test::validation::dst, arm_compute::test::validation::has_bias, Size2D::height, arm_compute::is_data_type_quantized_asymmetric(), arm_compute::NHWC, arm_compute::scaled_dimensions(), arm_compute::test::validation::src, arm_compute::test::validation::tensor_elem_at(), and Size2D::width.
Referenced by im2col().
integral_image() [1/2]
SimpleTensor< uint32_t > integral_image (const SimpleTensor< T > & src)
Definition at line 35 of file IntegralImage.cpp.
 {
     SimpleTensor<uint32_t> dst(src.shape(), DataType::U32);
     // Length of dimensions
     const size_t width  = src.shape().x();
     const size_t height = src.shape().y();
     const size_t depth  = src.shape().total_size_upper(2);
     const size_t image_size = width * height;
     for(size_t z = 0; z < depth; ++z)
     {
         size_t current_image = z * image_size;
         //First element of each image
         dst[current_image] = src[current_image];
         // First row of each image (add only pixel on the left)
         for(size_t x = 1; x < width; ++x)
         {
             dst[current_image + x] = static_cast<uint32_t>(src[current_image + x]) + dst[current_image + x - 1];
         }
         // Subsequent rows
         for(size_t y = 1; y < height; ++y)
         {
             size_t current_row = current_image + (width * y);
             // First element of each row (add only pixel up)
             dst[current_row] = static_cast<uint32_t>(src[current_row]) + dst[current_row - width];
             // Following row elements
             for(size_t x = 1; x < width; ++x)
             {
                 size_t current_pixel = current_row + x;
                 // out = in + up(out) + left(out) - up_left(out)
                 dst[current_pixel] = static_cast<uint32_t>(src[current_pixel]) + dst[current_pixel - 1]
                                      + dst[current_pixel - width] - dst[current_pixel - width - 1];
             }
         }
     }
     return dst;
 }
References arm_compute::test::validation::dst, arm_compute::test::validation::src, and arm_compute::U32.
integral_image() [2/2]
template SimpleTensor<uint32_t> arm_compute::test::validation::reference::integral_image (const SimpleTensor< uint8_t > & src)
l2_normalize() [1/3]
SimpleTensor< T > l2_normalize (const SimpleTensor< T > & src, unsigned int axis, float epsilon)
Definition at line 51 of file L2NormalizeLayer.cpp.
 {
     // Create reference
     SimpleTensor<T> dst{ src.shape(), src.data_type() };
     // Reduce across given axis
     SimpleTensor<T> sum = reduction_operation<T, T>(src, get_output_shape(src.shape(), axis), axis, ReductionOperation::SUM_SQUARE);
     // Compute reference
     const int upper_dims     = src.shape().total_size_upper(axis + 1);
     const int lower_dims     = src.shape().total_size_lower(axis + 1);
     const int lower_dims_sum = sum.shape().total_size_lower(axis + 1);
     for(int du = 0; du < upper_dims; ++du)
     {
         const T *src_row_ptr = src.data() + du * lower_dims;
         T       *dst_row_ptr = dst.data() + du * lower_dims;
         switch(axis)
         {
             case 0:
             {
                 const int elems               = src.shape()[0];
                 const T   normalization_value = sqrt(std::max(sum[du], static_cast<T>(epsilon)));
                 std::transform(src_row_ptr, src_row_ptr + elems, dst_row_ptr, [normalization_value](T val)
                 {
                     return val / normalization_value;
                 });
             }
             break;
             case 1:
             case 2:
             {
                 for(int ld = 0; ld < lower_dims; ++ld)
                 {
                     const T normalization_value = sqrt(std::max(sum[ld % lower_dims_sum + du * lower_dims_sum], static_cast<T>(epsilon)));
                     dst_row_ptr[ld]             = src_row_ptr[ld] / normalization_value;
                 }
             }
             break;
             default:
                 ARM_COMPUTE_ERROR("Axis not supported");
         }
     }
     return dst;
 }
References ARM_COMPUTE_ERROR, arm_compute::test::validation::axis, arm_compute::test::validation::dst, epsilon, arm_compute::test::validation::src, sum(), and arm_compute::SUM_SQUARE.
l2_normalize() [2/3]
template SimpleTensor<float> arm_compute::test::validation::reference::l2_normalize (const SimpleTensor< float > & src, unsigned int axis, float epsilon)
l2_normalize() [3/3]
template SimpleTensor<half> arm_compute::test::validation::reference::l2_normalize (const SimpleTensor< half > & src, unsigned int axis, float epsilon)
laplacian_pyramid() [1/2]
std::vector< SimpleTensor< U > > laplacian_pyramid (const SimpleTensor< T > & src, SimpleTensor< U > & dst, size_t num_levels, BorderMode border_mode, uint8_t constant_border_value)
Definition at line 40 of file LaplacianPyramid.cpp.
 {
     std::vector<SimpleTensor<T>> pyramid_conv;
     std::vector<SimpleTensor<U>> pyramid_dst;
     // First, a Gaussian pyramid with SCALE_PYRAMID_HALF is created
     std::vector<SimpleTensor<T>> gaussian_level_pyramid = reference::gaussian_pyramid_half(src, border_mode, constant_border_value, num_levels);
     // For each level i, the corresponding image Ii is blurred with Gaussian 5x5
     // filter, and the difference between the two images is the corresponding
     // level Li of the Laplacian pyramid
     for(size_t i = 0; i < num_levels; ++i)
     {
         const SimpleTensor<T> level_filtered = reference::gaussian5x5(gaussian_level_pyramid[i], border_mode, constant_border_value);
         pyramid_conv.push_back(level_filtered);
         const SimpleTensor<U> level_filtered_converted = depth_convert<T, U>(level_filtered, DataType::S16, ConvertPolicy::WRAP, 0);
         const SimpleTensor<U> gaussian_level_converted = depth_convert<T, U>(gaussian_level_pyramid[i], DataType::S16, ConvertPolicy::WRAP, 0);
         const SimpleTensor<U> level_sub = reference::arithmetic_operation<U>(reference::ArithmeticOperation::SUB, gaussian_level_converted, level_filtered_converted, dst.data_type(), ConvertPolicy::WRAP);
         pyramid_dst.push_back(level_sub);
     }
     // Return the lowest resolution image and the pyramid
     dst = depth_convert<T, U>(pyramid_conv[num_levels - 1], DataType::S16, ConvertPolicy::WRAP, 0);
     return pyramid_dst;
 }
References arm_compute::test::validation::border_mode, arm_compute::test::validation::dst, gaussian5x5(), gaussian_pyramid_half(), arm_compute::S16, arm_compute::test::validation::src, SUB, and arm_compute::WRAP.
Referenced by arm_compute::test::validation::DATA_TEST_CASE().
laplacian_pyramid() [2/2]
template std::vector<SimpleTensor<int16_t> > arm_compute::test::validation::reference::laplacian_pyramid (const SimpleTensor< uint8_t > & src, SimpleTensor< int16_t > & dst, size_t num_levels, BorderMode border_mode, uint8_t constant_border_value)
Referenced by arm_compute::test::validation::DATA_TEST_CASE().
laplacian_reconstruct() [1/2]
SimpleTensor< U > laplacian_reconstruct (const std::vector< SimpleTensor< T >> & pyramid, const SimpleTensor< T > & low_res, BorderMode border_mode, T constant_border_value)
Definition at line 40 of file LaplacianReconstruct.cpp.
 {
     std::vector<SimpleTensor<T>> tmp_pyramid(pyramid);
     const size_t   last_level = pyramid.size() - 1;
     const DataType data_type  = low_res.data_type();
     // input + L(n-1)
     tmp_pyramid[last_level] = reference::arithmetic_operation(reference::ArithmeticOperation::ADD, low_res, pyramid[last_level], data_type, ConvertPolicy::SATURATE);
     // Scale levels n-1 to 1, and add levels n-2 to 0
     for(size_t i = last_level; i-- > 0;)
     {
         const float scale_x = static_cast<float>(tmp_pyramid[i].shape().x()) / tmp_pyramid[i + 1].shape().x();
         const float scale_y = static_cast<float>(tmp_pyramid[i].shape().y()) / tmp_pyramid[i + 1].shape().y();
         tmp_pyramid[i] = reference::scale(tmp_pyramid[i + 1], scale_x, scale_y, InterpolationPolicy::NEAREST_NEIGHBOR,
                                           border_mode, constant_border_value, SamplingPolicy::CENTER, false);
         tmp_pyramid[i] = reference::arithmetic_operation(reference::ArithmeticOperation::ADD, tmp_pyramid[i], pyramid[i], data_type, ConvertPolicy::SATURATE);
     }
     return reference::depth_convert<T, U>(tmp_pyramid[0], DataType::U8, ConvertPolicy::SATURATE, 0);
 }
References ADD, arithmetic_operation(), arm_compute::test::validation::border_mode, arm_compute::CENTER, arm_compute::test::validation::data_type, SimpleTensor< T >::data_type(), arm_compute::NEAREST_NEIGHBOR, arm_compute::SATURATE, scale(), arm_compute::test::validation::shape, and arm_compute::U8.
laplacian_reconstruct() [2/2]
template SimpleTensor<uint8_t> arm_compute::test::validation::reference::laplacian_reconstruct (const std::vector< SimpleTensor< int16_t >> & pyramid, const SimpleTensor< int16_t > & low_res, BorderMode border_mode, int16_t constant_border_value)
Referenced by arm_compute::test::validation::DATA_TEST_CASE().
locally_connected() [1/2]
SimpleTensor< T > locally_connected (const SimpleTensor< T > & src, const SimpleTensor< T > & weights, const SimpleTensor< TB > & bias, const TensorShape & output_shape, const PadStrideInfo & info)
Definition at line 41 of file LocallyConnected.cpp.
 {
     // Create reference
     SimpleTensor<T> dst{ output_shape, src.data_type(), 1, src.quantization_info() };
     // Compute reference
     const int width_in  = src.shape().x();
     const int height_in = src.shape().y();
     const int depth_in  = src.shape().z();
     const int width_out  = dst.shape().x();
     const int height_out = dst.shape().y();
     const int depth_out  = dst.shape().z();
     const int width_weights  = weights.shape().x();
     const int height_weights = weights.shape().y();
     const int depth_weights  = weights.shape().z();
     const int pad_left  = info.pad_left();
     const int pad_top   = info.pad_top();
     const int stride_xi = info.stride().first;
     const int stride_yi = info.stride().second;
     auto output_wh = scaled_dimensions(width_in, height_in, width_weights, height_weights, info);
     const int start_xi    = width_weights / 2 - pad_left;
     const int start_yi    = height_weights / 2 - pad_top;
     const int end_xi      = output_wh.first * stride_xi;
     const int end_yi      = output_wh.second * stride_yi;
     const int num_batches = src.shape().total_size() / (width_in * height_in * depth_in);
     for(int r = 0; r < num_batches; ++r)
     {
         int count = 0;
         for(int yi = start_yi; yi < start_yi + end_yi; yi += stride_yi)
         {
             for(int xi = start_xi; xi < start_xi + end_xi; xi += stride_xi)
             {
                 for(int ofm = 0; ofm < depth_out; ++ofm)
                 {
                     // Compute input and output offsets
                     const int offset_in  = r * width_in * height_in * depth_in;
                     const int xo         = (xi - start_xi) / stride_xi;
                     const int yo         = (yi - start_yi) / stride_yi;
                     const int offset_out = xo + yo * width_out + ofm * width_out * height_out + r * width_out * height_out * depth_out;
                     ARM_COMPUTE_ASSERT(xo < width_out);
                     ARM_COMPUTE_ASSERT(yo < height_out);
                     // Compute 3D convolution
                     convolution_3d::detail::convolution3d(src, weights, bias, dst,
                                                           offset_in, count * width_weights * height_weights * depth_weights, count, offset_out,
                                                           xi, yi,
                                                           width_in, height_in, depth_in,
                                                           width_weights, height_weights);
                     count++;
                 }
             }
         }
     }
     return dst;
 }
References ARM_COMPUTE_ASSERT, arm_compute::test::validation::bias, arm_compute::test::convolution_3d::detail::convolution3d(), arm_compute::test::validation::dst, arm_compute::test::validation::info, arm_compute::test::validation::output_shape, arm_compute::test::validation::output_wh, arm_compute::scaled_dimensions(), arm_compute::test::validation::src, and arm_compute::test::validation::weights.
locally_connected() [2/2]
template SimpleTensor<float> arm_compute::test::validation::reference::locally_connected (const SimpleTensor< float > & src, const SimpleTensor< float > & weights, const SimpleTensor< float > & bias, const TensorShape & output_shape, const PadStrideInfo & info)
magnitude() [1/4]
SimpleTensor< T > magnitude (const SimpleTensor< T > & gx, const SimpleTensor< T > & gy, MagnitudeType magnitude_type)
Definition at line 35 of file Magnitude.cpp.
 {
     SimpleTensor<T> mag(gx.shape(), gx.data_type());
     using intermediate_type = typename common_promoted_unsigned_type<T>::intermediate_type;
     for(int i = 0; i < gx.num_elements(); ++i)
     {
         double val = 0.f;
         if(magnitude_type == MagnitudeType::L1NORM)
         {
             val = static_cast<intermediate_type>(std::abs(gx[i])) + static_cast<intermediate_type>(std::abs(gy[i]));
         }
         else // MagnitudeType::L2NORM
         {
             // Note: kernel saturates to uint32_t instead of intermediate_type for S32 format
             auto sum = static_cast<uint32_t>(gx[i] * gx[i]) + static_cast<uint32_t>(gy[i] * gy[i]);
             val      = std::sqrt(sum) + 0.5f;
         }
         mag[i] = saturate_cast<T>(val);
     }
     return mag;
 }
References SimpleTensor< T >::data_type(), arm_compute::L1NORM, SimpleTensor< T >::num_elements(), SimpleTensor< T >::shape(), and sum().
Referenced by CLGradientKernel::configure(), CLMagnitudePhaseKernel::configure(), NEMagnitudePhaseKernel< mag_type, phase_type >::configure(), NEGradientKernel::configure(), CLEdgeNonMaxSuppressionKernel::configure(), NEEdgeNonMaxSuppressionKernel::configure(), hog_descriptor(), hog_multi_detection(), magnitude_phase(), NEGradientKernel::run(), and NEEdgeNonMaxSuppressionKernel::run().
magnitude() [2/4]
template SimpleTensor<int16_t> arm_compute::test::validation::reference::magnitude (const SimpleTensor< int16_t > & gx, const SimpleTensor< int16_t > & gy, MagnitudeType magnitude_type)
magnitude() [3/4]
template SimpleTensor<int32_t> arm_compute::test::validation::reference::magnitude (const SimpleTensor< int32_t > & gx, const SimpleTensor< int32_t > & gy, MagnitudeType magnitude_type)
magnitude() [4/4]
template SimpleTensor<half_float::half> arm_compute::test::validation::reference::magnitude (const SimpleTensor< half_float::half > & gx, const SimpleTensor< half_float::half > & gy, MagnitudeType magnitude_type)
Referenced by arm_compute::test::validation::DATA_TEST_CASE().
mean_and_standard_deviation() [1/4]
std::pair< float, float > mean_and_standard_deviation (const SimpleTensor< T > & in)
Definition at line 35 of file MeanStdDev.cpp.
 {
     const int num_elements = in.num_elements();
     // Calculate mean
     float mean = std::accumulate(in.data(), in.data() + num_elements, 0.f) / num_elements;
     // Calculate standard deviation
     float std_dev = std::accumulate(in.data(), in.data() + num_elements, 0.f, [&mean](float a, float b)
     {
         return a + (mean - b) * (mean - b);
     });
     std_dev = std::sqrt(std_dev / num_elements);
     return std::make_pair(mean, std_dev);
 }
References accumulate(), arm_compute::test::validation::b, SimpleTensor< T >::data(), and SimpleTensor< T >::num_elements().
mean_and_standard_deviation() [2/4]
template std::pair<float, float> arm_compute::test::validation::reference::mean_and_standard_deviation (const SimpleTensor< uint8_t > & in)
mean_and_standard_deviation() [3/4]
template std::pair<float, float> arm_compute::test::validation::reference::mean_and_standard_deviation (const SimpleTensor< half > & in)
mean_and_standard_deviation() [4/4]
template std::pair<float, float> arm_compute::test::validation::reference::mean_and_standard_deviation (const SimpleTensor< float > & in)
mean_std_normalization_layer() [1/3]
SimpleTensor< T > mean_std_normalization_layer (const SimpleTensor< T > & src, float epsilon)
Definition at line 37 of file MeanStdDevNormalizationLayer.cpp.
 {
     // Create reference
     SimpleTensor<T> dst{ src.shape(), src.data_type(), 1 };
     const int cols       = src.shape()[0];
     const int batch_size = src.shape()[1];
     for(int i = 0; i < batch_size; ++i)
     {
         T sum    = static_cast<T>(0.f);
         T sum_sq = static_cast<T>(0.f);
         for(int j = 0; j < cols; ++j)
         {
             const T value = src[j + i * cols];
             sum += value;
             sum_sq += value * value;
         }
         const T mean       = sum / static_cast<T>(cols);
         const T var        = ((sum_sq / static_cast<T>(cols)) - (mean * mean)) + static_cast<T>(epsilon);
         const T stddev_inv = static_cast<T>(1.f) / static_cast<T>(std::sqrt(var));
         for(int j = 0; j < cols; ++j)
         {
             dst[j + i * cols] = (src[j + i * cols] - mean) * stddev_inv;
         }
     }
     return dst;
 }
References arm_compute::test::validation::dst, arm_compute::test::validation::src, and sum().
mean_std_normalization_layer() [2/3]
template SimpleTensor<float> arm_compute::test::validation::reference::mean_std_normalization_layer (const SimpleTensor< float > & src, float epsilon)
mean_std_normalization_layer() [3/3]
template SimpleTensor<half> arm_compute::test::validation::reference::mean_std_normalization_layer (const SimpleTensor< half > & src, float epsilon)
median3x3() [1/2]
SimpleTensor< T > median3x3 (const SimpleTensor< T > & src, BorderMode border_mode, T constant_border_value)
Definition at line 44 of file Median3x3.cpp.
 {
     SimpleTensor<T> dst(src.shape(), src.data_type());
     const int       size_tot_filter = filter_size * filter_size;
     for(int src_idx = 0; src_idx < src.num_elements(); ++src_idx)
     {
         std::array<T, size_tot_filter> filter_elems = { { 0 } };
         Coordinates id = index2coord(src.shape(), src_idx);
         const int   x  = id.x();
         const int   y  = id.y();
         for(int j = y - static_cast<int>(border_size.top), index = 0; j <= y + static_cast<int>(border_size.bottom); ++j)
         {
             for(int i = x - static_cast<int>(border_size.left); i <= x + static_cast<int>(border_size.right); ++i, ++index)
             {
                 id.set(0, i);
                 id.set(1, j);
                 filter_elems[index] = tensor_elem_at(src, id, border_mode, constant_border_value);
             }
         }
         std::sort(filter_elems.begin(), filter_elems.end());
         dst[src_idx] = filter_elems[size_tot_filter / 2];
     }
     return dst;
 }
References arm_compute::test::validation::border_mode, arm_compute::test::validation::dst, arm_compute::test::validation::filter_size, arm_compute::test::index2coord(), arm_compute::test::validation::src, arm_compute::test::validation::tensor_elem_at(), and Dimensions< T >::x().
median3x3() [2/2]
template SimpleTensor<uint8_t> arm_compute::test::validation::reference::median3x3 (const SimpleTensor< uint8_t > & src, BorderMode border_mode, uint8_t constant_border_value)
min_max_location() [1/4]
MinMaxLocationValues< T > min_max_location (const SimpleTensor< T > & src)
Definition at line 58 of file MinMaxLocation.cpp.
 {
     MinMaxLocationValues<T> dst;
     const size_t width = src.shape().x();
     compute_min_max<T>(src, dst.min, dst.max);
     Coordinates2D coord{ 0, 0 };
     for(int i = 0; i < src.num_elements(); ++i)
     {
         coord.x = static_cast<int32_t>(i % width);
         coord.y = static_cast<int32_t>(i / width);
         if(src[i] == dst.min)
         {
             dst.min_loc.push_back(coord);
         }
         if(src[i] == dst.max)
         {
             dst.max_loc.push_back(coord);
         }
     }
     return dst;
 }
References arm_compute::test::validation::dst, arm_compute::test::validation::src, and Coordinates2D::x.
min_max_location() [2/4]
template MinMaxLocationValues<uint8_t> arm_compute::test::validation::reference::min_max_location (const SimpleTensor< uint8_t > & src)
min_max_location() [3/4]
template MinMaxLocationValues<int16_t> arm_compute::test::validation::reference::min_max_location (const SimpleTensor< int16_t > & src)
min_max_location() [4/4]
template MinMaxLocationValues<float> arm_compute::test::validation::reference::min_max_location (const SimpleTensor< float > & src)
non_linear_filter() [1/2]
SimpleTensor< T > non_linear_filter (const SimpleTensor< T > & src, NonLinearFilterFunction function, unsigned int mask_size, MatrixPattern pattern, const uint8_t * mask, BorderMode border_mode, uint8_t constant_border_value)
Definition at line 36 of file NonLinearFilter.cpp.
 {
     SimpleTensor<T> dst(src.shape(), src.data_type());
     ARM_COMPUTE_ERROR_ON(pattern == MatrixPattern::OTHER && mask == nullptr);
     ARM_COMPUTE_UNUSED(pattern);
     using intermediate_type = typename common_promoted_signed_type<T>::intermediate_type;
     const int                      sq_mask_size   = mask_size * mask_size;
     const int                      half_mask_size = mask_size / 2;
     std::vector<intermediate_type> vals(sq_mask_size);
     intermediate_type              current_value = 0;
     const ValidRegion valid_region = shape_to_valid_region(src.shape(), border_mode == BorderMode::UNDEFINED, BorderSize(half_mask_size));
     for(int element_idx = 0, count = 0, index = 0; element_idx < src.num_elements(); ++element_idx, count = 0, index = 0)
     {
         Coordinates id = index2coord(src.shape(), element_idx);
         if(is_in_valid_region(valid_region, id))
         {
             int idx = id.x();
             int idy = id.y();
             for(int y = idy - half_mask_size; y <= idy + half_mask_size; ++y)
             {
                 for(int x = idx - half_mask_size; x <= idx + half_mask_size; ++x, ++index)
                 {
                     id.set(0, x);
                     id.set(1, y);
                     current_value = tensor_elem_at(src, id, border_mode, constant_border_value);
                     if(mask[index] == 255)
                     {
                         vals[count] = static_cast<intermediate_type>(current_value);
                         ++count;
                     }
                 }
             }
             std::sort(vals.begin(), vals.begin() + count);
             ARM_COMPUTE_ERROR_ON(count == 0);
             switch(function)
             {
                 case NonLinearFilterFunction::MIN:
                     dst[element_idx] = saturate_cast<T>(vals[0]);
                     break;
                 case NonLinearFilterFunction::MAX:
                     dst[element_idx] = saturate_cast<T>(vals[count - 1]);
                     break;
                 case NonLinearFilterFunction::MEDIAN:
                     dst[element_idx] = saturate_cast<T>(vals[count / 2]);
                     break;
                 default:
                     ARM_COMPUTE_ERROR("Unsupported NonLinearFilter function.");
             }
         }
     }
     return dst;
 }
References ARM_COMPUTE_ERROR, ARM_COMPUTE_ERROR_ON, ARM_COMPUTE_UNUSED, arm_compute::test::validation::border_mode, arm_compute::test::validation::dst, arm_compute::test::index2coord(), arm_compute::test::is_in_valid_region(), arm_compute::MAX, arm_compute::MEDIAN, arm_compute::MIN, arm_compute::OTHER, arm_compute::test::shape_to_valid_region(), arm_compute::test::validation::src, arm_compute::test::validation::tensor_elem_at(), arm_compute::UNDEFINED, arm_compute::test::validation::valid_region, and Dimensions< T >::x().
non_linear_filter() [2/2]
template SimpleTensor<uint8_t> arm_compute::test::validation::reference::non_linear_filter (const SimpleTensor< uint8_t > & src, NonLinearFilterFunction function, unsigned int mask_size, MatrixPattern pattern, const uint8_t * mask, BorderMode border_mode, uint8_t constant_border_value)
non_max_suppression()
SimpleTensor< int > non_max_suppression (const SimpleTensor< float > & bboxes, const SimpleTensor< float > & scores, SimpleTensor< int > & indices, unsigned int max_output_size, float score_threshold, float nms_threshold)
Definition at line 139 of file NonMaxSuppression.cpp.
 {
     const size_t                    num_boxes         = bboxes.shape().y();
     const size_t                    output_size       = std::min(static_cast<size_t>(max_output_size), num_boxes);
     const std::vector<CandidateBox> candidates_vector = get_candidates(scores, score_threshold);
     std::vector<int>                selected;
     for(const auto c : candidates_vector)
     {
         if(selected.size() == output_size)
         {
             break;
         }
         if(is_box_selected(c, bboxes, selected, nms_threshold))
         {
             selected.push_back(c.first);
         }
     }
     std::copy_n(selected.begin(), selected.size(), indices.data());
     for(unsigned int i = selected.size(); i < max_output_size; ++i)
     {
         indices[i] = -1;
     }
     return indices;
 }
References SimpleTensor< T >::data(), and SimpleTensor< T >::shape().
non_maxima_suppression() [1/3]
SimpleTensor< T > non_maxima_suppression (const SimpleTensor< T > & src, BorderMode border_mode, T constant_border_value)
Definition at line 38 of file NonMaximaSuppression.cpp.
 {
     constexpr int   block_size = 3;
     SimpleTensor<T> dst(src.shape(), src.data_type(), src.num_channels());
     ValidRegion     valid_region = shape_to_valid_region(src.shape(), border_mode == BorderMode::UNDEFINED, BorderSize(block_size / 2));
     for(int i = 0; i < src.num_elements(); ++i)
     {
         Coordinates coord = index2coord(src.shape(), i);
         int         x     = coord.x();
         int         y     = coord.y();
         if(!is_in_valid_region(valid_region, coord))
         {
             continue;
         }
         if(src[i] >= tensor_elem_at(src, Coordinates(x - 1, y - 1), border_mode, constant_border_value) && src[i] >= tensor_elem_at(src, Coordinates(x, y - 1), border_mode, constant_border_value)
            && src[i] >= tensor_elem_at(src, Coordinates(x + 1, y - 1), border_mode, constant_border_value) && src[i] >= tensor_elem_at(src, Coordinates(x - 1, y), border_mode, constant_border_value)
            && src[i] > tensor_elem_at(src, Coordinates(x + 1, y), border_mode, constant_border_value) && src[i] > tensor_elem_at(src, Coordinates(x - 1, y + 1), border_mode, constant_border_value)
            && src[i] > tensor_elem_at(src, Coordinates(x, y + 1), border_mode, constant_border_value) && src[i] > tensor_elem_at(src, Coordinates(x + 1, y + 1), border_mode, constant_border_value))
         {
             dst[i] = src[i];
         }
         else
         {
             dst[i] = T(0);
         }
     }
     return dst;
 }
References arm_compute::test::validation::border_mode, arm_compute::test::validation::dst, arm_compute::test::index2coord(), arm_compute::test::is_in_valid_region(), arm_compute::test::shape_to_valid_region(), arm_compute::test::validation::src, arm_compute::test::validation::tensor_elem_at(), arm_compute::UNDEFINED, arm_compute::test::validation::valid_region, Dimensions< T >::x(), and Dimensions< T >::y().
Referenced by CLHOGMultiDetection::configure(), NEHOGMultiDetection::configure(), fast_corners(), and hog_multi_detection().
non_maxima_suppression() [2/3]
template SimpleTensor<float> arm_compute::test::validation::reference::non_maxima_suppression (const SimpleTensor< float > & src, BorderMode border_mode, float constant_border_value)
non_maxima_suppression() [3/3]
template SimpleTensor<uint8_t> arm_compute::test::validation::reference::non_maxima_suppression (const SimpleTensor< uint8_t > & src, BorderMode border_mode, uint8_t constant_border_value)
normalization_layer() [1/3]
SimpleTensor< T > normalization_layer (const SimpleTensor< T > & src, NormalizationLayerInfo info)
Definition at line 37 of file NormalizationLayer.cpp.
 {
     // Create reference
     SimpleTensor<T> dst{ src.shape(), src.data_type(), 1 };
     // Compute reference
     const uint32_t norm_size = info.norm_size();
     NormType       type      = info.type();
     float          beta      = info.beta();
     uint32_t       kappa     = info.kappa();
     const int cols       = src.shape()[0];
     const int rows       = src.shape()[1];
     const int depth      = src.shape()[2];
     int       upper_dims = src.shape().total_size() / (cols * rows);
     float coeff       = info.scale_coeff();
     int   radius_cols = norm_size / 2;
     // IN_MAP_1D and CROSS_MAP normalize over a single axis only
     int radius_rows = (NormType::IN_MAP_2D == type) ? norm_size / 2 : 0;
     if(info.is_cross_map())
     {
         // Remove also depth from upper dimensions since it is the dimension we
         // want to use for normalization
         upper_dims /= depth;
         for(int r = 0; r < upper_dims; ++r)
         {
             for(int i = 0; i < rows; ++i)
             {
                 for(int k = 0; k < cols; ++k)
                 {
                     for(int l = 0; l < depth; ++l)
                     {
                         float accumulated_scale = 0.f;
                         for(int j = -radius_cols; j <= radius_cols; ++j)
{
                             const int z = l + j;
                             if(z >= 0 && z < depth)
{
                                 const T value = src[k + i * cols + z * rows * cols + r * cols * rows * depth];
                                 accumulated_scale += value * value;
                             }
                         }
                         dst[k + i * cols + l * rows * cols + r * cols * rows * depth] = kappa + accumulated_scale * coeff;
                     }
                 }
             }
         }
     }
     else
     {
         for(int r = 0; r < upper_dims; ++r)
         {
             for(int i = 0; i < rows; ++i)
             {
                 for(int k = 0; k < cols; ++k)
                 {
                     float accumulated_scale = 0.f;
                     for(int j = -radius_rows; j <= radius_rows; ++j)
                     {
                         const int y = i + j;
                         for(int l = -radius_cols; l <= radius_cols; ++l)
{
                             const int x = k + l;
                             if((x >= 0 && y >= 0) && (x < cols && y < rows))
{
                                 const T value = src[x + y * cols + r * cols * rows];
                                 accumulated_scale += value * value;
                             }
                         }
                     }
                     dst[k + i * cols + r * cols * rows] = kappa + accumulated_scale * coeff;
                 }
             }
         }
     }
     if(beta == 1.f)
     {
         for(int i = 0; i < dst.num_elements(); ++i)
         {
             dst[i] = src[i] / dst[i];
         }
     }
     else if(beta == 0.5f)
     {
         for(int i = 0; i < dst.num_elements(); ++i)
         {
             dst[i] = src[i] / std::sqrt(dst[i]);
         }
     }
     else
     {
         for(int i = 0; i < dst.num_elements(); ++i)
         {
             dst[i] = src[i] * std::exp(std::log(dst[i]) * -beta);
         }
     }
     return dst;
 }
References arm_compute::test::validation::dst, arm_compute::IN_MAP_2D, arm_compute::test::validation::info, and arm_compute::test::validation::src.
normalization_layer() [2/3]
template SimpleTensor<float> arm_compute::test::validation::reference::normalization_layer (const SimpleTensor< float > & src, NormalizationLayerInfo info)
normalization_layer() [3/3]
template SimpleTensor<half> arm_compute::test::validation::reference::normalization_layer (const SimpleTensor< half > & src, NormalizationLayerInfo info)
normalize_planar_yuv_layer() [1/3]
SimpleTensor< T > normalize_planar_yuv_layer (const SimpleTensor< T > & src, const SimpleTensor< T > & mean, const SimpleTensor< T > & std)
Definition at line 38 of file NormalizePlanarYUVLayer.cpp.
 {
     SimpleTensor<T> result(src.shape(), src.data_type());
     const auto cols       = static_cast<int>(src.shape()[0]);
     const auto rows       = static_cast<int>(src.shape()[1]);
     const auto depth      = static_cast<int>(src.shape()[2]);
     const int  upper_dims = src.shape().total_size() / (cols * rows * depth);
     for(int r = 0; r < upper_dims; ++r)
     {
         for(int i = 0; i < depth; ++i)
         {
             for(int k = 0; k < rows; ++k)
             {
                 for(int l = 0; l < cols; ++l)
                 {
                     const int pos = l + k * cols + i * rows * cols + r * cols * rows * depth;
                     result[pos]   = (src[pos] - mean[i]) / std[i];
                 }
             }
         }
     }
     return result;
 }
References arm_compute::test::validation::src.
normalize_planar_yuv_layer() [2/3]
template SimpleTensor<half> arm_compute::test::validation::reference::normalize_planar_yuv_layer (const SimpleTensor< half > & src, const SimpleTensor< half > & mean, const SimpleTensor< half > & std)
normalize_planar_yuv_layer() [3/3]
template SimpleTensor<float> arm_compute::test::validation::reference::normalize_planar_yuv_layer (const SimpleTensor< float > & src, const SimpleTensor< float > & mean, const SimpleTensor< float > & std)
normalize_planar_yuv_layer< uint8_t >()
SimpleTensor<uint8_t> arm_compute::test::validation::reference::normalize_planar_yuv_layer< uint8_t > (const SimpleTensor< uint8_t > & src, const SimpleTensor< uint8_t > & mean, const SimpleTensor< uint8_t > & std)
Definition at line 65 of file NormalizePlanarYUVLayer.cpp.
 {
     SimpleTensor<float>   src_tmp  = convert_from_asymmetric(src);
     SimpleTensor<float>   mean_tmp = convert_from_asymmetric(mean);
     SimpleTensor<float>   std_tmp  = convert_from_asymmetric(std);
     SimpleTensor<float>   dst_tmp  = normalize_planar_yuv_layer<float>(src_tmp, mean_tmp, std_tmp);
     SimpleTensor<uint8_t> dst      = convert_to_asymmetric(dst_tmp, src.quantization_info());
     return dst;
 }
References arm_compute::test::validation::convert_from_asymmetric(), arm_compute::test::validation::convert_to_asymmetric(), arm_compute::test::validation::dst, and arm_compute::test::validation::src.
optical_flow() [1/2]
std::vector< KeyPoint > optical_flow (const SimpleTensor< T > & old_input, const SimpleTensor< T > & new_input, const OpticalFlowParameters & params, size_t num_levels, const std::vector< KeyPoint > & old_points, const std::vector< KeyPoint > & new_points_estimates, BorderMode border_mode, uint8_t constant_border_value)
Definition at line 246 of file OpticalFlow.cpp.
 {
     const int    filter_size      = 3;    // scharr filter size
     const size_t max_iterations   = 1000; // fixed by kernel
     const size_t window_dimension = params.window_dimension;
     const size_t num_iterations   = (params.termination == Termination::TERM_CRITERIA_EPSILON) ? max_iterations : params.num_iterations;
     KeyPointArray new_points(old_points.size());
     InternalKeyPointArray old_points_internal = create_internal_keypoints(old_points);
     InternalKeyPointArray new_points_internal = create_internal_keypoints(new_points_estimates);
     SimpleTensor<int16_t> scharr_gx;
     SimpleTensor<int16_t> scharr_gy;
     // Create pyramids
     std::vector<SimpleTensor<T>> old_pyramid = gaussian_pyramid_half(old_input, border_mode, constant_border_value, num_levels);
     std::vector<SimpleTensor<T>> new_pyramid = gaussian_pyramid_half(new_input, border_mode, constant_border_value, num_levels);
     // Iterate over each level of the pyramid
     for(size_t idx = num_levels; idx > 0; --idx)
     {
         const size_t level = idx - 1;
         // Calculate scharr gradients
         std::tie(scharr_gx, scharr_gy) = scharr<int16_t, T>(old_pyramid[level], filter_size, border_mode, constant_border_value, GradientDimension::GRAD_XY);
         scale_tracked_points(level, num_levels, params.use_initial_estimate, old_points_internal, new_points_internal, old_points, new_points_estimates);
         // Calculate valid region based on image dimensions of current pyramid level
         const ValidRegion valid_region = shape_to_valid_region(old_pyramid[level].shape(), (border_mode == BorderMode::UNDEFINED), BorderSize(filter_size / 2));
         for(size_t i = 0; i < old_points.size(); ++i)
         {
             InternalKeyPoint &old_keypoint = old_points_internal.at(i);
             InternalKeyPoint &new_keypoint = new_points_internal.at(i);
             // Helper function for untracking keypoints when on the lowest pyramid level (high resolution)
             const auto untrack_keypoint = [&](bool predicate)
             {
                 if(predicate && (level == 0))
                 {
                     new_keypoint.tracking_status = false;
                     return true;
                 }
                 return predicate;
             };
             if(!old_keypoint.tracking_status)
             {
                 continue;
             }
             // Check if tracked coordinate is outside image coordinate
             if(untrack_keypoint(is_invalid_keypoint(old_keypoint, valid_region, window_dimension)))
             {
                 continue;
             }
             // Compute spatial derivative
             std::vector<int> bilinear_ix = compute_derivative(scharr_gx, old_keypoint, border_mode, constant_border_value, window_dimension, W_BITS);
             std::vector<int> bilinear_iy = compute_derivative(scharr_gy, old_keypoint, border_mode, constant_border_value, window_dimension, W_BITS);
             float A11 = 0.f;
             float A12 = 0.f;
             float A22 = 0.f;
             std::tie(A11, A12, A22) = compute_spatial_gradient_matrix(bilinear_ix, bilinear_iy);
             // Calculate criteria for lost tracking : Matrix A is invertible
             // 1. The determinant of the matrix is less than DETERMINANT_THRESHOLD
             // 2. The minimum eigenvalue of the matrix is less than EIGENVALUE_THRESHOLD
             const float trace_A      = A11 + A22;
             const float determinant  = A11 * A22 - A12 * A12;
             const float discriminant = (trace_A * trace_A) - 4.0f * (determinant);
             const float eigenvalue_A = (trace_A - std::sqrt(discriminant)) / 2.0f;
             // Divide by window_dimension squared to reduce the floating point accummulation error
             const float eigenvalue = eigenvalue_A / (window_dimension * window_dimension);
             // Check if it is a good point to track
             if(untrack_keypoint(eigenvalue < EIGENVALUE_THRESHOLD || determinant < DETERMINANT_THRESHOLD))
             {
                 continue;
             }
             float prev_delta_x = 0.f;
             float prev_delta_y = 0.f;
             for(size_t j = 0; j < num_iterations; ++j)
             {
                 // Check if tracked coordinate is outside image coordinate
                 if(untrack_keypoint(is_invalid_keypoint(new_keypoint, valid_region, window_dimension)))
                 {
                     break;
                 }
                 // Compute temporal derivative
                 std::vector<int> bilinear_it_old = compute_derivative(old_pyramid[level], old_keypoint, border_mode, constant_border_value, window_dimension, W_BITS - 5);
                 std::vector<int> bilinear_it_new = compute_derivative(new_pyramid[level], new_keypoint, border_mode, constant_border_value, window_dimension, W_BITS - 5);
                 double b1 = 0.f;
                 double b2 = 0.f;
                 std::tie(b1, b2) = compute_temporal_gradient_vector(bilinear_it_old, bilinear_it_new, bilinear_ix, bilinear_iy);
                 // Compute motion vector -> A^-1 * -b
                 const float delta_x = (A12 * b2 - A22 * b1) / determinant;
                 const float delta_y = (A12 * b1 - A11 * b2) / determinant;
                 // Update the new position
                 new_keypoint.x += delta_x;
                 new_keypoint.y += delta_y;
                 const float magnitude_squared = delta_x * delta_x + delta_y * delta_y;
                 // Check if termination criteria is EPSILON and if it is satisfied
                 if(magnitude_squared <= params.epsilon && (params.termination == Termination::TERM_CRITERIA_EPSILON || params.termination == Termination::TERM_CRITERIA_BOTH))
                 {
                     break;
                 }
                 // Check convergence analyzing the previous delta
                 if(j > 0 && (std::fabs(delta_x + prev_delta_x) < 0.01f && std::fabs(delta_y + prev_delta_y) < 0.01f))
                 {
                     new_keypoint.x -= delta_x * SCALE_PYRAMID_HALF;
                     new_keypoint.y -= delta_y * SCALE_PYRAMID_HALF;
                     break;
                 }
                 prev_delta_x = delta_x;
                 prev_delta_y = delta_y;
             }
         }
     }
     // Copy optical flow coordinates to output vector
     for(size_t i = 0; i < old_points.size(); ++i)
     {
         const InternalKeyPoint &new_keypoint = new_points_internal.at(i);
         new_points.at(i).x               = roundf(new_keypoint.x);
         new_points.at(i).y               = roundf(new_keypoint.y);
         new_points.at(i).tracking_status = new_keypoint.tracking_status ? 1 : 0;
     }
     return new_points;
 }
References arm_compute::test::validation::border_mode, OpticalFlowParameters::epsilon, arm_compute::test::validation::filter_size, gaussian_pyramid_half(), arm_compute::GRAD_XY, OpticalFlowParameters::num_iterations, arm_compute::SCALE_PYRAMID_HALF, arm_compute::test::validation::shape, arm_compute::test::shape_to_valid_region(), arm_compute::TERM_CRITERIA_BOTH, arm_compute::TERM_CRITERIA_EPSILON, OpticalFlowParameters::termination, InternalKeyPoint::tracking_status, arm_compute::UNDEFINED, OpticalFlowParameters::use_initial_estimate, arm_compute::test::validation::valid_region, W_BITS, OpticalFlowParameters::window_dimension, InternalKeyPoint::x, and InternalKeyPoint::y.
optical_flow() [2/2]
template std::vector<KeyPoint> arm_compute::test::validation::reference::optical_flow (const SimpleTensor< uint8_t > & old_input, const SimpleTensor< uint8_t > & new_input, const OpticalFlowParameters & params, size_t num_levels, const std::vector< KeyPoint > & old_points, const std::vector< KeyPoint > & new_points_estimates, BorderMode border_mode, uint8_t constant_border_value)
pad_layer() [1/8]
SimpleTensor< T > pad_layer (const SimpleTensor< T > & src, const PaddingList & paddings, const PixelValue const_value = PixelValue(), const PaddingMode mode = PaddingMode::CONSTANT)
Reference function to pad an ND tensor.
This function is not supposed to be optimized, but to clearly and naively execute the padding of a tensor
Parameters
[in] src Tensor to pad
[in] paddings Padding size in each dimension
[in] const_value Constant value to fill padding with
[in] mode [optional] Padding mode to use
Returns
The padded Tensor
Definition at line 39 of file PadLayer.cpp.
 {
     const DataType dst_data_type = src.data_type();
     const TensorShape orig_shape = src.shape();
     std::vector<PaddingInfo> paddings_extended = paddings;
     for(size_t i = paddings.size(); i < TensorShape::num_max_dimensions; ++i)
     {
         paddings_extended.emplace_back(PaddingInfo{ 0, 0 });
     }
     const TensorShape padded_shape = misc::shape_calculator::compute_padded_shape(orig_shape, paddings);
     SimpleTensor<T> dst(padded_shape, dst_data_type);
     // Reference algorithm: loop over the different dimension of the input.
     for(int idx = 0; idx < dst.num_elements(); ++idx)
     {
         const Coordinates coord = index2coord(padded_shape, idx);
         const size_t i = coord.x();
         const size_t j = coord.y();
         const size_t k = coord.z();
         const size_t l = coord[3];
         const size_t m = coord[4];
         const size_t n = coord[5];
         const std::array<size_t, TensorShape::num_max_dimensions> dims   = { { 0, 1, 2, 3, 4, 5 } };
         const std::array<size_t, TensorShape::num_max_dimensions> coords = { { i, j, k, l, m, n } };
         auto is_padding_area = [&](size_t i)
         {
             return (coords[i] < paddings_extended[i].first || coords[i] > orig_shape[i] + paddings_extended[i].first - 1);
         };
         auto orig_coord_reflect = [&](size_t i)
         {
             if(is_padding_area(i))
             {
                 if(coords[i] < paddings_extended[i].first)
                 {
                     return paddings_extended[i].first - coords[i];
                 }
                 else
                 {
                     return 2 * orig_shape[i] + paddings_extended[i].first - 2 - coords[i];
                 }
             }
             return coords[i] - paddings_extended[i].first;
         };
         auto orig_coord_symm = [&](size_t i)
         {
             if(is_padding_area(i))
             {
                 if(coords[i] < paddings_extended[i].first)
                 {
                     return paddings_extended[i].first - coords[i] - 1;
                 }
                 else
                 {
                     return 2 * orig_shape[i] + paddings_extended[i].first - 1 - coords[i];
                 }
             }
             return coords[i] - paddings_extended[i].first;
         };
         // If the tuple [i,j,k,l,m] is in the padding area, then simply set the value
         if(std::any_of(dims.begin(), dims.end(), is_padding_area))
         {
             switch(mode)
             {
                 case PaddingMode::CONSTANT:
                     const_value.get(dst[idx]);
                     break;
                 case PaddingMode::REFLECT:
                 {
                     const Coordinates orig_coords{ orig_coord_reflect(0),
                                              orig_coord_reflect(1),
                                              orig_coord_reflect(2),
                                              orig_coord_reflect(3),
                                              orig_coord_reflect(4),
                                              orig_coord_reflect(5) };
                     const size_t idx_src = coord2index(orig_shape, orig_coords);
                     dst[idx]             = src[idx_src];
                     break;
                 }
                 case PaddingMode::SYMMETRIC:
                 {
                     const Coordinates orig_coords{ orig_coord_symm(0),
                                              orig_coord_symm(1),
                                              orig_coord_symm(2),
                                              orig_coord_symm(3),
                                              orig_coord_symm(4),
                                              orig_coord_symm(5) };
                     const size_t idx_src = coord2index(orig_shape, orig_coords);
                     dst[idx]             = src[idx_src];
                     break;
                 }
                 default:
                     ARM_COMPUTE_ERROR("Padding mode not supported.");
                     break;
             }
         }
         else
         {
             // If the tuple[i,j,k,l,m] is not in the padding area, then copy the input into the output
             const Coordinates orig_coords{ i - paddings_extended[0].first,
                                      j - paddings_extended[1].first,
                                      k - paddings_extended[2].first,
                                      l - paddings_extended[3].first,
                                      m - paddings_extended[4].first,
                                      n - paddings_extended[5].first };
             const size_t idx_src = coord2index(orig_shape, orig_coords);
             dst[idx]             = src[idx_src];
         }
     }
     return dst;
 }
References ARM_COMPUTE_ERROR, arm_compute::misc::shape_calculator::compute_padded_shape(), arm_compute::CONSTANT, arm_compute::test::coord2index(), arm_compute::test::validation::dst, PixelValue::get(), arm_compute::test::index2coord(), Dimensions< size_t >::num_max_dimensions, arm_compute::REFLECT, arm_compute::test::validation::src, arm_compute::SYMMETRIC, Dimensions< T >::x(), Dimensions< T >::y(), and Dimensions< T >::z().
Referenced by conv2d_dft().
pad_layer() [2/8]
template SimpleTensor<float> arm_compute::test::validation::reference::pad_layer (const SimpleTensor< float > & src, const PaddingList & paddings, const PixelValue const_value = PixelValue(), const PaddingMode mode)
pad_layer() [3/8]
template SimpleTensor<half> arm_compute::test::validation::reference::pad_layer (const SimpleTensor< half > & src, const PaddingList & paddings, const PixelValue const_value = PixelValue(), const PaddingMode mode)
pad_layer() [4/8]
template SimpleTensor<uint32_t> arm_compute::test::validation::reference::pad_layer (const SimpleTensor< uint32_t > & src, const PaddingList & paddings, const PixelValue const_value = PixelValue(), const PaddingMode mode)
pad_layer() [5/8]
template SimpleTensor<uint8_t> arm_compute::test::validation::reference::pad_layer (const SimpleTensor< uint8_t > & src, const PaddingList & paddings, const PixelValue const_value = PixelValue(), const PaddingMode mode)
pad_layer() [6/8]
template SimpleTensor<int8_t> arm_compute::test::validation::reference::pad_layer (const SimpleTensor< int8_t > & src, const PaddingList & paddings, const PixelValue const_value = PixelValue(), const PaddingMode mode)
pad_layer() [7/8]
template SimpleTensor<uint16_t> arm_compute::test::validation::reference::pad_layer (const SimpleTensor< uint16_t > & src, const PaddingList & paddings, const PixelValue const_value = PixelValue(), const PaddingMode mode)
pad_layer() [8/8]
template SimpleTensor<int16_t> arm_compute::test::validation::reference::pad_layer (const SimpleTensor< int16_t > & src, const PaddingList & paddings, const PixelValue const_value = PixelValue(), const PaddingMode mode)
permute() [1/8]
SimpleTensor< T > permute (const SimpleTensor< T > & src, PermutationVector perm)
Definition at line 38 of file Permute.cpp.
 {
     // Permute shapes
     TensorShape dst_shape = src.shape();
     permute(dst_shape, perm);
     // Create reference
     SimpleTensor<T> dst{ dst_shape, src.data_type(), src.num_channels(), src.quantization_info() };
     // Compute reference
     for(int i = 0; i < src.num_elements(); ++i)
     {
         const Coordinates src_coords = index2coord(src.shape(), i);
         Coordinates       dst_coords = src_coords;
         permute(dst_coords, perm);
         std::copy_n(static_cast<const T *>(src(src_coords)), src.num_channels(), static_cast<T *>(dst(dst_coords)));
     }
     return dst;
 }
References arm_compute::test::validation::dst, arm_compute::test::validation::dst_shape, arm_compute::test::index2coord(), and arm_compute::test::validation::src.
Referenced by dft_2d(), rdft_2d(), and ridft_2d().
permute() [2/8]
template SimpleTensor<int8_t> arm_compute::test::validation::reference::permute (const SimpleTensor< int8_t > & src, PermutationVector perm)
permute() [3/8]
template SimpleTensor<uint8_t> arm_compute::test::validation::reference::permute (const SimpleTensor< uint8_t > & src, PermutationVector perm)
permute() [4/8]
template SimpleTensor<int16_t> arm_compute::test::validation::reference::permute (const SimpleTensor< int16_t > & src, PermutationVector perm)
permute() [5/8]
template SimpleTensor<uint16_t> arm_compute::test::validation::reference::permute (const SimpleTensor< uint16_t > & src, PermutationVector perm)
permute() [6/8]
template SimpleTensor<uint32_t> arm_compute::test::validation::reference::permute (const SimpleTensor< uint32_t > & src, PermutationVector perm)
permute() [7/8]
template SimpleTensor<float> arm_compute::test::validation::reference::permute (const SimpleTensor< float > & src, PermutationVector perm)
permute() [8/8]
template SimpleTensor<half> arm_compute::test::validation::reference::permute (const SimpleTensor< half > & src, PermutationVector perm)
phase() [1/3]
SimpleTensor< uint8_t > phase (const SimpleTensor< T > & gx, const SimpleTensor< T > & gy, PhaseType phase_type)
Definition at line 35 of file Phase.cpp.
 {
     const float           PI = std::atan(1) * 4;
     SimpleTensor<uint8_t> phase(gx.shape(), DataType::U8);
     if(phase_type == PhaseType::UNSIGNED) // unsigned: map to [0-255)
     {
         for(int i = 0; i < gx.num_elements(); ++i)
         {
             float angle_deg = (std::atan2(float(gy[i]), float(gx[i])) / PI) * 180.0f;
             phase[i]        = (angle_deg < 0.0f) ? 180.f + angle_deg : angle_deg;
         }
     }
     else // signed: map to [0-180) degrees
     {
         for(int i = 0; i < gx.num_elements(); ++i)
         {
             float angle_pi = std::atan2(gy[i], gx[i]) / PI;
             angle_pi       = (angle_pi < 0.0f) ? 2 + angle_pi : angle_pi;
             phase[i]       = lround(angle_pi * 128) & 0xFFu;
         }
     }
     return phase;
 }
References SimpleTensor< T >::num_elements(), SimpleTensor< T >::shape(), arm_compute::U8, and arm_compute::UNSIGNED.
Referenced by CLGradientKernel::configure(), CLMagnitudePhaseKernel::configure(), NEMagnitudePhaseKernel< mag_type, phase_type >::configure(), NEGradientKernel::configure(), CLEdgeNonMaxSuppressionKernel::configure(), NEEdgeNonMaxSuppressionKernel::configure(), hog_descriptor(), hog_multi_detection(), hog_orientation_binning(), magnitude_phase(), NEHOGOrientationBinningKernel::run(), NEGradientKernel::run(), and NEEdgeNonMaxSuppressionKernel::run().
phase() [2/3]
template SimpleTensor<uint8_t> arm_compute::test::validation::reference::phase (const SimpleTensor< int16_t > & gx, const SimpleTensor< int16_t > & gy, PhaseType phase_type)
phase() [3/3]
template SimpleTensor<uint8_t> arm_compute::test::validation::reference::phase (const SimpleTensor< int32_t > & gx, const SimpleTensor< int32_t > & gy, PhaseType phase_type)
pixel_wise_multiplication() [1/6]
SimpleTensor< T2 > pixel_wise_multiplication (const SimpleTensor< T1 > & src1, const SimpleTensor< T2 > & src2, float scale, ConvertPolicy convert_policy, RoundingPolicy rounding_policy, const QuantizationInfo & qout)
Definition at line 131 of file PixelWiseMultiplication.cpp.
 {
     ARM_COMPUTE_UNUSED(qout);
     SimpleTensor<T2> dst(TensorShape::broadcast_shape(src1.shape(), src2.shape()), src2.data_type());
     if(scale < 0)
     {
         ARM_COMPUTE_ERROR("Scale of pixel-wise multiplication must be non-negative");
     }
     Coordinates id_src1{};
     Coordinates id_src2{};
     Coordinates id_dst{};
     BroadcastUnroll<Coordinates::num_max_dimensions>::unroll(src1, src2, dst, scale, convert_policy, rounding_policy, id_src1, id_src2, id_dst);
     return dst;
 }
References ARM_COMPUTE_ERROR, ARM_COMPUTE_UNUSED, TensorShape::broadcast_shape(), arm_compute::test::validation::convert_policy, SimpleTensor< T >::data_type(), arm_compute::test::validation::dst, arm_compute::test::validation::rounding_policy, scale(), and SimpleTensor< T >::shape().
pixel_wise_multiplication() [2/6]
SimpleTensor<uint8_t> arm_compute::test::validation::reference::pixel_wise_multiplication (const SimpleTensor< uint8_t > & src1, const SimpleTensor< uint8_t > & src2, float scale, ConvertPolicy convert_policy, RoundingPolicy rounding_policy, const QuantizationInfo & qout)
Definition at line 153 of file PixelWiseMultiplication.cpp.
 {
     SimpleTensor<uint8_t> dst(TensorShape::broadcast_shape(src1.shape(), src2.shape()), src2.data_type(), 1, qout);
     if(src1.data_type() == DataType::QASYMM8 && src2.data_type() == DataType::QASYMM8)
     {
         SimpleTensor<float> src1_tmp = convert_from_asymmetric(src1);
         SimpleTensor<float> src2_tmp = convert_from_asymmetric(src2);
         SimpleTensor<float> dst_tmp  = pixel_wise_multiplication<float>(src1_tmp, src2_tmp, scale, convert_policy, rounding_policy, qout);
         dst                          = convert_to_asymmetric(dst_tmp, qout);
     }
     else
     {
         if(scale < 0)
         {
             ARM_COMPUTE_ERROR("Scale of pixel-wise multiplication must be non-negative");
         }
         Coordinates id_src1{};
         Coordinates id_src2{};
         Coordinates id_dst{};
         BroadcastUnroll<Coordinates::num_max_dimensions>::unroll(src1, src2, dst, scale, convert_policy, rounding_policy, id_src1, id_src2, id_dst);
     }
     return dst;
 }
References ARM_COMPUTE_ERROR, TensorShape::broadcast_shape(), arm_compute::test::validation::convert_from_asymmetric(), arm_compute::test::validation::convert_policy, arm_compute::test::validation::convert_to_asymmetric(), SimpleTensor< T >::data_type(), arm_compute::test::validation::dst, arm_compute::QASYMM8, arm_compute::test::validation::rounding_policy, scale(), and SimpleTensor< T >::shape().
pixel_wise_multiplication() [3/6]
SimpleTensor<int16_t> arm_compute::test::validation::reference::pixel_wise_multiplication (const SimpleTensor< int16_t > & src1, const SimpleTensor< int16_t > & src2, float scale, ConvertPolicy convert_policy, RoundingPolicy rounding_policy, const QuantizationInfo & qout)
Definition at line 181 of file PixelWiseMultiplication.cpp.
 {
     SimpleTensor<int16_t> dst(TensorShape::broadcast_shape(src1.shape(), src2.shape()), src2.data_type(), 1, qout);
     if(src1.data_type() == DataType::QSYMM16 && src2.data_type() == DataType::QSYMM16)
     {
         SimpleTensor<float> src1_tmp = convert_from_symmetric<int16_t>(src1);
         SimpleTensor<float> src2_tmp = convert_from_symmetric<int16_t>(src2);
         SimpleTensor<float> dst_tmp  = pixel_wise_multiplication<float>(src1_tmp, src2_tmp, scale, convert_policy, rounding_policy, qout);
         dst                          = convert_to_symmetric<int16_t>(dst_tmp, qout);
     }
     else
     {
         if(scale < 0)
         {
             ARM_COMPUTE_ERROR("Scale of pixel-wise multiplication must be non-negative");
         }
         Coordinates id_src1{};
         Coordinates id_src2{};
         Coordinates id_dst{};
         BroadcastUnroll<Coordinates::num_max_dimensions>::unroll(src1, src2, dst, scale, convert_policy, rounding_policy, id_src1, id_src2, id_dst);
     }
     return dst;
 }
References ARM_COMPUTE_ERROR, TensorShape::broadcast_shape(), arm_compute::test::validation::convert_policy, SimpleTensor< T >::data_type(), arm_compute::test::validation::dst, arm_compute::QSYMM16, arm_compute::test::validation::rounding_policy, scale(), and SimpleTensor< T >::shape().
pixel_wise_multiplication() [4/6]
template SimpleTensor<int16_t> arm_compute::test::validation::reference::pixel_wise_multiplication (const SimpleTensor< uint8_t > & src1, const SimpleTensor< int16_t > & src2, float scale, ConvertPolicy convert_policy, RoundingPolicy rounding_policy, const QuantizationInfo & qout)
pixel_wise_multiplication() [5/6]
template SimpleTensor<float> arm_compute::test::validation::reference::pixel_wise_multiplication (const SimpleTensor< float > & src1, const SimpleTensor< float > & src2, float scale, ConvertPolicy convert_policy, RoundingPolicy rounding_policy, const QuantizationInfo & qout)
pixel_wise_multiplication() [6/6]
template SimpleTensor<half_float::half> arm_compute::test::validation::reference::pixel_wise_multiplication (const SimpleTensor< half_float::half > & src1, const SimpleTensor< half_float::half > & src2, float scale, ConvertPolicy convert_policy, RoundingPolicy rounding_policy, const QuantizationInfo & qout)
pooling_layer() [1/3]
SimpleTensor< T > pooling_layer (const SimpleTensor< T > & src, const PoolingLayerInfo & info, const QuantizationInfo & output_qinfo)
Definition at line 41 of file PoolingLayer.cpp.
 {
     ARM_COMPUTE_UNUSED(output_qinfo); // requantization occurs in pooling_layer<uint8_t>
     ARM_COMPUTE_ERROR_ON(info.is_global_pooling() && (src.shape().x() != src.shape().y()));
     // Create reference
     SimpleTensor<T> dst{ compute_pool_shape(TensorInfo(src.shape(), 1, src.data_type()), info), src.data_type(), 1 };
     const int   pool_size_x     = info.is_global_pooling() ? src.shape().x() : info.pool_size().width;
     const int   pool_size_y     = info.is_global_pooling() ? src.shape().y() : info.pool_size().height;
     PoolingType type            = info.pool_type();
     int         pool_stride_x   = info.pad_stride_info().stride().first;
     int         pool_stride_y   = info.pad_stride_info().stride().second;
     int         pad_left        = info.pad_stride_info().pad_left();
     int         pad_top         = info.pad_stride_info().pad_top();
     int         pad_right       = info.pad_stride_info().pad_right();
     int         pad_bottom      = info.pad_stride_info().pad_bottom();
     bool        exclude_padding = info.exclude_padding();
     const auto w_src      = static_cast<int>(src.shape()[0]);
     const auto h_src      = static_cast<int>(src.shape()[1]);
     const int  upper_dims = src.shape().total_size() / (w_src * h_src);
     const auto w_dst = static_cast<int>(dst.shape()[0]);
     const auto h_dst = static_cast<int>(dst.shape()[1]);
     if(type == PoolingType::MAX)
     {
         for(int r = 0; r < upper_dims; ++r)
         {
             for(int h = 0; h < h_dst; ++h)
             {
                 for(int w = 0; w < w_dst; ++w)
                 {
                     int wstart = w * pool_stride_x - pad_left;
                     int hstart = h * pool_stride_y - pad_top;
                     int wend   = std::min(wstart + pool_size_x, w_src);
                     int hend   = std::min(hstart + pool_size_y, h_src);
                     wstart     = std::max(wstart, 0);
                     hstart     = std::max(hstart, 0);
                     T max_val = std::numeric_limits<T>::lowest();
                     for(int y = hstart; y < hend; ++y)
                     {
                         for(int x = wstart; x < wend; ++x)
{
                             const T val = src[r * h_src * w_src + y * w_src + x];
                             if(val > max_val)
{
                                 max_val = val;
                             }
                         }
                     }
                     dst[r * h_dst * w_dst + h * w_dst + w] = max_val;
                 }
             }
         }
     }
     else // Average or l2 pooling
     {
         for(int r = 0; r < upper_dims; ++r)
         {
             for(int h = 0; h < h_dst; ++h)
             {
                 for(int w = 0; w < w_dst; ++w)
                 {
                     T   avg_val(0);
                     int wstart = w * pool_stride_x - pad_left;
                     int hstart = h * pool_stride_y - pad_top;
                     int wend   = std::min(wstart + pool_size_x, w_src + pad_right);
                     int hend   = std::min(hstart + pool_size_y, h_src + pad_bottom);
                     int pool   = (hend - hstart) * (wend - wstart);
                     wstart     = std::max(wstart, 0);
                     hstart     = std::max(hstart, 0);
                     wend       = std::min(wend, w_src);
                     hend       = std::min(hend, h_src);
                     // Exclude padding pixels from the average
                     if(exclude_padding)
                     {
                         pool = (hend - hstart) * (wend - wstart);
                     }
                     if(type == PoolingType::AVG)
                     {
                         for(int y = hstart; y < hend; ++y)
{
                             for(int x = wstart; x < wend; ++x)
{
                                 avg_val += src[r * h_src * w_src + y * w_src + x];
                             }
                         }
                         dst[r * h_dst * w_dst + h * w_dst + w] = avg_val / pool;
                     }
                     else
                     {
                         for(int y = hstart; y < hend; ++y)
{
                             for(int x = wstart; x < wend; ++x)
{
                                 const T val = src[r * h_src * w_src + y * w_src + x];
                                 avg_val += val * val;
                             }
                         }
                         dst[r * h_dst * w_dst + h * w_dst + w] = std::sqrt(avg_val / pool);
                     }
                 }
             }
         }
     }
     return dst;
 }
References ARM_COMPUTE_ERROR_ON, ARM_COMPUTE_UNUSED, arm_compute::AVG, arm_compute::misc::shape_calculator::compute_pool_shape(), arm_compute::test::validation::dst, arm_compute::test::validation::info, arm_compute::support::cpp11::lowest(), arm_compute::MAX, arm_compute::test::validation::src, and arm_compute::test::validation::w.
pooling_layer() [2/3]
template SimpleTensor<float> arm_compute::test::validation::reference::pooling_layer (const SimpleTensor< float > & src, const PoolingLayerInfo & info, const QuantizationInfo & output_qinfo)
pooling_layer() [3/3]
template SimpleTensor<half> arm_compute::test::validation::reference::pooling_layer (const SimpleTensor< half > & src, const PoolingLayerInfo & info, const QuantizationInfo & output_qinfo)
pooling_layer< uint8_t >()
SimpleTensor<uint8_t> arm_compute::test::validation::reference::pooling_layer< uint8_t > (const SimpleTensor< uint8_t > & src, const PoolingLayerInfo & info, const QuantizationInfo & output_qinfo)
Definition at line 156 of file PoolingLayer.cpp.
 {
     SimpleTensor<float>   src_tmp = convert_from_asymmetric(src);
     SimpleTensor<float>   dst_tmp = pooling_layer<float>(src_tmp, info, output_qinfo);
     SimpleTensor<uint8_t> dst     = convert_to_asymmetric(dst_tmp, output_qinfo);
     return dst;
 }
References arm_compute::test::validation::convert_from_asymmetric(), arm_compute::test::validation::convert_to_asymmetric(), arm_compute::test::validation::dst, arm_compute::test::validation::info, and arm_compute::test::validation::src.
prior_box_layer() [1/2]
SimpleTensor< T > prior_box_layer (const SimpleTensor< T > & src1, const SimpleTensor< T > & src2, const PriorBoxLayerInfo & info, const TensorShape & output_shape)
Definition at line 39 of file PriorBoxLayer.cpp.
 {
     const auto layer_width  = static_cast<int>(src1.shape()[0]);
     const auto layer_height = static_cast<int>(src1.shape()[1]);
     int img_width  = info.img_size().x;
     int img_height = info.img_size().y;
     if(img_width == 0 || img_height == 0)
     {
         img_width  = static_cast<int>(src2.shape()[0]);
         img_height = static_cast<int>(src2.shape()[1]);
     }
     float step_x = info.steps()[0];
     float step_y = info.steps()[1];
     if(step_x == 0.f || step_y == 0.f)
     {
         step_x = static_cast<float>(img_width) / layer_width;
         step_x = static_cast<float>(img_height) / layer_height;
     }
     // Calculate number of aspect ratios
     const int num_priors     = info.aspect_ratios().size() * info.min_sizes().size() + info.max_sizes().size();
     const int total_elements = layer_width * layer_height * num_priors * 4;
     SimpleTensor<T> result(output_shape, src1.data_type());
     int idx = 0;
     for(int y = 0; y < layer_height; ++y)
     {
         for(int x = 0; x < layer_width; ++x)
         {
             const float center_x = (x + info.offset()) * step_x;
             const float center_y = (y + info.offset()) * step_y;
             float       box_width;
             float       box_height;
             for(unsigned int i = 0; i < info.min_sizes().size(); ++i)
             {
                 const float min_size = info.min_sizes().at(i);
                 box_width            = min_size;
                 box_height           = min_size;
                 // (xmin, ymin, xmax, ymax)
                 result[idx++] = (center_x - box_width / 2.f) / img_width;
                 result[idx++] = (center_y - box_height / 2.f) / img_height;
                 result[idx++] = (center_x + box_width / 2.f) / img_width;
                 result[idx++] = (center_y + box_height / 2.f) / img_height;
                 if(!info.max_sizes().empty())
                 {
                     const float max_size = info.max_sizes().at(i);
                     box_width            = sqrt(min_size * max_size);
                     box_height           = box_width;
                     // (xmin, ymin, xmax, ymax)
                     result[idx++] = (center_x - box_width / 2.f) / img_width;
                     result[idx++] = (center_y - box_height / 2.f) / img_height;
                     result[idx++] = (center_x + box_width / 2.f) / img_width;
                     result[idx++] = (center_y + box_height / 2.f) / img_height;
                 }
                 // rest of priors
                 for(auto ar : info.aspect_ratios())
                 {
                     if(fabs(ar - 1.) < 1e-6)
                     {
                         continue;
                     }
                     box_width  = min_size * sqrt(ar);
                     box_height = min_size / sqrt(ar);
                     // (xmin, ymin, xmax, ymax)
                     result[idx++] = (center_x - box_width / 2.f) / img_width;
                     result[idx++] = (center_y - box_height / 2.f) / img_height;
                     result[idx++] = (center_x + box_width / 2.f) / img_width;
                     result[idx++] = (center_y + box_height / 2.f) / img_height;
                 }
             }
         }
     }
     // clip the coordinates
     if(info.clip())
     {
         for(int i = 0; i < total_elements; ++i)
         {
             result[i] = std::min<T>(std::max<T>(result[i], 0.f), 1.f);
         }
     }
     // set the variance.
     if(info.variances().size() == 1)
     {
         std::fill_n(result.data() + idx, total_elements, info.variances().at(0));
     }
     else
     {
         for(int h = 0; h < layer_height; ++h)
         {
             for(int w = 0; w < layer_width; ++w)
             {
                 for(int i = 0; i < num_priors; ++i)
                 {
                     for(int j = 0; j < 4; ++j)
                     {
                         result[idx++] = info.variances().at(j);
                     }
                 }
             }
         }
     }
     return result;
 }
References SimpleTensor< T >::data_type(), arm_compute::test::validation::info, arm_compute::test::validation::output_shape, SimpleTensor< T >::shape(), and arm_compute::test::validation::w.
prior_box_layer() [2/2]
template SimpleTensor<float> arm_compute::test::validation::reference::prior_box_layer (const SimpleTensor< float > & src1, const SimpleTensor< float > & src2, const PriorBoxLayerInfo & info, const TensorShape & output_shape)
quantization_layer() [1/3]
SimpleTensor< uint8_t > quantization_layer (const SimpleTensor< T > & src, const QuantizationInfo & quantization_info)
Definition at line 37 of file QuantizationLayer.cpp.
 {
     // Create reference
     SimpleTensor<uint8_t> dst{ src.shape(), DataType::QASYMM8, 1, quantization_info };
     const UniformQuantizationInfo qinfo = quantization_info.uniform();
     for(int i = 0; i < src.num_elements(); ++i)
     {
 #ifdef __aarch64__
         dst[i] = quantize_qasymm8((src[i]), qinfo, RoundingPolicy::TO_NEAREST_EVEN);
 #else  // __aarch64__
         dst[i] = quantize_qasymm8((src[i]), qinfo, RoundingPolicy::TO_ZERO);
 #endif // __aarch64__
     }
     return dst;
 }
References arm_compute::test::validation::dst, arm_compute::QASYMM8, arm_compute::test::validation::qinfo, arm_compute::quantize_qasymm8(), arm_compute::test::validation::src, arm_compute::TO_NEAREST_EVEN, arm_compute::TO_ZERO, and QuantizationInfo::uniform().
quantization_layer() [2/3]
template SimpleTensor<uint8_t> arm_compute::test::validation::reference::quantization_layer (const SimpleTensor< half > & src, const QuantizationInfo & quantization_info)
quantization_layer() [3/3]
template SimpleTensor<uint8_t> arm_compute::test::validation::reference::quantization_layer (const SimpleTensor< float > & src, const QuantizationInfo & quantization_info)
range() [1/7]
SimpleTensor< T > range (SimpleTensor< T > & dst, float start, const size_t num_of_elements, float step)
Definition at line 50 of file Range.cpp.
 {
     generate_range(dst, start, num_of_elements, step);
     return dst;
 }
References arm_compute::test::validation::dst, and arm_compute::test::validation::step.
Referenced by arm_compute::helpers::tensor_transform::compute_strided_slice_output_shape(), CLHistogramKernel::configure(), CLHistogramBorderKernel::configure(), arm_compute::test::validation::DATA_TEST_CASE(), hist_border_kernel(), hist_local_kernel(), histogram(), TestFilter::is_selected(), and TFPreproccessor::preprocess().
range() [2/7]
SimpleTensor<uint8_t> arm_compute::test::validation::reference::range (SimpleTensor< uint8_t > & dst, float start, const size_t num_of_elements, float step)
Definition at line 57 of file Range.cpp.
 {
     if(dst.data_type() == DataType::QASYMM8)
     {
         SimpleTensor<float> dst_tmp{ dst.shape(), DataType::F32, 1 };
         generate_range(dst_tmp, start, num_of_elements, step);
         return convert_to_asymmetric(dst_tmp, dst.quantization_info());
     }
     generate_range(dst, start, num_of_elements, step);
     return dst;
 }
References arm_compute::test::validation::convert_to_asymmetric(), arm_compute::test::validation::dst, arm_compute::F32, arm_compute::QASYMM8, and arm_compute::test::validation::step.
range() [3/7]
template SimpleTensor<float> arm_compute::test::validation::reference::range (SimpleTensor< float > & dst, float start, const size_t num_of_elements, float step)
range() [4/7]
template SimpleTensor<half> arm_compute::test::validation::reference::range (SimpleTensor< half > & dst, float start, const size_t num_of_elements, float step)
range() [5/7]
template SimpleTensor<int8_t> arm_compute::test::validation::reference::range (SimpleTensor< int8_t > & dst, float start, const size_t num_of_elements, float step)
range() [6/7]
template SimpleTensor<uint16_t> arm_compute::test::validation::reference::range (SimpleTensor< uint16_t > & dst, float start, const size_t num_of_elements, float step)
range() [7/7]
template SimpleTensor<int16_t> arm_compute::test::validation::reference::range (SimpleTensor< int16_t > & dst, float start, const size_t num_of_elements, float step)
rdft_1d() [1/2]
SimpleTensor< T > rdft_1d (const SimpleTensor< T > & src)
Performs an one dimensional DFT on a real input.
Parameters
[in] src Source tensor.
Returns
Complex output of length n/2 + 1 due to symmetry.
Definition at line 291 of file DFT.cpp.
 {
     return rdft_1d_core(src, FFTDirection::Forward, false);
 }
References Forward, and arm_compute::test::validation::src.
Referenced by arm_compute::test::validation::DATA_TEST_CASE().
rdft_1d() [2/2]
template SimpleTensor<float> arm_compute::test::validation::reference::rdft_1d (const SimpleTensor< float > & src)
rdft_2d() [1/2]
SimpleTensor< T > rdft_2d (const SimpleTensor< T > & src)
Performs a two dimensional DFT on a real input.
Parameters
[in] src Source tensor.
Returns
Complex output of length n/2 + 1 across width due to symmetry and height of same size as the input.
Definition at line 320 of file DFT.cpp.
 {
     ARM_COMPUTE_ERROR_ON(src.num_channels() != 1);
     constexpr FFTDirection direction = FFTDirection::Forward;
     auto first_pass  = rdft_1d_core(src, direction, false);
     auto transposed  = permute(first_pass, PermutationVector(1U, 0U));
     auto second_pass = dft_1d_core(transposed, direction);
     return permute(second_pass, PermutationVector(1U, 0U));
 }
References ARM_COMPUTE_ERROR_ON, Forward, permute(), and arm_compute::test::validation::src.
Referenced by conv2d_dft().
rdft_2d() [2/2]
template SimpleTensor<float> arm_compute::test::validation::reference::rdft_2d (const SimpleTensor< float > & src)
reduction_operation() [1/5]
SimpleTensor< OT > reduction_operation (const SimpleTensor< T > & src, const TensorShape & dst_shape, unsigned int axis, ReductionOperation op)
Definition at line 272 of file ReductionOperation.cpp.
 {
     return compute_reduction_operation<T, OT>(src, dst_shape, axis, op);
 }
References arm_compute::test::validation::axis, arm_compute::test::validation::dst_shape, and arm_compute::test::validation::src.
reduction_operation() [2/5]
template SimpleTensor< uint32_t > reduction_operation (const SimpleTensor< uint8_t > & src, const TensorShape & dst_shape, unsigned int axis, ReductionOperation op)
Definition at line 278 of file ReductionOperation.cpp.
 {
     if(src.data_type() == DataType::QASYMM8 && op != ReductionOperation::MEAN_SUM)
     {
         SimpleTensor<float> src_f = convert_from_asymmetric(src);
         SimpleTensor<float> dst_f = reference::reduction_operation<float, float>(src_f, dst_shape, axis, op);
         return convert_to_asymmetric(dst_f, src.quantization_info());
     }
     else
     {
         return compute_reduction_operation<uint8_t, uint8_t>(src, dst_shape, axis, op);
     }
 }
References arm_compute::test::validation::axis, arm_compute::test::validation::convert_from_asymmetric(), arm_compute::test::validation::convert_to_asymmetric(), arm_compute::test::validation::dst_shape, arm_compute::MEAN_SUM, arm_compute::QASYMM8, and arm_compute::test::validation::src.
reduction_operation() [3/5]
template SimpleTensor< uint32_t > reduction_operation (const SimpleTensor< float > & src, const TensorShape & dst_shape, unsigned int axis, ReductionOperation op)
reduction_operation() [4/5]
template SimpleTensor< uint32_t > reduction_operation (const SimpleTensor< half > & src, const TensorShape & dst_shape, unsigned int axis, ReductionOperation op)
reduction_operation() [5/5]
template SimpleTensor<uint32_t> arm_compute::test::validation::reference::reduction_operation (const SimpleTensor< int32_t > & src, const TensorShape & dst_shape, unsigned int axis, ReductionOperation op)
remap() [1/2]
SimpleTensor< T > remap (const SimpleTensor< T > & in, SimpleTensor< float > & map_x, SimpleTensor< float > & map_y, SimpleTensor< T > & valid_mask, InterpolationPolicy policy, BorderMode border_mode, T constant_border_value)
Definition at line 41 of file Remap.cpp.
 {
     ARM_COMPUTE_ERROR_ON_MSG(border_mode == BorderMode::REPLICATE, "BorderMode not supported");
     SimpleTensor<T> out(in.shape(), in.data_type());
     ARM_COMPUTE_ERROR_ON(out.num_elements() != map_x.num_elements());
     const int width  = in.shape().x();
     const int height = in.shape().y();
     for(int idx = 0; idx < out.num_elements(); idx++)
     {
         const Coordinates id_out = index2coord(out.shape(), idx);
         valid_mask[idx]          = 1;
         Coordinates src_idx      = id_out; // need to setup all coordinates and not just xy
         src_idx.set(0, static_cast<int>(std::floor(map_x[idx])));
         src_idx.set(1, static_cast<int>(std::floor(map_y[idx])));
         if((0 <= map_y[idx]) && (map_y[idx] < height) && (0 <= map_x[idx]) && (map_x[idx] < width))
         {
             switch(policy)
             {
                 case InterpolationPolicy::NEAREST_NEIGHBOR:
                 {
                     out[idx] = tensor_elem_at(in, src_idx, border_mode, constant_border_value);
                     break;
                 }
                 case InterpolationPolicy::BILINEAR:
                 {
                     (valid_bilinear_policy(map_x[idx], map_y[idx], width, height, border_mode)) ?
                     out[idx]        = bilinear_policy(in, src_idx, map_x[idx], map_y[idx], border_mode, constant_border_value) :
                                       valid_mask[idx] = 0;
                     break;
                 }
                 case InterpolationPolicy::AREA:
                 default:
                     ARM_COMPUTE_ERROR("Interpolation not supported");
                     break;
             }
         }
         else
         {
             if(border_mode == BorderMode::UNDEFINED)
             {
                 valid_mask[idx] = 0;
             }
             else
             {
                 switch(policy)
                 {
                     case InterpolationPolicy::NEAREST_NEIGHBOR:
                         out[idx] = constant_border_value;
                         break;
                     case InterpolationPolicy::BILINEAR:
                         out[idx] = bilinear_policy(in, src_idx, map_x[idx], map_y[idx], border_mode, constant_border_value);
                         break;
                     case InterpolationPolicy::AREA:
                     default:
                         break;
                 }
             }
         }
     }
     return out;
 }
References arm_compute::AREA, ARM_COMPUTE_ERROR, ARM_COMPUTE_ERROR_ON, ARM_COMPUTE_ERROR_ON_MSG, arm_compute::BILINEAR, arm_compute::test::validation::bilinear_policy(), arm_compute::test::validation::border_mode, SimpleTensor< T >::data_type(), arm_compute::test::index2coord(), arm_compute::NEAREST_NEIGHBOR, SimpleTensor< T >::num_elements(), arm_compute::test::validation::policy, arm_compute::REPLICATE, Dimensions< T >::set(), SimpleTensor< T >::shape(), arm_compute::test::validation::tensor_elem_at(), arm_compute::UNDEFINED, and valid_bilinear_policy().
remap() [2/2]
template SimpleTensor<uint8_t> arm_compute::test::validation::reference::remap (const SimpleTensor< uint8_t > & src, SimpleTensor< float > & map_x, SimpleTensor< float > & map_y, SimpleTensor< uint8_t > & valid_mask, InterpolationPolicy policy, BorderMode border_mode, uint8_t constant_border_value)
reorg_layer() [1/4]
SimpleTensor< T > reorg_layer (const SimpleTensor< T > & src, int32_t stride)
Definition at line 38 of file ReorgLayer.cpp.
 {
     ARM_COMPUTE_ERROR_ON(src.shape().num_dimensions() > 4);
     ARM_COMPUTE_ERROR_ON(src.data_layout() != DataLayout::NCHW);
     TensorInfo        input_info(src.shape(), 1, src.data_type());
     const TensorShape output_shape = misc::shape_calculator::compute_reorg_output_shape(input_info, stride);
     // Create destination tensor
     SimpleTensor<T> dst{ output_shape, src.data_type() };
     const unsigned int W          = dst.shape().x();
     const unsigned int H          = dst.shape().y();
     const unsigned int C          = dst.shape().z();
     const unsigned int out_c      = C / (stride * stride);
     const unsigned int outer_dims = dst.shape().total_size() / (W * H * C);
     // Calculate layer reorg in NCHW
     Coordinates map_coords;
     for(unsigned int b = 0; b < outer_dims; ++b)
     {
         map_coords.set(3, b);
         for(unsigned int c = 0; c < C; ++c)
         {
             map_coords.set(2, c % out_c);
             const unsigned int offset = c / out_c;
             for(unsigned int h = 0; h < H; ++h)
             {
                 map_coords.set(1, h * stride + offset / stride);
                 for(unsigned int w = 0; w < W; ++w)
                 {
                     const unsigned int dst_idx = w + W * (h + H * (c + C * b));
                     map_coords.set(0, w * stride + offset % stride);
                     dst[dst_idx] = *reinterpret_cast<const T *>(src(map_coords));
                 }
             }
         }
     }
     return dst;
 }
References ARM_COMPUTE_ERROR_ON, arm_compute::test::validation::b, arm_compute::misc::shape_calculator::compute_reorg_output_shape(), arm_compute::test::validation::dst, arm_compute::test::validation::input_info, arm_compute::NCHW, offset(), arm_compute::test::validation::output_shape, Dimensions< T >::set(), arm_compute::test::validation::src, and arm_compute::test::validation::w.
reorg_layer() [2/4]
template SimpleTensor<int32_t> arm_compute::test::validation::reference::reorg_layer (const SimpleTensor< int32_t > & src, int32_t stride)
reorg_layer() [3/4]
template SimpleTensor<int16_t> arm_compute::test::validation::reference::reorg_layer (const SimpleTensor< int16_t > & src, int32_t stride)
reorg_layer() [4/4]
template SimpleTensor<int8_t> arm_compute::test::validation::reference::reorg_layer (const SimpleTensor< int8_t > & src, int32_t stride)
reshape_layer() [1/9]
SimpleTensor< T > reshape_layer (const SimpleTensor< T > & src, const TensorShape & output_shape)
[ReshapeLayer]
Definition at line 38 of file ReshapeLayer.cpp.
 {
     ARM_COMPUTE_ERROR_ON(src.shape().total_size() != output_shape.total_size());
     SimpleTensor<T> dst(output_shape, src.data_type());
     std::copy_n(src.data(), src.num_elements(), dst.data());
     return dst;
 }
References ARM_COMPUTE_ERROR_ON, arm_compute::test::validation::dst, arm_compute::test::validation::output_shape, and arm_compute::test::validation::src.
reshape_layer() [2/9]
template SimpleTensor<uint8_t> arm_compute::test::validation::reference::reshape_layer (const SimpleTensor< uint8_t > & src, const TensorShape & output_shape)
reshape_layer() [3/9]
template SimpleTensor<int8_t> arm_compute::test::validation::reference::reshape_layer (const SimpleTensor< int8_t > & src, const TensorShape & output_shape)
reshape_layer() [4/9]
template SimpleTensor<uint16_t> arm_compute::test::validation::reference::reshape_layer (const SimpleTensor< uint16_t > & src, const TensorShape & output_shape)
reshape_layer() [5/9]
template SimpleTensor<int16_t> arm_compute::test::validation::reference::reshape_layer (const SimpleTensor< int16_t > & src, const TensorShape & output_shape)
reshape_layer() [6/9]
template SimpleTensor<uint32_t> arm_compute::test::validation::reference::reshape_layer (const SimpleTensor< uint32_t > & src, const TensorShape & output_shape)
reshape_layer() [7/9]
template SimpleTensor<int32_t> arm_compute::test::validation::reference::reshape_layer (const SimpleTensor< int32_t > & src, const TensorShape & output_shape)
reshape_layer() [8/9]
template SimpleTensor<half> arm_compute::test::validation::reference::reshape_layer (const SimpleTensor< half > & src, const TensorShape & output_shape)
reshape_layer() [9/9]
template SimpleTensor<float> arm_compute::test::validation::reference::reshape_layer (const SimpleTensor< float > & src, const TensorShape & output_shape)
reverse() [1/4]
SimpleTensor< T > reverse (const SimpleTensor< T > & src, const SimpleTensor< uint32_t > & axis)
Definition at line 38 of file Reverse.cpp.
 {
     ARM_COMPUTE_ERROR_ON(axis.shape().num_dimensions() > 1);
     ARM_COMPUTE_ERROR_ON(axis.shape().x() > 4);
     // Create reference
     SimpleTensor<T> dst{ src.shape(), src.data_type(), src.num_channels(), src.quantization_info() };
     const unsigned int width   = src.shape()[0];
     const unsigned int height  = src.shape()[1];
     const unsigned int depth   = src.shape()[2];
     const unsigned int batches = src.shape()[3];
     std::array<bool, 4> to_reverse = { { false, false, false, false } };
     for(int i = 0; i < axis.num_elements(); ++i)
     {
         to_reverse[axis[i]] = true;
     }
     for(int i = 0; i < src.num_elements(); ++i)
     {
         const Coordinates  src_coord = index2coord(src.shape(), i);
         const unsigned int dst_x     = to_reverse[0] ? width - src_coord[0] - 1 : src_coord[0];
         const unsigned int dst_y     = to_reverse[1] ? height - src_coord[1] - 1 : src_coord[1];
         const unsigned int dst_z     = to_reverse[2] ? depth - src_coord[2] - 1 : src_coord[2];
         const unsigned int dst_w     = to_reverse[3] ? batches - src_coord[3] - 1 : src_coord[3];
         dst[coord2index(src.shape(), Coordinates(dst_x, dst_y, dst_z, dst_w))] = src[i];
     }
     return dst;
 }
References ARM_COMPUTE_ERROR_ON, arm_compute::test::validation::axis, arm_compute::test::coord2index(), arm_compute::test::validation::dst, arm_compute::test::index2coord(), and arm_compute::test::validation::src.
Referenced by conv2d_dft(), and arm_compute::utils::parse_npy_header().
reverse() [2/4]
template SimpleTensor<uint8_t> arm_compute::test::validation::reference::reverse (const SimpleTensor< uint8_t > & src, const SimpleTensor< uint32_t > & axis)
reverse() [3/4]
template SimpleTensor<half> arm_compute::test::validation::reference::reverse (const SimpleTensor< half > & src, const SimpleTensor< uint32_t > & axis)
reverse() [4/4]
template SimpleTensor<float> arm_compute::test::validation::reference::reverse (const SimpleTensor< float > & src, const SimpleTensor< uint32_t > & axis)
ridft_1d() [1/2]
SimpleTensor< T > ridft_1d (const SimpleTensor< T > & src, bool is_odd = false)
Performs an one dimensional inverse DFT on a real input.
Parameters
[in] src Source tensor.
[in] is_odd (Optional) Specifies if the output has odd dimensions. Is used by the inverse variant to reconstruct odd sequences.
Returns
Complex output of length n/2 + 1 due to symmetry.
Definition at line 297 of file DFT.cpp.
 {
     auto dst = rdft_1d_core(src, FFTDirection::Inverse, is_odd);
     const T scaling_factor = dst.shape()[0];
     scale(dst, scaling_factor);
     return dst;
 }
References arm_compute::test::validation::dst, Inverse, arm_compute::test::validation::is_odd, scale(), and arm_compute::test::validation::src.
Referenced by arm_compute::test::validation::DATA_TEST_CASE().
ridft_1d() [2/2]
template SimpleTensor<float> arm_compute::test::validation::reference::ridft_1d (const SimpleTensor< float > & src, bool is_odd)
ridft_2d() [1/2]
SimpleTensor< T > ridft_2d (const SimpleTensor< T > & src, bool is_odd = false)
Performs a two dimensional inverse DFT on a real input.
Parameters
[in] src Source tensor.
[in] is_odd (Optional) Specifies if the output has odd dimensions across width. Is used by the inverse variant to reconstruct odd sequences.
Returns
Complex output of length n/2 + 1 across width due to symmetry and height of same size as the input.
Definition at line 332 of file DFT.cpp.
 {
     ARM_COMPUTE_ERROR_ON(src.num_channels() != 2);
     constexpr FFTDirection direction = FFTDirection::Inverse;
     auto transposed   = permute(src, PermutationVector(1U, 0U));
     auto first_pass   = dft_1d_core(transposed, direction);
     auto transposed_2 = permute(first_pass, PermutationVector(1U, 0U));
     auto dst          = rdft_1d_core(transposed_2, direction, is_odd);
     const T scaling_factor = dst.shape()[0] * dst.shape()[1];
     scale(dst, scaling_factor);
     return dst;
 }
References ARM_COMPUTE_ERROR_ON, arm_compute::test::validation::dst, Inverse, arm_compute::test::validation::is_odd, permute(), scale(), and arm_compute::test::validation::src.
Referenced by conv2d_dft().
ridft_2d() [2/2]
template SimpleTensor<float> arm_compute::test::validation::reference::ridft_2d (const SimpleTensor< float > & src, bool is_odd)
roi_align_layer() [1/3]
SimpleTensor< T > roi_align_layer (const SimpleTensor< T > & src, const SimpleTensor< T > & rois, const ROIPoolingLayerInfo & pool_info)
Definition at line 117 of file ROIAlignLayer.cpp.
 {
     const size_t values_per_roi = rois.shape()[0];
     const size_t num_rois       = rois.shape()[1];
     DataType     dst_data_type  = src.data_type();
     const auto *rois_ptr = static_cast<const T *>(rois.data());
     TensorShape     input_shape = src.shape();
     TensorShape     output_shape(pool_info.pooled_width(), pool_info.pooled_height(), src.shape()[2], num_rois);
     SimpleTensor<T> dst(output_shape, dst_data_type);
     // Iterate over every pixel of the input image
     for(size_t px = 0; px < pool_info.pooled_width(); ++px)
     {
         for(size_t py = 0; py < pool_info.pooled_height(); ++py)
         {
             for(size_t pw = 0; pw < num_rois; ++pw)
             {
                 const unsigned int roi_batch = rois_ptr[values_per_roi * pw];
                 const auto         x1        = float(rois_ptr[values_per_roi * pw + 1]);
                 const auto         y1        = float(rois_ptr[values_per_roi * pw + 2]);
                 const auto         x2        = float(rois_ptr[values_per_roi * pw + 3]);
                 const auto         y2        = float(rois_ptr[values_per_roi * pw + 4]);
                 const float roi_anchor_x = x1 * pool_info.spatial_scale();
                 const float roi_anchor_y = y1 * pool_info.spatial_scale();
                 const float roi_dims_x   = std::max((x2 - x1) * pool_info.spatial_scale(), 1.0f);
                 const float roi_dims_y   = std::max((y2 - y1) * pool_info.spatial_scale(), 1.0f);
                 float bin_size_x     = roi_dims_x / pool_info.pooled_width();
                 float bin_size_y     = roi_dims_y / pool_info.pooled_height();
                 float region_start_x = px * bin_size_x + roi_anchor_x;
                 float region_start_y = py * bin_size_y + roi_anchor_y;
                 float region_end_x   = (px + 1) * bin_size_x + roi_anchor_x;
                 float region_end_y   = (py + 1) * bin_size_y + roi_anchor_y;
                 region_start_x = clamp(region_start_x, 0.0f, float(input_shape[0]));
                 region_start_y = clamp(region_start_y, 0.0f, float(input_shape[1]));
                 region_end_x   = clamp(region_end_x, 0.0f, float(input_shape[0]));
                 region_end_y   = clamp(region_end_y, 0.0f, float(input_shape[1]));
                 const int roi_bin_grid_x = (pool_info.sampling_ratio() > 0) ? pool_info.sampling_ratio() : int(ceil(bin_size_x));
                 const int roi_bin_grid_y = (pool_info.sampling_ratio() > 0) ? pool_info.sampling_ratio() : int(ceil(bin_size_y));
                 // Move input and output pointer across the fourth dimension
                 const size_t input_stride_w  = input_shape[0] * input_shape[1] * input_shape[2];
                 const size_t output_stride_w = output_shape[0] * output_shape[1] * output_shape[2];
                 const T     *input_ptr       = src.data() + roi_batch * input_stride_w;
                 T           *output_ptr      = dst.data() + px + py * output_shape[0] + pw * output_stride_w;
                 for(int pz = 0; pz < int(input_shape[2]); ++pz)
                 {
                     // For every pixel pool over an aligned region
                     *(output_ptr + pz * output_shape[0] * output_shape[1]) = roi_align_1x1(input_ptr, input_shape,
                                                                                            region_start_x,
                                                                                            bin_size_x,
                                                                                            roi_bin_grid_x,
                                                                                            region_end_x,
                                                                                            region_start_y,
                                                                                            bin_size_y,
                                                                                            roi_bin_grid_y,
                                                                                            region_end_y, pz);
                 }
             }
         }
     }
     return dst;
 }
References arm_compute::utility::clamp(), SimpleTensor< T >::data(), arm_compute::test::validation::dst, arm_compute::test::validation::input_shape, arm_compute::test::validation::output_shape, ROIPoolingLayerInfo::pooled_height(), ROIPoolingLayerInfo::pooled_width(), ROIPoolingLayerInfo::sampling_ratio(), SimpleTensor< T >::shape(), ROIPoolingLayerInfo::spatial_scale(), and arm_compute::test::validation::src.
roi_align_layer() [2/3]
template SimpleTensor<float> arm_compute::test::validation::reference::roi_align_layer (const SimpleTensor< float > & src, const SimpleTensor< float > & rois, const ROIPoolingLayerInfo & pool_info)
roi_align_layer() [3/3]
template SimpleTensor<half> arm_compute::test::validation::reference::roi_align_layer (const SimpleTensor< half > & src, const SimpleTensor< half > & rois, const ROIPoolingLayerInfo & pool_info)
safe_read()
T arm_compute::test::validation::reference::safe_read (const SimpleTensor< T > & t, int y, int x)
Definition at line 37 of file GEMMInterleaveBlocked.h.
 {
     const int stride = t.shape().x();
     const int M      = t.shape().y();
     const int N      = t.shape().x();
     if((y < M) && (x < N))
     {
         return t[y * stride + x];
     }
     return 0;
 }
References SimpleTensor< T >::shape().
Referenced by gemm_interleave_blocked().
scale() [1/5]
SimpleTensor< T > scale (const SimpleTensor< T > & src, float scale_x, float scale_y, InterpolationPolicy policy, BorderMode border_mode, T constant_border_value, SamplingPolicy sampling_policy, bool ceil_policy_scale)
Definition at line 183 of file Scale.cpp.
 {
     return scale_core<T>(src, scale_x, scale_y, policy, border_mode, constant_border_value, sampling_policy, ceil_policy_scale);
 }
References arm_compute::test::validation::border_mode, arm_compute::test::validation::policy, and arm_compute::test::validation::src.
Referenced by box3x3(), convolution(), dft_1d(), dft_2d(), gaussian3x3(), gaussian5x5(), gaussian_pyramid_half(), laplacian_reconstruct(), pixel_wise_multiplication(), ridft_1d(), and ridft_2d().
scale() [2/5]
SimpleTensor<uint8_t> arm_compute::test::validation::reference::scale (const SimpleTensor< uint8_t > & src, float scale_x, float scale_y, InterpolationPolicy policy, BorderMode border_mode, uint8_t constant_border_value, SamplingPolicy sampling_policy, bool ceil_policy_scale)
Definition at line 190 of file Scale.cpp.
 {
     SimpleTensor<uint8_t> dst;
     if(src.quantization_info().uniform().scale != 0.f)
     {
         SimpleTensor<float> src_tmp                 = convert_from_asymmetric(src);
         float               constant_border_value_f = dequantize_qasymm8(constant_border_value, src.quantization_info());
         SimpleTensor<float> dst_tmp                 = scale_core<float>(src_tmp, scale_x, scale_y, policy, border_mode, constant_border_value_f, sampling_policy, ceil_policy_scale);
         dst                                         = convert_to_asymmetric(dst_tmp, src.quantization_info());
     }
     else
     {
         dst = scale_core<uint8_t>(src, scale_x, scale_y, policy, border_mode, constant_border_value, sampling_policy, ceil_policy_scale);
     }
     return dst;
 }
References arm_compute::test::validation::border_mode, arm_compute::test::validation::convert_from_asymmetric(), arm_compute::test::validation::convert_to_asymmetric(), arm_compute::dequantize_qasymm8(), arm_compute::test::validation::dst, arm_compute::test::validation::policy, and arm_compute::test::validation::src.
scale() [3/5]
template SimpleTensor<int16_t> arm_compute::test::validation::reference::scale (const SimpleTensor< int16_t > & src, float scale_x, float scale_y, InterpolationPolicy policy, BorderMode border_mode, int16_t constant_border_value, SamplingPolicy sampling_policy, bool ceil_policy_scale)
scale() [4/5]
template SimpleTensor<half> arm_compute::test::validation::reference::scale (const SimpleTensor< half > & src, float scale_x, float scale_y, InterpolationPolicy policy, BorderMode border_mode, half constant_border_value, SamplingPolicy sampling_policy, bool ceil_policy_scale)
scale() [5/5]
template SimpleTensor<float> arm_compute::test::validation::reference::scale (const SimpleTensor< float > & src, float scale_x, float scale_y, InterpolationPolicy policy, BorderMode border_mode, float constant_border_value, SamplingPolicy sampling_policy, bool ceil_policy_scale)
scale_core()
SimpleTensor<T> arm_compute::test::validation::reference::scale_core (const SimpleTensor< T > & in, float scale_x, float scale_y, InterpolationPolicy policy, BorderMode border_mode, T constant_border_value, SamplingPolicy sampling_policy, bool ceil_policy_scale)
Definition at line 40 of file Scale.cpp.
 {
     // Add 1 if ceil_policy_scale is true
     const size_t round_value = ceil_policy_scale ? 1U : 0U;
     TensorShape  shape_scaled(in.shape());
     shape_scaled.set(0, (in.shape()[0] + round_value) * scale_x);
     shape_scaled.set(1, (in.shape()[1] + round_value) * scale_y);
     SimpleTensor<T> out(shape_scaled, in.data_type());
     // Compute the ratio between source width/height and destination width/height
     const auto wr = static_cast<float>(in.shape()[0]) / static_cast<float>(out.shape()[0]);
     const auto hr = static_cast<float>(in.shape()[1]) / static_cast<float>(out.shape()[1]);
     const auto width  = static_cast<int>(in.shape().x());
     const auto height = static_cast<int>(in.shape().y());
     // Determine border size
     const int border_size = (border_mode == BorderMode::UNDEFINED) ? 0 : 1;
     // Area interpolation behaves as Nearest Neighbour in case of up-sampling
     if(policy == InterpolationPolicy::AREA && wr <= 1.f && hr <= 1.f)
     {
         policy = InterpolationPolicy::NEAREST_NEIGHBOR;
     }
     for(int element_idx = 0, count = 0; element_idx < out.num_elements(); ++element_idx, ++count)
     {
         Coordinates id    = index2coord(out.shape(), element_idx);
         int         idx   = id.x();
         int         idy   = id.y();
         float       x_src = 0;
         float       y_src = 0;
         switch(policy)
         {
             case InterpolationPolicy::NEAREST_NEIGHBOR:
             {
                 switch(sampling_policy)
                 {
                     case SamplingPolicy::TOP_LEFT:
                         x_src = std::floor(idx * wr);
                         y_src = std::floor(idy * hr);
                         break;
                     case SamplingPolicy::CENTER:
                         //Calculate the source coords without -0.5f is equivalent to round the x_scr/y_src coords
                         x_src = (idx + 0.5f) * wr;
                         y_src = (idy + 0.5f) * hr;
                         break;
                     default:
                         ARM_COMPUTE_ERROR("Unsupported sampling policy.");
                 }
                 id.set(0, x_src);
                 id.set(1, y_src);
                 // If coordinates in range of tensor's width or height
                 if(is_valid_pixel_index(x_src, y_src, width, height, border_size))
                 {
                     out[element_idx] = tensor_elem_at(in, id, border_mode, constant_border_value);
                 }
                 break;
             }
             case InterpolationPolicy::BILINEAR:
             {
                 switch(sampling_policy)
                 {
                     case SamplingPolicy::TOP_LEFT:
                         x_src = idx * wr;
                         y_src = idy * hr;
                         break;
                     case SamplingPolicy::CENTER:
                         x_src = (idx + 0.5f) * wr - 0.5f;
                         y_src = (idy + 0.5f) * hr - 0.5f;
                         break;
                     default:
                         ARM_COMPUTE_ERROR("Unsupported sampling policy.");
                 }
                 id.set(0, std::floor(x_src));
                 id.set(1, std::floor(y_src));
                 if(is_valid_pixel_index(x_src, y_src, width, height, border_size))
                 {
                     out[element_idx] = bilinear_policy(in, id, x_src, y_src, border_mode, constant_border_value);
                 }
                 else
                 {
                     if(border_mode == BorderMode::CONSTANT)
                     {
                         out[element_idx] = constant_border_value;
                     }
                     else if(border_mode == BorderMode::REPLICATE)
                     {
                         id.set(0, utility::clamp<int>(x_src, 0, width - 1));
                         id.set(1, utility::clamp<int>(y_src, 0, height - 1));
                         out[element_idx] = in[coord2index(in.shape(), id)];
                     }
                 }
                 break;
             }
             case InterpolationPolicy::AREA:
             {
                 int       x_from = std::floor(idx * wr - 0.5f - x_src);
                 int       y_from = std::floor(idy * hr - 0.5f - y_src);
                 int       x_to   = std::ceil((idx + 1) * wr - 0.5f - x_src);
                 int       y_to   = std::ceil((idy + 1) * hr - 0.5f - y_src);
                 const int xi     = std::floor(x_src);
                 const int yi     = std::floor(y_src);
                 // Clamp position to borders
                 x_src = std::max(-static_cast<float>(border_size), std::min(x_src, static_cast<float>(width - 1 + border_size)));
                 y_src = std::max(-static_cast<float>(border_size), std::min(y_src, static_cast<float>(height - 1 + border_size)));
                 // Clamp bounding box offsets to borders
                 x_from = ((x_src + x_from) < -border_size) ? -border_size : x_from;
                 y_from = ((y_src + y_from) < -border_size) ? -border_size : y_from;
                 x_to   = ((x_src + x_to) >= (width + border_size)) ? (width - 1 + border_size) : x_to;
                 y_to   = ((y_src + y_to) >= (height + border_size)) ? (height - 1 + border_size) : y_to;
                 ARM_COMPUTE_ERROR_ON((x_to - x_from + 1) == 0 || (y_to - y_from + 1) == 0);
                 float sum = 0;
                 for(int j = yi + y_from, je = yi + y_to; j <= je; ++j)
                 {
                     for(int i = xi + x_from, ie = xi + x_to; i <= ie; ++i)
                     {
                         id.set(0, static_cast<int>(i));
                         id.set(1, static_cast<int>(j));
                         sum += tensor_elem_at(in, id, border_mode, constant_border_value);
                     }
                 }
                 out[element_idx] = sum / ((x_to - x_from + 1) * (y_to - y_from + 1));
                 break;
             }
             default:
                 ARM_COMPUTE_ERROR("Unsupported interpolation mode");
         }
     }
     return out;
 }
References arm_compute::AREA, ARM_COMPUTE_ERROR, ARM_COMPUTE_ERROR_ON, arm_compute::BILINEAR, arm_compute::test::validation::bilinear_policy(), arm_compute::test::validation::border_mode, arm_compute::CENTER, arm_compute::CONSTANT, arm_compute::test::coord2index(), SimpleTensor< T >::data_type(), arm_compute::test::index2coord(), arm_compute::test::validation::is_valid_pixel_index(), arm_compute::NEAREST_NEIGHBOR, arm_compute::test::validation::policy, arm_compute::REPLICATE, TensorShape::set(), SimpleTensor< T >::shape(), sum(), arm_compute::test::validation::tensor_elem_at(), arm_compute::TOP_LEFT, arm_compute::UNDEFINED, and Dimensions< T >::x().
scharr() [1/2]
std::pair< SimpleTensor< T >, SimpleTensor< T > > scharr (const SimpleTensor< U > & src, int filter_size, BorderMode border_mode, uint8_t constant_border_value, GradientDimension gradient_dimension)
Definition at line 62 of file Scharr.cpp.
 {
     const auto shape_size = static_cast<unsigned int>(filter_size);
     SimpleTensor<T> dst_x(src.shape(), data_type<T>::value, src.num_channels());
     SimpleTensor<T> dst_y(src.shape(), data_type<T>::value, src.num_channels());
     ValidRegion valid_region = shape_to_valid_region(src.shape(), border_mode == BorderMode::UNDEFINED, BorderSize(filter_size / 2));
     for(int i = 0; i < src.num_elements(); ++i)
     {
         Coordinates coord = index2coord(src.shape(), i);
         if(!is_in_valid_region(valid_region, coord))
         {
             continue;
         }
         switch(gradient_dimension)
         {
             case GradientDimension::GRAD_X:
                 apply_2d_spatial_filter(coord, src, dst_x, TensorShape{ shape_size, shape_size }, masks.at(filter_size).first, 1.f, border_mode, constant_border_value);
                 break;
             case GradientDimension::GRAD_Y:
                 apply_2d_spatial_filter(coord, src, dst_y, TensorShape{ shape_size, shape_size }, masks.at(filter_size).second, 1.f, border_mode, constant_border_value);
                 break;
             case GradientDimension::GRAD_XY:
                 apply_2d_spatial_filter(coord, src, dst_x, TensorShape{ shape_size, shape_size }, masks.at(filter_size).first, 1.f, border_mode, constant_border_value);
                 apply_2d_spatial_filter(coord, src, dst_y, TensorShape{ shape_size, shape_size }, masks.at(filter_size).second, 1.f, border_mode, constant_border_value);
                 break;
             default:
                 ARM_COMPUTE_ERROR("Gradient dimension not supported");
         }
     }
     return std::make_pair(dst_x, dst_y);
 }
References arm_compute::test::validation::filter_size, and arm_compute::test::validation::src.
Referenced by arm_compute::test::validation::DATA_TEST_CASE().
scharr() [2/2]
template std::pair<SimpleTensor<int16_t>, SimpleTensor<int16_t> > arm_compute::test::validation::reference::scharr (const SimpleTensor< uint8_t > & src, int filter_size, BorderMode border_mode, uint8_t constant_border_value, GradientDimension gradient_dimension)
select() [1/4]
SimpleTensor< T > select (const SimpleTensor< uint8_t > & c, const SimpleTensor< T > & x, const SimpleTensor< T > & y)
Definition at line 38 of file Select.cpp.
 {
     // Check if condition has the same rank as c
     const bool is_same_rank = (c.shape().num_dimensions() == x.shape().num_dimensions());
     // Check shapes
     ARM_COMPUTE_ERROR_ON(x.shape() != y.shape());
     ARM_COMPUTE_ERROR_ON(is_same_rank && (x.shape() != c.shape()));
     ARM_COMPUTE_ERROR_ON(!is_same_rank && (c.shape().num_dimensions() > 1) && (c.shape().x() != x.shape()[x.shape().num_dimensions() - 1]));
     // Create reference
     SimpleTensor<T> dst{ x.shape(), x.data_type(), 1 };
     // Run select core
     if(is_same_rank)
     {
         for(int i = 0; i < x.num_elements(); ++i)
         {
             dst[i] = c[i] > 0 ? x[i] : y[i];
         }
     }
     else
     {
         T *output_ptr = dst.data();
         const int outer_size = c.num_elements();
         const int inner_size = x.num_elements() / outer_size;
         size_t    offset     = 0;
         for(int i = 0; i < outer_size; ++i)
         {
             const T *input_ptr = c[i] > 0 ? x.data() : y.data();
             memcpy(output_ptr + offset, input_ptr + offset, inner_size * sizeof(T));
             offset += inner_size;
         }
     }
     return dst;
 }
References ARM_COMPUTE_ERROR_ON, SimpleTensor< T >::data(), SimpleTensor< T >::data_type(), arm_compute::test::validation::dst, Dimensions< T >::num_dimensions(), SimpleTensor< T >::num_elements(), offset(), SimpleTensor< T >::shape(), and Dimensions< T >::x().
select() [2/4]
template SimpleTensor<uint8_t> arm_compute::test::validation::reference::select (const SimpleTensor< uint8_t > & c, const SimpleTensor< uint8_t > & x, const SimpleTensor< uint8_t > & y)
select() [3/4]
template SimpleTensor<half> arm_compute::test::validation::reference::select (const SimpleTensor< uint8_t > & c, const SimpleTensor< half > & x, const SimpleTensor< half > & y)
select() [4/4]
template SimpleTensor<float> arm_compute::test::validation::reference::select (const SimpleTensor< uint8_t > & c, const SimpleTensor< float > & x, const SimpleTensor< float > & y)
slice() [1/3]
SimpleTensor< T > slice (const SimpleTensor< T > & src, Coordinates starts, Coordinates ends)
Definition at line 38 of file SliceOperations.cpp.
 {
     using namespace arm_compute::helpers::tensor_transform;
     // Validation checks
     ARM_COMPUTE_ERROR_ON(src.shape().num_dimensions() > 4);
     ARM_COMPUTE_ERROR_ON(starts.num_dimensions() > src.shape().num_dimensions());
     ARM_COMPUTE_ERROR_ON(std::any_of(starts.cbegin(), starts.cbegin() + starts.num_dimensions(), [](int i)
     {
         return i < 0;
     }));
     ARM_COMPUTE_ERROR_ON(ends.num_dimensions() > src.shape().num_dimensions());
     // Get source shape
     const TensorShape &src_shape = src.shape();
     // Get destination shape
     TensorShape dst_shape = arm_compute::misc::shape_calculator::compute_slice_shape(src_shape, starts, ends);
     // Create destination tensor
     SimpleTensor<T> dst{ dst_shape, src.data_type(), 1 };
     // Perform slice
     Window win;
     win.use_tensor_dimensions(dst_shape);
     execute_window_loop(win, [&](const Coordinates & id)
     {
         Coordinates offset;
         for(unsigned int i = 0; i < id.num_dimensions(); ++i)
         {
             offset.set(i, starts[i] + id[i]);
         }
         *reinterpret_cast<T *>(dst(id)) = *reinterpret_cast<const T *>(src(offset));
     });
     return dst;
 }
References ARM_COMPUTE_ERROR_ON, Dimensions< T >::cbegin(), arm_compute::misc::shape_calculator::compute_slice_shape(), arm_compute::test::validation::dst, arm_compute::test::validation::dst_shape, arm_compute::execute_window_loop(), Dimensions< T >::num_dimensions(), offset(), arm_compute::test::validation::src, and Window::use_tensor_dimensions().
Referenced by NEUnstack::configure(), CLUnstack::configure(), conv2d_dft(), deconvolution_layer(), depthconcatenate_layer(), ICLSimple2DKernel::run(), IGCSimple2DKernel::run(), ICLSimple3DKernel::run(), IGCSimple3DKernel::run(), GCTransposeKernel::run(), GCScaleKernel::run(), CLElementwiseOperationKernel::run(), CLHistogramKernel::run(), CLGradientKernel::run(), CLBitwiseAndKernel::run(), CLMinMaxKernel::run(), CLRemapKernel::run(), CLBitwiseOrKernel::run(), CLBitwiseXorKernel::run(), CLSobel3x3Kernel::run(), GCActivationLayerKernel::run(), GCPixelWiseMultiplicationKernel::run(), CLDerivativeKernel::run(), CLSobel5x5HorKernel::run(), CLSobel7x7HorKernel::run(), GCGEMMMatrixAdditionKernel::run(), GCNormalizationLayerKernel::run(), CLHOGOrientationBinningKernel::run(), GCAbsoluteDifferenceKernel::run(), CLAbsoluteDifferenceKernel::run(), CLMagnitudePhaseKernel::run(), CLFloorKernel::run(), CLDequantizationLayerKernel::run(), CLIntegralImageVertKernel::run(), CLReshapeLayerKernel::run(), CLQuantizationLayerKernel::run(), CLReverseKernel::run(), CLROIPoolingLayerKernel::run(), CLCopyKernel::run(), CLLocallyConnectedMatrixMultiplyKernel::run(), GCDropoutLayerKernel::run(), GCLogits1DShiftExpSumKernel::run(), CLChannelExtractKernel::run(), CLMemsetKernel::run(), CLFFTScaleKernel::run(), CLNormalizationLayerKernel::run(), CLFillBorderKernel::run(), GCDirectConvolutionLayerKernel< kernel_size >::run(), GCFillBorderKernel::run(), CLMeanStdDevNormalizationKernel::run(), CLFastCornersKernel::run(), CLPoolingLayerKernel::run(), CLActivationLayerKernel::run(), CLComparisonKernel::run(), CLTileKernel::run(), CLWidthConcatenate2TensorsKernel::run(), CLGEMMMatrixAdditionKernel::run(), CLDepthwiseConvolutionLayerReshapeWeightsGenericKernel::run(), GCPoolingLayerKernel::run(), CLDepthwiseVectorToTensorKernel::run(), CLMinMaxLayerKernel::run(), CLFFTDigitReverseKernel::run(), CLReorgLayerKernel::run(), CLHarrisScoreKernel::run(), CLChannelCombineKernel::run(), CLPriorBoxLayerKernel::run(), CLHOGDetectorKernel::run(), CLNormalizePlanarYUVLayerKernel::run(), CLScaleKernel::run(), GCArithmeticAdditionKernel::run(), CLMeanStdDevKernel::run(), CLBatchConcatenateLayerKernel::run(), CLSelectKernel::run(), GCNormalizePlanarYUVLayerKernel::run(), CLScharr3x3Kernel::run(), CLWidthConcatenate4TensorsKernel::run(), CLDepthConcatenateLayerKernel::run(), CLBoundingBoxTransformKernel::run(), GCTensorShiftKernel::run(), CLPixelWiseMultiplicationKernel::run(), CLYOLOLayerKernel::run(), CLGEMMLowpMatrixMultiplyKernel::run(), CLFFTRadixStageKernel::run(), CLGEMMReshapeRHSMatrixKernel::run(), CLDirectConvolutionLayerOutputStageKernel::run(), CLGEMMLowpMatrixMultiplyNativeKernel::run(), CLColorConvertKernel::run(), CLGEMMReshapeLHSMatrixKernel::run(), GCCol2ImKernel::run(), CLROIAlignLayerKernel::run(), CLDepthwiseIm2ColKernel::run(), GCGEMMMatrixMultiplyKernel::run(), CLGEMMLowpMatrixMultiplyReshapedOnlyRHSKernel::run(), CLGEMMLowpQuantizeDownInt32ToInt16ScaleByFixedPointKernel::run(), GCBatchNormalizationLayerKernel::run(), NEPixelWiseMultiplicationKernel::run(), CLWinogradInputTransformKernel::run(), CLGEMMLowpQuantizeDownInt32ToUint8ScaleByFloatKernel::run(), CLGEMMLowpQuantizeDownInt32ToUint8ScaleByFixedPointKernel::run(), CLCol2ImKernel::run(), CLGEMMLowpQuantizeDownInt32ToUint8ScaleKernel::run(), CLBatchNormalizationLayerKernel::run(), CLGEMMLowpOffsetContributionOutputStageKernel::run(), CLDirectConvolutionLayerKernel::run(), CLGEMMLowpOffsetContributionKernel::run(), CLStridedSliceKernel::run(), CLHistogramBorderKernel::run(), CLGEMMLowpMatrixMultiplyReshapedKernel::run(), CLGEMMMatrixMultiplyNativeKernel::run(), CLGEMMMatrixMultiplyKernel::run(), CLWinogradOutputTransformKernel::run(), CLGEMMMatrixMultiplyReshapedOnlyRHSKernel::run(), CLEdgeNonMaxSuppressionKernel::run(), CLMinMaxLocationKernel::run(), CLHOGBlockNormalizationKernel::run(), CLIm2ColKernel::run(), GCLogits1DNormKernel::run(), CLGEMMMatrixMultiplyReshapedKernel::run(), CLSobel5x5VertKernel::run(), CLSobel7x7VertKernel::run(), CLCopyToArrayKernel::run(), CLComplexPixelWiseMultiplicationKernel::run(), CLEdgeTraceKernel::run(), CLLogits1DMaxShiftExpSumKernel::run(), CLConvolutionRectangleKernel::run(), CLLogits1DNormKernel::run(), arm_compute::run_reverse(), Window::slide_window_slice_1D(), Window::slide_window_slice_2D(), Window::slide_window_slice_3D(), and Window::slide_window_slice_4D().
slice() [2/3]
template SimpleTensor<float> arm_compute::test::validation::reference::slice (const SimpleTensor< float > & src, Coordinates starts, Coordinates ends)
slice() [3/3]
template SimpleTensor<half_float::half> arm_compute::test::validation::reference::slice (const SimpleTensor< half_float::half > & src, Coordinates starts, Coordinates ends)
sobel() [1/2]
std::pair< SimpleTensor< T >, SimpleTensor< T > > sobel (const SimpleTensor< U > & src, int filter_size, BorderMode border_mode, uint8_t constant_border_value, GradientDimension gradient_dimension)
Definition at line 106 of file Sobel.cpp.
 {
     SimpleTensor<T> dst_x(src.shape(), data_type<T>::value, src.num_channels());
     SimpleTensor<T> dst_y(src.shape(), data_type<T>::value, src.num_channels());
     ValidRegion valid_region = shape_to_valid_region(src.shape(), border_mode == BorderMode::UNDEFINED, BorderSize(filter_size / 2));
     for(int i = 0; i < src.num_elements(); ++i)
     {
         Coordinates coord = index2coord(src.shape(), i);
         if(!is_in_valid_region(valid_region, coord))
         {
             continue;
         }
         switch(gradient_dimension)
         {
             case GradientDimension::GRAD_X:
                 apply_2d_spatial_filter(coord, src, dst_x, TensorShape{ static_cast<unsigned int>(filter_size), static_cast<unsigned int>(filter_size) }, masks.at(filter_size).first, 1.f, border_mode,
                                         constant_border_value);
                 break;
             case GradientDimension::GRAD_Y:
                 apply_2d_spatial_filter(coord, src, dst_y, TensorShape{ static_cast<unsigned int>(filter_size), static_cast<unsigned int>(filter_size) }, masks.at(filter_size).second, 1.f, border_mode,
                                         constant_border_value);
                 break;
             case GradientDimension::GRAD_XY:
                 apply_2d_spatial_filter(coord, src, dst_x, TensorShape{ static_cast<unsigned int>(filter_size), static_cast<unsigned int>(filter_size) }, masks.at(filter_size).first, 1.f, border_mode,
                                         constant_border_value);
                 apply_2d_spatial_filter(coord, src, dst_y, TensorShape{ static_cast<unsigned int>(filter_size), static_cast<unsigned int>(filter_size) }, masks.at(filter_size).second, 1.f, border_mode,
                                         constant_border_value);
                 break;
             default:
                 ARM_COMPUTE_ERROR("Gradient dimension not supported");
         }
     }
     return std::make_pair(dst_x, dst_y);
 }
References arm_compute::test::validation::src.
sobel() [2/2]
template std::pair< SimpleTensor< int >, SimpleTensor< int > > sobel (const SimpleTensor< uint8_t > & src, int filter_size, BorderMode border_mode, uint8_t constant_border_value, GradientDimension gradient_dimension)
softmax_layer() [1/4]
SimpleTensor< T > softmax_layer (const SimpleTensor< T > & src, float beta, size_t axis)
Definition at line 37 of file SoftmaxLayer.cpp.
 {
     // Create reference
     SimpleTensor<T> dst{ src.shape(), src.data_type(), 1 };
     // Compute reference. Lower dims are the collapsing of the first axis
     // dimensions (i.e., the flattened dimension of each batch). The upper dims are
     // instead the batches we want to normalize
     int lower_dims = 1;
     for(size_t i = 0; i < axis; i++)
     {
         lower_dims *= src.shape()[i];
     }
     int upper_dims = 1;
     for(size_t i = axis; i < TensorShape::num_max_dimensions; i++)
     {
         upper_dims *= src.shape()[i];
     }
     for(int r = 0; r < upper_dims; ++r)
     {
         const T *src_row_ptr = src.data() + r * lower_dims;
         T       *dst_row_ptr = dst.data() + r * lower_dims;
         // Find max
         const T max = *std::max_element(src_row_ptr, src_row_ptr + lower_dims);
         // Regularize
         T sum(0.f);
         std::transform(src_row_ptr, src_row_ptr + lower_dims, dst_row_ptr, [&sum, max, beta](T val)
         {
             const T res(std::exp((val - max) * beta));
             sum += res;
             return res;
         });
         // Normalize
         std::transform(dst_row_ptr, dst_row_ptr + lower_dims, dst_row_ptr, [sum](T val)
         {
             return val / sum;
         });
     }
     return dst;
 }
References arm_compute::test::validation::axis, arm_compute::test::validation::dst, Dimensions< size_t >::num_max_dimensions, arm_compute::test::validation::src, and sum().
softmax_layer() [2/4]
template SimpleTensor<float> arm_compute::test::validation::reference::softmax_layer (const SimpleTensor< float > & src, float beta, size_t axis)
softmax_layer() [3/4]
template SimpleTensor<half> arm_compute::test::validation::reference::softmax_layer (const SimpleTensor< half > & src, float beta, size_t axis)
softmax_layer() [4/4]
template SimpleTensor<uint8_t> arm_compute::test::validation::reference::softmax_layer (const SimpleTensor< uint8_t > & src, float beta, size_t axis)
space_to_batch() [1/4]
SimpleTensor< T > space_to_batch (const SimpleTensor< T > & src, const SimpleTensor< int32_t > & block_shape, const SimpleTensor< int32_t > & paddings, const TensorShape & dst_shape)
Definition at line 38 of file SpaceToBatch.cpp.
 {
     SimpleTensor<T> result(dst_shape, src.data_type(), 1, src.quantization_info());
     const auto width_out  = static_cast<int>(dst_shape[0]);
     const auto height_out = static_cast<int>(dst_shape[1]);
     const auto batch_out  = static_cast<int>(dst_shape[3]);
     const auto width_in  = static_cast<int>(src.shape()[0]);
     const auto height_in = static_cast<int>(src.shape()[1]);
     const auto batch_in  = static_cast<int>(src.shape()[3]);
     const auto channel = static_cast<int>(src.shape()[2]);
     const auto block_width  = block_shape[0];
     const auto block_height = block_shape[1];
     const auto padding_left = paddings[0];
     const auto padding_top  = paddings[2];
     // Pad value must be logic zero
     const auto pad_value = is_data_type_quantized(src.data_type()) ? src.quantization_info().uniform().offset : 0;
     int out_pos = 0;
     for(int outB = 0; outB < batch_out; ++outB)
     {
         unsigned int inB = outB % batch_in;
         int shift_w = (outB / batch_in) % block_width;
         int shift_h = (outB / batch_in) / block_width;
         for(int c = 0; c < channel; ++c)
         {
             for(int outH = 0; outH < height_out; ++outH)
             {
                 for(int outW = 0; outW < width_out; ++outW)
                 {
                     const auto in_pos = ((inB * channel + c) * height_in + ((outH * block_height + shift_h) - padding_top)) * width_in + (outW * block_width + shift_w) - padding_left;
                     if(outH * block_height + shift_h < padding_top || outH * block_height + shift_h >= padding_top + height_in || outW * block_width + shift_w < padding_left
                        || outW * block_width + shift_w >= padding_left + width_in)
                     {
                         result[out_pos] = pad_value;
                     }
                     else
                     {
                         result[out_pos] = src[in_pos];
                     }
                     ++out_pos;
                 }
             }
         }
     }
     return result;
 }
References arm_compute::test::validation::dst_shape, arm_compute::is_data_type_quantized(), and arm_compute::test::validation::src.
space_to_batch() [2/4]
template SimpleTensor<float> arm_compute::test::validation::reference::space_to_batch (const SimpleTensor< float > & src, const SimpleTensor< int32_t > & block_shape, const SimpleTensor< int32_t > & paddings, const TensorShape & dst_shape)
space_to_batch() [3/4]
template SimpleTensor<half> arm_compute::test::validation::reference::space_to_batch (const SimpleTensor< half > & src, const SimpleTensor< int32_t > & block_shape, const SimpleTensor< int32_t > & paddings, const TensorShape & dst_shape)
space_to_batch() [4/4]
template SimpleTensor<uint8_t> arm_compute::test::validation::reference::space_to_batch (const SimpleTensor< uint8_t > & src, const SimpleTensor< int32_t > & block_shape, const SimpleTensor< int32_t > & paddings, const TensorShape & dst_shape)
space_to_depth() [1/3]
SimpleTensor< T > space_to_depth (const SimpleTensor< T > & src, const TensorShape & dst_shape, const int block_shape)
Definition at line 38 of file SpaceToDepth.cpp.
 {
     SimpleTensor<T> result(dst_shape, src.data_type());
     const auto width_out   = static_cast<int>(dst_shape[0]);
     const auto height_out  = static_cast<int>(dst_shape[1]);
     const auto channel_out = static_cast<int>(dst_shape[2]);
     const auto width_in   = static_cast<int>(src.shape()[0]);
     const auto height_in  = static_cast<int>(src.shape()[1]);
     const auto channel_in = static_cast<int>(src.shape()[2]);
     const auto batch = static_cast<int>(src.shape()[3]);
     const auto block_width  = block_shape;
     const auto block_height = block_shape;
     int out_pos = 0;
     for(int ba = 0; ba < batch; ++ba)
     {
         for(int outC = 0; outC < channel_out; ++outC)
         {
             unsigned int inC = outC % channel_in;
             int shift_w = (outC / channel_in) % block_width;
             int shift_h = (outC / channel_in) / block_width;
             for(int outH = 0; outH < height_out; ++outH)
             {
                 for(int outW = 0; outW < width_out; ++outW)
                 {
                     const auto in_pos = ((ba * channel_in + inC) * height_in + ((outH * block_height + shift_h))) * width_in + (outW * block_width + shift_w);
                     result[out_pos]   = src[in_pos];
                     ++out_pos;
                 }
             }
         }
     }
     return result;
 }
References arm_compute::test::validation::dst_shape, and arm_compute::test::validation::src.
space_to_depth() [2/3]
template SimpleTensor<float> arm_compute::test::validation::reference::space_to_depth (const SimpleTensor< float > & src, const TensorShape & dst_shape, const int block_shape)
space_to_depth() [3/3]
template SimpleTensor<half> arm_compute::test::validation::reference::space_to_depth (const SimpleTensor< half > & src, const TensorShape & dst_shape, const int block_shape)
stack_layer() [1/4]
SimpleTensor< T > stack_layer (const std::vector< SimpleTensor< T >> & in, const TensorShape & output_shape, DataType data_type, unsigned int axis)
Definition at line 41 of file StackLayer.cpp.
 {
     ARM_COMPUTE_ERROR_ON(output_shape.num_dimensions() > 5);
     ARM_COMPUTE_ERROR_ON(in.size() < 2);
     ARM_COMPUTE_ERROR_ON(axis > in[0].shape().num_dimensions());
     SimpleTensor<T> out{ output_shape, data_type };
     const int width       = in[0].shape()[0];
     const int height      = in[0].shape()[1];
     const int depth       = in[0].shape()[2];
     const int batch_size  = in[0].shape()[3];
     const int num_tensors = in.size();
     // Array to store the input coordinates
     // i_coordinates[0] = xi, i_coordinates[1] = yi, i_coordinates[2] = zi
     // i_coordinates[3] = bi, i_coordinates[4] = i, i_coordinates[5] = 0
     // i_coordinates[5] will be always zero and used for not incrementing the output when the input has less than 4 dimensions
     std::array<int, 6> i_coordinates{ 0 };
     // Array of pointers used to map the output coordinates to the input ones accordingly with the axis
     // This array is initialized with &i_coordinates[5] since this will be always zero
     std::array<int *, 5> o_coordinates = { &i_coordinates[5], &i_coordinates[5], &i_coordinates[5], &i_coordinates[5], &i_coordinates[5] };
     // Set the axis coordinate
     o_coordinates[axis] = &i_coordinates[4];
     unsigned int k_shift = 0;
     // Map the output coordinates
     for(unsigned int k = 0; k < in[0].shape().num_dimensions(); ++k)
     {
         if(k == axis)
         {
             k_shift++;
         }
         o_coordinates[k + k_shift] = &i_coordinates[k];
     }
     // Use alias for the input coordinates
     int &xi = i_coordinates[0];
     int &yi = i_coordinates[1];
     int &zi = i_coordinates[2];
     int &bi = i_coordinates[3];
     int &i  = i_coordinates[4];
     // Use alias for the output coordinates
     int &xo = *(o_coordinates[0]);
     int &yo = *(o_coordinates[1]);
     int &zo = *(o_coordinates[2]);
     int &bo = *(o_coordinates[3]);
     int &wo = *(o_coordinates[4]);
     // Stack tensors
     for(; i < num_tensors; ++(i))
     {
         bi = 0;
         for(; bi < batch_size; ++(bi))
         {
             zi = 0;
             for(; zi < depth; ++(zi))
             {
                 yi = 0;
                 for(; yi < height; ++(yi))
                 {
                     xi = 0;
                     for(; xi < width; ++(xi))
                     {
                         *(reinterpret_cast<T *>(out(Coordinates(xo, yo, zo, bo, wo)))) = *(reinterpret_cast<const T *>(in[i](Coordinates(xi, yi, zi, bi))));
                     }
                 }
             }
         }
     }
     return out;
 }
References ARM_COMPUTE_ERROR_ON, arm_compute::test::validation::axis, arm_compute::test::validation::data_type, arm_compute::test::validation::num_tensors, arm_compute::test::validation::output_shape, and arm_compute::test::validation::shape.
stack_layer() [2/4]
template SimpleTensor<int> arm_compute::test::validation::reference::stack_layer (const std::vector< SimpleTensor< int >> & in, const TensorShape & output_shape, DataType data_type, unsigned int axis)
stack_layer() [3/4]
template SimpleTensor<short> arm_compute::test::validation::reference::stack_layer (const std::vector< SimpleTensor< short >> & in, const TensorShape & output_shape, DataType data_type, unsigned int axis)
stack_layer() [4/4]
template SimpleTensor<char> arm_compute::test::validation::reference::stack_layer (const std::vector< SimpleTensor< char >> & in, const TensorShape & output_shape, DataType data_type, unsigned int axis)
strided_slice() [1/3]
SimpleTensor< T > strided_slice (const SimpleTensor< T > & src, Coordinates starts, Coordinates ends, BiStrides strides, int32_t begin_mask, int32_t end_mask, int32_t shrink_axis_mask)
Definition at line 80 of file SliceOperations.cpp.
 {
     using namespace arm_compute::helpers::tensor_transform;
     // Validation checks
     ARM_COMPUTE_ERROR_ON(src.shape().num_dimensions() > 4);
     ARM_COMPUTE_ERROR_ON(starts.num_dimensions() > src.shape().num_dimensions());
     ARM_COMPUTE_ERROR_ON(ends.num_dimensions() > src.shape().num_dimensions());
     ARM_COMPUTE_ERROR_ON(strides.num_dimensions() > src.shape().num_dimensions());
     ARM_COMPUTE_ERROR_ON(std::any_of(strides.cbegin(), strides.cbegin() + strides.num_dimensions(), [](int i)
     {
         return i == 0;
     }));
     // Get source shape
     const TensorShape &src_shape = src.shape();
     // Get destination shape
     const TensorShape dst_shape = compute_strided_slice_output_shape(src_shape, starts, ends, strides, begin_mask, end_mask, shrink_axis_mask);
     // Create destination tensor
     SimpleTensor<T> dst{ dst_shape, src.data_type(), 1 };
     // Get coordinates
     Coordinates starts_abs{};
     Coordinates ends_abs{};
     Coordinates final_strides{};
     std::tie(starts_abs, ends_abs, final_strides) = calculate_strided_slice_coords(src_shape,
                                                                                    starts, ends, strides,
                                                                                    begin_mask, end_mask, shrink_axis_mask);
     // Perform strided slice
     unsigned int idx = 0;
     Window       win;
     win.use_tensor_dimensions(compute_strided_slice_output_shape(src_shape,
                                                                  starts, ends, strides,
                                                                  begin_mask, end_mask, shrink_axis_mask, true));
     execute_window_loop(win, [&](const Coordinates & id)
     {
         Coordinates offset;
         for(unsigned int i = 0; i < id.num_dimensions(); ++i)
         {
             offset.set(i, starts_abs[i] + id[i] * final_strides[i]);
         }
         dst.data()[idx++] = *reinterpret_cast<const T *>(src(offset));
     });
     return dst;
 }
References ARM_COMPUTE_ERROR_ON, arm_compute::helpers::tensor_transform::calculate_strided_slice_coords(), Dimensions< T >::cbegin(), arm_compute::helpers::tensor_transform::compute_strided_slice_output_shape(), arm_compute::test::validation::dst, arm_compute::test::validation::dst_shape, arm_compute::execute_window_loop(), Dimensions< T >::num_dimensions(), offset(), arm_compute::test::validation::src, and Window::use_tensor_dimensions().
strided_slice() [2/3]
template SimpleTensor<float> arm_compute::test::validation::reference::strided_slice (const SimpleTensor< float > & src, Coordinates starts, Coordinates ends, BiStrides strides, int32_t begin_mask, int32_t end_mask, int32_t shrink_axis_mask)
strided_slice() [3/3]
template SimpleTensor<half_float::half> arm_compute::test::validation::reference::strided_slice (const SimpleTensor< half_float::half > & src, Coordinates starts, Coordinates ends, BiStrides strides, int32_t begin_mask, int32_t end_mask, int32_t shrink_axis_mask)
table_lookup() [1/3]
SimpleTensor< T > table_lookup (const SimpleTensor< T > & src, const std::map< T, T > & rawlut)
Definition at line 37 of file TableLookup.cpp.
 {
     SimpleTensor<T> result(src.shape(), src.data_type());
     for(int i = 0; i < src.num_elements(); ++i)
     {
         result[i] = rawlut.at(src[i]);
     }
     return result;
 }
References arm_compute::test::validation::src.
table_lookup() [2/3]
template SimpleTensor<uint8_t> arm_compute::test::validation::reference::table_lookup (const SimpleTensor< uint8_t > & src, const std::map< uint8_t, uint8_t > & rawlut)
table_lookup() [3/3]
template SimpleTensor<int16_t> arm_compute::test::validation::reference::table_lookup (const SimpleTensor< int16_t > & src, const std::map< int16_t, int16_t > & rawlut)
threshold() [1/2]
SimpleTensor< T > threshold (const SimpleTensor< T > & src, T threshold, T false_value, T true_value, ThresholdType type, T upper)
Definition at line 35 of file Threshold.cpp.
 {
     SimpleTensor<T> dst(src.shape(), src.data_type());
     switch(type)
     {
         case ThresholdType::BINARY:
             for(int i = 0; i < src.num_elements(); ++i)
             {
                 dst[i] = ((src[i] > threshold) ? true_value : false_value);
             }
             break;
         case ThresholdType::RANGE:
             for(int i = 0; i < src.num_elements(); ++i)
             {
                 if(src[i] > upper)
                 {
                     dst[i] = false_value;
                 }
                 else if(src[i] < threshold)
                 {
                     dst[i] = false_value;
                 }
                 else
                 {
                     dst[i] = true_value;
                 }
             }
             break;
         default:
             ARM_COMPUTE_ERROR("Thresholding type not recognised");
             break;
     }
     return dst;
 }
References ARM_COMPUTE_ERROR, arm_compute::BINARY, arm_compute::test::validation::dst, arm_compute::RANGE, and arm_compute::test::validation::src.
Referenced by arm_compute::test::validation::asymm_rounding_divide_by_pow2(), compute_strength(), CLThreshold::configure(), NEThreshold::configure(), CLThresholdKernel::configure(), NEHOGDetector::configure(), NEFastCornersKernel::configure(), NEThresholdKernel::configure(), NEFillArrayKernel::configure(), CLHOGDetector::configure(), NEFastCorners::configure(), NEHOGDetectorKernel::configure(), CLFastCornersKernel::configure(), CLHOGDetectorKernel::configure(), CLFastCorners::configure(), CLHarrisCorners::configure(), NEHarrisCorners::configure(), NEHOGMultiDetection::configure(), CLHOGMultiDetection::configure(), arm_compute::test::validation::DATA_TEST_CASE(), fast_corners(), fast_corners(), harris_corner_detector(), hog_detector(), hog_multi_detection(), arm_compute::rounding_divide_by_pow2(), and threshold_binary().
threshold() [2/2]
template SimpleTensor<uint8_t> arm_compute::test::validation::reference::threshold (const SimpleTensor< uint8_t > & src, uint8_t threshold, uint8_t false_value, uint8_t true_value, ThresholdType type, uint8_t upper)
Referenced by arm_compute::test::validation::DATA_TEST_CASE().
tile() [1/9]
SimpleTensor< T > tile (const SimpleTensor< T > & src, const Multiples & multiples)
Definition at line 38 of file Tile.cpp.
 {
     // Create reference
     const auto src_shape   = src.shape();
     const auto tiled_shape = misc::shape_calculator::compute_tiled_shape(src.shape(), multiples);
     SimpleTensor<T> dst{ tiled_shape, src.data_type() };
     for(int idx = 0; idx < dst.num_elements(); idx++)
     {
         Coordinates coord = index2coord(tiled_shape, idx);
         const size_t x = coord.x();
         const size_t y = coord.y();
         const size_t z = coord.z();
         const size_t w = coord[3];
         Coordinates src_coords{ x % src_shape[0], y % src_shape[1], z % src_shape[2], w % src_shape[3] };
         int         src_idx = coord2index(src_shape, src_coords);
         dst[idx] = src[src_idx];
     }
     return dst;
 }
References arm_compute::misc::shape_calculator::compute_tiled_shape(), arm_compute::test::coord2index(), arm_compute::test::validation::dst, arm_compute::test::index2coord(), arm_compute::test::validation::src, arm_compute::test::validation::w, Dimensions< T >::x(), Dimensions< T >::y(), and Dimensions< T >::z().
Referenced by arm_compute::test::validation::get_tile().
tile() [2/9]
template SimpleTensor<uint8_t> arm_compute::test::validation::reference::tile (const SimpleTensor< uint8_t > & src, const Multiples & multiples)
tile() [3/9]
template SimpleTensor<int8_t> arm_compute::test::validation::reference::tile (const SimpleTensor< int8_t > & src, const Multiples & multiples)
tile() [4/9]
template SimpleTensor<uint16_t> arm_compute::test::validation::reference::tile (const SimpleTensor< uint16_t > & src, const Multiples & multiples)
tile() [5/9]
template SimpleTensor<int16_t> arm_compute::test::validation::reference::tile (const SimpleTensor< int16_t > & src, const Multiples & multiples)
tile() [6/9]
template SimpleTensor<uint32_t> arm_compute::test::validation::reference::tile (const SimpleTensor< uint32_t > & src, const Multiples & multiples)
tile() [7/9]
template SimpleTensor<int32_t> arm_compute::test::validation::reference::tile (const SimpleTensor< int32_t > & src, const Multiples & multiples)
tile() [8/9]
template SimpleTensor<half> arm_compute::test::validation::reference::tile (const SimpleTensor< half > & src, const Multiples & multiples)
tile() [9/9]
template SimpleTensor<float> arm_compute::test::validation::reference::tile (const SimpleTensor< float > & src, const Multiples & multiples)
transpose() [1/6]
SimpleTensor< T > transpose (const SimpleTensor< T > & src)
Definition at line 38 of file Transpose.cpp.
 {
     // Make rows the columns of the original shape
     TensorShape dst_shape{ src.shape().y(), src.shape().x() };
     // Create reference
     SimpleTensor<T> dst{ dst_shape, src.data_type() };
     // Compute reference
     for(int i = 0; i < src.num_elements(); ++i)
     {
         const Coordinates coord = index2coord(src.shape(), i);
         const Coordinates dst_coord{ coord.y(), coord.x() };
         const size_t      dst_index = coord2index(dst.shape(), dst_coord);
         dst[dst_index] = src[i];
     }
     return dst;
 }
References arm_compute::test::coord2index(), arm_compute::test::validation::dst, arm_compute::test::validation::dst_shape, arm_compute::test::index2coord(), arm_compute::test::validation::src, Dimensions< T >::x(), and Dimensions< T >::y().
transpose() [2/6]
template SimpleTensor<uint8_t> arm_compute::test::validation::reference::transpose (const SimpleTensor< uint8_t > & src)
transpose() [3/6]
template SimpleTensor<uint16_t> arm_compute::test::validation::reference::transpose (const SimpleTensor< uint16_t > & src)
transpose() [4/6]
template SimpleTensor<uint32_t> arm_compute::test::validation::reference::transpose (const SimpleTensor< uint32_t > & src)
transpose() [5/6]
template SimpleTensor<half> arm_compute::test::validation::reference::transpose (const SimpleTensor< half > & src)
transpose() [6/6]
template SimpleTensor<float> arm_compute::test::validation::reference::transpose (const SimpleTensor< float > & src)
unstack() [1/4]
std::vector< SimpleTensor< T > > unstack (const SimpleTensor< T > & input_tensor, std::vector< SimpleTensor< T >> & output_tensors, int axis)
Definition at line 87 of file Unstack.cpp.
 {
     // Wrap around negative values
     const unsigned int axis_u = wrap_around(axis, static_cast<int>(input_tensor.shape().num_dimensions()));
     ARM_COMPUTE_ERROR_ON(axis_u >= input_tensor.shape().num_dimensions());
     for(size_t k = 0; k < output_tensors.size(); ++k)
     {
         SimpleTensor<T>      &output    = output_tensors[k];
         const SimpleTensor<T> kth_slice = get_slice(input_tensor, axis_u, k);
         output                          = copy_tensor<T>(kth_slice);
     }
     return output_tensors;
 }
References ARM_COMPUTE_ERROR_ON, arm_compute::test::validation::axis, SimpleTensor< T >::shape(), and arm_compute::wrap_around().
unstack() [2/4]
template std::vector<SimpleTensor<float> > arm_compute::test::validation::reference::unstack (const SimpleTensor< float > & input_tensor, std::vector< SimpleTensor< float >> & output_tensors, int axis)
unstack() [3/4]
template std::vector<SimpleTensor<half> > arm_compute::test::validation::reference::unstack (const SimpleTensor< half > & input_tensor, std::vector< SimpleTensor< half >> & output_tensors, int axis)
unstack() [4/4]
template std::vector<SimpleTensor<uint8_t> > arm_compute::test::validation::reference::unstack (const SimpleTensor< uint8_t > & input_tensor, std::vector< SimpleTensor< uint8_t >> & output_tensors, int axis)
upsample_layer() [1/4]
SimpleTensor< T > upsample_layer (const SimpleTensor< T > & src, const Size2D & info, const InterpolationPolicy policy)
Definition at line 82 of file UpsampleLayer.cpp.
 {
     return upsample_function<T>(src, info, policy);
 }
References arm_compute::test::validation::info, arm_compute::test::validation::policy, and arm_compute::test::validation::src.
upsample_layer() [2/4]
SimpleTensor<uint8_t> arm_compute::test::validation::reference::upsample_layer (const SimpleTensor< uint8_t > & src, const Size2D & info, const InterpolationPolicy policy)
Definition at line 88 of file UpsampleLayer.cpp.
 {
     SimpleTensor<uint8_t> dst(src.shape(), src.data_type(), 1, src.quantization_info());
     if(is_data_type_quantized_asymmetric(src.data_type()))
     {
         SimpleTensor<float> src_tmp = convert_from_asymmetric(src);
         SimpleTensor<float> dst_tmp = upsample_function<float>(src_tmp, info, policy);
         dst                         = convert_to_asymmetric(dst_tmp, src.quantization_info());
     }
     else
     {
         dst = upsample_function<uint8_t>(src, info, policy);
     }
     return dst;
 }
References arm_compute::test::validation::convert_from_asymmetric(), arm_compute::test::validation::convert_to_asymmetric(), arm_compute::test::validation::dst, arm_compute::test::validation::info, arm_compute::is_data_type_quantized_asymmetric(), arm_compute::test::validation::policy, and arm_compute::test::validation::src.
upsample_layer() [3/4]
template SimpleTensor<float> arm_compute::test::validation::reference::upsample_layer (const SimpleTensor< float > & src, const Size2D & info, const InterpolationPolicy policy)
upsample_layer() [4/4]
template SimpleTensor<half> arm_compute::test::validation::reference::upsample_layer (const SimpleTensor< half > & src, const Size2D & info, const InterpolationPolicy policy)
valid_bilinear_policy()
bool arm_compute::test::validation::reference::valid_bilinear_policy (float xn, float yn, int width, int height, BorderMode border_mode)
Definition at line 36 of file WarpAffine.cpp.
 {
     if(border_mode != BorderMode::UNDEFINED)
     {
         return true;
     }
     if((0 <= yn + 1) && (yn + 1 < height) && (0 <= xn + 1) && (xn + 1 < width))
     {
         return true;
     }
     return false;
 }
References arm_compute::test::validation::border_mode, and arm_compute::UNDEFINED.
Referenced by remap(), warp_affine(), and warp_perspective().
warp_affine() [1/2]
SimpleTensor< T > warp_affine (const SimpleTensor< T > & src, SimpleTensor< T > & valid_mask, const float * matrix, InterpolationPolicy policy, BorderMode border_mode, uint8_t constant_border_value)
Definition at line 50 of file WarpAffine.cpp.
 {
     SimpleTensor<T> dst(src.shape(), src.data_type());
     // x0 = M00 * x + M01 * y + M02
     // y0 = M10 * x + M11 * y + M12
     const float M00 = matrix[0];
     const float M10 = matrix[1];
     const float M01 = matrix[0 + 1 * 2];
     const float M11 = matrix[1 + 1 * 2];
     const float M02 = matrix[0 + 2 * 2];
     const float M12 = matrix[1 + 2 * 2];
     const int width  = src.shape().x();
     const int height = src.shape().y();
     for(int element_idx = 0; element_idx < src.num_elements(); ++element_idx)
     {
         valid_mask[element_idx] = 1;
         Coordinates id          = index2coord(src.shape(), element_idx);
         int         idx         = id.x();
         int         idy         = id.y();
         float x0 = M00 * idx + M01 * idy + M02;
         float y0 = M10 * idx + M11 * idy + M12;
         id.set(0, static_cast<int>(std::floor(x0)));
         id.set(1, static_cast<int>(std::floor(y0)));
         if((0 <= y0) && (y0 < height) && (0 <= x0) && (x0 < width))
         {
             switch(policy)
             {
                 case InterpolationPolicy::NEAREST_NEIGHBOR:
                     dst[element_idx] = tensor_elem_at(src, id, border_mode, constant_border_value);
                     break;
                 case InterpolationPolicy::BILINEAR:
                     (valid_bilinear_policy(x0, y0, width, height, border_mode)) ? dst[element_idx] = bilinear_policy(src, id, x0, y0, border_mode, constant_border_value) :
                                                                                                      valid_mask[element_idx] = 0;
                     break;
                 case InterpolationPolicy::AREA:
                 default:
                     ARM_COMPUTE_ERROR("Interpolation not supported");
             }
         }
         else
         {
             if(border_mode == BorderMode::UNDEFINED)
             {
                 valid_mask[element_idx] = 0;
             }
             else
             {
                 switch(policy)
                 {
                     case InterpolationPolicy::NEAREST_NEIGHBOR:
                         if(border_mode == BorderMode::CONSTANT)
{
                             dst[element_idx] = constant_border_value;
                         }
                         else if(border_mode == BorderMode::REPLICATE)
{
                             id.set(0, std::max(0, std::min(static_cast<int>(x0), width - 1)));
                             id.set(1, std::max(0, std::min(static_cast<int>(y0), height - 1)));
                             dst[element_idx] = src[coord2index(src.shape(), id)];
                         }
                         break;
                     case InterpolationPolicy::BILINEAR:
                         dst[element_idx] = bilinear_policy(src, id, x0, y0, border_mode, constant_border_value);
                         break;
                     case InterpolationPolicy::AREA:
                     default:
                         ARM_COMPUTE_ERROR("Interpolation not supported");
                 }
             }
         }
     }
     return dst;
 }
References arm_compute::AREA, ARM_COMPUTE_ERROR, arm_compute::BILINEAR, arm_compute::test::validation::bilinear_policy(), arm_compute::test::validation::border_mode, arm_compute::CONSTANT, arm_compute::test::coord2index(), arm_compute::test::validation::dst, arm_compute::test::index2coord(), arm_compute::NEAREST_NEIGHBOR, arm_compute::test::validation::policy, arm_compute::REPLICATE, arm_compute::test::validation::src, arm_compute::test::validation::tensor_elem_at(), arm_compute::UNDEFINED, valid_bilinear_policy(), and Dimensions< T >::x().
warp_affine() [2/2]
template SimpleTensor<uint8_t> arm_compute::test::validation::reference::warp_affine (const SimpleTensor< uint8_t > & src, SimpleTensor< uint8_t > & valid_mask, const float * matrix, InterpolationPolicy policy, BorderMode border_mode, uint8_t constant_border_value)
warp_perspective() [1/2]
SimpleTensor< T > warp_perspective (const SimpleTensor< T > & src, SimpleTensor< T > & valid_mask, const float * matrix, InterpolationPolicy policy, BorderMode border_mode, uint8_t constant_border_value)
Definition at line 38 of file WarpPerspective.cpp.
 {
     SimpleTensor<T> dst(src.shape(), src.data_type());
     // x0 = M00 * x + M01 * y + M02
     // y0 = M10 * x + M11 * y + M12
     // z0 = M20 * x + M21 * y + M22
     // xn = x0 / z0
     // yn = y0 / z0
     const float M00 = matrix[0];
     const float M10 = matrix[1];
     const float M20 = matrix[2];
     const float M01 = matrix[0 + 1 * 3];
     const float M11 = matrix[1 + 1 * 3];
     const float M21 = matrix[2 + 1 * 3];
     const float M02 = matrix[0 + 2 * 3];
     const float M12 = matrix[1 + 2 * 3];
     const float M22 = matrix[2 + 2 * 3];
     const int width  = src.shape().x();
     const int height = src.shape().y();
     for(int element_idx = 0; element_idx < src.num_elements(); ++element_idx)
     {
         valid_mask[element_idx] = 1;
         Coordinates id          = index2coord(src.shape(), element_idx);
         const int   idx         = id.x();
         const int   idy         = id.y();
         const float z0          = M20 * idx + M21 * idy + M22;
         const float x0 = (M00 * idx + M01 * idy + M02);
         const float y0 = (M10 * idx + M11 * idy + M12);
         const float xn = x0 / z0;
         const float yn = y0 / z0;
         id.set(0, static_cast<int>(std::floor(xn)));
         id.set(1, static_cast<int>(std::floor(yn)));
         if((0 <= yn) && (yn < height) && (0 <= xn) && (xn < width))
         {
             switch(policy)
             {
                 case InterpolationPolicy::NEAREST_NEIGHBOR:
                     dst[element_idx] = tensor_elem_at(src, id, border_mode, constant_border_value);
                     break;
                 case InterpolationPolicy::BILINEAR:
                     (valid_bilinear_policy(xn, yn, width, height, border_mode)) ? dst[element_idx] = bilinear_policy(src, id, xn, yn, border_mode, constant_border_value) : valid_mask[element_idx] = 0;
                     break;
                 case InterpolationPolicy::AREA:
                 default:
                     ARM_COMPUTE_ERROR("Interpolation not supported");
                     break;
             }
         }
         else
         {
             if(border_mode == BorderMode::UNDEFINED)
             {
                 valid_mask[element_idx] = 0;
             }
             else
             {
                 switch(policy)
                 {
                     case InterpolationPolicy::NEAREST_NEIGHBOR:
                         if(border_mode == BorderMode::CONSTANT)
{
                             dst[element_idx] = constant_border_value;
                         }
                         else if(border_mode == BorderMode::REPLICATE)
{
                             id.set(0, std::max(0, std::min(static_cast<int>(xn), width - 1)));
                             id.set(1, std::max(0, std::min(static_cast<int>(yn), height - 1)));
                             dst[element_idx] = src[coord2index(src.shape(), id)];
                         }
                         break;
                     case InterpolationPolicy::BILINEAR:
                         dst[element_idx] = bilinear_policy(src, id, xn, yn, border_mode, constant_border_value);
                         break;
                     case InterpolationPolicy::AREA:
                     default:
                         ARM_COMPUTE_ERROR("Interpolation not supported");
                         break;
                 }
             }
         }
     }
     return dst;
 }
References arm_compute::AREA, ARM_COMPUTE_ERROR, arm_compute::BILINEAR, arm_compute::test::validation::bilinear_policy(), arm_compute::test::validation::border_mode, arm_compute::CONSTANT, arm_compute::test::coord2index(), arm_compute::test::validation::dst, arm_compute::test::index2coord(), arm_compute::NEAREST_NEIGHBOR, arm_compute::test::validation::policy, arm_compute::REPLICATE, arm_compute::test::validation::src, arm_compute::test::validation::tensor_elem_at(), arm_compute::UNDEFINED, valid_bilinear_policy(), and Dimensions< T >::x().
warp_perspective() [2/2]
template SimpleTensor<uint8_t> arm_compute::test::validation::reference::warp_perspective (const SimpleTensor< uint8_t > & src, SimpleTensor< uint8_t > & valid_mask, const float * matrix, InterpolationPolicy policy, BorderMode border_mode, uint8_t constant_border_value)
weights_reshape() [1/4]
SimpleTensor< T > weights_reshape (const SimpleTensor< T > & src, const SimpleTensor< T > & biases, const TensorShape & dst_shape, const unsigned int num_groups)
Definition at line 38 of file WeightsReshape.cpp.
 {
     SimpleTensor<T> dst{ dst_shape, src.data_type(), 1 };
     // Compute reference
     const bool   has_bias  = biases.size() > 0;
     const size_t linear_sz = src.shape().total_size_lower(3);
     const size_t group_sz  = src.shape()[3] / num_groups;
     for(size_t g = 0; g < num_groups; ++g)
     {
         for(size_t w = 0; w < group_sz; ++w)
         {
             const size_t curr_weight = g * group_sz + w;
             size_t i = 0;
             for(; i < linear_sz; ++i)
             {
                 dst[coord2index(dst.shape(), Coordinates(w, i, g))] = src[curr_weight * linear_sz + i];
             }
             if(has_bias)
             {
                 dst[coord2index(dst.shape(), Coordinates(w, i, g))] = static_cast<T>(biases[curr_weight]);
             }
         }
     }
     return dst;
 }
References arm_compute::test::coord2index(), arm_compute::test::validation::dst, arm_compute::test::validation::dst_shape, arm_compute::test::validation::has_bias, arm_compute::test::validation::num_groups, SimpleTensor< T >::size(), arm_compute::test::validation::src, and arm_compute::test::validation::w.
weights_reshape() [2/4]
template SimpleTensor<float> arm_compute::test::validation::reference::weights_reshape (const SimpleTensor< float > & src, const SimpleTensor< float > & biases, const TensorShape & dst_shape, const unsigned int num_groups)
weights_reshape() [3/4]
template SimpleTensor<half> arm_compute::test::validation::reference::weights_reshape (const SimpleTensor< half > & src, const SimpleTensor< half > & biases, const TensorShape & dst_shape, const unsigned int num_groups)
weights_reshape() [4/4]
template SimpleTensor<uint8_t> arm_compute::test::validation::reference::weights_reshape (const SimpleTensor< uint8_t > & src, const SimpleTensor< uint8_t > & biases, const TensorShape & dst_shape, const unsigned int num_groups)
winograd_filter_transform() [1/3]
SimpleTensor< T > winograd_filter_transform (const SimpleTensor< T > & in, const TensorShape & output_shape, const WinogradInfo & winograd_info)
Definition at line 360 of file Winograd.cpp.
 {
     ARM_COMPUTE_ERROR_ON_MSG(in.data_layout() != DataLayout::NCHW, "Only supported NCHW data format");
     // Create reference
     SimpleTensor<T> out{ output_shape, in.data_type(), 1 };
     const Size2D output_tile_size = winograd_info.output_tile_size;
     const Size2D kernel_size      = winograd_info.kernel_size;
     // Calculate dimensions for the tile
     const unsigned int input_tile_w    = output_tile_size.width + kernel_size.width - 1;
     const unsigned int input_tile_h    = output_tile_size.height + kernel_size.height - 1;
     const unsigned int input_tile_area = input_tile_w * input_tile_h;
     // Get the maximum dimension from the filter size
     const unsigned int kernel_max_dim = std::max(kernel_size.width, kernel_size.height);
     // Get the maximum dimension from the input tile
     const unsigned int input_tile_max_dim = std::max(input_tile_w, input_tile_h);
     // Simple tensor for the input tile
     SimpleTensor<T> input_tile{ TensorShape(kernel_max_dim, kernel_max_dim), in.data_type(), 1 };
     // Simple tensor for the transformation matrix
     SimpleTensor<T> trans_matrix{ TensorShape(kernel_max_dim, input_tile_max_dim), in.data_type(), 1 };
     // Simple tensor for the transformation matrix transpose
     SimpleTensor<T> trans_matrix_transposed{ TensorShape(input_tile_max_dim, kernel_max_dim), in.data_type(), 1 };
     // Simple tensor for the temporary tile
     SimpleTensor<T> tmp_tile{ TensorShape(kernel_max_dim, input_tile_max_dim), in.data_type(), 1 };
     // Simple tensor for the output tile
     SimpleTensor<T> transf_tile{ TensorShape(input_tile_max_dim, input_tile_max_dim), in.data_type(), 1 };
     // Initialize matrix for the filter transform
     initialize_matrix_transform(trans_matrix, output_tile_size, kernel_size, WinogradTransformType::FILTER);
     // Transpose the transformation matrix
     transpose_matrix<T>(trans_matrix, trans_matrix_transposed);
     const int num_channels = in.shape()[2];
     const int num_filters  = in.shape()[3];
     const int num_batches  = in.shape().total_size() / (kernel_size.area() * num_channels * num_filters);
     // If we have a vertical filter (i.e. 1x3, 1x5,..), we need to take the elements along the y direction (step_y_transf_tile = width of the output tile)
     const int step_y_transf_tile = kernel_size.width == 1 ? input_tile_max_dim : 1;
     for(int n = 0; n < num_batches; ++n)
     {
         for(int w = 0; w < num_filters; ++w)
         {
             for(int z = 0; z < num_channels; ++z)
             {
                 // Load the tile from the input tensor
                 get_tile<T>(in, input_tile, Coordinates(0, 0, z, w, n));
                 // First transformation
                 matrix_multiply<T>(trans_matrix, input_tile, tmp_tile);
                 // Second transformation
                 matrix_multiply<T>(tmp_tile, trans_matrix_transposed, transf_tile);
                 // Store the output tile across the channels
                 const int output_offset = w + z * num_filters;
                 // Store the values across the channels
                 for(unsigned int i = 0; i < input_tile_area; ++i)
                 {
                     out[output_offset + i * num_filters * num_channels] = transf_tile[i * step_y_transf_tile];
                 }
             }
         }
     }
     return out;
 }
References Size2D::area(), ARM_COMPUTE_ERROR_ON_MSG, SimpleTensor< T >::data_layout(), SimpleTensor< T >::data_type(), FILTER, Size2D::height, arm_compute::NCHW, arm_compute::test::validation::output_shape, SimpleTensor< T >::shape(), arm_compute::test::validation::w, Size2D::width, and arm_compute::test::validation::winograd_info.
winograd_filter_transform() [2/3]
template SimpleTensor<float> arm_compute::test::validation::reference::winograd_filter_transform (const SimpleTensor< float > & in, const TensorShape & output_shape, const WinogradInfo & winograd_info)
winograd_filter_transform() [3/3]
template SimpleTensor<half> arm_compute::test::validation::reference::winograd_filter_transform (const SimpleTensor< half > & in, const TensorShape & output_shape, const WinogradInfo & winograd_info)
winograd_input_transform() [1/3]
SimpleTensor< T > winograd_input_transform (const SimpleTensor< T > & in, const TensorShape & output_shape, const WinogradInfo & winograd_info)
Definition at line 236 of file Winograd.cpp.
 {
     ARM_COMPUTE_ERROR_ON(in.data_layout() != DataLayout::NCHW);
     const PadStrideInfo conv_info        = winograd_info.convolution_info;
     const Size2D        output_tile_size = winograd_info.output_tile_size;
     const Size2D        kernel_size      = winograd_info.kernel_size;
     SimpleTensor<T> out{ output_shape, in.data_type() };
     // Calculate dimensions for the tile
     const unsigned int tile_w = output_tile_size.width + kernel_size.width - 1;
     const unsigned int tile_h = output_tile_size.height + kernel_size.height - 1;
     // Get the maximum dimension from the tile size
     const unsigned int tile_max_dim = std::max(tile_w, tile_h);
     TensorShape tile_dims(tile_max_dim, tile_max_dim);
     // Simple tensor for the input tile
     SimpleTensor<T> src_tile{ tile_dims, in.data_type() };
     // Simple tensor for the temporary tile
     SimpleTensor<T> tmp_tile{ tile_dims, in.data_type() };
     // Simple tensor for the output tile
     SimpleTensor<T> dst_tile{ tile_dims, in.data_type() };
     // Simple tensor for the transformation matrix
     SimpleTensor<T> matrix{ tile_dims, in.data_type() };
     // Simple tensor for the transformation matrix transposed
     SimpleTensor<T> matrix_transposed{ tile_dims, in.data_type() };
     // Initialize matrix for the input transform
     initialize_matrix_transform(matrix, output_tile_size, kernel_size, WinogradTransformType::INPUT);
     // Transpose matrix
     transpose_matrix<T>(matrix, matrix_transposed);
     const int in_w        = in.shape().x();
     const int in_h        = in.shape().y();
     const int in_d        = in.shape().z();
     const int out_d       = out.shape().z();
     const int num_batches = in.shape().total_size() / (in_w * in_h * in_d);
     const int step_x      = output_tile_size.width;
     const int step_y      = output_tile_size.height;
     // Compute the number of output tiles along the x and y direction of size "output_tile_size"
     const Size2D num_tiles = compute_winograd_convolution_tiles(Size2D(in_w, in_h),
                                                                 kernel_size,
                                                                 output_tile_size,
                                                                 conv_info);
     const int num_tiles_x = num_tiles.width;
     const int num_tiles_y = num_tiles.height;
     // In case of 1D convolution, the input tile has to be partially filled with zeros
     int start_x_zero = 0;
     int start_y_zero = 0;
     int end_x_zero   = 0;
     int end_y_zero   = 0;
     if(output_tile_size.width == 1)
     {
         start_x_zero = 1;
         start_y_zero = 0;
         end_x_zero   = tile_max_dim - 1;
         end_y_zero   = tile_max_dim;
     }
     else if(output_tile_size.height == 1)
     {
         start_x_zero = 0;
         start_y_zero = 1;
         end_x_zero   = tile_max_dim;
         end_y_zero   = tile_max_dim - 1;
     }
     // Set the anchor and shape of the zeros area
     const Coordinates anchor_zeros(start_x_zero, start_y_zero);
     const TensorShape shape_zeros(end_x_zero, end_y_zero);
     // If we have a vertical filter (i.e. 1x3, 1x5,..), we need to take the elements along the y direction (step = width of the output tile)
     const int step_y_transf_tile = kernel_size.width == 1 ? tile_max_dim : 1;
     ARM_COMPUTE_ERROR_ON((num_tiles_x * num_tiles_y) != static_cast<int>(out.shape().y()));
     for(int b = 0; b < num_batches; ++b)
     {
         for(int z = 0; z < in_d; ++z)
         {
             for(int y = 0; y < num_tiles_y; ++y)
             {
                 for(int x = 0; x < num_tiles_x; ++x)
                 {
                     int xi = x * step_x - conv_info.pad_left();
                     int yi = y * step_y - conv_info.pad_top();
                     // Get the tile from the input tensor
                     get_tile<T>(in, src_tile, Coordinates(xi, yi, z, b));
                     // Fill partially with zeros in case of 1D convolution
                     zeros<T>(src_tile, anchor_zeros, shape_zeros);
                     // Compute the transformation
                     matrix_multiply<T>(matrix, src_tile, tmp_tile);
                     matrix_multiply<T>(tmp_tile, matrix_transposed, dst_tile);
                     // Store the output tile across the channels
                     for(int i = 0; i < out_d; ++i)
                     {
                         int xo = z;
                         int yo = x + y * num_tiles_x;
                         out[coords2index(out.shape(), Coordinates(xo, yo, i, b))] = dst_tile[i * step_y_transf_tile];
                     }
                 }
             }
         }
     }
     return out;
 }
References ARM_COMPUTE_ERROR_ON, arm_compute::test::validation::b, arm_compute::compute_winograd_convolution_tiles(), arm_compute::test::validation::conv_info, arm_compute::coords2index(), SimpleTensor< T >::data_layout(), SimpleTensor< T >::data_type(), Size2D::height, INPUT, arm_compute::NCHW, arm_compute::test::validation::output_shape, SimpleTensor< T >::shape(), Size2D::width, and arm_compute::test::validation::winograd_info.
winograd_input_transform() [2/3]
template SimpleTensor<float> arm_compute::test::validation::reference::winograd_input_transform (const SimpleTensor< float > & in, const TensorShape & output_shape, const WinogradInfo & winograd_info)
winograd_input_transform() [3/3]
template SimpleTensor<half> arm_compute::test::validation::reference::winograd_input_transform (const SimpleTensor< half > & in, const TensorShape & output_shape, const WinogradInfo & winograd_info)
winograd_output_transform() [1/3]
SimpleTensor< T > winograd_output_transform (const SimpleTensor< T > & in, const SimpleTensor< T > & b, const TensorShape & output_shape, const WinogradInfo & winograd_info)
Definition at line 440 of file Winograd.cpp.
 {
     const PadStrideInfo conv_info        = winograd_info.convolution_info;
     const Size2D        input_dimensions = winograd_info.input_dimensions;
     const Size2D        output_tile_size = winograd_info.output_tile_size;
     const Size2D        kernel_size      = winograd_info.kernel_size;
     // Create reference
     SimpleTensor<T> out{ output_shape, in.data_type(), 1 };
     // Calculate dimensions for the tiles
     const unsigned int in_tile_w  = output_tile_size.width + kernel_size.width - 1;
     const unsigned int in_tile_h  = output_tile_size.height + kernel_size.height - 1;
     const unsigned int out_tile_w = output_tile_size.width;
     const unsigned int out_tile_h = output_tile_size.height;
     ARM_COMPUTE_ERROR_ON(in.shape()[2] != (in_tile_w * in_tile_h));
     ARM_COMPUTE_ERROR_ON(in.shape()[0] != out.shape()[get_data_layout_dimension_index(winograd_info.output_data_layout, DataLayoutDimension::CHANNEL)]);
     // Get the maximum dimension from the tile size
     const unsigned int in_tile_max_dim  = std::max(in_tile_w, in_tile_h);
     const unsigned int out_tile_max_dim = std::max(output_tile_size.width, output_tile_size.height);
     // Compute tile dimensions
     // Input tile dimensions
     TensorShape in_tile_dims(in_tile_max_dim, in_tile_max_dim);
     // Output tile dimensions
     TensorShape out_tile_dims(out_tile_max_dim, out_tile_max_dim);
     // Transformation matrix dimensions
     TensorShape tr_tile_dims(in_tile_max_dim, out_tile_max_dim);
     // Create tensors
     // Simple tensor for the input tile
     SimpleTensor<T> input_tile{ in_tile_dims, in.data_type(), 1 };
     // Simple tensor for the transformation matrix
     SimpleTensor<T> trans_matrix{ tr_tile_dims, in.data_type(), 1 };
     // Simple tensor for the transformation matrix transpose
     SimpleTensor<T> trans_matrix_transposed{ TensorShape(tr_tile_dims[1], tr_tile_dims[0]), in.data_type(), 1 };
     // Simple tensor for the temporary tile
     SimpleTensor<T> tmp_tile{ tr_tile_dims, in.data_type(), 1 };
     // Simple tensor for the output tile
     SimpleTensor<T> output_tile{ out_tile_dims, in.data_type(), 1 };
     // Initialize matrix for the output transform
     initialize_matrix_transform(trans_matrix, output_tile_size, kernel_size, WinogradTransformType::OUTPUT);
     // Transpose the transformation matrix
     transpose_matrix<T>(trans_matrix, trans_matrix_transposed);
     const int w_in        = in.shape()[0];
     const int h_in        = in.shape()[1];
     const int c_in        = in.shape()[2];
     const int w_out       = out.shape()[0];
     const int h_out       = out.shape()[1];
     const int c_out       = out.shape()[2];
     const int num_batches = in.shape().total_size() / (w_in * h_in * c_in);
     // Input strides
     const int stridey_in = w_in;
     const int stridez_in = stridey_in * h_in;
     const int stridew_in = stridez_in * c_in;
     // Output strides
     const int stridey_out = w_out;
     const int stridez_out = stridey_out * h_out;
     const int stridew_out = stridez_out * c_out;
     // Compute the number of output tiles along the x and y direction of size "output_tile_size"
     const Size2D num_tiles = compute_winograd_convolution_tiles(Size2D(input_dimensions.width, input_dimensions.height),
                                                                 kernel_size,
                                                                 output_tile_size,
                                                                 conv_info);
     const int num_tiles_x = num_tiles.width;
     const int num_tiles_y = num_tiles.height;
     ARM_COMPUTE_UNUSED(num_tiles_y);
     ARM_COMPUTE_ERROR_ON(in.shape()[1] != static_cast<unsigned int>(num_tiles_x * num_tiles_y));
     // If we have a vertical filter (i.e. 1x3, 1x5,..), we still need to take the elements along the x direction (step_y_transf_tile = 1)
     const int step_y_transf_tile = kernel_size.width == 1 ? 1 : output_tile.shape()[0];
     // Initialize with zeros the input tile
     zeros<T>(input_tile, Coordinates(0, 0), input_tile.shape());
     for(int n = 0; n < num_batches; ++n)
     {
         for(int y = 0; y < h_in; ++y)
         {
             for(int x = 0; x < w_in; ++x)
             {
                 // Load the input tile tile across the channels of the input tensor
                 for(int z = 0; z < c_in; ++z)
                 {
                     input_tile[z] = in[x + (y * stridey_in) + (z * stridez_in) + (n * stridew_in)];
                 }
                 // First transformation
                 matrix_multiply<T>(trans_matrix, input_tile, tmp_tile);
                 // Second transformation
                 matrix_multiply<T>(tmp_tile, trans_matrix_transposed, output_tile);
                 // Store the output tile
                 const int xo = (y % num_tiles_x) * out_tile_w;
                 const int yo = (y / num_tiles_x) * out_tile_h;
                 const int zo = x;
                 const int output_offset = xo + (yo * stridey_out) + (zo * stridez_out) + (n * stridew_out);
                 for(int yi = 0; yi < static_cast<int>(out_tile_h); ++yi)
                 {
                     for(int xi = 0; xi < static_cast<int>(out_tile_w); ++xi)
                     {
                         // Check out-of-bound writes
                         if((xo + xi < w_out) && (yo + yi < h_out))
{
                             out[output_offset + yi * stridey_out + xi] = output_tile[xi + yi * step_y_transf_tile];
                             // Add bias
                             out[output_offset + yi * stridey_out + xi] += b[zo];
                         }
                     }
                 }
             }
         }
     }
     return out;
 }
References ARM_COMPUTE_ERROR_ON, ARM_COMPUTE_UNUSED, arm_compute::test::validation::b, arm_compute::CHANNEL, arm_compute::compute_winograd_convolution_tiles(), arm_compute::test::validation::conv_info, SimpleTensor< T >::data_type(), arm_compute::get_data_layout_dimension_index(), Size2D::height, OUTPUT, arm_compute::test::validation::output_shape, SimpleTensor< T >::shape(), Size2D::width, and arm_compute::test::validation::winograd_info.
winograd_output_transform() [2/3]
template SimpleTensor<float> arm_compute::test::validation::reference::winograd_output_transform (const SimpleTensor< float > & in, const SimpleTensor< float > & b, const TensorShape & output_shape, const WinogradInfo & winograd_info)
winograd_output_transform() [3/3]
template SimpleTensor<half> arm_compute::test::validation::reference::winograd_output_transform (const SimpleTensor< half > & in, const SimpleTensor< half > & b, const TensorShape & output_shape, const WinogradInfo & winograd_info)
yolo_layer() [1/3]
SimpleTensor< T > yolo_layer (const SimpleTensor< T > & src, const ActivationLayerInfo & info, int32_t num_classes)
Definition at line 40 of file YOLOLayer.cpp.
 {
     // Create reference
     SimpleTensor<T> dst{ src.shape(), src.data_type() };
     // Compute reference
     const T a(info.a());
     const T b(info.b());
     for(int i = 0; i < src.num_elements(); ++i)
     {
         const size_t z = index2coord(dst.shape(), i).z() % (num_classes + 5);
         if(z != 2 && z != 3)
         {
             dst[i] = activate_float<T>(src[i], a, b, info.activation());
         }
         else
         {
             dst[i] = src[i];
         }
     }
     return dst;
 }
References arm_compute::test::validation::b, arm_compute::test::validation::dst, arm_compute::test::index2coord(), arm_compute::test::validation::info, and arm_compute::test::validation::src.
yolo_layer() [2/3]
template SimpleTensor<float> arm_compute::test::validation::reference::yolo_layer (const SimpleTensor< float > & src, const ActivationLayerInfo & info, int32_t num_classes)
yolo_layer() [3/3]
template SimpleTensor<half> arm_compute::test::validation::reference::yolo_layer (const SimpleTensor< half > & src, const ActivationLayerInfo & info, int32_t num_classes)
yolo_layer< uint8_t >()
SimpleTensor<uint8_t> arm_compute::test::validation::reference::yolo_layer< uint8_t > (const SimpleTensor< uint8_t > & src, const ActivationLayerInfo & info, int32_t num_classes)
Definition at line 67 of file YOLOLayer.cpp.
 {
     SimpleTensor<float>   src_tmp = convert_from_asymmetric(src);
     SimpleTensor<float>   dst_tmp = yolo_layer<float>(src_tmp, info, num_classes);
     SimpleTensor<uint8_t> dst     = convert_to_asymmetric(dst_tmp, src.quantization_info());
     return dst;
 }
References arm_compute::test::validation::convert_from_asymmetric(), arm_compute::test::validation::convert_to_asymmetric(), arm_compute::test::validation::dst, arm_compute::test::validation::info, and arm_compute::test::validation::src.