Compute Library: logistic< T, S > Struct Template Reference
logistic< T, S > Struct Template Reference
Logistic activation object.
#include <NEActivationFunctionDetail.h>
Public Types
using ExactType = typename wrapper::traits::neon_vector< T, S >::type
NEON vector type.
using ExactTagType = typename wrapper::traits::neon_vector< T, S >::tag_type
NEON vector tag type.
Public Member Functions
logistic (ActivationLayerInfo act_info)
Construct a Logistic activation object.
void operator() (ExactType &vval)
Run activation function.
Data Fields
const ExactType vone
Vector of ones.
Detailed Description
template<typename T, int S>
struct arm_compute::detail::logistic< T, S >
Logistic activation object.
Definition at line 119 of file NEActivationFunctionDetail.h.
Member Typedef Documentation
ExactTagType
using ExactTagType = typename wrapper::traits::neon_vector<T, S>::tag_type
NEON vector tag type.
Definition at line 124 of file NEActivationFunctionDetail.h.
ExactType
using ExactType = typename wrapper::traits::neon_vector<T, S>::type
NEON vector type.
Definition at line 122 of file NEActivationFunctionDetail.h.
Constructor & Destructor Documentation
logistic()
logistic (ActivationLayerInfo act_info) inline explicit
Construct a Logistic activation object.
Parameters
[in] act_info Activation layer information.
Definition at line 130 of file NEActivationFunctionDetail.h.
         : vone(wrapper::vdup_n(static_cast<T>(1.f), ExactTagType{}))
     {
         ARM_COMPUTE_UNUSED(act_info);
     }
Member Function Documentation
operator()()
void operator() (ExactType & vval) inline
Run activation function.
Parameters
[in] vval Vector of values.
Definition at line 140 of file NEActivationFunctionDetail.h.
     {
         vval = wrapper::vinv(wrapper::vadd(vone, wrapper::vexpq(wrapper::vneg(vval))));
     }
References arm_compute::wrapper::vadd(), arm_compute::wrapper::vexpq(), arm_compute::wrapper::vinv(), arm_compute::wrapper::vneg(), and logistic< T, S >::vone.
Field Documentation
vone
const ExactType vone
Vector of ones.
Definition at line 146 of file NEActivationFunctionDetail.h.
Referenced by logistic< T, S >::operator()().
The documentation for this struct was generated from the following file:
arm_compute/core/NEON/kernels/detail/NEActivationFunctionDetail.h