Compute Library: ContainerDataset< T >::iterator Struct Reference
ContainerDataset< T >::iterator Struct Reference
Iterator for the dataset.
#include <ContainerDataset.h>
Public Member Functions
iterator (std::string name, container_const_iterator iterator)
Construct iterator.
std::string description () const
Get a description of the current value.
ContainerDataset::type operator * () const
Get the current value.
iterator & operator++ ()
Increment the iterator.
Detailed Description
template<typename T>
struct arm_compute::test::framework::dataset::ContainerDataset< T >::iterator
Iterator for the dataset.
Definition at line 85 of file ContainerDataset.h.
Constructor & Destructor Documentation
iterator()
iterator (std::string name, container_const_iterator iterator) inline
Construct iterator.
Parameters
[in] name Description of the values.
[in] iterator Iterator for the values.
Definition at line 92 of file ContainerDataset.h.
             : _name{ name }, _iterator{ iterator }
         {
         }
References NamedDataset::name().
Member Function Documentation
description()
std::string description () const inline
Get a description of the current value.
Returns
a description.
Definition at line 101 of file ContainerDataset.h.
         {
             using support::cpp11::to_string;
             return _name + "=" + to_string(*_iterator);
         }
References arm_compute::test::framework::to_string(), and arm_compute::support::cpp11::to_string().
operator *()
ContainerDataset::type operator * () const inline
Get the current value.
Returns
the current value.
Definition at line 111 of file ContainerDataset.h.
         {
             return std::make_tuple(*_iterator);
         }
operator++()
iterator& operator++ () inline
Increment the iterator.
Returns
this.
Definition at line 120 of file ContainerDataset.h.
         {
             ++_iterator;
             return *this;
         }
The documentation for this struct was generated from the following file:
tests/framework/datasets/ContainerDataset.h