Compute Library: src/core/CL/cl_kernels/warp_helpers.h File Reference
warp_helpers.h File Reference
#include "helpers.h"
Functions
const float8 clamp_to_border_with_size (float8 coords, const float width, const float height, const float border_size)
Clamps the given coordinates to the borders according to the border size.
const float8 clamp_to_border (float8 coords, const float width, const float height)
Clamps the given coordinates to the borders.
const DATA_TYPE4 read_texels4 (const Image *in, const int8 coords)
Reads four texels from the input image.
const float2 get_current_coords ()
Returns the current thread coordinates.
const float8 get_neighbour_coords (const float2 coord)
Given a texel coordinates this function will return the following array of coordinates: [ P, right neighbour, below neighbour, below right neighbour ].
const DATA_TYPE4 bilinear_interpolate_with_border (const Image *in, const float8 coords, const float width, const float height, const float border_size)
Computes the bilinear interpolation for each set of coordinates in the vector coords and returns the values.
const DATA_TYPE4 bilinear_interpolate (const Image *in, const float8 coords, const float width, const float height)
Computes the bilinear interpolation for each set of coordinates in the vector coords and returns the values.
Function Documentation
bilinear_interpolate()
const DATA_TYPE4 bilinear_interpolate (const Image * in, const float8 coords, const float width, const float height) inline
Computes the bilinear interpolation for each set of coordinates in the vector coords and returns the values.
Parameters
[in] in Pointer to the source image.
[in] coords Vector of four 2D coordinates. Even pos is x and odd y.
[in] width Width of the image
[in] height Height of the image
Definition at line 137 of file warp_helpers.h.
 {
     return bilinear_interpolate_with_border(in, coords, width, height, 1);
 }
References bilinear_interpolate_with_border().
Referenced by remap_bilinear(), warp_affine_bilinear(), and warp_perspective_bilinear().
bilinear_interpolate_with_border()
const DATA_TYPE4 bilinear_interpolate_with_border (const Image * in, const float8 coords, const float width, const float height, const float border_size) inline
Computes the bilinear interpolation for each set of coordinates in the vector coords and returns the values.
Parameters
[in] in Pointer to the source image.
[in] coords Vector of four 2D coordinates. Even pos is x and odd y.
[in] width Width of the image
[in] height Height of the image
[in] border_size Border size
Definition at line 95 of file warp_helpers.h.
 {
     // If any of the 4 texels is out of the image's boundaries we use the border value (REPLICATE or CONSTANT) for any texel out of the image.
     // Sets the 4x4 coordinates for each of the four input texels
     const float8  fc = floor(coords);
     const float16 c1 = (float16)(
                            clamp_to_border_with_size(get_neighbour_coords((float2)(fc.s0, fc.s1)), width, height, border_size),
                            clamp_to_border_with_size(get_neighbour_coords((float2)(fc.s2, fc.s3)), width, height, border_size));
     const float16 c2 = (float16)(
                            clamp_to_border_with_size(get_neighbour_coords((float2)(fc.s4, fc.s5)), width, height, border_size),
                            clamp_to_border_with_size(get_neighbour_coords((float2)(fc.s6, fc.s7)), width, height, border_size));
     // Loads the values from the input image
     const float16 t = (float16)(
                           /* tl, tr, bl, br */
                           * ((__global DATA_TYPE *)offset(in, c1.s0, c1.s1)), *((__global DATA_TYPE *)offset(in, c1.s2, c1.s3)),
                           *((__global DATA_TYPE *)offset(in, c1.s4, c1.s5)), *((__global DATA_TYPE *)offset(in, c1.s6, c1.s7)),
                           *((__global DATA_TYPE *)offset(in, c1.s8, c1.s9)), *((__global DATA_TYPE *)offset(in, c1.sa, c1.sb)),
                           *((__global DATA_TYPE *)offset(in, c1.sc, c1.sd)), *((__global DATA_TYPE *)offset(in, c1.se, c1.sf)),
                           *((__global DATA_TYPE *)offset(in, c2.s0, c2.s1)), *((__global DATA_TYPE *)offset(in, c2.s2, c2.s3)),
                           *((__global DATA_TYPE *)offset(in, c2.s4, c2.s5)), *((__global DATA_TYPE *)offset(in, c2.s6, c2.s7)),
                           *((__global DATA_TYPE *)offset(in, c2.s8, c2.s9)), *((__global DATA_TYPE *)offset(in, c2.sa, c2.sb)),
                           *((__global DATA_TYPE *)offset(in, c2.sc, c2.sd)), *((__global DATA_TYPE *)offset(in, c2.se, c2.sf)));
     const float8 a  = coords - fc;
     const float8 b  = ((float8)(1.f)) - a;
     const float4 fr = (float4)(
                           ((t.s0 * b.s0 * b.s1) + (t.s1 * a.s0 * b.s1) + (t.s2 * b.s0 * a.s1) + (t.s3 * a.s0 * a.s1)),
                           ((t.s4 * b.s2 * b.s3) + (t.s5 * a.s2 * b.s3) + (t.s6 * b.s2 * a.s3) + (t.s7 * a.s2 * a.s3)),
                           ((t.s8 * b.s4 * b.s5) + (t.s9 * a.s4 * b.s5) + (t.sa * b.s4 * a.s5) + (t.sb * a.s4 * a.s5)),
                           ((t.sc * b.s6 * b.s7) + (t.sd * a.s6 * b.s7) + (t.se * b.s6 * a.s7) + (t.sf * a.s6 * a.s7)));
     return CONVERT(fr, VEC_DATA_TYPE(DATA_TYPE, 4));
 }
References arm_compute::test::validation::b, clamp_to_border_with_size(), CONVERT, DATA_TYPE, get_neighbour_coords(), offset(), and VEC_DATA_TYPE.
Referenced by bilinear_interpolate(), and scale_bilinear_nchw().
clamp_to_border()
const float8 clamp_to_border (float8 coords, const float width, const float height) inline
Clamps the given coordinates to the borders.
Parameters
[in] coords Vector of 2D coordinates to clamp. Even positions are X coords, odd positions are Y coords.
[in] width Width of the image
[in] height Height of the image
Definition at line 49 of file warp_helpers.h.
 {
     return clamp_to_border_with_size(coords, width, height, 1);
 }
References clamp_to_border_with_size().
Referenced by remap_bilinear(), remap_nearest_neighbour(), warp_affine_nearest_neighbour(), and warp_perspective_nearest_neighbour().
clamp_to_border_with_size()
const float8 clamp_to_border_with_size (float8 coords, const float width, const float height, const float border_size) inline
Clamps the given coordinates to the borders according to the border size.
Parameters
[in] coords Vector of 2D coordinates to clamp. Even positions are X coords, odd positions are Y coords.
[in] width Width of the image
[in] height Height of the image
[in] border_size Border size of the image
Definition at line 34 of file warp_helpers.h.
 {
     const float4 clamped_x = clamp(coords.even, 0.0f - border_size, width - 1 + border_size);
     const float4 clamped_y = clamp(coords.odd, 0.0f - border_size, height - 1 + border_size);
     return (float8)(clamped_x.s0, clamped_y.s0, clamped_x.s1, clamped_y.s1, clamped_x.s2, clamped_y.s2, clamped_x.s3, clamped_y.s3);
 }
References arm_compute::utility::clamp().
Referenced by bilinear_interpolate_with_border(), clamp_to_border(), and scale_nearest_neighbour_nchw().
get_current_coords()
const float2 get_current_coords () inline
Returns the current thread coordinates.
Definition at line 68 of file warp_helpers.h.
 {
     return (float2)(get_global_id(0) * 4, get_global_id(1));
 }
Referenced by scale_bilinear_nchw(), scale_nearest_neighbour_nchw(), warp_affine_bilinear(), warp_affine_nearest_neighbour(), warp_perspective_bilinear(), and warp_perspective_nearest_neighbour().
get_neighbour_coords()
const float8 get_neighbour_coords (const float2 coord) inline
Given a texel coordinates this function will return the following array of coordinates: [ P, right neighbour, below neighbour, below right neighbour ].
Note
No checks to see if the coordinates are out of the image are done here.
Parameters
[in] coord Input coordinates
Returns
vector of 8 floats with the coordinates, even positions are x and odd y.
Definition at line 82 of file warp_helpers.h.
 {
     return (float8)(/*tl*/ coord.s0, coord.s1, /*tr*/ coord.s0 + 1, coord.s1, /*bl*/ coord.s0, coord.s1 + 1, /*br*/ coord.s0 + 1, coord.s1 + 1);
 }
Referenced by bilinear_interpolate_with_border().
read_texels4()
const DATA_TYPE4 read_texels4 (const Image * in, const int8 coords) inline
Reads four texels from the input image.
The coords vector is used to determine which texels to be read.
Parameters
[in] in Pointer to the source image.
[in] coords Vector of coordinates to be read from the image.
Definition at line 59 of file warp_helpers.h.
 {
     return (VEC_DATA_TYPE(DATA_TYPE, 4))(*((__global DATA_TYPE *)offset(in, coords.s0, coords.s1)),
                                          *((__global DATA_TYPE *)offset(in, coords.s2, coords.s3)),
                                          *((__global DATA_TYPE *)offset(in, coords.s4, coords.s5)),
                                          *((__global DATA_TYPE *)offset(in, coords.s6, coords.s7)));
 }
References DATA_TYPE, offset(), and VEC_DATA_TYPE.
Referenced by remap_nearest_neighbour(), scale_nearest_neighbour_nchw(), warp_affine_nearest_neighbour(), and warp_perspective_nearest_neighbour().