Compute Library: src/core/CL/cl_kernels/depthwise_convolution.cl File Reference
depthwise_convolution.cl File Reference
#include "helpers.h"
Macros
#define CONVOLUTION1x3_BIFROST2X1_STRIDE1(acc, src0, weights_row0)
#define CONVOLUTION1x3_BIFROST2X1_STRIDE2(acc, src0, src1, weights_row0)
Functions
__kernel void depthwise_convolution_3x3_stridex1_stridey1_bifrost (__global uchar *src_ptr, uint src_stride_x, uint src_step_x, uint src_stride_y, uint src_step_y, uint src_stride_z, uint src_step_z, uint src_offset_first_element_in_bytes, __global uchar *dst_ptr, uint dst_stride_x, uint dst_step_x, uint dst_stride_y, uint dst_step_y, uint dst_stride_z, uint dst_step_z, uint dst_offset_first_element_in_bytes, __global uchar *weights_ptr, uint weights_stride_x, uint weights_step_x, uint weights_stride_y, uint weights_step_y, uint weights_stride_z, uint weights_step_z, uint weights_offset_first_element_in_bytes, __global uchar *biases_ptr, uint biases_stride_x, uint biases_step_x, uint biases_offset_first_element_in_bytes)
This OpenCL kernel is optimized for Bifrost architectures and computes the depthwise convolution 3x3 when both stride_x and stride_y are equal to 1.
__kernel void depthwise_convolution_3x3_stridex2_stridey2_bifrost (__global uchar *src_ptr, uint src_stride_x, uint src_step_x, uint src_stride_y, uint src_step_y, uint src_stride_z, uint src_step_z, uint src_offset_first_element_in_bytes, __global uchar *dst_ptr, uint dst_stride_x, uint dst_step_x, uint dst_stride_y, uint dst_step_y, uint dst_stride_z, uint dst_step_z, uint dst_offset_first_element_in_bytes, __global uchar *weights_ptr, uint weights_stride_x, uint weights_step_x, uint weights_stride_y, uint weights_step_y, uint weights_stride_z, uint weights_step_z, uint weights_offset_first_element_in_bytes, __global uchar *biases_ptr, uint biases_stride_x, uint biases_step_x, uint biases_offset_first_element_in_bytes)
This OpenCL kernel is optimized for Bifrost architectures and computes the depthwise convolution 3x3 when both stride_x and stride_y are equal to 2.
Macro Definition Documentation
#define CONVOLUTION1x3_BIFROST2X1_STRIDE1 (acc, src0, weights_row0)
Value:
({                                                             \
        acc.s0 = fma(src0.s0, weights_row0.s0, acc.s0);            \
        acc.s0 = fma(src0.s1, weights_row0.s1, acc.s0);            \
        acc.s0 = fma(src0.s2, weights_row0.s2, acc.s0);            \
        acc.s1 = fma(src0.s1, weights_row0.s0, acc.s1);            \
        acc.s1 = fma(src0.s2, weights_row0.s1, acc.s1);            \
        acc.s1 = fma(src0.s3, weights_row0.s2, acc.s1);            \
    })
Definition at line 211 of file depthwise_convolution.cl.
Referenced by depthwise_convolution_3x3_stridex1_stridey1_bifrost().
#define CONVOLUTION1x3_BIFROST2X1_STRIDE2 (acc, src0, src1, weights_row0)
Value:
({                                                                   \
        acc.s0 = fma(src0.s0, weights_row0.s0, acc.s0);                  \
        acc.s0 = fma(src0.s1, weights_row0.s1, acc.s0);                  \
        acc.s0 = fma(src0.s2, weights_row0.s2, acc.s0);                  \
        acc.s1 = fma(src0.s2, weights_row0.s0, acc.s1);                  \
        acc.s1 = fma(src0.s3, weights_row0.s1, acc.s1);                  \
        acc.s1 = fma(src1.s0, weights_row0.s2, acc.s1);                  \
    })
Definition at line 221 of file depthwise_convolution.cl.
Referenced by depthwise_convolution_3x3_stridex2_stridey2_bifrost().
Function Documentation
__kernel void depthwise_convolution_3x3_stridex1_stridey1_bifrost (__global uchar * src_ptr, uint src_stride_x, uint src_step_x, uint src_stride_y, uint src_step_y, uint src_stride_z, uint src_step_z, uint src_offset_first_element_in_bytes, __global uchar * dst_ptr, uint dst_stride_x, uint dst_step_x, uint dst_stride_y, uint dst_step_y, uint dst_stride_z, uint dst_step_z, uint dst_offset_first_element_in_bytes, __global uchar * weights_ptr, uint weights_stride_x, uint weights_step_x, uint weights_stride_y, uint weights_step_y, uint weights_stride_z, uint weights_step_z, uint weights_offset_first_element_in_bytes, __global uchar * biases_ptr, uint biases_stride_x, uint biases_step_x, uint biases_offset_first_element_in_bytes)
This OpenCL kernel is optimized for Bifrost architectures and computes the depthwise convolution 3x3 when both stride_x and stride_y are equal to 1.
Parameters
[in] src_ptr Pointer to the source image. Supported data types: F32
[in] src_stride_x Stride of the source image in X dimension (in bytes)
[in] src_step_x src_stride_x * number of elements along X processed per workitem(in bytes)
[in] src_stride_y Stride of the source image in Y dimension (in bytes)
[in] src_step_y src_stride_y * number of elements along Y processed per workitem(in bytes)
[in] src_offset_first_element_in_bytes The offset of the first element in the source image
[in] src_stride_z Stride of the source tensor in Z dimension (in bytes)
[in] src_step_z src_stride_z * number of elements along Y processed per workitem(in bytes)
[in] dst_ptr Pointer to the destination tensor. Supported data types: F32
[in] dst_stride_x Stride of the destination tensor in X dimension (in bytes)
[in] dst_step_x dst_stride_x * number of elements along X processed per workitem(in bytes)
[in] dst_stride_y Stride of the destination tensor in Y dimension (in bytes)
[in] dst_step_y dst_stride_y * number of elements along Y processed per workitem(in bytes)
[in] dst_stride_z Stride of the destination tensor in Z dimension (in bytes)
[in] dst_step_z dst_stride_z * number of elements along Y processed per workitem(in bytes)
[in] dst_offset_first_element_in_bytes The offset of the first element in the destination tensor
[in] weights_ptr Pointer to the weights tensor. Supported data types: F32
[in] weights_stride_x Stride of the weights tensor in X dimension (in bytes)
[in] weights_step_x weights_stride_x * number of elements along X processed per workitem(in bytes)
[in] weights_stride_y Stride of the weights tensor in Y dimension (in bytes)
[in] weights_step_y weights_stride_y * number of elements along Y processed per workitem(in bytes)
[in] weights_stride_z Stride of the weights tensor in Z dimension (in bytes)
[in] weights_step_z weights_stride_z * number of elements along Y processed per workitem(in bytes)
[in] weights_offset_first_element_in_bytes The offset of the first element in the biases vector
[in] biases_ptr (Optional) Pointer to the biases vector. Supported data types: F32
[in] biases_stride_x (Optional) Stride of the biases vector in X dimension (in bytes)
[in] biases_step_x (Optional) biases_stride_x * number of elements along X processed per workitem(in bytes)
[in] biases_offset_first_element_in_bytes (Optional) The offset of the first element in the biases vector
Definition at line 263 of file depthwise_convolution.cl.
References CONVERT_TENSOR3D_TO_IMAGE_STRUCT, CONVERT_TO_TENSOR3D_STRUCT, CONVERT_TO_VECTOR_STRUCT_NO_STEP, CONVOLUTION1x3_BIFROST2X1_STRIDE1, offset(), Image::ptr, Tensor3D::ptr, and vector_offset().
 {
     Image    src     = CONVERT_TENSOR3D_TO_IMAGE_STRUCT(src);
     Image    dst     = CONVERT_TENSOR3D_TO_IMAGE_STRUCT(dst);
     Tensor3D weights = CONVERT_TO_TENSOR3D_STRUCT(weights);
     float2 pixels0 = 0.0f;
     float2 pixels1 = 0.0f;
     float2 pixels2 = 0.0f;
     float2 pixels3 = 0.0f;
     __global uchar *weights_addr = (__global uchar *)weights.ptr;
     __global uchar *src_addr     = (__global uchar *)offset(&src, 0, 0);
     // Load the weights
     float3 weights_row0 = vload3(0, (__global float *)(weights_addr + 0 * weights_stride_y));
     float3 weights_row1 = vload3(0, (__global float *)(weights_addr + 1 * weights_stride_y));
     float3 weights_row2 = vload3(0, (__global float *)(weights_addr + 2 * weights_stride_y));
     // Note: Since each work-item computes 4x2 elements, we need to load 4 rows from the input tensor
     float4 src00 = vload4(0, (__global float *)(src_addr + 0 * src_stride_y)); // Row0
     float4 src10 = vload4(0, (__global float *)(src_addr + 1 * src_stride_y)); // Row1
     float4 src20 = vload4(0, (__global float *)(src_addr + 2 * src_stride_y)); // Row2
     float4 src30 = vload4(0, (__global float *)(src_addr + 3 * src_stride_y)); // Row3
     float4 src40 = vload4(0, (__global float *)(src_addr + 4 * src_stride_y)); // Row3
     float4 src50 = vload4(0, (__global float *)(src_addr + 5 * src_stride_y)); // Row3
     CONVOLUTION1x3_BIFROST2X1_STRIDE1(pixels0, src00, weights_row0);
     CONVOLUTION1x3_BIFROST2X1_STRIDE1(pixels0, src10, weights_row1);
     CONVOLUTION1x3_BIFROST2X1_STRIDE1(pixels0, src20, weights_row2);
     CONVOLUTION1x3_BIFROST2X1_STRIDE1(pixels1, src10, weights_row0);
     CONVOLUTION1x3_BIFROST2X1_STRIDE1(pixels1, src20, weights_row1);
     CONVOLUTION1x3_BIFROST2X1_STRIDE1(pixels1, src30, weights_row2);
     CONVOLUTION1x3_BIFROST2X1_STRIDE1(pixels2, src20, weights_row0);
     CONVOLUTION1x3_BIFROST2X1_STRIDE1(pixels2, src30, weights_row1);
     CONVOLUTION1x3_BIFROST2X1_STRIDE1(pixels2, src40, weights_row2);
     CONVOLUTION1x3_BIFROST2X1_STRIDE1(pixels3, src30, weights_row0);
     CONVOLUTION1x3_BIFROST2X1_STRIDE1(pixels3, src40, weights_row1);
     CONVOLUTION1x3_BIFROST2X1_STRIDE1(pixels3, src50, weights_row2);
 #ifdef HAS_BIAS
     Vector biases = CONVERT_TO_VECTOR_STRUCT_NO_STEP(biases);
     float bias = *((__global float *)(vector_offset(&biases, get_global_id(2))));
     pixels0 += (float2)bias;
     pixels1 += (float2)bias;
     pixels2 += (float2)bias;
     pixels3 += (float2)bias;
 #endif /* defined(HAS_BIAS) */
     vstore2(pixels0, 0, (__global float *)(dst.ptr + 0 * dst_stride_y));
     vstore2(pixels1, 0, (__global float *)(dst.ptr + 1 * dst_stride_y));
     vstore2(pixels2, 0, (__global float *)(dst.ptr + 2 * dst_stride_y));
     vstore2(pixels3, 0, (__global float *)(dst.ptr + 3 * dst_stride_y));
 }
__kernel void depthwise_convolution_3x3_stridex2_stridey2_bifrost (__global uchar * src_ptr, uint src_stride_x, uint src_step_x, uint src_stride_y, uint src_step_y, uint src_stride_z, uint src_step_z, uint src_offset_first_element_in_bytes, __global uchar * dst_ptr, uint dst_stride_x, uint dst_step_x, uint dst_stride_y, uint dst_step_y, uint dst_stride_z, uint dst_step_z, uint dst_offset_first_element_in_bytes, __global uchar * weights_ptr, uint weights_stride_x, uint weights_step_x, uint weights_stride_y, uint weights_step_y, uint weights_stride_z, uint weights_step_z, uint weights_offset_first_element_in_bytes, __global uchar * biases_ptr, uint biases_stride_x, uint biases_step_x, uint biases_offset_first_element_in_bytes)
This OpenCL kernel is optimized for Bifrost architectures and computes the depthwise convolution 3x3 when both stride_x and stride_y are equal to 2.
Parameters
[in] src_ptr Pointer to the source image. Supported data types: F32
[in] src_stride_x Stride of the source image in X dimension (in bytes)
[in] src_step_x src_stride_x * number of elements along X processed per workitem(in bytes)
[in] src_stride_y Stride of the source image in Y dimension (in bytes)
[in] src_step_y src_stride_y * number of elements along Y processed per workitem(in bytes)
[in] src_offset_first_element_in_bytes The offset of the first element in the source image
[in] src_stride_z Stride of the source tensor in Z dimension (in bytes)
[in] src_step_z src_stride_z * number of elements along Y processed per workitem(in bytes)
[in] dst_ptr Pointer to the destination tensor. Supported data types: F32
[in] dst_stride_x Stride of the destination tensor in X dimension (in bytes)
[in] dst_step_x dst_stride_x * number of elements along X processed per workitem(in bytes)
[in] dst_stride_y Stride of the destination tensor in Y dimension (in bytes)
[in] dst_step_y dst_stride_y * number of elements along Y processed per workitem(in bytes)
[in] dst_stride_z Stride of the destination tensor in Z dimension (in bytes)
[in] dst_step_z dst_stride_z * number of elements along Y processed per workitem(in bytes)
[in] dst_offset_first_element_in_bytes The offset of the first element in the destination tensor
[in] weights_ptr Pointer to the weights tensor. Supported data types: F32
[in] weights_stride_x Stride of the weights tensor in X dimension (in bytes)
[in] weights_step_x weights_stride_x * number of elements along X processed per workitem(in bytes)
[in] weights_stride_y Stride of the weights tensor in Y dimension (in bytes)
[in] weights_step_y weights_stride_y * number of elements along Y processed per workitem(in bytes)
[in] weights_stride_z Stride of the weights tensor in Z dimension (in bytes)
[in] weights_step_z weights_stride_z * number of elements along Y processed per workitem(in bytes)
[in] weights_offset_first_element_in_bytes The offset of the first element in the biases vector
[in] biases_ptr (Optional) Pointer to the biases vector. Supported data types: F32
[in] biases_stride_x (Optional) Stride of the biases vector in X dimension (in bytes)
[in] biases_step_x (Optional) biases_stride_x * number of elements along X processed per workitem(in bytes)
[in] biases_offset_first_element_in_bytes (Optional) The offset of the first element in the biases vector
Definition at line 360 of file depthwise_convolution.cl.
References CONVERT, CONVERT_TENSOR3D_TO_IMAGE_STRUCT, CONVERT_TO_TENSOR3D_STRUCT, CONVERT_TO_VECTOR_STRUCT, CONVERT_TO_VECTOR_STRUCT_NO_STEP, CONVOLUTION1x3_BIFROST2X1_STRIDE2, DATA_TYPE, IMAGE_DECLARATION, offset(), Vector::ptr, Image::ptr, Tensor3D::ptr, TENSOR3D_DECLARATION, VECTOR_DECLARATION, and vector_offset().
 {
     Image    src     = CONVERT_TENSOR3D_TO_IMAGE_STRUCT(src);
     Image    dst     = CONVERT_TENSOR3D_TO_IMAGE_STRUCT(dst);
     Tensor3D weights = CONVERT_TO_TENSOR3D_STRUCT(weights);
     float2 pixels0 = 0.0f;
     float2 pixels1 = 0.0f;
     __global uchar *weights_addr = (__global uchar *)weights.ptr;
     __global uchar *src_addr     = (__global uchar *)offset(&src, 0, 0);
     // Load the weights
     float3 weights_row0 = vload3(0, (__global float *)(weights_addr + 0 * weights_stride_y));
     float3 weights_row1 = vload3(0, (__global float *)(weights_addr + 1 * weights_stride_y));
     float3 weights_row2 = vload3(0, (__global float *)(weights_addr + 2 * weights_stride_y));
     // Note: Since each work-item computes 4x2 elements, we need to load 5 rows from the input tensor
     float4 src00 = vload4(0, (__global float *)(src_addr + 0 * src_stride_y)); // Row0
     float2 src01 = vload2(2, (__global float *)(src_addr + 0 * src_stride_y)); // Row0
     float4 src10 = vload4(0, (__global float *)(src_addr + 1 * src_stride_y)); // Row1
     float2 src11 = vload2(2, (__global float *)(src_addr + 1 * src_stride_y)); // Row1
     float4 src20 = vload4(0, (__global float *)(src_addr + 2 * src_stride_y)); // Row2
     float2 src21 = vload2(2, (__global float *)(src_addr + 2 * src_stride_y)); // Row2
     float4 src30 = vload4(0, (__global float *)(src_addr + 3 * src_stride_y)); // Row3
     float2 src31 = vload2(2, (__global float *)(src_addr + 3 * src_stride_y)); // Row3
     float4 src40 = vload4(0, (__global float *)(src_addr + 4 * src_stride_y)); // Row4
     float2 src41 = vload2(2, (__global float *)(src_addr + 4 * src_stride_y)); // Row4
     CONVOLUTION1x3_BIFROST2X1_STRIDE2(pixels0, src00, src01, weights_row0);
     CONVOLUTION1x3_BIFROST2X1_STRIDE2(pixels0, src10, src11, weights_row1);
     CONVOLUTION1x3_BIFROST2X1_STRIDE2(pixels0, src20, src21, weights_row2);
     CONVOLUTION1x3_BIFROST2X1_STRIDE2(pixels1, src20, src21, weights_row0);
     CONVOLUTION1x3_BIFROST2X1_STRIDE2(pixels1, src30, src31, weights_row1);
     CONVOLUTION1x3_BIFROST2X1_STRIDE2(pixels1, src40, src41, weights_row2);
 #ifdef HAS_BIAS
     Vector biases = CONVERT_TO_VECTOR_STRUCT_NO_STEP(biases);
     float bias = *((__global float *)(vector_offset(&biases, get_global_id(2))));
     pixels0 += (float2)bias;
     pixels1 += (float2)bias;
 #endif /* defined(HAS_BIAS) */
     vstore2(pixels0, 0, (__global float *)(dst.ptr + 0 * dst_stride_y));
     vstore2(pixels1, 0, (__global float *)(dst.ptr + 1 * dst_stride_y));
 }