Compute Library: src/c/AclOperator.cpp File Reference
AclOperator.cpp File Reference
#include "arm_compute/AclEntrypoints.h"
#include "src/common/IOperator.h"
#include "src/common/IQueue.h"
#include "src/common/TensorPack.h"
#include "src/common/utils/Macros.h"
Functions
AclStatus AclRunOperator (AclOperator external_op, AclQueue external_queue, AclTensorPack external_tensors)
Eager execution of a given operator on a list of inputs and outputs.
AclStatus AclDestroyOperator (AclOperator external_op)
Destroy a given operator object.
Function Documentation
AclDestroyOperator()
AclStatus AclDestroyOperator (AclOperator op)
Destroy a given operator object.
Parameters
[in,out] op A valid operator object to destroy
Returns
Status code
Returns:
AclSuccess if functions was completed successfully
AclInvalidArgument if the provided context is invalid
Definition at line 53 of file AclOperator.cpp.
References AclSuccess, ARM_COMPUTE_RETURN_CENUM_ON_FAILURE, arm_compute::get_internal(), and arm_compute::detail::validate_internal_operator().
 {
     using namespace arm_compute;
     auto op = get_internal(external_op);
     StatusCode status = detail::validate_internal_operator(op);
     ARM_COMPUTE_RETURN_CENUM_ON_FAILURE(status);
     delete op;
     return AclSuccess;
 }
AclRunOperator()
AclStatus AclRunOperator (AclOperator op, AclQueue queue, AclTensorPack tensors)
Eager execution of a given operator on a list of inputs and outputs.
Parameters
[in] op Operator to execute
[in] queue Queue to schedule the operator on
[in,out] tensors A list of input and outputs tensors to execute the operator on
Returns
Status Code
Returns:
AclSuccess if function was completed successfully
AclOutOfMemory if there was a failure allocating memory resources
AclUnsupportedTarget if the requested target is unsupported
AclInvalidArgument if a given argument is invalid
AclRuntimeError on any other runtime related error
Definition at line 31 of file AclOperator.cpp.
References AclSuccess, ARM_COMPUTE_RETURN_CENUM_ON_FAILURE, arm_compute::get_internal(), arm_compute::test::validation::pack, arm_compute::Success, arm_compute::detail::validate_internal_operator(), arm_compute::detail::validate_internal_pack(), and arm_compute::detail::validate_internal_queue().
Referenced by Operator::run().
 {
     using namespace arm_compute;
     auto op    = get_internal(external_op);
     auto queue = get_internal(external_queue);
     auto pack  = get_internal(external_tensors);
     StatusCode status = StatusCode::Success;
     status            = detail::validate_internal_operator(op);
     ARM_COMPUTE_RETURN_CENUM_ON_FAILURE(status);
     status = detail::validate_internal_queue(queue);
     ARM_COMPUTE_RETURN_CENUM_ON_FAILURE(status);
     status = detail::validate_internal_pack(pack);
     ARM_COMPUTE_RETURN_CENUM_ON_FAILURE(status);
     status = op->run(*queue, pack->get_tensor_pack());
     ARM_COMPUTE_RETURN_CENUM_ON_FAILURE(status);
     return AclSuccess;
 }