Compute Library: CLGEMMHeuristicsHandle Class Reference
CLGEMMHeuristicsHandle Class Reference
Handle for loading and retrieving GEMM heuristics.
#include <CLGEMMHeuristicsHandle.h>
Public Member Functions
CLGEMMHeuristicsHandle ()
Constructor.
~CLGEMMHeuristicsHandle ()
Destructor.
CLGEMMHeuristicsHandle (const CLGEMMHeuristicsHandle &)=delete
Prevent Copy Construct.
CLGEMMHeuristicsHandle & operator= (const CLGEMMHeuristicsHandle &)=delete
Prevent Copy Assignment.
CLGEMMHeuristicsHandle (CLGEMMHeuristicsHandle &&)=default
Default Move Constructor.
CLGEMMHeuristicsHandle & operator= (CLGEMMHeuristicsHandle &&)=default
Default Move Assignment.
bool reload_from_file (const std::string &filename)
(Re)Load the heuristics from reading a dotmlgo file
const mlgo::MLGOHeuristics * get () const
Return a pointer to underlying heuristics for querying purposes.
Detailed Description
Handle for loading and retrieving GEMM heuristics.
Definition at line 38 of file CLGEMMHeuristicsHandle.h.
Constructor & Destructor Documentation
CLGEMMHeuristicsHandle() [1/3]
CLGEMMHeuristicsHandle ()
Constructor.
Definition at line 30 of file CLGEMMHeuristicsHandle.cpp.
References CLGEMMHeuristicsHandle::~CLGEMMHeuristicsHandle().
     : _heuristics(std::make_unique<mlgo::MLGOHeuristics>())
 {
 }
~CLGEMMHeuristicsHandle()
~CLGEMMHeuristicsHandle () default
Destructor.
Referenced by CLGEMMHeuristicsHandle::CLGEMMHeuristicsHandle().
CLGEMMHeuristicsHandle() [2/3]
CLGEMMHeuristicsHandle (const CLGEMMHeuristicsHandle &) delete
Prevent Copy Construct.
CLGEMMHeuristicsHandle() [3/3]
CLGEMMHeuristicsHandle (CLGEMMHeuristicsHandle &&) default
Default Move Constructor.
Member Function Documentation
get()
const mlgo::MLGOHeuristics * get () const
Return a pointer to underlying heuristics for querying purposes.
Returns
MLGOHeuristics*
Definition at line 40 of file CLGEMMHeuristicsHandle.cpp.
Referenced by arm_compute::cl_gemm::auto_heuristics::select_mlgo_gemm_config_native(), arm_compute::cl_gemm::auto_heuristics::select_mlgo_gemm_config_reshaped(), arm_compute::cl_gemm::auto_heuristics::select_mlgo_gemm_config_reshaped_only_rhs(), and arm_compute::cl_gemm::auto_heuristics::select_mlgo_gemm_kernel().
 {
     return _heuristics.get();
 }
operator=() [1/2]
CLGEMMHeuristicsHandle& operator= (const CLGEMMHeuristicsHandle &) delete
Prevent Copy Assignment.
operator=() [2/2]
CLGEMMHeuristicsHandle& operator= (CLGEMMHeuristicsHandle &&) default
Default Move Assignment.
reload_from_file()
bool reload_from_file (const std::string & filename)
(Re)Load the heuristics from reading a dotmlgo file
Parameters
[in] filename Path to the dotmlgo file
Returns
bool Signals if the reload succeeded or failed
Definition at line 36 of file CLGEMMHeuristicsHandle.cpp.
Referenced by main(), and CLDeviceBackend::setup_backend_context().
 {
     return _heuristics->reload_from_file(filename);
 }
The documentation for this class was generated from the following files:
arm_compute/runtime/CL/CLGEMMHeuristicsHandle.h
src/runtime/CL/CLGEMMHeuristicsHandle.cpp