Compute Library: CLStackLayer Class Reference
CLStackLayer Class Reference
Basic function to stack tensors along an axis.
#include <CLStackLayer.h>
Public Member Functions
CLStackLayer ()
Default constructor.
CLStackLayer (const CLStackLayer &)=delete
Prevent instances of this class from being copied.
CLStackLayer & operator= (const CLStackLayer &)=delete
Prevent instances of this class from being copied.
CLStackLayer (CLStackLayer &&)=delete
Prevent instances of this class to be moved.
CLStackLayer & operator= (CLStackLayer &&)=delete
Prevent instances of this class to be moved.
~CLStackLayer ()
Default destructor.
void configure (const std::vector< ICLTensor *> &input, int axis, ICLTensor *output)
Initialise the kernel's inputs vector and output.
void configure (const CLCompileContext &compile_context, const std::vector< ICLTensor *> &input, int axis, ICLTensor *output)
Initialise the kernel's inputs vector and output.
void run () override
Run the kernels contained in the function.
Public Member Functions inherited from IFunction
virtual ~IFunction ()=default
Destructor.
virtual void prepare ()
Prepare the function for executing.
Static Public Member Functions
static Status validate (const std::vector< ITensorInfo *> &input, int axis, const ITensorInfo *output)
Static function to check if given info will lead to a valid configuration of CLStackLayerKernel.
Detailed Description
Basic function to stack tensors along an axis.
This function calls the following kernel:
CLStackLayerKernel
Definition at line 45 of file CLStackLayer.h.
Constructor & Destructor Documentation
CLStackLayer() [1/3]
CLStackLayer ()
Default constructor.
Definition at line 41 of file CLStackLayer.cpp.
References CLStackLayer::~CLStackLayer().
     : _input(),
       _stack_kernels(),
       _num_inputs(0)
 {
 }
CLStackLayer() [2/3]
CLStackLayer (const CLStackLayer &) delete
Prevent instances of this class from being copied.
CLStackLayer() [3/3]
CLStackLayer (CLStackLayer &&) delete
Prevent instances of this class to be moved.
~CLStackLayer()
~CLStackLayer () default
Default destructor.
Referenced by CLStackLayer::CLStackLayer().
Member Function Documentation
configure() [1/2]
void configure (const std::vector< ICLTensor *> & input, int axis, ICLTensor * output)
Initialise the kernel's inputs vector and output.
Valid data layouts:
All
Valid data type configurations:
src dst
All All
Note
Supported input tensor rank: up to 4
Parameters
[in] input The vectors containing all the tensors with the same shape to stack. Data types supported: All.
[in] axis The dimension to stack the tensors along. It must be smaller than the number of input dimensions. Negative values wrap around
[out] output Output tensor. Data types supported: Same as input.
Definition at line 50 of file CLStackLayer.cpp.
References CLKernelLibrary::get().
 {
     configure(CLKernelLibrary::get().get_compile_context(), input, axis, output);
 }
configure() [2/2]
void configure (const CLCompileContext & compile_context, const std::vector< ICLTensor *> & input, int axis, ICLTensor * output)
Initialise the kernel's inputs vector and output.
Note
Supported input tensor rank: up to 4
Parameters
[in] compile_context The compile context to be used.
[in] input The vectors containing all the tensors with the same shape to stack. Data types supported: All.
[in] axis The dimension to stack the tensors along. It must be smaller than the number of input dimensions. Negative values wrap around
[out] output Output tensor. Data types supported: Same as input.
Definition at line 55 of file CLStackLayer.cpp.
References ARM_COMPUTE_LOG_PARAMS, arm_compute::test::validation::info, and arm_compute::wrap_around().
 {
     ARM_COMPUTE_LOG_PARAMS(input, axis, output);
     _num_inputs = input.size();
     _stack_kernels.reserve(_num_inputs);
     // Wrap around negative values
     const unsigned int axis_u = wrap_around(axis, static_cast<int>(input[0]->info()->num_dimensions() + 1));
     for(unsigned int i = 0; i < _num_inputs; i++)
     {
         _stack_kernels.emplace_back(std::make_unique<CLStackLayerKernel>());
         _stack_kernels.back()->configure(compile_context, input[i], axis_u, i, _num_inputs, output);
     }
 }
operator=() [1/2]
CLStackLayer& operator= (const CLStackLayer &) delete
Prevent instances of this class from being copied.
operator=() [2/2]
CLStackLayer& operator= (CLStackLayer &&) delete
Prevent instances of this class to be moved.
run()
void run () override virtual
Run the kernels contained in the function.
For CPU kernels:
Multi-threading is used for the kernels which are parallelisable.
By default std::thread::hardware_concurrency() threads are used.
Note
CPPScheduler::set_num_threads() can be used to manually set the number of threads
For OpenCL kernels:
All the kernels are enqueued on the queue associated with CLScheduler.
The queue is then flushed.
Note
The function will not block until the kernels are executed. It is the user's responsibility to wait.
Will call prepare() on first run if hasn't been done
Implements IFunction.
Definition at line 93 of file CLStackLayer.cpp.
References CLScheduler::enqueue(), and CLScheduler::get().
 {
     for(unsigned i = 0; i < _num_inputs; i++)
     {
         CLScheduler::get().enqueue(*_stack_kernels[i], false);
     }
 }
validate()
Status validate (const std::vector< ITensorInfo *> & input, int axis, const ITensorInfo * output) static
Static function to check if given info will lead to a valid configuration of CLStackLayerKernel.
Note
Supported input tensor rank: up to 4
Parameters
[in] input The vectors containing all the tensors info with the same shape to stack. Data types supported: All.
[in] axis The dimension to stack the tensors along. It must be smaller than the number of input dimensions. Negative values wrap around
[in] output Output tensor info. Data types supported: Same as input.
Returns
a status
Definition at line 71 of file CLStackLayer.cpp.
References ARM_COMPUTE_RETURN_ERROR_ON, ARM_COMPUTE_RETURN_ERROR_ON_NULLPTR, ARM_COMPUTE_RETURN_ON_ERROR, CLStackLayerKernel::validate(), and arm_compute::wrap_around().
Referenced by arm_compute::test::validation::DATA_TEST_CASE().
 {
     ARM_COMPUTE_RETURN_ERROR_ON_NULLPTR(output);
     ARM_COMPUTE_RETURN_ERROR_ON(input.empty());
     // Wrap around negative values
     const size_t       rank   = input[0]->num_dimensions();
     const unsigned int axis_u = wrap_around(axis, static_cast<int>(rank + 1));
     const unsigned int num_inputs = input.size();
     for(unsigned int i = 0; i < num_inputs; i++)
     {
         // All the tensors must have the same rank
         ARM_COMPUTE_RETURN_ERROR_ON(input[i]->num_dimensions() != rank);
         // Validate Kernel
         ARM_COMPUTE_RETURN_ON_ERROR(CLStackLayerKernel::validate(input[i], axis_u, i, num_inputs, output));
     }
     return Status{};
 }
The documentation for this class was generated from the following files:
arm_compute/runtime/CL/functions/CLStackLayer.h
src/runtime/CL/functions/CLStackLayer.cpp