Compute Library: NEConv3D Class Reference
NEConv3D Class Reference
Basic function to simulate a 3d convolution.
#include <NEConv3D.h>
Public Member Functions
NEConv3D ()
Constructor.
NEConv3D (const NEConv3D &)=delete
Prevent instances of this class from being copied (As this class contains pointers)
NEConv3D & operator= (const NEConv3D &)=delete
Prevent instances of this class from being copied (As this class contains pointers)
NEConv3D (NEConv3D &&)=default
Default move constructor.
NEConv3D & operator= (NEConv3D &&)=default
Prevent instances of this class from being moved (As this class contains non movable objects)
~NEConv3D ()
Default destructor.
void configure (ITensor *input, const ITensor *weights, const ITensor *biases, ITensor *output, const Conv3dInfo &conv_info)
Set the input and output tensors.
void run () override
Run the kernels contained in the function.
Public Member Functions inherited from IFunction
virtual ~IFunction ()=default
Destructor.
virtual void prepare ()
Prepare the function for executing.
Static Public Member Functions
static Status validate (const ITensorInfo *input, const ITensorInfo *weights, const ITensorInfo *biases, const ITensorInfo *output, const Conv3dInfo &conv_info)
Static function to check if given info will lead to a valid configuration.
Detailed Description
Basic function to simulate a 3d convolution.
This function calls one of the following functions:
cpu::CpuDirectConv3d
Definition at line 44 of file NEConv3D.h.
Constructor & Destructor Documentation
NEConv3D() [1/3]
NEConv3D ()
Constructor.
Definition at line 42 of file NEConv3D.cpp.
References NEConv3D::~NEConv3D().
     : _impl(std::make_unique<Impl>())
 {
 }
NEConv3D() [2/3]
NEConv3D (const NEConv3D &) delete
Prevent instances of this class from being copied (As this class contains pointers)
NEConv3D() [3/3]
NEConv3D (NEConv3D &&) default
Default move constructor.
~NEConv3D()
~NEConv3D () default
Default destructor.
Referenced by NEConv3D::NEConv3D().
Member Function Documentation
configure()
void configure (ITensor * input, const ITensor * weights, const ITensor * biases, ITensor * output, const Conv3dInfo & conv_info)
Set the input and output tensors.
Valid data layouts:
NDHWC
Valid data type configurations:
src0 src1 src2 dst
F16 F16 F16 F16
F32 F32 F32 F32
QASYMM8 QASYMM8 S32 QASYMM8
QASYMM8_SIGNED QASYMM8_SIGNED S32 QASYMM8_SIGNED
Parameters
[in] input Source tensor. 4 lower dimensions represent a single input [IFM, width, height, depth], while every optional dimension from 5 and above represent a batch of inputs.
[in] weights Weights tensor. Weights are 5D tensor with dimensions [OFM, IFM, kernel_x, kernel_y, kernel_z].
[in] biases Biases tensor. Shared biases supported. Biases are 1D tensor with dimensions [OFM].
[out] output Destination tensor. 4 lower dimensions represent a single output [OFM, width, height, depth], while the rest represent batch of outputs.
[in] conv_info Contains padding, stride, acitvation information described in Conv3dInfo.
Definition at line 49 of file NEConv3D.cpp.
References arm_compute::ACL_DST, arm_compute::ACL_SRC_0, arm_compute::ACL_SRC_1, arm_compute::ACL_SRC_2, ARM_COMPUTE_ERROR_ON_NULLPTR, ARM_COMPUTE_ERROR_THROW_ON, ARM_COMPUTE_LOG_PARAMS, arm_compute::test::validation::conv_info, ITensor::info(), and CpuDirectConv3d::validate().
 {
     // Perform validate step
     ARM_COMPUTE_ERROR_ON_NULLPTR(input, weights, output);
     ARM_COMPUTE_ERROR_THROW_ON(cpu::CpuDirectConv3d::validate(input->info(), weights->info(), ((biases != nullptr) ? biases->info() : nullptr), output->info(), conv_info));
     ARM_COMPUTE_LOG_PARAMS(input, weights, biases, output, conv_info);
     auto f = std::make_unique<cpu::CpuDirectConv3d>();
     f->configure(input->info(), weights->info(), ((biases != nullptr) ? biases->info() : nullptr), output->info(), conv_info);
     _impl->op = std::move(f);
     if(_impl->op != nullptr)
     {
         _impl->run_pack = { { ACL_SRC_0, input }, { ACL_SRC_1, weights }, { ACL_SRC_2, biases }, { ACL_DST, output } };
     }
 }
operator=() [1/2]
NEConv3D& operator= (const NEConv3D &) delete
Prevent instances of this class from being copied (As this class contains pointers)
operator=() [2/2]
NEConv3D& operator= (NEConv3D &&) default
Prevent instances of this class from being moved (As this class contains non movable objects)
run()
void run () override virtual
Run the kernels contained in the function.
For CPU kernels:
Multi-threading is used for the kernels which are parallelisable.
By default std::thread::hardware_concurrency() threads are used.
Note
CPPScheduler::set_num_threads() can be used to manually set the number of threads
For OpenCL kernels:
All the kernels are enqueued on the queue associated with CLScheduler.
The queue is then flushed.
Note
The function will not block until the kernels are executed. It is the user's responsibility to wait.
Will call prepare() on first run if hasn't been done
Implements IFunction.
Definition at line 73 of file NEConv3D.cpp.
 {
     if(_impl->op != nullptr)
     {
         _impl->op->run(_impl->run_pack);
     }
 }
validate()
Status validate (const ITensorInfo * input, const ITensorInfo * weights, const ITensorInfo * biases, const ITensorInfo * output, const Conv3dInfo & conv_info) static
Static function to check if given info will lead to a valid configuration.
Similar to NEConv3D::configure()
Returns
a status
Definition at line 66 of file NEConv3D.cpp.
References ARM_COMPUTE_RETURN_ON_ERROR, and CpuDirectConv3d::validate().
Referenced by arm_compute::test::validation::DATA_TEST_CASE().
 {
     ARM_COMPUTE_RETURN_ON_ERROR(cpu::CpuDirectConv3d::validate(input, weights, biases, output, conv_info));
     return Status{};
 }
The documentation for this class was generated from the following files:
arm_compute/runtime/NEON/functions/NEConv3D.h
src/runtime/NEON/functions/NEConv3D.cpp