Compute Library: NDCoordinate< N > Class Template Reference
NDCoordinate< N > Class Template Reference
NDCoordinate builds upon a range, but specifies a starting position in addition to a size which it inherits from NDRange.
#include <ndrange.hpp>
Public Member Functions
NDCoordinate & operator= (const NDCoordinate &rhs)=default
NDCoordinate (const NDCoordinate &rhs)=default
NDCoordinate (const std::initializer_list< std::pair< int_t, int_t >> &list)
int_t get_position (int_t d) const
void set_position (int_t d, int_t v)
int_t get_position_end (int_t d) const
Public Member Functions inherited from NDRange< N >
NDRange & operator= (const NDRange &rhs)=default
NDRange (const NDRange &rhs)=default
NDRange (T... ts)
NDRange (const std::array< unsigned int, D > &n)
NDRangeIterator iterator (unsigned int start, unsigned int end) const
unsigned int total_size () const
unsigned int get_size (unsigned int v) const
Detailed Description
template<unsigned int N>
class arm_gemm::NDCoordinate< N >
NDCoordinate builds upon a range, but specifies a starting position in addition to a size which it inherits from NDRange.
Definition at line 151 of file ndrange.hpp.
Constructor & Destructor Documentation
NDCoordinate() [1/2]
NDCoordinate (const NDCoordinate< N > & rhs) default
NDCoordinate() [2/2]
NDCoordinate (const std::initializer_list< std::pair< int_t, int_t >> & list) inline
Definition at line 161 of file ndrange.hpp.
     {
         std::array<int_t, N> sizes{};
         std::size_t i = 0;
         for(auto &p : list)
         {
             m_positions[i] = p.first;
             sizes[i++]     = p.second;
         }
         //update the parents sizes
         static_cast<ndrange_t &>(*this) = ndrange_t(sizes);
     }
Member Function Documentation
get_position()
int_t get_position (int_t d) const inline
Definition at line 176 of file ndrange.hpp.
References N.
Referenced by GemvPretransposed< strategy, To, Tr, OutputStage >::execute(), GemmHybrid< strategy, To, Tr >::execute(), GemmHybridQuantizedInline< strategy, To, Tr >::execute(), GemmHybridQuantized< strategy, To, Tr >::execute(), GemmInterleavedPretransposed2d< strategy, To, Tr >::execute(), GemmHybridIndirect< strategy, To, Tr, OutputStage, SeparateQuantize, FixedFormat >::execute(), GemmInterleaved< strategy, To, Tr, OutputStage, MergeStep, FixedFormat, ForceThreadColumns >::execute(), and arm_gemm::to_window().
     {
         assert(d < N);
         return m_positions[d];
     }
get_position_end()
int_t get_position_end (int_t d) const inline
Definition at line 190 of file ndrange.hpp.
References NDRange< D >::get_size().
Referenced by GemvPretransposed< strategy, To, Tr, OutputStage >::execute(), GemmHybrid< strategy, To, Tr >::execute(), GemmHybridQuantizedInline< strategy, To, Tr >::execute(), GemmHybridQuantized< strategy, To, Tr >::execute(), GemmHybridIndirect< strategy, To, Tr, OutputStage, SeparateQuantize, FixedFormat >::execute(), and GemmInterleaved< strategy, To, Tr, OutputStage, MergeStep, FixedFormat, ForceThreadColumns >::execute().
     {
         return get_position(d) + ndrange_t::get_size(d);
     }
operator=()
NDCoordinate& operator= (const NDCoordinate< N > & rhs) default
set_position()
void set_position (int_t d, int_t v) inline
Definition at line 183 of file ndrange.hpp.
References N.
     {
         assert(d < N);
         m_positions[d] = v;
     }
The documentation for this class was generated from the following file:
src/cpu/kernels/assembly/ndrange.hpp