Compute Library: NEElementwiseSquaredDiff Class Reference
NEElementwiseSquaredDiff Class Reference
Basic function to run cpu::kernels::CpuArithmeticKernel for squared difference.
#include <NEElementwiseOperations.h>
Public Member Functions
NEElementwiseSquaredDiff ()
Default Constructor.
~NEElementwiseSquaredDiff ()
Default Destructor.
NEElementwiseSquaredDiff (const NEElementwiseSquaredDiff &)=delete
Prevent instances of this class from being copied (As this class contains pointers)
NEElementwiseSquaredDiff (NEElementwiseSquaredDiff &&)
Default move constructor.
NEElementwiseSquaredDiff & operator= (const NEElementwiseSquaredDiff &)=delete
Prevent instances of this class from being copied (As this class contains pointers)
NEElementwiseSquaredDiff & operator= (NEElementwiseSquaredDiff &&)
Default move assignment operator.
void configure (ITensor *input1, ITensor *input2, ITensor *output, const ActivationLayerInfo &act_info=ActivationLayerInfo())
Initialise the kernel's inputs, output and conversion policy.
void run () override
Run the kernels contained in the function.
Public Member Functions inherited from IFunction
virtual ~IFunction ()=default
Destructor.
virtual void prepare ()
Prepare the function for executing.
Static Public Member Functions
static Status validate (const ITensorInfo *input1, const ITensorInfo *input2, const ITensorInfo *output, const ActivationLayerInfo &act_info=ActivationLayerInfo())
Static function to check if given info will lead to a valid configuration of cpu::kernels::CpuArithmeticKernel for squared difference.
Detailed Description
Basic function to run cpu::kernels::CpuArithmeticKernel for squared difference.
Note
The tensor data type for the inputs must be QASYMM8/QASYMM8_SIGNED/S16/F16/S32/F32.
The function performs a squared different operation between two tensors (i.e., out[i] = (in1[i] - in2[i])^2
Definition at line 160 of file NEElementwiseOperations.h.
Constructor & Destructor Documentation
NEElementwiseSquaredDiff() [1/3]
NEElementwiseSquaredDiff ()
Default Constructor.
Definition at line 124 of file NEElementwiseOperations.cpp.
References NEElementwiseSquaredDiff::operator=(), and NEElementwiseSquaredDiff::~NEElementwiseSquaredDiff().
     : _impl(std::make_unique<Impl>())
 {
 }
~NEElementwiseSquaredDiff()
~NEElementwiseSquaredDiff () default
Default Destructor.
Referenced by NEElementwiseSquaredDiff::NEElementwiseSquaredDiff().
NEElementwiseSquaredDiff() [2/3]
NEElementwiseSquaredDiff (const NEElementwiseSquaredDiff &) delete
Prevent instances of this class from being copied (As this class contains pointers)
NEElementwiseSquaredDiff() [3/3]
NEElementwiseSquaredDiff (NEElementwiseSquaredDiff &&) default
Default move constructor.
Member Function Documentation
configure()
void configure (ITensor * input1, ITensor * input2, ITensor * output, const ActivationLayerInfo & act_info = ActivationLayerInfo())
Initialise the kernel's inputs, output and conversion policy.
Valid data layouts:
All
Valid data type configurations:
src0 src1 dst
QASYMM8 QASYMM8 QASYMM8
QASYMM8_SIGNED QASYMM8_SIGNED QASYMM8_SIGNED
S32 S32 S32
S16 S16 S16
F16 F16 F16
F32 F32 F32
Parameters
[in,out] input1 First tensor input. Data types supported: QASYMM8/QASYMM8_SIGNED/S16/F16/S32/F32.
[in,out] input2 Second tensor input. Data types supported: Same as input1.
[out] output Output tensor. Data types supported: Same as input1.
[in] act_info (Optional) Activation layer information in case of a fused activation. Currently not supported.
Definition at line 132 of file NEElementwiseOperations.cpp.
References ARM_COMPUTE_UNUSED, and ITensor::info().
 {
     ARM_COMPUTE_UNUSED(act_info);
     _impl->src_0 = input1;
     _impl->src_1 = input2;
     _impl->dst   = output;
     _impl->op    = std::make_unique<cpu::CpuElementwiseSquaredDiff>();
     _impl->op->configure(input1->info(), input2->info(), output->info());
 }
operator=() [1/2]
NEElementwiseSquaredDiff& operator= (const NEElementwiseSquaredDiff &) delete
Prevent instances of this class from being copied (As this class contains pointers)
Referenced by NEElementwiseSquaredDiff::NEElementwiseSquaredDiff().
operator=() [2/2]
NEElementwiseSquaredDiff & operator= (NEElementwiseSquaredDiff &&) default
Default move assignment operator.
run()
void run () override virtual
Run the kernels contained in the function.
For CPU kernels:
Multi-threading is used for the kernels which are parallelisable.
By default std::thread::hardware_concurrency() threads are used.
Note
CPPScheduler::set_num_threads() can be used to manually set the number of threads
For OpenCL kernels:
All the kernels are enqueued on the queue associated with CLScheduler.
The queue is then flushed.
Note
The function will not block until the kernels are executed. It is the user's responsibility to wait.
Will call prepare() on first run if hasn't been done
Implements IFunction.
Definition at line 148 of file NEElementwiseOperations.cpp.
References arm_compute::ACL_DST, arm_compute::ACL_SRC_0, arm_compute::ACL_SRC_1, ITensorPack::add_tensor(), arm_compute::test::validation::dst, and arm_compute::test::validation::pack.
 {
     ITensorPack pack;
     pack.add_tensor(TensorType::ACL_SRC_0, _impl->src_0);
     pack.add_tensor(TensorType::ACL_SRC_1, _impl->src_1);
     pack.add_tensor(TensorType::ACL_DST, _impl->dst);
     _impl->op->run(pack);
 }
validate()
Status validate (const ITensorInfo * input1, const ITensorInfo * input2, const ITensorInfo * output, const ActivationLayerInfo & act_info = ActivationLayerInfo()) static
Static function to check if given info will lead to a valid configuration of cpu::kernels::CpuArithmeticKernel for squared difference.
Parameters
[in] input1 First tensor input info. Data types supported: QASYMM8/QASYMM8_SIGNED/S16/F16/S32/F32.
[in] input2 Second tensor input info. Data types supported: Same as input1.
[in] output Output tensor info. Data types supported: Same as input1.
[in] act_info (Optional) Activation layer information in case of a fused activation. Currently not supported.
Returns
a status
Definition at line 142 of file NEElementwiseOperations.cpp.
References ARM_COMPUTE_RETURN_ERROR_ON, ActivationLayerInfo::enabled(), and CpuElementwiseArithmetic< op >::validate().
Referenced by arm_compute::test::validation::DATA_TEST_CASE().
 {
     ARM_COMPUTE_RETURN_ERROR_ON(act_info.enabled());
     return cpu::CpuElementwiseSquaredDiff::validate(input1, input2, output);
 }
The documentation for this class was generated from the following files:
arm_compute/runtime/NEON/functions/NEElementwiseOperations.h
src/runtime/NEON/functions/NEElementwiseOperations.cpp