Compute Library: ClCompositeOperator Class Reference
ClCompositeOperator Class Reference
Operator runtime to run a ClWorkload.
#include <ClCompositeOperator.h>
Public Member Functions
ClCompositeOperator ()
~ClCompositeOperator ()
void configure (const CLCompileContext &ctx, const ClWorkload &workload)
Configures a ClCompositeOperator with a ClWorkload This includes the compilation of Cl kernels inside the ClWorkload.
void prepare (TensorPackMap &tensor_pack_map)
Enqueue prepare workloads.
void run (TensorPackMap &tensor_pack_map)
Enqueue run workloads.
Static Public Member Functions
static Status validate (const ClWorkload &workload)
Validate ClWorkload workload.
Detailed Description
Operator runtime to run a ClWorkload.
Note
User must explicitly call prepare before run otherwise run will fail.
Examples:
dynamic_fusion/cl_fused_conv2d_elementwise_add.cpp.
Definition at line 151 of file ClCompositeOperator.h.
Constructor & Destructor Documentation
ClCompositeOperator()
ClCompositeOperator ()
Definition at line 167 of file ClCompositeOperator.cpp.
References ClCompositeOperator::~ClCompositeOperator().
     : _impl{ std::make_unique<Implementation>() }
 {
 }
~ClCompositeOperator()
~ClCompositeOperator () default
Referenced by ClCompositeOperator::ClCompositeOperator().
Member Function Documentation
configure()
void configure (const CLCompileContext & ctx, const ClWorkload & workload)
Configures a ClCompositeOperator with a ClWorkload This includes the compilation of Cl kernels inside the ClWorkload.
Parameters
[in] ctx CLCompileContext
[in] workload ClWorkload to configure with
Definition at line 174 of file ClCompositeOperator.cpp.
References ARM_COMPUTE_ERROR, ARM_COMPUTE_ERROR_THROW_ON, IWorkload::graph, arm_compute::test::validation::k, UnitWorkloadStage::Prepare, UnitWorkloadStage::Run, DependencyGraph::topological_sort(), ClWorkload::unit_workloads, ClCompositeOperator::validate(), and arm_compute::test::validation::workload.
Referenced by arm_compute::test::validation::TEST_CASE().
 {
     ARM_COMPUTE_ERROR_THROW_ON(ClCompositeOperator::validate(workload));
     _impl->_workload = workload;
     // Traverse workloads in topological order
     const auto sorted = workload.graph.topological_sort().second;
     for(const auto &node : sorted)
     {
         auto work  = workload.unit_workloads.at(node.op);
         auto stage = work.stage.stage;
         auto k     = std::make_unique<ClCompositeKernel>();
         k->configure(ctx, work.code);
         switch(stage)
         {
             case UnitWorkloadStage::Stage::Run:
                 _impl->_kernels.emplace(work.id, std::move(k));
                 break;
             case UnitWorkloadStage::Stage::Prepare:
                 _impl->_kernels_prep.emplace(work.id, std::move(k));
                 break;
             default:
                 ARM_COMPUTE_ERROR("Invalid stage");
         }
         break;
     }
 }
prepare()
void prepare (TensorPackMap & tensor_pack_map)
Enqueue prepare workloads.
Parameters
tensor_pack_map Tensors required by the prepare workloads
Definition at line 208 of file ClCompositeOperator.cpp.
References CLScheduler::enqueue_op(), CLScheduler::get(), and TensorPackMap::get_tensor_pack().
Referenced by arm_compute::test::validation::TEST_CASE().
 {
     if(!_impl->_is_prepared)
     {
         for(auto &id_kernel_pair : _impl->_kernels_prep)
         {
             const bool flush_queue = false;
             const auto uwk_id      = id_kernel_pair.first;
             auto       kernel      = id_kernel_pair.second.get();
             CLScheduler::get().enqueue_op(*kernel, tensor_pack_map.get_tensor_pack(uwk_id), ClExecutionDescriptor{}, flush_queue);
         }
         _impl->_is_prepared = true;
     }
 }
run()
void run (TensorPackMap & tensor_pack_map)
Enqueue run workloads.
Parameters
tensor_pack_map Tensors required by the run workloads
Definition at line 224 of file ClCompositeOperator.cpp.
References ARM_COMPUTE_ERROR_ON_MSG, CLScheduler::enqueue_op(), CLScheduler::get(), and TensorPackMap::get_tensor_pack().
Referenced by arm_compute::test::validation::TEST_CASE().
 {
     ARM_COMPUTE_ERROR_ON_MSG(!_impl->_is_prepared, "Operator is not prepared");
     for(auto &id_kernel_pair : _impl->_kernels)
     {
         // Flush the command queue on the last kernel
         const bool flush_queue = false;
         const auto uwk_id      = id_kernel_pair.first;
         auto       kernel      = id_kernel_pair.second.get();
         CLScheduler::get().enqueue_op(*kernel, tensor_pack_map.get_tensor_pack(uwk_id), ClExecutionDescriptor{}, flush_queue);
     }
 }
validate()
Status validate (const ClWorkload & workload) static
Validate ClWorkload workload.
Parameters
[in] workload ClWorkload to be validated
Returns
Status
Definition at line 203 of file ClCompositeOperator.cpp.
References ClWorkload::status.
Referenced by ClCompositeOperator::configure(), and arm_compute::test::validation::TEST_CASE().
 {
     return workload.status;
 }
The documentation for this class was generated from the following files:
arm_compute/runtime/experimental/ClCompositeOperator.h
src/gpu/cl/operators/experimental/dynamic_fusion/ClCompositeOperator.cpp