Compute Library: ClSoftmax Class Reference
ClSoftmax Class Reference
#include <ClSoftmax.h>
Public Member Functions
ClSoftmax ()
Constructor.
void configure (const CLCompileContext &compile_context, const ITensorInfo &src, ITensorInfo &dst, const SoftmaxKernelInfo &info)
Configure the operator.
void run (ITensorPack &tensors) override
Run the kernels contained in the function.
experimental::MemoryRequirements workspace () const override
Return the memory requirements required by the workspace.
Public Member Functions inherited from ICLOperator
ICLOperator (IRuntimeContext *ctx=nullptr)
Constructor.
ICLOperator (const ICLOperator &)=delete
Prevent instances of this class from being copied (As this class contains pointers)
ICLOperator (ICLOperator &&)=default
Default move constructor.
ICLOperator & operator= (const ICLOperator &)=delete
Prevent instances of this class from being copied (As this class contains pointers)
ICLOperator & operator= (ICLOperator &&)=default
Default move assignment operator.
void prepare (ITensorPack &constants) override
Prepare the function for executing.
Public Member Functions inherited from IOperator
virtual ~IOperator ()=default
Destructor.
Static Public Member Functions
static Status validate (const ITensorInfo &src, const ITensorInfo &dst, const SoftmaxKernelInfo &info)
Static function to check if given info will lead to a valid configuration.
Detailed Description
Definition at line 43 of file ClSoftmax.h.
Constructor & Destructor Documentation
ClSoftmax()
ClSoftmax ()
Constructor.
Definition at line 41 of file ClSoftmax.cpp.
     : _permute_input(std::make_unique<ClPermute>()),
       _permute_output(std::make_unique<ClPermute>()),
       _max_shift_exp_sum_kernel(std::make_unique<kernels::ClLogits1DMaxShiftExpSumKernel>()),
       _norm_kernel(std::make_unique<kernels::ClLogits1DNormKernel>()),
       _max_info(),
       _sum_info(),
       _tmp_info(),
       _permuted_src_info(),
       _permuted_dst_info(),
       _aux_mem(InternalTensorIdx::COUNT)
 {
 }
Member Function Documentation
configure()
void configure (const CLCompileContext & compile_context, const ITensorInfo & src, ITensorInfo & dst, const SoftmaxKernelInfo & info)
Configure the operator.
Parameters
[in] compile_context The compile context to be used.
[in] src Source tensor info. Data types supported: QASYMM8/QASYMM8_SIGNED/F16/F32 for Softmax and F16/F32 for Log Softmax
[out] dst Destination tensor info. Data types supported: same as src
[in] info Contains information consumed by kernels for softmax described in SoftmaxKernelInfo.
Definition at line 55 of file ClSoftmax.cpp.
References ARM_COMPUTE_ERROR_THROW_ON, ARM_COMPUTE_LOG_PARAMS, SoftmaxKernelInfo::axis, ICloneable< T >::clone(), ITensorInfo::data_type(), arm_compute::test::validation::dst, CLScheduler::get(), arm_compute::softmax_helpers::get_permutation_vector_from_softmax_axis(), arm_compute::is_data_type_quantized_asymmetric(), arm_compute::MAX, ITensorInfo::num_dimensions(), arm_compute::offset_int_vec(), arm_compute::S32, arm_compute::test::validation::src, arm_compute::SUM, ITensorInfo::tensor_shape(), TensorInfo::total_size(), ClSoftmax::validate(), and arm_compute::wrap_around().
 {
     ARM_COMPUTE_ERROR_THROW_ON(validate(src, dst, info));
     ARM_COMPUTE_LOG_PARAMS(src, dst, info);
     const size_t actual_axis = static_cast<size_t>(wrap_around(info.axis, static_cast<int32_t>(src.num_dimensions())));
     _needs_permute = actual_axis != 0;
     const ITensorInfo &tmp_input_info  = _needs_permute ? _permuted_src_info : src;
     ITensorInfo       &tmp_output_info = _needs_permute ? _permuted_dst_info : dst;
     if(_needs_permute)
     {
         const auto perm_info = softmax_helpers::get_permutation_vector_from_softmax_axis(actual_axis);
         _permute_input->configure(compile_context, &src, &_permuted_src_info, perm_info);
     }
     DataType tmp_data_type = is_data_type_quantized_asymmetric(tmp_input_info.data_type()) ? DataType::S32 : tmp_input_info.data_type();
     _tmp_info              = tmp_input_info.clone()->set_data_type(tmp_data_type);
     TensorShape max_sum_shape = tmp_input_info.tensor_shape();
     _max_info                 = tmp_input_info.clone()->set_tensor_shape(max_sum_shape);
     _sum_info                 = tmp_input_info.clone()->set_tensor_shape(max_sum_shape).set_data_type(tmp_data_type);
     // Set GPU target to kernels
     _max_shift_exp_sum_kernel->set_target(CLScheduler::get().target());
     _max_shift_exp_sum_kernel->configure(compile_context, tmp_input_info, _max_info, _tmp_info, _sum_info, info);
     _norm_kernel->configure(compile_context, _tmp_info, _sum_info, tmp_output_info, info);
     if(_needs_permute)
     {
         const auto perm_info = softmax_helpers::get_permutation_vector_from_softmax_axis(actual_axis);
         _permute_output->configure(compile_context, &_permuted_dst_info, &dst, perm_info);
     }
     _aux_mem[InternalTensorIdx::SUM] = MemoryInfo(offset_int_vec(InternalTensorIdx::SUM), MemoryLifetime::Temporary, _sum_info.total_size());
     _aux_mem[InternalTensorIdx::TMP] = MemoryInfo(offset_int_vec(InternalTensorIdx::TMP), MemoryLifetime::Temporary, _tmp_info.total_size());
     _aux_mem[InternalTensorIdx::MAX] = MemoryInfo(offset_int_vec(InternalTensorIdx::MAX), MemoryLifetime::Temporary, _max_info.total_size());
     _aux_mem[InternalTensorIdx::PERMUTED_SRC] = MemoryInfo(offset_int_vec(InternalTensorIdx::PERMUTED_SRC), MemoryLifetime::Temporary, _permuted_src_info.total_size());
     _aux_mem[InternalTensorIdx::PERMUTED_DST] = MemoryInfo(offset_int_vec(InternalTensorIdx::PERMUTED_DST), MemoryLifetime::Temporary, _permuted_dst_info.total_size());
 }
run()
void run (ITensorPack & tensors) override virtual
Run the kernels contained in the function.
Parameters
[in] tensors Vector that contains the tensors to operate on.
Reimplemented from ICLOperator.
Definition at line 133 of file ClSoftmax.cpp.
References arm_compute::ACL_DST, arm_compute::ACL_INT_0, arm_compute::ACL_INT_1, arm_compute::ACL_SRC, ITensorPack::add_const_tensor(), ITensorPack::add_tensor(), arm_compute::test::validation::dst, CLScheduler::enqueue_op(), CLScheduler::get(), CLAuxTensorHandler::get(), ITensorPack::get_const_tensor(), ITensorPack::get_tensor(), arm_compute::MAX, arm_compute::offset_int_vec(), arm_compute::test::validation::pack, arm_compute::test::validation::src, and arm_compute::SUM.
 {
     auto src = tensors.get_const_tensor(TensorType::ACL_SRC);
     auto dst = tensors.get_tensor(TensorType::ACL_DST);
     CLAuxTensorHandler sum(offset_int_vec(InternalTensorIdx::SUM), _sum_info, tensors, false);
     CLAuxTensorHandler tmp(offset_int_vec(InternalTensorIdx::TMP), _tmp_info, tensors, false);
     CLAuxTensorHandler max(offset_int_vec(InternalTensorIdx::MAX), _max_info, tensors, false);
     CLAuxTensorHandler permuted_src(offset_int_vec(InternalTensorIdx::PERMUTED_SRC), _permuted_src_info, tensors, false);
     CLAuxTensorHandler permuted_dst(offset_int_vec(InternalTensorIdx::PERMUTED_DST), _permuted_dst_info, tensors, false);
     if(_needs_permute)
     {
         ITensorPack pack;
         pack.add_const_tensor(TensorType::ACL_SRC, src);
         pack.add_tensor(TensorType::ACL_DST, permuted_src.get());
         _permute_input.get()->run(pack);
     }
     ITensorPack sum_pack;
     ITensorPack norm_pack;
     if(_needs_permute)
     {
         sum_pack.add_const_tensor(TensorType::ACL_SRC, permuted_src.get());
         norm_pack.add_tensor(TensorType::ACL_DST, permuted_dst.get());
     }
     else
     {
         sum_pack.add_const_tensor(TensorType::ACL_SRC, src);
         norm_pack.add_tensor(TensorType::ACL_DST, dst);
     }
     sum_pack.add_tensor(TensorType::ACL_DST, tmp.get());
     sum_pack.add_tensor(TensorType::ACL_INT_0, max.get());
     sum_pack.add_tensor(TensorType::ACL_INT_1, sum.get());
     norm_pack.add_const_tensor(TensorType::ACL_SRC, tmp.get());
     norm_pack.add_tensor(TensorType::ACL_INT_0, sum.get());
     CLScheduler::get().enqueue_op(*_max_shift_exp_sum_kernel.get(), sum_pack, false);
     CLScheduler::get().enqueue_op(*_norm_kernel.get(), norm_pack, false);
     if(_needs_permute)
     {
         ITensorPack pack;
         pack.add_const_tensor(TensorType::ACL_SRC, permuted_dst.get());
         pack.add_tensor(TensorType::ACL_DST, dst);
         _permute_output.get()->run(pack);
     }
 }
validate()
Status validate (const ITensorInfo & src, const ITensorInfo & dst, const SoftmaxKernelInfo & info) static
Static function to check if given info will lead to a valid configuration.
Similar to ClSoftmax::configure()
Returns
a status
Definition at line 100 of file ClSoftmax.cpp.
References ARM_COMPUTE_RETURN_ERROR_ON, ARM_COMPUTE_RETURN_ERROR_ON_MSG, ARM_COMPUTE_RETURN_ON_ERROR, ARM_COMPUTE_UNUSED, SoftmaxKernelInfo::axis, SoftmaxKernelInfo::beta, ICloneable< T >::clone(), arm_compute::misc::shape_calculator::compute_permutation_output_shape(), ITensorInfo::data_type(), arm_compute::softmax_helpers::get_permutation_vector_from_softmax_axis(), arm_compute::is_data_type_quantized_asymmetric(), ITensorInfo::num_dimensions(), arm_compute::S32, TensorShape::set(), ITensorInfo::tensor_shape(), ClPermute::validate(), ClLogits1DMaxShiftExpSumKernel::validate(), ClLogits1DNormKernel::validate(), and arm_compute::wrap_around().
Referenced by ClSoftmax::configure().
 {
     ARM_COMPUTE_RETURN_ERROR_ON_MSG(src.num_dimensions() > 4, "Only up to 4 dimensions are supported");
     ARM_COMPUTE_UNUSED(info.beta);
     ARM_COMPUTE_RETURN_ERROR_ON(info.axis < static_cast<int32_t>(-src.num_dimensions()) || static_cast<int32_t>(src.num_dimensions()) <= info.axis);
     const size_t actual_axis   = static_cast<size_t>(wrap_around(info.axis, static_cast<int32_t>(src.num_dimensions())));
     const bool   needs_permute = actual_axis != 0;
     if(needs_permute)
     {
         const PermutationVector permutation_vector = softmax_helpers::get_permutation_vector_from_softmax_axis(actual_axis);
         const TensorShape       permuted_shape     = misc::shape_calculator::compute_permutation_output_shape(src, permutation_vector);
         TensorInfo              input_permuted(src.clone()->set_tensor_shape(permuted_shape));
         ARM_COMPUTE_RETURN_ON_ERROR(ClPermute::validate(&src, &input_permuted, permutation_vector));
         TensorInfo output_permuted(dst.clone()->set_tensor_shape(permuted_shape));
         ARM_COMPUTE_RETURN_ON_ERROR(ClPermute::validate(&output_permuted, &dst, permutation_vector));
     }
     // Create intermediate tensor info
     DataType   tmp_data_type = is_data_type_quantized_asymmetric(src.data_type()) ? DataType::S32 : src.data_type();
     TensorInfo tensor_info_tmp(src.clone()->set_data_type(tmp_data_type).set_is_resizable(true));
     TensorShape max_sum_shape = src.tensor_shape();
     max_sum_shape.set(0, 1);
     TensorInfo tensor_info_max(src.clone()->set_tensor_shape(max_sum_shape).set_is_resizable(true));
     TensorInfo tensor_info_sum(src.clone()->set_tensor_shape(max_sum_shape).set_data_type(tmp_data_type).set_quantization_info(QuantizationInfo()).set_is_resizable(true));
     ARM_COMPUTE_RETURN_ON_ERROR(kernels::ClLogits1DMaxShiftExpSumKernel::validate(src, tensor_info_max, tensor_info_tmp, tensor_info_sum));
     ARM_COMPUTE_RETURN_ON_ERROR(kernels::ClLogits1DNormKernel::validate(tensor_info_tmp, tensor_info_sum, dst, info));
     return Status{};
 }
workspace()
experimental::MemoryRequirements workspace () const override virtual
Return the memory requirements required by the workspace.
Reimplemented from ICLOperator.
Definition at line 184 of file ClSoftmax.cpp.
 {
     return _aux_mem;
 }
The documentation for this class was generated from the following files:
src/gpu/cl/operators/ClSoftmax.h
src/gpu/cl/operators/ClSoftmax.cpp