Compute Library: CLComparisonStatic< COP > Class Template Reference
CLComparisonStatic< COP > Class Template Reference
Basic function to run CLComparisonKernel.
#include <CLComparison.h>
Public Member Functions
void configure (ICLTensor *input1, ICLTensor *input2, ICLTensor *output)
Comparison operations used by the class.
void configure (const CLCompileContext &compile_context, ICLTensor *input1, ICLTensor *input2, ICLTensor *output)
Comparison operations used by the class.
Public Member Functions inherited from ICLSimpleFunction
ICLSimpleFunction (CLRuntimeContext *ctx=nullptr)
Constructor.
ICLSimpleFunction (const ICLSimpleFunction &)=delete
Prevent instances of this class from being copied (As this class contains pointers)
ICLSimpleFunction (ICLSimpleFunction &&)=default
Default move constructor.
ICLSimpleFunction & operator= (const ICLSimpleFunction &)=delete
Prevent instances of this class from being copied (As this class contains pointers)
ICLSimpleFunction & operator= (ICLSimpleFunction &&)=default
Default move assignment operator.
~ICLSimpleFunction ()
Default destructor.
void run () override final
Run the kernels contained in the function.
Public Member Functions inherited from IFunction
virtual ~IFunction ()=default
Destructor.
virtual void prepare ()
Prepare the function for executing.
Static Public Member Functions
static Status validate (const ITensorInfo *input1, const ITensorInfo *input2, const ITensorInfo *output)
Static function to check if given info will lead to a valid configuration of CLComparison.
Static Public Attributes
static constexpr ComparisonOperation operation = COP
Detailed Description
template<ComparisonOperation COP>
class arm_compute::CLComparisonStatic< COP >
Basic function to run CLComparisonKernel.
Definition at line 84 of file CLComparison.h.
Member Function Documentation
configure() [1/2]
void configure (ICLTensor * input1, ICLTensor * input2, ICLTensor * output)
Comparison operations used by the class.
Initialise the kernel's inputs and outputs.
Parameters
[in] input1 Source tensor. Data types supported: All. The input1 tensor is [in, out] because its TensorInfo might be modified inside the kernel in case of broadcasting of dimension 0.
[in] input2 Source tensor. Data types supported: Same as input1. The input2 tensor is [in, out] because its TensorInfo might be modified inside the kernel in case of broadcasting of dimension 0.
[out] output Destination tensor. Data types supported: U8.
Definition at line 64 of file CLComparison.cpp.
References CLComparison::configure(), and CLKernelLibrary::get().
 {
     configure(CLKernelLibrary::get().get_compile_context(), input1, input2, output);
 }
configure() [2/2]
void configure (const CLCompileContext & compile_context, ICLTensor * input1, ICLTensor * input2, ICLTensor * output)
Comparison operations used by the class.
Initialise the kernel's inputs and outputs.
Parameters
[in] compile_context The compile context to be used.
[in] input1 Source tensor. Data types supported: All. The input1 tensor is [in, out] because its TensorInfo might be modified inside the kernel in case of broadcasting of dimension 0.
[in] input2 Source tensor. Data types supported: Same as input1. The input2 tensor is [in, out] because its TensorInfo might be modified inside the kernel in case of broadcasting of dimension 0.
[out] output Destination tensor. Data types supported: U8.
Definition at line 70 of file CLComparison.cpp.
References ITensorInfo::dimension(), ITensor::info(), arm_compute::test::validation::k, and arm_compute::REPLICATE.
 {
     auto k = std::make_unique<CLComparisonKernel>();
     k->configure(compile_context, input1, input2, output, COP);
     _kernel = std::move(k);
     if(output->info()->dimension(0) > 1)
     {
         ICLTensor *broadcasted_info = (input1->info()->dimension(0) == 1) ? input1 : input2;
         if(broadcasted_info->info()->dimension(0) == 1)
         {
             _border_handler->configure(compile_context, broadcasted_info, _kernel->border_size(), BorderMode::REPLICATE);
         }
     }
 }
validate()
Status validate (const ITensorInfo * input1, const ITensorInfo * input2, const ITensorInfo * output) static
Static function to check if given info will lead to a valid configuration of CLComparison.
Parameters
[in] input1 Source tensor. Data types supported: All.
[in] input2 Source tensor. Data types supported: Same as input1.
[in] output Destination tensor. Data types supported: U8.
Returns
a status
Definition at line 88 of file CLComparison.cpp.
References CLComparisonKernel::validate().
 {
     return CLComparisonKernel::validate(input1, input2, output, COP);
 }
Field Documentation
operation
constexpr ComparisonOperation operation = COP static
Definition at line 87 of file CLComparison.h.
The documentation for this class was generated from the following files:
arm_compute/runtime/CL/functions/CLComparison.h
src/runtime/CL/functions/CLComparison.cpp