Compute Library: NEROIPoolingLayerKernel Class Reference
NEROIPoolingLayerKernel Class Reference
Interface for the ROI pooling layer kernel.
#include <NEROIPoolingLayerKernel.h>
Public Member Functions
const char * name () const override
Name of the kernel.
NEROIPoolingLayerKernel ()
Default constructor.
NEROIPoolingLayerKernel (const NEROIPoolingLayerKernel &)=delete
Prevent instances of this class from being copied (As this class contains pointers)
NEROIPoolingLayerKernel & operator= (const NEROIPoolingLayerKernel &)=delete
Prevent instances of this class from being copied (As this class contains pointers)
NEROIPoolingLayerKernel (NEROIPoolingLayerKernel &&)=default
Allow instances of this class to be moved.
NEROIPoolingLayerKernel & operator= (NEROIPoolingLayerKernel &&)=default
Allow instances of this class to be moved.
~NEROIPoolingLayerKernel ()=default
Default destructor.
void configure (const ITensor *input, const ITensor *rois, const ITensor *output, const ROIPoolingLayerInfo &pool_info)
Set the input and output tensors.
void run (const Window &window, const ThreadInfo &info) override
Execute the kernel on the passed window.
Public Member Functions inherited from ICPPKernel
virtual ~ICPPKernel ()=default
Default destructor.
virtual void run_nd (const Window &window, const ThreadInfo &info, const Window &thread_locator)
legacy compatibility layer for implemantions which do not support thread_locator In these cases we simply narrow the interface down the legacy version
virtual void run_op (ITensorPack &tensors, const Window &window, const ThreadInfo &info)
Execute the kernel on the passed window.
virtual size_t get_mws (const CPUInfo &platform, size_t thread_count) const
Return minimum workload size of the relevant kernel.
Public Member Functions inherited from IKernel
IKernel ()
Constructor.
virtual ~IKernel ()=default
Destructor.
virtual bool is_parallelisable () const
Indicates whether or not the kernel is parallelisable.
virtual BorderSize border_size () const
The size of the border for that kernel.
const Window & window () const
The maximum window the kernel can be executed on.
bool is_window_configured () const
Function to check if the embedded window of this kernel has been configured.
Static Public Member Functions
static Status validate (const ITensorInfo *input, const ITensorInfo *rois, const ITensorInfo *output, const ROIPoolingLayerInfo &pool_info)
Static function to check if given info will lead to a valid configuration of NEROIPoolingLayerKernel.
Additional Inherited Members
Static Public Attributes inherited from ICPPKernel
static constexpr size_t default_mws = 1
Detailed Description
Interface for the ROI pooling layer kernel.
Definition at line 33 of file NEROIPoolingLayerKernel.h.
Constructor & Destructor Documentation
NEROIPoolingLayerKernel() [1/3]
NEROIPoolingLayerKernel ()
Default constructor.
Definition at line 110 of file NEROIPoolingLayerKernel.cpp.
Referenced by NEROIPoolingLayerKernel::name().
     : _input(nullptr), _rois(nullptr), _output(nullptr), _pool_info(0, 0, 0.f)
 {
 }
NEROIPoolingLayerKernel() [2/3]
NEROIPoolingLayerKernel (const NEROIPoolingLayerKernel &) delete
Prevent instances of this class from being copied (As this class contains pointers)
NEROIPoolingLayerKernel() [3/3]
NEROIPoolingLayerKernel (NEROIPoolingLayerKernel &&) default
Allow instances of this class to be moved.
~NEROIPoolingLayerKernel()
~NEROIPoolingLayerKernel () default
Default destructor.
Referenced by NEROIPoolingLayerKernel::name().
Member Function Documentation
configure()
void configure (const ITensor * input, const ITensor * rois, const ITensor * output, const ROIPoolingLayerInfo & pool_info)
Set the input and output tensors.
Parameters
[in] input Source tensor. Data types supported: QASYMM8/F32
[in] rois ROIs tensor, it is a 2D tensor of size [5, N] (where N is the number of ROIs) containing top left and bottom right corner as coordinate of an image and batch_id of ROI [ batch_id, x1, y1, x2, y2 ]. Data types supported: U16
[out] output Destination tensor. Data types supported: Same as input.
[in] pool_info Contains pooling operation information described in ROIPoolingLayerInfo.
Note
The x and y dimensions of output tensor must be the same as that specified by pool_info 's pooled width and pooled height.
The z dimensions of output tensor and input tensor must be the same.
The fourth dimension of output tensor must be the same as the number of elements in rois tensor.
Definition at line 121 of file NEROIPoolingLayerKernel.cpp.
References ARM_COMPUTE_ERROR_ON, ARM_COMPUTE_ERROR_ON_MISMATCHING_DATA_TYPES, ARM_COMPUTE_ERROR_ON_NULLPTR, ARM_COMPUTE_ERROR_THROW_ON, arm_compute::auto_init_if_empty(), ITensorInfo::data_type(), ITensorInfo::dimension(), Window::DimX, Window::DimY, ITensor::info(), arm_compute::test::validation::input, arm_compute::test::validation::output_shape, ROIPoolingLayerInfo::pooled_height(), ROIPoolingLayerInfo::pooled_width(), ITensorInfo::quantization_info(), Window::set(), arm_compute::cpu::kernels::validate_arguments(), and IKernel::window().
Referenced by NEROIPoolingLayerKernel::name().
 {
     ARM_COMPUTE_ERROR_ON_NULLPTR(input, output, rois);
     //Validate arguments
     ARM_COMPUTE_ERROR_THROW_ON(validate_arguments(input->info(), rois->info(), output->info(), pool_info));
     // Output auto initialization if not yet initialized
     TensorShape output_shape(pool_info.pooled_width(), pool_info.pooled_height(), input->info()->dimension(2), rois->info()->dimension(1));
     auto_init_if_empty(*output->info(), output_shape, 1, input->info()->data_type(), output->info()->quantization_info());
     ARM_COMPUTE_ERROR_ON_MISMATCHING_DATA_TYPES(input, output);
     ARM_COMPUTE_ERROR_ON((output->info()->dimension(0) != pool_info.pooled_width()) || (output->info()->dimension(1) != pool_info.pooled_height()));
     // Set instance variables
     _input     = input;
     _rois      = rois;
     _output    = output;
     _pool_info = pool_info;
     // Configure kernel window
     Window window;
     window.set(Window::DimX, Window::Dimension(0, rois->info()->dimension(1)));
     window.set(Window::DimY, Window::Dimension(0, 1));
     INEKernel::configure(window);
 }
name()
const char* name () const inline override virtual
Name of the kernel.
Returns
Kernel name
Implements ICPPKernel.
Definition at line 36 of file NEROIPoolingLayerKernel.h.
References NEROIPoolingLayerKernel::configure(), arm_compute::test::validation::info, arm_compute::test::validation::input, NEROIPoolingLayerKernel::NEROIPoolingLayerKernel(), NEROIPoolingLayerKernel::operator=(), NEROIPoolingLayerKernel::run(), NEROIPoolingLayerKernel::validate(), IKernel::window(), and NEROIPoolingLayerKernel::~NEROIPoolingLayerKernel().
     {
         return "NEROIPoolingLayerKernel";
     }
operator=() [1/2]
NEROIPoolingLayerKernel& operator= (const NEROIPoolingLayerKernel &) delete
Prevent instances of this class from being copied (As this class contains pointers)
Referenced by NEROIPoolingLayerKernel::name().
operator=() [2/2]
NEROIPoolingLayerKernel& operator= (NEROIPoolingLayerKernel &&) default
Allow instances of this class to be moved.
run()
void run (const Window & window, const ThreadInfo & info) override virtual
Execute the kernel on the passed window.
Warning
If is_parallelisable() returns false then the passed window must be equal to window()
Note
The window has to be a region within the window returned by the window() method
The width of the window has to be a multiple of num_elems_processed_per_iteration().
Parameters
[in] window Region on which to execute the kernel. (Must be a region of the window returned by window())
[in] info Info about executing thread and CPU.
Reimplemented from ICPPKernel.
Definition at line 150 of file NEROIPoolingLayerKernel.cpp.
References ARM_COMPUTE_ERROR, ARM_COMPUTE_ERROR_ON_INVALID_SUBWINDOW, ARM_COMPUTE_ERROR_ON_UNCONFIGURED_KERNEL, ARM_COMPUTE_UNUSED, ITensor::buffer(), arm_compute::test::validation::data_type, ITensorInfo::data_type(), ITensorInfo::dimension(), Window::DimX, Window::DimY, Window::DimZ, Window::Dimension::end(), arm_compute::F32, ITensor::info(), ROIPoolingLayerInfo::pooled_height(), ROIPoolingLayerInfo::pooled_width(), arm_compute::QASYMM8, arm_compute::support::cpp11::round(), ROIPoolingLayerInfo::spatial_scale(), Window::Dimension::start(), IKernel::window(), and Window::x().
Referenced by NEROIPoolingLayerKernel::name().
 {
     ARM_COMPUTE_UNUSED(info);
     ARM_COMPUTE_ERROR_ON_UNCONFIGURED_KERNEL(this);
     ARM_COMPUTE_ERROR_ON_INVALID_SUBWINDOW(INEKernel::window(), window);
     const size_t values_per_roi = _rois->info()->dimension(0);
     const int   roi_list_start = window.x().start();
     const int   roi_list_end   = window.x().end();
     const int   width          = _input->info()->dimension(Window::DimX);
     const int   height         = _input->info()->dimension(Window::DimY);
     const int   fms            = _input->info()->dimension(Window::DimZ);
     const int   pooled_w       = _pool_info.pooled_width();
     const int   pooled_h       = _pool_info.pooled_height();
     const float spatial_scale  = _pool_info.spatial_scale();
     const auto *rois_ptr  = reinterpret_cast<const uint16_t *>(_rois->buffer());
     const auto  data_type = _input->info()->data_type();
     for(int roi_indx = roi_list_start; roi_indx < roi_list_end; ++roi_indx)
     {
         const unsigned int roi_batch = rois_ptr[values_per_roi * roi_indx];
         const auto         x1        = rois_ptr[values_per_roi * roi_indx + 1];
         const auto         y1        = rois_ptr[values_per_roi * roi_indx + 2];
         const auto         x2        = rois_ptr[values_per_roi * roi_indx + 3];
         const auto         y2        = rois_ptr[values_per_roi * roi_indx + 4];
         // Scale ROI
         const int roi_anchor_x = support::cpp11::round(x1 * spatial_scale);
         const int roi_anchor_y = support::cpp11::round(y1 * spatial_scale);
         const int roi_width    = std::max(support::cpp11::round((x2 - x1) * spatial_scale), 1.f);
         const int roi_height   = std::max(support::cpp11::round((y2 - y1) * spatial_scale), 1.f);
         // Iterate through all feature maps
         for(int fm = 0; fm < fms; ++fm)
         {
             // Iterate through all output pixels
             for(int py = 0; py < pooled_h; ++py)
             {
                 for(int px = 0; px < pooled_w; ++px)
                 {
                     auto region_start_x = static_cast<int>(std::floor((static_cast<float>(px) / pooled_w) * roi_width));
                     auto region_end_x   = static_cast<int>(std::floor((static_cast<float>(px + 1) / pooled_w) * roi_width));
                     auto region_start_y = static_cast<int>(std::floor((static_cast<float>(py) / pooled_h) * roi_height));
                     auto region_end_y   = static_cast<int>(std::floor((static_cast<float>(py + 1) / pooled_h) * roi_height));
                     region_start_x = std::min(std::max(region_start_x + roi_anchor_x, 0), width);
                     region_end_x   = std::min(std::max(region_end_x + roi_anchor_x, 0), width);
                     region_start_y = std::min(std::max(region_start_y + roi_anchor_y, 0), height);
                     region_end_y   = std::min(std::max(region_end_y + roi_anchor_y, 0), height);
                     switch(data_type)
                     {
                         case DataType::F32:
                             template_eval<float>(_input, _output, region_start_x, region_start_y, region_end_x, region_end_y, fm, px, py, roi_batch, roi_indx);
                             break;
                         case DataType::QASYMM8:
                             template_eval<qasymm8_t>(_input, _output, region_start_x, region_start_y, region_end_x, region_end_y, fm, px, py, roi_batch, roi_indx);
                             break;
                         default:
                             ARM_COMPUTE_ERROR("DataType not Supported");
                             break;
                     }
                 }
             }
         }
     }
 }
validate()
Status validate (const ITensorInfo * input, const ITensorInfo * rois, const ITensorInfo * output, const ROIPoolingLayerInfo & pool_info) static
Static function to check if given info will lead to a valid configuration of NEROIPoolingLayerKernel.
Parameters
[in] input Source tensor info. Data types supported: QASYMM8/F32.
[in] rois ROIs tensor info. Data types supported: U16
[in] output Destination tensor info. Data types supported: Same as input.
[in] pool_info Contains pooling operation information described in ROIPoolingLayerInfo.
Note
The x and y dimensions of output tensor must be the same as pool_info 's pooled width and pooled height.
The datatype of output should be the same as the datatype of input
The fourth dimension of output tensor must be the same as the number of elements in rois array.
Returns
a Status
Definition at line 115 of file NEROIPoolingLayerKernel.cpp.
References ARM_COMPUTE_RETURN_ON_ERROR, and arm_compute::cpu::kernels::validate_arguments().
Referenced by NEROIPoolingLayerKernel::name(), and NEROIPoolingLayer::validate().
 {
     ARM_COMPUTE_RETURN_ON_ERROR(validate_arguments(input, rois, output, pool_info));
     return Status{};
 }
The documentation for this class was generated from the following files:
src/core/NEON/kernels/NEROIPoolingLayerKernel.h
src/core/NEON/kernels/NEROIPoolingLayerKernel.cpp