Compute Library: ClFloorKernelComponent Class Reference
ClFloorKernelComponent Class Reference
#include <ClFloorKernelComponent.h>
Public Member Functions
ClFloorKernelComponent (ClKernelBlueprint *blueprint, const Link &src, const Link &dst)
Construct a new Cl Floor Kernel Component object.
ComponentType get_component_type () const override
std::set< std::string > get_headers_list () const override
std::string get_component_code () const override
Window get_window () const override
CLBuildOptions generate_build_options () const override
std::string generate_config_id () const override
Generate config id of the component.
virtual std::vector< Link > get_links () const override
virtual TagLUT get_tag_lut (const SharedVarTable &vtable) const override
Get the tag look-up table used to instantiate the component code.
virtual void allocate_shared_vars (SharedVarTable &vtable) const override
Allocate all shared variables used by the component in the vtable.
virtual std::string name () const override
Public Member Functions inherited from IClKernelComponent
IClKernelComponent (ClKernelBlueprint *blueprint)
ARM_COMPUTE_DISALLOW_COPY_ALLOW_MOVE (IClKernelComponent)
virtual ~IClKernelComponent ()=default
ComponentID id () const
void set_id (ComponentID id)
virtual std::string get_additional_macros () const
virtual std::string get_dst_addr_calculation () const
Additional Inherited Members
Public Types inherited from IClKernelComponent
using Link = SharedVarLink
using Tag = std::string
using TagLUT = std::unordered_map< Tag, TagVal >
Static Public Member Functions inherited from IClKernelComponent
static std::string replace_tags (const std::string &code_template, const TagLUT &tags)
Detailed Description
Definition at line 37 of file ClFloorKernelComponent.h.
Constructor & Destructor Documentation
ClFloorKernelComponent()
ClFloorKernelComponent (ClKernelBlueprint * blueprint, const Link & src, const Link & dst) inline
Construct a new Cl Floor Kernel Component object.
Parameters
blueprint Blueprint to which this component is added
src Link to SRC tensor
dst Link to DST tensor
Support Level Data Type: F16, F32 Tensor Shape: Any shape of arbitrary dimension >= 1 and <= 4 Value Range: All
Definition at line 51 of file ClFloorKernelComponent.h.
References arm_compute::test::validation::dst, ClFloorKernelComponent::generate_build_options(), ClFloorKernelComponent::generate_config_id(), ClFloorKernelComponent::get_component_code(), ClFloorKernelComponent::get_component_type(), ClFloorKernelComponent::get_headers_list(), and ClFloorKernelComponent::get_window().
         : IClKernelComponent(blueprint), _src{ src }, _dst{ dst }
     {
     }
Member Function Documentation
allocate_shared_vars()
void allocate_shared_vars (SharedVarTable & vtable) const override virtual
Allocate all shared variables used by the component in the vtable.
Parameters
vtable
Implements IClKernelComponent.
Definition at line 124 of file ClFloorKernelComponent.cpp.
References SharedVarTable::add(), SharedVarLink::arg_id, and arm_compute::experimental::dynamic_fusion::Tensor_4D_t_Buffer.
Referenced by ClFloorKernelComponent::get_links().
 {
     vtable.add(_src, _blueprint->impl().group(_src.arg_id), ClKernelArgDescriptor(_src.arg_id, ClKernelTensorArgType::Tensor_4D_t_Buffer), "src");
     vtable.add(_dst, _blueprint->impl().group(_dst.arg_id), ClKernelArgDescriptor(_dst.arg_id, ClKernelTensorArgType::Tensor_4D_t_Buffer), "dst");
 }
generate_build_options()
CLBuildOptions generate_build_options () const override virtual
Reimplemented from IClKernelComponent.
Definition at line 99 of file ClFloorKernelComponent.cpp.
References CLBuildOptions::add_option(), and arm_compute::support::cpp11::to_string().
Referenced by ClFloorKernelComponent::ClFloorKernelComponent().
 {
     CLBuildOptions     build_opts{};
     const auto         n0               = _blueprint->impl().get_execution_window().x().step();
     const auto         m0               = _blueprint->impl().get_execution_window().y().step();
     const auto         dst_info         = _blueprint->impl().get_kernel_argument_info(_blueprint->impl().get_dst_id());
     const unsigned int partial_store_n0 = dst_info->dimension(0) % n0;
     build_opts.add_option("-DM0=" + support::cpp11::to_string(m0));
     build_opts.add_option("-DN0=" + support::cpp11::to_string(n0));
     build_opts.add_option("-DPARTIAL_N0=" + support::cpp11::to_string(partial_store_n0));
     return build_opts;
 }
generate_config_id()
std::string generate_config_id () const override virtual
Generate config id of the component.
Returns
std::string
Reimplemented from IClKernelComponent.
Definition at line 111 of file ClFloorKernelComponent.cpp.
References arm_compute::lower_string(), arm_compute::string_from_data_layout(), arm_compute::string_from_data_type(), arm_compute::test::validation::t_dst_info, and arm_compute::support::cpp11::to_string().
Referenced by ClFloorKernelComponent::ClFloorKernelComponent().
 {
     auto        t_dst_info = _blueprint->impl().get_kernel_argument_info(_blueprint->impl().get_dst_id());
     std::string config_id{};
     config_id += lower_string(string_from_data_type(t_dst_info->data_type()));
     config_id += "_";
     config_id += support::cpp11::to_string(t_dst_info->dimension(0));
     config_id += "_";
     config_id += support::cpp11::to_string(t_dst_info->dimension(1));
     config_id += "_";
     config_id += lower_string(string_from_data_layout(t_dst_info->data_layout()));
     return config_id;
 }
get_component_code()
std::string get_component_code () const override virtual
Reimplemented from IClKernelComponent.
Definition at line 64 of file ClFloorKernelComponent.cpp.
References SharedVarLink::arg_id, and arm_compute::experimental::dynamic_fusion::Argument.
Referenced by ClFloorKernelComponent::ClFloorKernelComponent().
 {
     bool is_root = _blueprint->impl().group(_src.arg_id) == SharedVarGroup::Argument;
     if(is_root)
     {
         return R"_(
     //------------------ START KERNEL {{meta_kernel_id}} FLOOR ---------------------
     // IN_0(src)            {{src}}
     // OUT(dst, accum)      {{dst}}
     TILE({{DATA_TYPE}}, M0, N0, {{dst}});
     {
         TILE({{DATA_TYPE}}, M0, N0, src_tile);
         // Since mout maps to dimensions 1 (y) and dimension 2 (z) of the input tensor because of the collapsed window, bout maps to dimension 3 (w)
         {{src}}_offset_first_element_in_bytes += bout * {{src}}_stride_w;
         T_LOAD({{DATA_TYPE}}, M0, N0, BUFFER, {{src}}, cout, mout, 1, {{src}}_stride_y, src_tile);
         T_FLOOR({{DATA_TYPE}}, M0, N0, src_tile, {{dst}});
     }
     //------------------ END KERNEL {{meta_kernel_id}} FLOOR ---------------------
 )_";
     }
     else
     {
         return R"_(
     //------------------ START KERNEL {{meta_kernel_id}} FLOOR ---------------------
     // IN_0/Out(Accumulator)        {{acc}}
     // output = floor(input)
     {
         T_FLOOR({{DATA_TYPE}}, M0, N0, {{acc}}, {{acc}});
     }
     //------------------ END KERNEL {{meta_kernel_id}} FLOOR ---------------------
 )_";
     }
 }
get_component_type()
ComponentType get_component_type () const override virtual
Implements IClKernelComponent.
Definition at line 38 of file ClFloorKernelComponent.cpp.
References arm_compute::experimental::dynamic_fusion::Simple.
Referenced by ClFloorKernelComponent::ClFloorKernelComponent().
 {
     return ComponentType::Simple;
 }
get_headers_list()
std::set< std::string > get_headers_list () const override virtual
Reimplemented from IClKernelComponent.
Definition at line 42 of file ClFloorKernelComponent.cpp.
Referenced by ClFloorKernelComponent::ClFloorKernelComponent().
 {
     return std::set<std::string> { "common/experimental/gemm_fused_post_ops/fp_mixed_precision_helpers.h", "tile_helpers.h" };
 }
get_links()
virtual std::vector<Link> get_links () const inline override virtual
Implements IClKernelComponent.
Definition at line 63 of file ClFloorKernelComponent.h.
References ClFloorKernelComponent::allocate_shared_vars(), and ClFloorKernelComponent::get_tag_lut().
     {
         return { _src, _dst };
     }
get_tag_lut()
ClFloorKernelComponent::TagLUT get_tag_lut (const SharedVarTable & vtable) const override virtual
Get the tag look-up table used to instantiate the component code.
Parameters
vtable
Returns
TagLUT
Implements IClKernelComponent.
Definition at line 129 of file ClFloorKernelComponent.cpp.
References SharedVarLink::arg_id, arm_compute::experimental::dynamic_fusion::Argument, SharedVarTable::get(), arm_compute::get_cl_type_from_data_type(), IClKernelComponent::id(), and arm_compute::test::validation::t_dst_info.
Referenced by ClFloorKernelComponent::get_links().
 {
     TagLUT     lut{};
     const auto t_dst_info = _blueprint->impl().get_kernel_argument_info(_blueprint->impl().get_dst_id());
     // Arguments and global shared variables
     const bool is_root = _blueprint->impl().group(_src.arg_id) == SharedVarGroup::Argument;
     if(is_root)
     {
         lut["src"] = vtable.get(_src);
         lut["dst"] = vtable.get(_dst);
     }
     else
     {
         lut["acc"] = vtable.get(_src);
     }
     lut["meta_kernel_id"] = id();
     lut["DATA_TYPE"]      = get_cl_type_from_data_type(t_dst_info->data_type());
     return lut;
 }
get_window()
Window get_window () const override virtual
Reimplemented from IClKernelComponent.
Definition at line 46 of file ClFloorKernelComponent.cpp.
References arm_compute::adjust_vec_size(), SharedVarLink::arg_id, ARM_COMPUTE_ERROR_ON_NULLPTR, arm_compute::auto_init_if_empty(), arm_compute::calculate_max_window(), TensorShape::collapse(), ITensorInfo::data_type(), ITensorInfo::dimension(), ITensorInfo::element_size(), num_elems_processed_per_iteration, arm_compute::test::validation::output_shape, arm_compute::test::validation::src_info, ITensorInfo::tensor_shape(), and arm_compute::utils::cast::U.
Referenced by ClFloorKernelComponent::ClFloorKernelComponent().
 {
     const ITensorInfo *src_info = _blueprint->impl().get_kernel_argument_info(_src.arg_id);
     ITensorInfo       *dst_info = _blueprint->impl().get_kernel_argument_info(_blueprint->impl().get_dst_id());
     ARM_COMPUTE_ERROR_ON_NULLPTR(src_info, dst_info);
     auto_init_if_empty(*dst_info, src_info->tensor_shape(), 1, src_info->data_type());
     TensorShape output_shape = dst_info->tensor_shape();
     // Collapse Dim 1 (W) and Dim 2 (H) together, leave Dim 0 (C) and upper dimensions unchanged
     // This is in line with the collapsing convention used by Conv2d
     output_shape.collapse(2U, 1U);
     const unsigned int vector_size_byte_opencl           = 16;
     const unsigned int num_elems_processed_per_iteration = adjust_vec_size(vector_size_byte_opencl / dst_info->element_size(), dst_info->dimension(0));
     Window             win                               = calculate_max_window(output_shape, Steps(num_elems_processed_per_iteration));
     return win;
 }
name()
virtual std::string name () const inline override virtual
Implements IClKernelComponent.
Definition at line 71 of file ClFloorKernelComponent.h.
References arm_compute::experimental::dynamic_fusion::to_string().
     {
         return "floor_" + std::to_string(id());
     }
The documentation for this class was generated from the following files:
src/core/experimental/dynamic_fusion/ClKernelBuildingImpl/components/ClFloorKernelComponent.h
src/core/experimental/dynamic_fusion/ClKernelBuildingImpl/components/ClFloorKernelComponent.cpp