Compute Library: OperatorGraph Class Reference
OperatorGraph Class Reference final
Graph of operators to execute within a Workload.
#include <OperatorGraph.h>
Data Structures
struct Implementation
Public Member Functions
OperatorGraph ()
~OperatorGraph ()
Implementation * impl ()
const Implementation * impl () const
Detailed Description
Graph of operators to execute within a Workload.
This is a pure descriptive construct.
Examples:
dynamic_fusion/cl_fused_conv2d_elementwise_add.cpp.
Definition at line 42 of file OperatorGraph.h.
Constructor & Destructor Documentation
OperatorGraph()
OperatorGraph ()
Definition at line 104 of file OperatorGraph.cpp.
References OperatorGraph::~OperatorGraph().
     : _impl{ std::make_unique<Implementation>() }
 {
 }
~OperatorGraph()
~OperatorGraph () default
Referenced by OperatorGraph::OperatorGraph().
Member Function Documentation
impl() [1/2]
OperatorGraph::Implementation * impl ()
Definition at line 111 of file OperatorGraph.cpp.
Referenced by arm_compute::experimental::dynamic_fusion::add_op_conv2d(), arm_compute::experimental::dynamic_fusion::add_op_elementwise_op(), arm_compute::experimental::dynamic_fusion::add_op_floor(), arm_compute::experimental::dynamic_fusion::add_tensor(), arm_compute::experimental::dynamic_fusion::build(), arm_compute::experimental::dynamic_fusion::force_conv2d_method(), and arm_compute::experimental::dynamic_fusion::validate().
 {
     return _impl.get();
 }
impl() [2/2]
const OperatorGraph::Implementation * impl () const
Definition at line 116 of file OperatorGraph.cpp.
 {
     return _impl.get();
 }
The documentation for this class was generated from the following files:
arm_compute/core/experimental/OperatorGraph.h
src/core/experimental/dynamic_fusion/OperatorGraph.cpp