Compute Library: CPPBoxWithNonMaximaSuppressionLimit Class Reference
CPPBoxWithNonMaximaSuppressionLimit Class Reference
Basic function to run CPPBoxWithNonMaximaSuppressionLimitKernel.
#include <CPPBoxWithNonMaximaSuppressionLimit.h>
Public Member Functions
CPPBoxWithNonMaximaSuppressionLimit (std::shared_ptr< IMemoryManager > memory_manager=nullptr)
Constructor.
CPPBoxWithNonMaximaSuppressionLimit (const CPPBoxWithNonMaximaSuppressionLimit &)=delete
Prevent instances of this class from being copied (As this class contains pointers)
CPPBoxWithNonMaximaSuppressionLimit & operator= (const CPPBoxWithNonMaximaSuppressionLimit &)=delete
Prevent instances of this class from being copied (As this class contains pointers)
void configure (const ITensor *scores_in, const ITensor *boxes_in, const ITensor *batch_splits_in, ITensor *scores_out, ITensor *boxes_out, ITensor *classes, ITensor *batch_splits_out=nullptr, ITensor *keeps=nullptr, ITensor *keeps_size=nullptr, const BoxNMSLimitInfo info=BoxNMSLimitInfo())
Configure the BoxWithNonMaximaSuppressionLimit CPP kernel.
void run () override
Run the kernels contained in the function.
Public Member Functions inherited from IFunction
virtual ~IFunction ()=default
Destructor.
virtual void prepare ()
Prepare the function for executing.
Static Public Member Functions
static Status validate (const ITensorInfo *scores_in, const ITensorInfo *boxes_in, const ITensorInfo *batch_splits_in, const ITensorInfo *scores_out, const ITensorInfo *boxes_out, const ITensorInfo *classes, const ITensorInfo *batch_splits_out=nullptr, const ITensorInfo *keeps=nullptr, const ITensorInfo *keeps_size=nullptr, const BoxNMSLimitInfo info=BoxNMSLimitInfo())
Static function to check if given info will lead to a valid configuration of CPPDetectionOutputLayer.
Detailed Description
Basic function to run CPPBoxWithNonMaximaSuppressionLimitKernel.
Definition at line 39 of file CPPBoxWithNonMaximaSuppressionLimit.h.
Constructor & Destructor Documentation
CPPBoxWithNonMaximaSuppressionLimit() [1/2]
CPPBoxWithNonMaximaSuppressionLimit (std::shared_ptr< IMemoryManager > memory_manager = nullptr)
Constructor.
Definition at line 112 of file CPPBoxWithNonMaximaSuppressionLimit.cpp.
     : _memory_group(std::move(memory_manager)),
       _box_with_nms_limit_kernel(),
       _scores_in(),
       _boxes_in(),
       _batch_splits_in(),
       _scores_out(),
       _boxes_out(),
       _classes(),
       _batch_splits_out(),
       _keeps(),
       _scores_in_f32(),
       _boxes_in_f32(),
       _batch_splits_in_f32(),
       _scores_out_f32(),
       _boxes_out_f32(),
       _classes_f32(),
       _batch_splits_out_f32(),
       _keeps_f32(),
       _is_qasymm8(false)
 {
 }
CPPBoxWithNonMaximaSuppressionLimit() [2/2]
CPPBoxWithNonMaximaSuppressionLimit (const CPPBoxWithNonMaximaSuppressionLimit &) delete
Prevent instances of this class from being copied (As this class contains pointers)
Member Function Documentation
configure()
void configure (const ITensor * scores_in, const ITensor * boxes_in, const ITensor * batch_splits_in, ITensor * scores_out, ITensor * boxes_out, ITensor * classes, ITensor * batch_splits_out = nullptr, ITensor * keeps = nullptr, ITensor * keeps_size = nullptr, const BoxNMSLimitInfo info = BoxNMSLimitInfo())
Configure the BoxWithNonMaximaSuppressionLimit CPP kernel.
Parameters
[in] scores_in The scores input tensor of size [count, num_classes]. Data types supported: QASYMM8/QASYMM8_SIGNED/F16/F32
[in] boxes_in The boxes input tensor of size [count, num_classes * 4]. Data types supported: QASYMM16 with 0.125 scale and 0 offset if scores_in is QASYMM8/QASYMM8_SIGNED, otherwise same as scores_in
[in] batch_splits_in The batch splits input tensor of size [batch_size]. Data types supported: Same as scores_in
Note
Can be a nullptr. If not a nullptr, scores_in and boxes_in have items from multiple images.
Parameters
[out] scores_out The scores output tensor of size [N]. Data types supported: Same as scores_in
[out] boxes_out The boxes output tensor of size [N, 4]. Data types supported: QASYMM16 with 0.125 scale and 0 offset if scores_in is QASYMM8/QASYMM8_SIGNED, otherwise same as scores_in
[out] classes The classes output tensor of size [N]. Data types supported: Same as scores_in
[out] batch_splits_out (Optional) The batch splits output tensor. Data types supported: Same as scores_in
[out] keeps (Optional) The keeps output tensor of size [N]. Data types supported: Same as scores_in
[in] keeps_size (Optional) Number of filtered indices per class tensor of size [num_classes]. Data types supported: U32.
[in] info (Optional) BoxNMSLimitInfo information.
Definition at line 135 of file CPPBoxWithNonMaximaSuppressionLimit.cpp.
References TensorAllocator::allocate(), Tensor::allocator(), ARM_COMPUTE_ERROR_ON_NULLPTR, ARM_COMPUTE_LOG_PARAMS, ICloneable< T >::clone(), CPPBoxWithNonMaximaSuppressionLimitKernel::configure(), ITensorInfo::data_type(), arm_compute::F32, ITensor::info(), TensorAllocator::init(), MemoryGroup::manage(), arm_compute::QASYMM8, and arm_compute::QASYMM8_SIGNED.
Referenced by NEGenerateProposalsLayer::configure(), and CLGenerateProposalsLayer::configure().
 {
     ARM_COMPUTE_ERROR_ON_NULLPTR(scores_in, boxes_in, scores_out, boxes_out, classes);
     ARM_COMPUTE_LOG_PARAMS(scores_in, boxes_in, batch_splits_in, scores_out, boxes_out, classes, batch_splits_out, keeps, keeps_size, info);
     _is_qasymm8 = scores_in->info()->data_type() == DataType::QASYMM8 || scores_in->info()->data_type() == DataType::QASYMM8_SIGNED;
     _scores_in        = scores_in;
     _boxes_in         = boxes_in;
     _batch_splits_in  = batch_splits_in;
     _scores_out       = scores_out;
     _boxes_out        = boxes_out;
     _classes          = classes;
     _batch_splits_out = batch_splits_out;
     _keeps            = keeps;
     if(_is_qasymm8)
     {
         // Manage intermediate buffers
         _memory_group.manage(&_scores_in_f32);
         _memory_group.manage(&_boxes_in_f32);
         _memory_group.manage(&_scores_out_f32);
         _memory_group.manage(&_boxes_out_f32);
         _memory_group.manage(&_classes_f32);
         _scores_in_f32.allocator()->init(scores_in->info()->clone()->set_data_type(DataType::F32));
         _boxes_in_f32.allocator()->init(boxes_in->info()->clone()->set_data_type(DataType::F32));
         if(batch_splits_in != nullptr)
         {
             _memory_group.manage(&_batch_splits_in_f32);
             _batch_splits_in_f32.allocator()->init(batch_splits_in->info()->clone()->set_data_type(DataType::F32));
         }
         _scores_out_f32.allocator()->init(scores_out->info()->clone()->set_data_type(DataType::F32));
         _boxes_out_f32.allocator()->init(boxes_out->info()->clone()->set_data_type(DataType::F32));
         _classes_f32.allocator()->init(classes->info()->clone()->set_data_type(DataType::F32));
         if(batch_splits_out != nullptr)
         {
             _memory_group.manage(&_batch_splits_out_f32);
             _batch_splits_out_f32.allocator()->init(batch_splits_out->info()->clone()->set_data_type(DataType::F32));
         }
         if(keeps != nullptr)
         {
             _memory_group.manage(&_keeps_f32);
             _keeps_f32.allocator()->init(keeps->info()->clone()->set_data_type(DataType::F32));
         }
         _box_with_nms_limit_kernel.configure(&_scores_in_f32, &_boxes_in_f32, (batch_splits_in != nullptr) ? &_batch_splits_in_f32 : nullptr,
                                              &_scores_out_f32, &_boxes_out_f32, &_classes_f32,
                                              (batch_splits_out != nullptr) ? &_batch_splits_out_f32 : nullptr, (keeps != nullptr) ? &_keeps_f32 : nullptr,
                                              keeps_size, info);
     }
     else
     {
         _box_with_nms_limit_kernel.configure(scores_in, boxes_in, batch_splits_in, scores_out, boxes_out, classes, batch_splits_out, keeps, keeps_size, info);
     }
     if(_is_qasymm8)
     {
         _scores_in_f32.allocator()->allocate();
         _boxes_in_f32.allocator()->allocate();
         if(_batch_splits_in != nullptr)
         {
             _batch_splits_in_f32.allocator()->allocate();
         }
         _scores_out_f32.allocator()->allocate();
         _boxes_out_f32.allocator()->allocate();
         _classes_f32.allocator()->allocate();
         if(batch_splits_out != nullptr)
         {
             _batch_splits_out_f32.allocator()->allocate();
         }
         if(keeps != nullptr)
         {
             _keeps_f32.allocator()->allocate();
         }
     }
 }
operator=()
CPPBoxWithNonMaximaSuppressionLimit& operator= (const CPPBoxWithNonMaximaSuppressionLimit &) delete
Prevent instances of this class from being copied (As this class contains pointers)
run()
void run () override virtual
Run the kernels contained in the function.
For CPU kernels:
Multi-threading is used for the kernels which are parallelisable.
By default std::thread::hardware_concurrency() threads are used.
Note
CPPScheduler::set_num_threads() can be used to manually set the number of threads
For OpenCL kernels:
All the kernels are enqueued on the queue associated with CLScheduler.
The queue is then flushed.
Note
The function will not block until the kernels are executed. It is the user's responsibility to wait.
Will call prepare() on first run if hasn't been done
Implements IFunction.
Definition at line 235 of file CPPBoxWithNonMaximaSuppressionLimit.cpp.
References Window::DimY, Scheduler::get(), and IScheduler::schedule().
Referenced by NEGenerateProposalsLayer::run(), and CLGenerateProposalsLayer::validate().
 {
     // Acquire all the temporaries
     MemoryGroupResourceScope scope_mg(_memory_group);
     if(_is_qasymm8)
     {
         dequantize_tensor(_scores_in, &_scores_in_f32);
         dequantize_tensor(_boxes_in, &_boxes_in_f32);
         if(_batch_splits_in != nullptr)
         {
             dequantize_tensor(_batch_splits_in, &_batch_splits_in_f32);
         }
     }
     Scheduler::get().schedule(&_box_with_nms_limit_kernel, Window::DimY);
     if(_is_qasymm8)
     {
         quantize_tensor(&_scores_out_f32, _scores_out);
         quantize_tensor(&_boxes_out_f32, _boxes_out);
         quantize_tensor(&_classes_f32, _classes);
         if(_batch_splits_out != nullptr)
         {
             quantize_tensor(&_batch_splits_out_f32, _batch_splits_out);
         }
         if(_keeps != nullptr)
         {
             quantize_tensor(&_keeps_f32, _keeps);
         }
     }
 }
validate()
static Status validate (const ITensorInfo * scores_in, const ITensorInfo * boxes_in, const ITensorInfo * batch_splits_in, const ITensorInfo * scores_out, const ITensorInfo * boxes_out, const ITensorInfo * classes, const ITensorInfo * batch_splits_out = nullptr, const ITensorInfo * keeps = nullptr, const ITensorInfo * keeps_size = nullptr, const BoxNMSLimitInfo info = BoxNMSLimitInfo()) static
Static function to check if given info will lead to a valid configuration of CPPDetectionOutputLayer.
Parameters
[in] scores_in The scores input tensor of size [count, num_classes]. Data types supported: QASYMM8/QASYMM8_SIGNED/F16/F32
[in] boxes_in The boxes input tensor of size [count, num_classes * 4]. Data types supported: QASYMM16 with 0.125 scale and 0 offset if scores_in is QASYMM8/QASYMM8_SIGNED, otherwise same as scores_in
[in] batch_splits_in The batch splits input tensor of size [batch_size]. Data types supported: Same as scores_in
Note
Can be a nullptr. If not a nullptr, scores_in and boxes_in have items from multiple images.
Parameters
[in] scores_out The scores output tensor of size [N]. Data types supported: Same as scores_in
[in] boxes_out The boxes output tensor of size [N, 4]. Data types supported: QASYMM16 with 0.125 scale and 0 offset if scores_in is QASYMM8/QASYMM8_SIGNED, otherwise same as scores_in
[in] classes The classes output tensor of size [N]. Data types supported: Same as scores_in
[in] batch_splits_out (Optional) The batch splits output tensor. Data types supported: Same as scores_in
[in] keeps (Optional) The keeps output tensor of size [N]. Data types supported: Same as scores_in
[in] keeps_size (Optional) Number of filtered indices per class tensor of size [num_classes]. Data types supported: U32.
[in] info (Optional) BoxNMSLimitInfo information.
Returns
a status
The documentation for this class was generated from the following files:
arm_compute/runtime/CPP/functions/CPPBoxWithNonMaximaSuppressionLimit.h
src/runtime/CPP/functions/CPPBoxWithNonMaximaSuppressionLimit.cpp