Compute Library: GemmInterleaved< strategy, To, Tr, OutputStage, MergeStep, FixedFormat, ForceThreadColumns > Class Template Reference
GemmInterleaved< strategy, To, Tr, OutputStage, MergeStep, FixedFormat, ForceThreadColumns > Class Template Reference
#include <gemm_interleaved.hpp>
Public Member Functions
GemmInterleaved (GemmInterleaved &)=delete
GemmInterleaved & operator= (GemmInterleaved &)=delete
GemmInterleaved (const GemmArgs &args, const OutputStage &os)
GemmInterleaved (const GemmArgs &args)
ndrange_t get_window_size () const override
void set_nthreads (int nthreads) override
void execute (const ndcoord_t &work_range, const ndcoord_t &, int threadid) override
Main execute member fucntion.
size_t get_working_size () const override
void set_working_space (void *working_space) override
bool B_is_pretransposed () const override
bool B_pretranspose_required () const override
size_t get_B_pretransposed_array_size () const override
void requantize_bias (void *in_buffer, const To *B, const int ldb, const int B_multi_stride) override
void pretranspose_B_array (void *in_buffer, const To *B, const int ldb, const int B_multi_stride) override
void set_pretransposed_B_data (void *in_buffer) override
void set_quantized_bias (const int32_t *bias, size_t bias_multi_stride) override
void set_indirect_parameters (size_t string_len, const To *const *const *ptr) override
void set_convolution_parameters (ConvolutionParameters parms) override
GemmConfig get_config () override
Public Member Functions inherited from GemmCommon< To, Tr >
virtual void set_arrays (const To *A, const int lda, const int A_batch_stride, const int A_multi_stride, const To *B, const int ldb, const int B_multi_stride, Tr *C, const int ldc, const int C_batch_stride, const int C_multi_stride, const Tr *bias, const int bias_multi_stride)
void set_arrays_generic (const void *A, const int lda, const int A_batch_stride, const int A_multi_stride, const void *B, const int ldb, const int B_multi_stride, void *C, const int ldc, const int C_batch_stride, const int C_multi_stride, const void *bias, const int bias_multi_stride) override
void pretranspose_B_array_generic (void *out, const void *in, const int row_stride, const int multi_stride) override
void set_indirect_parameters_generic (size_t sz, const void *const *const *ptr) override
Public Member Functions inherited from IGemmCommon
virtual bool supports_dynamic_scheduling () const
virtual ~IGemmCommon ()
Static Public Member Functions
template<typename perf_type >
static uint64_t estimate_cycles (const GemmArgs &args)
Detailed Description
template<typename strategy, typename To, typename Tr, typename OutputStage = Nothing, bool MergeStep = true, bool FixedFormat = false, bool ForceThreadColumns = false>
class arm_gemm::GemmInterleaved< strategy, To, Tr, OutputStage, MergeStep, FixedFormat, ForceThreadColumns >
Definition at line 324 of file gemm_interleaved.hpp.
Constructor & Destructor Documentation
GemmInterleaved() [1/3]
GemmInterleaved (GemmInterleaved< strategy, To, Tr, OutputStage, MergeStep, FixedFormat, ForceThreadColumns > &) delete
GemmInterleaved() [2/3]
GemmInterleaved (const GemmArgs & args, const OutputStage & os) inline
Definition at line 650 of file gemm_interleaved.hpp.
                     : _ci(args._ci), _Msize(args._Msize), _Nsize(args._Nsize), _Ksize(args._Ksize),
                       _Ksections(args._Ksections), _Ktotal(get_ktotal(args)),
                       _rounded_Ksize(roundup(_Ksize, strategy::k_unroll())),
                       _nbatches(args._nbatches), _nmulti(args._nmulti), _thread_columns(is_thread_columns(args)),
                       _act(args._act), _maxthreads(args._maxthreads), _nthreads(args._maxthreads),
                       _k_block(get_k_block_size(args)), _x_block(get_x_block_size(args)), _Mround(roundup(args._Msize, strategy::out_height())),
                       _os(os) { }
GemmInterleaved() [3/3]
GemmInterleaved (const GemmArgs & args) inline
Definition at line 660 of file gemm_interleaved.hpp.
                     : _ci(args._ci), _Msize(args._Msize), _Nsize(args._Nsize), _Ksize(args._Ksize),
                       _Ksections(args._Ksections), _Ktotal(get_ktotal(args)),
                       _rounded_Ksize(roundup(_Ksize, strategy::k_unroll())),
                       _nbatches(args._nbatches), _nmulti(args._nmulti), _thread_columns(is_thread_columns(args)),
                       _act(args._act), _maxthreads(args._maxthreads), _nthreads(args._maxthreads),
                       _k_block(get_k_block_size(args)), _x_block(get_x_block_size(args)), _Mround(roundup(args._Msize, strategy::out_height())),
                       _os() { }
Member Function Documentation
B_is_pretransposed()
bool B_is_pretransposed () const inline override virtual
Reimplemented from IGemmCommon.
Definition at line 997 of file gemm_interleaved.hpp.
{
         return (FixedFormat == false);
     }
B_pretranspose_required()
bool B_pretranspose_required () const inline override virtual
Reimplemented from IGemmCommon.
Definition at line 1001 of file gemm_interleaved.hpp.
{
         return (FixedFormat == false) && (_B_transposed==nullptr);
     }
estimate_cycles()
static uint64_t estimate_cycles (const GemmArgs & args) inline static
Definition at line 1124 of file gemm_interleaved.hpp.
References GemmArgs::_ci, GemmArgs::_Ksize, GemmArgs::_maxthreads, GemmArgs::_Msize, GemmArgs::_nbatches, GemmArgs::_nmulti, GemmArgs::_Nsize, arm_gemm::iceildiv(), PerformanceParameters::kernel_macs_cycle, PerformanceParameters::merge_bytes_cycle, PerformanceParameters::prepare_bytes_cycle, and arm_gemm::roundup().
{
         unsigned int k_blocks = iceildiv(args._Ksize, get_k_block_size(args));
         const PerformanceParameters &params = strategy::template get_performance_parameters<perf_type>(args._ci);
         uint64_t total_macs    = static_cast<uint64_t>(args._nbatches) * args._nmulti * roundup(args._Msize, strategy::out_height()) * roundup(args._Nsize, strategy::out_width()) * get_ktotal(args);
         uint64_t prepare_bytes = static_cast<uint64_t>(args._nbatches) * args._nmulti * roundup(args._Msize, strategy::out_height()) * get_ktotal(args) * sizeof(Toi);
         uint64_t merge_bytes   = static_cast<uint64_t>(args._nbatches) * args._nmulti * k_blocks * args._Msize * roundup(args._Nsize, strategy::out_width()) * sizeof(Tr);
         float mac_cycles     = static_cast<float>(total_macs) / params.kernel_macs_cycle;
         float prepare_cycles = static_cast<float>(prepare_bytes) / params.prepare_bytes_cycle;
         float merge_cycles   = static_cast<float>(merge_bytes) / params.merge_bytes_cycle;
         float total_cycles = mac_cycles + prepare_cycles + merge_cycles;
         // We can't thread over multis or width, which makes this a poor
         // choice in many threaded cases.  Penalize that here.
         float parallelism_available = static_cast<float>(iceildiv(args._Msize, strategy::out_height()) * args._nbatches) * 0.9f;
         if (parallelism_available < args._maxthreads) {
             total_cycles *= (static_cast<float>(args._maxthreads) / parallelism_available);
         }
         return static_cast<uint64_t>(total_cycles);
     }
execute()
void execute (const ndcoord_t & work_range, const ndcoord_t & thread_locator, int threadid) inline override virtual
Main execute member fucntion.
Parameters
[in] work_range specifies the range of work we want to be computed, total range defined by get_window_size()
[in] thread_locator where are we inside of the thread space
[in] threadid a unique threadid
Implements IGemmCommon.
Definition at line 692 of file gemm_interleaved.hpp.
References arm_compute::test::validation::batch, arm_compute::mlgo::parser::end(), NDCoordinate< N >::get_position(), NDCoordinate< N >::get_position_end(), arm_gemm::roundup(), arm_compute::test::validation::run(), strategy, and type.
{
 #ifdef CYCLE_PROFILING
         profiler prof;
 #endif
         /* Make sure we've been set up correctly. */
         assert(FixedFormat || _B_transposed);
         assert(_working_space);
         int8_t *working_space_bytes = reinterpret_cast<int8_t *>(_working_space);
         /* Align if needed */
         intptr_t working_space_v = reinterpret_cast<intptr_t>(_working_space);
         if (working_space_v & 0x3f) {
             intptr_t alignment_offset = 0x40 - (working_space_v & 0x3f);
             working_space_bytes += alignment_offset;
         }
         strategy strat(_ci);
         const auto start = work_range.get_position(0);
         const auto end   = work_range.get_position_end(0);
         /* Translate 'start' and 'end' into a position within the batches and rows. */
         const unsigned int window_per_batch = _Mround / strategy::out_height();
         unsigned int batch_0   = start / window_per_batch;
         unsigned int batch_end = end   / window_per_batch;
         // In ThreadColumns mode, process work one horizontal strip at a time.
         // Transpose the block of needed rows at the start, then do all the work on that block.
         if (_thread_columns) {
             const auto start_x = work_range.get_position(1) * strategy::out_width();
             const auto end_x = std::min(work_range.get_position_end(1) * strategy::out_width(), _Nsize);
             Tri * const c_panel = reinterpret_cast<Tri *>(working_space_bytes + (threadid * get_c_working_size()));
             Toi * const a_panel = reinterpret_cast<Toi *>(working_space_bytes + (_maxthreads * get_c_working_size()) +
                                        (threadid * sizeof(Toi) * get_total_k_depth() * strategy::out_height()));
             for (unsigned int multi=0; multi<_nmulti; multi++) {
                 for (unsigned int k0=0; k0<_Ktotal; k0+=_k_block) {
                     unsigned int kmax=std::min(k0+_k_block, _Ktotal);
                     unsigned int rounded_width = roundup(_Nsize, strategy::out_width());
                     const bool first_pass = (k0==0);
                     const bool last_pass  = (kmax==_Ktotal);
                     // Figure out how many "K" the kernel will actually process.
                     unsigned int kern_k = roundup(kmax - k0, strategy::k_unroll());
                     const Toi *b_ptr = FixedFormat ?
                         reinterpret_cast<const Toi *>(this->_Bptr) + (multi * this->_B_multi_stride) +
                                                      ((start_x / get_stripe_width<strategy, FixedFormat>::get()) * this->_ldb) +
                                                      (k0 * get_stripe_width<strategy, FixedFormat>::get()) :
                         _B_transposed + (rounded_width * _Ktotal * multi) + (k0 * rounded_width) + (start_x * kern_k);
                     unsigned int batch     = batch_0;
                     unsigned int start_row = (start - (batch_0 * window_per_batch)) * strategy::out_height();
                     for (unsigned int p=start; p<end; p++) {
                         unsigned int end_row = std::min(start_row + strategy::out_height(), _Msize);
                         // Set up transposed 'A' block
{
 #ifdef CYCLE_PROFILING
                             auto p=prof.ScopedProfiler(PROFILE_PREPA, strategy::out_height() * (kmax-k0) * sizeof(Toi));
 #endif
                             // See comment above on transform_type<> class: this extracts either 'transforms' or
                             // 'transforms_quantized' as appropriate.
                             typename transform_type<strategy, MergeStep && std::is_same<OutputStage, Requantize32>::value>::type transforms;
                             if (_indirect_buf != nullptr) {
                                 transforms.PrepareA_indirect(a_panel,
                                                              _indirect_buf + (multi * _nbatches * _Ksections) + (batch * _Ksections), _Ksize,
                                                              _rounded_Ksize, start_row, end_row, k0, kmax, row_sum_multiplier());
                             } else if (_convolver) {
                                 transforms.PrepareA_convolution(a_panel,
                                                                 this->_Aptr + (batch * this->_A_batch_stride) + (multi * this->_A_multi_stride),
                                                                 this->_lda, *_convolver, _rounded_Ksize, start_row, end_row, k0, kmax, row_sum_multiplier());
                             } else {
                                 transforms.PrepareA(a_panel,
                                                     this->_Aptr + (batch * this->_A_batch_stride) + (multi * this->_A_multi_stride),
                                                     this->_lda, start_row, end_row, k0, std::min(kmax, _Ksize), row_sum_multiplier());
                             }
                         }
                         // Perform the kernel and merge step, either separately or together as required.
                         kernel_and_merge<MergeStep, FixedFormat, OutputStage>::run(
                         #ifdef CYCLE_PROFILING
                             prof,
                         #endif
                             // Strategy and panel pointers
                             strat, a_panel, b_ptr, this->_ldb, c_panel,
                             // Result buffer pointers
                             this->_Cptr + (batch * this->_C_batch_stride) + (multi * this->_C_multi_stride), this->_ldc,
                             // K size, and M/N ranges
                             kern_k, start_row, end_row, start_x, end_x,
                             // Only do bias on the first pass
                             ((first_pass && this->_bias) ? this->_bias + (multi * this->_bias_multi_stride) : nullptr),
                             // Only do activation on the last pass, and accumulation on any non-first pass.
                             (last_pass ? _act : Activation()), !first_pass,
                             // Pass in quantization parameters for requantizing kernels (others will ignore)
                             _os, col_bias + (multi * _Nsize),
                             // Accumulation buffer (not yet implemented on this path)
                             static_cast<Tab *>(nullptr));
                         /* Increment to the next block */
                         start_row += strategy::out_height();
                         if (start_row >= _Msize) {
                             start_row = 0;
                             batch++;
                         }
                     }
                 }
             }
         } else {
             blockwalker current(*this);
             /* Compute the M values to operate on */
             unsigned int m_0   = (start - (batch_0 * window_per_batch)) * strategy::out_height();
             unsigned int m_max = (end - (batch_end * window_per_batch)) * strategy::out_height();
             // Private buffers.  Treat working_space as an array of C buffers
             // (one per thread) first, followed by the (window-divided) A
             // buffer.
             // Set a_panel to the base of the A buffers - compute offsets into it based on M/batches later.
             Toi * const a_panel = reinterpret_cast<Toi *>(working_space_bytes + (_maxthreads * get_c_working_size()));
             Tri * const c_panel = reinterpret_cast<Tri *>(working_space_bytes + (threadid * get_c_working_size()));
             const Toi *b_panel;
             b_panel = _B_transposed;
             // newkblock() is always true on the first iteration, so these will be set properly on the first loop.
             // kern_k tracks the accumulation depth for the CURRENT K block a_panel_stride similarly tracks the total
             // stride of the A panel (i.e.  with 4 added for cases with embedded row sums)
             // These are distinct from k_block and get_total_k_depth() which are based on the target K block size, and
             // used for addressing inside a_panel.
             // In cases where K blocking is in use and the blocks are not all the same size, the (smaller) final block
             // won't use all the memory allocated.
             unsigned int kern_k = 0;
             unsigned int a_panel_stride = 0;
             for (;!current.done();current.advance()) {
                 if (current.newkblock()) {
 #ifdef CYCLE_PROFILING
                     auto p=prof.ScopedProfiler(PROFILE_PREPA, (end - start) * strategy::out_height() * (current.kmax()-current.k0()) * sizeof(Toi));
 #endif
                     // See comment above on transform_type<> class: this extracts either 'transforms' or
                     // 'transforms_quantized' as appropriate.
                     typename transform_type<strategy, MergeStep && std::is_same<OutputStage, Requantize32>::value>::type transforms;
                     for (unsigned int batch = batch_0; batch <= batch_end; batch++) {
                         unsigned int first_m = (batch == batch_0)   ? m_0   : 0;
                         unsigned int last_m  = (batch == batch_end) ? m_max : _Msize;
                         if (first_m >= last_m)
                             continue;
                         if (_indirect_buf != nullptr) {
                             transforms.PrepareA_indirect(a_panel + ((batch * _Mround + first_m) * get_total_k_depth()),
                                                       _indirect_buf + (current.multi() * _nbatches * _Ksections) + (batch * _Ksections), _Ksize,
                                                       _rounded_Ksize, first_m, last_m, current.k0(), current.kmax(), row_sum_multiplier());
                         } else if (_convolver) {
                             transforms.PrepareA_convolution(a_panel + ((batch * _Mround + first_m) * get_total_k_depth()),
                                                       this->_Aptr + (batch * this->_A_batch_stride) + (current.multi() * this->_A_multi_stride),
                                                       this->_lda, *_convolver, _rounded_Ksize, first_m, last_m, current.k0(), current.kmax(), row_sum_multiplier());
                         } else {
                             transforms.PrepareA(a_panel + ((batch * _Mround + first_m) * get_total_k_depth()),
                                                       this->_Aptr + (batch * this->_A_batch_stride) + (current.multi() * this->_A_multi_stride),
                                                       this->_lda, first_m, last_m, current.k0(), std::min(_Ksize, current.kmax()), row_sum_multiplier());
                         }
                     }
                     // Figure out how many "K" the kernel will actually process.
                     kern_k = roundup(current.kmax() - current.k0(), strategy::k_unroll());
                     // Requantizing GEMMs have the row sums built in to the
                     // transposed data, so the stride between rows is 4 bytes
                     // larger than the (rounded) K value.
                     if(std::is_same<OutputStage, Requantize32>::value) {
                         a_panel_stride = kern_k + (sizeof(int32_t) / sizeof(Toi));
                     } else {
                         a_panel_stride = kern_k;
                     }
                 }
                 // For FixedFormat cases, figure out the B pointer.  The loop below moves through batches and vertically through the output so this will be the same throughout.
                 if (FixedFormat) {
                     b_panel = reinterpret_cast<const Toi *>(this->_Bptr) + (current.multi() * this->_B_multi_stride) +
                                                                            ((current.x0() / get_stripe_width<strategy, FixedFormat>::get()) * this->_ldb) +
                                                                            (current.k0() * get_stripe_width<strategy, FixedFormat>::get());
                 }
                 /* Do the actual work. */
                 for (unsigned int batch = batch_0; batch <= batch_end; batch++) {
                     unsigned int first_m = (batch == batch_0)   ? m_0   : 0;
                     unsigned int last_m  = (batch == batch_end) ? m_max : _Msize;
                     const Toi *a_ptr = a_panel + (batch * _Mround + first_m) * get_total_k_depth();
                     if (first_m >= last_m)
                         continue;
                     // For the merge case we need to do this out_height() rows
                     // at a time, as that is the size of our intermediate
                     // buffer.  If we are not doing that, we can do all the
                     // relevant rows in one go.
                     unsigned int m_step = MergeStep ? strategy::out_height() : (last_m - first_m);
                     // But in the case where we have an accumulation buffer, we can't do that after all, unless
                     // there is no N blocking.
                     if (_accumulation_buffer && ((current.x0() != 0) || (current.xmax() < _Nsize))) {
                         m_step = strategy::out_height();
                     }
                     for (unsigned int y=first_m; y<last_m; y+=m_step) {
                         unsigned int ymax = std::min(_Msize, y + m_step);
                         const bool first_pass = (current.k0() == 0);
                         const bool last_pass  = (current.kmax() == _Ktotal);
                         // Pointer to appropriate part of result array.
                         Tr *result_ptr = this->_Cptr + (batch * this->_C_batch_stride) + (current.multi() * this->_C_multi_stride);
                         // If we are using an accumulation buffer, we don't pass the result buffer to ask the kernel
                         // to write things into the accumulation buffer instead, except on the last pass.
                         if (_accumulation_buffer && !last_pass) {
                             result_ptr = nullptr;
                         }
                         // Perform the kernel and merge step, either separately or together as required.
                         kernel_and_merge<MergeStep, FixedFormat, OutputStage>::run(
                         #ifdef CYCLE_PROFILING
                             prof,
                         #endif
                             // Strategy and panel pointers
                             strat, a_ptr, b_panel, this->_ldb, c_panel,
                             // Result buffer pointers
                             result_ptr, this->_ldc,
                             // K size, and M/N ranges
                             kern_k, y, ymax, current.x0(), current.xmax(),
                             // Only do bias on the first pass
                             ((first_pass && this->_bias) ? this->_bias + (current.multi() * this->_bias_multi_stride) : nullptr),
                             // Only do activation on the last pass, and accumulation on any non-first pass.
                             (last_pass ? _act : Activation()), !first_pass,
                             // Pass in quantization parameters for requantizing kernels (others will ignore)
                             _os, col_bias + (current.multi() * _Nsize),
                             // Accumulation buffer
                             get_accumulation_buffer(y, current.x0(), batch, current.multi()) );
                         a_ptr += (strategy::out_height() * a_panel_stride);
                     }
                 }
                 if (FixedFormat == false) {
                     b_panel += (roundup(current.xmax() - current.x0(), strategy::out_width()) * kern_k);
                 }
             }
         }
     }
get_B_pretransposed_array_size()
size_t get_B_pretransposed_array_size () const inline override virtual
Reimplemented from IGemmCommon.
Definition at line 1005 of file gemm_interleaved.hpp.
References arm_gemm::roundup().
{
         if (FixedFormat) {
             return 0;
         }
         unsigned int x_size = roundup(_Nsize, strategy::out_width());
         return (x_size * _Ktotal * _nmulti * sizeof(Toi)) + get_col_sum_size();
     }
get_config()
GemmConfig get_config () inline override virtual
Implements IGemmCommon.
Definition at line 1150 of file gemm_interleaved.hpp.
References GemmConfig::filter, arm_gemm::GEMM_INTERLEAVED, arm_gemm::get_weight_format(), GemmConfig::inner_block_size, GemmConfig::method, GemmConfig::outer_block_size, and GemmConfig::weight_format.
{
         GemmConfig c;
         c.method = GemmMethod::GEMM_INTERLEAVED;
         c.inner_block_size = _k_block;
         c.outer_block_size = _x_block;
         c.filter = get_type_name<strategy>();
         c.weight_format = get_weight_format(get_kernel_weight_format<strategy, FixedFormat, To>::get(), sizeof(To));
         return c;
     }
get_window_size()
ndrange_t get_window_size () const inline override virtual
Returns
an ndrange containing ranges of the compute space which can be broken up and parallelised over
Implements IGemmCommon.
Definition at line 675 of file gemm_interleaved.hpp.
References arm_gemm::iceildiv().
{
         unsigned int row_blocks = (_Mround / strategy::out_height()) * _nbatches;
         if (_thread_columns) {
             return { row_blocks, iceildiv(_Nsize, strategy::out_width()) };
         } else {
             // _Mround is a multiple of out_height by definition.
             return { row_blocks };
         }
     }
get_working_size()
size_t get_working_size (void) const inline override virtual
Reimplemented from IGemmCommon.
Definition at line 957 of file gemm_interleaved.hpp.
{
         // In all cases, we need one A buffer plus a C buffer per thread, plus an accumulation buffer.
         size_t size = get_a_working_size() + (get_c_working_size() * _maxthreads) + get_accumulation_buffer_size();
         size += 128; // Add on two cache lines extra for alignment.
         return size;
     }
operator=()
GemmInterleaved& operator= (GemmInterleaved< strategy, To, Tr, OutputStage, MergeStep, FixedFormat, ForceThreadColumns > &) delete
pretranspose_B_array()
void pretranspose_B_array (void * in_buffer, const To * B, const int ldb, const int B_multi_stride) inline override virtual
Reimplemented from GemmCommon< To, Tr >.
Definition at line 1028 of file gemm_interleaved.hpp.
References arm_gemm::roundup(), and strategy.
{
         requantize_bias(in_buffer, B, ldb, B_multi_stride);
         // Put the transposed data after the column sums - in non-quantized cases get_col_sum_size() == 0
         uintptr_t buffer_int = reinterpret_cast<uintptr_t>(in_buffer);
         Toi *buffer = reinterpret_cast<Toi *>(buffer_int + get_col_sum_size());
         _B_transposed = buffer;
         blockwalker current(*this);
         strategy strat(_ci);
         do {
             /* Figure out the size of each block. */
             unsigned int k_size = (current.kmax() - current.k0());
             if (_Ksections > 1) {
                 // We need to insert padding at the end of each K section.
                 // The computation needed is a little delicate - the coordinates from the block walker are expressed in
                 // terms of the full, padded, _Ktotal.
                 // But we need to transform each section with reference to the original, unpadded, input, letting the
                 // transform pad each section as needed.
                 // This is needed for computations below.
                 const unsigned int rounded_section_size = roundup(_Ksize, strategy::k_unroll());
                 // The expected output format is also an entire <out_width> columns interleaved, then the next set of
                 // columns, and so on.  This means, as we are breaking it up vertically, we have to do it one column at
                 // a time.
                 for (unsigned int x0=current.x0(); x0 < current.xmax(); x0 += strategy::out_width() ) {
                     unsigned int xmax = std::min(x0 + strategy::out_width(), current.xmax());
                     // Track where we are and how much work is left.
                     unsigned int kpos  = current.k0();
                     unsigned int kleft = k_size;
                     while (kleft) {
                         // Which section are we in?  Based on the rounded-up section size.
                         unsigned int k_section_base = kpos / rounded_section_size;
                         // How far into the section are we?
                         unsigned int k_offset = kpos - (k_section_base * rounded_section_size);
                         // We will either copy the rest of this section, or to the end of the requested length.
                         unsigned int k_length = std::min(_Ksize - k_offset, kleft);
                         strat.transforms.PrepareB(buffer, B + (current.multi() * B_multi_stride), ldb,
                                                   x0, xmax,
                                                   (k_section_base * _Ksize) + k_offset,               // K starting point - compute row to read based on our section and the true section length.
                                                   (k_section_base * _Ksize) + k_offset + k_length);   // K end point - starting point plus length computed above.
                         // We need to modify our position based on the ROUNDED version of what we just did.
                         unsigned int padded_length = roundup(k_length, strategy::k_unroll());
                         buffer += strategy::out_width() * padded_length;
                         kpos  += padded_length;
                         kleft -= padded_length;
                     }
                 }
             } else {
                 // In the single K section case, can process the whole lot in one go.
                 // Caution: 'blockwalker::kmax()' rounds up, so clamp to valid _Ksize.
                 strat.transforms.PrepareB(buffer, B + (current.multi() * B_multi_stride), ldb,
                                           current.x0(), current.xmax(), current.k0(), std::min(current.kmax(), _Ksize));
                 buffer += roundup(current.xmax() - current.x0(), strategy::out_width()) * roundup(current.kmax() - current.k0(), strategy::k_unroll());
             }
         } while (current.advance());
     }
requantize_bias()
void requantize_bias (void * in_buffer, const To * B, const int ldb, const int B_multi_stride) inline override virtual
Reimplemented from GemmCommon< To, Tr >.
Definition at line 1015 of file gemm_interleaved.hpp.
References arm_gemm::compute_col_sums().
{
         if (std::is_same<OutputStage, Requantize32>::value) {
             col_bias = reinterpret_cast<int32_t *>(in_buffer);
             Requantize32 *qp_ptr = reinterpret_cast<Requantize32 *>(&_os);
             for (unsigned int i=0; i<_nmulti; i++) {
                 // The input is assumed not to have any padding between sections, so straightforward Ksize * Ksections computation gets the total size.
                 compute_col_sums(*qp_ptr, _Nsize, _Ksize * _Ksections, B + (i * B_multi_stride), ldb, col_bias + (i * _Nsize), _Ksize * _Ksections, i, 0);
             }
         }
     }
set_convolution_parameters()
void set_convolution_parameters (ConvolutionParameters parms) inline override virtual
Reimplemented from IGemmCommon.
Definition at line 1117 of file gemm_interleaved.hpp.
References ConvolutionParameters::input_channels.
{
         assert(parms.input_channels == _Ksize);
         _convolver = std::unique_ptr<convolver<To>>(new convolver<To>(parms));
     }
set_indirect_parameters()
void set_indirect_parameters (size_t string_len, const To *const *const * ptr) inline override virtual
Reimplemented from GemmCommon< To, Tr >.
Definition at line 1112 of file gemm_interleaved.hpp.
{
         assert(string_len == _Ksize);
         _indirect_buf = ptr;
     }
set_nthreads()
void set_nthreads (int nthreads) inline override virtual
Reimplemented from IGemmCommon.
Definition at line 687 of file gemm_interleaved.hpp.
{
         _nthreads = std::min(nthreads, _maxthreads);
     }
set_pretransposed_B_data()
void set_pretransposed_B_data (void * in_buffer) inline override virtual
Reimplemented from IGemmCommon.
Definition at line 1096 of file gemm_interleaved.hpp.
{
         // Put the transposed data after the column sums - in non-quantized cases get_col_sum_size() == 0
         uintptr_t buffer_int = reinterpret_cast<uintptr_t>(in_buffer);
         _B_transposed = reinterpret_cast<Toi *>(buffer_int + get_col_sum_size());
         col_bias = reinterpret_cast<int32_t *>(in_buffer);
     }
set_quantized_bias()
void set_quantized_bias (const int32_t * bias, size_t bias_multi_stride) inline override virtual
Reimplemented from IGemmCommon.
Definition at line 1103 of file gemm_interleaved.hpp.
References Requantize32::bias, bias, and Requantize32::bias_multi_stride.
{
         if (std::is_same<OutputStage, Requantize32>::value) {
             Requantize32 *qp = reinterpret_cast<Requantize32 *>(&_os);
             qp->bias = bias;
             qp->bias_multi_stride = bias_multi_stride;
         }
     }
set_working_space()
void set_working_space (void * working_space) inline override virtual
Reimplemented from IGemmCommon.
Definition at line 966 of file gemm_interleaved.hpp.
{
         // Make sure everything ends up cache line aligned
         int8_t *working_space_bytes = reinterpret_cast<int8_t *>(working_space);
         intptr_t working_space_int = reinterpret_cast<intptr_t>(working_space);
         size_t diff=0;
         if (working_space_int & 0x3F) {
             diff = 0x40 - (working_space_int & 0x3F);
         }
         working_space_bytes += diff;
         working_space_int += diff;
         // Pretransposed case: just set internal pointer to parameter value.
         _working_space = reinterpret_cast<void *>(working_space_bytes);
         // Set up accumulation buffer
         if (get_accumulation_buffer_size() > 0) {
             intptr_t acc_buff_int = working_space_int + get_a_working_size() + (get_c_working_size() * _maxthreads);
             // Make sure the accumulation buffer is aligned (needed if the other blocks are not a multiple of cache line length)
             if (acc_buff_int & 0x3F) {
                 acc_buff_int += (0x40 - (acc_buff_int & 0x3F));
             }
             _accumulation_buffer = reinterpret_cast<Tab *>(acc_buff_int);
         } else {
             _accumulation_buffer = nullptr;
         }
     }
The documentation for this class was generated from the following file:
src/core/NEON/kernels/arm_gemm/gemm_interleaved.hpp