Compute Library: CpuQuantizeKernel Class Reference
CpuQuantizeKernel Class Reference
Interface for the quantization layer kernel.
#include <CpuQuantizeKernel.h>
Public Member Functions
CpuQuantizeKernel ()=default
ARM_COMPUTE_DISALLOW_COPY_ALLOW_MOVE (CpuQuantizeKernel)
void configure (const ITensorInfo *src, ITensorInfo *dst)
Set the input, output.
void run_op (ITensorPack &tensors, const Window &window, const ThreadInfo &info) override
Execute the kernel on the passed window.
const char * name () const override
Name of the kernel.
Public Member Functions inherited from ICPPKernel
virtual ~ICPPKernel ()=default
Default destructor.
virtual void run (const Window &window, const ThreadInfo &info)
Execute the kernel on the passed window.
virtual void run_nd (const Window &window, const ThreadInfo &info, const Window &thread_locator)
legacy compatibility layer for implemantions which do not support thread_locator In these cases we simply narrow the interface down the legacy version
virtual size_t get_mws (const CPUInfo &platform, size_t thread_count) const
Return minimum workload size of the relevant kernel.
Public Member Functions inherited from IKernel
IKernel ()
Constructor.
virtual ~IKernel ()=default
Destructor.
virtual bool is_parallelisable () const
Indicates whether or not the kernel is parallelisable.
virtual BorderSize border_size () const
The size of the border for that kernel.
const Window & window () const
The maximum window the kernel can be executed on.
bool is_window_configured () const
Function to check if the embedded window of this kernel has been configured.
Static Public Member Functions
static Status validate (const ITensorInfo *src, const ITensorInfo *dst)
Static function to check if given info will lead to a valid configuration.
Static Public Member Functions inherited from ICpuKernel< CpuQuantizeKernel >
static const auto * get_implementation (const SelectorType &selector, KernelSelectionType selection_type=KernelSelectionType::Supported)
Micro-kernel selector.
Additional Inherited Members
Static Public Attributes inherited from ICPPKernel
static constexpr size_t default_mws = 1
Detailed Description
Interface for the quantization layer kernel.
Note
The implementation supports only 3D input tensors
Definition at line 40 of file CpuQuantizeKernel.h.
Constructor & Destructor Documentation
CpuQuantizeKernel()
CpuQuantizeKernel () default
Member Function Documentation
ARM_COMPUTE_DISALLOW_COPY_ALLOW_MOVE()
ARM_COMPUTE_DISALLOW_COPY_ALLOW_MOVE (CpuQuantizeKernel)
configure()
void configure (const ITensorInfo * src, ITensorInfo * dst)
Set the input, output.
Parameters
[in] src Source tensor info. The dimensions over the third will be interpreted as batches. Data types supported: QASYMM8/QASYMM8_SIGNED/F32/F16.
[out] dst Destination tensor info with the same dimensions of input. Data types supported: QASYMM8/QASYMM8_SIGNED/QASYMM16.
Note
Output auto initialization is not supported by this kernel
Definition at line 111 of file CpuQuantizeKernel.cpp.
References ARM_COMPUTE_ERROR, ARM_COMPUTE_ERROR_ON_NULLPTR, ARM_COMPUTE_ERROR_THROW_ON, arm_compute::calculate_max_window(), ITensorInfo::data_type(), arm_compute::string_from_data_type(), and arm_compute::cpu::kernels::validate_arguments().
 {
     ARM_COMPUTE_ERROR_ON_NULLPTR(src, dst);
     ARM_COMPUTE_ERROR_THROW_ON(validate_arguments(src, dst));
     static const std::map<std::string, QuantizeFunctionExecutorPtr> quant_map =
     {
         { "op_QASYMM8_QASYMM8", &CpuQuantizeKernel::run_quantize_qasymm8<uint8_t, uint8_t> },
         { "op_QASYMM8_QASYMM8_SIGNED", &CpuQuantizeKernel::run_quantize_qasymm8<uint8_t, int8_t> },
         { "op_QASYMM8_QASYMM16", &CpuQuantizeKernel::run_quantize_qasymm16<uint8_t> },
         { "op_QASYMM8_SIGNED_QASYMM8", &CpuQuantizeKernel::run_quantize_qasymm8<int8_t, uint8_t> },
         { "op_QASYMM8_SIGNED_QASYMM8_SIGNED", &CpuQuantizeKernel::run_quantize_qasymm8<int8_t, int8_t> },
         { "op_QASYMM8_SIGNED_QASYMM16", &CpuQuantizeKernel::run_quantize_qasymm16<int8_t> },
         { "op_F32_QSYMM8", &CpuQuantizeKernel::run_quantize_qsymm8<float, int8_t> },
         { "op_F32_QASYMM8", &CpuQuantizeKernel::run_quantize_qasymm8<float, uint8_t> },
         { "op_F32_QASYMM8_SIGNED", &CpuQuantizeKernel::run_quantize_qasymm8<float, int8_t> },
         { "op_F32_QASYMM16", &CpuQuantizeKernel::run_quantize_qasymm16<float> },
 #ifdef __ARM_FEATURE_FP16_VECTOR_ARITHMETIC
         { "op_F16_QASYMM8", &CpuQuantizeKernel::run_quantize_qasymm8<float16_t, uint8_t> },
         { "op_F16_QASYMM8_SIGNED", &CpuQuantizeKernel::run_quantize_qasymm8<float16_t, int8_t> },
         { "op_F16_QASYMM16", &CpuQuantizeKernel::run_quantize_qasymm16<float16_t> },
 #endif /* __ARM_FEATURE_FP16_VECTOR_ARITHMETIC*/
     };
     std::string function_to_call("op_");
     function_to_call += string_from_data_type(src->data_type()) + "_";
     function_to_call += string_from_data_type(dst->data_type());
     auto it = quant_map.find(function_to_call);
     if(it == quant_map.end())
     {
         ARM_COMPUTE_ERROR("Unsupported combination of input and output data types");
     }
     _func = it->second;
     // Configure kernel window
     Window win_config = calculate_max_window(*src, Steps());
     ICpuKernel::configure(win_config);
 }
name()
const char * name () const override virtual
Name of the kernel.
Returns
Kernel name
Implements ICPPKernel.
Definition at line 298 of file CpuQuantizeKernel.cpp.
 {
     return "CpuQuantizeKernel";
 }
run_op()
void run_op (ITensorPack & tensors, const Window & window, const ThreadInfo & info) override virtual
Execute the kernel on the passed window.
Warning
If is_parallelisable() returns false then the passed window must be equal to window()
Note
The window has to be a region within the window returned by the window() method
The width of the window has to be a multiple of num_elems_processed_per_iteration().
Parameters
[in] tensors A vector containing the tensors to operate on.
[in] window Region on which to execute the kernel. (Must be a region of the window returned by window())
[in] info Info about executing thread and CPU.
Reimplemented from ICPPKernel.
Definition at line 286 of file CpuQuantizeKernel.cpp.
References arm_compute::ACL_DST, arm_compute::ACL_SRC, ARM_COMPUTE_ERROR_ON, ARM_COMPUTE_ERROR_ON_INVALID_SUBWINDOW, ARM_COMPUTE_ERROR_ON_UNCONFIGURED_KERNEL, ARM_COMPUTE_UNUSED, ITensorPack::get_const_tensor(), ITensorPack::get_tensor(), and IKernel::window().
 {
     ARM_COMPUTE_UNUSED(info);
     ARM_COMPUTE_ERROR_ON_UNCONFIGURED_KERNEL(this);
     ARM_COMPUTE_ERROR_ON_INVALID_SUBWINDOW(ICpuKernel::window(), window);
     ARM_COMPUTE_ERROR_ON(_func == nullptr);
     const auto src = tensors.get_const_tensor(TensorType::ACL_SRC);
     auto       dst = tensors.get_tensor(TensorType::ACL_DST);
     (this->*_func)(src, dst, window);
 }
validate()
Status validate (const ITensorInfo * src, const ITensorInfo * dst) static
Static function to check if given info will lead to a valid configuration.
Similar to CpuQuantizeKernel::configure()
Returns
a status
Definition at line 156 of file CpuQuantizeKernel.cpp.
References ARM_COMPUTE_RETURN_ON_ERROR, Window::collapse_if_possible(), arm_compute::compute_requantization_scale_offset(), ITensorInfo::data_type(), Window::DimX, Window::DimZ, Window::Dimension::end(), arm_compute::execute_window_loop(), ITensor::info(), arm_compute::test::validation::input, arm_compute::is_data_type_quantized_asymmetric(), Iterator::ptr(), ITensorInfo::quantization_info(), Qasymm8QuantizationHelper< QUANTIZED_TYPE >::quantize(), arm_compute::quantize_qasymm16(), arm_compute::quantize_qsymm8(), Window::set(), Window::Dimension::start(), arm_compute::TO_NEAREST_EVEN, arm_compute::TO_ZERO, QuantizationInfo::uniform(), arm_compute::cpu::kernels::validate_arguments(), arm_compute::vquantize_qasymm16(), arm_compute::wrapper::vstore(), IKernel::window(), and Window::x().
Referenced by CpuQuantize::validate().
 {
     ARM_COMPUTE_RETURN_ON_ERROR(validate_arguments(src, dst));
     return Status{};
 }
The documentation for this class was generated from the following files:
src/cpu/kernels/CpuQuantizeKernel.h
src/cpu/kernels/CpuQuantizeKernel.cpp