Compute Library: LSTMParams< T > Class Template Reference
LSTMParams< T > Class Template Reference
#include <LSTMParams.h>
Public Member Functions
LSTMParams ()
Constructor.
LSTMParams (const LSTMParams &)=delete
Prevent instances of this class from being copied (As this class contains pointers)
LSTMParams & operator= (const LSTMParams &)=delete
Prevent instances of this class from being copied (As this class contains pointers)
~LSTMParams ()=default
Default destructor.
LSTMParams & set_cifg_params (const T *input_to_input_weights, const T *recurrent_to_input_weights, T *cell_to_input_weights, const T *input_gate_bias)
Set CIFG tensor parameters.
LSTMParams & set_projection_params (const T *projection_weights, const T *projection_bias)
Set projection tensor parameters.
LSTMParams & set_peephole_params (T *cell_to_forget_weights, T *cell_to_output_weights)
Set peephole tensor parameters.
LSTMParams & set_layer_normalization_params (T *input_layer_norm_weights, T *forget_layer_norm_weights, T *cell_layer_norm_weights, T *output_layer_norm_weights)
Set layer normalization tensor parameters.
LSTMParams & set_cell_clip_params (float cell_clip)
Set cell clip value.
LSTMParams & set_projection_clip_params (float projection_clip)
Set projection clip value.
LSTMParams & set_matmul_scale_params (float input_intermediate_scale, float forget_intermediate_scale, float cell_intermediate_scale, float output_intermediate_scale)
Set scale of the intermediate results of matmul of each layer parameters.
LSTMParams & set_hidden_state_params (int32_t hidden_state_zero, float hidden_state_scale)
Set hidden state zero and scale parameters.
const T * input_to_input_weights () const
const T * recurrent_to_input_weights () const
T * cell_to_input_weights () const
const T * input_gate_bias () const
T * cell_to_forget_weights () const
T * cell_to_output_weights () const
const T * projection_weights () const
const T * projection_bias () const
T * input_layer_norm_weights () const
T * forget_layer_norm_weights () const
T * cell_layer_norm_weights () const
T * output_layer_norm_weights () const
float cell_clip () const
float projection_clip () const
float input_intermediate_scale () const
float forget_intermediate_scale () const
float cell_intermediate_scale () const
float output_intermediate_scale () const
int32_t hidden_state_zero () const
float hidden_state_scale () const
bool has_peephole_opt () const
bool has_projection () const
bool has_cifg_opt () const
bool use_layer_norm () const
Detailed Description
template<typename T>
class arm_compute::LSTMParams< T >
Definition at line 36 of file LSTMParams.h.
Constructor & Destructor Documentation
LSTMParams() [1/2]
LSTMParams () inline
Constructor.
Definition at line 40 of file LSTMParams.h.
References LSTMParams< T >::operator=(), and LSTMParams< T >::~LSTMParams().
         : _input_to_input_weights(nullptr),
           _recurrent_to_input_weights(nullptr),
           _cell_to_input_weights(nullptr),
           _input_gate_bias(nullptr),
           _cell_to_forget_weights(nullptr),
           _cell_to_output_weights(nullptr),
           _projection_weights(nullptr),
           _projection_bias(nullptr),
           _input_layer_norm_weights(nullptr),
           _forget_layer_norm_weights(nullptr),
           _cell_layer_norm_weights(nullptr),
           _output_layer_norm_weights(nullptr),
           _cell_clip(0.f),
           _projection_clip(0.0f),
           _input_intermediate_scale(0.0f),
           _forget_intermediate_scale(0.0f),
           _cell_intermediate_scale(0.0f),
           _output_intermediate_scale(0.0f),
           _hidden_state_zero(0),
           _hidden_state_scale(0.0f),
           _has_peephole_opt(false),
           _has_projection(false),
           _has_cifg_opt(true),
           _use_layer_norm(false)
     {
     }
LSTMParams() [2/2]
LSTMParams (const LSTMParams< T > &) delete
Prevent instances of this class from being copied (As this class contains pointers)
~LSTMParams()
~LSTMParams () default
Default destructor.
Referenced by LSTMParams< T >::LSTMParams().
Member Function Documentation
cell_clip()
float cell_clip () const inline
Definition at line 255 of file LSTMParams.h.
Referenced by NEQLSTMLayer::configure(), CLQLSTMLayer::configure(), LSTMParams< T >::set_cell_clip_params(), NEQLSTMLayer::validate(), and CLQLSTMLayer::validate().
     {
         return _cell_clip;
     }
cell_intermediate_scale()
float cell_intermediate_scale () const inline
Definition at line 275 of file LSTMParams.h.
Referenced by arm_compute::utils::info_helpers::build_lstm_params_tensor_info(), NEQLSTMLayer::configure(), CLQLSTMLayer::configure(), LSTMParams< T >::set_matmul_scale_params(), NEQLSTMLayer::validate(), and CLQLSTMLayer::validate().
     {
         return _cell_intermediate_scale;
     }
cell_layer_norm_weights()
T* cell_layer_norm_weights () const inline
Definition at line 245 of file LSTMParams.h.
Referenced by arm_compute::utils::info_helpers::build_lstm_params_tensor_info(), NELSTMLayer::configure(), NEQLSTMLayer::configure(), CLLSTMLayer::configure(), CLQLSTMLayer::configure(), LSTMParams< T >::set_layer_normalization_params(), NELSTMLayer::validate(), NEQLSTMLayer::validate(), CLLSTMLayer::validate(), and CLQLSTMLayer::validate().
     {
         return _cell_layer_norm_weights;
     }
cell_to_forget_weights()
T* cell_to_forget_weights () const inline
Definition at line 215 of file LSTMParams.h.
Referenced by arm_compute::utils::info_helpers::build_lstm_params_tensor_info(), NELSTMLayer::configure(), NEQLSTMLayer::configure(), CLLSTMLayer::configure(), CLQLSTMLayer::configure(), LSTMParams< T >::set_peephole_params(), NELSTMLayer::validate(), NEQLSTMLayer::validate(), CLLSTMLayer::validate(), and CLQLSTMLayer::validate().
     {
         return _cell_to_forget_weights;
     }
cell_to_input_weights()
T* cell_to_input_weights () const inline
Definition at line 205 of file LSTMParams.h.
Referenced by arm_compute::utils::info_helpers::build_lstm_params_tensor_info(), NELSTMLayer::configure(), NEQLSTMLayer::configure(), CLLSTMLayer::configure(), CLQLSTMLayer::configure(), LSTMParams< T >::set_cifg_params(), NELSTMLayer::validate(), NEQLSTMLayer::validate(), CLLSTMLayer::validate(), and CLQLSTMLayer::validate().
     {
         return _cell_to_input_weights;
     }
cell_to_output_weights()
T* cell_to_output_weights () const inline
Definition at line 220 of file LSTMParams.h.
Referenced by arm_compute::utils::info_helpers::build_lstm_params_tensor_info(), NELSTMLayer::configure(), NEQLSTMLayer::configure(), CLLSTMLayer::configure(), CLQLSTMLayer::configure(), LSTMParams< T >::set_peephole_params(), NELSTMLayer::validate(), NEQLSTMLayer::validate(), CLLSTMLayer::validate(), and CLQLSTMLayer::validate().
     {
         return _cell_to_output_weights;
     }
forget_intermediate_scale()
float forget_intermediate_scale () const inline
Definition at line 270 of file LSTMParams.h.
Referenced by arm_compute::utils::info_helpers::build_lstm_params_tensor_info(), NEQLSTMLayer::configure(), CLQLSTMLayer::configure(), LSTMParams< T >::set_matmul_scale_params(), NEQLSTMLayer::validate(), and CLQLSTMLayer::validate().
     {
         return _forget_intermediate_scale;
     }
forget_layer_norm_weights()
T* forget_layer_norm_weights () const inline
Definition at line 240 of file LSTMParams.h.
Referenced by arm_compute::utils::info_helpers::build_lstm_params_tensor_info(), NELSTMLayer::configure(), NEQLSTMLayer::configure(), CLLSTMLayer::configure(), CLQLSTMLayer::configure(), LSTMParams< T >::set_layer_normalization_params(), NELSTMLayer::validate(), NEQLSTMLayer::validate(), CLLSTMLayer::validate(), and CLQLSTMLayer::validate().
     {
         return _forget_layer_norm_weights;
     }
has_cifg_opt()
bool has_cifg_opt () const inline
Definition at line 305 of file LSTMParams.h.
Referenced by arm_compute::utils::info_helpers::build_lstm_params_tensor_info(), NELSTMLayer::configure(), NEQLSTMLayer::configure(), CLLSTMLayer::configure(), CLQLSTMLayer::configure(), NELSTMLayer::validate(), NEQLSTMLayer::validate(), CLLSTMLayer::validate(), and CLQLSTMLayer::validate().
     {
         return _has_cifg_opt;
     }
has_peephole_opt()
bool has_peephole_opt () const inline
Definition at line 295 of file LSTMParams.h.
Referenced by arm_compute::utils::info_helpers::build_lstm_params_tensor_info(), NELSTMLayer::configure(), NEQLSTMLayer::configure(), CLLSTMLayer::configure(), CLQLSTMLayer::configure(), NELSTMLayer::validate(), NEQLSTMLayer::validate(), CLLSTMLayer::validate(), and CLQLSTMLayer::validate().
     {
         return _has_peephole_opt;
     }
has_projection()
bool has_projection () const inline
Definition at line 300 of file LSTMParams.h.
Referenced by arm_compute::utils::info_helpers::build_lstm_params_tensor_info(), NELSTMLayer::configure(), NEQLSTMLayer::configure(), CLLSTMLayer::configure(), CLQLSTMLayer::configure(), NELSTMLayer::validate(), NEQLSTMLayer::validate(), CLLSTMLayer::validate(), and CLQLSTMLayer::validate().
     {
         return _has_projection;
     }
hidden_state_scale()
float hidden_state_scale () const inline
Definition at line 290 of file LSTMParams.h.
Referenced by arm_compute::utils::info_helpers::build_lstm_params_tensor_info(), NEQLSTMLayer::configure(), CLQLSTMLayer::configure(), LSTMParams< T >::set_hidden_state_params(), NEQLSTMLayer::validate(), and CLQLSTMLayer::validate().
     {
         return _hidden_state_scale;
     }
hidden_state_zero()
int32_t hidden_state_zero () const inline
Definition at line 285 of file LSTMParams.h.
Referenced by arm_compute::utils::info_helpers::build_lstm_params_tensor_info(), NEQLSTMLayer::configure(), CLQLSTMLayer::configure(), LSTMParams< T >::set_hidden_state_params(), NEQLSTMLayer::validate(), and CLQLSTMLayer::validate().
     {
         return _hidden_state_zero;
     }
input_gate_bias()
const T* input_gate_bias () const inline
Definition at line 210 of file LSTMParams.h.
Referenced by arm_compute::utils::info_helpers::build_lstm_params_tensor_info(), NELSTMLayer::configure(), NEQLSTMLayer::configure(), CLLSTMLayer::configure(), CLQLSTMLayer::configure(), LSTMParams< T >::set_cifg_params(), NELSTMLayer::validate(), NEQLSTMLayer::validate(), CLLSTMLayer::validate(), and CLQLSTMLayer::validate().
     {
         return _input_gate_bias;
     }
input_intermediate_scale()
float input_intermediate_scale () const inline
Definition at line 265 of file LSTMParams.h.
Referenced by arm_compute::utils::info_helpers::build_lstm_params_tensor_info(), NEQLSTMLayer::configure(), CLQLSTMLayer::configure(), LSTMParams< T >::set_matmul_scale_params(), NEQLSTMLayer::validate(), and CLQLSTMLayer::validate().
     {
         return _input_intermediate_scale;
     }
input_layer_norm_weights()
T* input_layer_norm_weights () const inline
Definition at line 235 of file LSTMParams.h.
Referenced by arm_compute::utils::info_helpers::build_lstm_params_tensor_info(), NELSTMLayer::configure(), NEQLSTMLayer::configure(), CLLSTMLayer::configure(), CLQLSTMLayer::configure(), LSTMParams< T >::set_layer_normalization_params(), NELSTMLayer::validate(), NEQLSTMLayer::validate(), CLLSTMLayer::validate(), and CLQLSTMLayer::validate().
     {
         return _input_layer_norm_weights;
     }
input_to_input_weights()
const T* input_to_input_weights () const inline
Definition at line 195 of file LSTMParams.h.
Referenced by arm_compute::utils::info_helpers::build_lstm_params_tensor_info(), NELSTMLayer::configure(), NEQLSTMLayer::configure(), CLLSTMLayer::configure(), CLQLSTMLayer::configure(), LSTMParams< T >::set_cifg_params(), NELSTMLayer::validate(), NEQLSTMLayer::validate(), CLLSTMLayer::validate(), and CLQLSTMLayer::validate().
     {
         return _input_to_input_weights;
     }
operator=()
LSTMParams& operator= (const LSTMParams< T > &) delete
Prevent instances of this class from being copied (As this class contains pointers)
Referenced by LSTMParams< T >::LSTMParams().
output_intermediate_scale()
float output_intermediate_scale () const inline
Definition at line 280 of file LSTMParams.h.
Referenced by arm_compute::utils::info_helpers::build_lstm_params_tensor_info(), NEQLSTMLayer::configure(), CLQLSTMLayer::configure(), LSTMParams< T >::set_matmul_scale_params(), NEQLSTMLayer::validate(), and CLQLSTMLayer::validate().
     {
         return _output_intermediate_scale;
     }
output_layer_norm_weights()
T* output_layer_norm_weights () const inline
Definition at line 250 of file LSTMParams.h.
Referenced by arm_compute::utils::info_helpers::build_lstm_params_tensor_info(), NELSTMLayer::configure(), NEQLSTMLayer::configure(), CLLSTMLayer::configure(), CLQLSTMLayer::configure(), LSTMParams< T >::set_layer_normalization_params(), NELSTMLayer::validate(), NEQLSTMLayer::validate(), CLLSTMLayer::validate(), and CLQLSTMLayer::validate().
     {
         return _output_layer_norm_weights;
     }
projection_bias()
const T* projection_bias () const inline
Definition at line 230 of file LSTMParams.h.
Referenced by arm_compute::utils::info_helpers::build_lstm_params_tensor_info(), NELSTMLayer::configure(), NEQLSTMLayer::configure(), CLLSTMLayer::configure(), CLQLSTMLayer::configure(), LSTMParams< T >::set_projection_params(), NELSTMLayer::validate(), NEQLSTMLayer::validate(), CLLSTMLayer::validate(), and CLQLSTMLayer::validate().
     {
         return _projection_bias;
     }
projection_clip()
float projection_clip () const inline
Definition at line 260 of file LSTMParams.h.
Referenced by NEQLSTMLayer::configure(), CLQLSTMLayer::configure(), LSTMParams< T >::set_projection_clip_params(), NEQLSTMLayer::validate(), and CLQLSTMLayer::validate().
     {
         return _projection_clip;
     }
projection_weights()
const T* projection_weights () const inline
Definition at line 225 of file LSTMParams.h.
Referenced by arm_compute::utils::info_helpers::build_lstm_params_tensor_info(), NELSTMLayer::configure(), NEQLSTMLayer::configure(), CLLSTMLayer::configure(), CLQLSTMLayer::configure(), LSTMParams< T >::set_projection_params(), NELSTMLayer::validate(), NEQLSTMLayer::validate(), CLLSTMLayer::validate(), and CLQLSTMLayer::validate().
     {
         return _projection_weights;
     }
recurrent_to_input_weights()
const T* recurrent_to_input_weights () const inline
Definition at line 200 of file LSTMParams.h.
Referenced by arm_compute::utils::info_helpers::build_lstm_params_tensor_info(), NELSTMLayer::configure(), NEQLSTMLayer::configure(), CLLSTMLayer::configure(), CLQLSTMLayer::configure(), LSTMParams< T >::set_cifg_params(), NELSTMLayer::validate(), NEQLSTMLayer::validate(), CLLSTMLayer::validate(), and CLQLSTMLayer::validate().
     {
         return _recurrent_to_input_weights;
     }
set_cell_clip_params()
LSTMParams& set_cell_clip_params (float cell_clip) inline
Set cell clip value.
Parameters
[in] cell_clip Value to be used to clip the cell state prior to the cell output activation.
Returns
Reference to this LSTMParams object
Definition at line 145 of file LSTMParams.h.
References LSTMParams< T >::cell_clip().
     {
         _cell_clip = cell_clip;
         return *this;
     }
set_cifg_params()
LSTMParams& set_cifg_params (const T * input_to_input_weights, const T * recurrent_to_input_weights, T * cell_to_input_weights, const T * input_gate_bias) inline
Set CIFG tensor parameters.
Parameters
[in] input_to_input_weights 2D weights tensor with dimensions [input_size, num_units]. Data types supported: QSYMM8/F16/F32.
[in] recurrent_to_input_weights 2D weights tensor with dimensions [output_size, num_units]. Data type supported: Same as input_to_input_weights.
[in] cell_to_input_weights 1D weights tensor with dimensions [num_units]. Can be nullptr. Data type supported: Same as input_to_input_weights.
[in] input_gate_bias 1D weights tensor with dimensions [num_units]. Data type supported: Same as input_to_input_weights, S32 when input_to_input_weights is QSYMM8
Returns
Reference to this LSTMParams object
Definition at line 82 of file LSTMParams.h.
References LSTMParams< T >::cell_to_input_weights(), LSTMParams< T >::input_gate_bias(), LSTMParams< T >::input_to_input_weights(), and LSTMParams< T >::recurrent_to_input_weights().
Referenced by arm_compute::utils::info_helpers::build_lstm_params_tensor_info().
     {
         _input_to_input_weights     = input_to_input_weights;
         _recurrent_to_input_weights = recurrent_to_input_weights;
         _cell_to_input_weights      = cell_to_input_weights;
         _input_gate_bias            = input_gate_bias;
         _has_cifg_opt               = false;
         return *this;
     }
set_hidden_state_params()
LSTMParams& set_hidden_state_params (int32_t hidden_state_zero, float hidden_state_scale) inline
Set hidden state zero and scale parameters.
Parameters
[in] hidden_state_zero The zero point of the hidden state.
[in] hidden_state_scale The scale of the hidden state.
Returns
Reference to this LSTMParams object
Definition at line 188 of file LSTMParams.h.
References LSTMParams< T >::hidden_state_scale(), and LSTMParams< T >::hidden_state_zero().
Referenced by arm_compute::utils::info_helpers::build_lstm_params_tensor_info().
     {
         _hidden_state_zero  = hidden_state_zero;
         _hidden_state_scale = hidden_state_scale;
         return *this;
     }
set_layer_normalization_params()
LSTMParams& set_layer_normalization_params (T * input_layer_norm_weights, T * forget_layer_norm_weights, T * cell_layer_norm_weights, T * output_layer_norm_weights) inline
Set layer normalization tensor parameters.
Parameters
[in] input_layer_norm_weights 1D weights tensor with dimensions [num_units]. Data type supported: Data types supported: QSYMM16/F16/F32.
[in] forget_layer_norm_weights 1D weights tensor with dimensions [num_units]. Data type supported: Same as input_layer_norm_weights.
[in] cell_layer_norm_weights 1D weights tensor with dimensions [num_units]. Data type supported: Same as input_layer_norm_weights.
[in] output_layer_norm_weights 1D weights tensor with dimensions [num_units]. Data type supported: Same as input_layer_norm_weights.
Returns
Reference to this LSTMParams object
Definition at line 128 of file LSTMParams.h.
References LSTMParams< T >::cell_layer_norm_weights(), LSTMParams< T >::forget_layer_norm_weights(), LSTMParams< T >::input_layer_norm_weights(), and LSTMParams< T >::output_layer_norm_weights().
Referenced by arm_compute::utils::info_helpers::build_lstm_params_tensor_info().
     {
         _input_layer_norm_weights  = input_layer_norm_weights;
         _forget_layer_norm_weights = forget_layer_norm_weights;
         _cell_layer_norm_weights   = cell_layer_norm_weights;
         _output_layer_norm_weights = output_layer_norm_weights;
         _use_layer_norm            = true;
         return *this;
     }
set_matmul_scale_params()
LSTMParams& set_matmul_scale_params (float input_intermediate_scale, float forget_intermediate_scale, float cell_intermediate_scale, float output_intermediate_scale) inline
Set scale of the intermediate results of matmul of each layer parameters.
Parameters
[in] input_intermediate_scale Scale of the intermediate result of matmul, i.e. input to layer normalization, at input gate.
[in] forget_intermediate_scale Scale of the intermediate result of matmul, i.e. input to layer normalization, at forget gate.
[in] cell_intermediate_scale Scale of the intermediate result of matmul, i.e. input to layer normalization, at cell gate.
[in] output_intermediate_scale Scale of the intermediate result of matmul, i.e. input to layer normalization, at output gate.
Returns
Reference to this LSTMParams object
Definition at line 172 of file LSTMParams.h.
References LSTMParams< T >::cell_intermediate_scale(), LSTMParams< T >::forget_intermediate_scale(), LSTMParams< T >::input_intermediate_scale(), and LSTMParams< T >::output_intermediate_scale().
Referenced by arm_compute::utils::info_helpers::build_lstm_params_tensor_info().
     {
         _input_intermediate_scale  = input_intermediate_scale;
         _forget_intermediate_scale = forget_intermediate_scale;
         _cell_intermediate_scale   = cell_intermediate_scale;
         _output_intermediate_scale = output_intermediate_scale;
         return *this;
     }
set_peephole_params()
LSTMParams& set_peephole_params (T * cell_to_forget_weights, T * cell_to_output_weights) inline
Set peephole tensor parameters.
Parameters
[in] cell_to_forget_weights 1D weights tensor with dimensions [num_units]. Data type supported: Data types supported: QSYMM16/F16/F32.
[in] cell_to_output_weights 1D weights tensor with dimensions [num_units]. Data type supported: Same as cell_to_forget_weights.
Returns
Reference to this LSTMParams object
Definition at line 112 of file LSTMParams.h.
References LSTMParams< T >::cell_to_forget_weights(), and LSTMParams< T >::cell_to_output_weights().
Referenced by arm_compute::utils::info_helpers::build_lstm_params_tensor_info(), and arm_compute::test::validation::DATA_TEST_CASE().
     {
         _cell_to_forget_weights = cell_to_forget_weights;
         _cell_to_output_weights = cell_to_output_weights;
         _has_peephole_opt       = true;
         return *this;
     }
set_projection_clip_params()
LSTMParams& set_projection_clip_params (float projection_clip) inline
Set projection clip value.
Parameters
[in] projection_clip Value to be used to clip the projection, in case projection is enabled.
Returns
Reference to this LSTMParams object
Definition at line 157 of file LSTMParams.h.
References LSTMParams< T >::projection_clip().
     {
         _projection_clip = projection_clip;
         return *this;
     }
set_projection_params()
LSTMParams& set_projection_params (const T * projection_weights, const T * projection_bias) inline
Set projection tensor parameters.
Parameters
[in] projection_weights 2D weights tensor with dimensions [output_size, num_units]. Data type supported: Data types supported: QSYMM8/F16/F32.
[in] projection_bias 1D weights tensor with dimensions [output_size]. Data type supported: Same as projection_weights, S32 when input_to_input_weights is QSYMM8.
Returns
Reference to this LSTMParams object
Definition at line 98 of file LSTMParams.h.
References LSTMParams< T >::projection_bias(), and LSTMParams< T >::projection_weights().
Referenced by arm_compute::utils::info_helpers::build_lstm_params_tensor_info().
     {
         _projection_weights = projection_weights;
         _projection_bias    = projection_bias;
         _has_projection     = true;
         return *this;
     }
use_layer_norm()
bool use_layer_norm () const inline
Definition at line 310 of file LSTMParams.h.
Referenced by arm_compute::utils::info_helpers::build_lstm_params_tensor_info(), NELSTMLayer::configure(), NEQLSTMLayer::configure(), CLLSTMLayer::configure(), CLQLSTMLayer::configure(), NELSTMLayer::validate(), NEQLSTMLayer::validate(), CLLSTMLayer::validate(), and CLQLSTMLayer::validate().
     {
         return _use_layer_norm;
     }
The documentation for this class was generated from the following file:
arm_compute/runtime/common/LSTMParams.h