Compute Library: IScheduler::Hints Class Reference
IScheduler::Hints Class Reference
Scheduler hints.
#include <IScheduler.h>
Public Member Functions
Hints (unsigned int split_dimension, StrategyHint strategy=StrategyHint::STATIC, int threshold=0)
Constructor.
Hints & set_split_dimension (unsigned int split_dimension)
Set the split_dimension hint.
unsigned int split_dimension () const
Return the prefered split dimension.
Hints & set_strategy (StrategyHint strategy)
Set the strategy hint.
StrategyHint strategy () const
Return the prefered strategy to use to split workload.
int threshold () const
Return the granule capping threshold to be used by dynamic scheduling.
Detailed Description
Scheduler hints.
Collection of preferences set by the function regarding how to split a given workload
Definition at line 68 of file IScheduler.h.
Constructor & Destructor Documentation
Hints()
Hints (unsigned int split_dimension, StrategyHint strategy = StrategyHint::STATIC, int threshold = 0) inline
Constructor.
Parameters
[in] split_dimension Dimension along which to split the kernel's execution window.
[in] strategy (Optional) Split strategy.
[in] threshold (Optional) Dynamic scheduling capping threshold.
Definition at line 77 of file IScheduler.h.
             : _split_dimension(split_dimension), _strategy(strategy), _threshold(threshold)
         {
         }
Member Function Documentation
set_split_dimension()
Hints& set_split_dimension (unsigned int split_dimension) inline
Set the split_dimension hint.
Parameters
[in] split_dimension Dimension along which to split the kernel's execution window.
Returns
the Hints object
Definition at line 87 of file IScheduler.h.
         {
             _split_dimension = split_dimension;
             return *this;
         }
set_strategy()
Hints& set_strategy (StrategyHint strategy) inline
Set the strategy hint.
Parameters
[in] strategy Prefered strategy to use to split the workload
Returns
the Hints object
Definition at line 107 of file IScheduler.h.
References strategy.
         {
             _strategy = strategy;
             return *this;
         }
split_dimension()
unsigned int split_dimension () const inline
Return the prefered split dimension.
Returns
The split dimension
Definition at line 96 of file IScheduler.h.
Referenced by IScheduler::num_threads_hint(), SingleThreadScheduler::schedule(), and OMPScheduler::schedule_op().
         {
             return _split_dimension;
         }
strategy()
StrategyHint strategy () const inline
Return the prefered strategy to use to split workload.
Returns
The strategy
Definition at line 116 of file IScheduler.h.
Referenced by IScheduler::num_threads_hint(), and OMPScheduler::schedule_op().
         {
             return _strategy;
         }
threshold()
int threshold () const inline
Return the granule capping threshold to be used by dynamic scheduling.
Returns
The capping threshold
Definition at line 124 of file IScheduler.h.
Referenced by IScheduler::num_threads_hint().
         {
             return _threshold;
         }
The documentation for this class was generated from the following file:
arm_compute/runtime/IScheduler.h