Compute Library: CpuPermuteKernel Class Reference
CpuPermuteKernel Class Reference
Kernel to perform tensor permutation given a permutation vector.
#include <CpuPermuteKernel.h>
Public Member Functions
CpuPermuteKernel ()=default
ARM_COMPUTE_DISALLOW_COPY_ALLOW_MOVE (CpuPermuteKernel)
void configure (const ITensorInfo *src, ITensorInfo *dst, const PermutationVector &perm)
Configure kernel for a given list of arguments.
void run_op (ITensorPack &tensors, const Window &window, const ThreadInfo &info) override
Execute the kernel on the passed window.
const char * name () const override
Name of the kernel.
Public Member Functions inherited from ICPPKernel
virtual ~ICPPKernel ()=default
Default destructor.
virtual void run (const Window &window, const ThreadInfo &info)
Execute the kernel on the passed window.
virtual void run_nd (const Window &window, const ThreadInfo &info, const Window &thread_locator)
legacy compatibility layer for implemantions which do not support thread_locator In these cases we simply narrow the interface down the legacy version
virtual size_t get_mws (const CPUInfo &platform, size_t thread_count) const
Return minimum workload size of the relevant kernel.
Public Member Functions inherited from IKernel
IKernel ()
Constructor.
virtual ~IKernel ()=default
Destructor.
virtual bool is_parallelisable () const
Indicates whether or not the kernel is parallelisable.
virtual BorderSize border_size () const
The size of the border for that kernel.
const Window & window () const
The maximum window the kernel can be executed on.
bool is_window_configured () const
Function to check if the embedded window of this kernel has been configured.
Static Public Member Functions
static Status validate (const ITensorInfo *src, const ITensorInfo *dst, const PermutationVector &perm)
Static function to check if given info will lead to a valid configuration.
Static Public Member Functions inherited from ICpuKernel< CpuPermuteKernel >
static const auto * get_implementation (const SelectorType &selector, KernelSelectionType selection_type=KernelSelectionType::Supported)
Micro-kernel selector.
Additional Inherited Members
Static Public Attributes inherited from ICPPKernel
static constexpr size_t default_mws = 1
Detailed Description
Kernel to perform tensor permutation given a permutation vector.
Definition at line 37 of file CpuPermuteKernel.h.
Constructor & Destructor Documentation
CpuPermuteKernel()
CpuPermuteKernel () default
Member Function Documentation
ARM_COMPUTE_DISALLOW_COPY_ALLOW_MOVE()
ARM_COMPUTE_DISALLOW_COPY_ALLOW_MOVE (CpuPermuteKernel)
configure()
void configure (const ITensorInfo * src, ITensorInfo * dst, const PermutationVector & perm)
Configure kernel for a given list of arguments.
Note
Arbitrary permutation vectors are supported with rank not greater than 4
Parameters
[in] src Srouce tensor to permute. Data types supported: All
[out] dst Destination tensor. Data types supported: Same as src
[in] perm Permutation vector
Definition at line 243 of file CpuPermuteKernel.cpp.
References ARM_COMPUTE_ERROR_ON_NULLPTR, ARM_COMPUTE_ERROR_THROW_ON, arm_compute::auto_init_if_empty(), arm_compute::calculate_max_window(), ICloneable< T >::clone(), arm_compute::misc::shape_calculator::compute_permutation_output_shape(), arm_compute::test::validation::dst_shape, and arm_compute::cpu::kernels::validate_arguments().
 {
     ARM_COMPUTE_ERROR_ON_NULLPTR(src, dst);
     const TensorShape dst_shape = misc::shape_calculator::compute_permutation_output_shape(*src, perm);
     // Destination auto inizialitation if not yet initialized
     auto_init_if_empty(*dst, src->clone()->set_tensor_shape(dst_shape));
     // Perform validation step
     ARM_COMPUTE_ERROR_THROW_ON(validate_arguments(src, dst, perm));
     _perm = perm;
     // Configure kernel window
     Window win = calculate_max_window(*src, Steps());
     // This kernel doesn't need padding so update_window_and_padding() can be skipped
     ICpuKernel::configure(win);
 }
name()
const char * name () const override virtual
Name of the kernel.
Returns
Kernel name
Implements ICPPKernel.
Definition at line 295 of file CpuPermuteKernel.cpp.
 {
     return "CpuPermuteKernel";
 }
run_op()
void run_op (ITensorPack & tensors, const Window & window, const ThreadInfo & info) override virtual
Execute the kernel on the passed window.
Warning
If is_parallelisable() returns false then the passed window must be equal to window()
Note
The window has to be a region within the window returned by the window() method
The width of the window has to be a multiple of num_elems_processed_per_iteration().
Parameters
[in] tensors A vector containing the tensors to operate on.
[in] window Region on which to execute the kernel. (Must be a region of the window returned by window())
[in] info Info about executing thread and CPU.
Reimplemented from ICPPKernel.
Definition at line 269 of file CpuPermuteKernel.cpp.
References arm_compute::ACL_DST, arm_compute::ACL_SRC, ARM_COMPUTE_ERROR, ARM_COMPUTE_ERROR_ON_INVALID_SUBWINDOW, ARM_COMPUTE_ERROR_ON_UNCONFIGURED_KERNEL, ARM_COMPUTE_UNUSED, arm_compute::test::validation::dst, ITensorPack::get_const_tensor(), ITensorPack::get_tensor(), arm_compute::test::validation::src, and IKernel::window().
 {
     ARM_COMPUTE_UNUSED(info);
     ARM_COMPUTE_ERROR_ON_UNCONFIGURED_KERNEL(this);
     ARM_COMPUTE_ERROR_ON_INVALID_SUBWINDOW(ICpuKernel::window(), window);
     const auto src = tensors.get_const_tensor(TensorType::ACL_SRC);
     auto       dst = tensors.get_tensor(TensorType::ACL_DST);
     switch(src->info()->element_size())
     {
         case 1:
             run_permute<uint8_t>(window, src, dst, _perm);
             break;
         case 2:
             run_permute<uint16_t>(window, src, dst, _perm);
             break;
         case 4:
             run_permute<uint32_t>(window, src, dst, _perm);
             break;
         default:
             ARM_COMPUTE_ERROR("Element size not supported");
             break;
     }
 }
validate()
Status validate (const ITensorInfo * src, const ITensorInfo * dst, const PermutationVector & perm) static
Static function to check if given info will lead to a valid configuration.
Similar to CpuPermuteKernel::configure()
Returns
a status
Definition at line 263 of file CpuPermuteKernel.cpp.
References ARM_COMPUTE_RETURN_ON_ERROR, and arm_compute::cpu::kernels::validate_arguments().
Referenced by CpuPermute::validate().
 {
     ARM_COMPUTE_RETURN_ON_ERROR(validate_arguments(src, dst, perm));
     return Status{};
 }
The documentation for this class was generated from the following files:
src/cpu/kernels/CpuPermuteKernel.h
src/cpu/kernels/CpuPermuteKernel.cpp