Compute Library: CpuSub Class Reference
CpuSub Class Reference
Basic function to run kernels::CpuSubKernel.
#include <CpuSub.h>
Public Member Functions
void configure (const ITensorInfo *src0, const ITensorInfo *src1, ITensorInfo *dst, ConvertPolicy policy, const ActivationLayerInfo &act_info=ActivationLayerInfo())
Initialise the kernel's inputs, dst and conversion policy.
Public Member Functions inherited from INEOperator
INEOperator (IRuntimeContext *ctx=nullptr)
Constructor.
INEOperator (const INEOperator &)=delete
Prevent instances of this class from being copied (As this class contains pointers)
INEOperator (INEOperator &&)=default
Default move constructor.
INEOperator & operator= (const INEOperator &)=delete
Prevent instances of this class from being copied (As this class contains pointers)
INEOperator & operator= (INEOperator &&)=default
Default move assignment operator.
~INEOperator ()
Default destructor.
void run (ITensorPack &tensors) override
Run the kernels contained in the function.
void prepare (ITensorPack &constants) override
Prepare the function for executing.
MemoryRequirements workspace () const override
Return the memory requirements required by the workspace.
Public Member Functions inherited from IOperator
virtual ~IOperator ()=default
Destructor.
Static Public Member Functions
static Status validate (const ITensorInfo *src0, const ITensorInfo *src1, const ITensorInfo *dst, ConvertPolicy policy, const ActivationLayerInfo &act_info=ActivationLayerInfo())
Static function to check if given info will lead to a valid configuration.
Detailed Description
Basic function to run kernels::CpuSubKernel.
Definition at line 34 of file CpuSub.h.
Member Function Documentation
configure()
void configure (const ITensorInfo * src0, const ITensorInfo * src1, ITensorInfo * dst, ConvertPolicy policy, const ActivationLayerInfo & act_info = ActivationLayerInfo())
Initialise the kernel's inputs, dst and conversion policy.
Valid configurations (src0,src1) -> dst :
(U8,U8) -> U8
(QASYMM8, QASYMM8) -> QASYMM8
(QASYMM8_SIGNED, QASYMM8_SIGNED) -> QASYMM8_SIGNED
(S16,S16) -> S16
(S32,S32) -> S32
(F16,F16) -> F16
(F32,F32) -> F32
Parameters
[in] src0 First tensor input info. Data types supported: U8/QASYMM8/QASYMM8_SIGNED/QSYMM16/S16/S32/F16/F32
[in] src1 Second tensor input info. Data types supported: U8/QASYMM8/QASYMM8_SIGNED/QSYMM16/S16/S32/F16/F32
[out] dst Output tensor info. Data types supported: U8/QASYMM8/QASYMM8_SIGNED/QSYMM16/S16/S32/F16/F32
[in] policy Policy to use to handle overflow. Convert policy cannot be WRAP if datatype is quantized.
[in] act_info (Optional) Activation layer information in case of a fused activation. Currently not supported.
Definition at line 34 of file CpuSub.cpp.
References ARM_COMPUTE_LOG_PARAMS, ARM_COMPUTE_UNUSED, and arm_compute::test::validation::k.
 {
     ARM_COMPUTE_UNUSED(act_info);
     ARM_COMPUTE_LOG_PARAMS(src0, src1, dst, policy);
     auto k = std::make_unique<kernels::CpuSubKernel>();
     k->configure(src0, src1, dst, policy);
     _kernel = std::move(k);
 }
validate()
Status validate (const ITensorInfo * src0, const ITensorInfo * src1, const ITensorInfo * dst, ConvertPolicy policy, const ActivationLayerInfo & act_info = ActivationLayerInfo()) static
Static function to check if given info will lead to a valid configuration.
Similar to CpuSub::configure()
Returns
a status
Definition at line 43 of file CpuSub.cpp.
References ARM_COMPUTE_RETURN_ERROR_ON, ActivationLayerInfo::enabled(), and CpuSubKernel::validate().
Referenced by NEArithmeticSubtraction::validate().
 {
     ARM_COMPUTE_RETURN_ERROR_ON(act_info.enabled());
     return kernels::CpuSubKernel::validate(src0, src1, dst, policy);
 }
The documentation for this class was generated from the following files:
src/cpu/operators/CpuSub.h
src/cpu/operators/CpuSub.cpp