Compute Library: FloorContent Class Reference
FloorContent Class Reference
#include <OperatorGraphImpl.h>
Public Member Functions
FloorContent ()=default
FloorContent (const OperatorGraph::Implementation *graph, Id id, const FloorDescriptor &desc, const ITensorDescPack< OpTensorContent > &tensors)
~FloorContent ()=default
FloorContent (const FloorContent &)=default
FloorContent & operator= (const FloorContent &)=default
FloorContent (FloorContent &&)=default
FloorContent & operator= (FloorContent &&)=default
bool operator== (const OperatorContent &other) const override
OperatorComplexity complexity () const override
Status translate (ClKernelGraph &kernel_graph) const override
Public Member Functions inherited from OperatorContent
OperatorContent ()=default
OperatorContent (const OperatorGraph::Implementation *graph, Id id, const ITensorDescPack< OpTensorContent > &tensors)
OperatorContent (const OperatorContent &op)=default
OperatorContent & operator= (const OperatorContent &op)=default
OperatorContent (OperatorContent &&op)=default
OperatorContent & operator= (OperatorContent &&op)=default
virtual ~OperatorContent ()=default
Additional Inherited Members
Public Types inherited from OperatorContent
using Id = DependencyGraph::Id
Detailed Description
Definition at line 184 of file OperatorGraphImpl.h.
Constructor & Destructor Documentation
FloorContent() [1/4]
FloorContent () default
FloorContent() [2/4]
FloorContent (const OperatorGraph::Implementation * graph, Id id, const FloorDescriptor & desc, const ITensorDescPack< OpTensorContent > & tensors) inline
Definition at line 188 of file OperatorGraphImpl.h.
References arm_compute::experimental::dynamic_fusion::operator==().
         : OperatorContent(graph, id, tensors), desc(desc)
     {
     }
~FloorContent()
~FloorContent () default
FloorContent() [3/4]
FloorContent (const FloorContent &) default
FloorContent() [4/4]
FloorContent (FloorContent &&) default
Member Function Documentation
complexity()
OperatorComplexity complexity () const inline override virtual
Implements OperatorContent.
Definition at line 198 of file OperatorGraphImpl.h.
References arm_compute::experimental::dynamic_fusion::Simple, and arm_compute::experimental::dynamic_fusion::translate().
     {
         return OperatorComplexity::Simple;
     }
operator=() [1/2]
FloorContent& operator= (const FloorContent &) default
operator=() [2/2]
FloorContent& operator= (FloorContent &&) default
operator==()
bool operator== (const OperatorContent & other) const override virtual
Implements OperatorContent.
Definition at line 138 of file OperatorGraphImpl.cpp.
References Conv2dContent::desc.
 {
     const auto converted = *utils::cast::polymorphic_downcast<const FloorContent *>(&other);
     return desc == converted.desc;
 }
translate()
Status translate (ClKernelGraph & kernel_graph) const override virtual
Implements OperatorContent.
Definition at line 362 of file OperatorGraphImpl.cpp.
References arm_compute::ACL_DST_0, arm_compute::ACL_SRC_0, ITensorDescPack< TDesc >::add_const_tensor(), ClKernelGraph::add_kernel(), ARM_COMPUTE_ERROR_ON_NULLPTR, ARM_COMPUTE_RETURN_ON_ERROR, Conv2dContent::desc, arm_compute::test::validation::dst, ClKernelGraph::get_tensor(), UnitWorkloadStage::Run, arm_compute::test::validation::src, arm_compute::experimental::dynamic_fusion::TStoreIndirectWidthSelect, and ClFloorKernel::validate().
 {
     const auto src = _tensors.get_const_tensor(TensorType::ACL_SRC_0);
     const auto dst = _tensors.get_const_tensor(TensorType::ACL_DST_0);
     ARM_COMPUTE_ERROR_ON_NULLPTR(src, dst);
     ITensorDescPack<ClKernelTensor> tensors;
     DependencyGraph::Id src_id;
     auto                st = add_kernel_tensor(kernel_graph, *_graph, *src, src_id);
     ARM_COMPUTE_RETURN_ON_ERROR(st);
     tensors.add_const_tensor(ACL_SRC_0, kernel_graph.get_tensor(src_id));
     DependencyGraph::Id dst_id;
     st = add_kernel_tensor(kernel_graph, *_graph, *dst, dst_id);
     ARM_COMPUTE_RETURN_ON_ERROR(st);
     tensors.add_const_tensor(ACL_DST_0, kernel_graph.get_tensor(dst_id));
     DependencyGraph::Id add_id;
     ClKernelConfig      config{ UnitWorkloadStage{ UnitWorkloadStage::Stage::Run }, TileDescriptor{}, StoreType::TStoreIndirectWidthSelect };
     st = ClFloorKernel::validate(src->desc, dst->desc);
     ARM_COMPUTE_RETURN_ON_ERROR(st);
     st = kernel_graph.add_kernel<ClFloorKernel>(config, ClFloorKernelDescriptor{ desc }, tensors, add_id);
     ARM_COMPUTE_RETURN_ON_ERROR(st);
     return Status{};
 }
The documentation for this class was generated from the following files:
src/core/experimental/dynamic_fusion/WorkloadImpl/OperatorGraphImpl.h
src/core/experimental/dynamic_fusion/WorkloadImpl/OperatorGraphImpl.cpp