Compute Library: ClStoreBlockBoundaryAwareKernelComponent Class Reference
ClStoreBlockBoundaryAwareKernelComponent Class Reference
#include <ClStoreKernelComponents.h>
Public Member Functions
ClStoreBlockBoundaryAwareKernelComponent (ClKernelBlueprint *blueprint, const Link &src, const Link &dst)
ComponentType get_component_type () const override
std::string get_component_code () const override
CLBuildOptions generate_build_options () const override
TagLUT get_tag_lut (const SharedVarTable &vtable) const override
Get the tag look-up table used to instantiate the component code.
void allocate_shared_vars (SharedVarTable &vtable) const override
Allocate all shared variables used by the component in the vtable.
virtual std::vector< Link > get_links () const override
virtual std::string name () const override
Public Member Functions inherited from IClKernelComponent
IClKernelComponent (ClKernelBlueprint *blueprint)
ARM_COMPUTE_DISALLOW_COPY_ALLOW_MOVE (IClKernelComponent)
virtual ~IClKernelComponent ()=default
ComponentID id () const
void set_id (ComponentID id)
virtual std::set< std::string > get_headers_list () const
virtual std::string get_additional_macros () const
virtual Window get_window () const
virtual std::string get_dst_addr_calculation () const
virtual std::string generate_config_id () const
Generate config id of the component.
Additional Inherited Members
Public Types inherited from IClKernelComponent
using Link = SharedVarLink
using Tag = std::string
using TagLUT = std::unordered_map< Tag, TagVal >
Static Public Member Functions inherited from IClKernelComponent
static std::string replace_tags (const std::string &code_template, const TagLUT &tags)
Detailed Description
Definition at line 37 of file ClStoreKernelComponents.h.
Constructor & Destructor Documentation
ClStoreBlockBoundaryAwareKernelComponent()
ClStoreBlockBoundaryAwareKernelComponent (ClKernelBlueprint * blueprint, const Link & src, const Link & dst) inline
Definition at line 40 of file ClStoreKernelComponents.h.
References ClStoreBlockBoundaryAwareKernelComponent::allocate_shared_vars(), arm_compute::test::validation::dst, ClStoreBlockBoundaryAwareKernelComponent::generate_build_options(), ClStoreBlockBoundaryAwareKernelComponent::get_component_code(), ClStoreBlockBoundaryAwareKernelComponent::get_component_type(), and ClStoreBlockBoundaryAwareKernelComponent::get_tag_lut().
         : IClKernelComponent(blueprint), _src{ src }, _dst{ dst }
     {
     }
Member Function Documentation
allocate_shared_vars()
void allocate_shared_vars (SharedVarTable & vtable) const override virtual
Allocate all shared variables used by the component in the vtable.
Parameters
vtable
Implements IClKernelComponent.
Definition at line 86 of file ClStoreKernelComponents.cpp.
References SharedVarTable::add(), SharedVarLink::arg_id, and arm_compute::experimental::dynamic_fusion::Image_3D.
Referenced by ClStoreBlockBoundaryAwareKernelComponent::ClStoreBlockBoundaryAwareKernelComponent(), and ClStoreIndirectWidthSelectKernelComponent::ClStoreIndirectWidthSelectKernelComponent().
 {
     vtable.add(_src, _blueprint->impl().group(_src.arg_id), ClKernelArgDescriptor(_src.arg_id, ClKernelTensorArgType::Image_3D), "src");
     vtable.add(_dst, _blueprint->impl().group(_dst.arg_id), ClKernelArgDescriptor(_dst.arg_id, ClKernelTensorArgType::Image_3D), "dst");
 }
generate_build_options()
CLBuildOptions generate_build_options () const override virtual
Reimplemented from IClKernelComponent.
Definition at line 65 of file ClStoreKernelComponents.cpp.
References arm_compute::get_cl_type_from_data_type(), arm_compute::test::validation::t_dst_info, and arm_compute::support::cpp11::to_string().
Referenced by ClStoreBlockBoundaryAwareKernelComponent::ClStoreBlockBoundaryAwareKernelComponent(), and ClStoreIndirectWidthSelectKernelComponent::ClStoreIndirectWidthSelectKernelComponent().
 {
     auto t_dst_info = _blueprint->impl().get_kernel_argument_info(_blueprint->impl().get_dst_id());
     // auto tile_info  = _blueprint->impl().get_tile_info();
     CLBuildOptions build_opts{};
     const auto n0         = _blueprint->impl().get_execution_window().x().step();
     const auto m0         = _blueprint->impl().get_execution_window().y().step();
     const auto partial_m0 = t_dst_info->dimension(0) % m0;
     const auto partial_n0 = t_dst_info->dimension(1) % n0;
     build_opts.add_option("-DDATA_TYPE=" + get_cl_type_from_data_type(t_dst_info->data_type()));
     build_opts.add_option("-DM0=" + support::cpp11::to_string(m0));
     build_opts.add_option("-DN0=" + support::cpp11::to_string(n0));
     build_opts.add_option("-DPARTIAL_STORE_M0=" + support::cpp11::to_string(partial_m0));
     build_opts.add_option("-DPARTIAL_STORE_N0=" + support::cpp11::to_string(partial_n0));
     return build_opts;
 }
get_component_code()
std::string get_component_code () const override virtual
Reimplemented from IClKernelComponent.
Definition at line 39 of file ClStoreKernelComponents.cpp.
Referenced by ClStoreBlockBoundaryAwareKernelComponent::ClStoreBlockBoundaryAwareKernelComponent(), and ClStoreIndirectWidthSelectKernelComponent::ClStoreIndirectWidthSelectKernelComponent().
 {
     return R"_(
     //------------------ START KERNEL {{meta_kernel_id}} STORE ---------------------
     __global uchar *dst_addr = {{dst}}_ptr + {{dst}}_offset_first_element_in_bytes + (g_x * (uint)N0 * sizeof(DATA_TYPE)) + (COMPUTE_M0_START_ROW(g_y, M0, PARTIAL_STORE_M0) * {{dst}}_stride_y);
 #if defined(REINTERPRET_OUTPUT_AS_3D)
     // Add offset for batched GEMM. The batches will be in the fourth dimension and for this reason we
     // multiply dst_stride_z by DEPTH_GEMM3D
     dst_addr += g_z * {{dst}}_stride_z * DEPTH_GEMM3D;
 #else // defined(REINTERPRET_OUTPUT_AS_3D)
     // Add offset for batched GEMM
     dst_addr += g_z * {{dst}}_stride_z;
 #endif // defined(REINTERPRET_OUTPUT_AS_3D)
     STORE_BLOCK_BOUNDARY_AWARE(M0, N0, DATA_TYPE, {{src}}, dst_addr, {{dst}}_stride_y, g_zout, PARTIAL_STORE_M0, PARTIAL_STORE_N0, g_cond_y, g_cond_x);
     //------------------ END KERNEL {{meta_kernel_id}} STORE ---------------------
 )_";
 }
get_component_type()
ComponentType get_component_type () const override virtual
Implements IClKernelComponent.
Definition at line 34 of file ClStoreKernelComponents.cpp.
References arm_compute::experimental::dynamic_fusion::Store.
Referenced by ClStoreBlockBoundaryAwareKernelComponent::ClStoreBlockBoundaryAwareKernelComponent(), and ClStoreIndirectWidthSelectKernelComponent::ClStoreIndirectWidthSelectKernelComponent().
 {
     return ComponentType::Store;
 }
get_links()
virtual std::vector<Link> get_links () const inline override virtual
Implements IClKernelComponent.
Definition at line 50 of file ClStoreKernelComponents.h.
     {
         return { _src, _dst };
     }
get_tag_lut()
ClStoreBlockBoundaryAwareKernelComponent::TagLUT get_tag_lut (const SharedVarTable & vtable) const override virtual
Get the tag look-up table used to instantiate the component code.
Parameters
vtable
Returns
TagLUT
Implements IClKernelComponent.
Definition at line 92 of file ClStoreKernelComponents.cpp.
References SharedVarTable::get(), and IClKernelComponent::id().
Referenced by ClStoreBlockBoundaryAwareKernelComponent::ClStoreBlockBoundaryAwareKernelComponent(), and ClStoreIndirectWidthSelectKernelComponent::ClStoreIndirectWidthSelectKernelComponent().
 {
     return {
         { "meta_kernel_id", id() },
         { "src", vtable.get(_src) },
         { "dst", vtable.get(_dst) },
     };
 }
name()
virtual std::string name () const inline override virtual
Implements IClKernelComponent.
Definition at line 55 of file ClStoreKernelComponents.h.
     {
         return "";
     }
The documentation for this class was generated from the following files:
src/core/experimental/dynamic_fusion/ClKernelBuildingImpl/components/ClStoreKernelComponents.h
src/core/experimental/dynamic_fusion/ClKernelBuildingImpl/components/ClStoreKernelComponents.cpp