Compute Library: NEElementwiseUnaryLayer< op > Class Template Reference
NEElementwiseUnaryLayer< op > Class Template Reference
Basic function to perform unary elementwise operations.
#include <NEElementwiseUnaryLayer.h>
Public Member Functions
NEElementwiseUnaryLayer ()
Default Constructor.
~NEElementwiseUnaryLayer ()
Default Destructor.
NEElementwiseUnaryLayer (const NEElementwiseUnaryLayer &)=delete
Prevent instances of this class from being copied (As this class contains pointers)
NEElementwiseUnaryLayer (NEElementwiseUnaryLayer &&)
Default move constructor.
NEElementwiseUnaryLayer & operator= (const NEElementwiseUnaryLayer &)=delete
Prevent instances of this class from being copied (As this class contains pointers)
NEElementwiseUnaryLayer & operator= (NEElementwiseUnaryLayer &&)
Default move assignment operator.
void configure (const ITensor *input, ITensor *output)
Initialize the function.
void run () override
Run the kernels contained in the function.
Public Member Functions inherited from IFunction
virtual ~IFunction ()=default
Destructor.
virtual void prepare ()
Prepare the function for executing.
Static Public Member Functions
static Status validate (const ITensorInfo *input, const ITensorInfo *output)
Static function to check if given info will lead to a valid configuration.
Detailed Description
template<ElementWiseUnary op>
class arm_compute::NEElementwiseUnaryLayer< op >
Basic function to perform unary elementwise operations.
Definition at line 39 of file NEElementwiseUnaryLayer.h.
Constructor & Destructor Documentation
NEElementwiseUnaryLayer() [1/3]
NEElementwiseUnaryLayer ()
Default Constructor.
Definition at line 41 of file NEElementwiseUnaryLayer.cpp.
References NEElementwiseUnaryLayer< op >::operator=(), and NEElementwiseUnaryLayer< op >::~NEElementwiseUnaryLayer().
     : _impl(std::make_unique<Impl>())
 {
 }
~NEElementwiseUnaryLayer()
~NEElementwiseUnaryLayer () default
Default Destructor.
Referenced by NEElementwiseUnaryLayer< op >::NEElementwiseUnaryLayer().
NEElementwiseUnaryLayer() [2/3]
NEElementwiseUnaryLayer (const NEElementwiseUnaryLayer< op > &) delete
Prevent instances of this class from being copied (As this class contains pointers)
NEElementwiseUnaryLayer() [3/3]
NEElementwiseUnaryLayer (NEElementwiseUnaryLayer< op > &&) default
Default move constructor.
Member Function Documentation
configure()
void configure (const ITensor * input, ITensor * output)
Initialize the function.
Valid data layouts:
All
Valid data type configurations:
src dst
F16 F16
F32 F32
S32 S32
Parameters
[in] input Input tensor. Data types supported: F16/F32, F16/F32/S32 for NEG/ABS operations.
[out] output Output tensor. Data types supported: Same as input.
Definition at line 53 of file NEElementwiseUnaryLayer.cpp.
References arm_compute::test::validation::input.
 {
     _impl->src    = input;
     _impl->dst    = output;
     _impl->cpu_op = std::make_unique<OperatorType>();
     _impl->cpu_op->configure(op, *_impl->src->info(), *_impl->dst->info());
 }
operator=() [1/2]
NEElementwiseUnaryLayer& operator= (const NEElementwiseUnaryLayer< op > &) delete
Prevent instances of this class from being copied (As this class contains pointers)
Referenced by NEElementwiseUnaryLayer< op >::NEElementwiseUnaryLayer().
operator=() [2/2]
NEElementwiseUnaryLayer< op > & operator= (NEElementwiseUnaryLayer< op > &&) default
Default move assignment operator.
run()
void run () override virtual
Run the kernels contained in the function.
For CPU kernels:
Multi-threading is used for the kernels which are parallelisable.
By default std::thread::hardware_concurrency() threads are used.
Note
CPPScheduler::set_num_threads() can be used to manually set the number of threads
For OpenCL kernels:
All the kernels are enqueued on the queue associated with CLScheduler.
The queue is then flushed.
Note
The function will not block until the kernels are executed. It is the user's responsibility to wait.
Will call prepare() on first run if hasn't been done
Implements IFunction.
Definition at line 68 of file NEElementwiseUnaryLayer.cpp.
References arm_compute::ACL_DST, arm_compute::ACL_SRC, ITensorPack::add_tensor(), and arm_compute::test::validation::pack.
 {
     ITensorPack pack;
     pack.add_tensor(TensorType::ACL_SRC, _impl->src);
     pack.add_tensor(TensorType::ACL_DST, _impl->dst);
     _impl->cpu_op->run(pack);
 }
validate()
Status validate (const ITensorInfo * input, const ITensorInfo * output) static
Static function to check if given info will lead to a valid configuration.
Parameters
[in] input Input tensor info. Data types supported: F16/F32, F16/F32/S32 for NEG/ABS operations.
[in] output Output tensor info. Data types supported: Same as input.
Returns
a status
Definition at line 62 of file NEElementwiseUnaryLayer.cpp.
References ClGemm::validate().
 {
     return OperatorType::validate(op, *input, *output);
 }
The documentation for this class was generated from the following files:
arm_compute/runtime/NEON/functions/NEElementwiseUnaryLayer.h
src/runtime/NEON/functions/NEElementwiseUnaryLayer.cpp