Compute Library: NEDetectionPostProcessLayer Class Reference
NEDetectionPostProcessLayer Class Reference
NE Function to generate the detection output based on center size encoded boxes, class prediction and anchors by doing non maximum suppression.
#include <NEDetectionPostProcessLayer.h>
Public Member Functions
NEDetectionPostProcessLayer (std::shared_ptr< IMemoryManager > memory_manager=nullptr)
Constructor.
NEDetectionPostProcessLayer (const NEDetectionPostProcessLayer &)=delete
Prevent instances of this class from being copied (As this class contains pointers)
NEDetectionPostProcessLayer & operator= (const NEDetectionPostProcessLayer &)=delete
Prevent instances of this class from being copied (As this class contains pointers)
~NEDetectionPostProcessLayer ()=default
Default destructor.
void configure (const ITensor *input_box_encoding, const ITensor *input_score, const ITensor *input_anchors, ITensor *output_boxes, ITensor *output_classes, ITensor *output_scores, ITensor *num_detection, DetectionPostProcessLayerInfo info=DetectionPostProcessLayerInfo())
Configure the detection output layer NE function.
void run () override
Run the kernels contained in the function.
Public Member Functions inherited from IFunction
virtual ~IFunction ()=default
Destructor.
virtual void prepare ()
Prepare the function for executing.
Static Public Member Functions
static Status validate (const ITensorInfo *input_box_encoding, const ITensorInfo *input_class_score, const ITensorInfo *input_anchors, ITensorInfo *output_boxes, ITensorInfo *output_classes, ITensorInfo *output_scores, ITensorInfo *num_detection, DetectionPostProcessLayerInfo info=DetectionPostProcessLayerInfo())
Static function to check if given info will lead to a valid configuration of NEDetectionPostProcessLayer.
Detailed Description
NE Function to generate the detection output based on center size encoded boxes, class prediction and anchors by doing non maximum suppression.
Note
Intended for use with MultiBox detection method.
Definition at line 47 of file NEDetectionPostProcessLayer.h.
Constructor & Destructor Documentation
NEDetectionPostProcessLayer() [1/2]
NEDetectionPostProcessLayer (std::shared_ptr< IMemoryManager > memory_manager = nullptr)
Constructor.
Definition at line 37 of file NEDetectionPostProcessLayer.cpp.
     : _memory_group(std::move(memory_manager)), _dequantize(), _detection_post_process(), _decoded_scores(), _run_dequantize(false)
 {
 }
NEDetectionPostProcessLayer() [2/2]
NEDetectionPostProcessLayer (const NEDetectionPostProcessLayer &) delete
Prevent instances of this class from being copied (As this class contains pointers)
~NEDetectionPostProcessLayer()
~NEDetectionPostProcessLayer () default
Default destructor.
Member Function Documentation
configure()
void configure (const ITensor * input_box_encoding, const ITensor * input_score, const ITensor * input_anchors, ITensor * output_boxes, ITensor * output_classes, ITensor * output_scores, ITensor * num_detection, DetectionPostProcessLayerInfo info = DetectionPostProcessLayerInfo())
Configure the detection output layer NE function.
Valid data layouts:
All
Valid data type configurations:
src0 - src2 dst0 - dst3
QASYMM8 F32
QASYMM8_SIGNED F32
F32 F32
Parameters
[in] input_box_encoding The bounding box input tensor. Data types supported: QASYMM8/QASYMM8_SIGNED/F32.
[in] input_score The class prediction input tensor. Data types supported: same as input_box_encoding.
[in] input_anchors The anchors input tensor. Data types supported: same as input_box_encoding.
[out] output_boxes The boxes output tensor. Data types supported: F32.
[out] output_classes The classes output tensor. Data types supported: Same as output_boxes.
[out] output_scores The scores output tensor. Data types supported: Same as output_boxes.
[out] num_detection The number of output detection. Data types supported: Same as output_boxes.
[in] info (Optional) DetectionPostProcessLayerInfo information.
Note
Output contains all the detections. Of those, only the ones selected by the valid region are valid.
Definition at line 42 of file NEDetectionPostProcessLayer.cpp.
References TensorAllocator::allocate(), Tensor::allocator(), ARM_COMPUTE_ERROR_ON_NULLPTR, ARM_COMPUTE_ERROR_THROW_ON, ARM_COMPUTE_LOG_PARAMS, CPPDetectionPostProcessLayer::configure(), NEDequantizationLayer::configure(), ITensorInfo::data_type(), DetectionPostProcessLayerInfo::detection_per_class(), ITensor::info(), arm_compute::test::validation::info, DetectionPostProcessLayerInfo::iou_threshold(), arm_compute::is_data_type_quantized(), MemoryGroup::manage(), DetectionPostProcessLayerInfo::max_classes_per_detection(), DetectionPostProcessLayerInfo::max_detections(), DetectionPostProcessLayerInfo::nms_score_threshold(), DetectionPostProcessLayerInfo::num_classes(), DetectionPostProcessLayerInfo::scale_value_h(), DetectionPostProcessLayerInfo::scale_value_w(), DetectionPostProcessLayerInfo::scale_value_x(), DetectionPostProcessLayerInfo::scale_value_y(), DetectionPostProcessLayerInfo::use_regular_nms(), and NEDetectionPostProcessLayer::validate().
 {
     ARM_COMPUTE_ERROR_ON_NULLPTR(input_box_encoding, input_scores, input_anchors, output_boxes, output_classes, output_scores);
     ARM_COMPUTE_ERROR_THROW_ON(NEDetectionPostProcessLayer::validate(input_box_encoding->info(), input_scores->info(), input_anchors->info(), output_boxes->info(), output_classes->info(),
                                                                      output_scores->info(),
                                                                      num_detection->info(), info));
     ARM_COMPUTE_LOG_PARAMS(input_box_encoding, input_scores, input_anchors, output_boxes, output_classes, output_scores, num_detection, info);
     const ITensor                *input_scores_to_use = input_scores;
     DetectionPostProcessLayerInfo info_to_use         = info;
     _run_dequantize                                   = is_data_type_quantized(input_box_encoding->info()->data_type());
     if(_run_dequantize)
     {
         _memory_group.manage(&_decoded_scores);
         _dequantize.configure(input_scores, &_decoded_scores);
         input_scores_to_use = &_decoded_scores;
         // Create a new info struct to avoid dequantizing in the CPP layer
         std::array<float, 4> scales_values{ info.scale_value_y(), info.scale_value_x(), info.scale_value_h(), info.scale_value_w() };
         DetectionPostProcessLayerInfo info_quantized(info.max_detections(), info.max_classes_per_detection(), info.nms_score_threshold(), info.iou_threshold(), info.num_classes(),
                                                      scales_values, info.use_regular_nms(), info.detection_per_class(), false);
         info_to_use = info_quantized;
     }
     _detection_post_process.configure(input_box_encoding, input_scores_to_use, input_anchors, output_boxes, output_classes, output_scores, num_detection, info_to_use);
     _decoded_scores.allocator()->allocate();
 }
operator=()
NEDetectionPostProcessLayer& operator= (const NEDetectionPostProcessLayer &) delete
Prevent instances of this class from being copied (As this class contains pointers)
run()
void run () override virtual
Run the kernels contained in the function.
For CPU kernels:
Multi-threading is used for the kernels which are parallelisable.
By default std::thread::hardware_concurrency() threads are used.
Note
CPPScheduler::set_num_threads() can be used to manually set the number of threads
For OpenCL kernels:
All the kernels are enqueued on the queue associated with CLScheduler.
The queue is then flushed.
Note
The function will not block until the kernels are executed. It is the user's responsibility to wait.
Will call prepare() on first run if hasn't been done
Implements IFunction.
Definition at line 88 of file NEDetectionPostProcessLayer.cpp.
References NEDequantizationLayer::run(), and CPPDetectionPostProcessLayer::run().
 {
     MemoryGroupResourceScope scope_mg(_memory_group);
     // Decode scores if necessary
     if(_run_dequantize)
     {
         _dequantize.run();
     }
     _detection_post_process.run();
 }
validate()
Status validate (const ITensorInfo * input_box_encoding, const ITensorInfo * input_class_score, const ITensorInfo * input_anchors, ITensorInfo * output_boxes, ITensorInfo * output_classes, ITensorInfo * output_scores, ITensorInfo * num_detection, DetectionPostProcessLayerInfo info = DetectionPostProcessLayerInfo()) static
Static function to check if given info will lead to a valid configuration of NEDetectionPostProcessLayer.
Parameters
[in] input_box_encoding The bounding box input tensor info. Data types supported: QASYMM8/QASYMM8_SIGNED/F32.
[in] input_class_score The class prediction input tensor info. Data types supported: same as input_box_encoding.
[in] input_anchors The anchors input tensor info. Data types supported: same as input_box_encoding.
[in] output_boxes The output tensor info. Data types supported: F32.
[in] output_classes The output tensor info. Data types supported: Same as output_boxes.
[in] output_scores The output tensor info. Data types supported: Same as output_boxes.
[in] num_detection The number of output detection tensor info. Data types supported: Same as output_boxes.
[in] info (Optional) DetectionPostProcessLayerInfo information.
Returns
a status
Definition at line 74 of file NEDetectionPostProcessLayer.cpp.
References ARM_COMPUTE_RETURN_ON_ERROR, ICloneable< T >::clone(), ITensorInfo::data_type(), arm_compute::F32, arm_compute::is_data_type_quantized(), NEDequantizationLayer::validate(), and CPPDetectionPostProcessLayer::validate().
Referenced by NEDetectionPostProcessLayer::configure(), and arm_compute::test::validation::DATA_TEST_CASE().
 {
     bool run_dequantize = is_data_type_quantized(input_box_encoding->data_type());
     if(run_dequantize)
     {
         TensorInfo decoded_classes_info = input_scores->clone()->set_is_resizable(true).set_data_type(DataType::F32);
         ARM_COMPUTE_RETURN_ON_ERROR(NEDequantizationLayer::validate(input_scores, &decoded_classes_info));
     }
     ARM_COMPUTE_RETURN_ON_ERROR(CPPDetectionPostProcessLayer::validate(input_box_encoding, input_scores, input_anchors, output_boxes, output_classes, output_scores, num_detection, info));
     return Status{};
 }
The documentation for this class was generated from the following files:
arm_compute/runtime/NEON/functions/NEDetectionPostProcessLayer.h
src/runtime/NEON/functions/NEDetectionPostProcessLayer.cpp