Compute Library: ClSynthetizeOperatorWithBorder< K > Class Template Reference
ClSynthetizeOperatorWithBorder< K > Class Template Reference
As above but this also setups a Zero border on the input tensor of the kernel's bordersize.
#include <Helper.h>
Public Member Functions
template<typename T , typename... Args>
void configure (T first, Args &&... args)
Configure the kernel.
void run (ITensorPack &tensors) override
Run the kernels contained in the function.
Public Member Functions inherited from ICLOperator
ICLOperator (IRuntimeContext *ctx=nullptr)
Constructor.
ICLOperator (const ICLOperator &)=delete
Prevent instances of this class from being copied (As this class contains pointers)
ICLOperator (ICLOperator &&)=default
Default move constructor.
ICLOperator & operator= (const ICLOperator &)=delete
Prevent instances of this class from being copied (As this class contains pointers)
ICLOperator & operator= (ICLOperator &&)=default
Default move assignment operator.
void prepare (ITensorPack &constants) override
Prepare the function for executing.
MemoryRequirements workspace () const override
Return the memory requirements required by the workspace.
Public Member Functions inherited from IOperator
virtual ~IOperator ()=default
Destructor.
Detailed Description
template<typename K>
class arm_compute::test::ClSynthetizeOperatorWithBorder< K >
As above but this also setups a Zero border on the input tensor of the kernel's bordersize.
Definition at line 224 of file Helper.h.
Member Function Documentation
configure()
void configure (T first, Args &&... args) inline
Configure the kernel.
Parameters
[in] first First configuration argument.
[in] args Rest of the configuration arguments.
Definition at line 233 of file Helper.h.
References GemmTuner::args, arm_compute::test::validation::b, arm_compute::CONSTANT, CLKernelLibrary::get(), and arm_compute::test::validation::k.
     {
         auto k = std::make_unique<K>();
         k->configure(CLKernelLibrary::get().get_compile_context(), first, std::forward<Args>(args)...);
         _kernel = std::move(k);
         auto b = std::make_unique<CLFillBorderKernel>();
         b->configure(CLKernelLibrary::get().get_compile_context(), first, BorderSize(_kernel->border_size()), BorderMode::CONSTANT, PixelValue());
         _border_handler = std::move(b);
     }
run()
void run (ITensorPack & tensors) inline override virtual
Run the kernels contained in the function.
Parameters
[in] tensors Vector that contains the tensors to operate on.
Reimplemented from ICLOperator.
Definition at line 244 of file Helper.h.
References CLScheduler::enqueue(), CLScheduler::enqueue_op(), and CLScheduler::get().
     {
         CLScheduler::get().enqueue(*_border_handler);
         CLScheduler::get().enqueue_op(*_kernel, tensors);
     }
The documentation for this class was generated from the following file:
tests/CL/Helper.h