Compute Library: NEBitwiseNotKernel Class Reference
NEBitwiseNotKernel Class Reference
Interface for the kernel to perform bitwise NOT operation.
#include <NEBitwiseNotKernel.h>
Public Member Functions
const char * name () const override
Name of the kernel.
NEBitwiseNotKernel ()
Default constructor.
NEBitwiseNotKernel (const NEBitwiseNotKernel &)=delete
Prevent instances of this class from being copied (As this class contains pointers)
NEBitwiseNotKernel & operator= (const NEBitwiseNotKernel &)=delete
Prevent instances of this class from being copied (As this class contains pointers)
NEBitwiseNotKernel (NEBitwiseNotKernel &&)=default
Allow instances of this class to be moved.
NEBitwiseNotKernel & operator= (NEBitwiseNotKernel &&)=default
Allow instances of this class to be moved.
~NEBitwiseNotKernel ()=default
Default destructor.
void configure (const ITensor *input, ITensor *output)
Initialise the kernel's input and output.
void run (const Window &window, const ThreadInfo &info) override
Execute the kernel on the passed window.
Public Member Functions inherited from ICPPKernel
virtual ~ICPPKernel ()=default
Default destructor.
virtual void run_nd (const Window &window, const ThreadInfo &info, const Window &thread_locator)
legacy compatibility layer for implemantions which do not support thread_locator In these cases we simply narrow the interface down the legacy version
virtual void run_op (ITensorPack &tensors, const Window &window, const ThreadInfo &info)
Execute the kernel on the passed window.
virtual size_t get_mws (const CPUInfo &platform, size_t thread_count) const
Return minimum workload size of the relevant kernel.
Public Member Functions inherited from IKernel
IKernel ()
Constructor.
virtual ~IKernel ()=default
Destructor.
virtual bool is_parallelisable () const
Indicates whether or not the kernel is parallelisable.
virtual BorderSize border_size () const
The size of the border for that kernel.
const Window & window () const
The maximum window the kernel can be executed on.
bool is_window_configured () const
Function to check if the embedded window of this kernel has been configured.
Additional Inherited Members
Static Public Attributes inherited from ICPPKernel
static constexpr size_t default_mws = 1
Detailed Description
Interface for the kernel to perform bitwise NOT operation.
Result is computed by:
\[ output(x,y) = \lnot input(x,y) \]
Definition at line 38 of file NEBitwiseNotKernel.h.
Constructor & Destructor Documentation
NEBitwiseNotKernel() [1/3]
NEBitwiseNotKernel ()
Default constructor.
Definition at line 53 of file NEBitwiseNotKernel.cpp.
Referenced by NEBitwiseNotKernel::name().
     : _input(nullptr), _output(nullptr)
 {
 }
NEBitwiseNotKernel() [2/3]
NEBitwiseNotKernel (const NEBitwiseNotKernel &) delete
Prevent instances of this class from being copied (As this class contains pointers)
NEBitwiseNotKernel() [3/3]
NEBitwiseNotKernel (NEBitwiseNotKernel &&) default
Allow instances of this class to be moved.
~NEBitwiseNotKernel()
~NEBitwiseNotKernel () default
Default destructor.
Referenced by NEBitwiseNotKernel::name().
Member Function Documentation
configure()
void configure (const ITensor * input, ITensor * output)
Initialise the kernel's input and output.
Parameters
[in] input An input tensor. Data type supported: U8.
[out] output The output tensor. Data type supported: U8.
Definition at line 58 of file NEBitwiseNotKernel.cpp.
References ARM_COMPUTE_ERROR_ON_DATA_TYPE_CHANNEL_NOT_IN, ARM_COMPUTE_ERROR_ON_MISMATCHING_DATA_TYPES, ARM_COMPUTE_ERROR_ON_MISMATCHING_SHAPES, ARM_COMPUTE_ERROR_ON_NULLPTR, arm_compute::calculate_max_window(), arm_compute::test::validation::configure(), ITensor::info(), arm_compute::test::validation::input, num_elems_processed_per_iteration, arm_compute::set_format_if_unknown(), arm_compute::set_shape_if_empty(), ITensorInfo::tensor_shape(), arm_compute::U8, and arm_compute::update_window_and_padding().
Referenced by NEBitwiseNotKernel::name().
 {
     ARM_COMPUTE_ERROR_ON_NULLPTR(input, output);
     set_shape_if_empty(*output->info(), input->info()->tensor_shape());
     set_format_if_unknown(*output->info(), Format::U8);
     set_format_if_unknown(*input->info(), Format::U8);
     ARM_COMPUTE_ERROR_ON_MISMATCHING_SHAPES(input, output);
     ARM_COMPUTE_ERROR_ON_DATA_TYPE_CHANNEL_NOT_IN(input, 1, DataType::U8);
     ARM_COMPUTE_ERROR_ON_DATA_TYPE_CHANNEL_NOT_IN(output, 1, DataType::U8);
     ARM_COMPUTE_ERROR_ON_MISMATCHING_DATA_TYPES(input, output);
     _input  = input;
     _output = output;
     constexpr unsigned int num_elems_processed_per_iteration = 16;
     // Configure kernel window
     Window                 win = calculate_max_window(*input->info(), Steps(num_elems_processed_per_iteration));
     AccessWindowHorizontal output_access(output->info(), 0, num_elems_processed_per_iteration);
     update_window_and_padding(win, AccessWindowHorizontal(input->info(), 0, num_elems_processed_per_iteration), output_access);
     INEKernel::configure(win);
 }
name()
const char* name () const inline override virtual
Name of the kernel.
Returns
Kernel name
Implements ICPPKernel.
Definition at line 41 of file NEBitwiseNotKernel.h.
References NEBitwiseNotKernel::configure(), arm_compute::test::validation::info, arm_compute::test::validation::input, NEBitwiseNotKernel::NEBitwiseNotKernel(), NEBitwiseNotKernel::operator=(), NEBitwiseNotKernel::run(), IKernel::window(), and NEBitwiseNotKernel::~NEBitwiseNotKernel().
     {
         return "NEBitwiseNotKernel";
     }
operator=() [1/2]
NEBitwiseNotKernel& operator= (const NEBitwiseNotKernel &) delete
Prevent instances of this class from being copied (As this class contains pointers)
Referenced by NEBitwiseNotKernel::name().
operator=() [2/2]
NEBitwiseNotKernel& operator= (NEBitwiseNotKernel &&) default
Allow instances of this class to be moved.
run()
void run (const Window & window, const ThreadInfo & info) override virtual
Execute the kernel on the passed window.
Warning
If is_parallelisable() returns false then the passed window must be equal to window()
Note
The window has to be a region within the window returned by the window() method
The width of the window has to be a multiple of num_elems_processed_per_iteration().
Parameters
[in] window Region on which to execute the kernel. (Must be a region of the window returned by window())
[in] info Info about executing thread and CPU.
Reimplemented from ICPPKernel.
Definition at line 85 of file NEBitwiseNotKernel.cpp.
References ARM_COMPUTE_ERROR_ON_INVALID_SUBWINDOW, ARM_COMPUTE_ERROR_ON_UNCONFIGURED_KERNEL, ARM_COMPUTE_UNUSED, arm_compute::execute_window_loop(), arm_compute::test::validation::input, Iterator::ptr(), and IKernel::window().
Referenced by NEBitwiseNotKernel::name().
 {
     ARM_COMPUTE_UNUSED(info);
     ARM_COMPUTE_ERROR_ON_UNCONFIGURED_KERNEL(this);
     ARM_COMPUTE_ERROR_ON_INVALID_SUBWINDOW(INEKernel::window(), window);
     Iterator input(_input, window);
     Iterator output(_output, window);
     execute_window_loop(window, [&](const Coordinates &)
     {
         bitwise_not_U8_U8(input.ptr(), output.ptr());
     },
     input, output);
 }
The documentation for this class was generated from the following files:
src/core/NEON/kernels/NEBitwiseNotKernel.h
src/core/NEON/kernels/NEBitwiseNotKernel.cpp