Compute Library: CLScheduler Class Reference
CLScheduler Class Reference final
Provides global access to a CL context and command queue.
#include <CLScheduler.h>
Public Member Functions
CLScheduler ()
Constructor.
CLScheduler (const CLScheduler &)=delete
Prevent instances of this class from being copied (As this class contains pointers)
CLScheduler & operator= (const CLScheduler &)=delete
Prevent instances of this class from being copied (As this class contains pointers)
~CLScheduler ()=default
Default destructor.
void default_init (ICLTuner *cl_tuner=nullptr, CLGEMMHeuristicsHandle *gemm_h=nullptr, CLBackendType cl_backend_type=CLBackendType::Native)
Initialises the context and command queue used by the scheduler to default values and sets a default device and kernel path for the CLKernelLibrary.
void default_init_with_context (cl::Device &device, cl::Context &ctx, ICLTuner *cl_tuner=nullptr, CLGEMMHeuristicsHandle *gemm_h=nullptr)
Initialises the scheduler with context and device provided by the user.
void default_reinit (ICLTuner *cl_tuner=nullptr, CLGEMMHeuristicsHandle *gemm_h=nullptr, CLBackendType cl_backend_type=CLBackendType::Native)
Re-initializes the context and command queue used by the scheduler to default values and sets a default device and kernel path for the CLKernelLibrary.
void enqueue (ICLKernel &kernel, bool flush=true)
Schedule the execution of the passed kernel if possible.
void enqueue_op (ICLKernel &kernel, ITensorPack &tensors, bool flush=true)
Schedule the execution of the passed kernel if possible.
void enqueue_op (ICLKernel &kernel, ITensorPack &tensors, const experimental::dynamic_fusion::ClExecutionDescriptor &exec_desc, bool flush=true)
Schedule the execution of the passed kernel if possible.
void init (cl::Context context, cl::CommandQueue queue, const cl::Device &device, ICLTuner *cl_tuner=nullptr, CLGEMMHeuristicsHandle *gemm_h=nullptr, CLBackendType cl_backend_type=CLBackendType::Native)
Initialises the context and command queue to be used by the scheduler.
cl::Context & context ()
Accessor for the associated CL context.
cl::CommandQueue & queue ()
Accessor for the associated CL command queue.
GPUTarget target () const
Get the target GPU.
CLGEMMHeuristicsHandle * gemm_heuristics () const
Accessor for the associated CLGEMMHeuristicsHandle.
void set_context (cl::Context context)
Accessor to set the CL context to be used by the scheduler.
void set_queue (cl::CommandQueue queue)
Accessor to set the CL command queue to be used by the scheduler.
void set_target (GPUTarget target)
Accessor to set target GPU to be used by the scheduler.
void set_tuner (ICLTuner *tuner)
Accessor to set the CL tuner to be used by the scheduler.
void sync ()
Blocks until all commands in the associated command queue have finished.
cl::Event enqueue_sync_event ()
Enqueues a marker into the associated command queue and return the event.
void tune_kernel_static (ICLKernel &kernel)
Tunes OpenCL kernel.
void enable_job_chaining (int job_chaining_size)
Enable job chaining.
bool is_initialised () const
Static Public Member Functions
static CLScheduler & get ()
Access the scheduler singleton.
Detailed Description
Provides global access to a CL context and command queue.
Definition at line 56 of file CLScheduler.h.
Constructor & Destructor Documentation
CLScheduler() [1/2]
CLScheduler ()
Constructor.
Definition at line 101 of file CLScheduler.cpp.
     : _context(), _queue(), _target(GPUTarget::MIDGARD), _is_initialised(false), _cl_tuner(nullptr), _gemm_heuristics(nullptr), _backend_type(CLBackendType::Native), _job_chaining_enabled(false),
       _job_chaining_size(), _job_chaining_count(0)
 {
 }
CLScheduler() [2/2]
CLScheduler (const CLScheduler &) delete
Prevent instances of this class from being copied (As this class contains pointers)
~CLScheduler()
~CLScheduler () default
Default destructor.
Member Function Documentation
context()
cl::Context & context ()
Accessor for the associated CL context.
Returns
A CL context.
Definition at line 36 of file CLScheduler.cpp.
References ARM_COMPUTE_ERROR_ON, CLKernelLibrary::context(), and CLKernelLibrary::get().
Referenced by CLTensorAllocator::import_memory(), arm_compute::restore_program_cache_from_file(), and Framework::run().
 {
     ARM_COMPUTE_ERROR_ON(!_is_initialised);
     _context = CLKernelLibrary::get().context();
     return _context;
 }
default_init()
void default_init (ICLTuner * cl_tuner = nullptr, CLGEMMHeuristicsHandle * gemm_h = nullptr, CLBackendType cl_backend_type = CLBackendType::Native)
Initialises the context and command queue used by the scheduler to default values and sets a default device and kernel path for the CLKernelLibrary.
Parameters
[in] cl_tuner (Optional) Pointer to ICLTuner (default=nullptr)
[in] gemm_h (Optional) Pointer to CLGEMMHeuristicsHandle (default = nullptr)
[in] cl_backend_type (Optional) Type of backend to use (default = CLBackendType::Native)
Examples:
dynamic_fusion/cl_fused_conv2d_elementwise_add.cpp.
Definition at line 126 of file CLScheduler.cpp.
References ARM_COMPUTE_ERROR_ON_MSG, arm_compute::create_opencl_context_and_device(), CLKernelLibrary::get(), CLKernelLibrary::init(), CLScheduler::init(), and CLScheduler::queue().
Referenced by CLScheduler::default_reinit(), CLDeviceBackend::initialize_backend(), and arm_compute::restore_program_cache_from_file().
 {
     if(!_is_initialised)
     {
         cl::Context ctx;
         cl::Device  dev;
         cl_int      err;
         std::tie(ctx, dev, err) = create_opencl_context_and_device(cl_backend_type);
         ARM_COMPUTE_ERROR_ON_MSG(err != CL_SUCCESS, "Failed to create OpenCL context");
         cl::CommandQueue queue = cl::CommandQueue(ctx, dev);
         CLKernelLibrary::get().init("./cl_kernels/", ctx, dev);
         init(ctx, queue, dev, cl_tuner, gemm_h);
     }
     // Set CL tuner and GEMM heuristics
     _cl_tuner        = cl_tuner;
     _gemm_heuristics = gemm_h;
 }
default_init_with_context()
void default_init_with_context (cl::Device & device, cl::Context & ctx, ICLTuner * cl_tuner = nullptr, CLGEMMHeuristicsHandle * gemm_h = nullptr)
Initialises the scheduler with context and device provided by the user.
Parameters
[in] device OpenCL device to be used
[in] ctx OpenCL ctx to be used
[in] cl_tuner (Optional) Pointer to ICLTuner (default=nullptr)
[in] gemm_h (Optional) Pointer to CLGEMMHeuristicsHandle (default = nullptr)
Definition at line 114 of file CLScheduler.cpp.
References CLKernelLibrary::get(), CLKernelLibrary::init(), CLScheduler::init(), and CLScheduler::queue().
Referenced by main(), and arm_compute::utils::run_example().
 {
     if(!_is_initialised)
     {
         const std::string cl_kernels_folder("./cl_kernels/");
         cl::CommandQueue  queue = cl::CommandQueue(ctx, device);
         CLKernelLibrary::get().init(cl_kernels_folder, ctx, device);
         init(ctx, queue, device, cl_tuner, gemm_h);
         _cl_tuner = cl_tuner;
     }
 }
default_reinit()
void default_reinit (ICLTuner * cl_tuner = nullptr, CLGEMMHeuristicsHandle * gemm_h = nullptr, CLBackendType cl_backend_type = CLBackendType::Native)
Re-initializes the context and command queue used by the scheduler to default values and sets a default device and kernel path for the CLKernelLibrary.
Parameters
[in] cl_tuner (Optional) Pointer to ICLTuner (default=nullptr)
[in] gemm_h (Optional) Pointer to CLGEMMHeuristicsHandle (default = nullptr)
[in] cl_backend_type (Optional) Type of backend to use (default = CLBackendType::Native)
Definition at line 145 of file CLScheduler.cpp.
References CLScheduler::default_init().
Referenced by arm_compute::test::validation::TEST_CASE().
 {
     _is_initialised = false;
     default_init(cl_tuner, gemm_h, cl_backend_type);
 }
enable_job_chaining()
void enable_job_chaining (int job_chaining_size)
Enable job chaining.
The command queue will only be flushed when job_chaining_size kernels have been enqueued.
Parameters
[in] job_chaining_size Kernels to enqueue before flushing
Definition at line 257 of file CLScheduler.cpp.
 {
     _job_chaining_enabled = true;
     _job_chaining_size    = job_chaining_size;
 }
enqueue()
void enqueue (ICLKernel & kernel, bool flush = true)
Schedule the execution of the passed kernel if possible.
Parameters
[in] kernel Kernel to execute.
[in] flush (Optional) Specifies if the command queue will be flushed after running the kernel. This will be ignored if job chaining is enabled.
Definition at line 237 of file CLScheduler.cpp.
References arm_compute::test::validation::pack.
Referenced by CLSpaceToDepthLayer::run(), CLDeconvolutionLayerUpsample::run(), CLFFT1D::run(), CLStackLayer::run(), CLL2NormalizeLayer::run(), CLNormalizationLayer::run(), CLArgMinMaxLayer::run(), CLPadLayer::run(), CLReductionOperation::run(), CLDepthwiseConvolutionLayer::run(), CLMaxUnpoolingLayer::run(), CLBatchToSpaceLayer::run(), CLFuseBatchNormalization::run(), CLBatchNormalizationLayer::run(), CLSpaceToBatchLayer::run(), CLGEMMDeconvolutionLayer::run(), CLGenerateProposalsLayer::run(), CLSynthetizeFunctionInitOutputWithZeroAndWithZeroConstantBorder< K, bordersize >::run(), CLQLSTMLayer::run(), ClSynthetizeOperatorWithBorder< K >::run(), and arm_compute::schedule_kernel_on_ctx().
 {
     ITensorPack pack;
     enqueue_common(kernel, pack, flush);
 }
enqueue_op() [1/2]
void enqueue_op (ICLKernel & kernel, ITensorPack & tensors, bool flush = true)
Schedule the execution of the passed kernel if possible.
Parameters
[in] kernel Kernel to execute.
[in] tensors Vector containing the tensors to operate on.
[in] flush (Optional) Specifies if the command queue will be flushed after running the kernel. This will be ignored if job chaining is enabled.
Definition at line 243 of file CLScheduler.cpp.
Referenced by ClGemm::prepare(), ClGemmLowpMatrixMultiplyCore::prepare(), ClWinogradConv2d::prepare(), ClGemmConv2d::prepare(), ClCompositeOperator::prepare(), CLQLSTMLayer::prepare(), ClDequantize::run(), ClQuantize::run(), ICLOperator::run(), ClScale::run(), ClSoftmax::run(), ClConcatenate::run(), ClDirectConv2d::run(), ClDirectConv3d::run(), ClGemmLowpOutputStage::run(), ClGemm::run(), ClGemmLowpMatrixMultiplyCore::run(), CLSynthetizeOperatorInitOutputWithZeroAndWithZeroConstantBorder< K, bordersize >::run(), ClWinogradConv2d::run(), ClGemmConv2d::run(), ClCompositeOperator::run(), CLLSTMLayer::run(), and ClSynthetizeOperatorWithBorder< K >::run().
 {
     enqueue_common(kernel, tensors, flush);
 }
enqueue_op() [2/2]
void enqueue_op (ICLKernel & kernel, ITensorPack & tensors, const experimental::dynamic_fusion::ClExecutionDescriptor & exec_desc, bool flush = true)
Schedule the execution of the passed kernel if possible.
Parameters
[in] kernel Kernel to execute.
[in] tensors Map containing the tensors to operate on.
[in] exec_desc Execution descriptor
[in] flush (Optional) Specifies if the command queue will be flushed after running the kernel. This will be ignored if job chaining is enabled.
Definition at line 250 of file CLScheduler.cpp.
 {
     enqueue_common(kernel, tensors, exec_desc, flush);
 }
enqueue_sync_event()
cl::Event enqueue_sync_event ()
Enqueues a marker into the associated command queue and return the event.
Returns
An event that can be waited on to block the executing thread.
Definition at line 79 of file CLScheduler.cpp.
 {
     cl::Event event;
     _queue.enqueueMarker(&event);
     return event;
 }
gemm_heuristics()
CLGEMMHeuristicsHandle * gemm_heuristics () const
Accessor for the associated CLGEMMHeuristicsHandle.
Returns
Pointer to CLGEMMHeuristicsHandle
Definition at line 54 of file CLScheduler.cpp.
Referenced by arm_compute::cl_gemm::auto_heuristics::select_mlgo_gemm_config_native(), arm_compute::cl_gemm::auto_heuristics::select_mlgo_gemm_config_reshaped(), arm_compute::cl_gemm::auto_heuristics::select_mlgo_gemm_config_reshaped_only_rhs(), arm_compute::cl_gemm::auto_heuristics::select_mlgo_gemm_kernel(), and CLDeviceBackend::setup_backend_context().
 {
     return _gemm_heuristics;
 }
get()
CLScheduler & get () static
Access the scheduler singleton.
This method has been deprecated and will be removed in future releases
Returns
The scheduler
Examples:
dynamic_fusion/cl_fused_conv2d_elementwise_add.cpp.
Definition at line 107 of file CLScheduler.cpp.
References arm_compute::opencl_is_available().
Referenced by CLTuner::add_tuning_params(), CLBufferAllocator::allocate(), ClDirectConvolutionKernelComponent::allocate_shared_vars(), ClQueue::cl_queue(), CLBufferMemoryRegion::CLBufferMemoryRegion(), ClScale::configure(), ClPool2d::configure(), ClPool3d::configure(), ClSoftmax::configure(), ClDirectConv2d::configure(), CLPriorBoxLayer::configure(), CLRange::configure(), CLFFT1D::configure(), ClGemm::configure(), CLDepthwiseConvolutionLayer::configure(), ClGemmLowpMatrixMultiplyCore::configure(), ClWinogradConv2d::configure(), CLSynthetizeOperatorInitOutputWithZeroAndWithZeroConstantBorder< K, bordersize >::configure(), CLCropResize::configure(), ClGemmConv2d::configure(), ClConv2d::configure(), CLConvolutionLayer::configure(), CLSynthetizeFunctionInitOutputWithZeroAndWithZeroConstantBorder< K, bordersize >::configure(), arm_compute::test::validation::DATA_TEST_CASE(), ClQueue::finish(), ClDirectConvolutionKernelComponent::generate_build_options(), CLTensorAllocator::import_memory(), CLDeviceBackend::initialize_backend(), main(), CLArray< cl_int >::map(), CLSubTensor::map(), CLTensor::map(), OpenCLClock< output_timestamps >::OpenCLClock(), ClGemm::prepare(), ClGemmLowpMatrixMultiplyCore::prepare(), ClWinogradConv2d::prepare(), ClGemmConv2d::prepare(), CLFFTConvolutionLayer::prepare(), ClCompositeOperator::prepare(), CLQLSTMLayer::prepare(), arm_compute::restore_program_cache_from_file(), ClDequantize::run(), ClQuantize::run(), CLSplit::run(), ICLOperator::run(), ClScale::run(), ClSoftmax::run(), ClConcatenate::run(), ClDirectConv2d::run(), ClDirectConv3d::run(), ClGemmLowpOutputStage::run(), CLSpaceToDepthLayer::run(), CLDeconvolutionLayerUpsample::run(), CLFFT1D::run(), ClGemm::run(), CLStackLayer::run(), ClGemmLowpMatrixMultiplyCore::run(), CLL2NormalizeLayer::run(), CLNormalizationLayer::run(), CLPadLayer::run(), CLArgMinMaxLayer::run(), CLReductionOperation::run(), ClWinogradConv2d::run(), CLSynthetizeOperatorInitOutputWithZeroAndWithZeroConstantBorder< K, bordersize >::run(), CLDepthwiseConvolutionLayer::run(), CLMaxUnpoolingLayer::run(), ClGemmConv2d::run(), CLBatchToSpaceLayer::run(), CLFuseBatchNormalization::run(), CLCropResize::run(), CLBatchNormalizationLayer::run(), CLSpaceToBatchLayer::run(), CLGEMMDeconvolutionLayer::run(), CLGenerateProposalsLayer::run(), ClCompositeOperator::run(), CLSynthetizeFunctionInitOutputWithZeroAndWithZeroConstantBorder< K, bordersize >::run(), CLLSTMLayer::run(), CLQLSTMLayer::run(), ClSynthetizeOperatorWithBorder< K >::run(), Framework::run(), arm_compute::utils::run_example(), arm_compute::save_program_cache_to_file(), arm_compute::schedule_kernel_on_ctx(), ClQueue::scheduler(), arm_compute::cl_gemm::auto_heuristics::select_mlgo_gemm_config_native(), arm_compute::cl_gemm::auto_heuristics::select_mlgo_gemm_config_reshaped(), arm_compute::cl_gemm::auto_heuristics::select_mlgo_gemm_config_reshaped_only_rhs(), arm_compute::cl_gemm::auto_heuristics::select_mlgo_gemm_kernel(), ClContext::set_cl_ctx(), ClQueue::set_cl_queue(), CLTensorAllocator::set_global_allocator(), CLDeviceBackend::setup_backend_context(), CLDeviceBackend::sync(), arm_compute::test::sync_if_necessary(), arm_compute::test::validation::TEST_CASE(), OpenCLClock< output_timestamps >::test_measurements(), Conv2dContent::translate(), CLArray< cl_int >::unmap(), CLSubTensor::unmap(), CLTensor::unmap(), CLBufferMemoryRegion::unmap(), ClGemm::validate(), ClGemmLowpMatrixMultiplyCore::validate(), CLDepthwiseConvolutionLayer::validate(), ClConv2d::validate(), CLGenerateProposalsLayer::validate(), and CLConvolutionLayer::validate().
 {
     std::call_once(_initialize_symbols, opencl_is_available);
     static CLScheduler scheduler;
     return scheduler;
 }
init()
void init (cl::Context context, cl::CommandQueue queue, const cl::Device & device, ICLTuner * cl_tuner = nullptr, CLGEMMHeuristicsHandle * gemm_h = nullptr, CLBackendType cl_backend_type = CLBackendType::Native)
Initialises the context and command queue to be used by the scheduler.
Parameters
[in] context A CL context.
[in] queue A CL command queue.
[in] device A CL device.
[in] cl_tuner (Optional) Pointer to OpenCL tuner (default=nullptr) Note: It is caller's responsibility to release the allocated memory for CLTuner
[in] gemm_h (Optional) Pointer to CLGEMMHeuristicsHandle (default = nullptr)
[in] cl_backend_type (Optional) Type of backend to use (default = CLBackendType::Native)
Definition at line 158 of file CLScheduler.cpp.
References ARM_COMPUTE_ERROR_ON_MSG, ITensorPack::empty(), arm_compute::get_target_from_device(), ICLKernel::run(), ICLKernel::run_composite_op(), ICLKernel::run_op(), CLScheduler::set_context(), ICLTuner::tune_kernel_dynamic(), and IKernel::window().
Referenced by CLScheduler::default_init(), and CLScheduler::default_init_with_context().
 {
     set_context(std::move(context));
     _queue           = std::move(queue);
     _target          = get_target_from_device(device);
     _is_initialised  = true;
     _cl_tuner        = cl_tuner;
     _gemm_heuristics = gemm_h;
     _backend_type    = cl_backend_type;
 }
is_initialised()
bool is_initialised () const
Definition at line 94 of file CLScheduler.cpp.
Referenced by arm_compute::restore_program_cache_from_file().
 {
     return _is_initialised;
 }
operator=()
CLScheduler& operator= (const CLScheduler &) delete
Prevent instances of this class from being copied (As this class contains pointers)
queue()
cl::CommandQueue & queue ()
Accessor for the associated CL command queue.
Returns
A CL command queue.
Definition at line 43 of file CLScheduler.cpp.
References ARM_COMPUTE_ERROR_ON.
Referenced by CLTuner::add_tuning_params(), ClQueue::cl_queue(), arm_compute::test::validation::DATA_TEST_CASE(), CLScheduler::default_init(), CLScheduler::default_init_with_context(), ClQueue::finish(), CLTensor::map(), OpenCLClock< output_timestamps >::OpenCLClock(), ClGemmLowpMatrixMultiplyCore::prepare(), ClWinogradConv2d::prepare(), CLFFTConvolutionLayer::prepare(), CLQLSTMLayer::prepare(), CLSplit::run(), Framework::run(), CLTensorAllocator::set_global_allocator(), arm_compute::test::validation::TEST_CASE(), OpenCLClock< output_timestamps >::test_measurements(), and CLTensor::unmap().
 {
     ARM_COMPUTE_ERROR_ON(!_is_initialised);
     return _queue;
 }
set_context()
void set_context (cl::Context context)
Accessor to set the CL context to be used by the scheduler.
Parameters
[in] context A CL context.
Definition at line 152 of file CLScheduler.cpp.
References CLKernelLibrary::get(), and CLKernelLibrary::set_context().
Referenced by CLScheduler::init(), Framework::run(), and ClContext::set_cl_ctx().
 {
     _context = std::move(context);
     CLKernelLibrary::get().set_context(_context);
 }
set_queue()
void set_queue (cl::CommandQueue queue)
Accessor to set the CL command queue to be used by the scheduler.
Parameters
[in] queue A CL command queue.
Definition at line 59 of file CLScheduler.cpp.
Referenced by OpenCLClock< output_timestamps >::OpenCLClock(), Framework::run(), and ClQueue::set_cl_queue().
 {
     _queue = std::move(queue);
 }
set_target()
void set_target (GPUTarget target)
Accessor to set target GPU to be used by the scheduler.
Parameters
[in] target The target GPU.
Definition at line 64 of file CLScheduler.cpp.
References CLScheduler::target().
 {
     _target = target;
 }
set_tuner()
void set_tuner (ICLTuner * tuner)
Accessor to set the CL tuner to be used by the scheduler.
Parameters
[in] tuner A CL tuner
Definition at line 69 of file CLScheduler.cpp.
 {
     _cl_tuner = tuner;
 }
sync()
void sync ()
Blocks until all commands in the associated command queue have finished.
Examples:
dynamic_fusion/cl_fused_conv2d_elementwise_add.cpp.
Definition at line 74 of file CLScheduler.cpp.
Referenced by CLCropResize::configure(), main(), CLCropResize::run(), CLDeviceBackend::sync(), arm_compute::test::sync_if_necessary(), and arm_compute::test::validation::TEST_CASE().
 {
     _queue.finish();
 }
target()
GPUTarget target () const
Get the target GPU.
Returns
The target GPU.
Examples:
dynamic_fusion/cl_fused_conv2d_elementwise_add.cpp.
Definition at line 49 of file CLScheduler.cpp.
Referenced by ClDirectConvolutionKernelComponent::allocate_shared_vars(), ClGemm::configure(), CLDepthwiseConvolutionLayer::configure(), ClGemmLowpMatrixMultiplyCore::configure(), CLConvolutionLayer::configure(), ClDirectConvolutionKernelComponent::generate_build_options(), CLScheduler::set_target(), arm_compute::test::validation::TEST_CASE(), Conv2dContent::translate(), ClGemm::validate(), ClGemmLowpMatrixMultiplyCore::validate(), CLDepthwiseConvolutionLayer::validate(), ClConv2d::validate(), and CLConvolutionLayer::validate().
 {
     return _target;
 }
tune_kernel_static()
void tune_kernel_static (ICLKernel & kernel)
Tunes OpenCL kernel.
Parameters
[in] kernel Kernel to tune
Definition at line 86 of file CLScheduler.cpp.
References ICLTuner::tune_kernel_static().
Referenced by ClScale::configure(), ClPool2d::configure(), ClPool3d::configure(), ClDirectConv2d::configure(), CLRange::configure(), and ClGemmConv2d::configure().
 {
     if(_cl_tuner != nullptr)
     {
         _cl_tuner->tune_kernel_static(kernel);
     }
 }
The documentation for this class was generated from the following files:
arm_compute/runtime/CL/CLScheduler.h
src/runtime/CL/CLScheduler.cpp