Compute Library: Tensor Class Reference
Tensor Class Reference
Tensor class.
#include <Acl.hpp>
Public Member Functions
Tensor (Context &ctx, const TensorDescriptor &desc, StatusCode *status=nullptr)
Constructor.
Tensor (Context &ctx, const TensorDescriptor &desc, bool allocate, StatusCode *status)
Constructor.
void * map ()
Maps the backing memory of a given tensor that can be used by the host to access any contents.
StatusCode unmap (void *handle)
Unmaps tensor's memory.
StatusCode import (void *handle, ImportType type)
Import external memory to a given tensor object.
uint64_t get_size ()
Get the size of the tensor in byte.
TensorDescriptor get_descriptor ()
Get the descriptor of this tensor.
Public Member Functions inherited from ObjectBase< AclTensor_ >
~ObjectBase ()=default
Destructor.
ObjectBase (const ObjectBase< AclTensor_ > &)=default
Copy constructor.
ObjectBase (ObjectBase< AclTensor_ > &&)=default
Move Constructor.
ObjectBase< AclTensor_ > & operator= (const ObjectBase< AclTensor_ > &)=default
Copy assignment operator.
ObjectBase< AclTensor_ > & operator= (ObjectBase< AclTensor_ > &&)=default
Move assignment operator.
void reset (AclTensor_ *val)
Reset object value.
const AclTensor_ * get () const
Access uderlying object.
AclTensor_ * get ()
Access uderlying object.
Detailed Description
Tensor class.
Tensor is an mathematical construct that can represent an N-Dimensional space.
Note
Maximum dimensionality support is 6 internally at the moment
Definition at line 584 of file Acl.hpp.
Constructor & Destructor Documentation
Tensor() [1/2]
Tensor (Context & ctx, const TensorDescriptor & desc, StatusCode * status = nullptr) inline
Constructor.
Note
Tensor memory is allocated
Parameters
[in] ctx Context from where the tensor will be created from
[in] desc Tensor descriptor to be used
[out] status Status information if requested
Definition at line 595 of file Acl.hpp.
         : Tensor(ctx, desc, true, status)
     {
     }
Tensor() [2/2]
Tensor (Context & ctx, const TensorDescriptor & desc, bool allocate, StatusCode * status) inline
Constructor.
Parameters
[in] ctx Context from where the tensor will be created from
[in] desc Tensor descriptor to be used
[in] allocate Flag to indicate if the tensor needs to be allocated
[out] status Status information if requested
Definition at line 606 of file Acl.hpp.
References AclCreateTensor(), ObjectBase< T >::get(), and TensorDescriptor::get().
     {
         AclTensor  tensor;
         const auto st = detail::as_enum<StatusCode>(AclCreateTensor(&tensor, ctx.get(), desc.get(), allocate));
         reset(tensor);
         report_status(st, "[Compute Library] Failed to create tensor!");
         if(status)
         {
             *status = st;
         }
     }
Member Function Documentation
get_descriptor()
TensorDescriptor get_descriptor () inline
Get the descriptor of this tensor.
Returns
The descriptor describing the characteristics of this tensor
Definition at line 670 of file Acl.hpp.
References AclGetTensorDescriptor().
     {
         AclTensorDescriptor desc;
         const auto          st = detail::as_enum<StatusCode>(AclGetTensorDescriptor(_object.get(), &desc));
         report_status(st, "[Compute Library] Failed to get the descriptor of the tensor");
         return TensorDescriptor(desc);
     }
get_size()
uint64_t get_size () inline
Get the size of the tensor in byte.
Note
The size isn't based on allocated memory, but based on information in its descriptor (dimensions, data type, etc.).
Returns
The size of the tensor in byte
Definition at line 659 of file Acl.hpp.
References AclGetTensorSize().
     {
         uint64_t   size{ 0 };
         const auto st = detail::as_enum<StatusCode>(AclGetTensorSize(_object.get(), &size));
         report_status(st, "[Compute Library] Failed to get the size of the tensor");
         return size;
     }
import()
StatusCode import (void * handle, ImportType type) inline
Import external memory to a given tensor object.
Parameters
[in] handle External memory handle
[in] type Type of memory to be imported
Returns
Status code
Definition at line 647 of file Acl.hpp.
References AclTensorImport(), and type.
     {
         const auto st = detail::as_enum<StatusCode>(AclTensorImport(_object.get(), handle, detail::as_cenum<AclImportMemoryType>(type)));
         report_status(st, "[Compute Library] Failed to import external memory to tensor!");
         return st;
     }
map()
void* map () inline
Maps the backing memory of a given tensor that can be used by the host to access any contents.
Returns
A valid non-zero pointer in case of success else nullptr
Definition at line 621 of file Acl.hpp.
References AclMapTensor().
     {
         void      *handle = nullptr;
         const auto st     = detail::as_enum<StatusCode>(AclMapTensor(_object.get(), &handle));
         report_status(st, "[Compute Library] Failed to map the tensor and extract the tensor's backing memory!");
         return handle;
     }
unmap()
StatusCode unmap (void * handle) inline
Unmaps tensor's memory.
Parameters
[in] handle Handle to unmap
Returns
Status code
Definition at line 634 of file Acl.hpp.
References AclUnmapTensor().
     {
         const auto st = detail::as_enum<StatusCode>(AclUnmapTensor(_object.get(), handle));
         report_status(st, "[Compute Library] Failed to unmap the tensor!");
         return st;
     }
The documentation for this class was generated from the following file:
arm_compute/Acl.hpp