Compute Library: arm_compute::quantization Namespace Reference
arm_compute::quantization Namespace Reference
Functions
Status calculate_quantized_multiplier (float multiplier, int32_t *quant_multiplier, int32_t *shift, bool ignore_epsilon=false)
Calculate quantized representation of multiplier.
Status calculate_quantized_multiplier_less_than_one (float multiplier, int32_t *quant_multiplier, int32_t *right_shift, bool ignore_epsilon=false)
Calculate quantized representation of multiplier with value less than one.
Status calculate_quantized_multiplier_greater_than_one (float multiplier, int32_t *quantized_multiplier, int32_t *left_shift)
Calculate quantized representation of multiplier having value greater than one.
Status calculate_quantized_multipliers (const QuantizationInfo &iq_info, const QuantizationInfo &wq_info, const QuantizationInfo &oq_info, GEMMLowpOutputStageInfo &stage_info)
Calculate quantized representation of per-channel multipliers.
std::pair< int, int > get_min_max_values_from_quantized_data_type (DataType data_type)
Get minimum and maximum values for the input quantized data type.
void compute_quantized_multipliers_and_shifts (const ITensorInfo *input, const ITensorInfo *weights, const ITensorInfo *output, int32_t *output_multipliers_ptr, int32_t *output_shifts_ptr)
Compute quantized per-channel multipliers and shifts.
int32_t rounding_divide_by_pow2 (int32_t x, int exponent)
Round to the nearest division by a power-of-two using exponent, copied from NEMath.
int32_t saturating_rounding_doubling_highmul (int32_t a, int32_t b)
Compute multiplication of two integers.
int32_t multiply_by_quantized_multiplier (int32_t input, int32_t qmul, int32_t shift)
Compute the value multiplied by given quantized multiplier and shift.
int32_t saturating_rounding_multiply_by_pow2 (int32_t exponent, int32_t v)
Compute the value multiplied the power-of-two.
void get_invsqrt_quantized_multiplier_exp (int32_t input, int32_t reverse_shift, int32_t &output_inv_sqrt, int32_t &output_shift)
Compute quantized multiplier and shift for the inverse square root of input.
Variables
constexpr int64_t fixed_point_one_Q0 = (1LL << 31)
constexpr float epsilon = 0.00001f
Function Documentation
calculate_quantized_multiplier()
Status calculate_quantized_multiplier (float multiplier, int32_t * quant_multiplier, int32_t * shift, bool ignore_epsilon = false)
Calculate quantized representation of multiplier.
Parameters
[in] multiplier Real multiplier.
[out] quant_multiplier Integer multiplier.
[out] shift bit shift. A negative value indicates a left shift, while a positive value indicates a right shift
[in] ignore_epsilon When true, ignore pre-defined epsilon value. Defaults to false
Returns
a status
Definition at line 39 of file AsymmHelpers.cpp.
References calculate_quantized_multiplier_greater_than_one(), and calculate_quantized_multiplier_less_than_one().
Referenced by calculate_quantized_multipliers(), CLQLSTMLayer::CLQLSTMLayer(), compute_quantized_multipliers_and_shifts(), NEQLSTMLayerNormalizationKernel::configure(), CLQLSTMLayerNormalizationKernel::configure(), ClDirectConv2dKernel::configure(), ClDirectConv3dKernel::configure(), CLDepthwiseConvolutionLayerNativeKernel::configure(), NELSTMLayerQuantized::configure(), CLLSTMLayerQuantized::configure(), NEQLSTMLayer::configure(), CLQLSTMLayer::configure(), arm_compute::test::convolution_3d::detail::convolution3d(), arm_compute::cpu::directconv3d_quantized_neon_ndhwc(), CpuPool2dAssemblyWrapperKernel::is_configured(), NEQLSTMLayer::NEQLSTMLayer(), arm_compute::test::validation::reference::qlstm_layer_normalization(), arm_compute::cpu::run_depthwise_quanitized8bit(), CpuPool2dAssemblyWrapperKernel::validate(), NELSTMLayerQuantized::validate(), CLLSTMLayerQuantized::validate(), NEQLSTMLayer::validate(), and CLQLSTMLayer::validate().
 {
     if(multiplier >= 1.f)
     {
         Status status = calculate_quantized_multiplier_greater_than_one(multiplier, quant_multiplier, shift);
         *shift *= -1;
         return status;
     }
     else
     {
         return calculate_quantized_multiplier_less_than_one(multiplier, quant_multiplier, shift, ignore_epsilon);
     }
 }
calculate_quantized_multiplier_greater_than_one()
Status calculate_quantized_multiplier_greater_than_one (float multiplier, int32_t * quantized_multiplier, int32_t * left_shift)
Calculate quantized representation of multiplier having value greater than one.
Parameters
[in] multiplier Real multiplier.
[out] quantized_multiplier Integer multiplier.
[out] left_shift Left bit shift.
Returns
a status
Definition at line 89 of file AsymmHelpers.cpp.
References ARM_COMPUTE_RETURN_ERROR_ON, and arm_compute::support::cpp11::round().
Referenced by calculate_quantized_multiplier().
 {
     ARM_COMPUTE_RETURN_ERROR_ON(quantized_multiplier == nullptr);
     ARM_COMPUTE_RETURN_ERROR_ON(left_shift == nullptr);
     ARM_COMPUTE_RETURN_ERROR_ON(multiplier < 1.f);
     int          shift_exp = 0;
     const double q         = std::frexp(multiplier, &shift_exp);
     *left_shift            = shift_exp;
     auto q_fixed           = static_cast<int64_t>(support::cpp11::round(q * fixed_point_one_Q0));
     ARM_COMPUTE_RETURN_ERROR_ON(q_fixed > fixed_point_one_Q0);
     if(q_fixed == fixed_point_one_Q0)
     {
         q_fixed /= 2;
         ++*left_shift;
     }
     ARM_COMPUTE_RETURN_ERROR_ON(*left_shift < 0);
     ARM_COMPUTE_RETURN_ERROR_ON(q_fixed > std::numeric_limits<int32_t>::max());
     *quantized_multiplier = static_cast<int32_t>(q_fixed);
     return Status{};
 }
calculate_quantized_multiplier_less_than_one()
Status calculate_quantized_multiplier_less_than_one (float multiplier, int32_t * quant_multiplier, int32_t * right_shift, bool ignore_epsilon = false)
Calculate quantized representation of multiplier with value less than one.
Parameters
[in] multiplier Real multiplier.
[out] quant_multiplier Integer multiplier.
[out] right_shift Right bit shift.
[in] ignore_epsilon When true, ignore pre-defined epsilon value. Defaults to false
Returns
a status
Definition at line 53 of file AsymmHelpers.cpp.
References ARM_COMPUTE_RETURN_ERROR_ON, epsilon, and arm_compute::support::cpp11::round().
Referenced by calculate_quantized_multiplier(), and main().
 {
     const float internal_epsilon = ignore_epsilon ? 0.0f : epsilon;
     ARM_COMPUTE_RETURN_ERROR_ON(quant_multiplier == nullptr);
     ARM_COMPUTE_RETURN_ERROR_ON(right_shift == nullptr);
     ARM_COMPUTE_RETURN_ERROR_ON(multiplier < -internal_epsilon);
     ARM_COMPUTE_RETURN_ERROR_ON(multiplier > 1.0f + internal_epsilon);
     int          shift_exp = 0;
     const double q         = std::frexp(multiplier, &shift_exp);
     *right_shift           = -1 * shift_exp;
     auto q_fixed           = static_cast<int64_t>(support::cpp11::round(q * fixed_point_one_Q0));
     ARM_COMPUTE_RETURN_ERROR_ON(q_fixed > fixed_point_one_Q0);
     if(q_fixed == fixed_point_one_Q0)
     {
         q_fixed /= 2;
         --*right_shift;
     }
     if(ignore_epsilon && *right_shift > 31)
     {
         *right_shift = 0;
         q_fixed      = 0;
     }
     ARM_COMPUTE_RETURN_ERROR_ON(*right_shift < 0);
     ARM_COMPUTE_RETURN_ERROR_ON(q_fixed > std::numeric_limits<int32_t>::max());
     *quant_multiplier = static_cast<int32_t>(q_fixed);
     return Status{};
 }
calculate_quantized_multipliers()
arm_compute::Status calculate_quantized_multipliers (const QuantizationInfo & iq_info, const QuantizationInfo & wq_info, const QuantizationInfo & oq_info, GEMMLowpOutputStageInfo & stage_info)
Calculate quantized representation of per-channel multipliers.
Parameters
[in] iq_info Input quantization info.
[in] wq_info Weights quantization info.
[in] oq_info Output quantization info.
[in,out] stage_info GemmLowp output stage info
Returns
a status
Definition at line 114 of file AsymmHelpers.cpp.
References ARM_COMPUTE_RETURN_ERROR_ON, ARM_COMPUTE_RETURN_ON_ERROR, calculate_quantized_multiplier(), GEMMLowpOutputStageInfo::gemmlowp_multiplier, GEMMLowpOutputStageInfo::gemmlowp_multipliers, GEMMLowpOutputStageInfo::gemmlowp_shift, GEMMLowpOutputStageInfo::gemmlowp_shifts, and QuantizationInfo::scale().
 {
     ARM_COMPUTE_RETURN_ERROR_ON(iq_info.scale().empty());
     ARM_COMPUTE_RETURN_ERROR_ON(wq_info.scale().empty());
     ARM_COMPUTE_RETURN_ERROR_ON(oq_info.scale().empty());
     const unsigned int size = wq_info.scale().size();
     auto &quant_multipliers = stage_info.gemmlowp_multipliers;
     auto &quant_shifts      = stage_info.gemmlowp_shifts;
     quant_multipliers.resize(size);
     quant_shifts.resize(size);
     const auto &w_scales = wq_info.scale();
     const float i_scale  = iq_info.scale().at(0);
     const float o_scale  = oq_info.scale().at(0);
     for(unsigned int i = 0; i < size; ++i)
     {
         const float multiplier       = i_scale * w_scales[i] / o_scale;
         int32_t     quant_multiplier = 0;
         int32_t     quant_shift      = 0;
         ARM_COMPUTE_RETURN_ON_ERROR(calculate_quantized_multiplier(multiplier, &quant_multiplier, &quant_shift));
         quant_multipliers[i] = quant_multiplier;
         quant_shifts[i]      = quant_shift;
     }
     // Legacy part
     stage_info.gemmlowp_shift      = quant_shifts[0];
     stage_info.gemmlowp_multiplier = quant_multipliers[0];
     return Status{};
 }
compute_quantized_multipliers_and_shifts()
void compute_quantized_multipliers_and_shifts (const ITensorInfo * input, const ITensorInfo * weights, const ITensorInfo * output, int32_t * output_multipliers_ptr, int32_t * output_shifts_ptr)
Compute quantized per-channel multipliers and shifts.
As many multipliers and shifts as output channels are computed. If weights are not quantized per-channel, multipliers and shifts will end up being the same for each channel.
Parameters
[in] input Input tensor info.
[in] weights Weights tensor info.
[in] output Output tensor info.
[out] output_multipliers_ptr Pointer to the buffer where to store per-channel multipliers.
[out] output_shifts_ptr Pointer to the buffer where to store per-channel shifts.
Returns
min and max values for the quantized data type
Definition at line 179 of file AsymmHelpers.cpp.
References calculate_quantized_multiplier(), ITensorInfo::quantization_info(), UniformQuantizationInfo::scale, QuantizationInfo::scale(), and QuantizationInfo::uniform().
Referenced by ClGemmConv2d::configure(), CLDepthwiseConvolutionLayer::prepare(), and ClGemmConv2d::validate().
 {
     const UniformQuantizationInfo iq_info = input->quantization_info().uniform();
     const QuantizationInfo        wq_info = weights->quantization_info();
     const UniformQuantizationInfo oq_info = output->quantization_info().uniform();
     const unsigned int num_filters = wq_info.scale().size();
     for(unsigned int i = 0; i < num_filters; ++i)
     {
         int32_t     output_multiplier = 0;
         int32_t     output_shift      = 0;
         const float multiplier        = iq_info.scale * wq_info.scale()[i] / oq_info.scale;
         calculate_quantized_multiplier(multiplier, &output_multiplier, &output_shift);
         output_multipliers_ptr[i] = output_multiplier;
         output_shifts_ptr[i]      = output_shift;
     }
 }
get_invsqrt_quantized_multiplier_exp()
void get_invsqrt_quantized_multiplier_exp (int32_t input, int32_t reverse_shift, int32_t & output_inv_sqrt, int32_t & output_shift)
Compute quantized multiplier and shift for the inverse square root of input.
Using 3-bit fixed point and 5 iteration of Newton-Raphson method.
Parameters
[in] input Input to use
[in] reverse_shift -1 to reverse the shift direction
[out] output_inv_sqrt Quantized multiplier for inverse square root
[out] output_shift Shift for inverse square root
Definition at line 257 of file AsymmHelpers.cpp.
References ARM_COMPUTE_ERROR_ON, arm_compute::test::validation::b, rounding_divide_by_pow2(), saturating_rounding_doubling_highmul(), and saturating_rounding_multiply_by_pow2().
Referenced by arm_compute::test::validation::reference::qlstm_layer_normalization(), and NEQLSTMLayerNormalizationKernel::run().
 {
     ARM_COMPUTE_ERROR_ON(input < 0);
     if(input <= 1)
     {
         // dealing the inputs (0 and 1) separately to avoid overflow
         output_inv_sqrt = std::numeric_limits<std::int32_t>::max();
         output_shift    = 0;
         return;
     }
     // prepare input for fixed point operation and compute shift value
     output_shift = 11;
     while(input >= (1 << 29))
     {
         input /= 4;
         ++output_shift;
     }
     const uint32_t max_left_shift_bits       = __builtin_clz(static_cast<uint32_t>(input)) - 1;
     const uint32_t max_left_shift_bits_pairs = max_left_shift_bits / 2;
     const uint32_t left_shift_bit_pairs      = max_left_shift_bits_pairs - 1;
     output_shift -= left_shift_bit_pairs;
     input <<= 2 * left_shift_bit_pairs;
     // Calculation in fixed point domain with 3 integer bits.
     using FixedPointRawType                    = int32_t;
     constexpr uint32_t fixedpoint_position     = 3;
     constexpr uint32_t fixedpoint_int_position = sizeof(FixedPointRawType) * 8 - 1 - fixedpoint_position;
     using FixedPoint3                          = FixedPointRawType;
     using FixedPoint0                          = FixedPointRawType;
     // fixed point representation of input divided by 2 and 1.5 for Newton-Raphson iteration
     const FixedPoint3 fixedpoint_input      = (input >> 1);
     const FixedPoint3 fixedpoint_half_input = rounding_divide_by_pow2(fixedpoint_input, 1);
     const FixedPoint3 fixedpoint_half_three = (0x1 << fixedpoint_int_position) + (0x1 << (fixedpoint_int_position - 1));
     // initial guess (1) in fixed point representation
     FixedPoint3 x = 0x1 << fixedpoint_int_position;
     // multiplication of two fixed point numbers, defined for readability
     auto fixed_point_mul = [](FixedPointRawType a, FixedPointRawType b) -> FixedPointRawType
     {
         return saturating_rounding_doubling_highmul(a, b);
     };
     // rescaling of fixed point to have dst_bit integer bits, defined for readability
     auto fixed_point_rescale = [](FixedPointRawType a, uint32_t src_bit, uint32_t dst_bit) -> FixedPointRawType
     {
         const uint32_t exponent = src_bit - dst_bit;
         return saturating_rounding_multiply_by_pow2(exponent, a);
     };
     // 5 iterations of Newton-Raphson method for inverse square root - 1.5 * x_n = input/2 * (x_n)^3
     constexpr int32_t num_iteration = 5;
     for(int32_t i = 0; i < num_iteration; ++i)
     {
         const auto x3 = fixed_point_rescale(fixed_point_mul(fixed_point_mul(x, x), x), 9, fixedpoint_position);
         x             = fixed_point_rescale(fixed_point_mul(fixedpoint_half_three, x) - fixed_point_mul(fixedpoint_half_input, x3), 6, fixedpoint_position);
     }
     // fixed point representation of sqrt(1/2)
     const FixedPoint0 fixedpoint_half_sqrt_2 = 1518500250;
     x                                        = fixed_point_mul(fixedpoint_half_sqrt_2, x);
     output_inv_sqrt                          = x;
     if(output_shift < 0)
     {
         output_inv_sqrt <<= -output_shift;
         output_shift = 0;
     }
     // convert right shift to left shift
     output_shift *= reverse_shift;
 }
get_min_max_values_from_quantized_data_type()
std::pair< int, int > get_min_max_values_from_quantized_data_type (DataType data_type)
Get minimum and maximum values for the input quantized data type.
Returns
min and max values for the quantized data type
Definition at line 151 of file AsymmHelpers.cpp.
References ARM_COMPUTE_ERROR, arm_compute::QASYMM16, arm_compute::QASYMM8, arm_compute::QASYMM8_SIGNED, arm_compute::QSYMM16, and arm_compute::QSYMM8.
Referenced by ClQuantizeKernel::configure(), ClGemmLowpQuantizeDownInt32ScaleByFixedPointKernel::configure(), ClGemmLowpQuantizeDownInt32ScaleKernel::configure(), CLQLSTMLayerNormalizationKernel::configure(), and CpuGemmLowpQuantizeDownInt32ScaleKernel::configure().
 {
     int min_quant_val = 0;
     int max_quant_val = 0;
     switch(data_type)
     {
         case DataType::QASYMM8:
             min_quant_val = std::numeric_limits<uint8_t>::min();
             max_quant_val = std::numeric_limits<uint8_t>::max();
             break;
         case DataType::QSYMM8:
         case DataType::QASYMM8_SIGNED:
             min_quant_val = std::numeric_limits<int8_t>::min();
             max_quant_val = std::numeric_limits<int8_t>::max();
             break;
         case DataType::QASYMM16:
             min_quant_val = std::numeric_limits<uint16_t>::min();
             max_quant_val = std::numeric_limits<uint16_t>::max();
             break;
         case DataType::QSYMM16:
             min_quant_val = std::numeric_limits<int16_t>::min();
             max_quant_val = std::numeric_limits<int16_t>::max();
             break;
         default:
             ARM_COMPUTE_ERROR("Unsupported data type");
     }
     return std::make_pair(min_quant_val, max_quant_val);
 }
multiply_by_quantized_multiplier()
int32_t multiply_by_quantized_multiplier (int32_t input, int32_t qmul, int32_t shift)
Compute the value multiplied by given quantized multiplier and shift.
Parameters
[in] input Target value to multiply.
[in] qmul Quantized multipler
[in] shift Left bit shift
Returns
The multiplied value
Definition at line 224 of file AsymmHelpers.cpp.
References rounding_divide_by_pow2(), and saturating_rounding_doubling_highmul().
Referenced by arm_compute::test::validation::reference::qlstm_layer_normalization(), and NEQLSTMLayerNormalizationKernel::run().
 {
     const auto left_shift  = shift > 0 ? shift : 0;
     const auto right_shift = shift > 0 ? 0 : -shift;
     return rounding_divide_by_pow2(saturating_rounding_doubling_highmul(input * (1 << left_shift), qmul), right_shift);
 }
rounding_divide_by_pow2()
int32_t rounding_divide_by_pow2 (int32_t x, int exponent) inline
Round to the nearest division by a power-of-two using exponent, copied from NEMath.
Note
This function calculates the following expression: (x + 2^n -1) / 2^n where n = exponent
Parameters
[in] x Element to divide.
[in] exponent Integer value used to round to nearest division by a power-of-two
Returns
the nearest division by a power-of-two using exponent
Definition at line 217 of file AsymmHelpers.cpp.
Referenced by get_invsqrt_quantized_multiplier_exp(), multiply_by_quantized_multiplier(), and saturating_rounding_multiply_by_pow2().
 {
     const int32_t mask      = (1 << exponent) - 1;
     const int32_t threshold = (mask >> 1) + (x < 0 ? 1 : 0);
     return (x >> exponent) + ((x & mask) > threshold ? 1 : 0);
 }
saturating_rounding_doubling_highmul()
int32_t saturating_rounding_doubling_highmul (int32_t a, int32_t b)
Compute multiplication of two integers.
Parameters
[in] a One integer to multiply
[in] b Another integer to multiply
Returns
The multiplied value
Definition at line 203 of file AsymmHelpers.cpp.
References arm_compute::support::cpp11::signbit().
Referenced by get_invsqrt_quantized_multiplier_exp(), and multiply_by_quantized_multiplier().
 {
     bool    overflow = a == b && a == std::numeric_limits<int32_t>::min();
     int64_t a_64(a);
     int64_t b_64(b);
     int64_t ab_64               = a_64 * b_64;
     const bool  is_positive_or_zero =
         a == 0 || b == 0 ||
         (std::signbit(static_cast<double>(a)) == std::signbit(static_cast<double>(b)));
     int32_t nudge               = is_positive_or_zero ? (1 << 30) : (1 - (1 << 30));
     int32_t ab_x2_high32        = static_cast<int32_t>((ab_64 + nudge) / (1ll << 31));
     return overflow ? std::numeric_limits<int32_t>::max() : ab_x2_high32;
 }
saturating_rounding_multiply_by_pow2()
int32_t saturating_rounding_multiply_by_pow2 (int32_t exponent, int32_t v)
Compute the value multiplied the power-of-two.
Parameters
[in] exponent Exponent used to calculate power-of-two
[in] v Target value to multiply
Returns
The multiplied value
Definition at line 231 of file AsymmHelpers.cpp.
References rounding_divide_by_pow2().
Referenced by get_invsqrt_quantized_multiplier_exp().
 {
     if(exponent == 0)
     {
         return v;
     }
     else if(exponent < 0)
     {
         return rounding_divide_by_pow2(v, -exponent);
     }
     else
     {
         constexpr auto min   = std::numeric_limits<int32_t>::min();
         constexpr auto max   = std::numeric_limits<int32_t>::max();
         const auto     width = sizeof(int32_t) * 8;
         const int32_t threshold = ((1 << (width - 1 - exponent)) - 1);
         bool          pos_mask  = v > threshold;
         bool          neg_mask  = v < -threshold;
         int32_t       result    = v << exponent;
         result                  = pos_mask ? max : result;
         result                  = neg_mask ? min : result;
         return result;
     }
 }
Variable Documentation
epsilon
constexpr float epsilon = 0.00001f
Definition at line 37 of file AsymmHelpers.cpp.
Referenced by GraphBuilder::add_batch_normalization_node(), GraphBuilder::add_l2_normalize_node(), arm_compute::test::validation::reference::batch_normalization_layer(), calculate_quantized_multiplier_less_than_one(), NEMeanStdDevNormalizationKernel::configure(), NEFuseBatchNormalizationKernel::configure(), CLMeanStdDevNormalizationKernel::configure(), NEBatchNormalizationLayerKernel::configure(), CLL2NormalizeLayerKernel::configure(), NEInstanceNormalizationLayer::configure(), CLFuseBatchNormalizationKernel::configure(), CLBatchNormalizationLayerKernel::configure(), arm_compute::graph::backends::detail::create_batch_normalization_layer(), arm_compute::graph::backends::detail::create_fused_convolution_batch_normalization_layer(), arm_compute::graph::backends::detail::create_fused_convolution_batch_normalization_with_post_op(), arm_compute::graph::backends::detail::create_fused_depthwise_convolution_batch_normalization_layer(), arm_compute::graph::backends::detail::create_l2_normalize_layer(), AssetsLibrary::fill_boxes(), arm_compute::cpu::fp32_neon_batch_normalization(), arm_compute::test::validation::reference::fuse_batch_normalization_conv_layer(), arm_compute::graph::detail::fuse_convolution_batch_normalization_with_post_ops(), arm_compute::graph::detail::fuse_convolution_with_batch_normalization(), arm_compute::graph::detail::fuse_depthwise_convolution_with_batch_normalization(), arm_compute::cpu::fused_batch_normalization_conv(), arm_compute::cpu::fused_batch_normalization_conv_f32(), arm_compute::cpu::fused_batch_normalization_dwc_nchw_f32(), arm_compute::cpu::fused_batch_normalization_dwc_nhwc(), arm_compute::cpu::fused_batch_normalization_dwc_nhwc_f32(), arm_compute::test::validation::reference::instance_normalization(), arm_compute::cpu::instance_normalization_nchw(), arm_compute::helpers::float_ops::is_one(), arm_compute::helpers::float_ops::is_zero(), arm_compute::test::validation::reference::l2_normalize(), arm_compute::cpu::l2_normalize_yz(), arm_compute::test::validation::reference::mean_std_normalization_layer(), arm_compute::cpu::mean_stddev_normalization(), NEL2NormalizeLayerKernel::name(), NEFuseBatchNormalizationKernel::name(), NEInstanceNormalizationLayerKernel::name(), NEBatchNormalizationLayerKernel::name(), NEMeanStdDevNormalizationKernel::name(), arm_compute::cpu::neon_fp32_instancenorm(), arm_compute::cpu::neon_fp32_l2_normalize_x(), arm_compute::cpu::neon_fp32_l2_normalize_yz(), arm_compute::cpu::neon_fp32_meanstddevnorm(), compare< RelativeTolerance< U > >::operator bool(), AbsoluteTolerance< U >::operator U(), RelativeTolerance< U >::operator value_type(), RangedUniformDistribution< T >::RangedUniformDistribution(), arm_compute::test::round_half_even(), arm_compute::utils::rounding::round_half_even(), NEInstanceNormalizationLayer::validate(), and arm_compute::graph::backends::detail::validate_l2_normalize_layer().
fixed_point_one_Q0
constexpr int64_t fixed_point_one_Q0 = (1LL << 31)
Definition at line 36 of file AsymmHelpers.cpp.