Compute Library: arm_compute::utils::info_helpers Namespace Reference
arm_compute::utils::info_helpers Namespace Reference
Functions
bool is_relu (ActivationLayerInfo activation_info)
Checks if activation information correspond to a relu activation function.
bool is_relu6 (ActivationLayerInfo activation_info)
Checks if activation information correspond to a relu6 activation function.
template<typename T >
void build_lstm_params_tensor_info (const LSTMParams< T > &lstm_params, LSTMParams< ITensorInfo > *lstm_params_info)
Build LSTMParams<ITensorInfo> object by extracting the metadata from each tensor.
Function Documentation
build_lstm_params_tensor_info()
void arm_compute::utils::info_helpers::build_lstm_params_tensor_info (const LSTMParams< T > & lstm_params, LSTMParams< ITensorInfo > * lstm_params_info) inline
Build LSTMParams<ITensorInfo> object by extracting the metadata from each tensor.
Parameters
[in] lstm_params The LSTMParams<T> object containing the tensors.
[out] lstm_params_info The LSTMParams<ITensorInfo> to be constructed.
Definition at line 71 of file InfoHelpers.h.
References ARM_COMPUTE_ERROR_ON_NULLPTR, LSTMParams< T >::cell_intermediate_scale(), LSTMParams< T >::cell_layer_norm_weights(), LSTMParams< T >::cell_to_forget_weights(), LSTMParams< T >::cell_to_input_weights(), LSTMParams< T >::cell_to_output_weights(), LSTMParams< T >::forget_intermediate_scale(), LSTMParams< T >::forget_layer_norm_weights(), LSTMParams< T >::has_cifg_opt(), LSTMParams< T >::has_peephole_opt(), LSTMParams< T >::has_projection(), LSTMParams< T >::hidden_state_scale(), LSTMParams< T >::hidden_state_zero(), LSTMParams< T >::input_gate_bias(), arm_compute::test::validation::input_info, LSTMParams< T >::input_intermediate_scale(), LSTMParams< T >::input_layer_norm_weights(), LSTMParams< T >::input_to_input_weights(), arm_compute::test::validation::output_info, LSTMParams< T >::output_intermediate_scale(), LSTMParams< T >::output_layer_norm_weights(), LSTMParams< T >::projection_bias(), LSTMParams< T >::projection_weights(), LSTMParams< T >::recurrent_to_input_weights(), LSTMParams< T >::set_cifg_params(), LSTMParams< T >::set_hidden_state_params(), LSTMParams< T >::set_layer_normalization_params(), LSTMParams< T >::set_matmul_scale_params(), LSTMParams< T >::set_peephole_params(), LSTMParams< T >::set_projection_params(), and LSTMParams< T >::use_layer_norm().
Referenced by NELSTMLayer::configure(), NEQLSTMLayer::configure(), CLLSTMLayer::configure(), and CLQLSTMLayer::configure().
 {
     if(lstm_params.has_peephole_opt())
     {
         ARM_COMPUTE_ERROR_ON_NULLPTR(lstm_params.cell_to_forget_weights(), lstm_params.cell_to_output_weights());
         lstm_params_info->set_peephole_params(lstm_params.cell_to_forget_weights()->info(), lstm_params.cell_to_output_weights()->info());
     }
     if(lstm_params.has_projection())
     {
         ARM_COMPUTE_ERROR_ON_NULLPTR(lstm_params.projection_weights());
         lstm_params_info->set_projection_params(lstm_params.projection_weights()->info(),
                                                 lstm_params.projection_bias() != nullptr ? lstm_params.projection_bias()->info() : nullptr);
     }
     if(!lstm_params.has_cifg_opt())
     {
         ARM_COMPUTE_ERROR_ON_NULLPTR(lstm_params.input_to_input_weights(), lstm_params.recurrent_to_input_weights(), lstm_params.input_gate_bias());
         ITensorInfo *cell_to_input_weights_info = (lstm_params.has_peephole_opt()) ? lstm_params.cell_to_input_weights()->info() : nullptr;
         lstm_params_info->set_cifg_params(lstm_params.input_to_input_weights()->info(), lstm_params.recurrent_to_input_weights()->info(),
                                           cell_to_input_weights_info, lstm_params.input_gate_bias()->info());
     }
     if(lstm_params.use_layer_norm())
     {
         ARM_COMPUTE_ERROR_ON_NULLPTR(lstm_params.forget_layer_norm_weights(),
                                      lstm_params.output_layer_norm_weights(),
                                      lstm_params.cell_layer_norm_weights());
         if(!lstm_params.has_cifg_opt())
         {
             ARM_COMPUTE_ERROR_ON_NULLPTR(lstm_params.input_layer_norm_weights());
         }
         ITensorInfo *forget_info = lstm_params.forget_layer_norm_weights()->info();
         ITensorInfo *cell_info   = lstm_params.cell_layer_norm_weights()->info();
         ITensorInfo *output_info = lstm_params.output_layer_norm_weights()->info();
         ITensorInfo *input_info  = lstm_params.has_cifg_opt() ? nullptr : lstm_params.input_layer_norm_weights()->info();
         lstm_params_info->set_layer_normalization_params(input_info, forget_info, cell_info, output_info);
     }
     lstm_params_info->set_matmul_scale_params(lstm_params.input_intermediate_scale(),
                                               lstm_params.forget_intermediate_scale(),
                                               lstm_params.cell_intermediate_scale(),
                                               lstm_params.output_intermediate_scale());
     lstm_params_info->set_hidden_state_params(lstm_params.hidden_state_zero(), lstm_params.hidden_state_scale());
 }
is_relu()
bool arm_compute::utils::info_helpers::is_relu (ActivationLayerInfo activation_info) inline
Checks if activation information correspond to a relu activation function.
Parameters
[in] activation_info Activation metadata
Returns
True if activation metadata correspond to a relu activation else false
Definition at line 43 of file InfoHelpers.h.
References ActivationLayerInfo::activation(), ActivationLayerInfo::enabled(), and ActivationLayerInfo::RELU.
 {
     return activation_info.enabled() && activation_info.activation() == ActivationLayerInfo::ActivationFunction::RELU;
 }
is_relu6()
bool arm_compute::utils::info_helpers::is_relu6 (ActivationLayerInfo activation_info) inline
Checks if activation information correspond to a relu6 activation function.
Parameters
[in] activation_info Activation metadata
Returns
True if activation metadata correspond to a relu6 activation else false
Definition at line 54 of file InfoHelpers.h.
References ActivationLayerInfo::a(), ActivationLayerInfo::activation(), ActivationLayerInfo::b(), ActivationLayerInfo::BOUNDED_RELU, ActivationLayerInfo::enabled(), and ActivationLayerInfo::LU_BOUNDED_RELU.
 {
     const bool is_lu_bounded_relu = activation_info.activation() == ActivationLayerInfo::ActivationFunction::LU_BOUNDED_RELU
                                     && activation_info.a() == 6.f && activation_info.b() == 0.f;
     const bool is_bounded_relu = activation_info.activation() == ActivationLayerInfo::ActivationFunction::BOUNDED_RELU
                                  && activation_info.a() == 6.f;
     return activation_info.enabled() && (is_lu_bounded_relu || is_bounded_relu);
 }