Compute Library: arm_compute::assembly_utils Namespace Reference
arm_compute::assembly_utils Namespace Reference
Functions
arm_gemm::Activation map_to_arm_gemm_activation (const ActivationLayerInfo &act)
Performs a mapping between Compute Library ActivationLayerInfo and the assembly Activation structure.
arm_conv::PaddingValues map_to_arm_conv_padding (const PadStrideInfo &pad_stride_info)
Performs a mapping between Compute Library PadStrideInfo and the assembly PaddingValues structure.
arm_gemm::WeightFormat map_to_arm_gemm_weight_format (const arm_compute::WeightFormat &weight_format)
Performs a mapping from Compute Library WeightFormat to the assembly WeightFormat enum.
arm_compute::WeightFormat map_to_arm_compute_weight_format (const arm_gemm::WeightFormat &weight_format)
Performs a mapping from Assembly WeightFormat to the Compute Library WeightFormat enum.
Function Documentation
map_to_arm_compute_weight_format()
arm_compute::WeightFormat map_to_arm_compute_weight_format (const arm_gemm::WeightFormat & weight_format)
Performs a mapping from Assembly WeightFormat to the Compute Library WeightFormat enum.
Parameters
[in] weight_format Assembly WeightFormat enum value
Returns
Compute Library WeightFormat
Definition at line 190 of file AssemblyUtils.cpp.
References arm_gemm::ANY, arm_compute::ANY, arm_gemm::OHWI, arm_compute::OHWI, arm_gemm::OHWIo128, arm_compute::OHWIo128, arm_gemm::OHWIo16, arm_compute::OHWIo16, arm_gemm::OHWIo16i2, arm_compute::OHWIo16i2, arm_gemm::OHWIo16i2_bf16, arm_compute::OHWIo16i2_bf16, arm_gemm::OHWIo16i4, arm_compute::OHWIo16i4, arm_gemm::OHWIo16i4_bf16, arm_compute::OHWIo16i4_bf16, arm_gemm::OHWIo16i8, arm_compute::OHWIo16i8, arm_gemm::OHWIo2, arm_compute::OHWIo2, arm_gemm::OHWIo2i8, arm_compute::OHWIo2i8, arm_gemm::OHWIo32, arm_compute::OHWIo32, arm_gemm::OHWIo32i2, arm_compute::OHWIo32i2, arm_gemm::OHWIo32i2_bf16, arm_compute::OHWIo32i2_bf16, arm_gemm::OHWIo32i4, arm_compute::OHWIo32i4, arm_gemm::OHWIo32i4_bf16, arm_compute::OHWIo32i4_bf16, arm_gemm::OHWIo32i8, arm_compute::OHWIo32i8, arm_gemm::OHWIo4, arm_compute::OHWIo4, arm_gemm::OHWIo4i2, arm_compute::OHWIo4i2, arm_gemm::OHWIo4i2_bf16, arm_compute::OHWIo4i2_bf16, arm_gemm::OHWIo4i4, arm_compute::OHWIo4i4, arm_gemm::OHWIo4i4_bf16, arm_compute::OHWIo4i4_bf16, arm_gemm::OHWIo4i8, arm_compute::OHWIo4i8, arm_gemm::OHWIo64, arm_compute::OHWIo64, arm_gemm::OHWIo64i2, arm_compute::OHWIo64i2, arm_gemm::OHWIo64i2_bf16, arm_compute::OHWIo64i2_bf16, arm_gemm::OHWIo64i4, arm_compute::OHWIo64i4, arm_gemm::OHWIo64i4_bf16, arm_compute::OHWIo64i4_bf16, arm_gemm::OHWIo64i8, arm_compute::OHWIo64i8, arm_gemm::OHWIo8, arm_compute::OHWIo8, arm_gemm::OHWIo8i2, arm_compute::OHWIo8i2, arm_gemm::OHWIo8i2_bf16, arm_compute::OHWIo8i2_bf16, arm_gemm::OHWIo8i4, arm_compute::OHWIo8i4, arm_gemm::OHWIo8i4_bf16, arm_compute::OHWIo8i4_bf16, arm_gemm::OHWIo8i8, arm_compute::OHWIo8i8, arm_gemm::UNSPECIFIED, and arm_compute::UNSPECIFIED.
Referenced by CpuGemmAssemblyDispatch::has_opt_impl().
 {
     arm_compute::WeightFormat acl_weight_fromat;
     switch(weight_format)
     {
         case arm_gemm::WeightFormat::UNSPECIFIED:
             acl_weight_fromat = arm_compute::WeightFormat::UNSPECIFIED;
             break;
         case arm_gemm::WeightFormat::ANY:
             acl_weight_fromat = arm_compute::WeightFormat::ANY;
             break;
         case arm_gemm::WeightFormat::OHWI:
             acl_weight_fromat = arm_compute::WeightFormat::OHWI;
             break;
         case arm_gemm::WeightFormat::OHWIo2:
             acl_weight_fromat = arm_compute::WeightFormat::OHWIo2;
             break;
         case arm_gemm::WeightFormat::OHWIo4:
             acl_weight_fromat = arm_compute::WeightFormat::OHWIo4;
             break;
         case arm_gemm::WeightFormat::OHWIo8:
             acl_weight_fromat = arm_compute::WeightFormat::OHWIo8;
             break;
         case arm_gemm::WeightFormat::OHWIo16:
             acl_weight_fromat = arm_compute::WeightFormat::OHWIo16;
             break;
         case arm_gemm::WeightFormat::OHWIo32:
             acl_weight_fromat = arm_compute::WeightFormat::OHWIo32;
             break;
         case arm_gemm::WeightFormat::OHWIo64:
             acl_weight_fromat = arm_compute::WeightFormat::OHWIo64;
             break;
         case arm_gemm::WeightFormat::OHWIo128:
             acl_weight_fromat = arm_compute::WeightFormat::OHWIo128;
             break;
         case arm_gemm::WeightFormat::OHWIo4i2:
             acl_weight_fromat = arm_compute::WeightFormat::OHWIo4i2;
             break;
         case arm_gemm::WeightFormat::OHWIo4i2_bf16:
             acl_weight_fromat = arm_compute::WeightFormat::OHWIo4i2_bf16;
             break;
         case arm_gemm::WeightFormat::OHWIo8i2:
             acl_weight_fromat = arm_compute::WeightFormat::OHWIo8i2;
             break;
         case arm_gemm::WeightFormat::OHWIo8i2_bf16:
             acl_weight_fromat = arm_compute::WeightFormat::OHWIo8i2_bf16;
             break;
         case arm_gemm::WeightFormat::OHWIo16i2:
             acl_weight_fromat = arm_compute::WeightFormat::OHWIo16i2;
             break;
         case arm_gemm::WeightFormat::OHWIo16i2_bf16:
             acl_weight_fromat = arm_compute::WeightFormat::OHWIo16i2_bf16;
             break;
         case arm_gemm::WeightFormat::OHWIo32i2:
             acl_weight_fromat = arm_compute::WeightFormat::OHWIo32i2;
             break;
         case arm_gemm::WeightFormat::OHWIo32i2_bf16:
             acl_weight_fromat = arm_compute::WeightFormat::OHWIo32i2_bf16;
             break;
         case arm_gemm::WeightFormat::OHWIo64i2:
             acl_weight_fromat = arm_compute::WeightFormat::OHWIo64i2;
             break;
         case arm_gemm::WeightFormat::OHWIo64i2_bf16:
             acl_weight_fromat = arm_compute::WeightFormat::OHWIo64i2_bf16;
             break;
         case arm_gemm::WeightFormat::OHWIo4i4:
             acl_weight_fromat = arm_compute::WeightFormat::OHWIo4i4;
             break;
         case arm_gemm::WeightFormat::OHWIo4i4_bf16:
             acl_weight_fromat = arm_compute::WeightFormat::OHWIo4i4_bf16;
             break;
         case arm_gemm::WeightFormat::OHWIo8i4:
             acl_weight_fromat = arm_compute::WeightFormat::OHWIo8i4;
             break;
         case arm_gemm::WeightFormat::OHWIo8i4_bf16:
             acl_weight_fromat = arm_compute::WeightFormat::OHWIo8i4_bf16;
             break;
         case arm_gemm::WeightFormat::OHWIo16i4:
             acl_weight_fromat = arm_compute::WeightFormat::OHWIo16i4;
             break;
         case arm_gemm::WeightFormat::OHWIo16i4_bf16:
             acl_weight_fromat = arm_compute::WeightFormat::OHWIo16i4_bf16;
             break;
         case arm_gemm::WeightFormat::OHWIo32i4:
             acl_weight_fromat = arm_compute::WeightFormat::OHWIo32i4;
             break;
         case arm_gemm::WeightFormat::OHWIo32i4_bf16:
             acl_weight_fromat = arm_compute::WeightFormat::OHWIo32i4_bf16;
             break;
         case arm_gemm::WeightFormat::OHWIo64i4:
             acl_weight_fromat = arm_compute::WeightFormat::OHWIo64i4;
             break;
         case arm_gemm::WeightFormat::OHWIo64i4_bf16:
             acl_weight_fromat = arm_compute::WeightFormat::OHWIo64i4_bf16;
             break;
         case arm_gemm::WeightFormat::OHWIo2i8:
             acl_weight_fromat = arm_compute::WeightFormat::OHWIo2i8;
             break;
         case arm_gemm::WeightFormat::OHWIo4i8:
             acl_weight_fromat = arm_compute::WeightFormat::OHWIo4i8;
             break;
         case arm_gemm::WeightFormat::OHWIo8i8:
             acl_weight_fromat = arm_compute::WeightFormat::OHWIo8i8;
             break;
         case arm_gemm::WeightFormat::OHWIo16i8:
             acl_weight_fromat = arm_compute::WeightFormat::OHWIo16i8;
             break;
         case arm_gemm::WeightFormat::OHWIo32i8:
             acl_weight_fromat = arm_compute::WeightFormat::OHWIo32i8;
             break;
         case arm_gemm::WeightFormat::OHWIo64i8:
             acl_weight_fromat = arm_compute::WeightFormat::OHWIo64i8;
             break;
         default:
             acl_weight_fromat = arm_compute::WeightFormat::UNSPECIFIED;
     }
     return acl_weight_fromat;
 }
map_to_arm_conv_padding()
arm_conv::PaddingValues map_to_arm_conv_padding (const PadStrideInfo & pad_stride_info)
Performs a mapping between Compute Library PadStrideInfo and the assembly PaddingValues structure.
Parameters
[in] pad_stride_info Compute Library padding and strides info.
Returns
Assembly padding values.
Definition at line 62 of file AssemblyUtils.cpp.
References PadStrideInfo::pad_bottom(), PadStrideInfo::pad_left(), PadStrideInfo::pad_right(), and PadStrideInfo::pad_top().
 {
     return arm_conv::PaddingValues{ pad_stride_info.pad_left(),
                                     pad_stride_info.pad_top(),
                                     pad_stride_info.pad_right(),
                                     pad_stride_info.pad_bottom() };
 }
map_to_arm_gemm_activation()
arm_gemm::Activation map_to_arm_gemm_activation (const ActivationLayerInfo & act)
Performs a mapping between Compute Library ActivationLayerInfo and the assembly Activation structure.
Parameters
[in] act Compute Library activation info.
Returns
Assembly activation info.
Definition at line 30 of file AssemblyUtils.cpp.
References ActivationLayerInfo::a(), ActivationLayerInfo::activation(), ActivationLayerInfo::b(), ActivationLayerInfo::BOUNDED_RELU, Activation::BoundedReLU, ActivationLayerInfo::LU_BOUNDED_RELU, Activation::None, Activation::param1, Activation::param2, Activation::ReLU, ActivationLayerInfo::RELU, and Activation::type.
Referenced by CpuGemmAssemblyDispatch::configure(), CpuGemmAssemblyDispatch::has_opt_impl(), CpuDepthwiseConv2dAssemblyDispatch::is_activation_supported(), and CpuGemmAssemblyDispatch::is_activation_supported().
 {
     arm_gemm::Activation gemm_act;
     // Early exit in case lower bound is other than 0, as it's not yet supported
     if(act.b() != 0.f)
     {
         return gemm_act;
     }
     switch(act.activation())
     {
         case ActivationLayerInfo::ActivationFunction::RELU:
             gemm_act.type = arm_gemm::Activation::Type::ReLU;
             break;
         case ActivationLayerInfo::ActivationFunction::BOUNDED_RELU:
             gemm_act.type   = arm_gemm::Activation::Type::BoundedReLU;
             gemm_act.param1 = act.a();
             gemm_act.param2 = 0.f;
             break;
         case ActivationLayerInfo::ActivationFunction::LU_BOUNDED_RELU:
             gemm_act.type   = arm_gemm::Activation::Type::BoundedReLU;
             gemm_act.param1 = act.a();
             gemm_act.param2 = act.b();
             break;
         default:
             gemm_act.type = arm_gemm::Activation::Type::None;
     }
     return gemm_act;
 }
map_to_arm_gemm_weight_format()
arm_gemm::WeightFormat map_to_arm_gemm_weight_format (const arm_compute::WeightFormat & weight_format)
Performs a mapping from Compute Library WeightFormat to the assembly WeightFormat enum.
Parameters
[in] weight_format Compute Library WeightFormat enum value
Returns
Assembly WeightFormat
Definition at line 70 of file AssemblyUtils.cpp.
References arm_gemm::ANY, arm_compute::ANY, arm_gemm::OHWI, arm_compute::OHWI, arm_gemm::OHWIo128, arm_compute::OHWIo128, arm_gemm::OHWIo16, arm_compute::OHWIo16, arm_gemm::OHWIo16i2, arm_compute::OHWIo16i2, arm_gemm::OHWIo16i2_bf16, arm_compute::OHWIo16i2_bf16, arm_gemm::OHWIo16i4, arm_compute::OHWIo16i4, arm_gemm::OHWIo16i4_bf16, arm_compute::OHWIo16i4_bf16, arm_gemm::OHWIo16i8, arm_compute::OHWIo16i8, arm_gemm::OHWIo2, arm_compute::OHWIo2, arm_gemm::OHWIo2i8, arm_compute::OHWIo2i8, arm_gemm::OHWIo32, arm_compute::OHWIo32, arm_gemm::OHWIo32i2, arm_compute::OHWIo32i2, arm_gemm::OHWIo32i2_bf16, arm_compute::OHWIo32i2_bf16, arm_gemm::OHWIo32i4, arm_compute::OHWIo32i4, arm_gemm::OHWIo32i4_bf16, arm_compute::OHWIo32i4_bf16, arm_gemm::OHWIo32i8, arm_compute::OHWIo32i8, arm_gemm::OHWIo4, arm_compute::OHWIo4, arm_gemm::OHWIo4i2, arm_compute::OHWIo4i2, arm_gemm::OHWIo4i2_bf16, arm_compute::OHWIo4i2_bf16, arm_gemm::OHWIo4i4, arm_compute::OHWIo4i4, arm_gemm::OHWIo4i4_bf16, arm_compute::OHWIo4i4_bf16, arm_gemm::OHWIo4i8, arm_compute::OHWIo4i8, arm_gemm::OHWIo64, arm_compute::OHWIo64, arm_gemm::OHWIo64i2, arm_compute::OHWIo64i2, arm_gemm::OHWIo64i2_bf16, arm_compute::OHWIo64i2_bf16, arm_gemm::OHWIo64i4, arm_compute::OHWIo64i4, arm_gemm::OHWIo64i4_bf16, arm_compute::OHWIo64i4_bf16, arm_gemm::OHWIo64i8, arm_compute::OHWIo64i8, arm_gemm::OHWIo8, arm_compute::OHWIo8, arm_gemm::OHWIo8i2, arm_compute::OHWIo8i2, arm_gemm::OHWIo8i2_bf16, arm_compute::OHWIo8i2_bf16, arm_gemm::OHWIo8i4, arm_compute::OHWIo8i4, arm_gemm::OHWIo8i4_bf16, arm_compute::OHWIo8i4_bf16, arm_gemm::OHWIo8i8, arm_compute::OHWIo8i8, arm_gemm::UNSPECIFIED, and arm_compute::UNSPECIFIED.
Referenced by CpuGemmAssemblyDispatch::has_opt_impl().
 {
     arm_gemm::WeightFormat gemm_weight_fromat;
     switch(weight_format)
     {
         case arm_compute::WeightFormat::UNSPECIFIED:
             gemm_weight_fromat = arm_gemm::WeightFormat::UNSPECIFIED;
             break;
         case arm_compute::WeightFormat::ANY:
             gemm_weight_fromat = arm_gemm::WeightFormat::ANY;
             break;
         case arm_compute::WeightFormat::OHWI:
             gemm_weight_fromat = arm_gemm::WeightFormat::OHWI;
             break;
         case arm_compute::WeightFormat::OHWIo2:
             gemm_weight_fromat = arm_gemm::WeightFormat::OHWIo2;
             break;
         case arm_compute::WeightFormat::OHWIo4:
             gemm_weight_fromat = arm_gemm::WeightFormat::OHWIo4;
             break;
         case arm_compute::WeightFormat::OHWIo8:
             gemm_weight_fromat = arm_gemm::WeightFormat::OHWIo8;
             break;
         case arm_compute::WeightFormat::OHWIo16:
             gemm_weight_fromat = arm_gemm::WeightFormat::OHWIo16;
             break;
         case arm_compute::WeightFormat::OHWIo32:
             gemm_weight_fromat = arm_gemm::WeightFormat::OHWIo32;
             break;
         case arm_compute::WeightFormat::OHWIo64:
             gemm_weight_fromat = arm_gemm::WeightFormat::OHWIo64;
             break;
         case arm_compute::WeightFormat::OHWIo128:
             gemm_weight_fromat = arm_gemm::WeightFormat::OHWIo128;
             break;
         case arm_compute::WeightFormat::OHWIo4i2:
             gemm_weight_fromat = arm_gemm::WeightFormat::OHWIo4i2;
             break;
         case arm_compute::WeightFormat::OHWIo4i2_bf16:
             gemm_weight_fromat = arm_gemm::WeightFormat::OHWIo4i2_bf16;
             break;
         case arm_compute::WeightFormat::OHWIo8i2:
             gemm_weight_fromat = arm_gemm::WeightFormat::OHWIo8i2;
             break;
         case arm_compute::WeightFormat::OHWIo8i2_bf16:
             gemm_weight_fromat = arm_gemm::WeightFormat::OHWIo8i2_bf16;
             break;
         case arm_compute::WeightFormat::OHWIo16i2:
             gemm_weight_fromat = arm_gemm::WeightFormat::OHWIo16i2;
             break;
         case arm_compute::WeightFormat::OHWIo16i2_bf16:
             gemm_weight_fromat = arm_gemm::WeightFormat::OHWIo16i2_bf16;
             break;
         case arm_compute::WeightFormat::OHWIo32i2:
             gemm_weight_fromat = arm_gemm::WeightFormat::OHWIo32i2;
             break;
         case arm_compute::WeightFormat::OHWIo32i2_bf16:
             gemm_weight_fromat = arm_gemm::WeightFormat::OHWIo32i2_bf16;
             break;
         case arm_compute::WeightFormat::OHWIo64i2:
             gemm_weight_fromat = arm_gemm::WeightFormat::OHWIo64i2;
             break;
         case arm_compute::WeightFormat::OHWIo64i2_bf16:
             gemm_weight_fromat = arm_gemm::WeightFormat::OHWIo64i2_bf16;
             break;
         case arm_compute::WeightFormat::OHWIo4i4:
             gemm_weight_fromat = arm_gemm::WeightFormat::OHWIo4i4;
             break;
         case arm_compute::WeightFormat::OHWIo4i4_bf16:
             gemm_weight_fromat = arm_gemm::WeightFormat::OHWIo4i4_bf16;
             break;
         case arm_compute::WeightFormat::OHWIo8i4:
             gemm_weight_fromat = arm_gemm::WeightFormat::OHWIo8i4;
             break;
         case arm_compute::WeightFormat::OHWIo8i4_bf16:
             gemm_weight_fromat = arm_gemm::WeightFormat::OHWIo8i4_bf16;
             break;
         case arm_compute::WeightFormat::OHWIo16i4:
             gemm_weight_fromat = arm_gemm::WeightFormat::OHWIo16i4;
             break;
         case arm_compute::WeightFormat::OHWIo16i4_bf16:
             gemm_weight_fromat = arm_gemm::WeightFormat::OHWIo16i4_bf16;
             break;
         case arm_compute::WeightFormat::OHWIo32i4:
             gemm_weight_fromat = arm_gemm::WeightFormat::OHWIo32i4;
             break;
         case arm_compute::WeightFormat::OHWIo32i4_bf16:
             gemm_weight_fromat = arm_gemm::WeightFormat::OHWIo32i4_bf16;
             break;
         case arm_compute::WeightFormat::OHWIo64i4:
             gemm_weight_fromat = arm_gemm::WeightFormat::OHWIo64i4;
             break;
         case arm_compute::WeightFormat::OHWIo64i4_bf16:
             gemm_weight_fromat = arm_gemm::WeightFormat::OHWIo64i4_bf16;
             break;
         case arm_compute::WeightFormat::OHWIo2i8:
             gemm_weight_fromat = arm_gemm::WeightFormat::OHWIo2i8;
             break;
         case arm_compute::WeightFormat::OHWIo4i8:
             gemm_weight_fromat = arm_gemm::WeightFormat::OHWIo4i8;
             break;
         case arm_compute::WeightFormat::OHWIo8i8:
             gemm_weight_fromat = arm_gemm::WeightFormat::OHWIo8i8;
             break;
         case arm_compute::WeightFormat::OHWIo16i8:
             gemm_weight_fromat = arm_gemm::WeightFormat::OHWIo16i8;
             break;
         case arm_compute::WeightFormat::OHWIo32i8:
             gemm_weight_fromat = arm_gemm::WeightFormat::OHWIo32i8;
             break;
         case arm_compute::WeightFormat::OHWIo64i8:
             gemm_weight_fromat = arm_gemm::WeightFormat::OHWIo64i8;
             break;
         default:
             gemm_weight_fromat = arm_gemm::WeightFormat::UNSPECIFIED;
     }
     return gemm_weight_fromat;
 }