Compute Library: add_copyright Namespace Reference
add_copyright Namespace Reference
Functions
def add_cpp_copyright (f, content)
def add_python_copyright (f, content)
def remove_comment (content)
def remove_comment_python (content)
def check_file (path)
Variables
mit_copyright = open("scripts/copyright_mit.txt",'r').read()
path = os.path.join(root, f)
Function Documentation
add_cpp_copyright()
def add_copyright.add_cpp_copyright (f, content)
Definition at line 8 of file add_copyright.py.
Referenced by check_file().
 def add_cpp_copyright( f, content):
     global mit_copyright
     out = open(f,'w')
     out.write("/*\n")
     for line in mit_copyright.split('\n')[:-1]:
         out.write(" *");
         if line.strip() != "":
             out.write(" %s" %line)
         out.write("\n")
     out.write(" */\n")
     out.write(content.strip())
     out.write("\n")
     out.close()
add_python_copyright()
def add_copyright.add_python_copyright (f, content)
Definition at line 22 of file add_copyright.py.
Referenced by check_file().
 def add_python_copyright( f, content):
     global mit_copyright
     out = open(f,'w')
     for line in mit_copyright.split('\n')[:-1]:
         out.write("#");
         if line.strip() != "":
             out.write(" %s" %line)
         out.write("\n")
     out.write(content.strip())
     out.write("\n")
     out.close()
check_file()
def add_copyright.check_file (path)
Definition at line 60 of file add_copyright.py.
References add_cpp_copyright(), and add_python_copyright().
 def check_file( path ):
     root, f = os.path.split(path)
     if f in ['.clang-tidy', '.clang-format']:
         print("Skipping file: {}".format(path))
         return
     with open(path, 'r', encoding='utf-8') as fd:
         content = fd.read()
         _, extension = os.path.splitext(f)
         if extension in ['.cpp', '.h', '.hpp', '.inl', '.cl', '.in', '.cs']:
             if not content.startswith('/*'):
                 add_cpp_copyright(path, content)
         elif extension == '.py' or f in ['SConstruct', 'SConscript']:
             if not content.startswith('# Copyright'):
                 add_python_copyright(path, content)
         elif f == 'CMakeLists.txt':
             if not content.startswith('# Copyright'):
                 add_python_copyright(path, content)
         else:
             raise Exception("Unhandled file: {}".format(path))
remove_comment()
def add_copyright.remove_comment (content)
Definition at line 34 of file add_copyright.py.
 def remove_comment( content ):
     comment=True
     out=""
     for line in content.split('\n'):
         if comment:
             if line.startswith(' */'):
                 comment=False
             elif line.startswith('/*') or line.startswith(' *'):
                 #print(line)
                 continue
             else:
                 raise Exception("ERROR: not a comment ? '%s'"% line)
         else:
             out += line + "\n"
     return out
remove_comment_python()
def add_copyright.remove_comment_python (content)
Definition at line 49 of file add_copyright.py.
 def remove_comment_python( content ):
     comment=True
     out=""
     for line in content.split('\n'):
         if comment and line.startswith('#'):
             continue
         else:
             comment = False
             out += line + "\n"
     return out
Variable Documentation
mit_copyright
mit_copyright = open("scripts/copyright_mit.txt",'r').read()
Definition at line 6 of file add_copyright.py.
path
path = os.path.join(root, f)
Definition at line 89 of file add_copyright.py.