Compute Library: OpTensorContent Struct Reference
OpTensorContent Struct Reference
#include <OperatorGraphImpl.h>
Public Types
using Id = DependencyGraph::Id
Public Member Functions
OpTensorContent ()=default
OpTensorContent (Id id)
OpTensorContent (Id id, ITensorInfo *desc)
~OpTensorContent ()=default
OpTensorContent (const OpTensorContent &)=default
OpTensorContent & operator= (const OpTensorContent &)=default
OpTensorContent (OpTensorContent &&)=default
OpTensorContent & operator= (OpTensorContent &&)=default
bool operator== (const OpTensorContent &other) const
const ITensorInfo * get_tensor_info () const
ITensorInfo * get_tensor_info ()
Data Fields
Id id {}
ITensorInfo * desc {}
Detailed Description
Definition at line 51 of file OperatorGraphImpl.h.
Member Typedef Documentation
Id
using Id = DependencyGraph::Id
Definition at line 54 of file OperatorGraphImpl.h.
Constructor & Destructor Documentation
OpTensorContent() [1/5]
OpTensorContent () default
OpTensorContent() [2/5]
OpTensorContent (Id id) inline
Definition at line 56 of file OperatorGraphImpl.h.
         : id{ id }, desc{}
     {
     }
OpTensorContent() [3/5]
OpTensorContent (Id id, ITensorInfo * desc) inline
Definition at line 60 of file OperatorGraphImpl.h.
         : id{ id }, desc{ desc }
     {
     }
~OpTensorContent()
~OpTensorContent () default
OpTensorContent() [4/5]
OpTensorContent (const OpTensorContent &) default
OpTensorContent() [5/5]
OpTensorContent (OpTensorContent &&) default
Member Function Documentation
get_tensor_info() [1/2]
const ITensorInfo* get_tensor_info () const inline
Definition at line 74 of file OperatorGraphImpl.h.
Referenced by arm_compute::experimental::dynamic_fusion::add_op_conv2d(), arm_compute::experimental::dynamic_fusion::add_op_elementwise_op(), and arm_compute::experimental::dynamic_fusion::add_op_floor().
     {
         return desc;
     }
get_tensor_info() [2/2]
ITensorInfo* get_tensor_info () inline
Definition at line 78 of file OperatorGraphImpl.h.
     {
         return desc;
     }
operator=() [1/2]
OpTensorContent& operator= (const OpTensorContent &) default
operator=() [2/2]
OpTensorContent& operator= (OpTensorContent &&) default
operator==()
bool operator== (const OpTensorContent & other) const inline
Definition at line 69 of file OperatorGraphImpl.h.
References OpTensorContent::desc.
     {
         return desc == other.desc;
     }
Field Documentation
desc
ITensorInfo* desc {}
Definition at line 84 of file OperatorGraphImpl.h.
Referenced by OpTensorContent::operator==().
id
Id id {}
Definition at line 83 of file OperatorGraphImpl.h.
The documentation for this struct was generated from the following file:
src/core/experimental/dynamic_fusion/WorkloadImpl/OperatorGraphImpl.h