Compute Library: ClKernelGraph Struct Reference
ClKernelGraph Struct Reference
#include <ClKernelGraph.h>
Public Types
using Id = DependencyGraph::Id
using KernelMap = std::map< Id, utils::memory::deep_unique_ptr< ClKernel > >
using KernelTensorMap = std::map< Id, utils::memory::deep_unique_ptr< ClKernelTensor > >
Public Member Functions
ClKernelGraph ()=default
~ClKernelGraph ()=default
Status add_kernel_tensor (ITensorInfo *desc, MemoryType memory_type, const AuxMemoryInfo &memory_info, Id &tensor_id, Id merge_point=DependencyGraph::empty_id())
template<typename ContentT , typename KernelDescT >
Status add_kernel (const ClKernelConfig &config, const KernelDescT &desc, const ITensorDescPack< ClKernelTensor > &tensors, Id &kernel_id)
ClKernel * get_kernel (Id id)
const ClKernel * get_kernel (Id id) const
ClKernelTensor * get_tensor (Id id)
const ClKernelTensor * get_tensor (Id id) const
Data Fields
DependencyGraph graph {}
KernelMap kernels {}
KernelTensorMap tensors {}
Friends
bool operator== (const ClKernelGraph &graph0, const ClKernelGraph &graph1)
Detailed Description
Definition at line 182 of file ClKernelGraph.h.
Member Typedef Documentation
Id
using Id = DependencyGraph::Id
Definition at line 185 of file ClKernelGraph.h.
KernelMap
using KernelMap = std::map<Id, utils::memory::deep_unique_ptr<ClKernel> >
Definition at line 186 of file ClKernelGraph.h.
KernelTensorMap
using KernelTensorMap = std::map<Id, utils::memory::deep_unique_ptr<ClKernelTensor> >
Definition at line 187 of file ClKernelGraph.h.
Constructor & Destructor Documentation
ClKernelGraph()
ClKernelGraph () default
~ClKernelGraph()
~ClKernelGraph () default
Member Function Documentation
add_kernel()
Status add_kernel (const ClKernelConfig & config, const KernelDescT & desc, const ITensorDescPack< ClKernelTensor > & tensors, Id & kernel_id) inline
Definition at line 208 of file ClKernelGraph.h.
References ITensorDescPack< TDesc >::get_const_dst_tensors(), ITensorDescPack< TDesc >::get_const_src_tensors(), arm_compute::test::validation::k, and tf_frozen_model_extractor::t.
Referenced by Conv2dContent::translate(), ElementwiseContent::translate(), and FloorContent::translate().
     {
         const auto      src_tensors = tensors.get_const_src_tensors();
         const auto      dst_tensors = tensors.get_const_dst_tensors();
         std::vector<Id> src_tensor_ids{};
         std::vector<Id> dst_tensor_ids{};
         for(const auto &t : src_tensors)
         {
             src_tensor_ids.push_back(t->id);
         }
         for(const auto &t : dst_tensors)
         {
             dst_tensor_ids.push_back(t->id);
         }
         kernel_id          = graph.add_operator(src_tensor_ids, dst_tensor_ids).second;
         auto k             = utils::memory::make_deep_unique<ClKernel, ContentT>(this, kernel_id, config, desc, tensors);
         kernels[kernel_id] = std::move(k);
         return Status{};
     }
add_kernel_tensor()
Status add_kernel_tensor (ITensorInfo * desc, MemoryType memory_type, const AuxMemoryInfo & memory_info, Id & tensor_id, Id merge_point = DependencyGraph::empty_id()) inline
Definition at line 197 of file ClKernelGraph.h.
     {
         tensor_id = graph.add_tensor(merge_point);
         if(tensors.find(tensor_id) == tensors.end())
         {
             tensors[tensor_id] = utils::memory::make_deep_unique<ClKernelTensor, ClKernelTensor>(tensor_id, desc, memory_type, memory_info);
         }
         return Status{};
     }
get_kernel() [1/2]
ClKernel* get_kernel (Id id) inline
Definition at line 228 of file ClKernelGraph.h.
     {
         return kernels.at(id).get();
     }
get_kernel() [2/2]
const ClKernel* get_kernel (Id id) const inline
Definition at line 232 of file ClKernelGraph.h.
     {
         return kernels.at(id).get();
     }
get_tensor() [1/2]
ClKernelTensor* get_tensor (Id id) inline
Definition at line 237 of file ClKernelGraph.h.
Referenced by arm_compute::experimental::dynamic_fusion::generate(), arm_compute::experimental::dynamic_fusion::generate_store(), Conv2dContent::translate(), ElementwiseContent::translate(), and FloorContent::translate().
     {
         return tensors.at(id).get();
     }
get_tensor() [2/2]
const ClKernelTensor* get_tensor (Id id) const inline
Definition at line 241 of file ClKernelGraph.h.
     {
         return tensors.at(id).get();
     }
Friends And Related Function Documentation
operator==
bool operator== (const ClKernelGraph & graph0, const ClKernelGraph & graph1) friend
Definition at line 192 of file ClKernelGraph.h.
     {
         return graph0.graph == graph1.graph && graph0.kernels == graph1.kernels && graph0.tensors == graph1.tensors;
     }
Field Documentation
graph
DependencyGraph graph {}
Definition at line 246 of file ClKernelGraph.h.
Referenced by arm_compute::experimental::dynamic_fusion::build(), and arm_compute::experimental::dynamic_fusion::traverse().
kernels
KernelMap kernels {}
Definition at line 247 of file ClKernelGraph.h.
Referenced by arm_compute::experimental::dynamic_fusion::traverse().
tensors
KernelTensorMap tensors {}
Definition at line 248 of file ClKernelGraph.h.
The documentation for this struct was generated from the following file:
src/core/experimental/dynamic_fusion/WorkloadImpl/ClKernelGraph.h