Compute Library: ClFusedKernelGraph Struct Reference
ClFusedKernelGraph Struct Reference
#include <ClFusedKernelGraph.h>
Public Types
using Id = DependencyGraph::Id
using KernelFusionGroupMap = std::map< Id, utils::memory::deep_unique_ptr< ClKernelFusionGroup > >
Public Member Functions
ClFusedKernelGraph ()=default
~ClFusedKernelGraph ()=default
ClFusedKernelGraph (const ClFusedKernelGraph &graph)=default
ClFusedKernelGraph & operator= (const ClFusedKernelGraph &graph)=default
ClFusedKernelGraph (ClFusedKernelGraph &&graph)=default
ClFusedKernelGraph & operator= (ClFusedKernelGraph &&graph)=default
Id add_fusion_group (const std::vector< const ClKernel *> &fused_kernels)
Status fuse (ClKernelFusionGroup &fg0, ClKernelFusionGroup &fg1)
Status can_fuse (const ClKernelFusionGroup &fg0, const ClKernelFusionGroup &fg1) const
Data Fields
const ClKernelGraph * original_graph {}
DependencyGraph fg_dependency {}
KernelFusionGroupMap fusion_groups {}
Friends
bool operator== (const ClFusedKernelGraph &graph0, const ClFusedKernelGraph &graph1)
Detailed Description
Definition at line 134 of file ClFusedKernelGraph.h.
Member Typedef Documentation
Id
using Id = DependencyGraph::Id
Definition at line 137 of file ClFusedKernelGraph.h.
KernelFusionGroupMap
using KernelFusionGroupMap = std::map<Id, utils::memory::deep_unique_ptr<ClKernelFusionGroup> >
Definition at line 139 of file ClFusedKernelGraph.h.
Constructor & Destructor Documentation
ClFusedKernelGraph() [1/3]
ClFusedKernelGraph () default
~ClFusedKernelGraph()
~ClFusedKernelGraph () default
ClFusedKernelGraph() [2/3]
ClFusedKernelGraph (const ClFusedKernelGraph & graph) default
ClFusedKernelGraph() [3/3]
ClFusedKernelGraph (ClFusedKernelGraph && graph) default
Member Function Documentation
add_fusion_group()
Id add_fusion_group (const std::vector< const ClKernel *> & fused_kernels) inline
Definition at line 156 of file ClFusedKernelGraph.h.
References arm_compute::mlgo::parser::end(), and arm_compute::test::validation::k.
     {
         auto fg = utils::memory::make_deep_unique<ClKernelFusionGroup, ClKernelFusionGroup>();
         for(const auto k : fused_kernels)
         {
             fg->add_fused_kernel(k);
         }
         const auto      src_tensors = fg->get_src_tensors();
         const auto      dst_tensors = fg->get_dst_tensors();
         std::vector<Id> inputs{};
         std::transform(std::begin(src_tensors), std::end(src_tensors), std::back_inserter(inputs), [this](auto kernel)
         {
             return fg_dependency.add_tensor(kernel->id);
         });
         std::vector<Id> outputs{};
         std::transform(std::begin(dst_tensors), std::end(dst_tensors), std::back_inserter(outputs), [this](auto kernel)
         {
             return fg_dependency.add_tensor(kernel->id);
         });
         const auto id = fg_dependency.add_operator(inputs, outputs);
         fg->set_id(id.second);
         fusion_groups[id.second] = std::move(fg);
         return id.second;
     }
can_fuse()
Status can_fuse (const ClKernelFusionGroup & fg0, const ClKernelFusionGroup & fg1) const inline
ASSUMPTION0: All tensors have 0 or 1 incoming kernel ASSUMPTION1: All kernels have exactly 1 dst tensor (Temporary, can be lifted once we start supporting multi-dst kernels) Note that this does not apply to fusion groups ASSUMPTION2: Simple kernels' tile infos can be overriden (share with) that of the root kernel's ASSUMPTION3: Extension of ASSUMPTION0: All tensors have 0 or 1 incoming fusion group INV0: All Fusion groups have a single root INV1: All Fusion groups have no cycles or loops within themselves <- guaranteed by the underlying ClKernelGraph having no cycles or loops; enforced by DependencyGraph INV2: The ClKernelFusionGroup itself has no cycles or loops <- enforced by DependencyGraph INV3: All non-roots are Simple kernels INV4: All non roots' dst tensors have the same shape as that of the root kernel INV5: All kernels within a fusion group have the same UnitWorkloadStage
Definition at line 319 of file ClFusedKernelGraph.h.
References ARM_COMPUTE_ERROR_ON, arm_compute::detail::have_different_dimensions(), ClKernelFusionGroup::id, arm_compute::experimental::dynamic_fusion::is_in(), arm_compute::RUNTIME_ERROR, arm_compute::experimental::dynamic_fusion::Simple, and tf_frozen_model_extractor::t.
Referenced by arm_compute::experimental::dynamic_fusion::fuse().
     {
         /// ASSUMPTION0: All tensors have 0 or 1 incoming kernel
         /// ASSUMPTION1: All kernels have exactly 1 dst tensor (Temporary, can be lifted once we start supporting multi-dst kernels)
         ///              Note that this does not apply to fusion groups
         /// ASSUMPTION2: Simple kernels' tile infos can be overriden (share with) that of the root kernel's
         /// ASSUMPTION3: Extension of ASSUMPTION0: All tensors have 0 or 1 incoming fusion group
         /// INV0: All Fusion groups have a single root
         /// INV1: All Fusion groups have no cycles or loops within themselves <- guaranteed by the underlying ClKernelGraph having no cycles or loops; enforced by DependencyGraph
         /// INV2: The ClKernelFusionGroup itself has no cycles or loops <- enforced by DependencyGraph
         /// INV3: All non-roots are Simple kernels
         /// INV4: All non roots' dst tensors have the same shape as that of the root kernel
         /// INV5: All kernels within a fusion group have the same UnitWorkloadStage
         const ClKernelFusionGroup *fg_src {};
         const ClKernelFusionGroup *fg_dst{};
         // Check 0: Ensure fg0 and fg1 are "directly connected": one of them is a direct parent of the other
         // This guarantess INV0
         // This also finds fg_src (parent / root) and fg_dst (child / non-root)
         if(is_in(fg1.id, fg_dependency.dst_ops(fg0.id)))
         {
             fg_src = &fg0;
             fg_dst = &fg1;
         }
         else if(is_in(fg0.id, fg_dependency.dst_ops(fg1.id)))
         {
             fg_src = &fg1;
             fg_dst = &fg0;
         }
         else
         {
             return Status{ ErrorCode::RUNTIME_ERROR, "Invalid fusion: Not directly connected fusion groups cannot be fused together" };
         }
         // Find unconnected tensors between fg_src and fg_dst
         std::vector<Id> unconnected_tensors{};
         for(const auto &t : fg_dependency.dst_tensors(fg_src->id))
         {
             if(!is_in(t, fg_dependency.src_tensors(fg_dst->id)))
             {
                 unconnected_tensors.push_back(t);
             }
         }
         // Check 1: Any unconnected tensor cannot be an ancestor of fg_dst
         // This guarantees INV2: That is, the fused graph does not have any cycles or loops between different fusion groups
         for(const auto &t : unconnected_tensors)
         {
             if(fg_dependency.path_exists_from_tensor_to_op(t, fg_dst->id))
             {
                 return Status{ ErrorCode::RUNTIME_ERROR, "Invalid fusion: the fusion would result in cycles or loops" };
             }
         }
         // Check 2: All non-root fgs are simple. Ensure INV3
         if(fg_dst->get_root_kernel()->complexity() != Complexity::Simple)
         {
             return Status{ ErrorCode::RUNTIME_ERROR, "Invalid fusion: only root kernel can be a complex kernel" };
         }
         // Check 3: All non roots' dst tensors have the same shape as that of the root kernel. Ensure INV4
         const auto root_kernel_dst_tensors = fg_dependency.dst_tensors(fg_src->id);
         ARM_COMPUTE_ERROR_ON(root_kernel_dst_tensors.size() != 1); // (ASSUMPTION 1: All kernels have exactly 1 dst tensor)
         const auto root_kernel_dst_tensor_info = original_graph->get_tensor(root_kernel_dst_tensors[0])->desc;
         for(const auto &t : fg_dependency.dst_tensors(fg_dst->id))
         {
             const auto t_info = original_graph->get_tensor(t)->desc;
             if(detail::have_different_dimensions(root_kernel_dst_tensor_info->tensor_shape(), t_info->tensor_shape(), 0))
             {
                 return Status{ ErrorCode::RUNTIME_ERROR, "Invalid fusion: all non roots' dst tensors should have the same shape as that of the root kernel" };
             }
         }
         // Check 4: All kernels within a fg have the same UnitWorkloadStage. Ensure INV5
         if(!(fg_src->get_root_kernel()->config().stage == fg_dst->get_root_kernel()->config().stage))
         {
             return Status{ ErrorCode::RUNTIME_ERROR, "Invalid fusion: all kernels within a fusion group should have the same UnitWorkloadStage" };
         }
         return Status{};
     }
fuse()
Status fuse (ClKernelFusionGroup & fg0, ClKernelFusionGroup & fg1) inline
PRE: Already checked by can_fuse, and thus all the INVs and ASSUMPTIONS still hold
Definition at line 181 of file ClFusedKernelGraph.h.
References ClKernelFusionGroup::id, arm_compute::experimental::dynamic_fusion::is_in(), arm_compute::RUNTIME_ERROR, tf_frozen_model_extractor::t, arm_compute::experimental::dynamic_fusion::traverse(), and arm_compute::utils::cast::U.
Referenced by arm_compute::experimental::dynamic_fusion::fuse().
     {
         /// PRE: Already checked by can_fuse, and thus all the INVs and ASSUMPTIONS still hold
         ClKernelFusionGroup *fg_src{};
         ClKernelFusionGroup *fg_dst{};
         // Find fg_src (parent / root) and fg_dst (child / non-root)
         if(is_in(fg1.id, fg_dependency.dst_ops(fg0.id)))
         {
             fg_src = &fg0;
             fg_dst = &fg1;
         }
         else if(is_in(fg0.id, fg_dependency.dst_ops(fg1.id)))
         {
             fg_src = &fg1;
             fg_dst = &fg0;
         }
         else
         {
             return Status{ ErrorCode::RUNTIME_ERROR, "Invalid fusion: Not directly connected fusion groups cannot be fused together" };
         }
         for(const auto &t : fg_dependency.src_tensors(fg_dst->id))
         {
             if(!is_in(t, fg_dependency.dst_tensors(fg_src->id)))
             {
                 // Link any incoming tensors of fg_dst, that ARE NOT in between fg_src and fg_dst, to fg_src
                 // Before:
                 // fg_src
                 // |
                 // ..          t1
                 // |           |
                 // -> fg_dst <-
                 //
                 // After:
                 // fg_src <---t1
                 //
                 const auto st = link_src_tensors(fg_src->id, { t });
                 if(!bool(st))
                 {
                     return st;
                 }
             }
             else
             {
                 const auto dst_fgs = fg_dependency.dst_ops_from_tensor(t);
                 if(dst_fgs.size() == 1U && dst_fgs.at(0) == fg_dst->id)
                 {
                     // Remove any incoming tensors of fg_dst, that ARE in between fg_src and fg_dst
                     // AND that are not connected to any other outgoing fgs (Note that they cannot connect to any other incoming fgs as all tensors can have at most 1 incoming fg (ASSUMPTION 3))
                     // Before:
                     // fg_src
                     // |
                     // t0
                     // |
                     // -> fg_dst
                     //
                     // After:
                     // fg_src
                     //
                     const auto st = remove_fg_tensor(t);
                     if(!bool(st))
                     {
                         return st;
                     }
                 }
                 else
                 {
                     // If the tensors ARE in between fg_src and fg_dst
                     // BUT have any other outgoing fgs than fg_dst, then we leave it as a dst tensor to the fused fg_src
                     // Before:
                     // fg_src
                     // |
                     // t0
                     // |
                     // |-----------
                     // |          |
                     // -> fg_dst  -> fg_other
                     //
                     // After:
                     // fg_src
                     // |
                     // t0
                     // |
                     // -> fg_other
                     //
                     // Note that this may seem like a case we shouldn't fuse. But actually all it means is that t0 is an
                     // intermediate tensor between the fused fg_src and fg_dst, but only that we also STORE it to memory
                     // so that any unfused fg's (fg_other in this case) can read it.
                     // So all this means that we not only can STORE the tensors at the "end" of a fusion group,
                     // but also any other tensors that are not source tensors. And all tensors that are STORED (exported),
                     // can be termed "dst tensors" to a fusion group
                     void();
                 }
             }
         }
         for(const auto &t : fg_dependency.dst_tensors(fg_dst->id))
         {
             // Link any outgoing tensors of fg_dst to fg_src
             // Before:
             // fg_src
             // |
             // ..
             // |
             // -> fg_dst
             //    |
             //    |--------
             //    |       |
             //    |-> t0  |-> t1
             //
             // After:
             // fg_src
             // |
             // |--------
             // |       |
             // |-> t0  |-> t1
             //
             const auto st = link_dst_tensors(fg_src->id, { t });
             if(!bool(st))
             {
                 return st;
             }
         }
         // Merge fg_dst's graph into fg_src's graph
         for(const auto kernel : traverse(*fg_dst))
         {
             fg_src->add_fused_kernel(kernel);
         }
         const auto st = remove_fg(fg_dst->id);
         return st;
     }
operator=() [1/2]
ClFusedKernelGraph& operator= (const ClFusedKernelGraph & graph) default
operator=() [2/2]
ClFusedKernelGraph& operator= (ClFusedKernelGraph && graph) default
Friends And Related Function Documentation
operator==
bool operator== (const ClFusedKernelGraph & graph0, const ClFusedKernelGraph & graph1) friend
NOTE: fg_dependency may change based on the order of fusion, and thus is omitted in the comparison. The fusion groups can already guarantee the equivalence of fusion In the future we may want to enforce a stronger equivalence by implementing topological comparison between DependencyGraph s
Definition at line 148 of file ClFusedKernelGraph.h.
     {
         /// NOTE: fg_dependency may change based on the order of fusion, and thus is omitted in the comparison.
         ///       The fusion groups can already guarantee the equivalence of fusion
         ///       In the future we may want to enforce a stronger equivalence by implementing topological comparison between @ref DependencyGraph s
         return graph0.original_graph == graph1.original_graph && graph0.fusion_groups == graph1.fusion_groups;
     }
Field Documentation
fg_dependency
DependencyGraph fg_dependency {}
Definition at line 403 of file ClFusedKernelGraph.h.
Referenced by arm_compute::experimental::dynamic_fusion::generate(), arm_compute::experimental::dynamic_fusion::generate_store(), and arm_compute::experimental::dynamic_fusion::traverse().
fusion_groups
KernelFusionGroupMap fusion_groups {}
Definition at line 404 of file ClFusedKernelGraph.h.
Referenced by arm_compute::experimental::dynamic_fusion::traverse().
original_graph
const ClKernelGraph* original_graph {}
Definition at line 402 of file ClFusedKernelGraph.h.
Referenced by arm_compute::experimental::dynamic_fusion::build(), arm_compute::experimental::dynamic_fusion::generate(), arm_compute::experimental::dynamic_fusion::generate_store(), and arm_compute::experimental::dynamic_fusion::init_fusion_graph().
The documentation for this struct was generated from the following file:
src/core/experimental/dynamic_fusion/WorkloadImpl/ClFusedKernelGraph.h