Compute Library: ClKernelFusionGroup Struct Reference
ClKernelFusionGroup Struct Reference
A const view of a subgraph of the ClKernelGraph to be fused together.
#include <ClFusedKernelGraph.h>
Public Types
using Id = DependencyGraph::Id
Public Member Functions
ClKernelFusionGroup ()=default
ClKernelFusionGroup (Id id)
~ClKernelFusionGroup ()=default
void set_id (Id i)
Id add_fused_kernel (const ClKernel *kernel)
const ClKernel * get_root_kernel () const
std::vector< const ClKernelTensor * > get_src_tensors () const
std::vector< const ClKernelTensor * > get_dst_tensors () const
Data Fields
Id id {}
DependencyGraph graph {}
std::map< Id, const ClKernel * > fused_kernels {}
std::map< Id, const ClKernelTensor * > tensors {}
Friends
bool operator== (const ClKernelFusionGroup &fg0, const ClKernelFusionGroup &fg1)
Detailed Description
A const view of a subgraph of the ClKernelGraph to be fused together.
Definition at line 47 of file ClFusedKernelGraph.h.
Member Typedef Documentation
Id
using Id = DependencyGraph::Id
Definition at line 50 of file ClFusedKernelGraph.h.
Constructor & Destructor Documentation
ClKernelFusionGroup() [1/2]
ClKernelFusionGroup () default
ClKernelFusionGroup() [2/2]
ClKernelFusionGroup (Id id) inline
Definition at line 53 of file ClFusedKernelGraph.h.
References ClKernelFusionGroup::fused_kernels, ClKernelFusionGroup::graph, ClKernelFusionGroup::tensors, and ClKernelFusionGroup::~ClKernelFusionGroup().
         : id{ id }, graph{}, fused_kernels{}, tensors{}
     {
     }
~ClKernelFusionGroup()
~ClKernelFusionGroup () default
Referenced by ClKernelFusionGroup::ClKernelFusionGroup().
Member Function Documentation
add_fused_kernel()
Id add_fused_kernel (const ClKernel * kernel) inline
PRE: Acyclicity ensured by DependencyGraph PRE: Connectedness ensured by DependencyGraph PRE: Single-rootedness ensured by User
Definition at line 64 of file ClFusedKernelGraph.h.
References DependencyGraph::add_operator(), DependencyGraph::add_tensor(), ClKernelFusionGroup::fused_kernels, ClKernelFusionGroup::graph, ClKernelFusionGroup::id, tf_frozen_model_extractor::t, ClKernel::tensors(), and ClKernelFusionGroup::tensors.
     {
         /// PRE: Acyclicity ensured by DependencyGraph
         /// PRE: Connectedness ensured by DependencyGraph
         /// PRE: Single-rootedness ensured by User
         std::vector<Id> src_tensors;
         for(const auto t : kernel->tensors().get_const_src_tensors())
         {
             auto id = graph.add_tensor(t->id);
             if(tensors.find(id) == tensors.end())
             {
                 tensors[id] = t;
             }
             src_tensors.push_back(id);
         }
         std::vector<Id> dst_tensors;
         for(const auto t : kernel->tensors().get_const_dst_tensors())
         {
             auto id = graph.add_tensor(t->id);
             if(tensors.find(id) == tensors.end())
             {
                 tensors[id] = t;
             }
             dst_tensors.push_back(id);
         }
         auto id                  = graph.add_operator(src_tensors, dst_tensors);
         fused_kernels[id.second] = kernel;
         return id.second;
     }
get_dst_tensors()
std::vector<const ClKernelTensor *> get_dst_tensors () const inline
Definition at line 111 of file ClFusedKernelGraph.h.
References DependencyGraph::dst_tensors(), ClKernelFusionGroup::graph, and ClKernelFusionGroup::tensors.
     {
         std::vector<const ClKernelTensor *> dst_tensors;
         for(auto tensor_id : graph.dst_tensors())
         {
             dst_tensors.push_back(tensors.at(tensor_id));
         }
         return dst_tensors;
     }
get_root_kernel()
const ClKernel* get_root_kernel () const inline
Definition at line 94 of file ClFusedKernelGraph.h.
References ARM_COMPUTE_ERROR_ON, ClKernelFusionGroup::fused_kernels, DependencyGraph::get_root_ops(), and ClKernelFusionGroup::graph.
Referenced by arm_compute::experimental::dynamic_fusion::generate_store().
     {
         auto root_kernels = graph.get_root_ops();
         ARM_COMPUTE_ERROR_ON(root_kernels.size() != 1);
         return fused_kernels.at(root_kernels.at(0));
     }
get_src_tensors()
std::vector<const ClKernelTensor *> get_src_tensors () const inline
Definition at line 101 of file ClFusedKernelGraph.h.
References ClKernelFusionGroup::graph, DependencyGraph::src_tensors(), and ClKernelFusionGroup::tensors.
     {
         std::vector<const ClKernelTensor *> src_tensors;
         for(auto tensor_id : graph.src_tensors())
         {
             src_tensors.push_back(tensors.at(tensor_id));
         }
         return src_tensors;
     }
set_id()
void set_id (Id i) inline
Definition at line 59 of file ClFusedKernelGraph.h.
     {
         id = i;
     }
Friends And Related Function Documentation
operator==
bool operator== (const ClKernelFusionGroup & fg0, const ClKernelFusionGroup & fg1) friend
Definition at line 121 of file ClFusedKernelGraph.h.
     {
         return fg0.id == fg1.id && fg0.graph == fg1.graph && fg0.fused_kernels == fg1.fused_kernels && fg0.tensors == fg1.tensors;
     }
Field Documentation
fused_kernels
std::map<Id, const ClKernel *> fused_kernels {}
Definition at line 128 of file ClFusedKernelGraph.h.
Referenced by ClKernelFusionGroup::add_fused_kernel(), ClKernelFusionGroup::ClKernelFusionGroup(), ClKernelFusionGroup::get_root_kernel(), and arm_compute::experimental::dynamic_fusion::traverse().
graph
DependencyGraph graph {}
Definition at line 127 of file ClFusedKernelGraph.h.
Referenced by ClKernelFusionGroup::add_fused_kernel(), ClKernelFusionGroup::ClKernelFusionGroup(), ClKernelFusionGroup::get_dst_tensors(), ClKernelFusionGroup::get_root_kernel(), ClKernelFusionGroup::get_src_tensors(), and arm_compute::experimental::dynamic_fusion::traverse().
id
Id id {}
Definition at line 126 of file ClFusedKernelGraph.h.
Referenced by ClKernelFusionGroup::add_fused_kernel(), ClFusedKernelGraph::can_fuse(), ClFusedKernelGraph::fuse(), and arm_compute::experimental::dynamic_fusion::generate_store().
tensors
std::map<Id, const ClKernelTensor *> tensors {}
Definition at line 129 of file ClFusedKernelGraph.h.
Referenced by ClKernelFusionGroup::add_fused_kernel(), ClKernelFusionGroup::ClKernelFusionGroup(), ClKernelFusionGroup::get_dst_tensors(), and ClKernelFusionGroup::get_src_tensors().
The documentation for this struct was generated from the following file:
src/core/experimental/dynamic_fusion/WorkloadImpl/ClFusedKernelGraph.h