Compute Library: src/c/AclTensorPack.cpp File Reference
AclTensorPack.cpp File Reference
#include "arm_compute/AclEntrypoints.h"
#include "src/common/ITensorV2.h"
#include "src/common/TensorPack.h"
#include "src/common/utils/Macros.h"
Functions
AclStatus AclCreateTensorPack (AclTensorPack *external_pack, AclContext external_ctx)
Creates a tensor pack.
AclStatus AclPackTensor (AclTensorPack external_pack, AclTensor external_tensor, int32_t slot_id)
Add a tensor to a tensor pack.
AclStatus AclPackTensors (AclTensorPack external_pack, AclTensor *external_tensors, int32_t *slot_ids, size_t num_tensors)
A list of tensors to a tensor pack.
AclStatus AclDestroyTensorPack (AclTensorPack external_pack)
Destroy a given tensor pack object.
Function Documentation
AclCreateTensorPack()
AclStatus AclCreateTensorPack (AclTensorPack * pack, AclContext ctx)
Creates a tensor pack.
Tensor packs are used to create a collection of tensors that can be passed around for operator execution
Parameters
[in,out] pack A valid non-zero tensor pack object if no failures occur
[in] ctx Context to be used
Returns
Status code
Returns:
AclSuccess if function was completed successfully
AclOutOfMemory if there was a failure allocating memory resources
AclInvalidArgument if a given argument is invalid
Definition at line 50 of file AclTensorPack.cpp.
References AclOutOfMemory, AclSuccess, ARM_COMPUTE_LOG_ERROR_WITH_FUNCNAME_ACL, ARM_COMPUTE_RETURN_CENUM_ON_FAILURE, arm_compute::get_internal(), arm_compute::test::validation::pack, and arm_compute::detail::validate_internal_context().
Referenced by TensorPack::TensorPack().
 {
     using namespace arm_compute;
     IContext *ctx = get_internal(external_ctx);
     const StatusCode status = detail::validate_internal_context(ctx);
     ARM_COMPUTE_RETURN_CENUM_ON_FAILURE(status);
     auto pack = new TensorPack(ctx);
     if(pack == nullptr)
     {
         ARM_COMPUTE_LOG_ERROR_WITH_FUNCNAME_ACL("Couldn't allocate internal resources!");
         return AclOutOfMemory;
     }
     *external_pack = pack;
     return AclSuccess;
 }
AclDestroyTensorPack()
AclStatus AclDestroyTensorPack (AclTensorPack pack)
Destroy a given tensor pack object.
Parameters
[in,out] pack A valid tensor pack object to destroy
Returns
Status code
Returns:
AclSuccess if functions was completed successfully
AclInvalidArgument if the provided context is invalid
Definition at line 94 of file AclTensorPack.cpp.
References AclSuccess, ARM_COMPUTE_RETURN_CENUM_ON_FAILURE, arm_compute::get_internal(), arm_compute::test::validation::pack, and arm_compute::detail::validate_internal_pack().
 {
     using namespace arm_compute;
     auto       pack   = get_internal(external_pack);
     StatusCode status = detail::validate_internal_pack(pack);
     ARM_COMPUTE_RETURN_CENUM_ON_FAILURE(status);
     delete pack;
     return AclSuccess;
 }
AclPackTensor()
AclStatus AclPackTensor (AclTensorPack pack, AclTensor tensor, int32_t slot_id)
Add a tensor to a tensor pack.
Parameters
[in,out] pack Pack to append a tensor to
[in] tensor Tensor to pack
[in] slot_id Slot of the operator that the tensors corresponds to
Returns
Status code
Returns:
AclSuccess if function was completed successfully
AclOutOfMemory if there was a failure allocating memory resources
AclInvalidArgument if a given argument is invalid
Definition at line 70 of file AclTensorPack.cpp.
References AclSuccess, ARM_COMPUTE_RETURN_CENUM_ON_FAILURE, arm_compute::get_internal(), and arm_compute::detail::validate_internal_pack().
Referenced by TensorPack::add().
 {
     using namespace arm_compute;
     auto pack = get_internal(external_pack);
     ARM_COMPUTE_RETURN_CENUM_ON_FAILURE(detail::validate_internal_pack(pack));
     ARM_COMPUTE_RETURN_CENUM_ON_FAILURE(PackTensorInternal(*pack, external_tensor, slot_id));
     return AclStatus::AclSuccess;
 }
AclPackTensors()
AclStatus AclPackTensors (AclTensorPack pack, AclTensor * tensors, int32_t * slot_ids, size_t num_tensors)
A list of tensors to a tensor pack.
Parameters
[in,out] pack Pack to append the tensors to
[in] tensors Tensors to append to the pack
[in] slot_ids Slot IDs of each tensors to the operators
[in] num_tensors Number of tensors that are passed
Returns
Status code
Returns:
AclSuccess if function was completed successfully
AclOutOfMemory if there was a failure allocating memory resources
AclInvalidArgument if a given argument is invalid
Definition at line 80 of file AclTensorPack.cpp.
References AclSuccess, ARM_COMPUTE_RETURN_CENUM_ON_FAILURE, arm_compute::get_internal(), and arm_compute::detail::validate_internal_pack().
Referenced by TensorPack::add().
 {
     using namespace arm_compute;
     auto pack = get_internal(external_pack);
     ARM_COMPUTE_RETURN_CENUM_ON_FAILURE(detail::validate_internal_pack(pack));
     for(unsigned i = 0; i < num_tensors; ++i)
     {
         ARM_COMPUTE_RETURN_CENUM_ON_FAILURE(PackTensorInternal(*pack, external_tensors[i], slot_ids[i]));
     }
     return AclStatus::AclSuccess;
 }