Compute Library: scripts/clang-tidy.h File Reference
clang-tidy.h File Reference
#include <arm_neon.h>
Functions
float16x4_t vrsqrts_f16 (float16x4_t, float16x4_t)
float16x8_t vrsqrtsq_f16 (float16x8_t, float16x8_t)
float16x4_t vpmax_f16 (float16x4_t, float16x4_t)
float16x4_t vpadd_f16 (float16x4_t, float16x4_t)
float16x8_t vmulq_lane_f16 (float16x8_t, float16x4_t, const int)
float16x4_t vmul_f16 (float16x4_t, float16x4_t)
float16x4_t vadd_f16 (float16x4_t, float16x4_t)
float16x4_t vmul_lane_f16 (float16x4_t, float16x4_t, const int)
float16x4_t vmul_n_f16 (float16x4_t, float16_t)
float16x4_t vmax_f16 (float16x4_t, float16x4_t)
float16x8_t vcvtq_f16_u16 (uint16x8_t)
uint16x8_t vcvtq_u16_f16 (float16x8_t)
int16x8_t vcvtq_s16_f16 (float16x8_t)
float16x8_t vaddq_f16 (float16x8_t, float16x8_t)
float16x8_t vsubq_f16 (float16x8_t, float16x8_t)
float16x8_t vmulq_f16 (float16x8_t, float16x8_t)
float16x8_t vmulq_n_f16 (float16x8_t, float16_t)
float16x8_t vfmaq_f16 (float16x8_t, float16x8_t, float16x8_t)
uint16x8_t vcgeq_f16 (float16x8_t, float16x8_t)
uint16x8_t vcgtq_f16 (float16x8_t, float16x8_t)
float16x8_t vbslq_f16 (uint16x8_t, float16x8_t, float16x8_t)
float16x8_t vextq_f16 (float16x8_t, float16x8_t, int)
float16x8_t vabsq_f16 (float16x8_t)
uint16x8_t vcvtq_f16_s16 (float16x8_t)
float16x4_t vbsl_f16 (uint16x4_t, float16x4_t, float16x4_t)
float16x4_t vrsqrte_f16 (float16x4_t)
float16x8_t vrsqrteq_f16 (float16x8_t)
float16x8_t vfmsq_f16 (float16x8_t, float16x8_t, float16x8_t)
float16x4_t vrecpe_f16 (float16x4_t)
float16x8_t vrecpeq_f16 (float16x8_t)
float16x4_t vrecps_f16 (float16x4_t, float16x4_t)
float16x8_t vrecpsq_f16 (float16x8_t, float16x8_t)
float16x8_t vmaxq_f16 (float16x8_t, float16x8_t)
float16x8_t vminq_f16 (float16x8_t, float16x8_t)
uint16x8_t vcltq_f16 (float16x8_t, float16x8_t)
Function Documentation
vabsq_f16()
float16x8_t vabsq_f16 (float16x8_t) inline
Definition at line 120 of file clang-tidy.h.
 {
   return vdupq_n_f16(0);
 }
vadd_f16()
float16x4_t vadd_f16 (float16x4_t , float16x4_t) inline
Definition at line 40 of file clang-tidy.h.
Referenced by arm_compute::detail::accumulate_results< 3 >(), and arm_compute::vreduce().
 {
   return vdup_n_f16(0);
 }
vaddq_f16()
float16x8_t vaddq_f16 (float16x8_t , float16x8_t) inline
Definition at line 75 of file clang-tidy.h.
Referenced by arm_compute::detail::accumulate_results< 3 >(), arm_compute::detail::convolve_3x3(), arm_compute::cpu::matrix_addition_f32(), arm_compute::cpu::matrix_matrix_multiply_f32(), arm_compute::cpu::mean_stddev_normalization(), and arm_compute::vreduce().
 {
   return vdupq_n_f16(0);
 }
vbsl_f16()
float16x4_t vbsl_f16 (uint16x4_t , float16x4_t , float16x4_t) inline
Definition at line 130 of file clang-tidy.h.
 {
   return vdup_n_f16(0);
 }
vbslq_f16()
float16x8_t vbslq_f16 (uint16x8_t , float16x8_t , float16x8_t) inline
Definition at line 110 of file clang-tidy.h.
Referenced by arm_compute::vreduce().
 {
   return vdupq_n_f16(0);;
 }
vcgeq_f16()
uint16x8_t vcgeq_f16 (float16x8_t , float16x8_t) inline
Definition at line 100 of file clang-tidy.h.
 {
   return vdupq_n_u16(0);
 }
vcgtq_f16()
uint16x8_t vcgtq_f16 (float16x8_t , float16x8_t) inline
Definition at line 105 of file clang-tidy.h.
Referenced by arm_compute::vreduce().
 {
   return vdupq_n_u16(0);
 }
vcltq_f16()
uint16x8_t vcltq_f16 (float16x8_t , float16x8_t) inline
Definition at line 180 of file clang-tidy.h.
 {
    return vdupq_n_u16(0);
 }
vcvtq_f16_s16()
uint16x8_t vcvtq_f16_s16 (float16x8_t) inline
Definition at line 125 of file clang-tidy.h.
Referenced by arm_compute::vreduce().
 {
   return vdupq_n_s16(0);
 }
vcvtq_f16_u16()
float16x8_t vcvtq_f16_u16 (uint16x8_t) inline
Definition at line 60 of file clang-tidy.h.
 {
   return vdupq_n_f16(0);
 }
vcvtq_s16_f16()
int16x8_t vcvtq_s16_f16 (float16x8_t) inline
Definition at line 70 of file clang-tidy.h.
Referenced by arm_compute::vreduce().
 {
   return vdupq_n_s16(0);
 }
vcvtq_u16_f16()
uint16x8_t vcvtq_u16_f16 (float16x8_t) inline
Definition at line 65 of file clang-tidy.h.
 {
   return vdupq_n_u16(0);
 }
vextq_f16()
float16x8_t vextq_f16 (float16x8_t , float16x8_t , int) inline
Definition at line 115 of file clang-tidy.h.
Referenced by arm_compute::detail::convolve_3x3().
 {
   return vdupq_n_f16(0);
 }
vfmaq_f16()
float16x8_t vfmaq_f16 (float16x8_t , float16x8_t , float16x8_t) inline
Definition at line 95 of file clang-tidy.h.
 {
   return vdupq_n_f16(0);
 }
vfmsq_f16()
float16x8_t vfmsq_f16 (float16x8_t , float16x8_t , float16x8_t) inline
Definition at line 145 of file clang-tidy.h.
 {
    return vdupq_n_f16(0);
 }
vmax_f16()
float16x4_t vmax_f16 (float16x4_t , float16x4_t) inline
Definition at line 55 of file clang-tidy.h.
 {
   return vdup_n_f16(0);
 }
vmaxq_f16()
float16x8_t vmaxq_f16 (float16x8_t , float16x8_t) inline
Definition at line 170 of file clang-tidy.h.
 {
    return vdupq_n_f16(0);
 }
vminq_f16()
float16x8_t vminq_f16 (float16x8_t , float16x8_t) inline
Definition at line 175 of file clang-tidy.h.
 {
    return vdupq_n_f16(0);
 }
vmul_f16()
float16x4_t vmul_f16 (float16x4_t , float16x4_t) inline
Definition at line 35 of file clang-tidy.h.
Referenced by arm_compute::vreduce().
 {
   return vdup_n_f16(0);
 }
vmul_lane_f16()
float16x4_t vmul_lane_f16 (float16x4_t , float16x4_t , const int) inline
Definition at line 45 of file clang-tidy.h.
 {
   return vdup_n_f16(0);
 }
vmul_n_f16()
float16x4_t vmul_n_f16 (float16x4_t , float16_t) inline
Definition at line 50 of file clang-tidy.h.
 {
   return vdup_n_f16(0);
 }
vmulq_f16()
float16x8_t vmulq_f16 (float16x8_t , float16x8_t) inline
Definition at line 85 of file clang-tidy.h.
Referenced by arm_compute::detail::convolve_3x3(), arm_compute::cpu::matrix_addition_f32(), arm_compute::cpu::matrix_matrix_multiply_f32(), arm_compute::cpu::mean_stddev_normalization(), and arm_compute::vreduce().
 {
   return vdupq_n_f16(0);
 }
vmulq_lane_f16()
float16x8_t vmulq_lane_f16 (float16x8_t , float16x4_t , const int) inline
Definition at line 30 of file clang-tidy.h.
 {
   return vdupq_n_f16(0);
 }
vmulq_n_f16()
float16x8_t vmulq_n_f16 (float16x8_t , float16_t) inline
Definition at line 90 of file clang-tidy.h.
Referenced by arm_compute::cpu::matrix_matrix_multiply_f32().
 {
   return vdupq_n_f16(0);
 }
vpadd_f16()
float16x4_t vpadd_f16 (float16x4_t , float16x4_t) inline
Definition at line 25 of file clang-tidy.h.
Referenced by arm_compute::cpu::mean_stddev_normalization().
 {
   return vdup_n_f16(0);
 }
vpmax_f16()
float16x4_t vpmax_f16 (float16x4_t , float16x4_t) inline
Definition at line 20 of file clang-tidy.h.
 {
   return vdup_n_f16(0);
 }
vrecpe_f16()
float16x4_t vrecpe_f16 (float16x4_t) inline
Definition at line 150 of file clang-tidy.h.
Referenced by arm_compute::vreduce().
 {
    return vdup_n_f16(0);
 }
vrecpeq_f16()
float16x8_t vrecpeq_f16 (float16x8_t) inline
Definition at line 155 of file clang-tidy.h.
Referenced by arm_compute::vreduce().
 {
    return vdupq_n_f16(0);
 }
vrecps_f16()
float16x4_t vrecps_f16 (float16x4_t , float16x4_t) inline
Definition at line 160 of file clang-tidy.h.
Referenced by arm_compute::vreduce().
 {
    return vdup_n_f16(0);
 }
vrecpsq_f16()
float16x8_t vrecpsq_f16 (float16x8_t , float16x8_t) inline
Definition at line 165 of file clang-tidy.h.
Referenced by arm_compute::vreduce().
 {
    return vdupq_n_f16(0);
 }
vrsqrte_f16()
float16x4_t vrsqrte_f16 (float16x4_t) inline
Definition at line 135 of file clang-tidy.h.
Referenced by arm_compute::vreduce().
 {
    return vdup_n_f16(0);
 }
vrsqrteq_f16()
float16x8_t vrsqrteq_f16 (float16x8_t) inline
Definition at line 140 of file clang-tidy.h.
Referenced by arm_compute::vreduce().
 {
    return vdupq_n_f16(0);
 }
vrsqrts_f16()
float16x4_t vrsqrts_f16 (float16x4_t , float16x4_t) inline
Definition at line 10 of file clang-tidy.h.
Referenced by arm_compute::vreduce().
 {
   return vdup_n_f16(0);
 }
vrsqrtsq_f16()
float16x8_t vrsqrtsq_f16 (float16x8_t , float16x8_t) inline
Definition at line 15 of file clang-tidy.h.
Referenced by arm_compute::vreduce().
 {
   return vdupq_n_f16(0);
 }
vsubq_f16()
float16x8_t vsubq_f16 (float16x8_t , float16x8_t) inline
Definition at line 80 of file clang-tidy.h.
Referenced by arm_compute::cpu::mean_stddev_normalization(), and arm_compute::vreduce().
 {
   return vdupq_n_f16(0);
 }