Compute Library: DepthwiseDepthfirstMultiplier< TInput, TWeight, TOutput, TAccum, is_generic, OutputStage > Class Template Reference
DepthwiseDepthfirstMultiplier< TInput, TWeight, TOutput, TAccum, is_generic, OutputStage > Class Template Reference
#include <depthwise_depthfirst_multiplier.hpp>
Public Member Functions
DepthwiseDepthfirstMultiplier (StratType *const strat, const DepthwiseArgs &args, const OutputStage &os={})
DepthwiseDepthfirstMultiplier (DepthwiseDepthfirstMultiplier &)=delete
DepthwiseDepthfirstMultiplier & operator= (DepthwiseDepthfirstMultiplier &)=delete
size_t get_storage_size (void) const override
void pack_parameters (void *buffer, const void *biases, const void *weights, size_t ld_weight_col, size_t ld_weight_row) override
size_t get_working_size_per_thread (const unsigned int n_input_channels) const override
void initialise_working_space (void *buffer, unsigned int n_input_channels) const override
void compute_tile_padded (unsigned int output_i, unsigned int output_j, unsigned int output_channel_start, unsigned int output_channel_end, const TensorSpec< const TInput *> &input, const TensorSpec< TOutput *> &output, const void *parameters, void *working_space_raw) const override
Public Member Functions inherited from DepthfirstDriver< TInput, TWeight, TOutput >
DepthfirstDriver (IDepthfirstStrategy *strategy, const DepthwiseArgs &args)
size_t get_working_size (unsigned int n_threads, unsigned int n_input_channels) const override final
Detailed Description
template<typename TInput, typename TWeight = TInput, typename TOutput = TInput, typename TAccum = typename DefaultTAccum<TInput>::Type, bool is_generic = false, typename OutputStage = typename DefaultOutputStage<TOutput>::Type>
class arm_conv::depthwise::DepthwiseDepthfirstMultiplier< TInput, TWeight, TOutput, TAccum, is_generic, OutputStage >
Definition at line 476 of file depthwise_depthfirst_multiplier.hpp.
Constructor & Destructor Documentation
DepthwiseDepthfirstMultiplier() [1/2]
DepthwiseDepthfirstMultiplier (StratType *const strat, const DepthwiseArgs & args, const OutputStage & os = {}) inline
Definition at line 491 of file depthwise_depthfirst_multiplier.hpp.
                                                                                                            {})
   : DepthfirstDriver<TInput, TWeight, TOutput>(strat, args), m_os(os)
   {
   }
DepthwiseDepthfirstMultiplier() [2/2]
DepthwiseDepthfirstMultiplier (DepthwiseDepthfirstMultiplier< TInput, TWeight, TOutput, TAccum, is_generic, OutputStage > &) delete
Member Function Documentation
compute_tile_padded()
void compute_tile_padded (unsigned int output_i, unsigned int output_j, unsigned int output_channel_start, unsigned int output_channel_end, const TensorSpec< const TInput *> & input, const TensorSpec< TOutput *> & output, const void * parameters, void * working_space_raw) const inline override virtual
Implements DepthfirstDriver< TInput, TWeight, TOutput >.
Definition at line 527 of file depthwise_depthfirst_multiplier.hpp.
References TensorSpec< T >::base, StrategyType< IsGeneric, TInput, TWeight, TOutput, TAccum, OutputStage >::execute(), arm_conv::addressing::fill_pointer_array(), DepthfirstMultiplierStrategy< TInput, TWeight, TOutput, TAccum >::get_storage_size(), TensorSpec< T >::ld_col, TensorSpec< T >::ld_row, arm_compute::test::validation::n, and arm_compute::test::parameters.
   {
     // Get the working space
     auto ws = reinterpret_cast<WorkingSpace *>(working_space_raw);
     const int ii = static_cast<int>(output_i * this->m_args.stride_rows) - this->m_args.padding.top;
     const auto input_pad_top = static_cast<unsigned int>(ii < 0 ? -ii : 0);
     const auto input_i = static_cast<unsigned int>(ii < 0 ? 0 : ii);
     const int ij = static_cast<int>(output_j * this->m_args.stride_cols) - this->m_args.padding.left;
     const auto input_pad_left = static_cast<unsigned int>(ij < 0 ? -ij : 0);
     const auto input_j = static_cast<unsigned int>(ij < 0 ? 0 : ij);
     // Compute the output pointer array. We'll update this array after every
     // invocation of the kernel.
     fill_pointer_array(
       ws->outptr_array, this->m_strat->get_output_rows(), this->m_strat->get_output_cols(),
       output.base + output_i*output.ld_row + output_j*output.ld_col + output_channel_start,
       output.ld_row, output.ld_col,
       ws->output_buffer,
       0, this->m_args.output_rows - output_i, // Top padding, # valid rows
       0, this->m_args.output_cols - output_j  // Left padding, # valid columns
     );
     // Compute the parameter stride
     DepthwiseArgs single_iter(this->m_args);
     single_iter.input_channels = 1;
     const size_t parameter_stride = reinterpret_cast<const StratType *>(this->m_strat.get())
       ->get_storage_size(single_iter);
     for (; output_channel_start < output_channel_end;
          output_channel_start += this->m_args.channel_multiplier)
     {
       // Compute the input pointer array
       const auto input_channel = output_channel_start / this->m_args.channel_multiplier;
       // Construct the input patch
       depthfirst_multiplier::PrepareInputSample<is_generic>::execute(
         this->m_args, ws, this->m_strat.get(),
         input.base + input_channel + input_i*input.ld_row + input_j*input.ld_col, input.ld_row, input.ld_col,
         input_pad_top, this->m_args.input_rows - input_i,
         input_pad_left, this->m_args.input_cols - input_j
       );
       // Execute the kernel
       depthfirst_multiplier::StrategyType<is_generic, TInput, TWeight, TOutput, TAccum, OutputStage>::execute(
         this->m_args, ws, reinterpret_cast<const StratType *>(this->m_strat.get()), m_os, output_channel_start,
         parameters, m_bias
       );
       // Update the output pointers
       for (unsigned int n = 0; n < this->m_strat->get_output_rows() * this->m_strat->get_output_cols(); n++)
       {
         ws->outptr_array[n] += this->m_args.channel_multiplier;
       }
       // Progress the parameters
       parameters = reinterpret_cast<const char *>(parameters) + parameter_stride;
     }
   }
get_storage_size()
size_t get_storage_size (void) const inline override
Definition at line 499 of file depthwise_depthfirst_multiplier.hpp.
References DepthfirstMultiplierStrategy< TInput, TWeight, TOutput, TAccum >::get_storage_size().
   {
     return reinterpret_cast<const StratType *>(this->m_strat.get())
       ->get_storage_size(this->m_args);
   }
get_working_size_per_thread()
size_t get_working_size_per_thread (const unsigned int n_input_channels) const inline override virtual
Implements DepthfirstDriver< TInput, TWeight, TOutput >.
Definition at line 513 of file depthwise_depthfirst_multiplier.hpp.
References GemmTuner::args.
   {
     DepthwiseArgs args(this->m_args);
     args.input_channels = n_input_channels;
     return WorkspaceManager::get_sizeof_workspace(WorkspaceArgs<IDepthfirstStrategy, OutputStage>(this->m_strat.get(), args, m_os));
   }
initialise_working_space()
void initialise_working_space (void * buffer, unsigned int n_input_channels) const inline override virtual
Implements DepthfirstDriver< TInput, TWeight, TOutput >.
Definition at line 520 of file depthwise_depthfirst_multiplier.hpp.
References GemmTuner::args.
   {
     DepthwiseArgs args(this->m_args);
     args.input_channels = n_input_channels;
     return WorkspaceManager::initialise(buffer, WorkspaceArgs<IDepthfirstStrategy, OutputStage>(this->m_strat.get(), args, m_os));
   }
operator=()
DepthwiseDepthfirstMultiplier& operator= (DepthwiseDepthfirstMultiplier< TInput, TWeight, TOutput, TAccum, is_generic, OutputStage > &) delete
pack_parameters()
void pack_parameters (void * buffer, const void * biases, const void * weights, size_t ld_weight_col, size_t ld_weight_row) inline override
Definition at line 505 of file depthwise_depthfirst_multiplier.hpp.
References DepthfirstMultiplierStrategy< TInput, TWeight, TOutput, TAccum >::pack_parameters().
   {
     reinterpret_cast<const StratType *>(this->m_strat.get())
       ->pack_parameters(this->m_args, buffer, biases, m_os, weights, ld_weight_col, ld_weight_row);
     m_bias = biases;
     depthwise_depthfirst::stash_bias(m_os, biases);
   }
The documentation for this class was generated from the following file:
src/core/NEON/kernels/arm_conv/depthwise/depthwise_depthfirst_multiplier.hpp