Compute Library: ITensorDescPack< TDesc > Class Template Reference
ITensorDescPack< TDesc > Class Template Reference
#include <ITensorDescPack.h>
Data Structures
struct PackElement
Public Member Functions
ITensorDescPack ()=default
Default Constructor.
~ITensorDescPack ()=default
ITensorDescPack (const ITensorDescPack< TDesc > &other)=default
ITensorDescPack< TDesc > & operator= (const ITensorDescPack< TDesc > &other)=default
ITensorDescPack (ITensorDescPack< TDesc > &&other)=default
ITensorDescPack< TDesc > & operator= (ITensorDescPack< TDesc > &&other)=default
ITensorDescPack (std::initializer_list< PackElement > l)
Initializer list Constructor.
void add_tensor (int id, TDesc *tensor)
Add tensor to the pack.
void add_const_tensor (int id, const TDesc *tensor)
Add const tensor to the pack.
TDesc * get_tensor (int id)
Get tensor of a given id from the pac.
const TDesc * get_const_tensor (int id) const
Get constant tensor of a given id.
void remove_tensor (int id)
Remove the tensor stored with the given id.
size_t size () const
Pack size accessor.
bool empty () const
Checks if pack is empty.
std::vector< TDesc * > get_src_tensors ()
Get the ACL_SRC_* tensors.
std::vector< const TDesc * > get_const_src_tensors () const
Get the const ACL_SRC_* tensors.
std::vector< TDesc * > get_dst_tensors ()
Get the ACL_DST_* tensors.
std::vector< const TDesc * > get_const_dst_tensors () const
Get the const ACL_DST_* tensors.
Friends
bool operator== (const ITensorDescPack< TDesc > &pack0, const ITensorDescPack< TDesc > &pack1)
Detailed Description
template<typename TDesc>
class arm_compute::experimental::dynamic_fusion::ITensorDescPack< TDesc >
Definition at line 39 of file ITensorDescPack.h.
Constructor & Destructor Documentation
ITensorDescPack() [1/4]
ITensorDescPack () default
Default Constructor.
~ITensorDescPack()
~ITensorDescPack () default
ITensorDescPack() [2/4]
ITensorDescPack (const ITensorDescPack< TDesc > & other) default
ITensorDescPack() [3/4]
ITensorDescPack (ITensorDescPack< TDesc > && other) default
ITensorDescPack() [4/4]
ITensorDescPack (std::initializer_list< PackElement > l) inline
Initializer list Constructor.
Definition at line 81 of file ITensorDescPack.h.
         : _pack{}
     {
         for(auto &e : l)
         {
             _pack[e.id] = e;
         }
     }
Member Function Documentation
add_const_tensor()
void add_const_tensor (int id, const TDesc * tensor) inline
Add const tensor to the pack.
Parameters
[in] id ID/type of the tensor to add
[in] tensor Tensor to add
Definition at line 104 of file ITensorDescPack.h.
Referenced by arm_compute::experimental::dynamic_fusion::add_op_conv2d(), arm_compute::experimental::dynamic_fusion::add_op_elementwise_op(), arm_compute::experimental::dynamic_fusion::add_op_floor(), Conv2dContent::translate(), ElementwiseContent::translate(), and FloorContent::translate().
     {
         _pack[id] = PackElement(id, tensor);
     }
add_tensor()
void add_tensor (int id, TDesc * tensor) inline
Add tensor to the pack.
Parameters
[in] id ID/type of the tensor to add
[in] tensor Tensor to add
Definition at line 94 of file ITensorDescPack.h.
     {
         _pack[id] = PackElement(id, tensor);
     }
empty()
bool empty () const inline
Checks if pack is empty.
Returns
True if empty else false
Definition at line 154 of file ITensorDescPack.h.
     {
         return _pack.empty();
     }
get_const_dst_tensors()
std::vector<const TDesc *> get_const_dst_tensors () const inline
Get the const ACL_DST_* tensors.
Returns
std::vector<const TDesc *>
Definition at line 214 of file ITensorDescPack.h.
Referenced by ClKernelGraph::add_kernel().
     {
         std::vector<const TDesc *> dst_tensors{};
         for(int id = static_cast<int>(TensorType::ACL_DST); id <= static_cast<int>(TensorType::ACL_DST_END); ++id)
         {
             auto tensor = get_const_tensor(id);
             if(tensor != nullptr)
             {
                 dst_tensors.push_back(tensor);
             }
         }
         return dst_tensors;
     }
get_const_src_tensors()
std::vector<const TDesc *> get_const_src_tensors () const inline
Get the const ACL_SRC_* tensors.
Returns
std::vector<const TDesc *>
Definition at line 180 of file ITensorDescPack.h.
Referenced by ClKernelGraph::add_kernel().
     {
         std::vector<const TDesc *> src_tensors{};
         for(int id = static_cast<int>(TensorType::ACL_SRC); id <= static_cast<int>(TensorType::ACL_SRC_END); ++id)
         {
             auto tensor = get_const_tensor(id);
             if(tensor != nullptr)
             {
                 src_tensors.push_back(tensor);
             }
         }
         return src_tensors;
     }
get_const_tensor()
const TDesc* get_const_tensor (int id) const inline
Get constant tensor of a given id.
Parameters
[in] id ID of tensor to extract
Returns
The pointer to the tensor if exist and is const else nullptr
Definition at line 125 of file ITensorDescPack.h.
Referenced by ITensorDescPack< arm_compute::experimental::dynamic_fusion::OpTensorContent >::get_const_dst_tensors(), and ITensorDescPack< arm_compute::experimental::dynamic_fusion::OpTensorContent >::get_const_src_tensors().
     {
         auto it = _pack.find(id);
         if(it != _pack.end())
         {
             return it->second.ctensor != nullptr ? it->second.ctensor : it->second.tensor;
         }
         return nullptr;
     }
get_dst_tensors()
std::vector<TDesc *> get_dst_tensors () inline
Get the ACL_DST_* tensors.
Returns
std::vector<TDesc *>
Definition at line 197 of file ITensorDescPack.h.
     {
         std::vector<TDesc *> dst_tensors{};
         for(int id = static_cast<int>(TensorType::ACL_DST); id <= static_cast<int>(TensorType::ACL_DST_END); ++id)
         {
             auto tensor = get_tensor(id);
             if(tensor != nullptr)
             {
                 dst_tensors.push_back(tensor);
             }
         }
         return dst_tensors;
     }
get_src_tensors()
std::vector<TDesc *> get_src_tensors () inline
Get the ACL_SRC_* tensors.
Returns
std::vector<TDesc *>
Definition at line 163 of file ITensorDescPack.h.
     {
         std::vector<TDesc *> src_tensors{};
         for(int id = static_cast<int>(TensorType::ACL_SRC); id <= static_cast<int>(TensorType::ACL_SRC_END); ++id)
         {
             auto tensor = get_tensor(id);
             if(tensor != nullptr)
             {
                 src_tensors.push_back(tensor);
             }
         }
         return src_tensors;
     }
get_tensor()
TDesc* get_tensor (int id) inline
Get tensor of a given id from the pac.
Parameters
[in] id ID of tensor to extract
Returns
The pointer to the tensor if exist and is non-const else nullptr
Definition at line 114 of file ITensorDescPack.h.
Referenced by ITensorDescPack< arm_compute::experimental::dynamic_fusion::OpTensorContent >::get_dst_tensors(), and ITensorDescPack< arm_compute::experimental::dynamic_fusion::OpTensorContent >::get_src_tensors().
     {
         auto it = _pack.find(id);
         return it != _pack.end() ? it->second.tensor : nullptr;
     }
operator=() [1/2]
ITensorDescPack<TDesc>& operator= (const ITensorDescPack< TDesc > & other) default
operator=() [2/2]
ITensorDescPack<TDesc>& operator= (ITensorDescPack< TDesc > && other) default
remove_tensor()
void remove_tensor (int id) inline
Remove the tensor stored with the given id.
Parameters
[in] id ID of tensor to remove
Definition at line 138 of file ITensorDescPack.h.
     {
         _pack.erase(id);
     }
size()
size_t size () const inline
Pack size accessor.
Returns
Number of tensors registered to the pack
Definition at line 146 of file ITensorDescPack.h.
     {
         return _pack.size();
     }
Friends And Related Function Documentation
operator==
bool operator== (const ITensorDescPack< TDesc > & pack0, const ITensorDescPack< TDesc > & pack1) friend
Definition at line 228 of file ITensorDescPack.h.
     {
         return pack0._pack == pack1._pack;
     }
The documentation for this class was generated from the following file:
src/core/experimental/dynamic_fusion/WorkloadImpl/ITensorDescPack.h