Compute Library: CLFlattenLayer Class Reference
CLFlattenLayer Class Reference
Basic function to execute flatten.
#include <CLFlattenLayer.h>
Public Member Functions
CLFlattenLayer ()
~CLFlattenLayer ()
Destructor.
CLFlattenLayer (const CLFlattenLayer &)=delete
Prevent instances of this class from being copied (As this class contains pointers)
CLFlattenLayer (CLFlattenLayer &&)
Default move constructor.
CLFlattenLayer & operator= (const CLFlattenLayer &)=delete
Prevent instances of this class from being copied (As this class contains pointers)
CLFlattenLayer & operator= (CLFlattenLayer &&)
Default move assignment operator.
void configure (const ICLTensor *input, ICLTensor *output)
Initialise the kernel's input and output.
void configure (const CLCompileContext &compile_context, const ICLTensor *input, ICLTensor *output)
Initialise the kernel's input and output.
void run () override
Run the kernels contained in the function.
Public Member Functions inherited from IFunction
virtual ~IFunction ()=default
Destructor.
virtual void prepare ()
Prepare the function for executing.
Static Public Member Functions
static Status validate (const ITensorInfo *input, const ITensorInfo *output)
Static function to check if given info will lead to a valid configuration of CLFlattenLayer.
Detailed Description
Basic function to execute flatten.
Definition at line 38 of file CLFlattenLayer.h.
Constructor & Destructor Documentation
CLFlattenLayer() [1/3]
CLFlattenLayer ()
Definition at line 44 of file CLFlattenLayer.cpp.
References CLFlattenLayer::operator=(), and CLFlattenLayer::~CLFlattenLayer().
     : _impl(std::make_unique<Impl>())
 {
 }
~CLFlattenLayer()
~CLFlattenLayer () default
Destructor.
Referenced by CLFlattenLayer::CLFlattenLayer().
CLFlattenLayer() [2/3]
CLFlattenLayer (const CLFlattenLayer &) delete
Prevent instances of this class from being copied (As this class contains pointers)
CLFlattenLayer() [3/3]
CLFlattenLayer (CLFlattenLayer &&) default
Default move constructor.
Member Function Documentation
configure() [1/2]
void configure (const ICLTensor * input, ICLTensor * output)
Initialise the kernel's input and output.
Valid data layouts:
All
Valid data type configurations:
src dst
All All
Parameters
[in] input First input tensor to flatten with at least 3 dimensions. The dimensions above the third will be interpreted as batches. Data types supported: All.
[out] output Output tensor with shape [w*h*d, input_batches] where: w = width input tensor, h = height input tensor and d = depth input tensor. Data type supported: same as input
Definition at line 52 of file CLFlattenLayer.cpp.
References CLKernelLibrary::get().
 {
     configure(CLKernelLibrary::get().get_compile_context(), input, output);
 }
configure() [2/2]
void configure (const CLCompileContext & compile_context, const ICLTensor * input, ICLTensor * output)
Initialise the kernel's input and output.
Parameters
[in] compile_context The compile context to be used.
[in] input First input tensor to flatten with at least 3 dimensions. The dimensions above the third will be interpreted as batches. Data types supported: All.
[out] output Output tensor with shape [w*h*d, input_batches] where: w = width input tensor, h = height input tensor and d = depth input tensor. Data type supported: same as input
Definition at line 57 of file CLFlattenLayer.cpp.
References ARM_COMPUTE_ERROR_ON_NULLPTR, arm_compute::auto_init_if_empty(), ICloneable< T >::clone(), arm_compute::misc::shape_calculator::compute_flatten_shape(), ITensor::info(), and arm_compute::test::validation::input.
 {
     ARM_COMPUTE_ERROR_ON_NULLPTR(input, output);
     _impl->src = input;
     _impl->dst = output;
     auto_init_if_empty(*output->info(), input->info()->clone()->set_tensor_shape(misc::shape_calculator::compute_flatten_shape(input->info())));
     _impl->op = std::make_unique<opencl::ClFlatten>();
     _impl->op->configure(compile_context, _impl->src->info(), _impl->dst->info());
 }
operator=() [1/2]
CLFlattenLayer& operator= (const CLFlattenLayer &) delete
Prevent instances of this class from being copied (As this class contains pointers)
Referenced by CLFlattenLayer::CLFlattenLayer().
operator=() [2/2]
CLFlattenLayer & operator= (CLFlattenLayer &&) default
Default move assignment operator.
run()
void run () override virtual
Run the kernels contained in the function.
For CPU kernels:
Multi-threading is used for the kernels which are parallelisable.
By default std::thread::hardware_concurrency() threads are used.
Note
CPPScheduler::set_num_threads() can be used to manually set the number of threads
For OpenCL kernels:
All the kernels are enqueued on the queue associated with CLScheduler.
The queue is then flushed.
Note
The function will not block until the kernels are executed. It is the user's responsibility to wait.
Will call prepare() on first run if hasn't been done
Implements IFunction.
Definition at line 79 of file CLFlattenLayer.cpp.
References arm_compute::ACL_DST, arm_compute::ACL_SRC, ITensorPack::add_tensor(), and arm_compute::test::validation::pack.
 {
     ITensorPack pack;
     pack.add_tensor(TensorType::ACL_SRC, _impl->src);
     pack.add_tensor(TensorType::ACL_DST, _impl->dst);
     _impl->op->run(pack);
 }
validate()
Status validate (const ITensorInfo * input, const ITensorInfo * output) static
Static function to check if given info will lead to a valid configuration of CLFlattenLayer.
Parameters
[in] input First input tensor to flatten with at least 3 dimensions. The dimensions above the third will be interpreted as batches. Data types supported: All.
[out] output Output tensor with shape [w*h*d, input_batches] where: w = width input tensor, h = height input tensor and d = depth input tensor. Data type supported: same as input
Returns
a status
Definition at line 68 of file CLFlattenLayer.cpp.
References ARM_COMPUTE_RETURN_ERROR_ON_MISMATCHING_SHAPES, ICloneable< T >::clone(), arm_compute::misc::shape_calculator::compute_flatten_shape(), ITensorInfo::total_size(), and ClFlatten::validate().
 {
     // Checks performed when output is configured
     if(output->total_size() != 0)
     {
         const TensorInfo tensor_info_output = input->clone()->set_tensor_shape(misc::shape_calculator::compute_flatten_shape(input));
         ARM_COMPUTE_RETURN_ERROR_ON_MISMATCHING_SHAPES(output, &tensor_info_output);
     }
     return opencl::ClFlatten::validate(input, output);
 }
The documentation for this class was generated from the following files:
arm_compute/runtime/CL/functions/CLFlattenLayer.h
src/runtime/CL/functions/CLFlattenLayer.cpp