Compute Library: NELogicalKernel Class Reference
NELogicalKernel Class Reference
Interface for the kernel to perform logical operations between two tensors.
#include <NELogicalKernel.h>
Public Member Functions
void configure (const ITensorInfo *input1, const ITensorInfo *input2, ITensorInfo *output, LogicalOperation op)
Initialise the kernel's inputs and output.
void run_op (ITensorPack &tensors, const Window &window, const ThreadInfo &info) override
Execute the kernel on the passed window.
const char * name () const override
Name of the kernel.
Public Member Functions inherited from ICPPKernel
virtual ~ICPPKernel ()=default
Default destructor.
virtual void run (const Window &window, const ThreadInfo &info)
Execute the kernel on the passed window.
virtual void run_nd (const Window &window, const ThreadInfo &info, const Window &thread_locator)
legacy compatibility layer for implemantions which do not support thread_locator In these cases we simply narrow the interface down the legacy version
virtual size_t get_mws (const CPUInfo &platform, size_t thread_count) const
Return minimum workload size of the relevant kernel.
Public Member Functions inherited from IKernel
IKernel ()
Constructor.
virtual ~IKernel ()=default
Destructor.
virtual bool is_parallelisable () const
Indicates whether or not the kernel is parallelisable.
virtual BorderSize border_size () const
The size of the border for that kernel.
const Window & window () const
The maximum window the kernel can be executed on.
bool is_window_configured () const
Function to check if the embedded window of this kernel has been configured.
Static Public Member Functions
static Status validate (const ITensorInfo *input1, const ITensorInfo *input2, const ITensorInfo *output, LogicalOperation op)
Static function to check if given info will lead to a valid configuration of NELogicalKernel.
Additional Inherited Members
Static Public Attributes inherited from ICPPKernel
static constexpr size_t default_mws = 1
Detailed Description
Interface for the kernel to perform logical operations between two tensors.
Supported logical operations:
AND
OR
NOT
Definition at line 41 of file NELogicalKernel.h.
Member Function Documentation
configure()
void configure (const ITensorInfo * input1, const ITensorInfo * input2, ITensorInfo * output, LogicalOperation op)
Initialise the kernel's inputs and output.
Parameters
[in] input1 An input tensor. Data type supported: U8.
[in] input2 An input tensor. Data type supported: U8
[out] output Output tensor. Data type supported: U8.
[out] op Logical operation to perform
Definition at line 273 of file NELogicalKernel.cpp.
References ARM_COMPUTE_ERROR_ON_NULLPTR, ARM_COMPUTE_ERROR_THROW_ON, TensorShape::broadcast_shape(), arm_compute::calculate_max_window(), ITensorInfo::data_type(), arm_compute::Not, arm_compute::set_data_type_if_unknown(), arm_compute::set_shape_if_empty(), ITensorInfo::tensor_shape(), and NELogicalKernel::validate().
 {
     ARM_COMPUTE_ERROR_ON_NULLPTR(input1, output);
     ARM_COMPUTE_ERROR_THROW_ON(validate(input1, input2, output, op));
     _op = op;
     Window      win       = calculate_max_window(*input1, Steps());
     TensorShape out_shape = input1->tensor_shape();
     if(op != LogicalOperation::Not)
     {
         ARM_COMPUTE_ERROR_ON_NULLPTR(input2);
         out_shape = TensorShape::broadcast_shape(input1->tensor_shape(), input2->tensor_shape());
         win       = calculate_max_window(out_shape, Steps());
     }
     ICPPKernel::configure(win);
     // Auto initialize if empty
     set_shape_if_empty(*output, out_shape);
     set_data_type_if_unknown(*output, input1->data_type());
 }
name()
const char * name () const override virtual
Name of the kernel.
Returns
Kernel name
Implements ICPPKernel.
Definition at line 268 of file NELogicalKernel.cpp.
 {
     return "NELogicalKernel";
 }
run_op()
void run_op (ITensorPack & tensors, const Window & window, const ThreadInfo & info) override virtual
Execute the kernel on the passed window.
Warning
If is_parallelisable() returns false then the passed window must be equal to window()
Note
The window has to be a region within the window returned by the window() method
The width of the window has to be a multiple of num_elems_processed_per_iteration().
Parameters
[in] tensors A vector containing the tensors to operate on.
[in] window Region on which to execute the kernel. (Must be a region of the window returned by window())
[in] info Info about executing thread and CPU.
Reimplemented from ICPPKernel.
Definition at line 318 of file NELogicalKernel.cpp.
References arm_compute::ACL_DST, arm_compute::ACL_SRC_0, arm_compute::ACL_SRC_1, ARM_COMPUTE_ERROR_ON, ARM_COMPUTE_ERROR_ON_INVALID_SUBWINDOW, ARM_COMPUTE_ERROR_ON_UNCONFIGURED_KERNEL, ARM_COMPUTE_UNUSED, arm_compute::test::validation::dst, ITensorPack::empty(), ITensorPack::get_const_tensor(), ITensorPack::get_tensor(), arm_compute::Not, and IKernel::window().
 {
     ARM_COMPUTE_UNUSED(info);
     ARM_COMPUTE_ERROR_ON_UNCONFIGURED_KERNEL(this);
     ARM_COMPUTE_ERROR_ON_INVALID_SUBWINDOW(INEKernel::window(), window);
     ARM_COMPUTE_ERROR_ON(tensors.empty());
     const ITensor *src0 = tensors.get_const_tensor(TensorType::ACL_SRC_0);
     const ITensor *src1 = tensors.get_const_tensor(TensorType::ACL_SRC_1);
     ITensor       *dst  = tensors.get_tensor(TensorType::ACL_DST);
     if(_op == LogicalOperation::Not)
     {
         run_unary(window, src0, dst);
     }
     else
     {
         run_binary(window, src0, src1, dst, _op);
     }
 }
validate()
Status validate (const ITensorInfo * input1, const ITensorInfo * input2, const ITensorInfo * output, LogicalOperation op) static
Static function to check if given info will lead to a valid configuration of NELogicalKernel.
Parameters
[in] input1 An input tensor. Data type supported: U8.
[in] input2 An input tensor. Data type supported: U8
[in] output Output tensor. Data type supported: U8.
[in] op Logical operation to perform
Returns
a status
Definition at line 295 of file NELogicalKernel.cpp.
References ARM_COMPUTE_RETURN_ERROR_ON, ARM_COMPUTE_RETURN_ERROR_ON_DATA_TYPE_CHANNEL_NOT_IN, ARM_COMPUTE_RETURN_ERROR_ON_MISMATCHING_DATA_TYPES, ARM_COMPUTE_RETURN_ERROR_ON_MSG, TensorShape::broadcast_shape(), arm_compute::detail::have_different_dimensions(), arm_compute::Not, ITensorInfo::tensor_shape(), TensorShape::total_size(), ITensorInfo::total_size(), arm_compute::U8, and arm_compute::Unknown.
Referenced by NELogicalKernel::configure(), NELogicalAnd::validate(), NELogicalOr::validate(), and NELogicalNot::validate().
 {
     ARM_COMPUTE_RETURN_ERROR_ON_DATA_TYPE_CHANNEL_NOT_IN(input1, 1, DataType::U8);
     ARM_COMPUTE_RETURN_ERROR_ON(op == LogicalOperation::Unknown);
     TensorShape out_shape = input1->tensor_shape();
     if(op != LogicalOperation::Not)
     {
         out_shape = TensorShape::broadcast_shape(input1->tensor_shape(), input2->tensor_shape());
         ARM_COMPUTE_RETURN_ERROR_ON_MSG(out_shape.total_size() == 0, "Inputs are not broadcast compatible");
         ARM_COMPUTE_RETURN_ERROR_ON_MISMATCHING_DATA_TYPES(input1, input2);
     }
     // Checks performed when output is configured
     if((output != nullptr) && (output->total_size() != 0))
     {
         ARM_COMPUTE_RETURN_ERROR_ON(detail::have_different_dimensions(out_shape, output->tensor_shape(), 0));
         ARM_COMPUTE_RETURN_ERROR_ON_MISMATCHING_DATA_TYPES(input1, output);
     }
     return Status{};
 }
The documentation for this class was generated from the following files:
src/core/NEON/kernels/NELogicalKernel.h
src/core/NEON/kernels/NELogicalKernel.cpp