Compute Library: SharedVarTable Class Reference
SharedVarTable Class Reference
A table of all the variables used in the kernel / blueprint Because we limit the DependencyGraph in the blueprint to a Linear Sequence for now, we only allow ** a single global variable (the accumulator) **.
#include <Common.h>
Data Structures
class Arguments
struct SharedVar
A fully realized SharedVarLink.
Public Member Functions
void add (SharedVarLink var_link, SharedVarGroup group, ClKernelArgDescriptor runtime_desc, const std::string &name="unnamed")
Create a SharedVar for a corresponding SharedVarLink (contains ArgumentID).
SharedVar get (const SharedVarLink &var_link) const
Get the SharedVar associated with var_link.
Arguments get_kernel_arguments () const
Detailed Description
A table of all the variables used in the kernel / blueprint Because we limit the DependencyGraph in the blueprint to a Linear Sequence for now, we only allow ** a single global variable (the accumulator) **.
NOTE: the order they appear in the table is the order of their "declaration" in the component code, and is also their ID NOTE: the variables all have the scope of the full kernel function
Definition at line 92 of file Common.h.
Member Function Documentation
add()
void add (SharedVarLink var_link, SharedVarGroup group, ClKernelArgDescriptor runtime_desc, const std::string & name = "unnamed") inline
Create a SharedVar for a corresponding SharedVarLink (contains ArgumentID).
If one has already been created for the SharedVarLink, simply return it instead of creating a new one
Note
: The order of insertion is important. There is one precondition: PRECOND: The components have been sorted topologically / is being traversed in topological order This ensures that all the consumer var links (Output, Automatic Links) can consume (return) the producer var links when they're referred
Definition at line 153 of file Common.h.
References SharedVarLink::arg_id, arm_compute::experimental::dynamic_fusion::Argument, ARM_COMPUTE_ERROR, ARM_COMPUTE_ERROR_ON_MSG, arm_compute::experimental::dynamic_fusion::Automatic, SharedVarLink::io, SharedVarLink::is_empty(), name, arm_compute::experimental::dynamic_fusion::Output, and arm_compute::test::validation::ss().
Referenced by ClStoreBlockBoundaryAwareKernelComponent::allocate_shared_vars(), ClDirectConvolutionKernelComponent::allocate_shared_vars(), ClFloorKernelComponent::allocate_shared_vars(), ClElementwiseKernelComponent::allocate_shared_vars(), and ClStoreIndirectWidthSelectKernelComponent::allocate_shared_vars().
     {
         ARM_COMPUTE_ERROR_ON_MSG(var_link.is_empty(), "Non-empty SharedVarLink expected");
         if(!get(var_link).is_empty())
         {
             return;
         }
         auto              var_id = _num_var;
         std::stringstream ss;
         ss << name << "_" << var_id;
         const auto uniq_name = ss.str();
         SharedVar  var{ var_link.arg_id, var_link.io, group, uniq_name, runtime_desc };
         if(group == SharedVarGroup::Argument)
         {
             _arguments.emplace(var_id, var);
             _arg_id_map.emplace(var_link.arg_id, var_id);
             _num_var++;
         }
         else if(group == SharedVarGroup::Automatic)
         {
             if(_global_vars.empty())
             {
                 if(var_link.io == SharedVarIO::Output)
                 {
                     _global_vars.emplace(var_id, var);
                     _arg_id_map.emplace(var_link.arg_id, var_id);
                     _num_var++;
                 }
                 else
                 {
                     ARM_COMPUTE_ERROR("Component likely not traversed in topological order");
                 }
             }
             else
             {
                 // Associate additional SharedVarLinks with the single global shared variable
                 const auto global_var_id     = _global_vars.begin()->first;
                 _arg_id_map[var_link.arg_id] = global_var_id;
             }
         }
         else
         {
             ARM_COMPUTE_ERROR("Unrecognised SharedVarGroup");
         }
     }
get()
SharedVar get (const SharedVarLink & var_link) const inline
Get the SharedVar associated with var_link.
Parameters
var_link
Returns
SharedVar
Definition at line 206 of file Common.h.
Referenced by ClStoreBlockBoundaryAwareKernelComponent::get_tag_lut(), ClDirectConvolutionKernelComponent::get_tag_lut(), ClFloorKernelComponent::get_tag_lut(), ClElementwiseKernelComponent::get_tag_lut(), and ClStoreIndirectWidthSelectKernelComponent::get_tag_lut().
     {
         const SharedVar empty_var{};
         if(_arg_id_map.find(var_link.arg_id) != _arg_id_map.end())
         {
             const auto var_id  = _arg_id_map.at(var_link.arg_id);
             const auto arg_var = _arguments.find(var_id);
             if(arg_var != _arguments.end())
             {
                 return arg_var->second;
             }
             else
             {
                 return _global_vars.at(var_id);
             }
         }
         return empty_var;
     }
get_kernel_arguments()
Arguments get_kernel_arguments () const inline
Note
The arguments are returned in the order they are added
Definition at line 227 of file Common.h.
References GemmTuner::args.
     {
         Arguments args{};
         for(const auto &a : _arguments)
         {
             args.add_var(a.second);
         }
         return args;
     }
The documentation for this class was generated from the following file:
src/core/experimental/dynamic_fusion/ClKernelBuildingImpl/Common.h