Compute Library: GenericDepthfirstMultiplierStrategy< TInput, TWeight, TOutput, TAccum, OutputStage > Class Template Reference
GenericDepthfirstMultiplierStrategy< TInput, TWeight, TOutput, TAccum, OutputStage > Class Template Reference
#include <depthwise_depthfirst_multiplier.hpp>
Public Member Functions
GenericDepthfirstMultiplierStrategy (KernelStrategyType *kern, const DepthwiseArgs &args)
arm_gemm::VLType get_vl_type (void) const override
const KernelStrategyType::KernelType get_kernel (void) const
size_t get_storage_size (const DepthwiseArgs &args) const override
void pack_parameters (const DepthwiseArgs &args, void *buffer, const void *biases, const OutputStage &, const void *weights, size_t ld_weight_col, size_t ld_weight_row) const override
Public Member Functions inherited from DepthwiseDepthfirstStrategyCommon< TInput, TWeight, TOutput, TAccum, OutputStage >
DepthwiseDepthfirstStrategyCommon (unsigned int output_rows, unsigned int output_cols, unsigned int kernel_rows, unsigned int kernel_cols, unsigned int stride_rows=1, unsigned int stride_cols=1)
DepthwiseDepthfirstStrategyCommon (unsigned int output_size, unsigned int kernel_size, unsigned int stride=1)
virtual ~DepthwiseDepthfirstStrategyCommon ()
unsigned int get_output_rows () const override
unsigned int get_output_cols () const override
unsigned int get_kernel_rows () const override
unsigned int get_kernel_cols () const override
unsigned int get_stride_rows () const override
unsigned int get_stride_cols () const override
Public Member Functions inherited from DepthfirstStrategyUntyped
virtual unsigned int get_input_rows () const override
virtual unsigned int get_input_cols () const override
virtual unsigned int get_n_input_points () const
virtual unsigned int get_n_output_points () const
virtual unsigned int get_n_kernel_points () const
virtual unsigned int get_accumulator_depth_vl () const
virtual bool get_kernel_packing_point (const unsigned int index, unsigned int &x, unsigned int &y) const
Public Member Functions inherited from IDepthfirstStrategy
virtual ~IDepthfirstStrategy ()=default
Detailed Description
template<typename TInput, typename TWeight = TInput, typename TOutput = TInput, typename TAccum = typename DefaultTAccum<TInput>::Type, typename OutputStage = typename DefaultOutputStage<TOutput>::Type>
class arm_conv::depthwise::GenericDepthfirstMultiplierStrategy< TInput, TWeight, TOutput, TAccum, OutputStage >
Definition at line 189 of file depthwise_depthfirst_multiplier.hpp.
Constructor & Destructor Documentation
GenericDepthfirstMultiplierStrategy()
GenericDepthfirstMultiplierStrategy (KernelStrategyType * kern, const DepthwiseArgs & args) inline
Definition at line 216 of file depthwise_depthfirst_multiplier.hpp.
   : DepthwiseDepthfirstStrategyCommon<TInput, TWeight, TOutput, TAccum, OutputStage>(
       kern->get_output_rows(), kern->get_output_cols(),
       args.kernel_rows, args.kernel_cols,
       args.stride_rows, args.stride_cols
     ),
     m_kern(kern)
   {
   };
Member Function Documentation
get_kernel()
const KernelStrategyType::KernelType get_kernel (void) const inline
Definition at line 227 of file depthwise_depthfirst_multiplier.hpp.
Referenced by StrategyType< true, TInput, TWeight, TOutput, TAccum, OutputStage >::execute(), and StrategyType< true, TInput, TWeight, TOutput, int32_t, arm_gemm::Requantize32 >::execute().
 { return m_kern->get_kernel(); }
get_storage_size()
size_t get_storage_size (const DepthwiseArgs & args) const inline override virtual
Reimplemented from DepthfirstStrategy< TInput, TWeight, TOutput, TAccum, OutputStage >.
Definition at line 229 of file depthwise_depthfirst_multiplier.hpp.
References arm_conv::depthwise::interleaves::get_storage_size_generic().
   {
     return interleaves::get_storage_size_generic(this->get_packing_args(args), args);
   }
get_vl_type()
arm_gemm::VLType get_vl_type (void) const inline override virtual
Implements DepthfirstStrategyUntyped.
Definition at line 226 of file depthwise_depthfirst_multiplier.hpp.
 { return m_kern->get_vl_type(); }
pack_parameters()
void pack_parameters (const DepthwiseArgs & args, void * buffer, const void * biases, const OutputStage & , const void * weights, size_t ld_weight_col, size_t ld_weight_row) const inline override virtual
Reimplemented from DepthfirstStrategy< TInput, TWeight, TOutput, TAccum, OutputStage >.
Definition at line 234 of file depthwise_depthfirst_multiplier.hpp.
References arm_conv::depthwise::interleaves::pack_parameters_generic().
   {
     interleaves::pack_parameters_generic(
       this->get_packing_args(args), args,
       buffer, biases, weights, ld_weight_col, ld_weight_row
     );
   }
The documentation for this class was generated from the following file:
src/core/NEON/kernels/arm_conv/depthwise/depthwise_depthfirst_multiplier.hpp