Compute Library: ClGemmReshapeRhsMatrixKernel Class Reference
ClGemmReshapeRhsMatrixKernel Class Reference
OpenCL kernel to reshape the RHS matrix when performing the matrix multiplication In particular, this kernel splits the src matrix in blocks of size K0xN0 and stores each one in the dst matrix unrolling the values.
#include <ClGemmReshapeRhsMatrixKernel.h>
Public Member Functions
ClGemmReshapeRhsMatrixKernel ()
ARM_COMPUTE_DISALLOW_COPY_ALLOW_MOVE (ClGemmReshapeRhsMatrixKernel)
void configure (const ClCompileContext &compile_context, ITensorInfo *src, ITensorInfo *dst, const GEMMRHSMatrixInfo &rhs_info)
Initialise the kernel's input and output.
void run_op (ITensorPack &tensors, const Window &window, cl::CommandQueue &queue) override
Enqueue the OpenCL kernel to process the given window on the passed OpenCL command queue.
Public Member Functions inherited from ICLKernel
ICLKernel ()
Constructor.
cl::Kernel & kernel ()
Returns a reference to the OpenCL kernel of this object.
CLKernelType type () const
Returns the CL kernel type.
template<typename T >
void add_1D_array_argument (unsigned int &idx, const ICLArray< T > *array, const Strides &strides, unsigned int num_dimensions, const Window &window)
Add the passed 1D array's parameters to the object's kernel's arguments starting from the index idx.
void add_1D_tensor_argument (unsigned int &idx, const ICLTensor *tensor, const Window &window)
Add the passed 1D tensor's parameters to the object's kernel's arguments starting from the index idx.
void add_1D_tensor_argument_if (bool cond, unsigned int &idx, const ICLTensor *tensor, const Window &window)
Add the passed 1D tensor's parameters to the object's kernel's arguments starting from the index idx if the condition is true.
void add_2D_tensor_argument (unsigned int &idx, const ICLTensor *tensor, const Window &window)
Add the passed 2D tensor's parameters to the object's kernel's arguments starting from the index idx.
void add_2D_tensor_argument_if (bool cond, unsigned int &idx, const ICLTensor *tensor, const Window &window)
Add the passed 2D tensor's parameters to the object's kernel's arguments starting from the index idx if the condition is true.
void add_3D_tensor_argument (unsigned int &idx, const ICLTensor *tensor, const Window &window)
Add the passed 3D tensor's parameters to the object's kernel's arguments starting from the index idx.
void add_4D_tensor_argument (unsigned int &idx, const ICLTensor *tensor, const Window &window)
Add the passed 4D tensor's parameters to the object's kernel's arguments starting from the index idx.
void add_5D_tensor_argument (unsigned int &idx, const ICLTensor *tensor, const Window &window)
Add the passed 5D tensor's parameters to the object's kernel's arguments starting from the index idx.
void add_3d_tensor_nhw_argument (unsigned int &idx, const ICLTensor *tensor)
Add the passed NHW 3D tensor's parameters to the object's kernel's arguments by passing strides, dimensions and the offset to the first valid element in bytes.
void add_4d_tensor_nhwc_argument (unsigned int &idx, const ICLTensor *tensor)
Add the passed NHWC 4D tensor's parameters to the object's kernel's arguments by passing strides, dimensions and the offset to the first valid element in bytes.
virtual void run (const Window &window, cl::CommandQueue &queue)
Enqueue the OpenCL kernel to process the given window on the passed OpenCL command queue.
virtual void run_composite_op (ITensorPack &tensors, const Window &window, cl::CommandQueue &queue, const experimental::dynamic_fusion::ClExecutionDescriptor &exec_desc)
The execution is carried out through run_op method. But the run_op method needs to be extended to include ClExecutionDescriptor as now LWS GWS tuning will be separated from the IKernel.
template<typename T >
void add_argument (unsigned int &idx, T value)
Add the passed parameters to the object's kernel's arguments starting from the index idx.
void set_lws_hint (const cl::NDRange &lws_hint)
Set the Local-Workgroup-Size hint.
cl::NDRange lws_hint () const
Return the Local-Workgroup-Size hint.
void set_wbsm_hint (const cl_int &wbsm_hint)
Set the workgroup batch size modifier hint.
cl_int wbsm_hint () const
Return the workgroup batch size modifier hint.
const std::string & config_id () const
Get the configuration ID.
void set_target (GPUTarget target)
Set the targeted GPU architecture.
void set_target (cl::Device &device)
Set the targeted GPU architecture according to the CL device.
GPUTarget get_target () const
Get the targeted GPU architecture.
size_t get_max_workgroup_size ()
Get the maximum workgroup size for the device the CLKernelLibrary uses.
template<unsigned int dimension_size>
void add_tensor_argument (unsigned &idx, const ICLTensor *tensor, const Window &window)
template<typename T , unsigned int dimension_size>
void add_array_argument (unsigned &idx, const ICLArray< T > *array, const Strides &strides, unsigned int num_dimensions, const Window &window)
Add the passed array's parameters to the object's kernel's arguments starting from the index idx.
Public Member Functions inherited from IKernel
IKernel ()
Constructor.
virtual ~IKernel ()=default
Destructor.
virtual bool is_parallelisable () const
Indicates whether or not the kernel is parallelisable.
virtual BorderSize border_size () const
The size of the border for that kernel.
const Window & window () const
The maximum window the kernel can be executed on.
bool is_window_configured () const
Function to check if the embedded window of this kernel has been configured.
Static Public Member Functions
static Status validate (const ITensorInfo *src, const ITensorInfo *dst, const GEMMRHSMatrixInfo &rhs_info)
Static function to check if given info will lead to a valid configuration.
Static Public Member Functions inherited from ICLKernel
static constexpr unsigned int num_arguments_per_3d_tensor_nhw ()
Returns the number of arguments enqueued per NHW 3D Tensor object.
static constexpr unsigned int num_arguments_per_4d_tensor_nhwc ()
Returns the number of arguments enqueued per NHWC 4D Tensor object.
static constexpr unsigned int num_arguments_per_1D_array ()
Returns the number of arguments enqueued per 1D array object.
static constexpr unsigned int num_arguments_per_1D_tensor ()
Returns the number of arguments enqueued per 1D tensor object.
static constexpr unsigned int num_arguments_per_2D_tensor ()
Returns the number of arguments enqueued per 2D tensor object.
static constexpr unsigned int num_arguments_per_3D_tensor ()
Returns the number of arguments enqueued per 3D tensor object.
static constexpr unsigned int num_arguments_per_4D_tensor ()
Returns the number of arguments enqueued per 4D tensor object.
static cl::NDRange gws_from_window (const Window &window)
Get the global work size given an execution window.
Detailed Description
OpenCL kernel to reshape the RHS matrix when performing the matrix multiplication In particular, this kernel splits the src matrix in blocks of size K0xN0 and stores each one in the dst matrix unrolling the values.
Definition at line 40 of file ClGemmReshapeRhsMatrixKernel.h.
Constructor & Destructor Documentation
ClGemmReshapeRhsMatrixKernel()
ClGemmReshapeRhsMatrixKernel ()
Definition at line 110 of file ClGemmReshapeRhsMatrixKernel.cpp.
References arm_compute::ELEMENTWISE.
 {
     _type = CLKernelType::ELEMENTWISE;
 }
Member Function Documentation
ARM_COMPUTE_DISALLOW_COPY_ALLOW_MOVE()
ARM_COMPUTE_DISALLOW_COPY_ALLOW_MOVE (ClGemmReshapeRhsMatrixKernel)
configure()
void configure (const ClCompileContext & compile_context, ITensorInfo * src, ITensorInfo * dst, const GEMMRHSMatrixInfo & rhs_info)
Initialise the kernel's input and output.
Note
If rhs_info.export_to_cl_image = true, this OpenCL kernel will guarantee the OpenCL pitch alignment for the output tensor, required to create a OpenCL image object from buffer in ClGemmMatrixMultiplyReshapedKernel and in ClGemmMatrixMultiplyReshapedOnlyRhsKernel Since the OpenCL image object is created importing the OpenCL buffer, the following conditions are required:
rhs_info.n0 can only be 4, 8 and 16
rhs_info.k0 can only be 4, 8 and 16
Data type can only be F32, F16
The platform should support the OpenCL cl_khr_image2d_from_buffer extension
output width should be less or equal to (CL_DEVICE_IMAGE2D_MAX_WIDTH * 4)
output (height * depth) should be less or equal to CL_DEVICE_IMAGE2D_MAX_HEIGHT
The output tensor should be only consumed by ClGemmMatrixMultiplyReshapedKernel or ClGemmMatrixMultiplyReshapedOnlyRhsKernel
Parameters
[in] compile_context The compile context to be used.
[in] src Input tensor. Data types supported: All
[out] dst Output tensor. Data type supported: same as src
[in] rhs_info RHS matrix information to be used for reshaping. This object contains all the necessary information to reshape the src tensor. Only the following values are supported: rhs_info.n0: 2,3,4,8,16 (only 4, 8 and 16 if rhs_info.export_to_cl_image == true) rhs_info.k0: 1,2,3,4,8,16 (k0 = 1 only if rhs_info.transpose = false), (only 4, 8 and 16 if rhs_info.export_to_cl_image == true) rhs_info.h0: greater than 0 rhs_info.transpose: true, false rhs_info.interleave: true, false
Definition at line 115 of file ClGemmReshapeRhsMatrixKernel.cpp.
References CLBuildOptions::add_option(), CLBuildOptions::add_option_if(), ARM_COMPUTE_ERROR_ON_NULLPTR, ARM_COMPUTE_ERROR_THROW_ON, arm_compute::create_kernel(), ITensorInfo::element_size(), arm_compute::get_cl_unsigned_type_from_element_size(), GEMMRHSMatrixInfo::h0, GEMMRHSMatrixInfo::interleave, GEMMRHSMatrixInfo::k0, kernel_name, GEMMRHSMatrixInfo::n0, ICLKernel::num_arguments_per_3d_tensor_nhw(), CLBuildOptions::options(), arm_compute::support::cpp11::to_string(), GEMMRHSMatrixInfo::transpose, arm_compute::cpu::kernels::validate_and_configure_window(), and arm_compute::cpu::kernels::validate_arguments().
Referenced by arm_compute::test::validation::DATA_TEST_CASE().
 {
     ARM_COMPUTE_ERROR_ON_NULLPTR(src, dst);
     // Perform validate step
     ARM_COMPUTE_ERROR_THROW_ON(validate_arguments(src, dst, rhs_info));
     // Create build options
     CLBuildOptions build_opts;
     build_opts.add_option("-DN0=" + support::cpp11::to_string(rhs_info.n0));
     build_opts.add_option("-DK0=" + support::cpp11::to_string(rhs_info.k0));
     build_opts.add_option_if(rhs_info.interleave, "-DINTERLEAVE");
     build_opts.add_option_if(rhs_info.transpose, "-DRESHAPE_RHS_T");
     build_opts.add_option_if(!rhs_info.transpose, "-DRESHAPE_RHS_NT");
     build_opts.add_option("-DDATA_TYPE=" + get_cl_unsigned_type_from_element_size(src->element_size()));
     std::string kernel_name("gemm_reshape_rhs_matrix_");
     kernel_name += rhs_info.transpose ? "t" : "nt";
     // Create kernel
     _kernel = create_kernel(compile_context, kernel_name, build_opts.options());
     // Configure kernel window
     auto win_config = validate_and_configure_window(src, dst, rhs_info);
     ARM_COMPUTE_ERROR_THROW_ON(win_config.first);
     ICLKernel::configure_internal(win_config.second);
     unsigned int idx = 2 * num_arguments_per_3d_tensor_nhw();
     _kernel.setArg<cl_int>(idx++, rhs_info.h0);
 }
run_op()
void run_op (ITensorPack & tensors, const Window & window, cl::CommandQueue & queue) override virtual
Enqueue the OpenCL kernel to process the given window on the passed OpenCL command queue.
Note
The queue is not flushed by this method, and therefore the kernel will not have been executed by the time this method returns.
Parameters
[in] tensors A vector containing the tensors to operato on.
[in] window Region on which to execute the kernel. (Must be a valid region of the window returned by window()).
[in,out] queue Command queue on which to enqueue the kernel.
Reimplemented from ICLKernel.
Definition at line 154 of file ClGemmReshapeRhsMatrixKernel.cpp.
References arm_compute::ACL_DST, arm_compute::ACL_SRC, ICLKernel::add_3d_tensor_nhw_argument(), ARM_COMPUTE_ERROR_ON_INVALID_SUBWINDOW, ARM_COMPUTE_ERROR_ON_NULLPTR, ARM_COMPUTE_ERROR_ON_UNCONFIGURED_KERNEL, arm_compute::enqueue(), Window::first_slice_window_3D(), ITensorPack::get_const_tensor(), ITensorPack::get_tensor(), ICLKernel::lws_hint(), arm_compute::test::validation::reference::slice(), Window::slide_window_slice_3D(), and IKernel::window().
 {
     ARM_COMPUTE_ERROR_ON_UNCONFIGURED_KERNEL(this);
     ARM_COMPUTE_ERROR_ON_INVALID_SUBWINDOW(ICLKernel::window(), window);
     const auto src = utils::cast::polymorphic_downcast<const ICLTensor *>(tensors.get_const_tensor(TensorType::ACL_SRC));
     auto       dst = utils::cast::polymorphic_downcast<ICLTensor *>(tensors.get_tensor(TensorType::ACL_DST));
     ARM_COMPUTE_ERROR_ON_NULLPTR(src, dst);
     Window slice = window.first_slice_window_3D();
     do
     {
         unsigned int idx = 0;
         add_3d_tensor_nhw_argument(idx, src);
         add_3d_tensor_nhw_argument(idx, dst);
         enqueue(queue, *this, slice, lws_hint());
     }
     while(window.slide_window_slice_3D(slice));
 }
validate()
Status validate (const ITensorInfo * src, const ITensorInfo * dst, const GEMMRHSMatrixInfo & rhs_info) static
Static function to check if given info will lead to a valid configuration.
Similar to ClGemmReshapeRhsMatrixKernel::configure()
Returns
a status
Definition at line 146 of file ClGemmReshapeRhsMatrixKernel.cpp.
References ARM_COMPUTE_RETURN_ON_ERROR, ICloneable< T >::clone(), arm_compute::test::validation::rhs_info, arm_compute::cpu::kernels::validate_and_configure_window(), and arm_compute::cpu::kernels::validate_arguments().
Referenced by arm_compute::test::validation::DATA_TEST_CASE(), and ClGemmLowpMatrixMultiplyCore::validate().
 {
     ARM_COMPUTE_RETURN_ON_ERROR(validate_arguments(src, dst, rhs_info));
     ARM_COMPUTE_RETURN_ON_ERROR(validate_and_configure_window(src->clone().get(), dst->clone().get(), rhs_info).first);
     return Status{};
 }
The documentation for this class was generated from the following files:
src/gpu/cl/kernels/ClGemmReshapeRhsMatrixKernel.h
src/gpu/cl/kernels/ClGemmReshapeRhsMatrixKernel.cpp