Compute Library: CpuComplexMul Class Reference
CpuComplexMul Class Reference
Basic function to run kernels::CpuComplexMulKernel.
#include <CpuMul.h>
Public Member Functions
void configure (ITensorInfo *src1, ITensorInfo *src2, ITensorInfo *dst, const ActivationLayerInfo &act_info=ActivationLayerInfo())
Initialise the kernel's inputs, dst.
void run (ITensorPack &tensors) override
Run the kernels contained in the function.
Public Member Functions inherited from INEOperator
INEOperator (IRuntimeContext *ctx=nullptr)
Constructor.
INEOperator (const INEOperator &)=delete
Prevent instances of this class from being copied (As this class contains pointers)
INEOperator (INEOperator &&)=default
Default move constructor.
INEOperator & operator= (const INEOperator &)=delete
Prevent instances of this class from being copied (As this class contains pointers)
INEOperator & operator= (INEOperator &&)=default
Default move assignment operator.
~INEOperator ()
Default destructor.
void prepare (ITensorPack &constants) override
Prepare the function for executing.
MemoryRequirements workspace () const override
Return the memory requirements required by the workspace.
Public Member Functions inherited from IOperator
virtual ~IOperator ()=default
Destructor.
Static Public Member Functions
static Status validate (const ITensorInfo *src1, const ITensorInfo *src2, const ITensorInfo *dst, const ActivationLayerInfo &act_info=ActivationLayerInfo())
Static function to check if given info will lead to a valid configuration.
Detailed Description
Basic function to run kernels::CpuComplexMulKernel.
Definition at line 79 of file CpuMul.h.
Member Function Documentation
configure()
void configure (ITensorInfo * src1, ITensorInfo * src2, ITensorInfo * dst, const ActivationLayerInfo & act_info = ActivationLayerInfo())
Initialise the kernel's inputs, dst.
Parameters
[in,out] src1 First input tensor. Data types supported: F32. Number of channels supported: 2 (complex tensor). The input tensor is [in, out] because its TensorInfo might be modified inside the kernel in case of broadcasting of dimension 0.
[in,out] src2 Second input tensor. Data types supported: same as src1. Number of channels supported: same as src1. The input tensor is [in, out] because its TensorInfo might be modified inside the kernel in case of broadcasting of dimension 0.
[out] dst The dst tensor. Data types supported: same as src1. Number of channels: same as src1.
[in] act_info (Optional) Activation layer information in case of a fused activation. Currently not supported.
Definition at line 67 of file CpuMul.cpp.
References ARM_COMPUTE_LOG_PARAMS, ARM_COMPUTE_UNUSED, and arm_compute::test::validation::k.
 {
     ARM_COMPUTE_UNUSED(act_info);
     ARM_COMPUTE_LOG_PARAMS(src1, src2, dst, act_info);
     auto k = std::make_unique<kernels::CpuComplexMulKernel>();
     k->configure(src1, src2, dst);
     _kernel = std::move(k);
 }
run()
void run (ITensorPack & tensors) override virtual
Run the kernels contained in the function.
Parameters
[in] tensors Vector that contains the tensors to operate on.
Reimplemented from INEOperator.
Definition at line 77 of file CpuMul.cpp.
References ARM_COMPUTE_ERROR_ON_MSG, Window::DimY, ITensorPack::empty(), Scheduler::get(), and IScheduler::schedule_op().
 {
     ARM_COMPUTE_ERROR_ON_MSG(tensors.empty(), "No inputs provided");
     NEScheduler::get().schedule_op(_kernel.get(), Window::DimY, _kernel->window(), tensors);
 }
validate()
Status validate (const ITensorInfo * src1, const ITensorInfo * src2, const ITensorInfo * dst, const ActivationLayerInfo & act_info = ActivationLayerInfo()) static
Static function to check if given info will lead to a valid configuration.
Similar to CpuComplexMul::configure()
Returns
a status
Definition at line 61 of file CpuMul.cpp.
References ARM_COMPUTE_RETURN_ERROR_ON, ActivationLayerInfo::enabled(), and CpuComplexMulKernel::validate().
Referenced by NEComplexPixelWiseMultiplication::validate().
 {
     ARM_COMPUTE_RETURN_ERROR_ON(act_info.enabled());
     return kernels::CpuComplexMulKernel::validate(src1, src2, dst);
 }
The documentation for this class was generated from the following files:
src/cpu/operators/CpuMul.h
src/cpu/operators/CpuMul.cpp