Compute Library: AssetsLibrary Class Reference
AssetsLibrary Class Reference final
Factory class to create and fill tensors.
#include <AssetsLibrary.h>
Public Types
using RangePair = std::pair< float, float >
template<typename ResultType >
using GeneratorFunctionType = std::function< ResultType(void)>
Public Member Functions
AssetsLibrary (std::string path, std::random_device::result_type seed)
Initialises the library with a path to the assets directory.
std::string path () const
Path to assets directory used to initialise library.
std::random_device::result_type seed () const
Seed that is used to fill tensors with random values.
TensorShape get_image_shape (const std::string &name)
Provides a tensor shape for the specified image.
const RawTensor & get (const std::string &name) const
Provides a constant raw tensor for the specified image.
RawTensor get (const std::string &name)
Provides a raw tensor for the specified image.
RawTensor get (const std::string &name, DataType data_type, int num_channels=1) const
Creates an uninitialised raw tensor with the given data_type and num_channels.
const RawTensor & get (const std::string &name, Format format) const
Provides a contant raw tensor for the specified image after it has been converted to format.
RawTensor get (const std::string &name, Format format)
Provides a raw tensor for the specified image after it has been converted to format.
const RawTensor & get (const std::string &name, Channel channel) const
Provides a contant raw tensor for the specified channel after it has been extracted form the given image.
RawTensor get (const std::string &name, Channel channel)
Provides a raw tensor for the specified channel after it has been extracted form the given image.
const RawTensor & get (const std::string &name, Format format, Channel channel) const
Provides a constant raw tensor for the specified channel after it has been extracted form the given image formatted to format.
RawTensor get (const std::string &name, Format format, Channel channel)
Provides a raw tensor for the specified channel after it has been extracted form the given image formatted to format.
template<typename T , typename D >
void fill_borders_with_garbage (T &&tensor, D &&distribution, std::random_device::result_type seed_offset) const
Puts garbage values all around the tensor for testing purposes.
template<typename T , typename D >
void fill (T &&tensor, D &&distribution, std::random_device::result_type seed_offset) const
Fills the specified tensor with random values drawn from distribution.
template<typename T , typename D >
void fill_boxes (T &&tensor, D &&distribution, std::random_device::result_type seed_offset) const
template<typename T , typename D >
void fill (std::vector< T > &vec, D &&distribution, std::random_device::result_type seed_offset) const
Fills the specified raw tensor with random values drawn from distribution.
template<typename D >
void fill (RawTensor &raw, D &&distribution, std::random_device::result_type seed_offset) const
Fills the specified raw tensor with random values drawn from distribution.
template<typename T >
void fill (T &&tensor, const std::string &name, Format format) const
Fills the specified tensor with the content of the specified image converted to the given format.
void fill (RawTensor &raw, const std::string &name, Format format) const
Fills the raw tensor with the content of the specified image converted to the given format.
template<typename T >
void fill (T &&tensor, const std::string &name, Channel channel) const
Fills the specified tensor with the content of the specified channel extracted from the given image.
void fill (RawTensor &raw, const std::string &name, Channel channel) const
Fills the raw tensor with the content of the specified channel extracted from the given image.
template<typename T >
void fill (T &&tensor, const std::string &name, Format format, Channel channel) const
Fills the specified tensor with the content of the specified channel extracted from the given image after it has been converted to the given format.
void fill (RawTensor &raw, const std::string &name, Format format, Channel channel) const
Fills the raw tensor with the content of the specified channel extracted from the given image after it has been converted to the given format.
template<typename T >
void fill (T &&tensor, RawTensor raw) const
Fills the specified tensor with the content of the raw tensor.
template<typename T >
void fill_tensor_uniform (T &&tensor, std::random_device::result_type seed_offset) const
Fill a tensor with uniform distribution.
template<typename T , typename D >
void fill_tensor_uniform (T &&tensor, std::random_device::result_type seed_offset, D low, D high) const
Fill a tensor with uniform distribution.
template<typename T >
void fill_tensor_uniform_ranged (T &&tensor, std::random_device::result_type seed_offset, const std::vector< AssetsLibrary::RangePair > &excluded_range_pairs) const
Fill a tensor with uniform distribution across the specified range.
template<typename T >
void fill_layer_data (T &&tensor, std::string name) const
Fills the specified tensor with data loaded from .npy (numpy binary) in specified path.
template<typename T , typename D >
void fill_tensor_value (T &&tensor, D value) const
Fill a tensor with a constant value.
template<typename T , typename DataType >
void fill_static_values (T &&tensor, const std::vector< DataType > &values) const
Fill a tensor with a given vector with static values.
template<typename T , typename ResultType >
void fill_with_generator (T &&tensor, const GeneratorFunctionType< ResultType > &generate_value) const
Fill a tensor with a value generator function.
Detailed Description
Factory class to create and fill tensors.
Allows to initialise tensors from loaded images or by specifying the shape explicitly. Furthermore, provides methods to fill tensors with the content of loaded images or with random values.
Definition at line 59 of file AssetsLibrary.h.
Member Typedef Documentation
GeneratorFunctionType
using GeneratorFunctionType = std::function<ResultType(void)>
Definition at line 411 of file AssetsLibrary.h.
RangePair
using RangePair = std::pair<float, float>
Definition at line 62 of file AssetsLibrary.h.
Constructor & Destructor Documentation
AssetsLibrary()
AssetsLibrary (std::string path, std::random_device::result_type seed)
Initialises the library with a path to the assets directory.
Furthermore, sets the seed for the random generator to seed.
Parameters
[in] path Path to load assets from.
[in] seed Seed used to initialise the random number generator.
Definition at line 254 of file AssetsLibrary.cpp.
     : _library_path(std::move(path)),
       _seed{ seed }
 {
 }
Member Function Documentation
fill() [1/10]
void fill (T && tensor, D && distribution, std::random_device::result_type seed_offset) const
Fills the specified tensor with random values drawn from distribution.
Parameters
[in,out] tensor To be filled tensor.
[in] distribution Distribution used to fill the tensor.
[in] seed_offset The offset will be added to the global seed before initialising the random generator.
Note
The distribution has to provide operator(Generator &) which will be used to draw samples.
Definition at line 622 of file AssetsLibrary.h.
References arm_compute::test::validation::distribution(), AssetsLibrary::fill_borders_with_garbage(), AssetsLibrary::fill_with_generator(), and tensor.
Referenced by arm_compute::test::validation::utils::fill(), AssetsLibrary::fill(), AssetsLibrary::fill_tensor_uniform(), and AssetsLibrary::fill_tensor_uniform_ranged().
 {
     using ResultType = typename std::remove_reference<D>::type::result_type;
     std::mt19937 gen(_seed + seed_offset);
     GeneratorFunctionType<ResultType> number_generator = [&]()
     {
         const ResultType value = distribution(gen);
         return value;
     };
     fill_with_generator(tensor, number_generator);
     fill_borders_with_garbage(tensor, distribution, seed_offset);
 }
fill() [2/10]
void fill (std::vector< T > & vec, D && distribution, std::random_device::result_type seed_offset) const
Fills the specified raw tensor with random values drawn from distribution.
Parameters
[in,out] vec To be filled vector.
[in] distribution Distribution used to fill the tensor.
[in] seed_offset The offset will be added to the global seed before initialising the random generator.
Note
The distribution has to provide operator(Generator &) which will be used to draw samples.
Definition at line 571 of file AssetsLibrary.h.
References ARM_COMPUTE_ERROR_ON_MSG, and arm_compute::test::validation::distribution().
 {
     ARM_COMPUTE_ERROR_ON_MSG(vec.empty(), "Vector must not be empty");
     using ResultType = typename std::remove_reference<D>::type::result_type;
     std::mt19937 gen(_seed + seed_offset);
     for(size_t i = 0; i < vec.size(); ++i)
     {
         const ResultType value = distribution(gen);
         vec[i] = value;
     }
 }
fill() [3/10]
void fill (RawTensor & raw, D && distribution, std::random_device::result_type seed_offset) const
Fills the specified raw tensor with random values drawn from distribution.
Parameters
[in,out] raw To be filled raw.
[in] distribution Distribution used to fill the tensor.
[in] seed_offset The offset will be added to the global seed before initialising the random generator.
Note
The distribution has to provide operator(Generator &) which will be used to draw samples.
Definition at line 658 of file AssetsLibrary.h.
References SimpleTensor< T >::data(), SimpleTensor< T >::data_type(), arm_compute::test::validation::distribution(), SimpleTensor< T >::element_size(), offset(), SimpleTensor< T >::size(), and arm_compute::test::store_value_with_data_type().
 {
     std::mt19937 gen(_seed + seed_offset);
     for(size_t offset = 0; offset < raw.size(); offset += raw.element_size())
     {
         using ResultType       = typename std::remove_reference<D>::type::result_type;
         const ResultType value = distribution(gen);
         store_value_with_data_type(raw.data() + offset, value, raw.data_type());
     }
 }
fill() [4/10]
void fill (T && tensor, const std::string & name, Format format) const
Fills the specified tensor with the content of the specified image converted to the given format.
Parameters
[in,out] tensor To be filled tensor.
[in] name Image file used to fill the tensor.
[in] format Format of the image used to fill the tensor.
Warning
No check is performed that the specified format actually matches the format of the tensor.
Definition at line 672 of file AssetsLibrary.h.
References SimpleTensor< T >::data(), SimpleTensor< T >::element_size(), arm_compute::test::index2coord(), name, offset(), SimpleTensor< T >::shape(), SimpleTensor< T >::size(), and tensor.
 {
     const RawTensor &raw = get(name, format);
     for(size_t offset = 0; offset < raw.size(); offset += raw.element_size())
     {
         const Coordinates id = index2coord(raw.shape(), offset / raw.element_size());
         const RawTensor::value_type *const raw_ptr = raw.data() + offset;
         const auto                         out_ptr = static_cast<RawTensor::value_type *>(tensor(id));
         std::copy_n(raw_ptr, raw.element_size(), out_ptr);
     }
 }
fill() [5/10]
void fill (RawTensor & raw, const std::string & name, Format format) const
Fills the raw tensor with the content of the specified image converted to the given format.
Parameters
[in,out] raw To be filled raw tensor.
[in] name Image file used to fill the tensor.
[in] format Format of the image used to fill the tensor.
Warning
No check is performed that the specified format actually matches the format of the tensor.
Definition at line 270 of file AssetsLibrary.cpp.
References SimpleTensor< T >::data(), name, and SimpleTensor< T >::size().
 {
     //FIXME: Should be done by swapping cached buffers
     const RawTensor &src = get(name, format);
     std::copy_n(src.data(), raw.size(), raw.data());
 }
fill() [6/10]
void fill (T && tensor, const std::string & name, Channel channel) const
Fills the specified tensor with the content of the specified channel extracted from the given image.
Parameters
[in,out] tensor To be filled tensor.
[in] name Image file used to fill the tensor.
[in] channel Channel of the image used to fill the tensor.
Note
The channel has to be unambiguous so that the format can be inferred automatically.
Warning
No check is performed that the specified format actually matches the format of the tensor.
Definition at line 687 of file AssetsLibrary.h.
References AssetsLibrary::fill(), arm_compute::test::get_format_for_channel(), and tensor.
 {
     fill(std::forward<T>(tensor), name, get_format_for_channel(channel), channel);
 }
fill() [7/10]
void fill (RawTensor & raw, const std::string & name, Channel channel) const
Fills the raw tensor with the content of the specified channel extracted from the given image.
Parameters
[in,out] raw To be filled raw tensor.
[in] name Image file used to fill the tensor.
[in] channel Channel of the image used to fill the tensor.
Note
The channel has to be unambiguous so that the format can be inferred automatically.
Warning
No check is performed that the specified format actually matches the format of the tensor.
Definition at line 277 of file AssetsLibrary.cpp.
References AssetsLibrary::fill(), and arm_compute::test::get_format_for_channel().
 {
     fill(raw, name, get_format_for_channel(channel), channel);
 }
fill() [8/10]
void fill (T && tensor, const std::string & name, Format format, Channel channel) const
Fills the specified tensor with the content of the specified channel extracted from the given image after it has been converted to the given format.
Parameters
[in,out] tensor To be filled tensor.
[in] name Image file used to fill the tensor.
[in] format Format of the image used to fill the tensor.
[in] channel Channel of the image used to fill the tensor.
Warning
No check is performed that the specified format actually matches the format of the tensor.
Definition at line 693 of file AssetsLibrary.h.
References SimpleTensor< T >::data(), SimpleTensor< T >::element_size(), arm_compute::test::index2coord(), name, offset(), SimpleTensor< T >::shape(), SimpleTensor< T >::size(), and tensor.
 {
     const RawTensor &raw = get(name, format, channel);
     for(size_t offset = 0; offset < raw.size(); offset += raw.element_size())
     {
         const Coordinates id = index2coord(raw.shape(), offset / raw.element_size());
         const RawTensor::value_type *const raw_ptr = raw.data() + offset;
         const auto                         out_ptr = static_cast<RawTensor::value_type *>(tensor(id));
         std::copy_n(raw_ptr, raw.element_size(), out_ptr);
     }
 }
fill() [9/10]
void fill (RawTensor & raw, const std::string & name, Format format, Channel channel) const
Fills the raw tensor with the content of the specified channel extracted from the given image after it has been converted to the given format.
Parameters
[in,out] raw To be filled raw tensor.
[in] name Image file used to fill the tensor.
[in] format Format of the image used to fill the tensor.
[in] channel Channel of the image used to fill the tensor.
Warning
No check is performed that the specified format actually matches the format of the tensor.
Definition at line 282 of file AssetsLibrary.cpp.
References TensorCache::add(), arm_compute::B, SimpleTensor< T >::data(), arm_compute::test::validation::dst, TensorCache::find(), SimpleTensor< T >::format(), arm_compute::G, arm_compute::test::get_channel_format(), name, arm_compute::R, arm_compute::RGB888, arm_compute::S16, SimpleTensor< T >::shape(), SimpleTensor< T >::size(), arm_compute::U16, arm_compute::U32, and arm_compute::U8.
 {
     const RawTensor &src = get(name, format, channel);
     std::copy_n(src.data(), raw.size(), raw.data());
 }
fill() [10/10]
void fill (T && tensor, RawTensor raw) const
Fills the specified tensor with the content of the raw tensor.
Parameters
[in,out] tensor To be filled tensor.
[in] raw Raw tensor used to fill the tensor.
Warning
No check is performed that the specified format actually matches the format of the tensor.
Definition at line 708 of file AssetsLibrary.h.
References SimpleTensor< T >::data(), SimpleTensor< T >::element_size(), arm_compute::test::index2coord(), offset(), SimpleTensor< T >::shape(), SimpleTensor< T >::size(), and tensor.
 {
     for(size_t offset = 0; offset < raw.size(); offset += raw.element_size())
     {
         const Coordinates id = index2coord(raw.shape(), offset / raw.element_size());
         const RawTensor::value_type *const raw_ptr = raw.data() + offset;
         const auto                         out_ptr = static_cast<RawTensor::value_type *>(tensor(id));
         std::copy_n(raw_ptr, raw.element_size(), out_ptr);
     }
 }
fill_borders_with_garbage()
void fill_borders_with_garbage (T && tensor, D && distribution, std::random_device::result_type seed_offset) const
Puts garbage values all around the tensor for testing purposes.
Parameters
[in,out] tensor To be filled tensor.
[in] distribution Distribution used to fill the tensor's surroundings.
[in] seed_offset The offset will be added to the global seed before initialising the random generator.
Definition at line 506 of file AssetsLibrary.h.
References BorderSize::bottom, arm_compute::test::validation::distribution(), arm_compute::execute_window_loop(), BorderSize::left, BorderSize::right, Window::set(), arm_compute::test::validation::shape, arm_compute::test::store_value_with_data_type(), tensor, BorderSize::top, Dimensions< T >::x(), and Dimensions< T >::y().
Referenced by arm_compute::test::validation::utils::fill(), AssetsLibrary::fill(), and AssetsLibrary::fill_boxes().
 {
     const PaddingSize padding_size = tensor.padding();
     Window window;
     window.set(0, Window::Dimension(-padding_size.left, tensor.shape()[0] + padding_size.right, 1));
     if(tensor.shape().num_dimensions() > 1)
     {
         window.set(1, Window::Dimension(-padding_size.top, tensor.shape()[1] + padding_size.bottom, 1));
     }
     std::mt19937 gen(_seed + seed_offset);
     execute_window_loop(window, [&](const Coordinates & id)
     {
         TensorShape shape = tensor.shape();
         // If outside of valid region
         if(id.x() < 0 || id.x() >= static_cast<int>(shape.x()) || id.y() < 0 || id.y() >= static_cast<int>(shape.y()))
         {
             using ResultType         = typename std::remove_reference<D>::type::result_type;
             const ResultType value   = distribution(gen);
             void *const      out_ptr = tensor(id);
             store_value_with_data_type(out_ptr, value, tensor.data_type());
         }
     });
 }
fill_boxes()
void fill_boxes (T && tensor, D && distribution, std::random_device::result_type seed_offset) const
Definition at line 535 of file AssetsLibrary.h.
References arm_compute::test::validation::distribution(), arm_compute::quantization::epsilon, AssetsLibrary::fill_borders_with_garbage(), arm_compute::test::index2coord(), arm_compute::test::validation::shape, arm_compute::test::store_value_with_data_type(), tensor, and type.
 {
     using DistributionType = typename std::remove_reference<D>::type;
     using ResultType       = typename DistributionType::result_type;
     std::mt19937   gen(_seed + seed_offset);
     TensorShape    shape(tensor.shape());
     const uint32_t num_boxes = tensor.num_elements() / 4;
     // Iterate over all elements
     DistributionType size_dist{ ResultType(0.f), ResultType(1.f) };
     for(uint32_t element_idx = 0; element_idx < num_boxes * 4; element_idx += 4)
     {
         const ResultType delta   = size_dist(gen);
         const ResultType epsilon = size_dist(gen);
         const ResultType left    = distribution(gen);
         const ResultType top     = distribution(gen);
         const ResultType right   = left + delta;
         const ResultType bottom  = top + epsilon;
         const std::tuple<ResultType, ResultType, ResultType, ResultType> box(left, top, right, bottom);
         Coordinates x1              = index2coord(shape, element_idx);
         Coordinates y1              = index2coord(shape, element_idx + 1);
         Coordinates x2              = index2coord(shape, element_idx + 2);
         Coordinates y2              = index2coord(shape, element_idx + 3);
         ResultType &target_value_x1 = reinterpret_cast<ResultType *>(tensor(x1))[0];
         ResultType &target_value_y1 = reinterpret_cast<ResultType *>(tensor(y1))[0];
         ResultType &target_value_x2 = reinterpret_cast<ResultType *>(tensor(x2))[0];
         ResultType &target_value_y2 = reinterpret_cast<ResultType *>(tensor(y2))[0];
         store_value_with_data_type(&target_value_x1, std::get<0>(box), tensor.data_type());
         store_value_with_data_type(&target_value_y1, std::get<1>(box), tensor.data_type());
         store_value_with_data_type(&target_value_x2, std::get<2>(box), tensor.data_type());
         store_value_with_data_type(&target_value_y2, std::get<3>(box), tensor.data_type());
     }
     fill_borders_with_garbage(tensor, distribution, seed_offset);
 }
fill_layer_data()
void fill_layer_data (T && tensor, std::string name) const
Fills the specified tensor with data loaded from .npy (numpy binary) in specified path.
Parameters
[in,out] tensor To be filled tensor.
[in] name Data file.
Note
The numpy array stored in the binary .npy file must be row-major in the sense that it must store elements within a row consecutively in the memory, then rows within a 2D slice, then 2D slices within a 3D slice and so on. Note that it imposes no restrictions on what indexing convention is used in the numpy array. That is, the numpy array can be either fortran style or C style as long as it adheres to the rule above.
More concretely, the orders of dimensions for each style are as follows: C-style (numpy default): array[HigherDims..., Z, Y, X] Fortran style: array[X, Y, Z, HigherDims...]
Definition at line 1016 of file AssetsLibrary.h.
References arm_compute::execute_window_loop(), name, AssetsLibrary::path(), tensor, Window::use_tensor_dimensions(), and arm_compute::test::detail::validate_npy_header().
 {
 #ifdef _WIN32
     const std::string path_separator("\\");
 #else  /* _WIN32 */
     const std::string path_separator("/");
 #endif /* _WIN32 */
     const std::string path = _library_path + path_separator + name;
     // Open file
     std::ifstream stream(path, std::ios::in | std::ios::binary);
     if(!stream.good())
     {
         throw framework::FileNotFound("Could not load npy file: " + path);
     }
     validate_npy_header(stream, tensor.data_type(), tensor.shape());
     // Read data
     if(tensor.padding().empty())
     {
         // If tensor has no padding read directly from stream.
         stream.read(reinterpret_cast<char *>(tensor.data()), tensor.size());
     }
     else
     {
         // If tensor has padding accessing tensor elements through execution window.
         Window window;
         window.use_tensor_dimensions(tensor.shape());
         execute_window_loop(window, [&](const Coordinates & id)
         {
             stream.read(reinterpret_cast<char *>(tensor(id)), tensor.element_size());
         });
     }
 }
fill_static_values()
void fill_static_values (T && tensor, const std::vector< DataType > & values) const
Fill a tensor with a given vector with static values.
Parameters
[in,out] tensor To be filled tensor.
[in] values A vector containing values
To cope with various size tensors, the vector size doens't have to be the same as tensor's size. If the size of the tensor is larger than the vector, the iterator the vector will keep iterating and wrap around. If the vector is larger, values located after the required size won't be used.
Definition at line 638 of file AssetsLibrary.h.
References AssetsLibrary::fill_with_generator(), and tensor.
 {
     auto                            it             = values.begin();
     GeneratorFunctionType<DataType> get_next_value = [&]()
     {
         const DataType value = *it;
         ++it;
         if(it == values.end())
         {
             it = values.begin();
         }
         return value;
     };
     fill_with_generator(tensor, get_next_value);
 }
fill_tensor_uniform() [1/2]
void fill_tensor_uniform (T && tensor, std::random_device::result_type seed_offset) const
Fill a tensor with uniform distribution.
Parameters
[in,out] tensor To be filled tensor.
[in] seed_offset The offset will be added to the global seed before initialising the random generator.
Definition at line 721 of file AssetsLibrary.h.
References ARM_COMPUTE_ERROR, arm_compute::BFLOAT16, arm_compute::F16, arm_compute::F32, arm_compute::F64, AssetsLibrary::fill(), arm_compute::support::cpp11::lowest(), arm_compute::QASYMM8, arm_compute::QASYMM8_SIGNED, arm_compute::QSYMM16, arm_compute::QSYMM8, arm_compute::QSYMM8_PER_CHANNEL, arm_compute::S16, arm_compute::S32, arm_compute::S64, arm_compute::S8, arm_compute::SIZET, tensor, arm_compute::U16, arm_compute::U32, arm_compute::U64, and arm_compute::U8.
Referenced by AssetsLibrary::fill_tensor_value().
 {
     switch(tensor.data_type())
     {
         case DataType::U8:
         case DataType::QASYMM8:
         {
             std::uniform_int_distribution<unsigned int> distribution_u8(std::numeric_limits<uint8_t>::lowest(), std::numeric_limits<uint8_t>::max());
             fill(tensor, distribution_u8, seed_offset);
             break;
         }
         case DataType::S8:
         case DataType::QSYMM8:
         case DataType::QSYMM8_PER_CHANNEL:
         case DataType::QASYMM8_SIGNED:
         {
             std::uniform_int_distribution<int> distribution_s8(std::numeric_limits<int8_t>::lowest(), std::numeric_limits<int8_t>::max());
             fill(tensor, distribution_s8, seed_offset);
             break;
         }
         case DataType::U16:
         {
             std::uniform_int_distribution<uint16_t> distribution_u16(std::numeric_limits<uint16_t>::lowest(), std::numeric_limits<uint16_t>::max());
             fill(tensor, distribution_u16, seed_offset);
             break;
         }
         case DataType::S16:
         case DataType::QSYMM16:
         {
             std::uniform_int_distribution<int16_t> distribution_s16(std::numeric_limits<int16_t>::lowest(), std::numeric_limits<int16_t>::max());
             fill(tensor, distribution_s16, seed_offset);
             break;
         }
         case DataType::U32:
         {
             std::uniform_int_distribution<uint32_t> distribution_u32(std::numeric_limits<uint32_t>::lowest(), std::numeric_limits<uint32_t>::max());
             fill(tensor, distribution_u32, seed_offset);
             break;
         }
         case DataType::S32:
         {
             std::uniform_int_distribution<int32_t> distribution_s32(std::numeric_limits<int32_t>::lowest(), std::numeric_limits<int32_t>::max());
             fill(tensor, distribution_s32, seed_offset);
             break;
         }
         case DataType::U64:
         {
             std::uniform_int_distribution<uint64_t> distribution_u64(std::numeric_limits<uint64_t>::lowest(), std::numeric_limits<uint64_t>::max());
             fill(tensor, distribution_u64, seed_offset);
             break;
         }
         case DataType::S64:
         {
             std::uniform_int_distribution<int64_t> distribution_s64(std::numeric_limits<int64_t>::lowest(), std::numeric_limits<int64_t>::max());
             fill(tensor, distribution_s64, seed_offset);
             break;
         }
         case DataType::BFLOAT16:
         {
             // It doesn't make sense to check [-inf, inf], so hard code it to a big number
             arm_compute::utils::uniform_real_distribution_16bit<bfloat16> distribution_bf16{ -1000.f, 1000.f };
             fill(tensor, distribution_bf16, seed_offset);
             break;
         }
         case DataType::F16:
         {
             // It doesn't make sense to check [-inf, inf], so hard code it to a big number
             arm_compute::utils::uniform_real_distribution_16bit<half> distribution_f16{ -100.f, 100.f };
             fill(tensor, distribution_f16, seed_offset);
             break;
         }
         case DataType::F32:
         {
             // It doesn't make sense to check [-inf, inf], so hard code it to a big number
             std::uniform_real_distribution<float> distribution_f32(-1000.f, 1000.f);
             fill(tensor, distribution_f32, seed_offset);
             break;
         }
         case DataType::F64:
         {
             // It doesn't make sense to check [-inf, inf], so hard code it to a big number
             std::uniform_real_distribution<double> distribution_f64(-1000.f, 1000.f);
             fill(tensor, distribution_f64, seed_offset);
             break;
         }
         case DataType::SIZET:
         {
             std::uniform_int_distribution<size_t> distribution_sizet(std::numeric_limits<size_t>::lowest(), std::numeric_limits<size_t>::max());
             fill(tensor, distribution_sizet, seed_offset);
             break;
         }
         default:
             ARM_COMPUTE_ERROR("NOT SUPPORTED!");
     }
 }
fill_tensor_uniform() [2/2]
void fill_tensor_uniform (T && tensor, std::random_device::result_type seed_offset, D low, D high) const
Fill a tensor with uniform distribution.
Parameters
[in,out] tensor To be filled tensor.
[in] seed_offset The offset will be added to the global seed before initialising the random generator.
[in] low lowest value in the range (inclusive)
[in] high highest value in the range (inclusive)
Note
low and high must be of the same type as the data type of tensor
Definition at line 913 of file AssetsLibrary.h.
References ARM_COMPUTE_ERROR, ARM_COMPUTE_ERROR_ON, arm_compute::BFLOAT16, arm_compute::F16, arm_compute::F32, arm_compute::F64, AssetsLibrary::fill(), arm_compute::QASYMM8, arm_compute::QASYMM8_SIGNED, arm_compute::QSYMM16, arm_compute::QSYMM8, arm_compute::S16, arm_compute::S32, arm_compute::S64, arm_compute::S8, arm_compute::SIZET, tensor, arm_compute::U16, arm_compute::U32, arm_compute::U64, and arm_compute::U8.
 {
     switch(tensor.data_type())
     {
         case DataType::U8:
         case DataType::QASYMM8:
         {
             ARM_COMPUTE_ERROR_ON(!(std::is_same<uint8_t, D>::value));
             std::uniform_int_distribution<uint32_t> distribution_u8(low, high);
             fill(tensor, distribution_u8, seed_offset);
             break;
         }
         case DataType::S8:
         case DataType::QSYMM8:
         case DataType::QASYMM8_SIGNED:
         {
             ARM_COMPUTE_ERROR_ON(!(std::is_same<int8_t, D>::value));
             std::uniform_int_distribution<int32_t> distribution_s8(low, high);
             fill(tensor, distribution_s8, seed_offset);
             break;
         }
         case DataType::U16:
         {
             ARM_COMPUTE_ERROR_ON(!(std::is_same<uint16_t, D>::value));
             std::uniform_int_distribution<uint16_t> distribution_u16(low, high);
             fill(tensor, distribution_u16, seed_offset);
             break;
         }
         case DataType::S16:
         case DataType::QSYMM16:
         {
             ARM_COMPUTE_ERROR_ON(!(std::is_same<int16_t, D>::value));
             std::uniform_int_distribution<int16_t> distribution_s16(low, high);
             fill(tensor, distribution_s16, seed_offset);
             break;
         }
         case DataType::U32:
         {
             ARM_COMPUTE_ERROR_ON(!(std::is_same<uint32_t, D>::value));
             std::uniform_int_distribution<uint32_t> distribution_u32(low, high);
             fill(tensor, distribution_u32, seed_offset);
             break;
         }
         case DataType::S32:
         {
             ARM_COMPUTE_ERROR_ON(!(std::is_same<int32_t, D>::value));
             std::uniform_int_distribution<int32_t> distribution_s32(low, high);
             fill(tensor, distribution_s32, seed_offset);
             break;
         }
         case DataType::U64:
         {
             ARM_COMPUTE_ERROR_ON(!(std::is_same<uint64_t, D>::value));
             std::uniform_int_distribution<uint64_t> distribution_u64(low, high);
             fill(tensor, distribution_u64, seed_offset);
             break;
         }
         case DataType::S64:
         {
             ARM_COMPUTE_ERROR_ON(!(std::is_same<int64_t, D>::value));
             std::uniform_int_distribution<int64_t> distribution_s64(low, high);
             fill(tensor, distribution_s64, seed_offset);
             break;
         }
         case DataType::BFLOAT16:
         {
             arm_compute::utils::uniform_real_distribution_16bit<bfloat16> distribution_bf16{ float(low), float(high) };
             fill(tensor, distribution_bf16, seed_offset);
             break;
         }
         case DataType::F16:
         {
             arm_compute::utils::uniform_real_distribution_16bit<half> distribution_f16{ float(low), float(high) };
             fill(tensor, distribution_f16, seed_offset);
             break;
         }
         case DataType::F32:
         {
             ARM_COMPUTE_ERROR_ON(!(std::is_same<float, D>::value));
             std::uniform_real_distribution<float> distribution_f32(low, high);
             fill(tensor, distribution_f32, seed_offset);
             break;
         }
         case DataType::F64:
         {
             ARM_COMPUTE_ERROR_ON(!(std::is_same<double, D>::value));
             std::uniform_real_distribution<double> distribution_f64(low, high);
             fill(tensor, distribution_f64, seed_offset);
             break;
         }
         case DataType::SIZET:
         {
             ARM_COMPUTE_ERROR_ON(!(std::is_same<size_t, D>::value));
             std::uniform_int_distribution<size_t> distribution_sizet(low, high);
             fill(tensor, distribution_sizet, seed_offset);
             break;
         }
         default:
             ARM_COMPUTE_ERROR("NOT SUPPORTED!");
     }
 }
fill_tensor_uniform_ranged()
void fill_tensor_uniform_ranged (T && tensor, std::random_device::result_type seed_offset, const std::vector< AssetsLibrary::RangePair > & excluded_range_pairs) const
Fill a tensor with uniform distribution across the specified range.
Parameters
[in,out] tensor To be filled tensor.
[in] seed_offset The offset will be added to the global seed before initialising the random generator.
[in] excluded_range_pairs Ranges to exclude from the generator
Definition at line 818 of file AssetsLibrary.h.
References ARM_COMPUTE_ERROR, arm_compute::BFLOAT16, arm_compute::F16, arm_compute::F32, AssetsLibrary::fill(), arm_compute::support::cpp11::lowest(), arm_compute::QASYMM8, arm_compute::QSYMM16, arm_compute::QSYMM8, arm_compute::S16, arm_compute::S32, arm_compute::S8, tensor, arm_compute::U16, arm_compute::U32, and arm_compute::U8.
 {
     using namespace arm_compute::utils::random;
     switch(tensor.data_type())
     {
         case DataType::U8:
         case DataType::QASYMM8:
         {
             const auto                          converted_pairs = detail::convert_range_pair<uint32_t>(excluded_range_pairs);
             RangedUniformDistribution<uint32_t> distribution_u8(std::numeric_limits<uint8_t>::lowest(),
                                                                 std::numeric_limits<uint8_t>::max(),
                                                                 converted_pairs);
             fill(tensor, distribution_u8, seed_offset);
             break;
         }
         case DataType::S8:
         case DataType::QSYMM8:
         {
             const auto                         converted_pairs = detail::convert_range_pair<int32_t>(excluded_range_pairs);
             RangedUniformDistribution<int32_t> distribution_s8(std::numeric_limits<int8_t>::lowest(),
                                                                std::numeric_limits<int8_t>::max(),
                                                                converted_pairs);
             fill(tensor, distribution_s8, seed_offset);
             break;
         }
         case DataType::U16:
         {
             const auto                          converted_pairs = detail::convert_range_pair<uint16_t>(excluded_range_pairs);
             RangedUniformDistribution<uint16_t> distribution_u16(std::numeric_limits<uint16_t>::lowest(),
                                                                  std::numeric_limits<uint16_t>::max(),
                                                                  converted_pairs);
             fill(tensor, distribution_u16, seed_offset);
             break;
         }
         case DataType::S16:
         case DataType::QSYMM16:
         {
             const auto                         converted_pairs = detail::convert_range_pair<int16_t>(excluded_range_pairs);
             RangedUniformDistribution<int16_t> distribution_s16(std::numeric_limits<int16_t>::lowest(),
                                                                 std::numeric_limits<int16_t>::max(),
                                                                 converted_pairs);
             fill(tensor, distribution_s16, seed_offset);
             break;
         }
         case DataType::U32:
         {
             const auto                          converted_pairs = detail::convert_range_pair<uint32_t>(excluded_range_pairs);
             RangedUniformDistribution<uint32_t> distribution_u32(std::numeric_limits<uint32_t>::lowest(),
                                                                  std::numeric_limits<uint32_t>::max(),
                                                                  converted_pairs);
             fill(tensor, distribution_u32, seed_offset);
             break;
         }
         case DataType::S32:
         {
             const auto                         converted_pairs = detail::convert_range_pair<int32_t>(excluded_range_pairs);
             RangedUniformDistribution<int32_t> distribution_s32(std::numeric_limits<int32_t>::lowest(),
                                                                 std::numeric_limits<int32_t>::max(),
                                                                 converted_pairs);
             fill(tensor, distribution_s32, seed_offset);
             break;
         }
         case DataType::BFLOAT16:
         {
             // It doesn't make sense to check [-inf, inf], so hard code it to a big number
             const auto                          converted_pairs = detail::convert_range_pair<bfloat16>(excluded_range_pairs);
             RangedUniformDistribution<bfloat16> distribution_bf16(bfloat16(-1000.f), bfloat16(1000.f), converted_pairs);
             fill(tensor, distribution_bf16, seed_offset);
             break;
         }
         case DataType::F16:
         {
             // It doesn't make sense to check [-inf, inf], so hard code it to a big number
             const auto                      converted_pairs = detail::convert_range_pair<half>(excluded_range_pairs);
             RangedUniformDistribution<half> distribution_f16(half(-100.f), half(100.f), converted_pairs);
             fill(tensor, distribution_f16, seed_offset);
             break;
         }
         case DataType::F32:
         {
             // It doesn't make sense to check [-inf, inf], so hard code it to a big number
             const auto                       converted_pairs = detail::convert_range_pair<float>(excluded_range_pairs);
             RangedUniformDistribution<float> distribution_f32(-1000.f, 1000.f, converted_pairs);
             fill(tensor, distribution_f32, seed_offset);
             break;
         }
         default:
             ARM_COMPUTE_ERROR("NOT SUPPORTED!");
     }
 }
fill_tensor_value()
void fill_tensor_value (T && tensor, D value) const
Fill a tensor with a constant value.
Parameters
[in,out] tensor To be filled tensor.
[in] value Value to be assigned to all elements of the input tensor.
Note
value must be of the same type as the data type of tensor
Definition at line 1054 of file AssetsLibrary.h.
References AssetsLibrary::fill_tensor_uniform(), and tensor.
 {
     fill_tensor_uniform(tensor, 0, value, value);
 }
fill_with_generator()
void fill_with_generator (T && tensor, const GeneratorFunctionType< ResultType > & generate_value) const
Fill a tensor with a value generator function.
Parameters
[in,out] tensor To be filled tensor.
[in] generate_value A function that generates values.
Definition at line 587 of file AssetsLibrary.h.
References arm_compute::test::index2coord(), arm_compute::NHWC, arm_compute::permute(), arm_compute::test::validation::shape, arm_compute::test::store_value_with_data_type(), tensor, and arm_compute::utils::cast::U.
Referenced by AssetsLibrary::fill(), and AssetsLibrary::fill_static_values().
 {
     const bool  is_nhwc = tensor.data_layout() == DataLayout::NHWC;
     TensorShape shape(tensor.shape());
     if(is_nhwc)
     {
         // Ensure that the equivalent tensors will be filled for both data layouts
         permute(shape, PermutationVector(1U, 2U, 0U));
     }
     // Iterate over all elements
     const uint32_t num_elements = tensor.num_elements();
     for(uint32_t element_idx = 0; element_idx < num_elements; ++element_idx)
     {
         Coordinates id = index2coord(shape, element_idx);
         if(is_nhwc)
         {
             // Write in the correct id for permuted shapes
             permute(id, PermutationVector(2U, 0U, 1U));
         }
         // Iterate over all channels
         for(int channel = 0; channel < tensor.num_channels(); ++channel)
         {
             const ResultType value        = generate_value();
             ResultType      &target_value = reinterpret_cast<ResultType *>(tensor(id))[channel];
             store_value_with_data_type(&target_value, value, tensor.data_type());
         }
     }
 }
get() [1/9]
const RawTensor & get (const std::string & name) const
Provides a constant raw tensor for the specified image.
Parameters
[in] name Image file used to look up the raw tensor.
Returns
a raw tensor for the specified image.
Definition at line 471 of file AssetsLibrary.cpp.
References arm_compute::RGB888.
 {
     //FIXME: Format should be derived from the image name. Not be fixed to RGB.
     return find_or_create_raw_tensor(name, Format::RGB888);
 }
get() [2/9]
RawTensor get (const std::string & name)
Provides a raw tensor for the specified image.
Parameters
[in] name Image file used to look up the raw tensor.
Returns
a raw tensor for the specified image.
Definition at line 477 of file AssetsLibrary.cpp.
References arm_compute::RGB888.
 {
     //FIXME: Format should be derived from the image name. Not be fixed to RGB.
     return RawTensor(find_or_create_raw_tensor(name, Format::RGB888));
 }
get() [3/9]
RawTensor get (const std::string & name, DataType data_type, int num_channels = 1) const
Creates an uninitialised raw tensor with the given data_type and num_channels.
The shape is derived from the specified image.
Parameters
[in] name Image file used to initialise the tensor.
[in] data_type Data type used to initialise the tensor.
[in] num_channels Number of channels used to initialise the tensor.
Returns
a raw tensor for the specified image.
Definition at line 483 of file AssetsLibrary.cpp.
References arm_compute::test::validation::data_type, name, and SimpleTensor< T >::shape().
 {
     const RawTensor &raw = get(name);
     return RawTensor(raw.shape(), data_type, num_channels);
 }
get() [4/9]
const RawTensor & get (const std::string & name, Format format) const
Provides a contant raw tensor for the specified image after it has been converted to format.
Parameters
[in] name Image file used to look up the raw tensor.
[in] format Format used to look up the raw tensor.
Returns
a raw tensor for the specified image.
Definition at line 490 of file AssetsLibrary.cpp.
 {
     return find_or_create_raw_tensor(name, format);
 }
get() [5/9]
RawTensor get (const std::string & name, Format format)
Provides a raw tensor for the specified image after it has been converted to format.
Parameters
[in] name Image file used to look up the raw tensor.
[in] format Format used to look up the raw tensor.
Returns
a raw tensor for the specified image.
Definition at line 495 of file AssetsLibrary.cpp.
 {
     return RawTensor(find_or_create_raw_tensor(name, format));
 }
get() [6/9]
const RawTensor & get (const std::string & name, Channel channel) const
Provides a contant raw tensor for the specified channel after it has been extracted form the given image.
Parameters
[in] name Image file used to look up the raw tensor.
[in] channel Channel used to look up the raw tensor.
Note
The channel has to be unambiguous so that the format can be inferred automatically.
Returns
a raw tensor for the specified image channel.
Definition at line 500 of file AssetsLibrary.cpp.
References arm_compute::test::get_format_for_channel(), and name.
 {
     return get(name, get_format_for_channel(channel), channel);
 }
get() [7/9]
RawTensor get (const std::string & name, Channel channel)
Provides a raw tensor for the specified channel after it has been extracted form the given image.
Parameters
[in] name Image file used to look up the raw tensor.
[in] channel Channel used to look up the raw tensor.
Note
The channel has to be unambiguous so that the format can be inferred automatically.
Returns
a raw tensor for the specified image channel.
Definition at line 505 of file AssetsLibrary.cpp.
References arm_compute::test::get_format_for_channel().
 {
     return RawTensor(get(name, get_format_for_channel(channel), channel));
 }
get() [8/9]
const RawTensor & get (const std::string & name, Format format, Channel channel) const
Provides a constant raw tensor for the specified channel after it has been extracted form the given image formatted to format.
Parameters
[in] name Image file used to look up the raw tensor.
[in] format Format used to look up the raw tensor.
[in] channel Channel used to look up the raw tensor.
Returns
a raw tensor for the specified image channel.
Definition at line 510 of file AssetsLibrary.cpp.
 {
     return find_or_create_raw_tensor(name, format, channel);
 }
get() [9/9]
RawTensor get (const std::string & name, Format format, Channel channel)
Provides a raw tensor for the specified channel after it has been extracted form the given image formatted to format.
Parameters
[in] name Image file used to look up the raw tensor.
[in] format Format used to look up the raw tensor.
[in] channel Channel used to look up the raw tensor.
Returns
a raw tensor for the specified image channel.
Definition at line 515 of file AssetsLibrary.cpp.
 {
     return RawTensor(find_or_create_raw_tensor(name, format, channel));
 }
get_image_shape()
TensorShape get_image_shape (const std::string & name)
Provides a tensor shape for the specified image.
Parameters
[in] name Image file used to look up the raw tensor.
Returns
the tensor shape for the specified image.
Definition at line 466 of file AssetsLibrary.cpp.
References SimpleTensor< T >::shape().
 {
     return load_image(name).shape();
 }
path()
std::string path () const
Path to assets directory used to initialise library.
Returns
the path to the assets directory.
Definition at line 260 of file AssetsLibrary.cpp.
Referenced by AssetsLibrary::fill_layer_data().
 {
     return _library_path;
 }
seed()
std::random_device::result_type seed () const
Seed that is used to fill tensors with random values.
Returns
the initial random seed.
Definition at line 265 of file AssetsLibrary.cpp.
 {
     return _seed;
 }
The documentation for this class was generated from the following files:
tests/AssetsLibrary.h
tests/AssetsLibrary.cpp