Compute Library: CpuGemmTranspose1xWKernel Class Reference
CpuGemmTranspose1xWKernel Class Reference
Kernel which transposes the elements of a matrix in chunks of 1xW, where W is equal to (16 / element size of the tensor)
#include <CpuGemmTranspose1xWKernel.h>
Public Member Functions
CpuGemmTranspose1xWKernel ()=default
ARM_COMPUTE_DISALLOW_COPY_ALLOW_MOVE (CpuGemmTranspose1xWKernel)
void configure (const ITensorInfo *src, ITensorInfo *dst)
Configure kernel for a given list of arguments.
void run_op (ITensorPack &tensors, const Window &window, const ThreadInfo &info) override
Execute the kernel on the passed window.
const char * name () const override
Name of the kernel.
Public Member Functions inherited from ICPPKernel
virtual ~ICPPKernel ()=default
Default destructor.
virtual void run (const Window &window, const ThreadInfo &info)
Execute the kernel on the passed window.
virtual void run_nd (const Window &window, const ThreadInfo &info, const Window &thread_locator)
legacy compatibility layer for implemantions which do not support thread_locator In these cases we simply narrow the interface down the legacy version
virtual size_t get_mws (const CPUInfo &platform, size_t thread_count) const
Return minimum workload size of the relevant kernel.
Public Member Functions inherited from IKernel
IKernel ()
Constructor.
virtual ~IKernel ()=default
Destructor.
virtual bool is_parallelisable () const
Indicates whether or not the kernel is parallelisable.
virtual BorderSize border_size () const
The size of the border for that kernel.
const Window & window () const
The maximum window the kernel can be executed on.
bool is_window_configured () const
Function to check if the embedded window of this kernel has been configured.
Static Public Member Functions
static Status validate (const ITensorInfo *src, const ITensorInfo *dst)
Static function to check if given info will lead to a valid configuration of CpuGemmTranspose1xWKernel.
Static Public Member Functions inherited from ICpuKernel< CpuGemmTranspose1xWKernel >
static const auto * get_implementation (const SelectorType &selector, KernelSelectionType selection_type=KernelSelectionType::Supported)
Micro-kernel selector.
Additional Inherited Members
Static Public Attributes inherited from ICPPKernel
static constexpr size_t default_mws = 1
Detailed Description
Kernel which transposes the elements of a matrix in chunks of 1xW, where W is equal to (16 / element size of the tensor)
Following an example of how the transposition1xW works when the input data is F32
\[ \left(\begin{array}{cccc} a00 & a01 & a02 & a03 \\ a10 & a11 & a12 & a13 \\ a20 & a21 & a22 & a23 \\ a30 & a31 & a32 & a33 \\ \end{array} \right) \rightarrow \left(\begin{array}{ccccccccccccccccc} a00 & a01 & a02 & a03 & a10 & a11 & a12 & a13 & a20 & a21 & a22 & a23 & a30 & a31 & a32 & a33 \\ \end{array} \right) \]
Following an example of how the transposition1xW works when the input data type is F16
\[ \left(\begin{array}{cccccccc} a00 & a01 & a02 & a03 & a04 & a05 & a06 & a07 \\ a10 & a11 & a12 & a13 & a14 & a15 & a16 & a17 \\ a20 & a21 & a22 & a23 & a24 & a25 & a26 & a27 \\ a30 & a31 & a32 & a33 & a34 & a35 & a36 & a37 \\ \end{array} \right) \rightarrow \left(\begin{array}{cccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccc} a00 & a01 & a02 & a03 & a04 & a05 & a06 & a07 & a10 & a11 & a12 & a13 & a14 & a15 & a16 & a17 & a20 & a21 & a22 & a23 & a24 & a25 & a26 & a27 & a30 & a31 & a32 & a33 & a34 & a35 & a36 & a37\\ \end{array} \right) \]
Note
The output matrix will have the following shape: [ height * W, ceil(width / W) ], where W = (16 / element size of the tensor)
Definition at line 71 of file CpuGemmTranspose1xWKernel.h.
Constructor & Destructor Documentation
CpuGemmTranspose1xWKernel()
CpuGemmTranspose1xWKernel () default
Member Function Documentation
ARM_COMPUTE_DISALLOW_COPY_ALLOW_MOVE()
ARM_COMPUTE_DISALLOW_COPY_ALLOW_MOVE (CpuGemmTranspose1xWKernel)
configure()
void configure (const ITensorInfo * src, ITensorInfo * dst)
Configure kernel for a given list of arguments.
Parameters
[in] src Input tensor info. Data types supported: All
[out] dst Output tensor info. Data type supported: same as src.
Definition at line 43 of file CpuGemmTranspose1xWKernel.cpp.
References ARM_COMPUTE_ERROR_ON_NULLPTR, ARM_COMPUTE_ERROR_THROW_ON, arm_compute::auto_init_if_empty(), arm_compute::calculate_max_window(), ICloneable< T >::clone(), arm_compute::misc::shape_calculator::compute_transpose1xW_with_element_size_shape(), ITensorInfo::element_size(), and CpuGemmTranspose1xWKernel::validate().
 {
     ARM_COMPUTE_ERROR_ON_NULLPTR(src, dst);
     // Output tensor auto inizialitation if not yet initialized
     auto_init_if_empty(*dst, src->clone()->set_tensor_shape(compute_transpose1xW_with_element_size_shape(*src)));
     // Perform validate step
     ARM_COMPUTE_ERROR_THROW_ON(CpuGemmTranspose1xWKernel::validate(src, dst));
     const size_t vector_size = 16 / src->element_size();
     // Configure kernel window
     Window win = calculate_max_window(*src, Steps(vector_size));
     ICPPKernel::configure(win);
 }
name()
const char * name () const override virtual
Name of the kernel.
Returns
Kernel name
Implements ICPPKernel.
Definition at line 131 of file CpuGemmTranspose1xWKernel.cpp.
 {
     return "CpuGemmTranspose1xWKernel";
 }
run_op()
void run_op (ITensorPack & tensors, const Window & window, const ThreadInfo & info) override virtual
Execute the kernel on the passed window.
Warning
If is_parallelisable() returns false then the passed window must be equal to window()
Note
The window has to be a region within the window returned by the window() method
The width of the window has to be a multiple of num_elems_processed_per_iteration().
Parameters
[in] tensors A vector containing the tensors to operate on.
[in] window Region on which to execute the kernel. (Must be a region of the window returned by window())
[in] info Info about executing thread and CPU.
Reimplemented from ICPPKernel.
Definition at line 76 of file CpuGemmTranspose1xWKernel.cpp.
References arm_compute::ACL_DST, arm_compute::ACL_SRC, ARM_COMPUTE_ERROR_ON, ARM_COMPUTE_ERROR_ON_INVALID_SUBWINDOW, ARM_COMPUTE_ERROR_ON_UNCONFIGURED_KERNEL, ARM_COMPUTE_UNUSED, ITensorInfo::dimension(), Window::DimX, Window::DimY, arm_compute::test::validation::dst, ITensorInfo::element_size(), ITensorPack::empty(), arm_compute::execute_window_loop(), ITensorPack::get_const_tensor(), ITensorPack::get_tensor(), ITensor::info(), arm_compute::test::validation::k, Iterator::ptr(), arm_compute::test::validation::src, ITensorInfo::strides_in_bytes(), and IKernel::window().
 {
     ARM_COMPUTE_UNUSED(info);
     ARM_COMPUTE_ERROR_ON_UNCONFIGURED_KERNEL(this);
     ARM_COMPUTE_ERROR_ON_INVALID_SUBWINDOW(IKernel::window(), window);
     ARM_COMPUTE_ERROR_ON(tensors.empty());
     /*
      * Following an example of how the transposition1xW works when the src data type is F32
      *
      *         |a00 a01 a02 a03|
      *         |a10 a11 a12 a13|
      *         |a20 a21 a22 a23| = | a00 a01 a02 a03 || a10 a11 a12 a13 || a20 a21 a22 a23 || a30 a31 a32 a33 |
      *         |a30 a31 a32 a33|
      *
      * The dst matrix will have the following shape: [ height * W, ceil(width / W) ], where W = (16 / element size of the tensor)
      */
     // Set window for dst tensor. Set to 0 the X and Y dimensions in order to allow multi-threading implementation and future batched matrix multiplications
     Window win_out(window);
     win_out.set(Window::DimX, Window::Dimension(0, 0, 0));
     win_out.set(Window::DimY, Window::Dimension(0, 0, 0));
     const ITensor *src = tensors.get_const_tensor(TensorType::ACL_SRC);
     ITensor       *dst = tensors.get_tensor(TensorType::ACL_DST);
     Iterator in(src, window);
     Iterator out(dst, win_out);
     const size_t in_width     = src->info()->dimension(0);
     const size_t element_size = src->info()->element_size();
     const size_t out_stride   = dst->info()->strides_in_bytes()[1];
     const size_t vector_size  = 16 / element_size;
     execute_window_loop(window, [&](const Coordinates & id)
     {
         const uint8_t *in_ptr  = in.ptr();
         uint8_t *const out_ptr = out.ptr() + (id.y() * vector_size) * element_size + (id.x() / vector_size) * out_stride;
         for(size_t k = 0; k < vector_size; ++k)
         {
             // If the src width is not multiple of W, we fill the reference with 0s
             if((id.x() + k) >= in_width)
             {
                 std::memset(out_ptr + k * element_size, 0, element_size);
             }
             else
             {
                 std::memcpy(out_ptr + k * element_size, in_ptr + k * element_size, element_size);
             }
         }
     },
     in, out);
 }
validate()
Status validate (const ITensorInfo * src, const ITensorInfo * dst) static
Static function to check if given info will lead to a valid configuration of CpuGemmTranspose1xWKernel.
Similar to CpuGemmTranspose1xWKernel::configure()
Returns
a status
Definition at line 60 of file CpuGemmTranspose1xWKernel.cpp.
References ARM_COMPUTE_RETURN_ERROR_ON, ARM_COMPUTE_RETURN_ERROR_ON_MISMATCHING_DATA_TYPES, ARM_COMPUTE_RETURN_ERROR_ON_MISMATCHING_DIMENSIONS, ARM_COMPUTE_RETURN_ERROR_ON_MISMATCHING_QUANTIZATION_INFO, ARM_COMPUTE_RETURN_ERROR_ON_NULLPTR, arm_compute::misc::shape_calculator::compute_transpose1xW_with_element_size_shape(), ITensorInfo::data_type(), ITensorInfo::tensor_shape(), ITensorInfo::total_size(), and arm_compute::UNKNOWN.
Referenced by CpuGemmTranspose1xWKernel::configure(), CpuGemm::validate(), and CpuGemmLowpMatrixMultiplyCore::validate().
 {
     ARM_COMPUTE_RETURN_ERROR_ON_NULLPTR(src);
     ARM_COMPUTE_RETURN_ERROR_ON(src->data_type() == DataType::UNKNOWN);
     //Note: ARM_COMPUTE_RETURN_ERROR_ON_CPU_F16_UNSUPPORTED(src) is not needed here as this kernel doesn't use CPU FP16 instructions.
     if(dst->total_size() != 0)
     {
         ARM_COMPUTE_RETURN_ERROR_ON_MISMATCHING_DIMENSIONS(dst->tensor_shape(), compute_transpose1xW_with_element_size_shape(*src));
         ARM_COMPUTE_RETURN_ERROR_ON_MISMATCHING_DATA_TYPES(src, dst);
         ARM_COMPUTE_RETURN_ERROR_ON_MISMATCHING_QUANTIZATION_INFO(src, dst);
     }
     return Status{};
 }
The documentation for this class was generated from the following files:
src/cpu/kernels/CpuGemmTranspose1xWKernel.h
src/cpu/kernels/CpuGemmTranspose1xWKernel.cpp