Compute Library: ClComponentDirectConv2d Class Reference
ClComponentDirectConv2d Class Reference final
#include <ClComponentDirectConv2d.h>
Public Types
using Attributes = Conv2dAttributes
Attributes are a set of backend-agnostic parameters that define what a component does.
using Settings = ClComponentDirectConv2dSettings
Settings are a set of backend-specific parameters that influence the implementation of a component.
Public Types inherited from IGpuKernelComponent
using Properties = KernelProperties
Public Member Functions
ClComponentDirectConv2d (ComponentId id, const Properties &properties, const ArgumentPack< ITensorInfo > &tensors, const Attributes &attributes, const Settings &settings)
Constructor.
~ClComponentDirectConv2d () override
Destructor.
ClComponentDirectConv2d (const ClComponentDirectConv2d &component)=delete
Prevent instances of this class from being copy constructed.
ClComponentDirectConv2d & operator= (const ClComponentDirectConv2d &component)=delete
Prevent instances of this class from being copied.
ClComponentDirectConv2d (ClComponentDirectConv2d &&component)=default
Allow instances of this class to be move constructed.
ClComponentDirectConv2d & operator= (ClComponentDirectConv2d &&component)=default
Allow instances of this class to be moved.
const IGpuTemplateComponentWriter * template_writer () const override
Get template writer for the component.
GpuComponentType type () const override
Get component type.
Public Member Functions inherited from IGpuKernelComponent
IGpuKernelComponent (ComponentId id, const Properties &properties, const ArgumentPack< ITensorInfo > &tensors)
Constructor.
virtual ~IGpuKernelComponent ()
Destructor.
ComponentId id () const
Get component id.
ArgumentPack< ITensorInfo > tensors () const
Get tensor arguments.
Properties properties () const
Get properties.
Static Public Member Functions
static Status validate (const Properties &properties, const ArgumentPack< ITensorInfo > &tensors, const Attributes &attributes, const Settings &settings)
Validate the component.
Detailed Description
Definition at line 67 of file ClComponentDirectConv2d.h.
Member Typedef Documentation
Attributes
using Attributes = Conv2dAttributes
Attributes are a set of backend-agnostic parameters that define what a component does.
Definition at line 71 of file ClComponentDirectConv2d.h.
Settings
using Settings = ClComponentDirectConv2dSettings
Settings are a set of backend-specific parameters that influence the implementation of a component.
Definition at line 73 of file ClComponentDirectConv2d.h.
Constructor & Destructor Documentation
ClComponentDirectConv2d() [1/3]
ClComponentDirectConv2d (ComponentId id, const Properties & properties, const ArgumentPack< ITensorInfo > & tensors, const Attributes & attributes, const Settings & settings)
Constructor.
Similar to ClComponentDirectConv2d::validate()
Definition at line 133 of file ClComponentDirectConv2d.cpp.
References IGpuKernelComponent::id(), IGpuKernelComponent::properties(), and IGpuKernelComponent::tensors().
     : IGpuKernelComponent{ id, properties, tensors },
       _component_writer{ std::make_unique<ClTemplateDirectConv2d>(id, tensors, attributes, settings) }
 {
 }
~ClComponentDirectConv2d()
~ClComponentDirectConv2d () override
Destructor.
Definition at line 143 of file ClComponentDirectConv2d.cpp.
 {
 }
ClComponentDirectConv2d() [2/3]
ClComponentDirectConv2d (const ClComponentDirectConv2d & component) delete
Prevent instances of this class from being copy constructed.
ClComponentDirectConv2d() [3/3]
ClComponentDirectConv2d (ClComponentDirectConv2d && component) default
Allow instances of this class to be move constructed.
Member Function Documentation
operator=() [1/2]
ClComponentDirectConv2d& operator= (const ClComponentDirectConv2d & component) delete
Prevent instances of this class from being copied.
operator=() [2/2]
ClComponentDirectConv2d& operator= (ClComponentDirectConv2d && component) default
Allow instances of this class to be moved.
template_writer()
const IGpuTemplateComponentWriter * template_writer () const override virtual
Get template writer for the component.
Implements IGpuKernelComponent.
Definition at line 146 of file ClComponentDirectConv2d.cpp.
 {
     return _component_writer.get();
 }
type()
GpuComponentType type () const inline override virtual
Get component type.
Implements IGpuKernelComponent.
Definition at line 136 of file ClComponentDirectConv2d.h.
References arm_compute::experimental::dynamic_fusion::Complex.
     {
         return GpuComponentType::Complex;
     }
validate()
Status validate (const Properties & properties, const ArgumentPack< ITensorInfo > & tensors, const Attributes & attributes, const Settings & settings) static
Validate the component.
Parameters
[in] properties Component properties
[in,out] tensors Tensor arguments to the component
[in] attributes Component attributes
[in] settings Component settings
Returns
Status Validation results
Tensor argument names:
ACL_SRC_0: Input
ACL_SRC_1: Weight
ACL_SRC_2: Bias (Optional)
ACL_DST_0: Output
Tensor argument constness:
ACL_SRC_0: Const
ACL_SRC_1: Const
ACL_SRC_2: Const
ACL_DST_0: Const
Valid data layouts:
NHWC
Valid data type configurations:
ACL_SRC_0 ACL_SRC_1 ACL_SRC_2 ACL_DST_0
F16 F16 F16 F16
F32 F32 F32 F32
Definition at line 62 of file ClComponentDirectConv2d.cpp.
References arm_compute::ACL_DST_0, arm_compute::ACL_SRC_0, arm_compute::ACL_SRC_1, arm_compute::ACL_SRC_2, ARM_COMPUTE_RETURN_ERROR_ON, ARM_COMPUTE_RETURN_ERROR_ON_DATA_LAYOUT_NOT_IN, ARM_COMPUTE_RETURN_ERROR_ON_DATA_TYPE_CHANNEL_NOT_IN, ARM_COMPUTE_RETURN_ERROR_ON_F16_UNSUPPORTED, ARM_COMPUTE_RETURN_ERROR_ON_MISMATCHING_DATA_LAYOUT, ARM_COMPUTE_RETURN_ERROR_ON_MISMATCHING_DATA_TYPES, ARM_COMPUTE_RETURN_ERROR_ON_MISMATCHING_DIMENSIONS, ARM_COMPUTE_RETURN_ERROR_ON_MSG, ARM_COMPUTE_RETURN_ERROR_ON_NULLPTR, ARM_COMPUTE_UNUSED, arm_compute::CHANNEL, arm_compute::misc::shape_calculator::compute_deep_convolution_shape(), arm_compute::test::validation::data_layout, arm_compute::test::validation::dst, arm_compute::F16, arm_compute::F32, ArgumentPack< T >::get_const_tensor(), arm_compute::get_data_layout_dimension_index(), arm_compute::NHWC, Conv2dAttributes::pad(), arm_compute::test::validation::src, and Conv2dAttributes::stride().
Referenced by GpuConv2d::validate_op().
 {
     ARM_COMPUTE_UNUSED(properties, settings);
     const auto src = tensors.get_const_tensor(TensorType::ACL_SRC_0);
     const auto wei = tensors.get_const_tensor(TensorType::ACL_SRC_1);
     const auto bia = tensors.get_const_tensor(TensorType::ACL_SRC_2);
     const auto dst = tensors.get_const_tensor(TensorType::ACL_DST_0);
     ARM_COMPUTE_RETURN_ERROR_ON_NULLPTR(src, wei, dst);
     // 1. Check validity
     // Matching data type
     ARM_COMPUTE_RETURN_ERROR_ON_MISMATCHING_DATA_TYPES(src, wei);
     ARM_COMPUTE_RETURN_ERROR_ON_MISMATCHING_DATA_TYPES(src, dst);
     if(bia != nullptr)
     {
         ARM_COMPUTE_RETURN_ERROR_ON_MISMATCHING_DATA_TYPES(src, bia);
     }
     // Matching data layout
     ARM_COMPUTE_RETURN_ERROR_ON_MISMATCHING_DATA_LAYOUT(src, wei);
     ARM_COMPUTE_RETURN_ERROR_ON_MISMATCHING_DATA_LAYOUT(src, dst);
     if(bia != nullptr)
     {
         ARM_COMPUTE_RETURN_ERROR_ON_MISMATCHING_DATA_LAYOUT(src, bia);
     }
     // All tensor infos are initialized
     ARM_COMPUTE_RETURN_ERROR_ON(src->tensor_shape().total_size() == 0);
     ARM_COMPUTE_RETURN_ERROR_ON(wei->tensor_shape().total_size() == 0);
     ARM_COMPUTE_RETURN_ERROR_ON(dst->tensor_shape().total_size() == 0);
     if(bia != nullptr)
     {
         ARM_COMPUTE_RETURN_ERROR_ON(bia->tensor_shape().total_size() == 0);
     }
     // Device requirements are met
     ARM_COMPUTE_RETURN_ERROR_ON_F16_UNSUPPORTED(src);
     // wei shape is correct
     const DataLayout data_layout = src->data_layout();
     const int        channel_idx = get_data_layout_dimension_index(data_layout, DataLayoutDimension::CHANNEL);
     ARM_COMPUTE_RETURN_ERROR_ON_MSG(wei->dimension(channel_idx) != src->dimension(channel_idx), "Weights feature map dimension should match the respective src's one");
     ARM_COMPUTE_RETURN_ERROR_ON_MSG(wei->num_dimensions() > 4, "Weights can be at most 4 dimensional");
     // dst shape is correct
     PadStrideInfo legacy_pad_stride(attributes.stride().x(), attributes.stride().y(), attributes.pad().left, attributes.pad().right, attributes.pad().top,
                                     attributes.pad().bottom, DimensionRoundingType{});
     ARM_COMPUTE_RETURN_ERROR_ON_MISMATCHING_DIMENSIONS(dst->tensor_shape(),
                                                        misc::shape_calculator::compute_deep_convolution_shape(*src, *wei, legacy_pad_stride));
     // bia shape is correct
     if(bia != nullptr)
     {
         ARM_COMPUTE_RETURN_ERROR_ON_MSG(bia->dimension(0) != wei->dimension(3),
                                         "Biases size and number of dst feature maps should match");
         ARM_COMPUTE_RETURN_ERROR_ON_MSG(bia->num_dimensions() > 1,
                                         "Biases should be one dimensional");
     }
     // 2. Check support level
     // Data type
     ARM_COMPUTE_RETURN_ERROR_ON_DATA_TYPE_CHANNEL_NOT_IN(src, 1, DataType::F16, DataType::F32);
     // Data layout
     ARM_COMPUTE_RETURN_ERROR_ON_DATA_LAYOUT_NOT_IN(src, DataLayout::NHWC);
     return Status{};
 }
The documentation for this class was generated from the following files:
src/dynamic_fusion/sketch/gpu/components/cl/ClComponentDirectConv2d.h
src/dynamic_fusion/sketch/gpu/components/cl/ClComponentDirectConv2d.cpp