Compute Library: CpuDepthwiseConv2dAssemblyDispatch Class Reference
CpuDepthwiseConv2dAssemblyDispatch Class Reference
Depthwise convolution assembly kernel glue.
#include <CpuDepthwiseConv2dAssemblyDispatch.h>
Public Member Functions
CpuDepthwiseConv2dAssemblyDispatch ()
ARM_COMPUTE_DISALLOW_COPY_ALLOW_MOVE (CpuDepthwiseConv2dAssemblyDispatch)
~CpuDepthwiseConv2dAssemblyDispatch ()
void configure (const ITensorInfo *src, const ITensorInfo *weights, const ITensorInfo *bias, ITensorInfo *dst, const ConvolutionInfo &info)
Initialize the function's source, destination, kernels and border_size.
void run (ITensorPack &tensors) override
Run the kernels contained in the function.
void prepare (ITensorPack &tensors) override
Prepare the function for executing.
experimental::MemoryRequirements workspace () const override
Return the memory requirements required by the workspace.
Public Member Functions inherited from INEOperator
INEOperator (IRuntimeContext *ctx=nullptr)
Constructor.
INEOperator (const INEOperator &)=delete
Prevent instances of this class from being copied (As this class contains pointers)
INEOperator (INEOperator &&)=default
Default move constructor.
INEOperator & operator= (const INEOperator &)=delete
Prevent instances of this class from being copied (As this class contains pointers)
INEOperator & operator= (INEOperator &&)=default
Default move assignment operator.
~INEOperator ()
Default destructor.
Public Member Functions inherited from IOperator
virtual ~IOperator ()=default
Destructor.
Static Public Member Functions
static Status validate (const ITensorInfo *src, const ITensorInfo *weights, const ITensorInfo *bias, const ITensorInfo *dst, const ConvolutionInfo &info)
Static function to check if given info will lead to a valid configuration.
static bool is_activation_supported (const ActivationLayerInfo &activation)
Checks if activation is supported by the assembly kernels.
Detailed Description
Depthwise convolution assembly kernel glue.
Definition at line 35 of file CpuDepthwiseConv2dAssemblyDispatch.h.
Constructor & Destructor Documentation
CpuDepthwiseConv2dAssemblyDispatch()
CpuDepthwiseConv2dAssemblyDispatch ()
~CpuDepthwiseConv2dAssemblyDispatch()
~CpuDepthwiseConv2dAssemblyDispatch () default
Member Function Documentation
ARM_COMPUTE_DISALLOW_COPY_ALLOW_MOVE()
ARM_COMPUTE_DISALLOW_COPY_ALLOW_MOVE (CpuDepthwiseConv2dAssemblyDispatch)
configure()
void configure (const ITensorInfo * src, const ITensorInfo * weights, const ITensorInfo * bias, ITensorInfo * dst, const ConvolutionInfo & info)
Initialize the function's source, destination, kernels and border_size.
Note
Supports only NHWC format
Parameters
[in] src Source tensor info. Data type supported: QASYMM8/QASYMM8_SIGNED/F16/F32.
[in] weights Weights tensor info. These are 3D tensors with shape [W, H, IFM]. Data type supported: same as src or QASYMM8/QASYMM8_SIGNED/QSYMM8_PER_CHANNEL when src is QASYMM8/QASYMM8_SIGNED.
[in] bias (Optional) Biases tensor info. A 1D tensor with shape [IFM]. Must be nullptr if not needed. Data type supported: same as src or S32 if src is quantized.
[out] dst Destination tensor info. Data type supported: same as src.
[in] info Depthwise convolution meta-data.
Definition at line 56 of file CpuDepthwiseConv2dAssemblyDispatch.cpp.
References arm_compute::ACL_INT_0, arm_compute::ACL_INT_1, ITensorInfo::are_values_constant(), ARM_COMPUTE_ERROR_ON, ARM_COMPUTE_LOG_PARAMS, ci, IScheduler::cpu_info(), ITensorInfo::dimension(), Scheduler::get(), IScheduler::num_threads(), and CpuDepthwiseConv2dAssemblyDispatch::validate().
 {
     ARM_COMPUTE_LOG_PARAMS(src, weights, bias, dst, info);
     const CPUInfo     &ci          = NEScheduler::get().cpu_info();
     const unsigned int num_threads = NEScheduler::get().num_threads();
     _pImpl->is_prepared            = false;
     _pImpl->are_weights_const      = weights->are_values_constant();
     // If we don't support a combination of data types, silently return: it is the caller's responsibility to check if configure() was successful via is_configured()
     if(!CpuDepthwiseConv2dAssemblyDispatch::validate(src, weights, bias, dst, info))
     {
         return;
     }
     auto dwc_wrapper = std::make_unique<kernels::CpuDepthwiseConv2dAssemblyWrapperKernel>();
     ARM_COMPUTE_ERROR_ON(dwc_wrapper == nullptr);
     dwc_wrapper->configure(src, weights, bias, dst, info, ci);
     // Compute memory requirements for assembly kernels
     constexpr size_t alignment = 4096;
     _pImpl->mem_req.push_back({ TensorType::ACL_INT_0, dwc_wrapper->get_working_size(num_threads, src->dimension(0)), alignment });
     _pImpl->mem_req.push_back({ TensorType::ACL_INT_1, dwc_wrapper->get_storage_size(), alignment });
     _pImpl->asm_kernel = std::move(dwc_wrapper);
 }
is_activation_supported()
bool is_activation_supported (const ActivationLayerInfo & activation) static
Checks if activation is supported by the assembly kernels.
Parameters
[in] activation Activation to check
Returns
True if activation is supported else false
Definition at line 95 of file CpuDepthwiseConv2dAssemblyDispatch.cpp.
References arm_compute::assembly_utils::map_to_arm_gemm_activation(), Activation::None, and Activation::type.
 {
     arm_gemm::Activation act = assembly_utils::map_to_arm_gemm_activation(activation);
     return act.type != arm_gemm::Activation::Type::None;
 }
prepare()
void prepare (ITensorPack & constants) override virtual
Prepare the function for executing.
Any one off pre-processing step required by the function is handled here
Parameters
[in] constants Vector that contains the constants tensors.
Note
Prepare stage might not need all the function's buffers' backing memory to be available in order to execute
Reimplemented from INEOperator.
Definition at line 110 of file CpuDepthwiseConv2dAssemblyDispatch.cpp.
References arm_compute::ACL_INT_1, arm_compute::ACL_SRC_1, arm_compute::ACL_SRC_2, bias, ITensor::buffer(), ITensorPack::get_const_tensor(), ITensorPack::get_tensor(), ITensor::info(), ITensor::mark_as_unused(), ITensorInfo::offset_first_element_in_bytes(), ITensorInfo::padding(), ITensorInfo::tensor_shape(), and arm_compute::test::validation::weights_shape.
 {
     const ITensor *weights = tensors.get_const_tensor(TensorType::ACL_SRC_1);
     if((!_pImpl->are_weights_const && weights != nullptr) || !_pImpl->is_prepared)
     {
         // Pack weights and bias
         const ITensor *bias    = tensors.get_const_tensor(TensorType::ACL_SRC_2);
         ITensor       *storage = tensors.get_tensor(TensorType::ACL_INT_1);
         const auto weights_ptr    = weights->buffer() + weights->info()->offset_first_element_in_bytes();
         const auto bias_ptr       = (bias) ? bias->buffer() + bias->info()->offset_first_element_in_bytes() : nullptr;
         auto       parameters_ptr = storage->buffer() + storage->info()->offset_first_element_in_bytes();
         const auto weights_shape   = weights->info()->tensor_shape();
         const auto weights_padding = weights->info()->padding();
         const size_t ld_weights_col = weights_shape[0] + weights_padding.left + weights_padding.right;
         const size_t ld_weights_row = ld_weights_col * (weights_shape[1] + weights_padding.top + weights_padding.bottom);
         _pImpl->asm_kernel->pack_parameters(parameters_ptr, bias_ptr, weights_ptr, ld_weights_col, ld_weights_row);
         weights->mark_as_unused();
         if(bias != nullptr)
         {
             bias->mark_as_unused();
         }
         _pImpl->is_prepared = true;
     }
 }
run()
void run (ITensorPack & tensors) override virtual
Run the kernels contained in the function.
Parameters
[in] tensors Vector that contains the tensors to operate on.
Reimplemented from INEOperator.
Definition at line 101 of file CpuDepthwiseConv2dAssemblyDispatch.cpp.
References ARM_COMPUTE_ERROR_ON_MSG, Window::DimY, ITensorPack::empty(), Scheduler::get(), CpuDepthwiseConv2d::prepare(), and IScheduler::schedule_op().
 {
     ARM_COMPUTE_ERROR_ON_MSG(tensors.empty(), "No inputs provided");
     prepare(tensors);
     NEScheduler::get().schedule_op(_pImpl->asm_kernel.get(), Window::DimY, _pImpl->asm_kernel->window(), tensors);
 }
validate()
Status validate (const ITensorInfo * src, const ITensorInfo * weights, const ITensorInfo * bias, const ITensorInfo * dst, const ConvolutionInfo & info) static
Static function to check if given info will lead to a valid configuration.
Similar to CpuDepthwiseConv2dAssemblyDispatch::configure()
Returns
a status
Definition at line 85 of file CpuDepthwiseConv2dAssemblyDispatch.cpp.
References CpuDepthwiseConv2dAssemblyWrapperKernel::validate().
Referenced by CpuDepthwiseConv2dAssemblyDispatch::configure().
 {
     return kernels::CpuDepthwiseConv2dAssemblyWrapperKernel::validate(src, weights, bias, dst, info);
 }
workspace()
experimental::MemoryRequirements workspace () const override virtual
Return the memory requirements required by the workspace.
Reimplemented from INEOperator.
Definition at line 90 of file CpuDepthwiseConv2dAssemblyDispatch.cpp.
 {
     return _pImpl->mem_req;
 }
The documentation for this class was generated from the following files:
src/cpu/operators/CpuDepthwiseConv2dAssemblyDispatch.h
src/cpu/operators/CpuDepthwiseConv2dAssemblyDispatch.cpp