Compute Library: ICLGEMMKernelSelection Class Reference
ICLGEMMKernelSelection Class Reference abstract
Basic interface for the GEMM kernel selection.
#include <ICLGEMMKernelSelection.h>
Public Member Functions
ICLGEMMKernelSelection (GPUTarget arch)
Constructor.
ICLGEMMKernelSelection (ICLGEMMKernelSelection &&)=default
Default Move Constructor.
ICLGEMMKernelSelection & operator= (ICLGEMMKernelSelection &&)=default
Default move assignment operator.
virtual ~ICLGEMMKernelSelection ()=default
Virtual destructor.
virtual CLGEMMKernelType select_kernel (const CLGEMMKernelSelectionParams &params)=0
Given the input parameters passed through CLGEMMKernelSelectionParams, this method returns the CLGEMMKernelType to use.
Detailed Description
Basic interface for the GEMM kernel selection.
Definition at line 36 of file ICLGEMMKernelSelection.h.
Constructor & Destructor Documentation
ICLGEMMKernelSelection() [1/2]
ICLGEMMKernelSelection (GPUTarget arch) inline
Constructor.
Parameters
[in] arch GPU target
Definition at line 43 of file ICLGEMMKernelSelection.h.
References ICLGEMMKernelSelection::operator=(), ICLGEMMKernelSelection::select_kernel(), and ICLGEMMKernelSelection::~ICLGEMMKernelSelection().
         : _target(arch)
     {
     }
ICLGEMMKernelSelection() [2/2]
ICLGEMMKernelSelection (ICLGEMMKernelSelection &&) default
Default Move Constructor.
~ICLGEMMKernelSelection()
virtual ~ICLGEMMKernelSelection () virtual default
Virtual destructor.
Referenced by ICLGEMMKernelSelection::ICLGEMMKernelSelection().
Member Function Documentation
operator=()
ICLGEMMKernelSelection& operator= (ICLGEMMKernelSelection &&) default
Default move assignment operator.
Referenced by ICLGEMMKernelSelection::ICLGEMMKernelSelection().
select_kernel()
virtual CLGEMMKernelType select_kernel (const CLGEMMKernelSelectionParams & params) pure virtual
Given the input parameters passed through CLGEMMKernelSelectionParams, this method returns the CLGEMMKernelType to use.
Parameters
[in] params Input parameters used by the function to return the OpenCL GEMM's kernel
Returns
CLGEMMKernelType
Implemented in CLGEMMDefaultTypeBifrost, CLGEMMDefaultTypeMidgard, and CLGEMMDefaultTypeValhall.
Referenced by ICLGEMMKernelSelection::ICLGEMMKernelSelection().
The documentation for this class was generated from the following file:
arm_compute/runtime/CL/ICLGEMMKernelSelection.h