Compute Library: DepthwiseDepthfirstGenericWithMultiplierBase< strategy > Class Template Reference
DepthwiseDepthfirstGenericWithMultiplierBase< strategy > Class Template Reference
#include <depthwise_depthfirst_generic_multiplier.hpp>
Public Member Functions
DepthwiseDepthfirstGenericWithMultiplierBase (const DepthwiseArgs &args)
DepthwiseDepthfirstGenericWithMultiplierBase (DepthwiseDepthfirstGenericWithMultiplierBase &)=delete
DepthwiseDepthfirstGenericWithMultiplierBase & operator= (DepthwiseDepthfirstGenericWithMultiplierBase &)=delete
size_t get_storage_size (void) const override
size_t get_working_size (const unsigned int n_threads, const unsigned int n_channels) const override
Detailed Description
template<class strategy>
class arm_conv::depthwise::DepthwiseDepthfirstGenericWithMultiplierBase< strategy >
Definition at line 39 of file depthwise_depthfirst_generic_multiplier.hpp.
Constructor & Destructor Documentation
DepthwiseDepthfirstGenericWithMultiplierBase() [1/2]
DepthwiseDepthfirstGenericWithMultiplierBase (const DepthwiseArgs & args) inline
Definition at line 348 of file depthwise_depthfirst_generic_multiplier.hpp.
References DepthwiseDepthfirstGenericWithMultiplierBase< strategy >::operator=().
                                                                           : DepthwiseCommon<TInput, TWeight, TOutput>(args)
   {
   }
DepthwiseDepthfirstGenericWithMultiplierBase() [2/2]
DepthwiseDepthfirstGenericWithMultiplierBase (DepthwiseDepthfirstGenericWithMultiplierBase< strategy > &) delete
Member Function Documentation
get_storage_size()
size_t get_storage_size (void) const inline override
Definition at line 355 of file depthwise_depthfirst_generic_multiplier.hpp.
References arm_gemm::roundup().
   {
     const unsigned int vl = arm_gemm::utils::get_vector_length<TAccum>(strategy::vl_type);
     const auto rounded_channels = this->m_args.input_channels * arm_gemm::roundup(this->m_args.channel_multiplier, vl);
     return kernel_points() * rounded_channels * sizeof(TWeight);
   }
get_working_size()
size_t get_working_size (const unsigned int n_threads, const unsigned int n_channels) const inline override
Definition at line 362 of file depthwise_depthfirst_generic_multiplier.hpp.
   {
     const unsigned int n_output_channels = n_channels * this->m_args.channel_multiplier;
     return n_threads * (sizeof_inptr_array() +
                         sizeof_input_samples() +
                         sizeof_outptr_array() +
                         sizeof_output_buffer(n_output_channels));
   }
operator=()
DepthwiseDepthfirstGenericWithMultiplierBase& operator= (DepthwiseDepthfirstGenericWithMultiplierBase< strategy > &) delete
Referenced by DepthwiseDepthfirstGenericWithMultiplier< strategy >::DepthwiseDepthfirstGenericWithMultiplier(), and DepthwiseDepthfirstGenericWithMultiplierBase< strategy >::DepthwiseDepthfirstGenericWithMultiplierBase().
The documentation for this class was generated from the following file:
src/core/NEON/kernels/arm_conv/depthwise/depthwise_depthfirst_generic_multiplier.hpp