Compute Library: ClDirectConv2d Class Reference
ClDirectConv2d Class Reference
Basic function to simulate a directly convolution layer.
#include <ClDirectConv2d.h>
Public Member Functions
ClDirectConv2d ()=default
void configure (const CLCompileContext &compile_context, ITensorInfo *src, ITensorInfo *weights, ITensorInfo *biases, ITensorInfo *dst, const PadStrideInfo &conv_info, const ActivationLayerInfo &act_info=ActivationLayerInfo())
Set the src and dst tensors.
void run (ITensorPack &tensors) override
Run the kernels contained in the function.
Public Member Functions inherited from ICLOperator
ICLOperator (IRuntimeContext *ctx=nullptr)
Constructor.
ICLOperator (const ICLOperator &)=delete
Prevent instances of this class from being copied (As this class contains pointers)
ICLOperator (ICLOperator &&)=default
Default move constructor.
ICLOperator & operator= (const ICLOperator &)=delete
Prevent instances of this class from being copied (As this class contains pointers)
ICLOperator & operator= (ICLOperator &&)=default
Default move assignment operator.
void prepare (ITensorPack &constants) override
Prepare the function for executing.
MemoryRequirements workspace () const override
Return the memory requirements required by the workspace.
Public Member Functions inherited from IOperator
virtual ~IOperator ()=default
Destructor.
Static Public Member Functions
static Status validate (const ITensorInfo *src, const ITensorInfo *weights, const ITensorInfo *biases, const ITensorInfo *dst, const PadStrideInfo &conv_info, const ActivationLayerInfo &act_info=ActivationLayerInfo())
Static function to check if given info will lead to a valid configuration.
Detailed Description
Basic function to simulate a directly convolution layer.
This function calls the following OpenCL kernels:
CLFillBorderKernel (executed if padding size is different from zero)
opencl::ClDirectConv2d
Definition at line 42 of file ClDirectConv2d.h.
Constructor & Destructor Documentation
ClDirectConv2d()
ClDirectConv2d () default
Member Function Documentation
configure()
void configure (const CLCompileContext & compile_context, ITensorInfo * src, ITensorInfo * weights, ITensorInfo * biases, ITensorInfo * dst, const PadStrideInfo & conv_info, const ActivationLayerInfo & act_info = ActivationLayerInfo())
Set the src and dst tensors.
Parameters
[in] compile_context The compile context to be used.
[in] src Source tensor. 3 lower dimensions represent a single src [width, height, IFM], while every optional dimension from 4 and above represent a batch of srcs. Data types supported: QASYMM8_SIGNED/QASYMM8/F16/F32.
[in] weights Weights tensor. Weights are 4D tensor with dimensions [kernel_x, kernel_y, IFM, OFM]. Data type supported:Same as src.
[in] biases Biases tensor. Shared biases supported. Biases are 1D tensor with dimensions [OFM]. Data type supported: Should match src data type, except for src of QASYMM8 and QASYMM8_SIGNED type where biases should be of S32 type.
[out] dst Destination tensor. 3 lower dimensions represent a single dst [width, height, OFM], while the rest represent batch of dsts. Data types supported: Same as src.
[in] conv_info Contains padding and stride information described in PadStrideInfo.
[in] act_info (Optional) Activation layer information in case of a fused activation.
Definition at line 68 of file ClDirectConv2d.cpp.
References ARM_COMPUTE_ERROR_ON_NULLPTR, ARM_COMPUTE_LOG_PARAMS, arm_compute::test::validation::b, arm_compute::CONSTANT, ITensorInfo::data_layout(), ITensorInfo::data_type(), ActivationLayerInfo::enabled(), CLScheduler::get(), arm_compute::is_data_type_float(), arm_compute::is_data_type_quantized_asymmetric(), arm_compute::test::validation::k, arm_compute::NHWC, ITensorInfo::quantization_info(), and CLScheduler::tune_kernel_static().
 {
     ARM_COMPUTE_ERROR_ON_NULLPTR(src);
     ARM_COMPUTE_LOG_PARAMS(src, weights, biases, dst, conv_info, act_info);
     // Initialize the direct convolution descriptor
     const DirectConvComputeKernelInfo desc = config_direct_convolution_nhwc(src, weights, conv_info);
     // Configure direct convolution kernel
     const ActivationLayerInfo conv2d_act_info = (src->data_layout() == DataLayout::NHWC && is_data_type_float(src->data_type())) ? act_info : ActivationLayerInfo();
     auto                      k               = std::make_unique<kernels::ClDirectConv2dKernel>();
     k->set_target(CLScheduler::get().target());
     k->configure(compile_context, src, weights, biases, dst, conv_info, conv2d_act_info, desc);
     _direct_conv_kernel = std::move(k);
     // Configure border handler
     PixelValue zero_value(0.f);
     if(is_data_type_quantized_asymmetric(src->data_type()))
     {
         zero_value = PixelValue(0, src->data_type(), src->quantization_info());
     }
     auto b = std::make_unique<CLFillBorderKernel>();
     b->configure(compile_context, src, _direct_conv_kernel->border_size(), BorderMode::CONSTANT, zero_value);
     _src_border_handler = std::move(b);
     // Fused activation is currently supported for NHWC and floating point types
     if(act_info.enabled() && !conv2d_act_info.enabled())
     {
         auto a = std::make_unique<kernels::ClActivationKernel>();
         a->configure(compile_context, dst, dst, act_info);
         _activation_kernel = std::move(a);
     }
     // Tune kernels
     CLScheduler::get().tune_kernel_static(*_direct_conv_kernel);
 }
run()
void run (ITensorPack & tensors) override virtual
Run the kernels contained in the function.
Parameters
[in] tensors Vector that contains the tensors to operate on.
Reimplemented from ICLOperator.
Definition at line 120 of file ClDirectConv2d.cpp.
References CLScheduler::enqueue_op(), and CLScheduler::get().
 {
     // Run border handler
     CLScheduler::get().enqueue_op(*_src_border_handler.get(), tensors, false);
     // Run direct convolution
     CLScheduler::get().enqueue_op(*_direct_conv_kernel.get(), tensors, false);
     // Run activation kernel
     if(_activation_kernel)
     {
         auto act_pack = select_activation_src_dst(tensors);
         CLScheduler::get().enqueue_op(*_activation_kernel.get(), act_pack, false);
     }
 }
validate()
Status validate (const ITensorInfo * src, const ITensorInfo * weights, const ITensorInfo * biases, const ITensorInfo * dst, const PadStrideInfo & conv_info, const ActivationLayerInfo & act_info = ActivationLayerInfo()) static
Static function to check if given info will lead to a valid configuration.
Similar to ClDirectConv2d::configure()
Returns
a status
Definition at line 106 of file ClDirectConv2d.cpp.
References ARM_COMPUTE_RETURN_ON_ERROR, ActivationLayerInfo::enabled(), and arm_compute::experimental::dynamic_fusion::validate().
Referenced by ClConv2d::get_convolution_method(), CLDirectConvolutionLayer::validate(), and ClConv2d::validate().
 {
     // Initialize the direct convolution descriptor
     const DirectConvComputeKernelInfo desc = config_direct_convolution_nhwc(src, weights, conv_info);
     ARM_COMPUTE_RETURN_ON_ERROR(kernels::ClDirectConv2dKernel::validate(src, weights, biases, dst, conv_info, ActivationLayerInfo(), desc));
     if(act_info.enabled())
     {
         ARM_COMPUTE_RETURN_ON_ERROR(kernels::ClActivationKernel::validate(dst, dst, act_info));
     }
     return Status{};
 }
The documentation for this class was generated from the following files:
src/gpu/cl/operators/ClDirectConv2d.h
src/gpu/cl/operators/ClDirectConv2d.cpp