Compute Library: CLLogicalOr Class Reference
CLLogicalOr Class Reference
#include <CLLogicalOr.h>
Public Member Functions
CLLogicalOr ()=default
Default Constructor.
void configure (const CLCompileContext &compile_context, ITensorInfo *input1, ITensorInfo *input2, ITensorInfo *output)
Initialise the kernel's inputs, output and conversion policy.
void run (ITensorPack &tensors) override
Run the kernels contained in the function.
Public Member Functions inherited from ICLOperator
ICLOperator (IRuntimeContext *ctx=nullptr)
Constructor.
ICLOperator (const ICLOperator &)=delete
Prevent instances of this class from being copied (As this class contains pointers)
ICLOperator (ICLOperator &&)=default
Default move constructor.
ICLOperator & operator= (const ICLOperator &)=delete
Prevent instances of this class from being copied (As this class contains pointers)
ICLOperator & operator= (ICLOperator &&)=default
Default move assignment operator.
void run (ITensorPack &tensors) override
Run the kernels contained in the function.
void prepare (ITensorPack &constants) override
Prepare the function for executing.
MemoryRequirements workspace () const override
Return the memory requirements required by the workspace.
Public Member Functions inherited from IOperator
virtual ~IOperator ()=default
Destructor.
Static Public Member Functions
static Status validate (const ITensorInfo *input1, const ITensorInfo *input2, const ITensorInfo *output)
Static function to check if given info will lead to a valid configuration of arm_compute::opencl::kernels::ClLogicalBinaryKernel.
Detailed Description
Definition at line 100 of file CLLogicalOr.h.
Constructor & Destructor Documentation
CLLogicalOr()
CLLogicalOr () default
Default Constructor.
Member Function Documentation
configure()
void configure (const CLCompileContext & compile_context, ITensorInfo * input1, ITensorInfo * input2, ITensorInfo * output)
Initialise the kernel's inputs, output and conversion policy.
Parameters
[in] compile_context The compile context to be used.
[in,out] input1 First tensor input. Data types supported: U8. The input tensor is [in, out] because its TensorInfo might be modified inside the kernel in case of broadcasting of dimension 0.
[in,out] input2 Second tensor input. Data types supported: same as input1. The input tensor is [in, out] because its TensorInfo might be modified inside the kernel in case of broadcasting of dimension 0.
[out] output Output tensor. Data types supported: same as input1.
Definition at line 36 of file CLLogicalOr.cpp.
References ARM_COMPUTE_LOG_PARAMS, arm_compute::test::validation::k, and arm_compute::Or.
 {
     ARM_COMPUTE_LOG_PARAMS(input1, input2, output);
     auto k = std::make_unique<arm_compute::opencl::kernels::ClLogicalBinaryKernel>();
     k->configure(compile_context, LogicalOperation::Or, input1, input2, output);
     _kernel = std::move(k);
 }
run()
void run (ITensorPack & tensors) override virtual
Run the kernels contained in the function.
Parameters
[in] tensors Vector that contains the tensors to operate on.
Implements IOperator.
Definition at line 49 of file CLLogicalOr.cpp.
References arm_compute::test::validation::dst, and ICLOperator::run().
 {
     ICLOperator::run(tensors);
 }
validate()
Status validate (const ITensorInfo * input1, const ITensorInfo * input2, const ITensorInfo * output) static
Static function to check if given info will lead to a valid configuration of arm_compute::opencl::kernels::ClLogicalBinaryKernel.
Parameters
[in] input1 First tensor input info. Data types supported: U8.
[in] input2 Second tensor input info. Data types supported: same as input1.
[in] output Output tensor info. Data types supported: same as input1.
Returns
a status
Definition at line 44 of file CLLogicalOr.cpp.
References arm_compute::Or, and ClLogicalBinaryKernel::validate().
Referenced by CLLogicalOr::validate().
 {
     return arm_compute::opencl::kernels::ClLogicalBinaryKernel::validate(LogicalOperation::Or, input1, input2, output);
 }
The documentation for this class was generated from the following files:
arm_compute/runtime/CL/functions/CLLogicalOr.h
src/runtime/CL/functions/CLLogicalOr.cpp