Compute Library: Framework Class Reference
Framework Class Reference final
Main framework class.
#include <Framework.h>
Public Member Functions
std::set< InstrumentsDescription > available_instruments () const
Supported instrument types for benchmarking.
void init (const FrameworkConfig &config)
Init the framework.
void push_suite (std::string name)
Add a new test suite.
void pop_suite ()
Remove innermost test suite.
template<typename T >
void add_test_case (std::string test_name, DatasetMode mode, TestCaseFactory::Status status)
Add a test case to the framework.
template<typename T , typename D >
void add_data_test_case (std::string test_name, DatasetMode mode, TestCaseFactory::Status status, std::string description, D &&data)
Add a data test case to the framework.
void add_test_info (std::string info)
Add info string for the next expectation/assertion.
void clear_test_info ()
Clear the collected test info.
bool has_test_info () const
Check if any info has been registered.
void print_test_info (std::ostream &os) const
Print test info.
void log_test_start (const TestInfo &info)
Tell the framework that execution of a test starts.
void log_test_skipped (const TestInfo &info)
Tell the framework that a test case is skipped.
void log_test_end (const TestInfo &info)
Tell the framework that a test case finished.
void log_failed_expectation (const TestError &error)
Tell the framework that the currently running test case failed a non-fatal expectation.
void log_info (const std::string &info)
Print the debug information that has already been logged.
int num_iterations () const
Number of iterations per test case.
void set_num_iterations (int num_iterations)
Set number of iterations per test case.
bool throw_errors () const
Should errors be caught or thrown by the framework.
void set_throw_errors (bool throw_errors)
Set whether errors are caught or thrown by the framework.
bool stop_on_error () const
Indicates if test execution is stopped after the first failed test.
void set_stop_on_error (bool stop_on_error)
Set whether to stop execution after the first failed test.
bool error_on_missing_assets () const
Indicates if a test should be marked as failed when its assets are missing.
void set_error_on_missing_assets (bool error_on_missing_assets)
Set whether a test should be considered as failed if its assets cannot be found.
bool run ()
Run all enabled test cases.
void set_test_result (TestInfo info, TestResult result)
Set the result for an executed test case.
void print_test_results (Printer &printer) const
Use the specified printer to output test results from the last run.
Profiler get_profiler () const
Factory method to obtain a configured profiler.
void add_printer (Printer *printer)
Set the printer used for the output of test results.
std::vector< TestInfo > test_infos () const
List of TestInfo's.
LogLevel log_level () const
Get the current logging level.
void set_instruments_info (InstrumentsInfo instr_info)
Sets instruments info.
bool configure_only () const
Get the configure only flag.
bool new_fixture_call () const
Return whether the new fixture has been called.
void set_new_fixture_call (bool val)
Set the new fixture call flag.
Static Public Member Functions
static Framework & get ()
Access to the singleton.
Detailed Description
Main framework class.
Keeps track of the global state, owns all test cases and collects results.
Definition at line 95 of file Framework.h.
Member Function Documentation
add_data_test_case()
void add_data_test_case (std::string test_name, DatasetMode mode, TestCaseFactory::Status status, std::string description, D && data) inline
Add a data test case to the framework.
Parameters
[in] test_name Name of the new test case.
[in] mode Mode in which to include the test.
[in] status Status of the test case.
[in] description Description of data.
[in] data Data that will be used as input to the test.
Definition at line 380 of file Framework.h.
References FrameworkConfig::mode.
Referenced by TestCaseRegistrar< T >::TestCaseRegistrar().
 {
     // WORKAROUND for GCC 4.9
     // The function should get *it which is tuple but that seems to trigger a
     // bug in the compiler.
     auto tmp = std::unique_ptr<DataTestCaseFactory<T, decltype(*std::declval<D>())>>(new DataTestCaseFactory<T, decltype(*std::declval<D>())>(current_suite_name(), std::move(test_name), mode, status,
                                                                                      std::move(description), *data));
     _test_factories.emplace_back(std::move(tmp));
 }
add_printer()
void add_printer (Printer * printer)
Set the printer used for the output of test results.
Parameters
[in] printer Pointer to a printer.
Definition at line 672 of file Framework.cpp.
Referenced by main(), and arm_compute::utils::run_example().
 {
     _printers.push_back(printer);
 }
add_test_case()
void add_test_case (std::string test_name, DatasetMode mode, TestCaseFactory::Status status) inline
Add a test case to the framework.
Parameters
[in] test_name Name of the new test case.
[in] mode Mode in which to include the test.
[in] status Status of the test case.
Definition at line 374 of file Framework.h.
Referenced by arm_compute::utils::run_example(), and TestCaseRegistrar< T >::TestCaseRegistrar().
 {
     _test_factories.emplace_back(std::make_unique<SimpleTestCaseFactory<T>>(current_suite_name(), std::move(test_name), mode, status));
 }
add_test_info()
void add_test_info (std::string info)
Add info string for the next expectation/assertion.
Parameters
[in] info Info string.
Definition at line 156 of file Framework.cpp.
 {
     _test_info.emplace_back(std::move(info));
 }
available_instruments()
std::set< InstrumentsDescription > available_instruments () const
Supported instrument types for benchmarking.
Returns
Set of all available instrument types.
Definition at line 100 of file Framework.cpp.
Referenced by CommonOptions::CommonOptions().
 {
     std::set<InstrumentsDescription> types;
     for(const auto &instrument : _available_instruments)
     {
         types.emplace(instrument.first);
     }
     return types;
 }
clear_test_info()
void clear_test_info ()
Clear the collected test info.
Definition at line 161 of file Framework.cpp.
Referenced by arm_compute::test::framework::ARM_COMPUTE_PRINT_INFO().
 {
     _test_info.clear();
 }
configure_only()
bool configure_only () const
Get the configure only flag.
Returns
The current configure only flag.
Definition at line 709 of file Framework.cpp.
 {
     return _configure_only;
 }
error_on_missing_assets()
bool error_on_missing_assets () const
Indicates if a test should be marked as failed when its assets are missing.
Returns
True if a test should be marked as failed when its assets are missing.
Definition at line 290 of file Framework.cpp.
References TestResult::CRASHED, arm_compute::test::framework::DEBUG, TestResult::DISABLED, TestCaseFactory::DISABLED, arm_compute::test::framework::ERRORS, TestResult::EXPECTED_FAILURE, TestCaseFactory::EXPECTED_FAILURE, TestResult::FAILED, Framework::get_profiler(), Profiler::header(), TestResult::header_data, arm_compute::test::validation::info, TestError::level(), Framework::log_test_end(), Framework::log_test_skipped(), Framework::log_test_start(), TestCaseFactory::make(), TestResult::measurements, Profiler::measurements(), TestResult::NOT_RUN, Printer::print_error(), Printer::print_errors_footer(), Printer::print_errors_header(), Printer::print_info(), Framework::set_test_result(), Profiler::start(), TestResult::status, TestInfo::status, TestCaseFactory::status(), Profiler::stop(), TestResult::SUCCESS, Profiler::test_start(), and Profiler::test_stop().
Referenced by Framework::set_error_on_missing_assets().
 {
     return _error_on_missing_assets;
 }
get()
Framework & get () static
Access to the singleton.
Returns
Unique instance of the framework class.
Definition at line 124 of file Framework.cpp.
Referenced by arm_compute::test::framework::ARM_COMPUTE_PRINT_INFO(), CLAccessor::CLAccessor(), CommonOptions::CommonOptions(), main(), arm_compute::utils::run_example(), TestCaseRegistrar< T >::TestCaseRegistrar(), TestSuiteRegistrar::TestSuiteRegistrar(), arm_compute::test::validation::validate(), arm_compute::test::validation::validate_min_max_loc(), arm_compute::test::validation::validate_wrap(), and CLAccessor::~CLAccessor().
 {
     static Framework instance;
     return instance;
 }
get_profiler()
Profiler get_profiler () const
Factory method to obtain a configured profiler.
The profiler enables all instruments that have been passed to the init method.
Returns
Configured profiler to collect benchmark results.
Definition at line 643 of file Framework.cpp.
References Profiler::add(), arm_compute::test::framework::ALL, is_selected, and type.
Referenced by Framework::error_on_missing_assets(), and main().
 {
     Profiler profiler;
     const bool all_instruments = std::any_of(
                                      _instruments.begin(),
                                      _instruments.end(),
                                      [](InstrumentsDescription type) -> bool { return type.first == InstrumentType::ALL; });
     auto is_selected = [&](InstrumentsDescription instrument) -> bool
     {
         return std::find_if(_instruments.begin(), _instruments.end(), [&](InstrumentsDescription type) -> bool {
             const auto group = static_cast<InstrumentType>(static_cast<uint64_t>(type.first) & 0xFF00);
             return (group == instrument.first) && (instrument.second == type.second);
         })
         != _instruments.end();
     };
     for(const auto &instrument : _available_instruments)
     {
         if(all_instruments || is_selected(instrument.first))
         {
             profiler.add(instrument.second());
         }
     }
     return profiler;
 }
has_test_info()
bool has_test_info () const
Check if any info has been registered.
Returns
True if there is test info.
Definition at line 166 of file Framework.cpp.
 {
     return !_test_info.empty();
 }
init()
void init (const FrameworkConfig & config)
Init the framework.
See also
TestFilter::TestFilter for the format of the string to filter ids.
Parameters
[in] config Framework configuration meta-data.
Definition at line 130 of file Framework.cpp.
References FrameworkConfig::configure_only, FrameworkConfig::cooldown_sec, arm_compute::mlgo::parser::end(), FrameworkConfig::id_filter, FrameworkConfig::instruments, arm_compute::test::join(), FrameworkConfig::log_level, FrameworkConfig::mode, FrameworkConfig::name_filter, and FrameworkConfig::num_iterations.
Referenced by main(), and arm_compute::utils::run_example().
 {
     _test_filter.reset(new TestFilter(config.mode, config.name_filter, config.id_filter));
     _num_iterations = config.num_iterations;
     _log_level      = config.log_level;
     _cooldown_sec   = config.cooldown_sec;
     _configure_only = config.configure_only;
     _instruments = std::set<framework::InstrumentsDescription>(std::begin(config.instruments), std::end(config.instruments));
 }
log_failed_expectation()
void log_failed_expectation (const TestError & error)
Tell the framework that the currently running test case failed a non-fatal expectation.
Parameters
[in] error Description of the error.
Definition at line 226 of file Framework.cpp.
References ARM_COMPUTE_ERROR_ON, TestCaseFactory::EXPECTED_FAILURE, TestResult::FAILED, TestError::level(), Printer::print_error(), TestResult::status, and TestInfo::status.
 {
     ARM_COMPUTE_ERROR_ON(_current_test_info == nullptr);
     ARM_COMPUTE_ERROR_ON(_current_test_result == nullptr);
     const bool is_expected_failure = _current_test_info->status == TestCaseFactory::Status::EXPECTED_FAILURE;
     if(_log_level >= error.level())
     {
         func_on_all_printers([&](Printer * p)
         {
             p->print_error(error, is_expected_failure);
         });
     }
     _current_test_result->status = TestResult::Status::FAILED;
 }
log_info()
void log_info (const std::string & info)
Print the debug information that has already been logged.
Parameters
[in] info Description of the log info.
Definition at line 244 of file Framework.cpp.
References arm_compute::test::framework::DEBUG, and Printer::print_info().
Referenced by arm_compute::test::framework::ARM_COMPUTE_PRINT_INFO().
 {
     if(_log_level >= LogLevel::DEBUG)
     {
         func_on_all_printers([&](Printer * p)
         {
             p->print_info(info);
         });
     }
 }
log_level()
LogLevel log_level () const
Get the current logging level.
Returns
The current logging level.
Definition at line 698 of file Framework.cpp.
 {
     return _log_level;
 }
log_test_end()
void log_test_end (const TestInfo & info)
Tell the framework that a test case finished.
Parameters
[in] info Test info.
Definition at line 206 of file Framework.cpp.
References arm_compute::test::framework::MEASUREMENTS, Printer::print_measurements(), Printer::print_profiler_header(), Printer::print_test_footer(), and arm_compute::test::framework::TESTS.
Referenced by Framework::error_on_missing_assets().
 {
     if(_log_level >= LogLevel::MEASUREMENTS)
     {
         func_on_all_printers([&](Printer * p)
         {
             p->print_profiler_header(_test_results.at(info).header_data);
             p->print_measurements(_test_results.at(info).measurements);
         });
     }
     if(_log_level >= LogLevel::TESTS)
     {
         func_on_all_printers([](Printer * p)
         {
             p->print_test_footer();
         });
     }
 }
log_test_skipped()
void log_test_skipped (const TestInfo & info)
Tell the framework that a test case is skipped.
Parameters
[in] info Test info.
Definition at line 201 of file Framework.cpp.
References arm_compute::test::validation::info.
Referenced by Framework::error_on_missing_assets().
 {
     static_cast<void>(info);
 }
log_test_start()
void log_test_start (const TestInfo & info)
Tell the framework that execution of a test starts.
Parameters
[in] info Test info.
Definition at line 190 of file Framework.cpp.
References Printer::print_test_header(), and arm_compute::test::framework::TESTS.
Referenced by Framework::error_on_missing_assets().
 {
     if(_log_level >= LogLevel::TESTS)
     {
         func_on_all_printers([&](Printer * p)
         {
             p->print_test_header(info);
         });
     }
 }
new_fixture_call()
bool new_fixture_call () const
Return whether the new fixture has been called.
Returns
The current new fixture call flag.
Definition at line 714 of file Framework.cpp.
 {
     return _new_fixture_call;
 }
num_iterations()
int num_iterations () const
Number of iterations per test case.
Returns
Number of iterations per test case.
Definition at line 255 of file Framework.cpp.
Referenced by Framework::set_num_iterations().
 {
     return _num_iterations;
 }
pop_suite()
void pop_suite ()
Remove innermost test suite.
Warning
Cannot be used at execution time. It can only be used for registering test cases.
Definition at line 151 of file Framework.cpp.
Referenced by TestSuiteRegistrar::TestSuiteRegistrar().
 {
     _test_suite_name.pop_back();
 }
print_test_info()
void print_test_info (std::ostream & os) const
Print test info.
Parameters
[out] os Output stream.
Definition at line 171 of file Framework.cpp.
References arm_compute::mlgo::parser::end(), arm_compute::utility::for_each(), and caffe_mnist_image_extractor::str.
Referenced by arm_compute::test::framework::ARM_COMPUTE_PRINT_INFO().
 {
     if(!_test_info.empty())
     {
         os << "CONTEXT:\n";
         for(const auto &str : _test_info)
         {
             os << "    " << str << "\n";
         }
     }
 }
print_test_results()
void print_test_results (Printer & printer) const
Use the specified printer to output test results from the last run.
This method can be used if the test results need to be obtained using a different printer than the one managed by the framework.
Parameters
[in] printer Printer used to output results.
Definition at line 628 of file Framework.cpp.
References Printer::print_measurements(), Printer::print_profiler_header(), Printer::print_run_footer(), Printer::print_run_header(), Printer::print_test_footer(), and Printer::print_test_header().
 {
     printer.print_run_header();
     for(const auto &test : _test_results)
     {
         printer.print_test_header(test.first);
         printer.print_profiler_header(test.second.header_data);
         printer.print_measurements(test.second.measurements);
         printer.print_test_footer();
     }
     printer.print_run_footer();
 }
push_suite()
void push_suite (std::string name)
Add a new test suite.
Warning
Cannot be used at execution time. It can only be used for registering test cases.
Parameters
[in] name Name of the added test suite.
Returns
Name of the current test suite.
Definition at line 146 of file Framework.cpp.
Referenced by TestSuiteRegistrar::TestSuiteRegistrar().
 {
     _test_suite_name.emplace_back(std::move(name));
 }
run()
bool run ()
Run all enabled test cases.
Returns
True if all test cases executed successful.
Definition at line 543 of file Framework.cpp.
References CLKernelLibrary::clear_programs_cache(), CLScheduler::context(), TestResult::CRASHED, TestResult::DISABLED, arm_compute::mlgo::parser::end(), TestResult::EXPECTED_FAILURE, TestResult::FAILED, CLKernelLibrary::get(), CLScheduler::get(), TestCaseFactory::mode(), TestCaseFactory::name(), arm_compute::test::framework::NONE, arm_compute::opencl_is_available(), Printer::print_run_footer(), Printer::print_run_header(), CLScheduler::queue(), CLScheduler::set_context(), CLScheduler::set_queue(), arm_compute::test::framework::sleep_in_seconds(), TestCaseFactory::status(), TestResult::SUCCESS, and arm_compute::test::framework::TESTS.
Referenced by main(), and arm_compute::utils::run_example().
 {
     // Clear old test results
     _test_results.clear();
     if(_log_level >= LogLevel::TESTS)
     {
         func_on_all_printers([](Printer * p)
         {
             p->print_run_header();
         });
     }
     const std::chrono::time_point<std::chrono::high_resolution_clock> start = std::chrono::high_resolution_clock::now();
     int id          = 0;
     int id_run_test = 0;
     for(auto &test_factory : _test_factories)
     {
         const std::string test_case_name = test_factory->name();
         const TestInfo    test_info{ id, test_case_name, test_factory->mode(), test_factory->status() };
         if(_test_filter->is_selected(test_info))
         {
 #ifdef ARM_COMPUTE_CL
             // Every 100 tests, reset the OpenCL context to release the allocated memory
             if(opencl_is_available() && (id_run_test % 100) == 0)
             {
                 auto ctx_properties   = CLScheduler::get().context().getInfo<CL_CONTEXT_PROPERTIES>(nullptr);
                 auto queue_properties = CLScheduler::get().queue().getInfo<CL_QUEUE_PROPERTIES>(nullptr);
                 cl::Context      new_ctx   = cl::Context(CL_DEVICE_TYPE_DEFAULT, ctx_properties.data());
                 cl::CommandQueue new_queue = cl::CommandQueue(new_ctx, CLKernelLibrary::get().get_device(), queue_properties);
                 CLKernelLibrary::get().clear_programs_cache();
                 CLScheduler::get().set_context(new_ctx);
                 CLScheduler::get().set_queue(new_queue);
             }
 #endif // ARM_COMPUTE_CL
             run_test(test_info, *test_factory);
             ++id_run_test;
             // Run test delay
             sleep_in_seconds(_cooldown_sec);
         }
         ++id;
     }
     const std::chrono::time_point<std::chrono::high_resolution_clock> end = std::chrono::high_resolution_clock::now();
     if(_log_level >= LogLevel::TESTS)
     {
         func_on_all_printers([](Printer * p)
         {
             p->print_run_footer();
         });
     }
     auto runtime = std::chrono::duration_cast<std::chrono::seconds>(end - start);
     std::map<TestResult::Status, int> results = count_test_results();
     if(_log_level > LogLevel::NONE)
     {
         std::cout << "Executed " << _test_results.size() << " test(s) ("
                   << results[TestResult::Status::SUCCESS] << " passed, "
                   << results[TestResult::Status::EXPECTED_FAILURE] << " expected failures, "
                   << results[TestResult::Status::FAILED] << " failed, "
                   << results[TestResult::Status::CRASHED] << " crashed, "
                   << results[TestResult::Status::DISABLED] << " disabled) in " << runtime.count() << " second(s)\n";
     }
     int num_successful_tests = results[TestResult::Status::SUCCESS] + results[TestResult::Status::EXPECTED_FAILURE] + results[TestResult::Status::DISABLED];
     return (static_cast<unsigned int>(num_successful_tests) == _test_results.size());
 }
set_error_on_missing_assets()
void set_error_on_missing_assets (bool error_on_missing_assets)
Set whether a test should be considered as failed if its assets cannot be found.
Parameters
[in] error_on_missing_assets True if a test should be marked as failed when its assets are missing.
Definition at line 285 of file Framework.cpp.
References Framework::error_on_missing_assets().
Referenced by main().
 {
     _error_on_missing_assets = error_on_missing_assets;
 }
set_instruments_info()
void set_instruments_info (InstrumentsInfo instr_info)
Sets instruments info.
Note
TODO(COMPMID-2638) : Remove once instruments are transferred outside the framework.
Parameters
[in] instr_info Instruments info to set
Definition at line 703 of file Framework.cpp.
References ARM_COMPUTE_ERROR_ON.
Referenced by main().
 {
     ARM_COMPUTE_ERROR_ON(instruments_info == nullptr);
     *instruments_info = instr_info;
 }
set_new_fixture_call()
void set_new_fixture_call (bool val)
Set the new fixture call flag.
Parameters
[in] val Value to set for the flag
Definition at line 719 of file Framework.cpp.
 {
     _new_fixture_call = val;
 }
set_num_iterations()
void set_num_iterations (int num_iterations)
Set number of iterations per test case.
Parameters
[in] num_iterations Number of iterations per test case.
Definition at line 260 of file Framework.cpp.
References Framework::num_iterations().
 {
     _num_iterations = num_iterations;
 }
set_stop_on_error()
void set_stop_on_error (bool stop_on_error)
Set whether to stop execution after the first failed test.
Parameters
[in] stop_on_error True if execution is going to be stopped after first failed test.
Definition at line 275 of file Framework.cpp.
References Framework::stop_on_error().
Referenced by main().
 {
     _stop_on_error = stop_on_error;
 }
set_test_result()
void set_test_result (TestInfo info, TestResult result)
Set the result for an executed test case.
Parameters
[in] info Test info.
[in] result Execution result.
Definition at line 623 of file Framework.cpp.
Referenced by Framework::error_on_missing_assets().
 {
     _test_results.emplace(std::move(info), std::move(result));
 }
set_throw_errors()
void set_throw_errors (bool throw_errors)
Set whether errors are caught or thrown by the framework.
Parameters
[in] throw_errors True if errors should be thrown.
Definition at line 265 of file Framework.cpp.
References Framework::throw_errors().
Referenced by main(), and arm_compute::utils::run_example().
 {
     _throw_errors = throw_errors;
 }
stop_on_error()
bool stop_on_error () const
Indicates if test execution is stopped after the first failed test.
Returns
True if the execution is going to be stopped after the first failed test.
Definition at line 280 of file Framework.cpp.
Referenced by Framework::set_stop_on_error().
 {
     return _stop_on_error;
 }
test_infos()
std::vector< TestInfo > test_infos () const
List of TestInfo's.
Returns
Vector with all test ids.
Definition at line 677 of file Framework.cpp.
References TestInfo::name.
Referenced by main().
 {
     std::vector<TestInfo> ids;
     int id = 0;
     for(const auto &factory : _test_factories)
     {
         const TestInfo test_info{ id, factory->name(), factory->mode(), factory->status() };
         if(_test_filter->is_selected(test_info))
         {
             ids.emplace_back(std::move(test_info));
         }
         ++id;
     }
     return ids;
 }
throw_errors()
bool throw_errors () const
Should errors be caught or thrown by the framework.
Returns
True if errors are thrown.
Definition at line 270 of file Framework.cpp.
Referenced by Framework::set_throw_errors().
 {
     return _throw_errors;
 }
The documentation for this class was generated from the following files:
tests/framework/Framework.h
tests/framework/Framework.cpp