Compute Library: CLCrop Class Reference
CLCrop Class Reference
Basic function to run opencl::kernels::ClCropKernel.
#include <CLCrop.h>
Public Member Functions
CLCrop ()
Constructor.
~CLCrop ()
Destructor.
CLCrop (const CLCrop &)=delete
Prevent instances of this class from being copied (As this class contains pointers)
CLCrop (CLCrop &&)
Default move constructor.
CLCrop & operator= (const CLCrop &)=delete
Prevent instances of this class from being copied (As this class contains pointers)
CLCrop & operator= (CLCrop &&)
Default move assignment operator.
void configure (const ICLTensor *input, ICLTensor *output, Coordinates2D start, Coordinates2D end, uint32_t batch_index, float extrapolation_value=0, Window *output_window=nullptr)
Configure function.
void configure (const CLCompileContext &compile_context, const ICLTensor *input, ICLTensor *output, Coordinates2D start, Coordinates2D end, uint32_t batch_index, float extrapolation_value=0, Window *output_window=nullptr)
Configure function.
void run () override
Run the kernels contained in the function.
Public Member Functions inherited from IFunction
virtual ~IFunction ()=default
Destructor.
virtual void prepare ()
Prepare the function for executing.
Static Public Member Functions
static Status validate (const ITensorInfo *input, const ITensorInfo *output, Coordinates2D start, Coordinates2D end, uint32_t batch_index, float extrapolation_value=0, Window *output_window=nullptr)
Static function to check if given info will lead to a valid configuration of CLStridedSliceKernel.
Detailed Description
Basic function to run opencl::kernels::ClCropKernel.
Definition at line 39 of file CLCrop.h.
Constructor & Destructor Documentation
CLCrop() [1/3]
CLCrop ()
Constructor.
Definition at line 46 of file CLCrop.cpp.
References CLCrop::operator=(), and CLCrop::~CLCrop().
     : _impl(std::make_unique<Impl>())
 {
 }
~CLCrop()
~CLCrop () default
Destructor.
Referenced by CLCrop::CLCrop().
CLCrop() [2/3]
CLCrop (const CLCrop &) delete
Prevent instances of this class from being copied (As this class contains pointers)
CLCrop() [3/3]
CLCrop (CLCrop &&) default
Default move constructor.
Member Function Documentation
configure() [1/2]
void configure (const ICLTensor * input, ICLTensor * output, Coordinates2D start, Coordinates2D end, uint32_t batch_index, float extrapolation_value = 0, Window * output_window = nullptr)
Configure function.
Note
Supported tensor rank: up to 4
Valid data layouts:
NHWC
Valid data type configurations:
src dst
All F32
Parameters
[in] input Source tensor. Data type supported: All. Data layouts supported: NHWC.
[out] output Destination tensor. Data type supported: F32
[in] start Coordinates of where to start cropping the image.
[in] end Coordinates of where to end cropping the image.
[in] batch_index Fourth dimension index of the 3D image to crop in input.
[in] extrapolation_value Value to be used for values outside of the image. Default is 0.
[in] output_window Output window to be used in case cropped image is being copied into a tensor. Default is nullptr.
Definition at line 54 of file CLCrop.cpp.
References CLKernelLibrary::get().
 {
     configure(CLKernelLibrary::get().get_compile_context(), src, dst, start, end, batch_index, extrapolation_value, dst_window);
 }
configure() [2/2]
void configure (const CLCompileContext & compile_context, const ICLTensor * input, ICLTensor * output, Coordinates2D start, Coordinates2D end, uint32_t batch_index, float extrapolation_value = 0, Window * output_window = nullptr)
Configure function.
Note
Supported tensor rank: up to 4
Parameters
[in] compile_context The compile context to be used.
[in] input Source tensor. Data type supported: All. Data layouts supported: NHWC.
[out] output Destination tensor. Data type supported: F32
[in] start Coordinates of where to start cropping the image.
[in] end Coordinates of where to end cropping the image.
[in] batch_index Fourth dimension index of the 3D image to crop in input.
[in] extrapolation_value Value to be used for values outside of the image. Default is 0.
[in] output_window Output window to be used in case cropped image is being copied into a tensor. Default is nullptr.
Definition at line 60 of file CLCrop.cpp.
References ARM_COMPUTE_ERROR_ON_NULLPTR, ARM_COMPUTE_LOG_PARAMS, arm_compute::test::validation::dst, arm_compute::mlgo::parser::end(), and arm_compute::test::validation::src.
 {
     ARM_COMPUTE_ERROR_ON_NULLPTR(src, dst);
     ARM_COMPUTE_LOG_PARAMS(src, dst, start, end, batch_index, extrapolation_value, dst_window);
     _impl->src = src;
     _impl->dst = dst;
     _impl->op = std::make_unique<opencl::ClCrop>();
     _impl->op->configure(compile_context, _impl->src->info(), _impl->dst->info(), start, end, batch_index, extrapolation_value, dst_window);
 }
operator=() [1/2]
CLCrop& operator= (const CLCrop &) delete
Prevent instances of this class from being copied (As this class contains pointers)
Referenced by CLCrop::CLCrop().
operator=() [2/2]
CLCrop & operator= (CLCrop &&) default
Default move assignment operator.
run()
void run () override virtual
Run the kernels contained in the function.
For CPU kernels:
Multi-threading is used for the kernels which are parallelisable.
By default std::thread::hardware_concurrency() threads are used.
Note
CPPScheduler::set_num_threads() can be used to manually set the number of threads
For OpenCL kernels:
All the kernels are enqueued on the queue associated with CLScheduler.
The queue is then flushed.
Note
The function will not block until the kernels are executed. It is the user's responsibility to wait.
Will call prepare() on first run if hasn't been done
Implements IFunction.
Definition at line 78 of file CLCrop.cpp.
References arm_compute::ACL_DST, arm_compute::ACL_SRC, ITensorPack::add_tensor(), and arm_compute::test::validation::pack.
 {
     ITensorPack pack;
     pack.add_tensor(TensorType::ACL_SRC, _impl->src);
     pack.add_tensor(TensorType::ACL_DST, _impl->dst);
     _impl->op->run(pack);
 }
validate()
Status validate (const ITensorInfo * input, const ITensorInfo * output, Coordinates2D start, Coordinates2D end, uint32_t batch_index, float extrapolation_value = 0, Window * output_window = nullptr) static
Static function to check if given info will lead to a valid configuration of CLStridedSliceKernel.
Note
Supported tensor rank: up to 4
Parameters
[in] input Source tensor info. Data type supported: All. Data layouts supported: NHWC.
[in] output Destination tensor info. Data type supported: F32
[in] start Coordinates of where to start cropping the image.
[in] end Coordinates of where to end cropping the image.
[in] batch_index Fourth dimension index of the 3D image to crop in input.
[in] extrapolation_value Value to be used for values outside of the image. Default is 0.
[in] output_window Output window to be used in case cropped image is being copied into a tensor. Default is nullptr.
Definition at line 73 of file CLCrop.cpp.
References ClCrop::validate().
Referenced by CLCropResize::validate().
 {
     return opencl::ClCrop::validate(input, output, start, end, batch_index, extrapolation_value, dst_window);
 }
The documentation for this class was generated from the following files:
arm_compute/runtime/CL/functions/CLCrop.h
src/runtime/CL/functions/CLCrop.cpp