Compute Library: ClCast Class Reference
ClCast Class Reference
Basic function to run kernels::ClCastKernel.
#include <ClCast.h>
Public Member Functions
void configure (const ClCompileContext &compile_context, const ITensorInfo *src, ITensorInfo *dst, ConvertPolicy policy)
Configure operator for a given list of arguments.
Public Member Functions inherited from ICLOperator
ICLOperator (IRuntimeContext *ctx=nullptr)
Constructor.
ICLOperator (const ICLOperator &)=delete
Prevent instances of this class from being copied (As this class contains pointers)
ICLOperator (ICLOperator &&)=default
Default move constructor.
ICLOperator & operator= (const ICLOperator &)=delete
Prevent instances of this class from being copied (As this class contains pointers)
ICLOperator & operator= (ICLOperator &&)=default
Default move assignment operator.
void run (ITensorPack &tensors) override
Run the kernels contained in the function.
void prepare (ITensorPack &constants) override
Prepare the function for executing.
MemoryRequirements workspace () const override
Return the memory requirements required by the workspace.
Public Member Functions inherited from IOperator
virtual ~IOperator ()=default
Destructor.
Static Public Member Functions
static Status validate (const ITensorInfo *src, const ITensorInfo *dst, ConvertPolicy policy)
Static function to check if given info will lead to a valid configuration.
Detailed Description
Basic function to run kernels::ClCastKernel.
Definition at line 35 of file ClCast.h.
Member Function Documentation
configure()
void configure (const ClCompileContext & compile_context, const ITensorInfo * src, ITensorInfo * dst, ConvertPolicy policy)
Configure operator for a given list of arguments.
Note
Input data type must be different than output data type.
Valid data layouts:
All
Valid data type configurations:
src dst
U8 S8, U16, S16, U32, S32, F16, F32
U16 U8, S8, S16, U32, S32, F16, F32
S16 U8, S8, U16, U32, S32, F16, F32
U32 U8, S8, U16, S16, S32, F16, F32
S32 U8, S8, U16, S16, U32, F16, F32
F16 U8, S8, U16, S16, U32, F32
F32 U8, S8, U16, S16, U32, F16
Parameters
[in] compile_context The compile context to be used.
[in] src The source tensor to convert. Data types supported: U8/S8/U16/S16/U32/S32/F16/F32.
[out] dst The destinatio tensor. Data types supported: U8/S8/U16/S16/U32/S32/F16/F32.
[in] policy Conversion policy.
Definition at line 35 of file ClCast.cpp.
References ARM_COMPUTE_LOG_PARAMS, and arm_compute::test::validation::k.
 {
     ARM_COMPUTE_LOG_PARAMS(src, dst, policy);
     auto k = std::make_unique<kernels::ClCastKernel>();
     k->configure(compile_context, src, dst, policy);
     _kernel = std::move(k);
 }
validate()
Status validate (const ITensorInfo * src, const ITensorInfo * dst, ConvertPolicy policy) static
Static function to check if given info will lead to a valid configuration.
Similar to ClCast::configure()
Returns
a status
Definition at line 43 of file ClCast.cpp.
References ClCastKernel::validate().
Referenced by CLCast::validate(), and CLDepthConvertLayer::validate().
 {
     return kernels::ClCastKernel::validate(src, dst, policy);
 }
The documentation for this class was generated from the following files:
src/gpu/cl/operators/ClCast.h
src/gpu/cl/operators/ClCast.cpp