Compute Library: NEMeanStdDevNormalizationKernel Class Reference
NEMeanStdDevNormalizationKernel Class Reference
Interface for the kernel to normalize the input 2D tensor across the first dimension with respect to mean and standard deviation of the same dimension.
#include <NEMeanStdDevNormalizationKernel.h>
Public Member Functions
const char * name () const override
Name of the kernel.
NEMeanStdDevNormalizationKernel ()
Default constructor.
NEMeanStdDevNormalizationKernel (const NEMeanStdDevNormalizationKernel &)=delete
Prevent instances of this class from being copied (As this class contains pointers)
NEMeanStdDevNormalizationKernel & operator= (const NEMeanStdDevNormalizationKernel &)=delete
Prevent instances of this class from being copied (As this class contains pointers)
NEMeanStdDevNormalizationKernel (NEMeanStdDevNormalizationKernel &&)=default
Allow instances of this class to be moved.
NEMeanStdDevNormalizationKernel & operator= (NEMeanStdDevNormalizationKernel &&)=default
Allow instances of this class to be moved.
~NEMeanStdDevNormalizationKernel ()=default
Default destructor.
void configure (ITensor *input, ITensor *output=nullptr, float epsilon=1e-8f)
Initialise the kernel's input and outputs.
void run (const Window &window, const ThreadInfo &info) override
Execute the kernel on the passed window.
Public Member Functions inherited from ICPPKernel
virtual ~ICPPKernel ()=default
Default destructor.
virtual void run_nd (const Window &window, const ThreadInfo &info, const Window &thread_locator)
legacy compatibility layer for implemantions which do not support thread_locator In these cases we simply narrow the interface down the legacy version
virtual void run_op (ITensorPack &tensors, const Window &window, const ThreadInfo &info)
Execute the kernel on the passed window.
virtual size_t get_mws (const CPUInfo &platform, size_t thread_count) const
Return minimum workload size of the relevant kernel.
Public Member Functions inherited from IKernel
IKernel ()
Constructor.
virtual ~IKernel ()=default
Destructor.
virtual bool is_parallelisable () const
Indicates whether or not the kernel is parallelisable.
virtual BorderSize border_size () const
The size of the border for that kernel.
const Window & window () const
The maximum window the kernel can be executed on.
bool is_window_configured () const
Function to check if the embedded window of this kernel has been configured.
Static Public Member Functions
static Status validate (const ITensorInfo *input, const ITensorInfo *output=nullptr, float epsilon=1e-8f)
Static function to check if given info will lead to a valid configuration of NEMeanStdDevNormalizationKernel.
Additional Inherited Members
Static Public Attributes inherited from ICPPKernel
static constexpr size_t default_mws = 1
Detailed Description
Interface for the kernel to normalize the input 2D tensor across the first dimension with respect to mean and standard deviation of the same dimension.
Definition at line 38 of file NEMeanStdDevNormalizationKernel.h.
Constructor & Destructor Documentation
NEMeanStdDevNormalizationKernel() [1/3]
NEMeanStdDevNormalizationKernel ()
Default constructor.
Definition at line 131 of file NEMeanStdDevNormalizationKernel.cpp.
Referenced by NEMeanStdDevNormalizationKernel::name().
     : _input(nullptr), _output(nullptr), _epsilon(1e-8f)
 {
 }
NEMeanStdDevNormalizationKernel() [2/3]
NEMeanStdDevNormalizationKernel (const NEMeanStdDevNormalizationKernel &) delete
Prevent instances of this class from being copied (As this class contains pointers)
NEMeanStdDevNormalizationKernel() [3/3]
NEMeanStdDevNormalizationKernel (NEMeanStdDevNormalizationKernel &&) default
Allow instances of this class to be moved.
~NEMeanStdDevNormalizationKernel()
~NEMeanStdDevNormalizationKernel () default
Default destructor.
Referenced by NEMeanStdDevNormalizationKernel::name().
Member Function Documentation
configure()
void configure (ITensor * input, ITensor * output = nullptr, float epsilon = 1e-8f)
Initialise the kernel's input and outputs.
Note
If the output tensor is a nullptr, the normalization will be performed in-place.
Parameters
[in,out] input Source tensor with 2 dimensions. In case of output tensor = nullptr, this tensor will store the result of the normalization. Data types supported: F16/F32.
[out] output (Optional) Destination tensor. It can be nullptr in case of in-place computation. Data type supported: same as input
[in] epsilon (Optional) Small float to avoid division by zero in case of zero standard deviation. Defaults to 1e-8.
Definition at line 136 of file NEMeanStdDevNormalizationKernel.cpp.
References ARM_COMPUTE_ERROR_ON_NULLPTR, ARM_COMPUTE_ERROR_THROW_ON, arm_compute::quantization::epsilon, ITensor::info(), arm_compute::test::validation::input, NEMeanStdDevNormalizationKernel::validate(), and arm_compute::cpu::kernels::validate_and_configure_window().
Referenced by NEMeanStdDevNormalizationKernel::name().
 {
     ARM_COMPUTE_ERROR_ON_NULLPTR(input);
     ARM_COMPUTE_ERROR_THROW_ON(NEMeanStdDevNormalizationKernel::validate(input->info(), (output != nullptr) ? output->info() : nullptr, epsilon));
     _input   = input;
     _output  = (output == nullptr) ? input : output;
     _epsilon = epsilon;
     // Configure kernel window
     auto win_config = validate_and_configure_window(input->info(), (output == nullptr) ? nullptr : output->info());
     ARM_COMPUTE_ERROR_THROW_ON(win_config.first);
     ICPPKernel::configure(win_config.second);
 }
name()
const char* name () const inline override virtual
Name of the kernel.
Returns
Kernel name
Implements ICPPKernel.
Definition at line 41 of file NEMeanStdDevNormalizationKernel.h.
References NEMeanStdDevNormalizationKernel::configure(), arm_compute::quantization::epsilon, arm_compute::test::validation::info, arm_compute::test::validation::input, NEMeanStdDevNormalizationKernel::NEMeanStdDevNormalizationKernel(), NEMeanStdDevNormalizationKernel::operator=(), NEMeanStdDevNormalizationKernel::run(), NEMeanStdDevNormalizationKernel::validate(), IKernel::window(), and NEMeanStdDevNormalizationKernel::~NEMeanStdDevNormalizationKernel().
     {
         return "NEMeanStdDevNormalizationKernel";
     }
operator=() [1/2]
NEMeanStdDevNormalizationKernel& operator= (const NEMeanStdDevNormalizationKernel &) delete
Prevent instances of this class from being copied (As this class contains pointers)
Referenced by NEMeanStdDevNormalizationKernel::name().
operator=() [2/2]
NEMeanStdDevNormalizationKernel& operator= (NEMeanStdDevNormalizationKernel &&) default
Allow instances of this class to be moved.
run()
void run (const Window & window, const ThreadInfo & info) override virtual
Execute the kernel on the passed window.
Warning
If is_parallelisable() returns false then the passed window must be equal to window()
Note
The window has to be a region within the window returned by the window() method
The width of the window has to be a multiple of num_elems_processed_per_iteration().
Parameters
[in] window Region on which to execute the kernel. (Must be a region of the window returned by window())
[in] info Info about executing thread and CPU.
Reimplemented from ICPPKernel.
Definition at line 159 of file NEMeanStdDevNormalizationKernel.cpp.
References ARM_COMPUTE_ERROR_ON, ARM_COMPUTE_ERROR_ON_INVALID_SUBWINDOW, ARM_COMPUTE_ERROR_ON_UNCONFIGURED_KERNEL, ARM_COMPUTE_UNUSED, ITensorInfo::data_type(), ITensor::info(), and IKernel::window().
Referenced by NEMeanStdDevNormalizationKernel::name().
 {
     ARM_COMPUTE_UNUSED(info);
     ARM_COMPUTE_ERROR_ON_UNCONFIGURED_KERNEL(this);
     ARM_COMPUTE_ERROR_ON_INVALID_SUBWINDOW(IKernel::window(), window);
     const auto *uk = get_implementation(MeanStdDevNormSelectorData{ _output->info()->data_type() });
     ARM_COMPUTE_ERROR_ON(uk == nullptr || uk->ukernel == nullptr);
     uk->ukernel(_input, _output, _epsilon, window);
 }
validate()
Status validate (const ITensorInfo * input, const ITensorInfo * output = nullptr, float epsilon = 1e-8f) static
Static function to check if given info will lead to a valid configuration of NEMeanStdDevNormalizationKernel.
Parameters
[in] input Source tensor info with 2 dimensions. In case of output tensor info = nullptr, this tensor will store the result of the normalization. Data types supported: F16/F32.
[in] output (Optional) Destination tensor info. It can be nullptr in case of in-place computation. Data type supported: same as input
[in] epsilon (Optional) Small float to avoid division by zero in case of zero standard deviation. Defaults to 1e-8.
Returns
a status
Definition at line 152 of file NEMeanStdDevNormalizationKernel.cpp.
References ARM_COMPUTE_RETURN_ON_ERROR, ICloneable< T >::clone(), arm_compute::cpu::kernels::validate_and_configure_window(), and arm_compute::cpu::kernels::validate_arguments().
Referenced by NEMeanStdDevNormalizationKernel::configure(), NEMeanStdDevNormalizationKernel::name(), and NEMeanStdDevNormalizationLayer::validate().
 {
     ARM_COMPUTE_RETURN_ON_ERROR(validate_arguments(input, output, epsilon));
     ARM_COMPUTE_RETURN_ON_ERROR(validate_and_configure_window(input->clone().get(), (output != nullptr) ? output->clone().get() : nullptr).first);
     return Status{};
 }
The documentation for this class was generated from the following files:
src/core/NEON/kernels/NEMeanStdDevNormalizationKernel.h
src/core/NEON/kernels/NEMeanStdDevNormalizationKernel.cpp