Compute Library: NEBatchToSpaceLayer Class Reference
NEBatchToSpaceLayer Class Reference
Basic function to run NEBatchToSpaceLayerKernel.
#include <NEBatchToSpaceLayer.h>
Public Member Functions
NEBatchToSpaceLayer ()=default
Constructor.
NEBatchToSpaceLayer (const NEBatchToSpaceLayer &)=delete
Prevent instances of this class from being copied (As this class contains pointers)
NEBatchToSpaceLayer & operator= (const NEBatchToSpaceLayer &)=delete
Prevent instances of this class from being copied (As this class contains pointers)
NEBatchToSpaceLayer (NEBatchToSpaceLayer &&)=delete
Prevent instances of this class from being moved (As this class contains non movable objects)
NEBatchToSpaceLayer & operator= (NEBatchToSpaceLayer &&)=delete
Prevent instances of this class from being moved (As this class contains non movable objects)
~NEBatchToSpaceLayer ()=default
Default destructor.
void configure (const ITensor *input, const ITensor *block_shape, ITensor *output)
Set the input and output tensors.
void configure (const ITensor *input, int32_t block_shape_x, int32_t block_shape_y, ITensor *output)
Set the input and output tensors.
Public Member Functions inherited from INESimpleFunctionNoBorder
INESimpleFunctionNoBorder (IRuntimeContext *ctx=nullptr)
Constructor.
INESimpleFunctionNoBorder (const INESimpleFunctionNoBorder &)=delete
Prevent instances of this class from being copied (As this class contains pointers)
INESimpleFunctionNoBorder (INESimpleFunctionNoBorder &&)=default
Default move constructor.
INESimpleFunctionNoBorder & operator= (const INESimpleFunctionNoBorder &)=delete
Prevent instances of this class from being copied (As this class contains pointers)
INESimpleFunctionNoBorder & operator= (INESimpleFunctionNoBorder &&)=default
Default move assignment operator.
~INESimpleFunctionNoBorder ()
Default destructor.
void run () override final
Run the kernels contained in the function.
Public Member Functions inherited from IFunction
virtual ~IFunction ()=default
Destructor.
virtual void prepare ()
Prepare the function for executing.
Static Public Member Functions
static Status validate (const ITensorInfo *input, const ITensorInfo *block_shape, const ITensorInfo *output)
Static function to check if given info will lead to a valid configuration of CLBatchToSpaceLayer.
static Status validate (const ITensorInfo *input, int32_t block_shape_x, int32_t block_shape_y, const ITensorInfo *output)
Static function to check if given info will lead to a valid configuration of CLBatchToSpaceLayer (Static block shape).
Detailed Description
Basic function to run NEBatchToSpaceLayerKernel.
Definition at line 38 of file NEBatchToSpaceLayer.h.
Constructor & Destructor Documentation
NEBatchToSpaceLayer() [1/3]
NEBatchToSpaceLayer () default
Constructor.
NEBatchToSpaceLayer() [2/3]
NEBatchToSpaceLayer (const NEBatchToSpaceLayer &) delete
Prevent instances of this class from being copied (As this class contains pointers)
NEBatchToSpaceLayer() [3/3]
NEBatchToSpaceLayer (NEBatchToSpaceLayer &&) delete
Prevent instances of this class from being moved (As this class contains non movable objects)
~NEBatchToSpaceLayer()
~NEBatchToSpaceLayer () default
Default destructor.
Member Function Documentation
configure() [1/2]
void configure (const ITensor * input, const ITensor * block_shape, ITensor * output)
Set the input and output tensors.
Valid data layouts:
NHWC
NCHW
Valid data type configurations:
src0 src1 dst
All s32 All
Parameters
[in] input Tensor input. Supported tensor rank: 4. Data types supported: All.
[in] block_shape 1-D tensor with shape [M]. Data types supported: S32
[out] output Tensor output. Data types supported: same as input
Definition at line 36 of file NEBatchToSpaceLayer.cpp.
References ARM_COMPUTE_LOG_PARAMS, and arm_compute::test::validation::k.
 {
     ARM_COMPUTE_LOG_PARAMS(input, block_shape, output);
     auto k = std::make_unique<NEBatchToSpaceLayerKernel>();
     k->configure(input, block_shape, output);
     _kernel = std::move(k);
 }
configure() [2/2]
void configure (const ITensor * input, int32_t block_shape_x, int32_t block_shape_y, ITensor * output)
Set the input and output tensors.
(Static block shape).
Parameters
[in] input Tensor input. Supported tensor rank: 4. Data types supported: All.
[in] block_shape_x Block shape x value.
[in] block_shape_y Block shape y value.
[out] output Tensor output. Data types supported: same as input
Definition at line 44 of file NEBatchToSpaceLayer.cpp.
References arm_compute::test::validation::k.
 {
     auto k = std::make_unique<NEBatchToSpaceLayerKernel>();
     k->configure(input, block_shape_x, block_shape_y, output);
     _kernel = std::move(k);
 }
operator=() [1/2]
NEBatchToSpaceLayer& operator= (const NEBatchToSpaceLayer &) delete
Prevent instances of this class from being copied (As this class contains pointers)
operator=() [2/2]
NEBatchToSpaceLayer& operator= (NEBatchToSpaceLayer &&) delete
Prevent instances of this class from being moved (As this class contains non movable objects)
validate() [1/2]
Status validate (const ITensorInfo * input, const ITensorInfo * block_shape, const ITensorInfo * output) static
Static function to check if given info will lead to a valid configuration of CLBatchToSpaceLayer.
Parameters
[in] input Tensor input info. Supported tensor rank: 4. Data types supported: All.
[in] block_shape block shape tensor info with shape [M]. Data types supported: S32
[out] output Tensor output info. Data types supported: same as input
Returns
a status
Definition at line 51 of file NEBatchToSpaceLayer.cpp.
References NEBatchToSpaceLayerKernel::validate().
Referenced by arm_compute::test::validation::DATA_TEST_CASE().
 {
     return NEBatchToSpaceLayerKernel::validate(input, block_shape, output);
 }
validate() [2/2]
Status validate (const ITensorInfo * input, int32_t block_shape_x, int32_t block_shape_y, const ITensorInfo * output) static
Static function to check if given info will lead to a valid configuration of CLBatchToSpaceLayer (Static block shape).
Parameters
[in] input Tensor input info. Supported tensor rank: 4. Data types supported: All.
[in] block_shape_x Block shape x value.
[in] block_shape_y Block shape y value.
[out] output Tensor output info. Data types supported: same as input
Returns
a status
Definition at line 56 of file NEBatchToSpaceLayer.cpp.
References NEBatchToSpaceLayerKernel::validate().
 {
     return NEBatchToSpaceLayerKernel::validate(input, block_shape_x, block_shape_y, output);
 }
The documentation for this class was generated from the following files:
arm_compute/runtime/NEON/functions/NEBatchToSpaceLayer.h
src/runtime/NEON/functions/NEBatchToSpaceLayer.cpp