Compute Library: CLDevice Class Reference
CLDevice Class Reference
OpenCL device type class.
#include <CLDevice.h>
Public Member Functions
CLDevice ()
Default Constructor.
CLDevice (const cl::Device &cl_device)
Constructor.
const GPUTarget & target () const
Returns the GPU target of the cl device.
size_t compute_units () const
Returns the number of compute units available.
const cl::Device & cl_device () const
Returns the underlying cl device object.
CLVersion version () const
Returns the device's CL version.
std::string device_version () const
Returns the device version as a string.
DeviceType type () const override
Device type accessor.
bool supported (const std::string &extension) const override
Check if extensions on a device are supported.
std::tuple< bool, std::string > is_non_uniform_workgroup_supported () const
Returns whether non-uniform workgroup is supported and the build options.
Public Member Functions inherited from IDevice
virtual ~IDevice ()=default
Virtual Destructor.
Detailed Description
OpenCL device type class.
Initializes and stores all the information about a cl device, working mainly as a cache mechanism.
Definition at line 43 of file CLDevice.h.
Constructor & Destructor Documentation
CLDevice() [1/2]
CLDevice () inline
Default Constructor.
Definition at line 47 of file CLDevice.h.
         : _device(cl::Device()), _options()
     {
     }
CLDevice() [2/2]
CLDevice (const cl::Device & cl_device) inline
Constructor.
Parameters
[in] cl_device OpenCL device
Definition at line 56 of file CLDevice.h.
References CLDevice::cl_device(), CLDeviceOptions::compute_units, CLDeviceOptions::device_version, CLDeviceOptions::extensions, arm_compute::G76, arm_compute::get_cl_version(), arm_compute::get_target_from_name(), CLDeviceOptions::gpu_target, and CLDeviceOptions::version.
         : _device(), _options()
     {
         _device = cl_device;
         // Get device target
         std::string device_name = _device.getInfo<CL_DEVICE_NAME>();
         _options.gpu_target     = get_target_from_name(device_name);
         // Fill extensions
         std::string extensions = _device.getInfo<CL_DEVICE_EXTENSIONS>();
         std::istringstream iss(extensions);
         for(std::string s; iss >> s;)
         {
             _options.extensions.insert(s);
         }
         // SW workaround for G76
         if(_options.gpu_target == GPUTarget::G76)
         {
             _options.extensions.insert("cl_arm_integer_dot_product_int8");
         }
         // Get device version
         _options.version = get_cl_version(_device);
         // Get compute units
         _options.compute_units = _device.getInfo<CL_DEVICE_MAX_COMPUTE_UNITS>();
         // Get device version
         _options.device_version = _device.getInfo<CL_DEVICE_VERSION>();
     }
Member Function Documentation
cl_device()
const cl::Device& cl_device () const inline
Returns the underlying cl device object.
Returns
A cl device
Definition at line 112 of file CLDevice.h.
Referenced by CLDevice::CLDevice(), CLCompileContext::create_kernel(), CLCompileContext::default_ndrange(), CLCompileContext::get_device(), and CLCompileContext::max_local_workgroup_size().
     {
         return _device;
     }
compute_units()
size_t compute_units () const inline
Returns the number of compute units available.
Returns
Number of compute units
Definition at line 103 of file CLDevice.h.
References CLDeviceOptions::compute_units.
Referenced by CLCompileContext::get_num_compute_units().
     {
         return _options.compute_units;
     }
device_version()
std::string device_version () const inline
Returns the device version as a string.
Returns
CLVersion of the device
Definition at line 130 of file CLDevice.h.
References CLDeviceOptions::device_version.
Referenced by CLCompileContext::get_ddk_version(), and CLCompileContext::get_device_version().
     {
         return _options.device_version;
     }
is_non_uniform_workgroup_supported()
std::tuple<bool, std::string> is_non_uniform_workgroup_supported () const inline
Returns whether non-uniform workgroup is supported and the build options.
If the feature is supported, the appropriate build options will be appended to the specified string.
Returns
A tuple (supported, build_options) indicating whether the feature is supported and the corresponding build options to enable it.
Definition at line 154 of file CLDevice.h.
References arm_compute::CL20, arm_compute::CL30, arm_compute::get_cl_non_uniform_work_group_supported(), CLDevice::supported(), and CLDevice::version().
Referenced by CLCompileContext::set_context().
     {
         if(version() == CLVersion::CL30 && get_cl_non_uniform_work_group_supported(_device))
         {
             return {true, " -cl-std=CL3.0 "};
         }
         else if(version() == CLVersion::CL20)
         {
             return {true, " -cl-std=CL2.0 "};
         }
         else if(supported("cl_arm_non_uniform_work_group_size"))
         {
             return {true, " -cl-arm-non-uniform-work-group-size "};
         }
         return {false, ""};
     }
supported()
bool supported (const std::string & extension) const inline override virtual
Check if extensions on a device are supported.
Parameters
[in] extension An extension to check if it's supported.
Returns
True if the extension is supported else false
Implements IDevice.
Definition at line 141 of file CLDevice.h.
References CLDeviceOptions::extensions.
Referenced by CLCompileContext::fp16_supported(), CLCompileContext::int64_base_atomics_supported(), CLDevice::is_non_uniform_workgroup_supported(), and CLCompileContext::set_context().
     {
         return _options.extensions.count(extension) != 0;
     }
target()
const GPUTarget& target () const inline
Returns the GPU target of the cl device.
Returns
The GPU target
Definition at line 94 of file CLDevice.h.
References CLDeviceOptions::gpu_target.
Referenced by CLCompileContext::get_gpu_target(), and CLCompileContext::set_context().
     {
         return _options.gpu_target;
     }
type()
DeviceType type () const inline override virtual
Device type accessor.
Implements IDevice.
Definition at line 136 of file CLDevice.h.
References arm_compute::CL.
     {
         return DeviceType::CL;
     }
version()
CLVersion version () const inline
Returns the device's CL version.
Returns
CLVersion of the device
Definition at line 121 of file CLDevice.h.
References CLDeviceOptions::version.
Referenced by CLDevice::is_non_uniform_workgroup_supported().
     {
         return _options.version;
     }
The documentation for this class was generated from the following file:
arm_compute/core/CL/CLDevice.h