Compute Library: OpTensor Class Reference
OpTensor Class Reference final
Operator Tensor Handle This can be either an argument tensor, or an intermediate tensor linking 2 Operator s.
#include <OperatorGraph.h>
Public Types
using Id = int
Public Member Functions
OpTensor (Id id={})
Id id () const
Id of the OpTensor.
Detailed Description
Operator Tensor Handle This can be either an argument tensor, or an intermediate tensor linking 2 Operator s.
Definition at line 68 of file OperatorGraph.h.
Member Typedef Documentation
Id
using Id = int
Definition at line 71 of file OperatorGraph.h.
Constructor & Destructor Documentation
OpTensor()
OpTensor (Id id = {})
Definition at line 74 of file OperatorGraph.cpp.
     : _id{ id }
 {
 }
Member Function Documentation
id()
OpTensor::Id id () const
Id of the OpTensor.
Returns
Id
Definition at line 79 of file OperatorGraph.cpp.
Referenced by arm_compute::experimental::dynamic_fusion::add_op_conv2d(), arm_compute::experimental::dynamic_fusion::add_op_elementwise_op(), arm_compute::experimental::dynamic_fusion::add_op_floor(), arm_compute::experimental::dynamic_fusion::operator<(), and arm_compute::experimental::dynamic_fusion::operator==().
 {
     return _id;
 }
The documentation for this class was generated from the following files:
arm_compute/core/experimental/OperatorGraph.h
src/core/experimental/dynamic_fusion/OperatorGraph.cpp