Compute Library: ClDirectConvDefaultConfigBifrost Class Reference
ClDirectConvDefaultConfigBifrost Class Reference final
Bifrost based OpenCL direct convolution configuration.
#include <ClDirectConvDefaultConfigBifrost.h>
Public Member Functions
ClDirectConvDefaultConfigBifrost (GPUTarget gpu)
Constructor.
DirectConvComputeKernelInfo configure (const ITensorInfo *src, const ITensorInfo *wei, const PadStrideInfo &conv_info) override
This method returns the DirectConvComputeKernelInfo for the given inputs.
Public Member Functions inherited from IClDirectConvKernelConfig
IClDirectConvKernelConfig (GPUTarget arch)
Constructor.
ARM_COMPUTE_DISALLOW_COPY_ALLOW_MOVE (IClDirectConvKernelConfig)
virtual ~IClDirectConvKernelConfig ()=default
Virtual destructor.
Detailed Description
Bifrost based OpenCL direct convolution configuration.
Definition at line 34 of file ClDirectConvDefaultConfigBifrost.h.
Constructor & Destructor Documentation
ClDirectConvDefaultConfigBifrost()
ClDirectConvDefaultConfigBifrost (GPUTarget gpu)
Constructor.
Parameters
[in] gpu GPU target
Definition at line 40 of file ClDirectConvDefaultConfigBifrost.cpp.
     : IClDirectConvKernelConfig(gpu)
 {
 }
Member Function Documentation
configure()
DirectConvComputeKernelInfo configure (const ITensorInfo * src, const ITensorInfo * wei, const PadStrideInfo & conv_info) override virtual
This method returns the DirectConvComputeKernelInfo for the given inputs.
Parameters
[in] src Source tensor (activation tensor)
[in] wei Weights tensor
[in] conv_info Convolution info
Implements IClDirectConvKernelConfig.
Definition at line 45 of file ClDirectConvDefaultConfigBifrost.cpp.
References ARM_COMPUTE_ERROR_ON_MSG, arm_compute::misc::shape_calculator::compute_deep_convolution_shape(), arm_compute::test::validation::conv_info, ITensorInfo::data_layout(), ITensorInfo::data_type(), arm_compute::export_to_cl_image(), DirectConvComputeKernelInfo::export_weights_to_cl_image, arm_compute::G71, ClDirectConvConfigArray< T >::get_function(), DirectConvComputeKernelInfo::k0, DirectConvComputeKernelInfo::m0, DirectConvComputeKernelInfo::n0, arm_compute::NHWC, arm_compute::test::validation::output_shape, and arm_compute::test::validation::src.
 {
     using ConfigurationFunctionExecutorPtr = DirectConvComputeKernelInfo (ClDirectConvDefaultConfigBifrost::*)(const ITensorInfo * src, const ITensorInfo * wei, const PadStrideInfo & conv_info);
     ClDirectConvConfigArray<ConfigurationFunctionExecutorPtr> configs_G71(&ClDirectConvDefaultConfigBifrost::configure_G71_f32,
                                                                           &ClDirectConvDefaultConfigBifrost::configure_G71_f16,
                                                                           &ClDirectConvDefaultConfigBifrost::configure_G71_u8);
     ClDirectConvConfigArray<ConfigurationFunctionExecutorPtr> configs_default(&ClDirectConvDefaultConfigBifrost::configure_default_f32,
                                                                               &ClDirectConvDefaultConfigBifrost::configure_default_f16,
                                                                               &ClDirectConvDefaultConfigBifrost::configure_G71_u8);
     ConfigurationFunctionExecutorPtr func = nullptr;
     switch(_target)
     {
         case GPUTarget::G71:
             func = configs_G71.get_function(src->data_type());
             break;
         default:
             func = configs_default.get_function(src->data_type());
             break;
     }
     ARM_COMPUTE_ERROR_ON_MSG(func == nullptr, "Data type not supported for direct convolution");
     return (this->*func)(src, wei, conv_info);
 }
The documentation for this class was generated from the following files:
src/gpu/cl/kernels/direct_conv/ClDirectConvDefaultConfigBifrost.h
src/gpu/cl/kernels/direct_conv/ClDirectConvDefaultConfigBifrost.cpp