Compute Library: GpuConv2d Class Reference
GpuConv2d Class Reference final
Operator interface.
#include <GpuConv2d.h>
Public Types
using Attributes = Conv2dAttributes
Attributes are a set of backend-agnostic parameters that define what an operator does.
Static Public Member Functions
static void create_op (GpuWorkloadSketch &sketch, ITensorInfo *src, ITensorInfo *wei, ITensorInfo *bia, ITensorInfo *dst, const Attributes &attributes)
Create an operator and fuse it into the workload sketch.
static Status validate_op (const GpuWorkloadSketch &sketch, const ITensorInfo *src, const ITensorInfo *wei, const ITensorInfo *bia, const ITensorInfo *dst, const Attributes &attributes)
Validate the operator and check if it can be fused into the workload sketch.
Detailed Description
Operator interface.
Definition at line 40 of file GpuConv2d.h.
Member Typedef Documentation
Attributes
using Attributes = Conv2dAttributes
Attributes are a set of backend-agnostic parameters that define what an operator does.
Definition at line 44 of file GpuConv2d.h.
Member Function Documentation
create_op()
void create_op (GpuWorkloadSketch & sketch, ITensorInfo * src, ITensorInfo * wei, ITensorInfo * bia, ITensorInfo * dst, const Attributes & attributes) static
Create an operator and fuse it into the workload sketch.
Note
If validate_op() fails, the creation also fails and may throw an error.
If validate_op() fails, sketch remains unchanged and valid.
Valid data type configurations:
src wei bia dst
F16 F16 F16 F16
F32 F32 F32 F32
Valid data layouts:
NHWC
Parameters
[in,out] sketch Workload sketch into which the operator will be fused
[in] src Source tensor
[in] wei Weight tensor
[in] bia (Optional) Bias tensor
[out] dst Destination tensor
[in] attributes Operator attributes
Definition at line 172 of file GpuConv2d.cpp.
References arm_compute::ACL_DST_0, arm_compute::ACL_SRC_0, arm_compute::ACL_SRC_1, arm_compute::ACL_SRC_2, ArgumentPack< T >::add_const_tensor(), GpuOperatorGroup::add_operator(), ArgumentPack< T >::add_tensor(), ARM_COMPUTE_ERROR, ARM_COMPUTE_ERROR_ON, ARM_COMPUTE_ERROR_ON_NULLPTR, ARM_COMPUTE_ERROR_THROW_ON, arm_compute::auto_init_if_empty(), arm_compute::BIFROST, ICloneable< T >::clone(), GpuWorkloadSketch::Implementation::component_graph(), arm_compute::misc::shape_calculator::compute_deep_convolution_shape(), GpuWorkloadSketch::Implementation::context(), ITensorInfo::data_layout(), arm_compute::test::validation::data_layout, ITensorInfo::data_type(), arm_compute::experimental::dynamic_fusion::export_to_cl_image_support(), arm_compute::F16, arm_compute::F32, arm_compute::FLOOR, arm_compute::G71, arm_compute::GPU_ARCH_MASK, GpuWorkloadContext::gpu_target(), GpuWorkloadSketch::implementation(), GpuOperatorGroup::new_operator(), arm_compute::experimental::dynamic_fusion::OpenCL, GpuWorkloadSketch::Implementation::operator_group(), Conv2dAttributes::pad(), UnitWorkloadStage::Run, arm_compute::test::validation::shape, Conv2dAttributes::stride(), ITensorInfo::tensor_shape(), arm_compute::opencl::kernels::gemm::update_padding_for_cl_image(), and GpuConv2d::validate_op().
Referenced by arm_compute::test::validation::TEST_CASE().
 {
     // Assert validation
     ARM_COMPUTE_ERROR_THROW_ON(GpuConv2d::validate_op(sketch, src, wei, bia, dst, attributes));
     ARM_COMPUTE_ERROR_ON_NULLPTR(src, wei, dst);
     const auto data_layout = src->data_layout();
     // Auto initialize dst tensor
     {
         auto shape = misc::shape_calculator::compute_deep_convolution_shape(src->tensor_shape(), data_layout, wei->tensor_shape(),
                                                                             PadStrideInfo(attributes.stride().x(), attributes.stride().y(), attributes.pad().left,
                                                                                           attributes.pad().right,
                                                                                           attributes.pad().top, attributes.pad().bottom, DimensionRoundingType::FLOOR)); // use the default DimensionRoundingType
         auto_init_if_empty(*dst, src->clone()->set_tensor_shape(shape));
     }
     // Translate into components and add to component graph
     auto &comp_graph = sketch.implementation().component_graph();
     const auto sketch_ctx = sketch.implementation().context();
     const auto gpu_target = sketch_ctx->gpu_target();
     if(sketch_ctx->gpu_language() == GpuLanguage::OpenCL)
     {
         const auto cl_compile_ctx = sketch_ctx->cl_compile_context();
         ARM_COMPUTE_ERROR_ON(cl_compile_ctx == nullptr);
         // Add Direct Conv2d Component
         {
             auto properties = IGpuKernelComponent::Properties();
             properties.stage(UnitWorkloadStage{ UnitWorkloadStage::Stage::Run });
             auto settings = ClComponentDirectConv2d::Settings();
             settings.export_to_cl_image(
                 export_to_cl_image_support(src, gpu_target, cl_compile_ctx->get_device(), data_layout));
             settings.fast_relaxed_math(
                 (gpu_target != GPUTarget::G71 && (gpu_target & GPUTarget::GPU_ARCH_MASK) == GPUTarget::BIFROST)
                 && (dst->data_type() == DataType::F32 || dst->data_type() == DataType::F16));
             if(settings.export_to_cl_image())
             {
                 arm_compute::opencl::kernels::gemm::update_padding_for_cl_image(wei);
             }
             ArgumentPack<ITensorInfo> arguments;
             arguments.add_const_tensor(ACL_SRC_0, src);
             arguments.add_const_tensor(ACL_SRC_1, wei);
             arguments.add_const_tensor(ACL_SRC_2, bia);
             arguments.add_const_tensor(ACL_DST_0, dst);
             comp_graph.add_new_component<ClComponentDirectConv2d>(properties, arguments, attributes, settings);
         }
     }
     else
     {
         ARM_COMPUTE_ERROR("Unimplemented Gpu language");
     }
     // Set up fusion test by adding to the Operator Group
     // Note this has to be performed after all the components have been successfully added to the component graph
     // Pack tensor infos
     ArgumentPack<ITensorInfo> tensors;
     tensors.add_const_tensor(ACL_SRC_0, src);
     tensors.add_tensor(ACL_SRC_1, wei);
     tensors.add_const_tensor(ACL_SRC_2, bia);
     tensors.add_tensor(ACL_DST_0, dst);
     const auto op = sketch.implementation().operator_group().new_operator(operator_type, tensors);
     sketch.implementation().operator_group().add_operator(op);
 }
validate_op()
Status validate_op (const GpuWorkloadSketch & sketch, const ITensorInfo * src, const ITensorInfo * wei, const ITensorInfo * bia, const ITensorInfo * dst, const Attributes & attributes) static
Validate the operator and check if it can be fused into the workload sketch.
Similar to GpuConv2d::create_op()
Definition at line 92 of file GpuConv2d.cpp.
References arm_compute::ACL_DST_0, arm_compute::ACL_SRC_0, arm_compute::ACL_SRC_1, arm_compute::ACL_SRC_2, ArgumentPack< T >::add_const_tensor(), ARM_COMPUTE_RETURN_ERROR_MSG, ARM_COMPUTE_RETURN_ERROR_ON, ARM_COMPUTE_RETURN_ERROR_ON_DATA_LAYOUT_NOT_IN, ARM_COMPUTE_RETURN_ERROR_ON_DATA_TYPE_CHANNEL_NOT_IN, ARM_COMPUTE_RETURN_ERROR_ON_MSG, ARM_COMPUTE_RETURN_ERROR_ON_NULLPTR, ARM_COMPUTE_RETURN_ON_ERROR, arm_compute::auto_init_if_empty(), arm_compute::BIFROST, ICloneable< T >::clone(), arm_compute::misc::shape_calculator::compute_deep_convolution_shape(), GpuWorkloadSketch::Implementation::context(), ITensorInfo::data_layout(), arm_compute::test::validation::data_layout, arm_compute::test::validation::dst, arm_compute::experimental::dynamic_fusion::export_to_cl_image_support(), arm_compute::F16, arm_compute::F32, arm_compute::FLOOR, arm_compute::G71, arm_compute::GPU_ARCH_MASK, GpuWorkloadContext::gpu_target(), ITensorInfo::has_valid_id(), GpuWorkloadSketch::implementation(), GpuOperatorGroup::new_operator(), arm_compute::NHWC, arm_compute::experimental::dynamic_fusion::OpenCL, GpuWorkloadSketch::Implementation::operator_group(), Conv2dAttributes::pad(), UnitWorkloadStage::Run, arm_compute::test::validation::shape, KernelProperties::stage(), Conv2dAttributes::stride(), ITensorInfo::tensor_shape(), GpuOperatorGroup::try_add_operator(), and ClComponentDirectConv2d::validate().
Referenced by GpuConv2d::create_op(), and arm_compute::test::validation::TEST_CASE().
 {
     ARM_COMPUTE_RETURN_ERROR_ON_NULLPTR(src, wei, dst);
     ARM_COMPUTE_RETURN_ERROR_ON(
         !src->has_valid_id() || !wei->has_valid_id() || !dst->has_valid_id());
     if(bia != nullptr)
     {
         ARM_COMPUTE_RETURN_ERROR_ON(!bia->has_valid_id());
     }
     // Perform fusion test
     // Pack tensor infos
     ArgumentPack<ITensorInfo> tensors;
     tensors.add_const_tensor(ACL_SRC_0, src);
     tensors.add_const_tensor(ACL_SRC_1, wei);
     tensors.add_const_tensor(ACL_SRC_2, bia);
     tensors.add_const_tensor(ACL_DST_0, dst);
     const auto op = sketch.implementation().operator_group().new_operator(operator_type, tensors);
     ARM_COMPUTE_RETURN_ERROR_ON_MSG(!sketch.implementation().operator_group().try_add_operator(op),
                                     "Operator fusion test failed. This operator cannot be fused into the workload");
     // Auto initialize dst tensor info
     TensorInfo dst_info_to_validate = *dst;
     const auto data_layout          = src->data_layout();
     {
         auto shape = misc::shape_calculator::compute_deep_convolution_shape(src->tensor_shape(), data_layout, wei->tensor_shape(),
                                                                             PadStrideInfo(attributes.stride().x(), attributes.stride().y(), attributes.pad().left,
                                                                                           attributes.pad().right,
                                                                                           attributes.pad().top, attributes.pad().bottom, DimensionRoundingType::FLOOR)); // use the default DimensionRoundingType
         auto_init_if_empty(dst_info_to_validate, src->clone()->set_tensor_shape(shape));
     }
     // Check support level
     // Data type
     ARM_COMPUTE_RETURN_ERROR_ON_DATA_TYPE_CHANNEL_NOT_IN(src, 1, DataType::F16, DataType::F32);
     // Data layout
     ARM_COMPUTE_RETURN_ERROR_ON_DATA_LAYOUT_NOT_IN(src, DataLayout::NHWC);
     const auto sketch_ctx = sketch.implementation().context();
     const auto gpu_target = sketch_ctx->gpu_target();
     if(sketch_ctx->gpu_language() == GpuLanguage::OpenCL)
     {
         const auto cl_compile_ctx = sketch_ctx->cl_compile_context();
         ARM_COMPUTE_RETURN_ERROR_ON(cl_compile_ctx == nullptr);
         // Validate Direct Conv2d Component
         {
             const auto properties = IGpuKernelComponent::Properties().stage(UnitWorkloadStage{ UnitWorkloadStage::Stage::Run });
             auto       settings   = ClComponentDirectConv2d::Settings();
             settings.export_to_cl_image(
                 export_to_cl_image_support(src, gpu_target, cl_compile_ctx->get_device(), data_layout));
             settings.fast_relaxed_math(
                 (gpu_target != GPUTarget::G71 && (gpu_target & GPUTarget::GPU_ARCH_MASK) == GPUTarget::BIFROST)
                 && (dst_info_to_validate.data_type() == DataType::F32 || dst_info_to_validate.data_type() == DataType::F16));
             ArgumentPack<ITensorInfo> arguments;
             arguments.add_const_tensor(ACL_SRC_0, src);
             arguments.add_const_tensor(ACL_SRC_1, wei);
             arguments.add_const_tensor(ACL_SRC_2, bia);
             arguments.add_const_tensor(ACL_DST_0, &dst_info_to_validate);
             ARM_COMPUTE_RETURN_ON_ERROR(ClComponentDirectConv2d::validate(properties, arguments, attributes, settings));
         }
     }
     else
     {
         ARM_COMPUTE_RETURN_ERROR_MSG("Unimplemented Gpu language");
     }
     return Status{};
 }
The documentation for this class was generated from the following files:
arm_compute/dynamic_fusion/sketch/gpu/operators/GpuConv2d.h
src/dynamic_fusion/sketch/gpu/operators/GpuConv2d.cpp