Compute Library: GpuKernelComponentGraph Class Reference
GpuKernelComponentGraph Class Reference
A multi-input (tensors), multi-output (tensors) acyclic directed graph of gpu kernel components Its main purposes are:
#include <GpuKernelComponentGraph.h>
Public Member Functions
GpuKernelComponentGraph (GpuComponentServices *services)
Constructor.
GpuKernelComponentGraph (const GpuKernelComponentGraph &graph)=delete
Prevent instances of this class from being copy constructed.
GpuKernelComponentGraph & operator= (const GpuKernelComponentGraph &graph)=delete
Prevent instances of this class from being copied.
GpuKernelComponentGraph (GpuKernelComponentGraph &&graph)=default
Allow instances of this class to be move constructed.
GpuKernelComponentGraph & operator= (GpuKernelComponentGraph &&graph)=default
Allow instances of this class to be moved.
template<typename T , typename... Args>
void add_new_component (Args &&... args)
Create a new component and add it to the component graph Component id is automatically allocated.
GpuKernelComponentStream fuse () const
Perform component fusion and serialize the graph into a stream of component groups.
Detailed Description
A multi-input (tensors), multi-output (tensors) acyclic directed graph of gpu kernel components Its main purposes are:
Perform "graph-level" optimizations like fusion of kernel components (not the fusion of operators)
Automatically assign memory descriptions MemoryDescriptor of all tensors based on graph topology
Definition at line 47 of file GpuKernelComponentGraph.h.
Constructor & Destructor Documentation
GpuKernelComponentGraph() [1/3]
GpuKernelComponentGraph (GpuComponentServices * services)
Constructor.
Parameters
[in] services GpuComponentServices to be used by the graph
Definition at line 78 of file GpuKernelComponentGraph.cpp.
     : _services{ services }, _components{}, _tensors{}, _dependency_graph{}
 {
 }
GpuKernelComponentGraph() [2/3]
GpuKernelComponentGraph (const GpuKernelComponentGraph & graph) delete
Prevent instances of this class from being copy constructed.
GpuKernelComponentGraph() [3/3]
GpuKernelComponentGraph (GpuKernelComponentGraph && graph) default
Allow instances of this class to be move constructed.
Member Function Documentation
add_new_component()
void add_new_component (Args &&... args) inline
Create a new component and add it to the component graph Component id is automatically allocated.
Template Parameters
T Component type
Args Component argument types
Parameters
[in] args Component arguments except for component id, which is auto-allocated
Definition at line 72 of file GpuKernelComponentGraph.h.
References DependencyGraph::add_operator(), GemmTuner::args, ARM_COMPUTE_ERROR_ON, ARM_COMPUTE_UNUSED, GpuComponentServices::component_factory(), GpuKernelComponentFactory::create(), GpuKernelComponentGraph::fuse(), ArgumentPack< T >::get_const_dst_tensors(), ArgumentPack< T >::get_const_src_tensors(), arm_compute::test::validation::success, and tf_frozen_model_extractor::t.
     {
         auto                      comp           = _services->component_factory().create<T>(std::forward<Args>(args)...);
         ArgumentPack<ITensorInfo> tensors        = comp->tensors();
         const auto                src_tensor_ids = get_tensor_ids(tensors.get_const_src_tensors());
         const auto                dst_tensor_ids = get_tensor_ids(tensors.get_const_dst_tensors());
         bool                      success        = _dependency_graph.add_operator(comp->id(), src_tensor_ids, dst_tensor_ids);
         ARM_COMPUTE_UNUSED(success);
         ARM_COMPUTE_ERROR_ON(!success);
         _components[comp->id()] = std::move(comp);
         for(auto t : tensors.get_const_src_tensors())
         {
             _tensors[t->id()] = t;
         }
         for(auto t : tensors.get_const_dst_tensors())
         {
             _tensors[t->id()] = t;
         }
     }
fuse()
GpuKernelComponentStream fuse () const
Perform component fusion and serialize the graph into a stream of component groups.
Note
Fusion constraints (for kernel components) are exactly the same as the invariants of GpuKernelComponentGroup Fusion can be framed as a mathematical optimization problem: Given fusion constraints, find the "best" fusion patterns possible "Best" is ill-defined at the moment. For now we define "best" fusion pattern as one which results in the least number of fused kernels (GpuKernelComponentGroup) at the end
As the first iteration, we offer a sub-optimal algorithm here which ensures all constraints are met, but provides no guarantee that the fusion pattern is optimal
Definition at line 83 of file GpuKernelComponentGraph.cpp.
References ARM_COMPUTE_ERROR_ON, arm_compute::test::validation::success, and DependencyGraph::topological_partition().
Referenced by GpuKernelComponentGraph::add_new_component(), and GpuWorkloadSketch::Implementation::generate_source_code().
 {
     // Obtain memory descriptor map
     const auto mem_map = assign_memory_descriptors(_tensors, _dependency_graph);
     /// @note Fusion constraints (for kernel components) are exactly the same as the invariants of @ref GpuKernelComponentGroup
     /// Fusion can be framed as a mathematical optimization problem:
     /// Given fusion constraints, find the "best" fusion patterns possible
     /// "Best" is ill-defined at the moment. For now we define "best" fusion pattern as one
     /// which results in the least number of fused kernels ( @ref GpuKernelComponentGroup ) at the end
     /// As the first iteration, we offer a sub-optimal algorithm here which ensures all
     /// constraints are met, but provides no guarantee that the fusion pattern is optimal
     GpuKernelComponentStream stream{ _services, mem_map };
     // Break down into linear groups of components (constraint 1), preserving topological order
     const auto linear_graphs = _dependency_graph.topological_partition();
     // Further divide up the linear groups based on rest of the fusion constraints (rely on component group's invariants)
     for(const auto &graph : linear_graphs)
     {
         for(unsigned int i = 0; i < graph.size(); ++i)
         {
             const auto comp = _components.at(graph[i].op).get();
             // Each new linear graph signals a new component group in the stream
             if(i == 0)
             {
                 stream.new_component_group();
             }
             // If it violates the component group's invariant / fusion constraint, breaks up the stream by inserting a new group
             bool success = stream.add_component(comp);
             if(!success)
             {
                 stream.new_component_group();
                 success = stream.add_component(comp);
                 ARM_COMPUTE_ERROR_ON(!success);
             }
         }
     }
     return stream;
 }
operator=() [1/2]
GpuKernelComponentGraph& operator= (const GpuKernelComponentGraph & graph) delete
Prevent instances of this class from being copied.
operator=() [2/2]
GpuKernelComponentGraph& operator= (GpuKernelComponentGraph && graph) default
Allow instances of this class to be moved.
The documentation for this class was generated from the following files:
src/dynamic_fusion/sketch/gpu/GpuKernelComponentGraph.h
src/dynamic_fusion/sketch/gpu/GpuKernelComponentGraph.cpp