Compute Library: KernelProperties Class Reference
KernelProperties Class Reference
Properties common to all kernel component types.
#include <IGpuKernelComponent.h>
Public Member Functions
KernelProperties & stage (const UnitWorkloadStage &stage)
UnitWorkloadStage stage () const
Detailed Description
Properties common to all kernel component types.
Definition at line 39 of file IGpuKernelComponent.h.
Member Function Documentation
stage() [1/2]
KernelProperties& stage (const UnitWorkloadStage & stage) inline
Definition at line 42 of file IGpuKernelComponent.h.
References KernelProperties::stage().
Referenced by arm_compute::experimental::dynamic_fusion::operator==(), and GpuConv2d::validate_op().
     {
         _stage = stage;
         return *this;
     }
stage() [2/2]
UnitWorkloadStage stage () const inline
Definition at line 47 of file IGpuKernelComponent.h.
Referenced by KernelProperties::stage().
     {
         return _stage;
     }
The documentation for this class was generated from the following file:
src/dynamic_fusion/sketch/gpu/components/IGpuKernelComponent.h