Compute Library: arm_compute::utils::math Namespace Reference
arm_compute::utils::math Namespace Reference
Functions
template<typename T , typename = typename std::enable_if<(std::is_integral<T>::value), arm_compute::utils::requires::detail::enabler>::type>
T safe_integer_add (T val_a, T val_b)
Safe integer addition between two integers.
template<typename T , typename = typename std::enable_if<(std::is_integral<T>::value), arm_compute::utils::requires::detail::enabler>::type>
T safe_integer_sub (T val_a, T val_b)
Safe integer subtraction between two integers.
template<typename T , typename = typename std::enable_if<(std::is_integral<T>::value), arm_compute::utils::requires::detail::enabler>::type>
T safe_integer_mul (T val_a, T val_b)
Safe integer multiplication between two integers.
template<typename T , typename = typename std::enable_if<(std::is_integral<T>::value), arm_compute::utils::requires::detail::enabler>::type>
T safe_integer_div (T val_a, T val_b)
Safe integer division between two integers.
Function Documentation
safe_integer_add()
T arm_compute::utils::math::safe_integer_add (T val_a, T val_b)
Safe integer addition between two integers.
In case of an overflow the numeric max limit is return. In case of an underflow numeric max limit is return.
Template Parameters
T Integer types to add
Parameters
[in] val_a First value to add
[in] val_b Second value to add
Returns
The addition result
Definition at line 50 of file SafeOps.h.
Referenced by arm_compute::test::validation::TEST_CASE().
 {
     T result = 0;
     if((val_b > 0) && (val_a > std::numeric_limits<T>::max() - val_b))
     {
         result = std::numeric_limits<T>::max();
     }
     else if((val_b < 0) && (val_a < std::numeric_limits<T>::min() - val_b))
     {
         result = std::numeric_limits<T>::min();
     }
     else
     {
         result = val_a + val_b;
     }
     return result;
 }
safe_integer_div()
T arm_compute::utils::math::safe_integer_div (T val_a, T val_b)
Safe integer division between two integers.
In case of an overflow the numeric max limit is return. In case of an underflow numeric max limit is return.
Template Parameters
T Integer types to divide
Parameters
[in] val_a Dividend value
[in] val_b Divisor value
Returns
The quotient
Definition at line 164 of file SafeOps.h.
Referenced by arm_compute::test::validation::TEST_CASE().
 {
     T result = 0;
     if((val_b == 0) || ((val_a == std::numeric_limits<T>::min()) && (val_b == -1)))
     {
         result = std::numeric_limits<T>::min();
     }
     else
     {
         result = val_a / val_b;
     }
     return result;
 }
safe_integer_mul()
T arm_compute::utils::math::safe_integer_mul (T val_a, T val_b)
Safe integer multiplication between two integers.
In case of an overflow the numeric max limit is return. In case of an underflow numeric max limit is return.
Template Parameters
T Integer types to multiply
Parameters
[in] val_a First value to multiply
[in] val_b Second value to multiply
Returns
The multiplication result
Definition at line 114 of file SafeOps.h.
Referenced by arm_compute::test::validation::TEST_CASE().
 {
     T result = 0;
     if(val_a > 0)
     {
         if((val_b > 0) && (val_a > (std::numeric_limits<T>::max() / val_b)))
         {
             result = std::numeric_limits<T>::max();
         }
         else if(val_b < (std::numeric_limits<T>::min() / val_a))
         {
             result = std::numeric_limits<T>::min();
         }
         else
         {
             result = val_a * val_b;
         }
     }
     else
     {
         if((val_b > 0) && (val_a < (std::numeric_limits<T>::min() / val_b)))
         {
             result = std::numeric_limits<T>::max();
         }
         else if((val_a != 0) && (val_b < (std::numeric_limits<T>::max() / val_a)))
         {
             result = std::numeric_limits<T>::min();
         }
         else
         {
             result = val_a * val_b;
         }
     }
     return result;
 }
safe_integer_sub()
T arm_compute::utils::math::safe_integer_sub (T val_a, T val_b)
Safe integer subtraction between two integers.
In case of an overflow the numeric max limit is return. In case of an underflow numeric max limit is return.
Template Parameters
T Integer types to subtract
Parameters
[in] val_a Value to subtract from
[in] val_b Value to subtract
Returns
The subtraction result
Definition at line 82 of file SafeOps.h.
Referenced by arm_compute::test::validation::TEST_CASE().
 {
     T result = 0;
     if((val_b < 0) && (val_a > std::numeric_limits<T>::max() + val_b))
     {
         result = std::numeric_limits<T>::max();
     }
     else if((val_b > 0) && (val_a < std::numeric_limits<T>::min() + val_b))
     {
         result = std::numeric_limits<T>::min();
     }
     else
     {
         result = val_a - val_b;
     }
     return result;
 }