Compute Library: Conv2dContent Struct Reference
Conv2dContent Struct Reference
#include <OperatorGraphImpl.h>
Public Member Functions
Conv2dContent ()=default
Conv2dContent (const OperatorGraph::Implementation *graph, Id id, const Conv2dDescriptor &desc, const ITensorDescPack< OpTensorContent > &tensors)
Conv2dContent (const OperatorGraph::Implementation *graph, Id id, const Conv2dDescriptor &desc, const ITensorDescPack< OpTensorContent > &tensors, ConvolutionMethod method)
~Conv2dContent ()=default
Conv2dContent (const Conv2dContent &)=default
Conv2dContent & operator= (const Conv2dContent &)=default
Conv2dContent (Conv2dContent &&)=default
Conv2dContent & operator= (Conv2dContent &&)=default
bool operator== (const OperatorContent &other) const override
OperatorComplexity complexity () const override
void set_method (ConvolutionMethod method)
Status translate (ClKernelGraph &kernel_graph) const override
Public Member Functions inherited from OperatorContent
OperatorContent ()=default
OperatorContent (const OperatorGraph::Implementation *graph, Id id, const ITensorDescPack< OpTensorContent > &tensors)
OperatorContent (const OperatorContent &op)=default
OperatorContent & operator= (const OperatorContent &op)=default
OperatorContent (OperatorContent &&op)=default
OperatorContent & operator= (OperatorContent &&op)=default
virtual ~OperatorContent ()=default
Static Public Member Functions
static ConvolutionMethod select_conv_method (const ITensorInfo *src, const ITensorInfo *weights, const ITensorInfo *dst, const Conv2dDescriptor &conv2d_desc, const GPUTarget gpu_target)
Replicate heuristics of ClConv2d::get_convolution_method(), except that non-supported data types and data layouts are removed from the heuristics.
Data Fields
Conv2dDescriptor desc {}
ConvolutionMethod forced_method { ConvolutionMethod::GEMM_CONV2D }
bool forced_method_enabled { false }
Additional Inherited Members
Public Types inherited from OperatorContent
using Id = DependencyGraph::Id
Detailed Description
Definition at line 111 of file OperatorGraphImpl.h.
Constructor & Destructor Documentation
Conv2dContent() [1/5]
Conv2dContent () default
Conv2dContent() [2/5]
Conv2dContent (const OperatorGraph::Implementation * graph, Id id, const Conv2dDescriptor & desc, const ITensorDescPack< OpTensorContent > & tensors) inline
Definition at line 115 of file OperatorGraphImpl.h.
         : OperatorContent(graph, id, tensors), desc(desc), forced_method(), forced_method_enabled(false)
     {
     }
Conv2dContent() [3/5]
Conv2dContent (const OperatorGraph::Implementation * graph, Id id, const Conv2dDescriptor & desc, const ITensorDescPack< OpTensorContent > & tensors, ConvolutionMethod method) inline
Definition at line 120 of file OperatorGraphImpl.h.
References arm_compute::experimental::dynamic_fusion::operator==().
         : OperatorContent(graph, id, tensors), desc(desc), forced_method(method), forced_method_enabled(true)
     {
     }
~Conv2dContent()
~Conv2dContent () default
Conv2dContent() [4/5]
Conv2dContent (const Conv2dContent &) default
Conv2dContent() [5/5]
Conv2dContent (Conv2dContent &&) default
Member Function Documentation
complexity()
OperatorComplexity complexity () const inline override virtual
Implements OperatorContent.
Definition at line 130 of file OperatorGraphImpl.h.
References arm_compute::experimental::dynamic_fusion::Complex.
     {
         return OperatorComplexity::Complex;
     }
operator=() [1/2]
Conv2dContent& operator= (const Conv2dContent &) default
operator=() [2/2]
Conv2dContent& operator= (Conv2dContent &&) default
operator==()
bool operator== (const OperatorContent & other) const override virtual
Implements OperatorContent.
Definition at line 122 of file OperatorGraphImpl.cpp.
References Conv2dContent::desc.
 {
     const auto converted = *utils::cast::polymorphic_downcast<const Conv2dContent *>(&other);
     return desc == converted.desc;
 }
select_conv_method()
ConvolutionMethod select_conv_method (const ITensorInfo * src, const ITensorInfo * weights, const ITensorInfo * dst, const Conv2dDescriptor & conv2d_desc, const GPUTarget gpu_target) static
Replicate heuristics of ClConv2d::get_convolution_method(), except that non-supported data types and data layouts are removed from the heuristics.
Parameters
src
weights
dst
conv2d_desc
gpu_target
Returns
ConvolutionMethod
Definition at line 140 of file OperatorGraphImpl.cpp.
References ARM_COMPUTE_ERROR, ARM_COMPUTE_ERROR_ON_NULLPTR, Padding2D::bottom, arm_compute::CHANNEL, arm_compute::misc::shape_calculator::compute_deep_convolution_shape(), ITensorInfo::data_layout(), arm_compute::test::validation::data_layout, ITensorInfo::data_type(), Conv2dDescriptor::dilation, ITensorInfo::dimension(), arm_compute::DIRECT, arm_compute::FLOOR, arm_compute::G71, arm_compute::G72, arm_compute::GEMM, arm_compute::get_data_layout_dimension_index(), arm_compute::HEIGHT, arm_compute::test::validation::info, arm_compute::is_data_type_float(), Padding2D::left, arm_compute::MIDGARD, arm_compute::NCHW, arm_compute::NHWC, arm_compute::test::validation::output_shape, Conv2dDescriptor::pad, PadStrideInfo::pad_bottom(), PadStrideInfo::pad_left(), PadStrideInfo::pad_right(), PadStrideInfo::pad_top(), Padding2D::right, Conv2dDescriptor::stride, PadStrideInfo::stride(), Padding2D::top, arm_compute::utils::cast::U, ClDirectConv2dKernel::validate(), arm_compute::WIDTH, Size2D::x(), and Size2D::y().
Referenced by Conv2dContent::translate().
 {
     // Modified from ClConv2d::get_convolution_method
     ARM_COMPUTE_ERROR_ON_NULLPTR(src);
     ARM_COMPUTE_ERROR_ON_NULLPTR(dst);
     ARM_COMPUTE_ERROR_ON_NULLPTR(weights);
     const PadStrideInfo legacy_pad_stride(conv2d_desc.stride.x(), conv2d_desc.stride.y(), conv2d_desc.pad.left, conv2d_desc.pad.right, conv2d_desc.pad.top, conv2d_desc.pad.bottom, DimensionRoundingType{});
     const Size2D        dilation = conv2d_desc.dilation;
     const size_t idx_w = get_data_layout_dimension_index(src->data_layout(), DataLayoutDimension::WIDTH);
     const size_t idx_h = get_data_layout_dimension_index(src->data_layout(), DataLayoutDimension::HEIGHT);
     const size_t idx_c = get_data_layout_dimension_index(src->data_layout(), DataLayoutDimension::CHANNEL);
     /* Input spatial dims, kernel size, IFM/OFM, conv info*/
     using ConvolutionConfiguration = std::tuple<Size2D, Size2D, Size2D, PadStrideInfo, DataLayout>;
     using ConfigurationMethod      = std::pair<ConvolutionConfiguration, ConvolutionMethod>;
     const std::vector<ConfigurationMethod> known_configs =
     {
         // Alexnet
         ConfigurationMethod(ConvolutionConfiguration(Size2D(27U, 27U), Size2D(5U, 5U), Size2D(48U, 128U), PadStrideInfo(1U, 1U, 2U, 2U), DataLayout::NCHW), ConvolutionMethod::DIRECT),
         // VGG16 / VGG19
         ConfigurationMethod(ConvolutionConfiguration(Size2D(224U, 224U), Size2D(3U, 3U), Size2D(3U, 64U), PadStrideInfo(1U, 1U, 1U, 1U), DataLayout::NCHW), ConvolutionMethod::DIRECT),
         // Mobilenet 224
         ConfigurationMethod(ConvolutionConfiguration(Size2D(224U, 224U), Size2D(3U, 3U), Size2D(3U, 32U), PadStrideInfo(2U, 2U, 0U, 1U, 0U, 1U, DimensionRoundingType::FLOOR), DataLayout::NCHW), ConvolutionMethod::GEMM),
         // Mobilenet 160
         ConfigurationMethod(ConvolutionConfiguration(Size2D(160U, 160U), Size2D(3U, 3U), Size2D(3U, 24U), PadStrideInfo(2U, 2U, 0U, 1U, 0U, 1U, DimensionRoundingType::FLOOR), DataLayout::NCHW), ConvolutionMethod::GEMM),
         // Mobilenet 224
         ConfigurationMethod(ConvolutionConfiguration(Size2D(224U, 224U), Size2D(3U, 3U), Size2D(3U, 32U), PadStrideInfo(2U, 2U, 0U, 1U, 0U, 1U, DimensionRoundingType::FLOOR), DataLayout::NHWC), ConvolutionMethod::GEMM),
         // Mobilenet 160
         ConfigurationMethod(ConvolutionConfiguration(Size2D(160U, 160U), Size2D(3U, 3U), Size2D(3U, 24U), PadStrideInfo(2U, 2U, 0U, 1U, 0U, 1U, DimensionRoundingType::FLOOR), DataLayout::NHWC), ConvolutionMethod::GEMM),
     };
     const auto find_config = [&](ConfigurationMethod c)
     {
         const ConvolutionConfiguration config      = c.first;
         const PadStrideInfo            info        = std::get<3>(config);
         const DataLayout               data_layout = std::get<4>(config);
         return std::get<0>(config) == Size2D(src->dimension(idx_w), src->dimension(idx_h)) && std::get<1>(config) == Size2D(weights->dimension(idx_w), weights->dimension(idx_h))
                && std::get<2>(config) == Size2D(weights->dimension(idx_c), weights->dimension(3)) && info.pad_top() == legacy_pad_stride.pad_top() && info.pad_right() == legacy_pad_stride.pad_right()
                && info.pad_bottom() == legacy_pad_stride.pad_bottom() && info.pad_left() == legacy_pad_stride.pad_left() && info.stride() == legacy_pad_stride.stride() && (data_layout == src->data_layout());
     };
     std::vector<ConfigurationMethod>::const_iterator found;
     if((found = std::find_if(known_configs.begin(), known_configs.end(), find_config)) != known_configs.end())
     {
         return (*found).second;
     }
     if(dilation != Size2D(1U, 1U))
     {
         return ConvolutionMethod::GEMM;
     }
     else
     {
         if(src->data_layout() == DataLayout::NCHW)
         {
             ARM_COMPUTE_ERROR("NCHW not supported");
         }
         else
         {
             const bool   is_direct_valid           = bool(ClDirectConv2dKernel::validate(src, weights, nullptr, dst, ClDirectConv2dKernelDescriptor{ conv2d_desc }));
             const size_t kernel_sz_direct_conv_thr = get_direct_conv_kernel_threshold_nhwc(gpu_target);
             // SRGAN case
             if((src->dimension(idx_h) > 720U) && (dst->dimension(idx_h) > 720U) && (weights->dimension(idx_h) == 9) && (conv2d_desc.pad.top < 3)
                && is_direct_valid)
             {
                 return ConvolutionMethod::DIRECT;
             }
             // Floating-point case: GeMM/Direct
             if(is_data_type_float(src->data_type()))
             {
                 // Get dst shape
                 TensorShape output_shape       = misc::shape_calculator::compute_deep_convolution_shape(*src, *weights, legacy_pad_stride);
                 const bool  is_large_kernel_sz = (weights->dimension(idx_w) >= kernel_sz_direct_conv_thr) && (weights->dimension(idx_h) >= kernel_sz_direct_conv_thr);
                 const bool  is_ifm_ge_16       = src->dimension(idx_c) >= 16;
                 const bool  is_ofm_lte_8       = weights->dimension(3U) <= 8;
                 const bool  workload_gte_8192  = (output_shape[0] * output_shape[1] * output_shape[2]) / 16 >= 8192;
                 const bool  is_ifm_gt_ofm      = src->dimension(idx_c) > weights->dimension(3U);
                 // Direct convolution case
                 if(is_direct_valid)
                 {
                     if((gpu_target == arm_compute::GPUTarget::G71 || gpu_target == arm_compute::GPUTarget::G72 || gpu_target == arm_compute::GPUTarget::MIDGARD))
                     {
                         if(is_large_kernel_sz && is_ifm_ge_16 && is_ifm_gt_ofm)
{
                             return ConvolutionMethod::DIRECT;
                         }
                     }
                     else
                     {
                         if((is_large_kernel_sz && workload_gte_8192 && is_ifm_ge_16) || (is_ofm_lte_8 && is_ifm_ge_16))
{
                             return ConvolutionMethod::DIRECT;
                         }
                     }
                 }
                 // Default case
                 return ConvolutionMethod::GEMM;
             }
             // Generic case for quantized. Only GeMM
             return ConvolutionMethod::GEMM;
         }
     }
     return ConvolutionMethod::DIRECT;
 }
set_method()
void set_method (ConvolutionMethod method) inline
Definition at line 134 of file OperatorGraphImpl.h.
References arm_compute::test::validation::conv2d_desc, arm_compute::test::validation::dst, arm_compute::test::validation::src, and arm_compute::experimental::dynamic_fusion::translate().
     {
         forced_method_enabled = true;
         forced_method         = method;
     }
translate()
Status translate (ClKernelGraph & kernel_graph) const override virtual
Implements OperatorContent.
Definition at line 255 of file OperatorGraphImpl.cpp.
References arm_compute::ACL_DST_0, arm_compute::ACL_SRC_0, arm_compute::ACL_SRC_1, arm_compute::ACL_SRC_2, ITensorDescPack< TDesc >::add_const_tensor(), ClKernelGraph::add_kernel(), ARM_COMPUTE_ERROR_ON_NULLPTR, ARM_COMPUTE_RETURN_ERROR_MSG, ARM_COMPUTE_RETURN_ON_ERROR, ARM_COMPUTE_UNUSED, bias, Conv2dContent::desc, arm_compute::DIRECT, arm_compute::test::validation::dst, Conv2dContent::forced_method, Conv2dContent::forced_method_enabled, CLScheduler::get(), ClKernelGraph::get_tensor(), arm_compute::test::validation::input, UnitWorkloadStage::Run, Conv2dContent::select_conv_method(), CLScheduler::target(), arm_compute::experimental::dynamic_fusion::TStoreIndirectWidthSelect, and ClDirectConv2dKernel::validate().
 {
     const auto input  = _tensors.get_const_tensor(TensorType::ACL_SRC_0);
     const auto weight = _tensors.get_const_tensor(TensorType::ACL_SRC_1);
     const auto dst    = _tensors.get_const_tensor(TensorType::ACL_DST_0);
     const auto method = forced_method_enabled ? forced_method : Conv2dContent::select_conv_method(input->desc, weight->desc, dst->desc, desc, CLScheduler::get().target());
     switch(method)
     {
         case ConvolutionMethod::DIRECT:
         {
             return translate_direct_conv2d(kernel_graph);
         }
         default:
         {
             ARM_COMPUTE_RETURN_ERROR_MSG("Not implemented");
         }
     }
     return Status{};
 }
Field Documentation
desc
Conv2dDescriptor desc {}
Definition at line 152 of file OperatorGraphImpl.h.
Referenced by Conv2dContent::operator==(), ElementwiseContent::operator==(), FloorContent::operator==(), Conv2dContent::translate(), ElementwiseContent::translate(), and FloorContent::translate().
forced_method
ConvolutionMethod forced_method { ConvolutionMethod::GEMM_CONV2D }
Definition at line 153 of file OperatorGraphImpl.h.
Referenced by Conv2dContent::translate().
forced_method_enabled
bool forced_method_enabled { false }
Definition at line 154 of file OperatorGraphImpl.h.
Referenced by Conv2dContent::translate().
The documentation for this struct was generated from the following files:
src/core/experimental/dynamic_fusion/WorkloadImpl/OperatorGraphImpl.h
src/core/experimental/dynamic_fusion/WorkloadImpl/OperatorGraphImpl.cpp