Compute Library: GemmImplementation< Top, Tret, Nothing > Struct Template Reference
GemmImplementation< Top, Tret, Nothing > Struct Template Reference
#include <gemm_implementation.hpp>
Public Member Functions
bool do_is_supported (const GemmArgs &args, const Nothing &) const
uint64_t do_cycle_estimate (const GemmArgs &args, const Nothing &) const
GemmCommon< Top, Tret > * do_instantiate (const GemmArgs &args, const Nothing &) const
GemmImplementation (const GemmImplementation &)=default
GemmImplementation & operator= (const GemmImplementation &)=default
GemmImplementation (GemmMethod m, const char *n, KernelWeightFormat f=KernelWeightFormat::NON_FIXED)
GemmImplementation (GemmMethod m, const char *n, std::function< bool(const GemmArgs &)> is_supported, std::function< bool(const GemmArgs &)> is_recommended, std::function< GemmCommon< Top, Tret > *(const GemmArgs &)> instantiate)
GemmImplementation (GemmMethod m, const char *n, KernelWeightFormat kwf, std::function< bool(const GemmArgs &)> is_supported, std::function< bool(const GemmArgs &)> is_recommended, std::function< GemmCommon< Top, Tret > *(const GemmArgs &)> instantiate)
Static Public Member Functions
static GemmImplementation with_estimate (GemmMethod m, const char *n, std::function< bool(const GemmArgs &)> is_supported, std::function< uint64_t(const GemmArgs &)> cycle_estimate, std::function< GemmCommon< Top, Tret > *(const GemmArgs &)> instantiate)
static GemmImplementation with_estimate (GemmMethod m, const char *n, KernelWeightFormat f, std::function< bool(const GemmArgs &)> is_supported, std::function< uint64_t(const GemmArgs &)> cycle_estimate, std::function< GemmCommon< Top, Tret > *(const GemmArgs &)> instantiate)
Data Fields
const GemmMethod method
const char * name
const KernelWeightFormat kernel_weight_format = KernelWeightFormat::NON_FIXED
std::function< bool(const GemmArgs &)> is_supported = {}
std::function< uint64_t(const GemmArgs &)> cycle_estimate = {}
std::function< GemmCommon< Top, Tret > *(const GemmArgs &)> instantiate = {}
Detailed Description
template<typename Top, typename Tret>
struct arm_gemm::GemmImplementation< Top, Tret, Nothing >
Definition at line 123 of file gemm_implementation.hpp.
Constructor & Destructor Documentation
GemmImplementation() [1/4]
GemmImplementation (const GemmImplementation< Top, Tret, Nothing > &) default
GemmImplementation() [2/4]
GemmImplementation (GemmMethod m, const char * n, KernelWeightFormat f = KernelWeightFormat::NON_FIXED) inline
Definition at line 198 of file gemm_implementation.hpp.
 : method(m), name(n), kernel_weight_format(f) {}
GemmImplementation() [3/4]
GemmImplementation (GemmMethod m, const char * n, std::function< bool(const GemmArgs &)> is_supported, std::function< bool(const GemmArgs &)> is_recommended, std::function< GemmCommon< Top, Tret > *(const GemmArgs &)> instantiate) inline
Definition at line 200 of file gemm_implementation.hpp.
References GemmTuner::args, and GemmImplementation< Top, Tret, OutputStage >::instantiate.
                                                                                            :
                        method(m), name(n), is_supported(is_supported),
                        cycle_estimate( [is_recommended](const GemmArgs &args) -> uint64_t { return (is_recommended == nullptr) ? 0 : (is_recommended(args) ? 0 : UINT64_MAX); } ),
                        instantiate(instantiate) {   }
GemmImplementation() [4/4]
GemmImplementation (GemmMethod m, const char * n, KernelWeightFormat kwf, std::function< bool(const GemmArgs &)> is_supported, std::function< bool(const GemmArgs &)> is_recommended, std::function< GemmCommon< Top, Tret > *(const GemmArgs &)> instantiate) inline
Definition at line 207 of file gemm_implementation.hpp.
References GemmTuner::args, arm_gemm::gemm_implementation_list(), and GemmImplementation< Top, Tret, OutputStage >::instantiate.
                                                                                            :
                        method(m), name(n), kernel_weight_format(kwf), is_supported(is_supported),
                        cycle_estimate( [is_recommended](const GemmArgs &args) -> uint64_t { return (is_recommended == nullptr) ? 0 : (is_recommended(args) ? 0 : UINT64_MAX); } ),
                        instantiate(instantiate) {   }
Member Function Documentation
do_cycle_estimate()
uint64_t do_cycle_estimate (const GemmArgs & args, const Nothing &) const inline
Definition at line 159 of file gemm_implementation.hpp.
References GemmImplementation< Top, Tret, OutputStage >::cycle_estimate.
{
         if (cycle_estimate != nullptr) {
             return cycle_estimate(args);
         } else {
             return 0;
         }
     }
do_instantiate()
GemmCommon<Top, Tret>* do_instantiate (const GemmArgs & args, const Nothing &) const inline
Definition at line 167 of file gemm_implementation.hpp.
References GemmImplementation< Top, Tret, OutputStage >::instantiate.
{
         return instantiate(args);
     }
do_is_supported()
bool do_is_supported (const GemmArgs & args, const Nothing &) const inline
Definition at line 131 of file gemm_implementation.hpp.
References GemmArgs::_cfg, GemmArgs::_fixed_format, arm_gemm::ANY, arm_gemm::get_weight_format(), GemmImplementation< Top, Tret, OutputStage >::is_supported, arm_gemm::NON_FIXED, and GemmConfig::weight_format.
{
     // Check supplied is_supported() function first.
         if (is_supported != nullptr && !is_supported(args)) {
             return false;
         }
         // Check weight format is appropriate.
         if (args._fixed_format == false) {
             // Can't return a fixed format kernel if we weren't asked for one.
             return (kernel_weight_format == KernelWeightFormat::NON_FIXED);
         } else {
             // Fixed format kernel requested: if this is a non-fixed format kernel we can't use it.
             if (kernel_weight_format == KernelWeightFormat::NON_FIXED) {
                 return false;
             }
             // If there's no config, or the config says ANY then this one is OK.
             if (!args._cfg || args._cfg->weight_format == WeightFormat::ANY) {
                 return true;
             }
             // If we get here it means there is a config and it specifies a format.  Check it matches this kernel.
             // NOTE: this will execute SVE instructions if it's an SVE kernel, so it's important that is_supported()
             // was called above first.
             return (args._cfg->weight_format == get_weight_format(kernel_weight_format, sizeof(Top)));
         }
     }
operator=()
GemmImplementation& operator= (const GemmImplementation< Top, Tret, Nothing > &) default
with_estimate() [1/2]
static GemmImplementation with_estimate (GemmMethod m, const char * n, std::function< bool(const GemmArgs &)> is_supported, std::function< uint64_t(const GemmArgs &)> cycle_estimate, std::function< GemmCommon< Top, Tret > *(const GemmArgs &)> instantiate) inline static
Definition at line 171 of file gemm_implementation.hpp.
References GemmImplementation< Top, Tret, OutputStage >::cycle_estimate, GemmImplementation< Top, Tret, OutputStage >::instantiate, and GemmImplementation< Top, Tret, OutputStage >::is_supported.
{
         GemmImplementation impl(m,n);
         impl.is_supported=is_supported;
         impl.cycle_estimate=cycle_estimate;
         impl.instantiate=instantiate;
         return impl;
     }
with_estimate() [2/2]
static GemmImplementation with_estimate (GemmMethod m, const char * n, KernelWeightFormat f, std::function< bool(const GemmArgs &)> is_supported, std::function< uint64_t(const GemmArgs &)> cycle_estimate, std::function< GemmCommon< Top, Tret > *(const GemmArgs &)> instantiate) inline static
Definition at line 183 of file gemm_implementation.hpp.
References GemmImplementation< Top, Tret, OutputStage >::cycle_estimate, GemmImplementation< Top, Tret, OutputStage >::GemmImplementation(), GemmImplementation< Top, Tret, OutputStage >::instantiate, GemmImplementation< Top, Tret, OutputStage >::is_supported, and GemmImplementation< Top, Tret, OutputStage >::operator=().
{
         GemmImplementation impl(m,n,f);
         impl.is_supported=is_supported;
         impl.cycle_estimate=cycle_estimate;
         impl.instantiate=instantiate;
         return impl;
     }
Field Documentation
cycle_estimate
std::function<uint64_t(const GemmArgs &)> cycle_estimate = {}
Definition at line 128 of file gemm_implementation.hpp.
instantiate
std::function<GemmCommon<Top, Tret> *(const GemmArgs &)> instantiate = {}
Definition at line 129 of file gemm_implementation.hpp.
is_supported
std::function<bool(const GemmArgs &)> is_supported = {}
Definition at line 127 of file gemm_implementation.hpp.
kernel_weight_format
const KernelWeightFormat kernel_weight_format = KernelWeightFormat::NON_FIXED
Definition at line 126 of file gemm_implementation.hpp.
method
const GemmMethod method
Definition at line 124 of file gemm_implementation.hpp.
name
const char* name
Definition at line 125 of file gemm_implementation.hpp.
The documentation for this struct was generated from the following file:
src/core/NEON/kernels/arm_gemm/gemm_implementation.hpp