Compute Library: ClDirectConv2dKernel Struct Reference
ClDirectConv2dKernel Struct Reference
#include <ClKernelGraph.h>
Public Member Functions
Complexity complexity () const override
ClDirectConv2dKernel ()=default
~ClDirectConv2dKernel () override=default
ClDirectConv2dKernel (const ClKernelGraph *graph, Id id, const ClKernelConfig config, const ClDirectConv2dKernelDescriptor &desc, const ITensorDescPack< ClKernelTensor > tensors)
bool operator== (const ClKernel &other) const override
Status generate (ClKernelBlueprint &bp) const override
Public Member Functions inherited from ClKernel
ClKernel ()=default
virtual ~ClKernel ()=default
ClKernel (const ClKernel &kernel)=default
ClKernel & operator= (const ClKernel &kernel)=default
ClKernel (ClKernel &&kernel)=default
ClKernel & operator= (ClKernel &&kernel)=default
ClKernel (const ClKernelGraph *graph, Id id, const ClKernelConfig &config, const ITensorDescPack< ClKernelTensor > &tensors)
Id id () const
ITensorDescPack< ClKernelTensor > tensors () const
ClKernelConfig config () const
Static Public Member Functions
static Status validate (const ITensorInfo *src, const ITensorInfo *weights, const ITensorInfo *biases, const ITensorInfo *dst, const ClDirectConv2dKernelDescriptor &conv2d_desc)
Data Fields
ClDirectConv2dKernelDescriptor desc {}
Additional Inherited Members
Public Types inherited from ClKernel
using Id = DependencyGraph::Id
Detailed Description
Definition at line 122 of file ClKernelGraph.h.
Constructor & Destructor Documentation
ClDirectConv2dKernel() [1/2]
ClDirectConv2dKernel () default
~ClDirectConv2dKernel()
~ClDirectConv2dKernel () override default
ClDirectConv2dKernel() [2/2]
ClDirectConv2dKernel (const ClKernelGraph * graph, Id id, const ClKernelConfig config, const ClDirectConv2dKernelDescriptor & desc, const ITensorDescPack< ClKernelTensor > tensors) inline
Definition at line 131 of file ClKernelGraph.h.
References arm_compute::test::validation::conv2d_desc, arm_compute::test::validation::dst, arm_compute::experimental::dynamic_fusion::generate(), arm_compute::experimental::dynamic_fusion::operator==(), arm_compute::test::validation::src, and arm_compute::experimental::dynamic_fusion::validate().
         : ClKernel{ graph, id, config, tensors }, desc{ desc }
     {
     }
Member Function Documentation
complexity()
Complexity complexity () const inline override virtual
Implements ClKernel.
Definition at line 125 of file ClKernelGraph.h.
References arm_compute::experimental::dynamic_fusion::Complex.
     {
         return Complexity::Complex;
     }
generate()
Status generate (ClKernelBlueprint & bp) const override virtual
Implements ClKernel.
Definition at line 39 of file ClKernelGraph.cpp.
References arm_compute::ACL_DST_0, arm_compute::ACL_SRC_0, arm_compute::ACL_SRC_1, arm_compute::ACL_SRC_2, arm_compute::experimental::dynamic_fusion::add_kcomp_direct_conv2d(), arm_compute::experimental::dynamic_fusion::add_tensor(), ARM_COMPUTE_ERROR_ON_NULLPTR, bias, ClDirectConv2dKernel::desc, arm_compute::test::validation::dst, and arm_compute::test::validation::input.
 {
     const auto input  = _tensors.get_const_tensor(TensorType::ACL_SRC_0);
     const auto weight = _tensors.get_const_tensor(TensorType::ACL_SRC_1);
     const auto bias   = _tensors.get_const_tensor(TensorType::ACL_SRC_2);
     const auto dst    = _tensors.get_const_tensor(TensorType::ACL_DST_0);
     ARM_COMPUTE_ERROR_ON_NULLPTR(input, weight, dst);
     ArgumentID input_id;
     add_tensor(bp, input->desc, input_id, input->id);
     ArgumentID weight_id;
     add_tensor(bp, weight->desc, weight_id, weight->id);
     ArgumentID bias_id = g_arg_placeholder;
     if(bias != nullptr)
     {
         add_tensor(bp, bias->desc, bias_id, bias->id);
     }
     ArgumentID dst_id;
     add_tensor(bp, dst->desc, dst_id, dst->id);
     add_kcomp_direct_conv2d(bp, desc, input_id, weight_id, bias_id, dst_id);
     return Status{};
 }
operator==()
bool operator== (const ClKernel & other) const override virtual
Implements ClKernel.
Definition at line 121 of file ClKernelGraph.cpp.
References ClKernel::config(), ClDirectConv2dKernel::desc, and ClKernel::tensors().
 {
     const auto converted = *utils::cast::polymorphic_downcast<const ClDirectConv2dKernel *>(&other);
     return config() == other.config() && tensors() == other.tensors() && desc == converted.desc;
 }
validate()
Status validate (const ITensorInfo * src, const ITensorInfo * weights, const ITensorInfo * biases, const ITensorInfo * dst, const ClDirectConv2dKernelDescriptor & conv2d_desc) static
Definition at line 61 of file ClKernelGraph.cpp.
References ARM_COMPUTE_RETURN_ERROR_ON, ARM_COMPUTE_RETURN_ERROR_ON_DATA_LAYOUT_NOT_IN, ARM_COMPUTE_RETURN_ERROR_ON_DATA_TYPE_CHANNEL_NOT_IN, ARM_COMPUTE_RETURN_ERROR_ON_F16_UNSUPPORTED, ARM_COMPUTE_RETURN_ERROR_ON_MISMATCHING_DATA_LAYOUT, ARM_COMPUTE_RETURN_ERROR_ON_MISMATCHING_DATA_TYPES, ARM_COMPUTE_RETURN_ERROR_ON_MISMATCHING_DIMENSIONS, ARM_COMPUTE_RETURN_ERROR_ON_MSG, ARM_COMPUTE_RETURN_ERROR_ON_NULLPTR, Padding2D::bottom, arm_compute::CHANNEL, arm_compute::misc::shape_calculator::compute_deep_convolution_shape(), ClDirectConv2dKernelDescriptor::conv2d, ITensorInfo::data_layout(), arm_compute::test::validation::data_layout, ITensorInfo::dimension(), arm_compute::F16, arm_compute::F32, arm_compute::get_data_layout_dimension_index(), Padding2D::left, arm_compute::NHWC, ITensorInfo::num_dimensions(), Conv2dDescriptor::pad, Padding2D::right, Conv2dDescriptor::stride, ITensorInfo::tensor_shape(), Padding2D::top, TensorShape::total_size(), Size2D::x(), and Size2D::y().
Referenced by Conv2dContent::select_conv_method(), and Conv2dContent::translate().
 {
     // 1. Check validity
     ARM_COMPUTE_RETURN_ERROR_ON_NULLPTR(src, weights, dst);
     // Matching data type
     ARM_COMPUTE_RETURN_ERROR_ON_MISMATCHING_DATA_TYPES(src, weights);
     ARM_COMPUTE_RETURN_ERROR_ON_MISMATCHING_DATA_TYPES(src, dst);
     if(biases != nullptr)
     {
         ARM_COMPUTE_RETURN_ERROR_ON_MISMATCHING_DATA_TYPES(src, biases);
     }
     // Matching data layout
     ARM_COMPUTE_RETURN_ERROR_ON_MISMATCHING_DATA_LAYOUT(src, weights);
     ARM_COMPUTE_RETURN_ERROR_ON_MISMATCHING_DATA_LAYOUT(src, dst);
     if(biases != nullptr)
     {
         ARM_COMPUTE_RETURN_ERROR_ON_MISMATCHING_DATA_LAYOUT(src, biases);
     }
     // All tensor infos are initialized
     ARM_COMPUTE_RETURN_ERROR_ON(src->tensor_shape().total_size() == 0);
     ARM_COMPUTE_RETURN_ERROR_ON(weights->tensor_shape().total_size() == 0);
     ARM_COMPUTE_RETURN_ERROR_ON(dst->tensor_shape().total_size() == 0);
     if(biases != nullptr)
     {
         ARM_COMPUTE_RETURN_ERROR_ON(biases->tensor_shape().total_size() == 0);
     }
     // Device requirements are met
     ARM_COMPUTE_RETURN_ERROR_ON_F16_UNSUPPORTED(src);
     // weights shape is correct
     const DataLayout data_layout = src->data_layout();
     const int        channel_idx = get_data_layout_dimension_index(data_layout, DataLayoutDimension::CHANNEL);
     ARM_COMPUTE_RETURN_ERROR_ON_MSG(weights->dimension(channel_idx) != src->dimension(channel_idx), "Weights feature map dimension should match the respective src's one");
     ARM_COMPUTE_RETURN_ERROR_ON_MSG(weights->num_dimensions() > 4, "Weights can be at most 4 dimensional");
     // dst shape is correct
     PadStrideInfo legacy_pad_stride(conv2d_desc.conv2d.stride.x(), conv2d_desc.conv2d.stride.y(), conv2d_desc.conv2d.pad.left, conv2d_desc.conv2d.pad.right, conv2d_desc.conv2d.pad.top,
                                     conv2d_desc.conv2d.pad.bottom, DimensionRoundingType{});
     ARM_COMPUTE_RETURN_ERROR_ON_MISMATCHING_DIMENSIONS(dst->tensor_shape(),
                                                        misc::shape_calculator::compute_deep_convolution_shape(*src, *weights, legacy_pad_stride));
     // biases shape is correct
     if(biases != nullptr)
     {
         ARM_COMPUTE_RETURN_ERROR_ON_MSG(biases->dimension(0) != weights->dimension(3),
                                         "Biases size and number of dst feature maps should match");
         ARM_COMPUTE_RETURN_ERROR_ON_MSG(biases->num_dimensions() > 1,
                                         "Biases should be one dimensional");
     }
     // 2. Check support level
     // Data type
     ARM_COMPUTE_RETURN_ERROR_ON_DATA_TYPE_CHANNEL_NOT_IN(src, 1, DataType::F16, DataType::F32);
     // Data layout
     ARM_COMPUTE_RETURN_ERROR_ON_DATA_LAYOUT_NOT_IN(src, DataLayout::NHWC);
     return Status{};
 }
Field Documentation
desc
ClDirectConv2dKernelDescriptor desc {}
Definition at line 139 of file ClKernelGraph.h.
Referenced by ClDirectConv2dKernel::generate(), ClElementwiseKernel::generate(), ClFloorKernel::generate(), ClDirectConv2dKernel::operator==(), ClElementwiseKernel::operator==(), and ClFloorKernel::operator==().
The documentation for this struct was generated from the following files:
src/core/experimental/dynamic_fusion/WorkloadImpl/ClKernelGraph.h
src/core/experimental/dynamic_fusion/WorkloadImpl/ClKernelGraph.cpp