Compute Library: ClFloorKernel Struct Reference
ClFloorKernel Struct Reference
#include <ClKernelGraph.h>
Public Member Functions
Complexity complexity () const override
ClFloorKernel ()=default
~ClFloorKernel () override=default
ClFloorKernel (const ClKernelGraph *graph, Id id, const ClKernelConfig &config, const ClFloorKernelDescriptor &desc, const ITensorDescPack< ClKernelTensor > tensors)
bool operator== (const ClKernel &other) const override
Status generate (ClKernelBlueprint &bp) const override
Public Member Functions inherited from ClKernel
ClKernel ()=default
virtual ~ClKernel ()=default
ClKernel (const ClKernel &kernel)=default
ClKernel & operator= (const ClKernel &kernel)=default
ClKernel (ClKernel &&kernel)=default
ClKernel & operator= (ClKernel &&kernel)=default
ClKernel (const ClKernelGraph *graph, Id id, const ClKernelConfig &config, const ITensorDescPack< ClKernelTensor > &tensors)
Id id () const
ITensorDescPack< ClKernelTensor > tensors () const
ClKernelConfig config () const
Static Public Member Functions
static Status validate (const ITensorInfo *src, const ITensorInfo *dst)
Data Fields
ClFloorKernelDescriptor desc {}
Additional Inherited Members
Public Types inherited from ClKernel
using Id = DependencyGraph::Id
Detailed Description
Definition at line 162 of file ClKernelGraph.h.
Constructor & Destructor Documentation
ClFloorKernel() [1/2]
ClFloorKernel () default
~ClFloorKernel()
~ClFloorKernel () override default
ClFloorKernel() [2/2]
ClFloorKernel (const ClKernelGraph * graph, Id id, const ClKernelConfig & config, const ClFloorKernelDescriptor & desc, const ITensorDescPack< ClKernelTensor > tensors) inline
Definition at line 171 of file ClKernelGraph.h.
References arm_compute::test::validation::dst, arm_compute::experimental::dynamic_fusion::generate(), arm_compute::experimental::dynamic_fusion::operator==(), arm_compute::test::validation::src, and arm_compute::experimental::dynamic_fusion::validate().
         : ClKernel{ graph, id, config, tensors }, desc{ desc }
     {
     }
Member Function Documentation
complexity()
Complexity complexity () const inline override virtual
Implements ClKernel.
Definition at line 165 of file ClKernelGraph.h.
References arm_compute::experimental::dynamic_fusion::Simple.
     {
         return Complexity::Simple;
     }
generate()
Status generate (ClKernelBlueprint & bp) const override virtual
Implements ClKernel.
Definition at line 195 of file ClKernelGraph.cpp.
References arm_compute::ACL_DST_0, arm_compute::ACL_SRC_0, arm_compute::experimental::dynamic_fusion::add_kcomp_floor(), arm_compute::experimental::dynamic_fusion::add_tensor(), ARM_COMPUTE_ERROR_ON_NULLPTR, ClDirectConv2dKernel::desc, arm_compute::test::validation::dst, and arm_compute::test::validation::src.
 {
     const auto src = _tensors.get_const_tensor(TensorType::ACL_SRC_0);
     const auto dst = _tensors.get_const_tensor(TensorType::ACL_DST_0);
     ARM_COMPUTE_ERROR_ON_NULLPTR(src, dst);
     ArgumentID src_id;
     add_tensor(bp, src->desc, src_id, src->id);
     ArgumentID dst_id;
     add_tensor(bp, dst->desc, dst_id, dst->id);
     add_kcomp_floor(bp, desc, src_id, dst_id);
     return Status{};
 }
operator==()
bool operator== (const ClKernel & other) const override virtual
Implements ClKernel.
Definition at line 241 of file ClKernelGraph.cpp.
References ClKernel::config(), ClDirectConv2dKernel::desc, and ClKernel::tensors().
 {
     const auto converted = *utils::cast::polymorphic_downcast<const ClFloorKernel *>(&other);
     return config() == other.config() && tensors() == other.tensors() && desc == converted.desc;
 }
validate()
Status validate (const ITensorInfo * src, const ITensorInfo * dst) static
Definition at line 209 of file ClKernelGraph.cpp.
References ARM_COMPUTE_RETURN_ERROR_ON, ARM_COMPUTE_RETURN_ERROR_ON_DATA_LAYOUT_NOT_IN, ARM_COMPUTE_RETURN_ERROR_ON_DATA_TYPE_CHANNEL_NOT_IN, ARM_COMPUTE_RETURN_ERROR_ON_F16_UNSUPPORTED, ARM_COMPUTE_RETURN_ERROR_ON_MISMATCHING_DATA_LAYOUT, ARM_COMPUTE_RETURN_ERROR_ON_MISMATCHING_DATA_TYPES, ARM_COMPUTE_RETURN_ERROR_ON_MSG, ARM_COMPUTE_RETURN_ERROR_ON_NULLPTR, arm_compute::F16, arm_compute::F32, arm_compute::detail::have_different_dimensions(), arm_compute::NHWC, ITensorInfo::tensor_shape(), and TensorShape::total_size().
Referenced by FloorContent::translate().
 {
     // 1. Check validity
     ARM_COMPUTE_RETURN_ERROR_ON_NULLPTR(src, dst);
     // Matching data type
     ARM_COMPUTE_RETURN_ERROR_ON_MISMATCHING_DATA_TYPES(src, dst);
     // Matching data layout
     ARM_COMPUTE_RETURN_ERROR_ON_MISMATCHING_DATA_LAYOUT(src, dst);
     // All tensor infos are initialized
     ARM_COMPUTE_RETURN_ERROR_ON(src->tensor_shape().total_size() == 0);
     ARM_COMPUTE_RETURN_ERROR_ON(dst->tensor_shape().total_size() == 0);
     // Device requirements are met
     ARM_COMPUTE_RETURN_ERROR_ON_F16_UNSUPPORTED(src);
     // dst shape is correct
     ARM_COMPUTE_RETURN_ERROR_ON_MSG(detail::have_different_dimensions(src->tensor_shape(), dst->tensor_shape(), 0), "Wrong shape for dst");
     // 2. Check support level
     // Data type
     ARM_COMPUTE_RETURN_ERROR_ON_DATA_TYPE_CHANNEL_NOT_IN(src, 1, DataType::F32, DataType::F16);
     // Data layout
     ARM_COMPUTE_RETURN_ERROR_ON_DATA_LAYOUT_NOT_IN(src, DataLayout::NHWC);
     return Status{};
 }
Field Documentation
desc
ClFloorKernelDescriptor desc {}
Definition at line 179 of file ClKernelGraph.h.
The documentation for this struct was generated from the following files:
src/core/experimental/dynamic_fusion/WorkloadImpl/ClKernelGraph.h
src/core/experimental/dynamic_fusion/WorkloadImpl/ClKernelGraph.cpp