Compute Library: GpuCkwElementwiseBinary Class Reference
GpuCkwElementwiseBinary Class Reference
#include <GpuCkwElementwiseBinary.h>
Public Types
using Attributes = ClComponentElementwiseBinary::Attributes
Public Types inherited from IGpuCkwComponentDriver
using ComponentGroup = GpuKernelComponentGroup
Public Member Functions
GpuCkwElementwiseBinary (ComponentId id, const ArgumentPack< ITensorInfo > &tensors, const Attributes &attributes)
Constructor.
ARM_COMPUTE_DISALLOW_COPY_ALLOW_MOVE (GpuCkwElementwiseBinary)
~GpuCkwElementwiseBinary () override=default
Destructor.
virtual void write_component_code (const ComponentGroup &comp_group, GpuCkwVariableTable &vtable, GpuCkwScopedKernelWriter writer) const override
Generate kernel component code.
Window get_window () const override
Generate the execution window for the component.
std::string get_name (const ComponentGroup &comp_group) const override
Generate the name of the component.
std::string get_tuner_id (const ComponentGroup &comp_group) const override
Generate the tuner id of the component This id should capture all the parameters that distinguish one kernel's lws tuning from another.
Public Member Functions inherited from IGpuCkwComponentDriver
IGpuCkwComponentDriver (ComponentId id, const ArgumentPack< ITensorInfo > &tensors)
Constructor.
virtual ~IGpuCkwComponentDriver ()
Destructor.
ArgumentPack< ITensorInfo > tensors () const
Get tensor arguments.
ComponentId id () const
Get component id.
Detailed Description
Definition at line 37 of file GpuCkwElementwiseBinary.h.
Member Typedef Documentation
Attributes
using Attributes = ClComponentElementwiseBinary::Attributes
Definition at line 40 of file GpuCkwElementwiseBinary.h.
Constructor & Destructor Documentation
GpuCkwElementwiseBinary()
GpuCkwElementwiseBinary (ComponentId id, const ArgumentPack< ITensorInfo > & tensors, const Attributes & attributes)
Constructor.
For supported configurations please refer to ClComponentElementwiseBinary::validate()
Parameters
[in] id Component id
[in] tensors Tensor arguments to the component
[in] attributes Component attributes
Definition at line 55 of file GpuCkwElementwiseBinary.cpp.
     : IGpuCkwComponentDriver{id, tensors}, _lhs{}, _rhs{}, _dst{}, _attributes{attributes}
 {
     _lhs = this->tensors().get_const_tensor(TensorType::ACL_SRC_0);
     _rhs = this->tensors().get_const_tensor(TensorType::ACL_SRC_1);
     _dst = this->tensors().get_const_tensor(TensorType::ACL_DST_0);
     ARM_COMPUTE_ERROR_ON_NULLPTR(_lhs, _rhs, _dst);
 }
References IGpuCkwComponentDriver::id(), and IGpuCkwComponentDriver::tensors().
~GpuCkwElementwiseBinary()
~GpuCkwElementwiseBinary () override default
Destructor.
Member Function Documentation
ARM_COMPUTE_DISALLOW_COPY_ALLOW_MOVE()
ARM_COMPUTE_DISALLOW_COPY_ALLOW_MOVE (GpuCkwElementwiseBinary)
get_name()
std::string get_name (const ComponentGroup & comp_group) const override virtual
Generate the name of the component.
This will be concatenated with other components' names to form the name of the kernel
Reimplemented from IGpuCkwComponentDriver.
Definition at line 149 of file GpuCkwElementwiseBinary.cpp.
 {
     ARM_COMPUTE_UNUSED(comp_group);
     const std::vector<std::string> build_params = {
         "elementwise_binary",
         "op",
         to_string(_attributes.operation()),
         "dt",
         lower_string(string_from_data_type(_dst->data_type())),
     };
     return join(build_params, "_");
 }
References ARM_COMPUTE_UNUSED, ITensorInfo::data_type(), arm_compute::join(), arm_compute::lower_string(), ElementwiseBinaryCommonAttributes::operation(), arm_compute::string_from_data_type(), and arm_compute::to_string().
get_tuner_id()
std::string get_tuner_id (const ComponentGroup & comp_group) const override virtual
Generate the tuner id of the component This id should capture all the parameters that distinguish one kernel's lws tuning from another.
e.g. two components that are identical in every other way, but have output tensor dimensions should have different tuner ids, because the lws of one may not be optimal on the other.
This will be concatenated with other components' tuner id to form the tuner id of the kernel
NOTE: Hardcoded for now, the parameters should ideally be exported by ckw (a selection of constant tiles)
Reimplemented from IGpuCkwComponentDriver.
Definition at line 162 of file GpuCkwElementwiseBinary.cpp.
 {
     ARM_COMPUTE_UNUSED(comp_group);
     /// NOTE: Hardcoded for now, the parameters should ideally be exported by ckw (a selection of constant tiles)
     std::vector<std::string> build_params = {
         "elementwise_binary",
         "op",
         to_string(_attributes.operation()),
         "dt",
         lower_string(string_from_data_type(_dst->data_type())),
         "dst_dim0",
         support::cpp11::to_string(_dst->dimension(0)),
         "dst_dim1",
         support::cpp11::to_string(_dst->dimension(1)),
     };
     return join(build_params, "_");
 }
References ARM_COMPUTE_UNUSED, ITensorInfo::data_type(), ITensorInfo::dimension(), arm_compute::join(), arm_compute::lower_string(), ElementwiseBinaryCommonAttributes::operation(), arm_compute::string_from_data_type(), arm_compute::to_string(), and arm_compute::support::cpp11::to_string().
get_window()
Window get_window () const override virtual
Generate the execution window for the component.
Reimplemented from IGpuCkwComponentDriver.
Definition at line 133 of file GpuCkwElementwiseBinary.cpp.
 {
     ARM_COMPUTE_ERROR_ON_MSG(_dst->tensor_shape().total_size() == 0U, "Destination tensor is not initialized");
     TensorShape output_shape = _dst->tensor_shape();
     // Collapse Dim 1 (W) and Dim 2 (H) together, leave Dim 0 (C) unchanged
     // This is in line with the collapsing convention used by operators like Conv2d
     output_shape.collapse(2U, 1U);
     constexpr unsigned int vector_size_byte_opencl = 16;
     const unsigned int     num_elems_processed_per_iteration =
         adjust_vec_size(vector_size_byte_opencl / _dst->element_size(), _dst->dimension(0));
     Window win = calculate_max_window(output_shape, Steps(num_elems_processed_per_iteration));
     return win;
 }
References arm_compute::adjust_vec_size(), ARM_COMPUTE_ERROR_ON_MSG, arm_compute::calculate_max_window(), TensorShape::collapse(), ITensorInfo::dimension(), ITensorInfo::element_size(), num_elems_processed_per_iteration, arm_compute::test::validation::output_shape, ITensorInfo::tensor_shape(), TensorShape::total_size(), arm_compute::utils::cast::U, and arm_compute::experimental::dynamic_fusion::vector_size_byte_opencl.
write_component_code()
void write_component_code (const ComponentGroup & comp_group, GpuCkwVariableTable & vtable, GpuCkwScopedKernelWriter writer) const override virtual
Generate kernel component code.
Parameters
[in] comp_group Component group of which the component is a part of
[in,out] vtable Table of variables declared by each component
[in,out] writer CKW writer that writes code scoped to this kernel component.
                       @note @p writer can only be passed via value since the new scope is created in the copy constructor
Implements IGpuCkwComponentDriver.
Definition at line 66 of file GpuCkwElementwiseBinary.cpp.
 {
     const auto root_window = comp_group.get_root_component()->ckw_component_driver()->get_window();
     const auto n0          = static_cast<int32_t>(root_window.x().step());
     const auto m0          = static_cast<int32_t>(root_window.y().step());
     GpuCkwComponentArgument *lhs =
         vtable.declare_variable(comp_group, writer, _lhs, TensorStorageType::ClBufferUint8Ptr, "lhs");
     GpuCkwComponentArgument *rhs =
         vtable.declare_variable(comp_group, writer, _rhs, TensorStorageType::ClBufferUint8Ptr, "rhs");
     GpuCkwComponentArgument *dst =
         vtable.declare_variable(comp_group, writer, _dst, TensorStorageType::ClBufferUint8Ptr, "dst");
     auto &gid_0 = writer->declare_tile("gid_0", ckw::DataType::Int32);
     auto &gid_1 = writer->declare_tile("gid_1", ckw::DataType::Int32);
     auto &gid_2 = writer->declare_tile("gid_2", ckw::DataType::Int32);
     writer->op_get_global_id(gid_0, 0);
     writer->op_get_global_id(gid_1, 1);
     writer->op_get_global_id(gid_2, 2);
     auto &const_0 = writer->declare_tile("0", 0);
     // Load the LHS and RHS tiles
     if (!lhs->has_tile())
     {
         auto sampler = create_boundary_aware_2d_sampler(writer, gid_0, gid_1, _lhs->dimension(0), _lhs->dimension(1),
                                                         n0, m0, "lhs_", const_0);
         sampler.format(TensorSamplerFormat::C_WH_1); // 3rd dimension collapsed with 2nd dimension
         sampler.z(const_0);
         sampler.b(gid_2);
         writer->op_load_once(lhs, sampler);
     }
     if (!rhs->has_tile())
     {
         auto sampler = create_boundary_aware_2d_sampler(writer, gid_0, gid_1, _rhs->dimension(0), _rhs->dimension(1),
                                                         n0, m0, "rhs_", const_0);
         sampler.format(TensorSamplerFormat::C_WH_1); // 3rd dimension collapsed with 2nd dimension
         sampler.z(const_0);
         sampler.b(gid_2);
         writer->op_load_once(rhs, sampler);
     }
     auto dst_sampler = create_boundary_aware_2d_sampler(writer, gid_0, gid_1, _dst->dimension(0), _dst->dimension(1),
                                                         n0, m0, "dst_", const_0);
     dst_sampler.format(TensorSamplerFormat::C_WH_1); // 3rd dimension collapsed with 2nd dimension
     dst_sampler.z(const_0);
     dst_sampler.b(gid_2);
     // Prepare the output tile.
     if (!dst->has_tile())
     {
         auto &tile = writer->declare_tile(
             "dst_tile", ckw::TileInfo(to_ckw(_dst->data_type()), dst_sampler.height(), dst_sampler.width()));
         dst->init_virtual_tensor(tile, dst_sampler);
     }
     auto &lhs_tile = lhs->tile();
     auto &rhs_tile = rhs->tile();
     auto &dst_tile = dst->tile();
     // Perform the operation.
     writer->op_binary_expression(dst_tile, lhs_tile, to_ckw(_attributes), rhs_tile);
 }
References IGpuKernelComponent::ckw_component_driver(), arm_compute::experimental::dynamic_fusion::create_boundary_aware_2d_sampler(), ITensorInfo::data_type(), GpuCkwVariableTable::declare_variable(), ITensorInfo::dimension(), arm_compute::test::validation::dst, GpuKernelComponentGroup::get_root_component(), IGpuCkwComponentDriver::get_window(), GpuCkwComponentArgument::has_tile(), GpuCkwKernelWriter::op_load_once(), arm_compute::test::validation::reference::tile(), GpuCkwComponentArgument::tile(), and arm_compute::experimental::dynamic_fusion::to_ckw().
The documentation for this class was generated from the following files:
src/dynamic_fusion/sketch/gpu/ckw_driver/components/GpuCkwElementwiseBinary.h
src/dynamic_fusion/sketch/gpu/ckw_driver/components/GpuCkwElementwiseBinary.cpp