Compute Library: ClTemplateElementwiseBinary Class Reference
ClTemplateElementwiseBinary Class Reference final
#include <ClTemplateElementwiseBinary.h>
Public Types
using Attributes = ClComponentElementwiseBinary::Attributes
Public Types inherited from IGpuTemplateComponentWriter
using ComponentGroup = GpuKernelComponentGroup
Public Member Functions
ClTemplateElementwiseBinary (ComponentId id, const ArgumentPack< ITensorInfo > &tensors, const Attributes &attributes)
Constructor.
ClTemplateElementwiseBinary (const ClTemplateElementwiseBinary &elementwise)=delete
Prevent instances of this class from being copy constructed.
ClTemplateElementwiseBinary & operator= (const ClTemplateElementwiseBinary &elementwise)=delete
Prevent instances of this class from being copied.
ClTemplateElementwiseBinary (ClTemplateElementwiseBinary &&elementwise)=default
Allow instances of this class to be move constructed.
ClTemplateElementwiseBinary & operator= (ClTemplateElementwiseBinary &&elementwise)=default
Allow instances of this class to be moved.
std::string get_name () const override
Generate kernel component name.
std::string get_component_code (const ComponentGroup &comp_group) const override
Generate kernel component code template.
void declare_variables (GpuKernelVariableTable &vtable, const ComponentGroup &comp_group) const override
Declare all variables used by the component in the vtable.
TagLUT get_tag_lut (const GpuKernelVariableTable &vtable, const ComponentGroup &comp_group) const override
Generate the tag look-up table used to instantiate the component code.
CLBuildOptions get_build_options (const ComponentGroup &comp_group) const override
Generate the build options used in the component.
std::string get_config_id () const override
Generate the component config id string used for tuning.
std::set< std::string > get_headers_list () const override
Generate the header list used in the component.
Window get_window () const override
Generate the execution window for the component.
Public Member Functions inherited from IGpuTemplateComponentWriter
IGpuTemplateComponentWriter (ComponentId id, const ArgumentPack< ITensorInfo > &tensors)
Constructor.
virtual ~IGpuTemplateComponentWriter ()
Destructor.
virtual std::string get_additional_macros () const
Generate additional macros used in the component.
ArgumentPack< ITensorInfo > tensors () const
Get tensor arguments.
ComponentId id () const
Get component id.
Additional Inherited Members
Static Public Attributes inherited from IGpuTemplateComponentWriter
static constexpr GpuKernelArgumentInfo::Type common_tensor_type = GpuKernelArgumentInfo::Type::Tensor_4D_t_Buffer
For now all kernel intermeditate/destination tensors are expected to be of type Tensor_4D_t_Buffer.
Detailed Description
Definition at line 39 of file ClTemplateElementwiseBinary.h.
Member Typedef Documentation
Attributes
using Attributes = ClComponentElementwiseBinary::Attributes
Definition at line 42 of file ClTemplateElementwiseBinary.h.
Constructor & Destructor Documentation
ClTemplateElementwiseBinary() [1/3]
ClTemplateElementwiseBinary (ComponentId id, const ArgumentPack< ITensorInfo > & tensors, const Attributes & attributes)
Constructor.
Similar to ClComponentElementwiseBinary::validate()
Parameters
[in] id Component id
[in] tensors Tensor arguments to the components
[in] attributes Component attributes
Definition at line 43 of file ClTemplateElementwiseBinary.cpp.
     : IGpuTemplateComponentWriter{id, tensors}, _lhs{}, _rhs{}, _dst{}, _attributes{attributes}
 {
     _lhs = this->tensors().get_const_tensor(TensorType::ACL_SRC_0);
     _rhs = this->tensors().get_const_tensor(TensorType::ACL_SRC_1);
     _dst = this->tensors().get_const_tensor(TensorType::ACL_DST_0);
     ARM_COMPUTE_ERROR_ON_NULLPTR(_lhs, _rhs, _dst);
 }
References IGpuTemplateComponentWriter::id(), and IGpuTemplateComponentWriter::tensors().
ClTemplateElementwiseBinary() [2/3]
ClTemplateElementwiseBinary (const ClTemplateElementwiseBinary & elementwise) delete
Prevent instances of this class from being copy constructed.
ClTemplateElementwiseBinary() [3/3]
ClTemplateElementwiseBinary (ClTemplateElementwiseBinary && elementwise) default
Allow instances of this class to be move constructed.
Member Function Documentation
declare_variables()
void declare_variables (GpuKernelVariableTable & vtable, const ComponentGroup & comp_group) const override virtual
Declare all variables used by the component in the vtable.
Parameters
[out] vtable Variable table
[in] comp_group Component group of which the component is a part of
Implements IGpuTemplateComponentWriter.
Definition at line 118 of file ClTemplateElementwiseBinary.cpp.
                   {{BROADCAST_OP}}{{ELTWISE_OP}}({{DATA_TYPE}}, M0, N0, {{lhs}}, {{rhs}}, {{dst}});
 )_";
     if (is_root)
     {
         // Calculate the destination indirect Y
         code +=
get_build_options()
CLBuildOptions get_build_options (const ComponentGroup & comp_group) const override virtual
Generate the build options used in the component.
Parameters
[in] comp_group Component group of which the component is a part of
Returns
CLBuildOptions Build options
NOTE: For now tile sizes (n0, m0) are set by the execution window. This may change in the future
Reimplemented from IGpuTemplateComponentWriter.
Definition at line 194 of file ClTemplateElementwiseBinary.cpp.
                                                      : "N0";
     lut["lhs_start_ind_0"] = (lhs_broadcast_x) ? "0" : "g_ind_0";
     lut["rhs_n0"]          = (rhs_broadcast_x) ? "1" : "N0";
     lut["rhs_start_ind_0"] = (rhs_broadcast_x) ? "0" : "g_ind_0";
get_component_code()
std::string get_component_code (const ComponentGroup & comp_group) const override virtual
Generate kernel component code template.
Parameters
[in] comp_group Component group of which the component is a part of
Returns
std::string Component code
Implements IGpuTemplateComponentWriter.
Definition at line 59 of file ClTemplateElementwiseBinary.cpp.
 {
     std::string code;
     const bool  is_root      = (comp_group.get_root_component()->id() == this->id());
     const bool  is_lhs_input = comp_group.is_input_tensor(_lhs);
     const bool  is_rhs_input = comp_group.is_input_tensor(_rhs);
     code =
         R"_(
     //------------------ START KERNEL {{meta_kernel_id}} {{ELTWISE_OP}} ---------------------
 )_";
     if (is_root)
     {
         code +=
             R"_(
     TILE(uint, M0, 1, g_dst_indirect_y);
 )_";
     }
     if (is_lhs_input)
     {
         code +=
             R"_(
     TILE({{DATA_TYPE}}, {{lhs_m0}}, N0, {{lhs}});
 )_";
     }
     if (is_rhs_input)
     {
         code +=
             R"_(
     TILE({{DATA_TYPE}}, {{rhs_m0}}, N0, {{rhs}});
 )_";
     }
     code +=
         R"_(
     {
 )_";
     if (is_lhs_input)
     {
         code +=
             R"_(
         {{lhs}}_offset_first_element_in_bytes += g_ind_2 * {{lhs}}_stride_w;
         T_LOAD({{DATA_TYPE}}, {{lhs_m0}}, {{lhs_n0}}, BUFFER, {{lhs}}, {{lhs_start_ind_0}}, {{lhs_start_ind_1}}, 1, {{lhs}}_stride_y, {{lhs}});
 )_";
     }
     if (is_rhs_input)
     {
         code +=
             R"_(
         {{rhs}}_offset_first_element_in_bytes += g_ind_2 * {{rhs}}_stride_w;
         T_LOAD({{DATA_TYPE}}, {{rhs_m0}}, {{rhs_n0}}, BUFFER, {{rhs}}, {{rhs_start_ind_0}}, {{rhs_start_ind_1}}, 1, {{rhs}}_stride_y, {{rhs}});
 )_";
     }
References GpuKernelComponentGroup::get_root_component(), IGpuKernelComponent::id(), IGpuTemplateComponentWriter::id(), and GpuKernelComponentGroup::is_input_tensor().
get_config_id()
std::string get_config_id () const override virtual
Generate the component config id string used for tuning.
Reimplemented from IGpuTemplateComponentWriter.
Definition at line 211 of file ClTemplateElementwiseBinary.cpp.
                                                       : "M0";
     lut["lhs_start_ind_1"] = (lhs_broadcast_yz) ? "0" : "g_ind_1";
     lut["rhs_m0"]          = (rhs_broadcast_yz) ? "1" : "M0";
     lut["rhs_start_ind_1"] = (rhs_broadcast_yz) ? "0" : "g_ind_1";
     lut["BROADCAST_OP"] = (lhs_broadcast_yz) ? "BROADCAST_LHS_X_" : (rhs_broadcast_yz) ? "BROADCAST_RHS_X_" : "";
     return lut;
 }
 CLBuildOptions ClTemplateElementwiseBinary::get_build_options(const ComponentGroup &comp_group) const
 {
     CLBuildOptions build_opts{};
get_headers_list()
std::set< std::string > get_headers_list () const override virtual
Generate the header list used in the component.
Reimplemented from IGpuTemplateComponentWriter.
Definition at line 225 of file ClTemplateElementwiseBinary.cpp.
get_name()
std::string get_name () const override virtual
Generate kernel component name.
Implements IGpuTemplateComponentWriter.
Definition at line 54 of file ClTemplateElementwiseBinary.cpp.
 {
     return "elementwise_binary";
 }
get_tag_lut()
TagLUT get_tag_lut (const GpuKernelVariableTable & vtable, const ComponentGroup & comp_group) const override virtual
Generate the tag look-up table used to instantiate the component code.
Parameters
[in] vtable Variable table
[in] comp_group Component group of which the component is a part of
Returns
TagLUT Tag lookup table
Implements IGpuTemplateComponentWriter.
Definition at line 128 of file ClTemplateElementwiseBinary.cpp.
         {
             g_dst_indirect_y[i].v = (uint)min(g_ind_1 + i, (int)({{arg_dst}}_w * {{arg_dst}}_h) - 1);
             g_dst_indirect_y[i].v += g_ind_2 * (int)({{arg_dst}}_w * {{arg_dst}}_h);
         })
 )_";
     }
     code +=
         R"_(
     }
     //------------------ END KERNEL {{meta_kernel_id}} {{ELTWISE_OP}} ---------------------
 )_";
     return code;
 }
 void ClTemplateElementwiseBinary::declare_variables(GpuKernelVariableTable &vtable,
                                                     const ComponentGroup   &comp_group) const
 {
     vtable.declare_variable(comp_group, _lhs, GpuKernelArgumentInfo(common_tensor_type), "lhs");
     vtable.declare_variable(comp_group, _rhs, GpuKernelArgumentInfo(common_tensor_type), "rhs");
     vtable.declare_variable(comp_group, _dst, GpuKernelArgumentInfo(common_tensor_type), "dst");
 }
 TagLUT ClTemplateElementwiseBinary::get_tag_lut(const GpuKernelVariableTable &vtable,
                                                 const ComponentGroup         &comp_group) const
 {
     TagLUT lut{};
     // Local build options
     lut["meta_kernel_id"] = id();
     lut["DATA_TYPE"]      = get_cl_type_from_data_type(_lhs->data_type());
     // Arguments and global shared variables
     lut["lhs"]     = vtable.get_variable(_lhs);
     lut["rhs"]     = vtable.get_variable(_rhs);
     lut["dst"]     = vtable.get_variable(_dst);
     lut["arg_dst"] = vtable.get_variable(comp_group.get_any_dst_tensor());
     switch (_attributes.operation())
     {
         case Attributes::ElementwiseOp::Add:
             lut["ELTWISE_OP"] = "ADD";
             break;
         case Attributes::ElementwiseOp::Sub:
             lut["ELTWISE_OP"] = "SUB";
             break;
         case Attributes::ElementwiseOp::Mul:
             lut["ELTWISE_OP"] = "MUL";
             break;
         default:
             ARM_COMPUTE_ERROR("Arithmetic Operation not supported");
     }
     ARM_COMPUTE_ERROR_ON(comp_group.is_intermediate_tensor(_lhs) &&
                          detail::have_different_dimensions(_lhs->tensor_shape(), _dst->tensor_shape(), 0));
     ARM_COMPUTE_ERROR_ON(comp_group.is_intermediate_tensor(_rhs) &&
                          detail::have_different_dimensions(_rhs->tensor_shape(), _dst->tensor_shape(), 0));
     // Set broadcast parameters
     // PRE: All tensors are broadcast-compatible
     const auto &lhs_dims = _lhs->tensor_shape();
get_window()
Window get_window () const override virtual
Generate the execution window for the component.
Reimplemented from IGpuTemplateComponentWriter.
Definition at line 230 of file ClTemplateElementwiseBinary.cpp.
 {
     std::string config_id{};
     config_id += lower_string(string_from_data_type(_dst->data_type()));
     config_id += "_";
     config_id += support::cpp11::to_string(_dst->dimension(0));
operator=() [1/2]
ClTemplateElementwiseBinary& operator= (ClTemplateElementwiseBinary && elementwise) default
Allow instances of this class to be moved.
operator=() [2/2]
ClTemplateElementwiseBinary& operator= (const ClTemplateElementwiseBinary & elementwise) delete
Prevent instances of this class from being copied.
The documentation for this class was generated from the following files:
src/dynamic_fusion/sketch/gpu/template_writer/cl/ClTemplateElementwiseBinary.h
src/dynamic_fusion/sketch/gpu/template_writer/cl/ClTemplateElementwiseBinary.cpp