Compute Library: ClTemplateLogits1DNorm Class Reference
ClTemplateLogits1DNorm Class Reference final
#include <ClTemplateLogits1DNorm.h>
Public Types
using Attributes = ClComponentLogits1DNorm::Attributes
Public Types inherited from IGpuTemplateComponentWriter
using ComponentGroup = GpuKernelComponentGroup
Public Member Functions
ClTemplateLogits1DNorm (ComponentId id, const ArgumentPack< ITensorInfo > &tensors, const Attributes &attributes)
Constructor.
ClTemplateLogits1DNorm (const ClTemplateLogits1DNorm &)=delete
Prevent instances of this class from being copy constructed.
ClTemplateLogits1DNorm & operator= (const ClTemplateLogits1DNorm &)=delete
Prevent instances of this class from being copied.
ClTemplateLogits1DNorm (ClTemplateLogits1DNorm &&)=default
Allow instances of this class to be move constructed.
ClTemplateLogits1DNorm & operator= (ClTemplateLogits1DNorm &&)=default
Allow instances of this class to be moved.
std::string get_name () const override
Generate kernel component name.
std::string get_component_code (const ComponentGroup &comp_group) const override
Generate kernel component code template.
void declare_variables (GpuKernelVariableTable &vtable, const ComponentGroup &comp_group) const override
Declare all variables used by the component in the vtable.
TagLUT get_tag_lut (const GpuKernelVariableTable &vtable, const ComponentGroup &comp_group) const override
Generate the tag look-up table used to instantiate the component code.
CLBuildOptions get_build_options (const ComponentGroup &comp_group) const override
Generate the build options used in the component.
std::string get_config_id () const override
Generate the component config id string used for tuning.
std::set< std::string > get_headers_list () const override
Generate the header list used in the component.
Window get_window () const override
Generate the execution window for the component.
Public Member Functions inherited from IGpuTemplateComponentWriter
IGpuTemplateComponentWriter (ComponentId id, const ArgumentPack< ITensorInfo > &tensors)
Constructor.
virtual ~IGpuTemplateComponentWriter ()
Destructor.
virtual std::string get_additional_macros () const
Generate additional macros used in the component.
ArgumentPack< ITensorInfo > tensors () const
Get tensor arguments.
ComponentId id () const
Get component id.
Additional Inherited Members
Static Public Attributes inherited from IGpuTemplateComponentWriter
static constexpr GpuKernelArgumentInfo::Type common_tensor_type = GpuKernelArgumentInfo::Type::Tensor_4D_t_Buffer
For now all kernel intermeditate/destination tensors are expected to be of type Tensor_4D_t_Buffer.
Detailed Description
Definition at line 38 of file ClTemplateLogits1DNorm.h.
Member Typedef Documentation
Attributes
using Attributes = ClComponentLogits1DNorm::Attributes
Definition at line 41 of file ClTemplateLogits1DNorm.h.
Constructor & Destructor Documentation
ClTemplateLogits1DNorm() [1/3]
ClTemplateLogits1DNorm (ComponentId id, const ArgumentPack< ITensorInfo > & tensors, const Attributes & attributes)
Constructor.
Parameters
[in] id Component id
[in] tensors Tensor arguments to the components
[in] attributes Component attributes
Definition at line 39 of file ClTemplateLogits1DNorm.cpp.
     : IGpuTemplateComponentWriter{id, tensors}, _src{}, _sum{}, _dst{}, _attributes{attributes}
 {
     _src = this->tensors().get_const_tensor(TensorType::ACL_SRC_0);
     _sum = this->tensors().get_const_tensor(TensorType::ACL_SRC_1);
     _dst = this->tensors().get_const_tensor(TensorType::ACL_DST_0);
     ARM_COMPUTE_ERROR_ON_NULLPTR(_src);
     ARM_COMPUTE_ERROR_ON_NULLPTR(_sum);
     ARM_COMPUTE_ERROR_ON_NULLPTR(_dst);
 }
References IGpuTemplateComponentWriter::id(), and IGpuTemplateComponentWriter::tensors().
ClTemplateLogits1DNorm() [2/3]
ClTemplateLogits1DNorm (const ClTemplateLogits1DNorm &) delete
Prevent instances of this class from being copy constructed.
ClTemplateLogits1DNorm() [3/3]
ClTemplateLogits1DNorm (ClTemplateLogits1DNorm &&) default
Allow instances of this class to be move constructed.
Member Function Documentation
declare_variables()
void declare_variables (GpuKernelVariableTable & vtable, const ComponentGroup & comp_group) const override virtual
Declare all variables used by the component in the vtable.
Parameters
[out] vtable Variable table
[in] comp_group Component group of which the component is a part of
Implements IGpuTemplateComponentWriter.
Definition at line 99 of file ClTemplateLogits1DNorm.cpp.
 {
     vtable.declare_variable(comp_group, _src, GpuKernelArgumentInfo(GpuKernelArgumentInfo::Type::Tensor_3D), "src");
     vtable.declare_variable(comp_group, _sum, GpuKernelArgumentInfo(GpuKernelArgumentInfo::Type::Tensor_3D), "sum");
     vtable.declare_variable(comp_group, _dst, GpuKernelArgumentInfo(GpuKernelArgumentInfo::Type::Tensor_3D), "dst");
 }
References GpuKernelVariableTable::declare_variable(), and GpuKernelArgumentInfo::Tensor_3D.
get_build_options()
CLBuildOptions get_build_options (const ComponentGroup & comp_group) const override virtual
Generate the build options used in the component.
Parameters
[in] comp_group Component group of which the component is a part of
Returns
CLBuildOptions Build options
Reimplemented from IGpuTemplateComponentWriter.
Definition at line 129 of file ClTemplateLogits1DNorm.cpp.
 {
     ARM_COMPUTE_UNUSED(comp_group);
     CLBuildOptions build_opts{};
     const auto         root_window = comp_group.get_root_component()->template_writer()->get_window();
     const unsigned int n0          = root_window.x().step();
     build_opts.add_option("-DN0=" + support::cpp11::to_string(n0));
     build_opts.add_option("-DPARTIAL_N0=" + support::cpp11::to_string((_src->dimension(0) % n0)));
     return build_opts;
 }
References ARM_COMPUTE_UNUSED, ITensorInfo::dimension(), GpuKernelComponentGroup::get_root_component(), IGpuTemplateComponentWriter::get_window(), Window::Dimension::step(), IGpuKernelComponent::template_writer(), arm_compute::support::cpp11::to_string(), and Window::x().
get_component_code()
std::string get_component_code (const ComponentGroup & comp_group) const override virtual
Generate kernel component code template.
Parameters
[in] comp_group Component group of which the component is a part of
Returns
std::string Component code
Implements IGpuTemplateComponentWriter.
Definition at line 57 of file ClTemplateLogits1DNorm.cpp.
 {
     ARM_COMPUTE_UNUSED(comp_group);
     std::string code = R"_(
 //------------------ START KERNEL {{meta_kernel_id}} ---------------------
 {
     const int x_offs = g_ind_0 * sizeof({{DATA_TYPE}});
     __global uchar *src_addr = {{src}}_ptr + {{src}}_offset_first_element_in_bytes + x_offs + g_ind_1 * {{src}}_stride_y + g_ind_2 * {{src}}_stride_z;
     __global uchar *dst_addr = {{dst}}_ptr + {{dst}}_offset_first_element_in_bytes + x_offs + g_ind_1 * {{dst}}_stride_y + g_ind_2 * {{dst}}_stride_z;
     Image sum = CONVERT_TENSOR3D_TO_IMAGE_STRUCT_NO_STEP({{sum}});
 )_";
     // Load max value of 1D logits vector (row)
     code += R"_(
     {{DATA_TYPE}} sum_val = *((__global {{DATA_TYPE}} *)offset(&sum, 0, g_ind_1));
     VEC_DATA_TYPE({{DATA_TYPE}}, N0)
     data0 = VLOAD(N0)(0, (__global {{DATA_TYPE}} *)src_addr);
 )_";
     if (_attributes.is_log_softmax())
     {
         code += R"_(
     sum_val = log(sum_val);
     data0 -= sum_val;
 )_";
     }
     else
     {
         code += R"_(
     data0 /= sum_val;
 )_";
     }
     code += R"_(
     STORE_VECTOR_SELECT(data, {{DATA_TYPE}}, dst_addr, N0, PARTIAL_N0, PARTIAL_N0 != 0 && g_ind_0 == 0);
 }
 //------------------ END KERNEL {{meta_kernel_id}} ---------------------
 )_";
     return code;
 }
References ARM_COMPUTE_UNUSED, and SoftmaxAttributes::is_log_softmax().
get_config_id()
std::string get_config_id () const override virtual
Generate the component config id string used for tuning.
Reimplemented from IGpuTemplateComponentWriter.
Definition at line 142 of file ClTemplateLogits1DNorm.cpp.
 {
     std::string config_id = get_name();
     config_id += "_";
     config_id += support::cpp11::to_string(_src->dimension(0));
     config_id += "_";
     config_id += string_from_data_type(_src->data_type());
     return config_id;
 }
References ITensorInfo::data_type(), ITensorInfo::dimension(), ClTemplateLogits1DNorm::get_name(), arm_compute::string_from_data_type(), and arm_compute::support::cpp11::to_string().
get_headers_list()
std::set< std::string > get_headers_list () const override virtual
Generate the header list used in the component.
Reimplemented from IGpuTemplateComponentWriter.
Definition at line 154 of file ClTemplateLogits1DNorm.cpp.
 {
     return std::set<std::string>{"helpers.h", "tile_helpers.h"};
 }
get_name()
std::string get_name () const override virtual
Generate kernel component name.
Implements IGpuTemplateComponentWriter.
Definition at line 52 of file ClTemplateLogits1DNorm.cpp.
 {
     return "logits_1d_norm";
 }
Referenced by ClTemplateLogits1DNorm::get_config_id().
get_tag_lut()
TagLUT get_tag_lut (const GpuKernelVariableTable & vtable, const ComponentGroup & comp_group) const override virtual
Generate the tag look-up table used to instantiate the component code.
Parameters
[in] vtable Variable table
[in] comp_group Component group of which the component is a part of
Returns
TagLUT Tag lookup table
Implements IGpuTemplateComponentWriter.
Definition at line 108 of file ClTemplateLogits1DNorm.cpp.
 {
     ARM_COMPUTE_UNUSED(comp_group);
     TagLUT lut{};
     // Arguments and global shared variables
     lut["src"] = vtable.get_variable(_src);
     lut["sum"] = vtable.get_variable(_sum);
     lut["dst"] = vtable.get_variable(_dst);
     // Local build options
     lut["meta_kernel_id"] = id();
     const DataType data_type = _src->data_type();
     lut["DATA_TYPE"] = get_cl_type_from_data_type(data_type);
     return lut;
 }
References ARM_COMPUTE_UNUSED, arm_compute::test::validation::data_type, ITensorInfo::data_type(), arm_compute::get_cl_type_from_data_type(), GpuKernelVariableTable::get_variable(), and IGpuTemplateComponentWriter::id().
get_window()
Window get_window () const override virtual
Generate the execution window for the component.
Reimplemented from IGpuTemplateComponentWriter.
Definition at line 159 of file ClTemplateLogits1DNorm.cpp.
 {
     ARM_COMPUTE_ERROR_ON_MSG(_dst->tensor_shape().total_size() == 0U, "Destination tensor is not initialized");
     constexpr unsigned int serial_vector_size = 16;
     const unsigned int     vector_size        = adjust_vec_size(serial_vector_size, _src->dimension(0));
     Window win = calculate_max_window(*_src, Steps(vector_size));
     return win.collapse(win, Window::DimZ);
 }
References arm_compute::adjust_vec_size(), ARM_COMPUTE_ERROR_ON_MSG, arm_compute::calculate_max_window(), Window::collapse(), ITensorInfo::dimension(), Window::DimZ, ITensorInfo::tensor_shape(), TensorShape::total_size(), arm_compute::utils::cast::U, and arm_compute::cpu::vector_size.
operator=() [1/2]
ClTemplateLogits1DNorm& operator= (ClTemplateLogits1DNorm &&) default
Allow instances of this class to be moved.
operator=() [2/2]
ClTemplateLogits1DNorm& operator= (const ClTemplateLogits1DNorm &) delete
Prevent instances of this class from being copied.
The documentation for this class was generated from the following files:
src/dynamic_fusion/sketch/gpu/template_writer/cl/ClTemplateLogits1DNorm.h
src/dynamic_fusion/sketch/gpu/template_writer/cl/ClTemplateLogits1DNorm.cpp