Compute Library: NEDepthToSpaceLayerKernel Class Reference
NEDepthToSpaceLayerKernel Class Reference
Interface for the depth to space kernel.
#include <NEDepthToSpaceLayerKernel.h>
Public Member Functions
const char * name () const override
Name of the kernel.
NEDepthToSpaceLayerKernel ()
Default constructor.
NEDepthToSpaceLayerKernel (const NEDepthToSpaceLayerKernel &)=delete
Prevent instances of this class from being copied (As this class contains pointers)
NEDepthToSpaceLayerKernel & operator= (const NEDepthToSpaceLayerKernel &)=delete
Prevent instances of this class from being copied (As this class contains pointers)
NEDepthToSpaceLayerKernel (NEDepthToSpaceLayerKernel &&)=default
Allow instances of this class to be moved.
NEDepthToSpaceLayerKernel & operator= (NEDepthToSpaceLayerKernel &&)=default
Allow instances of this class to be moved.
~NEDepthToSpaceLayerKernel ()=default
Default destructor.
void configure (const ITensor *input, ITensor *output, int32_t block_shape)
Initialise the kernel's inputs and output.
size_t get_split_dimension () const
Get the dimension the scheduler should use to split.
void run (const Window &window, const ThreadInfo &info) override
Execute the kernel on the passed window.
Public Member Functions inherited from ICPPKernel
virtual ~ICPPKernel ()=default
Default destructor.
virtual void run_nd (const Window &window, const ThreadInfo &info, const Window &thread_locator)
legacy compatibility layer for implemantions which do not support thread_locator In these cases we simply narrow the interface down the legacy version
virtual void run_op (ITensorPack &tensors, const Window &window, const ThreadInfo &info)
Execute the kernel on the passed window.
virtual size_t get_mws (const CPUInfo &platform, size_t thread_count) const
Return minimum workload size of the relevant kernel.
Public Member Functions inherited from IKernel
IKernel ()
Constructor.
virtual ~IKernel ()=default
Destructor.
virtual bool is_parallelisable () const
Indicates whether or not the kernel is parallelisable.
virtual BorderSize border_size () const
The size of the border for that kernel.
const Window & window () const
The maximum window the kernel can be executed on.
bool is_window_configured () const
Function to check if the embedded window of this kernel has been configured.
Static Public Member Functions
static Status validate (const ITensorInfo *input, const ITensorInfo *output, int32_t block_shape)
Static function to check if given info will lead to a valid configuration of NEDepthToSpaceLayerKernel.
Additional Inherited Members
Static Public Attributes inherited from ICPPKernel
static constexpr size_t default_mws = 1
Detailed Description
Interface for the depth to space kernel.
Definition at line 35 of file NEDepthToSpaceLayerKernel.h.
Constructor & Destructor Documentation
NEDepthToSpaceLayerKernel() [1/3]
NEDepthToSpaceLayerKernel ()
Default constructor.
Definition at line 70 of file NEDepthToSpaceLayerKernel.cpp.
     : _input(nullptr),
       _output(nullptr),
       _block_shape(),
       _data_layout(DataLayout::UNKNOWN),
       _split_dimension(Window::DimY)
 {
 }
NEDepthToSpaceLayerKernel() [2/3]
NEDepthToSpaceLayerKernel (const NEDepthToSpaceLayerKernel &) delete
Prevent instances of this class from being copied (As this class contains pointers)
NEDepthToSpaceLayerKernel() [3/3]
NEDepthToSpaceLayerKernel (NEDepthToSpaceLayerKernel &&) default
Allow instances of this class to be moved.
~NEDepthToSpaceLayerKernel()
~NEDepthToSpaceLayerKernel () default
Default destructor.
Member Function Documentation
configure()
void configure (const ITensor * input, ITensor * output, int32_t block_shape)
Initialise the kernel's inputs and output.
Parameters
[in] input Tensor input. Supported tensor rank: 4. Data types supported: All
[out] output Tensor output. Data types supported: same as input
[in] block_shape Block shape x value.
Definition at line 79 of file NEDepthToSpaceLayerKernel.cpp.
 {
     ARM_COMPUTE_ERROR_ON_NULLPTR(input, output);
     TensorShape output_shape = misc::shape_calculator::compute_depth_to_space_shape(
         input->info()->tensor_shape(), input->info()->data_layout(), block_shape);
     // Output auto inizialitation if not yet initialized
     auto_init_if_empty(*output->info(), input->info()->clone()->set_tensor_shape(output_shape));
     // Perform validation step
     ARM_COMPUTE_ERROR_THROW_ON(validate_arguments(input->info(), output->info(), block_shape));
     _input       = input;
     _output      = output;
     _block_shape = block_shape;
     _data_layout = input->info()->data_layout();
     constexpr size_t dim_b = 3;
     const auto       dim_h = get_data_layout_dimension_index(_data_layout, DataLayoutDimension::HEIGHT);
     const auto       dim_w = get_data_layout_dimension_index(_data_layout, DataLayoutDimension::WIDTH);
     const auto       dim_c = get_data_layout_dimension_index(_data_layout, DataLayoutDimension::CHANNEL);
     ARM_COMPUTE_ERROR_ON(get_data_layout_dimension_index(_data_layout, DataLayoutDimension::BATCHES) != dim_b);
     // Configure kernel window
     Steps steps;
     steps.set(dim_h, block_shape);
     steps.set(dim_w, block_shape);
     steps.set(dim_c, output->info()->dimension(dim_c));
     Window win = calculate_max_window(*output->info(), steps);
     ICPPKernel::configure(win);
     const auto num_batches = input->info()->tensor_shape().total_size_upper(dim_b);
     if (num_batches > 1)
     {
         _split_dimension = dim_b;
     }
     else
     {
         _split_dimension = dim_h;
     }
 }
References ARM_COMPUTE_ERROR_ON, ARM_COMPUTE_ERROR_ON_NULLPTR, ARM_COMPUTE_ERROR_THROW_ON, arm_compute::auto_init_if_empty(), arm_compute::BATCHES, arm_compute::calculate_max_window(), arm_compute::CHANNEL, arm_compute::misc::shape_calculator::compute_depth_to_space_shape(), ITensorInfo::dimension(), arm_compute::get_data_layout_dimension_index(), arm_compute::HEIGHT, ITensor::info(), arm_compute::test::validation::input, arm_compute::test::validation::output_shape, Dimensions< T >::set(), arm_compute::cpu::kernels::validate_arguments(), and arm_compute::WIDTH.
get_split_dimension()
size_t get_split_dimension () const
Get the dimension the scheduler should use to split.
Definition at line 129 of file NEDepthToSpaceLayerKernel.cpp.
 {
     return _split_dimension;
 }
name()
const char* name () const inline override virtual
Name of the kernel.
Returns
Kernel name
Implements ICPPKernel.
Definition at line 38 of file NEDepthToSpaceLayerKernel.h.
     {
         return "NEDepthToSpaceLayerKernel";
     }
operator=() [1/2]
NEDepthToSpaceLayerKernel& operator= (const NEDepthToSpaceLayerKernel &) delete
Prevent instances of this class from being copied (As this class contains pointers)
operator=() [2/2]
NEDepthToSpaceLayerKernel& operator= (NEDepthToSpaceLayerKernel &&) default
Allow instances of this class to be moved.
run()
void run (const Window & window, const ThreadInfo & info) override virtual
Execute the kernel on the passed window.
Warning
If is_parallelisable() returns false then the passed window must be equal to window()
Note
The window has to be a region within the window returned by the window() method
The width of the window has to be a multiple of num_elems_processed_per_iteration().
Parameters
[in] window Region on which to execute the kernel. (Must be a region of the window returned by window())
[in] info Info about executing thread and CPU.
Reimplemented from ICPPKernel.
Definition at line 134 of file NEDepthToSpaceLayerKernel.cpp.
 {
     ARM_COMPUTE_UNUSED(info);
     ARM_COMPUTE_ERROR_ON_UNCONFIGURED_KERNEL(this);
     ARM_COMPUTE_ERROR_ON_INVALID_SUBWINDOW(ICPPKernel::window(), window);
     const auto *input_info  = _input->info();
     const auto *output_info = _output->info();
     const auto  element_size   = input_info->element_size();
     const auto &input_strides  = input_info->strides_in_bytes();
     const auto &output_strides = output_info->strides_in_bytes();
     const auto &input_shape = input_info->tensor_shape();
     const uintptr_t k_input_strides[]  = {input_strides[0], input_strides[1], input_strides[2], input_strides[3]};
     const uintptr_t k_output_strides[] = {output_strides[0], output_strides[1], output_strides[2], output_strides[3]};
     const uint8_t *k_input_ptr  = _input->buffer();
     uint8_t       *k_output_ptr =               //
         _output->buffer() +                     //
         window[3].start() * output_strides[3] + //
         window[2].start() * output_strides[2] + //
         window[1].start() * output_strides[1] + //
         window[0].start() * output_strides[0];
     if (_data_layout == DataLayout::NCHW)
     {
         ARM_COMPUTE_ERROR_ON_MSG(window[2].start() != 0 || window[2].end() != window[2].step(),
                                  "The window cannot be splitted in channel dimension");
         const uintptr_t k_input_shape[] = {
             window.num_iterations(0), //
             window.num_iterations(1), //
             input_shape[2],           // The window cannot be splitted in channel dimension.
             window.num_iterations(3)  //
         };
         k_input_ptr += window[3].start() * input_strides[3] +                               //
                        window[2].start() * _block_shape * _block_shape * input_strides[2] + //
                        (window[1].start() / _block_shape) * input_strides[1] +              //
                        (window[0].start() / _block_shape) * input_strides[0];
         cpu::depth_to_space_nchw_any(                         //
             k_input_ptr, k_output_ptr,                        //
             k_input_shape, k_input_strides, k_output_strides, //
             element_size, _block_shape);
     }
     else
     {
         ARM_COMPUTE_ERROR_ON_MSG(window[0].start() != 0 || window[0].end() != window[0].step(),
                                  "The window cannot be splitted in channel dimension");
         const uintptr_t k_input_shape[] = {
             input_shape[0],           // The window cannot be splitted in channel dimension.
             window.num_iterations(1), //
             window.num_iterations(2), //
             window.num_iterations(3)  //
         };
         k_input_ptr += window[3].start() * input_strides[3] +                  //
                        (window[2].start() / _block_shape) * input_strides[2] + //
                        (window[1].start() / _block_shape) * input_strides[1] + //
                        window[0].start() * _block_shape * _block_shape * input_strides[0];
         cpu::depth_to_space_nhwc_any(                         //
             k_input_ptr, k_output_ptr,                        //
             k_input_shape, k_input_strides, k_output_strides, //
             element_size, _block_shape);
     }
 }
References ARM_COMPUTE_ERROR_ON_INVALID_SUBWINDOW, ARM_COMPUTE_ERROR_ON_MSG, ARM_COMPUTE_ERROR_ON_UNCONFIGURED_KERNEL, ARM_COMPUTE_UNUSED, ITensor::buffer(), arm_compute::cpu::depth_to_space_nchw_any(), arm_compute::cpu::depth_to_space_nhwc_any(), arm_compute::mlgo::parser::end(), ITensor::info(), arm_compute::test::validation::info, arm_compute::test::validation::input_info, arm_compute::test::validation::input_shape, arm_compute::NCHW, Window::num_iterations(), arm_compute::test::validation::output_info, arm_compute::cpu::step, and IKernel::window().
validate()
Status validate (const ITensorInfo * input, const ITensorInfo * output, int32_t block_shape) static
Static function to check if given info will lead to a valid configuration of NEDepthToSpaceLayerKernel.
Parameters
[in] input Tensor input info. Supported tensor rank: 4. Data types supported: All
[in] output Tensor output info. Data types supported: same as input
[in] block_shape Block shape value.
Returns
a status
Definition at line 122 of file NEDepthToSpaceLayerKernel.cpp.
 {
     ARM_COMPUTE_RETURN_ERROR_ON_NULLPTR(input, output);
     ARM_COMPUTE_RETURN_ON_ERROR(validate_arguments(input, output, block_shape));
     return Status{};
 }
References ARM_COMPUTE_RETURN_ERROR_ON_NULLPTR, ARM_COMPUTE_RETURN_ON_ERROR, arm_compute::test::validation::input, and arm_compute::cpu::kernels::validate_arguments().
Referenced by NEDepthToSpaceLayer::validate().
The documentation for this class was generated from the following files:
src/core/NEON/kernels/NEDepthToSpaceLayerKernel.h
src/core/NEON/kernels/NEDepthToSpaceLayerKernel.cpp