Compute Library: PriorBoxLayerInfo Class Reference
PriorBoxLayerInfo Class Reference final
PriorBox layer info.
#include <Types.h>
Public Member Functions
PriorBoxLayerInfo ()
Default Constructor.
PriorBoxLayerInfo (const std::vector< float > &min_sizes, const std::vector< float > &variances, float offset, bool flip=true, bool clip=false, const std::vector< float > &max_sizes={}, const std::vector< float > &aspect_ratios={}, const Coordinates2D &img_size=Coordinates2D{0, 0}, const std::array< float, 2 > &steps={{0.f, 0.f}})
Constructor.
std::vector< float > min_sizes () const
Get min sizes.
std::vector< float > variances () const
Get min variances.
std::array< float, 2 > steps () const
Get the step coordinates.
Coordinates2D img_size () const
Get the image size coordinates.
float offset () const
Get the offset.
bool flip () const
Get the flip value.
bool clip () const
Get the clip value.
std::vector< float > max_sizes () const
Get max sizes.
std::vector< float > aspect_ratios () const
Get aspect ratios.
Detailed Description
PriorBox layer info.
Definition at line 647 of file Types.h.
Constructor & Destructor Documentation
PriorBoxLayerInfo() [1/2]
PriorBoxLayerInfo () inline
Default Constructor.
Definition at line 651 of file Types.h.
         : _min_sizes(),
           _variances(),
           _offset(),
           _flip(true),
           _clip(false),
           _max_sizes(),
           _aspect_ratios(),
           _img_size(),
           _steps()
     {
     }
PriorBoxLayerInfo() [2/2]
PriorBoxLayerInfo (const std::vector< float > & min_sizes, const std::vector< float > & variances, float offset, bool flip = true, bool clip = false, const std::vector< float > & max_sizes = {}, const std::vector< float > & aspect_ratios = {}, const Coordinates2D & img_size = Coordinates2D{0, 0}, const std::array< float, 2 > & steps = {{0.f, 0.f}}) inline
Constructor.
Parameters
[in] min_sizes Min sizes vector.
[in] variances Variances vector.
[in] offset Offset value.
[in] flip (Optional) Flip the aspect ratios.
[in] clip (Optional) Clip coordinates so that they're within [0,1].
[in] max_sizes (Optional) Max sizes vector.
[in] aspect_ratios (Optional) Aspect ratios of the boxes.
[in] img_size (Optional) Image size.
[in] steps (Optional) Step values.
Definition at line 675 of file Types.h.
                                                                 {},
                       const std::vector<float>   &aspect_ratios = {},
                       const Coordinates2D        &img_size      = Coordinates2D{0, 0},
                       const std::array<float, 2> &steps         = {{0.f, 0.f}})
         : _min_sizes(min_sizes),
           _variances(variances),
           _offset(offset),
           _flip(flip),
           _clip(clip),
           _max_sizes(max_sizes),
           _aspect_ratios(),
           _img_size(img_size),
           _steps(steps)
     {
         _aspect_ratios.push_back(1.);
         for (unsigned int i = 0; i < aspect_ratios.size(); ++i)
         {
             float ar            = aspect_ratios[i];
             bool  already_exist = false;
             for (auto ar_new : _aspect_ratios)
             {
                 if (fabs(ar - ar_new) < 1e-6)
                 {
                     already_exist = true;
                     break;
                 }
             }
             if (!already_exist)
             {
                 _aspect_ratios.push_back(ar);
                 if (flip)
                 {
                     _aspect_ratios.push_back(1.f / ar);
                 }
             }
         }
     }
Member Function Documentation
aspect_ratios()
std::vector<float> aspect_ratios () const inline
Get aspect ratios.
Definition at line 758 of file Types.h.
     {
         return _aspect_ratios;
     }
Referenced by CLPriorBoxLayerKernel::run().
clip()
bool clip () const inline
Get the clip value.
Definition at line 748 of file Types.h.
     {
         return _clip;
     }
flip()
bool flip () const inline
Get the flip value.
Definition at line 743 of file Types.h.
     {
         return _flip;
     }
img_size()
Coordinates2D img_size () const inline
Get the image size coordinates.
Definition at line 733 of file Types.h.
     {
         return _img_size;
     }
max_sizes()
std::vector<float> max_sizes () const inline
Get max sizes.
Definition at line 753 of file Types.h.
     {
         return _max_sizes;
     }
Referenced by CLPriorBoxLayerKernel::run().
min_sizes()
std::vector<float> min_sizes () const inline
Get min sizes.
Definition at line 718 of file Types.h.
     {
         return _min_sizes;
     }
Referenced by CLPriorBoxLayerKernel::run().
offset()
float offset () const inline
Get the offset.
Definition at line 738 of file Types.h.
     {
         return _offset;
     }
steps()
std::array<float, 2> steps () const inline
Get the step coordinates.
Definition at line 728 of file Types.h.
     {
         return _steps;
     }
variances()
std::vector<float> variances () const inline
Get min variances.
Definition at line 723 of file Types.h.
     {
         return _variances;
     }
The documentation for this class was generated from the following file:
arm_compute/core/Types.h