Compute Library: CLCropResize Class Reference
CLCropResize Class Reference
Function to perform cropping and resizing.
#include <CLCropResize.h>
Public Member Functions
CLCropResize ()
Default constructor.
CLCropResize (const CLCropResize &)=delete
Prevent instances of this class from being copied (As this class contains pointers)
CLCropResize & operator= (const CLCropResize &)=delete
Prevent instances of this class from being copied (As this class contains pointers)
CLCropResize (CLCropResize &&)=default
Allow instances of this class to be moved.
CLCropResize & operator= (CLCropResize &&)=default
Allow instances of this class to be moved.
~CLCropResize ()
Default destructor.
void configure (const ICLTensor *input, ICLTensor *boxes, ICLTensor *box_ind, ICLTensor *output, Coordinates2D crop_size, InterpolationPolicy method=InterpolationPolicy::BILINEAR, float extrapolation_value=0)
Configure kernel.
void configure (const CLCompileContext &compile_context, const ICLTensor *input, ICLTensor *boxes, ICLTensor *box_ind, ICLTensor *output, Coordinates2D crop_size, InterpolationPolicy method=InterpolationPolicy::BILINEAR, float extrapolation_value=0)
Configure kernel.
void run () override
Run the kernels contained in the function.
Public Member Functions inherited from IFunction
virtual ~IFunction ()=default
Destructor.
virtual void prepare ()
Prepare the function for executing.
Static Public Member Functions
static Status validate (const ITensorInfo *input, ITensorInfo *boxes, ITensorInfo *box_ind, const ITensorInfo *output, Coordinates2D crop_size, InterpolationPolicy method, float extrapolation_value)
Static function to check if given info will lead to a valid configuration of NESlice.
Data Fields
const ICLTensor * _input
ICLTensor * _boxes
ICLTensor * _box_ind
ICLTensor * _output
size_t _num_boxes
InterpolationPolicy _method
float _extrapolation_value
std::vector< std::unique_ptr< CLScale > > _scale
std::vector< std::unique_ptr< CLCopy > > _copy
std::vector< std::unique_ptr< CLTensor > > _crop_results
std::vector< std::unique_ptr< CLTensor > > _scaled_results
std::vector< std::unique_ptr< IFunction > > _internal_functions
Detailed Description
Function to perform cropping and resizing.
Definition at line 45 of file CLCropResize.h.
Constructor & Destructor Documentation
CLCropResize() [1/3]
CLCropResize ()
Default constructor.
Definition at line 68 of file CLCropResize.cpp.
     : _input(nullptr),
       _boxes(nullptr),
       _box_ind(nullptr),
       _output(nullptr),
       _num_boxes(0),
       _method(),
       _extrapolation_value(0),
       _scale(),
       _copy(),
       _crop_results(),
       _scaled_results(),
       _internal_functions()
 {
 }
CLCropResize() [2/3]
CLCropResize (const CLCropResize &) delete
Prevent instances of this class from being copied (As this class contains pointers)
CLCropResize() [3/3]
CLCropResize (CLCropResize &&) default
Allow instances of this class to be moved.
~CLCropResize()
~CLCropResize () default
Default destructor.
Member Function Documentation
configure() [1/2]
void configure (const CLCompileContext & compile_context, const ICLTensor * input, ICLTensor * boxes, ICLTensor * box_ind, ICLTensor * output, Coordinates2D crop_size, InterpolationPolicy method = InterpolationPolicy::BILINEAR, float extrapolation_value = 0)
Configure kernel.
Note
Supported tensor rank: up to 4
Box indices may be outside of the bounds, in which case extrapolation_value is used.
Start and end indices of boxes are inclusive.
Parameters
[in] compile_context The compile context to be used.
[in] input Source tensor containing N batches of 3D images to be cropped. Data type supported: All
[in] boxes Tensor containing the boxes used to crop the images. It has to be known before configuration. Data type supported: F32
[in] box_ind One dimensional tensor containing the batch index of the 3D image in input that the corresponding box in boxes will be applied to. It has to be known before configuration. Data type supported: F32
[out] output Destination tensor containing a cropped and resized image for each box in boxes. Data type supported: F32
[in] crop_size The dimensions that each cropped image will be resized to.
[in] method The policy to be used when resizing image. Default is bilinear.
[in] extrapolation_value Value to be used for values outside of the image for cropping and resizing. Default is 0.
The number of rows out of bounds at the start and end of _crop_results[num_box].get().
The number of columns out of bounds at the start and end of _crop_results[num_box].get().
Definition at line 123 of file CLCropResize.cpp.
 {
     ARM_COMPUTE_ERROR_ON_NULLPTR(input, output, boxes, box_ind);
     ARM_COMPUTE_ERROR_THROW_ON(CLCropResize::validate(input->info(), boxes->info(), box_ind->info(), output->info(),
                                                       crop_size, method, extrapolation_value));
     ARM_COMPUTE_LOG_PARAMS(input, boxes, box_ind, output, crop_size, method, extrapolation_value);
     TensorShape output_shape =
         TensorShape(input->info()->tensor_shape()[0], crop_size.x, crop_size.y, boxes->info()->tensor_shape()[1]);
     auto_init_if_empty(*output->info(), output_shape, 1, DataType::F32);
     _num_boxes = boxes->info()->tensor_shape()[1];
     TensorShape out_shape(input->info()->tensor_shape()[0], crop_size.x, crop_size.y);
     _input               = input;
     _boxes               = boxes;
     _box_ind             = box_ind;
     _output              = output;
     _method              = method;
     _extrapolation_value = extrapolation_value;
     // For each crop box:
     // - The initial cropped image is produced as specified by boxes[i] from the 3D image input[box_ind[i]].
     //   Possibly using a CLCrop and up to four CLFills.
     // - A tensor is required to hold this initial cropped image.
     // - A scale function is used to resize the cropped image to the size specified by crop_size.
     // - A tensor is required to hold the final scaled image before it is copied into the 4D output
     //   that will hold all final cropped and scaled 3D images using CLCopy.
     // The contents of _boxes and _box_ind are required to calculate the shape
     // of the initial cropped image and thus are required to configure the
     // kernels used for cropping and scaling.
     _boxes->map(CLScheduler::get().queue());
     _box_ind->map(CLScheduler::get().queue());
     for (unsigned int num_box = 0; num_box < _num_boxes; ++num_box)
     {
         auto       crop_tensor = std::make_unique<CLTensor>();
         TensorInfo crop_result_info(1, DataType::F32);
         crop_result_info.set_data_layout(DataLayout::NHWC);
         crop_tensor->allocator()->init(crop_result_info);
         _crop_results.emplace_back(std::move(crop_tensor));
         auto       scale_tensor = std::make_unique<CLTensor>();
         TensorInfo scaled_result_info(out_shape, 1, DataType::F32);
         scaled_result_info.set_data_layout(DataLayout::NHWC);
         scale_tensor->allocator()->init(scaled_result_info);
         _scaled_results.emplace_back(std::move(scale_tensor));
         // Size of the crop box in _boxes has to be given before the configure
         uint32_t    batch_index;
         Coordinates start{};
         Coordinates end{};
         configure_crop(_input, _boxes, _box_ind, _crop_results[num_box].get(), num_box, start, end, batch_index);
         auto scale_kernel = std::make_unique<CLScale>();
         scale_kernel->configure(
             compile_context, _crop_results[num_box].get(), _scaled_results[num_box].get(),
             ScaleKernelInfo{_method, BorderMode::CONSTANT, PixelValue(_extrapolation_value), SamplingPolicy::TOP_LEFT});
         _scale.emplace_back(std::move(scale_kernel));
         Window win = calculate_max_window(*_output->info());
         win.set(3, Window::Dimension(num_box, num_box + 1, 1));
         auto copy_kernel = std::make_unique<CLCopy>();
         copy_kernel->configure(compile_context, _scaled_results[num_box].get(), _output, &win);
         _copy.emplace_back(std::move(copy_kernel));
         _crop_results[num_box]->allocator()->allocate();
         _scaled_results[num_box]->allocator()->allocate();
         bool is_width_flipped  = end[0] < start[0];
         bool is_height_flipped = end[1] < start[1];
         /** The number of rows out of bounds at the start and end of _crop_results[num_box].get(). */
         std::array<int32_t, 2> rows_out_of_bounds{0};
         /** The number of columns out of bounds at the start and end of _crop_results[num_box].get(). */
         std::array<int32_t, 2> cols_out_of_bounds{0};
         if (is_height_flipped)
         {
             rows_out_of_bounds[0] = start[1] >= static_cast<int32_t>(_input->info()->dimension(2))
                                         ? std::min(start[1] - _input->info()->dimension(2) + 1,
                                                    _crop_results[num_box].get()->info()->dimension(2))
                                         : 0;
             rows_out_of_bounds[1] =
                 end[1] < 0 ? std::min(-end[1], static_cast<int32_t>(_crop_results[num_box].get()->info()->dimension(2)))
                            : 0;
         }
         else
         {
             rows_out_of_bounds[0] =
                 start[1] < 0
                     ? std::min(-start[1], static_cast<int32_t>(_crop_results[num_box].get()->info()->dimension(2)))
                     : 0;
             rows_out_of_bounds[1] = end[1] >= static_cast<int32_t>(_input->info()->dimension(2))
                                         ? std::min(end[1] - _input->info()->dimension(2) + 1,
                                                    _crop_results[num_box].get()->info()->dimension(2))
                                         : 0;
         }
         if (is_width_flipped)
         {
             cols_out_of_bounds[0] = start[0] >= static_cast<int32_t>(_input->info()->dimension(1))
                                         ? std::min(start[0] - _input->info()->dimension(1) + 1,
                                                    _crop_results[num_box].get()->info()->dimension(1))
                                         : 0;
             cols_out_of_bounds[1] =
                 end[0] < 0 ? std::min(-end[0], static_cast<int32_t>(_crop_results[num_box].get()->info()->dimension(1)))
                            : 0;
         }
         else
         {
             cols_out_of_bounds[0] =
                 start[0] < 0
                     ? std::min(-start[0], static_cast<int32_t>(_crop_results[num_box].get()->info()->dimension(1)))
                     : 0;
             cols_out_of_bounds[1] = end[0] >= static_cast<int32_t>(_input->info()->dimension(1))
                                         ? std::min(end[0] - _input->info()->dimension(1) + 1,
                                                    _crop_results[num_box].get()->info()->dimension(1))
                                         : 0;
         }
         Window full_window = calculate_max_window(*_crop_results[num_box].get()->info());
         //  Full _crop_results[num_box].get() window:
         //  --------------------------------
         //  |          Out of bounds       |
         //  |          rows before         |
         //  |------------------------------|
         //  | Out of | In         | Out of |
         //  | bounds | bounds     | bounds |
         //  | cols   | elements   | cols   |
         //  | before | copied     | after  |
         //  |        | from input |        |
         //  |------------------------------|
         //  |        Out of bounds         |
         //  |        rows after            |
         //  |------------------------------|
         // Use a separate _crop_results[num_box].get() window for each section of the full _crop_results[num_box].get() window.
         // Fill all _crop_results[num_box].get() rows that have no elements that are within the input bounds
         // with the extrapolation value using memset.
         // First for the rows before the in bounds rows.
         if (rows_out_of_bounds[0] > 0)
         {
             Window slice_fill_rows_before(full_window);
             slice_fill_rows_before.set(2, Window::Dimension(0, rows_out_of_bounds[0], 1));
             auto kernel = std::make_unique<CLFill>();
             kernel->configure(compile_context, _crop_results[num_box].get(), extrapolation_value,
                               &slice_fill_rows_before);
             //_internal_functions.emplace_back(std::move(kernel));
             _internal_functions.push_back(std::move(kernel));
         }
         Window slice_in(full_window);
         slice_in.set(2,
                      Window::Dimension(rows_out_of_bounds[0],
                                        _crop_results[num_box].get()->info()->dimension(2) - rows_out_of_bounds[1], 1));
         slice_in.set(1,
                      Window::Dimension(cols_out_of_bounds[0],
                                        _crop_results[num_box].get()->info()->dimension(1) - cols_out_of_bounds[1], 1));
         int rows_in_bounds = static_cast<int32_t>(_crop_results[num_box].get()->info()->dimension(2)) -
                              rows_out_of_bounds[0] - rows_out_of_bounds[1];
         if (rows_in_bounds > 0)
         {
             // Fill all elements that share a row with an in bounds element with the extrapolation value.
             if (cols_out_of_bounds[0] > 0)
             {
                 Window slice_fill_cols_before(slice_in);
                 slice_fill_cols_before.set(1, Window::Dimension(0, cols_out_of_bounds[0], 1));
                 auto kernel = std::make_unique<CLFill>();
                 kernel->configure(compile_context, _crop_results[num_box].get(), extrapolation_value,
                                   &slice_fill_cols_before);
                 //_internal_functions.emplace_back(std::move(kernel));
                 _internal_functions.push_back(std::move(kernel));
             }
             if (cols_out_of_bounds[1] > 0)
             {
                 Window slice_fill_cols_after(slice_in);
                 slice_fill_cols_after.set(
                     1, Window::Dimension(_crop_results[num_box].get()->info()->dimension(1) - cols_out_of_bounds[1],
                                          _crop_results[num_box].get()->info()->dimension(1), 1));
                 auto kernel = std::make_unique<CLFill>();
                 kernel->configure(compile_context, _crop_results[num_box].get(), extrapolation_value,
                                   &slice_fill_cols_after);
                 //_internal_functions.emplace_back(std::move(kernel));
                 _internal_functions.push_back(std::move(kernel));
             }
             // Copy all elements within the input bounds from the input tensor.
             int cols_in_bounds = static_cast<int32_t>(_crop_results[num_box].get()->info()->dimension(1)) -
                                  cols_out_of_bounds[0] - cols_out_of_bounds[1];
             if (cols_in_bounds > 0)
             {
                 Coordinates2D start_in{
                     is_width_flipped ? start[0] - cols_out_of_bounds[0] : start[0] + cols_out_of_bounds[0],
                     is_height_flipped ? start[1] - rows_out_of_bounds[0] : start[1] + rows_out_of_bounds[0]};
                 Coordinates2D end_in{
                     is_width_flipped ? start_in.x - cols_in_bounds + 1 : start_in.x + cols_in_bounds - 1,
                     is_height_flipped ? start_in.y - rows_in_bounds + 1 : start_in.y + rows_in_bounds - 1};
                 auto kernel = std::make_unique<CLCrop>();
                 kernel->configure(compile_context, _input, _crop_results[num_box].get(), start_in, end_in, batch_index,
                                   extrapolation_value, &slice_in);
                 //_internal_functions.emplace_back(std::move(kernel));
                 _internal_functions.push_back(std::move(kernel));
             }
         }
         // Fill all rows after the in bounds elements with the extrapolation value.
         if (rows_out_of_bounds[1] > 0)
         {
             Window slice_fill_rows_after(full_window);
             slice_fill_rows_after.set(
                 2, Window::Dimension(_crop_results[num_box].get()->info()->dimension(2) - rows_out_of_bounds[1],
                                      _crop_results[num_box].get()->info()->dimension(2), 1));
             auto kernel = std::make_unique<CLFill>();
             kernel->configure(compile_context, _crop_results[num_box].get(), extrapolation_value,
                               &slice_fill_rows_after);
             //_internal_functions.emplace_back(std::move(kernel));
             _internal_functions.push_back(std::move(kernel));
         }
     }
     _boxes->unmap(CLScheduler::get().queue());
     _box_ind->unmap(CLScheduler::get().queue());
     CLScheduler::get().sync();
 }
References CLCropResize::_box_ind, CLCropResize::_boxes, CLCropResize::_copy, CLCropResize::_crop_results, CLCropResize::_extrapolation_value, CLCropResize::_input, CLCropResize::_internal_functions, CLCropResize::_method, CLCropResize::_num_boxes, CLCropResize::_output, CLCropResize::_scale, CLCropResize::_scaled_results, ARM_COMPUTE_ERROR_ON_NULLPTR, ARM_COMPUTE_ERROR_THROW_ON, ARM_COMPUTE_LOG_PARAMS, arm_compute::auto_init_if_empty(), arm_compute::calculate_max_window(), arm_compute::CONSTANT, ITensorInfo::dimension(), arm_compute::mlgo::parser::end(), arm_compute::F32, CLScheduler::get(), ITensor::info(), arm_compute::test::validation::info, arm_compute::test::validation::input, ICLTensor::map(), arm_compute::NHWC, arm_compute::test::validation::output_shape, Window::set(), TensorInfo::set_data_layout(), CLScheduler::sync(), ITensorInfo::tensor_shape(), arm_compute::TOP_LEFT, ICLTensor::unmap(), CLCropResize::validate(), Coordinates2D::x, and Coordinates2D::y.
configure() [2/2]
void configure (const ICLTensor * input, ICLTensor * boxes, ICLTensor * box_ind, ICLTensor * output, Coordinates2D crop_size, InterpolationPolicy method = InterpolationPolicy::BILINEAR, float extrapolation_value = 0)
Configure kernel.
Valid data layouts:
NHWC
Valid data type configurations:
src0 src1 src2 dst
All F32 F32 F32
Note
Supported tensor rank: up to 4
Box indices may be outside of the bounds, in which case extrapolation_value is used.
Start and end indices of boxes are inclusive.
Parameters
[in] input Source tensor containing N batches of 3D images to be cropped. Data type supported: All
[in] boxes Tensor containing the boxes used to crop the images. It has to be known before configuration. Data type supported: F32
[in] box_ind One dimensional tensor containing the batch index of the 3D image in input that the corresponding box in boxes will be applied to. It has to be known before configuration. Data type supported: F32
[out] output Destination tensor containing a cropped and resized image for each box in boxes. Data type supported: F32
[in] crop_size The dimensions that each cropped image will be resized to.
[in] method The policy to be used when resizing image. Default is bilinear.
[in] extrapolation_value Value to be used for values outside of the image for cropping and resizing. Default is 0.
Definition at line 111 of file CLCropResize.cpp.
 {
     configure(CLKernelLibrary::get().get_compile_context(), input, boxes, box_ind, output, crop_size, method,
               extrapolation_value);
 }
References CLKernelLibrary::get(), and arm_compute::test::validation::input.
operator=() [1/2]
CLCropResize& operator= (CLCropResize &&) default
Allow instances of this class to be moved.
operator=() [2/2]
CLCropResize& operator= (const CLCropResize &) delete
Prevent instances of this class from being copied (As this class contains pointers)
run()
void run () override virtual
Run the kernels contained in the function.
For CPU kernels:
Multi-threading is used for the kernels which are parallelisable.
By default std::thread::hardware_concurrency() threads are used.
Note
CPPScheduler::set_num_threads() can be used to manually set the number of threads
For OpenCL kernels:
All the kernels are enqueued on the queue associated with CLScheduler.
The queue is then flushed.
Note
The function will not block until the kernels are executed. It is the user's responsibility to wait.
Will call prepare() on first run if hasn't been done
Implements IFunction.
Definition at line 356 of file CLCropResize.cpp.
 {
     ARM_COMPUTE_ERROR_ON_MSG(_output == nullptr, "Unconfigured function");
     for (unsigned int i = 0; i < _internal_functions.size(); ++i)
     {
         _internal_functions[i]->run();
     }
     CLScheduler::get().sync();
     for (auto &kernel : _scale)
     {
         kernel->run();
     }
     CLScheduler::get().sync();
     for (auto &kernel : _copy)
     {
         kernel->run();
     }
     CLScheduler::get().sync();
 }
References CLCropResize::_copy, CLCropResize::_internal_functions, CLCropResize::_output, CLCropResize::_scale, ARM_COMPUTE_ERROR_ON_MSG, CLScheduler::get(), and CLScheduler::sync().
validate()
Status validate (const ITensorInfo * input, ITensorInfo * boxes, ITensorInfo * box_ind, const ITensorInfo * output, Coordinates2D crop_size, InterpolationPolicy method, float extrapolation_value) static
Static function to check if given info will lead to a valid configuration of NESlice.
Note
Supported tensor rank: up to 4
Box indices may be outside of the bounds, in which case extrapolation_value is used.
Start and end indices of boxes are inclusive.
Parameters
[in] input Source tensor info containing N batches of 3D images to be cropped. Data type supported: All
[in] boxes Tensor info for the tensor containing the boxes used to crop the images. Data type supported: F32
[in] box_ind Tensor info for the one dimensional tensor containing the batch index of the 3D image in input that the corresponding box in boxes will be applied to. Data type supported: F32
[in] output Tensor info for the destination tensor containing a cropped and resized image for each box in boxes. Data type supported: F32
[in] crop_size The dimensions that each cropped image will be resized to.
[in] method The policy to be used when resizing image. Default is bilinear.
[in] extrapolation_value Value to be used for values outside of the image for cropping and resizing. Default is 0.
Returns
A status
Definition at line 86 of file CLCropResize.cpp.
 {
     ARM_COMPUTE_RETURN_ERROR_ON(crop_size.x <= 0 || crop_size.y <= 0);
     ARM_COMPUTE_RETURN_ERROR_ON(method == InterpolationPolicy::AREA);
     ARM_COMPUTE_RETURN_ERROR_ON(boxes->tensor_shape()[0] != 4);
     ARM_COMPUTE_RETURN_ERROR_ON(boxes->tensor_shape()[1] != box_ind->tensor_shape()[0]);
     TensorInfo temp_info;
     ARM_COMPUTE_RETURN_ON_ERROR(CLCrop::validate(input->clone().get(), &temp_info, {0, 0}, {1, 1},
                                                  input->dimension(3) - 1, extrapolation_value));
     if (output->total_size() > 0)
     {
         ARM_COMPUTE_RETURN_ERROR_ON_DATA_TYPE_NOT_IN(output, DataType::F32);
         ARM_COMPUTE_RETURN_ERROR_ON_MISMATCHING_DATA_LAYOUT(input, output);
         TensorShape out_shape(input->tensor_shape()[0], crop_size.x, crop_size.y, boxes->tensor_shape()[1]);
         ARM_COMPUTE_RETURN_ERROR_ON_MISMATCHING_DIMENSIONS(output->tensor_shape(), out_shape);
     }
     return Status{};
 }
References arm_compute::AREA, ARM_COMPUTE_RETURN_ERROR_ON, ARM_COMPUTE_RETURN_ERROR_ON_DATA_TYPE_NOT_IN, ARM_COMPUTE_RETURN_ERROR_ON_MISMATCHING_DATA_LAYOUT, ARM_COMPUTE_RETURN_ERROR_ON_MISMATCHING_DIMENSIONS, ARM_COMPUTE_RETURN_ON_ERROR, arm_compute::F32, arm_compute::test::validation::input, ITensorInfo::tensor_shape(), ITensorInfo::total_size(), CLCrop::validate(), Coordinates2D::x, and Coordinates2D::y.
Referenced by CLCropResize::configure().
Field Documentation
_box_ind
ICLTensor* _box_ind
Definition at line 146 of file CLCropResize.h.
Referenced by CLCropResize::configure().
_boxes
ICLTensor* _boxes
Definition at line 145 of file CLCropResize.h.
Referenced by CLCropResize::configure().
_copy
std::vector<std::unique_ptr<CLCopy> > _copy
Definition at line 153 of file CLCropResize.h.
Referenced by CLCropResize::configure(), and CLCropResize::run().
_crop_results
std::vector<std::unique_ptr<CLTensor> > _crop_results
Definition at line 154 of file CLCropResize.h.
Referenced by CLCropResize::configure().
_extrapolation_value
float _extrapolation_value
Definition at line 150 of file CLCropResize.h.
Referenced by CLCropResize::configure().
_input
const ICLTensor* _input
Definition at line 144 of file CLCropResize.h.
Referenced by CLCropResize::configure().
_internal_functions
std::vector<std::unique_ptr<IFunction> > _internal_functions
Definition at line 157 of file CLCropResize.h.
Referenced by CLCropResize::configure(), and CLCropResize::run().
_method
InterpolationPolicy _method
Definition at line 149 of file CLCropResize.h.
Referenced by CLCropResize::configure().
_num_boxes
size_t _num_boxes
Definition at line 148 of file CLCropResize.h.
Referenced by CLCropResize::configure().
_output
ICLTensor* _output
Definition at line 147 of file CLCropResize.h.
Referenced by CLCropResize::configure(), and CLCropResize::run().
_scale
std::vector<std::unique_ptr<CLScale> > _scale
Definition at line 152 of file CLCropResize.h.
Referenced by CLCropResize::configure(), and CLCropResize::run().
_scaled_results
std::vector<std::unique_ptr<CLTensor> > _scaled_results
Definition at line 155 of file CLCropResize.h.
Referenced by CLCropResize::configure().
The documentation for this class was generated from the following files:
arm_compute/runtime/CL/functions/CLCropResize.h
src/runtime/CL/functions/CLCropResize.cpp