Compute Library: GpuMatMulSettings Class Reference
GpuMatMulSettings Class Reference
Operator backend specific settings.
#include <GpuMatMul.h>
Public Member Functions
GpuMatMulSettings & n0 (int n0)
Set N0: number of columns processed by each work-item.
int n0 () const
Get N0: number of columns processed by each work-item.
GpuMatMulSettings & m0 (int m0)
Set M0: number of rows processed by each work-item.
int m0 () const
Get M0: number of rows processed by each work-item.
GpuMatMulSettings & k0 (int k0)
Set K0: number of inner accumulations.
int k0 () const
Get K0: number of inner accumulations.
Detailed Description
Operator backend specific settings.
Definition at line 43 of file GpuMatMul.h.
Member Function Documentation
k0() [1/2]
int k0 () const
Get K0: number of inner accumulations.
k0() [2/2]
GpuMatMulSettings& k0 (int k0)
Set K0: number of inner accumulations.
Referenced by GpuCkwMatMul::get_name(), and GpuCkwMatMul::write_component_code().
m0() [1/2]
int m0 () const
Get M0: number of rows processed by each work-item.
m0() [2/2]
GpuMatMulSettings& m0 (int m0)
Set M0: number of rows processed by each work-item.
Referenced by GpuCkwMatMul::get_name(), and GpuCkwMatMul::get_window().
n0() [1/2]
int n0 () const
Get N0: number of columns processed by each work-item.
n0() [2/2]
GpuMatMulSettings& n0 (int n0)
Set N0: number of columns processed by each work-item.
Referenced by GpuCkwMatMul::get_name(), and GpuCkwMatMul::get_window().
The documentation for this class was generated from the following file:
arm_compute/dynamic_fusion/sketch/gpu/operators/GpuMatMul.h