Compute Library: CpuMaxUnpoolingLayerKernel Class Reference
CpuMaxUnpoolingLayerKernel Class Reference
Interface for the pooling layer kernel.
#include <CpuMaxUnpoolingLayerKernel.h>
Data Structures
struct MaxUnpoolingKernel
Public Member Functions
CpuMaxUnpoolingLayerKernel ()=default
Default constructor.
ARM_COMPUTE_DISALLOW_COPY_ALLOW_MOVE (CpuMaxUnpoolingLayerKernel)
void configure (const ITensorInfo *src, const ITensorInfo *indices, ITensorInfo *dst, const PoolingLayerInfo &pool_info)
Configure kernel for a given list of arguments.
void run_op (ITensorPack &tensors, const Window &window, const ThreadInfo &info) override
Execute the kernel on the passed window.
const char * name () const override
Name of the kernel.
Public Member Functions inherited from ICPPKernel
virtual ~ICPPKernel ()=default
Default destructor.
virtual void run (const Window &window, const ThreadInfo &info)
Execute the kernel on the passed window.
virtual void run_nd (const Window &window, const ThreadInfo &info, const Window &thread_locator)
legacy compatibility layer for implemantions which do not support thread_locator In these cases we simply narrow the interface down the legacy version
virtual size_t get_mws (const CPUInfo &platform, size_t thread_count) const
Return minimum workload size of the relevant kernel.
Public Member Functions inherited from IKernel
IKernel ()
Constructor.
virtual ~IKernel ()=default
Destructor.
virtual bool is_parallelisable () const
Indicates whether or not the kernel is parallelisable.
virtual BorderSize border_size () const
The size of the border for that kernel.
const Window & window () const
The maximum window the kernel can be executed on.
bool is_window_configured () const
Function to check if the embedded window of this kernel has been configured.
Static Public Member Functions
static Status validate (const ITensorInfo *src, const ITensorInfo *indices, const ITensorInfo *dst, const PoolingLayerInfo &pool_info)
Static function to check if given info will lead to a valid configuration of CpuMaxUnpoolingLayerKernel.
static const std::vector< MaxUnpoolingKernel > & get_available_kernels ()
Static Public Member Functions inherited from ICpuKernel< CpuMaxUnpoolingLayerKernel >
static const auto * get_implementation (const SelectorType &selector, KernelSelectionType selection_type=KernelSelectionType::Supported)
Micro-kernel selector.
Additional Inherited Members
Static Public Attributes inherited from ICPPKernel
static constexpr size_t default_mws = 1
Detailed Description
Interface for the pooling layer kernel.
Definition at line 37 of file CpuMaxUnpoolingLayerKernel.h.
Constructor & Destructor Documentation
CpuMaxUnpoolingLayerKernel()
CpuMaxUnpoolingLayerKernel () default
Default constructor.
Member Function Documentation
ARM_COMPUTE_DISALLOW_COPY_ALLOW_MOVE()
ARM_COMPUTE_DISALLOW_COPY_ALLOW_MOVE (CpuMaxUnpoolingLayerKernel)
configure()
void configure (const ITensorInfo * src, const ITensorInfo * indices, ITensorInfo * dst, const PoolingLayerInfo & pool_info)
Configure kernel for a given list of arguments.
Note
Dst shape must be equal to the shape of the original src to pool.
Parameters
[in] src Source tensor to permute. Data types supported: QASYMM8/QASYMM8_SIGNED/F16/F32.
[in] indices Tensor containing the offset to store the src elements in the dst tensor. CpuMaxUnpooling with indices should precede this function in order to properly reconstruct the output tensor. The tensor shape of this tensor has to be equal to the src tensor shape. Data type supported: U32.
[out] dst Destination tensor. Data types supported: Same as src
[in] pool_info Contains pooling operation information described in PoolingLayerInfo.
Definition at line 93 of file CpuMaxUnpoolingLayerKernel.cpp.
 {
     ARM_COMPUTE_ERROR_ON_NULLPTR(src, dst, indices);
     ARM_COMPUTE_ERROR_THROW_ON(validate_arguments(src, indices, dst, pool_info));
     ARM_COMPUTE_UNUSED(indices);
     const auto uk = CpuMaxUnpoolingLayerKernel::get_implementation(
         DataTypeISASelectorData{src->data_type(), CPUInfo::get().get_isa()});
     ARM_COMPUTE_ERROR_ON_NULLPTR(uk);
     _run_method = uk->ukernel;
     const TensorShape output_shape = compute_unpool_shape(*src, pool_info);
     auto_init_if_empty(*dst, src->clone()->set_tensor_shape(output_shape));
     auto window = calculate_max_window(*src, Steps());
     ICpuKernel::configure(window);
 }
References ARM_COMPUTE_ERROR_ON_NULLPTR, ARM_COMPUTE_ERROR_THROW_ON, ARM_COMPUTE_UNUSED, arm_compute::auto_init_if_empty(), arm_compute::calculate_max_window(), arm_compute::misc::shape_calculator::compute_unpool_shape(), arm_compute::test::validation::dst, CPUInfo::get(), ICpuKernel< CpuMaxUnpoolingLayerKernel >::get_implementation(), arm_compute::test::validation::output_shape, arm_compute::test::validation::src, and arm_compute::cpu::kernels::validate_arguments().
get_available_kernels()
const std::vector< CpuMaxUnpoolingLayerKernel::MaxUnpoolingKernel > & get_available_kernels () static
Definition at line 142 of file CpuMaxUnpoolingLayerKernel.cpp.
 {
     return available_kernels;
 }
name()
const char * name () const override virtual
Name of the kernel.
Returns
Kernel name
Implements ICPPKernel.
Definition at line 137 of file CpuMaxUnpoolingLayerKernel.cpp.
 {
     return "CpuMaxUnpoolingLayerKernel";
 }
run_op()
void run_op (ITensorPack & tensors, const Window & window, const ThreadInfo & info) override virtual
Execute the kernel on the passed window.
Warning
If is_parallelisable() returns false then the passed window must be equal to window()
Note
The window has to be a region within the window returned by the window() method
The width of the window has to be a multiple of num_elems_processed_per_iteration().
Parameters
[in] tensors A vector containing the tensors to operate on.
[in] window Region on which to execute the kernel. (Must be a region of the window returned by window())
[in] info Info about executing thread and CPU.
Reimplemented from ICPPKernel.
Definition at line 124 of file CpuMaxUnpoolingLayerKernel.cpp.
 {
     ARM_COMPUTE_UNUSED(info);
     ARM_COMPUTE_ERROR_ON_UNCONFIGURED_KERNEL(this);
     ARM_COMPUTE_ERROR_ON_INVALID_SUBWINDOW(ICpuKernel::window(), window);
     const auto src     = tensors.get_const_tensor(TensorType::ACL_SRC_0);
     const auto indices = tensors.get_const_tensor(TensorType::ACL_SRC_1);
     const auto dst     = tensors.get_tensor(TensorType::ACL_DST);
     _run_method(src, indices, dst, window);
 }
References arm_compute::ACL_DST, arm_compute::ACL_SRC_0, arm_compute::ACL_SRC_1, ARM_COMPUTE_ERROR_ON_INVALID_SUBWINDOW, ARM_COMPUTE_ERROR_ON_UNCONFIGURED_KERNEL, ARM_COMPUTE_UNUSED, arm_compute::test::validation::dst, ITensorPack::get_const_tensor(), ITensorPack::get_tensor(), arm_compute::test::validation::info, arm_compute::test::validation::src, and IKernel::window().
validate()
Status validate (const ITensorInfo * src, const ITensorInfo * indices, const ITensorInfo * dst, const PoolingLayerInfo & pool_info) static
Static function to check if given info will lead to a valid configuration of CpuMaxUnpoolingLayerKernel.
Parameters
[in] src Source tensor to permute. Data types supported: QASYMM8/QASYMM8_SIGNED/F16/F32.
[in] indices Tensor info of the indices of the maximal values. Data type supported: U32.
[out] dst Destination tensor. Data types supported: Same as src
[in] pool_info Contains pooling operation information described in PoolingLayerInfo.
Returns
a status
Definition at line 114 of file CpuMaxUnpoolingLayerKernel.cpp.
 {
     ARM_COMPUTE_RETURN_ERROR_ON_NULLPTR(src, indices, dst);
     ARM_COMPUTE_RETURN_ON_ERROR(validate_arguments(src, indices, dst, pool_info));
     return Status{};
 }
References ARM_COMPUTE_RETURN_ERROR_ON_NULLPTR, ARM_COMPUTE_RETURN_ON_ERROR, arm_compute::test::validation::dst, arm_compute::test::validation::src, and arm_compute::cpu::kernels::validate_arguments().
Referenced by CpuMaxUnpooling::validate().
The documentation for this class was generated from the following files:
src/cpu/kernels/CpuMaxUnpoolingLayerKernel.h
src/cpu/kernels/CpuMaxUnpoolingLayerKernel.cpp