Compute Library: QuantizeWrapper< To, Tr, Tgemm > Class Template Reference
QuantizeWrapper< To, Tr, Tgemm > Class Template Reference
#include <quantize_wrapper.hpp>
Public Member Functions
QuantizeWrapper (const QuantizeWrapper &)=delete
QuantizeWrapper operator= (const QuantizeWrapper &)=delete
QuantizeWrapper (const GemmArgs &args, const Requantize32 &qp)
void set_arrays (const To *A, const int lda, const int A_batch_stride, const int A_multi_stride, const To *B, const int ldb, const int B_multi_stride, Tr *C, const int ldc, const int C_batch_stride, const int C_multi_stride, const Tr *bias, const int bias_multi_stride) override
ndrange_t get_window_size () const override
void set_nthreads (int nthreads) override
void execute (const ndcoord_t &work_range, const ndcoord_t &thread_locator, int threadid) override
Main execute member fucntion.
size_t get_working_size () const override
void set_working_space (void *space) override
bool B_is_pretransposed () const override
bool B_pretranspose_required () const override
size_t get_B_pretransposed_array_size () const override
void requantize_bias (void *in_buffer, const To *B, const int ldb, const int B_multi_stride) override
void pretranspose_B_array (void *buffer, const To *B, const int ldb, const int B_multi_stride) override
void set_pretransposed_B_data (void *buffer) override
void set_quantized_bias (const int32_t *bias, size_t bias_multi_stride) override
GemmConfig get_config () override
Public Member Functions inherited from GemmCommon< To, Tr >
void set_arrays_generic (const void *A, const int lda, const int A_batch_stride, const int A_multi_stride, const void *B, const int ldb, const int B_multi_stride, void *C, const int ldc, const int C_batch_stride, const int C_multi_stride, const void *bias, const int bias_multi_stride) override
void pretranspose_B_array_generic (void *out, const void *in, const int row_stride, const int multi_stride) override
virtual void pretranspose_B_array_part (void *out, const To *in, const int row_stride, const int multi_stride, size_t, size_t)
void pretranspose_B_array_part_generic (void *out, const void *in, const int row_stride, const int multi_stride, size_t start, size_t end) override
virtual void set_indirect_parameters (size_t, const To *const *const *)
void set_indirect_parameters_generic (size_t sz, const void *const *const *ptr) override
Public Member Functions inherited from IGemmCommon
virtual bool supports_dynamic_scheduling () const
virtual size_t get_B_pretranspose_window_size () const
virtual void set_convolution_parameters (ConvolutionParameters)
virtual ~IGemmCommon ()
Detailed Description
template<typename To, typename Tr, typename Tgemm>
class arm_gemm::QuantizeWrapper< To, Tr, Tgemm >
Definition at line 38 of file quantize_wrapper.hpp.
Constructor & Destructor Documentation
QuantizeWrapper() [1/2]
QuantizeWrapper (const QuantizeWrapper< To, Tr, Tgemm > &) delete
QuantizeWrapper() [2/2]
QuantizeWrapper (const GemmArgs & args, const Requantize32 & qp) inline
Definition at line 112 of file quantize_wrapper.hpp.
                                                                   : _params(qp), _args(args), _barrier(args._maxthreads) {
         GemmArgs newargs = GemmArgs(args._ci, args._Msize, args._Nsize, args._Ksize, args._Ksections, args._nbatches, args._nmulti, args._indirect_input, Activation(), args._maxthreads);
         _subgemm = gemm<To, Tgemm>(newargs);
         if (_subgemm == nullptr) {
             return;
         }
     }
References GemmTuner::args.
Member Function Documentation
B_is_pretransposed()
bool B_is_pretransposed () const inline override virtual
Reimplemented from IGemmCommon.
Definition at line 169 of file quantize_wrapper.hpp.
{
         /* We clear this flag if the subgemm isn't pretransposed, so just return its value */
         return _subgemm->B_is_pretransposed();
     }
B_pretranspose_required()
bool B_pretranspose_required () const inline override virtual
Reimplemented from IGemmCommon.
Definition at line 174 of file quantize_wrapper.hpp.
{
         return _subgemm->B_pretranspose_required();
     }
execute()
void execute (const ndcoord_t & work_range, const ndcoord_t & thread_locator, int threadid) inline override virtual
Main execute member fucntion.
Parameters
[in] work_range specifies the range of work we want to be computed, total range defined by get_window_size()
[in] thread_locator where are we inside of the thread space
[in] threadid a unique threadid
Implements IGemmCommon.
Definition at line 141 of file quantize_wrapper.hpp.
{
         _subgemm->execute(work_range, thread_locator, threadid);
         _barrier.arrive_and_wait();
         requantize_runtime(threadid);
     }
References barrier::arrive_and_wait().
get_B_pretransposed_array_size()
size_t get_B_pretransposed_array_size () const inline override virtual
Reimplemented from IGemmCommon.
Definition at line 178 of file quantize_wrapper.hpp.
{
         return _subgemm->get_B_pretransposed_array_size() + col_sum_size();
     }
get_config()
GemmConfig get_config () inline override virtual
Implements IGemmCommon.
Definition at line 205 of file quantize_wrapper.hpp.
{
         GemmConfig c = _subgemm->get_config();
         std::string n = "quantize_wrapper[";
         n.append(c.filter);
         n.append("]");
         c.method = GemmMethod::QUANTIZE_WRAPPER;
         c.filter = n;
         return c;
     }
References GemmConfig::filter, GemmConfig::method, and arm_gemm::QUANTIZE_WRAPPER.
get_window_size()
ndrange_t get_window_size () const inline override virtual
Returns
an ndrange containing ranges of the compute space which can be broken up and parallelised over
Implements IGemmCommon.
Definition at line 131 of file quantize_wrapper.hpp.
{
         return { _subgemm->get_window_size() };
     }
get_working_size()
size_t get_working_size () const inline override virtual
Reimplemented from IGemmCommon.
Definition at line 149 of file quantize_wrapper.hpp.
{
         return _subgemm->get_working_size() + local_working_size();
     }
operator=()
QuantizeWrapper operator= (const QuantizeWrapper< To, Tr, Tgemm > &) delete
pretranspose_B_array()
void pretranspose_B_array (void * buffer, const To * B, const int ldb, const int B_multi_stride) inline override virtual
Reimplemented from GemmCommon< To, Tr >.
Definition at line 187 of file quantize_wrapper.hpp.
{
         uintptr_t buffer_int = reinterpret_cast<uintptr_t>(buffer);
         _subgemm->pretranspose_B_array(reinterpret_cast<void *>(buffer_int + col_sum_size()), B, ldb, B_multi_stride);
         requantize_bias(buffer, B, ldb, B_multi_stride);
     }
References QuantizeWrapper< To, Tr, Tgemm >::requantize_bias().
requantize_bias()
void requantize_bias (void * in_buffer, const To * B, const int ldb, const int B_multi_stride) inline override virtual
Reimplemented from GemmCommon< To, Tr >.
Definition at line 182 of file quantize_wrapper.hpp.
{
         _col_sums = reinterpret_cast<int32_t *>(in_buffer);
         col_sums_pretransposed(B, ldb, B_multi_stride);
     }
Referenced by QuantizeWrapper< To, Tr, Tgemm >::pretranspose_B_array().
set_arrays()
void set_arrays (const To * A, const int lda, const int A_batch_stride, const int A_multi_stride, const To * B, const int ldb, const int B_multi_stride, Tr * C, const int ldc, const int C_batch_stride, const int C_multi_stride, const Tr * bias, const int bias_multi_stride) inline override virtual
Reimplemented from GemmCommon< To, Tr >.
Definition at line 121 of file quantize_wrapper.hpp.
{
         GemmCommon<To, Tr>::set_arrays(A, lda, A_batch_stride, A_multi_stride, B, ldb, B_multi_stride, C, ldc, C_batch_stride, C_multi_stride, bias, bias_multi_stride);
         arrays_set = true;
         set_child_arrays();
     }
References bias, and GemmCommon< To, Tr >::set_arrays().
set_nthreads()
void set_nthreads (int nthreads) inline override virtual
Reimplemented from IGemmCommon.
Definition at line 135 of file quantize_wrapper.hpp.
{
         _subgemm->set_nthreads(nthreads);
         _barrier.set_nthreads(nthreads);
         _args._maxthreads = nthreads;
     }
References GemmArgs::_maxthreads, and barrier::set_nthreads().
set_pretransposed_B_data()
void set_pretransposed_B_data (void * buffer) inline override virtual
Reimplemented from IGemmCommon.
Definition at line 194 of file quantize_wrapper.hpp.
{
         uintptr_t buffer_int = reinterpret_cast<uintptr_t>(buffer);
         _subgemm->set_pretransposed_B_data(reinterpret_cast<void *>(buffer_int + col_sum_size()));
         _col_sums = reinterpret_cast<int32_t *>(buffer);
     }
set_quantized_bias()
void set_quantized_bias (const int32_t * bias, size_t bias_multi_stride) inline override virtual
Reimplemented from IGemmCommon.
Definition at line 200 of file quantize_wrapper.hpp.
{
         _params.bias = bias;
         _params.bias_multi_stride = bias_multi_stride;
     }
References Requantize32::bias, bias, and Requantize32::bias_multi_stride.
set_working_space()
void set_working_space (void * space) inline override virtual
Reimplemented from IGemmCommon.
Definition at line 158 of file quantize_wrapper.hpp.
{
         uintptr_t space_int = reinterpret_cast<uintptr_t>(space);
         working_space = space;
         _subgemm->set_working_space(reinterpret_cast<void *>(space_int + local_working_size()));
         _row_sums = reinterpret_cast<int32_t *>(space_int + subgemm_output_size());
         set_child_arrays();
     }
The documentation for this class was generated from the following file:
src/core/NEON/kernels/arm_gemm/quantize_wrapper.hpp