Compute Library: ClComponentDepthwiseConv2d Class Reference
ClComponentDepthwiseConv2d Class Reference final
#include <ClComponentDepthwiseConv2d.h>
Public Types
using Attributes = DepthwiseConv2dAttributes
Attributes are a set of backend-agnostic parameters that define what a component does.
using Settings = ClComponentDepthwiseConv2dSettings
Settings are a set of backend-specific parameters that influence the implementation of a component.
Public Types inherited from IGpuKernelComponent
using Properties = KernelProperties
Public Member Functions
ClComponentDepthwiseConv2d (ComponentId id, const Properties &properties, const ArgumentPack< ITensorInfo > &tensors, const Attributes &attributes, const Settings &settings)
Constructor.
~ClComponentDepthwiseConv2d () override
Destructor.
ClComponentDepthwiseConv2d (const ClComponentDepthwiseConv2d &component)=delete
Prevent instances of this class from being copy constructed.
ClComponentDepthwiseConv2d & operator= (const ClComponentDepthwiseConv2d &component)=delete
Prevent instances of this class from being copied.
ClComponentDepthwiseConv2d (ClComponentDepthwiseConv2d &&component)=default
Allow instances of this class to be move constructed.
ClComponentDepthwiseConv2d & operator= (ClComponentDepthwiseConv2d &&component)=default
Allow instances of this class to be moved.
const IGpuTemplateComponentWriter * template_writer () const override
Get template writer for the component.
GpuComponentType type () const override
Get component type.
Public Member Functions inherited from IGpuKernelComponent
IGpuKernelComponent (ComponentId id, const Properties &properties, const ArgumentPack< ITensorInfo > &tensors)
Constructor.
virtual ~IGpuKernelComponent ()
Destructor.
ComponentId id () const
Get component id.
ArgumentPack< ITensorInfo > tensors () const
Get tensor arguments.
Properties properties () const
Get properties.
virtual const IGpuCkwComponentDriver * ckw_component_driver () const
Static Public Member Functions
static Status validate (const Properties &properties, const ArgumentPack< ITensorInfo > &tensors, const Attributes &attributes, const Settings &settings)
Validate the component.
Detailed Description
Definition at line 100 of file ClComponentDepthwiseConv2d.h.
Member Typedef Documentation
Attributes
using Attributes = DepthwiseConv2dAttributes
Attributes are a set of backend-agnostic parameters that define what a component does.
Definition at line 104 of file ClComponentDepthwiseConv2d.h.
Settings
using Settings = ClComponentDepthwiseConv2dSettings
Settings are a set of backend-specific parameters that influence the implementation of a component.
Definition at line 106 of file ClComponentDepthwiseConv2d.h.
Constructor & Destructor Documentation
ClComponentDepthwiseConv2d() [1/3]
ClComponentDepthwiseConv2d (ComponentId id, const Properties & properties, const ArgumentPack< ITensorInfo > & tensors, const Attributes & attributes, const Settings & settings)
Constructor.
Similar to ClComponentDepthwiseConv2d::validate()
Definition at line 209 of file ClComponentDepthwiseConv2d.cpp.
     : IGpuKernelComponent{id, properties, tensors},
 #ifndef ACL_INTERNAL_TEST_CKW_IN_DF
       _component_writer{std::make_unique<ClTemplateDepthwiseConv2d>(id, tensors, attributes, settings)}
 #else  //ACL_INTERNAL_TEST_CKW_IN_DF
       _component_writer{std::make_unique<GpuCkwDepthwiseConv2d>(id, tensors, attributes, settings)}
 #endif //ACL_INTERNAL_TEST_CKW_IN_DF
 {
     ARM_COMPUTE_UNUSED(attributes, settings);
 }
References IGpuKernelComponent::id(), IGpuKernelComponent::properties(), and IGpuKernelComponent::tensors().
~ClComponentDepthwiseConv2d()
~ClComponentDepthwiseConv2d () override
Destructor.
Definition at line 223 of file ClComponentDepthwiseConv2d.cpp.
 {
 }
ClComponentDepthwiseConv2d() [2/3]
ClComponentDepthwiseConv2d (const ClComponentDepthwiseConv2d & component) delete
Prevent instances of this class from being copy constructed.
ClComponentDepthwiseConv2d() [3/3]
ClComponentDepthwiseConv2d (ClComponentDepthwiseConv2d && component) default
Allow instances of this class to be move constructed.
Member Function Documentation
operator=() [1/2]
ClComponentDepthwiseConv2d& operator= (ClComponentDepthwiseConv2d && component) default
Allow instances of this class to be moved.
operator=() [2/2]
ClComponentDepthwiseConv2d& operator= (const ClComponentDepthwiseConv2d & component) delete
Prevent instances of this class from being copied.
template_writer()
const IGpuTemplateComponentWriter * template_writer () const override virtual
Get template writer for the component.
Reimplemented from IGpuKernelComponent.
Definition at line 227 of file ClComponentDepthwiseConv2d.cpp.
 {
     return _component_writer.get();
 }
type()
GpuComponentType type () const inline override virtual
Get component type.
Implements IGpuKernelComponent.
Definition at line 172 of file ClComponentDepthwiseConv2d.h.
     {
         return GpuComponentType::Complex;
     }
References arm_compute::experimental::dynamic_fusion::Complex.
validate()
Status validate (const Properties & properties, const ArgumentPack< ITensorInfo > & tensors, const Attributes & attributes, const Settings & settings) static
Validate the component.
Parameters
[in] properties Component properties Properties
[in,out] tensors Tensor arguments to the component
[in] attributes Component attributes Attributes
[in] settings Component settings Settings
Returns
Status Validation results
Tensor argument names:
ACL_SRC_0: Input
ACL_SRC_1: Weight
ACL_SRC_2: Bias (Optional)
ACL_DST_0: Output
Tensor argument constness:
ACL_SRC_0: Const
ACL_SRC_1: Const
ACL_SRC_2: Const
ACL_DST_0: Const
Valid data layouts:
NHWC
Valid data type configurations:
ACL_SRC_0 ACL_SRC_1 ACL_SRC_2 ACL_DST_0
F16 F16 F16 F16
F32 F32 F32 F32
Definition at line 111 of file ClComponentDepthwiseConv2d.cpp.
 {
     ARM_COMPUTE_UNUSED(properties, settings);
     const auto src = tensors.get_const_tensor(TensorType::ACL_SRC_0);
     const auto wei = tensors.get_const_tensor(TensorType::ACL_SRC_1);
     const auto bia = tensors.get_const_tensor(TensorType::ACL_SRC_2);
     const auto dst = tensors.get_const_tensor(TensorType::ACL_DST_0);
     ARM_COMPUTE_RETURN_ERROR_ON_NULLPTR(src, wei, dst);
     // 1. Check validity
     // Matching data type
     ARM_COMPUTE_RETURN_ERROR_ON_MISMATCHING_DATA_TYPES(src, wei);
     ARM_COMPUTE_RETURN_ERROR_ON_MISMATCHING_DATA_TYPES(src, dst);
     if (bia != nullptr)
     {
         ARM_COMPUTE_RETURN_ERROR_ON_MISMATCHING_DATA_TYPES(src, bia);
     }
     // Matching data layout
     ARM_COMPUTE_RETURN_ERROR_ON_MISMATCHING_DATA_LAYOUT(src, wei);
     ARM_COMPUTE_RETURN_ERROR_ON_MISMATCHING_DATA_LAYOUT(src, dst);
     if (bia != nullptr)
     {
         ARM_COMPUTE_RETURN_ERROR_ON_MISMATCHING_DATA_LAYOUT(src, bia);
     }
     // All tensor infos are initialized
     ARM_COMPUTE_RETURN_ERROR_ON(src->tensor_shape().total_size() == 0);
     ARM_COMPUTE_RETURN_ERROR_ON(wei->tensor_shape().total_size() == 0);
     ARM_COMPUTE_RETURN_ERROR_ON(dst->tensor_shape().total_size() == 0);
     if (bia != nullptr)
     {
         ARM_COMPUTE_RETURN_ERROR_ON(bia->tensor_shape().total_size() == 0);
     }
     // Device requirements are met
     ARM_COMPUTE_RETURN_ERROR_ON_F16_UNSUPPORTED(src);
     // wei shape is correct
     const DataLayout data_layout = src->data_layout();
     const size_t     channel_idx = get_data_layout_dimension_index(data_layout, DataLayoutDimension::CHANNEL);
     ARM_COMPUTE_RETURN_ERROR_ON(wei->dimension(channel_idx) !=
                                 (src->dimension(channel_idx) * attributes.depth_multiplier()));
     ARM_COMPUTE_RETURN_ERROR_ON_MSG(wei->num_dimensions() > 3, "Weights can be at most 3 dimensional");
     // dst shape is correct
     const PadStrideInfo pad_stride_info =
         PadStrideInfo(attributes.stride().x(), attributes.stride().y(), attributes.pad().left, attributes.pad().right,
                       attributes.pad().top, attributes.pad().bottom, attributes.dimension_rounding_type());
     const ConvolutionInfo conv_info{pad_stride_info, attributes.depth_multiplier(), ActivationLayerInfo(),
                                     attributes.dilation()};
     const TensorShape output_shape = misc::shape_calculator::compute_depthwise_convolution_shape(*src, *wei, conv_info);
     ARM_COMPUTE_RETURN_ERROR_ON_MISMATCHING_DIMENSIONS(dst->tensor_shape(), output_shape);
     // Check strides and dilation
     ARM_COMPUTE_RETURN_ERROR_ON(conv_info.pad_stride_info.stride().first < 1);
     ARM_COMPUTE_RETURN_ERROR_ON(conv_info.pad_stride_info.stride().second < 1);
     ARM_COMPUTE_RETURN_ERROR_ON((conv_info.dilation.x() < 1) || (conv_info.dilation.y() < 1));
     ARM_COMPUTE_RETURN_ERROR_ON(conv_info.pad_stride_info.stride().first > 1 && settings.m0() != 1);
     ARM_COMPUTE_RETURN_ERROR_ON(conv_info.dilation.x() > 1 && settings.m0() != 1);
     if (conv_info.depth_multiplier > 1 && settings.n0() > 1)
     {
         ARM_COMPUTE_RETURN_ERROR_ON((conv_info.depth_multiplier % settings.n0()) != 0);
     }
     // Check export weights to cl image
     ARM_COMPUTE_RETURN_ERROR_ON_MSG((settings.export_weights_to_cl_image() == true) &&
                                         (export_to_cl_image(wei) == false),
                                     "Weights cannot be exported to cl_image!");
     ARM_COMPUTE_RETURN_ERROR_ON((settings.export_weights_to_cl_image() == true) && ((settings.n0() % 4) != 0));
     ARM_COMPUTE_RETURN_ERROR_ON(wei->dimension(channel_idx) !=
                                 (src->dimension(channel_idx) * conv_info.depth_multiplier));
     // bia shape is correct
     if (bia != nullptr)
     {
         ARM_COMPUTE_RETURN_ERROR_ON_MSG(bia->dimension(0) != output_shape[channel_idx],
                                         "Biases size and number of dst feature maps should match");
         ARM_COMPUTE_RETURN_ERROR_ON_MSG(bia->num_dimensions() > 1, "Biases should be one dimensional");
     }
     // 2. Check support level
     // Data type
     ARM_COMPUTE_RETURN_ERROR_ON_DATA_TYPE_CHANNEL_NOT_IN(src, 1, DataType::F16, DataType::F32);
     // Data layout
     ARM_COMPUTE_RETURN_ERROR_ON_DATA_LAYOUT_NOT_IN(src, DataLayout::NHWC);
     // Texture in the input tensor
     ARM_COMPUTE_RETURN_ERROR_ON((settings.export_input_to_cl_image() == true));
     return Status{};
 }
References arm_compute::ACL_DST_0, arm_compute::ACL_SRC_0, arm_compute::ACL_SRC_1, arm_compute::ACL_SRC_2, ARM_COMPUTE_RETURN_ERROR_ON, ARM_COMPUTE_RETURN_ERROR_ON_DATA_LAYOUT_NOT_IN, ARM_COMPUTE_RETURN_ERROR_ON_DATA_TYPE_CHANNEL_NOT_IN, ARM_COMPUTE_RETURN_ERROR_ON_F16_UNSUPPORTED, ARM_COMPUTE_RETURN_ERROR_ON_MISMATCHING_DATA_LAYOUT, ARM_COMPUTE_RETURN_ERROR_ON_MISMATCHING_DATA_TYPES, ARM_COMPUTE_RETURN_ERROR_ON_MISMATCHING_DIMENSIONS, ARM_COMPUTE_RETURN_ERROR_ON_MSG, ARM_COMPUTE_RETURN_ERROR_ON_NULLPTR, ARM_COMPUTE_UNUSED, arm_compute::CHANNEL, arm_compute::cpu::channel_idx, arm_compute::misc::shape_calculator::compute_depthwise_convolution_shape(), arm_compute::test::validation::conv_info, arm_compute::cpu::data_layout, DepthwiseConv2dAttributes::depth_multiplier(), DepthwiseConv2dAttributes::dilation(), DepthwiseConv2dAttributes::dimension_rounding_type(), arm_compute::test::validation::dst, ClComponentDepthwiseConv2dSettings::export_input_to_cl_image(), arm_compute::export_to_cl_image(), ClComponentDepthwiseConv2dSettings::export_weights_to_cl_image(), arm_compute::F16, arm_compute::F32, arm_compute::get_data_layout_dimension_index(), ClComponentDepthwiseConv2dSettings::m0(), ClComponentDepthwiseConv2dSettings::n0(), arm_compute::NHWC, arm_compute::test::validation::output_shape, DepthwiseConv2dAttributes::pad(), IGpuKernelComponent::properties(), arm_compute::test::validation::src, DepthwiseConv2dAttributes::stride(), and IGpuKernelComponent::tensors().
The documentation for this class was generated from the following files:
src/dynamic_fusion/sketch/gpu/components/cl/ClComponentDepthwiseConv2d.h
src/dynamic_fusion/sketch/gpu/components/cl/ClComponentDepthwiseConv2d.cpp