Compute Library: GpuCkwActivation Class Reference
GpuCkwActivation Class Reference
#include <GpuCkwActivation.h>
Public Types
using Attributes = ClComponentActivation::Attributes
Public Types inherited from IGpuCkwComponentDriver
using ComponentGroup = GpuKernelComponentGroup
Public Member Functions
GpuCkwActivation (ComponentId id, const ArgumentPack< ITensorInfo > &tensors, const Attributes &attributes)
Constructor.
ARM_COMPUTE_DISALLOW_COPY_ALLOW_MOVE (GpuCkwActivation)
~GpuCkwActivation () override=default
Destructor.
virtual void write_component_code (const ComponentGroup &comp_group, GpuCkwVariableTable &vtable, GpuCkwScopedKernelWriter writer) const override
Generate kernel component code.
Window get_window () const override
Generate the execution window for the component.
Public Member Functions inherited from IGpuCkwComponentDriver
IGpuCkwComponentDriver (ComponentId id, const ArgumentPack< ITensorInfo > &tensors)
Constructor.
virtual ~IGpuCkwComponentDriver ()
Destructor.
ArgumentPack< ITensorInfo > tensors () const
Get tensor arguments.
virtual std::string get_name (const ComponentGroup &comp_group) const
Generate the name of the component.
virtual std::string get_tuner_id (const ComponentGroup &comp_group) const
Generate the tuner id of the component This id should capture all the parameters that distinguish one kernel's lws tuning from another.
ComponentId id () const
Get component id.
Detailed Description
Definition at line 37 of file GpuCkwActivation.h.
Member Typedef Documentation
Attributes
using Attributes = ClComponentActivation::Attributes
Definition at line 40 of file GpuCkwActivation.h.
Constructor & Destructor Documentation
GpuCkwActivation()
GpuCkwActivation (ComponentId id, const ArgumentPack< ITensorInfo > & tensors, const Attributes & attributes)
Constructor.
For supported configurations please refer to GpuCkwActivation::validate()
Parameters
[in] id Component id
[in] tensors Tensor arguments to the component
[in] attributes Component attributes
Definition at line 89 of file GpuCkwActivation.cpp.
     : IGpuCkwComponentDriver{id, tensors}, _src{}, _dst{}, _attributes{attributes}
 {
     _src = this->tensors().get_const_tensor(TensorType::ACL_SRC_0);
     _dst = this->tensors().get_const_tensor(TensorType::ACL_DST_0);
     ARM_COMPUTE_ERROR_ON_NULLPTR(_src, _dst);
 }
References IGpuCkwComponentDriver::id(), and IGpuCkwComponentDriver::tensors().
~GpuCkwActivation()
~GpuCkwActivation () override default
Destructor.
Member Function Documentation
ARM_COMPUTE_DISALLOW_COPY_ALLOW_MOVE()
ARM_COMPUTE_DISALLOW_COPY_ALLOW_MOVE (GpuCkwActivation)
get_window()
Window get_window () const override virtual
Generate the execution window for the component.
Reimplemented from IGpuCkwComponentDriver.
Definition at line 177 of file GpuCkwActivation.cpp.
 {
     ARM_COMPUTE_ERROR_ON_MSG(_dst->tensor_shape().total_size() == 0U, "Destination tensor is not initialized");
     TensorShape output_shape = _dst->tensor_shape();
     // Collapse Dim 1 (W) and Dim 2 (H) together, leave Dim 0 (C) unchanged
     // This is in line with the collapsing convention used by operators like Conv2d
     output_shape.collapse(2U, 1U);
     constexpr unsigned int vector_size_byte_opencl = 16;
     const unsigned int     num_elems_processed_per_iteration =
         adjust_vec_size(vector_size_byte_opencl / _dst->element_size(), _dst->dimension(0));
     Window win = calculate_max_window(output_shape, Steps(num_elems_processed_per_iteration));
     return win;
 }
References arm_compute::adjust_vec_size(), ARM_COMPUTE_ERROR_ON_MSG, arm_compute::calculate_max_window(), TensorShape::collapse(), ITensorInfo::dimension(), ITensorInfo::element_size(), num_elems_processed_per_iteration, arm_compute::test::validation::output_shape, ITensorInfo::tensor_shape(), TensorShape::total_size(), arm_compute::utils::cast::U, and arm_compute::experimental::dynamic_fusion::vector_size_byte_opencl.
write_component_code()
void write_component_code (const ComponentGroup & comp_group, GpuCkwVariableTable & vtable, GpuCkwScopedKernelWriter writer) const override virtual
Generate kernel component code.
Parameters
[in] comp_group Component group of which the component is a part of
[in,out] vtable Table of variables declared by each component
[in,out] writer CKW writer that writes code scoped to this kernel component.
                       @note @p writer can only be passed via value since the new scope is created in the copy constructor
Implements IGpuCkwComponentDriver.
Definition at line 99 of file GpuCkwActivation.cpp.
 {
     const auto         root_window = comp_group.get_root_component()->ckw_component_driver()->get_window();
     const unsigned int n0          = root_window.x().step();
     const unsigned int m0          = root_window.y().step();
     GpuCkwComponentArgument *src =
         vtable.declare_variable(comp_group, writer, _src, TensorStorageType::ClBufferUint8Ptr, "src");
     GpuCkwComponentArgument *dst =
         vtable.declare_variable(comp_group, writer, _dst, TensorStorageType::ClBufferUint8Ptr, "dst");
     load_src_dst_tiles_and_prepare_sampler(writer, src, dst, m0, n0, create_sampler);
     auto &src_tile = src->tile();
     auto &dst_tile = dst->tile();
     // Constants
     const auto &constant_minus_1 = writer->declare_tile("minus_1", -1);
     const auto &constant_pos_1   = writer->declare_tile("one", 1);
     const auto &constant_zero    = writer->declare_tile("zero", 0);
     const auto &constant_A       = writer->declare_tile("A_VAL", _attributes.a());
     const auto &constant_B       = writer->declare_tile("B_VAL", _attributes.b());
     // Perform the operation.
     switch (_attributes.activation())
     {
         case ActivationLayerInfo::ActivationFunction::LOGISTIC:
         {
             // dst = src * -1
             writer->op_binary_expression(dst_tile, src_tile, BinaryOp::Mul, constant_minus_1);
             // dst = exp(src * -1)
             writer->op_unary_elementwise_function(dst_tile, UnaryFunction::Exp, dst_tile);
             // dst = 1 + (exp(src * -1))
             writer->op_binary_expression(dst_tile, dst_tile, BinaryOp::Add, constant_pos_1);
             // dst = 1 /  1 + (exp(src * -1))
             writer->op_binary_expression(dst_tile, constant_pos_1, BinaryOp::Div, dst_tile);
             break;
         }
         case ActivationLayerInfo::ActivationFunction::TANH:
         {
             // dst = B_VAL * src
             writer->op_binary_expression(dst_tile, src_tile, BinaryOp::Mul, constant_B);
             // dst = tanh(B_VAL * src)
             writer->op_unary_elementwise_function(dst_tile, UnaryFunction::Tanh, dst_tile);
             // dst = A_VAL * tanh(B_VAL * src)
             writer->op_binary_expression(dst_tile, dst_tile, BinaryOp::Mul, constant_A);
             break;
         }
         case ActivationLayerInfo::ActivationFunction::RELU:
         {
             // dst = max(src, 0)
             writer->op_binary_elementwise_function(dst_tile, ckw::BinaryFunction::Max, src_tile, constant_zero);
             break;
         }
         case ActivationLayerInfo::ActivationFunction::BOUNDED_RELU:
         {
             //dst = max(src, 0)
             writer->op_binary_elementwise_function(dst_tile, ckw::BinaryFunction::Max, src_tile, constant_zero);
             //dst = min(max(src, 0), A_VAL)
             writer->op_binary_elementwise_function(dst_tile, ckw::BinaryFunction::Min, dst_tile, constant_A);
             break;
         }
         case ActivationLayerInfo::ActivationFunction::LU_BOUNDED_RELU:
         {
             //dst = max(src, B_VAL)
             writer->op_binary_elementwise_function(dst_tile, ckw::BinaryFunction::Max, src_tile, constant_B);
             //dst = min(max(src, B_VAL), A_VAL)
             writer->op_binary_elementwise_function(dst_tile, ckw::BinaryFunction::Min, dst_tile, constant_A);
             break;
         }
         default:
             CKW_ASSERT(false);
             break;
     }
 }
References ActivationLayerInfo::a(), ActivationLayerInfo::activation(), ActivationLayerInfo::b(), IGpuKernelComponent::ckw_component_driver(), GpuCkwVariableTable::declare_variable(), arm_compute::test::validation::dst, GpuKernelComponentGroup::get_root_component(), IGpuCkwComponentDriver::get_window(), arm_compute::experimental::dynamic_fusion::load_src_dst_tiles_and_prepare_sampler(), arm_compute::test::validation::src, Window::Dimension::step(), and Window::x().
The documentation for this class was generated from the following files:
src/dynamic_fusion/sketch/gpu/ckw_driver/components/GpuCkwActivation.h
src/dynamic_fusion/sketch/gpu/ckw_driver/components/GpuCkwActivation.cpp