Compute Library: ClDirectConv2dKernel Class Reference
ClDirectConv2dKernel Class Reference
Interface for the direct convolution kernel.
#include <ClDirectConv2dKernel.h>
Public Member Functions
ClDirectConv2dKernel ()
ARM_COMPUTE_DISALLOW_COPY_ALLOW_MOVE (ClDirectConv2dKernel)
void configure (const CLCompileContext &compile_context, ITensorInfo *src, ITensorInfo *weights, ITensorInfo *biases, ITensorInfo *dst, const PadStrideInfo &conv_info, const ActivationLayerInfo &act_info, const DirectConvComputeKernelInfo &desc)
Set the src, weights, biases and dst tensors info.
void run_op (ITensorPack &tensors, const Window &window, cl::CommandQueue &queue) override
Enqueue the OpenCL kernel to process the given window on the passed OpenCL command queue.
Public Member Functions inherited from ICLKernel
ICLKernel ()
Constructor.
cl::Kernel & kernel ()
Returns a reference to the OpenCL kernel of this object.
CLKernelType type () const
Returns the CL kernel type.
template<typename T >
void add_1D_array_argument (unsigned int &idx, const ICLArray< T > *array, const Strides &strides, unsigned int num_dimensions, const Window &window)
Add the passed 1D array's parameters to the object's kernel's arguments starting from the index idx.
void add_1D_tensor_argument (unsigned int &idx, const ICLTensor *tensor, const Window &window)
Add the passed 1D tensor's parameters to the object's kernel's arguments starting from the index idx.
void add_1D_tensor_argument_if (bool cond, unsigned int &idx, const ICLTensor *tensor, const Window &window)
Add the passed 1D tensor's parameters to the object's kernel's arguments starting from the index idx if the condition is true.
void add_2D_tensor_argument (unsigned int &idx, const ICLTensor *tensor, const Window &window)
Add the passed 2D tensor's parameters to the object's kernel's arguments starting from the index idx.
void add_2D_tensor_argument_if (bool cond, unsigned int &idx, const ICLTensor *tensor, const Window &window)
Add the passed 2D tensor's parameters to the object's kernel's arguments starting from the index idx if the condition is true.
void add_3D_tensor_argument (unsigned int &idx, const ICLTensor *tensor, const Window &window)
Add the passed 3D tensor's parameters to the object's kernel's arguments starting from the index idx.
void add_4D_tensor_argument (unsigned int &idx, const ICLTensor *tensor, const Window &window)
Add the passed 4D tensor's parameters to the object's kernel's arguments starting from the index idx.
void add_5D_tensor_argument (unsigned int &idx, const ICLTensor *tensor, const Window &window)
Add the passed 5D tensor's parameters to the object's kernel's arguments starting from the index idx.
void add_3d_tensor_nhw_argument (unsigned int &idx, const ICLTensor *tensor)
Add the passed NHW 3D tensor's parameters to the object's kernel's arguments by passing strides, dimensions and the offset to the first valid element in bytes.
void add_4d_tensor_nhwc_argument (unsigned int &idx, const ICLTensor *tensor)
Add the passed NHWC 4D tensor's parameters to the object's kernel's arguments by passing strides, dimensions and the offset to the first valid element in bytes.
virtual void run (const Window &window, cl::CommandQueue &queue)
Enqueue the OpenCL kernel to process the given window on the passed OpenCL command queue.
template<typename T >
void add_argument (unsigned int &idx, T value)
Add the passed parameters to the object's kernel's arguments starting from the index idx.
void set_lws_hint (const cl::NDRange &lws_hint)
Set the Local-Workgroup-Size hint.
cl::NDRange lws_hint () const
Return the Local-Workgroup-Size hint.
void set_wbsm_hint (const cl_int &wbsm_hint)
Set the workgroup batch size modifier hint.
cl_int wbsm_hint () const
Return the workgroup batch size modifier hint.
const std::string & config_id () const
Get the configuration ID.
void set_target (GPUTarget target)
Set the targeted GPU architecture.
void set_target (cl::Device &device)
Set the targeted GPU architecture according to the CL device.
GPUTarget get_target () const
Get the targeted GPU architecture.
size_t get_max_workgroup_size ()
Get the maximum workgroup size for the device the CLKernelLibrary uses.
cl::NDRange get_cached_gws () const
Get the cached gws used to enqueue this kernel.
void cache_gws (const cl::NDRange &gws)
Cache the latest gws used to enqueue this kernel.
template<unsigned int dimension_size>
void add_tensor_argument (unsigned &idx, const ICLTensor *tensor, const Window &window)
template<typename T , unsigned int dimension_size>
void add_array_argument (unsigned &idx, const ICLArray< T > *array, const Strides &strides, unsigned int num_dimensions, const Window &window)
Add the passed array's parameters to the object's kernel's arguments starting from the index idx.
Public Member Functions inherited from IKernel
IKernel ()
Constructor.
virtual ~IKernel ()=default
Destructor.
virtual bool is_parallelisable () const
Indicates whether or not the kernel is parallelisable.
virtual BorderSize border_size () const
The size of the border for that kernel.
const Window & window () const
The maximum window the kernel can be executed on.
bool is_window_configured () const
Function to check if the embedded window of this kernel has been configured.
Static Public Member Functions
static Status validate (const ITensorInfo *src, const ITensorInfo *weights, const ITensorInfo *biases, const ITensorInfo *dst, const PadStrideInfo &conv_info, const ActivationLayerInfo &act_info, const DirectConvComputeKernelInfo &desc)
Static function to check if given info will lead to a valid configuration.
Static Public Member Functions inherited from ICLKernel
constexpr static unsigned int num_arguments_per_3d_tensor_nhw ()
Returns the number of arguments enqueued per NHW 3D Tensor object.
constexpr static unsigned int num_arguments_per_4d_tensor_nhwc ()
Returns the number of arguments enqueued per NHWC 4D Tensor object.
constexpr static unsigned int num_arguments_per_1D_array ()
Returns the number of arguments enqueued per 1D array object.
constexpr static unsigned int num_arguments_per_1D_tensor ()
Returns the number of arguments enqueued per 1D tensor object.
constexpr static unsigned int num_arguments_per_2D_tensor ()
Returns the number of arguments enqueued per 2D tensor object.
constexpr static unsigned int num_arguments_per_3D_tensor ()
Returns the number of arguments enqueued per 3D tensor object.
constexpr static unsigned int num_arguments_per_4D_tensor ()
Returns the number of arguments enqueued per 4D tensor object.
static cl::NDRange gws_from_window (const Window &window, bool use_dummy_work_items)
Get the global work size given an execution window.
Data Fields
DataLayout _data_layout {}
PadStrideInfo _conv_info {}
bool _export_weights_to_cl_image {false}
bool _export_output_to_cl_image {false}
bool _export_input_to_cl_image {false}
Detailed Description
Interface for the direct convolution kernel.
Definition at line 43 of file ClDirectConv2dKernel.h.
Constructor & Destructor Documentation
ClDirectConv2dKernel()
ClDirectConv2dKernel ()
Definition at line 171 of file ClDirectConv2dKernel.cpp.
 {
     _type = CLKernelType::DIRECT;
 }
References arm_compute::DIRECT.
Member Function Documentation
ARM_COMPUTE_DISALLOW_COPY_ALLOW_MOVE()
ARM_COMPUTE_DISALLOW_COPY_ALLOW_MOVE (ClDirectConv2dKernel)
configure()
void configure (const CLCompileContext & compile_context, ITensorInfo * src, ITensorInfo * weights, ITensorInfo * biases, ITensorInfo * dst, const PadStrideInfo & conv_info, const ActivationLayerInfo & act_info, const DirectConvComputeKernelInfo & desc)
Set the src, weights, biases and dst tensors info.
Note
: Due to set_valid_region() in NCHW, src/weights/biases cannot be const. Need to change this once the set_valid_region() is removed.
: DirectConvolution only works in the following configurations for the NCHW data layout: 1x1 convolution with stride_x = 1/2/3, stride_y = 1/2/3 3x3 convolution with stride_x = 1/2, stride_y = 1/2 5x5 convolution with stride_x = 1/2, stride_y = 1/2 9x9 convolution with stride_x = 1/2, stride_y = 1/2
Parameters
[in] compile_context The compile context to be used.
[in] src The src tensor info to convolve. 3 lower dimensions represent a single src [width, height, IFM], while every optional dimension from 4 and above represent a batch of inputs. Data types supported: QASYMM8_SIGNED/QASYMM8/F16/F32.
[in] weights Weights tensor info. Weights are 4D tensor with dimensions [kernel_x, kernel_y, IFM, OFM]. The 3rd dimension must be the same as the src's volume 3rd dimension. Data type supported:Same as src.
[in] biases Biases tensor info. Biases are 1D tensor with dimension [OFM]. Data type supported: Should match src data type, except for src of QASYMM8 and QASYMM8_SIGNED type where biases should be of S32 type
[out] dst Output tensor info. The 3rd dimensions must be equal to the 4th dimension of the kernels tensor. Data types supported: Same as src.
[in] conv_info Contains padding and stride information described in PadStrideInfo.
[in] act_info Contains activaton information described in ActivationLayerInfo.
[in] desc Direct convolution descriptor used to build the NHWC direct convolution kernel. For NCHW, this parameter is ignored.
Definition at line 176 of file ClDirectConv2dKernel.cpp.
 {
     ARM_COMPUTE_ERROR_ON_NULLPTR(src, weights, dst);
     // Perform validation
     ARM_COMPUTE_ERROR_THROW_ON(validate_arguments(src, weights, biases, dst, conv_info, act_info, desc));
     const int conv_stride_x = std::get<0>(conv_info.stride());
     const int conv_stride_y = std::get<1>(conv_info.stride());
     _data_layout = src->data_layout();
     _conv_info   = conv_info;
     const unsigned int width_idx   = get_data_layout_dimension_index(_data_layout, DataLayoutDimension::WIDTH);
     const unsigned int height_idx  = get_data_layout_dimension_index(_data_layout, DataLayoutDimension::HEIGHT);
     const unsigned int channel_idx = get_data_layout_dimension_index(_data_layout, DataLayoutDimension::CHANNEL);
     const unsigned int kernel_size = weights->dimension(width_idx);
     const DataType     data_type   = src->data_type();
     const GPUTarget gpu_target                         = get_target();
     unsigned int    _num_elems_processed_per_iteration = 0;
     // Get dst shape
     TensorShape output_shape = misc::shape_calculator::compute_deep_convolution_shape(*src, *weights, conv_info);
     // Output auto inizialitation if not yet initialized
     auto_init_if_empty(*dst, output_shape, 1, src->data_type(), src->quantization_info());
     // Configure kernel window
     Window win;
     if (_data_layout == DataLayout::NHWC)
     {
         output_shape.collapse(2U, 1U);
         const unsigned int n0 = adjust_vec_size(desc.n0, output_shape[0]);
         const unsigned int m0 = adjust_vec_size(desc.m0, output_shape[1]);
         // Create window and update padding
         win = calculate_max_window(output_shape, Steps(n0, m0));
     }
     else if (_data_layout == DataLayout::NCHW)
     {
         _num_elems_processed_per_iteration = 1u;
         win                                = calculate_max_window(*dst, Steps(_num_elems_processed_per_iteration));
     }
     ICLKernel::configure_internal(win);
     std::stringstream kernel_name;
     CLBuildOptions    build_options;
     if (_data_layout == DataLayout::NHWC)
     {
         kernel_name << "direct_convolution_nhwc";
         const unsigned int n0               = win.x().step();
         const unsigned int m0               = win.y().step();
         const unsigned int k0               = adjust_vec_size(desc.k0, src->dimension(channel_idx));
         const unsigned int partial_store_n0 = dst->dimension(channel_idx) % n0;
         const unsigned int pad_left         = conv_info.pad_left();
         const unsigned int pad_top          = conv_info.pad_top();
         _export_weights_to_cl_image = desc.export_weights_to_cl_image;
         _export_input_to_cl_image   = desc.export_input_to_cl_image;
         _export_output_to_cl_image  = desc.export_output_to_cl_image;
         // Update the padding for the weights tensor if we can export to cl_image
         if (_export_weights_to_cl_image)
         {
             gemm::update_padding_for_cl_image(weights);
         }
         if (_export_output_to_cl_image)
         {
             gemm::update_padding_for_cl_image(dst);
         }
         if (_export_input_to_cl_image)
         {
             gemm::update_padding_for_cl_image(src);
         }
         if (biases != nullptr)
         {
             build_options.add_option(std::string("-DHAS_BIAS"));
             build_options.add_option(std::string("-DBIA_DATA_TYPE=" + get_cl_type_from_data_type(biases->data_type())));
         }
         // Conditions of -cl-fast-relaxed-math causing accuracy issues can be traced from COMPMID-5324
         const auto act_function  = act_info.activation();
         const auto dst_data_type = dst->data_type();
         if ((gpu_target != GPUTarget::G71 && (gpu_target & GPUTarget::GPU_ARCH_MASK) == GPUTarget::BIFROST) &&
             (act_function == ActivationLayerInfo::ActivationFunction::BOUNDED_RELU ||
              act_function == ActivationLayerInfo::ActivationFunction::LU_BOUNDED_RELU) &&
             (dst_data_type == DataType::F32 || dst_data_type == DataType::F16))
         {
             // -cl-fast-relaxed-math also sets -cl-finite-math-only and -cl-unsafe-math-optimizations
             // to disable -cl-finite-math-only, we only include -cl-unsafe-math-optimizations
             build_options.add_option("-cl-unsafe-math-optimizations");
         }
         else
         {
             build_options.add_option("-cl-fast-relaxed-math");
         }
         build_options.add_option_if_else(_export_input_to_cl_image, "-DSRC_TENSOR_TYPE=IMAGE",
                                          "-DSRC_TENSOR_TYPE=BUFFER");
         build_options.add_option("-DSRC_DATA_TYPE=" + get_cl_type_from_data_type(src->data_type()));
         build_options.add_option("-DSRC_CHANNELS=" + support::cpp11::to_string(src->dimension(0)));
         build_options.add_option("-DSRC_WIDTH=" + support::cpp11::to_string(src->dimension(1)));
         build_options.add_option("-DSRC_HEIGHT=" + support::cpp11::to_string(src->dimension(2)));
         build_options.add_option("-DDST_CHANNELS=" + support::cpp11::to_string(dst->dimension(0)));
         build_options.add_option("-DDST_WIDTH=" + support::cpp11::to_string(dst->dimension(1)));
         build_options.add_option("-DDST_HEIGHT=" + support::cpp11::to_string(dst->dimension(2)));
         build_options.add_option_if_else(_export_output_to_cl_image, "-DDST_TENSOR_TYPE=IMAGE",
                                          "-DDST_TENSOR_TYPE=BUFFER");
         build_options.add_option("-DDST_DATA_TYPE=" + get_cl_type_from_data_type(dst_data_type));
         build_options.add_option_if_else(_export_weights_to_cl_image, "-DWEI_TENSOR_TYPE=IMAGE",
                                          "-DWEI_TENSOR_TYPE=BUFFER");
         build_options.add_option("-DWEI_WIDTH=" + support::cpp11::to_string(weights->dimension(width_idx)));
         build_options.add_option("-DWEI_HEIGHT=" + support::cpp11::to_string(weights->dimension(height_idx)));
         build_options.add_option("-DWEI_DATA_TYPE=" + get_cl_type_from_data_type(weights->data_type()));
         build_options.add_option("-DSTRIDE_X=" + support::cpp11::to_string(conv_stride_x));
         build_options.add_option("-DSTRIDE_Y=" + support::cpp11::to_string(conv_stride_y));
         build_options.add_option("-DPAD_LEFT=" + support::cpp11::to_string(pad_left));
         build_options.add_option("-DPAD_TOP=" + support::cpp11::to_string(pad_top));
         build_options.add_option("-DN0=" + support::cpp11::to_string(n0));
         build_options.add_option("-DM0=" + support::cpp11::to_string(m0));
         build_options.add_option("-DK0=" + support::cpp11::to_string(k0));
         build_options.add_option("-DPARTIAL_N0=" + support::cpp11::to_string(partial_store_n0));
         build_options.add_option_if((src->dimension(channel_idx) % k0) != 0, "-DLEFTOVER_LOOP");
         build_options.add_option("-DACTIVATION_TYPE=" + lower_string(string_from_activation_func(act_function)));
         if (is_data_type_quantized(data_type))
         {
             const UniformQuantizationInfo iqinfo = src->quantization_info().uniform();
             const UniformQuantizationInfo wqinfo = weights->quantization_info().uniform();
             const UniformQuantizationInfo oqinfo = dst->quantization_info().uniform();
             PixelValue zero_value = PixelValue(0, src->data_type(), src->quantization_info());
             int        zero_value_s32;
             zero_value.get(zero_value_s32);
             float multiplier        = iqinfo.scale * wqinfo.scale / oqinfo.scale;
             int   output_multiplier = 0;
             int   output_shift      = 0;
             quantization::calculate_quantized_multiplier(multiplier, &output_multiplier, &output_shift);
             build_options.add_option("-DIS_QUANTIZED");
             build_options.add_option("-DDST_MULTIPLIER=" + support::cpp11::to_string(output_multiplier));
             build_options.add_option("-DDST_SHIFT=" + support::cpp11::to_string(output_shift));
             build_options.add_option("-DSRC_OFFSET=" + support::cpp11::to_string(-iqinfo.offset));
             build_options.add_option("-DWEI_OFFSET=" + support::cpp11::to_string(-wqinfo.offset));
             build_options.add_option("-DDST_OFFSET=" + support::cpp11::to_string(oqinfo.offset));
             build_options.add_option("-DZERO_VALUE=" + support::cpp11::to_string(zero_value_s32));
             build_options.add_option("-DACC_DATA_TYPE=" + get_cl_type_from_data_type(DataType::S32));
         }
         else
         {
             build_options.add_option("-DACC_DATA_TYPE=" + get_cl_type_from_data_type(data_type));
             build_options.add_option("-DZERO_VALUE=" + support::cpp11::to_string(0));
             build_options.add_option("-DSRC_OFFSET=" + support::cpp11::to_string(0));
             build_options.add_option("-DWEI_OFFSET=" + support::cpp11::to_string(0));
             build_options.add_option("-DDST_OFFSET=" + support::cpp11::to_string(0));
             build_options.add_option_if(act_info.enabled(),
                                         "-DA_VAL=" + float_to_string_with_full_precision(act_info.a()));
             build_options.add_option_if(act_info.enabled(),
                                         "-DB_VAL=" + float_to_string_with_full_precision(act_info.b()));
         }
         if (compile_context.get_ddk_version() >= 30)
         {
             build_options.add_option("-fregister-allocation=64");
         }
     }
     else
     {
         _export_weights_to_cl_image = false;
         kernel_name << "direct_convolution_nchw";
         build_options.add_option_if(biases != nullptr, std::string("-DHAS_BIAS"));
         build_options.add_option("-DSRC_WIDTH=" + support::cpp11::to_string(src->dimension(width_idx)));
         build_options.add_option("-DSRC_HEIGHT=" + support::cpp11::to_string(src->dimension(height_idx)));
         build_options.add_option("-DSRC_CHANNELS=" + support::cpp11::to_string(src->dimension(channel_idx)));
         build_options.add_option("-DPAD_LEFT=" + support::cpp11::to_string(conv_info.pad_left()));
         build_options.add_option("-DPAD_TOP=" + support::cpp11::to_string(conv_info.pad_top()));
         build_options.add_option("-DSTRIDE_X=" + support::cpp11::to_string(conv_stride_x));
         build_options.add_option("-DSTRIDE_Y=" + support::cpp11::to_string(conv_stride_y));
         build_options.add_option("-DWEI_WIDTH=" + support::cpp11::to_string(weights->dimension(width_idx)));
         build_options.add_option("-DWEI_HEIGHT=" + support::cpp11::to_string(weights->dimension(height_idx)));
         build_options.add_option(std::string("-DDATA_TYPE=" + get_cl_type_from_data_type(data_type)));
         build_options.add_option(std::string("-DDATA_SIZE=" + get_data_size_from_data_type(data_type)));
         build_options.add_option(
             std::string("-DWEIGHTS_DEPTH=" + support::cpp11::to_string(weights->dimension(channel_idx))));
         build_options.add_option(std::string("-DSTRIDE_X=" + support::cpp11::to_string(conv_stride_x)));
         build_options.add_option(std::string("-DDATA_TYPE_PROMOTED=" + get_cl_type_from_data_type(data_type)));
         build_options.add_option(
             std::string("-DVEC_SIZE=" + support::cpp11::to_string(_num_elems_processed_per_iteration)));
         build_options.add_option(
             std::string("-DVEC_SIZE_LEFTOVER=" +
                         support::cpp11::to_string(src->dimension(0) % _num_elems_processed_per_iteration)));
         if (is_data_type_quantized(data_type))
         {
             const UniformQuantizationInfo iqinfo = src->quantization_info().uniform();
             const UniformQuantizationInfo wqinfo = weights->quantization_info().uniform();
             const UniformQuantizationInfo oqinfo = dst->quantization_info().uniform();
             float multiplier        = iqinfo.scale * wqinfo.scale / oqinfo.scale;
             int   output_multiplier = 0;
             int   output_shift      = 0;
             quantization::calculate_quantized_multiplier(multiplier, &output_multiplier, &output_shift);
             build_options.add_option("-DIS_QUANTIZED");
             build_options.add_option("-DOUTPUT_MULTIPLIER=" + support::cpp11::to_string(output_multiplier));
             build_options.add_option("-DOUTPUT_SHIFT=" + support::cpp11::to_string(output_shift));
             build_options.add_option("-DKERNEL_SIZE=" + support::cpp11::to_string(kernel_size));
             build_options.add_option("-DINPUT_OFFSET=" + support::cpp11::to_string(-iqinfo.offset));
             build_options.add_option("-DWEIGHTS_OFFSET=" + support::cpp11::to_string(-wqinfo.offset));
             build_options.add_option("-DOUTPUT_OFFSET=" + support::cpp11::to_string(oqinfo.offset));
         }
     }
     _kernel = create_kernel(compile_context, kernel_name.str(), build_options.options());
     // Set config_id for enabling LWS tuning
     // config_id should include the variables used to parameterize the kernel
     _config_id = kernel_name.str();
     _config_id += "_";
     _config_id += lower_string(string_from_data_type(data_type));
     _config_id += "_";
     _config_id += support::cpp11::to_string(kernel_size);
     _config_id += "_";
     _config_id += support::cpp11::to_string(border_size().left);
     _config_id += "_";
     _config_id += support::cpp11::to_string(border_size().top);
     _config_id += "_";
     _config_id += support::cpp11::to_string(border_size().right);
     _config_id += "_";
     _config_id += support::cpp11::to_string(border_size().bottom);
     _config_id += "_";
     _config_id += support::cpp11::to_string(conv_stride_x);
     _config_id += "_";
     _config_id += support::cpp11::to_string(conv_stride_y);
     // SRC_CHANNELS, SRC_WIDTH, SRC_HEIGHT
     _config_id += "_";
     _config_id += support::cpp11::to_string(src->dimension(channel_idx));
     _config_id += "_";
     _config_id += support::cpp11::to_string(src->dimension(width_idx));
     _config_id += "_";
     _config_id += support::cpp11::to_string(src->dimension(height_idx));
     _config_id += "_";
     // DST_CHANNELS, DST_WIDTH, DST_HEIGHT
     _config_id += support::cpp11::to_string(dst->dimension(channel_idx));
     _config_id += "_";
     _config_id += support::cpp11::to_string(dst->dimension(width_idx));
     _config_id += "_";
     _config_id += support::cpp11::to_string(dst->dimension(height_idx));
     _config_id += "_";
     _config_id += lower_string(string_from_data_layout(_data_layout));
 }
References ClDirectConv2dKernel::_conv_info, ClDirectConv2dKernel::_data_layout, ClDirectConv2dKernel::_export_input_to_cl_image, ClDirectConv2dKernel::_export_output_to_cl_image, ClDirectConv2dKernel::_export_weights_to_cl_image, arm_compute::test::validation::act_info, arm_compute::adjust_vec_size(), ARM_COMPUTE_ERROR_ON_NULLPTR, ARM_COMPUTE_ERROR_THROW_ON, arm_compute::auto_init_if_empty(), arm_compute::BIFROST, IKernel::border_size(), build_options, arm_compute::calculate_max_window(), arm_compute::quantization::calculate_quantized_multiplier(), arm_compute::CHANNEL, arm_compute::cpu::channel_idx, TensorShape::collapse(), arm_compute::misc::shape_calculator::compute_deep_convolution_shape(), arm_compute::test::validation::conv_info, arm_compute::create_kernel(), arm_compute::test::validation::data_type, ITensorInfo::data_type(), ITensorInfo::dimension(), arm_compute::test::validation::dst, DirectConvComputeKernelInfo::export_input_to_cl_image, DirectConvComputeKernelInfo::export_output_to_cl_image, DirectConvComputeKernelInfo::export_weights_to_cl_image, arm_compute::F16, arm_compute::F32, arm_compute::float_to_string_with_full_precision(), arm_compute::G71, PixelValue::get(), arm_compute::get_cl_type_from_data_type(), arm_compute::get_data_layout_dimension_index(), arm_compute::get_data_size_from_data_type(), CLCompileContext::get_ddk_version(), ICLKernel::get_target(), arm_compute::GPU_ARCH_MASK, arm_compute::HEIGHT, arm_compute::cpu::height_idx, arm_compute::is_data_type_quantized(), DirectConvComputeKernelInfo::k0, kernel_name, arm_compute::lower_string(), DirectConvComputeKernelInfo::m0, DirectConvComputeKernelInfo::n0, arm_compute::NCHW, arm_compute::NHWC, UniformQuantizationInfo::offset, arm_compute::test::validation::output_shape, ITensorInfo::quantization_info(), arm_compute::S32, UniformQuantizationInfo::scale, arm_compute::test::validation::src, Window::Dimension::step(), arm_compute::string_from_activation_func(), arm_compute::string_from_data_layout(), arm_compute::string_from_data_type(), arm_compute::support::cpp11::to_string(), arm_compute::utils::cast::U, QuantizationInfo::uniform(), arm_compute::opencl::kernels::gemm::update_padding_for_cl_image(), arm_compute::cpu::kernels::validate_arguments(), arm_compute::WIDTH, arm_compute::cpu::width_idx, Window::x(), and Window::y().
run_op()
void run_op (ITensorPack & tensors, const Window & window, cl::CommandQueue & queue) override virtual
Enqueue the OpenCL kernel to process the given window on the passed OpenCL command queue.
Note
The queue is not flushed by this method, and therefore the kernel will not have been executed by the time this method returns.
Parameters
[in] tensors A vector containing the tensors to operato on.
[in] window Region on which to execute the kernel. (Must be a valid region of the window returned by window()).
[in,out] queue Command queue on which to enqueue the kernel.
Reimplemented from ICLKernel.
Definition at line 455 of file ClDirectConv2dKernel.cpp.
 {
     ARM_COMPUTE_ERROR_ON_UNCONFIGURED_KERNEL(this);
     ARM_COMPUTE_ERROR_ON_INVALID_SUBWINDOW(IKernel::window(), window);
     // Get initial windows
     Window slice = window.first_slice_window_3D();
     const auto src =
         utils::cast::polymorphic_downcast<const ICLTensor *>(tensors.get_const_tensor(TensorType::ACL_SRC_0));
     const auto weights =
         utils::cast::polymorphic_downcast<const ICLTensor *>(tensors.get_const_tensor(TensorType::ACL_SRC_1));
     const auto biases =
         utils::cast::polymorphic_downcast<const ICLTensor *>(tensors.get_const_tensor(TensorType::ACL_SRC_2));
     auto dst = utils::cast::polymorphic_downcast<ICLTensor *>(tensors.get_tensor(TensorType::ACL_DST));
     if (_data_layout == DataLayout::NHWC)
     {
         cl::Image2D weights_cl_image;
         cl::Image2D output_cl_image;
         cl::Image2D input_cl_image;
         if (_export_weights_to_cl_image)
         {
             // Export tensor to cl_image
             weights_cl_image = create_image2d_from_tensor(weights, CLImage2DType::ReadOnly);
         }
         if (_export_output_to_cl_image)
         {
             // Export tensor to cl_image
             output_cl_image = create_image2d_from_tensor(dst, CLImage2DType::WriteOnly);
         }
         if (_export_input_to_cl_image)
         {
             // Export tensor to cl_image
             input_cl_image = create_image2d_from_tensor(src, CLImage2DType::ReadOnly);
         }
         unsigned int idx = 0;
         if (_export_input_to_cl_image)
         {
             _kernel.setArg(idx++, input_cl_image);
         }
         add_4d_tensor_nhwc_argument(idx, src);
         if (_export_output_to_cl_image)
         {
             _kernel.setArg(idx++, output_cl_image);
         }
         add_4d_tensor_nhwc_argument(idx, dst);
         if (_export_weights_to_cl_image)
         {
             _kernel.setArg(idx++, weights_cl_image);
         }
         add_4d_tensor_nhwc_argument(idx, weights);
         if (biases != nullptr)
         {
             add_1D_tensor_argument(idx, biases, slice);
         }
         enqueue(queue, *this, slice, lws_hint());
     }
     else
     {
         unsigned int idx1 = 2 * num_arguments_per_3D_tensor();
         add_3D_tensor_argument(idx1, weights, slice);
         if (biases != nullptr)
         {
             Window slice_biases;
             slice_biases.use_tensor_dimensions(biases->info()->tensor_shape());
             add_1D_tensor_argument(idx1, biases, slice_biases);
         }
         _kernel.setArg(idx1++, static_cast<unsigned int>(weights->info()->strides_in_bytes()[3]));
         do
         {
             unsigned int idx = 0;
             add_3D_tensor_argument(idx, src, slice);
             add_3D_tensor_argument(idx, dst, slice);
             enqueue(queue, *this, slice, lws_hint());
         } while (window.slide_window_slice_3D(slice));
     }
 }
References ClDirectConv2dKernel::_data_layout, ClDirectConv2dKernel::_export_input_to_cl_image, ClDirectConv2dKernel::_export_output_to_cl_image, ClDirectConv2dKernel::_export_weights_to_cl_image, arm_compute::ACL_DST, arm_compute::ACL_SRC_0, arm_compute::ACL_SRC_1, arm_compute::ACL_SRC_2, ICLKernel::add_1D_tensor_argument(), ICLKernel::add_3D_tensor_argument(), ICLKernel::add_4d_tensor_nhwc_argument(), ARM_COMPUTE_ERROR_ON_INVALID_SUBWINDOW, ARM_COMPUTE_ERROR_ON_UNCONFIGURED_KERNEL, arm_compute::create_image2d_from_tensor(), arm_compute::test::validation::dst, arm_compute::enqueue(), Window::first_slice_window_3D(), ITensorPack::get_const_tensor(), ITensorPack::get_tensor(), ICLKernel::lws_hint(), arm_compute::NHWC, ICLKernel::num_arguments_per_3D_tensor(), arm_compute::ReadOnly, arm_compute::test::validation::reference::slice(), Window::slide_window_slice_3D(), arm_compute::test::validation::src, Window::use_tensor_dimensions(), IKernel::window(), and arm_compute::WriteOnly.
validate()
Status validate (const ITensorInfo * src, const ITensorInfo * weights, const ITensorInfo * biases, const ITensorInfo * dst, const PadStrideInfo & conv_info, const ActivationLayerInfo & act_info, const DirectConvComputeKernelInfo & desc) static
Static function to check if given info will lead to a valid configuration.
Similar to ClDirectConv2dKernel::configure()
Returns
a status
Definition at line 443 of file ClDirectConv2dKernel.cpp.
 {
     ARM_COMPUTE_RETURN_ON_ERROR(validate_arguments(src, weights, biases, dst, conv_info, act_info, desc));
     return Status{};
 }
References arm_compute::test::validation::act_info, ARM_COMPUTE_RETURN_ON_ERROR, arm_compute::test::validation::conv_info, arm_compute::test::validation::dst, arm_compute::test::validation::src, and arm_compute::cpu::kernels::validate_arguments().
Field Documentation
_conv_info
PadStrideInfo _conv_info {}
Definition at line 99 of file ClDirectConv2dKernel.h.
Referenced by ClDirectConv2dKernel::configure().
_data_layout
DataLayout _data_layout {}
Definition at line 98 of file ClDirectConv2dKernel.h.
Referenced by ClDirectConv2dKernel::configure(), and ClDirectConv2dKernel::run_op().
_export_input_to_cl_image
bool _export_input_to_cl_image {false}
Definition at line 102 of file ClDirectConv2dKernel.h.
Referenced by ClDirectConv2dKernel::configure(), and ClDirectConv2dKernel::run_op().
_export_output_to_cl_image
bool _export_output_to_cl_image {false}
Definition at line 101 of file ClDirectConv2dKernel.h.
Referenced by ClDirectConv2dKernel::configure(), and ClDirectConv2dKernel::run_op().
_export_weights_to_cl_image
bool _export_weights_to_cl_image {false}
Definition at line 100 of file ClDirectConv2dKernel.h.
Referenced by ClDirectConv2dKernel::configure(), and ClDirectConv2dKernel::run_op().
The documentation for this class was generated from the following files:
src/gpu/cl/kernels/ClDirectConv2dKernel.h
src/gpu/cl/kernels/ClDirectConv2dKernel.cpp