Compute Library: CpuDepthwiseConv2d Class Reference
CpuDepthwiseConv2d Class Reference
Function to execute a depthwise convolution.
#include <CpuDepthwiseConv2d.h>
Public Member Functions
CpuDepthwiseConv2d ()=default
Default constructor.
void configure (ITensorInfo *src, const ITensorInfo *weights, const ITensorInfo *biases, ITensorInfo *dst, const ConvolutionInfo &info)
Initialize the function's source, destination, weights and convolution information.
void run (ITensorPack &tensors) override
Run the kernels contained in the function.
void prepare (ITensorPack &tensors) override
Prepare the function for executing.
Public Member Functions inherited from INEOperator
INEOperator (IRuntimeContext *ctx=nullptr)
Constructor.
INEOperator (const INEOperator &)=delete
Prevent instances of this class from being copied (As this class contains pointers)
INEOperator (INEOperator &&)=default
Default move constructor.
INEOperator & operator= (const INEOperator &)=delete
Prevent instances of this class from being copied (As this class contains pointers)
INEOperator & operator= (INEOperator &&)=default
Default move assignment operator.
~INEOperator ()
Default destructor.
MemoryRequirements workspace () const override
Return the memory requirements required by the workspace.
Public Member Functions inherited from IOperator
virtual ~IOperator ()=default
Destructor.
Static Public Member Functions
static Status validate (const ITensorInfo *src, const ITensorInfo *weights, const ITensorInfo *biases, const ITensorInfo *dst, const ConvolutionInfo &info)
Static function to check if given info will lead to a valid configuration.
static DepthwiseConvolutionFunction get_depthwiseconvolution_function (const ITensorInfo *src, const ITensorInfo *weights, const ITensorInfo *biases, const ITensorInfo *dst, const ConvolutionInfo &info)
Static function to choose the best depthwise convolution function for CpuDepthwiseConv2d.
Detailed Description
Function to execute a depthwise convolution.
Definition at line 45 of file CpuDepthwiseConv2d.h.
Constructor & Destructor Documentation
CpuDepthwiseConv2d()
CpuDepthwiseConv2d () default
Default constructor.
Member Function Documentation
configure()
void configure (ITensorInfo * src, const ITensorInfo * weights, const ITensorInfo * biases, ITensorInfo * dst, const ConvolutionInfo & info)
Initialize the function's source, destination, weights and convolution information.
Parameters
[in,out] src Source tensor info. Data type supported: QASYMM8/QASYMM8_SIGNED/F16/F32
[out] dst Destination tensor info. Data type supported: same as src.
[in] weights Weights tensor info. These are 3D tensor infos with shape [kernel_x, kernel_y, IFM]. Data type supported: Same as src or QASYMM8/QASYMM8_SIGNED/QSYMM8_PER_CHANNEL when src is QASYMM8/QASYMM8_SIGNED.
[in] biases Biases tensor info. A 1D tensor with shape [IFM]. Must be nullptr if not needed. Data type supported: Same as src, S32 when src is QASYMM8/QASYMM8_SIGNED.
[in] info Depthwise convolution meta-data.
Definition at line 479 of file CpuDepthwiseConv2d.cpp.
 {
     ARM_COMPUTE_LOG_PARAMS(src, weights, biases, dst, info);
     _depth_conv_func =
         get_depthwiseconvolution_function(src, weights, (biases != nullptr) ? biases : nullptr, dst, info);
     switch (_depth_conv_func)
     {
         case DepthwiseConvolutionFunction::OPTIMIZED:
             _func_optimized.configure(src, weights, biases, dst, info);
             break;
         case DepthwiseConvolutionFunction::GENERIC:
             _func_generic.configure(src, weights, biases, dst, info);
             break;
         default:
             ARM_COMPUTE_ERROR("Unsupported DepthwiseConvolutionFunction");
     }
 }
References ARM_COMPUTE_ERROR, ARM_COMPUTE_LOG_PARAMS, arm_compute::test::validation::dst, arm_compute::GENERIC, CpuDepthwiseConv2d::get_depthwiseconvolution_function(), arm_compute::test::validation::info, arm_compute::OPTIMIZED, and arm_compute::test::validation::src.
get_depthwiseconvolution_function()
DepthwiseConvolutionFunction get_depthwiseconvolution_function (const ITensorInfo * src, const ITensorInfo * weights, const ITensorInfo * biases, const ITensorInfo * dst, const ConvolutionInfo & info) static
Static function to choose the best depthwise convolution function for CpuDepthwiseConv2d.
Parameters
[in] src Source tensor info. Data type supported: QASYMM8/QASYMM8_SIGNED/F16/F32
[in] weights Weights tensor info. These are 3D tensors with shape [kernel_x, kernel_y, IFM]. Data type supported: Same as src or QASYMM8/QASYMM8_SIGNED/QSYMM8_PER_CHANNEL when src is QASYMM8/QASYMM8_SIGNED.
[in] biases Biases tensor info. A 1D tensor with shape [IFM]. Must be nullptr if not needed. Data type supported: Same as src, S32 when src is QASYMM8/QASYMM8_SIGNED.
[in] dst Destination tensor. Data type supported: same as src.
[in] info Depthwise convolution meta-data.
Returns
a Depthwise Convolution Function
Definition at line 522 of file CpuDepthwiseConv2d.cpp.
 {
     if (bool(CpuDepthwiseConv2dOptimizedInternal::validate(src, weights, biases, dst, info)))
     {
         return DepthwiseConvolutionFunction::OPTIMIZED;
     }
     else
     {
         return DepthwiseConvolutionFunction::GENERIC;
     }
 }
References arm_compute::test::validation::dst, arm_compute::GENERIC, arm_compute::test::validation::info, arm_compute::OPTIMIZED, arm_compute::test::validation::src, and arm_compute::validate().
Referenced by CpuDepthwiseConv2d::configure(), and CpuDepthwiseConv2d::validate().
prepare()
void prepare (ITensorPack & constants) override virtual
Prepare the function for executing.
Any one off pre-processing step required by the function is handled here
Parameters
[in] constants Vector that contains the constants tensors.
Note
Prepare stage might not need all the function's buffers' backing memory to be available in order to execute
Reimplemented from INEOperator.
Definition at line 553 of file CpuDepthwiseConv2d.cpp.
 {
     switch (_depth_conv_func)
     {
         case DepthwiseConvolutionFunction::OPTIMIZED:
             _func_optimized.prepare(tensors);
             break;
         case DepthwiseConvolutionFunction::GENERIC:
             _func_generic.prepare(tensors);
             break;
         default:
             ARM_COMPUTE_ERROR("DepthwiseConvolutionFunction not properly configured");
     }
 }
References ARM_COMPUTE_ERROR, arm_compute::GENERIC, and arm_compute::OPTIMIZED.
run()
void run (ITensorPack & tensors) override virtual
Run the kernels contained in the function.
Parameters
[in] tensors Vector that contains the tensors to operate on.
Reimplemented from INEOperator.
Definition at line 538 of file CpuDepthwiseConv2d.cpp.
 {
     switch (_depth_conv_func)
     {
         case DepthwiseConvolutionFunction::OPTIMIZED:
             _func_optimized.run(tensors);
             break;
         case DepthwiseConvolutionFunction::GENERIC:
             _func_generic.run(tensors);
             break;
         default:
             ARM_COMPUTE_ERROR("DepthwiseConvolutionFunction not properly configured");
     }
 }
References ARM_COMPUTE_ERROR, arm_compute::GENERIC, and arm_compute::OPTIMIZED.
validate()
Status validate (const ITensorInfo * src, const ITensorInfo * weights, const ITensorInfo * biases, const ITensorInfo * dst, const ConvolutionInfo & info) static
Static function to check if given info will lead to a valid configuration.
Similar to CpuDepthwiseConv2d::configure()
Returns
a status
Definition at line 502 of file CpuDepthwiseConv2d.cpp.
 {
     DepthwiseConvolutionFunction depth_conv_func = get_depthwiseconvolution_function(src, weights, biases, dst, info);
     switch (depth_conv_func)
     {
         case DepthwiseConvolutionFunction::OPTIMIZED:
             return CpuDepthwiseConv2dOptimizedInternal::validate(src, weights, biases, dst, info);
             break;
         case DepthwiseConvolutionFunction::GENERIC:
             return CpuDepthwiseConv2dGeneric::validate(src, weights, biases, dst, info);
             break;
         default:
             ARM_COMPUTE_ERROR("Unsupported DepthwiseConvolutionFunction");
     }
 }
References ARM_COMPUTE_ERROR, arm_compute::test::validation::dst, arm_compute::GENERIC, CpuDepthwiseConv2d::get_depthwiseconvolution_function(), arm_compute::test::validation::info, arm_compute::OPTIMIZED, arm_compute::test::validation::src, and arm_compute::validate().
Referenced by NEDepthwiseConvolutionLayer::validate().
The documentation for this class was generated from the following files:
src/cpu/operators/CpuDepthwiseConv2d.h
src/cpu/operators/CpuDepthwiseConv2d.cpp