Compute Library: ArgumentPack< T > Class Template Reference
ArgumentPack< T > Class Template Reference
This is a generic class that packs the arguments of an operator.
#include <ArgumentPack.h>
Data Structures
struct PackElement
A single argument element within the pack It contains either a const pointer or a non-const pointer to the Tensor-related type T, but never at the same time.
Public Types
using Id = TensorType
arm_compute::TensorType encodes the position of a tensor argument within the pack
Public Member Functions
ArgumentPack ()=default
Default constructor.
~ArgumentPack ()=default
Destructor.
ArgumentPack (const ArgumentPack< T > &other)=default
Allow instances of this class to be copy constructed.
ArgumentPack< T > & operator= (const ArgumentPack< T > &other)=default
Allow instances of this class to be copied.
ArgumentPack (ArgumentPack< T > &&other)=default
Allow instances of this class to be move constructed.
ArgumentPack< T > & operator= (ArgumentPack< T > &&other)=default
Allow instances of this class to be moved.
ArgumentPack (const std::initializer_list< PackElement > &l)
Initializer list Constructor.
void add_tensor (Id id, T *tensor)
Add tensor to the pack.
void add_const_tensor (Id id, const T *tensor)
Add const tensor to the pack.
T * get_tensor (Id id)
Get tensor of a given id from the pack.
const T * get_const_tensor (Id id) const
Get constant tensor of a given id.
void remove_tensor (Id id)
Remove the tensor stored with the given id.
size_t size () const
Pack size accessor.
bool empty () const
Checks if pack is empty.
std::vector< T * > get_src_tensors ()
Get the ACL_SRC_* tensors.
std::vector< const T * > get_const_src_tensors () const
Get the const ACL_SRC_* tensors.
std::vector< T * > get_dst_tensors ()
Get the ACL_DST_* tensors.
std::vector< const T * > get_const_dst_tensors () const
Get the const ACL_DST_* tensors.
Detailed Description
template<typename T>
class arm_compute::experimental::dynamic_fusion::ArgumentPack< T >
This is a generic class that packs the arguments of an operator.
Forward declaration.
For now, it is only used for tensor-related types Examples of "tensor-related types": ITensorInfo, ITensor, ICLTensor
The argument id is the position of the argument within the pack, and is represented by TensorType
Template Parameters
T Tensor-related type
Definition at line 46 of file ArgumentPack.h.
Member Typedef Documentation
Id
using Id = TensorType
arm_compute::TensorType encodes the position of a tensor argument within the pack
Definition at line 50 of file ArgumentPack.h.
Constructor & Destructor Documentation
ArgumentPack() [1/4]
ArgumentPack () default
Default constructor.
~ArgumentPack()
~ArgumentPack () default
Destructor.
ArgumentPack() [2/4]
ArgumentPack (const ArgumentPack< T > & other) default
Allow instances of this class to be copy constructed.
ArgumentPack() [3/4]
ArgumentPack (ArgumentPack< T > && other) default
Allow instances of this class to be move constructed.
ArgumentPack() [4/4]
ArgumentPack (const std::initializer_list< PackElement > & l) inline
Initializer list Constructor.
Definition at line 87 of file ArgumentPack.h.
                                                             : _pack{}
     {
         for (const auto &e : l)
         {
             _pack[e.id] = e;
         }
     }
Member Function Documentation
add_const_tensor()
void add_const_tensor (Id id, const T * tensor) inline
Add const tensor to the pack.
Parameters
[in] id ID of the tensor to add
[in] tensor Tensor to add
Definition at line 108 of file ArgumentPack.h.
     {
         _pack[id] = PackElement(id, tensor);
     }
Referenced by GpuOutput::create_op(), GpuSigmoid::create_op(), GpuTanh::create_op(), GpuClamp::create_op(), GpuSoftmax::create_op(), GpuReshape::create_op(), GpuDepthwiseConv2d::create_op(), GpuConv2d::create_op(), GpuResize::create_op(), GpuCast::create_op(), GpuElementwiseBinaryCommon::create_op(), GpuPool2d::create_op(), GpuSoftmax::is_supported_op(), GpuPool2d::is_supported_op(), GpuOutput::validate_op(), GpuSigmoid::validate_op(), GpuTanh::validate_op(), GpuReshape::validate_op(), GpuSoftmax::validate_op(), GpuClamp::validate_op(), GpuResize::validate_op(), GpuCast::validate_op(), GpuConv2d::validate_op(), GpuDepthwiseConv2d::validate_op(), GpuPool2d::validate_op(), and GpuElementwiseBinaryCommon::validate_op().
add_tensor()
void add_tensor (Id id, T * tensor) inline
Add tensor to the pack.
Parameters
[in] id ID of the tensor to add
[in] tensor Tensor to add
Definition at line 99 of file ArgumentPack.h.
     {
         _pack[id] = PackElement(id, tensor);
     }
Referenced by GpuReshape::create_op(), GpuElementwiseBinaryCommon::create_op(), and GpuPool2d::create_op().
empty()
bool empty () const inline
Checks if pack is empty.
Returns
True if empty else false
Definition at line 158 of file ArgumentPack.h.
     {
         return _pack.empty();
     }
get_const_dst_tensors()
std::vector<const T *> get_const_dst_tensors () const inline
Get the const ACL_DST_* tensors.
Returns
std::vector<const T *>
Definition at line 217 of file ArgumentPack.h.
     {
         std::vector<const T *> dst_tensors{};
         for (int id = static_cast<int>(TensorType::ACL_DST); id <= static_cast<int>(TensorType::ACL_DST_END); ++id)
         {
             auto tensor = get_const_tensor(static_cast<TensorType>(id));
             if (tensor != nullptr)
             {
                 dst_tensors.push_back(tensor);
             }
         }
         return dst_tensors;
     }
Referenced by GpuKernelComponentGraph::add_new_component().
get_const_src_tensors()
std::vector<const T *> get_const_src_tensors () const inline
Get the const ACL_SRC_* tensors.
Returns
std::vector<const T *>
Definition at line 183 of file ArgumentPack.h.
     {
         std::vector<const T *> src_tensors{};
         for (int id = static_cast<int>(TensorType::ACL_SRC); id <= static_cast<int>(TensorType::ACL_SRC_END); ++id)
         {
             auto tensor = get_const_tensor(static_cast<TensorType>(id));
             if (tensor != nullptr)
             {
                 src_tensors.push_back(tensor);
             }
         }
         return src_tensors;
     }
Referenced by GpuKernelComponentGraph::add_new_component().
get_const_tensor()
const T* get_const_tensor (Id id) const inline
Get constant tensor of a given id.
Parameters
[in] id ID of tensor to extract
Returns
The pointer to the tensor (const or not) if exist else nullptr
Definition at line 129 of file ArgumentPack.h.
     {
         auto it = _pack.find(id);
         if (it != _pack.end())
         {
             return it->second.ctensor != nullptr ? it->second.ctensor : it->second.tensor;
         }
         return nullptr;
     }
Referenced by ArgumentPack< arm_compute::ITensorInfo >::get_const_dst_tensors(), and ArgumentPack< arm_compute::ITensorInfo >::get_const_src_tensors().
get_dst_tensors()
std::vector<T *> get_dst_tensors () inline
Get the ACL_DST_* tensors.
Returns
std::vector<T *>
Definition at line 200 of file ArgumentPack.h.
     {
         std::vector<T *> dst_tensors{};
         for (int id = static_cast<int>(TensorType::ACL_DST); id <= static_cast<int>(TensorType::ACL_DST_END); ++id)
         {
             auto tensor = get_tensor(static_cast<TensorType>(id));
             if (tensor != nullptr)
             {
                 dst_tensors.push_back(tensor);
             }
         }
         return dst_tensors;
     }
get_src_tensors()
std::vector<T *> get_src_tensors () inline
Get the ACL_SRC_* tensors.
Returns
std::vector<T *>
Definition at line 166 of file ArgumentPack.h.
     {
         std::vector<T *> src_tensors{};
         for (int id = static_cast<int>(TensorType::ACL_SRC); id <= static_cast<int>(TensorType::ACL_SRC_END); ++id)
         {
             auto tensor = get_tensor(static_cast<TensorType>(id));
             if (tensor != nullptr)
             {
                 src_tensors.push_back(tensor);
             }
         }
         return src_tensors;
     }
get_tensor()
T* get_tensor (Id id) inline
Get tensor of a given id from the pack.
Parameters
[in] id ID of tensor to extract
Returns
The pointer to the tensor if exist and is non-const else nullptr
Definition at line 118 of file ArgumentPack.h.
     {
         auto it = _pack.find(id);
         return it != _pack.end() ? it->second.tensor : nullptr;
     }
Referenced by ArgumentPack< arm_compute::ITensorInfo >::get_dst_tensors(), and ArgumentPack< arm_compute::ITensorInfo >::get_src_tensors().
operator=() [1/2]
ArgumentPack<T>& operator= (ArgumentPack< T > && other) default
Allow instances of this class to be moved.
operator=() [2/2]
ArgumentPack<T>& operator= (const ArgumentPack< T > & other) default
Allow instances of this class to be copied.
remove_tensor()
void remove_tensor (Id id) inline
Remove the tensor stored with the given id.
Parameters
[in] id ID of tensor to remove
Definition at line 142 of file ArgumentPack.h.
     {
         _pack.erase(id);
     }
size()
size_t size () const inline
Pack size accessor.
Returns
Number of tensors registered to the pack
Definition at line 150 of file ArgumentPack.h.
     {
         return _pack.size();
     }
The documentation for this class was generated from the following file:
src/dynamic_fusion/sketch/ArgumentPack.h