Compute Library: CpuConcatenateDepthKernel Class Reference
CpuConcatenateDepthKernel Class Reference
Interface for the depth concatenate kernel.
#include <CpuConcatenateDepthKernel.h>
Public Member Functions
CpuConcatenateDepthKernel ()=default
ARM_COMPUTE_DISALLOW_COPY_ALLOW_MOVE (CpuConcatenateDepthKernel)
void configure (const ITensorInfo *src, unsigned int depth_offset, ITensorInfo *dst)
Configure kernel for a given list of arguments.
void run_op (ITensorPack &tensors, const Window &window, const ThreadInfo &info) override
Execute the kernel on the passed window.
const char * name () const override
Name of the kernel.
Public Member Functions inherited from ICPPKernel
virtual ~ICPPKernel ()=default
Default destructor.
virtual void run (const Window &window, const ThreadInfo &info)
Execute the kernel on the passed window.
virtual void run_nd (const Window &window, const ThreadInfo &info, const Window &thread_locator)
legacy compatibility layer for implemantions which do not support thread_locator In these cases we simply narrow the interface down the legacy version
virtual size_t get_mws (const CPUInfo &platform, size_t thread_count) const
Return minimum workload size of the relevant kernel.
Public Member Functions inherited from IKernel
IKernel ()
Constructor.
virtual ~IKernel ()=default
Destructor.
virtual bool is_parallelisable () const
Indicates whether or not the kernel is parallelisable.
virtual BorderSize border_size () const
The size of the border for that kernel.
const Window & window () const
The maximum window the kernel can be executed on.
bool is_window_configured () const
Function to check if the embedded window of this kernel has been configured.
Static Public Member Functions
static Status validate (const ITensorInfo *src, unsigned int depth_offset, const ITensorInfo *dst)
Static function to check if given info will lead to a valid configuration.
Static Public Member Functions inherited from ICpuKernel< CpuConcatenateDepthKernel >
static const auto * get_implementation (const SelectorType &selector, KernelSelectionType selection_type=KernelSelectionType::Supported)
Micro-kernel selector.
Additional Inherited Members
Static Public Attributes inherited from ICPPKernel
static constexpr size_t default_mws = 1
Detailed Description
Interface for the depth concatenate kernel.
The input tensor will be concatenated into the output tensor.
Definition at line 43 of file CpuConcatenateDepthKernel.h.
Constructor & Destructor Documentation
CpuConcatenateDepthKernel()
CpuConcatenateDepthKernel () default
Member Function Documentation
ARM_COMPUTE_DISALLOW_COPY_ALLOW_MOVE()
ARM_COMPUTE_DISALLOW_COPY_ALLOW_MOVE (CpuConcatenateDepthKernel)
configure()
void configure (const ITensorInfo * src, unsigned int depth_offset, ITensorInfo * dst)
Configure kernel for a given list of arguments.
Parameters
[in] src Source tensor info. Data types supported: QASYMM8/QASYMM8_SIGNED/F16/F32.
[in] depth_offset The offset on the Z axis.
[in,out] dst Destination tensor info. Data types supported: Same as src.
Note
: The output tensor's low two dimensions can't be smaller than the input one's.
: The gaps between the two lowest dimensions of input and output need to be divisible by 2.
Definition at line 161 of file CpuConcatenateDepthKernel.cpp.
 {
     ARM_COMPUTE_ERROR_ON_NULLPTR(src, dst);
     ARM_COMPUTE_ERROR_THROW_ON(validate_arguments(src, depth_offset, dst));
     _func         = nullptr;
     _depth_offset = depth_offset;
     switch (src->data_type())
     {
         case DataType::QASYMM8:
             _func = &depth_concat<uint8_t>;
             break;
         case DataType::QASYMM8_SIGNED:
             _func = &depth_concat<int8_t>;
             break;
         case DataType::F16:
             _func = &depth_concat<uint16_t>;
             break;
         case DataType::F32:
             _func = &depth_concat<uint32_t>;
             break;
         default:
             ARM_COMPUTE_ERROR("Unsupported data type.");
     }
     // Configure kernel window
     Window win = calculate_max_window(*dst, Steps());
     ICpuKernel::configure(win);
 }
References ARM_COMPUTE_ERROR, ARM_COMPUTE_ERROR_ON_NULLPTR, ARM_COMPUTE_ERROR_THROW_ON, arm_compute::calculate_max_window(), arm_compute::test::validation::dst, arm_compute::F16, arm_compute::F32, arm_compute::QASYMM8, arm_compute::QASYMM8_SIGNED, arm_compute::test::validation::src, and arm_compute::cpu::kernels::validate_arguments().
name()
const char * name () const override virtual
Name of the kernel.
Returns
Kernel name
Implements ICPPKernel.
Definition at line 211 of file CpuConcatenateDepthKernel.cpp.
 {
     return "CpuConcatenateDepthKernel";
 }
run_op()
void run_op (ITensorPack & tensors, const Window & window, const ThreadInfo & info) override virtual
Execute the kernel on the passed window.
Warning
If is_parallelisable() returns false then the passed window must be equal to window()
Note
The window has to be a region within the window returned by the window() method
The width of the window has to be a multiple of num_elems_processed_per_iteration().
Parameters
[in] tensors A vector containing the tensors to operate on.
[in] window Region on which to execute the kernel. (Must be a region of the window returned by window())
[in] info Info about executing thread and CPU.
Reimplemented from ICPPKernel.
Definition at line 200 of file CpuConcatenateDepthKernel.cpp.
 {
     ARM_COMPUTE_UNUSED(info);
     ARM_COMPUTE_ERROR_ON_UNCONFIGURED_KERNEL(this);
     ARM_COMPUTE_ERROR_ON_INVALID_SUBWINDOW(ICpuKernel::window(), window);
     ARM_COMPUTE_ERROR_ON(_func == nullptr);
     (*_func)(tensors.get_const_tensor(TensorType::ACL_SRC), tensors.get_tensor(TensorType::ACL_DST), _depth_offset,
              window);
 }
References arm_compute::ACL_DST, arm_compute::ACL_SRC, ARM_COMPUTE_ERROR_ON, ARM_COMPUTE_ERROR_ON_INVALID_SUBWINDOW, ARM_COMPUTE_ERROR_ON_UNCONFIGURED_KERNEL, ARM_COMPUTE_UNUSED, ITensorPack::get_const_tensor(), ITensorPack::get_tensor(), arm_compute::test::validation::info, and IKernel::window().
validate()
Status validate (const ITensorInfo * src, unsigned int depth_offset, const ITensorInfo * dst) static
Static function to check if given info will lead to a valid configuration.
Similar to CpuConcatenateDepthKernel::configure()
Returns
a status
Definition at line 192 of file CpuConcatenateDepthKernel.cpp.
 {
     ARM_COMPUTE_RETURN_ON_ERROR(validate_arguments(src, depth_offset, dst));
     return Status{};
 }
References ARM_COMPUTE_RETURN_ON_ERROR, arm_compute::test::validation::dst, arm_compute::test::validation::src, and arm_compute::cpu::kernels::validate_arguments().
Referenced by CpuConcatenate::validate().
The documentation for this class was generated from the following files:
src/cpu/kernels/CpuConcatenateDepthKernel.h
src/cpu/kernels/CpuConcatenateDepthKernel.cpp