Compute Library: IDepthfirstStrategy Class Reference
IDepthfirstStrategy Class Reference abstract
#include <depthfirst_driver.hpp>
Public Member Functions
virtual ~IDepthfirstStrategy ()=default
virtual unsigned int get_input_rows () const =0
virtual unsigned int get_input_cols () const =0
virtual unsigned int get_output_rows () const =0
virtual unsigned int get_output_cols () const =0
Detailed Description
Definition at line 41 of file depthfirst_driver.hpp.
Constructor & Destructor Documentation
~IDepthfirstStrategy()
virtual ~IDepthfirstStrategy () virtual default
Member Function Documentation
get_input_cols()
virtual unsigned int get_input_cols () const pure virtual
Implemented in DepthfirstStrategyUntyped.
get_input_rows()
virtual unsigned int get_input_rows () const pure virtual
Implemented in DepthfirstStrategyUntyped.
get_output_cols()
virtual unsigned int get_output_cols () const pure virtual
Implemented in DepthwiseDepthfirstStrategyCommon< TInput, TWeight, TOutput, TAccum, OutputStage >.
Referenced by DepthfirstStrategyUntyped::get_input_cols(), and DepthfirstStrategyUntyped::get_n_output_points().
get_output_rows()
virtual unsigned int get_output_rows () const pure virtual
Implemented in DepthwiseDepthfirstStrategyCommon< TInput, TWeight, TOutput, TAccum, OutputStage >.
Referenced by DepthfirstStrategyUntyped::get_input_rows(), and DepthfirstStrategyUntyped::get_n_output_points().
The documentation for this class was generated from the following file:
src/core/NEON/kernels/arm_conv/depthwise/depthfirst_driver.hpp