Compute Library: ClMatMulNativeDefaultVariantValhall Class Reference
ClMatMulNativeDefaultVariantValhall Class Reference final
Valhall based OpenCL matmul configuration.
#include <ClMatMulNativeDefaultVariantValhall.h>
Public Member Functions
ClMatMulNativeDefaultVariantValhall (GPUTarget gpu)
Constructor.
MatMulKernelType select_kernel (const ITensorInfo *lhs, const ITensorInfo *rhs, const MatMulInfo &info, const ActivationLayerInfo &act_info) override
This method returns the MatMulKernelType for the given inputs.
Public Member Functions inherited from IClMatMulNativeKernelVariant
IClMatMulNativeKernelVariant (GPUTarget arch)
Constructor.
ARM_COMPUTE_DISALLOW_COPY_ALLOW_MOVE (IClMatMulNativeKernelVariant)
virtual ~IClMatMulNativeKernelVariant ()=default
Virtual destructor.
Detailed Description
Valhall based OpenCL matmul configuration.
Definition at line 34 of file ClMatMulNativeDefaultVariantValhall.h.
Constructor & Destructor Documentation
ClMatMulNativeDefaultVariantValhall()
ClMatMulNativeDefaultVariantValhall (GPUTarget gpu)
Constructor.
Parameters
[in] gpu GPU target
Definition at line 34 of file ClMatMulNativeDefaultVariantValhall.cpp.
     : IClMatMulNativeKernelVariant(gpu)
 {
 }
Member Function Documentation
select_kernel()
MatMulKernelType select_kernel (const ITensorInfo * lhs, const ITensorInfo * rhs, const MatMulInfo & info, const ActivationLayerInfo & act_info) override virtual
This method returns the MatMulKernelType for the given inputs.
Parameters
[in] lhs LHS tensor
[in] rhs RHS tensor
[in] info MatMul info
[in] act_info Activation layer info
Implements IClMatMulNativeKernelVariant.
Definition at line 39 of file ClMatMulNativeDefaultVariantValhall.cpp.
 {
     ARM_COMPUTE_UNUSED(rhs);
     using VariantFunctionExecutorPtr =
         MatMulKernelType (ClMatMulNativeDefaultVariantValhall::*)(int k, bool act_enabled);
     ClMatMulNativeVariantArray<VariantFunctionExecutorPtr> configs_G715(
         &ClMatMulNativeDefaultVariantValhall::configure_G715_float,
         &ClMatMulNativeDefaultVariantValhall::configure_G715_quantized);
     ClMatMulNativeVariantArray<VariantFunctionExecutorPtr> configs_default(
         &ClMatMulNativeDefaultVariantValhall::configure_default_float,
         &ClMatMulNativeDefaultVariantValhall::configure_default_quantized);
     VariantFunctionExecutorPtr func = nullptr;
     switch (_target)
     {
         case GPUTarget::G715:
         case GPUTarget::G615:
             func = configs_G715.get_function(lhs->data_type());
             break;
         default:
             func = configs_default.get_function(lhs->data_type());
             break;
     }
     const int  k           = info.adj_lhs() ? lhs->tensor_shape().y() : lhs->tensor_shape().x();
     const bool act_enabled = act_info.enabled();
     ARM_COMPUTE_ERROR_ON_MSG(func == nullptr, "Data type not supported for matmul native");
     return (this->*func)(k, act_enabled);
 }
References arm_compute::test::validation::act_info, ARM_COMPUTE_ERROR_ON_MSG, ARM_COMPUTE_UNUSED, ITensorInfo::data_type(), arm_compute::G615, arm_compute::G715, ClMatMulNativeVariantArray< T >::get_function(), arm_compute::test::validation::info, ITensorInfo::tensor_shape(), Dimensions< T >::x(), and Dimensions< T >::y().
The documentation for this class was generated from the following files:
src/runtime/heuristics/matmul_native/ClMatMulNativeDefaultVariantValhall.h
src/runtime/heuristics/matmul_native/ClMatMulNativeDefaultVariantValhall.cpp