Compute Library: ReshapedGEMMConfig Class Reference
ReshapedGEMMConfig Class Reference
Public Member Functions
def parse_from_strs (cls, *args)
def __str__ (self)
Detailed Description
Definition at line 103 of file GemmTuner.py.
Member Function Documentation
__str__()
def __str__ (self)
Definition at line 129 of file GemmTuner.py.
     def __str__(self):
         return ",".join(map(str, self))
 # Measurement we take from the benchmark result.
References arm_compute.join(), and arm_compute::utils.map().
parse_from_strs()
def parse_from_strs (cls, * args)
Definition at line 121 of file GemmTuner.py.
     def parse_from_strs(cls, *args):
         (*mnkvh, interleave_lhs, interleave_rhs, transpose_rhs, export_to_cl_image_rhs,) = map(int, args)
         interleave_lhs = interleave_lhs == 1
         interleave_rhs = interleave_rhs == 1
         transpose_rhs = transpose_rhs == 1
         export_to_cl_image_rhs = export_to_cl_image_rhs == 1
         return cls(*mnkvh, interleave_lhs, interleave_rhs, transpose_rhs, export_to_cl_image_rhs)
References arm_compute::utils.map().
The documentation for this class was generated from the following file:
examples/gemm_tuner/GemmTuner.py