Compute Library: CLBatchNormalizationLayerKernel Class Reference
CLBatchNormalizationLayerKernel Class Reference
Interface for the BatchNormalization layer kernel.
#include <CLBatchNormalizationLayerKernel.h>
Public Member Functions
CLBatchNormalizationLayerKernel ()
Constructor.
CLBatchNormalizationLayerKernel (const CLBatchNormalizationLayerKernel &)=delete
Prevent instances of this class from being copied (As this class contains pointers)
CLBatchNormalizationLayerKernel & operator= (const CLBatchNormalizationLayerKernel &)=delete
Prevent instances of this class from being copied (As this class contains pointers)
CLBatchNormalizationLayerKernel (CLBatchNormalizationLayerKernel &&)=default
Default Move Constructor.
CLBatchNormalizationLayerKernel & operator= (CLBatchNormalizationLayerKernel &&)=default
Default move assignment operator.
~CLBatchNormalizationLayerKernel ()=default
Default destructor.
void configure (ICLTensor *input, ICLTensor *output, const ICLTensor *mean, const ICLTensor *var, const ICLTensor *beta=nullptr, const ICLTensor *gamma=nullptr, float epsilon=0.001f, ActivationLayerInfo act_info=ActivationLayerInfo())
Set the input and output tensors.
void configure (const CLCompileContext &compile_context, ICLTensor *input, ICLTensor *output, const ICLTensor *mean, const ICLTensor *var, const ICLTensor *beta=nullptr, const ICLTensor *gamma=nullptr, float epsilon=0.001f, ActivationLayerInfo act_info=ActivationLayerInfo())
Set the input and output tensors.
void run (const Window &window, cl::CommandQueue &queue) override
Enqueue the OpenCL kernel to process the given window on the passed OpenCL command queue.
Public Member Functions inherited from ICLKernel
ICLKernel ()
Constructor.
cl::Kernel & kernel ()
Returns a reference to the OpenCL kernel of this object.
CLKernelType type () const
Returns the CL kernel type.
template<typename T >
void add_1D_array_argument (unsigned int &idx, const ICLArray< T > *array, const Strides &strides, unsigned int num_dimensions, const Window &window)
Add the passed 1D array's parameters to the object's kernel's arguments starting from the index idx.
void add_1D_tensor_argument (unsigned int &idx, const ICLTensor *tensor, const Window &window)
Add the passed 1D tensor's parameters to the object's kernel's arguments starting from the index idx.
void add_1D_tensor_argument_if (bool cond, unsigned int &idx, const ICLTensor *tensor, const Window &window)
Add the passed 1D tensor's parameters to the object's kernel's arguments starting from the index idx if the condition is true.
void add_2D_tensor_argument (unsigned int &idx, const ICLTensor *tensor, const Window &window)
Add the passed 2D tensor's parameters to the object's kernel's arguments starting from the index idx.
void add_2D_tensor_argument_if (bool cond, unsigned int &idx, const ICLTensor *tensor, const Window &window)
Add the passed 2D tensor's parameters to the object's kernel's arguments starting from the index idx if the condition is true.
void add_3D_tensor_argument (unsigned int &idx, const ICLTensor *tensor, const Window &window)
Add the passed 3D tensor's parameters to the object's kernel's arguments starting from the index idx.
void add_4D_tensor_argument (unsigned int &idx, const ICLTensor *tensor, const Window &window)
Add the passed 4D tensor's parameters to the object's kernel's arguments starting from the index idx.
void add_5D_tensor_argument (unsigned int &idx, const ICLTensor *tensor, const Window &window)
Add the passed 5D tensor's parameters to the object's kernel's arguments starting from the index idx.
void add_3d_tensor_nhw_argument (unsigned int &idx, const ICLTensor *tensor)
Add the passed NHW 3D tensor's parameters to the object's kernel's arguments by passing strides, dimensions and the offset to the first valid element in bytes.
void add_4d_tensor_nhwc_argument (unsigned int &idx, const ICLTensor *tensor)
Add the passed NHWC 4D tensor's parameters to the object's kernel's arguments by passing strides, dimensions and the offset to the first valid element in bytes.
virtual void run_op (ITensorPack &tensors, const Window &window, cl::CommandQueue &queue)
Enqueue the OpenCL kernel to process the given window on the passed OpenCL command queue.
template<typename T >
void add_argument (unsigned int &idx, T value)
Add the passed parameters to the object's kernel's arguments starting from the index idx.
void set_lws_hint (const cl::NDRange &lws_hint)
Set the Local-Workgroup-Size hint.
cl::NDRange lws_hint () const
Return the Local-Workgroup-Size hint.
void set_wbsm_hint (const cl_int &wbsm_hint)
Set the workgroup batch size modifier hint.
cl_int wbsm_hint () const
Return the workgroup batch size modifier hint.
const std::string & config_id () const
Get the configuration ID.
void set_target (GPUTarget target)
Set the targeted GPU architecture.
void set_target (cl::Device &device)
Set the targeted GPU architecture according to the CL device.
GPUTarget get_target () const
Get the targeted GPU architecture.
size_t get_max_workgroup_size ()
Get the maximum workgroup size for the device the CLKernelLibrary uses.
cl::NDRange get_cached_gws () const
Get the cached gws used to enqueue this kernel.
void cache_gws (const cl::NDRange &gws)
Cache the latest gws used to enqueue this kernel.
template<unsigned int dimension_size>
void add_tensor_argument (unsigned &idx, const ICLTensor *tensor, const Window &window)
template<typename T , unsigned int dimension_size>
void add_array_argument (unsigned &idx, const ICLArray< T > *array, const Strides &strides, unsigned int num_dimensions, const Window &window)
Add the passed array's parameters to the object's kernel's arguments starting from the index idx.
Public Member Functions inherited from IKernel
IKernel ()
Constructor.
virtual ~IKernel ()=default
Destructor.
virtual bool is_parallelisable () const
Indicates whether or not the kernel is parallelisable.
virtual BorderSize border_size () const
The size of the border for that kernel.
const Window & window () const
The maximum window the kernel can be executed on.
bool is_window_configured () const
Function to check if the embedded window of this kernel has been configured.
Static Public Member Functions
static Status validate (const ITensorInfo *input, const ITensorInfo *output, const ITensorInfo *mean, const ITensorInfo *var, const ITensorInfo *beta=nullptr, const ITensorInfo *gamma=nullptr, float epsilon=0.001f, ActivationLayerInfo act_info=ActivationLayerInfo())
Static function to check if given info will lead to a valid configuration of CLBatchNormalizationLayerKernel.
Static Public Member Functions inherited from ICLKernel
constexpr static unsigned int num_arguments_per_3d_tensor_nhw ()
Returns the number of arguments enqueued per NHW 3D Tensor object.
constexpr static unsigned int num_arguments_per_4d_tensor_nhwc ()
Returns the number of arguments enqueued per NHWC 4D Tensor object.
constexpr static unsigned int num_arguments_per_1D_array ()
Returns the number of arguments enqueued per 1D array object.
constexpr static unsigned int num_arguments_per_1D_tensor ()
Returns the number of arguments enqueued per 1D tensor object.
constexpr static unsigned int num_arguments_per_2D_tensor ()
Returns the number of arguments enqueued per 2D tensor object.
constexpr static unsigned int num_arguments_per_3D_tensor ()
Returns the number of arguments enqueued per 3D tensor object.
constexpr static unsigned int num_arguments_per_4D_tensor ()
Returns the number of arguments enqueued per 4D tensor object.
static cl::NDRange gws_from_window (const Window &window, bool use_dummy_work_items)
Get the global work size given an execution window.
Detailed Description
Interface for the BatchNormalization layer kernel.
Definition at line 37 of file CLBatchNormalizationLayerKernel.h.
Constructor & Destructor Documentation
CLBatchNormalizationLayerKernel() [1/3]
CLBatchNormalizationLayerKernel ()
Constructor.
Definition at line 120 of file CLBatchNormalizationLayerKernel.cpp.
     : _input(nullptr),
       _output(nullptr),
       _mean(nullptr),
       _var(nullptr),
       _beta(nullptr),
       _gamma(nullptr),
       _epsilon(0),
       _run_in_place(false)
 {
     _type = CLKernelType::ELEMENTWISE;
 }
References arm_compute::ELEMENTWISE.
CLBatchNormalizationLayerKernel() [2/3]
CLBatchNormalizationLayerKernel (const CLBatchNormalizationLayerKernel &) delete
Prevent instances of this class from being copied (As this class contains pointers)
CLBatchNormalizationLayerKernel() [3/3]
CLBatchNormalizationLayerKernel (CLBatchNormalizationLayerKernel &&) default
Default Move Constructor.
~CLBatchNormalizationLayerKernel()
~CLBatchNormalizationLayerKernel () default
Default destructor.
Member Function Documentation
configure() [1/2]
void configure (const CLCompileContext & compile_context, ICLTensor * input, ICLTensor * output, const ICLTensor * mean, const ICLTensor * var, const ICLTensor * beta = nullptr, const ICLTensor * gamma = nullptr, float epsilon = 0.001f, ActivationLayerInfo act_info = ActivationLayerInfo())
Set the input and output tensors.
Note
If the output tensor is a nullptr, the batch normalization function will be performed in-place
Parameters
[in] compile_context The compile context to be used.
[in,out] input Source tensor. In case of output tensor = nullptr, this tensor will store the result. 3 lower dimensions represent a single input with dimensions [width, height, FM]. The rest are optional and used for representing batches. Data types supported: F16/F32. Data layouts supported: NCHW/NHWC.
[out] output Destination tensor. Output will have the same number of dimensions as input. Data type supported: same as input
[in] mean Mean values tensor. 1 dimension with size equal to the feature maps [FM]. Data types supported: Same as input
[in] var Variance values tensor. 1 dimension with size equal to the feature maps [FM]. Data types supported: Same as input
[in] beta (Optional) Beta values tensor info. 1 dimension with size equal to the feature maps [FM]. If not provided, default value for beta is 0. Data types supported: Same as input
[in] gamma (Optional) Gamma values tensor info. 1 dimension with size equal to the feature maps [FM]. If not provided, default value for gamma is 1. Data types supported: Same as input
[in] epsilon (Optional) Small value to avoid division with zero. Default value is 0.001f.
[in] act_info (Optional) Activation layer information in case of a fused activation. Only RELU, BOUNDED_RELU and LU_BOUNDED_RELU supported.
Definition at line 145 of file CLBatchNormalizationLayerKernel.cpp.
 {
     ARM_COMPUTE_ERROR_ON_NULLPTR(input, mean, var);
     auto padding_info = get_padding_info({input, output, mean, var, beta, gamma});
     _input            = input;
     _output           = output;
     _mean             = mean;
     _var              = var;
     _beta             = beta;
     _gamma            = gamma;
     _epsilon          = epsilon;
     _run_in_place = (output == nullptr) || (output == input);
     ARM_COMPUTE_ERROR_THROW_ON(validate_arguments(input->info(), (output != nullptr) ? output->info() : nullptr,
                                                   mean->info(), var->info(), (beta != nullptr) ? beta->info() : nullptr,
                                                   (gamma != nullptr) ? gamma->info() : nullptr, epsilon, act_info));
     unsigned int num_elems_processed_per_iteration =
         adjust_vec_size(16 / input->info()->element_size(), input->info()->dimension(0));
     // Set build options
     CLBuildOptions build_opts;
     build_opts.add_option("-DDATA_TYPE=" + get_cl_type_from_data_type(input->info()->data_type()));
     build_opts.add_option("-DVEC_SIZE=" + support::cpp11::to_string(num_elems_processed_per_iteration));
     build_opts.add_option("-DVEC_SIZE_LEFTOVER=" +
                           support::cpp11::to_string(input->info()->dimension(0) % num_elems_processed_per_iteration));
     build_opts.add_option("-DACTIVATION_TYPE=" + lower_string(string_from_activation_func(act_info.activation())));
     build_opts.add_option_if(act_info.enabled(), "-DA_VAL=" + float_to_string_with_full_precision(act_info.a()));
     build_opts.add_option_if(act_info.enabled(), "-DB_VAL=" + float_to_string_with_full_precision(act_info.b()));
     build_opts.add_option_if(_run_in_place, "-DIN_PLACE");
     build_opts.add_option_if(beta == nullptr, "-DUSE_DEFAULT_BETA");
     build_opts.add_option_if(gamma == nullptr, "-DUSE_DEFAULT_GAMMA");
     // Create kernel
     _kernel =
         create_kernel(compile_context,
                       "batchnormalization_layer_" + lower_string(string_from_data_layout(input->info()->data_layout())),
                       build_opts.options());
     // Set kernel static arguments
     unsigned int include_output = (!_run_in_place) ? 1 : 0;
     unsigned int idx            = (1 + include_output) * num_arguments_per_3D_tensor() +
                        2 * num_arguments_per_1D_tensor(); // Skip the input and output parameters
     if (_beta != nullptr)
     {
         idx += num_arguments_per_1D_tensor(); // Skip beta parameter
     }
     if (_gamma != nullptr)
     {
         idx += num_arguments_per_1D_tensor(); // Skip gamma parameter
     }
     _kernel.setArg<cl_float>(idx++, _epsilon);
     if (output != nullptr)
     {
         // Output tensor auto initialization if not yet initialized
         auto_init_if_empty(*output->info(), *input->info()->clone());
     }
     // Configure kernel window
     if (input->info()->data_layout() == DataLayout::NHWC)
     {
         Window win = calculate_max_window(*input->info(), Steps(num_elems_processed_per_iteration));
         ICLKernel::configure_internal(win);
     }
     else
     {
         auto win_config = validate_and_configure_window_nchw(input->info(), (_run_in_place) ? nullptr : output->info());
         ARM_COMPUTE_ERROR_THROW_ON(win_config.first);
         ICLKernel::configure_internal(win_config.second);
     }
     ARM_COMPUTE_ERROR_ON(input->info()->data_layout() == DataLayout::NHWC && has_padding_changed(padding_info));
     _config_id = "batch_normalization_layer_";
     _config_id += string_from_data_type(input->info()->data_type());
     _config_id += "_";
     _config_id += support::cpp11::to_string(input->info()->dimension(0));
     _config_id += "_";
     _config_id += support::cpp11::to_string(input->info()->dimension(1));
     _config_id += "_";
     _config_id += support::cpp11::to_string(input->info()->dimension(2));
     _config_id += "_";
     _config_id += lower_string(string_from_data_layout(input->info()->data_layout()));
 }
References arm_compute::test::validation::act_info, CLBuildOptions::add_option(), CLBuildOptions::add_option_if(), arm_compute::adjust_vec_size(), ARM_COMPUTE_ERROR_ON, ARM_COMPUTE_ERROR_ON_NULLPTR, ARM_COMPUTE_ERROR_THROW_ON, arm_compute::auto_init_if_empty(), arm_compute::calculate_max_window(), arm_compute::create_kernel(), arm_compute::quantization::epsilon, arm_compute::float_to_string_with_full_precision(), arm_compute::get_cl_type_from_data_type(), arm_compute::get_padding_info(), arm_compute::has_padding_changed(), ITensor::info(), arm_compute::test::validation::input, arm_compute::lower_string(), arm_compute::NHWC, ICLKernel::num_arguments_per_1D_tensor(), ICLKernel::num_arguments_per_3D_tensor(), num_elems_processed_per_iteration, CLBuildOptions::options(), arm_compute::string_from_activation_func(), arm_compute::string_from_data_layout(), arm_compute::string_from_data_type(), arm_compute::support::cpp11::to_string(), and arm_compute::cpu::kernels::validate_arguments().
configure() [2/2]
void configure (ICLTensor * input, ICLTensor * output, const ICLTensor * mean, const ICLTensor * var, const ICLTensor * beta = nullptr, const ICLTensor * gamma = nullptr, float epsilon = 0.001f, ActivationLayerInfo act_info = ActivationLayerInfo())
Set the input and output tensors.
Note
If the output tensor is a nullptr, the batch normalization function will be performed in-place
Parameters
[in,out] input Source tensor. In case of output tensor = nullptr, this tensor will store the result. 3 lower dimensions represent a single input with dimensions [width, height, FM]. The rest are optional and used for representing batches. Data types supported: F16/F32. Data layouts supported: NCHW/NHWC.
[out] output Destination tensor. Output will have the same number of dimensions as input. Data type supported: same as input
[in] mean Mean values tensor. 1 dimension with size equal to the feature maps [FM]. Data types supported: Same as input
[in] var Variance values tensor. 1 dimension with size equal to the feature maps [FM]. Data types supported: Same as input
[in] beta (Optional) Beta values tensor info. 1 dimension with size equal to the feature maps [FM]. If not provided, default value for beta is 0. Data types supported: Same as input
[in] gamma (Optional) Gamma values tensor info. 1 dimension with size equal to the feature maps [FM]. If not provided, default value for gamma is 1. Data types supported: Same as input
[in] epsilon (Optional) Small value to avoid division with zero. Default value is 0.001f.
[in] act_info (Optional) Activation layer information in case of a fused activation. Only RELU, BOUNDED_RELU and LU_BOUNDED_RELU supported.
Definition at line 133 of file CLBatchNormalizationLayerKernel.cpp.
 {
     configure(CLKernelLibrary::get().get_compile_context(), input, output, mean, var, beta, gamma, epsilon, act_info);
 }
References arm_compute::test::validation::act_info, arm_compute::quantization::epsilon, CLKernelLibrary::get(), and arm_compute::test::validation::input.
operator=() [1/2]
CLBatchNormalizationLayerKernel& operator= (CLBatchNormalizationLayerKernel &&) default
Default move assignment operator.
operator=() [2/2]
CLBatchNormalizationLayerKernel& operator= (const CLBatchNormalizationLayerKernel &) delete
Prevent instances of this class from being copied (As this class contains pointers)
run()
void run (const Window & window, cl::CommandQueue & queue) override virtual
Enqueue the OpenCL kernel to process the given window on the passed OpenCL command queue.
Note
The queue is not flushed by this method, and therefore the kernel will not have been executed by the time this method returns.
Parameters
[in] window Region on which to execute the kernel. (Must be a valid region of the window returned by window()).
[in,out] queue Command queue on which to enqueue the kernel.
Reimplemented from ICLKernel.
Definition at line 263 of file CLBatchNormalizationLayerKernel.cpp.
 {
     ARM_COMPUTE_ERROR_ON_UNCONFIGURED_KERNEL(this);
     ARM_COMPUTE_ERROR_ON_INVALID_SUBWINDOW(IKernel::window(), window);
     Window slice = window.first_slice_window_3D();
     Window vector_slice = window.first_slice_window_1D();
     vector_slice.set(Window::DimX, Window::Dimension(0, 0, 0));
     unsigned int include_output = (!_run_in_place) ? 1 : 0;
     unsigned int idx            = (1 + include_output) * num_arguments_per_3D_tensor();
     add_1D_tensor_argument(idx, _mean, vector_slice);
     add_1D_tensor_argument(idx, _var, vector_slice);
     if (_beta != nullptr)
     {
         add_1D_tensor_argument(idx, _beta, vector_slice);
     }
     if (_gamma != nullptr)
     {
         add_1D_tensor_argument(idx, _gamma, vector_slice);
     }
     do
     {
         idx = 0;
         add_3D_tensor_argument(idx, _input, slice);
         if (!_run_in_place)
         {
             add_3D_tensor_argument(idx, _output, slice);
         }
         enqueue(queue, *this, slice, lws_hint());
     } while (window.slide_window_slice_3D(slice));
 }
References ICLKernel::add_1D_tensor_argument(), ICLKernel::add_3D_tensor_argument(), ARM_COMPUTE_ERROR_ON_INVALID_SUBWINDOW, ARM_COMPUTE_ERROR_ON_UNCONFIGURED_KERNEL, Window::DimX, arm_compute::enqueue(), Window::first_slice_window_1D(), Window::first_slice_window_3D(), ICLKernel::lws_hint(), ICLKernel::num_arguments_per_3D_tensor(), Window::set(), arm_compute::test::validation::reference::slice(), Window::slide_window_slice_3D(), and IKernel::window().
validate()
Status validate (const ITensorInfo * input, const ITensorInfo * output, const ITensorInfo * mean, const ITensorInfo * var, const ITensorInfo * beta = nullptr, const ITensorInfo * gamma = nullptr, float epsilon = 0.001f, ActivationLayerInfo act_info = ActivationLayerInfo()) static
Static function to check if given info will lead to a valid configuration of CLBatchNormalizationLayerKernel.
Parameters
[in] input Source tensor info. In case of output tensor info = nullptr, this tensor will store the result. 3 lower dimensions represent a single input with dimensions [width, height, FM]. The rest are optional and used for representing batches. Data types supported: F16/F32. Data layouts supported: NCHW/NHWC.
[in] output Destination tensor info. Output will have the same number of dimensions as input. Data type supported: same as input
[in] mean Mean values tensor info. 1 dimension with size equal to the feature maps [FM]. Data types supported: Same as input
[in] var Variance values tensor info. 1 dimension with size equal to the feature maps [FM]. Data types supported: Same as input
[in] beta (Optional) Beta values tensor info. 1 dimension with size equal to the feature maps [FM]. If not provided, default value for beta is 0. Data types supported: Same as input
[in] gamma (Optional) Gamma values tensor info. 1 dimension with size equal to the feature maps [FM]. If not provided, default value for gamma is 1. Data types supported: Same as input
[in] epsilon (Optional) Small value to avoid division with zero. Default value is 0.001f.
[in] act_info (Optional) Activation layer information in case of a fused activation. Only RELU, BOUNDED_RELU and LU_BOUNDED_RELU supported.
Returns
a status
Definition at line 241 of file CLBatchNormalizationLayerKernel.cpp.
 {
     const bool run_in_place = (output == nullptr) || (output == input);
     ARM_COMPUTE_RETURN_ON_ERROR(validate_arguments(input, output, mean, var, beta, gamma, epsilon, act_info));
     if (input->data_layout() != DataLayout::NHWC)
     {
         ARM_COMPUTE_RETURN_ON_ERROR(
             validate_and_configure_window_nchw(input->clone().get(), (run_in_place) ? nullptr : output->clone().get())
                 .first);
     }
     return Status{};
 }
References arm_compute::test::validation::act_info, ARM_COMPUTE_RETURN_ON_ERROR, ICloneable< T >::clone(), arm_compute::quantization::epsilon, arm_compute::test::validation::input, arm_compute::NHWC, and arm_compute::cpu::kernels::validate_arguments().
Referenced by CLBatchNormalizationLayer::validate().
The documentation for this class was generated from the following files:
src/core/CL/kernels/CLBatchNormalizationLayerKernel.h
src/core/CL/kernels/CLBatchNormalizationLayerKernel.cpp