Compute Library: CpuScale Class Reference
CpuScale Class Reference
Basic function to compute Scale.
#include <CpuScale.h>
Public Member Functions
void configure (ITensorInfo *src, ITensorInfo *dst, const ScaleKernelInfo &info)
Initialize the function's source, destination, interpolation type and border_mode.
void prepare (ITensorPack &tensors) override
Prepare the function for executing.
void run (ITensorPack &tensors) override
Run the kernels contained in the function.
Public Member Functions inherited from INEOperator
INEOperator (IRuntimeContext *ctx=nullptr)
Constructor.
INEOperator (const INEOperator &)=delete
Prevent instances of this class from being copied (As this class contains pointers)
INEOperator (INEOperator &&)=default
Default move constructor.
INEOperator & operator= (const INEOperator &)=delete
Prevent instances of this class from being copied (As this class contains pointers)
INEOperator & operator= (INEOperator &&)=default
Default move assignment operator.
~INEOperator ()
Default destructor.
MemoryRequirements workspace () const override
Return the memory requirements required by the workspace.
Public Member Functions inherited from IOperator
virtual ~IOperator ()=default
Destructor.
Static Public Member Functions
static Status validate (const ITensorInfo *src, const ITensorInfo *dst, const ScaleKernelInfo &info)
Static function to check if given info will lead to a valid configuration.
Detailed Description
Basic function to compute Scale.
Definition at line 41 of file CpuScale.h.
Member Function Documentation
configure()
void configure (ITensorInfo * src, ITensorInfo * dst, const ScaleKernelInfo & info)
Initialize the function's source, destination, interpolation type and border_mode.
Parameters
[in,out] src Source tensor info. Data type supported: QASYMM8/QASYMM8_SIGNED/U8/S16/F16/F32. (Written to only for border_mode != UNDEFINED)
[out] dst Destination tensor info. Data type supported: Same as src. All but the lowest two dimensions must be the same size as in the input tensor, i.e. scaling is only performed within the XY-plane.
[in] info ScaleKernelInfo to be used for configuration
Note
Using S8 data type only supports NHWC, border_mode Replicate, and policy Bilinear
Definition at line 97 of file CpuScale.cpp.
 {
     ARM_COMPUTE_ERROR_ON_NULLPTR(src, dst);
     ARM_COMPUTE_ERROR_THROW_ON(CpuScale::validate(src, dst, info));
     ARM_COMPUTE_LOG_PARAMS(src, dst, info);
     _scale_info  = info;
     _is_prepared = false;
     // Get data layout and width/height indices
     _data_layout        = _scale_info.data_layout == DataLayout::UNKNOWN ? src->data_layout() : _scale_info.data_layout;
     const int idx_width = get_data_layout_dimension_index(_data_layout, DataLayoutDimension::WIDTH);
     const int idx_height = get_data_layout_dimension_index(_data_layout, DataLayoutDimension::HEIGHT);
     // Compute the ratio between source width/height and destination width/height
     const bool is_align_corners_used =
         _scale_info.align_corners &&
         arm_compute::scale_utils::is_align_corners_allowed_sampling_policy(_scale_info.sampling_policy);
     const auto wr = arm_compute::scale_utils::calculate_resize_ratio(src->dimension(idx_width),
                                                                      dst->dimension(idx_width), is_align_corners_used);
     const auto hr = arm_compute::scale_utils::calculate_resize_ratio(src->dimension(idx_height),
                                                                      dst->dimension(idx_height), is_align_corners_used);
     // Area interpolation behaves as Nearest Neighbour in case of up-sampling
     InterpolationPolicy policy_to_use =
         (_scale_info.interpolation_policy == InterpolationPolicy::AREA && wr <= 1.f && hr <= 1.f)
             ? InterpolationPolicy::NEAREST_NEIGHBOR
             : _scale_info.interpolation_policy;
     // Get the tensor shape
     TensorShape shape(dst->dimension(idx_width));
     shape.set(1, dst->dimension(idx_height), false);
     TensorInfo tensor_info_offsets(shape, Format::S32);
     TensorInfo tensor_info_dxdy(shape, Format::F32);
     auto dx           = std::make_unique<TensorInfo>(tensor_info_dxdy);
     auto dy           = std::make_unique<TensorInfo>(tensor_info_dxdy);
     auto offsets      = std::make_unique<TensorInfo>(tensor_info_offsets);
     auto scale_kernel = std::make_unique<kernels::CpuScaleKernel>();
     switch (policy_to_use)
     {
         case InterpolationPolicy::NEAREST_NEIGHBOR:
         {
             scale_kernel->configure(src, nullptr, nullptr, offsets.get(), dst, info);
             break;
         }
         case InterpolationPolicy::BILINEAR:
         {
             scale_kernel->configure(src, dx.get(), dy.get(), offsets.get(), dst, info);
             break;
         }
         case InterpolationPolicy::AREA:
         {
             scale_kernel->configure(src, nullptr, nullptr, nullptr, dst, info);
             break;
         }
         default:
             ARM_COMPUTE_ERROR("Unsupported interpolation mode");
     }
     _kernel = std::move(scale_kernel);
 }
References ScaleKernelInfo::align_corners, arm_compute::AREA, ARM_COMPUTE_ERROR, ARM_COMPUTE_ERROR_ON_NULLPTR, ARM_COMPUTE_ERROR_THROW_ON, ARM_COMPUTE_LOG_PARAMS, arm_compute::BILINEAR, arm_compute::scale_utils::calculate_resize_ratio(), ScaleKernelInfo::data_layout, arm_compute::test::validation::dst, arm_compute::F32, arm_compute::get_data_layout_dimension_index(), arm_compute::HEIGHT, arm_compute::test::validation::idx_height, arm_compute::test::validation::idx_width, arm_compute::test::validation::info, ScaleKernelInfo::interpolation_policy, arm_compute::scale_utils::is_align_corners_allowed_sampling_policy(), arm_compute::NEAREST_NEIGHBOR, arm_compute::S32, ScaleKernelInfo::sampling_policy, arm_compute::test::validation::shape, arm_compute::test::validation::src, arm_compute::UNKNOWN, CpuScale::validate(), and arm_compute::WIDTH.
prepare()
void prepare (ITensorPack & constants) override virtual
Prepare the function for executing.
Any one off pre-processing step required by the function is handled here
Parameters
[in] constants Vector that contains the constants tensors.
Note
Prepare stage might not need all the function's buffers' backing memory to be available in order to execute
Reimplemented from INEOperator.
Definition at line 213 of file CpuScale.cpp.
 {
     if (!_is_prepared)
     {
         _is_prepared       = true;
         const auto src     = tensors.get_const_tensor(TensorType::ACL_SRC);
         auto       dst     = tensors.get_tensor(TensorType::ACL_DST);
         auto       dx      = tensors.get_tensor(TensorType::ACL_INT_0);
         auto       dy      = tensors.get_tensor(TensorType::ACL_INT_1);
         auto       offsets = tensors.get_tensor(TensorType::ACL_INT_2);
         // Get data layout and width/height indices
         const int idx_width  = get_data_layout_dimension_index(_data_layout, DataLayoutDimension::WIDTH);
         const int idx_height = get_data_layout_dimension_index(_data_layout, DataLayoutDimension::HEIGHT);
         // Compute the ratio between source width/height and destination width/height
         const bool is_align_corners_used =
             _scale_info.align_corners &&
             arm_compute::scale_utils::is_align_corners_allowed_sampling_policy(_scale_info.sampling_policy);
         const auto wr = arm_compute::scale_utils::calculate_resize_ratio(
             src->info()->dimension(idx_width), dst->info()->dimension(idx_width), is_align_corners_used);
         const auto hr = arm_compute::scale_utils::calculate_resize_ratio(
             src->info()->dimension(idx_height), dst->info()->dimension(idx_height), is_align_corners_used);
         // Area interpolation behaves as Nearest Neighbour in case of up-sampling
         InterpolationPolicy policy_to_use =
             (_scale_info.interpolation_policy == InterpolationPolicy::AREA && wr <= 1.f && hr <= 1.f)
                 ? InterpolationPolicy::NEAREST_NEIGHBOR
                 : _scale_info.interpolation_policy;
         const SamplingPolicy sampling_policy = _scale_info.sampling_policy;
         bool precompute_indices_weights = arm_compute::scale_utils::is_precomputation_required(
             _data_layout, src->info()->data_type(), policy_to_use, _scale_info.border_mode);
         if (precompute_indices_weights)
         {
             switch (policy_to_use)
             {
                 case InterpolationPolicy::NEAREST_NEIGHBOR:
                 {
                     // Pre-compute offsets for nearest interpolation
                     precompute_dx_dy_offsets(nullptr, nullptr, offsets, wr, hr, sampling_policy, is_align_corners_used);
                     break;
                 }
                 case InterpolationPolicy::BILINEAR:
                 {
                     // Pre-compute dx, dy and offsets for bilinear interpolation
                     precompute_dx_dy_offsets(dx, dy, offsets, wr, hr, sampling_policy, is_align_corners_used);
                     break;
                 }
                 case InterpolationPolicy::AREA:
                 {
                     break;
                 }
                 default:
                     ARM_COMPUTE_ERROR("Unsupported interpolation mode");
             }
         }
         else
         {
             if (policy_to_use != InterpolationPolicy::NEAREST_NEIGHBOR &&
                 policy_to_use != InterpolationPolicy::BILINEAR && policy_to_use != InterpolationPolicy::AREA)
             {
                 ARM_COMPUTE_ERROR("Unsupported interpolation mode");
             }
         }
     }
 }
References arm_compute::ACL_DST, arm_compute::ACL_INT_0, arm_compute::ACL_INT_1, arm_compute::ACL_INT_2, arm_compute::ACL_SRC, ScaleKernelInfo::align_corners, arm_compute::AREA, ARM_COMPUTE_ERROR, arm_compute::BILINEAR, ScaleKernelInfo::border_mode, arm_compute::scale_utils::calculate_resize_ratio(), arm_compute::test::validation::dst, ITensorPack::get_const_tensor(), arm_compute::get_data_layout_dimension_index(), ITensorPack::get_tensor(), arm_compute::HEIGHT, arm_compute::test::validation::idx_height, arm_compute::test::validation::idx_width, ScaleKernelInfo::interpolation_policy, arm_compute::scale_utils::is_align_corners_allowed_sampling_policy(), arm_compute::scale_utils::is_precomputation_required(), arm_compute::NEAREST_NEIGHBOR, ScaleKernelInfo::sampling_policy, arm_compute::test::validation::sampling_policy, arm_compute::test::validation::src, and arm_compute::WIDTH.
Referenced by CpuScale::run().
run()
void run (ITensorPack & tensors) override virtual
Run the kernels contained in the function.
Parameters
[in] tensors Vector that contains the tensors to operate on.
Reimplemented from INEOperator.
Definition at line 282 of file CpuScale.cpp.
 {
     ARM_COMPUTE_ERROR_ON_MSG(tensors.empty(), "No inputs provided");
     prepare(tensors);
     NEScheduler::get().schedule_op(_kernel.get(), Window::DimY, _kernel->window(), tensors);
 }
References ARM_COMPUTE_ERROR_ON_MSG, Window::DimY, ITensorPack::empty(), Scheduler::get(), CpuScale::prepare(), and IScheduler::schedule_op().
validate()
Status validate (const ITensorInfo * src, const ITensorInfo * dst, const ScaleKernelInfo & info) static
Static function to check if given info will lead to a valid configuration.
Similar to CpuScale::configure()
Returns
a status
Definition at line 160 of file CpuScale.cpp.
 {
     ARM_COMPUTE_RETURN_ERROR_ON_NULLPTR(src, dst);
     ARM_COMPUTE_RETURN_ERROR_ON(info.sampling_policy != SamplingPolicy::CENTER &&
                                 info.sampling_policy != SamplingPolicy::TOP_LEFT);
     ITensorInfo *offsets = nullptr;
     ITensorInfo *dx      = nullptr;
     ITensorInfo *dy      = nullptr;
     // Get data layout and width/height indices
     const DataLayout data_layout = info.data_layout == DataLayout::UNKNOWN ? src->data_layout() : info.data_layout;
     const int        idx_width   = get_data_layout_dimension_index(data_layout, DataLayoutDimension::WIDTH);
     const int        idx_height  = get_data_layout_dimension_index(data_layout, DataLayoutDimension::HEIGHT);
     // Compute the ratio between source width/height and destination width/height
     const bool is_align_corners_used =
         info.align_corners && arm_compute::scale_utils::is_align_corners_allowed_sampling_policy(info.sampling_policy);
     const auto wr = arm_compute::scale_utils::calculate_resize_ratio(src->dimension(idx_width),
                                                                      dst->dimension(idx_width), is_align_corners_used);
     const auto hr = arm_compute::scale_utils::calculate_resize_ratio(src->dimension(idx_height),
                                                                      dst->dimension(idx_height), is_align_corners_used);
     // Area interpolation behaves as Nearest Neighbour in case of up-sampling
     InterpolationPolicy policy_to_use =
         (info.interpolation_policy == InterpolationPolicy::AREA && wr <= 1.f && hr <= 1.f)
             ? InterpolationPolicy::NEAREST_NEIGHBOR
             : info.interpolation_policy;
     // Get the tensor shape of auxilary buffers
     const TensorShape shape(dst->dimension(idx_width), dst->dimension(idx_height));
     TensorInfo        tensor_info_offsets(shape, Format::S32);
     TensorInfo        tensor_info_dx(shape, Format::F32);
     TensorInfo        tensor_info_dy(shape, Format::F32);
     switch (policy_to_use)
     {
         case InterpolationPolicy::NEAREST_NEIGHBOR:
             offsets = &tensor_info_offsets;
             break;
         case InterpolationPolicy::BILINEAR:
             offsets = &tensor_info_offsets;
             dx      = &tensor_info_dx;
             dy      = &tensor_info_dy;
             break;
         default:
             break;
     }
     ARM_COMPUTE_RETURN_ON_ERROR(
         kernels::CpuScaleKernel::validate(src->clone().get(), dx, dy, offsets, dst->clone().get(), info));
     return Status{};
 }
References ScaleKernelInfo::align_corners, arm_compute::AREA, ARM_COMPUTE_RETURN_ERROR_ON, ARM_COMPUTE_RETURN_ERROR_ON_NULLPTR, ARM_COMPUTE_RETURN_ON_ERROR, arm_compute::BILINEAR, arm_compute::scale_utils::calculate_resize_ratio(), arm_compute::CENTER, arm_compute::cpu::data_layout, ScaleKernelInfo::data_layout, arm_compute::test::validation::dst, arm_compute::F32, arm_compute::get_data_layout_dimension_index(), arm_compute::HEIGHT, arm_compute::test::validation::idx_height, arm_compute::test::validation::idx_width, arm_compute::test::validation::info, ScaleKernelInfo::interpolation_policy, arm_compute::scale_utils::is_align_corners_allowed_sampling_policy(), arm_compute::NEAREST_NEIGHBOR, arm_compute::S32, ScaleKernelInfo::sampling_policy, arm_compute::test::validation::shape, arm_compute::test::validation::src, arm_compute::TOP_LEFT, arm_compute::UNKNOWN, CpuScaleKernel::validate(), and arm_compute::WIDTH.
Referenced by CpuScale::configure(), and NEScale::validate().
The documentation for this class was generated from the following files:
src/cpu/operators/CpuScale.h
src/cpu/operators/CpuScale.cpp