Compute Library: GpuKernelArgument Class Reference
GpuKernelArgument Class Reference
Kernel argument information linked with its corresponding ITensorInfo.
#include <GpuKernelArgument.h>
Public Member Functions
GpuKernelArgument (const ITensorInfo &tensor_info, const GpuKernelArgumentInfo &kernel_arg_info)
Constructor.
ITensorInfo::Id id () const
Get workload tensor id.
ITensorInfo * tensor_info ()
Get associated ITensorInfo.
const ITensorInfo * tensor_info () const
Get associated ITensorInfo.
GpuKernelArgumentInfo * kernel_argument_info ()
Get associated GpuKernelArgumentInfo.
const GpuKernelArgumentInfo * kernel_argument_info () const
Get associated GpuKernelArgumentInfo.
bool has_valid_id () const
Check if the associated workload tensor has valid id.
Detailed Description
Kernel argument information linked with its corresponding ITensorInfo.
Deprecated:
To be removed along with ClTemplateWriter
Definition at line 73 of file GpuKernelArgument.h.
Constructor & Destructor Documentation
GpuKernelArgument()
GpuKernelArgument (const ITensorInfo & tensor_info, const GpuKernelArgumentInfo & kernel_arg_info) inline
Constructor.
Parameters
[in] tensor_info Associated ITensorInfo
[in] kernel_arg_info Associated GpuKernelArgumentInfo
Definition at line 81 of file GpuKernelArgument.h.
         : _tensor_info{tensor_info}, _kernel_arg_info{kernel_arg_info}
     {
     }
References GpuKernelArgument::tensor_info().
Member Function Documentation
has_valid_id()
bool has_valid_id () const inline
Check if the associated workload tensor has valid id.
Returns
true if has valid id
false otherwise
Definition at line 115 of file GpuKernelArgument.h.
     {
         return _tensor_info.has_valid_id();
     }
References ITensorInfo::has_valid_id().
id()
ITensorInfo::Id id () const inline
Get workload tensor id.
Definition at line 86 of file GpuKernelArgument.h.
     {
         return _tensor_info.id();
     }
References TensorInfo::id().
kernel_argument_info() [1/2]
GpuKernelArgumentInfo* kernel_argument_info () inline
Get associated GpuKernelArgumentInfo.
Definition at line 101 of file GpuKernelArgument.h.
     {
         return &_kernel_arg_info;
     }
kernel_argument_info() [2/2]
const GpuKernelArgumentInfo* kernel_argument_info () const inline
Get associated GpuKernelArgumentInfo.
Definition at line 106 of file GpuKernelArgument.h.
     {
         return &_kernel_arg_info;
     }
tensor_info() [1/2]
ITensorInfo* tensor_info () inline
Get associated ITensorInfo.
Definition at line 91 of file GpuKernelArgument.h.
     {
         return &_tensor_info;
     }
Referenced by GpuKernelArgument::GpuKernelArgument().
tensor_info() [2/2]
const ITensorInfo* tensor_info () const inline
Get associated ITensorInfo.
Definition at line 96 of file GpuKernelArgument.h.
     {
         return &_tensor_info;
     }
The documentation for this class was generated from the following file:
src/dynamic_fusion/sketch/gpu/GpuKernelArgument.h