Compute Library: DetectionPostProcessLayerInfo Class Reference
DetectionPostProcessLayerInfo Class Reference final
Detection Output layer info.
#include <Types.h>
Public Member Functions
DetectionPostProcessLayerInfo ()
Default Constructor.
DetectionPostProcessLayerInfo (unsigned int max_detections, unsigned int max_classes_per_detection, float nms_score_threshold, float iou_threshold, unsigned int num_classes, std::array< float, 4 > scales_values, bool use_regular_nms=false, unsigned int detection_per_class=100, bool dequantize_scores=true)
Constructor.
unsigned int max_detections () const
Get max detections.
unsigned int max_classes_per_detection () const
Get max_classes per detection.
unsigned int detection_per_class () const
Get detection per class.
float nms_score_threshold () const
Get nms threshold.
float iou_threshold () const
Get intersection over union threshold.
unsigned int num_classes () const
Get num classes.
bool use_regular_nms () const
Get if use regular nms.
float scale_value_y () const
Get y scale value.
float scale_value_x () const
Get x scale value.
float scale_value_h () const
Get h scale value.
float scale_value_w () const
Get w scale value.
bool dequantize_scores () const
Get dequantize_scores value.
Detailed Description
Detection Output layer info.
Definition at line 917 of file Types.h.
Constructor & Destructor Documentation
DetectionPostProcessLayerInfo() [1/2]
DetectionPostProcessLayerInfo () inline
Default Constructor.
Definition at line 921 of file Types.h.
         : _max_detections(),
           _max_classes_per_detection(),
           _nms_score_threshold(),
           _iou_threshold(),
           _num_classes(),
           _scales_values(),
           _use_regular_nms(),
           _detection_per_class(),
           _dequantize_scores()
     {
     }
DetectionPostProcessLayerInfo() [2/2]
DetectionPostProcessLayerInfo (unsigned int max_detections, unsigned int max_classes_per_detection, float nms_score_threshold, float iou_threshold, unsigned int num_classes, std::array< float, 4 > scales_values, bool use_regular_nms = false, unsigned int detection_per_class = 100, bool dequantize_scores = true) inline
Constructor.
Parameters
[in] max_detections Number of total detection.
[in] max_classes_per_detection Number of total classes to be kept after NMS step. Used in the Fast Non-Max-Suppression
[in] nms_score_threshold Threshold to be used in NMS
[in] iou_threshold Threshold to be used during the intersection over union.
[in] num_classes Number of classes.
[in] scales_values Scales values used for decode center size boxes.
[in] use_regular_nms (Optional) Boolean to determinate if use regular or fast nms. Defaults to false.
[in] detection_per_class (Optional) Number of detection per class. Used in the Regular Non-Max-Suppression. Defaults to 100.
[in] dequantize_scores (Optional) If the scores need to be dequantized. Defaults to true.
Definition at line 945 of file Types.h.
         : _max_detections(max_detections),
           _max_classes_per_detection(max_classes_per_detection),
           _nms_score_threshold(nms_score_threshold),
           _iou_threshold(iou_threshold),
           _num_classes(num_classes),
           _scales_values(scales_values),
           _use_regular_nms(use_regular_nms),
           _detection_per_class(detection_per_class),
           _dequantize_scores(dequantize_scores)
     {
     }
Member Function Documentation
dequantize_scores()
bool dequantize_scores () const inline
Get dequantize_scores value.
Definition at line 1025 of file Types.h.
     {
         return _dequantize_scores;
     }
detection_per_class()
unsigned int detection_per_class () const inline
Get detection per class.
Used in the Regular Non-Max-Suppression
Definition at line 976 of file Types.h.
     {
         return _detection_per_class;
     }
Referenced by arm_compute::operator<<(), and CPPDetectionPostProcessLayer::run().
iou_threshold()
float iou_threshold () const inline
Get intersection over union threshold.
Definition at line 986 of file Types.h.
     {
         return _iou_threshold;
     }
Referenced by arm_compute::operator<<().
max_classes_per_detection()
unsigned int max_classes_per_detection () const inline
Get max_classes per detection.
Used in the Fast Non-Max-Suppression.
Definition at line 971 of file Types.h.
     {
         return _max_classes_per_detection;
     }
Referenced by DetectionPostProcessLayerNode::configure_output(), arm_compute::operator<<(), and CPPDetectionPostProcessLayer::run().
max_detections()
unsigned int max_detections () const inline
Get max detections.
Definition at line 966 of file Types.h.
     {
         return _max_detections;
     }
Referenced by DetectionPostProcessLayerNode::configure_output(), arm_compute::operator<<(), and CPPDetectionPostProcessLayer::run().
nms_score_threshold()
float nms_score_threshold () const inline
Get nms threshold.
Definition at line 981 of file Types.h.
     {
         return _nms_score_threshold;
     }
Referenced by arm_compute::operator<<().
num_classes()
unsigned int num_classes () const inline
Get num classes.
Definition at line 991 of file Types.h.
     {
         return _num_classes;
     }
Referenced by arm_compute::operator<<(), and CPPDetectionPostProcessLayer::run().
scale_value_h()
float scale_value_h () const inline
Get h scale value.
Definition at line 1013 of file Types.h.
     {
         // Saved as [y,x,h,w]
         return _scales_values[2];
     }
Referenced by arm_compute::operator<<().
scale_value_w()
float scale_value_w () const inline
Get w scale value.
Definition at line 1019 of file Types.h.
     {
         // Saved as [y,x,h,w]
         return _scales_values[3];
     }
Referenced by arm_compute::operator<<().
scale_value_x()
float scale_value_x () const inline
Get x scale value.
Definition at line 1007 of file Types.h.
     {
         // Saved as [y,x,h,w]
         return _scales_values[1];
     }
Referenced by arm_compute::operator<<().
scale_value_y()
float scale_value_y () const inline
Get y scale value.
Definition at line 1001 of file Types.h.
     {
         // Saved as [y,x,h,w]
         return _scales_values[0];
     }
Referenced by arm_compute::operator<<().
use_regular_nms()
bool use_regular_nms () const inline
Get if use regular nms.
Definition at line 996 of file Types.h.
     {
         return _use_regular_nms;
     }
Referenced by arm_compute::operator<<(), and CPPDetectionPostProcessLayer::run().
The documentation for this class was generated from the following file:
arm_compute/core/Types.h