Compute Library: GpuWorkloadSketch::Implementation Class Reference
GpuWorkloadSketch::Implementation Class Reference
Internal implementation of GpuWorkloadSketch.
#include <GpuWorkloadSketchImpl.h>
Public Member Functions
Implementation (Context *context)
Constructor.
Implementation (const Implementation &impl)=delete
Prevent instances of this class from being copy constructed.
Implementation & operator= (const Implementation &impl)=delete
Prevent instances of this class from being copied.
Implementation (Implementation &&impl)=default
Allow instances of this class to be move constructed.
Implementation & operator= (Implementation &&impl)=default
Allow instances of this class to be moved.
const Context * context () const
Get workload context.
const GpuKernelComponentGraph & component_graph () const
Get component graph.
GpuKernelComponentGraph & component_graph ()
Get component graph.
const GpuOperatorGroup & operator_group () const
Get operator group.
GpuOperatorGroup & operator_group ()
Get operator group.
GpuWorkloadSourceCode generate_source_code () const
Generate GpuWorkloadSourceCode from the workload sketch.
ITensorInfo * create_virtual_tensor ()
Create a virtual (see MemoryType) tensor info and save it.
ITensorInfo * create_auxiliary_tensor (const ITensorInfo &tensor_info)
Create an auxiliary (see MemoryType) tensor info and save it.
ITensorInfo * get_tensor_info (ITensorInfo::Id id)
Detailed Description
Internal implementation of GpuWorkloadSketch.
Definition at line 42 of file GpuWorkloadSketchImpl.h.
Constructor & Destructor Documentation
Implementation() [1/3]
Implementation (Context * context) inline explicit
Constructor.
Parameters
[in] context global workload creation context
Definition at line 49 of file GpuWorkloadSketchImpl.h.
         : _context{context}, _comp_services{}, _component_graph{_context, &_comp_services}, _operator_group{}
     {
     }
References GpuWorkloadSketch::Implementation::context().
Implementation() [2/3]
Implementation (const Implementation & impl) delete
Prevent instances of this class from being copy constructed.
Implementation() [3/3]
Implementation (Implementation && impl) default
Allow instances of this class to be move constructed.
Member Function Documentation
component_graph() [1/2]
GpuKernelComponentGraph& component_graph () inline
Get component graph.
Definition at line 72 of file GpuWorkloadSketchImpl.h.
     {
         return _component_graph;
     }
component_graph() [2/2]
const GpuKernelComponentGraph& component_graph () const inline
Get component graph.
Definition at line 67 of file GpuWorkloadSketchImpl.h.
     {
         return _component_graph;
     }
Referenced by GpuOutput::create_op(), GpuSigmoid::create_op(), GpuTanh::create_op(), GpuReshape::create_op(), GpuSoftmax::create_op(), GpuClamp::create_op(), GpuDepthwiseConv2d::create_op(), GpuConv2d::create_op(), GpuResize::create_op(), GpuCast::create_op(), GpuElementwiseBinaryCommon::create_op(), GpuPool2d::create_op(), and GpuWorkloadSketch::Implementation::generate_source_code().
context()
const Context* context () const inline
Get workload context.
Definition at line 62 of file GpuWorkloadSketchImpl.h.
     {
         return _context;
     }
Referenced by GpuOutput::create_op(), GpuSigmoid::create_op(), GpuTanh::create_op(), GpuReshape::create_op(), GpuSoftmax::create_op(), GpuClamp::create_op(), GpuDepthwiseConv2d::create_op(), GpuConv2d::create_op(), GpuResize::create_op(), GpuCast::create_op(), GpuElementwiseBinaryCommon::create_op(), GpuPool2d::create_op(), and GpuWorkloadSketch::Implementation::Implementation().
create_auxiliary_tensor()
ITensorInfo* create_auxiliary_tensor (const ITensorInfo & tensor_info) inline
Create an auxiliary (see MemoryType) tensor info and save it.
Parameters
[in] tensor_info ITensorInfo to copy from
Returns
ITensorInfo* The created auxiliary tensor info object pointer
Definition at line 110 of file GpuWorkloadSketchImpl.h.
     {
         return _context->implementation().create_auxiliary_tensor(tensor_info);
     }
References GpuWorkloadContext::Impl::create_auxiliary_tensor(), GpuWorkloadContext::implementation(), and tensor_info.
Referenced by GpuSoftmax::create_op().
create_virtual_tensor()
ITensorInfo* create_virtual_tensor () inline
Create a virtual (see MemoryType) tensor info and save it.
Returns
ITensorInfo* The created virtual tensor info object pointer
Definition at line 100 of file GpuWorkloadSketchImpl.h.
     {
         return _context->implementation().create_virtual_tensor();
     }
References GpuWorkloadContext::Impl::create_virtual_tensor(), and GpuWorkloadContext::implementation().
Referenced by GpuSigmoid::create_op(), GpuTanh::create_op(), GpuClamp::create_op(), GpuReshape::create_op(), GpuDepthwiseConv2d::create_op(), GpuConv2d::create_op(), GpuResize::create_op(), GpuCast::create_op(), GpuElementwiseBinaryCommon::create_op(), and GpuPool2d::create_op().
generate_source_code()
GpuWorkloadSourceCode generate_source_code () const inline
Generate GpuWorkloadSourceCode from the workload sketch.
Note
The sketch must be valid. Any error encountered during the building of the code will be thrown.
Returns
GpuWorkloadSourceCode The generated workload code
Definition at line 91 of file GpuWorkloadSketchImpl.h.
     {
         const auto mem_map = _context->implementation().mem_map();
         return component_graph().fuse(mem_map).write_workload_code();
     }
References GpuWorkloadSketch::Implementation::component_graph(), GpuKernelComponentGraph::fuse(), GpuWorkloadContext::implementation(), GpuWorkloadContext::Impl::mem_map(), and GpuKernelComponentStream::write_workload_code().
Referenced by ClWorkloadRuntime::configure().
get_tensor_info()
ITensorInfo* get_tensor_info (ITensorInfo::Id id) inline
Definition at line 115 of file GpuWorkloadSketchImpl.h.
     {
         return _context->implementation().get_tensor_info(id);
     }
References GpuWorkloadContext::Impl::get_tensor_info(), and GpuWorkloadContext::implementation().
operator=() [1/2]
Implementation& operator= (const Implementation & impl) delete
Prevent instances of this class from being copied.
operator=() [2/2]
Implementation& operator= (Implementation && impl) default
Allow instances of this class to be moved.
operator_group() [1/2]
GpuOperatorGroup& operator_group () inline
Get operator group.
Definition at line 82 of file GpuWorkloadSketchImpl.h.
     {
         return _operator_group;
     }
operator_group() [2/2]
const GpuOperatorGroup& operator_group () const inline
Get operator group.
Definition at line 77 of file GpuWorkloadSketchImpl.h.
     {
         return _operator_group;
     }
Referenced by GpuOutput::create_op(), GpuSigmoid::create_op(), GpuTanh::create_op(), GpuClamp::create_op(), GpuSoftmax::create_op(), GpuReshape::create_op(), GpuDepthwiseConv2d::create_op(), GpuConv2d::create_op(), GpuResize::create_op(), GpuCast::create_op(), GpuElementwiseBinaryCommon::create_op(), GpuPool2d::create_op(), GpuOutput::validate_op(), GpuSigmoid::validate_op(), GpuTanh::validate_op(), GpuReshape::validate_op(), GpuSoftmax::validate_op(), GpuClamp::validate_op(), GpuResize::validate_op(), GpuCast::validate_op(), GpuConv2d::validate_op(), GpuDepthwiseConv2d::validate_op(), GpuPool2d::validate_op(), and GpuElementwiseBinaryCommon::validate_op().
The documentation for this class was generated from the following file:
src/dynamic_fusion/sketch/gpu/GpuWorkloadSketchImpl.h