Compute Library: DepthwiseConv2dAttributes Class Reference
DepthwiseConv2dAttributes Class Reference
Attributes are backend-agnostic parameters (in addition to the input/output tensors) of an operator.
#include <DepthwiseConv2dAttributes.h>
Public Member Functions
DepthwiseConv2dAttributes & pad (const Padding2D &pad)
Set padding.
Padding2D pad () const
Get padding.
DepthwiseConv2dAttributes & stride (const Size2D &stride)
Set stride.
Size2D stride () const
Get stride.
DepthwiseConv2dAttributes & dilation (const Size2D &dilation)
Set dilation.
Size2D dilation () const
Get dilation.
DepthwiseConv2dAttributes & depth_multiplier (const uint32_t &depth_multiplier)
Set depth multiplier.
uint32_t depth_multiplier () const
Get depth multiplier.
DepthwiseConv2dAttributes & dimension_rounding_type (const DimensionRoundingType &dimension_rounding_type)
Set Dimension rounding type.
DimensionRoundingType dimension_rounding_type () const
Get Dimension rounding type.
Detailed Description
Attributes are backend-agnostic parameters (in addition to the input/output tensors) of an operator.
Depthwise Conv2d attributes
Definition at line 42 of file DepthwiseConv2dAttributes.h.
Member Function Documentation
depth_multiplier() [1/2]
uint32_t depth_multiplier () const
Get depth multiplier.
Definition at line 67 of file DepthwiseConv2dAttributes.cpp.
 {
     return _depth_multiplier;
 }
Referenced by DepthwiseConv2dAttributes::depth_multiplier().
depth_multiplier() [2/2]
DepthwiseConv2dAttributes & depth_multiplier (const uint32_t & depth_multiplier)
Set depth multiplier.
Definition at line 61 of file DepthwiseConv2dAttributes.cpp.
 {
     _depth_multiplier = depth_multiplier;
     return *this;
 }
References DepthwiseConv2dAttributes::depth_multiplier().
Referenced by GpuDepthwiseConv2d::create_op(), ClTemplateDepthwiseConv2d::get_build_options(), ClTemplateDepthwiseConv2d::get_tag_lut(), arm_compute::operator<<(), ClComponentDepthwiseConv2d::validate(), and GpuCkwDepthwiseConv2d::write_component_code().
dilation() [1/2]
Size2D dilation () const
Get dilation.
Definition at line 56 of file DepthwiseConv2dAttributes.cpp.
 {
     return _dilation;
 }
Referenced by DepthwiseConv2dAttributes::dilation().
dilation() [2/2]
DepthwiseConv2dAttributes & dilation (const Size2D & dilation)
Set dilation.
Definition at line 51 of file DepthwiseConv2dAttributes.cpp.
 {
     _dilation = dilation;
     return *this;
 }
References DepthwiseConv2dAttributes::dilation().
Referenced by GpuDepthwiseConv2d::create_op(), ClTemplateDepthwiseConv2d::get_tag_lut(), arm_compute::operator<<(), and ClComponentDepthwiseConv2d::validate().
dimension_rounding_type() [1/2]
DimensionRoundingType dimension_rounding_type () const
Get Dimension rounding type.
Definition at line 79 of file DepthwiseConv2dAttributes.cpp.
 {
     return _dimension_rounding_type;
 }
Referenced by DepthwiseConv2dAttributes::dimension_rounding_type().
dimension_rounding_type() [2/2]
DepthwiseConv2dAttributes & dimension_rounding_type (const DimensionRoundingType & dimension_rounding_type)
Set Dimension rounding type.
Definition at line 73 of file DepthwiseConv2dAttributes.cpp.
 {
     _dimension_rounding_type = dimension_rounding_type;
     return *this;
 }
References DepthwiseConv2dAttributes::dimension_rounding_type().
Referenced by arm_compute::operator<<(), and ClComponentDepthwiseConv2d::validate().
pad() [1/2]
Padding2D pad () const
Get padding.
Definition at line 38 of file DepthwiseConv2dAttributes.cpp.
 {
     return _pad;
 }
Referenced by DepthwiseConv2dAttributes::pad().
pad() [2/2]
DepthwiseConv2dAttributes & pad (const Padding2D & pad)
Set padding.
Definition at line 33 of file DepthwiseConv2dAttributes.cpp.
 {
     _pad = pad;
     return *this;
 }
References DepthwiseConv2dAttributes::pad().
Referenced by GpuDepthwiseConv2d::create_op(), ClTemplateDepthwiseConv2d::get_tag_lut(), arm_compute::operator<<(), ClComponentDepthwiseConv2d::validate(), and GpuCkwDepthwiseConv2d::write_component_code().
stride() [1/2]
Size2D stride () const
Get stride.
Definition at line 47 of file DepthwiseConv2dAttributes.cpp.
 {
     return _stride;
 }
Referenced by DepthwiseConv2dAttributes::stride().
stride() [2/2]
DepthwiseConv2dAttributes & stride (const Size2D & stride)
Set stride.
Definition at line 42 of file DepthwiseConv2dAttributes.cpp.
 {
     _stride = stride;
     return *this;
 }
References DepthwiseConv2dAttributes::stride().
Referenced by GpuDepthwiseConv2d::create_op(), ClTemplateDepthwiseConv2d::get_tag_lut(), arm_compute::operator<<(), ClComponentDepthwiseConv2d::validate(), and GpuCkwDepthwiseConv2d::write_component_code().
The documentation for this class was generated from the following files:
arm_compute/dynamic_fusion/sketch/attributes/DepthwiseConv2dAttributes.h
src/dynamic_fusion/sketch/attributes/DepthwiseConv2dAttributes.cpp