Compute Library: NEArithmeticSubtraction Class Reference
NEArithmeticSubtraction Class Reference
Basic function to run cpu::kernels::CpuSubKernel.
#include <NEArithmeticSubtraction.h>
Public Member Functions
NEArithmeticSubtraction ()
Default Constructor.
~NEArithmeticSubtraction ()
Default Destructor.
NEArithmeticSubtraction (const NEArithmeticSubtraction &)=delete
Prevent instances of this class from being copied (As this class contains pointers)
NEArithmeticSubtraction (NEArithmeticSubtraction &&)
Default move constructor.
NEArithmeticSubtraction & operator= (const NEArithmeticSubtraction &)=delete
Prevent instances of this class from being copied (As this class contains pointers)
NEArithmeticSubtraction & operator= (NEArithmeticSubtraction &&)
Default move assignment operator.
void configure (const ITensor *input1, const ITensor *input2, ITensor *output, ConvertPolicy policy, const ActivationLayerInfo &act_info=ActivationLayerInfo())
Initialise the kernel's inputs, output and conversion policy.
void run () override
Run the kernels contained in the function.
Public Member Functions inherited from IFunction
virtual ~IFunction ()=default
Destructor.
virtual void prepare ()
Prepare the function for executing.
Static Public Member Functions
static Status validate (const ITensorInfo *input1, const ITensorInfo *input2, const ITensorInfo *output, ConvertPolicy policy, const ActivationLayerInfo &act_info=ActivationLayerInfo())
Static function to check if given info will lead to a valid configuration of NEArithmeticSubtraction.
Detailed Description
Basic function to run cpu::kernels::CpuSubKernel.
Note
The tensor data type for the inputs must be U8/QASYMM8/S16/S32/F16/F32.
The function performs an arithmetic subtraction between two tensors.
This function calls the following kernels:
cpu::kernels::CpuSubKernel
Definition at line 44 of file NEArithmeticSubtraction.h.
Constructor & Destructor Documentation
NEArithmeticSubtraction() [1/3]
NEArithmeticSubtraction ()
Default Constructor.
Definition at line 42 of file NEArithmeticSubtraction.cpp.
                                                  : _impl(std::make_unique<Impl>())
 {
 }
~NEArithmeticSubtraction()
~NEArithmeticSubtraction () default
Default Destructor.
NEArithmeticSubtraction() [2/3]
NEArithmeticSubtraction (const NEArithmeticSubtraction &) delete
Prevent instances of this class from being copied (As this class contains pointers)
NEArithmeticSubtraction() [3/3]
NEArithmeticSubtraction (NEArithmeticSubtraction &&) default
Default move constructor.
Member Function Documentation
configure()
void configure (const ITensor * input1, const ITensor * input2, ITensor * output, ConvertPolicy policy, const ActivationLayerInfo & act_info = ActivationLayerInfo())
Initialise the kernel's inputs, output and conversion policy.
Valid data layouts:
All
Valid data type configurations:
src0 src1 dst
QASYMM8 QASYMM8 QASYMM8
QASYMM8_SIGNED QASYMM8_SIGNED QASYMM8_SIGNED
QSYMM16 QSYMM16 QASYMM16
QSYMM16 QSYMM16 S32
U8 U8 U8
S16 S16 S16
S32 S32 S32
F16 F16 F16
F32 F32 F32
Parameters
[in] input1 First tensor input. Data types supported: U8/QASYMM8/QASYMM8_SIGNED/QSYMM16/S16/S32/F16/F32
[in] input2 Second tensor input. Data types supported: U8/QASYMM8/QASYMM8_SIGNED/QSYMM16/S16/S32/F16/F32
[out] output Output tensor. Data types supported: U8/QASYMM8/QASYMM8_SIGNED/QSYMM16/S16/S32/F16/F32
[in] policy Policy to use to handle overflow. Convert policy cannot be WRAP if datatype is quantized.
[in] act_info (Optional) Activation layer information in case of a fused activation. Currently not supported.
Definition at line 58 of file NEArithmeticSubtraction.cpp.
 {
     _impl->src_0 = input1;
     _impl->src_1 = input2;
     _impl->dst   = output;
     _impl->op    = std::make_unique<cpu::CpuSub>();
     _impl->op->configure(input1->info(), input2->info(), output->info(), policy, act_info);
 }
References arm_compute::test::validation::act_info, and ITensor::info().
Referenced by NELSTMLayer::configure(), and NEQLSTMLayer::configure().
operator=() [1/2]
NEArithmeticSubtraction& operator= (const NEArithmeticSubtraction &) delete
Prevent instances of this class from being copied (As this class contains pointers)
operator=() [2/2]
NEArithmeticSubtraction & operator= (NEArithmeticSubtraction &&) default
Default move assignment operator.
run()
void run () override virtual
Run the kernels contained in the function.
For CPU kernels:
Multi-threading is used for the kernels which are parallelisable.
By default std::thread::hardware_concurrency() threads are used.
Note
CPPScheduler::set_num_threads() can be used to manually set the number of threads
For OpenCL kernels:
All the kernels are enqueued on the queue associated with CLScheduler.
The queue is then flushed.
Note
The function will not block until the kernels are executed. It is the user's responsibility to wait.
Will call prepare() on first run if hasn't been done
Implements IFunction.
Definition at line 71 of file NEArithmeticSubtraction.cpp.
 {
     ITensorPack pack;
     pack.add_tensor(TensorType::ACL_SRC_0, _impl->src_0);
     pack.add_tensor(TensorType::ACL_SRC_1, _impl->src_1);
     pack.add_tensor(TensorType::ACL_DST, _impl->dst);
     _impl->op->run(pack);
 }
References arm_compute::ACL_DST, arm_compute::ACL_SRC_0, arm_compute::ACL_SRC_1, ITensorPack::add_tensor(), and arm_compute::test::validation::pack.
Referenced by NELSTMLayer::run(), and NEQLSTMLayer::run().
validate()
Status validate (const ITensorInfo * input1, const ITensorInfo * input2, const ITensorInfo * output, ConvertPolicy policy, const ActivationLayerInfo & act_info = ActivationLayerInfo()) static
Static function to check if given info will lead to a valid configuration of NEArithmeticSubtraction.
Parameters
[in] input1 First tensor input. Data types supported: U8/QASYMM8/QASYMM8_SIGNED/S16/S32/F16/F32
[in] input2 Second tensor input. Data types supported: U8/QASYMM8/QASYMM8_SIGNED/S16/S32/F16/F32
[in] output Output tensor. Data types supported: U8/QASYMM8/QASYMM8_SIGNED/S16/S32/F16/F32
[in] policy Policy to use to handle overflow. Convert policy cannot be WRAP if datatype is quantized.
[in] act_info (Optional) Activation layer information in case of a fused activation. Currently not supported.
Returns
a status
Definition at line 49 of file NEArithmeticSubtraction.cpp.
 {
     return cpu::CpuSub::validate(input1, input2, output, policy, act_info);
 }
References arm_compute::test::validation::act_info, and CpuSub::validate().
Referenced by NELSTMLayer::validate(), and NEQLSTMLayer::validate().
The documentation for this class was generated from the following files:
arm_compute/runtime/NEON/functions/NEArithmeticSubtraction.h
src/runtime/NEON/functions/NEArithmeticSubtraction.cpp