Compute Library: ClMatMul Class Reference
ClMatMul Class Reference
Basic operator to execute BatchMatMul on OpenCL.
#include <ClMatMul.h>
Public Member Functions
ClMatMul ()
Constructor.
~ClMatMul ()=default
Default destructor.
void configure (const CLCompileContext &compile_context, ITensorInfo *lhs, ITensorInfo *rhs, ITensorInfo *dst, const MatMulInfo &matmul_info, const ActivationLayerInfo &act_info=ActivationLayerInfo())
Initialise the kernel's inputs and output.
void run (ITensorPack &tensors) override
Run the kernels contained in the function.
Public Member Functions inherited from ICLOperator
ICLOperator (IRuntimeContext *ctx=nullptr)
Constructor.
ICLOperator (const ICLOperator &)=delete
Prevent instances of this class from being copied (As this class contains pointers)
ICLOperator (ICLOperator &&)=default
Default move constructor.
ICLOperator & operator= (const ICLOperator &)=delete
Prevent instances of this class from being copied (As this class contains pointers)
ICLOperator & operator= (ICLOperator &&)=default
Default move assignment operator.
void prepare (ITensorPack &constants) override
Prepare the function for executing.
MemoryRequirements workspace () const override
Return the memory requirements required by the workspace.
Public Member Functions inherited from IOperator
virtual ~IOperator ()=default
Destructor.
Static Public Member Functions
static Status validate (const ITensorInfo *lhs, const ITensorInfo *rhs, const ITensorInfo *dst, const MatMulInfo &matmul_info, const ActivationLayerInfo &act_info=ActivationLayerInfo())
Static function to check if given info will lead to a valid configuration.
Detailed Description
Basic operator to execute BatchMatMul on OpenCL.
This operator calls the following OpenCL kernels:
kernels::ClMatMulNativeKernel
Definition at line 43 of file ClMatMul.h.
Constructor & Destructor Documentation
ClMatMul()
ClMatMul ()
Constructor.
Definition at line 48 of file ClMatMul.cpp.
 {
 }
~ClMatMul()
~ClMatMul () default
Default destructor.
Member Function Documentation
configure()
void configure (const CLCompileContext & compile_context, ITensorInfo * lhs, ITensorInfo * rhs, ITensorInfo * dst, const MatMulInfo & matmul_info, const ActivationLayerInfo & act_info = ActivationLayerInfo())
Initialise the kernel's inputs and output.
Valid data layouts:
All
Valid data type configurations:
lhs rhs dst
F32 F32 F32
F16 F16 F16
QASYMM8_SIGNED QASYMM8_SIGNED QASYMM8_SIGNED
QASYMM8 QASYMM8 QASYMM8
Note
BatchMatMul: Batched Matrix Multiply - [A * B], Multiplies all slices (slice is an element of a batch) of Tensors A and B and stores the result in the dst tensor of the same batch size. Batch here is number of slices from A and B multiplied at a time, do not confuse with the batch dimension 'N' of NHWC/NCHW For NHWC for example: the batch is the higher dimensions H * N, and in general it is H * all higher dimensions.
All tensors must have the same data type.
Parameters
[in] compile_context The compile context to be used.
[in] lhs Left-hand side tensor info. Data types supported: F16/F32/QASYMM8_SIGNED/QASYMM8.
[in] rhs Right-hand side tensor info. Data types supported: same as lhs.
[out] dst Output tensor to store the result of the batched matrix multiplication. Data types supported: same as lhs.
[in] matmul_info Contains MatMul operation information described in MatMulInfo.
[in] act_info Class containing information about fused activation function.
Definition at line 88 of file ClMatMul.cpp.
 {
     ARM_COMPUTE_ERROR_ON_NULLPTR(lhs, rhs, dst);
     ARM_COMPUTE_LOG_PARAMS(lhs, rhs, dst, matmul_info);
     // Perform validation step
     ARM_COMPUTE_ERROR_THROW_ON(validate(lhs, rhs, dst, matmul_info));
     const GPUTarget        gpu_target    = CLScheduler::get().target();
     const auto             kernel_config = ClMatMulNativeKernelConfigurationFactory::create(gpu_target);
     const MatMulKernelInfo kernel_info   = kernel_config->configure(lhs, rhs, matmul_info);
     const auto             kernel_selector = ClMatMulNativeKernelVariantFactory::create(gpu_target);
     const MatMulKernelType kernel_type     = kernel_selector->select_kernel(lhs, rhs, matmul_info, act_info);
     switch (kernel_type)
     {
         case MatMulKernelType::NATIVE_FP:
         {
             auto kernel = std::make_unique<ClMatMulNativeKernel>();
             kernel->set_target(gpu_target);
             kernel->configure(compile_context, lhs, rhs, nullptr /* bias */, dst, kernel_info, act_info);
             _matmul_kernel = std::move(kernel);
         }
         break;
         case MatMulKernelType::NATIVE_MMUL_FP:
         {
             auto kernel = std::make_unique<ClMatMulNativeMMULKernel>();
             kernel->set_target(gpu_target);
             kernel->configure(compile_context, lhs, rhs, nullptr /* bias */, dst, kernel_info);
             _matmul_kernel = std::move(kernel);
         }
         break;
         case MatMulKernelType::NATIVE_QUANTIZED:
         {
             auto kernel = std::make_unique<ClMatMulLowpNativeKernel>();
             kernel->set_target(gpu_target);
             kernel->configure(compile_context, lhs, rhs, nullptr /* bias */, dst, kernel_info, act_info);
             _matmul_kernel = std::move(kernel);
         }
         break;
         case MatMulKernelType::NATIVE_MMUL_QUANTIZED:
         {
             auto kernel = std::make_unique<ClMatMulLowpNativeMMULKernel>();
             kernel->set_target(gpu_target);
             kernel->configure(compile_context, lhs, rhs, nullptr /* bias */, dst, kernel_info, act_info);
             _matmul_kernel = std::move(kernel);
         }
         break;
         default:
             ARM_COMPUTE_ERROR("Unsupported MatMul Kernel!");
     }
 }
References arm_compute::test::validation::act_info, ARM_COMPUTE_ERROR, ARM_COMPUTE_ERROR_ON_NULLPTR, ARM_COMPUTE_ERROR_THROW_ON, ARM_COMPUTE_LOG_PARAMS, ClMatMulNativeKernelConfigurationFactory::create(), ClMatMulNativeKernelVariantFactory::create(), arm_compute::test::validation::dst, CLScheduler::get(), arm_compute::cl_matmul::NATIVE_FP, arm_compute::cl_matmul::NATIVE_MMUL_FP, arm_compute::cl_matmul::NATIVE_MMUL_QUANTIZED, arm_compute::cl_matmul::NATIVE_QUANTIZED, CLScheduler::target(), and arm_compute::validate().
run()
void run (ITensorPack & tensors) override virtual
Run the kernels contained in the function.
Parameters
[in] tensors Vector that contains the tensors to operate on.
Reimplemented from ICLOperator.
Definition at line 151 of file ClMatMul.cpp.
 {
     CLScheduler::get().enqueue_op(*_matmul_kernel, tensors, /* flush */ true);
 }
References CLScheduler::enqueue_op(), and CLScheduler::get().
validate()
Status validate (const ITensorInfo * lhs, const ITensorInfo * rhs, const ITensorInfo * dst, const MatMulInfo & matmul_info, const ActivationLayerInfo & act_info = ActivationLayerInfo()) static
Static function to check if given info will lead to a valid configuration.
Similar to ClMatMul::configure()
Returns
a status
Definition at line 52 of file ClMatMul.cpp.
 {
     ARM_COMPUTE_RETURN_ERROR_ON_NULLPTR(lhs, rhs, dst);
     ARM_COMPUTE_RETURN_ERROR_ON_DATA_TYPE_CHANNEL_NOT_IN(lhs, 1, DataType::QASYMM8, DataType::QASYMM8_SIGNED,
                                                          DataType::F16, DataType::F32);
     ARM_COMPUTE_RETURN_ERROR_ON_DATA_TYPE_CHANNEL_NOT_IN(rhs, 1, DataType::QASYMM8, DataType::QASYMM8_SIGNED,
                                                          DataType::F16, DataType::F32);
     const GPUTarget gpu_target = CLScheduler::get().target();
     std::unique_ptr<IClMatMulNativeKernelConfig> t = ClMatMulNativeKernelConfigurationFactory::create(gpu_target);
     const MatMulKernelInfo kernel_info = t->configure(lhs, rhs, matmul_info);
     const auto             kernel_selector = ClMatMulNativeKernelVariantFactory::create(gpu_target);
     const MatMulKernelType kernel_type     = kernel_selector->select_kernel(lhs, rhs, matmul_info, act_info);
     switch (kernel_type)
     {
         case MatMulKernelType::NATIVE_FP:
             return ClMatMulNativeKernel::validate(lhs, rhs, nullptr /* bias */, dst, kernel_info, act_info);
         case MatMulKernelType::NATIVE_MMUL_FP:
             return ClMatMulNativeMMULKernel::validate(lhs, rhs, nullptr /* bias */, dst, kernel_info);
         case MatMulKernelType::NATIVE_QUANTIZED:
             return ClMatMulLowpNativeKernel::validate(lhs, rhs, nullptr /* bias */, dst, kernel_info, act_info);
         case MatMulKernelType::NATIVE_MMUL_QUANTIZED:
             return ClMatMulLowpNativeMMULKernel::validate(lhs, rhs, nullptr /* bias */, dst, kernel_info, act_info);
         default:
             ARM_COMPUTE_ERROR("Unsupported MatMul Kernel!");
     }
 }
References arm_compute::test::validation::act_info, ARM_COMPUTE_ERROR, ARM_COMPUTE_RETURN_ERROR_ON_DATA_TYPE_CHANNEL_NOT_IN, ARM_COMPUTE_RETURN_ERROR_ON_NULLPTR, ClMatMulNativeKernelConfigurationFactory::create(), ClMatMulNativeKernelVariantFactory::create(), arm_compute::test::validation::dst, arm_compute::F16, arm_compute::F32, CLScheduler::get(), arm_compute::cl_matmul::NATIVE_FP, arm_compute::cl_matmul::NATIVE_MMUL_FP, arm_compute::cl_matmul::NATIVE_MMUL_QUANTIZED, arm_compute::cl_matmul::NATIVE_QUANTIZED, arm_compute::QASYMM8, arm_compute::QASYMM8_SIGNED, tf_frozen_model_extractor::t, CLScheduler::target(), ClMatMulLowpNativeMMULKernel::validate(), ClMatMulNativeKernel::validate(), ClMatMulLowpNativeKernel::validate(), and ClMatMulNativeMMULKernel::validate().
The documentation for this class was generated from the following files:
src/gpu/cl/operators/ClMatMul.h
src/gpu/cl/operators/ClMatMul.cpp