Compute Library: CLFFT2D Class Reference
CLFFT2D Class Reference
Basic function to execute two dimensional FFT.
#include <CLFFT2D.h>
Public Member Functions
CLFFT2D (std::shared_ptr< IMemoryManager > memory_manager=nullptr)
Default Constructor.
CLFFT2D (const CLFFT2D &)=delete
Prevent instances of this class from being copied.
CLFFT2D & operator= (const CLFFT2D &)=delete
Prevent instances of this class from being copied.
CLFFT2D (CLFFT2D &&)=default
Default move constructor.
CLFFT2D & operator= (CLFFT2D &&)=default
Default move assignment operator.
~CLFFT2D ()
Default destructor.
void configure (const ICLTensor *input, ICLTensor *output, const FFT2DInfo &config)
Initialise the function's source, destinations and border mode.
void configure (const CLCompileContext &compile_context, const ICLTensor *input, ICLTensor *output, const FFT2DInfo &config)
Initialise the function's source, destinations and border mode.
void run () override
Run the kernels contained in the function.
Public Member Functions inherited from IFunction
virtual ~IFunction ()=default
Destructor.
virtual void prepare ()
Prepare the function for executing.
Static Public Member Functions
static Status validate (const ITensorInfo *input, const ITensorInfo *output, const FFT2DInfo &config)
Static function to check if given info will lead to a valid configuration of CLFFT2D.
Detailed Description
Basic function to execute two dimensional FFT.
This function calls the following OpenCL kernels:
CLFFT1D 1D FFT is performed on the first given axis
CLFFT1D 1D FFT is performed on the second given axis
Definition at line 43 of file CLFFT2D.h.
Constructor & Destructor Documentation
CLFFT2D() [1/3]
CLFFT2D (std::shared_ptr< IMemoryManager > memory_manager = nullptr)
Default Constructor.
Definition at line 37 of file CLFFT2D.cpp.
     : _memory_group(memory_manager),
       _first_pass_func(memory_manager),
       _second_pass_func(memory_manager),
       _first_pass_tensor()
 {
 }
CLFFT2D() [2/3]
CLFFT2D (const CLFFT2D &) delete
Prevent instances of this class from being copied.
CLFFT2D() [3/3]
CLFFT2D (CLFFT2D &&) default
Default move constructor.
~CLFFT2D()
~CLFFT2D () default
Default destructor.
Member Function Documentation
configure() [1/2]
void configure (const CLCompileContext & compile_context, const ICLTensor * input, ICLTensor * output, const FFT2DInfo & config)
Initialise the function's source, destinations and border mode.
Parameters
[in] compile_context The compile context to be used.
[in] input Source tensor. Data types supported: F16/F32.
[out] output Destination tensor. Data types and data layouts supported: Same as input.
[in] config FFT related configuration
Definition at line 52 of file CLFFT2D.cpp.
 {
     ARM_COMPUTE_ERROR_ON_NULLPTR(input, output);
     ARM_COMPUTE_ERROR_THROW_ON(CLFFT2D::validate(input->info(), output->info(), config));
     ARM_COMPUTE_LOG_PARAMS(input, output, config);
     // Setup first pass
     FFT1DInfo first_pass_config;
     first_pass_config.axis      = config.axis0;
     first_pass_config.direction = config.direction;
     _memory_group.manage(&_first_pass_tensor);
     _first_pass_func.configure(compile_context, input, &_first_pass_tensor, first_pass_config);
     // Setup second pass
     FFT1DInfo second_pass_config;
     second_pass_config.axis      = config.axis1;
     second_pass_config.direction = config.direction;
     _second_pass_func.configure(compile_context, &_first_pass_tensor, output, second_pass_config);
     _first_pass_tensor.allocator()->allocate();
 }
References CLTensorAllocator::allocate(), CLTensor::allocator(), ARM_COMPUTE_ERROR_ON_NULLPTR, ARM_COMPUTE_ERROR_THROW_ON, ARM_COMPUTE_LOG_PARAMS, FFT1DInfo::axis, FFT2DInfo::axis0, FFT2DInfo::axis1, CLFFT1D::configure(), FFT1DInfo::direction, FFT2DInfo::direction, ITensor::info(), arm_compute::test::validation::input, MemoryGroup::manage(), and CLFFT2D::validate().
configure() [2/2]
void configure (const ICLTensor * input, ICLTensor * output, const FFT2DInfo & config)
Initialise the function's source, destinations and border mode.
Valid data layouts:
All
Valid data type configurations:
src dst
F32 F32
F16 F16
Parameters
[in] input Source tensor. Data types supported: F16/F32.
[out] output Destination tensor. Data types and data layouts supported: Same as input.
[in] config FFT related configuration
Definition at line 47 of file CLFFT2D.cpp.
 {
     configure(CLKernelLibrary::get().get_compile_context(), input, output, config);
 }
References CLKernelLibrary::get(), and arm_compute::test::validation::input.
Referenced by CLFFTConvolutionLayer::configure().
operator=() [1/2]
CLFFT2D& operator= (CLFFT2D &&) default
Default move assignment operator.
operator=() [2/2]
CLFFT2D& operator= (const CLFFT2D &) delete
Prevent instances of this class from being copied.
run()
void run () override virtual
Run the kernels contained in the function.
For CPU kernels:
Multi-threading is used for the kernels which are parallelisable.
By default std::thread::hardware_concurrency() threads are used.
Note
CPPScheduler::set_num_threads() can be used to manually set the number of threads
For OpenCL kernels:
All the kernels are enqueued on the queue associated with CLScheduler.
The queue is then flushed.
Note
The function will not block until the kernels are executed. It is the user's responsibility to wait.
Will call prepare() on first run if hasn't been done
Implements IFunction.
Definition at line 106 of file CLFFT2D.cpp.
 {
     MemoryGroupResourceScope scope_mg(_memory_group);
     _first_pass_func.run();
     _second_pass_func.run();
 }
References CLFFT1D::run().
Referenced by CLFFTConvolutionLayer::run().
validate()
Status validate (const ITensorInfo * input, const ITensorInfo * output, const FFT2DInfo & config) static
Static function to check if given info will lead to a valid configuration of CLFFT2D.
Parameters
[in] input Source tensor info. Data types supported: F16/F32.
[in] output Destination tensor info. Data types and data layouts supported: Same as input.
[in] config FFT related configuration
Returns
a status
Definition at line 76 of file CLFFT2D.cpp.
 {
     ARM_COMPUTE_RETURN_ERROR_ON_NULLPTR(input, output);
     ARM_COMPUTE_RETURN_ERROR_ON_DATA_TYPE_NOT_IN(input, DataType::F16, DataType::F32);
     // Create intermediate tensor info
     TensorInfo first_pass_tensor(input->clone()->set_is_resizable(true).reset_padding().set_num_channels(2));
     // Validate first pass
     FFT1DInfo first_pass_config;
     first_pass_config.axis      = config.axis0;
     first_pass_config.direction = config.direction;
     ARM_COMPUTE_RETURN_ON_ERROR(CLFFT1D::validate(input, &first_pass_tensor, first_pass_config));
     // Validate second pass
     FFT1DInfo second_pass_config;
     second_pass_config.axis      = config.axis1;
     second_pass_config.direction = config.direction;
     ARM_COMPUTE_RETURN_ON_ERROR(CLFFT1D::validate(&first_pass_tensor, output, second_pass_config));
     // Checks performed when output is configured
     if ((output != nullptr) && (output->total_size() != 0))
     {
         ARM_COMPUTE_RETURN_ERROR_ON_MISMATCHING_SHAPES(input, output);
         ARM_COMPUTE_RETURN_ERROR_ON_MISMATCHING_DATA_TYPES(input, output);
     }
     return Status{};
 }
References ARM_COMPUTE_RETURN_ERROR_ON_DATA_TYPE_NOT_IN, ARM_COMPUTE_RETURN_ERROR_ON_MISMATCHING_DATA_TYPES, ARM_COMPUTE_RETURN_ERROR_ON_MISMATCHING_SHAPES, ARM_COMPUTE_RETURN_ERROR_ON_NULLPTR, ARM_COMPUTE_RETURN_ON_ERROR, FFT1DInfo::axis, FFT2DInfo::axis0, FFT2DInfo::axis1, FFT1DInfo::direction, FFT2DInfo::direction, arm_compute::F16, arm_compute::F32, arm_compute::test::validation::input, ITensorInfo::total_size(), and CLFFT1D::validate().
Referenced by CLFFT2D::configure().
The documentation for this class was generated from the following files:
arm_compute/runtime/CL/functions/CLFFT2D.h
src/runtime/CL/functions/CLFFT2D.cpp