Compute Library: InPlaceOperationMutator Class Reference
InPlaceOperationMutator Class Reference final
Mutation pass to optimize operations that can be performed in-place.
#include <InPlaceOperationMutator.h>
Public Member Functions
virtual void mutate (Graph &g) override
Walk the graph and perform a specific mutation.
MutationType type () const override
Returns mutation type.
const char * name () override
Returns mutator name.
Public Member Functions inherited from IGraphMutator
virtual ~IGraphMutator ()=default
Virtual Destructor.
Additional Inherited Members
Public Types inherited from IGraphMutator
enum MutationType { IR, Backend }
Mutation type.
Detailed Description
Mutation pass to optimize operations that can be performed in-place.
Definition at line 34 of file InPlaceOperationMutator.h.
Member Function Documentation
mutate()
void mutate (Graph & g) override virtual
Walk the graph and perform a specific mutation.
Parameters
[in,out] g Graph to walk and mutate
Implements IGraphMutator.
Definition at line 223 of file InPlaceOperationMutator.cpp.
 {
     std::set<NodeType> in_place_nodes = {NodeType::ActivationLayer,
                                          NodeType::BatchNormalizationLayer,
                                          NodeType::EltwiseLayer,
                                          NodeType::UnaryEltwiseLayer,
                                          NodeType::DepthwiseConvolutionLayer,
                                          NodeType::FusedDepthwiseConvolutionBatchNormalizationLayer,
                                          NodeType::PrintLayer};
     // Not interested in the order of nodes
     for (auto &node : g.nodes())
     {
         if (node && in_place_nodes.find(node->type()) != std::end(in_place_nodes))
         {
             // Get input edge
             Edge *input_edge = node->input_edge(0);
             // Check if parent has a single output if yes then force in place calculation else not
             if ((input_edge != nullptr) && output_edges_are_separate_tensors(g, input_edge))
             {
                 if (node->type() == NodeType::EltwiseLayer)
                 {
                     try_in_place_elementwise(node);
                 }
                 else if (node->type() == NodeType::FusedDepthwiseConvolutionBatchNormalizationLayer ||
                          node->type() == NodeType::DepthwiseConvolutionLayer)
                 {
                     try_in_place_depthwiseconv(node);
                 }
                 else
                 {
                     // Get current and new output tensors
                     auto current_output_tensor = node->output(0);
                     auto new_output_tensor     = input_edge->tensor();
                     ARM_COMPUTE_ERROR_ON(current_output_tensor == nullptr || new_output_tensor == nullptr);
                     // Prevent in-place operation if there is an accessor bound to the in-place tensor or quantization info are different
                     if (new_output_tensor->accessor() != nullptr ||
                         current_output_tensor->desc().quant_info != new_output_tensor->desc().quant_info)
                     {
                         ARM_COMPUTE_LOG_GRAPH_VERBOSE("Prevented in-place operation as there is an accessor bound to "
                                                       "the input tensor or the quantization info are different.\n");
                     }
                     else
                     {
                         set_new_output_and_inherit_accessor(node, current_output_tensor, new_output_tensor);
                     }
                 }
             }
         }
     }
 }
References ARM_COMPUTE_ERROR_ON, ARM_COMPUTE_LOG_GRAPH_VERBOSE, arm_compute::mlgo::parser::end(), Graph::nodes(), and Edge::tensor().
name()
const char * name () override virtual
Returns mutator name.
Returns
Mutator name
Implements IGraphMutator.
Definition at line 213 of file InPlaceOperationMutator.cpp.
 {
     return "InPlaceOperationMutator";
 }
type()
IGraphMutator::MutationType type () const override virtual
Returns mutation type.
Returns
Mutation type enumeration
Implements IGraphMutator.
Definition at line 218 of file InPlaceOperationMutator.cpp.
 {
     return IGraphMutator::MutationType::Backend;
 }
The documentation for this class was generated from the following files:
arm_compute/graph/mutators/InPlaceOperationMutator.h
src/graph/mutators/InPlaceOperationMutator.cpp