Compute Library: CpuArithmeticKernel Class Reference
CpuArithmeticKernel Class Reference
#include <CpuElementwiseKernel.h>
Public Member Functions
CpuArithmeticKernel ()=default
void configure (ArithmeticOperation op, const ITensorInfo *src0, const ITensorInfo *src1, ITensorInfo *dst)
Configure kernel.
size_t get_mws (const CPUInfo &platform, size_t thread_count) const override
Return minimum workload size of the relevant kernel.
Public Member Functions inherited from CpuElementwiseKernel< CpuArithmeticKernel >
CpuElementwiseKernel ()=default
ARM_COMPUTE_DISALLOW_COPY_ALLOW_MOVE (CpuElementwiseKernel)
void run_op (ITensorPack &tensors, const Window &window, const ThreadInfo &info) override
Execute the kernel on the passed window.
const char * name () const override
Name of the kernel.
Public Member Functions inherited from ICPPKernel
virtual ~ICPPKernel ()=default
Default destructor.
virtual void run (const Window &window, const ThreadInfo &info)
Execute the kernel on the passed window.
virtual void run_nd (const Window &window, const ThreadInfo &info, const Window &thread_locator)
legacy compatibility layer for implemantions which do not support thread_locator In these cases we simply narrow the interface down the legacy version
virtual const char * name () const =0
Name of the kernel.
Public Member Functions inherited from IKernel
IKernel ()
Constructor.
virtual ~IKernel ()=default
Destructor.
virtual bool is_parallelisable () const
Indicates whether or not the kernel is parallelisable.
virtual BorderSize border_size () const
The size of the border for that kernel.
const Window & window () const
The maximum window the kernel can be executed on.
bool is_window_configured () const
Function to check if the embedded window of this kernel has been configured.
Static Public Member Functions
static Status validate (ArithmeticOperation op, const ITensorInfo *src0, const ITensorInfo *src1, const ITensorInfo *dst)
Static function to check if given info will lead to a valid configuration.
static const std::vector< CpuElementwiseKernel< CpuArithmeticKernel >::ElementwiseKernel > & get_available_kernels ()
Static Public Member Functions inherited from ICpuKernel< CpuArithmeticKernel >
static const auto * get_implementation (const SelectorType &selector, KernelSelectionType selection_type=KernelSelectionType::Supported)
Micro-kernel selector.
Additional Inherited Members
Public Types inherited from CpuElementwiseKernel< CpuArithmeticKernel >
using ElementwiseFunction = void(const ITensor *, const ITensor *, ITensor *, const Window &)
Static Public Attributes inherited from ICPPKernel
static constexpr size_t default_mws = 1
Detailed Description
Definition at line 80 of file CpuElementwiseKernel.h.
Constructor & Destructor Documentation
CpuArithmeticKernel()
CpuArithmeticKernel () default
Member Function Documentation
configure()
void configure (ArithmeticOperation op, const ITensorInfo * src0, const ITensorInfo * src1, ITensorInfo * dst)
Configure kernel.
Arithmetic operators (min, max, squared_diff)
Parameters
[in] op Arithmetic operation to be executed.
[in] src0 First tensor input info. Data types supported: QASYMM8/S16/F16/S32/F32.
[in] src1 Second tensor input info. Data types supported: Same as src0.
[out] dst Output tensor info. Data types supported: Same as src0.
Definition at line 316 of file CpuElementwiseKernel.cpp.
 {
     ARM_COMPUTE_ERROR_THROW_ON(validate_arguments(*src0, *src1, *dst));
     _op = op;
     CpuArithmeticKernel::configure_common(src0, src1, dst);
 }
References ARM_COMPUTE_ERROR_THROW_ON, and arm_compute::test::validation::dst.
get_available_kernels()
const std::vector< CpuElementwiseKernel< CpuArithmeticKernel >::ElementwiseKernel > & get_available_kernels () static
Definition at line 176 of file CpuElementwiseKernel.cpp.
 {
     static std::vector<CpuElementwiseKernel<CpuArithmeticKernel>::ElementwiseKernel> available_kernels;
     std::move(available_kernels_arithmetic<ArithmeticOperation::ADD>.begin(),
               available_kernels_arithmetic<ArithmeticOperation::ADD>.end(), std::back_inserter(available_kernels));
     std::move(available_kernels_arithmetic<ArithmeticOperation::SUB>.begin(),
               available_kernels_arithmetic<ArithmeticOperation::SUB>.end(), std::back_inserter(available_kernels));
     std::move(available_kernels_arithmetic<ArithmeticOperation::DIV>.begin(),
               available_kernels_arithmetic<ArithmeticOperation::DIV>.end(), std::back_inserter(available_kernels));
     std::move(available_kernels_arithmetic<ArithmeticOperation::MIN>.begin(),
               available_kernels_arithmetic<ArithmeticOperation::MIN>.end(), std::back_inserter(available_kernels));
     std::move(available_kernels_arithmetic<ArithmeticOperation::MAX>.begin(),
               available_kernels_arithmetic<ArithmeticOperation::MAX>.end(), std::back_inserter(available_kernels));
     std::move(available_kernels_arithmetic<ArithmeticOperation::SQUARED_DIFF>.begin(),
               available_kernels_arithmetic<ArithmeticOperation::SQUARED_DIFF>.end(),
               std::back_inserter(available_kernels));
     std::move(available_kernels_arithmetic<ArithmeticOperation::POWER>.begin(),
               available_kernels_arithmetic<ArithmeticOperation::POWER>.end(), std::back_inserter(available_kernels));
     std::move(available_kernels_arithmetic<ArithmeticOperation::PRELU>.begin(),
               available_kernels_arithmetic<ArithmeticOperation::PRELU>.end(), std::back_inserter(available_kernels));
     return available_kernels;
 }
References arm_compute::mlgo::parser::end().
get_mws()
size_t get_mws (const CPUInfo & platform, size_t thread_count) const override virtual
Return minimum workload size of the relevant kernel.
Parameters
[in] platform The CPU platform used to create the context.
[in] thread_count Number of threads in the execution.
Returns
[out] mws Minimum workload size for requested configuration.
Reimplemented from ICPPKernel.
Reimplemented in CpuDivisionKernel.
Definition at line 349 of file CpuElementwiseKernel.cpp.
 {
     ARM_COMPUTE_UNUSED(thread_count);
 #if defined(ENABLE_FP32_KERNELS)
     if (this->_run_method == &neon_fp32_elementwise_binary<ArithmeticOperation::MIN> ||
         this->_run_method == &neon_fp32_elementwise_binary<ArithmeticOperation::MAX>)
     {
         size_t mws = ICPPKernel::default_mws;
         if (platform.get_cpu_model() == CPUModel::N1)
         {
             mws = default_min_max_mws_N1_fp32_neon;
         }
         else if (platform.get_cpu_model() == CPUModel::V1)
         {
             mws = default_min_max_mws_V1_fp32_neon;
         }
         else
         {
             return ICPPKernel::default_mws;
         }
         // tensor is 1D or was re-interpreted as 1D
         if (this->window().shape().num_dimensions() == 1)
         {
             return mws;
         }
         else
         {
             // scale mws down by the number of elements along all the dimensions (x, z, w, etc) except the one
             // that we parallelize along (the y dimension). This allows for parallelization when the Y_SIZE is small
             // but the other sizes are large, which boosts performance.
             mws = static_cast<size_t>(mws / (this->window().num_iterations_total() / this->window().num_iterations(1)));
             return std::max(static_cast<size_t>(1), mws);
         }
     }
 #else  /* ENABLE_FP32_KERNELS */
     ARM_COMPUTE_UNUSED(platform);
 #endif /* ENABLE_FP32_KERNELS */
     return ICPPKernel::default_mws;
 }
References ARM_COMPUTE_UNUSED, ICPPKernel::default_mws, CPUInfo::get_cpu_model(), arm_compute::N1, Window::num_iterations(), Window::num_iterations_total(), arm_compute::test::validation::shape, arm_compute::V1, and IKernel::window().
validate()
Status validate (ArithmeticOperation op, const ITensorInfo * src0, const ITensorInfo * src1, const ITensorInfo * dst) static
Static function to check if given info will lead to a valid configuration.
Similar to CpuArithmeticKernel::configure()
Returns
a status
Definition at line 338 of file CpuElementwiseKernel.cpp.
 {
     ARM_COMPUTE_UNUSED(op);
     ARM_COMPUTE_RETURN_ERROR_ON_NULLPTR(src0, src1, dst);
     ARM_COMPUTE_RETURN_ON_ERROR(validate_arguments(*src0, *src1, *dst));
     return Status{};
 }
References ARM_COMPUTE_RETURN_ERROR_ON_NULLPTR, ARM_COMPUTE_RETURN_ON_ERROR, ARM_COMPUTE_UNUSED, and arm_compute::test::validation::dst.
Referenced by CpuElementwiseArithmetic< op >::validate().
The documentation for this class was generated from the following files:
src/cpu/kernels/CpuElementwiseKernel.h
src/cpu/kernels/CpuElementwiseKernel.cpp