Compute Library: NEReshapeLayer Class Reference
NEReshapeLayer Class Reference
Basic function to run cpu::kernels::CpuReshapeKernel.
#include <NEReshapeLayer.h>
Public Member Functions
NEReshapeLayer ()
Default Constructor.
~NEReshapeLayer ()
Default Destructor.
NEReshapeLayer (const NEReshapeLayer &)=delete
Prevent instances of this class from being copied (As this class contains pointers)
NEReshapeLayer (NEReshapeLayer &&)
Default move constructor.
NEReshapeLayer & operator= (const NEReshapeLayer &)=delete
Prevent instances of this class from being copied (As this class contains pointers)
NEReshapeLayer & operator= (NEReshapeLayer &&)
Default move assignment operator.
void configure (const ITensor *input, ITensor *output)
Initialise the kernel's inputs and outputs.
void run () override
Run the kernels contained in the function.
Public Member Functions inherited from IFunction
virtual ~IFunction ()=default
Destructor.
virtual void prepare ()
Prepare the function for executing.
Static Public Member Functions
static Status validate (const ITensorInfo *input, const ITensorInfo *output)
Static function to check if given info will lead to a valid configuration of NEReshapeLayer.
Detailed Description
Basic function to run cpu::kernels::CpuReshapeKernel.
Definition at line 38 of file NEReshapeLayer.h.
Constructor & Destructor Documentation
NEReshapeLayer() [1/3]
NEReshapeLayer ()
Default Constructor.
Definition at line 41 of file NEReshapeLayer.cpp.
                                : _impl(std::make_unique<Impl>())
 {
 }
~NEReshapeLayer()
~NEReshapeLayer () default
Default Destructor.
NEReshapeLayer() [2/3]
NEReshapeLayer (const NEReshapeLayer &) delete
Prevent instances of this class from being copied (As this class contains pointers)
NEReshapeLayer() [3/3]
NEReshapeLayer (NEReshapeLayer &&) default
Default move constructor.
Member Function Documentation
configure()
void configure (const ITensor * input, ITensor * output)
Initialise the kernel's inputs and outputs.
Valid data layouts:
All
Valid data type configurations:
src dst
All All
Parameters
[in] input Input tensor. Data type supported: All
[out] output Output tensor. Data type supported: Same as input
Definition at line 48 of file NEReshapeLayer.cpp.
 {
     ARM_COMPUTE_ERROR_ON_NULLPTR(input, output);
     _impl->src = input;
     _impl->dst = output;
     _impl->op  = std::make_unique<cpu::CpuReshape>();
     _impl->op->configure(input->info(), output->info());
 }
References ARM_COMPUTE_ERROR_ON_NULLPTR, ITensor::info(), and arm_compute::test::validation::input.
Referenced by NEReduceMean::configure(), NEReductionOperation::configure(), and NEGenerateProposalsLayer::configure().
operator=() [1/2]
NEReshapeLayer& operator= (const NEReshapeLayer &) delete
Prevent instances of this class from being copied (As this class contains pointers)
operator=() [2/2]
NEReshapeLayer & operator= (NEReshapeLayer &&) default
Default move assignment operator.
run()
void run () override virtual
Run the kernels contained in the function.
For CPU kernels:
Multi-threading is used for the kernels which are parallelisable.
By default std::thread::hardware_concurrency() threads are used.
Note
CPPScheduler::set_num_threads() can be used to manually set the number of threads
For OpenCL kernels:
All the kernels are enqueued on the queue associated with CLScheduler.
The queue is then flushed.
Note
The function will not block until the kernels are executed. It is the user's responsibility to wait.
Will call prepare() on first run if hasn't been done
Implements IFunction.
Definition at line 66 of file NEReshapeLayer.cpp.
 {
     ITensorPack pack;
     pack.add_tensor(TensorType::ACL_SRC, _impl->src);
     pack.add_tensor(TensorType::ACL_DST, _impl->dst);
     _impl->op->run(pack);
 }
References arm_compute::ACL_DST, arm_compute::ACL_SRC, ITensorPack::add_tensor(), and arm_compute::test::validation::pack.
Referenced by NEReduceMean::run(), NEReductionOperation::run(), and NEGenerateProposalsLayer::run().
validate()
Status validate (const ITensorInfo * input, const ITensorInfo * output) static
Static function to check if given info will lead to a valid configuration of NEReshapeLayer.
Parameters
[in] input Input tensor info. Data type supported: All
[in] output Output tensor info. Data type supported: Same as input
Returns
a status
Definition at line 58 of file NEReshapeLayer.cpp.
 {
     ARM_COMPUTE_RETURN_ERROR_ON_NULLPTR(input, output);
     ARM_COMPUTE_RETURN_ON_ERROR(cpu::CpuReshape::validate(input, output));
     return Status{};
 }
References ARM_COMPUTE_RETURN_ERROR_ON_NULLPTR, ARM_COMPUTE_RETURN_ON_ERROR, arm_compute::test::validation::input, and CpuReshape::validate().
Referenced by NEReductionOperation::validate(), and NEGenerateProposalsLayer::validate().
The documentation for this class was generated from the following files:
arm_compute/runtime/NEON/functions/NEReshapeLayer.h
src/runtime/NEON/functions/NEReshapeLayer.cpp