Compute Library: CpuPool2dKernel Class Reference
CpuPool2dKernel Class Reference
Interface for the pooling layer kernel.
#include <CpuPool2dKernel.h>
Data Structures
struct PoolingKernel
Public Member Functions
CpuPool2dKernel ()=default
ARM_COMPUTE_DISALLOW_COPY_ALLOW_MOVE (CpuPool2dKernel)
void configure (ITensorInfo *src, ITensorInfo *dst, const PoolingLayerInfo &pool_info, ITensorInfo *indices=nullptr)
Configure kernel for a given list of arguments.
void run_op (ITensorPack &tensors, const Window &window, const ThreadInfo &info) override
Execute the kernel on the passed window.
const char * name () const override
Name of the kernel.
Public Member Functions inherited from ICPPKernel
virtual ~ICPPKernel ()=default
Default destructor.
virtual void run (const Window &window, const ThreadInfo &info)
Execute the kernel on the passed window.
virtual void run_nd (const Window &window, const ThreadInfo &info, const Window &thread_locator)
legacy compatibility layer for implemantions which do not support thread_locator In these cases we simply narrow the interface down the legacy version
virtual size_t get_mws (const CPUInfo &platform, size_t thread_count) const
Return minimum workload size of the relevant kernel.
Public Member Functions inherited from IKernel
IKernel ()
Constructor.
virtual ~IKernel ()=default
Destructor.
virtual bool is_parallelisable () const
Indicates whether or not the kernel is parallelisable.
virtual BorderSize border_size () const
The size of the border for that kernel.
const Window & window () const
The maximum window the kernel can be executed on.
bool is_window_configured () const
Function to check if the embedded window of this kernel has been configured.
Static Public Member Functions
static Status validate (const ITensorInfo *src, const ITensorInfo *dst, const PoolingLayerInfo &pool_info, const ITensorInfo *indices=nullptr)
Static function to check if given info will lead to a valid configuration.
static const std::vector< PoolingKernel > & get_available_kernels ()
Static Public Member Functions inherited from ICpuKernel< CpuPool2dKernel >
static const auto * get_implementation (const SelectorType &selector, KernelSelectionType selection_type=KernelSelectionType::Supported)
Micro-kernel selector.
Additional Inherited Members
Static Public Attributes inherited from ICPPKernel
static constexpr size_t default_mws = 1
Detailed Description
Interface for the pooling layer kernel.
Definition at line 39 of file CpuPool2dKernel.h.
Constructor & Destructor Documentation
CpuPool2dKernel()
CpuPool2dKernel () default
Member Function Documentation
ARM_COMPUTE_DISALLOW_COPY_ALLOW_MOVE()
ARM_COMPUTE_DISALLOW_COPY_ALLOW_MOVE (CpuPool2dKernel)
configure()
void configure (ITensorInfo * src, ITensorInfo * dst, const PoolingLayerInfo & pool_info, ITensorInfo * indices = nullptr)
Configure kernel for a given list of arguments.
Note
F16 are supported for pool sizes 2 and 3 only
Parameters
[in] src Source tensor info. Data types supported: QASYMM8/QASYMM8_SIGNED/F16/F32.
[out] dst Destination tensor info. Data types supported: Same as src.
[in] pool_info Contains pooling operation information described in PoolingLayerInfo.
[out] indices (optional) The indices of the maximal values. Data type supported: U32.
Definition at line 301 of file CpuPool2dKernel.cpp.
 {
     ARM_COMPUTE_ERROR_ON_NULLPTR(src, dst);
     const PadStrideInfo pad_stride_info   = pool_info.pad_stride_info;
     const bool          is_global_pooling = pool_info.is_global_pooling;
     // Get data layout
     const auto data_layout = pool_info.data_layout == DataLayout::UNKNOWN ? src->data_layout() : pool_info.data_layout;
     const int  idx_width   = get_data_layout_dimension_index(data_layout, DataLayoutDimension::WIDTH);
     const int  idx_height  = get_data_layout_dimension_index(data_layout, DataLayoutDimension::HEIGHT);
     // Update pool size in case of global pooling
     const Size2D pool_size(is_global_pooling ? src->dimension(idx_width) : pool_info.pool_size.width,
                            is_global_pooling ? src->dimension(idx_height) : pool_info.pool_size.height);
     // Perform validation step
     ARM_COMPUTE_ERROR_THROW_ON(validate_arguments(src, dst, pool_info, indices, pool_size));
     const auto *uk = CpuPool2dKernel::get_implementation(
         PoolDataTypeISASelectorData{src->data_type(), src->data_layout(), (int)pad_stride_info.stride().first,
                                     pool_size, CPUInfo::get().get_isa()});
     ARM_COMPUTE_ERROR_ON(uk == nullptr);
     // Set instance variables
     _pool_info     = pool_info;
     _data_layout   = src->data_layout();
     _pool_size     = pool_size;
     _pool_stride_x = pad_stride_info.stride().first;
     _run_method    = uk->ukernel;
     _name          = std::string("CpuPool2dKernel").append("/").append(uk->name);
     if (_data_layout == DataLayout::NHWC)
     {
         // Configure kernel window
         Window win = calculate_max_window(*dst, Steps());
         ICpuKernel::configure(win);
     }
     else
     {
         // Configure kernel window
         auto win_config = validate_and_configure_window(
             src, dst, indices, pool_info, _num_elems_processed_per_iteration, pool_size.x(), pool_size.y());
         ARM_COMPUTE_ERROR_THROW_ON(win_config.first);
         ICpuKernel::configure(win_config.second);
     }
 }
References ARM_COMPUTE_ERROR_ON, ARM_COMPUTE_ERROR_ON_NULLPTR, ARM_COMPUTE_ERROR_THROW_ON, arm_compute::calculate_max_window(), arm_compute::cpu::data_layout, PoolingLayerInfo::data_layout, arm_compute::test::validation::dst, CPUInfo::get(), arm_compute::get_data_layout_dimension_index(), ICpuKernel< CpuPool2dKernel >::get_implementation(), CPUInfo::get_isa(), Size2D::height, arm_compute::HEIGHT, arm_compute::test::validation::idx_height, arm_compute::test::validation::idx_width, PoolingLayerInfo::is_global_pooling, arm_compute::NHWC, PoolingLayerInfo::pad_stride_info, PoolingLayerInfo::pool_size, arm_compute::test::validation::src, PadStrideInfo::stride(), arm_compute::UNKNOWN, arm_compute::cpu::kernels::validate_and_configure_window(), arm_compute::cpu::kernels::validate_arguments(), Size2D::width, arm_compute::WIDTH, Size2D::x(), and Size2D::y().
get_available_kernels()
const std::vector< CpuPool2dKernel::PoolingKernel > & get_available_kernels () static
Definition at line 444 of file CpuPool2dKernel.cpp.
 {
     return available_kernels;
 }
name()
const char * name () const override virtual
Name of the kernel.
Returns
Kernel name
Implements ICPPKernel.
Definition at line 439 of file CpuPool2dKernel.cpp.
 {
     return _name.c_str();
 }
run_op()
void run_op (ITensorPack & tensors, const Window & window, const ThreadInfo & info) override virtual
Execute the kernel on the passed window.
Warning
If is_parallelisable() returns false then the passed window must be equal to window()
Note
The window has to be a region within the window returned by the window() method
The width of the window has to be a multiple of num_elems_processed_per_iteration().
Parameters
[in] tensors A vector containing the tensors to operate on.
[in] window Region on which to execute the kernel. (Must be a region of the window returned by window())
[in] info Info about executing thread and CPU.
Reimplemented from ICPPKernel.
Definition at line 380 of file CpuPool2dKernel.cpp.
 {
     ARM_COMPUTE_UNUSED(info);
     ARM_COMPUTE_ERROR_ON_UNCONFIGURED_KERNEL(this);
     ARM_COMPUTE_ERROR_ON_INVALID_SUBWINDOW(ICpuKernel::window(), window);
     ARM_COMPUTE_ERROR_ON(_run_method == nullptr);
     const ITensor *src     = tensors.get_const_tensor(TensorType::ACL_SRC_0);
     ITensor       *dst     = tensors.get_tensor(TensorType::ACL_DST_0);
     ITensor       *indices = tensors.get_tensor(TensorType::ACL_DST_1);
     const unsigned int pool_stride_x = _pool_info.pad_stride_info.stride().first;
     const unsigned int pool_stride_y = _pool_info.pad_stride_info.stride().second;
     const unsigned int pool_size     = _pool_info.pool_size.width;
     Window window_src(window);
     if (_data_layout == DataLayout::NCHW)
     {
         // Set step for src in x and y direction for the src
         unsigned int window_x_inc = 0;
         switch (src->info()->data_type())
         {
             case DataType::QASYMM8:
             case DataType::QASYMM8_SIGNED:
             {
                 window_x_inc = pool_stride_x;
                 if ((pool_size == 2 || pool_size == 3) && pool_stride_x < 3)
                 {
                     window_x_inc = (pool_stride_x == 2) ? _num_elems_processed_per_iteration * 2
                                                         : _num_elems_processed_per_iteration;
                 }
                 break;
             }
             case DataType::F16:
             case DataType::F32:
             {
                 window_x_inc = pool_stride_x;
                 break;
             }
             default:
             {
                 ARM_COMPUTE_ERROR("Not supported");
             }
         }
         window_src.set(Window::DimX, Window::Dimension(window.x().start() * pool_stride_x,
                                                        window.x().end() * pool_stride_x, window_x_inc));
         window_src.set(Window::DimY, Window::Dimension(window.y().start() * pool_stride_y,
                                                        window.y().end() * pool_stride_y, pool_stride_y));
     }
     else
     {
         window_src.set(Window::DimX, Window::Dimension(0, 1, 1));
         window_src.set(Window::DimY, Window::Dimension(0, src->info()->dimension(1), pool_stride_x));
         window_src.set(Window::DimZ, Window::Dimension(0, src->info()->dimension(2), pool_stride_y));
     }
     _run_method(src, dst, indices, _pool_info, window_src, window);
 }
References arm_compute::ACL_DST_0, arm_compute::ACL_DST_1, arm_compute::ACL_SRC_0, ARM_COMPUTE_ERROR, ARM_COMPUTE_ERROR_ON, ARM_COMPUTE_ERROR_ON_INVALID_SUBWINDOW, ARM_COMPUTE_ERROR_ON_UNCONFIGURED_KERNEL, ARM_COMPUTE_UNUSED, Window::DimX, Window::DimY, Window::DimZ, arm_compute::test::validation::dst, Window::Dimension::end(), arm_compute::F16, arm_compute::F32, ITensorPack::get_const_tensor(), ITensorPack::get_tensor(), arm_compute::test::validation::info, arm_compute::NCHW, PoolingLayerInfo::pad_stride_info, PoolingLayerInfo::pool_size, arm_compute::QASYMM8, arm_compute::QASYMM8_SIGNED, Window::set(), arm_compute::test::validation::src, Window::Dimension::start(), PadStrideInfo::stride(), Size2D::width, IKernel::window(), Window::x(), and Window::y().
validate()
Status validate (const ITensorInfo * src, const ITensorInfo * dst, const PoolingLayerInfo & pool_info, const ITensorInfo * indices = nullptr) static
Static function to check if given info will lead to a valid configuration.
Similar to CpuPool2dKernel::configure()
Returns
a status
Definition at line 351 of file CpuPool2dKernel.cpp.
 {
     ARM_COMPUTE_RETURN_ERROR_ON_NULLPTR(src);
     unsigned int num_elems_processed_per_iteration = 0;
     const bool is_global_pooling = pool_info.is_global_pooling;
     // Get data layout
     const auto data_layout = pool_info.data_layout == DataLayout::UNKNOWN ? src->data_layout() : pool_info.data_layout;
     const int  idx_width   = get_data_layout_dimension_index(data_layout, DataLayoutDimension::WIDTH);
     const int  idx_height  = get_data_layout_dimension_index(data_layout, DataLayoutDimension::HEIGHT);
     unsigned int pool_size_x = is_global_pooling ? src->dimension(idx_width) : pool_info.pool_size.width;
     unsigned int pool_size_y = is_global_pooling ? src->dimension(idx_height) : pool_info.pool_size.height;
     ARM_COMPUTE_RETURN_ON_ERROR(validate_arguments(src, dst, pool_info, indices, Size2D(pool_size_x, pool_size_y)));
     ARM_COMPUTE_RETURN_ON_ERROR(validate_and_configure_window(src->clone().get(), dst->clone().get(),
                                                               (indices) ? indices->clone().get() : nullptr, pool_info,
                                                               num_elems_processed_per_iteration, pool_size_x,
                                                               pool_size_y)
                                     .first);
     return Status{};
 }
References ARM_COMPUTE_RETURN_ERROR_ON_NULLPTR, ARM_COMPUTE_RETURN_ON_ERROR, ICloneable< T >::clone(), arm_compute::cpu::data_layout, PoolingLayerInfo::data_layout, arm_compute::test::validation::dst, arm_compute::get_data_layout_dimension_index(), Size2D::height, arm_compute::HEIGHT, arm_compute::test::validation::idx_height, arm_compute::test::validation::idx_width, PoolingLayerInfo::is_global_pooling, num_elems_processed_per_iteration, PoolingLayerInfo::pool_size, arm_compute::test::validation::src, arm_compute::UNKNOWN, arm_compute::cpu::kernels::validate_and_configure_window(), arm_compute::cpu::kernels::validate_arguments(), Size2D::width, and arm_compute::WIDTH.
Referenced by CpuPool2d::validate().
The documentation for this class was generated from the following files:
src/cpu/kernels/CpuPool2dKernel.h
src/cpu/kernels/CpuPool2dKernel.cpp