Compute Library: CpuInfo Class Reference
CpuInfo Class Reference
Aggregate class that contains CPU related information.
#include <CpuInfo.h>
Public Member Functions
CpuInfo ()=default
Default constructor.
CpuInfo (CpuIsaInfo isa, std::vector< CpuModel > cpus)
Construct a new Cpu Info object.
bool has_neon () const
bool has_sve () const
bool has_sve2 () const
bool has_sme () const
bool has_sme2 () const
bool has_fp16 () const
bool has_bf16 () const
bool has_svebf16 () const
bool has_dotprod () const
bool has_i8mm () const
bool has_svei8mm () const
bool has_svef32mm () const
const CpuIsaInfo & isa () const
const std::vector< CpuModel > & cpus () const
CpuModel cpu_model (uint32_t cpuid) const
CpuModel cpu_model () const
uint32_t num_cpus () const
Static Public Member Functions
static CpuInfo build ()
CpuInfo builder function from system related information.
Detailed Description
Aggregate class that contains CPU related information.
Contains information about the numbers of the CPUs, the model of each CPU, ISA related information and more
Note
We can safely assume that the ISA is common between different clusters of cores
Definition at line 44 of file CpuInfo.h.
Constructor & Destructor Documentation
CpuInfo() [1/2]
CpuInfo () default
Default constructor.
CpuInfo() [2/2]
CpuInfo (CpuIsaInfo isa, std::vector< CpuModel > cpus)
Construct a new Cpu Info object.
Parameters
[in] isa ISA capabilities information
[in] cpus CPU models information
Definition at line 301 of file CpuInfo.cpp.
                                                          : _isa(std::move(isa)), _cpus(std::move(cpus))
 {
 }
Member Function Documentation
build()
CpuInfo build () static
CpuInfo builder function from system related information.
Returns
CpuInfo A populated CpuInfo structure
Definition at line 305 of file CpuInfo.cpp.
 {
 #if !defined(_WIN64) && !defined(BARE_METAL) && !defined(__APPLE__) && !defined(__OpenBSD__) && \
     (defined(__arm__) || defined(__aarch64__))
     const uint32_t hwcaps   = getauxval(AT_HWCAP);
     const uint32_t hwcaps2  = getauxval(AT_HWCAP2);
     const uint32_t max_cpus = get_max_cpus();
     // Populate midr values
     std::vector<uint32_t> cpus_midr;
     if (hwcaps & ARM_COMPUTE_CPU_FEATURE_HWCAP_CPUID)
     {
         cpus_midr = midr_from_cpuid(max_cpus);
     }
     if (cpus_midr.empty())
     {
         cpus_midr = midr_from_proc_cpuinfo(max_cpus);
     }
     if (cpus_midr.empty())
     {
         cpus_midr.resize(max_cpus, 0);
     }
     // Populate isa (Assume homogeneous ISA specification)
     CpuIsaInfo isa = init_cpu_isa_from_hwcaps(hwcaps, hwcaps2, cpus_midr.back());
     // Convert midr to models
     std::vector<CpuModel> cpus_model;
     std::transform(std::begin(cpus_midr), std::end(cpus_midr), std::back_inserter(cpus_model),
                    [](uint32_t midr) -> CpuModel { return midr_to_model(midr); });
     CpuInfo info(isa, cpus_model);
     return info;
 #elif (BARE_METAL) && \
     defined(          \
         __aarch64__) /* !defined(BARE_METAL) && !defined(__APPLE__) && !defined(__OpenBSD__) && (defined(__arm__) || defined(__aarch64__)) */
     // Assume single CPU in bare metal mode.  Just read the ID register and feature bits directly.
     uint64_t isar0 = 0, isar1 = 0, pfr0 = 0, pfr1 = 0, svefr0 = 0, midr = 0;
     ARM_COMPUTE_GET_FEATURE_REG(isar0, ID_AA64ISAR0_EL1);
     ARM_COMPUTE_GET_FEATURE_REG(isar1, ID_AA64ISAR1_EL1);
     ARM_COMPUTE_GET_FEATURE_REG(pfr0, ID_AA64PFR0_EL1);
     ARM_COMPUTE_GET_FEATURE_REG(pfr1, ID_AA64PFR1_EL1);
     ARM_COMPUTE_GET_FEATURE_REG(midr, MIDR_EL1);
     if ((pfr0 >> 32) & 0xf)
     {
         svefr0 = get_sve_feature_reg();
     }
     CpuIsaInfo            isa = init_cpu_isa_from_regs(isar0, isar1, pfr0, pfr1, svefr0, midr);
     std::vector<CpuModel> cpus_model(1, midr_to_model(midr));
     CpuInfo               info(isa, cpus_model);
     return info;
 #elif defined(__aarch64__) && defined(__APPLE__) /* #elif(BARE_METAL) && defined(__aarch64__) */
     int                   ncpus = get_hw_capability("hw.perflevel0.logicalcpu");
     CpuIsaInfo            isainfo;
     std::vector<CpuModel> cpus_model(ncpus);
     isainfo.neon = get_hw_capability("hw.optional.neon");
     isainfo.fp16 = get_hw_capability("hw.optional.neon_fp16");
     isainfo.dot  = get_hw_capability("hw.optional.arm.FEAT_DotProd");
     CpuInfo info(isainfo, cpus_model);
     return info;
 #else                                            /* #elif defined(__aarch64__) && defined(__APPLE__) */
     CpuInfo info(CpuIsaInfo(), {CpuModel::GENERIC});
     return info;
 #endif /* !defined(BARE_METAL) && !defined(__APPLE__) && !defined(__OpenBSD__) && (defined(__arm__) || defined(__aarch64__)) */
 }
References ARM_COMPUTE_CPU_FEATURE_HWCAP_CPUID, ARM_COMPUTE_GET_FEATURE_REG, CpuIsaInfo::dot, arm_compute::mlgo::parser::end(), CpuIsaInfo::fp16, arm_compute::test::validation::info, arm_compute::cpuinfo::init_cpu_isa_from_hwcaps(), arm_compute::cpuinfo::init_cpu_isa_from_regs(), CpuInfo::isa(), arm_compute::cpuinfo::midr_to_model(), and CpuIsaInfo::neon.
cpu_model() [1/2]
CpuModel cpu_model () const
Definition at line 383 of file CpuInfo.cpp.
 {
 #if defined(_WIN64) || defined(BARE_METAL) || defined(__APPLE__) || defined(__OpenBSD__) || \
     (!defined(__arm__) && !defined(__aarch64__))
     return cpu_model(0);
 #else /* defined(BARE_METAL) || defined(__APPLE__) || defined(__OpenBSD__) || (!defined(__arm__) && !defined(__aarch64__)) */
     return cpu_model(sched_getcpu());
 #endif /* defined(BARE_METAL) || defined(__APPLE__) || defined(__OpenBSD__) || (!defined(__arm__) && !defined(__aarch64__)) */
 }
cpu_model() [2/2]
CpuModel cpu_model (uint32_t cpuid) const
Definition at line 374 of file CpuInfo.cpp.
 {
     if (cpuid < _cpus.size())
     {
         return _cpus[cpuid];
     }
     return CpuModel::GENERIC;
 }
cpus()
const std::vector<CpuModel>& cpus () const inline
Definition at line 115 of file CpuInfo.h.
     {
         return _cpus;
     }
has_bf16()
bool has_bf16 () const inline
Definition at line 86 of file CpuInfo.h.
     {
         return _isa.bf16;
     }
References CpuIsaInfo::bf16.
has_dotprod()
bool has_dotprod () const inline
Definition at line 94 of file CpuInfo.h.
     {
         return _isa.dot;
     }
References CpuIsaInfo::dot.
Referenced by arm_compute::test::validation::TEST_CASE().
has_fp16()
bool has_fp16 () const inline
Definition at line 82 of file CpuInfo.h.
     {
         return _isa.fp16;
     }
References CpuIsaInfo::fp16.
Referenced by arm_compute::test::validation::TEST_CASE().
has_i8mm()
bool has_i8mm () const inline
Definition at line 98 of file CpuInfo.h.
     {
         return _isa.i8mm;
     }
References CpuIsaInfo::i8mm.
Referenced by arm_compute::test::validation::TEST_CASE().
has_neon()
bool has_neon () const inline
Definition at line 62 of file CpuInfo.h.
     {
         return _isa.neon;
     }
References CpuIsaInfo::neon.
Referenced by arm_compute::test::validation::TEST_CASE().
has_sme()
bool has_sme () const inline
Definition at line 74 of file CpuInfo.h.
     {
         return _isa.sme;
     }
References CpuIsaInfo::sme.
has_sme2()
bool has_sme2 () const inline
Definition at line 78 of file CpuInfo.h.
     {
         return _isa.sme2;
     }
References CpuIsaInfo::sme2.
has_sve()
bool has_sve () const inline
Definition at line 66 of file CpuInfo.h.
     {
         return _isa.sve;
     }
References CpuIsaInfo::sve.
has_sve2()
bool has_sve2 () const inline
Definition at line 70 of file CpuInfo.h.
     {
         return _isa.sve2;
     }
References CpuIsaInfo::sve2.
Referenced by arm_compute::test::validation::TEST_CASE().
has_svebf16()
bool has_svebf16 () const inline
Definition at line 90 of file CpuInfo.h.
     {
         return _isa.svebf16;
     }
References CpuIsaInfo::svebf16.
has_svef32mm()
bool has_svef32mm () const inline
Definition at line 106 of file CpuInfo.h.
     {
         return _isa.svef32mm;
     }
References CpuIsaInfo::svef32mm.
has_svei8mm()
bool has_svei8mm () const inline
Definition at line 102 of file CpuInfo.h.
     {
         return _isa.svei8mm;
     }
References CpuIsaInfo::svei8mm.
isa()
const CpuIsaInfo& isa () const inline
Definition at line 111 of file CpuInfo.h.
     {
         return _isa;
     }
Referenced by CpuInfo::build().
num_cpus()
uint32_t num_cpus () const
Definition at line 393 of file CpuInfo.cpp.
 {
     return _cpus.size();
 }
The documentation for this class was generated from the following files:
src/common/cpuinfo/CpuInfo.h
src/common/cpuinfo/CpuInfo.cpp