Compute Library: arm_compute::scale_utils Namespace Reference
arm_compute::scale_utils Namespace Reference
Functions
float calculate_resize_ratio (size_t input_size, size_t output_size, bool align_corners=false)
Returns resize ratio between input and output with consideration of aligned corners.
bool is_align_corners_allowed_sampling_policy (SamplingPolicy sampling_policy)
Returns if aligned corners are allowed for the given sampling policy.
bool is_precomputation_required (DataLayout data_layout, DataType data_type, InterpolationPolicy policy, BorderMode border_mode)
Returns if precomputation of indices and/or weights is required or/not.
Function Documentation
calculate_resize_ratio()
float calculate_resize_ratio (size_t input_size, size_t output_size, bool align_corners = false)
Returns resize ratio between input and output with consideration of aligned corners.
Parameters
[in] input_size The input size
[in] output_size the output size
[in] align_corners True to align corners of input and output. Defaults to false.
Returns
The ratio between input and output (i.e., the input size divided by the output size)
Definition at line 32 of file ScaleUtils.cpp.
 {
     const size_t offset = (align_corners && output_size > 1) ? 1 : 0;
     const auto   in     = input_size - offset;
     const auto   out    = output_size - offset;
     ARM_COMPUTE_ERROR_ON((input_size == 0 || output_size == 0) && offset == 1);
     ARM_COMPUTE_ERROR_ON(out == 0);
     return static_cast<float>(in) / static_cast<float>(out);
 }
References ARM_COMPUTE_ERROR_ON, arm_compute::test::validation::input_size, offset(), and arm_compute::test::validation::output_size.
Referenced by arm_compute::cpu::bilinear_neon_scale(), CpuScale::configure(), CpuScaleKernel::configure(), NEScale::configure(), ClTemplateResize::get_tag_lut(), arm_compute::cpu::nearest_neon_scale(), CpuScale::prepare(), arm_compute::test::validation::reference::scale_core(), and CpuScale::validate().
is_align_corners_allowed_sampling_policy()
bool arm_compute::scale_utils::is_align_corners_allowed_sampling_policy (SamplingPolicy sampling_policy) inline
Returns if aligned corners are allowed for the given sampling policy.
Parameters
[in] sampling_policy The sampling policy to consider
Returns
True if aligned corners are allowed
Definition at line 49 of file ScaleUtils.h.
 {
     return sampling_policy != SamplingPolicy::CENTER;
 }
References arm_compute::CENTER, and arm_compute::test::validation::sampling_policy.
Referenced by CpuScale::configure(), NEScale::configure(), CpuScale::prepare(), CpuScale::validate(), and ClComponentResize::validate().
is_precomputation_required()
bool is_precomputation_required (DataLayout data_layout, DataType data_type, InterpolationPolicy policy, BorderMode border_mode)
Returns if precomputation of indices and/or weights is required or/not.
Parameters
[in] data_layout Data layout
[in] data_type Data type
[in] policy Interpolation policy
[in] border_mode Border Mode
Returns
True if precomputation is required
Definition at line 44 of file ScaleUtils.cpp.
 {
     // Do not calculate precomputed weights and indices if kernel code doesn't use them
     if (data_layout == DataLayout::NHWC)
     {
         switch (data_type)
         {
             case DataType::F32:
             case DataType::F16:
                 return (CPUInfo::get().get_isa().sve == true && policy == InterpolationPolicy::NEAREST_NEIGHBOR);
             case DataType::U8:
             case DataType::S8:
             case DataType::QASYMM8:
             case DataType::QASYMM8_SIGNED:
                 return (border_mode != BorderMode::REPLICATE) || (policy == InterpolationPolicy::NEAREST_NEIGHBOR);
             default:
                 return true;
         }
     }
     return true;
 }
References arm_compute::cpu::data_layout, arm_compute::test::validation::data_type, CPUInfo::get(), and arm_compute::test::validation::sve.
Referenced by NEScale::configure(), and CpuScale::prepare().