Compute Library: include_functions_kernels Namespace Reference
include_functions_kernels Namespace Reference
Functions
def read_file (file)
def write_file (file, lines)
def remove_existing_includes (lines)
def add_updated_includes (lines, pos, includes)
def create_include_list (folder)
def include_components (target, path, header_prefix, folder, subfolders=None)
Variables
string armcv_path = "arm_compute"
string src_path = "src"
Target = collections.namedtuple('Target', 'name prefix basepath')
list core_targets
list runtime_targets
string core_path = "/core/"
string runtime_path = "/runtime/"
string include_str = "#include \""
Function Documentation
add_updated_includes()
def include_functions_kernels.add_updated_includes (lines, pos, includes)
Definition at line 68 of file include_functions_kernels.py.
 def add_updated_includes(lines, pos, includes):
     lines[pos:pos] = includes
     return lines
Referenced by include_components().
create_include_list()
def include_functions_kernels.create_include_list (folder)
Definition at line 73 of file include_functions_kernels.py.
 def create_include_list(folder):
     files_path = folder + "/*.h"
     files = glob.glob(files_path)
     updated_files = [include_str + folder + "/" + x.rsplit('/',1)[1] + "\"\n" for x in files]
     updated_files.sort(key=lambda x: x.lower())
     return updated_files
Referenced by include_components().
include_components()
def include_functions_kernels.include_components (target, path, header_prefix, folder, subfolders = None)
Definition at line 81 of file include_functions_kernels.py.
 def include_components(target, path, header_prefix, folder, subfolders=None):
     for t in target:
         target_path = t.basepath + path +  t.name + "/"
         components_file = target_path + t.prefix + header_prefix
         if os.path.exists(components_file):
             include_list = create_include_list(target_path + folder)
             for s in subfolders or []:
                 include_list += create_include_list( target_path + folder + "/" + s)
             include_list.sort(key=lambda x: x.lower())
             lines = read_file(components_file)
             lines, first_pos = remove_existing_includes(lines)
             lines = add_updated_includes(lines, first_pos, include_list)
             write_file(components_file, lines)
References add_updated_includes(), create_include_list(), read_file(), remove_existing_includes(), and write_file().
read_file()
def include_functions_kernels.read_file (file)
Definition at line 51 of file include_functions_kernels.py.
 def read_file(file):
     with open(file, "r") as f:
         lines = f.readlines()
     return lines
Referenced by include_components().
remove_existing_includes()
def include_functions_kernels.remove_existing_includes (lines)
Definition at line 63 of file include_functions_kernels.py.
 def remove_existing_includes(lines):
     first_pos = next(i for i, line in enumerate(lines) if include_str in line)
     return [x for x in lines if not x.startswith(include_str)], first_pos
Referenced by include_components().
write_file()
def include_functions_kernels.write_file (file, lines)
Definition at line 57 of file include_functions_kernels.py.
 def write_file(file, lines):
     with open(file, "w") as f:
         for line in lines:
             f.write(line)
Referenced by include_components().
Variable Documentation
armcv_path
string armcv_path = "arm_compute"
Definition at line 29 of file include_functions_kernels.py.
core_path
string core_path = "/core/"
Definition at line 47 of file include_functions_kernels.py.
core_targets
list core_targets
Initial value:
 =  [
     Target("NEON", "NE", src_path),             # Arm® Neon™ kernels are under src
     Target("CL", "CL", src_path),               # CL kernels are under src
     Target("CPP", "CPP", armcv_path)            # CPP kernels are under arm_compute
     ]
Definition at line 34 of file include_functions_kernels.py.
include_str
string include_str = "#include \""
Definition at line 49 of file include_functions_kernels.py.
runtime_path
string runtime_path = "/runtime/"
Definition at line 48 of file include_functions_kernels.py.
runtime_targets
list runtime_targets
Initial value:
 =  [
     Target("NEON", "NE", armcv_path),
     Target("CL", "CL", armcv_path),
     Target("CPP", "CPP", armcv_path)
     ]
Definition at line 41 of file include_functions_kernels.py.
src_path
string src_path = "src"
Definition at line 30 of file include_functions_kernels.py.
Target
Target = collections.namedtuple('Target', 'name prefix basepath')
Definition at line 32 of file include_functions_kernels.py.