Compute Library: arm_compute::graph::backends::detail Namespace Reference
arm_compute::graph::backends::detail Namespace Reference
Data Structures
class BackendRegistrar
Helper class to statically register a backend.
Functions
template<typename TargetInfo >
TargetInfo::TensorType * get_backing_tensor (arm_compute::graph::Tensor *tensor)
Returns backing tensor of a given tensor.
template<typename TargetInfo >
void validate_node (const INode &node, size_t num_expected_inputs, size_t num_expected_outputs)
template<typename ActivationLayerFunction , typename TargetInfo >
std::unique_ptr< IFunction > create_activation_layer (ActivationLayerNode &node)
Creates a backend activation layer function.
template<typename ArgMinMaxLayerFunction , typename TargetInfo >
std::unique_ptr< IFunction > create_arg_min_max_layer (ArgMinMaxLayerNode &node)
Creates a backend argminmax layer function.
template<typename BatchNormalizationLayerFunction , typename TargetInfo >
std::unique_ptr< IFunction > create_batch_normalization_layer (BatchNormalizationLayerNode &node)
Create a backend batch normalization layer function.
template<typename FusedLayerTypes , typename TargetInfo >
std::unique_ptr< IFunction > create_fused_convolution_batch_normalization_layer (FusedConvolutionBatchNormalizationNode &node, GraphContext &ctx)
Create a backend batch normalization layer function.
template<typename FusedLayerTypes , typename TargetInfo >
std::unique_ptr< IFunction > create_fused_depthwise_convolution_batch_normalization_layer (FusedDepthwiseConvolutionBatchNormalizationNode &node, GraphContext &ctx)
Create a backend fused depthwise convolution batch normalization layer function.
template<typename BoundingBoxTransformLayerFunction , typename TargetInfo >
std::unique_ptr< IFunction > create_bounding_box_transform_layer (BoundingBoxTransformLayerNode &node)
Create a backend bounding box transform layer function.
template<typename ChannelShuffleLayerFunction , typename TargetInfo >
std::unique_ptr< IFunction > create_channel_shuffle_layer (ChannelShuffleLayerNode &node)
Create a backend channel shuffle layer function.
template<typename ConcatenateLayerFunction , typename TargetInfo >
std::unique_ptr< arm_compute::IFunction > create_concatenate_layer (ConcatenateLayerNode &node)
Create a backend layer concatenate function.
template<typename ConvolutionLayerFunctions , typename TargetInfo >
std::unique_ptr< IFunction > create_convolution_layer (ConvolutionLayerNode &node, GraphContext &ctx)
Create a backend convolution layer function.
template<typename DeconvolutionLayerFunction , typename TargetInfo >
std::unique_ptr< IFunction > create_deconvolution_layer (DeconvolutionLayerNode &node, GraphContext &ctx)
Create a backend deconvolution layer function.
template<typename DepthwiseConvolutionLayer , typename TargetInfo >
std::unique_ptr< IFunction > create_depthwise_convolution_layer (DepthwiseConvolutionLayerNode &node)
Create a backend layer depth-wise convolution function.
template<typename DepthToSpaceLayerFunction , typename TargetInfo >
std::unique_ptr< IFunction > create_depth_to_space_layer (DepthToSpaceLayerNode &node)
Create a backend depth to space layer function.
template<typename DequantizationLayerFunction , typename TargetInfo >
std::unique_ptr< IFunction > create_dequantization_layer (DequantizationLayerNode &node)
Create a backend dequantize layer function.
template<typename DetectionOutputLayerFunction , typename TargetInfo >
std::unique_ptr< IFunction > create_detection_output_layer (DetectionOutputLayerNode &node)
Create a backend detection output layer function.
template<typename DetectionPostProcessLayerFunction , typename TargetInfo >
std::unique_ptr< IFunction > create_detection_post_process_layer (DetectionPostProcessLayerNode &node)
Create a backend detection post process layer function.
template<typename EltwiseFunctions , typename TargetInfo >
std::unique_ptr< IFunction > create_eltwise_layer (EltwiseLayerNode &node)
Create a backend element-wise operation layer function.
template<typename UnaryEltwiseFunctions , typename TargetInfo >
std::unique_ptr< IFunction > create_unary_eltwise_layer (UnaryEltwiseLayerNode &node)
Create a backend unary element-wise operation layer function.
template<typename FlattenLayerFunction , typename TargetInfo >
std::unique_ptr< IFunction > create_flatten_layer (FlattenLayerNode &node)
Create a backend flatten layer function.
template<typename FullyConnectedLayerFunction , typename TargetInfo >
std::unique_ptr< IFunction > create_fully_connected_layer (FullyConnectedLayerNode &node, GraphContext &ctx)
Create a backend fully connected layer function.
template<typename GenerateProposalsLayerFunction , typename TargetInfo >
std::unique_ptr< IFunction > create_generate_proposals_layer (GenerateProposalsLayerNode &node, GraphContext &ctx)
Create a backend generate proposals layer function.
template<typename L2NormalizeLayerFunction , typename TargetInfo >
std::unique_ptr< IFunction > create_l2_normalize_layer (L2NormalizeLayerNode &node, GraphContext &ctx)
Create a backend l2 normalization layer function.
template<typename NormalizationLayerFunction , typename TargetInfo >
std::unique_ptr< IFunction > create_normalization_layer (NormalizationLayerNode &node, GraphContext &ctx)
Create a backend normalization layer function.
template<typename NormalizePlanarYUVLayerFunction , typename TargetInfo >
std::unique_ptr< IFunction > create_normalize_planar_yuv_layer (NormalizePlanarYUVLayerNode &node)
Create a backend normalize planar YUV layer function.
template<typename PadLayerFunction , typename TargetInfo >
std::unique_ptr< IFunction > create_pad_layer (PadLayerNode &node)
Create a backend pad layer function.
template<typename PermuteLayerFunction , typename TargetInfo >
std::unique_ptr< IFunction > create_permute_layer (PermuteLayerNode &node)
Create a backend permute layer function.
template<typename PoolingLayerFunction , typename TargetInfo >
std::unique_ptr< IFunction > create_pooling_layer (PoolingLayerNode &node)
Create a backend pooling layer function.
template<typename PReluFunction , typename TargetInfo >
std::unique_ptr< IFunction > create_prelu_layer (PReluLayerNode &node)
Create a backend PRelu layer function.
template<typename TargetInfo >
std::unique_ptr< IFunction > create_print_layer (PrintLayerNode &node)
Create a backend print layer function.
template<typename PriorBoxLayerFunction , typename TargetInfo >
std::unique_ptr< IFunction > create_priorbox_layer (PriorBoxLayerNode &node)
Create a backend priorbox layer function.
template<typename QuantizationLayerFunction , typename TargetInfo >
std::unique_ptr< IFunction > create_quantization_layer (QuantizationLayerNode &node)
Create a backend quantization layer function.
template<typename ReductionOperationFunction , typename TargetInfo >
std::unique_ptr< IFunction > create_reduction_operation_layer (ReductionLayerNode &node, GraphContext &ctx)
Create a backend reduction operation layer function.
template<typename ReorgLayerFunction , typename TargetInfo >
std::unique_ptr< IFunction > create_reorg_layer (ReorgLayerNode &node)
Create a backend reorg layer function.
template<typename ReshapeLayerFunction , typename TargetInfo >
std::unique_ptr< IFunction > create_reshape_layer (ReshapeLayerNode &node)
Create a backend reshape layer function.
template<typename ResizeLayerFunction , typename TargetInfo >
std::unique_ptr< IFunction > create_resize_layer (ResizeLayerNode &node)
Create a backend resize layer function.
template<typename ROIAlignLayerFunction , typename TargetInfo >
std::unique_ptr< IFunction > create_roi_align_layer (ROIAlignLayerNode &node)
Create a backend ROI align layer function.
template<typename SliceLayerFunction , typename TargetInfo >
std::unique_ptr< IFunction > create_slice_layer (SliceLayerNode &node)
Create a backend slice layer function.
template<typename SoftmaxLayerFunction , typename TargetInfo >
std::unique_ptr< IFunction > create_softmax_layer (SoftmaxLayerNode &node, GraphContext &ctx)
Create a backend softmax layer function.
template<typename StackLayerFunction , typename TargetInfo >
std::unique_ptr< arm_compute::IFunction > create_stack_layer (StackLayerNode &node)
Create a backend layer stack function.
template<typename StridedSliceLayerFunction , typename TargetInfo >
std::unique_ptr< IFunction > create_strided_slice_layer (StridedSliceLayerNode &node)
Create a backend slice layer function.
arm_compute::ITensorInfo * get_backing_tensor_info (arm_compute::graph::Tensor *tensor)
Returns backing tensor info of a given tensor.
template<typename ArgMinMaxLayer >
Status validate_arg_min_max_layer (ArgMinMaxLayerNode &node)
Validates a ArgMinMax layer node.
template<typename BoundingBoxTransformLayer >
Status validate_bounding_box_transform_layer (BoundingBoxTransformLayerNode &node)
Validates a Bounding Box Transform layer node.
template<typename ChannelShuffleLayer >
Status validate_channel_shuffle_layer (ChannelShuffleLayerNode &node)
Validates a Channel Shuffle layer node.
template<typename ConvolutionLayer , typename DirectConvolutionLayer , typename GEMMConvolutionLayer , typename WinogradConvolutionLayer >
Status validate_convolution_layer (ConvolutionLayerNode &node)
Validates a Convolution layer node.
template<typename DepthwiseConvolutionLayer >
Status validate_depthwise_convolution_layer (DepthwiseConvolutionLayerNode &node)
Validates a Depthwise Convolution layer node.
template<typename DepthToSpaceLayer >
Status validate_depth_to_space_layer (DepthToSpaceLayerNode &node)
Validates a depth to space layer node.
template<typename DequantizationLayer >
Status validate_dequantization_layer (DequantizationLayerNode &node)
Validates a dequantize layer node.
template<typename DetectionOutputLayer >
Status validate_detection_output_layer (DetectionOutputLayerNode &node)
Validates a detection output layer node.
template<typename DetectionPostProcessLayer >
Status validate_detection_post_process_layer (DetectionPostProcessLayerNode &node)
Validates a detection post process layer node.
template<typename GenerateProposalsLayer >
Status validate_generate_proposals_layer (GenerateProposalsLayerNode &node)
Validates a Generate Proposals layer node.
template<typename L2NormalizeLayer >
Status validate_l2_normalize_layer (L2NormalizeLayerNode &node)
Validates a L2Normalization layer node.
template<typename NormalizePlanarYUVLayer >
Status validate_normalize_planar_yuv_layer (NormalizePlanarYUVLayerNode &node)
Validates a NormalizePlanarYUV layer node.
template<typename PadLayer >
Status validate_pad_layer (PadLayerNode &node)
Validates a pad layer node.
template<typename PermuteLayer >
Status validate_permute_layer (PermuteLayerNode &node)
Validates a permute layer node.
template<typename PReluLayer >
Status validate_prelu_layer (PReluLayerNode &node)
Validates a PRelu layer node.
template<typename PriorBoxLayer >
Status validate_priorbox_layer (PriorBoxLayerNode &node)
Validates a priorbox layer node.
template<typename QuantizationLayer >
Status validate_quantization_layer (QuantizationLayerNode &node)
Validates a Quantization layer node.
template<typename ReductionLayer >
Status validate_reduction_operation_layer (ReductionLayerNode &node)
Validates a Reduction operation layer node.
template<typename ReorgLayer >
Status validate_reorg_layer (ReorgLayerNode &node)
Validates a Reorg layer node.
template<typename ReshapeLayer >
Status validate_reshape_layer (ReshapeLayerNode &node)
Validates a Reshape layer node.
template<typename ROIAlignLayer >
Status validate_roi_align_layer (ROIAlignLayerNode &node)
Validates a ROI Align layer node.
template<typename SliceLayer >
Status validate_slice_layer (SliceLayerNode &node)
Validates a Slice layer node.
template<typename StridedSliceLayer >
Status validate_strided_slice_layer (StridedSliceLayerNode &node)
Validates a Strided Slice layer node.
template<typename EltwiseLayerFunctions >
Status validate_eltwise_Layer (EltwiseLayerNode &node)
Validates a element-wise layer node.
template<typename UnaryEltwiseLayerFunctions >
Status validate_unary_eltwise_layer (UnaryEltwiseLayerNode &node)
Validates a unary element-wise layer node.
template<>
std::unique_ptr< IFunction > create_detection_output_layer< CPPDetectionOutputLayer, CLTargetInfo > (DetectionOutputLayerNode &node)
template<>
std::unique_ptr< IFunction > create_detection_post_process_layer< CPPDetectionPostProcessLayer, CLTargetInfo > (DetectionPostProcessLayerNode &node)
template<>
std::unique_ptr< IFunction > create_normalization_layer< NENormalizationLayer, NETargetInfo > (NormalizationLayerNode &node, GraphContext &ctx)
Function Documentation
create_activation_layer()
std::unique_ptr<IFunction> arm_compute::graph::backends::detail::create_activation_layer (ActivationLayerNode & node)
Creates a backend activation layer function.
Template Parameters
ActivationLayerFunction Backend activation function
TargetInfo Target-specific information
Parameters
[in] node Node to create the backend function for
Returns
Backend activation layer function
Definition at line 99 of file FunctionHelpers.h.
 {
     validate_node<TargetInfo>(node, 1 /* expected inputs */, 1 /* expected outputs */);
     // Extract IO and info
     typename TargetInfo::TensorType *input    = get_backing_tensor<TargetInfo>(node.input(0));
     typename TargetInfo::TensorType *output   = get_backing_tensor<TargetInfo>(node.output(0));
     const ActivationLayerInfo        act_info = node.activation_info();
     // Create function
     auto func = std::make_unique<ActivationLayerFunction>();
     func->configure(input, output, act_info);
     ARM_COMPUTE_LOG_GRAPH_INFO(
         "Instantiated " << node.name() << " Type: " << node.type() << " Target: " << TargetInfo::TargetType
                         << " Data Type: " << input->info()->data_type() << " Shape: " << input->info()->tensor_shape()
                         << " Activation function: " << act_info.activation() << " a: " << act_info.a() << " b: "
                         << act_info.b() << " InPlace : " << is_in_place_operation(input, output) << std::endl);
     return func;
 }
References arm_compute::test::validation::act_info, ActivationLayerNode::activation_info(), ARM_COMPUTE_LOG_GRAPH_INFO, INode::input(), arm_compute::test::validation::input, arm_compute::graph::backends::is_in_place_operation(), INode::name(), INode::output(), and ActivationLayerNode::type().
create_arg_min_max_layer()
std::unique_ptr<IFunction> arm_compute::graph::backends::detail::create_arg_min_max_layer (ArgMinMaxLayerNode & node)
Creates a backend argminmax layer function.
Template Parameters
ArgMinMaxLayerFunction Backend activation function
TargetInfo Target-specific information
Parameters
[in] node Node to create the backend function for
Returns
Backend argminmax layer function
Definition at line 131 of file FunctionHelpers.h.
 {
     validate_node<TargetInfo>(node, 1 /* expected inputs */, 1 /* expected outputs */);
     // Extract IO and info
     typename TargetInfo::TensorType *input  = get_backing_tensor<TargetInfo>(node.input(0));
     typename TargetInfo::TensorType *output = get_backing_tensor<TargetInfo>(node.output(0));
     const ReductionOperation         op     = node.reduction_operation();
     unsigned int                     axis   = node.axis();
     // Create function
     auto func = std::make_unique<ArgMinMaxLayerFunction>();
     func->configure(input, axis, output, op);
     ARM_COMPUTE_LOG_GRAPH_INFO("Instantiated " << node.name() << " Type: " << node.type() << " Target: "
                                                << TargetInfo::TargetType << " Data Type: " << input->info()->data_type()
                                                << " Shape: " << input->info()->tensor_shape()
                                                << " Reduction Operation: " << op << " axis: " << axis << std::endl);
     return func;
 }
References ARM_COMPUTE_LOG_GRAPH_INFO, ArgMinMaxLayerNode::axis(), INode::input(), arm_compute::test::validation::input, INode::name(), INode::output(), ArgMinMaxLayerNode::reduction_operation(), and ArgMinMaxLayerNode::type().
create_batch_normalization_layer()
std::unique_ptr<IFunction> arm_compute::graph::backends::detail::create_batch_normalization_layer (BatchNormalizationLayerNode & node)
Create a backend batch normalization layer function.
Template Parameters
BatchNormalizationLayerFunction Backend batch normalization function
TargetInfo Target-specific information
Parameters
[in] node Node to create the backend function for
Returns
Backend batch normalization layer function
Definition at line 163 of file FunctionHelpers.h.
 {
     validate_node<TargetInfo>(node, 5 /* expected inputs */, 1 /* expected outputs */);
     // Extract IO and info
     typename TargetInfo::TensorType *input = get_backing_tensor<TargetInfo>(node.input(0));
     typename TargetInfo::TensorType *mean  = get_backing_tensor<TargetInfo>(node.input(1));
     typename TargetInfo::TensorType *var   = get_backing_tensor<TargetInfo>(node.input(2));
     typename TargetInfo::TensorType *beta  = get_backing_tensor<TargetInfo>(node.input(3));
     typename TargetInfo::TensorType *gamma = get_backing_tensor<TargetInfo>(node.input(4));
     typename TargetInfo::TensorType *output    = get_backing_tensor<TargetInfo>(node.output(0));
     const float                      epsilon   = node.epsilon();
     const ActivationLayerInfo        fused_act = node.fused_activation();
     // Create and configure function
     auto func = std::make_unique<BatchNormalizationLayerFunction>();
     func->configure(input, output, mean, var, beta, gamma, epsilon, fused_act);
     // Log info
     ARM_COMPUTE_LOG_GRAPH_INFO("Instantiated " << node.name() << " Type: " << node.type() << " Target: "
                                                << TargetInfo::TargetType << " Data Type: " << input->info()->data_type()
                                                << " Shape: " << input->info()->tensor_shape() << " Epsilon: " << epsilon
                                                << " " << (fused_act.enabled() ? to_string(fused_act.activation()) : "")
                                                << " InPlace: " << is_in_place_operation(input, output) << std::endl);
     return func;
 }
References ActivationLayerInfo::activation(), ARM_COMPUTE_LOG_GRAPH_INFO, ActivationLayerInfo::enabled(), arm_compute::quantization::epsilon, BatchNormalizationLayerNode::epsilon(), BatchNormalizationLayerNode::fused_activation(), INode::input(), arm_compute::test::validation::input, arm_compute::graph::backends::is_in_place_operation(), INode::name(), INode::output(), arm_compute::to_string(), and BatchNormalizationLayerNode::type().
create_bounding_box_transform_layer()
std::unique_ptr<IFunction> arm_compute::graph::backends::detail::create_bounding_box_transform_layer (BoundingBoxTransformLayerNode & node)
Create a backend bounding box transform layer function.
Template Parameters
BoundingBoxTransformLayerFunction Backend bounding box transform function
TargetInfo Target-specific information
Parameters
[in] node Node to create the backend function for
Returns
Backend bounding box transform layer function
Definition at line 312 of file FunctionHelpers.h.
 {
     validate_node<TargetInfo>(node, 2 /* expected inputs */, 1 /* expected outputs */);
     // Extract IO and info
     typename TargetInfo::TensorType *input     = get_backing_tensor<TargetInfo>(node.input(0));
     typename TargetInfo::TensorType *deltas    = get_backing_tensor<TargetInfo>(node.input(1));
     typename TargetInfo::TensorType *output    = get_backing_tensor<TargetInfo>(node.output(0));
     const BoundingBoxTransformInfo   bbox_info = node.info();
     // Create and configure function
     auto func = std::make_unique<BoundingBoxTransformLayerFunction>();
     func->configure(input, output, deltas, bbox_info);
     // Log info
     ARM_COMPUTE_LOG_GRAPH_INFO(
         "Instantiated " << node.name() << " Type: " << node.type() << " Target: " << TargetInfo::TargetType
                         << " Data Type: " << input->info()->data_type() << " Shape: " << input->info()->tensor_shape()
                         << " BoundingBox Info img W: " << bbox_info.img_width() << " "
                         << " BoundingBox Info img H: " << bbox_info.img_height() << " " << std::endl);
     return std::move(func);
 }
References ARM_COMPUTE_LOG_GRAPH_INFO, BoundingBoxTransformInfo::img_height(), BoundingBoxTransformInfo::img_width(), BoundingBoxTransformLayerNode::info(), INode::input(), arm_compute::test::validation::input, INode::name(), INode::output(), and BoundingBoxTransformLayerNode::type().
create_channel_shuffle_layer()
std::unique_ptr<IFunction> arm_compute::graph::backends::detail::create_channel_shuffle_layer (ChannelShuffleLayerNode & node)
Create a backend channel shuffle layer function.
Template Parameters
ChannelShuffleLayerFunction Backend channel shuffle function
TargetInfo Target-specific information
Parameters
[in] node Node to create the backend function for
Returns
Backend channel shuffle layer function
Definition at line 346 of file FunctionHelpers.h.
 {
     validate_node<TargetInfo>(node, 1 /* expected inputs */, 1 /* expected outputs */);
     // Extract IO and info
     typename TargetInfo::TensorType *input      = get_backing_tensor<TargetInfo>(node.input(0));
     typename TargetInfo::TensorType *output     = get_backing_tensor<TargetInfo>(node.output(0));
     const unsigned int               num_groups = node.num_groups();
     // Create function
     auto func = std::make_unique<ChannelShuffleLayerFunction>();
     func->configure(input, output, num_groups);
     ARM_COMPUTE_LOG_GRAPH_INFO("Instantiated " << node.name() << " Type: " << node.type() << " Target: "
                                                << TargetInfo::TargetType << " Data Type: " << input->info()->data_type()
                                                << " Shape: " << input->info()->tensor_shape()
                                                << " Num groups: " << num_groups << std::endl);
     return func;
 }
References ARM_COMPUTE_LOG_GRAPH_INFO, INode::input(), arm_compute::test::validation::input, INode::name(), ChannelShuffleLayerNode::num_groups(), arm_compute::test::validation::num_groups, INode::output(), and ChannelShuffleLayerNode::type().
create_concatenate_layer()
std::unique_ptr<arm_compute::IFunction> arm_compute::graph::backends::detail::create_concatenate_layer (ConcatenateLayerNode & node)
Create a backend layer concatenate function.
Template Parameters
ConcatenateLayerFunction Backend concatenate function
TargetInfo Target-specific information
Parameters
[in] node Node to create the backend function for
Returns
Backend concatenate layer function
Definition at line 377 of file FunctionHelpers.h.
 {
     ARM_COMPUTE_LOG_GRAPH_VERBOSE("Creating Concatenate node with ID : " << node.id() << " and Name: " << node.name()
                                                                          << std::endl);
     ARM_COMPUTE_ERROR_ON(node.num_outputs() != 1);
     // Return nullptr if depth concatenate is switched off
     if (!node.is_enabled())
     {
         return nullptr;
     }
     // Extract IO and info
     std::vector<typename TargetInfo::SrcTensorType *> inputs;
     for (unsigned int i = 0; i < node.num_inputs(); ++i)
     {
         inputs.push_back(get_backing_tensor<TargetInfo>(node.input(i)));
     }
     typename TargetInfo::TensorType *output = get_backing_tensor<TargetInfo>(node.output(0));
     const DataLayout data_layout = node.output(0) != nullptr ? node.output(0)->desc().layout : DataLayout::UNKNOWN;
     const size_t     concat_axis = get_dimension_idx(data_layout, node.concatenation_axis());
     // Create and configure function
     auto func = std::make_unique<ConcatenateLayerFunction>();
     func->configure(inputs, output, concat_axis);
     // Log info
     const bool         is_quantized = is_data_type_quantized_asymmetric(output->info()->data_type());
     std::ostringstream qss;
     if (is_quantized)
     {
         qss << " Output QuantInfo: " << output->info()->quantization_info();
     }
     ARM_COMPUTE_LOG_GRAPH_INFO(
         "Instantiated " << node.name() << " Type: " << node.type() << " Target: " << TargetInfo::TargetType
                         << " Data Type: " << output->info()->data_type() << " Shape: " << output->info()->tensor_shape()
                         << " Num Inputs: " << inputs.size() << " Axis: " << concat_axis << qss.str() << std::endl);
     return func;
 }
References ARM_COMPUTE_ERROR_ON, ARM_COMPUTE_LOG_GRAPH_INFO, ARM_COMPUTE_LOG_GRAPH_VERBOSE, ConcatenateLayerNode::concatenation_axis(), arm_compute::cpu::data_layout, Tensor::desc(), arm_compute::graph::get_dimension_idx(), INode::id(), INode::input(), arm_compute::is_data_type_quantized_asymmetric(), ConcatenateLayerNode::is_enabled(), TensorDescriptor::layout, INode::name(), INode::num_inputs(), INode::num_outputs(), INode::output(), ConcatenateLayerNode::type(), and arm_compute::UNKNOWN.
create_convolution_layer()
std::unique_ptr<IFunction> arm_compute::graph::backends::detail::create_convolution_layer (ConvolutionLayerNode & node, GraphContext & ctx)
Create a backend convolution layer function.
Template Parameters
ConvolutionLayerFunctions Backend convolution functions
TargetInfo Target-specific information
Parameters
[in] node Node to create the backend function for
[in] ctx Graph context
Returns
Backend convolution layer function
Definition at line 429 of file FunctionHelpers.h.
 {
     validate_node<TargetInfo>(node, 3 /* expected inputs */, 1 /* expected outputs */);
     // Extract IO and info
     typename TargetInfo::TensorType *input   = get_backing_tensor<TargetInfo>(node.input(0));
     typename TargetInfo::TensorType *weights = get_backing_tensor<TargetInfo>(node.input(1));
     typename TargetInfo::TensorType *biases  = get_backing_tensor<TargetInfo>(node.input(2));
     typename TargetInfo::TensorType *output  = get_backing_tensor<TargetInfo>(node.output(0));
     const bool is_quantized = is_data_type_quantized_asymmetric(input->info()->data_type());
     if (is_quantized)
     {
         biases->info()->set_data_type(DataType::S32);
     }
     const PadStrideInfo       conv_info      = node.convolution_info();
     const unsigned int        num_groups     = node.num_groups();
     const ConvolutionMethod   conv_algorithm = node.convolution_method();
     const bool                fast_math      = node.fast_math_hint() == FastMathHint::Enabled;
     const ActivationLayerInfo fused_act      = node.fused_activation();
     // Create and configure function (we assume that functions have been validated before creation)
     std::shared_ptr<IMemoryManager> mm = get_memory_manager(ctx, TargetInfo::TargetType);
     std::unique_ptr<IFunction>      func;
     std::string                     func_name;
     if (conv_algorithm == ConvolutionMethod::Winograd)
     {
         ARM_COMPUTE_ERROR_ON_MSG(num_groups != 1, "WinogradConvolutionLayer does not support grouping!");
         std::tie(func, func_name) =
             create_named_memory_managed_function<typename ConvolutionLayerFunctions::WinogradConvolutionLayer>(
                 std::string("WinogradConvolutionLayer"), mm, input, weights, biases, output, conv_info, fused_act,
                 fast_math);
     }
     else if (conv_algorithm == ConvolutionMethod::Direct)
     {
         ARM_COMPUTE_ERROR_ON_MSG(num_groups != 1, "DirectConvolutionLayer does not support grouping!");
         std::tie(func, func_name) = create_named_function<typename ConvolutionLayerFunctions::DirectConvolutionLayer>(
             std::string("DirectConvolutionLayer"), input, weights, biases, output, conv_info, fused_act);
     }
     else if (conv_algorithm == ConvolutionMethod::GEMM)
     {
         std::tie(func, func_name) =
             create_named_memory_managed_function<typename ConvolutionLayerFunctions::GEMMConvolutionLayer>(
                 std::string("GEMMConvolutionLayer"), mm, input, weights, biases, output, conv_info, WeightsInfo(),
                 Size2D(1U, 1U), fused_act, num_groups);
     }
     else
     {
         std::tie(func, func_name) =
             create_named_memory_managed_function<typename ConvolutionLayerFunctions::GenericConvolutionLayer>(
                 std::string("GenericConvolutionLayer"), mm, input, weights, biases, output, conv_info, WeightsInfo(),
                 Size2D(1U, 1U), fused_act, fast_math, num_groups);
     }
     // Log info
     std::ostringstream qss;
     if (is_quantized)
     {
         qss << " Input QuantInfo: " << input->info()->quantization_info()
             << " Weights QuantInfo: " << weights->info()->quantization_info()
             << " Output QuantInfo: " << output->info()->quantization_info();
     }
     ARM_COMPUTE_LOG_GRAPH_INFO("Instantiated "
                                << node.name() << " Type: " << func_name << " Target: " << TargetInfo::TargetType
                                << " Data Type: " << input->info()->data_type() << " Groups: " << num_groups
                                << " Input shape: " << input->info()->tensor_shape()
                                << " Weights shape: " << weights->info()->tensor_shape()
                                << " Output shape: " << output->info()->tensor_shape() << qss.str()
                                << (fused_act.enabled() ? " " + to_string(fused_act.activation()) : "") << std::endl);
     return func;
 }
References ActivationLayerInfo::activation(), ARM_COMPUTE_ERROR_ON_MSG, ARM_COMPUTE_LOG_GRAPH_INFO, arm_compute::test::validation::conv_info, ConvolutionLayerNode::convolution_info(), ConvolutionLayerNode::convolution_method(), arm_compute::graph::Direct, ActivationLayerInfo::enabled(), arm_compute::graph::Enabled, ConvolutionLayerNode::fast_math_hint(), ConvolutionLayerNode::fused_activation(), arm_compute::graph::GEMM, arm_compute::graph::backends::get_memory_manager(), INode::input(), arm_compute::test::validation::input, arm_compute::is_data_type_quantized_asymmetric(), INode::name(), ConvolutionLayerNode::num_groups(), arm_compute::test::validation::num_groups, INode::output(), arm_compute::S32, arm_compute::to_string(), arm_compute::utils::cast::U, and arm_compute::graph::Winograd.
create_deconvolution_layer()
std::unique_ptr<IFunction> arm_compute::graph::backends::detail::create_deconvolution_layer (DeconvolutionLayerNode & node, GraphContext & ctx)
Create a backend deconvolution layer function.
Template Parameters
DeconvolutionLayerFunction Backend deconvolution function
TargetInfo Target-specific information
Parameters
[in] node Node to create the backend function for
[in] ctx Graph context
Returns
Backend deconvolution layer function
Definition at line 515 of file FunctionHelpers.h.
 {
     validate_node<TargetInfo>(node, 3 /* expected inputs */, 1 /* expected outputs */);
     // Extract IO and info
     typename TargetInfo::TensorType *input   = get_backing_tensor<TargetInfo>(node.input(0));
     typename TargetInfo::TensorType *weights = get_backing_tensor<TargetInfo>(node.input(1));
     typename TargetInfo::TensorType *biases  = get_backing_tensor<TargetInfo>(node.input(2));
     typename TargetInfo::TensorType *output  = get_backing_tensor<TargetInfo>(node.output(0));
     const PadStrideInfo deconv_info = node.deconvolution_info();
     // Create and configure function (we assume that functions have been validated before creation)
     std::shared_ptr<IMemoryManager> mm = get_memory_manager(ctx, TargetInfo::TargetType);
     std::unique_ptr<IFunction>      func;
     std::tie(func, std::ignore) = create_named_memory_managed_function<DeconvolutionLayerFunction>(
         std::string(), mm, input, weights, biases, output, deconv_info);
     // Log info
     ARM_COMPUTE_LOG_GRAPH_INFO("Instantiated " << node.name() << " Type: " << node.type() << " Target: "
                                                << TargetInfo::TargetType << " Data Type: " << input->info()->data_type()
                                                << " Input shape: " << input->info()->tensor_shape()
                                                << " Weights shape: " << weights->info()->tensor_shape()
                                                << " Output shape: " << output->info()->tensor_shape() << std::endl);
     return func;
 }
References ARM_COMPUTE_LOG_GRAPH_INFO, DeconvolutionLayerNode::deconvolution_info(), arm_compute::graph::backends::get_memory_manager(), INode::input(), arm_compute::test::validation::input, INode::name(), INode::output(), and DeconvolutionLayerNode::type().
create_depth_to_space_layer()
std::unique_ptr<IFunction> arm_compute::graph::backends::detail::create_depth_to_space_layer (DepthToSpaceLayerNode & node)
Create a backend depth to space layer function.
Template Parameters
DepthToSpaceLayerNode Function Backend depth to space function
TargetInfo Target-specific information
Parameters
[in] node Node to create the backend function for
Returns
Backend depth to space layer function
Definition at line 610 of file FunctionHelpers.h.
 {
     validate_node<TargetInfo>(node, 1 /* expected inputs */, 1 /* expected outputs */);
     // Extract IO and info
     typename TargetInfo::TensorType *input  = get_backing_tensor<TargetInfo>(node.input(0));
     typename TargetInfo::TensorType *output = get_backing_tensor<TargetInfo>(node.output(0));
     ARM_COMPUTE_ERROR_ON(input == nullptr);
     ARM_COMPUTE_ERROR_ON(output == nullptr);
     // Create and configure function
     auto func = std::make_unique<DepthToSpaceLayerFunction>();
     func->configure(input, output, node.block_shape());
     // Log info
     ARM_COMPUTE_LOG_GRAPH_INFO("Instantiated " << node.name() << " Type: " << node.type() << " Target: "
                                                << TargetInfo::TargetType << " Data Type: " << input->info()->data_type()
                                                << " Input shape: " << input->info()->tensor_shape()
                                                << " Block Size: " << node.block_shape()
                                                << " Output shape: " << output->info()->tensor_shape() << std::endl);
     return func;
 }
References ARM_COMPUTE_ERROR_ON, ARM_COMPUTE_LOG_GRAPH_INFO, DepthToSpaceLayerNode::block_shape(), INode::input(), arm_compute::test::validation::input, INode::name(), INode::output(), and DepthToSpaceLayerNode::type().
create_depthwise_convolution_layer()
std::unique_ptr<IFunction> arm_compute::graph::backends::detail::create_depthwise_convolution_layer (DepthwiseConvolutionLayerNode & node)
Create a backend layer depth-wise convolution function.
Template Parameters
DepthwiseConvolutionLayerFunctions Backend depthwise convolution function
TargetInfo Target-specific information
Parameters
[in] node Node to create the backend function for
Returns
Backend depth-wise convolution layer function
Definition at line 553 of file FunctionHelpers.h.
 {
     validate_node<TargetInfo>(node, 3 /* expected inputs */, 1 /* expected outputs */);
     // Extract IO and info
     typename TargetInfo::TensorType *input   = get_backing_tensor<TargetInfo>(node.input(0));
     typename TargetInfo::TensorType *weights = get_backing_tensor<TargetInfo>(node.input(1));
     typename TargetInfo::TensorType *biases  = get_backing_tensor<TargetInfo>(node.input(2));
     typename TargetInfo::TensorType *output  = get_backing_tensor<TargetInfo>(node.output(0));
     const bool is_quantized = is_data_type_quantized_asymmetric(input->info()->data_type());
     if (is_quantized)
     {
         biases->info()->set_data_type(DataType::S32);
     }
     const PadStrideInfo       conv_info        = node.convolution_info();
     const unsigned int        depth_multiplier = node.depth_multiplier();
     const ActivationLayerInfo fused_act        = node.fused_activation();
     // Create and configure function (we assume that functions have been validated before creation)
     std::unique_ptr<IFunction> func;
     std::string                func_name;
     std::tie(func, func_name) =
         create_named_function<DepthwiseConvolutionLayer>(std::string("DepthwiseConvolutionLayer"), input, weights,
                                                          biases, output, conv_info, depth_multiplier, fused_act);
     // Log info
     std::ostringstream qss;
     if (is_quantized)
     {
         qss << " Input QuantInfo: " << input->info()->quantization_info()
             << " Weights QuantInfo: " << weights->info()->quantization_info()
             << " Output QuantInfo: " << output->info()->quantization_info();
     }
     ARM_COMPUTE_LOG_GRAPH_INFO("Instantiated "
                                << node.name() << " Type: " << func_name << " Target: " << TargetInfo::TargetType
                                << " Data Type: " << input->info()->data_type() << " Input shape: "
                                << input->info()->tensor_shape() << " Weights shape: " << weights->info()->tensor_shape()
                                << " Output shape: " << output->info()->tensor_shape()
                                << " Depth multiplier: " << depth_multiplier << qss.str()
                                << (fused_act.enabled() ? " " + to_string(fused_act.activation()) : "") << std::endl);
     return func;
 }
References ActivationLayerInfo::activation(), ARM_COMPUTE_LOG_GRAPH_INFO, arm_compute::test::validation::conv_info, DepthwiseConvolutionLayerNode::convolution_info(), DepthwiseConvolutionLayerNode::depth_multiplier(), ActivationLayerInfo::enabled(), DepthwiseConvolutionLayerNode::fused_activation(), INode::input(), arm_compute::test::validation::input, arm_compute::is_data_type_quantized_asymmetric(), INode::name(), INode::output(), arm_compute::S32, and arm_compute::to_string().
create_dequantization_layer()
std::unique_ptr<IFunction> arm_compute::graph::backends::detail::create_dequantization_layer (DequantizationLayerNode & node)
Create a backend dequantize layer function.
Template Parameters
DequantizationLayer Function Backend dequantize function
TargetInfo Target-specific information
Parameters
[in] node Node to create the backend function for
Returns
Backend dequantize layer function
Definition at line 645 of file FunctionHelpers.h.
 {
     validate_node<TargetInfo>(node, 1 /* expected inputs */, 1 /* expected outputs */);
     // Extract IO and info
     typename TargetInfo::TensorType *input  = get_backing_tensor<TargetInfo>(node.input(0));
     typename TargetInfo::TensorType *output = get_backing_tensor<TargetInfo>(node.output(0));
     ARM_COMPUTE_ERROR_ON(input == nullptr);
     ARM_COMPUTE_ERROR_ON(output == nullptr);
     // Create and configure function
     auto func = std::make_unique<DequantizationLayerFunction>();
     func->configure(input, output);
     // Log info
     ARM_COMPUTE_LOG_GRAPH_INFO("Instantiated " << node.name() << " Type: " << node.type() << " Target: "
                                                << TargetInfo::TargetType << " Data Type: " << input->info()->data_type()
                                                << " Input shape: " << input->info()->tensor_shape()
                                                << " Input quantization info: " << output->info()->quantization_info()
                                                << " Output shape: " << output->info()->tensor_shape() << std::endl);
     return func;
 }
References ARM_COMPUTE_ERROR_ON, ARM_COMPUTE_LOG_GRAPH_INFO, INode::input(), arm_compute::test::validation::input, INode::name(), INode::output(), and DequantizationLayerNode::type().
create_detection_output_layer()
std::unique_ptr<IFunction> arm_compute::graph::backends::detail::create_detection_output_layer (DetectionOutputLayerNode & node)
Create a backend detection output layer function.
Template Parameters
DetectionOutputLayer Function Backend detection output function
TargetInfo Target-specific information
Parameters
[in] node Node to create the backend function for
Returns
Backend detection output layer function
Definition at line 679 of file FunctionHelpers.h.
 {
     validate_node<TargetInfo>(node, 3 /* expected inputs */, 1 /* expected outputs */);
     // Extract IO and info
     typename TargetInfo::TensorType *input0      = get_backing_tensor<TargetInfo>(node.input(0));
     typename TargetInfo::TensorType *input1      = get_backing_tensor<TargetInfo>(node.input(1));
     typename TargetInfo::TensorType *input2      = get_backing_tensor<TargetInfo>(node.input(2));
     typename TargetInfo::TensorType *output      = get_backing_tensor<TargetInfo>(node.output(0));
     const DetectionOutputLayerInfo   detect_info = node.detection_output_info();
     ARM_COMPUTE_ERROR_ON(input0 == nullptr);
     ARM_COMPUTE_ERROR_ON(input1 == nullptr);
     ARM_COMPUTE_ERROR_ON(input2 == nullptr);
     ARM_COMPUTE_ERROR_ON(output == nullptr);
     // Create and configure function
     auto func = std::make_unique<DetectionOutputLayerFunction>();
     func->configure(input0, input1, input2, output, detect_info);
     // Log info
     ARM_COMPUTE_LOG_GRAPH_INFO("Instantiated "
                                << node.name() << " Type: " << node.type() << " Target: " << TargetInfo::TargetType
                                << " Data Type: " << input0->info()->data_type() << " Input0 shape: "
                                << input0->info()->tensor_shape() << " Input1 shape: " << input1->info()->tensor_shape()
                                << " Input2 shape: " << input2->info()->tensor_shape()
                                << " Output shape: " << output->info()->tensor_shape()
                                << " DetectionOutputLayer info: " << detect_info << std::endl);
     return func;
 }
References ARM_COMPUTE_ERROR_ON, ARM_COMPUTE_LOG_GRAPH_INFO, DetectionOutputLayerNode::detection_output_info(), INode::input(), INode::name(), INode::output(), and DetectionOutputLayerNode::type().
create_detection_output_layer< CPPDetectionOutputLayer, CLTargetInfo >()
std::unique_ptr<IFunction> arm_compute::graph::backends::detail::create_detection_output_layer< CPPDetectionOutputLayer, CLTargetInfo > (DetectionOutputLayerNode & node)
Definition at line 130 of file CLFunctionsFactory.cpp.
 {
     validate_node<CLTargetInfo>(node, 3 /* expected inputs */, 1 /* expected outputs */);
     // Extract IO and info
     CLTargetInfo::TensorType      *input0      = get_backing_tensor<CLTargetInfo>(node.input(0));
     CLTargetInfo::TensorType      *input1      = get_backing_tensor<CLTargetInfo>(node.input(1));
     CLTargetInfo::TensorType      *input2      = get_backing_tensor<CLTargetInfo>(node.input(2));
     CLTargetInfo::TensorType      *output      = get_backing_tensor<CLTargetInfo>(node.output(0));
     const DetectionOutputLayerInfo detect_info = node.detection_output_info();
     ARM_COMPUTE_ERROR_ON(input0 == nullptr);
     ARM_COMPUTE_ERROR_ON(input1 == nullptr);
     ARM_COMPUTE_ERROR_ON(input2 == nullptr);
     ARM_COMPUTE_ERROR_ON(output == nullptr);
     // Create and configure function
     auto func = std::make_unique<CPPDetectionOutputLayer>();
     func->configure(input0, input1, input2, output, detect_info);
     // Log info
     ARM_COMPUTE_LOG_GRAPH_INFO("Instantiated "
                                << node.name() << " Type: " << node.type() << " Target: " << CLTargetInfo::TargetType
                                << " Data Type: " << input0->info()->data_type() << " Input0 shape: "
                                << input0->info()->tensor_shape() << " Input1 shape: " << input1->info()->tensor_shape()
                                << " Input2 shape: " << input2->info()->tensor_shape()
                                << " Output shape: " << output->info()->tensor_shape()
                                << " DetectionOutputLayer info: " << detect_info << std::endl);
     auto wrap_function = std::make_unique<CPPWrapperFunction>();
     wrap_function->register_function(std::move(func));
     wrap_function->register_tensor(input0);
     wrap_function->register_tensor(input1);
     wrap_function->register_tensor(input2);
     wrap_function->register_tensor(output);
     return std::move(wrap_function);
 }
References ARM_COMPUTE_ERROR_ON, ARM_COMPUTE_LOG_GRAPH_INFO, ITensorInfo::data_type(), DetectionOutputLayerNode::detection_output_info(), ITensor::info(), INode::input(), INode::name(), INode::output(), ITensorInfo::tensor_shape(), and DetectionOutputLayerNode::type().
Referenced by CLFunctionFactory::create().
create_detection_post_process_layer()
std::unique_ptr<IFunction> arm_compute::graph::backends::detail::create_detection_post_process_layer (DetectionPostProcessLayerNode & node)
Create a backend detection post process layer function.
Template Parameters
DetectionPostProcessLayerFunction Backend detection output function
TargetInfo Target-specific information
Parameters
[in] node Node to create the backend function for
Returns
Backend detection post process layer function
Definition at line 721 of file FunctionHelpers.h.
 {
     validate_node<TargetInfo>(node, 3 /* expected inputs */, 4 /* expected outputs */);
     // Extract IO and info
     typename TargetInfo::TensorType    *input0      = get_backing_tensor<TargetInfo>(node.input(0));
     typename TargetInfo::TensorType    *input1      = get_backing_tensor<TargetInfo>(node.input(1));
     typename TargetInfo::TensorType    *input2      = get_backing_tensor<TargetInfo>(node.input(2));
     typename TargetInfo::TensorType    *output0     = get_backing_tensor<TargetInfo>(node.output(0));
     typename TargetInfo::TensorType    *output1     = get_backing_tensor<TargetInfo>(node.output(1));
     typename TargetInfo::TensorType    *output2     = get_backing_tensor<TargetInfo>(node.output(2));
     typename TargetInfo::TensorType    *output3     = get_backing_tensor<TargetInfo>(node.output(3));
     const DetectionPostProcessLayerInfo detect_info = node.detection_post_process_info();
     ARM_COMPUTE_ERROR_ON(input0 == nullptr);
     ARM_COMPUTE_ERROR_ON(input1 == nullptr);
     ARM_COMPUTE_ERROR_ON(input2 == nullptr);
     ARM_COMPUTE_ERROR_ON(output0 == nullptr);
     ARM_COMPUTE_ERROR_ON(output1 == nullptr);
     ARM_COMPUTE_ERROR_ON(output2 == nullptr);
     ARM_COMPUTE_ERROR_ON(output3 == nullptr);
     // Create and configure function
     auto func = std::make_unique<DetectionPostProcessLayerFunction>();
     func->configure(input0, input1, input2, output0, output1, output2, output3, detect_info);
     // Log info
     ARM_COMPUTE_LOG_GRAPH_INFO("Instantiated "
                                << node.name() << " Type: " << node.type() << " Target: " << TargetInfo::TargetType
                                << " Data Type: " << input0->info()->data_type() << " Input0 shape: "
                                << input0->info()->tensor_shape() << " Input1 shape: " << input1->info()->tensor_shape()
                                << " Input2 shape: " << input2->info()->tensor_shape()
                                << " Output0 shape: " << output0->info()->tensor_shape()
                                << " Output1 shape: " << output1->info()->tensor_shape()
                                << " Output2 shape: " << output2->info()->tensor_shape()
                                << " Output3 shape: " << output3->info()->tensor_shape()
                                << " DetectionPostProcessLayer info: " << detect_info << std::endl);
     return func;
 }
References ARM_COMPUTE_ERROR_ON, ARM_COMPUTE_LOG_GRAPH_INFO, DetectionPostProcessLayerNode::detection_post_process_info(), INode::input(), INode::name(), INode::output(), and DetectionPostProcessLayerNode::type().
create_detection_post_process_layer< CPPDetectionPostProcessLayer, CLTargetInfo >()
std::unique_ptr<IFunction> arm_compute::graph::backends::detail::create_detection_post_process_layer< CPPDetectionPostProcessLayer, CLTargetInfo > (DetectionPostProcessLayerNode & node)
Definition at line 171 of file CLFunctionsFactory.cpp.
 {
     validate_node<CLTargetInfo>(node, 3 /* expected inputs */, 4 /* expected outputs */);
     // Extract IO and info
     CLTargetInfo::TensorType           *input0      = get_backing_tensor<CLTargetInfo>(node.input(0));
     CLTargetInfo::TensorType           *input1      = get_backing_tensor<CLTargetInfo>(node.input(1));
     CLTargetInfo::TensorType           *input2      = get_backing_tensor<CLTargetInfo>(node.input(2));
     CLTargetInfo::TensorType           *output0     = get_backing_tensor<CLTargetInfo>(node.output(0));
     CLTargetInfo::TensorType           *output1     = get_backing_tensor<CLTargetInfo>(node.output(1));
     CLTargetInfo::TensorType           *output2     = get_backing_tensor<CLTargetInfo>(node.output(2));
     CLTargetInfo::TensorType           *output3     = get_backing_tensor<CLTargetInfo>(node.output(3));
     const DetectionPostProcessLayerInfo detect_info = node.detection_post_process_info();
     ARM_COMPUTE_ERROR_ON(input0 == nullptr);
     ARM_COMPUTE_ERROR_ON(input1 == nullptr);
     ARM_COMPUTE_ERROR_ON(input2 == nullptr);
     ARM_COMPUTE_ERROR_ON(output0 == nullptr);
     ARM_COMPUTE_ERROR_ON(output1 == nullptr);
     ARM_COMPUTE_ERROR_ON(output2 == nullptr);
     ARM_COMPUTE_ERROR_ON(output3 == nullptr);
     // Create and configure function
     auto func = std::make_unique<CPPDetectionPostProcessLayer>();
     func->configure(input0, input1, input2, output0, output1, output2, output3, detect_info);
     // Log info
     ARM_COMPUTE_LOG_GRAPH_INFO("Instantiated "
                                << node.name() << " Type: " << node.type() << " Target: " << CLTargetInfo::TargetType
                                << " Data Type: " << input0->info()->data_type() << " Input0 shape: "
                                << input0->info()->tensor_shape() << " Input1 shape: " << input1->info()->tensor_shape()
                                << " Input2 shape: " << input2->info()->tensor_shape()
                                << " Output0 shape: " << output0->info()->tensor_shape()
                                << " Output1 shape: " << output1->info()->tensor_shape()
                                << " Output2 shape: " << output2->info()->tensor_shape()
                                << " Output3 shape: " << output3->info()->tensor_shape()
                                << " DetectionPostProcessLayer info: " << detect_info << std::endl);
     auto wrap_function = std::make_unique<CPPWrapperFunction>();
     wrap_function->register_function(std::move(func));
     wrap_function->register_tensor(input0);
     wrap_function->register_tensor(input1);
     wrap_function->register_tensor(input2);
     wrap_function->register_tensor(output0);
     wrap_function->register_tensor(output1);
     wrap_function->register_tensor(output2);
     wrap_function->register_tensor(output3);
     return std::move(wrap_function);
 }
References ARM_COMPUTE_ERROR_ON, ARM_COMPUTE_LOG_GRAPH_INFO, ITensorInfo::data_type(), DetectionPostProcessLayerNode::detection_post_process_info(), ITensor::info(), INode::input(), INode::name(), INode::output(), ITensorInfo::tensor_shape(), and DetectionPostProcessLayerNode::type().
Referenced by CLFunctionFactory::create().
create_eltwise_layer()
std::unique_ptr<IFunction> arm_compute::graph::backends::detail::create_eltwise_layer (EltwiseLayerNode & node)
Create a backend element-wise operation layer function.
Template Parameters
EltwiseFunctions Backend element-wise function
TargetInfo Target-specific information
Parameters
[in] node Node to create the backend function for
Returns
Backend element-wise operation layer function
Definition at line 772 of file FunctionHelpers.h.
 {
     validate_node<TargetInfo>(node, 2 /* expected inputs */, 1 /* expected outputs */);
     // Extract IO and info
     typename TargetInfo::TensorType *input1         = get_backing_tensor<TargetInfo>(node.input(0));
     typename TargetInfo::TensorType *input2         = get_backing_tensor<TargetInfo>(node.input(1));
     typename TargetInfo::TensorType *output         = get_backing_tensor<TargetInfo>(node.output(0));
     const EltwiseOperation           eltwise_op     = node.eltwise_operation();
     const ConvertPolicy              convert_policy = node.convert_policy();
     const ActivationLayerInfo        act_info       = node.fused_activation();
     ARM_COMPUTE_ERROR_ON(input1 == nullptr);
     ARM_COMPUTE_ERROR_ON(input2 == nullptr);
     ARM_COMPUTE_ERROR_ON(output == nullptr);
     std::unique_ptr<IFunction> func = nullptr;
     std::string                func_name;
     if (eltwise_op == EltwiseOperation::Add)
     {
         std::tie(func, func_name) = create_named_function<typename EltwiseFunctions::Addition>(
             std::string("ArithmeticAddition"), input1, input2, output, convert_policy, act_info);
     }
     else if (eltwise_op == EltwiseOperation::Sub)
     {
         std::tie(func, func_name) = create_named_function<typename EltwiseFunctions::Subtraction>(
             std::string("ArithmeticSubtraction"), input1, input2, output, convert_policy, act_info);
     }
     else if (eltwise_op == EltwiseOperation::Mul)
     {
         std::tie(func, func_name) = create_named_function<typename EltwiseFunctions::Multiplication>(
             std::string("PixelWiseMultiplication"), input1, input2, output, 1.f, convert_policy, node.rounding_policy(),
             act_info);
     }
     else if (eltwise_op == EltwiseOperation::Max)
     {
         std::tie(func, func_name) = create_named_function<typename EltwiseFunctions::Maximum>(
             std::string("ElementwiseMaximum"), input1, input2, output, act_info);
     }
     else if (eltwise_op == EltwiseOperation::Div)
     {
         std::tie(func, func_name) = create_named_function<typename EltwiseFunctions::Division>(
             std::string("ArithmeticDivision"), input1, input2, output, act_info);
     }
     else
     {
         ARM_COMPUTE_ERROR("Unsupported element-wise operation!");
     }
     // Log info
     ARM_COMPUTE_LOG_GRAPH_INFO("Instantiated " << node.name() << " Type: " << node.type()
                                                << " Target: " << TargetInfo::TargetType << " Operation: " << func_name
                                                << " Data Type: " << input1->info()->data_type()
                                                << " Shape: " << input1->info()->tensor_shape() << std::endl);
     return func;
 }
References arm_compute::test::validation::act_info, arm_compute::graph::Add, ARM_COMPUTE_ERROR, ARM_COMPUTE_ERROR_ON, ARM_COMPUTE_LOG_GRAPH_INFO, EltwiseLayerNode::convert_policy(), arm_compute::graph::Div, EltwiseLayerNode::eltwise_operation(), EltwiseLayerNode::fused_activation(), INode::input(), arm_compute::graph::Max, arm_compute::graph::Mul, INode::name(), INode::output(), EltwiseLayerNode::rounding_policy(), arm_compute::graph::Sub, and EltwiseLayerNode::type().
create_flatten_layer()
std::unique_ptr<IFunction> arm_compute::graph::backends::detail::create_flatten_layer (FlattenLayerNode & node)
Create a backend flatten layer function.
Template Parameters
FlattenLayerFunction Backend flatten function
TargetInfo Target-specific information
Parameters
[in] node Node to create the backend function for
Returns
Backend flatten layer function
Definition at line 882 of file FunctionHelpers.h.
 {
     validate_node<TargetInfo>(node, 1 /* expected inputs */, 1 /* expected outputs */);
     // Extract IO and info
     typename TargetInfo::TensorType *input  = get_backing_tensor<TargetInfo>(node.input(0));
     typename TargetInfo::TensorType *output = get_backing_tensor<TargetInfo>(node.output(0));
     ARM_COMPUTE_ERROR_ON(input == nullptr);
     ARM_COMPUTE_ERROR_ON(output == nullptr);
     // Create and configure function
     auto func = std::make_unique<FlattenLayerFunction>();
     func->configure(input, output);
     // Log info
     ARM_COMPUTE_LOG_GRAPH_INFO("Instantiated " << node.name() << " Type: " << node.type() << " Target: "
                                                << TargetInfo::TargetType << " Data Type: " << input->info()->data_type()
                                                << " Input shape: " << input->info()->tensor_shape()
                                                << " Output shape: " << output->info()->tensor_shape() << std::endl);
     return func;
 }
References ARM_COMPUTE_ERROR_ON, ARM_COMPUTE_LOG_GRAPH_INFO, INode::input(), arm_compute::test::validation::input, INode::name(), INode::output(), and FlattenLayerNode::type().
create_fully_connected_layer()
std::unique_ptr<IFunction> arm_compute::graph::backends::detail::create_fully_connected_layer (FullyConnectedLayerNode & node, GraphContext & ctx)
Create a backend fully connected layer function.
Template Parameters
FullyConnectedLayerFunction Backend fully-connected function
TargetInfo Target-specific information
Parameters
[in] node Node to create the backend function for
[in] ctx Graph context
Returns
Backend fully connected layer function
Definition at line 917 of file FunctionHelpers.h.
 {
     validate_node<TargetInfo>(node, 3 /* expected inputs */, 1 /* expected outputs */);
     // Extract IO and info
     typename TargetInfo::TensorType *input   = get_backing_tensor<TargetInfo>(node.input(0));
     typename TargetInfo::TensorType *weights = get_backing_tensor<TargetInfo>(node.input(1));
     typename TargetInfo::TensorType *biases  = get_backing_tensor<TargetInfo>(node.input(2));
     typename TargetInfo::TensorType *output  = get_backing_tensor<TargetInfo>(node.output(0));
     FullyConnectedLayerInfo          fc_info = node.info();
     fc_info.enable_fast_math                 = (node.fast_math_hint() == FastMathHint::Enabled);
     ARM_COMPUTE_ERROR_ON(input == nullptr);
     ARM_COMPUTE_ERROR_ON(weights == nullptr);
     ARM_COMPUTE_ERROR_ON(output == nullptr);
     // Create and configure function
     auto wm   = get_weights_manager(ctx, TargetInfo::TargetType);
     auto mm   = get_memory_manager(ctx, TargetInfo::TargetType);
     auto func = std::make_unique<FullyConnectedLayerFunction>(mm, wm.get());
     func->configure(input, weights, biases, output, fc_info);
     const bool is_quantized = is_data_type_quantized_asymmetric(input->info()->data_type());
     // Log info
     std::ostringstream qss;
     if (is_quantized)
     {
         qss << " Input QuantInfo: " << input->info()->quantization_info()
             << " Weights QuantInfo: " << weights->info()->quantization_info()
             << " Output QuantInfo: " << output->info()->quantization_info();
     }
     ARM_COMPUTE_LOG_GRAPH_INFO("Instantiated " << node.name() << " Type: " << node.type() << " Target: "
                                                << TargetInfo::TargetType << " Data Type: " << input->info()->data_type()
                                                << qss.str() << " Input shape: " << input->info()->tensor_shape()
                                                << " Weights shape: " << weights->info()->tensor_shape()
                                                << " Output shape: " << output->info()->tensor_shape() << std::endl);
     return func;
 }
References ARM_COMPUTE_ERROR_ON, ARM_COMPUTE_LOG_GRAPH_INFO, FullyConnectedLayerInfo::enable_fast_math, arm_compute::graph::Enabled, FullyConnectedLayerNode::fast_math_hint(), arm_compute::graph::backends::get_memory_manager(), arm_compute::graph::backends::get_weights_manager(), FullyConnectedLayerNode::info(), INode::input(), arm_compute::test::validation::input, arm_compute::is_data_type_quantized_asymmetric(), INode::name(), INode::output(), and FullyConnectedLayerNode::type().
create_fused_convolution_batch_normalization_layer()
std::unique_ptr<IFunction> arm_compute::graph::backends::detail::create_fused_convolution_batch_normalization_layer (FusedConvolutionBatchNormalizationNode & node, GraphContext & ctx)
Create a backend batch normalization layer function.
Template Parameters
BatchNormalizationLayerFunction Backend batch normalization function
TargetInfo Target-specific information
Parameters
[in] node Node to create the backend function for
[in] ctx Graph context
Returns
Backend batch normalization layer function
Definition at line 204 of file FunctionHelpers.h.
 {
     validate_node<TargetInfo>(node, 7 /* expected inputs */, 1 /* expected outputs */);
     // Extract IO and info
     typename TargetInfo::TensorType *input   = get_backing_tensor<TargetInfo>(node.input(0));
     typename TargetInfo::TensorType *weights = get_backing_tensor<TargetInfo>(node.input(1));
     typename TargetInfo::TensorType *biases  = get_backing_tensor<TargetInfo>(node.input(2));
     typename TargetInfo::TensorType *mean    = get_backing_tensor<TargetInfo>(node.input(3));
     typename TargetInfo::TensorType *var     = get_backing_tensor<TargetInfo>(node.input(4));
     typename TargetInfo::TensorType *beta    = get_backing_tensor<TargetInfo>(node.input(5));
     typename TargetInfo::TensorType *gamma   = get_backing_tensor<TargetInfo>(node.input(6));
     typename TargetInfo::TensorType *output = get_backing_tensor<TargetInfo>(node.output(0));
     const PadStrideInfo       conv_info  = node.convolution_info();
     const unsigned int        num_groups = node.num_groups();
     const bool                fast_math  = node.fast_math_hint() == FastMathHint::Enabled;
     const ActivationLayerInfo fused_act  = node.fused_activation();
     const float               epsilon    = node.epsilon();
     // Create and configure function (we assume that functions have been validated before creation)
     std::shared_ptr<IMemoryManager> mm = get_memory_manager(ctx, TargetInfo::TargetType);
     std::unique_ptr<IFunction>      func;
     std::string                     func_name;
     using FType = FusedConvolutionBatchNormalizationFunction<TargetInfo, FusedLayerTypes>;
     // Create and configure function
     std::tie(func, func_name) = create_named_memory_managed_function<FType>(
         std::string("FusedConvolutionBatchNormalizationLayer"), mm, input, weights, biases, output, mean, var, beta,
         gamma, epsilon, conv_info, num_groups, fast_math, fused_act);
     // Log info
     ARM_COMPUTE_LOG_GRAPH_INFO("Instantiated "
                                << node.name() << " Type: " << node.type() << " Target: " << TargetInfo::TargetType
                                << " Data Type: " << input->info()->data_type() << " Input shape: "
                                << input->info()->tensor_shape() << " Weights shape: " << weights->info()->tensor_shape()
                                << " Output shape: " << output->info()->tensor_shape()
                                << (fused_act.enabled() ? " " + to_string(fused_act.activation()) : "") << std::endl);
     return func;
 }
References ActivationLayerInfo::activation(), ARM_COMPUTE_LOG_GRAPH_INFO, arm_compute::test::validation::conv_info, FusedConvolutionBatchNormalizationNode::convolution_info(), ActivationLayerInfo::enabled(), arm_compute::graph::Enabled, arm_compute::quantization::epsilon, FusedConvolutionBatchNormalizationNode::epsilon(), FusedConvolutionBatchNormalizationNode::fast_math_hint(), FusedConvolutionBatchNormalizationNode::fused_activation(), arm_compute::graph::backends::get_memory_manager(), INode::input(), arm_compute::test::validation::input, INode::name(), FusedConvolutionBatchNormalizationNode::num_groups(), arm_compute::test::validation::num_groups, INode::output(), arm_compute::to_string(), and FusedConvolutionBatchNormalizationNode::type().
create_fused_depthwise_convolution_batch_normalization_layer()
std::unique_ptr<IFunction> arm_compute::graph::backends::detail::create_fused_depthwise_convolution_batch_normalization_layer (FusedDepthwiseConvolutionBatchNormalizationNode & node, GraphContext & ctx)
Create a backend fused depthwise convolution batch normalization layer function.
Template Parameters
FusedLayerTypes Fused layer types
TargetInfo Target-specific information
Parameters
[in] node Node to create the backend function for
[in] ctx Graph context
Returns
Backend fused depthwise convolution batch normalization layer function
Definition at line 259 of file FunctionHelpers.h.
 {
     validate_node<TargetInfo>(node, 7 /* expected inputs */, 1 /* expected outputs */);
     // Extract IO and info
     typename TargetInfo::TensorType *input   = get_backing_tensor<TargetInfo>(node.input(0));
     typename TargetInfo::TensorType *weights = get_backing_tensor<TargetInfo>(node.input(1));
     typename TargetInfo::TensorType *biases  = get_backing_tensor<TargetInfo>(node.input(2));
     typename TargetInfo::TensorType *mean    = get_backing_tensor<TargetInfo>(node.input(3));
     typename TargetInfo::TensorType *var     = get_backing_tensor<TargetInfo>(node.input(4));
     typename TargetInfo::TensorType *beta    = get_backing_tensor<TargetInfo>(node.input(5));
     typename TargetInfo::TensorType *gamma   = get_backing_tensor<TargetInfo>(node.input(6));
     typename TargetInfo::TensorType *output = get_backing_tensor<TargetInfo>(node.output(0));
     const PadStrideInfo       conv_info        = node.convolution_info();
     const unsigned int        depth_multiplier = node.depth_multiplier();
     const ActivationLayerInfo fused_act        = node.fused_activation();
     const float               epsilon          = node.epsilon();
     // Create and configure function (we assume that functions have been validated before creation)
     std::shared_ptr<IMemoryManager> mm = get_memory_manager(ctx, TargetInfo::TargetType);
     std::unique_ptr<IFunction>      func;
     std::string                     func_name;
     using FType = FusedDepthwiseConvolutionBatchNormalizationFunction<TargetInfo, FusedLayerTypes>;
     // Create and configure function
     std::tie(func, func_name) = create_named_memory_managed_function<FType>(
         std::string("FusedDepthwiseConvolutionBatchNormalizationLayer"), mm, input, weights, biases, output, mean, var,
         beta, gamma, epsilon, conv_info, depth_multiplier, fused_act);
     // Log info
     ARM_COMPUTE_LOG_GRAPH_INFO("Instantiated "
                                << node.name() << " Type: " << node.type() << " Target: " << TargetInfo::TargetType
                                << " Data Type: " << input->info()->data_type() << " Input shape: "
                                << input->info()->tensor_shape() << " Weights shape: " << weights->info()->tensor_shape()
                                << " Output shape: " << output->info()->tensor_shape()
                                << (fused_act.enabled() ? " " + to_string(fused_act.activation()) : "") << std::endl);
     return func;
 }
References ActivationLayerInfo::activation(), ARM_COMPUTE_LOG_GRAPH_INFO, arm_compute::test::validation::conv_info, FusedDepthwiseConvolutionBatchNormalizationNode::convolution_info(), FusedDepthwiseConvolutionBatchNormalizationNode::depth_multiplier(), ActivationLayerInfo::enabled(), arm_compute::quantization::epsilon, FusedDepthwiseConvolutionBatchNormalizationNode::epsilon(), FusedDepthwiseConvolutionBatchNormalizationNode::fused_activation(), arm_compute::graph::backends::get_memory_manager(), INode::input(), arm_compute::test::validation::input, INode::name(), INode::output(), arm_compute::to_string(), and FusedDepthwiseConvolutionBatchNormalizationNode::type().
Referenced by CLFunctionFactory::create(), and NEFunctionFactory::create().
create_generate_proposals_layer()
std::unique_ptr<IFunction> arm_compute::graph::backends::detail::create_generate_proposals_layer (GenerateProposalsLayerNode & node, GraphContext & ctx)
Create a backend generate proposals layer function.
Template Parameters
GenerateProposalsLayerFunction Backend generate proposals function
TargetInfo Target-specific information
Parameters
[in] node Node to create the backend function for
[in] ctx Graph context
Returns
Backend generate proposals layer function
Definition at line 969 of file FunctionHelpers.h.
 {
     validate_node<TargetInfo>(node, 3 /* expected inputs */, 3 /* expected outputs */);
     // Extract IO and info
     typename TargetInfo::TensorType *scores              = get_backing_tensor<TargetInfo>(node.input(0));
     typename TargetInfo::TensorType *deltas              = get_backing_tensor<TargetInfo>(node.input(1));
     typename TargetInfo::TensorType *anchors             = get_backing_tensor<TargetInfo>(node.input(2));
     typename TargetInfo::TensorType *proposals           = get_backing_tensor<TargetInfo>(node.output(0));
     typename TargetInfo::TensorType *scores_out          = get_backing_tensor<TargetInfo>(node.output(1));
     typename TargetInfo::TensorType *num_valid_proposals = get_backing_tensor<TargetInfo>(node.output(2));
     const GenerateProposalsInfo      info                = node.info();
     ARM_COMPUTE_ERROR_ON(scores == nullptr);
     ARM_COMPUTE_ERROR_ON(deltas == nullptr);
     ARM_COMPUTE_ERROR_ON(anchors == nullptr);
     ARM_COMPUTE_ERROR_ON(proposals == nullptr);
     ARM_COMPUTE_ERROR_ON(scores_out == nullptr);
     // Create and configure function
     auto func = std::make_unique<GenerateProposalsLayerFunction>(get_memory_manager(ctx, TargetInfo::TargetType));
     func->configure(scores, deltas, anchors, proposals, scores_out, num_valid_proposals, info);
     // Log info
     ARM_COMPUTE_LOG_GRAPH_INFO("Instantiated "
                                << node.type() << " Target " << TargetInfo::TargetType << " Data Type: "
                                << scores->info()->data_type() << " Scores shape: " << scores->info()->tensor_shape()
                                << " Deltas shape: " << deltas->info()->tensor_shape()
                                << " Anchors shape: " << anchors->info()->tensor_shape()
                                << " Proposals shape: " << proposals->info()->tensor_shape()
                                << " Num valid proposals shape: " << num_valid_proposals->info()->tensor_shape()
                                << " Scores Out shape: " << scores_out->info()->tensor_shape() << std::endl);
     return std::move(func);
 }
References ARM_COMPUTE_ERROR_ON, ARM_COMPUTE_LOG_GRAPH_INFO, arm_compute::graph::backends::get_memory_manager(), GenerateProposalsLayerNode::info(), arm_compute::test::validation::info, INode::input(), INode::output(), and GenerateProposalsLayerNode::type().
create_l2_normalize_layer()
std::unique_ptr<IFunction> arm_compute::graph::backends::detail::create_l2_normalize_layer (L2NormalizeLayerNode & node, GraphContext & ctx)
Create a backend l2 normalization layer function.
Template Parameters
NormalizationLayerFunction Backend normalization function
TargetInfo Target-specific information
Parameters
[in] node Node to create the backend function for
[in] ctx Graph context
Returns
Backend normalization layer function
Definition at line 1016 of file FunctionHelpers.h.
 {
     validate_node<TargetInfo>(node, 1 /* expected inputs */, 1 /* expected outputs */);
     // Extract IO and info
     typename TargetInfo::TensorType *input   = get_backing_tensor<TargetInfo>(node.input(0));
     typename TargetInfo::TensorType *output  = get_backing_tensor<TargetInfo>(node.output(0));
     int                              axis    = node.axis();
     float                            epsilon = node.epsilon();
     ARM_COMPUTE_ERROR_ON(input == nullptr);
     ARM_COMPUTE_ERROR_ON(output == nullptr);
     // Create and configure function
     auto mm   = get_memory_manager(ctx, TargetInfo::TargetType);
     auto func = std::make_unique<L2NormalizeLayerFunction>(mm);
     func->configure(input, output, axis, epsilon);
     // Log info
     ARM_COMPUTE_LOG_GRAPH_INFO("Instantiated " << node.name() << " Type: " << node.type() << " Target: "
                                                << TargetInfo::TargetType << " Data Type: " << input->info()->data_type()
                                                << " Input shape: " << input->info()->tensor_shape()
                                                << " Output shape: " << output->info()->tensor_shape()
                                                << " Axis: " << axis << " Epsilon: " << epsilon << std::endl);
     return func;
 }
References ARM_COMPUTE_ERROR_ON, ARM_COMPUTE_LOG_GRAPH_INFO, L2NormalizeLayerNode::axis(), arm_compute::quantization::epsilon, L2NormalizeLayerNode::epsilon(), arm_compute::graph::backends::get_memory_manager(), INode::input(), arm_compute::test::validation::input, INode::name(), INode::output(), and L2NormalizeLayerNode::type().
create_normalization_layer()
std::unique_ptr<IFunction> arm_compute::graph::backends::detail::create_normalization_layer (NormalizationLayerNode & node, GraphContext & ctx)
Create a backend normalization layer function.
Template Parameters
NormalizationLayerFunction Backend normalization function
TargetInfo Target-specific information
Parameters
[in] node Node to create the backend function for
[in] ctx Graph context
Returns
Backend normalization layer function
Definition at line 1055 of file FunctionHelpers.h.
 {
     ARM_COMPUTE_UNUSED(ctx);
     validate_node<TargetInfo>(node, 1 /* expected inputs */, 1 /* expected outputs */);
     // Extract IO and info
     typename TargetInfo::TensorType *input     = get_backing_tensor<TargetInfo>(node.input(0));
     typename TargetInfo::TensorType *output    = get_backing_tensor<TargetInfo>(node.output(0));
     const NormalizationLayerInfo     norm_info = node.normalization_info();
     ARM_COMPUTE_ERROR_ON(input == nullptr);
     ARM_COMPUTE_ERROR_ON(output == nullptr);
     // Create and configure function
     auto func = std::make_unique<NormalizationLayerFunction>();
     func->configure(input, output, norm_info);
     // Log info
     ARM_COMPUTE_LOG_GRAPH_INFO("Instantiated " << node.name() << " Type: " << node.type() << " Target: "
                                                << TargetInfo::TargetType << " Data Type: " << input->info()->data_type()
                                                << " Input shape: " << input->info()->tensor_shape()
                                                << " Output shape: " << output->info()->tensor_shape()
                                                << " Normalization info: " << norm_info.type() << std::endl);
     return std::move(func);
 }
References ARM_COMPUTE_ERROR_ON, ARM_COMPUTE_LOG_GRAPH_INFO, ARM_COMPUTE_UNUSED, INode::input(), arm_compute::test::validation::input, INode::name(), NormalizationLayerNode::normalization_info(), INode::output(), NormalizationLayerNode::type(), and NormalizationLayerInfo::type().
create_normalization_layer< NENormalizationLayer, NETargetInfo >()
std::unique_ptr<IFunction> arm_compute::graph::backends::detail::create_normalization_layer< NENormalizationLayer, NETargetInfo > (NormalizationLayerNode & node, GraphContext & ctx)
Definition at line 91 of file NEFunctionFactory.cpp.
 {
     validate_node<NETargetInfo>(node, 1 /* expected inputs */, 1 /* expected outputs */);
     // Extract IO and info
     NETargetInfo::TensorType    *input     = get_backing_tensor<NETargetInfo>(node.input(0));
     NETargetInfo::TensorType    *output    = get_backing_tensor<NETargetInfo>(node.output(0));
     const NormalizationLayerInfo norm_info = node.normalization_info();
     ARM_COMPUTE_ERROR_ON(input == nullptr);
     ARM_COMPUTE_ERROR_ON(output == nullptr);
     // Create and configure function
     auto func = std::make_unique<NENormalizationLayer>(get_memory_manager(ctx, NETargetInfo::TargetType));
     func->configure(input, output, norm_info);
     // Log info
     ARM_COMPUTE_LOG_GRAPH_INFO("Instantiated "
                                << node.name() << " Type: " << node.type() << " Target: " << NETargetInfo::TargetType
                                << " Data Type: " << input->info()->data_type() << " Input shape: "
                                << input->info()->tensor_shape() << " Output shape: " << output->info()->tensor_shape()
                                << " Normalization info: " << norm_info.type() << std::endl);
     return func;
 }
References ARM_COMPUTE_ERROR_ON, ARM_COMPUTE_LOG_GRAPH_INFO, arm_compute::graph::backends::get_memory_manager(), ITensor::info(), INode::input(), arm_compute::test::validation::input, INode::name(), NormalizationLayerNode::normalization_info(), INode::output(), ITensorInfo::tensor_shape(), NormalizationLayerNode::type(), and NormalizationLayerInfo::type().
Referenced by NEFunctionFactory::create().
create_normalize_planar_yuv_layer()
std::unique_ptr<IFunction> arm_compute::graph::backends::detail::create_normalize_planar_yuv_layer (NormalizePlanarYUVLayerNode & node)
Create a backend normalize planar YUV layer function.
Template Parameters
NormalizePlanarYUVLayerFunction Backend normalize planar YUV function
TargetInfo Target-specific information
Parameters
[in] node Node to create the backend function for
Returns
Backend normalize plnar YUV layer function
Definition at line 1092 of file FunctionHelpers.h.
 {
     validate_node<TargetInfo>(node, 3 /* expected inputs */, 1 /* expected outputs */);
     // Extract IO and info
     typename TargetInfo::TensorType *input  = get_backing_tensor<TargetInfo>(node.input(0));
     typename TargetInfo::TensorType *mean   = get_backing_tensor<TargetInfo>(node.input(1));
     typename TargetInfo::TensorType *std    = get_backing_tensor<TargetInfo>(node.input(2));
     typename TargetInfo::TensorType *output = get_backing_tensor<TargetInfo>(node.output(0));
     ARM_COMPUTE_ERROR_ON(input == nullptr);
     ARM_COMPUTE_ERROR_ON(mean == nullptr);
     ARM_COMPUTE_ERROR_ON(std == nullptr);
     ARM_COMPUTE_ERROR_ON(output == nullptr);
     // Create and configure function
     auto func = std::make_unique<NormalizePlanarYUVLayerFunction>();
     func->configure(input, output, mean, std);
     // Log info
     ARM_COMPUTE_LOG_GRAPH_INFO("Instantiated " << node.name() << " Type: " << node.type() << " Target: "
                                                << TargetInfo::TargetType << " Data Type: " << input->info()->data_type()
                                                << " Shape: " << input->info()->tensor_shape() << std::endl);
     return std::move(func);
 }
References ARM_COMPUTE_ERROR_ON, ARM_COMPUTE_LOG_GRAPH_INFO, INode::input(), arm_compute::test::validation::input, INode::name(), INode::output(), and NormalizePlanarYUVLayerNode::type().
create_pad_layer()
std::unique_ptr<IFunction> arm_compute::graph::backends::detail::create_pad_layer (PadLayerNode & node)
Create a backend pad layer function.
Template Parameters
PadLayerFunction Backend pad function
TargetInfo Target-specific information
Parameters
[in] node Node to create the backend function for
Returns
Backend pad layer function
Definition at line 1128 of file FunctionHelpers.h.
 {
     validate_node<TargetInfo>(node, 1 /* expected inputs */, 1 /* expected outputs */);
     // Extract IO and info
     typename TargetInfo::TensorType *input     = get_backing_tensor<TargetInfo>(node.input(0));
     typename TargetInfo::TensorType *output    = get_backing_tensor<TargetInfo>(node.output(0));
     const PaddingList               &padding   = node.padding();
     const PixelValue                 pad_value = node.pad_value();
     ARM_COMPUTE_ERROR_ON(input == nullptr);
     ARM_COMPUTE_ERROR_ON(output == nullptr);
     // Create and configure function
     auto func = std::make_unique<PadLayerFunction>();
     func->configure(input, output, padding, pad_value);
     // Log info
     ARM_COMPUTE_LOG_GRAPH_INFO("Instantiated " << node.name() << " Type: " << node.type() << " Target: "
                                                << TargetInfo::TargetType << " Data Type: " << input->info()->data_type()
                                                << " Input shape: " << input->info()->tensor_shape()
                                                << " Output shape: " << output->info()->tensor_shape() << std::endl);
     return func;
 }
References ARM_COMPUTE_ERROR_ON, ARM_COMPUTE_LOG_GRAPH_INFO, INode::input(), arm_compute::test::validation::input, INode::name(), INode::output(), PadLayerNode::pad_value(), PadLayerNode::padding(), and PadLayerNode::type().
create_permute_layer()
std::unique_ptr<IFunction> arm_compute::graph::backends::detail::create_permute_layer (PermuteLayerNode & node)
Create a backend permute layer function.
Template Parameters
PermuteLayerFunction Backend permute function
TargetInfo Target-specific information
Parameters
[in] node Node to create the backend function for
Returns
Backend permute layer function
Definition at line 1163 of file FunctionHelpers.h.
 {
     validate_node<TargetInfo>(node, 1 /* expected inputs */, 1 /* expected outputs */);
     // Extract IO and info
     typename TargetInfo::TensorType *input  = get_backing_tensor<TargetInfo>(node.input(0));
     typename TargetInfo::TensorType *output = get_backing_tensor<TargetInfo>(node.output(0));
     const PermutationVector         &perm   = node.permutation_vector();
     ARM_COMPUTE_ERROR_ON(input == nullptr);
     ARM_COMPUTE_ERROR_ON(output == nullptr);
     // Create and configure function
     auto func = std::make_unique<PermuteLayerFunction>();
     func->configure(input, output, perm);
     // Log info
     ARM_COMPUTE_LOG_GRAPH_INFO("Instantiated " << node.name() << " Type: " << node.type() << " Target: "
                                                << TargetInfo::TargetType << " Data Type: " << input->info()->data_type()
                                                << " Input shape: " << input->info()->tensor_shape()
                                                << " Output shape: " << output->info()->tensor_shape()
                                                << " Permutation vector: " << perm << std::endl);
     return func;
 }
References ARM_COMPUTE_ERROR_ON, ARM_COMPUTE_LOG_GRAPH_INFO, INode::input(), arm_compute::test::validation::input, INode::name(), INode::output(), PermuteLayerNode::permutation_vector(), and PermuteLayerNode::type().
create_pooling_layer()
std::unique_ptr<IFunction> arm_compute::graph::backends::detail::create_pooling_layer (PoolingLayerNode & node)
Create a backend pooling layer function.
Template Parameters
PoolingLayerFunction Backend pooling function
TargetInfo Target-specific information
Parameters
[in] node Node to create the backend function for
Returns
Backend pooling layer function
Definition at line 1198 of file FunctionHelpers.h.
 {
     validate_node<TargetInfo>(node, 1 /* expected inputs */, 1 /* expected outputs */);
     // Extract IO and info
     typename TargetInfo::TensorType *input     = get_backing_tensor<TargetInfo>(node.input(0));
     typename TargetInfo::TensorType *output    = get_backing_tensor<TargetInfo>(node.output(0));
     const PoolingLayerInfo           pool_info = node.pooling_info();
     ARM_COMPUTE_ERROR_ON(input == nullptr);
     ARM_COMPUTE_ERROR_ON(output == nullptr);
     // Create and configure function
     auto func = std::make_unique<PoolingLayerFunction>();
     func->configure(input, output, pool_info);
     // Log info
     ARM_COMPUTE_LOG_GRAPH_INFO("Instantiated " << node.name() << " Type: " << node.type() << " Target: "
                                                << TargetInfo::TargetType << " Data Type: " << input->info()->data_type()
                                                << " Input shape: " << input->info()->tensor_shape()
                                                << " Output shape: " << output->info()->tensor_shape()
                                                << " Pooling info: " << pool_info.pool_type << std::endl);
     return func;
 }
References ARM_COMPUTE_ERROR_ON, ARM_COMPUTE_LOG_GRAPH_INFO, INode::input(), arm_compute::test::validation::input, INode::name(), INode::output(), PoolingLayerInfo::pool_type, PoolingLayerNode::pooling_info(), and PoolingLayerNode::type().
create_prelu_layer()
std::unique_ptr<IFunction> arm_compute::graph::backends::detail::create_prelu_layer (PReluLayerNode & node)
Create a backend PRelu layer function.
Template Parameters
PReluFunction Backend PRelu function
TargetInfo Target-specific information
Parameters
[in] node Node to create the backend function for
Returns
Backend PRelu layer function
Definition at line 1233 of file FunctionHelpers.h.
 {
     validate_node<TargetInfo>(node, 2 /* expected inputs */, 1 /* expected outputs */);
     // Extract IO and info
     typename TargetInfo::TensorType *input  = get_backing_tensor<TargetInfo>(node.input(0));
     typename TargetInfo::TensorType *alpha  = get_backing_tensor<TargetInfo>(node.input(1));
     typename TargetInfo::TensorType *output = get_backing_tensor<TargetInfo>(node.output(0));
     ARM_COMPUTE_ERROR_ON(input == nullptr || alpha == nullptr);
     ARM_COMPUTE_ERROR_ON(output == nullptr);
     // Create and configure function
     auto func = std::make_unique<PReluFunction>();
     func->configure(input, alpha, output);
     // Log info
     ARM_COMPUTE_LOG_GRAPH_INFO("Instantiated " << node.name() << " Type: " << node.type() << " Target: "
                                                << TargetInfo::TargetType << " Data Type: " << input->info()->data_type()
                                                << " Input shape: " << input->info()->tensor_shape()
                                                << " Output shape: " << output->info()->tensor_shape() << std::endl);
     return func;
 }
References ARM_COMPUTE_ERROR_ON, ARM_COMPUTE_LOG_GRAPH_INFO, INode::input(), arm_compute::test::validation::input, INode::name(), INode::output(), and PReluLayerNode::type().
create_print_layer()
std::unique_ptr<IFunction> arm_compute::graph::backends::detail::create_print_layer (PrintLayerNode & node)
Create a backend print layer function.
Template Parameters
TargetInfo Target-specific information
Parameters
[in] node Node to create the backend function for
Returns
Backend print layer function
Definition at line 1266 of file FunctionHelpers.h.
 {
     validate_node<TargetInfo>(node, 1 /* expected inputs */, 1 /* expected outputs */);
     typename TargetInfo::TensorType *input = get_backing_tensor<TargetInfo>(node.input(0));
     ARM_COMPUTE_ERROR_ON(input == nullptr);
     ARM_COMPUTE_UNUSED(input);
     // Log info
     ARM_COMPUTE_LOG_GRAPH_INFO("Instantiated " << node.name() << " Type: " << node.type() << " Target: "
                                                << TargetInfo::TargetType << " Data Type: " << input->info()->data_type()
                                                << " Input shape: " << input->info()->tensor_shape() << std::endl);
     return nullptr;
 }
References ARM_COMPUTE_ERROR_ON, ARM_COMPUTE_LOG_GRAPH_INFO, ARM_COMPUTE_UNUSED, INode::input(), arm_compute::test::validation::input, INode::name(), and PrintLayerNode::type().
create_priorbox_layer()
std::unique_ptr<IFunction> arm_compute::graph::backends::detail::create_priorbox_layer (PriorBoxLayerNode & node)
Create a backend priorbox layer function.
Template Parameters
PriorBoxLayerFunction Backend priorbox function
TargetInfo Target-specific information
Parameters
[in] node Node to create the backend function for
Returns
Backend priorbox layer function
Definition at line 1292 of file FunctionHelpers.h.
 {
     validate_node<TargetInfo>(node, 2 /* expected inputs */, 1 /* expected outputs */);
     // Extract IO and info
     typename TargetInfo::TensorType *input0     = get_backing_tensor<TargetInfo>(node.input(0));
     typename TargetInfo::TensorType *input1     = get_backing_tensor<TargetInfo>(node.input(1));
     typename TargetInfo::TensorType *output     = get_backing_tensor<TargetInfo>(node.output(0));
     const PriorBoxLayerInfo          prior_info = node.priorbox_info();
     ARM_COMPUTE_ERROR_ON(input0 == nullptr);
     ARM_COMPUTE_ERROR_ON(input1 == nullptr);
     ARM_COMPUTE_ERROR_ON(output == nullptr);
     // Create and configure function
     auto func = std::make_unique<PriorBoxLayerFunction>();
     func->configure(input0, input1, output, prior_info);
     // Log info
     ARM_COMPUTE_LOG_GRAPH_INFO("Instantiated "
                                << node.name() << " Type: " << node.type() << " Target: " << TargetInfo::TargetType
                                << " Data Type: " << input0->info()->data_type() << " Input0 shape: "
                                << input0->info()->tensor_shape() << " Input1 shape: " << input1->info()->tensor_shape()
                                << " Output shape: " << output->info()->tensor_shape()
                                << " PriorBoxLayer info: " << prior_info << std::endl);
     return func;
 }
References ARM_COMPUTE_ERROR_ON, ARM_COMPUTE_LOG_GRAPH_INFO, INode::input(), INode::name(), INode::output(), PriorBoxLayerNode::priorbox_info(), and PriorBoxLayerNode::type().
create_quantization_layer()
std::unique_ptr<IFunction> arm_compute::graph::backends::detail::create_quantization_layer (QuantizationLayerNode & node)
Create a backend quantization layer function.
Template Parameters
QuantizationLayerFunction Backend quantization function
TargetInfo Target-specific information
Parameters
[in] node Node to create the backend function for
Returns
Backend quantization layer function
Definition at line 1330 of file FunctionHelpers.h.
 {
     validate_node<TargetInfo>(node, 1 /* expected inputs */, 1 /* expected outputs */);
     // Extract IO and info
     typename TargetInfo::TensorType *input  = get_backing_tensor<TargetInfo>(node.input(0));
     typename TargetInfo::TensorType *output = get_backing_tensor<TargetInfo>(node.output(0));
     ARM_COMPUTE_ERROR_ON(input == nullptr);
     ARM_COMPUTE_ERROR_ON(output == nullptr);
     // Create and configure function
     auto func = std::make_unique<QuantizationLayerFunction>();
     func->configure(input, output);
     // Log info
     ARM_COMPUTE_LOG_GRAPH_INFO("Instantiated " << node.name() << " Type: " << node.type() << " Target: "
                                                << TargetInfo::TargetType << " Data Type: " << input->info()->data_type()
                                                << " Input shape: " << input->info()->tensor_shape()
                                                << " Output shape: " << output->info()->tensor_shape() << std::endl);
     return func;
 }
References ARM_COMPUTE_ERROR_ON, ARM_COMPUTE_LOG_GRAPH_INFO, INode::input(), arm_compute::test::validation::input, INode::name(), INode::output(), and QuantizationLayerNode::type().
create_reduction_operation_layer()
std::unique_ptr<IFunction> arm_compute::graph::backends::detail::create_reduction_operation_layer (ReductionLayerNode & node, GraphContext & ctx)
Create a backend reduction operation layer function.
Template Parameters
ReductionOperationFunction Backend reduction operation function
TargetInfo Target-specific information
Parameters
[in] node Node to create the backend function for
[in] ctx Graph context
Returns
Backend reduction sum layer function
Definition at line 1364 of file FunctionHelpers.h.
 {
     validate_node<TargetInfo>(node, 1 /* expected inputs */, 1 /* expected outputs */);
     // Extract IO and info
     typename TargetInfo::TensorType *input     = get_backing_tensor<TargetInfo>(node.input(0));
     typename TargetInfo::TensorType *output    = get_backing_tensor<TargetInfo>(node.output(0));
     ReductionOperation               op        = node.op();
     int                              axis      = node.axis();
     bool                             keep_dims = node.keep_dims();
     ARM_COMPUTE_ERROR_ON(input == nullptr);
     ARM_COMPUTE_ERROR_ON(output == nullptr);
     // Create and configure function
     auto func = std::make_unique<ReductionOperationFunction>(get_memory_manager(ctx, TargetInfo::TargetType));
     func->configure(input, output, axis, op, keep_dims);
     // Log info
     ARM_COMPUTE_LOG_GRAPH_INFO("Instantiated "
                                << node.name() << " Type: " << node.type() << " Target: " << TargetInfo::TargetType
                                << " Data Type: " << input->info()->data_type()
                                << " Input shape: " << input->info()->tensor_shape()
                                << " Output shape: " << output->info()->tensor_shape() << " Operation: " << op
                                << " Axis: " << axis << " Keep dimensions:" << keep_dims << std::endl);
     return func;
 }
References ARM_COMPUTE_ERROR_ON, ARM_COMPUTE_LOG_GRAPH_INFO, ReductionLayerNode::axis(), arm_compute::graph::backends::get_memory_manager(), INode::input(), arm_compute::test::validation::input, ReductionLayerNode::keep_dims(), INode::name(), ReductionLayerNode::op(), INode::output(), and ReductionLayerNode::type().
create_reorg_layer()
std::unique_ptr<IFunction> arm_compute::graph::backends::detail::create_reorg_layer (ReorgLayerNode & node)
Create a backend reorg layer function.
Template Parameters
ReorgLayerFunction Backend reorg function
TargetInfo Target-specific information
Parameters
[in] node Node to create the backend function for
Returns
Backend reshape layer function
Definition at line 1402 of file FunctionHelpers.h.
 {
     validate_node<TargetInfo>(node, 1 /* expected inputs */, 1 /* expected outputs */);
     // Extract IO and info
     typename TargetInfo::TensorType *input  = get_backing_tensor<TargetInfo>(node.input(0));
     typename TargetInfo::TensorType *output = get_backing_tensor<TargetInfo>(node.output(0));
     ARM_COMPUTE_ERROR_ON(input == nullptr);
     ARM_COMPUTE_ERROR_ON(output == nullptr);
     // Create and configure function
     auto func = std::make_unique<ReorgLayerFunction>();
     func->configure(input, output, node.stride());
     // Log info
     ARM_COMPUTE_LOG_GRAPH_INFO("Instantiated " << node.name() << " Type: " << node.type() << " Target: "
                                                << TargetInfo::TargetType << " Data Type: " << input->info()->data_type()
                                                << " Input shape: " << input->info()->tensor_shape()
                                                << " Output shape: " << output->info()->tensor_shape() << std::endl);
     return func;
 }
References ARM_COMPUTE_ERROR_ON, ARM_COMPUTE_LOG_GRAPH_INFO, INode::input(), arm_compute::test::validation::input, INode::name(), INode::output(), ReorgLayerNode::stride(), and ReorgLayerNode::type().
create_reshape_layer()
std::unique_ptr<IFunction> arm_compute::graph::backends::detail::create_reshape_layer (ReshapeLayerNode & node)
Create a backend reshape layer function.
Template Parameters
ReshapeLayerFunction Backend reshape function
TargetInfo Target-specific information
Parameters
[in] node Node to create the backend function for
Returns
Backend reshape layer function
Definition at line 1435 of file FunctionHelpers.h.
 {
     validate_node<TargetInfo>(node, 1 /* expected inputs */, 1 /* expected outputs */);
     // Extract IO and info
     typename TargetInfo::TensorType *input  = get_backing_tensor<TargetInfo>(node.input(0));
     typename TargetInfo::TensorType *output = get_backing_tensor<TargetInfo>(node.output(0));
     ARM_COMPUTE_ERROR_ON(input == nullptr);
     ARM_COMPUTE_ERROR_ON(output == nullptr);
     // Create and configure function
     auto func = std::make_unique<ReshapeLayerFunction>();
     func->configure(input, output);
     // Log info
     ARM_COMPUTE_LOG_GRAPH_INFO("Instantiated " << node.name() << " Type: " << node.type() << " Target: "
                                                << TargetInfo::TargetType << " Data Type: " << input->info()->data_type()
                                                << " Input shape: " << input->info()->tensor_shape()
                                                << " Output shape: " << output->info()->tensor_shape() << std::endl);
     return func;
 }
References ARM_COMPUTE_ERROR_ON, ARM_COMPUTE_LOG_GRAPH_INFO, INode::input(), arm_compute::test::validation::input, INode::name(), INode::output(), and ReshapeLayerNode::type().
create_resize_layer()
std::unique_ptr<IFunction> arm_compute::graph::backends::detail::create_resize_layer (ResizeLayerNode & node)
Create a backend resize layer function.
Template Parameters
ResizeLayerFunction Backend resize function
TargetInfo Target-specific information
Parameters
[in] node Node to create the backend function for
Returns
Backend resize layer function
Definition at line 1468 of file FunctionHelpers.h.
 {
     validate_node<TargetInfo>(node, 1 /* expected inputs */, 1 /* expected outputs */);
     // Extract IO and info
     typename TargetInfo::TensorType *input  = get_backing_tensor<TargetInfo>(node.input(0));
     typename TargetInfo::TensorType *output = get_backing_tensor<TargetInfo>(node.output(0));
     ARM_COMPUTE_ERROR_ON(input == nullptr);
     ARM_COMPUTE_ERROR_ON(output == nullptr);
     const InterpolationPolicy policy = node.policy();
     // Create and configure function
     auto func = std::make_unique<ResizeLayerFunction>();
     func->configure(input, output,
                     ScaleKernelInfo{policy, BorderMode::CONSTANT, PixelValue(), SamplingPolicy::CENTER, false, false});
     // Log info
     ARM_COMPUTE_LOG_GRAPH_INFO("Instantiated " << node.name() << " Type: " << node.type() << " Target: "
                                                << TargetInfo::TargetType << " Data Type: " << input->info()->data_type()
                                                << " Input shape: " << input->info()->tensor_shape()
                                                << " Output shape: " << output->info()->tensor_shape()
                                                << " Interpolation: " << policy << std::endl);
     return func;
 }
References ARM_COMPUTE_ERROR_ON, ARM_COMPUTE_LOG_GRAPH_INFO, arm_compute::CENTER, arm_compute::CONSTANT, INode::input(), arm_compute::test::validation::input, INode::name(), INode::output(), ResizeLayerNode::policy(), and ResizeLayerNode::type().
create_roi_align_layer()
std::unique_ptr<IFunction> arm_compute::graph::backends::detail::create_roi_align_layer (ROIAlignLayerNode & node)
Create a backend ROI align layer function.
Template Parameters
ROIAlignLayerFunction ROI Align function
TargetInfo Target-specific information
Parameters
[in] node Node to create the backend function for
Returns
ROI Align layer function
Definition at line 1504 of file FunctionHelpers.h.
 {
     validate_node<TargetInfo>(node, 2 /* expected inputs */, 1 /* expected outputs */);
     // Extract IO and info
     typename TargetInfo::TensorType *input  = get_backing_tensor<TargetInfo>(node.input(0));
     typename TargetInfo::TensorType *rois   = get_backing_tensor<TargetInfo>(node.input(1));
     typename TargetInfo::TensorType *output = get_backing_tensor<TargetInfo>(node.output(0));
     ARM_COMPUTE_ERROR_ON(input == nullptr);
     ARM_COMPUTE_ERROR_ON(output == nullptr);
     ARM_COMPUTE_ERROR_ON(rois == nullptr);
     const ROIPoolingLayerInfo pool_info = node.pooling_info();
     // Create and configure function
     auto func = std::make_unique<ROIAlignLayerFunction>();
     func->configure(input, rois, output, pool_info);
     // Log info
     ARM_COMPUTE_LOG_GRAPH_INFO("Instantiated " << node.name() << " Type: " << node.type() << " Target: "
                                                << TargetInfo::TargetType << " Data Type: " << input->info()->data_type()
                                                << " Input shape: " << input->info()->tensor_shape()
                                                << " Output shape: " << output->info()->tensor_shape()
                                                << " ROIs shape: " << rois->info()->tensor_shape()
                                                << " ROIPooling width: " << pool_info.pooled_width()
                                                << " ROIPooling height: " << pool_info.pooled_height() << std::endl);
     return std::move(func);
 }
References ARM_COMPUTE_ERROR_ON, ARM_COMPUTE_LOG_GRAPH_INFO, INode::input(), arm_compute::test::validation::input, INode::name(), INode::output(), ROIPoolingLayerInfo::pooled_height(), ROIPoolingLayerInfo::pooled_width(), ROIAlignLayerNode::pooling_info(), and ROIAlignLayerNode::type().
create_slice_layer()
std::unique_ptr<IFunction> arm_compute::graph::backends::detail::create_slice_layer (SliceLayerNode & node)
Create a backend slice layer function.
Template Parameters
SliceLayerFunction Backend slice function
TargetInfo Target-specific information
Parameters
[in] node Node to create the backend function for
Returns
Backend slice layer function
Definition at line 1545 of file FunctionHelpers.h.
 {
     validate_node<TargetInfo>(node, 1 /* expected inputs */, 1 /* expected outputs */);
     // Extract IO and info
     typename TargetInfo::TensorType *input  = get_backing_tensor<TargetInfo>(node.input(0));
     typename TargetInfo::TensorType *output = get_backing_tensor<TargetInfo>(node.output(0));
     ARM_COMPUTE_ERROR_ON(input == nullptr);
     ARM_COMPUTE_ERROR_ON(output == nullptr);
     // Create and configure function
     auto func = std::make_unique<SliceLayerFunction>();
     func->configure(input, output, node.starts(), node.ends());
     // Log info
     ARM_COMPUTE_LOG_GRAPH_INFO("Instantiated " << node.name() << " Type: " << node.type() << " Target: "
                                                << TargetInfo::TargetType << " Data Type: " << input->info()->data_type()
                                                << " Input shape: " << input->info()->tensor_shape()
                                                << " Output shape: " << output->info()->tensor_shape() << std::endl);
     return func;
 }
References ARM_COMPUTE_ERROR_ON, ARM_COMPUTE_LOG_GRAPH_INFO, SliceLayerNode::ends(), INode::input(), arm_compute::test::validation::input, INode::name(), INode::output(), SliceLayerNode::starts(), and SliceLayerNode::type().
create_softmax_layer()
std::unique_ptr<IFunction> arm_compute::graph::backends::detail::create_softmax_layer (SoftmaxLayerNode & node, GraphContext & ctx)
Create a backend softmax layer function.
Template Parameters
SoftmaxLayerFunction Backend softmax function
TargetInfo Target-specific information
Parameters
[in] node Node to create the backend function for
[in] ctx Graph context
Returns
Backend softmax layer function
Definition at line 1579 of file FunctionHelpers.h.
 {
     validate_node<TargetInfo>(node, 1 /* expected inputs */, 1 /* expected outputs */);
     // Extract IO and info
     typename TargetInfo::TensorType *input  = get_backing_tensor<TargetInfo>(node.input(0));
     typename TargetInfo::TensorType *output = get_backing_tensor<TargetInfo>(node.output(0));
     const float                      beta   = node.beta();
     ARM_COMPUTE_ERROR_ON(input == nullptr);
     ARM_COMPUTE_ERROR_ON(output == nullptr);
     // Create and configure function
     auto func = std::make_unique<SoftmaxLayerFunction>(get_memory_manager(ctx, TargetInfo::TargetType));
     func->configure(input, output, beta);
     // Log info
     ARM_COMPUTE_LOG_GRAPH_INFO("Instantiated " << node.name() << " Type: " << node.type() << " Target: "
                                                << TargetInfo::TargetType << " Data Type: " << input->info()->data_type()
                                                << " Input shape: " << input->info()->tensor_shape()
                                                << " Output shape: " << output->info()->tensor_shape() << std::endl);
     return func;
 }
References ARM_COMPUTE_ERROR_ON, ARM_COMPUTE_LOG_GRAPH_INFO, SoftmaxLayerNode::beta(), arm_compute::graph::backends::get_memory_manager(), INode::input(), arm_compute::test::validation::input, INode::name(), INode::output(), and SoftmaxLayerNode::type().
create_stack_layer()
std::unique_ptr<arm_compute::IFunction> arm_compute::graph::backends::detail::create_stack_layer (StackLayerNode & node)
Create a backend layer stack function.
Template Parameters
StackLayerFunction Backend stack function
TargetInfo Target-specific information
Parameters
[in] node Node to create the backend function for
Returns
Backend stack layer function
Definition at line 1613 of file FunctionHelpers.h.
 {
     ARM_COMPUTE_LOG_GRAPH_VERBOSE("Creating Stack node with ID : " << node.id() << " and Name: " << node.name()
                                                                    << std::endl);
     ARM_COMPUTE_ERROR_ON(node.num_outputs() != 1);
     // Extract IO and info
     std::vector<typename TargetInfo::TensorType *> inputs;
     for (unsigned int i = 0; i < node.num_inputs(); ++i)
     {
         inputs.push_back(get_backing_tensor<TargetInfo>(node.input(i)));
     }
     typename TargetInfo::TensorType *output = get_backing_tensor<TargetInfo>(node.output(0));
     const int                        axis   = node.axis();
     // Create and configure function
     auto func = std::make_unique<StackLayerFunction>();
     func->configure(inputs, axis, output);
     // Log info
     ARM_COMPUTE_LOG_GRAPH_INFO("Instantiated " << node.name() << " Type: " << node.type()
                                                << " Target: " << TargetInfo::TargetType
                                                << " Data Type: " << output->info()->data_type()
                                                << " Inputs shape: " << inputs[0]->info()->tensor_shape()
                                                << " Output shape: " << output->info()->tensor_shape()
                                                << " Num Inputs: " << inputs.size() << " Axis: " << axis << std::endl);
     return func;
 }
References ARM_COMPUTE_ERROR_ON, ARM_COMPUTE_LOG_GRAPH_INFO, ARM_COMPUTE_LOG_GRAPH_VERBOSE, StackLayerNode::axis(), INode::id(), INode::input(), INode::name(), INode::num_inputs(), INode::num_outputs(), INode::output(), and StackLayerNode::type().
create_strided_slice_layer()
std::unique_ptr<IFunction> arm_compute::graph::backends::detail::create_strided_slice_layer (StridedSliceLayerNode & node)
Create a backend slice layer function.
Template Parameters
StridedSliceLayerFunction Backend strided slice function
TargetInfo Target-specific information
Parameters
[in] node Node to create the backend function for
Returns
Backend strided slice layer function
Definition at line 1653 of file FunctionHelpers.h.
 {
     validate_node<TargetInfo>(node, 1 /* expected inputs */, 1 /* expected outputs */);
     // Extract IO and info
     typename TargetInfo::TensorType *input   = get_backing_tensor<TargetInfo>(node.input(0));
     typename TargetInfo::TensorType *output  = get_backing_tensor<TargetInfo>(node.output(0));
     Coordinates                      starts  = node.starts();
     Coordinates                      ends    = node.ends();
     BiStrides                        strides = node.strides();
     StridedSliceLayerInfo            info    = node.strided_slice_info();
     ARM_COMPUTE_ERROR_ON(input == nullptr);
     ARM_COMPUTE_ERROR_ON(output == nullptr);
     // Create and configure function
     auto func = std::make_unique<StridedSliceLayerFunction>();
     func->configure(input, output, starts, ends, strides, info.begin_mask(), info.end_mask(), info.shrink_axis_mask());
     // Log info
     ARM_COMPUTE_LOG_GRAPH_INFO("Instantiated " << node.name() << " Type: " << node.type() << " Target: "
                                                << TargetInfo::TargetType << " Data Type: " << input->info()->data_type()
                                                << " Input shape: " << input->info()->tensor_shape()
                                                << " Output shape: " << output->info()->tensor_shape() << std::endl);
     return func;
 }
References ARM_COMPUTE_ERROR_ON, ARM_COMPUTE_LOG_GRAPH_INFO, StridedSliceLayerNode::ends(), arm_compute::test::validation::info, INode::input(), arm_compute::test::validation::input, INode::name(), INode::output(), StridedSliceLayerNode::starts(), StridedSliceLayerNode::strided_slice_info(), StridedSliceLayerNode::strides(), and StridedSliceLayerNode::type().
create_unary_eltwise_layer()
std::unique_ptr<IFunction> arm_compute::graph::backends::detail::create_unary_eltwise_layer (UnaryEltwiseLayerNode & node)
Create a backend unary element-wise operation layer function.
Template Parameters
UnaryEltwiseFunctions Backend unary element-wise function
TargetInfo Target-specific information
Parameters
[in] node Node to create the backend function for
Returns
Backend unary element-wise operation layer function
Definition at line 839 of file FunctionHelpers.h.
 {
     validate_node<TargetInfo>(node, 1 /* expected inputs */, 1 /* expected outputs */);
     // Extract IO and info
     typename TargetInfo::TensorType *input      = get_backing_tensor<TargetInfo>(node.input(0));
     typename TargetInfo::TensorType *output     = get_backing_tensor<TargetInfo>(node.output(0));
     const UnaryEltwiseOperation      eltwise_op = node.eltwise_descriptor().op;
     ARM_COMPUTE_ERROR_ON(input == nullptr);
     ARM_COMPUTE_ERROR_ON(output == nullptr);
     std::unique_ptr<IFunction> func = nullptr;
     std::string                func_name;
     if (eltwise_op == UnaryEltwiseOperation::Exp)
     {
         std::tie(func, func_name) =
             create_named_function<typename UnaryEltwiseFunctions::Exp>(std::string("Exp"), input, output);
     }
     else
     {
         ARM_COMPUTE_ERROR("Unsupported unary element-wise operation!");
     }
     // Log info
     ARM_COMPUTE_LOG_GRAPH_INFO("Instantiated " << node.name() << " Type: " << node.type()
                                                << " Target: " << TargetInfo::TargetType << " Operation: " << func_name
                                                << " Data Type: " << input->info()->data_type()
                                                << " Shape: " << input->info()->tensor_shape() << std::endl);
     return func;
 }
References ARM_COMPUTE_ERROR, ARM_COMPUTE_ERROR_ON, ARM_COMPUTE_LOG_GRAPH_INFO, UnaryEltwiseLayerNode::eltwise_descriptor(), arm_compute::graph::Exp, INode::input(), arm_compute::test::validation::input, INode::name(), UnaryEltwiseLayerDescriptor::op, INode::output(), and UnaryEltwiseLayerNode::type().
get_backing_tensor()
TargetInfo::TensorType* arm_compute::graph::backends::detail::get_backing_tensor (arm_compute::graph::Tensor * tensor)
Returns backing tensor of a given tensor.
Template Parameters
TargetInfo Target information
Parameters
[in] tensor Tensor to extract the backing tensor from
Returns
Backing tensor if present else nullptr
Definition at line 59 of file FunctionHelpers.h.
 {
     typename TargetInfo::TensorType *backing_tensor = nullptr;
     if (tensor != nullptr)
     {
         ARM_COMPUTE_ERROR_ON(tensor->desc().target != TargetInfo::TargetType);
         // Get backing tensor handle
         ITensorHandle *tensor_handle = tensor->handle();
         // Get backing tensor
         backing_tensor = (tensor_handle != nullptr)
                              ? arm_compute::utils::cast::polymorphic_cast<typename TargetInfo::TensorType *>(
                                    &tensor_handle->tensor())
                              : nullptr;
     }
     return backing_tensor;
 }
References ARM_COMPUTE_ERROR_ON, tensor, and ITensorHandle::tensor().
get_backing_tensor_info()
arm_compute::ITensorInfo* arm_compute::graph::backends::detail::get_backing_tensor_info (arm_compute::graph::Tensor * tensor) inline
Returns backing tensor info of a given tensor.
Parameters
[in] tensor Tensor to extract the backing tensor from
Returns
Backing tensor tensor info if present else nullptr
Definition at line 49 of file ValidateHelpers.h.
 {
     return ((tensor == nullptr) || (tensor->handle() == nullptr)) ? nullptr : tensor->handle()->tensor().info();
 }
References tensor.
Referenced by validate_arg_min_max_layer(), validate_bounding_box_transform_layer(), validate_channel_shuffle_layer(), validate_convolution_layer(), validate_depth_to_space_layer(), validate_depthwise_convolution_layer(), validate_dequantization_layer(), validate_detection_output_layer(), validate_detection_post_process_layer(), validate_eltwise_Layer(), validate_generate_proposals_layer(), validate_l2_normalize_layer(), validate_normalize_planar_yuv_layer(), validate_pad_layer(), validate_permute_layer(), validate_prelu_layer(), validate_priorbox_layer(), validate_quantization_layer(), validate_reduction_operation_layer(), validate_reorg_layer(), validate_reshape_layer(), validate_roi_align_layer(), validate_slice_layer(), validate_strided_slice_layer(), and validate_unary_eltwise_layer().
validate_arg_min_max_layer()
Status arm_compute::graph::backends::detail::validate_arg_min_max_layer (ArgMinMaxLayerNode & node)
Validates a ArgMinMax layer node.
Template Parameters
ArgMinMax layer function type
Parameters
[in] node Node to validate
Returns
Status
Definition at line 63 of file ValidateHelpers.h.
 {
     ARM_COMPUTE_LOG_GRAPH_VERBOSE(
         "Validating ArgMinMaxLayer node with ID : " << node.id() << " and Name: " << node.name() << std::endl);
     ARM_COMPUTE_RETURN_ERROR_ON(node.num_inputs() != 1);
     ARM_COMPUTE_RETURN_ERROR_ON(node.num_outputs() != 1);
     // Extract IO and info
     arm_compute::ITensorInfo *input  = detail::get_backing_tensor_info(node.input(0));
     arm_compute::ITensorInfo *output = get_backing_tensor_info(node.output(0));
     // Validate function
     return ArgMinMaxLayer::validate(input, node.axis(), output, node.reduction_operation());
 }
References ARM_COMPUTE_LOG_GRAPH_VERBOSE, ARM_COMPUTE_RETURN_ERROR_ON, ArgMinMaxLayerNode::axis(), get_backing_tensor_info(), INode::id(), INode::input(), arm_compute::test::validation::input, INode::name(), INode::num_inputs(), INode::num_outputs(), INode::output(), ArgMinMaxLayerNode::reduction_operation(), and arm_compute::validate().
validate_bounding_box_transform_layer()
Status arm_compute::graph::backends::detail::validate_bounding_box_transform_layer (BoundingBoxTransformLayerNode & node)
Validates a Bounding Box Transform layer node.
Template Parameters
BoundingBoxTransformLayer Bounding Box Transform layer function type
Parameters
[in] node Node to validate
Returns
Status
Definition at line 87 of file ValidateHelpers.h.
 {
     ARM_COMPUTE_LOG_GRAPH_VERBOSE("Validating BoundingBoxTransformLayer node with ID : " << node.id() << " and Name: "
                                                                                          << node.name() << std::endl);
     ARM_COMPUTE_RETURN_ERROR_ON(node.num_inputs() != 2);
     ARM_COMPUTE_RETURN_ERROR_ON(node.num_outputs() != 1);
     // Extract IO and info
     arm_compute::ITensorInfo      *input     = get_backing_tensor_info(node.input(0));
     arm_compute::ITensorInfo      *deltas    = get_backing_tensor_info(node.input(1));
     arm_compute::ITensorInfo      *output    = get_backing_tensor_info(node.output(0));
     const BoundingBoxTransformInfo bbox_info = node.info();
     return BoundingBoxTransformLayer::validate(input, output, deltas, bbox_info);
 }
References ARM_COMPUTE_LOG_GRAPH_VERBOSE, ARM_COMPUTE_RETURN_ERROR_ON, get_backing_tensor_info(), INode::id(), BoundingBoxTransformLayerNode::info(), INode::input(), arm_compute::test::validation::input, INode::name(), INode::num_inputs(), INode::num_outputs(), INode::output(), and arm_compute::validate().
validate_channel_shuffle_layer()
Status arm_compute::graph::backends::detail::validate_channel_shuffle_layer (ChannelShuffleLayerNode & node)
Validates a Channel Shuffle layer node.
Template Parameters
ChannelShuffleLayer Channel Shuffle layer function type
Parameters
[in] node Node to validate
Returns
Status
Definition at line 112 of file ValidateHelpers.h.
 {
     ARM_COMPUTE_LOG_GRAPH_VERBOSE(
         "Validating ChannelShuffle node with ID : " << node.id() << " and Name: " << node.name() << std::endl);
     ARM_COMPUTE_RETURN_ERROR_ON(node.num_inputs() != 1);
     ARM_COMPUTE_RETURN_ERROR_ON(node.num_outputs() != 1);
     // Extract IO and info
     arm_compute::ITensorInfo *input      = get_backing_tensor_info(node.input(0));
     arm_compute::ITensorInfo *output     = get_backing_tensor_info(node.output(0));
     const unsigned int        num_groups = node.num_groups();
     return ChannelShuffleLayer::validate(input, output, num_groups);
 }
References ARM_COMPUTE_LOG_GRAPH_VERBOSE, ARM_COMPUTE_RETURN_ERROR_ON, get_backing_tensor_info(), INode::id(), INode::input(), arm_compute::test::validation::input, INode::name(), ChannelShuffleLayerNode::num_groups(), arm_compute::test::validation::num_groups, INode::num_inputs(), INode::num_outputs(), INode::output(), and arm_compute::validate().
validate_convolution_layer()
Status arm_compute::graph::backends::detail::validate_convolution_layer (ConvolutionLayerNode & node)
Validates a Convolution layer node.
Template Parameters
ConvolutionLayer Default Convolution layer function type
DirectConvolutionLayer Direct Convolution layer function type
GEMMConvolutionLayer GEMM Convolution layer function type
WinogradConvolutionLayer Winograd Convolution layer function type
Parameters
[in] node Node to validate
Returns
Status
Definition at line 142 of file ValidateHelpers.h.
 {
     ARM_COMPUTE_LOG_GRAPH_VERBOSE(
         "Validating ConvolutionLayer node with ID : " << node.id() << " and Name: " << node.name() << std::endl);
     ARM_COMPUTE_RETURN_ERROR_ON(node.num_inputs() != 3);
     ARM_COMPUTE_RETURN_ERROR_ON(node.num_outputs() != 1);
     // Extract IO and info
     arm_compute::ITensorInfo *input   = get_backing_tensor_info(node.input(0));
     arm_compute::ITensorInfo *weights = get_backing_tensor_info(node.input(1));
     arm_compute::ITensorInfo *biases  = get_backing_tensor_info(node.input(2));
     arm_compute::ITensorInfo *output  = get_backing_tensor_info(node.output(0));
     if (is_data_type_quantized_asymmetric(input->data_type()))
     {
         biases->set_data_type(DataType::S32);
     }
     const PadStrideInfo     conv_info      = node.convolution_info();
     const ConvolutionMethod conv_algorithm = node.convolution_method();
     const bool              fast_math      = node.fast_math_hint() == FastMathHint::Enabled;
     const unsigned int      num_groups     = node.num_groups();
     // Validate function
     Status status{};
     switch (conv_algorithm)
     {
         case ConvolutionMethod::Direct:
             ARM_COMPUTE_RETURN_ERROR_ON_MSG(num_groups != 1, "DirectConvolutionLayer does not support grouping!");
             status = DirectConvolutionLayer::validate(input, weights, biases, output, conv_info);
             break;
         case ConvolutionMethod::GEMM:
             status = GEMMConvolutionLayer::validate(input, weights, biases, output, conv_info, WeightsInfo(),
                                                     Size2D(1, 1), ActivationLayerInfo(), num_groups);
             break;
         case ConvolutionMethod::Winograd:
             ARM_COMPUTE_RETURN_ERROR_ON_MSG(num_groups != 1, "WinogradConvolutionLayer does not support grouping!");
             status = WinogradConvolutionLayer::validate(input, weights, biases, output, conv_info,
                                                         ActivationLayerInfo(), fast_math);
             break;
         case ConvolutionMethod::Default:
             status = ConvolutionLayer::validate(input, weights, biases, output, conv_info, WeightsInfo(), Size2D(1, 1),
                                                 ActivationLayerInfo(), fast_math, num_groups);
             break;
         default:
             ARM_COMPUTE_RETURN_ERROR_MSG("Unsupported convolution method");
     }
     return status;
 }
References ARM_COMPUTE_LOG_GRAPH_VERBOSE, ARM_COMPUTE_RETURN_ERROR_MSG, ARM_COMPUTE_RETURN_ERROR_ON, ARM_COMPUTE_RETURN_ERROR_ON_MSG, arm_compute::test::validation::conv_info, ConvolutionLayerNode::convolution_info(), ConvolutionLayerNode::convolution_method(), arm_compute::graph::Default, arm_compute::graph::Direct, arm_compute::graph::Enabled, ConvolutionLayerNode::fast_math_hint(), arm_compute::graph::GEMM, get_backing_tensor_info(), INode::id(), INode::input(), arm_compute::test::validation::input, arm_compute::is_data_type_quantized_asymmetric(), INode::name(), ConvolutionLayerNode::num_groups(), arm_compute::test::validation::num_groups, INode::num_inputs(), INode::num_outputs(), INode::output(), arm_compute::S32, ITensorInfo::set_data_type(), arm_compute::validate(), and arm_compute::graph::Winograd.
Referenced by CLNodeValidator::validate(), and NENodeValidator::validate().
validate_depth_to_space_layer()
Status arm_compute::graph::backends::detail::validate_depth_to_space_layer (DepthToSpaceLayerNode & node)
Validates a depth to space layer node.
Template Parameters
DequantizationLayer Dequantize layer type
Parameters
[in] node Node to validate
Returns
Status
Definition at line 242 of file ValidateHelpers.h.
 {
     ARM_COMPUTE_LOG_GRAPH_VERBOSE(
         "Validating DetectionOutputLayer node with ID : " << node.id() << " and Name: " << node.name() << std::endl);
     ARM_COMPUTE_RETURN_ERROR_ON(node.num_inputs() != 1);
     ARM_COMPUTE_RETURN_ERROR_ON(node.num_outputs() != 1);
     // Extract IO and info
     arm_compute::ITensorInfo *input  = get_backing_tensor_info(node.input(0));
     arm_compute::ITensorInfo *output = get_backing_tensor_info(node.output(0));
     return DepthToSpaceLayer::validate(input, output, node.block_shape());
 }
References ARM_COMPUTE_LOG_GRAPH_VERBOSE, ARM_COMPUTE_RETURN_ERROR_ON, DepthToSpaceLayerNode::block_shape(), get_backing_tensor_info(), INode::id(), INode::input(), arm_compute::test::validation::input, INode::name(), INode::num_inputs(), INode::num_outputs(), INode::output(), and arm_compute::validate().
validate_depthwise_convolution_layer()
Status arm_compute::graph::backends::detail::validate_depthwise_convolution_layer (DepthwiseConvolutionLayerNode & node)
Validates a Depthwise Convolution layer node.
Template Parameters
DepthwiseConvolutionLayer Default Depthwise Convolution layer type
Parameters
[in] node Node to validate
Returns
Status
Definition at line 202 of file ValidateHelpers.h.
 {
     ARM_COMPUTE_LOG_GRAPH_VERBOSE("Validating DepthwiseConvolutionLayer node with ID : " << node.id() << " and Name: "
                                                                                          << node.name() << std::endl);
     ARM_COMPUTE_RETURN_ERROR_ON(node.num_inputs() != 3);
     ARM_COMPUTE_RETURN_ERROR_ON(node.num_outputs() != 1);
     // Extract IO and info
     arm_compute::ITensorInfo *input   = detail::get_backing_tensor_info(node.input(0));
     arm_compute::ITensorInfo *weights = detail::get_backing_tensor_info(node.input(1));
     arm_compute::ITensorInfo *biases  = get_backing_tensor_info(node.input(2));
     arm_compute::ITensorInfo *output  = get_backing_tensor_info(node.output(0));
     const PadStrideInfo              conv_info        = node.convolution_info();
     const DepthwiseConvolutionMethod dwc_algorithm    = node.depthwise_convolution_method();
     const int                        depth_multiplier = node.depth_multiplier();
     // Validate function
     Status status{};
     switch (dwc_algorithm)
     {
         case DepthwiseConvolutionMethod::Default:
         case DepthwiseConvolutionMethod::Optimized3x3:
             status = DepthwiseConvolutionLayer::validate(input, weights, biases, output, conv_info, depth_multiplier);
             break;
         default:
             ARM_COMPUTE_RETURN_ERROR_MSG("Unsupported depthwise convolution method");
     }
     return status;
 }
References ARM_COMPUTE_LOG_GRAPH_VERBOSE, ARM_COMPUTE_RETURN_ERROR_MSG, ARM_COMPUTE_RETURN_ERROR_ON, arm_compute::test::validation::conv_info, DepthwiseConvolutionLayerNode::convolution_info(), arm_compute::graph::Default, DepthwiseConvolutionLayerNode::depth_multiplier(), DepthwiseConvolutionLayerNode::depthwise_convolution_method(), get_backing_tensor_info(), INode::id(), INode::input(), arm_compute::test::validation::input, INode::name(), INode::num_inputs(), INode::num_outputs(), arm_compute::graph::Optimized3x3, INode::output(), and arm_compute::validate().
validate_dequantization_layer()
Status arm_compute::graph::backends::detail::validate_dequantization_layer (DequantizationLayerNode & node)
Validates a dequantize layer node.
Template Parameters
DequantizationLayer Dequantize layer type
Parameters
[in] node Node to validate
Returns
Status
Definition at line 264 of file ValidateHelpers.h.
 {
     ARM_COMPUTE_LOG_GRAPH_VERBOSE(
         "Validating DetectionOutputLayer node with ID : " << node.id() << " and Name: " << node.name() << std::endl);
     ARM_COMPUTE_RETURN_ERROR_ON(node.num_inputs() != 1);
     ARM_COMPUTE_RETURN_ERROR_ON(node.num_outputs() != 1);
     // Extract IO and info
     arm_compute::ITensorInfo *input  = get_backing_tensor_info(node.input(0));
     arm_compute::ITensorInfo *output = get_backing_tensor_info(node.output(0));
     return DequantizationLayer::validate(input, output);
 }
References ARM_COMPUTE_LOG_GRAPH_VERBOSE, ARM_COMPUTE_RETURN_ERROR_ON, get_backing_tensor_info(), INode::id(), INode::input(), arm_compute::test::validation::input, INode::name(), INode::num_inputs(), INode::num_outputs(), INode::output(), and arm_compute::validate().
validate_detection_output_layer()
Status arm_compute::graph::backends::detail::validate_detection_output_layer (DetectionOutputLayerNode & node)
Validates a detection output layer node.
Template Parameters
DetectionOutputLayer DetectionOutput layer type
Parameters
[in] node Node to validate
Returns
Status
Definition at line 286 of file ValidateHelpers.h.
 {
     ARM_COMPUTE_LOG_GRAPH_VERBOSE(
         "Validating DetectionOutputLayer node with ID : " << node.id() << " and Name: " << node.name() << std::endl);
     ARM_COMPUTE_RETURN_ERROR_ON(node.num_inputs() != 3);
     ARM_COMPUTE_RETURN_ERROR_ON(node.num_outputs() != 1);
     // Extract IO and info
     arm_compute::ITensorInfo      *input0      = get_backing_tensor_info(node.input(0));
     arm_compute::ITensorInfo      *input1      = get_backing_tensor_info(node.input(1));
     arm_compute::ITensorInfo      *input2      = get_backing_tensor_info(node.input(2));
     arm_compute::ITensorInfo      *output      = get_backing_tensor_info(node.output(0));
     const DetectionOutputLayerInfo detect_info = node.detection_output_info();
     return DetectionOutputLayer::validate(input0, input1, input2, output, detect_info);
 }
References ARM_COMPUTE_LOG_GRAPH_VERBOSE, ARM_COMPUTE_RETURN_ERROR_ON, DetectionOutputLayerNode::detection_output_info(), get_backing_tensor_info(), INode::id(), INode::input(), INode::name(), INode::num_inputs(), INode::num_outputs(), INode::output(), and arm_compute::validate().
validate_detection_post_process_layer()
Status arm_compute::graph::backends::detail::validate_detection_post_process_layer (DetectionPostProcessLayerNode & node)
Validates a detection post process layer node.
Template Parameters
DetectionPostProcessLayer DetectionOutput layer type
Parameters
[in] node Node to validate
Returns
Status
Definition at line 311 of file ValidateHelpers.h.
 {
     ARM_COMPUTE_LOG_GRAPH_VERBOSE("Validating DetectionPostProcessLayer node with ID : " << node.id() << " and Name: "
                                                                                          << node.name() << std::endl);
     ARM_COMPUTE_RETURN_ERROR_ON(node.num_inputs() != 3);
     ARM_COMPUTE_RETURN_ERROR_ON(node.num_outputs() != 4);
     // Extract IO and info
     arm_compute::ITensorInfo           *input0      = get_backing_tensor_info(node.input(0));
     arm_compute::ITensorInfo           *input1      = get_backing_tensor_info(node.input(1));
     arm_compute::ITensorInfo           *input2      = get_backing_tensor_info(node.input(2));
     arm_compute::ITensorInfo           *output0     = get_backing_tensor_info(node.output(0));
     arm_compute::ITensorInfo           *output1     = get_backing_tensor_info(node.output(1));
     arm_compute::ITensorInfo           *output2     = get_backing_tensor_info(node.output(2));
     arm_compute::ITensorInfo           *output3     = get_backing_tensor_info(node.output(3));
     const DetectionPostProcessLayerInfo detect_info = node.detection_post_process_info();
     return DetectionPostProcessLayer::validate(input0, input1, input2, output0, output1, output2, output3, detect_info);
 }
References ARM_COMPUTE_LOG_GRAPH_VERBOSE, ARM_COMPUTE_RETURN_ERROR_ON, DetectionPostProcessLayerNode::detection_post_process_info(), get_backing_tensor_info(), INode::id(), INode::input(), INode::name(), INode::num_inputs(), INode::num_outputs(), INode::output(), and arm_compute::validate().
validate_eltwise_Layer()
Status arm_compute::graph::backends::detail::validate_eltwise_Layer (EltwiseLayerNode & node)
Validates a element-wise layer node.
Parameters
[in] node Node to validate
Returns
Status
Definition at line 691 of file ValidateHelpers.h.
 {
     ARM_COMPUTE_LOG_GRAPH_VERBOSE("Validating EltwiseLayer node with ID : " << node.id() << " and Name: " << node.name()
                                                                             << std::endl);
     ARM_COMPUTE_RETURN_ERROR_ON(node.num_inputs() != 2);
     ARM_COMPUTE_RETURN_ERROR_ON(node.num_outputs() != 1);
     // Extract input and output
     const arm_compute::ITensorInfo *input1         = detail::get_backing_tensor_info(node.input(0));
     const arm_compute::ITensorInfo *input2         = detail::get_backing_tensor_info(node.input(1));
     const arm_compute::ITensorInfo *output         = get_backing_tensor_info(node.output(0));
     const EltwiseOperation          eltwise_op     = node.eltwise_operation();
     const ConvertPolicy             convert_policy = node.convert_policy();
     const RoundingPolicy            round_policy   = node.rounding_policy();
     const ActivationLayerInfo       act_info       = node.fused_activation();
     const QuantizationInfo          quant_info     = node.output_quant_info();
     // Validate function
     if (eltwise_op == EltwiseOperation::Add)
     {
         return EltwiseLayerFunctions::ArithmeticAddition::validate(input1, input2, output, convert_policy, act_info);
     }
     else if (eltwise_op == EltwiseOperation::Sub)
     {
         return EltwiseLayerFunctions::ArithmeticSubtraction::validate(input1, input2, output, convert_policy, act_info);
     }
     else if (eltwise_op == EltwiseOperation::Mul)
     {
         return EltwiseLayerFunctions::PixelWiseMultiplication::validate(input1, input2, output, 1.0f, convert_policy,
                                                                         round_policy, act_info);
     }
     else if (eltwise_op == EltwiseOperation::Max)
     {
         return EltwiseLayerFunctions::ElementwiseMax::validate(input1, input2, output, act_info);
     }
     else if (eltwise_op == EltwiseOperation::Div)
     {
         return EltwiseLayerFunctions::ArithmeticDivision::validate(input1, input2, output, act_info);
     }
     else
     {
         ARM_COMPUTE_ERROR("Unsupported element-wise operation!");
     }
     return Status{};
 }
References arm_compute::test::validation::act_info, arm_compute::graph::Add, ARM_COMPUTE_ERROR, ARM_COMPUTE_LOG_GRAPH_VERBOSE, ARM_COMPUTE_RETURN_ERROR_ON, EltwiseLayerNode::convert_policy(), arm_compute::graph::Div, EltwiseLayerNode::eltwise_operation(), EltwiseLayerNode::fused_activation(), get_backing_tensor_info(), INode::id(), INode::input(), arm_compute::graph::Max, arm_compute::graph::Mul, INode::name(), INode::num_inputs(), INode::num_outputs(), INode::output(), EltwiseLayerNode::output_quant_info(), EltwiseLayerNode::rounding_policy(), arm_compute::graph::Sub, and arm_compute::validate().
validate_generate_proposals_layer()
Status arm_compute::graph::backends::detail::validate_generate_proposals_layer (GenerateProposalsLayerNode & node)
Validates a Generate Proposals layer node.
Template Parameters
GenerateProposalsLayer Generate Proposals layer type
Parameters
[in] node Node to validate
Returns
Status
Definition at line 340 of file ValidateHelpers.h.
 {
     ARM_COMPUTE_LOG_GRAPH_VERBOSE(
         "Validating GenerateProposalsLayer node with ID : " << node.id() << " and Name: " << node.name() << std::endl);
     ARM_COMPUTE_RETURN_ERROR_ON(node.num_inputs() != 3);
     ARM_COMPUTE_RETURN_ERROR_ON(node.num_outputs() != 3);
     // Extract IO and info
     arm_compute::ITensorInfo   *scores              = detail::get_backing_tensor_info(node.input(0));
     arm_compute::ITensorInfo   *deltas              = detail::get_backing_tensor_info(node.input(1));
     arm_compute::ITensorInfo   *anchors             = detail::get_backing_tensor_info(node.input(2));
     arm_compute::ITensorInfo   *proposals           = get_backing_tensor_info(node.output(0));
     arm_compute::ITensorInfo   *scores_out          = get_backing_tensor_info(node.output(1));
     arm_compute::ITensorInfo   *num_valid_proposals = get_backing_tensor_info(node.output(2));
     const GenerateProposalsInfo info                = node.info();
     return GenerateProposalsLayer::validate(scores, deltas, anchors, proposals, scores_out, num_valid_proposals, info);
 }
References ARM_COMPUTE_LOG_GRAPH_VERBOSE, ARM_COMPUTE_RETURN_ERROR_ON, get_backing_tensor_info(), INode::id(), GenerateProposalsLayerNode::info(), arm_compute::test::validation::info, INode::input(), INode::name(), INode::num_inputs(), INode::num_outputs(), INode::output(), and arm_compute::validate().
validate_l2_normalize_layer()
Status arm_compute::graph::backends::detail::validate_l2_normalize_layer (L2NormalizeLayerNode & node)
Validates a L2Normalization layer node.
Template Parameters
L2Normalization layer type
Parameters
[in] node Node to validate
Returns
Status
Definition at line 368 of file ValidateHelpers.h.
 {
     ARM_COMPUTE_LOG_GRAPH_VERBOSE(
         "Validating L2NormalizeLayerNode node with ID : " << node.id() << " and Name: " << node.name() << std::endl);
     ARM_COMPUTE_RETURN_ERROR_ON(node.num_inputs() != 1);
     ARM_COMPUTE_RETURN_ERROR_ON(node.num_outputs() != 1);
     // Extract IO and info
     arm_compute::ITensorInfo *input   = detail::get_backing_tensor_info(node.input(0));
     arm_compute::ITensorInfo *output  = get_backing_tensor_info(node.output(0));
     int                       axis    = node.axis();
     float                     epsilon = node.epsilon();
     // Validate function
     return L2NormalizeLayer::validate(input, output, axis, epsilon);
 }
References ARM_COMPUTE_LOG_GRAPH_VERBOSE, ARM_COMPUTE_RETURN_ERROR_ON, L2NormalizeLayerNode::axis(), arm_compute::quantization::epsilon, L2NormalizeLayerNode::epsilon(), get_backing_tensor_info(), INode::id(), INode::input(), arm_compute::test::validation::input, INode::name(), INode::num_inputs(), INode::num_outputs(), INode::output(), and arm_compute::validate().
validate_node()
void arm_compute::graph::backends::detail::validate_node (const INode & node, size_t num_expected_inputs, size_t num_expected_outputs)
Definition at line 78 of file FunctionHelpers.h.
 {
     ARM_COMPUTE_LOG_GRAPH_VERBOSE("Creating " << node.type() << " Target: " << TargetInfo::TargetType
                                               << " ID: " << node.id() << node.name() << std::endl);
     ARM_COMPUTE_ERROR_ON(TargetInfo::TargetType != node.assigned_target());
     ARM_COMPUTE_ERROR_ON(node.num_inputs() != num_expected_inputs);
     ARM_COMPUTE_ERROR_ON(node.num_outputs() != num_expected_outputs);
     ARM_COMPUTE_UNUSED(node, num_expected_inputs, num_expected_outputs);
 }
References ARM_COMPUTE_ERROR_ON, ARM_COMPUTE_LOG_GRAPH_VERBOSE, ARM_COMPUTE_UNUSED, INode::assigned_target(), INode::id(), INode::name(), INode::num_inputs(), INode::num_outputs(), and INode::type().
validate_normalize_planar_yuv_layer()
Status arm_compute::graph::backends::detail::validate_normalize_planar_yuv_layer (NormalizePlanarYUVLayerNode & node)
Validates a NormalizePlanarYUV layer node.
Template Parameters
NormalizePlanarYUVLayer layer type
Parameters
[in] node Node to validate
Returns
Status
Definition at line 394 of file ValidateHelpers.h.
 {
     ARM_COMPUTE_LOG_GRAPH_VERBOSE(
         "Validating NormalizePlanarYUVLayer node with ID : " << node.id() << " and Name: " << node.name() << std::endl);
     ARM_COMPUTE_RETURN_ERROR_ON(node.num_inputs() != 3);
     ARM_COMPUTE_RETURN_ERROR_ON(node.num_outputs() != 1);
     // Extract IO and info
     arm_compute::ITensorInfo *input  = detail::get_backing_tensor_info(node.input(0));
     arm_compute::ITensorInfo *mean   = detail::get_backing_tensor_info(node.input(1));
     arm_compute::ITensorInfo *std    = detail::get_backing_tensor_info(node.input(2));
     arm_compute::ITensorInfo *output = get_backing_tensor_info(node.output(0));
     // Validate function
     return NormalizePlanarYUVLayer::validate(input, output, mean, std);
 }
References ARM_COMPUTE_LOG_GRAPH_VERBOSE, ARM_COMPUTE_RETURN_ERROR_ON, get_backing_tensor_info(), INode::id(), INode::input(), arm_compute::test::validation::input, INode::name(), INode::num_inputs(), INode::num_outputs(), INode::output(), and arm_compute::validate().
validate_pad_layer()
Status arm_compute::graph::backends::detail::validate_pad_layer (PadLayerNode & node)
Validates a pad layer node.
Template Parameters
PadLayer Pad layer type
Parameters
[in] node Node to validate
Returns
Status
Definition at line 420 of file ValidateHelpers.h.
 {
     ARM_COMPUTE_LOG_GRAPH_VERBOSE("Validating PadLayer node with ID : " << node.id() << " and Name: " << node.name()
                                                                         << std::endl);
     ARM_COMPUTE_RETURN_ERROR_ON(node.num_inputs() != 1);
     ARM_COMPUTE_RETURN_ERROR_ON(node.num_outputs() != 1);
     // Extract IO and info
     arm_compute::ITensorInfo *input   = get_backing_tensor_info(node.input(0));
     arm_compute::ITensorInfo *output  = get_backing_tensor_info(node.output(0));
     const PaddingList        &padding = node.padding();
     return PadLayer::validate(input, output, padding);
 }
References ARM_COMPUTE_LOG_GRAPH_VERBOSE, ARM_COMPUTE_RETURN_ERROR_ON, get_backing_tensor_info(), INode::id(), INode::input(), arm_compute::test::validation::input, INode::name(), INode::num_inputs(), INode::num_outputs(), INode::output(), PadLayerNode::padding(), and arm_compute::validate().
validate_permute_layer()
Status arm_compute::graph::backends::detail::validate_permute_layer (PermuteLayerNode & node)
Validates a permute layer node.
Template Parameters
PermuteLayer Permute layer type
Parameters
[in] node Node to validate
Returns
Status
Definition at line 444 of file ValidateHelpers.h.
 {
     ARM_COMPUTE_LOG_GRAPH_VERBOSE("Validating PermuteLayer node with ID : " << node.id() << " and Name: " << node.name()
                                                                             << std::endl);
     ARM_COMPUTE_RETURN_ERROR_ON(node.num_inputs() != 1);
     ARM_COMPUTE_RETURN_ERROR_ON(node.num_outputs() != 1);
     // Extract IO and info
     arm_compute::ITensorInfo *input  = get_backing_tensor_info(node.input(0));
     arm_compute::ITensorInfo *output = get_backing_tensor_info(node.output(0));
     const PermutationVector  &perm   = node.permutation_vector();
     return PermuteLayer::validate(input, output, perm);
 }
References ARM_COMPUTE_LOG_GRAPH_VERBOSE, ARM_COMPUTE_RETURN_ERROR_ON, get_backing_tensor_info(), INode::id(), INode::input(), arm_compute::test::validation::input, INode::name(), INode::num_inputs(), INode::num_outputs(), INode::output(), PermuteLayerNode::permutation_vector(), and arm_compute::validate().
validate_prelu_layer()
Status arm_compute::graph::backends::detail::validate_prelu_layer (PReluLayerNode & node)
Validates a PRelu layer node.
Template Parameters
PReluLayer PRelu layer type
Parameters
[in] node Node to validate
Returns
Status
Definition at line 468 of file ValidateHelpers.h.
 {
     ARM_COMPUTE_LOG_GRAPH_VERBOSE("Validating PRelu node with ID : " << node.id() << " and Name: " << node.name()
                                                                      << std::endl);
     ARM_COMPUTE_RETURN_ERROR_ON(node.num_inputs() != 2);
     ARM_COMPUTE_RETURN_ERROR_ON(node.num_outputs() != 1);
     // Extract IO and info
     arm_compute::ITensorInfo *input  = get_backing_tensor_info(node.input(0));
     arm_compute::ITensorInfo *alpha  = get_backing_tensor_info(node.input(1));
     arm_compute::ITensorInfo *output = get_backing_tensor_info(node.output(0));
     return PReluLayer::validate(input, alpha, output);
 }
References ARM_COMPUTE_LOG_GRAPH_VERBOSE, ARM_COMPUTE_RETURN_ERROR_ON, get_backing_tensor_info(), INode::id(), INode::input(), arm_compute::test::validation::input, INode::name(), INode::num_inputs(), INode::num_outputs(), INode::output(), and arm_compute::validate().
validate_priorbox_layer()
Status arm_compute::graph::backends::detail::validate_priorbox_layer (PriorBoxLayerNode & node)
Validates a priorbox layer node.
Template Parameters
PriorBoxLayer PriorBox layer type
Parameters
[in] node Node to validate
Returns
Status
Definition at line 492 of file ValidateHelpers.h.
 {
     ARM_COMPUTE_LOG_GRAPH_VERBOSE(
         "Validating PriorBoxLayer node with ID : " << node.id() << " and Name: " << node.name() << std::endl);
     ARM_COMPUTE_RETURN_ERROR_ON(node.num_inputs() != 2);
     ARM_COMPUTE_RETURN_ERROR_ON(node.num_outputs() != 1);
     // Extract IO and info
     arm_compute::ITensorInfo *input0     = get_backing_tensor_info(node.input(0));
     arm_compute::ITensorInfo *input1     = get_backing_tensor_info(node.input(1));
     arm_compute::ITensorInfo *output     = get_backing_tensor_info(node.output(0));
     const PriorBoxLayerInfo   prior_info = node.priorbox_info();
     return PriorBoxLayer::validate(input0, input1, output, prior_info);
 }
References ARM_COMPUTE_LOG_GRAPH_VERBOSE, ARM_COMPUTE_RETURN_ERROR_ON, get_backing_tensor_info(), INode::id(), INode::input(), INode::name(), INode::num_inputs(), INode::num_outputs(), INode::output(), PriorBoxLayerNode::priorbox_info(), and arm_compute::validate().
validate_quantization_layer()
Status arm_compute::graph::backends::detail::validate_quantization_layer (QuantizationLayerNode & node)
Validates a Quantization layer node.
Template Parameters
QuantizationLayer Quantization layer type
Parameters
[in] node Node to validate
Returns
Status
Definition at line 517 of file ValidateHelpers.h.
 {
     ARM_COMPUTE_LOG_GRAPH_VERBOSE(
         "Validating QuantizationLayer node with ID : " << node.id() << " and Name: " << node.name() << std::endl);
     ARM_COMPUTE_RETURN_ERROR_ON(node.num_inputs() != 1);
     ARM_COMPUTE_RETURN_ERROR_ON(node.num_outputs() != 1);
     // Extract input and output
     arm_compute::ITensorInfo *input  = detail::get_backing_tensor_info(node.input(0));
     arm_compute::ITensorInfo *output = get_backing_tensor_info(node.output(0));
     // Validate function
     return QuantizationLayer::validate(input, output);
 }
References ARM_COMPUTE_LOG_GRAPH_VERBOSE, ARM_COMPUTE_RETURN_ERROR_ON, get_backing_tensor_info(), INode::id(), INode::input(), arm_compute::test::validation::input, INode::name(), INode::num_inputs(), INode::num_outputs(), INode::output(), and arm_compute::validate().
validate_reduction_operation_layer()
Status arm_compute::graph::backends::detail::validate_reduction_operation_layer (ReductionLayerNode & node)
Validates a Reduction operation layer node.
Template Parameters
ReductionLayer Reduction layer type
Parameters
[in] node Node to validate
Returns
Status
Definition at line 541 of file ValidateHelpers.h.
 {
     ARM_COMPUTE_LOG_GRAPH_VERBOSE(
         "Validating ReductionLayer node with ID : " << node.id() << " and Name: " << node.name() << std::endl);
     ARM_COMPUTE_RETURN_ERROR_ON(node.num_inputs() != 1);
     ARM_COMPUTE_RETURN_ERROR_ON(node.num_outputs() != 1);
     // Extract input and output
     arm_compute::ITensorInfo *input  = detail::get_backing_tensor_info(node.input(0));
     arm_compute::ITensorInfo *output = get_backing_tensor_info(node.output(0));
     // Validate function
     return ReductionLayer::validate(input, output, node.axis(), node.op(), node.keep_dims());
 }
References ARM_COMPUTE_LOG_GRAPH_VERBOSE, ARM_COMPUTE_RETURN_ERROR_ON, ReductionLayerNode::axis(), get_backing_tensor_info(), INode::id(), INode::input(), arm_compute::test::validation::input, ReductionLayerNode::keep_dims(), INode::name(), INode::num_inputs(), INode::num_outputs(), ReductionLayerNode::op(), INode::output(), and arm_compute::validate().
validate_reorg_layer()
Status arm_compute::graph::backends::detail::validate_reorg_layer (ReorgLayerNode & node)
Validates a Reorg layer node.
Template Parameters
ReorgLayer Reorg layer type
Parameters
[in] node Node to validate
Returns
Status
Definition at line 566 of file ValidateHelpers.h.
 {
     ARM_COMPUTE_LOG_GRAPH_VERBOSE("Validating ReorgLayer node with ID : " << node.id() << " and Name: " << node.name()
                                                                           << std::endl);
     ARM_COMPUTE_RETURN_ERROR_ON(node.num_inputs() != 1);
     ARM_COMPUTE_RETURN_ERROR_ON(node.num_outputs() != 1);
     // Extract input and output
     arm_compute::ITensorInfo *input  = detail::get_backing_tensor_info(node.input(0));
     arm_compute::ITensorInfo *output = get_backing_tensor_info(node.output(0));
     // Validate function
     return ReorgLayer::validate(input, output, node.stride());
 }
References ARM_COMPUTE_LOG_GRAPH_VERBOSE, ARM_COMPUTE_RETURN_ERROR_ON, get_backing_tensor_info(), INode::id(), INode::input(), arm_compute::test::validation::input, INode::name(), INode::num_inputs(), INode::num_outputs(), INode::output(), ReorgLayerNode::stride(), and arm_compute::validate().
validate_reshape_layer()
Status arm_compute::graph::backends::detail::validate_reshape_layer (ReshapeLayerNode & node)
Validates a Reshape layer node.
Template Parameters
ReshapeLayer Reshape layer type
Parameters
[in] node Node to validate
Returns
Status
Definition at line 590 of file ValidateHelpers.h.
 {
     ARM_COMPUTE_LOG_GRAPH_VERBOSE("Validating ReshapeLayer node with ID : " << node.id() << " and Name: " << node.name()
                                                                             << std::endl);
     ARM_COMPUTE_RETURN_ERROR_ON(node.num_inputs() != 1);
     ARM_COMPUTE_RETURN_ERROR_ON(node.num_outputs() != 1);
     // Extract input and output
     arm_compute::ITensorInfo *input  = detail::get_backing_tensor_info(node.input(0));
     arm_compute::ITensorInfo *output = detail::get_backing_tensor_info(node.output(0));
     // Validate function
     return ReshapeLayer::validate(input, output);
 }
References ARM_COMPUTE_LOG_GRAPH_VERBOSE, ARM_COMPUTE_RETURN_ERROR_ON, get_backing_tensor_info(), INode::id(), INode::input(), arm_compute::test::validation::input, INode::name(), INode::num_inputs(), INode::num_outputs(), INode::output(), and arm_compute::validate().
validate_roi_align_layer()
Status arm_compute::graph::backends::detail::validate_roi_align_layer (ROIAlignLayerNode & node)
Validates a ROI Align layer node.
Template Parameters
ROIAlignLayer ROIAlign layer type
Parameters
[in] node Node to validate
Returns
Status
Definition at line 614 of file ValidateHelpers.h.
 {
     ARM_COMPUTE_LOG_GRAPH_VERBOSE(
         "Validating ROIAlignLayer node with ID : " << node.id() << " and Name: " << node.name() << std::endl);
     ARM_COMPUTE_RETURN_ERROR_ON(node.num_inputs() != 2);
     ARM_COMPUTE_RETURN_ERROR_ON(node.num_outputs() != 1);
     // Extract input and output
     arm_compute::ITensorInfo  *input     = detail::get_backing_tensor_info(node.input(0));
     arm_compute::ITensorInfo  *rois      = detail::get_backing_tensor_info(node.input(1));
     arm_compute::ITensorInfo  *output    = detail::get_backing_tensor_info(node.output(0));
     const ROIPoolingLayerInfo &pool_info = node.pooling_info();
     // Validate function
     return ROIAlignLayer::validate(input, rois, output, pool_info);
 }
References ARM_COMPUTE_LOG_GRAPH_VERBOSE, ARM_COMPUTE_RETURN_ERROR_ON, get_backing_tensor_info(), INode::id(), INode::input(), arm_compute::test::validation::input, INode::name(), INode::num_inputs(), INode::num_outputs(), INode::output(), ROIAlignLayerNode::pooling_info(), and arm_compute::validate().
validate_slice_layer()
Status arm_compute::graph::backends::detail::validate_slice_layer (SliceLayerNode & node)
Validates a Slice layer node.
Template Parameters
SliceLayer Slice layer function type
Parameters
[in] node Node to validate
Returns
Status
Definition at line 640 of file ValidateHelpers.h.
 {
     ARM_COMPUTE_LOG_GRAPH_VERBOSE("Validating Slice node with ID : " << node.id() << " and Name: " << node.name()
                                                                      << std::endl);
     ARM_COMPUTE_RETURN_ERROR_ON(node.num_inputs() != 1);
     ARM_COMPUTE_RETURN_ERROR_ON(node.num_outputs() != 1);
     // Extract IO and info
     arm_compute::ITensorInfo *input  = get_backing_tensor_info(node.input(0));
     arm_compute::ITensorInfo *output = get_backing_tensor_info(node.output(0));
     const Coordinates         starts = node.starts();
     const Coordinates         ends   = node.ends();
     return SliceLayer::validate(input, output, starts, ends);
 }
References ARM_COMPUTE_LOG_GRAPH_VERBOSE, ARM_COMPUTE_RETURN_ERROR_ON, SliceLayerNode::ends(), get_backing_tensor_info(), INode::id(), INode::input(), arm_compute::test::validation::input, INode::name(), INode::num_inputs(), INode::num_outputs(), INode::output(), SliceLayerNode::starts(), and arm_compute::validate().
validate_strided_slice_layer()
Status arm_compute::graph::backends::detail::validate_strided_slice_layer (StridedSliceLayerNode & node)
Validates a Strided Slice layer node.
Template Parameters
StridedSliceLayer Strided Slice layer function type
Parameters
[in] node Node to validate
Returns
Status
Definition at line 665 of file ValidateHelpers.h.
 {
     ARM_COMPUTE_LOG_GRAPH_VERBOSE("Validating StridedSlice node with ID : " << node.id() << " and Name: " << node.name()
                                                                             << std::endl);
     ARM_COMPUTE_RETURN_ERROR_ON(node.num_inputs() != 1);
     ARM_COMPUTE_RETURN_ERROR_ON(node.num_outputs() != 1);
     // Extract IO and info
     arm_compute::ITensorInfo   *input   = get_backing_tensor_info(node.input(0));
     arm_compute::ITensorInfo   *output  = get_backing_tensor_info(node.output(0));
     const Coordinates           starts  = node.starts();
     const Coordinates           ends    = node.ends();
     const BiStrides             strides = node.strides();
     const StridedSliceLayerInfo info    = node.strided_slice_info();
     return StridedSliceLayer::validate(input, output, starts, ends, strides, info.begin_mask(), info.end_mask(),
                                        info.shrink_axis_mask());
 }
References ARM_COMPUTE_LOG_GRAPH_VERBOSE, ARM_COMPUTE_RETURN_ERROR_ON, StridedSliceLayerNode::ends(), get_backing_tensor_info(), INode::id(), arm_compute::test::validation::info, INode::input(), arm_compute::test::validation::input, INode::name(), INode::num_inputs(), INode::num_outputs(), INode::output(), StridedSliceLayerNode::starts(), StridedSliceLayerNode::strided_slice_info(), StridedSliceLayerNode::strides(), and arm_compute::validate().
validate_unary_eltwise_layer()
Status arm_compute::graph::backends::detail::validate_unary_eltwise_layer (UnaryEltwiseLayerNode & node)
Validates a unary element-wise layer node.
Parameters
[in] node Node to validate
Returns
Status
Definition at line 743 of file ValidateHelpers.h.
 {
     ARM_COMPUTE_LOG_GRAPH_VERBOSE("Validating EltwiseLayer node with ID : " << node.id() << " and Name: " << node.name()
                                                                             << std::endl);
     ARM_COMPUTE_RETURN_ERROR_ON(node.num_inputs() != 1);
     ARM_COMPUTE_RETURN_ERROR_ON(node.num_outputs() != 1);
     // Extract input and output
     arm_compute::ITensorInfo   *input      = detail::get_backing_tensor_info(node.input(0));
     arm_compute::ITensorInfo   *output     = get_backing_tensor_info(node.output(0));
     const UnaryEltwiseOperation eltwise_op = node.eltwise_descriptor().op;
     // Validate function
     if (eltwise_op == UnaryEltwiseOperation::Exp)
     {
         return UnaryEltwiseLayerFunctions::ExpLayer::validate(input, output);
     }
     else
     {
         ARM_COMPUTE_ERROR("Unsupported unary element-wise operation!");
     }
     return Status{};
 }
References ARM_COMPUTE_ERROR, ARM_COMPUTE_LOG_GRAPH_VERBOSE, ARM_COMPUTE_RETURN_ERROR_ON, UnaryEltwiseLayerNode::eltwise_descriptor(), arm_compute::graph::Exp, get_backing_tensor_info(), INode::id(), INode::input(), arm_compute::test::validation::input, INode::name(), INode::num_inputs(), INode::num_outputs(), UnaryEltwiseLayerDescriptor::op, INode::output(), and arm_compute::validate().