Compute Library: Qasymm8QuantizationHelper< QUANTIZED_TYPE > Struct Template Reference
Qasymm8QuantizationHelper< QUANTIZED_TYPE > Struct Template Reference
#include <QuantizationInfo.h>
Static Public Member Functions
static QUANTIZED_TYPE quantize (float value, const UniformQuantizationInfo &qinfo)
Quantize a value given a 8-bit asymmetric quantization scheme.
static QUANTIZED_TYPE quantize (float value, const UniformQuantizationInfo &qinfo, RoundingPolicy rounding_policy)
Quantize a value given a 8-bit asymmetric quantization scheme using a specific rounding policy.
static QUANTIZED_TYPE quantize (float value, const QuantizationInfo &qinfo, RoundingPolicy rounding_policy=RoundingPolicy::TO_NEAREST_UP)
Quantize a value given a 8-bit asymmetric quantization scheme.
static float dequantize (QUANTIZED_TYPE value, const UniformQuantizationInfo &qinfo)
Dequantize a value given a 8-bit asymmetric quantization scheme.
static float dequantize (QUANTIZED_TYPE value, const QuantizationInfo &qinfo)
Dequantize a value given a 8-bit asymmetric quantization scheme.
Detailed Description
template<typename QUANTIZED_TYPE = uint8_t>
struct arm_compute::Qasymm8QuantizationHelper< QUANTIZED_TYPE >
Definition at line 202 of file QuantizationInfo.h.
Member Function Documentation
dequantize() [1/2]
static float dequantize (QUANTIZED_TYPE value, const QuantizationInfo & qinfo) inline static
Dequantize a value given a 8-bit asymmetric quantization scheme.
Parameters
[in] value Value to dequantize
[in] qinfo Quantization information to use for dequantizing
Returns
Dequantized value
Definition at line 278 of file QuantizationInfo.h.
     {
         const UniformQuantizationInfo uqinfo = qinfo.uniform();
         return (static_cast<int>(value) - uqinfo.offset) * uqinfo.scale;
     }
References UniformQuantizationInfo::offset, arm_compute::test::validation::qinfo, UniformQuantizationInfo::scale, and QuantizationInfo::uniform().
dequantize() [2/2]
static float dequantize (QUANTIZED_TYPE value, const UniformQuantizationInfo & qinfo) inline static
Dequantize a value given a 8-bit asymmetric quantization scheme.
Parameters
[in] value Value to dequantize
[in] qinfo Quantization information to use for dequantizing
Returns
Dequantized value
Definition at line 266 of file QuantizationInfo.h.
     {
         return (static_cast<int>(value) - qinfo.offset) * qinfo.scale;
     }
References QuantizationInfo::offset(), arm_compute::test::validation::qinfo, and QuantizationInfo::scale().
Referenced by arm_compute::dequantize_qasymm8(), arm_compute::dequantize_qasymm8_signed(), arm_compute::cpu::elementwise_arithmetic_quantized_op(), and arm_compute::cpu::elementwise_comparison_quantized_op().
quantize() [1/3]
static QUANTIZED_TYPE quantize (float value, const QuantizationInfo & qinfo, RoundingPolicy rounding_policy = RoundingPolicy::TO_NEAREST_UP) inline static
Quantize a value given a 8-bit asymmetric quantization scheme.
Parameters
[in] value Value to quantize
[in] qinfo Quantization information to use for quantizing
[in] rounding_policy (Optional) Rounding policy to use. Default: nearest up
Returns
Quantized value
Definition at line 251 of file QuantizationInfo.h.
     {
         const UniformQuantizationInfo uqinfo = qinfo.uniform();
         ARM_COMPUTE_ERROR_ON(uqinfo.scale == 0);
         const int quantized = arm_compute::round(value / uqinfo.scale, rounding_policy) + uqinfo.offset;
         return static_cast<QUANTIZED_TYPE>(arm_compute::utility::clamp<decltype(quantized), QUANTIZED_TYPE>(quantized));
     }
References ARM_COMPUTE_ERROR_ON, UniformQuantizationInfo::offset, arm_compute::test::validation::qinfo, arm_compute::round(), UniformQuantizationInfo::scale, and QuantizationInfo::uniform().
quantize() [2/3]
static QUANTIZED_TYPE quantize (float value, const UniformQuantizationInfo & qinfo) inline static
Quantize a value given a 8-bit asymmetric quantization scheme.
Parameters
[in] value Value to quantize
[in] qinfo Quantization information to use for quantizing
Returns
Quantized value
Definition at line 214 of file QuantizationInfo.h.
     {
         ARM_COMPUTE_ERROR_ON(qinfo.scale == 0);
         const int quantized = support::cpp11::lround(value / qinfo.scale) + qinfo.offset;
         return static_cast<QUANTIZED_TYPE>(arm_compute::utility::clamp<decltype(quantized), QUANTIZED_TYPE>(quantized));
     }
References ARM_COMPUTE_ERROR_ON, arm_compute::support::cpp11::lround(), QuantizationInfo::offset(), arm_compute::test::validation::qinfo, and QuantizationInfo::scale().
Referenced by Qasymm8QuantizationHelper< QUANTIZED_TYPE >::quantize(), arm_compute::quantize_qasymm8(), and arm_compute::quantize_qasymm8_signed().
quantize() [3/3]
static QUANTIZED_TYPE quantize (float value, const UniformQuantizationInfo & qinfo, RoundingPolicy rounding_policy) inline static
Quantize a value given a 8-bit asymmetric quantization scheme using a specific rounding policy.
Parameters
[in] value Value to quantize
[in] qinfo Quantization information to use for quantizing
[in] rounding_policy Rounding policy to use
Returns
Quantized value
Definition at line 230 of file QuantizationInfo.h.
     {
         if (rounding_policy == RoundingPolicy::TO_NEAREST_UP)
         {
             return quantize(value, qinfo);
         }
         ARM_COMPUTE_ERROR_ON(qinfo.scale == 0);
         const int quantized = arm_compute::round(value / qinfo.scale, rounding_policy) + qinfo.offset;
         return static_cast<QUANTIZED_TYPE>(arm_compute::utility::clamp<decltype(quantized), QUANTIZED_TYPE>(quantized));
     }
References ARM_COMPUTE_ERROR_ON, QuantizationInfo::offset(), arm_compute::test::validation::qinfo, Qasymm8QuantizationHelper< QUANTIZED_TYPE >::quantize(), arm_compute::round(), QuantizationInfo::scale(), and arm_compute::TO_NEAREST_UP.
The documentation for this struct was generated from the following file:
arm_compute/core/QuantizationInfo.h