Compute Library: ImageAccessor Class Reference
ImageAccessor Class Reference final
Image accessor class.
#include <GraphUtils.h>
Public Member Functions
ImageAccessor (std::string filename, bool bgr=true, std::unique_ptr< IPreprocessor > preprocessor=nullptr)
Constructor.
ImageAccessor (ImageAccessor &&)=default
Allow instances of this class to be move constructed.
bool access_tensor (ITensor &tensor) override
Interface to be implemented to access a given tensor.
Public Member Functions inherited from ITensorAccessor
virtual ~ITensorAccessor ()=default
Default virtual destructor.
virtual bool access_tensor_data ()
Returns true if the tensor data is being accessed.
Detailed Description
Image accessor class.
Definition at line 231 of file GraphUtils.h.
Constructor & Destructor Documentation
ImageAccessor() [1/2]
ImageAccessor (std::string filename, bool bgr = true, std::unique_ptr< IPreprocessor > preprocessor = nullptr)
Constructor.
Parameters
[in] filename Image file
[in] bgr (Optional) Fill the first plane with blue channel (default = false - RGB format)
[in] preprocessor (Optional) Image pre-processing object
Definition at line 258 of file GraphUtils.cpp.
     : _already_loaded(false), _filename(std::move(filename)), _bgr(bgr), _preprocessor(std::move(preprocessor))
 {
 }
ImageAccessor() [2/2]
ImageAccessor (ImageAccessor &&) default
Allow instances of this class to be move constructed.
Member Function Documentation
access_tensor()
bool access_tensor (ITensor & tensor) override virtual
Interface to be implemented to access a given tensor.
Parameters
[in] tensor Tensor to be accessed
Returns
True if access is successful else false
Implements ITensorAccessor.
Definition at line 263 of file GraphUtils.cpp.
References ARM_COMPUTE_EXIT_ON_MSG, ARM_COMPUTE_EXIT_ON_MSG_VAR, ImageLoaderFactory::create(), ITensorInfo::data_layout(), ITensor::info(), arm_compute::NCHW, ITensorInfo::tensor_shape(), Dimensions< T >::x(), and Dimensions< T >::y().
 {
     if(!_already_loaded)
     {
         auto image_loader = utils::ImageLoaderFactory::create(_filename);
         ARM_COMPUTE_EXIT_ON_MSG(image_loader == nullptr, "Unsupported image type");
         // Open image file
         image_loader->open(_filename);
         // Get permutated shape and permutation parameters
         TensorShape                    permuted_shape = tensor.info()->tensor_shape();
         arm_compute::PermutationVector perm;
         if(tensor.info()->data_layout() != DataLayout::NCHW)
         {
             std::tie(permuted_shape, perm) = compute_permutation_parameters(tensor.info()->tensor_shape(), tensor.info()->data_layout());
         }
 #ifdef __arm__
         ARM_COMPUTE_EXIT_ON_MSG_VAR(image_loader->width() != permuted_shape.x() || image_loader->height() != permuted_shape.y(),
                                     "Failed to load image file: dimensions [%d,%d] not correct, expected [%" PRIu32 ",%" PRIu32 "].",
                                     image_loader->width(), image_loader->height(), permuted_shape.x(), permuted_shape.y());
 #else  // __arm__
         ARM_COMPUTE_EXIT_ON_MSG_VAR(image_loader->width() != permuted_shape.x() || image_loader->height() != permuted_shape.y(),
                                     "Failed to load image file: dimensions [%d,%d] not correct, expected [%" PRIu64 ",%" PRIu64 "].",
                                     image_loader->width(), image_loader->height(),
                                     static_cast<uint64_t>(permuted_shape.x()), static_cast<uint64_t>(permuted_shape.y()));
 #endif // __arm__
         // Fill the tensor with the PPM content (BGR)
         image_loader->fill_planar_tensor(tensor, _bgr);
         // Preprocess tensor
         if(_preprocessor)
         {
             _preprocessor->preprocess(tensor);
         }
     }
     _already_loaded = !_already_loaded;
     return _already_loaded;
 }
The documentation for this class was generated from the following files:
utils/GraphUtils.h
utils/GraphUtils.cpp