Compute Library: NEActivationLayer Class Reference
NEActivationLayer Class Reference
Basic function to run cpu::kernels::CpuActivationKernel.
#include <NEActivationLayer.h>
Public Member Functions
NEActivationLayer (IRuntimeContext *ctx=nullptr)
Constructor.
NEActivationLayer (const NEActivationLayer &)=delete
Prevent instances of this class from being copied (As this class contains pointers)
NEActivationLayer (NEActivationLayer &&)
Default move constructor.
NEActivationLayer & operator= (const NEActivationLayer &)=delete
Prevent instances of this class from being copied (As this class contains pointers)
NEActivationLayer & operator= (NEActivationLayer &&)
Default move assignment operator.
~NEActivationLayer ()
Destructor.
void configure (ITensor *input, ITensor *output, ActivationLayerInfo activation_info)
[NEActivationLayer snippet]
void run () override
Run the kernels contained in the function.
Public Member Functions inherited from IFunction
virtual ~IFunction ()=default
Destructor.
virtual void prepare ()
Prepare the function for executing.
Static Public Member Functions
static Status validate (const ITensorInfo *input, const ITensorInfo *output, const ActivationLayerInfo &act_info)
[NEActivationLayer snippet]
Detailed Description
Basic function to run cpu::kernels::CpuActivationKernel.
Note
The function simulates an activation layer with the specified activation function.
Definition at line 44 of file NEActivationLayer.h.
Constructor & Destructor Documentation
NEActivationLayer() [1/3]
NEActivationLayer (IRuntimeContext * ctx = nullptr)
Constructor.
Parameters
[in] ctx Runtime context to be used by the function
Definition at line 39 of file NEActivationLayer.cpp.
References NEActivationLayer::operator=(), and NEActivationLayer::~NEActivationLayer().
     : _impl(std::make_unique<Impl>())
 {
     _impl->ctx = ctx;
 }
NEActivationLayer() [2/3]
NEActivationLayer (const NEActivationLayer &) delete
Prevent instances of this class from being copied (As this class contains pointers)
NEActivationLayer() [3/3]
NEActivationLayer (NEActivationLayer &&) default
Default move constructor.
~NEActivationLayer()
~NEActivationLayer () default
Destructor.
Referenced by NEActivationLayer::NEActivationLayer().
Member Function Documentation
configure()
void configure (ITensor * input, ITensor * output, ActivationLayerInfo activation_info)
[NEActivationLayer snippet]
Set the input and output tensor.
Valid data layouts:
All
Valid data type configurations:
src dst
QASYMM8 QASYMM8
QASYMM8_SIGNED QASYMM8_SIGNED
QSYMM16 QSYMM16
F16 F16
F32 F32
Note
If the output tensor is a nullptr or is equal to the input, the activation function will be performed in-place
Parameters
[in,out] input Source tensor. In case of output tensor = nullptr, this tensor will store the result of the activation function. Data types supported: QASYMM8/QASYMM8_SIGNED/QSYMM16/F16/F32.
[out] output Destination tensor. Data type supported: same as input
[in] activation_info Activation layer parameters.
Definition at line 48 of file NEActivationLayer.cpp.
References ARM_COMPUTE_ERROR_ON_NULLPTR, and arm_compute::test::validation::input.
Referenced by NERNNLayer::configure(), NEFFTConvolutionLayer::configure(), NELSTMLayerQuantized::configure(), NELSTMLayer::configure(), NEQLSTMLayer::configure(), and arm_compute::test::validation::TEST_CASE().
 {
     _impl->src = input;
     _impl->dst = output == nullptr ? input : output;
     ARM_COMPUTE_ERROR_ON_NULLPTR(_impl->src, _impl->dst);
     _impl->op = std::make_unique<cpu::CpuActivation>();
     _impl->op->configure(_impl->src->info(), _impl->dst->info(), activation_info);
 }
operator=() [1/2]
NEActivationLayer& operator= (const NEActivationLayer &) delete
Prevent instances of this class from being copied (As this class contains pointers)
Referenced by NEActivationLayer::NEActivationLayer().
operator=() [2/2]
NEActivationLayer & operator= (NEActivationLayer &&) default
Default move assignment operator.
run()
void run () override virtual
Run the kernels contained in the function.
For CPU kernels:
Multi-threading is used for the kernels which are parallelisable.
By default std::thread::hardware_concurrency() threads are used.
Note
CPPScheduler::set_num_threads() can be used to manually set the number of threads
For OpenCL kernels:
All the kernels are enqueued on the queue associated with CLScheduler.
The queue is then flushed.
Note
The function will not block until the kernels are executed. It is the user's responsibility to wait.
Will call prepare() on first run if hasn't been done
Implements IFunction.
Definition at line 64 of file NEActivationLayer.cpp.
References arm_compute::ACL_DST, arm_compute::ACL_SRC, ITensorPack::add_tensor(), and arm_compute::test::validation::pack.
Referenced by NERNNLayer::run(), NEFFTConvolutionLayer::run(), NELSTMLayerQuantized::run(), NELSTMLayer::run(), NEQLSTMLayer::run(), and arm_compute::test::validation::TEST_CASE().
 {
     ITensorPack pack;
     pack.add_tensor(TensorType::ACL_SRC, _impl->src);
     pack.add_tensor(TensorType::ACL_DST, _impl->dst);
     _impl->op->run(pack);
 }
validate()
Status validate (const ITensorInfo * input, const ITensorInfo * output, const ActivationLayerInfo & act_info) static
[NEActivationLayer snippet]
Static function to check if given info will lead to a valid configuration of NEActivationLayer
Parameters
[in] input Source tensor info. In case of output tensor info = nullptr, this tensor will store the result of the activation function. Data types supported: QASYMM8/QASYMM8_SIGNED/QSYMM16/F16/F32.
[in] output Destination tensor info. Data type supported: same as input
[in] act_info Activation layer information.
Returns
a status
Definition at line 59 of file NEActivationLayer.cpp.
References CpuActivation::validate().
Referenced by arm_compute::test::validation::DATA_TEST_CASE(), NERNNLayer::validate(), NEFFTConvolutionLayer::validate(), NELSTMLayerQuantized::validate(), NELSTMLayer::validate(), and NEQLSTMLayer::validate().
 {
     return cpu::CpuActivation::validate(input, output, act_info);
 }
The documentation for this class was generated from the following files:
arm_compute/runtime/NEON/functions/NEActivationLayer.h
src/runtime/NEON/functions/NEActivationLayer.cpp