Compute Library: CpuElementwiseBase Class Reference
CpuElementwiseBase Class Reference
#include <CpuElementwise.h>
Public Member Functions
void run (ITensorPack &tensors) override
Run the kernels contained in the function.
Public Member Functions inherited from INEOperator
INEOperator (IRuntimeContext *ctx=nullptr)
Constructor.
INEOperator (const INEOperator &)=delete
Prevent instances of this class from being copied (As this class contains pointers)
INEOperator (INEOperator &&)=default
Default move constructor.
INEOperator & operator= (const INEOperator &)=delete
Prevent instances of this class from being copied (As this class contains pointers)
INEOperator & operator= (INEOperator &&)=default
Default move assignment operator.
~INEOperator ()
Default destructor.
void prepare (ITensorPack &constants) override
Prepare the function for executing.
MemoryRequirements workspace () const override
Return the memory requirements required by the workspace.
Public Member Functions inherited from IOperator
virtual ~IOperator ()=default
Destructor.
Detailed Description
Definition at line 33 of file CpuElementwise.h.
Member Function Documentation
run()
void run (ITensorPack & tensors) override virtual
Run the kernels contained in the function.
Parameters
[in] tensors Vector that contains the tensors to operate on.
Reimplemented from INEOperator.
Definition at line 33 of file CpuElementwise.cpp.
References arm_compute::ACL_SRC_0, arm_compute::ACL_SRC_1, ITensorPack::get_const_tensor(), ITensor::info(), and INEOperator::run().
 {
     // If the kernel has been configured, use the window from the kernel.
     if(_kernel->is_window_configured())
     {
         ICpuOperator::run(tensors);
         return;
     }
     auto src0_info        = tensors.get_const_tensor(TensorType::ACL_SRC_0)->info();
     auto src1_info        = tensors.get_const_tensor(TensorType::ACL_SRC_1)->info();
     auto shape_and_window = compute_output_shape_and_window(src0_info->tensor_shape(), src1_info->tensor_shape());
     ICpuOperator::run(tensors, shape_and_window.second);
 }
The documentation for this class was generated from the following files:
src/cpu/operators/CpuElementwise.h
src/cpu/operators/CpuElementwise.cpp