Compute Library: CpuScaleKernel Class Reference
CpuScaleKernel Class Reference
Arm(R) Neon(TM) kernel to perform scaling on a tensor.
#include <CpuScaleKernel.h>
Data Structures
struct ScaleKernel
Public Member Functions
CpuScaleKernel ()=default
ARM_COMPUTE_DISALLOW_COPY_ALLOW_MOVE (CpuScaleKernel)
void configure (const ITensorInfo *src, const ITensorInfo *dx, const ITensorInfo *dy, const ITensorInfo *offsets, ITensorInfo *dst, const ScaleKernelInfo &info)
Initialise the kernel's inputs, output and interpolation policy.
void run_op (ITensorPack &tensors, const Window &window, const ThreadInfo &info) override
Execute the kernel on the passed window.
const char * name () const override
Name of the kernel.
Public Member Functions inherited from ICPPKernel
virtual ~ICPPKernel ()=default
Default destructor.
virtual void run (const Window &window, const ThreadInfo &info)
Execute the kernel on the passed window.
virtual void run_nd (const Window &window, const ThreadInfo &info, const Window &thread_locator)
legacy compatibility layer for implemantions which do not support thread_locator In these cases we simply narrow the interface down the legacy version
virtual size_t get_mws (const CPUInfo &platform, size_t thread_count) const
Return minimum workload size of the relevant kernel.
Public Member Functions inherited from IKernel
IKernel ()
Constructor.
virtual ~IKernel ()=default
Destructor.
virtual bool is_parallelisable () const
Indicates whether or not the kernel is parallelisable.
virtual BorderSize border_size () const
The size of the border for that kernel.
const Window & window () const
The maximum window the kernel can be executed on.
bool is_window_configured () const
Function to check if the embedded window of this kernel has been configured.
Static Public Member Functions
static Status validate (const ITensorInfo *src, const ITensorInfo *dx, const ITensorInfo *dy, const ITensorInfo *offsets, ITensorInfo *dst, const ScaleKernelInfo &info)
Static function to check if given info will lead to a valid configuration.
static const std::vector< ScaleKernel > & get_available_kernels ()
Static Public Member Functions inherited from ICpuKernel< CpuScaleKernel >
static const auto * get_implementation (const SelectorType &selector, KernelSelectionType selection_type=KernelSelectionType::Supported)
Micro-kernel selector.
Additional Inherited Members
Static Public Attributes inherited from ICPPKernel
static constexpr size_t default_mws = 1
Detailed Description
Arm(R) Neon(TM) kernel to perform scaling on a tensor.
Definition at line 38 of file CpuScaleKernel.h.
Constructor & Destructor Documentation
CpuScaleKernel()
CpuScaleKernel () default
Member Function Documentation
ARM_COMPUTE_DISALLOW_COPY_ALLOW_MOVE()
ARM_COMPUTE_DISALLOW_COPY_ALLOW_MOVE (CpuScaleKernel)
configure()
void configure (const ITensorInfo * src, const ITensorInfo * dx, const ITensorInfo * dy, const ITensorInfo * offsets, ITensorInfo * dst, const ScaleKernelInfo & info)
Initialise the kernel's inputs, output and interpolation policy.
Note
dx, dy and offsets have the same dimensions (width and height) of the output tensor
Using policy Area only supports data layout NCHW and input data type U8.
Using S8 data type only supports NHWC, border_mode Replicate, and policy Bilinear
Parameters
[in] src Source tensor info. Data types supported: QASYMM8/QASYMM8_SIGNED/U8/S8/S16/F16/F32.
[in] dx Distance x tensor info. Pixel's distance between the X real coordinate and the smallest X following integer. Data type supported: F32
[in] dy Distance y tensor info. Pixel's distance between the Y real coordinate and the smallest Y following integer. Data type supported: F32
[in] offsets Offset tensor info. Offset to access the pixel with NEAREST interpolation or the top-left pixel with BILINEAR interpolation in the input tensor. Data type supported: S32.
[out] dst Destination tensor info. Data types supported: Same as input. All but the lowest two dimensions must be the same size as in the input tensor, i.e. scaling is only performed within the XY-plane.
[in] info ScaleKernelInfo to use for configuration
Definition at line 185 of file CpuScaleKernel.cpp.
References ScaleKernelInfo::align_corners, arm_compute::AREA, ARM_COMPUTE_ERROR, ARM_COMPUTE_ERROR_ON_DATA_TYPE_CHANNEL_NOT_IN, ARM_COMPUTE_ERROR_ON_NULLPTR, ARM_COMPUTE_ERROR_THROW_ON, ARM_COMPUTE_UNUSED, ScaleKernelInfo::border_mode, arm_compute::calculate_max_window(), arm_compute::scale_utils::calculate_resize_ratio(), arm_compute::CENTER, arm_compute::CONSTANT, ScaleKernelInfo::constant_border_value, ScaleKernelInfo::data_layout, ITensorInfo::data_layout(), ITensorInfo::data_type(), arm_compute::scale_helpers::delta_bilinear(), Qasymm8QuantizationHelper< QUANTIZED_TYPE >::dequantize(), ITensorInfo::dimension(), Window::DimX, Window::DimY, Window::DimZ, arm_compute::execute_window_loop(), CPUInfo::get(), PixelValue::get(), arm_compute::get_data_layout_dimension_index(), ICpuKernel< CpuScaleKernel >::get_implementation(), CPUInfo::get_isa(), arm_compute::HEIGHT, arm_compute::test::validation::idx_height, arm_compute::test::validation::idx_width, ITensor::info(), ScaleKernelInfo::interpolation_policy, BorderSize::left, arm_compute::NCHW, arm_compute::NEAREST_NEIGHBOR, ITensorInfo::num_dimensions(), ITensorInfo::padding(), arm_compute::scale_helpers::pixel_area_c1u8_clamp(), Iterator::ptr(), ITensor::ptr_to_element(), ITensorInfo::quantization_info(), arm_compute::REPLICATE, BorderSize::right, arm_compute::utils::rounding::round_half_away_from_zero(), ScaleKernelInfo::sampling_policy, scale_bilinear_nchw(), Window::set(), ITensorInfo::strides_in_bytes(), arm_compute::string_from_data_layout(), arm_compute::string_from_data_type(), arm_compute::string_from_interpolation_policy(), type, arm_compute::U8, arm_compute::UNDEFINED, QuantizationInfo::uniform(), arm_compute::UNKNOWN, arm_compute::cpu::kernels::validate_arguments(), arm_compute::test::validation::w, arm_compute::WIDTH, IKernel::window(), Window::x(), and Window::y().
 {
     ARM_COMPUTE_UNUSED(dx, dy, offsets);
     ARM_COMPUTE_ERROR_ON_NULLPTR(src, dst);
     // Perform validation step
     ARM_COMPUTE_ERROR_THROW_ON(validate_arguments(src,
                                                   dx,
                                                   dy,
                                                   offsets,
                                                   dst,
                                                   info));
     const auto *uk = CpuScaleKernel::get_implementation(ScaleKernelDataTypeISASelectorData{ src->data_type(), CPUInfo::get().get_isa(), info.interpolation_policy });
     ARM_COMPUTE_ERROR_ON_NULLPTR(uk);
     _run_method = uk->ukernel;
     _name       = std::string("CpuScaleKernel").append("/").append(uk->name).append("_").append(string_from_interpolation_policy(info.interpolation_policy));
     // Get data layout and width/height indices
     _data_layout         = info.data_layout == DataLayout::UNKNOWN ? src->data_layout() : info.data_layout;
     const int idx_width  = get_data_layout_dimension_index(_data_layout, DataLayoutDimension::WIDTH);
     const int idx_height = get_data_layout_dimension_index(_data_layout, DataLayoutDimension::HEIGHT);
     _policy                = info.interpolation_policy;
     _border_mode           = info.border_mode;
     _constant_border_value = info.constant_border_value;
     _align_corners         = info.align_corners;
     if(info.sampling_policy == SamplingPolicy::CENTER)
     {
         _sampling_offset = 0.5f;
     }
     // Compute the ratio between source width/height and destination width/height
     const auto wr = scale_utils::calculate_resize_ratio(src->dimension(idx_width), dst->dimension(idx_width), _align_corners);
     const auto hr = scale_utils::calculate_resize_ratio(src->dimension(idx_height), dst->dimension(idx_height), _align_corners);
     // Area interpolation behaves as Nearest Neighbour in case of up-sampling
     _policy = (_policy == InterpolationPolicy::AREA && wr <= 1.f && hr <= 1.f) ? InterpolationPolicy::NEAREST_NEIGHBOR : _policy;
     if(_border_mode == BorderMode::UNDEFINED)
     {
         _border_mode           = BorderMode::CONSTANT;
         _constant_border_value = PixelValue();
     }
 #ifdef ENABLE_NCHW_KERNELS
     // Configure scale function to run
     if(_data_layout == DataLayout::NCHW)
     {
         std::string function_to_call("scale_");
         function_to_call += string_from_data_type(src->data_type()) + "_";
         function_to_call += string_from_data_layout(_data_layout) + "_";
         function_to_call += string_from_interpolation_policy(_policy);
         static std::map<std::string, ScaleFunctionPtr> map_function =
         {
             { "scale_U8_NCHW_AREA_CONSTANT", &CpuScaleKernel::scale_area_nchw_u8 },
             { "scale_U8_NCHW_BILINEAR", &CpuScaleKernel::scale_bilinear_nchw<uint8_t> },
             { "scale_U8_NCHW_NEAREST_NEIGHBOUR", &CpuScaleKernel::scale_nearest_nchw<uint8_t> },
             { "scale_QASYMM8_NCHW_BILINEAR", &CpuScaleKernel::scale_bilinear_qasymm<uint8_t> },
             { "scale_QASYMM8_NCHW_NEAREST_NEIGHBOUR", &CpuScaleKernel::scale_nearest_nchw<uint8_t> },
             { "scale_QASYMM8_SIGNED_NCHW_BILINEAR", &CpuScaleKernel::scale_bilinear_qasymm<int8_t> },
             { "scale_QASYMM8_SIGNED_NCHW_NEAREST_NEIGHBOUR", &CpuScaleKernel::scale_nearest_nchw<int8_t> },
             { "scale_S16_NCHW_BILINEAR", &CpuScaleKernel::scale_bilinear_nchw<int16_t> },
             { "scale_S16_NCHW_NEAREST_NEIGHBOUR", &CpuScaleKernel::scale_nearest_nchw<int16_t> },
 #ifdef __ARM_FEATURE_FP16_VECTOR_ARITHMETIC
             { "scale_F16_NCHW_BILINEAR", &CpuScaleKernel::scale_bilinear_nchw<float16_t> },
             { "scale_F16_NCHW_NEAREST_NEIGHBOUR", &CpuScaleKernel::scale_nearest_nchw<float16_t> },
 #endif /* __ARM_FEATURE_FP16_VECTOR_ARITHMETIC */
             { "scale_F32_NCHW_BILINEAR", &CpuScaleKernel::scale_bilinear_nchw<float> },
             { "scale_F32_NCHW_NEAREST_NEIGHBOUR", &CpuScaleKernel::scale_nearest_nchw<float> },
         };
         auto it = map_function.find(function_to_call);
         if(it != map_function.end())
         {
             _func = it->second;
         }
     }
 #endif // ENABLE_NCHW_KERNELS
     // Configure window
     Window win = calculate_max_window(*dst, Steps());
     ICpuKernel::configure(win);
 }
get_available_kernels()
const std::vector< CpuScaleKernel::ScaleKernel > & get_available_kernels () static
Definition at line 605 of file CpuScaleKernel.cpp.
 {
     return available_kernels;
 }
name()
const char * name () const override virtual
Name of the kernel.
Returns
Kernel name
Implements ICPPKernel.
Definition at line 600 of file CpuScaleKernel.cpp.
 {
     return _name.c_str();
 }
run_op()
void run_op (ITensorPack & tensors, const Window & window, const ThreadInfo & info) override virtual
Execute the kernel on the passed window.
Warning
If is_parallelisable() returns false then the passed window must be equal to window()
Note
The window has to be a region within the window returned by the window() method
The width of the window has to be a multiple of num_elems_processed_per_iteration().
Parameters
[in] tensors A vector containing the tensors to operate on.
[in] window Region on which to execute the kernel. (Must be a region of the window returned by window())
[in] info Info about executing thread and CPU.
Reimplemented from ICPPKernel.
Definition at line 576 of file CpuScaleKernel.cpp.
References arm_compute::ACL_DST, arm_compute::ACL_INT_0, arm_compute::ACL_INT_1, arm_compute::ACL_INT_2, arm_compute::ACL_SRC, ARM_COMPUTE_ERROR_ON, ARM_COMPUTE_ERROR_ON_INVALID_SUBWINDOW, ARM_COMPUTE_ERROR_ON_UNCONFIGURED_KERNEL, ARM_COMPUTE_UNUSED, ITensorPack::get_const_tensor(), ITensorPack::get_tensor(), arm_compute::NCHW, arm_compute::NHWC, and IKernel::window().
 {
     ARM_COMPUTE_UNUSED(info);
     ARM_COMPUTE_ERROR_ON_UNCONFIGURED_KERNEL(this);
     ARM_COMPUTE_ERROR_ON_INVALID_SUBWINDOW(ICpuKernel::window(), window);
     ARM_COMPUTE_ERROR_ON(_func == nullptr && _data_layout == DataLayout::NCHW);
     ARM_COMPUTE_ERROR_ON(_run_method == nullptr && _data_layout == DataLayout::NHWC);
     const auto src     = tensors.get_const_tensor(TensorType::ACL_SRC);
     auto       dst     = tensors.get_tensor(TensorType::ACL_DST);
     const auto dx      = tensors.get_const_tensor(TensorType::ACL_INT_0);
     const auto dy      = tensors.get_const_tensor(TensorType::ACL_INT_1);
     const auto offsets = tensors.get_const_tensor(TensorType::ACL_INT_2);
     if(_data_layout == DataLayout::NCHW)
     {
         (this->*_func)(src, dst, dx, dy, offsets, window);
     }
     else
     {
         _run_method(src, dst, offsets, dx, dy, _policy, _border_mode, _constant_border_value, _sampling_offset, _align_corners, window);
     }
 }
validate()
Status validate (const ITensorInfo * src, const ITensorInfo * dx, const ITensorInfo * dy, const ITensorInfo * offsets, ITensorInfo * dst, const ScaleKernelInfo & info) static
Static function to check if given info will lead to a valid configuration.
Similar to CpuScaleKernel::configure()
Returns
a status
Definition at line 569 of file CpuScaleKernel.cpp.
References ARM_COMPUTE_RETURN_ON_ERROR, and arm_compute::cpu::kernels::validate_arguments().
Referenced by CpuScale::validate().
 {
     ARM_COMPUTE_RETURN_ON_ERROR(validate_arguments(input, dx, dy, offsets, output, info));
     return Status{};
 }
The documentation for this class was generated from the following files:
src/cpu/kernels/CpuScaleKernel.h
src/cpu/kernels/CpuScaleKernel.cpp