Compute Library: GpuDepthwiseConv2d Class Reference
GpuDepthwiseConv2d Class Reference final
Operator interface.
#include <GpuDepthwiseConv2d.h>
Public Types
using Attributes = DepthwiseConv2dAttributes
Attributes are a set of backend-agnostic parameters that define what an operator does.
Static Public Member Functions
static ITensorInfo * create_op (GpuWorkloadSketch &sketch, ITensorInfo *src, ITensorInfo *wei, ITensorInfo *bia, const Attributes &attributes)
Create an operator and fuse it into the workload sketch.
static Status is_supported_op (const GpuWorkloadContext &context, const ITensorInfo *src, const ITensorInfo *wei, const ITensorInfo *bia, const Attributes &attributes)
Check if the operator configuration is supported, irrespective of fusion.
static Status validate_op (const GpuWorkloadSketch &sketch, const ITensorInfo *src, const ITensorInfo *wei, const ITensorInfo *bia, const Attributes &attributes)
Check if the operator configuration is supported and if it can be fused into the workload sketch.
Detailed Description
Operator interface.
Definition at line 40 of file GpuDepthwiseConv2d.h.
Member Typedef Documentation
Attributes
using Attributes = DepthwiseConv2dAttributes
Attributes are a set of backend-agnostic parameters that define what an operator does.
Definition at line 44 of file GpuDepthwiseConv2d.h.
Member Function Documentation
create_op()
ITensorInfo * create_op (GpuWorkloadSketch & sketch, ITensorInfo * src, ITensorInfo * wei, ITensorInfo * bia, const Attributes & attributes) static
Create an operator and fuse it into the workload sketch.
Note
If validate_op() fails, the creation also fails and may throw an error.
If validate_op() fails, sketch remains unchanged and valid.
Valid data type configurations:
src wei bia dst
F16 F16 F16 F16
F32 F32 F32 F32
Valid data layouts:
NHWC
Parameters
[in,out] sketch Workload sketch into which the operator will be fused
[in] src Source tensor
[in] wei Weight tensor
[in] bia (Optional) Bias tensor
[in] attributes Operator attributes
Returns
Pointer for the destination tensor info
Definition at line 186 of file GpuDepthwiseConv2d.cpp.
References arm_compute::ACL_DST_0, arm_compute::ACL_SRC_0, arm_compute::ACL_SRC_1, arm_compute::ACL_SRC_2, ArgumentPack< T >::add_const_tensor(), GpuKernelComponentGraph::add_new_component(), GpuOperatorGroup::add_operator(), ARM_COMPUTE_ERROR, ARM_COMPUTE_ERROR_ON_NULLPTR, ARM_COMPUTE_ERROR_THROW_ON, ARM_COMPUTE_LOG_PARAMS, GpuWorkloadSketch::Implementation::component_graph(), GpuWorkloadSketch::Implementation::context(), ClDWCNativeKernelConfigurationFactory::create(), GpuWorkloadSketch::Implementation::create_virtual_tensor(), DepthwiseConv2dAttributes::depth_multiplier(), DepthwiseConv2dAttributes::dilation(), arm_compute::test::validation::dst, DWCComputeKernelInfo::export_input_to_cl_image, DWCComputeKernelInfo::export_weights_to_cl_image, arm_compute::FLOOR, arm_compute::get_arch_from_target(), GpuWorkloadContext::gpu_target(), GpuWorkloadSketch::implementation(), DWCComputeKernelInfo::m0, arm_compute::MIDGARD, DWCComputeKernelInfo::n0, GpuOperatorGroup::new_operator(), arm_compute::experimental::dynamic_fusion::OpenCL, GpuWorkloadSketch::Implementation::operator_group(), DepthwiseConv2dAttributes::pad(), UnitWorkloadStage::Run, KernelProperties::stage(), DepthwiseConv2dAttributes::stride(), arm_compute::opencl::kernels::gemm::update_padding_for_cl_image(), and GpuDepthwiseConv2d::validate_op().
 {
     ARM_COMPUTE_ERROR_ON_NULLPTR(src, wei);
     ARM_COMPUTE_LOG_PARAMS(src, wei, bia, attributes);
     ARM_COMPUTE_ERROR_THROW_ON(GpuDepthwiseConv2d::validate_op(sketch, src, wei, bia, attributes));
     ITensorInfo *dst = sketch.implementation().create_virtual_tensor();
     ARM_COMPUTE_ERROR_ON_NULLPTR(dst);
     calculate_and_init_dst_if_empty(dst, src, wei, attributes);
     // Translate into components and add to component graph
     GpuKernelComponentGraph &comp_graph = sketch.implementation().component_graph();
     const auto              *sketch_ctx = sketch.implementation().context();
     const GpuTarget          gpu_target = sketch_ctx->gpu_target();
     if(sketch_ctx->gpu_language() == GpuLanguage::OpenCL)
     {
         ARM_COMPUTE_ERROR_ON_NULLPTR(sketch_ctx->cl_compile_context());
         // Add Depthwise Conv2d Component
         {
             const auto properties = IGpuKernelComponent::Properties().stage(UnitWorkloadStage{ UnitWorkloadStage::Stage::Run });
             auto       settings   = ClComponentDepthwiseConv2d::Settings();
             const PadStrideInfo legacy_conv_info(attributes.stride().x(), attributes.stride().y(), attributes.pad().left,
                                                  attributes.pad().right,
                                                  attributes.pad().top, attributes.pad().bottom, DimensionRoundingType::FLOOR);
             // Get the depthwise convolution compute parameters
             auto                       t        = arm_compute::cl_dwc::ClDWCNativeKernelConfigurationFactory::create(gpu_target);
             const DWCComputeKernelInfo dwc_info = t->configure(src, wei, legacy_conv_info, attributes.dilation(), attributes.depth_multiplier());
             settings.is_fma_available(get_arch_from_target(gpu_target) != GPUTarget::MIDGARD)
             .m0(dwc_info.m0)
             .n0(dwc_info.n0)
             .export_input_to_cl_image(dwc_info.export_input_to_cl_image)
             .export_weights_to_cl_image(dwc_info.export_weights_to_cl_image);
             if(settings.export_input_to_cl_image())
             {
                 arm_compute::opencl::kernels::gemm::update_padding_for_cl_image(src);
             }
             if(settings.export_weights_to_cl_image())
             {
                 arm_compute::opencl::kernels::gemm::update_padding_for_cl_image(wei);
             }
             ArgumentPack<ITensorInfo> arguments;
             arguments.add_const_tensor(ACL_SRC_0, src);
             arguments.add_const_tensor(ACL_SRC_1, wei);
             arguments.add_const_tensor(ACL_SRC_2, bia);
             arguments.add_const_tensor(ACL_DST_0, dst);
             comp_graph.add_new_component<ClComponentDepthwiseConv2d>(properties, arguments, attributes, settings);
         }
     }
     else
     {
         ARM_COMPUTE_ERROR("Unimplemented Gpu language");
     }
     // Set up fusion test by adding to the Operator Group
     // Note this has to be performed after all the components have been successfully added to the component graph
     // Pack tensor infos
     ArgumentPack<ITensorInfo> tensors;
     tensors.add_const_tensor(ACL_SRC_0, src);
     tensors.add_const_tensor(ACL_SRC_1, wei);
     tensors.add_const_tensor(ACL_SRC_2, bia);
     tensors.add_const_tensor(ACL_DST_0, dst);
     const Operator op = sketch.implementation().operator_group().new_operator(operator_type, tensors);
     sketch.implementation().operator_group().add_operator(op);
     return dst;
 }
is_supported_op()
Status is_supported_op (const GpuWorkloadContext & context, const ITensorInfo * src, const ITensorInfo * wei, const ITensorInfo * bia, const Attributes & attributes) static
Check if the operator configuration is supported, irrespective of fusion.
Parameters
[in] context Workload context within which the operator is running
[in] src Source tensor
[in] wei Weight tensor
[in] bia (Optional) Bias tensor
[in] attributes Operator attributes
Returns
Status
Definition at line 141 of file GpuDepthwiseConv2d.cpp.
 {
     return is_supported_op_helper(context, src, wei, bia, nullptr, attributes);
 }
validate_op()
Status validate_op (const GpuWorkloadSketch & sketch, const ITensorInfo * src, const ITensorInfo * wei, const ITensorInfo * bia, const Attributes & attributes) static
Check if the operator configuration is supported and if it can be fused into the workload sketch.
Parameters are similar to GpuDepthwiseConv2d::create_op()
Returns
Status
Definition at line 150 of file GpuDepthwiseConv2d.cpp.
References arm_compute::ACL_DST_0, arm_compute::ACL_SRC_0, arm_compute::ACL_SRC_1, arm_compute::ACL_SRC_2, ArgumentPack< T >::add_const_tensor(), ARM_COMPUTE_RETURN_ERROR_ON, ARM_COMPUTE_RETURN_ERROR_ON_MSG, ARM_COMPUTE_RETURN_ERROR_ON_NULLPTR, GpuWorkloadSketch::gpu_context(), ITensorInfo::has_valid_id(), GpuWorkloadSketch::implementation(), GpuOperatorGroup::new_operator(), GpuWorkloadSketch::Implementation::operator_group(), arm_compute::test::validation::src, and GpuOperatorGroup::try_add_operator().
Referenced by GpuDepthwiseConv2d::create_op().
 {
     ARM_COMPUTE_RETURN_ERROR_ON_NULLPTR(src, wei);
     ARM_COMPUTE_RETURN_ERROR_ON(!src->has_valid_id() || !wei->has_valid_id());
     if(bia != nullptr)
     {
         ARM_COMPUTE_RETURN_ERROR_ON(!bia->has_valid_id());
     }
     // Refer to GpuConv2d::validate_op() for id-validness of this TensorInfo object
     TensorInfo dst_info_to_validate;
     // Auto initialize dst tensor info
     calculate_and_init_dst_if_empty(&dst_info_to_validate, src, wei, attributes);
     // Perform fusion test
     // Pack tensor infos
     ArgumentPack<ITensorInfo> tensors;
     tensors.add_const_tensor(ACL_SRC_0, src);
     tensors.add_const_tensor(ACL_SRC_1, wei);
     tensors.add_const_tensor(ACL_SRC_2, bia);
     tensors.add_const_tensor(ACL_DST_0, &dst_info_to_validate);
     const Operator op = sketch.implementation().operator_group().new_operator(operator_type, tensors);
     ARM_COMPUTE_RETURN_ERROR_ON_MSG(!sketch.implementation().operator_group().try_add_operator(op),
                                     "Operator fusion test failed. This operator cannot be fused into the workload");
     // Check if configuration is supported
     return is_supported_op_helper(*sketch.gpu_context(), src, wei, bia, &dst_info_to_validate, attributes);
 }
The documentation for this class was generated from the following files:
arm_compute/dynamic_fusion/sketch/gpu/operators/GpuDepthwiseConv2d.h
src/dynamic_fusion/sketch/gpu/operators/GpuDepthwiseConv2d.cpp