Compute Library: NEArithmeticAddition Class Reference
NEArithmeticAddition Class Reference
Basic function to run cpu::kernels::CpuAddKernel.
#include <NEArithmeticAddition.h>
Public Member Functions
NEArithmeticAddition ()
Default Constructor.
~NEArithmeticAddition ()
Default Destructor.
NEArithmeticAddition (const NEArithmeticAddition &)=delete
Prevent instances of this class from being copied (As this class contains pointers)
NEArithmeticAddition (NEArithmeticAddition &&)
Default move constructor.
NEArithmeticAddition & operator= (const NEArithmeticAddition &)=delete
Prevent instances of this class from being copied (As this class contains pointers)
NEArithmeticAddition & operator= (NEArithmeticAddition &&)
Default move assignment operator.
void configure (const ITensor *input1, const ITensor *input2, ITensor *output, ConvertPolicy policy, const ActivationLayerInfo &act_info=ActivationLayerInfo())
Initialise the kernel's inputs, output and conversion policy.
void run () override
Run the kernels contained in the function.
Public Member Functions inherited from IFunction
virtual ~IFunction ()=default
Destructor.
virtual void prepare ()
Prepare the function for executing.
Static Public Member Functions
static Status validate (const ITensorInfo *input1, const ITensorInfo *input2, const ITensorInfo *output, ConvertPolicy policy, const ActivationLayerInfo &act_info=ActivationLayerInfo())
Static function to check if given info will lead to a valid configuration of NEArithmeticAddition.
Detailed Description
Basic function to run cpu::kernels::CpuAddKernel.
Definition at line 37 of file NEArithmeticAddition.h.
Constructor & Destructor Documentation
NEArithmeticAddition() [1/3]
NEArithmeticAddition ()
Default Constructor.
Definition at line 41 of file NEArithmeticAddition.cpp.
References NEArithmeticAddition::operator=(), and NEArithmeticAddition::~NEArithmeticAddition().
     : _impl(std::make_unique<Impl>())
 {
 }
~NEArithmeticAddition()
~NEArithmeticAddition () default
Default Destructor.
Referenced by NEArithmeticAddition::NEArithmeticAddition().
NEArithmeticAddition() [2/3]
NEArithmeticAddition (const NEArithmeticAddition &) delete
Prevent instances of this class from being copied (As this class contains pointers)
NEArithmeticAddition() [3/3]
NEArithmeticAddition (NEArithmeticAddition &&) default
Default move constructor.
Member Function Documentation
configure()
void configure (const ITensor * input1, const ITensor * input2, ITensor * output, ConvertPolicy policy, const ActivationLayerInfo & act_info = ActivationLayerInfo())
Initialise the kernel's inputs, output and conversion policy.
Valid data layouts:
All
Valid data type configurations:
src0 src1 dst
QASYMM8 QASYMM8 QASYMM8
QASYMM8_SIGNED QASYMM8_SIGNED QASYMM8_SIGNED
QSYMM16 QSYMM16 QASYMM16
QSYMM16 QSYMM16 S32
U8 U8 U8
S16 S16 S16
S32 S32 S32
F16 F16 F16
F32 F32 F32
Parameters
[in] input1 First tensor input. Data types supported: U8/QASYMM8/QASYMM8_SIGNED/S16/QSYMM16/F16/S32/F32
[in] input2 Second tensor input. Data types supported: U8/QASYMM8/QASYMM8_SIGNED/S16/QSYMM16/F16/S32/F32
[out] output Output tensor. Data types supported: U8/QASYMM8/QASYMM8_SIGNED/S16/QSYMM16/F16/S32/F32
[in] policy Policy to use to handle overflow.
[in] act_info (Optional) Activation layer information in case of a fused activation. Currently not supported.
Definition at line 54 of file NEArithmeticAddition.cpp.
References arm_compute::test::validation::act_info.
Referenced by NERNNLayer::configure(), NEFFTConvolutionLayer::configure(), NELSTMLayerQuantized::configure(), NELSTMLayer::configure(), NEQLSTMLayer::configure(), and arm_compute::test::validation::TEST_CASE().
 {
     _impl->src_0 = input1;
     _impl->src_1 = input2;
     _impl->dst   = output;
     _impl->op    = std::make_unique<cpu::CpuAdd>();
     _impl->op->configure(_impl->src_0->info(), _impl->src_1->info(), _impl->dst->info(), policy, act_info);
 }
operator=() [1/2]
NEArithmeticAddition& operator= (const NEArithmeticAddition &) delete
Prevent instances of this class from being copied (As this class contains pointers)
Referenced by NEArithmeticAddition::NEArithmeticAddition().
operator=() [2/2]
NEArithmeticAddition & operator= (NEArithmeticAddition &&) default
Default move assignment operator.
run()
void run () override virtual
Run the kernels contained in the function.
For CPU kernels:
Multi-threading is used for the kernels which are parallelisable.
By default std::thread::hardware_concurrency() threads are used.
Note
CPPScheduler::set_num_threads() can be used to manually set the number of threads
For OpenCL kernels:
All the kernels are enqueued on the queue associated with CLScheduler.
The queue is then flushed.
Note
The function will not block until the kernels are executed. It is the user's responsibility to wait.
Will call prepare() on first run if hasn't been done
Implements IFunction.
Definition at line 63 of file NEArithmeticAddition.cpp.
References arm_compute::ACL_DST, arm_compute::ACL_SRC_0, arm_compute::ACL_SRC_1, ITensorPack::add_tensor(), and arm_compute::test::validation::pack.
Referenced by NEQLSTMLayer::prepare(), NERNNLayer::run(), NEFFTConvolutionLayer::run(), NELSTMLayerQuantized::run(), NELSTMLayer::run(), and NEQLSTMLayer::run().
 {
     ITensorPack pack;
     pack.add_tensor(TensorType::ACL_SRC_0, _impl->src_0);
     pack.add_tensor(TensorType::ACL_SRC_1, _impl->src_1);
     pack.add_tensor(TensorType::ACL_DST, _impl->dst);
     _impl->op->run(pack);
 }
validate()
Status validate (const ITensorInfo * input1, const ITensorInfo * input2, const ITensorInfo * output, ConvertPolicy policy, const ActivationLayerInfo & act_info = ActivationLayerInfo()) static
Static function to check if given info will lead to a valid configuration of NEArithmeticAddition.
Parameters
[in] input1 First tensor input info. Data types supported: U8/QASYMM8/QASYMM8_SIGNED/S16/QSYMM16/F16/S32/F32
[in] input2 Second tensor input info. Data types supported: U8/QASYMM8/QASYMM8_SIGNED/S16/QSYMM16/F16/S32/F32
[in] output Output tensor info. Data types supported: U8/SQASYMM8/QASYMM8_SIGNED/S16/QSYMM16/F16/S32/F32
[in] policy Policy to use to handle overflow
[in] act_info (Optional) Activation layer information in case of a fused activation. Currently not supported.
Returns
a status
Definition at line 49 of file NEArithmeticAddition.cpp.
References CpuAdd::validate().
Referenced by arm_compute::test::validation::DATA_TEST_CASE(), NERNNLayer::validate(), NELSTMLayerQuantized::validate(), NELSTMLayer::validate(), and NEQLSTMLayer::validate().
 {
     return cpu::CpuAdd::validate(input1, input2, output, policy, act_info);
 }
The documentation for this class was generated from the following files:
arm_compute/runtime/NEON/functions/NEArithmeticAddition.h
src/runtime/NEON/functions/NEArithmeticAddition.cpp