Compute Library: PReluLayer Class Reference
PReluLayer Class Reference final
PRelu Layer.
#include <Layers.h>
Public Member Functions
PReluLayer (SubStream &&sub_stream0, SubStream &&sub_stream1)
Construct an PRelu operation layer.
NodeID create_layer (IStream &s) override
Create layer and add to the given stream.
Public Member Functions inherited from ILayer
virtual ~ILayer ()=default
Default destructor.
ILayer & set_name (std::string name)
Sets the name of the layer.
const std::string & name () const
Layer name accessor.
Detailed Description
PRelu Layer.
Definition at line 1001 of file Layers.h.
Constructor & Destructor Documentation
PReluLayer()
PReluLayer (SubStream && sub_stream0, SubStream && sub_stream1) inline
Construct an PRelu operation layer.
Parameters
[in] sub_stream0 First graph sub-stream
[in] sub_stream1 First graph sub-stream
Definition at line 1009 of file Layers.h.
         : _ss0(std::move(sub_stream0)), _ss1(std::move(sub_stream1))
     {
     }
Member Function Documentation
create_layer()
NodeID create_layer (IStream & s) inline override virtual
Create layer and add to the given stream.
Parameters
[in] s Stream to add layer to.
Returns
ID of the created node.
Implements ILayer.
Definition at line 1014 of file Layers.h.
References GraphBuilder::add_prelu_node(), IStream::graph(), IStream::hints(), arm_compute::test::validation::input, ILayer::name(), and StreamHints::target_hint.
     {
         NodeParams  common_params = { name(), s.hints().target_hint };
         NodeIdxPair input         = { _ss0.tail_node(), 0 };
         NodeIdxPair alpha         = { _ss1.tail_node(), 0 };
         return GraphBuilder::add_prelu_node(s.graph(), common_params, input, alpha);
     }
The documentation for this class was generated from the following file:
arm_compute/graph/frontend/Layers.h