Compute Library: Size2D Class Reference
Size2D Class Reference
Class for specifying the size of an image or rectangle.
#include <Size2D.h>
Public Member Functions
Size2D ()=default
Default constructor.
Size2D (size_t w, size_t h) noexcept
Constructor.
size_t area () const
The area of the image or rectangle calculated as (width * height)
bool operator== (const Size2D &other) const
bool operator!= (const Size2D &other) const
std::string to_string () const
size_t x () const
Semantic accessor for width as x.
size_t y () const
Semantic accessor for height as y.
Data Fields
size_t width = {}
Width of the image region or rectangle.
size_t height = {}
Height of the image region or rectangle.
Detailed Description
Class for specifying the size of an image or rectangle.
Definition at line 34 of file Size2D.h.
Constructor & Destructor Documentation
Size2D() [1/2]
Size2D () default
Default constructor.
Size2D() [2/2]
Size2D (size_t w, size_t h) inline noexcept
Constructor.
Initializes "width" and "height" respectively with "w" and "h"
Parameters
[in] w Width of the image or rectangle
[in] h Height of the image or rectangle
Definition at line 44 of file Size2D.h.
         : width(w),
           height(h)
     {
     }
Member Function Documentation
area()
size_t area () const inline
The area of the image or rectangle calculated as (width * height)
Returns
Area (width * height)
Definition at line 54 of file Size2D.h.
References Size2D::height, and Size2D::width.
Referenced by arm_compute::misc::shape_calculator::compute_col2im_shape(), arm_compute::misc::shape_calculator::compute_im2col_conv_shape(), arm_compute::misc::shape_calculator::compute_winograd_filter_transform_shape(), arm_compute::misc::shape_calculator::compute_winograd_input_transform_shape(), and arm_compute::test::validation::reference::winograd_filter_transform().
     {
         return (width * height);
     }
operator!=()
bool operator!= (const Size2D & other) const inline
Definition at line 64 of file Size2D.h.
References Size2D::to_string().
     {
         return !(*this == other);
     }
operator==()
bool operator== (const Size2D & other) const inline
Definition at line 59 of file Size2D.h.
References Size2D::height, and Size2D::width.
     {
         return (width == other.width) && (height == other.height);
     }
to_string()
std::string to_string () const
Definition at line 29 of file Size2D.cpp.
References Size2D::height, arm_compute::support::cpp11::to_string(), and Size2D::width.
Referenced by ClWinogradFilterTransformKernel::configure(), ClWinogradInputTransformKernel::configure(), ClWinogradOutputTransformKernel::configure(), and Size2D::operator!=().
 {
     return support::cpp11::to_string(width) + std::string("x") + support::cpp11::to_string(height);
 }
x()
size_t x () const inline
Semantic accessor for width as x.
Returns
x.
Definition at line 75 of file Size2D.h.
References Size2D::width.
Referenced by arm_compute::calculate_same_pad(), arm_compute::misc::shape_calculator::compute_space_to_batch_shape(), arm_compute::misc::shape_calculator::compute_upsample_shape(), ClDWCNativeDefaultConfigValhall::configure(), ClDWCNativeDefaultConfigBifrost::configure(), ClWinogradOutputTransformKernel::configure(), arm_compute::experimental::dynamic_fusion::convert_pool_attr_to_pool_info(), arm_compute::test::validation::reference::convolution_layer_nchw(), ClTemplatePool2d::get_component_code(), CpuPool2dAssemblyWrapperKernel::is_configured(), arm_compute::is_pool_region_entirely_outside_input(), NESpaceToBatchLayerKernel::run(), arm_compute::scaled_dimensions(), and CLDepthwiseConvolutionLayer::validate().
     {
         return width;
     }
y()
size_t y () const inline
Semantic accessor for height as y.
Returns
y.
Definition at line 84 of file Size2D.h.
References Size2D::height.
Referenced by arm_compute::calculate_same_pad(), arm_compute::misc::shape_calculator::compute_space_to_batch_shape(), arm_compute::misc::shape_calculator::compute_upsample_shape(), ClWinogradOutputTransformKernel::configure(), arm_compute::experimental::dynamic_fusion::convert_pool_attr_to_pool_info(), arm_compute::test::validation::reference::convolution_layer_nchw(), ClTemplatePool2d::get_component_code(), CpuPool2dAssemblyWrapperKernel::is_configured(), arm_compute::is_pool_region_entirely_outside_input(), NESpaceToBatchLayerKernel::run(), arm_compute::scaled_dimensions(), and CLDepthwiseConvolutionLayer::validate().
     {
         return height;
     }
Field Documentation
height
size_t height = {}
Height of the image region or rectangle.
Definition at line 91 of file Size2D.h.
Referenced by GraphBuilder::add_convolution_node(), GraphBuilder::add_deconvolution_node(), GraphBuilder::add_depthwise_convolution_node(), Size2D::area(), arm_compute::cl_winograd_convolution_layer_supported(), arm_compute::misc::shape_calculator::compute_col2im_shape(), arm_compute::misc::shape_calculator::compute_im2col_conv_shape(), PoolingLayerNode::compute_output_descriptor(), arm_compute::misc::shape_calculator::compute_pool_shape(), arm_compute::misc::shape_calculator::compute_unpool_shape(), arm_compute::compute_winograd_convolution_tiles(), arm_compute::misc::shape_calculator::compute_winograd_filter_transform_shape(), arm_compute::misc::shape_calculator::compute_winograd_input_transform_shape(), arm_compute::misc::shape_calculator::compute_winograd_output_transform_shape(), ClPool2dKernel::configure(), CpuPool2dKernel::configure(), CpuPool2d::configure(), ClWinogradInputTransformKernel::configure(), ClWinogradFilterTransformKernel::configure(), ClWinogradOutputTransformKernel::configure(), CpuIm2ColKernel::configure(), ClIm2ColKernel::configure(), arm_compute::test::validation::reference::im2col_nchw(), arm_compute::test::validation::reference::im2col_nhwc(), arm_compute::operator<<(), Size2D::operator==(), arm_compute::test::validation::reference::pooling_layer_internal(), arm_compute::cpu::poolingMxN_fp32_neon_nhwc(), arm_compute::cpu::poolingMxN_q8_neon_nhwc(), Size2D::to_string(), arm_compute::to_string(), CpuPool2dKernel::validate(), arm_compute::test::validation::reference::winograd_filter_transform(), arm_compute::test::validation::reference::winograd_input_transform(), arm_compute::test::validation::reference::winograd_output_transform(), and Size2D::y().
width
size_t width = {}
Width of the image region or rectangle.
Definition at line 90 of file Size2D.h.
Referenced by GraphBuilder::add_convolution_node(), GraphBuilder::add_deconvolution_node(), GraphBuilder::add_depthwise_convolution_node(), Size2D::area(), arm_compute::cl_winograd_convolution_layer_supported(), arm_compute::misc::shape_calculator::compute_col2im_shape(), arm_compute::misc::shape_calculator::compute_im2col_conv_shape(), PoolingLayerNode::compute_output_descriptor(), arm_compute::misc::shape_calculator::compute_pool_shape(), arm_compute::misc::shape_calculator::compute_unpool_shape(), arm_compute::compute_winograd_convolution_tiles(), arm_compute::misc::shape_calculator::compute_winograd_filter_transform_shape(), arm_compute::misc::shape_calculator::compute_winograd_input_transform_shape(), arm_compute::misc::shape_calculator::compute_winograd_output_transform_shape(), ClPool2dKernel::configure(), CpuPool2dKernel::configure(), CpuPool2d::configure(), ClWinogradFilterTransformKernel::configure(), ClWinogradInputTransformKernel::configure(), ClWinogradOutputTransformKernel::configure(), ClCol2ImKernel::configure(), CpuIm2ColKernel::configure(), ClIm2ColKernel::configure(), arm_compute::test::validation::reference::im2col_nchw(), arm_compute::test::validation::reference::im2col_nhwc(), arm_compute::operator<<(), Size2D::operator==(), arm_compute::test::validation::reference::pooling_layer_internal(), arm_compute::cpu::poolingMxN_fp32_neon_nhwc(), arm_compute::cpu::poolingMxN_q8_neon_nhwc(), Size2D::to_string(), arm_compute::to_string(), CpuPool2dKernel::validate(), arm_compute::test::validation::reference::winograd_filter_transform(), arm_compute::test::validation::reference::winograd_input_transform(), arm_compute::test::validation::reference::winograd_output_transform(), and Size2D::x().
The documentation for this class was generated from the following files:
arm_compute/core/Size2D.h
src/core/Size2D.cpp