Compute Library: GpuKernelVariableTable Class Reference
GpuKernelVariableTable Class Reference
A table of all the variables used in the kernel.
#include <GpuKernelVariableTable.h>
Data Structures
struct TensorVariable
A tensor variable whose main purposes are:
Public Types
using VariableList = std::vector< TensorVariable >
Public Member Functions
void declare_variable (const GpuKernelComponentGroup &comp_group, const ITensorInfo *tensor, GpuKernelArgumentInfo argument_info, const std::string &alias="unnamed")
Declare a TensorVariable for a corresponding tensor info.
TensorVariable get_variable (const ITensorInfo *tensor) const
Get the TensorVariable associated with tensor.
VariableList get_variable_list (const std::vector< const ITensorInfo *> &tensors) const
Get the TensorVariable list associated with tensors.
Detailed Description
A table of all the variables used in the kernel.
Each kernel has exactly one variable table.
Definition at line 47 of file GpuKernelVariableTable.h.
Member Typedef Documentation
VariableList
using VariableList = std::vector<TensorVariable>
Definition at line 68 of file GpuKernelVariableTable.h.
Member Function Documentation
declare_variable()
void declare_variable (const GpuKernelComponentGroup & comp_group, const ITensorInfo * tensor, GpuKernelArgumentInfo argument_info, const std::string & alias = "unnamed")
Declare a TensorVariable for a corresponding tensor info.
Parameters
[in] comp_group Component group the tensor belongs to
[in] tensor Tensor info with which the new variable is associated
[in] argument_info Kernel argument information
[in] alias Alias for the variable. Will be used as part of the variable name
Definition at line 35 of file GpuKernelVariableTable.cpp.
References ARM_COMPUTE_ERROR_ON, ARM_COMPUTE_ERROR_ON_MSG, GpuKernelComponentGroup::get_tile_for_tensor(), ITensorInfo::has_valid_id(), ITensorInfo::id(), and arm_compute::test::validation::ss().
Referenced by ClTemplateStore::declare_variables(), ClTemplateCast::declare_variables(), ClTemplateReshape::declare_variables(), ClTemplateLogits1DMaxShiftExpSum::declare_variables(), ClTemplateLogits1DNorm::declare_variables(), ClTemplateDepthwiseConv2d::declare_variables(), ClTemplateElementwiseBinary::declare_variables(), ClTemplateDirectConv2d::declare_variables(), ClTemplateResize::declare_variables(), ClTemplateActivation::declare_variables(), and ClTemplatePool2d::declare_variables().
 {
     ARM_COMPUTE_ERROR_ON_MSG(!tensor->has_valid_id(), "Tensor info with valid id expected");
     // Do not re-declare if the variable associated with the tensor has already been declared
     auto it = _vars.find(tensor->id());
     if(it != _vars.end())
     {
         ARM_COMPUTE_ERROR_ON(!(it->second.kernel_argument_info == argument_info));
         return;
     }
     const auto target = comp_group.get_tile_for_tensor(tensor);
     if(target != tensor)
     {
         // If the tensor uses a shared tile, don't declare another variable.
         it = _vars.find(target->id());
         ARM_COMPUTE_ERROR_ON_MSG(
             it == _vars.end(),
             "The variable used for this tensor must have been declared.");
         _vars[tensor->id()] = it->second;
     }
     else
     {
         // Declare variable associated with the tensor
         std::stringstream ss;
         ss << alias << "_t" << abs(tensor->id());
         const auto     uniq_name = ss.str();
         TensorVariable var{ tensor->id(), uniq_name, argument_info };
         _vars.emplace(tensor->id(), var);
     }
 }
get_variable()
GpuKernelVariableTable::TensorVariable get_variable (const ITensorInfo * tensor) const
Get the TensorVariable associated with tensor.
Parameters
[in] tensor Tensor info to be queried
Returns
TensorVariable
Definition at line 73 of file GpuKernelVariableTable.cpp.
References ITensorInfo::id().
Referenced by ClTemplateStore::get_tag_lut(), ClTemplateCast::get_tag_lut(), ClTemplateLogits1DMaxShiftExpSum::get_tag_lut(), ClTemplateLogits1DNorm::get_tag_lut(), ClTemplateReshape::get_tag_lut(), ClTemplateDepthwiseConv2d::get_tag_lut(), ClTemplateElementwiseBinary::get_tag_lut(), ClTemplateDirectConv2d::get_tag_lut(), ClTemplateResize::get_tag_lut(), ClTemplateActivation::get_tag_lut(), ClTemplatePool2d::get_tag_lut(), ClTemplateWriter::get_tensors(), and GpuKernelVariableTable::get_variable_list().
 {
     const auto var = _vars.at(tensor->id());
     return var;
 }
get_variable_list()
GpuKernelVariableTable::VariableList get_variable_list (const std::vector< const ITensorInfo *> & tensors) const
Get the TensorVariable list associated with tensors.
Note
Empty tensors are skipped
Parameters
[in] tensors List of tensor infos to be queried
Returns
VariableList
Definition at line 79 of file GpuKernelVariableTable.cpp.
References GpuKernelVariableTable::get_variable(), and tensor.
Referenced by ClTemplateWriter::get_tensors().
 {
     VariableList vars{};
     for(const auto &tensor : tensors)
     {
         if(!tensor->has_valid_id())
         {
             continue;
         }
         vars.push_back(get_variable(tensor));
     }
     return vars;
 }
The documentation for this class was generated from the following files:
src/dynamic_fusion/sketch/gpu/template_writer/GpuKernelVariableTable.h
src/dynamic_fusion/sketch/gpu/template_writer/GpuKernelVariableTable.cpp