Compute Library: NEStackLayerKernel Class Reference
NEStackLayerKernel Class Reference
Basic kernel to stack a rank-R tensor into one with rank-(R+1) along the axis dimension.
#include <NEStackLayerKernel.h>
Public Member Functions
const char * name () const override
Name of the kernel.
NEStackLayerKernel ()
Default constructor.
NEStackLayerKernel (const NEStackLayerKernel &)=delete
Prevent instances of this class from being copied (As this class contains pointers)
NEStackLayerKernel & operator= (const NEStackLayerKernel &)=delete
Prevent instances of this class from being copied (As this class contains pointers)
NEStackLayerKernel (NEStackLayerKernel &&)=default
Allow instances of this class to be moved.
NEStackLayerKernel & operator= (NEStackLayerKernel &&)=default
Allow instances of this class to be moved.
~NEStackLayerKernel ()=default
Default destructor.
void configure (const ITensor *input, unsigned int axis, unsigned int idx_input, unsigned int num_tensors, ITensor *output)
Initialise the kernel's inputs and output.
void run (const Window &window, const ThreadInfo &info) override
Execute the kernel on the passed window.
Public Member Functions inherited from ICPPKernel
virtual ~ICPPKernel ()=default
Default destructor.
virtual void run_nd (const Window &window, const ThreadInfo &info, const Window &thread_locator)
legacy compatibility layer for implemantions which do not support thread_locator In these cases we simply narrow the interface down the legacy version
virtual void run_op (ITensorPack &tensors, const Window &window, const ThreadInfo &info)
Execute the kernel on the passed window.
virtual size_t get_mws (const CPUInfo &platform, size_t thread_count) const
Return minimum workload size of the relevant kernel.
Public Member Functions inherited from IKernel
IKernel ()
Constructor.
virtual ~IKernel ()=default
Destructor.
virtual bool is_parallelisable () const
Indicates whether or not the kernel is parallelisable.
virtual BorderSize border_size () const
The size of the border for that kernel.
const Window & window () const
The maximum window the kernel can be executed on.
bool is_window_configured () const
Function to check if the embedded window of this kernel has been configured.
Static Public Member Functions
static Status validate (const ITensorInfo *input, unsigned int axis, unsigned int idx_input, unsigned int num_tensors, const ITensorInfo *output)
Static function to check if given info will lead to a valid configuration of NEStackLayerKernel.
Additional Inherited Members
Static Public Attributes inherited from ICPPKernel
static constexpr size_t default_mws = 1
Detailed Description
Basic kernel to stack a rank-R tensor into one with rank-(R+1) along the axis dimension.
Definition at line 36 of file NEStackLayerKernel.h.
Constructor & Destructor Documentation
NEStackLayerKernel() [1/3]
NEStackLayerKernel ()
Default constructor.
Definition at line 87 of file NEStackLayerKernel.cpp.
Referenced by NEStackLayerKernel::name().
     : _input(nullptr), _output(nullptr), _axis(), _idx_input()
 {
 }
NEStackLayerKernel() [2/3]
NEStackLayerKernel (const NEStackLayerKernel &) delete
Prevent instances of this class from being copied (As this class contains pointers)
NEStackLayerKernel() [3/3]
NEStackLayerKernel (NEStackLayerKernel &&) default
Allow instances of this class to be moved.
~NEStackLayerKernel()
~NEStackLayerKernel () default
Default destructor.
Referenced by NEStackLayerKernel::name().
Member Function Documentation
configure()
void configure (const ITensor * input, unsigned int axis, unsigned int idx_input, unsigned int num_tensors, ITensor * output)
Initialise the kernel's inputs and output.
Note
Supported input tensor rank: up to 4
Parameters
[in] input Input tensor. Data types supported: All
[in] axis The dimension to stack the tensors along. It must be smaller than the number of input dimensions.
[in] idx_input Index of the input tensor in the list of tensors to stack. All tensors in the list must have the same shape
[in] num_tensors Number of tensors to stack
[out] output Output tensor. Data types supported: Same as input.
Definition at line 92 of file NEStackLayerKernel.cpp.
References ARM_COMPUTE_ERROR_ON_NULLPTR, ARM_COMPUTE_ERROR_THROW_ON, ITensor::info(), arm_compute::test::validation::input, arm_compute::cpu::kernels::validate_and_configure_window(), and arm_compute::cpu::kernels::validate_arguments().
Referenced by NEStackLayerKernel::name().
 {
     ARM_COMPUTE_ERROR_ON_NULLPTR(input, output);
     ARM_COMPUTE_ERROR_THROW_ON(validate_arguments(input->info(), axis, idx_input, num_tensors, output->info()));
     _input     = input;
     _output    = output;
     _axis      = axis;
     _idx_input = idx_input;
     // Configure kernel window
     auto win_config = validate_and_configure_window(input->info(), axis, num_tensors, output->info());
     ARM_COMPUTE_ERROR_THROW_ON(win_config.first);
     INEKernel::configure(win_config.second);
 }
name()
const char* name () const inline override virtual
Name of the kernel.
Returns
Kernel name
Implements ICPPKernel.
Definition at line 39 of file NEStackLayerKernel.h.
References NEStackLayerKernel::configure(), arm_compute::test::validation::info, arm_compute::test::validation::input, NEStackLayerKernel::NEStackLayerKernel(), NEStackLayerKernel::operator=(), NEStackLayerKernel::run(), NEStackLayerKernel::validate(), IKernel::window(), and NEStackLayerKernel::~NEStackLayerKernel().
     {
         return "NEStackLayerKernel";
     }
operator=() [1/2]
NEStackLayerKernel& operator= (const NEStackLayerKernel &) delete
Prevent instances of this class from being copied (As this class contains pointers)
Referenced by NEStackLayerKernel::name().
operator=() [2/2]
NEStackLayerKernel& operator= (NEStackLayerKernel &&) default
Allow instances of this class to be moved.
run()
void run (const Window & window, const ThreadInfo & info) override virtual
Execute the kernel on the passed window.
Warning
If is_parallelisable() returns false then the passed window must be equal to window()
Note
The window has to be a region within the window returned by the window() method
The width of the window has to be a multiple of num_elems_processed_per_iteration().
Parameters
[in] window Region on which to execute the kernel. (Must be a region of the window returned by window())
[in] info Info about executing thread and CPU.
Reimplemented from ICPPKernel.
Definition at line 116 of file NEStackLayerKernel.cpp.
References ARM_COMPUTE_ERROR_ON_INVALID_SUBWINDOW, ARM_COMPUTE_ERROR_ON_UNCONFIGURED_KERNEL, ARM_COMPUTE_UNUSED, ITensorInfo::element_size(), arm_compute::execute_window_loop(), ITensor::info(), arm_compute::test::validation::input, ITensorInfo::num_dimensions(), Iterator::ptr(), ITensorInfo::strides_in_bytes(), ITensorInfo::tensor_shape(), Window::use_tensor_dimensions(), and IKernel::window().
Referenced by NEStackLayerKernel::name().
 {
     ARM_COMPUTE_UNUSED(info);
     ARM_COMPUTE_ERROR_ON_UNCONFIGURED_KERNEL(this);
     ARM_COMPUTE_ERROR_ON_INVALID_SUBWINDOW(INEKernel::window(), window);
     Window window_out;
     window_out.use_tensor_dimensions(_output->info()->tensor_shape());
     Iterator input(_input, window);
     Iterator output(_output, window_out);
     const int stride_x = _output->info()->strides_in_bytes()[0];
     const int stride_y = _output->info()->num_dimensions() >= 1 ? _output->info()->strides_in_bytes()[1] : 0;
     const int stride_z = _output->info()->num_dimensions() >= 2 ? _output->info()->strides_in_bytes()[2] : 0;
     const int stride_w = _output->info()->num_dimensions() >= 3 ? _output->info()->strides_in_bytes()[3] : 0;
     const int stride_k = _output->info()->num_dimensions() >= 4 ? _output->info()->strides_in_bytes()[4] : 0;
     execute_window_loop(window, [&](const Coordinates & id)
     {
         Coordinates id_out = shift_from_axis_and_replace_coordinate(id, _axis, _idx_input);
         const int   idx    = id_out[0] * stride_x + id_out[1] * stride_y + id_out[2] * stride_z + id_out[3] * stride_w + id_out[4] * stride_k;
         std::memcpy(output.ptr() + idx, input.ptr(), _input->info()->element_size());
     },
     input);
 }
validate()
Status validate (const ITensorInfo * input, unsigned int axis, unsigned int idx_input, unsigned int num_tensors, const ITensorInfo * output) static
Static function to check if given info will lead to a valid configuration of NEStackLayerKernel.
Note
Supported input tensor rank: up to 4
Parameters
[in] input Input tensor info. Data types supported: All
[in] axis The dimension to stack the tensors along. It must be smaller than the number of input dimensions.
[in] idx_input Index of the input tensor in the list of tensors to stack All tensors in the list must have the same shape
[in] num_tensors Number of tensors to stack
[in] output Output tensor info. Data types supported: Same as input.
Returns
a status
Definition at line 109 of file NEStackLayerKernel.cpp.
References ARM_COMPUTE_RETURN_ON_ERROR, ICloneable< T >::clone(), arm_compute::cpu::kernels::validate_and_configure_window(), and arm_compute::cpu::kernels::validate_arguments().
Referenced by NEStackLayerKernel::name(), and NEStackLayer::validate().
 {
     ARM_COMPUTE_RETURN_ON_ERROR(validate_arguments(input, axis, idx_input, num_tensors, output));
     ARM_COMPUTE_RETURN_ON_ERROR(validate_and_configure_window(input->clone().get(), axis, num_tensors, output->clone().get()).first);
     return Status{};
 }
The documentation for this class was generated from the following files:
src/core/NEON/kernels/NEStackLayerKernel.h
src/core/NEON/kernels/NEStackLayerKernel.cpp