Compute Library: GpuWorkloadSketch Class Reference
GpuWorkloadSketch Class Reference
A descriptor of a workload of operators.
#include <GpuWorkloadSketch.h>
Data Structures
class Implementation
Internal implementation of GpuWorkloadSketch.
Public Types
using Context = GpuWorkloadContext
Global context used for the creation of a workload.
Public Member Functions
GpuWorkloadSketch (GpuWorkloadContext *context)
Constructor.
~GpuWorkloadSketch ()
Destructor.
Implementation & implementation ()
Get the implementation.
const Implementation & implementation () const
Get the implementation.
const GpuWorkloadContext * gpu_context () const
Get the gpu workload context of this sketch.
template<typename... Args>
TensorInfo create_tensor_info (Args &&... args)
Create a TensorInfo associated with the workload sketch.
TensorInfo create_tensor_info ()
Create a default TensorInfo associated with the workload sketch It is usually used by user input or output tensors.
Detailed Description
A descriptor of a workload of operators.
A "workload" is a basic unit of computation to schedule and perform. It contains one or more operators that can be "fused" together. Note that a workload may still contain multiple kernels.
Definition at line 43 of file GpuWorkloadSketch.h.
Member Typedef Documentation
Context
using Context = GpuWorkloadContext
Global context used for the creation of a workload.
Definition at line 47 of file GpuWorkloadSketch.h.
Constructor & Destructor Documentation
GpuWorkloadSketch()
GpuWorkloadSketch (GpuWorkloadContext * context) explicit
Constructor.
Parameters
[in] context Gpu context for the creation of a workload
Definition at line 33 of file GpuWorkloadSketch.cpp.
     : _impl{ std::make_unique<Implementation>(context) }
 {
 }
~GpuWorkloadSketch()
~GpuWorkloadSketch ()
Destructor.
Definition at line 37 of file GpuWorkloadSketch.cpp.
 {
 }
Member Function Documentation
create_tensor_info() [1/2]
TensorInfo create_tensor_info (Args &&... args) inline
Create a TensorInfo associated with the workload sketch.
Returns
TensorInfo Newly created tensor info
Definition at line 70 of file GpuWorkloadSketch.h.
References GemmTuner::args, GpuWorkloadSketch::create_tensor_info(), and tensor_info.
Referenced by arm_compute::test::validation::DATA_TEST_CASE(), and arm_compute::test::validation::TEST_CASE().
     {
         auto tensor_info = TensorInfo(std::forward<Args>(args)...);
         register_new_tensor(tensor_info);
         return tensor_info;
     }
create_tensor_info() [2/2]
TensorInfo create_tensor_info ()
Create a default TensorInfo associated with the workload sketch It is usually used by user input or output tensors.
Returns
TensorInfo Newly created tensor info
Definition at line 53 of file GpuWorkloadSketch.cpp.
References tensor_info.
Referenced by GpuWorkloadSketch::create_tensor_info().
 {
     TensorInfo tensor_info{};
     register_new_tensor(tensor_info);
     return tensor_info;
 }
gpu_context()
const GpuWorkloadSketch::Context * gpu_context () const
Get the gpu workload context of this sketch.
Definition at line 41 of file GpuWorkloadSketch.cpp.
References ITensorInfo::set_id(), tensor_info, and arm_compute::experimental::dynamic_fusion::User.
Referenced by ClWorkloadRuntime::configure(), GpuOutput::validate_op(), GpuReshape::validate_op(), GpuSoftmax::validate_op(), GpuClamp::validate_op(), GpuResize::validate_op(), GpuCast::validate_op(), GpuConv2d::validate_op(), GpuDepthwiseConv2d::validate_op(), GpuPool2d::validate_op(), and GpuElementwiseBinaryCommon::validate_op().
 {
     return _impl->context();
 }
implementation() [1/2]
GpuWorkloadSketch::Implementation & implementation ()
Get the implementation.
Definition at line 60 of file GpuWorkloadSketch.cpp.
Referenced by ClWorkloadRuntime::configure(), GpuOutput::create_op(), GpuSoftmax::create_op(), GpuClamp::create_op(), GpuReshape::create_op(), GpuDepthwiseConv2d::create_op(), GpuConv2d::create_op(), GpuResize::create_op(), GpuCast::create_op(), GpuPool2d::create_op(), GpuElementwiseBinaryCommon::create_op(), GpuOutput::validate_op(), GpuReshape::validate_op(), GpuSoftmax::validate_op(), GpuClamp::validate_op(), GpuResize::validate_op(), GpuCast::validate_op(), GpuConv2d::validate_op(), GpuDepthwiseConv2d::validate_op(), GpuPool2d::validate_op(), and GpuElementwiseBinaryCommon::validate_op().
 {
     return *_impl;
 }
implementation() [2/2]
const GpuWorkloadSketch::Implementation & implementation () const
Get the implementation.
Definition at line 64 of file GpuWorkloadSketch.cpp.
 {
     return *_impl;
 }
The documentation for this class was generated from the following files:
arm_compute/dynamic_fusion/sketch/gpu/GpuWorkloadSketch.h
src/dynamic_fusion/sketch/gpu/GpuWorkloadSketch.cpp