Compute Library: NEReductionOperationKernel Class Reference
NEReductionOperationKernel Class Reference
Kernel to perform a reduction operation.
#include <NEReductionOperationKernel.h>
Public Member Functions
const char * name () const override
Name of the kernel.
NEReductionOperationKernel ()
Default constructor.
NEReductionOperationKernel (const NEReductionOperationKernel &)=delete
Prevent instances of this class from being copied (As this class contains pointers)
NEReductionOperationKernel & operator= (const NEReductionOperationKernel &)=delete
Prevent instances of this class from being copied (As this class contains pointers)
NEReductionOperationKernel (NEReductionOperationKernel &&)=default
Allow instances of this class to be moved.
NEReductionOperationKernel & operator= (NEReductionOperationKernel &&)=default
Allow instances of this class to be moved.
~NEReductionOperationKernel ()=default
Default destructor.
void configure (const ITensor *input, ITensor *output, unsigned int axis, ReductionOperation op)
Set the source, destination of the kernel.
void run (const Window &window, const ThreadInfo &info) override
Execute the kernel on the passed window.
Public Member Functions inherited from ICPPKernel
virtual ~ICPPKernel ()=default
Default destructor.
virtual void run_nd (const Window &window, const ThreadInfo &info, const Window &thread_locator)
legacy compatibility layer for implemantions which do not support thread_locator In these cases we simply narrow the interface down the legacy version
virtual void run_op (ITensorPack &tensors, const Window &window, const ThreadInfo &info)
Execute the kernel on the passed window.
virtual size_t get_mws (const CPUInfo &platform, size_t thread_count) const
Return minimum workload size of the relevant kernel.
Public Member Functions inherited from IKernel
IKernel ()
Constructor.
virtual ~IKernel ()=default
Destructor.
virtual bool is_parallelisable () const
Indicates whether or not the kernel is parallelisable.
virtual BorderSize border_size () const
The size of the border for that kernel.
const Window & window () const
The maximum window the kernel can be executed on.
bool is_window_configured () const
Function to check if the embedded window of this kernel has been configured.
Static Public Member Functions
static Status validate (const ITensorInfo *input, const ITensorInfo *output, unsigned int axis, ReductionOperation op)
Static function to check if given info will lead to a valid configuration of NEReductionOperationKernel.
Additional Inherited Members
Static Public Attributes inherited from ICPPKernel
static constexpr size_t default_mws = 1
Detailed Description
Kernel to perform a reduction operation.
Note
For ARG_MIN/ARG_MAX reduction, the default data type for an uninitialized output tensor is signed 32-bit integer (S32). It is the user's responsibility to check that the results do not overflow because the indices are computed in unsigned 32-bit (U32).
Definition at line 40 of file NEReductionOperationKernel.h.
Constructor & Destructor Documentation
NEReductionOperationKernel() [1/3]
NEReductionOperationKernel ()
Default constructor.
Definition at line 1743 of file NEReductionOperationKernel.cpp.
Referenced by NEReductionOperationKernel::name().
     : _input(nullptr), _output(nullptr), _reduction_axis(0), _op(ReductionOperation::SUM_SQUARE)
 {
 }
NEReductionOperationKernel() [2/3]
NEReductionOperationKernel (const NEReductionOperationKernel &) delete
Prevent instances of this class from being copied (As this class contains pointers)
NEReductionOperationKernel() [3/3]
NEReductionOperationKernel (NEReductionOperationKernel &&) default
Allow instances of this class to be moved.
~NEReductionOperationKernel()
~NEReductionOperationKernel () default
Default destructor.
Referenced by NEReductionOperationKernel::name().
Member Function Documentation
configure()
void configure (const ITensor * input, ITensor * output, unsigned int axis, ReductionOperation op)
Set the source, destination of the kernel.
Parameters
[in] input Source tensor. Data type supported: QASYMM8_SIGNED/QASYMM8/F16/F32/S32.
[out] output Destination tensor.Data types and data layouts supported: same as input, S32 for ARG_MIX/ARG_MAX. Output will have the same number of dimensions as input.
[in] axis Axis along which to reduce. Supported reduction axis : 0
[in] op Reduction operation to perform.
Definition at line 1748 of file NEReductionOperationKernel.cpp.
References arm_compute::ARG_IDX_MAX, arm_compute::ARG_IDX_MIN, ARM_COMPUTE_ERROR_ON_NULLPTR, ARM_COMPUTE_ERROR_THROW_ON, arm_compute::auto_init_if_empty(), arm_compute::calculate_max_window(), ICloneable< T >::clone(), arm_compute::misc::shape_calculator::compute_reduced_shape(), ITensorInfo::data_type(), ITensor::info(), arm_compute::test::validation::input, arm_compute::S32, ITensorInfo::tensor_shape(), and arm_compute::cpu::kernels::validate_arguments().
Referenced by NEReductionOperationKernel::name().
 {
     ARM_COMPUTE_ERROR_ON_NULLPTR(input, output);
     ARM_COMPUTE_ERROR_THROW_ON(validate_arguments(input->info(), output->info(), axis, op));
     _input          = input;
     _output         = output;
     _op             = op;
     _reduction_axis = axis;
     // Configure kernel window
     Window win = calculate_max_window(*input->info(), Steps());
     INEKernel::configure(win);
     // Calculate output shape and set if empty
     const TensorShape output_shape = arm_compute::misc::shape_calculator::compute_reduced_shape(input->info()->tensor_shape(), axis);
     // Output auto initialization if not yet initialized
     const bool is_arg_min_max   = (op == ReductionOperation::ARG_IDX_MIN || op == ReductionOperation::ARG_IDX_MAX);
     DataType   output_data_type = is_arg_min_max ? DataType::S32 : input->info()->data_type();
     auto_init_if_empty(*output->info(), input->info()->clone()->set_tensor_shape(output_shape).set_data_type(output_data_type).reset_padding().set_is_resizable(true));
 }
name()
const char* name () const inline override virtual
Name of the kernel.
Returns
Kernel name
Implements ICPPKernel.
Definition at line 43 of file NEReductionOperationKernel.h.
References NEReductionOperationKernel::configure(), arm_compute::test::validation::info, arm_compute::test::validation::input, NEReductionOperationKernel::NEReductionOperationKernel(), NEReductionOperationKernel::operator=(), NEReductionOperationKernel::run(), NEReductionOperationKernel::validate(), IKernel::window(), and NEReductionOperationKernel::~NEReductionOperationKernel().
     {
         return "NEReductionOperationKernel";
     }
operator=() [1/2]
NEReductionOperationKernel& operator= (const NEReductionOperationKernel &) delete
Prevent instances of this class from being copied (As this class contains pointers)
Referenced by NEReductionOperationKernel::name().
operator=() [2/2]
NEReductionOperationKernel& operator= (NEReductionOperationKernel &&) default
Allow instances of this class to be moved.
run()
void run (const Window & window, const ThreadInfo & info) override virtual
Execute the kernel on the passed window.
Warning
If is_parallelisable() returns false then the passed window must be equal to window()
Note
The window has to be a region within the window returned by the window() method
The width of the window has to be a multiple of num_elems_processed_per_iteration().
Parameters
[in] window Region on which to execute the kernel. (Must be a region of the window returned by window())
[in] info Info about executing thread and CPU.
Reimplemented from ICPPKernel.
Definition at line 1778 of file NEReductionOperationKernel.cpp.
References ARM_COMPUTE_ERROR_ON_INVALID_SUBWINDOW, ARM_COMPUTE_ERROR_ON_UNCONFIGURED_KERNEL, ARM_COMPUTE_UNUSED, and IKernel::window().
Referenced by NEReductionOperationKernel::name().
 {
     ARM_COMPUTE_UNUSED(info);
     ARM_COMPUTE_ERROR_ON_UNCONFIGURED_KERNEL(this);
     ARM_COMPUTE_ERROR_ON_INVALID_SUBWINDOW(INEKernel::window(), window);
     reduce_op(window, _input, _output, _reduction_axis, _op);
 }
validate()
Status validate (const ITensorInfo * input, const ITensorInfo * output, unsigned int axis, ReductionOperation op) static
Static function to check if given info will lead to a valid configuration of NEReductionOperationKernel.
Parameters
[in] input Source tensor info. Data type supported: QASYMM8_SIGNED/QASYMM8/F16/F32/S32.
[in] output Destination tensor info.Data types and data layouts supported: same as input, S32 for ARG_MIX/ARG_MAX. Output will have the same number of dimensions as input.
[in] axis Axis along which to reduce. Supported reduction axis : 0
[in] op Reduction operation to perform.
Returns
a status
Definition at line 1771 of file NEReductionOperationKernel.cpp.
References ARM_COMPUTE_RETURN_ON_ERROR, and arm_compute::cpu::kernels::validate_arguments().
Referenced by NEReductionOperationKernel::name(), and NEReductionOperation::validate().
 {
     ARM_COMPUTE_RETURN_ON_ERROR(validate_arguments(input, output, axis, op));
     return Status{};
 }
The documentation for this class was generated from the following files:
src/core/NEON/kernels/NEReductionOperationKernel.h
src/core/NEON/kernels/NEReductionOperationKernel.cpp