Compute Library: CpuContext Class Reference
CpuContext Class Reference final
CPU context implementation class.
#include <CpuContext.h>
Public Member Functions
CpuContext (const AclContextOptions *options)
Default Constructor.
const CpuCapabilities & capabilities () const
Cpu Capabilities accessor.
AllocatorWrapper & allocator ()
Backing memory allocator accessor.
ITensorV2 * create_tensor (const AclTensorDescriptor &desc, bool allocate) override
Create a tensor object.
IQueue * create_queue (const AclQueueOptions *options) override
Create a queue object.
std::tuple< IOperator *, StatusCode > create_activation (const AclTensorDescriptor &src, const AclTensorDescriptor &dst, const AclActivationDescriptor &act, bool is_validate) override
Public Member Functions inherited from IContext
IContext (Target target)
virtual ~IContext ()
Virtual Destructor.
Target type () const
Target type accessor.
void inc_ref () const
Increment context refcount.
void dec_ref () const
Decrement context refcount.
int refcount () const
Reference counter accessor.
bool is_valid () const
Checks if an object is valid.
Additional Inherited Members
Data Fields inherited from AclContext_
arm_compute::detail::Header header { arm_compute::detail::ObjectType::Context, nullptr }
Detailed Description
CPU context implementation class.
Definition at line 43 of file CpuContext.h.
Constructor & Destructor Documentation
CpuContext()
CpuContext (const AclContextOptions * options) explicit
Default Constructor.
Parameters
[in] options Creational options
Definition at line 149 of file CpuContext.cpp.
References AclContextOptions::allocator, AclContextOptions::capabilities, and AclContextOptions::max_compute_units.
     : IContext(Target::Cpu),
       _allocator(default_allocator),
       _caps(populate_capabilities(AclCpuCapabilitiesAuto, -1))
 {
     if(options != nullptr)
     {
         _allocator = populate_allocator(options->allocator);
         _caps      = populate_capabilities(options->capabilities, options->max_compute_units);
     }
 }
Member Function Documentation
allocator()
AllocatorWrapper & allocator ()
Backing memory allocator accessor.
Returns
Allocator that allocates CPU memory
Definition at line 166 of file CpuContext.cpp.
 {
     return _allocator;
 }
capabilities()
const CpuCapabilities & capabilities () const
Cpu Capabilities accessor.
Returns
The ISA capabilities to be used by the CPU
Definition at line 161 of file CpuContext.cpp.
Referenced by arm_compute::test::validation::TEST_CASE().
 {
     return _caps;
 }
create_activation()
std::tuple< IOperator *, StatusCode > create_activation (const AclTensorDescriptor & src, const AclTensorDescriptor & dst, const AclActivationDescriptor & act, bool is_validate) override virtual
Implements IContext.
Definition at line 57 of file CpuActivation.cpp.
References ARM_COMPUTE_LOG_ERROR_ACL, arm_compute::detail::convert_to_activation_info(), arm_compute::detail::convert_to_legacy_tensor_info(), arm_compute::test::validation::info, arm_compute::OutOfMemory, TensorInfo::set_is_resizable(), arm_compute::test::validation::src_info, arm_compute::Success, arm_compute::UnsupportedConfig, and CpuActivation::validate().
 {
     TensorInfo src_info = detail::convert_to_legacy_tensor_info(src);
     TensorInfo dst_info = detail::convert_to_legacy_tensor_info(dst);
     auto       info     = detail::convert_to_activation_info(act);
     if(is_validate && !bool(CpuActivation::validate(&src_info.set_is_resizable(false), &dst_info.set_is_resizable(false), info)))
     {
         return std::make_tuple(nullptr, StatusCode::UnsupportedConfig);
     }
     auto act_op = std::make_unique<cpu::CpuActivation>();
     act_op->configure(&src_info, &dst_info, info);
     auto op = new arm_compute::IOperator(static_cast<IContext *>(this));
     if(op == nullptr)
     {
         ARM_COMPUTE_LOG_ERROR_ACL("Couldn't allocate internal resources");
         return std::make_tuple(nullptr, StatusCode::OutOfMemory);
     }
     op->set_internal_operator(std::move(act_op));
     return std::make_tuple(op, StatusCode::Success);
 }
create_queue()
IQueue * create_queue (const AclQueueOptions * options) override virtual
Create a queue object.
Parameters
[in] options Queue options to be used
Returns
A pointer to the created queue object
Implements IContext.
Definition at line 181 of file CpuContext.cpp.
 {
     return new CpuQueue(this, options);
 }
create_tensor()
ITensorV2 * create_tensor (const AclTensorDescriptor & desc, bool allocate) override virtual
Create a tensor object.
Parameters
[in] desc Descriptor to use
[in] allocate Flag to allocate tensor
Returns
A pointer to the created tensor object
Implements IContext.
Definition at line 171 of file CpuContext.cpp.
References CpuTensor::allocate(), and tensor.
 {
     CpuTensor *tensor = new CpuTensor(this, desc);
     if(tensor != nullptr && allocate)
     {
         tensor->allocate();
     }
     return tensor;
 }
The documentation for this class was generated from the following files:
src/cpu/CpuContext.h
src/cpu/CpuContext.cpp
src/cpu/operators/CpuActivation.cpp