Compute Library: ResizeAttributes Class Reference
ResizeAttributes Class Reference
Attributes are backend-agnostic parameters (in addition to the input/output tensors) of an operator.
#include <ResizeAttributes.h>
Public Member Functions
ResizeAttributes & output_width (int32_t output_width)
Set output width.
int32_t output_width () const
Get output width.
ResizeAttributes & output_height (int32_t output_height)
Set output height.
int32_t output_height () const
Get output height.
ResizeAttributes & interpolation_policy (InterpolationPolicy interpolation_policy)
Set interpolation policy.
InterpolationPolicy interpolation_policy () const
Get interpolation policy.
ResizeAttributes & sampling_policy (SamplingPolicy sampling_policy)
Set sampling policy.
SamplingPolicy sampling_policy () const
Get sampling policy.
ResizeAttributes & align_corners (bool align_corners)
Set align corners.
bool align_corners () const
Get align corners.
Detailed Description
Attributes are backend-agnostic parameters (in addition to the input/output tensors) of an operator.
Resize attributes
Definition at line 42 of file ResizeAttributes.h.
Member Function Documentation
align_corners() [1/2]
ResizeAttributes & align_corners (bool align_corners)
Set align corners.
Definition at line 77 of file ResizeAttributes.cpp.
References ResizeAttributes::align_corners().
Referenced by ClTemplateResize::get_component_code(), ClTemplateResize::get_tag_lut(), arm_compute::operator<<(), arm_compute::test::validation::TEST_CASE(), and ClComponentResize::validate().
 {
     _align_corners = align_corners;
     return *this;
 }
align_corners() [2/2]
bool align_corners () const
Get align corners.
Definition at line 83 of file ResizeAttributes.cpp.
Referenced by ResizeAttributes::align_corners().
 {
     return _align_corners;
 }
interpolation_policy() [1/2]
ResizeAttributes & interpolation_policy (InterpolationPolicy interpolation_policy)
Set interpolation policy.
Definition at line 55 of file ResizeAttributes.cpp.
References ResizeAttributes::interpolation_policy().
Referenced by ClTemplateResize::get_component_code(), ClTemplateResize::get_config_id(), ClTemplateResize::get_name(), arm_compute::operator<<(), and arm_compute::test::validation::TEST_CASE().
 {
     _interpolation_policy = interpolation_policy;
     return *this;
 }
interpolation_policy() [2/2]
InterpolationPolicy interpolation_policy () const
Get interpolation policy.
Definition at line 61 of file ResizeAttributes.cpp.
Referenced by ResizeAttributes::interpolation_policy().
 {
     return _interpolation_policy;
 }
output_height() [1/2]
ResizeAttributes & output_height (int32_t output_height)
Set output height.
Definition at line 44 of file ResizeAttributes.cpp.
References ResizeAttributes::output_height().
Referenced by arm_compute::operator<<().
 {
     _output_height = output_height;
     return *this;
 }
output_height() [2/2]
int32_t output_height () const
Get output height.
Definition at line 50 of file ResizeAttributes.cpp.
Referenced by ResizeAttributes::output_height().
 {
     return _output_height;
 }
output_width() [1/2]
ResizeAttributes & output_width (int32_t output_width)
Set output width.
Definition at line 33 of file ResizeAttributes.cpp.
References ResizeAttributes::output_width().
Referenced by arm_compute::operator<<().
 {
     _output_width = output_width;
     return *this;
 }
output_width() [2/2]
int32_t output_width () const
Get output width.
Definition at line 39 of file ResizeAttributes.cpp.
Referenced by ResizeAttributes::output_width().
 {
     return _output_width;
 }
sampling_policy() [1/2]
ResizeAttributes & sampling_policy (SamplingPolicy sampling_policy)
Set sampling policy.
Definition at line 66 of file ResizeAttributes.cpp.
References ResizeAttributes::sampling_policy().
Referenced by ClTemplateResize::get_component_code(), ClTemplateResize::get_config_id(), arm_compute::operator<<(), arm_compute::test::validation::TEST_CASE(), and ClComponentResize::validate().
 {
     _sampling_policy = sampling_policy;
     return *this;
 }
sampling_policy() [2/2]
SamplingPolicy sampling_policy () const
Get sampling policy.
Definition at line 72 of file ResizeAttributes.cpp.
Referenced by ResizeAttributes::sampling_policy().
 {
     return _sampling_policy;
 }
The documentation for this class was generated from the following files:
arm_compute/dynamic_fusion/sketch/attributes/ResizeAttributes.h
src/dynamic_fusion/sketch/attributes/ResizeAttributes.cpp