Compute Library: CpuGemmLowpMatrixAReductionKernel Class Reference
CpuGemmLowpMatrixAReductionKernel Class Reference
Kernel used to compute the row-vectors of sums of all the entries in each row of Matrix A.
#include <CpuGemmLowpMatrixReductionKernel.h>
Public Member Functions
CpuGemmLowpMatrixAReductionKernel ()=default
Default constructor.
ARM_COMPUTE_DISALLOW_COPY_ALLOW_MOVE (CpuGemmLowpMatrixAReductionKernel)
void configure (const ITensorInfo *src, ITensorInfo *dst, const GEMMLowpReductionKernelInfo &info)
Initialise the kernel's input and output.
void run_op (ITensorPack &tensors, const Window &window, const ThreadInfo &info) override
Execute the kernel on the passed window.
const char * name () const override
Name of the kernel.
Public Member Functions inherited from ICPPKernel
virtual ~ICPPKernel ()=default
Default destructor.
virtual void run (const Window &window, const ThreadInfo &info)
Execute the kernel on the passed window.
virtual void run_nd (const Window &window, const ThreadInfo &info, const Window &thread_locator)
legacy compatibility layer for implemantions which do not support thread_locator In these cases we simply narrow the interface down the legacy version
virtual size_t get_mws (const CPUInfo &platform, size_t thread_count) const
Return minimum workload size of the relevant kernel.
Public Member Functions inherited from IKernel
IKernel ()
Constructor.
virtual ~IKernel ()=default
Destructor.
virtual bool is_parallelisable () const
Indicates whether or not the kernel is parallelisable.
virtual BorderSize border_size () const
The size of the border for that kernel.
const Window & window () const
The maximum window the kernel can be executed on.
bool is_window_configured () const
Function to check if the embedded window of this kernel has been configured.
Static Public Member Functions
static Status validate (const ITensorInfo *src, const ITensorInfo *dst, const GEMMLowpReductionKernelInfo &info)
Static function to check if given info will lead to a valid configuration.
Static Public Member Functions inherited from ICpuKernel< CpuGemmLowpMatrixAReductionKernel >
static const auto * get_implementation (const SelectorType &selector, KernelSelectionType selection_type=KernelSelectionType::Supported)
Micro-kernel selector.
Additional Inherited Members
Static Public Attributes inherited from ICPPKernel
static constexpr size_t default_mws = 1
Detailed Description
Kernel used to compute the row-vectors of sums of all the entries in each row of Matrix A.
Note
This stage is needed to handle the offset of matrix product https://github.com/google/gemmlowp/blob/master/doc/low-precision.md
Definition at line 43 of file CpuGemmLowpMatrixReductionKernel.h.
Constructor & Destructor Documentation
CpuGemmLowpMatrixAReductionKernel()
CpuGemmLowpMatrixAReductionKernel () default
Default constructor.
Member Function Documentation
ARM_COMPUTE_DISALLOW_COPY_ALLOW_MOVE()
ARM_COMPUTE_DISALLOW_COPY_ALLOW_MOVE (CpuGemmLowpMatrixAReductionKernel)
configure()
void configure (const ITensorInfo * src, ITensorInfo * dst, const GEMMLowpReductionKernelInfo & info)
Initialise the kernel's input and output.
Parameters
[in] src Input tensor. Data type supported: QASYMM8/QASYMM8_SIGNED/QSYMM8/QSYMM8_PER_CHANNEL
[out] dst Output row-vector of sums of all the entries in each row of mtx_a. Data type supported: S32
[in] info Kernel metadata:
k (num_mtx_a_cols) Number of matrix A columns
is_reshaped (is_interleaved4x4) True if the matrix A has been interleaved4x4
scalar Scalar value to multiply each reduced row by.
mul_byscalar True if each reduced column must be multiplied by a scalar value.
Definition at line 71 of file CpuGemmLowpMatrixReductionKernel.cpp.
References ARM_COMPUTE_ERROR, ARM_COMPUTE_ERROR_ON_NULLPTR, ARM_COMPUTE_ERROR_THROW_ON, arm_compute::auto_init_if_empty(), arm_compute::calculate_max_window(), ITensorInfo::data_type(), ITensorInfo::dimension(), GEMMLowpReductionKernelInfo::k, GEMMLowpReductionKernelInfo::mul_by_scalar, arm_compute::QASYMM8, arm_compute::QASYMM8_SIGNED, arm_compute::QSYMM8, arm_compute::QSYMM8_PER_CHANNEL, arm_compute::S32, and GEMMLowpReductionKernelInfo::scalar.
 {
     // Perform validate step
     ARM_COMPUTE_ERROR_ON_NULLPTR(src, dst);
     ARM_COMPUTE_ERROR_THROW_ON(validate_arguments_matrix_a_reduction(src, dst, info));
     _k             = info.k;
     _scalar        = info.scalar;
     _mul_by_scalar = info.mul_by_scalar;
     switch(src->data_type())
     {
         case DataType::QASYMM8:
             _func = &CpuGemmLowpMatrixAReductionKernel::run_internal<uint8_t>;
             break;
         case DataType::QASYMM8_SIGNED:
         case DataType::QSYMM8:
         case DataType::QSYMM8_PER_CHANNEL:
             _func = &CpuGemmLowpMatrixAReductionKernel::run_internal<int8_t>;
             break;
         default:
             ARM_COMPUTE_ERROR("Unsupported data type");
     }
     // Output auto initialization if not yet initialized
     auto_init_if_empty(*dst, TensorShape(src->dimension(1)), 1, DataType::S32);
     Window win = calculate_max_window(*dst, Steps(1));
     ICpuKernel::configure(win);
 }
name()
const char * name () const override virtual
Name of the kernel.
Returns
Kernel name
Implements ICPPKernel.
Definition at line 187 of file CpuGemmLowpMatrixReductionKernel.cpp.
 {
     return "CpuGemmLowpMatrixAReductionKernel";
 }
run_op()
void run_op (ITensorPack & tensors, const Window & window, const ThreadInfo & info) override virtual
Execute the kernel on the passed window.
Warning
If is_parallelisable() returns false then the passed window must be equal to window()
Note
The window has to be a region within the window returned by the window() method
The width of the window has to be a multiple of num_elems_processed_per_iteration().
Parameters
[in] tensors A vector containing the tensors to operate on.
[in] window Region on which to execute the kernel. (Must be a region of the window returned by window())
[in] info Info about executing thread and CPU.
Reimplemented from ICPPKernel.
Definition at line 175 of file CpuGemmLowpMatrixReductionKernel.cpp.
References arm_compute::ACL_DST, arm_compute::ACL_SRC, ARM_COMPUTE_ERROR_ON_INVALID_SUBWINDOW, ARM_COMPUTE_ERROR_ON_UNCONFIGURED_KERNEL, ARM_COMPUTE_UNUSED, ITensorPack::get_const_tensor(), ITensorPack::get_tensor(), and IKernel::window().
 {
     ARM_COMPUTE_UNUSED(info);
     ARM_COMPUTE_ERROR_ON_UNCONFIGURED_KERNEL(this);
     ARM_COMPUTE_ERROR_ON_INVALID_SUBWINDOW(ICpuKernel::window(), window);
     auto src = tensors.get_const_tensor(TensorType::ACL_SRC);
     auto dst = tensors.get_tensor(TensorType::ACL_DST);
     (this->*_func)(src, dst, window);
 }
validate()
Status validate (const ITensorInfo * src, const ITensorInfo * dst, const GEMMLowpReductionKernelInfo & info) static
Static function to check if given info will lead to a valid configuration.
Similar to CpuGemmLowpMatrixAReductionKernel::configure()
Returns
a status
Definition at line 101 of file CpuGemmLowpMatrixReductionKernel.cpp.
References ARM_COMPUTE_RETURN_ON_ERROR, Window::collapse_if_possible(), Window::DimX, Window::DimY, Window::DimZ, arm_compute::execute_window_loop(), ITensor::info(), Iterator::ptr(), Window::set(), ITensorInfo::strides_in_bytes(), arm_compute::wrapper::vadd(), arm_compute::wrapper::vaddl(), arm_compute::wrapper::vdup_n(), arm_compute::wrapper::vgethigh(), arm_compute::wrapper::vgetlane(), arm_compute::wrapper::vgetlow(), arm_compute::wrapper::vloadq(), arm_compute::wrapper::vpadd(), arm_compute::wrapper::vpaddl(), IKernel::window(), and Dimensions< T >::y().
Referenced by CpuGemmLowpMatrixMultiplyCore::validate(), and NEQLSTMLayer::validate().
 {
     ARM_COMPUTE_RETURN_ON_ERROR(validate_arguments_matrix_a_reduction(src, dst, info));
     return Status{};
 }
The documentation for this class was generated from the following files:
src/cpu/kernels/CpuGemmLowpMatrixReductionKernel.h
src/cpu/kernels/CpuGemmLowpMatrixReductionKernel.cpp