Compute Library: CLNormalizationLayerKernel Class Reference
CLNormalizationLayerKernel Class Reference
Interface for the normalization layer kernel.
#include <CLNormalizationLayerKernel.h>
Public Member Functions
CLNormalizationLayerKernel ()
Constructor.
CLNormalizationLayerKernel (const CLNormalizationLayerKernel &)=delete
Prevent instances of this class from being copied (As this class contains pointers)
CLNormalizationLayerKernel & operator= (const CLNormalizationLayerKernel &)=delete
Prevent instances of this class from being copied (As this class contains pointers)
CLNormalizationLayerKernel (CLNormalizationLayerKernel &&)=default
Default Move Constructor.
CLNormalizationLayerKernel & operator= (CLNormalizationLayerKernel &&)=default
Default move assignment operator.
void configure (const ICLTensor *input, ICLTensor *output, NormalizationLayerInfo norm_info)
Set the input and output tensors.
void configure (const CLCompileContext &compile_context, const ICLTensor *input, ICLTensor *output, NormalizationLayerInfo norm_info)
Set the input and output tensors.
void run (const Window &window, cl::CommandQueue &queue) override
Enqueue the OpenCL kernel to process the given window on the passed OpenCL command queue.
BorderSize border_size () const override
The size of the border for that kernel.
Public Member Functions inherited from ICLKernel
ICLKernel ()
Constructor.
cl::Kernel & kernel ()
Returns a reference to the OpenCL kernel of this object.
CLKernelType type () const
Returns the CL kernel type.
template<typename T >
void add_1D_array_argument (unsigned int &idx, const ICLArray< T > *array, const Strides &strides, unsigned int num_dimensions, const Window &window)
Add the passed 1D array's parameters to the object's kernel's arguments starting from the index idx.
void add_1D_tensor_argument (unsigned int &idx, const ICLTensor *tensor, const Window &window)
Add the passed 1D tensor's parameters to the object's kernel's arguments starting from the index idx.
void add_1D_tensor_argument_if (bool cond, unsigned int &idx, const ICLTensor *tensor, const Window &window)
Add the passed 1D tensor's parameters to the object's kernel's arguments starting from the index idx if the condition is true.
void add_2D_tensor_argument (unsigned int &idx, const ICLTensor *tensor, const Window &window)
Add the passed 2D tensor's parameters to the object's kernel's arguments starting from the index idx.
void add_2D_tensor_argument_if (bool cond, unsigned int &idx, const ICLTensor *tensor, const Window &window)
Add the passed 2D tensor's parameters to the object's kernel's arguments starting from the index idx if the condition is true.
void add_3D_tensor_argument (unsigned int &idx, const ICLTensor *tensor, const Window &window)
Add the passed 3D tensor's parameters to the object's kernel's arguments starting from the index idx.
void add_4D_tensor_argument (unsigned int &idx, const ICLTensor *tensor, const Window &window)
Add the passed 4D tensor's parameters to the object's kernel's arguments starting from the index idx.
void add_5D_tensor_argument (unsigned int &idx, const ICLTensor *tensor, const Window &window)
Add the passed 5D tensor's parameters to the object's kernel's arguments starting from the index idx.
void add_3d_tensor_nhw_argument (unsigned int &idx, const ICLTensor *tensor)
Add the passed NHW 3D tensor's parameters to the object's kernel's arguments by passing strides, dimensions and the offset to the first valid element in bytes.
void add_4d_tensor_nhwc_argument (unsigned int &idx, const ICLTensor *tensor)
Add the passed NHWC 4D tensor's parameters to the object's kernel's arguments by passing strides, dimensions and the offset to the first valid element in bytes.
virtual void run_op (ITensorPack &tensors, const Window &window, cl::CommandQueue &queue)
Enqueue the OpenCL kernel to process the given window on the passed OpenCL command queue.
template<typename T >
void add_argument (unsigned int &idx, T value)
Add the passed parameters to the object's kernel's arguments starting from the index idx.
void set_lws_hint (const cl::NDRange &lws_hint)
Set the Local-Workgroup-Size hint.
cl::NDRange lws_hint () const
Return the Local-Workgroup-Size hint.
void set_wbsm_hint (const cl_int &wbsm_hint)
Set the workgroup batch size modifier hint.
cl_int wbsm_hint () const
Return the workgroup batch size modifier hint.
const std::string & config_id () const
Get the configuration ID.
void set_target (GPUTarget target)
Set the targeted GPU architecture.
void set_target (cl::Device &device)
Set the targeted GPU architecture according to the CL device.
GPUTarget get_target () const
Get the targeted GPU architecture.
size_t get_max_workgroup_size ()
Get the maximum workgroup size for the device the CLKernelLibrary uses.
template<unsigned int dimension_size>
void add_tensor_argument (unsigned &idx, const ICLTensor *tensor, const Window &window)
template<typename T , unsigned int dimension_size>
void add_array_argument (unsigned &idx, const ICLArray< T > *array, const Strides &strides, unsigned int num_dimensions, const Window &window)
Add the passed array's parameters to the object's kernel's arguments starting from the index idx.
Public Member Functions inherited from IKernel
IKernel ()
Constructor.
virtual ~IKernel ()=default
Destructor.
virtual bool is_parallelisable () const
Indicates whether or not the kernel is parallelisable.
const Window & window () const
The maximum window the kernel can be executed on.
bool is_window_configured () const
Function to check if the embedded window of this kernel has been configured.
Static Public Member Functions
static Status validate (const ITensorInfo *input, const ITensorInfo *output, NormalizationLayerInfo norm_info)
Static function to check if given info will lead to a valid configuration of CLNormalizationLayerKernel.
Static Public Member Functions inherited from ICLKernel
static constexpr unsigned int num_arguments_per_3d_tensor_nhw ()
Returns the number of arguments enqueued per NHW 3D Tensor object.
static constexpr unsigned int num_arguments_per_4d_tensor_nhwc ()
Returns the number of arguments enqueued per NHWC 4D Tensor object.
static constexpr unsigned int num_arguments_per_1D_array ()
Returns the number of arguments enqueued per 1D array object.
static constexpr unsigned int num_arguments_per_1D_tensor ()
Returns the number of arguments enqueued per 1D tensor object.
static constexpr unsigned int num_arguments_per_2D_tensor ()
Returns the number of arguments enqueued per 2D tensor object.
static constexpr unsigned int num_arguments_per_3D_tensor ()
Returns the number of arguments enqueued per 3D tensor object.
static constexpr unsigned int num_arguments_per_4D_tensor ()
Returns the number of arguments enqueued per 4D tensor object.
static cl::NDRange gws_from_window (const Window &window)
Get the global work size given an execution window.
Detailed Description
Interface for the normalization layer kernel.
Definition at line 35 of file CLNormalizationLayerKernel.h.
Constructor & Destructor Documentation
CLNormalizationLayerKernel() [1/3]
CLNormalizationLayerKernel ()
Constructor.
Definition at line 124 of file CLNormalizationLayerKernel.cpp.
References arm_compute::ELEMENTWISE.
     : _input(nullptr), _output(nullptr), _border_size(0), _is_norm_across_width(false)
 {
     _type = CLKernelType::ELEMENTWISE;
 }
CLNormalizationLayerKernel() [2/3]
CLNormalizationLayerKernel (const CLNormalizationLayerKernel &) delete
Prevent instances of this class from being copied (As this class contains pointers)
CLNormalizationLayerKernel() [3/3]
CLNormalizationLayerKernel (CLNormalizationLayerKernel &&) default
Default Move Constructor.
Member Function Documentation
border_size()
BorderSize border_size () const override virtual
The size of the border for that kernel.
Returns
The width in number of elements of the border.
Reimplemented from IKernel.
Definition at line 130 of file CLNormalizationLayerKernel.cpp.
 {
     return _border_size;
 }
configure() [1/2]
void configure (const ICLTensor * input, ICLTensor * output, NormalizationLayerInfo norm_info)
Set the input and output tensors.
Parameters
[in] input Source tensor. 3 lower dims represent a single input with dimensions [width, height, IFM], and an optional 4th dimension for batch of inputs. Data types supported: F16/F32. Data layouts supported: NCHW/NHWC.
[out] output Destination tensor. Output will have the same number of dimensions as input. Data types supported: same as input. Data layouts supported: same as input.
[in] norm_info Normalization layer information like the normalization type, normalization size and other parameters.
Definition at line 135 of file CLNormalizationLayerKernel.cpp.
References CLKernelLibrary::get().
 {
     configure(CLKernelLibrary::get().get_compile_context(), input, output, norm_info);
 }
configure() [2/2]
void configure (const CLCompileContext & compile_context, const ICLTensor * input, ICLTensor * output, NormalizationLayerInfo norm_info)
Set the input and output tensors.
Parameters
[in] compile_context The compile context to be used.
[in] input Source tensor. 3 lower dims represent a single input with dimensions [width, height, IFM], and an optional 4th dimension for batch of inputs. Data types supported: F16/F32. Data layouts supported: NCHW/NHWC.
[out] output Destination tensor. Output will have the same number of dimensions as input. Data types supported: same as input. Data layouts supported: same as input.
[in] norm_info Normalization layer information like the normalization type, normalization size and other parameters.
Definition at line 140 of file CLNormalizationLayerKernel.cpp.
References CLBuildOptions::add_option(), CLBuildOptions::add_option_if(), arm_compute::adjust_vec_size(), ARM_COMPUTE_ERROR_ON, ARM_COMPUTE_ERROR_ON_NULLPTR, ARM_COMPUTE_ERROR_THROW_ON, NormalizationLayerInfo::beta(), arm_compute::create_kernel(), ITensorInfo::data_layout(), ITensorInfo::data_type(), ITensorInfo::dimension(), ITensorInfo::element_size(), arm_compute::float_to_string_with_full_precision(), arm_compute::get_cl_type_from_data_type(), arm_compute::get_normalization_dimension_index(), arm_compute::get_padding_info(), arm_compute::has_padding_changed(), arm_compute::IN_MAP_2D, ITensor::info(), arm_compute::test::validation::input, NormalizationLayerInfo::is_cross_map(), NormalizationLayerInfo::is_in_map(), NormalizationLayerInfo::kappa(), kernel_name, arm_compute::lower_string(), arm_compute::NCHW, arm_compute::NHWC, NormalizationLayerInfo::norm_size(), CLBuildOptions::options(), NormalizationLayerInfo::scale_coeff(), arm_compute::string_from_data_layout(), arm_compute::string_from_data_type(), arm_compute::support::cpp11::to_string(), type, NormalizationLayerInfo::type(), arm_compute::cpu::kernels::validate_and_configure_window(), and arm_compute::cpu::kernels::validate_arguments().
 {
     ARM_COMPUTE_ERROR_ON_NULLPTR(input, output);
     auto padding_info = get_padding_info({ input, output });
     // Perform validation step
     ARM_COMPUTE_ERROR_THROW_ON(validate_arguments(input->info(), output->info(), norm_info));
     auto win_config = validate_and_configure_window(input->info(), output->info(), norm_info);
     ARM_COMPUTE_ERROR_THROW_ON(win_config.first);
     _input  = input;
     _output = output;
     const DataLayout data_layout          = input->info()->data_layout();
     unsigned int     vec_size_x           = adjust_vec_size(max_cl_vector_width / input->info()->element_size(), input->info()->dimension(0));
     int              vec_size_x_leftovers = input->info()->dimension(0) % vec_size_x;
     if(norm_info.is_cross_map() && data_layout == DataLayout::NHWC)
     {
         vec_size_x           = 1;
         vec_size_x_leftovers = 0;
     }
     if(data_layout == DataLayout::NCHW)
     {
         const unsigned int norm_idx    = get_normalization_dimension_index(data_layout, norm_info);
         _is_norm_across_width          = norm_idx == 0;
         const unsigned int norm_radius = norm_info.norm_size() / 2;
         // Border / padding calculation:
         // For NCHW no border handling is impelmeneted in the kernel in the x axis.
         // This means the x axis is fully-padded depending on vec_size_x and norm_size
         // E.G. for input x dimension = 3, norm_size = 3 (radius = 1), vec_size_x = 2 ('#' is element 'p' is padding):
         // In : |p|#|#|#|p|p|
         // Out:   |#|#|#|p|
         // The output has 1 right padding because of the vec_size_x.
         // The input has 1 left padding because radius = 1.
         // The input has 2 right padding because of radius = 1 AND the extra output padding
         const unsigned int border_width_left  = _is_norm_across_width ? norm_radius : 0;
         const unsigned int border_width_right = _is_norm_across_width ? norm_radius + (vec_size_x - input->info()->dimension(0) % vec_size_x) : 0;
         _border_size                          = BorderSize(0, border_width_right, 0, border_width_left);
     }
     const bool is_in_map_2D = (norm_info.type() == NormType::IN_MAP_2D);
     // Set build options
     CLBuildOptions build_opts;
     build_opts.add_option(("-DDATA_TYPE=" + get_cl_type_from_data_type(input->info()->data_type())));
     build_opts.add_option(("-DCOEFF=" + float_to_string_with_full_precision(norm_info.scale_coeff())));
     build_opts.add_option(("-DBETA=" + float_to_string_with_full_precision(norm_info.beta())));
     build_opts.add_option(("-DKAPPA=" + float_to_string_with_full_precision(norm_info.kappa())));
     build_opts.add_option(("-DVEC_SIZE=" + support::cpp11::to_string(vec_size_x)));
     build_opts.add_option(("-DVEC_SIZE_LEFTOVER=" + support::cpp11::to_string(vec_size_x_leftovers)));
     build_opts.add_option(("-DRADIUS=" + support::cpp11::to_string(norm_info.norm_size() / 2)));
     build_opts.add_option(("-DNUM_SLICES=" + support::cpp11::to_string(input->info()->dimension(2))));
     build_opts.add_option_if(is_in_map_2D, "-DIN_MAP_2D");
     build_opts.add_option_if(norm_info.is_in_map() || (data_layout == DataLayout::NHWC && norm_info.is_cross_map()), "-DWIDTH_SIZE=" + support::cpp11::to_string(input->info()->dimension(0)));
     build_opts.add_option_if(norm_info.is_in_map() && data_layout == DataLayout::NHWC, "-DDIM1_SIZE=" + support::cpp11::to_string(input->info()->dimension(1)));
     // Create kernel
     std::string kernel_name;
     if(norm_info.is_in_map())
     {
         kernel_name = "normalization_layer_in_map_" + lower_string(string_from_data_layout(data_layout));
     }
     else
     {
         kernel_name = "normalization_layer_cross_map_" + lower_string(string_from_data_layout(data_layout));
     }
     _kernel = create_kernel(compile_context, kernel_name, build_opts.options());
     // Configure kernel window
     ICLKernel::configure_internal(win_config.second);
     // Set config_id for enabling LWS tuning
     _config_id = "normalization_layer_";
     _config_id += lower_string(string_from_data_type(input->info()->data_type()));
     _config_id += "_";
     _config_id += support::cpp11::to_string(static_cast<std::underlying_type<NormType>::type>(norm_info.type()));
     _config_id += "_";
     _config_id += support::cpp11::to_string(norm_info.norm_size());
     _config_id += "_";
     _config_id += support::cpp11::to_string(input->info()->dimension(0));
     _config_id += "_";
     _config_id += support::cpp11::to_string(input->info()->dimension(1));
     if(data_layout == DataLayout::NHWC)
     {
         ARM_COMPUTE_ERROR_ON(has_padding_changed(padding_info));
     }
 }
operator=() [1/2]
CLNormalizationLayerKernel& operator= (const CLNormalizationLayerKernel &) delete
Prevent instances of this class from being copied (As this class contains pointers)
operator=() [2/2]
CLNormalizationLayerKernel& operator= (CLNormalizationLayerKernel &&) default
Default move assignment operator.
run()
void run (const Window & window, cl::CommandQueue & queue) override virtual
Enqueue the OpenCL kernel to process the given window on the passed OpenCL command queue.
Note
The queue is not flushed by this method, and therefore the kernel will not have been executed by the time this method returns.
Parameters
[in] window Region on which to execute the kernel. (Must be a valid region of the window returned by window()).
[in,out] queue Command queue on which to enqueue the kernel.
Reimplemented from ICLKernel.
Definition at line 237 of file CLNormalizationLayerKernel.cpp.
References ICLKernel::add_3D_tensor_argument(), ARM_COMPUTE_ERROR_ON_INVALID_SUBWINDOW, ARM_COMPUTE_ERROR_ON_UNCONFIGURED_KERNEL, Window::collapse_if_possible(), Window::DimZ, arm_compute::enqueue(), Window::first_slice_window_3D(), ICLKernel::lws_hint(), arm_compute::test::validation::reference::slice(), Window::slide_window_slice_3D(), and IKernel::window().
 {
     ARM_COMPUTE_ERROR_ON_UNCONFIGURED_KERNEL(this);
     ARM_COMPUTE_ERROR_ON_INVALID_SUBWINDOW(IKernel::window(), window);
     const int collapsed_dimension = _is_norm_across_width ? Window::DimZ : 4;
     Window    window_collapsed    = window.collapse_if_possible(ICLKernel::window(), collapsed_dimension);
     Window    slice               = window_collapsed.first_slice_window_3D();
     do
     {
         unsigned int idx = 0;
         add_3D_tensor_argument(idx, _input, slice);
         add_3D_tensor_argument(idx, _output, slice);
         enqueue(queue, *this, slice, lws_hint());
     }
     while(window_collapsed.slide_window_slice_3D(slice));
 }
validate()
Status validate (const ITensorInfo * input, const ITensorInfo * output, NormalizationLayerInfo norm_info) static
Static function to check if given info will lead to a valid configuration of CLNormalizationLayerKernel.
Parameters
[in] input Source tensor. 3 lower dims represent a single input with dimensions [width, height, IFM], and an optional 4th dimension for batch of inputs. Data types supported: F16/F32. Data layouts supported: NCHW/NHWC.
[in] output Destination tensor. Output will have the same number of dimensions as input. Data types supported: same as input. Data layouts supported: same as input.
[in] norm_info Normalization layer information like the normalization type, normalization size and other parameters.
Returns
a status
Definition at line 229 of file CLNormalizationLayerKernel.cpp.
References ARM_COMPUTE_RETURN_ON_ERROR, ICloneable< T >::clone(), arm_compute::cpu::kernels::validate_and_configure_window(), and arm_compute::cpu::kernels::validate_arguments().
Referenced by CLNormalizationLayer::validate().
 {
     ARM_COMPUTE_RETURN_ON_ERROR(validate_arguments(input, output, norm_info));
     ARM_COMPUTE_RETURN_ON_ERROR(validate_and_configure_window(input->clone().get(), output->clone().get(), norm_info).first);
     return Status{};
 }
The documentation for this class was generated from the following files:
src/core/CL/kernels/CLNormalizationLayerKernel.h
src/core/CL/kernels/CLNormalizationLayerKernel.cpp