Compute Library: arm_compute::test::validation::detail Namespace Reference
arm_compute::test::validation::detail Namespace Reference
Functions
template<>
void configure_conv_function< NEGEMMConv2d, Tensor > (NEGEMMConv2d &func, Tensor *src, const Tensor *weights, const Tensor *bias, Tensor *dst, const PadStrideInfo &info, const WeightsInfo &weights_info, const Size2D &dilation, const ActivationLayerInfo &act_info, unsigned int num_groups)
Function Documentation
configure_conv_function< NEGEMMConv2d, Tensor >()
void arm_compute::test::validation::detail::configure_conv_function< NEGEMMConv2d, Tensor > (NEGEMMConv2d & func, Tensor * src, const Tensor * weights, const Tensor * bias, Tensor * dst, const PadStrideInfo & info, const WeightsInfo & weights_info, const Size2D & dilation, const ActivationLayerInfo & act_info, unsigned int num_groups)
Definition at line 56 of file ConvolutionLayer.cpp.
References abs_tolerance_f32(), ARM_COMPUTE_UNUSED, ActivationLayerInfo::BOUNDED_RELU, arm_compute::test::validation::conv_info, arm_compute::F16, arm_compute::F32, arm_compute::test::framework::dataset::make(), arm_compute::NEON, arm_compute::test::validation::num_groups, arm_compute::QASYMM8, arm_compute::test::validation::QuantizationData, ActivationLayerInfo::RELU, arm_compute::test::validation::TEST_SUITE(), arm_compute::test::validation::tolerance_num, and tolerance_num_f16.
 {
     ARM_COMPUTE_UNUSED(weights_info);
     Conv2dInfo conv_info(info, dilation, act_info, false, num_groups);
     func.configure(src, weights, bias, dst, conv_info);
 }