Compute Library: brelu< T, S > Struct Template Reference
brelu< T, S > Struct Template Reference
Bounded RELU activation object.
#include <NEActivationFunctionDetail.h>
Public Types
using ExactType = typename wrapper::traits::neon_vector< T, S >::type
SIMD vector type.
using ExactTagType = typename wrapper::traits::neon_vector< T, S >::tag_type
SIMD vector tag type.
Public Member Functions
brelu (ActivationLayerInfo act_info)
Construct a bounded RELU activation object.
void operator() (ExactType &vval)
Run activation function.
void operator() (T &val)
Run activation function.
Data Fields
const T alpha
const ExactType vzero
Scalar alpha.
const ExactType valpha
Vector of zeroes.
Detailed Description
template<typename T, int S>
struct arm_compute::detail::brelu< T, S >
Bounded RELU activation object.
Definition at line 229 of file NEActivationFunctionDetail.h.
Member Typedef Documentation
ExactTagType
using ExactTagType = typename wrapper::traits::neon_vector<T, S>::tag_type
SIMD vector tag type.
Definition at line 234 of file NEActivationFunctionDetail.h.
ExactType
using ExactType = typename wrapper::traits::neon_vector<T, S>::type
SIMD vector type.
Definition at line 232 of file NEActivationFunctionDetail.h.
Constructor & Destructor Documentation
brelu()
brelu (ActivationLayerInfo act_info) inline explicit
Construct a bounded RELU activation object.
Parameters
[in] act_info Activation layer information.
Definition at line 240 of file NEActivationFunctionDetail.h.
References arm_compute::test::validation::act_info, and arm_compute::wrapper::vdup_n().
         : alpha(act_info.a()),
           vzero(wrapper::vdup_n(static_cast<T>(0), ExactTagType{})),
           valpha(wrapper::vdup_n(static_cast<T>(act_info.a()), ExactTagType{}))
     {
     }
Member Function Documentation
operator()() [1/2]
void operator() (ExactType & vval) inline
Run activation function.
Parameters
[in] vval Vector of values.
Definition at line 251 of file NEActivationFunctionDetail.h.
References arm_compute::wrapper::vmax(), and arm_compute::wrapper::vmin().
     {
         vval = wrapper::vmin(valpha, wrapper::vmax(vzero, vval));
     }
operator()() [2/2]
void operator() (T & val) inline
Run activation function.
Parameters
[in] val Scalar value.
Definition at line 260 of file NEActivationFunctionDetail.h.
     {
         val = std::min(alpha, std::max(static_cast<T>(0), val));
     }
Field Documentation
alpha
const T alpha
Definition at line 265 of file NEActivationFunctionDetail.h.
valpha
const ExactType valpha
Vector of zeroes.
Definition at line 267 of file NEActivationFunctionDetail.h.
vzero
const ExactType vzero
Scalar alpha.
Definition at line 266 of file NEActivationFunctionDetail.h.
The documentation for this struct was generated from the following file:
src/core/NEON/kernels/detail/NEActivationFunctionDetail.h