Compute Library: arm_compute/AclOpenClExt.h File Reference
AclOpenClExt.h File Reference
#include "arm_compute/AclTypes.h"
#include "include/CL/cl.h"
Macros
#define CL_TARGET_OPENCL_VERSION 300
#define CL_USE_DEPRECATED_OPENCL_1_1_APIS
#define CL_USE_DEPRECATED_OPENCL_1_2_APIS
Functions
AclStatus AclGetClContext (AclContext ctx, cl_context *opencl_context)
Extract the underlying OpenCL context used by a given Compute Library context object.
AclStatus AclGetClDevice (AclContext ctx, cl_device_id *opencl_device)
Extract the underlying OpenCL device id used by a given Compute Library context object.
AclStatus AclSetClContext (AclContext ctx, cl_context opencl_context)
Set the underlying OpenCL context to be used by a given Compute Library context object.
AclStatus AclGetClQueue (AclQueue queue, cl_command_queue *opencl_queue)
Extract the underlying OpenCL queue used by a given Compute Library queue object.
AclStatus AclSetClQueue (AclQueue queue, cl_command_queue opencl_queue)
Set the underlying OpenCL queue to be used by a given Compute Library queue object.
AclStatus AclGetClMem (AclTensor tensor, cl_mem *opencl_mem)
Extract the underlying OpenCL memory object by a given Compute Library tensor object.
Macro Definition Documentation
CL_TARGET_OPENCL_VERSION
#define CL_TARGET_OPENCL_VERSION 300
Definition at line 30 of file AclOpenClExt.h.
CL_USE_DEPRECATED_OPENCL_1_1_APIS
#define CL_USE_DEPRECATED_OPENCL_1_1_APIS
Definition at line 31 of file AclOpenClExt.h.
CL_USE_DEPRECATED_OPENCL_1_2_APIS
#define CL_USE_DEPRECATED_OPENCL_1_2_APIS
Definition at line 32 of file AclOpenClExt.h.
Function Documentation
AclGetClContext()
AclStatus AclGetClContext (AclContext ctx, cl_context * opencl_context)
Extract the underlying OpenCL context used by a given Compute Library context object.
Note
AclContext should be of an OpenCL backend target
Parameters
[in] ctx A valid non-zero context
[out] opencl_context Underlying OpenCL context used
Returns
Status code
Definition at line 35 of file AclOpenClExt.cpp.
 {
     using namespace arm_compute;
     IContext *ctx = get_internal(external_ctx);
     if(detail::validate_internal_context(ctx) != StatusCode::Success)
     {
         return AclStatus::AclInvalidArgument;
     }
     if(ctx->type() != Target::GpuOcl)
     {
         return AclStatus::AclInvalidTarget;
     }
     if(opencl_context == nullptr)
     {
         return AclStatus::AclInvalidArgument;
     }
     *opencl_context = utils::cast::polymorphic_downcast<arm_compute::gpu::opencl::ClContext *>(ctx)->cl_ctx().get();
     return AclStatus::AclSuccess;
 }
References AclInvalidArgument, AclInvalidTarget, AclSuccess, arm_compute::get_internal(), arm_compute::GpuOcl, arm_compute::Success, IContext::type(), and arm_compute::detail::validate_internal_context().
Referenced by arm_compute::test::validation::TEST_CASE().
AclGetClDevice()
AclStatus AclGetClDevice (AclContext ctx, cl_device_id * opencl_device)
Extract the underlying OpenCL device id used by a given Compute Library context object.
Note
AclContext should be of an OpenCL backend target
Parameters
[in] ctx A valid non-zero context
[out] opencl_device Underlying OpenCL device used
Returns
Status code
Definition at line 89 of file AclOpenClExt.cpp.
 {
     using namespace arm_compute;
     IContext *ctx = get_internal(external_ctx);
     if(detail::validate_internal_context(ctx) != StatusCode::Success)
     {
         return AclStatus::AclInvalidArgument;
     }
     if(ctx->type() != Target::GpuOcl)
     {
         return AclStatus::AclInvalidTarget;
     }
     if(opencl_device == nullptr)
     {
         return AclStatus::AclInvalidArgument;
     }
     *opencl_device = utils::cast::polymorphic_downcast<arm_compute::gpu::opencl::ClContext *>(ctx)->cl_dev().get();
     return AclStatus::AclSuccess;
 }
References AclInvalidArgument, AclInvalidTarget, AclSuccess, arm_compute::get_internal(), arm_compute::GpuOcl, arm_compute::Success, IContext::type(), and arm_compute::detail::validate_internal_context().
Referenced by arm_compute::test::validation::TEST_CASE().
AclGetClMem()
AclStatus AclGetClMem (AclTensor tensor, cl_mem * opencl_mem)
Extract the underlying OpenCL memory object by a given Compute Library tensor object.
Parameters
[in] tensor A valid non-zero tensor
[out] opencl_mem Underlyig OpenCL memory object
Returns
Status code
Definition at line 163 of file AclOpenClExt.cpp.
 {
     using namespace arm_compute;
     ITensorV2 *tensor = get_internal(external_tensor);
     if(detail::validate_internal_tensor(tensor) != StatusCode::Success)
     {
         return AclStatus::AclInvalidArgument;
     }
     if(tensor->header.ctx->type() != Target::GpuOcl)
     {
         return AclStatus::AclInvalidTarget;
     }
     if(opencl_mem == nullptr)
     {
         return AclStatus::AclInvalidArgument;
     }
     auto cl_tensor = utils::cast::polymorphic_downcast<arm_compute::ICLTensor *>(tensor->tensor());
     *opencl_mem    = cl_tensor->cl_buffer().get();
     return AclStatus::AclSuccess;
 }
References AclInvalidArgument, AclInvalidTarget, AclSuccess, arm_compute::get_internal(), arm_compute::GpuOcl, arm_compute::Success, tensor, and arm_compute::detail::validate_internal_tensor().
AclGetClQueue()
AclStatus AclGetClQueue (AclQueue queue, cl_command_queue * opencl_queue)
Extract the underlying OpenCL queue used by a given Compute Library queue object.
Note
AclQueue should be of an OpenCL backend target
AclQueue refcount should be 0, meaning not used by other objects
Parameters
[in] queue A valid non-zero queue
[out] opencl_queue Underlying OpenCL queue used
Returns
Status code
Definition at line 114 of file AclOpenClExt.cpp.
 {
     using namespace arm_compute;
     IQueue *queue = get_internal(external_queue);
     if(detail::validate_internal_queue(queue) != StatusCode::Success)
     {
         return AclStatus::AclInvalidArgument;
     }
     if(queue->header.ctx->type() != Target::GpuOcl)
     {
         return AclStatus::AclInvalidTarget;
     }
     if(opencl_queue == nullptr)
     {
         return AclStatus::AclInvalidArgument;
     }
     *opencl_queue = utils::cast::polymorphic_downcast<arm_compute::gpu::opencl::ClQueue *>(queue)->cl_queue().get();
     return AclStatus::AclSuccess;
 }
References AclInvalidArgument, AclInvalidTarget, AclSuccess, Header::ctx, arm_compute::get_internal(), arm_compute::GpuOcl, AclQueue_::header, arm_compute::Success, IContext::type(), and arm_compute::detail::validate_internal_queue().
AclSetClContext()
AclStatus AclSetClContext (AclContext ctx, cl_context opencl_context)
Set the underlying OpenCL context to be used by a given Compute Library context object.
Note
AclContext should be of an OpenCL backend target
Parameters
[in] ctx A valid non-zero context object
[out] opencl_context Underlying OpenCL context to be used
Returns
Status code
Definition at line 60 of file AclOpenClExt.cpp.
 {
     using namespace arm_compute;
     IContext *ctx = get_internal(external_ctx);
     if(detail::validate_internal_context(ctx) != StatusCode::Success)
     {
         return AclStatus::AclInvalidArgument;
     }
     if(ctx->type() != Target::GpuOcl)
     {
         return AclStatus::AclInvalidTarget;
     }
     if(ctx->refcount() != 0)
     {
         return AclStatus::AclUnsupportedConfig;
     }
     auto cl_ctx = utils::cast::polymorphic_downcast<arm_compute::gpu::opencl::ClContext *>(ctx);
     if(!cl_ctx->set_cl_ctx(::cl::Context(opencl_context)))
     {
         return AclStatus::AclRuntimeError;
     }
     return AclStatus::AclSuccess;
 }
References AclInvalidArgument, AclInvalidTarget, AclRuntimeError, AclSuccess, AclUnsupportedConfig, arm_compute::get_internal(), arm_compute::GpuOcl, IContext::refcount(), arm_compute::Success, IContext::type(), and arm_compute::detail::validate_internal_context().
AclSetClQueue()
AclStatus AclSetClQueue (AclQueue queue, cl_command_queue opencl_queue)
Set the underlying OpenCL queue to be used by a given Compute Library queue object.
Note
AclQueue should be of an OpenCL backend target
opecl_queue needs to be created from the same context that the AclContext that the queue will use
Parameters
[in] queue A valid non-zero queue object
[out] opencl_queue Underlying OpenCL queue to be used
Returns
Status code
Definition at line 139 of file AclOpenClExt.cpp.
 {
     using namespace arm_compute;
     IQueue *queue = get_internal(external_queue);
     if(detail::validate_internal_queue(queue) != StatusCode::Success)
     {
         return AclStatus::AclInvalidArgument;
     }
     if(queue->header.ctx->type() != Target::GpuOcl)
     {
         return AclStatus::AclInvalidTarget;
     }
     auto cl_queue = utils::cast::polymorphic_downcast<arm_compute::gpu::opencl::ClQueue *>(queue);
     if(!cl_queue->set_cl_queue(::cl::CommandQueue(opencl_queue)))
     {
         return AclStatus::AclRuntimeError;
     }
     return AclStatus::AclSuccess;
 }
References AclInvalidArgument, AclInvalidTarget, AclRuntimeError, AclSuccess, Header::ctx, arm_compute::get_internal(), arm_compute::GpuOcl, AclQueue_::header, arm_compute::Success, IContext::type(), and arm_compute::detail::validate_internal_queue().