Compute Library: PostOpCLKernelUtils Class Reference
PostOpCLKernelUtils Class Reference final
Manage validation, building and configurations of PostOp CL kernels.
#include <CLUtils.h>
Public Types
using NamePostfix = std::string
CL kernel name postfix for post ops.
using Slots = std::vector< unsigned int >
CL kernels that supports post ops assign each post op to a 'slot', in accordance with the postfix For example, for a kernel with postfix '_act_prelu_eltwiseadd', there are 3 slots slot 1: (unary) activation, slot 2: pRelu, slot 3: elementwise addition.
using Config = std::map< PostOpTypeSequence, std::tuple< NamePostfix, Slots > >
Public Member Functions
PostOpCLKernelUtils (const Config &config)
bool is_post_op_sequence_supported (const PostOpList< ITensorInfo * > &post_ops) const
Check if the post op sequence is supported in the current configuration.
void set_post_ops_cl_build_options (CLBuildOptions &built_opts, const PostOpList< ITensorInfo * > &post_ops) const
Helper function to set PostOp related build options.
void set_post_ops_cl_kernel_name (std::string &kernel_name, const PostOpList< ITensorInfo * > &post_ops) const
Helper function to set PostOp kernel name.
Static Public Member Functions
static bool are_post_op_shapes_compliant (const ITensorInfo *dst, const experimental::PostOpList< ITensorInfo * > &post_ops)
Check if post op argument tensor shapes are compliant All post ops must not alter the shape of the original dst tensor (even after broadcasting)
Detailed Description
Manage validation, building and configurations of PostOp CL kernels.
Definition at line 85 of file CLUtils.h.
Member Typedef Documentation
Config
using Config = std::map<PostOpTypeSequence, std::tuple<NamePostfix, Slots> >
Definition at line 106 of file CLUtils.h.
NamePostfix
using NamePostfix = std::string
CL kernel name postfix for post ops.
Definition at line 89 of file CLUtils.h.
Slots
using Slots = std::vector<unsigned int>
CL kernels that supports post ops assign each post op to a 'slot', in accordance with the postfix For example, for a kernel with postfix '_act_prelu_eltwiseadd', there are 3 slots slot 1: (unary) activation, slot 2: pRelu, slot 3: elementwise addition.
Some kernels may allow some slots to be optional, to support multiple combinations of post op sequences. In such cases, we need to explicitly set up a mapping between each post op and the slots for that kernel. For example, suppose we have 2 kernels with postfixes: _eltwiseadd_prelu, _act_eltwiseadd_act_prelu, where the activations in the second kernel are optional. Say we want to support an eltwise addition, followed by a prelu (sequence { eltwiseadd, prelu }). Now we can choose which one of the 2 kernels to use, since they both support this post op sequence. We can either:
assign the elementwise to slot 1 and prelu to slot 2 of kernel 1 { { Eltwise_Add, PRelu } -> {"_eltwise_act", {1, 2} } } or
assign the elementwise to slot 2 and prelu to slot 4 of kernel 1 { { Eltwise_Add, PRelu } -> {"_act_eltwiseadd_act_prelu", {2, 4} } }
Definition at line 105 of file CLUtils.h.
Constructor & Destructor Documentation
PostOpCLKernelUtils()
PostOpCLKernelUtils (const Config & config) explicit
Definition at line 119 of file CLUtils.cpp.
     : _supported_config(supported_config)
 {
     ARM_COMPUTE_ERROR_ON_MSG(supported_config.empty(), "Empty PostOp CL kernel support configuration is not allowed");
     for(auto it = _supported_config.begin(); it != _supported_config.end(); ++it)
     {
         auto post_op_sequence = it->first;
         auto post_op_slots    = std::get<1>(it->second);
         ARM_COMPUTE_ERROR_ON_MSG(post_op_sequence.size() != post_op_slots.size(), "The number of PostOps must be the same as that of the assigned slots");
     }
 }
References ARM_COMPUTE_ERROR_ON_MSG.
Member Function Documentation
are_post_op_shapes_compliant()
bool are_post_op_shapes_compliant (const ITensorInfo * dst, const experimental::PostOpList< ITensorInfo * > & post_ops) static
Check if post op argument tensor shapes are compliant All post ops must not alter the shape of the original dst tensor (even after broadcasting)
Parameters
[in] dst Dst tensor to apply the post ops to
[in] post_ops Post ops
Returns
true if shapes are compliant and false otherwise
Definition at line 131 of file CLUtils.cpp.
 {
     for(const auto &op : post_ops.get_list())
     {
         for(const auto &tensor : op->arguments())
         {
             const TensorShape &out_shape = TensorShape::broadcast_shape(dst->tensor_shape(), (*tensor)->tensor_shape());
             // All post ops must be elementwise and must not alter the shape of the original dst tensor after broadcasting
             if(detail::have_different_dimensions(out_shape, dst->tensor_shape(), 0))
             {
                 return false;
             }
             // NOTE: Kernel limitation: currently only the following broadcasting types are supported:
             //  1. Post op arg is scalar, broadcast in both first and second dims
             //  2. Post op arg is of shape: second dim=1, first dim=N, broadcast only in second dim
             //  This means this case: Post op arg is of shape: second dim=M, first dim=1, broadcast only in first dim, is NOT supported
             if(dst->dimension(0) > 1 && dst->dimension(1) > 1 && (*tensor)->dimension(0) == 1 && (*tensor)->dimension(1) > 1)
             {
                 return false;
             }
         }
     }
     return true;
 }
References TensorShape::broadcast_shape(), arm_compute::test::validation::dst, arm_compute::detail::have_different_dimensions(), arm_compute::test::validation::post_ops, and tensor.
is_post_op_sequence_supported()
bool is_post_op_sequence_supported (const PostOpList< ITensorInfo * > & post_ops) const
Check if the post op sequence is supported in the current configuration.
Parameters
[in] post_ops Post ops
Returns
true if the post op sequence is supported and false otherwise
Definition at line 156 of file CLUtils.cpp.
 {
     if(post_ops.size() == 0)
     {
         return true; // Always support cases where no post op is specified
     }
     const auto post_op_sequence = get_post_op_sequence(post_ops);
     return _supported_config.find(post_op_sequence) != _supported_config.end();
 }
References arm_compute::experimental::get_post_op_sequence(), and arm_compute::test::validation::post_ops.
set_post_ops_cl_build_options()
void set_post_ops_cl_build_options (CLBuildOptions & built_opts, const PostOpList< ITensorInfo * > & post_ops) const
Helper function to set PostOp related build options.
Note
Convention
Each post op "slot" is prefixed with "P<slot number>", followed by the usual parameters for that post op. E.g. If the first slot is an activation, we need to pass 3 definitions in this way: -P1_ACTIVATION_TYPE=... -P1_ACTIVATION_A_VAL=... -P1_ACTIVATION_B_VAL=...
For multi-ary post ops, to pass the position of the previous op's dest tensor, we append "_X_POS_<pos>" to the post op type. E.g. for a single post op add(dst, x), where dst is the result of the main op. In this case, the position of the previous op's dest is 0, so we pass -P1_ELTWISE_OP=ADD_X_POS_0
Parameters
[out] built_opts OpenCL kernel build options
[in] post_ops Post ops
Definition at line 167 of file CLUtils.cpp.
 {
     const auto post_op_sequence = get_post_op_sequence(post_ops);
     const auto slots            = std::get<1>(_supported_config.at(post_op_sequence));
     for(size_t post_op_id = 0; post_op_id < post_ops.size(); ++post_op_id)
     {
         const auto &post_op     = post_ops.get_list().at(post_op_id);
         const auto  slot_prefix = "-DP" + support::cpp11::to_string(slots[post_op_id]);
         if(post_op->type() == experimental::PostOpType::Activation)
         {
             const auto _post_op  = utils::cast::polymorphic_downcast<const experimental::PostOpAct<ITensorInfo *> *>(post_op.get());
             const auto act_type  = slot_prefix + "_ACTIVATION_TYPE=" + lower_string(string_from_activation_func(_post_op->_act_info.activation()));
             const auto act_a_val = slot_prefix + "_ACTIVATION_A_VAL=" + float_to_string_with_full_precision(_post_op->_act_info.a());
             const auto act_b_val = slot_prefix + "_ACTIVATION_B_VAL=" + float_to_string_with_full_precision(_post_op->_act_info.b());
             build_opts.add_option(act_type);
             build_opts.add_option(act_a_val);
             build_opts.add_option(act_b_val);
         }
         else if(post_op->type() == experimental::PostOpType::Eltwise_Add)
         {
             size_t     arg_id     = 1;
             const auto eltwise_op = slot_prefix + "_ELTWISE_OP=ADD" + "_X_POS_" + support::cpp11::to_string(post_op->prev_dst_pos());
             build_opts.add_option(eltwise_op);
             for(const auto &tensor : post_op->arguments())
             {
                 const auto height = slot_prefix + "_ELTWISE_ARG" + support::cpp11::to_string(arg_id) + "_HEIGHT=" + support::cpp11::to_string((*tensor)->dimension(1));
                 const auto width  = slot_prefix + "_ELTWISE_ARG" + support::cpp11::to_string(arg_id) + "_WIDTH=" + support::cpp11::to_string((*tensor)->dimension(0));
                 build_opts.add_option(height);
                 build_opts.add_option(width);
                 ++arg_id;
             }
         }
         else if(post_op->type() == experimental::PostOpType::Eltwise_PRelu)
         {
             size_t     arg_id     = 1;
             const auto eltwise_op = slot_prefix + "_ELTWISE_OP=PRELU" + "_X_POS_" + support::cpp11::to_string(post_op->prev_dst_pos());
             build_opts.add_option(eltwise_op);
             for(const auto &tensor : post_op->arguments())
             {
                 const auto height = slot_prefix + "_ELTWISE_ARG" + support::cpp11::to_string(arg_id) + "_HEIGHT=" + support::cpp11::to_string((*tensor)->dimension(1));
                 const auto width  = slot_prefix + "_ELTWISE_ARG" + support::cpp11::to_string(arg_id) + "_WIDTH=" + support::cpp11::to_string((*tensor)->dimension(0));
                 build_opts.add_option(height);
                 build_opts.add_option(width);
                 ++arg_id;
             }
         }
     }
 }
References arm_compute::experimental::Activation, CLBuildOptions::add_option(), arm_compute::experimental::Eltwise_Add, arm_compute::experimental::Eltwise_PRelu, arm_compute::float_to_string_with_full_precision(), arm_compute::experimental::get_post_op_sequence(), arm_compute::lower_string(), arm_compute::test::validation::post_ops, arm_compute::string_from_activation_func(), tensor, and arm_compute::support::cpp11::to_string().
set_post_ops_cl_kernel_name()
void set_post_ops_cl_kernel_name (std::string & kernel_name, const PostOpList< ITensorInfo * > & post_ops) const
Helper function to set PostOp kernel name.
Parameters
[out] kernel_name OpenCL kernel name
[in] post_ops Post ops
Definition at line 216 of file CLUtils.cpp.
 {
     const auto post_op_sequence = get_post_op_sequence(post_ops);
     const auto postfix          = std::get<0>(_supported_config.at(post_op_sequence));
     kernel_name += postfix;
 }
References arm_compute::experimental::get_post_op_sequence(), kernel_name, and arm_compute::test::validation::post_ops.
The documentation for this class was generated from the following files:
src/core/CL/CLUtils.h
src/core/CL/CLUtils.cpp