Compute Library: NELogicalNot Class Reference
NELogicalNot Class Reference
Basic function to perform logical NOT.
#include <NELogical.h>
Public Member Functions
NELogicalNot ()
Constructor.
NELogicalNot (const NELogicalNot &)=delete
Prevent instances of this class from being copied (As this class contains pointers)
NELogicalNot (NELogicalNot &&)=delete
Prevent instances of this class from being moved (As this class contains non movable objects)
NELogicalNot & operator= (const NELogicalNot &)=delete
Prevent instances of this class from being copied (As this class contains pointers)
NELogicalNot & operator= (NELogicalNot &&)=delete
Prevent instances of this class from being moved (As this class contains non movable objects)
~NELogicalNot ()
Destructor.
void configure (const ITensor *input, ITensor *output)
Initialise the kernel's inputs and output.
void run () override
Run the kernels contained in the function.
Public Member Functions inherited from IFunction
virtual ~IFunction ()=default
Destructor.
virtual void prepare ()
Prepare the function for executing.
Static Public Member Functions
static Status validate (const ITensorInfo *input, const ITensorInfo *output)
Static function to check if given info will lead to a valid configuration of NELogicalNot.
Detailed Description
Basic function to perform logical NOT.
Definition at line 139 of file NELogical.h.
Constructor & Destructor Documentation
NELogicalNot() [1/3]
NELogicalNot ()
Constructor.
Definition at line 108 of file NELogical.cpp.
     : _impl(std::make_unique<Impl>())
 {
 }
NELogicalNot() [2/3]
NELogicalNot (const NELogicalNot &) delete
Prevent instances of this class from being copied (As this class contains pointers)
NELogicalNot() [3/3]
NELogicalNot (NELogicalNot &&) delete
Prevent instances of this class from being moved (As this class contains non movable objects)
~NELogicalNot()
~NELogicalNot () default
Destructor.
Member Function Documentation
configure()
void configure (const ITensor * input, ITensor * output)
Initialise the kernel's inputs and output.
Valid data layouts:
All
Valid data type configurations:
src dst
U8 U8
Parameters
[in] input Input tensor. Data type supported: U8.
[out] output Output tensor. Data type supported: U8.
Definition at line 114 of file NELogical.cpp.
 {
     ARM_COMPUTE_ERROR_ON_NULLPTR(input, output);
     ARM_COMPUTE_LOG_PARAMS(input, output);
     _impl->kernel = std::make_unique<kernels::NELogicalKernel>();
     _impl->kernel->configure(input->info(), nullptr, output->info(), LogicalOperation::Not);
     _impl->pack = ITensorPack();
     _impl->pack.add_tensor(TensorType::ACL_SRC_0, input);
     _impl->pack.add_tensor(TensorType::ACL_DST, output);
 }
References arm_compute::ACL_DST, arm_compute::ACL_SRC_0, ARM_COMPUTE_ERROR_ON_NULLPTR, ARM_COMPUTE_LOG_PARAMS, ITensor::info(), arm_compute::test::validation::input, and arm_compute::Not.
operator=() [1/2]
NELogicalNot& operator= (const NELogicalNot &) delete
Prevent instances of this class from being copied (As this class contains pointers)
operator=() [2/2]
NELogicalNot& operator= (NELogicalNot &&) delete
Prevent instances of this class from being moved (As this class contains non movable objects)
run()
void run () override virtual
Run the kernels contained in the function.
For CPU kernels:
Multi-threading is used for the kernels which are parallelisable.
By default std::thread::hardware_concurrency() threads are used.
Note
CPPScheduler::set_num_threads() can be used to manually set the number of threads
For OpenCL kernels:
All the kernels are enqueued on the queue associated with CLScheduler.
The queue is then flushed.
Note
The function will not block until the kernels are executed. It is the user's responsibility to wait.
Will call prepare() on first run if hasn't been done
Implements IFunction.
Definition at line 132 of file NELogical.cpp.
 {
     NEScheduler::get().schedule_op(_impl->kernel.get(), Window::DimY, _impl->kernel->window(), _impl->pack);
 }
References Window::DimY, Scheduler::get(), and IScheduler::schedule_op().
validate()
Status validate (const ITensorInfo * input, const ITensorInfo * output) static
Static function to check if given info will lead to a valid configuration of NELogicalNot.
Parameters
[in] input Input tensor info. Data types supported: U8.
[in] output Output tensor info. Data type supported: U8
Returns
a status
Definition at line 127 of file NELogical.cpp.
 {
     return kernels::NELogicalKernel::validate(input, nullptr, output, LogicalOperation::Not);
 }
References arm_compute::test::validation::input, arm_compute::Not, and NELogicalKernel::validate().
The documentation for this class was generated from the following files:
arm_compute/runtime/NEON/functions/NELogical.h
src/runtime/NEON/functions/NELogical.cpp