Compute Library: Operator Class Reference
Operator Class Reference
Operator class.
#include <Acl.hpp>
Public Member Functions
StatusCode run (Queue &queue, TensorPack &pack)
Run an operator on a given input list.
Public Member Functions inherited from ObjectBase< AclOperator_ >
~ObjectBase ()=default
Destructor.
ObjectBase (const ObjectBase< AclOperator_ > &)=default
Copy constructor.
ObjectBase (ObjectBase< AclOperator_ > &&)=default
Move Constructor.
ObjectBase< AclOperator_ > & operator= (const ObjectBase< AclOperator_ > &)=default
Copy assignment operator.
ObjectBase< AclOperator_ > & operator= (ObjectBase< AclOperator_ > &&)=default
Move assignment operator.
void reset (AclOperator_ *val)
Reset object value.
const AclOperator_ * get () const
Access uderlying object.
AclOperator_ * get ()
Access uderlying object.
Detailed Description
Operator class.
Operators are the basic algorithmic blocks responsible for performing distinct operations
Definition at line 758 of file Acl.hpp.
Member Function Documentation
run()
StatusCode run (Queue & queue, TensorPack & pack) inline
Run an operator on a given input list.
Parameters
[in,out] queue Queue to scheduler the operator on
pack Tensor list to be used as input
Returns
Status Code
Definition at line 768 of file Acl.hpp.
     {
         return detail::as_cenum<StatusCode>(AclRunOperator(_object.get(), queue.get(), pack.get()));
     }
References AclRunOperator(), ObjectBase< T >::get(), and arm_compute::test::validation::pack.
Referenced by arm_compute::test::validation::TEST_CASE().
The documentation for this class was generated from the following file:
arm_compute/Acl.hpp