Compute Library: ObjectBase< T > Class Template Reference
ObjectBase< T > Class Template Reference
Object base class for library objects.
#include <Acl.hpp>
Public Member Functions
~ObjectBase ()=default
Destructor.
ObjectBase (const ObjectBase< T > &)=default
Copy constructor.
ObjectBase (ObjectBase< T > &&)=default
Move Constructor.
ObjectBase< T > & operator= (const ObjectBase< T > &)=default
Copy assignment operator.
ObjectBase< T > & operator= (ObjectBase< T > &&)=default
Move assignment operator.
void reset (T *val)
Reset object value.
const T * get () const
Access uderlying object.
T * get ()
Access uderlying object.
Detailed Description
template<typename T>
class acl::detail::ObjectBase< T >
Object base class for library objects.
Class is defining basic common interface for all the library objects
Template Parameters
T Object type to be templated on
Definition at line 131 of file Acl.hpp.
Constructor & Destructor Documentation
~ObjectBase()
~ObjectBase () default
Destructor.
ObjectBase() [1/2]
ObjectBase (const ObjectBase< T > &) default
Copy constructor.
ObjectBase() [2/2]
ObjectBase (ObjectBase< T > &&) default
Move Constructor.
Member Function Documentation
get() [1/2]
T* get () inline
Access uderlying object.
Returns
Underlying object
Definition at line 164 of file Acl.hpp.
     {
         return _object.get();
     }
get() [2/2]
const T* get () const inline
Access uderlying object.
Returns
Underlying object
Definition at line 156 of file Acl.hpp.
     {
         return _object.get();
     }
Referenced by Activation::Activation(), acl::detail::operator==(), Queue::Queue(), Operator::run(), Tensor::Tensor(), TensorPack::TensorPack(), and arm_compute::test::validation::TEST_CASE().
operator=() [1/2]
ObjectBase<T>& operator= (const ObjectBase< T > &) default
Copy assignment operator.
operator=() [2/2]
ObjectBase<T>& operator= (ObjectBase< T > &&) default
Move assignment operator.
reset()
void reset (T * val) inline
Reset object value.
Parameters
[in] val Value to set
Definition at line 148 of file Acl.hpp.
     {
         _object.reset(val, detail::ObjectDeleter<T *>::Destroy);
     }
The documentation for this class was generated from the following file:
arm_compute/Acl.hpp