Compute Library: ClPRelu Class Reference
ClPRelu Class Reference
Basic operator to run arm_compute::opencl::kernels::ClArithmeticKernel for PRELU.
#include <ClPRelu.h>
Public Member Functions
void configure (const CLCompileContext &compile_context, ITensorInfo *input, ITensorInfo *alpha, ITensorInfo *output)
Set the input and output tensor.
void run (ITensorPack &tensors) override
Run the kernels contained in the function.
Public Member Functions inherited from ICLOperator
ICLOperator (IRuntimeContext *ctx=nullptr)
Constructor.
ICLOperator (const ICLOperator &)=delete
Prevent instances of this class from being copied (As this class contains pointers)
ICLOperator (ICLOperator &&)=default
Default move constructor.
ICLOperator & operator= (const ICLOperator &)=delete
Prevent instances of this class from being copied (As this class contains pointers)
ICLOperator & operator= (ICLOperator &&)=default
Default move assignment operator.
void prepare (ITensorPack &constants) override
Prepare the function for executing.
MemoryRequirements workspace () const override
Return the memory requirements required by the workspace.
Public Member Functions inherited from IOperator
virtual ~IOperator ()=default
Destructor.
Static Public Member Functions
static Status validate (const ITensorInfo *input, const ITensorInfo *alpha, const ITensorInfo *output)
Static function to check if given info will lead to a valid configuration.
Detailed Description
Basic operator to run arm_compute::opencl::kernels::ClArithmeticKernel for PRELU.
Note
The operator implements an activation layer with the PRELU activation function.
Definition at line 38 of file ClPRelu.h.
Member Function Documentation
configure()
void configure (const CLCompileContext & compile_context, ITensorInfo * input, ITensorInfo * alpha, ITensorInfo * output)
Set the input and output tensor.
Note
If the output tensor is a nullptr or is equal to the input, the activation function will be performed in-place
Parameters
[in] compile_context The compile context to be used.
[in] input Source tensor. Data types supported: QASYMM8/QASYMM8_SIGNED/F16/F32.
[in] alpha PRelu layer parameters. Data types supported: same of input.
[out] output Destination tensor. Data type supported: same as input
Definition at line 35 of file ClPRelu.cpp.
 {
     ARM_COMPUTE_LOG_PARAMS(input, alpha, output);
     auto k = std::make_unique<KernelType>();
     k->configure(compile_context, ArithmeticOperation::PRELU, input, alpha, (output == nullptr ? input : output));
     _kernel = std::move(k);
 }
References ARM_COMPUTE_LOG_PARAMS, arm_compute::test::validation::input, arm_compute::test::validation::k, and arm_compute::PRELU.
run()
void run (ITensorPack & tensors) override virtual
Run the kernels contained in the function.
Parameters
[in] tensors Vector that contains the tensors to operate on.
Reimplemented from ICLOperator.
Definition at line 48 of file ClPRelu.cpp.
 {
     // Output tensor can be given as nullptr for in-place computation.
     // In this case, get the input tensor and use it as the output tensor.
     if(tensors.get_tensor(TensorType::ACL_DST) == nullptr)
     {
         auto src_tensor = const_cast<ITensor *>(tensors.get_const_tensor(TensorType::ACL_SRC_0));
         ARM_COMPUTE_ERROR_ON_MSG(src_tensor == nullptr, "invalid source tensor is given for in-place computation");
         tensors.add_tensor(TensorType::ACL_DST, src_tensor);
     }
     IClOperator::run(tensors);
 }
References arm_compute::ACL_DST, arm_compute::ACL_SRC_0, ITensorPack::add_tensor(), ARM_COMPUTE_ERROR_ON_MSG, ITensorPack::get_const_tensor(), ITensorPack::get_tensor(), and ICLOperator::run().
validate()
Status validate (const ITensorInfo * input, const ITensorInfo * alpha, const ITensorInfo * output) static
Static function to check if given info will lead to a valid configuration.
Similar to ClPRelu::configure()
Returns
a status
Definition at line 43 of file ClPRelu.cpp.
 {
     return KernelType::validate(ArithmeticOperation::PRELU, input, alpha, (output == nullptr ? input : output));
 }
References arm_compute::test::validation::input, arm_compute::PRELU, and ClArithmeticKernel::validate().
The documentation for this class was generated from the following files:
src/gpu/cl/operators/ClPRelu.h
src/gpu/cl/operators/ClPRelu.cpp