Compute Library: GpuCkwCast Class Reference
GpuCkwCast Class Reference
#include <GpuCkwCast.h>
Public Types
using Attributes = ClComponentCast::Attributes
Public Types inherited from IGpuCkwComponentDriver
using ComponentGroup = GpuKernelComponentGroup
Public Member Functions
GpuCkwCast (ComponentId id, const ArgumentPack< ITensorInfo > &tensors, const Attributes &attributes)
Constructor.
ARM_COMPUTE_DISALLOW_COPY_ALLOW_MOVE (GpuCkwCast)
~GpuCkwCast () override=default
Destructor.
virtual void write_component_code (const ComponentGroup &comp_group, GpuCkwVariableTable &vtable, GpuCkwScopedKernelWriter writer) const override
Generate kernel component code.
Window get_window () const override
Generate the execution window for the component.
Public Member Functions inherited from IGpuCkwComponentDriver
IGpuCkwComponentDriver (ComponentId id, const ArgumentPack< ITensorInfo > &tensors)
Constructor.
virtual ~IGpuCkwComponentDriver ()
Destructor.
ArgumentPack< ITensorInfo > tensors () const
Get tensor arguments.
virtual std::string get_name (const ComponentGroup &comp_group) const
Generate the name of the component.
virtual std::string get_tuner_id (const ComponentGroup &comp_group) const
Generate the tuner id of the component This id should capture all the parameters that distinguish one kernel's lws tuning from another.
ComponentId id () const
Get component id.
Detailed Description
Definition at line 37 of file GpuCkwCast.h.
Member Typedef Documentation
Attributes
using Attributes = ClComponentCast::Attributes
Definition at line 40 of file GpuCkwCast.h.
Constructor & Destructor Documentation
GpuCkwCast()
GpuCkwCast (ComponentId id, const ArgumentPack< ITensorInfo > & tensors, const Attributes & attributes)
Constructor.
For supported configurations please refer to ClComponentCast::validate()
Parameters
[in] id Component id
[in] tensors Tensor arguments to the component
[in] attributes Component attributes
Definition at line 87 of file GpuCkwCast.cpp.
     : IGpuCkwComponentDriver{ id, tensors },
       _src{},
       _dst{},
       _attributes{ attributes }
 {
     _src = this->tensors().get_const_tensor(TensorType::ACL_SRC_0);
     _dst = this->tensors().get_const_tensor(TensorType::ACL_DST_0);
     ARM_COMPUTE_ERROR_ON_NULLPTR(_src, _dst);
 }
References IGpuCkwComponentDriver::id(), and IGpuCkwComponentDriver::tensors().
~GpuCkwCast()
~GpuCkwCast () override default
Destructor.
Member Function Documentation
ARM_COMPUTE_DISALLOW_COPY_ALLOW_MOVE()
ARM_COMPUTE_DISALLOW_COPY_ALLOW_MOVE (GpuCkwCast)
get_window()
Window get_window () const override virtual
Generate the execution window for the component.
Reimplemented from IGpuCkwComponentDriver.
Definition at line 162 of file GpuCkwCast.cpp.
 {
     ARM_COMPUTE_ERROR_ON_MSG(_dst->tensor_shape().total_size() == 0U, "Destination tensor is not initialized");
     TensorShape output_shape = _dst->tensor_shape();
     // Collapse Dim 1 (W) and Dim 2 (H) together, leave Dim 0 (C) unchanged
     // This is in line with the collapsing convention used by operators like Conv2d
     output_shape.collapse(2U, 1U);
     constexpr unsigned int vector_size_byte_opencl           = 16;
     const unsigned int     num_elems_processed_per_iteration = adjust_vec_size(vector_size_byte_opencl / _dst->element_size(), _dst->dimension(0));
     Window                 win                               = calculate_max_window(output_shape, Steps(num_elems_processed_per_iteration));
     return win;
 }
References arm_compute::adjust_vec_size(), ARM_COMPUTE_ERROR_ON_MSG, arm_compute::calculate_max_window(), ITensorInfo::dimension(), ITensorInfo::element_size(), num_elems_processed_per_iteration, arm_compute::test::validation::output_shape, ITensorInfo::tensor_shape(), TensorShape::total_size(), arm_compute::utils::cast::U, and arm_compute::experimental::dynamic_fusion::vector_size_byte_opencl.
write_component_code()
void write_component_code (const ComponentGroup & comp_group, GpuCkwVariableTable & vtable, GpuCkwScopedKernelWriter writer) const override virtual
Generate kernel component code.
Parameters
[in] comp_group Component group of which the component is a part of
[in,out] vtable Table of variables declared by each component
[in,out] writer CKW writer that writes code scoped to this kernel component.
                       @note @p writer can only be passed via value since the new scope is created in the copy constructor
Implements IGpuCkwComponentDriver.
Definition at line 100 of file GpuCkwCast.cpp.
 {
     const auto         root_window = comp_group.get_root_component()->ckw_component_driver()->get_window();
     const unsigned int n0          = root_window.x().step();
     const unsigned int m0          = root_window.y().step();
     GpuCkwComponentArgument *src = vtable.declare_variable(comp_group, writer, _src, TensorStorageType::ClBufferUint8Ptr, "src");
     GpuCkwComponentArgument *dst = vtable.declare_variable(comp_group, writer, _dst, TensorStorageType::ClBufferUint8Ptr, "dst");
     // Load the source tile and prepare the sampler.
     if(!src->has_tile())
     {
         const auto sampler = create_sampler(writer, m0, n0);
         writer->op_load_once(src, sampler);
     }
     else
     {
         const auto &sampler = src->tile_sampler();
         writer->op_load_once(src, sampler);
     }
     const auto &src_tile = src->tile();
     const auto &sampler  = src->tile_sampler();
     // Prepare the output tile.
     if(!dst->has_tile())
     {
         // Get Target datatype and convert it to ckw::DataType.
         ckw::DataType target_dt = dynamic_fusion::to_ckw(_attributes.data_type());
         // Create dst_tile based on src_tile dimensions and with target DataType.
         const TileInfo src_tile_info = src_tile.tile_info();
         const TileInfo dst_tile_info = TileInfo(target_dt, src_tile_info.height(), src_tile_info.width());
         // Declare dst_tile
         auto &tile = writer->declare_tile("dst_tile", dst_tile_info);
         dst->init_virtual_tensor(tile, sampler);
     }
     const auto &dst_tile = dst->tile();
     // Check if this op is cast-down or cast-up
     const size_t src_size  = data_size_from_type(_src->data_type());
     const size_t dst_size  = data_size_from_type(_dst->data_type());
     const bool   cast_down = (src_size >= dst_size);
     if(cast_down && is_data_type_quantized(_src->data_type()))
     {
         const auto &constant_x80 = writer->declare_tile("0x80", 0x80);
         writer->op_binary_expression(src_tile, src_tile, BinaryOp::BitwiseXOR, constant_x80);
     }
     ckw::ConvertPolicy convert_policy = ckw::ConvertPolicy::None;
     if(cast_down && (is_data_type_float(_src->data_type()) || _attributes.convert_policy() == ConvertPolicy::SATURATE))
     {
         convert_policy = ckw::ConvertPolicy::Saturate;
     }
     writer->op_cast_expression(dst_tile, src_tile, convert_policy);
 }
References cast_down(), IGpuKernelComponent::ckw_component_driver(), CastAttributes::convert_policy(), arm_compute::data_size_from_type(), CastAttributes::data_type(), ITensorInfo::data_type(), GpuCkwVariableTable::declare_variable(), arm_compute::test::validation::dst, GpuKernelComponentGroup::get_root_component(), IGpuCkwComponentDriver::get_window(), arm_compute::is_data_type_float(), arm_compute::is_data_type_quantized(), tf_frozen_model_extractor::None, GpuCkwKernelWriter::op_load_once(), arm_compute::SATURATE, arm_compute::test::validation::src, Window::Dimension::step(), arm_compute::test::validation::reference::tile(), arm_compute::experimental::dynamic_fusion::to_ckw(), and Window::x().
The documentation for this class was generated from the following files:
src/dynamic_fusion/sketch/gpu/ckw_driver/components/GpuCkwCast.h
src/dynamic_fusion/sketch/gpu/ckw_driver/components/GpuCkwCast.cpp