Compute Library: PadStrideInfo Class Reference
PadStrideInfo Class Reference
#include <CoreTypes.h>
Public Member Functions
PadStrideInfo (unsigned int stride_x=1, unsigned int stride_y=1, unsigned int pad_x=0, unsigned int pad_y=0, DimensionRoundingType round=DimensionRoundingType::FLOOR)
Constructor.
PadStrideInfo (unsigned int stride_x, unsigned int stride_y, unsigned int pad_left, unsigned int pad_right, unsigned int pad_top, unsigned int pad_bottom, DimensionRoundingType round)
Constructor.
std::pair< unsigned int, unsigned int > stride () const
Get the stride.
bool padding_is_symmetric () const
Check whether the padding is symmetric.
std::pair< unsigned int, unsigned int > pad () const
Get the padding.
unsigned int pad_left () const
Get the left padding.
unsigned int pad_right () const
Get the right padding.
unsigned int pad_top () const
Get the top padding.
unsigned int pad_bottom () const
Get the bottom padding.
DimensionRoundingType round () const
Get the rounding type.
bool has_padding () const
Check whether this has any padding.
Detailed Description
Definition at line 138 of file CoreTypes.h.
Constructor & Destructor Documentation
PadStrideInfo() [1/2]
PadStrideInfo (unsigned int stride_x = 1, unsigned int stride_y = 1, unsigned int pad_x = 0, unsigned int pad_y = 0, DimensionRoundingType round = DimensionRoundingType::FLOOR) inline
Constructor.
Parameters
[in] stride_x (Optional) Stride, in elements, across x. Defaults to 1.
[in] stride_y (Optional) Stride, in elements, across y. Defaults to 1.
[in] pad_x (Optional) Padding, in elements, across x. Defaults to 0.
[in] pad_y (Optional) Padding, in elements, across y. Defaults to 0.
[in] round (Optional) Dimensions rounding. Defaults to DimensionRoundingType::FLOOR.
Definition at line 149 of file CoreTypes.h.
         : _stride(std::make_pair(stride_x, stride_y)),
           _pad_left(pad_x),
           _pad_top(pad_y),
           _pad_right(pad_x),
           _pad_bottom(pad_y),
           _round_type(round)
     {
     }
PadStrideInfo() [2/2]
PadStrideInfo (unsigned int stride_x, unsigned int stride_y, unsigned int pad_left, unsigned int pad_right, unsigned int pad_top, unsigned int pad_bottom, DimensionRoundingType round) inline
Constructor.
Parameters
[in] stride_x Stride, in elements, across x.
[in] stride_y Stride, in elements, across y.
[in] pad_left Padding across x on the left, in elements.
[in] pad_right Padding across x on the right, in elements.
[in] pad_top Padding across y on the top, in elements.
[in] pad_bottom Padding across y on the bottom, in elements.
[in] round Dimensions rounding.
Definition at line 170 of file CoreTypes.h.
         : _stride(std::make_pair(stride_x, stride_y)),
           _pad_left(pad_left),
           _pad_top(pad_top),
           _pad_right(pad_right),
           _pad_bottom(pad_bottom),
           _round_type(round)
     {
     }
Member Function Documentation
has_padding()
bool has_padding () const inline
Check whether this has any padding.
Definition at line 239 of file CoreTypes.h.
     {
         return (_pad_left != 0 || _pad_top != 0 || _pad_right != 0 || _pad_bottom != 0);
     }
Referenced by arm_compute::cpu::poolingMxN_fp32_neon_nhwc().
pad()
std::pair<unsigned int, unsigned int> pad () const inline
Get the padding.
Note
This should only be used when the padding is symmetric.
Returns
a pair: padding left/right, padding top/bottom
Definition at line 204 of file CoreTypes.h.
     {
         //this accessor should be used only when padding is symmetric
         ARM_COMPUTE_ERROR_ON(!padding_is_symmetric());
         return std::make_pair(_pad_left, _pad_top);
     }
References ARM_COMPUTE_ERROR_ON, and PadStrideInfo::padding_is_symmetric().
pad_bottom()
unsigned int pad_bottom () const inline
Get the bottom padding.
Definition at line 227 of file CoreTypes.h.
     {
         return _pad_bottom;
     }
Referenced by arm_compute::misc::shape_calculator::compute_unpool_shape(), NEDeconvolutionLayer::configure(), CLGEMMDeconvolutionLayer::configure(), arm_compute::deconvolution_output_dimensions(), arm_compute::assembly_utils::map_to_arm_conv_padding(), arm_compute::operator<<(), arm_compute::cpu::poolingMxN_fp32_neon_nhwc(), arm_compute::cpu::poolingMxN_q8_neon_nhwc(), CPPUpsampleKernel::run(), CLDeconvolutionLayerUpsampleKernel::run(), arm_compute::scaled_dimensions(), arm_compute::scaled_dimensions_signed(), NEDeconvolutionLayer::validate(), and CLGEMMDeconvolutionLayer::validate().
pad_left()
unsigned int pad_left () const inline
Get the left padding.
Definition at line 212 of file CoreTypes.h.
     {
         return _pad_left;
     }
Referenced by arm_compute::misc::shape_calculator::compute_unpool_shape(), ClTransposedConvolutionKernel::configure(), ClPool2dKernel::configure(), NEDeconvolutionLayer::configure(), CLGEMMDeconvolutionLayer::configure(), arm_compute::deconvolution_output_dimensions(), arm_compute::assembly_utils::map_to_arm_conv_padding(), arm_compute::operator<<(), arm_compute::cpu::poolingMxN_fp32_neon_nhwc(), arm_compute::cpu::poolingMxN_fp32_neon_nhwc_kernel_indices(), arm_compute::cpu::poolingMxN_q8_neon_nhwc(), CPPUpsampleKernel::run(), CLDeconvolutionLayerUpsampleKernel::run(), arm_compute::scaled_dimensions(), arm_compute::scaled_dimensions_signed(), NEDeconvolutionLayer::validate(), and CLGEMMDeconvolutionLayer::validate().
pad_right()
unsigned int pad_right () const inline
Get the right padding.
Definition at line 217 of file CoreTypes.h.
     {
         return _pad_right;
     }
Referenced by arm_compute::misc::shape_calculator::compute_unpool_shape(), NEDeconvolutionLayer::configure(), CLGEMMDeconvolutionLayer::configure(), arm_compute::deconvolution_output_dimensions(), arm_compute::assembly_utils::map_to_arm_conv_padding(), arm_compute::operator<<(), arm_compute::cpu::poolingMxN_fp32_neon_nhwc(), arm_compute::cpu::poolingMxN_q8_neon_nhwc(), CPPUpsampleKernel::run(), CLDeconvolutionLayerUpsampleKernel::run(), arm_compute::scaled_dimensions(), arm_compute::scaled_dimensions_signed(), NEDeconvolutionLayer::validate(), and CLGEMMDeconvolutionLayer::validate().
pad_top()
unsigned int pad_top () const inline
Get the top padding.
Definition at line 222 of file CoreTypes.h.
     {
         return _pad_top;
     }
Referenced by arm_compute::misc::shape_calculator::compute_unpool_shape(), ClTransposedConvolutionKernel::configure(), ClPool2dKernel::configure(), NEDeconvolutionLayer::configure(), CLGEMMDeconvolutionLayer::configure(), arm_compute::deconvolution_output_dimensions(), arm_compute::assembly_utils::map_to_arm_conv_padding(), arm_compute::operator<<(), arm_compute::cpu::poolingMxN_fp32_neon_nhwc(), arm_compute::cpu::poolingMxN_fp32_neon_nhwc_kernel_indices(), arm_compute::cpu::poolingMxN_q8_neon_nhwc(), CPPUpsampleKernel::run(), CLDeconvolutionLayerUpsampleKernel::run(), arm_compute::scaled_dimensions(), arm_compute::scaled_dimensions_signed(), NEDeconvolutionLayer::validate(), and CLGEMMDeconvolutionLayer::validate().
padding_is_symmetric()
bool padding_is_symmetric () const inline
Check whether the padding is symmetric.
Returns
True if the padding is symmetric.
Definition at line 194 of file CoreTypes.h.
     {
         return (_pad_left == _pad_right) && (_pad_top == _pad_bottom);
     }
Referenced by PadStrideInfo::pad().
round()
DimensionRoundingType round () const inline
Get the rounding type.
Definition at line 233 of file CoreTypes.h.
     {
         return _round_type;
     }
Referenced by arm_compute::scaled_dimensions(), and arm_compute::scaled_dimensions_signed().
stride()
std::pair<unsigned int, unsigned int> stride () const inline
Get the stride.
Returns
a pair: stride x, stride y.
Definition at line 186 of file CoreTypes.h.
     {
         return _stride;
     }
Referenced by arm_compute::misc::shape_calculator::compute_unpool_shape(), ClTransposedConvolutionKernel::configure(), ClPool2dKernel::configure(), CpuPool2dKernel::configure(), ClGemmConv2d::configure(), arm_compute::deconvolution_output_dimensions(), ClConv2d::get_convolution_method(), CLDeconvolutionLayer::get_deconvolution_method(), arm_compute::operator<<(), arm_compute::cpu::poolingMxN_fp32_neon_nhwc(), arm_compute::cpu::poolingMxN_fp32_neon_nhwc_kernel_indices(), arm_compute::cpu::poolingMxN_q8_neon_nhwc(), CPPUpsampleKernel::run(), CLDeconvolutionLayerUpsampleKernel::run(), CpuPool2dKernel::run_op(), arm_compute::scaled_dimensions(), arm_compute::scaled_dimensions_signed(), ClGemmConv2d::validate(), and CLGEMMDeconvolutionLayer::validate().
The documentation for this class was generated from the following file:
arm_compute/core/CoreTypes.h