Compute Library: CLCopy Class Reference
CLCopy Class Reference
Basic function to run opencl::kernels::ClCopyKernel.
#include <CLCopy.h>
Public Member Functions
CLCopy ()
Constructor.
~CLCopy ()
Destructor.
CLCopy (const CLCopy &)=delete
Prevent instances of this class from being copied (As this class contains pointers)
CLCopy (CLCopy &&)
Default move constructor.
CLCopy & operator= (const CLCopy &)=delete
Prevent instances of this class from being copied (As this class contains pointers)
CLCopy & operator= (CLCopy &&)
Default move assignment operator.
void configure (ICLTensor *input, ICLTensor *output, Window *dst_window=nullptr)
Initialise the function's source and destination.
void configure (const CLCompileContext &compile_context, ICLTensor *input, ICLTensor *output, Window *dst_window=nullptr)
Initialise the function's source and destination.
void run () override
Run the kernels contained in the function.
Public Member Functions inherited from IFunction
virtual ~IFunction ()=default
Destructor.
virtual void prepare ()
Prepare the function for executing.
Static Public Member Functions
static Status validate (const ITensorInfo *input, const ITensorInfo *output, Window *dst_window=nullptr)
Static function to check if given info will lead to a valid configuration of CLCopy.
Detailed Description
Basic function to run opencl::kernels::ClCopyKernel.
Definition at line 39 of file CLCopy.h.
Constructor & Destructor Documentation
CLCopy() [1/3]
CLCopy ()
Constructor.
Definition at line 46 of file CLCopy.cpp.
     : _impl(std::make_unique<Impl>())
 {
 }
~CLCopy()
~CLCopy () default
Destructor.
CLCopy() [2/3]
CLCopy (const CLCopy &) delete
Prevent instances of this class from being copied (As this class contains pointers)
CLCopy() [3/3]
CLCopy (CLCopy &&) default
Default move constructor.
Member Function Documentation
configure() [1/2]
void configure (const CLCompileContext & compile_context, ICLTensor * input, ICLTensor * output, Window * dst_window = nullptr)
Initialise the function's source and destination.
Parameters
[in] compile_context The compile context to be used.
[in] input Source tensor. Data types supported: All.
[out] output Output tensor. Data types supported: Same as input.
[in] dst_window (Optional) Window to be used in case only copying into part of a tensor. Default is nullptr.
Definition at line 59 of file CLCopy.cpp.
 {
     ARM_COMPUTE_ERROR_ON_NULLPTR(input);
     ARM_COMPUTE_LOG_PARAMS(input, output, dst_window);
     _impl->src = input;
     _impl->dst = output;
     _impl->op = std::make_unique<opencl::ClCopy>();
     _impl->op->configure(compile_context, _impl->src->info(), _impl->dst->info(), dst_window);
 }
References ARM_COMPUTE_ERROR_ON_NULLPTR, ARM_COMPUTE_LOG_PARAMS, and arm_compute::test::validation::input.
configure() [2/2]
void configure (ICLTensor * input, ICLTensor * output, Window * dst_window = nullptr)
Initialise the function's source and destination.
Valid data layouts:
All
Valid data type configurations:
src dst
All All
Parameters
[in] input Source tensor. Data types supported: All.
[out] output Output tensor. Data types supported: Same as input.
[in] dst_window (Optional) Window to be used in case only copying into part of a tensor. Default is nullptr.
Definition at line 54 of file CLCopy.cpp.
 {
     configure(CLKernelLibrary::get().get_compile_context(), input, output, dst_window);
 }
References CLKernelLibrary::get(), and arm_compute::test::validation::input.
Referenced by CLRNNLayer::configure(), CLPadLayer::configure(), CLLSTMLayer::configure(), and CLQLSTMLayer::configure().
operator=() [1/2]
CLCopy & operator= (CLCopy &&) default
Default move assignment operator.
operator=() [2/2]
CLCopy& operator= (const CLCopy &) delete
Prevent instances of this class from being copied (As this class contains pointers)
run()
void run () override virtual
Run the kernels contained in the function.
For CPU kernels:
Multi-threading is used for the kernels which are parallelisable.
By default std::thread::hardware_concurrency() threads are used.
Note
CPPScheduler::set_num_threads() can be used to manually set the number of threads
For OpenCL kernels:
All the kernels are enqueued on the queue associated with CLScheduler.
The queue is then flushed.
Note
The function will not block until the kernels are executed. It is the user's responsibility to wait.
Will call prepare() on first run if hasn't been done
Implements IFunction.
Definition at line 76 of file CLCopy.cpp.
 {
     ITensorPack pack;
     pack.add_tensor(TensorType::ACL_SRC, _impl->src);
     pack.add_tensor(TensorType::ACL_DST, _impl->dst);
     _impl->op->run(pack);
 }
References arm_compute::ACL_DST, arm_compute::ACL_SRC, ITensorPack::add_tensor(), and arm_compute::test::validation::pack.
Referenced by CLRNNLayer::run(), CLPadLayer::run(), CLLSTMLayer::run(), and CLQLSTMLayer::run().
validate()
Status validate (const ITensorInfo * input, const ITensorInfo * output, Window * dst_window = nullptr) static
Static function to check if given info will lead to a valid configuration of CLCopy.
Parameters
[in] input Source tensor. Data types supported: All.
[in] output Output tensor. Data types supported: Same as input.
[in] dst_window (Optional) Window to be used in case only copying into part of a tensor. Default is nullptr.
Returns
a status
Definition at line 71 of file CLCopy.cpp.
 {
     return opencl::ClCopy::validate(input, output, dst_window);
 }
References arm_compute::test::validation::input, and ClCopy::validate().
Referenced by CLPadLayer::validate(), CLLSTMLayer::validate(), and CLQLSTMLayer::validate().
The documentation for this class was generated from the following files:
arm_compute/runtime/CL/functions/CLCopy.h
src/runtime/CL/functions/CLCopy.cpp