Compute Library: SoftmaxAttributes Class Reference
SoftmaxAttributes Class Reference
Attributes are backend-agnostic parameters (in addition to the input/output tensors) of an operator.
#include <SoftmaxAttributes.h>
Public Member Functions
SoftmaxAttributes & beta (float beta)
Set beta.
float beta () const
Get beta.
SoftmaxAttributes & is_log_softmax (bool is_log)
Set is_log.
bool is_log_softmax () const
Get is_log.
SoftmaxAttributes & axis (int axis)
Set axis.
int axis () const
Get axis.
Detailed Description
Attributes are backend-agnostic parameters (in addition to the input/output tensors) of an operator.
Softmax attributes
Definition at line 37 of file SoftmaxAttributes.h.
Member Function Documentation
axis() [1/2]
int axis () const
Get axis.
Definition at line 61 of file SoftmaxAttributes.cpp.
 {
     return _axis;
 }
Referenced by SoftmaxAttributes::axis().
axis() [2/2]
SoftmaxAttributes & axis (int axis)
Set axis.
Definition at line 55 of file SoftmaxAttributes.cpp.
 {
     _axis = axis;
     return *this;
 }
References SoftmaxAttributes::axis().
Referenced by arm_compute::operator<<(), and GpuSoftmax::validate_op().
beta() [1/2]
float beta () const
Get beta.
Definition at line 39 of file SoftmaxAttributes.cpp.
 {
     return _beta;
 }
Referenced by SoftmaxAttributes::beta().
beta() [2/2]
SoftmaxAttributes & beta (float beta)
Set beta.
Definition at line 33 of file SoftmaxAttributes.cpp.
 {
     _beta = beta;
     return *this;
 }
References SoftmaxAttributes::beta().
Referenced by ClTemplateLogits1DMaxShiftExpSum::get_component_code(), ClTemplateLogits1DMaxShiftExpSum::get_tag_lut(), and arm_compute::operator<<().
is_log_softmax() [1/2]
bool is_log_softmax () const
Get is_log.
Definition at line 50 of file SoftmaxAttributes.cpp.
 {
     return _is_log_softmax;
 }
Referenced by SoftmaxAttributes::is_log_softmax().
is_log_softmax() [2/2]
SoftmaxAttributes & is_log_softmax (bool is_log)
Set is_log.
Definition at line 44 of file SoftmaxAttributes.cpp.
 {
     _is_log_softmax = is_log_softmax;
     return *this;
 }
References SoftmaxAttributes::is_log_softmax().
Referenced by ClTemplateLogits1DMaxShiftExpSum::get_component_code(), ClTemplateLogits1DNorm::get_component_code(), arm_compute::operator<<(), and ClComponentLogits1DNorm::validate().
The documentation for this class was generated from the following files:
arm_compute/dynamic_fusion/sketch/attributes/SoftmaxAttributes.h
src/dynamic_fusion/sketch/attributes/SoftmaxAttributes.cpp