Compute Library: DepthfirstMultiplierStrategy< TInput, TWeight, TOutput, TAccum > Class Template Reference
DepthfirstMultiplierStrategy< TInput, TWeight, TOutput, TAccum > Class Template Reference abstract
#include <depthwise_depthfirst_multiplier.hpp>
Public Types
using KernelType = std::function< void(const TInput *const *, TOutput *const *, const void *, unsigned int, TAccum, TAccum)>
Public Member Functions
size_t get_storage_size (const DepthwiseArgs &args) const override
void pack_parameters (const DepthwiseArgs &args, void *buffer, const void *biases, const Nothing &, const void *weights, size_t ld_weight_col, size_t ld_weight_row) const override
virtual KernelType get_kernel (void) const =0
Public Member Functions inherited from DepthwiseDepthfirstStrategyCommon< TInput, TWeight, TOutput, TAccum, Nothing >
DepthwiseDepthfirstStrategyCommon (unsigned int output_rows, unsigned int output_cols, unsigned int kernel_rows, unsigned int kernel_cols, unsigned int stride_rows=1, unsigned int stride_cols=1)
DepthwiseDepthfirstStrategyCommon (unsigned int output_size, unsigned int kernel_size, unsigned int stride=1)
virtual ~DepthwiseDepthfirstStrategyCommon ()
unsigned int get_output_rows () const override
unsigned int get_output_cols () const override
unsigned int get_kernel_rows () const override
unsigned int get_kernel_cols () const override
unsigned int get_stride_rows () const override
unsigned int get_stride_cols () const override
Public Member Functions inherited from DepthfirstStrategyUntyped
virtual arm_gemm::VLType get_vl_type () const =0
virtual unsigned int get_kernel_rows () const =0
virtual unsigned int get_kernel_cols () const =0
virtual unsigned int get_stride_rows () const =0
virtual unsigned int get_stride_cols () const =0
virtual unsigned int get_input_rows () const override
virtual unsigned int get_input_cols () const override
virtual unsigned int get_n_input_points () const
virtual unsigned int get_n_output_points () const
virtual unsigned int get_n_kernel_points () const
virtual unsigned int get_accumulator_depth_vl () const
virtual bool get_kernel_packing_point (const unsigned int index, unsigned int &x, unsigned int &y) const
Public Member Functions inherited from IDepthfirstStrategy
virtual ~IDepthfirstStrategy ()=default
virtual unsigned int get_output_rows () const =0
virtual unsigned int get_output_cols () const =0
Detailed Description
template<typename TInput, typename TWeight, typename TOutput, typename TAccum>
class arm_conv::depthwise::DepthfirstMultiplierStrategy< TInput, TWeight, TOutput, TAccum >
Definition at line 36 of file depthwise_depthfirst_multiplier.hpp.
Member Typedef Documentation
KernelType
using KernelType = std::function<void(const TInput *const *, TOutput *const *, const void *, unsigned int, TAccum, TAccum)>
Definition at line 87 of file depthwise_depthfirst_multiplier.hpp.
Member Function Documentation
get_kernel()
virtual KernelType get_kernel (void) const pure virtual
Referenced by StrategyType< IsGeneric, TInput, TWeight, TOutput, TAccum, OutputStage >::execute().
get_storage_size()
size_t get_storage_size (const DepthwiseArgs & args) const inline override virtual
Reimplemented from DepthfirstStrategy< TInput, TWeight, TOutput, TAccum, Nothing >.
Definition at line 68 of file depthwise_depthfirst_multiplier.hpp.
   {
     return interleaves::get_storage_size_generic(this->get_packing_args(args), args);
   }
References GemmTuner::args, and arm_conv::depthwise::interleaves::get_storage_size_generic().
pack_parameters()
void pack_parameters (const DepthwiseArgs & args, void * buffer, const void * biases, const Nothing & , const void * weights, size_t ld_weight_col, size_t ld_weight_row) const inline override virtual
Reimplemented from DepthfirstStrategy< TInput, TWeight, TOutput, TAccum, Nothing >.
Definition at line 73 of file depthwise_depthfirst_multiplier.hpp.
   {
     interleaves::pack_parameters_generic(
       this->get_packing_args(args), args,
       buffer, biases, weights, ld_weight_col, ld_weight_row
     );
   }
References GemmTuner::args, and arm_conv::depthwise::interleaves::pack_parameters_generic().
The documentation for this class was generated from the following file:
src/core/NEON/kernels/arm_conv/depthwise/depthwise_depthfirst_multiplier.hpp