Compute Library: ClConcatenate Class Reference
ClConcatenate Class Reference
Basic function to execute concatenate tensors along a given axis.
#include <ClConcatenate.h>
Public Member Functions
ClConcatenate ()=default
void configure (const ClCompileContext &compile_context, const std::vector< ITensorInfo * > &src_vector, ITensorInfo *dst, size_t axis)
Initialise the kernel's inputs vector and dst.
void run (ITensorPack &tensors) override
Run the kernels contained in the function.
Public Member Functions inherited from ICLOperator
ICLOperator (IRuntimeContext *ctx=nullptr)
Constructor.
ICLOperator (const ICLOperator &)=delete
Prevent instances of this class from being copied (As this class contains pointers)
ICLOperator (ICLOperator &&)=default
Default move constructor.
ICLOperator & operator= (const ICLOperator &)=delete
Prevent instances of this class from being copied (As this class contains pointers)
ICLOperator & operator= (ICLOperator &&)=default
Default move assignment operator.
void prepare (ITensorPack &constants) override
Prepare the function for executing.
MemoryRequirements workspace () const override
Return the memory requirements required by the workspace.
Public Member Functions inherited from IOperator
virtual ~IOperator ()=default
Destructor.
Static Public Member Functions
static Status validate (const std::vector< const ITensorInfo * > &src_vector, const ITensorInfo *dst, size_t axis)
Static function to check if given info will lead to a valid configuration.
Detailed Description
Basic function to execute concatenate tensors along a given axis.
This function calls the following kernels:
kernels::ClWidthConcatenateKernel (if underlying concatenation axis is 0).
kernels::ClHeightConcatenateKernel (if underlying concatenation axis is 1).
kernels::ClDepthConcatenateKernel (if underlying concatenation axis is 2).
kernels::ClBatchConcatenateKernel (if underlying concatenation axis is 3).
Definition at line 44 of file ClConcatenate.h.
Constructor & Destructor Documentation
ClConcatenate()
ClConcatenate () default
Member Function Documentation
configure()
void configure (const ClCompileContext & compile_context, const std::vector< ITensorInfo * > & src_vector, ITensorInfo * dst, size_t axis)
Initialise the kernel's inputs vector and dst.
Note
Input and dst tensor dimensions preconditions defer depending on the concatenation axis.
Preconditions can be found respectively at kernels::ClWidthConcatenateKernel, kernels::ClHeightConcatenateKernel and kernels::ClDepthConcatenateKernel.
Parameters
[in] compile_context The compile context to be used.
[in,out] src_vector The vectors containing all the tensors info to concatenate. Data types supported: All
[out] dst Destination tensor info. Data types supported: same as src_vector.
[in] axis Concatenation axis. Supported underlying concatenation axis are 0, 1, 2 and 3.
Definition at line 47 of file ClConcatenate.cpp.
 {
     ARM_COMPUTE_ERROR_ON(dst == nullptr);
     ARM_COMPUTE_LOG_PARAMS(src_vector, dst, axis);
     _axis       = axis;
     _num_inputs = src_vector.size();
     TensorShape                      dst_shape = arm_compute::misc::shape_calculator::calculate_concatenate_shape(src_vector, _axis);
     std::vector<const ITensorInfo *> const_src_vector(src_vector.size());
     std::transform(src_vector.begin(), src_vector.end(), const_src_vector.begin(), [](ITensorInfo * t)
     {
         ARM_COMPUTE_ERROR_ON_NULLPTR(t);
         return t;
     });
     // dst auto inizialitation if not yet initialized
     auto_init_if_empty(*dst, dst_shape, 1, src_vector[0]->data_type());
     ARM_COMPUTE_ERROR_THROW_ON(ClConcatenate::validate(const_src_vector, dst, axis));
     unsigned int offset = 0;
     switch(_axis)
     {
         case Window::DimX:
         {
             switch(_num_inputs)
             {
                 case 2:
                 {
                     // Configure WidthConcatenate2Tensors kernel
                     auto kernel = std::make_unique<kernels::ClWidthConcatenate2TensorsKernel>();
                     kernel->configure(compile_context, src_vector.at(0), src_vector.at(1), dst);
                     _concat_kernels.emplace_back(std::move(kernel));
                     break;
                 }
                 case 4:
                 {
                     // Configure WidthConcatenate4Tensors kernel
                     auto kernel = std::make_unique<kernels::ClWidthConcatenate4TensorsKernel>();
                     kernel->configure(compile_context, src_vector.at(0), src_vector.at(1), src_vector.at(2), src_vector.at(3), dst);
                     _concat_kernels.emplace_back(std::move(kernel));
                     break;
                 }
                 default:
                 {
                     // Configure generic case WidthConcatenate kernels
                     for(unsigned int i = 0; i < _num_inputs; ++i)
                     {
                         auto kernel = std::make_unique<kernels::ClWidthConcatenateKernel>();
                         kernel->configure(compile_context, src_vector.at(i), offset, dst);
                         offset += src_vector.at(i)->dimension(_axis);
                         _concat_kernels.emplace_back(std::move(kernel));
                     }
                     break;
                 }
             }
             break;
         }
         case Window::DimY:
         {
             for(unsigned int i = 0; i < _num_inputs; ++i)
             {
                 auto kernel = std::make_unique<kernels::ClHeightConcatenateKernel>();
                 kernel->configure(compile_context, src_vector.at(i), offset, dst);
                 offset += src_vector.at(i)->dimension(_axis);
                 _concat_kernels.emplace_back(std::move(kernel));
             }
             break;
         }
         case Window::DimZ:
         {
             for(unsigned int i = 0; i < _num_inputs; ++i)
             {
                 auto kernel = std::make_unique<kernels::ClDepthConcatenateKernel>();
                 kernel->configure(compile_context, src_vector.at(i), offset, dst);
                 offset += src_vector.at(i)->dimension(_axis);
                 _concat_kernels.emplace_back(std::move(kernel));
             }
             break;
         }
         case 3:
         {
             for(unsigned int i = 0; i < _num_inputs; ++i)
             {
                 auto kernel = std::make_unique<kernels::ClBatchConcatenateKernel>();
                 kernel->configure(compile_context, src_vector.at(i), offset, dst);
                 offset += src_vector.at(i)->dimension(_axis);
                 _concat_kernels.emplace_back(std::move(kernel));
             }
             break;
         }
         default:
             ARM_COMPUTE_ERROR("Axis not supported");
     }
 }
References ARM_COMPUTE_ERROR, ARM_COMPUTE_ERROR_ON, ARM_COMPUTE_ERROR_THROW_ON, ARM_COMPUTE_LOG_PARAMS, arm_compute::auto_init_if_empty(), arm_compute::misc::shape_calculator::calculate_concatenate_shape(), arm_compute::test::validation::data_type, Window::DimX, Window::DimY, Window::DimZ, arm_compute::test::validation::dst, arm_compute::test::validation::dst_shape, offset(), tf_frozen_model_extractor::t, and ClConcatenate::validate().
run()
void run (ITensorPack & tensors) override virtual
Run the kernels contained in the function.
Parameters
[in] tensors Vector that contains the tensors to operate on.
Reimplemented from ICLOperator.
Definition at line 219 of file ClConcatenate.cpp.
 {
     if(tensors.empty())
     {
         ARM_COMPUTE_ERROR("No inputs provided");
     }
     if(static_cast<int>(tensors.size()) - 1 != static_cast<int>(_num_inputs))
     {
         ARM_COMPUTE_ERROR("Configured with different number of inputs");
     }
     if(_axis == Window::DimX && (_num_inputs == 2 || _num_inputs == 4))
     {
         ARM_COMPUTE_ERROR_ON(_concat_kernels.empty());
         CLScheduler::get().enqueue_op(*_concat_kernels.at(0), tensors, true);
     }
     else
     {
         int i = 0;
         for(auto &k : _concat_kernels)
         {
             ITensorPack pack;
             pack.add_tensor(TensorType::ACL_SRC, tensors.get_const_tensor(ACL_SRC_VEC + i));
             pack.add_tensor(TensorType::ACL_DST, tensors.get_tensor(ACL_DST));
             CLScheduler::get().enqueue_op(*k, pack, true);
             ++i;
         }
     }
 }
References arm_compute::ACL_DST, arm_compute::ACL_SRC, arm_compute::ACL_SRC_VEC, ITensorPack::add_tensor(), ARM_COMPUTE_ERROR, ARM_COMPUTE_ERROR_ON, Window::DimX, ITensorPack::empty(), CLScheduler::enqueue_op(), CLScheduler::get(), ITensorPack::get_const_tensor(), ITensorPack::get_tensor(), arm_compute::test::validation::k, arm_compute::test::validation::pack, and ITensorPack::size().
validate()
Status validate (const std::vector< const ITensorInfo * > & src_vector, const ITensorInfo * dst, size_t axis) static
Static function to check if given info will lead to a valid configuration.
Similar to ClConcatenate::configure()
Returns
a status
Definition at line 142 of file ClConcatenate.cpp.
 {
     ARM_COMPUTE_RETURN_ERROR_ON(dst == nullptr);
     const unsigned int num_inputs = src_vector.size();
     ARM_COMPUTE_RETURN_ERROR_ON_NULLPTR(dst);
     ARM_COMPUTE_RETURN_ERROR_ON(num_inputs < 2);
     unsigned int offset = 0;
     switch(axis)
     {
         case Window::DimX:
         {
             switch(num_inputs)
             {
                 case 2:
                     // Validate WidthConcatenate2Tensors kernels if there are 2 inputs
                     ARM_COMPUTE_RETURN_ERROR_ON_NULLPTR(src_vector[0], src_vector[1]);
                     ARM_COMPUTE_RETURN_ON_ERROR(kernels::ClWidthConcatenate2TensorsKernel::validate(src_vector[0], src_vector[1], dst));
                     break;
                 case 4:
                     // Validate WidthConcatenate4Tensors kernels if there are 4 inputs
                     ARM_COMPUTE_RETURN_ERROR_ON_NULLPTR(src_vector[0], src_vector[1], src_vector[2], src_vector[3]);
                     ARM_COMPUTE_RETURN_ON_ERROR(kernels::ClWidthConcatenate4TensorsKernel::validate(src_vector[0], src_vector[1], src_vector[2], src_vector[3], dst));
                     break;
                 default:
                     // Validate generic case of WidthConcatenate kernel
                     for(const auto &src : src_vector)
                     {
                         ARM_COMPUTE_RETURN_ERROR_ON_NULLPTR(src);
                         ARM_COMPUTE_RETURN_ON_ERROR(kernels::ClWidthConcatenateKernel::validate(src, offset, dst));
                         offset += src->dimension(axis);
                     }
                     break;
             }
             break;
         }
         case Window::DimY:
         {
             for(const auto &src : src_vector)
             {
                 ARM_COMPUTE_RETURN_ON_ERROR(kernels::ClHeightConcatenateKernel::validate(src, offset, dst));
                 offset += src->dimension(axis);
             }
             break;
         }
         case Window::DimZ:
         {
             for(const auto &src : src_vector)
             {
                 ARM_COMPUTE_RETURN_ON_ERROR(kernels::ClDepthConcatenateKernel::validate(src, offset, dst));
                 offset += src->dimension(axis);
             }
             break;
         }
         case 3:
         {
             for(const auto &src : src_vector)
             {
                 ARM_COMPUTE_RETURN_ON_ERROR(kernels::ClBatchConcatenateKernel::validate(src, offset, dst));
                 offset += src->dimension(axis);
             }
             break;
         }
         default:
             ARM_COMPUTE_ERROR("Axis not supported");
     }
     if(dst->total_size() != 0)
     {
         TensorShape dst_shape = arm_compute::misc::shape_calculator::calculate_concatenate_shape(src_vector, axis);
         ARM_COMPUTE_RETURN_ERROR_ON(dst_shape.total_size() != dst->tensor_shape().total_size());
     }
     return Status{};
 }
References ARM_COMPUTE_ERROR, ARM_COMPUTE_RETURN_ERROR_ON, ARM_COMPUTE_RETURN_ERROR_ON_NULLPTR, ARM_COMPUTE_RETURN_ON_ERROR, arm_compute::misc::shape_calculator::calculate_concatenate_shape(), Window::DimX, Window::DimY, Window::DimZ, arm_compute::test::validation::dst, arm_compute::test::validation::dst_shape, offset(), arm_compute::test::validation::src, TensorShape::total_size(), ClWidthConcatenate2TensorsKernel::validate(), ClHeightConcatenateKernel::validate(), ClWidthConcatenateKernel::validate(), ClWidthConcatenate4TensorsKernel::validate(), ClBatchConcatenateKernel::validate(), and ClDepthConcatenateKernel::validate().
Referenced by ClConcatenate::configure(), and CLConcatenateLayer::validate().
The documentation for this class was generated from the following files:
src/gpu/cl/operators/ClConcatenate.h
src/gpu/cl/operators/ClConcatenate.cpp