Compute Library: Measurement Class Reference
Measurement Class Reference
Public Member Functions
def get_total_ms (self)
def is_close_to (self, other, tol)
def is_better_than (self, other, tol)
def __add__ (self, other)
def __sub__ (self, other)
def __mul__ (self, other)
def __floordiv__ (self, other)
def __truediv__ (self, other)
def __pow__ (self, power)
def __str__ (self)
Detailed Description
Definition at line 134 of file GemmTuner.py.
Member Function Documentation
__add__()
def __add__ (self, other)
Definition at line 149 of file GemmTuner.py.
     def __add__(self, other):
         return Measurement(
             self.opencl_timer_ms_reshape + other.opencl_timer_ms_reshape,
             self.opencl_timer_ms_kernel + other.opencl_timer_ms_kernel,
         )
__floordiv__()
def __floordiv__ (self, other)
Definition at line 167 of file GemmTuner.py.
     def __floordiv__(self, other):
         return Measurement(
             self.opencl_timer_ms_reshape // other.opencl_timer_ms_reshape,
             self.opencl_timer_ms_kernel // other.opencl_timer_ms_kernel,
         )
__mul__()
def __mul__ (self, other)
Definition at line 161 of file GemmTuner.py.
     def __mul__(self, other):
         return Measurement(
             self.opencl_timer_ms_reshape * other.opencl_timer_ms_reshape,
             self.opencl_timer_ms_kernel * other.opencl_timer_ms_kernel,
         )
__pow__()
def __pow__ (self, power)
Definition at line 179 of file GemmTuner.py.
     def __pow__(self, power):
         return Measurement(
             self.opencl_timer_ms_reshape ** power, self.opencl_timer_ms_kernel ** power
         )
__str__()
def __str__ (self)
Definition at line 184 of file GemmTuner.py.
     def __str__(self):
         return ",".join(map(str, self))
 # GEMMConfig Type
References arm_compute.join(), and arm_compute::utils.map().
__sub__()
def __sub__ (self, other)
Definition at line 155 of file GemmTuner.py.
     def __sub__(self, other):
         return Measurement(
             self.opencl_timer_ms_reshape - other.opencl_timer_ms_reshape,
             self.opencl_timer_ms_kernel - other.opencl_timer_ms_kernel,
         )
__truediv__()
def __truediv__ (self, other)
Definition at line 173 of file GemmTuner.py.
     def __truediv__(self, other):
         return Measurement(
             self.opencl_timer_ms_reshape / other.opencl_timer_ms_reshape,
             self.opencl_timer_ms_kernel / other.opencl_timer_ms_kernel,
         )
get_total_ms()
def get_total_ms (self)
Definition at line 138 of file GemmTuner.py.
     def get_total_ms(self):
         return self.opencl_timer_ms_reshape + self.opencl_timer_ms_kernel
Referenced by Measurement.is_better_than(), and Measurement.is_close_to().
is_better_than()
def is_better_than (self, other, tol)
Definition at line 144 of file GemmTuner.py.
     def is_better_than(self, other, tol):
         return self.get_total_ms() < other.get_total_ms() and not self.is_close_to(
             other
         )
References Measurement.get_total_ms(), and Measurement.is_close_to().
is_close_to()
def is_close_to (self, other, tol)
Definition at line 141 of file GemmTuner.py.
     def is_close_to(self, other, tol):
         return math.fabs(self.get_total_ms() - other.get_total_ms()) < tol
References Measurement.get_total_ms().
Referenced by Measurement.is_better_than().
The documentation for this class was generated from the following file:
examples/gemm_tuner/GemmTuner.py