Compute Library: CLPermute Class Reference
CLPermute Class Reference
Basic function to execute an opencl::kernels::ClPermuteKernel.
#include <CLPermute.h>
Public Member Functions
CLPermute ()
Constructor.
~CLPermute ()
Destructor.
CLPermute (const CLPermute &)=delete
Prevent instances of this class from being copied (As this class contains pointers)
CLPermute (CLPermute &&)=default
Default move constructor.
CLPermute & operator= (const CLPermute &)=delete
Prevent instances of this class from being copied (As this class contains pointers)
CLPermute & operator= (CLPermute &&)=default
Default move assignment operator.
void configure (const ICLTensor *input, ICLTensor *output, const PermutationVector &perm)
Set the input and output tensors.
void configure (const CLCompileContext &compile_context, const ICLTensor *input, ICLTensor *output, const PermutationVector &perm)
Set the input and output tensors.
void run () override
Run the kernels contained in the function.
Public Member Functions inherited from IFunction
virtual ~IFunction ()=default
Destructor.
virtual void prepare ()
Prepare the function for executing.
Static Public Member Functions
static Status validate (const ITensorInfo *input, const ITensorInfo *output, const PermutationVector &perm)
Static function to check if given info will lead to a valid configuration of CLPermute.
Detailed Description
Basic function to execute an opencl::kernels::ClPermuteKernel.
Definition at line 39 of file CLPermute.h.
Constructor & Destructor Documentation
CLPermute() [1/3]
CLPermute ()
Constructor.
Definition at line 44 of file CLPermute.cpp.
     : _impl(std::make_unique<Impl>())
 {
 }
~CLPermute()
~CLPermute () default
Destructor.
CLPermute() [2/3]
CLPermute (const CLPermute &) delete
Prevent instances of this class from being copied (As this class contains pointers)
CLPermute() [3/3]
CLPermute (CLPermute &&) default
Default move constructor.
Member Function Documentation
configure() [1/2]
void configure (const CLCompileContext & compile_context, const ICLTensor * input, ICLTensor * output, const PermutationVector & perm)
Set the input and output tensors.
Note
Arbitrary permutation vectors are supported with rank not greater than 4
Parameters
[in] compile_context The compile context to be used.
[in] input The input tensor to permute. Data types supported: All.
[in] output The output tensor. Data types supported: Same as input
[in] perm Permutation vector
Definition at line 56 of file CLPermute.cpp.
 {
     ARM_COMPUTE_ERROR_ON_NULLPTR(input, output);
     ARM_COMPUTE_LOG_PARAMS(input, output, perm);
     _impl->src = input;
     _impl->dst = output;
     _impl->op = std::make_unique<opencl::ClPermute>();
     _impl->op->configure(compile_context, _impl->src->info(), _impl->dst->info(), perm);
 }
References ARM_COMPUTE_ERROR_ON_NULLPTR, ARM_COMPUTE_LOG_PARAMS, and arm_compute::test::validation::input.
configure() [2/2]
void configure (const ICLTensor * input, ICLTensor * output, const PermutationVector & perm)
Set the input and output tensors.
Valid data layouts:
NHWC
NCHW
Valid data type configurations:
src dst
All All
Note
Arbitrary permutation vectors are supported with rank not greater than 4
Parameters
[in] input The input tensor to permute. Data types supported: All.
[in] output The output tensor. Data types supported: Same as input
[in] perm Permutation vector
Definition at line 51 of file CLPermute.cpp.
 {
     configure(CLKernelLibrary::get().get_compile_context(), input, output, perm);
 }
References CLKernelLibrary::get(), and arm_compute::test::validation::input.
Referenced by CLDepthwiseConvolutionLayer::configure(), CLFFTConvolutionLayer::configure(), CLGenerateProposalsLayer::configure(), and CLGEMMDeconvolutionLayer::configure().
operator=() [1/2]
CLPermute& operator= (CLPermute &&) default
Default move assignment operator.
operator=() [2/2]
CLPermute& operator= (const CLPermute &) delete
Prevent instances of this class from being copied (As this class contains pointers)
run()
void run () override virtual
Run the kernels contained in the function.
For CPU kernels:
Multi-threading is used for the kernels which are parallelisable.
By default std::thread::hardware_concurrency() threads are used.
Note
CPPScheduler::set_num_threads() can be used to manually set the number of threads
For OpenCL kernels:
All the kernels are enqueued on the queue associated with CLScheduler.
The queue is then flushed.
Note
The function will not block until the kernels are executed. It is the user's responsibility to wait.
Will call prepare() on first run if hasn't been done
Implements IFunction.
Definition at line 73 of file CLPermute.cpp.
 {
     ITensorPack pack;
     pack.add_tensor(TensorType::ACL_SRC, _impl->src);
     pack.add_tensor(TensorType::ACL_DST, _impl->dst);
     _impl->op->run(pack);
 }
References arm_compute::ACL_DST, arm_compute::ACL_SRC, ITensorPack::add_tensor(), and arm_compute::test::validation::pack.
Referenced by CLDepthwiseConvolutionLayer::prepare(), CLFFTConvolutionLayer::prepare(), CLGEMMDeconvolutionLayer::prepare(), CLDepthwiseConvolutionLayer::run(), CLFFTConvolutionLayer::run(), CLGEMMDeconvolutionLayer::run(), and CLGenerateProposalsLayer::run().
validate()
Status validate (const ITensorInfo * input, const ITensorInfo * output, const PermutationVector & perm) static
Static function to check if given info will lead to a valid configuration of CLPermute.
Note
Arbitrary permutation vectors are supported with rank not greater than 4
Parameters
[in] input First tensor input info. Data types supported: All.
[in] output Output tensor info. Data types supported: same as input.
[in] perm Permutation vector
Returns
a status
Definition at line 68 of file CLPermute.cpp.
 {
     return opencl::ClPermute::validate(input, output, perm);
 }
References arm_compute::test::validation::input, and ClPermute::validate().
Referenced by CLDepthwiseConvolutionLayer::validate(), CLGenerateProposalsLayer::validate(), and CLGEMMDeconvolutionLayer::validate().
The documentation for this class was generated from the following files:
arm_compute/runtime/CL/functions/CLPermute.h
src/runtime/CL/functions/CLPermute.cpp