Compute Library: Conv2dAttributes Class Reference
Conv2dAttributes Class Reference
Attributes are backend-agnostic parameters (in addition to the input/output tensors) of an operator.
#include <Conv2dAttributes.h>
Public Member Functions
Conv2dAttributes & pad (const Padding2D &pad)
Set padding.
Padding2D pad () const
Get padding.
Conv2dAttributes & stride (const Size2D &stride)
Set stride.
Size2D stride () const
Get stride.
Conv2dAttributes & dilation (const Size2D &dilation)
Set dilation.
Size2D dilation () const
Get dilation.
Detailed Description
Attributes are backend-agnostic parameters (in addition to the input/output tensors) of an operator.
Conv2d attributes
Definition at line 41 of file Conv2dAttributes.h.
Member Function Documentation
dilation() [1/2]
Size2D dilation () const
Get dilation.
Definition at line 56 of file Conv2dAttributes.cpp.
 {
     return _dilation;
 }
dilation() [2/2]
Conv2dAttributes & dilation (const Size2D & dilation)
Set dilation.
Definition at line 51 of file Conv2dAttributes.cpp.
 {
     _dilation = dilation;
     return *this;
 }
References Conv2dAttributes::dilation().
Referenced by arm_compute::test::convert_pad_stride_info_to_conv_attr(), Conv2dAttributes::dilation(), and arm_compute::operator<<().
pad() [1/2]
Padding2D pad () const
Get padding.
Definition at line 38 of file Conv2dAttributes.cpp.
 {
     return _pad;
 }
Referenced by Conv2dAttributes::pad().
pad() [2/2]
Conv2dAttributes & pad (const Padding2D & pad)
Set padding.
Definition at line 33 of file Conv2dAttributes.cpp.
 {
     _pad = pad;
     return *this;
 }
References Conv2dAttributes::pad().
Referenced by arm_compute::test::convert_pad_stride_info_to_conv_attr(), GpuConv2d::create_op(), ClTemplateDirectConv2d::get_tag_lut(), arm_compute::operator<<(), ClComponentDirectConv2d::validate(), and GpuCkwDirectConv2d::write_component_code().
stride() [1/2]
Size2D stride () const
Get stride.
Definition at line 47 of file Conv2dAttributes.cpp.
 {
     return _stride;
 }
Referenced by Conv2dAttributes::stride().
stride() [2/2]
Conv2dAttributes & stride (const Size2D & stride)
Set stride.
Definition at line 42 of file Conv2dAttributes.cpp.
 {
     _stride = stride;
     return *this;
 }
References Conv2dAttributes::stride().
Referenced by arm_compute::test::convert_pad_stride_info_to_conv_attr(), GpuConv2d::create_op(), ClTemplateDirectConv2d::get_config_id(), ClTemplateDirectConv2d::get_tag_lut(), arm_compute::operator<<(), ClComponentDirectConv2d::validate(), and GpuCkwDirectConv2d::write_component_code().
The documentation for this class was generated from the following files:
arm_compute/dynamic_fusion/sketch/attributes/Conv2dAttributes.h
src/dynamic_fusion/sketch/attributes/Conv2dAttributes.cpp