Compute Library: ClIndirectConv2d Class Reference
ClIndirectConv2d Class Reference
Basic function to execute indirect convolution on OpenCL.
#include <ClIndirectConv2d.h>
Public Member Functions
ClIndirectConv2d ()=default
void configure (const CLCompileContext &compile_context, ITensorInfo *src, ITensorInfo *weights, ITensorInfo *biases, ITensorInfo *dst, const PadStrideInfo &conv_info, const ActivationLayerInfo &act_info=ActivationLayerInfo())
Initialise the kernel's inputs and output.
void run (ITensorPack &tensors) override
Run the kernels contained in the function.
void prepare (ITensorPack &constants) override
Prepare the function for executing.
experimental::MemoryRequirements workspace () const override
Return the memory requirements required by the workspace.
Public Member Functions inherited from ICLOperator
ICLOperator (IRuntimeContext *ctx=nullptr)
Constructor.
ICLOperator (const ICLOperator &)=delete
Prevent instances of this class from being copied (As this class contains pointers)
ICLOperator (ICLOperator &&)=default
Default move constructor.
ICLOperator & operator= (const ICLOperator &)=delete
Prevent instances of this class from being copied (As this class contains pointers)
ICLOperator & operator= (ICLOperator &&)=default
Default move assignment operator.
Public Member Functions inherited from IOperator
virtual ~IOperator ()=default
Destructor.
Static Public Member Functions
static Status validate (const ITensorInfo *src, const ITensorInfo *weights, const ITensorInfo *biases, const ITensorInfo *dst, const PadStrideInfo &conv_info, const ActivationLayerInfo &act_info=ActivationLayerInfo())
Static function to check if given info will lead to a valid configuration.
Detailed Description
Basic function to execute indirect convolution on OpenCL.
This function calls the following OpenCL kernels:
kernels::ClIndirectConv2dAddressPrecalculationKernel
kernels::ClIndirectConv2dKernel
Definition at line 50 of file ClIndirectConv2d.h.
Constructor & Destructor Documentation
ClIndirectConv2d()
ClIndirectConv2d () default
Member Function Documentation
configure()
void configure (const CLCompileContext & compile_context, ITensorInfo * src, ITensorInfo * weights, ITensorInfo * biases, ITensorInfo * dst, const PadStrideInfo & conv_info, const ActivationLayerInfo & act_info = ActivationLayerInfo())
Initialise the kernel's inputs and output.
Valid data layouts:
NHWC
Valid data type configurations:
src0 src1 src2 dst
F32 F32 F32 F32
F16 F16 F16 F16
Note
All tensors must have the same data type.
Parameters
[in] compile_context The compile context to be used.
[in] src Source tensor. 3 lower dimensions represent a single src, while every optional dimension from 4 and above represent a batch of sources. Data types supported: F16/F32.
[in] weights Weights tensor. Weights are 4D tensor with dimensions. Data type supported:Same as src.
[in] biases Biases tensor. Shared biases supported. Biases are 1D tensor with dimensions [OFM]. Data type supported: Should match src data type.
[out] dst Destination tensor. 3 lower dimensions represent a single dst, while the rest represent batch of destinations. Data types supported: Same as src.
[in] conv_info Contains padding and stride information described in PadStrideInfo.
[in] act_info (Optional) Activation layer information in case of a fused activation.
Definition at line 62 of file ClIndirectConv2d.cpp.
 {
     ARM_COMPUTE_ERROR_ON_NULLPTR(src);
     ARM_COMPUTE_LOG_PARAMS(src, weights, biases, dst, conv_info, act_info);
     // Reuse the direct convolution descriptor
     const DirectConvComputeKernelInfo desc = config_indirect_convolution_nhwc(src, weights, conv_info);
     // Configure indirect convolution kernels
     auto k0 = std::make_unique<kernels::ClIndirectConv2dAddressPrecalculationKernel>();
     auto k1 = std::make_unique<kernels::ClIndirectConv2dKernel>();
     k0->set_target(CLScheduler::get().target());
     k1->set_target(CLScheduler::get().target());
     k0->configure(compile_context, src, weights, &_indirect_buffer, conv_info, desc);
     k1->configure(compile_context, src, weights, biases, &_indirect_buffer, dst, conv_info, act_info, desc);
     _addr_precalculation_kernel = std::move(k0);
     _indirect_conv_kernel       = std::move(k1);
     _is_prepared                = false;
     // Tune kernels
     CLScheduler::get().tune_kernel_static(*_indirect_conv_kernel);
     // Request memory for the indirect buffer
     _aux_mem[IndirectBuffer] = MemoryInfo(offset_int_vec(IndirectBuffer), MemoryLifetime::Persistent, _indirect_buffer.total_size());
 }
References arm_compute::test::validation::act_info, ARM_COMPUTE_ERROR_ON_NULLPTR, ARM_COMPUTE_LOG_PARAMS, arm_compute::test::validation::conv_info, arm_compute::test::validation::dst, CLScheduler::get(), and arm_compute::test::validation::src.
prepare()
void prepare (ITensorPack & constants) override virtual
Prepare the function for executing.
Any one off pre-processing step required by the function is handled here
Parameters
[in] constants Vector that contains the constants tensors.
Note
Prepare stage might not need all the function's buffers' backing memory to be available in order to execute
Reimplemented from ICLOperator.
Definition at line 125 of file ClIndirectConv2d.cpp.
 {
     if(!_is_prepared)
     {
         ICLTensor *indirect_buffer_aux = utils::cast::polymorphic_downcast<ICLTensor *>(constants.get_tensor(offset_int_vec(IndirectBuffer)));
         ARM_COMPUTE_ERROR_ON(indirect_buffer_aux == nullptr);
         ARM_COMPUTE_LOG_INFO_WITH_FUNCNAME_ACL("Preparing indirect buffer");
         CLAuxTensorHandler indirect_buffer(_indirect_buffer, *indirect_buffer_aux);
         ARM_COMPUTE_ERROR_ON(indirect_buffer.get()->cl_buffer().get() == nullptr);
         ITensorPack indirect_buffer_pack{ { ACL_DST, indirect_buffer.get() } };
         CLScheduler::get().enqueue_op(*_addr_precalculation_kernel, indirect_buffer_pack, true);
         _is_prepared = true;
     }
 }
run()
void run (ITensorPack & tensors) override virtual
Run the kernels contained in the function.
Parameters
[in] tensors Vector that contains the tensors to operate on.
Reimplemented from ICLOperator.
Definition at line 112 of file ClIndirectConv2d.cpp.
 {
     CLAuxTensorHandler indirect_buffer(offset_int_vec(IndirectBuffer), _indirect_buffer, tensors, true);
     prepare(tensors);
     ITensorPack indirect_conv2d_pack(tensors);
     indirect_conv2d_pack.add_const_tensor(ACL_SRC_3, indirect_buffer.get());
     // Run indirect convolution
     CLScheduler::get().enqueue_op(*_indirect_conv_kernel, indirect_conv2d_pack, true);
 }
References arm_compute::ACL_SRC_3, ITensorPack::add_const_tensor(), CLScheduler::enqueue_op(), CLScheduler::get(), CLAuxTensorHandler::get(), and arm_compute::offset_int_vec().
validate()
Status validate (const ITensorInfo * src, const ITensorInfo * weights, const ITensorInfo * biases, const ITensorInfo * dst, const PadStrideInfo & conv_info, const ActivationLayerInfo & act_info = ActivationLayerInfo()) static
Static function to check if given info will lead to a valid configuration.
Similar to ClIndirectConv2d::configure()
Returns
a status
Definition at line 92 of file ClIndirectConv2d.cpp.
 {
     // Initialize the direct convolution descriptor
     const DirectConvComputeKernelInfo desc = config_indirect_convolution_nhwc(src, weights, conv_info);
     TensorShape ind_buffer_shape = misc::shape_calculator::compute_indirect_buffer_shape(src->tensor_shape(),
                                                                                          src->data_layout(),
                                                                                          weights->tensor_shape(),
                                                                                          conv_info,
                                                                                          desc);
     TensorInfo indirect_buffer(ind_buffer_shape, 1, DataType::S32);
     ARM_COMPUTE_RETURN_ON_ERROR(kernels::ClIndirectConv2dAddressPrecalculationKernel::validate(src, weights, &indirect_buffer, conv_info, desc));
     ARM_COMPUTE_RETURN_ON_ERROR(kernels::ClIndirectConv2dKernel::validate(src, weights, biases, &indirect_buffer, dst, conv_info, act_info, desc));
     return Status{};
 }
References arm_compute::test::validation::act_info, ARM_COMPUTE_RETURN_ON_ERROR, arm_compute::misc::shape_calculator::compute_indirect_buffer_shape(), arm_compute::test::validation::conv_info, arm_compute::test::validation::dst, arm_compute::S32, arm_compute::test::validation::src, ITensorInfo::tensor_shape(), and arm_compute::validate().
Referenced by ClConv2d::get_convolution_method(), CLIndirectConvolutionLayer::validate(), and ClConv2d::validate().
workspace()
experimental::MemoryRequirements workspace () const override virtual
Return the memory requirements required by the workspace.
Reimplemented from ICLOperator.
Definition at line 144 of file ClIndirectConv2d.cpp.
 {
     return _aux_mem;
 }
The documentation for this class was generated from the following files:
src/gpu/cl/operators/ClIndirectConv2d.h
src/gpu/cl/operators/ClIndirectConv2d.cpp