Compute Library: ClTemplateDirectConv2d Class Reference
ClTemplateDirectConv2d Class Reference final
#include <ClTemplateDirectConv2d.h>
Public Types
using Attributes = ClComponentDirectConv2d::Attributes
using Settings = ClComponentDirectConv2d::Settings
Public Types inherited from IGpuTemplateComponentWriter
using ComponentGroup = GpuKernelComponentGroup
Public Member Functions
ClTemplateDirectConv2d (ComponentId id, const ArgumentPack< ITensorInfo > &tensors, const Attributes &attributes, const Settings &settings)
Constructor.
~ClTemplateDirectConv2d () override=default
Destructor.
ClTemplateDirectConv2d (const ClTemplateDirectConv2d &direct_conv2d)=delete
Prevent instances of this class from being copy constructed.
ClTemplateDirectConv2d & operator= (const ClTemplateDirectConv2d &direct_conv2d)=delete
Prevent instances of this class from being copied.
ClTemplateDirectConv2d (ClTemplateDirectConv2d &&direct_conv2d)=default
Allow instances of this class to be move constructed.
ClTemplateDirectConv2d & operator= (ClTemplateDirectConv2d &&direct_conv2d)=default
Allow instances of this class to be moved.
std::string get_name () const override
Generate kernel component name.
std::string get_component_code (const ComponentGroup &comp_group) const override
Generate kernel component code template.
void declare_variables (GpuKernelVariableTable &vtable, const ComponentGroup &comp_group) const override
Declare all variables used by the component in the vtable.
TagLUT get_tag_lut (const GpuKernelVariableTable &vtable, const ComponentGroup &comp_group) const override
Generate the tag look-up table used to instantiate the component code.
CLBuildOptions get_build_options (const ComponentGroup &comp_group) const override
Generate the build options used in the component.
std::string get_config_id () const override
Generate the component config id string used for tuning.
std::set< std::string > get_headers_list () const override
Generate the header list used in the component.
Window get_window () const override
Generate the execution window for the component.
Public Member Functions inherited from IGpuTemplateComponentWriter
IGpuTemplateComponentWriter (ComponentId id, const ArgumentPack< ITensorInfo > &tensors)
Constructor.
virtual ~IGpuTemplateComponentWriter ()
Destructor.
virtual std::string get_additional_macros () const
Generate additional macros used in the component.
ArgumentPack< ITensorInfo > tensors () const
Get tensor arguments.
ComponentId id () const
Get component id.
Additional Inherited Members
Static Public Attributes inherited from IGpuTemplateComponentWriter
static constexpr GpuKernelArgumentInfo::Type common_tensor_type = GpuKernelArgumentInfo::Type::Tensor_4D_t_Buffer
For now all kernel intermeditate/destination tensors are expected to be of type Tensor_4D_t_Buffer.
Detailed Description
Definition at line 39 of file ClTemplateDirectConv2d.h.
Member Typedef Documentation
Attributes
using Attributes = ClComponentDirectConv2d::Attributes
Definition at line 42 of file ClTemplateDirectConv2d.h.
Settings
using Settings = ClComponentDirectConv2d::Settings
Definition at line 43 of file ClTemplateDirectConv2d.h.
Constructor & Destructor Documentation
ClTemplateDirectConv2d() [1/3]
ClTemplateDirectConv2d (ComponentId id, const ArgumentPack< ITensorInfo > & tensors, const Attributes & attributes, const Settings & settings)
Constructor.
Similar to ClComponentDirectConv2d::validate()
Parameters
[in] id Component id
[in] tensors Tensor arguments to the components
[in] attributes Component attributes
[in] settings Component settings
Definition at line 42 of file ClTemplateDirectConv2d.cpp.
     : IGpuTemplateComponentWriter{ id, tensors },
       _src{},
       _weight{},
       _bias{},
       _dst{},
       _attributes{ attributes },
       _settings{ settings }
 {
     _src    = this->tensors().get_const_tensor(TensorType::ACL_SRC_0);
     _weight = this->tensors().get_const_tensor(TensorType::ACL_SRC_1);
     if(this->tensors().get_const_tensor(TensorType::ACL_SRC_2))
     {
         _bias = this->tensors().get_const_tensor(TensorType::ACL_SRC_2);
     }
     _dst = this->tensors().get_const_tensor(TensorType::ACL_DST_0);
     ARM_COMPUTE_ERROR_ON_NULLPTR(_src, _weight, _dst);
 }
References IGpuTemplateComponentWriter::id(), and IGpuTemplateComponentWriter::tensors().
~ClTemplateDirectConv2d()
~ClTemplateDirectConv2d () override default
Destructor.
ClTemplateDirectConv2d() [2/3]
ClTemplateDirectConv2d (const ClTemplateDirectConv2d & direct_conv2d) delete
Prevent instances of this class from being copy constructed.
ClTemplateDirectConv2d() [3/3]
ClTemplateDirectConv2d (ClTemplateDirectConv2d && direct_conv2d) default
Allow instances of this class to be move constructed.
Member Function Documentation
declare_variables()
void declare_variables (GpuKernelVariableTable & vtable, const ComponentGroup & comp_group) const override virtual
Declare all variables used by the component in the vtable.
Parameters
[out] vtable Variable table
[in] comp_group Component group of which the component is a part of
Implements IGpuTemplateComponentWriter.
Definition at line 228 of file ClTemplateDirectConv2d.cpp.
 {
     vtable.declare_variable(
         comp_group,
         _src,
         GpuKernelArgumentInfo(GpuKernelArgumentInfo::Type::Tensor_4D_t_Buffer),
         "src");
     const GpuKernelArgumentInfo::Type weight_type = _settings.export_to_cl_image() ? GpuKernelArgumentInfo::Type::Tensor_4D_t_Image : GpuKernelArgumentInfo::Type::Tensor_4D_t_Buffer;
     vtable.declare_variable(
         comp_group,
         _weight,
         GpuKernelArgumentInfo(weight_type),
         "weight");
     if(_bias && _bias->has_valid_id()) // optional bias
     {
         vtable.declare_variable(
             comp_group,
             _bias,
             GpuKernelArgumentInfo(GpuKernelArgumentInfo::Type::Vector),
             "bias");
     }
     vtable.declare_variable(
         comp_group,
         _dst,
         GpuKernelArgumentInfo(common_tensor_type),
         "dst");
 }
References IGpuTemplateComponentWriter::common_tensor_type, GpuKernelVariableTable::declare_variable(), ClComponentDirectConv2dSettings::export_to_cl_image(), ITensorInfo::has_valid_id(), GpuKernelArgumentInfo::Tensor_4D_t_Buffer, GpuKernelArgumentInfo::Tensor_4D_t_Image, and GpuKernelArgumentInfo::Vector.
get_build_options()
CLBuildOptions get_build_options (const ComponentGroup & comp_group) const override virtual
Generate the build options used in the component.
Parameters
[in] comp_group Component group of which the component is a part of
Returns
CLBuildOptions Build options
Reimplemented from IGpuTemplateComponentWriter.
Definition at line 323 of file ClTemplateDirectConv2d.cpp.
 {
     const unsigned int channel_idx = get_data_layout_dimension_index(_src->data_layout(), DataLayoutDimension::CHANNEL);
     const auto         root_window      = comp_group.get_root_component()->template_writer()->get_window();
     const unsigned int n0               = root_window.x().step();
     const unsigned int m0               = root_window.y().step();
     const unsigned int k0               = adjust_vec_size(_settings.direct_conv_descriptor().k0, _src->dimension(channel_idx));
     const unsigned int partial_store_n0 = _dst->dimension(0) % n0;
     CLBuildOptions build_opts{};
     if(_settings.fast_relaxed_math())
     {
         build_opts.add_option("-cl-fast-relaxed-math");
     }
     else
     {
         // -cl-fast-relaxed-math also sets -cl-finite-math-only and -cl-unsafe-math-optimizations
         // to disable -cl-finite-math-only, we only include -cl-unsafe-math-optimizations
         build_opts.add_option("-cl-unsafe-math-optimizations");
     }
     build_opts.add_option("-DN0=" + support::cpp11::to_string(n0));
     build_opts.add_option("-DM0=" + support::cpp11::to_string(m0));
     build_opts.add_option("-DK0=" + support::cpp11::to_string(k0));
     build_opts.add_option("-DPARTIAL_N0=" + support::cpp11::to_string(partial_store_n0));
     return build_opts;
 }
References CLBuildOptions::add_option(), arm_compute::adjust_vec_size(), arm_compute::CHANNEL, ITensorInfo::data_layout(), ITensorInfo::dimension(), ClComponentDirectConv2dSettings::direct_conv_descriptor(), ClComponentDirectConv2dSettings::fast_relaxed_math(), arm_compute::get_data_layout_dimension_index(), GpuKernelComponentGroup::get_root_component(), IGpuTemplateComponentWriter::get_window(), Window::Dimension::step(), IGpuKernelComponent::template_writer(), arm_compute::support::cpp11::to_string(), and Window::x().
get_component_code()
std::string get_component_code (const ComponentGroup & comp_group) const override virtual
Generate kernel component code template.
Parameters
[in] comp_group Component group of which the component is a part of
Returns
std::string Component code
Implements IGpuTemplateComponentWriter.
Definition at line 69 of file ClTemplateDirectConv2d.cpp.
 {
     ARM_COMPUTE_UNUSED(comp_group);
     const auto channel_idx   = get_data_layout_dimension_index(_src->data_layout(), DataLayoutDimension::CHANNEL);
     const auto k0            = adjust_vec_size(_settings.direct_conv_descriptor().k0, _src->dimension(channel_idx));
     const bool leftover_loop = (_src->dimension(channel_idx) % k0) != 0;
     std::string code = R"_(
 //------------------ START KERNEL {{meta_kernel_id}} ---------------------
 // IN_0(src)            {{src}}
 // IN_1(wei)            {{weight}}
 )_";
     if(_bias && _bias->has_valid_id())
     {
         code += R"_(
 // IN_1(bia)            {{bias}}
 )_";
     }
     code += R"_(
 // OUT(dst, accum)      {{dst}}
 TILE(uint, M0, 1, g_dst_indirect_y);
 {
 #define _IWEI_WIDTH {{WEI_WIDTH}}
 #define _IWEI_HEIGHT {{WEI_HEIGHT}}
 #define _ISRC_WIDTH {{SRC_WIDTH}}
 #define _ISRC_HEIGHT {{SRC_HEIGHT}}
 #define _ISRC_CHANNELS {{SRC_CHANNELS}}
 #define _IDST_WIDTH {{DST_WIDTH}}
 #define _IDST_HEIGHT {{DST_HEIGHT}}
 #define _IDST_CHANNELS {{DST_CHANNELS}}
 #define _IY_MULTIPLIER (_IWEI_WIDTH * _IWEI_HEIGHT)
     TILE(int, M0, 1, xi);
     TILE(int, M0, 1, yi);
     // Convert the linear index to coordinate
     LOOP_UNROLLING(int, i, 0, 1, M0,
     {
         xi[0].s[i] = ((g_ind_1 + i) % _IDST_WIDTH) * {{STRIDE_X}};
         yi[0].s[i] = ((g_ind_1 + i) / _IDST_WIDTH) * {{STRIDE_Y}};
         xi[0].s[i] -= {{PAD_LEFT}};
         yi[0].s[i] -= {{PAD_TOP}};
     })
     LOOP_UNROLLING(int, i, 0, 1, M0,
     {
         {{dst}}[i].v = 0;
     })
     for(int i = 0; i < (_IWEI_WIDTH * _IWEI_HEIGHT); ++i)
     {
         int xk = i % _IWEI_WIDTH;
         int yk = i / _IWEI_WIDTH;
         TILE(int, 1, M0, my);
         LOOP_UNROLLING(int, i, 0, 1, M0,
         {
             int x_s    = xi[0].s[i] + xk;
             int y_s    = yi[0].s[i] + yk;
             my[0].s[i] = x_s + y_s *_ISRC_WIDTH;
             my[0].s[i] = my[0].s[i] + g_ind_2 * (int)(_ISRC_WIDTH * _ISRC_HEIGHT);
             my[0].s[i] = select(-1, my[0].s[i], x_s >= 0);
             my[0].s[i] = select(-1, my[0].s[i], x_s < _ISRC_WIDTH);
             my[0].s[i] = select(-1, my[0].s[i], y_s >= 0);
             my[0].s[i] = select(-1, my[0].s[i], y_s < _ISRC_HEIGHT);
         })
         int ck = 0;
         for(; ck <= (_ISRC_CHANNELS - K0); ck += K0)
         {
             TILE({{SRC_DATA_TYPE}}, M0, K0, a);
             TILE({{WEI_DATA_TYPE}}, N0, K0, b);
             LOOP_UNROLLING(int, i, 0, 1, M0,
             {
                 a[i].v = {{ZERO_VALUE}};
             })
             LOOP_UNROLLING(int, i, 0, 1, N0,
             {
                 b[i].v = {{ZERO_VALUE}};
             })
             T_LOAD2D_INDIRECT({{SRC_DATA_TYPE}}, M0, K0, {{SRC_TENSOR_TYPE}}, {{src}}, ck, {{src}}_stride_y, my, a);
             T_LOAD({{WEI_DATA_TYPE}}, N0, K0, {{WEI_TENSOR_TYPE}}, {{weight}}, ck, g_ind_0 * _IY_MULTIPLIER + i, _IY_MULTIPLIER, {{weight}}_stride_y, b);
             T_MMUL({{SRC_DATA_TYPE}}, {{WEI_DATA_TYPE}}, {{ACC_DATA_TYPE}}, M0, N0, K0, NT, T, a, b, {{dst}});
         }
 )_";
     if(leftover_loop)
     {
         code += R"_(
         for(; ck < _ISRC_CHANNELS; ++ck)
         {
             TILE({{SRC_DATA_TYPE}}, M0, 1, a);
             TILE({{WEI_DATA_TYPE}}, N0, 1, b);
             LOOP_UNROLLING(int, i, 0, 1, M0,
             {
                 a[i].v = {{ZERO_VALUE}};
             })
             LOOP_UNROLLING(int, i, 0, 1, N0,
             {
                 b[i].v = {{ZERO_VALUE}};
             })
             T_LOAD2D_INDIRECT({{SRC_DATA_TYPE}}, M0, 1, {{SRC_TENSOR_TYPE}}, {{src}}, ck, {{src}}_stride_y, my, a);
             T_LOAD({{WEI_DATA_TYPE}}, N0, 1, BUFFER, {{weight}}, ck, g_ind_0 * _IY_MULTIPLIER + i, _IY_MULTIPLIER, {{weight}}_stride_y, b);
             T_MMUL({{SRC_DATA_TYPE}}, {{WEI_DATA_TYPE}}, {{ACC_DATA_TYPE}}, M0, N0, 1, NT, T, a, b, {{dst}});
         }
     )_";
 }
 code += R"_(
 #undef _I_WEI_WIDTH
 #undef _I_WEI_HEIGHT
 #undef _ISRC_WIDTH
 #undef _ISRC_HEIGHT
 #undef _ISRC_CHANNELS
 #undef _IDST_WIDTH
 #undef _IDST_HEIGHT
 #undef _IDST_CHANNELS
 #undef _IY_MULTIPLIER
     }
 )_";
     if(_bias && _bias->has_valid_id())
     {
         code += R"_(
         TILE({{BIA_DATA_TYPE}}, 1, N0, bias0);
         T_LOAD({{BIA_DATA_TYPE}}, 1, N0, BUFFER, {{bias}}, g_ind_0, 0, 1, 0, bias0);
         T_ELTWISE_BROADCAST_ADD_X({{ACC_DATA_TYPE}}, M0, N0, {{dst}}, bias0, {{dst}});
     )_";
 }
 code += R"_(
     LOOP_UNROLLING(int, i, 0, 1, M0,
     {
         g_dst_indirect_y[i].v = (uint)min(g_ind_1 + i, (int)({{DST_WIDTH}} * {{DST_HEIGHT}}) - 1);
         g_dst_indirect_y[i].v += g_ind_2 * (int)({{DST_WIDTH}} * {{DST_HEIGHT}});
     })
 }
 //------------------ END KERNEL {{meta_kernel_id}} ---------------------
 )_";
     return code;
 }
References arm_compute::adjust_vec_size(), ARM_COMPUTE_UNUSED, arm_compute::CHANNEL, ITensorInfo::data_layout(), ITensorInfo::dimension(), ClComponentDirectConv2dSettings::direct_conv_descriptor(), arm_compute::get_data_layout_dimension_index(), and ITensorInfo::has_valid_id().
get_config_id()
std::string get_config_id () const override virtual
Generate the component config id string used for tuning.
Reimplemented from IGpuTemplateComponentWriter.
Definition at line 353 of file ClTemplateDirectConv2d.cpp.
 {
     const DataType   data_type   = _src->data_type();
     const DataLayout data_layout = _src->data_layout();
     const unsigned int width_idx  = get_data_layout_dimension_index(data_layout, DataLayoutDimension::WIDTH);
     const unsigned int height_idx = get_data_layout_dimension_index(data_layout, DataLayoutDimension::HEIGHT);
     const unsigned int kernel_size = _weight->dimension(width_idx);
     std::string config_id{};
     config_id += lower_string(string_from_data_type(data_type));
     config_id += "_";
     config_id += support::cpp11::to_string(kernel_size);
     config_id += "_";
     config_id += support::cpp11::to_string(_attributes.stride().x());
     config_id += "_";
     config_id += support::cpp11::to_string(_attributes.stride().y());
     config_id += "_";
     config_id += support::cpp11::to_string(_dst->dimension(width_idx));
     config_id += "_";
     config_id += support::cpp11::to_string(_dst->dimension(height_idx));
     config_id += "_";
     config_id += lower_string(string_from_data_layout(data_layout));
     return config_id;
 }
References ITensorInfo::data_layout(), arm_compute::test::validation::data_layout, arm_compute::test::validation::data_type, ITensorInfo::data_type(), ITensorInfo::dimension(), arm_compute::get_data_layout_dimension_index(), arm_compute::HEIGHT, arm_compute::lower_string(), Conv2dAttributes::stride(), arm_compute::string_from_data_layout(), arm_compute::string_from_data_type(), arm_compute::support::cpp11::to_string(), and arm_compute::WIDTH.
get_headers_list()
std::set< std::string > get_headers_list () const override virtual
Generate the header list used in the component.
Reimplemented from IGpuTemplateComponentWriter.
Definition at line 380 of file ClTemplateDirectConv2d.cpp.
 {
     return std::set<std::string>{ "helpers.h", "tile_helpers.h" };
 }
get_name()
std::string get_name () const override virtual
Generate kernel component name.
Implements IGpuTemplateComponentWriter.
Definition at line 64 of file ClTemplateDirectConv2d.cpp.
 {
     return "direct_conv2d";
 }
get_tag_lut()
TagLUT get_tag_lut (const GpuKernelVariableTable & vtable, const ComponentGroup & comp_group) const override virtual
Generate the tag look-up table used to instantiate the component code.
Parameters
[in] vtable Variable table
[in] comp_group Component group of which the component is a part of
Returns
TagLUT Tag lookup table
Implements IGpuTemplateComponentWriter.
Definition at line 258 of file ClTemplateDirectConv2d.cpp.
 {
     TagLUT lut{};
     // Arguments and global shared variables
     lut["src"]    = vtable.get_variable(_src);
     lut["weight"] = vtable.get_variable(_weight);
     if(_bias && _bias->has_valid_id()) // optional bias
     {
         lut["bias"]          = vtable.get_variable(_bias);
         lut["BIA_DATA_TYPE"] = get_cl_type_from_data_type(_bias->data_type());
     }
     lut["dst"] = vtable.get_variable(_dst);
     const auto dst_argument = vtable.get_variable(comp_group.get_any_dst_tensor());
     lut["arg_dst"]          = dst_argument.uniq_name;
     // Local build options
     lut["meta_kernel_id"] = id();
     lut["ACC_DATA_TYPE"]  = _src->data_type();
     lut["SRC_DATA_TYPE"]  = _src->data_type();
     lut["WEI_DATA_TYPE"]  = _weight->data_type();
     lut["SRC_TENSOR_TYPE"] = "BUFFER";
     switch(vtable.get_variable(_weight).kernel_argument_info.type)
     {
         case GpuKernelArgumentInfo::Type::Image_Export_To_ClImage2D:
         case GpuKernelArgumentInfo::Type::Image_3D_Export_To_ClImage2D:
         case GpuKernelArgumentInfo::Type::Tensor_4D_t_Image:
     {
         lut["WEI_TENSOR_TYPE"] = "IMAGE";
         break;
     }
         default:
     {
         lut["WEI_TENSOR_TYPE"] = "BUFFER";
         break;
     }
     }
     const auto width_idx  = 1;
     const auto height_idx = 2;
     const auto channel_idx = 0;
     lut["SRC_WIDTH"] = _src->dimension(width_idx);
     lut["SRC_HEIGHT"] = _src->dimension(height_idx);
     lut["SRC_CHANNELS"] = _src->dimension(channel_idx);
     lut["WEI_WIDTH"]      = _weight->dimension(width_idx);
     lut["WEI_HEIGHT"]     = _weight->dimension(height_idx);
     lut["DST_WIDTH"] = _dst->dimension(width_idx);
     lut["DST_HEIGHT"] = _dst->dimension(height_idx);
     lut["DST_CHANNELS"] = _dst->dimension(channel_idx);
     lut["STRIDE_X"] = _attributes.stride().x();
     lut["STRIDE_Y"] = _attributes.stride().y();
     lut["PAD_LEFT"] = _attributes.pad().left;
     lut["PAD_TOP"]  = _attributes.pad().top;
     lut["ZERO_VALUE"] = 0;
     return lut;
 }
References ITensorInfo::data_type(), ITensorInfo::dimension(), GpuKernelComponentGroup::get_any_dst_tensor(), arm_compute::get_cl_type_from_data_type(), GpuKernelVariableTable::get_variable(), ITensorInfo::has_valid_id(), IGpuTemplateComponentWriter::id(), GpuKernelArgumentInfo::Image_3D_Export_To_ClImage2D, GpuKernelArgumentInfo::Image_Export_To_ClImage2D, GpuKernelVariableTable::TensorVariable::kernel_argument_info, Conv2dAttributes::pad(), Conv2dAttributes::stride(), GpuKernelArgumentInfo::Tensor_4D_t_Image, GpuKernelArgumentInfo::type, and GpuKernelVariableTable::TensorVariable::uniq_name.
get_window()
Window get_window () const override virtual
Generate the execution window for the component.
Reimplemented from IGpuTemplateComponentWriter.
Definition at line 385 of file ClTemplateDirectConv2d.cpp.
 {
     ARM_COMPUTE_ERROR_ON_MSG(_dst->tensor_shape().total_size() == 0U, "Destination tensor is not initialized");
     const auto output_shape = _dst->tensor_shape();
     const auto desc         = _settings.direct_conv_descriptor();
     const unsigned int n0 = adjust_vec_size(desc.n0, output_shape[0]);
     const unsigned int m0 = adjust_vec_size(desc.m0, output_shape[1] * output_shape[2]);
     // Create and configure kernel window
     Window win = calculate_max_window(output_shape, Steps(n0, m0));
     const size_t dim_y_collapsed = ceil_to_multiple(output_shape[1] * output_shape[2], m0);
     win.set(Window::DimY, Window::Dimension(0, dim_y_collapsed, m0));
     win.set(Window::DimZ, Window::Dimension(0, output_shape.total_size_upper(3), 1));
     return win;
 }
References arm_compute::adjust_vec_size(), ARM_COMPUTE_ERROR_ON_MSG, arm_compute::calculate_max_window(), arm_compute::ceil_to_multiple(), Window::DimY, Window::DimZ, ClComponentDirectConv2dSettings::direct_conv_descriptor(), arm_compute::test::validation::output_shape, Window::set(), ITensorInfo::tensor_shape(), TensorShape::total_size(), and arm_compute::utils::cast::U.
operator=() [1/2]
ClTemplateDirectConv2d& operator= (ClTemplateDirectConv2d && direct_conv2d) default
Allow instances of this class to be moved.
operator=() [2/2]
ClTemplateDirectConv2d& operator= (const ClTemplateDirectConv2d & direct_conv2d) delete
Prevent instances of this class from being copied.
The documentation for this class was generated from the following files:
src/dynamic_fusion/sketch/gpu/template_writer/cl/ClTemplateDirectConv2d.h
src/dynamic_fusion/sketch/gpu/template_writer/cl/ClTemplateDirectConv2d.cpp