Compute Library: CpuGemmLowpOffsetContributionOutputStageKernel Class Reference
CpuGemmLowpOffsetContributionOutputStageKernel Class Reference
Kernel used to add the offset contribution and perform the output stage after CpuGemmLowpMatrixMultiplyKernel.
#include <CpuGemmLowpOffsetContributionOutputStageKernel.h>
Public Member Functions
CpuGemmLowpOffsetContributionOutputStageKernel ()=default
Default constructor.
ARM_COMPUTE_DISALLOW_COPY_ALLOW_MOVE (CpuGemmLowpOffsetContributionOutputStageKernel)
void configure (const ITensorInfo *mm_result, const ITensorInfo *vector_sum_col, const ITensorInfo *vector_sum_row, const ITensorInfo *bias, ITensorInfo *dst, int32_t k, int32_t a_offset, int32_t b_offset, GEMMLowpOutputStageInfo output_stage)
Initialise the kernel inputs and output.
void run_op (ITensorPack &tensors, const Window &window, const ThreadInfo &info) override
Execute the kernel on the passed window.
const char * name () const override
Name of the kernel.
Public Member Functions inherited from ICPPKernel
virtual ~ICPPKernel ()=default
Default destructor.
virtual void run (const Window &window, const ThreadInfo &info)
Execute the kernel on the passed window.
virtual void run_nd (const Window &window, const ThreadInfo &info, const Window &thread_locator)
legacy compatibility layer for implemantions which do not support thread_locator In these cases we simply narrow the interface down the legacy version
virtual size_t get_mws (const CPUInfo &platform, size_t thread_count) const
Return minimum workload size of the relevant kernel.
Public Member Functions inherited from IKernel
IKernel ()
Constructor.
virtual ~IKernel ()=default
Destructor.
virtual bool is_parallelisable () const
Indicates whether or not the kernel is parallelisable.
virtual BorderSize border_size () const
The size of the border for that kernel.
const Window & window () const
The maximum window the kernel can be executed on.
bool is_window_configured () const
Function to check if the embedded window of this kernel has been configured.
Static Public Member Functions
static Status validate (const ITensorInfo *mm_result, const ITensorInfo *vector_sum_col, const ITensorInfo *vector_sum_row, const ITensorInfo *bias, const ITensorInfo *dst, int32_t a_offset, int32_t b_offset, GEMMLowpOutputStageInfo output_stage)
Static function to check if given info will lead to a valid configuration.
Static Public Member Functions inherited from ICpuKernel< CpuGemmLowpOffsetContributionOutputStageKernel >
static const auto * get_implementation (const SelectorType &selector, KernelSelectionType selection_type=KernelSelectionType::Supported)
Micro-kernel selector.
Additional Inherited Members
Static Public Attributes inherited from ICPPKernel
static constexpr size_t default_mws = 1
Detailed Description
Kernel used to add the offset contribution and perform the output stage after CpuGemmLowpMatrixMultiplyKernel.
The computation is performed in-place
This kernel takes a final int32 accumulator value (the output of CpuGemmLowpMatrixMultiplyKernel), and adds to it the offset contribution of matrix A and matrix B in-place.
The output stage can perform either QuantizeDownInt32ToUint8Scale or QuantizeDownInt32ToUint8ScaleByFixedPoint for Uint8. The output stage can perform either QuantizeDownInt32ToInt8Scale or QuantizeDownInt32ToInt8ScaleByFixedPoint for Int8.
For QuantizeDownInt32ToUint8Scale/QuantizeDownInt32ToInt8Scale the final result is:
((mm_result'[i][k] + result_offset) * result_mult_int) >> result_shift
For QuantizeDownInt32ToUint8ScaleByFixedPoint/QuantizeDownInt32ToInt8ScaleByFixedPoint the final result is:
(FixedPointMul(mm_result'[i][k], result_fixedpoint_multiplier) >> result_shift) + result_offset_after_shift
where FixedPointMul(x, y) is the nearest integer to the following mathematical expression, evaluated without overflow or intermediate rounding:
(x * y) / 2^31
and mm_result'[i][k] = mm_result[i][k] + (vector_sum_col[k] * a_offset) + (vector_sum_row[i] * b_offset) + (a_offset * b_offset * k)
Definition at line 66 of file CpuGemmLowpOffsetContributionOutputStageKernel.h.
Constructor & Destructor Documentation
CpuGemmLowpOffsetContributionOutputStageKernel()
CpuGemmLowpOffsetContributionOutputStageKernel () default
Default constructor.
Member Function Documentation
ARM_COMPUTE_DISALLOW_COPY_ALLOW_MOVE()
ARM_COMPUTE_DISALLOW_COPY_ALLOW_MOVE (CpuGemmLowpOffsetContributionOutputStageKernel)
configure()
void configure (const ITensorInfo * mm_result, const ITensorInfo * vector_sum_col, const ITensorInfo * vector_sum_row, const ITensorInfo * bias, ITensorInfo * dst, int32_t k, int32_t a_offset, int32_t b_offset, GEMMLowpOutputStageInfo output_stage)
Initialise the kernel inputs and output.
Parameters
[in] mm_result Input tensor info containing the result of CpuGemmLowpMatrixMultiplyKernel. Data type supported: S32
[in] vector_sum_col Input row-vector tensor info of sums of all the entries in each column of matrix B. Can be a 1D or 2D tensor, in case of 2D, y dim is the batch dimension Note: vector_sum_col can be a nullptr in case a_offset = 0. Data type supported: same as mm_result
[in] vector_sum_row Input row-vector tensor info of sums of all the entries in each row of matrix A. Can be a 1D or 2D tensor, in case of 2D, y dim is the batch dimension
[in] bias Biases tensor info. Only shared biases supported and it can be a nullptr if the addition of biases is not required. Biases are 1D tensor with dimensions [OFM]. Data type supported: Same as mm_result.
[out] dst Output tensor info containing the final quantized result. Data type supported: QASYMM8/QASYMM8_SIGNED
[in] k Number of matrix A columns or Matrix B rows
[in] a_offset Offset to be added to each element of the matrix A.
[in] b_offset Offset to be added to each element of the matrix B.
[in] output_stage GEMMLowp output stage info, providing the type of quantization and the necessary parameters.
Definition at line 855 of file CpuGemmLowpOffsetContributionOutputStageKernel.cpp.
 {
     ARM_COMPUTE_UNUSED(vector_sum_row, bias);
     // Perform validate step
     ARM_COMPUTE_ERROR_ON_NULLPTR(mm_result, dst);
     ARM_COMPUTE_ERROR_THROW_ON(validate_arguments(mm_result, vector_sum_col, vector_sum_row, bias, dst, a_offset, b_offset, output_stage));
     _a_offset     = a_offset;
     _b_offset     = b_offset;
     _k_offset     = a_offset * b_offset * k;
     _output_stage = output_stage;
     // If a_offset == 0, vector_sum_col can be a nullptr
     if(a_offset != 0)
     {
         // Check if vector_sum_col_shape should be slidden or not
         // Don't slide vector_sum_col_shape along the y dimension if vector_sum_col_shape has just 1 dimension and vector_sum_row_shape more than 1
         // This scenario can happen when the the matrix multiplication is used to perform a convolution operation
         _is_vector_sum_col_batched = vector_sum_col->tensor_shape().num_dimensions() > 1;
     }
     // Output auto inizialitation if not yet initialized
     auto_init_if_empty(*dst, mm_result->clone()->set_data_type(DataType::QASYMM8));
     // Configure kernel window
     Window win = calculate_max_window(*mm_result, Steps());
     // Note: This kernel performs 16 elements per iteration.
     // However, since we use a left-over for loop, we cannot have any read or write out of memory
     // For this reason num_elems_processed_per_iteration is 1 and so update_window_and_padding() can be skipped
     ICpuKernel::configure(win);
 }
References ARM_COMPUTE_ERROR_ON_NULLPTR, ARM_COMPUTE_ERROR_THROW_ON, ARM_COMPUTE_UNUSED, arm_compute::auto_init_if_empty(), bias, arm_compute::calculate_max_window(), ICloneable< T >::clone(), arm_compute::test::validation::dst, arm_compute::test::validation::k, Dimensions< T >::num_dimensions(), output_stage, arm_compute::QASYMM8, ITensorInfo::tensor_shape(), and arm_compute::cpu::kernels::validate_arguments().
name()
const char * name () const override virtual
Name of the kernel.
Returns
Kernel name
Implements ICPPKernel.
Definition at line 953 of file CpuGemmLowpOffsetContributionOutputStageKernel.cpp.
 {
     return "CpuGemmLowpOffsetContributionOutputStageKernel";
 }
run_op()
void run_op (ITensorPack & tensors, const Window & window, const ThreadInfo & info) override virtual
Execute the kernel on the passed window.
Warning
If is_parallelisable() returns false then the passed window must be equal to window()
Note
The window has to be a region within the window returned by the window() method
The width of the window has to be a multiple of num_elems_processed_per_iteration().
Parameters
[in] tensors A vector containing the tensors to operate on.
[in] window Region on which to execute the kernel. (Must be a region of the window returned by window())
[in] info Info about executing thread and CPU.
Reimplemented from ICPPKernel.
Definition at line 900 of file CpuGemmLowpOffsetContributionOutputStageKernel.cpp.
 {
     ARM_COMPUTE_UNUSED(info);
     ARM_COMPUTE_ERROR_ON_UNCONFIGURED_KERNEL(this);
     ARM_COMPUTE_ERROR_ON_INVALID_SUBWINDOW(ICpuKernel::window(), window);
     auto mm_result      = tensors.get_const_tensor(TensorType::ACL_SRC_0);
     auto vector_sum_col = tensors.get_const_tensor(TensorType::ACL_SRC_1);
     auto vector_sum_row = tensors.get_const_tensor(TensorType::ACL_SRC_2);
     auto bias           = tensors.get_const_tensor(TensorType::ACL_SRC_3);
     auto dst            = tensors.get_tensor(TensorType::ACL_DST);
     PixelValue type_min{};
     PixelValue type_max{};
     std::tie(type_min, type_max) = get_min_max(dst->info()->data_type());
     int32_t type_min_int = type_min.get<int32_t>();
     int32_t type_max_int = type_max.get<int32_t>();
     const bool reinterpret_as_3d = vector_sum_row != nullptr
                                    && mm_result->info()->num_dimensions() > 1
                                    && mm_result->info()->tensor_shape().y() != vector_sum_row->info()->tensor_shape().x();
     const bool is_bounded_relu = !(_output_stage.gemmlowp_min_bound <= type_min_int && _output_stage.gemmlowp_max_bound >= type_max_int);
     // Check if we need to perform fixed point requantization
     const bool is_fixed_point = _output_stage.type != GEMMLowpOutputStageType::QUANTIZE_DOWN;
     // Check if symmetric per-channel execution
     const bool is_signed = dst->info()->data_type() == DataType::QASYMM8_SIGNED;
     // Check if symmetric per-channel execution
     const bool is_symm = _output_stage.is_quantized_per_channel;
     if(is_symm)
     {
         run_offset_contribution_output_stage_symm(window, mm_result, vector_sum_col, vector_sum_row, bias, dst, _a_offset, _b_offset, _k_offset, _is_vector_sum_col_batched, _output_stage,
                                                   reinterpret_as_3d, is_bounded_relu, is_fixed_point);
     }
     else
     {
         if(is_signed)
         {
             run_offset_contribution_output_stage<int8_t>(window, mm_result, vector_sum_col, vector_sum_row, bias, dst, _a_offset, _b_offset, _k_offset, _is_vector_sum_col_batched, _output_stage,
                                                          reinterpret_as_3d, is_bounded_relu, is_fixed_point);
         }
         else
         {
             run_offset_contribution_output_stage<uint8_t>(window, mm_result, vector_sum_col, vector_sum_row, bias, dst, _a_offset, _b_offset, _k_offset, _is_vector_sum_col_batched, _output_stage,
                                                           reinterpret_as_3d, is_bounded_relu, is_fixed_point);
         }
     }
 }
References arm_compute::ACL_DST, arm_compute::ACL_SRC_0, arm_compute::ACL_SRC_1, arm_compute::ACL_SRC_2, arm_compute::ACL_SRC_3, ARM_COMPUTE_ERROR_ON_INVALID_SUBWINDOW, ARM_COMPUTE_ERROR_ON_UNCONFIGURED_KERNEL, ARM_COMPUTE_UNUSED, bias, arm_compute::test::validation::dst, GEMMLowpOutputStageInfo::gemmlowp_max_bound, GEMMLowpOutputStageInfo::gemmlowp_min_bound, ITensorPack::get_const_tensor(), arm_compute::get_min_max(), ITensorPack::get_tensor(), arm_compute::test::validation::info, GEMMLowpOutputStageInfo::is_quantized_per_channel, arm_compute::QASYMM8_SIGNED, arm_compute::QUANTIZE_DOWN, GEMMLowpOutputStageInfo::type, and IKernel::window().
validate()
Status validate (const ITensorInfo * mm_result, const ITensorInfo * vector_sum_col, const ITensorInfo * vector_sum_row, const ITensorInfo * bias, const ITensorInfo * dst, int32_t a_offset, int32_t b_offset, GEMMLowpOutputStageInfo output_stage) static
Static function to check if given info will lead to a valid configuration.
Similar to CpuGemmLowpOffsetContributionOutputStageKernel::configure()
Returns
a status
Definition at line 891 of file CpuGemmLowpOffsetContributionOutputStageKernel.cpp.
 {
     ARM_COMPUTE_ERROR_ON_NULLPTR(mm_result, output);
     ARM_COMPUTE_RETURN_ON_ERROR(validate_arguments(mm_result, vector_sum_col, vector_sum_row, bias, output, a_offset, b_offset, output_stage));
     return Status{};
 }
References ARM_COMPUTE_ERROR_ON_NULLPTR, ARM_COMPUTE_RETURN_ON_ERROR, bias, output_stage, and arm_compute::cpu::kernels::validate_arguments().
Referenced by CpuGemmLowpMatrixMultiplyCore::validate().
The documentation for this class was generated from the following files:
src/cpu/kernels/CpuGemmLowpOffsetContributionOutputStageKernel.h
src/cpu/kernels/CpuGemmLowpOffsetContributionOutputStageKernel.cpp