Compute Library: CLLogicalAnd Class Reference
CLLogicalAnd Class Reference
Basic function to run arm_compute::opencl::kernels::ClLogicalBinaryKernel.
#include <CLLogicalAnd.h>
Public Member Functions
CLLogicalAnd ()
Default Constructor.
~CLLogicalAnd ()
Default Destructor.
CLLogicalAnd (const CLLogicalAnd &)=delete
Prevent instances of this class from being copied (As this class contains pointers)
CLLogicalAnd (CLLogicalAnd &&)
Default move constructor.
CLLogicalAnd & operator= (const CLLogicalAnd &)=delete
Prevent instances of this class from being copied (As this class contains pointers)
CLLogicalAnd & operator= (CLLogicalAnd &&)
Default move assignment operator.
void configure (ICLTensor *input1, ICLTensor *input2, ICLTensor *output)
Initialize the function.
void configure (const CLCompileContext &compile_context, ICLTensor *input1, ICLTensor *input2, ICLTensor *output)
Initialize the function.
void run () override
Run the kernels contained in the function.
Public Member Functions inherited from IFunction
virtual ~IFunction ()=default
Destructor.
virtual void prepare ()
Prepare the function for executing.
Static Public Member Functions
static Status validate (const ITensorInfo *input1, const ITensorInfo *input2, const ITensorInfo *output)
Static function to check if given info will lead to a valid configuration.
Detailed Description
Basic function to run arm_compute::opencl::kernels::ClLogicalBinaryKernel.
Note
The tensor data type for the inputs must be U8.
The function performs a logical AND operation using the two input tensors.
Definition at line 42 of file CLLogicalAnd.h.
Constructor & Destructor Documentation
CLLogicalAnd() [1/3]
CLLogicalAnd ()
Default Constructor.
Definition at line 63 of file CLLogicalAnd.cpp.
     : _impl(std::make_unique<Impl>())
 {
 }
~CLLogicalAnd()
~CLLogicalAnd () default
Default Destructor.
CLLogicalAnd() [2/3]
CLLogicalAnd (const CLLogicalAnd &) delete
Prevent instances of this class from being copied (As this class contains pointers)
CLLogicalAnd() [3/3]
CLLogicalAnd (CLLogicalAnd &&) default
Default move constructor.
Member Function Documentation
configure() [1/2]
void configure (const CLCompileContext & compile_context, ICLTensor * input1, ICLTensor * input2, ICLTensor * output)
Initialize the function.
Parameters
[in] compile_context The compile context to be used.
[in] input1 Input tensor. Data types supported: U8.
[in] input2 Input tensor. Data types supported: same as input1.
[out] output Output tensor. Data types supported: same as input1.
Definition at line 76 of file CLLogicalAnd.cpp.
 {
     _impl->src0 = input1;
     _impl->src1 = input2;
     _impl->dst  = output;
     _impl->op   = std::make_unique<experimental::CLLogicalAnd>();
     _impl->op->configure(compile_context, input1->info(), input2->info(), output->info());
 }
References ITensor::info().
configure() [2/2]
void configure (ICLTensor * input1, ICLTensor * input2, ICLTensor * output)
Initialize the function.
Valid data layouts:
All
Valid data type configurations:
src0 src1 dst
U8 U8 U8
Parameters
[in] input1 Input tensor. Data types supported: U8.
[in] input2 Input tensor. Data types supported: same as input1.
[out] output Output tensor. Data types supported: same as input1.
Definition at line 71 of file CLLogicalAnd.cpp.
 {
     configure(CLKernelLibrary::get().get_compile_context(), input1, input2, output);
 }
References CLKernelLibrary::get().
operator=() [1/2]
CLLogicalAnd & operator= (CLLogicalAnd &&) default
Default move assignment operator.
operator=() [2/2]
CLLogicalAnd& operator= (const CLLogicalAnd &) delete
Prevent instances of this class from being copied (As this class contains pointers)
run()
void run () override virtual
Run the kernels contained in the function.
For CPU kernels:
Multi-threading is used for the kernels which are parallelisable.
By default std::thread::hardware_concurrency() threads are used.
Note
CPPScheduler::set_num_threads() can be used to manually set the number of threads
For OpenCL kernels:
All the kernels are enqueued on the queue associated with CLScheduler.
The queue is then flushed.
Note
The function will not block until the kernels are executed. It is the user's responsibility to wait.
Will call prepare() on first run if hasn't been done
Implements IFunction.
Definition at line 90 of file CLLogicalAnd.cpp.
 {
     ITensorPack pack;
     pack.add_tensor(TensorType::ACL_SRC_0, _impl->src0);
     pack.add_tensor(TensorType::ACL_SRC_1, _impl->src1);
     pack.add_tensor(TensorType::ACL_DST, _impl->dst);
     _impl->op->run(pack);
 }
References arm_compute::ACL_DST, arm_compute::ACL_SRC_0, arm_compute::ACL_SRC_1, ITensorPack::add_tensor(), and arm_compute::test::validation::pack.
validate()
Status validate (const ITensorInfo * input1, const ITensorInfo * input2, const ITensorInfo * output) static
Static function to check if given info will lead to a valid configuration.
Parameters
[in] input1 First tensor input info. Data types supported: U8.
[in] input2 Second tensor input info. Data types supported: same as input1.
[in] output Output tensor info. Data types supported: same as input1.
Returns
a status
Definition at line 85 of file CLLogicalAnd.cpp.
 {
     return experimental::CLLogicalAnd::validate(input1, input2, output);
 }
References CLLogicalAnd::validate().
The documentation for this class was generated from the following files:
arm_compute/runtime/CL/functions/CLLogicalAnd.h
src/runtime/CL/functions/CLLogicalAnd.cpp