Compute Library: GpuPool2d Class Reference
GpuPool2d Class Reference final
Operator interface.
#include <GpuPool2d.h>
Public Types
using Attributes = Pool2dAttributes
Attributes are a set of backend-agnostic parameters that define what an operator does.
using Settings = GpuPool2dSettings
Settings are a set of backend-specific parameters that influence the implementation of a operator.
Static Public Member Functions
static void create_op (GpuWorkloadSketch &sketch, ITensorInfo *src, ITensorInfo *dst, const Attributes &attributes, const Settings &settings)
Create an operator and fuse it into the workload sketch.
static Status is_supported_op (const GpuWorkloadContext &context, const ITensorInfo *src, const ITensorInfo *dst, const Attributes &attributes, const Settings &settings)
Check if the operator configuration is supported, irrespective of fusion.
static Status validate_op (const GpuWorkloadSketch &sketch, const ITensorInfo *src, const ITensorInfo *dst, const Attributes &attributes, const Settings &settings)
Validate the operator and check if it can be fused into the workload sketch.
Detailed Description
Operator interface.
Definition at line 63 of file GpuPool2d.h.
Member Typedef Documentation
Attributes
using Attributes = Pool2dAttributes
Attributes are a set of backend-agnostic parameters that define what an operator does.
Definition at line 67 of file GpuPool2d.h.
Settings
using Settings = GpuPool2dSettings
Settings are a set of backend-specific parameters that influence the implementation of a operator.
Definition at line 69 of file GpuPool2d.h.
Member Function Documentation
create_op()
void create_op (GpuWorkloadSketch & sketch, ITensorInfo * src, ITensorInfo * dst, const Attributes & attributes, const Settings & settings) static
Create an operator and fuse it into the workload sketch.
Note
If validate_op() fails, the creation also fails and may throw an error.
If validate_op() fails, sketch remains unchanged and valid.
Valid data type configurations:
src dst
F16 F16
F32 F32
Valid data layouts:
NHWC
Parameters
[in,out] sketch Workload sketch into which the operator will be fused
[in] src Source tensor
[out] dst Destination tensor
[in] attributes Operator attributes
[in] settings Operator settings
Definition at line 148 of file GpuPool2d.cpp.
 {
     // Assert validation
     ARM_COMPUTE_ERROR_THROW_ON(GpuPool2d::validate_op(sketch, src, dst, attributes, settings));
     ARM_COMPUTE_LOG_PARAMS(src, dst, attributes, settings);
     // Auto initialize dst tensor
     {
         auto shape = misc::shape_calculator::compute_pool_shape(*src, convert_pool_attr_to_pool_info(attributes, settings.mixed_precision())); // use the default DimensionRoundingType
         auto_init_if_empty(*dst, src->clone()->set_tensor_shape(shape));
     }
     // Translate into components and add to component graph
     auto &comp_graph = sketch.implementation().component_graph();
     const auto sketch_ctx = sketch.implementation().context();
     if(sketch_ctx->gpu_language() == GpuLanguage::OpenCL)
     {
         const auto cl_compile_ctx = sketch_ctx->cl_compile_context();
         ARM_COMPUTE_UNUSED(cl_compile_ctx);
         ARM_COMPUTE_ERROR_ON(cl_compile_ctx == nullptr);
         // Add Component
         {
             auto properties = IGpuKernelComponent::Properties();
             properties.stage(UnitWorkloadStage{ UnitWorkloadStage::Stage::Run });
             ArgumentPack<ITensorInfo> arguments;
             arguments.add_const_tensor(ACL_SRC_0, src);
             arguments.add_const_tensor(ACL_DST_0, dst);
             comp_graph.add_new_component<ClComponentPool2d>(properties, arguments, attributes, settings);
         }
     }
     else
     {
         ARM_COMPUTE_ERROR("Unimplemented Gpu language");
     }
     // Set up fusion test by adding to the Operator Group
     // Note this has to be performed after all the components have been successfully added to the component graph
     // Pack tensor infos
     ArgumentPack<ITensorInfo> tensors;
     tensors.add_const_tensor(ACL_SRC_0, src);
     tensors.add_tensor(ACL_DST_0, dst);
     const auto op = sketch.implementation().operator_group().new_operator(operator_type, tensors);
     sketch.implementation().operator_group().add_operator(op);
 }
References arm_compute::ACL_DST_0, arm_compute::ACL_SRC_0, ArgumentPack< T >::add_const_tensor(), GpuOperatorGroup::add_operator(), ArgumentPack< T >::add_tensor(), ARM_COMPUTE_ERROR, ARM_COMPUTE_ERROR_ON, ARM_COMPUTE_ERROR_THROW_ON, ARM_COMPUTE_LOG_PARAMS, ARM_COMPUTE_UNUSED, arm_compute::auto_init_if_empty(), GpuWorkloadContext::cl_compile_context(), GpuWorkloadSketch::Implementation::component_graph(), arm_compute::misc::shape_calculator::compute_pool_shape(), GpuWorkloadSketch::Implementation::context(), arm_compute::experimental::dynamic_fusion::convert_pool_attr_to_pool_info(), arm_compute::test::validation::dst, GpuWorkloadSketch::implementation(), GpuPool2dSettings::mixed_precision(), GpuOperatorGroup::new_operator(), arm_compute::experimental::dynamic_fusion::OpenCL, GpuWorkloadSketch::Implementation::operator_group(), UnitWorkloadStage::Run, arm_compute::test::validation::shape, arm_compute::test::validation::sketch, arm_compute::test::validation::src, and GpuPool2d::validate_op().
is_supported_op()
Status is_supported_op (const GpuWorkloadContext & context, const ITensorInfo * src, const ITensorInfo * dst, const Attributes & attributes, const Settings & settings) static
Check if the operator configuration is supported, irrespective of fusion.
Parameters
[in] context Workload context within which the operator is running
[in] src Left hand side tensor info. Data types supported: F16/F32.
[out] dst Destination tensor info. Data types supported: F16/F32. If an uninitialized ITensorInfo is passed in, it will be auto-initialized
[in] attributes Operator attributes
[in] settings Operator settings
Definition at line 104 of file GpuPool2d.cpp.
 {
     ARM_COMPUTE_RETURN_ERROR_ON_NULLPTR(src, dst);
     // Data type
     ARM_COMPUTE_RETURN_ERROR_ON_DATA_TYPE_CHANNEL_NOT_IN(src, 1, DataType::F16, DataType::F32);
     // Data layout
     ARM_COMPUTE_RETURN_ERROR_ON_DATA_LAYOUT_NOT_IN(src, DataLayout::NHWC);
     // Check exclude padding is not false
     ARM_COMPUTE_RETURN_ERROR_ON_MSG(!attributes.exclude_padding(), "Exclude padding must be set to true in Attributes!");
     // Auto initialize dst tensor info
     TensorInfo dst_info_to_validate = *dst;
     {
         auto shape = misc::shape_calculator::compute_pool_shape(*src, convert_pool_attr_to_pool_info(attributes, settings.mixed_precision()));
         auto_init_if_empty(dst_info_to_validate, src->clone()->set_tensor_shape(shape));
     }
     // Check components
     if(context.gpu_language() == GpuLanguage::OpenCL)
     {
         const auto cl_compile_ctx = context.cl_compile_context();
         ARM_COMPUTE_RETURN_ERROR_ON(cl_compile_ctx == nullptr);
         // Validate Component
         {
             const KernelProperties properties = IGpuKernelComponent::Properties().stage(UnitWorkloadStage{ UnitWorkloadStage::Stage::Run });
             ArgumentPack<ITensorInfo> arguments;
             arguments.add_const_tensor(ACL_SRC_0, src);
             arguments.add_const_tensor(ACL_DST_0, &dst_info_to_validate);
             ARM_COMPUTE_RETURN_ON_ERROR(ClComponentPool2d::validate(properties, arguments, attributes, settings));
         }
     }
     else
     {
         ARM_COMPUTE_RETURN_ERROR_MSG("Unimplemented Gpu language");
     }
     return Status{};
 }
References arm_compute::ACL_DST_0, arm_compute::ACL_SRC_0, ArgumentPack< T >::add_const_tensor(), ARM_COMPUTE_RETURN_ERROR_MSG, ARM_COMPUTE_RETURN_ERROR_ON, ARM_COMPUTE_RETURN_ERROR_ON_DATA_LAYOUT_NOT_IN, ARM_COMPUTE_RETURN_ERROR_ON_DATA_TYPE_CHANNEL_NOT_IN, ARM_COMPUTE_RETURN_ERROR_ON_MSG, ARM_COMPUTE_RETURN_ERROR_ON_NULLPTR, ARM_COMPUTE_RETURN_ON_ERROR, arm_compute::auto_init_if_empty(), arm_compute::misc::shape_calculator::compute_pool_shape(), arm_compute::test::validation::context, arm_compute::experimental::dynamic_fusion::convert_pool_attr_to_pool_info(), arm_compute::test::validation::dst, Pool2dAttributes::exclude_padding(), arm_compute::F16, arm_compute::F32, GpuPool2dSettings::mixed_precision(), arm_compute::NHWC, arm_compute::experimental::dynamic_fusion::OpenCL, UnitWorkloadStage::Run, arm_compute::test::validation::shape, arm_compute::test::validation::src, KernelProperties::stage(), and ClComponentPool2d::validate().
Referenced by GpuPool2d::validate_op().
validate_op()
Status validate_op (const GpuWorkloadSketch & sketch, const ITensorInfo * src, const ITensorInfo * dst, const Attributes & attributes, const Settings & settings) static
Validate the operator and check if it can be fused into the workload sketch.
Similar to GpuPool2d::create_op()
Definition at line 74 of file GpuPool2d.cpp.
 {
     ARM_COMPUTE_RETURN_ERROR_ON_NULLPTR(src, dst);
     ARM_COMPUTE_RETURN_ERROR_ON(!src->has_valid_id() || !dst->has_valid_id());
     // Auto initialize dst tensor info
     TensorInfo dst_info_to_validate = *dst;
     {
         auto shape = misc::shape_calculator::compute_pool_shape(*src, convert_pool_attr_to_pool_info(attributes, settings.mixed_precision()));
         auto_init_if_empty(dst_info_to_validate, src->clone()->set_tensor_shape(shape));
     }
     // Perform fusion test
     // Pack tensor infos
     ArgumentPack<ITensorInfo> tensors;
     tensors.add_const_tensor(ACL_SRC_0, src);
     tensors.add_const_tensor(ACL_DST_0, &dst_info_to_validate);
     const auto op = sketch.implementation().operator_group().new_operator(operator_type, tensors);
     ARM_COMPUTE_RETURN_ERROR_ON_MSG(!sketch.implementation().operator_group().try_add_operator(op),
                                     "Operator fusion test failed. This operator cannot be fused into the workload");
     // Check if configuration is supported
     return is_supported_op(*sketch.gpu_context(), src, &dst_info_to_validate, attributes, settings);
 }
References arm_compute::ACL_DST_0, arm_compute::ACL_SRC_0, ArgumentPack< T >::add_const_tensor(), ARM_COMPUTE_RETURN_ERROR_ON, ARM_COMPUTE_RETURN_ERROR_ON_MSG, ARM_COMPUTE_RETURN_ERROR_ON_NULLPTR, arm_compute::auto_init_if_empty(), arm_compute::misc::shape_calculator::compute_pool_shape(), arm_compute::experimental::dynamic_fusion::convert_pool_attr_to_pool_info(), arm_compute::test::validation::dst, GpuWorkloadSketch::gpu_context(), GpuWorkloadSketch::implementation(), GpuPool2d::is_supported_op(), GpuPool2dSettings::mixed_precision(), GpuOperatorGroup::new_operator(), GpuWorkloadSketch::Implementation::operator_group(), arm_compute::test::validation::shape, arm_compute::test::validation::sketch, arm_compute::test::validation::src, and GpuOperatorGroup::try_add_operator().
Referenced by GpuPool2d::create_op().
The documentation for this class was generated from the following files:
arm_compute/dynamic_fusion/sketch/gpu/operators/GpuPool2d.h
src/dynamic_fusion/sketch/gpu/operators/GpuPool2d.cpp