Compute Library: ClTemplatePool2d Class Reference
ClTemplatePool2d Class Reference final
#include <ClTemplatePool2d.h>
Public Types
using Attributes = ClComponentPool2d::Attributes
using Settings = ClComponentPool2d::Settings
Public Types inherited from IGpuTemplateComponentWriter
using ComponentGroup = GpuKernelComponentGroup
Public Member Functions
ClTemplatePool2d (ComponentId id, const ArgumentPack< ITensorInfo > &tensors, const Attributes &attributes, const Settings &settings)
Constructor.
ClTemplatePool2d (const ClTemplatePool2d &direct_conv2d)=delete
Prevent instances of this class from being copy constructed.
ClTemplatePool2d & operator= (const ClTemplatePool2d &direct_conv2d)=delete
Prevent instances of this class from being copied.
ClTemplatePool2d (ClTemplatePool2d &&direct_conv2d)=default
Allow instances of this class to be move constructed.
ClTemplatePool2d & operator= (ClTemplatePool2d &&direct_conv2d)=default
Allow instances of this class to be moved.
std::string get_name () const override
Generate kernel component name.
std::string get_component_code (const ComponentGroup &comp_group) const override
Generate kernel component code template.
void declare_variables (GpuKernelVariableTable &vtable, const ComponentGroup &comp_group) const override
Declare all variables used by the component in the vtable.
TagLUT get_tag_lut (const GpuKernelVariableTable &vtable, const ComponentGroup &comp_group) const override
Generate the tag look-up table used to instantiate the component code.
CLBuildOptions get_build_options (const ComponentGroup &comp_group) const override
Generate the build options used in the component.
std::string get_config_id () const override
Generate the component config id string used for tuning.
std::set< std::string > get_headers_list () const override
Generate the header list used in the component.
Window get_window () const override
Generate the execution window for the component.
Public Member Functions inherited from IGpuTemplateComponentWriter
IGpuTemplateComponentWriter (ComponentId id, const ArgumentPack< ITensorInfo > &tensors)
Constructor.
virtual ~IGpuTemplateComponentWriter ()
Destructor.
virtual std::string get_additional_macros () const
Generate additional macros used in the component.
ArgumentPack< ITensorInfo > tensors () const
Get tensor arguments.
ComponentId id () const
Get component id.
Additional Inherited Members
Static Public Attributes inherited from IGpuTemplateComponentWriter
static constexpr GpuKernelArgumentInfo::Type common_tensor_type = GpuKernelArgumentInfo::Type::Tensor_4D_t_Buffer
For now all kernel intermeditate/destination tensors are expected to be of type Tensor_4D_t_Buffer.
Detailed Description
Definition at line 40 of file ClTemplatePool2d.h.
Member Typedef Documentation
Attributes
using Attributes = ClComponentPool2d::Attributes
Definition at line 43 of file ClTemplatePool2d.h.
Settings
using Settings = ClComponentPool2d::Settings
Definition at line 44 of file ClTemplatePool2d.h.
Constructor & Destructor Documentation
ClTemplatePool2d() [1/3]
ClTemplatePool2d (ComponentId id, const ArgumentPack< ITensorInfo > & tensors, const Attributes & attributes, const Settings & settings)
Constructor.
Parameters
[in] id Component id
[in] tensors Tensor arguments to the components
[in] attributes Component attributes
[in] settings Component settings
Definition at line 49 of file ClTemplatePool2d.cpp.
     : IGpuTemplateComponentWriter{ id, tensors },
       _src{},
       _dst{},
       _attributes{ attributes },
       _settings{ settings }
 {
     _src = this->tensors().get_const_tensor(TensorType::ACL_SRC_0);
     _dst = this->tensors().get_const_tensor(TensorType::ACL_DST_0);
     ARM_COMPUTE_ERROR_ON_NULLPTR(_src, _dst);
 }
References IGpuTemplateComponentWriter::id(), and IGpuTemplateComponentWriter::tensors().
ClTemplatePool2d() [2/3]
ClTemplatePool2d (const ClTemplatePool2d & direct_conv2d) delete
Prevent instances of this class from being copy constructed.
ClTemplatePool2d() [3/3]
ClTemplatePool2d (ClTemplatePool2d && direct_conv2d) default
Allow instances of this class to be move constructed.
Member Function Documentation
declare_variables()
void declare_variables (GpuKernelVariableTable & vtable, const ComponentGroup & comp_group) const override virtual
Declare all variables used by the component in the vtable.
Parameters
[out] vtable Variable table
[in] comp_group Component group of which the component is a part of
Implements IGpuTemplateComponentWriter.
Definition at line 366 of file ClTemplatePool2d.cpp.
 {
     vtable.declare_variable(
         comp_group,
         _src,
         GpuKernelArgumentInfo(GpuKernelArgumentInfo::Type::Tensor_4D_t_Buffer),
         "src");
     vtable.declare_variable(
         comp_group,
         _dst,
         GpuKernelArgumentInfo(GpuKernelArgumentInfo::Type::Tensor_4D_t_Buffer),
         "dst");
 }
References GpuKernelVariableTable::declare_variable(), and GpuKernelArgumentInfo::Tensor_4D_t_Buffer.
get_build_options()
CLBuildOptions get_build_options (const ComponentGroup & comp_group) const override virtual
Generate the build options used in the component.
Parameters
[in] comp_group Component group of which the component is a part of
Returns
CLBuildOptions Build options
Reimplemented from IGpuTemplateComponentWriter.
Definition at line 422 of file ClTemplatePool2d.cpp.
 {
     const auto         root_window      = comp_group.get_root_component()->template_writer()->get_window();
     const unsigned int n0               = root_window.x().step();
     const unsigned int partial_store_n0 = _dst->dimension(0) % n0;
     CLBuildOptions build_opts{};
     build_opts.add_option("-DN0=" + support::cpp11::to_string(n0));
     build_opts.add_option("-DPARTIAL_N0=" + support::cpp11::to_string(partial_store_n0));
     return build_opts;
 }
References CLBuildOptions::add_option(), ITensorInfo::dimension(), GpuKernelComponentGroup::get_root_component(), IGpuTemplateComponentWriter::get_window(), Window::Dimension::step(), IGpuKernelComponent::template_writer(), arm_compute::support::cpp11::to_string(), and Window::x().
get_component_code()
std::string get_component_code (const ComponentGroup & comp_group) const override virtual
Generate kernel component code template.
Parameters
[in] comp_group Component group of which the component is a part of
Returns
std::string Component code
Implements IGpuTemplateComponentWriter.
Definition at line 69 of file ClTemplatePool2d.cpp.
 {
     ARM_COMPUTE_UNUSED(comp_group);
     // Condition to use 2x2 optimized kernel
     if(_attributes.pool_size() == Size2D(2, 2))
     {
         return get_2x2_kernel_code();
     }
     else
     {
         return get_MxN_kernel_code();
     }
 }
References ARM_COMPUTE_UNUSED, and Pool2dAttributes::pool_size().
get_config_id()
std::string get_config_id () const override virtual
Generate the component config id string used for tuning.
Reimplemented from IGpuTemplateComponentWriter.
Definition at line 435 of file ClTemplatePool2d.cpp.
 {
     const DataType   data_type   = _src->data_type();
     const DataLayout data_layout = _src->data_layout();
     std::string config_id{};
     config_id += "pooling_layer_2d_";
     config_id += lower_string(string_from_data_type(data_type));
     config_id += "_";
     config_id += lower_string(string_from_data_layout(data_layout));
     config_id += "_";
     config_id += support::cpp11::to_string(_dst->dimension(width_idx));
     config_id += "_";
     config_id += support::cpp11::to_string(_dst->dimension(height_idx));
     config_id += "_";
     config_id += support::cpp11::to_string(_dst->dimension(channel_idx));
     return config_id;
 }
References ITensorInfo::data_layout(), arm_compute::test::validation::data_layout, arm_compute::test::validation::data_type, ITensorInfo::data_type(), ITensorInfo::dimension(), arm_compute::lower_string(), arm_compute::string_from_data_layout(), arm_compute::string_from_data_type(), and arm_compute::support::cpp11::to_string().
get_headers_list()
std::set< std::string > get_headers_list () const override virtual
Generate the header list used in the component.
Reimplemented from IGpuTemplateComponentWriter.
Definition at line 455 of file ClTemplatePool2d.cpp.
 {
     return std::set<std::string>{ "helpers.h", "tile_helpers.h", "repeat.h" };
 }
get_name()
std::string get_name () const override virtual
Generate kernel component name.
Implements IGpuTemplateComponentWriter.
Definition at line 64 of file ClTemplatePool2d.cpp.
 {
     return "pool2d";
 }
get_tag_lut()
TagLUT get_tag_lut (const GpuKernelVariableTable & vtable, const ComponentGroup & comp_group) const override virtual
Generate the tag look-up table used to instantiate the component code.
Parameters
[in] vtable Variable table
[in] comp_group Component group of which the component is a part of
Returns
TagLUT Tag lookup table
Implements IGpuTemplateComponentWriter.
Definition at line 381 of file ClTemplatePool2d.cpp.
 {
     ARM_COMPUTE_UNUSED(comp_group);
     TagLUT lut{};
     // Arguments and global shared variables
     lut["src"] = vtable.get_variable(_src);
     lut["dst"] = vtable.get_variable(_dst);
     // Local build options
     lut["meta_kernel_id"] = id();
     // Retrieve relevant data
     const auto        padding                = _attributes.pad();
     const auto        stride                 = _attributes.stride();
     const auto        pool_size              = _attributes.pool_size();
     const auto        data_type              = _src->data_type();
     const auto        use_fp_mixed_precision = (_src->data_type() == DataType::F16) && _settings.mixed_precision() && _attributes.pool_type() != PoolingType::MAX;
     const std::string max_initial_value      = _settings.use_inf_as_limit() ? "(-INFINITY)" : float_to_string_with_full_precision(std::numeric_limits<float>::lowest());
     // pool specific
     lut["STRIDE_X"]    = stride.x();
     lut["STRIDE_Y"]    = stride.y();
     lut["PAD_X"]       = padding.left;
     lut["PAD_Y"]       = padding.top;
     lut["POOL_SIZE_X"] = pool_size.width;
     lut["POOL_SIZE_Y"] = pool_size.height;
     // Datatypes and variables
     lut["ACC_DATA_TYPE"] = get_cl_type_from_data_type((use_fp_mixed_precision) ? (DataType::F32) : (data_type)); // Type of accumulators to use.
     lut["DATA_TYPE"]     = get_cl_type_from_data_type(data_type);
     lut["SRC_WIDTH"]     = _src->dimension(width_idx);
     lut["SRC_HEIGHT"]    = _src->dimension(height_idx);
     lut["INITIAL_VALUE"] = (_attributes.pool_type() == PoolingType::MAX) ? max_initial_value : std::string("0");
     // Tensor specific data
     lut["DST_HEIGHT"] = _dst->dimension(height_idx);
     return lut;
 }
References ARM_COMPUTE_UNUSED, arm_compute::test::validation::data_type, ITensorInfo::data_type(), ITensorInfo::dimension(), arm_compute::F16, arm_compute::F32, arm_compute::float_to_string_with_full_precision(), arm_compute::get_cl_type_from_data_type(), GpuKernelVariableTable::get_variable(), IGpuTemplateComponentWriter::id(), arm_compute::support::cpp11::lowest(), arm_compute::MAX, GpuPool2dSettings::mixed_precision(), Pool2dAttributes::pad(), Pool2dAttributes::pool_size(), Pool2dAttributes::pool_type(), Pool2dAttributes::stride(), and GpuPool2dSettings::use_inf_as_limit().
get_window()
Window get_window () const override virtual
Generate the execution window for the component.
Reimplemented from IGpuTemplateComponentWriter.
Definition at line 460 of file ClTemplatePool2d.cpp.
 {
     ARM_COMPUTE_ERROR_ON_MSG(_dst->tensor_shape().total_size() == 0U, "Destination tensor is not initialized");
     const auto         output_shape = _dst->tensor_shape();
     const unsigned int vec_size     = adjust_vec_size(((_dst->data_type() == DataType::F32) ? 2 : 4), _dst->dimension(0));
     // Create and configure kernel window
     auto win = calculate_max_window(output_shape, Steps(vec_size));
     win      = win.collapse_if_possible(win, Window::DimZ); // collapse window on batch size.
     return win;
 }
References arm_compute::adjust_vec_size(), ARM_COMPUTE_ERROR_ON_MSG, arm_compute::calculate_max_window(), ITensorInfo::data_type(), ITensorInfo::dimension(), Window::DimZ, arm_compute::F32, arm_compute::test::validation::output_shape, ITensorInfo::tensor_shape(), TensorShape::total_size(), and arm_compute::utils::cast::U.
operator=() [1/2]
ClTemplatePool2d& operator= (ClTemplatePool2d && direct_conv2d) default
Allow instances of this class to be moved.
operator=() [2/2]
ClTemplatePool2d& operator= (const ClTemplatePool2d & direct_conv2d) delete
Prevent instances of this class from being copied.
The documentation for this class was generated from the following files:
src/dynamic_fusion/sketch/gpu/template_writer/cl/ClTemplatePool2d.h
src/dynamic_fusion/sketch/gpu/template_writer/cl/ClTemplatePool2d.cpp