Compute Library: HeuristicTree Class Reference
HeuristicTree Class Reference
A binary decision tree based heuristic.
#include <HeuristicTree.h>
Data Structures
struct BranchNode
struct LeafNode
struct Node
Public Types
enum NodeType { Branch, Leaf }
using NodeID = size_t
using TreeID = size_t
using Index = std::tuple< HeuristicType, std::string, DataType >
Public Member Functions
HeuristicTree ()
Constructor.
HeuristicTree (TreeID id, HeuristicType h_type, const std::string &ip_target, DataType data_type)
Constructor.
HeuristicTree (const HeuristicTree &)=delete
Prevent copy construction.
HeuristicTree & operator= (const HeuristicTree &)=delete
Prevent copy assignment.
HeuristicTree (HeuristicTree &&other) noexcept=default
Move constructor.
HeuristicTree & operator= (HeuristicTree &&other)=default
Move assignment.
template<typename T >
std::pair< bool, T > query (GEMMShape shape) const
Query a leaf value given a gemm shape.
template<typename T >
bool add_leaf (NodeID id, T leaf_value)
Add a leaf node.
bool add_branch (NodeID id, Condition cond, NodeID true_node, NodeID false_node)
Add a branch node.
TreeID id () const
Get tree ID.
Index index () const
Get tree index.
bool check ()
Check if tree is valid.
Related Functions
(Note that these are not member functions.)
template std::pair< bool, GEMMType > query (GEMMShape shape) const
Explicit template instantiation.
template std::pair< bool, GEMMConfigNative > query (GEMMShape shape) const
Explicit template instantiation.
template std::pair< bool, GEMMConfigReshapedOnlyRHS > query (GEMMShape shape) const
Explicit template instantiation.
template std::pair< bool, GEMMConfigReshaped > query (GEMMShape shape) const
Explicit template instantiation.
template bool add_leaf (NodeID id, GEMMType val)
Explicit template instantiation.
template bool add_leaf (NodeID id, GEMMConfigNative val)
Explicit template instantiation.
template bool add_leaf (NodeID id, GEMMConfigReshapedOnlyRHS val)
Explicit template instantiation.
template bool add_leaf (NodeID id, GEMMConfigReshaped val)
Explicit template instantiation.
Detailed Description
A binary decision tree based heuristic.
Definition at line 67 of file HeuristicTree.h.
Member Typedef Documentation
Index
using Index = std::tuple<HeuristicType, std::string, DataType>
Definition at line 72 of file HeuristicTree.h.
NodeID
using NodeID = size_t
Definition at line 70 of file HeuristicTree.h.
TreeID
using TreeID = size_t
Definition at line 71 of file HeuristicTree.h.
Member Enumeration Documentation
NodeType
enum NodeType strong
Enumerator
Branch
Leaf
Definition at line 73 of file HeuristicTree.h.
     {
         Branch,
         Leaf
     };
Constructor & Destructor Documentation
HeuristicTree() [1/4]
HeuristicTree ()
Constructor.
Definition at line 95 of file HeuristicTree.cpp.
     : HeuristicTree(0, HeuristicType::GEMM_Type, "", DataType::F32)
 {
 }
References arm_compute::F32, and arm_compute::mlgo::GEMM_Type.
HeuristicTree() [2/4]
HeuristicTree (TreeID id, HeuristicType h_type, const std::string & ip_target, DataType data_type)
Constructor.
Definition at line 100 of file HeuristicTree.cpp.
     : _id{ id }, _heuristic_type{ h_type }, _ip_target{ ip_target }, _data_type{ data_type }, _tree{}
 {
 }
HeuristicTree() [3/4]
HeuristicTree (const HeuristicTree &) delete
Prevent copy construction.
HeuristicTree() [4/4]
HeuristicTree (HeuristicTree && other) default noexcept
Move constructor.
Member Function Documentation
add_branch()
bool add_branch (NodeID id, Condition cond, NodeID true_node, NodeID false_node)
Add a branch node.
Parameters
id Branch node ID
cond Branch node Condition
true_node True node's ID
false_node False node's ID
Returns
bool If the addition succeeded or not
Definition at line 152 of file HeuristicTree.cpp.
 {
     if(_tree.size() >= _max_num_nodes)
     {
         ARM_COMPUTE_LOG_INFO_MSG_WITH_FORMAT_CORE("Exceeding the maximum number of nodes allowed %zu", _max_num_nodes);
         return false;
     }
     const std::set<std::string> supported_features =
     {
         "m", "n", "k", "b", "r_mn", "r_mk", "r_nk", "r_mnk", "workload"
     };
     const auto orig_feature = cond.feature;
     std::transform(cond.feature.begin(), cond.feature.end(), cond.feature.begin(), [](char c)
     {
         return std::tolower(c);
     });
     if(supported_features.find(cond.feature) == supported_features.end())
     {
         ARM_COMPUTE_LOG_INFO_MSG_WITH_FORMAT_CORE("Unsupported feature %s", orig_feature.c_str());
         return false;
     }
     if(_tree.find(id) != _tree.end())
     {
         ARM_COMPUTE_LOG_INFO_MSG_WITH_FORMAT_CORE("Cannot add node; node id %zu already exists", id);
         return false;
     }
     _tree[id] = std::make_unique<BranchNode>(id, cond, t_node, f_node);
     return true;
 }
References ARM_COMPUTE_LOG_INFO_MSG_WITH_FORMAT_CORE, Condition::feature, and HeuristicTree::id().
add_leaf()
bool add_leaf (NodeID id, T leaf_value)
Add a leaf node.
Template Parameters
T Leaf value type
Parameters
id Leaf node ID
leaf_value Leaf node value
Returns
bool If the addition succeeded or not
Definition at line 136 of file HeuristicTree.cpp.
 {
     if(_tree.size() >= _max_num_nodes)
     {
         ARM_COMPUTE_LOG_INFO_MSG_WITH_FORMAT_CORE("Exceeding the maximum number of nodes allowed %zu", _max_num_nodes);
         return false;
     }
     if(_tree.find(id) != _tree.end())
     {
         ARM_COMPUTE_LOG_INFO_MSG_WITH_FORMAT_CORE("Cannot add node; node id %zu already exists", id);
         return false;
     }
     _tree[id] = std::make_unique<LeafNode<T>>(id, val);
     return true;
 }
References ARM_COMPUTE_LOG_INFO_MSG_WITH_FORMAT_CORE, and HeuristicTree::id().
check()
bool check ()
Check if tree is valid.
Returns
bool
Definition at line 220 of file HeuristicTree.cpp.
 {
     if(_tree.empty())
     {
         ARM_COMPUTE_LOG_INFO_MSG_CORE("Empty tree encountered");
         return false;
     }
     if(_tree.find(_root) == _tree.end())
     {
         ARM_COMPUTE_LOG_INFO_MSG_WITH_FORMAT_CORE("Missing root. Root must have a Node ID of %zu", _root);
         return false;
     }
     return check_if_structurally_correct();
 }
References ARM_COMPUTE_LOG_INFO_MSG_CORE, and ARM_COMPUTE_LOG_INFO_MSG_WITH_FORMAT_CORE.
id()
TreeID id () const inline
Get tree ID.
Returns
TreeID
Definition at line 161 of file HeuristicTree.h.
     {
         return _id;
     }
Referenced by HeuristicTree::add_branch(), and HeuristicTree::add_leaf().
index()
Index index () const inline
Get tree index.
Returns
Index
Definition at line 169 of file HeuristicTree.h.
     {
         return std::make_tuple(_heuristic_type, _ip_target, _data_type);
     }
operator=() [1/2]
HeuristicTree& operator= (const HeuristicTree &) delete
Prevent copy assignment.
operator=() [2/2]
HeuristicTree& operator= (HeuristicTree && other) default
Move assignment.
query()
std::pair< bool, T > query (GEMMShape shape) const
Query a leaf value given a gemm shape.
Template Parameters
T Leaf value type
Parameters
shape A GEMMShape for the query
Returns
std::pair<bool, T> Outcome contains bool, signalling if the query succeeded or not
Definition at line 106 of file HeuristicTree.cpp.
 {
     // Root ID = 0;
     auto   cur_node = _tree.at(_root).get();
     size_t depth    = 0;
     while(cur_node->type() != NodeType::Leaf)
     {
         if(depth > _max_query_depth)
         {
             ARM_COMPUTE_LOG_INFO_MSG_WITH_FORMAT_CORE("Exceeding max query depth: %zu. Is the tree too deep?", _max_query_depth);
             return std::make_pair(false, T{});
         }
         ARM_COMPUTE_ERROR_ON_MSG(cur_node->type() != NodeType::Branch, "Unexpected NodeType");
         auto br_node = utils::cast::polymorphic_downcast<BranchNode *>(cur_node);
         if(evaluate(shape, br_node->condition))
         {
             cur_node = _tree.at(br_node->true_node).get();
         }
         else
         {
             cur_node = _tree.at(br_node->false_node).get();
         }
         ++depth;
     }
     ARM_COMPUTE_ERROR_ON_MSG(cur_node->type() != NodeType::Leaf, "Unexpected NodeType");
     auto l_node = utils::cast::polymorphic_downcast<LeafNode<T> *>(cur_node);
     return std::make_pair(true, l_node->value);
 }
References ARM_COMPUTE_ERROR_ON_MSG, ARM_COMPUTE_LOG_INFO_MSG_WITH_FORMAT_CORE, HeuristicTree::Branch, HeuristicTree::Leaf, and arm_compute::test::validation::shape.
Friends And Related Function Documentation
add_leaf() [1/4]
template bool add_leaf (NodeID id, GEMMConfigNative val) related
Explicit template instantiation.
add_leaf() [2/4]
template bool add_leaf (NodeID id, GEMMConfigReshaped val) related
Explicit template instantiation.
add_leaf() [3/4]
template bool add_leaf (NodeID id, GEMMConfigReshapedOnlyRHS val) related
Explicit template instantiation.
add_leaf() [4/4]
template bool add_leaf (NodeID id, GEMMType val) related
Explicit template instantiation.
query() [1/4]
template std::pair< bool, GEMMType > query< GEMMType > (GEMMShape shape) const related
Explicit template instantiation.
query() [2/4]
template std::pair< bool, GEMMConfigNative > query< GEMMConfigNative > (GEMMShape shape) const related
Explicit template instantiation.
query() [3/4]
template std::pair< bool, GEMMConfigReshapedOnlyRHS > query< GEMMConfigReshapedOnlyRHS > (GEMMShape shape) const related
Explicit template instantiation.
query() [4/4]
template std::pair< bool, GEMMConfigReshaped > query< GEMMConfigReshaped > (GEMMShape shape) const related
Explicit template instantiation.
The documentation for this class was generated from the following files:
src/runtime/CL/mlgo/HeuristicTree.h
src/runtime/CL/mlgo/HeuristicTree.cpp