Compute Library: CLActivationLayer Class Reference
CLActivationLayer Class Reference
Basic function to run opencl::kernels::ClActivationKernel.
#include <CLActivationLayer.h>
Public Member Functions
CLActivationLayer (CLRuntimeContext *ctx=nullptr)
Constructor.
~CLActivationLayer ()
Destructor.
CLActivationLayer (const CLActivationLayer &)=delete
Prevent instances of this class from being copied (As this class contains pointers)
CLActivationLayer (CLActivationLayer &&)
Default move constructor.
CLActivationLayer & operator= (const CLActivationLayer &)=delete
Prevent instances of this class from being copied (As this class contains pointers)
CLActivationLayer & operator= (CLActivationLayer &&)
Default move assignment operator.
void configure (ICLTensor *input, ICLTensor *output, ActivationLayerInfo act_info)
Set the input and output tensor.
void configure (const CLCompileContext &compile_context, ICLTensor *input, ICLTensor *output, ActivationLayerInfo act_info)
Set the input and output tensor.
void run () override
Run the kernels contained in the function.
Public Member Functions inherited from IFunction
virtual ~IFunction ()=default
Destructor.
virtual void prepare ()
Prepare the function for executing.
Static Public Member Functions
static Status validate (const ITensorInfo *input, const ITensorInfo *output, const ActivationLayerInfo &act_info)
Static function to check if given info will lead to a valid configuration of CLActivationLayer.
Detailed Description
Basic function to run opencl::kernels::ClActivationKernel.
Note
The function simulates an activation layer with the specified activation function.
Definition at line 43 of file CLActivationLayer.h.
Constructor & Destructor Documentation
CLActivationLayer() [1/3]
CLActivationLayer (CLRuntimeContext * ctx = nullptr)
Constructor.
Parameters
[in] ctx Runtime context to be used by the function
Definition at line 44 of file CLActivationLayer.cpp.
     : _impl(std::make_unique<Impl>())
 {
     _impl->ctx = ctx;
 }
~CLActivationLayer()
~CLActivationLayer () default
Destructor.
CLActivationLayer() [2/3]
CLActivationLayer (const CLActivationLayer &) delete
Prevent instances of this class from being copied (As this class contains pointers)
CLActivationLayer() [3/3]
CLActivationLayer (CLActivationLayer &&) default
Default move constructor.
Member Function Documentation
configure() [1/2]
void configure (const CLCompileContext & compile_context, ICLTensor * input, ICLTensor * output, ActivationLayerInfo act_info)
Set the input and output tensor.
Note
If the output tensor is a nullptr or is equal to the input, the activation function will be performed in-place
Parameters
[in] compile_context The compile context to be used.
[in,out] input Source tensor. In case of output tensor = nullptr, this tensor will store the result of the activation function. Data types supported: QASYMM8/QASYMM8_SIGNED/QSYMM16/F16/F32.
[out] output Destination tensor. Data type supported: same as input
[in] act_info Activation layer parameters.
Definition at line 58 of file CLActivationLayer.cpp.
 {
     ARM_COMPUTE_ERROR_ON_NULLPTR(input);
     _impl->src = input;
     _impl->dst = output == nullptr ? input : output;
     _impl->op = std::make_unique<opencl::ClActivation>();
     _impl->op->configure(compile_context, _impl->src->info(), _impl->dst->info(), act_info);
 }
References arm_compute::test::validation::act_info, ARM_COMPUTE_ERROR_ON_NULLPTR, and arm_compute::test::validation::input.
configure() [2/2]
void configure (ICLTensor * input, ICLTensor * output, ActivationLayerInfo act_info)
Set the input and output tensor.
Valid data layouts:
All
Valid data type configurations:
src dst
QASYMM8 QASYMM8
QASYMM8_SIGNED QASYMM8_SIGNED
QSYMM16 QSYMM16
F16 F16
F32 F32
Note
If the output tensor is a nullptr or is equal to the input, the activation function will be performed in-place
Parameters
[in,out] input Source tensor. In case of output tensor = nullptr, this tensor will store the result of the activation function. Data types supported: QASYMM8/QASYMM8_SIGNED/QSYMM16/F16/F32.
[out] output Destination tensor. Data type supported: same as input
[in] act_info Activation layer parameters.
Definition at line 53 of file CLActivationLayer.cpp.
 {
     configure(CLKernelLibrary::get().get_compile_context(), input, output, act_info);
 }
References arm_compute::test::validation::act_info, CLKernelLibrary::get(), and arm_compute::test::validation::input.
Referenced by CLRNNLayer::configure(), CLFFTConvolutionLayer::configure(), CLLSTMLayerQuantized::configure(), CLLSTMLayer::configure(), CLQLSTMLayer::configure(), and arm_compute::test::validation::TEST_CASE().
operator=() [1/2]
CLActivationLayer & operator= (CLActivationLayer &&) default
Default move assignment operator.
operator=() [2/2]
CLActivationLayer& operator= (const CLActivationLayer &) delete
Prevent instances of this class from being copied (As this class contains pointers)
run()
void run () override virtual
Run the kernels contained in the function.
For CPU kernels:
Multi-threading is used for the kernels which are parallelisable.
By default std::thread::hardware_concurrency() threads are used.
Note
CPPScheduler::set_num_threads() can be used to manually set the number of threads
For OpenCL kernels:
All the kernels are enqueued on the queue associated with CLScheduler.
The queue is then flushed.
Note
The function will not block until the kernels are executed. It is the user's responsibility to wait.
Will call prepare() on first run if hasn't been done
Implements IFunction.
Definition at line 74 of file CLActivationLayer.cpp.
 {
     ITensorPack pack;
     pack.add_tensor(TensorType::ACL_SRC, _impl->src);
     pack.add_tensor(TensorType::ACL_DST, _impl->dst);
     _impl->op->run(pack);
 }
References arm_compute::ACL_DST, arm_compute::ACL_SRC, ITensorPack::add_tensor(), and arm_compute::test::validation::pack.
Referenced by CLRNNLayer::run(), CLFFTConvolutionLayer::run(), CLLSTMLayerQuantized::run(), CLLSTMLayer::run(), CLQLSTMLayer::run(), and arm_compute::test::validation::TEST_CASE().
validate()
Status validate (const ITensorInfo * input, const ITensorInfo * output, const ActivationLayerInfo & act_info) static
Static function to check if given info will lead to a valid configuration of CLActivationLayer.
Parameters
[in] input Source tensor info. In case of output tensor info = nullptr, this tensor will store the result of the activation function. Data types supported: QASYMM8/QASYMM8_SIGNED/QSYMM16/F16/F32.
[in] output Destination tensor info. Data type supported: same as input
[in] act_info Activation layer information.
Returns
a status
Definition at line 69 of file CLActivationLayer.cpp.
 {
     return opencl::ClActivation::validate(input, output, act_info);
 }
References arm_compute::test::validation::act_info, arm_compute::test::validation::input, and ClActivation::validate().
Referenced by CLRNNLayer::validate(), CLFFTConvolutionLayer::validate(), CLLSTMLayerQuantized::validate(), CLLSTMLayer::validate(), and CLQLSTMLayer::validate().
The documentation for this class was generated from the following files:
arm_compute/runtime/CL/functions/CLActivationLayer.h
src/runtime/CL/functions/CLActivationLayer.cpp