Compute Library: ClWorkloadRuntime Class Reference
ClWorkloadRuntime Class Reference
OpenCL runtime to run a workload.
#include <ClWorkloadRuntime.h>
Public Member Functions
ClWorkloadRuntime ()
~ClWorkloadRuntime ()
Status configure (const GpuWorkloadSketch &sketch)
Configure ClWorkloadRuntime.
Status run (const std::vector< CLTensor * > &tensors)
Perform run workload.
std::vector< std::tuple< CLTensor *, TensorInfo, AuxMemoryInfo > > get_auxiliary_tensors ()
Get auxiliary tensors of the workload and their memory requirement.
Detailed Description
OpenCL runtime to run a workload.
Definition at line 45 of file ClWorkloadRuntime.h.
Constructor & Destructor Documentation
ClWorkloadRuntime()
ClWorkloadRuntime ()
Definition at line 279 of file ClWorkloadRuntime.cpp.
     : _impl{ std::make_unique<Implementation>() }
 {
 }
~ClWorkloadRuntime()
~ClWorkloadRuntime () default
Member Function Documentation
configure()
Status configure (const GpuWorkloadSketch & sketch)
Configure ClWorkloadRuntime.
Note
A runtime cannot be re-configured
Parameters
[in] sketch GpuWorkloadSketch with which to configure
Definition at line 286 of file ClWorkloadRuntime.cpp.
 {
     ARM_COMPUTE_RETURN_ERROR_ON_MSG(_impl->_is_configured, "ClWorkloadRuntime cannot be re-configured");
     ARM_COMPUTE_RETURN_ERROR_ON_MSG(sketch.gpu_context()->gpu_language() != GpuLanguage::OpenCL, "ClWorkloadRuntime cannot be configured with non-OpenCL workload sketch");
     // Generate source code
     _impl->_source_code = sketch.implementation().generate_source_code();
     // Configure unit workload from source code
     for(auto uwk_id : _impl->_source_code.unit_workloads())
     {
         const auto work  = _impl->_source_code.query_unit_workload(uwk_id);
         const auto stage = work.stage().stage;
         auto       k     = std::make_unique<ClKernelRuntime>();
         k->configure(*sketch.gpu_context()->cl_compile_context(), work.code());
         switch(stage)
         {
             case UnitWorkloadStage::Stage::Run:
             {
                 _impl->_kernels.emplace(work.id(), std::move(k));
                 break;
             }
             case UnitWorkloadStage::Stage::Prepare:
             {
                 _impl->_kernels_prep.emplace(work.id(), std::move(k));
                 break;
             }
             default:
             {
                 ARM_COMPUTE_ERROR("Invalid unit workload stage");
             }
         }
     }
     // Create auxiliary tensor objects
     create_aux_tensors(&_impl->_aux_tensors, _impl->_source_code);
     _impl->_is_configured = true;
     return Status{};
 }
References ARM_COMPUTE_ERROR, ARM_COMPUTE_RETURN_ERROR_ON_MSG, GpuWorkloadContext::cl_compile_context(), GpuWorkloadSketch::Implementation::generate_source_code(), GpuWorkloadSketch::gpu_context(), GpuWorkloadContext::gpu_language(), GpuWorkloadSketch::implementation(), arm_compute::test::validation::k, arm_compute::experimental::dynamic_fusion::OpenCL, UnitWorkloadStage::Prepare, UnitWorkloadStage::Run, and arm_compute::test::validation::sketch.
Referenced by arm_compute::test::validation::TEST_CASE().
get_auxiliary_tensors()
std::vector< std::tuple< CLTensor *, TensorInfo, AuxMemoryInfo > > get_auxiliary_tensors ()
Get auxiliary tensors of the workload and their memory requirement.
Definition at line 358 of file ClWorkloadRuntime.cpp.
 {
     std::vector<std::tuple<CLTensor *, TensorInfo, AuxMemoryInfo>> aux_tensors;
     for(const auto &data : _impl->_aux_tensors.get_tensors())
     {
         aux_tensors.emplace_back(data.tensor, data.tensor_info, data.memory_info);
     }
     return aux_tensors;
 }
Referenced by arm_compute::test::validation::TEST_CASE().
run()
Status run (const std::vector< CLTensor * > & tensors)
Perform run workload.
Note
If the runtime is not configured, this method will not perform any action
Parameters
[in,out] tensors Tensors required by the run workloads
Returns
Status If the run is successful
Definition at line 340 of file ClWorkloadRuntime.cpp.
 {
     // Need to create the tensor lut in every run, unless the user can guarantee the binding remains fixed,
     // in which case the lut can be cached during prepare
     const auto st = create_tensor_lut(&_impl->_tensor_lut, _impl->_source_code, tensors, _impl->_aux_tensors);
     ARM_COMPUTE_RETURN_ON_ERROR(st);
     prepare();
     for(auto &id_kernel_pair : _impl->_kernels)
     {
         // Flush the command queue on the last kernel
         const bool flush_queue = false;
         const auto uwk_id      = id_kernel_pair.first;
         auto       kernel      = id_kernel_pair.second.get();
         CLScheduler::get().enqueue_op(*kernel, _impl->_tensor_lut.get_tensor_pack(uwk_id), flush_queue);
     }
     return Status{};
 }
References ARM_COMPUTE_RETURN_ON_ERROR, CLScheduler::enqueue_op(), and CLScheduler::get().
Referenced by arm_compute::test::validation::TEST_CASE().
The documentation for this class was generated from the following files:
arm_compute/dynamic_fusion/runtime/gpu/cl/ClWorkloadRuntime.h
src/dynamic_fusion/runtime/gpu/cl/ClWorkloadRuntime.cpp