Compute Library: CLSpaceToDepthLayer Class Reference
CLSpaceToDepthLayer Class Reference
Basic function to run CLSpaceToDepthLayerKernel.
#include <CLSpaceToDepthLayer.h>
Public Member Functions
CLSpaceToDepthLayer ()
Default constructor.
CLSpaceToDepthLayer (const CLSpaceToDepthLayer &)=delete
Prevent instances of this class from being copied.
CLSpaceToDepthLayer & operator= (const CLSpaceToDepthLayer &)=delete
Prevent instances of this class from being copied.
CLSpaceToDepthLayer (CLSpaceToDepthLayer &&)=delete
Prevent instances of this class to be moved.
CLSpaceToDepthLayer & operator= (CLSpaceToDepthLayer &&)=delete
Prevent instances of this class to be moved.
~CLSpaceToDepthLayer ()
Default destructor.
void configure (const ICLTensor *input, ICLTensor *output, int32_t block_shape)
Set the input and output tensors.
void configure (const CLCompileContext &compile_context, const ICLTensor *input, ICLTensor *output, int32_t block_shape)
Set the input and output tensors.
void run () override
Run the kernels contained in the function.
Public Member Functions inherited from IFunction
virtual ~IFunction ()=default
Destructor.
virtual void prepare ()
Prepare the function for executing.
Static Public Member Functions
static Status validate (const ITensorInfo *input, const ITensorInfo *output, int32_t block_shape)
Static function to check if given info will lead to a valid configuration of CLSpaceToDepthLayer.
Detailed Description
Basic function to run CLSpaceToDepthLayerKernel.
Definition at line 40 of file CLSpaceToDepthLayer.h.
Constructor & Destructor Documentation
CLSpaceToDepthLayer() [1/3]
CLSpaceToDepthLayer ()
Default constructor.
Definition at line 38 of file CLSpaceToDepthLayer.cpp.
     : _space_to_depth_kernel(std::make_unique<CLSpaceToDepthLayerKernel>())
 {
 }
CLSpaceToDepthLayer() [2/3]
CLSpaceToDepthLayer (const CLSpaceToDepthLayer &) delete
Prevent instances of this class from being copied.
CLSpaceToDepthLayer() [3/3]
CLSpaceToDepthLayer (CLSpaceToDepthLayer &&) delete
Prevent instances of this class to be moved.
~CLSpaceToDepthLayer()
~CLSpaceToDepthLayer () default
Default destructor.
Member Function Documentation
configure() [1/2]
void configure (const CLCompileContext & compile_context, const ICLTensor * input, ICLTensor * output, int32_t block_shape)
Set the input and output tensors.
Parameters
[in] compile_context The compile context to be used.
[in] input Tensor input. Supported tensor rank: 4. Data types supported: All.
[out] output Tensor output. Data types supported: same as input
[in] block_shape Block shape value.
Definition at line 50 of file CLSpaceToDepthLayer.cpp.
 {
     ARM_COMPUTE_LOG_PARAMS(input, output, block_shape);
     _space_to_depth_kernel->configure(compile_context, input, output, block_shape);
 }
References ARM_COMPUTE_LOG_PARAMS, and arm_compute::test::validation::input.
configure() [2/2]
void configure (const ICLTensor * input, ICLTensor * output, int32_t block_shape)
Set the input and output tensors.
Valid data layouts:
NHWC
NCHW
Valid data type configurations:
src dst
All All
Parameters
[in] input Tensor input. Supported tensor rank: 4. Data types supported: All.
[out] output Tensor output. Data types supported: same as input
[in] block_shape Block shape value.
Definition at line 45 of file CLSpaceToDepthLayer.cpp.
 {
     configure(CLKernelLibrary::get().get_compile_context(), input, output, block_shape);
 }
References CLKernelLibrary::get(), and arm_compute::test::validation::input.
operator=() [1/2]
CLSpaceToDepthLayer& operator= (CLSpaceToDepthLayer &&) delete
Prevent instances of this class to be moved.
operator=() [2/2]
CLSpaceToDepthLayer& operator= (const CLSpaceToDepthLayer &) delete
Prevent instances of this class from being copied.
run()
void run () override virtual
Run the kernels contained in the function.
For CPU kernels:
Multi-threading is used for the kernels which are parallelisable.
By default std::thread::hardware_concurrency() threads are used.
Note
CPPScheduler::set_num_threads() can be used to manually set the number of threads
For OpenCL kernels:
All the kernels are enqueued on the queue associated with CLScheduler.
The queue is then flushed.
Note
The function will not block until the kernels are executed. It is the user's responsibility to wait.
Will call prepare() on first run if hasn't been done
Implements IFunction.
Definition at line 61 of file CLSpaceToDepthLayer.cpp.
 {
     CLScheduler::get().enqueue(*_space_to_depth_kernel, true);
 }
References CLScheduler::enqueue(), and CLScheduler::get().
validate()
Status validate (const ITensorInfo * input, const ITensorInfo * output, int32_t block_shape) static
Static function to check if given info will lead to a valid configuration of CLSpaceToDepthLayer.
Parameters
[in] input Tensor input info. Supported tensor rank: 4. Data types supported: All.
[in] output Tensor output info. Data types supported: same as input
[in] block_shape Block shape value.
Returns
a status
Definition at line 56 of file CLSpaceToDepthLayer.cpp.
 {
     return CLSpaceToDepthLayerKernel::validate(input, output, block_shape);
 }
References arm_compute::test::validation::input, and CLSpaceToDepthLayerKernel::validate().
The documentation for this class was generated from the following files:
arm_compute/runtime/CL/functions/CLSpaceToDepthLayer.h
src/runtime/CL/functions/CLSpaceToDepthLayer.cpp