Compute Library: ClComponentElementwiseBinary Class Reference
ClComponentElementwiseBinary Class Reference final
#include <ClComponentElementwiseBinary.h>
Public Types
using Attributes = ElementwiseBinaryCommonAttributes
Attributes are a set of backend-agnostic parameters that define what a component does.
Public Types inherited from IGpuKernelComponent
using Properties = KernelProperties
Public Member Functions
ClComponentElementwiseBinary (ComponentId id, const Properties &properties, const ArgumentPack< ITensorInfo > &tensors, const Attributes &attributes)
Constructor.
~ClComponentElementwiseBinary () override
Destructor.
ClComponentElementwiseBinary (const ClComponentElementwiseBinary &component)=delete
Prevent instances of this class from being copy constructed.
ClComponentElementwiseBinary & operator= (const ClComponentElementwiseBinary &component)=delete
Prevent instances of this class from being copied.
ClComponentElementwiseBinary (ClComponentElementwiseBinary &&component)=default
Allow instances of this class to be move constructed.
ClComponentElementwiseBinary & operator= (ClComponentElementwiseBinary &&component)=default
Allow instances of this class to be moved.
const IGpuTemplateComponentWriter * template_writer () const override
Get writer for the component.
GpuComponentType type () const override
Get component type.
Public Member Functions inherited from IGpuKernelComponent
IGpuKernelComponent (ComponentId id, const Properties &properties, const ArgumentPack< ITensorInfo > &tensors)
Constructor.
virtual ~IGpuKernelComponent ()
Destructor.
ComponentId id () const
Get component id.
ArgumentPack< ITensorInfo > tensors () const
Get tensor arguments.
Properties properties () const
Get properties.
virtual const IGpuCkwComponentDriver * ckw_component_driver () const
Static Public Member Functions
static Status validate (const ArgumentPack< ITensorInfo > &tensors, const ElementwiseBinaryCommonAttributes &attributes)
Validate the component.
Detailed Description
Definition at line 49 of file ClComponentElementwiseBinary.h.
Member Typedef Documentation
Attributes
using Attributes = ElementwiseBinaryCommonAttributes
Attributes are a set of backend-agnostic parameters that define what a component does.
Definition at line 53 of file ClComponentElementwiseBinary.h.
Constructor & Destructor Documentation
ClComponentElementwiseBinary() [1/3]
ClComponentElementwiseBinary (ComponentId id, const Properties & properties, const ArgumentPack< ITensorInfo > & tensors, const Attributes & attributes)
Constructor.
Similar to ClComponentElementwiseBinary::validate()
Definition at line 115 of file ClComponentElementwiseBinary.cpp.
     : IGpuKernelComponent{ id, properties, tensors },
 #ifndef ACL_INTERNAL_TEST_CKW_IN_DF
       _component_writer
 {
     std::make_unique<ClTemplateElementwiseBinary>(id, tensors, attributes)
 }
 #else  //ACL_INTERNAL_TEST_CKW_IN_DF
       _component_writer
 {
     std::make_unique<GpuCkwElementwiseBinary>(id, tensors, attributes)
 }
 #endif //ACL_INTERNAL_TEST_CKW_IN_DF
 {
 }
References IGpuKernelComponent::id(), IGpuKernelComponent::properties(), and IGpuKernelComponent::tensors().
~ClComponentElementwiseBinary()
~ClComponentElementwiseBinary () override
Destructor.
Definition at line 112 of file ClComponentElementwiseBinary.cpp.
 {
 }
ClComponentElementwiseBinary() [2/3]
ClComponentElementwiseBinary (const ClComponentElementwiseBinary & component) delete
Prevent instances of this class from being copy constructed.
ClComponentElementwiseBinary() [3/3]
ClComponentElementwiseBinary (ClComponentElementwiseBinary && component) default
Allow instances of this class to be move constructed.
Member Function Documentation
operator=() [1/2]
ClComponentElementwiseBinary& operator= (ClComponentElementwiseBinary && component) default
Allow instances of this class to be moved.
operator=() [2/2]
ClComponentElementwiseBinary& operator= (const ClComponentElementwiseBinary & component) delete
Prevent instances of this class from being copied.
template_writer()
const IGpuTemplateComponentWriter * template_writer () const override virtual
Get writer for the component.
Reimplemented from IGpuKernelComponent.
Definition at line 136 of file ClComponentElementwiseBinary.cpp.
 {
     return _component_writer.get();
 }
type()
GpuComponentType type () const inline override virtual
Get component type.
Implements IGpuKernelComponent.
Definition at line 115 of file ClComponentElementwiseBinary.h.
     {
         return GpuComponentType::Simple;
     }
References arm_compute::experimental::dynamic_fusion::Simple.
validate()
Status validate (const ArgumentPack< ITensorInfo > & tensors, const ElementwiseBinaryCommonAttributes & attributes) static
Validate the component.
Parameters
[in,out] tensors Tensor arguments to the component
[in] attributes Component attributes
Returns
Status Validation results
Tensor argument names:
ACL_SRC_0: lhs
ACL_SRC_1: rhs
ACL_DST_0: dst
Tensor argument constness:
ACL_SRC_0: Const
ACL_SRC_1: Const
ACL_DST_0: Const
Valid data layouts:
All
Valid data type configurations (for DIV FP32/FP16/S32 supported, for POWER only FP32/FP16 supported):
ACL_SRC_0 ACL_SRC_1 ACL_DST_0
F16 F16 F16
F32 F32 F32
S32 S32 S32
S16 S16 S16
U8 U8 U8
Definition at line 50 of file ClComponentElementwiseBinary.cpp.
 {
     const auto lhs = tensors.get_const_tensor(TensorType::ACL_SRC_0);
     const auto rhs = tensors.get_const_tensor(TensorType::ACL_SRC_1);
     const auto dst = tensors.get_const_tensor(TensorType::ACL_DST_0);
     // Check operator type
     ARM_COMPUTE_RETURN_ERROR_ON_MSG(supported_ops.find(attributes.operation()) == supported_ops.end(), "Provided Elementwise operation not supported.");
     // Check validity
     ARM_COMPUTE_RETURN_ERROR_ON_NULLPTR(lhs, rhs, dst);
     //Check data type for different elementwise operators
     ARM_COMPUTE_RETURN_ERROR_ON_DATA_TYPE_CHANNEL_NOT_IN(lhs, 1, DataType::F32, DataType::F16, DataType::S32, DataType::S16, DataType::U8);
     // dst shape is correct
     const TensorShape out_shape = TensorShape::broadcast_shape(lhs->tensor_shape(), rhs->tensor_shape());
     ARM_COMPUTE_RETURN_ERROR_ON_MSG(out_shape.total_size() == 0, "Inputs are not broadcast compatible");
     ARM_COMPUTE_RETURN_ERROR_ON_MSG(detail::have_different_dimensions(out_shape, dst->tensor_shape(), 0), "Wrong shape for dst.");
     const auto &lhs_shape = lhs->tensor_shape();
     const auto &rhs_shape = rhs->tensor_shape();
     const auto &dst_shape = dst->tensor_shape();
     ARM_COMPUTE_RETURN_ERROR_ON_MSG(
         detail::have_different_dimensions(lhs_shape, dst_shape, 0) && detail::have_different_dimensions(rhs_shape, dst_shape, 0),
         "Only LHS or RHS can be broadcasting, not both.");
     // Dimension Y and Z are collapsed together in the current kernel implementation,
     // hence they cannot be independently broadcast or non-broadcast.
     // See: ClTemplateElementwiseBinary::get_window
     ARM_COMPUTE_RETURN_ERROR_ON_MSG(
         (lhs_shape[1] != dst_shape[1] || rhs_shape[1] != dst_shape[1]) != (lhs_shape[2] != dst_shape[2] || rhs_shape[2] != dst_shape[2]),
         "Dimension Y and Z must both be either broadcast or non-broadcast.");
     ARM_COMPUTE_RETURN_ERROR_ON_MSG(
         detail::have_different_dimensions(lhs_shape, dst_shape, 3),
         "LHS broadcast in dimension 3 or higher is not supported.");
     ARM_COMPUTE_RETURN_ERROR_ON_MSG(
         detail::have_different_dimensions(rhs_shape, dst_shape, 3),
         "RHS broadcast in dimension 3 or higher is not supported.");
     // Matching data type
     ARM_COMPUTE_RETURN_ERROR_ON_MISMATCHING_DATA_TYPES(lhs, rhs);
     ARM_COMPUTE_RETURN_ERROR_ON_MISMATCHING_DATA_TYPES(lhs, dst);
     // Matching data layout
     ARM_COMPUTE_RETURN_ERROR_ON_MISMATCHING_DATA_LAYOUT(lhs, rhs);
     ARM_COMPUTE_RETURN_ERROR_ON_MISMATCHING_DATA_LAYOUT(lhs, dst);
     // All tensor infos are initialized
     ARM_COMPUTE_RETURN_ERROR_ON(lhs->tensor_shape().total_size() == 0);
     ARM_COMPUTE_RETURN_ERROR_ON(rhs->tensor_shape().total_size() == 0);
     ARM_COMPUTE_RETURN_ERROR_ON(dst->tensor_shape().total_size() == 0);
     // Device requirements are met
     ARM_COMPUTE_RETURN_ERROR_ON_F16_UNSUPPORTED(lhs);
     return Status{};
 }
References arm_compute::ACL_DST_0, arm_compute::ACL_SRC_0, arm_compute::ACL_SRC_1, ARM_COMPUTE_RETURN_ERROR_ON, ARM_COMPUTE_RETURN_ERROR_ON_DATA_TYPE_CHANNEL_NOT_IN, ARM_COMPUTE_RETURN_ERROR_ON_F16_UNSUPPORTED, ARM_COMPUTE_RETURN_ERROR_ON_MISMATCHING_DATA_LAYOUT, ARM_COMPUTE_RETURN_ERROR_ON_MISMATCHING_DATA_TYPES, ARM_COMPUTE_RETURN_ERROR_ON_MSG, ARM_COMPUTE_RETURN_ERROR_ON_NULLPTR, TensorShape::broadcast_shape(), arm_compute::test::validation::dst, arm_compute::test::validation::dst_shape, arm_compute::F16, arm_compute::F32, arm_compute::detail::have_different_dimensions(), ElementwiseBinaryCommonAttributes::operation(), arm_compute::S16, arm_compute::S32, IGpuKernelComponent::tensors(), TensorShape::total_size(), and arm_compute::U8.
The documentation for this class was generated from the following files:
src/dynamic_fusion/sketch/gpu/components/cl/ClComponentElementwiseBinary.h
src/dynamic_fusion/sketch/gpu/components/cl/ClComponentElementwiseBinary.cpp