Compute Library: IGpuTemplateComponentWriter Class Reference
IGpuTemplateComponentWriter Class Reference abstract
An interface used by ClTemplateWriter to write source code for a kernel component.
#include <IGpuTemplateComponentWriter.h>
Public Types
using ComponentGroup = GpuKernelComponentGroup
Public Member Functions
IGpuTemplateComponentWriter (ComponentId id, const ArgumentPack< ITensorInfo > &tensors)
Constructor.
virtual ~IGpuTemplateComponentWriter ()
Destructor.
virtual std::string get_name () const =0
Generate kernel component name.
virtual std::string get_component_code (const ComponentGroup &comp_group) const =0
Generate kernel component code template.
virtual void declare_variables (GpuKernelVariableTable &vtable, const ComponentGroup &comp_group) const =0
Declare all variables used by the component in the vtable.
virtual TagLUT get_tag_lut (const GpuKernelVariableTable &vtable, const ComponentGroup &comp_group) const =0
Generate the tag look-up table used to instantiate the component code.
virtual std::string get_additional_macros () const
Generate additional macros used in the component.
virtual CLBuildOptions get_build_options (const ComponentGroup &comp_group) const
Generate the build options used in the component.
virtual std::string get_config_id () const
Generate the component config id string used for tuning.
virtual std::set< std::string > get_headers_list () const
Generate the header list used in the component.
virtual Window get_window () const
Generate the execution window for the component.
ArgumentPack< ITensorInfo > tensors () const
Get tensor arguments.
ComponentId id () const
Get component id.
Static Public Attributes
static constexpr GpuKernelArgumentInfo::Type common_tensor_type = GpuKernelArgumentInfo::Type::Tensor_4D_t_Buffer
For now all kernel intermeditate/destination tensors are expected to be of type Tensor_4D_t_Buffer.
Detailed Description
An interface used by ClTemplateWriter to write source code for a kernel component.
Definition at line 46 of file IGpuTemplateComponentWriter.h.
Member Typedef Documentation
ComponentGroup
using ComponentGroup = GpuKernelComponentGroup
Definition at line 49 of file IGpuTemplateComponentWriter.h.
Constructor & Destructor Documentation
IGpuTemplateComponentWriter()
IGpuTemplateComponentWriter (ComponentId id, const ArgumentPack< ITensorInfo > & tensors) inline
Constructor.
Parameters
[in] id Component id
[in] tensors Tensor arguments to the components
Definition at line 60 of file IGpuTemplateComponentWriter.h.
         : _id{ id }, _tensors{ tensors }
     {
     }
~IGpuTemplateComponentWriter()
virtual ~IGpuTemplateComponentWriter () inline virtual
Destructor.
Definition at line 65 of file IGpuTemplateComponentWriter.h.
     {
     }
Member Function Documentation
declare_variables()
virtual void declare_variables (GpuKernelVariableTable & vtable, const ComponentGroup & comp_group) const pure virtual
Declare all variables used by the component in the vtable.
Parameters
[out] vtable Variable table
[in] comp_group Component group of which the component is a part of
Implemented in ClTemplatePool2d, ClTemplateActivation, ClTemplateResize, ClTemplateDirectConv2d, ClTemplateElementwiseBinary, ClTemplateDepthwiseConv2d, ClTemplateLogits1DMaxShiftExpSum, ClTemplateLogits1DNorm, ClTemplateReshape, ClTemplateCast, and ClTemplateStore.
get_additional_macros()
virtual std::string get_additional_macros () const inline virtual
Generate additional macros used in the component.
Definition at line 92 of file IGpuTemplateComponentWriter.h.
     {
         return "";
     }
get_build_options()
virtual CLBuildOptions get_build_options (const ComponentGroup & comp_group) const inline virtual
Generate the build options used in the component.
Parameters
[in] comp_group Component group of which the component is a part of
Returns
CLBuildOptions Build options
Reimplemented in ClTemplateActivation, ClTemplatePool2d, ClTemplateResize, ClTemplateDirectConv2d, ClTemplateElementwiseBinary, ClTemplateDepthwiseConv2d, ClTemplateReshape, ClTemplateLogits1DMaxShiftExpSum, ClTemplateLogits1DNorm, and ClTemplateCast.
Definition at line 102 of file IGpuTemplateComponentWriter.h.
     {
         ARM_COMPUTE_UNUSED(comp_group);
         return CLBuildOptions{};
     }
References ARM_COMPUTE_UNUSED.
get_component_code()
virtual std::string get_component_code (const ComponentGroup & comp_group) const pure virtual
Generate kernel component code template.
Parameters
[in] comp_group Component group of which the component is a part of
Returns
std::string Component code
Implemented in ClTemplatePool2d, ClTemplateActivation, ClTemplateDirectConv2d, ClTemplateResize, ClTemplateElementwiseBinary, ClTemplateDepthwiseConv2d, ClTemplateLogits1DMaxShiftExpSum, ClTemplateLogits1DNorm, ClTemplateCast, ClTemplateReshape, and ClTemplateStore.
get_config_id()
virtual std::string get_config_id () const inline virtual
Generate the component config id string used for tuning.
Reimplemented in ClTemplateActivation, ClTemplatePool2d, ClTemplateResize, ClTemplateElementwiseBinary, ClTemplateDirectConv2d, ClTemplateDepthwiseConv2d, ClTemplateReshape, ClTemplateLogits1DMaxShiftExpSum, ClTemplateLogits1DNorm, and ClTemplateCast.
Definition at line 108 of file IGpuTemplateComponentWriter.h.
     {
         return "";
     }
get_headers_list()
virtual std::set<std::string> get_headers_list () const inline virtual
Generate the header list used in the component.
Reimplemented in ClTemplateActivation, ClTemplatePool2d, ClTemplateResize, ClTemplateElementwiseBinary, ClTemplateDirectConv2d, ClTemplateDepthwiseConv2d, ClTemplateReshape, ClTemplateLogits1DMaxShiftExpSum, ClTemplateLogits1DNorm, and ClTemplateCast.
Definition at line 113 of file IGpuTemplateComponentWriter.h.
     {
         return std::set<std::string> {};
     }
get_name()
virtual std::string get_name () const pure virtual
Generate kernel component name.
Implemented in ClTemplatePool2d, ClTemplateActivation, ClTemplateDirectConv2d, ClTemplateResize, ClTemplateDepthwiseConv2d, ClTemplateElementwiseBinary, ClTemplateLogits1DMaxShiftExpSum, ClTemplateLogits1DNorm, ClTemplateCast, ClTemplateReshape, and ClTemplateStore.
get_tag_lut()
virtual TagLUT get_tag_lut (const GpuKernelVariableTable & vtable, const ComponentGroup & comp_group) const pure virtual
Generate the tag look-up table used to instantiate the component code.
Parameters
[in] vtable Variable table
[in] comp_group Component group of which the component is a part of
Returns
TagLUT Tag lookup table
Implemented in ClTemplateActivation, ClTemplatePool2d, ClTemplateResize, ClTemplateDirectConv2d, ClTemplateElementwiseBinary, ClTemplateDepthwiseConv2d, ClTemplateReshape, ClTemplateLogits1DMaxShiftExpSum, ClTemplateLogits1DNorm, ClTemplateCast, and ClTemplateStore.
get_window()
virtual Window get_window () const inline virtual
Generate the execution window for the component.
Reimplemented in ClTemplateActivation, ClTemplatePool2d, ClTemplateResize, ClTemplateElementwiseBinary, ClTemplateDirectConv2d, ClTemplateDepthwiseConv2d, ClTemplateReshape, ClTemplateLogits1DMaxShiftExpSum, ClTemplateLogits1DNorm, and ClTemplateCast.
Definition at line 118 of file IGpuTemplateComponentWriter.h.
     {
         return Window{};
     }
Referenced by ClTemplateCast::get_build_options(), ClTemplateLogits1DNorm::get_build_options(), ClTemplateReshape::get_build_options(), ClTemplateDirectConv2d::get_build_options(), ClTemplateResize::get_build_options(), ClTemplatePool2d::get_build_options(), and ClTemplateActivation::get_build_options().
id()
ComponentId id () const inline
Get component id.
Definition at line 128 of file IGpuTemplateComponentWriter.h.
     {
         return _id;
     }
Referenced by ClTemplateActivation::ClTemplateActivation(), ClTemplateCast::ClTemplateCast(), ClTemplateDepthwiseConv2d::ClTemplateDepthwiseConv2d(), ClTemplateDirectConv2d::ClTemplateDirectConv2d(), ClTemplateElementwiseBinary::ClTemplateElementwiseBinary(), ClTemplateLogits1DMaxShiftExpSum::ClTemplateLogits1DMaxShiftExpSum(), ClTemplateLogits1DNorm::ClTemplateLogits1DNorm(), ClTemplatePool2d::ClTemplatePool2d(), ClTemplateReshape::ClTemplateReshape(), ClTemplateResize::ClTemplateResize(), ClTemplateStore::ClTemplateStore(), ClTemplateCast::get_component_code(), ClTemplateElementwiseBinary::get_component_code(), ClTemplateActivation::get_component_code(), ClTemplateStore::get_tag_lut(), ClTemplateCast::get_tag_lut(), ClTemplateLogits1DNorm::get_tag_lut(), ClTemplateLogits1DMaxShiftExpSum::get_tag_lut(), ClTemplateReshape::get_tag_lut(), ClTemplateDepthwiseConv2d::get_tag_lut(), ClTemplateDirectConv2d::get_tag_lut(), ClTemplateResize::get_tag_lut(), ClTemplateActivation::get_tag_lut(), and ClTemplatePool2d::get_tag_lut().
tensors()
ArgumentPack<ITensorInfo> tensors () const inline
Get tensor arguments.
Definition at line 123 of file IGpuTemplateComponentWriter.h.
     {
         return _tensors;
     }
Referenced by ClTemplateActivation::ClTemplateActivation(), ClTemplateCast::ClTemplateCast(), ClTemplateDepthwiseConv2d::ClTemplateDepthwiseConv2d(), ClTemplateDirectConv2d::ClTemplateDirectConv2d(), ClTemplateElementwiseBinary::ClTemplateElementwiseBinary(), ClTemplateLogits1DMaxShiftExpSum::ClTemplateLogits1DMaxShiftExpSum(), ClTemplateLogits1DNorm::ClTemplateLogits1DNorm(), ClTemplatePool2d::ClTemplatePool2d(), ClTemplateReshape::ClTemplateReshape(), ClTemplateResize::ClTemplateResize(), and ClTemplateStore::ClTemplateStore().
Field Documentation
common_tensor_type
constexpr GpuKernelArgumentInfo::Type common_tensor_type = GpuKernelArgumentInfo::Type::Tensor_4D_t_Buffer static constexpr
For now all kernel intermeditate/destination tensors are expected to be of type Tensor_4D_t_Buffer.
Definition at line 52 of file IGpuTemplateComponentWriter.h.
Referenced by ClTemplateReshape::declare_variables(), and ClTemplateDirectConv2d::declare_variables().
The documentation for this class was generated from the following file:
src/dynamic_fusion/sketch/gpu/template_writer/IGpuTemplateComponentWriter.h