Compute Library: CpuGemmAssemblyWrapperKernel< TypeInput, TypeOutput > Class Template Reference
CpuGemmAssemblyWrapperKernel< TypeInput, TypeOutput > Class Template Reference final
This class is a wrapper for the assembly kernels.
#include <CpuGemmAssemblyWrapperKernel.h>
Public Member Functions
CpuGemmAssemblyWrapperKernel ()
Constructor.
CpuGemmAssemblyWrapperKernel (CpuGemmAssemblyWrapperKernel &)=delete
CpuGemmAssemblyWrapperKernel (CpuGemmAssemblyWrapperKernel &&)=default
CpuGemmAssemblyWrapperKernel & operator= (CpuGemmAssemblyWrapperKernel &)=delete
const char * name () const override
Name of the kernel.
void run (const Window &window, const ThreadInfo &info) override
Execute the kernel on the passed window.
void run_nd (const Window &window, const ThreadInfo &info, const Window &thread_locator) override
legacy compatibility layer for implemantions which do not support thread_locator In these cases we simply narrow the interface down the legacy version
void configure (arm_gemm::GemmCommon< TypeInput, TypeOutput > *kernel, std::string kernel_name_tag)
Initialise the kernel's input and output.
size_t get_mws (const CPUInfo &platform, size_t thread_count) const override
Return minimum workload size of the relevant kernel.
Public Member Functions inherited from ICPPKernel
virtual ~ICPPKernel ()=default
Default destructor.
virtual void run_op (ITensorPack &tensors, const Window &window, const ThreadInfo &info)
Execute the kernel on the passed window.
Public Member Functions inherited from IKernel
IKernel ()
Constructor.
virtual ~IKernel ()=default
Destructor.
virtual bool is_parallelisable () const
Indicates whether or not the kernel is parallelisable.
virtual BorderSize border_size () const
The size of the border for that kernel.
const Window & window () const
The maximum window the kernel can be executed on.
bool is_window_configured () const
Function to check if the embedded window of this kernel has been configured.
Additional Inherited Members
Static Public Attributes inherited from ICPPKernel
static constexpr size_t default_mws = 1
Detailed Description
template<typename TypeInput, typename TypeOutput>
class arm_compute::cpu::kernel::CpuGemmAssemblyWrapperKernel< TypeInput, TypeOutput >
This class is a wrapper for the assembly kernels.
Some kernels were written in assembly and highly optimised for specific CPUs like A53 or A55. This class works as a wrapper for these assembly kernels. The arm compute library creates an instance of CpuGemmAssemblyWrapperKernel and other auxiliary data structures to execute a single assembly kernel in the context of an NEFunctions.
The type T is the type of the actual kernel implemented in assembly which is of type template<typename To, typename Tr> class GemmCommon
Definition at line 55 of file CpuGemmAssemblyWrapperKernel.h.
Constructor & Destructor Documentation
CpuGemmAssemblyWrapperKernel() [1/3]
CpuGemmAssemblyWrapperKernel () inline
Constructor.
Definition at line 60 of file CpuGemmAssemblyWrapperKernel.h.
         : _kernel(nullptr), _name("CpuGemmAssemblyWrapperKernel")
     {
     }
CpuGemmAssemblyWrapperKernel() [2/3]
CpuGemmAssemblyWrapperKernel (CpuGemmAssemblyWrapperKernel< TypeInput, TypeOutput > &) delete
CpuGemmAssemblyWrapperKernel() [3/3]
CpuGemmAssemblyWrapperKernel (CpuGemmAssemblyWrapperKernel< TypeInput, TypeOutput > &&) default
Member Function Documentation
configure()
void configure (arm_gemm::GemmCommon< TypeInput, TypeOutput > * kernel, std::string kernel_name_tag) inline
Initialise the kernel's input and output.
Parameters
[in] kernel Pointer to an assembly kernel implementation.
[in] kernel_name_tag Tag to be attacehd to the kernel's name.
Definition at line 104 of file CpuGemmAssemblyWrapperKernel.h.
     {
         ARM_COMPUTE_ERROR_ON_NULLPTR((reinterpret_cast<void *>(kernel)));
         _kernel = kernel;
         Window win = to_window(kernel->get_window_size());
         INEKernel::configure(win);
         if(!kernel_name_tag.empty())
         {
             _name += "/" + kernel_name_tag;
         }
     }
References ARM_COMPUTE_ERROR_ON_NULLPTR, IGemmCommon::get_window_size(), and arm_gemm::to_window().
get_mws()
size_t get_mws (const CPUInfo & platform, size_t thread_count) const inline override virtual
Return minimum workload size of the relevant kernel.
Parameters
[in] platform The CPU platform used to create the context.
[in] thread_count Number of threads in the execution.
Returns
[out] small_network_mws Minimum workload size for requested configuration.
Reimplemented from ICPPKernel.
Definition at line 125 of file CpuGemmAssemblyWrapperKernel.h.
     {
         ARM_COMPUTE_UNUSED(thread_count);
         ARM_COMPUTE_UNUSED(platform);
         return ICPPKernel::default_mws;
     }
References ARM_COMPUTE_UNUSED, and ICPPKernel::default_mws.
name()
const char* name () const inline override virtual
Name of the kernel.
Returns
Kernel name
Implements ICPPKernel.
Definition at line 69 of file CpuGemmAssemblyWrapperKernel.h.
     {
         return _name.c_str();
     }
operator=()
CpuGemmAssemblyWrapperKernel& operator= (CpuGemmAssemblyWrapperKernel< TypeInput, TypeOutput > &) delete
run()
void run (const Window & window, const ThreadInfo & info) inline override virtual
Execute the kernel on the passed window.
Warning
If is_parallelisable() returns false then the passed window must be equal to window()
Note
The window has to be a region within the window returned by the window() method
The width of the window has to be a multiple of num_elems_processed_per_iteration().
Parameters
[in] window Region on which to execute the kernel. (Must be a region of the window returned by window())
[in] info Info about executing thread and CPU.
Reimplemented from ICPPKernel.
Definition at line 74 of file CpuGemmAssemblyWrapperKernel.h.
     {
         ARM_COMPUTE_ERROR_ON_NULLPTR((reinterpret_cast<void *>(_kernel)));
         ARM_COMPUTE_ERROR_ON_UNCONFIGURED_KERNEL(this);
         auto win = arm_gemm::to_ndcoord(window);
         arm_gemm::ndcoord_t thread_locator{};
         _kernel->execute(win, thread_locator, info.thread_id);
     }
References ARM_COMPUTE_ERROR_ON_NULLPTR, ARM_COMPUTE_ERROR_ON_UNCONFIGURED_KERNEL, IGemmCommon::execute(), arm_compute::test::validation::info, arm_gemm::to_ndcoord(), and IKernel::window().
run_nd()
void run_nd (const Window & window, const ThreadInfo & info, const Window & thread_locator) inline override virtual
legacy compatibility layer for implemantions which do not support thread_locator In these cases we simply narrow the interface down the legacy version
Parameters
[in] window Region on which to execute the kernel. (Must be a region of the window returned by window())
[in] info Info about executing thread and CPU.
[in] thread_locator Specifies "where" the current thread is in the multi-dimensional space
Reimplemented from ICPPKernel.
Definition at line 87 of file CpuGemmAssemblyWrapperKernel.h.
     {
         ARM_COMPUTE_ERROR_ON_NULLPTR((reinterpret_cast<void *>(_kernel)));
         ARM_COMPUTE_ERROR_ON_UNCONFIGURED_KERNEL(this);
         //convert between arm_compute and arm_gemm types
         auto ndc_win = arm_gemm::to_ndcoord(window);
         auto ndc_tlc = arm_gemm::to_ndcoord(thread_locator);
         _kernel->execute(ndc_win, ndc_tlc, info.thread_id);
     }
References ARM_COMPUTE_ERROR_ON_NULLPTR, ARM_COMPUTE_ERROR_ON_UNCONFIGURED_KERNEL, IGemmCommon::execute(), arm_compute::test::validation::info, arm_gemm::to_ndcoord(), and IKernel::window().
The documentation for this class was generated from the following file:
src/cpu/kernels/assembly/CpuGemmAssemblyWrapperKernel.h