Compute Library: GemmImplementation< Top, Tret, OutputStage > Struct Template Reference
GemmImplementation< Top, Tret, OutputStage > Struct Template Reference
#include <gemm_implementation.hpp>
Public Member Functions
bool do_is_supported (const GemmArgs &args, const OutputStage &os) const
uint64_t do_cycle_estimate (const GemmArgs &args, const OutputStage &os) const
GemmCommon< Top, Tret > * do_instantiate (const GemmArgs &args, const OutputStage &os) const
GemmImplementation (const GemmImplementation &)=default
GemmImplementation & operator= (const GemmImplementation &)=default
GemmImplementation (GemmMethod m, const char *n)
GemmImplementation (GemmMethod m, const char *n, std::function< bool(const GemmArgs &, const OutputStage &)> is_supported, std::function< bool(const GemmArgs &, const OutputStage &)> is_recommended, std::function< GemmCommon< Top, Tret > *(const GemmArgs &, const OutputStage &)> instantiate)
GemmImplementation (GemmMethod m, const char *n, KernelWeightFormat kwf, std::function< bool(const GemmArgs &, const OutputStage &)> is_supported, std::function< bool(const GemmArgs &, const OutputStage &)> is_recommended, std::function< GemmCommon< Top, Tret > *(const GemmArgs &, const OutputStage &)> instantiate)
Static Public Member Functions
static GemmImplementation with_estimate (GemmMethod m, const char *n, std::function< bool(const GemmArgs &, const OutputStage &)> is_supported, std::function< uint64_t(const GemmArgs &, const OutputStage &)> cycle_estimate, std::function< GemmCommon< Top, Tret > *(const GemmArgs &, const OutputStage &)> instantiate)
Data Fields
const GemmMethod method
const char * name
const KernelWeightFormat kernel_weight_format = KernelWeightFormat::NON_FIXED
std::function< bool(const GemmArgs &, const OutputStage &)> is_supported = {}
std::function< uint64_t(const GemmArgs &, const OutputStage &)> cycle_estimate = {}
std::function< GemmCommon< Top, Tret > *(const GemmArgs &, const OutputStage &)> instantiate = {}
Detailed Description
template<typename Top, typename Tret, class OutputStage = Nothing>
struct arm_gemm::GemmImplementation< Top, Tret, OutputStage >
Definition at line 39 of file gemm_implementation.hpp.
Constructor & Destructor Documentation
GemmImplementation() [1/4]
GemmImplementation (const GemmImplementation< Top, Tret, OutputStage > &) default
GemmImplementation() [2/4]
GemmImplementation (GemmMethod m, const char * n) inline
Definition at line 102 of file gemm_implementation.hpp.
 : method(m), name(n) {}
GemmImplementation() [3/4]
GemmImplementation (GemmMethod m, const char * n, std::function< bool(const GemmArgs &, const OutputStage &)> is_supported, std::function< bool(const GemmArgs &, const OutputStage &)> is_recommended, std::function< GemmCommon< Top, Tret > *(const GemmArgs &, const OutputStage &)> instantiate) inline
Definition at line 104 of file gemm_implementation.hpp.
                                                                                                                 :
                        method(m), name(n), is_supported(is_supported),
                        cycle_estimate( [is_recommended](const GemmArgs &args, const OutputStage &os) { return (is_recommended == nullptr) ? 0 : (is_recommended(args, os) ? 0 : UINT64_MAX); } ),
                        instantiate(instantiate) {   }
References GemmTuner::args.
GemmImplementation() [4/4]
GemmImplementation (GemmMethod m, const char * n, KernelWeightFormat kwf, std::function< bool(const GemmArgs &, const OutputStage &)> is_supported, std::function< bool(const GemmArgs &, const OutputStage &)> is_recommended, std::function< GemmCommon< Top, Tret > *(const GemmArgs &, const OutputStage &)> instantiate) inline
Definition at line 111 of file gemm_implementation.hpp.
                                                                                                                 :
                        method(m), name(n), kernel_weight_format(kwf), is_supported(is_supported),
                        cycle_estimate( [is_recommended](const GemmArgs &args, const OutputStage &os) { return (is_recommended == nullptr) ? 0 : (is_recommended(args, os) ? 0 : UINT64_MAX); } ),
                        instantiate(instantiate) {   }
References GemmTuner::args.
Member Function Documentation
do_cycle_estimate()
uint64_t do_cycle_estimate (const GemmArgs & args, const OutputStage & os) const inline
Definition at line 75 of file gemm_implementation.hpp.
{
         if (cycle_estimate != nullptr) {
             return cycle_estimate(args, os);
         } else {
             return 0;
         }
     }
References GemmTuner::args, and GemmImplementation< Top, Tret, OutputStage >::cycle_estimate.
Referenced by arm_gemm::find_implementation(), and arm_gemm::get_compatible_kernels().
do_instantiate()
GemmCommon<Top, Tret>* do_instantiate (const GemmArgs & args, const OutputStage & os) const inline
Definition at line 83 of file gemm_implementation.hpp.
{
         return instantiate(args, os);
     }
References GemmTuner::args, and GemmImplementation< Top, Tret, OutputStage >::instantiate.
Referenced by arm_gemm::gemm(), and arm_gemm::has_opt_gemm().
do_is_supported()
bool do_is_supported (const GemmArgs & args, const OutputStage & os) const inline
Definition at line 47 of file gemm_implementation.hpp.
{
     // Check supplied is_supported() function first.
         if (is_supported != nullptr && !is_supported(args, os)) {
             return false;
         }
         // Check weight format is appropriate.
         if (args._fixed_format == false) {
             // Can't return a fixed format kernel if we weren't asked for one.
             return (kernel_weight_format == KernelWeightFormat::NON_FIXED);
         } else {
             // Fixed format kernel requested: if this is a non-fixed format kernel we can't use it.
             if (kernel_weight_format == KernelWeightFormat::NON_FIXED) {
                 return false;
             }
             // If there's no config, or the config says ANY then this one is OK.
             if (!args._cfg || args._cfg->weight_format == WeightFormat::ANY) {
                 return true;
             }
             // If we get here it means there is a config and it specifies a format.  Check it matches this kernel.
             // NOTE: this will execute SVE instructions if it's an SVE kernel, so it's important that is_supported()
             // was called above first.
             return (args._cfg->weight_format == get_weight_format(kernel_weight_format, sizeof(Top)));
         }
     }
References arm_gemm::ANY, GemmTuner::args, arm_gemm::get_weight_format(), GemmImplementation< Top, Tret, OutputStage >::is_supported, GemmImplementation< Top, Tret, OutputStage >::kernel_weight_format, and arm_gemm::NON_FIXED.
operator=()
GemmImplementation& operator= (const GemmImplementation< Top, Tret, OutputStage > &) default
with_estimate()
static GemmImplementation with_estimate (GemmMethod m, const char * n, std::function< bool(const GemmArgs &, const OutputStage &)> is_supported, std::function< uint64_t(const GemmArgs &, const OutputStage &)> cycle_estimate, std::function< GemmCommon< Top, Tret > *(const GemmArgs &, const OutputStage &)> instantiate) inline static
Definition at line 87 of file gemm_implementation.hpp.
{
         GemmImplementation impl(m,n);
         impl.is_supported=is_supported;
         impl.cycle_estimate=cycle_estimate;
         impl.instantiate=instantiate;
         return impl;
     }
References GemmImplementation< Top, Tret, OutputStage >::cycle_estimate, GemmImplementation< Top, Tret, OutputStage >::instantiate, GemmImplementation< Top, Tret, OutputStage >::is_supported, arm_compute::test::validation::m, and arm_compute::test::validation::n.
Field Documentation
cycle_estimate
std::function<uint64_t(const GemmArgs &, const OutputStage &)> cycle_estimate = {}
Definition at line 44 of file gemm_implementation.hpp.
Referenced by GemmImplementation< Top, Tret, OutputStage >::do_cycle_estimate(), GemmImplementation< Top, Tret, Nothing >::do_cycle_estimate(), GemmImplementation< Top, Tret, OutputStage >::with_estimate(), and GemmImplementation< Top, Tret, Nothing >::with_estimate().
instantiate
std::function<GemmCommon<Top, Tret> *(const GemmArgs &, const OutputStage &)> instantiate = {}
Definition at line 45 of file gemm_implementation.hpp.
Referenced by GemmImplementation< Top, Tret, OutputStage >::do_instantiate(), GemmImplementation< Top, Tret, Nothing >::do_instantiate(), GemmImplementation< Top, Tret, OutputStage >::with_estimate(), and GemmImplementation< Top, Tret, Nothing >::with_estimate().
is_supported
std::function<bool(const GemmArgs &, const OutputStage &)> is_supported = {}
Definition at line 43 of file gemm_implementation.hpp.
Referenced by GemmImplementation< Top, Tret, OutputStage >::do_is_supported(), GemmImplementation< Top, Tret, Nothing >::do_is_supported(), GemmImplementation< Top, Tret, OutputStage >::with_estimate(), and GemmImplementation< Top, Tret, Nothing >::with_estimate().
kernel_weight_format
const KernelWeightFormat kernel_weight_format = KernelWeightFormat::NON_FIXED
Definition at line 42 of file gemm_implementation.hpp.
Referenced by GemmImplementation< Top, Tret, OutputStage >::do_is_supported(), and GemmImplementation< Top, Tret, Nothing >::do_is_supported().
method
const GemmMethod method
Definition at line 40 of file gemm_implementation.hpp.
Referenced by arm_gemm::find_implementation(), arm_gemm::get_compatible_kernels(), and arm_gemm::get_gemm_method().
name
const char* name
Definition at line 41 of file gemm_implementation.hpp.
Referenced by arm_gemm::get_gemm_method().
The documentation for this struct was generated from the following file:
src/core/NEON/kernels/arm_gemm/gemm_implementation.hpp