Compute Library: GpuWorkloadArgument Class Reference
GpuWorkloadArgument Class Reference
Describes all the info related to a workload argument (tensor) in order to:
#include <GpuWorkloadSourceCode.h>
Public Member Functions
GpuWorkloadArgument ()=default
Default constructor.
GpuWorkloadArgument (const ITensorInfo &tensor_info, const MemoryDescriptor &mem_desc, const GpuKernelArgumentList &kernel_args)
Constructor.
ITensorInfo::Id id () const
Get tensor id within workload.
ITensorInfo * tensor_info ()
Get ITensorInfo of the argument.
const ITensorInfo * tensor_info () const
Get ITensorInfo of the argument.
MemoryDescriptor * memory_descriptor ()
Get MemoryDescriptor of the argument.
const MemoryDescriptor * memory_descriptor () const
Get MemoryDescriptor of the argument.
GpuKernelArgumentList * kernel_argument_list ()
Get GpuKernelArgumentList of the workload tensor.
const GpuKernelArgumentList * kernel_argument_list () const
Get GpuKernelArgumentList of the workload tensor.
bool has_valid_id () const
Check if the workload argument has valid id.
Detailed Description
Describes all the info related to a workload argument (tensor) in order to:
be used by runtime to configure gpu kernel argument
be used by memory managers to allocate required memory
Definition at line 79 of file GpuWorkloadSourceCode.h.
Constructor & Destructor Documentation
GpuWorkloadArgument() [1/2]
GpuWorkloadArgument () default
Default constructor.
GpuWorkloadArgument() [2/2]
GpuWorkloadArgument (const ITensorInfo & tensor_info, const MemoryDescriptor & mem_desc, const GpuKernelArgumentList & kernel_args) inline
Constructor.
Parameters
[in] tensor_info ITensorInfo of the workload argument
[in] mem_desc MemoryDescriptor of the workload argument
[in] kernel_args GpuKernelArgumentList of the workload argument
Definition at line 90 of file GpuWorkloadSourceCode.h.
         : _tensor_info{tensor_info}, _mem_desc{mem_desc}, _kernel_args{kernel_args}
     {
     }
References GpuWorkloadArgument::tensor_info().
Member Function Documentation
has_valid_id()
bool has_valid_id () const inline
Check if the workload argument has valid id.
Returns
true If has valid id
false Otherwise
Definition at line 136 of file GpuWorkloadSourceCode.h.
     {
         return _tensor_info.has_valid_id();
     }
References ITensorInfo::has_valid_id().
id()
ITensorInfo::Id id () const inline
Get tensor id within workload.
Definition at line 97 of file GpuWorkloadSourceCode.h.
     {
         return _tensor_info.id();
     }
References TensorInfo::id().
kernel_argument_list() [1/2]
GpuKernelArgumentList* kernel_argument_list () inline
Get GpuKernelArgumentList of the workload tensor.
Definition at line 122 of file GpuWorkloadSourceCode.h.
     {
         return &_kernel_args;
     }
kernel_argument_list() [2/2]
const GpuKernelArgumentList* kernel_argument_list () const inline
Get GpuKernelArgumentList of the workload tensor.
Definition at line 127 of file GpuWorkloadSourceCode.h.
     {
         return &_kernel_args;
     }
memory_descriptor() [1/2]
MemoryDescriptor* memory_descriptor () inline
Get MemoryDescriptor of the argument.
Definition at line 112 of file GpuWorkloadSourceCode.h.
     {
         return &_mem_desc;
     }
memory_descriptor() [2/2]
const MemoryDescriptor* memory_descriptor () const inline
Get MemoryDescriptor of the argument.
Definition at line 117 of file GpuWorkloadSourceCode.h.
     {
         return &_mem_desc;
     }
tensor_info() [1/2]
ITensorInfo* tensor_info () inline
Get ITensorInfo of the argument.
Definition at line 102 of file GpuWorkloadSourceCode.h.
     {
         return &_tensor_info;
     }
Referenced by GpuWorkloadArgument::GpuWorkloadArgument().
tensor_info() [2/2]
const ITensorInfo* tensor_info () const inline
Get ITensorInfo of the argument.
Definition at line 107 of file GpuWorkloadSourceCode.h.
     {
         return &_tensor_info;
     }
The documentation for this class was generated from the following file:
src/dynamic_fusion/sketch/gpu/GpuWorkloadSourceCode.h