Compute Library: QuantizationInfo Class Reference
QuantizationInfo Class Reference
Quantization information.
#include <QuantizationInfo.h>
Public Member Functions
QuantizationInfo () noexcept
Default constructor.
QuantizationInfo (float scale)
Construct quantization info.
QuantizationInfo (float scale, int offset, bool is_dynamic=false)
Construct quantization info.
QuantizationInfo (std::vector< float > scale)
Construct quantization info.
QuantizationInfo (std::vector< float > scale, std::vector< int32_t > offset, bool is_dynamic=false)
Construct quantization info.
const std::vector< float > & scale () const
Scale vector accessor.
const std::vector< int32_t > & offset () const
Offset vector accessor.
bool is_dynamic () const
is_dynamic accessor
bool empty () const
Indicates whether this QuantizationInfo has valid settings or not.
UniformQuantizationInfo uniform () const
Return per layer quantization info.
Detailed Description
Quantization information.
Definition at line 67 of file QuantizationInfo.h.
Constructor & Destructor Documentation
QuantizationInfo() [1/5]
QuantizationInfo () inline noexcept
Default constructor.
Definition at line 71 of file QuantizationInfo.h.
                                 : _scale(), _offset()
     {
     }
QuantizationInfo() [2/5]
QuantizationInfo (float scale) inline
Construct quantization info.
Note
Used for symmetric quantization
Parameters
[in] scale Scale.
Definition at line 80 of file QuantizationInfo.h.
                                   : _scale(1, scale), _offset()
     {
     }
QuantizationInfo() [3/5]
QuantizationInfo (float scale, int offset, bool is_dynamic = false) inline
Construct quantization info.
Note
Used for asymmetric quantization
Parameters
[in] scale Scale.
[in] offset Offset.
[in] is_dynamic Whether this QuantizationInfo is dynamic, i.e. the scale and offset may change.
Definition at line 91 of file QuantizationInfo.h.
         : _scale(1, scale), _offset(1, offset), _is_dynamic(is_dynamic)
     {
     }
QuantizationInfo() [4/5]
QuantizationInfo (std::vector< float > scale) inline
Construct quantization info.
Note
Used for symmetric per channel quantization
Parameters
[in] scale Scale.
Definition at line 101 of file QuantizationInfo.h.
                                              : _scale(scale), _offset()
     {
     }
QuantizationInfo() [5/5]
QuantizationInfo (std::vector< float > scale, std::vector< int32_t > offset, bool is_dynamic = false) inline
Construct quantization info.
Note
Used for asymmetric per channel quantization
Parameters
[in] scale Scale.
[in] offset Offset.
[in] is_dynamic Whether this QuantizationInfo is dynamic, i.e. the scale and offset may change.
Definition at line 112 of file QuantizationInfo.h.
         : _scale(scale), _offset(offset), _is_dynamic(is_dynamic)
     {
     }
Member Function Documentation
empty()
bool empty () const inline
Indicates whether this QuantizationInfo has valid settings or not.
Returns
True if the this has invalid settings.
Definition at line 144 of file QuantizationInfo.h.
     {
         return _scale.empty() && _offset.empty();
     }
Referenced by arm_compute::test::validation::reference::activation_layer< int16_t >(), arm_compute::test::validation::reference::activation_layer< int8_t >(), arm_compute::test::validation::reference::activation_layer< uint8_t >(), GraphBuilder::add_convolution_node(), GraphBuilder::add_depthwise_convolution_node(), GraphBuilder::add_detection_post_process_node(), FullyConnectedLayerNode::compute_output_descriptor(), FullyConnectedLayerNode::compute_weights_descriptor(), ActivationLayerNode::configure_output(), DeconvolutionLayerNode::configure_output(), ArgMinMaxLayerNode::configure_output(), EltwiseLayerNode::configure_output(), ConcatenateLayerNode::configure_output(), DepthwiseConvolutionLayerNode::configure_output(), ConvolutionLayerNode::configure_output(), and UnaryEltwiseLayerNode::configure_output().
is_dynamic()
bool is_dynamic () const inline
is_dynamic accessor
Returns
If true, the scale and offset may change, so operators will need to read on every run
Definition at line 136 of file QuantizationInfo.h.
     {
         return _is_dynamic;
     }
Referenced by CpuGemmLowpMatrixMultiplyCore::configure(), invert_qinfo_offset(), CpuGemmLowpMatrixMultiplyCore::run(), and CpuGemmLowpMatrixMultiplyCore::validate().
offset()
const std::vector<int32_t>& offset () const inline
Offset vector accessor.
Returns
A reference to quantization offset metadata
Definition at line 128 of file QuantizationInfo.h.
     {
         return _offset;
     }
Referenced by ClDequantizeKernel::configure(), ClQuantizeKernel::configure(), ClScaleKernel::configure(), CLComputeAllAnchorsKernel::configure(), CLNormalizePlanarYUVLayerKernel::configure(), CLRangeKernel::configure(), Qasymm8QuantizationHelper< QUANTIZED_TYPE >::dequantize(), arm_compute::dequantize_qasymm16(), arm_compute::dequantize_s32(), dynamic_qinfo(), invert_qinfo_offset(), main(), arm_compute::operator<<(), arm_compute::operator==(), print_quantization_info(), Qasymm8QuantizationHelper< QUANTIZED_TYPE >::quantize(), arm_compute::quantize_qasymm16(), and arm_compute::test::validation::TEST_CASE().
scale()
const std::vector<float>& scale () const inline
Scale vector accessor.
Returns
A reference to quantization scale metadata
Definition at line 120 of file QuantizationInfo.h.
     {
         return _scale;
     }
Referenced by arm_compute::quantization::calculate_quantized_multipliers(), arm_compute::cpu::compute_all_anchors_qasymm16(), arm_compute::quantization::compute_quantized_multipliers_and_shifts(), ClDequantizeKernel::configure(), ClQuantizeKernel::configure(), ClScaleKernel::configure(), CLComputeAllAnchorsKernel::configure(), CLNormalizePlanarYUVLayerKernel::configure(), CLRangeKernel::configure(), Qasymm8QuantizationHelper< QUANTIZED_TYPE >::dequantize(), arm_compute::dequantize_qasymm16(), arm_compute::dequantize_qsymm16(), arm_compute::dequantize_qsymm8(), arm_compute::dequantize_s32(), dynamic_qinfo(), invert_qinfo_offset(), main(), arm_compute::operator<<(), arm_compute::operator==(), print_quantization_info(), Qasymm8QuantizationHelper< QUANTIZED_TYPE >::quantize(), arm_compute::quantize_qasymm16(), arm_compute::quantize_qsymm16(), arm_compute::quantize_qsymm8_per_channel(), arm_compute::cpu::run_depthwise_quanitized8bit(), arm_compute::test::validation::TEST_CASE(), and CpuDepthwiseConv2dAssemblyWrapperKernel::validate().
uniform()
UniformQuantizationInfo uniform () const inline
Return per layer quantization info.
Returns
Uniform quantization information in case of empty information zero is returned in the respective fields
Definition at line 152 of file QuantizationInfo.h.
     {
         UniformQuantizationInfo uqinfo;
         uqinfo.scale  = _scale.empty() ? 0 : _scale[0];
         uqinfo.offset = _offset.empty() ? 0 : _offset[0];
         return uqinfo;
     }
References UniformQuantizationInfo::offset, and UniformQuantizationInfo::scale.
Referenced by arm_compute::cpu::add_qasymm8_signed_sve2(), arm_compute::cpu::add_qasymm8_sve2(), arm_compute::cpu::add_qsymm16_neon(), arm_compute::cpu::add_qsymm16_sve2(), arm_compute::cpu::add_sub_q8_neon_fixedpoint_possible(), arm_compute::cpu::add_sub_qasymm8_neon(), arm_compute::cpu::add_sub_qasymm8_signed_neon(), arm_compute::cpu::avg_poolingMxNxD_q8_neon_ndhwc(), arm_compute::cpu::bounding_box_transform_qsymm16(), arm_compute::cpu::compute_all_anchors_qasymm16(), arm_compute::quantization::compute_quantized_multipliers_and_shifts(), ClTransposedConvolutionKernel::configure(), ClMatMulLowpNativeMMULKernel::configure(), ClWidthConcatenate2TensorsKernel::configure(), ClWidthConcatenate4TensorsKernel::configure(), ClMatMulLowpNativeKernel::configure(), NEQLSTMLayerNormalizationKernel::configure(), CLComputeAllAnchorsKernel::configure(), CLQLSTMLayerNormalizationKernel::configure(), CLComparisonKernel::configure(), CLRangeKernel::configure(), ClDirectConv2dKernel::configure(), ClDirectConv3dKernel::configure(), ClMulKernel::configure(), CLDepthwiseConvolutionLayerNativeKernel::configure(), CLBoundingBoxTransformKernel::configure(), CLROIPoolingLayerKernel::configure(), CLROIAlignLayerKernel::configure(), ClGemmLowpMatrixMultiplyCore::configure(), NELSTMLayerQuantized::configure(), CpuGemmLowpMatrixMultiplyCore::configure(), CLGEMMDeconvolutionLayer::configure(), NEQLSTMLayer::configure(), CLLSTMLayerQuantized::configure(), CLQLSTMLayer::configure(), arm_compute::test::validation::convert_to_asymmetric(), arm_compute::test::validation::convert_to_symmetric(), Qasymm8QuantizationHelper< QUANTIZED_TYPE >::dequantize(), arm_compute::dequantize_qasymm16(), arm_compute::dequantize_qsymm16(), arm_compute::dequantize_s32(), arm_compute::cpu::directconv3d_quantized_neon_ndhwc(), arm_compute::cpu::elementwise_arithmetic_quantized_op(), arm_compute::cpu::elementwise_comp_quantized_signed(), arm_compute::cpu::elementwise_comparison_quantized_op(), arm_compute::cpu::elementwise_op< int8_t >(), arm_compute::cpu::elementwise_op< uint8_t >(), arm_compute::cpu::elementwise_op_quantized(), arm_compute::cpu::elementwise_op_quantized_signed(), arm_compute::quantization::get_quantized_asymmetric_output_min_max(), arm_compute::test::validation::get_quantized_bounds(), arm_compute::test::validation::get_quantized_qasymm8_signed_bounds(), main(), arm_compute::cpu::max_poolingMxNxD_q8_neon_ndhwc(), arm_compute::cpu::neon_qasymm8_meanstddevnorm(), arm_compute::cpu::neon_softmax_non_x_quantized(), arm_compute::cpu::neon_softmax_x_quantized(), arm_compute::operator<<(), arm_compute::cpu::poolingMxN_q8_neon_nhwc(), arm_compute::test::validation::reference::quantization_layer(), Qasymm8QuantizationHelper< QUANTIZED_TYPE >::quantize(), arm_compute::quantize_qasymm16(), arm_compute::quantize_qsymm16(), arm_compute::quantize_qsymm8(), arm_compute::cpu::roi_align_1x1_qasymm8(), CPPUpsampleKernel::run(), CpuGemmLowpMatrixMultiplyCore::run(), arm_compute::cpu::sub_qsymm16_neon(), arm_compute::test::validation::suggest_mac_dst_q_info_and_bias(), arm_compute::cpu::sve2_softmax_logits_1d_quantized(), ClGemmLowpMatrixMultiplyCore::validate(), NEGenerateProposalsLayer::validate(), CpuGemmLowpMatrixMultiplyCore::validate(), NELSTMLayerQuantized::validate(), CLGenerateProposalsLayer::validate(), CLLSTMLayerQuantized::validate(), NEQLSTMLayer::validate(), arm_compute::validate(), and CLQLSTMLayer::validate().
The documentation for this class was generated from the following file:
arm_compute/core/QuantizationInfo.h