Compute Library: GemmCommon< To, Tr > Class Template Reference
GemmCommon< To, Tr > Class Template Reference
#include <gemm_common.hpp>
Public Member Functions
virtual void set_arrays (const To *A, const int lda, const int A_batch_stride, const int A_multi_stride, const To *B, const int ldb, const int B_multi_stride, Tr *C, const int ldc, const int C_batch_stride, const int C_multi_stride, const Tr *bias, const int bias_multi_stride)
void set_arrays_generic (const void *A, const int lda, const int A_batch_stride, const int A_multi_stride, const void *B, const int ldb, const int B_multi_stride, void *C, const int ldc, const int C_batch_stride, const int C_multi_stride, const void *bias, const int bias_multi_stride) override
virtual void requantize_bias (void *, const To *, const int, const int)
virtual void pretranspose_B_array (void *, const To *, const int, const int, bool)
void pretranspose_B_array_generic (void *out, const void *in, const int row_stride, const int multi_stride, bool transposed) override
virtual void pretranspose_B_array_part (void *out, const To *in, const int row_stride, const int multi_stride, bool transposed, size_t, size_t)
void pretranspose_B_array_part_generic (void *out, const void *in, const int row_stride, const int multi_stride, bool transposed, size_t start, size_t end) override
virtual void set_indirect_parameters (size_t, const To *const *const *)
void set_indirect_parameters_generic (size_t sz, const void *const *const *ptr) override
Public Member Functions inherited from IGemmCommon
virtual ndrange_t get_window_size () const =0
virtual void set_nthreads (int)
virtual bool supports_dynamic_scheduling () const
virtual void execute (const ndcoord_t &work_range, const ndcoord_t &thread_locator, int threadid)=0
Main execute member fucntion.
virtual size_t get_working_size () const
virtual void set_working_space (void *)
virtual bool B_is_pretransposed () const
virtual bool B_pretranspose_required () const
virtual bool B_pretranspose_supports_transpose () const
virtual size_t get_B_pretransposed_array_size () const
virtual size_t get_B_pretranspose_window_size () const
virtual void set_pretransposed_B_data (void *)
virtual void set_quantized_bias (const int32_t *, size_t)
virtual void set_convolution_parameters (ConvolutionParameters)
virtual void set_dequantize_scale (const float)
virtual GemmConfig get_config ()=0
virtual ~IGemmCommon ()
Detailed Description
template<typename To, typename Tr>
class arm_gemm::GemmCommon< To, Tr >
Definition at line 193 of file gemm_common.hpp.
Member Function Documentation
pretranspose_B_array()
virtual void pretranspose_B_array (void * , const To * , const int , const int , bool) inline virtual
Reimplemented in GemmInterleaved< strategy, To, Tr, OutputStage, MergeStep, FixedFormat, ForceThreadColumns, ForceFloatAccumulate >, GemmHybridIndirect< strategy, To, Tr, OutputStage, SeparateQuantize, FixedFormat >, GemmHybridQuantized< strategy, To, Tr >, GemmHybrid< strategy, To, Tr >, GemvPretransposed< strategy, To, Tr, OutputStage >, QuantizeWrapper< To, Tr, Tgemm >, and GemvBatched< To, Tr >.
Definition at line 269 of file gemm_common.hpp.
 {};
Referenced by GemmCommon< TypeInput, TypeOutput >::pretranspose_B_array_generic(), and GemmCommon< TypeInput, TypeOutput >::pretranspose_B_array_part().
pretranspose_B_array_generic()
void pretranspose_B_array_generic (void * out, const void * in, const int row_stride, const int multi_stride, bool transposed) inline override virtual
Implements IGemmCommon.
Definition at line 272 of file gemm_common.hpp.
     {
         pretranspose_B_array(out, static_cast<const To *>(in), row_stride, multi_stride, transposed);
     }
pretranspose_B_array_part()
virtual void pretranspose_B_array_part (void * out, const To * in, const int row_stride, const int multi_stride, bool transposed, size_t , size_t) inline virtual
Reimplemented in GemmInterleaved< strategy, To, Tr, OutputStage, MergeStep, FixedFormat, ForceThreadColumns, ForceFloatAccumulate >, and GemmHybridIndirect< strategy, To, Tr, OutputStage, SeparateQuantize, FixedFormat >.
Definition at line 282 of file gemm_common.hpp.
     {
         pretranspose_B_array(out, in, row_stride, multi_stride, transposed);
     };
Referenced by GemmCommon< TypeInput, TypeOutput >::pretranspose_B_array_part_generic().
pretranspose_B_array_part_generic()
void pretranspose_B_array_part_generic (void * out, const void * in, const int row_stride, const int multi_stride, bool transposed, size_t start, size_t end) inline override virtual
Implements IGemmCommon.
Definition at line 288 of file gemm_common.hpp.
     {
         pretranspose_B_array_part(out, static_cast<const To *>(in), row_stride, multi_stride, transposed, start, end);
     }
requantize_bias()
virtual void requantize_bias (void * , const To * , const int , const int) inline virtual
Reimplemented in GemmInterleaved< strategy, To, Tr, OutputStage, MergeStep, FixedFormat, ForceThreadColumns, ForceFloatAccumulate >, GemmHybridIndirect< strategy, To, Tr, OutputStage, SeparateQuantize, FixedFormat >, GemmHybridQuantized< strategy, To, Tr >, GemmHybridQuantizedInline< strategy, To, Tr >, GemvPretransposed< strategy, To, Tr, OutputStage >, and QuantizeWrapper< To, Tr, Tgemm >.
Definition at line 265 of file gemm_common.hpp.
 {};
set_arrays()
virtual void set_arrays (const To * A, const int lda, const int A_batch_stride, const int A_multi_stride, const To * B, const int ldb, const int B_multi_stride, Tr * C, const int ldc, const int C_batch_stride, const int C_multi_stride, const Tr * bias, const int bias_multi_stride) inline virtual
Reimplemented in GemvBatched< To, Tr >, and QuantizeWrapper< To, Tr, Tgemm >.
Definition at line 213 of file gemm_common.hpp.
     {
         _Aptr              = A;
         _lda               = lda;
         _A_batch_stride    = A_batch_stride;
         _A_multi_stride    = A_multi_stride;
         _Bptr              = B;
         _ldb               = ldb;
         _B_multi_stride    = B_multi_stride;
         _Cptr              = C;
         _ldc               = ldc;
         _C_batch_stride    = C_batch_stride;
         _C_multi_stride    = C_multi_stride;
         _bias              = bias;
         _bias_multi_stride = bias_multi_stride;
     }
Referenced by QuantizeWrapper< To, Tr, Tgemm >::set_arrays(), and GemmCommon< TypeInput, TypeOutput >::set_arrays_generic().
set_arrays_generic()
void set_arrays_generic (const void * A, const int lda, const int A_batch_stride, const int A_multi_stride, const void * B, const int ldb, const int B_multi_stride, void * C, const int ldc, const int C_batch_stride, const int C_multi_stride, const void * bias, const int bias_multi_stride) inline override virtual
Implements IGemmCommon.
Definition at line 243 of file gemm_common.hpp.
     {
         set_arrays(static_cast<const To *>(A), lda, A_batch_stride, A_multi_stride, static_cast<const To *>(B), ldb,
                    B_multi_stride, static_cast<Tr *>(C), ldc, C_batch_stride, C_multi_stride,
                    static_cast<const Tr *>(bias), bias_multi_stride);
     }
set_indirect_parameters()
virtual void set_indirect_parameters (size_t , const To *const *const *) inline virtual
Reimplemented in GemmInterleaved< strategy, To, Tr, OutputStage, MergeStep, FixedFormat, ForceThreadColumns, ForceFloatAccumulate >, and GemmHybridIndirect< strategy, To, Tr, OutputStage, SeparateQuantize, FixedFormat >.
Definition at line 300 of file gemm_common.hpp.
     {
     }
Referenced by GemmCommon< TypeInput, TypeOutput >::set_indirect_parameters_generic().
set_indirect_parameters_generic()
void set_indirect_parameters_generic (size_t sz, const void *const *const * ptr) inline override virtual
Reimplemented from IGemmCommon.
Definition at line 304 of file gemm_common.hpp.
     {
         set_indirect_parameters(sz, reinterpret_cast<const To *const *const *>(ptr));
     }
The documentation for this class was generated from the following file:
src/cpu/kernels/assembly/gemm_common.hpp