Compute Library: PoolingLayerDataObject Class Reference
PoolingLayerDataObject Class Reference
#include <PoolingLayerDataset.h>
Public Member Functions
operator std::string () const
Data Fields
TensorShape src_shape
TensorShape dst_shape
PoolingLayerInfo info
Friends
std::ostream & operator<< (std::ostream &s, const PoolingLayerDataObject &obj)
Detailed Description
Definition at line 43 of file PoolingLayerDataset.h.
Member Function Documentation
operator std::string () const inline
Definition at line 46 of file PoolingLayerDataset.h.
References PoolingLayerDataObject::info, PoolingLayerInfo::pad_stride_info(), PoolingLayerInfo::pool_size(), PoolingLayerInfo::pool_type(), and PoolingLayerDataObject::src_shape.
     {
         std::stringstream ss;
         ss << "PoolingLayer";
         ss << "_I" << src_shape;
         ss << "_S_" << info.pool_size();
         ss << "_F_" << info.pool_type();
         ss << "_PS" << info.pad_stride_info();
         return ss.str();
     }
Friends And Related Function Documentation
std::ostream& operator<< (std::ostream & s, const PoolingLayerDataObject & obj) friend
Definition at line 57 of file PoolingLayerDataset.h.
     {
         s << static_cast<std::string>(obj);
         return s;
     }
Field Documentation
TensorShape dst_shape
Definition at line 65 of file PoolingLayerDataset.h.
Referenced by PoolingLayer< DataSet, TensorType, Accessor, Function, dt >::SetUp().
PoolingLayerInfo info
Definition at line 66 of file PoolingLayerDataset.h.
Referenced by PoolingLayerDataObject::operator std::string(), and PoolingLayer< DataSet, TensorType, Accessor, Function, dt >::SetUp().
TensorShape src_shape
Definition at line 64 of file PoolingLayerDataset.h.
Referenced by PoolingLayerDataObject::operator std::string(), and PoolingLayer< DataSet, TensorType, Accessor, Function, dt >::SetUp().
The documentation for this class was generated from the following file:
tests/dataset/PoolingLayerDataset.h