Compute Library: TensorFactory Class Reference
TensorFactory Class Reference
#include <TensorFactory.h>
Static Public Member Functions
template<typename R >
static TensorVariant get_tensor (R &&raw)
Detailed Description
Definition at line 54 of file TensorFactory.h.
Member Function Documentation
static TensorVariant get_tensor (R && raw) inline static
Definition at line 58 of file TensorFactory.h.
References ARM_COMPUTE_ERROR, arm_compute::F16, arm_compute::F32, arm_compute::QS8, arm_compute::S16, arm_compute::S32, arm_compute::S8, arm_compute::U16, arm_compute::U32, and arm_compute::U8.
Referenced by ReferenceCPP::absolute_difference(), ReferenceCPP::activation_layer(), ReferenceCPP::arithmetic_addition(), ReferenceCPP::arithmetic_subtraction(), ReferenceCPP::batch_normalization_layer(), ReferenceCPP::convolution_layer(), ReferenceCPP::depth_convert(), ReferenceCPP::fixed_point_operation(), ReferenceCPP::fixed_point_pixel_wise_multiplication(), ReferenceCPP::fully_connected_layer(), ReferenceCPP::gemm(), ReferenceCPP::normalization_layer(), ReferenceCPP::pixel_wise_multiplication(), ReferenceCPP::pooling_layer(), and ReferenceCPP::softmax_layer().
     {
         TensorVariant v;
         DataType      dt                   = raw.data_type();
         int           fixed_point_position = raw.fixed_point_position();
         auto          shape                = raw.shape();
         auto          data                 = raw.data();
         switch(dt)
         {
             case DataType::U8:
                 using value_type_u8 = typename match_const<R, uint8_t>::type;
                 v                   = Tensor<uint8_t>(shape, dt, fixed_point_position, reinterpret_cast<value_type_u8 *>(data));
                 break;
             case DataType::S8:
             case DataType::QS8:
                 using value_type_s8 = typename match_const<R, int8_t>::type;
                 v                   = Tensor<int8_t>(shape, dt, fixed_point_position, reinterpret_cast<value_type_s8 *>(data));
                 break;
             case DataType::U16:
                 using value_type_u16 = typename match_const<R, uint16_t>::type;
                 v                    = Tensor<uint16_t>(shape, dt, fixed_point_position, reinterpret_cast<value_type_u16 *>(data));
                 break;
             case DataType::S16:
                 using value_type_s16 = typename match_const<R, int16_t>::type;
                 v                    = Tensor<int16_t>(shape, dt, fixed_point_position, reinterpret_cast<value_type_s16 *>(data));
                 break;
             case DataType::U32:
                 using value_type_u32 = typename match_const<R, uint32_t>::type;
                 v                    = Tensor<uint32_t>(shape, dt, fixed_point_position, reinterpret_cast<value_type_u32 *>(data));
                 break;
             case DataType::S32:
                 using value_type_s32 = typename match_const<R, int32_t>::type;
                 v                    = Tensor<int32_t>(shape, dt, fixed_point_position, reinterpret_cast<value_type_s32 *>(data));
                 break;
 #ifdef ENABLE_FP16
             case DataType::F16:
                 using value_type_f16 = typename match_const<R, float16_t>::type;
                 v                    = Tensor<float16_t>(raw.shape(), dt, reinterpret_cast<value_type_f16 *>(raw.data()));
                 break;
 #endif
             case DataType::F32:
                 using value_type_f32 = typename match_const<R, float>::type;
                 v                    = Tensor<float>(shape, dt, fixed_point_position, reinterpret_cast<value_type_f32 *>(data));
                 break;
             default:
                 ARM_COMPUTE_ERROR("NOT SUPPORTED!");
         }
         return v;
     }
The documentation for this class was generated from the following file:
tests/validation/TensorFactory.h