Compute Library: ProgramOptions Class Reference
ProgramOptions Class Reference
Defines available commandline arguments and allows to parse them.
#include <ProgramOptions.h>
Public Member Functions
ProgramOptions ()
Defines available options.
bool wants_help () const
Signals if the –help flag has been passed on the commandline.
std::string get_help () const
Returns a string describing all available options.
void parse_commandline (int argc, char **argv)
Parses the given arguments and makes them available via get.
template<typename T >
bool get (const std::string &name, T &value) const
Sets value if it has been specified on the command line.
Detailed Description
Defines available commandline arguments and allows to parse them.
Definition at line 42 of file ProgramOptions.h.
Constructor & Destructor Documentation
ProgramOptions ()
Defines available options.
Definition at line 38 of file ProgramOptions.cpp.
 {
     boost::program_options::options_description generic("Generic options");
     generic.add_options()("help", "Print help message")("seed", boost::program_options::value<std::random_device::result_type>(), "Seed for the tensor library");
     _visible.add(generic);
     _hidden.add_options()("path", boost::program_options::value<std::string>(), "Path from where to load the asset/s");
     _positional.add("path", 1);
 }
Member Function Documentation
bool get (const std::string & name, T & value) const
Sets value if it has been specified on the command line.
Note
The type T has to match the type that has been specified for the command line option.
Parameters
[in] name Name of the option to query.
[out] value Variable to which the value will be assigned.
Returns
True if the value is assigned, false otherwise.
Definition at line 89 of file ProgramOptions.h.
Referenced by PerformanceUserConfiguration::PerformanceUserConfiguration(), and UserConfiguration::UserConfiguration().
 {
     if(_vm.count(name) != 0)
     {
         value = _vm[name].as<T>();
         return true;
     }
     return false;
 }
std::string get_help () const
Returns a string describing all available options.
Definition at line 60 of file ProgramOptions.cpp.
Referenced by init_unit_test(), and main().
 {
     std::stringstream help;
     help << _visible;
     return help.str();
 }
void parse_commandline (int argc, char ** argv)
Parses the given arguments and makes them available via get.
Parameters
[in] argc Number of command line arguments.
[in] argv Pointer to the command line arguments.
Definition at line 68 of file ProgramOptions.cpp.
Referenced by init_unit_test(), and main().
 {
     boost::program_options::options_description all;
     all.add(_visible).add(_hidden);
     boost::program_options::store(boost::program_options::command_line_parser(argc, argv)
                                   .options(all)
                                   .positional(_positional)
                                   .allow_unregistered()
                                   .run(),
                                   _vm);
     if(_vm.count("help") == 0 && _vm.count("path") == 0)
     {
         throw boost::program_options::required_option("PATH");
     }
     boost::program_options::notify(_vm);
 }
bool wants_help () const
Signals if the –help flag has been passed on the commandline.
Definition at line 55 of file ProgramOptions.cpp.
Referenced by init_unit_test(), and main().
 {
     return (_vm.count("help") != 0);
 }
The documentation for this class was generated from the following files:
tests/ProgramOptions.h
tests/ProgramOptions.cpp