Compute Library: NEAccessor Class Reference
NEAccessor Class Reference
Accessor implementation for Tensor objects.
#include <NEAccessor.h>
Public Member Functions
NEAccessor (Tensor &tensor)
Create an accessor for the given tensor.
NEAccessor (const NEAccessor &)=delete
NEAccessor & operator= (const NEAccessor &)=delete
NEAccessor (NEAccessor &&)=default
NEAccessor & operator= (NEAccessor &&)=default
TensorShape shape () const override
Shape of the tensor.
size_t element_size () const override
Size of each element in the tensor in bytes.
size_t size () const override
Total size of the tensor in bytes.
Format format () const override
Image format of the tensor.
DataType data_type () const override
Data type of the tensor.
int num_channels () const override
Number of channels of the tensor.
int num_elements () const override
Number of elements of the tensor.
int fixed_point_position () const override
Number of bits for the fractional part.
const void * operator() (const Coordinates &coord) const override
Read only access to the specified element.
void * operator() (const Coordinates &coord) override
Access to the specified element.
Public Member Functions inherited from IAccessor
virtual ~IAccessor ()=0
Pure virtual destructor.
Detailed Description
Accessor implementation for Tensor objects.
Definition at line 38 of file NEAccessor.h.
Constructor & Destructor Documentation
NEAccessor (Tensor & tensor) inline
Create an accessor for the given tensor.
Parameters
[in,out] tensor To be accessed tensor.
Definition at line 67 of file NEAccessor.h.
     : _tensor{ tensor }
 {
 }
NEAccessor (const NEAccessor &) delete
NEAccessor (NEAccessor &&) default
Member Function Documentation
DataType data_type () const inline override virtual
Data type of the tensor.
Implements IAccessor.
Definition at line 92 of file NEAccessor.h.
References ITensorInfo::data_type(), and Tensor::info().
 {
     return _tensor.info()->data_type();
 }
size_t element_size () const inline override virtual
Size of each element in the tensor in bytes.
Implements IAccessor.
Definition at line 77 of file NEAccessor.h.
References ITensorInfo::element_size(), and Tensor::info().
 {
     return _tensor.info()->element_size();
 }
int fixed_point_position () const inline override virtual
Number of bits for the fractional part.
Implements IAccessor.
Definition at line 107 of file NEAccessor.h.
References ITensorInfo::fixed_point_position(), and Tensor::info().
 {
     return _tensor.info()->fixed_point_position();
 }
Format format () const inline override virtual
Image format of the tensor.
Implements IAccessor.
Definition at line 87 of file NEAccessor.h.
References ITensorInfo::format(), and Tensor::info().
 {
     return _tensor.info()->format();
 }
int num_channels () const inline override virtual
Number of channels of the tensor.
Implements IAccessor.
Definition at line 97 of file NEAccessor.h.
References Tensor::info(), and ITensorInfo::num_channels().
 {
     return _tensor.info()->num_channels();
 }
int num_elements () const inline override virtual
Number of elements of the tensor.
Implements IAccessor.
Definition at line 102 of file NEAccessor.h.
References Tensor::info(), ITensorInfo::tensor_shape(), and TensorShape::total_size().
 {
     return _tensor.info()->tensor_shape().total_size();
 }
const void * operator() (const Coordinates & coord) const inline override virtual
Read only access to the specified element.
Parameters
[in] coord Coordinates of the desired element.
Returns
A pointer to the desired element.
Implements IAccessor.
Definition at line 112 of file NEAccessor.h.
References ITensor::ptr_to_element().
 {
     return _tensor.ptr_to_element(coord);
 }
void * operator() (const Coordinates & coord) inline override virtual
Access to the specified element.
Parameters
[in] coord Coordinates of the desired element.
Returns
A pointer to the desired element.
Implements IAccessor.
Definition at line 117 of file NEAccessor.h.
References ITensor::ptr_to_element().
 {
     return _tensor.ptr_to_element(coord);
 }
NEAccessor& operator= (const NEAccessor &) delete
NEAccessor& operator= (NEAccessor &&) default
TensorShape shape () const inline override virtual
Shape of the tensor.
Implements IAccessor.
Definition at line 72 of file NEAccessor.h.
References Tensor::info(), and ITensorInfo::tensor_shape().
 {
     return _tensor.info()->tensor_shape();
 }
size_t size () const inline override virtual
Total size of the tensor in bytes.
Implements IAccessor.
Definition at line 82 of file NEAccessor.h.
References Tensor::info(), and ITensorInfo::total_size().
 {
     return _tensor.info()->total_size();
 }
The documentation for this class was generated from the following file:
tests/NEON/NEAccessor.h