Compute Library: ReferenceCPP Class Reference
ReferenceCPP Class Reference final
C++ reference implementation.
#include <ReferenceCPP.h>
Static Public Member Functions
static void integral_image (const RawTensor &src, RawTensor &dst)
Function to compute the integral image of a tensor.
static void absolute_difference (const RawTensor &src1, const RawTensor &src2, RawTensor &dst)
Function to compute the absolute difference between two tensors.
static void accumulate (const RawTensor &src, RawTensor &dst)
Function to accumulate an input tensor into an output tensor.
static void accumulate_squared (const RawTensor &src, RawTensor &dst, uint32_t shift)
Function to accumulate a squared value from an input tensor to an output tensor.
static void accumulate_weighted (const RawTensor &src, RawTensor &dst, float alpha)
Function to accumulate a weighted value from an input tensor to an output tensor.
static void arithmetic_addition (const RawTensor &src1, const RawTensor &src2, RawTensor &dst, ConvertPolicy convert_policy)
Arithmetic addition of src1 and src2.
static void arithmetic_subtraction (const RawTensor &src1, const RawTensor &src2, RawTensor &dst, ConvertPolicy convert_policy)
Arithmetic subtraction of src2 from src1.
static void bitwise_and (const RawTensor &src1, const RawTensor &src2, RawTensor &dst)
Function to compute the bitwise and between two tensors.
static void bitwise_or (const RawTensor &src1, const RawTensor &src2, RawTensor &dst)
Function to compute the bitwise or between two tensors.
static void bitwise_xor (const RawTensor &src1, const RawTensor &src2, RawTensor &dst)
Function to compute the bitwise xor between two tensors.
static void bitwise_not (const RawTensor &src, RawTensor &dst)
Function to compute the bitwise not of a tensor.
static void box3x3 (const RawTensor &src, RawTensor &dst)
Function to compute 3-by-3 box filtered result tensor.
static void depth_convert (const RawTensor &src, RawTensor &dst, ConvertPolicy policy, uint32_t shift)
Depth conversion from src to dst.
static void gemm (const RawTensor &src1, const RawTensor &src2, const RawTensor &src3, RawTensor &dst, float alpha, float beta)
Compute GEMM function.
static void pixel_wise_multiplication (const RawTensor &src1, const RawTensor &src2, RawTensor &dst, float scale, ConvertPolicy convert_policy, RoundingPolicy rounding_policy)
Element-wise multiplication of src1, src2 and scale.
static void fixed_point_pixel_wise_multiplication (const RawTensor &src1, const RawTensor &src2, RawTensor &dst, float scale, ConvertPolicy convert_policy, RoundingPolicy rounding_policy)
Fixed-point Pixel-wise multiplication of src1 by src2.
static void threshold (const RawTensor &src, RawTensor &dst, uint8_t threshold, uint8_t false_value, uint8_t true_value, ThresholdType type, uint8_t upper)
Threshold ofsrc to dst.
static void activation_layer (const RawTensor &input, RawTensor &output, ActivationLayerInfo act_info)
Activation layer of src base on information from act_info.
static void batch_normalization_layer (const RawTensor &src, RawTensor &dst, const RawTensor &mean, const RawTensor &var, const RawTensor &beta, const RawTensor &gamma, float epsilon, int fixed_point_position=0)
Batch Normalization of src based on the information from norm_info.
static void convolution_layer (const RawTensor &src, const RawTensor &weights, const RawTensor &bias, RawTensor &dst, const PadStrideInfo &conv_info)
Convolution layer function.
static void fully_connected_layer (const RawTensor &src, const RawTensor &weights, const RawTensor &bias, RawTensor &dst)
Fully connected layer function.
static void normalization_layer (const RawTensor &src, RawTensor &dst, NormalizationLayerInfo norm_info)
Normalization of src based on the information from norm_info.
static void pooling_layer (const RawTensor &src, RawTensor &dst, PoolingLayerInfo pool_info, int fixed_point_position=0)
Pooling layer of src based on the information from norm_info.
static void softmax_layer (const RawTensor &src, RawTensor &dst)
Softmax Layer of src.
static void fixed_point_operation (const RawTensor &src, RawTensor &dst, FixedPointOp op)
Fixed point operations of src.
Static Public Member Functions inherited from Reference
static RawTensor compute_reference_integral_image (const TensorShape &shape)
Compute reference integral image.
static RawTensor compute_reference_absolute_difference (const TensorShape &shape, DataType dt_in0, DataType dt_in1, DataType dt_out)
Compute reference absolute difference.
static RawTensor compute_reference_accumulate (const TensorShape &shape)
Compute reference accumulate.
static RawTensor compute_reference_accumulate_squared (const TensorShape &shape, uint32_t shift)
Compute reference accumulate.
static RawTensor compute_reference_accumulate_weighted (const TensorShape &shape, float alpha)
Compute reference accumulate.
static RawTensor compute_reference_arithmetic_addition (const TensorShape &shape, DataType dt_in0, DataType dt_in1, DataType dt_out, ConvertPolicy convert_policy)
Compute reference arithmetic addition.
static RawTensor compute_reference_arithmetic_subtraction (const TensorShape &shape, DataType dt_in0, DataType dt_in1, DataType dt_out, ConvertPolicy convert_policy)
Compute reference arithmetic subtraction.
static RawTensor compute_reference_bitwise_and (const TensorShape &shape)
Compute reference bitwise and.
static RawTensor compute_reference_bitwise_or (const TensorShape &shape)
Compute reference bitwise or.
static RawTensor compute_reference_bitwise_xor (const TensorShape &shape)
Compute reference bitwise xor.
static RawTensor compute_reference_bitwise_not (const TensorShape &shape)
Compute reference bitwise not.
static RawTensor compute_reference_box3x3 (const TensorShape &shape)
Compute reference 3-by-3 box filter.
static RawTensor compute_reference_depth_convert (const TensorShape &shape, DataType dt_in, DataType dt_out, ConvertPolicy policy, uint32_t shift, uint32_t fixed_point_position)
Compute reference depth convert.
static RawTensor compute_reference_gemm (const TensorShape &src_shape1, const TensorShape &src_shape2, const TensorShape &src_shape3, const TensorShape &dst_shape, float alpha, float beta, DataType dt, int fixed_point_position=0)
Compute matrix multiply function.
static RawTensor compute_reference_pixel_wise_multiplication (const TensorShape &shape, DataType dt_in0, DataType dt_in1, DataType dt_out, float scale, ConvertPolicy convert_policy, RoundingPolicy rounding_policy)
Compute reference pixel-wise multiplication.
static RawTensor compute_reference_fixed_point_pixel_wise_multiplication (const TensorShape &shape, DataType dt_in0, DataType dt_in1, DataType dt_out, float scale, int fixed_point_position, ConvertPolicy convert_policy, RoundingPolicy rounding_policy)
Compute reference pixel-wise multiplication.
static RawTensor compute_reference_threshold (const TensorShape &shape, uint8_t threshold, uint8_t false_value, uint8_t true_value, ThresholdType type, uint8_t upper)
Compute reference threshold.
static RawTensor compute_reference_activation_layer (const TensorShape &shape, DataType dt, ActivationLayerInfo act_info, int fixed_point_position=0)
Compute reference activation layer.
static RawTensor compute_reference_batch_normalization_layer (const TensorShape &shape0, const TensorShape &shape1, DataType dt, float epsilon, int fixed_point_position=0)
Compute reference batch normalization layer.
static RawTensor compute_reference_convolution_layer (const TensorShape &input_shape, const TensorShape &weights_shape, const TensorShape &bias_shape, const TensorShape &output_shape, DataType dt, const PadStrideInfo &conv_info, int fixed_point_position)
Compute reference pixel-wise multiplication.
static RawTensor compute_reference_fully_connected_layer (const TensorShape &input_shape, const TensorShape &weights_shape, const TensorShape &bias_shape, const TensorShape &output_shape, DataType dt, bool transpose_weights, int fixed_point_position)
Compute reference for fully connected layer function.
static RawTensor compute_reference_normalization_layer (const TensorShape &shape, DataType dt, NormalizationLayerInfo norm_info, int fixed_point_position=0)
Compute reference normalization layer.
static RawTensor compute_reference_pooling_layer (const TensorShape &shape_in, const TensorShape &shape_out, DataType dt, PoolingLayerInfo pool_info, int fixed_point_position=0)
Compute reference pooling layer.
static RawTensor compute_reference_softmax_layer (const TensorShape &shape, DataType dt, int fixed_point_position=0)
Compute reference softmax layer.
static RawTensor compute_reference_fixed_point_operation (const TensorShape &shape, DataType dt_in, DataType dt_out, FixedPointOp op, int fixed_point_position)
Compute reference fixed point operation.
Detailed Description
C++ reference implementation.
Definition at line 42 of file ReferenceCPP.h.
Member Function Documentation
void absolute_difference (const RawTensor & src1, const RawTensor & src2, RawTensor & dst) static
Function to compute the absolute difference between two tensors.
Parameters
[in] src1 First tensor.
[in] src2 Second tensor.
[out] dst Result tensor.
Definition at line 52 of file ReferenceCPP.cpp.
References TensorFactory::get_tensor().
 {
     const TensorVariant s1 = TensorFactory::get_tensor(src1);
     const TensorVariant s2 = TensorFactory::get_tensor(src2);
     TensorVariant       d  = TensorFactory::get_tensor(dst);
     boost::apply_visitor(absolute_difference_visitor(), s1, s2, d);
 }
void accumulate (const RawTensor & src, RawTensor & dst) static
Function to accumulate an input tensor into an output tensor.
Parameters
[in] src Input tensor.
[in,out] dst Result tensor.
Definition at line 68 of file ReferenceCPP.cpp.
References arm_compute::test::validation::tensor_operations::accumulate(), ARM_COMPUTE_ERROR_ON, RawTensor::data(), RawTensor::data_type(), RawTensor::fixed_point_position(), arm_compute::S16, RawTensor::shape(), and arm_compute::U8.
 {
     ARM_COMPUTE_ERROR_ON(src.data_type() != DataType::U8 || dst.data_type() != DataType::S16);
     const Tensor<uint8_t> s(src.shape(), src.data_type(), src.fixed_point_position(), reinterpret_cast<const uint8_t *>(src.data()));
     Tensor<int16_t>       d(dst.shape(), dst.data_type(), dst.fixed_point_position(), reinterpret_cast<int16_t *>(dst.data()));
     tensor_operations::accumulate(s, d);
 }
void accumulate_squared (const RawTensor & src, RawTensor & dst, uint32_t shift) static
Function to accumulate a squared value from an input tensor to an output tensor.
Parameters
[in] src Input tensor.
[in,out] dst Result tensor.
[in] shift A uint32_t value within the range of [0, 15]
Definition at line 77 of file ReferenceCPP.cpp.
References arm_compute::test::validation::tensor_operations::accumulate_squared(), ARM_COMPUTE_ERROR_ON, RawTensor::data(), RawTensor::data_type(), RawTensor::fixed_point_position(), arm_compute::S16, RawTensor::shape(), and arm_compute::U8.
 {
     ARM_COMPUTE_ERROR_ON(src.data_type() != DataType::U8 || dst.data_type() != DataType::S16);
     const Tensor<uint8_t> s(src.shape(), src.data_type(), src.fixed_point_position(), reinterpret_cast<const uint8_t *>(src.data()));
     Tensor<int16_t>       d(dst.shape(), dst.data_type(), dst.fixed_point_position(), reinterpret_cast<int16_t *>(dst.data()));
     tensor_operations::accumulate_squared(s, d, shift);
 }
void accumulate_weighted (const RawTensor & src, RawTensor & dst, float alpha) static
Function to accumulate a weighted value from an input tensor to an output tensor.
Parameters
[in] src Input tensor.
[in,out] dst Result tensor.
[in] alpha A float value within the range of [0, 1]
Definition at line 86 of file ReferenceCPP.cpp.
References arm_compute::test::validation::tensor_operations::accumulate_weighted(), ARM_COMPUTE_ERROR_ON, RawTensor::data(), RawTensor::data_type(), RawTensor::fixed_point_position(), RawTensor::shape(), and arm_compute::U8.
 {
     ARM_COMPUTE_ERROR_ON(src.data_type() != DataType::U8 || dst.data_type() != DataType::U8);
     const Tensor<uint8_t> s(src.shape(), src.data_type(), src.fixed_point_position(), reinterpret_cast<const uint8_t *>(src.data()));
     Tensor<uint8_t>       d(dst.shape(), dst.data_type(), dst.fixed_point_position(), reinterpret_cast<uint8_t *>(dst.data()));
     tensor_operations::accumulate_weighted(s, d, alpha);
 }
void activation_layer (const RawTensor & input, RawTensor & output, ActivationLayerInfo act_info) static
Activation layer of src base on information from act_info.
Parameters
[in] input Input tensor.
[in] output Second tensor.
[out] act_info Activation layer information.
Definition at line 208 of file ReferenceCPP.cpp.
References TensorFactory::get_tensor().
 {
     const TensorVariant s = TensorFactory::get_tensor(input);
     TensorVariant       d = TensorFactory::get_tensor(output);
     boost::apply_visitor(tensor_visitors::activation_layer_visitor(s, act_info), d);
 }
void arithmetic_addition (const RawTensor & src1, const RawTensor & src2, RawTensor & dst, ConvertPolicy convert_policy) static
Arithmetic addition of src1 and src2.
Parameters
[in] src1 First tensor.
[in] src2 Second tensor.
[out] dst Result tensor.
[in] convert_policy Overflow policy.
Definition at line 95 of file ReferenceCPP.cpp.
References TensorFactory::get_tensor().
 {
     const TensorVariant s1 = TensorFactory::get_tensor(src1);
     const TensorVariant s2 = TensorFactory::get_tensor(src2);
     TensorVariant       d  = TensorFactory::get_tensor(dst);
     boost::apply_visitor(arithmetic_addition_visitor(convert_policy), s1, s2, d);
 }
void arithmetic_subtraction (const RawTensor & src1, const RawTensor & src2, RawTensor & dst, ConvertPolicy convert_policy) static
Arithmetic subtraction of src2 from src1.
Parameters
[in] src1 First tensor.
[in] src2 Second tensor.
[out] dst Result tensor.
[in] convert_policy Overflow policy.
Definition at line 104 of file ReferenceCPP.cpp.
References TensorFactory::get_tensor().
 {
     const TensorVariant s1 = TensorFactory::get_tensor(src1);
     const TensorVariant s2 = TensorFactory::get_tensor(src2);
     TensorVariant       d  = TensorFactory::get_tensor(dst);
     boost::apply_visitor(arithmetic_subtraction_visitor(convert_policy), s1, s2, d);
 }
void batch_normalization_layer (const RawTensor & src, RawTensor & dst, const RawTensor & mean, const RawTensor & var, const RawTensor & beta, const RawTensor & gamma, float epsilon, int fixed_point_position = 0) static
Batch Normalization of src based on the information from norm_info.
Parameters
[in] src Input tensor.
[out] dst Result tensor.
[out] mean Mean vector tensor.
[out] var Var vector tensor.
[out] beta Beta vector tensor.
[out] gamma Gamma vector tensor.
[in] epsilon Small value to avoid division with zero.
[in] fixed_point_position Fixed point position.
Definition at line 216 of file ReferenceCPP.cpp.
References TensorFactory::get_tensor().
 {
     const TensorVariant s = TensorFactory::get_tensor(src);
     TensorVariant       d = TensorFactory::get_tensor(dst);
     const TensorVariant m = TensorFactory::get_tensor(mean);
     const TensorVariant v = TensorFactory::get_tensor(var);
     const TensorVariant b = TensorFactory::get_tensor(beta);
     const TensorVariant g = TensorFactory::get_tensor(gamma);
     boost::apply_visitor(tensor_visitors::batch_normalization_layer_visitor(s, m, v, b, g, epsilon, fixed_point_position), d);
 }
void bitwise_and (const RawTensor & src1, const RawTensor & src2, RawTensor & dst) static
Function to compute the bitwise and between two tensors.
Parameters
[in] src1 First tensor.
[in] src2 Second tensor.
[out] dst Result tensor.
Definition at line 113 of file ReferenceCPP.cpp.
References ARM_COMPUTE_ERROR_ON, arm_compute::test::validation::tensor_operations::bitwise_and(), RawTensor::data(), RawTensor::data_type(), RawTensor::fixed_point_position(), RawTensor::shape(), and arm_compute::U8.
 {
     ARM_COMPUTE_ERROR_ON(src1.data_type() != DataType::U8 || src2.data_type() != DataType::U8 || dst.data_type() != DataType::U8);
     const Tensor<uint8_t> s1(src1.shape(), src1.data_type(), src1.fixed_point_position(), reinterpret_cast<const uint8_t *>(src1.data()));
     const Tensor<uint8_t> s2(src2.shape(), src2.data_type(), src2.fixed_point_position(), reinterpret_cast<const uint8_t *>(src2.data()));
     Tensor<uint8_t>       d(dst.shape(), dst.data_type(), dst.fixed_point_position(), reinterpret_cast<uint8_t *>(dst.data()));
     tensor_operations::bitwise_and(s1, s2, d);
 }
void bitwise_not (const RawTensor & src, RawTensor & dst) static
Function to compute the bitwise not of a tensor.
Parameters
[in] src Input tensor.
[out] dst Result tensor.
Definition at line 143 of file ReferenceCPP.cpp.
References ARM_COMPUTE_ERROR_ON, arm_compute::test::validation::tensor_operations::bitwise_not(), RawTensor::data(), RawTensor::data_type(), RawTensor::fixed_point_position(), RawTensor::shape(), and arm_compute::U8.
 {
     ARM_COMPUTE_ERROR_ON(src.data_type() != DataType::U8 || dst.data_type() != DataType::U8);
     const Tensor<uint8_t> s(src.shape(), src.data_type(), src.fixed_point_position(), reinterpret_cast<const uint8_t *>(src.data()));
     Tensor<uint8_t>       d(dst.shape(), dst.data_type(), dst.fixed_point_position(), reinterpret_cast<uint8_t *>(dst.data()));
     tensor_operations::bitwise_not(s, d);
 }
void bitwise_or (const RawTensor & src1, const RawTensor & src2, RawTensor & dst) static
Function to compute the bitwise or between two tensors.
Parameters
[in] src1 First tensor.
[in] src2 Second tensor.
[out] dst Result tensor.
Definition at line 123 of file ReferenceCPP.cpp.
References ARM_COMPUTE_ERROR_ON, arm_compute::test::validation::tensor_operations::bitwise_or(), RawTensor::data(), RawTensor::data_type(), RawTensor::fixed_point_position(), RawTensor::shape(), and arm_compute::U8.
 {
     ARM_COMPUTE_ERROR_ON(src1.data_type() != DataType::U8 || src2.data_type() != DataType::U8 || dst.data_type() != DataType::U8);
     const Tensor<uint8_t> s1(src1.shape(), src1.data_type(), src1.fixed_point_position(), reinterpret_cast<const uint8_t *>(src1.data()));
     const Tensor<uint8_t> s2(src2.shape(), src2.data_type(), src2.fixed_point_position(), reinterpret_cast<const uint8_t *>(src2.data()));
     Tensor<uint8_t>       d(dst.shape(), dst.data_type(), dst.fixed_point_position(), reinterpret_cast<uint8_t *>(dst.data()));
     tensor_operations::bitwise_or(s1, s2, d);
 }
void bitwise_xor (const RawTensor & src1, const RawTensor & src2, RawTensor & dst) static
Function to compute the bitwise xor between two tensors.
Parameters
[in] src1 First tensor.
[in] src2 Second tensor.
[out] dst Result tensor.
Definition at line 133 of file ReferenceCPP.cpp.
References ARM_COMPUTE_ERROR_ON, arm_compute::test::validation::tensor_operations::bitwise_xor(), RawTensor::data(), RawTensor::data_type(), RawTensor::fixed_point_position(), RawTensor::shape(), and arm_compute::U8.
 {
     ARM_COMPUTE_ERROR_ON(src1.data_type() != DataType::U8 || src2.data_type() != DataType::U8 || dst.data_type() != DataType::U8);
     const Tensor<uint8_t> s1(src1.shape(), src1.data_type(), src1.fixed_point_position(), reinterpret_cast<const uint8_t *>(src1.data()));
     const Tensor<uint8_t> s2(src2.shape(), src2.data_type(), src2.fixed_point_position(), reinterpret_cast<const uint8_t *>(src2.data()));
     Tensor<uint8_t>       d(dst.shape(), dst.data_type(), dst.fixed_point_position(), reinterpret_cast<uint8_t *>(dst.data()));
     tensor_operations::bitwise_xor(s1, s2, d);
 }
void box3x3 (const RawTensor & src, RawTensor & dst) static
Function to compute 3-by-3 box filtered result tensor.
Parameters
[in] src Input tensor.
[out] dst Result tensor.
Definition at line 152 of file ReferenceCPP.cpp.
References ARM_COMPUTE_ERROR_ON, arm_compute::test::validation::tensor_operations::box3x3(), RawTensor::data(), RawTensor::data_type(), RawTensor::fixed_point_position(), RawTensor::shape(), and arm_compute::U8.
 {
     ARM_COMPUTE_ERROR_ON(src.data_type() != DataType::U8 || dst.data_type() != DataType::U8);
     const Tensor<uint8_t> s(src.shape(), src.data_type(), src.fixed_point_position(), reinterpret_cast<const uint8_t *>(src.data()));
     Tensor<uint8_t>       d(dst.shape(), dst.data_type(), dst.fixed_point_position(), reinterpret_cast<uint8_t *>(dst.data()));
     tensor_operations::box3x3(s, d);
 }
void convolution_layer (const RawTensor & src, const RawTensor & weights, const RawTensor & bias, RawTensor & dst, const PadStrideInfo & conv_info) static
Convolution layer function.
Parameters
[in] src Input tensor.
[in] weights Weights tensor.
[in] bias Bias tensor.
[out] dst Result tensor.
[in] conv_info Pads and strides information for the convolution layer.
Definition at line 229 of file ReferenceCPP.cpp.
References TensorFactory::get_tensor().
 {
     const TensorVariant s = TensorFactory::get_tensor(src);
     const TensorVariant w = TensorFactory::get_tensor(weights);
     const TensorVariant b = TensorFactory::get_tensor(bias);
     TensorVariant       d = TensorFactory::get_tensor(dst);
     boost::apply_visitor(tensor_visitors::convolution_layer_visitor(s, w, b, conv_info), d);
 }
void depth_convert (const RawTensor & src, RawTensor & dst, ConvertPolicy policy, uint32_t shift) static
Depth conversion from src to dst.
Parameters
[in] src First tensor.
[out] dst Result tensor.
[in] policy Overflow policy.
[in] shift Value for down/up conversions.
Definition at line 161 of file ReferenceCPP.cpp.
References TensorFactory::get_tensor().
 {
     const TensorVariant s = TensorFactory::get_tensor(src);
     TensorVariant       d = TensorFactory::get_tensor(dst);
     boost::apply_visitor(tensor_visitors::depth_convert_visitor(policy, shift), s, d);
 }
void fixed_point_operation (const RawTensor & src, RawTensor & dst, FixedPointOp op) static
Fixed point operations of src.
Parameters
[in] src Input tensor.
[out] dst Result tensor.
[in] op Fixed point operation to perform.
Definition at line 273 of file ReferenceCPP.cpp.
References TensorFactory::get_tensor().
 {
     const TensorVariant s = TensorFactory::get_tensor(src);
     TensorVariant       d = TensorFactory::get_tensor(dst);
     boost::apply_visitor(tensor_visitors::fixed_point_operation_visitor(s, op), d);
 }
void fixed_point_pixel_wise_multiplication (const RawTensor & src1, const RawTensor & src2, RawTensor & dst, float scale, ConvertPolicy convert_policy, RoundingPolicy rounding_policy) static
Fixed-point Pixel-wise multiplication of src1 by src2.
Parameters
[in] src1 First tensor.
[in] src2 Second tensor.
[out] dst Result tensor.
[in] scale A non-negative float multiplied to each product.
[in] convert_policy Overflow policy.
[in] rounding_policy Rounding policy.
Definition at line 190 of file ReferenceCPP.cpp.
References TensorFactory::get_tensor().
 {
     const TensorVariant s1 = TensorFactory::get_tensor(src1);
     const TensorVariant s2 = TensorFactory::get_tensor(src2);
     TensorVariant       d  = TensorFactory::get_tensor(dst);
     boost::apply_visitor(tensor_visitors::fixed_point_pixel_wise_multiplication_visitor(s1, s2, scale, convert_policy, rounding_policy), d);
 }
void fully_connected_layer (const RawTensor & src, const RawTensor & weights, const RawTensor & bias, RawTensor & dst) static
Fully connected layer function.
Parameters
[in] src Input tensor
[in] weights Weights tensor.
[in] bias Bias tensor.
[out] dst Result tensor.
Definition at line 239 of file ReferenceCPP.cpp.
References TensorFactory::get_tensor().
 {
     const TensorVariant s = TensorFactory::get_tensor(src);
     const TensorVariant w = TensorFactory::get_tensor(weights);
     const TensorVariant b = TensorFactory::get_tensor(bias);
     TensorVariant       d = TensorFactory::get_tensor(dst);
     boost::apply_visitor(tensor_visitors::fully_connected_layer_visitor(s, w, b), d);
 }
void gemm (const RawTensor & src1, const RawTensor & src2, const RawTensor & src3, RawTensor & dst, float alpha, float beta) static
Compute GEMM function.
Parameters
[in] src1 First input tensor
[in] src2 Second input tensor
[in] src3 Third input tensor
[out] dst Output tensr
[in] alpha Weight of the matrix product
[in] beta Weight of the third matrix
Definition at line 169 of file ReferenceCPP.cpp.
References TensorFactory::get_tensor().
 {
     const TensorVariant s1 = TensorFactory::get_tensor(src1);
     const TensorVariant s2 = TensorFactory::get_tensor(src2);
     const TensorVariant s3 = TensorFactory::get_tensor(src3);
     TensorVariant       d  = TensorFactory::get_tensor(dst);
     boost::apply_visitor(tensor_visitors::gemm_visitor(s1, s2, s3, alpha, beta), d);
 }
void integral_image (const RawTensor & src, RawTensor & dst) static
Function to compute the integral image of a tensor.
Parameters
[in] src Input tensor.
[out] dst Result tensor.
Definition at line 60 of file ReferenceCPP.cpp.
References ARM_COMPUTE_ERROR_ON, RawTensor::data(), RawTensor::data_type(), RawTensor::fixed_point_position(), arm_compute::test::validation::tensor_operations::integral_image(), RawTensor::shape(), arm_compute::U32, and arm_compute::U8.
 {
     ARM_COMPUTE_ERROR_ON(src.data_type() != DataType::U8 || dst.data_type() != DataType::U32);
     const Tensor<uint8_t> s(src.shape(), src.data_type(), src.fixed_point_position(), reinterpret_cast<const uint8_t *>(src.data()));
     Tensor<uint32_t>      d(dst.shape(), dst.data_type(), dst.fixed_point_position(), reinterpret_cast<uint32_t *>(dst.data()));
     tensor_operations::integral_image(s, d);
 }
void normalization_layer (const RawTensor & src, RawTensor & dst, NormalizationLayerInfo norm_info) static
Normalization of src based on the information from norm_info.
Parameters
[in] src Input tensor.
[out] dst Result tensor.
[in] norm_info Normalization Layer information.
Definition at line 249 of file ReferenceCPP.cpp.
References TensorFactory::get_tensor().
 {
     const TensorVariant s = TensorFactory::get_tensor(src);
     TensorVariant       d = TensorFactory::get_tensor(dst);
     boost::apply_visitor(tensor_visitors::normalization_layer_visitor(s, norm_info), d);
 }
void pixel_wise_multiplication (const RawTensor & src1, const RawTensor & src2, RawTensor & dst, float scale, ConvertPolicy convert_policy, RoundingPolicy rounding_policy) static
Element-wise multiplication of src1, src2 and scale.
Parameters
[in] src1 First tensor.
[in] src2 Second tensor.
[out] dst Result tensor.
[in] scale A non-negative float multiplied to each product.
[in] convert_policy Overflow policy.
[in] rounding_policy Rounding policy.
Definition at line 181 of file ReferenceCPP.cpp.
References TensorFactory::get_tensor().
 {
     const TensorVariant s1 = TensorFactory::get_tensor(src1);
     const TensorVariant s2 = TensorFactory::get_tensor(src2);
     TensorVariant       d  = TensorFactory::get_tensor(dst);
     boost::apply_visitor(pixel_wise_multiplication_visitor(scale, convert_policy, rounding_policy), s1, s2, d);
 }
void pooling_layer (const RawTensor & src, RawTensor & dst, PoolingLayerInfo pool_info, int fixed_point_position = 0) static
Pooling layer of src based on the information from norm_info.
Parameters
[in] src Input tensor.
[out] dst Result tensor.
[in] pool_info Pooling Layer information.
[in] fixed_point_position Fixed point position. (Optional)
Definition at line 257 of file ReferenceCPP.cpp.
References TensorFactory::get_tensor().
 {
     const TensorVariant s = TensorFactory::get_tensor(src);
     TensorVariant       d = TensorFactory::get_tensor(dst);
     boost::apply_visitor(tensor_visitors::pooling_layer_visitor(s, pool_info, fixed_point_position), d);
 }
void softmax_layer (const RawTensor & src, RawTensor & dst) static
Softmax Layer of src.
Parameters
[in] src Input tensor.
[out] dst Result tensor.
Definition at line 265 of file ReferenceCPP.cpp.
References TensorFactory::get_tensor().
 {
     const TensorVariant s = TensorFactory::get_tensor(src);
     TensorVariant       d = TensorFactory::get_tensor(dst);
     boost::apply_visitor(tensor_visitors::softmax_layer_visitor(s), d);
 }
void threshold (const RawTensor & src, RawTensor & dst, uint8_t threshold, uint8_t false_value, uint8_t true_value, ThresholdType type, uint8_t upper) static
Threshold ofsrc to dst.
Parameters
[in] src First tensor.
[out] dst Result tensor.
[in] threshold Threshold. When the threhold type is RANGE, this is used as the lower threshold.
[in] false_value value to set when the condition is not respected.
[in] true_value value to set when the condition is respected.
[in] type Thresholding type. Either RANGE or BINARY.
[in] upper Upper threshold. Only used when the thresholding type is RANGE.
Definition at line 199 of file ReferenceCPP.cpp.
References ARM_COMPUTE_ERROR_ON, RawTensor::data(), RawTensor::data_type(), RawTensor::fixed_point_position(), RawTensor::shape(), arm_compute::test::validation::tensor_visitors::threshold_operation(), and arm_compute::U8.
 {
     ARM_COMPUTE_ERROR_ON(src.data_type() != DataType::U8 || dst.data_type() != DataType::U8);
     const Tensor<uint8_t> s(src.shape(), src.data_type(), src.fixed_point_position(), reinterpret_cast<const uint8_t *>(src.data()));
     Tensor<uint8_t>       d(dst.shape(), dst.data_type(), dst.fixed_point_position(), reinterpret_cast<uint8_t *>(dst.data()));
     threshold_operation(s, d, threshold, false_value, true_value, type, upper);
 }
The documentation for this class was generated from the following files:
tests/validation/ReferenceCPP.h
tests/validation/ReferenceCPP.cpp