Compute Library: arm_compute::test::cpp11 Namespace Reference
arm_compute::test::cpp11 Namespace Reference
Functions
template<typename T >
std::string to_string (T &&value)
Convert integer and float values to string.
template<typename... Ts>
int stoi (Ts &&...args)
Convert string values to integer.
template<typename... Ts>
int stoul (Ts &&...args)
Convert string values to unsigned long.
template<typename... Ts>
int stof (Ts &&...args)
Convert string values to float.
template<typename T , typename = typename std::enable_if<std::is_floating_point<T>::value>::type>
T round (T value)
Round floating-point value with half value rounding away from zero.
template<typename T , typename = typename std::enable_if<std::is_floating_point<T>::value>::type>
T trunc (T value)
Truncate floating-point value.
template<typename T , typename = typename std::enable_if<std::is_floating_point<T>::value>::type>
T copysign (T x, T y)
Composes a floating point value with the magnitude of x and the sign of y.
template<typename T , typename = typename std::enable_if<std::is_floating_point<T>::value>::type>
T round_half_up (T value)
Round floating-point value with half value rounding to positive infinity.
template<typename T , typename = typename std::enable_if<std::is_floating_point<T>::value>::type>
T round_half_even (T value, T epsilon=std::numeric_limits< T >::epsilon())
Round floating-point value with half value rounding to nearest even.
Function Documentation
T arm_compute::test::cpp11::copysign (T x, T y) inline
Composes a floating point value with the magnitude of x and the sign of y.
Note
This function implements the same behaviour as std::copysign except that it doesn't support Integral type. The latter is not in the namespace std in some Android toolchains.
Parameters
[in] x value that contains the magnitued to be used in constructing the result.
[in] y value that contains the sign to be used in constructin the result.
Returns
Floating-point value with magnitude of x and sign of y.
Definition at line 263 of file Utils.h.
Referenced by round_half_even().
 {
     return std::copysign(x, y);
 }
T arm_compute::test::cpp11::round (T value) inline
Round floating-point value with half value rounding away from zero.
Note
This function implements the same behaviour as std::round except that it doesn't support Integral type. The latter is not in the namespace std in some Android toolchains.
Parameters
[in] value floating-point value to be rounded.
Returns
Floating-point value of rounded value.
Definition at line 232 of file Utils.h.
Referenced by finalize(), lktracker_stage0(), lktracker_stage1(), and round_half_even().
 {
     return std::round(value);
 }
T arm_compute::test::cpp11::round_half_even (T value, T epsilon = std::numeric_limits<T>::epsilon()) inline
Round floating-point value with half value rounding to nearest even.
Parameters
[in] value floating-point value to be rounded.
[in] epsilon precision.
Returns
Floating-point value of rounded value.
Definition at line 289 of file Utils.h.
References arm_compute::test::fixed_point_arithmetic::detail::abs(), copysign(), and round().
Referenced by arm_compute::test::validation::tensor_operations::pixel_wise_multiplication().
 {
     T positive_value = std::abs(value);
     T ipart          = 0;
     std::modf(positive_value, &ipart);
     // If 'value' is exactly halfway between two integers
     if(std::abs(positive_value - (ipart + 0.5f)) < epsilon)
     {
         // If 'ipart' is even then return 'ipart'
         if(std::fmod(ipart, 2.f) < epsilon)
         {
             return cpp11::copysign(ipart, value);
         }
         // Else return the nearest even integer
         return cpp11::copysign(std::ceil(ipart + 0.5f), value);
     }
     // Otherwise use the usual round to closest
     return cpp11::copysign(cpp11::round(positive_value), value);
 }
T arm_compute::test::cpp11::round_half_up (T value) inline
Round floating-point value with half value rounding to positive infinity.
Parameters
[in] value floating-point value to be rounded.
Returns
Floating-point value of rounded value.
Definition at line 276 of file Utils.h.
Referenced by arm_compute::test::validation::tensor_operations::pixel_wise_multiplication().
 {
     return std::floor(value + 0.5f);
 }
int arm_compute::test::cpp11::stof (Ts &&... args)
Convert string values to float.
Note
This function acts as a convenience wrapper around std::stof. The latter is missing in some Android toolchains.
Parameters
[in] args Arguments forwarded to std::stof.
Returns
Float representation of input string.
Definition at line 217 of file Utils.h.
 {
     return ::std::stof(std::forward<Ts>(args)...);
 }
int arm_compute::test::cpp11::stoi (Ts &&... args)
Convert string values to integer.
Note
This function acts as a convenience wrapper around std::stoi. The latter is missing in some Android toolchains.
Parameters
[in] args Arguments forwarded to std::stoi.
Returns
Integer representation of input string.
Definition at line 187 of file Utils.h.
 {
     return ::std::stoi(std::forward<Ts>(args)...);
 }
int arm_compute::test::cpp11::stoul (Ts &&... args)
Convert string values to unsigned long.
Note
This function acts as a convenience wrapper around std::stoul. The latter is missing in some Android toolchains.
Parameters
[in] args Arguments forwarded to std::stoul.
Returns
Unsigned long representation of input string.
Definition at line 202 of file Utils.h.
 {
     return ::std::stoul(std::forward<Ts>(args)...);
 }
std::string arm_compute::test::cpp11::to_string (T && value)
Convert integer and float values to string.
Note
This function acts as a convenience wrapper around std::to_string. The latter is missing in some Android toolchains.
Parameters
[in] value Value to be converted to string.
Returns
String representation of value.
Definition at line 172 of file Utils.h.
 {
     return ::std::to_string(std::forward<T>(value));
 }
T arm_compute::test::cpp11::trunc (T value) inline
Truncate floating-point value.
Note
This function implements the same behaviour as std::truncate except that it doesn't support Integral type. The latter is not in the namespace std in some Android toolchains.
Parameters
[in] value floating-point value to be truncated.
Returns
Floating-point value of truncated value.
Definition at line 247 of file Utils.h.
Referenced by arm_compute::test::validation::tensor_operations::pixel_wise_multiplication().
 {
     return std::trunc(value);
 }