Compute Library: Reducer< F > Class Template Reference
Reducer< F > Class Template Reference
#include <impl.h>
Static Public Member Functions
static void reduceX (const Window &window, const ITensor *input, ITensor *output, F f, const ReductionOperation op)
static void reduceY (const Window &window, const ITensor *input, ITensor *output, F f, const ReductionOperation op)
static void reduceZ (const Window &window, const ITensor *input, ITensor *output, F f, const ReductionOperation op)
static void reduceW (const Window &window, const ITensor *input, ITensor *output, F f, const ReductionOperation op)
Detailed Description
template<class F>
class arm_compute::Reducer< F >
Definition at line 335 of file impl.h.
Member Function Documentation
reduceW()
static void reduceW (const Window & window, const ITensor * input, ITensor * output, F f, const ReductionOperation op) inline static
Definition at line 368 of file impl.h.
     {
         // Set in/out window
         Window in_window(window);
         Window out_window(window);
         in_window.set(3, Window::Dimension(0, 1, 1));
         out_window.set(3, Window::Dimension(0, 1, 1));
         f(in_window, out_window, input, output, 3, op);
     }
References arm_compute::test::validation::input, and Window::set().
reduceX()
static void reduceX (const Window & window, const ITensor * input, ITensor * output, F f, const ReductionOperation op) inline static
Definition at line 338 of file impl.h.
     {
         // Set out window
         Window out_window(window);
         out_window.set(Window::DimX, Window::Dimension(0, 1, 1));
         f(window, out_window, input, output, op);
     }
References Window::DimX, arm_compute::test::validation::input, and Window::set().
reduceY()
static void reduceY (const Window & window, const ITensor * input, ITensor * output, F f, const ReductionOperation op) inline static
Definition at line 346 of file impl.h.
     {
         // Set in window
         Window in_window(window);
         Window out_window(window);
         in_window.set(Window::DimY, Window::Dimension(0, 1, 1));
         out_window.set(Window::DimY, Window::Dimension(0, output->info()->dimension(1), output->info()->dimension(1)));
         f(in_window, out_window, input, output, 1, op);
     }
References ITensorInfo::dimension(), Window::DimY, ITensor::info(), arm_compute::test::validation::input, and Window::set().
reduceZ()
static void reduceZ (const Window & window, const ITensor * input, ITensor * output, F f, const ReductionOperation op) inline static
Definition at line 357 of file impl.h.
     {
         // Set in window
         Window in_window(window);
         Window out_window(window);
         in_window.set(Window::DimZ, Window::Dimension(0, 1, 1));
         out_window.set(Window::DimZ, Window::Dimension(0, output->info()->dimension(2), output->info()->dimension(2)));
         f(in_window, out_window, input, output, 2, op);
     }
References ITensorInfo::dimension(), Window::DimZ, ITensor::info(), arm_compute::test::validation::input, and Window::set().
The documentation for this class was generated from the following file:
src/cpu/kernels/reduction_layer/generic/neon/impl.h