Compute Library: RedOpYZW< T, S > Struct Template Reference
RedOpYZW< T, S > Struct Template Reference
#include <impl.h>
Public Types
using ExactTagType = typename wrapper::traits::neon_vector< T, S >::tag_type
SIMD vector tag type.
using neon_vector = typename wrapper::traits::neon_vector< T, S >::type
Public Member Functions
void operator() (const Window &in_window, Window &out_window, const ITensor *in, ITensor *out, int axis, const ReductionOperation op)
Detailed Description
template<typename T, int S>
struct arm_compute::RedOpYZW< T, S >
Definition at line 898 of file impl.h.
Member Typedef Documentation
ExactTagType
using ExactTagType = typename wrapper::traits::neon_vector<T, S>::tag_type
SIMD vector tag type.
Definition at line 901 of file impl.h.
neon_vector
using neon_vector = typename wrapper::traits::neon_vector<T, S>::type
Definition at line 902 of file impl.h.
Member Function Documentation
operator()()
void operator() (const Window & in_window, Window & out_window, const ITensor * in, ITensor * out, int axis, const ReductionOperation op) inline
Definition at line 904 of file impl.h.
     {
         const TensorInfo in_info            = *(in->info());
         const int        window_step_x      = 16 / sizeof(T);
         const auto       window_start_x_tmp = static_cast<int>(in_window.x().start());
         const auto       window_end_x_tmp   = static_cast<int>(in_window.x().end());
         // As it split over x-axis, need to set the correct spiltted window start and end.
         const auto window_start_x = static_cast<int>(0);
         const auto window_end_x   = static_cast<int>(in_window.shape().x());
         Window in_win_no_pad = in_window;
         in_win_no_pad.set(Window::DimX, Window::Dimension(window_start_x_tmp, window_end_x_tmp, in_window.shape().x()));
         Window out_win_no_pad = out_window;
         out_win_no_pad.set(Window::DimX,
                            Window::Dimension(window_start_x_tmp, window_end_x_tmp, out_window.shape().x()));
         Iterator input(in, in_win_no_pad);
         Iterator output(out, out_win_no_pad);
         execute_window_loop(
             in_win_no_pad,
             [&](const Coordinates &)
             {
                 const auto input_ptr = reinterpret_cast<T *>(input.ptr());
                 // Compute window_step_x elements per iteration
                 int x = window_start_x;
                 for (; x <= (window_end_x - window_step_x); x += window_step_x)
                 {
                     neon_vector vec_res_value = {0};
                     switch (op)
                     {
                         case ReductionOperation::ARG_IDX_MAX:
                         case ReductionOperation::ARG_IDX_MIN:
                         case ReductionOperation::MIN:
                         case ReductionOperation::MAX:
{
                             vec_res_value = wrapper::vloadq(input_ptr + x);
                             break;
                         }
                         case ReductionOperation::PROD:
{
                             vec_res_value = wrapper::vdup_n(static_cast<T>(1.f), ExactTagType{});
                             break;
                         }
                         default:
{
                             vec_res_value = wrapper::vdup_n(static_cast<T>(0.f), ExactTagType{});
                             break;
                         }
                     }
                     uint32x4x4_t vec_res_idx{{0}};
                     for (unsigned int dim = 0; dim < in_info.dimension(axis); ++dim)
                     {
                         const T *in_ptr =
                             reinterpret_cast<T *>(input.ptr() + x * sizeof(T) + in_info.strides_in_bytes()[axis] * dim);
                         const auto vec_elements = wrapper::vloadq(in_ptr);
                         switch (op)
{
                             case ReductionOperation::SUM:
                             case ReductionOperation::MEAN_SUM:
                                 vec_res_value = wrapper::vadd(vec_elements, vec_res_value);
                                 break;
                             case ReductionOperation::SUM_SQUARE:
                                 vec_res_value = wrapper::vadd(wrapper::vmul(vec_elements, vec_elements), vec_res_value);
                                 break;
                             case ReductionOperation::PROD:
                                 vec_res_value = wrapper::vmul(vec_elements, vec_res_value);
                                 break;
                             case ReductionOperation::ARG_IDX_MIN:
{
                                 auto temp_vec_res_value = wrapper::vmin(vec_elements, vec_res_value);
                                 vec_res_idx =
                                     calculate_index(dim, temp_vec_res_value, vec_res_value, vec_res_idx, op, axis);
                                 vec_res_value = temp_vec_res_value;
                                 break;
                             }
                             case ReductionOperation::ARG_IDX_MAX:
{
                                 auto temp_vec_res_value = wrapper::vmax(vec_elements, vec_res_value);
                                 vec_res_idx =
                                     calculate_index(dim, temp_vec_res_value, vec_res_value, vec_res_idx, op, axis);
                                 vec_res_value = temp_vec_res_value;
                                 break;
                             }
                             case ReductionOperation::MIN:
{
                                 vec_res_value = wrapper::vmin(vec_elements, vec_res_value);
                                 break;
                             }
                             case ReductionOperation::MAX:
{
                                 vec_res_value = wrapper::vmax(vec_elements, vec_res_value);
                                 break;
                             }
                             default:
                                 ARM_COMPUTE_ERROR("Not supported");
                         }
                     }
                     if (op == ReductionOperation::MEAN_SUM)
                     {
                         auto vec_width_inv =
                             wrapper::vinv(wrapper::vdup_n(static_cast<T>(in_info.dimension(axis)), ExactTagType{}));
                         vec_res_value = wrapper::vmul(vec_res_value, vec_width_inv);
                     }
                     if (op == ReductionOperation::ARG_IDX_MIN || op == ReductionOperation::ARG_IDX_MAX)
                     {
                         wrapper::vstore(reinterpret_cast<uint32_t *>(output.ptr()) + x, vec_res_idx.val[0]);
 #ifdef __ARM_FEATURE_FP16_VECTOR_ARITHMETIC
                         if (std::is_same<T, float16_t>::value)
{
                             wrapper::vstore(reinterpret_cast<uint32_t *>(output.ptr()) + x + 4, vec_res_idx.val[1]);
                         }
 #endif // __ARM_FEATURE_FP16_VECTOR_ARITHMETIC
                     }
                     else
                     {
                         wrapper::vstore(reinterpret_cast<T *>(output.ptr() + x * sizeof(T)), vec_res_value);
                     }
                 }
                 // Compute left-over elements
                 for (; x < window_end_x; ++x)
                 {
                     auto res_value = 0.f;
                     switch (op)
                     {
                         case ReductionOperation::ARG_IDX_MAX:
                         case ReductionOperation::ARG_IDX_MIN:
                         case ReductionOperation::MIN:
                         case ReductionOperation::MAX:
{
                             res_value = *(input_ptr + x);
                             break;
                         }
                         case ReductionOperation::PROD:
{
                             res_value = static_cast<T>(1.f);
                             break;
                         }
                         default:
{
                             res_value = static_cast<T>(0.f);
                             break;
                         }
                     }
                     uint32_t res_idx = 0;
                     for (unsigned int dim = 0; dim < in_info.dimension(axis); ++dim)
                     {
                         const T *in_ptr =
                             reinterpret_cast<T *>(input.ptr() + x * sizeof(T) + in_info.strides_in_bytes()[axis] * dim);
                         switch (op)
{
                             case ReductionOperation::SUM:
                             case ReductionOperation::MEAN_SUM:
                                 res_value += *in_ptr;
                                 break;
                             case ReductionOperation::SUM_SQUARE:
                                 res_value += *in_ptr * *in_ptr;
                                 break;
                             case ReductionOperation::PROD:
                                 res_value *= *in_ptr;
                                 break;
                             case ReductionOperation::ARG_IDX_MIN:
{
                                 if (*in_ptr < res_value)
{
                                     res_value = *in_ptr;
                                     res_idx   = dim;
                                 }
                                 break;
                             }
                             case ReductionOperation::ARG_IDX_MAX:
{
                                 if (*in_ptr > res_value)
{
                                     res_value = *in_ptr;
                                     res_idx   = dim;
                                 }
                                 break;
                             }
                             case ReductionOperation::MIN:
{
                                 res_value = *in_ptr < res_value ? *in_ptr : res_value;
                                 break;
                             }
                             case ReductionOperation::MAX:
{
                                 res_value = *in_ptr > res_value ? *in_ptr : res_value;
                                 break;
                             }
                             default:
                                 ARM_COMPUTE_ERROR("Not supported");
                         }
                     }
                     if (op == ReductionOperation::MEAN_SUM)
                     {
                         res_value /= in_info.dimension(axis);
                     }
                     if (op == ReductionOperation::ARG_IDX_MIN || op == ReductionOperation::ARG_IDX_MAX)
                     {
                         *(reinterpret_cast<uint32_t *>(output.ptr()) + x) = res_idx;
                     }
                     else
                     {
                         *(reinterpret_cast<T *>(output.ptr() + x * sizeof(T))) = res_value;
                     }
                 }
             },
             input, output);
     }
References arm_compute::ARG_IDX_MAX, arm_compute::ARG_IDX_MIN, ARM_COMPUTE_ERROR, arm_compute::calculate_index(), TensorInfo::dimension(), Window::DimX, Window::Dimension::end(), arm_compute::execute_window_loop(), ITensor::info(), arm_compute::test::validation::input, arm_compute::MAX, arm_compute::MEAN_SUM, arm_compute::MIN, arm_compute::PROD, Iterator::ptr(), Window::set(), Window::shape(), Window::Dimension::start(), TensorInfo::strides_in_bytes(), arm_compute::SUM, arm_compute::SUM_SQUARE, arm_compute::wrapper::vadd(), arm_compute::wrapper::vdup_n(), arm_compute::wrapper::vinv(), arm_compute::wrapper::vloadq(), arm_compute::wrapper::vmax(), arm_compute::wrapper::vmin(), arm_compute::wrapper::vmul(), arm_compute::wrapper::vstore(), Dimensions< T >::x(), and Window::x().
The documentation for this struct was generated from the following file:
src/cpu/kernels/reduction_layer/generic/neon/impl.h