Compute Library: RedOpYZW_quantized< T > Struct Template Reference
RedOpYZW_quantized< T > Struct Template Reference
#include <impl.h>
Public Member Functions
void operator() (const Window &in_window, Window &out_window, const ITensor *in, ITensor *out, int axis, const ReductionOperation op)
Detailed Description
template<typename T>
struct arm_compute::RedOpYZW_quantized< T >
Definition at line 1213 of file impl.h.
Member Function Documentation
operator()()
void operator() (const Window & in_window, Window & out_window, const ITensor * in, ITensor * out, int axis, const ReductionOperation op) inline
Definition at line 1215 of file impl.h.
     {
         const TensorInfo              in_info = *(in->info());
         const UniformQuantizationInfo iq_info = in_info.quantization_info().uniform();
         using PromotedType = typename wrapper::traits::promote<typename wrapper::traits::promote<T>::type>::type;
         const auto oq_info = out->info()->quantization_info().uniform();
         const int  window_step_x      = 16 / sizeof(T);
         const auto window_start_x_tmp = static_cast<int>(in_window.x().start());
         const auto window_end_x_tmp   = static_cast<int>(in_window.x().end());
         // As it split over x-axis, need to set the correct spiltted window start and end.
         const auto window_start_x = static_cast<int>(0);
         const auto window_end_x   = static_cast<int>(in_window.shape().x());
         Window in_win_no_pad = in_window;
         in_win_no_pad.set(Window::DimX, Window::Dimension(window_start_x_tmp, window_end_x_tmp, in_window.shape().x()));
         Window out_win_no_pad = out_window;
         out_win_no_pad.set(Window::DimX,
                            Window::Dimension(window_start_x_tmp, window_end_x_tmp, out_window.shape().x()));
         Iterator input(in, in_win_no_pad);
         Iterator output(out, out_win_no_pad);
         using vector_type =
             typename wrapper::traits::neon_bitvector<PromotedType, wrapper::traits::BitWidth::W128>::type;
         using vector_type_f = typename wrapper::traits::neon_vector<float, 4>::type;
         vector_type vec_res_value1{};
         vector_type vec_res_value2{};
         vector_type vec_res_value3{};
         vector_type vec_res_value4{};
         vector_type_f vec_res_value1_f{};
         vector_type_f vec_res_value2_f{};
         vector_type_f vec_res_value3_f{};
         vector_type_f vec_res_value4_f{};
         const float in_offset = static_cast<float>(iq_info.offset);
         const float in_scale  = iq_info.scale;
         const float out_offset = static_cast<float>(oq_info.offset);
         const float out_scale  = oq_info.scale;
         const float num_elements = static_cast<float>(in_info.dimension(axis));
         const float A = in_scale / (out_scale * num_elements);
         const float B = out_offset - (in_scale * in_offset) / (out_scale);
         const auto vec_A = wrapper::vdup_n(static_cast<float>(A), wrapper::traits::vector_128_tag{});
         const auto vec_B = wrapper::vdup_n(static_cast<float>(B), wrapper::traits::vector_128_tag{});
         execute_window_loop(
             in_win_no_pad,
             [&](const Coordinates &)
             {
                 const auto input_ptr = reinterpret_cast<T *>(input.ptr());
                 // Compute window_step_x elements per iteration
                 int x = window_start_x;
                 for (; x <= (window_end_x - window_step_x); x += window_step_x)
                 {
                     uint32x4x4_t vec_res_idx{{0}};
                     vec_res_value1 = wrapper::vdup_n(static_cast<PromotedType>(0), wrapper::traits::vector_128_tag{});
                     vec_res_value2 = wrapper::vdup_n(static_cast<PromotedType>(0), wrapper::traits::vector_128_tag{});
                     vec_res_value3 = wrapper::vdup_n(static_cast<PromotedType>(0), wrapper::traits::vector_128_tag{});
                     vec_res_value4 = wrapper::vdup_n(static_cast<PromotedType>(0), wrapper::traits::vector_128_tag{});
                     vec_res_value1_f = wrapper::vdup_n(static_cast<float>(1), wrapper::traits::vector_128_tag{});
                     vec_res_value2_f = wrapper::vdup_n(static_cast<float>(1), wrapper::traits::vector_128_tag{});
                     vec_res_value3_f = wrapper::vdup_n(static_cast<float>(1), wrapper::traits::vector_128_tag{});
                     vec_res_value4_f = wrapper::vdup_n(static_cast<float>(1), wrapper::traits::vector_128_tag{});
                     auto vec_res_value = wrapper::vloadq(input_ptr + x);
                     for (unsigned int index_dim = 0; index_dim < in_info.dimension(axis); ++index_dim)
                     {
                         const T   *in_ptr       = input_ptr + x + in_info.strides_in_bytes()[axis] * index_dim;
                         const auto vec_elements = wrapper::vloadq(in_ptr);
                         switch (op)
{
                             case ReductionOperation::SUM:
                             case ReductionOperation::MEAN_SUM:
{
                                 const auto temp16x8t_1 = wrapper::vmovl(wrapper::vgetlow(vec_elements));
                                 const auto temp16x8t_2 = wrapper::vmovl(wrapper::vgethigh(vec_elements));
                                 const auto temp32x4t_1 = wrapper::vmovl(wrapper::vgetlow(temp16x8t_1));
                                 const auto temp32x4t_2 = wrapper::vmovl(wrapper::vgethigh(temp16x8t_1));
                                 const auto temp32x4t_3 = wrapper::vmovl(wrapper::vgetlow(temp16x8t_2));
                                 const auto temp32x4t_4 = wrapper::vmovl(wrapper::vgethigh(temp16x8t_2));
                                 vec_res_value1 = wrapper::vadd(temp32x4t_1, vec_res_value1);
                                 vec_res_value2 = wrapper::vadd(temp32x4t_2, vec_res_value2);
                                 vec_res_value3 = wrapper::vadd(temp32x4t_3, vec_res_value3);
                                 vec_res_value4 = wrapper::vadd(temp32x4t_4, vec_res_value4);
                                 break;
                             }
                             case ReductionOperation::PROD:
{
                                 const auto offset32x4f_4 = wrapper::vdup_n(static_cast<float>(iq_info.offset),
                                                                            wrapper::traits::vector_128_tag{});
                                 const auto scale32x4f_4 =
                                     wrapper::vdup_n(iq_info.scale, wrapper::traits::vector_128_tag{});
                                 const auto temp16x8t_1 = wrapper::vmovl(wrapper::vgetlow(vec_elements));
                                 const auto temp16x8t_2 = wrapper::vmovl(wrapper::vgethigh(vec_elements));
                                 const auto temp32x4t_1 = wrapper::vmovl(wrapper::vgetlow(temp16x8t_1));
                                 const auto temp32x4t_2 = wrapper::vmovl(wrapper::vgethigh(temp16x8t_1));
                                 const auto temp32x4t_3 = wrapper::vmovl(wrapper::vgetlow(temp16x8t_2));
                                 const auto temp32x4t_4 = wrapper::vmovl(wrapper::vgethigh(temp16x8t_2));
                                 auto temp32x4f_1 = wrapper::vcvt<float>(temp32x4t_1);
                                 auto temp32x4f_2 = wrapper::vcvt<float>(temp32x4t_2);
                                 auto temp32x4f_3 = wrapper::vcvt<float>(temp32x4t_3);
                                 auto temp32x4f_4 = wrapper::vcvt<float>(temp32x4t_4);
                                 //de-quantize vec_elements
                                 temp32x4f_1 = wrapper::vmul(wrapper::vsub(temp32x4f_1, offset32x4f_4), scale32x4f_4);
                                 temp32x4f_2 = wrapper::vmul(wrapper::vsub(temp32x4f_2, offset32x4f_4), scale32x4f_4);
                                 temp32x4f_3 = wrapper::vmul(wrapper::vsub(temp32x4f_3, offset32x4f_4), scale32x4f_4);
                                 temp32x4f_4 = wrapper::vmul(wrapper::vsub(temp32x4f_4, offset32x4f_4), scale32x4f_4);
                                 vec_res_value1_f = wrapper::vmul(temp32x4f_1, vec_res_value1_f);
                                 vec_res_value2_f = wrapper::vmul(temp32x4f_2, vec_res_value2_f);
                                 vec_res_value3_f = wrapper::vmul(temp32x4f_3, vec_res_value3_f);
                                 vec_res_value4_f = wrapper::vmul(temp32x4f_4, vec_res_value4_f);
                                 break;
                             }
                             case ReductionOperation::ARG_IDX_MIN:
{
                                 auto temp_vec_res_value = wrapper::vmin(vec_elements, vec_res_value);
                                 vec_res_idx   = calculate_index_quantized(index_dim, temp_vec_res_value, vec_res_value,
                                                                           vec_res_idx, op, axis);
                                 vec_res_value = temp_vec_res_value;
                                 break;
                             }
                             case ReductionOperation::ARG_IDX_MAX:
{
                                 auto temp_vec_res_value = wrapper::vmax(vec_elements, vec_res_value);
                                 vec_res_idx   = calculate_index_quantized(index_dim, temp_vec_res_value, vec_res_value,
                                                                           vec_res_idx, op, axis);
                                 vec_res_value = temp_vec_res_value;
                                 break;
                             }
                             case ReductionOperation::MIN:
{
                                 vec_res_value = wrapper::vmin(vec_elements, vec_res_value);
                                 break;
                             }
                             case ReductionOperation::MAX:
{
                                 vec_res_value = wrapper::vmax(vec_elements, vec_res_value);
                                 break;
                             }
                             default:
                                 ARM_COMPUTE_ERROR("Not supported");
                         }
                     }
                     switch (op)
                     {
                         case ReductionOperation::ARG_IDX_MIN:
                         case ReductionOperation::ARG_IDX_MAX:
{
                             wrapper::vstore(reinterpret_cast<uint32_t *>(output.ptr() + 4 * x), vec_res_idx.val[0]);
                             wrapper::vstore(reinterpret_cast<uint32_t *>(output.ptr() + 4 * x) + 4, vec_res_idx.val[1]);
                             wrapper::vstore(reinterpret_cast<uint32_t *>(output.ptr() + 4 * x) + 8, vec_res_idx.val[2]);
                             wrapper::vstore(reinterpret_cast<uint32_t *>(output.ptr() + 4 * x) + 12,
                                             vec_res_idx.val[3]);
                             break;
                         }
                         case ReductionOperation::MIN:
                         case ReductionOperation::MAX:
{
                             wrapper::vstore(reinterpret_cast<T *>(output.ptr() + x), vec_res_value);
                             break;
                         }
                         case ReductionOperation::SUM:
{
                             // Subtract offsets
                             auto offsets = vdupq_n_s32((in_info.dimension(axis) - 1) * iq_info.offset);
                             auto vec_res_s_value1 = wrapper::vreinterpret(vec_res_value1);
                             auto vec_res_s_value2 = wrapper::vreinterpret(vec_res_value2);
                             auto vec_res_s_value3 = wrapper::vreinterpret(vec_res_value3);
                             auto vec_res_s_value4 = wrapper::vreinterpret(vec_res_value4);
                             vec_res_s_value1 = wrapper::vsub(vec_res_s_value1, offsets);
                             vec_res_s_value2 = wrapper::vsub(vec_res_s_value2, offsets);
                             vec_res_s_value3 = wrapper::vsub(vec_res_s_value3, offsets);
                             vec_res_s_value4 = wrapper::vsub(vec_res_s_value4, offsets);
                             const auto temp16x8t_1 =
                                 wrapper::vcombine(wrapper::vqmovn(vec_res_s_value1), wrapper::vqmovn(vec_res_s_value2));
                             const auto temp16x8t_2 =
                                 wrapper::vcombine(wrapper::vqmovn(vec_res_s_value3), wrapper::vqmovn(vec_res_s_value4));
                             combine_and_store<T>(temp16x8t_1, temp16x8t_2, output, x);
                             break;
                         }
                         case ReductionOperation::MEAN_SUM:
{
                             vec_res_value1_f = wrapper::vmla(vec_B, wrapper::vcvt<float>(vec_res_value1), vec_A);
                             vec_res_value2_f = wrapper::vmla(vec_B, wrapper::vcvt<float>(vec_res_value2), vec_A);
                             vec_res_value3_f = wrapper::vmla(vec_B, wrapper::vcvt<float>(vec_res_value3), vec_A);
                             vec_res_value4_f = wrapper::vmla(vec_B, wrapper::vcvt<float>(vec_res_value4), vec_A);
 #ifdef __aarch64__
                             vec_res_value1 = wrapper::vcvta<PromotedType>(vec_res_value1_f);
                             vec_res_value2 = wrapper::vcvta<PromotedType>(vec_res_value2_f);
                             vec_res_value3 = wrapper::vcvta<PromotedType>(vec_res_value3_f);
                             vec_res_value4 = wrapper::vcvta<PromotedType>(vec_res_value4_f);
 #else  // defined(__aarch64__)
                             vec_res_value1    = wrapper::vcvt<PromotedType>(vec_res_value1_f);
                             vec_res_value2    = wrapper::vcvt<PromotedType>(vec_res_value2_f);
                             vec_res_value3    = wrapper::vcvt<PromotedType>(vec_res_value3_f);
                             vec_res_value4    = wrapper::vcvt<PromotedType>(vec_res_value4_f);
 #endif // __aarch64__
                             const auto temp16x8t_1 =
                                 wrapper::vcombine(wrapper::vqmovn(vec_res_value1), wrapper::vqmovn(vec_res_value2));
                             const auto temp16x8t_2 =
                                 wrapper::vcombine(wrapper::vqmovn(vec_res_value3), wrapper::vqmovn(vec_res_value4));
                             auto res = wrapper::vcombine(wrapper::vqmovn(temp16x8t_1), wrapper::vqmovn(temp16x8t_2));
                             wrapper::vstore(reinterpret_cast<T *>(output.ptr() + x), res);
                             break;
                         }
                         case ReductionOperation::PROD:
{
                             const auto offset32x4f_4 =
                                 wrapper::vdup_n(static_cast<float>(iq_info.offset), wrapper::traits::vector_128_tag{});
                             const auto iscale32x4f_4 = vinvq_f32(vdupq_n_f32(iq_info.scale));
                             //re-quantize
                             vec_res_value1_f =
                                 wrapper::vadd(wrapper::vmul(vec_res_value1_f, iscale32x4f_4), offset32x4f_4);
                             vec_res_value2_f =
                                 wrapper::vadd(wrapper::vmul(vec_res_value2_f, iscale32x4f_4), offset32x4f_4);
                             vec_res_value3_f =
                                 wrapper::vadd(wrapper::vmul(vec_res_value3_f, iscale32x4f_4), offset32x4f_4);
                             vec_res_value4_f =
                                 wrapper::vadd(wrapper::vmul(vec_res_value4_f, iscale32x4f_4), offset32x4f_4);
                             vec_res_value1 = wrapper::vcvt<T>(vec_res_value1_f);
                             vec_res_value2 = wrapper::vcvt<T>(vec_res_value2_f);
                             vec_res_value3 = wrapper::vcvt<T>(vec_res_value3_f);
                             vec_res_value4 = wrapper::vcvt<T>(vec_res_value4_f);
                             const auto temp16x8t_1 =
                                 wrapper::vcombine(wrapper::vqmovn(vec_res_value1), wrapper::vqmovn(vec_res_value2));
                             const auto temp16x8t_2 =
                                 wrapper::vcombine(wrapper::vqmovn(vec_res_value3), wrapper::vqmovn(vec_res_value4));
                             auto res = wrapper::vcombine(wrapper::vqmovn(temp16x8t_1), wrapper::vqmovn(temp16x8t_2));
                             wrapper::vstore(reinterpret_cast<T *>(output.ptr() + x), res);
                             break;
                         }
                         default:
                             ARM_COMPUTE_ERROR("Not supported");
                     }
                 }
                 // Compute left-over elements
                 for (; x < window_end_x; ++x)
                 {
                     float   res_value   = 0.f;
                     int32_t res_value_q = 0;
                     switch (op)
                     {
                         case ReductionOperation::ARG_IDX_MAX:
                         case ReductionOperation::ARG_IDX_MIN:
                         case ReductionOperation::MIN:
                         case ReductionOperation::MAX:
{
                             res_value = *(input_ptr + x);
                             break;
                         }
                         case ReductionOperation::PROD:
{
                             res_value = static_cast<T>(1.0f);
                             break;
                         }
                         default:
{
                             res_value = static_cast<T>(0.0f);
                             break;
                         }
                     }
                     uint32_t res_idx = 0;
                     for (unsigned int dim = 0; dim < in_info.dimension(axis); ++dim)
                     {
                         const T *in_ptr =
                             reinterpret_cast<T *>(input.ptr() + x + in_info.strides_in_bytes()[axis] * dim);
                         switch (op)
{
                             case ReductionOperation::SUM:
{
                                 res_value += *in_ptr;
                                 break;
                             }
                             case ReductionOperation::MEAN_SUM:
{
                                 res_value_q += *in_ptr;
                                 break;
                             }
                             case ReductionOperation::SUM_SQUARE:
{
                                 res_value += *in_ptr * *in_ptr;
                                 break;
                             }
                             case ReductionOperation::PROD:
{
                                 //de-quantize input
                                 if (std::is_same<T, uint8_t>::value)
{
                                     res_value *= dequantize_qasymm8(*in_ptr, iq_info);
                                 }
                                 else
{
                                     res_value *= dequantize_qasymm8_signed(*in_ptr, iq_info);
                                 }
                                 break;
                             }
                             case ReductionOperation::ARG_IDX_MIN:
{
                                 if (*in_ptr < res_value)
{
                                     res_value = *in_ptr;
                                     res_idx   = dim;
                                 }
                                 break;
                             }
                             case ReductionOperation::ARG_IDX_MAX:
{
                                 if (*in_ptr > res_value)
{
                                     res_value = *in_ptr;
                                     res_idx   = dim;
                                 }
                                 break;
                             }
                             case ReductionOperation::MIN:
{
                                 res_value = *in_ptr < res_value ? *in_ptr : res_value;
                                 break;
                             }
                             case ReductionOperation::MAX:
{
                                 res_value = *in_ptr > res_value ? *in_ptr : res_value;
                                 break;
                             }
                             default:
                                 ARM_COMPUTE_ERROR("Not supported");
                         }
                     }
                     switch (op)
                     {
                         case ReductionOperation::MEAN_SUM:
{
                         // Apply previously calculated coefficients (with rounding on aarch64)
 #ifdef __aarch64__
                             const int32_t res =
                                 arm_compute::support::cpp11::round(A * (static_cast<float>(res_value_q)) + B);
 #else  // defined(__aarch64__)
                             const int32_t res = A * (static_cast<float>(res_value_q)) + B;
 #endif // __aarch64__
                             *reinterpret_cast<T *>(output.ptr() + x) = utils::cast::saturate_cast<T>(res);
                             break;
                         }
                         case ReductionOperation::SUM:
{
                             // Subtract accumulated offsets
                             res_value -= (in_info.dimension(axis) - 1) * iq_info.offset;
                             *reinterpret_cast<T *>(output.ptr() + x) = utils::cast::saturate_cast<T>(res_value);
                             break;
                         }
                         case ReductionOperation::PROD:
{
                             //re-quantize result
                             T res = 0;
                             if (std::is_same<T, uint8_t>::value)
{
                                 res = quantize_qasymm8(res_value, iq_info);
                             }
                             else
{
                                 res = quantize_qasymm8_signed(res_value, iq_info);
                             }
                             *(reinterpret_cast<T *>(output.ptr() + x)) = res;
                             break;
                         }
                         case ReductionOperation::ARG_IDX_MIN:
                         case ReductionOperation::ARG_IDX_MAX:
{
                             *(reinterpret_cast<uint32_t *>(output.ptr() + x * 4)) = res_idx;
                             break;
                         }
                         default:
                             *(reinterpret_cast<T *>(output.ptr() + x)) = res_value;
                     }
                 }
             },
             input, output);
     }
References arm_compute::A, arm_compute::ARG_IDX_MAX, arm_compute::ARG_IDX_MIN, ARM_COMPUTE_ERROR, arm_compute::B, arm_compute::calculate_index_quantized(), arm_compute::dequantize_qasymm8(), arm_compute::dequantize_qasymm8_signed(), TensorInfo::dimension(), Window::DimX, Window::Dimension::end(), arm_compute::execute_window_loop(), ITensor::info(), arm_compute::test::validation::input, arm_compute::MAX, arm_compute::MEAN_SUM, arm_compute::MIN, UniformQuantizationInfo::offset, arm_compute::PROD, Iterator::ptr(), ITensorInfo::quantization_info(), TensorInfo::quantization_info(), arm_compute::quantize_qasymm8(), arm_compute::quantize_qasymm8_signed(), arm_compute::support::cpp11::round(), UniformQuantizationInfo::scale, Window::set(), Window::shape(), Window::Dimension::start(), TensorInfo::strides_in_bytes(), arm_compute::SUM, arm_compute::SUM_SQUARE, type, QuantizationInfo::uniform(), arm_compute::wrapper::vadd(), arm_compute::wrapper::vcombine(), arm_compute::wrapper::vdup_n(), arm_compute::wrapper::vgethigh(), arm_compute::wrapper::vgetlow(), arm_compute::vinvq_f32(), arm_compute::wrapper::vloadq(), arm_compute::wrapper::vmax(), arm_compute::wrapper::vmin(), arm_compute::wrapper::vmla(), arm_compute::wrapper::vmovl(), arm_compute::wrapper::vmul(), arm_compute::wrapper::vqmovn(), arm_compute::wrapper::vreinterpret(), arm_compute::wrapper::vstore(), arm_compute::wrapper::vsub(), Dimensions< T >::x(), and Window::x().
The documentation for this struct was generated from the following file:
src/cpu/kernels/reduction_layer/generic/neon/impl.h