Compute Library: CpuComparisonKernel Class Reference
CpuComparisonKernel Class Reference
#include <CpuElementwiseKernel.h>
Public Member Functions
CpuComparisonKernel ()=default
Default constructor.
void configure (ComparisonOperation op, const ITensorInfo *input1, const ITensorInfo *input2, ITensorInfo *output)
Configure kernel.
Public Member Functions inherited from CpuElementwiseKernel
const char * name () const override
Name of the kernel.
CpuElementwiseKernel ()=default
ARM_COMPUTE_DISALLOW_COPY_ALLOW_MOVE (CpuElementwiseKernel)
void run_op (ITensorPack &tensors, const Window &window, const ThreadInfo &info) override
Execute the kernel on the passed window.
Public Member Functions inherited from ICPPKernel
virtual ~ICPPKernel ()=default
Default destructor.
virtual void run (const Window &window, const ThreadInfo &info)
Execute the kernel on the passed window.
virtual void run_nd (const Window &window, const ThreadInfo &info, const Window &thread_locator)
legacy compatibility layer for implemantions which do not support thread_locator In these cases we simply narrow the interface down the legacy version
Public Member Functions inherited from IKernel
IKernel ()
Constructor.
virtual ~IKernel ()=default
Destructor.
virtual bool is_parallelisable () const
Indicates whether or not the kernel is parallelisable.
virtual BorderSize border_size () const
The size of the border for that kernel.
const Window & window () const
The maximum window the kernel can be executed on.
Static Public Member Functions
static Status validate (ComparisonOperation op, const ITensorInfo *input1, const ITensorInfo *input2, const ITensorInfo *output)
Static function to check if given info will lead to a valid configuration of cpu::kernels::CpuComparisonKernel.
Additional Inherited Members
Public Types inherited from CpuElementwiseKernel
using ElementwiseFunction = void(const ITensor *, const ITensor *, ITensor *, const Window &)
Common signature for all the specialised arithmetic functions.
Detailed Description
Definition at line 193 of file CpuElementwiseKernel.h.
Constructor & Destructor Documentation
CpuComparisonKernel()
CpuComparisonKernel () default
Default constructor.
Member Function Documentation
configure()
void configure (ComparisonOperation op, const ITensorInfo * input1, const ITensorInfo * input2, ITensorInfo * output)
Configure kernel.
Comparison operators (equal, not equal, less than, greater than, less than or equal, greater than or equal)
Parameters
[in] op Comparison operation to be executed.
[in] input1 First tensor input info. Data types supported: QASYMM8/QASYMM8_SIGNED/S16/F16/S32/F32.
[in] input2 Second tensor input info. Data types supported: Same as input1.
[out] output Output tensor info. Data types supported: U8.
Definition at line 306 of file CpuElementwiseKernel.cpp.
References ARM_COMPUTE_ERROR_THROW_ON, ARM_COMPUTE_RETURN_ERROR_ON_DATA_TYPE_CHANNEL_NOT_IN, arm_compute::F16, arm_compute::F32, arm_compute::QASYMM8, arm_compute::QASYMM8_SIGNED, arm_compute::S16, arm_compute::S32, ITensorInfo::total_size(), arm_compute::U8, and arm_compute::validate_arguments().
 {
     ARM_COMPUTE_ERROR_THROW_ON(validate_arguments(*input1, *input2, *output));
     configure_common(input1, input2, output);
     _op = op;
 }
validate()
Status validate (ComparisonOperation op, const ITensorInfo * input1, const ITensorInfo * input2, const ITensorInfo * output) static
Static function to check if given info will lead to a valid configuration of cpu::kernels::CpuComparisonKernel.
Parameters
[in] op Comparison operation to be executed.
[in] input1 First tensor input info. Data types supported: QASYMM8/QASYMM8_SIGNED/S16/F16/S32/F32.
[in] input2 Second tensor input info. Data types supported: Same as input1.
[in] output Output tensor info. Data types supported: U8.
Returns
a Status
Definition at line 324 of file CpuElementwiseKernel.cpp.
References ARM_COMPUTE_ERROR, ARM_COMPUTE_RETURN_ERROR_ON_NULLPTR, ARM_COMPUTE_RETURN_ON_ERROR, ARM_COMPUTE_UNUSED, arm_compute::Equal, arm_compute::Greater, arm_compute::GreaterEqual, arm_compute::Less, arm_compute::LessEqual, arm_compute::NotEqual, and arm_compute::validate_arguments().
Referenced by CpuElementwiseComparison::validate(), and CpuElementwiseComparisonStatic< op >::validate().
 {
     ARM_COMPUTE_UNUSED(op);
     ARM_COMPUTE_RETURN_ERROR_ON_NULLPTR(input1, input2, output);
     ARM_COMPUTE_RETURN_ON_ERROR(validate_arguments(*input1, *input2, *output));
     return Status{};
 }
The documentation for this class was generated from the following files:
src/core/cpu/kernels/CpuElementwiseKernel.h
src/core/cpu/kernels/CpuElementwiseKernel.cpp