Compute Library: CLEqualizeHistogram Class Reference
CLEqualizeHistogram Class Reference
Basic function to execute histogram equalization.
#include <CLEqualizeHistogram.h>
Public Member Functions
CLEqualizeHistogram ()
Default Constructor.
CLEqualizeHistogram (const CLEqualizeHistogram &)=delete
Prevent instances of this class from being copied.
CLEqualizeHistogram & operator= (const CLEqualizeHistogram &)=delete
Prevent instances of this class from being copied.
~CLEqualizeHistogram ()
Default destructor.
void configure (const ICLImage *input, ICLImage *output)
Initialise the kernel's inputs.
void configure (const CLCompileContext &compile_context, const ICLImage *input, ICLImage *output)
Initialise the kernel's inputs.
void run () override
Run the kernels contained in the function.
Public Member Functions inherited from IFunction
virtual ~IFunction ()=default
Destructor.
virtual void prepare ()
Prepare the function for executing.
Detailed Description
Basic function to execute histogram equalization.
This function calls the following CL kernels:
CLHistogramKernel
CLTableLookupKernel
Deprecated:
This function is deprecated and is intended to be removed in 21.05 release
Definition at line 51 of file CLEqualizeHistogram.h.
Constructor & Destructor Documentation
CLEqualizeHistogram() [1/2]
CLEqualizeHistogram ()
Default Constructor.
Definition at line 87 of file CLEqualizeHistogram.cpp.
References arm_compute::U8, and CLEqualizeHistogram::~CLEqualizeHistogram().
     : _histogram_kernel(std::make_unique<CLHistogramKernel>()),
       _border_histogram_kernel(std::make_unique<CLHistogramBorderKernel>()),
       _map_histogram_kernel(std::make_unique<CLTableLookupKernel>()),
       _hist(nr_bins, 0, max_range),
       _cum_dist(nr_bins, 0, max_range),
       _cd_lut(nr_bins, DataType::U8)
 {
 }
CLEqualizeHistogram() [2/2]
CLEqualizeHistogram (const CLEqualizeHistogram &) delete
Prevent instances of this class from being copied.
~CLEqualizeHistogram()
~CLEqualizeHistogram () default
Default destructor.
Referenced by CLEqualizeHistogram::CLEqualizeHistogram().
Member Function Documentation
configure() [1/2]
void configure (const ICLImage * input, ICLImage * output)
Initialise the kernel's inputs.
Parameters
[in] input Input image. Data types supported: U8.
[out] output Output of same data type with equalized brightness and contrast.
Definition at line 99 of file CLEqualizeHistogram.cpp.
References CLKernelLibrary::get().
 {
     configure(CLKernelLibrary::get().get_compile_context(), input, output);
 }
configure() [2/2]
void configure (const CLCompileContext & compile_context, const ICLImage * input, ICLImage * output)
Initialise the kernel's inputs.
Parameters
[in] compile_context The compile context to be used.
[in] input Input image. Data types supported: U8.
[out] output Output of same data type with equalized brightness and contrast.
Definition at line 104 of file CLEqualizeHistogram.cpp.
 {
     _histogram_kernel->configure(compile_context, input, &_hist);
     _border_histogram_kernel->configure(compile_context, input, &_hist);
     _map_histogram_kernel->configure(compile_context, input, &_cd_lut, output);
 }
operator=()
CLEqualizeHistogram& operator= (const CLEqualizeHistogram &) delete
Prevent instances of this class from being copied.
run()
void run () override virtual
Run the kernels contained in the function.
For Neon kernels:
Multi-threading is used for the kernels which are parallelisable.
By default std::thread::hardware_concurrency() threads are used.
Note
CPPScheduler::set_num_threads() can be used to manually set the number of threads
For OpenCL kernels:
All the kernels are enqueued on the queue associated with CLScheduler.
The queue is then flushed.
Note
The function will not block until the kernels are executed. It is the user's responsibility to wait.
Will call prepare() on first run if hasn't been done
Implements IFunction.
Definition at line 111 of file CLEqualizeHistogram.cpp.
References CLScheduler::enqueue(), and CLScheduler::get().
 {
     // Calculate histogram of input.
     CLScheduler::get().enqueue(*_histogram_kernel, false);
     // Calculate remaining pixels when image is not multiple of the elements of histogram kernel
     CLScheduler::get().enqueue(*_border_histogram_kernel, false);
     // Calculate cumulative distribution of histogram and create LUT.
     calculate_cum_dist_and_lut(_hist, _cum_dist, _cd_lut);
     // Map input to output using created LUT.
     CLScheduler::get().enqueue(*_map_histogram_kernel);
 }
The documentation for this class was generated from the following files:
arm_compute/runtime/CL/functions/CLEqualizeHistogram.h
src/runtime/CL/functions/CLEqualizeHistogram.cpp