Compute Library: CpuPooling Class Reference
CpuPooling Class Reference
Basic function to simulate a pooling layer with the specified pooling operation.
#include <CpuPooling.h>
Public Member Functions
CpuPooling (std::shared_ptr< IMemoryManager > memory_manager=nullptr)
Constructor.
CpuPooling (const CpuPooling &)=delete
Prevent instances of this class from being copied (As this class contains pointers)
CpuPooling & operator= (const CpuPooling &)=delete
Prevent instances of this class from being copied (As this class contains pointers)
CpuPooling (CpuPooling &&)=delete
Prevent instances of this class from being moved (As this class contains non movable objects)
CpuPooling & operator= (CpuPooling &&)=delete
Prevent instances of this class from being moved (As this class contains non movable objects)
~CpuPooling ()
Default destructor.
void configure (ITensorInfo *src, ITensorInfo *dst, const PoolingLayerInfo &pool_info, ITensorInfo *indices=nullptr)
Set the src and dst tensors.
void run (ITensorPack &tensors) override
Run the kernels contained in the function.
Public Member Functions inherited from INEOperator
INEOperator (IRuntimeContext *ctx=nullptr)
Constructor.
INEOperator (const INEOperator &)=delete
Prevent instances of this class from being copied (As this class contains pointers)
INEOperator (INEOperator &&)=default
Default move constructor.
INEOperator & operator= (const INEOperator &)=delete
Prevent instances of this class from being copied (As this class contains pointers)
INEOperator & operator= (INEOperator &&)=default
Default move assignment operator.
~INEOperator ()
Default destructor.
void prepare (ITensorPack &constants) override
Prepare the function for executing.
MemoryRequirements workspace () const override
Return the memory requirements required by the workspace.
Public Member Functions inherited from IOperator
virtual ~IOperator ()=default
Destructor.
Static Public Member Functions
static Status validate (const ITensorInfo *src, const ITensorInfo *dst, const PoolingLayerInfo &pool_info, const ITensorInfo *indices=nullptr)
Static function to check if given info will lead to a valid configuration of CpuPooling.
Detailed Description
Basic function to simulate a pooling layer with the specified pooling operation.
This function calls the following Neon kernels:
NEFillBorderKernel (executed if padding size is different from zero)
kernels::CpuPoolingKernel
CpuPoolingAssemblyDispatch
Definition at line 49 of file CpuPooling.h.
Constructor & Destructor Documentation
CpuPooling() [1/3]
CpuPooling (std::shared_ptr< IMemoryManager > memory_manager = nullptr)
Constructor.
Definition at line 36 of file CpuPooling.cpp.
References arm_compute::NCHW, and CpuPooling::~CpuPooling().
     : _memory_manager(std::move(memory_manager)), _pooling_layer_kernel(), _border_handler(), _asm_glue(), _is_global_pooling_layer(false), _data_layout(DataLayout::NCHW)
 {
 }
CpuPooling() [2/3]
CpuPooling (const CpuPooling &) delete
Prevent instances of this class from being copied (As this class contains pointers)
CpuPooling() [3/3]
CpuPooling (CpuPooling &&) delete
Prevent instances of this class from being moved (As this class contains non movable objects)
~CpuPooling()
~CpuPooling () default
Default destructor.
Referenced by CpuPooling::CpuPooling().
Member Function Documentation
configure()
void configure (ITensorInfo * src, ITensorInfo * dst, const PoolingLayerInfo & pool_info, ITensorInfo * indices = nullptr)
Set the src and dst tensors.
Note
F16 is supported for pool sizes 2 and 3 only
Parameters
[in,out] src Source tensor info. (Written to only when padding != 0) Data types supported: QASYMM8/QASYMM8_SIGNED/F16/F32.
[out] dst Destination tensor info. Data types supported: same as src.
[in] pool_info Contains pooling operation information described in PoolingLayerInfo.
[out] indices (optional) The indices of the maximal values. Data type supported: U32.
Definition at line 43 of file CpuPooling.cpp.
References ARM_COMPUTE_ERROR, ARM_COMPUTE_ERROR_ON, arm_compute::test::validation::b, arm_compute::CONSTANT, ITensorInfo::data_layout(), PoolingLayerInfo::data_layout, ITensorInfo::data_type(), ITensorInfo::dimension(), PoolingLayerInfo::exclude_padding, Size2D::height, arm_compute::is_data_type_quantized_asymmetric(), arm_compute::MAX, arm_compute::NCHW, arm_compute::NHWC, PoolingLayerInfo::pool_size, PoolingLayerInfo::pool_type, ITensorInfo::quantization_info(), arm_compute::REPLICATE, arm_compute::UNKNOWN, CpuPoolingAssemblyDispatch::validate(), and Size2D::width.
 {
     // Check if we can run assembly kernels. Currently, indices are not supported by those kernels
     const bool run_optimised = bool(CpuPoolingAssemblyDispatch::validate(input, output, pool_info)) && (indices == nullptr);
     if(run_optimised)
     {
         _asm_glue = std::make_unique<CpuPoolingAssemblyDispatch>(_memory_manager);
         _asm_glue->configure(input, output, pool_info);
         ARM_COMPUTE_ERROR_ON(!_asm_glue->is_configured());
     }
     else
     {
         // Check if we have Global Pooling Layer
         _is_global_pooling_layer = (input->dimension(0) == pool_info.pool_size.width) && (input->dimension(1) == pool_info.pool_size.height);
         // Get data layout
         _data_layout = pool_info.data_layout == DataLayout::UNKNOWN ? input->data_layout() : pool_info.data_layout;
         // Configure pooling kernel
         auto k = std::make_unique<kernels::CpuPoolingKernel>();
         k->configure(input, output, pool_info, indices);
         _pooling_layer_kernel = std::move(k);
         switch(_data_layout)
         {
             case DataLayout::NCHW:
             {
                 // Configure border depending on operation required (quantize border in case of asymmetric data_type)
                 BorderMode border_mode = (!indices && pool_info.pool_type == PoolingType::MAX) ? BorderMode::REPLICATE : BorderMode::CONSTANT;
                 PixelValue zero_value((indices) ? std::numeric_limits<int>::min() : 0.f);
                 if(is_data_type_quantized_asymmetric(input->data_type()) && !pool_info.exclude_padding)
                 {
                     zero_value = PixelValue(0, input->data_type(), input->quantization_info());
                 }
                 auto b = std::make_unique<NEFillBorderKernel>();
                 b->configure(input, _pooling_layer_kernel->border_size(), border_mode, zero_value);
                 _border_handler = std::move(b);
                 break;
             }
             case DataLayout::NHWC:
                 break;
             default:
                 ARM_COMPUTE_ERROR("Data layout not supported");
         }
     }
 }
operator=() [1/2]
CpuPooling& operator= (const CpuPooling &) delete
Prevent instances of this class from being copied (As this class contains pointers)
operator=() [2/2]
CpuPooling& operator= (CpuPooling &&) delete
Prevent instances of this class from being moved (As this class contains non movable objects)
run()
void run (ITensorPack & tensors) override virtual
Run the kernels contained in the function.
Parameters
[in] tensors Vector that contains the tensors to operate on.
Reimplemented from INEOperator.
Definition at line 103 of file CpuPooling.cpp.
References ARM_COMPUTE_ERROR, Window::DimX, Window::DimY, Window::DimZ, Scheduler::get(), arm_compute::NCHW, arm_compute::NHWC, and IScheduler::schedule_op().
 {
     if(_asm_glue && _asm_glue->is_configured())
     {
         _asm_glue->run(tensors);
     }
     else
     {
         switch(_data_layout)
         {
             case DataLayout::NCHW:
                 // Fill border
                 NEScheduler::get().schedule_op(_border_handler.get(), Window::DimY, _border_handler->window(), tensors);
                 // Run pooling layer
                 NEScheduler::get().schedule_op(_pooling_layer_kernel.get(), _is_global_pooling_layer ? Window::DimZ : Window::DimY, _pooling_layer_kernel->window(), tensors);
                 break;
             case DataLayout::NHWC:
                 // Run pooling layer
                 NEScheduler::get().schedule_op(_pooling_layer_kernel.get(), Window::DimX, _pooling_layer_kernel->window(), tensors);
                 break;
             default:
                 ARM_COMPUTE_ERROR("Data layout not supported");
         }
     }
 }
validate()
Status validate (const ITensorInfo * src, const ITensorInfo * dst, const PoolingLayerInfo & pool_info, const ITensorInfo * indices = nullptr) static
Static function to check if given info will lead to a valid configuration of CpuPooling.
Note
F16 is supported for pool sizes 2 and 3 only
Parameters
[in] src Source tensor info. (Written to only when padding != 0) Data types supported: QASYMM8/QASYMM8_SIGNED/F16/F32.
[in] dst Destination tensor info. Data types supported: same as src.
[in] pool_info Contains pooling operation information described in PoolingLayerInfo.
[in] indices (optional) Tensor info of the indices of the maximal values. Data type supported: U32.
Returns
a status
Definition at line 91 of file CpuPooling.cpp.
References CpuPoolingKernel::validate(), and CpuPoolingAssemblyDispatch::validate().
Referenced by NEPoolingLayer::validate().
 {
     const bool run_optimised = bool(CpuPoolingAssemblyDispatch::validate(input, output, pool_info)) && (indices == nullptr);
     if(run_optimised)
     {
         return Status{};
     }
     return kernels::CpuPoolingKernel::validate(input, output, pool_info, indices);
 }
The documentation for this class was generated from the following files:
src/runtime/cpu/operators/CpuPooling.h
src/runtime/cpu/operators/CpuPooling.cpp