Compute Library: CpuPoolingAssemblyWrapperKernel Class Reference
CpuPoolingAssemblyWrapperKernel Class Reference final
This class is a wrapper for the assembly kernels.
#include <CpuPoolingAssemblyWrapperKernel.h>
Public Member Functions
CpuPoolingAssemblyWrapperKernel ()=default
Constructor.
CpuPoolingAssemblyWrapperKernel (CpuPoolingAssemblyWrapperKernel &)=delete
CpuPoolingAssemblyWrapperKernel (CpuPoolingAssemblyWrapperKernel &&)=default
CpuPoolingAssemblyWrapperKernel & operator= (CpuPoolingAssemblyWrapperKernel &)=delete
const char * name () const override
Name of the kernel.
void configure (const ITensorInfo *src, ITensorInfo *dst, const PoolingLayerInfo &info, const CPUInfo &cpu_info)
Initialise the kernel's src and dst.
void run_op (ITensorPack &tensors, const Window &window, const ThreadInfo &info) override
Execute the kernel on the passed window.
size_t get_working_size (unsigned int num_threads) const
Get size of the workspace needed by the assembly kernel.
bool is_configured () const
Was the asm kernel successfully configured?
Public Member Functions inherited from ICPPKernel
virtual ~ICPPKernel ()=default
Default destructor.
virtual void run (const Window &window, const ThreadInfo &info)
Execute the kernel on the passed window.
virtual void run_nd (const Window &window, const ThreadInfo &info, const Window &thread_locator)
legacy compatibility layer for implemantions which do not support thread_locator In these cases we simply narrow the interface down the legacy version
Public Member Functions inherited from IKernel
IKernel ()
Constructor.
virtual ~IKernel ()=default
Destructor.
virtual bool is_parallelisable () const
Indicates whether or not the kernel is parallelisable.
virtual BorderSize border_size () const
The size of the border for that kernel.
const Window & window () const
The maximum window the kernel can be executed on.
Static Public Member Functions
static Status validate (const ITensorInfo *src, const ITensorInfo *dst, const PoolingLayerInfo &info)
Indicates whether or not this function can be used to process the given parameters.
Detailed Description
This class is a wrapper for the assembly kernels.
Some kernels were written in assembly and highly optimised for specific CPUs like A53 or A55. The arm compute library creates an instance of CpuPoolingAssemblyWrapperKernel and other auxiliary data structures to execute a single assembly kernel in the context of an NEFunction.
Definition at line 48 of file CpuPoolingAssemblyWrapperKernel.h.
Constructor & Destructor Documentation
CpuPoolingAssemblyWrapperKernel() [1/3]
CpuPoolingAssemblyWrapperKernel () default
Constructor.
CpuPoolingAssemblyWrapperKernel() [2/3]
CpuPoolingAssemblyWrapperKernel (CpuPoolingAssemblyWrapperKernel &) delete
CpuPoolingAssemblyWrapperKernel() [3/3]
CpuPoolingAssemblyWrapperKernel (CpuPoolingAssemblyWrapperKernel &&) default
Member Function Documentation
configure()
void configure (const ITensorInfo * src, ITensorInfo * dst, const PoolingLayerInfo & info, const CPUInfo & cpu_info)
Initialise the kernel's src and dst.
Parameters
[in] src Source tensor info. Data types supported: QASYMM8/QASYMM8_SIGNED/F16/F32.
[out] dst Destination tensor info to store the result of pooling. Data types supported: same as src.
[in] info Pooling meta-data.
[in] cpu_info CPU information needed to select the most appropriate kernel.
Definition at line 44 of file CpuPoolingAssemblyWrapperKernel.cpp.
References ARM_COMPUTE_ERROR_ON_NULLPTR, arm_compute::auto_init_if_empty(), arm_compute::calculate_max_window(), ICloneable< T >::clone(), arm_compute::misc::shape_calculator::compute_pool_shape(), ITensorInfo::data_type(), arm_compute::test::validation::dst, arm_compute::F16, arm_compute::F32, arm_compute::test::validation::info, arm_compute::QASYMM8, arm_compute::QASYMM8_SIGNED, ITensorInfo::quantization_info(), and arm_compute::test::validation::src.
Referenced by CpuPoolingAssemblyWrapperKernel::name().
 {
     ARM_COMPUTE_ERROR_ON_NULLPTR(src, dst);
     // dst initialization if not yet initialized
     auto_init_if_empty(*dst, src->clone()->set_tensor_shape(compute_pool_shape(*src, info)));
     const bool requantize = src->quantization_info() != dst->quantization_info();
     switch(src->data_type())
     {
         case DataType::QASYMM8:
             if(requantize)
             {
                 create_arm_pooling_requant<uint8_t, uint8_t>(src, dst, info, cpu_info);
             }
             else
             {
                 create_arm_pooling<uint8_t, uint8_t>(src, dst, info, cpu_info);
             }
             break;
         case DataType::QASYMM8_SIGNED:
             if(requantize)
             {
                 create_arm_pooling_requant<int8_t, int8_t>(src, dst, info, cpu_info);
             }
             else
             {
                 create_arm_pooling<int8_t, int8_t>(src, dst, info, cpu_info);
             }
             break;
 #ifdef __ARM_FEATURE_FP16_VECTOR_ARITHMETIC
         case DataType::F16:
             create_arm_pooling<float16_t, float16_t>(src, dst, info, cpu_info);
             break;
 #endif /* __ARM_FEATURE_FP16_VECTOR_ARITHMETIC */
         case DataType::F32:
             create_arm_pooling<float, float>(src, dst, info, cpu_info);
             break;
         default:
             break;
     }
     Window win = calculate_max_window(*dst, Steps());
     INEKernel::configure(win);
 }
get_working_size()
size_t get_working_size (unsigned int num_threads) const
Get size of the workspace needed by the assembly kernel.
Parameters
[in] num_threads Maximum number of threads that are going to be spawned.
Returns
size of workspace
Definition at line 173 of file CpuPoolingAssemblyWrapperKernel.cpp.
Referenced by CpuPoolingAssemblyWrapperKernel::name().
 {
     return _kernel_asm->get_working_size(num_threads);
 }
is_configured()
bool is_configured () const
Was the asm kernel successfully configured?
Returns
True if the asm kernel is configured and ready to run
Definition at line 178 of file CpuPoolingAssemblyWrapperKernel.cpp.
References GemmTuner::args, arm_compute::AVG, arm_compute::quantization::calculate_quantized_multiplier(), ITensorInfo::dimension(), arm_compute::test::validation::dst, PoolingLayerInfo::exclude_padding, arm_compute::test::validation::idx_height, arm_compute::test::validation::idx_width, arm_compute::test::validation::info, MAX, PadStrideInfo::pad_bottom(), PadStrideInfo::pad_left(), PadStrideInfo::pad_right(), PoolingLayerInfo::pad_stride_info, PadStrideInfo::pad_top(), PoolingLayerInfo::pool_size, PoolingLayerInfo::pool_type, ITensorInfo::quantization_info(), UniformQuantizationInfo::scale, arm_compute::test::validation::src, PadStrideInfo::stride(), QuantizationInfo::uniform(), Size2D::x(), and Size2D::y().
Referenced by CpuPoolingAssemblyWrapperKernel::name().
 {
     return _kernel_asm != nullptr;
 }
name()
const char* name () const inline override virtual
Name of the kernel.
Returns
Kernel name
Implements ICPPKernel.
Definition at line 58 of file CpuPoolingAssemblyWrapperKernel.h.
References CpuPoolingAssemblyWrapperKernel::configure(), arm_compute::test::validation::dst, CpuPoolingAssemblyWrapperKernel::get_working_size(), arm_compute::test::validation::info, CpuPoolingAssemblyWrapperKernel::is_configured(), CpuPoolingAssemblyWrapperKernel::run_op(), arm_compute::test::validation::src, CpuPoolingAssemblyWrapperKernel::validate(), and IKernel::window().
     {
         return "CpuPoolingAssemblyWrapperKernel";
     }
operator=()
CpuPoolingAssemblyWrapperKernel& operator= (CpuPoolingAssemblyWrapperKernel &) delete
run_op()
void run_op (ITensorPack & tensors, const Window & window, const ThreadInfo & info) override virtual
Execute the kernel on the passed window.
Warning
If is_parallelisable() returns false then the passed window must be equal to window()
Note
The window has to be a region within the window returned by the window() method
The width of the window has to be a multiple of num_elems_processed_per_iteration().
Parameters
[in] tensors A vector containing the tensors to operate on.
[in] window Region on which to execute the kernel. (Must be a region of the window returned by window())
[in] info Info about executing thread and CPU.
Reimplemented from ICPPKernel.
Definition at line 139 of file CpuPoolingAssemblyWrapperKernel.cpp.
References arm_compute::ACL_DST_0, arm_compute::ACL_DST_1, arm_compute::ACL_SRC, ARM_COMPUTE_ERROR_ON, ARM_COMPUTE_ERROR_ON_NULLPTR, ARM_COMPUTE_ERROR_ON_UNCONFIGURED_KERNEL, ARM_COMPUTE_UNUSED, ITensor::buffer(), arm_compute::test::validation::dst, arm_compute::test::validation::dst_shape, ITensorPack::empty(), ITensorPack::get_const_tensor(), ITensorPack::get_tensor(), ITensor::info(), BorderSize::left, ThreadInfo::num_threads, ITensorInfo::offset_first_element_in_bytes(), ITensorInfo::padding(), arm_compute::test::validation::src, ITensorInfo::tensor_shape(), and ThreadInfo::thread_id.
Referenced by CpuPoolingAssemblyWrapperKernel::name().
 {
     ARM_COMPUTE_ERROR_ON_NULLPTR(_kernel_asm.get());
     ARM_COMPUTE_ERROR_ON_UNCONFIGURED_KERNEL(this);
     ARM_COMPUTE_UNUSED(window);
     ARM_COMPUTE_UNUSED(info);
     ARM_COMPUTE_ERROR_ON(tensors.empty());
     const ITensor *src       = tensors.get_const_tensor(TensorType::ACL_SRC);
     ITensor       *dst       = tensors.get_tensor(TensorType::ACL_DST_0);
     ITensor       *workspace = tensors.get_tensor(TensorType::ACL_DST_1);
     const auto in_ptr        = src->buffer() + src->info()->offset_first_element_in_bytes();
     auto       out_ptr       = dst->buffer() + dst->info()->offset_first_element_in_bytes();
     auto       working_space = workspace->buffer() + workspace->info()->offset_first_element_in_bytes();
     const auto src_shape   = src->info()->tensor_shape();
     const auto dst_shape   = dst->info()->tensor_shape();
     const auto src_padding = src->info()->padding();
     const auto dst_padding = dst->info()->padding();
     const size_t ld_src_col   = src_shape[0] + src_padding.left + src_padding.right;
     const size_t ld_src_row   = ld_src_col * (src_shape[1] + src_padding.top + src_padding.bottom);
     const size_t ld_src_batch = ld_src_row * src_shape[2];
     const size_t ld_dst_col   = dst_shape[0] + dst_padding.left + dst_padding.right;
     const size_t ld_dst_row   = ld_dst_col * (dst_shape[1] + dst_padding.top + dst_padding.bottom);
     const size_t ld_dst_batch = ld_dst_row * dst_shape[2];
     _kernel_asm->execute(in_ptr, ld_src_col, ld_src_row, ld_src_batch,
                          out_ptr, ld_dst_col, ld_dst_row, ld_dst_batch,
                          working_space, info.thread_id, info.num_threads);
 }
validate()
Status validate (const ITensorInfo * src, const ITensorInfo * dst, const PoolingLayerInfo & info) static
Indicates whether or not this function can be used to process the given parameters.
Parameters
[in] src Source tensor info. Data types supported: QASYMM8/QASYMM8_SIGNED/F16/F32.
[in] dst Destination tensor to store the result of pooling. Data types supported: same as src.
[in] info Pooling meta-data
Returns
a status.
Definition at line 91 of file CpuPoolingAssemblyWrapperKernel.cpp.
References ARM_COMPUTE_RETURN_ERROR_MSG, ARM_COMPUTE_RETURN_ERROR_ON, ARM_COMPUTE_RETURN_ERROR_ON_CPU_F16_UNSUPPORTED, ARM_COMPUTE_RETURN_ERROR_ON_DATA_TYPE_CHANNEL_NOT_IN, ARM_COMPUTE_RETURN_ERROR_ON_MISMATCHING_DATA_TYPES, ARM_COMPUTE_RETURN_ERROR_ON_MSG, ARM_COMPUTE_RETURN_ERROR_ON_NULLPTR, arm_compute::AVG, arm_compute::quantization::calculate_quantized_multiplier(), ITensorInfo::data_layout(), PoolingLayerInfo::data_layout, ITensorInfo::data_type(), PoolingLayerInfo::exclude_padding, arm_compute::F16, arm_compute::F32, PadStrideInfo::has_padding(), arm_compute::MAX, arm_compute::NHWC, PoolingLayerInfo::pad_stride_info, PoolingLayerInfo::pool_type, arm_compute::QASYMM8, arm_compute::QASYMM8_SIGNED, ITensorInfo::quantization_info(), UniformQuantizationInfo::scale, ITensorInfo::total_size(), and QuantizationInfo::uniform().
Referenced by CpuPoolingAssemblyWrapperKernel::name(), and CpuPoolingAssemblyDispatch::validate().
 {
     ARM_COMPUTE_RETURN_ERROR_ON_NULLPTR(src, dst);
 #ifndef __aarch64__
     ARM_COMPUTE_RETURN_ERROR_MSG("32-bit is not supported by assembly kernels");
 #endif /* __aarch64__ */
     ARM_COMPUTE_RETURN_ERROR_ON_CPU_F16_UNSUPPORTED(src);
     ARM_COMPUTE_RETURN_ERROR_ON_DATA_TYPE_CHANNEL_NOT_IN(src, 1, DataType::QASYMM8, DataType::QASYMM8_SIGNED, DataType::F16, DataType::F32);
     ARM_COMPUTE_RETURN_ERROR_ON_MSG((src->data_layout() != DataLayout::NHWC) || (info.data_layout != DataLayout::NHWC), "Only NHWC is supported by assembly kernels");
     ARM_COMPUTE_RETURN_ERROR_ON_MSG((info.pool_type != PoolingType::AVG) && (info.pool_type != PoolingType::MAX),
                                     "Only AVG and MAX pooling are supported by assembly kernels");
     if(dst->total_size() > 0)
     {
         ARM_COMPUTE_RETURN_ERROR_ON_MISMATCHING_DATA_TYPES(src, dst);
         const auto src_qinfo = src->quantization_info().uniform();
         const auto dst_qinfo = dst->quantization_info().uniform();
         if(src_qinfo != dst_qinfo)
         {
             const float multiplier = src_qinfo.scale / dst_qinfo.scale;
             int32_t     dst_multiplier{};
             int32_t     dst_shift{};
             ARM_COMPUTE_RETURN_ERROR_ON(quantization::calculate_quantized_multiplier(multiplier, &dst_multiplier, &dst_shift));
         }
         else
         {
             if(src->data_type() == DataType::QASYMM8)
             {
                 const bool has_padding = info.pad_stride_info.has_padding();
                 ARM_COMPUTE_RETURN_ERROR_ON_MSG(!info.exclude_padding && has_padding, "Assembly kernels do not support padding for QASYMM8 with same src/dst quantization info");
             }
         }
     }
     else
     {
         if(src->data_type() == DataType::QASYMM8)
         {
             // If dst is not configured, the quantization info are the same
             const bool has_padding = info.pad_stride_info.has_padding();
             ARM_COMPUTE_RETURN_ERROR_ON_MSG(!info.exclude_padding && has_padding, "Assembly kernels do not support padding for QASYMM8 with same src/dst quantization info");
         }
     }
     return Status{};
 }
The documentation for this class was generated from the following files:
src/core/cpu/kernels/CpuPoolingAssemblyWrapperKernel.h
src/core/cpu/kernels/CpuPoolingAssemblyWrapperKernel.cpp