Compute Library: CLConvolutionSquare< matrix_size > Class Template Reference
CLConvolutionSquare< matrix_size > Class Template Reference
Basic function to execute square convolution.Currently it supports 5x5, 7x7, 9x9.
#include <CLConvolution.h>
Public Member Functions
CLConvolutionSquare (std::shared_ptr< IMemoryManager > memory_manager=nullptr)
Default constructor.
CLConvolutionSquare (const CLConvolutionSquare &)=delete
Prevent instances of this class from being copied (As this class contains pointers)
CLConvolutionSquare (CLConvolutionSquare &&)=default
Default move constructor.
CLConvolutionSquare & operator= (const CLConvolutionSquare &)=delete
Prevent instances of this class from being copied (As this class contains pointers)
CLConvolutionSquare & operator= (CLConvolutionSquare &&)=default
Default move assignment operator.
~CLConvolutionSquare ()
Default destructor.
void configure (ICLTensor *input, ICLTensor *output, const int16_t *conv, uint32_t scale, BorderMode border_mode, uint8_t constant_border_value=0)
Initialize the function's source, destination, conv and border_mode.
void configure (const CLCompileContext &compile_context, ICLTensor *input, ICLTensor *output, const int16_t *conv, uint32_t scale, BorderMode border_mode, uint8_t constant_border_value=0)
Initialize the function's source, destination, conv and border_mode.
void run () override
Run the kernels contained in the function.
Public Member Functions inherited from IFunction
virtual ~IFunction ()=default
Destructor.
virtual void prepare ()
Prepare the function for executing.
Detailed Description
template<unsigned int matrix_size>
class arm_compute::CLConvolutionSquare< matrix_size >
Basic function to execute square convolution.Currently it supports 5x5, 7x7, 9x9.
This function calls the following OpenCL kernels:
CLFillBorderKernel (executed if border_mode == CONSTANT or border_mode == REPLICATE)
CLConvolutionKernel or
CLSeparableConvolutionHorKernel and CLSeparableConvolutionVertKernel (if convolution matrix is separable)
Deprecated:
This function is deprecated and is intended to be removed in 21.05 release
Definition at line 92 of file CLConvolution.h.
Constructor & Destructor Documentation
CLConvolutionSquare() [1/3]
CLConvolutionSquare (std::shared_ptr< IMemoryManager > memory_manager = nullptr)
Default constructor.
Definition at line 56 of file CLConvolution.cpp.
References CLConvolutionSquare< matrix_size >::~CLConvolutionSquare().
     : _memory_group(std::move(memory_manager)), _tmp(), _is_separable(false), _kernel_hor(std::make_unique<CLSeparableConvolutionHorKernel<matrix_size>>()),
       _kernel_vert(std::make_unique<CLSeparableConvolutionVertKernel<matrix_size>>()), _kernel(std::make_unique<CLConvolutionKernel<matrix_size>>()), _border_handler(std::make_unique<CLFillBorderKernel>())
 {
 }
CLConvolutionSquare() [2/3]
CLConvolutionSquare (const CLConvolutionSquare< matrix_size > &) delete
Prevent instances of this class from being copied (As this class contains pointers)
CLConvolutionSquare() [3/3]
CLConvolutionSquare (CLConvolutionSquare< matrix_size > &&) default
Default move constructor.
~CLConvolutionSquare()
~CLConvolutionSquare () default
Default destructor.
Referenced by CLConvolutionSquare< matrix_size >::CLConvolutionSquare().
Member Function Documentation
configure() [1/2]
void configure (ICLTensor * input, ICLTensor * output, const int16_t * conv, uint32_t scale, BorderMode border_mode, uint8_t constant_border_value = 0)
Initialize the function's source, destination, conv and border_mode.
Parameters
[in,out] input Source tensor. Data types supported: U8. (Written to only for border_mode != UNDEFINED)
[out] output Destination tensor, Data types supported: U8 or S16.
[in] conv matrix_size x matrix_size S16 coefficients structured as a row-major 2D array in a linear buffer.
[in] scale Scale of the convolution matrix. If 0 is passed, it will be set to the sum of the coefficients of the convolution or 1 if they add up to 0.
[in] border_mode Strategy to use for borders.
[in] constant_border_value (Optional) Constant value to use for borders if border_mode is set to CONSTANT.
Definition at line 66 of file CLConvolution.cpp.
References CLKernelLibrary::get().
Referenced by CLConvolutionRectangle::configure().
 {
     configure(CLKernelLibrary::get().get_compile_context(), input, output, conv, scale, border_mode, constant_border_value);
 }
configure() [2/2]
void configure (const CLCompileContext & compile_context, ICLTensor * input, ICLTensor * output, const int16_t * conv, uint32_t scale, BorderMode border_mode, uint8_t constant_border_value = 0)
Initialize the function's source, destination, conv and border_mode.
Parameters
[in] compile_context The compile context to be used.
[in,out] input Source tensor. Data types supported: U8. (Written to only for border_mode != UNDEFINED)
[out] output Destination tensor, Data types supported: U8 or S16.
[in] conv matrix_size x matrix_size S16 coefficients structured as a row-major 2D array in a linear buffer.
[in] scale Scale of the convolution matrix. If 0 is passed, it will be set to the sum of the coefficients of the convolution or 1 if they add up to 0.
[in] border_mode Strategy to use for borders.
[in] constant_border_value (Optional) Constant value to use for borders if border_mode is set to CONSTANT.
Definition at line 73 of file CLConvolution.cpp.
References CLTensorAllocator::allocate(), CLTensor::allocator(), ARM_COMPUTE_ERROR_ON, ARM_COMPUTE_ERROR_ON_DATA_TYPE_CHANNEL_NOT_IN, arm_compute::calculate_matrix_scale(), arm_compute::data_type_for_convolution(), ITensor::info(), ITensorAllocator::init(), MemoryGroup::manage(), arm_compute::test::validation::scale, arm_compute::separate_matrix(), ITensorInfo::tensor_shape(), arm_compute::U8, and arm_compute::UNDEFINED.
 {
     ARM_COMPUTE_ERROR_ON_DATA_TYPE_CHANNEL_NOT_IN(input, 1, DataType::U8);
     ARM_COMPUTE_ERROR_ON(conv == nullptr);
     std::array<int16_t, matrix_size> conv_col{ 0 };
     std::array<int16_t, matrix_size> conv_row{ 0 };
     _is_separable = separate_matrix(conv, conv_col.data(), conv_row.data(), matrix_size);
     if(_is_separable)
     {
         std::pair<DataType, DataType> type_pair = data_type_for_convolution(conv_col.data(), conv_row.data(), matrix_size);
         _tmp.allocator()->init(TensorInfo(input->info()->tensor_shape(), 1, type_pair.first));
         // Manage intermediate buffers
         _memory_group.manage(&_tmp);
         if(scale == 0)
         {
             scale = calculate_matrix_scale(conv, matrix_size);
         }
         _kernel_hor->configure(compile_context, input, &_tmp, conv_row.data(), border_mode == BorderMode::UNDEFINED);
         _kernel_vert->configure(compile_context, &_tmp, output, conv_col.data(), scale, border_mode == BorderMode::UNDEFINED, type_pair.second);
         _border_handler->configure(compile_context, input, _kernel_hor->border_size(), border_mode, PixelValue(constant_border_value));
         // Allocate intermediate buffer
         _tmp.allocator()->allocate();
     }
     else
     {
         _kernel->configure(compile_context, input, output, conv, scale, border_mode == BorderMode::UNDEFINED);
         _border_handler->configure(compile_context, input, _kernel->border_size(), border_mode, PixelValue(constant_border_value));
     }
 }
operator=() [1/2]
CLConvolutionSquare& operator= (const CLConvolutionSquare< matrix_size > &) delete
Prevent instances of this class from being copied (As this class contains pointers)
operator=() [2/2]
CLConvolutionSquare& operator= (CLConvolutionSquare< matrix_size > &&) default
Default move assignment operator.
run()
void run () override virtual
Run the kernels contained in the function.
For Neon kernels:
Multi-threading is used for the kernels which are parallelisable.
By default std::thread::hardware_concurrency() threads are used.
Note
CPPScheduler::set_num_threads() can be used to manually set the number of threads
For OpenCL kernels:
All the kernels are enqueued on the queue associated with CLScheduler.
The queue is then flushed.
Note
The function will not block until the kernels are executed. It is the user's responsibility to wait.
Will call prepare() on first run if hasn't been done
Implements IFunction.
Definition at line 110 of file CLConvolution.cpp.
References CLScheduler::enqueue(), and CLScheduler::get().
 {
     CLScheduler::get().enqueue(*_border_handler);
     if(_is_separable)
     {
         MemoryGroupResourceScope scope_mg(_memory_group);
         CLScheduler::get().enqueue(*_kernel_hor, false);
         CLScheduler::get().enqueue(*_kernel_vert);
     }
     else
     {
         CLScheduler::get().enqueue(*_kernel);
     }
 }
The documentation for this class was generated from the following files:
arm_compute/runtime/CL/functions/CLConvolution.h
src/runtime/CL/functions/CLConvolution.cpp