Compute Library: StridedSliceLayerInfo Class Reference
StridedSliceLayerInfo Class Reference
#include <Types.h>
Public Member Functions
StridedSliceLayerInfo (int32_t begin_mask=0, int32_t end_mask=0, int32_t shrink_axis_mask=0)
Default Constructor.
int32_t begin_mask () const
int32_t end_mask () const
int32_t shrink_axis_mask () const
Detailed Description
Definition at line 1726 of file Types.h.
Constructor & Destructor Documentation
StridedSliceLayerInfo()
StridedSliceLayerInfo (int32_t begin_mask = 0, int32_t end_mask = 0, int32_t shrink_axis_mask = 0) inline
Default Constructor.
Parameters
[in] begin_mask (Optional) If the ith bit of begin_mask is set, starts[i] is ignored and the fullest possible range in that dimension is used instead.
[in] end_mask (Optional) If the ith bit of end_mask is set, ends[i] is ignored and the fullest possible range in that dimension is used instead.
[in] shrink_axis_mask (Optional) If the ith bit of shrink_axis_mask is set, it implies that the ith specification shrinks the dimensionality by 1.
Definition at line 1735 of file Types.h.
         : _begin_mask(begin_mask), _end_mask(end_mask), _shrink_axis_mask(shrink_axis_mask)
     {
     }
Member Function Documentation
begin_mask()
int32_t begin_mask () const inline
Definition at line 1741 of file Types.h.
Referenced by StridedSliceLayerNode::compute_output_descriptor(), arm_compute::graph::backends::detail::create_strided_slice_layer(), and arm_compute::graph::backends::detail::validate_strided_slice_layer().
     {
         return _begin_mask;
     }
end_mask()
int32_t end_mask () const inline
Definition at line 1747 of file Types.h.
Referenced by StridedSliceLayerNode::compute_output_descriptor(), arm_compute::graph::backends::detail::create_strided_slice_layer(), and arm_compute::graph::backends::detail::validate_strided_slice_layer().
     {
         return _end_mask;
     }
shrink_axis_mask()
int32_t shrink_axis_mask () const inline
Definition at line 1753 of file Types.h.
Referenced by StridedSliceLayerNode::compute_output_descriptor(), arm_compute::graph::backends::detail::create_strided_slice_layer(), and arm_compute::graph::backends::detail::validate_strided_slice_layer().
     {
         return _shrink_axis_mask;
     }
The documentation for this class was generated from the following file:
arm_compute/core/Types.h