Compute Library: NormalizationLayerInfo Class Reference
NormalizationLayerInfo Class Reference
Normalization Layer Information class.
#include <Types.h>
Public Member Functions
NormalizationLayerInfo (NormType type, uint32_t norm_size=5, float alpha=0.0001f, float beta=0.5f, float kappa=1.f, bool is_scaled=true)
Default Constructor.
NormType type () const
Get the normalization type.
uint32_t norm_size () const
Get the normalization size.
float alpha () const
Get the alpha value.
float beta () const
Get the beta value.
float kappa () const
Get the kappa value.
bool is_scaled () const
Get the is_scaled value.
bool is_cross_map () const
Check if normalization is cross map.
bool is_in_map () const
Check if normalization is not cross map.
float scale_coeff () const
Return the scaling factor of the normalization function.
Detailed Description
Normalization Layer Information class.
Definition at line 1647 of file Types.h.
Constructor & Destructor Documentation
NormalizationLayerInfo()
NormalizationLayerInfo (NormType type, uint32_t norm_size = 5, float alpha = 0.0001f, float beta = 0.5f, float kappa = 1.f, bool is_scaled = true) inline
Default Constructor.
Parameters
[in] type The normalization type. Can be NormType::IN_MAP_1D, NormType::IN_MAP_2D or NormType::CROSS_MAP
[in] norm_size The normalization size is the number of elements to normalize across. Defaults to 5.
[in] alpha (Optional) Alpha parameter used by normalization equation. Defaults to 0.0001.
[in] beta (Optional) Beta parameter used by normalization equation. Defaults to 0.5.
[in] kappa (Optional) Kappa parameter used by [Krichevksy 2012] Across Channel Local Brightness Normalization equation.
[in] is_scaled (Optional) Boolean that specifies if alpha will be scaled by the normalization size or not. Should be false to follow [Krichevksy 2012].
Definition at line 1660 of file Types.h.
         : _type(type), _norm_size(norm_size), _alpha(alpha), _beta(beta), _kappa(kappa), _is_scaled(is_scaled)
     {
     }
Member Function Documentation
alpha()
float alpha () const inline
Get the alpha value.
Definition at line 1675 of file Types.h.
     {
         return _alpha;
     }
beta()
float beta () const inline
Get the beta value.
Definition at line 1680 of file Types.h.
Referenced by GCNormalizationLayerKernel::configure(), NENormalizationLayerKernel::configure(), CLNormalizationLayerKernel::configure(), and arm_compute::test::validation::reference::normalization_layer().
     {
         return _beta;
     }
is_cross_map()
bool is_cross_map () const inline
Check if normalization is cross map.
Definition at line 1695 of file Types.h.
References arm_compute::CROSS_MAP.
Referenced by CLNormalizationLayerKernel::configure(), and arm_compute::test::validation::reference::normalization_layer().
     {
         return _type == NormType::CROSS_MAP;
     }
is_in_map()
bool is_in_map () const inline
Check if normalization is not cross map.
Definition at line 1700 of file Types.h.
Referenced by GCNormalizationLayerKernel::configure(), CLNormalizationLayerKernel::configure(), and arm_compute::get_normalization_dimension_index().
     {
         return !is_cross_map();
     }
is_scaled()
bool is_scaled () const inline
Get the is_scaled value.
Definition at line 1690 of file Types.h.
     {
         return _is_scaled;
     }
kappa()
float kappa () const inline
Get the kappa value.
Definition at line 1685 of file Types.h.
Referenced by GCNormalizationLayerKernel::configure(), NENormalizationLayerKernel::configure(), CLNormalizationLayerKernel::configure(), and arm_compute::test::validation::reference::normalization_layer().
     {
         return _kappa;
     }
norm_size()
uint32_t norm_size () const inline
Get the normalization size.
Definition at line 1670 of file Types.h.
Referenced by GCNormalizationLayerKernel::configure(), NENormalizationLayerKernel::configure(), CLNormalizationLayerKernel::configure(), arm_compute::test::validation::reference::normalization_layer(), arm_compute::operator<<(), and arm_compute::to_string().
     {
         return _norm_size;
     }
scale_coeff()
float scale_coeff () const inline
Return the scaling factor of the normalization function.
If is_scaled is set to false then [Krichevksy 2012] normalization scaling is performed, where alpha is returned plainly, else alpha is scaled by the total number of elements used for the normalization.
Returns
The normalization scaling factor.
Definition at line 1711 of file Types.h.
References arm_compute::IN_MAP_2D.
Referenced by GCNormalizationLayerKernel::configure(), NENormalizationLayerKernel::configure(), CLNormalizationLayerKernel::configure(), and arm_compute::test::validation::reference::normalization_layer().
     {
         const uint32_t size = (_type == NormType::IN_MAP_2D) ? _norm_size * _norm_size : _norm_size;
         return (_is_scaled) ? (_alpha / size) : _alpha;
     }
type()
NormType type () const inline
Get the normalization type.
Definition at line 1665 of file Types.h.
Referenced by GCNormalizationLayerKernel::configure(), NENormalizationLayerKernel::configure(), CLNormalizationLayerKernel::configure(), arm_compute::test::validation::reference::normalization_layer(), arm_compute::operator<<(), arm_compute::to_string(), and DotGraphVisitor::visit().
     {
         return _type;
     }
The documentation for this class was generated from the following file:
arm_compute/core/Types.h