Compute Library: GCPoolingLayerKernel Class Reference
GCPoolingLayerKernel Class Reference
Interface for the pooling layer kernel.
#include <GCPoolingLayerKernel.h>
Public Member Functions
GCPoolingLayerKernel ()
Default constructor.
GCPoolingLayerKernel (const GCPoolingLayerKernel &)=delete
Prevent instances of this class from being copied (As this class contains pointers)
GCPoolingLayerKernel & operator= (const GCPoolingLayerKernel &)=delete
Prevent instances of this class from being copied (As this class contains pointers)
GCPoolingLayerKernel (GCPoolingLayerKernel &&)=default
Allow instances of this class to be moved.
GCPoolingLayerKernel & operator= (GCPoolingLayerKernel &&)=default
Allow instances of this class to be moved.
~GCPoolingLayerKernel ()=default
Default destructor.
void configure (const IGCTensor *input, IGCTensor *output, const PoolingLayerInfo &pool_info, IGCTensor *indices=nullptr)
Set the input and output tensors.
void run (const Window &window) override
Enqueue the OpenGL ES shader to process the given window.
BorderSize border_size () const override
The size of the border for that kernel.
Public Member Functions inherited from IGCKernel
IGCKernel ()
Constructor.
GCKernel & kernel ()
Returns a reference to the GLES kernel of this object.
void add_1D_tensor_argument (unsigned int &idx, const IGCTensor *tensor, const unsigned int binding_point, const Window &window)
Add the passed 1D tensor's parameters to the object's kernel's arguments starting from the index idx.
void add_2D_tensor_argument (unsigned int &idx, const IGCTensor *tensor, const unsigned int binding_point, const Window &window)
Add the passed 2D tensor's parameters to the object's kernel's arguments starting from the index idx.
void add_3D_tensor_argument (unsigned int &idx, const IGCTensor *tensor, const unsigned int binding_point, const Window &window)
Add the passed 3D tensor's parameters to the object's kernel's arguments starting from the index idx.
unsigned int num_arguments_per_1D_tensor () const
Returns the number of arguments enqueued per 1D tensor object.
unsigned int num_arguments_per_2D_tensor () const
Returns the number of arguments enqueued per 2D tensor object.
unsigned int num_arguments_per_3D_tensor () const
Returns the number of arguments enqueued per 3D tensor object.
void set_lws_hint (gles::NDRange &lws_hint)
Set the Local-Workgroup-Size hint.
void set_target (GPUTarget target)
Set the targeted GPU architecture.
GPUTarget get_target () const
Get the targeted GPU architecture.
Public Member Functions inherited from IKernel
IKernel ()
Constructor.
virtual ~IKernel ()=default
Destructor.
virtual bool is_parallelisable () const
Indicates whether or not the kernel is parallelisable.
const Window & window () const
The maximum window the kernel can be executed on.
Static Public Member Functions
static Status validate (const ITensorInfo *input, const ITensorInfo *output, const PoolingLayerInfo &pool_info, const ITensorInfo *indices=nullptr)
Static function to check if given info will lead to a valid configuration of GCPoolingLayerKernel.
Detailed Description
Interface for the pooling layer kernel.
Definition at line 36 of file GCPoolingLayerKernel.h.
Constructor & Destructor Documentation
GCPoolingLayerKernel() [1/3]
GCPoolingLayerKernel ()
Default constructor.
Definition at line 220 of file GCPoolingLayerKernel.cpp.
     : _input(nullptr), _output(nullptr), _indices(nullptr), _pool_info(), _border_size(0), _num_elems_processed_per_iteration(1)
 {
 }
GCPoolingLayerKernel() [2/3]
GCPoolingLayerKernel (const GCPoolingLayerKernel &) delete
Prevent instances of this class from being copied (As this class contains pointers)
GCPoolingLayerKernel() [3/3]
GCPoolingLayerKernel (GCPoolingLayerKernel &&) default
Allow instances of this class to be moved.
~GCPoolingLayerKernel()
~GCPoolingLayerKernel () default
Default destructor.
Member Function Documentation
border_size()
BorderSize border_size () const override virtual
The size of the border for that kernel.
Returns
The width in number of elements of the border.
Reimplemented from IKernel.
Definition at line 225 of file GCPoolingLayerKernel.cpp.
 {
     return _border_size;
 }
configure()
void configure (const IGCTensor * input, IGCTensor * output, const PoolingLayerInfo & pool_info, IGCTensor * indices = nullptr)
Set the input and output tensors.
Parameters
[in] input Source tensor. Data types supported: F16/F32.
[out] output Destination tensor. Data types supported: Same as input.
[in] pool_info Contains pooling operation information described in PoolingLayerInfo.
[out] indices (optional) The indices of the maximal values. Data type supported: U32.
Definition at line 230 of file GCPoolingLayerKernel.cpp.
References ARM_COMPUTE_ERROR_ON_NULLPTR, ARM_COMPUTE_ERROR_THROW_ON, GCKernelLibrary::create_kernel(), ITensorInfo::data_type(), ITensorInfo::dimension(), PoolingLayerInfo::exclude_padding, arm_compute::F32, GCKernelLibrary::get(), ITensor::info(), arm_compute::test::validation::input, PoolingLayerInfo::is_global_pooling, kernel_name, PadStrideInfo::pad(), PoolingLayerInfo::pad_stride_info, pool_size, PoolingLayerInfo::pool_size, PoolingLayerInfo::pool_type, arm_compute::scaled_dimensions(), PadStrideInfo::stride(), arm_compute::string_from_pooling_type(), arm_compute::support::cpp11::to_string(), arm_compute::validate_arguments(), and Size2D::width.
 {
     int                 pool_pad_x      = 0;
     int                 pool_pad_y      = 0;
     int                 pool_stride_x   = 0;
     int                 pool_stride_y   = 0;
     unsigned int        pooled_w        = 0;
     unsigned int        pooled_h        = 0;
     const PoolingType   pool_type       = pool_info.pool_type;
     int                 pool_size       = pool_info.pool_size.width;
     const PadStrideInfo pad_stride_info = pool_info.pad_stride_info;
     const bool          exclude_padding = pool_info.exclude_padding;
     std::tie(pool_pad_x, pool_pad_y)       = pad_stride_info.pad();
     std::tie(pool_stride_x, pool_stride_y) = pad_stride_info.stride();
     ARM_COMPUTE_ERROR_ON_NULLPTR(input, output);
     // Update pool size in case of global pooling
     pool_size = pool_info.is_global_pooling ? input->info()->dimension(0) : pool_size;
     // Check output dimensions
     std::tie(pooled_w, pooled_h) = scaled_dimensions(input->info()->dimension(0),
                                                      input->info()->dimension(1),
                                                      pool_size,
                                                      pool_size,
                                                      pad_stride_info);
     auto_init(input->info(), output->info(), pooled_w, pooled_h);
     ARM_COMPUTE_ERROR_THROW_ON(validate_arguments(input->info(), output->info(), pool_info, (indices) ? indices->info() : nullptr));
     // Set instance variables
     _input     = input;
     _output    = output;
     _pool_info = pool_info;
     _indices   = indices;
     // Set build options
     std::set<std::string> build_opts;
     build_opts.emplace("#define LOCAL_SIZE_X " + support::cpp11::to_string(1));
     build_opts.emplace("#define LOCAL_SIZE_Y " + support::cpp11::to_string(1));
     build_opts.emplace("#define LOCAL_SIZE_Z " + support::cpp11::to_string(1));
     if(input->info()->data_type() == DataType::F32)
     {
         build_opts.insert("#define DATA_TYPE_FP32");
     }
     else
     {
         build_opts.insert("#define DATA_TYPE_FP16");
     }
     if(exclude_padding)
     {
         build_opts.emplace("#define EXCLUDE_PADDING");
     }
     build_opts.emplace(("#define POOL_" + string_from_pooling_type(pool_type)));
     build_opts.emplace(("#define STRIDE_X " + support::cpp11::to_string(pool_stride_x)));
     build_opts.emplace(("#define MAX_WIDTH " + support::cpp11::to_string(input->info()->dimension(0) + (exclude_padding ? 0 : pool_pad_x))));
     build_opts.emplace(("#define MAX_HEIGHT " + support::cpp11::to_string(input->info()->dimension(1) + (exclude_padding ? 0 : pool_pad_y))));
     build_opts.emplace(("#define STRIDE_Y " + support::cpp11::to_string(pool_stride_y)));
     build_opts.emplace(("#define PAD_X " + support::cpp11::to_string(pool_pad_x)));
     build_opts.emplace(("#define PAD_Y " + support::cpp11::to_string(pool_pad_y)));
     // Create kernel
     if((pool_size == 2) || (pool_size == 3) || (pool_size == 7))
     {
         // Check if we have pool3x3 with stride_x less equal than 3. In these cases, run an optimized OpenGLES kernel where
         // each thread computes 4 output elements
         const bool is_pool3x3_stride_le3 = (pool_size == 3) && (pool_stride_x <= 3);
         std::string kernel_name = "pooling_layer_" + support::cpp11::to_string(pool_size);
         if(is_pool3x3_stride_le3)
         {
             build_opts.insert("#define POOLING_LAYER_3_OPTIMIZED");
             _kernel = static_cast<GCKernel>(GCKernelLibrary::get().create_kernel(kernel_name + "_optimized", build_opts));
         }
         else
         {
             build_opts.insert("#define POOLING_LAYER_" + support::cpp11::to_string(pool_size));
             _kernel = static_cast<GCKernel>(GCKernelLibrary::get().create_kernel(kernel_name, build_opts));
         }
     }
     else // Run general case
     {
         build_opts.emplace(("#define POOL_SIZE " + support::cpp11::to_string(pool_size)));
         build_opts.insert("#define POOLING_LAYER_N");
         _kernel = static_cast<GCKernel>(GCKernelLibrary::get().create_kernel("pooling_layer_n", build_opts));
     }
     // Configure kernel window
     auto win_config = validate_and_configure_window(input->info(), output->info(), pool_info);
     ARM_COMPUTE_ERROR_THROW_ON(std::get<0>(win_config));
     IGCKernel::configure(std::get<1>(win_config));
     GCPoolingConfig pooling_config     = std::get<2>(win_config);
     _num_elems_processed_per_iteration = pooling_config.first;
     _border_size                       = pooling_config.second;
 }
operator=() [1/2]
GCPoolingLayerKernel& operator= (const GCPoolingLayerKernel &) delete
Prevent instances of this class from being copied (As this class contains pointers)
operator=() [2/2]
GCPoolingLayerKernel& operator= (GCPoolingLayerKernel &&) default
Allow instances of this class to be moved.
run()
void run (const Window & window) override virtual
Enqueue the OpenGL ES shader to process the given window.
Parameters
[in] window Region on which to execute the kernel. (Must be a valid region of the window returned by window()).
Implements IGCKernel.
Definition at line 335 of file GCPoolingLayerKernel.cpp.
References IGCKernel::add_3D_tensor_argument(), ARM_COMPUTE_ERROR_ON_INVALID_SUBWINDOW, ARM_COMPUTE_ERROR_ON_UNCONFIGURED_KERNEL, Window::collapse_if_possible(), Window::DimX, Window::DimY, Window::DimZ, Window::Dimension::end(), arm_compute::enqueue(), Window::first_slice_window_3D(), ITensor::info(), PadStrideInfo::pad(), PoolingLayerInfo::pad_stride_info, ITensorInfo::padding(), pool_stride_x, Window::set(), IGCTensor::set_needs_shifting(), Window::shift(), arm_compute::test::validation::reference::slice(), Window::slide_window_slice_3D(), Window::Dimension::start(), PadStrideInfo::stride(), IKernel::window(), Window::x(), and Window::y().
 {
     ARM_COMPUTE_ERROR_ON_UNCONFIGURED_KERNEL(this);
     ARM_COMPUTE_ERROR_ON_INVALID_SUBWINDOW(IKernel::window(), window);
     unsigned int pool_pad_x;
     unsigned int pool_pad_y;
     unsigned int pool_stride_x;
     unsigned int pool_stride_y;
     std::tie(pool_pad_x, pool_pad_y)       = _pool_info.pad_stride_info.pad();
     std::tie(pool_stride_x, pool_stride_y) = _pool_info.pad_stride_info.stride();
     _kernel.use();
     _output->set_needs_shifting(true);
     Window window_collapsed = window.collapse_if_possible(IGCKernel::window(), Window::DimZ);
     Window slice         = window_collapsed.first_slice_window_3D();
     Window slice_in_orig = window_collapsed.first_slice_window_3D();
     slice.shift(Window::DimX, -(_output->info()->padding()).left);
     do
     {
         // Upsample input by pool size
         Window in_slice(slice_in_orig); // NOLINT
         in_slice.set(Window::DimX, Window::Dimension(in_slice.x().start() - pool_pad_x, in_slice.x().end() * pool_stride_x, pool_stride_x * _num_elems_processed_per_iteration));
         in_slice.set(Window::DimY, Window::Dimension(in_slice.y().start() - pool_pad_y, in_slice.y().end() * pool_stride_y, pool_stride_y));
         // Set inputs
         unsigned int idx = 0;
         add_3D_tensor_argument(idx, _input, 1, in_slice);
         add_3D_tensor_argument(idx, _output, 2, slice);
         _kernel.update_shader_params();
         enqueue(*this, slice);
     }
     while(window_collapsed.slide_window_slice_3D(slice) && window_collapsed.slide_window_slice_3D(slice_in_orig));
 }
validate()
Status validate (const ITensorInfo * input, const ITensorInfo * output, const PoolingLayerInfo & pool_info, const ITensorInfo * indices = nullptr) static
Static function to check if given info will lead to a valid configuration of GCPoolingLayerKernel.
Parameters
[in] input Source tensor info. Data types supported: F16/F32.
[in] output Destination tensor info. Data types supported: Same as input.
[in] pool_info Contains pooling operation information described in PoolingLayerInfo.
[in] indices (optional) The indices of the maximal values. Data type supported: U32.
Returns
a status
Definition at line 327 of file GCPoolingLayerKernel.cpp.
References ARM_COMPUTE_RETURN_ON_ERROR, ICloneable< T >::clone(), and arm_compute::validate_arguments().
Referenced by GCPoolingLayer::validate().
 {
     ARM_COMPUTE_RETURN_ON_ERROR(validate_arguments(input, output, pool_info, indices));
     ARM_COMPUTE_RETURN_ON_ERROR(std::get<0>(validate_and_configure_window(input->clone().get(), output->clone().get(), pool_info)));
     return Status{};
 }
The documentation for this class was generated from the following files:
arm_compute/core/GLES_COMPUTE/kernels/GCPoolingLayerKernel.h
src/core/GLES_COMPUTE/kernels/GCPoolingLayerKernel.cpp