Compute Library: NESeparableConvolutionHorKernel< matrix_size > Class Template Reference
NESeparableConvolutionHorKernel< matrix_size > Class Template Reference
Kernel for the Horizontal pass of a Separable Convolution.
#include <NEConvolution.h>
Public Member Functions
const char * name () const override
Name of the kernel.
NESeparableConvolutionHorKernel ()
Default constructor.
NESeparableConvolutionHorKernel (const NESeparableConvolutionHorKernel &)=delete
Prevent instances of this class from being copied (As this class contains pointers).
NESeparableConvolutionHorKernel & operator= (const NESeparableConvolutionHorKernel &)=delete
Prevent instances of this class from being copied (As this class contains pointers).
NESeparableConvolutionHorKernel (NESeparableConvolutionHorKernel &&)=default
Allow instances of this class to be moved.
NESeparableConvolutionHorKernel & operator= (NESeparableConvolutionHorKernel &&)=default
Allow instances of this class to be moved.
~NESeparableConvolutionHorKernel ()=default
Default destructor.
void configure (const ITensor *input, ITensor *output, const int16_t *conv_row, bool border_undefined)
Initialise the kernel's input, output and border mode.
void run (const Window &window, const ThreadInfo &info) override
Execute the kernel on the passed window.
BorderSize border_size () const override
The size of the border for that kernel.
Public Member Functions inherited from ICPPSimpleKernel
ICPPSimpleKernel ()
Constructor.
ICPPSimpleKernel (const ICPPSimpleKernel &)=delete
Prevent instances of this class from being copied (As this class contains pointers)
ICPPSimpleKernel & operator= (const ICPPSimpleKernel &)=delete
Prevent instances of this class from being copied (As this class contains pointers)
ICPPSimpleKernel (ICPPSimpleKernel &&)=default
Allow instances of this class to be moved.
ICPPSimpleKernel & operator= (ICPPSimpleKernel &&)=default
Allow instances of this class to be moved.
~ICPPSimpleKernel ()=default
Default destructor.
Public Member Functions inherited from ICPPKernel
virtual ~ICPPKernel ()=default
Default destructor.
virtual void run_nd (const Window &window, const ThreadInfo &info, const Window &thread_locator)
legacy compatibility layer for implemantions which do not support thread_locator In these cases we simply narrow the interface down the legacy version
virtual void run_op (ITensorPack &tensors, const Window &window, const ThreadInfo &info)
Execute the kernel on the passed window.
Public Member Functions inherited from IKernel
IKernel ()
Constructor.
virtual ~IKernel ()=default
Destructor.
virtual bool is_parallelisable () const
Indicates whether or not the kernel is parallelisable.
const Window & window () const
The maximum window the kernel can be executed on.
Detailed Description
template<unsigned int matrix_size>
class arm_compute::NESeparableConvolutionHorKernel< matrix_size >
Kernel for the Horizontal pass of a Separable Convolution.
Definition at line 44 of file NEConvolution.h.
Constructor & Destructor Documentation
NESeparableConvolutionHorKernel() [1/3]
NESeparableConvolutionHorKernel ()
Default constructor.
Definition at line 656 of file NEConvolutionKernel.cpp.
     : _conv_row{ { 0 } }, _border_size(0)
 {
 }
NESeparableConvolutionHorKernel() [2/3]
NESeparableConvolutionHorKernel (const NESeparableConvolutionHorKernel< matrix_size > &) delete
Prevent instances of this class from being copied (As this class contains pointers).
NESeparableConvolutionHorKernel() [3/3]
NESeparableConvolutionHorKernel (NESeparableConvolutionHorKernel< matrix_size > &&) default
Allow instances of this class to be moved.
~NESeparableConvolutionHorKernel()
~NESeparableConvolutionHorKernel () default
Default destructor.
Member Function Documentation
border_size()
BorderSize border_size () const override virtual
The size of the border for that kernel.
Returns
The width in number of elements of the border.
Reimplemented from IKernel.
Definition at line 662 of file NEConvolutionKernel.cpp.
Referenced by NESeparableConvolutionHorKernel< matrix_size >::configure().
 {
     return _border_size;
 }
configure()
void configure (const ITensor * input, ITensor * output, const int16_t * conv_row, bool border_undefined)
Initialise the kernel's input, output and border mode.
Parameters
[in] input Source tensor. Data type supported: U8.
[out] output Destination tensor. Data types supported: U16, S16, S32.
[in] conv_row Convolution matrix to apply to the input tensor.
[in] border_undefined True if the border mode is undefined. False if it's replicate or constant.
Definition at line 668 of file NEConvolutionKernel.cpp.
References ARM_COMPUTE_ERROR_ON_DATA_TYPE_CHANNEL_NOT_IN, ARM_COMPUTE_ERROR_ON_MISMATCHING_SHAPES, ARM_COMPUTE_ERROR_ON_NULLPTR, NESeparableConvolutionHorKernel< matrix_size >::border_size(), arm_compute::calculate_max_window_horizontal(), ITensor::info(), arm_compute::test::validation::input, BorderSize::left, num_elems_processed_per_iteration, arm_compute::S16, arm_compute::S32, arm_compute::set_shape_if_empty(), ITensorInfo::tensor_shape(), arm_compute::U16, arm_compute::U8, arm_compute::update_window_and_padding(), and ITensorInfo::valid_region().
 {
     ARM_COMPUTE_ERROR_ON_NULLPTR(input, output, conv_row);
     set_shape_if_empty(*output->info(), input->info()->tensor_shape());
     ARM_COMPUTE_ERROR_ON_MISMATCHING_SHAPES(input, output);
     ARM_COMPUTE_ERROR_ON_DATA_TYPE_CHANNEL_NOT_IN(input, 1, DataType::U8);
     ARM_COMPUTE_ERROR_ON_DATA_TYPE_CHANNEL_NOT_IN(output, 1, DataType::U16, DataType::S16, DataType::S32);
     _input  = input;
     _output = output;
     std::copy_n(conv_row, _conv_row.size(), _conv_row.begin());
     _border_size = BorderSize(border_undefined ? 0 : matrix_size / 2, matrix_size / 2);
     // Configure kernel window
     constexpr unsigned int num_elems_processed_per_iteration = 8;
     constexpr unsigned int num_elems_read_per_iteration      = 16;
     constexpr unsigned int num_elems_written_per_iteration   = 8;
     Window                 win = calculate_max_window_horizontal(*input->info(), Steps(num_elems_processed_per_iteration), border_undefined, border_size());
     AccessWindowHorizontal output_access(output->info(), 0, num_elems_written_per_iteration);
     update_window_and_padding(win,
                               AccessWindowHorizontal(input->info(), -border_size().left, num_elems_read_per_iteration),
                               output_access);
     output_access.set_valid_region(win, input->info()->valid_region(), border_undefined, border_size());
     INEKernel::configure(win);
 }
name()
const char* name () const inline override virtual
Name of the kernel.
Returns
Kernel name
Implements ICPPKernel.
Definition at line 115 of file NEConvolutionKernel.h.
References NEConvolutionKernel< matrix_size >::border_size(), NEConvolutionKernel< matrix_size >::configure(), arm_compute::test::validation::info, arm_compute::test::validation::input, NEConvolutionKernel< matrix_size >::operator=(), NEConvolutionKernel< matrix_size >::run(), and IKernel::window().
     {
         return "NESeparableConvolutionHorKernel";
     }
operator=() [1/2]
NESeparableConvolutionHorKernel& operator= (const NESeparableConvolutionHorKernel< matrix_size > &) delete
Prevent instances of this class from being copied (As this class contains pointers).
operator=() [2/2]
NESeparableConvolutionHorKernel& operator= (NESeparableConvolutionHorKernel< matrix_size > &&) default
Allow instances of this class to be moved.
run()
void run (const Window & window, const ThreadInfo & info) override virtual
Execute the kernel on the passed window.
Warning
If is_parallelisable() returns false then the passed window must be equal to window()
Note
The window has to be a region within the window returned by the window() method
The width of the window has to be a multiple of num_elems_processed_per_iteration().
Parameters
[in] window Region on which to execute the kernel. (Must be a region of the window returned by window())
[in] info Info about executing thread and CPU.
Reimplemented from ICPPKernel.
Definition at line 701 of file NEConvolutionKernel.cpp.
References ARM_COMPUTE_ERROR, ARM_COMPUTE_ERROR_ON_INVALID_SUBWINDOW, ARM_COMPUTE_ERROR_ON_UNCONFIGURED_KERNEL, ARM_COMPUTE_UNUSED, Window::DimX, arm_compute::execute_window_loop(), arm_compute::test::validation::input, Iterator::ptr(), arm_compute::S16, arm_compute::S32, Window::shift(), arm_compute::U16, and IKernel::window().
 {
     ARM_COMPUTE_UNUSED(info);
     ARM_COMPUTE_ERROR_ON_UNCONFIGURED_KERNEL(this);
     ARM_COMPUTE_ERROR_ON_INVALID_SUBWINDOW(INEKernel::window(), window);
     switch(_output->info()->data_type())
     {
         case DataType::U16:
             convolve<uint16_t>(window);
             break;
         case DataType::S16:
             convolve<int16_t>(window);
             break;
         case DataType::S32:
             convolve<int32_t>(window);
             break;
         default:
             ARM_COMPUTE_ERROR("Unsupported intermediate data type!");
             break;
     }
 }
The documentation for this class was generated from the following files:
arm_compute/runtime/NEON/functions/NEConvolution.h
src/core/NEON/kernels/NEConvolutionKernel.h
src/core/NEON/kernels/NEConvolutionKernel.cpp