Compute Library: GCKernelLibrary Class Reference
GCKernelLibrary Class Reference final
GCKernelLibrary class.
#include <GCKernelLibrary.h>
Public Member Functions
GCKernelLibrary ()
Default Constructor.
~GCKernelLibrary ()
Default Destructor.
GCKernelLibrary (const GCKernelLibrary &)=delete
Prevent instances of this class from being copied.
const GCKernelLibrary & operator= (const GCKernelLibrary &)=delete
Prevent instances of this class from being copied.
void init (std::string shader_path="./", EGLDisplay dpy=EGL_NO_DISPLAY, EGLContext ctx=EGL_NO_CONTEXT)
Initialises the kernel library.
void set_shader_path (const std::string &shader_path)
Sets the path that the shaders reside in.
void set_context (EGLDisplay dpy, EGLContext ctx)
Sets display and context to create kernel.
GCKernel create_kernel (const std::string &shader_name, const StringSet &build_options_set={}) const
Creates a kernel from the kernel library.
void save_binary ()
Serializes and saves programs to a binary.
void load_binary ()
Load serialized binary with all the programs.
void setup_dummy_fbo ()
Setup a dummy fbo to workaround an issue on Galaxy S8.
Static Public Member Functions
static GCKernelLibrary & get ()
Get the static instance of GCKernelLibrary.
Detailed Description
GCKernelLibrary class.
Definition at line 187 of file GCKernelLibrary.h.
Constructor & Destructor Documentation
GCKernelLibrary() [1/2]
GCKernelLibrary ()
Default Constructor.
Definition at line 328 of file GCKernelLibrary.cpp.
     : _display(EGL_NO_DISPLAY), _context(EGL_NO_CONTEXT), _frame_buffer(0), _tex_rt(0), _shader_path("./"), _programs_map(), _built_programs_map()
 {
 }
~GCKernelLibrary()
~GCKernelLibrary ()
Default Destructor.
Definition at line 535 of file GCKernelLibrary.cpp.
References ARM_COMPUTE_GL_CHECK, glBindFramebuffer(), glBindTexture(), glDeleteFramebuffers(), and glDeleteTextures().
 {
     for(auto &program : _built_programs_map)
     {
         static_cast<GCKernel>(program.second).cleanup();
     }
     ARM_COMPUTE_GL_CHECK(glBindTexture(GL_TEXTURE_2D, 0));
     ARM_COMPUTE_GL_CHECK(glBindFramebuffer(GL_FRAMEBUFFER, 0));
     ARM_COMPUTE_GL_CHECK(glDeleteTextures(1, &_tex_rt));
     ARM_COMPUTE_GL_CHECK(glDeleteFramebuffers(1, &_frame_buffer));
 }
GCKernelLibrary() [2/2]
GCKernelLibrary (const GCKernelLibrary &) delete
Prevent instances of this class from being copied.
Member Function Documentation
create_kernel()
GCKernel create_kernel (const std::string & shader_name, const StringSet & build_options_set = {}) const
Creates a kernel from the kernel library.
Parameters
[in] shader_name Shader name.
[in] build_options_set Shader build options as a set.
Returns
The created kernel.
Definition at line 366 of file GCKernelLibrary.cpp.
References ARM_COMPUTE_ERROR_VAR, build_options, GCKernel::clear_arguments(), GCProgram::compile_shader(), arm_compute::test::validation::dst, GCProgram::link_program(), arm_compute::read_file(), GCKernel::set_shader_params_binding_point(), arm_compute::test::validation::src, and GCKernel::use().
Referenced by GCLogits1DMaxKernel::configure(), GCScaleKernel::configure(), GCTransposeKernel::configure(), GCGEMMMatrixAccumulateBiasesKernel::configure(), GCPixelWiseMultiplicationKernel::configure(), GCDepthwiseConvolutionLayer3x3Kernel::configure(), GCFillBorderKernel::configure(), GCNormalizationLayerKernel::configure(), GCPoolingLayerKernel::configure(), GCGEMMMatrixAdditionKernel::configure(), GCNormalizePlanarYUVLayerKernel::configure(), GCAbsoluteDifferenceKernel::configure(), GCArithmeticAdditionKernel::configure(), GCGEMMTranspose1xWKernel::configure(), GCDirectConvolutionLayerKernel< kernel_size >::configure(), GCBatchNormalizationLayerKernel::configure(), GCDepthConcatenateLayerKernel::configure(), GCDropoutLayerKernel::configure(), GCLogits1DShiftExpSumKernel::configure(), GCGEMMMatrixMultiplyKernel::configure(), GCGEMMInterleave4x4Kernel::configure(), GCTensorShiftKernel::configure(), GCWeightsReshapeKernel::configure(), GCCol2ImKernel::configure(), GCIm2ColKernel::configure(), GCLogits1DNormKernel::configure(), and arm_compute::create_opengl_kernel().
 {
     // Find which program contains the kernel
     auto shader_program_it = _shader_program_map.find(shader_name);
     if(_shader_program_map.end() == shader_program_it)
     {
         ARM_COMPUTE_ERROR_VAR("Shader %s not found in the GCKernelLibrary", shader_name.c_str());
     }
     // Check if the program has been built before with same build options.
     const std::string program_name       = shader_program_it->second;
     const std::string build_options      = stringify_set(build_options_set);
     const std::string built_program_name = program_name + "_" + build_options;
     auto              built_program_it   = _built_programs_map.find(built_program_name);
     GCKernel kernel;
     if(_built_programs_map.end() != built_program_it)
     {
         // If program has been built, retrieve to create kernel from it
         kernel = built_program_it->second;
     }
     else
     {
         GCProgram program = load_program(program_name);
         std::string source_name = _shader_path + shader_program_it->second;
         // load shader
         GLuint shader = program.compile_shader(build_options);
         // Build program
         GLuint gles_program = program.link_program(shader);
         // Create GCKernel
         kernel = GCKernel(shader_name, gles_program);
         // Add built program to internal map
         _built_programs_map.emplace(built_program_name, kernel);
     }
     kernel.use();
     kernel.clear_arguments();
     // set shader params binding point
     kernel.set_shader_params_binding_point(0);
     return kernel;
 }
get()
GCKernelLibrary & get () static
Get the static instance of GCKernelLibrary.
This method has been deprecated and will be removed in future releases.
Returns
The static instance of GCKernelLibrary.
Definition at line 333 of file GCKernelLibrary.cpp.
Referenced by GCLogits1DMaxKernel::configure(), GCScaleKernel::configure(), GCTransposeKernel::configure(), GCGEMMMatrixAccumulateBiasesKernel::configure(), GCPixelWiseMultiplicationKernel::configure(), GCDepthwiseConvolutionLayer3x3Kernel::configure(), GCFillBorderKernel::configure(), GCNormalizationLayerKernel::configure(), GCPoolingLayerKernel::configure(), GCGEMMMatrixAdditionKernel::configure(), GCNormalizePlanarYUVLayerKernel::configure(), GCAbsoluteDifferenceKernel::configure(), GCArithmeticAdditionKernel::configure(), GCGEMMTranspose1xWKernel::configure(), GCDirectConvolutionLayerKernel< kernel_size >::configure(), GCBatchNormalizationLayerKernel::configure(), GCDepthConcatenateLayerKernel::configure(), GCDropoutLayerKernel::configure(), GCLogits1DShiftExpSumKernel::configure(), GCGEMMMatrixMultiplyKernel::configure(), GCGEMMInterleave4x4Kernel::configure(), GCTensorShiftKernel::configure(), GCWeightsReshapeKernel::configure(), GCCol2ImKernel::configure(), GCIm2ColKernel::configure(), GCLogits1DNormKernel::configure(), arm_compute::create_opengl_kernel(), and GCScheduler::init().
 {
     static GCKernelLibrary _kernel_library;
     return _kernel_library;
 }
init()
void init (std::string shader_path = "./", EGLDisplay dpy = EGL_NO_DISPLAY, EGLContext ctx = EGL_NO_CONTEXT)
Initialises the kernel library.
Parameters
[in] shader_path (Optional) Path of the directory from which shader sources are loaded.
[in] dpy (Optional) EGLdisplay set by external application.
[in] ctx (Optional) EGLContext set by external application.
Definition at line 339 of file GCKernelLibrary.cpp.
References eglMakeCurrent(), and GCKernelLibrary::setup_dummy_fbo().
Referenced by GCRuntimeContext::GCRuntimeContext(), and GCScheduler::init().
 {
     //TODO: deal with old display and context.
     _shader_path = std::move(shader_path);
     _display = dpy;
     _context = ctx;
     eglMakeCurrent(_display, EGL_NO_SURFACE, EGL_NO_SURFACE, _context);
     setup_dummy_fbo();
 }
load_binary()
void load_binary ()
Load serialized binary with all the programs.
operator=()
const GCKernelLibrary& operator= (const GCKernelLibrary &) delete
Prevent instances of this class from being copied.
save_binary()
void save_binary ()
Serializes and saves programs to a binary.
set_context()
void set_context (EGLDisplay dpy, EGLContext ctx)
Sets display and context to create kernel.
Parameters
[in] dpy EGLdisplay set by external application.
[in] ctx EGLContext set by external application.
Definition at line 356 of file GCKernelLibrary.cpp.
References eglMakeCurrent(), and GCKernelLibrary::setup_dummy_fbo().
 {
     //TODO: deal with old display and context.
     _display = dpy;
     _context = ctx;
     eglMakeCurrent(dpy, EGL_NO_SURFACE, EGL_NO_SURFACE, ctx);
     setup_dummy_fbo();
 }
set_shader_path()
void set_shader_path (const std::string & shader_path)
Sets the path that the shaders reside in.
Parameters
[in] shader_path Path of the shader.
Definition at line 351 of file GCKernelLibrary.cpp.
 {
     _shader_path = shader_path;
 }
setup_dummy_fbo()
void setup_dummy_fbo ()
Setup a dummy fbo to workaround an issue on Galaxy S8.
Definition at line 525 of file GCKernelLibrary.cpp.
References ARM_COMPUTE_GL_CHECK, glBindFramebuffer(), glBindTexture(), glFramebufferTexture2D(), glGenFramebuffers(), glGenTextures(), and glTexImage2D().
Referenced by GCKernelLibrary::init(), and GCKernelLibrary::set_context().
 {
     ARM_COMPUTE_GL_CHECK(glGenFramebuffers(1, &_frame_buffer));
     ARM_COMPUTE_GL_CHECK(glBindFramebuffer(GL_FRAMEBUFFER, _frame_buffer));
     ARM_COMPUTE_GL_CHECK(glGenTextures(1, &_tex_rt));
     ARM_COMPUTE_GL_CHECK(glBindTexture(GL_TEXTURE_2D, _tex_rt));
     ARM_COMPUTE_GL_CHECK(glTexImage2D(GL_TEXTURE_2D, 0, GL_RGB, 1, 1, 0, GL_RGB, GL_UNSIGNED_BYTE, nullptr));
     ARM_COMPUTE_GL_CHECK(glFramebufferTexture2D(GL_FRAMEBUFFER, GL_COLOR_ATTACHMENT0, GL_TEXTURE_2D, _tex_rt, 0));
 }
The documentation for this class was generated from the following files:
arm_compute/core/GLES_COMPUTE/GCKernelLibrary.h
src/core/GLES_COMPUTE/GCKernelLibrary.cpp