Compute Library: CLSpaceToBatchLayer Class Reference
CLSpaceToBatchLayer Class Reference
Basic function to spatial divide a tensor.
#include <CLSpaceToBatchLayer.h>
Public Member Functions
CLSpaceToBatchLayer ()
Default constructor.
CLSpaceToBatchLayer (const CLSpaceToBatchLayer &)=delete
Prevent instances of this class from being copied (As this class contains pointers)
CLSpaceToBatchLayer & operator= (const CLSpaceToBatchLayer &)=delete
Prevent instances of this class from being copied (As this class contains pointers)
CLSpaceToBatchLayer (CLSpaceToBatchLayer &&)=default
Allow instances of this class to be moved.
CLSpaceToBatchLayer & operator= (CLSpaceToBatchLayer &&)=default
Allow instances of this class to be moved.
~CLSpaceToBatchLayer ()
Default destructor.
void configure (const ICLTensor *input, const ICLTensor *block_shape, const ICLTensor *paddings, ICLTensor *output)
Set the input and output tensors.
void configure (const CLCompileContext &compile_context, const ICLTensor *input, const ICLTensor *block_shape, const ICLTensor *paddings, ICLTensor *output)
Set the input and output tensors.
void configure (const ICLTensor *input, const int block_shape_x, const int block_shape_y, const Size2D &padding_left, const Size2D &padding_right, ICLTensor *output)
Set the input and output tensors.
void configure (const CLCompileContext &compile_context, const ICLTensor *input, const int block_shape_x, const int block_shape_y, const Size2D &padding_left, const Size2D &padding_right, ICLTensor *output)
Set the input and output tensors.
void run () override
Run the kernels contained in the function.
Public Member Functions inherited from IFunction
virtual ~IFunction ()=default
Destructor.
virtual void prepare ()
Prepare the function for executing.
Static Public Member Functions
static Status validate (const ITensorInfo *input, const ITensorInfo *block_shape, const ITensorInfo *paddings, const ITensorInfo *output)
Static function to check if given info will lead to a valid configuration of CLSpaceToBatchLayer.
static Status validate (const ITensorInfo *input, const int block_shape_x, const int block_shape_y, const Size2D &padding_left, const Size2D &padding_right, const ITensorInfo *output)
Static function to check if given info will lead to a valid configuration of CLSpaceToBatchLayer (Static block shape and paddings)
Detailed Description
Basic function to spatial divide a tensor.
This function calls the following OpenCL kernels/functions:
CLFill
CLSpaceToBatchLayerKernel
Definition at line 46 of file CLSpaceToBatchLayer.h.
Constructor & Destructor Documentation
CLSpaceToBatchLayer() [1/3]
CLSpaceToBatchLayer ()
Default constructor.
Definition at line 36 of file CLSpaceToBatchLayer.cpp.
References CLSpaceToBatchLayer::~CLSpaceToBatchLayer().
     : _space_to_batch_kernel(std::make_unique<CLSpaceToBatchLayerKernel>()),
       _fill(),
       _has_padding(false)
 {
 }
CLSpaceToBatchLayer() [2/3]
CLSpaceToBatchLayer (const CLSpaceToBatchLayer &) delete
Prevent instances of this class from being copied (As this class contains pointers)
CLSpaceToBatchLayer() [3/3]
CLSpaceToBatchLayer (CLSpaceToBatchLayer &&) default
Allow instances of this class to be moved.
~CLSpaceToBatchLayer()
~CLSpaceToBatchLayer () default
Default destructor.
Referenced by CLSpaceToBatchLayer::CLSpaceToBatchLayer().
Member Function Documentation
configure() [1/4]
void configure (const ICLTensor * input, const ICLTensor * block_shape, const ICLTensor * paddings, ICLTensor * output)
Set the input and output tensors.
Parameters
[in] input Tensor input. Supported tensor rank: 4. Data types supported: All.
[in] block_shape 1-D tensor with shape [M]. Supported M: 2. Data types supported: S32
[in] paddings 2-D tensor with shape [2, M] (First dimension is the fastest-changing dimension). Supported M: 2. Data types supported: S32
[out] output Tensor output. Data types supported: same as input
Definition at line 45 of file CLSpaceToBatchLayer.cpp.
References CLKernelLibrary::get().
Referenced by CLSpaceToBatchLayer::configure().
 {
     configure(CLKernelLibrary::get().get_compile_context(), input, block_shape, paddings, output);
 }
configure() [2/4]
void configure (const CLCompileContext & compile_context, const ICLTensor * input, const ICLTensor * block_shape, const ICLTensor * paddings, ICLTensor * output)
Set the input and output tensors.
Parameters
[in] compile_context The compile context to be used.
[in] input Tensor input. Supported tensor rank: 4. Data types supported: All.
[in] block_shape 1-D tensor with shape [M]. Supported M: 2. Data types supported: S32
[in] paddings 2-D tensor with shape [2, M] (First dimension is the fastest-changing dimension). Supported M: 2. Data types supported: S32
[out] output Tensor output. Data types supported: same as input
Definition at line 50 of file CLSpaceToBatchLayer.cpp.
References ARM_COMPUTE_ERROR_ON_NULLPTR, CLFill::configure(), ITensorInfo::data_type(), ITensor::info(), ITensorInfo::quantization_info(), ITensorInfo::tensor_shape(), and TensorShape::total_size().
 {
     ARM_COMPUTE_ERROR_ON_NULLPTR(input, block_shape, paddings, output);
     if(input->info()->tensor_shape().total_size() != output->info()->tensor_shape().total_size())
     {
         _has_padding = true;
         _fill.configure(compile_context, output, PixelValue(0, input->info()->data_type(), input->info()->quantization_info()));
     }
     _space_to_batch_kernel->configure(compile_context, input, block_shape, paddings, output);
 }
configure() [3/4]
void configure (const ICLTensor * input, const int block_shape_x, const int block_shape_y, const Size2D & padding_left, const Size2D & padding_right, ICLTensor * output)
Set the input and output tensors.
(Static block shape and paddings)
Parameters
[in] input Tensor input. Supported tensor rank: 4. Data types supported: All.
[in] block_shape_x Block shape x value.
[in] block_shape_y Block shape y value.
[in] padding_left The padding at the beginning of every dimension of the output tensor.
[in] padding_right The padding at the end of every dimension of the output tensor.
[out] output Tensor output. Data types supported: same as input
Definition at line 62 of file CLSpaceToBatchLayer.cpp.
References CLSpaceToBatchLayer::configure(), and CLKernelLibrary::get().
 {
     configure(CLKernelLibrary::get().get_compile_context(), input, block_shape_x, block_shape_y, padding_left, padding_right, output);
 }
configure() [4/4]
void configure (const CLCompileContext & compile_context, const ICLTensor * input, const int block_shape_x, const int block_shape_y, const Size2D & padding_left, const Size2D & padding_right, ICLTensor * output)
Set the input and output tensors.
(Static block shape and paddings)
Parameters
[in] compile_context The compile context to be used.
[in] input Tensor input. Supported tensor rank: 4. Data types supported: All.
[in] block_shape_x Block shape x value.
[in] block_shape_y Block shape y value.
[in] padding_left The padding at the beginning of every dimension of the output tensor.
[in] padding_right The padding at the end of every dimension of the output tensor.
[out] output Tensor output. Data types supported: same as input
Definition at line 67 of file CLSpaceToBatchLayer.cpp.
References ARM_COMPUTE_ERROR_ON_NULLPTR, CLFill::configure(), ITensorInfo::data_type(), ITensor::info(), ITensorInfo::quantization_info(), ITensorInfo::tensor_shape(), and TensorShape::total_size().
 {
     ARM_COMPUTE_ERROR_ON_NULLPTR(input, output);
     if(input->info()->tensor_shape().total_size() != output->info()->tensor_shape().total_size())
     {
         _has_padding = true;
         _fill.configure(compile_context, output, PixelValue(0, input->info()->data_type(), input->info()->quantization_info()));
     }
     _space_to_batch_kernel->configure(compile_context, input, block_shape_x, block_shape_y, padding_left, padding_right, output);
 }
operator=() [1/2]
CLSpaceToBatchLayer& operator= (const CLSpaceToBatchLayer &) delete
Prevent instances of this class from being copied (As this class contains pointers)
operator=() [2/2]
CLSpaceToBatchLayer& operator= (CLSpaceToBatchLayer &&) default
Allow instances of this class to be moved.
run()
void run () override virtual
Run the kernels contained in the function.
For Neon kernels:
Multi-threading is used for the kernels which are parallelisable.
By default std::thread::hardware_concurrency() threads are used.
Note
CPPScheduler::set_num_threads() can be used to manually set the number of threads
For OpenCL kernels:
All the kernels are enqueued on the queue associated with CLScheduler.
The queue is then flushed.
Note
The function will not block until the kernels are executed. It is the user's responsibility to wait.
Will call prepare() on first run if hasn't been done
Implements IFunction.
Definition at line 97 of file CLSpaceToBatchLayer.cpp.
References CLScheduler::enqueue(), CLScheduler::get(), and CLFill::run().
 {
     // Zero out output only if we have paddings
     if(_has_padding)
     {
         //CLScheduler::get().enqueue(*_fill, true);
         _fill.run();
     }
     CLScheduler::get().enqueue(*_space_to_batch_kernel, true);
 }
validate() [1/2]
Status validate (const ITensorInfo * input, const ITensorInfo * block_shape, const ITensorInfo * paddings, const ITensorInfo * output) static
Static function to check if given info will lead to a valid configuration of CLSpaceToBatchLayer.
Parameters
[in] input Tensor input info. Supported tensor rank: 4. Data types supported: All.
[in] block_shape block shape tensor info with shape [M]. Supported M: 2. Data types supported: S32
[in] paddings paddings tensor info with shape [2, M] (First dimension is the fastest-changing dimension). Supported M: 2. Data types supported: S32
[out] output Tensor output info. Data types supported: same as input
Returns
a status
Definition at line 80 of file CLSpaceToBatchLayer.cpp.
References ARM_COMPUTE_RETURN_ON_ERROR, ITensorInfo::data_type(), ITensorInfo::quantization_info(), CLFill::validate(), and CLSpaceToBatchLayerKernel::validate().
Referenced by arm_compute::test::validation::DATA_TEST_CASE().
 {
     ARM_COMPUTE_RETURN_ON_ERROR(CLFill::validate(output, PixelValue(0, input->data_type(), input->quantization_info())));
     ARM_COMPUTE_RETURN_ON_ERROR(CLSpaceToBatchLayerKernel::validate(input, block_shape, paddings, output));
     return Status{};
 }
validate() [2/2]
Status validate (const ITensorInfo * input, const int block_shape_x, const int block_shape_y, const Size2D & padding_left, const Size2D & padding_right, const ITensorInfo * output) static
Static function to check if given info will lead to a valid configuration of CLSpaceToBatchLayer (Static block shape and paddings)
Parameters
[in] input Tensor input info. Supported tensor rank: 4. Data types supported: All.
[in] block_shape_x Block shape x value.
[in] block_shape_y Block shape y value.
[in] padding_left The padding at the beginning of every dimension of the output tensor.
[in] padding_right The padding at the end of every dimension of the output tensor.
[out] output Tensor output info. Data types supported: same as input
Returns
a status
Definition at line 88 of file CLSpaceToBatchLayer.cpp.
References ARM_COMPUTE_RETURN_ON_ERROR, ITensorInfo::data_type(), ITensorInfo::quantization_info(), CLFill::validate(), and CLSpaceToBatchLayerKernel::validate().
 {
     ARM_COMPUTE_RETURN_ON_ERROR(CLFill::validate(output, PixelValue(0, input->data_type(), input->quantization_info())));
     ARM_COMPUTE_RETURN_ON_ERROR(CLSpaceToBatchLayerKernel::validate(input, block_shape_x, block_shape_y, padding_left, padding_right, output));
     return Status{};
 }
The documentation for this class was generated from the following files:
arm_compute/runtime/CL/functions/CLSpaceToBatchLayer.h
src/runtime/CL/functions/CLSpaceToBatchLayer.cpp