Compute Library: IKernel Class Reference
IKernel Class Reference
Common information for all the kernels.
#include <IKernel.h>
Public Member Functions
IKernel ()
Constructor.
virtual ~IKernel ()=default
Destructor.
virtual bool is_parallelisable () const
Indicates whether or not the kernel is parallelisable.
virtual BorderSize border_size () const
The size of the border for that kernel.
const Window & window () const
The maximum window the kernel can be executed on.
Detailed Description
Common information for all the kernels.
Definition at line 33 of file IKernel.h.
Constructor & Destructor Documentation
IKernel()
IKernel ()
Constructor.
Definition at line 33 of file IKernel.cpp.
References Window::DimX, Window::DimY, and Window::set().
     : _window()
 {
     // Create an empty window to make sure the children classes set the window values themselves
     _window.set(Window::DimX, Window::Dimension(0, 0, 1));
     _window.set(Window::DimY, Window::Dimension(0, 0, 1));
 }
~IKernel()
virtual ~IKernel () virtual default
Destructor.
Member Function Documentation
border_size()
BorderSize border_size () const virtual
The size of the border for that kernel.
Returns
The width in number of elements of the border.
Reimplemented in NEConvolutionRectangleKernel, CLConvolutionRectangleKernel, NESeparableConvolutionVertKernel< matrix_size >, CLComplexPixelWiseMultiplicationKernel, NEEdgeTraceKernel, CLSeparableConvolutionVertKernel< matrix_size >, NESeparableConvolutionHorKernel< matrix_size >, CLPixelWiseMultiplicationKernel, CLSobel5x5VertKernel, CLSobel7x7VertKernel, NEEdgeNonMaxSuppressionKernel, NESobel7x7VertKernel, CLSeparableConvolutionHorKernel< matrix_size >, CLEdgeNonMaxSuppressionKernel, NESobel5x5VertKernel, CLDirectConvolutionLayerKernel, CLDepthwiseConvolutionLayer3x3NHWCKernel, CLWinogradInputTransformKernel, CLDepthwiseConvolutionLayer3x3NCHWKernel, CLGaussianPyramidVertKernel, NEGaussian5x5VertKernel, NEGaussianPyramidVertKernel, NEHarrisScoreKernel< block_size >, NELKTrackerKernel, CLReductionOperationKernel, CLHarrisScoreKernel, CLMeanStdDevKernel, CLScharr3x3Kernel, NEConvolutionKernel< matrix_size >, NEDirectConvolutionLayerKernel, CLFastCornersKernel, CLComparisonKernel, CLNormalizationLayerKernel, CLScaleKernel, CLConvolutionKernel< matrix_size >, NEScharr3x3Kernel, NESobel3x3Kernel, GCPoolingLayerKernel, CLSobel5x5HorKernel, CLSobel7x7HorKernel, CLDerivativeKernel, CLSobel3x3Kernel, CLRemapKernel, CLNonLinearFilterKernel, NEMeanStdDevKernel, NENonLinearFilterKernel, CpuPoolingKernel, NEFastCornersKernel, NENonMaximaSuppression3x3Kernel, NESobel5x5HorKernel, NESobel7x7HorKernel, ClPoolingKernel, NEDerivativeKernel, GCDirectConvolutionLayerKernel< kernel_size >, NERemapKernel, INEWarpKernel, CLGaussianPyramidHorKernel, NEGaussian5x5HorKernel, GCNormalizationLayerKernel, NEGaussian3x3Kernel, NEGaussianPyramidHorKernel, NEMedian3x3Kernel, GCDepthwiseConvolutionLayer3x3Kernel, NEBox3x3Kernel, NEDilateKernel, NEErodeKernel, NEIntegralImageKernel, CLWarpAffineKernel, CLNonMaximaSuppression3x3Kernel, CLBox3x3Kernel, CLDilateKernel, CLErodeKernel, CLGaussian3x3Kernel, CLMedian3x3Kernel, CLWarpPerspectiveKernel, and GCScaleKernel.
Definition at line 46 of file IKernel.cpp.
References IKernel::window().
Referenced by ICLSimpleKernel::configure(), IGCSimpleKernel::configure(), CLFillBorderKernel::configure(), NEFillBorderKernel::configure(), ICPPSimpleKernel::ICPPSimpleKernel(), NEFillBorderKernel::name(), NEHarrisScoreKernel< block_size >::name(), NEEdgeNonMaxSuppressionKernel::name(), and NEEdgeTraceKernel::name().
 {
     return BorderSize(0);
 }
is_parallelisable()
bool is_parallelisable () const virtual
Indicates whether or not the kernel is parallelisable.
If the kernel is parallelisable then the window returned by window() can be split into sub-windows which can then be run in parallel.
If the kernel is not parallelisable then only the window returned by window() can be passed to run()
Returns
True if the kernel is parallelisable
Reimplemented in NEWinogradLayerTransformWeightsKernel< T, OutputTileRows, OutputTileCols, KernelRows, KernelCols >, NEEdgeTraceKernel, NEMinMaxLocationKernel, CLFillBorderKernel, NEChannelCombineKernel, CPPTopKVKernel, NECumulativeDistributionKernel, CPPBoxWithNonMaximaSuppressionLimitKernel, GCFillBorderKernel, CPPDetectionWindowNonMaximaSuppressionKernel, NEFillArrayKernel, CPPUpsampleKernel, CPPSortEuclideanDistanceKernel, and NEIntegralImageKernel.
Definition at line 41 of file IKernel.cpp.
Referenced by NEMinMaxLocationKernel::name(), NEEdgeTraceKernel::name(), NEWinogradLayerTransformWeightsKernel< T, OutputTileRows, OutputTileCols, KernelRows, KernelCols >::name(), IScheduler::num_threads_hint(), and OMPScheduler::schedule_op().
 {
     return true;
 }
window()
const Window & window () const
The maximum window the kernel can be executed on.
Returns
The maximum window the kernel can be executed on.
Definition at line 28 of file IKernel.cpp.
Referenced by ICLKernel::add_1D_array_argument(), IGCKernel::add_1D_tensor_argument(), ICLKernel::add_1D_tensor_argument(), IGCKernel::add_2D_tensor_argument(), ICLKernel::add_2D_tensor_argument(), IGCKernel::add_3D_tensor_argument(), ICLKernel::add_3D_tensor_argument(), ICLKernel::add_4D_tensor_argument(), ICLKernel::add_tensor_argument(), IKernel::border_size(), calculate_kernel(), ClFillKernel::configure(), INEWarpKernel::configure(), CLMaxUnpoolingLayerKernel::configure(), NENormalizationLayerKernel::configure(), NEDerivativeKernel::configure(), NEMagnitudePhaseKernel< mag_type, phase_type >::configure(), NEMaxUnpoolingLayerKernel::configure(), NEScaleKernel::configure(), CLLKTrackerInitKernel::configure(), NEROIPoolingLayerKernel::configure(), NEROIAlignLayerKernel::configure(), CLDepthConvertLayerKernel::configure(), CLLKTrackerFinalizeKernel::configure(), CLLKTrackerStage0Kernel::configure(), CLLKTrackerStage1Kernel::configure(), arm_compute::test::validation::DATA_TEST_CASE(), GCScheduler::dispatch(), arm_compute::error_on_unconfigured_kernel(), IGCKernel::get_target(), ICLKernel::get_target(), CLScheduler::init(), IGCKernel::kernel(), NEComputeAllAnchorsKernel::name(), NEDequantizationLayerKernel::name(), NEDilateKernel::name(), NEDirectConvolutionLayerKernel::name(), NEErodeKernel::name(), NEGaussian3x3Kernel::name(), NEGaussian5x5HorKernel::name(), NEGaussianPyramidHorKernel::name(), NEIntegralImageKernel::name(), CPPTopKVKernel::name(), NEL2NormalizeLayerKernel::name(), NEMaxUnpoolingLayerKernel::name(), NEMedian3x3Kernel::name(), NEPriorBoxLayerKernel::name(), NEReverseKernel::name(), NEBatchToSpaceLayerKernel::name(), NEBoundingBoxTransformKernel::name(), NEBox3x3Kernel::name(), NEDepthToSpaceLayerKernel::name(), NEFuseBatchNormalizationKernel::name(), NEInstanceNormalizationLayerKernel::name(), NENormalizationLayerKernel::name(), NEPixelWiseMultiplicationKernel::name(), NEQLSTMLayerNormalizationKernel::name(), NERemapKernel::name(), NEReorgLayerKernel::name(), NEROIAlignLayerKernel::name(), CPPBoxWithNonMaximaSuppressionLimitKernel::name(), NEScaleKernel::name(), NESpaceToDepthLayerKernel::name(), NETableLookupKernel::name(), NEChannelShuffleLayerKernel::name(), NEConvertQuantizedSignednessKernel::name(), NEDepthConvertLayerKernel::name(), CPPUpsampleKernel::name(), NEDerivativeKernel::name(), NEFFTDigitReverseKernel::name(), NEHOGOrientationBinningKernel::name(), NEMagnitudePhaseKernel< mag_type, phase_type >::name(), NEROIPoolingLayerKernel::name(), NESobel5x5HorKernel::name(), NESobel7x7HorKernel::name(), NESpaceToBatchLayerKernel::name(), NEBatchNormalizationLayerKernel::name(), NEStackLayerKernel::name(), NEThresholdKernel::name(), CPPSortEuclideanDistanceKernel::name(), NEGradientKernel::name(), NEColorConvertKernel::name(), NECropKernel::name(), NEFFTScaleKernel::name(), NEFillBorderKernel::name(), CPPPermuteKernel::name(), NEHOGDetectorKernel::name(), NENonLinearFilterKernel::name(), NEPadLayerKernel::name(), NEChannelExtractKernel::name(), NEFastCornersKernel::name(), CPPNonMaximumSuppressionKernel::name(), NEMeanStdDevKernel::name(), NEMeanStdDevNormalizationKernel::name(), NEMinMaxLayerKernel::name(), NEQuantizationLayerKernel::name(), NEAbsoluteDifferenceKernel::name(), NEStridedSliceKernel::name(), NEBitwiseAndKernel::name(), NEBitwiseNotKernel::name(), NETransposeKernel::name(), NEBitwiseOrKernel::name(), NEBitwiseXorKernel::name(), NEDirectConvolutionLayerOutputStageKernel::name(), NEFFTRadixStageKernel::name(), NEFillArrayKernel::name(), NEGEMMMatrixMultiplyKernel::name(), NEMinMaxKernel::name(), NENonMaximaSuppression3x3Kernel::name(), CPPDetectionWindowNonMaximaSuppressionKernel::name(), NERangeKernel::name(), NEChannelCombineKernel::name(), NEHistogramKernel::name(), NEReductionOperationKernel::name(), NEAccumulateKernel::name(), NEDepthwiseConvolutionLayerNativeKernel::name(), NEGEMMMatrixAdditionKernel::name(), NESelectKernel::name(), CPPCornerCandidatesKernel::name(), NEConvertFullyConnectedWeightsKernel::name(), NEGEMMLowpMatrixMultiplyKernel::name(), NEScharr3x3Kernel::name(), NESobel3x3Kernel::name(), NECumulativeDistributionKernel::name(), CpuElementwiseUnaryKernel::name(), NELKTrackerKernel::name(), NEGEMMLowpQuantizeDownInt32ToInt16ScaleByFixedPointKernel::name(), NEGEMMLowpOffsetContributionKernel::name(), NEGEMMLowpQuantizeDownInt32ToInt8ScaleByFixedPointKernel::name(), NEGEMMLowpQuantizeDownInt32ToUint8ScaleByFixedPointKernel::name(), NETileKernel::name(), NEGEMMLowpQuantizeDownInt32ScaleKernel::name(), NEGEMMInterleave4x4Kernel::name(), NECol2ImKernel::name(), NEGatherKernel::name(), NEConvolutionKernel< matrix_size >::name(), CpuPoolingAssemblyWrapperKernel::name(), NEWeightsReshapeKernel::name(), NEIm2ColKernel::name(), NEGEMMLowpOffsetContributionOutputStageKernel::name(), NEGEMMTranspose1xWKernel::name(), NEGaussianPyramidVertKernel::name(), NEGaussian5x5VertKernel::name(), NEGEMMLowpMatrixAReductionKernel::name(), NEAccumulateWeightedKernel::name(), NEHarrisScoreKernel< block_size >::name(), NESobel5x5VertKernel::name(), NESobel7x7VertKernel::name(), NEHOGBlockNormalizationKernel::name(), NEEdgeNonMaxSuppressionKernel::name(), NEMinMaxLocationKernel::name(), NESeparableConvolutionHorKernel< matrix_size >::name(), NEGEMMLowpMatrixBReductionKernel::name(), NEAccumulateSquaredKernel::name(), NEEdgeTraceKernel::name(), NEComplexPixelWiseMultiplicationKernel::name(), NEWinogradLayerTransformInputKernel< T, OutputTileRows, OutputTileCols, KernelRows, KernelCols >::name(), NESeparableConvolutionVertKernel< matrix_size >::name(), NEConvolutionRectangleKernel::name(), NEWinogradLayerTransformOutputKernel< T, OutputTileRows, OutputTileCols, KernelRows, KernelCols >::name(), NEWinogradLayerTransformWeightsKernel< T, OutputTileRows, OutputTileCols, KernelRows, KernelCols >::name(), NEGatherKernel::NEGatherKernel(), NETableLookupKernel::NETableLookupKernel(), ICLSimple2DKernel::run(), IGCSimple2DKernel::run(), ICLSimple3DKernel::run(), IGCSimple3DKernel::run(), GCScaleKernel::run(), GCTransposeKernel::run(), GCGEMMMatrixAccumulateBiasesKernel::run(), NEDilateKernel::run(), NEErodeKernel::run(), GCDepthwiseConvolutionLayer3x3Kernel::run(), NEIntegralImageKernel::run(), GCPixelWiseMultiplicationKernel::run(), NEBox3x3Kernel::run(), NEGaussian3x3Kernel::run(), NEGaussianPyramidHorKernel::run(), GCGEMMMatrixAdditionKernel::run(), GCNormalizationLayerKernel::run(), NEMedian3x3Kernel::run(), CPPSortEuclideanDistanceKernel::run(), NEGaussian5x5HorKernel::run(), GCAbsoluteDifferenceKernel::run(), NETableLookupKernel::run(), GCGEMMTranspose1xWKernel::run(), INEWarpKernel::run(), CPPUpsampleKernel::run(), CLBitwiseKernel::run(), NEBitwiseNotKernel::run(), CLGaussianPyramidHorKernel::run(), NEBitwiseXorKernel::run(), CLHistogramKernel::run(), NEBitwiseAndKernel::run(), GCActivationLayerKernel::run(), GCDepthConcatenateLayerKernel::run(), NEHOGOrientationBinningKernel::run(), NEBitwiseOrKernel::run(), NERemapKernel::run(), NEDerivativeKernel::run(), CLMinMaxKernel::run(), NEAbsoluteDifferenceKernel::run(), NEAccumulateKernel::run(), NEFastCornersKernel::run(), NEFillArrayKernel::run(), NEMagnitudePhaseKernel< mag_type, phase_type >::run(), NENonMaximaSuppression3x3Kernel::run(), NESobel5x5HorKernel::run(), NESobel7x7HorKernel::run(), CPPDetectionWindowNonMaximaSuppressionKernel::run(), NEDequantizationLayerKernel::run(), NENonLinearFilterKernel::run(), GCDropoutLayerKernel::run(), NEMeanStdDevKernel::run(), GCLogits1DShiftExpSumKernel::run(), CLGradientKernel::run(), NEGradientKernel::run(), CPPBoxWithNonMaximaSuppressionLimitKernel::run(), GCDirectConvolutionLayerKernel< kernel_size >::run(), NEHOGDetectorKernel::run(), GCFillBorderKernel::run(), NEMinMaxKernel::run(), NEConvertQuantizedSignednessKernel::run(), CPPCornerCandidatesKernel::run(), CLAbsoluteDifferenceKernel::run(), CLRemapKernel::run(), NETileKernel::run(), CLHOGOrientationBinningKernel::run(), NEDepthToSpaceLayerKernel::run(), CLDequantizationLayerKernel::run(), CLDerivativeKernel::run(), NEReverseKernel::run(), NEROIPoolingLayerKernel::run(), NESpaceToDepthLayerKernel::run(), CLSobel3x3Kernel::run(), NEChannelShuffleLayerKernel::run(), GCGEMMInterleave4x4Kernel::run(), NECumulativeDistributionKernel::run(), NEThresholdKernel::run(), CLLKTrackerInitKernel::run(), GCPoolingLayerKernel::run(), NEPriorBoxLayerKernel::run(), CLSobel5x5HorKernel::run(), CLSobel7x7HorKernel::run(), NEChannelExtractKernel::run(), NEFFTScaleKernel::run(), NEComputeAllAnchorsKernel::run(), GCArithmeticAdditionKernel::run(), NEInstanceNormalizationLayerKernel::run(), NETransposeKernel::run(), NEQLSTMLayerNormalizationKernel::run(), CLDepthwiseConvolutionLayerReshapeWeightsKernel::run(), CPPPermuteKernel::run(), NEScharr3x3Kernel::run(), GCNormalizePlanarYUVLayerKernel::run(), NEQuantizationLayerKernel::run(), NEReorgLayerKernel::run(), NESobel3x3Kernel::run(), CLChannelShuffleLayerKernel::run(), NEFFTDigitReverseKernel::run(), CLDepthToSpaceLayerKernel::run(), GCTensorShiftKernel::run(), CLReverseKernel::run(), CLSelectKernel::run(), CLSpaceToDepthLayerKernel::run(), CLDeconvolutionLayerUpsampleKernel::run(), CLComputeAllAnchorsKernel::run(), CLMaxUnpoolingLayerKernel::run(), NENormalizationLayerKernel::run(), NERangeKernel::run(), CLFFTScaleKernel::run(), NEMaxUnpoolingLayerKernel::run(), NEChannelCombineKernel::run(), CLQuantizationLayerKernel::run(), CLQLSTMLayerNormalizationKernel::run(), NEMeanStdDevNormalizationKernel::run(), CLMagnitudePhaseKernel::run(), CLScaleKernel::run(), NEConvertFullyConnectedWeightsKernel::run(), CLComparisonKernel::run(), CLGatherKernel::run(), CLIntegralImageVertKernel::run(), CLMinMaxLayerKernel::run(), CLNormalizationLayerKernel::run(), CLTileKernel::run(), NEFillBorderKernel::run(), CLFastCornersKernel::run(), NEMinMaxLayerKernel::run(), CLFFTDigitReverseKernel::run(), CLGEMMLowpQuantizeDownInt32ScaleByFixedPointKernel::run(), NEGEMMMatrixAdditionKernel::run(), CLInstanceNormalizationLayerKernel::run(), GCWeightsReshapeKernel::run(), CLMeanStdDevNormalizationKernel::run(), NESelectKernel::run(), CLConvertFullyConnectedWeightsKernel::run(), CLRangeKernel::run(), NEFFTRadixStageKernel::run(), NEGEMMLowpMatrixMultiplyKernel::run(), GCCol2ImKernel::run(), CLReorgLayerKernel::run(), NEPadLayerKernel::run(), NEReductionOperationKernel::run(), NEBoundingBoxTransformKernel::run(), CLROIPoolingLayerKernel::run(), NEHistogramKernel::run(), CPPNonMaximumSuppressionKernel::run(), GCGEMMMatrixMultiplyKernel::run(), GCIm2ColKernel::run(), NEStackLayerKernel::run(), NEColorConvertKernel::run(), NEConvolutionKernel< matrix_size >::run(), NEDirectConvolutionLayerKernel::run(), NEGEMMMatrixMultiplyKernel::run(), NEScaleKernel::run(), CLNormalizePlanarYUVLayerKernel::run(), CLMeanStdDevKernel::run(), NEDirectConvolutionLayerOutputStageKernel::run(), CLChannelExtractKernel::run(), CLScharr3x3Kernel::run(), GCBatchNormalizationLayerKernel::run(), CLPadLayerKernel::run(), CLPriorBoxLayerKernel::run(), NEDepthConvertLayerKernel::run(), NEGEMMInterleave4x4Kernel::run(), CLHarrisScoreKernel::run(), CLReductionOperationKernel::run(), CLHOGDetectorKernel::run(), CLFFTRadixStageKernel::run(), NEGEMMLowpQuantizeDownInt32ScaleKernel::run(), CLFillBorderKernel::run(), NEROIAlignLayerKernel::run(), NEBatchToSpaceLayerKernel::run(), CLL2NormalizeLayerKernel::run(), NECropKernel::run(), CLBoundingBoxTransformKernel::run(), CLChannelCombineKernel::run(), NEGEMMLowpOffsetContributionKernel::run(), NEGEMMLowpQuantizeDownInt32ToInt16ScaleByFixedPointKernel::run(), CLGEMMLowpQuantizeDownInt32ScaleKernel::run(), CLGEMMLowpQuantizeDownInt32ScaleByFloatKernel::run(), NEBatchNormalizationLayerKernel::run(), NECol2ImKernel::run(), CLStackLayerKernel::run(), NEGEMMLowpQuantizeDownInt32ToInt8ScaleByFixedPointKernel::run(), NEGEMMLowpQuantizeDownInt32ToUint8ScaleByFixedPointKernel::run(), CLLogits1DMaxShiftExpSumKernel::run(), NEFuseBatchNormalizationKernel::run(), CLLKTrackerFinalizeKernel::run(), NEHarrisScoreKernel< block_size >::run(), CLGEMMLowpMatrixMultiplyNativeKernel::run(), CLArgMinMaxLayerKernel::run(), NESpaceToBatchLayerKernel::run(), CLGEMMReshapeLHSMatrixKernel::run(), NEDepthwiseConvolutionLayerNativeKernel::run(), NEGaussianPyramidVertKernel::run(), CLCol2ImKernel::run(), NEGaussian5x5VertKernel::run(), CLDeconvolutionReshapeOutputKernel::run(), GCLogits1DNormKernel::run(), NEWeightsReshapeKernel::run(), CLROIAlignLayerKernel::run(), CLBatchToSpaceLayerKernel::run(), NEGEMMTranspose1xWKernel::run(), CLHistogramBorderKernel::run(), CLGaussianPyramidVertKernel::run(), CLDepthwiseConvolutionLayer3x3NCHWKernel::run(), CLWinogradInputTransformKernel::run(), CLGEMMLowpOffsetContributionKernel::run(), CLDepthwiseConvolutionLayer3x3NHWCKernel::run(), CLBatchNormalizationLayerKernel::run(), NEAccumulateWeightedKernel::run(), CLWinogradFilterTransformKernel::run(), CLGEMMMatrixMultiplyKernel::run(), CLFuseBatchNormalizationKernel::run(), NEIm2ColKernel::run(), CLGEMMLowpMatrixMultiplyReshapedKernel::run(), CLDirectConvolutionLayerKernel::run(), CLColorConvertKernel::run(), CLGEMMMatrixMultiplyNativeKernel::run(), CLSpaceToBatchLayerKernel::run(), CLWeightsReshapeKernel::run(), NESobel5x5VertKernel::run(), CLHOGBlockNormalizationKernel::run(), CLEdgeNonMaxSuppressionKernel::run(), CLWinogradOutputTransformKernel::run(), CLMinMaxLocationKernel::run(), CLDepthwiseConvolutionLayerNativeKernel::run(), NESobel7x7VertKernel::run(), NEGEMMLowpOffsetContributionOutputStageKernel::run(), CLGEMMLowpOffsetContributionOutputStageKernel::run(), NEGEMMLowpMatrixAReductionKernel::run(), CLIm2ColKernel::run(), NEHOGBlockNormalizationKernel::run(), CLGEMMLowpMatrixAReductionKernel::run(), CLCopyToArrayKernel::run(), NEEdgeNonMaxSuppressionKernel::run(), CLSobel5x5VertKernel::run(), CLSobel7x7VertKernel::run(), CLGEMMReshapeRHSMatrixKernel::run(), CLGEMMLowpMatrixMultiplyReshapedOnlyRHSKernel::run(), NEMinMaxLocationKernel::run(), NESeparableConvolutionHorKernel< matrix_size >::run(), CLLKTrackerStage0Kernel::run(), CLLogits1DNormKernel::run(), CLGEMMMatrixMultiplyReshapedOnlyRHSKernel::run(), CLGEMMMatrixMultiplyReshapedKernel::run(), CLEdgeTraceKernel::run(), CLGEMMLowpMatrixBReductionKernel::run(), NEAccumulateSquaredKernel::run(), NEEdgeTraceKernel::run(), NEGEMMLowpMatrixBReductionKernel::run(), NESeparableConvolutionVertKernel< matrix_size >::run(), CLLKTrackerStage1Kernel::run(), CLConvolutionRectangleKernel::run(), NEConvolutionRectangleKernel::run(), CpuFillKernel::run_op(), ClElementwiseKernel::run_op(), CpuLogits1DMaxKernel::run_op(), CpuReshapeKernel::run_op(), CpuCopyKernel::run_op(), ClReshapeKernel::run_op(), ClFloorKernel::run_op(), ClElementWiseUnaryKernel::run_op(), ClCopyKernel::run_op(), CpuConcatenateHeightKernel::run_op(), CpuConcatenateWidthKernel::run_op(), CpuActivationKernel::run_op(), CpuElementwiseKernel::run_op(), CpuPermuteKernel::run_op(), NELogicalKernel::run_op(), CpuConcatenateBatchKernel::run_op(), ClWidthConcatenate2TensorsKernel::run_op(), ClWidthConcatenateKernel::run_op(), ClHeightConcatenateKernel::run_op(), ClActivationKernel::run_op(), CpuFloorKernel::run_op(), ClPoolingKernel::run_op(), CpuPoolingKernel::run_op(), ClFillKernel::run_op(), ClDepthConcatenateKernel::run_op(), ClBatchConcatenateKernel::run_op(), CpuConcatenateDepthKernel::run_op(), ClWidthConcatenate4TensorsKernel::run_op(), CLStridedSliceKernel::run_op(), CpuAddKernel::run_op(), CpuElementwiseUnaryKernel::run_op(), ClPermuteKernel::run_op(), CLFillBorderKernel::run_op(), ClCropKernel::run_op(), CpuSubKernel::run_op(), NEStridedSliceKernel::run_op(), CpuLogits1DSoftmaxKernel< IS_LOG >::run_op(), NEPixelWiseMultiplicationKernel::run_op(), CLPixelWiseMultiplicationKernel::run_op(), NEComplexPixelWiseMultiplicationKernel::run_op(), CLComplexPixelWiseMultiplicationKernel::run_op(), SingleThreadScheduler::schedule(), CPPScheduler::schedule(), OMPScheduler::schedule(), NEThresholdKernel::validate(), NEComputeAllAnchorsKernel::validate(), NEQuantizationLayerKernel::validate(), NEFFTDigitReverseKernel::validate(), NEConvertFullyConnectedWeightsKernel::validate(), NEBoundingBoxTransformKernel::validate(), NEGEMMInterleave4x4Kernel::validate(), NEGEMMLowpMatrixAReductionKernel::validate(), and NEGEMMLowpMatrixBReductionKernel::validate().
 {
     return _window;
 }
The documentation for this class was generated from the following files:
arm_compute/core/IKernel.h
src/core/IKernel.cpp