Compute Library: Window::Dimension Class Reference
Window::Dimension Class Reference
Describe one of the image's dimensions with a start, end and step.
#include <Window.h>
Public Member Functions
constexpr Dimension (int start=0, int end=1, int step=1)
Constructor, by default creates a dimension of 1.
Dimension & operator= (const Dimension &d)=default
Default assignment operator to allow dimensions to be copied.
constexpr int start () const
Return the start of the dimension.
constexpr int end () const
Return the end of the dimension.
constexpr int step () const
Return the step of the dimension.
void set_step (int step)
Set the dimension's step.
void set_end (int end)
Set the dimension's end.
Detailed Description
Describe one of the image's dimensions with a start, end and step.
Iteration through the elements of the dimension is done like this: for(int v = start(); v < end(); v += step()) { ... }
Definition at line 77 of file Window.h.
Constructor & Destructor Documentation
Dimension()
constexpr Dimension (int start = 0, int end = 1, int step = 1) inline
Constructor, by default creates a dimension of 1.
Parameters
[in] start Start of the dimension
[in] end End of the dimension
[in] step Step between two elements of the dimension when iterating.
Definition at line 87 of file Window.h.
References Window::Dimension::operator=().
             : _start(start), _end(end), _step(step)
         {
         }
Member Function Documentation
end()
constexpr int end () const inline
Return the end of the dimension.
Definition at line 99 of file Window.h.
Referenced by arm_compute::cpu::add_qasymm8_neon(), arm_compute::cpu::add_qasymm8_signed_neon(), arm_compute::cpu::add_qsymm16_neon(), arm_compute::cpu::add_s16_u8_s16_neon(), arm_compute::cpu::add_same_neon(), arm_compute::cpu::add_u8_u8_s16_neon(), Window::adjust(), arm_compute::colorconvert_iyuv_to_nv12(), arm_compute::colorconvert_iyuv_to_rgb(), arm_compute::colorconvert_iyuv_to_yuv4(), arm_compute::colorconvert_nv12_to_iyuv(), arm_compute::colorconvert_nv12_to_rgb(), arm_compute::colorconvert_nv12_to_yuv4(), arm_compute::colorconvert_rgb_to_iyuv(), arm_compute::colorconvert_rgb_to_nv12(), arm_compute::colorconvert_yuyv_to_iyuv(), arm_compute::colorconvert_yuyv_to_nv12(), AccessWindowTranspose::compute_valid_region(), AccessWindowRectangle::compute_valid_region(), ClCopyKernel::configure(), CLStridedSliceKernel::configure(), ClFillKernel::configure(), GCGEMMTranspose1xWKernel::configure(), NENormalizationLayerKernel::configure(), ClCropKernel::configure(), arm_compute::cpu::elementwise_comp_quantized_signed(), arm_compute::cpu::elementwise_op(), arm_compute::cpu::elementwise_op_quantized(), arm_compute::cpu::elementwise_op_quantized_signed(), arm_compute::enqueue(), arm_compute::error_on_unconfigured_kernel(), arm_compute::finalize_quantization(), arm_compute::cpu::fp32_neon_activation(), ICLKernel::gws_from_window(), arm_compute::cpu::nearest_neon_scale(), arm_compute::cpu::neon_logits_1d_max(), arm_compute::operator<<(), arm_compute::cpu::poolingMxN_fp32_neon_nhwc(), arm_compute::cpu::poolingMxN_q8_neon_nhwc(), arm_compute::cpu::qasymm8_neon_activation(), arm_compute::cpu::qasymm8_signed_neon_activation(), arm_compute::cpu::qsymm16_neon_activation(), CLHistogramKernel::run(), NEConvertQuantizedSignednessKernel::run(), NEROIPoolingLayerKernel::run(), GCPoolingLayerKernel::run(), NEMinMaxLayerKernel::run(), NEGEMMLowpMatrixMultiplyKernel::run(), CLChannelExtractKernel::run(), NEDepthConvertLayerKernel::run(), CLReductionOperationKernel::run(), NEROIAlignLayerKernel::run(), CLChannelCombineKernel::run(), CLHistogramBorderKernel::run(), CLColorConvertKernel::run(), NEWinogradLayerTransformInputKernel< T, OutputTileRows, OutputTileCols, KernelRows, KernelCols >::run(), NEWinogradLayerTransformOutputKernel< T, OutputTileRows, OutputTileCols, KernelRows, KernelCols >::run(), NEWinogradLayerTransformWeightsKernel< T, OutputTileRows, OutputTileCols, KernelRows, KernelCols >::run(), CpuFillKernel::run_op(), CpuCopyKernel::run_op(), CpuConcatenateHeightKernel::run_op(), CpuConcatenateWidthKernel::run_op(), CpuFloorKernel::run_op(), ClPoolingKernel::run_op(), CpuPoolingKernel::run_op(), arm_compute::run_reverse(), Window::scale(), Window::Dimension::set_end(), Window::shift(), arm_compute::cpu::sub_qasymm8_neon(), arm_compute::cpu::sub_qasymm8_signed_neon(), arm_compute::cpu::sub_qsymm16_neon(), arm_compute::cpu::sub_same_neon(), arm_compute::cpu::sub_u8_u8_s16_neon(), AccessWindowTranspose::update_padding_if_needed(), AccessWindowRectangle::update_padding_if_needed(), AccessWindowTranspose::update_window_if_needed(), AccessWindowRectangle::update_window_if_needed(), NEThresholdKernel::validate(), NEQuantizationLayerKernel::validate(), and NEGEMMInterleave4x4Kernel::validate().
         {
             return _end;
         }
operator=()
Dimension& operator= (const Dimension & d) default
Default assignment operator to allow dimensions to be copied.
Referenced by Window::Dimension::Dimension().
set_end()
void set_end (int end) inline
Set the dimension's end.
Parameters
[in] end The new end
Definition at line 120 of file Window.h.
References Window::Dimension::end(), and Window::operator[]().
         {
             _end = end;
         }
set_step()
void set_step (int step) inline
Set the dimension's step.
Parameters
[in] step The new step
Definition at line 112 of file Window.h.
References Window::Dimension::step().
         {
             _step = step;
         }
start()
constexpr int start () const inline
Return the start of the dimension.
Definition at line 94 of file Window.h.
Referenced by arm_compute::cpu::add_qasymm8_neon(), arm_compute::cpu::add_qasymm8_signed_neon(), arm_compute::cpu::add_qsymm16_neon(), arm_compute::cpu::add_s16_u8_s16_neon(), arm_compute::cpu::add_same_neon(), arm_compute::cpu::add_u8_u8_s16_neon(), Window::adjust(), arm_compute::colorconvert_iyuv_to_nv12(), arm_compute::colorconvert_iyuv_to_rgb(), arm_compute::colorconvert_iyuv_to_yuv4(), arm_compute::colorconvert_nv12_to_iyuv(), arm_compute::colorconvert_nv12_to_rgb(), arm_compute::colorconvert_nv12_to_yuv4(), arm_compute::colorconvert_rgb_to_iyuv(), arm_compute::colorconvert_rgb_to_nv12(), arm_compute::colorconvert_yuyv_to_iyuv(), arm_compute::colorconvert_yuyv_to_nv12(), AccessWindowTranspose::compute_valid_region(), AccessWindowRectangle::compute_valid_region(), ClCopyKernel::configure(), CLStridedSliceKernel::configure(), ClFillKernel::configure(), INEWarpKernel::configure(), NENormalizationLayerKernel::configure(), ClCropKernel::configure(), arm_compute::cpu::elementwise_comp_quantized_signed(), arm_compute::cpu::elementwise_op(), arm_compute::cpu::elementwise_op_quantized(), arm_compute::cpu::elementwise_op_quantized_signed(), arm_compute::enqueue(), arm_compute::error_on_unconfigured_kernel(), arm_compute::finalize_quantization(), arm_compute::cpu::fp32_neon_activation(), ICLKernel::gws_from_window(), arm_compute::cpu::nearest_neon_scale(), arm_compute::cpu::neon_logits_1d_max(), arm_compute::operator<<(), arm_compute::cpu::poolingMxN_fp32_neon_nhwc(), arm_compute::cpu::poolingMxN_q8_neon_nhwc(), arm_compute::cpu::qasymm8_neon_activation(), arm_compute::cpu::qasymm8_signed_neon_activation(), arm_compute::cpu::qsymm16_neon_activation(), CLHistogramKernel::run(), NEHOGOrientationBinningKernel::run(), NEConvertQuantizedSignednessKernel::run(), CLHOGOrientationBinningKernel::run(), NEROIPoolingLayerKernel::run(), GCPoolingLayerKernel::run(), NEMinMaxLayerKernel::run(), NEGEMMLowpMatrixMultiplyKernel::run(), CLChannelExtractKernel::run(), NEDepthConvertLayerKernel::run(), CLReductionOperationKernel::run(), NEROIAlignLayerKernel::run(), CLChannelCombineKernel::run(), CLHistogramBorderKernel::run(), CLColorConvertKernel::run(), NEWinogradLayerTransformInputKernel< T, OutputTileRows, OutputTileCols, KernelRows, KernelCols >::run(), NEWinogradLayerTransformOutputKernel< T, OutputTileRows, OutputTileCols, KernelRows, KernelCols >::run(), NEWinogradLayerTransformWeightsKernel< T, OutputTileRows, OutputTileCols, KernelRows, KernelCols >::run(), CpuFillKernel::run_op(), CpuConcatenateHeightKernel::run_op(), CpuConcatenateWidthKernel::run_op(), CpuFloorKernel::run_op(), ClPoolingKernel::run_op(), CpuPoolingKernel::run_op(), arm_compute::run_reverse(), Window::scale(), Window::shift(), arm_compute::cpu::sub_qasymm8_neon(), arm_compute::cpu::sub_qasymm8_signed_neon(), arm_compute::cpu::sub_qsymm16_neon(), arm_compute::cpu::sub_same_neon(), arm_compute::cpu::sub_u8_u8_s16_neon(), AccessWindowTranspose::update_padding_if_needed(), AccessWindowRectangle::update_padding_if_needed(), AccessWindowTranspose::update_window_if_needed(), AccessWindowRectangle::update_window_if_needed(), NEThresholdKernel::validate(), NEQuantizationLayerKernel::validate(), and NEGEMMInterleave4x4Kernel::validate().
         {
             return _start;
         }
step()
constexpr int step () const inline
Return the step of the dimension.
Definition at line 104 of file Window.h.
Referenced by arm_compute::cpu::add_qasymm8_neon(), arm_compute::cpu::add_qasymm8_signed_neon(), arm_compute::cpu::add_qsymm16_neon(), arm_compute::cpu::add_same_neon(), Window::adjust(), arm_compute::colorconvert_iyuv_to_nv12(), arm_compute::colorconvert_iyuv_to_rgb(), arm_compute::colorconvert_iyuv_to_yuv4(), arm_compute::colorconvert_nv12_to_iyuv(), arm_compute::colorconvert_nv12_to_rgb(), arm_compute::colorconvert_nv12_to_yuv4(), arm_compute::colorconvert_rgb_to_iyuv(), arm_compute::colorconvert_rgb_to_nv12(), arm_compute::colorconvert_yuyv_to_iyuv(), arm_compute::colorconvert_yuyv_to_nv12(), AccessWindowTranspose::compute_valid_region(), AccessWindowRectangle::compute_valid_region(), arm_compute::cpu::elementwise_comp_quantized_signed(), arm_compute::cpu::elementwise_op(), arm_compute::cpu::elementwise_op_quantized(), arm_compute::cpu::elementwise_op_quantized_signed(), arm_compute::enqueue(), arm_compute::error_on_unconfigured_kernel(), arm_compute::operator<<(), GCDepthwiseConvolutionLayer3x3Kernel::run(), NEGaussianPyramidHorKernel::run(), CLHistogramKernel::run(), GCDirectConvolutionLayerKernel< kernel_size >::run(), CLChannelExtractKernel::run(), CLReductionOperationKernel::run(), CLChannelCombineKernel::run(), NEGaussianPyramidVertKernel::run(), CLGaussianPyramidVertKernel::run(), CLDepthwiseConvolutionLayer3x3NCHWKernel::run(), CLDepthwiseConvolutionLayer3x3NHWCKernel::run(), CLColorConvertKernel::run(), CLDepthwiseConvolutionLayerNativeKernel::run(), ClCropKernel::run_op(), Window::scale(), Window::Dimension::set_step(), Window::shift(), arm_compute::cpu::sub_qasymm8_neon(), arm_compute::cpu::sub_qasymm8_signed_neon(), arm_compute::cpu::sub_qsymm16_neon(), arm_compute::cpu::sub_same_neon(), AccessWindowTranspose::update_padding_if_needed(), AccessWindowRectangle::update_padding_if_needed(), AccessWindowTranspose::update_window_if_needed(), AccessWindowRectangle::update_window_if_needed(), ClFillKernel::validate(), ClCropKernel::validate(), and Window::z().
         {
             return _step;
         }
The documentation for this class was generated from the following file:
arm_compute/core/Window.h