Compute Library: CpuLogits1DMaxKernel Class Reference
CpuLogits1DMaxKernel Class Reference
Interface for the identifying the max value of 1D Logits.
#include <CpuSoftmaxKernel.h>
Public Member Functions
CpuLogits1DMaxKernel ()
Constructor.
ARM_COMPUTE_DISALLOW_COPY_ALLOW_MOVE (CpuLogits1DMaxKernel)
void configure (const ITensorInfo *src, ITensorInfo *dst)
Set the input and output tensors.
void run_op (ITensorPack &tensors, const Window &window, const ThreadInfo &info) override
Execute the kernel on the passed window.
const char * name () const override
Name of the kernel.
Public Member Functions inherited from ICPPKernel
virtual ~ICPPKernel ()=default
Default destructor.
virtual void run (const Window &window, const ThreadInfo &info)
Execute the kernel on the passed window.
virtual void run_nd (const Window &window, const ThreadInfo &info, const Window &thread_locator)
legacy compatibility layer for implemantions which do not support thread_locator In these cases we simply narrow the interface down the legacy version
Public Member Functions inherited from IKernel
IKernel ()
Constructor.
virtual ~IKernel ()=default
Destructor.
virtual bool is_parallelisable () const
Indicates whether or not the kernel is parallelisable.
virtual BorderSize border_size () const
The size of the border for that kernel.
const Window & window () const
The maximum window the kernel can be executed on.
Static Public Member Functions
static Status validate (const ITensorInfo *src, const ITensorInfo *dst)
Static function to check if given info will lead to a valid configuration of CpuLogits1DMaxKernel.
Detailed Description
Interface for the identifying the max value of 1D Logits.
Definition at line 37 of file CpuSoftmaxKernel.h.
Constructor & Destructor Documentation
CpuLogits1DMaxKernel()
CpuLogits1DMaxKernel ()
Constructor.
Definition at line 215 of file CpuSoftmaxKernel.cpp.
 {
 }
Member Function Documentation
ARM_COMPUTE_DISALLOW_COPY_ALLOW_MOVE()
ARM_COMPUTE_DISALLOW_COPY_ALLOW_MOVE (CpuLogits1DMaxKernel)
configure()
void configure (const ITensorInfo * src, ITensorInfo * dst)
Set the input and output tensors.
Parameters
[in] src Source tensor info. Data types supported: QASYMM8/QASYMM8_SIGNED/F16/F32.
[out] dst Destination tensor info. Data types supported: same as input
Definition at line 219 of file CpuSoftmaxKernel.cpp.
References ARM_COMPUTE_ERROR_ON_NULLPTR, ARM_COMPUTE_ERROR_THROW_ON, arm_compute::auto_init_if_empty(), arm_compute::calculate_max_window(), ITensorInfo::data_type(), ITensorInfo::num_dimensions(), arm_compute::test::validation::output_shape, ITensorInfo::quantization_info(), Dimensions< T >::set_num_dimensions(), ITensorInfo::set_valid_region(), and ITensorInfo::tensor_shape().
 {
     ARM_COMPUTE_ERROR_ON_NULLPTR(src, dst);
     // Perform validation step
     ARM_COMPUTE_ERROR_THROW_ON(validate_arguments_logits_1d_max(*src, *dst));
     // Softmax across the x dimension
     const TensorShape output_shape = TensorShape(src->tensor_shape()).set(0, 1);
     // Output auto initialization if not yet initialized
     auto_init_if_empty(*dst, output_shape, 1, src->data_type(), src->quantization_info());
     Window      win = calculate_max_window(*src, Steps());
     Coordinates coord;
     coord.set_num_dimensions(dst->num_dimensions());
     dst->set_valid_region(ValidRegion(coord, dst->tensor_shape()));
     ICpuKernel::configure(win);
 }
name()
const char * name () const override virtual
Name of the kernel.
Returns
Kernel name
Implements ICPPKernel.
Definition at line 260 of file CpuSoftmaxKernel.cpp.
References ARM_COMPUTE_RETURN_ERROR_ON, ARM_COMPUTE_RETURN_ERROR_ON_CPU_F16_UNSUPPORTED, ARM_COMPUTE_RETURN_ERROR_ON_DATA_TYPE_CHANNEL_NOT_IN, ARM_COMPUTE_RETURN_ERROR_ON_MISMATCHING_DATA_TYPES, ARM_COMPUTE_RETURN_ERROR_ON_MISMATCHING_DIMENSIONS, ARM_COMPUTE_RETURN_ERROR_ON_MISMATCHING_QUANTIZATION_INFO, ARM_COMPUTE_RETURN_ERROR_ON_MISMATCHING_SHAPES, ARM_COMPUTE_UNUSED, ITensorInfo::data_type(), arm_compute::test::validation::dst, arm_compute::F16, arm_compute::F32, arm_compute::get_softmax_output_quantization_info(), arm_compute::is_data_type_quantized_asymmetric(), arm_compute::QASYMM8, arm_compute::QASYMM8_SIGNED, ITensorInfo::quantization_info(), arm_compute::test::validation::src, ITensorInfo::tensor_shape(), and ITensorInfo::total_size().
 {
     return "CpuLogits1DMaxKernel";
 }
run_op()
void run_op (ITensorPack & tensors, const Window & window, const ThreadInfo & info) override virtual
Execute the kernel on the passed window.
Warning
If is_parallelisable() returns false then the passed window must be equal to window()
Note
The window has to be a region within the window returned by the window() method
The width of the window has to be a multiple of num_elems_processed_per_iteration().
Parameters
[in] tensors A vector containing the tensors to operate on.
[in] window Region on which to execute the kernel. (Must be a region of the window returned by window())
[in] info Info about executing thread and CPU.
Reimplemented from ICPPKernel.
Definition at line 247 of file CpuSoftmaxKernel.cpp.
References arm_compute::ACL_DST, arm_compute::ACL_SRC, ARM_COMPUTE_ERROR_ON_INVALID_SUBWINDOW, ARM_COMPUTE_ERROR_ON_UNCONFIGURED_KERNEL, ARM_COMPUTE_UNUSED, arm_compute::test::validation::dst, ITensorPack::get_const_tensor(), ITensorPack::get_tensor(), arm_compute::test::validation::src, and IKernel::window().
 {
     ARM_COMPUTE_UNUSED(info);
     ARM_COMPUTE_ERROR_ON_UNCONFIGURED_KERNEL(this);
     ARM_COMPUTE_ERROR_ON_INVALID_SUBWINDOW(ICpuKernel::window(), window);
     const auto src = tensors.get_const_tensor(TensorType::ACL_SRC);
     auto       dst = tensors.get_tensor(TensorType::ACL_DST);
     const auto *uk = get_implementation_logits_max(SoftmaxSelectorData{ src->info()->data_type() });
     uk->ukernel(src, dst, window);
 }
validate()
Status validate (const ITensorInfo * src, const ITensorInfo * dst) static
Static function to check if given info will lead to a valid configuration of CpuLogits1DMaxKernel.
Parameters
[in] src Source tensor info. Data types supported: QASYMM8/QASYMM8_SIGNED/F16/F32.
[in] dst Destination tensor info. Data types supported: same as input
Returns
a status
Definition at line 239 of file CpuSoftmaxKernel.cpp.
References ARM_COMPUTE_ERROR_ON_NULLPTR, and ARM_COMPUTE_RETURN_ON_ERROR.
Referenced by CpuSoftmaxGeneric< IS_LOG >::validate().
 {
     ARM_COMPUTE_ERROR_ON_NULLPTR(src, dst);
     ARM_COMPUTE_RETURN_ON_ERROR(validate_arguments_logits_1d_max(*src, *dst));
     return Status{};
 }
The documentation for this class was generated from the following files:
src/core/cpu/kernels/CpuSoftmaxKernel.h
src/core/cpu/kernels/CpuSoftmaxKernel.cpp