Compute Library: CLDirectConvolutionLayer Class Reference
CLDirectConvolutionLayer Class Reference
Basic function to execute direct convolution function:
#include <CLDirectConvolutionLayer.h>
Public Member Functions
CLDirectConvolutionLayer ()
Default constructor.
CLDirectConvolutionLayer (const CLDirectConvolutionLayer &)=delete
Prevent instances of this class from being copied.
CLDirectConvolutionLayer & operator= (const CLDirectConvolutionLayer &)=delete
Prevent instances of this class from being copied.
~CLDirectConvolutionLayer ()
Default destructor.
void configure (ICLTensor *input, const ICLTensor *weights, const ICLTensor *biases, ICLTensor *output, const PadStrideInfo &conv_info, const ActivationLayerInfo &act_info=ActivationLayerInfo())
Set the input and output tensors.
void configure (const CLCompileContext &compile_context, ICLTensor *input, const ICLTensor *weights, const ICLTensor *biases, ICLTensor *output, const PadStrideInfo &conv_info, const ActivationLayerInfo &act_info=ActivationLayerInfo())
Set the input and output tensors.
void run () override
Run the kernels contained in the function.
Public Member Functions inherited from IFunction
virtual ~IFunction ()=default
Destructor.
virtual void prepare ()
Prepare the function for executing.
Static Public Member Functions
static Status validate (const ITensorInfo *input, const ITensorInfo *weights, const ITensorInfo *biases, const ITensorInfo *output, const PadStrideInfo &conv_info, const ActivationLayerInfo &act_info=ActivationLayerInfo())
Static function to check if given info will lead to a valid configuration of CLDirectConvolutionLayer.
Detailed Description
Basic function to execute direct convolution function:
Definition at line 43 of file CLDirectConvolutionLayer.h.
Constructor & Destructor Documentation
CLDirectConvolutionLayer() [1/2]
CLDirectConvolutionLayer ()
Default constructor.
Definition at line 36 of file CLDirectConvolutionLayer.cpp.
References CLDirectConvolutionLayer::~CLDirectConvolutionLayer().
     : _direct_conv_kernel(std::make_unique<CLDirectConvolutionLayerKernel>()), _input_border_handler(std::make_unique<CLFillBorderKernel>()), _activationlayer_function(),
       _is_activationlayer_enabled(false)
 {
 }
CLDirectConvolutionLayer() [2/2]
CLDirectConvolutionLayer (const CLDirectConvolutionLayer &) delete
Prevent instances of this class from being copied.
~CLDirectConvolutionLayer()
~CLDirectConvolutionLayer () default
Default destructor.
Referenced by CLDirectConvolutionLayer::CLDirectConvolutionLayer().
Member Function Documentation
configure() [1/2]
void configure (ICLTensor * input, const ICLTensor * weights, const ICLTensor * biases, ICLTensor * output, const PadStrideInfo & conv_info, const ActivationLayerInfo & act_info = ActivationLayerInfo())
Set the input and output tensors.
Parameters
[in] input Source tensor. 3 lower dimensions represent a single input [width, height, IFM], while every optional dimension from 4 and above represent a batch of inputs. Data types supported: QASYMM8_SIGNED/QASYMM8/F16/F32.
[in] weights Weights tensor. Weights are 4D tensor with dimensions [kernel_x, kernel_y, IFM, OFM]. Data type supported:Same as input.
[in] biases Biases tensor. Shared biases supported. Biases are 1D tensor with dimensions [OFM]. Data type supported: Should match input data type, except for input of QASYMM8 and QASYMM8_SIGNED type where biases should be of S32 type.
[out] output Destination tensor. 3 lower dimensions represent a single output [width, height, OFM], while the rest represent batch of outputs. Data types supported: Same as input.
[in] conv_info Contains padding and stride information described in PadStrideInfo.
[in] act_info (Optional) Activation layer information in case of a fused activation.
Definition at line 44 of file CLDirectConvolutionLayer.cpp.
References CLKernelLibrary::get().
 {
     configure(CLKernelLibrary::get().get_compile_context(), input, weights, biases, output, conv_info, act_info);
 }
configure() [2/2]
void configure (const CLCompileContext & compile_context, ICLTensor * input, const ICLTensor * weights, const ICLTensor * biases, ICLTensor * output, const PadStrideInfo & conv_info, const ActivationLayerInfo & act_info = ActivationLayerInfo())
Set the input and output tensors.
Parameters
[in] compile_context The compile context to be used.
[in] input Source tensor. 3 lower dimensions represent a single input [width, height, IFM], while every optional dimension from 4 and above represent a batch of inputs. Data types supported: QASYMM8_SIGNED/QASYMM8/F16/F32.
[in] weights Weights tensor. Weights are 4D tensor with dimensions [kernel_x, kernel_y, IFM, OFM]. Data type supported:Same as input.
[in] biases Biases tensor. Shared biases supported. Biases are 1D tensor with dimensions [OFM]. Data type supported: Should match input data type, except for input of QASYMM8 and QASYMM8_SIGNED type where biases should be of S32 type.
[out] output Destination tensor. 3 lower dimensions represent a single output [width, height, OFM], while the rest represent batch of outputs. Data types supported: Same as input.
[in] conv_info Contains padding and stride information described in PadStrideInfo.
[in] act_info (Optional) Activation layer information in case of a fused activation.
Definition at line 49 of file CLDirectConvolutionLayer.cpp.
References CLActivationLayer::configure(), arm_compute::CONSTANT, ITensorInfo::data_type(), ActivationLayerInfo::enabled(), CLScheduler::get(), ITensor::info(), arm_compute::is_data_type_quantized_asymmetric(), ITensorInfo::quantization_info(), and CLScheduler::tune_kernel_static().
 {
     // Set GPU target
     _direct_conv_kernel->set_target(CLScheduler::get().target());
     // Configure direct convolution
     _direct_conv_kernel->configure(compile_context, input, weights, biases, output, conv_info);
     // Configure border handler
     PixelValue &&zero_value(0.f);
     if(is_data_type_quantized_asymmetric(input->info()->data_type()))
     {
         zero_value = PixelValue(0, input->info()->data_type(), input->info()->quantization_info());
     }
     _input_border_handler->configure(compile_context, input, _direct_conv_kernel->border_size(), BorderMode::CONSTANT, zero_value);
     // Tune kernels
     CLScheduler::get().tune_kernel_static(*_direct_conv_kernel);
     _is_activationlayer_enabled = act_info.enabled();
     //Configure Activation Layer
     if(_is_activationlayer_enabled)
     {
         _activationlayer_function.configure(compile_context, output, nullptr, act_info);
     }
 }
operator=()
CLDirectConvolutionLayer& operator= (const CLDirectConvolutionLayer &) delete
Prevent instances of this class from being copied.
run()
void run () override virtual
Run the kernels contained in the function.
For Neon kernels:
Multi-threading is used for the kernels which are parallelisable.
By default std::thread::hardware_concurrency() threads are used.
Note
CPPScheduler::set_num_threads() can be used to manually set the number of threads
For OpenCL kernels:
All the kernels are enqueued on the queue associated with CLScheduler.
The queue is then flushed.
Note
The function will not block until the kernels are executed. It is the user's responsibility to wait.
Will call prepare() on first run if hasn't been done
Implements IFunction.
Definition at line 90 of file CLDirectConvolutionLayer.cpp.
References CLScheduler::enqueue(), CLScheduler::get(), and CLActivationLayer::run().
 {
     // Run border handler
     CLScheduler::get().enqueue(*_input_border_handler, false);
     // Run direct convolution
     CLScheduler::get().enqueue(*_direct_conv_kernel);
     //Run Activation Layer
     if(_is_activationlayer_enabled)
     {
         _activationlayer_function.run();
     }
 }
validate()
Status validate (const ITensorInfo * input, const ITensorInfo * weights, const ITensorInfo * biases, const ITensorInfo * output, const PadStrideInfo & conv_info, const ActivationLayerInfo & act_info = ActivationLayerInfo()) static
Static function to check if given info will lead to a valid configuration of CLDirectConvolutionLayer.
Parameters
[in] input Source tensor. 3 lower dimensions represent a single input [width, height, IFM], while every optional dimension from 4 and above represent a batch of inputs. Data types supported: QASYMM8_SIGNED/QASYMM8/F16/F32.
[in] weights Weights tensor. Weights are 4D tensor with dimensions [kernel_x, kernel_y, IFM, OFM]. Data type supported:Same as input.
[in] biases Biases tensor. Shared biases supported. Biases are 1D tensor with dimensions [OFM]. Data type supported: Should match input data type, except for input of QASYMM8 and QASYMM8_SIGNED type where biases should be of S32 type.
[in] output Destination tensor. 3 lower dimensions represent a single output [width, height, OFM], while the rest represent batch of outputs. Data types supported: Same as input.
[in] conv_info Contains padding and stride information described in PadStrideInfo.
[in] act_info (Optional) Activation layer information in case of a fused activation.
Returns
a status
Definition at line 79 of file CLDirectConvolutionLayer.cpp.
References ARM_COMPUTE_RETURN_ON_ERROR, ActivationLayerInfo::enabled(), CLScheduler::get(), CLActivationLayer::validate(), and CLDirectConvolutionLayerKernel::validate().
Referenced by arm_compute::test::validation::DATA_TEST_CASE(), CLConvolutionLayer::get_convolution_method(), and CLConvolutionLayer::validate().
 {
     ARM_COMPUTE_RETURN_ON_ERROR(CLDirectConvolutionLayerKernel::validate(input, weights, biases, output, conv_info, CLScheduler::get().target()));
     if(act_info.enabled())
     {
         ARM_COMPUTE_RETURN_ON_ERROR(CLActivationLayer::validate(output, nullptr, act_info));
     }
     return Status{};
 }
The documentation for this class was generated from the following files:
arm_compute/runtime/CL/functions/CLDirectConvolutionLayer.h
src/runtime/CL/functions/CLDirectConvolutionLayer.cpp