Compute Library: CpuPowerKernel Class Reference
CpuPowerKernel Class Reference
#include <CpuElementwiseKernel.h>
Public Member Functions
CpuPowerKernel ()=default
Default constructor.
void configure (const ITensorInfo *input1, const ITensorInfo *input2, ITensorInfo *output)
Configure kernel.
Public Member Functions inherited from CpuArithmeticKernel
CpuArithmeticKernel ()=default
Default constructor.
void configure (ArithmeticOperation op, const ITensorInfo *input1, const ITensorInfo *input2, ITensorInfo *output)
Configure kernel.
Public Member Functions inherited from CpuElementwiseKernel
const char * name () const override
Name of the kernel.
CpuElementwiseKernel ()=default
ARM_COMPUTE_DISALLOW_COPY_ALLOW_MOVE (CpuElementwiseKernel)
void run_op (ITensorPack &tensors, const Window &window, const ThreadInfo &info) override
Execute the kernel on the passed window.
Public Member Functions inherited from ICPPKernel
virtual ~ICPPKernel ()=default
Default destructor.
virtual void run (const Window &window, const ThreadInfo &info)
Execute the kernel on the passed window.
virtual void run_nd (const Window &window, const ThreadInfo &info, const Window &thread_locator)
legacy compatibility layer for implemantions which do not support thread_locator In these cases we simply narrow the interface down the legacy version
Public Member Functions inherited from IKernel
IKernel ()
Constructor.
virtual ~IKernel ()=default
Destructor.
virtual bool is_parallelisable () const
Indicates whether or not the kernel is parallelisable.
virtual BorderSize border_size () const
The size of the border for that kernel.
const Window & window () const
The maximum window the kernel can be executed on.
Static Public Member Functions
static Status validate (const ITensorInfo *input1, const ITensorInfo *input2, const ITensorInfo *output)
Static function to check if given info will lead to a valid configuration of CpuPowerKernel.
Static Public Member Functions inherited from CpuArithmeticKernel
static Status validate (ArithmeticOperation op, const ITensorInfo *input1, const ITensorInfo *input2, const ITensorInfo *output)
Static function to check if given info will lead to a valid configuration of cpu::kernels::CpuArithmeticKernel.
Additional Inherited Members
Public Types inherited from CpuElementwiseKernel
using ElementwiseFunction = void(const ITensor *, const ITensor *, ITensor *, const Window &)
Common signature for all the specialised arithmetic functions.
Detailed Description
Definition at line 164 of file CpuElementwiseKernel.h.
Constructor & Destructor Documentation
CpuPowerKernel()
CpuPowerKernel () default
Default constructor.
Member Function Documentation
configure()
void configure (const ITensorInfo * input1, const ITensorInfo * input2, ITensorInfo * output)
Configure kernel.
The power operator.
Parameters
[in] input1 First tensor input info. Data types supported: F16/F32.
[in] input2 Second tensor input info. Data types supported: Same as input1.
[out] output Output tensor info. Data types supported: Same as input1.
Definition at line 285 of file CpuElementwiseKernel.cpp.
References ARM_COMPUTE_ERROR_THROW_ON, ARM_COMPUTE_RETURN_ERROR_ON_DATA_TYPE_CHANNEL_NOT_IN, arm_compute::F16, arm_compute::F32, arm_compute::POWER, and arm_compute::validate_arguments().
 {
     ARM_COMPUTE_ERROR_THROW_ON(validate_arguments(*input1, *input2, *output));
     configure_common(input1, input2, output);
     _op = ArithmeticOperation::POWER;
 }
validate()
Status validate (const ITensorInfo * input1, const ITensorInfo * input2, const ITensorInfo * output) static
Static function to check if given info will lead to a valid configuration of CpuPowerKernel.
Parameters
[in] input1 First tensor input info. Data types supported: F16/F32.
[in] input2 Second tensor input info. Data types supported: Same as input1.
[in] output Output tensor info. Data types supported: Same as input1.
Returns
a Status
Definition at line 298 of file CpuElementwiseKernel.cpp.
References ARM_COMPUTE_RETURN_ERROR_ON_NULLPTR, ARM_COMPUTE_RETURN_ON_ERROR, and arm_compute::validate_arguments().
Referenced by CpuElementwisePower::validate().
 {
     ARM_COMPUTE_RETURN_ERROR_ON_NULLPTR(input1, input2, output);
     ARM_COMPUTE_RETURN_ON_ERROR(validate_arguments(*input1, *input2, *output));
     return Status{};
 }
The documentation for this class was generated from the following files:
src/core/cpu/kernels/CpuElementwiseKernel.h
src/core/cpu/kernels/CpuElementwiseKernel.cpp