Compute Library: CLReductionOperation Class Reference
CLReductionOperation Class Reference
Perform reduction operation.
#include <CLReductionOperation.h>
Public Member Functions
CLReductionOperation (std::shared_ptr< IMemoryManager > memory_manager=nullptr)
Default Constructor.
~CLReductionOperation ()
Default Destructor.
CLReductionOperation (const CLReductionOperation &)=delete
Prevent instances of this class from being copied (As this class contains pointers)
CLReductionOperation (CLReductionOperation &&)=default
Default move constructor.
CLReductionOperation & operator= (const CLReductionOperation &)=delete
Prevent instances of this class from being copied (As this class contains pointers)
CLReductionOperation & operator= (CLReductionOperation &&)=default
Default move assignment operator.
void configure (ICLTensor *input, ICLTensor *output, unsigned int axis, ReductionOperation op, bool keep_dims=true)
Set the input and output tensors.
void configure (const CLCompileContext &compile_context, ICLTensor *input, ICLTensor *output, unsigned int axis, ReductionOperation op, bool keep_dims=true)
Set the input and output tensors.
void run () override
Run the kernels contained in the function.
Public Member Functions inherited from IFunction
virtual ~IFunction ()=default
Destructor.
virtual void prepare ()
Prepare the function for executing.
Static Public Member Functions
static Status validate (const ITensorInfo *input, const ITensorInfo *output, unsigned int axis, ReductionOperation op, bool keep_dims=true)
Static function to check if given info will lead to a valid configuration of CLReductionOperation.
Detailed Description
Perform reduction operation.
Definition at line 45 of file CLReductionOperation.h.
Constructor & Destructor Documentation
CLReductionOperation() [1/3]
CLReductionOperation (std::shared_ptr< IMemoryManager > memory_manager = nullptr)
Default Constructor.
Parameters
[in] memory_manager (Optional) Memory manager.
Definition at line 40 of file CLReductionOperation.cpp.
References CLReductionOperation::~CLReductionOperation().
     : _memory_group(std::move(memory_manager)), _results_vector(), _reduction_kernels_vector(), _border_handlers_vector(), _reshape(), _num_of_stages(), _reduction_axis(), _is_serial(),
       _is_reshape_required(false)
 {
 }
~CLReductionOperation()
~CLReductionOperation () default
Default Destructor.
Referenced by CLReductionOperation::CLReductionOperation().
CLReductionOperation() [2/3]
CLReductionOperation (const CLReductionOperation &) delete
Prevent instances of this class from being copied (As this class contains pointers)
CLReductionOperation() [3/3]
CLReductionOperation (CLReductionOperation &&) default
Default move constructor.
Member Function Documentation
configure() [1/2]
void configure (ICLTensor * input, ICLTensor * output, unsigned int axis, ReductionOperation op, bool keep_dims = true)
Set the input and output tensors.
Parameters
[in] input Source tensor. Data types supported: QASYMM8/QASYMM8_SIGNED/F16/F32/S32.
[out] output Destination tensor. Data types and data layouts supported: Same as input.
[in] axis Axis along which to reduce. Supported reduction axis : 0, 1, 2, 3
[in] op Reduction operation to perform. Operations supported: MEAN_SUM, PROD, SUM_SQUARE, SUM, MIN, MAX
[in] keep_dims (Optional) Whether to keep the reduced dimension after the operation. Defaults to true.
Definition at line 193 of file CLReductionOperation.cpp.
References CLKernelLibrary::get().
Referenced by CLMeanStdDev::configure(), CLL2NormalizeLayer::configure(), and CLFFTConvolutionLayer::configure().
 {
     configure(CLKernelLibrary::get().get_compile_context(), input, output, axis, op, keep_dims);
 }
configure() [2/2]
void configure (const CLCompileContext & compile_context, ICLTensor * input, ICLTensor * output, unsigned int axis, ReductionOperation op, bool keep_dims = true)
Set the input and output tensors.
Parameters
[in] compile_context The compile context to be used.
[in] input Source tensor. Data types supported: QASYMM8/QASYMM8_SIGNED/F16/F32/S32.
[out] output Destination tensor. Data types and data layouts supported: Same as input.
[in] axis Axis along which to reduce. Supported reduction axis : 0, 1, 2, 3
[in] op Reduction operation to perform. Operations supported: MEAN_SUM, PROD, SUM_SQUARE, SUM, MIN, MAX
[in] keep_dims (Optional) Whether to keep the reduced dimension after the operation. Defaults to true.
Definition at line 198 of file CLReductionOperation.cpp.
References ARM_COMPUTE_ERROR, ARM_COMPUTE_ERROR_ON_NULLPTR, arm_compute::auto_init_if_empty(), arm_compute::utils::calculate_number_of_stages_only_x_axis(), ICloneable< T >::clone(), arm_compute::misc::shape_calculator::compute_reduced_shape(), CLReshapeLayer::configure(), arm_compute::CONSTANT, ITensorInfo::data_type(), ITensorInfo::dimension(), arm_compute::get_min_max(), ITensor::info(), input_width, MemoryGroup::manage(), arm_compute::MAX, arm_compute::MEAN_SUM, arm_compute::MIN, arm_compute::needs_serialized_reduction(), arm_compute::test::validation::output_shape, arm_compute::PROD, arm_compute::SUM, arm_compute::SUM_SQUARE, and ITensorInfo::tensor_shape().
 {
     ARM_COMPUTE_ERROR_ON_NULLPTR(input, output);
     _num_of_stages       = utils::calculate_number_of_stages_only_x_axis(input->info()->dimension(0), axis);
     _reduction_axis      = axis;
     _is_serial           = needs_serialized_reduction(op, input->info()->data_type(), axis);
     _is_reshape_required = !keep_dims;
     auto *output_internal = configure_intermediate_result_vector(input, output);
     if(_is_reshape_required)
     {
         const TensorShape output_shape     = arm_compute::misc::shape_calculator::compute_reduced_shape(input->info()->tensor_shape(), axis, false);
         const auto        output_data_type = input->info()->data_type();
         auto_init_if_empty(*output->info(), input->info()->clone()->set_tensor_shape(output_shape).set_data_type(output_data_type).reset_padding().set_is_resizable(true));
     }
     // Configure reduction operation kernels
     _reduction_kernels_vector.reserve(_num_of_stages);
     // Create temporary tensors
     if(_is_serial)
     {
         if(_is_reshape_required)
         {
             _memory_group.manage(&_results_vector.back());
         }
         _reduction_kernels_vector.emplace_back(std::make_unique<CLReductionOperationKernel>());
         _reduction_kernels_vector[0]->configure(compile_context, input, output_internal, axis, op, 0);
     }
     else
     {
         _border_handlers_vector.reserve(_num_of_stages);
         _memory_group.manage(&_results_vector[0]);
         ReductionOperation first_kernel_op;
         ReductionOperation intermediate_kernel_op;
         ReductionOperation last_kernel_op;
         PixelValue         pixelValue;
         switch(op)
         {
             case ReductionOperation::SUM:
             case ReductionOperation::MEAN_SUM:
                 first_kernel_op        = ReductionOperation::SUM;
                 intermediate_kernel_op = ReductionOperation::SUM;
                 last_kernel_op         = op;
                 pixelValue             = PixelValue();
                 break;
             case ReductionOperation::SUM_SQUARE:
                 first_kernel_op        = ReductionOperation::SUM_SQUARE;
                 intermediate_kernel_op = ReductionOperation::SUM;
                 last_kernel_op         = ReductionOperation::SUM;
                 pixelValue             = PixelValue();
                 break;
             case ReductionOperation::PROD:
                 first_kernel_op        = ReductionOperation::PROD;
                 intermediate_kernel_op = ReductionOperation::PROD;
                 last_kernel_op         = ReductionOperation::PROD;
                 pixelValue             = PixelValue(1, input->info()->data_type());
                 break;
             case ReductionOperation::MIN:
                 first_kernel_op        = ReductionOperation::MIN;
                 intermediate_kernel_op = ReductionOperation::MIN;
                 last_kernel_op         = ReductionOperation::MIN;
                 pixelValue             = std::get<1>(get_min_max(input->info()->data_type()));
                 break;
             case ReductionOperation::MAX:
                 first_kernel_op        = ReductionOperation::MAX;
                 intermediate_kernel_op = ReductionOperation::MAX;
                 last_kernel_op         = ReductionOperation::MAX;
                 pixelValue             = std::get<0>(get_min_max(input->info()->data_type()));
                 break;
             default:
                 ARM_COMPUTE_ERROR("Not supported");
         }
         _reduction_kernels_vector.emplace_back(std::make_unique<CLReductionOperationKernel>());
         _reduction_kernels_vector[0]->configure(compile_context, input, &_results_vector[0], axis, first_kernel_op);
         _border_handlers_vector.emplace_back(std::make_unique<CLFillBorderKernel>());
         _border_handlers_vector[0]->configure(compile_context, input, _reduction_kernels_vector[0]->border_size(), BorderMode::CONSTANT, pixelValue);
         // Apply ReductionOperation on intermediate stages
         for(unsigned int i = 1; i < _num_of_stages - 1; ++i)
         {
             _memory_group.manage(&_results_vector[i]);
             _reduction_kernels_vector.emplace_back(std::make_unique<CLReductionOperationKernel>());
             _reduction_kernels_vector[i]->configure(compile_context, &_results_vector[i - 1], &_results_vector[i], axis, intermediate_kernel_op);
             _border_handlers_vector.emplace_back(std::make_unique<CLFillBorderKernel>());
             _border_handlers_vector[i]->configure(compile_context, &_results_vector[i - 1], _reduction_kernels_vector[i]->border_size(), BorderMode::CONSTANT, pixelValue);
             _results_vector[i - 1].allocator()->allocate();
         }
         // Apply ReductionOperation on the last stage
         const unsigned int last_stage  = _num_of_stages - 1;
         const unsigned int input_width = input->info()->dimension(0);
         if(_is_reshape_required)
         {
             _memory_group.manage(&_results_vector.back());
         }
         _reduction_kernels_vector.emplace_back(std::make_unique<CLReductionOperationKernel>());
         _reduction_kernels_vector[last_stage]->configure(compile_context, &_results_vector[last_stage - 1], output_internal, axis, last_kernel_op, input_width);
         _border_handlers_vector.emplace_back(std::make_unique<CLFillBorderKernel>());
         _border_handlers_vector[last_stage]->configure(compile_context, &_results_vector[last_stage - 1], _reduction_kernels_vector[last_stage]->border_size(), BorderMode::CONSTANT, pixelValue);
         _results_vector[last_stage - 1].allocator()->allocate();
     }
     if(_is_reshape_required)
     {
         _reshape.configure(compile_context, &_results_vector.back(), output);
         _results_vector.back().allocator()->allocate();
     }
 }
operator=() [1/2]
CLReductionOperation& operator= (const CLReductionOperation &) delete
Prevent instances of this class from being copied (As this class contains pointers)
operator=() [2/2]
CLReductionOperation& operator= (CLReductionOperation &&) default
Default move assignment operator.
run()
void run () override virtual
Run the kernels contained in the function.
For Neon kernels:
Multi-threading is used for the kernels which are parallelisable.
By default std::thread::hardware_concurrency() threads are used.
Note
CPPScheduler::set_num_threads() can be used to manually set the number of threads
For OpenCL kernels:
All the kernels are enqueued on the queue associated with CLScheduler.
The queue is then flushed.
Note
The function will not block until the kernels are executed. It is the user's responsibility to wait.
Will call prepare() on first run if hasn't been done
Implements IFunction.
Definition at line 320 of file CLReductionOperation.cpp.
References CLScheduler::enqueue(), CLScheduler::get(), and CLReshapeLayer::run().
Referenced by CLMeanStdDev::configure(), CLL2NormalizeLayer::run(), and CLFFTConvolutionLayer::run().
 {
     MemoryGroupResourceScope scope_mg(_memory_group);
     if(_is_serial)
     {
         CLScheduler::get().enqueue(*_reduction_kernels_vector[0], false);
     }
     else
     {
         for(unsigned int i = 0; i < _num_of_stages; ++i)
         {
             CLScheduler::get().enqueue(*_border_handlers_vector[i], false);
             CLScheduler::get().enqueue(*_reduction_kernels_vector[i], false);
         }
     }
     if(_is_reshape_required)
     {
         _reshape.run();
     }
 }
validate()
Status validate (const ITensorInfo * input, const ITensorInfo * output, unsigned int axis, ReductionOperation op, bool keep_dims = true) static
Static function to check if given info will lead to a valid configuration of CLReductionOperation.
Parameters
[in] input Source tensor info. Data types supported: QASYMM8/QASYMM8_SIGNED/F16/F32/S32.
[in] output Destination tensor info. Data types and data layouts supported: Same as input.
[in] axis Axis along which to reduce. Supported reduction axis : 0, 1, 2, 3
[in] op Reduction operation to perform. Operations supported: MEAN_SUM, PROD, SUM_SQUARE, SUM, MIN, MAX
[in] keep_dims (Optional) Whether to keep the reduced dimension after the operation. Defaults to true.
Returns
a status
Definition at line 48 of file CLReductionOperation.cpp.
References ARM_COMPUTE_ERROR, ARM_COMPUTE_ERROR_ON_NULLPTR, ARM_COMPUTE_RETURN_ERROR_ON_MISMATCHING_SHAPES, ARM_COMPUTE_RETURN_ERROR_ON_MSG, ARM_COMPUTE_RETURN_ON_ERROR, arm_compute::utils::calculate_number_of_stages_only_x_axis(), ICloneable< T >::clone(), arm_compute::misc::shape_calculator::compute_reduced_shape(), arm_compute::test::validation::data_type, ITensorInfo::data_type(), ITensorInfo::dimension(), ITensor::info(), arm_compute::test::validation::input, arm_compute::test::validation::input_shape, arm_compute::MAX, arm_compute::MEAN_SUM, arm_compute::MIN, arm_compute::needs_serialized_reduction(), ITensorInfo::num_channels(), Dimensions< size_t >::num_max_dimensions, arm_compute::PROD, arm_compute::test::validation::qinfo, ITensorInfo::quantization_info(), TensorShape::set(), TensorInfo::set_data_type(), ITensorInfo::set_num_channels(), ITensorInfo::set_quantization_info(), ITensorInfo::set_tensor_shape(), arm_compute::test::validation::shape, arm_compute::SUM, arm_compute::SUM_SQUARE, ITensorInfo::tensor_shape(), ITensorInfo::total_size(), CLReshapeLayer::validate(), and CLReductionOperationKernel::validate().
Referenced by arm_compute::test::validation::DATA_TEST_CASE(), CLMeanStdDev::validate(), and CLL2NormalizeLayer::validate().
 {
     ARM_COMPUTE_ERROR_ON_NULLPTR(input, output);
     ARM_COMPUTE_RETURN_ERROR_ON_MSG(axis >= TensorShape::num_max_dimensions, "Reduction axis greater than max number of dimensions");
     ARM_COMPUTE_RETURN_ERROR_ON_MSG(axis > 3, "Unsupported reduction axis");
     const unsigned int num_of_stages       = utils::calculate_number_of_stages_only_x_axis(input->dimension(0), axis);
     const bool         is_serial           = needs_serialized_reduction(op, input->data_type(), axis);
     const bool         is_reshape_required = !keep_dims;
     if(is_reshape_required && output->total_size() != 0)
     {
         const TensorInfo expected_output_shape = output->clone()->set_tensor_shape(arm_compute::misc::shape_calculator::compute_reduced_shape(input->tensor_shape(), axis, keep_dims));
         ARM_COMPUTE_RETURN_ERROR_ON_MISMATCHING_SHAPES(&expected_output_shape, output);
     }
     auto *output_internal = output;
     TensorInfo output_before_reshape;
     const auto input_shape        = input->tensor_shape();
     const auto input_data_type    = input->data_type();
     const auto input_num_channles = input->num_channels();
     const auto input_qinfo        = input->quantization_info();
     const auto output_data_type   = output->data_type();
     auto initialize_tensorinfo = [](TensorInfo & ti, TensorShape shape, DataType data_type, int num_channels, QuantizationInfo qinfo)
     {
         ti.set_data_type(data_type).set_tensor_shape(shape).set_num_channels(num_channels).set_quantization_info(qinfo);
     };
     if(is_reshape_required)
     {
         auto shape_before_reshape = input_shape;
         shape_before_reshape.set(axis, 1);
         initialize_tensorinfo(output_before_reshape, shape_before_reshape, output_data_type, input_num_channles, input_qinfo);
         output_internal = &output_before_reshape;
     }
     if(is_serial)
     {
         ARM_COMPUTE_RETURN_ON_ERROR(CLReductionOperationKernel::validate(input, output_internal, axis, op));
     }
     else
     {
         // Create temporary tensor infos
         std::vector<TensorInfo> sums_vector(num_of_stages - 1);
         // Create intermediate tensor info
         TensorShape shape{ input_shape };
         shape.set(0, ceil(shape.x() / 128.f));
         for(unsigned int i = 0; i < num_of_stages - 1; i++)
         {
             initialize_tensorinfo(sums_vector[i], shape, input_data_type, input_num_channles, input_qinfo);
         }
         ReductionOperation first_kernel_op;
         ReductionOperation intermediate_kernel_op;
         ReductionOperation last_kernel_op;
         switch(op)
         {
             case ReductionOperation::SUM:
             case ReductionOperation::MEAN_SUM:
                 first_kernel_op        = ReductionOperation::SUM;
                 intermediate_kernel_op = ReductionOperation::SUM;
                 last_kernel_op         = op;
                 break;
             case ReductionOperation::SUM_SQUARE:
                 first_kernel_op        = ReductionOperation::SUM_SQUARE;
                 intermediate_kernel_op = ReductionOperation::SUM;
                 last_kernel_op         = ReductionOperation::SUM;
                 break;
             case ReductionOperation::PROD:
                 first_kernel_op        = ReductionOperation::PROD;
                 intermediate_kernel_op = ReductionOperation::PROD;
                 last_kernel_op         = ReductionOperation::PROD;
                 break;
             case ReductionOperation::MIN:
                 first_kernel_op        = ReductionOperation::MIN;
                 intermediate_kernel_op = ReductionOperation::MIN;
                 last_kernel_op         = ReductionOperation::MIN;
                 break;
             case ReductionOperation::MAX:
                 first_kernel_op        = ReductionOperation::MAX;
                 intermediate_kernel_op = ReductionOperation::MAX;
                 last_kernel_op         = ReductionOperation::MAX;
                 break;
             default:
                 ARM_COMPUTE_ERROR("Not supported");
         }
         // Validate ReductionOperation only on first kernel
         ARM_COMPUTE_RETURN_ON_ERROR(CLReductionOperationKernel::validate(input, &sums_vector[0], axis, first_kernel_op));
         // Validate ReductionOperation on intermediate stages
         for(unsigned int i = 1; i < num_of_stages - 1; ++i)
         {
             ARM_COMPUTE_RETURN_ON_ERROR(CLReductionOperationKernel::validate(&sums_vector[i - 1], &sums_vector[i], axis, intermediate_kernel_op));
         }
         // Validate ReductionOperation on the last stage
         const unsigned int last_stage = num_of_stages - 1;
         ARM_COMPUTE_RETURN_ON_ERROR(CLReductionOperationKernel::validate(&sums_vector[last_stage - 1], output_internal, axis, last_kernel_op, input->dimension(0)));
     }
     if(is_reshape_required)
     {
         ARM_COMPUTE_RETURN_ON_ERROR(CLReshapeLayer::validate(output_internal, output));
     }
     return Status{};
 }
The documentation for this class was generated from the following files:
arm_compute/runtime/CL/functions/CLReductionOperation.h
src/runtime/CL/functions/CLReductionOperation.cpp