Compute Library: GCActivationLayerKernel Class Reference
GCActivationLayerKernel Class Reference
Interface for the activation layer kernel.
#include <GCActivationLayerKernel.h>
Public Member Functions
GCActivationLayerKernel (GCCoreRuntimeContext *ctx=nullptr)
Default constructor.
GCActivationLayerKernel (const GCActivationLayerKernel &)=delete
Prevent instances of this class from being copied (As this class contains pointers)
GCActivationLayerKernel & operator= (const GCActivationLayerKernel &)=delete
Prevent instances of this class from being copied (As this class contains pointers)
GCActivationLayerKernel (GCActivationLayerKernel &&)=default
Allow instances of this class to be moved.
GCActivationLayerKernel & operator= (GCActivationLayerKernel &&)=default
Allow instances of this class to be moved.
~GCActivationLayerKernel ()=default
Default destructor.
void configure (IGCTensor *input, IGCTensor *output, ActivationLayerInfo act_info)
Set the input and output tensor.
void run (const Window &window) override
Enqueue the OpenGL ES shader to process the given window.
Public Member Functions inherited from IGCKernel
IGCKernel ()
Constructor.
GCKernel & kernel ()
Returns a reference to the GLES kernel of this object.
void add_1D_tensor_argument (unsigned int &idx, const IGCTensor *tensor, const unsigned int binding_point, const Window &window)
Add the passed 1D tensor's parameters to the object's kernel's arguments starting from the index idx.
void add_2D_tensor_argument (unsigned int &idx, const IGCTensor *tensor, const unsigned int binding_point, const Window &window)
Add the passed 2D tensor's parameters to the object's kernel's arguments starting from the index idx.
void add_3D_tensor_argument (unsigned int &idx, const IGCTensor *tensor, const unsigned int binding_point, const Window &window)
Add the passed 3D tensor's parameters to the object's kernel's arguments starting from the index idx.
unsigned int num_arguments_per_1D_tensor () const
Returns the number of arguments enqueued per 1D tensor object.
unsigned int num_arguments_per_2D_tensor () const
Returns the number of arguments enqueued per 2D tensor object.
unsigned int num_arguments_per_3D_tensor () const
Returns the number of arguments enqueued per 3D tensor object.
void set_lws_hint (gles::NDRange &lws_hint)
Set the Local-Workgroup-Size hint.
void set_target (GPUTarget target)
Set the targeted GPU architecture.
GPUTarget get_target () const
Get the targeted GPU architecture.
Public Member Functions inherited from IKernel
IKernel ()
Constructor.
virtual ~IKernel ()=default
Destructor.
virtual bool is_parallelisable () const
Indicates whether or not the kernel is parallelisable.
virtual BorderSize border_size () const
The size of the border for that kernel.
const Window & window () const
The maximum window the kernel can be executed on.
Detailed Description
Interface for the activation layer kernel.
Definition at line 36 of file GCActivationLayerKernel.h.
Constructor & Destructor Documentation
GCActivationLayerKernel() [1/3]
GCActivationLayerKernel (GCCoreRuntimeContext * ctx = nullptr) explicit
Default constructor.
Parameters
[in,out] ctx Core context to use
Definition at line 44 of file GCActivationLayerKernel.cpp.
     : _input(nullptr), _output(nullptr), _ctx(ctx)
 {
 }
GCActivationLayerKernel() [2/3]
GCActivationLayerKernel (const GCActivationLayerKernel &) delete
Prevent instances of this class from being copied (As this class contains pointers)
GCActivationLayerKernel() [3/3]
GCActivationLayerKernel (GCActivationLayerKernel &&) default
Allow instances of this class to be moved.
~GCActivationLayerKernel()
~GCActivationLayerKernel () default
Default destructor.
Member Function Documentation
configure()
void configure (IGCTensor * input, IGCTensor * output, ActivationLayerInfo act_info)
Set the input and output tensor.
Note
If the output tensor is a nullptr, the activation function will be performed in-place
Parameters
[in,out] input Source tensor. In case of output tensor = nullptr, this tensor will store the result of the activation function. Data types supported: F16/F32.
[out] output Destination tensor. Data type should match the input data type.
[in] act_info Activation layer information.
Definition at line 49 of file GCActivationLayerKernel.cpp.
References ActivationLayerInfo::a(), ActivationLayerInfo::activation(), ARM_COMPUTE_ERROR_ON_DATA_TYPE_CHANNEL_NOT_IN, ARM_COMPUTE_ERROR_ON_MISMATCHING_DATA_TYPES, ARM_COMPUTE_ERROR_ON_MISMATCHING_SHAPES, arm_compute::auto_init_if_empty(), ActivationLayerInfo::b(), arm_compute::calculate_max_window(), arm_compute::create_opengl_kernel(), ITensorInfo::data_type(), ITensorInfo::element_size(), arm_compute::F16, arm_compute::F32, arm_compute::float_to_string_with_full_precision(), ITensor::info(), arm_compute::test::validation::input, num_elems_processed_per_iteration, ITensorInfo::set_valid_region(), arm_compute::string_from_activation_func(), ITensorInfo::tensor_shape(), arm_compute::support::cpp11::to_string(), and arm_compute::update_window_and_padding().
 {
     ARM_COMPUTE_ERROR_ON_DATA_TYPE_CHANNEL_NOT_IN(input, 1, DataType::F16, DataType::F32);
     // Make sure _kernel is initialized before calling the parent's configure
     _input  = input;
     _output = input;
     if(output != nullptr)
     {
         // Output auto inizialitation if not yet initialized
         auto_init_if_empty(*output->info(), input->info()->tensor_shape(), 1, input->info()->data_type());
         ARM_COMPUTE_ERROR_ON_MISMATCHING_SHAPES(input, output);
         ARM_COMPUTE_ERROR_ON_MISMATCHING_DATA_TYPES(input, output);
         _output = output;
     }
     unsigned int num_elems_processed_per_iteration = 4 / input->info()->element_size();
     // Set build options
     std::set<std::string> build_opts;
     std::string           dt_name = (input->info()->data_type() == DataType::F32) ? "DATA_TYPE_FP32" : "DATA_TYPE_FP16";
     build_opts.emplace(("#define " + string_from_activation_func(act_info.activation())));
     build_opts.emplace(("#define " + dt_name));
     build_opts.emplace(("#define A_VAL " + float_to_string_with_full_precision(act_info.a())));
     build_opts.emplace(("#define B_VAL " + float_to_string_with_full_precision(act_info.b())));
     build_opts.emplace(("#define LOCAL_SIZE_X " + support::cpp11::to_string(1)));
     build_opts.emplace(("#define LOCAL_SIZE_Y " + support::cpp11::to_string(1)));
     build_opts.emplace(("#define LOCAL_SIZE_Z " + support::cpp11::to_string(1)));
     // Create kernel
     _kernel = create_opengl_kernel(_ctx, "activation_layer", build_opts);
     // Configure kernel window
     Window win = calculate_max_window(*input->info(), Steps(num_elems_processed_per_iteration));
     if(output != nullptr)
     {
         AccessWindowHorizontal output_access(output->info(), 0, num_elems_processed_per_iteration);
         update_window_and_padding(win,
                                   AccessWindowHorizontal(input->info(), 0, num_elems_processed_per_iteration),
                                   output_access);
         output->info()->set_valid_region(ValidRegion(Coordinates(), output->info()->tensor_shape()));
     }
     else
     {
         update_window_and_padding(win,
                                   AccessWindowHorizontal(input->info(), 0, num_elems_processed_per_iteration));
     }
     IGCKernel::configure(win);
 }
operator=() [1/2]
GCActivationLayerKernel& operator= (const GCActivationLayerKernel &) delete
Prevent instances of this class from being copied (As this class contains pointers)
operator=() [2/2]
GCActivationLayerKernel& operator= (GCActivationLayerKernel &&) default
Allow instances of this class to be moved.
run()
void run (const Window & window) override virtual
Enqueue the OpenGL ES shader to process the given window.
Parameters
[in] window Region on which to execute the kernel. (Must be a valid region of the window returned by window()).
Implements IGCKernel.
Definition at line 106 of file GCActivationLayerKernel.cpp.
References IGCKernel::add_3D_tensor_argument(), ARM_COMPUTE_ERROR_ON_INVALID_SUBWINDOW, ARM_COMPUTE_ERROR_ON_UNCONFIGURED_KERNEL, Window::collapse_if_possible(), Window::DimX, Window::DimZ, arm_compute::enqueue(), Window::first_slice_window_3D(), ITensor::info(), ITensorInfo::padding(), IGCTensor::set_needs_shifting(), Window::shift(), arm_compute::test::validation::reference::slice(), Window::slide_window_slice_3D(), and IKernel::window().
 {
     ARM_COMPUTE_ERROR_ON_UNCONFIGURED_KERNEL(this);
     ARM_COMPUTE_ERROR_ON_INVALID_SUBWINDOW(IGCKernel::window(), window);
     _kernel.use();
     _output->set_needs_shifting(true);
     Window collapsed = window.collapse_if_possible(IGCKernel::window(), Window::DimZ);
     Window slice     = collapsed.first_slice_window_3D();
     Window slice_in  = collapsed.first_slice_window_3D();
     slice.shift(Window::DimX, -(_output->info()->padding()).left);
     if(_input == _output)
     {
         slice_in.shift(Window::DimX, -(_input->info()->padding()).left);
     }
     do
     {
         unsigned int idx     = 0;
         unsigned int binding = 1;
         add_3D_tensor_argument(idx, _input, binding++, slice);
         add_3D_tensor_argument(idx, _output, binding++, slice_in);
         _kernel.update_shader_params();
         enqueue(*this, slice);
     }
     while(collapsed.slide_window_slice_3D(slice) && collapsed.slide_window_slice_3D(slice_in));
 }
The documentation for this class was generated from the following files:
arm_compute/core/GLES_COMPUTE/kernels/GCActivationLayerKernel.h
src/core/GLES_COMPUTE/kernels/GCActivationLayerKernel.cpp