Compute Library: IGCSimpleFunction Class Reference
IGCSimpleFunction Class Reference
Basic interface for functions which have a single OpenGL ES kernel.
#include <IGCSimpleFunction.h>
Public Member Functions
IGCSimpleFunction (GCRuntimeContext *ctx=nullptr)
Default Constructor.
IGCSimpleFunction (const IGCSimpleFunction &)=delete
Prevent instances of this class from being copied (As this class contains pointers)
IGCSimpleFunction (IGCSimpleFunction &&)=default
Default move constructor.
IGCSimpleFunction & operator= (const IGCSimpleFunction &)=delete
Prevent instances of this class from being copied (As this class contains pointers)
IGCSimpleFunction & operator= (IGCSimpleFunction &&)=default
Default move assignment operator.
void run () override final
Run the kernels contained in the function.
Public Member Functions inherited from IFunction
virtual ~IFunction ()=default
Destructor.
virtual void prepare ()
Prepare the function for executing.
Detailed Description
Basic interface for functions which have a single OpenGL ES kernel.
Definition at line 37 of file IGCSimpleFunction.h.
Constructor & Destructor Documentation
IGCSimpleFunction() [1/3]
IGCSimpleFunction (GCRuntimeContext * ctx = nullptr)
Default Constructor.
Parameters
[in] ctx Runtime context to be used by the function
Definition at line 31 of file IGCSimpleFunction.cpp.
     : _kernel(),
       _border_handler(),
       _ctx(ctx)
 {
 }
IGCSimpleFunction() [2/3]
IGCSimpleFunction (const IGCSimpleFunction &) delete
Prevent instances of this class from being copied (As this class contains pointers)
IGCSimpleFunction() [3/3]
IGCSimpleFunction (IGCSimpleFunction &&) default
Default move constructor.
Member Function Documentation
operator=() [1/2]
IGCSimpleFunction& operator= (const IGCSimpleFunction &) delete
Prevent instances of this class from being copied (As this class contains pointers)
operator=() [2/2]
IGCSimpleFunction& operator= (IGCSimpleFunction &&) default
Default move assignment operator.
run()
void run () final override virtual
Run the kernels contained in the function.
For Neon kernels:
Multi-threading is used for the kernels which are parallelisable.
By default std::thread::hardware_concurrency() threads are used.
Note
CPPScheduler::set_num_threads() can be used to manually set the number of threads
For OpenCL kernels:
All the kernels are enqueued on the queue associated with CLScheduler.
The queue is then flushed.
Note
The function will not block until the kernels are executed. It is the user's responsibility to wait.
Will call prepare() on first run if hasn't been done
Implements IFunction.
Definition at line 38 of file IGCSimpleFunction.cpp.
References ARM_COMPUTE_ERROR_ON, ARM_COMPUTE_ERROR_ON_MSG, GCScheduler::dispatch(), GCScheduler::get(), GCRuntimeContext::gpu_scheduler(), and GCScheduler::memory_barrier().
Referenced by GCFullyConnectedLayer::prepare(), GCDepthwiseConvolutionLayer3x3::run(), and GCConvolutionLayer::run().
 {
     ARM_COMPUTE_ERROR_ON_MSG(!_kernel, "The child class didn't set the GLES kernel or function isn't configured");
     GCScheduler *scheduler = (_ctx != nullptr) ? _ctx->gpu_scheduler() : &GCScheduler::get().get();
     ARM_COMPUTE_ERROR_ON(scheduler == nullptr);
     scheduler->dispatch(_border_handler, false);
     scheduler->memory_barrier();
     scheduler->dispatch(*_kernel);
 }
The documentation for this class was generated from the following files:
arm_compute/runtime/GLES_COMPUTE/IGCSimpleFunction.h
src/runtime/GLES_COMPUTE/IGCSimpleFunction.cpp