Compute Library: CLGEMMReshapeRHSMatrixKernelManaged Class Reference
CLGEMMReshapeRHSMatrixKernelManaged Class Reference
Basic function to manage the reshape weights generated from CLGEMMReshapeRHSMatrixKernel.
#include <CLGEMM.h>
Public Member Functions
CLGEMMReshapeRHSMatrixKernelManaged ()
Default constructor.
CLGEMMReshapeRHSMatrixKernelManaged (const CLGEMMReshapeRHSMatrixKernelManaged &)=delete
Prevent instances of this class from being copied (As this class contains pointers)
CLGEMMReshapeRHSMatrixKernelManaged (CLGEMMReshapeRHSMatrixKernelManaged &&)=default
Default move constructor.
CLGEMMReshapeRHSMatrixKernelManaged & operator= (const CLGEMMReshapeRHSMatrixKernelManaged &)=delete
Prevent instances of this class from being copied (As this class contains pointers)
CLGEMMReshapeRHSMatrixKernelManaged & operator= (CLGEMMReshapeRHSMatrixKernelManaged &&)=default
Default move assignment operator.
~CLGEMMReshapeRHSMatrixKernelManaged ()
Default desctructor.
void run () override
Run the transformation function.
void release () override
Release transformed weights memory.
ICLTensor * get_weights () override
Get a pointer to the transformed weights.
uint32_t uid () override
Function that returns a unique id of the reshape function.
void configure (const ICLTensor *input, GEMMRHSMatrixInfo info)
Configures the CLGEMMReshapeRHSMatrixKernel kernel.
void configure (const CLCompileContext &compile_context, const ICLTensor *input, GEMMRHSMatrixInfo info)
Configures the CLGEMMReshapeRHSMatrixKernel kernel.
Public Member Functions inherited from ITransformWeights
ITransformWeights ()=default
Default Constructor.
virtual ~ITransformWeights ()=default
Default Destructor.
ITransformWeights (const ITransformWeights &)=delete
Prevent instances of this class to be copy constructed.
ITransformWeights & operator= (const ITransformWeights &)=delete
Prevent instances of this class to be copied.
ITransformWeights (ITransformWeights &&other)
Allow instances of this class to be move constructed.
ITransformWeights & operator= (ITransformWeights &&other)
Allow instances of this class to be moved.
void increase_refcount ()
Increase the object's refcount.
int32_t decrease_refcount ()
Decrease the object's refcount and return the updated value.
bool is_reshape_run ()
Function that returns a flag on whether the weights are reshaped or not.
Detailed Description
Basic function to manage the reshape weights generated from CLGEMMReshapeRHSMatrixKernel.
Definition at line 50 of file CLGEMM.h.
Constructor & Destructor Documentation
CLGEMMReshapeRHSMatrixKernelManaged() [1/3]
CLGEMMReshapeRHSMatrixKernelManaged ()
Default constructor.
Definition at line 60 of file CLGEMM.cpp.
References CLGEMMReshapeRHSMatrixKernelManaged::~CLGEMMReshapeRHSMatrixKernelManaged().
     : _kernel(std::make_unique<CLGEMMReshapeRHSMatrixKernel>())
 {
 }
CLGEMMReshapeRHSMatrixKernelManaged() [2/3]
CLGEMMReshapeRHSMatrixKernelManaged (const CLGEMMReshapeRHSMatrixKernelManaged &) delete
Prevent instances of this class from being copied (As this class contains pointers)
CLGEMMReshapeRHSMatrixKernelManaged() [3/3]
CLGEMMReshapeRHSMatrixKernelManaged (CLGEMMReshapeRHSMatrixKernelManaged &&) default
Default move constructor.
~CLGEMMReshapeRHSMatrixKernelManaged()
~CLGEMMReshapeRHSMatrixKernelManaged () default
Default desctructor.
Referenced by CLGEMMReshapeRHSMatrixKernelManaged::CLGEMMReshapeRHSMatrixKernelManaged().
Member Function Documentation
configure() [1/2]
void configure (const ICLTensor * input, GEMMRHSMatrixInfo info)
Configures the CLGEMMReshapeRHSMatrixKernel kernel.
Parameters
[in] input Input tensor. Data types supported: All
[in] info RHS matrix information to be used for reshaping.
Definition at line 89 of file CLGEMM.cpp.
References CLKernelLibrary::get().
 {
     configure(CLKernelLibrary::get().get_compile_context(), input, info);
 }
configure() [2/2]
void configure (const CLCompileContext & compile_context, const ICLTensor * input, GEMMRHSMatrixInfo info)
Configures the CLGEMMReshapeRHSMatrixKernel kernel.
Parameters
[in] compile_context The compile context to be used.
[in] input Input tensor. Data types supported: All
[in] info RHS matrix information to be used for reshaping.
Definition at line 94 of file CLGEMM.cpp.
References ARM_COMPUTE_LOG_INFO_MSG_WITH_FORMAT_CORE, arm_compute::auto_init_if_empty(), arm_compute::test::validation::b, ICloneable< T >::clone(), arm_compute::misc::shape_calculator::compute_lhs_reshaped_shape(), arm_compute::misc::shape_calculator::compute_rhs_reshaped_shape(), GEMMKernelInfo::has_pad_y, GEMMKernelInfo::lhs_info, arm_compute::NATIVE_V1, arm_compute::RESHAPED, arm_compute::RESHAPED_ONLY_RHS, arm_compute::RESHAPED_V1, GEMMKernelInfo::rhs_info, arm_compute::cl_gemm::auto_heuristics::select_default_gemm_config_reshaped(), arm_compute::cl_gemm::auto_heuristics::select_default_gemm_config_reshaped_only_rhs(), arm_compute::cl_gemm::auto_heuristics::select_default_gemm_kernel(), arm_compute::cl_gemm::auto_heuristics::select_mlgo_gemm_config_reshaped(), arm_compute::cl_gemm::auto_heuristics::select_mlgo_gemm_config_reshaped_only_rhs(), arm_compute::cl_gemm::auto_heuristics::select_mlgo_gemm_kernel(), arm_compute::to_string(), CLGEMMReshapeLHSMatrixKernel::validate(), CLGEMMReshapeRHSMatrixKernel::validate(), CLGEMMMatrixMultiplyReshapedOnlyRHSKernel::validate(), and CLGEMMMatrixMultiplyReshapedKernel::validate().
 {
     _kernel->configure(compile_context, input, &_output, info);
 }
get_weights()
ICLTensor * get_weights () override virtual
Get a pointer to the transformed weights.
Returns
The pointer to the transformed ITensor weights
Implements ITransformWeights.
Definition at line 79 of file CLGEMM.cpp.
 {
     return &_output;
 }
operator=() [1/2]
CLGEMMReshapeRHSMatrixKernelManaged& operator= (const CLGEMMReshapeRHSMatrixKernelManaged &) delete
Prevent instances of this class from being copied (As this class contains pointers)
operator=() [2/2]
CLGEMMReshapeRHSMatrixKernelManaged& operator= (CLGEMMReshapeRHSMatrixKernelManaged &&) default
Default move assignment operator.
release()
void release () override virtual
Release transformed weights memory.
Implements ITransformWeights.
Definition at line 74 of file CLGEMM.cpp.
References CLTensor::allocator(), and CLTensorAllocator::free().
 {
     _output.allocator()->free();
 }
run()
void run () override virtual
Run the transformation function.
Implements ITransformWeights.
Definition at line 67 of file CLGEMM.cpp.
References CLTensorAllocator::allocate(), CLTensor::allocator(), CLScheduler::enqueue(), and CLScheduler::get().
 {
     _output.allocator()->allocate();
     CLScheduler::get().enqueue(*_kernel, false);
     _reshape_run = true;
 }
uid()
uint32_t uid () override virtual
Function that returns a unique id of the reshape function.
Returns
The computed unique id
Implements ITransformWeights.
Definition at line 84 of file CLGEMM.cpp.
 {
     return _uid;
 }
The documentation for this class was generated from the following files:
arm_compute/runtime/CL/functions/CLGEMM.h
src/runtime/CL/functions/CLGEMM.cpp