Compute Library: CpuPoolingKernel Class Reference
CpuPoolingKernel Class Reference
Interface for the pooling layer kernel.
#include <CpuPoolingKernel.h>
Public Member Functions
CpuPoolingKernel ()=default
Default constructor.
ARM_COMPUTE_DISALLOW_COPY_ALLOW_MOVE (CpuPoolingKernel)
void configure (ITensorInfo *src, ITensorInfo *dst, const PoolingLayerInfo &pool_info, ITensorInfo *indices=nullptr)
Configure kernel for a given list of arguments.
void run_op (ITensorPack &tensors, const Window &window, const ThreadInfo &info) override
Execute the kernel on the passed window.
BorderSize border_size () const override
The size of the border for that kernel.
const char * name () const override
Name of the kernel.
Public Member Functions inherited from ICPPKernel
virtual ~ICPPKernel ()=default
Default destructor.
virtual void run (const Window &window, const ThreadInfo &info)
Execute the kernel on the passed window.
virtual void run_nd (const Window &window, const ThreadInfo &info, const Window &thread_locator)
legacy compatibility layer for implemantions which do not support thread_locator In these cases we simply narrow the interface down the legacy version
Public Member Functions inherited from IKernel
IKernel ()
Constructor.
virtual ~IKernel ()=default
Destructor.
virtual bool is_parallelisable () const
Indicates whether or not the kernel is parallelisable.
const Window & window () const
The maximum window the kernel can be executed on.
Static Public Member Functions
static Status validate (const ITensorInfo *src, const ITensorInfo *dst, const PoolingLayerInfo &pool_info, const ITensorInfo *indices=nullptr)
Static function to check if given info will lead to a valid configuration of CpuPoolingKernel.
Detailed Description
Interface for the pooling layer kernel.
Definition at line 38 of file CpuPoolingKernel.h.
Constructor & Destructor Documentation
CpuPoolingKernel()
CpuPoolingKernel () default
Default constructor.
Member Function Documentation
ARM_COMPUTE_DISALLOW_COPY_ALLOW_MOVE()
ARM_COMPUTE_DISALLOW_COPY_ALLOW_MOVE (CpuPoolingKernel)
border_size()
BorderSize border_size () const override virtual
The size of the border for that kernel.
Returns
The width in number of elements of the border.
Reimplemented from IKernel.
Definition at line 380 of file CpuPoolingKernel.cpp.
 {
     return _border_size;
 }
configure()
void configure (ITensorInfo * src, ITensorInfo * dst, const PoolingLayerInfo & pool_info, ITensorInfo * indices = nullptr)
Configure kernel for a given list of arguments.
Note
F16 are supported for pool sizes 2 and 3 only
Parameters
[in] src Source tensor info. Data types supported: QASYMM8/QASYMM8_SIGNED/F16/F32.
[out] dst Destination tensor info. Data types supported: Same as src.
[in] pool_info Contains pooling operation information described in PoolingLayerInfo.
[out] indices (optional) The indices of the maximal values. Data type supported: U32.
Definition at line 385 of file CpuPoolingKernel.cpp.
References ARM_COMPUTE_ERROR_ON_NULLPTR, ARM_COMPUTE_ERROR_THROW_ON, arm_compute::calculate_max_window(), arm_compute::test::validation::data_layout, ITensorInfo::data_layout(), PoolingLayerInfo::data_layout, ITensorInfo::dimension(), arm_compute::get_data_layout_dimension_index(), Size2D::height, arm_compute::HEIGHT, arm_compute::test::validation::idx_height, arm_compute::test::validation::idx_width, PoolingLayerInfo::is_global_pooling, arm_compute::NHWC, ITensorInfo::num_dimensions(), PoolingLayerInfo::pad_stride_info, pool_size, PoolingLayerInfo::pool_size, arm_compute::scaled_dimensions(), Dimensions< T >::set_num_dimensions(), ITensorInfo::set_valid_region(), PadStrideInfo::stride(), ITensorInfo::tensor_shape(), arm_compute::UNKNOWN, arm_compute::validate_arguments(), Size2D::width, and arm_compute::WIDTH.
 {
     ARM_COMPUTE_ERROR_ON_NULLPTR(src, dst);
     const PadStrideInfo pad_stride_info   = pool_info.pad_stride_info;
     const bool          is_global_pooling = pool_info.is_global_pooling;
     // Get data layout
     const auto data_layout = pool_info.data_layout == DataLayout::UNKNOWN ? src->data_layout() : pool_info.data_layout;
     const int  idx_width   = get_data_layout_dimension_index(data_layout, DataLayoutDimension::WIDTH);
     const int  idx_height  = get_data_layout_dimension_index(data_layout, DataLayoutDimension::HEIGHT);
     // Update pool size in case of global pooling
     const Size2D pool_size(
         is_global_pooling ? src->dimension(idx_width) : pool_info.pool_size.width,
         is_global_pooling ? src->dimension(idx_height) : pool_info.pool_size.height);
     // Validate pool info before calling scaled_dimensions
     ARM_COMPUTE_ERROR_THROW_ON(validate_arguments_pool_info(pool_size.x(), pool_size.y()));
     // Check dst dimensions
     unsigned int pooled_w;
     unsigned int pooled_h;
     std::tie(pooled_w, pooled_h) = scaled_dimensions(src->dimension(idx_width),
                                                      src->dimension(idx_height),
                                                      pool_size.x(),
                                                      pool_size.y(),
                                                      pad_stride_info);
     // Perform validation step
     ARM_COMPUTE_ERROR_THROW_ON(validate_arguments(src, dst, pool_info, pooled_w, pooled_h, indices, pool_size));
     // Set instance variables
     _pool_info     = pool_info;
     _data_layout   = src->data_layout();
     _pool_size     = pool_size;
     _pool_stride_x = pad_stride_info.stride().first;
     if(_data_layout == DataLayout::NHWC)
     {
         // Configure kernel window
         Window      win = calculate_max_window(*dst, Steps());
         Coordinates coord;
         coord.set_num_dimensions(dst->num_dimensions());
         dst->set_valid_region(ValidRegion(coord, dst->tensor_shape()));
         ICpuKernel::configure(win);
     }
     else
     {
         // Configure kernel window
         auto win_config = validate_and_configure_window(src, dst, indices, pool_info, _num_elems_processed_per_iteration,
                                                         _border_size, pooled_w, pooled_h, pool_size.x(), pool_size.y());
         ARM_COMPUTE_ERROR_THROW_ON(win_config.first);
         ICpuKernel::configure(win_config.second);
     }
 }
name()
const char * name () const override virtual
Name of the kernel.
Returns
Kernel name
Implements ICPPKernel.
Definition at line 540 of file CpuPoolingKernel.cpp.
 {
     return "CpuPoolingKernel";
 }
run_op()
void run_op (ITensorPack & tensors, const Window & window, const ThreadInfo & info) override virtual
Execute the kernel on the passed window.
Warning
If is_parallelisable() returns false then the passed window must be equal to window()
Note
The window has to be a region within the window returned by the window() method
The width of the window has to be a multiple of num_elems_processed_per_iteration().
Parameters
[in] tensors A vector containing the tensors to operate on.
[in] window Region on which to execute the kernel. (Must be a region of the window returned by window())
[in] info Info about executing thread and CPU.
Reimplemented from ICPPKernel.
Definition at line 481 of file CpuPoolingKernel.cpp.
References arm_compute::ACL_DST_0, arm_compute::ACL_DST_1, arm_compute::ACL_SRC_0, ARM_COMPUTE_ERROR, ARM_COMPUTE_ERROR_ON, ARM_COMPUTE_ERROR_ON_INVALID_SUBWINDOW, ARM_COMPUTE_ERROR_ON_UNCONFIGURED_KERNEL, ARM_COMPUTE_UNUSED, ITensorInfo::data_type(), ITensorInfo::dimension(), Window::DimX, Window::DimY, Window::DimZ, arm_compute::test::validation::dst, Window::Dimension::end(), arm_compute::F16, arm_compute::F32, ITensorPack::get_const_tensor(), ITensorPack::get_tensor(), ITensor::info(), arm_compute::NCHW, pool_size, pool_stride_x, arm_compute::QASYMM8, arm_compute::QASYMM8_SIGNED, Window::set(), arm_compute::test::validation::src, Window::Dimension::start(), IKernel::window(), Window::x(), and Window::y().
 {
     ARM_COMPUTE_UNUSED(info);
     ARM_COMPUTE_ERROR_ON_UNCONFIGURED_KERNEL(this);
     ARM_COMPUTE_ERROR_ON_INVALID_SUBWINDOW(ICpuKernel::window(), window);
     const ITensor *src     = tensors.get_const_tensor(TensorType::ACL_SRC_0);
     ITensor       *dst     = tensors.get_tensor(TensorType::ACL_DST_0);
     ITensor       *indices = tensors.get_tensor(TensorType::ACL_DST_1);
     const unsigned int pool_stride_x = _pool_info.pad_stride_info.stride().first;
     const unsigned int pool_stride_y = _pool_info.pad_stride_info.stride().second;
     const unsigned int pool_size     = _pool_info.pool_size.width;
     Window window_src(window);
     if(_data_layout == DataLayout::NCHW)
     {
         // Set step for src in x and y direction for the src
         unsigned int window_x_inc = 0;
         switch(src->info()->data_type())
         {
             case DataType::QASYMM8:
             case DataType::QASYMM8_SIGNED:
             {
                 window_x_inc = pool_stride_x;
                 if((pool_size == 2 || pool_size == 3) && pool_stride_x < 3)
                 {
                     window_x_inc = (pool_stride_x == 2) ? _num_elems_processed_per_iteration * 2 : _num_elems_processed_per_iteration;
                 }
                 break;
             }
             case DataType::F16:
             case DataType::F32:
             {
                 window_x_inc = pool_stride_x;
                 break;
             }
             default:
             {
                 ARM_COMPUTE_ERROR("Not supported");
             }
         }
         window_src.set(Window::DimX, Window::Dimension(window.x().start() * pool_stride_x, window.x().end() * pool_stride_x, window_x_inc));
         window_src.set(Window::DimY, Window::Dimension(window.y().start() * pool_stride_y, window.y().end() * pool_stride_y, pool_stride_y));
     }
     else
     {
         window_src.set(Window::DimX, Window::Dimension(0, 1, 1));
         window_src.set(Window::DimY, Window::Dimension(0, src->info()->dimension(1), pool_stride_x));
         window_src.set(Window::DimZ, Window::Dimension(0, src->info()->dimension(2), pool_stride_y));
     }
     const auto *uk = get_implementation(src->info()->data_type(), _data_layout, _pool_stride_x, _pool_size);
     ARM_COMPUTE_ERROR_ON(uk == nullptr || uk->ukernel == nullptr);
     uk->ukernel(src, dst, indices, _pool_info, window_src, window);
 }
validate()
Status validate (const ITensorInfo * src, const ITensorInfo * dst, const PoolingLayerInfo & pool_info, const ITensorInfo * indices = nullptr) static
Static function to check if given info will lead to a valid configuration of CpuPoolingKernel.
Note
F16 are supported for pool sizes 2 and 3 only
Parameters
[in] src Source tensor info. Data types supported: QASYMM8/QASYMM8_SIGNED/F16/F32.
[in] dst Destination tensor info. Data types supported: Same as src.
[in] pool_info Contains pooling operation information described in PoolingLayerInfo.
[in] indices (optional) The indices of the maximal values. Data type supported: U32.
Returns
a status
Definition at line 441 of file CpuPoolingKernel.cpp.
References ARM_COMPUTE_RETURN_ERROR_ON_NULLPTR, ARM_COMPUTE_RETURN_ON_ERROR, ICloneable< T >::clone(), arm_compute::test::validation::data_layout, ITensorInfo::data_layout(), PoolingLayerInfo::data_layout, ITensorInfo::dimension(), arm_compute::get_data_layout_dimension_index(), Size2D::height, arm_compute::HEIGHT, arm_compute::test::validation::idx_height, arm_compute::test::validation::idx_width, PoolingLayerInfo::is_global_pooling, num_elems_processed_per_iteration, PoolingLayerInfo::pad_stride_info, PoolingLayerInfo::pool_size, arm_compute::scaled_dimensions(), arm_compute::UNKNOWN, arm_compute::validate_arguments(), Size2D::width, and arm_compute::WIDTH.
Referenced by CpuPooling::validate().
 {
     ARM_COMPUTE_RETURN_ERROR_ON_NULLPTR(src);
     unsigned int pooled_w                          = 0;
     unsigned int pooled_h                          = 0;
     unsigned int num_elems_processed_per_iteration = 0;
     BorderSize   border_size(0);
     const bool   is_global_pooling = pool_info.is_global_pooling;
     unsigned int pool_size_x       = 0;
     unsigned int pool_size_y       = 0;
     // Get data layout
     const auto data_layout = pool_info.data_layout == DataLayout::UNKNOWN ? src->data_layout() : pool_info.data_layout;
     const int  idx_width   = get_data_layout_dimension_index(data_layout, DataLayoutDimension::WIDTH);
     const int  idx_height  = get_data_layout_dimension_index(data_layout, DataLayoutDimension::HEIGHT);
     pool_size_x = is_global_pooling ? src->dimension(idx_width) : pool_info.pool_size.width;
     pool_size_y = is_global_pooling ? src->dimension(idx_height) : pool_info.pool_size.height;
     // Validate pool info before calling scaled_dimensions
     ARM_COMPUTE_RETURN_ON_ERROR(validate_arguments_pool_info(pool_size_x, pool_size_y));
     // Check dst dimensions
     std::tie(pooled_w, pooled_h) = scaled_dimensions(src->dimension(idx_width),
                                                      src->dimension(idx_height),
                                                      pool_size_x,
                                                      pool_size_y,
                                                      pool_info.pad_stride_info);
     ARM_COMPUTE_RETURN_ON_ERROR(validate_arguments(src, dst, pool_info, pooled_w, pooled_h, indices, Size2D(pool_size_x, pool_size_y)));
     ARM_COMPUTE_RETURN_ON_ERROR(validate_and_configure_window(src->clone().get(), dst->clone().get(),
                                                               (indices) ? indices->clone().get() : nullptr, pool_info, num_elems_processed_per_iteration, border_size, pooled_w, pooled_h,
                                                               pool_size_x, pool_size_y)
                                 .first);
     return Status{};
 }
The documentation for this class was generated from the following files:
src/core/cpu/kernels/CpuPoolingKernel.h
src/core/cpu/kernels/CpuPoolingKernel.cpp