Compute Library: CLGEMMLowpQuantizeDownInt32ToUint8ScaleByFixedPoint Class Reference
CLGEMMLowpQuantizeDownInt32ToUint8ScaleByFixedPoint Class Reference
Basic function to execute CLGEMMLowpQuantizeDownInt32ToUint8ScaleByFixedPoint on OpenCL.
#include <CLGEMMLowpOutputStage.h>
Public Member Functions
void configure (const ICLTensor *input, const ICLTensor *bias, ICLTensor *output, int result_fixedpoint_multiplier, int result_shift, int result_offset_after_shift, int min=std::numeric_limits< int32_t >::lowest(), int max=std::numeric_limits< int32_t >::max())
Initialise the kernel's inputs, output.
void configure (const CLCompileContext &compile_context, const ICLTensor *input, const ICLTensor *bias, ICLTensor *output, int result_fixedpoint_multiplier, int result_shift, int result_offset_after_shift, int min=std::numeric_limits< int32_t >::lowest(), int max=std::numeric_limits< int32_t >::max())
Initialise the kernel's inputs, output.
Public Member Functions inherited from ICLSimpleFunction
ICLSimpleFunction (CLRuntimeContext *ctx=nullptr)
Constructor.
ICLSimpleFunction (const ICLSimpleFunction &)=delete
Prevent instances of this class from being copied (As this class contains pointers)
ICLSimpleFunction (ICLSimpleFunction &&)=default
Default move constructor.
ICLSimpleFunction & operator= (const ICLSimpleFunction &)=delete
Prevent instances of this class from being copied (As this class contains pointers)
ICLSimpleFunction & operator= (ICLSimpleFunction &&)=default
Default move assignment operator.
~ICLSimpleFunction ()
Default destructor.
void run () override final
Run the kernels contained in the function.
Public Member Functions inherited from IFunction
virtual ~IFunction ()=default
Destructor.
virtual void prepare ()
Prepare the function for executing.
Static Public Member Functions
static Status validate (const ITensorInfo *input, const ITensorInfo *bias, const ITensorInfo *output, int min=std::numeric_limits< int32_t >::lowest(), int max=std::numeric_limits< int32_t >::max())
Static function to check if given info will lead to a valid configuration of CLGEMMLowpQuantizeDownInt32ToUint8ScaleByFixedPoint.
Detailed Description
Basic function to execute CLGEMMLowpQuantizeDownInt32ToUint8ScaleByFixedPoint on OpenCL.
CLGEMMLowpQuantizeDownInt32ToUint8ScaleByFixedPoint depends on 3 parameters:
result_fixedpoint_multiplier, result_shift, result_offset_after_shift
The final result is:
(FixedPointMul(input[i][k], result_fixedpoint_multiplier) >> result_shift) + result_offset_after_shift
where FixedPointMul(x, y) is the nearest integer to the following mathematical expression, evaluated without overflow or intermediate rounding:
(x * y) / 2^31
For more information: https://github.com/google/gemmlowp/blob/master/public/output_stages.h#L68
In case the bias tensor is provided, the final result is:
((FixedPointMul(input[i][k] + bias[k], result_fixedpoint_multiplier)) >> result_shift) + result_offset_after_shift
This function calls the following OpenCL kernels:
CLGEMMLowpQuantizeDownInt32ScaleByFixedPointKernel
Note
The function accepts also 2 optional input arguments (min and max) which can be used to implement "rectified linear unit" activation functions after the result is shifted right by result_shift
Definition at line 76 of file CLGEMMLowpOutputStage.h.
Member Function Documentation
configure() [1/2]
void configure (const ICLTensor * input, const ICLTensor * bias, ICLTensor * output, int result_fixedpoint_multiplier, int result_shift, int result_offset_after_shift, int min = std::numeric_limits<int32_t>::lowest(), int max = std::numeric_limits<int32_t>::max())
Initialise the kernel's inputs, output.
Parameters
[in] input Input tensor. Data type supported: S32
[in] bias Biases tensor. Only shared biases supported and it can be a nullptr if the biases addition is not required. Biases are 1D tensor with dimensions [OFM]. Data type supported: Same as input.
[out] output Output tensor. Data type supported: QASYMM8
[in] result_fixedpoint_multiplier Fixed point value to be multiplied to each element of the input matrix when once the result_offset has been add
[in] result_shift Number of bits to shift right the result after the fixed point multiplication
[in] result_offset_after_shift Offset to be applied to result before converting it back to QASYMM8
[in] min (Optional) Min value used to saturate down the output result before converting back to QASYMM8. Defaults to the minimum possible 32-bit signed integer.
[in] max (Optional) Max value used to saturate up the output result before converting back to QASYMM8, Along with min, this value can be used to implement "rectified linear unit" activation functions. Defaults to the maximum possible 32-bit signed integer.
Definition at line 36 of file CLGEMMLowpOutputStage.cpp.
References CLKernelLibrary::get().
Referenced by CLGEMMLowpQuantizeDownInt32ToInt8ScaleByFixedPoint::configure(), CLGEMMLowpQuantizeDownInt32ToInt16ScaleByFixedPoint::configure(), and CLGEMMLowpOutputStage::configure().
 {
     configure(CLKernelLibrary::get().get_compile_context(), input, bias, output, result_fixedpoint_multiplier, result_shift, result_offset_after_shift, min, max);
 }
configure() [2/2]
void configure (const CLCompileContext & compile_context, const ICLTensor * input, const ICLTensor * bias, ICLTensor * output, int result_fixedpoint_multiplier, int result_shift, int result_offset_after_shift, int min = std::numeric_limits<int32_t>::lowest(), int max = std::numeric_limits<int32_t>::max())
Initialise the kernel's inputs, output.
Parameters
[in] compile_context The compile context to be used.
[in] input Input tensor. Data type supported: S32
[in] bias Biases tensor. Only shared biases supported and it can be a nullptr if the biases addition is not required. Biases are 1D tensor with dimensions [OFM]. Data type supported: Same as input.
[out] output Output tensor. Data type supported: QASYMM8
[in] result_fixedpoint_multiplier Fixed point value to be multiplied to each element of the input matrix when once the result_offset has been add
[in] result_shift Number of bits to shift right the result after the fixed point multiplication
[in] result_offset_after_shift Offset to be applied to result before converting it back to QASYMM8
[in] min (Optional) Min value used to saturate down the output result before converting back to QASYMM8. Defaults to the minimum possible 32-bit signed integer.
[in] max (Optional) Max value used to saturate up the output result before converting back to QASYMM8, Along with min, this value can be used to implement "rectified linear unit" activation functions. Defaults to the maximum possible 32-bit signed integer.
Definition at line 43 of file CLGEMMLowpOutputStage.cpp.
References arm_compute::test::validation::info, and arm_compute::QASYMM8.
 {
     GEMMLowpOutputStageInfo info{};
     info.gemmlowp_multiplier = result_fixedpoint_multiplier;
     info.gemmlowp_shift      = result_shift;
     info.gemmlowp_offset     = result_offset_after_shift;
     info.gemmlowp_min_bound  = min;
     info.gemmlowp_max_bound  = max;
     info.output_data_type    = DataType::QASYMM8;
     auto k                   = std::make_unique<CLGEMMLowpQuantizeDownInt32ScaleByFixedPointKernel>();
     k->configure(compile_context, input, bias, output, &info);
     _kernel = std::move(k);
 }
validate()
Status validate (const ITensorInfo * input, const ITensorInfo * bias, const ITensorInfo * output, int min = std::numeric_limits<int32_t>::lowest(), int max = std::numeric_limits<int32_t>::max()) static
Static function to check if given info will lead to a valid configuration of CLGEMMLowpQuantizeDownInt32ToUint8ScaleByFixedPoint.
Parameters
[in] input Input tensor. It is the output of CLGEMMLowpMatrixMultiplyCore function. Data type supported: S32
[in] bias Biases tensor. Only shared biases supported and it can be a nullptr if the addition of biases is not required. Biases are 1D tensor with dimensions [OFM]. Data type supported: Same as input.
[in] output Output tensor. Data type supported: QASYMM8
[in] min (Optional) Min value used to saturate down the output result before converting back to QASYMM8. Defaults to the minimum possible 32-bit signed integer.
[in] max (Optional) Max value used to saturate up the output result before converting back to QASYMM8, Along with min, this value can be used to implement "rectified linear unit" activation functions. Defaults to the maximum possible 32-bit signed integer.
Returns
a status
Definition at line 59 of file CLGEMMLowpOutputStage.cpp.
References arm_compute::test::validation::info, arm_compute::QASYMM8, and CLGEMMLowpQuantizeDownInt32ScaleByFixedPointKernel::validate().
 {
     GEMMLowpOutputStageInfo info{};
     info.gemmlowp_min_bound = min;
     info.gemmlowp_max_bound = max;
     info.output_data_type   = DataType::QASYMM8;
     return CLGEMMLowpQuantizeDownInt32ScaleByFixedPointKernel::validate(input, bias, output, &info);
 }
The documentation for this class was generated from the following files:
arm_compute/runtime/CL/functions/CLGEMMLowpOutputStage.h
src/runtime/CL/functions/CLGEMMLowpOutputStage.cpp