Compute Library: CLCannyEdge Class Reference
CLCannyEdge Class Reference
Basic function to execute canny edge on OpenCL.
#include <CLCannyEdge.h>
Public Member Functions
CLCannyEdge (std::shared_ptr< IMemoryManager > memory_manager=nullptr)
Constructor.
CLCannyEdge (const CLCannyEdge &)=delete
Prevent instances of this class from being copied (As this class contains pointers)
CLCannyEdge & operator= (const CLCannyEdge &)=delete
Prevent instances of this class from being copied (As this class contains pointers)
~CLCannyEdge ()
Default destructor.
void configure (ICLTensor *input, ICLTensor *output, int32_t upper_thr, int32_t lower_thr, int32_t gradient_size, int32_t norm_type, BorderMode border_mode, uint8_t constant_border_value=0)
Initialise the function's source, destination, thresholds, gradient size, normalization type and border mode.
void configure (const CLCompileContext &compile_context, ICLTensor *input, ICLTensor *output, int32_t upper_thr, int32_t lower_thr, int32_t gradient_size, int32_t norm_type, BorderMode border_mode, uint8_t constant_border_value=0)
Initialise the function's source, destination, thresholds, gradient size, normalization type and border mode.
virtual void run () override
Run the kernels contained in the function.
Public Member Functions inherited from IFunction
virtual ~IFunction ()=default
Destructor.
virtual void prepare ()
Prepare the function for executing.
Detailed Description
Basic function to execute canny edge on OpenCL.
This function calls the following OpenCL kernels and functions:
CLFillBorderKernel (if border_mode == REPLICATE or border_mode == CONSTANT)
CLSobel3x3 (if gradient_size == 3) or CLSobel5x5 (if gradient_size == 5) or CLSobel7x7 (if gradient_size == 7)
CLGradientKernel
CLEdgeNonMaxSuppressionKernel
CLEdgeTraceKernel
Deprecated:
This function is deprecated and is intended to be removed in 21.05 release
Definition at line 55 of file CLCannyEdge.h.
Constructor & Destructor Documentation
CLCannyEdge() [1/2]
CLCannyEdge (std::shared_ptr< IMemoryManager > memory_manager = nullptr)
Constructor.
Definition at line 41 of file CLCannyEdge.cpp.
     : _memory_group(std::move(memory_manager)),
       _sobel(),
       _gradient(std::make_unique<CLGradientKernel>()),
       _border_mag_gradient(std::make_unique<CLFillBorderKernel>()),
       _non_max_suppr(std::make_unique<CLEdgeNonMaxSuppressionKernel>()),
       _edge_trace(std::make_unique<CLEdgeTraceKernel>()),
       _gx(),
       _gy(),
       _mag(),
       _phase(),
       _nonmax(),
       _visited(),
       _recorded(),
       _l1_list_counter(),
       _l1_stack(),
       _output(nullptr)
 {
 }
CLCannyEdge() [2/2]
CLCannyEdge (const CLCannyEdge &) delete
Prevent instances of this class from being copied (As this class contains pointers)
~CLCannyEdge()
~CLCannyEdge () default
Default destructor.
Member Function Documentation
configure() [1/2]
void configure (ICLTensor * input, ICLTensor * output, int32_t upper_thr, int32_t lower_thr, int32_t gradient_size, int32_t norm_type, BorderMode border_mode, uint8_t constant_border_value = 0)
Initialise the function's source, destination, thresholds, gradient size, normalization type and border mode.
Parameters
[in,out] input Source tensor. Data types supported: U8. (Written to only for border_mode != UNDEFINED)
[out] output Destination tensor. Data types supported: U8.
[in] upper_thr Upper threshold used for the hysteresis.
[in] lower_thr Lower threshold used for the hysteresis.
[in] gradient_size Gradient size (3, 5 or 7).
[in] norm_type Normalization type. if 1, L1-Norm otherwise L2-Norm.
[in] border_mode Border mode to use for the convolution.
[in] constant_border_value (Optional) Constant value to use for borders if border_mode is set to CONSTANT.
Definition at line 63 of file CLCannyEdge.cpp.
References CLKernelLibrary::get().
 {
     configure(CLKernelLibrary::get().get_compile_context(), input, output, upper_thr, lower_thr, gradient_size, norm_type, border_mode, constant_border_value);
 }
configure() [2/2]
void configure (const CLCompileContext & compile_context, ICLTensor * input, ICLTensor * output, int32_t upper_thr, int32_t lower_thr, int32_t gradient_size, int32_t norm_type, BorderMode border_mode, uint8_t constant_border_value = 0)
Initialise the function's source, destination, thresholds, gradient size, normalization type and border mode.
Parameters
[in] compile_context The compile context to be used.
[in,out] input Source tensor. Data types supported: U8. (Written to only for border_mode != UNDEFINED)
[out] output Destination tensor. Data types supported: U8.
[in] upper_thr Upper threshold used for the hysteresis.
[in] lower_thr Lower threshold used for the hysteresis.
[in] gradient_size Gradient size (3, 5 or 7).
[in] norm_type Normalization type. if 1, L1-Norm otherwise L2-Norm.
[in] border_mode Border mode to use for the convolution.
[in] constant_border_value (Optional) Constant value to use for borders if border_mode is set to CONSTANT.
Definition at line 69 of file CLCannyEdge.cpp.
References CLTensorAllocator::allocate(), CLTensor::allocator(), ARM_COMPUTE_ERROR_ON, ARM_COMPUTE_ERROR_ON_DATA_TYPE_CHANNEL_NOT_IN, ARM_COMPUTE_ERROR_ON_NULLPTR, ARM_COMPUTE_ERROR_VAR, ITensorInfo::dimension(), ITensor::info(), arm_compute::test::validation::info, ITensorAllocator::init(), TensorInfo::init(), MemoryGroup::manage(), arm_compute::S16, arm_compute::S32, TensorShape::set(), arm_compute::test::validation::shape, ITensorInfo::tensor_shape(), arm_compute::U16, arm_compute::U32, arm_compute::U8, and arm_compute::UNDEFINED.
 {
     ARM_COMPUTE_ERROR_ON_NULLPTR(input, output);
     ARM_COMPUTE_ERROR_ON_DATA_TYPE_CHANNEL_NOT_IN(input, 1, DataType::U8);
     ARM_COMPUTE_ERROR_ON_DATA_TYPE_CHANNEL_NOT_IN(output, 1, DataType::U8);
     ARM_COMPUTE_ERROR_ON((1 != norm_type) && (2 != norm_type));
     ARM_COMPUTE_ERROR_ON((gradient_size != 3) && (gradient_size != 5) && (gradient_size != 7));
     ARM_COMPUTE_ERROR_ON((lower_thr < 0) || (lower_thr >= upper_thr));
     _output = output;
     const unsigned int L1_hysteresis_stack_size = 8;
     const TensorShape  shape                    = input->info()->tensor_shape();
     TensorInfo gradient_info;
     TensorInfo info;
     // Initialize images
     if(gradient_size < 7)
     {
         gradient_info.init(shape, 1, arm_compute::DataType::S16);
         info.init(shape, 1, arm_compute::DataType::U16);
     }
     else
     {
         gradient_info.init(shape, 1, arm_compute::DataType::S32);
         info.init(shape, 1, arm_compute::DataType::U32);
     }
     _gx.allocator()->init(gradient_info);
     _gy.allocator()->init(gradient_info);
     _mag.allocator()->init(info);
     _nonmax.allocator()->init(info);
     TensorInfo info_u8(shape, 1, arm_compute::DataType::U8);
     _phase.allocator()->init(info_u8);
     _l1_list_counter.allocator()->init(info_u8);
     TensorInfo info_u32(shape, 1, arm_compute::DataType::U32);
     _visited.allocator()->init(info_u32);
     _recorded.allocator()->init(info_u32);
     TensorShape shape_l1_stack = input->info()->tensor_shape();
     shape_l1_stack.set(0, input->info()->dimension(0) * L1_hysteresis_stack_size);
     TensorInfo info_s32(shape_l1_stack, 1, arm_compute::DataType::S32);
     _l1_stack.allocator()->init(info_s32);
     // Manage intermediate buffers
     _memory_group.manage(&_gx);
     _memory_group.manage(&_gy);
     // Configure/Init sobelNxN
     if(gradient_size == 3)
     {
         auto k = std::make_unique<CLSobel3x3>();
         k->configure(compile_context, input, &_gx, &_gy, border_mode, constant_border_value);
         _sobel = std::move(k);
     }
     else if(gradient_size == 5)
     {
         auto k = std::make_unique<CLSobel5x5>();
         k->configure(compile_context, input, &_gx, &_gy, border_mode, constant_border_value);
         _sobel = std::move(k);
     }
     else if(gradient_size == 7)
     {
         auto k = std::make_unique<CLSobel7x7>();
         k->configure(compile_context, input, &_gx, &_gy, border_mode, constant_border_value);
         _sobel = std::move(k);
     }
     else
     {
         ARM_COMPUTE_ERROR_VAR("Gradient size %d not supported", gradient_size);
     }
     // Manage intermediate buffers
     _memory_group.manage(&_mag);
     _memory_group.manage(&_phase);
     // Configure gradient
     _gradient->configure(compile_context, &_gx, &_gy, &_mag, &_phase, norm_type);
     // Allocate intermediate buffers
     _gx.allocator()->allocate();
     _gy.allocator()->allocate();
     // Manage intermediate buffers
     _memory_group.manage(&_nonmax);
     // Configure non-maxima suppression
     _non_max_suppr->configure(compile_context, &_mag, &_phase, &_nonmax, lower_thr, border_mode == BorderMode::UNDEFINED);
     // Allocate intermediate buffers
     _phase.allocator()->allocate();
     // Fill border around magnitude image as non-maxima suppression will access
     // it. If border mode is undefined filling the border is a nop.
     _border_mag_gradient->configure(compile_context, &_mag, _non_max_suppr->border_size(), border_mode, constant_border_value);
     // Allocate intermediate buffers
     _mag.allocator()->allocate();
     // Manage intermediate buffers
     _memory_group.manage(&_visited);
     _memory_group.manage(&_recorded);
     _memory_group.manage(&_l1_stack);
     _memory_group.manage(&_l1_list_counter);
     // Configure edge tracing
     _edge_trace->configure(compile_context, &_nonmax, output, upper_thr, lower_thr, &_visited, &_recorded, &_l1_stack, &_l1_list_counter);
     // Allocate intermediate buffers
     _visited.allocator()->allocate();
     _recorded.allocator()->allocate();
     _l1_stack.allocator()->allocate();
     _l1_list_counter.allocator()->allocate();
     _nonmax.allocator()->allocate();
 }
operator=()
CLCannyEdge& operator= (const CLCannyEdge &) delete
Prevent instances of this class from being copied (As this class contains pointers)
run()
void run () override virtual
Run the kernels contained in the function.
For Neon kernels:
Multi-threading is used for the kernels which are parallelisable.
By default std::thread::hardware_concurrency() threads are used.
Note
CPPScheduler::set_num_threads() can be used to manually set the number of threads
For OpenCL kernels:
All the kernels are enqueued on the queue associated with CLScheduler.
The queue is then flushed.
Note
The function will not block until the kernels are executed. It is the user's responsibility to wait.
Will call prepare() on first run if hasn't been done
Implements IFunction.
Definition at line 190 of file CLCannyEdge.cpp.
References ICLTensor::clear(), CLScheduler::enqueue(), and CLScheduler::get().
 {
     MemoryGroupResourceScope scope_mg(_memory_group);
     // Run sobel
     _sobel->run();
     // Run phase and magnitude calculation
     CLScheduler::get().enqueue(*_gradient, false);
     // Fill border before non-maxima suppression. Nop for border mode undefined.
     CLScheduler::get().enqueue(*_border_mag_gradient, false);
     // Run non max suppresion
     _nonmax.clear(CLScheduler::get().queue());
     CLScheduler::get().enqueue(*_non_max_suppr, false);
     // Clear temporary structures and run edge trace
     _output->clear(CLScheduler::get().queue());
     _visited.clear(CLScheduler::get().queue());
     _recorded.clear(CLScheduler::get().queue());
     _l1_list_counter.clear(CLScheduler::get().queue());
     _l1_stack.clear(CLScheduler::get().queue());
     CLScheduler::get().enqueue(*_edge_trace, true);
 }
The documentation for this class was generated from the following files:
arm_compute/runtime/CL/functions/CLCannyEdge.h
src/runtime/CL/functions/CLCannyEdge.cpp