Compute Library: NEGaussian5x5 Class Reference
NEGaussian5x5 Class Reference
Basic function to execute gaussian filter 5x5.
#include <NEGaussian5x5.h>
Public Member Functions
NEGaussian5x5 (std::shared_ptr< IMemoryManager > memory_manager=nullptr)
Default constructor.
NEGaussian5x5 (const NEGaussian5x5 &)=delete
Prevent instances of this class from being copied (As this class contains pointers)
NEGaussian5x5 & operator= (const NEGaussian5x5 &)=delete
Prevent instances of this class from being copied (As this class contains pointers)
NEGaussian5x5 (NEGaussian5x5 &&)=default
Allow instances of this class to be moved.
NEGaussian5x5 & operator= (NEGaussian5x5 &&)=default
Allow instances of this class to be moved.
~NEGaussian5x5 ()
Default destructor.
void configure (ITensor *input, ITensor *output, BorderMode border_mode, uint8_t constant_border_value=0)
Initialise the function's input, output and border mode.
void run () override
Run the kernels contained in the function.
Public Member Functions inherited from IFunction
virtual ~IFunction ()=default
Destructor.
virtual void prepare ()
Prepare the function for executing.
Detailed Description
Basic function to execute gaussian filter 5x5.
This function calls the following Neon kernels:
NEFillBorderKernel (executed if border_mode == CONSTANT or border_mode == REPLICATE)
NEGaussian5x5HorKernel
NEGaussian5x5VertKernel
Deprecated:
This function is deprecated and is intended to be removed in 21.05 release
Definition at line 52 of file NEGaussian5x5.h.
Constructor & Destructor Documentation
NEGaussian5x5() [1/3]
NEGaussian5x5 (std::shared_ptr< IMemoryManager > memory_manager = nullptr)
Default constructor.
Definition at line 38 of file NEGaussian5x5.cpp.
     : _memory_group(std::move(memory_manager)), _kernel_hor(), _kernel_vert(), _tmp(), _border_handler()
 {
 }
NEGaussian5x5() [2/3]
NEGaussian5x5 (const NEGaussian5x5 &) delete
Prevent instances of this class from being copied (As this class contains pointers)
NEGaussian5x5() [3/3]
NEGaussian5x5 (NEGaussian5x5 &&) default
Allow instances of this class to be moved.
~NEGaussian5x5()
~NEGaussian5x5 () default
Default destructor.
Member Function Documentation
configure()
void configure (ITensor * input, ITensor * output, BorderMode border_mode, uint8_t constant_border_value = 0)
Initialise the function's input, output and border mode.
Parameters
[in,out] input Source tensor. Data type supported: U8. (Written to only for border_mode != UNDEFINED)
[out] output Destination tensor, Data type supported: U8.
[in] border_mode Strategy to use for borders.
[in] constant_border_value (Optional) Constant value to use for borders if border_mode is set to CONSTANT.
Definition at line 43 of file NEGaussian5x5.cpp.
References TensorAllocator::allocate(), Tensor::allocator(), ITensor::info(), TensorAllocator::init(), MemoryGroup::manage(), arm_compute::S16, ITensorInfo::tensor_shape(), and arm_compute::UNDEFINED.
 {
     // Init temporary buffer
     TensorInfo tensor_info(input->info()->tensor_shape(), 1, DataType::S16);
     _tmp.allocator()->init(tensor_info);
     // Manage intermediate buffers
     _memory_group.manage(&_tmp);
     _kernel_hor     = std::make_unique<NEGaussian5x5HorKernel>();
     _kernel_vert    = std::make_unique<NEGaussian5x5VertKernel>();
     _border_handler = std::make_unique<NEFillBorderKernel>();
     // Create and configure kernels for the two passes
     _kernel_hor->configure(input, &_tmp, border_mode == BorderMode::UNDEFINED);
     _kernel_vert->configure(&_tmp, output, border_mode == BorderMode::UNDEFINED);
     _tmp.allocator()->allocate();
     _border_handler->configure(input, _kernel_hor->border_size(), border_mode, PixelValue(constant_border_value));
 }
operator=() [1/2]
NEGaussian5x5& operator= (const NEGaussian5x5 &) delete
Prevent instances of this class from being copied (As this class contains pointers)
operator=() [2/2]
NEGaussian5x5& operator= (NEGaussian5x5 &&) default
Allow instances of this class to be moved.
run()
void run () override virtual
Run the kernels contained in the function.
For Neon kernels:
Multi-threading is used for the kernels which are parallelisable.
By default std::thread::hardware_concurrency() threads are used.
Note
CPPScheduler::set_num_threads() can be used to manually set the number of threads
For OpenCL kernels:
All the kernels are enqueued on the queue associated with CLScheduler.
The queue is then flushed.
Note
The function will not block until the kernels are executed. It is the user's responsibility to wait.
Will call prepare() on first run if hasn't been done
Implements IFunction.
Definition at line 65 of file NEGaussian5x5.cpp.
References Window::DimY, Window::DimZ, Scheduler::get(), and IScheduler::schedule().
 {
     NEScheduler::get().schedule(_border_handler.get(), Window::DimZ);
     MemoryGroupResourceScope scope_mg(_memory_group);
     NEScheduler::get().schedule(_kernel_hor.get(), Window::DimY);
     NEScheduler::get().schedule(_kernel_vert.get(), Window::DimY);
 }
The documentation for this class was generated from the following files:
arm_compute/runtime/NEON/functions/NEGaussian5x5.h
src/runtime/NEON/functions/NEGaussian5x5.cpp