Compute Library: CLScale Class Reference
CLScale Class Reference
Basic function to run CLScaleKernel.
#include <CLScale.h>
Public Member Functions
CLScale ()
Default Constructor.
~CLScale ()=default
Default Destructor.
CLScale (const CLScale &)=delete
Prevent instances of this class from being copied (As this class contains pointers)
CLScale (CLScale &&)=default
Default move constructor.
CLScale & operator= (const CLScale &)=delete
Prevent instances of this class from being copied (As this class contains pointers)
CLScale & operator= (CLScale &&)=default
Default move assignment operator.
void configure (ICLTensor *input, ICLTensor *output, const ScaleKernelInfo &info)
Initialize the function's source, destination, interpolation type and border_mode.
void configure (const CLCompileContext &compile_context, ICLTensor *input, ICLTensor *output, const ScaleKernelInfo &info)
Initialize the function's source, destination, interpolation type and border_mode.
void run () override
Run the kernels contained in the function.
Public Member Functions inherited from IFunction
virtual ~IFunction ()=default
Destructor.
virtual void prepare ()
Prepare the function for executing.
Static Public Member Functions
static Status validate (const ITensorInfo *input, const ITensorInfo *output, const ScaleKernelInfo &info)
Static function to check if given info will lead to a valid configuration of CLScale.
Detailed Description
Basic function to run CLScaleKernel.
Definition at line 44 of file CLScale.h.
Constructor & Destructor Documentation
CLScale() [1/3]
CLScale ()
Default Constructor.
Definition at line 33 of file CLScale.cpp.
     : _border_handler(std::make_unique<CLFillBorderKernel>()), _kernel()
 {
 }
~CLScale()
~CLScale () default
Default Destructor.
CLScale() [2/3]
CLScale (const CLScale &) delete
Prevent instances of this class from being copied (As this class contains pointers)
CLScale() [3/3]
CLScale (CLScale &&) default
Default move constructor.
Member Function Documentation
configure() [1/2]
void configure (ICLTensor * input, ICLTensor * output, const ScaleKernelInfo & info)
Initialize the function's source, destination, interpolation type and border_mode.
Parameters
[in,out] input Source tensor. Data types supported: U8/QASYMM8/QASYMM8_SIGNED/S16/F16/F32. (Written to only for border_mode != UNDEFINED)
[out] output Destination tensor. Data types supported: Same as input All but the lowest two dimensions must be the same size as in the input tensor, i.e. scaling is only performed within the XY-plane.
[in] info ScaleKernelInfo descriptor to be used to configure
Definition at line 38 of file CLScale.cpp.
References CLKernelLibrary::get().
 {
     configure(CLKernelLibrary::get().get_compile_context(), input, output, info);
 }
configure() [2/2]
void configure (const CLCompileContext & compile_context, ICLTensor * input, ICLTensor * output, const ScaleKernelInfo & info)
Initialize the function's source, destination, interpolation type and border_mode.
Parameters
[in] compile_context The compile context to be used.
[in,out] input Source tensor. Data types supported: U8/QASYMM8/QASYMM8_SIGNED/S16/F16/F32. (Written to only for border_mode != UNDEFINED)
[out] output Destination tensor. Data types supported: Same as input All but the lowest two dimensions must be the same size as in the input tensor, i.e. scaling is only performed within the XY-plane.
[in] info ScaleKernelInfo descriptor to be used to configure
Definition at line 43 of file CLScale.cpp.
References ScaleKernelInfo::border_mode, ScaleKernelInfo::constant_border_value, arm_compute::test::validation::data_layout, ScaleKernelInfo::data_layout, ITensorInfo::data_layout(), CLScheduler::get(), ITensor::info(), arm_compute::NCHW, CLScheduler::tune_kernel_static(), and arm_compute::UNKNOWN.
 {
     auto k = std::make_unique<CLScaleKernel>();
     k->set_target(CLScheduler::get().target());
     k->configure(compile_context, input, output, info);
     _kernel = std::move(k);
     // Tune kernels
     CLScheduler::get().tune_kernel_static(*_kernel);
     const DataLayout data_layout = info.data_layout == DataLayout::UNKNOWN ? input->info()->data_layout() : info.data_layout;
     if(data_layout == DataLayout::NCHW && !_kernel->border_size().empty())
     {
         _border_handler->configure(compile_context, input, _kernel->border_size(), info.border_mode, info.constant_border_value);
     }
 }
operator=() [1/2]
CLScale& operator= (const CLScale &) delete
Prevent instances of this class from being copied (As this class contains pointers)
operator=() [2/2]
CLScale& operator= (CLScale &&) default
Default move assignment operator.
run()
void run () override virtual
Run the kernels contained in the function.
For Neon kernels:
Multi-threading is used for the kernels which are parallelisable.
By default std::thread::hardware_concurrency() threads are used.
Note
CPPScheduler::set_num_threads() can be used to manually set the number of threads
For OpenCL kernels:
All the kernels are enqueued on the queue associated with CLScheduler.
The queue is then flushed.
Note
The function will not block until the kernels are executed. It is the user's responsibility to wait.
Will call prepare() on first run if hasn't been done
Implements IFunction.
Definition at line 65 of file CLScale.cpp.
References CLScheduler::enqueue(), and CLScheduler::get().
 {
     if(!_kernel->border_size().empty())
     {
         CLScheduler::get().enqueue(*_border_handler, false);
     }
     CLScheduler::get().enqueue(*_kernel);
 }
validate()
Status validate (const ITensorInfo * input, const ITensorInfo * output, const ScaleKernelInfo & info) static
Static function to check if given info will lead to a valid configuration of CLScale.
Parameters
[in] input Source tensor info. Data types supported: U8/QASYMM8/QASYMM8_SIGNED/S16/F16/F32.
[in] output Output tensor info. Data type supported: Same as input All but the lowest two dimensions must be the same size as in the input tensor, i.e. scaling is only performed within the XY-plane.
[in] info ScaleKernelInfo descriptor to be used to validate
Returns
a status
Definition at line 60 of file CLScale.cpp.
References CLScaleKernel::validate().
Referenced by arm_compute::test::validation::TEST_CASE().
 {
     return CLScaleKernel::validate(input, output, info);
 }
The documentation for this class was generated from the following files:
arm_compute/runtime/CL/functions/CLScale.h
src/runtime/CL/functions/CLScale.cpp