Compute Library: CLGaussian5x5 Class Reference
CLGaussian5x5 Class Reference
Basic function to execute gaussian filter 5x5.
#include <CLGaussian5x5.h>
Public Member Functions
CLGaussian5x5 (std::shared_ptr< IMemoryManager > memory_manager=nullptr)
Default Constructor.
CLGaussian5x5 (const CLGaussian5x5 &)=delete
Prevent instances of this class from being copied.
CLGaussian5x5 (CLGaussian5x5 &&)=default
Default move constructor.
CLGaussian5x5 & operator= (const CLGaussian5x5 &)=delete
Prevent instances of this class from being copied.
CLGaussian5x5 & operator= (CLGaussian5x5 &&)=default
Default move assignment operator.
~CLGaussian5x5 ()
Default destructor.
void configure (ICLTensor *input, ICLTensor *output, BorderMode border_mode, uint8_t constant_border_value=0)
Initialise the function's source, destinations and border mode.
void configure (const CLCompileContext &compile_context, ICLTensor *input, ICLTensor *output, BorderMode border_mode, uint8_t constant_border_value=0)
Initialise the function's source, destinations and border mode.
void run () override
Run the kernels contained in the function.
Public Member Functions inherited from IFunction
virtual ~IFunction ()=default
Destructor.
virtual void prepare ()
Prepare the function for executing.
Detailed Description
Basic function to execute gaussian filter 5x5.
This function calls the following OpenCL kernels:
CLFillBorderKernel (executed if border_mode == CONSTANT or border_mode == REPLICATE)
CLGaussian5x5HorKernel
CLGaussian5x5VertKernel
Deprecated:
This function is deprecated and is intended to be removed in 21.05 release
Definition at line 53 of file CLGaussian5x5.h.
Constructor & Destructor Documentation
CLGaussian5x5() [1/3]
CLGaussian5x5 (std::shared_ptr< IMemoryManager > memory_manager = nullptr)
Default Constructor.
Parameters
[in] memory_manager (Optional) Memory manager.
Definition at line 39 of file CLGaussian5x5.cpp.
References CLGaussian5x5::~CLGaussian5x5().
     : _memory_group(std::move(memory_manager)),
       _kernel_hor(std::make_unique<CLGaussian5x5HorKernel>()),
       _kernel_vert(std::make_unique<CLGaussian5x5VertKernel>()),
       _border_handler(std::make_unique<CLFillBorderKernel>()),
       _tmp()
 {
 }
CLGaussian5x5() [2/3]
CLGaussian5x5 (const CLGaussian5x5 &) delete
Prevent instances of this class from being copied.
CLGaussian5x5() [3/3]
CLGaussian5x5 (CLGaussian5x5 &&) default
Default move constructor.
~CLGaussian5x5()
~CLGaussian5x5 () default
Default destructor.
Referenced by CLGaussian5x5::CLGaussian5x5().
Member Function Documentation
configure() [1/2]
void configure (ICLTensor * input, ICLTensor * output, BorderMode border_mode, uint8_t constant_border_value = 0)
Initialise the function's source, destinations and border mode.
Parameters
[in,out] input Source tensor. Data types supported: U8. (Written to only for border_mode != UNDEFINED)
[out] output Destination tensor, Data types supported: U8.
[in] border_mode Border mode to use for the convolution.
[in] constant_border_value (Optional) Constant value to use for borders if border_mode is set to CONSTANT.
Definition at line 50 of file CLGaussian5x5.cpp.
References CLKernelLibrary::get().
 {
     configure(CLKernelLibrary::get().get_compile_context(), input, output, border_mode, constant_border_value);
 }
configure() [2/2]
void configure (const CLCompileContext & compile_context, ICLTensor * input, ICLTensor * output, BorderMode border_mode, uint8_t constant_border_value = 0)
Initialise the function's source, destinations and border mode.
Parameters
[in] compile_context The compile context to be used.
[in,out] input Source tensor. Data types supported: U8. (Written to only for border_mode != UNDEFINED)
[out] output Destination tensor, Data types supported: U8.
[in] border_mode Border mode to use for the convolution.
[in] constant_border_value (Optional) Constant value to use for borders if border_mode is set to CONSTANT.
Definition at line 55 of file CLGaussian5x5.cpp.
References CLTensorAllocator::allocate(), CLTensor::allocator(), ARM_COMPUTE_ERROR_ON_DATA_TYPE_CHANNEL_NOT_IN, ITensor::info(), ITensorAllocator::init(), MemoryGroup::manage(), ITensorInfo::tensor_shape(), arm_compute::U16, arm_compute::U8, and arm_compute::UNDEFINED.
 {
     ARM_COMPUTE_ERROR_ON_DATA_TYPE_CHANNEL_NOT_IN(input, 1, DataType::U8);
     _tmp.allocator()->init(TensorInfo(input->info()->tensor_shape(), 1, DataType::U16));
     // Manage intermediate buffers
     _memory_group.manage(&_tmp);
     // Configure kernels
     _kernel_hor->configure(compile_context, input, &_tmp, border_mode == BorderMode::UNDEFINED);
     _kernel_vert->configure(compile_context, &_tmp, output, border_mode == BorderMode::UNDEFINED);
     _border_handler->configure(compile_context, input, _kernel_hor->border_size(), border_mode, PixelValue(constant_border_value));
     // Allocate intermediate buffers
     _tmp.allocator()->allocate();
 }
operator=() [1/2]
CLGaussian5x5& operator= (const CLGaussian5x5 &) delete
Prevent instances of this class from being copied.
operator=() [2/2]
CLGaussian5x5& operator= (CLGaussian5x5 &&) default
Default move assignment operator.
run()
void run () override virtual
Run the kernels contained in the function.
For Neon kernels:
Multi-threading is used for the kernels which are parallelisable.
By default std::thread::hardware_concurrency() threads are used.
Note
CPPScheduler::set_num_threads() can be used to manually set the number of threads
For OpenCL kernels:
All the kernels are enqueued on the queue associated with CLScheduler.
The queue is then flushed.
Note
The function will not block until the kernels are executed. It is the user's responsibility to wait.
Will call prepare() on first run if hasn't been done
Implements IFunction.
Definition at line 73 of file CLGaussian5x5.cpp.
References CLScheduler::enqueue(), and CLScheduler::get().
 {
     CLScheduler::get().enqueue(*_border_handler, false);
     MemoryGroupResourceScope scope_mg(_memory_group);
     CLScheduler::get().enqueue(*_kernel_hor, false);
     CLScheduler::get().enqueue(*_kernel_vert);
 }
The documentation for this class was generated from the following files:
arm_compute/runtime/CL/functions/CLGaussian5x5.h
src/runtime/CL/functions/CLGaussian5x5.cpp