Compute Library: NEHOGDescriptor Class Reference
NEHOGDescriptor Class Reference
Basic function to calculate HOG descriptor.
#include <NEHOGDescriptor.h>
Public Member Functions
NEHOGDescriptor (std::shared_ptr< IMemoryManager > memory_manager=nullptr)
Default constructor.
NEHOGDescriptor (const NEHOGDescriptor &)=delete
Prevent instances of this class from being copied (As this class contains pointers)
NEHOGDescriptor & operator= (const NEHOGDescriptor &)=delete
Prevent instances of this class from being copied (As this class contains pointers)
NEHOGDescriptor (NEHOGDescriptor &&)=delete
Prevent instances of this class from being moved (As this class contains non movable objects)
NEHOGDescriptor & operator= (NEHOGDescriptor &&)=delete
Prevent instances of this class from being moved (As this class contains non movable objects)
~NEHOGDescriptor ()
Default destructor.
void configure (ITensor *input, ITensor *output, const IHOG *hog, BorderMode border_mode, uint8_t constant_border_value=0)
Initialise the function's source, destination, HOG data-object and border mode.
void run () override
Run the kernels contained in the function.
Public Member Functions inherited from IFunction
virtual ~IFunction ()=default
Destructor.
virtual void prepare ()
Prepare the function for executing.
Detailed Description
Basic function to calculate HOG descriptor.
This function calls the following Neon kernels:
NEHOGGradient
NEHOGOrientationBinningKernel
NEHOGBlockNormalizationKernel
Deprecated:
This function is deprecated and is intended to be removed in 21.05 release
Definition at line 50 of file NEHOGDescriptor.h.
Constructor & Destructor Documentation
NEHOGDescriptor() [1/3]
NEHOGDescriptor (std::shared_ptr< IMemoryManager > memory_manager = nullptr)
Default constructor.
Definition at line 39 of file NEHOGDescriptor.cpp.
     : _memory_group(std::move(memory_manager)), _gradient(), _orient_bin(), _block_norm(), _mag(), _phase(), _hog_space()
 {
 }
NEHOGDescriptor() [2/3]
NEHOGDescriptor (const NEHOGDescriptor &) delete
Prevent instances of this class from being copied (As this class contains pointers)
NEHOGDescriptor() [3/3]
NEHOGDescriptor (NEHOGDescriptor &&) delete
Prevent instances of this class from being moved (As this class contains non movable objects)
~NEHOGDescriptor()
~NEHOGDescriptor () default
Default destructor.
Member Function Documentation
configure()
void configure (ITensor * input, ITensor * output, const IHOG * hog, BorderMode border_mode, uint8_t constant_border_value = 0)
Initialise the function's source, destination, HOG data-object and border mode.
Parameters
[in,out] input Input tensor. Data type supported: U8 (Written to only for border_mode != UNDEFINED)
[out] output Output tensor which stores the HOG descriptor. DataType supported: F32. The number of channels is equal to the number of histogram bins per block
[in] hog HOG data object which describes the HOG descriptor
[in] border_mode Border mode to use.
[in] constant_border_value (Optional) Constant value to use for borders if border_mode is set to CONSTANT.
Definition at line 44 of file NEHOGDescriptor.cpp.
References TensorAllocator::allocate(), Tensor::allocator(), ARM_COMPUTE_ERROR_ON, ARM_COMPUTE_ERROR_ON_DATA_TYPE_CHANNEL_NOT_IN, HOGInfo::cell_size(), NEHOGGradient::configure(), ITensorInfo::dimension(), Window::DimX, Window::DimY, arm_compute::F32, Size2D::height, IHOG::info(), ITensor::info(), TensorAllocator::init(), MemoryGroup::manage(), HOGInfo::num_bins(), HOGInfo::phase_type(), arm_compute::S16, TensorShape::set(), ITensorInfo::tensor_shape(), arm_compute::U8, and Size2D::width.
 {
     ARM_COMPUTE_ERROR_ON_DATA_TYPE_CHANNEL_NOT_IN(input, 1, DataType::U8);
     ARM_COMPUTE_ERROR_ON(nullptr == output);
     ARM_COMPUTE_ERROR_ON(nullptr == hog);
     const HOGInfo *hog_info = hog->info();
     const size_t   width    = input->info()->dimension(Window::DimX);
     const size_t   height   = input->info()->dimension(Window::DimY);
     const size_t   num_bins = hog_info->num_bins();
     Size2D cell_size = hog_info->cell_size();
     // Calculate number of cells along the x and y directions for the hog_space
     const size_t num_cells_x = width / cell_size.width;
     const size_t num_cells_y = height / cell_size.height;
     // TensorShape of the input image
     const TensorShape &shape_img = input->info()->tensor_shape();
     // TensorShape of the hog space
     TensorShape shape_hog_space = input->info()->tensor_shape();
     shape_hog_space.set(Window::DimX, num_cells_x);
     shape_hog_space.set(Window::DimY, num_cells_y);
     // Allocate memory for magnitude, phase and hog space
     TensorInfo info_mag(shape_img, Format::S16);
     _mag.allocator()->init(info_mag);
     TensorInfo info_phase(shape_img, Format::U8);
     _phase.allocator()->init(info_phase);
     TensorInfo info_space(shape_hog_space, num_bins, DataType::F32);
     _hog_space.allocator()->init(info_space);
     // Manage intermediate buffers
     _memory_group.manage(&_mag);
     _memory_group.manage(&_phase);
     // Initialise gradient kernel
     _gradient.configure(input, &_mag, &_phase, hog_info->phase_type(), border_mode, constant_border_value);
     // Manage intermediate buffers
     _memory_group.manage(&_hog_space);
     // Initialise orientation binning kernel
     _orient_bin = std::make_unique<NEHOGOrientationBinningKernel>();
     _orient_bin->configure(&_mag, &_phase, &_hog_space, hog->info());
     // Initialize HOG norm kernel
     _block_norm = std::make_unique<NEHOGBlockNormalizationKernel>();
     _block_norm->configure(&_hog_space, output, hog->info());
     // Allocate intermediate tensors
     _mag.allocator()->allocate();
     _phase.allocator()->allocate();
     _hog_space.allocator()->allocate();
 }
operator=() [1/2]
NEHOGDescriptor& operator= (const NEHOGDescriptor &) delete
Prevent instances of this class from being copied (As this class contains pointers)
operator=() [2/2]
NEHOGDescriptor& operator= (NEHOGDescriptor &&) delete
Prevent instances of this class from being moved (As this class contains non movable objects)
run()
void run () override virtual
Run the kernels contained in the function.
For Neon kernels:
Multi-threading is used for the kernels which are parallelisable.
By default std::thread::hardware_concurrency() threads are used.
Note
CPPScheduler::set_num_threads() can be used to manually set the number of threads
For OpenCL kernels:
All the kernels are enqueued on the queue associated with CLScheduler.
The queue is then flushed.
Note
The function will not block until the kernels are executed. It is the user's responsibility to wait.
Will call prepare() on first run if hasn't been done
Implements IFunction.
Definition at line 103 of file NEHOGDescriptor.cpp.
References Window::DimY, Scheduler::get(), NEHOGGradient::run(), and IScheduler::schedule().
 {
     MemoryGroupResourceScope scope_mg(_memory_group);
     // Run gradient
     _gradient.run();
     // Run orientation binning kernel
     NEScheduler::get().schedule(_orient_bin.get(), Window::DimY);
     // Run block normalization kernel
     NEScheduler::get().schedule(_block_norm.get(), Window::DimY);
 }
The documentation for this class was generated from the following files:
arm_compute/runtime/NEON/functions/NEHOGDescriptor.h
src/runtime/NEON/functions/NEHOGDescriptor.cpp