Compute Library: CpuElementwiseUnaryKernel Class Reference
CpuElementwiseUnaryKernel Class Reference
Interface for an element-wise unary operation kernel.
#include <CpuElementwiseUnaryKernel.h>
Public Types
using ElementwiseUnaryUkernelPtr = std::add_pointer< void(const ITensor *, ITensor *, const Window &, ElementWiseUnary)>::type
Common signature for all the specialised elementwise unary micro-kernels.
Public Member Functions
const char * name () const override
Name of the kernel.
CpuElementwiseUnaryKernel ()
Default constructor.
~CpuElementwiseUnaryKernel ()=default
Default destructor.
ARM_COMPUTE_DISALLOW_COPY_ALLOW_MOVE (CpuElementwiseUnaryKernel)
void configure (ElementWiseUnary op, const ITensorInfo &input, ITensorInfo &output)
Function to configure the CpuElementwiseUnaryKernel.
void run_op (ITensorPack &tensors, const Window &window, const ThreadInfo &info) override
Execute the kernel on the passed window.
Public Member Functions inherited from ICPPKernel
virtual ~ICPPKernel ()=default
Default destructor.
virtual void run (const Window &window, const ThreadInfo &info)
Execute the kernel on the passed window.
virtual void run_nd (const Window &window, const ThreadInfo &info, const Window &thread_locator)
legacy compatibility layer for implemantions which do not support thread_locator In these cases we simply narrow the interface down the legacy version
Public Member Functions inherited from IKernel
IKernel ()
Constructor.
virtual ~IKernel ()=default
Destructor.
virtual bool is_parallelisable () const
Indicates whether or not the kernel is parallelisable.
virtual BorderSize border_size () const
The size of the border for that kernel.
const Window & window () const
The maximum window the kernel can be executed on.
Static Public Member Functions
static Status validate (ElementWiseUnary op, const ITensorInfo &input, const ITensorInfo &output)
Static function to check if given info will lead to a valid configuration of CpuElementwiseUnaryKernel.
Detailed Description
Interface for an element-wise unary operation kernel.
Element-wise operation is computed by:
\[ output(x) = OP(input(x))\]
Definition at line 44 of file CpuElementwiseUnaryKernel.h.
Member Typedef Documentation
ElementwiseUnaryUkernelPtr
using ElementwiseUnaryUkernelPtr = std::add_pointer<void(const ITensor *, ITensor *, const Window &, ElementWiseUnary)>::type
Common signature for all the specialised elementwise unary micro-kernels.
Parameters
[in] window Region on which to execute the kernel.
Definition at line 82 of file CpuElementwiseUnaryKernel.h.
Constructor & Destructor Documentation
CpuElementwiseUnaryKernel()
CpuElementwiseUnaryKernel ()
Default constructor.
Definition at line 106 of file CpuElementwiseUnaryKernel.cpp.
Referenced by CpuElementwiseUnaryKernel::name().
     : _op()
 {
 }
~CpuElementwiseUnaryKernel()
~CpuElementwiseUnaryKernel () default
Default destructor.
Referenced by CpuElementwiseUnaryKernel::name().
Member Function Documentation
ARM_COMPUTE_DISALLOW_COPY_ALLOW_MOVE()
ARM_COMPUTE_DISALLOW_COPY_ALLOW_MOVE (CpuElementwiseUnaryKernel)
Referenced by CpuElementwiseUnaryKernel::name().
configure()
void configure (ElementWiseUnary op, const ITensorInfo & input, ITensorInfo & output)
Function to configure the CpuElementwiseUnaryKernel.
Parameters
[in] op Arithmetic operation to be executed.
[in] input First tensor input. Data types supported: F16/F32, F16/F32/S32 for NEG/ABS operations.
[out] output Output tensor. Data types supported: Same as input.
Definition at line 111 of file CpuElementwiseUnaryKernel.cpp.
References ARM_COMPUTE_ERROR_THROW_ON, arm_compute::auto_init_if_empty(), ITensorInfo::broadcast_shape_and_valid_region(), arm_compute::calculate_max_window(), ITensorInfo::data_type(), arm_compute::test::validation::valid_region, and CpuElementwiseUnaryKernel::validate().
Referenced by CpuElementwiseUnaryKernel::name().
 {
     ARM_COMPUTE_ERROR_THROW_ON(validate(op, input, output));
     // Configure kernel window
     const std::pair<TensorShape, ValidRegion> broadcast_pair = ITensorInfo::broadcast_shape_and_valid_region(input);
     const TensorShape &out_shape    = broadcast_pair.first;
     const ValidRegion &valid_region = broadcast_pair.second;
     // Auto initialize output if not initialized
     auto_init_if_empty(output, out_shape, 1, input.data_type());
     Window win = calculate_max_window(valid_region);
     _op = op;
     ICpuKernel::configure(win);
 }
name()
const char* name () const inline override virtual
Name of the kernel.
Returns
Kernel name
Implements ICPPKernel.
Definition at line 47 of file CpuElementwiseUnaryKernel.h.
References CpuElementwiseUnaryKernel::ARM_COMPUTE_DISALLOW_COPY_ALLOW_MOVE(), CpuElementwiseUnaryKernel::configure(), CpuElementwiseUnaryKernel::CpuElementwiseUnaryKernel(), arm_compute::test::validation::info, arm_compute::test::validation::input, CpuElementwiseUnaryKernel::run_op(), CpuElementwiseUnaryKernel::validate(), IKernel::window(), and CpuElementwiseUnaryKernel::~CpuElementwiseUnaryKernel().
     {
         return "CpuElementwiseUnaryKernel";
     }
run_op()
void run_op (ITensorPack & tensors, const Window & window, const ThreadInfo & info) override virtual
Execute the kernel on the passed window.
Warning
If is_parallelisable() returns false then the passed window must be equal to window()
Note
The window has to be a region within the window returned by the window() method
The width of the window has to be a multiple of num_elems_processed_per_iteration().
Parameters
[in] tensors A vector containing the tensors to operate on.
[in] window Region on which to execute the kernel. (Must be a region of the window returned by window())
[in] info Info about executing thread and CPU.
Reimplemented from ICPPKernel.
Definition at line 162 of file CpuElementwiseUnaryKernel.cpp.
References arm_compute::ACL_DST, arm_compute::ACL_SRC, ARM_COMPUTE_ERROR_ON, ARM_COMPUTE_ERROR_ON_INVALID_SUBWINDOW, ARM_COMPUTE_ERROR_ON_UNCONFIGURED_KERNEL, ARM_COMPUTE_UNUSED, arm_compute::test::validation::dst, func, ITensorPack::get_const_tensor(), ITensorPack::get_tensor(), arm_compute::test::validation::src, ukernel, and IKernel::window().
Referenced by CpuElementwiseUnaryKernel::name().
 {
     ARM_COMPUTE_UNUSED(info);
     ARM_COMPUTE_ERROR_ON_UNCONFIGURED_KERNEL(this);
     ARM_COMPUTE_ERROR_ON_INVALID_SUBWINDOW(ICpuKernel::window(), window);
     auto src  = tensors.get_const_tensor(TensorType::ACL_SRC);
     auto dst  = tensors.get_tensor(TensorType::ACL_DST);
     auto func = get_implementation(src->info()->data_type())->ukernel;
     ARM_COMPUTE_ERROR_ON(func == nullptr);
     func(src, dst, window, _op);
 }
validate()
Status validate (ElementWiseUnary op, const ITensorInfo & input, const ITensorInfo & output) static
Static function to check if given info will lead to a valid configuration of CpuElementwiseUnaryKernel.
Parameters
[in] op Arithmetic operation to be executed.
[in] input First tensor input info. Data types supported: F16/F32, F16/F32/S32 for NEG/ABS operations.
[in] output Output tensor info. Data types supported: Same as input.
Returns
a Status
Definition at line 130 of file CpuElementwiseUnaryKernel.cpp.
References arm_compute::ABS, ARM_COMPUTE_ERROR, ARM_COMPUTE_RETURN_ERROR_ON, ARM_COMPUTE_RETURN_ERROR_ON_CPU_F16_UNSUPPORTED, ARM_COMPUTE_RETURN_ERROR_ON_DATA_TYPE_CHANNEL_NOT_IN, ARM_COMPUTE_RETURN_ERROR_ON_MISMATCHING_DATA_TYPES, ITensorInfo::data_type(), arm_compute::EXP, arm_compute::F16, arm_compute::F32, arm_compute::LOG, arm_compute::NEG, arm_compute::ROUND, arm_compute::RSQRT, arm_compute::S32, arm_compute::SIN, and ITensorInfo::total_size().
Referenced by CpuElementwiseUnaryKernel::configure(), CpuElementwiseUnaryKernel::name(), and CpuElementwiseUnary::validate().
 {
     ARM_COMPUTE_RETURN_ERROR_ON_CPU_F16_UNSUPPORTED(&input);
     const auto *uk = get_implementation(input.data_type());
     ARM_COMPUTE_RETURN_ERROR_ON(uk == nullptr || uk->ukernel == nullptr);
     switch(op)
     {
         case ElementWiseUnary::EXP:
         case ElementWiseUnary::RSQRT:
         case ElementWiseUnary::LOG:
         case ElementWiseUnary::ROUND:
         case ElementWiseUnary::SIN:
             ARM_COMPUTE_RETURN_ERROR_ON_DATA_TYPE_CHANNEL_NOT_IN(&input, 1, DataType::F16, DataType::F32);
             break;
         case ElementWiseUnary::NEG:
         case ElementWiseUnary::ABS:
             ARM_COMPUTE_RETURN_ERROR_ON_DATA_TYPE_CHANNEL_NOT_IN(&input, 1, DataType::F16, DataType::F32, DataType::S32);
             break;
         default:
             ARM_COMPUTE_ERROR("ElementWiseUnary operation not supported");
     }
     // Validate in case of configured output
     if(output.total_size() > 0)
     {
         ARM_COMPUTE_RETURN_ERROR_ON_MISMATCHING_DATA_TYPES(&input, &output);
     }
     return Status{};
 }
The documentation for this class was generated from the following files:
src/core/cpu/kernels/CpuElementwiseUnaryKernel.h
src/core/cpu/kernels/CpuElementwiseUnaryKernel.cpp