Compute Library: arm_compute::test::detail Namespace Reference
arm_compute::test::detail Namespace Reference
Functions
void validate_npy_header (std::ifstream &stream, const std::string &expect_typestr, const TensorShape &expect_shape)
template<typename T >
std::vector< std::pair< T, T > > convert_range_pair (const std::vector< AssetsLibrary::RangePair > &excluded_range_pairs)
Function Documentation
convert_range_pair()
std::vector<std::pair<T, T> > arm_compute::test::detail::convert_range_pair (const std::vector< AssetsLibrary::RangePair > & excluded_range_pairs) inline
Definition at line 481 of file AssetsLibrary.h.
References validate_npy_header().
 {
     std::vector<std::pair<T, T>> converted;
     std::transform(excluded_range_pairs.begin(),
                    excluded_range_pairs.end(),
                    std::back_inserter(converted),
                    [](const AssetsLibrary::RangePair & p)
     {
         return std::pair<T, T>(static_cast<T>(p.first), static_cast<T>(p.second));
     });
     return converted;
 }
validate_npy_header()
void validate_npy_header (std::ifstream & stream, const std::string & expect_typestr, const TensorShape & expect_shape) inline
Definition at line 522 of file AssetsLibrary.cpp.
References ARM_COMPUTE_ERROR_ON_MSG, ARM_COMPUTE_UNUSED, arm_compute::mlgo::parser::header(), Dimensions< T >::num_dimensions(), and arm_compute::test::validation::shape.
Referenced by convert_range_pair(), and AssetsLibrary::fill_layer_data().
 {
     ARM_COMPUTE_UNUSED(expect_typestr);
     ARM_COMPUTE_UNUSED(expect_shape);
     std::string header = npy::read_header(stream);
     // Parse header
     std::vector<unsigned long> shape;
     bool                       fortran_order = false;
     std::string                typestr;
     npy::parse_header(header, typestr, fortran_order, shape);
     // Check if the typestring matches the given one
     ARM_COMPUTE_ERROR_ON_MSG(typestr != expect_typestr, "Typestrings mismatch");
     // Validate tensor shape
     ARM_COMPUTE_ERROR_ON_MSG(shape.size() != expect_shape.num_dimensions(), "Tensor ranks mismatch");
     if(fortran_order)
     {
         for(size_t i = 0; i < shape.size(); ++i)
         {
             ARM_COMPUTE_ERROR_ON_MSG(expect_shape[i] != shape[i], "Tensor dimensions mismatch");
         }
     }
     else
     {
         for(size_t i = 0; i < shape.size(); ++i)
         {
             ARM_COMPUTE_ERROR_ON_MSG(expect_shape[i] != shape[shape.size() - i - 1], "Tensor dimensions mismatch");
         }
     }
 }