Compute Library: arm_compute::scale_helpers Namespace Reference
arm_compute::scale_helpers Namespace Reference
Functions
template<typename T >
T delta_bilinear_c1 (const T *pixel_ptr, size_t stride, float dx, float dy)
Computes bilinear interpolation using the pointer to the top-left pixel and the pixel's distance between the real coordinates and the smallest following integer coordinates.
uint8_t delta_bilinear_c1_quantized (const uint8_t *pixel_ptr, size_t stride, float dx, float dy, UniformQuantizationInfo iq_info, UniformQuantizationInfo oq_info)
Computes bilinear interpolation for quantized input and output, using the pointer to the top-left pixel and the pixel's distance between the real coordinates and the smallest following integer coordinates.
int8_t delta_bilinear_c1_quantized (const int8_t *pixel_ptr, size_t stride, float dx, float dy, UniformQuantizationInfo iq_info, UniformQuantizationInfo oq_info)
Computes bilinear interpolation for quantized input and output, using the pointer to the top-left pixel and the pixel's distance between the real coordinates and the smallest following integer coordinates.
template<typename T >
T delta_linear_c1_y (const T *pixel_ptr, size_t stride, float dy)
Computes linear interpolation using the pointer to the top pixel and the pixel's distance between the real coordinates and the smallest following integer coordinates.
template<typename T >
T delta_linear_c1_x (const T *pixel_ptr, float dx)
Computes linear interpolation using the pointer to the left pixel and the pixel's distance between the real coordinates and the smallest following integer coordinates.
template<typename T >
T pixel_bilinear_c1 (const T *first_pixel_ptr, size_t stride, float x, float y)
Return the pixel at (x,y) using bilinear interpolation.
template<typename T >
uint8_t pixel_bilinear_c1_clamp (const T *first_pixel_ptr, size_t stride, size_t width, size_t height, float x, float y)
Return the pixel at (x,y) using bilinear interpolation by clamping when out of borders.
uint8_t pixel_area_c1u8_clamp (const uint8_t *first_pixel_ptr, size_t stride, size_t width, size_t height, float wr, float hr, int x, int y)
Return the pixel at (x,y) using area interpolation by clamping when out of borders.
float delta_bilinear (float a00, float a01, float a10, float a11, float dx_val, float dy_val)
Computes bilinear interpolation using the top-left, top-right, bottom-left, bottom-right pixels and the pixel's distance between the real coordinates and the smallest following integer coordinates.
Function Documentation
delta_bilinear()
float arm_compute::scale_helpers::delta_bilinear (float a00, float a01, float a10, float a11, float dx_val, float dy_val) inline
Computes bilinear interpolation using the top-left, top-right, bottom-left, bottom-right pixels and the pixel's distance between the real coordinates and the smallest following integer coordinates.
Parameters
[in] a00 The top-left pixel value.
[in] a01 The top-right pixel value.
[in] a10 The bottom-left pixel value.
[in] a11 The bottom-right pixel value.
[in] dx_val Pixel's distance between the X real coordinate and the smallest X following integer
[in] dy_val Pixel's distance between the Y real coordinate and the smallest Y following integer
Note
dx and dy must be in the range [0, 1.0]
Returns
The bilinear interpolated pixel value
Definition at line 343 of file ScaleHelpers.h.
 {
     const float dx1_val = 1.0f - dx_val;
     const float dy1_val = 1.0f - dy_val;
     const float w1 = dx1_val * dy1_val;
     const float w2 = dx_val * dy1_val;
     const float w3 = dx1_val * dy_val;
     const float w4 = dx_val * dy_val;
     return a00 * w1 + a01 * w2 + a10 * w3 + a11 * w4;
 }
delta_bilinear_c1()
T arm_compute::scale_helpers::delta_bilinear_c1 (const T * pixel_ptr, size_t stride, float dx, float dy) inline
Computes bilinear interpolation using the pointer to the top-left pixel and the pixel's distance between the real coordinates and the smallest following integer coordinates.
Input must be in single channel format.
Parameters
[in] pixel_ptr Pointer to the top-left pixel value of a single channel input.
[in] stride Stride to access the bottom-left and bottom-right pixel values
[in] dx Pixel's distance between the X real coordinate and the smallest X following integer
[in] dy Pixel's distance between the Y real coordinate and the smallest Y following integer
Note
dx and dy must be in the range [0, 1.0]
Returns
The bilinear interpolated pixel value
Definition at line 52 of file ScaleHelpers.h.
References ARM_COMPUTE_ERROR_ON.
Referenced by pixel_bilinear_c1(), and pixel_bilinear_c1_clamp().
 {
     ARM_COMPUTE_ERROR_ON(pixel_ptr == nullptr);
     const float dx1 = 1.0f - dx;
     const float dy1 = 1.0f - dy;
     const T a00 = *pixel_ptr;
     const T a01 = *(pixel_ptr + 1);
     const T a10 = *(pixel_ptr + stride);
     const T a11 = *(pixel_ptr + stride + 1);
     const float w1 = dx1 * dy1;
     const float w2 = dx * dy1;
     const float w3 = dx1 * dy;
     const float w4 = dx * dy;
     return static_cast<T>(a00 * w1 + a01 * w2 + a10 * w3 + a11 * w4);
 }
delta_bilinear_c1_quantized() [1/2]
uint8_t arm_compute::scale_helpers::delta_bilinear_c1_quantized (const uint8_t * pixel_ptr, size_t stride, float dx, float dy, UniformQuantizationInfo iq_info, UniformQuantizationInfo oq_info) inline
Computes bilinear interpolation for quantized input and output, using the pointer to the top-left pixel and the pixel's distance between the real coordinates and the smallest following integer coordinates.
Input must be QASYMM8 and in single channel format.
Parameters
[in] pixel_ptr Pointer to the top-left pixel value of a single channel input.
[in] stride Stride to access the bottom-left and bottom-right pixel values
[in] dx Pixel's distance between the X real coordinate and the smallest X following integer
[in] dy Pixel's distance between the Y real coordinate and the smallest Y following integer
[in] iq_info Input QuantizationInfo
[in] oq_info Output QuantizationInfo
Note
dx and dy must be in the range [0, 1.0]
Returns
The bilinear interpolated pixel value
Definition at line 86 of file ScaleHelpers.h.
References ARM_COMPUTE_ERROR_ON, arm_compute::dequantize_qasymm8(), and arm_compute::quantize_qasymm8().
 {
     ARM_COMPUTE_ERROR_ON(pixel_ptr == nullptr);
     const float dx1 = 1.0f - dx;
     const float dy1 = 1.0f - dy;
     const float a00 = dequantize_qasymm8(*pixel_ptr, iq_info);
     const float a01 = dequantize_qasymm8(*(pixel_ptr + 1), iq_info);
     const float a10 = dequantize_qasymm8(*(pixel_ptr + stride), iq_info);
     const float a11 = dequantize_qasymm8(*(pixel_ptr + stride + 1), iq_info);
     const float w1  = dx1 * dy1;
     const float w2  = dx * dy1;
     const float w3  = dx1 * dy;
     const float w4  = dx * dy;
     float       res = a00 * w1 + a01 * w2 + a10 * w3 + a11 * w4;
     return static_cast<uint8_t>(quantize_qasymm8(res, oq_info));
 }
delta_bilinear_c1_quantized() [2/2]
int8_t arm_compute::scale_helpers::delta_bilinear_c1_quantized (const int8_t * pixel_ptr, size_t stride, float dx, float dy, UniformQuantizationInfo iq_info, UniformQuantizationInfo oq_info) inline
Computes bilinear interpolation for quantized input and output, using the pointer to the top-left pixel and the pixel's distance between the real coordinates and the smallest following integer coordinates.
Input must be QASYMM8_SIGNED and in single channel format.
Parameters
[in] pixel_ptr Pointer to the top-left pixel value of a single channel input.
[in] stride Stride to access the bottom-left and bottom-right pixel values
[in] dx Pixel's distance between the X real coordinate and the smallest X following integer
[in] dy Pixel's distance between the Y real coordinate and the smallest Y following integer
[in] iq_info Input QuantizationInfo
[in] oq_info Output QuantizationInfo
Note
dx and dy must be in the range [0, 1.0]
Returns
The bilinear interpolated pixel value
Definition at line 121 of file ScaleHelpers.h.
References ARM_COMPUTE_ERROR_ON, arm_compute::dequantize_qasymm8_signed(), and arm_compute::quantize_qasymm8_signed().
 {
     ARM_COMPUTE_ERROR_ON(pixel_ptr == nullptr);
     const float dx1 = 1.0f - dx;
     const float dy1 = 1.0f - dy;
     const float a00 = dequantize_qasymm8_signed(*pixel_ptr, iq_info);
     const float a01 = dequantize_qasymm8_signed(*(pixel_ptr + 1), iq_info);
     const float a10 = dequantize_qasymm8_signed(*(pixel_ptr + stride), iq_info);
     const float a11 = dequantize_qasymm8_signed(*(pixel_ptr + stride + 1), iq_info);
     const float w1  = dx1 * dy1;
     const float w2  = dx * dy1;
     const float w3  = dx1 * dy;
     const float w4  = dx * dy;
     float       res = a00 * w1 + a01 * w2 + a10 * w3 + a11 * w4;
     return static_cast<int8_t>(quantize_qasymm8_signed(res, oq_info));
 }
delta_linear_c1_x()
T arm_compute::scale_helpers::delta_linear_c1_x (const T * pixel_ptr, float dx) inline
Computes linear interpolation using the pointer to the left pixel and the pixel's distance between the real coordinates and the smallest following integer coordinates.
Input must be in single channel format.
Parameters
[in] pixel_ptr Pointer to the left pixel value of a single channel input.
[in] dx Pixel's distance between the X real coordinate and the smallest X following integer
Note
dx must be in the range [0, 1.0]
Returns
The linear interpolated pixel value
Definition at line 180 of file ScaleHelpers.h.
References ARM_COMPUTE_ERROR_ON.
Referenced by pixel_bilinear_c1_clamp().
 {
     ARM_COMPUTE_ERROR_ON(pixel_ptr == nullptr);
     const T a00 = *pixel_ptr;
     const T a01 = *(pixel_ptr + 1);
     const float dx1 = 1.0f - dx;
     const float w1 = dx1;
     const float w2 = dx;
     return static_cast<T>(a00 * w1 + a01 * w2);
 }
delta_linear_c1_y()
T arm_compute::scale_helpers::delta_linear_c1_y (const T * pixel_ptr, size_t stride, float dy) inline
Computes linear interpolation using the pointer to the top pixel and the pixel's distance between the real coordinates and the smallest following integer coordinates.
Input must be in single channel format.
Parameters
[in] pixel_ptr Pointer to the top pixel value of a single channel input.
[in] stride Stride to access the bottom pixel value
[in] dy Pixel's distance between the Y real coordinate and the smallest Y following integer
Note
dy must be in the range [0, 1.0]
Returns
The linear interpolated pixel value
Definition at line 154 of file ScaleHelpers.h.
References ARM_COMPUTE_ERROR_ON.
Referenced by pixel_bilinear_c1_clamp().
 {
     ARM_COMPUTE_ERROR_ON(pixel_ptr == nullptr);
     const float dy1 = 1.0f - dy;
     const T a00 = *pixel_ptr;
     const T a10 = *(pixel_ptr + stride);
     const float w1 = dy1;
     const float w3 = dy;
     return static_cast<T>(a00 * w1 + a10 * w3);
 }
pixel_area_c1u8_clamp()
uint8_t arm_compute::scale_helpers::pixel_area_c1u8_clamp (const uint8_t * first_pixel_ptr, size_t stride, size_t width, size_t height, float wr, float hr, int x, int y) inline
Return the pixel at (x,y) using area interpolation by clamping when out of borders.
The image must be single channel U8
Note
The interpolation area depends on the width and height ration of the input and output images
Currently average of the contributing pixels is calculated
Parameters
[in] first_pixel_ptr Pointer to the first pixel of a single channel U8 image.
[in] stride Stride in bytes of the image
[in] width Width of the image
[in] height Height of the image
[in] wr Width ratio among the input image width and output image width.
[in] hr Height ratio among the input image height and output image height.
[in] x X position of the wanted pixel
[in] y Y position of the wanted pixel
Returns
The pixel at (x, y) using area interpolation.
Definition at line 283 of file ScaleHelpers.h.
References accumulate(), ARM_COMPUTE_ERROR_ON, and sum().
 {
     ARM_COMPUTE_ERROR_ON(first_pixel_ptr == nullptr);
     // Calculate sampling position
     float in_x = (x + 0.5f) * wr - 0.5f;
     float in_y = (y + 0.5f) * hr - 0.5f;
     // Get bounding box offsets
     int x_from = std::floor(x * wr - 0.5f - in_x);
     int y_from = std::floor(y * hr - 0.5f - in_y);
     int x_to   = std::ceil((x + 1) * wr - 0.5f - in_x);
     int y_to   = std::ceil((y + 1) * hr - 0.5f - in_y);
     // Clamp position to borders
     in_x = std::max(-1.f, std::min(in_x, static_cast<float>(width)));
     in_y = std::max(-1.f, std::min(in_y, static_cast<float>(height)));
     // Clamp bounding box offsets to borders
     x_from = ((in_x + x_from) < -1) ? -1 : x_from;
     y_from = ((in_y + y_from) < -1) ? -1 : y_from;
     x_to   = ((in_x + x_to) > width) ? (width - in_x) : x_to;
     y_to   = ((in_y + y_to) > height) ? (height - in_y) : y_to;
     // Get pixel index
     const int xi = std::floor(in_x);
     const int yi = std::floor(in_y);
     // Bounding box elements in each dimension
     const int x_elements = (x_to - x_from + 1);
     const int y_elements = (y_to - y_from + 1);
     ARM_COMPUTE_ERROR_ON(x_elements == 0 || y_elements == 0);
     // Sum pixels in area
     int sum = 0;
     for(int j = yi + y_from, je = yi + y_to; j <= je; ++j)
     {
         const uint8_t *ptr = first_pixel_ptr + j * stride + xi + x_from;
         sum                = std::accumulate(ptr, ptr + x_elements, sum);
     }
     // Return average
     return sum / (x_elements * y_elements);
 }
pixel_bilinear_c1()
T arm_compute::scale_helpers::pixel_bilinear_c1 (const T * first_pixel_ptr, size_t stride, float x, float y) inline
Return the pixel at (x,y) using bilinear interpolation.
Warning
Only works if the iterator was created with an IImage
Parameters
[in] first_pixel_ptr Pointer to the first pixel of a single channel input.
[in] stride Stride in bytes of the image;
[in] x X position of the wanted pixel
[in] y Y position of the wanted pixel
Returns
The pixel at (x, y) using bilinear interpolation.
Definition at line 207 of file ScaleHelpers.h.
References ARM_COMPUTE_ERROR_ON, and delta_bilinear_c1().
Referenced by INEWarpKernel::configure().
 {
     ARM_COMPUTE_ERROR_ON(first_pixel_ptr == nullptr);
     const int32_t xi = std::floor(x);
     const int32_t yi = std::floor(y);
     const float dx = x - xi;
     const float dy = y - yi;
     return delta_bilinear_c1(first_pixel_ptr + xi + yi * stride, stride, dx, dy);
 }
pixel_bilinear_c1_clamp()
uint8_t arm_compute::scale_helpers::pixel_bilinear_c1_clamp (const T * first_pixel_ptr, size_t stride, size_t width, size_t height, float x, float y) inline
Return the pixel at (x,y) using bilinear interpolation by clamping when out of borders.
The image must be single channel input
Warning
Only works if the iterator was created with an IImage
Parameters
[in] first_pixel_ptr Pointer to the first pixel of a single channel image.
[in] stride Stride in bytes of the image
[in] width Width of the image
[in] height Height of the image
[in] x X position of the wanted pixel
[in] y Y position of the wanted pixel
Returns
The pixel at (x, y) using bilinear interpolation.
Definition at line 235 of file ScaleHelpers.h.
References ARM_COMPUTE_ERROR_ON, delta_bilinear_c1(), delta_linear_c1_x(), and delta_linear_c1_y().
 {
     ARM_COMPUTE_ERROR_ON(first_pixel_ptr == nullptr);
     x = std::max(-1.f, std::min(x, static_cast<float>(width)));
     y = std::max(-1.f, std::min(y, static_cast<float>(height)));
     const float xi = std::floor(x);
     const float yi = std::floor(y);
     const float dx = x - xi;
     const float dy = y - yi;
     if(dx == 0.0f)
     {
         if(dy == 0.0f)
         {
             return static_cast<T>(first_pixel_ptr[static_cast<int32_t>(xi) + static_cast<int32_t>(yi) * stride]);
         }
         return delta_linear_c1_y(first_pixel_ptr + static_cast<int32_t>(xi) + static_cast<int32_t>(yi) * stride,
                                  stride, dy);
     }
     if(dy == 0.0f)
     {
         return delta_linear_c1_x(first_pixel_ptr + static_cast<int32_t>(xi) + static_cast<int32_t>(yi) * stride,
                                  dx);
     }
     return delta_bilinear_c1(first_pixel_ptr + static_cast<int32_t>(xi) + static_cast<int32_t>(yi) * stride, stride,
                              dx, dy);
 }