Compute Library: PoolingImplementation< TInput, TOutput, OutputStage > Struct Template Reference
PoolingImplementation< TInput, TOutput, OutputStage > Struct Template Reference
#include <pooling_implementation.hpp>
Public Member Functions
bool get_is_supported (const PoolingArgs &args, const OutputStage &os) const
uint64_t get_cycle_estimate (const PoolingArgs &args, const OutputStage &os) const
PoolingCommon< TInput, TOutput, OutputStage > * get_instance (const PoolingArgs &args, const OutputStage &os) const
Data Fields
const PoolingMethod method
const char * name
std::function< bool(const PoolingArgs &, const OutputStage &)> is_supported
std::function< uint64_t(const PoolingArgs &, const OutputStage &)> cycle_estimate
std::function< PoolingCommon< TInput, TOutput, OutputStage > *(const PoolingArgs &, const OutputStage &)> initialise
Detailed Description
template<typename TInput, typename TOutput, class OutputStage = Nothing>
struct arm_conv::pooling::PoolingImplementation< TInput, TOutput, OutputStage >
Definition at line 36 of file pooling_implementation.hpp.
Member Function Documentation
get_cycle_estimate()
uint64_t get_cycle_estimate (const PoolingArgs & args, const OutputStage & os) const inline
Definition at line 49 of file pooling_implementation.hpp.
References PoolingImplementation< TInput, TOutput, OutputStage >::cycle_estimate.
   {
     return (cycle_estimate == nullptr) ? 0 : cycle_estimate(args, os);
   }
get_instance()
PoolingCommon<TInput, TOutput, OutputStage>* get_instance (const PoolingArgs & args, const OutputStage & os) const inline
Definition at line 54 of file pooling_implementation.hpp.
References PoolingImplementation< TInput, TOutput, OutputStage >::initialise, and arm_conv::pooling::pooling_implementation_list().
Referenced by arm_conv::pooling::pooling().
   {
     return initialise(args, os);
   }
get_is_supported()
bool get_is_supported (const PoolingArgs & args, const OutputStage & os) const inline
Definition at line 44 of file pooling_implementation.hpp.
References PoolingImplementation< TInput, TOutput, OutputStage >::is_supported.
   {
     return (is_supported == nullptr) ? true : is_supported(args, os);
   }
Field Documentation
cycle_estimate
std::function<uint64_t(const PoolingArgs &, const OutputStage &)> cycle_estimate
Definition at line 41 of file pooling_implementation.hpp.
Referenced by PoolingImplementation< TInput, TOutput, OutputStage >::get_cycle_estimate().
initialise
std::function<PoolingCommon<TInput, TOutput, OutputStage> *(const PoolingArgs &, const OutputStage &)> initialise
Definition at line 42 of file pooling_implementation.hpp.
Referenced by PoolingImplementation< TInput, TOutput, OutputStage >::get_instance().
is_supported
std::function<bool(const PoolingArgs &, const OutputStage &)> is_supported
Definition at line 40 of file pooling_implementation.hpp.
Referenced by PoolingImplementation< TInput, TOutput, OutputStage >::get_is_supported().
method
const PoolingMethod method
Definition at line 38 of file pooling_implementation.hpp.
name
const char* name
Definition at line 39 of file pooling_implementation.hpp.
The documentation for this struct was generated from the following file:
src/core/NEON/kernels/arm_conv/pooling/pooling_implementation.hpp