Compute Library: arm_compute::support::cpp14 Namespace Reference
arm_compute::support::cpp14 Namespace Reference
Data Structures
struct _Unique_if
make_unique is missing in CPP11.
struct _Unique_if< T[]>
Template for array.
struct _Unique_if< T[N]>
Template for array with known bounds (to throw an error).
Functions
template<class T , class... Args>
_Unique_if< T >::_Single_object make_unique (Args &&...args)
Construct a single object and return a unique pointer to it.
template<class T >
_Unique_if< T >::_Unknown_bound make_unique (size_t n)
Construct an array of objects and return a unique pointer to it.
template<class T , class... Args>
_Unique_if< T >::_Known_bound make_unique (Args &&...)=delete
It is invalid to attempt to make_unique an array with known bounds.
Function Documentation
_Unique_if<T>::_Single_object arm_compute::support::cpp14::make_unique (Args &&... args)
Construct a single object and return a unique pointer to it.
Parameters
[in] args Constructor arguments.
Returns
a unique pointer to the new object.
Definition at line 382 of file ToolchainSupport.h.
Referenced by Framework::add_test_case().
 {
     return std::unique_ptr<T>(new T(std::forward<Args>(args)...));
 }
_Unique_if<T>::_Unknown_bound arm_compute::support::cpp14::make_unique (size_t n)
Construct an array of objects and return a unique pointer to it.
Parameters
[in] n Array size
Returns
a unique pointer to the new array.
Definition at line 395 of file ToolchainSupport.h.
References make_unique(), and arm_compute::U.
 {
     typedef typename std::remove_extent<T>::type U;
     return std::unique_ptr<T>(new U[n]());
 }
_Unique_if<T>::_Known_bound arm_compute::support::cpp14::make_unique (Args && ...) delete
It is invalid to attempt to make_unique an array with known bounds.
Referenced by make_unique().