Compute Library: src/core/CL/cl_kernels/scale.cl File Reference
scale.cl File Reference
#include "helpers.h"
#include "warp_helpers.h"
Functions
const float8 transform_nearest (const float2 coord, const float2 scale)
Transforms four 2D coordinates.
const float8 transform_bilinear (const float2 coord, const float2 scale)
Transforms four 2D coordinates.
__kernel void scale_nearest_neighbour_nchw (__global uchar *in_ptr, uint in_stride_x, uint in_step_x, uint in_stride_y, uint in_step_y, uint in_offset_first_element_in_bytes, __global uchar *out_ptr, uint out_stride_x, uint out_step_x, uint out_stride_y, uint out_step_y, uint out_offset_first_element_in_bytes, const float input_width, const float input_height, const float scale_x, const float scale_y)
Performs an affine transformation on an image interpolating with the NEAREAST NEIGHBOUR method.
__kernel void scale_bilinear_nchw (__global uchar *in_ptr, uint in_stride_x, uint in_step_x, uint in_stride_y, uint in_step_y, uint in_offset_first_element_in_bytes, __global uchar *out_ptr, uint out_stride_x, uint out_step_x, uint out_stride_y, uint out_step_y, uint out_offset_first_element_in_bytes, const float input_width, const float input_height, const float scale_x, const float scale_y)
Performs an affine transformation on an image interpolating with the BILINEAR method.
__kernel void scale_nearest_neighbour_nhwc (__global uchar *in_ptr, uint in_stride_x, uint in_step_x, uint in_stride_y, uint in_step_y, uint in_stride_z, uint in_step_z, uint in_offset_first_element_in_bytes, __global uchar *out_ptr, uint out_stride_x, uint out_step_x, uint out_stride_y, uint out_step_y, uint out_stride_z, uint out_step_z, uint out_offset_first_element_in_bytes, const float input_width, const float input_height, const float scale_x, const float scale_y)
Performs scale on an image interpolating with the NEAREAST NEIGHBOUR method.
__kernel void scale_bilinear_nhwc (__global uchar *in_ptr, uint in_stride_x, uint in_step_x, uint in_stride_y, uint in_step_y, uint in_stride_z, uint in_step_z, uint in_offset_first_element_in_bytes, __global uchar *out_ptr, uint out_stride_x, uint out_step_x, uint out_stride_y, uint out_step_y, uint out_stride_z, uint out_step_z, uint out_offset_first_element_in_bytes, const float input_width, const float input_height, const float scale_x, const float scale_y)
Performs scale on an image interpolating with the BILINEAR method.
Function Documentation
__kernel void scale_bilinear_nchw (__global uchar * in_ptr, uint in_stride_x, uint in_step_x, uint in_stride_y, uint in_step_y, uint in_offset_first_element_in_bytes, __global uchar * out_ptr, uint out_stride_x, uint out_step_x, uint out_stride_y, uint out_step_y, uint out_offset_first_element_in_bytes, const float input_width, const float input_height, const float scale_x, const float scale_y)
Performs an affine transformation on an image interpolating with the BILINEAR method.
Note
Sampling policy to used is passed as -DSAMPLING_POLICY_(TYPE) e.g. -DSAMPLING_POLICY_TOP_LEFT
Parameters
[in] in_ptr Pointer to the source image. Supported data types: U8, S16.
[in] in_stride_x Stride of the source image in X dimension (in bytes)
[in] in_step_x src_stride_x * number of elements along X processed per workitem(in bytes)
[in] in_stride_y Stride of the source image in Y dimension (in bytes)
[in] in_step_y src_stride_y * number of elements along Y processed per workitem(in bytes)
[in] in_offset_first_element_in_bytes The offset of the first element in the source image
[out] out_ptr Pointer to the destination image. Supported data types: U8, S16. (Must be the same as the input)
[in] out_stride_x Stride of the destination image in X dimension (in bytes)
[in] out_step_x dst_stride_x * number of elements along X processed per workitem(in bytes)
[in] out_stride_y Stride of the destination image in Y dimension (in bytes)
[in] out_step_y dst_stride_y * number of elements along Y processed per workitem(in bytes)
[in] out_offset_first_element_in_bytes The offset of the first element in the destination image
[in] input_width Input image width
[in] input_height Input image height
[in] scale_x The scale factor along x dimension
[in] scale_y The scale factor along y dimension
Definition at line 122 of file scale.cl.
References bilinear_interpolate_with_border(), CONVERT_TO_IMAGE_STRUCT, CONVERT_TO_IMAGE_STRUCT_NO_STEP, DATA_TYPE, get_current_coords(), arm_compute::test::validation::in, arm_compute::test::validation::out, Image::ptr, and transform_bilinear().
 {
     Image        in  = CONVERT_TO_IMAGE_STRUCT_NO_STEP(in);
     Image        out = CONVERT_TO_IMAGE_STRUCT(out);
     const float2 r   = (float2)(scale_x, scale_y);
     const float8 tc  = transform_bilinear(get_current_coords(), r);
     vstore4(bilinear_interpolate_with_border(&in, tc, input_width, input_height, BORDER_SIZE), 0, (__global DATA_TYPE *)out.ptr);
 }
__kernel void scale_bilinear_nhwc (__global uchar * in_ptr, uint in_stride_x, uint in_step_x, uint in_stride_y, uint in_step_y, uint in_stride_z, uint in_step_z, uint in_offset_first_element_in_bytes, __global uchar * out_ptr, uint out_stride_x, uint out_step_x, uint out_stride_y, uint out_step_y, uint out_stride_z, uint out_step_z, uint out_offset_first_element_in_bytes, const float input_width, const float input_height, const float scale_x, const float scale_y)
Performs scale on an image interpolating with the BILINEAR method.
(NHWC)
Note
Sampling policy to be used is passed as -DSAMPLING_POLICY_(TYPE) e.g. -DSAMPLING_POLICY_TOP_LEFT
If border mode replicate is used, is should be passed as -DBORDER_MODE_REPLICATE
Parameters
[in] in_ptr Pointer to the source image. Supported data types: U8/S16/F16/F32.
[in] in_stride_x Stride of the source image in X dimension (in bytes)
[in] in_step_x src_stride_x * number of elements along X processed per workitem(in bytes)
[in] in_stride_y Stride of the source image in Y dimension (in bytes)
[in] in_step_y src_stride_y * number of elements along Y processed per workitem(in bytes)
[in] in_stride_z Stride of the source image in Z dimension (in bytes)
[in] in_step_z src_stride_z * number of elements along Z processed per workitem(in bytes)
[in] in_offset_first_element_in_bytes The offset of the first element in the source image
[out] out_ptr Pointer to the destination image. Supported data types: same as in_ptr
[in] out_stride_x Stride of the destination image in X dimension (in bytes)
[in] out_step_x dst_stride_x * number of elements along X processed per workitem(in bytes)
[in] out_stride_y Stride of the destination image in Y dimension (in bytes)
[in] out_step_y dst_stride_y * number of elements along Y processed per workitem(in bytes)
[in] out_stride_z Stride of the destination image in Z dimension (in bytes)
[in] out_step_z dst_stride_y * number of elements along Z processed per workitem(in bytes)
[in] out_offset_first_element_in_bytes The offset of the first element in the destination image
[in] input_width Input image width
[in] input_height Input image height
[in] scale_x The scale factor along x dimension
[in] scale_y The scale factor along y dimension
Definition at line 207 of file scale.cl.
References arm_compute::test::validation::a, arm_compute::test::validation::b, arm_compute::utility::clamp(), CONVERT, CONVERT_TO_TENSOR3D_STRUCT, CONVERT_TO_TENSOR3D_STRUCT_NO_STEP, DATA_TYPE, arm_compute::test::validation::in, arm_compute::test::validation::out, Tensor3D::ptr, and tensor3D_offset().
 {
     Tensor3D in  = CONVERT_TO_TENSOR3D_STRUCT_NO_STEP(in);
     Tensor3D out = CONVERT_TO_TENSOR3D_STRUCT(out);
 #ifdef SAMPLING_POLICY_TOP_LEFT
     const float new_x = get_global_id(1) * scale_x;
     const float new_y = get_global_id(2) * scale_y;
 #elif SAMPLING_POLICY_CENTER
     const float new_x = (get_global_id(1) + 0.5f) * scale_x - 0.5f;
     const float new_y = (get_global_id(2) + 0.5f) * scale_y - 0.5f;
 #else /* SAMPLING_POLICY */
 #error("Unsupported sampling policy");
 #endif /* SAMPLING_POLICY */
     const float new_xf      = floor(new_x);
     const float new_yf      = floor(new_y);
     float       clamped_x   = clamp(new_xf, 0.0f, input_width - 1);
     float       clamped_x1  = clamp(new_xf + 1, 0.0f, input_width - 1);
     float       clamped_x_  = clamped_x;
     float       clamped_x1_ = clamped_x1;
     const float clamped_y   = clamp(new_yf, 0.0f, input_height - 1);
     const float clamped_y1  = clamp(new_yf + 1, 0.0f, input_height - 1);
 #ifndef BORDER_MODE_REPLICATE
     clamped_x1  = select(clamped_x1, 0.0f - BORDER_SIZE, new_yf + 1 < 0.f || new_yf + 1 > input_height - 1 || new_xf + 1 < 0.f || new_xf + 1 > input_width - 1);
     clamped_x_  = select(clamped_x_, 0.0f - BORDER_SIZE, new_yf + 1 > input_height - 1 || new_xf < 0.f || new_xf > input_width - 1);
     clamped_x   = select(clamped_x, 0.0f - BORDER_SIZE, new_yf < 0.f || new_yf > input_height - 1 || new_xf < 0.f || new_xf > input_width - 1);
     clamped_x1_ = select(clamped_x1_, 0.0f - BORDER_SIZE, new_xf + 1 < 0.f || new_xf + 1 > input_width - 1 || new_yf < 0.f || new_yf > input_height - 1);
 #endif /* BORDER_MODE_REPLICATE */
     float4 ins = (float4)(*((__global DATA_TYPE *)tensor3D_offset(&in, get_global_id(0), convert_int(clamped_x), convert_int(clamped_y))),
                           *((__global DATA_TYPE *)tensor3D_offset(&in, get_global_id(0), convert_int(clamped_x1_), convert_int(clamped_y))),
                           *((__global DATA_TYPE *)tensor3D_offset(&in, get_global_id(0), convert_int(clamped_x_), convert_int(clamped_y1))),
                           *((__global DATA_TYPE *)tensor3D_offset(&in, get_global_id(0), convert_int(clamped_x1), convert_int(clamped_y1))));
     const float a  = new_x - new_xf;
     const float b  = 1.f - a;
     const float a1 = new_y - new_yf;
     const float b1 = 1.f - a1;
     const float fr = ((ins.s0 * b * b1) + (ins.s1 * a * b1) + (ins.s2 * b * a1) + (ins.s3 * a * a1));
     *((__global DATA_TYPE *)out.ptr) = CONVERT(fr, DATA_TYPE);
 }
__kernel void scale_nearest_neighbour_nchw (__global uchar * in_ptr, uint in_stride_x, uint in_step_x, uint in_stride_y, uint in_step_y, uint in_offset_first_element_in_bytes, __global uchar * out_ptr, uint out_stride_x, uint out_step_x, uint out_stride_y, uint out_step_y, uint out_offset_first_element_in_bytes, const float input_width, const float input_height, const float scale_x, const float scale_y)
Performs an affine transformation on an image interpolating with the NEAREAST NEIGHBOUR method.
Input and output are single channel U8 or S16.
Note
Sampling policy to used is passed as -DSAMPLING_POLICY_(TYPE) e.g. -DSAMPLING_POLICY_TOP_LEFT
Parameters
[in] in_ptr Pointer to the source image. Supported data types: U8, S16.
[in] in_stride_x Stride of the source image in X dimension (in bytes)
[in] in_step_x src_stride_x * number of elements along X processed per workitem(in bytes)
[in] in_stride_y Stride of the source image in Y dimension (in bytes)
[in] in_step_y src_stride_y * number of elements along Y processed per workitem(in bytes)
[in] in_offset_first_element_in_bytes The offset of the first element in the source image
[out] out_ptr Pointer to the destination image. Supported data types: U8, S16. (Must be the same as the input)
[in] out_stride_x Stride of the destination image in X dimension (in bytes)
[in] out_step_x dst_stride_x * number of elements along X processed per workitem(in bytes)
[in] out_stride_y Stride of the destination image in Y dimension (in bytes)
[in] out_step_y dst_stride_y * number of elements along Y processed per workitem(in bytes)
[in] out_offset_first_element_in_bytes The offset of the first element in the destination image
[in] input_width Input image width
[in] input_height Input image height
[in] scale_x The scale factor along x dimension
[in] scale_y The scale factor along y dimension
Definition at line 86 of file scale.cl.
References clamp_to_border_with_size(), CONVERT_TO_IMAGE_STRUCT, CONVERT_TO_IMAGE_STRUCT_NO_STEP, DATA_TYPE, get_current_coords(), arm_compute::test::validation::in, arm_compute::test::validation::out, Image::ptr, read_texels4(), and transform_nearest().
 {
     Image        in  = CONVERT_TO_IMAGE_STRUCT_NO_STEP(in);
     Image        out = CONVERT_TO_IMAGE_STRUCT(out);
     const float2 r   = (float2)(scale_x, scale_y);
     const float8 tc  = clamp_to_border_with_size(transform_nearest(get_current_coords(), r), input_width, input_height, BORDER_SIZE);
     vstore4(read_texels4(&in, convert_int8(tc)), 0, (__global DATA_TYPE *)out.ptr);
 }
__kernel void scale_nearest_neighbour_nhwc (__global uchar * in_ptr, uint in_stride_x, uint in_step_x, uint in_stride_y, uint in_step_y, uint in_stride_z, uint in_step_z, uint in_offset_first_element_in_bytes, __global uchar * out_ptr, uint out_stride_x, uint out_step_x, uint out_stride_y, uint out_step_y, uint out_stride_z, uint out_step_z, uint out_offset_first_element_in_bytes, const float input_width, const float input_height, const float scale_x, const float scale_y)
Performs scale on an image interpolating with the NEAREAST NEIGHBOUR method.
Input and output are single channel F32. (NHWC)
Note
Sampling policy to used is passed as -DSAMPLING_POLICY_(TYPE) e.g. -DSAMPLING_POLICY_TOP_LEFT
Parameters
[in] in_ptr Pointer to the source image. Supported data types: U8/S16/F16/F32.
[in] in_stride_x Stride of the source image in X dimension (in bytes)
[in] in_step_x src_stride_x * number of elements along X processed per workitem(in bytes)
[in] in_stride_y Stride of the source image in Y dimension (in bytes)
[in] in_step_y src_stride_y * number of elements along Y processed per workitem(in bytes)
[in] in_stride_z Stride of the source image in Z dimension (in bytes)
[in] in_step_z src_stride_z * number of elements along Z processed per workitem(in bytes)
[in] in_offset_first_element_in_bytes The offset of the first element in the source image
[out] out_ptr Pointer to the destination image. Supported data types: same as in_ptr
[in] out_stride_x Stride of the destination image in X dimension (in bytes)
[in] out_step_x dst_stride_x * number of elements along X processed per workitem(in bytes)
[in] out_stride_y Stride of the destination image in Y dimension (in bytes)
[in] out_step_y dst_stride_y * number of elements along Y processed per workitem(in bytes)
[in] out_stride_z Stride of the destination image in Z dimension (in bytes)
[in] out_step_z dst_stride_z * number of elements along Z processed per workitem(in bytes)
[in] out_offset_first_element_in_bytes The offset of the first element in the destination image
[in] input_width Input image width
[in] input_height Input image height
[in] scale_x The scale factor along x dimension
[in] scale_y The scale factor along y dimension
Definition at line 162 of file scale.cl.
References arm_compute::utility::clamp(), CONVERT_TO_TENSOR3D_STRUCT, CONVERT_TO_TENSOR3D_STRUCT_NO_STEP, DATA_TYPE, arm_compute::test::validation::in, arm_compute::test::validation::out, Tensor3D::ptr, and tensor3D_offset().
 {
     Tensor3D in  = CONVERT_TO_TENSOR3D_STRUCT_NO_STEP(in);
     Tensor3D out = CONVERT_TO_TENSOR3D_STRUCT(out);
     const float new_x     = (get_global_id(1) + 0.5f) * scale_x;
     const float new_y     = (get_global_id(2) + 0.5f) * scale_y;
     const float clamped_x = clamp(new_x, 0.0f, input_width - 1);
     const float clamped_y = clamp(new_y, 0.0f, input_height - 1);
     *((__global DATA_TYPE *)out.ptr) = *((__global DATA_TYPE *)tensor3D_offset(&in, get_global_id(0), convert_int(clamped_x), convert_int(clamped_y)));
 }
const float8 transform_bilinear (const float2 coord, const float2 scale) inline
Transforms four 2D coordinates.
This is used to map the output coordinates to the input coordinates.
Parameters
[in] coord 2D coordinates to transform.
[in] scale input/output scale ratio
Returns
a float8 containing 4 2D transformed values in the input image.
Definition at line 49 of file scale.cl.
Referenced by scale_bilinear_nchw().
 {
     const float4 in_x_coords = (float4)(coord.s0, 1 + coord.s0, 2 + coord.s0, 3 + coord.s0);
 #ifdef SAMPLING_POLICY_TOP_LEFT
     const float4 new_x = in_x_coords * (float4)(scale.s0);
     const float4 new_y = (float4)(coord.s1 * scale.s1);
     return (float8)(new_x.s0, new_y.s0, new_x.s1, new_y.s1, new_x.s2, new_y.s2, new_x.s3, new_y.s3);
 #elif SAMPLING_POLICY_CENTER
     const float4 new_x = (in_x_coords + ((float4)(0.5f))) * (float4)(scale.s0) - (float4)(0.5f);
     const float4 new_y = (float4)((coord.s1 + 0.5f) * scale.s1 - 0.5f);
     return (float8)(new_x.s0, new_y.s0, new_x.s1, new_y.s1, new_x.s2, new_y.s2, new_x.s3, new_y.s3);
 #else /* SAMPLING_POLICY */
 #error("Unsupported sampling policy");
 #endif /* SAMPLING_POLICY */
 }
const float8 transform_nearest (const float2 coord, const float2 scale) inline
Transforms four 2D coordinates.
This is used to map the output coordinates to the input coordinates.
Parameters
[in] coord 2D coordinates to transform.
[in] scale input/output scale ratio
Returns
a float8 containing 4 2D transformed values in the input image.
Definition at line 34 of file scale.cl.
Referenced by scale_nearest_neighbour_nchw().
 {
     const float4 in_x_coords = (float4)(coord.s0, 1 + coord.s0, 2 + coord.s0, 3 + coord.s0);
     const float4 new_x       = (in_x_coords + ((float4)(0.5f))) * (float4)(scale.s0);
     const float4 new_y       = (float4)((coord.s1 + 0.5f) * scale.s1);
     return (float8)(new_x.s0, new_y.s0, new_x.s1, new_y.s1, new_x.s2, new_y.s2, new_x.s3, new_y.s3);
 }