Compute Library: CLGEMMReshapeLHSMatrixKernel Class Reference
CLGEMMReshapeLHSMatrixKernel Class Reference
OpenCL kernel to reshape the LHS matrix when performing the matrix multiplication.
#include <CLGEMMReshapeLHSMatrixKernel.h>
Public Member Functions
CLGEMMReshapeLHSMatrixKernel ()
Default constructor.
CLGEMMReshapeLHSMatrixKernel (const CLGEMMReshapeLHSMatrixKernel &)=delete
Prevent instances of this class from being copied (As this class contains pointers)
CLGEMMReshapeLHSMatrixKernel & operator= (const CLGEMMReshapeLHSMatrixKernel &)=delete
Prevent instances of this class from being copied (As this class contains pointers)
CLGEMMReshapeLHSMatrixKernel (CLGEMMReshapeLHSMatrixKernel &&)=default
Allow instances of this class to be moved.
CLGEMMReshapeLHSMatrixKernel & operator= (CLGEMMReshapeLHSMatrixKernel &&)=default
Allow instances of this class to be moved.
void configure (const ICLTensor *input, ICLTensor *output, const GEMMLHSMatrixInfo &lhs_info, bool reinterpret_input_as_3d=false)
Initialise the kernel's input and output.
void configure (const CLCompileContext &compile_context, const ICLTensor *input, ICLTensor *output, const GEMMLHSMatrixInfo &lhs_info, bool reinterpret_input_as_3d=false)
Initialise the kernel's input and output.
void run (const Window &window, cl::CommandQueue &queue) override
Enqueue the OpenCL kernel to process the given window on the passed OpenCL command queue.
Public Member Functions inherited from ICLKernel
ICLKernel ()
Constructor.
cl::Kernel & kernel ()
Returns a reference to the OpenCL kernel of this object.
template<typename T >
void add_1D_array_argument (unsigned int &idx, const ICLArray< T > *array, const Strides &strides, unsigned int num_dimensions, const Window &window)
Add the passed 1D array's parameters to the object's kernel's arguments starting from the index idx.
void add_1D_tensor_argument (unsigned int &idx, const ICLTensor *tensor, const Window &window)
Add the passed 1D tensor's parameters to the object's kernel's arguments starting from the index idx.
void add_1D_tensor_argument_if (bool cond, unsigned int &idx, const ICLTensor *tensor, const Window &window)
Add the passed 1D tensor's parameters to the object's kernel's arguments starting from the index idx if the condition is true.
void add_2D_tensor_argument (unsigned int &idx, const ICLTensor *tensor, const Window &window)
Add the passed 2D tensor's parameters to the object's kernel's arguments starting from the index idx.
void add_2D_tensor_argument_if (bool cond, unsigned int &idx, const ICLTensor *tensor, const Window &window)
Add the passed 2D tensor's parameters to the object's kernel's arguments starting from the index idx if the condition is true.
void add_3D_tensor_argument (unsigned int &idx, const ICLTensor *tensor, const Window &window)
Add the passed 3D tensor's parameters to the object's kernel's arguments starting from the index idx.
void add_4D_tensor_argument (unsigned int &idx, const ICLTensor *tensor, const Window &window)
Add the passed 4D tensor's parameters to the object's kernel's arguments starting from the index idx.
template<typename T >
void add_argument (unsigned int &idx, T value)
Add the passed parameters to the object's kernel's arguments starting from the index idx.
void set_lws_hint (const cl::NDRange &lws_hint)
Set the Local-Workgroup-Size hint.
cl::NDRange lws_hint () const
Return the Local-Workgroup-Size hint.
const std::string & config_id () const
Get the configuration ID.
void set_target (GPUTarget target)
Set the targeted GPU architecture.
void set_target (cl::Device &device)
Set the targeted GPU architecture according to the CL device.
GPUTarget get_target () const
Get the targeted GPU architecture.
size_t get_max_workgroup_size ()
Get the maximum workgroup size for the device the CLKernelLibrary uses.
template<typename T , unsigned int dimension_size>
void add_array_argument (unsigned &idx, const ICLArray< T > *array, const Strides &strides, unsigned int num_dimensions, const Window &window)
Add the passed array's parameters to the object's kernel's arguments starting from the index idx.
template<unsigned int dimension_size>
void add_tensor_argument (unsigned &idx, const ICLTensor *tensor, const Window &window)
Public Member Functions inherited from IKernel
IKernel ()
Constructor.
virtual ~IKernel ()=default
Destructor.
virtual bool is_parallelisable () const
Indicates whether or not the kernel is parallelisable.
virtual BorderSize border_size () const
The size of the border for that kernel.
const Window & window () const
The maximum window the kernel can be executed on.
Static Public Member Functions
static Status validate (const ITensorInfo *input, const ITensorInfo *output, const GEMMLHSMatrixInfo &lhs_info, bool reinterpret_input_as_3d)
Static function to check if given info will lead to a valid configuration of CLGEMMReshapeLHSMatrixKernel.
Static Public Member Functions inherited from ICLKernel
static constexpr unsigned int num_arguments_per_1D_array ()
Returns the number of arguments enqueued per 1D array object.
static constexpr unsigned int num_arguments_per_1D_tensor ()
Returns the number of arguments enqueued per 1D tensor object.
static constexpr unsigned int num_arguments_per_2D_tensor ()
Returns the number of arguments enqueued per 2D tensor object.
static constexpr unsigned int num_arguments_per_3D_tensor ()
Returns the number of arguments enqueued per 3D tensor object.
static constexpr unsigned int num_arguments_per_4D_tensor ()
Returns the number of arguments enqueued per 4D tensor object.
static cl::NDRange gws_from_window (const Window &window)
Get the global work size given an execution window.
Detailed Description
OpenCL kernel to reshape the LHS matrix when performing the matrix multiplication.
In particular, this function splits the input matrix in blocks of size M0xK0 (defined through GEMMLHSInfo) and stores each one in the output matrix unrolling the values
Definition at line 37 of file CLGEMMReshapeLHSMatrixKernel.h.
Constructor & Destructor Documentation
CLGEMMReshapeLHSMatrixKernel() [1/3]
CLGEMMReshapeLHSMatrixKernel ()
Default constructor.
Definition at line 117 of file CLGEMMReshapeLHSMatrixKernel.cpp.
     : _input(nullptr), _output(nullptr), _reinterpret_input_as_3d(false)
 {
 }
CLGEMMReshapeLHSMatrixKernel() [2/3]
CLGEMMReshapeLHSMatrixKernel (const CLGEMMReshapeLHSMatrixKernel &) delete
Prevent instances of this class from being copied (As this class contains pointers)
CLGEMMReshapeLHSMatrixKernel() [3/3]
CLGEMMReshapeLHSMatrixKernel (CLGEMMReshapeLHSMatrixKernel &&) default
Allow instances of this class to be moved.
Member Function Documentation
configure() [1/2]
void configure (const ICLTensor * input, ICLTensor * output, const GEMMLHSMatrixInfo & lhs_info, bool reinterpret_input_as_3d = false)
Initialise the kernel's input and output.
Parameters
[in] input Input tensor. Data types supported: All
[out] output Output tensor. Data type supported: same as input
[in] lhs_info LHS matrix information to be used for reshaping. This object contains all the necessary information to reshape the input tensor. Only the following values are supported: lhs_info.m0: 2,3,4,5,6,7,8 lhs_info.k0: 2,3,4,8,16 lhs_info.v0: greater than 0 lhs_info.transpose: true, false lhs_info.interleave: true, false
[in] reinterpret_input_as_3d (Optional) True if the input has to be reinterpreted as 3D tensor
Definition at line 122 of file CLGEMMReshapeLHSMatrixKernel.cpp.
 {
     configure(CLKernelLibrary::get().get_compile_context(), input, output, lhs_info, reinterpret_input_as_3d);
 }
References CLKernelLibrary::get(), and arm_compute::test::validation::input.
configure() [2/2]
void configure (const CLCompileContext & compile_context, const ICLTensor * input, ICLTensor * output, const GEMMLHSMatrixInfo & lhs_info, bool reinterpret_input_as_3d = false)
Initialise the kernel's input and output.
Parameters
[in] compile_context The compile context to be used.
[in] input Input tensor. Data types supported: All
[out] output Output tensor. Data type supported: same as input
[in] lhs_info LHS matrix information to be used for reshaping. This object contains all the necessary information to reshape the input tensor. Only the following values are supported: lhs_info.m0: 2,3,4,5,6,7,8 lhs_info.k0: 2,3,4,8,16 lhs_info.v0: greater than 0 lhs_info.transpose: true, false lhs_info.interleave: true, false
[in] reinterpret_input_as_3d (Optional) True if the input has to be reinterpreted as 3D tensor
Definition at line 127 of file CLGEMMReshapeLHSMatrixKernel.cpp.
 {
     ARM_COMPUTE_ERROR_ON_NULLPTR(input, output);
     // Perform validate step
     ARM_COMPUTE_ERROR_THROW_ON(validate_arguments(input->info(), output->info(), lhs_info, reinterpret_input_as_3d));
     _input                   = input;
     _output                  = output;
     _reinterpret_input_as_3d = reinterpret_input_as_3d;
     // Create build options
     CLBuildOptions build_opts;
     build_opts.add_option("-DM0=" + support::cpp11::to_string(lhs_info.m0));
     build_opts.add_option("-DK0=" + support::cpp11::to_string(lhs_info.k0));
     build_opts.add_option("-DV0=" + support::cpp11::to_string(lhs_info.v0));
     build_opts.add_option("-DSRC_WIDTH=" + support::cpp11::to_string(input->info()->dimension(0)));
     build_opts.add_option_if(lhs_info.interleave, "-DINTERLEAVE");
     build_opts.add_option_if(_reinterpret_input_as_3d, "-DREINTERPRET_INPUT_AS_3D");
     build_opts.add_option_if(_reinterpret_input_as_3d, "-DHEIGHT_GEMM3D=" + support::cpp11::to_string(input->info()->dimension(1)));
     build_opts.add_option_if(_reinterpret_input_as_3d, "-DDEPTH_GEMM3D=" + support::cpp11::to_string(input->info()->dimension(2)));
     build_opts.add_option("-DDATA_TYPE=" + get_cl_unsigned_type_from_element_size(input->info()->element_size()));
     std::string kernel_name("gemm_reshape_lhs_matrix_");
     kernel_name += lhs_info.transpose ? "t" : "nt";
     // Create kernel
     _kernel = create_kernel(compile_context, kernel_name, build_opts.options());
     // Configure kernel window
     auto win_config = validate_and_configure_window(input->info(), output->info(), lhs_info, reinterpret_input_as_3d);
     ARM_COMPUTE_ERROR_THROW_ON(win_config.first);
     ICLKernel::configure_internal(win_config.second);
     // Set config_id for enabling LWS tuning
     _config_id = "gemm_reshape_lhs_matrix_";
     _config_id += (_reinterpret_input_as_3d ? "3d_" : "");
     _config_id += lower_string(string_from_data_type(input->info()->data_type()));
     _config_id += "_";
     _config_id += support::cpp11::to_string(output->info()->dimension(0));
     _config_id += "_";
     _config_id += support::cpp11::to_string(output->info()->dimension(1));
     _config_id += "_";
     _config_id += support::cpp11::to_string(output->info()->dimension(2));
     _config_id += "_";
     _config_id += support::cpp11::to_string(lhs_info.m0);
     _config_id += "_";
     _config_id += support::cpp11::to_string(lhs_info.k0);
     _config_id += "_";
     _config_id += support::cpp11::to_string(lhs_info.v0);
     _config_id += "_";
     _config_id += support::cpp11::to_string(lhs_info.interleave);
     _config_id += "_";
     _config_id += support::cpp11::to_string(lhs_info.transpose);
 }
References CLBuildOptions::add_option(), CLBuildOptions::add_option_if(), ARM_COMPUTE_ERROR_ON_NULLPTR, ARM_COMPUTE_ERROR_THROW_ON, arm_compute::create_kernel(), ITensorInfo::dimension(), arm_compute::get_cl_unsigned_type_from_element_size(), ITensor::info(), arm_compute::test::validation::input, GEMMLHSMatrixInfo::interleave, GEMMLHSMatrixInfo::k0, kernel_name, arm_compute::lower_string(), GEMMLHSMatrixInfo::m0, CLBuildOptions::options(), arm_compute::string_from_data_type(), arm_compute::support::cpp11::to_string(), GEMMLHSMatrixInfo::transpose, GEMMLHSMatrixInfo::v0, and arm_compute::validate_arguments().
operator=() [1/2]
CLGEMMReshapeLHSMatrixKernel& operator= (const CLGEMMReshapeLHSMatrixKernel &) delete
Prevent instances of this class from being copied (As this class contains pointers)
operator=() [2/2]
CLGEMMReshapeLHSMatrixKernel& operator= (CLGEMMReshapeLHSMatrixKernel &&) default
Allow instances of this class to be moved.
run()
void run (const Window & window, cl::CommandQueue & queue) override virtual
Enqueue the OpenCL kernel to process the given window on the passed OpenCL command queue.
Note
The queue is not flushed by this method, and therefore the kernel will not have been executed by the time this method returns.
Parameters
[in] window Region on which to execute the kernel. (Must be a valid region of the window returned by window()).
[in,out] queue Command queue on which to enqueue the kernel.
Implements ICLKernel.
Definition at line 191 of file CLGEMMReshapeLHSMatrixKernel.cpp.
 {
     ARM_COMPUTE_ERROR_ON_UNCONFIGURED_KERNEL(this);
     ARM_COMPUTE_ERROR_ON_INVALID_SUBWINDOW(ICLKernel::window(), window);
     Window slice = window.first_slice_window_3D();
     if(_reinterpret_input_as_3d)
     {
         // Pass bottom paddings to the kernel if the input has to be reinterpreted as 3D tensor
         const unsigned int idx0                  = 2 * num_arguments_per_3D_tensor();
         const unsigned int total_cross_plane_pad = _input->info()->padding().top + _input->info()->padding().bottom;
         _kernel.setArg<cl_uint>(idx0, static_cast<unsigned int>(total_cross_plane_pad));
     }
     do
     {
         unsigned int idx = 0;
         add_3D_tensor_argument(idx, _input, slice);
         add_3D_tensor_argument(idx, _output, slice);
         enqueue(queue, *this, slice, lws_hint());
     }
     while(window.slide_window_slice_3D(slice));
 }
References ICLKernel::add_3D_tensor_argument(), ARM_COMPUTE_ERROR_ON_INVALID_SUBWINDOW, ARM_COMPUTE_ERROR_ON_UNCONFIGURED_KERNEL, BorderSize::bottom, arm_compute::enqueue(), Window::first_slice_window_3D(), ITensor::info(), ICLKernel::lws_hint(), ICLKernel::num_arguments_per_3D_tensor(), ITensorInfo::padding(), arm_compute::test::validation::reference::slice(), Window::slide_window_slice_3D(), BorderSize::top, and IKernel::window().
validate()
Status validate (const ITensorInfo * input, const ITensorInfo * output, const GEMMLHSMatrixInfo & lhs_info, bool reinterpret_input_as_3d) static
Static function to check if given info will lead to a valid configuration of CLGEMMReshapeLHSMatrixKernel.
Parameters
[in] input Input tensor info. Data types supported: All
[in] output Output tensor info which stores the interleaved matrix. Data type supported: same as input.
[in] lhs_info LHS matrix information to be used for reshaping. This object contains all the necessary information to reshape the input tensor. Only the following values are supported: lhs_info.m0: 2,3,4,5,6,7,8 lhs_info.k0: 2,3,4,8,16 lhs_info.v0: greater than 0 lhs_info.transpose: true, false lhs_info.interleave: true, false
[in] reinterpret_input_as_3d True if the input has to be reinterpreted as 3D tensor
Returns
a status
Definition at line 183 of file CLGEMMReshapeLHSMatrixKernel.cpp.
 {
     ARM_COMPUTE_RETURN_ON_ERROR(validate_arguments(input, output, lhs_info, reinterpret_input_as_3d));
     ARM_COMPUTE_RETURN_ON_ERROR(validate_and_configure_window(input->clone().get(), output->clone().get(), lhs_info, reinterpret_input_as_3d).first);
     return Status{};
 }
References ARM_COMPUTE_RETURN_ON_ERROR, ICloneable< T >::clone(), arm_compute::test::validation::input, and arm_compute::validate_arguments().
The documentation for this class was generated from the following files:
arm_compute/core/CL/kernels/CLGEMMReshapeLHSMatrixKernel.h
src/core/CL/kernels/CLGEMMReshapeLHSMatrixKernel.cpp