Compute Library: NEPoolingLayer Class Reference
NEPoolingLayer Class Reference
Basic function to simulate a pooling layer with the specified pooling operation.
#include <NEPoolingLayer.h>
Public Member Functions
NEPoolingLayer ()
Constructor.
void configure (ITensor *input, ITensor *output, const PoolingLayerInfo &pool_info, ITensor *indices=nullptr)
Set the input and output tensors.
void run () override
Run the kernels contained in the function.
Public Member Functions inherited from IFunction
virtual ~IFunction ()=default
Destructor.
virtual void prepare ()
Prepare the function for executing.
Static Public Member Functions
static Status validate (const ITensorInfo *input, const ITensorInfo *output, const PoolingLayerInfo &pool_info, const ITensorInfo *indices=nullptr)
Static function to check if given info will lead to a valid configuration of NEPoolingLayer.
Detailed Description
Basic function to simulate a pooling layer with the specified pooling operation.
This function calls the following NEON kernels:
NEFillBorderKernel (executed if padding size is different from zero)
NEPoolingLayerKernel
Definition at line 42 of file NEPoolingLayer.h.
Constructor & Destructor Documentation
NEPoolingLayer()
NEPoolingLayer ()
Constructor.
Definition at line 31 of file NEPoolingLayer.cpp.
     : _pooling_layer_kernel(), _border_handler(), _is_global_pooling_layer(false), _data_layout(DataLayout::NCHW)
 {
 }
References arm_compute::NCHW.
Member Function Documentation
configure()
void configure (ITensor * input, ITensor * output, const PoolingLayerInfo & pool_info, ITensor * indices = nullptr)
Set the input and output tensors.
Note
F16 is supported for pool sizes 2 and 3 only
Parameters
[in,out] input Source tensor. (Written to only when padding != 0) Data types supported: QASYMM8/QASYMM8_SIGNED/F16/F32.
[out] output Destination tensor. Data types supported: Same as input.
[in] pool_info Contains pooling operation information described in PoolingLayerInfo.
[out] indices (optional) The indices of the maximal values. Data type supported: U32.
Definition at line 36 of file NEPoolingLayer.cpp.
 {
     // Check if we have Global Pooling Layer
     _is_global_pooling_layer = (input->info()->dimension(0) == pool_info.pool_size.width) && (input->info()->dimension(1) == pool_info.pool_size.height);
     // Get data layout
     _data_layout = pool_info.data_layout == DataLayout::UNKNOWN ? input->info()->data_layout() : pool_info.data_layout;
     // Configure pooling kernel
     _pooling_layer_kernel.configure(input, output, pool_info, indices);
     switch(_data_layout)
     {
         case DataLayout::NCHW:
         {
             // Configure border depending on operation required (quantize border in case of asymmetric data_type)
             BorderMode border_mode = (pool_info.pool_type == PoolingType::MAX) ? BorderMode::REPLICATE : BorderMode::CONSTANT;
             PixelValue zero_value(0.f);
             if(is_data_type_quantized_asymmetric(input->info()->data_type()) && !pool_info.exclude_padding)
             {
                 zero_value = PixelValue(0, input->info()->data_type(), input->info()->quantization_info());
             }
             _border_handler.configure(input, _pooling_layer_kernel.border_size(), border_mode, zero_value);
             break;
         }
         case DataLayout::NHWC:
             break;
         default:
             ARM_COMPUTE_ERROR("Data layout not supported");
     }
 }
References ARM_COMPUTE_ERROR, arm_compute::test::validation::border_mode, NEPoolingLayerKernel::border_size(), NEPoolingLayerKernel::configure(), NEFillBorderKernel::configure(), arm_compute::CONSTANT, PoolingLayerInfo::data_layout, PoolingLayerInfo::exclude_padding, Size2D::height, arm_compute::test::validation::input, arm_compute::is_data_type_quantized_asymmetric(), arm_compute::MAX, arm_compute::NCHW, arm_compute::NHWC, PoolingLayerInfo::pool_size, PoolingLayerInfo::pool_type, arm_compute::REPLICATE, arm_compute::UNKNOWN, and Size2D::width.
run()
void run () override virtual
Run the kernels contained in the function.
For NEON kernels:
Multi-threading is used for the kernels which are parallelisable.
By default std::thread::hardware_concurrency() threads are used.
Note
CPPScheduler::set_num_threads() can be used to manually set the number of threads
For OpenCL kernels:
All the kernels are enqueued on the queue associated with CLScheduler.
The queue is then flushed.
Note
The function will not block until the kernels are executed. It is the user's responsibility to wait.
Will call prepare() on first run if hasn't been done
Implements IFunction.
Definition at line 73 of file NEPoolingLayer.cpp.
 {
     switch(_data_layout)
     {
         case DataLayout::NCHW:
             // Fill border
             NEScheduler::get().schedule(&_border_handler, Window::DimY);
             // Run pooling layer
             NEScheduler::get().schedule(&_pooling_layer_kernel, _is_global_pooling_layer ? Window::DimZ : Window::DimY);
             break;
         case DataLayout::NHWC:
             // Run pooling layer
             NEScheduler::get().schedule(&_pooling_layer_kernel, Window::DimX);
             break;
         default:
             ARM_COMPUTE_ERROR("Data layout not supported");
     }
 }
References ARM_COMPUTE_ERROR, Window::DimX, Window::DimY, Window::DimZ, Scheduler::get(), arm_compute::NCHW, arm_compute::NHWC, and IScheduler::schedule().
validate()
Status validate (const ITensorInfo * input, const ITensorInfo * output, const PoolingLayerInfo & pool_info, const ITensorInfo * indices = nullptr) static
Static function to check if given info will lead to a valid configuration of NEPoolingLayer.
Note
F16 is supported for pool sizes 2 and 3 only
Parameters
[in] input Source tensor. (Written to only when padding != 0) Data types supported: QASYMM8/QASYMM8_SIGNED/F16/F32.
[in] output Destination tensor. Data types supported: Same as input.
[in] pool_info Contains pooling operation information described in PoolingLayerInfo.
[in] indices (optional) The indices of the maximal values. Data type supported: U32.
Returns
a status
Definition at line 68 of file NEPoolingLayer.cpp.
 {
     return NEPoolingLayerKernel::validate(input, output, pool_info, indices);
 }
References arm_compute::test::validation::input, and NEPoolingLayerKernel::validate().
The documentation for this class was generated from the following files:
arm_compute/runtime/NEON/functions/NEPoolingLayer.h
src/runtime/NEON/functions/NEPoolingLayer.cpp