Compute Library: NEGEMMMatrixVectorMultiplyKernel Class Reference
NEGEMMMatrixVectorMultiplyKernel Class Reference
Interface for the GEMM matrix vector multiply kernel.
#include <NEGEMMMatrixVectorMultiplyKernel.h>
Public Member Functions
const char * name () const override
Name of the kernel.
NEGEMMMatrixVectorMultiplyKernel ()
Default constructor.
NEGEMMMatrixVectorMultiplyKernel (const NEGEMMMatrixVectorMultiplyKernel &)=delete
Prevent instances of this class from being copied (As this class contains pointers)
NEGEMMMatrixVectorMultiplyKernel & operator= (const NEGEMMMatrixVectorMultiplyKernel &)=delete
Prevent instances of this class from being copied (As this class contains pointers)
NEGEMMMatrixVectorMultiplyKernel (NEGEMMMatrixVectorMultiplyKernel &&)=default
Allow instances of this class to be moved.
NEGEMMMatrixVectorMultiplyKernel & operator= (NEGEMMMatrixVectorMultiplyKernel &&)=default
Allow instances of this class to be moved.
void configure (const ITensor *input0, const ITensor *input1, ITensor *output)
Initialise the kernel's input and output.
void run (const Window &window, const ThreadInfo &info) override
Execute the kernel on the passed window.
BorderSize border_size () const override
The size of the border for that kernel.
Public Member Functions inherited from ICPPSimpleKernel
ICPPSimpleKernel ()
Constructor.
ICPPSimpleKernel (const ICPPSimpleKernel &)=delete
Prevent instances of this class from being copied (As this class contains pointers)
ICPPSimpleKernel & operator= (const ICPPSimpleKernel &)=delete
Prevent instances of this class from being copied (As this class contains pointers)
ICPPSimpleKernel (ICPPSimpleKernel &&)=default
Allow instances of this class to be moved.
ICPPSimpleKernel & operator= (ICPPSimpleKernel &&)=default
Allow instances of this class to be moved.
~ICPPSimpleKernel ()=default
Default destructor.
Public Member Functions inherited from ICPPKernel
virtual ~ICPPKernel ()=default
Default destructor.
virtual void run_nd (const Window &window, const ThreadInfo &info, const Window &thread_locator)
legacy compatibility layer for implemantions which do not support thread_locator In these cases we simply narrow the interface down the legacy version
Public Member Functions inherited from IKernel
IKernel ()
Constructor.
virtual ~IKernel ()=default
Destructor.
virtual bool is_parallelisable () const
Indicates whether or not the kernel is parallelisable.
const Window & window () const
The maximum window the kernel can be executed on.
Static Public Member Functions
static Status validate (const ITensorInfo *input0, const ITensorInfo *input1, const ITensorInfo *output)
Static function to check if given info will lead to a valid configuration of NEGEMMMatrixVectorMultiplyKernel.
Detailed Description
Interface for the GEMM matrix vector multiply kernel.
Definition at line 34 of file NEGEMMMatrixVectorMultiplyKernel.h.
Constructor & Destructor Documentation
NEGEMMMatrixVectorMultiplyKernel() [1/3]
NEGEMMMatrixVectorMultiplyKernel ()
Default constructor.
Definition at line 322 of file NEGEMMMatrixVectorMultiplyKernel.cpp.
     : _func(nullptr), _input0(nullptr), _input1(nullptr), _output(nullptr), _border_size(0)
 {
 }
NEGEMMMatrixVectorMultiplyKernel() [2/3]
NEGEMMMatrixVectorMultiplyKernel (const NEGEMMMatrixVectorMultiplyKernel &) delete
Prevent instances of this class from being copied (As this class contains pointers)
NEGEMMMatrixVectorMultiplyKernel() [3/3]
NEGEMMMatrixVectorMultiplyKernel (NEGEMMMatrixVectorMultiplyKernel &&) default
Allow instances of this class to be moved.
Member Function Documentation
border_size()
BorderSize border_size () const override virtual
The size of the border for that kernel.
Returns
The width in number of elements of the border.
Reimplemented from IKernel.
Definition at line 327 of file NEGEMMMatrixVectorMultiplyKernel.cpp.
 {
     return _border_size;
 }
configure()
void configure (const ITensor * input0, const ITensor * input1, ITensor * output)
Initialise the kernel's input and output.
Parameters
[in] input0 First Input tensor. Data types supported: QASYMM8/QASYMM8_SIGNED/F16/F32
[in] input1 Second Input tensor. Data types supported: same as input.
[out] output Output tensor which stores the interleaved matrix. Data type supported: same as input, S32 for QASYMM8/QASYMM8_SIGNED input.
Definition at line 332 of file NEGEMMMatrixVectorMultiplyKernel.cpp.
 {
     ARM_COMPUTE_ERROR_ON_NULLPTR(input0, input1, output);
     ARM_COMPUTE_ERROR_THROW_ON(validate_arguments(input0->info(), input1->info(), output->info()));
     _input0 = input0;
     _input1 = input1;
     _output = output;
     // Set appropriate function to run
     switch(input0->info()->data_type())
     {
         case DataType::QASYMM8:
             _func = &NEGEMMMatrixVectorMultiplyKernel::matrix_vector_multiply<uint8_t, uint8_t, int32_t>;
             break;
         case DataType::QASYMM8_SIGNED:
             _func = &NEGEMMMatrixVectorMultiplyKernel::matrix_vector_multiply<int8_t, int8_t, int32_t>;
             break;
 #ifdef __ARM_FEATURE_FP16_VECTOR_ARITHMETIC
         case DataType::F16:
             _func = &NEGEMMMatrixVectorMultiplyKernel::matrix_vector_multiply<half, half, half>;
             break;
 #endif /* __ARM_FEATURE_FP16_VECTOR_ARITHMETIC */
         case DataType::F32:
             _func = &NEGEMMMatrixVectorMultiplyKernel::matrix_vector_multiply<float, float, float>;
             break;
         default:
             ARM_COMPUTE_ERROR("Unsupported data type");
     }
     // Configure kernel window
     const unsigned int num_elems_read_per_iteration = 16 / _input0->info()->element_size();
     const unsigned int border_x = ceil_to_multiple(input0->info()->dimension(0), num_elems_read_per_iteration) - input0->info()->dimension(0);
     _border_size                = BorderSize(0, border_x);
     auto win_config = validate_and_configure_window(input0->info(), input1->info(), output->info());
     ARM_COMPUTE_ERROR_THROW_ON(win_config.first);
     INEKernel::configure(win_config.second);
 }
References ARM_COMPUTE_ERROR, ARM_COMPUTE_ERROR_ON_NULLPTR, ARM_COMPUTE_ERROR_THROW_ON, arm_compute::ceil_to_multiple(), ITensorInfo::data_type(), ITensorInfo::dimension(), ITensorInfo::element_size(), arm_compute::F16, arm_compute::F32, ITensor::info(), arm_compute::QASYMM8, arm_compute::QASYMM8_SIGNED, and arm_compute::validate_arguments().
name()
const char* name () const inline override virtual
Name of the kernel.
Returns
Kernel name
Implements ICPPKernel.
Definition at line 37 of file NEGEMMMatrixVectorMultiplyKernel.h.
     {
         return "NEGEMMMatrixVectorMultiplyKernel";
     }
operator=() [1/2]
NEGEMMMatrixVectorMultiplyKernel& operator= (const NEGEMMMatrixVectorMultiplyKernel &) delete
Prevent instances of this class from being copied (As this class contains pointers)
operator=() [2/2]
NEGEMMMatrixVectorMultiplyKernel& operator= (NEGEMMMatrixVectorMultiplyKernel &&) default
Allow instances of this class to be moved.
run()
void run (const Window & window, const ThreadInfo & info) override virtual
Execute the kernel on the passed window.
Warning
If is_parallelisable() returns false then the passed window must be equal to window()
Note
The window has to be a region within the window returned by the window() method
The width of the window has to be a multiple of num_elems_processed_per_iteration().
Parameters
[in] window Region on which to execute the kernel. (Must be a region of the window returned by window())
[in] info Info about executing thread and CPU.
Reimplemented from ICPPKernel.
Definition at line 381 of file NEGEMMMatrixVectorMultiplyKernel.cpp.
 {
     ARM_COMPUTE_UNUSED(info);
     ARM_COMPUTE_ERROR_ON_UNCONFIGURED_KERNEL(this);
     ARM_COMPUTE_ERROR_ON_INVALID_SUBWINDOW(INEKernel::window(), window);
     ARM_COMPUTE_ERROR_ON(_func == nullptr);
     Window window_slice = window.first_slice_window_3D();
     Window window_in(window);
     Window window_weights(window_slice);
     Window window_out(window);
     // Setup input0 slice
     window_in.set(Window::DimX, Window::Dimension(0, _input0->info()->dimension(0), _input0->info()->dimension(0)));
     window_in.set(Window::DimY, Window::Dimension(0, _input0->info()->dimension(1), 1));
     window_in.set(Window::DimZ, Window::Dimension(0, _input0->info()->dimension(2), 1));
     // Setup input1 and output slice. Their dimensions are increased in the kernel.
     window_weights.set(Window::DimX, Window::Dimension(0, 0, 0));
     window_weights.set(Window::DimY, Window::Dimension(0, 0, 0));
     window_weights.set(Window::DimZ, Window::Dimension(0, 0, 0));
     window_out.set(Window::DimX, Window::Dimension(0, 0, 0));
     window_out.set(Window::DimY, Window::Dimension(0, 0, 0));
     window_out.set(Window::DimZ, Window::Dimension(0, 0, 0));
     (this->*_func)(window_in, window_weights, window_out);
 }
References ARM_COMPUTE_ERROR_ON, ARM_COMPUTE_ERROR_ON_INVALID_SUBWINDOW, ARM_COMPUTE_ERROR_ON_UNCONFIGURED_KERNEL, ARM_COMPUTE_UNUSED, ITensorInfo::dimension(), Window::DimX, Window::DimY, Window::DimZ, Window::first_slice_window_3D(), ITensor::info(), arm_compute::test::validation::info, Window::set(), and IKernel::window().
validate()
Status validate (const ITensorInfo * input0, const ITensorInfo * input1, const ITensorInfo * output) static
Static function to check if given info will lead to a valid configuration of NEGEMMMatrixVectorMultiplyKernel.
Parameters
[in] input0 First Input tensor. Data types supported: QASYMM8/QASYMM8_SIGNED/F16/F32
[in] input1 Second Input tensor. Data types supported: same as input.
[in] output Output tensor which stores the interleaved matrix. Data type supported: same as input, S32 for QASYMM8/QASYMM8_SIGNED input.
Returns
a status
Definition at line 373 of file NEGEMMMatrixVectorMultiplyKernel.cpp.
 {
     ARM_COMPUTE_RETURN_ERROR_ON_NULLPTR(input0, input1, output);
     ARM_COMPUTE_RETURN_ON_ERROR(validate_arguments(input0, input1, output));
     ARM_COMPUTE_RETURN_ON_ERROR(validate_and_configure_window(input0->clone().get(), input1->clone().get(), output->clone().get()).first);
     return Status{};
 }
References ARM_COMPUTE_RETURN_ERROR_ON_NULLPTR, ARM_COMPUTE_RETURN_ON_ERROR, ICloneable< T >::clone(), and arm_compute::validate_arguments().
The documentation for this class was generated from the following files:
arm_compute/core/NEON/kernels/NEGEMMMatrixVectorMultiplyKernel.h
src/core/NEON/kernels/NEGEMMMatrixVectorMultiplyKernel.cpp