Compute Library: CPPScheduler Class Reference
CPPScheduler Class Reference final
C++11 implementation of a pool of threads to automatically split a kernel's execution among several threads.
#include <CPPScheduler.h>
Public Member Functions
CPPScheduler ()
Constructor: create a pool of threads.
~CPPScheduler ()
Default destructor.
void set_num_threads (unsigned int num_threads) override
Sets the number of threads the scheduler will use to run the kernels.
unsigned int num_threads () const override
Returns the number of threads that the CPPScheduler has in his pool.
void schedule (ICPPKernel *kernel, const Hints &hints) override
Multithread the execution of the passed kernel if possible.
Public Member Functions inherited from IScheduler
IScheduler ()
Default constructor.
virtual ~IScheduler ()=default
Destructor.
virtual void run_tagged_workloads (std::vector< Workload > &workloads, const char *tag)
Execute all the passed workloads.
CPUInfo & cpu_info ()
Get CPU info.
unsigned int num_threads_hint () const
Get a hint for the best possible number of execution threads.
Static Public Member Functions
static CPPScheduler & get ()
Access the scheduler singleton.
Additional Inherited Members
Public Types inherited from IScheduler
enum StrategyHint { STATIC, DYNAMIC }
Strategies available to split a workload.
using Workload = std::function< void(const ThreadInfo &)>
Signature for the workloads to execute.
Static Public Attributes inherited from IScheduler
static constexpr unsigned int split_dimensions_all = std::numeric_limits<unsigned>::max()
When arm_compute::ISchedular::Hints::_split_dimension is initialized with this value then the schedular is free to break down the problem space over as many dimensions as it wishes.
Detailed Description
C++11 implementation of a pool of threads to automatically split a kernel's execution among several threads.
Definition at line 34 of file CPPScheduler.h.
Constructor & Destructor Documentation
CPPScheduler()
CPPScheduler ()
Constructor: create a pool of threads.
Definition at line 303 of file CPPScheduler.cpp.
     : _impl(support::cpp14::make_unique<Impl>(num_threads_hint()))
 {
 }
~CPPScheduler()
~CPPScheduler () default
Default destructor.
Member Function Documentation
get()
CPPScheduler & get () static
Access the scheduler singleton.
Note
this method has been deprecated and will be remover in the upcoming releases
Returns
The scheduler
Definition at line 297 of file CPPScheduler.cpp.
 {
     static CPPScheduler scheduler;
     return scheduler;
 }
num_threads()
unsigned int num_threads () const override virtual
Returns the number of threads that the CPPScheduler has in his pool.
Returns
Number of threads available in CPPScheduler.
Implements IScheduler.
Definition at line 317 of file CPPScheduler.cpp.
 {
     return _impl->num_threads();
 }
Referenced by CPPScheduler::schedule(), and CPPScheduler::set_num_threads().
schedule()
void schedule (ICPPKernel * kernel, const Hints & hints) override virtual
Multithread the execution of the passed kernel if possible.
The kernel will run on a single thread if any of these conditions is true:
ICPPKernel::is_parallelisable() returns false
The scheduler has been initialized with only one thread.
Parameters
[in] kernel Kernel to execute.
[in] hints Hints for the scheduler.
Implements IScheduler.
Definition at line 367 of file CPPScheduler.cpp.
 {
     ARM_COMPUTE_ERROR_ON_MSG(!kernel, "The child class didn't set the kernel");
     const Window      &max_window     = kernel->window();
     if(hints.split_dimension() == IScheduler::split_dimensions_all)
     {
         /*
          * if the split dim is size_t max then this signals we should parallelise over
          * all dimensions
          */
         const std::size_t m = max_window.num_iterations(Window::DimX);
         const std::size_t n = max_window.num_iterations(Window::DimY);
        //in c++17 this can be swapped for   auto [ m_threads, n_threads ] = split_2d(...
         unsigned m_threads, n_threads;
         std::tie(m_threads, n_threads) = split_2d(_impl->_num_threads, m, n);
         std::vector<IScheduler::Workload> workloads;
         for(unsigned int ni  = 0; ni != n_threads; ++ni)
         {
             for(unsigned int mi  = 0; mi != m_threads; ++mi)
             {
                 workloads.push_back(
                     [ ni, mi, m_threads, n_threads, &max_window, &kernel ]
                     (const ThreadInfo & info)
                     {
                         //narrow the window to our mi-ni workload
                         Window win = max_window.split_window(Window::DimX, mi, m_threads)
                                                .split_window(Window::DimY, ni, n_threads);
                         win.validate();
                         Window thread_locator;
                         thread_locator.set(Window::DimX, Window::Dimension(mi, m_threads));
                         thread_locator.set(Window::DimY, Window::Dimension(ni, n_threads));
                         thread_locator.validate();
                         kernel->run_nd(win, info, thread_locator);
                     }
                 );
             }
         }
         run_workloads(workloads);
     }
     else
     {
         const unsigned int num_iterations = max_window.num_iterations(hints.split_dimension());
         const unsigned int num_threads    = std::min(num_iterations, _impl->_num_threads);
         if(num_iterations == 0)
         {
             return;
         }
         if(!kernel->is_parallelisable() || num_threads == 1)
         {
             ThreadInfo info;
             info.cpu_info = &_cpu_info;
             kernel->run(max_window, info);
         }
         else
         {
             unsigned int num_windows = 0;
             switch(hints.strategy())
             {
                 case StrategyHint::STATIC:
                     num_windows = num_threads;
                     break;
                 case StrategyHint::DYNAMIC:
                 {
                     const unsigned int granule_threshold = (hints.threshold() <= 0) ? num_threads : static_cast<unsigned int>(hints.threshold());
                     // Make sure we don't use some windows which are too small as this might create some contention on the ThreadFeeder
                     num_windows = num_iterations > granule_threshold ? granule_threshold : num_iterations;
                     break;
                 }
                 default:
                     ARM_COMPUTE_ERROR("Unknown strategy");
             }
             std::vector<IScheduler::Workload> workloads(num_windows);
             for(unsigned int t = 0; t < num_windows; t++)
             {
                 //Capture 't' by copy, all the other variables by reference:
                 workloads[t] = [t, &hints, &max_window, &num_windows, &kernel](const ThreadInfo & info)
                 {
                     Window win = max_window.split_window(hints.split_dimension(), t, num_windows);
                     win.validate();
                     kernel->run(win, info);
                 };
             }
             run_workloads(workloads);
         }
     }
 }
References ARM_COMPUTE_ERROR, ARM_COMPUTE_ERROR_ON_MSG, Window::DimX, Window::DimY, IScheduler::DYNAMIC, arm_compute::test::validation::info, IKernel::is_parallelisable(), Window::num_iterations(), CPPScheduler::num_threads(), ICPPKernel::run(), ICPPKernel::run_nd(), Window::set(), IScheduler::Hints::split_dimension(), IScheduler::split_dimensions_all, Window::split_window(), IScheduler::STATIC, IScheduler::Hints::strategy(), IScheduler::Hints::threshold(), Window::validate(), and IKernel::window().
set_num_threads()
void set_num_threads (unsigned int num_threads) override virtual
Sets the number of threads the scheduler will use to run the kernels.
Parameters
[in] num_threads If set to 0, then the maximum number of threads supported by C++11 will be used, otherwise the number of threads specified.
Implements IScheduler.
Definition at line 310 of file CPPScheduler.cpp.
 {
     // No changes in the number of threads while current workloads are running
     arm_compute::lock_guard<std::mutex> lock(_impl->_run_workloads_mutex);
     _impl->set_num_threads(num_threads, num_threads_hint());
 }
References CPPScheduler::num_threads(), and IScheduler::num_threads_hint().
The documentation for this class was generated from the following files:
arm_compute/runtime/CPP/CPPScheduler.h
src/runtime/CPP/CPPScheduler.cpp