Compute Library: NEPoolingLayerKernel Class Reference
NEPoolingLayerKernel Class Reference
Interface for the pooling layer kernel.
#include <NEPoolingLayerKernel.h>
Public Member Functions
const char * name () const override
Name of the kernel.
NEPoolingLayerKernel ()
Default constructor.
NEPoolingLayerKernel (const NEPoolingLayerKernel &)=delete
Prevent instances of this class from being copied (As this class contains pointers)
NEPoolingLayerKernel & operator= (const NEPoolingLayerKernel &)=delete
Prevent instances of this class from being copied (As this class contains pointers)
NEPoolingLayerKernel (NEPoolingLayerKernel &&)=default
Allow instances of this class to be moved.
NEPoolingLayerKernel & operator= (NEPoolingLayerKernel &&)=default
Allow instances of this class to be moved.
~NEPoolingLayerKernel ()=default
Default destructor.
void configure (const ITensor *input, ITensor *output, const PoolingLayerInfo &pool_info, ITensor *indices=nullptr)
Set the input and output tensors.
void run (const Window &window, const ThreadInfo &info) override
Execute the kernel on the passed window.
BorderSize border_size () const override
The size of the border for that kernel.
Public Member Functions inherited from ICPPKernel
virtual ~ICPPKernel ()=default
Default destructor.
virtual void run_nd (const Window &window, const ThreadInfo &info, const Window &thread_locator)
legacy compatibility layer for implemantions which do not support thread_locator In these cases we simply narrow the interface down the legacy version
Public Member Functions inherited from IKernel
IKernel ()
Constructor.
virtual ~IKernel ()=default
Destructor.
virtual bool is_parallelisable () const
Indicates whether or not the kernel is parallelisable.
const Window & window () const
The maximum window the kernel can be executed on.
Static Public Member Functions
static Status validate (const ITensorInfo *input, const ITensorInfo *output, const PoolingLayerInfo &pool_info, const ITensorInfo *indices=nullptr)
Static function to check if given info will lead to a valid configuration of NEPoolingLayerKernel.
Detailed Description
Interface for the pooling layer kernel.
Definition at line 34 of file NEPoolingLayerKernel.h.
Constructor & Destructor Documentation
NEPoolingLayerKernel() [1/3]
NEPoolingLayerKernel ()
Default constructor.
Definition at line 470 of file NEPoolingLayerKernel.cpp.
     : _func(nullptr), _input(nullptr), _output(nullptr), _indices(nullptr), _pool_info(), _data_layout(DataLayout::UNKNOWN), _num_elems_processed_per_iteration(0), _border_size(0), _is_square(false)
 {
 }
NEPoolingLayerKernel() [2/3]
NEPoolingLayerKernel (const NEPoolingLayerKernel &) delete
Prevent instances of this class from being copied (As this class contains pointers)
NEPoolingLayerKernel() [3/3]
NEPoolingLayerKernel (NEPoolingLayerKernel &&) default
Allow instances of this class to be moved.
~NEPoolingLayerKernel()
~NEPoolingLayerKernel () default
Default destructor.
Member Function Documentation
border_size()
BorderSize border_size () const override virtual
The size of the border for that kernel.
Returns
The width in number of elements of the border.
Reimplemented from IKernel.
Definition at line 475 of file NEPoolingLayerKernel.cpp.
 {
     return _border_size;
 }
Referenced by NEPoolingLayer::configure(), and NEPoolingLayerKernel::validate().
configure()
void configure (const ITensor * input, ITensor * output, const PoolingLayerInfo & pool_info, ITensor * indices = nullptr)
Set the input and output tensors.
Note
F16 are supported for pool sizes 2 and 3 only
Parameters
[in] input Source tensor. Data types supported: QASYMM8/QASYMM8_SIGNED/F16/F32.
[out] output Destination tensor. Data types supported: Same as input.
[in] pool_info Contains pooling operation information described in PoolingLayerInfo.
[out] indices (optional) The indices of the maximal values. Data type supported: U32.
Definition at line 480 of file NEPoolingLayerKernel.cpp.
 {
     ARM_COMPUTE_ERROR_ON_NULLPTR(input, output);
     const PadStrideInfo pad_stride_info   = pool_info.pad_stride_info;
     const bool          is_global_pooling = pool_info.is_global_pooling;
     const int           pool_stride_x     = pad_stride_info.stride().first;
     // Get data layout
     const auto data_layout = pool_info.data_layout == DataLayout::UNKNOWN ? input->info()->data_layout() : pool_info.data_layout;
     const int  idx_width   = get_data_layout_dimension_index(data_layout, DataLayoutDimension::WIDTH);
     const int  idx_height  = get_data_layout_dimension_index(data_layout, DataLayoutDimension::HEIGHT);
     // Update pool size in case of global pooling
     const Size2D pool_size(
         is_global_pooling ? input->info()->dimension(idx_width) : pool_info.pool_size.width,
         is_global_pooling ? input->info()->dimension(idx_height) : pool_info.pool_size.height);
     // Validate pool info before calling scaled_dimensions
     ARM_COMPUTE_ERROR_THROW_ON(validate_arguments_pool_info(pool_size.x(), pool_size.y()));
     // Check output dimensions
     unsigned int pooled_w;
     unsigned int pooled_h;
     std::tie(pooled_w, pooled_h) = scaled_dimensions(input->info()->dimension(idx_width),
                                                      input->info()->dimension(idx_height),
                                                      pool_size.x(),
                                                      pool_size.y(),
                                                      pad_stride_info);
     // Perform validation step
     ARM_COMPUTE_ERROR_THROW_ON(validate_arguments(input->info(), output->info(), pool_info, pooled_w, pooled_h, (indices) ? indices->info() : nullptr, pool_size));
     // Set instance variables
     _input       = input;
     _output      = output;
     _indices     = indices;
     _pool_info   = pool_info;
     _data_layout = input->info()->data_layout();
     _is_square   = (pool_size.x() == pool_size.y());
     // Get data type
     const DataType data_type = input->info()->data_type();
     const bool     is_nchw   = _data_layout == DataLayout::NCHW;
     if(data_type == DataType::QASYMM8)
     {
         if(pool_size.x() == 2 && pool_stride_x < 3 && _is_square)
         {
             if(is_nchw)
             {
                 _func = &NEPoolingLayerKernel::pooling2_q8_nchw<uint8_t>;
             }
             else
             {
                 _func = &NEPoolingLayerKernel::poolingMxN_q8_nhwc<uint8_t>;
             }
         }
         else if(pool_size.x() == 3 && pool_stride_x < 3 && _is_square)
         {
             if(is_nchw)
             {
                 _func = &NEPoolingLayerKernel::pooling3_q8_nchw<uint8_t>;
             }
             else
             {
                 _func = &NEPoolingLayerKernel::poolingMxN_q8_nhwc<uint8_t>;
             }
         }
         else
         {
             if(is_nchw)
             {
                 _func = &NEPoolingLayerKernel::poolingMxN_q8_nchw<uint8_t>;
             }
             else
             {
                 _func = &NEPoolingLayerKernel::poolingMxN_q8_nhwc<uint8_t>;
             }
         }
     }
     else if(data_type == DataType::QASYMM8_SIGNED)
     {
         if(pool_size.x() == 2 && pool_stride_x < 3 && _is_square)
         {
             if(is_nchw)
             {
                 _func = &NEPoolingLayerKernel::pooling2_q8_nchw<int8_t>;
             }
             else
             {
                 _func = &NEPoolingLayerKernel::poolingMxN_q8_nhwc<int8_t>;
             }
         }
         else if(pool_size.x() == 3 && pool_stride_x < 3 && _is_square)
         {
             if(is_nchw)
             {
                 _func = &NEPoolingLayerKernel::pooling3_q8_nchw<int8_t>;
             }
             else
             {
                 _func = &NEPoolingLayerKernel::poolingMxN_q8_nhwc<int8_t>;
             }
         }
         else
         {
             if(is_nchw)
             {
                 _func = &NEPoolingLayerKernel::poolingMxN_q8_nchw<int8_t>;
             }
             else
             {
                 _func = &NEPoolingLayerKernel::poolingMxN_q8_nhwc<int8_t>;
             }
         }
     }
     else if(data_type == DataType::F16)
     {
         if(_is_square)
         {
             switch(pool_size.x())
             {
                 case 2:
                 {
                     if(is_nchw)
                     {
                         _func = &NEPoolingLayerKernel::pooling2_f16_nchw;
                     }
                     else
                     {
                         _func = &NEPoolingLayerKernel::poolingMxN_f16_nhwc;
                     }
                 }
                 break;
                 case 3:
                 {
                     if(is_nchw)
                     {
                         _func = &NEPoolingLayerKernel::pooling3_f16_nchw;
                     }
                     else
                     {
                         _func = &NEPoolingLayerKernel::poolingMxN_f16_nhwc;
                     }
                 }
                 break;
                 default:
                 {
                     if(is_nchw)
                     {
                         _func = &NEPoolingLayerKernel::poolingMxN_f16_nchw;
                     }
                     else
                     {
                         _func = &NEPoolingLayerKernel::poolingMxN_f16_nhwc;
                     }
                     break;
                 }
                 break;
             }
         }
         else
         {
             if(is_nchw)
             {
                 _func = &NEPoolingLayerKernel::poolingMxN_f16_nchw;
             }
             else
             {
                 _func = &NEPoolingLayerKernel::poolingMxN_f16_nhwc;
             }
         }
     }
     else if(data_type == DataType::F32)
     {
         if(_is_square)
         {
             switch(pool_size.x())
             {
                 case 2:
                 {
                     if(is_nchw)
                     {
                         _func = &NEPoolingLayerKernel::pooling2_f32_nchw;
                     }
                     else
                     {
                         _func = &NEPoolingLayerKernel::poolingMxN_f32_nhwc;
                     }
                     break;
                 }
                 case 3:
                 {
                     if(is_nchw)
                     {
                         _func = &NEPoolingLayerKernel::pooling3_f32_nchw;
                     }
                     else
                     {
                         _func = &NEPoolingLayerKernel::poolingMxN_f32_nhwc;
                     }
                     break;
                 }
                 case 7:
                 {
                     if(is_nchw)
                     {
                         _func = &NEPoolingLayerKernel::pooling7_f32_nchw;
                     }
                     else
                     {
                         _func = &NEPoolingLayerKernel::poolingMxN_f32_nhwc;
                     }
                     break;
                 }
                 default:
                 {
                     if(is_nchw)
                     {
                         _func = &NEPoolingLayerKernel::poolingMxN_f32_nchw;
                     }
                     else
                     {
                         _func = &NEPoolingLayerKernel::poolingMxN_f32_nhwc;
                     }
                     break;
                 }
             }
         }
         else
         {
             if(is_nchw)
             {
                 _func = &NEPoolingLayerKernel::poolingMxN_f32_nchw;
             }
             else
             {
                 _func = &NEPoolingLayerKernel::poolingMxN_f32_nhwc;
             }
         }
     }
     // Configure kernel window
     auto win_config = validate_and_configure_window(input->info(), output->info(), (indices) ? indices->info() : nullptr,
                                                     pool_info, _num_elems_processed_per_iteration, _border_size, pooled_w, pooled_h, pool_size.x(), pool_size.y());
     ARM_COMPUTE_ERROR_THROW_ON(win_config.first);
     INEKernel::configure(win_config.second);
 }
References ARM_COMPUTE_ERROR_ON_NULLPTR, ARM_COMPUTE_ERROR_THROW_ON, arm_compute::test::validation::data_layout, PoolingLayerInfo::data_layout, arm_compute::test::validation::data_type, arm_compute::F16, arm_compute::F32, arm_compute::get_data_layout_dimension_index(), Size2D::height, arm_compute::HEIGHT, ITensor::info(), arm_compute::test::validation::input, PoolingLayerInfo::is_global_pooling, arm_compute::NCHW, PoolingLayerInfo::pad_stride_info, PoolingLayerInfo::pool_size, arm_compute::QASYMM8, arm_compute::QASYMM8_SIGNED, arm_compute::scaled_dimensions(), PadStrideInfo::stride(), arm_compute::UNKNOWN, arm_compute::validate_arguments(), Size2D::width, and arm_compute::WIDTH.
Referenced by NEPoolingLayer::configure().
name()
const char* name () const inline override virtual
Name of the kernel.
Returns
Kernel name
Implements ICPPKernel.
Definition at line 37 of file NEPoolingLayerKernel.h.
     {
         return "NEPoolingLayerKernel";
     }
operator=() [1/2]
NEPoolingLayerKernel& operator= (const NEPoolingLayerKernel &) delete
Prevent instances of this class from being copied (As this class contains pointers)
operator=() [2/2]
NEPoolingLayerKernel& operator= (NEPoolingLayerKernel &&) default
Allow instances of this class to be moved.
run()
void run (const Window & window, const ThreadInfo & info) override virtual
Execute the kernel on the passed window.
Warning
If is_parallelisable() returns false then the passed window must be equal to window()
Note
The window has to be a region within the window returned by the window() method
The width of the window has to be a multiple of num_elems_processed_per_iteration().
Parameters
[in] window Region on which to execute the kernel. (Must be a region of the window returned by window())
[in] info Info about executing thread and CPU.
Reimplemented from ICPPKernel.
Definition at line 2210 of file NEPoolingLayerKernel.cpp.
 {
     ARM_COMPUTE_UNUSED(info);
     ARM_COMPUTE_ERROR_ON_UNCONFIGURED_KERNEL(this);
     ARM_COMPUTE_ERROR_ON_INVALID_SUBWINDOW(INEKernel::window(), window);
     ARM_COMPUTE_ERROR_ON(_func == nullptr);
     const unsigned int pool_stride_x   = _pool_info.pad_stride_info.stride().first;
     const unsigned int pool_stride_y   = _pool_info.pad_stride_info.stride().second;
     const unsigned int pool_size       = _pool_info.pool_size.width;
     const bool         exclude_padding = _pool_info.exclude_padding;
     Window window_input(window);
     if(_data_layout == DataLayout::NCHW)
     {
         // Set step for input in x and y direction for the input
         unsigned int window_x_inc = 0;
         switch(_input->info()->data_type())
         {
             case DataType::QASYMM8:
             case DataType::QASYMM8_SIGNED:
             {
                 window_x_inc = pool_stride_x;
                 if((pool_size == 2 || pool_size == 3) && pool_stride_x < 3)
                 {
                     window_x_inc = (pool_stride_x == 2) ? _num_elems_processed_per_iteration * 2 : _num_elems_processed_per_iteration;
                 }
                 break;
             }
             case DataType::F16:
             case DataType::F32:
             {
                 window_x_inc = pool_stride_x;
                 break;
             }
             default:
             {
                 ARM_COMPUTE_ERROR("Not supported");
             }
         }
         window_input.set(Window::DimX, Window::Dimension(window.x().start() * pool_stride_x, window.x().end() * pool_stride_x, window_x_inc));
         window_input.set(Window::DimY, Window::Dimension(window.y().start() * pool_stride_y, window.y().end() * pool_stride_y, pool_stride_y));
     }
     else
     {
         window_input.set(Window::DimX, Window::Dimension(window.x().start(), window.x().end(), _num_elems_processed_per_iteration));
         window_input.set(Window::DimY, Window::Dimension(0, _input->info()->dimension(1), pool_stride_x));
         window_input.set(Window::DimZ, Window::Dimension(0, _input->info()->dimension(2), pool_stride_y));
     }
     // Run function
     (this->*_func)(window_input, window, _pool_info.pool_type, exclude_padding);
 }
References ARM_COMPUTE_ERROR, ARM_COMPUTE_ERROR_ON, ARM_COMPUTE_ERROR_ON_INVALID_SUBWINDOW, ARM_COMPUTE_ERROR_ON_UNCONFIGURED_KERNEL, ARM_COMPUTE_UNUSED, ITensorInfo::data_type(), ITensorInfo::dimension(), Window::DimX, Window::DimY, Window::DimZ, Window::Dimension::end(), PoolingLayerInfo::exclude_padding, arm_compute::F16, arm_compute::F32, ITensor::info(), arm_compute::test::validation::info, arm_compute::NCHW, PoolingLayerInfo::pad_stride_info, PoolingLayerInfo::pool_size, PoolingLayerInfo::pool_type, arm_compute::QASYMM8, arm_compute::QASYMM8_SIGNED, Window::set(), Window::Dimension::start(), PadStrideInfo::stride(), Size2D::width, IKernel::window(), Window::x(), and Window::y().
validate()
Status validate (const ITensorInfo * input, const ITensorInfo * output, const PoolingLayerInfo & pool_info, const ITensorInfo * indices = nullptr) static
Static function to check if given info will lead to a valid configuration of NEPoolingLayerKernel.
Note
F16 are supported for pool sizes 2 and 3 only
Parameters
[in] input Source tensor. Data types supported: QASYMM8/QASYMM8_SIGNED/F16/F32.
[in] output Destination tensor. Data types supported: Same as input.
[in] pool_info Contains pooling operation information described in PoolingLayerInfo.
[in] indices (optional) The indices of the maximal values. Data type supported: U32.
Returns
a status
Definition at line 2170 of file NEPoolingLayerKernel.cpp.
 {
     ARM_COMPUTE_RETURN_ERROR_ON_NULLPTR(input);
     unsigned int pooled_w                          = 0;
     unsigned int pooled_h                          = 0;
     unsigned int num_elems_processed_per_iteration = 0;
     BorderSize   border_size(0);
     const bool   is_global_pooling = pool_info.is_global_pooling;
     unsigned int pool_size_x       = 0;
     unsigned int pool_size_y       = 0;
     // Get data layout
     const auto data_layout = pool_info.data_layout == DataLayout::UNKNOWN ? input->data_layout() : pool_info.data_layout;
     const int  idx_width   = get_data_layout_dimension_index(data_layout, DataLayoutDimension::WIDTH);
     const int  idx_height  = get_data_layout_dimension_index(data_layout, DataLayoutDimension::HEIGHT);
     pool_size_x = is_global_pooling ? input->dimension(idx_width) : pool_info.pool_size.width;
     pool_size_y = is_global_pooling ? input->dimension(idx_height) : pool_info.pool_size.height;
     // Validate pool info before calling scaled_dimensions
     ARM_COMPUTE_RETURN_ON_ERROR(validate_arguments_pool_info(pool_size_x, pool_size_y));
     // Check output dimensions
     std::tie(pooled_w, pooled_h) = scaled_dimensions(input->dimension(idx_width),
                                                      input->dimension(idx_height),
                                                      pool_size_x,
                                                      pool_size_y,
                                                      pool_info.pad_stride_info);
     ARM_COMPUTE_RETURN_ON_ERROR(validate_arguments(input, output, pool_info, pooled_w, pooled_h, indices, Size2D(pool_size_x, pool_size_y)));
     ARM_COMPUTE_RETURN_ON_ERROR(validate_and_configure_window(input->clone().get(), output->clone().get(),
                                                               (indices) ? indices->clone().get() : nullptr, pool_info, num_elems_processed_per_iteration, border_size, pooled_w, pooled_h,
                                                               pool_size_x, pool_size_y)
                                 .first);
     return Status{};
 }
References ARM_COMPUTE_RETURN_ERROR_ON_NULLPTR, ARM_COMPUTE_RETURN_ON_ERROR, NEPoolingLayerKernel::border_size(), ICloneable< T >::clone(), arm_compute::test::validation::data_layout, PoolingLayerInfo::data_layout, arm_compute::get_data_layout_dimension_index(), Size2D::height, arm_compute::HEIGHT, arm_compute::test::validation::input, PoolingLayerInfo::is_global_pooling, num_elems_processed_per_iteration, PoolingLayerInfo::pad_stride_info, PoolingLayerInfo::pool_size, arm_compute::scaled_dimensions(), arm_compute::UNKNOWN, arm_compute::validate_arguments(), Size2D::width, and arm_compute::WIDTH.
Referenced by NEPoolingLayer::validate().
The documentation for this class was generated from the following files:
arm_compute/core/NEON/kernels/NEPoolingLayerKernel.h
src/core/NEON/kernels/NEPoolingLayerKernel.cpp