Compute Library: NEPixelWiseMultiplicationKernel Class Reference
NEPixelWiseMultiplicationKernel Class Reference
Interface for the kernel to perform addition between two tensors.
#include <NEPixelWiseMultiplicationKernel.h>
Public Member Functions
const char * name () const override
Name of the kernel.
NEPixelWiseMultiplicationKernel ()
Default constructor.
NEPixelWiseMultiplicationKernel (const NEPixelWiseMultiplicationKernel &)=delete
Prevent instances of this class from being copied (As this class contains pointers)
NEPixelWiseMultiplicationKernel & operator= (const NEPixelWiseMultiplicationKernel &)=delete
Prevent instances of this class from being copied (As this class contains pointers)
NEPixelWiseMultiplicationKernel (NEPixelWiseMultiplicationKernel &&)=default
Allow instances of this class to be moved.
NEPixelWiseMultiplicationKernel & operator= (NEPixelWiseMultiplicationKernel &&)=default
Allow instances of this class to be moved.
~NEPixelWiseMultiplicationKernel ()=default
Default destructor.
void configure (const ITensor *input1, const ITensor *input2, ITensor *output, float scale, ConvertPolicy overflow_policy, RoundingPolicy rounding_policy)
Initialise the kernel's input, output and border mode.
void run (const Window &window, const ThreadInfo &info) override
Execute the kernel on the passed window.
BorderSize border_size () const override
The size of the border for that kernel.
Public Member Functions inherited from ICPPKernel
virtual ~ICPPKernel ()=default
Default destructor.
virtual void run_nd (const Window &window, const ThreadInfo &info, const Window &thread_locator)
legacy compatibility layer for implemantions which do not support thread_locator In these cases we simply narrow the interface down the legacy version
Public Member Functions inherited from IKernel
IKernel ()
Constructor.
virtual ~IKernel ()=default
Destructor.
virtual bool is_parallelisable () const
Indicates whether or not the kernel is parallelisable.
const Window & window () const
The maximum window the kernel can be executed on.
Static Public Member Functions
static Status validate (const ITensorInfo *input1, const ITensorInfo *input2, const ITensorInfo *output, float scale, ConvertPolicy overflow_policy, RoundingPolicy rounding_policy)
Static function to check if given info will lead to a valid configuration of NEPixelWiseMultiplicationKernel.
Detailed Description
Interface for the kernel to perform addition between two tensors.
Definition at line 35 of file NEPixelWiseMultiplicationKernel.h.
Constructor & Destructor Documentation
NEPixelWiseMultiplicationKernel() [1/3]
NEPixelWiseMultiplicationKernel ()
Default constructor.
Definition at line 677 of file NEPixelWiseMultiplicationKernel.cpp.
     : _func_float(nullptr), _func_int(nullptr), _func_quantized(nullptr), _input1(nullptr), _input2(nullptr), _output(nullptr), _scale{ 0 }, _scale_exponent{ 0 }, _run_optimized_qasymm8(false)
 {
 }
NEPixelWiseMultiplicationKernel() [2/3]
NEPixelWiseMultiplicationKernel (const NEPixelWiseMultiplicationKernel &) delete
Prevent instances of this class from being copied (As this class contains pointers)
NEPixelWiseMultiplicationKernel() [3/3]
NEPixelWiseMultiplicationKernel (NEPixelWiseMultiplicationKernel &&) default
Allow instances of this class to be moved.
~NEPixelWiseMultiplicationKernel()
~NEPixelWiseMultiplicationKernel () default
Default destructor.
Member Function Documentation
border_size()
BorderSize border_size () const override virtual
The size of the border for that kernel.
Returns
The width in number of elements of the border.
Reimplemented from IKernel.
Definition at line 914 of file NEPixelWiseMultiplicationKernel.cpp.
 {
     const unsigned int replicateSize = _output->info()->dimension(0) - std::min(_input1->info()->dimension(0), _input2->info()->dimension(0));
     const unsigned int border        = std::min<unsigned int>(num_elems_processed_per_iteration - 1U, replicateSize);
     return BorderSize{ 0, border, 0, 0 };
 }
References ITensorInfo::dimension(), ITensor::info(), num_elems_processed_per_iteration, and arm_compute::U.
configure()
void configure (const ITensor * input1, const ITensor * input2, ITensor * output, float scale, ConvertPolicy overflow_policy, RoundingPolicy rounding_policy)
Initialise the kernel's input, output and border mode.
Note
For scale equal to 1/255 only round to nearest even (implemented as round half up) is supported. For all other scale values only round to zero (implemented as round towards minus infinity) is supported.
Parameters
[in] input1 An input tensor. Data types supported: U8/QASYMM8/QASYMM8_SIGNED/S16/QSYMM16/F16/F32
[in] input2 An input tensor. Data types supported: U8, QASYMM8 (only if input1 is QASYMM8), QASYMM8_SIGNED (only if input1 is QASYMM8_SIGNED), S16, QSYMM16 (only if input1 is QSYMM16), F16 (only if input1 is F16), F32 (only if input1 is F32).
[out] output Output tensor. Data types supported:
U8, only if both inputs are U8.
QASYMM8, only if both inputs are QASYMM8.
QASYMM8_SIGNED, only if input1 is QASYMM8_SIGNED.
S16.
QSYMM16, only if both inputs are QSYMM16.
S32, only if both inputs are QSYMM16.
F16, only if input1 is F16.
F32, only if both inputs are F32.
[in] scale Scale to apply after multiplication. Scale must be positive and its value must be either 1/255 or 1/2^n where n is between 0 and 15.
[in] overflow_policy Overflow policy. ConvertPolicy cannot be WRAP if datatype is QASYMM8, QASYMM8_SIGNED or QSYMM16.
[in] rounding_policy Rounding policy.
Definition at line 682 of file NEPixelWiseMultiplicationKernel.cpp.
 {
     ARM_COMPUTE_UNUSED(rounding_policy);
     ARM_COMPUTE_ERROR_ON_NULLPTR(input1, input2, output);
     ARM_COMPUTE_ERROR_THROW_ON(validate_arguments(input1->info(), input2->info(), output->info(), scale, overflow_policy, rounding_policy));
     // Configure kernel window
     auto win_config = validate_and_configure_window(input1->info(), input2->info(), output->info());
     ARM_COMPUTE_ERROR_THROW_ON(win_config.first);
     _input1                = input1;
     _input2                = input2;
     _output                = output;
     _scale                 = scale;
     _scale_exponent        = 0;
     _func_quantized        = nullptr;
     _func_int              = nullptr;
     _func_float            = nullptr;
     _run_optimized_qasymm8 = false;
     bool is_scale_255 = false;
     // Check and validate scaling factor
     if(std::abs(scale - scale255_constant) < 0.00001f)
     {
         is_scale_255 = true;
     }
     else
     {
         int exponent = 0;
         std::frexp(scale, &exponent);
         // Store the positive exponent. We know that we compute 1/2^n
         // Additionally we need to subtract 1 to compensate that frexp used a mantissa of 0.5
         _scale_exponent = std::abs(exponent - 1);
     }
     const DataType dt_input1 = input1->info()->data_type();
     const DataType dt_input2 = input2->info()->data_type();
     const DataType dt_output = output->info()->data_type();
     const bool     is_sat    = (overflow_policy == ConvertPolicy::SATURATE);
     if(dt_input1 == DataType::QASYMM8 && dt_input2 == DataType::QASYMM8)
     {
         _run_optimized_qasymm8 = true;
     }
     else if(dt_input1 == DataType::QASYMM8_SIGNED && dt_input2 == DataType::QASYMM8_SIGNED)
     {
         _func_quantized = &mul_saturate_QASYMM8_SIGNED_QASYMM8_SIGNED_QASYMM8_SIGNED_n;
     }
     else if(dt_input1 == DataType::QSYMM16 && dt_input2 == DataType::QSYMM16 && dt_output == DataType::QSYMM16)
     {
         _func_quantized = &mul_saturate_QSYMM16_QSYMM16_QSYMM16_n;
     }
     else if(dt_input1 == DataType::QSYMM16 && dt_input2 == DataType::QSYMM16 && dt_output == DataType::S32)
     {
         _func_int = &mul_QSYMM16_QSYMM16_S32_n;
     }
     else if(DataType::U8 == dt_input1 && DataType::U8 == dt_input2 && DataType::U8 == dt_output)
     {
         if(is_scale_255)
         {
             _func_int = is_sat ? &mul_U8_U8_U8_n<true, true> : &mul_U8_U8_U8_n<true, false>;
         }
         else
         {
             _func_int = is_sat ? &mul_U8_U8_U8_n<false, true> : &mul_U8_U8_U8_n<false, false>;
         }
     }
     else if(DataType::S16 == dt_input1 && DataType::S16 == dt_input2 && DataType::S16 == dt_output)
     {
         if(is_scale_255)
         {
             _func_int = is_sat ? &mul_S16_S16_S16_n<true, true> : &mul_S16_S16_S16_n<true, false>;
         }
         else
         {
             _func_int = is_sat ? &mul_S16_S16_S16_n<false, true> : &mul_S16_S16_S16_n<false, false>;
         }
     }
     else if(DataType::S16 == dt_input1 && DataType::U8 == dt_input2 && DataType::S16 == dt_output)
     {
         if(is_scale_255)
         {
             _func_int = is_sat ? &mul_S16_U8_S16_n<true, true> : &mul_S16_U8_S16_n<true, false>;
         }
         else
         {
             _func_int = is_sat ? &mul_S16_U8_S16_n<false, true> : &mul_S16_U8_S16_n<false, false>;
         }
     }
     else if(DataType::U8 == dt_input1 && DataType::S16 == dt_input2 && DataType::S16 == dt_output)
     {
         if(is_scale_255)
         {
             _func_int = is_sat ? &mul_U8_S16_S16_n<true, true> : &mul_U8_S16_S16_n<true, false>;
         }
         else
         {
             _func_int = is_sat ? &mul_U8_S16_S16_n<false, true> : &mul_U8_S16_S16_n<false, false>;
         }
     }
     else if(DataType::U8 == dt_input1 && DataType::U8 == dt_input2 && DataType::S16 == dt_output)
     {
         if(is_scale_255)
         {
             _func_int = is_sat ? &mul_U8_U8_S16_n<true, true> : &mul_U8_U8_S16_n<true, false>;
         }
         else
         {
             _func_int = is_sat ? &mul_U8_U8_S16_n<false, true> : &mul_U8_U8_S16_n<false, false>;
         }
     }
     else if(DataType::F16 == dt_input1 && DataType::F16 == dt_input2 && DataType::F16 == dt_output)
     {
         _func_float = &mul_F16_F16_F16_n;
         _func_int   = nullptr;
     }
     else if(DataType::F32 == dt_input1 && DataType::F32 == dt_input2 && DataType::F32 == dt_output)
     {
         _func_float = &mul_F32_F32_F32_n;
         _func_int   = nullptr;
     }
     else
     {
         ARM_COMPUTE_ERROR("You called with the wrong img formats");
     }
     INEKernel::configure(win_config.second);
 }
References ARM_COMPUTE_ERROR, ARM_COMPUTE_ERROR_ON_NULLPTR, ARM_COMPUTE_ERROR_THROW_ON, ARM_COMPUTE_UNUSED, ITensorInfo::data_type(), arm_compute::F16, arm_compute::F32, ITensor::info(), arm_compute::QASYMM8, arm_compute::QASYMM8_SIGNED, arm_compute::QSYMM16, arm_compute::S16, arm_compute::S32, arm_compute::SATURATE, arm_compute::test::validation::reference::scale(), arm_compute::U8, and arm_compute::validate_arguments().
Referenced by NENormalizationLayer::configure(), and NELSTMLayer::configure().
name()
const char* name () const inline override virtual
Name of the kernel.
Returns
Kernel name
Implements ICPPKernel.
Definition at line 38 of file NEPixelWiseMultiplicationKernel.h.
     {
         return "NEPixelWiseMultiplicationKernel";
     }
operator=() [1/2]
NEPixelWiseMultiplicationKernel& operator= (const NEPixelWiseMultiplicationKernel &) delete
Prevent instances of this class from being copied (As this class contains pointers)
operator=() [2/2]
NEPixelWiseMultiplicationKernel& operator= (NEPixelWiseMultiplicationKernel &&) default
Allow instances of this class to be moved.
run()
void run (const Window & window, const ThreadInfo & info) override virtual
Execute the kernel on the passed window.
Warning
If is_parallelisable() returns false then the passed window must be equal to window()
Note
The window has to be a region within the window returned by the window() method
The width of the window has to be a multiple of num_elems_processed_per_iteration().
Parameters
[in] window Region on which to execute the kernel. (Must be a region of the window returned by window())
[in] info Info about executing thread and CPU.
Reimplemented from ICPPKernel.
Definition at line 824 of file NEPixelWiseMultiplicationKernel.cpp.
 {
     ARM_COMPUTE_UNUSED(info);
     ARM_COMPUTE_ERROR_ON_UNCONFIGURED_KERNEL(this);
     ARM_COMPUTE_ERROR_ON_INVALID_SUBWINDOW(INEKernel::window(), window);
     const TensorShape &in_shape1 = _input1->info()->tensor_shape();
     const TensorShape &in_shape2 = _input2->info()->tensor_shape();
     const TensorShape &out_shape = _output->info()->tensor_shape();
     bool can_collapse = true;
     if(std::min(in_shape1.total_size(), in_shape2.total_size()) > 1)
     {
         can_collapse = (std::min(in_shape1.num_dimensions(), in_shape2.num_dimensions()) > Window::DimZ);
         for(size_t d = Window::DimZ; can_collapse && (d < out_shape.num_dimensions()); ++d)
         {
             can_collapse = (in_shape1[d] == in_shape2[d]);
         }
     }
     bool   has_collapsed = false;
     Window collapsed     = can_collapse ? window.collapse_if_possible(INEKernel::window(), Window::DimZ, &has_collapsed) : window;
     const TensorShape &in_shape1_collapsed = has_collapsed ? in_shape1.collapsed_from(Window::DimZ) : in_shape1;
     const TensorShape &in_shape2_collapsed = has_collapsed ? in_shape2.collapsed_from(Window::DimZ) : in_shape2;
     Window slice        = collapsed.first_slice_window_3D();
     Window slice_input1 = slice.broadcast_if_dimension_le_one(in_shape1_collapsed);
     Window slice_input2 = slice.broadcast_if_dimension_le_one(in_shape2_collapsed);
     Iterator input1(_input1, slice_input1);
     Iterator input2(_input2, slice_input2);
     Iterator output(_output, slice);
     if((_run_optimized_qasymm8) || (_func_quantized != nullptr))
     {
         if(_run_optimized_qasymm8)
         {
             const int32x4_t   input1_voffset = vdupq_n_s32(_input1->info()->quantization_info().uniform().offset);
             const float32x4_t input1_vscale  = vdupq_n_f32(_input1->info()->quantization_info().uniform().scale);
             const int32x4_t   input2_voffset = vdupq_n_s32(_input2->info()->quantization_info().uniform().offset);
             const float32x4_t input2_vscale  = vdupq_n_f32(_input2->info()->quantization_info().uniform().scale);
             const float32x4_t output_voffset = vdupq_n_f32(static_cast<float>(_output->info()->quantization_info().uniform().offset));
             const float       output_scale   = _output->info()->quantization_info().uniform().scale;
             const float32x4_t vinvscale      = vdupq_n_f32(1.f / (output_scale / _scale));
             execute_window_loop(collapsed, [&](const Coordinates &)
             {
                 mul_saturate_QASYMM8_QASYMM8_QASYMM8_n_opt(input1.ptr(), input2.ptr(), output.ptr(),
                                                            input1_vscale, input1_voffset, input2_vscale, input2_voffset, output_voffset, vinvscale);
                 ARM_COMPUTE_UNUSED(collapsed.slide_window_slice_3D(slice_input1));
                 ARM_COMPUTE_UNUSED(collapsed.slide_window_slice_3D(slice_input2));
             },
             input1, input2, output);
         }
         else
         {
             execute_window_loop(collapsed, [&](const Coordinates &)
             {
                 (*_func_quantized)(input1.ptr(), input2.ptr(), output.ptr(), _scale,
                                    _input1->info()->quantization_info().uniform(), _input2->info()->quantization_info().uniform(), _output->info()->quantization_info().uniform());
                 ARM_COMPUTE_UNUSED(collapsed.slide_window_slice_3D(slice_input1));
                 ARM_COMPUTE_UNUSED(collapsed.slide_window_slice_3D(slice_input2));
             },
             input1, input2, output);
         }
     }
     else if(_func_int != nullptr)
     {
         execute_window_loop(collapsed, [&](const Coordinates &)
         {
             (*_func_int)(input1.ptr(), input2.ptr(), output.ptr(), _scale_exponent);
             ARM_COMPUTE_UNUSED(collapsed.slide_window_slice_3D(slice_input1));
             ARM_COMPUTE_UNUSED(collapsed.slide_window_slice_3D(slice_input2));
         },
         input1, input2, output);
     }
     else
     {
         ARM_COMPUTE_ERROR_ON(_func_float == nullptr);
         execute_window_loop(collapsed, [&](const Coordinates &)
         {
             (*_func_float)(input1.ptr(), input2.ptr(), output.ptr(), _scale);
             ARM_COMPUTE_UNUSED(collapsed.slide_window_slice_3D(slice_input1));
             ARM_COMPUTE_UNUSED(collapsed.slide_window_slice_3D(slice_input2));
         },
         input1, input2, output);
     }
 }
References ARM_COMPUTE_ERROR_ON, ARM_COMPUTE_ERROR_ON_INVALID_SUBWINDOW, ARM_COMPUTE_ERROR_ON_UNCONFIGURED_KERNEL, ARM_COMPUTE_UNUSED, Window::collapse_if_possible(), TensorShape::collapsed_from(), Window::DimZ, arm_compute::execute_window_loop(), Window::first_slice_window_3D(), ITensor::info(), arm_compute::test::validation::info, Dimensions< T >::num_dimensions(), UniformQuantizationInfo::offset, Iterator::ptr(), ITensorInfo::quantization_info(), UniformQuantizationInfo::scale, arm_compute::test::validation::reference::slice(), Window::slide_window_slice_3D(), ITensorInfo::tensor_shape(), TensorShape::total_size(), QuantizationInfo::uniform(), and IKernel::window().
validate()
Status validate (const ITensorInfo * input1, const ITensorInfo * input2, const ITensorInfo * output, float scale, ConvertPolicy overflow_policy, RoundingPolicy rounding_policy) static
Static function to check if given info will lead to a valid configuration of NEPixelWiseMultiplicationKernel.
Note
For scale equal to 1/255 only round to nearest even (implemented as round half up) is supported. For all other scale values only round to zero (implemented as round towards minus infinity) is supported.
Parameters
[in] input1 An input tensor info. Data types supported: U8/QASYMM8/QASYMM8_SIGNED/QSYMM16/S16/F16/F32
[in] input2 An input tensor info. Data types supported: U8, QASYMM8 (only if input1 is QASYMM8), QASYMM8_SIGNED (only if input1 is QASYMM8_SIGNED), S16, QSYMM16 (only if input1 is QSYMM16), F16 (only if input1 is F16), F32 (only if input1 is F32).
[in] output Output tensor info. Data types supported:
U8, only if both inputs are U8.
QASYMM8, only if both inputs are QASYMM8.
QASYMM8_SIGNED, only if input1 is QASYMM8_SIGNED.
S16.
QSYMM16, only if both inputs are QSYMM16.
S32, only if both inputs are QSYMM16.
F16, only if input1 is F16.
F32, only if both inputs are F32.
[in] scale Scale to apply after multiplication. Scale must be positive and its value must be either 1/255 or 1/2^n where n is between 0 and 15.
[in] overflow_policy Overflow policy. ConvertPolicy cannot be WRAP if datatype is QASYMM8, QASYMM8_SIGNED or QSYMM16.
[in] rounding_policy Rounding policy.
Returns
a status
Definition at line 814 of file NEPixelWiseMultiplicationKernel.cpp.
 {
     ARM_COMPUTE_ERROR_ON_NULLPTR(input1, input2, output);
     ARM_COMPUTE_RETURN_ON_ERROR(validate_arguments(input1, input2, output, scale, overflow_policy, rounding_policy));
     ARM_COMPUTE_RETURN_ON_ERROR(validate_and_configure_window(input1->clone().get(), input2->clone().get(), output->clone().get()).first);
     return Status{};
 }
References ARM_COMPUTE_ERROR_ON_NULLPTR, ARM_COMPUTE_RETURN_ON_ERROR, ICloneable< T >::clone(), arm_compute::test::validation::reference::scale(), and arm_compute::validate_arguments().
Referenced by NENormalizationLayer::validate(), NEPixelWiseMultiplication::validate(), NELSTMLayer::validate(), and NEQLSTMLayer::validate().
The documentation for this class was generated from the following files:
arm_compute/core/NEON/kernels/NEPixelWiseMultiplicationKernel.h
src/core/NEON/kernels/NEPixelWiseMultiplicationKernel.cpp