Compute Library: CLLogits1DNormKernel Class Reference
CLLogits1DNormKernel Class Reference
Interface for calculating the final step of the Softmax Layer where each logit value is multiplied by the inverse of the sum of the logits.
#include <CLSoftmaxLayerKernel.h>
Public Member Functions
CLLogits1DNormKernel ()
Default constructor.
CLLogits1DNormKernel (const CLLogits1DNormKernel &)=delete
Prevent instances of this class from being copied (As this class contains pointers)
CLLogits1DNormKernel & operator= (const CLLogits1DNormKernel &)=delete
Prevent instances of this class from being copied (As this class contains pointers)
CLLogits1DNormKernel (CLLogits1DNormKernel &&)=default
Allow instances of this class to be moved.
CLLogits1DNormKernel & operator= (CLLogits1DNormKernel &&)=default
Allow instances of this class to be moved.
void configure (const ICLTensor *input, const ICLTensor *sum, ICLTensor *output, const SoftmaxKernelInfo &info)
Set the input and output tensors.
void configure (const CLCompileContext &compile_context, const ICLTensor *input, const ICLTensor *sum, ICLTensor *output, const SoftmaxKernelInfo &info)
Set the input and output tensors.
void run (const Window &window, cl::CommandQueue &queue) override
Enqueue the OpenCL kernel to process the given window on the passed OpenCL command queue.
Public Member Functions inherited from ICLKernel
ICLKernel ()
Constructor.
cl::Kernel & kernel ()
Returns a reference to the OpenCL kernel of this object.
template<typename T >
void add_1D_array_argument (unsigned int &idx, const ICLArray< T > *array, const Strides &strides, unsigned int num_dimensions, const Window &window)
Add the passed 1D array's parameters to the object's kernel's arguments starting from the index idx.
void add_1D_tensor_argument (unsigned int &idx, const ICLTensor *tensor, const Window &window)
Add the passed 1D tensor's parameters to the object's kernel's arguments starting from the index idx.
void add_1D_tensor_argument_if (bool cond, unsigned int &idx, const ICLTensor *tensor, const Window &window)
Add the passed 1D tensor's parameters to the object's kernel's arguments starting from the index idx if the condition is true.
void add_2D_tensor_argument (unsigned int &idx, const ICLTensor *tensor, const Window &window)
Add the passed 2D tensor's parameters to the object's kernel's arguments starting from the index idx.
void add_2D_tensor_argument_if (bool cond, unsigned int &idx, const ICLTensor *tensor, const Window &window)
Add the passed 2D tensor's parameters to the object's kernel's arguments starting from the index idx if the condition is true.
void add_3D_tensor_argument (unsigned int &idx, const ICLTensor *tensor, const Window &window)
Add the passed 3D tensor's parameters to the object's kernel's arguments starting from the index idx.
void add_4D_tensor_argument (unsigned int &idx, const ICLTensor *tensor, const Window &window)
Add the passed 4D tensor's parameters to the object's kernel's arguments starting from the index idx.
template<typename T >
void add_argument (unsigned int &idx, T value)
Add the passed parameters to the object's kernel's arguments starting from the index idx.
void set_lws_hint (const cl::NDRange &lws_hint)
Set the Local-Workgroup-Size hint.
cl::NDRange lws_hint () const
Return the Local-Workgroup-Size hint.
const std::string & config_id () const
Get the configuration ID.
void set_target (GPUTarget target)
Set the targeted GPU architecture.
void set_target (cl::Device &device)
Set the targeted GPU architecture according to the CL device.
GPUTarget get_target () const
Get the targeted GPU architecture.
size_t get_max_workgroup_size ()
Get the maximum workgroup size for the device the CLKernelLibrary uses.
template<typename T , unsigned int dimension_size>
void add_array_argument (unsigned &idx, const ICLArray< T > *array, const Strides &strides, unsigned int num_dimensions, const Window &window)
Add the passed array's parameters to the object's kernel's arguments starting from the index idx.
template<unsigned int dimension_size>
void add_tensor_argument (unsigned &idx, const ICLTensor *tensor, const Window &window)
Public Member Functions inherited from IKernel
IKernel ()
Constructor.
virtual ~IKernel ()=default
Destructor.
virtual bool is_parallelisable () const
Indicates whether or not the kernel is parallelisable.
virtual BorderSize border_size () const
The size of the border for that kernel.
const Window & window () const
The maximum window the kernel can be executed on.
Static Public Member Functions
static Status validate (const ITensorInfo *input, const ITensorInfo *sum, const ITensorInfo *output, const SoftmaxKernelInfo &info)
Static function to check if given info will lead to a valid configuration of CLLogits1DNormKernel.
Static Public Member Functions inherited from ICLKernel
static constexpr unsigned int num_arguments_per_1D_array ()
Returns the number of arguments enqueued per 1D array object.
static constexpr unsigned int num_arguments_per_1D_tensor ()
Returns the number of arguments enqueued per 1D tensor object.
static constexpr unsigned int num_arguments_per_2D_tensor ()
Returns the number of arguments enqueued per 2D tensor object.
static constexpr unsigned int num_arguments_per_3D_tensor ()
Returns the number of arguments enqueued per 3D tensor object.
static constexpr unsigned int num_arguments_per_4D_tensor ()
Returns the number of arguments enqueued per 4D tensor object.
static cl::NDRange gws_from_window (const Window &window)
Get the global work size given an execution window.
Detailed Description
Interface for calculating the final step of the Softmax Layer where each logit value is multiplied by the inverse of the sum of the logits.
Definition at line 191 of file CLSoftmaxLayerKernel.h.
Constructor & Destructor Documentation
CLLogits1DNormKernel() [1/3]
CLLogits1DNormKernel ()
Default constructor.
Definition at line 344 of file CLSoftmaxLayerKernel.cpp.
     : _input(nullptr), _sum(nullptr), _output(nullptr)
 {
 }
CLLogits1DNormKernel() [2/3]
CLLogits1DNormKernel (const CLLogits1DNormKernel &) delete
Prevent instances of this class from being copied (As this class contains pointers)
CLLogits1DNormKernel() [3/3]
CLLogits1DNormKernel (CLLogits1DNormKernel &&) default
Allow instances of this class to be moved.
Member Function Documentation
configure() [1/2]
void configure (const ICLTensor * input, const ICLTensor * sum, ICLTensor * output, const SoftmaxKernelInfo & info)
Set the input and output tensors.
Parameters
[in] input Source tensor. Data types supported: S32/F16/F32
[in] sum Sum tensor. Dimensions should be dim(input)-1. Data types supported: same as input
[out] output Destination tensor. Data types supported: QASYMM8 for S32 input, or same as input
[in] info Contains information consumed by kernels for softmax described in SoftmaxKernelInfo.
Definition at line 349 of file CLSoftmaxLayerKernel.cpp.
 {
     configure(CLKernelLibrary::get().get_compile_context(), input, sum, output, info);
 }
References CLKernelLibrary::get(), arm_compute::test::validation::info, arm_compute::test::validation::input, and sum().
configure() [2/2]
void configure (const CLCompileContext & compile_context, const ICLTensor * input, const ICLTensor * sum, ICLTensor * output, const SoftmaxKernelInfo & info)
Set the input and output tensors.
Parameters
[in] compile_context The compile context to be used.
[in] input Source tensor. Data types supported: S32/F16/F32
[in] sum Sum tensor. Dimensions should be dim(input)-1. Data types supported: same as input
[out] output Destination tensor. Data types supported: QASYMM8 for S32 input, or same as input
[in] info Contains information consumed by kernels for softmax described in SoftmaxKernelInfo.
Definition at line 354 of file CLSoftmaxLayerKernel.cpp.
 {
     ARM_COMPUTE_ERROR_ON_NULLPTR(input, sum, output);
     // Note: output should always have a scale of 1/256 and offset 0
     const bool                    is_quantized_asymmetric   = is_data_type_quantized_asymmetric(info.input_data_type);
     const DataType                output_data_type          = info.input_data_type;
     const QuantizationInfo        allowed_quantization_info = get_softmax_output_quantization_info(info.input_data_type, info.is_log);
     const UniformQuantizationInfo qinfo                     = input->info()->quantization_info().uniform();
     // Output auto initialization if not yet initialized
     auto_init_if_empty(*output->info(),
                        input->info()->clone()->set_data_type(output_data_type).set_quantization_info(allowed_quantization_info));
     // Perform validation step
     ARM_COMPUTE_ERROR_THROW_ON(validate_arguments_1DNorm(input->info(), sum->info(), output->info(), info));
     _input  = input;
     _sum    = sum;
     _output = output;
     const auto is_signed_qasymm8 = is_data_type_quantized_asymmetric_signed(info.input_data_type);
     const int  min_value         = is_signed_qasymm8 ? CL_SCHAR_MIN : 0;
     // Set build options
     CLBuildOptions build_opts;
     build_opts.add_option("-DDATA_TYPE=" + get_cl_type_from_data_type(info.input_data_type));
     build_opts.add_option("-DMIN_VALUE=" + support::cpp11::to_string(min_value));
     build_opts.add_option_if(is_data_type_quantized_asymmetric_signed(info.input_data_type), "-DQASYMM8_SIGNED");
     build_opts.add_options_if(is_quantized_asymmetric,
                               prepare_quantized_softmax_build_options(qinfo.scale, info.beta).options());
     build_opts.add_option_if(info.is_log, "-DLOG_SOFTMAX");
     // Create kernel
     std::string kernel_name = is_quantized_asymmetric ? "softmax_layer_norm_quantized" : "softmax_layer_norm";
     _kernel                 = create_kernel(compile_context, kernel_name, build_opts.options());
     // Configure window
     auto win_config = validate_and_configure_window_1DNorm(input->info(), output->info(), sum->info(), info);
     ARM_COMPUTE_ERROR_THROW_ON(win_config.first);
     ICLKernel::configure_internal(win_config.second);
 }
References CLBuildOptions::add_option(), CLBuildOptions::add_option_if(), CLBuildOptions::add_options_if(), ARM_COMPUTE_ERROR_ON_NULLPTR, ARM_COMPUTE_ERROR_THROW_ON, arm_compute::auto_init_if_empty(), arm_compute::create_kernel(), arm_compute::get_cl_type_from_data_type(), arm_compute::get_softmax_output_quantization_info(), ITensor::info(), arm_compute::test::validation::info, arm_compute::test::validation::input, arm_compute::is_data_type_quantized_asymmetric(), arm_compute::is_data_type_quantized_asymmetric_signed(), kernel_name, CLBuildOptions::options(), arm_compute::test::validation::output_data_type, arm_compute::test::validation::qinfo, QuantizationInfo::scale(), sum(), and arm_compute::support::cpp11::to_string().
operator=() [1/2]
CLLogits1DNormKernel& operator= (const CLLogits1DNormKernel &) delete
Prevent instances of this class from being copied (As this class contains pointers)
operator=() [2/2]
CLLogits1DNormKernel& operator= (CLLogits1DNormKernel &&) default
Allow instances of this class to be moved.
run()
void run (const Window & window, cl::CommandQueue & queue) override virtual
Enqueue the OpenCL kernel to process the given window on the passed OpenCL command queue.
Note
The queue is not flushed by this method, and therefore the kernel will not have been executed by the time this method returns.
Parameters
[in] window Region on which to execute the kernel. (Must be a valid region of the window returned by window()).
[in,out] queue Command queue on which to enqueue the kernel.
Implements ICLKernel.
Definition at line 405 of file CLSoftmaxLayerKernel.cpp.
 {
     ARM_COMPUTE_ERROR_ON_UNCONFIGURED_KERNEL(this);
     ARM_COMPUTE_ERROR_ON_INVALID_SUBWINDOW(IKernel::window(), window);
     Window window_collapsed = window.collapse_if_possible(ICLKernel::window(), Window::DimZ);
     Window slice            = window_collapsed.first_slice_window_3D();
     do
     {
         Window sum_slice = slice;
         sum_slice.set(Window::DimX, Window::Dimension(0, 1, 1));
         unsigned int idx = 0;
         // Set inputs
         add_3D_tensor_argument(idx, _input, slice);
         add_3D_tensor_argument(idx, _sum, sum_slice);
         add_3D_tensor_argument(idx, _output, slice);
         enqueue(queue, *this, slice, lws_hint());
     }
     while(window_collapsed.slide_window_slice_3D(slice));
 }
References ICLKernel::add_3D_tensor_argument(), ARM_COMPUTE_ERROR_ON_INVALID_SUBWINDOW, ARM_COMPUTE_ERROR_ON_UNCONFIGURED_KERNEL, Window::collapse_if_possible(), Window::DimX, Window::DimZ, arm_compute::enqueue(), Window::first_slice_window_3D(), ICLKernel::lws_hint(), Window::set(), arm_compute::test::validation::reference::slice(), Window::slide_window_slice_3D(), and IKernel::window().
validate()
Status validate (const ITensorInfo * input, const ITensorInfo * sum, const ITensorInfo * output, const SoftmaxKernelInfo & info) static
Static function to check if given info will lead to a valid configuration of CLLogits1DNormKernel.
Parameters
[in] input Source tensor. Data types supported: S32/F16/F32
[in] sum Sum tensor. Dimensions should be dim(input)-1. Data types supported: same as input
[in] output Destination tensor. Data types supported: QASYMM8 for S32 input, or same as input
[in] info Contains information consumed by kernels for softmax described in SoftmaxKernelInfo.
Returns
a status
Definition at line 397 of file CLSoftmaxLayerKernel.cpp.
 {
     ARM_COMPUTE_RETURN_ON_ERROR(validate_arguments_1DNorm(input, sum, output, info));
     ARM_COMPUTE_RETURN_ON_ERROR(validate_and_configure_window_1DNorm(input->clone().get(), output->clone().get(), sum->clone().get(), info).first);
     return Status{};
 }
References ARM_COMPUTE_RETURN_ON_ERROR, ICloneable< T >::clone(), arm_compute::test::validation::info, arm_compute::test::validation::input, and sum().
Referenced by CLSoftmaxLayerGeneric< IS_LOG >::validate().
The documentation for this class was generated from the following files:
arm_compute/core/CL/kernels/CLSoftmaxLayerKernel.h
src/core/CL/kernels/CLSoftmaxLayerKernel.cpp