Compute Library: INESimpleFunctionNoBorder Class Reference
INESimpleFunctionNoBorder Class Reference
Basic interface for functions which have a single NEON kernel and no border.
#include <INESimpleFunctionNoBorder.h>
Public Member Functions
INESimpleFunctionNoBorder (IRuntimeContext *ctx=nullptr)
Constructor.
INESimpleFunctionNoBorder (const INESimpleFunctionNoBorder &)=delete
Prevent instances of this class from being copied (As this class contains pointers)
INESimpleFunctionNoBorder (INESimpleFunctionNoBorder &&)=default
Default move constructor.
INESimpleFunctionNoBorder & operator= (const INESimpleFunctionNoBorder &)=delete
Prevent instances of this class from being copied (As this class contains pointers)
INESimpleFunctionNoBorder & operator= (INESimpleFunctionNoBorder &&)=default
Default move assignment operator.
void run () override final
Run the kernels contained in the function.
Public Member Functions inherited from IFunction
virtual ~IFunction ()=default
Destructor.
virtual void prepare ()
Prepare the function for executing.
Detailed Description
Basic interface for functions which have a single NEON kernel and no border.
Definition at line 36 of file INESimpleFunctionNoBorder.h.
Constructor & Destructor Documentation
INESimpleFunctionNoBorder() [1/3]
INESimpleFunctionNoBorder (IRuntimeContext * ctx = nullptr)
Constructor.
Parameters
[in] ctx Runtime context to be used by the function
Definition at line 31 of file INESimpleFunctionNoBorder.cpp.
     : _kernel(),
       _ctx(ctx)
 {
 }
INESimpleFunctionNoBorder() [2/3]
INESimpleFunctionNoBorder (const INESimpleFunctionNoBorder &) delete
Prevent instances of this class from being copied (As this class contains pointers)
INESimpleFunctionNoBorder() [3/3]
INESimpleFunctionNoBorder (INESimpleFunctionNoBorder &&) default
Default move constructor.
Member Function Documentation
operator=() [1/2]
INESimpleFunctionNoBorder& operator= (const INESimpleFunctionNoBorder &) delete
Prevent instances of this class from being copied (As this class contains pointers)
operator=() [2/2]
INESimpleFunctionNoBorder& operator= (INESimpleFunctionNoBorder &&) default
Default move assignment operator.
run()
void run () final override virtual
Run the kernels contained in the function.
For NEON kernels:
Multi-threading is used for the kernels which are parallelisable.
By default std::thread::hardware_concurrency() threads are used.
Note
CPPScheduler::set_num_threads() can be used to manually set the number of threads
For OpenCL kernels:
All the kernels are enqueued on the queue associated with CLScheduler.
The queue is then flushed.
Note
The function will not block until the kernels are executed. It is the user's responsibility to wait.
Will call prepare() on first run if hasn't been done
Implements IFunction.
Definition at line 37 of file INESimpleFunctionNoBorder.cpp.
 {
     schedule_kernel_on_ctx(_ctx, _kernel.get(), Window::DimY);
 }
References Window::DimY, and arm_compute::schedule_kernel_on_ctx().
Referenced by main(), NEFFTConvolutionLayer::prepare(), NEDeconvolutionLayer::prepare(), NELSTMLayerQuantized::prepare(), NEFullyConnectedLayer::prepare(), NEReduceMean::run(), NEFullyConnectedLayerReshapeWeightsManaged::run(), NELaplacianPyramid::run(), NEInstanceNormalizationLayer::run(), NEWinogradConvolutionLayer::run(), NELaplacianReconstruct::run(), NEDetectionPostProcessLayer::run(), NEDirectConvolutionLayer::run(), NEGEMM::run(), NEFFTConvolutionLayer::run(), NEGEMMLowpMatrixMultiplyCore::run(), NELSTMLayerQuantized::run(), NELSTMLayer::run(), NEGEMMConvolutionLayer::run(), and arm_compute::test::validation::TEST_CASE().
The documentation for this class was generated from the following files:
arm_compute/runtime/NEON/INESimpleFunctionNoBorder.h
src/runtime/NEON/INESimpleFunctionNoBorder.cpp