Compute Library: CLConvolutionLayerReshapeWeightsTransform Class Reference
CLConvolutionLayerReshapeWeightsTransform Class Reference
Basic function to manage the reshape weights generated from CLConvolutionLayerReshapeWeights.
#include <CLGEMMConvolutionLayer.h>
Public Member Functions
void configure (const ICLTensor *input, const ICLTensor *biases, unsigned int num_groups)
Configures the CLConvolutionLayerReshapeWeights function.
void configure (const CLCompileContext &compile_context, const ICLTensor *input, const ICLTensor *biases, unsigned int num_groups)
Configures the CLConvolutionLayerReshapeWeights function.
void run () override
Run the transformation function.
ICLTensor * get_weights () override
Get a pointer to the transformed weights.
void release () override
Release transformed weights memory.
uint32_t uid () override
Function that returns a unique id of the reshape function.
Public Member Functions inherited from ITransformWeights
ITransformWeights ()=default
Default Constructor.
virtual ~ITransformWeights ()=default
Default Destructor.
ITransformWeights (const ITransformWeights &)=delete
Prevent instances of this class to be copy constructed.
ITransformWeights & operator= (const ITransformWeights &)=delete
Prevent instances of this class to be copied.
ITransformWeights (ITransformWeights &&other)
Allow instances of this class to be move constructed.
ITransformWeights & operator= (ITransformWeights &&other)
Allow instances of this class to be moved.
void increase_refcount ()
Increase the object's refcount.
int32_t decrease_refcount ()
Decrease the object's refcount and return the updated value.
bool is_reshape_run ()
Function that returns a flag on whether the weights are reshaped or not.
Detailed Description
Basic function to manage the reshape weights generated from CLConvolutionLayerReshapeWeights.
Definition at line 96 of file CLGEMMConvolutionLayer.h.
Member Function Documentation
configure() [1/2]
void configure (const ICLTensor * input, const ICLTensor * biases, unsigned int num_groups) inline
Configures the CLConvolutionLayerReshapeWeights function.
Parameters
[in] input Input tensor. Data type supported: QASYMM8/QASYMM8_SIGNED/F16/F32.
[in] biases Biases tensor. Data type supported: Same as input.
[in] num_groups Number of groups when performing a grouped convolution.
Definition at line 105 of file CLGEMMConvolutionLayer.h.
     {
         configure(CLKernelLibrary::get().get_compile_context(), input, biases, num_groups);
     }
References CLKernelLibrary::get(), arm_compute::test::validation::input, and arm_compute::test::validation::num_groups.
Referenced by CLGEMMConvolutionLayer::configure().
configure() [2/2]
void configure (const CLCompileContext & compile_context, const ICLTensor * input, const ICLTensor * biases, unsigned int num_groups) inline
Configures the CLConvolutionLayerReshapeWeights function.
Parameters
[in] compile_context The compile context to be used.
[in] input Input tensor. Data type supported: QASYMM8/QASYMM8_SIGNED/F16/F32.
[in] biases Biases tensor. Data type supported: Same as input.
[in] num_groups Number of groups when performing a grouped convolution.
Definition at line 116 of file CLGEMMConvolutionLayer.h.
     {
         _bias_bit   = (biases != nullptr) ? 1 : 0;
         _num_groups = num_groups;
         _func.configure(compile_context, input, biases, &_output, num_groups);
     }
References CLConvolutionLayerReshapeWeights::configure(), arm_compute::test::validation::input, and arm_compute::test::validation::num_groups.
get_weights()
ICLTensor* get_weights () inline override virtual
Get a pointer to the transformed weights.
Returns
The pointer to the transformed ITensor weights
Implements ITransformWeights.
Definition at line 132 of file CLGEMMConvolutionLayer.h.
     {
         return &_output;
     }
release()
void release () inline override virtual
Release transformed weights memory.
Implements ITransformWeights.
Definition at line 138 of file CLGEMMConvolutionLayer.h.
     {
         _output.allocator()->free();
     }
References CLTensor::allocator(), and CLTensorAllocator::free().
run()
void run () inline override virtual
Run the transformation function.
Implements ITransformWeights.
Definition at line 124 of file CLGEMMConvolutionLayer.h.
     {
         _output.allocator()->allocate();
         _func.run();
         _reshape_run = true;
     }
References CLTensorAllocator::allocate(), CLTensor::allocator(), and CLConvolutionLayerReshapeWeights::run().
uid()
uint32_t uid () inline override virtual
Function that returns a unique id of the reshape function.
Returns
The computed unique id
Implements ITransformWeights.
Definition at line 144 of file CLGEMMConvolutionLayer.h.
     {
         return ((0x9) | (_bias_bit << 7) | (_num_groups << 8));
     }
The documentation for this class was generated from the following file:
arm_compute/runtime/CL/functions/CLGEMMConvolutionLayer.h