Compute Library: NEDepthwiseConvolutionLayerNativeKernel Class Reference
NEDepthwiseConvolutionLayerNativeKernel Class Reference
Interface for the kernel to run a depthwise convolution native on a tensor.
#include <NEDepthwiseConvolutionLayerNativeKernel.h>
Public Member Functions
const char * name () const override
Name of the kernel.
NEDepthwiseConvolutionLayerNativeKernel ()
Default constructor.
NEDepthwiseConvolutionLayerNativeKernel (const NEDepthwiseConvolutionLayerNativeKernel &)=delete
Prevent instances of this class from being copied (As this class contains pointers)
NEDepthwiseConvolutionLayerNativeKernel & operator= (const NEDepthwiseConvolutionLayerNativeKernel &)=delete
Prevent instances of this class from being copied (As this class contains pointers)
NEDepthwiseConvolutionLayerNativeKernel (NEDepthwiseConvolutionLayerNativeKernel &&)=default
Default Move Constructor.
NEDepthwiseConvolutionLayerNativeKernel & operator= (NEDepthwiseConvolutionLayerNativeKernel &&)=default
Default move assignment operator.
void configure (const ITensor *input, const ITensor *weights, const ITensor *biases, ITensor *output, const PadStrideInfo &conv_info, unsigned int depth_multiplier=1, const Size2D &dilation=Size2D(1U, 1U))
Initialize the function's source, destination and parameters.
void run (const Window &window, const ThreadInfo &info) override
Execute the kernel on the passed window.
BorderSize border_size () const override
The size of the border for that kernel.
Public Member Functions inherited from ICPPKernel
virtual ~ICPPKernel ()=default
Default destructor.
virtual void run_nd (const Window &window, const ThreadInfo &info, const Window &thread_locator)
legacy compatibility layer for implemantions which do not support thread_locator In these cases we simply narrow the interface down the legacy version
Public Member Functions inherited from IKernel
IKernel ()
Constructor.
virtual ~IKernel ()=default
Destructor.
virtual bool is_parallelisable () const
Indicates whether or not the kernel is parallelisable.
const Window & window () const
The maximum window the kernel can be executed on.
Static Public Member Functions
static Status validate (const ITensorInfo *input, const ITensorInfo *weights, const ITensorInfo *biases, const ITensorInfo *output, const PadStrideInfo &conv_info, unsigned int depth_multiplier=1, const Size2D &dilation=Size2D(1U, 1U))
Static function to check if given info will lead to a valid configuration of NEDepthwiseConvolutionLayerNativeKernel.
Detailed Description
Interface for the kernel to run a depthwise convolution native on a tensor.
Definition at line 40 of file NEDepthwiseConvolutionLayerNativeKernel.h.
Constructor & Destructor Documentation
NEDepthwiseConvolutionLayerNativeKernel() [1/3]
NEDepthwiseConvolutionLayerNativeKernel ()
Default constructor.
Definition at line 499 of file NEDepthwiseConvolutionLayerNativeKernel.cpp.
     : _func(), _border_size(0), _input(), _weights(), _biases(), _output(), _conv_info(), _depth_multiplier(1), _dilation(), _output_multiplier(), _output_shift(), _has_biases()
 {
 }
NEDepthwiseConvolutionLayerNativeKernel() [2/3]
NEDepthwiseConvolutionLayerNativeKernel (const NEDepthwiseConvolutionLayerNativeKernel &) delete
Prevent instances of this class from being copied (As this class contains pointers)
NEDepthwiseConvolutionLayerNativeKernel() [3/3]
NEDepthwiseConvolutionLayerNativeKernel (NEDepthwiseConvolutionLayerNativeKernel &&) default
Default Move Constructor.
Member Function Documentation
border_size()
BorderSize border_size () const override virtual
The size of the border for that kernel.
Returns
The width in number of elements of the border.
Reimplemented from IKernel.
Definition at line 504 of file NEDepthwiseConvolutionLayerNativeKernel.cpp.
 {
     return _border_size;
 }
configure()
void configure (const ITensor * input, const ITensor * weights, const ITensor * biases, ITensor * output, const PadStrideInfo & conv_info, unsigned int depth_multiplier = 1, const Size2D & dilation = Size2D(1U, 1U))
Initialize the function's source, destination and parameters.
Note
Supported data layouts: NHWC
Parameters
[in] input Source tensor. DataType supported: QASYMM8/QASYMM8_SIGNED/F16/F32.
[in] weights Weights tensor. This is a 3D tensor with dimensions [IFM, W, H]. Data type supported: Same as input or QASYMM8/QASYMM8_SIGNED/QSYMM8_PER_CHANNEL when input is QASYMM8/QASYMM8_SIGNED.
[in] biases Biases tensor. A 1D tensor with dimensions [IFM]. Must be nullptr if not needed. Data type supported: Same as input, S32 when input is QASYMM8/QASYMM8_SIGNED.
[out] output Destination tensor. Data type supported: Same as input.
[in] conv_info Padding and stride information to use for the convolution.
[in] depth_multiplier (Optional) Multiplier to apply to the input's depth in order to retrieve the output's depth. Defaults to 1.
[in] dilation (Optional) Dilation, in elements, across x and y. Defaults to (1, 1).
Definition at line 509 of file NEDepthwiseConvolutionLayerNativeKernel.cpp.
 {
     ARM_COMPUTE_ERROR_ON_NULLPTR(input, weights, output);
     ARM_COMPUTE_ERROR_THROW_ON(validate_arguments(input->info(), weights->info(), (biases != nullptr) ? biases->info() : nullptr, output->info(), conv_info, depth_multiplier, dilation));
     _input            = input;
     _weights          = weights;
     _biases           = biases;
     _output           = output;
     _conv_info        = conv_info;
     _depth_multiplier = depth_multiplier;
     _border_size      = BorderSize(_conv_info.pad_left(), 0, std::max(std::max(conv_info.pad_right(), conv_info.pad_bottom()), conv_info.pad_top()), 0);
     _dilation         = dilation;
     _has_biases       = (biases != nullptr);
     if(is_data_type_quantized(_input->info()->data_type()))
     {
         const auto input_scale  = input->info()->quantization_info().uniform().scale;
         const auto output_scale = output->info()->quantization_info().uniform().scale;
         auto weights_scale = weights->info()->quantization_info().scale();
         if(!is_data_type_quantized_per_channel(_weights->info()->data_type()))
         {
             for(size_t i = 1; i < _weights->info()->dimension(0); ++i)
             {
                 weights_scale.push_back(weights_scale.front());
             }
         }
         for(size_t i = 0; i < weights_scale.size(); ++i)
         {
             int32_t     out_mult   = 0;
             int32_t     out_shift  = 0;
             const float multiplier = input_scale * weights_scale.at(i) / output_scale;
             arm_compute::quantization::calculate_quantized_multiplier(multiplier, &out_mult, &out_shift);
             _output_multiplier.push_back(out_mult);
             _output_shift.push_back(out_shift);
         }
     }
     switch(_weights->info()->data_type())
     {
         case DataType::QASYMM8:
             _func = &NEDepthwiseConvolutionLayerNativeKernel::run_depthwise<uint8_t, uint8_t, 8>;
             pad_vectors(_output_multiplier, _output_shift, 8);
             break;
         case DataType::QASYMM8_SIGNED:
             _func = &NEDepthwiseConvolutionLayerNativeKernel::run_depthwise<int8_t, int8_t, 8>;
             pad_vectors(_output_multiplier, _output_shift, 8);
             break;
         case DataType::QSYMM8_PER_CHANNEL:
             if(_input->info()->data_type() == DataType::QASYMM8)
             {
                 _func = &NEDepthwiseConvolutionLayerNativeKernel::run_depthwise<uint8_t, int8_t, 8>;
             }
             else
             {
                 _func = &NEDepthwiseConvolutionLayerNativeKernel::run_depthwise<int8_t, int8_t, 8>;
             }
             pad_vectors(_output_multiplier, _output_shift, 8);
             break;
 #ifdef __ARM_FEATURE_FP16_VECTOR_ARITHMETIC
         case DataType::F16:
             _func = &NEDepthwiseConvolutionLayerNativeKernel::run_depthwise<float16_t, float16_t, 4>;
             pad_vectors(_output_multiplier, _output_shift, 4);
             break;
 #endif // __ARM_FEATURE_FP16_VECTOR_ARITHMETIC
         case DataType::F32:
             _func = &NEDepthwiseConvolutionLayerNativeKernel::run_depthwise<float, float, 2>;
             pad_vectors(_output_multiplier, _output_shift, 2);
             break;
         default:
             ARM_COMPUTE_ERROR("Data type not supported");
             break;
     }
     auto win_config = validate_and_configure_window(_input->info(), _weights->info(), (biases != nullptr) ? biases->info() : nullptr, _output->info(), _conv_info, _depth_multiplier, dilation);
     ARM_COMPUTE_ERROR_THROW_ON(win_config.first);
     INEKernel::configure(win_config.second);
 }
References ARM_COMPUTE_ERROR, ARM_COMPUTE_ERROR_ON_NULLPTR, ARM_COMPUTE_ERROR_THROW_ON, arm_compute::quantization::calculate_quantized_multiplier(), arm_compute::test::validation::conv_info, ITensorInfo::data_type(), arm_compute::test::validation::dilation, ITensorInfo::dimension(), arm_compute::F16, arm_compute::F32, ITensor::info(), Tensor::info(), arm_compute::test::validation::input, arm_compute::is_data_type_quantized(), arm_compute::is_data_type_quantized_per_channel(), PadStrideInfo::pad_left(), arm_compute::QASYMM8, arm_compute::QASYMM8_SIGNED, arm_compute::QSYMM8_PER_CHANNEL, ITensorInfo::quantization_info(), UniformQuantizationInfo::scale, QuantizationInfo::scale(), QuantizationInfo::uniform(), arm_compute::validate_arguments(), and arm_compute::test::validation::weights.
name()
const char* name () const inline override virtual
Name of the kernel.
Returns
Kernel name
Implements ICPPKernel.
Definition at line 43 of file NEDepthwiseConvolutionLayerNativeKernel.h.
     {
         return "NEDepthwiseConvolutionLayerNativeKernel";
     }
operator=() [1/2]
NEDepthwiseConvolutionLayerNativeKernel& operator= (const NEDepthwiseConvolutionLayerNativeKernel &) delete
Prevent instances of this class from being copied (As this class contains pointers)
operator=() [2/2]
NEDepthwiseConvolutionLayerNativeKernel& operator= (NEDepthwiseConvolutionLayerNativeKernel &&) default
Default move assignment operator.
run()
void run (const Window & window, const ThreadInfo & info) override virtual
Execute the kernel on the passed window.
Warning
If is_parallelisable() returns false then the passed window must be equal to window()
Note
The window has to be a region within the window returned by the window() method
The width of the window has to be a multiple of num_elems_processed_per_iteration().
Parameters
[in] window Region on which to execute the kernel. (Must be a region of the window returned by window())
[in] info Info about executing thread and CPU.
Reimplemented from ICPPKernel.
Definition at line 603 of file NEDepthwiseConvolutionLayerNativeKernel.cpp.
 {
     ARM_COMPUTE_UNUSED(info);
     ARM_COMPUTE_ERROR_ON_UNCONFIGURED_KERNEL(this);
     ARM_COMPUTE_ERROR_ON_INVALID_SUBWINDOW(INEKernel::window(), window);
     (this->*_func)(window, _has_biases);
 }
References ARM_COMPUTE_ERROR_ON_INVALID_SUBWINDOW, ARM_COMPUTE_ERROR_ON_UNCONFIGURED_KERNEL, ARM_COMPUTE_UNUSED, arm_compute::test::validation::info, and IKernel::window().
validate()
Status validate (const ITensorInfo * input, const ITensorInfo * weights, const ITensorInfo * biases, const ITensorInfo * output, const PadStrideInfo & conv_info, unsigned int depth_multiplier = 1, const Size2D & dilation = Size2D(1U, 1U)) static
Static function to check if given info will lead to a valid configuration of NEDepthwiseConvolutionLayerNativeKernel.
Note
Supported data layouts: NHWC
Parameters
[in] input Source tensor info. DataType supported: QASYMM8/QASYMM8_SIGNED/F16/F32.
[in] weights Weights tensor info. This is a 3D tensor with dimensions [IFM, W, H]. Data type supported: Same as input or QASYMM8/QASYMM8_SIGNED/QSYMM8_PER_CHANNEL when input is QASYMM8/QASYMM8_SIGNED.
[in] biases Biases tensor info. A 1D tensor with dimensions [IFM]. Must be nullptr if not needed. Data type supported: Same as input, S32 when input is QASYMM8/QASYMM8_SIGNED.
[in] output Destination tensor info. Data type supported: Same as input.
[in] conv_info Padding and stride information to use for the convolution.
[in] depth_multiplier (Optional) Multiplier to apply to the input's depth in order to retrieve the output's depth. Defaults to 1.
[in] dilation (Optional) Dilation, in elements, across x and y. Defaults to (1, 1).
Returns
a status
Definition at line 592 of file NEDepthwiseConvolutionLayerNativeKernel.cpp.
 {
     ARM_COMPUTE_RETURN_ON_ERROR(validate_arguments(input, weights, biases, output, conv_info, depth_multiplier, dilation));
     ARM_COMPUTE_RETURN_ON_ERROR(validate_and_configure_window(input->clone().get(), weights->clone().get(), (biases != nullptr) ? biases->clone().get() : nullptr, output->clone().get(), conv_info,
                                                               depth_multiplier, dilation)
                                 .first);
     return Status{};
 }
References ARM_COMPUTE_RETURN_ON_ERROR, ICloneable< T >::clone(), arm_compute::test::validation::conv_info, arm_compute::test::validation::dilation, arm_compute::test::validation::input, arm_compute::validate_arguments(), and arm_compute::test::validation::weights.
The documentation for this class was generated from the following files:
arm_compute/core/NEON/kernels/NEDepthwiseConvolutionLayerNativeKernel.h
src/core/NEON/kernels/NEDepthwiseConvolutionLayerNativeKernel.cpp