Compute Library: GemmTuner Namespace Reference
GemmTuner Namespace Reference
Data Structures
class BenchmarkResult
class GEMMBenchmarkResultRecorder
class GEMMConfigDistribution
class GEMMParam
class Measurement
class NativeGEMMConfig
class ReshapedGEMMConfig
class ReshapedOnlyRHSGEMMConfig
Functions
BenchmarkResultCSVRow benchmark_result_2_csv_row (BenchmarkResult result)
Dict[str, str] parse_benchmark_commandline (str commandline)
Functions.
Generator[BenchmarkResult, None, None] extract_benchmark_results (Dict json_results, measurement_method="avg")
def parse_json (dir_name)
def main (args)
Main.
Variables
Strategy = Enum("Strategy", ["Native", "ReshapedOnlyRHS", "Reshaped"])
Types.
GEMMConfigT = Union[NativeGEMMConfig, ReshapedOnlyRHSGEMMConfig, ReshapedGEMMConfig]
BenchmarkResultCSVRow
dictionary GEMM_CONFIG_FACTORY
dictionary EXAMPLE_FILE_2_STRATEGY
dictionary GEMM_EXAMPLE_ARGS_FACTORY
string BENCHMARK_RESULT_JSON_EXTENSION = "gemmtuner_benchmark"
parser = argparse.ArgumentParser(description="CL GEMM Tuner")
dest
metavar
action
type
help
required
default
args = parser.parse_args()
logging_level = logging.DEBUG if args.debug else logging.INFO
level
Function Documentation
benchmark_result_2_csv_row()
BenchmarkResultCSVRow GemmTuner.benchmark_result_2_csv_row (BenchmarkResult result)
Convert a BenchmarkResult into its CSV row form
Definition at line 168 of file GemmTuner.py.
 def benchmark_result_2_csv_row(result: BenchmarkResult) -> BenchmarkResultCSVRow:
     """ Convert a BenchmarkResult into its CSV row form """
     return BenchmarkResultCSVRow(
         *(result.gemm_param + (result.strategy.name, str(result.gemm_config)) + result.measurement)
     )
References BenchmarkResultCSVRow.
Referenced by GEMMBenchmarkResultRecorder.save_to_csvs().
extract_benchmark_results()
Generator[BenchmarkResult, None, None] GemmTuner.extract_benchmark_results (Dict json_results, measurement_method = "avg")
Parse the benchmark result and extract relevant information, namely:
    GEMM param,
    Strategy,
    GEMM config,
    Measurements
Definition at line 417 of file GemmTuner.py.
 def extract_benchmark_results(
     json_results: Dict, measurement_method="avg"
 ) -> Generator[BenchmarkResult, None, None]:
     """ Parse the benchmark result and extract relevant information, namely:
         GEMM param,
         Strategy,
         GEMM config,
         Measurements
     """
     for json_res in json_results:
         # Get example test and test data.
         # There should only be 1 test per run
         example_tests = list(json_res["tests"].items())
         assert len(example_tests) == 1
         example_fn, example_test_data = example_tests[0]
         # Process example file name
         example_fn = example_fn.split(os.path.sep)[-1]
         # Get strategy
         strategy = EXAMPLE_FILE_2_STRATEGY[example_fn]
         # Get gemm params + gemm configs from example args
         benchmark_args = parse_benchmark_commandline(json_res["CommandLine"])
         Gemm_Example_Args_T = GEMM_EXAMPLE_ARGS_FACTORY[strategy]
         example_args = Gemm_Example_Args_T(*(benchmark_args["example_args"].split(",")))
         # Gemm_Example_Arg consists of GEMMParam first and then GEMMConfig (in that order)
         gemm_param_fields_len = len(GEMMParam._fields)
         gemm_param = GEMMParam.parse_from_strs(*example_args[:gemm_param_fields_len])
         GEMMConfig = GEMM_CONFIG_FACTORY[strategy]
         gemm_config = GEMMConfig.parse_from_strs(*example_args[gemm_param_fields_len:])
         # Get OpenCL_Time_Ms stats
         measurements = list(example_test_data["measurements"].items())
         # There should only be 1 instrument per run
         assert len(measurements) == 1
         measurement_instrument, data = measurements.pop()
         # Get instrument name and assert that it is the one we expect
         measurement_instrument_name = measurement_instrument.split("/")[0]
         assert measurement_instrument_name == "OpenCLTimer"
         # Take either the minimum or the average of the raw data as the measurement value
         if measurement_method == "min":
             measurement_val = min(data["raw"])
         elif measurement_method == "avg":
             measurement_val = sum(data["raw"]) / len(data["raw"])
         else:
             raise ValueError("Invalid measurement method: {}".format(measurement_method))
         measurement = Measurement(measurement_val)
         yield BenchmarkResult(gemm_param, strategy, gemm_config, measurement)
References parse_benchmark_commandline(), and sum().
Referenced by main().
main()
def GemmTuner.main (args)
Main.
Definition at line 483 of file GemmTuner.py.
 def main(args):
     logging.info("Searching best gemm configurations from {}".format(args.benchmark_results_dir))
     benchmark_results = extract_benchmark_results(parse_json(args.benchmark_results_dir))
     # Add all benchmark results to the recorder
     benchmark_result_recorder = GEMMBenchmarkResultRecorder(tol=args.tolerance)
     for benchmark_result in benchmark_results:
         benchmark_result_recorder.add(benchmark_result)
     if args.debug:
         recorder_sum_level = GEMMBenchmarkResultRecorder.SummaryLevel.Detailed
     else:
         recorder_sum_level = GEMMBenchmarkResultRecorder.SummaryLevel.Short
     # Print overall summary of the recorded results
     logging.info(benchmark_result_recorder.summary(sum_level=recorder_sum_level))
     # Get GEMM configuration distributions for each strategy
     all_config_dists = benchmark_result_recorder.get_config_distributions()
     logging.info("=== Result ===")
     for strategy, config_dist in all_config_dists.items():
         logging.info("Strategy: {}".format(strategy.name))
         logging.debug("GEMM Config, Votes")
         for config, freq in config_dist.frequency():
             logging.debug("{}, {}".format(config, freq))
         logging.info(
             "Best GEMM Config: {} with std: {}".format(config_dist.best_config(), config_dist.std())
         )
     # Save the recorded results to csv files in output directory
     if args.output_dir is not None:
         benchmark_result_recorder.save_to_csvs(args.output_dir, only_best_config=(not args.debug))
References extract_benchmark_results(), and parse_json().
parse_benchmark_commandline()
Dict[str, str] GemmTuner.parse_benchmark_commandline (str commandline)
Functions.
Parse the benchmark example command-line string into a dictionary of command-line agruments
Definition at line 400 of file GemmTuner.py.
 def parse_benchmark_commandline(commandline: str) -> Dict[str, str]:
     """ Parse the benchmark example command-line string into a dictionary of command-line agruments
     """
     args = commandline.split()
     # Discard program name
     args = args[1:]
     # Split into a list of (argument name, argument value)
     args = map(lambda arg: arg.split("="), args)
     def transform(_name):
         # Strip '-'/"--" if it exists
         _name = _name.lstrip("-")
         return _name
     return {transform(name): val for name, val in args}
References arm_compute::utils.map().
Referenced by extract_benchmark_results().
parse_json()
def GemmTuner.parse_json (dir_name)
Glob all benchmark result json files and parse them into json objects (dicts).
Definition at line 470 of file GemmTuner.py.
 def parse_json(dir_name):
     """ Glob all benchmark result json files and parse them into json objects (dicts).
     """
     for res_fn in Path(dir_name).rglob("*.{}".format(BENCHMARK_RESULT_JSON_EXTENSION)):
         with open(res_fn) as res_fp:
             yield json.load(res_fp)
Referenced by main().
Variable Documentation
action
action
Definition at line 526 of file GemmTuner.py.
args
args = parser.parse_args()
Definition at line 555 of file GemmTuner.py.
Referenced by Graph.add_node(), CommandLineParser.add_option(), CommandLineParser.add_positional_option(), arm_compute::test.apply(), arm_compute::test::framework.apply_impl(), CLSynthetizeFunction< CLGEMMMatrixMultiplyReshapedOnlyRHSKernel >.configure(), NESynthetizeFunction< K >.configure(), CLSynthetizeFunctionWithZeroConstantBorder< K, bordersize >.configure(), NESynthetizeFunctionWithZeroConstantBorder< K, bordersize >.configure(), NESynthetizeFunctionWithZeroConstantKernelBorder< K >.configure(), CLSynthetizeFunctionInitOutputWithZeroAndWithZeroConstantBorder< K, bordersize >.configure(), arm_compute.create_configure_kernel(), arm_compute::graph::backends.create_named_function(), arm_compute::graph::backends.create_named_memory_managed_function(), GemmImplementation< Top, Tret, OutputStage >.do_instantiate(), GemmImplementation< Top, Tret, Nothing >.do_instantiate(), GemmImplementation< Top, Tret, OutputStage >.do_is_recommended(), GemmImplementation< Top, Tret, Nothing >.do_is_recommended(), GemmImplementation< Top, Tret, OutputStage >.do_is_supported(), GemmImplementation< Top, Tret, Nothing >.do_is_supported(), arm_gemm.find_implementation(), arm_compute::utility.for_each(), arm_compute::detail.for_each_error(), arm_gemm.gemm(), GemmInterleaved< strategy, To, Tr >.GemmInterleaved(), GemmInterleaved2d< strategy, To, Tr >.GemmInterleaved2d(), GemmInterleavedPretransposed2d< strategy, To, Tr >.GemmInterleavedPretransposed2d(), GemvBatched< To, Tr >.GemvBatched(), GemvPretransposed< strategy, To, Tr >.GemvPretransposed(), arm_gemm.get_compatible_kernels(), arm_gemm.get_gemm_method(), Logger.log(), arm_compute::support::cpp14.make_unique(), arm_compute.operator<<(), QuantizeWrapper< To, Tr, Tgemm >.QuantizeWrapper(), arm_compute::support::cpp11.snprintf(), arm_compute::support::cpp11.stof(), arm_compute::logging.string_with_format(), arm_compute.to_string(), CLSynthetizeFunction< CLGEMMMatrixMultiplyReshapedOnlyRHSKernel >.validate(), and NESynthetizeFunction< K >.validate().
BENCHMARK_RESULT_JSON_EXTENSION
string BENCHMARK_RESULT_JSON_EXTENSION = "gemmtuner_benchmark"
Definition at line 393 of file GemmTuner.py.
BenchmarkResultCSVRow
BenchmarkResultCSVRow
Initial value:
 =  namedtuple(
     "BenchmarkResultCSVRow", GEMMParam._fields + ("Strategy", "GEMMConfig") + Measurement._fields
 )
Definition at line 163 of file GemmTuner.py.
Referenced by benchmark_result_2_csv_row().
default
default
Definition at line 548 of file GemmTuner.py.
dest
dest
Definition at line 524 of file GemmTuner.py.
EXAMPLE_FILE_2_STRATEGY
dictionary EXAMPLE_FILE_2_STRATEGY
Initial value:
 =  {
     "benchmark_cl_gemm_native": Strategy.Native,
     "benchmark_cl_gemm_reshaped_rhs_only": Strategy.ReshapedOnlyRHS,
     "benchmark_cl_gemm_reshaped": Strategy.Reshaped,
 }
Definition at line 367 of file GemmTuner.py.
GEMM_CONFIG_FACTORY
dictionary GEMM_CONFIG_FACTORY
Initial value:
 =  {
     Strategy.Native: NativeGEMMConfig,
     Strategy.ReshapedOnlyRHS: ReshapedOnlyRHSGEMMConfig,
     Strategy.Reshaped: ReshapedGEMMConfig,
 }
Definition at line 359 of file GemmTuner.py.
GEMM_EXAMPLE_ARGS_FACTORY
dictionary GEMM_EXAMPLE_ARGS_FACTORY
Initial value:
 =  {
     strategy: namedtuple(
         "{}_Gemm_Example_Args".format(strategy_name),
         GEMMParam._fields + GEMM_CONFIG_FACTORY[strategy]._fields,
     )
     for strategy_name, strategy in Strategy.__members__.items()
     if strategy_name == strategy.name
 }
Definition at line 383 of file GemmTuner.py.
GEMMConfigT
GEMMConfigT = Union[NativeGEMMConfig, ReshapedOnlyRHSGEMMConfig, ReshapedGEMMConfig]
Definition at line 146 of file GemmTuner.py.
help
help
Definition at line 528 of file GemmTuner.py.
Referenced by Option.set_help().
level
level
Definition at line 557 of file GemmTuner.py.
Referenced by CLLKTrackerInitKernel.configure(), CLLKTrackerStage0Kernel.configure(), CLLKTrackerStage1Kernel.configure(), arm_compute::test::validation.DATA_TEST_CASE(), glFramebufferTexture2D(), glTexImage2D(), arm_compute::test::framework.operator<<(), arm_compute::test::validation::reference.optical_flow(), NEOpticalFlow.run(), CLOpticalFlow.run(), and arm_compute::test::framework.to_string().
logging_level
logging_level = logging.DEBUG if args.debug else logging.INFO
Definition at line 556 of file GemmTuner.py.
metavar
metavar
Definition at line 525 of file GemmTuner.py.
parser
parser = argparse.ArgumentParser(description="CL GEMM Tuner")
Definition at line 520 of file GemmTuner.py.
Referenced by CommonGraphOptions.CommonGraphOptions(), CommonGraphValidateOptions.CommonGraphValidateOptions(), CommonOptions.CommonOptions(), GraphValidateExample< DepthwiseConvolutionLayer, DepthConvolutionOptions, DepthConvolutionVerifyAccessor >.do_setup(), main(), and arm_compute::utils.run_example().
required
required
Definition at line 532 of file GemmTuner.py.
Referenced by arm_compute.adjust_down(), and arm_compute.adjust_up().
Strategy
Strategy = Enum("Strategy", ["Native", "ReshapedOnlyRHS", "Reshaped"])
Types.
Definition at line 41 of file GemmTuner.py.
type
type
Definition at line 527 of file GemmTuner.py.
Referenced by CommonOptions.CommonOptions(), NEThreshold.configure(), CLThreshold.configure(), CLThresholdKernel.configure(), CLNormalizationLayerKernel.configure(), NEFunctionFactory.create(), SchedulerFactory.create(), CLFunctionFactory.create(), GCFunctionFactory.create(), ImageLoaderFactory.create(), arm_compute::test::validation.DATA_TEST_CASE(), arm_compute::test::validation::reference.gemmlowp_matrix_multiply_core(), arm_compute::utils.get_image_type_from_file(), Framework.get_profiler(), glCreateShader(), glTexImage2D(), TensorInfo.init(), TensorInfo.init_auto_padding(), arm_compute::support::cpp14.make_unique(), Graph.nodes(), arm_compute::test::validation::reference.normalization_layer(), arm_compute::test::framework.operator &(), compare< RelativeTolerance< U > >.operator bool(), arm_compute::test::framework.operator|(), arm_compute::test::framework.operator|=(), arm_compute::test::validation::reference.pooling_layer_internal(), PassManager.run_type(), arm_compute.string_from_norm_type(), arm_compute.string_from_pooling_type(), arm_compute::test.sync_if_necessary(), arm_compute::test.sync_tensor_if_necessary(), arm_compute::test::validation::reference.threshold(), arm_compute.to_string(), NENodeValidator.validate(), GCNodeValidator.validate(), CLNodeValidator.validate(), and arm_compute::test::validation.validate_wrap().