Compute Library: src/core/CL/cl_kernels/accumulate.cl File Reference
accumulate.cl File Reference
#include "helpers.h"
Functions
__kernel void accumulate (__global uchar *input_ptr, uint input_stride_x, uint input_step_x, uint input_stride_y, uint input_step_y, uint input_offset_first_element_in_bytes, __global uchar *accu_ptr, uint accu_stride_x, uint accu_step_x, uint accu_stride_y, uint accu_step_y, uint accu_offset_first_element_in_bytes)
This function accumulates an input image into output image.
__kernel void accumulate_weighted (__global uchar *input_ptr, uint input_stride_x, uint input_step_x, uint input_stride_y, uint input_step_y, uint input_offset_first_element_in_bytes, __global uchar *accu_ptr, uint accu_stride_x, uint accu_step_x, uint accu_stride_y, uint accu_step_y, uint accu_offset_first_element_in_bytes, const float alpha)
This function accumulates a weighted value from an input image to an output image.
__kernel void accumulate_squared (__global uchar *input_ptr, uint input_stride_x, uint input_step_x, uint input_stride_y, uint input_step_y, uint input_offset_first_element_in_bytes, __global uchar *accu_ptr, uint accu_stride_x, uint accu_step_x, uint accu_stride_y, uint accu_step_y, uint accu_offset_first_element_in_bytes, const uint shift)
This function accumulates a squared value from an input image to an output image.
Function Documentation
accumulate()
__kernel void accumulate (__global uchar * input_ptr, uint input_stride_x, uint input_step_x, uint input_stride_y, uint input_step_y, uint input_offset_first_element_in_bytes, __global uchar * accu_ptr, uint accu_stride_x, uint accu_step_x, uint accu_stride_y, uint accu_step_y, uint accu_offset_first_element_in_bytes)
This function accumulates an input image into output image.
Parameters
[in] input_ptr Pointer to the source image. Supported data types: U8
[in] input_stride_x Stride of the source image in X dimension (in bytes)
[in] input_step_x input_stride_x * number of elements along X processed per workitem(in bytes)
[in] input_stride_y Stride of the source image in Y dimension (in bytes)
[in] input_step_y input_stride_y * number of elements along Y processed per workitem(in bytes)
[in] input_offset_first_element_in_bytes The offset of the first element in the source image
[out] accu_ptr Pointer to the destination image. Supported data types: S16
[in] accu_stride_x Stride of the destination image in X dimension (in bytes)
[in] accu_step_x accu_stride_x * number of elements along X processed per workitem(in bytes)
[in] accu_stride_y Stride of the destination image in Y dimension (in bytes)
[in] accu_step_y accu_stride_y * number of elements along Y processed per workitem(in bytes)
[in] accu_offset_first_element_in_bytes The offset of the first element in the destination image
Definition at line 41 of file accumulate.cl.
 {
     // Get pixels pointer
     Image input = CONVERT_TO_IMAGE_STRUCT(input);
     Image accu  = CONVERT_TO_IMAGE_STRUCT(accu);
     // Load data
     uchar16 in_data   = vload16(0, input.ptr);
     short16 accu_data = vload16(0, (__global short *)accu.ptr);
     // Perform accumulation
     short16 res = add_sat(convert_short16(in_data), accu_data);
     // Store result
     vstore16(res, 0, (__global short *)accu.ptr);
 }
References arm_compute::wrapper::add_sat(), CONVERT_TO_IMAGE_STRUCT, and Image::ptr.
Referenced by arm_compute::calculate_matrix_scale(), Dimensions< size_t >::collapse(), arm_compute::data_type_for_convolution(), arm_compute::data_type_for_convolution_matrix(), arm_compute::helpers::fft::digit_reverse_indices(), arm_compute::test::join(), arm_compute::test::validation::reference::mean_and_standard_deviation(), arm_compute::pixel_area_c1u8_clamp(), SimpleTensor< uint8_t >::size(), OpenCLMemoryUsage::test_measurements(), TensorShape::total_size(), TensorShape::total_size_lower(), and TensorShape::total_size_upper().
accumulate_squared()
__kernel void accumulate_squared (__global uchar * input_ptr, uint input_stride_x, uint input_step_x, uint input_stride_y, uint input_step_y, uint input_offset_first_element_in_bytes, __global uchar * accu_ptr, uint accu_stride_x, uint accu_step_x, uint accu_stride_y, uint accu_step_y, uint accu_offset_first_element_in_bytes, const uint shift)
This function accumulates a squared value from an input image to an output image.
Parameters
[in] input_ptr Pointer to the source image. Supported data types: U8
[in] input_stride_x Stride of the source image in X dimension (in bytes)
[in] input_step_x input_stride_x * number of elements along X processed per workitem(in bytes)
[in] input_stride_y Stride of the source image in Y dimension (in bytes)
[in] input_step_y input_stride_y * number of elements along Y processed per workitem(in bytes)
[in] input_offset_first_element_in_bytes The offset of the first element in the source image
[out] accu_ptr Pointer to the destination image. Supported data types: S16
[in] accu_stride_x Stride of the destination image in X dimension (in bytes)
[in] accu_step_x accu_stride_x * number of elements along X processed per workitem(in bytes)
[in] accu_stride_y Stride of the destination image in Y dimension (in bytes)
[in] accu_step_y accu_stride_y * number of elements along Y processed per workitem(in bytes)
[in] accu_offset_first_element_in_bytes The offset of the first element in the destination image
[in] shift The U32 scalar value with a value in the range of 0 to 15
Definition at line 112 of file accumulate.cl.
 {
     // Get pixels pointer
     Image input = CONVERT_TO_IMAGE_STRUCT(input);
     Image accu  = CONVERT_TO_IMAGE_STRUCT(accu);
     // Load data
     ushort16 in_data   = convert_ushort16(vload16(0, input.ptr));
     uint16   accu_data = convert_uint16(vload16(0, (__global short *)accu.ptr));
     // Calculate squared accumulation
     short16 res = convert_short16_sat(accu_data + convert_uint16((in_data * in_data) >> shift));
     // Store result
     vstore16(res, 0, (__global short *)accu.ptr);
 }
References CONVERT_TO_IMAGE_STRUCT, Image::ptr, and arm_compute::test::validation::shift.
accumulate_weighted()
__kernel void accumulate_weighted (__global uchar * input_ptr, uint input_stride_x, uint input_step_x, uint input_stride_y, uint input_step_y, uint input_offset_first_element_in_bytes, __global uchar * accu_ptr, uint accu_stride_x, uint accu_step_x, uint accu_stride_y, uint accu_step_y, uint accu_offset_first_element_in_bytes, const float alpha)
This function accumulates a weighted value from an input image to an output image.
Parameters
[in] input_ptr Pointer to the source image. Supported data types: U8
[in] input_stride_x Stride of the source image in X dimension (in bytes)
[in] input_step_x input_stride_x * number of elements along X processed per workitem(in bytes)
[in] input_stride_y Stride of the source image in Y dimension (in bytes)
[in] input_step_y input_stride_y * number of elements along Y processed per workitem(in bytes)
[in] input_offset_first_element_in_bytes The offset of the first element in the source image
[out] accu_ptr Pointer to the destination image. Supported data types: S16
[in] accu_stride_x Stride of the destination image in X dimension (in bytes)
[in] accu_step_x accu_stride_x * number of elements along X processed per workitem(in bytes)
[in] accu_stride_y Stride of the destination image in Y dimension (in bytes)
[in] accu_step_y accu_stride_y * number of elements along Y processed per workitem(in bytes)
[in] accu_offset_first_element_in_bytes The offset of the first element in the destination image
[in] alpha The float scalar value with a value in the range of 0 to 1
Definition at line 76 of file accumulate.cl.
 {
     // Get pixels pointer
     Image input = CONVERT_TO_IMAGE_STRUCT(input);
     Image accu  = CONVERT_TO_IMAGE_STRUCT(accu);
     // Load data
     const float16 in_data   = convert_float16(vload16(0, input.ptr));
     const float16 accu_data = convert_float16(vload16(0, accu.ptr));
     // Calculate weighted accumulation
     const uchar16 res = convert_uchar16((1.0f - alpha) * accu_data + alpha * in_data);
     // Store result
     vstore16(res, 0, accu.ptr);
 }
References arm_compute::test::validation::alpha, CONVERT_TO_IMAGE_STRUCT, and Image::ptr.