Compute Library: tests/benchmark/main.cpp File Reference
main.cpp File Reference
#include "Globals.h"
#include "PMUCounter.h"
#include "PerformanceProgramOptions.h"
#include "PerformanceUserConfiguration.h"
#include "TensorLibrary.h"
#include "Utils.h"
#include "WallClockTimer.h"
#include "benchmark/benchmark_api.h"
#include "arm_compute/runtime/Scheduler.h"
#include <iostream>
#include <memory>
Namespaces
arm_compute
arm_compute::test
Functions
int main (int argc, char **argv)
Variables
PerformanceUserConfiguration user_config
std::unique_ptr< TensorLibrary > library
Function Documentation
int main (int argc, char ** argv)
Definition at line 54 of file main.cpp.
References CLScheduler::default_init(), CLScheduler::get(), Scheduler::get(), ProgramOptions::get_help(), arm_compute::test::library, ProgramOptions::parse_commandline(), UserConfiguration::path, UserConfiguration::seed, IScheduler::set_num_threads(), UserConfiguration::threads, arm_compute::test::user_config, and ProgramOptions::wants_help().
 {
     PerformanceProgramOptions options;
     try
     {
         options.parse_commandline(argc, argv);
         if(options.wants_help())
         {
             std::cout << "Usage: " << argv[0] << " [options] PATH\n";
             std::cout << options.get_help() << "\n";
         }
         user_config = PerformanceUserConfiguration(options);
     }
     catch(const boost::program_options::required_option &err)
     {
         std::cerr << "Error: " << err.what() << "\n";
         std::cout << "\nUsage: " << argv[0] << " [options] PATH\n";
         std::cout << options.get_help() << "\n";
         return 1;
     }
     ::benchmark::Initialize(&argc, argv);
     if(user_config.seed.is_set())
     {
         library = cpp14::make_unique<TensorLibrary>(user_config.path.get(), user_config.seed);
     }
     else
     {
         library = cpp14::make_unique<TensorLibrary>(user_config.path.get());
     }
 #ifdef OPENCL
     arm_compute::CLScheduler::get().default_init();
 #endif
     std::cout << "Using " << user_config.threads << " CPU " << (user_config.threads == 1 ? "thread" : "threads") << "\n";
     arm_compute::Scheduler::get().set_num_threads(user_config.threads);
     ::benchmark::RunSpecifiedBenchmarks();
 }