Compute Library: src/core/CL/cl_kernels/bitwise_op.cl File Reference
bitwise_op.cl File Reference
#include "helpers.h"
Functions
__kernel void bitwise_or (__global uchar *in1_ptr, uint in1_stride_x, uint in1_step_x, uint in1_stride_y, uint in1_step_y, uint in1_offset_first_element_in_bytes, __global uchar *in2_ptr, uint in2_stride_x, uint in2_step_x, uint in2_stride_y, uint in2_step_y, uint in2_offset_first_element_in_bytes, __global uchar *out_ptr, uint out_stride_x, uint out_step_x, uint out_stride_y, uint out_step_y, uint out_offset_first_element_in_bytes)
This function computes the bitwise OR of two input images.
__kernel void bitwise_and (__global uchar *in1_ptr, uint in1_stride_x, uint in1_step_x, uint in1_stride_y, uint in1_step_y, uint in1_offset_first_element_in_bytes, __global uchar *in2_ptr, uint in2_stride_x, uint in2_step_x, uint in2_stride_y, uint in2_step_y, uint in2_offset_first_element_in_bytes, __global uchar *out_ptr, uint out_stride_x, uint out_step_x, uint out_stride_y, uint out_step_y, uint out_offset_first_element_in_bytes)
This function computes the bitwise AND of two input images.
__kernel void bitwise_xor (__global uchar *in1_ptr, uint in1_stride_x, uint in1_step_x, uint in1_stride_y, uint in1_step_y, uint in1_offset_first_element_in_bytes, __global uchar *in2_ptr, uint in2_stride_x, uint in2_step_x, uint in2_stride_y, uint in2_step_y, uint in2_offset_first_element_in_bytes, __global uchar *out_ptr, uint out_stride_x, uint out_step_x, uint out_stride_y, uint out_step_y, uint out_offset_first_element_in_bytes)
This function computes the bitwise XOR of two input images.
__kernel void bitwise_not (__global uchar *in_ptr, uint in_stride_x, uint in_step_x, uint in_stride_y, uint in_step_y, uint in_offset_first_element_in_bytes, __global uchar *out_ptr, uint out_stride_x, uint out_step_x, uint out_stride_y, uint out_step_y, uint out_offset_first_element_in_bytes)
This function computes the bitwise NOT of an image.
Function Documentation
__kernel void bitwise_and (__global uchar * in1_ptr, uint in1_stride_x, uint in1_step_x, uint in1_stride_y, uint in1_step_y, uint in1_offset_first_element_in_bytes, __global uchar * in2_ptr, uint in2_stride_x, uint in2_step_x, uint in2_stride_y, uint in2_step_y, uint in2_offset_first_element_in_bytes, __global uchar * out_ptr, uint out_stride_x, uint out_step_x, uint out_stride_y, uint out_step_y, uint out_offset_first_element_in_bytes)
This function computes the bitwise AND of two input images.
Parameters
[in] in1_ptr Pointer to the source image. Supported data types: U8
[in] in1_stride_x Stride of the source image in X dimension (in bytes)
[in] in1_step_x in1_stride_x * number of elements along X processed per workitem(in bytes)
[in] in1_stride_y Stride of the source image in Y dimension (in bytes)
[in] in1_step_y in1_stride_y * number of elements along Y processed per workitem(in bytes)
[in] in1_offset_first_element_in_bytes The offset of the first element in the source image
[in] in2_ptr Pointer to the source image. Supported data types: U8
[in] in2_stride_x Stride of the source image in X dimension (in bytes)
[in] in2_step_x in2_stride_x * number of elements along X processed per workitem(in bytes)
[in] in2_stride_y Stride of the source image in Y dimension (in bytes)
[in] in2_step_y in2_stride_y * number of elements along Y processed per workitem(in bytes)
[in] in2_offset_first_element_in_bytes The offset of the first element in the source image
[out] out_ptr Pointer to the destination image. Supported data types: U8
[in] out_stride_x Stride of the destination image in X dimension (in bytes)
[in] out_step_x out_stride_x * number of elements along X processed per workitem(in bytes)
[in] out_stride_y Stride of the destination image in Y dimension (in bytes)
[in] out_step_y out_stride_y * number of elements along Y processed per workitem(in bytes)
[in] out_offset_first_element_in_bytes The offset of the first element in the destination image
Definition at line 83 of file bitwise_op.cl.
References CONVERT_TO_IMAGE_STRUCT, and Image::ptr.
Referenced by arm_compute::test::validation::DATA_TEST_CASE(), and BitwiseAndValidationFixture< TensorType, AccessorType, FunctionType, T >::setup().
 {
     Image in1 = CONVERT_TO_IMAGE_STRUCT(in1);
     Image in2 = CONVERT_TO_IMAGE_STRUCT(in2);
     Image out = CONVERT_TO_IMAGE_STRUCT(out);
     uchar16 in_a = vload16(0, in1.ptr);
     uchar16 in_b = vload16(0, in2.ptr);
     vstore16(in_a & in_b, 0, out.ptr);
 }
__kernel void bitwise_not (__global uchar * in_ptr, uint in_stride_x, uint in_step_x, uint in_stride_y, uint in_step_y, uint in_offset_first_element_in_bytes, __global uchar * out_ptr, uint out_stride_x, uint out_step_x, uint out_stride_y, uint out_step_y, uint out_offset_first_element_in_bytes)
This function computes the bitwise NOT of an image.
Parameters
[in] in_ptr Pointer to the source image. Supported data types: U8
[in] in_stride_x Stride of the source image in X dimension (in bytes)
[in] in_step_x in_stride_x * number of elements along X processed per workitem(in bytes)
[in] in_stride_y Stride of the source image in Y dimension (in bytes)
[in] in_step_y in_stride_y * number of elements along Y processed per workitem(in bytes)
[in] in_offset_first_element_in_bytes The offset of the first element in the source image
[out] out_ptr Pointer to the destination image. Supported data types: U8
[in] out_stride_x Stride of the destination image in X dimension (in bytes)
[in] out_step_x out_stride_x * number of elements along X processed per workitem(in bytes)
[in] out_stride_y Stride of the destination image in Y dimension (in bytes)
[in] out_step_y out_stride_y * number of elements along Y processed per workitem(in bytes)
[in] out_offset_first_element_in_bytes The offset of the first element in the destination image
Definition at line 149 of file bitwise_op.cl.
References CONVERT_TO_IMAGE_STRUCT, and Image::ptr.
Referenced by BitwiseNotValidationFixture< TensorType, AccessorType, FunctionType, T >::setup().
 {
     Image in  = CONVERT_TO_IMAGE_STRUCT(in);
     Image out = CONVERT_TO_IMAGE_STRUCT(out);
     uchar16 in_data = vload16(0, in.ptr);
     vstore16(~in_data, 0, out.ptr);
 }
__kernel void bitwise_or (__global uchar * in1_ptr, uint in1_stride_x, uint in1_step_x, uint in1_stride_y, uint in1_step_y, uint in1_offset_first_element_in_bytes, __global uchar * in2_ptr, uint in2_stride_x, uint in2_step_x, uint in2_stride_y, uint in2_step_y, uint in2_offset_first_element_in_bytes, __global uchar * out_ptr, uint out_stride_x, uint out_step_x, uint out_stride_y, uint out_step_y, uint out_offset_first_element_in_bytes)
This function computes the bitwise OR of two input images.
Parameters
[in] in1_ptr Pointer to the source image. Supported data types: U8
[in] in1_stride_x Stride of the source image in X dimension (in bytes)
[in] in1_step_x in1_stride_x * number of elements along X processed per workitem(in bytes)
[in] in1_stride_y Stride of the source image in Y dimension (in bytes)
[in] in1_step_y in1_stride_y * number of elements along Y processed per workitem(in bytes)
[in] in1_offset_first_element_in_bytes The offset of the first element in the source image
[in] in2_ptr Pointer to the source image. Supported data types: U8
[in] in2_stride_x Stride of the source image in X dimension (in bytes)
[in] in2_step_x in2_stride_x * number of elements along X processed per workitem(in bytes)
[in] in2_stride_y Stride of the source image in Y dimension (in bytes)
[in] in2_step_y in2_stride_y * number of elements along Y processed per workitem(in bytes)
[in] in2_offset_first_element_in_bytes The offset of the first element in the source image
[out] out_ptr Pointer to the destination image. Supported data types: U8
[in] out_stride_x Stride of the destination image in X dimension (in bytes)
[in] out_step_x out_stride_x * number of elements along X processed per workitem(in bytes)
[in] out_stride_y Stride of the destination image in Y dimension (in bytes)
[in] out_step_y out_stride_y * number of elements along Y processed per workitem(in bytes)
[in] out_offset_first_element_in_bytes The offset of the first element in the destination image
Definition at line 47 of file bitwise_op.cl.
References CONVERT_TO_IMAGE_STRUCT, and Image::ptr.
Referenced by BitwiseOrValidationFixture< TensorType, AccessorType, FunctionType, T >::setup().
 {
     Image in1 = CONVERT_TO_IMAGE_STRUCT(in1);
     Image in2 = CONVERT_TO_IMAGE_STRUCT(in2);
     Image out = CONVERT_TO_IMAGE_STRUCT(out);
     uchar16 in_a = vload16(0, in1.ptr);
     uchar16 in_b = vload16(0, in2.ptr);
     vstore16(in_a | in_b, 0, out.ptr);
 }
__kernel void bitwise_xor (__global uchar * in1_ptr, uint in1_stride_x, uint in1_step_x, uint in1_stride_y, uint in1_step_y, uint in1_offset_first_element_in_bytes, __global uchar * in2_ptr, uint in2_stride_x, uint in2_step_x, uint in2_stride_y, uint in2_step_y, uint in2_offset_first_element_in_bytes, __global uchar * out_ptr, uint out_stride_x, uint out_step_x, uint out_stride_y, uint out_step_y, uint out_offset_first_element_in_bytes)
This function computes the bitwise XOR of two input images.
Parameters
[in] in1_ptr Pointer to the source image. Supported data types: U8
[in] in1_stride_x Stride of the source image in X dimension (in bytes)
[in] in1_step_x in1_stride_x * number of elements along X processed per workitem(in bytes)
[in] in1_stride_y Stride of the source image in Y dimension (in bytes)
[in] in1_step_y in1_stride_y * number of elements along Y processed per workitem(in bytes)
[in] in1_offset_first_element_in_bytes The offset of the first element in the source image
[in] in2_ptr Pointer to the source image. Supported data types: U8
[in] in2_stride_x Stride of the source image in X dimension (in bytes)
[in] in2_step_x in2_stride_x * number of elements along X processed per workitem(in bytes)
[in] in2_stride_y Stride of the source image in Y dimension (in bytes)
[in] in2_step_y in2_stride_y * number of elements along Y processed per workitem(in bytes)
[in] in2_offset_first_element_in_bytes The offset of the first element in the source image
[out] out_ptr Pointer to the destination image. Supported data types: U8
[in] out_stride_x Stride of the destination image in X dimension (in bytes)
[in] out_step_x out_stride_x * number of elements along X processed per workitem(in bytes)
[in] out_stride_y Stride of the destination image in Y dimension (in bytes)
[in] out_step_y out_stride_y * number of elements along Y processed per workitem(in bytes)
[in] out_offset_first_element_in_bytes The offset of the first element in the destination image
Definition at line 119 of file bitwise_op.cl.
References CONVERT_TO_IMAGE_STRUCT, and Image::ptr.
Referenced by BitwiseXorValidationFixture< TensorType, AccessorType, FunctionType, T >::setup().
 {
     Image in1 = CONVERT_TO_IMAGE_STRUCT(in1);
     Image in2 = CONVERT_TO_IMAGE_STRUCT(in2);
     Image out = CONVERT_TO_IMAGE_STRUCT(out);
     uchar16 in_a = vload16(0, in1.ptr);
     uchar16 in_b = vload16(0, in2.ptr);
     vstore16(in_a ^ in_b, 0, out.ptr);
 }