Compute Library: NEHeightConcatenateLayerKernel Class Reference
NEHeightConcatenateLayerKernel Class Reference
Interface for the height concatenate kernel.
#include <NEHeightConcatenateLayerKernel.h>
Public Member Functions
const char * name () const override
Name of the kernel.
NEHeightConcatenateLayerKernel ()
Default constructor.
NEHeightConcatenateLayerKernel (const NEHeightConcatenateLayerKernel &)=delete
Prevent instances of this class from being copied (As this class contains pointers)
NEHeightConcatenateLayerKernel & operator= (const NEHeightConcatenateLayerKernel &)=delete
Prevent instances of this class from being copied (As this class contains pointers)
NEHeightConcatenateLayerKernel (NEHeightConcatenateLayerKernel &&)=default
Allow instances of this class to be moved.
NEHeightConcatenateLayerKernel & operator= (NEHeightConcatenateLayerKernel &&)=default
Allow instances of this class to be moved.
~NEHeightConcatenateLayerKernel ()=default
Default destructor.
void configure (const ITensor *input, unsigned int height_offset, ITensor *output)
Initialise the kernel's inputs and output.
void run (const Window &window, const ThreadInfo &info) override
Execute the kernel on the passed window.
Public Member Functions inherited from ICPPKernel
virtual ~ICPPKernel ()=default
Default destructor.
Public Member Functions inherited from IKernel
IKernel ()
Constructor.
virtual ~IKernel ()=default
Destructor.
virtual bool is_parallelisable () const
Indicates whether or not the kernel is parallelisable.
virtual BorderSize border_size () const
The size of the border for that kernel.
const Window & window () const
The maximum window the kernel can be executed on.
Static Public Member Functions
static Status validate (const ITensorInfo *input, unsigned int height_offset, const ITensorInfo *output)
Static function to check if given info will lead to a valid configuration of NEHeightConcatenateLayerKernel.
Detailed Description
Interface for the height concatenate kernel.
The input tensor will be concatenated into the output tensor.
Definition at line 38 of file NEHeightConcatenateLayerKernel.h.
Constructor & Destructor Documentation
NEHeightConcatenateLayerKernel() [1/3]
NEHeightConcatenateLayerKernel ()
Default constructor.
Definition at line 77 of file NEHeightConcatenateLayerKernel.cpp.
     : _input(nullptr), _output(nullptr), _height_offset(0)
 {
 }
NEHeightConcatenateLayerKernel() [2/3]
NEHeightConcatenateLayerKernel (const NEHeightConcatenateLayerKernel &) delete
Prevent instances of this class from being copied (As this class contains pointers)
NEHeightConcatenateLayerKernel() [3/3]
NEHeightConcatenateLayerKernel (NEHeightConcatenateLayerKernel &&) default
Allow instances of this class to be moved.
~NEHeightConcatenateLayerKernel()
~NEHeightConcatenateLayerKernel () default
Default destructor.
Member Function Documentation
configure()
void configure (const ITensor * input, unsigned int height_offset, ITensor * output)
Initialise the kernel's inputs and output.
Parameters
[in] input Input tensor. Data types supported: U8/S8/QASYMM8/U16/S16/F16/U32/S32/F32
[in] height_offset The starting offset on the Y axis for the output tensor.
[in,out] output Output tensor. Data types supported: Same as input.
Definition at line 82 of file NEHeightConcatenateLayerKernel.cpp.
 {
     ARM_COMPUTE_ERROR_ON_NULLPTR(input, output);
     ARM_COMPUTE_ERROR_THROW_ON(validate_arguments(input->info(), height_offset, output->info()));
     _input         = input;
     _output        = output;
     _height_offset = height_offset;
     // Configure kernel window
     auto win_config = validate_and_configure_window(input->info(), output->info());
     ARM_COMPUTE_ERROR_THROW_ON(std::get<0>(win_config));
     INEKernel::configure(std::get<1>(win_config));
     // Set output valid region
     output->info()->set_valid_region(ValidRegion(Coordinates(), output->info()->tensor_shape()));
 }
References ARM_COMPUTE_ERROR_ON_NULLPTR, ARM_COMPUTE_ERROR_THROW_ON, ITensor::info(), ITensorInfo::set_valid_region(), ITensorInfo::tensor_shape(), and arm_compute::validate_and_configure_window().
name()
const char* name () const inline override virtual
Name of the kernel.
Returns
Kernel name
Implements ICPPKernel.
Definition at line 41 of file NEHeightConcatenateLayerKernel.h.
     {
         return "NEHeightConcatenateLayerKernel";
     }
operator=() [1/2]
NEHeightConcatenateLayerKernel& operator= (const NEHeightConcatenateLayerKernel &) delete
Prevent instances of this class from being copied (As this class contains pointers)
operator=() [2/2]
NEHeightConcatenateLayerKernel& operator= (NEHeightConcatenateLayerKernel &&) default
Allow instances of this class to be moved.
run()
void run (const Window & window, const ThreadInfo & info) override virtual
Execute the kernel on the passed window.
Warning
If is_parallelisable() returns false then the passed window must be equal to window()
Note
The window has to be a region within the window returned by the window() method
The width of the window has to be a multiple of num_elems_processed_per_iteration().
Parameters
[in] window Region on which to execute the kernel. (Must be a region of the window returned by window())
[in] info Info about executing thread and CPU.
Implements ICPPKernel.
Definition at line 108 of file NEHeightConcatenateLayerKernel.cpp.
 {
     ARM_COMPUTE_UNUSED(info);
     ARM_COMPUTE_ERROR_ON_UNCONFIGURED_KERNEL(this);
     ARM_COMPUTE_ERROR_ON_INVALID_SUBWINDOW(INEKernel::window(), window);
     // Offset output pointer to the correct position
     uint8_t *output_ptr = _output->buffer() + _output->info()->offset_first_element_in_bytes() + _height_offset * _output->info()->strides_in_bytes()[Window::DimY];
     // Create iterators
     Iterator                       input(_input, window);
     Iterator                       output(_output, window);
     const DataType                 dt           = _input->info()->data_type();
     const UniformQuantizationInfo &input_qinfo  = _input->info()->quantization_info().uniform();
     const UniformQuantizationInfo &output_qinfo = _output->info()->quantization_info().uniform();
     if(dt == DataType::QASYMM8 && input_qinfo != output_qinfo)
     {
         execute_window_loop(window, [&](const Coordinates &)
         {
             vst1q_u8(output_ptr + output.offset(), vquantize(vdequantize(vld1q_u8(input.ptr()), input_qinfo), output_qinfo));
         },
         input, output);
     }
     else
     {
         execute_window_loop(window, [&](const Coordinates &)
         {
             const auto in_ptr  = input.ptr();
             const auto out_ptr = output_ptr + output.offset();
             wrapper::vstore(out_ptr, wrapper::vloadq(in_ptr));
         },
         input, output);
     }
 }
References ARM_COMPUTE_ERROR_ON_INVALID_SUBWINDOW, ARM_COMPUTE_ERROR_ON_UNCONFIGURED_KERNEL, ARM_COMPUTE_UNUSED, ITensor::buffer(), ITensorInfo::data_type(), Window::DimY, arm_compute::execute_window_loop(), ITensor::info(), arm_compute::test::validation::info, Iterator::offset(), ITensorInfo::offset_first_element_in_bytes(), Iterator::ptr(), arm_compute::QASYMM8, ITensorInfo::quantization_info(), ITensorInfo::strides_in_bytes(), QuantizationInfo::uniform(), arm_compute::vdequantize(), arm_compute::wrapper::vloadq(), arm_compute::vquantize(), arm_compute::wrapper::vstore(), and IKernel::window().
validate()
Status validate (const ITensorInfo * input, unsigned int height_offset, const ITensorInfo * output) static
Static function to check if given info will lead to a valid configuration of NEHeightConcatenateLayerKernel.
Parameters
[in] input Input tensor info. Data types supported: U8/S8/QASYMM8/U16/S16/F16/U32/S32/F32
[in] height_offset The starting offset on the Y axis for the output tensor.
[in] output Output tensor info. Data types supported: Same as input.
Returns
a status
Definition at line 101 of file NEHeightConcatenateLayerKernel.cpp.
 {
     ARM_COMPUTE_RETURN_ON_ERROR(validate_arguments(input, height_offset, output));
     ARM_COMPUTE_RETURN_ON_ERROR(validate_and_configure_window(input->clone().get(), output->clone().get()).first);
     return Status{};
 }
References ARM_COMPUTE_RETURN_ON_ERROR, ICloneable< T >::clone(), and arm_compute::validate_and_configure_window().
The documentation for this class was generated from the following files:
arm_compute/core/NEON/kernels/NEHeightConcatenateLayerKernel.h
src/core/NEON/kernels/NEHeightConcatenateLayerKernel.cpp