Compute Library: OpenCLClock< output_timestamps > Class Template Reference
OpenCLClock< output_timestamps > Class Template Reference
Instrument creating measurements based on the information returned by clGetEventProfilingInfo for each OpenCL kernel executed.
#include <OpenCLTimer.h>
Public Member Functions
OpenCLClock (ScaleFactor scale_factor)
Construct an OpenCL timer.
std::string id () const override
Identifier for the instrument.
void test_start () override
Start of the test.
void start () override
Start measuring.
void stop () override
Stop measuring.
void test_stop () override
End of the test.
MeasurementsMap measurements () const override
Return the latest measurements.
MeasurementsMap test_measurements () const override
Return the latest test measurements.
Public Member Functions inherited from Instrument
Instrument ()=default
Default constructor.
Instrument (const Instrument &)=default
Allow instances of this class to be copy constructed.
Instrument (Instrument &&)=default
Allow instances of this class to be move constructed.
Instrument & operator= (const Instrument &)=default
Allow instances of this class to be copied.
Instrument & operator= (Instrument &&)=default
Allow instances of this class to be moved.
virtual ~Instrument ()=default
Default destructor.
Additional Inherited Members
Public Types inherited from Instrument
using MeasurementsMap = std::map< std::string, Measurement >
Map of measurements.
Static Public Member Functions inherited from Instrument
template<typename T , ScaleFactor scale>
static std::unique_ptr< Instrument > make_instrument ()
Helper function to create an instrument of the given type.
Detailed Description
template<bool output_timestamps>
class arm_compute::test::framework::OpenCLClock< output_timestamps >
Instrument creating measurements based on the information returned by clGetEventProfilingInfo for each OpenCL kernel executed.
Definition at line 45 of file OpenCLTimer.h.
Constructor & Destructor Documentation
OpenCLClock()
OpenCLClock (ScaleFactor scale_factor)
Construct an OpenCL timer.
Parameters
[in] scale_factor Measurement scale factor.
Definition at line 56 of file OpenCLTimer.cpp.
     : _kernels(), _real_function(nullptr), _real_graph_function(nullptr), _prefix(), _timer_enabled(false)
 {
     auto                        q     = CLScheduler::get().queue();
     cl_command_queue_properties props = q.getInfo<CL_QUEUE_PROPERTIES>();
     if((props & CL_QUEUE_PROFILING_ENABLE) == 0)
     {
         CLScheduler::get().set_queue(cl::CommandQueue(CLScheduler::get().context(), props | CL_QUEUE_PROFILING_ENABLE));
     }
     switch(scale_factor)
     {
         case ScaleFactor::NONE:
             _scale_factor = 1.f;
             _unit         = "ns";
             break;
         case ScaleFactor::TIME_US:
             _scale_factor = 1000.f;
             _unit         = "us";
             break;
         case ScaleFactor::TIME_MS:
             _scale_factor = 1000000.f;
             _unit         = "ms";
             break;
         case ScaleFactor::TIME_S:
             _scale_factor = 1000000000.f;
             _unit         = "s";
             break;
         default:
             ARM_COMPUTE_ERROR("Invalid scale");
     }
 }
References ARM_COMPUTE_ERROR, CLScheduler::get(), arm_compute::test::framework::NONE, CLScheduler::queue(), CLScheduler::set_queue(), arm_compute::test::framework::TIME_MS, arm_compute::test::framework::TIME_S, and arm_compute::test::framework::TIME_US.
Member Function Documentation
id()
std::string id () const override virtual
Identifier for the instrument.
Implements Instrument.
Definition at line 43 of file OpenCLTimer.cpp.
 {
     if(output_timestamps)
     {
         return "OpenCLTimestamps";
     }
     else
     {
         return "OpenCLTimer";
     }
 }
measurements()
Instrument::MeasurementsMap measurements () const override virtual
Return the latest measurements.
Returns
the latest measurements.
Reimplemented from Instrument.
Definition at line 184 of file OpenCLTimer.cpp.
 {
     MeasurementsMap measurements;
     unsigned int    kernel_number = 0;
     for(auto kernel : _kernels)
     {
         cl_ulong queued, flushed, start, end;
         kernel.event.getProfilingInfo(CL_PROFILING_COMMAND_QUEUED, &queued);
         kernel.event.getProfilingInfo(CL_PROFILING_COMMAND_SUBMIT, &flushed);
         kernel.event.getProfilingInfo(CL_PROFILING_COMMAND_START, &start);
         kernel.event.getProfilingInfo(CL_PROFILING_COMMAND_END, &end);
         std::string name = kernel.name + " #" + support::cpp11::to_string(kernel_number++);
         if(output_timestamps)
         {
             measurements.emplace("[start]" + name, Measurement(start / static_cast<cl_ulong>(_scale_factor), _unit));
             measurements.emplace("[queued]" + name, Measurement(queued / static_cast<cl_ulong>(_scale_factor), _unit));
             measurements.emplace("[flushed]" + name, Measurement(flushed / static_cast<cl_ulong>(_scale_factor), _unit));
             measurements.emplace("[end]" + name, Measurement(end / static_cast<cl_ulong>(_scale_factor), _unit));
         }
         else
         {
             measurements.emplace(name, Measurement((end - start) / _scale_factor, _unit));
         }
     }
     return measurements;
 }
References arm_compute::support::cpp11::to_string().
start()
void start () override virtual
Start measuring.
Called just before the run of the test starts
Reimplemented from Instrument.
Definition at line 162 of file OpenCLTimer.cpp.
 {
     _kernels.clear();
     _timer_enabled = true;
 }
stop()
void stop () override virtual
Stop measuring.
Called just after the run of the test ends
Reimplemented from Instrument.
Definition at line 168 of file OpenCLTimer.cpp.
 {
     _timer_enabled = false;
 }
test_measurements()
Instrument::MeasurementsMap test_measurements () const override virtual
Return the latest test measurements.
Returns
the latest test measurements.
Reimplemented from Instrument.
Definition at line 214 of file OpenCLTimer.cpp.
 {
     MeasurementsMap measurements;
     if(output_timestamps)
     {
         // The OpenCL clock and the wall clock are not in sync, so we use
         // this trick to calculate the offset between the two clocks:
         ::cl::Event event;
         cl_ulong    now_gpu;
         // Enqueue retrieve current CPU clock and enqueue a dummy marker
         std::chrono::high_resolution_clock::time_point now_cpu = std::chrono::high_resolution_clock::now();
         CLScheduler::get().queue().enqueueMarker(&event);
         CLScheduler::get().queue().finish();
         //Access the time at which the marker was enqueued:
         event.getProfilingInfo(CL_PROFILING_COMMAND_QUEUED, &now_gpu);
         measurements.emplace("Now Wall clock", Measurement(now_cpu.time_since_epoch().count() / 1000, "us"));
         measurements.emplace("Now OpenCL", Measurement(now_gpu / static_cast<cl_ulong>(_scale_factor), _unit));
     }
     return measurements;
 }
References CLScheduler::get(), and CLScheduler::queue().
test_start()
void test_start () override virtual
Start of the test.
Called before the test set up starts
Reimplemented from Instrument.
Definition at line 90 of file OpenCLTimer.cpp.
 {
     // Start intercepting enqueues:
     ARM_COMPUTE_ERROR_ON(_real_function != nullptr);
     ARM_COMPUTE_ERROR_ON(_real_graph_function != nullptr);
     _real_function       = CLSymbols::get().clEnqueueNDRangeKernel_ptr;
     _real_graph_function = graph::TaskExecutor::get().execute_function;
     auto interceptor     = [this](
                                cl_command_queue command_queue,
                                cl_kernel        kernel,
                                cl_uint          work_dim,
                                const size_t    *gwo,
                                const size_t    *gws,
                                const size_t    *lws,
                                cl_uint          num_events_in_wait_list,
                                const cl_event * event_wait_list,
                                cl_event *       event)
     {
         if(this->_timer_enabled)
         {
             kernel_info       info;
             cl::Kernel        cpp_kernel(kernel, true);
             std::stringstream ss;
             ss << this->_prefix << cpp_kernel.getInfo<CL_KERNEL_FUNCTION_NAME>();
             if(gws != nullptr)
             {
                 ss << " GWS[" << gws[0] << "," << gws[1] << "," << gws[2] << "]";
             }
             if(lws != nullptr)
             {
                 ss << " LWS[" << lws[0] << "," << lws[1] << "," << lws[2] << "]";
             }
             info.name = ss.str();
             cl_event tmp;
             cl_int   retval = this->_real_function(command_queue, kernel, work_dim, gwo, gws, lws, num_events_in_wait_list, event_wait_list, &tmp);
             info.event      = tmp;
             this->_kernels.push_back(std::move(info));
             if(event != nullptr)
             {
                 //return cl_event from the intercepted call
                 clRetainEvent(tmp);
                 *event = tmp;
             }
             return retval;
         }
         else
         {
             return this->_real_function(command_queue, kernel, work_dim, gwo, gws, lws, num_events_in_wait_list, event_wait_list, event);
         }
     };
     // Start intercepting tasks:
     auto task_interceptor = [this](graph::ExecutionTask & task)
     {
         if(task.node != nullptr && !task.node->name().empty())
         {
             this->_prefix = task.node->name() + "/";
         }
         else
         {
             this->_prefix = "";
         }
         this->_real_graph_function(task);
         this->_prefix = "";
     };
     CLSymbols::get().clEnqueueNDRangeKernel_ptr = interceptor;
     graph::TaskExecutor::get().execute_function = task_interceptor;
 }
References ARM_COMPUTE_ERROR_ON, CLSymbols::clEnqueueNDRangeKernel_ptr, clRetainEvent(), TaskExecutor::execute_function, TaskExecutor::get(), CLSymbols::get(), and arm_compute::test::validation::info.
test_stop()
void test_stop () override virtual
End of the test.
Called after the test teardown ended
Reimplemented from Instrument.
Definition at line 174 of file OpenCLTimer.cpp.
 {
     // Restore real function
     CLSymbols::get().clEnqueueNDRangeKernel_ptr = _real_function;
     graph::TaskExecutor::get().execute_function = _real_graph_function;
     _real_graph_function                        = nullptr;
     _real_function                              = nullptr;
 }
References CLSymbols::clEnqueueNDRangeKernel_ptr, TaskExecutor::execute_function, TaskExecutor::get(), and CLSymbols::get().
The documentation for this class was generated from the following files:
tests/framework/instruments/OpenCLTimer.h
tests/framework/instruments/OpenCLTimer.cpp