Compute Library: NEHOGBlockNormalizationKernel Class Reference
NEHOGBlockNormalizationKernel Class Reference
NEON kernel to perform HOG block normalization.
#include <NEHOGDescriptorKernel.h>
Public Member Functions
const char * name () const override
Name of the kernel.
NEHOGBlockNormalizationKernel ()
Default constructor.
NEHOGBlockNormalizationKernel (const NEHOGBlockNormalizationKernel &)=delete
Prevent instances of this class from being copied (As this class contains pointers)
NEHOGBlockNormalizationKernel & operator= (const NEHOGBlockNormalizationKernel &)=delete
Prevent instances of this class from being copied (As this class contains pointers)
NEHOGBlockNormalizationKernel (NEHOGBlockNormalizationKernel &&)=default
Allow instances of this class to be moved.
NEHOGBlockNormalizationKernel & operator= (NEHOGBlockNormalizationKernel &&)=default
Allow instances of this class to be moved.
~NEHOGBlockNormalizationKernel ()=default
Default destructor.
void configure (const ITensor *input, ITensor *output, const HOGInfo *hog_info)
Initialise the kernel's input, output and HOG's metadata.
void run (const Window &window, const ThreadInfo &info) override
Execute the kernel on the passed window.
Public Member Functions inherited from ICPPKernel
virtual ~ICPPKernel ()=default
Default destructor.
Public Member Functions inherited from IKernel
IKernel ()
Constructor.
virtual ~IKernel ()=default
Destructor.
virtual bool is_parallelisable () const
Indicates whether or not the kernel is parallelisable.
virtual BorderSize border_size () const
The size of the border for that kernel.
const Window & window () const
The maximum window the kernel can be executed on.
Detailed Description
NEON kernel to perform HOG block normalization.
Definition at line 95 of file NEHOGDescriptorKernel.h.
Constructor & Destructor Documentation
NEHOGBlockNormalizationKernel() [1/3]
NEHOGBlockNormalizationKernel ()
Default constructor.
Definition at line 709 of file NEHOGDescriptorKernel.cpp.
     : _func(nullptr), _input(nullptr), _output(nullptr), _num_cells_per_block(), _num_cells_per_block_stride(), _num_bins(0), _l2_hyst_threshold(0.0f)
 {
 }
NEHOGBlockNormalizationKernel() [2/3]
NEHOGBlockNormalizationKernel (const NEHOGBlockNormalizationKernel &) delete
Prevent instances of this class from being copied (As this class contains pointers)
NEHOGBlockNormalizationKernel() [3/3]
NEHOGBlockNormalizationKernel (NEHOGBlockNormalizationKernel &&) default
Allow instances of this class to be moved.
~NEHOGBlockNormalizationKernel()
~NEHOGBlockNormalizationKernel () default
Default destructor.
Member Function Documentation
configure()
void configure (const ITensor * input, ITensor * output, const HOGInfo * hog_info)
Initialise the kernel's input, output and HOG's metadata.
Parameters
[in] input Input tensor which stores the local HOG for each cell. Data type supported: F32. Number of channels supported: equal to the number of histogram bins per cell
[out] output Output tensor which stores the normalised blocks. Data type supported: F32. Number of channels supported: equal to the number of histogram bins per block
[in] hog_info HOG's metadata
Definition at line 714 of file NEHOGDescriptorKernel.cpp.
 {
     ARM_COMPUTE_ERROR_ON(hog_info == nullptr);
     ARM_COMPUTE_ERROR_ON_DATA_TYPE_CHANNEL_NOT_IN(input, hog_info->num_bins(), DataType::F32);
     ARM_COMPUTE_ERROR_ON_DATA_TYPE_NOT_IN(output, DataType::F32);
     // Number of cells per block
     const Size2D num_cells_per_block(hog_info->block_size().width / hog_info->cell_size().width,
                                      hog_info->block_size().height / hog_info->cell_size().height);
     // Number of cells per block stride
     const Size2D num_cells_per_block_stride(hog_info->block_stride().width / hog_info->cell_size().width,
                                             hog_info->block_stride().height / hog_info->cell_size().height);
     _input                      = input;
     _output                     = output;
     _l2_hyst_threshold          = hog_info->l2_hyst_threshold();
     _num_cells_per_block        = num_cells_per_block;
     _num_cells_per_block_stride = num_cells_per_block_stride;
     _num_bins                   = hog_info->num_bins();
     ARM_COMPUTE_ERROR_ON((output->info()->num_channels() != (_num_bins * num_cells_per_block.width * num_cells_per_block.height)));
     switch(hog_info->normalization_type())
     {
         case HOGNormType::L2_NORM:
             _func = &l2_norm;
             break;
         case HOGNormType::L2HYS_NORM:
             _func = &l2hys_norm;
             break;
         case HOGNormType::L1_NORM:
             _func = &l1_norm;
             break;
         default:
             ARM_COMPUTE_ERROR_ON("Normalisation type not supported");
             break;
     }
     constexpr unsigned int num_elems_processed_per_iteration = 1;
     const unsigned int     num_elems_read_per_iteration      = 1;
     const unsigned int     num_rows_read_per_iteration       = _num_cells_per_block.height;
     const unsigned int     num_elems_written_per_iteration   = 1;
     const unsigned int     num_rows_written_per_iteration    = _num_cells_per_block.height;
     // Configure kernel window
     Window                win = calculate_max_window(*output->info(), Steps(num_elems_processed_per_iteration));
     AccessWindowRectangle output_access(output->info(), 0, 0, num_elems_written_per_iteration, num_rows_written_per_iteration);
     update_window_and_padding(win,
                               AccessWindowRectangle(input->info(), 0, 0, num_elems_read_per_iteration, num_rows_read_per_iteration),
                               output_access);
     output_access.set_valid_region(win, ValidRegion(Coordinates(), output->info()->tensor_shape()));
     INEKernel::configure(win);
 }
References ARM_COMPUTE_ERROR_ON, ARM_COMPUTE_ERROR_ON_DATA_TYPE_CHANNEL_NOT_IN, ARM_COMPUTE_ERROR_ON_DATA_TYPE_NOT_IN, HOGInfo::block_size(), HOGInfo::block_stride(), arm_compute::calculate_max_window(), HOGInfo::cell_size(), arm_compute::F32, Size2D::height, ITensor::info(), arm_compute::L1_NORM, HOGInfo::l2_hyst_threshold(), arm_compute::L2_NORM, arm_compute::L2HYS_NORM, HOGInfo::normalization_type(), HOGInfo::num_bins(), ITensorInfo::num_channels(), ITensorInfo::tensor_shape(), arm_compute::update_window_and_padding(), and Size2D::width.
Referenced by NEHOGDescriptor::configure().
name()
const char* name () const inline override virtual
Name of the kernel.
Returns
Kernel name
Implements ICPPKernel.
Definition at line 98 of file NEHOGDescriptorKernel.h.
     {
         return "NEHOGBlockNormalizationKernel";
     }
operator=() [1/2]
NEHOGBlockNormalizationKernel& operator= (const NEHOGBlockNormalizationKernel &) delete
Prevent instances of this class from being copied (As this class contains pointers)
operator=() [2/2]
NEHOGBlockNormalizationKernel& operator= (NEHOGBlockNormalizationKernel &&) default
Allow instances of this class to be moved.
run()
void run (const Window & window, const ThreadInfo & info) override virtual
Execute the kernel on the passed window.
Warning
If is_parallelisable() returns false then the passed window must be equal to window()
Note
The window has to be a region within the window returned by the window() method
The width of the window has to be a multiple of num_elems_processed_per_iteration().
Parameters
[in] window Region on which to execute the kernel. (Must be a region of the window returned by window())
[in] info Info about executing thread and CPU.
Implements ICPPKernel.
Definition at line 772 of file NEHOGDescriptorKernel.cpp.
 {
     ARM_COMPUTE_UNUSED(info);
     ARM_COMPUTE_ERROR_ON_UNCONFIGURED_KERNEL(this);
     ARM_COMPUTE_ERROR_ON(_func == nullptr);
     ARM_COMPUTE_ERROR_ON_INVALID_SUBWINDOW(IKernel::window(), window);
     // Get number of bins per block
     const size_t num_bins_per_block = _output->info()->num_channels();
     // Number of bins on the same row of the block
     const int32_t num_bins_per_block_x = _num_cells_per_block.width * _num_bins;
     const size_t input_stride = _input->info()->strides_in_bytes()[Window::DimY] / data_size_from_type(_input->info()->data_type());
     Window win_in(window);
     win_in.set_dimension_step(Window::DimX, _num_cells_per_block_stride.width);
     win_in.set(Window::DimY, Window::Dimension(0, 0, 0));
     Iterator in(_input, win_in);
     Iterator out(_output, window);
     // Normalises blocks
     execute_window_loop(window, [&](const Coordinates & id)
     {
         const auto input_row_ptr = reinterpret_cast<const float *>(in.ptr() + id.y() * _num_cells_per_block_stride.height * _input->info()->strides_in_bytes()[Window::DimY]);
         const auto out_row_ptr   = reinterpret_cast<float *>(out.ptr());
         // Execute normalization function
         (*_func)(input_row_ptr, out_row_ptr, input_stride, _num_cells_per_block.height, num_bins_per_block_x, num_bins_per_block, _l2_hyst_threshold);
     },
     in, out);
 }
References ARM_COMPUTE_ERROR_ON, ARM_COMPUTE_ERROR_ON_INVALID_SUBWINDOW, ARM_COMPUTE_ERROR_ON_UNCONFIGURED_KERNEL, ARM_COMPUTE_UNUSED, arm_compute::data_size_from_type(), ITensorInfo::data_type(), Window::DimX, Window::DimY, arm_compute::execute_window_loop(), Size2D::height, ITensor::info(), arm_compute::test::validation::info, ITensorInfo::num_channels(), Iterator::ptr(), ITensorInfo::strides_in_bytes(), Size2D::width, and IKernel::window().
The documentation for this class was generated from the following files:
arm_compute/core/NEON/kernels/NEHOGDescriptorKernel.h
src/core/NEON/kernels/NEHOGDescriptorKernel.cpp