Compute Library: AlexNetNormalizationLayerDataset Class Reference
AlexNetNormalizationLayerDataset Class Reference final
#include <AlexNetNormalizationLayerDataset.h>
Public Member Functions
AlexNetNormalizationLayerDataset ()
AlexNetNormalizationLayerDataset (AlexNetNormalizationLayerDataset &&)=default
~AlexNetNormalizationLayerDataset ()=default
Public Member Functions inherited from CartesianProductDataset< framework::dataset::InitializerListDataset< TensorShape >, framework::dataset::SingletonDataset< NormalizationLayerInfo > >
CartesianProductDataset (framework::dataset::InitializerListDataset< TensorShape > &&dataset1, framework::dataset::SingletonDataset< NormalizationLayerInfo > &&dataset2)
Construct dataset from the given datasets.
CartesianProductDataset (CartesianProductDataset &&)=default
iterator begin () const
Iterator pointing at the begin of the dataset.
int size () const
Size of the dataset.
Public Member Functions inherited from Dataset
Dataset (Dataset &&)=default
Additional Inherited Members
Public Types inherited from CartesianProductDataset< framework::dataset::InitializerListDataset< TensorShape >, framework::dataset::SingletonDataset< NormalizationLayerInfo > >
using type = decltype(std::tuple_cat(*std::declval< iter1_type >(),*std::declval< iter2_type >()))
Type of the dataset.
Detailed Description
Definition at line 40 of file AlexNetNormalizationLayerDataset.h.
Constructor & Destructor Documentation
AlexNetNormalizationLayerDataset () inline
Definition at line 44 of file AlexNetNormalizationLayerDataset.h.
References arm_compute::CROSS_MAP, arm_compute::test::framework::dataset::make(), arm_compute::U, and AlexNetNormalizationLayerDataset::~AlexNetNormalizationLayerDataset().
         : CartesianProductDataset
     {
         framework::dataset::make("Shape", { TensorShape(55U, 55U, 96U), TensorShape(27U, 27U, 256U) }),
         framework::dataset::make("Info", NormalizationLayerInfo(NormType::CROSS_MAP, 5, 0.0001f, 0.75f))
     }
     {
     }
AlexNetNormalizationLayerDataset (AlexNetNormalizationLayerDataset &&) default
~AlexNetNormalizationLayerDataset () default
Referenced by AlexNetNormalizationLayerDataset::AlexNetNormalizationLayerDataset().
The documentation for this class was generated from the following file:
tests/datasets/system_tests/alexnet/AlexNetNormalizationLayerDataset.h