Compute Library: ICLMultiHOG Class Reference
ICLMultiHOG Class Reference abstract
Interface for storing multiple HOG data-objects.
#include <ICLMultiHOG.h>
Public Member Functions
virtual ICLHOG * cl_model (size_t index)=0
Return a pointer to the requested OpenCL HOG model.
virtual const ICLHOG * cl_model (size_t index) const =0
Return a constant pointer to the requested OpenCL HOG model.
IHOG * model (size_t index) override
Return a pointer to the requested HOG model.
const IHOG * model (size_t index) const override
Return a const pointer to the requested HOG model.
Public Member Functions inherited from IMultiHOG
virtual ~IMultiHOG ()=default
Default destructor.
virtual size_t num_models () const =0
The number of HOG models stored.
Detailed Description
Interface for storing multiple HOG data-objects.
Definition at line 33 of file ICLMultiHOG.h.
Member Function Documentation
cl_model() [1/2]
virtual ICLHOG* cl_model (size_t index) pure virtual
Return a pointer to the requested OpenCL HOG model.
Parameters
[in] index The index of the wanted OpenCL HOG model.
Returns
A pointer pointed to the HOG model
Implemented in CLMultiHOG.
Referenced by CLHOGMultiDetection::configure(), and ICLMultiHOG::model().
cl_model() [2/2]
virtual const ICLHOG* cl_model (size_t index) const pure virtual
Return a constant pointer to the requested OpenCL HOG model.
Parameters
[in] index The index of the wanted OpenCL HOG model.
Returns
A constant pointer pointed to the OpenCL HOG model
Implemented in CLMultiHOG.
model() [1/2]
IHOG * model (size_t index) override virtual
Return a pointer to the requested HOG model.
Parameters
[in] index The index of the wanted HOG model.
Returns
A pointer pointed to the HOG model
Implements IMultiHOG.
Definition at line 30 of file ICLMultiHOG.cpp.
 {
     return cl_model(index);
 }
References ICLMultiHOG::cl_model().
Referenced by CLHOGMultiDetection::configure().
model() [2/2]
const IHOG * model (size_t index) const override virtual
Return a const pointer to the requested HOG model.
Parameters
[in] index The index of the wanted HOG model.
Returns
A const pointer pointed to the HOG model
Implements IMultiHOG.
Definition at line 35 of file ICLMultiHOG.cpp.
 {
     return cl_model(index);
 }
References ICLMultiHOG::cl_model().
The documentation for this class was generated from the following files:
arm_compute/core/CL/ICLMultiHOG.h
src/core/CL/ICLMultiHOG.cpp