Compute Library: NEConvolutionRectangleKernel Class Reference
NEConvolutionRectangleKernel Class Reference
Kernel for the running convolution on a rectangle matrix.
#include <NEConvolutionKernel.h>
Public Member Functions
const char * name () const override
Name of the kernel.
NEConvolutionRectangleKernel ()
Default constructor.
NEConvolutionRectangleKernel (NEConvolutionRectangleKernel &)=delete
Prevent instances of this class from being copied (As this class contains pointers)
NEConvolutionRectangleKernel & operator= (NEConvolutionRectangleKernel &)=delete
Prevent instances of this class from being copied (As this class contains pointers)
NEConvolutionRectangleKernel (NEConvolutionRectangleKernel &&)=default
Allow instances of this class to be moved.
NEConvolutionRectangleKernel & operator= (NEConvolutionRectangleKernel &&)=default
Allow instances of this class to be moved.
void configure (const ITensor *input, ITensor *output, const int16_t *conv, uint32_t width, uint32_t height, uint32_t scale, bool border_undefined)
Initialise the kernel's input, output and border mode.
void run (const Window &window, const ThreadInfo &info) override
Execute the kernel on the passed window.
BorderSize border_size () const override
The size of the border for that kernel.
Public Member Functions inherited from ICPPKernel
virtual ~ICPPKernel ()=default
Default destructor.
Public Member Functions inherited from IKernel
IKernel ()
Constructor.
virtual ~IKernel ()=default
Destructor.
virtual bool is_parallelisable () const
Indicates whether or not the kernel is parallelisable.
const Window & window () const
The maximum window the kernel can be executed on.
Detailed Description
Kernel for the running convolution on a rectangle matrix.
Note
Supports combinations of 3,5,7 and 9.
Definition at line 212 of file NEConvolutionKernel.h.
Constructor & Destructor Documentation
NEConvolutionRectangleKernel() [1/3]
NEConvolutionRectangleKernel ()
Default constructor.
Definition at line 1417 of file NEConvolutionKernel.cpp.
     : _input(nullptr), _output(nullptr), _scale(0), _convolution(), _border_size(), _func_idx(0)
 {
 }
NEConvolutionRectangleKernel() [2/3]
NEConvolutionRectangleKernel (NEConvolutionRectangleKernel &) delete
Prevent instances of this class from being copied (As this class contains pointers)
NEConvolutionRectangleKernel() [3/3]
NEConvolutionRectangleKernel (NEConvolutionRectangleKernel &&) default
Allow instances of this class to be moved.
Member Function Documentation
border_size()
BorderSize border_size () const override virtual
The size of the border for that kernel.
Returns
The width in number of elements of the border.
Reimplemented from IKernel.
Definition at line 1422 of file NEConvolutionKernel.cpp.
 {
     return _border_size;
 }
configure()
void configure (const ITensor * input, ITensor * output, const int16_t * conv, uint32_t width, uint32_t height, uint32_t scale, bool border_undefined)
Initialise the kernel's input, output and border mode.
Parameters
[in] input Source tensor. Data type supported: U8.
[out] output Destination tensor, Data types supported: U8, S16.
[in] conv Convolution matrix to apply to the input tensor.
[in] width Width of convolution matrix (Number of columns)
[in] height Height of convolution matrix (Number of rows)
[in] scale Scale of the convolution matrix. If 0 is passed, it will be set to the sum of the coefficients of the convolution or 1 if they add up to 0.
[in] border_undefined True if the border mode is undefined. False if it's replicate or constant.
Definition at line 1427 of file NEConvolutionKernel.cpp.
 {
     ARM_COMPUTE_ERROR_ON_NULLPTR(input, output, conv);
     set_shape_if_empty(*output->info(), input->info()->tensor_shape());
     ARM_COMPUTE_ERROR_ON_MISMATCHING_SHAPES(input, output);
     ARM_COMPUTE_ERROR_ON_DATA_TYPE_CHANNEL_NOT_IN(input, 1, DataType::U8);
     ARM_COMPUTE_ERROR_ON_DATA_TYPE_CHANNEL_NOT_IN(output, 1, DataType::U8, DataType::S16);
     ARM_COMPUTE_ERROR_ON(width != 3 && width != 5 && width != 7 && width != 9);
     ARM_COMPUTE_ERROR_ON(height != 3 && height != 5 && height != 7 && height != 9);
     ARM_COMPUTE_ERROR_ON(0 == scale);
     _input       = input;
     _output      = output;
     _scale       = scale;
     _border_size = BorderSize(height / 2, width / 2);
     // Setup the convolution matrix
     const uint32_t nr_elements = width * height;
     _convolution.resize(nr_elements);
     std::copy_n(conv, nr_elements, _convolution.begin());
     // Set function index to help choose appropriate function in run()
     _func_idx = get_index(height) * 4 + get_index(width);
     ARM_COMPUTE_ERROR_ON(_func_idx > (_nr_supported_sizes * _nr_supported_sizes));
     // Configure kernel window
     constexpr unsigned int num_elems_processed_per_iteration = 8;
     constexpr unsigned int num_elems_read_per_iteration      = 16;
     constexpr unsigned int num_elems_written_per_iteration   = 8;
     Window                 win = calculate_max_window(*input->info(), Steps(num_elems_processed_per_iteration), border_undefined, _border_size);
     AccessWindowHorizontal output_access(output->info(), 0, num_elems_written_per_iteration);
     update_window_and_padding(win,
                               AccessWindowRectangle(input->info(), -_border_size.left, -_border_size.top, num_elems_read_per_iteration, height),
                               output_access);
     output_access.set_valid_region(win, input->info()->valid_region(), border_undefined, _border_size);
     INEKernel::configure(win);
 }
References ARM_COMPUTE_ERROR_ON, ARM_COMPUTE_ERROR_ON_DATA_TYPE_CHANNEL_NOT_IN, ARM_COMPUTE_ERROR_ON_MISMATCHING_SHAPES, ARM_COMPUTE_ERROR_ON_NULLPTR, arm_compute::calculate_max_window(), arm_compute::test::validation::conv, ITensor::info(), BorderSize::left, arm_compute::S16, arm_compute::test::validation::scale, arm_compute::set_shape_if_empty(), ITensorInfo::tensor_shape(), BorderSize::top, arm_compute::U8, arm_compute::update_window_and_padding(), and ITensorInfo::valid_region().
name()
const char* name () const inline override virtual
Name of the kernel.
Returns
Kernel name
Implements ICPPKernel.
Definition at line 215 of file NEConvolutionKernel.h.
     {
         return "NEConvolutionRectangleKernel";
     }
operator=() [1/2]
NEConvolutionRectangleKernel& operator= (NEConvolutionRectangleKernel &) delete
Prevent instances of this class from being copied (As this class contains pointers)
operator=() [2/2]
NEConvolutionRectangleKernel& operator= (NEConvolutionRectangleKernel &&) default
Allow instances of this class to be moved.
run()
void run (const Window & window, const ThreadInfo & info) override virtual
Execute the kernel on the passed window.
Warning
If is_parallelisable() returns false then the passed window must be equal to window()
Note
The window has to be a region within the window returned by the window() method
The width of the window has to be a multiple of num_elems_processed_per_iteration().
Parameters
[in] window Region on which to execute the kernel. (Must be a region of the window returned by window())
[in] info Info about executing thread and CPU.
Implements ICPPKernel.
Definition at line 1471 of file NEConvolutionKernel.cpp.
 {
     ARM_COMPUTE_UNUSED(info);
     ARM_COMPUTE_ERROR_ON_UNCONFIGURED_KERNEL(this);
     ARM_COMPUTE_ERROR_ON_INVALID_SUBWINDOW(INEKernel::window(), window);
     using ConvolutionRectangleFunction = void (NEConvolutionRectangleKernel::*)(const Window & window);
     // uint8_t function table
     static const std::array<ConvolutionRectangleFunction, 16> func_table_u8 =
     {
         {
             &NEConvolutionRectangleKernel::convolution<uint8_t, 3, 3>,
             &NEConvolutionRectangleKernel::convolution<uint8_t, 3, 5>,
             &NEConvolutionRectangleKernel::convolution<uint8_t, 3, 7>,
             &NEConvolutionRectangleKernel::convolution<uint8_t, 3, 9>,
             &NEConvolutionRectangleKernel::convolution<uint8_t, 5, 3>,
             &NEConvolutionRectangleKernel::convolution<uint8_t, 5, 5>,
             &NEConvolutionRectangleKernel::convolution<uint8_t, 5, 7>,
             &NEConvolutionRectangleKernel::convolution<uint8_t, 5, 9>,
             &NEConvolutionRectangleKernel::convolution<uint8_t, 7, 3>,
             &NEConvolutionRectangleKernel::convolution<uint8_t, 7, 5>,
             &NEConvolutionRectangleKernel::convolution<uint8_t, 7, 7>,
             &NEConvolutionRectangleKernel::convolution<uint8_t, 7, 9>,
             &NEConvolutionRectangleKernel::convolution<uint8_t, 9, 3>,
             &NEConvolutionRectangleKernel::convolution<uint8_t, 9, 5>,
             &NEConvolutionRectangleKernel::convolution<uint8_t, 9, 7>,
             &NEConvolutionRectangleKernel::convolution<uint8_t, 9, 9>
         }
     };
     // int16_t function table
     static const std::array<ConvolutionRectangleFunction, 16> func_table_s16 =
     {
         {
             &NEConvolutionRectangleKernel::convolution<int16_t, 3, 3>,
             &NEConvolutionRectangleKernel::convolution<int16_t, 3, 5>,
             &NEConvolutionRectangleKernel::convolution<int16_t, 3, 7>,
             &NEConvolutionRectangleKernel::convolution<int16_t, 3, 9>,
             &NEConvolutionRectangleKernel::convolution<int16_t, 5, 3>,
             &NEConvolutionRectangleKernel::convolution<int16_t, 5, 5>,
             &NEConvolutionRectangleKernel::convolution<int16_t, 5, 7>,
             &NEConvolutionRectangleKernel::convolution<int16_t, 5, 9>,
             &NEConvolutionRectangleKernel::convolution<int16_t, 7, 3>,
             &NEConvolutionRectangleKernel::convolution<int16_t, 7, 5>,
             &NEConvolutionRectangleKernel::convolution<int16_t, 7, 7>,
             &NEConvolutionRectangleKernel::convolution<int16_t, 7, 9>,
             &NEConvolutionRectangleKernel::convolution<int16_t, 9, 3>,
             &NEConvolutionRectangleKernel::convolution<int16_t, 9, 5>,
             &NEConvolutionRectangleKernel::convolution<int16_t, 9, 7>,
             &NEConvolutionRectangleKernel::convolution<int16_t, 9, 9>
         }
     };
     // Run appropriate function
     switch(_output->info()->data_type())
     {
         case DataType::U8:
             ARM_COMPUTE_ERROR_ON(_func_idx >= func_table_u8.size());
             (this->*func_table_u8[_func_idx])(window);
             break;
         case DataType::S16:
             ARM_COMPUTE_ERROR_ON(_func_idx >= func_table_s16.size());
             (this->*func_table_s16[_func_idx])(window);
             break;
         default:
             ARM_COMPUTE_ERROR("Not supported");
     }
 }
References ARM_COMPUTE_ERROR, ARM_COMPUTE_ERROR_ON, ARM_COMPUTE_ERROR_ON_INVALID_SUBWINDOW, ARM_COMPUTE_ERROR_ON_UNCONFIGURED_KERNEL, ARM_COMPUTE_UNUSED, ITensorInfo::data_type(), ITensor::info(), arm_compute::test::validation::info, arm_compute::S16, arm_compute::U8, and IKernel::window().
The documentation for this class was generated from the following files:
arm_compute/core/NEON/kernels/NEConvolutionKernel.h
src/core/NEON/kernels/NEConvolutionKernel.cpp