Compute Library: SplitLayerNode Class Reference
SplitLayerNode Class Reference final
Split Layer node.
#include <SplitLayerNode.h>
Public Member Functions
SplitLayerNode (unsigned int num_splits, unsigned int axis=0)
Default Constructor.
unsigned int num_splits () const
Number of splits accessor.
unsigned int axis () const
Split axis accessor.
Status validate () const override
Validate node.
NodeType type () const override
Returns node's type.
bool forward_descriptors () override
Forwards descriptor information to outputs if possible.
TensorDescriptor configure_output (size_t idx) const override
Calculates output configuration.
void accept (INodeVisitor &v) override
Accepts a node visitor.
Public Member Functions inherited from INode
INode ()
Constructor.
virtual ~INode ()=default
Destructor.
INode (const INode &)=delete
Prevent instances of this class from being copied (As this class contains pointers)
INode & operator= (const INode &)=delete
Prevent instances of this class from being copy assigned (As this class contains pointers)
INode (INode &&)=default
Allow instances of this class to be moved.
INode & operator= (INode &&)=default
Allow instances of this class to be move assigned.
std::string name () const
Returns node's name.
NodeID id () const
Returns node's ID.
const Graph * graph () const
Returns node's Graph.
Graph * graph ()
Returns node's Graph.
void set_graph (Graph *g)
Sets the graph that this node is registered to.
void set_id (NodeID id)
Sets the node id.
void set_common_node_parameters (NodeParams common_params)
Sets common node parameters.
void set_requested_target (Target target)
Sets target preference.
void set_assigned_target (Target target)
Sets the final execution target.
void set_output_tensor (TensorID tid, size_t idx)
Sets the output tensor of at a given index.
const std::vector< TensorID > & inputs () const
Returns inputs of the node.
const std::vector< TensorID > & outputs () const
Returns outputs of the node.
const std::vector< EdgeID > & input_edges () const
Returns input edge set.
const std::set< EdgeID > & output_edges () const
Returns output edge set.
TensorID input_id (size_t idx) const
Returns the tensor ID of a given input of the node.
TensorID output_id (size_t idx) const
Returns the tensor ID of a given output of the node.
Tensor * input (size_t idx) const
Returns the tensor of a given input of the node.
Tensor * output (size_t idx) const
Returns the tensor of a given output of the node.
EdgeID input_edge_id (size_t idx) const
Returns the edge ID of a given input of the node.
Edge * input_edge (size_t idx) const
Returns the edge of a given input of the node.
size_t num_inputs () const
Returns number of inputs of the node.
size_t num_outputs () const
Returns number of outputs of the node.
NodeParams common_node_params () const
Returns common node parameters.
Target requested_target () const
Returns requested target for this node.
Target assigned_target () const
Returns assigned target for this node.
Static Public Member Functions
static std::pair< TensorDescriptor, Coordinates > compute_output_descriptor (const TensorDescriptor &input_descriptor, unsigned int num_splits, unsigned int axis, unsigned int idx)
Computes split layer output descriptor.
Detailed Description
Split Layer node.
Definition at line 36 of file SplitLayerNode.h.
Constructor & Destructor Documentation
SplitLayerNode()
SplitLayerNode (unsigned int num_splits, unsigned int axis = 0)
Default Constructor.
Parameters
[in] num_splits Number of splits
[in] axis (Optional) Axis to split on. Supported axis >= 2. Defaults to 0
Definition at line 34 of file SplitLayerNode.cpp.
     : _num_splits(num_splits), _axis(axis)
 {
     _input_edges.resize(1, EmptyEdgeID);
     _outputs.resize(num_splits, NullTensorID);
 }
References arm_compute::graph::EmptyEdgeID, arm_compute::graph::NullTensorID, and SplitLayerNode::num_splits().
Member Function Documentation
accept()
void accept (INodeVisitor & v) override virtual
Accepts a node visitor.
Parameters
[in] v Visitor to accept
Implements INode.
Definition at line 113 of file SplitLayerNode.cpp.
 {
     v.visit(*this);
 }
References INodeVisitor::visit().
axis()
unsigned int axis () const
Split axis accessor.
Returns
Split axis
Definition at line 46 of file SplitLayerNode.cpp.
 {
     return _axis;
 }
Referenced by SplitLayerNode::compute_output_descriptor().
compute_output_descriptor()
std::pair< TensorDescriptor, Coordinates > compute_output_descriptor (const TensorDescriptor & input_descriptor, unsigned int num_splits, unsigned int axis, unsigned int idx) static
Computes split layer output descriptor.
Parameters
[in] input_descriptor Descriptor of the input tensor
[in] num_splits Number of splits
[in] axis Axis to perform the split on
[in] idx Index of the split
Returns
A pair with the descriptor of the split and the starting coordinates
Definition at line 51 of file SplitLayerNode.cpp.
 {
     const unsigned int split_size = input_descriptor.shape[axis] / num_splits;
     TensorDescriptor output_descriptor = input_descriptor;
     output_descriptor.shape.set(axis, split_size);
     Coordinates coords;
     coords.set(axis, idx * split_size);
     return std::make_pair(output_descriptor, coords);
 }
References SplitLayerNode::axis(), SplitLayerNode::num_splits(), Dimensions< T >::set(), TensorShape::set(), and TensorDescriptor::shape.
Referenced by SplitLayerNode::configure_output(), and SplitLayerSubTensorMutator::mutate().
configure_output()
TensorDescriptor configure_output (size_t idx) const override virtual
Calculates output configuration.
Parameters
[in] idx Output index to configure
Returns
Output descriptor configuration
Implements INode.
Definition at line 84 of file SplitLayerNode.cpp.
 {
     ARM_COMPUTE_UNUSED(idx);
     ARM_COMPUTE_ERROR_ON(idx >= _outputs.size());
     const Tensor *src = input(0);
     ARM_COMPUTE_ERROR_ON(src == nullptr);
     TensorDescriptor output_info;
     std::tie(output_info, std::ignore) = compute_output_descriptor(src->desc(), _num_splits, _axis, idx);
     return output_info;
 }
References ARM_COMPUTE_ERROR_ON, ARM_COMPUTE_UNUSED, SplitLayerNode::compute_output_descriptor(), INode::input(), arm_compute::test::validation::output_info, and arm_compute::test::validation::src.
Referenced by SplitLayerNode::forward_descriptors().
forward_descriptors()
bool forward_descriptors () override virtual
Forwards descriptor information to outputs if possible.
Returns
True if descriptor information could be forwarded otherwise false
Implements INode.
Definition at line 65 of file SplitLayerNode.cpp.
 {
     if(input_id(0) != NullTensorID)
     {
         validate();
         for(unsigned int i = 0; i < _outputs.size(); ++i)
         {
             if(output_id(i) != NullTensorID)
             {
                 Tensor *dst_i = output(i);
                 ARM_COMPUTE_ERROR_ON(dst_i == nullptr);
                 dst_i->desc() = configure_output(i);
             }
         }
         return true;
     }
     return false;
 }
References ARM_COMPUTE_ERROR_ON, SplitLayerNode::configure_output(), Tensor::desc(), INode::input_id(), arm_compute::graph::NullTensorID, INode::output(), INode::output_id(), and SplitLayerNode::validate().
num_splits()
unsigned int num_splits () const
Number of splits accessor.
Returns
Number of splits
Definition at line 41 of file SplitLayerNode.cpp.
 {
     return _num_splits;
 }
Referenced by SplitLayerNode::compute_output_descriptor(), and SplitLayerNode::SplitLayerNode().
type()
NodeType type () const override virtual
Returns node's type.
Returns
Node's type
Implements INode.
Definition at line 108 of file SplitLayerNode.cpp.
 {
     return NodeType::SplitLayer;
 }
References arm_compute::graph::SplitLayer.
validate()
Status validate () const override virtual
Validate node.
Returns
Status containing any errors
Reimplemented from INode.
Definition at line 98 of file SplitLayerNode.cpp.
 {
     const Tensor *src = input(0);
     ARM_COMPUTE_RETURN_ERROR_ON(src == nullptr);
     ARM_COMPUTE_RETURN_ERROR_ON(_axis >= src->desc().shape.num_dimensions());
     ARM_COMPUTE_RETURN_ERROR_ON_MSG(src->desc().shape[_axis] % _num_splits, "Split should be exact");
     return Status{};
 }
References ARM_COMPUTE_RETURN_ERROR_ON, ARM_COMPUTE_RETURN_ERROR_ON_MSG, INode::input(), and arm_compute::test::validation::src.
Referenced by SplitLayerNode::forward_descriptors().
The documentation for this class was generated from the following files:
arm_compute/graph/nodes/SplitLayerNode.h
src/graph/nodes/SplitLayerNode.cpp