Compute Library: NESobel5x5VertKernel Class Reference
NESobel5x5VertKernel Class Reference
Interface for the kernel to run the vertical pass of 5x5 Sobel Y filter on a tensor.
#include <NESobel5x5Kernel.h>
Public Member Functions
const char * name () const override
Name of the kernel.
NESobel5x5VertKernel ()
Default constructor.
NESobel5x5VertKernel (const NESobel5x5VertKernel &)=delete
Prevent instances of this class from being copied (As this class contains pointers)
NESobel5x5VertKernel & operator= (const NESobel5x5VertKernel &)=delete
Prevent instances of this class from being copied (As this class contains pointers)
NESobel5x5VertKernel (NESobel5x5VertKernel &&)=default
Allow instances of this class to be moved.
NESobel5x5VertKernel & operator= (NESobel5x5VertKernel &&)=default
Allow instances of this class to be moved.
~NESobel5x5VertKernel ()=default
Default destructor.
void configure (ITensor *input_x, ITensor *input_y, ITensor *output_x, ITensor *output_y, bool border_undefined)
Initialise the kernel's source, destination and border mode.
void run (const Window &window, const ThreadInfo &info) override
Execute the kernel on the passed window.
BorderSize border_size () const override
The size of the border for that kernel.
Public Member Functions inherited from ICPPKernel
virtual ~ICPPKernel ()=default
Default destructor.
Public Member Functions inherited from IKernel
IKernel ()
Constructor.
virtual ~IKernel ()=default
Destructor.
virtual bool is_parallelisable () const
Indicates whether or not the kernel is parallelisable.
const Window & window () const
The maximum window the kernel can be executed on.
Detailed Description
Interface for the kernel to run the vertical pass of 5x5 Sobel Y filter on a tensor.
Definition at line 83 of file NESobel5x5Kernel.h.
Constructor & Destructor Documentation
NESobel5x5VertKernel() [1/3]
NESobel5x5VertKernel ()
Default constructor.
Definition at line 207 of file NESobel5x5Kernel.cpp.
     : _input_x(nullptr), _input_y(nullptr), _output_x(nullptr), _output_y(nullptr), _run_sobel_x(false), _run_sobel_y(false)
 {
 }
NESobel5x5VertKernel() [2/3]
NESobel5x5VertKernel (const NESobel5x5VertKernel &) delete
Prevent instances of this class from being copied (As this class contains pointers)
NESobel5x5VertKernel() [3/3]
NESobel5x5VertKernel (NESobel5x5VertKernel &&) default
Allow instances of this class to be moved.
~NESobel5x5VertKernel()
~NESobel5x5VertKernel () default
Default destructor.
Member Function Documentation
border_size()
BorderSize border_size () const override virtual
The size of the border for that kernel.
Returns
The width in number of elements of the border.
Reimplemented from IKernel.
Definition at line 212 of file NESobel5x5Kernel.cpp.
 {
     return BorderSize{ 2, 0 };
 }
Referenced by NESobel5x5VertKernel::configure().
configure()
void configure (ITensor * input_x, ITensor * input_y, ITensor * output_x, ITensor * output_y, bool border_undefined)
Initialise the kernel's source, destination and border mode.
Parameters
[in] input_x Input for X (X output of hor pass). Data type supported: S16.
[in] input_y Input for Y (Y output of hor pass). Data type supported: S16.
[out] output_x Destination tensor for the X gradient. Data type supported: S16.
[out] output_y Destination tensor for the Y gradient. Data type supported: S16.
[in] border_undefined True if the border mode is undefined. False if it's replicate or constant.
Definition at line 217 of file NESobel5x5Kernel.cpp.
 {
     ARM_COMPUTE_ERROR_ON((output_x == nullptr) && (output_y == nullptr));
     _run_sobel_x = output_x != nullptr;
     _run_sobel_y = output_y != nullptr;
     if(_run_sobel_x)
     {
         ARM_COMPUTE_ERROR_ON_FORMAT_NOT_IN(input_x, Format::S16);
         ARM_COMPUTE_ERROR_ON_FORMAT_NOT_IN(output_x, Format::S16);
     }
     if(_run_sobel_y)
     {
         ARM_COMPUTE_ERROR_ON_FORMAT_NOT_IN(input_y, Format::S16);
         ARM_COMPUTE_ERROR_ON_FORMAT_NOT_IN(output_y, Format::S16);
     }
     _input_x  = input_x;
     _input_y  = input_y;
     _output_x = output_x;
     _output_y = output_y;
     const ITensor *const input = _run_sobel_x ? input_x : input_y;
     // Configure kernel window
     constexpr unsigned int num_elems_processed_per_iteration = 16;
     constexpr unsigned int num_elems_read_per_iteration      = 16;
     constexpr unsigned int num_elems_written_per_iteration   = 16;
     constexpr unsigned int num_rows_read_per_iteration       = 5;
     Window                 win = calculate_max_window(*input->info(), Steps(num_elems_processed_per_iteration), border_undefined, border_size());
     AccessWindowHorizontal output_x_access(output_x == nullptr ? nullptr : output_x->info(), 0, num_elems_written_per_iteration);
     AccessWindowHorizontal output_y_access(output_y == nullptr ? nullptr : output_y->info(), 0, num_elems_written_per_iteration);
     update_window_and_padding(win,
                               AccessWindowRectangle(input_x == nullptr ? nullptr : input_x->info(), 0, -border_size().top, num_elems_read_per_iteration, num_rows_read_per_iteration),
                               AccessWindowRectangle(input_y == nullptr ? nullptr : input_y->info(), 0, -border_size().top, num_elems_read_per_iteration, num_rows_read_per_iteration),
                               output_x_access,
                               output_y_access);
     output_x_access.set_valid_region(win, input->info()->valid_region(), border_undefined, border_size());
     output_y_access.set_valid_region(win, input->info()->valid_region(), border_undefined, border_size());
     INEKernel::configure(win);
 }
References ARM_COMPUTE_ERROR_ON, ARM_COMPUTE_ERROR_ON_FORMAT_NOT_IN, NESobel5x5VertKernel::border_size(), arm_compute::calculate_max_window(), ITensor::info(), arm_compute::S16, BorderSize::top, arm_compute::update_window_and_padding(), and ITensorInfo::valid_region().
Referenced by NESobel5x5::configure().
name()
const char* name () const inline override virtual
Name of the kernel.
Returns
Kernel name
Implements ICPPKernel.
Definition at line 86 of file NESobel5x5Kernel.h.
     {
         return "NESobel5x5VertKernel";
     }
operator=() [1/2]
NESobel5x5VertKernel& operator= (const NESobel5x5VertKernel &) delete
Prevent instances of this class from being copied (As this class contains pointers)
operator=() [2/2]
NESobel5x5VertKernel& operator= (NESobel5x5VertKernel &&) default
Allow instances of this class to be moved.
run()
void run (const Window & window, const ThreadInfo & info) override virtual
Execute the kernel on the passed window.
Warning
If is_parallelisable() returns false then the passed window must be equal to window()
Note
The window has to be a region within the window returned by the window() method
The width of the window has to be a multiple of num_elems_processed_per_iteration().
Parameters
[in] window Region on which to execute the kernel. (Must be a region of the window returned by window())
[in] info Info about executing thread and CPU.
Implements ICPPKernel.
Definition at line 265 of file NESobel5x5Kernel.cpp.
 {
     ARM_COMPUTE_UNUSED(info);
     ARM_COMPUTE_ERROR_ON_UNCONFIGURED_KERNEL(this);
     ARM_COMPUTE_ERROR_ON_INVALID_SUBWINDOW(INEKernel::window(), window);
     Iterator input_x;
     Iterator input_y;
     Iterator output_x;
     Iterator output_y;
     const int16_t *input_x_low2_ptr = nullptr;
     const int16_t *input_x_low_ptr  = nullptr;
     const int16_t *input_x_mid_ptr  = nullptr;
     const int16_t *input_x_top_ptr  = nullptr;
     const int16_t *input_x_top2_ptr = nullptr;
     const int16_t *input_y_low2_ptr = nullptr;
     const int16_t *input_y_low_ptr  = nullptr;
     const int16_t *input_y_top_ptr  = nullptr;
     const int16_t *input_y_top2_ptr = nullptr;
     if(_run_sobel_x)
     {
         input_x          = Iterator(_input_x, window);
         output_x         = Iterator(_output_x, window);
         input_x_top2_ptr = reinterpret_cast<const int16_t *>(_input_x->ptr_to_element(Coordinates(0, -2)));
         input_x_top_ptr  = reinterpret_cast<const int16_t *>(_input_x->ptr_to_element(Coordinates(0, -1)));
         input_x_mid_ptr  = reinterpret_cast<const int16_t *>(_input_x->ptr_to_element(Coordinates(0, 0)));
         input_x_low_ptr  = reinterpret_cast<const int16_t *>(_input_x->ptr_to_element(Coordinates(0, 1)));
         input_x_low2_ptr = reinterpret_cast<const int16_t *>(_input_x->ptr_to_element(Coordinates(0, 2)));
     }
     if(_run_sobel_y)
     {
         input_y          = Iterator(_input_y, window);
         output_y         = Iterator(_output_y, window);
         input_y_top2_ptr = reinterpret_cast<const int16_t *>(_input_y->ptr_to_element(Coordinates(0, -2)));
         input_y_top_ptr  = reinterpret_cast<const int16_t *>(_input_y->ptr_to_element(Coordinates(0, -1)));
         input_y_low_ptr  = reinterpret_cast<const int16_t *>(_input_y->ptr_to_element(Coordinates(0, 1)));
         input_y_low2_ptr = reinterpret_cast<const int16_t *>(_input_y->ptr_to_element(Coordinates(0, 2)));
     }
     static const int16x8_t six      = vdupq_n_s16(6);
     static const int16x8_t four     = vdupq_n_s16(4);
     static const int16x8_t two      = vdupq_n_s16(2);
     static const int16x8_t minustwo = vdupq_n_s16(-2);
     if(_run_sobel_x)
     {
         execute_window_loop(window, [&](const Coordinates &)
         {
             // Convert offset from uint8_t* to uint16_t*
             const size_t input_offset_high_s16 = input_x.offset() / 2;
             const size_t input_offset_low_s16  = input_offset_high_s16 + 8;
             //HIGH DATA
             //top2
             int16x8_t data_high = vld1q_s16(input_x_top2_ptr + input_offset_high_s16);
             int16x8_t out_high  = data_high;
             //top
             data_high = vld1q_s16(input_x_top_ptr + input_offset_high_s16);
             out_high  = vmlaq_s16(out_high, data_high, four);
             //mid
             data_high = vld1q_s16(input_x_mid_ptr + input_offset_high_s16);
             out_high  = vmlaq_s16(out_high, data_high, six);
             //low
             data_high = vld1q_s16(input_x_low_ptr + input_offset_high_s16);
             out_high  = vmlaq_s16(out_high, data_high, four);
             //low2
             data_high = vld1q_s16(input_x_low2_ptr + input_offset_high_s16);
             out_high  = vaddq_s16(out_high, data_high);
             vst1q_s16((reinterpret_cast<int16_t *>(output_x.ptr())), out_high);
             //LOW DATA
             //top2
             int16x8_t data_low = vld1q_s16(input_x_top2_ptr + input_offset_low_s16);
             int16x8_t out_low  = data_low;
             //top
             data_low = vld1q_s16(input_x_top_ptr + input_offset_low_s16);
             out_low  = vmlaq_s16(out_low, data_low, four);
             //mid
             data_low = vld1q_s16(input_x_mid_ptr + input_offset_low_s16);
             out_low  = vmlaq_s16(out_low, data_low, six);
             //low
             data_low = vld1q_s16(input_x_low_ptr + input_offset_low_s16);
             out_low  = vmlaq_s16(out_low, data_low, four);
             //low2
             data_low = vld1q_s16(input_x_low2_ptr + input_offset_low_s16);
             out_low  = vaddq_s16(out_low, data_low);
             vst1q_s16((reinterpret_cast<int16_t *>(output_x.ptr())) + 8, out_low);
         },
         input_x, output_x);
     }
     if(_run_sobel_y)
     {
         execute_window_loop(window, [&](const Coordinates &)
         {
             // Convert offset from uint8_t* to uint16_t*
             const size_t input_offset_high_s16 = input_y.offset() / 2;
             const size_t input_offset_low_s16  = input_offset_high_s16 + 8;
             //HIGH DATA
             //top2
             int16x8_t data_high = vld1q_s16(input_y_top2_ptr + input_offset_high_s16);
             int16x8_t out_high  = vnegq_s16(data_high);
             //top
             data_high = vld1q_s16(input_y_top_ptr + input_offset_high_s16);
             out_high  = vmlaq_s16(out_high, data_high, minustwo);
             //low
             data_high = vld1q_s16(input_y_low_ptr + input_offset_high_s16);
             out_high  = vmlaq_s16(out_high, data_high, two);
             //low2
             data_high = vld1q_s16(input_y_low2_ptr + input_offset_high_s16);
             out_high  = vaddq_s16(out_high, data_high);
             vst1q_s16((reinterpret_cast<int16_t *>(output_y.ptr())), out_high);
             //LOW DATA
             //top2
             int16x8_t data_low = vld1q_s16(input_y_top2_ptr + input_offset_low_s16);
             int16x8_t out_low  = vnegq_s16(data_low);
             //top
             data_low = vld1q_s16(input_y_top_ptr + input_offset_low_s16);
             out_low  = vmlaq_s16(out_low, data_low, minustwo);
             //low
             data_low = vld1q_s16(input_y_low_ptr + input_offset_low_s16);
             out_low  = vmlaq_s16(out_low, data_low, two);
             //low2
             data_low = vld1q_s16(input_y_low2_ptr + input_offset_low_s16);
             out_low  = vaddq_s16(out_low, data_low);
             vst1q_s16((reinterpret_cast<int16_t *>(output_y.ptr())) + 8, out_low);
         },
         input_y, output_y);
     }
 }
References ARM_COMPUTE_ERROR_ON_INVALID_SUBWINDOW, ARM_COMPUTE_ERROR_ON_UNCONFIGURED_KERNEL, ARM_COMPUTE_UNUSED, arm_compute::execute_window_loop(), arm_compute::test::validation::info, Iterator::offset(), Iterator::ptr(), ITensor::ptr_to_element(), and IKernel::window().
The documentation for this class was generated from the following files:
arm_compute/core/NEON/kernels/NESobel5x5Kernel.h
src/core/NEON/kernels/NESobel5x5Kernel.cpp