Compute Library: CLArray< T > Class Template Reference
CLArray< T > Class Template Reference
CLArray implementation.
#include <CLArray.h>
Public Member Functions
CLArray ()
Default constructor: empty array.
CLArray (const CLArray &)=delete
Prevent instances of this class from being copied (As this class contains pointers)
CLArray & operator= (const CLArray &)=delete
Prevent instances of this class from being copied (As this class contains pointers)
CLArray (CLArray &&)=default
Allow instances of this class to be move constructed.
CLArray & operator= (CLArray &&)=default
Allow instances of this class to be moved.
CLArray (size_t max_num_values)
Constructor: initializes an array which can contain up to max_num_points values.
void map (bool blocking=true)
Enqueue a map operation of the allocated buffer.
void unmap ()
Enqueue an unmap operation of the allocated and mapped buffer.
const cl::Buffer & cl_buffer () const override
Interface to be implemented by the child class to return a reference to the OpenCL buffer containing the array's data.
Public Member Functions inherited from ICLArray< T >
ICLArray (size_t max_num_values)
Constructor.
ICLArray (const ICLArray &)=delete
Prevent instances of this class from being copy constructed.
ICLArray & operator= (const ICLArray &)=delete
Prevent instances of this class from being copied.
ICLArray (ICLArray &&)=default
Allow instances of this class to be move constructed.
ICLArray & operator= (ICLArray &&)=default
Allow instances of this class to be moved.
virtual ~ICLArray ()=default
Default virtual destructor.
void map (cl::CommandQueue &q, bool blocking=true)
Enqueue a map operation of the allocated buffer on the given queue.
void unmap (cl::CommandQueue &q)
Enqueue an unmap operation of the allocated and mapped buffer on the given queue.
T * buffer () const override
Pointer to the first element of the array.
Public Member Functions inherited from IArray< T >
IArray ()
Default constructor.
IArray (size_t max_num_values)
Constructor: initializes an array which can contain up to max_num_points values.
size_t max_num_values () const
Maximum number of values which can be stored in this array.
virtual ~IArray ()=default
Default virtual destructor.
size_t num_values () const
Number of values currently stored in the array.
bool push_back (const T &val)
Append the passed argument to the end of the array if there is room.
void clear ()
Clear all the points from the array.
bool overflow () const
Did we lose some values because the array is too small?
virtual T & at (size_t index) const
Reference to the element of the array located at the given index.
void resize (size_t num)
Resizes the array to contain "num" elements.
Detailed Description
template<class T>
class arm_compute::CLArray< T >
CLArray implementation.
Definition at line 37 of file CLArray.h.
Constructor & Destructor Documentation
CLArray() [1/4]
CLArray () inline
Default constructor: empty array.
Definition at line 41 of file CLArray.h.
         : ICLArray<T>(0), _buffer()
     {
     }
CLArray() [2/4]
CLArray (const CLArray< T > &) delete
Prevent instances of this class from being copied (As this class contains pointers)
CLArray() [3/4]
CLArray (CLArray< T > &&) default
Allow instances of this class to be move constructed.
CLArray() [4/4]
CLArray (size_t max_num_values) inline
Constructor: initializes an array which can contain up to max_num_points values.
Parameters
[in] max_num_values Maximum number of values the array will be able to stored
Definition at line 57 of file CLArray.h.
         : ICLArray<T>(max_num_values), _buffer(CLScheduler::get().context(), CL_MEM_ALLOC_HOST_PTR | CL_MEM_READ_WRITE, max_num_values * sizeof(T))
     {
     }
Member Function Documentation
cl_buffer()
const cl::Buffer& cl_buffer () const inline override virtual
Interface to be implemented by the child class to return a reference to the OpenCL buffer containing the array's data.
Returns
A reference to an OpenCL buffer containing the array's data.
Implements ICLArray< T >.
Definition at line 84 of file CLArray.h.
     {
         return _buffer;
     }
map()
void map (bool blocking = true) inline
Enqueue a map operation of the allocated buffer.
Parameters
[in] blocking If true, then the mapping will be ready to use by the time this method returns, else it is the caller's responsibility to flush the queue and wait for the mapping operation to have completed.
Definition at line 67 of file CLArray.h.
     {
         ICLArray<T>::map(CLScheduler::get().queue(), blocking);
     }
References CLScheduler::get(), and ICLArray< T >::map().
operator=() [1/2]
CLArray& operator= (const CLArray< T > &) delete
Prevent instances of this class from being copied (As this class contains pointers)
operator=() [2/2]
CLArray& operator= (CLArray< T > &&) default
Allow instances of this class to be moved.
unmap()
void unmap () inline
Enqueue an unmap operation of the allocated and mapped buffer.
Note
This method simply enqueues the unmap operation, it is the caller's responsibility to flush the queue and make sure the unmap is finished before the memory is accessed by the device.
Definition at line 77 of file CLArray.h.
     {
         ICLArray<T>::unmap(CLScheduler::get().queue());
     }
References CLScheduler::get(), and ICLArray< T >::unmap().
The documentation for this class was generated from the following file:
arm_compute/runtime/CL/CLArray.h