Compute Library: GCWeightsReshapeKernel Class Reference
GCWeightsReshapeKernel Class Reference
GLES Compute kernel to perform reshaping on the weights used by convolution and locally connected layer.
#include <GCWeightsReshapeKernel.h>
Public Member Functions
GCWeightsReshapeKernel ()
Constructor.
GCWeightsReshapeKernel (const GCWeightsReshapeKernel &)=delete
Prevent instances of this class from being copied (As this class contains pointers)
GCWeightsReshapeKernel & operator= (const GCWeightsReshapeKernel &)=delete
Prevent instances of this class from being copied (As this class contains pointers)
GCWeightsReshapeKernel (GCWeightsReshapeKernel &&)=default
Allow instances of this class to be moved.
GCWeightsReshapeKernel & operator= (GCWeightsReshapeKernel &&)=default
Allow instances of this class to be moved.
~GCWeightsReshapeKernel ()=default
Default destructor.
void configure (const IGCTensor *input, const IGCTensor *biases, IGCTensor *output)
Set the input and output of the kernel.
void run (const Window &window) override
Enqueue the OpenGL ES shader to process the given window.
Public Member Functions inherited from IGCKernel
IGCKernel ()
Constructor.
GCKernel & kernel ()
Returns a reference to the GLES kernel of this object.
void add_1D_tensor_argument (unsigned int &idx, const IGCTensor *tensor, const unsigned int binding_point, const Window &window)
Add the passed 1D tensor's parameters to the object's kernel's arguments starting from the index idx.
void add_2D_tensor_argument (unsigned int &idx, const IGCTensor *tensor, const unsigned int binding_point, const Window &window)
Add the passed 2D tensor's parameters to the object's kernel's arguments starting from the index idx.
void add_3D_tensor_argument (unsigned int &idx, const IGCTensor *tensor, const unsigned int binding_point, const Window &window)
Add the passed 3D tensor's parameters to the object's kernel's arguments starting from the index idx.
unsigned int num_arguments_per_1D_tensor () const
Returns the number of arguments enqueued per 1D tensor object.
unsigned int num_arguments_per_2D_tensor () const
Returns the number of arguments enqueued per 2D tensor object.
unsigned int num_arguments_per_3D_tensor () const
Returns the number of arguments enqueued per 3D tensor object.
void set_lws_hint (gles::NDRange &lws_hint)
Set the Local-Workgroup-Size hint.
void set_target (GPUTarget target)
Set the targeted GPU architecture.
GPUTarget get_target () const
Get the targeted GPU architecture.
Public Member Functions inherited from IKernel
IKernel ()
Constructor.
virtual ~IKernel ()=default
Destructor.
virtual bool is_parallelisable () const
Indicates whether or not the kernel is parallelisable.
virtual BorderSize border_size () const
The size of the border for that kernel.
const Window & window () const
The maximum window the kernel can be executed on.
Detailed Description
GLES Compute kernel to perform reshaping on the weights used by convolution and locally connected layer.
Rearranges each 3-dimensional kernel to a single row leading to a matrix with linearized kernels. In combination with the GCIm2ColKernel can transform a convolution to a matrix multiplication.
For example assuming a 3D weight kernel of 3x3 dimensions and depth of 2 we have:
\[ \left(\begin{array}{ccc} a000 & a001 & a002 \\ a010 & a011 & a012 \\ a020 & a021 & a022 \\ \end{array} \right) \left(\begin{array}{ccc} a100 & a101 & a102 \\ a110 & a111 & a112 \\ a120 & a121 & a122 \\ \end{array} \right) \rightarrow \left(\begin{array}{ccccccccc} a000 & a001 & a002 & a010 & a011 & a012 & a020 & a021 & a022 & a100 & a101 & a102 & a110 & a111 & a112 & a120 & a121 & a122 \\ \end{array} \right) \]
Definition at line 54 of file GCWeightsReshapeKernel.h.
Constructor & Destructor Documentation
GCWeightsReshapeKernel() [1/3]
GCWeightsReshapeKernel ()
Constructor.
Definition at line 41 of file GCWeightsReshapeKernel.cpp.
     : _input(nullptr), _biases(nullptr), _output(nullptr)
 {
 }
GCWeightsReshapeKernel() [2/3]
GCWeightsReshapeKernel (const GCWeightsReshapeKernel &) delete
Prevent instances of this class from being copied (As this class contains pointers)
GCWeightsReshapeKernel() [3/3]
GCWeightsReshapeKernel (GCWeightsReshapeKernel &&) default
Allow instances of this class to be moved.
~GCWeightsReshapeKernel()
~GCWeightsReshapeKernel () default
Default destructor.
Member Function Documentation
configure()
void configure (const IGCTensor * input, const IGCTensor * biases, IGCTensor * output)
Set the input and output of the kernel.
Parameters
[in] input The input tensor to convert. Weights are 4D tensor with dimensions [kernel_x, kernel_y, IFM, OFM] if shared, and 5D tensor with dimensions [kernel_x, kernel_y, IFM, OFM, batches] if unshared. Data types supported: F16, F32
[in] biases The shared biases tensor to append. Bias is 1D tensor with dimensions [OFM] if shared and 2D tensor with dimensions [OFM, batches] if unshared. Data types supported: Same as input
Warning
Appending biases to weights reshaped matrix is not supported for quantized asymmetric types.
Parameters
[out] output The output tensor. Should be a 2D Tensor. Data types supported: Same as input
Definition at line 46 of file GCWeightsReshapeKernel.cpp.
 {
     ARM_COMPUTE_ERROR_ON_DATA_TYPE_CHANNEL_NOT_IN(input, 1, DataType::F16, DataType::F32);
     ARM_COMPUTE_ERROR_ON_NULLPTR(output);
     // Output tensor auto inizialitation if not yet initialized
     auto_init_if_empty(*output->info(), input->info()->clone()->set_tensor_shape(compute_weights_reshaped_shape(*input->info(), (biases != nullptr))));
     ARM_COMPUTE_ERROR_ON_MISMATCHING_DATA_TYPES(input, output);
     if(biases != nullptr)
     {
         ARM_COMPUTE_ERROR_ON_MISMATCHING_DATA_TYPES(input, biases);
         ARM_COMPUTE_ERROR_ON((input->info()->num_dimensions() == 4) && (biases->info()->num_dimensions() != 1));
         ARM_COMPUTE_ERROR_ON((input->info()->num_dimensions() == 5) && (biases->info()->num_dimensions() != 2));
         ARM_COMPUTE_ERROR_ON((input->info()->num_dimensions() == 4) && (biases->info()->dimension(0) != input->info()->tensor_shape()[3]));
         ARM_COMPUTE_ERROR_ON((input->info()->num_dimensions() == 5) && (biases->info()->dimension(0) != input->info()->tensor_shape()[3] || biases->info()->dimension(1) != input->info()->tensor_shape()[4]));
     }
     _biases = biases;
     _output = output;
     _input  = input;
     // Create build options
     std::set<std::string> build_opts;
     std::string           dt_name = (input->info()->data_type() == DataType::F32) ? "DATA_TYPE_FP32" : "DATA_TYPE_FP16";
     build_opts.emplace("#define " + dt_name);
     build_opts.emplace("#define LOCAL_SIZE_X " + support::cpp11::to_string(1));
     build_opts.emplace("#define LOCAL_SIZE_Y " + support::cpp11::to_string(1));
     build_opts.emplace("#define LOCAL_SIZE_Z " + support::cpp11::to_string(1));
     build_opts.emplace("#define RESHAPE_TO_COLUMNS");
     if(biases != nullptr)
     {
         build_opts.emplace("#define HAS_BIAS");
     }
     // Create kernel
     _kernel = static_cast<GCKernel>(GCKernelLibrary::get().create_kernel("reshape_to_columns", build_opts));
     // Set static arguments
     unsigned int idx = num_arguments_per_3D_tensor() + num_arguments_per_2D_tensor();
     idx += (biases != nullptr) ? num_arguments_per_1D_tensor() : 0;
     _kernel.set_argument(idx++, _input->info()->dimension(0));
     _kernel.set_argument(idx++, _input->info()->dimension(1));
     _kernel.set_argument(idx++, _input->info()->dimension(2));
     _kernel.set_argument(idx++, _input->info()->dimension(3));
     // Configure window
     Window win = calculate_max_window(*input->info(), Steps());
     // The GCWeightsReshapeKernel doesn't need padding so update_window_and_padding() can be skipped
     output->info()->set_valid_region(ValidRegion(Coordinates(), output->info()->tensor_shape()));
     IGCKernel::configure(win);
 }
References ARM_COMPUTE_ERROR_ON, ARM_COMPUTE_ERROR_ON_DATA_TYPE_CHANNEL_NOT_IN, ARM_COMPUTE_ERROR_ON_MISMATCHING_DATA_TYPES, ARM_COMPUTE_ERROR_ON_NULLPTR, arm_compute::auto_init_if_empty(), arm_compute::calculate_max_window(), ICloneable< T >::clone(), arm_compute::misc::shape_calculator::compute_weights_reshaped_shape(), arm_compute::create_kernel(), ITensorInfo::data_type(), ITensorInfo::dimension(), arm_compute::F16, arm_compute::F32, GCKernelLibrary::get(), ITensor::info(), IGCKernel::num_arguments_per_1D_tensor(), IGCKernel::num_arguments_per_2D_tensor(), IGCKernel::num_arguments_per_3D_tensor(), ITensorInfo::num_dimensions(), ITensorInfo::set_valid_region(), ITensorInfo::tensor_shape(), and arm_compute::support::cpp11::to_string().
Referenced by GCConvolutionLayerReshapeWeights::configure().
operator=() [1/2]
GCWeightsReshapeKernel& operator= (const GCWeightsReshapeKernel &) delete
Prevent instances of this class from being copied (As this class contains pointers)
operator=() [2/2]
GCWeightsReshapeKernel& operator= (GCWeightsReshapeKernel &&) default
Allow instances of this class to be moved.
run()
void run (const Window & window) override virtual
Enqueue the OpenGL ES shader to process the given window.
Parameters
[in] window Region on which to execute the kernel. (Must be a valid region of the window returned by window()).
Implements IGCKernel.
Definition at line 101 of file GCWeightsReshapeKernel.cpp.
 {
     ARM_COMPUTE_ERROR_ON_UNCONFIGURED_KERNEL(this);
     ARM_COMPUTE_ERROR_ON_MISMATCHING_WINDOWS(IGCKernel::window(), window);
     Window out_window;
     out_window.use_tensor_dimensions(_output->info()->tensor_shape());
     Window in_slice  = window.first_slice_window_3D();
     Window out_slice = out_window.first_slice_window_2D();
     Window biases_window;
     Window biases_slice;
     if(_biases != nullptr)
     {
         biases_window.use_tensor_dimensions(_biases->info()->tensor_shape());
         biases_slice = biases_window.first_slice_window_1D();
     }
     _kernel.use();
     do
     {
         // Set arguments
         unsigned idx = 0;
         add_3D_tensor_argument(idx, _input, 1, in_slice);
         add_2D_tensor_argument(idx, _output, 2, out_slice);
         if(_biases != nullptr)
         {
             add_1D_tensor_argument(idx, _biases, 3, biases_slice);
             biases_window.slide_window_slice_1D(biases_slice);
         }
         _kernel.update_shader_params();
         // Run kernel
         enqueue(*this, in_slice);
     }
     while(window.slide_window_slice_4D(in_slice) && out_window.slide_window_slice_2D(out_slice));
 }
References IGCKernel::add_1D_tensor_argument(), IGCKernel::add_2D_tensor_argument(), IGCKernel::add_3D_tensor_argument(), ARM_COMPUTE_ERROR_ON_MISMATCHING_WINDOWS, ARM_COMPUTE_ERROR_ON_UNCONFIGURED_KERNEL, arm_compute::enqueue(), Window::first_slice_window_1D(), Window::first_slice_window_2D(), Window::first_slice_window_3D(), ITensor::info(), Window::slide_window_slice_1D(), Window::slide_window_slice_2D(), Window::slide_window_slice_4D(), ITensorInfo::tensor_shape(), Window::use_tensor_dimensions(), and IKernel::window().
The documentation for this class was generated from the following files:
arm_compute/core/GLES_COMPUTE/kernels/GCWeightsReshapeKernel.h
src/core/GLES_COMPUTE/kernels/GCWeightsReshapeKernel.cpp