Compute Library: NEDepthConcatenateLayer Class Reference
NEDepthConcatenateLayer Class Reference
Basic function to execute concatenate tensors along z axis.
#include <NEDepthConcatenateLayer.h>
Public Member Functions
NEDepthConcatenateLayer ()
Default constructor.
void configure (const std::vector< ITensor * > &inputs_vector, ITensor *output)
Initialise the kernel's inputs vector and output.
void run () override
Run the kernels contained in the function.
Public Member Functions inherited from IFunction
virtual ~IFunction ()=default
Destructor.
virtual void prepare ()
Prepare the function for executing.
Static Public Member Functions
static Status validate (const std::vector< ITensorInfo * > &inputs_vector, const ITensorInfo *output)
Static function to check if given info will lead to a valid configuration of NEDepthConcatenateLayer.
Detailed Description
Basic function to execute concatenate tensors along z axis.
This function calls the following kernels:
NEFillBorderKernel (executed if input's lowest two dimensions are smaller than respective output's dimensions)
NEDepthConcatenateLayerKernel
Definition at line 45 of file NEDepthConcatenateLayer.h.
Constructor & Destructor Documentation
NEDepthConcatenateLayer()
NEDepthConcatenateLayer ()
Default constructor.
Definition at line 38 of file NEDepthConcatenateLayer.cpp.
     : _inputs_vector(),
       _concat_kernels_vector(),
       _border_handlers_vector(),
       _num_inputs(0)
 {
 }
Member Function Documentation
configure()
void configure (const std::vector< ITensor * > & inputs_vector, ITensor * output)
Initialise the kernel's inputs vector and output.
Parameters
[in,out] inputs_vector The vectors containing all the tensors to concatenate. Data types supported: QASYMM8/F16/F32. Input dimensions might differ for each input for the first three dimensions (width, height, depth) and must match for the rest. Note that the difference between the minimum and maximum width and height among the input tensors must be divisible by 2 otherwise it is not clear how padding should be added on the inputs' width and height when they are less than the maximum input sizes.
[out] output Output tensor. Data types supported: Same as input. Output tensor dimensions match the inputs' ones from the fourth dimension and above, while width and height are the maximum width and height of the input tensors. Finally, depth is the sum of the input depths.
Definition at line 46 of file NEDepthConcatenateLayer.cpp.
 {
     _num_inputs             = inputs_vector.size();
     _concat_kernels_vector  = arm_compute::support::cpp14::make_unique<NEDepthConcatenateLayerKernel[]>(_num_inputs);
     _border_handlers_vector = arm_compute::support::cpp14::make_unique<NEFillBorderKernel[]>(_num_inputs);
     std::vector<ITensorInfo *> inputs_vector_info;
     for(unsigned int i = 0; i < _num_inputs; i++)
     {
         inputs_vector_info.emplace_back(inputs_vector.at(i)->info());
     }
     TensorShape output_shape = arm_compute::misc::shape_calculator::calculate_depth_concatenate_shape(inputs_vector_info);
     // Output auto inizialitation if not yet initialized
     auto_init_if_empty(*output->info(), output_shape, 1, inputs_vector[0]->info()->data_type());
     ARM_COMPUTE_ERROR_THROW_ON(NEDepthConcatenateLayer::validate(inputs_vector_info, output->info()));
     unsigned int depth_offset = 0;
     for(unsigned int i = 0; i < _num_inputs; ++i)
     {
         _concat_kernels_vector[i].configure(inputs_vector.at(i), depth_offset, output);
         _border_handlers_vector[i].configure(inputs_vector.at(i), _concat_kernels_vector[i].border_size(), BorderMode::CONSTANT, PixelValue(static_cast<float>(0.f)));
         depth_offset += inputs_vector.at(i)->info()->dimension(2);
     }
     // Set valid region from shape
     output->info()->set_valid_region(ValidRegion(Coordinates(), output_shape));
 }
References ARM_COMPUTE_ERROR_THROW_ON, arm_compute::auto_init_if_empty(), arm_compute::misc::shape_calculator::calculate_depth_concatenate_shape(), arm_compute::CONSTANT, ITensor::info(), arm_compute::test::validation::output_shape, ITensorInfo::set_valid_region(), and NEDepthConcatenateLayer::validate().
run()
void run () override virtual
Run the kernels contained in the function.
For NEON kernels:
Multi-threading is used for the kernels which are parallelisable.
By default std::thread::hardware_concurrency() threads are used.
Note
CPPScheduler::set_num_threads() can be used to manually set the number of threads
For OpenCL kernels:
All the kernels are enqueued on the queue associated with CLScheduler.
The queue is then flushed.
Note
The function will not block until the kernels are executed. It is the user's responsibility to wait.
Will call prepare() on first run if hasn't been done
Implements IFunction.
Definition at line 97 of file NEDepthConcatenateLayer.cpp.
 {
     for(unsigned i = 0; i < _num_inputs; ++i)
     {
         NEScheduler::get().schedule(&_border_handlers_vector[i], Window::DimX);
         NEScheduler::get().schedule(&_concat_kernels_vector[i], Window::DimX);
     }
 }
References Window::DimX, Scheduler::get(), and IScheduler::schedule().
validate()
Status validate (const std::vector< ITensorInfo * > & inputs_vector, const ITensorInfo * output) static
Static function to check if given info will lead to a valid configuration of NEDepthConcatenateLayer.
Parameters
[in] inputs_vector The vectors containing all the tensors to concatenate. Data types supported: QASYMM8/F16/F32. Input dimensions might differ for each input for the first three dimensions (width, height, depth) and must match for the rest. Note that the difference between the minimum and maximum width and height among the input tensors must be divisible by 2 otherwise it is not clear how padding should be added on the inputs' width and height when they are less than the maximum input sizes.
[in] output Output tensor. Data types supported: Same as input. Output tensor dimensions match the inputs' ones from the fourth dimension and above, while width and height are the maximum width and height of the input tensors. Finally, depth is the sum of the input depths.
Returns
a status
Definition at line 76 of file NEDepthConcatenateLayer.cpp.
 {
     ARM_COMPUTE_RETURN_ERROR_ON_NULLPTR(output);
     ARM_COMPUTE_RETURN_ERROR_ON(inputs_vector.size() < 2);
     // Output auto inizialitation if not yet initialized
     TensorInfo  tmp_output_info = *output->clone();
     TensorShape output_shape    = arm_compute::misc::shape_calculator::calculate_depth_concatenate_shape(inputs_vector);
     auto_init_if_empty(tmp_output_info, output_shape, 1, inputs_vector[0]->data_type());
     unsigned int depth_offset = 0;
     for(const auto &input : inputs_vector)
     {
         ARM_COMPUTE_RETURN_ERROR_ON_NULLPTR(input);
         ARM_COMPUTE_RETURN_ON_ERROR(NEDepthConcatenateLayerKernel::validate(input, depth_offset, &tmp_output_info));
         depth_offset += input->dimension(2);
     }
     return Status{};
 }
References ARM_COMPUTE_RETURN_ERROR_ON, ARM_COMPUTE_RETURN_ERROR_ON_NULLPTR, ARM_COMPUTE_RETURN_ON_ERROR, arm_compute::auto_init_if_empty(), arm_compute::misc::shape_calculator::calculate_depth_concatenate_shape(), ICloneable< T >::clone(), arm_compute::test::validation::data_type, arm_compute::test::validation::output_shape, and NEDepthConcatenateLayerKernel::validate().
Referenced by NEDepthConcatenateLayer::configure(), and NEConcatenateLayer::validate().
The documentation for this class was generated from the following files:
arm_compute/runtime/NEON/functions/NEDepthConcatenateLayer.h
src/runtime/NEON/functions/NEDepthConcatenateLayer.cpp