Compute Library: NEDirectConvolutionLayerKernel Class Reference
NEDirectConvolutionLayerKernel Class Reference
NEON interface for Direct Convolution Layer kernel.
#include <NEDirectConvolutionLayerKernel.h>
Public Member Functions
const char * name () const override
Name of the kernel.
NEDirectConvolutionLayerKernel ()
Default constructor.
NEDirectConvolutionLayerKernel (const NEDirectConvolutionLayerKernel &)=delete
Prevent instances of this class from being copied (As this class contains pointers)
NEDirectConvolutionLayerKernel & operator= (const NEDirectConvolutionLayerKernel &)=delete
Prevent instances of this class from being copied (As this class contains pointers)
NEDirectConvolutionLayerKernel (NEDirectConvolutionLayerKernel &&)=default
Allow instances of this class to be moved.
NEDirectConvolutionLayerKernel & operator= (NEDirectConvolutionLayerKernel &&)=default
Allow instances of this class to be moved.
~NEDirectConvolutionLayerKernel ()=default
Default destructor.
void configure (const ITensor *input, const ITensor *weights, ITensor *output, const PadStrideInfo &conv_info)
Set the input, weights, and output tensors.
void run (const Window &window, const ThreadInfo &info) override
Execute the kernel on the passed window.
BorderSize border_size () const override
The size of the border for that kernel.
Public Member Functions inherited from ICPPKernel
virtual ~ICPPKernel ()=default
Default destructor.
Public Member Functions inherited from IKernel
IKernel ()
Constructor.
virtual ~IKernel ()=default
Destructor.
virtual bool is_parallelisable () const
Indicates whether or not the kernel is parallelisable.
const Window & window () const
The maximum window the kernel can be executed on.
Static Public Member Functions
static Status validate (const ITensorInfo *input, const ITensorInfo *weights, const ITensorInfo *output, const PadStrideInfo &conv_info)
Static function to check if given info will lead to a valid configuration of NEDirectConvolutionLayerKernel.
Detailed Description
NEON interface for Direct Convolution Layer kernel.
Definition at line 34 of file NEDirectConvolutionLayerKernel.h.
Constructor & Destructor Documentation
NEDirectConvolutionLayerKernel() [1/3]
NEDirectConvolutionLayerKernel ()
Default constructor.
Definition at line 1453 of file NEDirectConvolutionLayerKernel.cpp.
     : _input(nullptr), _weights(nullptr), _output(nullptr), _conv_info(), _border_size(0), _kernel_size(0), _num_weight_elems_read_per_row(0), _num_elems_read_per_iteration(0),
       _num_elems_written_per_iteration(0)
 {
 }
NEDirectConvolutionLayerKernel() [2/3]
NEDirectConvolutionLayerKernel (const NEDirectConvolutionLayerKernel &) delete
Prevent instances of this class from being copied (As this class contains pointers)
NEDirectConvolutionLayerKernel() [3/3]
NEDirectConvolutionLayerKernel (NEDirectConvolutionLayerKernel &&) default
Allow instances of this class to be moved.
~NEDirectConvolutionLayerKernel()
~NEDirectConvolutionLayerKernel () default
Default destructor.
Member Function Documentation
border_size()
BorderSize border_size () const override virtual
The size of the border for that kernel.
Returns
The width in number of elements of the border.
Reimplemented from IKernel.
Definition at line 1459 of file NEDirectConvolutionLayerKernel.cpp.
 {
     return _border_size;
 }
Referenced by NEDirectConvolutionLayer::configure(), and NEDirectConvolutionLayerKernel::validate().
configure()
void configure (const ITensor * input, const ITensor * weights, ITensor * output, const PadStrideInfo & conv_info)
Set the input, weights, and output tensors.
Note
: DirectConvolution only works in the following configurations: 1x1 convolution with stride_x = 1/2/3, stride_y = 1/2/3 3x3 convolution with stride_x = 1/2/3, stride_y = 1/2/3
Parameters
[in] input The input tensor to convolve. 3 lower dimensions represent a single input [width, height, IFM], while every optional dimension from 4 and above represent a batch of inputs. Data types supported: F16/F32.
[in] weights Weights tensor. Weights are 4D tensor with dimensions [kernel_x, kernel_y, IFM, OFM]. The 3rd dimension must be the same as the input's volume 3rd dimension. Data type supported:Same as input.
[out] output Output tensor. The 3rd dimensions must be equal to the 4th dimension of the kernels tensor. Data types supported: F16/F32
[in] conv_info Contains padding and stride information described in PadStrideInfo.
Definition at line 1464 of file NEDirectConvolutionLayerKernel.cpp.
 {
     ARM_COMPUTE_ERROR_ON_NULLPTR(input, weights, output);
     _input       = input;
     _weights     = weights;
     _output      = output;
     _conv_info   = conv_info;
     _kernel_size = weights->info()->dimension(get_data_layout_dimension_index(weights->info()->data_layout(), DataLayoutDimension::WIDTH));
     const unsigned int conv_pad_left   = conv_info.pad_left();
     const unsigned int conv_pad_top    = conv_info.pad_top();
     const unsigned int conv_pad_right  = conv_info.pad_right();
     const unsigned int conv_pad_bottom = conv_info.pad_bottom();
     _border_size                       = BorderSize(conv_pad_top, conv_pad_right, conv_pad_bottom, conv_pad_left);
     // Get convolved dimensions
     TensorShape output_shape = misc::shape_calculator::compute_deep_convolution_shape(*input->info(), *weights->info(), conv_info);
     DataType data_type = input->info()->data_type();
     // Output auto inizialitation if not yet initialized
     auto_init_if_empty(*output->info(), output_shape, 1, data_type);
     // Perform validation step
     ARM_COMPUTE_ERROR_THROW_ON(validate_arguments(input->info(), weights->info(), output->info(), conv_info));
     // Configure kernel window
     auto win_config = validate_and_configure_window(input->info(), weights->info(), output->info(), conv_info, _num_weight_elems_read_per_row,
                                                     _num_elems_read_per_iteration, _num_elems_written_per_iteration, _border_size);
     ARM_COMPUTE_ERROR_THROW_ON(win_config.first);
     INEKernel::configure(win_config.second);
 }
References ARM_COMPUTE_ERROR_ON_NULLPTR, ARM_COMPUTE_ERROR_THROW_ON, arm_compute::auto_init_if_empty(), arm_compute::misc::shape_calculator::compute_deep_convolution_shape(), arm_compute::test::validation::conv_info, TensorInfo::data_layout(), arm_compute::test::validation::data_type, ITensorInfo::data_type(), TensorInfo::dimension(), arm_compute::get_data_layout_dimension_index(), ITensor::info(), CLTensor::info(), arm_compute::test::validation::output_shape, arm_compute::validate_and_configure_window(), arm_compute::test::validation::weights, and arm_compute::WIDTH.
Referenced by NEDirectConvolutionLayer::configure().
name()
const char* name () const inline override virtual
Name of the kernel.
Returns
Kernel name
Implements ICPPKernel.
Definition at line 37 of file NEDirectConvolutionLayerKernel.h.
     {
         return "NEDirectConvolutionLayerKernel";
     }
operator=() [1/2]
NEDirectConvolutionLayerKernel& operator= (const NEDirectConvolutionLayerKernel &) delete
Prevent instances of this class from being copied (As this class contains pointers)
operator=() [2/2]
NEDirectConvolutionLayerKernel& operator= (NEDirectConvolutionLayerKernel &&) default
Allow instances of this class to be moved.
run()
void run (const Window & window, const ThreadInfo & info) override virtual
Execute the kernel on the passed window.
Warning
If is_parallelisable() returns false then the passed window must be equal to window()
Note
The window has to be a region within the window returned by the window() method
The width of the window has to be a multiple of num_elems_processed_per_iteration().
Parameters
[in] window Region on which to execute the kernel. (Must be a region of the window returned by window())
[in] info Info about executing thread and CPU.
Implements ICPPKernel.
Definition at line 1518 of file NEDirectConvolutionLayerKernel.cpp.
 {
     ARM_COMPUTE_UNUSED(info);
     ARM_COMPUTE_ERROR_ON_UNCONFIGURED_KERNEL(this);
     ARM_COMPUTE_ERROR_ON_INVALID_SUBWINDOW(INEKernel::window(), window);
     ARM_COMPUTE_ERROR_ON(_input->buffer() == nullptr);
     const int kernel_size = _weights->info()->dimension(get_data_layout_dimension_index(_weights->info()->data_layout(), DataLayoutDimension::WIDTH));
     if(_input->info()->data_layout() == DataLayout::NCHW)
     {
         switch(kernel_size)
         {
             case 1:
             {
                 switch(_input->info()->data_type())
                 {
                     case DataType::F32:
                         convolve_1x1<float, float>(window, _num_elems_read_per_iteration, _num_elems_written_per_iteration, _input, _weights, _output, _conv_info);
                         break;
 #ifdef __ARM_FEATURE_FP16_VECTOR_ARITHMETIC
                     case DataType::F16:
                         convolve_1x1<float16_t, float16_t>(window, _num_elems_read_per_iteration, _num_elems_written_per_iteration, _input, _weights, _output, _conv_info);
                         break;
 #endif /* __ARM_FEATURE_FP16_VECTOR_ARITHMETIC */
                     default:
                         ARM_COMPUTE_ERROR("Data type not supported");
                         break;
                 }
                 break;
             }
             case 3:
             {
                 switch(_input->info()->data_type())
                 {
                     case DataType::F32:
                         convolve_3x3<float, float>(window, _num_elems_read_per_iteration, _num_elems_written_per_iteration, _input, _weights, _output, _conv_info);
                         break;
 #ifdef __ARM_FEATURE_FP16_VECTOR_ARITHMETIC
                     case DataType::F16:
                         convolve_3x3<float16_t, float16_t>(window, _num_elems_read_per_iteration, _num_elems_written_per_iteration, _input, _weights, _output, _conv_info);
                         break;
 #endif /* __ARM_FEATURE_FP16_VECTOR_ARITHMETIC */
                     default:
                         ARM_COMPUTE_ERROR("Data type not supported");
                         break;
                 }
                 break;
             }
             case 5:
             {
                 switch(_input->info()->data_type())
                 {
                     case DataType::F32:
                         convolve_5x5<float, float>(window, _num_elems_read_per_iteration, _num_elems_written_per_iteration, _input, _weights, _output, _conv_info);
                         break;
                     default:
                         ARM_COMPUTE_ERROR("Data type not supported");
                         break;
                 }
                 break;
             }
             default:
             {
                 ARM_COMPUTE_ERROR("Only kernel sizes 1x1, 3x3 and 5x5 are supported.");
                 break;
             }
         }
     }
     else
     {
         const int kernel_size = _weights->info()->dimension(get_data_layout_dimension_index(_weights->info()->data_layout(), DataLayoutDimension::WIDTH));
         const int stride_x    = std::get<0>(_conv_info.stride());
         const int stride_y    = std::get<1>(_conv_info.stride());
         switch(_input->info()->data_type())
         {
             case DataType::F32:
             {
                 if(kernel_size == 9 && stride_x == 1 && stride_y == 1)
                 {
                     using vtype = wrapper::traits::neon_vector<float, 4>;
                     convolve_9x9_nhwc<vtype>(window, _num_elems_read_per_iteration, _input, _weights, _output, _conv_info);
                 }
                 else
                 {
                     convolver_nhwc<float>::convolve(window, kernel_size, _num_elems_read_per_iteration, _input, _weights, _output, _conv_info);
                 }
                 break;
             }
             default:
                 ARM_COMPUTE_ERROR("Data type not supported");
                 break;
         }
     }
 }
References ARM_COMPUTE_ERROR, ARM_COMPUTE_ERROR_ON, ARM_COMPUTE_ERROR_ON_INVALID_SUBWINDOW, ARM_COMPUTE_ERROR_ON_UNCONFIGURED_KERNEL, ARM_COMPUTE_UNUSED, ITensor::buffer(), ITensorInfo::data_layout(), ITensorInfo::data_type(), ITensorInfo::dimension(), arm_compute::F16, arm_compute::F32, arm_compute::get_data_layout_dimension_index(), ITensor::info(), arm_compute::test::validation::info, arm_compute::NCHW, PadStrideInfo::stride(), arm_compute::WIDTH, and IKernel::window().
validate()
Status validate (const ITensorInfo * input, const ITensorInfo * weights, const ITensorInfo * output, const PadStrideInfo & conv_info) static
Static function to check if given info will lead to a valid configuration of NEDirectConvolutionLayerKernel.
Parameters
[in] input The input tensor to convolve. 3 lower dimensions represent a single input [width, height, IFM], while every optional dimension from 4 and above represent a batch of inputs. Data types supported: F16/F32.
[in] weights Weights tensor. Weights are 4D tensor with dimensions [kernel_x, kernel_y, IFM, OFM]. The 3rd dimension must be the same as the input's volume 3rd dimension. Data type supported:Same as input.
[in] output Output tensor. The 3rd dimensions must be equal to the 4th dimension of the kernels tensor. Data types supported: F16/F32
[in] conv_info Contains padding and stride information described in PadStrideInfo.
Returns
a status
Definition at line 1498 of file NEDirectConvolutionLayerKernel.cpp.
 {
     unsigned int num_weight_elems_read_per_row   = 0;
     unsigned int num_elems_read_per_iteration    = 0;
     unsigned int num_elems_written_per_iteration = 0;
     BorderSize   border_size                     = {};
     ARM_COMPUTE_RETURN_ON_ERROR(validate_arguments(input, weights, output, conv_info));
     ARM_COMPUTE_RETURN_ON_ERROR(validate_and_configure_window(input->clone().get(),
                                                               weights->clone().get(),
                                                               output->clone().get(),
                                                               conv_info,
                                                               num_weight_elems_read_per_row,
                                                               num_elems_read_per_iteration,
                                                               num_elems_written_per_iteration,
                                                               border_size)
                                 .first);
     return Status{};
 }
References ARM_COMPUTE_RETURN_ON_ERROR, NEDirectConvolutionLayerKernel::border_size(), ICloneable< T >::clone(), arm_compute::test::validation::conv_info, arm_compute::validate_and_configure_window(), and arm_compute::test::validation::weights.
Referenced by NEDirectConvolutionLayer::validate().
The documentation for this class was generated from the following files:
arm_compute/core/NEON/kernels/NEDirectConvolutionLayerKernel.h
src/core/NEON/kernels/NEDirectConvolutionLayerKernel.cpp