Compute Library: INode Class Reference
INode Class Reference abstract
Node interface.
#include <INode.h>
Public Member Functions
INode ()
Constructor.
virtual ~INode ()=default
Destructor.
INode (const INode &)=delete
Prevent instances of this class from being copied (As this class contains pointers)
INode & operator= (const INode &)=delete
Prevent instances of this class from being copy assigned (As this class contains pointers)
INode (INode &&)=default
Allow instances of this class to be moved.
INode & operator= (INode &&)=default
Allow instances of this class to be move assigned.
virtual Status validate () const
Validate node.
virtual NodeType type () const =0
Returns node's type.
virtual void accept (INodeVisitor &v)=0
Accepts a node visitor.
virtual bool forward_descriptors ()=0
Forwards descriptor information to outputs if possible.
virtual TensorDescriptor configure_output (size_t idx) const =0
Calculates output configuration.
std::string name () const
Returns node's name.
NodeID id () const
Returns node's ID.
const Graph * graph () const
Returns node's Graph.
Graph * graph ()
Returns node's Graph.
void set_graph (Graph *g)
Sets the graph that this node is registered to.
void set_id (NodeID id)
Sets the node id.
void set_common_node_parameters (NodeParams common_params)
Sets common node parameters.
void set_requested_target (Target target)
Sets target preference.
void set_assigned_target (Target target)
Sets the final execution target.
void set_output_tensor (TensorID tid, size_t idx)
Sets the output tensor of at a given index.
const std::vector< TensorID > & inputs () const
Returns inputs of the node.
const std::vector< TensorID > & outputs () const
Returns outputs of the node.
const std::vector< EdgeID > & input_edges () const
Returns input edge set.
const std::set< EdgeID > & output_edges () const
Returns output edge set.
TensorID input_id (size_t idx) const
Returns the tensor ID of a given input of the node.
TensorID output_id (size_t idx) const
Returns the tensor ID of a given output of the node.
Tensor * input (size_t idx) const
Returns the tensor of a given input of the node.
Tensor * output (size_t idx) const
Returns the tensor of a given output of the node.
EdgeID input_edge_id (size_t idx) const
Returns the edge ID of a given input of the node.
Edge * input_edge (size_t idx) const
Returns the edge of a given input of the node.
size_t num_inputs () const
Returns number of inputs of the node.
size_t num_outputs () const
Returns number of outputs of the node.
NodeParams common_node_params () const
Returns common node parameters.
Target requested_target () const
Returns requested target for this node.
Target assigned_target () const
Returns assigned target for this node.
Friends
class Graph
Detailed Description
Node interface.
Definition at line 44 of file INode.h.
Constructor & Destructor Documentation
INode() [1/3]
INode ()
Constructor.
Definition at line 37 of file INode.cpp.
     : _graph(nullptr), _id(EmptyNodeID), _common_params({ "", Target::UNSPECIFIED}),
       _outputs(), _input_edges(), _output_edges(), _assigned_target(Target::UNSPECIFIED)
 {
 }
References arm_compute::graph::UNSPECIFIED.
~INode()
virtual ~INode () virtual default
Destructor.
INode() [2/3]
INode (const INode &) delete
Prevent instances of this class from being copied (As this class contains pointers)
INode() [3/3]
INode (INode &&) default
Allow instances of this class to be moved.
Member Function Documentation
accept()
virtual void accept (INodeVisitor & v) pure virtual
Accepts a node visitor.
Parameters
[in] v Visitor to accept
Implemented in ConvolutionLayerNode, DepthwiseConvolutionLayerNode, FullyConnectedLayerNode, ConcatenateLayerNode, SplitLayerNode, SliceLayerNode, DeconvolutionLayerNode, EltwiseLayerNode, UpsampleLayerNode, BatchNormalizationLayerNode, DetectionOutputLayerNode, PoolingLayerNode, PriorBoxLayerNode, ReorgLayerNode, ROIAlignLayerNode, YOLOLayerNode, DummyNode, PermuteLayerNode, ResizeLayerNode, BoundingBoxTransformLayerNode, GenerateProposalsLayerNode, PadLayerNode, ActivationLayerNode, ChannelShuffleLayerNode, NormalizationLayerNode, SoftmaxLayerNode, ConstNode, InputNode, ReshapeLayerNode, FlattenLayerNode, NormalizePlanarYUVLayerNode, and OutputNode.
assigned_target()
Target assigned_target () const
Returns assigned target for this node.
Returns
Assigned target of this node
Definition at line 198 of file INode.cpp.
 {
     return _assigned_target;
 }
Referenced by arm_compute::graph::detail::configure_all_nodes(), NEDeviceBackend::configure_node(), GCDeviceBackend::configure_node(), CLDeviceBackend::configure_node(), GroupedConvolutionMutator::mutate(), NEDeviceBackend::validate_node(), GCDeviceBackend::validate_node(), CLDeviceBackend::validate_node(), and arm_compute::graph::backends::detail::validate_node().
common_node_params()
NodeParams common_node_params () const
Returns common node parameters.
Returns
Common node parameters
Definition at line 188 of file INode.cpp.
 {
     return _common_params;
 }
configure_output()
virtual TensorDescriptor configure_output (size_t idx) const pure virtual
Calculates output configuration.
Parameters
[in] idx Output index to configure
Returns
Output descriptor configuration
Implemented in ConvolutionLayerNode, DepthwiseConvolutionLayerNode, FullyConnectedLayerNode, ConcatenateLayerNode, SplitLayerNode, SliceLayerNode, DeconvolutionLayerNode, EltwiseLayerNode, UpsampleLayerNode, BatchNormalizationLayerNode, DetectionOutputLayerNode, PoolingLayerNode, PriorBoxLayerNode, ReorgLayerNode, ROIAlignLayerNode, YOLOLayerNode, DummyNode, PermuteLayerNode, ResizeLayerNode, BoundingBoxTransformLayerNode, GenerateProposalsLayerNode, PadLayerNode, ActivationLayerNode, ChannelShuffleLayerNode, NormalizationLayerNode, SoftmaxLayerNode, ConstNode, InputNode, ReshapeLayerNode, FlattenLayerNode, NormalizePlanarYUVLayerNode, and OutputNode.
forward_descriptors()
virtual bool forward_descriptors () pure virtual
Forwards descriptor information to outputs if possible.
Returns
True if descriptor information could be forwarded otherwise false
Implemented in ConvolutionLayerNode, DepthwiseConvolutionLayerNode, FullyConnectedLayerNode, ConcatenateLayerNode, SplitLayerNode, SliceLayerNode, DeconvolutionLayerNode, EltwiseLayerNode, UpsampleLayerNode, BatchNormalizationLayerNode, DetectionOutputLayerNode, PoolingLayerNode, PriorBoxLayerNode, ReorgLayerNode, ROIAlignLayerNode, YOLOLayerNode, DummyNode, PermuteLayerNode, ResizeLayerNode, BoundingBoxTransformLayerNode, GenerateProposalsLayerNode, PadLayerNode, ActivationLayerNode, ChannelShuffleLayerNode, NormalizationLayerNode, SoftmaxLayerNode, ConstNode, InputNode, ReshapeLayerNode, FlattenLayerNode, NormalizePlanarYUVLayerNode, and OutputNode.
Referenced by Graph::add_node().
graph() [1/2]
const Graph * graph () const
Returns node's Graph.
Returns
Node's graph
Definition at line 112 of file INode.cpp.
 {
     return _graph;
 }
Referenced by arm_compute::graph::detail::all_inputs_are_visited(), and arm_compute::graph::get_driving_nodes().
graph() [2/2]
Graph * graph ()
Returns node's Graph.
Returns
Node's graph
Definition at line 117 of file INode.cpp.
 {
     return _graph;
 }
id()
NodeID id () const
Returns node's ID.
Returns
Node's ID
Definition at line 102 of file INode.cpp.
 {
     return _id;
 }
Referenced by NEDeviceBackend::configure_node(), GCDeviceBackend::configure_node(), CLDeviceBackend::configure_node(), Edge::consumer_id(), arm_compute::graph::backends::detail::create_concatenate_layer(), arm_compute::graph::backends::detail::create_concatenate_layer< GCDepthConcatenateLayer, GCTargetInfo >(), arm_compute::graph::backends::detail::create_eltwise_layer< GCEltwiseFunctions, GCTargetInfo >(), SplitLayerSubTensorMutator::mutate(), DepthConcatSubTensorMutator::mutate(), GroupedConvolutionMutator::mutate(), NodeExecutionMethodMutator::mutate(), Edge::producer_id(), INode::set_id(), arm_compute::graph::backends::detail::validate_bounding_box_transform_layer(), arm_compute::graph::backends::detail::validate_channel_shuffle_layer(), arm_compute::graph::backends::detail::validate_convolution_layer(), arm_compute::graph::backends::detail::validate_depthwise_convolution_layer(), arm_compute::graph::backends::detail::validate_detection_output_layer(), arm_compute::graph::backends::detail::validate_generate_proposals_layer(), NEDeviceBackend::validate_node(), GCDeviceBackend::validate_node(), CLDeviceBackend::validate_node(), arm_compute::graph::backends::detail::validate_node(), arm_compute::graph::backends::detail::validate_normalize_planar_yuv_layer(), arm_compute::graph::backends::detail::validate_pad_layer(), arm_compute::graph::backends::detail::validate_permute_layer(), arm_compute::graph::backends::detail::validate_priorbox_layer(), arm_compute::graph::backends::detail::validate_reorg_layer(), arm_compute::graph::backends::detail::validate_roi_align_layer(), arm_compute::graph::backends::detail::validate_slice_layer(), arm_compute::graph::backends::detail::validate_upsample_layer(), and arm_compute::graph::backends::detail::validate_yolo_layer().
input()
Tensor * input (size_t idx) const
Returns the tensor of a given input of the node.
Note
Precondition : idx should be a valid input index
Parameters
[in] idx Index of the node input
Returns
Tensor of the requested input
Definition at line 150 of file INode.cpp.
 {
     ARM_COMPUTE_ERROR_ON(_graph == nullptr);
     ARM_COMPUTE_ERROR_ON(idx >= _input_edges.size());
     Edge *e = _graph->edge(_input_edges[idx]);
     return (e != nullptr) ? e->tensor() : nullptr;
 }
References ARM_COMPUTE_ERROR_ON, Graph::edge(), and Edge::tensor().
Referenced by arm_compute::graph::detail::allocate_all_input_tensors(), NormalizePlanarYUVLayerNode::configure_output(), FlattenLayerNode::configure_output(), ReshapeLayerNode::configure_output(), NormalizationLayerNode::configure_output(), SoftmaxLayerNode::configure_output(), ActivationLayerNode::configure_output(), ChannelShuffleLayerNode::configure_output(), GenerateProposalsLayerNode::configure_output(), PadLayerNode::configure_output(), BoundingBoxTransformLayerNode::configure_output(), PermuteLayerNode::configure_output(), ResizeLayerNode::configure_output(), DummyNode::configure_output(), YOLOLayerNode::configure_output(), ROIAlignLayerNode::configure_output(), PoolingLayerNode::configure_output(), PriorBoxLayerNode::configure_output(), ReorgLayerNode::configure_output(), DetectionOutputLayerNode::configure_output(), BatchNormalizationLayerNode::configure_output(), UpsampleLayerNode::configure_output(), EltwiseLayerNode::configure_output(), DeconvolutionLayerNode::configure_output(), SliceLayerNode::configure_output(), SplitLayerNode::configure_output(), FullyConnectedLayerNode::configure_output(), DepthwiseConvolutionLayerNode::configure_output(), ConvolutionLayerNode::configure_output(), arm_compute::graph::backends::detail::create_activation_layer(), arm_compute::graph::backends::detail::create_batch_normalization_layer(), arm_compute::graph::backends::detail::create_bounding_box_transform_layer(), arm_compute::graph::backends::detail::create_channel_shuffle_layer(), arm_compute::graph::backends::detail::create_concatenate_layer(), arm_compute::graph::backends::detail::create_concatenate_layer< GCDepthConcatenateLayer, GCTargetInfo >(), arm_compute::graph::backends::detail::create_convolution_layer(), arm_compute::graph::backends::detail::create_convolution_layer< GCConvolutionLayerFunctions, GCTargetInfo >(), arm_compute::graph::backends::detail::create_convolution_layer< NEConvolutionLayerFunctions, NETargetInfo >(), arm_compute::graph::backends::detail::create_deconvolution_layer(), arm_compute::graph::backends::detail::create_depthwise_convolution_layer(), arm_compute::graph::backends::detail::create_depthwise_convolution_layer< GCDepthwiseConvolutionLayerFunctions, GCTargetInfo >(), arm_compute::graph::backends::detail::create_detection_output_layer(), arm_compute::graph::backends::detail::create_detection_output_layer< CPPDetectionOutputLayer, CLTargetInfo >(), arm_compute::graph::backends::detail::create_eltwise_layer(), arm_compute::graph::backends::detail::create_eltwise_layer< GCEltwiseFunctions, GCTargetInfo >(), arm_compute::graph::backends::detail::create_flatten_layer(), arm_compute::graph::backends::detail::create_fully_connected_layer(), arm_compute::graph::backends::detail::create_generate_proposals_layer(), arm_compute::graph::backends::detail::create_normalization_layer(), arm_compute::graph::backends::detail::create_normalization_layer< NENormalizationLayer, NETargetInfo >(), arm_compute::graph::backends::detail::create_normalize_planar_yuv_layer(), arm_compute::graph::backends::detail::create_pad_layer(), arm_compute::graph::backends::detail::create_permute_layer(), arm_compute::graph::backends::detail::create_pooling_layer(), arm_compute::graph::backends::detail::create_priorbox_layer(), arm_compute::graph::backends::detail::create_reorg_layer(), arm_compute::graph::backends::detail::create_reshape_layer(), arm_compute::graph::backends::detail::create_resize_layer(), arm_compute::graph::backends::detail::create_roi_align_layer(), arm_compute::graph::backends::detail::create_slice_layer(), arm_compute::graph::backends::detail::create_softmax_layer(), arm_compute::graph::backends::detail::create_upsample_layer(), arm_compute::graph::backends::detail::create_yolo_layer(), SplitLayerSubTensorMutator::mutate(), DepthConcatSubTensorMutator::mutate(), SplitLayerNode::validate(), arm_compute::graph::backends::detail::validate_bounding_box_transform_layer(), arm_compute::graph::backends::detail::validate_channel_shuffle_layer(), arm_compute::graph::backends::detail::validate_convolution_layer(), arm_compute::graph::backends::detail::validate_depthwise_convolution_layer(), arm_compute::graph::backends::detail::validate_detection_output_layer(), arm_compute::graph::backends::detail::validate_generate_proposals_layer(), arm_compute::graph::backends::detail::validate_normalize_planar_yuv_layer(), arm_compute::graph::backends::detail::validate_pad_layer(), arm_compute::graph::backends::detail::validate_permute_layer(), arm_compute::graph::backends::detail::validate_priorbox_layer(), arm_compute::graph::backends::detail::validate_reorg_layer(), arm_compute::graph::backends::detail::validate_roi_align_layer(), arm_compute::graph::backends::detail::validate_slice_layer(), arm_compute::graph::backends::detail::validate_upsample_layer(), and arm_compute::graph::backends::detail::validate_yolo_layer().
input_edge()
Edge * input_edge (size_t idx) const
Returns the edge of a given input of the node.
Note
Precondition : idx should be a valid input index
Parameters
[in] idx Index of the node input
Returns
Edge of the requested input
Definition at line 171 of file INode.cpp.
 {
     ARM_COMPUTE_ERROR_ON(_graph == nullptr);
     ARM_COMPUTE_ERROR_ON(idx >= _input_edges.size());
     return _graph->edge(_input_edges[idx]);
 }
References ARM_COMPUTE_ERROR_ON, and Graph::edge().
input_edge_id()
EdgeID input_edge_id (size_t idx) const
Returns the edge ID of a given input of the node.
Note
Precondition : idx should be a valid input index
Parameters
[in] idx Index of the node input
Returns
EdgeID of the requested input
Definition at line 165 of file INode.cpp.
 {
     ARM_COMPUTE_ERROR_ON(idx >= _input_edges.size());
     return _input_edges[idx];
 }
References ARM_COMPUTE_ERROR_ON.
input_edges()
const std::vector< EdgeID > & input_edges () const
Returns input edge set.
Returns
Set of input edges
Definition at line 127 of file INode.cpp.
 {
     return _input_edges;
 }
Referenced by arm_compute::graph::detail::all_inputs_are_visited(), and DepthConcatSubTensorMutator::mutate().
input_id()
TensorID input_id (size_t idx) const
Returns the tensor ID of a given input of the node.
Note
Precondition : idx should be a valid input index
Parameters
[in] idx Index of the node input
Returns
TensorID of the requested input
Definition at line 137 of file INode.cpp.
 {
     ARM_COMPUTE_ERROR_ON(idx >= _input_edges.size());
     Edge *e = _graph->edge(_input_edges[idx]);
     return (e != nullptr) ? e->tensor_id() : NullTensorID;
 }
References ARM_COMPUTE_ERROR_ON, Graph::edge(), arm_compute::graph::NullTensorID, and Edge::tensor_id().
Referenced by ConcatenateLayerNode::configure_output(), NormalizePlanarYUVLayerNode::forward_descriptors(), FlattenLayerNode::forward_descriptors(), ReshapeLayerNode::forward_descriptors(), ActivationLayerNode::forward_descriptors(), ChannelShuffleLayerNode::forward_descriptors(), SoftmaxLayerNode::forward_descriptors(), NormalizationLayerNode::forward_descriptors(), PadLayerNode::forward_descriptors(), BoundingBoxTransformLayerNode::forward_descriptors(), GenerateProposalsLayerNode::forward_descriptors(), PermuteLayerNode::forward_descriptors(), DummyNode::forward_descriptors(), ResizeLayerNode::forward_descriptors(), YOLOLayerNode::forward_descriptors(), ROIAlignLayerNode::forward_descriptors(), DetectionOutputLayerNode::forward_descriptors(), PoolingLayerNode::forward_descriptors(), PriorBoxLayerNode::forward_descriptors(), ReorgLayerNode::forward_descriptors(), BatchNormalizationLayerNode::forward_descriptors(), EltwiseLayerNode::forward_descriptors(), UpsampleLayerNode::forward_descriptors(), DeconvolutionLayerNode::forward_descriptors(), SliceLayerNode::forward_descriptors(), SplitLayerNode::forward_descriptors(), FullyConnectedLayerNode::forward_descriptors(), DepthwiseConvolutionLayerNode::forward_descriptors(), and ConvolutionLayerNode::forward_descriptors().
inputs()
const std::vector<TensorID>& inputs () const
Returns inputs of the node.
Returns
Inputs of the node
name()
std::string name () const
Returns node's name.
Returns
Node name
Definition at line 107 of file INode.cpp.
 {
     return _common_params.name;
 }
References NodeParams::name.
Referenced by arm_compute::graph::backends::detail::create_activation_layer(), arm_compute::graph::backends::detail::create_batch_normalization_layer(), arm_compute::graph::backends::detail::create_channel_shuffle_layer(), arm_compute::graph::backends::detail::create_concatenate_layer(), arm_compute::graph::backends::detail::create_concatenate_layer< GCDepthConcatenateLayer, GCTargetInfo >(), arm_compute::graph::backends::detail::create_convolution_layer(), arm_compute::graph::backends::detail::create_convolution_layer< GCConvolutionLayerFunctions, GCTargetInfo >(), arm_compute::graph::backends::detail::create_deconvolution_layer(), arm_compute::graph::backends::detail::create_depthwise_convolution_layer(), arm_compute::graph::backends::detail::create_depthwise_convolution_layer< GCDepthwiseConvolutionLayerFunctions, GCTargetInfo >(), arm_compute::graph::backends::detail::create_detection_output_layer(), arm_compute::graph::backends::detail::create_detection_output_layer< CPPDetectionOutputLayer, CLTargetInfo >(), arm_compute::graph::backends::detail::create_eltwise_layer(), arm_compute::graph::backends::detail::create_eltwise_layer< GCEltwiseFunctions, GCTargetInfo >(), arm_compute::graph::backends::detail::create_flatten_layer(), arm_compute::graph::backends::detail::create_fully_connected_layer(), arm_compute::graph::backends::detail::create_normalization_layer(), arm_compute::graph::backends::detail::create_normalization_layer< NENormalizationLayer, NETargetInfo >(), arm_compute::graph::backends::detail::create_normalize_planar_yuv_layer(), arm_compute::graph::backends::detail::create_pad_layer(), arm_compute::graph::backends::detail::create_permute_layer(), arm_compute::graph::backends::detail::create_pooling_layer(), arm_compute::graph::backends::detail::create_priorbox_layer(), arm_compute::graph::backends::detail::create_reorg_layer(), arm_compute::graph::backends::detail::create_reshape_layer(), arm_compute::graph::backends::detail::create_resize_layer(), arm_compute::graph::backends::detail::create_slice_layer(), arm_compute::graph::backends::detail::create_softmax_layer(), arm_compute::graph::backends::detail::create_upsample_layer(), arm_compute::graph::backends::detail::create_yolo_layer(), SplitLayerSubTensorMutator::mutate(), DepthConcatSubTensorMutator::mutate(), NodeExecutionMethodMutator::mutate(), arm_compute::graph::backends::detail::validate_bounding_box_transform_layer(), arm_compute::graph::backends::detail::validate_channel_shuffle_layer(), arm_compute::graph::backends::detail::validate_convolution_layer(), arm_compute::graph::backends::detail::validate_depthwise_convolution_layer(), arm_compute::graph::backends::detail::validate_detection_output_layer(), arm_compute::graph::backends::detail::validate_generate_proposals_layer(), arm_compute::graph::backends::detail::validate_node(), arm_compute::graph::backends::detail::validate_normalize_planar_yuv_layer(), arm_compute::graph::backends::detail::validate_pad_layer(), arm_compute::graph::backends::detail::validate_permute_layer(), arm_compute::graph::backends::detail::validate_priorbox_layer(), arm_compute::graph::backends::detail::validate_reorg_layer(), arm_compute::graph::backends::detail::validate_roi_align_layer(), arm_compute::graph::backends::detail::validate_slice_layer(), arm_compute::graph::backends::detail::validate_upsample_layer(), and arm_compute::graph::backends::detail::validate_yolo_layer().
num_inputs()
size_t num_inputs () const
Returns number of inputs of the node.
Returns
Number of inputs
Definition at line 178 of file INode.cpp.
 {
     return _input_edges.size();
 }
Referenced by arm_compute::graph::detail::allocate_all_input_tensors(), arm_compute::graph::backends::detail::create_concatenate_layer(), arm_compute::graph::backends::detail::create_concatenate_layer< GCDepthConcatenateLayer, GCTargetInfo >(), arm_compute::graph::backends::detail::create_eltwise_layer< GCEltwiseFunctions, GCTargetInfo >(), arm_compute::graph::backends::detail::validate_bounding_box_transform_layer(), arm_compute::graph::backends::detail::validate_channel_shuffle_layer(), arm_compute::graph::backends::detail::validate_convolution_layer(), arm_compute::graph::backends::detail::validate_depthwise_convolution_layer(), arm_compute::graph::backends::detail::validate_detection_output_layer(), arm_compute::graph::backends::detail::validate_generate_proposals_layer(), arm_compute::graph::backends::detail::validate_node(), arm_compute::graph::backends::detail::validate_normalize_planar_yuv_layer(), arm_compute::graph::backends::detail::validate_pad_layer(), arm_compute::graph::backends::detail::validate_permute_layer(), arm_compute::graph::backends::detail::validate_priorbox_layer(), arm_compute::graph::backends::detail::validate_reorg_layer(), arm_compute::graph::backends::detail::validate_roi_align_layer(), arm_compute::graph::backends::detail::validate_slice_layer(), arm_compute::graph::backends::detail::validate_upsample_layer(), and arm_compute::graph::backends::detail::validate_yolo_layer().
num_outputs()
size_t num_outputs () const
Returns number of outputs of the node.
Returns
Number of outputs
Definition at line 183 of file INode.cpp.
 {
     return _outputs.size();
 }
Referenced by arm_compute::graph::detail::allocate_all_output_tensors(), FullyConnectedLayerNode::compute_output_descriptor(), FullyConnectedLayerNode::compute_weights_descriptor(), arm_compute::graph::backends::detail::create_concatenate_layer(), arm_compute::graph::backends::detail::create_concatenate_layer< GCDepthConcatenateLayer, GCTargetInfo >(), arm_compute::graph::backends::detail::create_eltwise_layer< GCEltwiseFunctions, GCTargetInfo >(), arm_compute::graph::backends::detail::validate_bounding_box_transform_layer(), arm_compute::graph::backends::detail::validate_channel_shuffle_layer(), arm_compute::graph::backends::detail::validate_convolution_layer(), arm_compute::graph::backends::detail::validate_depthwise_convolution_layer(), arm_compute::graph::backends::detail::validate_detection_output_layer(), arm_compute::graph::backends::detail::validate_generate_proposals_layer(), arm_compute::graph::backends::detail::validate_node(), arm_compute::graph::backends::detail::validate_normalize_planar_yuv_layer(), arm_compute::graph::backends::detail::validate_pad_layer(), arm_compute::graph::backends::detail::validate_permute_layer(), arm_compute::graph::backends::detail::validate_priorbox_layer(), arm_compute::graph::backends::detail::validate_reorg_layer(), arm_compute::graph::backends::detail::validate_roi_align_layer(), arm_compute::graph::backends::detail::validate_slice_layer(), arm_compute::graph::backends::detail::validate_upsample_layer(), and arm_compute::graph::backends::detail::validate_yolo_layer().
operator=() [1/2]
INode& operator= (const INode &) delete
Prevent instances of this class from being copy assigned (As this class contains pointers)
operator=() [2/2]
INode& operator= (INode &&) default
Allow instances of this class to be move assigned.
output()
Tensor * output (size_t idx) const
Returns the tensor of a given output of the node.
Note
Precondition : idx should be a valid output index
Parameters
[in] idx Index of the node output
Returns
Tensor of the requested output
Definition at line 158 of file INode.cpp.
 {
     ARM_COMPUTE_ERROR_ON(_graph == nullptr);
     ARM_COMPUTE_ERROR_ON(idx >= _outputs.size());
     return _graph->tensor(_outputs[idx]);
 }
References ARM_COMPUTE_ERROR_ON, and Graph::tensor().
Referenced by arm_compute::graph::detail::allocate_all_output_tensors(), arm_compute::graph::backends::detail::create_activation_layer(), arm_compute::graph::backends::detail::create_batch_normalization_layer(), arm_compute::graph::backends::detail::create_bounding_box_transform_layer(), arm_compute::graph::backends::detail::create_channel_shuffle_layer(), arm_compute::graph::backends::detail::create_concatenate_layer(), arm_compute::graph::backends::detail::create_concatenate_layer< GCDepthConcatenateLayer, GCTargetInfo >(), arm_compute::graph::backends::detail::create_convolution_layer(), arm_compute::graph::backends::detail::create_convolution_layer< GCConvolutionLayerFunctions, GCTargetInfo >(), arm_compute::graph::backends::detail::create_convolution_layer< NEConvolutionLayerFunctions, NETargetInfo >(), arm_compute::graph::backends::detail::create_deconvolution_layer(), arm_compute::graph::backends::detail::create_depthwise_convolution_layer(), arm_compute::graph::backends::detail::create_depthwise_convolution_layer< GCDepthwiseConvolutionLayerFunctions, GCTargetInfo >(), arm_compute::graph::backends::detail::create_detection_output_layer(), arm_compute::graph::backends::detail::create_detection_output_layer< CPPDetectionOutputLayer, CLTargetInfo >(), arm_compute::graph::backends::detail::create_eltwise_layer(), arm_compute::graph::backends::detail::create_eltwise_layer< GCEltwiseFunctions, GCTargetInfo >(), arm_compute::graph::backends::detail::create_flatten_layer(), arm_compute::graph::backends::detail::create_fully_connected_layer(), arm_compute::graph::backends::detail::create_generate_proposals_layer(), arm_compute::graph::backends::detail::create_normalization_layer(), arm_compute::graph::backends::detail::create_normalization_layer< NENormalizationLayer, NETargetInfo >(), arm_compute::graph::backends::detail::create_normalize_planar_yuv_layer(), arm_compute::graph::backends::detail::create_pad_layer(), arm_compute::graph::backends::detail::create_permute_layer(), arm_compute::graph::backends::detail::create_pooling_layer(), arm_compute::graph::backends::detail::create_priorbox_layer(), arm_compute::graph::backends::detail::create_reorg_layer(), arm_compute::graph::backends::detail::create_reshape_layer(), arm_compute::graph::backends::detail::create_resize_layer(), arm_compute::graph::backends::detail::create_roi_align_layer(), arm_compute::graph::backends::detail::create_slice_layer(), arm_compute::graph::backends::detail::create_softmax_layer(), arm_compute::graph::backends::detail::create_upsample_layer(), arm_compute::graph::backends::detail::create_yolo_layer(), FlattenLayerNode::forward_descriptors(), NormalizePlanarYUVLayerNode::forward_descriptors(), InputNode::forward_descriptors(), ReshapeLayerNode::forward_descriptors(), ConstNode::forward_descriptors(), NormalizationLayerNode::forward_descriptors(), SoftmaxLayerNode::forward_descriptors(), ActivationLayerNode::forward_descriptors(), ChannelShuffleLayerNode::forward_descriptors(), PadLayerNode::forward_descriptors(), GenerateProposalsLayerNode::forward_descriptors(), BoundingBoxTransformLayerNode::forward_descriptors(), DummyNode::forward_descriptors(), PermuteLayerNode::forward_descriptors(), ResizeLayerNode::forward_descriptors(), YOLOLayerNode::forward_descriptors(), ROIAlignLayerNode::forward_descriptors(), PoolingLayerNode::forward_descriptors(), ReorgLayerNode::forward_descriptors(), PriorBoxLayerNode::forward_descriptors(), DetectionOutputLayerNode::forward_descriptors(), BatchNormalizationLayerNode::forward_descriptors(), EltwiseLayerNode::forward_descriptors(), UpsampleLayerNode::forward_descriptors(), DeconvolutionLayerNode::forward_descriptors(), SliceLayerNode::forward_descriptors(), SplitLayerNode::forward_descriptors(), ConcatenateLayerNode::forward_descriptors(), FullyConnectedLayerNode::forward_descriptors(), DepthwiseConvolutionLayerNode::forward_descriptors(), ConvolutionLayerNode::forward_descriptors(), SplitLayerSubTensorMutator::mutate(), DepthConcatSubTensorMutator::mutate(), GroupedConvolutionMutator::mutate(), arm_compute::graph::backends::detail::validate_bounding_box_transform_layer(), arm_compute::graph::backends::detail::validate_channel_shuffle_layer(), arm_compute::graph::backends::detail::validate_convolution_layer(), arm_compute::graph::backends::detail::validate_depthwise_convolution_layer(), arm_compute::graph::backends::detail::validate_detection_output_layer(), arm_compute::graph::backends::detail::validate_generate_proposals_layer(), arm_compute::graph::backends::detail::validate_normalize_planar_yuv_layer(), arm_compute::graph::backends::detail::validate_pad_layer(), arm_compute::graph::backends::detail::validate_permute_layer(), arm_compute::graph::backends::detail::validate_priorbox_layer(), arm_compute::graph::backends::detail::validate_reorg_layer(), arm_compute::graph::backends::detail::validate_roi_align_layer(), arm_compute::graph::backends::detail::validate_slice_layer(), arm_compute::graph::backends::detail::validate_upsample_layer(), and arm_compute::graph::backends::detail::validate_yolo_layer().
output_edges()
const std::set< EdgeID > & output_edges () const
Returns output edge set.
Returns
Set of output edges
Definition at line 132 of file INode.cpp.
 {
     return _output_edges;
 }
Referenced by arm_compute::graph::bfs(), arm_compute::graph::dfs(), arm_compute::graph::get_driving_nodes(), InPlaceOperationMutator::mutate(), and Graph::remove_node().
output_id()
TensorID output_id (size_t idx) const
Returns the tensor ID of a given output of the node.
Note
Precondition : idx should be a valid output index
Parameters
[in] idx Index of the node output
Returns
TensorID of the requested output
Definition at line 144 of file INode.cpp.
 {
     ARM_COMPUTE_ERROR_ON(idx >= _outputs.size());
     return _outputs[idx];
 }
References ARM_COMPUTE_ERROR_ON.
Referenced by FlattenLayerNode::forward_descriptors(), NormalizePlanarYUVLayerNode::forward_descriptors(), ReshapeLayerNode::forward_descriptors(), ConstNode::forward_descriptors(), InputNode::forward_descriptors(), ActivationLayerNode::forward_descriptors(), NormalizationLayerNode::forward_descriptors(), ChannelShuffleLayerNode::forward_descriptors(), SoftmaxLayerNode::forward_descriptors(), PadLayerNode::forward_descriptors(), BoundingBoxTransformLayerNode::forward_descriptors(), GenerateProposalsLayerNode::forward_descriptors(), PermuteLayerNode::forward_descriptors(), DummyNode::forward_descriptors(), ResizeLayerNode::forward_descriptors(), YOLOLayerNode::forward_descriptors(), ROIAlignLayerNode::forward_descriptors(), DetectionOutputLayerNode::forward_descriptors(), PoolingLayerNode::forward_descriptors(), ReorgLayerNode::forward_descriptors(), PriorBoxLayerNode::forward_descriptors(), BatchNormalizationLayerNode::forward_descriptors(), UpsampleLayerNode::forward_descriptors(), EltwiseLayerNode::forward_descriptors(), DeconvolutionLayerNode::forward_descriptors(), SliceLayerNode::forward_descriptors(), SplitLayerNode::forward_descriptors(), FullyConnectedLayerNode::forward_descriptors(), DepthwiseConvolutionLayerNode::forward_descriptors(), and ConvolutionLayerNode::forward_descriptors().
outputs()
const std::vector< TensorID > & outputs () const
Returns outputs of the node.
Returns
Outputs of the node
Definition at line 122 of file INode.cpp.
 {
     return _outputs;
 }
Referenced by GraphBuilder::add_batch_normalization_node(), GraphBuilder::add_convolution_node(), GraphBuilder::add_deconvolution_node(), GraphBuilder::add_depthwise_convolution_node(), GraphBuilder::add_fully_connected_layer(), GraphBuilder::add_normalize_planar_yuv_node(), GraphBuilder::add_scale_layer(), and SplitLayerSubTensorMutator::mutate().
requested_target()
Target requested_target () const
Returns requested target for this node.
Returns
Requested execution target
Definition at line 193 of file INode.cpp.
 {
     return _common_params.target;
 }
References NodeParams::target.
set_assigned_target()
void set_assigned_target (Target target)
Sets the final execution target.
Note
GraphManager might change this target
Parameters
[in] target Final execution target
Definition at line 71 of file INode.cpp.
 {
     _assigned_target = target;
 }
set_common_node_parameters()
void set_common_node_parameters (NodeParams common_params)
Sets common node parameters.
Parameters
[in] common_params Common node parameters to set
Definition at line 61 of file INode.cpp.
 {
     _common_params = std::move(common_params);
 }
set_graph()
void set_graph (Graph * g)
Sets the graph that this node is registered to.
Parameters
[in] g Back reference to graph
Definition at line 50 of file INode.cpp.
 {
     ARM_COMPUTE_ERROR_ON(g == nullptr);
     _graph = g;
 }
References ARM_COMPUTE_ERROR_ON.
Referenced by Graph::add_node().
set_id()
void set_id (NodeID id)
Sets the node id.
Parameters
[in] id Node id
Definition at line 56 of file INode.cpp.
 {
     _id = id;
 }
References INode::id().
Referenced by Graph::add_node().
set_output_tensor()
void set_output_tensor (TensorID tid, size_t idx)
Sets the output tensor of at a given index.
Note
All edges will get updated
Parameters
[in] tid Tensor ID
[in] idx Output index
Definition at line 76 of file INode.cpp.
 {
     if(tid != NullTensorID && (idx < _outputs.size()) && (_graph->tensor(tid) != nullptr))
     {
         ARM_COMPUTE_ERROR_ON(_graph == nullptr);
         Tensor *updated_tensor = _graph->tensor(tid);
         _outputs[idx]          = tid;
         // Set tensor to all output edges of the node
         for(auto &output_edge_id : _output_edges)
         {
             auto output_edge = _graph->edge(output_edge_id);
             if(output_edge != nullptr)
             {
                 // Unbind edge from current tensor
                 auto current_output_tensor = output_edge->tensor();
                 current_output_tensor->unbind_edge(output_edge->id());
                 // Update tensor to edge and rebind tensor
                 output_edge->update_bound_tensor(updated_tensor);
                 updated_tensor->bind_edge(output_edge->id());
             }
         }
     }
 }
References ARM_COMPUTE_ERROR_ON, Tensor::bind_edge(), Graph::edge(), arm_compute::graph::NullTensorID, Edge::tensor(), Graph::tensor(), and Tensor::unbind_edge().
set_requested_target()
void set_requested_target (Target target)
Sets target preference.
Note
This is not the target that the graph executor might choose, its just an indication
Parameters
[in] target Target preference
Definition at line 66 of file INode.cpp.
 {
     _common_params.target = target;
 }
References NodeParams::target.
type()
virtual NodeType type () const pure virtual
Returns node's type.
Returns
Node's type
Implemented in ConvolutionLayerNode, DepthwiseConvolutionLayerNode, FullyConnectedLayerNode, ConcatenateLayerNode, SplitLayerNode, SliceLayerNode, DeconvolutionLayerNode, EltwiseLayerNode, UpsampleLayerNode, BatchNormalizationLayerNode, DetectionOutputLayerNode, PoolingLayerNode, PriorBoxLayerNode, ReorgLayerNode, ROIAlignLayerNode, YOLOLayerNode, DummyNode, PermuteLayerNode, ResizeLayerNode, BoundingBoxTransformLayerNode, GenerateProposalsLayerNode, PadLayerNode, ActivationLayerNode, ChannelShuffleLayerNode, NormalizationLayerNode, SoftmaxLayerNode, ConstNode, InputNode, ReshapeLayerNode, FlattenLayerNode, NormalizePlanarYUVLayerNode, and OutputNode.
Referenced by Graph::add_node(), GCFunctionFactory::create(), CLFunctionFactory::create(), NEFunctionFactory::create(), DepthConcatSubTensorMutator::mutate(), GroupedConvolutionMutator::mutate(), SplitLayerSubTensorMutator::mutate(), Graph::remove_node(), NENodeValidator::validate(), CLNodeValidator::validate(), GCNodeValidator::validate(), and arm_compute::graph::backends::detail::validate_node().
validate()
Status validate () const virtual
Validate node.
Returns
Status containing any errors
Reimplemented in SplitLayerNode.
Definition at line 45 of file INode.cpp.
 {
     return Status{};
 }
Friends And Related Function Documentation
Graph
friend class Graph friend
Definition at line 244 of file INode.h.
The documentation for this class was generated from the following files:
arm_compute/graph/INode.h
src/graph/INode.cpp