Compute Library: CLWidthConcatenateLayer Class Reference
CLWidthConcatenateLayer Class Reference
Basic function to execute concatenate tensors along x axis.
#include <CLWidthConcatenateLayer.h>
Public Member Functions
CLWidthConcatenateLayer ()
Default constructor.
void configure (std::vector< ICLTensor * > inputs_vector, ICLTensor *output)
Initialise the kernel's inputs vector and output.
void run () override
Run the kernels contained in the function.
Public Member Functions inherited from IFunction
virtual ~IFunction ()=default
Destructor.
virtual void prepare ()
Prepare the function for executing.
Static Public Member Functions
static Status validate (const std::vector< ITensorInfo * > &inputs_vector, const ITensorInfo *output)
Static function to check if given info will lead to a valid configuration of CLDepthConcatenateLayerKernel.
Detailed Description
Basic function to execute concatenate tensors along x axis.
This function calls the following kernel:
CLWidthConcatenateLayerKernel
CLWidthConcatenate2TensorsKernel (if there are exactly 2 input tensors)
CLWidthConcatenate4TensorsKernel (if there are exactly 4 input tensors)
Definition at line 50 of file CLWidthConcatenateLayer.h.
Constructor & Destructor Documentation
CLWidthConcatenateLayer()
CLWidthConcatenateLayer ()
Default constructor.
Definition at line 37 of file CLWidthConcatenateLayer.cpp.
     : _concat_kernels_vector(),
       _concat_x2_kernel(),
       _concat_x4_kernel(),
       _num_inputs(0)
 {
 }
Member Function Documentation
configure()
void configure (std::vector< ICLTensor * > inputs_vector, ICLTensor * output)
Initialise the kernel's inputs vector and output.
Parameters
[in] inputs_vector The vectors containing all the tensors to concatenate. Data types supported: QASYMM8/F16/F32. Dimensions of all the inputs should match apart for the width which can differ.
[out] output Output tensor. Data types supported: Same as input. Output tensor dimensions are the same with the inputs from the second dimension and above. The first dimension (width) is the sum of the input tensors' widths.
Definition at line 84 of file CLWidthConcatenateLayer.cpp.
 {
     _num_inputs = inputs_vector.size();
     std::vector<ITensorInfo *> inputs_vector_info;
     for(unsigned int i = 0; i < _num_inputs; i++)
     {
         inputs_vector_info.emplace_back(inputs_vector.at(i)->info());
     }
     const TensorShape output_shape = arm_compute::misc::shape_calculator::calculate_width_concatenate_shape(inputs_vector);
     // Output auto inizialitation if not yet initialized
     auto_init_if_empty(*output->info(), output_shape, 1, inputs_vector[0]->info()->data_type());
     ARM_COMPUTE_ERROR_THROW_ON(CLWidthConcatenateLayer::validate(inputs_vector_info, output->info()));
     switch(_num_inputs)
     {
         case 2:
             // Configure WidthConcatenate2Tensors kernel
             _concat_x2_kernel.configure(inputs_vector.at(0), inputs_vector.at(1), output);
             break;
         case 4:
             // Configure WidthConcatenate4Tensors kernel
             _concat_x4_kernel.configure(inputs_vector.at(0), inputs_vector.at(1), inputs_vector.at(2), inputs_vector.at(3), output);
             break;
         default:
             // Configure generic case WidthConcatenate kernels
             _concat_kernels_vector = arm_compute::support::cpp14::make_unique<CLWidthConcatenateLayerKernel[]>(_num_inputs);
             unsigned int width_offset = 0;
             for(unsigned int i = 0; i < _num_inputs; ++i)
             {
                 _concat_kernels_vector[i].configure(inputs_vector.at(i), width_offset, output);
                 width_offset += inputs_vector.at(i)->info()->dimension(0);
             }
             break;
     }
 }
References ARM_COMPUTE_ERROR_THROW_ON, arm_compute::auto_init_if_empty(), arm_compute::misc::shape_calculator::calculate_width_concatenate_shape(), CLWidthConcatenate2TensorsKernel::configure(), CLWidthConcatenate4TensorsKernel::configure(), ITensor::info(), arm_compute::test::validation::output_shape, and CLWidthConcatenateLayer::validate().
Referenced by CLLSTMLayer::configure().
run()
void run () override virtual
Run the kernels contained in the function.
For NEON kernels:
Multi-threading is used for the kernels which are parallelisable.
By default std::thread::hardware_concurrency() threads are used.
Note
CPPScheduler::set_num_threads() can be used to manually set the number of threads
For OpenCL kernels:
All the kernels are enqueued on the queue associated with CLScheduler.
The queue is then flushed.
Note
The function will not block until the kernels are executed. It is the user's responsibility to wait.
Will call prepare() on first run if hasn't been done
Implements IFunction.
Definition at line 124 of file CLWidthConcatenateLayer.cpp.
 {
     cl::CommandQueue q = CLScheduler::get().queue();
     switch(_num_inputs)
     {
         case 2:
             CLScheduler::get().enqueue(_concat_x2_kernel, true);
             break;
         case 4:
             CLScheduler::get().enqueue(_concat_x4_kernel, true);
             break;
         default:
             for(unsigned int i = 0; i < _num_inputs; ++i)
             {
                 CLScheduler::get().enqueue(_concat_kernels_vector[i], true);
             }
             break;
     }
 }
References CLScheduler::enqueue(), CLScheduler::get(), and CLScheduler::queue().
Referenced by CLLSTMLayer::run().
validate()
Status validate (const std::vector< ITensorInfo * > & inputs_vector, const ITensorInfo * output) static
Static function to check if given info will lead to a valid configuration of CLDepthConcatenateLayerKernel.
Parameters
[in] inputs_vector The vectors containing all the tensors to concatenate. Data types supported: QASYMM8/F16/F32. Dimensions of all the inputs should match apart for the width which can differ.
[in] output Output tensor. Data types supported: Same as input. Output tensor dimensions are the same with the inputs from the second dimension and above. The first dimension (width) is the sum of the input tensors' widths.
Returns
a status
Definition at line 45 of file CLWidthConcatenateLayer.cpp.
 {
     const unsigned int num_inputs = inputs_vector.size();
     ARM_COMPUTE_RETURN_ERROR_ON_NULLPTR(output);
     ARM_COMPUTE_RETURN_ERROR_ON(num_inputs < 2);
     // Output auto inizialitation if not yet initialized
     TensorInfo        tmp_output_info = *output->clone();
     const TensorShape output_shape    = arm_compute::misc::shape_calculator::calculate_width_concatenate_shape(inputs_vector);
     auto_init_if_empty(tmp_output_info, output_shape, 1, inputs_vector[0]->data_type());
     switch(num_inputs)
     {
         case 2:
             // Validate WidthConcatenate2Tensors kernels if there are 2 inputs
             ARM_COMPUTE_RETURN_ERROR_ON_NULLPTR(inputs_vector[0], inputs_vector[1]);
             ARM_COMPUTE_RETURN_ON_ERROR(CLWidthConcatenate2TensorsKernel::validate(inputs_vector[0], inputs_vector[1], &tmp_output_info));
             break;
         case 4:
             // Validate WidthConcatenate4Tensors kernels if there are 4 inputs
             ARM_COMPUTE_RETURN_ERROR_ON_NULLPTR(inputs_vector[0], inputs_vector[1], inputs_vector[2], inputs_vector[3]);
             ARM_COMPUTE_RETURN_ON_ERROR(CLWidthConcatenate4TensorsKernel::validate(inputs_vector[0], inputs_vector[1], inputs_vector[2], inputs_vector[3], &tmp_output_info));
             break;
         default:
             unsigned int width_offset = 0;
             // Validate generic case of WidthConcatenate kernel
             for(const auto &input : inputs_vector)
             {
                 ARM_COMPUTE_RETURN_ERROR_ON_NULLPTR(input);
                 ARM_COMPUTE_RETURN_ON_ERROR(CLWidthConcatenateLayerKernel::validate(input, width_offset, &tmp_output_info));
                 width_offset += input->dimension(0);
             }
             break;
     }
     return Status{};
 }
References ARM_COMPUTE_RETURN_ERROR_ON, ARM_COMPUTE_RETURN_ERROR_ON_NULLPTR, ARM_COMPUTE_RETURN_ON_ERROR, arm_compute::auto_init_if_empty(), arm_compute::misc::shape_calculator::calculate_width_concatenate_shape(), ICloneable< T >::clone(), arm_compute::test::validation::data_type, arm_compute::test::validation::output_shape, CLWidthConcatenate2TensorsKernel::validate(), CLWidthConcatenateLayerKernel::validate(), and CLWidthConcatenate4TensorsKernel::validate().
Referenced by CLWidthConcatenateLayer::configure(), CLConcatenateLayer::validate(), and CLLSTMLayer::validate().
The documentation for this class was generated from the following files:
arm_compute/runtime/CL/functions/CLWidthConcatenateLayer.h
src/runtime/CL/functions/CLWidthConcatenateLayer.cpp