Compute Library: ScaleFixture< TensorType, Function, Accessor > Class Template Reference
ScaleFixture< TensorType, Function, Accessor > Class Template Reference
#include <ScaleFixture.h>
Public Member Functions
template<typename... >
void setup (TensorShape shape, DataType data_type, InterpolationPolicy policy, BorderMode border_mode, SamplingPolicy sampling_policy)
void run ()
void sync ()
void teardown ()
Public Member Functions inherited from Fixture
void setup ()
Setup function.
void teardown ()
Teardown function.
Detailed Description
template<typename TensorType, typename Function, typename Accessor>
class arm_compute::test::benchmark::ScaleFixture< TensorType, Function, Accessor >
Definition at line 40 of file ScaleFixture.h.
Member Function Documentation
void run () inline
Definition at line 76 of file ScaleFixture.h.
     {
         scale_func.run();
     }
void setup (TensorShape shape, DataType data_type, InterpolationPolicy policy, BorderMode border_mode, SamplingPolicy sampling_policy) inline
Definition at line 44 of file ScaleFixture.h.
References arm_compute::test::validation::data_type, arm_compute::test::library, TensorShape::set(), arm_compute::test::validation::shape, Dimensions< T >::x(), and Dimensions< T >::y().
     {
         constexpr float max_width  = 8192.0f;
         constexpr float max_height = 6384.0f;
         std::mt19937                          generator(library->seed());
         std::uniform_real_distribution<float> distribution_float(0.25f, 3.0f);
         float                                 scale_x = distribution_float(generator);
         float                                 scale_y = distribution_float(generator);
         scale_x = ((shape.x() * scale_x) > max_width) ? (max_width / shape.x()) : scale_x;
         scale_y = ((shape.y() * scale_y) > max_height) ? (max_height / shape.y()) : scale_y;
         std::uniform_int_distribution<uint8_t> distribution_u8(0, 255);
         uint8_t                                constant_border_value = static_cast<uint8_t>(distribution_u8(generator));
         TensorShape shape_scaled(shape);
         shape_scaled.set(0, shape[0] * scale_x);
         shape_scaled.set(1, shape[1] * scale_y);
         // Create tensors
         src = create_tensor<TensorType>(shape, data_type);
         dst = create_tensor<TensorType>(shape_scaled, data_type);
         // Create and configure function
         scale_func.configure(&src, &dst, policy, border_mode, constant_border_value, sampling_policy);
         // Allocate tensors
         src.allocator()->allocate();
         dst.allocator()->allocate();
     }
void sync () inline
Definition at line 81 of file ScaleFixture.h.
     {
         sync_if_necessary<TensorType>();
         sync_tensor_if_necessary<TensorType>(dst);
     }
void teardown () inline
Definition at line 87 of file ScaleFixture.h.
     {
         src.allocator()->free();
         dst.allocator()->free();
     }
The documentation for this class was generated from the following file:
tests/benchmark/fixtures/ScaleFixture.h