Compute Library: GCKernel Class Reference
GCKernel Class Reference
GCKernel class.
#include <GCKernelLibrary.h>
Public Member Functions
GCKernel ()
Default Constructor.
GCKernel (const GCKernel &)=default
Default Copy Constructor.
GCKernel (GCKernel &&)=default
Default Move Constructor.
GCKernel & operator= (const GCKernel &)=default
Default copy assignment operator.
GCKernel & operator= (GCKernel &&)=default
Default move assignment operator.
GCKernel (std::string name, GLuint program)
Constructor.
~GCKernel ()
Destructor.
std::string name () const
Returns kernel name.
GLuint get_program () const
Get program id.
void use ()
Use current program.
void unuse ()
Unuse current program.
template<class T >
void set_argument (unsigned int idx, T value)
Set argument value at index of shader params.
void clear_arguments ()
Clear shader arguments.
void set_shader_params_binding_point (unsigned int binding)
Set shader params binding point.
void update_shader_params ()
Update shader params.
void cleanup ()
Clean up program and ubo.
Detailed Description
GCKernel class.
Definition at line 87 of file GCKernelLibrary.h.
Constructor & Destructor Documentation
GCKernel() [1/4]
GCKernel ()
Default Constructor.
Definition at line 131 of file GCKernelLibrary.cpp.
     : _name(), _program(), _shader_arguments(), _shader_params_ubo_name(), _shader_params_binding_point(), _shader_params_index(), _shader_params_size()
 {
 }
GCKernel() [2/4]
GCKernel (const GCKernel &) default
Default Copy Constructor.
GCKernel() [3/4]
GCKernel (GCKernel &&) default
Default Move Constructor.
GCKernel() [4/4]
GCKernel (std::string name, GLuint program)
Constructor.
Parameters
[in] name Kernel name.
[in] program Built program.
Definition at line 141 of file GCKernelLibrary.cpp.
     : _name(std::move(name)),
       _program(program),
       _shader_arguments(),
       _shader_params_ubo_name(0),
       _shader_params_binding_point(0),
       _shader_params_index(0),
       _shader_params_size(0)
 {
     _shader_arguments.clear();
     ARM_COMPUTE_GL_CHECK(glGenBuffers(1, &_shader_params_ubo_name));
     _shader_params_index = ARM_COMPUTE_GL_CHECK(glGetUniformBlockIndex(_program, _shader_params_name));
     ARM_COMPUTE_ERROR_ON_MSG(_shader_params_index == GL_INVALID_INDEX, "Failed to get index of %s", _shader_params_name);
     ARM_COMPUTE_GL_CHECK(glGetActiveUniformBlockiv(_program, _shader_params_index, GL_UNIFORM_BLOCK_DATA_SIZE, &_shader_params_size));
     ARM_COMPUTE_ERROR_ON_MSG(_shader_params_size == 0, "Failed to get size of %s", _shader_params_name);
 }
References ARM_COMPUTE_ERROR_ON_MSG, ARM_COMPUTE_GL_CHECK, glGenBuffers(), glGetActiveUniformBlockiv(), and glGetUniformBlockIndex().
~GCKernel()
~GCKernel ()
Destructor.
Definition at line 137 of file GCKernelLibrary.cpp.
 {
 }
Member Function Documentation
cleanup()
void cleanup ()
Clean up program and ubo.
Definition at line 160 of file GCKernelLibrary.cpp.
 {
     ARM_COMPUTE_GL_CHECK(glDeleteBuffers(1, &_shader_params_ubo_name));
     ARM_COMPUTE_GL_CHECK(glBindBuffer(GL_UNIFORM_BUFFER, 0));
     ARM_COMPUTE_GL_CHECK(glDeleteProgram(_program));
     ARM_COMPUTE_GL_CHECK(glUseProgram(0));
 }
References ARM_COMPUTE_GL_CHECK, glBindBuffer(), glDeleteBuffers(), glDeleteProgram(), and glUseProgram().
clear_arguments()
void clear_arguments () inline
Clear shader arguments.
Definition at line 154 of file GCKernelLibrary.h.
     {
         _shader_arguments.clear();
     }
Referenced by GCKernelLibrary::create_kernel().
get_program()
GLuint get_program () const inline
Get program id.
Returns
program id.
Definition at line 121 of file GCKernelLibrary.h.
     {
         return _program;
     }
Referenced by arm_compute::enqueue().
name()
std::string name () const inline
Returns kernel name.
Returns
Kernel's name.
Definition at line 113 of file GCKernelLibrary.h.
     {
         return _name;
     }
operator=() [1/2]
GCKernel& operator= (const GCKernel &) default
Default copy assignment operator.
operator=() [2/2]
GCKernel& operator= (GCKernel &&) default
Default move assignment operator.
set_argument()
void set_argument (unsigned int idx, T value) inline
Set argument value at index of shader params.
Parameters
[in] idx Index in shader params.
[in] value Argument value to be set.
Definition at line 141 of file GCKernelLibrary.h.
     {
         if(idx >= _shader_arguments.size())
         {
             _shader_arguments.resize(idx + 1, 0);
         }
         unsigned int *p        = reinterpret_cast<unsigned int *>(&value);
         _shader_arguments[idx] = *p;
     }
set_shader_params_binding_point()
void set_shader_params_binding_point (unsigned int binding) inline
Set shader params binding point.
Parameters
[in] binding Shader params binding point.
Definition at line 162 of file GCKernelLibrary.h.
     {
         _shader_params_binding_point = binding;
     }
Referenced by GCKernelLibrary::create_kernel().
unuse()
void unuse ()
Unuse current program.
Returns
program id.
Definition at line 173 of file GCKernelLibrary.cpp.
 {
     ARM_COMPUTE_GL_CHECK(glUseProgram(0));
 }
References ARM_COMPUTE_GL_CHECK, and glUseProgram().
update_shader_params()
void update_shader_params ()
Update shader params.
Definition at line 178 of file GCKernelLibrary.cpp.
 {
     ARM_COMPUTE_ERROR_ON_MSG((_shader_params_size != (int)(_shader_arguments.size() * sizeof(_shader_arguments[0]))), "Arguments size (%d) is not equal to shader params block size (%d)",
                              _shader_arguments.size() * sizeof(_shader_arguments[0]), _shader_params_size);
     ARM_COMPUTE_GL_CHECK(glUniformBlockBinding(_program, _shader_params_index, _shader_params_binding_point));
     ARM_COMPUTE_GL_CHECK(glBindBufferBase(GL_UNIFORM_BUFFER, _shader_params_binding_point, _shader_params_ubo_name));
     ARM_COMPUTE_GL_CHECK(glBindBuffer(GL_UNIFORM_BUFFER, _shader_params_ubo_name));
     ARM_COMPUTE_GL_CHECK(glBufferData(GL_UNIFORM_BUFFER, _shader_params_size, _shader_arguments.data(), GL_DYNAMIC_DRAW));
     ARM_COMPUTE_GL_CHECK(glBindBuffer(GL_UNIFORM_BUFFER, 0));
 }
References ARM_COMPUTE_ERROR_ON_MSG, ARM_COMPUTE_GL_CHECK, glBindBuffer(), glBindBufferBase(), glBufferData(), and glUniformBlockBinding().
use()
void use ()
Use current program.
Returns
program id.
Definition at line 168 of file GCKernelLibrary.cpp.
 {
     ARM_COMPUTE_GL_CHECK(glUseProgram(_program));
 }
References ARM_COMPUTE_GL_CHECK, and glUseProgram().
Referenced by GCKernelLibrary::create_kernel().
The documentation for this class was generated from the following files:
arm_compute/core/GLES_COMPUTE/GCKernelLibrary.h
src/core/GLES_COMPUTE/GCKernelLibrary.cpp