Compute Library: NENonLinearFilterKernel Class Reference
NENonLinearFilterKernel Class Reference
Interface for the kernel to apply a non-linear filter.
#include <NENonLinearFilterKernel.h>
Public Member Functions
const char * name () const override
Name of the kernel.
NENonLinearFilterKernel ()
Default constructor.
NENonLinearFilterKernel (NENonLinearFilterKernel &)=delete
Prevent instances of this class from being copied (As this class contains pointers)
NENonLinearFilterKernel & operator= (NENonLinearFilterKernel &)=delete
Prevent instances of this class from being copied (As this class contains pointers)
NENonLinearFilterKernel (NENonLinearFilterKernel &&)=default
Allow instances of this class to be moved.
NENonLinearFilterKernel & operator= (NENonLinearFilterKernel &&)=default
Allow instances of this class to be moved.
void configure (const ITensor *input, ITensor *output, NonLinearFilterFunction function, unsigned int mask_size, MatrixPattern pattern, const uint8_t *mask, bool border_undefined)
Set the source, destination and border mode of the kernel.
void run (const Window &window, const ThreadInfo &info) override
Execute the kernel on the passed window.
BorderSize border_size () const override
The size of the border for that kernel.
Public Member Functions inherited from ICPPKernel
virtual ~ICPPKernel ()=default
Default destructor.
Public Member Functions inherited from IKernel
IKernel ()
Constructor.
virtual ~IKernel ()=default
Destructor.
virtual bool is_parallelisable () const
Indicates whether or not the kernel is parallelisable.
const Window & window () const
The maximum window the kernel can be executed on.
Detailed Description
Interface for the kernel to apply a non-linear filter.
Definition at line 37 of file NENonLinearFilterKernel.h.
Constructor & Destructor Documentation
NENonLinearFilterKernel() [1/3]
NENonLinearFilterKernel ()
Default constructor.
Definition at line 343 of file NENonLinearFilterKernel.cpp.
     : _border_width(0), _input(nullptr), _output(nullptr), _mask(nullptr), _pattern(MatrixPattern::BOX), _function(NonLinearFilterFunction::MIN), _func_idx(0), _border_size()
 {
 }
References arm_compute::BOX, and MIN.
NENonLinearFilterKernel() [2/3]
NENonLinearFilterKernel (NENonLinearFilterKernel &) delete
Prevent instances of this class from being copied (As this class contains pointers)
NENonLinearFilterKernel() [3/3]
NENonLinearFilterKernel (NENonLinearFilterKernel &&) default
Allow instances of this class to be moved.
Member Function Documentation
border_size()
BorderSize border_size () const override virtual
The size of the border for that kernel.
Returns
The width in number of elements of the border.
Reimplemented from IKernel.
Definition at line 348 of file NENonLinearFilterKernel.cpp.
 {
     return _border_size;
 }
Referenced by NENonLinearFilterKernel::configure().
configure()
void configure (const ITensor * input, ITensor * output, NonLinearFilterFunction function, unsigned int mask_size, MatrixPattern pattern, const uint8_t * mask, bool border_undefined)
Set the source, destination and border mode of the kernel.
Parameters
[in] input Source tensor. Data type supported: U8
[out] output Destination tensor. Data type supported: U8
[in] function Non linear function to perform
[in] mask_size Mask size. Supported sizes: 3, 5
[in] pattern Mask pattern
[in] mask The given mask. Will be used only if pattern is specified to PATTERN_OTHER
[in] border_undefined True if the border mode is undefined. False if it's replicate or constant.
Definition at line 353 of file NENonLinearFilterKernel.cpp.
 {
     ARM_COMPUTE_ERROR_ON_DATA_TYPE_CHANNEL_NOT_IN(input, 1, DataType::U8);
     ARM_COMPUTE_ERROR_ON_DATA_TYPE_CHANNEL_NOT_IN(output, 1, DataType::U8);
     ARM_COMPUTE_ERROR_ON(3 != mask_size && 5 != mask_size);
     ARM_COMPUTE_ERROR_ON(MatrixPattern::OTHER == pattern && nullptr == mask);
     // Set class variables
     _border_size = BorderSize(mask_size / 2);
     _input       = input;
     _output      = output;
     _mask        = mask;
     _pattern     = pattern;
     _function    = function;
     // Configure kernel window
     const unsigned int     num_elems_processed_per_iteration = (MatrixPattern::OTHER == pattern) ? 1 : 8;
     constexpr unsigned int num_elems_read_per_iteration      = 16;
     Window                 win = calculate_max_window(*input->info(), num_elems_processed_per_iteration, border_undefined, border_size());
     AccessWindowHorizontal output_access(output->info(), 0, num_elems_processed_per_iteration);
     update_window_and_padding(win,
                               AccessWindowRectangle(input->info(), -border_size().left, -border_size().top, num_elems_read_per_iteration, mask_size),
                               output_access);
     output_access.set_valid_region(win, input->info()->valid_region(), border_undefined, border_size());
     INEKernel::configure(win);
     // Define function index
     _func_idx = (3 == mask_size) ? 0 : 1;
     if(MatrixPattern::OTHER != pattern)
     {
         _func_idx = (_func_idx) * 3 + static_cast<unsigned int>(function);
     }
 }
References ARM_COMPUTE_ERROR_ON, ARM_COMPUTE_ERROR_ON_DATA_TYPE_CHANNEL_NOT_IN, NENonLinearFilterKernel::border_size(), arm_compute::calculate_max_window(), ITensor::info(), BorderSize::left, arm_compute::OTHER, BorderSize::top, arm_compute::U8, arm_compute::update_window_and_padding(), and ITensorInfo::valid_region().
name()
const char* name () const inline override virtual
Name of the kernel.
Returns
Kernel name
Implements ICPPKernel.
Definition at line 40 of file NENonLinearFilterKernel.h.
     {
         return "NENonLinearFilterKernel";
     }
operator=() [1/2]
NENonLinearFilterKernel& operator= (NENonLinearFilterKernel &) delete
Prevent instances of this class from being copied (As this class contains pointers)
operator=() [2/2]
NENonLinearFilterKernel& operator= (NENonLinearFilterKernel &&) default
Allow instances of this class to be moved.
run()
void run (const Window & window, const ThreadInfo & info) override virtual
Execute the kernel on the passed window.
Warning
If is_parallelisable() returns false then the passed window must be equal to window()
Note
The window has to be a region within the window returned by the window() method
The width of the window has to be a multiple of num_elems_processed_per_iteration().
Parameters
[in] window Region on which to execute the kernel. (Must be a region of the window returned by window())
[in] info Info about executing thread and CPU.
Implements ICPPKernel.
Definition at line 939 of file NENonLinearFilterKernel.cpp.
 {
     ARM_COMPUTE_UNUSED(info);
     ARM_COMPUTE_ERROR_ON_UNCONFIGURED_KERNEL(this);
     ARM_COMPUTE_ERROR_ON_INVALID_SUBWINDOW(INEKernel::window(), window);
     using NonLinearFilterFunction = void (NENonLinearFilterKernel::*)(const Window & window);
     // Function table for BOX pattern
     static const std::array<NonLinearFilterFunction, 6> func_table_box =
     {
         {
             &NENonLinearFilterKernel::median_filter_box<3, 3>,
             &NENonLinearFilterKernel::min_filter_box<3, 3>,
             &NENonLinearFilterKernel::max_filter_box<3, 3>,
             &NENonLinearFilterKernel::median_filter_box<5, 5>,
             &NENonLinearFilterKernel::min_filter_box<5, 5>,
             &NENonLinearFilterKernel::max_filter_box<5, 5>,
         }
     };
     // Function table for CROSS pattern
     static const std::array<NonLinearFilterFunction, 6> func_table_cross =
     {
         {
             &NENonLinearFilterKernel::median_filter_cross<3, 3>,
             &NENonLinearFilterKernel::min_filter_cross<3, 3>,
             &NENonLinearFilterKernel::max_filter_cross<3, 3>,
             &NENonLinearFilterKernel::median_filter_cross<5, 5>,
             &NENonLinearFilterKernel::min_filter_cross<5, 5>,
             &NENonLinearFilterKernel::max_filter_cross<5, 5>,
         }
     };
     // Function table for DISK pattern
     static const std::array<NonLinearFilterFunction, 6> func_table_disk =
     {
         {
             &NENonLinearFilterKernel::median_filter_box<3, 3>,
             &NENonLinearFilterKernel::min_filter_box<3, 3>,
             &NENonLinearFilterKernel::max_filter_box<3, 3>,
             &NENonLinearFilterKernel::median_filter_disk<5, 5>,
             &NENonLinearFilterKernel::min_filter_disk<5, 5>,
             &NENonLinearFilterKernel::max_filter_disk<5, 5>,
         }
     };
     // Function table for OTHER pattern
     static const std::array<NonLinearFilterFunction, 2> func_table_generic =
     {
         {
             &NENonLinearFilterKernel::non_linear_filter_generic<3, 3>,
             &NENonLinearFilterKernel::non_linear_filter_generic<5, 5>,
         }
     };
     switch(_pattern)
     {
         case MatrixPattern::BOX:
             ARM_COMPUTE_ERROR_ON(_func_idx >= func_table_box.size());
             (this->*func_table_box[_func_idx])(window);
             break;
         case MatrixPattern::CROSS:
             ARM_COMPUTE_ERROR_ON(_func_idx >= func_table_cross.size());
             (this->*func_table_cross[_func_idx])(window);
             break;
         case MatrixPattern::DISK:
             ARM_COMPUTE_ERROR_ON(_func_idx >= func_table_disk.size());
             (this->*func_table_disk[_func_idx])(window);
             break;
         case MatrixPattern::OTHER:
         default:
             ARM_COMPUTE_ERROR_ON(_func_idx >= func_table_generic.size());
             (this->*func_table_generic[_func_idx])(window);
             break;
     }
 }
References ARM_COMPUTE_ERROR_ON, ARM_COMPUTE_ERROR_ON_INVALID_SUBWINDOW, ARM_COMPUTE_ERROR_ON_UNCONFIGURED_KERNEL, ARM_COMPUTE_UNUSED, arm_compute::BOX, arm_compute::CROSS, arm_compute::DISK, arm_compute::test::validation::info, arm_compute::OTHER, and IKernel::window().
The documentation for this class was generated from the following files:
arm_compute/core/NEON/kernels/NENonLinearFilterKernel.h
src/core/NEON/kernels/NENonLinearFilterKernel.cpp