Compute Library: CLDeconvolutionLayerUpsampleKernel Class Reference
CLDeconvolutionLayerUpsampleKernel Class Reference
Interface for the Deconvolution layer kernel on OpenCL.
#include <CLDeconvolutionLayerUpsampleKernel.h>
Public Member Functions
CLDeconvolutionLayerUpsampleKernel ()
Constructor.
CLDeconvolutionLayerUpsampleKernel (const CLDeconvolutionLayerUpsampleKernel &)=delete
Prevent instances of this class from being copied (As this class contains pointers)
CLDeconvolutionLayerUpsampleKernel & operator= (const CLDeconvolutionLayerUpsampleKernel &)=delete
Prevent instances of this class from being copied (As this class contains pointers)
CLDeconvolutionLayerUpsampleKernel (CLDeconvolutionLayerUpsampleKernel &&)=default
Default Move Constructor.
CLDeconvolutionLayerUpsampleKernel & operator= (CLDeconvolutionLayerUpsampleKernel &&)=default
Default move assignment operator.
~CLDeconvolutionLayerUpsampleKernel ()=default
Default destructor.
void configure (const ICLTensor *input, ICLTensor *output, const BorderSize &inner_border, const PadStrideInfo &info)
Initialise the kernel's input and output.
void run (const Window &window, cl::CommandQueue &queue) override
Enqueue the OpenCL kernel to process the given window on the passed OpenCL command queue.
Public Member Functions inherited from ICLKernel
ICLKernel ()
Constructor.
cl::Kernel & kernel ()
Returns a reference to the OpenCL kernel of this object.
template<typename T >
void add_1D_array_argument (unsigned int &idx, const ICLArray< T > *array, const Strides &strides, unsigned int num_dimensions, const Window &window)
Add the passed 1D array's parameters to the object's kernel's arguments starting from the index idx.
void add_1D_tensor_argument (unsigned int &idx, const ICLTensor *tensor, const Window &window)
Add the passed 1D tensor's parameters to the object's kernel's arguments starting from the index idx.
void add_2D_tensor_argument (unsigned int &idx, const ICLTensor *tensor, const Window &window)
Add the passed 2D tensor's parameters to the object's kernel's arguments starting from the index idx.
void add_3D_tensor_argument (unsigned int &idx, const ICLTensor *tensor, const Window &window)
Add the passed 3D tensor's parameters to the object's kernel's arguments starting from the index idx.
void add_4D_tensor_argument (unsigned int &idx, const ICLTensor *tensor, const Window &window)
Add the passed 4D tensor's parameters to the object's kernel's arguments starting from the index idx.
template<typename T >
void add_argument (unsigned int &idx, T value)
Add the passed parameters to the object's kernel's arguments starting from the index idx.
void set_lws_hint (const cl::NDRange &lws_hint)
Set the Local-Workgroup-Size hint.
cl::NDRange lws_hint () const
Return the Local-Workgroup-Size hint.
const std::string & config_id () const
Get the configuration ID.
void set_target (GPUTarget target)
Set the targeted GPU architecture.
void set_target (cl::Device &device)
Set the targeted GPU architecture according to the CL device.
GPUTarget get_target () const
Get the targeted GPU architecture.
size_t get_max_workgroup_size ()
Get the maximum workgroup size for the device the CLKernelLibrary uses.
template<typename T , unsigned int dimension_size>
void add_array_argument (unsigned &idx, const ICLArray< T > *array, const Strides &strides, unsigned int num_dimensions, const Window &window)
Add the passed array's parameters to the object's kernel's arguments starting from the index idx.
template<unsigned int dimension_size>
void add_tensor_argument (unsigned &idx, const ICLTensor *tensor, const Window &window)
Public Member Functions inherited from IKernel
IKernel ()
Constructor.
virtual ~IKernel ()=default
Destructor.
virtual bool is_parallelisable () const
Indicates whether or not the kernel is parallelisable.
virtual BorderSize border_size () const
The size of the border for that kernel.
const Window & window () const
The maximum window the kernel can be executed on.
Static Public Member Functions
static Status validate (const ITensorInfo *input, const ITensorInfo *output, const BorderSize &inner_border, const PadStrideInfo &info)
Static function to check if given info will lead to a valid configuration of CLDeconvolutionLayerUpsample.
Static Public Member Functions inherited from ICLKernel
static constexpr unsigned int num_arguments_per_1D_array ()
Returns the number of arguments enqueued per 1D array object.
static constexpr unsigned int num_arguments_per_1D_tensor ()
Returns the number of arguments enqueued per 1D tensor object.
static constexpr unsigned int num_arguments_per_2D_tensor ()
Returns the number of arguments enqueued per 2D tensor object.
static constexpr unsigned int num_arguments_per_3D_tensor ()
Returns the number of arguments enqueued per 3D tensor object.
static constexpr unsigned int num_arguments_per_4D_tensor ()
Returns the number of arguments enqueued per 4D tensor object.
static cl::NDRange gws_from_window (const Window &window)
Get the global work size given an execution window.
Detailed Description
Interface for the Deconvolution layer kernel on OpenCL.
Definition at line 35 of file CLDeconvolutionLayerUpsampleKernel.h.
Constructor & Destructor Documentation
CLDeconvolutionLayerUpsampleKernel() [1/3]
CLDeconvolutionLayerUpsampleKernel ()
Constructor.
Definition at line 37 of file CLDeconvolutionLayerUpsampleKernel.cpp.
     : _input(nullptr), _output(nullptr), _inner_border(), _info()
 {
 }
CLDeconvolutionLayerUpsampleKernel() [2/3]
CLDeconvolutionLayerUpsampleKernel (const CLDeconvolutionLayerUpsampleKernel &) delete
Prevent instances of this class from being copied (As this class contains pointers)
CLDeconvolutionLayerUpsampleKernel() [3/3]
CLDeconvolutionLayerUpsampleKernel (CLDeconvolutionLayerUpsampleKernel &&) default
Default Move Constructor.
~CLDeconvolutionLayerUpsampleKernel()
~CLDeconvolutionLayerUpsampleKernel () default
Default destructor.
Member Function Documentation
configure()
void configure (const ICLTensor * input, ICLTensor * output, const BorderSize & inner_border, const PadStrideInfo & info)
Initialise the kernel's input and output.
Parameters
[in] input Source tensor. Data types supported: QASYMM8/F16/F32.
[out] output Destination tensor. Data types supported: same as input. All but the lowest two dimensions must be the same size as in the input tensor, i.e. scaling is only performed within the XY-plane.
[in] inner_border Top and right inner border sizes. These rows and columns will be filled with zero.
[in] info Contains padding and stride information described in PadStrideInfo.
Definition at line 73 of file CLDeconvolutionLayerUpsampleKernel.cpp.
 {
     ARM_COMPUTE_ERROR_ON_NULLPTR(input, output);
     _input        = input;
     _output       = output;
     _inner_border = inner_border;
     _info         = info;
     // Perform validation step
     ARM_COMPUTE_ERROR_THROW_ON(CLDeconvolutionLayerUpsampleKernel::validate(input->info(), output->info(), inner_border, info));
     // Create kernel
     CLBuildOptions build_opts;
     build_opts.add_option(("-DDATA_TYPE=" + get_cl_type_from_data_type(input->info()->data_type())));
     _kernel = static_cast<cl::Kernel>(CLKernelLibrary::get().create_kernel("deconvolution_upsample", build_opts.options()));
     constexpr unsigned int num_elems_processed_per_iteration = 1;
     // Configure kernel window
     Window                 win = calculate_max_window(*output->info(), Steps(num_elems_processed_per_iteration));
     AccessWindowHorizontal output_access(output->info(), 0, num_elems_processed_per_iteration);
     output_access.set_valid_region(win, ValidRegion(Coordinates(), output->info()->tensor_shape()));
     ICLKernel::configure_internal(win);
 }
References CLBuildOptions::add_option(), ARM_COMPUTE_ERROR_ON_NULLPTR, ARM_COMPUTE_ERROR_THROW_ON, arm_compute::calculate_max_window(), arm_compute::create_kernel(), ITensorInfo::data_type(), CLKernelLibrary::get(), arm_compute::get_cl_type_from_data_type(), ITensor::info(), arm_compute::test::validation::info, CLBuildOptions::options(), AccessWindowRectangle::set_valid_region(), ITensorInfo::tensor_shape(), and CLDeconvolutionLayerUpsampleKernel::validate().
Referenced by CLDeconvolutionLayerUpsample::configure().
operator=() [1/2]
CLDeconvolutionLayerUpsampleKernel& operator= (const CLDeconvolutionLayerUpsampleKernel &) delete
Prevent instances of this class from being copied (As this class contains pointers)
operator=() [2/2]
CLDeconvolutionLayerUpsampleKernel& operator= (CLDeconvolutionLayerUpsampleKernel &&) default
Default move assignment operator.
run()
void run (const Window & window, cl::CommandQueue & queue) override virtual
Enqueue the OpenCL kernel to process the given window on the passed OpenCL command queue.
Note
The queue is not flushed by this method, and therefore the kernel will not have been executed by the time this method returns.
Parameters
[in] window Region on which to execute the kernel. (Must be a valid region of the window returned by window()).
[in,out] queue Command queue on which to enqueue the kernel.
Implements ICLKernel.
Definition at line 101 of file CLDeconvolutionLayerUpsampleKernel.cpp.
 {
     ARM_COMPUTE_ERROR_ON_UNCONFIGURED_KERNEL(this);
     ARM_COMPUTE_ERROR_ON_INVALID_SUBWINDOW(ICLKernel::window(), window);
     const DataLayout data_layout = _input->info()->data_layout();
     const size_t idx_w = get_data_layout_dimension_index(data_layout, DataLayoutDimension::WIDTH);
     const size_t idx_h = get_data_layout_dimension_index(data_layout, DataLayoutDimension::HEIGHT);
     const int out_start_x = _info.pad().first;
     const int out_end_x   = _output->info()->dimension(idx_w) - _inner_border.right - _info.pad().first + _info.stride().first - 1;
     const int out_step_x  = _info.stride().first;
     const int out_start_y = _inner_border.top + _info.pad().second;
     const int out_end_y   = _output->info()->dimension(idx_h) - _info.pad().second + _info.stride().second - 1;
     const int out_step_y  = _info.stride().second;
     switch(data_layout)
     {
         case DataLayout::NCHW:
         {
             Window collapsed = window.collapse_if_possible(ICLKernel::window(), Window::DimZ);
             Window slice_out = collapsed.first_slice_window_3D();
             slice_out.set(Window::DimX, Window::Dimension(out_start_x, out_end_x, out_step_x));
             slice_out.set(Window::DimY, Window::Dimension(out_start_y, out_end_y, out_step_y));
             Window slice_in = collapsed.first_slice_window_3D();
             do
             {
                 unsigned int idx = 0;
                 add_3D_tensor_argument(idx, _input, slice_in);
                 add_3D_tensor_argument(idx, _output, slice_out);
                 enqueue(queue, *this, slice_out);
             }
             while(collapsed.slide_window_slice_3D(slice_in) && collapsed.slide_window_slice_3D(slice_out));
             break;
         }
         case DataLayout::NHWC:
         {
             // NOTE: not collapsing in NHWC
             Window slice_out = window.first_slice_window_3D();
             slice_out.set(Window::DimY, Window::Dimension(out_start_x, out_end_x, out_step_x));
             slice_out.set(Window::DimZ, Window::Dimension(out_start_y, out_end_y, out_step_y));
             Window slice_in = window.first_slice_window_3D();
             do
             {
                 unsigned int idx = 0;
                 add_3D_tensor_argument(idx, _input, slice_in);
                 add_3D_tensor_argument(idx, _output, slice_out);
                 enqueue(queue, *this, slice_out);
             }
             while(window.slide_window_slice_3D(slice_in) && window.slide_window_slice_3D(slice_out));
             break;
         }
         default:
             ARM_COMPUTE_ERROR("Unsupported data layout");
     }
 }
References ICLKernel::add_3D_tensor_argument(), ARM_COMPUTE_ERROR, ARM_COMPUTE_ERROR_ON_INVALID_SUBWINDOW, ARM_COMPUTE_ERROR_ON_UNCONFIGURED_KERNEL, Window::collapse_if_possible(), ITensorInfo::data_layout(), ITensorInfo::dimension(), Window::DimX, Window::DimY, Window::DimZ, arm_compute::enqueue(), Window::first_slice_window_3D(), arm_compute::get_data_layout_dimension_index(), arm_compute::HEIGHT, ITensor::info(), arm_compute::NCHW, arm_compute::NHWC, PadStrideInfo::pad(), BorderSize::right, Window::set(), Window::slide_window_slice_3D(), PadStrideInfo::stride(), BorderSize::top, arm_compute::WIDTH, and IKernel::window().
validate()
Status validate (const ITensorInfo * input, const ITensorInfo * output, const BorderSize & inner_border, const PadStrideInfo & info) static
Static function to check if given info will lead to a valid configuration of CLDeconvolutionLayerUpsample.
Parameters
[in] input Source tensor info. Data types supported: QASYMM8/F16/F32.
[in] output Destination tensor info. Data types supported: same as input. All but the lowest two dimensions must be the same size as in the input tensor, i.e. scaling is only performed within the XY-plane.
[in] inner_border Top and right inner border sizes. These rows and columns will be filled with zero.
[in] info Contains padding and stride information described in PadStrideInfo.
Returns
a status
Definition at line 42 of file CLDeconvolutionLayerUpsampleKernel.cpp.
 {
     ARM_COMPUTE_RETURN_ERROR_ON_NULLPTR(input, output);
     ARM_COMPUTE_RETURN_ERROR_ON_F16_UNSUPPORTED(input);
     ARM_COMPUTE_RETURN_ERROR_ON_DATA_TYPE_CHANNEL_NOT_IN(input, 1, DataType::QASYMM8, DataType::F16, DataType::F32);
     ARM_COMPUTE_RETURN_ERROR_ON_MISMATCHING_DATA_TYPES(input, output);
     ARM_COMPUTE_RETURN_ERROR_ON_MISMATCHING_QUANTIZATION_INFO(input, output);
     const DataLayout data_layout = input->data_layout();
     const size_t idx_w = get_data_layout_dimension_index(data_layout, DataLayoutDimension::WIDTH);
     const size_t idx_h = get_data_layout_dimension_index(data_layout, DataLayoutDimension::HEIGHT);
     const size_t idx_c = get_data_layout_dimension_index(data_layout, DataLayoutDimension::CHANNEL);
     ARM_COMPUTE_RETURN_ERROR_ON(output->dimension(idx_w) == 0);
     ARM_COMPUTE_RETURN_ERROR_ON(output->dimension(idx_h) == 0);
     ARM_COMPUTE_RETURN_ERROR_ON(!info.padding_is_symmetric());
     ARM_COMPUTE_RETURN_ERROR_ON(input->dimension(idx_c) != output->dimension(idx_c));
     for(size_t i = 3; i < Coordinates::num_max_dimensions; ++i)
     {
         ARM_COMPUTE_RETURN_ERROR_ON(input->dimension(i) != output->dimension(i));
     }
     ARM_COMPUTE_RETURN_ERROR_ON_MSG(inner_border.right > info.stride().first - 1, "inner_border_right must be smaller that stride_x");
     ARM_COMPUTE_RETURN_ERROR_ON_MSG(inner_border.top > info.stride().second - 1, "inner_border_top must be smaller that stride_y");
     return Status{};
 }
References ARM_COMPUTE_RETURN_ERROR_ON, ARM_COMPUTE_RETURN_ERROR_ON_DATA_TYPE_CHANNEL_NOT_IN, ARM_COMPUTE_RETURN_ERROR_ON_F16_UNSUPPORTED, ARM_COMPUTE_RETURN_ERROR_ON_MISMATCHING_DATA_TYPES, ARM_COMPUTE_RETURN_ERROR_ON_MISMATCHING_QUANTIZATION_INFO, ARM_COMPUTE_RETURN_ERROR_ON_MSG, ARM_COMPUTE_RETURN_ERROR_ON_NULLPTR, arm_compute::CHANNEL, ITensorInfo::data_layout(), ITensorInfo::dimension(), arm_compute::F16, arm_compute::F32, arm_compute::get_data_layout_dimension_index(), arm_compute::HEIGHT, arm_compute::test::validation::info, Dimensions< int >::num_max_dimensions, arm_compute::QASYMM8, BorderSize::right, BorderSize::top, and arm_compute::WIDTH.
Referenced by CLDeconvolutionLayerUpsampleKernel::configure(), and CLDeconvolutionLayerUpsample::validate().
The documentation for this class was generated from the following files:
arm_compute/core/CL/kernels/CLDeconvolutionLayerUpsampleKernel.h
src/core/CL/kernels/CLDeconvolutionLayerUpsampleKernel.cpp