Compute Library: NEHarrisCorners Class Reference
NEHarrisCorners Class Reference
Basic function to execute harris corners detection.
#include <NEHarrisCorners.h>
Public Member Functions
NEHarrisCorners (std::shared_ptr< IMemoryManager > memory_manager=nullptr)
Constructor.
void configure (IImage *input, float threshold, float min_dist, float sensitivity, int32_t gradient_size, int32_t block_size, KeyPointArray *corners, BorderMode border_mode, uint8_t constant_border_value=0)
Initialize the function's source, destination, conv and border_mode.
void run () override
Run the kernels contained in the function.
Public Member Functions inherited from IFunction
virtual ~IFunction ()=default
Destructor.
virtual void prepare ()
Prepare the function for executing.
Detailed Description
Basic function to execute harris corners detection.
This function calls the following NEON kernels and functions:
NESobel3x3 (if gradient_size == 3) or
NESobel5x5 (if gradient_size == 5) or
NESobel7x7 (if gradient_size == 7)
NEFillBorderKernel
NEHarrisScoreKernel<3> (if block_size == 3) or
NEHarrisScoreKernel<5> (if block_size == 5) or
NEHarrisScoreKernel<7> (if block_size == 7)
NENonMaximaSuppression3x3
CPPCornerCandidatesKernel
CPPSortEuclideanDistanceKernel
Definition at line 61 of file NEHarrisCorners.h.
Constructor & Destructor Documentation
NEHarrisCorners()
NEHarrisCorners (std::shared_ptr< IMemoryManager > memory_manager = nullptr)
Constructor.
Initialize _sobel, _harris_score and _corner_list to nullptr.
Parameters
[in] memory_manager (Optional) Memory manager.
Definition at line 44 of file NEHarrisCorners.cpp.
     : _memory_group(std::move(memory_manager)),
       _sobel(),
       _harris_score(),
       _non_max_suppr(),
       _candidates(),
       _sort_euclidean(),
       _border_gx(),
       _border_gy(),
       _gx(),
       _gy(),
       _score(),
       _nonmax(),
       _corners_list(),
       _num_corner_candidates(0)
 {
 }
Member Function Documentation
configure()
void configure (IImage * input, float threshold, float min_dist, float sensitivity, int32_t gradient_size, int32_t block_size, KeyPointArray * corners, BorderMode border_mode, uint8_t constant_border_value = 0)
Initialize the function's source, destination, conv and border_mode.
Parameters
[in,out] input Source image. Data type supported: U8. (Written to only for border_mode != UNDEFINED)
[in] threshold Minimum threshold with which to eliminate Harris Corner scores (computed using the normalized Sobel kernel).
[in] min_dist Radial Euclidean distance for the euclidean diatance stage
[in] sensitivity Sensitivity threshold k from the Harris-Stephens equation
[in] gradient_size The gradient window size to use on the input. The implementation supports 3, 5, and 7
[in] block_size The block window size used to compute the Harris Corner score. The implementation supports 3, 5, and 7.
[out] corners Array of keypoints to store the results.
[in] border_mode Border mode to use
[in] constant_border_value (Optional) Constant value to use for borders if border_mode is set to CONSTANT.
Definition at line 62 of file NEHarrisCorners.cpp.
 {
     ARM_COMPUTE_ERROR_ON_TENSOR_NOT_2D(input);
     ARM_COMPUTE_ERROR_ON_DATA_TYPE_CHANNEL_NOT_IN(input, 1, DataType::U8);
     ARM_COMPUTE_ERROR_ON(!(block_size == 3 || block_size == 5 || block_size == 7));
     const TensorShape shape = input->info()->tensor_shape();
     TensorInfo        tensor_info_gxgy;
     if(gradient_size < 7)
     {
         tensor_info_gxgy.init(shape, Format::S16);
     }
     else
     {
         tensor_info_gxgy.init(shape, Format::S32);
     }
     _gx.allocator()->init(tensor_info_gxgy);
     _gy.allocator()->init(tensor_info_gxgy);
     // Manage intermediate buffers
     _memory_group.manage(&_gx);
     _memory_group.manage(&_gy);
     TensorInfo tensor_info_score(shape, Format::F32);
     _score.allocator()->init(tensor_info_score);
     _nonmax.allocator()->init(tensor_info_score);
     _corners_list = arm_compute::support::cpp14::make_unique<InternalKeypoint[]>(shape.x() * shape.y());
     // Set/init Sobel kernel accordingly with gradient_size
     switch(gradient_size)
     {
         case 3:
         {
             auto k = arm_compute::support::cpp14::make_unique<NESobel3x3>();
             k->configure(input, &_gx, &_gy, border_mode, constant_border_value);
             _sobel = std::move(k);
             break;
         }
         case 5:
         {
             auto k = arm_compute::support::cpp14::make_unique<NESobel5x5>();
             k->configure(input, &_gx, &_gy, border_mode, constant_border_value);
             _sobel = std::move(k);
             break;
         }
         case 7:
         {
             auto k = arm_compute::support::cpp14::make_unique<NESobel7x7>();
             k->configure(input, &_gx, &_gy, border_mode, constant_border_value);
             _sobel = std::move(k);
             break;
         }
         default:
             ARM_COMPUTE_ERROR("Gradient size not implemented");
     }
     // Normalization factor
     const float norm_factor = 1.0f / (255.0f * pow(4.0f, gradient_size / 2) * block_size);
     // Manage intermediate buffers
     _memory_group.manage(&_score);
     // Set/init Harris Score kernel accordingly with block_size
     switch(block_size)
     {
         case 3:
         {
             auto k = arm_compute::support::cpp14::make_unique<NEHarrisScoreKernel<3>>();
             k->configure(&_gx, &_gy, &_score, norm_factor, threshold, sensitivity, border_mode == BorderMode::UNDEFINED);
             _harris_score = std::move(k);
         }
         break;
         case 5:
         {
             auto k = arm_compute::support::cpp14::make_unique<NEHarrisScoreKernel<5>>();
             k->configure(&_gx, &_gy, &_score, norm_factor, threshold, sensitivity, border_mode == BorderMode::UNDEFINED);
             _harris_score = std::move(k);
         }
         break;
         case 7:
         {
             auto k = arm_compute::support::cpp14::make_unique<NEHarrisScoreKernel<7>>();
             k->configure(&_gx, &_gy, &_score, norm_factor, threshold, sensitivity, border_mode == BorderMode::UNDEFINED);
             _harris_score = std::move(k);
         }
         default:
             break;
     }
     // Configure border filling before harris score
     _border_gx.configure(&_gx, _harris_score->border_size(), border_mode, constant_border_value);
     _border_gy.configure(&_gy, _harris_score->border_size(), border_mode, constant_border_value);
     // Allocate once all the configure methods have been called
     _gx.allocator()->allocate();
     _gy.allocator()->allocate();
     // Manage intermediate buffers
     _memory_group.manage(&_nonmax);
     // Init non-maxima suppression function
     _non_max_suppr.configure(&_score, &_nonmax, border_mode);
     // Allocate once all the configure methods have been called
     _score.allocator()->allocate();
     // Init corner candidates kernel
     _candidates.configure(&_nonmax, _corners_list.get(), &_num_corner_candidates);
     // Allocate once all the configure methods have been called
     _nonmax.allocator()->allocate();
     // Init euclidean distance
     _sort_euclidean.configure(_corners_list.get(), corners, &_num_corner_candidates, min_dist);
 }
References TensorAllocator::allocate(), Tensor::allocator(), ARM_COMPUTE_ERROR, ARM_COMPUTE_ERROR_ON, ARM_COMPUTE_ERROR_ON_DATA_TYPE_CHANNEL_NOT_IN, ARM_COMPUTE_ERROR_ON_TENSOR_NOT_2D, arm_compute::test::validation::border_mode, NENonMaximaSuppression3x3::configure(), CPPSortEuclideanDistanceKernel::configure(), NEFillBorderKernel::configure(), CPPCornerCandidatesKernel::configure(), arm_compute::F32, ITensor::info(), TensorAllocator::init(), TensorInfo::init(), MemoryGroupBase< TensorType >::manage(), arm_compute::S16, arm_compute::S32, arm_compute::test::validation::shape, ITensorInfo::tensor_shape(), arm_compute::test::validation::reference::threshold(), arm_compute::U8, and arm_compute::UNDEFINED.
Referenced by arm_compute::test::validation::DATA_TEST_CASE().
run()
void run () override virtual
Run the kernels contained in the function.
For NEON kernels:
Multi-threading is used for the kernels which are parallelisable.
By default std::thread::hardware_concurrency() threads are used.
Note
CPPScheduler::set_num_threads() can be used to manually set the number of threads
For OpenCL kernels:
All the kernels are enqueued on the queue associated with CLScheduler.
The queue is then flushed.
Note
The function will not block until the kernels are executed. It is the user's responsibility to wait.
Will call prepare() on first run if hasn't been done
Implements IFunction.
Definition at line 183 of file NEHarrisCorners.cpp.
 {
     ARM_COMPUTE_ERROR_ON_MSG(_sobel == nullptr, "Unconfigured function");
     _memory_group.acquire();
     // Init to 0 number of corner candidates
     _num_corner_candidates = 0;
     // Run Sobel kernel
     _sobel->run();
     // Fill border before harris score kernel
     NEScheduler::get().schedule(&_border_gx, Window::DimZ);
     NEScheduler::get().schedule(&_border_gy, Window::DimZ);
     // Run harris score kernel
     NEScheduler::get().schedule(_harris_score.get(), Window::DimY);
     // Run non-maxima suppression
     _non_max_suppr.run();
     // Run corner candidate kernel
     NEScheduler::get().schedule(&_candidates, Window::DimY);
     // Run sort & euclidean distance
     NEScheduler::get().schedule(&_sort_euclidean, Window::DimY);
     _memory_group.release();
 }
References MemoryGroupBase< TensorType >::acquire(), ARM_COMPUTE_ERROR_ON_MSG, Window::DimY, Window::DimZ, Scheduler::get(), MemoryGroupBase< TensorType >::release(), INESimpleFunction::run(), and IScheduler::schedule().
The documentation for this class was generated from the following files:
arm_compute/runtime/NEON/functions/NEHarrisCorners.h
src/runtime/NEON/functions/NEHarrisCorners.cpp