Compute Library: MultiImage Class Reference
MultiImage Class Reference
Basic implementation of the multi-planar image interface.
#include <MultiImage.h>
Public Member Functions
MultiImage ()
Constructor.
void init (unsigned int width, unsigned int height, Format format)
Allocate the multi-planar image.
void init_auto_padding (unsigned int width, unsigned int height, Format format)
Allocate the multi-planar image.
void allocate ()
Allocated a previously initialised multi image.
void create_subimage (MultiImage *image, const Coordinates &coords, unsigned int width, unsigned int height)
Create a subimage from an existing MultiImage.
const MultiImageInfo * info () const override
Interface to be implemented by the child class to return the multi-planar image's metadata.
Image * plane (unsigned int index) override
Return a pointer to the requested plane of the image.
const Image * plane (unsigned int index) const override
Return a constant pointer to the requested plane of the image.
Public Member Functions inherited from IMultiImage
virtual ~IMultiImage ()=default
Destructor.
Detailed Description
Basic implementation of the multi-planar image interface.
Definition at line 41 of file MultiImage.h.
Constructor & Destructor Documentation
MultiImage()
MultiImage ()
Constructor.
Definition at line 33 of file MultiImage.cpp.
     : _info(), _plane()
 {
 }
Member Function Documentation
allocate()
void allocate ()
Allocated a previously initialised multi image.
Note
The multi image must not already be allocated when calling this function.
Definition at line 130 of file MultiImage.cpp.
 {
     switch(_info.format())
     {
         case Format::U8:
         case Format::S16:
         case Format::U16:
         case Format::S32:
         case Format::F16:
         case Format::F32:
         case Format::U32:
         case Format::RGB888:
         case Format::RGBA8888:
         case Format::YUYV422:
         case Format::UYVY422:
             std::get<0>(_plane).allocator()->allocate();
             break;
         case Format::NV12:
         case Format::NV21:
             std::get<0>(_plane).allocator()->allocate();
             std::get<1>(_plane).allocator()->allocate();
             break;
         case Format::IYUV:
         case Format::YUV444:
             std::get<0>(_plane).allocator()->allocate();
             std::get<1>(_plane).allocator()->allocate();
             std::get<2>(_plane).allocator()->allocate();
             break;
         default:
             ARM_COMPUTE_ERROR("Not supported");
             break;
     }
 }
References ARM_COMPUTE_ERROR, arm_compute::F16, arm_compute::F32, MultiImageInfo::format(), arm_compute::IYUV, arm_compute::NV12, arm_compute::NV21, arm_compute::RGB888, arm_compute::RGBA8888, arm_compute::S16, arm_compute::S32, arm_compute::U16, arm_compute::U32, arm_compute::U8, arm_compute::UYVY422, arm_compute::YUV444, and arm_compute::YUYV422.
create_subimage()
void create_subimage (MultiImage * image, const Coordinates & coords, unsigned int width, unsigned int height)
Create a subimage from an existing MultiImage.
Parameters
[in] image Image to use backing memory from
[in] coords Starting coordinates of the new image. Should be within the parent image sizes
[in] width The width of the subimage
[in] height The height of the subimage
Definition at line 164 of file MultiImage.cpp.
 {
     arm_compute::Format format = image->info()->format();
     const TensorInfo    info(width, height, Format::U8);
     switch(format)
     {
         case Format::U8:
         case Format::S16:
         case Format::U16:
         case Format::S32:
         case Format::F32:
         case Format::F16:
         case Format::U32:
         case Format::RGB888:
         case Format::RGBA8888:
         case Format::YUYV422:
         case Format::UYVY422:
         {
             const TensorInfo info_full(width, height, format);
             std::get<0>(_plane).allocator()->init(*dynamic_cast<Image *>(image->plane(0))->allocator(), coords, info_full);
             break;
         }
         case Format::NV12:
         case Format::NV21:
         {
             const TensorInfo info_uv88(width / 2, height / 2, Format::UV88);
             std::get<0>(_plane).allocator()->init(*dynamic_cast<Image *>(image->plane(0))->allocator(), coords, info);
             std::get<1>(_plane).allocator()->init(*dynamic_cast<Image *>(image->plane(1))->allocator(), coords, info_uv88);
             break;
         }
         case Format::IYUV:
         {
             const TensorInfo info_sub2(width / 2, height / 2, Format::U8);
             std::get<0>(_plane).allocator()->init(*dynamic_cast<Image *>(image->plane(0))->allocator(), coords, info);
             std::get<1>(_plane).allocator()->init(*dynamic_cast<Image *>(image->plane(1))->allocator(), coords, info_sub2);
             std::get<2>(_plane).allocator()->init(*dynamic_cast<Image *>(image->plane(2))->allocator(), coords, info_sub2);
             break;
         }
         case Format::YUV444:
             std::get<0>(_plane).allocator()->init(*dynamic_cast<Image *>(image->plane(0))->allocator(), coords, info);
             std::get<1>(_plane).allocator()->init(*dynamic_cast<Image *>(image->plane(0))->allocator(), coords, info);
             std::get<2>(_plane).allocator()->init(*dynamic_cast<Image *>(image->plane(0))->allocator(), coords, info);
             break;
         default:
             ARM_COMPUTE_ERROR("Not supported");
             break;
     }
     _info.init(width, height, format);
 }
References ARM_COMPUTE_ERROR, arm_compute::F16, arm_compute::F32, MultiImageInfo::format(), MultiImage::info(), MultiImageInfo::init(), arm_compute::IYUV, arm_compute::NV12, arm_compute::NV21, MultiImage::plane(), arm_compute::RGB888, arm_compute::RGBA8888, arm_compute::S16, arm_compute::S32, arm_compute::U16, arm_compute::U32, arm_compute::U8, arm_compute::UV88, arm_compute::UYVY422, arm_compute::YUV444, and arm_compute::YUYV422.
info()
const MultiImageInfo * info () const override virtual
Interface to be implemented by the child class to return the multi-planar image's metadata.
Returns
A pointer to the image's metadata.
Implements IMultiImage.
Definition at line 38 of file MultiImage.cpp.
 {
     return &_info;
 }
Referenced by MultiImage::create_subimage().
init()
void init (unsigned int width, unsigned int height, Format format)
Allocate the multi-planar image.
Parameters
[in] width Width of the whole image
[in] height Height of the whole image
[in] format Format of the whole image
Definition at line 43 of file MultiImage.cpp.
 {
     internal_init(width, height, format, false);
 }
init_auto_padding()
void init_auto_padding (unsigned int width, unsigned int height, Format format)
Allocate the multi-planar image.
Note
Uses conservative padding strategy which fits all kernels.
Parameters
[in] width Width of the whole image
[in] height Height of the whole image
[in] format Format of the whole image
Definition at line 48 of file MultiImage.cpp.
 {
     internal_init(width, height, format, true);
 }
plane() [1/2]
Image * plane (unsigned int index) override virtual
Return a pointer to the requested plane of the image.
Parameters
[in] index The index of the wanted planed.
Returns
A pointer pointed to the plane
Implements IMultiImage.
Definition at line 216 of file MultiImage.cpp.
 {
     return &_plane[index];
 }
Referenced by MultiImage::create_subimage().
plane() [2/2]
const Image * plane (unsigned int index) const override virtual
Return a constant pointer to the requested plane of the image.
Parameters
[in] index The index of the wanted planed.
Returns
A constant pointer pointed to the plane
Implements IMultiImage.
Definition at line 221 of file MultiImage.cpp.
 {
     return &_plane[index];
 }
The documentation for this class was generated from the following files:
arm_compute/runtime/MultiImage.h
src/runtime/MultiImage.cpp