Compute Library: NumPyBinLoader Class Reference
NumPyBinLoader Class Reference final
Numpy Binary loader class.
#include <GraphUtils.h>
Public Member Functions
NumPyBinLoader (std::string filename, DataLayout file_layout=DataLayout::NCHW)
Default Constructor.
NumPyBinLoader (NumPyBinLoader &&)=default
Allows instances to move constructed.
bool access_tensor (ITensor &tensor) override
Interface to be implemented to access a given tensor.
Public Member Functions inherited from ITensorAccessor
virtual ~ITensorAccessor ()=default
Default virtual destructor.
Detailed Description
Numpy Binary loader class.
Definition at line 232 of file GraphUtils.h.
Constructor & Destructor Documentation
NumPyBinLoader (std::string filename, DataLayout file_layout = DataLayout::NCHW)
Default Constructor.
Parameters
[in] filename Binary file name
[in] file_layout (Optional) Layout of the numpy tensor data. Defaults to NCHW
Definition at line 392 of file GraphUtils.cpp.
     : _filename(std::move(filename)), _file_layout(file_layout)
 {
 }
NumPyBinLoader (NumPyBinLoader &&) default
Allows instances to move constructed.
Member Function Documentation
bool access_tensor (ITensor & tensor) override virtual
Interface to be implemented to access a given tensor.
Parameters
[in] tensor Tensor to be accessed
Returns
True if access is successful else false
Implements ITensorAccessor.
Definition at line 397 of file GraphUtils.cpp.
References ARM_COMPUTE_ERROR_ON_MSG, ITensor::buffer(), ITensorInfo::data_layout(), ITensorInfo::data_type(), ITensorInfo::element_size(), BorderSize::empty(), arm_compute::execute_window_loop(), arm_compute::utils::get_typestring(), ITensor::info(), Dimensions< T >::num_dimensions(), ITensorInfo::padding(), arm_compute::permute(), ITensor::ptr_to_element(), arm_compute::test::validation::shape, ITensorInfo::tensor_shape(), ITensorInfo::total_size(), and Window::use_tensor_dimensions().
Referenced by NumPyAccessor::NumPyAccessor().
 {
     const TensorShape          tensor_shape = tensor.info()->tensor_shape();
     std::vector<unsigned long> shape;
     // Open file
     std::ifstream stream(_filename, std::ios::in | std::ios::binary);
     ARM_COMPUTE_ERROR_ON_MSG(!stream.good(), "Failed to load binary data");
     std::string header = npy::read_header(stream);
     // Parse header
     bool        fortran_order = false;
     std::string typestr;
     npy::parse_header(header, typestr, fortran_order, shape);
     // Check if the typestring matches the given one
     std::string expect_typestr = arm_compute::utils::get_typestring(tensor.info()->data_type());
     ARM_COMPUTE_ERROR_ON_MSG(typestr != expect_typestr, "Typestrings mismatch");
     // Reverse vector in case of non fortran order
     if(!fortran_order)
     {
         std::reverse(shape.begin(), shape.end());
     }
     // Correct dimensions (Needs to match TensorShape dimension corrections)
     if(shape.size() != tensor_shape.num_dimensions())
     {
         for(int i = static_cast<int>(shape.size()) - 1; i > 0; --i)
         {
             if(shape[i] == 1)
             {
                 shape.pop_back();
             }
             else
             {
                 break;
             }
         }
     }
     bool are_layouts_different = (_file_layout != tensor.info()->data_layout());
     // Validate tensor ranks
     ARM_COMPUTE_ERROR_ON_MSG(shape.size() != tensor_shape.num_dimensions(), "Tensor ranks mismatch");
     // Set permutation parameters if needed
     TensorShape                    permuted_shape = tensor_shape;
     arm_compute::PermutationVector perm;
     if(are_layouts_different)
     {
         std::tie(permuted_shape, perm) = compute_permutation_paramaters(tensor_shape, tensor.info()->data_layout());
     }
     // Validate shapes
     for(size_t i = 0; i < shape.size(); ++i)
     {
         ARM_COMPUTE_ERROR_ON_MSG(permuted_shape[i] != shape[i], "Tensor dimensions mismatch");
     }
     // Validate shapes and copy tensor
     if(!are_layouts_different || perm.num_dimensions() <= 2)
     {
         // Read data
         if(tensor.info()->padding().empty() && (dynamic_cast<SubTensor *>(&tensor) == nullptr))
         {
             // If tensor has no padding read directly from stream.
             stream.read(reinterpret_cast<char *>(tensor.buffer()), tensor.info()->total_size());
         }
         else
         {
             // If tensor has padding accessing tensor elements through execution window.
             Window window;
             window.use_tensor_dimensions(tensor_shape);
             execute_window_loop(window, [&](const Coordinates & id)
             {
                 stream.read(reinterpret_cast<char *>(tensor.ptr_to_element(id)), tensor.info()->element_size());
             });
         }
     }
     else
     {
         // If tensor has padding accessing tensor elements through execution window.
         Window window;
         window.use_tensor_dimensions(permuted_shape);
         execute_window_loop(window, [&](const Coordinates & id)
         {
             Coordinates coords(id);
             arm_compute::permute(coords, perm);
             stream.read(reinterpret_cast<char *>(tensor.ptr_to_element(coords)), tensor.info()->element_size());
         });
     }
     return true;
 }
The documentation for this class was generated from the following files:
utils/GraphUtils.h
utils/GraphUtils.cpp