Compute Library: SimpleOption< T > Class Template Reference
SimpleOption< T > Class Template Reference
Implementation of an option that accepts a single value.
#include <SimpleOption.h>
Public Member Functions
SimpleOption (std::string name, T default_value)
Construct the option with the given default value.
bool parse (std::string value) override
Parses the given string.
std::string help () const override
Help message for the option.
const T & value () const
template<>
bool parse (std::string value)
Parses the given string.
Public Member Functions inherited from Option
Option (std::string name)
Constructor.
Option (std::string name, bool is_required, bool is_set)
Constructor.
virtual ~Option ()=default
Default destructor.
std::string name () const
Name of the option.
void set_required (bool is_required)
Set whether the option is required.
void set_help (std::string help)
Set the help message for the option.
bool is_required () const
Is the option required?
bool is_set () const
Has a value been assigned to the option?
Detailed Description
template<typename T>
class arm_compute::test::framework::SimpleOption< T >
Implementation of an option that accepts a single value.
Definition at line 41 of file SimpleOption.h.
Constructor & Destructor Documentation
SimpleOption (std::string name, T default_value) inline
Construct the option with the given default value.
Parameters
[in] name Name of the option.
[in] default_value Default value.
Definition at line 62 of file SimpleOption.h.
     : Option{ std::move(name), false, true }, _value{ std::move(default_value) }
 {
 }
Member Function Documentation
std::string help () const inline override virtual
Help message for the option.
Returns
String representing the help message for the specific subclass.
Implements Option.
Definition at line 92 of file SimpleOption.h.
References Option::name().
 {
     return "--" + name() + "=VALUE - " + _help;
 }
bool parse (std::string value) override virtual
Parses the given string.
Parameters
[in] value String representation as passed on the command line.
Returns
True if the value could be parsed by the specific subclass.
Implements Option.
Definition at line 68 of file SimpleOption.h.
 {
     try
     {
         std::stringstream stream{ std::move(value) };
         stream >> _value;
         _is_set = !stream.fail();
         return _is_set;
     }
     catch(const std::invalid_argument &)
     {
         return false;
     }
 }
bool parse (std::string value) inline virtual
Parses the given string.
Parameters
[in] value String representation as passed on the command line.
Returns
True if the value could be parsed by the specific subclass.
Implements Option.
Definition at line 84 of file SimpleOption.h.
 {
     _value  = std::move(value);
     _is_set = true;
     return true;
 }
const T & value () const inline
Definition at line 98 of file SimpleOption.h.
Referenced by CommonOptions::create_printers(), and main().
 {
     return _value;
 }
The documentation for this class was generated from the following file:
tests/framework/command_line/SimpleOption.h