Compute Library: GenerateProposalsInfo Class Reference
GenerateProposalsInfo Class Reference
Generate Proposals Information class.
#include <Types.h>
Public Member Functions
GenerateProposalsInfo (float im_width, float im_height, float im_scale, float spatial_scale=1.0, int pre_nms_topN=6000, int post_nms_topN=300, float nms_thres=0.7, float min_size=16.0, size_t values_per_roi=4)
Constructor.
float im_height () const
float im_width () const
float im_scale () const
int pre_nms_topN () const
int post_nms_topN () const
float nms_thres () const
float min_size () const
float spatial_scale () const
size_t values_per_roi () const
Detailed Description
Generate Proposals Information class.
Definition at line 1085 of file Types.h.
Constructor & Destructor Documentation
GenerateProposalsInfo()
GenerateProposalsInfo (float im_width, float im_height, float im_scale, float spatial_scale = 1.0, int pre_nms_topN = 6000, int post_nms_topN = 300, float nms_thres = 0.7, float min_size = 16.0, size_t values_per_roi = 4) inline
Constructor.
Parameters
[in] im_width Width of the original image
[in] im_height Height of the original image
[in] im_scale Scale applied to the original image
[in] spatial_scale (Optional)Scale applied to the feature map. Defaults to 1.0
[in] pre_nms_topN (Optional)Number of the best scores to be selected from the transformations. Defaults to 6000.
[in] post_nms_topN (Optional)Number of the best scores to be selected from the NMS operation. Defaults to 300.
[in] nms_thres (Optional)NMS overlap threshold. Defaults to 0.7.
[in] min_size (Optional)Size used to validate the anchors produced. Defaults to 16.
[in] values_per_roi (Optional)Values used to represent a ROI(Region of interest). Defaults to 4.
Definition at line 1100 of file Types.h.
         : _im_height(im_height), _im_width(im_width), _im_scale(im_scale), _spatial_scale(spatial_scale), _pre_nms_topN(pre_nms_topN), _post_nms_topN(post_nms_topN), _nms_thres(nms_thres),
           _min_size(min_size), _values_per_roi(values_per_roi)
     {
     }
Member Function Documentation
im_height()
float im_height () const inline
Definition at line 1108 of file Types.h.
Referenced by CLGenerateProposalsLayer::configure(), arm_compute::operator<<(), and CLGenerateProposalsLayer::validate().
     {
         return _im_height;
     }
im_scale()
float im_scale () const inline
Definition at line 1118 of file Types.h.
Referenced by CLGenerateProposalsLayer::configure(), and arm_compute::operator<<().
     {
         return _im_scale;
     }
im_width()
float im_width () const inline
Definition at line 1113 of file Types.h.
Referenced by CLGenerateProposalsLayer::configure(), arm_compute::operator<<(), and CLGenerateProposalsLayer::validate().
     {
         return _im_width;
     }
min_size()
float min_size () const inline
Definition at line 1138 of file Types.h.
Referenced by CLGenerateProposalsLayer::configure().
     {
         return _min_size;
     }
nms_thres()
float nms_thres () const inline
Definition at line 1133 of file Types.h.
Referenced by CLGenerateProposalsLayer::configure().
     {
         return _nms_thres;
     }
post_nms_topN()
int post_nms_topN () const inline
Definition at line 1128 of file Types.h.
Referenced by CLGenerateProposalsLayer::configure().
     {
         return _post_nms_topN;
     }
pre_nms_topN()
int pre_nms_topN () const inline
Definition at line 1123 of file Types.h.
Referenced by CLGenerateProposalsLayer::configure().
     {
         return _pre_nms_topN;
     }
spatial_scale()
float spatial_scale () const inline
Definition at line 1143 of file Types.h.
Referenced by CLGenerateProposalsLayer::configure(), and CLGenerateProposalsLayer::validate().
     {
         return _spatial_scale;
     }
values_per_roi()
size_t values_per_roi () const inline
Definition at line 1148 of file Types.h.
Referenced by CLGenerateProposalsLayer::configure(), and CLGenerateProposalsLayer::validate().
     {
         return _values_per_roi;
     }
The documentation for this class was generated from the following file:
arm_compute/core/Types.h