Compute Library: OpenCLTimer Class Reference
OpenCLTimer Class Reference
Instrument creating measurements based on the information returned by clGetEventProfilingInfo for each OpenCL kernel executed.
#include <OpenCLTimer.h>
Public Member Functions
OpenCLTimer (ScaleFactor scale_factor)
Construct an OpenCL timer.
std::string id () const override
Identifier for the instrument.
void test_start () override
Start of the test.
void start () override
Start measuring.
void stop () override
Stop measuring.
void test_stop () override
End of the test.
MeasurementsMap measurements () const override
Return the latest measurements.
Public Member Functions inherited from Instrument
Instrument ()=default
Default constructor.
Instrument (const Instrument &)=default
Allow instances of this class to be copy constructed.
Instrument (Instrument &&)=default
Allow instances of this class to be move constructed.
Instrument & operator= (const Instrument &)=default
Allow instances of this class to be copied.
Instrument & operator= (Instrument &&)=default
Allow instances of this class to be moved.
virtual ~Instrument ()=default
Default destructor.
virtual MeasurementsMap test_measurements () const
Return the latest test measurements.
Additional Inherited Members
Public Types inherited from Instrument
using MeasurementsMap = std::map< std::string, Measurement >
Map of measurements.
Static Public Member Functions inherited from Instrument
template<typename T , ScaleFactor scale>
static std::unique_ptr< Instrument > make_instrument ()
Helper function to create an instrument of the given type.
Detailed Description
Instrument creating measurements based on the information returned by clGetEventProfilingInfo for each OpenCL kernel executed.
Definition at line 44 of file OpenCLTimer.h.
Constructor & Destructor Documentation
OpenCLTimer (ScaleFactor scale_factor)
Construct an OpenCL timer.
Parameters
[in] scale_factor Measurement scale factor.
Definition at line 47 of file OpenCLTimer.cpp.
References ARM_COMPUTE_ERROR, CLScheduler::get(), arm_compute::test::framework::NONE, CLScheduler::queue(), CLScheduler::set_queue(), arm_compute::test::framework::TIME_MS, arm_compute::test::framework::TIME_S, and arm_compute::test::framework::TIME_US.
     : _kernels(), _real_function(nullptr), _real_graph_function(nullptr), _prefix(), _timer_enabled(false)
 {
     auto                        q     = CLScheduler::get().queue();
     cl_command_queue_properties props = q.getInfo<CL_QUEUE_PROPERTIES>();
     if((props & CL_QUEUE_PROFILING_ENABLE) == 0)
     {
         CLScheduler::get().set_queue(cl::CommandQueue(CLScheduler::get().context(), props | CL_QUEUE_PROFILING_ENABLE));
     }
     switch(scale_factor)
     {
         case ScaleFactor::NONE:
             _scale_factor = 1.f;
             _unit         = "ns";
             break;
         case ScaleFactor::TIME_US:
             _scale_factor = 1000.f;
             _unit         = "us";
             break;
         case ScaleFactor::TIME_MS:
             _scale_factor = 1000000.f;
             _unit         = "ms";
             break;
         case ScaleFactor::TIME_S:
             _scale_factor = 1000000000.f;
             _unit         = "s";
             break;
         default:
             ARM_COMPUTE_ERROR("Invalid scale");
     }
 }
Member Function Documentation
std::string id () const override virtual
Identifier for the instrument.
Implements Instrument.
Definition at line 42 of file OpenCLTimer.cpp.
 {
     return "OpenCLTimer";
 }
Instrument::MeasurementsMap measurements () const override virtual
Return the latest measurements.
Returns
the latest measurements.
Reimplemented from Instrument.
Definition at line 166 of file OpenCLTimer.cpp.
References OpenCLTimer::start(), and arm_compute::support::cpp11::to_string().
 {
     MeasurementsMap measurements;
     unsigned int    kernel_number = 0;
     for(auto kernel : _kernels)
     {
         cl_ulong start = kernel.event.getProfilingInfo<CL_PROFILING_COMMAND_START>();
         cl_ulong end   = kernel.event.getProfilingInfo<CL_PROFILING_COMMAND_END>();
         measurements.emplace(kernel.name + " #" + support::cpp11::to_string(kernel_number++), Measurement((end - start) / _scale_factor, _unit));
     }
     return measurements;
 }
void start () override virtual
Start measuring.
Called just before the run of the test starts
Reimplemented from Instrument.
Definition at line 147 of file OpenCLTimer.cpp.
Referenced by OpenCLTimer::measurements().
 {
     _kernels.clear();
     _timer_enabled = true;
 }
void stop () override virtual
Stop measuring.
Called just after the run of the test ends
Reimplemented from Instrument.
Definition at line 152 of file OpenCLTimer.cpp.
 {
     _timer_enabled = false;
 }
void test_start () override virtual
Start of the test.
Called before the test set up starts
Reimplemented from Instrument.
Definition at line 80 of file OpenCLTimer.cpp.
References ARM_COMPUTE_ERROR_ON, ARM_COMPUTE_ERROR_ON_MSG, ARM_COMPUTE_UNUSED, CLSymbols::clEnqueueNDRangeKernel_ptr, TaskExecutor::execute_function, TaskExecutor::get(), CLSymbols::get(), and arm_compute::test::validation::info().
 {
     // Start intercepting enqueues:
     ARM_COMPUTE_ERROR_ON(_real_function != nullptr);
     ARM_COMPUTE_ERROR_ON(_real_graph_function != nullptr);
     _real_function       = CLSymbols::get().clEnqueueNDRangeKernel_ptr;
     _real_graph_function = graph::TaskExecutor::get().execute_function;
     auto interceptor     = [this](
                                cl_command_queue command_queue,
                                cl_kernel        kernel,
                                cl_uint          work_dim,
                                const size_t    *gwo,
                                const size_t    *gws,
                                const size_t    *lws,
                                cl_uint          num_events_in_wait_list,
                                const cl_event * event_wait_list,
                                cl_event *       event)
     {
         if(this->_timer_enabled)
         {
             ARM_COMPUTE_ERROR_ON_MSG(event != nullptr, "Not supported");
             ARM_COMPUTE_UNUSED(event);
             OpenCLTimer::kernel_info info;
             cl::Kernel               cpp_kernel(kernel, true);
             std::stringstream        ss;
             ss << this->_prefix << cpp_kernel.getInfo<CL_KERNEL_FUNCTION_NAME>();
             if(gws != nullptr)
             {
                 ss << " GWS[" << gws[0] << "," << gws[1] << "," << gws[2] << "]";
             }
             if(lws != nullptr)
             {
                 ss << " LWS[" << lws[0] << "," << lws[1] << "," << lws[2] << "]";
             }
             info.name = ss.str();
             cl_event tmp;
             cl_int   retval = this->_real_function(command_queue, kernel, work_dim, gwo, gws, lws, num_events_in_wait_list, event_wait_list, &tmp);
             info.event      = tmp;
             this->_kernels.push_back(std::move(info));
             return retval;
         }
         else
         {
             return this->_real_function(command_queue, kernel, work_dim, gwo, gws, lws, num_events_in_wait_list, event_wait_list, event);
         }
     };
     // Start intercepting tasks:
     auto task_interceptor = [this](graph::ExecutionTask & task)
     {
         if(task.node != nullptr && !task.node->name().empty())
         {
             this->_prefix = task.node->name() + "/";
         }
         else
         {
             this->_prefix = "";
         }
         this->_real_graph_function(task);
         this->_prefix = "";
     };
     CLSymbols::get().clEnqueueNDRangeKernel_ptr = interceptor;
     graph::TaskExecutor::get().execute_function = task_interceptor;
 }
void test_stop () override virtual
End of the test.
Called after the test teardown ended
Reimplemented from Instrument.
Definition at line 157 of file OpenCLTimer.cpp.
References CLSymbols::clEnqueueNDRangeKernel_ptr, TaskExecutor::execute_function, TaskExecutor::get(), and CLSymbols::get().
 {
     // Restore real function
     CLSymbols::get().clEnqueueNDRangeKernel_ptr = _real_function;
     graph::TaskExecutor::get().execute_function = _real_graph_function;
     _real_graph_function                        = nullptr;
     _real_function                              = nullptr;
 }
The documentation for this class was generated from the following files:
tests/framework/instruments/OpenCLTimer.h
tests/framework/instruments/OpenCLTimer.cpp