Compute Library: GCGEMMMatrixAccumulateBiasesKernel Class Reference
GCGEMMMatrixAccumulateBiasesKernel Class Reference
Interface to add a bias to each row of the input tensor.
#include <GCGEMMMatrixAccumulateBiasesKernel.h>
Public Member Functions
GCGEMMMatrixAccumulateBiasesKernel ()
Default constructor.
GCGEMMMatrixAccumulateBiasesKernel (const GCGEMMMatrixAccumulateBiasesKernel &)=delete
Prevent instances of this class from being copied (As this class contains pointers)
GCGEMMMatrixAccumulateBiasesKernel & operator= (const GCGEMMMatrixAccumulateBiasesKernel &)=delete
Prevent instances of this class from being copied (As this class contains pointers)
GCGEMMMatrixAccumulateBiasesKernel (GCGEMMMatrixAccumulateBiasesKernel &&)=default
Allow instances of this class to be moved.
GCGEMMMatrixAccumulateBiasesKernel & operator= (GCGEMMMatrixAccumulateBiasesKernel &&)=default
Allow instances of this class to be moved.
void configure (IGCTensor *accum, const IGCTensor *biases)
Set the accumulate buffer and the biases of the kernel.
void run (const Window &window) override
Enqueue the OpenGL ES shader to process the given window.
Public Member Functions inherited from IGCKernel
IGCKernel ()
Constructor.
GCKernel & kernel ()
Returns a reference to the GLES kernel of this object.
void add_1D_tensor_argument (unsigned int &idx, const IGCTensor *tensor, const unsigned int binding_point, const Window &window)
Add the passed 1D tensor's parameters to the object's kernel's arguments starting from the index idx.
void add_2D_tensor_argument (unsigned int &idx, const IGCTensor *tensor, const unsigned int binding_point, const Window &window)
Add the passed 2D tensor's parameters to the object's kernel's arguments starting from the index idx.
void add_3D_tensor_argument (unsigned int &idx, const IGCTensor *tensor, const unsigned int binding_point, const Window &window)
Add the passed 3D tensor's parameters to the object's kernel's arguments starting from the index idx.
unsigned int num_arguments_per_1D_tensor () const
Returns the number of arguments enqueued per 1D tensor object.
unsigned int num_arguments_per_2D_tensor () const
Returns the number of arguments enqueued per 2D tensor object.
unsigned int num_arguments_per_3D_tensor () const
Returns the number of arguments enqueued per 3D tensor object.
void set_lws_hint (gles::NDRange &lws_hint)
Set the Local-Workgroup-Size hint.
void set_target (GPUTarget target)
Set the targeted GPU architecture.
GPUTarget get_target () const
Get the targeted GPU architecture.
Public Member Functions inherited from IKernel
IKernel ()
Constructor.
virtual ~IKernel ()=default
Destructor.
virtual bool is_parallelisable () const
Indicates whether or not the kernel is parallelisable.
virtual BorderSize border_size () const
The size of the border for that kernel.
const Window & window () const
The maximum window the kernel can be executed on.
Detailed Description
Interface to add a bias to each row of the input tensor.
Definition at line 34 of file GCGEMMMatrixAccumulateBiasesKernel.h.
Constructor & Destructor Documentation
GCGEMMMatrixAccumulateBiasesKernel() [1/3]
GCGEMMMatrixAccumulateBiasesKernel ()
Default constructor.
Definition at line 39 of file GCGEMMMatrixAccumulateBiasesKernel.cpp.
     : _accum(nullptr), _biases(nullptr), _lws(gles::NDRange(1U, 1U, 1U))
 {
 }
GCGEMMMatrixAccumulateBiasesKernel() [2/3]
GCGEMMMatrixAccumulateBiasesKernel (const GCGEMMMatrixAccumulateBiasesKernel &) delete
Prevent instances of this class from being copied (As this class contains pointers)
GCGEMMMatrixAccumulateBiasesKernel() [3/3]
GCGEMMMatrixAccumulateBiasesKernel (GCGEMMMatrixAccumulateBiasesKernel &&) default
Allow instances of this class to be moved.
Member Function Documentation
configure()
void configure (IGCTensor * accum, const IGCTensor * biases)
Set the accumulate buffer and the biases of the kernel.
Parameters
[in,out] accum The accumulate tensor to convert. Data types supported: F16/F32
[in] biases The shared biases tensor to append. It must be 1D tensor. Data types supported: Same as input
Definition at line 44 of file GCGEMMMatrixAccumulateBiasesKernel.cpp.
 {
     ARM_COMPUTE_ERROR_ON_DATA_TYPE_CHANNEL_NOT_IN(accum, 1, DataType::F16, DataType::F32);
     ARM_COMPUTE_ERROR_ON_MISMATCHING_DATA_TYPES(biases, accum);
     ARM_COMPUTE_ERROR_ON(biases->info()->num_dimensions() != 1);
     _biases = biases;
     _accum  = accum;
     std::set<std::string> build_opts;
     build_opts.emplace("#define LOCAL_SIZE_X " + support::cpp11::to_string(_lws[0]));
     build_opts.emplace("#define LOCAL_SIZE_Y " + support::cpp11::to_string(_lws[1]));
     build_opts.emplace("#define LOCAL_SIZE_Z " + support::cpp11::to_string(_lws[2]));
     // Create kernel
     build_opts.emplace("#define GEMM_ACCUMULATE_BIASES");
 #define ACCUM_PROCESS_4X
 #if defined(ACCUM_PROCESS_4X)
     build_opts.emplace("#define ACCUM_PROCESS_4X");
 #elif defined(ACCUM_PROCESS_8X) /* ACCUM_PROCESS_4X */
     build_opts.emplace("#define ACCUM_PROCESS_8X");
 #endif                          /* ACCUM_PROCESS_4X */
     std::string dt_name = (accum->info()->data_type() == DataType::F32) ? "DATA_TYPE_FP32" : "DATA_TYPE_FP16";
     build_opts.emplace(("#define " + dt_name));
     _kernel = GCKernelLibrary::get().create_kernel("gemm_accumulate_biases", build_opts);
     // Configure kernel window
     unsigned int num_elems_processed_per_iteration = 1;
     if(_accum->info()->data_type() == DataType::F32)
     {
         num_elems_processed_per_iteration = 16;
     }
     else if(_accum->info()->data_type() == DataType::F16)
     {
 #if defined(ACCUM_PROCESS_4X)
         num_elems_processed_per_iteration = 4;
 #elif defined(ACCUM_PROCESS_8X) /* ACCUM_PROCESS_4X */
         num_elems_processed_per_iteration = 8;
 #endif                          /* ACCUM_PROCESS_4X */
     }
     const int  accum_width         = accum->info()->dimension(0);
     const int  accum_padding_right = ceil_to_multiple(accum_width, num_elems_processed_per_iteration * _lws[0]) - accum_width;
     BorderSize border              = BorderSize(0, accum_padding_right, 0, 0);
     Window win = calculate_max_enlarged_window(*_accum->info(), Steps(num_elems_processed_per_iteration), border);
     AccessWindowStatic biases_access(biases->info(), 0, 0, ceil_to_multiple(biases->info()->dimension(0), num_elems_processed_per_iteration * _lws[0]), biases->info()->dimension(1));
     AccessWindowStatic accum_access(_accum->info(), 0, 0, accum_width + accum_padding_right, _accum->info()->dimension(1));
     update_window_and_padding(win, biases_access, accum_access);
     IGCKernel::configure(win);
 }
References ARM_COMPUTE_ERROR_ON, ARM_COMPUTE_ERROR_ON_DATA_TYPE_CHANNEL_NOT_IN, ARM_COMPUTE_ERROR_ON_MISMATCHING_DATA_TYPES, arm_compute::calculate_max_enlarged_window(), arm_compute::ceil_to_multiple(), GCKernelLibrary::create_kernel(), ITensorInfo::data_type(), ITensorInfo::dimension(), arm_compute::F16, arm_compute::F32, GCKernelLibrary::get(), ITensor::info(), ITensorInfo::num_dimensions(), arm_compute::support::cpp11::to_string(), and arm_compute::update_window_and_padding().
Referenced by GCFullyConnectedLayer::configure().
operator=() [1/2]
GCGEMMMatrixAccumulateBiasesKernel& operator= (const GCGEMMMatrixAccumulateBiasesKernel &) delete
Prevent instances of this class from being copied (As this class contains pointers)
operator=() [2/2]
GCGEMMMatrixAccumulateBiasesKernel& operator= (GCGEMMMatrixAccumulateBiasesKernel &&) default
Allow instances of this class to be moved.
run()
void run (const Window & window) override virtual
Enqueue the OpenGL ES shader to process the given window.
Parameters
[in] window Region on which to execute the kernel. (Must be a valid region of the window returned by window()).
Implements IGCKernel.
Definition at line 103 of file GCGEMMMatrixAccumulateBiasesKernel.cpp.
 {
     ARM_COMPUTE_ERROR_ON_UNCONFIGURED_KERNEL(this);
     ARM_COMPUTE_ERROR_ON_MISMATCHING_WINDOWS(IGCKernel::window(), window);
     _kernel.use();
     Window accum_slice = window.first_slice_window_2D();
     Window biases_slice(accum_slice);
     biases_slice.set(Window::DimY, Window::Dimension(0, 1, 1));
     // Run kernel
     do
     {
         // Set arguments
         unsigned int idx = 0;
         add_2D_tensor_argument(idx, _accum, 1, accum_slice);
         add_1D_tensor_argument(idx, _biases, 2, biases_slice);
         _kernel.update_shader_params();
         enqueue(*this, accum_slice, _lws);
     }
     while(window.slide_window_slice_2D(accum_slice));
 }
References IGCKernel::add_1D_tensor_argument(), IGCKernel::add_2D_tensor_argument(), ARM_COMPUTE_ERROR_ON_MISMATCHING_WINDOWS, ARM_COMPUTE_ERROR_ON_UNCONFIGURED_KERNEL, Window::DimY, arm_compute::enqueue(), Window::first_slice_window_2D(), Window::set(), Window::slide_window_slice_2D(), and IKernel::window().
The documentation for this class was generated from the following files:
arm_compute/core/GLES_COMPUTE/kernels/GCGEMMMatrixAccumulateBiasesKernel.h
src/core/GLES_COMPUTE/kernels/GCGEMMMatrixAccumulateBiasesKernel.cpp