Compute Library: GCDeviceBackend Class Reference
GCDeviceBackend Class Reference final
GLES Compute device backend.
#include <GCDeviceBackend.h>
Public Member Functions
GCDeviceBackend ()
Default Constructor.
void initialize_backend () override
Initializes the backend.
void setup_backend_context (GraphContext &ctx) override
Setups the given graph context.
void release_backend_context (GraphContext &ctx) override
Release the backend specific resources associated to a given graph context.
bool is_backend_supported () override
Checks if an instantiated backend is actually supported.
IAllocator * backend_allocator () override
Gets a backend memory allocator.
std::unique_ptr< ITensorHandle > create_tensor (const Tensor &tensor) override
Create a backend Tensor.
std::unique_ptr< ITensorHandle > create_subtensor (ITensorHandle *parent, TensorShape shape, Coordinates coords, bool extend_parent) override
Create a backend Sub-Tensor.
std::unique_ptr< arm_compute::IFunction > configure_node (INode &node, GraphContext &ctx) override
Configure a backend Node.
Status validate_node (INode &node) override
Validate a node.
std::shared_ptr< arm_compute::IMemoryManager > create_memory_manager (MemoryManagerAffinity affinity) override
Create a backend memory manager given its affinity.
Public Member Functions inherited from IDeviceBackend
virtual ~IDeviceBackend ()=default
Virtual Destructor.
Detailed Description
GLES Compute device backend.
Definition at line 38 of file GCDeviceBackend.h.
Constructor & Destructor Documentation
GCDeviceBackend()
GCDeviceBackend ()
Default Constructor.
Definition at line 55 of file GCDeviceBackend.cpp.
     : _initialized(false), _allocator()
 {
 }
Member Function Documentation
backend_allocator()
IAllocator * backend_allocator () override virtual
Gets a backend memory allocator.
Returns
Backend memory allocator
Implements IDeviceBackend.
Definition at line 100 of file GCDeviceBackend.cpp.
 {
     return &_allocator;
 }
configure_node()
std::unique_ptr< arm_compute::IFunction > configure_node (INode & node, GraphContext & ctx) override virtual
Configure a backend Node.
Note
This creates an appropriate configured backend function for the given node
Parameters
[in] node The node we want to configure
[in] ctx Context to use
Returns
Backend execution function
Implements IDeviceBackend.
Definition at line 126 of file GCDeviceBackend.cpp.
 {
     ARM_COMPUTE_LOG_GRAPH_VERBOSE("Configuring GC node with ID : " << node.id() << std::endl);
     ARM_COMPUTE_ERROR_ON(node.assigned_target() != Target::GC);
     // Configure node
     return GCFunctionFactory::create(&node, ctx);
 }
References ARM_COMPUTE_ERROR_ON, ARM_COMPUTE_LOG_GRAPH_VERBOSE, INode::assigned_target(), GCFunctionFactory::create(), arm_compute::graph::GC, and INode::id().
create_memory_manager()
std::shared_ptr< arm_compute::IMemoryManager > create_memory_manager (MemoryManagerAffinity affinity) override virtual
Create a backend memory manager given its affinity.
Parameters
[in] affinity Memory Manager affinity
Returns
Memory manager
Implements IDeviceBackend.
Definition at line 143 of file GCDeviceBackend.cpp.
 {
     if(affinity == MemoryManagerAffinity::Offset)
     {
         ARM_COMPUTE_LOG_GRAPH_WARNING("GC Backend does not support offset affinity memory management!");
         return nullptr;
     }
     auto lifetime_mgr = std::make_shared<BlobLifetimeManager>();
     auto pool_mgr     = std::make_shared<PoolManager>();
     auto mm           = std::make_shared<MemoryManagerOnDemand>(lifetime_mgr, pool_mgr);
     return mm;
 }
References ARM_COMPUTE_LOG_GRAPH_WARNING, and arm_compute::graph::Offset.
Referenced by GCDeviceBackend::setup_backend_context().
create_subtensor()
std::unique_ptr< ITensorHandle > create_subtensor (ITensorHandle * parent, TensorShape shape, Coordinates coords, bool extend_parent) override virtual
Create a backend Sub-Tensor.
Parameters
[in] parent Parent sub-tensor handle
[in] shape Shape of the sub-tensor
[in] coords Starting coordinates of the sub-tensor
[in] extend_parent Extends parent shape if true
Returns
Backend sub-tensor handle
Implements IDeviceBackend.
Definition at line 119 of file GCDeviceBackend.cpp.
 {
     ARM_COMPUTE_UNUSED(parent, shape, coords, extend_parent);
     ARM_COMPUTE_ERROR("GLES backend has no sub-tensor support!");
     return nullptr;
 }
References ARM_COMPUTE_ERROR, ARM_COMPUTE_UNUSED, and arm_compute::test::validation::shape.
create_tensor()
std::unique_ptr< ITensorHandle > create_tensor (const Tensor & tensor) override virtual
Create a backend Tensor.
Parameters
[in] tensor The tensor we want to create a backend tensor for
Returns
Backend tensor handle
Implements IDeviceBackend.
Definition at line 105 of file GCDeviceBackend.cpp.
 {
     // Get tensor descriptor
     const TensorDescriptor &tensor_desc = tensor.desc();
     ARM_COMPUTE_ERROR_ON(tensor_desc.target != Target::GC);
     // Create backend tensor handle
     TensorInfo info(tensor_desc.shape, 1, tensor_desc.data_type, tensor_desc.quant_info);
     info.set_data_layout(tensor_desc.layout);
     auto backend_tensor_handle = support::cpp14::make_unique<GCTensorHandle>(info);
     return std::move(backend_tensor_handle);
 }
References ARM_COMPUTE_ERROR_ON, TensorDescriptor::data_type, Tensor::desc(), arm_compute::graph::GC, arm_compute::test::validation::info, TensorDescriptor::layout, TensorDescriptor::quant_info, TensorDescriptor::shape, and TensorDescriptor::target.
initialize_backend()
void initialize_backend () override virtual
Initializes the backend.
Implements IDeviceBackend.
Definition at line 60 of file GCDeviceBackend.cpp.
 {
     // Setup Scheduler
     GCScheduler::get().default_init();
 }
References GCScheduler::default_init(), and GCScheduler::get().
Referenced by GCDeviceBackend::setup_backend_context().
is_backend_supported()
bool is_backend_supported () override virtual
Checks if an instantiated backend is actually supported.
Returns
True if the backend is supported else false
Implements IDeviceBackend.
Definition at line 95 of file GCDeviceBackend.cpp.
 {
     return arm_compute::opengles31_is_available();
 }
References arm_compute::opengles31_is_available().
release_backend_context()
void release_backend_context (GraphContext & ctx) override virtual
Release the backend specific resources associated to a given graph context.
Parameters
[in,out] ctx Graph context
Implements IDeviceBackend.
Definition at line 66 of file GCDeviceBackend.cpp.
 {
     //Nothing to do
     ARM_COMPUTE_UNUSED(ctx);
 }
References ARM_COMPUTE_UNUSED.
setup_backend_context()
void setup_backend_context (GraphContext & ctx) override virtual
Setups the given graph context.
Parameters
[in,out] ctx Graph context
Implements IDeviceBackend.
Definition at line 72 of file GCDeviceBackend.cpp.
 {
     // Force backend initialization
     if(!_initialized)
     {
         initialize_backend();
         _initialized = true;
     }
     // Setup a management backend
     if(ctx.memory_management_ctx(Target::GC) == nullptr)
     {
         MemoryManagerContext mm_ctx;
         mm_ctx.target      = Target::GC;
         mm_ctx.intra_mm    = create_memory_manager(MemoryManagerAffinity::Buffer);
         mm_ctx.cross_mm    = create_memory_manager(MemoryManagerAffinity::Buffer);
         mm_ctx.cross_group = std::make_shared<GCMemoryGroup>(mm_ctx.cross_mm);
         mm_ctx.allocator   = &_allocator;
         ctx.insert_memory_management_ctx(std::move(mm_ctx));
     }
 }
References MemoryManagerContext::allocator, arm_compute::graph::Buffer, GCDeviceBackend::create_memory_manager(), MemoryManagerContext::cross_group, MemoryManagerContext::cross_mm, arm_compute::graph::GC, GCDeviceBackend::initialize_backend(), GraphContext::insert_memory_management_ctx(), MemoryManagerContext::intra_mm, GraphContext::memory_management_ctx(), and MemoryManagerContext::target.
validate_node()
arm_compute::Status validate_node (INode & node) override virtual
Validate a node.
Parameters
[in] node The node we want to validate
Returns
An error status
Implements IDeviceBackend.
Definition at line 135 of file GCDeviceBackend.cpp.
 {
     ARM_COMPUTE_LOG_GRAPH_VERBOSE("Validating GC node with ID : " << node.id() << std::endl);
     ARM_COMPUTE_ERROR_ON(node.assigned_target() != Target::GC);
     return GCNodeValidator::validate(&node);
 }
References ARM_COMPUTE_ERROR_ON, ARM_COMPUTE_LOG_GRAPH_VERBOSE, INode::assigned_target(), arm_compute::graph::GC, INode::id(), and GCNodeValidator::validate().
The documentation for this class was generated from the following files:
arm_compute/graph/backends/GLES/GCDeviceBackend.h
src/graph/backends/GLES/GCDeviceBackend.cpp