Compute Library: CLReshapeLayerKernel Class Reference
CLReshapeLayerKernel Class Reference
Interface for the kernel to perform tensor reshaping.
#include <CLReshapeLayerKernel.h>
Public Member Functions
CLReshapeLayerKernel ()
Default constructor.
CLReshapeLayerKernel (const CLReshapeLayerKernel &)=delete
Prevent instances of this class from being copied (As this class contains pointers)
CLReshapeLayerKernel & operator= (const CLReshapeLayerKernel &)=delete
Prevent instances of this class from being copied (As this class contains pointers)
CLReshapeLayerKernel (CLReshapeLayerKernel &&)=default
Allow instances of this class to be moved.
CLReshapeLayerKernel & operator= (CLReshapeLayerKernel &&)=default
Allow instances of this class to be moved.
~CLReshapeLayerKernel ()=default
Default destructor.
void configure (const ICLTensor *input, ICLTensor *output)
Set the input and output of the kernel.
void run (const Window &window, cl::CommandQueue &queue) override
Enqueue the OpenCL kernel to process the given window on the passed OpenCL command queue.
Public Member Functions inherited from ICLKernel
ICLKernel ()
Constructor.
cl::Kernel & kernel ()
Returns a reference to the OpenCL kernel of this object.
template<typename T >
void add_1D_array_argument (unsigned int &idx, const ICLArray< T > *array, const Strides &strides, unsigned int num_dimensions, const Window &window)
Add the passed 1D array's parameters to the object's kernel's arguments starting from the index idx.
void add_1D_tensor_argument (unsigned int &idx, const ICLTensor *tensor, const Window &window)
Add the passed 1D tensor's parameters to the object's kernel's arguments starting from the index idx.
void add_1D_tensor_argument_if (bool cond, unsigned int &idx, const ICLTensor *tensor, const Window &window)
Add the passed 1D tensor's parameters to the object's kernel's arguments starting from the index idx if the condition is true.
void add_2D_tensor_argument (unsigned int &idx, const ICLTensor *tensor, const Window &window)
Add the passed 2D tensor's parameters to the object's kernel's arguments starting from the index idx.
void add_2D_tensor_argument_if (bool cond, unsigned int &idx, const ICLTensor *tensor, const Window &window)
Add the passed 2D tensor's parameters to the object's kernel's arguments starting from the index idx if the condition is true.
void add_3D_tensor_argument (unsigned int &idx, const ICLTensor *tensor, const Window &window)
Add the passed 3D tensor's parameters to the object's kernel's arguments starting from the index idx.
void add_4D_tensor_argument (unsigned int &idx, const ICLTensor *tensor, const Window &window)
Add the passed 4D tensor's parameters to the object's kernel's arguments starting from the index idx.
template<typename T >
void add_argument (unsigned int &idx, T value)
Add the passed parameters to the object's kernel's arguments starting from the index idx.
void set_lws_hint (const cl::NDRange &lws_hint)
Set the Local-Workgroup-Size hint.
cl::NDRange lws_hint () const
Return the Local-Workgroup-Size hint.
const std::string & config_id () const
Get the configuration ID.
void set_target (GPUTarget target)
Set the targeted GPU architecture.
void set_target (cl::Device &device)
Set the targeted GPU architecture according to the CL device.
GPUTarget get_target () const
Get the targeted GPU architecture.
size_t get_max_workgroup_size ()
Get the maximum workgroup size for the device the CLKernelLibrary uses.
template<typename T , unsigned int dimension_size>
void add_array_argument (unsigned &idx, const ICLArray< T > *array, const Strides &strides, unsigned int num_dimensions, const Window &window)
Add the passed array's parameters to the object's kernel's arguments starting from the index idx.
template<unsigned int dimension_size>
void add_tensor_argument (unsigned &idx, const ICLTensor *tensor, const Window &window)
Public Member Functions inherited from IKernel
IKernel ()
Constructor.
virtual ~IKernel ()=default
Destructor.
virtual bool is_parallelisable () const
Indicates whether or not the kernel is parallelisable.
virtual BorderSize border_size () const
The size of the border for that kernel.
const Window & window () const
The maximum window the kernel can be executed on.
Static Public Member Functions
static Status validate (const ITensorInfo *input, const ITensorInfo *output)
Static function to check if given info will lead to a valid configuration of CLReshapeLayerKernel.
Static Public Member Functions inherited from ICLKernel
static constexpr unsigned int num_arguments_per_1D_array ()
Returns the number of arguments enqueued per 1D array object.
static constexpr unsigned int num_arguments_per_1D_tensor ()
Returns the number of arguments enqueued per 1D tensor object.
static constexpr unsigned int num_arguments_per_2D_tensor ()
Returns the number of arguments enqueued per 2D tensor object.
static constexpr unsigned int num_arguments_per_3D_tensor ()
Returns the number of arguments enqueued per 3D tensor object.
static constexpr unsigned int num_arguments_per_4D_tensor ()
Returns the number of arguments enqueued per 4D tensor object.
static cl::NDRange gws_from_window (const Window &window)
Get the global work size given an execution window.
Detailed Description
Interface for the kernel to perform tensor reshaping.
Definition at line 35 of file CLReshapeLayerKernel.h.
Constructor & Destructor Documentation
CLReshapeLayerKernel() [1/3]
CLReshapeLayerKernel ()
Default constructor.
Definition at line 62 of file CLReshapeLayerKernel.cpp.
     : _input(nullptr), _output(nullptr)
 {
 }
CLReshapeLayerKernel() [2/3]
CLReshapeLayerKernel (const CLReshapeLayerKernel &) delete
Prevent instances of this class from being copied (As this class contains pointers)
CLReshapeLayerKernel() [3/3]
CLReshapeLayerKernel (CLReshapeLayerKernel &&) default
Allow instances of this class to be moved.
~CLReshapeLayerKernel()
~CLReshapeLayerKernel () default
Default destructor.
Member Function Documentation
configure()
void configure (const ICLTensor * input, ICLTensor * output)
Set the input and output of the kernel.
Parameters
[in] input Source tensor. Data type supported: U8/S8/QASYMM8/U16/S16/U32/S32/F16/F32
[out] output Destination tensor. Data type supported: Same as input
Definition at line 67 of file CLReshapeLayerKernel.cpp.
 {
     ARM_COMPUTE_ERROR_ON_NULLPTR(input, output);
     ARM_COMPUTE_ERROR_THROW_ON(validate_arguments(input->info(), output->info()));
     _input  = input;
     _output = output;
     // Create kernel
     std::set<std::string> build_opts = { "-DDATA_TYPE=" + get_cl_type_from_data_type(input->info()->data_type()) };
     _kernel                          = static_cast<cl::Kernel>(CLKernelLibrary::get().create_kernel("reshape_layer", build_opts));
     // Add static arguments
     const cl_int2 input_shape =
     {
         {
             static_cast<cl_int>(_input->info()->tensor_shape()[0]),
             static_cast<cl_int>(_input->info()->tensor_shape()[1])
         }
     };
     const cl_int2 output_shape =
     {
         {
             static_cast<cl_int>(_output->info()->tensor_shape()[0]),
             static_cast<cl_int>(_output->info()->tensor_shape()[1])
         }
     };
     unsigned int idx = 2 * num_arguments_per_3D_tensor(); // Skip the input and output parameters
     _kernel.setArg<cl_int2>(idx++, input_shape);
     _kernel.setArg<cl_int2>(idx++, output_shape);
     // Configure kernel window
     Window win = calculate_max_window(*input->info());
     // Set the output valid region
     output->info()->set_valid_region(ValidRegion(Coordinates(), output->info()->tensor_shape()));
     ICLKernel::configure_internal(win);
 }
References ARM_COMPUTE_ERROR_ON_NULLPTR, ARM_COMPUTE_ERROR_THROW_ON, arm_compute::calculate_max_window(), arm_compute::create_kernel(), ITensorInfo::data_type(), CLKernelLibrary::get(), arm_compute::get_cl_type_from_data_type(), ITensor::info(), arm_compute::test::validation::input_shape, ICLKernel::num_arguments_per_3D_tensor(), arm_compute::test::validation::output_shape, ITensorInfo::set_valid_region(), and ITensorInfo::tensor_shape().
Referenced by CLSoftmaxLayer::configure(), and CLGenerateProposalsLayer::configure().
operator=() [1/2]
CLReshapeLayerKernel& operator= (const CLReshapeLayerKernel &) delete
Prevent instances of this class from being copied (As this class contains pointers)
operator=() [2/2]
CLReshapeLayerKernel& operator= (CLReshapeLayerKernel &&) default
Allow instances of this class to be moved.
run()
void run (const Window & window, cl::CommandQueue & queue) override virtual
Enqueue the OpenCL kernel to process the given window on the passed OpenCL command queue.
Note
The queue is not flushed by this method, and therefore the kernel will not have been executed by the time this method returns.
Parameters
[in] window Region on which to execute the kernel. (Must be a valid region of the window returned by window()).
[in,out] queue Command queue on which to enqueue the kernel.
Implements ICLKernel.
Definition at line 113 of file CLReshapeLayerKernel.cpp.
 {
     ARM_COMPUTE_ERROR_ON_UNCONFIGURED_KERNEL(this);
     ARM_COMPUTE_ERROR_ON_INVALID_SUBWINDOW(IKernel::window(), window);
     Window window_collapsed = window.collapse_if_possible(ICLKernel::window(), Window::DimZ);
     Window slice            = window_collapsed.first_slice_window_3D();
     // Set inputs
     unsigned int idx = 0;
     add_3D_tensor_argument(idx, _input, window_collapsed);
     add_3D_tensor_argument(idx, _output, window_collapsed);
     enqueue(queue, *this, slice);
 }
References ICLKernel::add_3D_tensor_argument(), ARM_COMPUTE_ERROR_ON_INVALID_SUBWINDOW, ARM_COMPUTE_ERROR_ON_UNCONFIGURED_KERNEL, Window::collapse_if_possible(), Window::DimZ, arm_compute::enqueue(), Window::first_slice_window_3D(), arm_compute::test::validation::reference::slice(), and IKernel::window().
validate()
Status validate (const ITensorInfo * input, const ITensorInfo * output) static
Static function to check if given info will lead to a valid configuration of CLReshapeLayerKernel.
Parameters
[in] input Source tensor info. Data type supported: U8/S8/QASYMM8/U16/S16/U32/S32/F16/F32
[in] output Destination tensor info. Data type supported: Same as input
Returns
a status
Definition at line 106 of file CLReshapeLayerKernel.cpp.
 {
     ARM_COMPUTE_RETURN_ON_ERROR(validate_arguments(input, output));
     return Status{};
 }
References ARM_COMPUTE_RETURN_ON_ERROR.
Referenced by CLReshapeLayer::validate(), CLSoftmaxLayer::validate(), and CLGenerateProposalsLayer::validate().
The documentation for this class was generated from the following files:
arm_compute/core/CL/kernels/CLReshapeLayerKernel.h
src/core/CL/kernels/CLReshapeLayerKernel.cpp