Compute Library: NEHOGGradient Class Reference
NEHOGGradient Class Reference
Basic function to calculate the gradient for HOG.
#include <NEHOGGradient.h>
Public Member Functions
NEHOGGradient (std::shared_ptr< IMemoryManager > memory_manager=nullptr)
Default constructor.
void configure (ITensor *input, ITensor *output_magnitude, ITensor *output_phase, PhaseType phase_type, BorderMode border_mode, uint8_t constant_border_value=0)
Initialise the function's source, destinations, phase type and border mode.
void run () override
Run the kernels contained in the function.
Public Member Functions inherited from IFunction
virtual ~IFunction ()=default
Destructor.
virtual void prepare ()
Prepare the function for executing.
Detailed Description
Basic function to calculate the gradient for HOG.
This function calls the following NEON kernels:
NEDerivative
NEMagnitudePhaseKernel
Definition at line 47 of file NEHOGGradient.h.
Constructor & Destructor Documentation
NEHOGGradient()
NEHOGGradient (std::shared_ptr< IMemoryManager > memory_manager = nullptr)
Default constructor.
Definition at line 33 of file NEHOGGradient.cpp.
     : _memory_group(std::move(memory_manager)),
       _derivative(),
       _mag_phase(nullptr),
       _gx(),
       _gy()
 {
 }
Member Function Documentation
configure()
void configure (ITensor * input, ITensor * output_magnitude, ITensor * output_phase, PhaseType phase_type, BorderMode border_mode, uint8_t constant_border_value = 0)
Initialise the function's source, destinations, phase type and border mode.
Parameters
[in,out] input Input tensor. Data type supported: U8. (Written to only for border_mode != UNDEFINED)
[out] output_magnitude Output tensor (magnitude). Data type supported: U16.
[out] output_phase Output tensor.(phase). Format supported: U8
[in] phase_type Type of PhaseType
[in] border_mode Border mode to use
[in] constant_border_value (Optional) Constant value to use for borders if border_mode is set to CONSTANT.
Definition at line 42 of file NEHOGGradient.cpp.
 {
     ARM_COMPUTE_ERROR_ON_DATA_TYPE_CHANNEL_NOT_IN(input, 1, DataType::U8);
     ARM_COMPUTE_ERROR_ON_DATA_TYPE_CHANNEL_NOT_IN(output_magnitude, 1, DataType::S16);
     ARM_COMPUTE_ERROR_ON_DATA_TYPE_CHANNEL_NOT_IN(output_phase, 1, DataType::U8);
     const TensorShape &shape_img = input->info()->tensor_shape();
     // Allocate image memory
     TensorInfo info(shape_img, Format::S16);
     _gx.allocator()->init(info);
     _gy.allocator()->init(info);
     // Manage intermediate buffers
     _memory_group.manage(&_gx);
     _memory_group.manage(&_gy);
     // Initialise derivate kernel
     _derivative.configure(input, &_gx, &_gy, border_mode, constant_border_value);
     // Initialise magnitude/phase kernel
     if(PhaseType::UNSIGNED == phase_type)
     {
         auto k = arm_compute::support::cpp14::make_unique<NEMagnitudePhaseKernel<MagnitudeType::L2NORM, PhaseType::UNSIGNED>>();
         k->configure(&_gx, &_gy, output_magnitude, output_phase);
         _mag_phase = std::move(k);
     }
     else
     {
         auto k = arm_compute::support::cpp14::make_unique<NEMagnitudePhaseKernel<MagnitudeType::L2NORM, PhaseType::SIGNED>>();
         k->configure(&_gx, &_gy, output_magnitude, output_phase);
         _mag_phase = std::move(k);
     }
     // Allocate intermediate tensors
     _gx.allocator()->allocate();
     _gy.allocator()->allocate();
 }
References TensorAllocator::allocate(), Tensor::allocator(), ARM_COMPUTE_ERROR_ON_DATA_TYPE_CHANNEL_NOT_IN, arm_compute::test::validation::border_mode, NEDerivative::configure(), ITensor::info(), arm_compute::test::validation::info, TensorAllocator::init(), MemoryGroupBase< TensorType >::manage(), arm_compute::S16, ITensorInfo::tensor_shape(), arm_compute::U8, and arm_compute::UNSIGNED.
Referenced by NEHOGDescriptor::configure(), and NEHOGMultiDetection::configure().
run()
void run () override virtual
Run the kernels contained in the function.
For NEON kernels:
Multi-threading is used for the kernels which are parallelisable.
By default std::thread::hardware_concurrency() threads are used.
Note
CPPScheduler::set_num_threads() can be used to manually set the number of threads
For OpenCL kernels:
All the kernels are enqueued on the queue associated with CLScheduler.
The queue is then flushed.
Note
The function will not block until the kernels are executed. It is the user's responsibility to wait.
Will call prepare() on first run if hasn't been done
Implements IFunction.
Definition at line 81 of file NEHOGGradient.cpp.
 {
     _memory_group.acquire();
     // Run derivative
     _derivative.run();
     // Run magnitude/phase kernel
     NEScheduler::get().schedule(_mag_phase.get(), Window::DimY);
     _memory_group.release();
 }
References MemoryGroupBase< TensorType >::acquire(), Window::DimY, Scheduler::get(), MemoryGroupBase< TensorType >::release(), NEDerivative::run(), and IScheduler::schedule().
Referenced by NEHOGDescriptor::run(), and NEHOGMultiDetection::run().
The documentation for this class was generated from the following files:
arm_compute/runtime/NEON/functions/NEHOGGradient.h
src/runtime/NEON/functions/NEHOGGradient.cpp