Compute Library: Pyramid Class Reference
Pyramid Class Reference
Basic implementation of the pyramid interface.
#include <Pyramid.h>
Public Member Functions
void init (const PyramidInfo &info)
Initialize pyramid data-object using the given Pyramid's metadata.
void init_auto_padding (const PyramidInfo &info)
Initialize pyramid data-object using the given Pyramid's metadata.
void allocate ()
Allocate the planes in the pyramid.
const PyramidInfo * info () const override
Interface to be implemented by the child class to return the Pyramid's metadata.
Tensor * get_pyramid_level (size_t index) const override
Retrieves a level of the pyramid as a ITensor pointer.
Public Member Functions inherited from IPyramid
virtual ~IPyramid ()=default
Default virtual destructor.
Detailed Description
Basic implementation of the pyramid interface.
Definition at line 40 of file Pyramid.h.
Member Function Documentation
allocate()
void allocate ()
Allocate the planes in the pyramid.
Definition at line 100 of file Pyramid.cpp.
 {
     for(size_t i = 0; i < _info.num_levels(); ++i)
     {
         _pyramid[i].allocator()->allocate();
     }
 }
References PyramidInfo::num_levels().
Referenced by NELaplacianPyramid::configure(), and NELaplacianReconstruct::configure().
get_pyramid_level()
Tensor * get_pyramid_level (size_t index) const override virtual
Retrieves a level of the pyramid as a ITensor pointer.
Parameters
[in] index The index of the level, such that index is less than levels.
Returns
An ITensor pointer
Implements IPyramid.
Definition at line 113 of file Pyramid.cpp.
 {
     ARM_COMPUTE_ERROR_ON(index >= _info.num_levels());
     return &_pyramid[index];
 }
References ARM_COMPUTE_ERROR_ON, and PyramidInfo::num_levels().
Referenced by NELaplacianPyramid::configure(), NELaplacianReconstruct::configure(), and NEOpticalFlow::configure().
info()
const PyramidInfo * info () const override virtual
Interface to be implemented by the child class to return the Pyramid's metadata.
Returns
A pointer to the Pyramid's metadata.
Implements IPyramid.
Definition at line 108 of file Pyramid.cpp.
 {
     return &_info;
 }
Referenced by NEOpticalFlow::configure(), Pyramid::init(), Pyramid::init_auto_padding(), and NELaplacianReconstruct::run().
init()
void init (const PyramidInfo & info)
Initialize pyramid data-object using the given Pyramid's metadata.
Parameters
[in] info Pyramid's metadata
Definition at line 36 of file Pyramid.cpp.
 {
     internal_init(info, false);
 }
References Pyramid::info().
Referenced by NELaplacianPyramid::configure(), and NELaplacianReconstruct::configure().
init_auto_padding()
void init_auto_padding (const PyramidInfo & info)
Initialize pyramid data-object using the given Pyramid's metadata.
Note
Uses conservative padding strategy which fits all kernels.
Parameters
[in] info Pyramid's metadata
Definition at line 41 of file Pyramid.cpp.
 {
     internal_init(info, true);
 }
References Pyramid::info().
The documentation for this class was generated from the following files:
arm_compute/runtime/Pyramid.h
src/runtime/Pyramid.cpp