Compute Library: CommandLineParser Class Reference
CommandLineParser Class Reference final
Class to parse command line arguments.
#include <CommandLineParser.h>
Public Member Functions
CommandLineParser ()=default
Default constructor.
template<typename T , typename... As>
T * add_option (const std::string &name, As &&... args)
Function to add a new option to the parser.
template<typename T , typename... As>
T * add_positional_option (As &&... args)
Function to add a new positional argument to the parser.
void parse (int argc, char **argv)
Parses the command line arguments and updates the options accordingly.
bool validate () const
Validates the previously parsed command line arguments.
void print_help (const std::string &program_name) const
Prints a help message for all configured options.
Detailed Description
Class to parse command line arguments.
Definition at line 44 of file CommandLineParser.h.
Constructor & Destructor Documentation
CommandLineParser()
CommandLineParser () default
Default constructor.
Member Function Documentation
add_option()
T * add_option (const std::string & name, As &&... args) inline
Function to add a new option to the parser.
Parameters
[in] name Name of the option. Will be available under –name=VALUE.
[in] args Option specific configuration arguments.
Returns
Pointer to the option. The option is owned by the parser.
Definition at line 103 of file CommandLineParser.h.
 {
     auto result = _options.emplace(name, support::cpp14::make_unique<T>(name, std::forward<As>(args)...));
     return static_cast<T *>(result.first->second.get());
 }
Referenced by CommonGraphOptions::CommonGraphOptions(), CommonOptions::CommonOptions(), and main().
add_positional_option()
T * add_positional_option (As &&... args) inline
Function to add a new positional argument to the parser.
Parameters
[in] args Option specific configuration arguments.
Returns
Pointer to the option. The option is owned by the parser.
Definition at line 110 of file CommandLineParser.h.
 {
     _positional_options.emplace_back(support::cpp14::make_unique<T>(std::forward<As>(args)...));
     return static_cast<T *>(_positional_options.back().get());
 }
Referenced by main().
parse()
void parse (int argc, char ** argv) inline
Parses the command line arguments and updates the options accordingly.
Parameters
[in] argc Number of arguments.
[in] argv Arguments.
Definition at line 116 of file CommandLineParser.h.
 {
     const std::regex option_regex{ "--((?:no-)?)([^=]+)(?:=(.*))?" };
     const auto set_option = [&](const std::string & option, const std::string & name, const std::string & value)
     {
         if(_options.find(name) == _options.end())
         {
             _unknown_options.push_back(option);
             return;
         }
         const bool success = _options[name]->parse(value);
         if(!success)
         {
             _invalid_options.push_back(option);
         }
     };
     unsigned int positional_index = 0;
     for(int i = 1; i < argc; ++i)
     {
         std::string mixed_case_opt{ argv[i] };
         int         equal_sign = mixed_case_opt.find('=');
         int         pos        = (equal_sign == -1) ? strlen(argv[i]) : equal_sign;
         const std::string option = arm_compute::utility::tolower(mixed_case_opt.substr(0, pos)) + mixed_case_opt.substr(pos);
         std::smatch       option_matches;
         if(std::regex_match(option, option_matches, option_regex))
         {
             // Boolean option
             if(option_matches.str(3).empty())
             {
                 set_option(option, option_matches.str(2), option_matches.str(1).empty() ? "true" : "false");
             }
             else
             {
                 // Can't have "no-" and a value
                 if(!option_matches.str(1).empty())
                 {
                     _invalid_options.emplace_back(option);
                 }
                 else
                 {
                     set_option(option, option_matches.str(2), option_matches.str(3));
                 }
             }
         }
         else
         {
             if(positional_index >= _positional_options.size())
             {
                 _invalid_options.push_back(mixed_case_opt);
             }
             else
             {
                 _positional_options[positional_index]->parse(mixed_case_opt);
                 ++positional_index;
             }
         }
     }
 }
Referenced by main().
print_help()
void print_help (const std::string & program_name) const inline
Prints a help message for all configured options.
Parameters
[in] program_name Name of the program to be used in the help message.
Definition at line 217 of file CommandLineParser.h.
 {
     std::cout << "usage: " << program_name << " \n";
     for(const auto &option : _options)
     {
         std::cout << option.second->help() << "\n";
     }
     for(const auto &option : _positional_options)
     {
         //FIXME: Print help string as well
         std::cout << option->name() << "\n";
     }
 }
Referenced by main().
validate()
bool validate () const inline
Validates the previously parsed command line arguments.
Validation fails if not all required options are provided. Additionally warnings are generated for options that have illegal values or unknown options.
Returns
True if all required options have been provided.
Definition at line 182 of file CommandLineParser.h.
 {
     bool is_valid = true;
     for(const auto &option : _options)
     {
         if(option.second->is_required() && !option.second->is_set())
         {
             is_valid = false;
             std::cerr << "ERROR: Option '" << option.second->name() << "' is required but not given!\n";
         }
     }
     for(const auto &option : _positional_options)
     {
         if(option->is_required() && !option->is_set())
         {
             is_valid = false;
             std::cerr << "ERROR: Option '" << option->name() << "' is required but not given!\n";
         }
     }
     for(const auto &option : _unknown_options)
     {
         std::cerr << "WARNING: Skipping unknown option '" << option << "'!\n";
     }
     for(const auto &option : _invalid_options)
     {
         std::cerr << "WARNING: Skipping invalid option '" << option << "'!\n";
     }
     return is_valid;
 }
Referenced by main().
The documentation for this class was generated from the following file:
utils/command_line/CommandLineParser.h