Compute Library: FixedPointValidationFixture< TensorType, AccessorType, T > Class Template Reference
FixedPointValidationFixture< TensorType, AccessorType, T > Class Template Reference
#include <FixedPointFixture.h>
Public Member Functions
template<typename... >
void setup (TensorShape shape, DataType dt, FixedPointOp op, int fractional_bits)
Public Member Functions inherited from Fixture
void setup ()
Setup function.
void teardown ()
Teardown function.
Detailed Description
template<typename TensorType, typename AccessorType, typename T>
class arm_compute::test::validation::FixedPointValidationFixture< TensorType, AccessorType, T >
Definition at line 44 of file FixedPointFixture.h.
Member Function Documentation
void setup (TensorShape shape, DataType dt, FixedPointOp op, int fractional_bits) inline
Definition at line 48 of file FixedPointFixture.h.
References ITensorAllocator::allocate(), CLTensor::allocator(), ARM_COMPUTE_ERROR, arm_compute::test::validation::ARM_COMPUTE_EXPECT(), arm_compute::test::validation::dst, arm_compute::test::framework::ERRORS, arm_compute::EXP, arm_compute::INV_SQRT, arm_compute::test::library, arm_compute::LOG, arm_compute::test::fixed_point_arithmetic::detail::max(), arm_compute::test::fixed_point_arithmetic::detail::min(), arm_compute::QS8, arm_compute::RECIPROCAL, arm_compute::test::validation::shape, arm_compute::test::validation::src, and arm_compute::U.
     {
         _fractional_bits = fractional_bits;
         _target          = compute_target(shape, dt, op, fractional_bits);
         _reference       = compute_reference(shape, dt, op, fractional_bits);
     }
The documentation for this class was generated from the following file:
tests/validation/fixtures/FixedPointFixture.h