Compute Library: FullyConnectedLayerFixture< TensorType, Function, Accessor > Class Template Reference
FullyConnectedLayerFixture< TensorType, Function, Accessor > Class Template Reference
Fixture that can be used for NEON and CL.
#include <FullyConnectedLayerFixture.h>
Public Member Functions
template<typename... >
void setup (TensorShape src_shape, TensorShape weights_shape, TensorShape biases_shape, TensorShape dst_shape, DataType data_type, int batches)
void run ()
void teardown ()
Public Member Functions inherited from Fixture
void setup ()
Setup function.
void teardown ()
Teardown function.
Detailed Description
template<typename TensorType, typename Function, typename Accessor>
class arm_compute::test::FullyConnectedLayerFixture< TensorType, Function, Accessor >
Fixture that can be used for NEON and CL.
Definition at line 46 of file FullyConnectedLayerFixture.h.
Member Function Documentation
void run () inline
Definition at line 78 of file FullyConnectedLayerFixture.h.
References arm_compute::test::validation::dst, arm_compute::test::gles_compute::force_sync_tensor(), arm_compute::opengles31_is_available(), caffe_data_extractor::type, and value.
     {
         fc_layer.run();
 #ifdef ARM_COMPUTE_GC
         if(opengles31_is_available() && std::is_same<typename std::decay<TensorType>::type, arm_compute::GCTensor>::value)
         {
             force_sync_tensor(dst);
         }
 #endif /* ARM_COMPUTE_GC */
     }
void setup (TensorShape src_shape, TensorShape weights_shape, TensorShape biases_shape, TensorShape dst_shape, DataType data_type, int batches) inline
Definition at line 50 of file FullyConnectedLayerFixture.h.
References TensorAllocator::allocate(), Tensor::allocator(), arm_compute::test::validation::data_type, arm_compute::test::validation::dst, arm_compute::test::library, Dimensions< T >::num_dimensions(), and TensorShape::set().
     {
         // Set batched in source and destination shapes
         const unsigned int fixed_point_position = 4;
         src_shape.set(src_shape.num_dimensions() /* batch */, batches);
         dst_shape.set(dst_shape.num_dimensions() /* batch */, batches);
         // Create tensors
         src     = create_tensor<TensorType>(src_shape, data_type, 1, fixed_point_position);
         weights = create_tensor<TensorType>(weights_shape, data_type, 1, fixed_point_position);
         biases  = create_tensor<TensorType>(biases_shape, data_type, 1, fixed_point_position);
         dst     = create_tensor<TensorType>(dst_shape, data_type, 1, fixed_point_position);
         // Create and configure function
         fc_layer.configure(&src, &weights, &biases, &dst);
         // Allocate tensors
         src.allocator()->allocate();
         weights.allocator()->allocate();
         biases.allocator()->allocate();
         dst.allocator()->allocate();
         // Fill tensors
         library->fill_tensor_uniform(Accessor(src), 0);
         library->fill_tensor_uniform(Accessor(weights), 1);
         library->fill_tensor_uniform(Accessor(biases), 2);
     }
void teardown () inline
Definition at line 89 of file FullyConnectedLayerFixture.h.
References Tensor::allocator(), arm_compute::test::validation::dst, and TensorAllocator::free().
     {
         src.allocator()->free();
         weights.allocator()->free();
         biases.allocator()->free();
         dst.allocator()->free();
     }
The documentation for this class was generated from the following file:
tests/benchmark/fixtures/FullyConnectedLayerFixture.h