Compute Library: NEGEMMInterleavedWrapper Class Reference
NEGEMMInterleavedWrapper Class Reference
Equivalent to arm_gemm::GemmInterleaved but using Compute Library types.
#include <NEGEMMInterleavedWrapper.h>
Public Member Functions
NEGEMMInterleavedWrapper (std::shared_ptr< IMemoryManager > memory_manager=nullptr)
~NEGEMMInterleavedWrapper ()=default
NEGEMMInterleavedWrapper (const NEGEMMInterleavedWrapper &)=delete
NEGEMMInterleavedWrapper & operator= (const NEGEMMInterleavedWrapper &)=delete
void configure (const ITensor *a, const ITensor *b, ITensor *c, float alpha, float beta, const GEMMInfo &gemm_info)
Initialise the kernel's input and output.
void run () override
Run the kernels contained in the function.
void prepare () override
Prepare the function for executing.
Public Member Functions inherited from IFunction
virtual ~IFunction ()=default
Destructor.
Detailed Description
Equivalent to arm_gemm::GemmInterleaved but using Compute Library types.
Definition at line 94 of file NEGEMMInterleavedWrapper.h.
Constructor & Destructor Documentation
NEGEMMInterleavedWrapper() [1/2]
NEGEMMInterleavedWrapper (std::shared_ptr< IMemoryManager > memory_manager = nullptr)
Definition at line 183 of file NEGEMMInterleavedWrapper.cpp.
     : _memory_group(std::move(memory_manager))
 {
 }
~NEGEMMInterleavedWrapper()
~NEGEMMInterleavedWrapper () default
NEGEMMInterleavedWrapper() [2/2]
NEGEMMInterleavedWrapper (const NEGEMMInterleavedWrapper &) delete
Member Function Documentation
configure()
void configure (const ITensor * a, const ITensor * b, ITensor * c, float alpha, float beta, const GEMMInfo & gemm_info)
Initialise the kernel's input and output.
Note
The input and output tensor must have the same dimensions
Parameters
[in] a Input tensor (Matrix A)
[in] b Input tensor (Matrix B)
[out] c Output tensor to store the result of matrix multiplication. Data type supported: same as input0.
[in] alpha Scalar multiplier to apply to AB matrix product.
[in] beta Scalar multiplier to apply to input C matrix before adding product.
[in] gemm_info GEMM meta-data
Definition at line 342 of file NEGEMMInterleavedWrapper.cpp.
 {
     _params         = INEGEMMWrapperKernel::extract_parameters(a, b, c, gemm_info);
     _a              = a;
     _b              = b;
     _c              = c;
     _pretranspose_b = gemm_info.pretranpose_B();
     const DataType     input_type  = a->info()->data_type();
     const CPUInfo     &ci          = NEScheduler::get().cpu_info();
     const unsigned int num_threads = NEScheduler::get().num_threads();
     const arm_gemm::KernelDescription gemm_kernel_info = get_gemm_info(input_type, ci, num_threads, _params, alpha, beta, _pretranspose_b);
     ARM_COMPUTE_ERROR_ON(gemm_kernel_info.method != arm_gemm::GemmMethod::GEMM_INTERLEAVED);
     // Forcing 128-byte alignment (required by 32-bit kernels)
     const unsigned int alignment = 128;
     _transformed_b.allocator()->init(TensorInfo{}, alignment);
     _tmp_c.allocator()->init(TensorInfo{}, alignment);
     _tag = "NEGEMMInterleaved_" + gemm_kernel_info.name;
     // Get strategy
     std::unique_ptr<detail::IInterleavedStrategy> strategy = detail::create_strategy(gemm_kernel_info.name);
     _num_windows                                           = iceildiv(_params.M, strategy->out_height()) * _params.batches;
     ARM_COMPUTE_ERROR_ON(strategy == nullptr);
     if(!_pretranspose_b)
     {
         _block_sizes = strategy->calculate_block_sizes_for_strategy(ci, _params);
         _batch_window.set(Window::DimX, Window::Dimension(0, ceil_to_multiple(_block_sizes.m_round, _block_sizes.strategy_out_height), _block_sizes.strategy_out_height));
         _batch_window.set(Window::DimY, Window::Dimension(0, _params.batches));
         // If the execution is single threaded or has only one window then the buffer manager only needs 1 buffer else we will use NUM_BUFFERS buffers and ping pong between them:
         const unsigned int num_iterations = _batch_window.num_iterations_total();
         if(NEScheduler::get().num_threads() == 1 || num_iterations == 1)
         {
             _buffer_manager = support::cpp14::make_unique<BufferManagerSingleThread>();
         }
         else
         {
 #ifdef NO_MULTI_THREADING
             ARM_COMPUTE_ERROR("Can't have more than 1 buffer without multiple threads");
 #else  /* NO_MULTI_THREADING */
             _buffer_manager = support::cpp14::make_unique<BufferManagerMultipleThreads>(NEScheduler::get().num_threads());
 #endif /* NO_MULTI_THREADING */
         }
         // If B is transposed at every iteration then transformed_B can be managed:
         _memory_group.manage(&_transformed_b);
         auto_init_if_empty(*_transformed_b.info(), _b->info()->clone()->set_tensor_shape(TensorShape(_block_sizes.x_block * _block_sizes.k_block, _buffer_manager->num_buffers())));
     }
     else
     {
         _tag += "_preB";
     }
     _prepare_b = strategy->instantiate_prepareB(b, &_transformed_b, _params, ci);
     ARM_COMPUTE_ERROR_ON(_prepare_b == nullptr);
     if(_pretranspose_b)
     {
         _block_sizes = _prepare_b->block_sizes();
         _batch_window.set(Window::DimX, Window::Dimension(0, ceil_to_multiple(_block_sizes.m_round, _block_sizes.strategy_out_height), _block_sizes.strategy_out_height));
         _batch_window.set(Window::DimY, Window::Dimension(0, _params.batches));
     }
     _block_walker.set(Window::DimX, Window::Dimension(0, ceil_to_multiple(_params.N, _block_sizes.x_block), _block_sizes.x_block));
     _block_walker.set(Window::DimY, Window::Dimension(0, ceil_to_multiple(_params.K, _block_sizes.k_block), _block_sizes.k_block));
     _block_walker.set(Window::DimZ, Window::Dimension(0, _params.multis));
     _transformed_a.allocator()->init(TensorInfo(TensorShape{ _block_sizes.k_block, _block_sizes.m_round, _params.batches }, 1, input_type), alignment);
     _memory_group.manage(&_transformed_a);
     _memory_group.manage(&_tmp_c);
     _transform_a     = strategy->instantiate_transformA(_a, &_transformed_a, _block_walker, _params, gemm_info);
     _matrix_multiply = strategy->instantiate_matrix_multiply(&_transformed_a, &_transformed_b, &_tmp_c, c, _block_walker, _block_sizes, _params, alpha, beta, gemm_info, num_threads);
     ARM_COMPUTE_ERROR_ON(_transform_a == nullptr);
     ARM_COMPUTE_ERROR_ON(_matrix_multiply == nullptr);
     _transformed_a.allocator()->allocate();
     _tmp_c.allocator()->allocate();
     if(!_pretranspose_b)
     {
         _transformed_b.allocator()->allocate();
     }
 }
References TensorAllocator::allocate(), Tensor::allocator(), arm_compute::test::validation::alpha, ARM_COMPUTE_ERROR, ARM_COMPUTE_ERROR_ON, arm_compute::auto_init_if_empty(), arm_compute::test::validation::b, arm_compute::ceil_to_multiple(), ICloneable< T >::clone(), IScheduler::cpu_info(), ITensorInfo::data_type(), Window::DimX, Window::DimY, Window::DimZ, Scheduler::get(), iceildiv(), ITensor::info(), Tensor::info(), TensorAllocator::init(), MemoryGroupBase< TensorType >::manage(), Window::num_iterations_total(), IScheduler::num_threads(), GEMMInfo::pretranpose_B(), and Window::set().
operator=()
NEGEMMInterleavedWrapper& operator= (const NEGEMMInterleavedWrapper &) delete
prepare()
void prepare () override virtual
Prepare the function for executing.
Any one off pre-processing step required by the function is handled here
Note
Prepare stage might not need all the function's buffers' backing memory to be available in order to execute
Reimplemented from IFunction.
Definition at line 196 of file NEGEMMInterleavedWrapper.cpp.
 {
     if(!_is_prepared)
     {
         if(_pretranspose_b)
         {
             _transformed_b.allocator()->allocate();
             NEScheduler::get().schedule(_prepare_b.get(), Window::DimX);
             _b->mark_as_unused();
         }
         else
         {
             _prepare_b->create_workloads(_b_workloads);
         }
         _transform_a->create_workloads(_a_workloads);
         _matrix_multiply->create_workloads(_mm_workloads);
         //Maximum number of workloads to create:
         const unsigned int num_threads    = NEScheduler::get().num_threads();
         const unsigned int max_iterations = std::max(num_threads, _num_windows);
         //Maximum number of iterations the parameters allow:
         const unsigned int num_iterations = _batch_window.num_iterations_total();
         // Keep the smallest of the two:
         const unsigned int num_windows  = std::min(num_iterations, max_iterations);
         const TensorShape  window_shape = _batch_window.shape();
         const unsigned int num_x_blocks = _block_walker.num_iterations(Window::DimX);
         // Create a 1D window to dynamically split the batch window:
         Window win_1D;
         win_1D.set(0, Window::Dimension(0, num_iterations));
         // Create one workload for each sub-window:
         for(unsigned int w = 0; w < num_windows; w++)
         {
             Window            win          = win_1D.split_window(0, w, num_windows);
             const Coordinates start_offset = index2coords(window_shape, win.x().start());
             const Coordinates end_offset   = index2coords(window_shape, win.x().end() - 1);
             if(_pretranspose_b)
             {
                 auto workload = [start_offset, end_offset, num_x_blocks, this](const ThreadInfo & info)
                 {
                     //For each block of rows in "M"
                     auto workload_mm = this->_mm_workloads.begin();
                     for(auto &workload_a : this->_a_workloads)
                     {
                         // Transform one k_block from A:
                         this->_transform_a->transform(workload_a, info, this->_batch_window, start_offset, end_offset);
                         // Then perform the matrix multiplication for each x block along N:
                         for(unsigned int i = 0; i < num_x_blocks; i++)
{
                             ARM_COMPUTE_ERROR_ON(workload_mm == this->_mm_workloads.end());
                             this->_matrix_multiply->transform(*workload_mm++, info, this->_batch_window, start_offset, end_offset);
                         }
                     }
                 };
                 _workloads.emplace_back(workload);
             }
             else
             {
                 auto workload = [num_threads, start_offset, end_offset, num_x_blocks, this](const ThreadInfo & info)
                 {
                     //For each block of rows in "M"
                     auto         workload_mm = this->_mm_workloads.begin();
                     unsigned int workload_b  = 0;
                     //If there is only one thread then only reshape the B blocks as you need them:
                     unsigned int workload_b_next = num_threads == 1 ? this->_b_workloads.size() : 1;
                     for(auto &workload_a : this->_a_workloads)
                     {
                         // Transform one k_block from A:
                         this->_transform_a->transform(workload_a, info, this->_batch_window, start_offset, end_offset);
                         // Then perform the matrix multiplication for each x block along N:
                         for(unsigned int i = 0; i < num_x_blocks; i++)
{
                             ARM_COMPUTE_ERROR_ON(workload_mm == this->_mm_workloads.end());
                             if(workload_b_next < this->_b_workloads.size())
{
                                 //Lock on BufferManager: need to run it ?
                                 if(this->_buffer_manager->lock_to_reshape_if_needed(workload_b_next))
{
                                     this->_prepare_b->transform(this->_b_workloads[workload_b_next], info);
                                     this->_buffer_manager->mark_as_reshaped(workload_b_next);
                                 }
                                 workload_b_next++;
                             }
                             ARM_COMPUTE_ERROR_ON(workload_b >= this->_b_workloads.size());
                             // Run if needed or wait
                             if(this->_buffer_manager->lock_to_reshape_if_needed(workload_b))
{
                                 this->_prepare_b->transform(this->_b_workloads[workload_b], info);
                                 this->_buffer_manager->mark_as_reshaped(workload_b);
                             }
                             this->_buffer_manager->wait_for_reshaping(workload_b);
                             this->_matrix_multiply->transform(*workload_mm++, info, this->_batch_window, start_offset, end_offset);
                             this->_buffer_manager->mark_as_unused(workload_b);
                             workload_b++;
                         }
                     }
                 };
                 _workloads.emplace_back(workload);
             }
         }
         if(!_pretranspose_b && num_windows > 1 && num_windows % num_threads != 0)
         {
             //Make sure the number of workloads is a multiple of the number of threads to avoid dead locks:
             for(unsigned int leftover = num_windows % num_threads; leftover != num_threads; leftover++)
             {
                 auto workload = [this](const ThreadInfo & info)
                 {
                     unsigned int workload_b = 0;
                     //If there is only one thread then only reshape the B blocks as you need them:
                     unsigned int workload_b_next = 1;
                     for(unsigned int iteration = 0; iteration < this->_mm_workloads.size(); iteration++)
                     {
                         if(workload_b_next < this->_b_workloads.size())
{
                             //Lock on BufferManager: need to run it ?
                             if(this->_buffer_manager->lock_to_reshape_if_needed(workload_b_next))
{
                                 this->_prepare_b->transform(this->_b_workloads[workload_b_next], info);
                                 this->_buffer_manager->mark_as_reshaped(workload_b_next);
                             }
                             workload_b_next++;
                         }
                         ARM_COMPUTE_ERROR_ON(workload_b >= this->_b_workloads.size());
                         // Run if needed or wait
                         if(this->_buffer_manager->lock_to_reshape_if_needed(workload_b))
{
                             this->_prepare_b->transform(this->_b_workloads[workload_b], info);
                             this->_buffer_manager->mark_as_reshaped(workload_b);
                         }
                         this->_buffer_manager->wait_for_reshaping(workload_b);
                         this->_buffer_manager->mark_as_unused(workload_b);
                         workload_b++;
                     }
                 };
                 _workloads.emplace_back(workload);
             }
         }
         _is_prepared = true;
     }
 }
References TensorAllocator::allocate(), Tensor::allocator(), ARM_COMPUTE_ERROR_ON, Window::DimX, Window::Dimension::end(), Scheduler::get(), arm_compute::index2coords(), arm_compute::test::validation::info, ITensor::mark_as_unused(), Window::num_iterations(), Window::num_iterations_total(), IScheduler::num_threads(), IScheduler::schedule(), Window::set(), Window::shape(), Window::split_window(), Window::Dimension::start(), arm_compute::test::validation::w, and Window::x().
Referenced by NEGEMMInterleavedWrapper::run().
run()
void run () override virtual
Run the kernels contained in the function.
For NEON kernels:
Multi-threading is used for the kernels which are parallelisable.
By default std::thread::hardware_concurrency() threads are used.
Note
CPPScheduler::set_num_threads() can be used to manually set the number of threads
For OpenCL kernels:
All the kernels are enqueued on the queue associated with CLScheduler.
The queue is then flushed.
Note
The function will not block until the kernels are executed. It is the user's responsibility to wait.
Will call prepare() on first run if hasn't been done
Implements IFunction.
Definition at line 188 of file NEGEMMInterleavedWrapper.cpp.
 {
     prepare();
     MemoryGroupResourceScope scope_mg(_memory_group);
     NEScheduler::get().run_tagged_workloads(_workloads, _tag.c_str());
 }
References Scheduler::get(), NEGEMMInterleavedWrapper::prepare(), and IScheduler::run_tagged_workloads().
The documentation for this class was generated from the following files:
arm_compute/runtime/NEON/functions/assembly/NEGEMMInterleavedWrapper.h
src/runtime/NEON/functions/assembly/NEGEMMInterleavedWrapper.cpp