Compute Library: PrettyPrinter Class Reference
PrettyPrinter Class Reference
Implementation of a Printer that produces human readable output.
#include <PrettyPrinter.h>
Public Member Functions
void set_color_output (bool color_output)
Set if the output is colored.
void print_entry (const std::string &name, const std::string &value) override
Print an entry consisting of a (name, value) pair.
void print_global_header () override
Print global header.
void print_global_footer () override
Print global footer.
void print_run_header () override
Print header before running all tests.
void print_run_footer () override
Print footer after running all tests.
void print_test_header (const TestInfo &info) override
Print header before a test.
void print_test_footer () override
Print footer after a test.
void print_errors_header () override
Print header before errors.
void print_errors_footer () override
Print footer after errors.
void print_error (const std::exception &error, bool expected) override
Print test error.
void print_info (const std::string &info) override
Print test log info.
void print_measurements (const Profiler::MeasurementsMap &measurements) override
Print measurements for a test.
void print_list_tests (const std::vector< TestInfo > &infos) override
Print the list of all the tests.
Public Member Functions inherited from Printer
Printer ()=default
Default constructor.
Printer (std::ostream &stream)
Construct printer with given output stream.
Printer (const Printer &)=delete
Printer & operator= (const Printer &)=delete
Printer (Printer &&)=default
Printer & operator= (Printer &&)=default
virtual ~Printer ()=default
void print (const std::string &str)
Print given string.
void set_stream (std::ostream &stream)
Set the output stream.
Detailed Description
Implementation of a Printer that produces human readable output.
Definition at line 36 of file PrettyPrinter.h.
Member Function Documentation
void print_entry (const std::string & name, const std::string & value) override virtual
Print an entry consisting of a (name, value) pair.
Parameters
[in] name Description of the value.
[in] value Value.
Implements Printer.
Definition at line 62 of file PrettyPrinter.cpp.
 {
     *_stream << begin_color("4") << name << " = " << value << end_color() << "\n";
 }
void print_error (const std::exception & error, bool expected) override virtual
Print test error.
Parameters
[in] error Description of the error.
[in] expected Whether the error was expected or not.
Implements Printer.
Definition at line 105 of file PrettyPrinter.cpp.
 {
     std::string prefix = expected ? "EXPECTED ERROR: " : "ERROR: ";
     *_stream << begin_color("1") << prefix << error.what() << end_color() << "\n";
 }
void print_errors_footer () override virtual
Print footer after errors.
Implements Printer.
Definition at line 96 of file PrettyPrinter.cpp.
 {
 }
void print_errors_header () override virtual
Print header before errors.
Implements Printer.
Definition at line 92 of file PrettyPrinter.cpp.
 {
 }
void print_global_footer () override virtual
Print global footer.
Implements Printer.
Definition at line 71 of file PrettyPrinter.cpp.
 {
 }
void print_global_header () override virtual
Print global header.
Implements Printer.
Definition at line 67 of file PrettyPrinter.cpp.
 {
 }
void print_info (const std::string & info) override virtual
Print test log info.
Parameters
[in] info Description of the log.
Implements Printer.
Definition at line 100 of file PrettyPrinter.cpp.
 {
     *_stream << begin_color("1") << "INFO: " << info << end_color() << "\n";
 }
void print_list_tests (const std::vector< TestInfo > & infos) override virtual
Print the list of all the tests.
Parameters
[in] infos List of tests to print
Implements Printer.
Definition at line 111 of file PrettyPrinter.cpp.
References arm_compute::test::validation::info().
 {
     for(auto info : infos)
     {
         *_stream << "[" << info.id << ", " << info.mode << ", " << info.status << "] " << info.name << "\n";
     }
 }
void print_measurements (const Profiler::MeasurementsMap & measurements) override virtual
Print measurements for a test.
Parameters
[in] measurements Measurements as collected by a Profiler.
Implements Printer.
Definition at line 118 of file PrettyPrinter.cpp.
References arm_compute::test::validation::a, accumulate(), arm_compute::test::arithmetic_to_string(), arm_compute::test::validation::b, Measurement::Value::relative_standard_deviation(), and Measurement::value().
 {
     for(const auto &instrument : measurements)
     {
         *_stream << begin_color("3") << "  " << instrument.first << ":";
         auto add_measurements = [](Measurement::Value a, const Measurement & b)
         {
             return a + b.value();
         };
         auto cmp_measurements = [](const Measurement & a, const Measurement & b)
         {
             return a.value() < b.value();
         };
         int                num_values    = instrument.second.size();
         const auto         minmax_values = std::minmax_element(instrument.second.begin(), instrument.second.end(), cmp_measurements);
         Measurement::Value sum_values    = std::accumulate(instrument.second.begin(), instrument.second.end(), Measurement::Value(minmax_values.first->value().is_floating_point), add_measurements);
         // Calculate the median value
         auto measurements = instrument.second;
         std::nth_element(measurements.begin(), measurements.begin() + (num_values / 2), measurements.end(), cmp_measurements);
         const auto median_value = measurements[num_values / 2];
         // Calculate the relative standard deviation
         auto                            mean_value = sum_values / num_values;
         std::vector<Measurement::Value> diff(measurements.size(), minmax_values.first->value().is_floating_point);
         std::transform(measurements.begin(), measurements.end(), diff.begin(), [mean_value](const Measurement & x)
         {
             return x.value() - mean_value;
         });
         auto sq_sum   = std::inner_product(diff.begin(), diff.end(), diff.begin(), Measurement::Value(minmax_values.first->value().is_floating_point));
         auto variance = sq_sum / measurements.size();
         auto rsd      = Measurement::Value::relative_standard_deviation(variance, mean_value);
         if(num_values > 2)
         {
             sum_values -= minmax_values.first->value() + minmax_values.second->value();
             num_values -= 2;
         }
         *_stream << "    ";
         *_stream << "MEDIAN=" << median_value.value() << " " << median_value.unit() << ", ";
         *_stream << "AVG=" << (sum_values / num_values) << " " << minmax_values.second->unit() << ", ";
         *_stream << "STDDEV=" << arithmetic_to_string(rsd, 2) << " %, ";
         if(num_values > 1)
         {
             *_stream << "MIN=" << *minmax_values.first << ", ";
             *_stream << "MAX=" << *minmax_values.second;
         }
         *_stream << end_color() << "\n";
     }
 }
void print_run_footer () override virtual
Print footer after running all tests.
Implements Printer.
Definition at line 79 of file PrettyPrinter.cpp.
 {
 }
void print_run_header () override virtual
Print header before running all tests.
Implements Printer.
Definition at line 75 of file PrettyPrinter.cpp.
 {
 }
void print_test_footer () override virtual
Print footer after a test.
Implements Printer.
Definition at line 88 of file PrettyPrinter.cpp.
 {
 }
void print_test_header (const TestInfo & info) override virtual
Print header before a test.
Parameters
[in] info Test info.
Implements Printer.
Definition at line 83 of file PrettyPrinter.cpp.
References TestInfo::id, and TestInfo::name.
 {
     *_stream << begin_color("2") << "Running [" << info.id << "] '" << info.name << "'" << end_color() << "\n";
 }
void set_color_output (bool color_output)
Set if the output is colored.
Parameters
[in] color_output True if the output is colored.
Definition at line 57 of file PrettyPrinter.cpp.
 {
     _color_output = color_output;
 }
The documentation for this class was generated from the following files:
tests/framework/printers/PrettyPrinter.h
tests/framework/printers/PrettyPrinter.cpp