Compute Library: CLEdgeTraceKernel Class Reference
CLEdgeTraceKernel Class Reference
OpenCL kernel to perform Edge tracing.
#include <CLCannyEdgeKernel.h>
Public Member Functions
CLEdgeTraceKernel ()
Constructor.
CLEdgeTraceKernel (const CLEdgeTraceKernel &)=delete
Prevent instances of this class from being copied (As this class contains pointers)
CLEdgeTraceKernel & operator= (const CLEdgeTraceKernel &)=delete
Prevent instances of this class from being copied (As this class contains pointers)
void configure (const ICLTensor *input, ICLTensor *output, int32_t upper_thr, int32_t lower_thr, ICLTensor *visited, ICLTensor *recorded, ICLTensor *l1_stack, ICLTensor *l1_stack_counter)
Initialise the kernel's source, destination and border mode.
void run (const Window &window, cl::CommandQueue &queue) override
Enqueue the OpenCL kernel to process the given window on the passed OpenCL command queue.
Public Member Functions inherited from ICLKernel
ICLKernel ()
Constructor.
cl::Kernel & kernel ()
Returns a reference to the OpenCL kernel of this object.
template<typename T >
void add_1D_array_argument (unsigned int &idx, const ICLArray< T > *array, const Strides &strides, unsigned int num_dimensions, const Window &window)
Add the passed 1D array's parameters to the object's kernel's arguments starting from the index idx.
void add_1D_tensor_argument (unsigned int &idx, const ICLTensor *tensor, const Window &window)
Add the passed 1D tensor's parameters to the object's kernel's arguments starting from the index idx.
void add_1D_tensor_argument_if (bool cond, unsigned int &idx, const ICLTensor *tensor, const Window &window)
Add the passed 1D tensor's parameters to the object's kernel's arguments starting from the index idx if the condition is true.
void add_2D_tensor_argument (unsigned int &idx, const ICLTensor *tensor, const Window &window)
Add the passed 2D tensor's parameters to the object's kernel's arguments starting from the index idx.
void add_2D_tensor_argument_if (bool cond, unsigned int &idx, const ICLTensor *tensor, const Window &window)
Add the passed 2D tensor's parameters to the object's kernel's arguments starting from the index idx if the condition is true.
void add_3D_tensor_argument (unsigned int &idx, const ICLTensor *tensor, const Window &window)
Add the passed 3D tensor's parameters to the object's kernel's arguments starting from the index idx.
void add_4D_tensor_argument (unsigned int &idx, const ICLTensor *tensor, const Window &window)
Add the passed 4D tensor's parameters to the object's kernel's arguments starting from the index idx.
template<typename T >
void add_argument (unsigned int &idx, T value)
Add the passed parameters to the object's kernel's arguments starting from the index idx.
void set_lws_hint (const cl::NDRange &lws_hint)
Set the Local-Workgroup-Size hint.
cl::NDRange lws_hint () const
Return the Local-Workgroup-Size hint.
const std::string & config_id () const
Get the configuration ID.
void set_target (GPUTarget target)
Set the targeted GPU architecture.
void set_target (cl::Device &device)
Set the targeted GPU architecture according to the CL device.
GPUTarget get_target () const
Get the targeted GPU architecture.
size_t get_max_workgroup_size ()
Get the maximum workgroup size for the device the CLKernelLibrary uses.
template<typename T , unsigned int dimension_size>
void add_array_argument (unsigned &idx, const ICLArray< T > *array, const Strides &strides, unsigned int num_dimensions, const Window &window)
Add the passed array's parameters to the object's kernel's arguments starting from the index idx.
template<unsigned int dimension_size>
void add_tensor_argument (unsigned &idx, const ICLTensor *tensor, const Window &window)
Public Member Functions inherited from IKernel
IKernel ()
Constructor.
virtual ~IKernel ()=default
Destructor.
virtual bool is_parallelisable () const
Indicates whether or not the kernel is parallelisable.
virtual BorderSize border_size () const
The size of the border for that kernel.
const Window & window () const
The maximum window the kernel can be executed on.
Additional Inherited Members
Static Public Member Functions inherited from ICLKernel
static constexpr unsigned int num_arguments_per_1D_array ()
Returns the number of arguments enqueued per 1D array object.
static constexpr unsigned int num_arguments_per_1D_tensor ()
Returns the number of arguments enqueued per 1D tensor object.
static constexpr unsigned int num_arguments_per_2D_tensor ()
Returns the number of arguments enqueued per 2D tensor object.
static constexpr unsigned int num_arguments_per_3D_tensor ()
Returns the number of arguments enqueued per 3D tensor object.
static constexpr unsigned int num_arguments_per_4D_tensor ()
Returns the number of arguments enqueued per 4D tensor object.
static cl::NDRange gws_from_window (const Window &window)
Get the global work size given an execution window.
Detailed Description
OpenCL kernel to perform Edge tracing.
Definition at line 106 of file CLCannyEdgeKernel.h.
Constructor & Destructor Documentation
CLEdgeTraceKernel() [1/2]
CLEdgeTraceKernel ()
Constructor.
Definition at line 189 of file CLCannyEdgeKernel.cpp.
     : _input(nullptr), _output(nullptr), _lower_thr(0), _upper_thr(0), _visited(nullptr), _recorded(nullptr), _l1_stack(nullptr), _l1_stack_counter(nullptr)
 {
 }
CLEdgeTraceKernel() [2/2]
CLEdgeTraceKernel (const CLEdgeTraceKernel &) delete
Prevent instances of this class from being copied (As this class contains pointers)
Member Function Documentation
configure()
void configure (const ICLTensor * input, ICLTensor * output, int32_t upper_thr, int32_t lower_thr, ICLTensor * visited, ICLTensor * recorded, ICLTensor * l1_stack, ICLTensor * l1_stack_counter)
Initialise the kernel's source, destination and border mode.
Parameters
[in] input Source tensor. Data types supported: U8.
[out] output Destination tensor. Data types supported: U8.
[in] upper_thr Upper threshold used for the hysteresis
[in] lower_thr Lower threshold used for the hysteresis
[in,out] visited Tensor for keeping the visited pixels. Data types supported: U32. Expected to be initialized to 0 before each run.
[in,out] recorded Tensor for keeping the recorded pixels. Data types supported: U32 Expected to be initialized to 0 before each run.
[in,out] l1_stack Tensor with the L1 stack for each pixel. Data types supported: S32. Expected to be initialized to 0 before each run.
[in,out] l1_stack_counter Tensor for counting the elements in the L1 stack of each pixel. Data types supported: U8. Expected to be initialized to 0 before each run.
Definition at line 194 of file CLCannyEdgeKernel.cpp.
 {
     ARM_COMPUTE_ERROR_ON_DATA_TYPE_CHANNEL_NOT_IN(input, 1, DataType::U16, DataType::U32);
     ARM_COMPUTE_ERROR_ON_DATA_TYPE_CHANNEL_NOT_IN(output, 1, DataType::U8);
     ARM_COMPUTE_ERROR_ON_DATA_TYPE_CHANNEL_NOT_IN(visited, 1, DataType::U32);
     ARM_COMPUTE_ERROR_ON_DATA_TYPE_CHANNEL_NOT_IN(recorded, 1, DataType::U32);
     ARM_COMPUTE_ERROR_ON_DATA_TYPE_CHANNEL_NOT_IN(l1_stack, 1, DataType::S32);
     ARM_COMPUTE_ERROR_ON_DATA_TYPE_CHANNEL_NOT_IN(l1_stack_counter, 1, DataType::U8);
     _input            = input;
     _output           = output;
     _lower_thr        = lower_thr;
     _upper_thr        = upper_thr;
     _visited          = visited;
     _recorded         = recorded;
     _l1_stack         = l1_stack;
     _l1_stack_counter = l1_stack_counter;
     // Create build opts
     std::set<std::string> built_opts;
     built_opts.emplace("-DDATA_TYPE_IN=" + get_cl_type_from_data_type(input->info()->data_type()));
     built_opts.emplace("-DDATA_TYPE_OUT=" + get_cl_type_from_data_type(output->info()->data_type()));
     // Create kernel
     const std::string kernel_name = std::string("hysteresis");
     _kernel                       = static_cast<cl::Kernel>(CLKernelLibrary::get().create_kernel(kernel_name, built_opts));
     // Set constant kernel args
     unsigned int width  = _input->info()->dimension(0);
     unsigned int height = _input->info()->dimension(1);
     unsigned int idx    = 6 * num_arguments_per_2D_tensor(); //Skip the input and output parameters
     _kernel.setArg(idx++, static_cast<cl_uint>(_lower_thr));
     _kernel.setArg(idx++, static_cast<cl_uint>(_upper_thr));
     _kernel.setArg(idx++, static_cast<cl_uint>(width));
     _kernel.setArg(idx++, static_cast<cl_uint>(height));
     // Configure kernel window
     constexpr unsigned int num_elems_processed_per_iteration = 1;
     Window                 win                               = calculate_max_window(*_input->info(), Steps(num_elems_processed_per_iteration));
     AccessWindowHorizontal output_access(_output->info(), 0, num_elems_processed_per_iteration);
     AccessWindowHorizontal visited_access(_visited->info(), 0, num_elems_processed_per_iteration);
     AccessWindowHorizontal recorded_access(_recorded->info(), 0, num_elems_processed_per_iteration);
     AccessWindowHorizontal l1_stack_access(_l1_stack->info(), 0, num_elems_processed_per_iteration);
     AccessWindowHorizontal l1_stack_counter_access(_l1_stack_counter->info(), 0, num_elems_processed_per_iteration);
     update_window_and_padding(win,
                               AccessWindowHorizontal(_input->info(), 0, num_elems_processed_per_iteration),
                               output_access,
                               visited_access,
                               recorded_access,
                               l1_stack_access,
                               l1_stack_counter_access);
     output_access.set_valid_region(win, _input->info()->valid_region());
     visited_access.set_valid_region(win, _input->info()->valid_region());
     recorded_access.set_valid_region(win, _input->info()->valid_region());
     l1_stack_access.set_valid_region(win, _input->info()->valid_region());
     l1_stack_counter_access.set_valid_region(win, _input->info()->valid_region());
     ICLKernel::configure_internal(win);
     // Set config_id for enabling LWS tuning
     _config_id = kernel_name;
     _config_id += "_";
     _config_id += lower_string(string_from_data_type(input->info()->data_type()));
     _config_id += "_";
     _config_id += support::cpp11::to_string(input->info()->dimension(0));
     _config_id += "_";
     _config_id += support::cpp11::to_string(input->info()->dimension(1));
     _config_id += "_";
     _config_id += lower_string(string_from_format(output->info()->format()));
     _config_id += "_";
     _config_id += support::cpp11::to_string(output->info()->dimension(0));
     _config_id += "_";
     _config_id += support::cpp11::to_string(output->info()->dimension(1));
 }
References ARM_COMPUTE_ERROR_ON_DATA_TYPE_CHANNEL_NOT_IN, arm_compute::calculate_max_window(), arm_compute::create_kernel(), ITensorInfo::data_type(), ITensorInfo::dimension(), ITensorInfo::format(), CLKernelLibrary::get(), arm_compute::get_cl_type_from_data_type(), ITensor::info(), arm_compute::lower_string(), ICLKernel::num_arguments_per_2D_tensor(), arm_compute::S32, arm_compute::string_from_data_type(), arm_compute::string_from_format(), arm_compute::support::cpp11::to_string(), arm_compute::U16, arm_compute::U32, arm_compute::U8, arm_compute::update_window_and_padding(), and ITensorInfo::valid_region().
Referenced by CLCannyEdge::configure().
operator=()
CLEdgeTraceKernel& operator= (const CLEdgeTraceKernel &) delete
Prevent instances of this class from being copied (As this class contains pointers)
run()
void run (const Window & window, cl::CommandQueue & queue) override virtual
Enqueue the OpenCL kernel to process the given window on the passed OpenCL command queue.
Note
The queue is not flushed by this method, and therefore the kernel will not have been executed by the time this method returns.
Parameters
[in] window Region on which to execute the kernel. (Must be a valid region of the window returned by window()).
[in,out] queue Command queue on which to enqueue the kernel.
Implements ICLKernel.
Definition at line 273 of file CLCannyEdgeKernel.cpp.
 {
     ARM_COMPUTE_ERROR_ON_UNCONFIGURED_KERNEL(this);
     ARM_COMPUTE_ERROR_ON_INVALID_SUBWINDOW(IKernel::window(), window);
     Window slice = window.first_slice_window_2D();
     do
     {
         unsigned int idx = 0;
         add_2D_tensor_argument(idx, _input, slice);
         add_2D_tensor_argument(idx, _output, slice);
         add_2D_tensor_argument(idx, _visited, slice);
         add_2D_tensor_argument(idx, _recorded, slice);
         add_2D_tensor_argument(idx, _l1_stack, slice);
         add_2D_tensor_argument(idx, _l1_stack_counter, slice);
         enqueue(queue, *this, slice, lws_hint());
     }
     while(window.slide_window_slice_2D(slice));
 }
References ICLKernel::add_2D_tensor_argument(), ARM_COMPUTE_ERROR_ON_INVALID_SUBWINDOW, ARM_COMPUTE_ERROR_ON_UNCONFIGURED_KERNEL, arm_compute::enqueue(), Window::first_slice_window_2D(), ICLKernel::lws_hint(), arm_compute::test::validation::reference::slice(), Window::slide_window_slice_2D(), and IKernel::window().
The documentation for this class was generated from the following files:
arm_compute/core/CL/kernels/CLCannyEdgeKernel.h
src/core/CL/kernels/CLCannyEdgeKernel.cpp