Compute Library: NEDepthwiseSeparableConvolutionLayer Class Reference
NEDepthwiseSeparableConvolutionLayer Class Reference
Basic function to execute depthwise convolution.
#include <NEDepthwiseSeparableConvolutionLayer.h>
Public Member Functions
NEDepthwiseSeparableConvolutionLayer ()
Default constructor.
void configure (ITensor *input, const ITensor *depthwise_weights, const ITensor *depthwise_biases, ITensor *depthwise_out, const ITensor *pointwise_weights, const ITensor *pointwise_biases, ITensor *output, const PadStrideInfo &depthwise_conv_info, const PadStrideInfo &pointwise_conv_info)
Set the input and output tensors.
void run () override
Run the kernels contained in the function.
void prepare () override
Prepare the function for executing.
Public Member Functions inherited from IFunction
virtual ~IFunction ()=default
Destructor.
Detailed Description
Basic function to execute depthwise convolution.
This function calls the following NEON kernels and function:
NEDepthwiseConvolutionLayer
NEDirectConvolutionLayer
Definition at line 45 of file NEDepthwiseSeparableConvolutionLayer.h.
Constructor & Destructor Documentation
NEDepthwiseSeparableConvolutionLayer()
NEDepthwiseSeparableConvolutionLayer ()
Default constructor.
Definition at line 33 of file NEDepthwiseSeparableConvolutionLayer.cpp.
     : _depthwise_conv(), _pointwise_conv()
 {
 }
Member Function Documentation
configure()
void configure (ITensor * input, const ITensor * depthwise_weights, const ITensor * depthwise_biases, ITensor * depthwise_out, const ITensor * pointwise_weights, const ITensor * pointwise_biases, ITensor * output, const PadStrideInfo & depthwise_conv_info, const PadStrideInfo & pointwise_conv_info)
Set the input and output tensors.
Parameters
[in] input Source tensor. 3 lower dimensions represent a single input [width, height, IFM], while every optional dimension from 4 and above represent a batch of inputs. Data types supported: F32.
[in] depthwise_weights Depthwise convolution weights tensor. These are 3D tensors with dimensions [kernel_x, kernel_y, IFM]. Data type supported: Same as input.
[in] depthwise_biases (Optional) Biases tensor.Biases are 1D tensor with dimensions [IFM]. Must be nullptr if not needed. Data type supported: Same as weights.
[out] depthwise_out Depthwise destination tensor.
[in] pointwise_weights Pointwise convolution weights tensor. These are 4D tensors with dimensions [1, 1, IFM, OFM]. Data type supported: Same as input.
[in] pointwise_biases (Optional) Biases tensor. Biases are 1D tensor with dimensions [OFM]. Must be nullptr if not needed. Data type supported: Same as weights.
[out] output Destination tensor. 3 lower dimensions represent a single output [width, height, OFM], while the rest represent batch of outputs. Data types supported: Same as input.
[in] depthwise_conv_info Contains padding and stride information described in PadStrideInfo for depthwise convolution.
[in] pointwise_conv_info Contains padding and stride information described in PadStrideInfo for pointwise convolution.
Definition at line 38 of file NEDepthwiseSeparableConvolutionLayer.cpp.
 {
     _depthwise_conv.configure(input, depthwise_weights, depthwise_biases, depthwise_out, depthwise_conv_info);
     _pointwise_conv.configure(depthwise_out, pointwise_weights, pointwise_biases, output, pointwise_conv_info);
 }
References NEDirectConvolutionLayer::configure(), and NEDepthwiseConvolutionLayer::configure().
prepare()
void prepare () override virtual
Prepare the function for executing.
Any one off pre-processing step required by the function is handled here
Note
Prepare stage might not need all the function's buffers' backing memory to be available in order to execute
Reimplemented from IFunction.
Definition at line 54 of file NEDepthwiseSeparableConvolutionLayer.cpp.
 {
     _depthwise_conv.prepare();
     _pointwise_conv.prepare();
 }
References IFunction::prepare(), and NEDepthwiseConvolutionLayer::prepare().
Referenced by NEDepthwiseSeparableConvolutionLayer::run().
run()
void run () override virtual
Run the kernels contained in the function.
For NEON kernels:
Multi-threading is used for the kernels which are parallelisable.
By default std::thread::hardware_concurrency() threads are used.
Note
CPPScheduler::set_num_threads() can be used to manually set the number of threads
For OpenCL kernels:
All the kernels are enqueued on the queue associated with CLScheduler.
The queue is then flushed.
Note
The function will not block until the kernels are executed. It is the user's responsibility to wait.
Will call prepare() on first run if hasn't been done
Implements IFunction.
Definition at line 46 of file NEDepthwiseSeparableConvolutionLayer.cpp.
 {
     prepare();
     _depthwise_conv.run();
     _pointwise_conv.run();
 }
References NEDepthwiseSeparableConvolutionLayer::prepare(), NEDirectConvolutionLayer::run(), and NEDepthwiseConvolutionLayer::run().
The documentation for this class was generated from the following files:
arm_compute/runtime/NEON/functions/NEDepthwiseSeparableConvolutionLayer.h
src/runtime/NEON/functions/NEDepthwiseSeparableConvolutionLayer.cpp