Compute Library: GroupedConvolutionMutator Class Reference
GroupedConvolutionMutator Class Reference final
Mutation pass to implement/optimize grouped convolutions.
#include <GroupedConvolutionMutator.h>
Public Member Functions
virtual void mutate (Graph &g) override
Walk the graph and perform a specific mutation.
const char * name () override
Returns mutator name.
Public Member Functions inherited from IGraphMutator
virtual ~IGraphMutator ()=default
Virtual Destructor.
Detailed Description
Mutation pass to implement/optimize grouped convolutions.
Warning
This is compulsory to run in case of grouped convolutions
Definition at line 37 of file GroupedConvolutionMutator.h.
Member Function Documentation
mutate()
void mutate (Graph & g) override virtual
Walk the graph and perform a specific mutation.
Parameters
[in,out] g Graph to walk and mutate
Implements IGraphMutator.
Definition at line 106 of file GroupedConvolutionMutator.cpp.
 {
     // Early exit if no Convolution layers exist in graph
     if(g.nodes(NodeType::ConvolutionLayer).empty())
     {
         return;
     }
     // Total nodes
     size_t total_nodes = g.nodes().size();
     // Iterate over convolution nodes
     for(unsigned int i = 0; i < total_nodes; ++i)
     {
         INode *node = g.node(i);
         if(node != nullptr && node->type() == NodeType::ConvolutionLayer && arm_compute::utils::cast::polymorphic_downcast<ConvolutionLayerNode *>(node)->num_groups() != 1)
         {
             // Validate node
             backends::IDeviceBackend &backend = backends::BackendRegistry::get().get_backend(node->assigned_target());
             Status                    status  = backend.validate_node(*node);
             // If grouped convolution is not supported
             if(!bool(status))
             {
                 // Down-cast node
                 auto *conv_node = arm_compute::utils::cast::polymorphic_downcast<ConvolutionLayerNode *>(node);
                 // Get internal convolution info
                 // TODO (geopin01) : Create a descriptor or a clone interface
                 const PadStrideInfo       conv_info       = conv_node->convolution_info();
                 const ConvolutionMethod   conv_method     = conv_node->convolution_method();
                 const ActivationLayerInfo fused_act_info  = conv_node->fused_activation();
                 const FastMathHint        fast_math_hint  = conv_node->fast_math_hint();
                 const unsigned int        num_groups      = conv_node->num_groups();
                 const NodeParams          params          = conv_node->common_node_params();
                 const Target              assigned_target = conv_node->assigned_target();
                 // Extract node ids
                 ARM_COMPUTE_ERROR_ON(conv_node->input_edge(0) == nullptr || conv_node->input_edge(1) == nullptr);
                 const NodeID input_id   = conv_node->input_edge(0)->producer()->id();
                 const NodeID weights_id = conv_node->input_edge(1)->producer()->id();
                 const NodeID bias_id    = (conv_node->input_edge(2) != nullptr) ? conv_node->input_edge(2)->producer()->id() : EmptyNodeID;
                 // Get driving nodes
                 std::vector<NodeIdxPair> driving_nodes = get_driving_nodes(*node);
                 // Extract activation node accessor if any
                 auto node_accessor = conv_node->output(0)->extract_accessor();
                 // Current max tensor and node id
                 TensorID latest_tid = g.tensors().size();
                 NodeID   latest_nid = g.nodes().size();
                 // Create grouped convolution node
                 NodeID grouped_conv_id = create_grouped_convolution(g, params, { input_id, 0 }, weights_id, bias_id,
                                                                     conv_info, conv_method, fused_act_info, fast_math_hint, num_groups);
                 // Remove convolution node
                 g.remove_node(node->id());
                 // Update batch normalization node outputs
                 for(auto &driving_node : driving_nodes)
                 {
                     g.add_connection(grouped_conv_id, 0, driving_node.node_id, driving_node.index);
                 }
                 // Update accessor to batch normalization node
                 g.node(grouped_conv_id)->output(0)->set_accessor(std::move(node_accessor));
                 // Configure new tensors and nodes
                 std::for_each(g.tensors().begin() + latest_tid, g.tensors().end(), [](std::unique_ptr<Tensor> &t)
                 {
                     configure_tensor(t.get());
                 });
                 std::for_each(g.nodes().begin() + latest_nid, g.nodes().end(), [&assigned_target](std::unique_ptr<INode> &n)
                 {
                     if(n != nullptr)
                     {
                         n->set_assigned_target(assigned_target);
                     }
                 });
             }
         }
     }
 }
References Graph::add_connection(), ARM_COMPUTE_ERROR_ON, INode::assigned_target(), arm_compute::graph::configure_tensor(), arm_compute::test::validation::conv_info, arm_compute::graph::ConvolutionLayer, arm_compute::graph::EmptyNodeID, arm_compute::utility::for_each(), BackendRegistry::get(), BackendRegistry::get_backend(), arm_compute::graph::get_driving_nodes(), INode::id(), Graph::node(), Graph::nodes(), arm_compute::test::validation::num_groups, INode::output(), Graph::remove_node(), Tensor::set_accessor(), Graph::tensors(), INode::type(), and IDeviceBackend::validate_node().
name()
const char * name () override virtual
Returns mutator name.
Returns
Mutator name
Implements IGraphMutator.
Definition at line 101 of file GroupedConvolutionMutator.cpp.
 {
     return "GroupedConvolutionMutator";
 }
The documentation for this class was generated from the following files:
arm_compute/graph/mutators/GroupedConvolutionMutator.h
src/graph/mutators/GroupedConvolutionMutator.cpp