Compute Library: CLAccessor Class Reference
CLAccessor Class Reference
Accessor implementation for CLTensor objects.
#include <CLAccessor.h>
Public Member Functions
CLAccessor (CLTensor &tensor)
Create an accessor for the given tensor.
CLAccessor (const CLAccessor &)=delete
Prevent instances of this class from being copy constructed.
CLAccessor & operator= (const CLAccessor &)=delete
Prevent instances of this class from being copied.
CLAccessor (CLAccessor &&)=default
Allow instances of this class to be move constructed.
CLAccessor & operator= (CLAccessor &&)=default
Allow instances of this class to be moved.
~CLAccessor ()
Destructor that unmaps the CL memory.
const void * data () const
Get the tensor data.
void * data ()
Get the tensor data.
TensorShape shape () const override
Shape of the tensor.
size_t element_size () const override
Size of each element in the tensor in bytes.
size_t size () const override
Total size of the tensor in bytes.
Format format () const override
Image format of the tensor.
DataLayout data_layout () const override
Data layout of the tensor.
DataType data_type () const override
Data type of the tensor.
int num_channels () const override
Number of channels of the tensor.
int num_elements () const override
Number of elements of the tensor.
PaddingSize padding () const override
Available padding around the tensor.
QuantizationInfo quantization_info () const override
Quantization info in case of asymmetric quantized type.
const void * operator() (const Coordinates &coord) const override
Read only access to the specified element.
void * operator() (const Coordinates &coord) override
Access to the specified element.
Public Member Functions inherited from IAccessor
virtual ~IAccessor ()=default
Virtual destructor.
Detailed Description
Accessor implementation for CLTensor objects.
Definition at line 35 of file CLAccessor.h.
Constructor & Destructor Documentation
CLAccessor() [1/3]
CLAccessor (CLTensor & tensor) inline
Create an accessor for the given tensor.
Parameters
[in,out] tensor To be accessed tensor.
Note
The CL memory is mapped by the constructor.
Definition at line 88 of file CLAccessor.h.
     : _tensor{ tensor }
 {
     _tensor.map();
 }
CLAccessor() [2/3]
CLAccessor (const CLAccessor &) delete
Prevent instances of this class from being copy constructed.
CLAccessor() [3/3]
CLAccessor (CLAccessor &&) default
Allow instances of this class to be move constructed.
~CLAccessor()
~CLAccessor () inline
Destructor that unmaps the CL memory.
Definition at line 94 of file CLAccessor.h.
 {
     _tensor.unmap();
 }
References CLTensor::unmap().
Member Function Documentation
data() [1/2]
const void * data () const inline
Get the tensor data.
Returns
a constant pointer to the tensor data.
Definition at line 149 of file CLAccessor.h.
 {
     return _tensor.buffer();
 }
References ICLTensor::buffer().
data() [2/2]
void * data () inline
Get the tensor data.
Returns
a pointer to the tensor data.
Definition at line 154 of file CLAccessor.h.
 {
     return _tensor.buffer();
 }
References ICLTensor::buffer().
data_layout()
DataLayout data_layout () const inline override virtual
Data layout of the tensor.
Returns
the data layout of the tensor.
Implements IAccessor.
Definition at line 119 of file CLAccessor.h.
 {
     return _tensor.info()->data_layout();
 }
References TensorInfo::data_layout(), and CLTensor::info().
data_type()
DataType data_type () const inline override virtual
Data type of the tensor.
Returns
the data type of the tensor.
Implements IAccessor.
Definition at line 124 of file CLAccessor.h.
 {
     return _tensor.info()->data_type();
 }
References TensorInfo::data_type(), and CLTensor::info().
element_size()
size_t element_size () const inline override virtual
Size of each element in the tensor in bytes.
Returns
the size of each element in the tensor in bytes.
Implements IAccessor.
Definition at line 104 of file CLAccessor.h.
 {
     return _tensor.info()->element_size();
 }
References TensorInfo::element_size(), and CLTensor::info().
format()
Format format () const inline override virtual
Image format of the tensor.
Returns
the format of the tensor.
Implements IAccessor.
Definition at line 114 of file CLAccessor.h.
 {
     return _tensor.info()->format();
 }
References TensorInfo::format(), and CLTensor::info().
num_channels()
int num_channels () const inline override virtual
Number of channels of the tensor.
Returns
the number of channels of the tensor.
Implements IAccessor.
Definition at line 129 of file CLAccessor.h.
 {
     return _tensor.info()->num_channels();
 }
References CLTensor::info(), and TensorInfo::num_channels().
num_elements()
int num_elements () const inline override virtual
Number of elements of the tensor.
Returns
the number of elements of the tensor.
Implements IAccessor.
Definition at line 134 of file CLAccessor.h.
 {
     return _tensor.info()->tensor_shape().total_size();
 }
References CLTensor::info(), TensorInfo::tensor_shape(), and TensorShape::total_size().
operator()() [1/2]
const void * operator() (const Coordinates & coord) const inline override virtual
Read only access to the specified element.
Parameters
[in] coord Coordinates of the desired element.
Returns
A pointer to the desired element.
Implements IAccessor.
Definition at line 159 of file CLAccessor.h.
 {
     return _tensor.ptr_to_element(coord);
 }
References ITensor::ptr_to_element().
operator()() [2/2]
void * operator() (const Coordinates & coord) inline override virtual
Access to the specified element.
Parameters
[in] coord Coordinates of the desired element.
Returns
A pointer to the desired element.
Implements IAccessor.
Definition at line 164 of file CLAccessor.h.
 {
     return _tensor.ptr_to_element(coord);
 }
References ITensor::ptr_to_element().
operator=() [1/2]
CLAccessor& operator= (const CLAccessor &) delete
Prevent instances of this class from being copied.
operator=() [2/2]
CLAccessor& operator= (CLAccessor &&) default
Allow instances of this class to be moved.
padding()
PaddingSize padding () const inline override virtual
Available padding around the tensor.
Returns
the available padding around the tensor.
Implements IAccessor.
Definition at line 139 of file CLAccessor.h.
 {
     return _tensor.info()->padding();
 }
References CLTensor::info(), and TensorInfo::padding().
quantization_info()
QuantizationInfo quantization_info () const inline override virtual
Quantization info in case of asymmetric quantized type.
Returns
Implements IAccessor.
Definition at line 144 of file CLAccessor.h.
 {
     return _tensor.info()->quantization_info();
 }
References CLTensor::info(), and TensorInfo::quantization_info().
shape()
TensorShape shape () const inline override virtual
Shape of the tensor.
Returns
the shape of the tensor.
Implements IAccessor.
Definition at line 99 of file CLAccessor.h.
 {
     return _tensor.info()->tensor_shape();
 }
References CLTensor::info(), and TensorInfo::tensor_shape().
size()
size_t size () const inline override virtual
Total size of the tensor in bytes.
Returns
the total size of the tensor in bytes.
Implements IAccessor.
Definition at line 109 of file CLAccessor.h.
 {
     return _tensor.info()->total_size();
 }
References CLTensor::info(), and TensorInfo::total_size().
The documentation for this class was generated from the following file:
tests/CL/CLAccessor.h