Compute Library: NETileKernel Class Reference
NETileKernel Class Reference
NEON kernel to perform a tile operation.
#include <NETileKernel.h>
Public Member Functions
NETileKernel ()
Default constructor.
NETileKernel (const NETileKernel &)=delete
Prevent instances of this class from being copied (As this class contains pointers).
NETileKernel & operator= (const NETileKernel &)=delete
Prevent instances of this class from being copied (As this class contains pointers).
NETileKernel (NETileKernel &&)=default
Allow instances of this class to be moved.
NETileKernel & operator= (NETileKernel &&)=default
Allow instances of this class to be moved.
const char * name () const override
Name of the kernel.
void configure (const ITensor *input, ITensor *output, const Multiples &multiples)
Set the source, destination of the kernel.
void run (const Window &window, const ThreadInfo &info) override
Execute the kernel on the passed window.
Public Member Functions inherited from ICPPKernel
virtual ~ICPPKernel ()=default
Default destructor.
Public Member Functions inherited from IKernel
IKernel ()
Constructor.
virtual ~IKernel ()=default
Destructor.
virtual bool is_parallelisable () const
Indicates whether or not the kernel is parallelisable.
virtual BorderSize border_size () const
The size of the border for that kernel.
const Window & window () const
The maximum window the kernel can be executed on.
Static Public Member Functions
static Status validate (const ITensorInfo *input, const ITensorInfo *output, const Multiples &multiples)
Static function to check if given info will lead to a valid configuration of NETileKernel.
Detailed Description
NEON kernel to perform a tile operation.
Definition at line 34 of file NETileKernel.h.
Constructor & Destructor Documentation
NETileKernel() [1/3]
NETileKernel ()
Default constructor.
Definition at line 59 of file NETileKernel.cpp.
     : _input(nullptr), _output(nullptr)
 {
 }
NETileKernel() [2/3]
NETileKernel (const NETileKernel &) delete
Prevent instances of this class from being copied (As this class contains pointers).
NETileKernel() [3/3]
NETileKernel (NETileKernel &&) default
Allow instances of this class to be moved.
Member Function Documentation
configure()
void configure (const ITensor * input, ITensor * output, const Multiples & multiples)
Set the source, destination of the kernel.
Parameters
[in] input Source tensor. Data type supported: U8/S8/QASYMM8/U16/S16/F16/U32/S32/F32.
[out] output Destination tensor. Same as input
[in] multiples Contains the number of times the input tensor should be replicated on the given dimension.
Definition at line 64 of file NETileKernel.cpp.
 {
     ARM_COMPUTE_ERROR_ON_NULLPTR(input, output);
     // Auto initialize output
     TensorShape tiled_shape = misc::shape_calculator::compute_tiled_shape(input->info()->tensor_shape(), multiples);
     auto_init_if_empty(*output->info(), tiled_shape, 1, input->info()->data_type());
     // Validate
     ARM_COMPUTE_ERROR_THROW_ON(validate_arguments(input->info(), output->info(), multiples));
     _input  = input;
     _output = output;
     // Configure window without padding
     Window win = calculate_max_window(*output->info());
     INEKernel::configure(win);
 }
References ARM_COMPUTE_ERROR_ON_NULLPTR, ARM_COMPUTE_ERROR_THROW_ON, arm_compute::auto_init_if_empty(), arm_compute::calculate_max_window(), arm_compute::misc::shape_calculator::compute_tiled_shape(), ITensorInfo::data_type(), ITensor::info(), and ITensorInfo::tensor_shape().
name()
const char* name () const inline override virtual
Name of the kernel.
Returns
Kernel name
Implements ICPPKernel.
Definition at line 47 of file NETileKernel.h.
     {
         return "NETileKernel";
     }
operator=() [1/2]
NETileKernel& operator= (const NETileKernel &) delete
Prevent instances of this class from being copied (As this class contains pointers).
operator=() [2/2]
NETileKernel& operator= (NETileKernel &&) default
Allow instances of this class to be moved.
run()
void run (const Window & window, const ThreadInfo & info) override virtual
Execute the kernel on the passed window.
Warning
If is_parallelisable() returns false then the passed window must be equal to window()
Note
The window has to be a region within the window returned by the window() method
The width of the window has to be a multiple of num_elems_processed_per_iteration().
Parameters
[in] window Region on which to execute the kernel. (Must be a region of the window returned by window())
[in] info Info about executing thread and CPU.
Implements ICPPKernel.
Definition at line 89 of file NETileKernel.cpp.
 {
     ARM_COMPUTE_UNUSED(info);
     ARM_COMPUTE_ERROR_ON_UNCONFIGURED_KERNEL(this);
     ARM_COMPUTE_ERROR_ON_INVALID_SUBWINDOW(INEKernel::window(), window);
     Window output_window{ window };
     output_window.set(Window::DimX, Window::Dimension(output_window.x().start(), output_window.x().end(), _input->info()->dimension(0)));
     Window out_slice = output_window.first_slice_window_1D();
     const auto src_shape = _input->info()->tensor_shape();
     do
     {
         Iterator output_it(_output, out_slice);
         execute_window_loop(out_slice, [&](const Coordinates & id)
         {
             const size_t x = id.x();
             const size_t y = id.y();
             const size_t z = id.z();
             const size_t w = id[3];
             Coordinates  input_coords{ x % src_shape[0], y % src_shape[1], z % src_shape[2], w % src_shape[3] };
             memcpy(output_it.ptr(), _input->ptr_to_element(input_coords), _input->info()->dimension(0) * _input->info()->element_size());
         },
         output_it);
     }
     while(output_window.slide_window_slice_1D(out_slice));
 }
References ARM_COMPUTE_ERROR_ON_INVALID_SUBWINDOW, ARM_COMPUTE_ERROR_ON_UNCONFIGURED_KERNEL, ARM_COMPUTE_UNUSED, ITensorInfo::dimension(), Window::DimX, ITensorInfo::element_size(), arm_compute::execute_window_loop(), Window::first_slice_window_1D(), ITensor::info(), arm_compute::test::validation::info, Iterator::ptr(), ITensor::ptr_to_element(), Window::set(), ITensorInfo::tensor_shape(), arm_compute::test::validation::w, IKernel::window(), and Window::x().
validate()
Status validate (const ITensorInfo * input, const ITensorInfo * output, const Multiples & multiples) static
Static function to check if given info will lead to a valid configuration of NETileKernel.
Parameters
[in] input Source tensor info. Data type supported: U8/S8/QASYMM8/U16/S16/F16/U32/S32/F32.
[in] output Destination tensor info. Same as input
[in] multiples Contains the number of times the input tensor should be replicated on the given dimension.
Returns
a status
Definition at line 83 of file NETileKernel.cpp.
 {
     ARM_COMPUTE_RETURN_ON_ERROR(validate_arguments(input, output, multiples));
     return Status{};
 }
References ARM_COMPUTE_RETURN_ON_ERROR.
Referenced by NETile::validate().
The documentation for this class was generated from the following files:
arm_compute/core/NEON/kernels/NETileKernel.h
src/core/NEON/kernels/NETileKernel.cpp