Compute Library: CLLut Class Reference
CLLut Class Reference
Basic implementation of the OpenCL lut interface.
#include <CLLut.h>
Public Member Functions
CLLut ()
Constructor.
CLLut (size_t num_elements, DataType data_type)
Constructor: initializes a LUT which can contain num_values values of data_type type.
ILutAllocator * allocator ()
Return a pointer to the lut's allocator.
void map (bool blocking=true)
Enqueue a map operation of the allocated buffer.
void unmap ()
Enqueue an unmap operation of the allocated and mapped buffer.
size_t num_elements () const override
Returns the total number of elements in the LUT.
uint32_t index_offset () const override
Indicates the offset that needs to be applied to the raw index before performing a lookup in the LUT.
size_t size_in_bytes () const override
Returns the total size in bytes of the LUT.
DataType type () const override
Returns the type of the LUT.
const cl::Buffer & cl_buffer () const override
Interface to be implemented by the child class to return a reference to the OpenCL buffer containing the lut's data.
void clear () override
Clears the LUT by setting every element to zero.
void map (cl::CommandQueue &q, bool blocking=true)
Enqueue a map operation of the allocated buffer on the given queue.
void unmap (cl::CommandQueue &q)
Enqueue an unmap operation of the allocated and mapped buffer on the given queue.
Public Member Functions inherited from ICLLut
ICLLut ()
ICLLut (const ICLLut &)=delete
ICLLut & operator= (const ICLLut &)=delete
void map (cl::CommandQueue &q, bool blocking=true)
Enqueue a map operation of the allocated buffer on the given queue.
void unmap (cl::CommandQueue &q)
Enqueue an unmap operation of the allocated and mapped buffer on the given queue.
uint8_t * buffer () const override
Returns a pointer to the start of the LUT.
Public Member Functions inherited from ILut
virtual ~ILut ()=default
Default virtual destructor.
Detailed Description
Basic implementation of the OpenCL lut interface.
Definition at line 40 of file CLLut.h.
Constructor & Destructor Documentation
CLLut() [1/2]
CLLut ()
Constructor.
Definition at line 32 of file CLLut.cpp.
     : _allocator()
 {
 }
CLLut() [2/2]
CLLut (size_t num_elements, DataType data_type)
Constructor: initializes a LUT which can contain num_values values of data_type type.
Parameters
[in] num_elements Number of elements of the LUT.
[in] data_type Data type of each element.
Definition at line 37 of file CLLut.cpp.
     : _allocator()
 {
     _allocator.init(num_elements, data_type);
 }
References arm_compute::test::validation::data_type, ILutAllocator::init(), and CLLut::num_elements().
Member Function Documentation
allocator()
ILutAllocator * allocator ()
Return a pointer to the lut's allocator.
Returns
A pointer to the lut's allocator
Definition at line 76 of file CLLut.cpp.
 {
     return &_allocator;
 }
cl_buffer()
const cl::Buffer & cl_buffer () const override virtual
Interface to be implemented by the child class to return a reference to the OpenCL buffer containing the lut's data.
Returns
A reference to an OpenCL buffer containing the lut's data.
Implements ICLLut.
Definition at line 63 of file CLLut.cpp.
 {
     return _allocator.cl_data();
 }
References CLLutAllocator::cl_data().
clear()
void clear () override virtual
Clears the LUT by setting every element to zero.
Implements ILut.
Definition at line 68 of file CLLut.cpp.
 {
     cl::CommandQueue &q    = CLScheduler::get().queue();
     uint8_t          *data = _allocator.map(q, true /* blocking */);
     std::memset(data, 0, size_in_bytes());
     _allocator.unmap(q, data);
 }
References CLScheduler::get(), CLLutAllocator::map(), CLScheduler::queue(), CLLut::size_in_bytes(), and CLLutAllocator::unmap().
index_offset()
uint32_t index_offset () const override virtual
Indicates the offset that needs to be applied to the raw index before performing a lookup in the LUT.
Returns
The normalization offset.
Implements ILut.
Definition at line 48 of file CLLut.cpp.
 {
     return (DataType::S16 == _allocator.type()) ? num_elements() / 2 : 0;
 }
References CLLut::num_elements(), arm_compute::S16, and ILutAllocator::type().
Referenced by CLLutAccessor< T >::operator[]().
map() [1/2]
void map (bool blocking = true)
Enqueue a map operation of the allocated buffer.
Parameters
[in] blocking If true, then the mapping will be ready to use by the time this method returns, else it is the caller's responsibility to flush the queue and wait for the mapping operation to have completed.
Definition at line 81 of file CLLut.cpp.
 {
     ICLLut::map(CLScheduler::get().queue(), blocking);
 }
References CLScheduler::get(), and ICLLut::map().
map() [2/2]
void map
Enqueue a map operation of the allocated buffer on the given queue.
Parameters
[in,out] q The CL command queue to use for the mapping operation.
[in] blocking If true, then the mapping will be ready to use by the time this method returns, else it is the caller's responsibility to flush the queue and wait for the mapping operation to have completed before using the returned mapping pointer.
Definition at line 33 of file ICLLut.cpp.
 {
     _mapping = do_map(q, blocking);
 }
num_elements()
size_t num_elements () const override virtual
Returns the total number of elements in the LUT.
Returns
Total number of elements.
Implements ILut.
Definition at line 43 of file CLLut.cpp.
 {
     return _allocator.num_elements();
 }
References ILutAllocator::num_elements().
Referenced by CLLut::CLLut(), CLLut::index_offset(), and CLLutAccessor< T >::num_elements().
size_in_bytes()
size_t size_in_bytes () const override virtual
Returns the total size in bytes of the LUT.
Returns
Total size of the LUT in bytes.
Implements ILut.
Definition at line 53 of file CLLut.cpp.
 {
     return _allocator.size();
 }
References ILutAllocator::size().
Referenced by CLLut::clear().
type()
DataType type () const override virtual
Returns the type of the LUT.
Returns
The type of the LUT.
Implements ILut.
Definition at line 58 of file CLLut.cpp.
 {
     return _allocator.type();
 }
References ILutAllocator::type().
unmap() [1/2]
void unmap ()
Enqueue an unmap operation of the allocated and mapped buffer.
Note
This method simply enqueues the unmap operation, it is the caller's responsibility to flush the queue and make sure the unmap is finished before the memory is accessed by the device.
Definition at line 86 of file CLLut.cpp.
 {
     ICLLut::unmap(CLScheduler::get().queue());
 }
References CLScheduler::get(), and ICLLut::unmap().
Referenced by CLLutAccessor< T >::~CLLutAccessor().
unmap() [2/2]
void unmap
Enqueue an unmap operation of the allocated and mapped buffer on the given queue.
Note
This method simply enqueues the unmap operation, it is the caller's responsibility to flush the queue and make sure the unmap is finished before the memory is accessed by the device.
Parameters
[in,out] q The CL command queue to use for the mapping operation.
Definition at line 38 of file ICLLut.cpp.
 {
     do_unmap(q);
     _mapping = nullptr;
 }
The documentation for this class was generated from the following files:
arm_compute/runtime/CL/CLLut.h
src/runtime/CL/CLLut.cpp