Compute Library: NEPermuteKernel Class Reference
NEPermuteKernel Class Reference
NEON kernel to perform tensor permutation.
#include <NEPermuteKernel.h>
Public Member Functions
const char * name () const override
Name of the kernel.
NEPermuteKernel ()
Default constructor.
NEPermuteKernel (const NEPermuteKernel &)=delete
Prevent instances of this class from being copied (As this class contains pointers)
NEPermuteKernel & operator= (const NEPermuteKernel &)=delete
Prevent instances of this class from being copied (As this class contains pointers)
NEPermuteKernel (NEPermuteKernel &&)=default
Allow instances of this class to be moved.
NEPermuteKernel & operator= (NEPermuteKernel &&)=default
Allow instances of this class to be moved.
~NEPermuteKernel ()=default
Default destructor.
void configure (const ITensor *input, ITensor *output, const PermutationVector &perm)
Set the input and output of the kernel.
void run (const Window &window, const ThreadInfo &info) override
Execute the kernel on the passed window.
Public Member Functions inherited from ICPPKernel
virtual ~ICPPKernel ()=default
Default destructor.
Public Member Functions inherited from IKernel
IKernel ()
Constructor.
virtual ~IKernel ()=default
Destructor.
virtual bool is_parallelisable () const
Indicates whether or not the kernel is parallelisable.
virtual BorderSize border_size () const
The size of the border for that kernel.
const Window & window () const
The maximum window the kernel can be executed on.
Static Public Member Functions
static Status validate (const ITensorInfo *input, const ITensorInfo *output, const PermutationVector &perm)
Static function to check if given info will lead to a valid configuration of CPPPermuteKernel.
Detailed Description
NEON kernel to perform tensor permutation.
Permutes given a permutation vector
Definition at line 37 of file NEPermuteKernel.h.
Constructor & Destructor Documentation
NEPermuteKernel() [1/3]
NEPermuteKernel ()
Default constructor.
Definition at line 237 of file NEPermuteKernel.cpp.
     : _func(), _input(nullptr), _output(nullptr), _perm()
 {
 }
NEPermuteKernel() [2/3]
NEPermuteKernel (const NEPermuteKernel &) delete
Prevent instances of this class from being copied (As this class contains pointers)
NEPermuteKernel() [3/3]
NEPermuteKernel (NEPermuteKernel &&) default
Allow instances of this class to be moved.
~NEPermuteKernel()
~NEPermuteKernel () default
Default destructor.
Member Function Documentation
configure()
void configure (const ITensor * input, ITensor * output, const PermutationVector & perm)
Set the input and output of the kernel.
Note
Supported permutation vectors : [2, 0, 1], [1, 2, 0]
Parameters
[in] input The input tensor to permute. Data types supported: U8/S8/QASYMM8/U16/S16/F16/U32/S32/F32
[out] output The output tensor. Data types supported: Same as input
[in] perm Permutation vector
Definition at line 242 of file NEPermuteKernel.cpp.
 {
     ARM_COMPUTE_ERROR_ON_NULLPTR(input, output);
     const TensorShape output_shape = misc::shape_calculator::compute_permutation_output_shape(*input->info(), perm);
     // Output auto inizialitation if not yet initialized
     auto_init_if_empty(*output->info(), input->info()->clone()->set_tensor_shape(output_shape));
     // Perform validation step
     ARM_COMPUTE_ERROR_THROW_ON(validate_arguments(input->info(), output->info(), perm));
     _input  = input;
     _output = output;
     _perm   = perm;
     switch(input->info()->element_size())
     {
         case 1:
             _func = &NEPermuteKernel::run_permute<uint8_t>;
             break;
         case 2:
             _func = &NEPermuteKernel::run_permute<uint16_t>;
             break;
         case 4:
             _func = &NEPermuteKernel::run_permute<uint32_t>;
             break;
         default:
             ARM_COMPUTE_ERROR("Element size not supported");
             break;
     }
     // Configure kernel window
     Window win = calculate_max_window(*input->info(), Steps());
     // The NEPermute doesn't need padding so update_window_and_padding() can be skipped
     Coordinates coord;
     coord.set_num_dimensions(output->info()->num_dimensions());
     output->info()->set_valid_region(ValidRegion(coord, output->info()->tensor_shape()));
     ICPPKernel::configure(win);
 }
References ARM_COMPUTE_ERROR, ARM_COMPUTE_ERROR_ON_NULLPTR, ARM_COMPUTE_ERROR_THROW_ON, arm_compute::auto_init_if_empty(), arm_compute::calculate_max_window(), ICloneable< T >::clone(), arm_compute::misc::shape_calculator::compute_permutation_output_shape(), ITensorInfo::element_size(), ITensor::info(), ITensorInfo::num_dimensions(), arm_compute::test::validation::output_shape, Dimensions< T >::set_num_dimensions(), ITensorInfo::set_valid_region(), and ITensorInfo::tensor_shape().
name()
const char* name () const inline override virtual
Name of the kernel.
Returns
Kernel name
Implements ICPPKernel.
Definition at line 40 of file NEPermuteKernel.h.
     {
         return "NEPermuteKernel";
     }
operator=() [1/2]
NEPermuteKernel& operator= (const NEPermuteKernel &) delete
Prevent instances of this class from being copied (As this class contains pointers)
operator=() [2/2]
NEPermuteKernel& operator= (NEPermuteKernel &&) default
Allow instances of this class to be moved.
run()
void run (const Window & window, const ThreadInfo & info) override virtual
Execute the kernel on the passed window.
Warning
If is_parallelisable() returns false then the passed window must be equal to window()
Note
The window has to be a region within the window returned by the window() method
The width of the window has to be a multiple of num_elems_processed_per_iteration().
Parameters
[in] window Region on which to execute the kernel. (Must be a region of the window returned by window())
[in] info Info about executing thread and CPU.
Implements ICPPKernel.
Definition at line 289 of file NEPermuteKernel.cpp.
 {
     ARM_COMPUTE_UNUSED(info);
     ARM_COMPUTE_ERROR_ON_UNCONFIGURED_KERNEL(this);
     ARM_COMPUTE_ERROR_ON_INVALID_SUBWINDOW(ICPPKernel::window(), window);
     if(_func != nullptr)
     {
         (this->*_func)(window);
     }
 }
References ARM_COMPUTE_ERROR_ON_INVALID_SUBWINDOW, ARM_COMPUTE_ERROR_ON_UNCONFIGURED_KERNEL, ARM_COMPUTE_UNUSED, arm_compute::test::validation::info, and IKernel::window().
validate()
Status validate (const ITensorInfo * input, const ITensorInfo * output, const PermutationVector & perm) static
Static function to check if given info will lead to a valid configuration of CPPPermuteKernel.
Note
Supported permutation vectors : [2, 0, 1], [1, 2, 0]
Parameters
[in] input The input tensor to permute. Data types supported: U8/S8/QASYMM8/U16/S16/F16/U32/S32/F32
[in] output The output tensor. Data types supported: Same as input
[in] perm Permutation vector
Returns
a status
Definition at line 283 of file NEPermuteKernel.cpp.
 {
     ARM_COMPUTE_RETURN_ON_ERROR(validate_arguments(input, output, perm));
     return Status{};
 }
References ARM_COMPUTE_RETURN_ON_ERROR.
Referenced by NEPermute::validate().
The documentation for this class was generated from the following files:
arm_compute/core/NEON/kernels/NEPermuteKernel.h
src/core/NEON/kernels/NEPermuteKernel.cpp