Compute Library: CLHOGAccessor Class Reference
CLHOGAccessor Class Reference
Accessor implementation for CLHOG objects.
#include <CLHOGAccessor.h>
Public Member Functions
CLHOGAccessor (CLHOG &hog)
Create an accessor for the given CLHOG.
~CLHOGAccessor ()
Destructor that unmaps the CL memory.
CLHOGAccessor (const CLHOGAccessor &)=delete
Prevent instances of this class from being copied (As this class contains references).
CLHOGAccessor & operator= (const CLHOGAccessor &)=delete
Prevent instances of this class from being copied (As this class contains references).
CLHOGAccessor (CLHOGAccessor &&)=default
Allow instances of this class to be moved.
CLHOGAccessor & operator= (CLHOGAccessor &&)=default
Allow instances of this class to be moved.
float * descriptor () const override
Pointer to the first element of the array which stores the linear SVM coefficients of HOG descriptor.
Public Member Functions inherited from IHOGAccessor
virtual ~IHOGAccessor ()=default
Virtual destructor.
Detailed Description
Accessor implementation for CLHOG objects.
Definition at line 35 of file CLHOGAccessor.h.
Constructor & Destructor Documentation
CLHOGAccessor (CLHOG & hog) inline
Create an accessor for the given CLHOG.
Definition at line 39 of file CLHOGAccessor.h.
References CLHOG::map().
Referenced by CLHOGAccessor::~CLHOGAccessor().
         : _hog{ hog }
     {
         _hog.map();
     }
~CLHOGAccessor () inline
Destructor that unmaps the CL memory.
Definition at line 46 of file CLHOGAccessor.h.
References CLHOGAccessor::CLHOGAccessor(), CLHOGAccessor::operator=(), and CLHOG::unmap().
     {
         _hog.unmap();
     }
CLHOGAccessor (const CLHOGAccessor &) delete
Prevent instances of this class from being copied (As this class contains references).
CLHOGAccessor (CLHOGAccessor &&) default
Allow instances of this class to be moved.
Member Function Documentation
float* descriptor () const inline override virtual
Pointer to the first element of the array which stores the linear SVM coefficients of HOG descriptor.
Returns
A pointer to the first element of the array which stores the linear SVM coefficients of HOG descriptor
Implements IHOGAccessor.
Definition at line 64 of file CLHOGAccessor.h.
References ICLHOG::descriptor().
     {
         return _hog.descriptor();
     }
CLHOGAccessor& operator= (const CLHOGAccessor &) delete
Prevent instances of this class from being copied (As this class contains references).
Referenced by CLHOGAccessor::~CLHOGAccessor().
CLHOGAccessor& operator= (CLHOGAccessor &&) default
Allow instances of this class to be moved.
The documentation for this class was generated from the following file:
tests/CL/CLHOGAccessor.h