Compute Library: BackendRegistry Class Reference
BackendRegistry Class Reference final
Registry holding all the supported backends.
#include <BackendRegistry.h>
Public Member Functions
IDeviceBackend * find_backend (Target target)
Finds a backend in the registry.
IDeviceBackend & get_backend (Target target)
Get a backend from the registry.
bool contains (Target target) const
Checks if a backend for a given target exists.
const std::map< Target, std::unique_ptr< IDeviceBackend > > & backends () const
Backends accessor.
template<typename T >
void add_backend (Target target)
Registers a backend to the registry.
Static Public Member Functions
static BackendRegistry & get ()
Gets backend registry instance.
Detailed Description
Registry holding all the supported backends.
Definition at line 41 of file BackendRegistry.h.
Member Function Documentation
add_backend()
void add_backend (Target target) inline
Registers a backend to the registry.
Parameters
[in] target Execution target to register for
Definition at line 94 of file BackendRegistry.h.
 {
     _registered_backends[target] = support::cpp14::make_unique<T>();
 }
Referenced by BackendRegistrar< T >::BackendRegistrar().
backends()
const std::map< Target, std::unique_ptr< IDeviceBackend > > & backends () const
Backends accessor.
Returns
Map containing the registered backends
Definition at line 65 of file BackendRegistry.cpp.
 {
     return _registered_backends;
 }
contains()
bool contains (Target target) const
Checks if a backend for a given target exists.
Parameters
[in] target Execution target
Returns
True if exists else false
Definition at line 59 of file BackendRegistry.cpp.
 {
     auto it = _registered_backends.find(target);
     return (it != _registered_backends.end());
 }
Referenced by arm_compute::graph::is_target_supported().
find_backend()
IDeviceBackend * find_backend (Target target)
Finds a backend in the registry.
Parameters
[in] target Backend target
Returns
Pointer to the backend interface if found, else nullptr
Definition at line 45 of file BackendRegistry.cpp.
 {
     ARM_COMPUTE_ERROR_ON(!contains(target));
     return _registered_backends[target].get();
 }
References ARM_COMPUTE_ERROR_ON.
Referenced by arm_compute::graph::is_target_supported(), and arm_compute::graph::setup_requested_backend_context().
get()
BackendRegistry & get () static
Gets backend registry instance.
Returns
Backend registry instance
Definition at line 39 of file BackendRegistry.cpp.
 {
     static BackendRegistry instance;
     return instance;
 }
Referenced by BackendRegistrar< T >::BackendRegistrar(), arm_compute::graph::detail::configure_all_nodes(), arm_compute::graph::detail::configure_all_tensors(), arm_compute::graph::configure_tensor(), arm_compute::graph::is_target_supported(), SplitLayerSubTensorMutator::mutate(), DepthConcatSubTensorMutator::mutate(), GroupedConvolutionMutator::mutate(), arm_compute::graph::release_default_graph_context(), arm_compute::graph::setup_requested_backend_context(), and arm_compute::graph::detail::validate_all_nodes().
get_backend()
IDeviceBackend & get_backend (Target target)
Get a backend from the registry.
The backend must be present and supported.
Parameters
[in] target Backend target
Returns
Reference to the backend interface
Definition at line 51 of file BackendRegistry.cpp.
 {
     IDeviceBackend *backend = find_backend(target);
     ARM_COMPUTE_ERROR_ON_MSG(!backend, "Requested backend doesn't exist!");
     ARM_COMPUTE_ERROR_ON_MSG(!backend->is_backend_supported(), "Requested backend isn't supported");
     return *backend;
 }
References ARM_COMPUTE_ERROR_ON_MSG, and IDeviceBackend::is_backend_supported().
Referenced by arm_compute::graph::detail::configure_all_nodes(), arm_compute::graph::detail::configure_all_tensors(), arm_compute::graph::configure_tensor(), DepthConcatSubTensorMutator::mutate(), SplitLayerSubTensorMutator::mutate(), GroupedConvolutionMutator::mutate(), and arm_compute::graph::detail::validate_all_nodes().
The documentation for this class was generated from the following files:
arm_compute/graph/backends/BackendRegistry.h
src/graph/backends/BackendRegistry.cpp