Compute Library: GCNormalizationLayerKernel Class Reference
GCNormalizationLayerKernel Class Reference
Interface for the normalization layer kernel.
#include <GCNormalizationLayerKernel.h>
Public Member Functions
GCNormalizationLayerKernel ()
Constructor.
GCNormalizationLayerKernel (const GCNormalizationLayerKernel &)=delete
Prevent instances of this class from being copied (As this class contains pointers)
GCNormalizationLayerKernel & operator= (const GCNormalizationLayerKernel &)=delete
Prevent instances of this class from being copied (As this class contains pointers)
GCNormalizationLayerKernel (GCNormalizationLayerKernel &&)=default
Default Move Constructor.
GCNormalizationLayerKernel & operator= (GCNormalizationLayerKernel &&)=default
Default move assignment operator.
~GCNormalizationLayerKernel ()=default
Default destrutor.
void configure (const IGCTensor *input, const IGCTensor *squared_input, IGCTensor *output, NormalizationLayerInfo norm_info)
Set the input and output tensors.
void run (const Window &window) override
Enqueue the OpenGL ES shader to process the given window.
BorderSize border_size () const override
The size of the border for that kernel.
Public Member Functions inherited from IGCKernel
IGCKernel ()
Constructor.
GCKernel & kernel ()
Returns a reference to the GLES kernel of this object.
void add_1D_tensor_argument (unsigned int &idx, const IGCTensor *tensor, const unsigned int binding_point, const Window &window)
Add the passed 1D tensor's parameters to the object's kernel's arguments starting from the index idx.
void add_2D_tensor_argument (unsigned int &idx, const IGCTensor *tensor, const unsigned int binding_point, const Window &window)
Add the passed 2D tensor's parameters to the object's kernel's arguments starting from the index idx.
void add_3D_tensor_argument (unsigned int &idx, const IGCTensor *tensor, const unsigned int binding_point, const Window &window)
Add the passed 3D tensor's parameters to the object's kernel's arguments starting from the index idx.
unsigned int num_arguments_per_1D_tensor () const
Returns the number of arguments enqueued per 1D tensor object.
unsigned int num_arguments_per_2D_tensor () const
Returns the number of arguments enqueued per 2D tensor object.
unsigned int num_arguments_per_3D_tensor () const
Returns the number of arguments enqueued per 3D tensor object.
void set_lws_hint (gles::NDRange &lws_hint)
Set the Local-Workgroup-Size hint.
void set_target (GPUTarget target)
Set the targeted GPU architecture.
GPUTarget get_target () const
Get the targeted GPU architecture.
Public Member Functions inherited from IKernel
IKernel ()
Constructor.
virtual ~IKernel ()=default
Destructor.
virtual bool is_parallelisable () const
Indicates whether or not the kernel is parallelisable.
const Window & window () const
The maximum window the kernel can be executed on.
Detailed Description
Interface for the normalization layer kernel.
Definition at line 35 of file GCNormalizationLayerKernel.h.
Constructor & Destructor Documentation
GCNormalizationLayerKernel() [1/3]
GCNormalizationLayerKernel ()
Constructor.
Definition at line 39 of file GCNormalizationLayerKernel.cpp.
     : _input(nullptr), _squared_input(nullptr), _output(nullptr), _border_size(0)
 {
 }
GCNormalizationLayerKernel() [2/3]
GCNormalizationLayerKernel (const GCNormalizationLayerKernel &) delete
Prevent instances of this class from being copied (As this class contains pointers)
GCNormalizationLayerKernel() [3/3]
GCNormalizationLayerKernel (GCNormalizationLayerKernel &&) default
Default Move Constructor.
~GCNormalizationLayerKernel()
~GCNormalizationLayerKernel () default
Default destrutor.
Member Function Documentation
border_size()
BorderSize border_size () const override virtual
The size of the border for that kernel.
Returns
The width in number of elements of the border.
Reimplemented from IKernel.
Definition at line 44 of file GCNormalizationLayerKernel.cpp.
 {
     return _border_size;
 }
Referenced by GCNormalizationLayer::configure().
configure()
void configure (const IGCTensor * input, const IGCTensor * squared_input, IGCTensor * output, NormalizationLayerInfo norm_info)
Set the input and output tensors.
Parameters
[in] input Source tensor. 3 lower dims represent a single input with dimensions [width, height, IFM], and an optional 4th dimension for batch of inputs. Data types supported: F32.
[in] squared_input Source with each element has been squared. 3 lower dims represent a single input with dimensions [width, height, IFM], Data types should match the input type.
[out] output Destination tensor. Output will have the same number of dimensions as input. Data types should match the input type.
[in] norm_info Normalization layer information like the normalization type, normalization size and other parameters.
Definition at line 49 of file GCNormalizationLayerKernel.cpp.
 {
     ARM_COMPUTE_ERROR_ON_DATA_TYPE_CHANNEL_NOT_IN(input, 1, DataType::F32);
     ARM_COMPUTE_ERROR_ON_MISMATCHING_DATA_TYPES(input, output);
     ARM_COMPUTE_ERROR_ON_MSG(!(norm_info.norm_size() % 2), "Normalization size should be odd");
     ARM_COMPUTE_ERROR_ON_MSG(norm_info.type() == NormType::IN_MAP_2D, "2D In-Map Normalization not implemented");
     // Set build options
     std::set<std::string> build_opts;
     _input         = input;
     _squared_input = squared_input;
     _output        = output;
     const bool         is_in_map    = norm_info.is_in_map();
     const unsigned int border_width = is_in_map ? std::min(norm_info.norm_size() / 2, 3U) : 0;
     _border_size                    = BorderSize(0, border_width);
     // Set kernel static arguments
     std::string func_name = ((norm_info.type() == NormType::IN_MAP_1D) ? "IN_MAP_1D" : "CROSS_MAP");
     build_opts.emplace(("#define " + func_name));
     build_opts.emplace(("#define COEFF " + float_to_string_with_full_precision(norm_info.scale_coeff())));
     build_opts.emplace(("#define BETA " + float_to_string_with_full_precision(norm_info.beta())));
     build_opts.emplace(("#define KAPPA " + float_to_string_with_full_precision(norm_info.kappa())));
     build_opts.emplace(("#define RADIUS " + support::cpp11::to_string(norm_info.norm_size() / 2)));
     build_opts.emplace(("#define LOCAL_SIZE_X " + support::cpp11::to_string(1)));
     build_opts.emplace(("#define LOCAL_SIZE_Y " + support::cpp11::to_string(1)));
     build_opts.emplace(("#define LOCAL_SIZE_Z " + support::cpp11::to_string(1)));
     // Create kernel
     _kernel = static_cast<GCKernel>(GCKernelLibrary::get().create_kernel("normalization_layer", build_opts));
     // Configure kernel window
     const unsigned int num_elems_processed_per_iteration = 1;
     const unsigned int num_elems_read_per_iteration      = num_elems_processed_per_iteration + 2 * (norm_info.norm_size() / 2);
     Window win = calculate_max_window(*input->info(), Steps(num_elems_processed_per_iteration));
     AccessWindowHorizontal input_access(input->info(), -_border_size.left, num_elems_read_per_iteration);
     AccessWindowHorizontal squared_input_access(squared_input->info(), -_border_size.left, num_elems_read_per_iteration);
     AccessWindowHorizontal output_access(output->info(), 0, num_elems_processed_per_iteration);
     update_window_and_padding(win, input_access, squared_input_access, output_access);
     output_access.set_valid_region(win, input->info()->valid_region());
     IGCKernel::configure(win);
 }
References ARM_COMPUTE_ERROR_ON_DATA_TYPE_CHANNEL_NOT_IN, ARM_COMPUTE_ERROR_ON_MISMATCHING_DATA_TYPES, ARM_COMPUTE_ERROR_ON_MSG, NormalizationLayerInfo::beta(), arm_compute::calculate_max_window(), arm_compute::create_kernel(), arm_compute::F32, arm_compute::float_to_string_with_full_precision(), GCKernelLibrary::get(), arm_compute::IN_MAP_1D, arm_compute::IN_MAP_2D, ITensor::info(), NormalizationLayerInfo::is_in_map(), NormalizationLayerInfo::kappa(), NormalizationLayerInfo::norm_size(), NormalizationLayerInfo::scale_coeff(), arm_compute::support::cpp11::to_string(), NormalizationLayerInfo::type(), arm_compute::U, arm_compute::update_window_and_padding(), and ITensorInfo::valid_region().
Referenced by GCNormalizationLayer::configure().
operator=() [1/2]
GCNormalizationLayerKernel& operator= (const GCNormalizationLayerKernel &) delete
Prevent instances of this class from being copied (As this class contains pointers)
operator=() [2/2]
GCNormalizationLayerKernel& operator= (GCNormalizationLayerKernel &&) default
Default move assignment operator.
run()
void run (const Window & window) override virtual
Enqueue the OpenGL ES shader to process the given window.
Parameters
[in] window Region on which to execute the kernel. (Must be a valid region of the window returned by window()).
Implements IGCKernel.
Definition at line 98 of file GCNormalizationLayerKernel.cpp.
 {
     ARM_COMPUTE_ERROR_ON_UNCONFIGURED_KERNEL(this);
     ARM_COMPUTE_ERROR_ON_INVALID_SUBWINDOW(IKernel::window(), window);
     _kernel.use();
     Window slice = window.first_slice_window_3D();
     do
     {
         unsigned int idx     = 0;
         unsigned int binding = 1;
         add_3D_tensor_argument(idx, _input, binding++, slice);
         add_3D_tensor_argument(idx, _squared_input, binding++, slice);
         add_3D_tensor_argument(idx, _output, binding++, slice);
         _kernel.update_shader_params();
         enqueue(*this, slice);
     }
     while(window.slide_window_slice_3D(slice));
 }
References IGCKernel::add_3D_tensor_argument(), ARM_COMPUTE_ERROR_ON_INVALID_SUBWINDOW, ARM_COMPUTE_ERROR_ON_UNCONFIGURED_KERNEL, arm_compute::enqueue(), Window::first_slice_window_3D(), arm_compute::test::validation::reference::slice(), Window::slide_window_slice_3D(), and IKernel::window().
The documentation for this class was generated from the following files:
arm_compute/core/GLES_COMPUTE/kernels/GCNormalizationLayerKernel.h
src/core/GLES_COMPUTE/kernels/GCNormalizationLayerKernel.cpp