Compute Library: CPPCornerCandidatesKernel Class Reference
CPPCornerCandidatesKernel Class Reference
CPP kernel to perform corner candidates.
#include <CPPCornerCandidatesKernel.h>
Public Member Functions
const char * name () const override
Name of the kernel.
CPPCornerCandidatesKernel ()
Default constructor.
CPPCornerCandidatesKernel (const CPPCornerCandidatesKernel &)=delete
Prevent instances of this class from being copied (As this class contains pointers)
CPPCornerCandidatesKernel & operator= (const CPPCornerCandidatesKernel &)=delete
Prevent instances of this class from being copied (As this class contains pointers)
CPPCornerCandidatesKernel (CPPCornerCandidatesKernel &&)=default
Allow instances of this class to be moved.
CPPCornerCandidatesKernel & operator= (CPPCornerCandidatesKernel &&)=default
Allow instances of this class to be moved.
~CPPCornerCandidatesKernel ()=default
Default destructor.
void configure (const IImage *input, InternalKeypoint *output, int32_t *num_corner_candidates)
Setup the kernel parameters.
void run (const Window &window, const ThreadInfo &info) override
Execute the kernel on the passed window.
Public Member Functions inherited from ICPPKernel
virtual ~ICPPKernel ()=default
Default destructor.
Public Member Functions inherited from IKernel
IKernel ()
Constructor.
virtual ~IKernel ()=default
Destructor.
virtual bool is_parallelisable () const
Indicates whether or not the kernel is parallelisable.
virtual BorderSize border_size () const
The size of the border for that kernel.
const Window & window () const
The maximum window the kernel can be executed on.
Detailed Description
CPP kernel to perform corner candidates.
Definition at line 41 of file CPPCornerCandidatesKernel.h.
Constructor & Destructor Documentation
CPPCornerCandidatesKernel() [1/3]
CPPCornerCandidatesKernel ()
Default constructor.
Definition at line 69 of file CPPCornerCandidatesKernel.cpp.
     : _num_corner_candidates(nullptr), _corner_candidates_mutex(), _input(nullptr), _output(nullptr)
 {
 }
CPPCornerCandidatesKernel() [2/3]
CPPCornerCandidatesKernel (const CPPCornerCandidatesKernel &) delete
Prevent instances of this class from being copied (As this class contains pointers)
CPPCornerCandidatesKernel() [3/3]
CPPCornerCandidatesKernel (CPPCornerCandidatesKernel &&) default
Allow instances of this class to be moved.
~CPPCornerCandidatesKernel()
~CPPCornerCandidatesKernel () default
Default destructor.
Member Function Documentation
configure()
void configure (const IImage * input, InternalKeypoint * output, int32_t * num_corner_candidates)
Setup the kernel parameters.
Parameters
[in] input Source image (harris score). Format supported F32
[out] output Destination array of InternalKeypoint
[out] num_corner_candidates Number of corner candidates
Definition at line 74 of file CPPCornerCandidatesKernel.cpp.
 {
     ARM_COMPUTE_ERROR_ON_TENSOR_NOT_2D(input);
     ARM_COMPUTE_ERROR_ON_DATA_TYPE_CHANNEL_NOT_IN(input, 1, DataType::F32);
     ARM_COMPUTE_ERROR_ON(nullptr == output);
     ARM_COMPUTE_ERROR_ON(nullptr == num_corner_candidates);
     ARM_COMPUTE_ERROR_ON(*num_corner_candidates != 0);
     _input                 = input;
     _output                = output;
     _num_corner_candidates = num_corner_candidates;
     const unsigned int num_elems_processed_per_iteration = 1;
     // Configure kernel window
     Window win = calculate_max_window(*input->info(), Steps(num_elems_processed_per_iteration));
     update_window_and_padding(win, AccessWindowHorizontal(input->info(), 0, num_elems_processed_per_iteration));
     INEKernel::configure(win);
 }
References ARM_COMPUTE_ERROR_ON, ARM_COMPUTE_ERROR_ON_DATA_TYPE_CHANNEL_NOT_IN, ARM_COMPUTE_ERROR_ON_TENSOR_NOT_2D, arm_compute::calculate_max_window(), arm_compute::F32, ITensor::info(), and arm_compute::update_window_and_padding().
Referenced by CLHarrisCorners::configure(), and NEHarrisCorners::configure().
name()
const char* name () const inline override virtual
Name of the kernel.
Returns
Kernel name
Implements ICPPKernel.
Definition at line 44 of file CPPCornerCandidatesKernel.h.
     {
         return "CPPCornerCandidatesKernel";
     }
operator=() [1/2]
CPPCornerCandidatesKernel& operator= (const CPPCornerCandidatesKernel &) delete
Prevent instances of this class from being copied (As this class contains pointers)
operator=() [2/2]
CPPCornerCandidatesKernel& operator= (CPPCornerCandidatesKernel &&) default
Allow instances of this class to be moved.
run()
void run (const Window & window, const ThreadInfo & info) override virtual
Execute the kernel on the passed window.
Warning
If is_parallelisable() returns false then the passed window must be equal to window()
Note
The window has to be a region within the window returned by the window() method
The width of the window has to be a multiple of num_elems_processed_per_iteration().
Parameters
[in] window Region on which to execute the kernel. (Must be a region of the window returned by window())
[in] info Info about executing thread and CPU.
Implements ICPPKernel.
Definition at line 96 of file CPPCornerCandidatesKernel.cpp.
 {
     ARM_COMPUTE_UNUSED(info);
     ARM_COMPUTE_ERROR_ON_UNCONFIGURED_KERNEL(this);
     ARM_COMPUTE_ERROR_ON_INVALID_SUBWINDOW(INEKernel::window(), window);
     Iterator input(_input, window);
     execute_window_loop(window, [&](const Coordinates & id)
     {
         corner_candidates(reinterpret_cast<float *>(input.ptr()), &_output[0], id.x(), id.y(), _num_corner_candidates, &_corner_candidates_mutex);
     },
     input);
 }
References ARM_COMPUTE_ERROR_ON_INVALID_SUBWINDOW, ARM_COMPUTE_ERROR_ON_UNCONFIGURED_KERNEL, ARM_COMPUTE_UNUSED, arm_compute::execute_window_loop(), arm_compute::test::validation::info, Iterator::ptr(), IKernel::window(), and InternalKeypoint::y.
The documentation for this class was generated from the following files:
arm_compute/core/CPP/kernels/CPPCornerCandidatesKernel.h
src/core/CPP/kernels/CPPCornerCandidatesKernel.cpp