Compute Library: NEMagnitudePhaseKernel< mag_type, phase_type > Class Template Reference
NEMagnitudePhaseKernel< mag_type, phase_type > Class Template Reference
Template interface for the kernel to compute magnitude and phase.
#include <NEMagnitudePhaseKernel.h>
Public Member Functions
const char * name () const override
Name of the kernel.
NEMagnitudePhaseKernel ()
Default constructor.
~NEMagnitudePhaseKernel ()=default
Destructor.
NEMagnitudePhaseKernel (const NEMagnitudePhaseKernel &)=delete
Prevent instances of this class from being copied (As this class contains pointers)
NEMagnitudePhaseKernel (NEMagnitudePhaseKernel &&)=default
Default move constructor.
NEMagnitudePhaseKernel & operator= (const NEMagnitudePhaseKernel &)=delete
Prevent instances of this class from being copied (As this class contains pointers)
NEMagnitudePhaseKernel & operator= (NEMagnitudePhaseKernel &&)=default
Default move assignment operator.
void configure (const ITensor *gx, const ITensor *gy, ITensor *magnitude, ITensor *phase)
Initialise the kernel's input, output.
void run (const Window &window, const ThreadInfo &info) override
Execute the kernel on the passed window.
Public Member Functions inherited from ICPPKernel
virtual ~ICPPKernel ()=default
Default destructor.
Public Member Functions inherited from IKernel
IKernel ()
Constructor.
virtual ~IKernel ()=default
Destructor.
virtual bool is_parallelisable () const
Indicates whether or not the kernel is parallelisable.
virtual BorderSize border_size () const
The size of the border for that kernel.
const Window & window () const
The maximum window the kernel can be executed on.
Detailed Description
template<MagnitudeType mag_type, PhaseType phase_type>
class arm_compute::NEMagnitudePhaseKernel< mag_type, phase_type >
Template interface for the kernel to compute magnitude and phase.
Definition at line 36 of file NEMagnitudePhaseKernel.h.
Constructor & Destructor Documentation
NEMagnitudePhaseKernel() [1/3]
NEMagnitudePhaseKernel ()
Default constructor.
Definition at line 244 of file NEMagnitudePhaseKernel.cpp.
     : _func(nullptr), _gx(nullptr), _gy(nullptr), _magnitude(nullptr), _phase(nullptr)
 {
 }
~NEMagnitudePhaseKernel()
~NEMagnitudePhaseKernel () default
Destructor.
NEMagnitudePhaseKernel() [2/3]
NEMagnitudePhaseKernel (const NEMagnitudePhaseKernel< mag_type, phase_type > &) delete
Prevent instances of this class from being copied (As this class contains pointers)
NEMagnitudePhaseKernel() [3/3]
NEMagnitudePhaseKernel (NEMagnitudePhaseKernel< mag_type, phase_type > &&) default
Default move constructor.
Member Function Documentation
configure()
void configure (const ITensor * gx, const ITensor * gy, ITensor * magnitude, ITensor * phase)
Initialise the kernel's input, output.
Note
At least one of out1 or out2 must be set
Parameters
[in] gx Gradient X tensor. Data type supported: S16.
[in] gy Gradient Y tensor. Data type supported: S16.
[out] magnitude (Optional) The output tensor - Magnitude. Data type supported: S16.
[out] phase (Optional) The output tensor - Phase. Data type supported: U8.
Definition at line 250 of file NEMagnitudePhaseKernel.cpp.
 {
     ARM_COMPUTE_ERROR_ON_DATA_TYPE_CHANNEL_NOT_IN(gx, 1, DataType::S16);
     ARM_COMPUTE_ERROR_ON_DATA_TYPE_CHANNEL_NOT_IN(gy, 1, DataType::S16);
     ARM_COMPUTE_ERROR_ON((nullptr == magnitude) && (nullptr == phase));
     const bool run_mag   = magnitude != nullptr;
     const bool run_phase = phase != nullptr;
     if(run_mag)
     {
         ARM_COMPUTE_ERROR_ON_DATA_TYPE_CHANNEL_NOT_IN(magnitude, 1, DataType::S16);
     }
     if(run_phase)
     {
         ARM_COMPUTE_ERROR_ON_DATA_TYPE_CHANNEL_NOT_IN(phase, 1, DataType::U8);
     }
     _gx        = gx;
     _gy        = gy;
     _magnitude = magnitude;
     _phase     = phase;
     if(run_mag && run_phase)
     {
         /* Run magnitude and phase */
         _func = &NEMagnitudePhaseKernel<mag_type, phase_type>::magnitude_phase;
     }
     else
     {
         if(run_mag)
         {
             /* Run magnitude */
             _func = &NEMagnitudePhaseKernel<mag_type, phase_type>::magnitude;
         }
         else if(run_phase)
         {
             /* Run phase */
             _func = &NEMagnitudePhaseKernel<mag_type, phase_type>::phase;
         }
         else
         {
             ARM_COMPUTE_ERROR("At least one output must be NOT NULL");
         }
     }
     constexpr unsigned int num_elems_processed_per_iteration = 16;
     // Configure kernel window
     Window                 win = calculate_max_window(*gx->info(), Steps(num_elems_processed_per_iteration));
     AccessWindowHorizontal magnitude_access(magnitude == nullptr ? nullptr : magnitude->info(), 0, num_elems_processed_per_iteration);
     AccessWindowHorizontal phase_access(phase == nullptr ? nullptr : phase->info(), 0, num_elems_processed_per_iteration);
     update_window_and_padding(win,
                               AccessWindowHorizontal(gx->info(), 0, num_elems_processed_per_iteration),
                               AccessWindowHorizontal(gy->info(), 0, num_elems_processed_per_iteration),
                               magnitude_access,
                               phase_access);
     ValidRegion valid_region = intersect_valid_regions(gx->info()->valid_region(),
                                                        gy->info()->valid_region());
     magnitude_access.set_valid_region(win, valid_region);
     phase_access.set_valid_region(win, valid_region);
     INEKernel::configure(win);
 }
References ARM_COMPUTE_ERROR, ARM_COMPUTE_ERROR_ON, ARM_COMPUTE_ERROR_ON_DATA_TYPE_CHANNEL_NOT_IN, arm_compute::calculate_max_window(), ITensor::info(), arm_compute::intersect_valid_regions(), arm_compute::test::validation::reference::magnitude(), arm_compute::test::validation::reference::phase(), arm_compute::S16, arm_compute::U8, arm_compute::update_window_and_padding(), arm_compute::test::validation::valid_region, and ITensorInfo::valid_region().
name()
const char* name () const inline override virtual
Name of the kernel.
Returns
Kernel name
Implements ICPPKernel.
Definition at line 39 of file NEMagnitudePhaseKernel.h.
     {
         return "NEMagnitudePhaseKernel";
     }
operator=() [1/2]
NEMagnitudePhaseKernel& operator= (const NEMagnitudePhaseKernel< mag_type, phase_type > &) delete
Prevent instances of this class from being copied (As this class contains pointers)
operator=() [2/2]
NEMagnitudePhaseKernel& operator= (NEMagnitudePhaseKernel< mag_type, phase_type > &&) default
Default move assignment operator.
run()
void run (const Window & window, const ThreadInfo & info) override virtual
Execute the kernel on the passed window.
Warning
If is_parallelisable() returns false then the passed window must be equal to window()
Note
The window has to be a region within the window returned by the window() method
The width of the window has to be a multiple of num_elems_processed_per_iteration().
Parameters
[in] window Region on which to execute the kernel. (Must be a region of the window returned by window())
[in] info Info about executing thread and CPU.
Implements ICPPKernel.
Definition at line 475 of file NEMagnitudePhaseKernel.cpp.
 {
     ARM_COMPUTE_UNUSED(info);
     ARM_COMPUTE_ERROR_ON_UNCONFIGURED_KERNEL(this);
     ARM_COMPUTE_ERROR_ON_INVALID_SUBWINDOW(INEKernel::window(), window);
     ARM_COMPUTE_ERROR_ON(_func == nullptr);
     (this->*_func)(window);
 }
References ARM_COMPUTE_ERROR_ON, ARM_COMPUTE_ERROR_ON_INVALID_SUBWINDOW, ARM_COMPUTE_ERROR_ON_UNCONFIGURED_KERNEL, ARM_COMPUTE_UNUSED, arm_compute::test::validation::info, and IKernel::window().
The documentation for this class was generated from the following files:
arm_compute/core/NEON/kernels/NEMagnitudePhaseKernel.h
src/core/NEON/kernels/NEMagnitudePhaseKernel.cpp