Compute Library: NEFastCornersKernel Class Reference
NEFastCornersKernel Class Reference
NEON kernel to perform fast corners.
#include <NEFastCornersKernel.h>
Public Member Functions
const char * name () const override
Name of the kernel.
NEFastCornersKernel ()
Constructor.
NEFastCornersKernel (const NEFastCornersKernel &)=delete
Prevent instances of this class from being copied (As this class contains pointers)
NEFastCornersKernel & operator= (const NEFastCornersKernel &)=delete
Prevent instances of this class from being copied (As this class contains pointers)
NEFastCornersKernel (NEFastCornersKernel &&)=default
Allow instances of this class to be moved.
NEFastCornersKernel & operator= (NEFastCornersKernel &&)=default
Allow instances of this class to be moved.
void configure (const IImage *input, IImage *output, uint8_t threshold, bool non_max_suppression, bool border_undefined)
Initialise the kernel.
void run (const Window &window, const ThreadInfo &info) override
Execute the kernel on the passed window.
BorderSize border_size () const override
The size of the border for that kernel.
Public Member Functions inherited from ICPPKernel
virtual ~ICPPKernel ()=default
Default destructor.
Public Member Functions inherited from IKernel
IKernel ()
Constructor.
virtual ~IKernel ()=default
Destructor.
virtual bool is_parallelisable () const
Indicates whether or not the kernel is parallelisable.
const Window & window () const
The maximum window the kernel can be executed on.
Detailed Description
NEON kernel to perform fast corners.
Definition at line 38 of file NEFastCornersKernel.h.
Constructor & Destructor Documentation
NEFastCornersKernel() [1/3]
NEFastCornersKernel ()
Constructor.
Definition at line 38 of file NEFastCornersKernel.cpp.
     : INEKernel(), _input(nullptr), _output(nullptr), _threshold(0), _non_max_suppression(false)
 {
 }
NEFastCornersKernel() [2/3]
NEFastCornersKernel (const NEFastCornersKernel &) delete
Prevent instances of this class from being copied (As this class contains pointers)
NEFastCornersKernel() [3/3]
NEFastCornersKernel (NEFastCornersKernel &&) default
Allow instances of this class to be moved.
Member Function Documentation
border_size()
BorderSize border_size () const override virtual
The size of the border for that kernel.
Returns
The width in number of elements of the border.
Reimplemented from IKernel.
Definition at line 354 of file NEFastCornersKernel.cpp.
 {
     return BorderSize(3);
 }
Referenced by NEFastCornersKernel::configure(), and NEFastCorners::configure().
configure()
void configure (const IImage * input, IImage * output, uint8_t threshold, bool non_max_suppression, bool border_undefined)
Initialise the kernel.
Parameters
[in] input Source image. Data type supported: U8.
[out] output Output image. Data type supported: U8.
[in] threshold Threshold on difference between intensity of the central pixel and pixels on Bresenham's circle of radius 3.
[in] non_max_suppression True if non-maxima suppresion is applied, false otherwise.
[in] border_undefined True if the border mode is undefined. False if it's replicate or constant.
Definition at line 359 of file NEFastCornersKernel.cpp.
 {
     ARM_COMPUTE_ERROR_ON_TENSOR_NOT_2D(input);
     ARM_COMPUTE_ERROR_ON_TENSOR_NOT_2D(output);
     ARM_COMPUTE_ERROR_ON_DATA_TYPE_CHANNEL_NOT_IN(input, 1, DataType::U8);
     ARM_COMPUTE_ERROR_ON_DATA_TYPE_CHANNEL_NOT_IN(output, 1, DataType::U8);
     ARM_COMPUTE_ERROR_ON_MSG(border_undefined == false, "Not implemented");
     _input               = input;
     _output              = output;
     _threshold           = threshold;
     _non_max_suppression = non_max_suppression;
     constexpr unsigned int num_elems_processed_per_iteration = 1;
     constexpr unsigned int num_elems_read_per_iteration      = 8;
     constexpr unsigned int num_elems_written_per_iteration   = 1;
     constexpr unsigned int num_rows_read_per_iteration       = 7;
     // Configure kernel window
     Window                 win = calculate_max_window(*input->info(), Steps(num_elems_processed_per_iteration), border_undefined, border_size());
     AccessWindowHorizontal output_access(output->info(), 0, num_elems_written_per_iteration);
     AccessWindowRectangle  input_access(input->info(), -border_size().left, -border_size().top, num_elems_read_per_iteration, num_rows_read_per_iteration);
     update_window_and_padding(win, input_access, output_access);
     output_access.set_valid_region(win, input->info()->valid_region(), border_undefined, border_size());
     INEKernel::configure(win);
 }
References ARM_COMPUTE_ERROR_ON_DATA_TYPE_CHANNEL_NOT_IN, ARM_COMPUTE_ERROR_ON_MSG, ARM_COMPUTE_ERROR_ON_TENSOR_NOT_2D, NEFastCornersKernel::border_size(), arm_compute::calculate_max_window(), ITensor::info(), BorderSize::left, non_max_suppression(), arm_compute::test::validation::reference::threshold(), BorderSize::top, arm_compute::U8, arm_compute::update_window_and_padding(), and ITensorInfo::valid_region().
Referenced by NEFastCorners::configure().
name()
const char* name () const inline override virtual
Name of the kernel.
Returns
Kernel name
Implements ICPPKernel.
Definition at line 41 of file NEFastCornersKernel.h.
     {
         return "NEFastCornersKernel";
     }
operator=() [1/2]
NEFastCornersKernel& operator= (const NEFastCornersKernel &) delete
Prevent instances of this class from being copied (As this class contains pointers)
operator=() [2/2]
NEFastCornersKernel& operator= (NEFastCornersKernel &&) default
Allow instances of this class to be moved.
run()
void run (const Window & window, const ThreadInfo & info) override virtual
Execute the kernel on the passed window.
Warning
If is_parallelisable() returns false then the passed window must be equal to window()
Note
The window has to be a region within the window returned by the window() method
The width of the window has to be a multiple of num_elems_processed_per_iteration().
Parameters
[in] window Region on which to execute the kernel. (Must be a region of the window returned by window())
[in] info Info about executing thread and CPU.
Implements ICPPKernel.
Definition at line 389 of file NEFastCornersKernel.cpp.
 {
     ARM_COMPUTE_UNUSED(info);
     ARM_COMPUTE_ERROR_ON_UNCONFIGURED_KERNEL(this);
     ARM_COMPUTE_ERROR_ON_INVALID_SUBWINDOW(INEKernel::window(), window);
     std::array<uint8x8x2_t, PERMUTATIONS> perm_index{ {} };
     /*
         We use a LUT loaded with 7 rows of uint8_t from the input image [-3,-3]...[+3,+3] to retrieve the texels in the Brensenham circle radius 3 and put them in one neon register uint8x16_t.
         The three lines below setup the neon index registers to get these texels out from the table
     */
     const uint8x8x4_t circle_index_r = create_circle_index_register();
     /*
         We put the 16 texels (circle) in a LUT to easily generate all the permutations. The for block below setups the indices for each permutation.
     */
     for(size_t k = 0; k < PERMUTATIONS; ++k)
     {
         perm_index[k] = create_permutation_index(k);
     }
     Iterator in(_input, window);
     Iterator out(_output, window);
     const std::array<uint8_t *const __restrict, 7> in_row
     {
         _input->ptr_to_element(Coordinates(-3, -3)),
         _input->ptr_to_element(Coordinates(-3, -2)),
         _input->ptr_to_element(Coordinates(-3, -1)),
         _input->ptr_to_element(Coordinates(-3, 0)),
         _input->ptr_to_element(Coordinates(-3, 1)),
         _input->ptr_to_element(Coordinates(-3, 2)),
         _input->ptr_to_element(Coordinates(-3, 3))
     };
     auto is_rejected = [](uint8_t p, uint8_t q, uint8_t a, uint8_t b)
     {
         const bool p_is_in_ab = (a <= p) && (p <= b);
         const bool q_is_in_ab = (a <= q) && (q <= b);
         return p_is_in_ab && q_is_in_ab;
     };
     execute_window_loop(window, [&](const Coordinates &)
     {
         const size_t  in_offset = in.offset();
         const uint8_t p0        = *in.ptr();
         const uint8_t b         = std::min(p0 + _threshold, 255);
         const uint8_t a         = std::max(p0 - _threshold, 0);
         uint8_t       score     = 0;
         /*
             Fast check to discard points which cannot be corners and avoid the expensive computation of the potential 16 permutations
             pixels 1 and 9 are examined, if both I1 and I9 are within [Ip - t, Ip + t], then candidate p is not a corner.
         */
         const uint8_t p1 = (in_offset + in_row[0])[3];
         const uint8_t p9 = (in_offset + in_row[6])[3];
         if(!is_rejected(p1, p9, a, b))
         {
             /* pixels 5 and 13 are further examined to check whether three of them are brighter than Ip + t or darker than Ip - t */
             const uint8_t p5  = (in_offset + in_row[3])[6];
             const uint8_t p13 = (in_offset + in_row[3])[0];
             if(!is_rejected(p5, p13, a, b))
             {
                 /* at this stage we use the full test with the 16 permutations to classify the point as corner or not */
                 const uint8x8x2_t tbl_circle_texel = create_circle_tbl(in_row, in_offset, circle_index_r);
                 if(point_is_fast_corner(p0, _threshold, tbl_circle_texel, perm_index))
                 {
                     if(_non_max_suppression)
                     {
                         score = get_point_score(p0, _threshold, tbl_circle_texel, perm_index);
                     }
                     else
                     {
                         score = 1;
                     }
                 }
             }
         }
         *out.ptr() = score;
     },
     in, out);
 }
References ARM_COMPUTE_ERROR_ON_INVALID_SUBWINDOW, ARM_COMPUTE_ERROR_ON_UNCONFIGURED_KERNEL, ARM_COMPUTE_UNUSED, arm_compute::test::validation::b, arm_compute::execute_window_loop(), arm_compute::test::validation::info, Iterator::offset(), Iterator::ptr(), ITensor::ptr_to_element(), and IKernel::window().
The documentation for this class was generated from the following files:
arm_compute/core/NEON/kernels/NEFastCornersKernel.h
src/core/NEON/kernels/NEFastCornersKernel.cpp