Compute Library: TestFilter Class Reference
TestFilter Class Reference final
Test filter class.
#include <TestFilter.h>
Public Member Functions
TestFilter ()=default
Default constructor.
TestFilter (DatasetMode mode, const std::string &name_filter, const std::string &id_filter)
Constructor.
bool is_selected (const TestInfo &info) const
Check if a test case is selected to be executed.
Detailed Description
Test filter class.
Stores information about which test cases are selected for execution. Based on test name and test id.
Definition at line 46 of file TestFilter.h.
Constructor & Destructor Documentation
TestFilter() [1/2]
TestFilter () default
Default constructor.
All tests selected.
TestFilter() [2/2]
TestFilter (DatasetMode mode, const std::string & name_filter, const std::string & id_filter)
Constructor.
The id_filter string has be a comma separated list of test ids. ... can be used to include a range of tests. For instance, "..., 15" means all test up to and including 15, "3, 6, ..., 10" means tests 3 and 6 to 10, and "15, ..." means test 15 and all following.
Parameters
[in] mode Dataset mode.
[in] name_filter Regular expression to filter tests by name. Only matching tests will be executed.
[in] id_filter String to match selected test ids. Only matching tests will be executed.
Definition at line 38 of file TestFilter.cpp.
     : _dataset_mode{ mode }, _name_filter{ name_filter }, _id_filter{ parse_id_filter(id_filter) }
 {
 }
Member Function Documentation
is_selected()
bool is_selected (const TestInfo & info) const
Check if a test case is selected to be executed.
Parameters
[in] info Test case info.
Returns
True if the test case is selected to be executed.
Definition at line 43 of file TestFilter.cpp.
 {
     const bool include_disabled = (info.mode == _dataset_mode) && (_dataset_mode == DatasetMode::DISABLED);
     if((info.mode & _dataset_mode) == DatasetMode::DISABLED && !include_disabled)
     {
         return false;
     }
     if(!std::regex_search(info.name, _name_filter))
     {
         return false;
     }
     if(!_id_filter.empty())
     {
         bool found = false;
         for(const auto range : _id_filter)
         {
             if(range.first <= info.id && info.id <= range.second)
             {
                 found = true;
                 break;
             }
         }
         if(!found)
         {
             return false;
         }
     }
     return true;
 }
References arm_compute::test::framework::DISABLED, arm_compute::test::validation::info, and arm_compute::test::validation::reference::range().
Referenced by Framework::run(), and Framework::test_infos().
The documentation for this class was generated from the following files:
tests/framework/TestFilter.h
tests/framework/TestFilter.cpp