Compute Library: GCGEMM Class Reference
GCGEMM Class Reference
Basic function to execute GEMM on OpenGLES Compute.
#include <GCGEMM.h>
Public Member Functions
GCGEMM (std::shared_ptr< IMemoryManager > memory_manager=nullptr)
Default constructor.
GCGEMM (const GCGEMM &)=delete
Prevent instances of this class from being copied (As this class contains pointers)
GCGEMM (GCGEMM &&)=default
Default move constructor.
GCGEMM & operator= (const GCGEMM &)=delete
Prevent instances of this class from being copied (As this class contains pointers)
GCGEMM & operator= (GCGEMM &&)=default
Default move assignment operator.
void configure (const IGCTensor *a, const IGCTensor *b, const IGCTensor *c, IGCTensor *output, float alpha, float beta, const GEMMInfo &gemm_info=GEMMInfo())
Initialise the kernel's inputs and output.
void run () override
Run the kernels contained in the function.
void prepare () override
Prepare the function for executing.
Public Member Functions inherited from IFunction
virtual ~IFunction ()=default
Destructor.
Static Public Member Functions
static Status validate (const ITensorInfo *a, const ITensorInfo *b, const IGCTensor *c, const ITensorInfo *output, const float alpha, const float beta, const GEMMInfo &gemm_info=GEMMInfo())
Static function to check if given info will lead to a valid configuration of GCGEMM.
Detailed Description
Basic function to execute GEMM on OpenGLES Compute.
This function calls the following kernels:
GCGEMMInterleave4x4Kernel (if the output tensor is a matrix)
GCGEMMTranspose1xWKernel (if the output tensor is a matrix)
GCGEMMMatrixMultiplyKernel
GCGEMMMatrixAdditionKernel (if c != nullptr and beta != 0.0)
Definition at line 48 of file GCGEMM.h.
Constructor & Destructor Documentation
GCGEMM() [1/3]
GCGEMM (std::shared_ptr< IMemoryManager > memory_manager = nullptr)
Default constructor.
Definition at line 75 of file GCGEMM.cpp.
     : _memory_group(std::move(memory_manager)), _interleave_kernel(), _transpose_kernel(), _mm_kernel(), _ma_kernel(), _tmp_a(), _tmp_b(), _original_b(nullptr), _is_interleaved_transposed(false),
       _run_addition(false), _reshape_b_only_on_first_run(false), _is_prepared(false)
 {
 }
GCGEMM() [2/3]
GCGEMM (const GCGEMM &) delete
Prevent instances of this class from being copied (As this class contains pointers)
GCGEMM() [3/3]
GCGEMM (GCGEMM &&) default
Default move constructor.
Member Function Documentation
configure()
void configure (const IGCTensor * a, const IGCTensor * b, const IGCTensor * c, IGCTensor * output, float alpha, float beta, const GEMMInfo & gemm_info = GEMMInfo())
Initialise the kernel's inputs and output.
Note
GEMM: General Matrix Multiply - [alpha * A * B + beta * C].
All tensors must have the same data type.
Whilst the first input tensor can be a vector, the second input tensor must be at least a matrix
Parameters
[in] a First input tensor (Matrix or Vector A). Data types supported: F32
[in] b Second input tensor (Matrix B). Data type supported: same as a.
[in] c Third input tensor (Matrix C). It can be a nullptr if just the multiplication between a and b is needed. Data type supported: same as a.
[out] output Output tensor. Data type supported: same as a
[in] alpha Weight of the matrix product
[in] beta Weight of matrix C
[in] gemm_info (Optional) Specifies if the matrix A and/or matrix B have been reshaped and if the reshape of matrix B should happen only for the first run
Definition at line 81 of file GCGEMM.cpp.
 {
     ARM_COMPUTE_ERROR_ON_NULLPTR(a, b, output);
     // Perform validation step
     ARM_COMPUTE_ERROR_THROW_ON(validate_arguments(a->info(), b->info(), c, output->info(), alpha, beta, gemm_info));
     // Check if we need to reshape the matrix B only on the first run
     _reshape_b_only_on_first_run = gemm_info.reshape_b_only_on_first_run();
     _is_prepared                 = false;
     _original_b                  = b;
     const IGCTensor *matrix_a = a;
     const IGCTensor *matrix_b = b;
     // Get the GPU target
     const GPUTarget gpu_target = GCScheduler::get().get_target();
     // Set the target for the kernels
     _interleave_kernel.set_target(gpu_target);
     _mm_kernel.set_target(gpu_target);
     // Arguments used by GEMMReshapeInfo
     // If we pass the matrix A and matrix B reshaped to GCGEMMMatrixMultiplyKernel, we need to pass m, n, k, mult_transpose1xW_width and mult_interleave4x4_height to GCGEMMReshapeInfo
     // in order to know how the matrices have been reshaped
     const int m                         = a->info()->dimension(1);
     const int n                         = b->info()->dimension(0);
     const int k                         = a->info()->dimension(0);
     int       mult_transpose1xW_width   = 1;
     int       mult_interleave4x4_height = 1;
     // If the input tensor has less than 16 rows, we run a special version of GEMM without reshaping the input tensors
     _is_interleaved_transposed = a->info()->dimension(1) > 16;
     if(_is_interleaved_transposed)
     {
         matrix_a = &_tmp_a;
         matrix_b = &_tmp_b;
         // Manage intermediate buffers
         _memory_group.manage(&_tmp_a);
         if(!_reshape_b_only_on_first_run)
         {
             _memory_group.manage(&_tmp_b);
         }
         // _tmp_a and _tmp_b will be auto configured in _interleave_kernel and in _transpose_kernel
         // Configure interleave kernel
         _interleave_kernel.configure(a, &_tmp_a);
         // Configure transpose kernel
         _transpose_kernel.configure(b, &_tmp_b);
     }
     _mm_kernel.configure(matrix_a, matrix_b, output, alpha, _is_interleaved_transposed, GEMMReshapeInfo(m, n, k, mult_transpose1xW_width, mult_interleave4x4_height));
     if(_is_interleaved_transposed)
     {
         // Allocate intermediate tensors
         _tmp_a.allocator()->allocate();
         if(!_reshape_b_only_on_first_run)
         {
             _tmp_b.allocator()->allocate();
         }
     }
     // Configure matrix addition kernel
     if(beta != 0 && c != nullptr)
     {
         _ma_kernel.configure(c, output, beta);
         _run_addition = true;
     }
 }
References ITensorAllocator::allocate(), GCTensor::allocator(), arm_compute::test::validation::alpha, ARM_COMPUTE_ERROR_ON_NULLPTR, ARM_COMPUTE_ERROR_THROW_ON, arm_compute::test::validation::b, GCGEMMMatrixAdditionKernel::configure(), GCGEMMTranspose1xWKernel::configure(), GCGEMMMatrixMultiplyKernel::configure(), GCGEMMInterleave4x4Kernel::configure(), ITensorInfo::dimension(), GCScheduler::get(), GCScheduler::get_target(), ITensor::info(), MemoryGroupBase< TensorType >::manage(), GEMMInfo::reshape_b_only_on_first_run(), and IGCKernel::set_target().
operator=() [1/2]
GCGEMM& operator= (const GCGEMM &) delete
Prevent instances of this class from being copied (As this class contains pointers)
operator=() [2/2]
GCGEMM& operator= (GCGEMM &&) default
Default move assignment operator.
prepare()
void prepare () override virtual
Prepare the function for executing.
Any one off pre-processing step required by the function is handled here
Note
Prepare stage might not need all the function's buffers' backing memory to be available in order to execute
Reimplemented from IFunction.
Definition at line 192 of file GCGEMM.cpp.
 {
     if(!_is_prepared)
     {
         if(_is_interleaved_transposed && _reshape_b_only_on_first_run)
         {
             ARM_COMPUTE_ERROR_ON(!_original_b->is_used());
             // Run transpose kernel
             _tmp_b.allocator()->allocate();
             GCScheduler::get().dispatch(_transpose_kernel, false);
             GCScheduler::get().memory_barrier();
             // Mark original weights tensor as unused
             _original_b->mark_as_unused();
         }
         _is_prepared = true;
     }
 }
References ITensorAllocator::allocate(), GCTensor::allocator(), ARM_COMPUTE_ERROR_ON, GCScheduler::dispatch(), GCScheduler::get(), ITensor::is_used(), ITensor::mark_as_unused(), and GCScheduler::memory_barrier().
Referenced by GCGEMM::run().
run()
void run () override virtual
Run the kernels contained in the function.
For NEON kernels:
Multi-threading is used for the kernels which are parallelisable.
By default std::thread::hardware_concurrency() threads are used.
Note
CPPScheduler::set_num_threads() can be used to manually set the number of threads
For OpenCL kernels:
All the kernels are enqueued on the queue associated with CLScheduler.
The queue is then flushed.
Note
The function will not block until the kernels are executed. It is the user's responsibility to wait.
Will call prepare() on first run if hasn't been done
Implements IFunction.
Definition at line 161 of file GCGEMM.cpp.
 {
     prepare();
     MemoryGroupResourceScope scope_mg(_memory_group);
     if(_is_interleaved_transposed)
     {
         // Run interleave kernel
         GCScheduler::get().dispatch(_interleave_kernel, false);
         if(!_reshape_b_only_on_first_run)
         {
             // Run transpose kernel
             GCScheduler::get().dispatch(_transpose_kernel, false);
         }
         GCScheduler::get().memory_barrier();
     }
     // Run matrix multiply kernel
     GCScheduler::get().dispatch(_mm_kernel, !_run_addition);
     // Run matrix addition kernel
     if(_run_addition)
     {
         GCScheduler::get().memory_barrier();
         GCScheduler::get().dispatch(_ma_kernel);
     }
 }
References GCScheduler::dispatch(), GCScheduler::get(), GCScheduler::memory_barrier(), and GCGEMM::prepare().
Referenced by GCConvolutionLayer::run().
validate()
Status validate (const ITensorInfo * a, const ITensorInfo * b, const IGCTensor * c, const ITensorInfo * output, const float alpha, const float beta, const GEMMInfo & gemm_info = GEMMInfo()) static
Static function to check if given info will lead to a valid configuration of GCGEMM.
Parameters
[in] a First input tensor (Matrix or Vector A). Data types supported: F16/F32
[in] b Second input tensor (Matrix B). Data type supported: same as a.
[in] c Third input tensor (Matrix C). It can be a nullptr if just the multiplication between a and b is needed. Data type supported: same as a.
[out] output Output tensor. Data type supported: same as a
[in] alpha Weight of the matrix product
[in] beta Weight of matrix C
[in] gemm_info (Optional) Specifies if the matrix A and/or matrix B have been reshaped and if the reshape of matrix B should happen only for the first run
Returns
a status
Definition at line 155 of file GCGEMM.cpp.
 {
     ARM_COMPUTE_RETURN_ON_ERROR(validate_arguments(a, b, c, output, alpha, beta, gemm_info));
     return Status{};
 }
References arm_compute::test::validation::alpha, ARM_COMPUTE_RETURN_ON_ERROR, and arm_compute::test::validation::b.
The documentation for this class was generated from the following files:
arm_compute/runtime/GLES_COMPUTE/functions/GCGEMM.h
src/runtime/GLES_COMPUTE/functions/GCGEMM.cpp