Compute Library: IWeightsManager Class Reference
IWeightsManager Class Reference
Weights manager interface to handle weights transformations.
#include <IWeightsManager.h>
Public Member Functions
IWeightsManager ()
Constructor.
virtual ~IWeightsManager ()=default
Default Destructor.
IWeightsManager (const IWeightsManager &)=delete
Prevent instances of this class to be copy constructed.
IWeightsManager & operator= (const IWeightsManager &)=delete
Prevent instances of this class to be copied.
IWeightsManager (IWeightsManager &&)=default
Allow instances of this class to be move constructed.
IWeightsManager & operator= (IWeightsManager &&)=default
Allow instances of this class to be moved.
void manage (const ITensor *weights, ITransformWeights *parent=nullptr)
Start managing a weights tensor.
ITensor * run (const ITensor *weights, ITransformWeights *weights_transform)
Run the reshape function.
ITensor * acquire (const ITensor *weights, ITransformWeights *weights_transform)
Acquire the requested reshape tensor of the selected weights.
bool are_weights_managed (const ITensor *weights)
Check if the weights are managed.
Detailed Description
Weights manager interface to handle weights transformations.
Definition at line 36 of file IWeightsManager.h.
Constructor & Destructor Documentation
IWeightsManager() [1/3]
IWeightsManager ()
Constructor.
Definition at line 28 of file IWeightsManager.cpp.
     : _managed_weights(), _managed_weights_parents()
 {
 }
~IWeightsManager()
virtual ~IWeightsManager () virtual default
Default Destructor.
IWeightsManager() [2/3]
IWeightsManager (const IWeightsManager &) delete
Prevent instances of this class to be copy constructed.
IWeightsManager() [3/3]
IWeightsManager (IWeightsManager &&) default
Allow instances of this class to be move constructed.
Member Function Documentation
acquire()
ITensor * acquire (const ITensor * weights, ITransformWeights * weights_transform)
Acquire the requested reshape tensor of the selected weights.
Parameters
[in] weights Pointer to the weights tensor to be managed
[in] weights_transform Weights transformation object
Definition at line 117 of file IWeightsManager.cpp.
 {
     ARM_COMPUTE_ERROR_ON_MSG(!are_weights_managed(weights), "Cannot acquire weights. Weights are not managed");
     ITensor *transformed_weights{ nullptr };
     auto     item = _managed_weights.find(weights);
     // Check if I already have the requested transform. If I do,
     // increase the refcount of the transformed weights object and
     // reuse the tensor
     for(auto it : item->second)
     {
         if(it->uid() == weights_transform->uid())
         {
             transformed_weights = it->get_weights();
             it->increase_refcount();
             break;
         }
     }
     if(transformed_weights == nullptr)
     {
         transformed_weights = weights_transform->get_weights();
         weights_transform->increase_refcount();
         item->second.emplace_back(weights_transform);
     }
     // Manage the weights and store link to the parent node
     manage(transformed_weights, weights_transform);
     return transformed_weights;
 }
References IWeightsManager::are_weights_managed(), ARM_COMPUTE_ERROR_ON_MSG, ITransformWeights::get_weights(), ITransformWeights::increase_refcount(), IWeightsManager::manage(), ITransformWeights::uid(), and arm_compute::test::validation::weights.
Referenced by NEFullyConnectedLayer::configure(), CLFullyConnectedLayer::configure(), NEGEMMConvolutionLayer::configure(), and CLGEMMConvolutionLayer::configure().
are_weights_managed()
bool are_weights_managed (const ITensor * weights)
Check if the weights are managed.
Parameters
[in] weights Pointer to the weights tensor we want to check if managed
Returns
True if the weights tensor is managed else false
Definition at line 112 of file IWeightsManager.cpp.
 {
     return (_managed_weights.find(weights) != _managed_weights.end());
 }
References arm_compute::test::validation::weights.
Referenced by IWeightsManager::acquire(), NEFullyConnectedLayer::configure(), CLFullyConnectedLayer::configure(), NEGEMMConvolutionLayer::configure(), CLGEMMConvolutionLayer::configure(), IWeightsManager::manage(), NEGEMM::prepare(), CLGEMM::prepare(), NEFullyConnectedLayer::prepare(), CLFullyConnectedLayer::prepare(), NEGEMMConvolutionLayer::prepare(), CLGEMMConvolutionLayer::prepare(), IWeightsManager::run(), and CLGEMM::run().
manage()
void manage (const ITensor * weights, ITransformWeights * parent = nullptr)
Start managing a weights tensor.
Parameters
[in] weights Pointer to the weights tensor to be managed
[in] parent Parent node in case where the weights are coming from a previous reshape function
Definition at line 33 of file IWeightsManager.cpp.
 {
     if(!are_weights_managed(weights))
     {
         _managed_weights[weights];
     }
     // In case the weights are an output of a previous reshape function
     // store the parent's link
     if(parent != nullptr)
     {
         if(_managed_weights_parents.find(weights) == _managed_weights_parents.end())
         {
             _managed_weights_parents[weights] = parent;
         }
     }
 }
References IWeightsManager::are_weights_managed(), and arm_compute::test::validation::weights.
Referenced by IWeightsManager::acquire(), NEFullyConnectedLayer::configure(), and CLFullyConnectedLayer::configure().
operator=() [1/2]
IWeightsManager& operator= (const IWeightsManager &) delete
Prevent instances of this class to be copied.
operator=() [2/2]
IWeightsManager& operator= (IWeightsManager &&) default
Allow instances of this class to be moved.
run()
ITensor * run (const ITensor * weights, ITransformWeights * weights_transform)
Run the reshape function.
Parameters
[in] weights Pointer to the weights tensor we want to reshape
[in] weights_transform Weights transformation object
Returns
The reshaped tensor
Definition at line 51 of file IWeightsManager.cpp.
 {
     ARM_COMPUTE_ERROR_ON_MSG(!are_weights_managed(weights), "Cannot run function. Weights are not managed");
     // Find if I have the same weights with weights transform. If I do, don't run the reshape
     auto     item = _managed_weights.find(weights);
     bool     perform_run{ true };
     ITensor *weights_tensor{ nullptr };
     // Check if I already have the requested transform and I have run the reshape function
     for(auto it : item->second)
     {
         if(it->is_reshape_run() && (it->uid() == weights_transform->uid()))
         {
             weights_tensor = it->get_weights();
             perform_run    = false;
             break;
         }
     }
     if(perform_run)
     {
         weights_transform->run();
         weights_tensor = weights_transform->get_weights();
     }
     // Check if we can release memory from parent
     auto parent_item = _managed_weights_parents.find(weights);
     if(parent_item != _managed_weights_parents.end())
     {
         int32_t refcount = parent_item->second->decrease_refcount();
         if(refcount == 0)
         {
             parent_item->second->release();
         }
     }
     // Check top level weights. If all the transformations are done
     // mark the weights as unused
     if(_managed_weights_parents.find(weights) == _managed_weights_parents.end())
     {
         auto item           = _managed_weights.find(weights);
         bool mark_as_unused = true;
         for(auto it : item->second)
         {
             if(!it->is_reshape_run())
             {
                 mark_as_unused = false;
                 break;
             }
         }
         if(mark_as_unused)
         {
             weights->mark_as_unused();
         }
     }
     return weights_tensor;
 }
References IWeightsManager::are_weights_managed(), ARM_COMPUTE_ERROR_ON_MSG, ITransformWeights::get_weights(), ITensor::mark_as_unused(), ITransformWeights::run(), ITransformWeights::uid(), and arm_compute::test::validation::weights.
Referenced by CLGEMM::prepare(), NEFullyConnectedLayer::prepare(), CLFullyConnectedLayer::prepare(), NEGEMMConvolutionLayer::prepare(), CLGEMMConvolutionLayer::prepare(), and CLGEMM::run().
The documentation for this class was generated from the following files:
arm_compute/runtime/IWeightsManager.h
src/runtime/IWeightsManager.cpp