Compute Library: OMPScheduler Class Reference
OMPScheduler Class Reference
Pool of threads to automatically split a kernel's execution among several threads.
#include <OMPScheduler.h>
Public Member Functions
void set_num_threads (unsigned int num_threads) override
Sets the number of threads the scheduler will use to run the kernels.
unsigned int num_threads () const override
Returns the number of threads that the OMPScheduler has in its pool.
void schedule (ICPPKernel *kernel, const Hints &hints) override
Multithread the execution of the passed kernel if possible.
Public Member Functions inherited from IScheduler
IScheduler ()
Default constructor.
virtual ~IScheduler ()=default
Destructor.
virtual void run_tagged_workloads (std::vector< Workload > &workloads, const char *tag)
Execute all the passed workloads.
CPUInfo & cpu_info ()
Get CPU info.
unsigned int num_threads_hint () const
Get a hint for the best possible number of execution threads.
Static Public Member Functions
static OMPScheduler & get ()
Access the scheduler singleton.
Additional Inherited Members
Public Types inherited from IScheduler
enum StrategyHint { STATIC, DYNAMIC }
Strategies available to split a workload.
using Workload = std::function< void(const ThreadInfo &)>
Signature for the workloads to execute.
Detailed Description
Pool of threads to automatically split a kernel's execution among several threads.
Definition at line 32 of file OMPScheduler.h.
Member Function Documentation
get()
OMPScheduler & get () static
Access the scheduler singleton.
Returns
The scheduler
Definition at line 36 of file OMPScheduler.cpp.
 {
     static OMPScheduler scheduler;
     return scheduler;
 }
Referenced by Scheduler::get().
num_threads()
unsigned int num_threads () const override virtual
Returns the number of threads that the OMPScheduler has in its pool.
Returns
Number of threads available in OMPScheduler.
Implements IScheduler.
Definition at line 47 of file OMPScheduler.cpp.
 {
     return _num_threads;
 }
Referenced by OMPScheduler::schedule(), and OMPScheduler::set_num_threads().
schedule()
void schedule (ICPPKernel * kernel, const Hints & hints) override virtual
Multithread the execution of the passed kernel if possible.
The kernel will run on a single thread if any of these conditions is true:
ICPPKernel::is_parallelisable() returns false
The scheduler has been initialized with only one thread.
Parameters
[in] kernel Kernel to execute.
[in] hints Hints for the scheduler.
Implements IScheduler.
Definition at line 58 of file OMPScheduler.cpp.
 {
     ARM_COMPUTE_ERROR_ON_MSG(!kernel, "The child class didn't set the kernel");
     ARM_COMPUTE_ERROR_ON_MSG(hints.strategy() == StrategyHint::DYNAMIC,
                              "Dynamic scheduling is not supported in OMPScheduler");
     const Window      &max_window     = kernel->window();
     const unsigned int num_iterations = max_window.num_iterations(hints.split_dimension());
     const unsigned int num_threads    = std::min(num_iterations, _num_threads);
     if(!kernel->is_parallelisable() || num_threads == 1)
     {
         ThreadInfo info;
         info.cpu_info = &_cpu_info;
         kernel->run(max_window, info);
     }
     else
     {
         const unsigned int                num_windows = num_threads;
         std::vector<IScheduler::Workload> workloads(num_windows);
         for(unsigned int t = 0; t < num_windows; t++)
         {
             //Capture 't' by copy, all the other variables by reference:
             workloads[t] = [t, &hints, &max_window, &num_windows, &kernel](const ThreadInfo & info)
             {
                 Window win = max_window.split_window(hints.split_dimension(), t, num_windows);
                 win.validate();
                 kernel->run(win, info);
             };
         }
         run_workloads(workloads);
     }
 }
References ARM_COMPUTE_ERROR_ON_MSG, IScheduler::DYNAMIC, arm_compute::test::validation::info, IKernel::is_parallelisable(), Window::num_iterations(), OMPScheduler::num_threads(), ICPPKernel::run(), IScheduler::Hints::split_dimension(), Window::split_window(), IScheduler::Hints::strategy(), Window::validate(), and IKernel::window().
set_num_threads()
void set_num_threads (unsigned int num_threads) override virtual
Sets the number of threads the scheduler will use to run the kernels.
Parameters
[in] num_threads If set to 0, then the number returned by omp_get_max_threads() will be used, otherwise the number of threads specified.
Implements IScheduler.
Definition at line 52 of file OMPScheduler.cpp.
 {
     const unsigned int num_cores = omp_get_max_threads();
     _num_threads                 = (num_threads == 0) ? num_cores : num_threads;
 }
References OMPScheduler::num_threads().
The documentation for this class was generated from the following files:
arm_compute/runtime/OMP/OMPScheduler.h
src/runtime/OMP/OMPScheduler.cpp