Compute Library: CLComputeAllAnchorsKernel Class Reference
CLComputeAllAnchorsKernel Class Reference
Interface for Compute All Anchors kernel.
#include <CLGenerateProposalsLayerKernel.h>
Public Member Functions
CLComputeAllAnchorsKernel ()
Default constructor.
CLComputeAllAnchorsKernel (const CLComputeAllAnchorsKernel &)=delete
Prevent instances of this class from being copied (As this class contains pointers)
CLComputeAllAnchorsKernel & operator= (const CLComputeAllAnchorsKernel &)=delete
Prevent instances of this class from being copied (As this class contains pointers)
CLComputeAllAnchorsKernel (CLComputeAllAnchorsKernel &&)=default
Allow instances of this class to be moved.
CLComputeAllAnchorsKernel & operator= (CLComputeAllAnchorsKernel &&)=default
Allow instances of this class to be moved.
~CLComputeAllAnchorsKernel ()=default
Default destructor.
void configure (const ICLTensor *anchors, ICLTensor *all_anchors, const ComputeAnchorsInfo &info)
Set the input and output tensors.
void run (const Window &window, cl::CommandQueue &queue) override
Enqueue the OpenCL kernel to process the given window on the passed OpenCL command queue.
Public Member Functions inherited from ICLKernel
ICLKernel ()
Constructor.
cl::Kernel & kernel ()
Returns a reference to the OpenCL kernel of this object.
template<typename T >
void add_1D_array_argument (unsigned int &idx, const ICLArray< T > *array, const Strides &strides, unsigned int num_dimensions, const Window &window)
Add the passed 1D array's parameters to the object's kernel's arguments starting from the index idx.
void add_1D_tensor_argument (unsigned int &idx, const ICLTensor *tensor, const Window &window)
Add the passed 1D tensor's parameters to the object's kernel's arguments starting from the index idx.
void add_1D_tensor_argument_if (bool cond, unsigned int &idx, const ICLTensor *tensor, const Window &window)
Add the passed 1D tensor's parameters to the object's kernel's arguments starting from the index idx if the condition is true.
void add_2D_tensor_argument (unsigned int &idx, const ICLTensor *tensor, const Window &window)
Add the passed 2D tensor's parameters to the object's kernel's arguments starting from the index idx.
void add_2D_tensor_argument_if (bool cond, unsigned int &idx, const ICLTensor *tensor, const Window &window)
Add the passed 2D tensor's parameters to the object's kernel's arguments starting from the index idx if the condition is true.
void add_3D_tensor_argument (unsigned int &idx, const ICLTensor *tensor, const Window &window)
Add the passed 3D tensor's parameters to the object's kernel's arguments starting from the index idx.
void add_4D_tensor_argument (unsigned int &idx, const ICLTensor *tensor, const Window &window)
Add the passed 4D tensor's parameters to the object's kernel's arguments starting from the index idx.
template<typename T >
void add_argument (unsigned int &idx, T value)
Add the passed parameters to the object's kernel's arguments starting from the index idx.
void set_lws_hint (const cl::NDRange &lws_hint)
Set the Local-Workgroup-Size hint.
cl::NDRange lws_hint () const
Return the Local-Workgroup-Size hint.
const std::string & config_id () const
Get the configuration ID.
void set_target (GPUTarget target)
Set the targeted GPU architecture.
void set_target (cl::Device &device)
Set the targeted GPU architecture according to the CL device.
GPUTarget get_target () const
Get the targeted GPU architecture.
size_t get_max_workgroup_size ()
Get the maximum workgroup size for the device the CLKernelLibrary uses.
template<typename T , unsigned int dimension_size>
void add_array_argument (unsigned &idx, const ICLArray< T > *array, const Strides &strides, unsigned int num_dimensions, const Window &window)
Add the passed array's parameters to the object's kernel's arguments starting from the index idx.
template<unsigned int dimension_size>
void add_tensor_argument (unsigned &idx, const ICLTensor *tensor, const Window &window)
Public Member Functions inherited from IKernel
IKernel ()
Constructor.
virtual ~IKernel ()=default
Destructor.
virtual bool is_parallelisable () const
Indicates whether or not the kernel is parallelisable.
virtual BorderSize border_size () const
The size of the border for that kernel.
const Window & window () const
The maximum window the kernel can be executed on.
Static Public Member Functions
static Status validate (const ITensorInfo *anchors, const ITensorInfo *all_anchors, const ComputeAnchorsInfo &info)
Static function to check if given info will lead to a valid configuration of CLComputeAllAnchorsKernel.
Static Public Member Functions inherited from ICLKernel
static constexpr unsigned int num_arguments_per_1D_array ()
Returns the number of arguments enqueued per 1D array object.
static constexpr unsigned int num_arguments_per_1D_tensor ()
Returns the number of arguments enqueued per 1D tensor object.
static constexpr unsigned int num_arguments_per_2D_tensor ()
Returns the number of arguments enqueued per 2D tensor object.
static constexpr unsigned int num_arguments_per_3D_tensor ()
Returns the number of arguments enqueued per 3D tensor object.
static constexpr unsigned int num_arguments_per_4D_tensor ()
Returns the number of arguments enqueued per 4D tensor object.
static cl::NDRange gws_from_window (const Window &window)
Get the global work size given an execution window.
Detailed Description
Interface for Compute All Anchors kernel.
Definition at line 33 of file CLGenerateProposalsLayerKernel.h.
Constructor & Destructor Documentation
CLComputeAllAnchorsKernel() [1/3]
CLComputeAllAnchorsKernel ()
Default constructor.
Definition at line 63 of file CLGenerateProposalsLayerKernel.cpp.
     : _anchors(nullptr), _all_anchors(nullptr)
 {
 }
CLComputeAllAnchorsKernel() [2/3]
CLComputeAllAnchorsKernel (const CLComputeAllAnchorsKernel &) delete
Prevent instances of this class from being copied (As this class contains pointers)
CLComputeAllAnchorsKernel() [3/3]
CLComputeAllAnchorsKernel (CLComputeAllAnchorsKernel &&) default
Allow instances of this class to be moved.
~CLComputeAllAnchorsKernel()
~CLComputeAllAnchorsKernel () default
Default destructor.
Member Function Documentation
configure()
void configure (const ICLTensor * anchors, ICLTensor * all_anchors, const ComputeAnchorsInfo & info)
Set the input and output tensors.
Parameters
[in] anchors Source tensor. Original set of anchors of size (4, A), where A is the number of anchors. Data types supported: F16/F32
[out] all_anchors Destination tensor. Destination anchors of size (4, H*W*A) where H and W are the height and width of the feature map and A is the number of anchors. Data types supported: Same as input
[in] info Contains Compute Anchors operation information described in ComputeAnchorsInfo
Definition at line 68 of file CLGenerateProposalsLayerKernel.cpp.
 {
     ARM_COMPUTE_ERROR_ON_NULLPTR(anchors, all_anchors);
     ARM_COMPUTE_ERROR_THROW_ON(validate_arguments(anchors->info(), all_anchors->info(), info));
     // Metadata
     const size_t   num_anchors = anchors->info()->dimension(1);
     const DataType data_type   = anchors->info()->data_type();
     const float    width       = info.feat_width();
     const float    height      = info.feat_height();
     // Initialize the output if empty
     const TensorShape output_shape(info.values_per_roi(), width * height * num_anchors);
     auto_init_if_empty(*all_anchors->info(), output_shape, 1, data_type);
     // Set instance variables
     _anchors     = anchors;
     _all_anchors = all_anchors;
     // Set build options
     CLBuildOptions build_opts;
     build_opts.add_option("-DDATA_TYPE=" + get_cl_type_from_data_type(data_type));
     build_opts.add_option("-DWIDTH=" + float_to_string_with_full_precision(width));
     build_opts.add_option("-DHEIGHT=" + float_to_string_with_full_precision(height));
     build_opts.add_option("-DSTRIDE=" + float_to_string_with_full_precision(1.f / info.spatial_scale()));
     build_opts.add_option("-DNUM_ANCHORS=" + support::cpp11::to_string(num_anchors));
     build_opts.add_option("-DNUM_ROI_FIELDS=" + support::cpp11::to_string(info.values_per_roi()));
     // Create kernel
     _kernel = static_cast<cl::Kernel>(CLKernelLibrary::get().create_kernel("generate_proposals_compute_all_anchors", build_opts.options()));
     // The tensor all_anchors can be interpreted as an array of structs (each structs has values_per_roi fields).
     // This means we don't need to pad on the X dimension, as we know in advance how many fields
     // compose the struct.
     Window win = calculate_max_window(*all_anchors->info(), Steps(info.values_per_roi()));
     ICLKernel::configure_internal(win);
 }
References CLBuildOptions::add_option(), ARM_COMPUTE_ERROR_ON_NULLPTR, ARM_COMPUTE_ERROR_THROW_ON, arm_compute::auto_init_if_empty(), arm_compute::calculate_max_window(), arm_compute::create_kernel(), arm_compute::test::validation::data_type, ITensorInfo::data_type(), ITensorInfo::dimension(), arm_compute::float_to_string_with_full_precision(), CLKernelLibrary::get(), arm_compute::get_cl_type_from_data_type(), ITensor::info(), arm_compute::test::validation::info, CLBuildOptions::options(), arm_compute::test::validation::output_shape, and arm_compute::support::cpp11::to_string().
Referenced by CLGenerateProposalsLayer::configure().
operator=() [1/2]
CLComputeAllAnchorsKernel& operator= (const CLComputeAllAnchorsKernel &) delete
Prevent instances of this class from being copied (As this class contains pointers)
operator=() [2/2]
CLComputeAllAnchorsKernel& operator= (CLComputeAllAnchorsKernel &&) default
Allow instances of this class to be moved.
run()
void run (const Window & window, cl::CommandQueue & queue) override virtual
Enqueue the OpenCL kernel to process the given window on the passed OpenCL command queue.
Note
The queue is not flushed by this method, and therefore the kernel will not have been executed by the time this method returns.
Parameters
[in] window Region on which to execute the kernel. (Must be a valid region of the window returned by window()).
[in,out] queue Command queue on which to enqueue the kernel.
Implements ICLKernel.
Definition at line 112 of file CLGenerateProposalsLayerKernel.cpp.
 {
     ARM_COMPUTE_ERROR_ON_UNCONFIGURED_KERNEL(this);
     ARM_COMPUTE_ERROR_ON_INVALID_SUBWINDOW(IKernel::window(), window);
     // Collapse everything on the first dimension
     Window collapsed = window.collapse(ICLKernel::window(), Window::DimX);
     // Set arguments
     unsigned int idx = 0;
     add_1D_tensor_argument(idx, _anchors, collapsed);
     add_1D_tensor_argument(idx, _all_anchors, collapsed);
     // Note that we don't need to loop over the slices, as we are launching exactly
     // as many threads as all the anchors generated
     enqueue(queue, *this, collapsed);
 }
References ICLKernel::add_1D_tensor_argument(), ARM_COMPUTE_ERROR_ON_INVALID_SUBWINDOW, ARM_COMPUTE_ERROR_ON_UNCONFIGURED_KERNEL, Window::collapse(), Window::DimX, arm_compute::enqueue(), and IKernel::window().
validate()
Status validate (const ITensorInfo * anchors, const ITensorInfo * all_anchors, const ComputeAnchorsInfo & info) static
Static function to check if given info will lead to a valid configuration of CLComputeAllAnchorsKernel.
Parameters
[in] anchors Source tensor info. Original set of anchors of size (4, A), where A is the number of anchors. Data types supported: F16/F32
[in] all_anchors Destination tensor info. Destination anchors of size (4, H*W*A) where H and W are the height and width of the feature map and A is the number of anchors. Data types supported: Same as input
[in] info Contains Compute Anchors operation information described in ComputeAnchorsInfo
Returns
a Status
Definition at line 106 of file CLGenerateProposalsLayerKernel.cpp.
 {
     ARM_COMPUTE_RETURN_ON_ERROR(validate_arguments(anchors, all_anchors, info));
     return Status{};
 }
References ARM_COMPUTE_RETURN_ON_ERROR, and arm_compute::test::validation::info.
Referenced by CLComputeAllAnchors::validate(), and CLGenerateProposalsLayer::validate().
The documentation for this class was generated from the following files:
arm_compute/core/CL/kernels/CLGenerateProposalsLayerKernel.h
src/core/CL/kernels/CLGenerateProposalsLayerKernel.cpp