Compute Library: CLConcatenateLayer Class Reference
CLConcatenateLayer Class Reference
Basic function to execute concatenate tensors along a given axis.
#include <CLConcatenateLayer.h>
Public Member Functions
CLConcatenateLayer ()
Default constructor.
void configure (const std::vector< ICLTensor * > &inputs_vector, ICLTensor *output, size_t axis)
Initialise the kernel's inputs vector and output.
void run () override
Run the kernels contained in the function.
Public Member Functions inherited from IFunction
virtual ~IFunction ()=default
Destructor.
virtual void prepare ()
Prepare the function for executing.
Static Public Member Functions
static Status validate (const std::vector< ITensorInfo * > &inputs_vector, const ITensorInfo *output, size_t axis)
Static function to check if given info will lead to a valid configuration of CLConcatenateLayer.
Detailed Description
Basic function to execute concatenate tensors along a given axis.
This function calls the following kernels:
CLWidthConcatenateLayer (if underlying concatenation axis is 0).
CLHeightConcatenateLayerKernel (if underlying concatenation axis is 1).
CLDepthConcatenateLayer (if underlying concatenation axis is 2).
Definition at line 48 of file CLConcatenateLayer.h.
Constructor & Destructor Documentation
CLConcatenateLayer()
CLConcatenateLayer ()
Default constructor.
Definition at line 40 of file CLConcatenateLayer.cpp.
     : _concat_kernels(),
       _num_inputs(0),
       _axis(Window::DimX)
 {
 }
Member Function Documentation
configure()
void configure (const std::vector< ICLTensor * > & inputs_vector, ICLTensor * output, size_t axis)
Initialise the kernel's inputs vector and output.
Note
Input and output tensor dimensions preconditions defer depending on the concatenation axis.
Preconditions can be found respectively at CLWidthConcatenateLayer, CLHeightConcatenateLayerKernel and CLDepthConcatenateLayer.
Parameters
[in,out] inputs_vector The vectors containing all the tensors to concatenate. Data types supported: QASYMM8/F16/F32.
[out] output Output tensor. Data types supported: Same as input.
[in] axis Concatenation axis. Supported underlying concatenation axis are 0, 1 and 2.
Definition at line 47 of file CLConcatenateLayer.cpp.
 {
     ARM_COMPUTE_ERROR_ON(output == nullptr);
     _axis       = axis;
     _num_inputs = inputs_vector.size();
     std::vector<ITensorInfo *> inputs_vector_info(inputs_vector.size());
     std::transform(inputs_vector.begin(), inputs_vector.end(), inputs_vector_info.begin(), [](ICLTensor * t)
     {
         ARM_COMPUTE_ERROR_ON_NULLPTR(t);
         return t->info();
     });
     TensorShape output_shape = arm_compute::misc::shape_calculator::calculate_concatenate_shape(inputs_vector, _axis);
     // Output auto inizialitation if not yet initialized
     auto_init_if_empty(*output->info(), output_shape, 1, inputs_vector[0]->info()->data_type());
     ARM_COMPUTE_ERROR_THROW_ON(CLConcatenateLayer::validate(inputs_vector_info, output->info(), axis));
     unsigned int offset = 0;
     switch(_axis)
     {
         case Window::DimX:
         {
             switch(_num_inputs)
             {
                 case 2:
                 {
                     // Configure WidthConcatenate2Tensors kernel
                     auto kernel = support::cpp14::make_unique<CLWidthConcatenate2TensorsKernel>();
                     kernel->configure(inputs_vector.at(0), inputs_vector.at(1), output);
                     _concat_kernels.emplace_back(std::move(kernel));
                     break;
                 }
                 case 4:
                 {
                     // Configure WidthConcatenate4Tensors kernel
                     auto kernel = support::cpp14::make_unique<CLWidthConcatenate4TensorsKernel>();
                     kernel->configure(inputs_vector.at(0), inputs_vector.at(1), inputs_vector.at(2), inputs_vector.at(3), output);
                     _concat_kernels.emplace_back(std::move(kernel));
                     break;
                 }
                 default:
                 {
                     // Configure generic case WidthConcatenate kernels
                     for(unsigned int i = 0; i < _num_inputs; ++i)
                     {
                         auto kernel = support::cpp14::make_unique<CLWidthConcatenateLayerKernel>();
                         kernel->configure(inputs_vector.at(i), offset, output);
                         offset += inputs_vector.at(i)->info()->dimension(_axis);
                         _concat_kernels.emplace_back(std::move(kernel));
                     }
                     break;
                 }
             }
             break;
         }
         case Window::DimY:
         {
             for(unsigned int i = 0; i < _num_inputs; ++i)
             {
                 auto kernel = support::cpp14::make_unique<CLHeightConcatenateLayerKernel>();
                 kernel->configure(inputs_vector.at(i), offset, output);
                 offset += inputs_vector.at(i)->info()->dimension(_axis);
                 _concat_kernels.emplace_back(std::move(kernel));
             }
             break;
         }
         case Window::DimZ:
         {
             for(unsigned int i = 0; i < _num_inputs; ++i)
             {
                 auto kernel = support::cpp14::make_unique<CLDepthConcatenateLayerKernel>();
                 kernel->configure(inputs_vector.at(i), offset, output);
                 offset += inputs_vector.at(i)->info()->dimension(_axis);
                 _concat_kernels.emplace_back(std::move(kernel));
             }
             break;
         }
         default:
             ARM_COMPUTE_ERROR("Axis not supported");
     }
 }
References ARM_COMPUTE_ERROR, ARM_COMPUTE_ERROR_ON, ARM_COMPUTE_ERROR_ON_NULLPTR, ARM_COMPUTE_ERROR_THROW_ON, arm_compute::auto_init_if_empty(), arm_compute::test::validation::axis, arm_compute::misc::shape_calculator::calculate_concatenate_shape(), Window::DimX, Window::DimY, Window::DimZ, ITensor::info(), offset(), arm_compute::test::validation::output_shape, and CLConcatenateLayer::validate().
Referenced by arm_compute::test::validation::TEST_CASE().
run()
void run () override virtual
Run the kernels contained in the function.
For NEON kernels:
Multi-threading is used for the kernels which are parallelisable.
By default std::thread::hardware_concurrency() threads are used.
Note
CPPScheduler::set_num_threads() can be used to manually set the number of threads
For OpenCL kernels:
All the kernels are enqueued on the queue associated with CLScheduler.
The queue is then flushed.
Note
The function will not block until the kernels are executed. It is the user's responsibility to wait.
Will call prepare() on first run if hasn't been done
Implements IFunction.
Definition at line 198 of file CLConcatenateLayer.cpp.
 {
     for(auto &kernel : _concat_kernels)
     {
         CLScheduler::get().enqueue(*kernel, true);
     }
 }
References CLScheduler::enqueue(), and CLScheduler::get().
validate()
Status validate (const std::vector< ITensorInfo * > & inputs_vector, const ITensorInfo * output, size_t axis) static
Static function to check if given info will lead to a valid configuration of CLConcatenateLayer.
Note
Input and output tensor dimensions preconditions defer depending on the concatenation axis.
Preconditions can be found respectively at CLWidthConcatenateLayer, CLHeightConcatenateLayerKernel and CLDepthConcatenateLayer.
Parameters
[in] inputs_vector The vectors containing all the tensors info to concatenate. Data types supported: QASYMM8/F16/F32.
[in] output Output tensor info. Data types supported: Same as input.
[in] axis Concatenation axis. Supported underlying concatenation axis are 0, 1 and 2.
Returns
a status
Definition at line 130 of file CLConcatenateLayer.cpp.
 {
     ARM_COMPUTE_RETURN_ERROR_ON(output == nullptr);
     const unsigned int num_inputs = inputs_vector.size();
     ARM_COMPUTE_RETURN_ERROR_ON_NULLPTR(output);
     ARM_COMPUTE_RETURN_ERROR_ON(num_inputs < 2);
     unsigned int offset = 0;
     switch(axis)
     {
         case Window::DimX:
         {
             switch(num_inputs)
             {
                 case 2:
                     // Validate WidthConcatenate2Tensors kernels if there are 2 inputs
                     ARM_COMPUTE_RETURN_ERROR_ON_NULLPTR(inputs_vector[0], inputs_vector[1]);
                     ARM_COMPUTE_RETURN_ON_ERROR(CLWidthConcatenate2TensorsKernel::validate(inputs_vector[0], inputs_vector[1], output));
                     break;
                 case 4:
                     // Validate WidthConcatenate4Tensors kernels if there are 4 inputs
                     ARM_COMPUTE_RETURN_ERROR_ON_NULLPTR(inputs_vector[0], inputs_vector[1], inputs_vector[2], inputs_vector[3]);
                     ARM_COMPUTE_RETURN_ON_ERROR(CLWidthConcatenate4TensorsKernel::validate(inputs_vector[0], inputs_vector[1], inputs_vector[2], inputs_vector[3], output));
                     break;
                 default:
                     // Validate generic case of WidthConcatenate kernel
                     for(const auto &input : inputs_vector)
                     {
                         ARM_COMPUTE_RETURN_ERROR_ON_NULLPTR(input);
                         ARM_COMPUTE_RETURN_ON_ERROR(CLWidthConcatenateLayerKernel::validate(input, offset, output));
                         offset += input->dimension(axis);
                     }
                     break;
             }
             break;
         }
         case Window::DimY:
         {
             for(const auto &input : inputs_vector)
             {
                 ARM_COMPUTE_RETURN_ON_ERROR(CLHeightConcatenateLayerKernel::validate(input, offset, output));
                 offset += input->dimension(axis);
             }
             break;
         }
         case Window::DimZ:
         {
             for(const auto &input : inputs_vector)
             {
                 ARM_COMPUTE_RETURN_ON_ERROR(CLDepthConcatenateLayerKernel::validate(input, offset, output));
                 offset += input->dimension(axis);
             }
             break;
         }
         default:
             ARM_COMPUTE_ERROR("Axis not supported");
     }
     if(output->total_size() != 0)
     {
         TensorShape output_shape = arm_compute::misc::shape_calculator::calculate_concatenate_shape(inputs_vector, axis);
         ARM_COMPUTE_RETURN_ERROR_ON(output_shape.total_size() != output->tensor_shape().total_size());
     }
     return Status{};
 }
References ARM_COMPUTE_ERROR, ARM_COMPUTE_RETURN_ERROR_ON, ARM_COMPUTE_RETURN_ERROR_ON_NULLPTR, ARM_COMPUTE_RETURN_ON_ERROR, arm_compute::test::validation::axis, arm_compute::misc::shape_calculator::calculate_concatenate_shape(), Window::DimX, Window::DimY, Window::DimZ, offset(), arm_compute::test::validation::output_shape, ITensorInfo::tensor_shape(), TensorShape::total_size(), ITensorInfo::total_size(), CLWidthConcatenate2TensorsKernel::validate(), CLHeightConcatenateLayerKernel::validate(), CLWidthConcatenateLayerKernel::validate(), CLWidthConcatenate4TensorsKernel::validate(), and CLDepthConcatenateLayerKernel::validate().
Referenced by CLConcatenateLayer::configure().
The documentation for this class was generated from the following files:
arm_compute/runtime/CL/functions/CLConcatenateLayer.h
src/runtime/CL/functions/CLConcatenateLayer.cpp