Compute Library: PoolingLayerInfo Class Reference
PoolingLayerInfo Class Reference
Pooling Layer Information class.
#include <Types.h>
Public Member Functions
PoolingLayerInfo ()
Default Constructor.
PoolingLayerInfo (PoolingType pool_type, unsigned int pool_size, PadStrideInfo pad_stride_info=PadStrideInfo(), bool exclude_padding=false)
Default Constructor.
PoolingLayerInfo (PoolingType pool_type, Size2D pool_size, PadStrideInfo pad_stride_info=PadStrideInfo(), bool exclude_padding=false)
Default Constructor.
PoolingLayerInfo (PoolingType pool_type)
Default Constructor.
PoolingType pool_type () const
Get the pooling type.
const Size2D & pool_size () const
Get the pooling size.
PadStrideInfo pad_stride_info () const
Get the padding and stride.
bool exclude_padding () const
Check if padding is excluded in calculations.
bool is_global_pooling () const
Check if is global pooling.
Detailed Description
Pooling Layer Information class.
Definition at line 957 of file Types.h.
Constructor & Destructor Documentation
PoolingLayerInfo() [1/4]
PoolingLayerInfo () inline
Default Constructor.
Definition at line 961 of file Types.h.
         : _pool_type(PoolingType::MAX), _pool_size(Size2D()), _pad_stride_info(PadStrideInfo()), _exclude_padding(false), _is_global_pooling(false)
     {
     }
PoolingLayerInfo() [2/4]
PoolingLayerInfo (PoolingType pool_type, unsigned int pool_size, PadStrideInfo pad_stride_info = PadStrideInfo(), bool exclude_padding = false) inline explicit
Default Constructor.
Parameters
[in] pool_type Pooling type PoolingType.
[in] pool_size Pooling size, in elements, across x and y.
[in] pad_stride_info (Optional) Padding and stride information PadStrideInfo
[in] exclude_padding (Optional) Strategy when accounting padding in calculations. True will exclude padding while false will not (Used in AVG/L2 pooling to determine the pooling area). Defaults to false;
Definition at line 974 of file Types.h.
         : _pool_type(pool_type), _pool_size(Size2D(pool_size, pool_size)), _pad_stride_info(pad_stride_info), _exclude_padding(exclude_padding), _is_global_pooling(false)
     {
     }
PoolingLayerInfo() [3/4]
PoolingLayerInfo (PoolingType pool_type, Size2D pool_size, PadStrideInfo pad_stride_info = PadStrideInfo(), bool exclude_padding = false) inline explicit
Default Constructor.
Parameters
[in] pool_type Pooling type PoolingType.
[in] pool_size Pooling size, in elements, across x and y.
[in] pad_stride_info (Optional) Padding and stride information PadStrideInfo
[in] exclude_padding (Optional) Strategy when accounting padding in calculations. True will exclude padding while false will not (Used in AVG/L2 pooling to determine the pooling area). Defaults to false;
Definition at line 990 of file Types.h.
         : _pool_type(pool_type), _pool_size(pool_size), _pad_stride_info(pad_stride_info), _exclude_padding(exclude_padding), _is_global_pooling(false)
     {
     }
PoolingLayerInfo() [4/4]
PoolingLayerInfo (PoolingType pool_type) inline explicit
Default Constructor.
Note
This constructor is used for global pooling
Parameters
[in] pool_type Pooling type PoolingType.
Definition at line 1003 of file Types.h.
         : _pool_type(pool_type), _pool_size(Size2D()), _pad_stride_info(PadStrideInfo(1, 1, 0, 0)), _exclude_padding(false), _is_global_pooling(true)
     {
     }
Member Function Documentation
exclude_padding()
bool exclude_padding () const inline
Check if padding is excluded in calculations.
Definition at line 1023 of file Types.h.
Referenced by CLPoolingLayer::configure(), NEPoolingLayer::configure(), GCPoolingLayerKernel::configure(), CLPoolingLayerKernel::configure(), NEPoolingLayerKernel::configure(), and arm_compute::test::validation::reference::pooling_layer().
     {
         return _exclude_padding;
     }
is_global_pooling()
bool is_global_pooling () const inline
Check if is global pooling.
Definition at line 1028 of file Types.h.
Referenced by PoolingLayerNode::compute_output_descriptor(), arm_compute::misc::shape_calculator::compute_pool_shape(), GCPoolingLayerKernel::configure(), CLPoolingLayerKernel::configure(), NEPoolingLayerKernel::configure(), arm_compute::test::validation::reference::pooling_layer(), arm_compute::to_string(), and NEPoolingLayerKernel::validate().
     {
         return _is_global_pooling;
     }
pad_stride_info()
PadStrideInfo pad_stride_info () const inline
Get the padding and stride.
Definition at line 1018 of file Types.h.
Referenced by PoolingLayerNode::compute_output_descriptor(), arm_compute::misc::shape_calculator::compute_pool_shape(), GCPoolingLayerKernel::configure(), CLPoolingLayerKernel::configure(), NEPoolingLayerKernel::configure(), arm_compute::test::validation::reference::pooling_layer(), GCPoolingLayerKernel::run(), CLPoolingLayerKernel::run(), NEPoolingLayerKernel::run(), arm_compute::to_string(), NEPoolingLayerKernel::validate(), and DotGraphVisitor::visit().
     {
         return _pad_stride_info;
     }
pool_size()
const Size2D& pool_size () const inline
Get the pooling size.
Definition at line 1013 of file Types.h.
Referenced by PoolingLayerNode::compute_output_descriptor(), arm_compute::misc::shape_calculator::compute_pool_shape(), NEPoolingLayer::configure(), GCPoolingLayerKernel::configure(), CLPoolingLayerKernel::configure(), NEPoolingLayerKernel::configure(), arm_compute::test::validation::reference::pooling_layer(), NEPoolingLayerKernel::run(), arm_compute::to_string(), NEPoolingLayerKernel::validate(), and DotGraphVisitor::visit().
     {
         return _pool_size;
     }
pool_type()
PoolingType pool_type () const inline
Get the pooling type.
Definition at line 1008 of file Types.h.
Referenced by CLPoolingLayer::configure(), GCPoolingLayer::configure(), NEPoolingLayer::configure(), GCPoolingLayerKernel::configure(), CLPoolingLayerKernel::configure(), NEPoolingLayerKernel::configure(), arm_compute::operator<<(), arm_compute::test::validation::reference::pooling_layer(), arm_compute::to_string(), and DotGraphVisitor::visit().
     {
         return _pool_type;
     }
The documentation for this class was generated from the following file:
arm_compute/core/Types.h