Compute Library: CLLutAccessor< T > Class Template Reference
CLLutAccessor< T > Class Template Reference
Accessor implementation for CLLut objects.
#include <CLLutAccessor.h>
Public Member Functions
CLLutAccessor (CLLut &lut)
Create an accessor for the given CLLut.
~CLLutAccessor ()
Default destructor.
CLLutAccessor (const CLLutAccessor &)=delete
Prevent instances of this class from being copy constructed.
CLLutAccessor & operator= (const CLLutAccessor &)=delete
Prevent instances of this class from being copied.
CLLutAccessor (CLLutAccessor &&)=default
Allow instances of this class to be move constructed.
CLLutAccessor & operator= (CLLutAccessor &&)=default
Allow instance of this class to be moved.
int num_elements () const override
Number of elements of the Lut.
const T & operator[] (T input_value) const override
Read access to the specified element.
T & operator[] (T input_value) override
Write access to the specified element.
Public Member Functions inherited from ILutAccessor< T >
virtual ~ILutAccessor ()=default
Pure virtual destructor.
Additional Inherited Members
Public Types inherited from ILutAccessor< T >
using value_type = T
Lut value type.
Detailed Description
template<typename T>
class arm_compute::test::CLLutAccessor< T >
Accessor implementation for CLLut objects.
Definition at line 37 of file CLLutAccessor.h.
Constructor & Destructor Documentation
CLLutAccessor() [1/3]
CLLutAccessor (CLLut & lut) inline
Create an accessor for the given CLLut.
Definition at line 42 of file CLLutAccessor.h.
         : _lut{ lut }
     {
         _lut.map(true);
     }
~CLLutAccessor()
~CLLutAccessor () inline
Default destructor.
Definition at line 48 of file CLLutAccessor.h.
     {
         _lut.unmap();
     }
References CLLut::unmap().
CLLutAccessor() [2/3]
CLLutAccessor (const CLLutAccessor< T > &) delete
Prevent instances of this class from being copy constructed.
CLLutAccessor() [3/3]
CLLutAccessor (CLLutAccessor< T > &&) default
Allow instances of this class to be move constructed.
Member Function Documentation
num_elements()
int num_elements () const inline override virtual
Number of elements of the Lut.
Returns
the number of elements.
Implements ILutAccessor< T >.
Definition at line 62 of file CLLutAccessor.h.
     {
         return _lut.num_elements();
     }
References CLLut::num_elements().
Referenced by CLLutAccessor< T >::operator[]().
operator=() [1/2]
CLLutAccessor& operator= (const CLLutAccessor< T > &) delete
Prevent instances of this class from being copied.
operator=() [2/2]
CLLutAccessor& operator= (CLLutAccessor< T > &&) default
Allow instance of this class to be moved.
operator[]() [1/2]
const T& operator[] (T input_value) const inline override virtual
Read access to the specified element.
Parameters
[in] input_value Lut input value, from numericlimits<T>:min to numericlimits<T>:max.
Returns
Output desired element.
Implements ILutAccessor< T >.
Definition at line 67 of file CLLutAccessor.h.
     {
         auto    lut        = reinterpret_cast<T *>(_lut.buffer());
         int32_t real_index = _lut.index_offset() + static_cast<int32_t>(input_value);
         if(0 <= real_index && real_index < num_elements())
         {
             return lut[real_index];
         }
         ARM_COMPUTE_ERROR("Error index not in range.");
     }
References ARM_COMPUTE_ERROR, ICLLut::buffer(), CLLut::index_offset(), and CLLutAccessor< T >::num_elements().
operator[]() [2/2]
T& operator[] (T input_value) inline override virtual
Write access to the specified element.
Parameters
[in] input_value Lut input value, from numericlimits<T>:min to numericlimits<T>:max.
Returns
Output desired element.
Implements ILutAccessor< T >.
Definition at line 79 of file CLLutAccessor.h.
     {
         auto    lut        = reinterpret_cast<T *>(_lut.buffer());
         int32_t real_index = _lut.index_offset() + static_cast<int32_t>(input_value);
         if(0 <= real_index && real_index < num_elements())
         {
             return lut[real_index];
         }
         ARM_COMPUTE_ERROR("Error index not in range.");
     }
References ARM_COMPUTE_ERROR, ICLLut::buffer(), CLLut::index_offset(), and CLLutAccessor< T >::num_elements().
The documentation for this class was generated from the following file:
tests/CL/CLLutAccessor.h