Compute Library: GCArithmeticAdditionKernel Class Reference
GCArithmeticAdditionKernel Class Reference
Interface for the arithmetic addition kernel.
#include <GCArithmeticAdditionKernel.h>
Public Member Functions
GCArithmeticAdditionKernel ()
Default constructor.
GCArithmeticAdditionKernel (const GCArithmeticAdditionKernel &)=delete
Prevent instances of this class from being copied (As this class contains pointers)
GCArithmeticAdditionKernel & operator= (const GCArithmeticAdditionKernel &)=delete
Prevent instances of this class from being copied (As this class contains pointers)
GCArithmeticAdditionKernel (GCArithmeticAdditionKernel &&)=default
Allow instances of this class to be moved.
GCArithmeticAdditionKernel & operator= (GCArithmeticAdditionKernel &&)=default
Allow instances of this class to be moved.
~GCArithmeticAdditionKernel ()=default
Default destructor.
void configure (const IGCTensor *input1, const IGCTensor *input2, IGCTensor *output, ConvertPolicy policy)
Initialise the kernel's inputs, output and convertion policy.
void run (const Window &window) override
Enqueue the OpenGL ES shader to process the given window.
Public Member Functions inherited from IGCKernel
IGCKernel ()
Constructor.
GCKernel & kernel ()
Returns a reference to the GLES kernel of this object.
void add_1D_tensor_argument (unsigned int &idx, const IGCTensor *tensor, const unsigned int binding_point, const Window &window)
Add the passed 1D tensor's parameters to the object's kernel's arguments starting from the index idx.
void add_2D_tensor_argument (unsigned int &idx, const IGCTensor *tensor, const unsigned int binding_point, const Window &window)
Add the passed 2D tensor's parameters to the object's kernel's arguments starting from the index idx.
void add_3D_tensor_argument (unsigned int &idx, const IGCTensor *tensor, const unsigned int binding_point, const Window &window)
Add the passed 3D tensor's parameters to the object's kernel's arguments starting from the index idx.
unsigned int num_arguments_per_1D_tensor () const
Returns the number of arguments enqueued per 1D tensor object.
unsigned int num_arguments_per_2D_tensor () const
Returns the number of arguments enqueued per 2D tensor object.
unsigned int num_arguments_per_3D_tensor () const
Returns the number of arguments enqueued per 3D tensor object.
void set_lws_hint (gles::NDRange &lws_hint)
Set the Local-Workgroup-Size hint.
void set_target (GPUTarget target)
Set the targeted GPU architecture.
GPUTarget get_target () const
Get the targeted GPU architecture.
Public Member Functions inherited from IKernel
IKernel ()
Constructor.
virtual ~IKernel ()=default
Destructor.
virtual bool is_parallelisable () const
Indicates whether or not the kernel is parallelisable.
virtual BorderSize border_size () const
The size of the border for that kernel.
const Window & window () const
The maximum window the kernel can be executed on.
Static Public Member Functions
static Status validate (const ITensorInfo *input1, const ITensorInfo *input2, const ITensorInfo *output, ConvertPolicy policy)
Static function to check if given info will lead to a valid configuration of GCArithmeticAdditionKernel.
Detailed Description
Interface for the arithmetic addition kernel.
Arithmetic addition is computed by:
\[ output(x,y) = input1(x,y) + input2(x,y) \]
Definition at line 39 of file GCArithmeticAdditionKernel.h.
Constructor & Destructor Documentation
GCArithmeticAdditionKernel() [1/3]
GCArithmeticAdditionKernel ()
Default constructor.
Definition at line 86 of file GCArithmeticAdditionKernel.cpp.
     : _input1(nullptr), _input2(nullptr), _output(nullptr)
 {
 }
GCArithmeticAdditionKernel() [2/3]
GCArithmeticAdditionKernel (const GCArithmeticAdditionKernel &) delete
Prevent instances of this class from being copied (As this class contains pointers)
GCArithmeticAdditionKernel() [3/3]
GCArithmeticAdditionKernel (GCArithmeticAdditionKernel &&) default
Allow instances of this class to be moved.
~GCArithmeticAdditionKernel()
~GCArithmeticAdditionKernel () default
Default destructor.
Member Function Documentation
configure()
void configure (const IGCTensor * input1, const IGCTensor * input2, IGCTensor * output, ConvertPolicy policy)
Initialise the kernel's inputs, output and convertion policy.
Parameters
[in] input1 First tensor input. Data types supported: F16.
[in] input2 Second tensor input. Data types supported: F16.
[out] output Output tensor. Data types supported: F16.
[in] policy Policy to use to handle overflow.
Definition at line 91 of file GCArithmeticAdditionKernel.cpp.
 {
     ARM_COMPUTE_UNUSED(policy);
     ARM_COMPUTE_ERROR_ON_NULLPTR(input1, input2, output);
     // Auto initialize output if not initialized
     {
         set_shape_if_empty(*output->info(), input1->info()->tensor_shape());
         set_format_if_unknown(*output->info(), Format::F16);
     }
     ARM_COMPUTE_ERROR_THROW_ON(validate_arguments(input1->info(), input2->info(), output->info(), policy));
     _input1 = input1;
     _input2 = input2;
     _output = output;
     // Set kernel build options
     std::set<std::string> build_opts;
     build_opts.emplace("#define LOCAL_SIZE_X " + support::cpp11::to_string(1));
     build_opts.emplace("#define LOCAL_SIZE_Y " + support::cpp11::to_string(1));
     build_opts.emplace("#define LOCAL_SIZE_Z " + support::cpp11::to_string(1));
     // Create kernel
     _kernel = static_cast<GCKernel>(GCKernelLibrary::get().create_kernel("arithmetic_add", build_opts));
     // Configure kernel window
     auto win_config = validate_and_configure_window(input1->info(), input2->info(), output->info());
     ARM_COMPUTE_ERROR_THROW_ON(win_config.first);
     IGCKernel::configure(win_config.second);
 }
References ARM_COMPUTE_ERROR_ON_NULLPTR, ARM_COMPUTE_ERROR_THROW_ON, ARM_COMPUTE_UNUSED, arm_compute::create_kernel(), arm_compute::F16, GCKernelLibrary::get(), ITensor::info(), arm_compute::test::validation::policy, arm_compute::set_format_if_unknown(), arm_compute::set_shape_if_empty(), ITensorInfo::tensor_shape(), arm_compute::support::cpp11::to_string(), and arm_compute::validate_and_configure_window().
operator=() [1/2]
GCArithmeticAdditionKernel& operator= (const GCArithmeticAdditionKernel &) delete
Prevent instances of this class from being copied (As this class contains pointers)
operator=() [2/2]
GCArithmeticAdditionKernel& operator= (GCArithmeticAdditionKernel &&) default
Allow instances of this class to be moved.
run()
void run (const Window & window) override virtual
Enqueue the OpenGL ES shader to process the given window.
Parameters
[in] window Region on which to execute the kernel. (Must be a valid region of the window returned by window()).
Implements IGCKernel.
Definition at line 131 of file GCArithmeticAdditionKernel.cpp.
 {
     ARM_COMPUTE_ERROR_ON_UNCONFIGURED_KERNEL(this);
     ARM_COMPUTE_ERROR_ON_INVALID_SUBWINDOW(IGCKernel::window(), window);
     _kernel.use();
     _output->set_needs_shifting(true);
     Window slice    = window.first_slice_window_3D();
     Window slice_in = window.first_slice_window_3D();
     slice.shift(Window::DimX, -(_output->info()->padding()).left);
     do
     {
         unsigned int idx     = 0;
         unsigned int binding = 1; // SSBO binding starts from 1.
         add_3D_tensor_argument(idx, _input1, binding++, slice_in);
         add_3D_tensor_argument(idx, _input2, binding++, slice_in);
         add_3D_tensor_argument(idx, _output, binding++, slice);
         _kernel.update_shader_params();
         enqueue(*this, slice);
     }
     while(window.slide_window_slice_3D(slice) && window.slide_window_slice_3D(slice_in));
 }
References IGCKernel::add_3D_tensor_argument(), ARM_COMPUTE_ERROR_ON_INVALID_SUBWINDOW, ARM_COMPUTE_ERROR_ON_UNCONFIGURED_KERNEL, Window::DimX, arm_compute::enqueue(), Window::first_slice_window_3D(), ITensor::info(), ITensorInfo::padding(), IGCTensor::set_needs_shifting(), arm_compute::test::validation::reference::slice(), Window::slide_window_slice_3D(), and IKernel::window().
validate()
Status validate (const ITensorInfo * input1, const ITensorInfo * input2, const ITensorInfo * output, ConvertPolicy policy) static
Static function to check if given info will lead to a valid configuration of GCArithmeticAdditionKernel.
Parameters
[in] input1 First tensor input info. Data types supported: F16.
[in] input2 Second tensor input info. Data types supported: F16.
[out] output Output tensor info. Data types supported: F16.
[in] policy Policy to use to handle overflow.
Returns
a status
Definition at line 123 of file GCArithmeticAdditionKernel.cpp.
 {
     ARM_COMPUTE_RETURN_ON_ERROR(validate_arguments(input1, input2, output, policy));
     ARM_COMPUTE_RETURN_ON_ERROR(validate_and_configure_window(input1->clone().get(), input2->clone().get(), output->clone().get()).first);
     return Status{};
 }
References ARM_COMPUTE_RETURN_ON_ERROR, ICloneable< T >::clone(), arm_compute::test::validation::policy, and arm_compute::validate_and_configure_window().
Referenced by GCArithmeticAddition::validate().
The documentation for this class was generated from the following files:
arm_compute/core/GLES_COMPUTE/kernels/GCArithmeticAdditionKernel.h
src/core/GLES_COMPUTE/kernels/GCArithmeticAdditionKernel.cpp