Compute Library: CLNormalizePlanarYUVLayerKernel Class Reference
CLNormalizePlanarYUVLayerKernel Class Reference
Interface for the NormalizePlanarYUV layer kernel.
#include <CLNormalizePlanarYUVLayerKernel.h>
Public Member Functions
CLNormalizePlanarYUVLayerKernel ()
Constructor.
CLNormalizePlanarYUVLayerKernel (const CLNormalizePlanarYUVLayerKernel &)=delete
Prevent instances of this class from being copied (As this class contains pointers)
CLNormalizePlanarYUVLayerKernel & operator= (const CLNormalizePlanarYUVLayerKernel &)=delete
Prevent instances of this class from being copied (As this class contains pointers)
CLNormalizePlanarYUVLayerKernel (CLNormalizePlanarYUVLayerKernel &&)=default
Default Move Constructor.
CLNormalizePlanarYUVLayerKernel & operator= (CLNormalizePlanarYUVLayerKernel &&)=default
Default move assignment operator.
~CLNormalizePlanarYUVLayerKernel ()=default
Default destructor.
void configure (const ICLTensor *input, ICLTensor *output, const ICLTensor *mean, const ICLTensor *std)
Set the input and output tensors.
void run (const Window &window, cl::CommandQueue &queue) override
Enqueue the OpenCL kernel to process the given window on the passed OpenCL command queue.
Public Member Functions inherited from ICLKernel
ICLKernel ()
Constructor.
cl::Kernel & kernel ()
Returns a reference to the OpenCL kernel of this object.
template<typename T >
void add_1D_array_argument (unsigned int &idx, const ICLArray< T > *array, const Strides &strides, unsigned int num_dimensions, const Window &window)
Add the passed 1D array's parameters to the object's kernel's arguments starting from the index idx.
void add_1D_tensor_argument (unsigned int &idx, const ICLTensor *tensor, const Window &window)
Add the passed 1D tensor's parameters to the object's kernel's arguments starting from the index idx.
void add_2D_tensor_argument (unsigned int &idx, const ICLTensor *tensor, const Window &window)
Add the passed 2D tensor's parameters to the object's kernel's arguments starting from the index idx.
void add_3D_tensor_argument (unsigned int &idx, const ICLTensor *tensor, const Window &window)
Add the passed 3D tensor's parameters to the object's kernel's arguments starting from the index idx.
void add_4D_tensor_argument (unsigned int &idx, const ICLTensor *tensor, const Window &window)
Add the passed 4D tensor's parameters to the object's kernel's arguments starting from the index idx.
template<typename T >
void add_argument (unsigned int &idx, T value)
Add the passed parameters to the object's kernel's arguments starting from the index idx.
void set_lws_hint (const cl::NDRange &lws_hint)
Set the Local-Workgroup-Size hint.
cl::NDRange lws_hint () const
Return the Local-Workgroup-Size hint.
const std::string & config_id () const
Get the configuration ID.
void set_target (GPUTarget target)
Set the targeted GPU architecture.
void set_target (cl::Device &device)
Set the targeted GPU architecture according to the CL device.
GPUTarget get_target () const
Get the targeted GPU architecture.
size_t get_max_workgroup_size ()
Get the maximum workgroup size for the device the CLKernelLibrary uses.
template<typename T , unsigned int dimension_size>
void add_array_argument (unsigned &idx, const ICLArray< T > *array, const Strides &strides, unsigned int num_dimensions, const Window &window)
Add the passed array's parameters to the object's kernel's arguments starting from the index idx.
template<unsigned int dimension_size>
void add_tensor_argument (unsigned &idx, const ICLTensor *tensor, const Window &window)
Public Member Functions inherited from IKernel
IKernel ()
Constructor.
virtual ~IKernel ()=default
Destructor.
virtual bool is_parallelisable () const
Indicates whether or not the kernel is parallelisable.
virtual BorderSize border_size () const
The size of the border for that kernel.
const Window & window () const
The maximum window the kernel can be executed on.
Static Public Member Functions
static Status validate (const ITensorInfo *input, const ITensorInfo *output, const ITensorInfo *mean, const ITensorInfo *std)
Static function to check if given info will lead to a valid configuration of CLNormalizePlanarYUVLayerKernel.
Static Public Member Functions inherited from ICLKernel
static constexpr unsigned int num_arguments_per_1D_array ()
Returns the number of arguments enqueued per 1D array object.
static constexpr unsigned int num_arguments_per_1D_tensor ()
Returns the number of arguments enqueued per 1D tensor object.
static constexpr unsigned int num_arguments_per_2D_tensor ()
Returns the number of arguments enqueued per 2D tensor object.
static constexpr unsigned int num_arguments_per_3D_tensor ()
Returns the number of arguments enqueued per 3D tensor object.
static constexpr unsigned int num_arguments_per_4D_tensor ()
Returns the number of arguments enqueued per 4D tensor object.
static cl::NDRange gws_from_window (const Window &window)
Get the global work size given an execution window.
Detailed Description
Interface for the NormalizePlanarYUV layer kernel.
Definition at line 34 of file CLNormalizePlanarYUVLayerKernel.h.
Constructor & Destructor Documentation
CLNormalizePlanarYUVLayerKernel() [1/3]
CLNormalizePlanarYUVLayerKernel ()
Constructor.
Definition at line 93 of file CLNormalizePlanarYUVLayerKernel.cpp.
     : _input(nullptr), _output(nullptr), _mean(nullptr), _std(nullptr)
 {
 }
CLNormalizePlanarYUVLayerKernel() [2/3]
CLNormalizePlanarYUVLayerKernel (const CLNormalizePlanarYUVLayerKernel &) delete
Prevent instances of this class from being copied (As this class contains pointers)
CLNormalizePlanarYUVLayerKernel() [3/3]
CLNormalizePlanarYUVLayerKernel (CLNormalizePlanarYUVLayerKernel &&) default
Default Move Constructor.
~CLNormalizePlanarYUVLayerKernel()
~CLNormalizePlanarYUVLayerKernel () default
Default destructor.
Member Function Documentation
configure()
void configure (const ICLTensor * input, ICLTensor * output, const ICLTensor * mean, const ICLTensor * std)
Set the input and output tensors.
Parameters
[in] input Source tensor. 3 lower dimensions represent a single input with dimensions [width, height, channels]. Data types supported: QASYMM8/F16/F32.
[out] output Destination tensor. Data type supported: same as input
[in] mean Mean values tensor. 1 dimension with size equal to the number of input channels. Data types supported: same as input
[in] std Standard deviation values tensor. 1 dimension with size equal to the number of input channels. Data types supported: same as input
Definition at line 98 of file CLNormalizePlanarYUVLayerKernel.cpp.
 {
     ARM_COMPUTE_ERROR_ON_NULLPTR(input, output, mean, std);
     // Output tensor auto initialization if not yet initialized
     auto_init_if_empty(*output->info(), *input->info()->clone());
     // Perform validation step
     ARM_COMPUTE_ERROR_THROW_ON(validate_arguments(input->info(), output->info(), mean->info(), std->info()));
     _input  = input;
     _output = output;
     _mean   = mean;
     _std    = std;
     const unsigned int num_elems_processed_per_iteration = 16 / input->info()->element_size();
     const unsigned int channel_idx                       = get_data_layout_dimension_index(input->info()->data_layout(), DataLayoutDimension::CHANNEL);
     const DataType     dt                                = input->info()->data_type();
     // Set build options
     CLBuildOptions build_opts;
     build_opts.add_option(("-DDATA_TYPE=" + get_cl_type_from_data_type(dt)));
     build_opts.add_option(("-DVEC_SIZE=" + support::cpp11::to_string(num_elems_processed_per_iteration)));
     build_opts.add_option(("-DNUM_CHANNELS=" + support::cpp11::to_string(input->info()->dimension(channel_idx))));
     std::string kernel_name = "normalize_planar_yuv_layer_";
     if(is_data_type_quantized(dt))
     {
         build_opts.add_option(("-DOFFSET=" + support::cpp11::to_string(input->info()->quantization_info().offset)));
         build_opts.add_option(("-DSCALE=" + support::cpp11::to_string(input->info()->quantization_info().scale)));
         kernel_name += "q8_";
     }
     // Create kernel
     kernel_name += lower_string(string_from_data_layout(input->info()->data_layout()));
     _kernel = static_cast<cl::Kernel>(CLKernelLibrary::get().create_kernel(kernel_name, build_opts.options()));
     // Configure kernel window
     auto win_config = validate_and_configure_window(input->info(), output->info(), mean->info(), std->info());
     ARM_COMPUTE_ERROR_THROW_ON(win_config.first);
     ICLKernel::configure_internal(win_config.second);
     // Set config_id for enabling LWS tuning
     _config_id = "normalize_planar_yuv_layer_";
     _config_id += lower_string(string_from_data_layout(input->info()->data_layout()));
     _config_id += "_";
     _config_id += lower_string(string_from_data_type(dt));
     _config_id += "_";
     _config_id += support::cpp11::to_string(input->info()->dimension(0));
     _config_id += "_";
     _config_id += support::cpp11::to_string(input->info()->dimension(1));
     _config_id += "_";
     _config_id += support::cpp11::to_string(input->info()->dimension(2));
 }
References CLBuildOptions::add_option(), ARM_COMPUTE_ERROR_ON_NULLPTR, ARM_COMPUTE_ERROR_THROW_ON, arm_compute::auto_init_if_empty(), arm_compute::CHANNEL, ICloneable< T >::clone(), arm_compute::create_kernel(), ITensorInfo::data_layout(), ITensorInfo::data_type(), ITensorInfo::dimension(), ITensorInfo::element_size(), CLKernelLibrary::get(), arm_compute::get_cl_type_from_data_type(), arm_compute::get_data_layout_dimension_index(), ITensor::info(), arm_compute::is_data_type_quantized(), arm_compute::lower_string(), QuantizationInfo::offset, CLBuildOptions::options(), ITensorInfo::quantization_info(), QuantizationInfo::scale, arm_compute::string_from_data_layout(), arm_compute::string_from_data_type(), and arm_compute::support::cpp11::to_string().
Referenced by CLNormalizePlanarYUVLayer::configure().
operator=() [1/2]
CLNormalizePlanarYUVLayerKernel& operator= (const CLNormalizePlanarYUVLayerKernel &) delete
Prevent instances of this class from being copied (As this class contains pointers)
operator=() [2/2]
CLNormalizePlanarYUVLayerKernel& operator= (CLNormalizePlanarYUVLayerKernel &&) default
Default move assignment operator.
run()
void run (const Window & window, cl::CommandQueue & queue) override virtual
Enqueue the OpenCL kernel to process the given window on the passed OpenCL command queue.
Note
The queue is not flushed by this method, and therefore the kernel will not have been executed by the time this method returns.
Parameters
[in] window Region on which to execute the kernel. (Must be a valid region of the window returned by window()).
[in,out] queue Command queue on which to enqueue the kernel.
Implements ICLKernel.
Definition at line 161 of file CLNormalizePlanarYUVLayerKernel.cpp.
 {
     ARM_COMPUTE_ERROR_ON_UNCONFIGURED_KERNEL(this);
     ARM_COMPUTE_ERROR_ON_INVALID_SUBWINDOW(IKernel::window(), window);
     Window collapsed = window.collapse_if_possible(ICLKernel::window(), Window::DimZ);
     Window slice     = collapsed.first_slice_window_3D();
     Window slice_in = collapsed.first_slice_window_1D();
     slice_in.set(Window::DimX, Window::Dimension(0, 0, 0));
     unsigned int idx = 2 * num_arguments_per_3D_tensor();
     add_1D_tensor_argument(idx, _mean, slice_in);
     add_1D_tensor_argument(idx, _std, slice_in);
     do
     {
         idx = 0;
         add_3D_tensor_argument(idx, _input, slice);
         add_3D_tensor_argument(idx, _output, slice);
         enqueue(queue, *this, slice, lws_hint());
     }
     while(collapsed.slide_window_slice_3D(slice));
 }
References ICLKernel::add_1D_tensor_argument(), ICLKernel::add_3D_tensor_argument(), ARM_COMPUTE_ERROR_ON_INVALID_SUBWINDOW, ARM_COMPUTE_ERROR_ON_UNCONFIGURED_KERNEL, Window::collapse_if_possible(), Window::DimX, Window::DimZ, arm_compute::enqueue(), Window::first_slice_window_1D(), Window::first_slice_window_3D(), ICLKernel::lws_hint(), ICLKernel::num_arguments_per_3D_tensor(), Window::set(), arm_compute::test::validation::reference::slice(), Window::slide_window_slice_3D(), and IKernel::window().
validate()
Status validate (const ITensorInfo * input, const ITensorInfo * output, const ITensorInfo * mean, const ITensorInfo * std) static
Static function to check if given info will lead to a valid configuration of CLNormalizePlanarYUVLayerKernel.
Parameters
[in] input Source tensor info. 3 lower dimensions represent a single input with dimensions [width, height, channels]. Data types supported: QASYMM8/F16/F32.
[out] output Destination tensor info. Data type supported: same as input
[in] mean Mean values tensor info. 1 dimension with size equal to the number of input channels. Data types supported: same as input
[in] std Standard deviation values tensor info. 1 dimension with size equal to the number of input channels. Data types supported: same as input
Returns
a status
Definition at line 153 of file CLNormalizePlanarYUVLayerKernel.cpp.
 {
     ARM_COMPUTE_RETURN_ON_ERROR(validate_arguments(input, output, mean, std));
     ARM_COMPUTE_RETURN_ON_ERROR(validate_and_configure_window(input->clone().get(), output->clone().get(), mean->clone().get(), std->clone().get()).first);
     return Status{};
 }
References ARM_COMPUTE_RETURN_ON_ERROR, and ICloneable< T >::clone().
Referenced by CLNormalizePlanarYUVLayer::validate().
The documentation for this class was generated from the following files:
arm_compute/core/CL/kernels/CLNormalizePlanarYUVLayerKernel.h
src/core/CL/kernels/CLNormalizePlanarYUVLayerKernel.cpp