Compute Library: MMappedFile Class Reference
MMappedFile Class Reference
Memory mapped file class.
#include <MMappedFile.h>
Public Member Functions
MMappedFile ()
Constructor.
MMappedFile (std::string filename, size_t size, size_t offset)
Constructor.
MMappedFile (const MMappedFile &)=delete
Prevent instances of this class from being copied (As this class contains pointers)
MMappedFile (MMappedFile &&)=default
Default move constructor.
MMappedFile & operator= (const MMappedFile &)=delete
Prevent instances of this class from being copied (As this class contains pointers)
MMappedFile & operator= (MMappedFile &&)=default
Default move assignment operator.
~MMappedFile ()
Destructor.
bool map (const std::string &filename, size_t size, size_t offset)
Opens and maps a file.
void release ()
Unmaps and closes file.
unsigned char * data ()
Mapped data accessor.
size_t file_size () const
File size accessor.
size_t map_size () const
Map size accessor.
bool is_mapped () const
Checks if file mapped.
Detailed Description
Memory mapped file class.
Definition at line 39 of file MMappedFile.h.
Constructor & Destructor Documentation
MMappedFile() [1/4]
MMappedFile ()
Constructor.
Definition at line 76 of file MMappedFile.cpp.
     : _filename(), _file_size(0), _map_size(0), _map_offset(0), _fp(nullptr), _data(nullptr)
 {
 }
MMappedFile() [2/4]
MMappedFile (std::string filename, size_t size, size_t offset)
Constructor.
Note
file will be created if it doesn't exist.
Parameters
[in] filename File to be mapped, if doesn't exist will be created.
[in] size Size of file to map
[in] offset Offset to mapping point, should be multiple of page size
Definition at line 81 of file MMappedFile.cpp.
     : _filename(std::move(filename)), _file_size(0), _map_size(size), _map_offset(offset), _fp(nullptr), _data(nullptr)
 {
     map(_filename, _map_size, _map_offset);
 }
References MMappedFile::map().
MMappedFile() [3/4]
MMappedFile (const MMappedFile &) delete
Prevent instances of this class from being copied (As this class contains pointers)
MMappedFile() [4/4]
MMappedFile (MMappedFile &&) default
Default move constructor.
~MMappedFile()
~MMappedFile ()
Destructor.
Definition at line 87 of file MMappedFile.cpp.
 {
     release();
 }
References MMappedFile::release().
Member Function Documentation
data()
unsigned char * data ()
Mapped data accessor.
Returns
Pointer to the mapped data, nullptr if not mapped
Definition at line 170 of file MMappedFile.cpp.
 {
     return static_cast<unsigned char *>(_data);
 }
Referenced by arm_compute::test::validation::TEST_CASE().
file_size()
size_t file_size () const
File size accessor.
Returns
Size of file
Definition at line 175 of file MMappedFile.cpp.
 {
     return _file_size;
 }
is_mapped()
bool is_mapped () const
Checks if file mapped.
Returns
True if file is mapped else false
Definition at line 185 of file MMappedFile.cpp.
 {
     return _data != nullptr;
 }
Referenced by MMappedFile::map(), and arm_compute::test::validation::TEST_CASE().
map()
bool map (const std::string & filename, size_t size, size_t offset)
Opens and maps a file.
Note
file will be created if it doesn't exist.
Parameters
[in] filename File to be mapped, if doesn't exist will be created.
[in] size Size of file to map. If 0 all the file will be mapped.
[in] offset Offset to mapping point, should be multiple of page size.
Returns
True if operation was successful else false
Definition at line 92 of file MMappedFile.cpp.
 {
     // Check if file is mapped
     if(is_mapped())
     {
         return false;
     }
     // Open file
     _fp = fopen(filename.c_str(), "a+be");
     if(_fp == nullptr)
     {
         return false;
     }
     // Extract file descriptor
     int  fd     = fileno(_fp);
     bool status = fd >= 0;
     if(status)
     {
         // Get file size
         std::tie(_file_size, status) = get_file_size(_filename);
         if(status)
         {
             // Map all file from offset if map size is 0
             _map_size   = (size == 0) ? _file_size : size;
             _map_offset = offset;
             // Check offset mapping
             if((_map_offset > _file_size) || (_map_offset % get_page_size() != 0))
             {
                 status = false;
             }
             else
             {
                 // Truncate to file size
                 if(_map_offset + _map_size > _file_size)
                 {
                     _map_size = _file_size - _map_offset;
                 }
                 // Perform mapping
                 _data = ::mmap(nullptr, _map_size, PROT_WRITE, MAP_SHARED, fd, _map_offset);
             }
         }
     }
     if(!status)
     {
         fclose(_fp);
     }
     return status;
 }
References MMappedFile::is_mapped(), and offset().
Referenced by MMappedFile::MMappedFile().
map_size()
size_t map_size () const
Map size accessor.
Returns
Mapping size
Definition at line 180 of file MMappedFile.cpp.
 {
     return _map_size;
 }
operator=() [1/2]
MMappedFile& operator= (const MMappedFile &) delete
Prevent instances of this class from being copied (As this class contains pointers)
operator=() [2/2]
MMappedFile& operator= (MMappedFile &&) default
Default move assignment operator.
release()
void release ()
Unmaps and closes file.
Definition at line 148 of file MMappedFile.cpp.
 {
     // Unmap file
     if(_data != nullptr)
     {
         ::munmap(_data, _file_size);
         _data = nullptr;
     }
     // Close file
     if(_fp != nullptr)
     {
         fclose(_fp);
         _fp = nullptr;
     }
     // Clear variables
     _file_size  = 0;
     _map_size   = 0;
     _map_offset = 0;
 }
Referenced by MMappedFile::~MMappedFile().
The documentation for this class was generated from the following files:
arm_compute/core/utils/misc/MMappedFile.h
src/core/utils/misc/MMappedFile.cpp