Compute Library: CLOpticalFlow Class Reference
CLOpticalFlow Class Reference
Basic function to execute optical flow.
#include <CLOpticalFlow.h>
Public Member Functions
CLOpticalFlow (std::shared_ptr< IMemoryManager > memory_manager=nullptr)
Default constructor.
CLOpticalFlow (const CLOpticalFlow &)=delete
Prevent instances of this class from being copied (As this class contains pointers)
CLOpticalFlow & operator= (const CLOpticalFlow &)=delete
Prevent instances of this class from being copied (As this class contains pointers)
CLOpticalFlow (CLOpticalFlow &&)=default
Allow instances of this class to be moved.
CLOpticalFlow & operator= (CLOpticalFlow &&)=default
Allow instances of this class to be moved.
void configure (const CLPyramid *old_pyramid, const CLPyramid *new_pyramid, const ICLKeyPointArray *old_points, const ICLKeyPointArray *new_points_estimates, ICLKeyPointArray *new_points, Termination termination, float epsilon, size_t num_iterations, size_t window_dimension, bool use_initial_estimate, BorderMode border_mode, uint8_t constant_border_value=0)
Initialise the function input and output.
void run () override
Run the kernels contained in the function.
Public Member Functions inherited from IFunction
virtual ~IFunction ()=default
Destructor.
virtual void prepare ()
Prepare the function for executing.
Detailed Description
Basic function to execute optical flow.
This function calls the following OpenCL kernels and functions:
CLScharr3x3
CLLKTrackerInitKernel
CLLKTrackerStage0Kernel
CLLKTrackerStage1Kernel
CLLKTrackerFinalizeKernel
Definition at line 61 of file CLOpticalFlow.h.
Constructor & Destructor Documentation
CLOpticalFlow() [1/3]
CLOpticalFlow (std::shared_ptr< IMemoryManager > memory_manager = nullptr)
Default constructor.
Definition at line 40 of file CLOpticalFlow.cpp.
     : _memory_group(std::move(memory_manager)),
       _tracker_init_kernel(),
       _tracker_stage0_kernel(),
       _tracker_stage1_kernel(),
       _tracker_finalize_kernel(),
       _func_scharr(),
       _scharr_gx(),
       _scharr_gy(),
       _old_points(nullptr),
       _new_points_estimates(nullptr),
       _new_points(nullptr),
       _old_points_internal(),
       _new_points_internal(),
       _coefficient_table(),
       _old_values(),
       _num_levels(0)
 {
 }
CLOpticalFlow() [2/3]
CLOpticalFlow (const CLOpticalFlow &) delete
Prevent instances of this class from being copied (As this class contains pointers)
CLOpticalFlow() [3/3]
CLOpticalFlow (CLOpticalFlow &&) default
Allow instances of this class to be moved.
Member Function Documentation
configure()
void configure (const CLPyramid * old_pyramid, const CLPyramid * new_pyramid, const ICLKeyPointArray * old_points, const ICLKeyPointArray * new_points_estimates, ICLKeyPointArray * new_points, Termination termination, float epsilon, size_t num_iterations, size_t window_dimension, bool use_initial_estimate, BorderMode border_mode, uint8_t constant_border_value = 0)
Initialise the function input and output.
Parameters
[in] old_pyramid Pointer to the pyramid for the old tensor. Data types supported U8
[in] new_pyramid Pointer to the pyramid for the new tensor. Data types supported U8
[in] old_points Pointer to the IKeyPointArray storing old key points
[in] new_points_estimates Pointer to the IKeyPointArray storing new estimates key points
[out] new_points Pointer to the IKeyPointArray storing new key points
[in] termination The criteria to terminate the search of each keypoint.
[in] epsilon The error for terminating the algorithm
[in] num_iterations The maximum number of iterations before terminate the alogrithm
[in] window_dimension The size of the window on which to perform the algorithm
[in] use_initial_estimate The flag to indicate whether the initial estimated position should be used
[in] border_mode The border mode applied at scharr kernel stage
[in] constant_border_value (Optional) Constant value to use for borders if border_mode is set to CONSTANT
Definition at line 60 of file CLOpticalFlow.cpp.
 {
     ARM_COMPUTE_ERROR_ON(nullptr == old_pyramid);
     ARM_COMPUTE_ERROR_ON(nullptr == new_pyramid);
     ARM_COMPUTE_ERROR_ON(nullptr == old_points);
     ARM_COMPUTE_ERROR_ON(nullptr == new_points_estimates);
     ARM_COMPUTE_ERROR_ON(nullptr == new_points);
     ARM_COMPUTE_ERROR_ON(old_pyramid->info()->num_levels() != new_pyramid->info()->num_levels());
     ARM_COMPUTE_ERROR_ON(0 == old_pyramid->info()->num_levels());
     ARM_COMPUTE_ERROR_ON(old_pyramid->info()->width() != new_pyramid->info()->width());
     ARM_COMPUTE_ERROR_ON(old_pyramid->info()->height() != new_pyramid->info()->height());
     ARM_COMPUTE_ERROR_ON(use_initial_estimate && old_points->num_values() != new_points_estimates->num_values());
     // Set member variables
     _old_points           = old_points;
     _new_points_estimates = new_points_estimates;
     _new_points           = new_points;
     _num_levels           = old_pyramid->info()->num_levels();
     const float pyr_scale              = old_pyramid->info()->scale();
     const int   list_length            = old_points->num_values();
     const int   old_values_list_length = list_length * window_dimension * window_dimension;
     // Create kernels and tensors
     _tracker_init_kernel.resize(_num_levels);
     _tracker_stage0_kernel.resize(_num_levels);
     _tracker_stage1_kernel.resize(_num_levels);
     _func_scharr.resize(_num_levels);
     _scharr_gx.resize(_num_levels);
     _scharr_gy.resize(_num_levels);
     // Create internal keypoint arrays
     _old_points_internal = arm_compute::support::cpp14::make_unique<CLLKInternalKeypointArray>(list_length);
     _old_points_internal->resize(list_length);
     _new_points_internal = arm_compute::support::cpp14::make_unique<CLLKInternalKeypointArray>(list_length);
     _new_points_internal->resize(list_length);
     _coefficient_table = arm_compute::support::cpp14::make_unique<CLCoefficientTableArray>(list_length);
     _coefficient_table->resize(list_length);
     _old_values = arm_compute::support::cpp14::make_unique<CLOldValueArray>(old_values_list_length);
     _old_values->resize(old_values_list_length);
     _new_points->resize(list_length);
     for(size_t i = 0; i < _num_levels; ++i)
     {
         // Get images from the ith level of old and right pyramid
         ICLImage *old_ith_input = old_pyramid->get_pyramid_level(i);
         ICLImage *new_ith_input = new_pyramid->get_pyramid_level(i);
         // Get width and height of images
         const unsigned int width_ith  = old_ith_input->info()->dimension(0);
         const unsigned int height_ith = new_ith_input->info()->dimension(1);
         // Initialize Scharr tensors
         TensorInfo tensor_info(TensorShape(width_ith, height_ith), 1, DataType::S16);
         _scharr_gx[i].allocator()->init(tensor_info);
         _scharr_gy[i].allocator()->init(tensor_info);
         // Manage intermediate buffers
         _memory_group.manage(&_scharr_gx[i]);
         _memory_group.manage(&_scharr_gy[i]);
         // Init Scharr kernel
         _func_scharr[i].configure(old_ith_input, &_scharr_gx[i], &_scharr_gy[i], border_mode, constant_border_value);
         // Init Lucas-Kanade init kernel
         _tracker_init_kernel[i].configure(old_points, new_points_estimates, _old_points_internal.get(), _new_points_internal.get(), use_initial_estimate, i, _num_levels, pyr_scale);
         // Init Lucas-Kanade stage0 kernel
         _tracker_stage0_kernel[i].configure(old_ith_input, &_scharr_gx[i], &_scharr_gy[i],
                                             _old_points_internal.get(), _new_points_internal.get(), _coefficient_table.get(), _old_values.get(),
                                             window_dimension, i);
         // Init Lucas-Kanade stage1 kernel
         _tracker_stage1_kernel[i].configure(new_ith_input, _new_points_internal.get(), _coefficient_table.get(), _old_values.get(),
                                             termination, epsilon, num_iterations, window_dimension, i);
         // Allocate intermediate buffers
         _scharr_gx[i].allocator()->allocate();
         _scharr_gy[i].allocator()->allocate();
     }
     // Finalize Lucas-Kanade
     _tracker_finalize_kernel.configure(_new_points_internal.get(), new_points);
 }
References ARM_COMPUTE_ERROR_ON, arm_compute::test::validation::border_mode, CLLKTrackerFinalizeKernel::configure(), ITensorInfo::dimension(), epsilon, CLPyramid::get_pyramid_level(), PyramidInfo::height(), ITensor::info(), CLPyramid::info(), MemoryGroupBase< TensorType >::manage(), PyramidInfo::num_levels(), IArray< T >::num_values(), IArray< T >::resize(), arm_compute::S16, PyramidInfo::scale(), and PyramidInfo::width().
operator=() [1/2]
CLOpticalFlow& operator= (const CLOpticalFlow &) delete
Prevent instances of this class from being copied (As this class contains pointers)
operator=() [2/2]
CLOpticalFlow& operator= (CLOpticalFlow &&) default
Allow instances of this class to be moved.
run()
void run () override virtual
Run the kernels contained in the function.
For NEON kernels:
Multi-threading is used for the kernels which are parallelisable.
By default std::thread::hardware_concurrency() threads are used.
Note
CPPScheduler::set_num_threads() can be used to manually set the number of threads
For OpenCL kernels:
All the kernels are enqueued on the queue associated with CLScheduler.
The queue is then flushed.
Note
The function will not block until the kernels are executed. It is the user's responsibility to wait.
Will call prepare() on first run if hasn't been done
Implements IFunction.
Definition at line 148 of file CLOpticalFlow.cpp.
 {
     ARM_COMPUTE_ERROR_ON_MSG(_num_levels == 0, "Unconfigured function");
     MemoryGroupResourceScope scope_mg(_memory_group);
     for(unsigned int level = _num_levels; level > 0; --level)
     {
         // Run Scharr kernel
         _func_scharr[level - 1].run();
         // Run Lucas-Kanade init kernel
         CLScheduler::get().enqueue(_tracker_init_kernel[level - 1]);
         // Run Lucas-Kanade stage0 kernel
         CLScheduler::get().enqueue(_tracker_stage0_kernel[level - 1]);
         // Run Lucas-Kanade stage1 kernel
         CLScheduler::get().enqueue(_tracker_stage1_kernel[level - 1]);
     }
     CLScheduler::get().enqueue(_tracker_finalize_kernel, true);
 }
References ARM_COMPUTE_ERROR_ON_MSG, CLScheduler::enqueue(), and CLScheduler::get().
The documentation for this class was generated from the following files:
arm_compute/runtime/CL/functions/CLOpticalFlow.h
src/runtime/CL/functions/CLOpticalFlow.cpp