Compute Library: IPyramid Class Reference
IPyramid Class Reference abstract
Interface for pyramid data-object.
#include <IPyramid.h>
Public Member Functions
virtual ~IPyramid ()=default
Default virtual destructor.
virtual const PyramidInfo * info () const =0
Interface to be implemented by the child class to return the Pyramid's metadata.
virtual ITensor * get_pyramid_level (size_t index) const =0
Retrieves a level of the pyramid as a ITensor pointer.
Detailed Description
Interface for pyramid data-object.
Definition at line 36 of file IPyramid.h.
Constructor & Destructor Documentation
~IPyramid()
virtual ~IPyramid () virtual default
Default virtual destructor.
Member Function Documentation
get_pyramid_level()
virtual ITensor* get_pyramid_level (size_t index) const pure virtual
Retrieves a level of the pyramid as a ITensor pointer.
Parameters
[in] index The index of the level, such that index is less than levels.
Returns
An ITensor pointer
Implemented in CLPyramid, and Pyramid.
Referenced by NELaplacianPyramid::configure(), NELaplacianReconstruct::configure(), NEGaussianPyramidHalf::configure(), and NEGaussianPyramidOrb::configure().
info()
virtual const PyramidInfo* info () const pure virtual
Interface to be implemented by the child class to return the Pyramid's metadata.
Returns
A pointer to the Pyramid's metadata.
Implemented in CLPyramid, and Pyramid.
Referenced by NELaplacianPyramid::configure(), NELaplacianReconstruct::configure(), NEGaussianPyramidHalf::configure(), and NEGaussianPyramidOrb::configure().
The documentation for this class was generated from the following file:
arm_compute/core/IPyramid.h