Compute Library: NEChannelShuffleLayerKernel Class Reference
NEChannelShuffleLayerKernel Class Reference
Interface for the channel shuffle kernel.
#include <NEChannelShuffleLayerKernel.h>
Public Member Functions
const char * name () const override
Name of the kernel.
NEChannelShuffleLayerKernel ()
Default constructor.
NEChannelShuffleLayerKernel (const NEChannelShuffleLayerKernel &)=delete
Prevent instances of this class from being copied (As this class contains pointers)
NEChannelShuffleLayerKernel & operator= (const NEChannelShuffleLayerKernel &)=delete
Prevent instances of this class from being copied (As this class contains pointers)
NEChannelShuffleLayerKernel (NEChannelShuffleLayerKernel &&)=default
Allow instances of this class to be moved.
NEChannelShuffleLayerKernel & operator= (NEChannelShuffleLayerKernel &&)=default
Allow instances of this class to be moved.
~NEChannelShuffleLayerKernel ()=default
Default destructor.
void configure (const ITensor *input, ITensor *output, unsigned int num_groups)
Configure function's inputs and outputs.
void run (const Window &window, const ThreadInfo &info) override
Execute the kernel on the passed window.
Public Member Functions inherited from ICPPKernel
virtual ~ICPPKernel ()=default
Default destructor.
Public Member Functions inherited from IKernel
IKernel ()
Constructor.
virtual ~IKernel ()=default
Destructor.
virtual bool is_parallelisable () const
Indicates whether or not the kernel is parallelisable.
virtual BorderSize border_size () const
The size of the border for that kernel.
const Window & window () const
The maximum window the kernel can be executed on.
Static Public Member Functions
static Status validate (const ITensorInfo *input, const ITensorInfo *output, unsigned int num_groups)
Static function to check if given info will lead to a valid configuration of NEChannelShuffleLayerKernel.
Detailed Description
Interface for the channel shuffle kernel.
Definition at line 35 of file NEChannelShuffleLayerKernel.h.
Constructor & Destructor Documentation
NEChannelShuffleLayerKernel() [1/3]
NEChannelShuffleLayerKernel ()
Default constructor.
Definition at line 139 of file NEChannelShuffleLayerKernel.cpp.
     : _input(nullptr), _output(nullptr), _num_groups()
 {
 }
NEChannelShuffleLayerKernel() [2/3]
NEChannelShuffleLayerKernel (const NEChannelShuffleLayerKernel &) delete
Prevent instances of this class from being copied (As this class contains pointers)
NEChannelShuffleLayerKernel() [3/3]
NEChannelShuffleLayerKernel (NEChannelShuffleLayerKernel &&) default
Allow instances of this class to be moved.
~NEChannelShuffleLayerKernel()
~NEChannelShuffleLayerKernel () default
Default destructor.
Member Function Documentation
configure()
void configure (const ITensor * input, ITensor * output, unsigned int num_groups)
Configure function's inputs and outputs.
Parameters
[in] input Input tensor. Data types supported: U8/S8/QASYMM8/U16/S16/F16/U32/S32/F32
[out] output Output tensor. Data type supported: Same as input
[in] num_groups Number of groups. Must be greater than 1 and the number of channels of the tensors must be a multiple of the number of groups.
Definition at line 144 of file NEChannelShuffleLayerKernel.cpp.
 {
     ARM_COMPUTE_ERROR_ON_NULLPTR(input, output);
     // Output tensor auto initialization if not yet initialized
     auto_init_if_empty(*output->info(), *input->info()->clone());
     _input      = input;
     _output     = output;
     _num_groups = num_groups;
     ARM_COMPUTE_ERROR_THROW_ON(validate_arguments(input->info(), output->info(), num_groups));
     // Configure kernel window
     Window win = calculate_max_window(*input->info(), Steps());
     // The NEChannelShuffleLayerKernel doesn't need padding so update_window_and_padding() can be skipped
     Coordinates coord;
     coord.set_num_dimensions(output->info()->num_dimensions());
     output->info()->set_valid_region(ValidRegion(coord, output->info()->tensor_shape()));
     INEKernel::configure(win);
 }
References ARM_COMPUTE_ERROR_ON_NULLPTR, ARM_COMPUTE_ERROR_THROW_ON, arm_compute::auto_init_if_empty(), arm_compute::calculate_max_window(), ICloneable< T >::clone(), ITensor::info(), ITensorInfo::num_dimensions(), Dimensions< T >::set_num_dimensions(), ITensorInfo::set_valid_region(), and ITensorInfo::tensor_shape().
name()
const char* name () const inline override virtual
Name of the kernel.
Returns
Kernel name
Implements ICPPKernel.
Definition at line 38 of file NEChannelShuffleLayerKernel.h.
     {
         return "NEChannelShuffleLayerKernel";
     }
operator=() [1/2]
NEChannelShuffleLayerKernel& operator= (const NEChannelShuffleLayerKernel &) delete
Prevent instances of this class from being copied (As this class contains pointers)
operator=() [2/2]
NEChannelShuffleLayerKernel& operator= (NEChannelShuffleLayerKernel &&) default
Allow instances of this class to be moved.
run()
void run (const Window & window, const ThreadInfo & info) override virtual
Execute the kernel on the passed window.
Warning
If is_parallelisable() returns false then the passed window must be equal to window()
Note
The window has to be a region within the window returned by the window() method
The width of the window has to be a multiple of num_elems_processed_per_iteration().
Parameters
[in] window Region on which to execute the kernel. (Must be a region of the window returned by window())
[in] info Info about executing thread and CPU.
Implements ICPPKernel.
Definition at line 174 of file NEChannelShuffleLayerKernel.cpp.
 {
     ARM_COMPUTE_UNUSED(info);
     ARM_COMPUTE_ERROR_ON_UNCONFIGURED_KERNEL(this);
     ARM_COMPUTE_ERROR_ON_INVALID_SUBWINDOW(IKernel::window(), window);
     switch(_input->info()->data_layout())
     {
         case DataLayout::NHWC:
             channel_shuffle_nhwc(_input, _output, _num_groups, window);
             break;
         case DataLayout::NCHW:
             channel_shuffle_nchw(_input, _output, _num_groups, window);
             break;
         default:
             ARM_COMPUTE_ERROR("Unsupported data layout!");
             break;
     }
 }
References ARM_COMPUTE_ERROR, ARM_COMPUTE_ERROR_ON_INVALID_SUBWINDOW, ARM_COMPUTE_ERROR_ON_UNCONFIGURED_KERNEL, ARM_COMPUTE_UNUSED, ITensorInfo::data_layout(), ITensor::info(), arm_compute::test::validation::info, arm_compute::NCHW, arm_compute::NHWC, and IKernel::window().
validate()
Status validate (const ITensorInfo * input, const ITensorInfo * output, unsigned int num_groups) static
Static function to check if given info will lead to a valid configuration of NEChannelShuffleLayerKernel.
Parameters
[in] input Input tensor. Data types supported: U8/S8/QASYMM8/U16/S16/F16/U32/S32/F32
[out] output Output tensor. Data type supported: Same as input
[in] num_groups Number of groups. Must be greater than 1 and the number of channels of the tensors must be a multiple of the number of groups.
Returns
a status
Definition at line 168 of file NEChannelShuffleLayerKernel.cpp.
 {
     ARM_COMPUTE_RETURN_ON_ERROR(validate_arguments(input, output, num_groups));
     return Status{};
 }
References ARM_COMPUTE_RETURN_ON_ERROR.
Referenced by NEChannelShuffleLayer::validate().
The documentation for this class was generated from the following files:
arm_compute/core/NEON/kernels/NEChannelShuffleLayerKernel.h
src/core/NEON/kernels/NEChannelShuffleLayerKernel.cpp