Compute Library: CLMinMaxLayerKernel Class Reference
CLMinMaxLayerKernel Class Reference
Interface for the kernel to perform min max search on a 3D tensor.
#include <CLMinMaxLayerKernel.h>
Public Member Functions
CLMinMaxLayerKernel ()
Default constructor.
CLMinMaxLayerKernel (const CLMinMaxLayerKernel &)=delete
Prevent instances of this class from being copied (As this class contains pointers)
CLMinMaxLayerKernel & operator= (const CLMinMaxLayerKernel &)=delete
Prevent instances of this class from being copied (As this class contains pointers)
CLMinMaxLayerKernel (CLMinMaxLayerKernel &&)=default
Allow instances of this class to be moved.
CLMinMaxLayerKernel & operator= (CLMinMaxLayerKernel &&)=default
Allow instances of this class to be moved.
void configure (const ICLTensor *input, ICLTensor *output)
Initialise the kernel's input and output.
void reset (cl::CommandQueue &queue)
Resets global minimum and maximum.
void run (const Window &window, cl::CommandQueue &queue) override
Enqueue the OpenCL kernel to process the given window on the passed OpenCL command queue.
Public Member Functions inherited from ICLKernel
ICLKernel ()
Constructor.
cl::Kernel & kernel ()
Returns a reference to the OpenCL kernel of this object.
template<typename T >
void add_1D_array_argument (unsigned int &idx, const ICLArray< T > *array, const Strides &strides, unsigned int num_dimensions, const Window &window)
Add the passed 1D array's parameters to the object's kernel's arguments starting from the index idx.
void add_1D_tensor_argument (unsigned int &idx, const ICLTensor *tensor, const Window &window)
Add the passed 1D tensor's parameters to the object's kernel's arguments starting from the index idx.
void add_2D_tensor_argument (unsigned int &idx, const ICLTensor *tensor, const Window &window)
Add the passed 2D tensor's parameters to the object's kernel's arguments starting from the index idx.
void add_3D_tensor_argument (unsigned int &idx, const ICLTensor *tensor, const Window &window)
Add the passed 3D tensor's parameters to the object's kernel's arguments starting from the index idx.
void add_4D_tensor_argument (unsigned int &idx, const ICLTensor *tensor, const Window &window)
Add the passed 4D tensor's parameters to the object's kernel's arguments starting from the index idx.
template<typename T >
void add_argument (unsigned int &idx, T value)
Add the passed parameters to the object's kernel's arguments starting from the index idx.
void set_lws_hint (const cl::NDRange &lws_hint)
Set the Local-Workgroup-Size hint.
cl::NDRange lws_hint () const
Return the Local-Workgroup-Size hint.
const std::string & config_id () const
Get the configuration ID.
void set_target (GPUTarget target)
Set the targeted GPU architecture.
void set_target (cl::Device &device)
Set the targeted GPU architecture according to the CL device.
GPUTarget get_target () const
Get the targeted GPU architecture.
size_t get_max_workgroup_size ()
Get the maximum workgroup size for the device the CLKernelLibrary uses.
template<typename T , unsigned int dimension_size>
void add_array_argument (unsigned &idx, const ICLArray< T > *array, const Strides &strides, unsigned int num_dimensions, const Window &window)
Add the passed array's parameters to the object's kernel's arguments starting from the index idx.
template<unsigned int dimension_size>
void add_tensor_argument (unsigned &idx, const ICLTensor *tensor, const Window &window)
Public Member Functions inherited from IKernel
IKernel ()
Constructor.
virtual ~IKernel ()=default
Destructor.
virtual bool is_parallelisable () const
Indicates whether or not the kernel is parallelisable.
virtual BorderSize border_size () const
The size of the border for that kernel.
const Window & window () const
The maximum window the kernel can be executed on.
Static Public Member Functions
static Status validate (const ITensorInfo *input, const ITensorInfo *output)
Static function to check if given info will lead to a valid configuration of CLMinMaxLayerKernel.
Static Public Member Functions inherited from ICLKernel
static constexpr unsigned int num_arguments_per_1D_array ()
Returns the number of arguments enqueued per 1D array object.
static constexpr unsigned int num_arguments_per_1D_tensor ()
Returns the number of arguments enqueued per 1D tensor object.
static constexpr unsigned int num_arguments_per_2D_tensor ()
Returns the number of arguments enqueued per 2D tensor object.
static constexpr unsigned int num_arguments_per_3D_tensor ()
Returns the number of arguments enqueued per 3D tensor object.
static constexpr unsigned int num_arguments_per_4D_tensor ()
Returns the number of arguments enqueued per 4D tensor object.
static cl::NDRange gws_from_window (const Window &window)
Get the global work size given an execution window.
Detailed Description
Interface for the kernel to perform min max search on a 3D tensor.
Definition at line 35 of file CLMinMaxLayerKernel.h.
Constructor & Destructor Documentation
CLMinMaxLayerKernel() [1/3]
CLMinMaxLayerKernel ()
Default constructor.
Definition at line 83 of file CLMinMaxLayerKernel.cpp.
     : _input(nullptr), _output(nullptr)
 {
 }
CLMinMaxLayerKernel() [2/3]
CLMinMaxLayerKernel (const CLMinMaxLayerKernel &) delete
Prevent instances of this class from being copied (As this class contains pointers)
CLMinMaxLayerKernel() [3/3]
CLMinMaxLayerKernel (CLMinMaxLayerKernel &&) default
Allow instances of this class to be moved.
Member Function Documentation
configure()
void configure (const ICLTensor * input, ICLTensor * output)
Initialise the kernel's input and output.
Parameters
[in] input Input tensor with at least 3 dimensions. The dimensions over the third will be interpreted as batches.Data types supported: F32.
[out] output Output tensor with shape [2, batches, ...] which stores the minimum and maximum values for each 3D input tensor. The dimensions over the second must match the batched dimensions of the input tensor. Data types supported: F32.
Definition at line 88 of file CLMinMaxLayerKernel.cpp.
 {
     ARM_COMPUTE_ERROR_ON_NULLPTR(input, output);
     ARM_COMPUTE_ERROR_THROW_ON(validate_arguments(input->info(), output->info()));
     _input  = input;
     _output = output;
     std::set<std::string> build_opts;
     build_opts.emplace("-DWIDTH=" + support::cpp11::to_string(input->info()->dimension(0)));
     build_opts.emplace("-DHEIGHT=" + support::cpp11::to_string(input->info()->dimension(1)));
     build_opts.emplace("-DDEPTH=" + support::cpp11::to_string(input->info()->dimension(2)));
     // Create kernel
     _kernel = static_cast<cl::Kernel>(CLKernelLibrary::get().create_kernel("minmax_layer", build_opts));
     auto win_config = validate_and_configure_window(input->info(), output->info());
     ARM_COMPUTE_ERROR_THROW_ON(std::get<0>(win_config));
     ICLKernel::configure_internal(std::get<1>(win_config));
 }
References ARM_COMPUTE_ERROR_ON_NULLPTR, ARM_COMPUTE_ERROR_THROW_ON, arm_compute::create_kernel(), ITensorInfo::dimension(), CLKernelLibrary::get(), ITensor::info(), and arm_compute::support::cpp11::to_string().
operator=() [1/2]
CLMinMaxLayerKernel& operator= (const CLMinMaxLayerKernel &) delete
Prevent instances of this class from being copied (As this class contains pointers)
operator=() [2/2]
CLMinMaxLayerKernel& operator= (CLMinMaxLayerKernel &&) default
Allow instances of this class to be moved.
reset()
void reset (cl::CommandQueue & queue)
Resets global minimum and maximum.
Parameters
[in,out] queue Command queue on which to map and unmap the min_max tensor
Definition at line 119 of file CLMinMaxLayerKernel.cpp.
 {
     _output->map(queue, true);
     Window window_output;
     window_output.use_tensor_dimensions(_output->info()->tensor_shape());
     window_output.set(Window::DimX, Window::Dimension(0, 1, 1));
     Iterator output(_output, window_output);
     // Reset output
     execute_window_loop(window_output, [&](const Coordinates &)
     {
         auto *ptr = reinterpret_cast<float *>(output.ptr());
         ptr[0]    = std::numeric_limits<float>::max();
         ptr[1]    = std::numeric_limits<float>::min();
     },
     output);
     _output->unmap(queue);
 }
References Window::DimX, arm_compute::execute_window_loop(), ITensor::info(), ICLTensor::map(), Iterator::ptr(), Window::set(), ITensorInfo::tensor_shape(), ICLTensor::unmap(), and Window::use_tensor_dimensions().
run()
void run (const Window & window, cl::CommandQueue & queue) override virtual
Enqueue the OpenCL kernel to process the given window on the passed OpenCL command queue.
Note
The queue is not flushed by this method, and therefore the kernel will not have been executed by the time this method returns.
Parameters
[in] window Region on which to execute the kernel. (Must be a valid region of the window returned by window()).
[in,out] queue Command queue on which to enqueue the kernel.
Implements ICLKernel.
Definition at line 141 of file CLMinMaxLayerKernel.cpp.
 {
     ARM_COMPUTE_ERROR_ON_UNCONFIGURED_KERNEL(this);
     ARM_COMPUTE_ERROR_ON_INVALID_SUBWINDOW(IKernel::window(), window);
     Window window_collapsed = window.collapse_if_possible(ICLKernel::window(), 3);
     Window slice            = window_collapsed.first_slice_window_3D();
     slice.set(Window::DimX, Window::Dimension(0, 1, 1));
     slice.set(Window::DimY, Window::Dimension(0, 1, 1));
     slice.set(Window::DimZ, Window::Dimension(0, 1, 1));
     do
     {
         Window output_slice = slice.shift_dimensions(2);
         unsigned int idx = 0;
         // Set inputs
         add_3D_tensor_argument(idx, _input, slice);
         add_1D_tensor_argument(idx, _output, output_slice);
         enqueue(queue, *this, slice);
     }
     while(window_collapsed.slide_window_slice_3D(slice));
 }
References ICLKernel::add_1D_tensor_argument(), ICLKernel::add_3D_tensor_argument(), ARM_COMPUTE_ERROR_ON_INVALID_SUBWINDOW, ARM_COMPUTE_ERROR_ON_UNCONFIGURED_KERNEL, Window::collapse_if_possible(), Window::DimX, Window::DimY, Window::DimZ, arm_compute::enqueue(), Window::first_slice_window_3D(), arm_compute::test::validation::reference::slice(), Window::slide_window_slice_3D(), and IKernel::window().
validate()
Status validate (const ITensorInfo * input, const ITensorInfo * output) static
Static function to check if given info will lead to a valid configuration of CLMinMaxLayerKernel.
Parameters
[in] input Input tensor info. Data types supported: F32.
[in] output Output tensor info with shape [2, batches, ...] which stores the minimum and maximum values for each 3D input tensor. The dimensions over the second must match the batched dimensions of the input tensor. Data types supported: F32.
Returns
a status
Definition at line 111 of file CLMinMaxLayerKernel.cpp.
 {
     ARM_COMPUTE_RETURN_ON_ERROR(validate_arguments(input, output));
     ARM_COMPUTE_RETURN_ON_ERROR(std::get<0>(validate_and_configure_window(input->clone().get(), output->clone().get())));
     return Status{};
 }
References ARM_COMPUTE_RETURN_ON_ERROR, and ICloneable< T >::clone().
The documentation for this class was generated from the following files:
arm_compute/core/CL/kernels/CLMinMaxLayerKernel.h
src/core/CL/kernels/CLMinMaxLayerKernel.cpp