Compute Library: SubStream Class Reference
SubStream Class Reference final
Sub stream class.
#include <SubStream.h>
Public Member Functions
SubStream (IStream &s)
Default Constructor.
void add_layer (ILayer &layer) override
Adds a layer to the stream.
Graph & graph () override
Returns the underlying graph.
const Graph & graph () const override
Returns the underlying graph.
Public Member Functions inherited from IStream
virtual ~IStream ()=default
NodeID tail_node ()
Returns the tail node of the Stream.
StreamHints & hints ()
Returns the stream hints that are currently used.
void forward_tail (NodeID nid)
Forwards tail of stream to a given nid.
Detailed Description
Sub stream class.
Definition at line 47 of file SubStream.h.
Constructor & Destructor Documentation
SubStream()
SubStream (IStream & s)
Default Constructor.
Parameters
[in] s Parent stream
Definition at line 35 of file SubStream.cpp.
     : _s(s)
 {
     _hints     = s.hints();
     _tail_node = s.tail_node();
 }
References IStream::hints(), and IStream::tail_node().
Member Function Documentation
add_layer()
void add_layer (ILayer & layer) override virtual
Adds a layer to the stream.
Parameters
[in] layer Layer to add
Implements IStream.
Definition at line 42 of file SubStream.cpp.
 {
     auto nid   = layer.create_layer(*this);
     _tail_node = nid;
 }
References ILayer::create_layer().
graph() [1/2]
Graph & graph () override virtual
Returns the underlying graph.
Returns
Underlying graph
Implements IStream.
Definition at line 53 of file SubStream.cpp.
 {
     return _s.graph();
 }
References IStream::graph().
graph() [2/2]
const Graph & graph () const override virtual
Returns the underlying graph.
Returns
Underlying graph
Implements IStream.
Definition at line 48 of file SubStream.cpp.
 {
     return _s.graph();
 }
References IStream::graph().
The documentation for this class was generated from the following files:
arm_compute/graph/frontend/SubStream.h
src/graph/frontend/SubStream.cpp