Compute Library: CLAccumulateWeightedKernel Class Reference
CLAccumulateWeightedKernel Class Reference
Interface for the accumulate weighted kernel.
#include <CLAccumulateKernel.h>
Public Member Functions
void configure (const ICLTensor *input, float alpha, ICLTensor *accum)
Set the input and accumulation images, and the scale value.
Public Member Functions inherited from ICLSimple2DKernel
void run (const Window &window, cl::CommandQueue &queue) override
Enqueue the OpenCL kernel to process the given window on the passed OpenCL command queue.
Public Member Functions inherited from ICLSimpleKernel
ICLSimpleKernel ()
Constructor.
ICLSimpleKernel (const ICLSimpleKernel &)=delete
Prevent instances of this class from being copied (As this class contains pointers)
ICLSimpleKernel & operator= (const ICLSimpleKernel &)=delete
Prevent instances of this class from being copied (As this class contains pointers)
ICLSimpleKernel (ICLSimpleKernel &&)=default
Allow instances of this class to be moved.
ICLSimpleKernel & operator= (ICLSimpleKernel &&)=default
Allow instances of this class to be moved.
~ICLSimpleKernel ()=default
Default destructor.
void configure (const ICLTensor *input, ICLTensor *output, unsigned int num_elems_processed_per_iteration, bool border_undefined=false, const BorderSize &border_size=BorderSize())
Configure the kernel.
Public Member Functions inherited from ICLKernel
ICLKernel ()
Constructor.
cl::Kernel & kernel ()
Returns a reference to the OpenCL kernel of this object.
template<typename T >
void add_1D_array_argument (unsigned int &idx, const ICLArray< T > *array, const Strides &strides, unsigned int num_dimensions, const Window &window)
Add the passed 1D array's parameters to the object's kernel's arguments starting from the index idx.
void add_1D_tensor_argument (unsigned int &idx, const ICLTensor *tensor, const Window &window)
Add the passed 1D tensor's parameters to the object's kernel's arguments starting from the index idx.
void add_2D_tensor_argument (unsigned int &idx, const ICLTensor *tensor, const Window &window)
Add the passed 2D tensor's parameters to the object's kernel's arguments starting from the index idx.
void add_3D_tensor_argument (unsigned int &idx, const ICLTensor *tensor, const Window &window)
Add the passed 3D tensor's parameters to the object's kernel's arguments starting from the index idx.
void add_4D_tensor_argument (unsigned int &idx, const ICLTensor *tensor, const Window &window)
Add the passed 4D tensor's parameters to the object's kernel's arguments starting from the index idx.
template<typename T >
void add_argument (unsigned int &idx, T value)
Add the passed parameters to the object's kernel's arguments starting from the index idx.
void set_lws_hint (const cl::NDRange &lws_hint)
Set the Local-Workgroup-Size hint.
cl::NDRange lws_hint () const
Return the Local-Workgroup-Size hint.
const std::string & config_id () const
Get the configuration ID.
void set_target (GPUTarget target)
Set the targeted GPU architecture.
void set_target (cl::Device &device)
Set the targeted GPU architecture according to the CL device.
GPUTarget get_target () const
Get the targeted GPU architecture.
size_t get_max_workgroup_size ()
Get the maximum workgroup size for the device the CLKernelLibrary uses.
template<typename T , unsigned int dimension_size>
void add_array_argument (unsigned &idx, const ICLArray< T > *array, const Strides &strides, unsigned int num_dimensions, const Window &window)
Add the passed array's parameters to the object's kernel's arguments starting from the index idx.
template<unsigned int dimension_size>
void add_tensor_argument (unsigned &idx, const ICLTensor *tensor, const Window &window)
Public Member Functions inherited from IKernel
IKernel ()
Constructor.
virtual ~IKernel ()=default
Destructor.
virtual bool is_parallelisable () const
Indicates whether or not the kernel is parallelisable.
virtual BorderSize border_size () const
The size of the border for that kernel.
const Window & window () const
The maximum window the kernel can be executed on.
Additional Inherited Members
Static Public Member Functions inherited from ICLKernel
static constexpr unsigned int num_arguments_per_1D_array ()
Returns the number of arguments enqueued per 1D array object.
static constexpr unsigned int num_arguments_per_1D_tensor ()
Returns the number of arguments enqueued per 1D tensor object.
static constexpr unsigned int num_arguments_per_2D_tensor ()
Returns the number of arguments enqueued per 2D tensor object.
static constexpr unsigned int num_arguments_per_3D_tensor ()
Returns the number of arguments enqueued per 3D tensor object.
static constexpr unsigned int num_arguments_per_4D_tensor ()
Returns the number of arguments enqueued per 4D tensor object.
static cl::NDRange gws_from_window (const Window &window)
Get the global work size given an execution window.
Detailed Description
Interface for the accumulate weighted kernel.
Weighted accumulation is computed:
\[ accum(x,y) = (1 - \alpha)*accum(x,y) + \alpha*input(x,y) \]
Where \(0 \le \alpha \le 1 \) Conceptually, the rounding for this is defined as:
\[ output(x,y)= uint8((1 - \alpha) * float32(int32(output(x,y))) + \alpha * float32(int32(input(x,y)))) \]
Definition at line 60 of file CLAccumulateKernel.h.
Member Function Documentation
configure()
void configure (const ICLTensor * input, float alpha, ICLTensor * accum)
Set the input and accumulation images, and the scale value.
Parameters
[in] input Source tensor. Data types supported: U8.
[in] alpha Scalar value in the range [0, 1.0]. Data types supported: F32.
[in,out] accum Accumulated tensor. Data types supported: U8.
Definition at line 49 of file CLAccumulateKernel.cpp.
 {
     ARM_COMPUTE_ERROR_ON_DATA_TYPE_CHANNEL_NOT_IN(input, 1, DataType::U8);
     ARM_COMPUTE_ERROR_ON_DATA_TYPE_CHANNEL_NOT_IN(accum, 1, DataType::U8);
     ARM_COMPUTE_ERROR_ON(alpha < 0.0 || alpha > 1.0);
     // Create kernel
     _kernel = static_cast<cl::Kernel>(CLKernelLibrary::get().create_kernel("accumulate_weighted"));
     // Set static kernel arguments
     unsigned int idx = 2 * num_arguments_per_2D_tensor(); //Skip the input and output parameters
     _kernel.setArg(idx++, alpha);
     // Configure kernel window
     constexpr unsigned int num_elems_processed_per_iteration = 16;
     ICLSimple2DKernel::configure(input, accum, num_elems_processed_per_iteration);
 }
References arm_compute::test::validation::alpha, ARM_COMPUTE_ERROR_ON, ARM_COMPUTE_ERROR_ON_DATA_TYPE_CHANNEL_NOT_IN, ICLSimpleKernel::configure(), arm_compute::create_kernel(), CLKernelLibrary::get(), ICLKernel::num_arguments_per_2D_tensor(), and arm_compute::U8.
The documentation for this class was generated from the following files:
arm_compute/core/CL/kernels/CLAccumulateKernel.h
src/core/CL/kernels/CLAccumulateKernel.cpp