Compute Library: TFPreproccessor Class Reference
TFPreproccessor Class Reference
TF preproccessor.
#include <GraphUtils.h>
Public Member Functions
TFPreproccessor (float min_range=-1.f, float max_range=1.f)
Constructor.
void preprocess (ITensor &tensor) override
Preprocess the given tensor.
Public Member Functions inherited from IPreprocessor
virtual ~IPreprocessor ()=default
Default destructor.
Detailed Description
TF preproccessor.
Definition at line 79 of file GraphUtils.h.
Constructor & Destructor Documentation
TFPreproccessor()
TFPreproccessor (float min_range = -1.f, float max_range = 1.f)
Constructor.
Parameters
[in] min_range Min normalization range. (Defaults to -1.f)
[in] max_range Max normalization range. (Defaults to 1.f)
Definition at line 60 of file GraphUtils.cpp.
     : _min_range(min_range), _max_range(max_range)
 {
 }
Member Function Documentation
preprocess()
void preprocess (ITensor & tensor) override virtual
Preprocess the given tensor.
Parameters
[in] tensor Tensor to preprocess.
Implements IPreprocessor.
Definition at line 64 of file GraphUtils.cpp.
 {
     Window window;
     window.use_tensor_dimensions(tensor.info()->tensor_shape());
     const float range = _max_range - _min_range;
     execute_window_loop(window, [&](const Coordinates & id)
     {
         const float value                                     = *reinterpret_cast<float *>(tensor.ptr_to_element(id));
         float       res                                       = value / 255.f;            // Normalize to [0, 1]
         res                                                   = res * range + _min_range; // Map to [min_range, max_range]
         *reinterpret_cast<float *>(tensor.ptr_to_element(id)) = res;
     });
 }
References arm_compute::execute_window_loop(), ITensor::info(), arm_compute::test::validation::reference::range(), ITensorInfo::tensor_shape(), and Window::use_tensor_dimensions().
The documentation for this class was generated from the following files:
utils/GraphUtils.h
utils/GraphUtils.cpp