Compute Library: CLGEMMReshapeRHSMatrixKernel Class Reference
CLGEMMReshapeRHSMatrixKernel Class Reference
OpenCL kernel to reshape the RHS matrix when performing the matrix multiplication In particular, this kernel splits the input matrix in blocks of size K0xN0 and stores each one in the output matrix unrolling the values.
#include <CLGEMMReshapeRHSMatrixKernel.h>
Public Member Functions
CLGEMMReshapeRHSMatrixKernel ()
Default constructor.
CLGEMMReshapeRHSMatrixKernel (const CLGEMMReshapeRHSMatrixKernel &)=delete
Prevent instances of this class from being copied (As this class contains pointers)
CLGEMMReshapeRHSMatrixKernel & operator= (const CLGEMMReshapeRHSMatrixKernel &)=delete
Prevent instances of this class from being copied (As this class contains pointers)
CLGEMMReshapeRHSMatrixKernel (CLGEMMReshapeRHSMatrixKernel &&)=default
Allow instances of this class to be moved.
CLGEMMReshapeRHSMatrixKernel & operator= (CLGEMMReshapeRHSMatrixKernel &&)=default
Allow instances of this class to be moved.
void configure (const ICLTensor *input, ICLTensor *output, const GEMMRHSMatrixInfo &rhs_info)
Initialise the kernel's input and output.
void run (const Window &window, cl::CommandQueue &queue) override
Enqueue the OpenCL kernel to process the given window on the passed OpenCL command queue.
Public Member Functions inherited from ICLKernel
ICLKernel ()
Constructor.
cl::Kernel & kernel ()
Returns a reference to the OpenCL kernel of this object.
template<typename T >
void add_1D_array_argument (unsigned int &idx, const ICLArray< T > *array, const Strides &strides, unsigned int num_dimensions, const Window &window)
Add the passed 1D array's parameters to the object's kernel's arguments starting from the index idx.
void add_1D_tensor_argument (unsigned int &idx, const ICLTensor *tensor, const Window &window)
Add the passed 1D tensor's parameters to the object's kernel's arguments starting from the index idx.
void add_2D_tensor_argument (unsigned int &idx, const ICLTensor *tensor, const Window &window)
Add the passed 2D tensor's parameters to the object's kernel's arguments starting from the index idx.
void add_3D_tensor_argument (unsigned int &idx, const ICLTensor *tensor, const Window &window)
Add the passed 3D tensor's parameters to the object's kernel's arguments starting from the index idx.
void add_4D_tensor_argument (unsigned int &idx, const ICLTensor *tensor, const Window &window)
Add the passed 4D tensor's parameters to the object's kernel's arguments starting from the index idx.
template<typename T >
void add_argument (unsigned int &idx, T value)
Add the passed parameters to the object's kernel's arguments starting from the index idx.
void set_lws_hint (const cl::NDRange &lws_hint)
Set the Local-Workgroup-Size hint.
cl::NDRange lws_hint () const
Return the Local-Workgroup-Size hint.
const std::string & config_id () const
Get the configuration ID.
void set_target (GPUTarget target)
Set the targeted GPU architecture.
void set_target (cl::Device &device)
Set the targeted GPU architecture according to the CL device.
GPUTarget get_target () const
Get the targeted GPU architecture.
size_t get_max_workgroup_size ()
Get the maximum workgroup size for the device the CLKernelLibrary uses.
template<typename T , unsigned int dimension_size>
void add_array_argument (unsigned &idx, const ICLArray< T > *array, const Strides &strides, unsigned int num_dimensions, const Window &window)
Add the passed array's parameters to the object's kernel's arguments starting from the index idx.
template<unsigned int dimension_size>
void add_tensor_argument (unsigned &idx, const ICLTensor *tensor, const Window &window)
Public Member Functions inherited from IKernel
IKernel ()
Constructor.
virtual ~IKernel ()=default
Destructor.
virtual bool is_parallelisable () const
Indicates whether or not the kernel is parallelisable.
virtual BorderSize border_size () const
The size of the border for that kernel.
const Window & window () const
The maximum window the kernel can be executed on.
Static Public Member Functions
static Status validate (const ITensorInfo *input, const ITensorInfo *output, const GEMMRHSMatrixInfo &rhs_info)
Static function to check if given info will lead to a valid configuration of CLGEMMReshapeRHSMatrixKernel.
Static Public Member Functions inherited from ICLKernel
static constexpr unsigned int num_arguments_per_1D_array ()
Returns the number of arguments enqueued per 1D array object.
static constexpr unsigned int num_arguments_per_1D_tensor ()
Returns the number of arguments enqueued per 1D tensor object.
static constexpr unsigned int num_arguments_per_2D_tensor ()
Returns the number of arguments enqueued per 2D tensor object.
static constexpr unsigned int num_arguments_per_3D_tensor ()
Returns the number of arguments enqueued per 3D tensor object.
static constexpr unsigned int num_arguments_per_4D_tensor ()
Returns the number of arguments enqueued per 4D tensor object.
static cl::NDRange gws_from_window (const Window &window)
Get the global work size given an execution window.
Detailed Description
OpenCL kernel to reshape the RHS matrix when performing the matrix multiplication In particular, this kernel splits the input matrix in blocks of size K0xN0 and stores each one in the output matrix unrolling the values.
Definition at line 36 of file CLGEMMReshapeRHSMatrixKernel.h.
Constructor & Destructor Documentation
CLGEMMReshapeRHSMatrixKernel() [1/3]
CLGEMMReshapeRHSMatrixKernel ()
Default constructor.
Definition at line 98 of file CLGEMMReshapeRHSMatrixKernel.cpp.
     : _input(nullptr), _output(nullptr)
 {
 }
CLGEMMReshapeRHSMatrixKernel() [2/3]
CLGEMMReshapeRHSMatrixKernel (const CLGEMMReshapeRHSMatrixKernel &) delete
Prevent instances of this class from being copied (As this class contains pointers)
CLGEMMReshapeRHSMatrixKernel() [3/3]
CLGEMMReshapeRHSMatrixKernel (CLGEMMReshapeRHSMatrixKernel &&) default
Allow instances of this class to be moved.
Member Function Documentation
configure()
void configure (const ICLTensor * input, ICLTensor * output, const GEMMRHSMatrixInfo & rhs_info)
Initialise the kernel's input and output.
Parameters
[in] input Input tensor. Data types supported: U8/S8/QASYMM8/U16/S16/F16/U32/S32/F32
[out] output Output tensor. Data type supported: same as input
[in] rhs_info RHS matrix information to be used for reshaping. This object contains all the necessary information to reshape the input tensor. Only the following values are supported: rhs_info.n0: 2,3,4,8,16 rhs_info.k0: 1,2,3,4,8,16 (k0 = 1 only if rhs_info.transpose = false) rhs_info.h0: greater than 0 rhs_info.transpose: true, false rhs_info.interleave: true, false
Definition at line 103 of file CLGEMMReshapeRHSMatrixKernel.cpp.
 {
     ARM_COMPUTE_ERROR_ON_NULLPTR(input, output);
     // Perform validate step
     ARM_COMPUTE_ERROR_THROW_ON(validate_arguments(input->info(), output->info(), rhs_info));
     _input  = input;
     _output = output;
     // Create build options
     CLBuildOptions build_opts;
     build_opts.add_option("-DN0=" + support::cpp11::to_string(rhs_info.n0));
     build_opts.add_option("-DK0=" + support::cpp11::to_string(rhs_info.k0));
     build_opts.add_option("-DH0=" + support::cpp11::to_string(rhs_info.h0));
     build_opts.add_option_if(rhs_info.transpose, "-DTRANSPOSE");
     build_opts.add_option_if(rhs_info.interleave, "-DINTERLEAVE");
     build_opts.add_option("-DSRC_HEIGHT=" + support::cpp11::to_string(input->info()->dimension(1)));
     switch(input->info()->element_size())
     {
         case 1:
             build_opts.add_option("-DDATA_TYPE=uchar");
             break;
         case 2:
             build_opts.add_option("-DDATA_TYPE=ushort");
             break;
         case 4:
             build_opts.add_option("-DDATA_TYPE=uint");
             break;
         default:
             ARM_COMPUTE_ERROR("Data type not supported");
     }
     std::string kernel_name("gemm_reshape_rhs_matrix_");
     kernel_name += rhs_info.transpose ? "t" : "nt";
     // Create kernel
     _kernel = static_cast<cl::Kernel>(CLKernelLibrary::get().create_kernel(kernel_name, build_opts.options()));
     // Configure kernel window
     auto win_config = validate_and_configure_window(input->info(), output->info(), rhs_info);
     ARM_COMPUTE_ERROR_THROW_ON(win_config.first);
     ICLKernel::configure_internal(win_config.second);
 }
References CLBuildOptions::add_option(), CLBuildOptions::add_option_if(), ARM_COMPUTE_ERROR, ARM_COMPUTE_ERROR_ON_NULLPTR, ARM_COMPUTE_ERROR_THROW_ON, arm_compute::create_kernel(), ITensorInfo::dimension(), ITensorInfo::element_size(), CLKernelLibrary::get(), GEMMRHSMatrixInfo::h0, ITensor::info(), GEMMRHSMatrixInfo::interleave, GEMMRHSMatrixInfo::k0, GEMMRHSMatrixInfo::n0, CLBuildOptions::options(), arm_compute::support::cpp11::to_string(), and GEMMRHSMatrixInfo::transpose.
Referenced by CLGEMM::configure(), CLGEMMLowpMatrixMultiplyCore::configure(), and arm_compute::test::validation::DATA_TEST_CASE().
operator=() [1/2]
CLGEMMReshapeRHSMatrixKernel& operator= (const CLGEMMReshapeRHSMatrixKernel &) delete
Prevent instances of this class from being copied (As this class contains pointers)
operator=() [2/2]
CLGEMMReshapeRHSMatrixKernel& operator= (CLGEMMReshapeRHSMatrixKernel &&) default
Allow instances of this class to be moved.
run()
void run (const Window & window, cl::CommandQueue & queue) override virtual
Enqueue the OpenCL kernel to process the given window on the passed OpenCL command queue.
Note
The queue is not flushed by this method, and therefore the kernel will not have been executed by the time this method returns.
Parameters
[in] window Region on which to execute the kernel. (Must be a valid region of the window returned by window()).
[in,out] queue Command queue on which to enqueue the kernel.
Implements ICLKernel.
Definition at line 157 of file CLGEMMReshapeRHSMatrixKernel.cpp.
 {
     ARM_COMPUTE_ERROR_ON_UNCONFIGURED_KERNEL(this);
     ARM_COMPUTE_ERROR_ON_INVALID_SUBWINDOW(ICLKernel::window(), window);
     Window slice = window.first_slice_window_3D();
     do
     {
         unsigned int idx = 0;
         add_3D_tensor_argument(idx, _input, slice);
         add_3D_tensor_argument(idx, _output, slice);
         enqueue(queue, *this, slice);
     }
     while(window.slide_window_slice_3D(slice));
 }
References ICLKernel::add_3D_tensor_argument(), ARM_COMPUTE_ERROR_ON_INVALID_SUBWINDOW, ARM_COMPUTE_ERROR_ON_UNCONFIGURED_KERNEL, arm_compute::enqueue(), Window::first_slice_window_3D(), arm_compute::test::validation::reference::slice(), Window::slide_window_slice_3D(), and IKernel::window().
validate()
Status validate (const ITensorInfo * input, const ITensorInfo * output, const GEMMRHSMatrixInfo & rhs_info) static
Static function to check if given info will lead to a valid configuration of CLGEMMReshapeRHSMatrixKernel.
Parameters
[in] input Input tensor info. Data types supported: U8/S8/QASYMM8/U16/S16/F16/U32/S32/F32
[in] output Output tensor info which stores the interleaved matrix. Data type supported: same as input.
[in] rhs_info RHS matrix information to be used for reshaping. This object contains all the necessary information to reshape the input tensor. Only the following values are supported: rhs_info.n0: 2,3,4,8,16 rhs_info.k0: 1,2,3,4,8,16 (k0 = 1 only if rhs_info.transpose = false) rhs_info.h0: greater than 0 rhs_info.transpose: true, false rhs_info.interleave: true, false
Returns
a status
Definition at line 149 of file CLGEMMReshapeRHSMatrixKernel.cpp.
 {
     ARM_COMPUTE_RETURN_ON_ERROR(validate_arguments(input, output, rhs_info));
     ARM_COMPUTE_RETURN_ON_ERROR(validate_and_configure_window(input->clone().get(), output->clone().get(), rhs_info).first);
     return Status{};
 }
References ARM_COMPUTE_RETURN_ON_ERROR, and ICloneable< T >::clone().
Referenced by CLGEMMLowpMatrixMultiplyCore::validate(), and CLGEMM::validate().
The documentation for this class was generated from the following files:
arm_compute/core/CL/kernels/CLGEMMReshapeRHSMatrixKernel.h
src/core/CL/kernels/CLGEMMReshapeRHSMatrixKernel.cpp