Compute Library: CLEdgeNonMaxSuppressionKernel Class Reference
CLEdgeNonMaxSuppressionKernel Class Reference
OpenCL kernel to perform Non-Maxima suppression for Canny Edge.
#include <CLCannyEdgeKernel.h>
Public Member Functions
CLEdgeNonMaxSuppressionKernel ()
Constructor.
CLEdgeNonMaxSuppressionKernel (const CLEdgeNonMaxSuppressionKernel &)=delete
Prevent instances of this class from being copied (As this class contains pointers)
CLEdgeNonMaxSuppressionKernel & operator= (const CLEdgeNonMaxSuppressionKernel &)=delete
Prevent instances of this class from being copied (As this class contains pointers)
void configure (const ICLTensor *magnitude, const ICLTensor *phase, ICLTensor *output, int32_t lower_thr, bool border_undefined)
Initialise the kernel's sources, destination and border mode.
void run (const Window &window, cl::CommandQueue &queue) override
Enqueue the OpenCL kernel to process the given window on the passed OpenCL command queue.
BorderSize border_size () const override
The size of the border for that kernel.
Public Member Functions inherited from ICLKernel
ICLKernel ()
Constructor.
cl::Kernel & kernel ()
Returns a reference to the OpenCL kernel of this object.
template<typename T >
void add_1D_array_argument (unsigned int &idx, const ICLArray< T > *array, const Strides &strides, unsigned int num_dimensions, const Window &window)
Add the passed 1D array's parameters to the object's kernel's arguments starting from the index idx.
void add_1D_tensor_argument (unsigned int &idx, const ICLTensor *tensor, const Window &window)
Add the passed 1D tensor's parameters to the object's kernel's arguments starting from the index idx.
void add_1D_tensor_argument_if (bool cond, unsigned int &idx, const ICLTensor *tensor, const Window &window)
Add the passed 1D tensor's parameters to the object's kernel's arguments starting from the index idx if the condition is true.
void add_2D_tensor_argument (unsigned int &idx, const ICLTensor *tensor, const Window &window)
Add the passed 2D tensor's parameters to the object's kernel's arguments starting from the index idx.
void add_2D_tensor_argument_if (bool cond, unsigned int &idx, const ICLTensor *tensor, const Window &window)
Add the passed 2D tensor's parameters to the object's kernel's arguments starting from the index idx if the condition is true.
void add_3D_tensor_argument (unsigned int &idx, const ICLTensor *tensor, const Window &window)
Add the passed 3D tensor's parameters to the object's kernel's arguments starting from the index idx.
void add_4D_tensor_argument (unsigned int &idx, const ICLTensor *tensor, const Window &window)
Add the passed 4D tensor's parameters to the object's kernel's arguments starting from the index idx.
template<typename T >
void add_argument (unsigned int &idx, T value)
Add the passed parameters to the object's kernel's arguments starting from the index idx.
void set_lws_hint (const cl::NDRange &lws_hint)
Set the Local-Workgroup-Size hint.
cl::NDRange lws_hint () const
Return the Local-Workgroup-Size hint.
const std::string & config_id () const
Get the configuration ID.
void set_target (GPUTarget target)
Set the targeted GPU architecture.
void set_target (cl::Device &device)
Set the targeted GPU architecture according to the CL device.
GPUTarget get_target () const
Get the targeted GPU architecture.
size_t get_max_workgroup_size ()
Get the maximum workgroup size for the device the CLKernelLibrary uses.
template<typename T , unsigned int dimension_size>
void add_array_argument (unsigned &idx, const ICLArray< T > *array, const Strides &strides, unsigned int num_dimensions, const Window &window)
Add the passed array's parameters to the object's kernel's arguments starting from the index idx.
template<unsigned int dimension_size>
void add_tensor_argument (unsigned &idx, const ICLTensor *tensor, const Window &window)
Public Member Functions inherited from IKernel
IKernel ()
Constructor.
virtual ~IKernel ()=default
Destructor.
virtual bool is_parallelisable () const
Indicates whether or not the kernel is parallelisable.
const Window & window () const
The maximum window the kernel can be executed on.
Additional Inherited Members
Static Public Member Functions inherited from ICLKernel
static constexpr unsigned int num_arguments_per_1D_array ()
Returns the number of arguments enqueued per 1D array object.
static constexpr unsigned int num_arguments_per_1D_tensor ()
Returns the number of arguments enqueued per 1D tensor object.
static constexpr unsigned int num_arguments_per_2D_tensor ()
Returns the number of arguments enqueued per 2D tensor object.
static constexpr unsigned int num_arguments_per_3D_tensor ()
Returns the number of arguments enqueued per 3D tensor object.
static constexpr unsigned int num_arguments_per_4D_tensor ()
Returns the number of arguments enqueued per 4D tensor object.
static cl::NDRange gws_from_window (const Window &window)
Get the global work size given an execution window.
Detailed Description
OpenCL kernel to perform Non-Maxima suppression for Canny Edge.
Note
This kernel is meant to be used alongside CannyEdge and performs a non-maxima suppression using magnitude and phase of input to characterize points as possible edges. The output buffer needs to be cleared before this kernel is executed.
Hysteresis is computed in CLEdgeTraceKernel
Definition at line 75 of file CLCannyEdgeKernel.h.
Constructor & Destructor Documentation
CLEdgeNonMaxSuppressionKernel() [1/2]
CLEdgeNonMaxSuppressionKernel ()
Constructor.
Definition at line 110 of file CLCannyEdgeKernel.cpp.
     : _magnitude(nullptr), _phase(nullptr), _output(nullptr)
 {
 }
CLEdgeNonMaxSuppressionKernel() [2/2]
CLEdgeNonMaxSuppressionKernel (const CLEdgeNonMaxSuppressionKernel &) delete
Prevent instances of this class from being copied (As this class contains pointers)
Member Function Documentation
border_size()
BorderSize border_size () const override virtual
The size of the border for that kernel.
Returns
The width in number of elements of the border.
Reimplemented from IKernel.
Definition at line 115 of file CLCannyEdgeKernel.cpp.
 {
     return BorderSize(1);
 }
Referenced by CLCannyEdge::configure(), and CLEdgeNonMaxSuppressionKernel::configure().
configure()
void configure (const ICLTensor * magnitude, const ICLTensor * phase, ICLTensor * output, int32_t lower_thr, bool border_undefined)
Initialise the kernel's sources, destination and border mode.
Parameters
[in] magnitude Source tensor - Magnitude. Data types supported: U16/U32.
[in] phase Source tensor - Quantized phase. Data types supported: U8.
[out] output Destination tensor. Data types supported: U16/U32.
[in] lower_thr Lower threshold.
[in] border_undefined True if the border mode is undefined. False if it's replicate or constant.
Definition at line 120 of file CLCannyEdgeKernel.cpp.
 {
     ARM_COMPUTE_ERROR_ON_DATA_TYPE_CHANNEL_NOT_IN(magnitude, 1, DataType::U16, DataType::U32);
     ARM_COMPUTE_ERROR_ON_DATA_TYPE_CHANNEL_NOT_IN(phase, 1, DataType::U8);
     ARM_COMPUTE_ERROR_ON_DATA_TYPE_CHANNEL_NOT_IN(output, 1, DataType::U16, DataType::U32);
     _magnitude = magnitude;
     _phase     = phase;
     _output    = output;
     // Create build opts
     std::set<std::string> built_opts;
     built_opts.emplace("-DDATA_TYPE_IN=" + get_cl_type_from_data_type(magnitude->info()->data_type()));
     built_opts.emplace("-DDATA_TYPE_OUT=" + get_cl_type_from_data_type(output->info()->data_type()));
     // Create kernel
     const std::string kernel_name = std::string("suppress_non_maximum");
     _kernel                       = static_cast<cl::Kernel>(CLKernelLibrary::get().create_kernel(kernel_name, built_opts));
     // Set minimum threshold argument
     unsigned int idx = 3 * num_arguments_per_2D_tensor(); //Skip the input and output parameters
     _kernel.setArg(idx++, lower_thr);
     // Configure kernel window
     constexpr unsigned int num_elems_processed_per_iteration    = 1;
     constexpr unsigned int num_elems_read_written_per_iteration = 3;
     Window win = calculate_max_window(*_magnitude->info(), Steps(num_elems_processed_per_iteration), border_undefined, border_size());
     AccessWindowRectangle mag_access(_magnitude->info(), -border_size().left, -border_size().top,
                                      num_elems_read_written_per_iteration, num_elems_read_written_per_iteration);
     AccessWindowHorizontal phase_access(_phase->info(), 0, num_elems_processed_per_iteration);
     AccessWindowHorizontal output_access(_output->info(), 0, num_elems_processed_per_iteration);
     update_window_and_padding(win, mag_access, phase_access, output_access);
     output_access.set_valid_region(win, _magnitude->info()->valid_region(), border_undefined, border_size());
     ICLKernel::configure_internal(win);
     // Set config_id for enabling LWS tuning
     _config_id = kernel_name;
     _config_id += "_";
     _config_id += lower_string(string_from_data_type(output->info()->data_type()));
     _config_id += "_";
     _config_id += support::cpp11::to_string(output->info()->dimension(0));
     _config_id += "_";
     _config_id += support::cpp11::to_string(output->info()->dimension(1));
     _config_id += "_";
     _config_id += support::cpp11::to_string(border_undefined);
 }
References ARM_COMPUTE_ERROR_ON_DATA_TYPE_CHANNEL_NOT_IN, CLEdgeNonMaxSuppressionKernel::border_size(), arm_compute::calculate_max_window(), arm_compute::create_kernel(), ITensorInfo::data_type(), ITensorInfo::dimension(), CLKernelLibrary::get(), arm_compute::get_cl_type_from_data_type(), ITensor::info(), BorderSize::left, arm_compute::lower_string(), arm_compute::test::validation::reference::magnitude(), ICLKernel::num_arguments_per_2D_tensor(), arm_compute::test::validation::reference::phase(), arm_compute::string_from_data_type(), arm_compute::support::cpp11::to_string(), BorderSize::top, arm_compute::U16, arm_compute::U32, arm_compute::U8, arm_compute::update_window_and_padding(), and ITensorInfo::valid_region().
Referenced by CLCannyEdge::configure().
operator=()
CLEdgeNonMaxSuppressionKernel& operator= (const CLEdgeNonMaxSuppressionKernel &) delete
Prevent instances of this class from being copied (As this class contains pointers)
run()
void run (const Window & window, cl::CommandQueue & queue) override virtual
Enqueue the OpenCL kernel to process the given window on the passed OpenCL command queue.
Note
The queue is not flushed by this method, and therefore the kernel will not have been executed by the time this method returns.
Parameters
[in] window Region on which to execute the kernel. (Must be a valid region of the window returned by window()).
[in,out] queue Command queue on which to enqueue the kernel.
Implements ICLKernel.
Definition at line 172 of file CLCannyEdgeKernel.cpp.
 {
     ARM_COMPUTE_ERROR_ON_UNCONFIGURED_KERNEL(this);
     ARM_COMPUTE_ERROR_ON_INVALID_SUBWINDOW(IKernel::window(), window);
     Window slice = window.first_slice_window_2D();
     do
     {
         unsigned int idx = 0;
         add_2D_tensor_argument(idx, _magnitude, slice);
         add_2D_tensor_argument(idx, _phase, slice);
         add_2D_tensor_argument(idx, _output, slice);
         enqueue(queue, *this, slice, lws_hint());
     }
     while(window.slide_window_slice_2D(slice));
 }
References ICLKernel::add_2D_tensor_argument(), ARM_COMPUTE_ERROR_ON_INVALID_SUBWINDOW, ARM_COMPUTE_ERROR_ON_UNCONFIGURED_KERNEL, arm_compute::enqueue(), Window::first_slice_window_2D(), ICLKernel::lws_hint(), arm_compute::test::validation::reference::slice(), Window::slide_window_slice_2D(), and IKernel::window().
The documentation for this class was generated from the following files:
arm_compute/core/CL/kernels/CLCannyEdgeKernel.h
src/core/CL/kernels/CLCannyEdgeKernel.cpp