Compute Library: GCProgram Class Reference
GCProgram Class Reference
GCProgram class.
#include <GCKernelLibrary.h>
Public Member Functions
GCProgram ()
Default constructor.
GCProgram (std::string name, std::string source)
Construct program from source file.
GCProgram (const GCProgram &)=default
Default Copy Constructor.
GCProgram (GCProgram &&)=default
Default Move Constructor.
GCProgram & operator= (const GCProgram &)=default
Default copy assignment operator.
GCProgram & operator= (GCProgram &&)=default
Default move assignment operator.
std::string name () const
Returns program name.
GLuint link_program (GLuint shader)
Link program.
GLuint compile_shader (const std::string &build_options)
Compile shader.
Detailed Description
GCProgram class.
Definition at line 39 of file GCKernelLibrary.h.
Constructor & Destructor Documentation
GCProgram() [1/4]
GCProgram ()
Default constructor.
Definition at line 38 of file GCKernelLibrary.cpp.
     : _name(), _source()
 {
 }
GCProgram() [2/4]
GCProgram (std::string name, std::string source)
Construct program from source file.
Parameters
[in] name Program name.
[in] source Program source.
Definition at line 43 of file GCKernelLibrary.cpp.
     : _name(std::move(name)), _source(std::move(source))
 {
 }
GCProgram() [3/4]
GCProgram (const GCProgram &) default
Default Copy Constructor.
GCProgram() [4/4]
GCProgram (GCProgram &&) default
Default Move Constructor.
Member Function Documentation
compile_shader()
GLuint compile_shader (const std::string & build_options)
Compile shader.
Parameters
[in] build_options Shader build options.
Returns
GLES shader object.
Definition at line 79 of file GCKernelLibrary.cpp.
 {
     GLuint shader = ARM_COMPUTE_GL_CHECK(glCreateShader(GL_COMPUTE_SHADER));
     const char *src[]
     {
         "#version 310 es\n",
         build_options.c_str(),
         _source.c_str()
     };
     ARM_COMPUTE_GL_CHECK(glShaderSource(shader, sizeof(src) / sizeof(src[0]), src, nullptr));
     ARM_COMPUTE_GL_CHECK(glCompileShader(shader));
     // Check if there were any issues when compiling the shader
     GLint   rvalue;
     GLsizei length;
     ARM_COMPUTE_GL_CHECK(glGetShaderiv(shader, GL_COMPILE_STATUS, &rvalue));
     if(rvalue == 0)
     {
         ARM_COMPUTE_GL_CHECK(glGetShaderiv(shader, GL_INFO_LOG_LENGTH, &length));
         std::vector<GLchar> log(length);
         ARM_COMPUTE_GL_CHECK(glGetShaderInfoLog(shader, length, nullptr, log.data()));
 #ifdef ARM_COMPUTE_DEBUG_ENABLED
         std::istringstream ss(_source);
         std::stringstream  output_stream;
         std::string        line;
         size_t             line_num = 1;
         ARM_COMPUTE_LOG_INFO_MSG_WITH_FORMAT_CORE("GLES Shader build options:\n%s\n", build_options.c_str());
         while(std::getline(ss, line, '\n'))
         {
             output_stream << std::setw(6) << line_num << ": " << line << std::endl;
             line_num++;
         }
         ARM_COMPUTE_LOG_INFO_STREAM_CORE("GLES Shader source code:\n"
                                          << output_stream.rdbuf());
 #endif /* ARM_COMPUTE_DEBUG_ENABLED */
         ARM_COMPUTE_ERROR("Error: Compiler log:\n%s\n", log.data());
         return 0;
     }
     return shader;
 }
References ARM_COMPUTE_ERROR, ARM_COMPUTE_GL_CHECK, ARM_COMPUTE_LOG_INFO_MSG_WITH_FORMAT_CORE, ARM_COMPUTE_LOG_INFO_STREAM_CORE, glCompileShader(), glCreateShader(), glGetShaderInfoLog(), glGetShaderiv(), glShaderSource(), and arm_compute::test::validation::src.
Referenced by GCKernelLibrary::create_kernel().
link_program()
GLuint link_program (GLuint shader)
Link program.
Parameters
[in] shader Shader used to link program.
Returns
linked program id .
Definition at line 48 of file GCKernelLibrary.cpp.
 {
     GLuint program = ARM_COMPUTE_GL_CHECK(glCreateProgram());
     GLint   rvalue;
     GLsizei length;
     ARM_COMPUTE_GL_CHECK(glAttachShader(program, shader));
     ARM_COMPUTE_GL_CHECK(glLinkProgram(program));
     ARM_COMPUTE_GL_CHECK(glDetachShader(program, shader));
     ARM_COMPUTE_GL_CHECK(glDeleteShader(shader));
     // Check if there were some issues when linking the shader.
     ARM_COMPUTE_GL_CHECK(glGetProgramiv(program, GL_LINK_STATUS, &rvalue));
     if(rvalue == 0)
     {
         ARM_COMPUTE_GL_CHECK(glGetProgramiv(program, GL_INFO_LOG_LENGTH, &length));
         std::vector<GLchar> log(length);
         ARM_COMPUTE_GL_CHECK(glGetProgramInfoLog(program, length, nullptr, log.data()));
         ARM_COMPUTE_ERROR("Error: Linker log:\n%s\n", log.data());
         return 0;
     }
     ARM_COMPUTE_GL_CHECK(glUseProgram(program));
     return program;
 }
References ARM_COMPUTE_ERROR, ARM_COMPUTE_GL_CHECK, glAttachShader(), glCreateProgram(), glDeleteShader(), glDetachShader(), glGetProgramInfoLog(), glGetProgramiv(), glLinkProgram(), and glUseProgram().
Referenced by GCKernelLibrary::create_kernel().
name()
std::string name () const inline
Returns program name.
Returns
Program's name.
Definition at line 62 of file GCKernelLibrary.h.
     {
         return _name;
     }
operator=() [1/2]
GCProgram& operator= (const GCProgram &) default
Default copy assignment operator.
operator=() [2/2]
GCProgram& operator= (GCProgram &&) default
Default move assignment operator.
The documentation for this class was generated from the following files:
arm_compute/core/GLES_COMPUTE/GCKernelLibrary.h
src/core/GLES_COMPUTE/GCKernelLibrary.cpp