Compute Library: GCFillBorderKernel Class Reference
GCFillBorderKernel Class Reference
Interface for filling the border of a kernel.
#include <GCFillBorderKernel.h>
Public Member Functions
GCFillBorderKernel ()
Default constructor.
GCFillBorderKernel (const GCFillBorderKernel &)=delete
Prevent instances of this class from being copied (As this class contains pointers)
GCFillBorderKernel & operator= (const GCFillBorderKernel &)=delete
Prevent instances of this class from being copied (As this class contains pointers)
GCFillBorderKernel (GCFillBorderKernel &&)=default
Allow instances of this class to be moved.
GCFillBorderKernel & operator= (GCFillBorderKernel &&)=default
Allow instances of this class to be moved.
~GCFillBorderKernel ()=default
Default destructor.
void configure (const IGCTensor *tensor, BorderSize border_size, BorderMode border_mode, const PixelValue &constant_border_value=PixelValue())
Initialise the kernel's input, output and border mode.
template<class T >
void set_constant_border (unsigned int idx, const PixelValue &constant_border_value)
Function to set the constant value on fill border kernel depending on type.
void run (const Window &window) override
Enqueue the OpenGL ES shader to process the given window.
bool is_parallelisable () const override
Indicates whether or not the kernel is parallelisable.
Public Member Functions inherited from IGCKernel
IGCKernel ()
Constructor.
GCKernel & kernel ()
Returns a reference to the GLES kernel of this object.
void add_1D_tensor_argument (unsigned int &idx, const IGCTensor *tensor, const unsigned int binding_point, const Window &window)
Add the passed 1D tensor's parameters to the object's kernel's arguments starting from the index idx.
void add_2D_tensor_argument (unsigned int &idx, const IGCTensor *tensor, const unsigned int binding_point, const Window &window)
Add the passed 2D tensor's parameters to the object's kernel's arguments starting from the index idx.
void add_3D_tensor_argument (unsigned int &idx, const IGCTensor *tensor, const unsigned int binding_point, const Window &window)
Add the passed 3D tensor's parameters to the object's kernel's arguments starting from the index idx.
unsigned int num_arguments_per_1D_tensor () const
Returns the number of arguments enqueued per 1D tensor object.
unsigned int num_arguments_per_2D_tensor () const
Returns the number of arguments enqueued per 2D tensor object.
unsigned int num_arguments_per_3D_tensor () const
Returns the number of arguments enqueued per 3D tensor object.
void set_lws_hint (gles::NDRange &lws_hint)
Set the Local-Workgroup-Size hint.
void set_target (GPUTarget target)
Set the targeted GPU architecture.
GPUTarget get_target () const
Get the targeted GPU architecture.
Public Member Functions inherited from IKernel
IKernel ()
Constructor.
virtual ~IKernel ()=default
Destructor.
virtual BorderSize border_size () const
The size of the border for that kernel.
const Window & window () const
The maximum window the kernel can be executed on.
Detailed Description
Interface for filling the border of a kernel.
Definition at line 36 of file GCFillBorderKernel.h.
Constructor & Destructor Documentation
GCFillBorderKernel() [1/3]
GCFillBorderKernel ()
Default constructor.
Definition at line 42 of file GCFillBorderKernel.cpp.
     : IGCKernel(), _tensor(nullptr)
 {
 }
GCFillBorderKernel() [2/3]
GCFillBorderKernel (const GCFillBorderKernel &) delete
Prevent instances of this class from being copied (As this class contains pointers)
GCFillBorderKernel() [3/3]
GCFillBorderKernel (GCFillBorderKernel &&) default
Allow instances of this class to be moved.
~GCFillBorderKernel()
~GCFillBorderKernel () default
Default destructor.
Member Function Documentation
configure()
void configure (const IGCTensor * tensor, BorderSize border_size, BorderMode border_mode, const PixelValue & constant_border_value = PixelValue())
Initialise the kernel's input, output and border mode.
Parameters
[in,out] tensor Tensor to process Data types supported: F16/F32.
[in] border_size Size of the border to fill in elements.
[in] border_mode Border mode to use for the convolution.
[in] constant_border_value (Optional) Constant value to use for borders if border_mode is set to CONSTANT.
Definition at line 60 of file GCFillBorderKernel.cpp.
 {
     ARM_COMPUTE_ERROR_ON(tensor == nullptr);
     ARM_COMPUTE_ERROR_ON_DATA_TYPE_CHANNEL_NOT_IN(tensor, 1, DataType::F32, DataType::F16);
     ARM_COMPUTE_ERROR_ON(tensor->info()->num_channels() != 1);
     border_size.limit(tensor->info()->padding());
     // If there is no border: early exit
     if(border_size.empty() || border_mode == BorderMode::UNDEFINED)
     {
         return;
     }
     // Select appropriate kernel
     std::string kernel_name = "fill_image_borders_" + lower_string(string_from_border_mode(border_mode));
     // Define build options
     std::set<std::string> build_opts;
     build_opts.emplace("#define LOCAL_SIZE_X " + support::cpp11::to_string(1));
     build_opts.emplace("#define LOCAL_SIZE_Y " + support::cpp11::to_string(1));
     build_opts.emplace("#define LOCAL_SIZE_Z " + support::cpp11::to_string(1));
     build_opts.emplace("#define BORDER_SIZE_TOP " + support::cpp11::to_string(border_size.top));
     build_opts.emplace("#define BORDER_SIZE_BOTTOM " + support::cpp11::to_string(border_size.bottom));
     build_opts.emplace("#define BORDER_SIZE_LEFT " + support::cpp11::to_string(border_size.left));
     build_opts.emplace("#define BORDER_SIZE_RIGHT " + support::cpp11::to_string(border_size.right));
     if(border_mode == BorderMode::REPLICATE)
     {
         build_opts.emplace("#define FILL_IMAGE_BORDERS_REPLICATE\n");
     }
     else
     {
         build_opts.emplace("#define FILL_IMAGE_BORDERS_CONSTANT\n");
     }
     switch(tensor->info()->data_type())
     {
         case DataType::F16:
             build_opts.emplace("#define DATA_TYPE_FP16");
             break;
         case DataType::F32:
             build_opts.emplace("#define DATA_TYPE_FP32");
             break;
         default:
             ARM_COMPUTE_ERROR("Current data type is not supported");
             break;
     }
     // Create kernel
     _kernel = static_cast<GCKernel>(GCKernelLibrary::get().create_kernel(kernel_name, build_opts));
     _tensor = tensor;
     // Create static kernel arguments
     const unsigned int valid_width       = tensor->info()->valid_region().shape[0];
     const unsigned int valid_height      = tensor->info()->valid_region().shape[1];
     const unsigned int total_valid_width = border_size.left + valid_width + border_size.right;
     // Set static kernel arguments
     unsigned int idx = num_arguments_per_3D_tensor(); //Skip the tensor parameters
     _kernel.set_argument(idx++, valid_width);
     _kernel.set_argument(idx++, valid_height);
     _kernel.set_argument(idx++, tensor->info()->valid_region().anchor[0]);
     _kernel.set_argument(idx++, tensor->info()->valid_region().anchor[1]);
     if(BorderMode::CONSTANT == border_mode)
     {
         set_constant_border<float>(idx++, constant_border_value);
     }
     // Configure kernel window
     Window win;
     win.set(Window::DimX, Window::Dimension(0, total_valid_width + valid_height));
     win.set(Window::DimY, Window::Dimension(0, 1, 1));
     win.use_tensor_dimensions(tensor->info()->tensor_shape(), Window::DimZ);
     IGCKernel::configure(win);
 }
References ValidRegion::anchor, ARM_COMPUTE_ERROR, ARM_COMPUTE_ERROR_ON, ARM_COMPUTE_ERROR_ON_DATA_TYPE_CHANNEL_NOT_IN, arm_compute::test::validation::border_mode, IKernel::border_size(), BorderSize::bottom, arm_compute::CONSTANT, arm_compute::create_kernel(), ITensorInfo::data_type(), Window::DimX, Window::DimY, Window::DimZ, BorderSize::empty(), arm_compute::F16, arm_compute::F32, GCKernelLibrary::get(), ITensor::info(), BorderSize::left, BorderSize::limit(), arm_compute::lower_string(), IGCKernel::num_arguments_per_3D_tensor(), ITensorInfo::num_channels(), ITensorInfo::padding(), arm_compute::REPLICATE, BorderSize::right, Window::set(), ValidRegion::shape, arm_compute::string_from_border_mode(), ITensorInfo::tensor_shape(), arm_compute::support::cpp11::to_string(), BorderSize::top, arm_compute::UNDEFINED, Window::use_tensor_dimensions(), and ITensorInfo::valid_region().
Referenced by GCPoolingLayer::configure(), GCNormalizationLayer::configure(), GCDepthwiseConvolutionLayer3x3::configure(), GCDirectConvolutionLayer::configure(), and GCConvolutionLayer::configure().
is_parallelisable()
bool is_parallelisable () const override virtual
Indicates whether or not the kernel is parallelisable.
If the kernel is parallelisable then the window returned by window() can be split into sub-windows which can then be run in parallel.
If the kernel is not parallelisable then only the window returned by window() can be passed to run()
Returns
True if the kernel is parallelisable
Reimplemented from IKernel.
Definition at line 47 of file GCFillBorderKernel.cpp.
 {
     return false;
 }
operator=() [1/2]
GCFillBorderKernel& operator= (const GCFillBorderKernel &) delete
Prevent instances of this class from being copied (As this class contains pointers)
operator=() [2/2]
GCFillBorderKernel& operator= (GCFillBorderKernel &&) default
Allow instances of this class to be moved.
run()
void run (const Window & window) override virtual
Enqueue the OpenGL ES shader to process the given window.
Parameters
[in] window Region on which to execute the kernel. (Must be a valid region of the window returned by window()).
Implements IGCKernel.
Definition at line 141 of file GCFillBorderKernel.cpp.
 {
     // Border mode undefined or border width == 0
     if(_kernel.get_program() == 0)
     {
         return;
     }
     ARM_COMPUTE_ERROR_ON_UNCONFIGURED_KERNEL(this);
     ARM_COMPUTE_ERROR_ON_MISMATCHING_WINDOWS(IGCKernel::window(), window);
     _kernel.use();
     Window slice = window.first_slice_window_3D();
     do
     {
         unsigned int idx = 0;
         add_3D_tensor_argument(idx, _tensor, 1, slice);
         _kernel.update_shader_params();
         enqueue(*this, slice);
     }
     while(window.slide_window_slice_3D(slice));
 }
References IGCKernel::add_3D_tensor_argument(), ARM_COMPUTE_ERROR_ON_MISMATCHING_WINDOWS, ARM_COMPUTE_ERROR_ON_UNCONFIGURED_KERNEL, arm_compute::enqueue(), Window::first_slice_window_3D(), arm_compute::test::validation::reference::slice(), Window::slide_window_slice_3D(), and IKernel::window().
set_constant_border()
void set_constant_border (unsigned int idx, const PixelValue & constant_border_value)
Function to set the constant value on fill border kernel depending on type.
Parameters
[in] idx Index of the kernel argument to set.
[in] constant_border_value Constant value to use for borders if border_mode is set to CONSTANT.
Definition at line 53 of file GCFillBorderKernel.cpp.
 {
     T value;
     constant_border_value.get(value);
     _kernel.set_argument(idx, static_cast<T>(value));
 }
The documentation for this class was generated from the following files:
arm_compute/core/GLES_COMPUTE/kernels/GCFillBorderKernel.h
src/core/GLES_COMPUTE/kernels/GCFillBorderKernel.cpp