Compute Library: NEConvolutionLayerReshapeWeights Class Reference
NEConvolutionLayerReshapeWeights Class Reference
Function to reshape the weights.
#include <NEGEMMConvolutionLayer.h>
Public Member Functions
NEConvolutionLayerReshapeWeights ()
Constructor.
void configure (const ITensor *weights, const ITensor *biases, ITensor *output)
Set the input and output tensors.
void run () override
Run the kernels contained in the function.
Public Member Functions inherited from IFunction
virtual ~IFunction ()=default
Destructor.
virtual void prepare ()
Prepare the function for executing.
Static Public Member Functions
static Status validate (const ITensorInfo *weights, const ITensorInfo *biases, const ITensorInfo *output)
Static function to check if given info will lead to a valid configuration of NEConvolutionLayerReshapeWeights.
Detailed Description
Function to reshape the weights.
This function calls the following kernel:
NEWeightsReshapeKernel
Definition at line 52 of file NEGEMMConvolutionLayer.h.
Constructor & Destructor Documentation
NEConvolutionLayerReshapeWeights()
NEConvolutionLayerReshapeWeights ()
Constructor.
Definition at line 41 of file NEGEMMConvolutionLayer.cpp.
     : _weights_reshape_kernel()
 {
 }
Member Function Documentation
configure()
void configure (const ITensor * weights, const ITensor * biases, ITensor * output)
Set the input and output tensors.
Parameters
[in] weights Weights tensor. Weights are 4D tensor with dimensions [kernel_x, kernel_y, IFM, OFM]. Data type supported: QASYMM8/F16/F32.
[in] biases Biases tensor. Shared biases supported. Biases are 1D tensor with dimensions [OFM]. Data type supported: Same as weights.
[out] output Destination tensor. Data types supported: Same as weights.
Definition at line 46 of file NEGEMMConvolutionLayer.cpp.
 {
     // Perform validation step
     ARM_COMPUTE_ERROR_ON_NULLPTR(weights, output);
     ARM_COMPUTE_ERROR_THROW_ON(NEConvolutionLayerReshapeWeights::validate(weights->info(),
                                                                           (biases != nullptr) ? biases->info() : nullptr,
                                                                           output->info()));
     const bool     append_biases = (biases != nullptr) && !is_data_type_quantized_asymmetric(weights->info()->data_type());
     const ITensor *biases_to_use = (append_biases) ? biases : nullptr;
     _weights_reshape_kernel.configure(weights, biases_to_use, output);
     output->info()->set_quantization_info(weights->info()->quantization_info());
 }
References ARM_COMPUTE_ERROR_ON_NULLPTR, ARM_COMPUTE_ERROR_THROW_ON, NEWeightsReshapeKernel::configure(), TensorInfo::data_type(), ITensor::info(), CLTensor::info(), arm_compute::is_data_type_quantized_asymmetric(), TensorInfo::quantization_info(), ITensorInfo::set_quantization_info(), NEConvolutionLayerReshapeWeights::validate(), and arm_compute::test::validation::weights.
Referenced by NEGEMMConvolutionLayer::configure().
run()
void run () override virtual
Run the kernels contained in the function.
For NEON kernels:
Multi-threading is used for the kernels which are parallelisable.
By default std::thread::hardware_concurrency() threads are used.
Note
CPPScheduler::set_num_threads() can be used to manually set the number of threads
For OpenCL kernels:
All the kernels are enqueued on the queue associated with CLScheduler.
The queue is then flushed.
Note
The function will not block until the kernels are executed. It is the user's responsibility to wait.
Will call prepare() on first run if hasn't been done
Implements IFunction.
Definition at line 87 of file NEGEMMConvolutionLayer.cpp.
 {
     NEScheduler::get().schedule(&_weights_reshape_kernel, 3);
 }
References Scheduler::get(), and IScheduler::schedule().
Referenced by NEGEMMConvolutionLayer::prepare().
validate()
Status validate (const ITensorInfo * weights, const ITensorInfo * biases, const ITensorInfo * output) static
Static function to check if given info will lead to a valid configuration of NEConvolutionLayerReshapeWeights.
Parameters
[in] weights Weights tensor. Weights are 4D tensor with dimensions [kernel_x, kernel_y, IFM, OFM]. Data type supported: QASYMM8/F16/F32.
[in] biases Biases tensor. Shared biases supported. Biases are 1D tensor with dimensions [OFM]. Data type supported: Same as weights.
[in] output Destination tensor. Data types supported: Same as weights.
Returns
an error status
Definition at line 62 of file NEGEMMConvolutionLayer.cpp.
 {
     ARM_COMPUTE_RETURN_ERROR_ON_NULLPTR(weights);
     ARM_COMPUTE_RETURN_ERROR_ON_DATA_TYPE_CHANNEL_NOT_IN(weights, 1, DataType::QASYMM8, DataType::F16, DataType::F32);
     ARM_COMPUTE_RETURN_ERROR_ON(weights->num_dimensions() > 4);
     if(biases != nullptr)
     {
         const int idx_kernels = get_data_layout_dimension_index(weights->data_layout(), DataLayoutDimension::BATCHES);
         ARM_COMPUTE_RETURN_ERROR_ON(is_data_type_quantized_asymmetric(weights->data_type()));
         ARM_COMPUTE_RETURN_ERROR_ON_MISMATCHING_DATA_TYPES(weights, biases);
         ARM_COMPUTE_RETURN_ERROR_ON(biases->dimension(0) != weights->dimension(idx_kernels));
         ARM_COMPUTE_RETURN_ERROR_ON(biases->num_dimensions() > 1);
     }
     if((output != nullptr) && (output->total_size() != 0))
     {
         ARM_COMPUTE_RETURN_ERROR_ON_MISMATCHING_DATA_TYPES(weights, output);
         NEWeightsReshapeKernel::validate(weights, biases, output);
     }
     return Status{};
 }
References ARM_COMPUTE_RETURN_ERROR_ON, ARM_COMPUTE_RETURN_ERROR_ON_DATA_TYPE_CHANNEL_NOT_IN, ARM_COMPUTE_RETURN_ERROR_ON_MISMATCHING_DATA_TYPES, ARM_COMPUTE_RETURN_ERROR_ON_NULLPTR, arm_compute::BATCHES, ITensorInfo::dimension(), arm_compute::F16, arm_compute::F32, arm_compute::get_data_layout_dimension_index(), arm_compute::is_data_type_quantized_asymmetric(), ITensorInfo::num_dimensions(), arm_compute::QASYMM8, ITensorInfo::total_size(), NEWeightsReshapeKernel::validate(), and arm_compute::test::validation::weights.
Referenced by NEConvolutionLayerReshapeWeights::configure(), and NEGEMMConvolutionLayer::validate().
The documentation for this class was generated from the following files:
arm_compute/runtime/NEON/functions/NEGEMMConvolutionLayer.h
src/runtime/NEON/functions/NEGEMMConvolutionLayer.cpp