Compute Library: CLMinMaxLocation Class Reference
CLMinMaxLocation Class Reference
Basic function to execute min and max location.
#include <CLMinMaxLocation.h>
Public Member Functions
CLMinMaxLocation ()
Constructor.
CLMinMaxLocation (const CLMinMaxLocation &)=delete
Prevent instances of this class from being copied (As this class contains pointers)
CLMinMaxLocation & operator= (const CLMinMaxLocation &)=delete
Prevent instances of this class from being copied (As this class contains pointers)
CLMinMaxLocation (CLMinMaxLocation &&)=default
Allow instances of this class to be moved.
CLMinMaxLocation & operator= (CLMinMaxLocation &&)=default
Allow instances of this class to be moved.
void configure (const ICLImage *input, void *min, void *max, CLCoordinates2DArray *min_loc=nullptr, CLCoordinates2DArray *max_loc=nullptr, uint32_t *min_count=nullptr, uint32_t *max_count=nullptr)
Initialise the kernel's inputs and outputs.
void run () override
Run the kernels contained in the function.
Public Member Functions inherited from IFunction
virtual ~IFunction ()=default
Destructor.
virtual void prepare ()
Prepare the function for executing.
Detailed Description
Basic function to execute min and max location.
This function calls the following OpenCL kernels:
CLMinMaxKernel
CLMinMaxLocationKernel
Definition at line 41 of file CLMinMaxLocation.h.
Constructor & Destructor Documentation
CLMinMaxLocation() [1/3]
CLMinMaxLocation ()
Constructor.
Definition at line 30 of file CLMinMaxLocation.cpp.
     : _min_max_kernel(),
       _min_max_loc_kernel(),
       _min_max_vals(),
       _min_max_count_vals(),
       _min(nullptr),
       _max(nullptr),
       _min_count(nullptr),
       _max_count(nullptr),
       _min_loc(nullptr),
       _max_loc(nullptr)
 {
 }
CLMinMaxLocation() [2/3]
CLMinMaxLocation (const CLMinMaxLocation &) delete
Prevent instances of this class from being copied (As this class contains pointers)
CLMinMaxLocation() [3/3]
CLMinMaxLocation (CLMinMaxLocation &&) default
Allow instances of this class to be moved.
Member Function Documentation
configure()
void configure (const ICLImage * input, void * min, void * max, CLCoordinates2DArray * min_loc = nullptr, CLCoordinates2DArray * max_loc = nullptr, uint32_t * min_count = nullptr, uint32_t * max_count = nullptr)
Initialise the kernel's inputs and outputs.
Note
When locations of min and max occurrences are requested, the reported number of locations is limited to the given array size.
Parameters
[in] input Input image. Data types supported: U8/S16/F32.
[out] min Minimum value of image. Data types supported: S32 if input type is U8/S16, F32 if input type is F32.
[out] max Maximum value of image. Data types supported: S32 if input type is U8/S16, F32 if input type is F32.
[out] min_loc (Optional) Array of Coordinates2D used to store minimum value locations.
[out] max_loc (Optional) Array of Coordinates2D used to store maximum value locations.
[out] min_count (Optional) Number of minimum value encounters.
[out] max_count (Optional) Number of maximum value encounters.
Definition at line 44 of file CLMinMaxLocation.cpp.
 {
     ARM_COMPUTE_ERROR_ON(nullptr == min);
     ARM_COMPUTE_ERROR_ON(nullptr == max);
     _min_max_vals       = cl::Buffer(CLScheduler::get().context(), CL_MEM_ALLOC_HOST_PTR | CL_MEM_READ_WRITE, 2 * sizeof(int32_t));
     _min_max_count_vals = cl::Buffer(CLScheduler::get().context(), CL_MEM_ALLOC_HOST_PTR | CL_MEM_READ_WRITE, 2 * sizeof(uint32_t));
     _min                = min;
     _max                = max;
     _min_count          = min_count;
     _max_count          = max_count;
     _min_loc            = min_loc;
     _max_loc            = max_loc;
     _min_max_kernel.configure(input, &_min_max_vals);
     _min_max_loc_kernel.configure(input, &_min_max_vals, &_min_max_count_vals, _min_loc, _max_loc);
 }
References ARM_COMPUTE_ERROR_ON, CLMinMaxKernel::configure(), CLMinMaxLocationKernel::configure(), and CLScheduler::get().
Referenced by arm_compute::test::validation::validate_configuration().
operator=() [1/2]
CLMinMaxLocation& operator= (const CLMinMaxLocation &) delete
Prevent instances of this class from being copied (As this class contains pointers)
operator=() [2/2]
CLMinMaxLocation& operator= (CLMinMaxLocation &&) default
Allow instances of this class to be moved.
run()
void run () override virtual
Run the kernels contained in the function.
For NEON kernels:
Multi-threading is used for the kernels which are parallelisable.
By default std::thread::hardware_concurrency() threads are used.
Note
CPPScheduler::set_num_threads() can be used to manually set the number of threads
For OpenCL kernels:
All the kernels are enqueued on the queue associated with CLScheduler.
The queue is then flushed.
Note
The function will not block until the kernels are executed. It is the user's responsibility to wait.
Will call prepare() on first run if hasn't been done
Implements IFunction.
Definition at line 62 of file CLMinMaxLocation.cpp.
 {
     cl::CommandQueue q = CLScheduler::get().queue();
     CLScheduler::get().enqueue(_min_max_kernel, false);
     CLScheduler::get().enqueue(_min_max_loc_kernel, false);
     // Update min and max
     q.enqueueReadBuffer(_min_max_vals, CL_FALSE, 0 * sizeof(int32_t), sizeof(int32_t), static_cast<int32_t *>(_min));
     q.enqueueReadBuffer(_min_max_vals, CL_FALSE, 1 * sizeof(int32_t), sizeof(int32_t), static_cast<int32_t *>(_max));
     // Update min and max count
     if(_min_count != nullptr)
     {
         q.enqueueReadBuffer(_min_max_count_vals, CL_FALSE, 0 * sizeof(uint32_t), sizeof(uint32_t), _min_count);
     }
     if(_max_count != nullptr)
     {
         q.enqueueReadBuffer(_min_max_count_vals, CL_FALSE, 1 * sizeof(uint32_t), sizeof(uint32_t), _max_count);
     }
     // Update min/max point arrays (Makes the kernel blocking)
     if(_min_loc != nullptr)
     {
         unsigned int min_count = 0;
         q.enqueueReadBuffer(_min_max_count_vals, CL_TRUE, 0 * sizeof(uint32_t), sizeof(uint32_t), &min_count);
         size_t min_corner_size = std::min(static_cast<size_t>(min_count), _min_loc->max_num_values());
         _min_loc->resize(min_corner_size);
     }
     if(_max_loc != nullptr)
     {
         unsigned int max_count = 0;
         q.enqueueReadBuffer(_min_max_count_vals, CL_TRUE, 1 * sizeof(uint32_t), sizeof(uint32_t), &max_count);
         size_t max_corner_size = std::min(static_cast<size_t>(max_count), _max_loc->max_num_values());
         _max_loc->resize(max_corner_size);
     }
 }
References CLScheduler::enqueue(), CLScheduler::get(), IArray< T >::max_num_values(), CLScheduler::queue(), and IArray< T >::resize().
The documentation for this class was generated from the following files:
arm_compute/runtime/CL/functions/CLMinMaxLocation.h
src/runtime/CL/functions/CLMinMaxLocation.cpp