Compute Library: CLTensorHandle Class Reference
CLTensorHandle Class Reference final
OpenCL Tensor handle interface object.
#include <CLTensorHandle.h>
Public Member Functions
CLTensorHandle (const ITensorInfo &info)
Default Constructor.
~CLTensorHandle ()=default
Destructor: free the tensor's memory.
CLTensorHandle (CLTensorHandle &&)=default
Allow instances of this class to be move constructed.
CLTensorHandle & operator= (CLTensorHandle &&)=default
Allow instances of this class to be moved.
void allocate () override
Allocates backend memory for the handle.
void free () override
Allocates backend memory for the handle.
void manage (IMemoryGroup *mg) override
Set backend tensor to be managed by a memory group.
void map (bool blocking) override
Maps backend tensor object.
void unmap () override
Un-maps a backend tensor object.
void release_if_unused () override
Releases backend tensor if is marked as unused.
arm_compute::ITensor & tensor () override
Backend tensor object accessor.
const arm_compute::ITensor & tensor () const override
Backend tensor object const accessor.
ITensorHandle * parent_handle () override
Return the parent tensor handle if is a subtensor else this.
bool is_subtensor () const override
Checks if a backing tensor is a sub-tensor object or not.
Target target () const override
Returns target type.
Public Member Functions inherited from ITensorHandle
virtual ~ITensorHandle ()=default
Default virtual destructor.
Detailed Description
OpenCL Tensor handle interface object.
Definition at line 38 of file CLTensorHandle.h.
Constructor & Destructor Documentation
CLTensorHandle() [1/2]
CLTensorHandle (const ITensorInfo & info)
Default Constructor.
Parameters
[in] info Tensor metadata
Definition at line 35 of file CLTensorHandle.cpp.
     : _tensor()
 {
     _tensor.allocator()->init(info);
 }
References CLTensor::allocator(), arm_compute::test::validation::info, and ITensorAllocator::init().
~CLTensorHandle()
~CLTensorHandle () default
Destructor: free the tensor's memory.
CLTensorHandle() [2/2]
CLTensorHandle (CLTensorHandle &&) default
Allow instances of this class to be move constructed.
Member Function Documentation
allocate()
void allocate () override virtual
Allocates backend memory for the handle.
Implements ITensorHandle.
Definition at line 41 of file CLTensorHandle.cpp.
 {
     _tensor.allocator()->allocate();
 }
References CLTensorAllocator::allocate(), and CLTensor::allocator().
free()
void free () override virtual
Allocates backend memory for the handle.
Implements ITensorHandle.
Definition at line 46 of file CLTensorHandle.cpp.
 {
     _tensor.allocator()->free();
 }
References CLTensor::allocator(), and CLTensorAllocator::free().
is_subtensor()
bool is_subtensor () const override virtual
Checks if a backing tensor is a sub-tensor object or not.
Returns
True if the backend tensor is a sub-tensor else false
Implements ITensorHandle.
Definition at line 94 of file CLTensorHandle.cpp.
 {
     return false;
 }
manage()
void manage (IMemoryGroup * mg) override virtual
Set backend tensor to be managed by a memory group.
Parameters
[in] mg Memory group
Implements ITensorHandle.
Definition at line 51 of file CLTensorHandle.cpp.
 {
     if(mg != nullptr)
     {
         auto *cl_mg = arm_compute::utils::cast::polymorphic_downcast<CLMemoryGroup *>(mg);
         cl_mg->manage(&_tensor);
     }
 }
map()
void map (bool blocking) override virtual
Maps backend tensor object.
Parameters
[in] blocking Flags if the mapping operations should be blocking
Implements ITensorHandle.
Definition at line 60 of file CLTensorHandle.cpp.
 {
     _tensor.map(blocking);
 }
References CLTensor::map().
operator=()
CLTensorHandle& operator= (CLTensorHandle &&) default
Allow instances of this class to be moved.
parent_handle()
ITensorHandle * parent_handle () override virtual
Return the parent tensor handle if is a subtensor else this.
Returns
Parent tensor handle
Implements ITensorHandle.
Definition at line 89 of file CLTensorHandle.cpp.
 {
     return this;
 }
release_if_unused()
void release_if_unused () override virtual
Releases backend tensor if is marked as unused.
Note
This has no effect on sub-tensors
Warning
Parent tensors don't keep track of sub-tensors, thus if a parent is set as unused then all sub-tensors will be invalidated, on the other hand if a sub-tensor is marked as unused then the parent tensor won't be released
Implements ITensorHandle.
Definition at line 70 of file CLTensorHandle.cpp.
 {
     // TODO (geopin01): Release tensor only if all sub-tensors are marked as not used
     if(!_tensor.is_used())
     {
         _tensor.allocator()->free();
     }
 }
References CLTensor::allocator(), CLTensorAllocator::free(), and ITensor::is_used().
target()
Target target () const override virtual
Returns target type.
Returns
Target type
Implements ITensorHandle.
Definition at line 99 of file CLTensorHandle.cpp.
 {
     return Target::CL;
 }
References arm_compute::graph::CL.
tensor() [1/2]
arm_compute::ITensor & tensor () override virtual
Backend tensor object accessor.
Implements ITensorHandle.
Definition at line 84 of file CLTensorHandle.cpp.
 {
     return _tensor;
 }
tensor() [2/2]
const arm_compute::ITensor & tensor () const override virtual
Backend tensor object const accessor.
Implements ITensorHandle.
Definition at line 79 of file CLTensorHandle.cpp.
 {
     return _tensor;
 }
unmap()
void unmap () override virtual
Un-maps a backend tensor object.
Implements ITensorHandle.
Definition at line 65 of file CLTensorHandle.cpp.
 {
     _tensor.unmap();
 }
References CLTensor::unmap().
The documentation for this class was generated from the following files:
arm_compute/graph/backends/CL/CLTensorHandle.h
src/graph/backends/CL/CLTensorHandle.cpp