Compute Library: GCGEMMInterleave4x4Kernel Class Reference
GCGEMMInterleave4x4Kernel Class Reference
OpenGL ES kernel which interleaves the elements of a matrix A in chunk of 4x4.
#include <GCGEMMInterleave4x4Kernel.h>
Public Member Functions
GCGEMMInterleave4x4Kernel ()
Default constructor.
GCGEMMInterleave4x4Kernel (const GCGEMMInterleave4x4Kernel &)=delete
Prevent instances of this class from being copied (As this class contains pointers)
GCGEMMInterleave4x4Kernel & operator= (const GCGEMMInterleave4x4Kernel &)=delete
Prevent instances of this class from being copied (As this class contains pointers)
GCGEMMInterleave4x4Kernel (GCGEMMInterleave4x4Kernel &&)=default
Allow instances of this class to be moved.
GCGEMMInterleave4x4Kernel & operator= (GCGEMMInterleave4x4Kernel &&)=default
Allow instances of this class to be moved.
void configure (const IGCTensor *input, IGCTensor *output)
Initialise the kernel's input and output.
void run (const Window &window) override
Enqueue the OpenGL ES shader to process the given window.
Public Member Functions inherited from IGCKernel
IGCKernel ()
Constructor.
GCKernel & kernel ()
Returns a reference to the GLES kernel of this object.
void add_1D_tensor_argument (unsigned int &idx, const IGCTensor *tensor, const unsigned int binding_point, const Window &window)
Add the passed 1D tensor's parameters to the object's kernel's arguments starting from the index idx.
void add_2D_tensor_argument (unsigned int &idx, const IGCTensor *tensor, const unsigned int binding_point, const Window &window)
Add the passed 2D tensor's parameters to the object's kernel's arguments starting from the index idx.
void add_3D_tensor_argument (unsigned int &idx, const IGCTensor *tensor, const unsigned int binding_point, const Window &window)
Add the passed 3D tensor's parameters to the object's kernel's arguments starting from the index idx.
unsigned int num_arguments_per_1D_tensor () const
Returns the number of arguments enqueued per 1D tensor object.
unsigned int num_arguments_per_2D_tensor () const
Returns the number of arguments enqueued per 2D tensor object.
unsigned int num_arguments_per_3D_tensor () const
Returns the number of arguments enqueued per 3D tensor object.
void set_lws_hint (gles::NDRange &lws_hint)
Set the Local-Workgroup-Size hint.
void set_target (GPUTarget target)
Set the targeted GPU architecture.
GPUTarget get_target () const
Get the targeted GPU architecture.
Public Member Functions inherited from IKernel
IKernel ()
Constructor.
virtual ~IKernel ()=default
Destructor.
virtual bool is_parallelisable () const
Indicates whether or not the kernel is parallelisable.
virtual BorderSize border_size () const
The size of the border for that kernel.
const Window & window () const
The maximum window the kernel can be executed on.
Detailed Description
OpenGL ES kernel which interleaves the elements of a matrix A in chunk of 4x4.
This function puts the values in a 4x4 block of Matrix A on the same row (Interleaved values)
\[ \left(\begin{array}{cccc} a00 & a01 & a02 & a03 \\ a10 & a11 & a12 & a13 \\ a20 & a21 & a22 & a23 \\ a30 & a31 & a32 & a33 \\ \end{array} \right) \rightarrow \left(\begin{array}{ccccccccccccccccc} a00 & a10 & a20 & a30 & a01 & a11 & a21 & a31 & a02 & a12 & a22 & a32 & a03 & a13 & a23 & a33 \\ \end{array} \right) \]
After this operation, the output matrix will have the following shape: [ height * 4, ceil(width / 4.0f) ]
Definition at line 52 of file GCGEMMInterleave4x4Kernel.h.
Constructor & Destructor Documentation
GCGEMMInterleave4x4Kernel() [1/3]
GCGEMMInterleave4x4Kernel ()
Default constructor.
Definition at line 39 of file GCGEMMInterleave4x4Kernel.cpp.
     : _input(nullptr), _output(nullptr)
 {
 }
GCGEMMInterleave4x4Kernel() [2/3]
GCGEMMInterleave4x4Kernel (const GCGEMMInterleave4x4Kernel &) delete
Prevent instances of this class from being copied (As this class contains pointers)
GCGEMMInterleave4x4Kernel() [3/3]
GCGEMMInterleave4x4Kernel (GCGEMMInterleave4x4Kernel &&) default
Allow instances of this class to be moved.
Member Function Documentation
configure()
void configure (const IGCTensor * input, IGCTensor * output)
Initialise the kernel's input and output.
Parameters
[in] input Input tensor. Data types supported: F16, F32
[out] output Output tensor. Data type supported: same as input
Definition at line 44 of file GCGEMMInterleave4x4Kernel.cpp.
 {
     ARM_COMPUTE_ERROR_ON_DATA_TYPE_CHANNEL_NOT_IN(input, 1, DataType::F16, DataType::F32);
     ARM_COMPUTE_ERROR_ON_NULLPTR(output);
     TensorShape output_shape = input->info()->tensor_shape();
     output_shape.set(0, input->info()->dimension(0) * 4);
     output_shape.set(1, std::ceil(input->info()->dimension(1) / 4.0f));
     // Output auto inizialitation if not yet initialized
     auto_init_if_empty(*output->info(), output_shape, 1, input->info()->data_type());
     ARM_COMPUTE_ERROR_ON_MISMATCHING_DIMENSIONS(output->info()->tensor_shape(), output_shape);
     ARM_COMPUTE_ERROR_ON_MISMATCHING_DATA_TYPES(input, output);
     _input  = input;
     _output = output;
     std::set<std::string> build_opts;
     std::string           dt_name = (input->info()->data_type() == DataType::F32) ? "DATA_TYPE_FP32" : "DATA_TYPE_FP16";
     build_opts.emplace(("#define " + dt_name));
     build_opts.emplace("#define LOCAL_SIZE_X " + support::cpp11::to_string(1));
     build_opts.emplace("#define LOCAL_SIZE_Y " + support::cpp11::to_string(1));
     build_opts.emplace("#define LOCAL_SIZE_Z " + support::cpp11::to_string(1));
     // Create kernel
     build_opts.emplace("#define GEMM_INTERLEAVE4x4");
     _kernel = static_cast<GCKernel>(GCKernelLibrary::get().create_kernel("gemm_interleave4x4", build_opts));
     // Configure kernel window
     const unsigned int     num_elems_processed_per_iteration_x = max_gc_vector_width / data_size_from_type(input->info()->data_type());
     constexpr unsigned int num_elems_processed_per_iteration_y = 4;
     const unsigned int     num_elems_written_per_iteration     = num_elems_processed_per_iteration_x * num_elems_processed_per_iteration_y;
     Window win = calculate_max_window(*input->info(), Steps(num_elems_processed_per_iteration_x, num_elems_processed_per_iteration_y));
     AccessWindowRectangle input_access(input->info(), 0, 0, num_elems_processed_per_iteration_x, num_elems_processed_per_iteration_y);
     AccessWindowRectangle output_access(output->info(), 0, 0, num_elems_written_per_iteration, 1, 4.f, 0.25f);
     update_window_and_padding(win, input_access, output_access);
     output_access.set_valid_region(win, input->info()->valid_region());
     IGCKernel::configure(win);
 }
References ARM_COMPUTE_ERROR_ON_DATA_TYPE_CHANNEL_NOT_IN, ARM_COMPUTE_ERROR_ON_MISMATCHING_DATA_TYPES, ARM_COMPUTE_ERROR_ON_MISMATCHING_DIMENSIONS, ARM_COMPUTE_ERROR_ON_NULLPTR, arm_compute::auto_init_if_empty(), arm_compute::calculate_max_window(), arm_compute::create_kernel(), arm_compute::data_size_from_type(), ITensorInfo::data_type(), ITensorInfo::dimension(), arm_compute::F16, arm_compute::F32, GCKernelLibrary::get(), ITensor::info(), arm_compute::test::validation::output_shape, ITensorInfo::tensor_shape(), arm_compute::support::cpp11::to_string(), arm_compute::update_window_and_padding(), and ITensorInfo::valid_region().
Referenced by GCGEMM::configure().
operator=() [1/2]
GCGEMMInterleave4x4Kernel& operator= (const GCGEMMInterleave4x4Kernel &) delete
Prevent instances of this class from being copied (As this class contains pointers)
operator=() [2/2]
GCGEMMInterleave4x4Kernel& operator= (GCGEMMInterleave4x4Kernel &&) default
Allow instances of this class to be moved.
run()
void run (const Window & window) override virtual
Enqueue the OpenGL ES shader to process the given window.
Parameters
[in] window Region on which to execute the kernel. (Must be a valid region of the window returned by window()).
Implements IGCKernel.
Definition at line 90 of file GCGEMMInterleave4x4Kernel.cpp.
 {
     ARM_COMPUTE_ERROR_ON_UNCONFIGURED_KERNEL(this);
     ARM_COMPUTE_ERROR_ON_INVALID_SUBWINDOW(IGCKernel::window(), window);
     _kernel.use();
     /*
      * This kernel puts the values in a 4x4 block of Matrix A on the same row (Interleaved values)
      *         |a00 a01 a02 a03|
      *         |a10 a11 a12 a13|
      *         |a20 a21 a22 a23| = | a00 a10 a20 a30 || a01 a11 a21 a31 || a02 a12 a22 a32 || a03 a13 a23 a33 |
      *         |a30 a31 a32 a33|
      *
      * After this operation, the output matrix will have the following shape: [ height * 4, width / 4 ]
      */
     Window in_slice  = window.first_slice_window_2D();
     Window out_slice = window.first_slice_window_2D();
     // Change x and y steps for the slide of output tensor
     out_slice.scale(Window::DimX, 4.f);
     out_slice.scale(Window::DimY, 0.25f);
     do
     {
         unsigned int idx = 0;
         add_2D_tensor_argument(idx, _input, 1, in_slice);
         add_2D_tensor_argument(idx, _output, 2, out_slice);
         _kernel.update_shader_params();
         enqueue(*this, in_slice);
     }
     while(window.slide_window_slice_2D(in_slice) && window.slide_window_slice_2D(out_slice));
 }
References IGCKernel::add_2D_tensor_argument(), ARM_COMPUTE_ERROR_ON_INVALID_SUBWINDOW, ARM_COMPUTE_ERROR_ON_UNCONFIGURED_KERNEL, Window::DimX, Window::DimY, arm_compute::enqueue(), Window::first_slice_window_2D(), Window::scale(), Window::slide_window_slice_2D(), and IKernel::window().
The documentation for this class was generated from the following files:
arm_compute/core/GLES_COMPUTE/kernels/GCGEMMInterleave4x4Kernel.h
src/core/GLES_COMPUTE/kernels/GCGEMMInterleave4x4Kernel.cpp