Compute Library: NERNNLayer Class Reference
NERNNLayer Class Reference
Basic function to run NERNNLayer.
#include <NERNNLayer.h>
Public Member Functions
NERNNLayer (std::shared_ptr< IMemoryManager > memory_manager=nullptr)
Default constructor.
NERNNLayer (const NERNNLayer &)=delete
Prevent instances of this class from being copied (As this class contains pointers)
NERNNLayer (NERNNLayer &&)=default
Default move constructor.
NERNNLayer & operator= (const NERNNLayer &)=delete
Prevent instances of this class from being copied (As this class contains pointers)
NERNNLayer & operator= (NERNNLayer &&)=default
Default move assignment operator.
void configure (const ITensor *input, const ITensor *weights, const ITensor *recurrent_weights, const ITensor *bias, ITensor *hidden_state, ITensor *output, ActivationLayerInfo &info)
Initialize the function.
void run () override
Run the kernels contained in the function.
void prepare () override
Prepare the function for executing.
Public Member Functions inherited from IFunction
virtual ~IFunction ()=default
Destructor.
Static Public Member Functions
static Status validate (const ITensorInfo *input, const ITensorInfo *weights, const ITensorInfo *recurrent_weights, const ITensorInfo *bias, const ITensorInfo *hidden_state, const ITensorInfo *output, const ActivationLayerInfo &info)
Initialize the function.
Detailed Description
Basic function to run NERNNLayer.
Definition at line 41 of file NERNNLayer.h.
Constructor & Destructor Documentation
NERNNLayer() [1/3]
NERNNLayer (std::shared_ptr< IMemoryManager > memory_manager = nullptr)
Default constructor.
Definition at line 36 of file NERNNLayer.cpp.
     : _memory_group(std::move(memory_manager)), _gemm_state_f(), _add_kernel(), _activation_kernel(), _fully_connected_kernel(), _copy_kernel(), _fully_connected_out(), _gemm_output(), _add_output(),
       _is_prepared(false)
 {
 }
NERNNLayer() [2/3]
NERNNLayer (const NERNNLayer &) delete
Prevent instances of this class from being copied (As this class contains pointers)
NERNNLayer() [3/3]
NERNNLayer (NERNNLayer &&) default
Default move constructor.
Member Function Documentation
configure()
void configure (const ITensor * input, const ITensor * weights, const ITensor * recurrent_weights, const ITensor * bias, ITensor * hidden_state, ITensor * output, ActivationLayerInfo & info)
Initialize the function.
Parameters
[in] input Input is a 2-D tensor of shape [input_size, batch_size]. Data types supported: F16/F32
[in] weights Weights tensor of shape [input_size, num_units] that multiplies the input. Data types supported: Same as input
[in] recurrent_weights Weights tensor of shape [num_units, num_units] that multiplies the current 'state'. Data types supported: Same as input
[in] bias Bias vector of shape [num_units]. Data types supported: Same as input
[out] output Output tensor of shape [num_units, batch_size]. Data types supported: Same as input
[in,out] hidden_state Output tensor of shape [num_units, batch_size]. Data types supported: Same as input
[in] info Activation layer parameter.
Definition at line 67 of file NERNNLayer.cpp.
 {
     ARM_COMPUTE_ERROR_ON_NULLPTR(input, weights, recurrent_weights, bias, hidden_state, output);
     ARM_COMPUTE_ERROR_THROW_ON(NERNNLayer::validate(input->info(), weights->info(), recurrent_weights->info(), bias->info(), hidden_state->info(), output->info(), info));
     const int   idx_height = get_data_layout_dimension_index(input->info()->data_layout(), DataLayoutDimension::HEIGHT);
     TensorShape shape      = misc::shape_calculator::compute_rnn_shape(recurrent_weights->info(), hidden_state->info()->dimension(idx_height));
     _is_prepared = false;
     // Manage intermediate buffers and configure
     _fully_connected_out.allocator()->init(TensorInfo(shape, 1, input->info()->data_type()));
     _gemm_output.allocator()->init(TensorInfo(shape, 1, input->info()->data_type()));
     // Manage intermediate buffers and configure
     _memory_group.manage(&_fully_connected_out);
     _fully_connected_kernel.configure(input, weights, bias, &_fully_connected_out);
     _memory_group.manage(&_gemm_output);
     _gemm_state_f.configure(hidden_state, recurrent_weights, nullptr, &_gemm_output, 1.f, 0.f);
     _add_output.allocator()->init(TensorInfo(shape, 1, input->info()->data_type()));
     _memory_group.manage(&_add_output);
     _add_kernel.configure(&_fully_connected_out, &_gemm_output, &_add_output, ConvertPolicy::SATURATE);
     _fully_connected_out.allocator()->allocate();
     _gemm_output.allocator()->allocate();
     _activation_kernel.configure(&_add_output, hidden_state, info);
     _add_output.allocator()->allocate();
     _copy_kernel.configure(hidden_state, output);
 }
References TensorAllocator::allocate(), Tensor::allocator(), ARM_COMPUTE_ERROR_ON_NULLPTR, ARM_COMPUTE_ERROR_THROW_ON, arm_compute::test::validation::bias, arm_compute::misc::shape_calculator::compute_rnn_shape(), NECopyKernel::configure(), NEActivationLayerKernel::configure(), NEArithmeticAdditionKernel::configure(), NEGEMM::configure(), NEFullyConnectedLayer::configure(), ITensorInfo::data_layout(), ITensorInfo::data_type(), ITensorInfo::dimension(), arm_compute::get_data_layout_dimension_index(), arm_compute::HEIGHT, ITensor::info(), CLTensor::info(), arm_compute::test::validation::info, TensorAllocator::init(), MemoryGroupBase< TensorType >::manage(), arm_compute::SATURATE, arm_compute::test::validation::shape, NERNNLayer::validate(), and arm_compute::test::validation::weights.
operator=() [1/2]
NERNNLayer& operator= (const NERNNLayer &) delete
Prevent instances of this class from being copied (As this class contains pointers)
operator=() [2/2]
NERNNLayer& operator= (NERNNLayer &&) default
Default move assignment operator.
prepare()
void prepare () override virtual
Prepare the function for executing.
Any one off pre-processing step required by the function is handled here
Note
Prepare stage might not need all the function's buffers' backing memory to be available in order to execute
Reimplemented from IFunction.
Definition at line 120 of file NERNNLayer.cpp.
 {
     if(!_is_prepared)
     {
         _fully_connected_kernel.prepare();
         _gemm_state_f.prepare();
         _is_prepared = true;
     }
 }
References NEGEMM::prepare(), and NEFullyConnectedLayer::prepare().
Referenced by NERNNLayer::run().
run()
void run () override virtual
Run the kernels contained in the function.
For NEON kernels:
Multi-threading is used for the kernels which are parallelisable.
By default std::thread::hardware_concurrency() threads are used.
Note
CPPScheduler::set_num_threads() can be used to manually set the number of threads
For OpenCL kernels:
All the kernels are enqueued on the queue associated with CLScheduler.
The queue is then flushed.
Note
The function will not block until the kernels are executed. It is the user's responsibility to wait.
Will call prepare() on first run if hasn't been done
Implements IFunction.
Definition at line 103 of file NERNNLayer.cpp.
 {
     prepare();
     MemoryGroupResourceScope scope_mg(_memory_group);
     _fully_connected_kernel.run();
     _gemm_state_f.run();
     NEScheduler::get().schedule(&_add_kernel, Window::DimY);
     NEScheduler::get().schedule(&_activation_kernel, Window::DimY);
     // copy hidden out to output
     NEScheduler::get().schedule(&_copy_kernel, Window::DimY);
 }
References Window::DimY, Scheduler::get(), NERNNLayer::prepare(), NEGEMM::run(), NEFullyConnectedLayer::run(), and IScheduler::schedule().
validate()
Status validate (const ITensorInfo * input, const ITensorInfo * weights, const ITensorInfo * recurrent_weights, const ITensorInfo * bias, const ITensorInfo * hidden_state, const ITensorInfo * output, const ActivationLayerInfo & info) static
Initialize the function.
Parameters
[in] input Input is a 2-D tensor of shape [input_size, batch_size]. Data types supported: F16/F32
[in] weights Weights tensor of shape [input_size, num_units] that multiplies the input. Data types supported: Same as input
[in] recurrent_weights Weights tensor of shape [num_units, num_units] that multiplies the current 'state'. Data types supported: Same as input
[in] bias Bias vector of shape [num_units]. Data types supported: Same as input
[in] output Output tensor of shape [num_units, batch_size]. Data types supported: Same as input
[in] hidden_state Output tensor of shape [num_units, batch_size]. Data types supported: Same as input
[in] info Activation layer parameter.
Returns
a status
Definition at line 42 of file NERNNLayer.cpp.
 {
     ARM_COMPUTE_RETURN_ERROR_ON_NULLPTR(input, weights, recurrent_weights, bias, hidden_state, output);
     const int idx_width  = get_data_layout_dimension_index(input->data_layout(), DataLayoutDimension::WIDTH);
     const int idx_height = get_data_layout_dimension_index(input->data_layout(), DataLayoutDimension::HEIGHT);
     ARM_COMPUTE_RETURN_ERROR_ON(input->dimension(idx_width) != weights->dimension(idx_width));
     ARM_COMPUTE_RETURN_ERROR_ON(weights->dimension(idx_height) != recurrent_weights->dimension(idx_width));
     ARM_COMPUTE_RETURN_ERROR_ON(recurrent_weights->dimension(idx_width) != recurrent_weights->dimension(idx_height));
     ARM_COMPUTE_RETURN_ERROR_ON(bias->num_dimensions() != 1);
     ARM_COMPUTE_RETURN_ERROR_ON(bias->dimension(idx_width) != weights->dimension(idx_height));
     ARM_COMPUTE_RETURN_ERROR_ON(hidden_state->dimension(idx_width) != weights->dimension(idx_height));
     ARM_COMPUTE_RETURN_ERROR_ON(hidden_state->dimension(idx_height) != input->dimension(idx_height));
     ARM_COMPUTE_RETURN_ERROR_ON_MISMATCHING_DIMENSIONS(output->tensor_shape(), hidden_state->tensor_shape());
     auto shape_info = TensorInfo(misc::shape_calculator::compute_rnn_shape(recurrent_weights, hidden_state->dimension(idx_height)), 1, input->data_type());
     ARM_COMPUTE_RETURN_ON_ERROR(NEFullyConnectedLayer::validate(input, weights, bias, &shape_info));
     ARM_COMPUTE_RETURN_ON_ERROR(NEArithmeticAdditionKernel::validate(&shape_info, &shape_info, &shape_info, ConvertPolicy::SATURATE));
     ARM_COMPUTE_RETURN_ON_ERROR(NEActivationLayerKernel::validate(&shape_info, &shape_info, info));
     return Status{};
 }
References ARM_COMPUTE_RETURN_ERROR_ON, ARM_COMPUTE_RETURN_ERROR_ON_MISMATCHING_DIMENSIONS, ARM_COMPUTE_RETURN_ERROR_ON_NULLPTR, ARM_COMPUTE_RETURN_ON_ERROR, arm_compute::test::validation::bias, arm_compute::misc::shape_calculator::compute_rnn_shape(), ITensorInfo::data_layout(), ITensorInfo::data_type(), ITensorInfo::dimension(), arm_compute::get_data_layout_dimension_index(), arm_compute::HEIGHT, arm_compute::test::validation::info, arm_compute::SATURATE, ITensorInfo::tensor_shape(), NEActivationLayerKernel::validate(), NEArithmeticAdditionKernel::validate(), NEFullyConnectedLayer::validate(), arm_compute::test::validation::weights, and arm_compute::WIDTH.
Referenced by NERNNLayer::configure().
The documentation for this class was generated from the following files:
arm_compute/runtime/NEON/functions/NERNNLayer.h
src/runtime/NEON/functions/NERNNLayer.cpp