Compute Library: EnumOption< T > Class Template Reference
EnumOption< T > Class Template Reference
Implementation of a simple option that accepts a value from a fixed set.
#include <EnumOption.h>
Public Member Functions
EnumOption (std::string name, std::set< T > allowed_values)
Construct option with allowed values.
EnumOption (std::string name, std::set< T > allowed_values, T default_value)
Construct option with allowed values, a fixed number of accepted values and default values for the option.
bool parse (std::string value) override
Parses the given string.
std::string help () const override
Help message for the option.
const T & value () const
Get the selected value.
Public Member Functions inherited from SimpleOption< T >
SimpleOption (std::string name, T default_value)
Construct the option with the given default value.
bool parse (std::string value) override
Parses the given string.
std::string help () const override
Help message for the option.
const T & value () const
Get the option value.
template<>
bool parse (std::string value)
Parses the given string.
Option (std::string name)
Constructor.
Option (std::string name, bool is_required, bool is_set)
Constructor.
Public Member Functions inherited from Option
Option (std::string name)
Constructor.
Option (std::string name, bool is_required, bool is_set)
Constructor.
virtual ~Option ()=default
Default destructor.
std::string name () const
Name of the option.
void set_required (bool is_required)
Set whether the option is required.
void set_help (std::string help)
Set the help message for the option.
bool is_required () const
Is the option required?
bool is_set () const
Has a value been assigned to the option?
Detailed Description
template<typename T>
class arm_compute::utils::EnumOption< T >
Implementation of a simple option that accepts a value from a fixed set.
Definition at line 40 of file EnumOption.h.
Constructor & Destructor Documentation
EnumOption() [1/2]
EnumOption (std::string name, std::set< T > allowed_values) inline
Construct option with allowed values.
Parameters
[in] name Name of the option.
[in] allowed_values Set of allowed values for the option.
Definition at line 72 of file EnumOption.h.
     : SimpleOption<T>{ std::move(name) }, _allowed_values{ std::move(allowed_values) }
 {
 }
EnumOption() [2/2]
EnumOption (std::string name, std::set< T > allowed_values, T default_value) inline
Construct option with allowed values, a fixed number of accepted values and default values for the option.
Parameters
[in] name Name of the option.
[in] allowed_values Set of allowed values for the option.
[in] default_value Default value.
Definition at line 78 of file EnumOption.h.
     : SimpleOption<T>{ std::move(name), std::move(default_value) }, _allowed_values{ std::move(allowed_values) }
 {
 }
Member Function Documentation
help()
std::string help () const override virtual
Help message for the option.
Returns
String representing the help message for the specific subclass.
Implements Option.
Definition at line 114 of file EnumOption.h.
 {
     std::stringstream msg;
     msg << "--" + this->name() + "={";
     for(const auto &value : _allowed_values)
     {
         msg << value << ",";
     }
     msg << "} - " << this->_help;
     return msg.str();
 }
parse()
bool parse (std::string value) override virtual
Parses the given string.
Parameters
[in] value String representation as passed on the command line.
Returns
True if the value could be parsed by the specific subclass.
Implements Option.
Definition at line 84 of file EnumOption.h.
 {
     try
     {
         std::stringstream stream{ value };
         T                 typed_value{};
         stream >> typed_value;
         if(!stream.fail())
         {
             if(_allowed_values.count(typed_value) == 0)
             {
                 return false;
             }
             this->_value  = std::move(typed_value);
             this->_is_set = true;
             return true;
         }
         return false;
     }
     catch(const std::invalid_argument &)
     {
         return false;
     }
 }
value()
const T & value () const inline
Get the selected value.
Returns
get the selected enum value.
Definition at line 130 of file EnumOption.h.
 {
     return this->_value;
 }
Referenced by arm_compute::utils::consume_common_graph_parameters(), CommonOptions::create_printers(), and main().
The documentation for this class was generated from the following file:
utils/command_line/EnumOption.h