Compute Library: CLChannelExtractKernel Class Reference
CLChannelExtractKernel Class Reference
Interface for the channel extract kernel.
#include <CLChannelExtractKernel.h>
Public Member Functions
CLChannelExtractKernel ()
Default constructor.
CLChannelExtractKernel (const CLChannelExtractKernel &)=delete
Prevent instances of this class from being copied (As this class contains pointers)
CLChannelExtractKernel & operator= (const CLChannelExtractKernel &)=delete
Prevent instances of this class from being copied (As this class contains pointers)
CLChannelExtractKernel (CLChannelExtractKernel &&)=default
Allow instances of this class to be moved.
CLChannelExtractKernel & operator= (CLChannelExtractKernel &&)=default
Allow instances of this class to be moved.
~CLChannelExtractKernel ()=default
Default destructor.
void configure (const ICLTensor *input, Channel channel, ICLTensor *output)
Set the input and output of the kernel.
void configure (const ICLMultiImage *input, Channel channel, ICLImage *output)
Set the input and output of the kernel.
void run (const Window &window, cl::CommandQueue &queue) override
Enqueue the OpenCL kernel to process the given window on the passed OpenCL command queue.
Public Member Functions inherited from ICLKernel
ICLKernel ()
Constructor.
cl::Kernel & kernel ()
Returns a reference to the OpenCL kernel of this object.
template<typename T >
void add_1D_array_argument (unsigned int &idx, const ICLArray< T > *array, const Strides &strides, unsigned int num_dimensions, const Window &window)
Add the passed 1D array's parameters to the object's kernel's arguments starting from the index idx.
void add_1D_tensor_argument (unsigned int &idx, const ICLTensor *tensor, const Window &window)
Add the passed 1D tensor's parameters to the object's kernel's arguments starting from the index idx.
void add_1D_tensor_argument_if (bool cond, unsigned int &idx, const ICLTensor *tensor, const Window &window)
Add the passed 1D tensor's parameters to the object's kernel's arguments starting from the index idx if the condition is true.
void add_2D_tensor_argument (unsigned int &idx, const ICLTensor *tensor, const Window &window)
Add the passed 2D tensor's parameters to the object's kernel's arguments starting from the index idx.
void add_2D_tensor_argument_if (bool cond, unsigned int &idx, const ICLTensor *tensor, const Window &window)
Add the passed 2D tensor's parameters to the object's kernel's arguments starting from the index idx if the condition is true.
void add_3D_tensor_argument (unsigned int &idx, const ICLTensor *tensor, const Window &window)
Add the passed 3D tensor's parameters to the object's kernel's arguments starting from the index idx.
void add_4D_tensor_argument (unsigned int &idx, const ICLTensor *tensor, const Window &window)
Add the passed 4D tensor's parameters to the object's kernel's arguments starting from the index idx.
template<typename T >
void add_argument (unsigned int &idx, T value)
Add the passed parameters to the object's kernel's arguments starting from the index idx.
void set_lws_hint (const cl::NDRange &lws_hint)
Set the Local-Workgroup-Size hint.
cl::NDRange lws_hint () const
Return the Local-Workgroup-Size hint.
const std::string & config_id () const
Get the configuration ID.
void set_target (GPUTarget target)
Set the targeted GPU architecture.
void set_target (cl::Device &device)
Set the targeted GPU architecture according to the CL device.
GPUTarget get_target () const
Get the targeted GPU architecture.
size_t get_max_workgroup_size ()
Get the maximum workgroup size for the device the CLKernelLibrary uses.
template<typename T , unsigned int dimension_size>
void add_array_argument (unsigned &idx, const ICLArray< T > *array, const Strides &strides, unsigned int num_dimensions, const Window &window)
Add the passed array's parameters to the object's kernel's arguments starting from the index idx.
template<unsigned int dimension_size>
void add_tensor_argument (unsigned &idx, const ICLTensor *tensor, const Window &window)
Public Member Functions inherited from IKernel
IKernel ()
Constructor.
virtual ~IKernel ()=default
Destructor.
virtual bool is_parallelisable () const
Indicates whether or not the kernel is parallelisable.
virtual BorderSize border_size () const
The size of the border for that kernel.
const Window & window () const
The maximum window the kernel can be executed on.
Additional Inherited Members
Static Public Member Functions inherited from ICLKernel
static constexpr unsigned int num_arguments_per_1D_array ()
Returns the number of arguments enqueued per 1D array object.
static constexpr unsigned int num_arguments_per_1D_tensor ()
Returns the number of arguments enqueued per 1D tensor object.
static constexpr unsigned int num_arguments_per_2D_tensor ()
Returns the number of arguments enqueued per 2D tensor object.
static constexpr unsigned int num_arguments_per_3D_tensor ()
Returns the number of arguments enqueued per 3D tensor object.
static constexpr unsigned int num_arguments_per_4D_tensor ()
Returns the number of arguments enqueued per 4D tensor object.
static cl::NDRange gws_from_window (const Window &window)
Get the global work size given an execution window.
Detailed Description
Interface for the channel extract kernel.
Definition at line 39 of file CLChannelExtractKernel.h.
Constructor & Destructor Documentation
CLChannelExtractKernel() [1/3]
CLChannelExtractKernel ()
Default constructor.
Definition at line 45 of file CLChannelExtractKernel.cpp.
     : _input(nullptr), _output(nullptr), _num_elems_processed_per_iteration(8), _subsampling(1)
 {
 }
CLChannelExtractKernel() [2/3]
CLChannelExtractKernel (const CLChannelExtractKernel &) delete
Prevent instances of this class from being copied (As this class contains pointers)
CLChannelExtractKernel() [3/3]
CLChannelExtractKernel (CLChannelExtractKernel &&) default
Allow instances of this class to be moved.
~CLChannelExtractKernel()
~CLChannelExtractKernel () default
Default destructor.
Member Function Documentation
configure() [1/2]
void configure (const ICLTensor * input, Channel channel, ICLTensor * output)
Set the input and output of the kernel.
Parameters
[in] input Source tensor. Formats supported: RGB888/RGBA8888/YUYV422/UYVY422
[in] channel Channel to extract.
[out] output Destination tensor. Must be of U8 format.
Definition at line 50 of file CLChannelExtractKernel.cpp.
 {
     ARM_COMPUTE_ERROR_ON_NULLPTR(input, output);
     ARM_COMPUTE_ERROR_ON(input == output);
     set_format_if_unknown(*output->info(), Format::U8);
     // Check if input tensor has a valid format
     ARM_COMPUTE_ERROR_ON_FORMAT_NOT_IN(input, Format::RGB888, Format::RGBA8888, Format::YUYV422, Format::UYVY422);
     ARM_COMPUTE_ERROR_ON_FORMAT_NOT_IN(output, Format::U8);
     ARM_COMPUTE_ERROR_ON_TENSOR_NOT_2D(output);
     // Check if channel is valid for given format
     const Format format = input->info()->format();
     ARM_COMPUTE_ERROR_ON_CHANNEL_NOT_IN_KNOWN_FORMAT(format, channel);
     // Half the processed elements for U,V channels due to sub-sampling of 2
     _subsampling = 1;
     if(format == Format::YUYV422 || format == Format::UYVY422)
     {
         // Check if the width of the tensor shape is even for formats with subsampled channels (UYVY422 and YUYV422)
         ARM_COMPUTE_ERROR_ON_TENSORS_NOT_EVEN(format, input);
         if(channel != Channel::Y)
         {
             _subsampling = 2;
         }
     }
     // Calculate output tensor shape using subsampling
     TensorShape output_shape = calculate_subsampled_shape(input->info()->tensor_shape(), format, channel);
     set_shape_if_empty(*output->info(), output_shape);
     ARM_COMPUTE_ERROR_ON_MISMATCHING_DIMENSIONS(output->info()->tensor_shape(), output_shape);
     _input  = input;
     _output = output;
     // Create kernel
     std::string           kernel_name = "channel_extract_" + string_from_format(format);
     std::set<std::string> build_opts  = { ("-DCHANNEL_" + string_from_channel(channel)) };
     _kernel                           = static_cast<cl::Kernel>(CLKernelLibrary::get().create_kernel(kernel_name, build_opts));
     // Configure window
     Window                 win = calculate_max_window(*input->info(), Steps(_num_elems_processed_per_iteration));
     AccessWindowHorizontal input_access(input->info(), 0, _num_elems_processed_per_iteration);
     AccessWindowRectangle  output_access(output->info(), 0, 0, _num_elems_processed_per_iteration, 1, 1.f / _subsampling, 1.f / _subsampling);
     update_window_and_padding(win, input_access, output_access);
     ValidRegion input_valid_region = input->info()->valid_region();
     output_access.set_valid_region(win, ValidRegion(input_valid_region.anchor, output->info()->tensor_shape()));
     ICLKernel::configure_internal(win);
 }
References ValidRegion::anchor, ARM_COMPUTE_ERROR_ON, ARM_COMPUTE_ERROR_ON_CHANNEL_NOT_IN_KNOWN_FORMAT, ARM_COMPUTE_ERROR_ON_FORMAT_NOT_IN, ARM_COMPUTE_ERROR_ON_MISMATCHING_DIMENSIONS, ARM_COMPUTE_ERROR_ON_NULLPTR, ARM_COMPUTE_ERROR_ON_TENSOR_NOT_2D, ARM_COMPUTE_ERROR_ON_TENSORS_NOT_EVEN, arm_compute::calculate_max_window(), arm_compute::calculate_subsampled_shape(), arm_compute::create_kernel(), ITensorInfo::format(), CLKernelLibrary::get(), ITensor::info(), arm_compute::test::validation::output_shape, arm_compute::RGB888, arm_compute::RGBA8888, arm_compute::set_format_if_unknown(), arm_compute::set_shape_if_empty(), arm_compute::string_from_channel(), arm_compute::string_from_format(), ITensorInfo::tensor_shape(), arm_compute::U8, arm_compute::update_window_and_padding(), arm_compute::UYVY422, ITensorInfo::valid_region(), arm_compute::Y, and arm_compute::YUYV422.
configure() [2/2]
void configure (const ICLMultiImage * input, Channel channel, ICLImage * output)
Set the input and output of the kernel.
Parameters
[in] input Multi-planar source image. Formats supported: NV12/NV21/IYUV/YUV444
[in] channel Channel to extract.
[out] output Single-planar 2D destination image. Must be of U8 format.
Definition at line 107 of file CLChannelExtractKernel.cpp.
 {
     ARM_COMPUTE_ERROR_ON_NULLPTR(input, output);
     ARM_COMPUTE_ERROR_ON_TENSOR_NOT_2D(output);
     set_format_if_unknown(*output->info(), Format::U8);
     // Check if channel is valid for given format
     const Format format = input->info()->format();
     ARM_COMPUTE_ERROR_ON_CHANNEL_NOT_IN_KNOWN_FORMAT(format, channel);
     // Get input plane from the given channel
     const ICLImage *input_plane = input->cl_plane(plane_idx_from_channel(format, channel));
     ARM_COMPUTE_ERROR_ON_NULLPTR(input_plane);
     if(Channel::Y == channel && format != Format::YUV444)
     {
         // Check if the width of the tensor shape is even for formats with subsampled channels (UYVY422 and YUYV422)
         ARM_COMPUTE_ERROR_ON_TENSORS_NOT_EVEN(format, input_plane);
     }
     // Calculate 2x2 subsampled tensor shape
     TensorShape output_shape = calculate_subsampled_shape(input->cl_plane(0)->info()->tensor_shape(), format, channel);
     set_shape_if_empty(*output->info(), output_shape);
     ARM_COMPUTE_ERROR_ON_MISMATCHING_DIMENSIONS(output_shape, output->info()->tensor_shape());
     // Check if input tensor has a valid format
     ARM_COMPUTE_ERROR_ON_FORMAT_NOT_IN(input, Format::NV12, Format::NV21, Format::IYUV, Format::YUV444);
     ARM_COMPUTE_ERROR_ON_FORMAT_NOT_IN(output, Format::U8);
     _output      = output;
     _input       = input_plane;
     _subsampling = 1;
     // Create kernel
     std::string           kernel_name;
     std::set<std::string> build_opts;
     if(Channel::Y == channel || Format::IYUV == format || Format::YUV444 == format)
     {
         kernel_name = "copy_plane";
     }
     else
     {
         kernel_name = "channel_extract_" + string_from_format(format);
         build_opts.insert(("-DCHANNEL_" + string_from_channel(channel)));
     }
     _kernel = static_cast<cl::Kernel>(CLKernelLibrary::get().create_kernel(kernel_name, build_opts));
     // Configure window
     Window                 win = calculate_max_window(*input_plane->info(), Steps(_num_elems_processed_per_iteration));
     AccessWindowHorizontal input_access(input_plane->info(), 0, _num_elems_processed_per_iteration);
     AccessWindowHorizontal output_access(output->info(), 0, _num_elems_processed_per_iteration);
     update_window_and_padding(win, input_access, output_access);
     output_access.set_valid_region(win, input_plane->info()->valid_region());
     ICLKernel::configure_internal(win);
 }
References ARM_COMPUTE_ERROR_ON_CHANNEL_NOT_IN_KNOWN_FORMAT, ARM_COMPUTE_ERROR_ON_FORMAT_NOT_IN, ARM_COMPUTE_ERROR_ON_MISMATCHING_DIMENSIONS, ARM_COMPUTE_ERROR_ON_NULLPTR, ARM_COMPUTE_ERROR_ON_TENSOR_NOT_2D, ARM_COMPUTE_ERROR_ON_TENSORS_NOT_EVEN, arm_compute::calculate_max_window(), arm_compute::calculate_subsampled_shape(), ICLMultiImage::cl_plane(), arm_compute::create_kernel(), MultiImageInfo::format(), CLKernelLibrary::get(), ITensor::info(), IMultiImage::info(), arm_compute::IYUV, arm_compute::NV12, arm_compute::NV21, arm_compute::test::validation::output_shape, arm_compute::plane_idx_from_channel(), arm_compute::set_format_if_unknown(), arm_compute::set_shape_if_empty(), arm_compute::string_from_channel(), arm_compute::string_from_format(), ITensorInfo::tensor_shape(), arm_compute::U8, arm_compute::update_window_and_padding(), ITensorInfo::valid_region(), arm_compute::Y, and arm_compute::YUV444.
operator=() [1/2]
CLChannelExtractKernel& operator= (const CLChannelExtractKernel &) delete
Prevent instances of this class from being copied (As this class contains pointers)
operator=() [2/2]
CLChannelExtractKernel& operator= (CLChannelExtractKernel &&) default
Allow instances of this class to be moved.
run()
void run (const Window & window, cl::CommandQueue & queue) override virtual
Enqueue the OpenCL kernel to process the given window on the passed OpenCL command queue.
Note
The queue is not flushed by this method, and therefore the kernel will not have been executed by the time this method returns.
Parameters
[in] window Region on which to execute the kernel. (Must be a valid region of the window returned by window()).
[in,out] queue Command queue on which to enqueue the kernel.
Implements ICLKernel.
Definition at line 168 of file CLChannelExtractKernel.cpp.
 {
     ARM_COMPUTE_ERROR_ON_UNCONFIGURED_KERNEL(this);
     ARM_COMPUTE_ERROR_ON_INVALID_SUBWINDOW(ICLKernel::window(), window);
     Window slice = window.first_slice_window_2D();
     do
     {
         Window win_sub(slice);
         win_sub.set(Window::DimX, Window::Dimension(win_sub.x().start() / _subsampling, win_sub.x().end() / _subsampling, win_sub.x().step() / _subsampling));
         win_sub.set(Window::DimY, Window::Dimension(win_sub.y().start() / _subsampling, win_sub.y().end() / _subsampling, 1));
         unsigned int idx = 0;
         add_2D_tensor_argument(idx, _input, slice);
         add_2D_tensor_argument(idx, _output, win_sub);
         enqueue(queue, *this, slice);
     }
     while(window.slide_window_slice_2D(slice));
 }
References ICLKernel::add_2D_tensor_argument(), ARM_COMPUTE_ERROR_ON_INVALID_SUBWINDOW, ARM_COMPUTE_ERROR_ON_UNCONFIGURED_KERNEL, Window::DimX, Window::DimY, Window::Dimension::end(), arm_compute::enqueue(), Window::first_slice_window_2D(), Window::set(), arm_compute::test::validation::reference::slice(), Window::slide_window_slice_2D(), Window::Dimension::start(), Window::Dimension::step(), IKernel::window(), Window::x(), and Window::y().
The documentation for this class was generated from the following files:
arm_compute/core/CL/kernels/CLChannelExtractKernel.h
src/core/CL/kernels/CLChannelExtractKernel.cpp