Compute Library: NECannyEdge Class Reference
NECannyEdge Class Reference
Basic function to execute canny edge on NEON.
#include <NECannyEdge.h>
Public Member Functions
NECannyEdge (std::shared_ptr< IMemoryManager > memory_manager=nullptr)
Constructor.
NECannyEdge (const NECannyEdge &)=delete
Prevent instances of this class from being copied (As this class contains pointers)
NECannyEdge & operator= (const NECannyEdge &)=delete
Prevent instances of this class from being copied (As this class contains pointers)
void configure (ITensor *input, ITensor *output, int32_t upper_thr, int32_t lower_thr, int32_t gradient_size, int32_t norm_type, BorderMode border_mode, uint8_t constant_border_value=0)
Initialise the function's source, destination, thresholds, gradient size, normalization type and border mode.
void run () override
Run the kernels contained in the function.
Public Member Functions inherited from IFunction
virtual ~IFunction ()=default
Destructor.
virtual void prepare ()
Prepare the function for executing.
Detailed Description
Basic function to execute canny edge on NEON.
This function calls the following NEON kernels and functions:
NEFillBorderKernel (if border_mode == REPLICATE or border_mode == CONSTANT)
NESobel3x3 (if gradient_size == 3) or NESobel5x5 (if gradient_size == 5) or NESobel7x7 (if gradient_size == 7)
NEGradientKernel
NEEdgeNonMaxSuppressionKernel
NEEdgeTraceKernel
Definition at line 53 of file NECannyEdge.h.
Constructor & Destructor Documentation
NECannyEdge() [1/2]
NECannyEdge (std::shared_ptr< IMemoryManager > memory_manager = nullptr)
Constructor.
Initialize Sobel kernel to nullptr.
Parameters
[in] memory_manager (Optional) Memory manager.
Definition at line 44 of file NECannyEdge.cpp.
     : _memory_group(std::move(memory_manager)),
       _sobel(),
       _gradient(),
       _non_max_suppr(),
       _edge_trace(),
       _border_mag_gradient(),
       _border_edge_trace(),
       _gx(),
       _gy(),
       _magnitude(),
       _phase(),
       _nonmax(),
       _output(nullptr)
 {
 }
NECannyEdge() [2/2]
NECannyEdge (const NECannyEdge &) delete
Prevent instances of this class from being copied (As this class contains pointers)
Member Function Documentation
configure()
void configure (ITensor * input, ITensor * output, int32_t upper_thr, int32_t lower_thr, int32_t gradient_size, int32_t norm_type, BorderMode border_mode, uint8_t constant_border_value = 0)
Initialise the function's source, destination, thresholds, gradient size, normalization type and border mode.
Parameters
[in,out] input Source tensor. Data type supported: U8. (Written to only for border_mode != UNDEFINED)
[out] output Destination tensor. Data type supported: U8.
[in] upper_thr Upper threhold used for the hysteresis
[in] lower_thr Lower threshold used for the hysteresis.
[in] gradient_size Gradient size (3, 5 or 7)
[in] norm_type Normalization type. If 1, L1-Norm otherwise L2-Norm
[in] border_mode Border mode to use for the convolution.
[in] constant_border_value (Optional) Constant value to use for borders if border_mode is set to CONSTANT.
Definition at line 61 of file NECannyEdge.cpp.
 {
     ARM_COMPUTE_ERROR_ON_NULLPTR(input, output);
     ARM_COMPUTE_ERROR_ON_DATA_TYPE_CHANNEL_NOT_IN(input, 1, DataType::U8);
     ARM_COMPUTE_ERROR_ON_DATA_TYPE_CHANNEL_NOT_IN(output, 1, DataType::U8);
     ARM_COMPUTE_ERROR_ON((1 != norm_type) && (2 != norm_type));
     ARM_COMPUTE_ERROR_ON((gradient_size != 3) && (gradient_size != 5) && (gradient_size != 7));
     ARM_COMPUTE_ERROR_ON((lower_thr < 0) || (lower_thr >= upper_thr));
     _output = output;
     const TensorShape &shape = input->info()->tensor_shape();
     TensorInfo         gradient_info;
     TensorInfo         magnitude_info;
     // Initialize images
     if(gradient_size < 7)
     {
         gradient_info.init(shape, Format::S16);
         magnitude_info.init(shape, Format::U16);
     }
     else
     {
         gradient_info.init(shape, Format::S32);
         magnitude_info.init(shape, Format::U32);
     }
     _gx.allocator()->init(gradient_info);
     _gy.allocator()->init(gradient_info);
     _magnitude.allocator()->init(magnitude_info);
     TensorInfo info(shape, Format::U8);
     _phase.allocator()->init(info);
     _nonmax.allocator()->init(info);
     // Manage intermediate buffers
     _memory_group.manage(&_gx);
     _memory_group.manage(&_gy);
     // Configure/Init sobelNxN
     if(gradient_size == 3)
     {
         auto k = arm_compute::support::cpp14::make_unique<NESobel3x3>();
         k->configure(input, &_gx, &_gy, border_mode, constant_border_value);
         _sobel = std::move(k);
     }
     else if(gradient_size == 5)
     {
         auto k = arm_compute::support::cpp14::make_unique<NESobel5x5>();
         k->configure(input, &_gx, &_gy, border_mode, constant_border_value);
         _sobel = std::move(k);
     }
     else if(gradient_size == 7)
     {
         auto k = arm_compute::support::cpp14::make_unique<NESobel7x7>();
         k->configure(input, &_gx, &_gy, border_mode, constant_border_value);
         _sobel = std::move(k);
     }
     else
     {
         ARM_COMPUTE_ERROR("Gradient size %d not supported\n", gradient_size);
     }
     // Manage intermediate buffers
     _memory_group.manage(&_magnitude);
     _memory_group.manage(&_phase);
     // Configure gradient
     auto k = arm_compute::support::cpp14::make_unique<NEGradientKernel>();
     k->configure(&_gx, &_gy, &_magnitude, &_phase, norm_type);
     _gradient = std::move(k);
     // Allocate intermediate tensors
     _gx.allocator()->allocate();
     _gy.allocator()->allocate();
     // Manage intermediate buffers
     _memory_group.manage(&_nonmax);
     // Configure non-maxima suppression
     _non_max_suppr.configure(&_magnitude, &_phase, &_nonmax, upper_thr, lower_thr, border_mode == BorderMode::UNDEFINED);
     // Fill border around magnitude image as non-maxima suppression will access
     // it. If border mode is undefined filling the border is a nop.
     _border_mag_gradient.configure(&_magnitude, _non_max_suppr.border_size(), border_mode, constant_border_value);
     // Allocate intermediate tensors
     _phase.allocator()->allocate();
     _magnitude.allocator()->allocate();
     // Configure edge tracing
     _edge_trace.configure(&_nonmax, output);
     // Fill border with "No edge" to stop recursion in edge trace
     _border_edge_trace.configure(&_nonmax, _edge_trace.border_size(), BorderMode::CONSTANT, static_cast<float>(0.f));
     // Allocate intermediate tensors
     _nonmax.allocator()->allocate();
 }
References TensorAllocator::allocate(), Tensor::allocator(), ARM_COMPUTE_ERROR, ARM_COMPUTE_ERROR_ON, ARM_COMPUTE_ERROR_ON_DATA_TYPE_CHANNEL_NOT_IN, ARM_COMPUTE_ERROR_ON_NULLPTR, arm_compute::test::validation::border_mode, NEEdgeNonMaxSuppressionKernel::border_size(), NEEdgeTraceKernel::border_size(), NEFillBorderKernel::configure(), NEEdgeNonMaxSuppressionKernel::configure(), NEEdgeTraceKernel::configure(), arm_compute::CONSTANT, ITensor::info(), arm_compute::test::validation::info, TensorAllocator::init(), TensorInfo::init(), MemoryGroupBase< TensorType >::manage(), arm_compute::S16, arm_compute::S32, arm_compute::test::validation::shape, ITensorInfo::tensor_shape(), arm_compute::U16, arm_compute::U32, arm_compute::U8, and arm_compute::UNDEFINED.
Referenced by arm_compute::test::validation::DATA_TEST_CASE().
operator=()
NECannyEdge& operator= (const NECannyEdge &) delete
Prevent instances of this class from being copied (As this class contains pointers)
run()
void run () override virtual
Run the kernels contained in the function.
For NEON kernels:
Multi-threading is used for the kernels which are parallelisable.
By default std::thread::hardware_concurrency() threads are used.
Note
CPPScheduler::set_num_threads() can be used to manually set the number of threads
For OpenCL kernels:
All the kernels are enqueued on the queue associated with CLScheduler.
The queue is then flushed.
Note
The function will not block until the kernels are executed. It is the user's responsibility to wait.
Will call prepare() on first run if hasn't been done
Implements IFunction.
Definition at line 161 of file NECannyEdge.cpp.
 {
     ARM_COMPUTE_ERROR_ON_MSG(_sobel == nullptr, "Unconfigured function");
     MemoryGroupResourceScope scope_mg(_memory_group);
     // Run sobelNxN
     _sobel->run();
     // Run gradient
     NEScheduler::get().schedule(_gradient.get(), Window::DimY);
     // Fill border before non-maxima suppression. Nop for border mode undefined.
     NEScheduler::get().schedule(&_border_mag_gradient, Window::DimZ);
     // Run non-maxima suppression
     NEScheduler::get().schedule(&_non_max_suppr, Window::DimY);
     ARM_COMPUTE_ERROR_ON(_output->buffer() == nullptr);
     std::fill_n(_output->buffer(), _output->info()->total_size(), 0);
     // Fill border before edge trace
     NEScheduler::get().schedule(&_border_edge_trace, Window::DimZ);
     // Run edge tracing
     NEScheduler::get().schedule(&_edge_trace, Window::DimY);
 }
References ARM_COMPUTE_ERROR_ON, ARM_COMPUTE_ERROR_ON_MSG, ITensor::buffer(), Window::DimY, Window::DimZ, Scheduler::get(), ITensor::info(), IScheduler::schedule(), and ITensorInfo::total_size().
The documentation for this class was generated from the following files:
arm_compute/runtime/NEON/functions/NECannyEdge.h
src/runtime/NEON/functions/NECannyEdge.cpp