Compute Library: EltwiseLayer Class Reference
EltwiseLayer Class Reference final
#include <Layers.h>
Public Member Functions
EltwiseLayer (SubStream &&sub_stream0, SubStream &&sub_stream1, EltwiseOperation op)
Construct an element-wise operation layer.
NodeID create_layer (IStream &s) override
Create layer and add to the given stream.
Public Member Functions inherited from ILayer
virtual ~ILayer ()=default
Default destructor.
ILayer & set_name (std::string name)
Sets the name of the layer.
const std::string & name () const
Layer name accessor.
Detailed Description
Definition at line 524 of file Layers.h.
Constructor & Destructor Documentation
EltwiseLayer()
EltwiseLayer (SubStream && sub_stream0, SubStream && sub_stream1, EltwiseOperation op) inline
Construct an element-wise operation layer.
Parameters
[in] sub_stream0 First graph sub-stream
[in] sub_stream1 First graph sub-stream
[in] op Element-wise operation to perform
Definition at line 533 of file Layers.h.
         : _ss0(std::move(sub_stream0)), _ss1(std::move(sub_stream1)), _op(op)
     {
     }
Member Function Documentation
create_layer()
NodeID create_layer (IStream & s) inline override virtual
Create layer and add to the given stream.
Parameters
[in] s Stream to add layer to.
Returns
ID of the created node.
Implements ILayer.
Definition at line 538 of file Layers.h.
     {
         NodeParams  common_params = { name(), s.hints().target_hint };
         NodeIdxPair input0        = { _ss0.tail_node(), 0 };
         NodeIdxPair input1        = { _ss1.tail_node(), 0 };
         return GraphBuilder::add_elementwise_node(s.graph(), common_params, input0, input1, _op);
     }
References GraphBuilder::add_elementwise_node(), IStream::graph(), IStream::hints(), ILayer::name(), IStream::tail_node(), and StreamHints::target_hint.
The documentation for this class was generated from the following file:
arm_compute/graph/frontend/Layers.h