Compute Library: NEYOLOLayerKernel Class Reference
NEYOLOLayerKernel Class Reference
Interface for the YOLO layer kernel.
#include <NEYOLOLayerKernel.h>
Public Member Functions
const char * name () const override
Name of the kernel.
NEYOLOLayerKernel ()
Constructor.
NEYOLOLayerKernel (const NEYOLOLayerKernel &)=delete
Prevent instances of this class from being copied (As this class contains pointers)
NEYOLOLayerKernel (NEYOLOLayerKernel &&)=default
Default move constructor.
NEYOLOLayerKernel & operator= (const NEYOLOLayerKernel &)=delete
Prevent instances of this class from being copied (As this class contains pointers)
NEYOLOLayerKernel & operator= (NEYOLOLayerKernel &&)=default
Default move assignment operator.
~NEYOLOLayerKernel ()=default
Default destructor.
void configure (ITensor *input, ITensor *output, const ActivationLayerInfo &act_info, int32_t num_classes)
Set the input and output tensor.
void run (const Window &window, const ThreadInfo &info) override
Execute the kernel on the passed window.
Public Member Functions inherited from ICPPKernel
virtual ~ICPPKernel ()=default
Default destructor.
Public Member Functions inherited from IKernel
IKernel ()
Constructor.
virtual ~IKernel ()=default
Destructor.
virtual bool is_parallelisable () const
Indicates whether or not the kernel is parallelisable.
virtual BorderSize border_size () const
The size of the border for that kernel.
const Window & window () const
The maximum window the kernel can be executed on.
Static Public Member Functions
static Status validate (const ITensorInfo *input, const ITensorInfo *output, const ActivationLayerInfo &act_info, int32_t num_classes)
Static function to check if given info will lead to a valid configuration of NEYOLOLayerKernel.
Detailed Description
Interface for the YOLO layer kernel.
Definition at line 34 of file NEYOLOLayerKernel.h.
Constructor & Destructor Documentation
NEYOLOLayerKernel() [1/3]
NEYOLOLayerKernel ()
Constructor.
Definition at line 99 of file NEYOLOLayerKernel.cpp.
     : _func(nullptr), _input(nullptr), _output(nullptr), _act_info(), _num_classes()
 {
 }
NEYOLOLayerKernel() [2/3]
NEYOLOLayerKernel (const NEYOLOLayerKernel &) delete
Prevent instances of this class from being copied (As this class contains pointers)
NEYOLOLayerKernel() [3/3]
NEYOLOLayerKernel (NEYOLOLayerKernel &&) default
Default move constructor.
~NEYOLOLayerKernel()
~NEYOLOLayerKernel () default
Default destructor.
Member Function Documentation
configure()
void configure (ITensor * input, ITensor * output, const ActivationLayerInfo & act_info, int32_t num_classes)
Set the input and output tensor.
Note
If the output tensor is a nullptr or is equal to the input, the activation function will be performed in-place
Parameters
[in,out] input Source tensor. In case of output tensor = nullptr, this tensor will store the result of the activation function. Data types supported: F16/F32.
[out] output Destination tensor. Data type supported: same as input
[in] act_info Activation layer parameters.
[in] num_classes Number of classes to activate (must be submultiple of input channels)
Definition at line 204 of file NEYOLOLayerKernel.cpp.
 {
     ARM_COMPUTE_ERROR_ON_NULLPTR(input);
     ARM_COMPUTE_ERROR_THROW_ON(validate_arguments(input->info(), (output != nullptr) ? output->info() : nullptr, act_info, num_classes));
     _input       = input;
     _output      = output;
     _act_info    = act_info;
     _num_classes = num_classes;
     switch(_input->info()->data_type())
     {
 #ifdef __ARM_FEATURE_FP16_VECTOR_ARITHMETIC
         case DataType::F16:
             _func = (_input->info()->data_layout() == DataLayout::NHWC) ? &NEYOLOLayerKernel::yolo_layer_fp16_nhwc : &NEYOLOLayerKernel::yolo_layer_fp16_nchw;
             break;
 #endif // __ARM_FEATURE_FP16_VECTOR_ARITHMETIC
         case DataType::F32:
             _func = (_input->info()->data_layout() == DataLayout::NHWC) ? &NEYOLOLayerKernel::yolo_layer_fp32_nhwc : &NEYOLOLayerKernel::yolo_layer_fp32_nchw;
             break;
         default:
             ARM_COMPUTE_ERROR("Element size not supported");
             break;
     }
     // Configure kernel window
     auto win_config = validate_and_configure_window(input->info(), (output == nullptr) ? nullptr : output->info());
     ARM_COMPUTE_ERROR_THROW_ON(win_config.first);
     ICPPKernel::configure(win_config.second);
 }
References arm_compute::test::validation::act_info, ARM_COMPUTE_ERROR, ARM_COMPUTE_ERROR_ON_NULLPTR, ARM_COMPUTE_ERROR_THROW_ON, ITensorInfo::data_layout(), ITensorInfo::data_type(), arm_compute::F16, arm_compute::F32, ITensor::info(), and arm_compute::NHWC.
name()
const char* name () const inline override virtual
Name of the kernel.
Returns
Kernel name
Implements ICPPKernel.
Definition at line 37 of file NEYOLOLayerKernel.h.
     {
         return "NEYOLOLayerKernel";
     }
operator=() [1/2]
NEYOLOLayerKernel& operator= (const NEYOLOLayerKernel &) delete
Prevent instances of this class from being copied (As this class contains pointers)
operator=() [2/2]
NEYOLOLayerKernel& operator= (NEYOLOLayerKernel &&) default
Default move assignment operator.
run()
void run (const Window & window, const ThreadInfo & info) override virtual
Execute the kernel on the passed window.
Warning
If is_parallelisable() returns false then the passed window must be equal to window()
Note
The window has to be a region within the window returned by the window() method
The width of the window has to be a multiple of num_elems_processed_per_iteration().
Parameters
[in] window Region on which to execute the kernel. (Must be a region of the window returned by window())
[in] info Info about executing thread and CPU.
Implements ICPPKernel.
Definition at line 243 of file NEYOLOLayerKernel.cpp.
 {
     ARM_COMPUTE_UNUSED(info);
     ARM_COMPUTE_ERROR_ON_UNCONFIGURED_KERNEL(this);
     ARM_COMPUTE_ERROR_ON_INVALID_SUBWINDOW(IKernel::window(), window);
     ARM_COMPUTE_ERROR_ON(_func == nullptr);
     (this->*_func)(window);
 }
References ARM_COMPUTE_ERROR_ON, ARM_COMPUTE_ERROR_ON_INVALID_SUBWINDOW, ARM_COMPUTE_ERROR_ON_UNCONFIGURED_KERNEL, ARM_COMPUTE_UNUSED, arm_compute::test::validation::info, and IKernel::window().
validate()
Status validate (const ITensorInfo * input, const ITensorInfo * output, const ActivationLayerInfo & act_info, int32_t num_classes) static
Static function to check if given info will lead to a valid configuration of NEYOLOLayerKernel.
Parameters
[in] input Source tensor info. In case of output tensor info = nullptr, this tensor will store the result of the activation function. Data types supported: F16/F32.
[in] output Destination tensor info. Data type supported: same as input
[in] act_info Activation layer information.
[in] num_classes Number of classes to activate (must be submultiple of input channels)
Returns
a status
Definition at line 235 of file NEYOLOLayerKernel.cpp.
 {
     ARM_COMPUTE_RETURN_ON_ERROR(validate_arguments(input, output, act_info, num_classes));
     ARM_COMPUTE_RETURN_ON_ERROR(validate_and_configure_window(input->clone().get(), (output == nullptr) ? nullptr : output->clone().get()).first);
     return Status{};
 }
References arm_compute::test::validation::act_info, ARM_COMPUTE_RETURN_ON_ERROR, and ICloneable< T >::clone().
Referenced by NEYOLOLayer::validate().
The documentation for this class was generated from the following files:
arm_compute/core/NEON/kernels/NEYOLOLayerKernel.h
src/core/NEON/kernels/NEYOLOLayerKernel.cpp