Compute Library: CLBatchToSpaceLayer Class Reference
CLBatchToSpaceLayer Class Reference
Basic function to run CLBatchToSpaceLayerKernel.
#include <CLBatchToSpaceLayer.h>
Public Member Functions
CLBatchToSpaceLayer ()
Default constructor.
void configure (const ICLTensor *input, const ICLTensor *block_shape, ICLTensor *output)
Set the input and output tensors.
void configure (const ICLTensor *input, int32_t block_shape_x, int32_t block_shape_y, ICLTensor *output)
Set the input and output tensors.
void run () override
Run the kernels contained in the function.
Public Member Functions inherited from IFunction
virtual ~IFunction ()=default
Destructor.
virtual void prepare ()
Prepare the function for executing.
Static Public Member Functions
static Status validate (const ITensorInfo *input, const ITensorInfo *block_shape, const ITensorInfo *output)
Static function to check if given info will lead to a valid configuration of CLBatchToSpaceLayer.
static Status validate (const ITensorInfo *input, int32_t block_shape_x, int32_t block_shape_y, const ITensorInfo *output)
Static function to check if given info will lead to a valid configuration of CLBatchToSpaceLayer (Static block shape).
Detailed Description
Basic function to run CLBatchToSpaceLayerKernel.
Definition at line 37 of file CLBatchToSpaceLayer.h.
Constructor & Destructor Documentation
CLBatchToSpaceLayer()
CLBatchToSpaceLayer ()
Default constructor.
Definition at line 35 of file CLBatchToSpaceLayer.cpp.
     : _batch_to_space_kernel()
 {
 }
Member Function Documentation
configure() [1/2]
void configure (const ICLTensor * input, const ICLTensor * block_shape, ICLTensor * output)
Set the input and output tensors.
Parameters
[in] input Tensor input. Supported tensor rank: 4. Data types supported: U8/S8/QASYMM8/U16/S16/F16/U32/S32/F32.
[in] block_shape 1-D tensor with shape [M]. Data types supported: S32
[out] output Tensor output. Data types supported: same as input
Definition at line 40 of file CLBatchToSpaceLayer.cpp.
 {
     _batch_to_space_kernel.configure(input, block_shape, output);
 }
References CLBatchToSpaceLayerKernel::configure().
configure() [2/2]
void configure (const ICLTensor * input, int32_t block_shape_x, int32_t block_shape_y, ICLTensor * output)
Set the input and output tensors.
(Static block shape).
Parameters
[in] input Tensor input. Supported tensor rank: 4. Data types supported: U8/S8/QASYMM8/U16/S16/F16/U32/S32/F32.
[in] block_shape_x Block shape x value.
[in] block_shape_y Block shape y value.
[out] output Tensor output. Data types supported: same as input
Definition at line 45 of file CLBatchToSpaceLayer.cpp.
 {
     _batch_to_space_kernel.configure(input, block_shape_x, block_shape_y, output);
 }
References CLBatchToSpaceLayerKernel::configure().
run()
void run () override virtual
Run the kernels contained in the function.
For NEON kernels:
Multi-threading is used for the kernels which are parallelisable.
By default std::thread::hardware_concurrency() threads are used.
Note
CPPScheduler::set_num_threads() can be used to manually set the number of threads
For OpenCL kernels:
All the kernels are enqueued on the queue associated with CLScheduler.
The queue is then flushed.
Note
The function will not block until the kernels are executed. It is the user's responsibility to wait.
Will call prepare() on first run if hasn't been done
Implements IFunction.
Definition at line 60 of file CLBatchToSpaceLayer.cpp.
 {
     CLScheduler::get().enqueue(_batch_to_space_kernel, true);
 }
References CLScheduler::enqueue(), and CLScheduler::get().
validate() [1/2]
Status validate (const ITensorInfo * input, const ITensorInfo * block_shape, const ITensorInfo * output) static
Static function to check if given info will lead to a valid configuration of CLBatchToSpaceLayer.
Parameters
[in] input Tensor input info. Supported tensor rank: 4. Data types supported: U8/S8/QASYMM8/U16/S16/F16/U32/S32/F32.
[in] block_shape block shape tensor info with shape [M]. Data types supported: S32
[out] output Tensor output info. Data types supported: same as input
Returns
a status
Definition at line 50 of file CLBatchToSpaceLayer.cpp.
 {
     return CLBatchToSpaceLayerKernel::validate(input, block_shape, output);
 }
References CLBatchToSpaceLayerKernel::validate().
validate() [2/2]
Status validate (const ITensorInfo * input, int32_t block_shape_x, int32_t block_shape_y, const ITensorInfo * output) static
Static function to check if given info will lead to a valid configuration of CLBatchToSpaceLayer (Static block shape).
Parameters
[in] input Tensor input info. Supported tensor rank: 4. Data types supported: U8/S8/QASYMM8/U16/S16/F16/U32/S32/F32.
[in] block_shape_x Block shape x value.
[in] block_shape_y Block shape y value.
[out] output Tensor output info. Data types supported: same as input
Returns
a status
Definition at line 55 of file CLBatchToSpaceLayer.cpp.
 {
     return CLBatchToSpaceLayerKernel::validate(input, block_shape_x, block_shape_y, output);
 }
References CLBatchToSpaceLayerKernel::validate().
The documentation for this class was generated from the following files:
arm_compute/runtime/CL/functions/CLBatchToSpaceLayer.h
src/runtime/CL/functions/CLBatchToSpaceLayer.cpp