Compute Library: JSONPrinter Class Reference
JSONPrinter Class Reference
Implementation of a Printer that produces JSON output.
#include <JSONPrinter.h>
Public Member Functions
void print_entry (const std::string &name, const std::string &value) override
Print an entry consisting of a (name, value) pair.
void print_global_header () override
Print global header.
void print_global_footer () override
Print global footer.
void print_run_header () override
Print header before running all tests.
void print_run_footer () override
Print footer after running all tests.
void print_test_header (const TestInfo &info) override
Print header before a test.
void print_test_footer () override
Print footer after a test.
void print_errors_header () override
Print header before errors.
void print_errors_footer () override
Print footer after errors.
void print_error (const std::exception &error, bool expected) override
Print test error.
void print_info (const std::string &info) override
Print test log info.
void print_measurements (const Profiler::MeasurementsMap &measurements) override
Print measurements for a test.
void print_list_tests (const std::vector< TestInfo > &infos) override
Print the list of all the tests.
Public Member Functions inherited from Printer
Printer ()=default
Default constructor.
Printer (std::ostream &stream)
Construct printer with given output stream.
Printer (const Printer &)=delete
Printer & operator= (const Printer &)=delete
Printer (Printer &&)=default
Printer & operator= (Printer &&)=default
virtual ~Printer ()=default
void print (const std::string &str)
Print given string.
void set_stream (std::ostream &stream)
Set the output stream.
Detailed Description
Implementation of a Printer that produces JSON output.
Definition at line 38 of file JSONPrinter.h.
Member Function Documentation
void print_entry (const std::string & name, const std::string & value) override virtual
Print an entry consisting of a (name, value) pair.
Parameters
[in] name Description of the value.
[in] value Value.
Implements Printer.
Definition at line 74 of file JSONPrinter.cpp.
 {
     print_separator(_first_entry);
     *_stream << R"(")" << name << R"(" : ")" << value << R"(")";
 }
void print_error (const std::exception & error, bool expected) override virtual
Print test error.
Parameters
[in] error Description of the error.
[in] expected Whether the error was expected or not.
Implements Printer.
Definition at line 155 of file JSONPrinter.cpp.
 {
     if(expected)
     {
         _expected_errors.emplace_back(error.what());
     }
     else
     {
         _errors.emplace_back(error.what());
     }
 }
void print_errors_footer () override virtual
Print footer after errors.
Implements Printer.
Definition at line 138 of file JSONPrinter.cpp.
 {
     print_separator(_first_test_entry);
     *_stream << R"("errors" : [)";
     print_strings(_errors.begin(), _errors.end());
     *_stream << "]";
     *_stream << R"(, "expected_errors" : [)";
     print_strings(_expected_errors.begin(), _expected_errors.end());
     *_stream << "]";
     *_stream << R"(, "infos" : [)";
     print_strings(_infos.begin(), _infos.end());
     *_stream << "]";
 }
void print_errors_header () override virtual
Print header before errors.
Implements Printer.
Definition at line 131 of file JSONPrinter.cpp.
 {
     _errors.clear();
     _expected_errors.clear();
     _infos.clear();
 }
void print_global_footer () override virtual
Print global footer.
Implements Printer.
Definition at line 86 of file JSONPrinter.cpp.
 {
     *_stream << "}\n";
 }
void print_global_header () override virtual
Print global header.
Implements Printer.
Definition at line 81 of file JSONPrinter.cpp.
 {
     *_stream << "{";
 }
void print_info (const std::string & info) override virtual
Print test log info.
Parameters
[in] info Description of the log.
Implements Printer.
Definition at line 167 of file JSONPrinter.cpp.
 {
     _infos.push_back(info);
 }
void print_list_tests (const std::vector< TestInfo > & infos) override virtual
Print the list of all the tests.
Parameters
[in] infos List of tests to print
Implements Printer.
Definition at line 116 of file JSONPrinter.cpp.
References arm_compute::test::validation::info().
 {
     *_stream << R"(, "list_tests" : {)";
     bool first = true;
     for(auto info : infos)
     {
         if(!first)
         {
             *_stream << ",";
         }
         *_stream << R"(")" << info.id << R"(" : { "name": ")" << info.name << R"(", "mode": ")" << info.mode << R"(", "status" : ")" << info.status << R"(" })";
         first = false;
     }
     *_stream << "}";
 }
void print_measurements (const Profiler::MeasurementsMap & measurements) override virtual
Print measurements for a test.
Parameters
[in] measurements Measurements as collected by a Profiler.
Implements Printer.
Definition at line 172 of file JSONPrinter.cpp.
References arm_compute::test::validation::a, accumulate(), arm_compute::test::validation::b, arm_compute::test::join(), caffe_data_extractor::str, and Measurement::value().
 {
     print_separator(_first_test_entry);
     *_stream << R"("measurements" : {)";
     for(auto i_it = measurements.cbegin(), i_end = measurements.cend(); i_it != i_end;)
     {
         *_stream << R"(")" << i_it->first << R"(" : {)";
         auto add_measurements = [](Measurement::Value a, const Measurement & b)
         {
             return a + b.value();
         };
         auto cmp_measurements = [](const Measurement & a, const Measurement & b)
         {
             return a.value() < b.value();
         };
         int        num_values    = i_it->second.size();
         const auto minmax_values = std::minmax_element(i_it->second.begin(), i_it->second.end(), cmp_measurements);
         Measurement::Value sum_values = std::accumulate(i_it->second.cbegin(), i_it->second.cend(), Measurement::Value(minmax_values.first->value().is_floating_point), add_measurements);
         if(num_values > 2)
         {
             sum_values -= minmax_values.first->value() + minmax_values.second->value();
             num_values -= 2;
         }
         auto measurement_to_string = [](const Measurement & measurement)
         {
             if(measurement.raw_data().size() == 1)
             {
                 return measurement.raw_data().front();
             }
             else
             {
                 std::stringstream str;
                 str << R"([")";
                 str << join(measurement.raw_data().begin(), measurement.raw_data().end(), R"(",")");
                 str << R"("])";
                 return str.str();
             }
         };
         *_stream << R"("avg" : )" << (sum_values / num_values) << ",";
         if(num_values > 1)
         {
             *_stream << R"("min" : )" << minmax_values.first->value() << ",";
             *_stream << R"("max" : )" << minmax_values.second->value() << ",";
         }
         *_stream << R"("raw" : [)" << join(i_it->second.begin(), i_it->second.end(), ",", measurement_to_string) << "],";
         *_stream << R"("unit" : ")" << minmax_values.first->unit() << R"(")";
         *_stream << "}";
         if(++i_it != i_end)
         {
             *_stream << ",";
         }
     }
     *_stream << "}";
 }
void print_run_footer () override virtual
Print footer after running all tests.
Implements Printer.
Definition at line 98 of file JSONPrinter.cpp.
 {
     *_stream << "}";
 }
void print_run_header () override virtual
Print header before running all tests.
Implements Printer.
Definition at line 91 of file JSONPrinter.cpp.
 {
     print_separator(_first_entry);
     *_stream << R"("tests" : {)";
 }
void print_test_footer () override virtual
Print footer after a test.
Implements Printer.
Definition at line 111 of file JSONPrinter.cpp.
 {
     *_stream << "}";
 }
void print_test_header (const TestInfo & info) override virtual
Print header before a test.
Parameters
[in] info Test info.
Implements Printer.
Definition at line 103 of file JSONPrinter.cpp.
References TestInfo::name.
 {
     print_separator(_first_test);
     _first_test_entry = true;
     *_stream << R"(")" << info.name << R"(" : {)";
 }
The documentation for this class was generated from the following files:
tests/framework/printers/JSONPrinter.h
tests/framework/printers/JSONPrinter.cpp