Compute Library: WindowIterator< L > Class Template Reference
WindowIterator< L > Class Template Reference
Iterate over a portion of a Window.
#include <WindowIterator.h>
Public Member Functions
WindowIterator (const Window &w, const Coordinates &start, const Coordinates &end, L &&lambda_function)
Construct a WindowIterator object.
template<typename M >
void iterate_3D (M &&on_new_row_size)
Iterate over the lowest 3 dimensions of the window.
template<typename M >
void iterate_2D (M &&on_new_row_size)
Iterate over the lowest 2 dimensions of the window.
void set_step (size_t dim, int step)
Change the step used for the iteration.
const Coordinates & end_position () const
Returns the coordinates in absolute coordinates of the end position.
Detailed Description
template<typename L>
class arm_compute::WindowIterator< L >
Iterate over a portion of a Window.
Definition at line 138 of file WindowIterator.h.
Constructor & Destructor Documentation
WindowIterator()
WindowIterator (const Window & w, const Coordinates & start, const Coordinates & end, L && lambda_function) inline
Construct a WindowIterator object.
Parameters
[in] w Window to use for the iteration
[in] start Where to start iterating from (In Window coordinates)
[in] end Where to stop iterating (In Window coordinates).
[in] lambda_function Lambda function to call for every iteration between start and end. (It will be called last for end - 1)
Definition at line 148 of file WindowIterator.h.
         : _lambda_function(std::move(lambda_function)),
           _position(convert_window_coord_to_position(w, start)),
           _end(convert_window_coord_to_position(w, end)),
           _w(w)
     {
     }
Member Function Documentation
end_position()
const Coordinates& end_position () const inline
Returns the coordinates in absolute coordinates of the end position.
Returns
End position coordinates.
Definition at line 201 of file WindowIterator.h.
     {
         return _end;
     }
iterate_2D()
void iterate_2D (M && on_new_row_size) inline
Iterate over the lowest 2 dimensions of the window.
Parameters
[in] on_new_row_size Callback to be called before lambda_function every time the width of the row processed changes.
Definition at line 180 of file WindowIterator.h.
     {
         iterate_2D_internal(on_new_row_size, _end.x(), _end.y());
     }
References Dimensions< T >::x(), and Dimensions< T >::y().
Referenced by WindowIterator< L >::iterate_3D().
iterate_3D()
void iterate_3D (M && on_new_row_size) inline
Iterate over the lowest 3 dimensions of the window.
Parameters
[in] on_new_row_size Callback to be called before lambda_function every time the width of the row processed changes.
Definition at line 160 of file WindowIterator.h.
     {
         while(_end.z() != _position.z())
         {
             PRINTF("New slice %d\n", _position.z());
             iterate_2D_internal(on_new_row_size, _w.x().end() - _w.x().step(), _w.y().end() - _w.y().step());
             _position[2] += _w.z().step();
             _position[1] = _w.y().start();
             _position[0] = _w.x().start();
         }
         // Left over:
         PRINTF("Left over slice\n");
         iterate_2D(on_new_row_size);
     }
References Window::Dimension::end(), WindowIterator< L >::iterate_2D(), PRINTF, Window::Dimension::start(), Window::Dimension::step(), Window::x(), Window::y(), Dimensions< T >::z(), and Window::z().
set_step()
void set_step (size_t dim, int step) inline
Change the step used for the iteration.
Note
Does not affect the start and end points.
Parameters
[in] dim Dimension to change
[in] step New step to use for the given dimension.
Definition at line 192 of file WindowIterator.h.
     {
         _w.set_dimension_step(dim, step);
     }
References Window::set_dimension_step(), and arm_compute::test::validation::step.
The documentation for this class was generated from the following file:
arm_compute/core/WindowIterator.h