Compute Library: PyramidInfo Class Reference
PyramidInfo Class Reference
Store the Pyramid's metadata.
#include <PyramidInfo.h>
Public Member Functions
PyramidInfo ()
Default constructor.
virtual ~PyramidInfo ()=default
Default destructor.
PyramidInfo (const PyramidInfo &)=default
Allow instances of this class to be copy constructed.
PyramidInfo & operator= (const PyramidInfo &)=default
Allow instances of this class to be copied.
PyramidInfo (PyramidInfo &&)=default
Allow instances of this class to be move constructed.
PyramidInfo & operator= (PyramidInfo &&)=default
Allow instances of this class to be moved.
PyramidInfo (size_t num_levels, float scale, size_t width, size_t height, Format format)
Create pyramid info for 2D tensors.
PyramidInfo (size_t num_levels, float scale, const TensorShape &tensor_shape, Format format)
Create pyramid info using TensorShape.
void init (size_t num_levels, float scale, size_t width, size_t height, Format format)
Initialize pyramid's metadata for 2D tensors.
void init (size_t num_levels, float scale, const TensorShape &tensor_shape, Format format)
Initialize pyramid's metadata using TensorShape.
size_t num_levels () const
Return the number of the pyramid levels.
size_t width () const
Return the width of the 0th level tensor.
size_t height () const
Return the height of the 0th level tensor.
const TensorShape & tensor_shape () const
Return the TensorShape of the o-th level tensor.
Format format () const
Return the image format of all tensor in the pyramid.
float scale () const
Return the scale factor of the pyramid.
Detailed Description
Store the Pyramid's metadata.
Definition at line 35 of file PyramidInfo.h.
Constructor & Destructor Documentation
PyramidInfo() [1/5]
PyramidInfo ()
Default constructor.
Definition at line 33 of file PyramidInfo.cpp.
     : _num_levels(0), _tensor_shape(), _format(Format::UNKNOWN), _scale(0.0f)
 {
 }
References arm_compute::UNKNOWN.
~PyramidInfo()
virtual ~PyramidInfo () virtual default
Default destructor.
PyramidInfo() [2/5]
PyramidInfo (const PyramidInfo &) default
Allow instances of this class to be copy constructed.
PyramidInfo() [3/5]
PyramidInfo (PyramidInfo &&) default
Allow instances of this class to be move constructed.
PyramidInfo() [4/5]
PyramidInfo (size_t num_levels, float scale, size_t width, size_t height, Format format)
Create pyramid info for 2D tensors.
Parameters
[in] num_levels The number of pyramid levels. This is required to be a non-zero value
[in] scale Used to indicate the scale between the pyramid levels. This is required to be a non-zero positive value.
[in] width The width of the 2D tensor at 0th pyramid level
[in] height The height of the 2D tensor at 0th pyramid level
[in] format The format of all 2D tensors in the pyramid NV12, NV21, IYUV, UYVY and YUYV formats are not supported.
Definition at line 38 of file PyramidInfo.cpp.
     : PyramidInfo()
 {
     init(num_levels, scale, width, height, format);
 }
References PyramidInfo::format(), PyramidInfo::height(), PyramidInfo::init(), PyramidInfo::num_levels(), PyramidInfo::scale(), and PyramidInfo::width().
PyramidInfo() [5/5]
PyramidInfo (size_t num_levels, float scale, const TensorShape & tensor_shape, Format format)
Create pyramid info using TensorShape.
Parameters
[in] num_levels The number of pyramid levels. This is required to be a non-zero value
[in] scale Used to indicate the scale between the pyramid levels. This is required to be a non-zero positive value.
[in] tensor_shape It specifies the size for each dimension of the tensor 0th pyramid level in number of elements
[in] format The format of all tensors in the pyramid
Definition at line 44 of file PyramidInfo.cpp.
     : PyramidInfo()
 {
     init(num_levels, scale, tensor_shape, format);
 }
References PyramidInfo::format(), PyramidInfo::init(), PyramidInfo::num_levels(), PyramidInfo::scale(), and PyramidInfo::tensor_shape().
Member Function Documentation
format()
Format format () const
Return the image format of all tensor in the pyramid.
Returns
The image format
Definition at line 97 of file PyramidInfo.cpp.
 {
     return _format;
 }
Referenced by PyramidInfo::init(), and PyramidInfo::PyramidInfo().
height()
size_t height () const
Return the height of the 0th level tensor.
Returns
The height of the 0th level tensor
Definition at line 87 of file PyramidInfo.cpp.
 {
     return _tensor_shape.y();
 }
References Dimensions< T >::y().
Referenced by CLLaplacianPyramid::configure(), NELaplacianPyramid::configure(), NEOpticalFlow::configure(), CLGaussianPyramidHalf::configure(), NEGaussianPyramidHalf::configure(), CLOpticalFlow::configure(), CLGaussianPyramidOrb::configure(), NEGaussianPyramidOrb::configure(), PyramidInfo::init(), and PyramidInfo::PyramidInfo().
init() [1/2]
void init (size_t num_levels, float scale, size_t width, size_t height, Format format)
Initialize pyramid's metadata for 2D tensors.
Parameters
[in] num_levels The number of pyramid levels. This is required to be a non-zero value
[in] scale Used to indicate the scale between the pyramid levels. This is required to be a non-zero positive value.
[in] width The width of the 2D tensor at 0th pyramid level
[in] height The height of the 2D tensor at 0th pyramid level
[in] format The format of all 2D tensors in the pyramid NV12, NV21, IYUV, UYVY and YUYV formats are not supported.
Definition at line 50 of file PyramidInfo.cpp.
 {
     init(num_levels, scale, TensorShape(width, height), format);
 }
References PyramidInfo::format(), PyramidInfo::height(), PyramidInfo::num_levels(), PyramidInfo::scale(), and PyramidInfo::width().
Referenced by CLLaplacianPyramid::configure(), NELaplacianPyramid::configure(), CLLaplacianReconstruct::configure(), NELaplacianReconstruct::configure(), CLGaussianPyramidOrb::configure(), NEGaussianPyramidOrb::configure(), and PyramidInfo::PyramidInfo().
init() [2/2]
void init (size_t num_levels, float scale, const TensorShape & tensor_shape, Format format)
Initialize pyramid's metadata using TensorShape.
Parameters
[in] num_levels The number of pyramid levels. This is required to be a non-zero value
[in] scale Used to indicate the scale between the pyramid levels. This is required to be a non-zero positive value.
[in] tensor_shape It specifies the size for each dimension of the tensor 0th pyramid level in number of elements
[in] format The format of all tensors in the pyramid
Definition at line 55 of file PyramidInfo.cpp.
 {
     ARM_COMPUTE_ERROR_ON(0 == num_levels);
     ARM_COMPUTE_ERROR_ON(0.0f == scale);
     ARM_COMPUTE_ERROR_ON(0 == tensor_shape.x());
     ARM_COMPUTE_ERROR_ON(0 == tensor_shape.y());
     ARM_COMPUTE_ERROR_ON(Format::IYUV == format);
     ARM_COMPUTE_ERROR_ON(Format::NV12 == format);
     ARM_COMPUTE_ERROR_ON(Format::NV21 == format);
     ARM_COMPUTE_ERROR_ON(Format::UYVY422 == format);
     ARM_COMPUTE_ERROR_ON(Format::YUV444 == format);
     ARM_COMPUTE_ERROR_ON(Format::YUYV422 == format);
     ARM_COMPUTE_ERROR_ON_MSG(0 != _num_levels, "PyramidInfo already initialized");
     ARM_COMPUTE_ERROR_ON(0 == (tensor_shape.x() * pow(scale, num_levels)));
     ARM_COMPUTE_ERROR_ON(0 == (tensor_shape.y() * pow(scale, num_levels)));
     _num_levels   = num_levels;
     _format       = format;
     _scale        = scale;
     _tensor_shape = tensor_shape;
 }
References ARM_COMPUTE_ERROR_ON, ARM_COMPUTE_ERROR_ON_MSG, PyramidInfo::format(), arm_compute::IYUV, PyramidInfo::num_levels(), arm_compute::NV12, arm_compute::NV21, PyramidInfo::scale(), PyramidInfo::tensor_shape(), arm_compute::UYVY422, Dimensions< T >::x(), Dimensions< T >::y(), arm_compute::YUV444, and arm_compute::YUYV422.
num_levels()
size_t num_levels () const
Return the number of the pyramid levels.
Returns
The number of the pyramid levels
Definition at line 77 of file PyramidInfo.cpp.
 {
     return _num_levels;
 }
Referenced by Pyramid::allocate(), CLPyramid::allocate(), CLLaplacianPyramid::configure(), NELaplacianPyramid::configure(), CLLaplacianReconstruct::configure(), NELaplacianReconstruct::configure(), NEOpticalFlow::configure(), CLGaussianPyramidHalf::configure(), CLOpticalFlow::configure(), NEGaussianPyramidHalf::configure(), CLGaussianPyramidOrb::configure(), NEGaussianPyramidOrb::configure(), arm_compute::test::validation::DATA_TEST_CASE(), Pyramid::get_pyramid_level(), CLPyramid::get_pyramid_level(), PyramidInfo::init(), PyramidInfo::PyramidInfo(), CLLaplacianReconstruct::run(), and NELaplacianReconstruct::run().
operator=() [1/2]
PyramidInfo& operator= (const PyramidInfo &) default
Allow instances of this class to be copied.
operator=() [2/2]
PyramidInfo& operator= (PyramidInfo &&) default
Allow instances of this class to be moved.
scale()
float scale () const
Return the scale factor of the pyramid.
Returns
Return the scale factor
Definition at line 102 of file PyramidInfo.cpp.
 {
     return _scale;
 }
Referenced by NEOpticalFlow::configure(), CLGaussianPyramidHalf::configure(), CLOpticalFlow::configure(), NEGaussianPyramidHalf::configure(), CLGaussianPyramidOrb::configure(), NEGaussianPyramidOrb::configure(), PyramidInfo::init(), and PyramidInfo::PyramidInfo().
tensor_shape()
const TensorShape & tensor_shape () const
Return the TensorShape of the o-th level tensor.
Returns
Definition at line 92 of file PyramidInfo.cpp.
 {
     return _tensor_shape;
 }
Referenced by CLLaplacianPyramid::configure(), NELaplacianPyramid::configure(), CLGaussianPyramidHalf::configure(), NEGaussianPyramidHalf::configure(), CLGaussianPyramidOrb::configure(), NEGaussianPyramidOrb::configure(), PyramidInfo::init(), and PyramidInfo::PyramidInfo().
width()
size_t width () const
Return the width of the 0th level tensor.
Returns
The width of the 0th level tensor
Definition at line 82 of file PyramidInfo.cpp.
 {
     return _tensor_shape.x();
 }
References Dimensions< T >::x().
Referenced by CLLaplacianPyramid::configure(), NELaplacianPyramid::configure(), NEOpticalFlow::configure(), CLGaussianPyramidHalf::configure(), NEGaussianPyramidHalf::configure(), CLOpticalFlow::configure(), CLGaussianPyramidOrb::configure(), NEGaussianPyramidOrb::configure(), PyramidInfo::init(), and PyramidInfo::PyramidInfo().
The documentation for this class was generated from the following files:
arm_compute/core/PyramidInfo.h
src/core/PyramidInfo.cpp