Compute Library: NECropResize Class Reference
NECropResize Class Reference
Function to perform cropping and resizing.
#include <NECropResize.h>
Public Member Functions
NECropResize ()
Default constructor.
NECropResize (const NECropResize &)=delete
Prevent instances of this class from being copied (As this class contains pointers)
NECropResize & operator= (const NECropResize &)=delete
Prevent instances of this class from being copied (As this class contains pointers)
NECropResize (NECropResize &&)=default
Allow instances of this class to be moved.
NECropResize & operator= (NECropResize &&)=default
Allow instances of this class to be moved.
virtual ~NECropResize ()=default
Default destructor.
void configure (const ITensor *input, const ITensor *boxes, const ITensor *box_ind, ITensor *output, Coordinates2D crop_size, InterpolationPolicy method=InterpolationPolicy::BILINEAR, float extrapolation_value=0)
Configure kernel.
void run () override
Run the kernels contained in the function.
Public Member Functions inherited from IFunction
virtual ~IFunction ()=default
Destructor.
virtual void prepare ()
Prepare the function for executing.
Static Public Member Functions
static Status validate (const ITensorInfo *input, const ITensorInfo *boxes, const ITensorInfo *box_ind, const ITensorInfo *output, Coordinates2D crop_size, InterpolationPolicy method, float extrapolation_value)
Static function to check if given info will lead to a valid configuration of NESlice.
Data Fields
ITensor * _output
size_t _num_boxes
InterpolationPolicy _method
float _extrapolation_value
std::vector< std::unique_ptr< NECropKernel > > _crop
std::vector< std::unique_ptr< NEScale > > _scale
std::vector< std::unique_ptr< Tensor > > _crop_results
std::vector< std::unique_ptr< Tensor > > _scaled_results
Detailed Description
Function to perform cropping and resizing.
Definition at line 39 of file NECropResize.h.
Constructor & Destructor Documentation
NECropResize() [1/3]
NECropResize ()
Default constructor.
Definition at line 32 of file NECropResize.cpp.
     : _output(nullptr), _num_boxes(0), _method(), _extrapolation_value(0), _crop(), _scale(), _crop_results(), _scaled_results()
 {
 }
NECropResize() [2/3]
NECropResize (const NECropResize &) delete
Prevent instances of this class from being copied (As this class contains pointers)
NECropResize() [3/3]
NECropResize (NECropResize &&) default
Allow instances of this class to be moved.
~NECropResize()
virtual ~NECropResize () virtual default
Default destructor.
Member Function Documentation
configure()
void configure (const ITensor * input, const ITensor * boxes, const ITensor * box_ind, ITensor * output, Coordinates2D crop_size, InterpolationPolicy method = InterpolationPolicy::BILINEAR, float extrapolation_value = 0)
Configure kernel.
Note
Supported tensor rank: up to 4
Box indices may be outside of the bounds, in which case extrapolation_value is used.
Start and end indices of boxes are inclusive.
Parameters
[in] input Source tensor containing N batches of 3D images to be cropped. Data type supported: U16/S16/U32/S32/F16/F32
[in] boxes Tensor containing the boxes used to crop the images. Data type supported: F32
[in] box_ind One dimensional tensor containing the batch index of the 3D image in input that the corresponding box in boxes will be applied to. Data type supported: F32
[out] output Destination tensor containing a cropped and resized image for each box in boxes. Data type supported: F32
[in] crop_size The dimensions that each cropped image will be resized to.
[in] method The policy to be used when resizing image. Default is bilinear.
[in] extrapolation_value Value to be used for values outside of the image for cropping and resizing. Default is 0.
Definition at line 54 of file NECropResize.cpp.
 {
     ARM_COMPUTE_ERROR_ON_NULLPTR(input, output);
     ARM_COMPUTE_ERROR_THROW_ON(NECropResize::validate(input->info(), boxes->info(), box_ind->info(), output->info(), crop_size, method, extrapolation_value));
     _num_boxes = boxes->info()->tensor_shape()[1];
     TensorShape out_shape(input->info()->tensor_shape()[0], crop_size.x, crop_size.y);
     _output              = output;
     _method              = method;
     _extrapolation_value = extrapolation_value;
     // For each crop box:
     // - A crop kernel is used to extract the initial cropped image as specified by boxes[i] from the 3D image input[box_ind[i]].
     // - A tensor is required to hold this initial cropped image.
     // - A scale function is used to resize the cropped image to the size specified by crop_size.
     // - A tensor is required to hold the final scaled image before it is copied into the 4D output
     //   that will hold all final cropped and scaled 3D images.
     _crop.reserve(_num_boxes);
     _crop_results.reserve(_num_boxes);
     _scaled_results.reserve(_num_boxes);
     _scale.reserve(_num_boxes);
     for(unsigned int i = 0; i < _num_boxes; ++i)
     {
         auto       crop_tensor = support::cpp14::make_unique<Tensor>();
         TensorInfo crop_result_info(1, DataType::F32);
         crop_result_info.set_data_layout(DataLayout::NHWC);
         crop_tensor->allocator()->init(crop_result_info);
         auto       scale_tensor = support::cpp14::make_unique<Tensor>();
         TensorInfo scaled_result_info(out_shape, 1, DataType::F32);
         scaled_result_info.set_data_layout(DataLayout::NHWC);
         scale_tensor->allocator()->init(scaled_result_info);
         auto crop_kernel  = support::cpp14::make_unique<NECropKernel>();
         auto scale_kernel = support::cpp14::make_unique<NEScale>();
         crop_kernel->configure(input, boxes, box_ind, crop_tensor.get(), i, _extrapolation_value);
         _crop.emplace_back(std::move(crop_kernel));
         _scaled_results.emplace_back(std::move(scale_tensor));
         _crop_results.emplace_back(std::move(crop_tensor));
         _scale.emplace_back(std::move(scale_kernel));
     }
 }
References NECropResize::_crop, NECropResize::_crop_results, NECropResize::_extrapolation_value, NECropResize::_method, NECropResize::_num_boxes, NECropResize::_output, NECropResize::_scale, NECropResize::_scaled_results, ARM_COMPUTE_ERROR_ON_NULLPTR, ARM_COMPUTE_ERROR_THROW_ON, arm_compute::F32, ITensor::info(), arm_compute::NHWC, TensorInfo::set_data_layout(), ITensorInfo::tensor_shape(), NECropResize::validate(), Coordinates2D::x, and Coordinates2D::y.
operator=() [1/2]
NECropResize& operator= (const NECropResize &) delete
Prevent instances of this class from being copied (As this class contains pointers)
operator=() [2/2]
NECropResize& operator= (NECropResize &&) default
Allow instances of this class to be moved.
run()
void run () override virtual
Run the kernels contained in the function.
For NEON kernels:
Multi-threading is used for the kernels which are parallelisable.
By default std::thread::hardware_concurrency() threads are used.
Note
CPPScheduler::set_num_threads() can be used to manually set the number of threads
For OpenCL kernels:
All the kernels are enqueued on the queue associated with CLScheduler.
The queue is then flushed.
Note
The function will not block until the kernels are executed. It is the user's responsibility to wait.
Will call prepare() on first run if hasn't been done
Implements IFunction.
Definition at line 101 of file NECropResize.cpp.
 {
     ARM_COMPUTE_ERROR_ON_MSG(_output == nullptr, "Unconfigured function");
     for(unsigned int i = 0; i < _num_boxes; ++i)
     {
         // Size of the crop box in _boxes and thus the shape of _crop_results[i]
         // may not be known until run-time and so the kernels cannot be configured until then.
         _crop[i]->configure_output_shape();
         _crop_results[i]->allocator()->allocate();
         NEScheduler::get().schedule(_crop[i].get(), Window::DimZ);
         // Scale the cropped image.
         _scale[i]->configure(_crop_results[i].get(), _scaled_results[i].get(), _method, BorderMode::CONSTANT, PixelValue(_extrapolation_value), SamplingPolicy::TOP_LEFT, false);
         _scaled_results[i]->allocator()->allocate();
         _scale[i]->run();
         // Copy scaled image into output.
         std::copy_n(_scaled_results[i]->buffer(), _scaled_results[i]->info()->total_size(), _output->ptr_to_element(Coordinates(0, 0, 0, i)));
     }
 }
References NECropResize::_crop, NECropResize::_crop_results, NECropResize::_extrapolation_value, NECropResize::_method, NECropResize::_num_boxes, NECropResize::_output, NECropResize::_scale, NECropResize::_scaled_results, ARM_COMPUTE_ERROR_ON_MSG, arm_compute::CONSTANT, Window::DimZ, Scheduler::get(), arm_compute::test::validation::info, ITensor::ptr_to_element(), IScheduler::schedule(), and arm_compute::TOP_LEFT.
validate()
Status validate (const ITensorInfo * input, const ITensorInfo * boxes, const ITensorInfo * box_ind, const ITensorInfo * output, Coordinates2D crop_size, InterpolationPolicy method, float extrapolation_value) static
Static function to check if given info will lead to a valid configuration of NESlice.
Note
Supported tensor rank: up to 4
Box indices may be outside of the bounds, in which case extrapolation_value is used.
Start and end indices of boxes are inclusive.
Parameters
[in] input Source tensor containing N batches of 3D images to be cropped. Data type supported: U16/S16/U32/S32/F16/F32
[in] boxes Tensor info for the tensor containing the boxes used to crop the images. Data type supported: F32
[in] box_ind Tensor info for the one dimensional tensor containing the batch index of the 3D image in input that the corresponding box in boxes will be applied to. Data type supported: F32
[in] output Tensor info for the destination tensor containing a cropped and resized image for each box in boxes. Data type supported: F32
[in] crop_size The dimensions that each cropped image will be resized to.
[in] method The policy to be used when resizing image. Default is bilinear.
[in] extrapolation_value Value to be used for values outside of the image for cropping and resizing. Default is 0.
Returns
A status
Definition at line 37 of file NECropResize.cpp.
 {
     ARM_COMPUTE_RETURN_ERROR_ON(crop_size.x <= 0 || crop_size.y <= 0);
     ARM_COMPUTE_RETURN_ERROR_ON(method == InterpolationPolicy::AREA);
     TensorInfo temp_info;
     ARM_COMPUTE_RETURN_ON_ERROR(NECropKernel::validate(input->clone().get(), boxes->clone().get(), box_ind->clone().get(), &temp_info, boxes->tensor_shape()[1] - 1, extrapolation_value));
     if(output->total_size() > 0)
     {
         ARM_COMPUTE_RETURN_ERROR_ON_DATA_TYPE_NOT_IN(output, DataType::F32);
         ARM_COMPUTE_RETURN_ERROR_ON_MISMATCHING_DATA_LAYOUT(input, output);
         TensorShape out_shape(input->tensor_shape()[0], crop_size.x, crop_size.y, boxes->tensor_shape()[1]);
         ARM_COMPUTE_RETURN_ERROR_ON_MISMATCHING_DIMENSIONS(output->tensor_shape(), out_shape);
     }
     return Status{};
 }
References arm_compute::AREA, ARM_COMPUTE_RETURN_ERROR_ON, ARM_COMPUTE_RETURN_ERROR_ON_DATA_TYPE_NOT_IN, ARM_COMPUTE_RETURN_ERROR_ON_MISMATCHING_DATA_LAYOUT, ARM_COMPUTE_RETURN_ERROR_ON_MISMATCHING_DIMENSIONS, ARM_COMPUTE_RETURN_ON_ERROR, ICloneable< T >::clone(), arm_compute::F32, ITensorInfo::tensor_shape(), ITensorInfo::total_size(), NECropKernel::validate(), Coordinates2D::x, and Coordinates2D::y.
Referenced by NECropResize::configure().
Field Documentation
_crop
std::vector<std::unique_ptr<NECropKernel> > _crop
Definition at line 101 of file NECropResize.h.
Referenced by NECropResize::configure(), and NECropResize::run().
_crop_results
std::vector<std::unique_ptr<Tensor> > _crop_results
Definition at line 103 of file NECropResize.h.
Referenced by NECropResize::configure(), and NECropResize::run().
_extrapolation_value
float _extrapolation_value
Definition at line 99 of file NECropResize.h.
Referenced by NECropResize::configure(), and NECropResize::run().
_method
InterpolationPolicy _method
Definition at line 98 of file NECropResize.h.
Referenced by NECropResize::configure(), and NECropResize::run().
_num_boxes
size_t _num_boxes
Definition at line 97 of file NECropResize.h.
Referenced by NECropResize::configure(), and NECropResize::run().
_output
ITensor* _output
Definition at line 96 of file NECropResize.h.
Referenced by NECropResize::configure(), and NECropResize::run().
_scale
std::vector<std::unique_ptr<NEScale> > _scale
Definition at line 102 of file NECropResize.h.
Referenced by NECropResize::configure(), and NECropResize::run().
_scaled_results
std::vector<std::unique_ptr<Tensor> > _scaled_results
Definition at line 104 of file NECropResize.h.
Referenced by NECropResize::configure(), and NECropResize::run().
The documentation for this class was generated from the following files:
arm_compute/runtime/NEON/functions/NECropResize.h
src/runtime/NEON/functions/NECropResize.cpp