Compute Library: CLHarrisCorners Class Reference
CLHarrisCorners Class Reference
Basic function to execute harris corners detection.
#include <CLHarrisCorners.h>
Public Member Functions
CLHarrisCorners (std::shared_ptr< IMemoryManager > memory_manager=nullptr)
Constructor.
CLHarrisCorners (const CLHarrisCorners &)=delete
Prevent instances of this class from being copied (As this class contains pointers)
const CLHarrisCorners & operator= (const CLHarrisCorners &)=delete
Prevent instances of this class from being copied (As this class contains pointers)
void configure (ICLImage *input, float threshold, float min_dist, float sensitivity, int32_t gradient_size, int32_t block_size, ICLKeyPointArray *corners, BorderMode border_mode, uint8_t constant_border_value=0, bool use_fp16=false)
Initialize the function's source, destination, conv and border_mode.
void run () override
Run the kernels contained in the function.
Public Member Functions inherited from IFunction
virtual ~IFunction ()=default
Destructor.
virtual void prepare ()
Prepare the function for executing.
Detailed Description
Basic function to execute harris corners detection.
This function calls the following CL and NEON kernels and functions:
Note
Requires CPU support for the kernels: CPPCornerCandidatesKernel and CPPSortEuclideanDistanceKernel.
CLSobel3x3 (if gradient_size == 3) or
CLSobel5x5 (if gradient_size == 5) or
CLSobel7x7 (if gradient_size == 7)
CLFillBorderKernel
CLHarrisScoreKernel
CLNonMaximaSuppression3x3
CPPCornerCandidatesKernel
CPPSortEuclideanDistanceKernel
Definition at line 60 of file CLHarrisCorners.h.
Constructor & Destructor Documentation
CLHarrisCorners() [1/2]
CLHarrisCorners (std::shared_ptr< IMemoryManager > memory_manager = nullptr)
Constructor.
Definition at line 45 of file CLHarrisCorners.cpp.
     : _memory_group(std::move(memory_manager)),
       _sobel(nullptr),
       _harris_score(),
       _non_max_suppr(),
       _candidates(),
       _sort_euclidean(),
       _border_gx(),
       _border_gy(),
       _gx(),
       _gy(),
       _score(),
       _nonmax(),
       _corners_list(),
       _num_corner_candidates(0),
       _corners(nullptr)
 {
 }
CLHarrisCorners() [2/2]
CLHarrisCorners (const CLHarrisCorners &) delete
Prevent instances of this class from being copied (As this class contains pointers)
Member Function Documentation
configure()
void configure (ICLImage * input, float threshold, float min_dist, float sensitivity, int32_t gradient_size, int32_t block_size, ICLKeyPointArray * corners, BorderMode border_mode, uint8_t constant_border_value = 0, bool use_fp16 = false)
Initialize the function's source, destination, conv and border_mode.
Parameters
[in,out] input Source image. Data types supported: U8. (Written to only for border_mode != UNDEFINED)
[in] threshold Minimum threshold with which to eliminate Harris Corner scores (computed using the normalized Sobel kernel).
[in] min_dist Radial Euclidean distance for the euclidean distance stage.
[in] sensitivity Sensitivity threshold k from the Harris-Stephens equation
[in] gradient_size The gradient window size to use on the input. The implementation supports 3, 5, and 7
[in] block_size The block window size used to compute the Harris Corner score. The implementation supports 3, 5, and 7.
[out] corners Array of keypoints to store the results.
[in] border_mode Border mode to use
[in] constant_border_value (Optional) Constant value to use for borders if border_mode is set to CONSTANT.
[in] use_fp16 (Optional) If true the FP16 kernels will be used. If false F32 kernels are used.
Definition at line 64 of file CLHarrisCorners.cpp.
 {
     ARM_COMPUTE_UNUSED(use_fp16); //TODO(COMPMID-772): Add half float support
     ARM_COMPUTE_ERROR_ON_TENSOR_NOT_2D(input);
     ARM_COMPUTE_ERROR_ON_DATA_TYPE_CHANNEL_NOT_IN(input, 1, DataType::U8);
     ARM_COMPUTE_ERROR_ON(!(block_size == 3 || block_size == 5 || block_size == 7));
     ARM_COMPUTE_ERROR_ON(nullptr == corners);
     _corners = corners;
     const TensorShape shape = input->info()->tensor_shape();
     const DataType    dt    = (gradient_size < 7) ? DataType::S16 : DataType::S32;
     TensorInfo        tensor_info(shape, 1, dt);
     _gx.allocator()->init(tensor_info);
     _gy.allocator()->init(tensor_info);
     TensorInfo info_f32(shape, 1, DataType::F32);
     _score.allocator()->init(info_f32);
     _nonmax.allocator()->init(info_f32);
     _corners_list.resize(shape.x() * shape.y());
     // Manage intermediate buffers
     _memory_group.manage(&_gx);
     _memory_group.manage(&_gy);
     /* Set/init Sobel kernel accordingly with gradient_size */
     switch(gradient_size)
     {
         case 3:
         {
             auto k = arm_compute::support::cpp14::make_unique<CLSobel3x3>();
             k->configure(input, &_gx, &_gy, border_mode, constant_border_value);
             _sobel = std::move(k);
             break;
         }
         case 5:
         {
             auto k = arm_compute::support::cpp14::make_unique<CLSobel5x5>();
             k->configure(input, &_gx, &_gy, border_mode, constant_border_value);
             _sobel = std::move(k);
             break;
         }
         case 7:
         {
             auto k = arm_compute::support::cpp14::make_unique<CLSobel7x7>();
             k->configure(input, &_gx, &_gy, border_mode, constant_border_value);
             _sobel = std::move(k);
             break;
         }
         default:
             ARM_COMPUTE_ERROR("Gradient size not implemented");
     }
     // Normalization factor
     const float norm_factor               = 1.0f / (255.0f * pow(4.0f, gradient_size / 2) * block_size);
     const float pow4_normalization_factor = pow(norm_factor, 4);
     // Manage intermediate buffers
     _memory_group.manage(&_score);
     // Set/init Harris Score kernel accordingly with block_size
     _harris_score.configure(&_gx, &_gy, &_score, block_size, pow4_normalization_factor, threshold, sensitivity, border_mode == BorderMode::UNDEFINED);
     // Configure border filling using harris score kernel's block size
     _border_gx.configure(&_gx, _harris_score.border_size(), border_mode, PixelValue(constant_border_value));
     _border_gy.configure(&_gy, _harris_score.border_size(), border_mode, PixelValue(constant_border_value));
     // Allocate intermediate buffers
     _gx.allocator()->allocate();
     _gy.allocator()->allocate();
     // Manage intermediate buffers
     _memory_group.manage(&_nonmax);
     // Init non-maxima suppression function
     _non_max_suppr.configure(&_score, &_nonmax, border_mode);
     // Allocate intermediate buffers
     _score.allocator()->allocate();
     // Init corner candidates kernel
     _candidates.configure(&_nonmax, _corners_list.data(), &_num_corner_candidates);
     // Allocate intermediate buffers
     _nonmax.allocator()->allocate();
     // Init euclidean distance
     _sort_euclidean.configure(_corners_list.data(), _corners, &_num_corner_candidates, min_dist);
 }
References CLTensorAllocator::allocate(), CLTensor::allocator(), ARM_COMPUTE_ERROR, ARM_COMPUTE_ERROR_ON, ARM_COMPUTE_ERROR_ON_DATA_TYPE_CHANNEL_NOT_IN, ARM_COMPUTE_ERROR_ON_TENSOR_NOT_2D, ARM_COMPUTE_UNUSED, arm_compute::test::validation::border_mode, CLHarrisScoreKernel::border_size(), CLNonMaximaSuppression3x3::configure(), CLFillBorderKernel::configure(), CPPSortEuclideanDistanceKernel::configure(), CLHarrisScoreKernel::configure(), CPPCornerCandidatesKernel::configure(), arm_compute::F32, ITensor::info(), ITensorAllocator::init(), MemoryGroupBase< TensorType >::manage(), arm_compute::S16, arm_compute::S32, arm_compute::test::validation::shape, ITensorInfo::tensor_shape(), arm_compute::test::validation::reference::threshold(), arm_compute::U8, and arm_compute::UNDEFINED.
Referenced by arm_compute::test::validation::DATA_TEST_CASE().
operator=()
const CLHarrisCorners& operator= (const CLHarrisCorners &) delete
Prevent instances of this class from being copied (As this class contains pointers)
run()
void run () override virtual
Run the kernels contained in the function.
For NEON kernels:
Multi-threading is used for the kernels which are parallelisable.
By default std::thread::hardware_concurrency() threads are used.
Note
CPPScheduler::set_num_threads() can be used to manually set the number of threads
For OpenCL kernels:
All the kernels are enqueued on the queue associated with CLScheduler.
The queue is then flushed.
Note
The function will not block until the kernels are executed. It is the user's responsibility to wait.
Will call prepare() on first run if hasn't been done
Implements IFunction.
Definition at line 158 of file CLHarrisCorners.cpp.
 {
     ARM_COMPUTE_ERROR_ON_MSG(_sobel == nullptr, "Unconfigured function");
     MemoryGroupResourceScope scope_mg(_memory_group);
     // Init to 0 number of corner candidates
     _num_corner_candidates = 0;
     // Run Sobel kernel
     _sobel->run();
     // Fill border before harris score kernel
     CLScheduler::get().enqueue(_border_gx, false);
     CLScheduler::get().enqueue(_border_gy, false);
     // Run harris score kernel
     CLScheduler::get().enqueue(_harris_score, false);
     // Run non-maxima suppression
     _non_max_suppr.run();
     // Run corner candidate kernel
     _nonmax.map(true);
     Scheduler::get().schedule(&_candidates, Window::DimY);
     _nonmax.unmap();
     _corners->map(CLScheduler::get().queue(), true);
     Scheduler::get().schedule(&_sort_euclidean, Window::DimY);
     _corners->unmap(CLScheduler::get().queue());
 }
References ARM_COMPUTE_ERROR_ON_MSG, Window::DimY, CLScheduler::enqueue(), Scheduler::get(), CLScheduler::get(), CLTensor::map(), ICLArray< T >::map(), ICLSimpleFunction::run(), IScheduler::schedule(), CLTensor::unmap(), and ICLArray< T >::unmap().
The documentation for this class was generated from the following files:
arm_compute/runtime/CL/functions/CLHarrisCorners.h
src/runtime/CL/functions/CLHarrisCorners.cpp