Compute Library: DeconvolutionValidationFixture< TensorType, AccessorType, FunctionType, T, kernel_size_x, kernel_size_y > Class Template Reference
DeconvolutionValidationFixture< TensorType, AccessorType, FunctionType, T, kernel_size_x, kernel_size_y > Class Template Reference
#include <DeconvolutionLayerFixture.h>
Public Member Functions
template<typename... >
void setup (TensorShape input_shape, unsigned int sx, unsigned int sy, unsigned int padx, unsigned int pady, unsigned int inner_border_right, unsigned int inner_border_top, unsigned int num_kernels, DataType data_type)
Public Member Functions inherited from DeconvolutionLayerFixtureBase< TensorType, AccessorType, FunctionType, T >
template<typename... >
void setup (TensorShape input_shape, TensorShape weights_shape, TensorShape bias_shape, TensorShape output_shape, PadStrideInfo info, const std::pair< unsigned int, unsigned int > &inner_border, DataType data_type, int fractional_bits)
Public Member Functions inherited from Fixture
void setup ()
Setup function.
void teardown ()
Teardown function.
Detailed Description
template<typename TensorType, typename AccessorType, typename FunctionType, typename T, unsigned int kernel_size_x, unsigned int kernel_size_y>
class arm_compute::test::validation::DeconvolutionValidationFixture< TensorType, AccessorType, FunctionType, T, kernel_size_x, kernel_size_y >
Definition at line 137 of file DeconvolutionLayerFixture.h.
Member Function Documentation
void setup (TensorShape input_shape, unsigned int sx, unsigned int sy, unsigned int padx, unsigned int pady, unsigned int inner_border_right, unsigned int inner_border_top, unsigned int num_kernels, DataType data_type) inline
Definition at line 141 of file DeconvolutionLayerFixture.h.
References ARM_COMPUTE_ERROR_ON_MSG, arm_compute::CEIL, arm_compute::deconvolution_output_dimensions(), arm_compute::deconvolution_output_shape(), arm_compute::test::validation::info(), arm_compute::test::validation::output_shape, Fixture::setup(), Dimensions< T >::x(), Dimensions< T >::y(), and Dimensions< T >::z().
     {
         ARM_COMPUTE_ERROR_ON_MSG(kernel_size_x != kernel_size_y, "Only square kernels supported");
         const TensorShape   weights_shape(kernel_size_x, kernel_size_y, input_shape.z(), num_kernels);
         const TensorShape   bias_shape(num_kernels);
         const PadStrideInfo info(sx, sy, padx, pady, DimensionRoundingType::CEIL);
         const std::pair<unsigned int, unsigned int> inner_border(inner_border_right, inner_border_top);
         auto        out_dim      = deconvolution_output_dimensions(input_shape.x(), input_shape.y(), kernel_size_x, kernel_size_y, padx, pady, inner_border.first, inner_border.second, sx, sy);
         TensorShape output_shape = deconvolution_output_shape(out_dim, input_shape, weights_shape);
         DeconvolutionLayerFixtureBase<TensorType, AccessorType, FunctionType, T>::setup(input_shape, weights_shape, bias_shape, output_shape, info, inner_border, data_type, 0);
     }
The documentation for this class was generated from the following file:
tests/validation/fixtures/DeconvolutionLayerFixture.h