Compute Library: GCPoolingLayer Class Reference
GCPoolingLayer Class Reference
Basic function to simulate a pooling layer with the specified pooling operation.
#include <GCPoolingLayer.h>
Public Member Functions
GCPoolingLayer ()
void configure (IGCTensor *input, IGCTensor *output, const PoolingLayerInfo &pool_info)
Set the input and output tensors.
void run () override final
Run the kernels contained in the function.
Public Member Functions inherited from IFunction
virtual ~IFunction ()=default
Destructor.
virtual void prepare ()
Prepare the function for executing.
Static Public Member Functions
static Status validate (const ITensorInfo *input, const ITensorInfo *output, const PoolingLayerInfo &pool_info)
Static function to check if given info will lead to a valid configuration of GCPoolingLayer.
Detailed Description
Basic function to simulate a pooling layer with the specified pooling operation.
This function calls the following OpenGL ES kernels:
GCFillBorderKernel (executed if padding size is different from zero)
GCPoolingLayerKernel
Definition at line 45 of file GCPoolingLayer.h.
Constructor & Destructor Documentation
GCPoolingLayer()
GCPoolingLayer ()
Definition at line 34 of file GCPoolingLayer.cpp.
     : _kernel(nullptr), _border_handler(), _shift_handler()
 {
 }
Member Function Documentation
configure()
void configure (IGCTensor * input, IGCTensor * output, const PoolingLayerInfo & pool_info)
Set the input and output tensors.
Parameters
[in,out] input Source tensor. (Written to only when padding != 0) Data types supported: F16/F32.
[out] output Destination tensor. Data types supported: Same as input.
[in] pool_info Contains pooling operation information described in PoolingLayerInfo.
Definition at line 39 of file GCPoolingLayer.cpp.
 {
     // Configure pooling kernel
     auto k = arm_compute::support::cpp14::make_unique<GCPoolingLayerKernel>();
     k->configure(input, output, pool_info);
     _kernel = std::move(k);
     // Configure border depending on operation required
     BorderMode border_mode = (PoolingType::MAX == pool_info.pool_type()) ? BorderMode::REPLICATE : BorderMode::CONSTANT;
     _border_handler.configure(input, _kernel->border_size(), border_mode, PixelValue(0.0f));
     _shift_handler.configure(input);
 }
References arm_compute::test::validation::border_mode, GCFillBorderKernel::configure(), GCTensorShiftKernel::configure(), arm_compute::CONSTANT, arm_compute::MAX, PoolingLayerInfo::pool_type(), and arm_compute::REPLICATE.
run()
void run () final override virtual
Run the kernels contained in the function.
For NEON kernels:
Multi-threading is used for the kernels which are parallelisable.
By default std::thread::hardware_concurrency() threads are used.
Note
CPPScheduler::set_num_threads() can be used to manually set the number of threads
For OpenCL kernels:
All the kernels are enqueued on the queue associated with CLScheduler.
The queue is then flushed.
Note
The function will not block until the kernels are executed. It is the user's responsibility to wait.
Will call prepare() on first run if hasn't been done
Implements IFunction.
Definition at line 58 of file GCPoolingLayer.cpp.
 {
     GCScheduler::get().dispatch(_shift_handler, false);
     GCScheduler::get().memory_barrier();
     GCScheduler::get().dispatch(_border_handler, false);
     GCScheduler::get().memory_barrier();
     GCScheduler::get().dispatch(*_kernel);
 }
References GCScheduler::dispatch(), GCScheduler::get(), and GCScheduler::memory_barrier().
validate()
Status validate (const ITensorInfo * input, const ITensorInfo * output, const PoolingLayerInfo & pool_info) static
Static function to check if given info will lead to a valid configuration of GCPoolingLayer.
Parameters
[in] input Source tensor info. Data types supported: F16/F32.
[in] output Destination tensor info. Data types supported: Same as input.
[in] pool_info Contains pooling operation information described in PoolingLayerInfo.
Returns
a status
Definition at line 53 of file GCPoolingLayer.cpp.
 {
     return GCPoolingLayerKernel::validate(input, output, pool_info);
 }
References GCPoolingLayerKernel::validate().
The documentation for this class was generated from the following files:
arm_compute/runtime/GLES_COMPUTE/functions/GCPoolingLayer.h
src/runtime/GLES_COMPUTE/functions/GCPoolingLayer.cpp