Compute Library: Memory Class Reference
Memory Class Reference
CPU implementation of memory object.
#include <Memory.h>
Public Member Functions
Memory ()
Default Constructor.
Memory (std::shared_ptr< IMemoryRegion > memory)
Default Constructor.
Memory (IMemoryRegion *memory)
Default Constructor.
Memory (const Memory &)=default
Allow instances of this class to be copied.
Memory & operator= (const Memory &)=default
Allow instances of this class to be copy assigned.
Memory (Memory &&) noexcept=default
Allow instances of this class to be moved.
Memory & operator= (Memory &&) noexcept=default
Allow instances of this class to be move assigned.
IMemoryRegion * region () final
Region accessor.
IMemoryRegion * region () const final
Region accessor.
void set_region (IMemoryRegion *region) final
Sets a memory region.
void set_owned_region (std::unique_ptr< IMemoryRegion > region) final
Sets a memory region.
Public Member Functions inherited from IMemory
virtual ~IMemory ()=default
Virtual default destructor.
Detailed Description
CPU implementation of memory object.
Definition at line 37 of file Memory.h.
Constructor & Destructor Documentation
Memory() [1/5]
Memory ()
Default Constructor.
Definition at line 30 of file Memory.cpp.
     : _region(nullptr), _region_owned(nullptr)
 {
 }
Memory() [2/5]
Memory (std::shared_ptr< IMemoryRegion > memory)
Default Constructor.
Parameters
[in] memory Memory to be imported
Definition at line 35 of file Memory.cpp.
     : _region(nullptr), _region_owned(std::move(memory))
 {
     _region_owned = memory;
     _region       = _region_owned.get();
 }
Memory() [3/5]
Memory (IMemoryRegion * memory)
Default Constructor.
Note
Ownership of the memory is not transferred to this object. Thus management (allocate/free) should be done by the client.
Parameters
[in] memory Memory to be imported
Definition at line 42 of file Memory.cpp.
     : _region(memory), _region_owned(nullptr)
 {
     _region = memory;
 }
Memory() [4/5]
Memory (const Memory &) default
Allow instances of this class to be copied.
Memory() [5/5]
Memory (Memory &&) default noexcept
Allow instances of this class to be moved.
Member Function Documentation
operator=() [1/2]
Memory& operator= (const Memory &) default
Allow instances of this class to be copy assigned.
operator=() [2/2]
Memory& operator= (Memory &&) default noexcept
Allow instances of this class to be move assigned.
region() [1/2]
IMemoryRegion * region () final virtual
Region accessor.
Returns
Memory region
Implements IMemory.
Definition at line 48 of file Memory.cpp.
 {
     return _region;
 }
Referenced by TensorAllocator::data(), TensorAllocator::init(), TensorAllocator::set_associated_memory_group(), Memory::set_owned_region(), and Memory::set_region().
region() [2/2]
IMemoryRegion * region () const final virtual
Region accessor.
Returns
Memory region
Implements IMemory.
Definition at line 53 of file Memory.cpp.
 {
     return _region;
 }
set_owned_region()
void set_owned_region (std::unique_ptr< IMemoryRegion > region) final virtual
Sets a memory region.
Warning
Ownership of the memory region is transfered along
Parameters
region Memory region
Implements IMemory.
Definition at line 64 of file Memory.cpp.
 {
     _region_owned = std::move(region);
     _region       = _region_owned.get();
 }
References Memory::region().
Referenced by TensorAllocator::allocate(), and TensorAllocator::import_memory().
set_region()
void set_region (IMemoryRegion * region) final virtual
Sets a memory region.
Warning
Ownership of the memory region remains to the caller
Parameters
region Memory region
Implements IMemory.
Definition at line 58 of file Memory.cpp.
 {
     _region_owned = nullptr;
     _region       = region;
 }
References Memory::region().
Referenced by TensorAllocator::free().
The documentation for this class was generated from the following files:
arm_compute/runtime/Memory.h
src/runtime/Memory.cpp