Compute Library: IGCSimpleKernel Class Reference
IGCSimpleKernel Class Reference
Interface for simple OpenGL ES kernels having 1 tensor input and 1 tensor output.
#include <IGCSimpleKernel.h>
Public Member Functions
IGCSimpleKernel ()
Constructor.
IGCSimpleKernel (const IGCSimpleKernel &)=delete
Prevent instances of this class from being copied (As this class contains pointers)
IGCSimpleKernel & operator= (const IGCSimpleKernel &)=delete
Prevent instances of this class from being copied (As this class contains pointers)
IGCSimpleKernel (IGCSimpleKernel &&)=default
Allow instances of this class to be moved.
IGCSimpleKernel & operator= (IGCSimpleKernel &&)=default
Allow instances of this class to be moved.
~IGCSimpleKernel ()=default
Default destructor.
void configure (const IGCTensor *input, IGCTensor *output, unsigned int num_elems_processed_per_iteration, bool border_undefined=false, const BorderSize &border_size=BorderSize())
Configure the kernel.
Public Member Functions inherited from IGCKernel
IGCKernel ()
Constructor.
GCKernel & kernel ()
Returns a reference to the GLES kernel of this object.
void add_1D_tensor_argument (unsigned int &idx, const IGCTensor *tensor, const unsigned int binding_point, const Window &window)
Add the passed 1D tensor's parameters to the object's kernel's arguments starting from the index idx.
void add_2D_tensor_argument (unsigned int &idx, const IGCTensor *tensor, const unsigned int binding_point, const Window &window)
Add the passed 2D tensor's parameters to the object's kernel's arguments starting from the index idx.
void add_3D_tensor_argument (unsigned int &idx, const IGCTensor *tensor, const unsigned int binding_point, const Window &window)
Add the passed 3D tensor's parameters to the object's kernel's arguments starting from the index idx.
unsigned int num_arguments_per_1D_tensor () const
Returns the number of arguments enqueued per 1D tensor object.
unsigned int num_arguments_per_2D_tensor () const
Returns the number of arguments enqueued per 2D tensor object.
unsigned int num_arguments_per_3D_tensor () const
Returns the number of arguments enqueued per 3D tensor object.
virtual void run (const Window &window)=0
Enqueue the OpenGL ES shader to process the given window.
void set_lws_hint (gles::NDRange &lws_hint)
Set the Local-Workgroup-Size hint.
void set_target (GPUTarget target)
Set the targeted GPU architecture.
GPUTarget get_target () const
Get the targeted GPU architecture.
Public Member Functions inherited from IKernel
IKernel ()
Constructor.
virtual ~IKernel ()=default
Destructor.
virtual bool is_parallelisable () const
Indicates whether or not the kernel is parallelisable.
virtual BorderSize border_size () const
The size of the border for that kernel.
const Window & window () const
The maximum window the kernel can be executed on.
Detailed Description
Interface for simple OpenGL ES kernels having 1 tensor input and 1 tensor output.
Definition at line 34 of file IGCSimpleKernel.h.
Constructor & Destructor Documentation
IGCSimpleKernel() [1/3]
IGCSimpleKernel ()
Constructor.
Definition at line 33 of file IGCSimpleKernel.cpp.
     : _input(nullptr), _output(nullptr)
 {
 }
IGCSimpleKernel() [2/3]
IGCSimpleKernel (const IGCSimpleKernel &) delete
Prevent instances of this class from being copied (As this class contains pointers)
IGCSimpleKernel() [3/3]
IGCSimpleKernel (IGCSimpleKernel &&) default
Allow instances of this class to be moved.
~IGCSimpleKernel()
~IGCSimpleKernel () default
Default destructor.
Member Function Documentation
configure()
void configure (const IGCTensor * input, IGCTensor * output, unsigned int num_elems_processed_per_iteration, bool border_undefined = false, const BorderSize & border_size = BorderSize())
Configure the kernel.
Parameters
[in] input Source tensor.
[out] output Destination tensor.
[in] num_elems_processed_per_iteration Number of processed elements per iteration.
[in] border_undefined (Optional) True if the border mode is undefined. False if it's replicate or constant.
[in] border_size (Optional) Size of the border.
Definition at line 38 of file IGCSimpleKernel.cpp.
 {
     _input  = input;
     _output = output;
     // Configure kernel window
     Window                 win = calculate_max_window(*input->info(), Steps(num_elems_processed_per_iteration), border_undefined, border_size);
     AccessWindowHorizontal output_access(output->info(), 0, num_elems_processed_per_iteration);
     update_window_and_padding(win,
                               AccessWindowHorizontal(input->info(), 0, num_elems_processed_per_iteration),
                               output_access);
     output_access.set_valid_region(win, input->info()->valid_region(), border_undefined, border_size);
     IGCKernel::configure(win);
 }
References IKernel::border_size(), arm_compute::calculate_max_window(), ITensor::info(), arm_compute::update_window_and_padding(), and ITensorInfo::valid_region().
operator=() [1/2]
IGCSimpleKernel& operator= (const IGCSimpleKernel &) delete
Prevent instances of this class from being copied (As this class contains pointers)
operator=() [2/2]
IGCSimpleKernel& operator= (IGCSimpleKernel &&) default
Allow instances of this class to be moved.
The documentation for this class was generated from the following files:
arm_compute/core/GLES_COMPUTE/IGCSimpleKernel.h
src/core/GLES_COMPUTE/IGCSimpleKernel.cpp