Compute Library: GCCol2ImKernel Class Reference
GCCol2ImKernel Class Reference
Interface for the col2im reshaping kernel.
#include <GCCol2ImKernel.h>
Public Member Functions
GCCol2ImKernel ()
Default constructor.
GCCol2ImKernel (const GCCol2ImKernel &)=delete
Prevent instances of this class from being copied (As this class contains pointers)
GCCol2ImKernel & operator= (const GCCol2ImKernel &)=delete
Prevent instances of this class from being copied (As this class contains pointers)
GCCol2ImKernel (GCCol2ImKernel &&)=default
Allow instances of this class to be moved.
GCCol2ImKernel & operator= (GCCol2ImKernel &&)=default
Allow instances of this class to be moved.
~GCCol2ImKernel ()=default
Default destructor.
void configure (const IGCTensor *input, IGCTensor *output, std::pair< unsigned int, unsigned int > convolved_dims)
Set the input and output of the kernel.
void run (const Window &window) override
Enqueue the OpenGL ES shader to process the given window.
Public Member Functions inherited from IGCKernel
IGCKernel ()
Constructor.
GCKernel & kernel ()
Returns a reference to the GLES kernel of this object.
void add_1D_tensor_argument (unsigned int &idx, const IGCTensor *tensor, const unsigned int binding_point, const Window &window)
Add the passed 1D tensor's parameters to the object's kernel's arguments starting from the index idx.
void add_2D_tensor_argument (unsigned int &idx, const IGCTensor *tensor, const unsigned int binding_point, const Window &window)
Add the passed 2D tensor's parameters to the object's kernel's arguments starting from the index idx.
void add_3D_tensor_argument (unsigned int &idx, const IGCTensor *tensor, const unsigned int binding_point, const Window &window)
Add the passed 3D tensor's parameters to the object's kernel's arguments starting from the index idx.
unsigned int num_arguments_per_1D_tensor () const
Returns the number of arguments enqueued per 1D tensor object.
unsigned int num_arguments_per_2D_tensor () const
Returns the number of arguments enqueued per 2D tensor object.
unsigned int num_arguments_per_3D_tensor () const
Returns the number of arguments enqueued per 3D tensor object.
void set_lws_hint (gles::NDRange &lws_hint)
Set the Local-Workgroup-Size hint.
void set_target (GPUTarget target)
Set the targeted GPU architecture.
GPUTarget get_target () const
Get the targeted GPU architecture.
Public Member Functions inherited from IKernel
IKernel ()
Constructor.
virtual ~IKernel ()=default
Destructor.
virtual bool is_parallelisable () const
Indicates whether or not the kernel is parallelisable.
virtual BorderSize border_size () const
The size of the border for that kernel.
const Window & window () const
The maximum window the kernel can be executed on.
Detailed Description
Interface for the col2im reshaping kernel.
Rearranges each matrix column into image blocks. It's the inverse operation of GCIm2ColKernel.
For example, a vector of 9 elements can be reshaped to a block(image) of 3x3:
\[ \left(\begin{array}{ccccccccc} a0 & a1 & a2 & a3 & a4 & a5 & a6 & a7 & a8 \\ \end{array} \right) \rightarrow \left(\begin{array}{ccc} a0 & a1 & a2 \\ a3 & a4 & a5 \\ a6 & a7 & a8 \\ \end{array} \right) \]
Definition at line 52 of file GCCol2ImKernel.h.
Constructor & Destructor Documentation
GCCol2ImKernel() [1/3]
GCCol2ImKernel ()
Default constructor.
Definition at line 39 of file GCCol2ImKernel.cpp.
     : _input(nullptr), _output(nullptr), _convolved_dims()
 {
 }
GCCol2ImKernel() [2/3]
GCCol2ImKernel (const GCCol2ImKernel &) delete
Prevent instances of this class from being copied (As this class contains pointers)
GCCol2ImKernel() [3/3]
GCCol2ImKernel (GCCol2ImKernel &&) default
Allow instances of this class to be moved.
~GCCol2ImKernel()
~GCCol2ImKernel () default
Default destructor.
Member Function Documentation
configure()
void configure (const IGCTensor * input, IGCTensor * output, std::pair< unsigned int, unsigned int > convolved_dims)
Set the input and output of the kernel.
Parameters
[in] input The input tensor to convert. Data types supported: F16/F32
[out] output The output tensor. 3 lower dimensions represent a single output [width, height, OFM], while the rest represent batch of outputs. Data types supported: Same as input
[in] convolved_dims Output convolved dimensions.
Definition at line 44 of file GCCol2ImKernel.cpp.
 {
     ARM_COMPUTE_ERROR_ON_DATA_TYPE_CHANNEL_NOT_IN(input, 1, DataType::F16, DataType::F32);
     ARM_COMPUTE_ERROR_ON_NULLPTR(output);
     TensorShape output_shape = input->info()->tensor_shape();
     output_shape.set(0, convolved_dims.first);
     output_shape.set(1, convolved_dims.second);
     output_shape.set(2, input->info()->tensor_shape()[0]);
     // Output auto inizialitation if not yet initialized
     auto_init_if_empty(*output->info(), input->info()->clone()->set_tensor_shape(output_shape));
     ARM_COMPUTE_ERROR_ON_MISMATCHING_DIMENSIONS(output->info()->tensor_shape(), output_shape);
     ARM_COMPUTE_ERROR_ON_MISMATCHING_DATA_TYPES(input, output);
     _input          = input;
     _output         = output;
     _convolved_dims = convolved_dims;
     const DataType     dt         = input->info()->data_type();
     const unsigned int local_size = 1;
     // Create kernel
     std::set<std::string> build_opts;
     build_opts.emplace("#define COL2IM ");
     build_opts.emplace("#define WIDTH_OUTPUT " + support::cpp11::to_string(_convolved_dims.first));
     const std::string dt_name = (dt == DataType::F32) ? "DATA_TYPE_FP32" : "DATA_TYPE_FP16";
     build_opts.emplace(("#define " + dt_name));
     build_opts.emplace("#define LOCAL_SIZE_X " + support::cpp11::to_string(local_size));
     build_opts.emplace("#define LOCAL_SIZE_Y " + support::cpp11::to_string(local_size));
     build_opts.emplace("#define LOCAL_SIZE_Z " + support::cpp11::to_string(local_size));
     _kernel = static_cast<GCKernel>(GCKernelLibrary::get().create_kernel("col2im", build_opts));
     // Configure window
     const unsigned int num_elems_processed_per_iteration = (dt == DataType::F32) ? 1 : 2;
     Window win = calculate_max_window(*output->info(), Steps(num_elems_processed_per_iteration));
     AccessWindowHorizontal output_access(output->info(), 0, num_elems_processed_per_iteration);
     const int              input_padding = ceil_to_multiple(input->info()->dimension(0), 2) - input->info()->dimension(0);
     AccessWindowStatic input_access(input->info(), 0, 0, input->info()->dimension(0) + input_padding, input->info()->dimension(1) + 1);
     update_window_and_padding(win, input_access, output_access);
     output_access.set_valid_region(win, output->info()->valid_region());
     IGCKernel::configure(win);
 }
References ARM_COMPUTE_ERROR_ON_DATA_TYPE_CHANNEL_NOT_IN, ARM_COMPUTE_ERROR_ON_MISMATCHING_DATA_TYPES, ARM_COMPUTE_ERROR_ON_MISMATCHING_DIMENSIONS, ARM_COMPUTE_ERROR_ON_NULLPTR, arm_compute::auto_init_if_empty(), arm_compute::calculate_max_window(), arm_compute::ceil_to_multiple(), ICloneable< T >::clone(), arm_compute::create_kernel(), ITensorInfo::data_type(), ITensorInfo::dimension(), arm_compute::F16, arm_compute::F32, GCKernelLibrary::get(), ITensor::info(), arm_compute::test::validation::output_shape, ITensorInfo::tensor_shape(), arm_compute::support::cpp11::to_string(), arm_compute::update_window_and_padding(), and ITensorInfo::valid_region().
Referenced by GCConvolutionLayer::configure().
operator=() [1/2]
GCCol2ImKernel& operator= (const GCCol2ImKernel &) delete
Prevent instances of this class from being copied (As this class contains pointers)
operator=() [2/2]
GCCol2ImKernel& operator= (GCCol2ImKernel &&) default
Allow instances of this class to be moved.
run()
void run (const Window & window) override virtual
Enqueue the OpenGL ES shader to process the given window.
Parameters
[in] window Region on which to execute the kernel. (Must be a valid region of the window returned by window()).
Implements IGCKernel.
Definition at line 97 of file GCCol2ImKernel.cpp.
 {
     ARM_COMPUTE_ERROR_ON_UNCONFIGURED_KERNEL(this);
     ARM_COMPUTE_ERROR_ON_MISMATCHING_WINDOWS(IGCKernel::window(), window);
     _kernel.use();
     Window collapsed_window = window.collapse_if_possible(IGCKernel::window(), Window::DimZ);
     Window slice            = collapsed_window.first_slice_window_3D();
     // Set static kernel arguments
     unsigned int idx = 2 * num_arguments_per_3D_tensor();
     //_kernel.set_argument(idx++, _output->info()->strides_in_bytes()[3]);
     _kernel.set_argument(idx++, uint(_output->info()->dimension(2)));
     _kernel.set_argument(idx++, _input->info()->strides_in_bytes()[2]);
     do
     {
         // Set inputs
         unsigned int idx = 0;
         add_2D_tensor_argument(idx, _input, 1, slice);
         add_3D_tensor_argument(idx, _output, 2, slice);
         _kernel.update_shader_params();
         enqueue(*this, slice);
     }
     while(collapsed_window.slide_window_slice_3D(slice));
 }
References IGCKernel::add_2D_tensor_argument(), IGCKernel::add_3D_tensor_argument(), ARM_COMPUTE_ERROR_ON_MISMATCHING_WINDOWS, ARM_COMPUTE_ERROR_ON_UNCONFIGURED_KERNEL, Window::collapse_if_possible(), ITensorInfo::dimension(), Window::DimZ, arm_compute::enqueue(), Window::first_slice_window_3D(), ITensor::info(), IGCKernel::num_arguments_per_3D_tensor(), arm_compute::test::validation::reference::slice(), Window::slide_window_slice_3D(), ITensorInfo::strides_in_bytes(), and IKernel::window().
The documentation for this class was generated from the following files:
arm_compute/core/GLES_COMPUTE/kernels/GCCol2ImKernel.h
src/core/GLES_COMPUTE/kernels/GCCol2ImKernel.cpp