Compute Library: NEHarrisScoreKernel< block_size > Class Template Reference
NEHarrisScoreKernel< block_size > Class Template Reference
Template NEON kernel to perform Harris Score.
#include <NEHarrisCornersKernel.h>
Public Member Functions
const char * name () const override
Name of the kernel.
NEHarrisScoreKernel ()
Default constructor.
void configure (const IImage *input1, const IImage *input2, IImage *output, float norm_factor, float strength_thresh, float sensitivity, bool border_undefined) override
Setup the kernel parameters.
BorderSize border_size () const override
The size of the border for that kernel.
void run (const Window &window, const ThreadInfo &info) override
Execute the kernel on the passed window.
Public Member Functions inherited from INEHarrisScoreKernel
INEHarrisScoreKernel ()
Default constructor.
INEHarrisScoreKernel (const INEHarrisScoreKernel &)=delete
Prevent instances of this class from being copied (As this class contains pointers)
INEHarrisScoreKernel & operator= (const INEHarrisScoreKernel &)=delete
Prevent instances of this class from being copied (As this class contains pointers)
INEHarrisScoreKernel (INEHarrisScoreKernel &&)=default
Allow instances of this class to be moved.
INEHarrisScoreKernel & operator= (INEHarrisScoreKernel &&)=default
Allow instances of this class to be moved.
~INEHarrisScoreKernel ()=default
Default destructor.
Public Member Functions inherited from ICPPKernel
virtual ~ICPPKernel ()=default
Default destructor.
Public Member Functions inherited from IKernel
IKernel ()
Constructor.
virtual ~IKernel ()=default
Destructor.
virtual bool is_parallelisable () const
Indicates whether or not the kernel is parallelisable.
const Window & window () const
The maximum window the kernel can be executed on.
Detailed Description
template<int32_t block_size>
class arm_compute::NEHarrisScoreKernel< block_size >
Template NEON kernel to perform Harris Score.
The implementation supports 3, 5, and 7 for the block_size
Definition at line 84 of file NEHarrisCornersKernel.h.
Constructor & Destructor Documentation
NEHarrisScoreKernel()
NEHarrisScoreKernel ()
Default constructor.
Definition at line 703 of file NEHarrisCornersKernel.cpp.
     : INEHarrisScoreKernel(), _func(nullptr)
 {
 }
Member Function Documentation
border_size()
BorderSize border_size () const override virtual
The size of the border for that kernel.
Returns
The width in number of elements of the border.
Reimplemented from IKernel.
Definition at line 730 of file NEHarrisCornersKernel.cpp.
 {
     return _border_size;
 }
configure()
void configure (const IImage * input1, const IImage * input2, IImage * output, float norm_factor, float strength_thresh, float sensitivity, bool border_undefined) override virtual
Setup the kernel parameters.
Parameters
[in] input1 Source image (gradient X). Data types supported: S16/S32
[in] input2 Source image (gradient Y). Data types supported: same as @ input1
[out] output Destination image (harris score). Data types supported: F32
[in] norm_factor Normalization factor to use accordingly with the gradient size (Must be different from 0)
[in] strength_thresh Minimum threshold with which to eliminate Harris Corner scores (computed using the normalized Sobel kernel).
[in] sensitivity Sensitivity threshold k from the Harris-Stephens equation
[in] border_undefined True if the border mode is undefined. False if it's replicate or constant.
Implements INEHarrisScoreKernel.
Definition at line 736 of file NEHarrisCornersKernel.cpp.
 {
     ARM_COMPUTE_ERROR_ON_TENSOR_NOT_2D(input1);
     ARM_COMPUTE_ERROR_ON_TENSOR_NOT_2D(input2);
     ARM_COMPUTE_ERROR_ON_TENSOR_NOT_2D(output);
     ARM_COMPUTE_ERROR_ON_DATA_TYPE_CHANNEL_NOT_IN(input1, 1, DataType::S16, DataType::S32);
     ARM_COMPUTE_ERROR_ON_DATA_TYPE_CHANNEL_NOT_IN(input2, 1, DataType::S16, DataType::S32);
     ARM_COMPUTE_ERROR_ON_DATA_TYPE_CHANNEL_NOT_IN(output, 1, DataType::F32);
     ARM_COMPUTE_ERROR_ON_MISMATCHING_DATA_TYPES(input1, input2);
     ARM_COMPUTE_ERROR_ON(0.0f == norm_factor);
     _input1          = input1;
     _input2          = input2;
     _output          = output;
     _sensitivity     = sensitivity;
     _strength_thresh = strength_thresh;
     _norm_factor     = norm_factor;
     _border_size     = BorderSize(block_size / 2);
     if(input1->info()->data_type() == DataType::S16)
     {
         switch(block_size)
         {
             case 3:
                 _func = &harris_score3x3_S16_S16_FLOAT;
                 break;
             case 5:
                 _func = &harris_score5x5_S16_S16_FLOAT;
                 break;
             case 7:
                 _func = &harris_score7x7_S16_S16_FLOAT;
                 break;
             default:
                 ARM_COMPUTE_ERROR("Invalid block size");
                 break;
         }
     }
     else
     {
         switch(block_size)
         {
             case 3:
                 _func = &harris_score3x3_S32_S32_FLOAT;
                 break;
             case 5:
                 _func = &harris_score5x5_S32_S32_FLOAT;
                 break;
             case 7:
                 _func = &harris_score7x7_S32_S32_FLOAT;
                 break;
             default:
                 ARM_COMPUTE_ERROR("Invalid block size");
                 break;
         }
     }
     ARM_COMPUTE_ERROR_ON(nullptr == _func);
     constexpr unsigned int num_elems_processed_per_iteration = block_size != 7 ? 8 : 4;
     constexpr unsigned int num_elems_read_per_iteration      = block_size != 7 ? 16 : 12;
     constexpr unsigned int num_elems_written_per_iteration   = block_size != 7 ? 8 : 4;
     constexpr unsigned int num_rows_read_per_iteration       = block_size;
     // Configure kernel window
     Window                 win = calculate_max_window(*input1->info(), Steps(num_elems_processed_per_iteration), border_undefined, border_size());
     AccessWindowHorizontal output_access(output->info(), 0, num_elems_written_per_iteration);
     update_window_and_padding(win,
                               AccessWindowRectangle(input1->info(), -_border_size.left, -_border_size.top, num_elems_read_per_iteration, num_rows_read_per_iteration),
                               AccessWindowRectangle(input2->info(), -_border_size.left, -_border_size.top, num_elems_read_per_iteration, num_rows_read_per_iteration),
                               output_access);
     ValidRegion valid_region = intersect_valid_regions(input1->info()->valid_region(),
                                                        input2->info()->valid_region());
     output_access.set_valid_region(win, valid_region, border_undefined, border_size());
     INEKernel::configure(win);
 }
References ARM_COMPUTE_ERROR, ARM_COMPUTE_ERROR_ON, ARM_COMPUTE_ERROR_ON_DATA_TYPE_CHANNEL_NOT_IN, ARM_COMPUTE_ERROR_ON_MISMATCHING_DATA_TYPES, ARM_COMPUTE_ERROR_ON_TENSOR_NOT_2D, arm_compute::calculate_max_window(), ITensorInfo::data_type(), arm_compute::F32, ITensor::info(), arm_compute::intersect_valid_regions(), arm_compute::S16, arm_compute::S32, arm_compute::update_window_and_padding(), arm_compute::test::validation::valid_region, and ITensorInfo::valid_region().
name()
const char* name () const inline override virtual
Name of the kernel.
Returns
Kernel name
Implements ICPPKernel.
Definition at line 87 of file NEHarrisCornersKernel.h.
     {
         return "NEHarrisScoreKernel";
     }
run()
void run (const Window & window, const ThreadInfo & info) override virtual
Execute the kernel on the passed window.
Warning
If is_parallelisable() returns false then the passed window must be equal to window()
Note
The window has to be a region within the window returned by the window() method
The width of the window has to be a multiple of num_elems_processed_per_iteration().
Parameters
[in] window Region on which to execute the kernel. (Must be a region of the window returned by window())
[in] info Info about executing thread and CPU.
Implements ICPPKernel.
Definition at line 709 of file NEHarrisCornersKernel.cpp.
 {
     ARM_COMPUTE_UNUSED(info);
     ARM_COMPUTE_ERROR_ON_UNCONFIGURED_KERNEL(this);
     ARM_COMPUTE_ERROR_ON_INVALID_SUBWINDOW(INEKernel::window(), window);
     ARM_COMPUTE_ERROR_ON(_func == nullptr);
     Iterator input1(_input1, window);
     Iterator input2(_input2, window);
     Iterator output(_output, window);
     const size_t input_stride = _input1->info()->strides_in_bytes()[1] / element_size_from_data_type(_input1->info()->data_type());
     execute_window_loop(window, [&](const Coordinates & id)
     {
         (*_func)(input1.ptr(), input2.ptr(), output.ptr(), input_stride, _norm_factor, _sensitivity, _strength_thresh);
     },
     input1, input2, output);
 }
References ARM_COMPUTE_ERROR_ON, ARM_COMPUTE_ERROR_ON_INVALID_SUBWINDOW, ARM_COMPUTE_ERROR_ON_UNCONFIGURED_KERNEL, ARM_COMPUTE_UNUSED, arm_compute::element_size_from_data_type(), arm_compute::execute_window_loop(), arm_compute::test::validation::info, Iterator::ptr(), and IKernel::window().
The documentation for this class was generated from the following files:
arm_compute/core/NEON/kernels/NEHarrisCornersKernel.h
src/core/NEON/kernels/NEHarrisCornersKernel.cpp