Compute Library: Steps Class Reference
Steps Class Reference
Class to describe a number of elements in each dimension.
#include <Steps.h>
Public Member Functions
template<typename... Ts>
Steps (Ts...steps)
Constructor to initialize the steps.
constexpr Steps (const Steps &)=default
Allow instances of this class to be copy constructed.
Steps & operator= (const Steps &)=default
Allow instances of this class to be copied.
constexpr Steps (Steps &&)=default
Allow instances of this class to be move constructed.
Steps & operator= (Steps &&)=default
Allow instances of this class to be moved.
~Steps ()=default
Default destructor.
Public Member Functions inherited from Dimensions< unsigned int >
Dimensions (Ts...dims)
Constructor to initialize the tensor shape.
Dimensions (const Dimensions &)=default
Allow instances of this class to be copy constructed.
Dimensions (Dimensions &&)=default
Allow instances of this class to be move constructed.
Dimensions & operator= (const Dimensions &)=default
Allow instances of this class to be copied.
Dimensions & operator= (Dimensions &&)=default
Allow instances of this class to be moved.
void set (size_t dimension, unsigned intvalue)
Accessor to set the value of one of the dimensions.
unsigned int x () const
Alias to access the size of the first dimension.
unsigned int y () const
Alias to access the size of the second dimension.
unsigned int z () const
Alias to access the size of the third dimension.
const unsigned int & operator[] (size_t dimension) const
Generic accessor to get the size of any dimension.
unsigned int & operator[] (size_t dimension)
Generic accessor to get the size of any dimension.
unsigned int num_dimensions () const
Returns the effective dimensionality of the tensor.
void set_num_dimensions (size_t num_dimensions)
Set number of dimensions.
void collapse (size_t n, size_t first=0)
Collapse dimensions.
void collapse_from (size_t start)
Collapse dimensions starting from a given point.
std::array< unsigned int, num_max_dimensions >::iterator begin ()
Returns a read/write iterator that points to the first element in the dimension array.
std::array< unsigned int, num_max_dimensions >::const_iterator begin () const
Returns a read-only (constant) iterator that points to the first element in the dimension array.
std::array< unsigned int, num_max_dimensions >::const_iterator cbegin () const
Returns a read-only (constant) iterator that points to the first element in the dimension array.
std::array< unsigned int, num_max_dimensions >::iterator end ()
Returns a read/write iterator that points one past the last element in the dimension array.
std::array< unsigned int, num_max_dimensions >::const_iterator end () const
Returns a read-only (constant) iterator that points one past the last element in the dimension array.
std::array< unsigned int, num_max_dimensions >::const_iterator cend () const
Returns a read-only (constant) iterator that points one past the last element in the dimension array.
Additional Inherited Members
Static Public Attributes inherited from Dimensions< unsigned int >
static constexpr size_t num_max_dimensions
Number of dimensions the tensor has.
Detailed Description
Class to describe a number of elements in each dimension.
Similar to Strides but not in bytes but number of elements.
Definition at line 40 of file Steps.h.
Constructor & Destructor Documentation
Steps (Ts... steps) inline
Constructor to initialize the steps.
Parameters
[in] steps Values to initialize the steps.
Definition at line 48 of file Steps.h.
References Steps::operator=(), and Steps::~Steps().
         : Dimensions{ steps... }
     {
         // Initialize empty dimensions to 1
         std::fill(_id.begin() + _num_dimensions, _id.end(), 1);
     }
constexpr Steps (const Steps &) default
Allow instances of this class to be copy constructed.
constexpr Steps (Steps &&) default
Allow instances of this class to be move constructed.
~Steps () default
Default destructor.
Referenced by Steps::Steps().
Member Function Documentation
Steps& operator= (const Steps &) default
Allow instances of this class to be copied.
Referenced by Steps::Steps().
Steps& operator= (Steps &&) default
Allow instances of this class to be moved.
The documentation for this class was generated from the following file:
arm_compute/core/Steps.h