Compute Library: HOGAccessor Class Reference
HOGAccessor Class Reference
Accessor implementation for HOG objects.
#include <HOGAccessor.h>
Public Member Functions
HOGAccessor (HOG &hog)
Create an accessor for the given HOG.
HOGAccessor (const HOGAccessor &)=delete
Prevent instances of this class from being copied (As this class contains references).
HOGAccessor & operator= (const HOGAccessor &)=delete
Prevent instances of this class from being copied (As this class contains references).
HOGAccessor (HOGAccessor &&)=default
Allow instances of this class to be moved.
HOGAccessor & operator= (HOGAccessor &&)=default
Allow instances of this class to be moved.
float * descriptor () const override
Pointer to the first element of the array which stores the linear SVM coefficients of HOG descriptor.
Public Member Functions inherited from IHOGAccessor
virtual ~IHOGAccessor ()=default
Virtual destructor.
Detailed Description
Accessor implementation for HOG objects.
Definition at line 35 of file HOGAccessor.h.
Constructor & Destructor Documentation
HOGAccessor (HOG & hog) inline
Create an accessor for the given HOG.
Definition at line 40 of file HOGAccessor.h.
References HOGAccessor::operator=().
         : _hog{ hog }
     {
     }
HOGAccessor (const HOGAccessor &) delete
Prevent instances of this class from being copied (As this class contains references).
HOGAccessor (HOGAccessor &&) default
Allow instances of this class to be moved.
Member Function Documentation
float* descriptor () const inline override virtual
Pointer to the first element of the array which stores the linear SVM coefficients of HOG descriptor.
Returns
A pointer to the first element of the array which stores the linear SVM coefficients of HOG descriptor
Implements IHOGAccessor.
Definition at line 58 of file HOGAccessor.h.
References HOG::descriptor().
     {
         return _hog.descriptor();
     }
HOGAccessor& operator= (const HOGAccessor &) delete
Prevent instances of this class from being copied (As this class contains references).
Referenced by HOGAccessor::HOGAccessor().
HOGAccessor& operator= (HOGAccessor &&) default
Allow instances of this class to be moved.
The documentation for this class was generated from the following file:
tests/NEON/HOGAccessor.h