Compute Library: TopNPredictionsAccessor Class Reference
TopNPredictionsAccessor Class Reference final
Result accessor class.
#include <GraphUtils.h>
Public Member Functions
TopNPredictionsAccessor (const std::string &labels_path, size_t top_n=5, std::ostream &output_stream=std::cout)
Constructor.
TopNPredictionsAccessor (TopNPredictionsAccessor &&)=default
Allow instances of this class to be move constructed.
TopNPredictionsAccessor (const TopNPredictionsAccessor &)=delete
Prevent instances of this class from being copied (As this class contains pointers)
TopNPredictionsAccessor & operator= (const TopNPredictionsAccessor &)=delete
Prevent instances of this class from being copied (As this class contains pointers)
bool access_tensor (ITensor &tensor) override
Interface to be implemented to access a given tensor.
Public Member Functions inherited from ITensorAccessor
virtual ~ITensorAccessor ()=default
Default virtual destructor.
Detailed Description
Result accessor class.
Definition at line 118 of file GraphUtils.h.
Constructor & Destructor Documentation
TopNPredictionsAccessor (const std::string & labels_path, size_t top_n = 5, std::ostream & output_stream = std::cout)
Constructor.
Parameters
[in] labels_path Path to labels text file.
[in] top_n (Optional) Number of output classes to print
[out] output_stream (Optional) Output stream
Definition at line 122 of file GraphUtils.cpp.
References arm_compute::test::validation::a, ARM_COMPUTE_ERROR, arm_compute::test::validation::b, ITensor::buffer(), ITensorInfo::dimension(), ITensor::info(), and ITensorInfo::offset_first_element_in_bytes().
     : _labels(), _output_stream(output_stream), _top_n(top_n)
 {
     _labels.clear();
     std::ifstream ifs;
     try
     {
         ifs.exceptions(std::ifstream::badbit);
         ifs.open(labels_path, std::ios::in | std::ios::binary);
         for(std::string line; !std::getline(ifs, line).fail();)
         {
             _labels.emplace_back(line);
         }
     }
     catch(const std::ifstream::failure &e)
     {
         ARM_COMPUTE_ERROR("Accessing %s: %s", labels_path.c_str(), e.what());
     }
 }
TopNPredictionsAccessor (TopNPredictionsAccessor &&) default
Allow instances of this class to be move constructed.
TopNPredictionsAccessor (const TopNPredictionsAccessor &) delete
Prevent instances of this class from being copied (As this class contains pointers)
Member Function Documentation
bool access_tensor (ITensor & tensor) override virtual
Interface to be implemented to access a given tensor.
Parameters
[in] tensor Tensor to be accessed
Returns
True if access is successful else false
Implements ITensorAccessor.
Definition at line 179 of file GraphUtils.cpp.
References ARM_COMPUTE_ERROR, ARM_COMPUTE_ERROR_ON, ARM_COMPUTE_ERROR_ON_DATA_TYPE_CHANNEL_NOT_IN, ITensorInfo::data_type(), ITensorInfo::dimension(), arm_compute::F32, ITensor::info(), and arm_compute::QASYMM8.
 {
     ARM_COMPUTE_ERROR_ON_DATA_TYPE_CHANNEL_NOT_IN(&tensor, 1, DataType::F32, DataType::QASYMM8);
     ARM_COMPUTE_ERROR_ON(_labels.size() != tensor.info()->dimension(0));
     switch(tensor.info()->data_type())
     {
         case DataType::QASYMM8:
             access_predictions_tensor<uint8_t>(tensor);
             break;
         case DataType::F32:
             access_predictions_tensor<float>(tensor);
             break;
         default:
             ARM_COMPUTE_ERROR("NOT SUPPORTED!");
     }
     return false;
 }
TopNPredictionsAccessor& operator= (const TopNPredictionsAccessor &) delete
Prevent instances of this class from being copied (As this class contains pointers)
The documentation for this class was generated from the following files:
utils/GraphUtils.h
utils/GraphUtils.cpp