Compute Library: CLDistribution1D Class Reference
CLDistribution1D Class Reference
CLDistribution1D object class.
#include <CLDistribution1D.h>
Public Member Functions
CLDistribution1D (size_t num_bins, int32_t offset, uint32_t range)
Constructor: Creates a 1D CLDistribution of a consecutive interval [offset, offset + range - 1] defined by a start offset and valid range, divided equally into num_bins parts.
CLDistribution1D (const CLDistribution1D &)=delete
Prevent instances of this class from being copied (As this class contains pointers)
CLDistribution1D & operator= (const CLDistribution1D &)=delete
Prevent instances of this class from being copied (As this class contains pointers)
void map (bool blocking=true)
Enqueue a map operation of the allocated buffer.
void unmap ()
Enqueue an unmap operation of the allocated and mapped buffer.
cl::Buffer & cl_buffer () override
Interface to be implemented by the child class to return a reference to the OpenCL buffer containing the distribution's data.
void map (cl::CommandQueue &q, bool blocking=true)
Enqueue a map operation of the allocated buffer on the given queue.
void unmap (cl::CommandQueue &q)
Enqueue an unmap operation of the allocated and mapped buffer on the given queue.
Public Member Functions inherited from ICLDistribution1D
ICLDistribution1D (size_t num_bins, int32_t offset, uint32_t range)
Constructor: Creates a 1D CLDistribution of a consecutive interval [offset, offset + range - 1] defined by a start offset and valid range, divided equally into num_bins parts.
ICLDistribution1D (const ICLDistribution1D &)=delete
Prevent instances of this class from being copied (As this class contains pointers)
const ICLDistribution1D & operator= (const ICLDistribution1D &)=delete
Prevent instances of this class from being copied (As this class contains pointers)
void map (cl::CommandQueue &q, bool blocking=true)
Enqueue a map operation of the allocated buffer on the given queue.
void unmap (cl::CommandQueue &q)
Enqueue an unmap operation of the allocated and mapped buffer on the given queue.
uint32_t * buffer () const override
Returns a pointer to the start of the distribution.
Public Member Functions inherited from IDistribution1D
IDistribution1D (size_t num_bins, int32_t offset, uint32_t range)
Constructor: Creates a 1D Distribution of a consecutive interval [offset, offset + range - 1] defined by a start offset and valid range, divided equally into num_bins parts.
size_t num_bins () const
Returns the number of bins that the distribution has.
int32_t offset () const
Returns the offset of the distribution.
uint32_t range () const
Returns the range of the distribution.
uint32_t window () const
Returns the window of the distribution, which is the range divided by the number of bins.
void set_range (uint32_t range)
Sets the range of the distribution.
size_t size () const override
Returns the total size in bytes of the distribution.
size_t dimensions () const override
Returns the dimensions of the distribution.
Public Member Functions inherited from IDistribution
virtual ~IDistribution ()=default
Default virtual destructor.
void clear () const
Clears the distribution by setting every element to zero.
Detailed Description
CLDistribution1D object class.
Definition at line 36 of file CLDistribution1D.h.
Constructor & Destructor Documentation
CLDistribution1D() [1/2]
CLDistribution1D (size_t num_bins, int32_t offset, uint32_t range)
Constructor: Creates a 1D CLDistribution of a consecutive interval [offset, offset + range - 1] defined by a start offset and valid range, divided equally into num_bins parts.
Parameters
[in] num_bins The number of bins the distribution is divided in.
[in] offset The start of the values to use.
[in] range The total number of the consecutive values of the distribution interval.
Definition at line 31 of file CLDistribution1D.cpp.
     : ICLDistribution1D(num_bins, offset, range), _mem(CLScheduler::get().context(), CL_MEM_ALLOC_HOST_PTR | CL_MEM_READ_WRITE, num_bins * sizeof(int32_t))
 {
 }
CLDistribution1D() [2/2]
CLDistribution1D (const CLDistribution1D &) delete
Prevent instances of this class from being copied (As this class contains pointers)
Member Function Documentation
cl_buffer()
cl::Buffer & cl_buffer () override virtual
Interface to be implemented by the child class to return a reference to the OpenCL buffer containing the distribution's data.
Returns
A reference to an OpenCL buffer containing the distribution's data.
Implements ICLDistribution1D.
Definition at line 58 of file CLDistribution1D.cpp.
 {
     return _mem;
 }
map() [1/2]
void map (bool blocking = true)
Enqueue a map operation of the allocated buffer.
Parameters
[in] blocking If true, then the mapping will be ready to use by the time this method returns, else it is the caller's responsibility to flush the queue and wait for the mapping operation to have completed.
Definition at line 36 of file CLDistribution1D.cpp.
 {
     ICLDistribution1D::map(CLScheduler::get().queue(), blocking);
 }
References CLScheduler::get(), and ICLDistribution1D::map().
map() [2/2]
void map
Enqueue a map operation of the allocated buffer on the given queue.
Parameters
[in,out] q The CL command queue to use for the mapping operation.
[in] blocking If true, then the mapping will be ready to use by the time this method returns, else it is the caller's responsibility to flush the queue and wait for the mapping operation to have completed before using the returned mapping pointer.
Definition at line 35 of file ICLDistribution1D.cpp.
 {
     ARM_COMPUTE_ERROR_ON(_mapping != nullptr);
     _mapping = do_map(q, blocking);
 }
operator=()
CLDistribution1D& operator= (const CLDistribution1D &) delete
Prevent instances of this class from being copied (As this class contains pointers)
unmap() [1/2]
void unmap ()
Enqueue an unmap operation of the allocated and mapped buffer.
Note
This method simply enqueues the unmap operation, it is the caller's responsibility to flush the queue and make sure the unmap is finished before the memory is accessed by the device.
Definition at line 41 of file CLDistribution1D.cpp.
 {
     ICLDistribution1D::unmap(CLScheduler::get().queue());
 }
References CLScheduler::get(), and ICLDistribution1D::unmap().
unmap() [2/2]
void unmap
Enqueue an unmap operation of the allocated and mapped buffer on the given queue.
Note
This method simply enqueues the unmap operation, it is the caller's responsibility to flush the queue and make sure the unmap is finished before the memory is accessed by the device.
Parameters
[in,out] q The CL command queue to use for the mapping operation.
Definition at line 41 of file ICLDistribution1D.cpp.
 {
     ARM_COMPUTE_ERROR_ON(_mapping == nullptr);
     do_unmap(q);
     _mapping = nullptr;
 }
The documentation for this class was generated from the following files:
arm_compute/runtime/CL/CLDistribution1D.h
src/runtime/CL/CLDistribution1D.cpp