Compute Library: INodeVisitor Class Reference
INodeVisitor Class Reference abstract
Node visitor interface.
#include <INodeVisitor.h>
Public Member Functions
virtual ~INodeVisitor ()=default
Default destructor.
virtual void visit (INode &n)=0
Visit INode.
virtual void visit (ActivationLayerNode &n)=0
Visit ActivationLayerNode.
virtual void visit (BatchNormalizationLayerNode &n)=0
Visit BatchNormalizationLayerNode.
virtual void visit (ConcatenateLayerNode &n)=0
Visit ConcatenateLayerNode.
virtual void visit (ConstNode &n)=0
Visit ConstNode.
virtual void visit (ConvolutionLayerNode &n)=0
Visit ConvolutionLayerNode.
virtual void visit (DepthwiseConvolutionLayerNode &n)=0
Visit DepthwiseConvolutionLayerNode.
virtual void visit (DetectionOutputLayerNode &n)=0
Visit DetectionOutputLayerNode.
virtual void visit (DetectionPostProcessLayerNode &n)=0
Visit DetectionPostProcessLayerNode.
virtual void visit (EltwiseLayerNode &n)=0
Visit EltwiseLayerNode.
virtual void visit (FlattenLayerNode &n)=0
Visit FlattenLayerNode.
virtual void visit (FullyConnectedLayerNode &n)=0
Visit FullyConnectedLayerNode.
virtual void visit (FusedConvolutionBatchNormalizationNode &n)=0
Visit FusedConvolutionBatchNormalizationNode.
virtual void visit (FusedDepthwiseConvolutionBatchNormalizationNode &n)=0
Visit FusedDepthwiseConvolutionBatchNormalizationNode.
virtual void visit (InputNode &n)=0
Visit InputNode.
virtual void visit (NormalizationLayerNode &n)=0
Visit NormalizationLayerNode.
virtual void visit (OutputNode &n)=0
Visit OutputNode.
virtual void visit (PermuteLayerNode &n)=0
Visit PermuteLayerNode.
virtual void visit (PoolingLayerNode &n)=0
Visit PoolingLayerNode.
virtual void visit (PriorBoxLayerNode &n)=0
Visit PriorBoxLayerNode.
virtual void visit (QuantizationLayerNode &n)=0
Visit QuantizationLayerNode.
virtual void visit (ReshapeLayerNode &n)=0
Visit ReshapeLayerNode.
virtual void visit (SoftmaxLayerNode &n)=0
Visit SoftmaxLayerNode.
virtual void visit (SplitLayerNode &n)=0
Visit SplitLayerNode.
virtual void visit (StackLayerNode &n)=0
Visit StackLayerNode.
Detailed Description
Node visitor interface.
Definition at line 34 of file INodeVisitor.h.
Constructor & Destructor Documentation
~INodeVisitor()
virtual ~INodeVisitor () virtual default
Default destructor.
Member Function Documentation
visit() [1/25]
virtual void visit (INode & n) pure virtual
Visit INode.
Parameters
[in] n Node to visit.
Referenced by FlattenLayerNode::accept(), NormalizePlanarYUVLayerNode::accept(), OutputNode::accept(), InputNode::accept(), ConstNode::accept(), QuantizationLayerNode::accept(), ReshapeLayerNode::accept(), DetectionPostProcessLayerNode::accept(), SoftmaxLayerNode::accept(), NormalizationLayerNode::accept(), ChannelShuffleLayerNode::accept(), GenerateProposalsLayerNode::accept(), BoundingBoxTransformLayerNode::accept(), PadLayerNode::accept(), DummyNode::accept(), PermuteLayerNode::accept(), ActivationLayerNode::accept(), ResizeLayerNode::accept(), YOLOLayerNode::accept(), ROIAlignLayerNode::accept(), PriorBoxLayerNode::accept(), DetectionOutputLayerNode::accept(), PoolingLayerNode::accept(), ReorgLayerNode::accept(), StackLayerNode::accept(), DeconvolutionLayerNode::accept(), BatchNormalizationLayerNode::accept(), UpsampleLayerNode::accept(), EltwiseLayerNode::accept(), SliceLayerNode::accept(), SplitLayerNode::accept(), ConcatenateLayerNode::accept(), FullyConnectedLayerNode::accept(), DepthwiseConvolutionLayerNode::accept(), ConvolutionLayerNode::accept(), FusedDepthwiseConvolutionBatchNormalizationNode::accept(), and FusedConvolutionBatchNormalizationNode::accept().
visit() [2/25]
virtual void visit (ActivationLayerNode & n) pure virtual
Visit ActivationLayerNode.
Parameters
[in] n Node to visit.
Implemented in DotGraphVisitor.
visit() [3/25]
virtual void visit (BatchNormalizationLayerNode & n) pure virtual
Visit BatchNormalizationLayerNode.
Parameters
[in] n Node to visit.
Implemented in DotGraphVisitor.
visit() [4/25]
virtual void visit (ConcatenateLayerNode & n) pure virtual
Visit ConcatenateLayerNode.
Parameters
[in] n Node to visit.
Implemented in DotGraphVisitor.
visit() [5/25]
virtual void visit (ConstNode & n) pure virtual
Visit ConstNode.
Parameters
[in] n Node to visit.
visit() [6/25]
virtual void visit (ConvolutionLayerNode & n) pure virtual
Visit ConvolutionLayerNode.
Parameters
[in] n Node to visit.
Implemented in DotGraphVisitor.
visit() [7/25]
virtual void visit (DepthwiseConvolutionLayerNode & n) pure virtual
Visit DepthwiseConvolutionLayerNode.
Parameters
[in] n Node to visit.
Implemented in DotGraphVisitor.
visit() [8/25]
virtual void visit (DetectionOutputLayerNode & n) pure virtual
Visit DetectionOutputLayerNode.
Parameters
[in] n Node to visit.
visit() [9/25]
virtual void visit (DetectionPostProcessLayerNode & n) pure virtual
Visit DetectionPostProcessLayerNode.
Parameters
[in] n Node to visit.
visit() [10/25]
virtual void visit (EltwiseLayerNode & n) pure virtual
Visit EltwiseLayerNode.
Parameters
[in] n Node to visit.
Implemented in DotGraphVisitor.
visit() [11/25]
virtual void visit (FlattenLayerNode & n) pure virtual
Visit FlattenLayerNode.
Parameters
[in] n Node to visit.
visit() [12/25]
virtual void visit (FullyConnectedLayerNode & n) pure virtual
Visit FullyConnectedLayerNode.
Parameters
[in] n Node to visit.
visit() [13/25]
virtual void visit (FusedConvolutionBatchNormalizationNode & n) pure virtual
Visit FusedConvolutionBatchNormalizationNode.
Parameters
[in] n Node to visit.
Implemented in DotGraphVisitor.
visit() [14/25]
virtual void visit (FusedDepthwiseConvolutionBatchNormalizationNode & n) pure virtual
Visit FusedDepthwiseConvolutionBatchNormalizationNode.
Parameters
[in] n Node to visit.
Implemented in DotGraphVisitor.
visit() [15/25]
virtual void visit (InputNode & n) pure virtual
Visit InputNode.
Parameters
[in] n Node to visit.
visit() [16/25]
virtual void visit (NormalizationLayerNode & n) pure virtual
Visit NormalizationLayerNode.
Parameters
[in] n Node to visit.
Implemented in DotGraphVisitor.
visit() [17/25]
virtual void visit (OutputNode & n) pure virtual
Visit OutputNode.
Parameters
[in] n Node to visit.
visit() [18/25]
virtual void visit (PermuteLayerNode & n) pure virtual
Visit PermuteLayerNode.
Parameters
[in] n Node to visit.
visit() [19/25]
virtual void visit (PoolingLayerNode & n) pure virtual
Visit PoolingLayerNode.
Parameters
[in] n Node to visit.
Implemented in DotGraphVisitor.
visit() [20/25]
virtual void visit (PriorBoxLayerNode & n) pure virtual
Visit PriorBoxLayerNode.
Parameters
[in] n Node to visit.
visit() [21/25]
virtual void visit (QuantizationLayerNode & n) pure virtual
Visit QuantizationLayerNode.
Parameters
[in] n Node to visit.
visit() [22/25]
virtual void visit (ReshapeLayerNode & n) pure virtual
Visit ReshapeLayerNode.
Parameters
[in] n Node to visit.
visit() [23/25]
virtual void visit (SoftmaxLayerNode & n) pure virtual
Visit SoftmaxLayerNode.
Parameters
[in] n Node to visit.
visit() [24/25]
virtual void visit (SplitLayerNode & n) pure virtual
Visit SplitLayerNode.
Parameters
[in] n Node to visit.
visit() [25/25]
virtual void visit (StackLayerNode & n) pure virtual
Visit StackLayerNode.
Parameters
[in] n Node to visit.
The documentation for this class was generated from the following file:
arm_compute/graph/INodeVisitor.h