Compute Library: CLWidthConcatenate4TensorsKernel Class Reference
CLWidthConcatenate4TensorsKernel Class Reference
Interface for the width concatenate kernel of 4 tensors.
#include <CLWidthConcatenate4TensorsKernel.h>
Public Member Functions
CLWidthConcatenate4TensorsKernel ()
Default constructor.
CLWidthConcatenate4TensorsKernel (const CLWidthConcatenate4TensorsKernel &)=delete
Prevent instances of this class from being copied (As this class contains pointers)
CLWidthConcatenate4TensorsKernel & operator= (const CLWidthConcatenate4TensorsKernel &)=delete
Prevent instances of this class from being copied (As this class contains pointers)
CLWidthConcatenate4TensorsKernel (CLWidthConcatenate4TensorsKernel &&)=default
Allow instances of this class to be moved.
CLWidthConcatenate4TensorsKernel & operator= (CLWidthConcatenate4TensorsKernel &&)=default
Allow instances of this class to be moved.
~CLWidthConcatenate4TensorsKernel ()=default
Default destructor.
void configure (const ICLTensor *input1, const ICLTensor *input2, const ICLTensor *input3, const ICLTensor *input4, ICLTensor *output)
Initialise the kernel's input1s and output.
void run (const Window &window, cl::CommandQueue &queue) override
Enqueue the OpenCL kernel to process the given window on the passed OpenCL command queue.
Public Member Functions inherited from ICLKernel
ICLKernel ()
Constructor.
cl::Kernel & kernel ()
Returns a reference to the OpenCL kernel of this object.
template<typename T >
void add_1D_array_argument (unsigned int &idx, const ICLArray< T > *array, const Strides &strides, unsigned int num_dimensions, const Window &window)
Add the passed 1D array's parameters to the object's kernel's arguments starting from the index idx.
void add_1D_tensor_argument (unsigned int &idx, const ICLTensor *tensor, const Window &window)
Add the passed 1D tensor's parameters to the object's kernel's arguments starting from the index idx.
void add_2D_tensor_argument (unsigned int &idx, const ICLTensor *tensor, const Window &window)
Add the passed 2D tensor's parameters to the object's kernel's arguments starting from the index idx.
void add_3D_tensor_argument (unsigned int &idx, const ICLTensor *tensor, const Window &window)
Add the passed 3D tensor's parameters to the object's kernel's arguments starting from the index idx.
void add_4D_tensor_argument (unsigned int &idx, const ICLTensor *tensor, const Window &window)
Add the passed 4D tensor's parameters to the object's kernel's arguments starting from the index idx.
template<typename T >
void add_argument (unsigned int &idx, T value)
Add the passed parameters to the object's kernel's arguments starting from the index idx.
void set_lws_hint (const cl::NDRange &lws_hint)
Set the Local-Workgroup-Size hint.
cl::NDRange lws_hint () const
Return the Local-Workgroup-Size hint.
const std::string & config_id () const
Get the configuration ID.
void set_target (GPUTarget target)
Set the targeted GPU architecture.
void set_target (cl::Device &device)
Set the targeted GPU architecture according to the CL device.
GPUTarget get_target () const
Get the targeted GPU architecture.
size_t get_max_workgroup_size ()
Get the maximum workgroup size for the device the CLKernelLibrary uses.
template<typename T , unsigned int dimension_size>
void add_array_argument (unsigned &idx, const ICLArray< T > *array, const Strides &strides, unsigned int num_dimensions, const Window &window)
Add the passed array's parameters to the object's kernel's arguments starting from the index idx.
template<unsigned int dimension_size>
void add_tensor_argument (unsigned &idx, const ICLTensor *tensor, const Window &window)
Public Member Functions inherited from IKernel
IKernel ()
Constructor.
virtual ~IKernel ()=default
Destructor.
virtual bool is_parallelisable () const
Indicates whether or not the kernel is parallelisable.
virtual BorderSize border_size () const
The size of the border for that kernel.
const Window & window () const
The maximum window the kernel can be executed on.
Static Public Member Functions
static Status validate (const ITensorInfo *input1, const ITensorInfo *input2, const ITensorInfo *input3, const ITensorInfo *input4, const ITensorInfo *output)
Static function to check if given info will lead to a valid configuration of CLWidthConcatenate4TensorsKernel.
Static Public Member Functions inherited from ICLKernel
static constexpr unsigned int num_arguments_per_1D_array ()
Returns the number of arguments enqueued per 1D array object.
static constexpr unsigned int num_arguments_per_1D_tensor ()
Returns the number of arguments enqueued per 1D tensor object.
static constexpr unsigned int num_arguments_per_2D_tensor ()
Returns the number of arguments enqueued per 2D tensor object.
static constexpr unsigned int num_arguments_per_3D_tensor ()
Returns the number of arguments enqueued per 3D tensor object.
static constexpr unsigned int num_arguments_per_4D_tensor ()
Returns the number of arguments enqueued per 4D tensor object.
static cl::NDRange gws_from_window (const Window &window)
Get the global work size given an execution window.
Detailed Description
Interface for the width concatenate kernel of 4 tensors.
All input tensors will be concatenated into the output tensor.
Definition at line 38 of file CLWidthConcatenate4TensorsKernel.h.
Constructor & Destructor Documentation
CLWidthConcatenate4TensorsKernel() [1/3]
CLWidthConcatenate4TensorsKernel ()
Default constructor.
Definition at line 104 of file CLWidthConcatenate4TensorsKernel.cpp.
     : _input1(nullptr), _input2(nullptr), _input3(nullptr), _input4(nullptr), _output(nullptr)
 {
 }
CLWidthConcatenate4TensorsKernel() [2/3]
CLWidthConcatenate4TensorsKernel (const CLWidthConcatenate4TensorsKernel &) delete
Prevent instances of this class from being copied (As this class contains pointers)
CLWidthConcatenate4TensorsKernel() [3/3]
CLWidthConcatenate4TensorsKernel (CLWidthConcatenate4TensorsKernel &&) default
Allow instances of this class to be moved.
~CLWidthConcatenate4TensorsKernel()
~CLWidthConcatenate4TensorsKernel () default
Default destructor.
Member Function Documentation
configure()
void configure (const ICLTensor * input1, const ICLTensor * input2, const ICLTensor * input3, const ICLTensor * input4, ICLTensor * output)
Initialise the kernel's input1s and output.
Parameters
[in] input1 First input tensor. Data types supported: U8/S8/QASYMM8/U16/S16/F16/U32/S32/F32
[in] input2 Second input tensor. Data types supported: same as input1
[in] input3 Third input tensor. Data types supported: same as input1
[in] input4 Fourth input tensor. Data types supported: same as input1
[out] output Output tensor. Data types supported: Same as input1.
Definition at line 116 of file CLWidthConcatenate4TensorsKernel.cpp.
 {
     ARM_COMPUTE_ERROR_ON_NULLPTR(input1, input2, input3, input4, output);
     ARM_COMPUTE_ERROR_THROW_ON(validate_arguments(input1->info(), input2->info(), input3->info(), input4->info(), output->info()));
     _input1 = input1;
     _input2 = input2;
     _input3 = input3;
     _input4 = input4;
     _output = output;
     // Add build options
     CLBuildOptions build_opts;
     build_opts.add_option("-DDATA_TYPE=" + get_underlying_cl_type_from_data_type(input1->info()->data_type()));
     build_opts.add_option("-DVEC_SIZE=" + support::cpp11::to_string(num_elems_processed_per_iteration));
     build_opts.add_option("-DDEPTH=" + support::cpp11::to_string(input1->info()->dimension(2)));
     build_opts.add_option("-DINPUT1_WIDTH=" + support::cpp11::to_string(input1->info()->dimension(0)));
     build_opts.add_option("-DINPUT2_WIDTH=" + support::cpp11::to_string(input2->info()->dimension(0)));
     build_opts.add_option("-DINPUT3_WIDTH=" + support::cpp11::to_string(input3->info()->dimension(0)));
     build_opts.add_option("-DELEMENT_SIZE=" + support::cpp11::to_string(input1->info()->element_size()));
     // If input have different quantization info set quantization parameters needed for the re-quantization process
     const bool have_different_qinfo = helpers::tensor_info::tensors_have_different_quantization_info(output->info(), input1->info(), input2->info(), input3->info(), input4->info());
     if(is_data_type_quantized_asymmetric(input1->info()->data_type()) && have_different_qinfo)
     {
         build_opts.add_option("-DOFFSET_IN1=" + float_to_string_with_full_precision(input1->info()->quantization_info().offset));
         build_opts.add_option("-DSCALE_IN1=" + float_to_string_with_full_precision(input1->info()->quantization_info().scale));
         build_opts.add_option("-DOFFSET_IN2=" + float_to_string_with_full_precision(input2->info()->quantization_info().offset));
         build_opts.add_option("-DSCALE_IN2=" + float_to_string_with_full_precision(input2->info()->quantization_info().scale));
         build_opts.add_option("-DOFFSET_IN3=" + float_to_string_with_full_precision(input3->info()->quantization_info().offset));
         build_opts.add_option("-DSCALE_IN3=" + float_to_string_with_full_precision(input3->info()->quantization_info().scale));
         build_opts.add_option("-DOFFSET_IN4=" + float_to_string_with_full_precision(input4->info()->quantization_info().offset));
         build_opts.add_option("-DSCALE_IN4=" + float_to_string_with_full_precision(input4->info()->quantization_info().scale));
         build_opts.add_option("-DOFFSET_OUT=" + float_to_string_with_full_precision(output->info()->quantization_info().offset));
         build_opts.add_option("-DSCALE_OUT=" + float_to_string_with_full_precision(output->info()->quantization_info().scale));
     }
     // Create kernel
     _kernel = static_cast<cl::Kernel>(CLKernelLibrary::get().create_kernel("concatenate_width_x4", build_opts.options()));
     // Configure kernel window
     auto win_config = validate_and_configure_window(input1->info(), input2->info(), input3->info(), input4->info(), output->info());
     ARM_COMPUTE_ERROR_THROW_ON(std::get<0>(win_config));
     ICLKernel::configure_internal(std::get<1>(win_config));
     // Pass paddings as arguments to the kernel
     const unsigned int input1_width = input1->info()->dimension(0);
     const unsigned int input2_width = input2->info()->dimension(0);
     const unsigned int input3_width = input3->info()->dimension(0);
     const unsigned int input1_right_padding = ceil_to_multiple(input1_width, num_elems_processed_per_iteration) - input1_width;
     const unsigned int input2_left_padding  = input1_width % num_elems_processed_per_iteration;
     const unsigned int input2_right_padding = ((input1_width + input2_width) / num_elems_processed_per_iteration) * num_elems_processed_per_iteration - input1_width + num_elems_processed_per_iteration -
                                               input2_width;
     const unsigned int input3_left_padding  = (input1_width + input2_width) % num_elems_processed_per_iteration;
     const unsigned int input3_right_padding = ((input1_width + input2_width + input3_width) / num_elems_processed_per_iteration) * num_elems_processed_per_iteration - input1_width - input2_width +
                                               num_elems_processed_per_iteration - input3_width;
     const unsigned int input4_left_padding  = (input1_width + input2_width + input3_width) % num_elems_processed_per_iteration;
     unsigned int       idx0                 = 5 * num_arguments_per_4D_tensor();
     _kernel.setArg<cl_uint>(idx0++, input1_right_padding);
     _kernel.setArg<cl_uint>(idx0++, input2_left_padding);
     _kernel.setArg<cl_uint>(idx0++, input2_right_padding);
     _kernel.setArg<cl_uint>(idx0++, input3_left_padding);
     _kernel.setArg<cl_uint>(idx0++, input3_right_padding);
     _kernel.setArg<cl_uint>(idx0++, input4_left_padding);
     // Set config_id for enabling LWS tuning
     _config_id = "concatenate_width_x4_";
     _config_id += lower_string(string_from_data_type(input1->info()->data_type()));
     _config_id += "_";
     _config_id += support::cpp11::to_string(input1->info()->dimension(0));
     _config_id += "_";
     _config_id += support::cpp11::to_string(input1->info()->dimension(1));
     _config_id += "_";
     _config_id += support::cpp11::to_string(input2->info()->dimension(0));
     _config_id += "_";
     _config_id += support::cpp11::to_string(input2->info()->dimension(1));
     _config_id += "_";
     _config_id += support::cpp11::to_string(input3->info()->dimension(0));
     _config_id += "_";
     _config_id += support::cpp11::to_string(input3->info()->dimension(1));
     _config_id += "_";
     _config_id += support::cpp11::to_string(input4->info()->dimension(0));
     _config_id += "_";
     _config_id += support::cpp11::to_string(input4->info()->dimension(1));
 }
References CLBuildOptions::add_option(), ARM_COMPUTE_ERROR_ON_NULLPTR, ARM_COMPUTE_ERROR_THROW_ON, arm_compute::ceil_to_multiple(), arm_compute::create_kernel(), ITensorInfo::data_type(), ITensorInfo::dimension(), ITensorInfo::element_size(), arm_compute::float_to_string_with_full_precision(), CLKernelLibrary::get(), arm_compute::get_underlying_cl_type_from_data_type(), ITensor::info(), arm_compute::is_data_type_quantized_asymmetric(), arm_compute::lower_string(), ICLKernel::num_arguments_per_4D_tensor(), QuantizationInfo::offset, CLBuildOptions::options(), ITensorInfo::quantization_info(), QuantizationInfo::scale, arm_compute::string_from_data_type(), arm_compute::helpers::tensor_info::tensors_have_different_quantization_info(), and arm_compute::support::cpp11::to_string().
Referenced by CLWidthConcatenateLayer::configure().
operator=() [1/2]
CLWidthConcatenate4TensorsKernel& operator= (const CLWidthConcatenate4TensorsKernel &) delete
Prevent instances of this class from being copied (As this class contains pointers)
operator=() [2/2]
CLWidthConcatenate4TensorsKernel& operator= (CLWidthConcatenate4TensorsKernel &&) default
Allow instances of this class to be moved.
run()
void run (const Window & window, cl::CommandQueue & queue) override virtual
Enqueue the OpenCL kernel to process the given window on the passed OpenCL command queue.
Note
The queue is not flushed by this method, and therefore the kernel will not have been executed by the time this method returns.
Parameters
[in] window Region on which to execute the kernel. (Must be a valid region of the window returned by window()).
[in,out] queue Command queue on which to enqueue the kernel.
Implements ICLKernel.
Definition at line 204 of file CLWidthConcatenate4TensorsKernel.cpp.
 {
     ARM_COMPUTE_ERROR_ON_UNCONFIGURED_KERNEL(this);
     ARM_COMPUTE_ERROR_ON_INVALID_SUBWINDOW(ICLKernel::window(), window);
     Window slice = window.first_slice_window_4D();
     do
     {
         unsigned int idx = 0;
         add_4D_tensor_argument(idx, _input1, slice);
         add_4D_tensor_argument(idx, _input2, slice);
         add_4D_tensor_argument(idx, _input3, slice);
         add_4D_tensor_argument(idx, _input4, slice);
         add_4D_tensor_argument(idx, _output, slice);
         enqueue(queue, *this, window, lws_hint());
     }
     while(window.slide_window_slice_4D(slice));
 }
References ICLKernel::add_4D_tensor_argument(), ARM_COMPUTE_ERROR_ON_INVALID_SUBWINDOW, ARM_COMPUTE_ERROR_ON_UNCONFIGURED_KERNEL, arm_compute::enqueue(), Window::first_slice_window_4D(), ICLKernel::lws_hint(), arm_compute::test::validation::reference::slice(), Window::slide_window_slice_4D(), and IKernel::window().
validate()
Status validate (const ITensorInfo * input1, const ITensorInfo * input2, const ITensorInfo * input3, const ITensorInfo * input4, const ITensorInfo * output) static
Static function to check if given info will lead to a valid configuration of CLWidthConcatenate4TensorsKernel.
Parameters
[in] input1 First tensor info. Data types supported: U8/S8/QASYMM8/U16/S16/F16/U32/S32/F32
[in] input2 Second tensor info. Data types supported: same as input1
[in] input3 Third tensor info. Data types supported: same as input1
[in] input4 Fourth tensor info. Data types supported: same as input1
[in] output Output tensor info. Data types supported: Same as input1.
Returns
a status
Definition at line 109 of file CLWidthConcatenate4TensorsKernel.cpp.
 {
     ARM_COMPUTE_RETURN_ON_ERROR(validate_arguments(input1, input2, input3, input4, output));
     ARM_COMPUTE_RETURN_ON_ERROR(validate_and_configure_window(input1->clone().get(), input2->clone().get(), input3->clone().get(), input4->clone().get(), output->clone().get()).first);
     return Status{};
 }
References ARM_COMPUTE_RETURN_ON_ERROR, and ICloneable< T >::clone().
Referenced by CLConcatenateLayer::validate(), and CLWidthConcatenateLayer::validate().
The documentation for this class was generated from the following files:
arm_compute/core/CL/kernels/CLWidthConcatenate4TensorsKernel.h
src/core/CL/kernels/CLWidthConcatenate4TensorsKernel.cpp