Compute Library: CLMinMaxLocationKernel Class Reference
CLMinMaxLocationKernel Class Reference
Interface for the kernel to find min max locations of an image.
#include <CLMinMaxLocationKernel.h>
Public Member Functions
CLMinMaxLocationKernel ()
Constructor.
CLMinMaxLocationKernel (const CLMinMaxLocationKernel &)=delete
Prevent instances of this class from being copied (As this class contains pointers)
CLMinMaxLocationKernel & operator= (const CLMinMaxLocationKernel &)=delete
Prevent instances of this class from being copied (As this class contains pointers)
CLMinMaxLocationKernel (CLMinMaxLocationKernel &&)=default
Allow instances of this class to be moved.
CLMinMaxLocationKernel & operator= (CLMinMaxLocationKernel &&)=default
Allow instances of this class to be moved.
void configure (const ICLImage *input, cl::Buffer *min_max, cl::Buffer *min_max_count, ICLCoordinates2DArray *min_loc=nullptr, ICLCoordinates2DArray *max_loc=nullptr)
Initialise the kernel's input and outputs.
void run (const Window &window, cl::CommandQueue &queue) override
Enqueue the OpenCL kernel to process the given window on the passed OpenCL command queue.
Public Member Functions inherited from ICLKernel
ICLKernel ()
Constructor.
cl::Kernel & kernel ()
Returns a reference to the OpenCL kernel of this object.
template<typename T >
void add_1D_array_argument (unsigned int &idx, const ICLArray< T > *array, const Strides &strides, unsigned int num_dimensions, const Window &window)
Add the passed 1D array's parameters to the object's kernel's arguments starting from the index idx.
void add_1D_tensor_argument (unsigned int &idx, const ICLTensor *tensor, const Window &window)
Add the passed 1D tensor's parameters to the object's kernel's arguments starting from the index idx.
void add_1D_tensor_argument_if (bool cond, unsigned int &idx, const ICLTensor *tensor, const Window &window)
Add the passed 1D tensor's parameters to the object's kernel's arguments starting from the index idx if the condition is true.
void add_2D_tensor_argument (unsigned int &idx, const ICLTensor *tensor, const Window &window)
Add the passed 2D tensor's parameters to the object's kernel's arguments starting from the index idx.
void add_2D_tensor_argument_if (bool cond, unsigned int &idx, const ICLTensor *tensor, const Window &window)
Add the passed 2D tensor's parameters to the object's kernel's arguments starting from the index idx if the condition is true.
void add_3D_tensor_argument (unsigned int &idx, const ICLTensor *tensor, const Window &window)
Add the passed 3D tensor's parameters to the object's kernel's arguments starting from the index idx.
void add_4D_tensor_argument (unsigned int &idx, const ICLTensor *tensor, const Window &window)
Add the passed 4D tensor's parameters to the object's kernel's arguments starting from the index idx.
template<typename T >
void add_argument (unsigned int &idx, T value)
Add the passed parameters to the object's kernel's arguments starting from the index idx.
void set_lws_hint (const cl::NDRange &lws_hint)
Set the Local-Workgroup-Size hint.
cl::NDRange lws_hint () const
Return the Local-Workgroup-Size hint.
const std::string & config_id () const
Get the configuration ID.
void set_target (GPUTarget target)
Set the targeted GPU architecture.
void set_target (cl::Device &device)
Set the targeted GPU architecture according to the CL device.
GPUTarget get_target () const
Get the targeted GPU architecture.
size_t get_max_workgroup_size ()
Get the maximum workgroup size for the device the CLKernelLibrary uses.
template<typename T , unsigned int dimension_size>
void add_array_argument (unsigned &idx, const ICLArray< T > *array, const Strides &strides, unsigned int num_dimensions, const Window &window)
Add the passed array's parameters to the object's kernel's arguments starting from the index idx.
template<unsigned int dimension_size>
void add_tensor_argument (unsigned &idx, const ICLTensor *tensor, const Window &window)
Public Member Functions inherited from IKernel
IKernel ()
Constructor.
virtual ~IKernel ()=default
Destructor.
virtual bool is_parallelisable () const
Indicates whether or not the kernel is parallelisable.
virtual BorderSize border_size () const
The size of the border for that kernel.
const Window & window () const
The maximum window the kernel can be executed on.
Additional Inherited Members
Static Public Member Functions inherited from ICLKernel
static constexpr unsigned int num_arguments_per_1D_array ()
Returns the number of arguments enqueued per 1D array object.
static constexpr unsigned int num_arguments_per_1D_tensor ()
Returns the number of arguments enqueued per 1D tensor object.
static constexpr unsigned int num_arguments_per_2D_tensor ()
Returns the number of arguments enqueued per 2D tensor object.
static constexpr unsigned int num_arguments_per_3D_tensor ()
Returns the number of arguments enqueued per 3D tensor object.
static constexpr unsigned int num_arguments_per_4D_tensor ()
Returns the number of arguments enqueued per 4D tensor object.
static cl::NDRange gws_from_window (const Window &window)
Get the global work size given an execution window.
Detailed Description
Interface for the kernel to find min max locations of an image.
Definition at line 70 of file CLMinMaxLocationKernel.h.
Constructor & Destructor Documentation
CLMinMaxLocationKernel() [1/3]
CLMinMaxLocationKernel ()
Constructor.
Definition at line 164 of file CLMinMaxLocationKernel.cpp.
     : _input(nullptr), _min_max_count(nullptr)
 {
 }
CLMinMaxLocationKernel() [2/3]
CLMinMaxLocationKernel (const CLMinMaxLocationKernel &) delete
Prevent instances of this class from being copied (As this class contains pointers)
CLMinMaxLocationKernel() [3/3]
CLMinMaxLocationKernel (CLMinMaxLocationKernel &&) default
Allow instances of this class to be moved.
Member Function Documentation
configure()
void configure (const ICLImage * input, cl::Buffer * min_max, cl::Buffer * min_max_count, ICLCoordinates2DArray * min_loc = nullptr, ICLCoordinates2DArray * max_loc = nullptr)
Initialise the kernel's input and outputs.
Note
When locations of min and max occurrences are requested, the reported number of locations is limited to the given array size.
Parameters
[in] input Input image. Data types supported: U8/S16/F32.
[out] min_max Buffer of 2 elements to store the min value at position 0 and the max value at position 1. Data type supported: S32 if input type is U8/S16, F32 if input type is F32.
[out] min_max_count Buffer of 2 elements to store the min value occurrences at position 0 and the max value occurrences at position 1. Data type supported: S32
[out] min_loc (Optional) Array of Coordinates2D used to store minimum value locations.
[out] max_loc (Optional) Array of Coordinates2D used to store maximum value locations.
Definition at line 169 of file CLMinMaxLocationKernel.cpp.
 {
     ARM_COMPUTE_ERROR_ON_DATA_TYPE_CHANNEL_NOT_IN(input, 1, DataType::U8, DataType::S16, DataType::F32);
     ARM_COMPUTE_ERROR_ON_TENSOR_NOT_2D(input);
     ARM_COMPUTE_ERROR_ON(min_max == nullptr);
     ARM_COMPUTE_ERROR_ON(min_max_count == nullptr && min_loc == nullptr && max_loc == nullptr);
     _input         = input;
     _min_max_count = min_max_count;
     // Set kernel build options
     std::set<std::string> build_opts;
     build_opts.emplace("-DDATA_TYPE=" + get_cl_type_from_data_type(input->info()->data_type()));
     build_opts.emplace((min_max_count != nullptr) ? "-DCOUNT_MIN_MAX" : "");
     build_opts.emplace((min_loc != nullptr) ? "-DLOCATE_MIN" : "");
     build_opts.emplace((max_loc != nullptr) ? "-DLOCATE_MAX" : "");
     if(input->info()->data_type() == DataType::F32)
     {
         build_opts.emplace("-DIS_DATA_TYPE_FLOAT");
     }
     // Create kernel
     _kernel = static_cast<cl::Kernel>(CLKernelLibrary::get().create_kernel("minmaxloc", build_opts));
     // Set static arguments
     unsigned int idx = num_arguments_per_2D_tensor(); //Skip the input and output parameters
     _kernel.setArg(idx++, *min_max);
     _kernel.setArg(idx++, *min_max_count);
     if(min_loc != nullptr)
     {
         _kernel.setArg(idx++, min_loc->cl_buffer());
         _kernel.setArg<cl_uint>(idx++, min_loc->max_num_values());
     }
     if(max_loc != nullptr)
     {
         _kernel.setArg(idx++, max_loc->cl_buffer());
         _kernel.setArg<cl_uint>(idx++, max_loc->max_num_values());
     }
     // Configure kernel window
     constexpr unsigned int num_elems_processed_per_iteration = 1;
     Window                 win                               = calculate_max_window(*input->info(), Steps(num_elems_processed_per_iteration));
     update_window_and_padding(win, AccessWindowHorizontal(input->info(), 0, num_elems_processed_per_iteration));
     ICLKernel::configure_internal(win);
 }
References ARM_COMPUTE_ERROR_ON, ARM_COMPUTE_ERROR_ON_DATA_TYPE_CHANNEL_NOT_IN, ARM_COMPUTE_ERROR_ON_TENSOR_NOT_2D, arm_compute::calculate_max_window(), ICLArray< T >::cl_buffer(), arm_compute::create_kernel(), ITensorInfo::data_type(), arm_compute::F32, CLKernelLibrary::get(), arm_compute::get_cl_type_from_data_type(), ITensor::info(), IArray< T >::max_num_values(), ICLKernel::num_arguments_per_2D_tensor(), arm_compute::S16, arm_compute::U8, and arm_compute::update_window_and_padding().
Referenced by CLMinMaxLocation::configure().
operator=() [1/2]
CLMinMaxLocationKernel& operator= (const CLMinMaxLocationKernel &) delete
Prevent instances of this class from being copied (As this class contains pointers)
operator=() [2/2]
CLMinMaxLocationKernel& operator= (CLMinMaxLocationKernel &&) default
Allow instances of this class to be moved.
run()
void run (const Window & window, cl::CommandQueue & queue) override virtual
Enqueue the OpenCL kernel to process the given window on the passed OpenCL command queue.
Note
The queue is not flushed by this method, and therefore the kernel will not have been executed by the time this method returns.
Parameters
[in] window Region on which to execute the kernel. (Must be a valid region of the window returned by window()).
[in,out] queue Command queue on which to enqueue the kernel.
Implements ICLKernel.
Definition at line 215 of file CLMinMaxLocationKernel.cpp.
 {
     ARM_COMPUTE_ERROR_ON_UNCONFIGURED_KERNEL(this);
     ARM_COMPUTE_ERROR_ON_INVALID_SUBWINDOW(IKernel::window(), window);
     static const unsigned int zero_count = 0;
     queue.enqueueWriteBuffer(*_min_max_count, CL_FALSE, 0 * sizeof(zero_count), sizeof(zero_count), &zero_count);
     queue.enqueueWriteBuffer(*_min_max_count, CL_FALSE, 1 * sizeof(zero_count), sizeof(zero_count), &zero_count);
     Window slice = window.first_slice_window_2D();
     do
     {
         unsigned int idx = 0;
         add_2D_tensor_argument(idx, _input, slice);
         enqueue(queue, *this, slice);
     }
     while(window.slide_window_slice_2D(slice));
 }
References ICLKernel::add_2D_tensor_argument(), ARM_COMPUTE_ERROR_ON_INVALID_SUBWINDOW, ARM_COMPUTE_ERROR_ON_UNCONFIGURED_KERNEL, arm_compute::enqueue(), Window::first_slice_window_2D(), arm_compute::test::validation::reference::slice(), Window::slide_window_slice_2D(), and IKernel::window().
The documentation for this class was generated from the following files:
arm_compute/core/CL/kernels/CLMinMaxLocationKernel.h
src/core/CL/kernels/CLMinMaxLocationKernel.cpp