Compute Library: InstrumentsStats Class Reference
InstrumentsStats Class Reference
Generate common statistics for a set of measurements.
#include <InstrumentsStats.h>
Public Member Functions
InstrumentsStats (const std::vector< Measurement > &measurements)
Compute statistics for the passed set of measurements.
const Measurement & min () const
The measurement with the minimum value.
const Measurement & max () const
The measurement with the maximum value.
const Measurement & median () const
The median measurement.
const Measurement::Value & mean () const
The average of all the measurements.
double relative_standard_deviation () const
The relative standard deviation of the measurements.
Detailed Description
Generate common statistics for a set of measurements.
Definition at line 39 of file InstrumentsStats.h.
Constructor & Destructor Documentation
InstrumentsStats()
InstrumentsStats (const std::vector< Measurement > & measurements)
Compute statistics for the passed set of measurements.
Parameters
[in] measurements The measurements to process
Definition at line 33 of file InstrumentsStats.cpp.
     : _min(nullptr), _max(nullptr), _median(nullptr), _mean(measurements.begin()->value().is_floating_point), _stddev(0.0)
 {
     auto add_measurements = [](Measurement::Value a, const Measurement & b)
     {
         return a + b.value();
     };
     //Calculate min, max & median values
     auto indices = arm_compute::utility::sort_indices(measurements);
     _median      = &measurements[indices[measurements.size() / 2]];
     _min         = &measurements[indices[0]];
     _max         = &measurements[indices[measurements.size() - 1]];
     Measurement::Value sum_values = std::accumulate(measurements.begin(), measurements.end(), Measurement::Value(_min->value().is_floating_point), add_measurements);
     // Calculate the relative standard deviation
     _mean = sum_values / measurements.size();
     std::vector<Measurement::Value> diff(measurements.size(), _min->value().is_floating_point);
     std::transform(measurements.begin(), measurements.end(), diff.begin(), [&](const Measurement & x)
     {
         return x.value() - _mean;
     });
     auto sq_sum   = std::inner_product(diff.begin(), diff.end(), diff.begin(), Measurement::Value(_min->value().is_floating_point));
     auto variance = sq_sum / measurements.size();
     _stddev       = Measurement::Value::relative_standard_deviation(variance, _mean);
 }
Member Function Documentation
max()
const Measurement& max () const inline
The measurement with the maximum value.
Definition at line 55 of file InstrumentsStats.h.
     {
         return *_max;
     }
Referenced by PrettyPrinter::print_measurements().
mean()
const Measurement::Value& mean () const inline
The average of all the measurements.
Definition at line 67 of file InstrumentsStats.h.
     {
         return _mean;
     }
Referenced by PrettyPrinter::print_measurements().
median()
const Measurement& median () const inline
The median measurement.
Definition at line 61 of file InstrumentsStats.h.
     {
         return *_median;
     }
Referenced by PrettyPrinter::print_measurements().
min()
const Measurement& min () const inline
The measurement with the minimum value.
Definition at line 49 of file InstrumentsStats.h.
     {
         return *_min;
     }
Referenced by PrettyPrinter::print_measurements().
relative_standard_deviation()
double relative_standard_deviation () const inline
The relative standard deviation of the measurements.
Definition at line 73 of file InstrumentsStats.h.
     {
         return _stddev;
     }
Referenced by PrettyPrinter::print_measurements().
The documentation for this class was generated from the following files:
tests/framework/instruments/InstrumentsStats.h
tests/framework/instruments/InstrumentsStats.cpp