Compute Library: CLIntegralImage Class Reference
CLIntegralImage Class Reference
Basic function to execute integral image.
#include <CLIntegralImage.h>
Public Member Functions
CLIntegralImage ()
Default Constructor.
void configure (const ICLTensor *input, ICLTensor *output)
Initialise the function's source, destinations and border mode.
void run () override
Run the kernels contained in the function.
Public Member Functions inherited from IFunction
virtual ~IFunction ()=default
Destructor.
virtual void prepare ()
Prepare the function for executing.
Detailed Description
Basic function to execute integral image.
This function calls the following OpenCL kernels:
CLIntegralImageHorKernel
CLIntegralImageVertKernel
Definition at line 40 of file CLIntegralImage.h.
Constructor & Destructor Documentation
CLIntegralImage()
CLIntegralImage ()
Default Constructor.
Definition at line 31 of file CLIntegralImage.cpp.
     : _integral_hor(), _integral_vert()
 {
 }
Member Function Documentation
configure()
void configure (const ICLTensor * input, ICLTensor * output)
Initialise the function's source, destinations and border mode.
Parameters
[in] input Source tensor. Data types supported: U8.
[out] output Destination tensor, Data types supported: U32.
Definition at line 36 of file CLIntegralImage.cpp.
 {
     _integral_hor.configure(input, output);
     _integral_vert.configure(output);
 }
References CLIntegralImageHorKernel::configure(), and CLIntegralImageVertKernel::configure().
run()
void run () override virtual
Run the kernels contained in the function.
For NEON kernels:
Multi-threading is used for the kernels which are parallelisable.
By default std::thread::hardware_concurrency() threads are used.
Note
CPPScheduler::set_num_threads() can be used to manually set the number of threads
For OpenCL kernels:
All the kernels are enqueued on the queue associated with CLScheduler.
The queue is then flushed.
Note
The function will not block until the kernels are executed. It is the user's responsibility to wait.
Will call prepare() on first run if hasn't been done
Implements IFunction.
Definition at line 42 of file CLIntegralImage.cpp.
 {
     CLScheduler::get().enqueue(_integral_hor, false);
     CLScheduler::get().enqueue(_integral_vert);
 }
References CLScheduler::enqueue(), and CLScheduler::get().
The documentation for this class was generated from the following files:
arm_compute/runtime/CL/functions/CLIntegralImage.h
src/runtime/CL/functions/CLIntegralImage.cpp