Compute Library: NEGEMMLowpMatrixMultiplyKernel Class Reference
NEGEMMLowpMatrixMultiplyKernel Class Reference
NEON kernel to multiply matrices.
#include <NEGEMMLowpMatrixMultiplyKernel.h>
Public Member Functions
const char * name () const override
Name of the kernel.
NEGEMMLowpMatrixMultiplyKernel ()
Constructor.
NEGEMMLowpMatrixMultiplyKernel (const NEGEMMLowpMatrixMultiplyKernel &)=delete
Prevent instances of this class from being copied (As this class contains pointers)
NEGEMMLowpMatrixMultiplyKernel & operator= (const NEGEMMLowpMatrixMultiplyKernel &)=delete
Prevent instances of this class from being copied (As this class contains pointers)
NEGEMMLowpMatrixMultiplyKernel (NEGEMMLowpMatrixMultiplyKernel &&)=default
Allow instances of this class to be moved.
NEGEMMLowpMatrixMultiplyKernel & operator= (NEGEMMLowpMatrixMultiplyKernel &&)=default
Allow instances of this class to be moved.
void configure (const ITensor *input0, const ITensor *input1, ITensor *output)
Initialise the kernel's input and output.
void run (const Window &window, const ThreadInfo &info) override
Execute the kernel on the passed window.
Public Member Functions inherited from ICPPKernel
virtual ~ICPPKernel ()=default
Default destructor.
Public Member Functions inherited from IKernel
IKernel ()
Constructor.
virtual ~IKernel ()=default
Destructor.
virtual bool is_parallelisable () const
Indicates whether or not the kernel is parallelisable.
virtual BorderSize border_size () const
The size of the border for that kernel.
const Window & window () const
The maximum window the kernel can be executed on.
Static Public Member Functions
static Status validate (const ITensorInfo *input0, const ITensorInfo *input1, const ITensorInfo *output)
Static function to check if given info will lead to a valid configuration of NEGEMMLowpMatrixMultiplyKernel.
Detailed Description
NEON kernel to multiply matrices.
Note
NEGEMMLowpMatrixMultiplyKernel low precision matrix product kernel This kernel performs the following computation:
Convert a values from int8 to int32
Convert b values from int8 to int32
Compute the int32 matrix product of the resulting a * b and store the result as int32
Definition at line 43 of file NEGEMMLowpMatrixMultiplyKernel.h.
Constructor & Destructor Documentation
NEGEMMLowpMatrixMultiplyKernel() [1/3]
NEGEMMLowpMatrixMultiplyKernel ()
Constructor.
Definition at line 797 of file NEGEMMLowpMatrixMultiplyKernel.cpp.
     : _input0(nullptr), _input1(nullptr), _output(nullptr), _slide_matrix_b(true)
 {
 }
NEGEMMLowpMatrixMultiplyKernel() [2/3]
NEGEMMLowpMatrixMultiplyKernel (const NEGEMMLowpMatrixMultiplyKernel &) delete
Prevent instances of this class from being copied (As this class contains pointers)
NEGEMMLowpMatrixMultiplyKernel() [3/3]
NEGEMMLowpMatrixMultiplyKernel (NEGEMMLowpMatrixMultiplyKernel &&) default
Allow instances of this class to be moved.
Member Function Documentation
configure()
void configure (const ITensor * input0, const ITensor * input1, ITensor * output)
Initialise the kernel's input and output.
The input matrices input0 and input1 must be the output of the kernels: NEGEMMInterleave4x4Kernel and NEGEMMTranspose1xWKernel. These two kernels change the layout of the original matrices to be more cache-friendly.
Parameters
[in] input0 Input tensor containing the interleaved Matrix A. Data type supported: QASYMM8
[in] input1 Input tensor containing the transposed1xW Matrix B. Data type supported: same as input0
[out] output Output tensor to store the result of matrix multiplication. Data type supported: S32
Definition at line 802 of file NEGEMMLowpMatrixMultiplyKernel.cpp.
 {
     ARM_COMPUTE_ERROR_ON_NULLPTR(input0, input1, output);
     ARM_COMPUTE_ERROR_THROW_ON(validate_arguments(input0->info(), input1->info(), output->info()));
     TensorShape in1_shape = input1->info()->tensor_shape();
     in1_shape.collapse(2);
     _input0         = input0;
     _input1         = input1;
     _output         = output;
     _slide_matrix_b = in1_shape[2] != 1;
     // Configure kernel window
     auto win_config = validate_and_configure_window(input0->info(), input1->info(), output->info());
     ARM_COMPUTE_ERROR_THROW_ON(win_config.first);
     INEKernel::configure(win_config.second);
 }
References ARM_COMPUTE_ERROR_ON_NULLPTR, ARM_COMPUTE_ERROR_THROW_ON, TensorShape::collapse(), ITensor::info(), and ITensorInfo::tensor_shape().
name()
const char* name () const inline override virtual
Name of the kernel.
Returns
Kernel name
Implements ICPPKernel.
Definition at line 46 of file NEGEMMLowpMatrixMultiplyKernel.h.
     {
         return "NEGEMMLowpMatrixMultiplyKernel";
     }
operator=() [1/2]
NEGEMMLowpMatrixMultiplyKernel& operator= (const NEGEMMLowpMatrixMultiplyKernel &) delete
Prevent instances of this class from being copied (As this class contains pointers)
operator=() [2/2]
NEGEMMLowpMatrixMultiplyKernel& operator= (NEGEMMLowpMatrixMultiplyKernel &&) default
Allow instances of this class to be moved.
run()
void run (const Window & window, const ThreadInfo & info) override virtual
Execute the kernel on the passed window.
Warning
If is_parallelisable() returns false then the passed window must be equal to window()
Note
The window has to be a region within the window returned by the window() method
The width of the window has to be a multiple of num_elems_processed_per_iteration().
Parameters
[in] window Region on which to execute the kernel. (Must be a region of the window returned by window())
[in] info Info about executing thread and CPU.
Implements ICPPKernel.
Definition at line 829 of file NEGEMMLowpMatrixMultiplyKernel.cpp.
 {
     ARM_COMPUTE_UNUSED(info);
     ARM_COMPUTE_ERROR_ON_UNCONFIGURED_KERNEL(this);
     ARM_COMPUTE_ERROR_ON_INVALID_SUBWINDOW(INEKernel::window(), window);
     // Check if the output tensor is a vector. If so,the kernel runs the vector-matrix multiplication path
     if((_output->info()->dimension(1) == 1))
     {
         const auto width_matrix_a = static_cast<int>(_input0->info()->dimension(0));
         const auto width_matrix_b = static_cast<int>(_input1->info()->dimension(0));
         const auto in_b_stride    = static_cast<int>(_input1->info()->strides_in_bytes()[1] / data_size_from_type(_input1->info()->data_type()));
         // The implementation computes 16 elements per iteration
         const int window_start_x = 16 * info.thread_id;
         const int window_step_x  = 16 * info.num_threads;
         // Make sure (window_end_x - window_start_x) is a multiple of window_step_x
         const int window_end_x = ceil_to_multiple(width_matrix_b - window_start_x, window_step_x) + window_start_x;
         Window win_out(window);
         win_out.set(Window::DimX, Window::Dimension(window_start_x, window_end_x, window_step_x));
         win_out.set(Window::DimY, Window::Dimension(0, 1, 1));
         Window win_a(window);
         win_a.set(Window::DimX, Window::Dimension(0, 0, 0));
         win_a.set(Window::DimY, Window::Dimension(0, 0, 0));
         Window win_b;
         // Don't slice matrix B along the z dimension if matrix B has just 2 dimensions and matrix A more than 2
         // This scenario can happen when the the matrix multiplication is used to perform a convolution operation
         if(_input1->info()->num_dimensions() >= 3)
         {
             win_b = window;
         }
         win_b.set(Window::DimX, Window::Dimension(window_start_x, window_end_x, window_step_x));
         win_b.set(Window::DimY, Window::Dimension(0, 1, 1));
         Iterator ina(_input0, win_a);
         Iterator inb(_input1, win_b);
         Iterator out(_output, win_out);
         switch(_input0->info()->data_type())
         {
             case DataType::S8:
             {
                 vector_matrix_multiply_s8(ina, inb, out, width_matrix_a, width_matrix_b, in_b_stride, window);
                 break;
             }
             case DataType::U8:
             case DataType::QASYMM8:
             {
                 vector_matrix_multiply_u8(ina, inb, out, width_matrix_a, width_matrix_b, in_b_stride, window);
                 break;
             }
             default:
             {
                 ARM_COMPUTE_ERROR("Not supported");
                 break;
             }
         }
     }
     else
     {
         const size_t in_b_stride = _input1->info()->strides_in_bytes()[1];
         const size_t out_stride  = _output->info()->strides_in_bytes()[1] / _output->info()->element_size();
         // Set step_x and step_y for matrix A. Scale by a factor of 4 the Y range as the input interleaved matrix A has 4 times less the rows of the output matrix
         Window win_a(window);
         win_a.set(Window::DimX, Window::Dimension(0, 0, 0));
         win_a.set(Window::DimY, Window::Dimension(window.y().start() / 4, window.y().end() / 4, 1));
         // Set step_x and step_y for matrix B. Scale by a factor of 16 the X range as the input transposed matrix A has 16 times less the columns of the output matrix
         Window win_b;
         // Don't slice matrix B along the z dimension if matrix B has just 2 dimensions and matrix A more than 2
         // This scenario can happen when the the matrix multiplication is used to perform a convolution operation
         if(_slide_matrix_b)
         {
             win_b = window;
         }
         win_b.set(Window::DimX, Window::Dimension(window.x().start() / 16, window.x().end() / 16, in_b_stride));
         win_b.set(Window::DimY, Window::Dimension(0, 0, 0));
         // The step x and step y for the output matrix has been already set using in configure()
         Iterator ina(_input0, win_a);
         Iterator inb(_input1, win_b);
         Iterator out(_output, window);
         const int width_b = _input1->info()->dimension(0);
         switch(_input0->info()->data_type())
         {
             case DataType::S8:
             {
                 matrix_multiply_s8(ina, inb, out, width_b, out_stride, window);
                 break;
             }
             case DataType::U8:
             case DataType::QASYMM8:
             {
                 matrix_multiply_u8(ina, inb, out, width_b, out_stride, window);
                 break;
             }
             default:
             {
                 ARM_COMPUTE_ERROR("Not supported");
                 break;
             }
         }
     }
 }
References ARM_COMPUTE_ERROR, ARM_COMPUTE_ERROR_ON_INVALID_SUBWINDOW, ARM_COMPUTE_ERROR_ON_UNCONFIGURED_KERNEL, ARM_COMPUTE_UNUSED, arm_compute::ceil_to_multiple(), arm_compute::data_size_from_type(), ITensorInfo::data_type(), ITensorInfo::dimension(), Window::DimX, Window::DimY, ITensorInfo::element_size(), Window::Dimension::end(), ITensor::info(), arm_compute::test::validation::info, ITensorInfo::num_dimensions(), arm_compute::QASYMM8, arm_compute::S8, Window::set(), Window::Dimension::start(), ITensorInfo::strides_in_bytes(), arm_compute::U8, IKernel::window(), Window::x(), and Window::y().
validate()
Status validate (const ITensorInfo * input0, const ITensorInfo * input1, const ITensorInfo * output) static
Static function to check if given info will lead to a valid configuration of NEGEMMLowpMatrixMultiplyKernel.
Parameters
[in] input0 Input tensor info containing the interleaved Matrix A. Data type supported: QASYMM8
[in] input1 Input tensor info containing the transposed Matrix B. Data type supported: same as input0
[in] output Output tensor info to store the result of matrix multiplication. Data type supported: S32
Returns
a status
Definition at line 821 of file NEGEMMLowpMatrixMultiplyKernel.cpp.
 {
     ARM_COMPUTE_RETURN_ON_ERROR(validate_arguments(input0, input1, output));
     ARM_COMPUTE_RETURN_ON_ERROR(validate_and_configure_window(input0->clone().get(), input1->clone().get(), output->clone().get()).first);
     return Status{};
 }
References ARM_COMPUTE_RETURN_ON_ERROR, and ICloneable< T >::clone().
Referenced by NEGEMMLowpMatrixMultiplyCore::validate().
The documentation for this class was generated from the following files:
arm_compute/core/NEON/kernels/NEGEMMLowpMatrixMultiplyKernel.h
src/core/NEON/kernels/NEGEMMLowpMatrixMultiplyKernel.cpp