Compute Library: NEReduceMean Class Reference
NEReduceMean Class Reference
Basic function to perform reduce operation.
#include <NEReduceMean.h>
Public Member Functions
NEReduceMean (std::shared_ptr< IMemoryManager > memory_manager=nullptr)
Constructor.
void configure (ITensor *input, const Coordinates &reduction_axis, bool keep_dims, ITensor *output)
Configure kernel.
void run () override
Run the kernels contained in the function.
Public Member Functions inherited from IFunction
virtual ~IFunction ()=default
Destructor.
virtual void prepare ()
Prepare the function for executing.
Static Public Member Functions
static Status validate (const ITensorInfo *input, const Coordinates &reduction_axis, bool keep_dims, const ITensorInfo *output)
Static function to check if given info will lead to a valid configuration of NEReduceMean.
Detailed Description
Basic function to perform reduce operation.
Definition at line 40 of file NEReduceMean.h.
Constructor & Destructor Documentation
NEReduceMean()
NEReduceMean (std::shared_ptr< IMemoryManager > memory_manager = nullptr)
Constructor.
Definition at line 31 of file NEReduceMean.cpp.
     : _memory_group(std::move(memory_manager)), _reduction_kernels(), _reduced_outs(), _reshape(), _reduction_ops(), _keep_dims()
 {
 }
Member Function Documentation
configure()
void configure (ITensor * input, const Coordinates & reduction_axis, bool keep_dims, ITensor * output)
Configure kernel.
Note
Supported tensor rank: up to 4
Parameters
[in] input Source tensor. Data type supported: QASYMM8/F16/F32
[in] reduction_axis Reduction axis vector.
[in] keep_dims If positive, retains reduced dimensions with length 1.
[out] output Destination tensor. Data type supported: Same as input
Definition at line 77 of file NEReduceMean.cpp.
 {
     ARM_COMPUTE_ERROR_ON_NULLPTR(input);
     _reduction_ops     = reduction_axis.num_dimensions();
     _reduction_kernels = arm_compute::support::cpp14::make_unique<NEReductionOperation[]>(_reduction_ops);
     _reduced_outs      = arm_compute::support::cpp14::make_unique<Tensor[]>(_reduction_ops - (keep_dims ? 1 : 0));
     _keep_dims         = keep_dims;
     Coordinates        axis_local    = reduction_axis;
     const int          input_dims    = input->info()->num_dimensions();
     const unsigned int reduction_ops = reduction_axis.num_dimensions();
     // Convert negative axis
     for(unsigned int i = 0; i < reduction_ops; ++i)
     {
         axis_local[i] = wrap_around(axis_local[i], input_dims);
     }
     // Perform reduction for every axis
     for(unsigned int i = 0; i < _reduction_ops; ++i)
     {
         TensorShape out_shape = i == 0 ? input->info()->tensor_shape() : (_reduced_outs.get() + i - 1)->info()->tensor_shape();
         out_shape.set(axis_local[i], 1);
         auto in = (i == 0) ? input : (_reduced_outs.get() + i - 1);
         if(i == _reduction_ops - 1 && keep_dims)
         {
             _reduction_kernels[i].configure(in, output, axis_local[i], ReductionOperation::MEAN_SUM);
         }
         else
         {
             _reduced_outs[i].allocator()->init(TensorInfo(out_shape, input->info()->num_channels(), input->info()->data_type(), input->info()->quantization_info()));
             _memory_group.manage(_reduced_outs.get() + i);
             _reduction_kernels[i].configure(in, _reduced_outs.get() + i, axis_local[i], ReductionOperation::MEAN_SUM);
         }
     }
     // Allocate intermediate tensors
     for(unsigned int i = 0; i < _reduction_ops - (keep_dims ? 1 : 0); ++i)
     {
         _reduced_outs[i].allocator()->allocate();
     }
     // Configure reshape layer if we want to drop the dimensions
     if(!keep_dims)
     {
         TensorShape out_shape = input->info()->tensor_shape();
         // We have to sort the reduction axis vectors in order for remove_dimension
         // to work properly
         std::sort(axis_local.begin(), axis_local.begin() + _reduction_ops);
         for(unsigned int i = 0; i < _reduction_ops; ++i)
         {
             out_shape.remove_dimension(axis_local[i] - i);
         }
         auto_init_if_empty(*output->info(), input->info()->clone()->set_tensor_shape(out_shape));
         _reshape.configure(_reduced_outs.get() + _reduction_ops - 1, output);
     }
 }
References ARM_COMPUTE_ERROR_ON_NULLPTR, arm_compute::auto_init_if_empty(), Dimensions< T >::begin(), ICloneable< T >::clone(), NEReshapeLayer::configure(), ITensorInfo::data_type(), ITensor::info(), arm_compute::test::validation::info, MemoryGroupBase< TensorType >::manage(), arm_compute::MEAN_SUM, ITensorInfo::num_channels(), Dimensions< T >::num_dimensions(), ITensorInfo::num_dimensions(), ITensorInfo::quantization_info(), TensorShape::remove_dimension(), TensorShape::set(), ITensorInfo::tensor_shape(), and arm_compute::wrap_around().
run()
void run () override virtual
Run the kernels contained in the function.
For NEON kernels:
Multi-threading is used for the kernels which are parallelisable.
By default std::thread::hardware_concurrency() threads are used.
Note
CPPScheduler::set_num_threads() can be used to manually set the number of threads
For OpenCL kernels:
All the kernels are enqueued on the queue associated with CLScheduler.
The queue is then flushed.
Note
The function will not block until the kernels are executed. It is the user's responsibility to wait.
Will call prepare() on first run if hasn't been done
Implements IFunction.
Definition at line 138 of file NEReduceMean.cpp.
 {
     _memory_group.acquire();
     for(unsigned int i = 0; i < _reduction_ops; ++i)
     {
         _reduction_kernels[i].run();
     }
     if(!_keep_dims)
     {
         _reshape.run();
     }
     _memory_group.release();
 }
References MemoryGroupBase< TensorType >::acquire(), MemoryGroupBase< TensorType >::release(), and INESimpleFunctionNoBorder::run().
validate()
Status validate (const ITensorInfo * input, const Coordinates & reduction_axis, bool keep_dims, const ITensorInfo * output) static
Static function to check if given info will lead to a valid configuration of NEReduceMean.
Parameters
[in] input Source tensor. Data type supported: QASYMM8/F16/F32
[in] reduction_axis Reduction axis vector.
[in] keep_dims If positive, retains reduced dimensions with length 1.
[in] output Destination tensor. Data type supported: Same as input
Returns
A status
Definition at line 36 of file NEReduceMean.cpp.
 {
     ARM_COMPUTE_UNUSED(keep_dims);
     ARM_COMPUTE_RETURN_ERROR_ON_NULLPTR(input);
     ARM_COMPUTE_RETURN_ERROR_ON(reduction_axis.num_dimensions() > input->num_dimensions());
     TensorShape        out_shape     = input->tensor_shape();
     const unsigned int reduction_ops = reduction_axis.num_dimensions();
     const int          input_dims    = input->num_dimensions();
     Coordinates        axis_local    = reduction_axis;
     // Convert negative axis
     for(unsigned int i = 0; i < reduction_ops; ++i)
     {
         axis_local[i] = wrap_around(axis_local[i], input_dims);
     }
     std::sort(axis_local.begin(), axis_local.begin() + reduction_ops);
     for(unsigned int i = 0; i < reduction_ops; ++i)
     {
         ARM_COMPUTE_RETURN_ERROR_ON(axis_local[i] > 3);
         ARM_COMPUTE_RETURN_ERROR_ON(static_cast<unsigned int>(axis_local[i]) > input->num_dimensions() - 1);
         if(output->total_size() > 0 && keep_dims)
         {
             ARM_COMPUTE_RETURN_ERROR_ON(output->dimension(axis_local[i]) != 1);
         }
         if(keep_dims)
         {
             out_shape.set(axis_local[i], 1);
         }
         else
         {
             out_shape.remove_dimension(axis_local[i] - i);
         }
     }
     const TensorInfo out_info = input->clone()->set_tensor_shape(out_shape);
     ARM_COMPUTE_RETURN_ERROR_ON_MISMATCHING_SHAPES(output, &out_info);
     return Status{};
 }
References ARM_COMPUTE_RETURN_ERROR_ON, ARM_COMPUTE_RETURN_ERROR_ON_MISMATCHING_SHAPES, ARM_COMPUTE_RETURN_ERROR_ON_NULLPTR, ARM_COMPUTE_UNUSED, Dimensions< T >::begin(), ICloneable< T >::clone(), ITensorInfo::dimension(), Dimensions< T >::num_dimensions(), ITensorInfo::num_dimensions(), ITensorInfo::tensor_shape(), ITensorInfo::total_size(), and arm_compute::wrap_around().
The documentation for this class was generated from the following files:
arm_compute/runtime/NEON/functions/NEReduceMean.h
src/runtime/NEON/functions/NEReduceMean.cpp