Compute Library: GCBufferMemoryRegion Class Reference
GCBufferMemoryRegion Class Reference final
GLES buffer memory region implementation.
#include <GCMemoryRegion.h>
Public Member Functions
GCBufferMemoryRegion (size_t size)
Constructor.
~GCBufferMemoryRegion ()
Destructor.
void * ptr () final
Host/SVM pointer accessor.
void * map (bool blocking) final
Enqueue a map operation of the allocated buffer on the given queue.
void unmap () final
Enqueue an unmap operation of the allocated buffer on the given queue.
std::unique_ptr< IMemoryRegion > extract_subregion (size_t offset, size_t size) final
Extract a sub-region from the memory.
Public Member Functions inherited from IGCMemoryRegion
IGCMemoryRegion (size_t size)
Constructor.
virtual ~IGCMemoryRegion ()=default
Default Destructor.
IGCMemoryRegion (const IGCMemoryRegion &)=delete
Prevent instances of this class from being copied (As this class contains pointers)
IGCMemoryRegion (IGCMemoryRegion &&)=default
Default move constructor.
IGCMemoryRegion & operator= (const IGCMemoryRegion &)=delete
Prevent instances of this class from being copied (As this class contains pointers)
IGCMemoryRegion & operator= (IGCMemoryRegion &&)=default
Default move assignment operator.
const GLuint & gc_ssbo_name () const
Returns the underlying CL buffer.
void * buffer () override
Returns the pointer to the allocated data.
void * buffer () const override
Returns the pointer to the allocated data.
Public Member Functions inherited from IMemoryRegion
IMemoryRegion (size_t size)
Default constructor.
virtual ~IMemoryRegion ()=default
Virtual Destructor.
size_t size () const
Memory region size accessor.
void set_size (size_t size)
Sets size of region.
Detailed Description
GLES buffer memory region implementation.
Definition at line 90 of file GCMemoryRegion.h.
Constructor & Destructor Documentation
GCBufferMemoryRegion()
GCBufferMemoryRegion (size_t size)
Constructor.
Parameters
[in] size Region size
Definition at line 50 of file GCMemoryRegion.cpp.
     : IGCMemoryRegion(size)
 {
     ARM_COMPUTE_GL_CHECK(glGenBuffers(1, &_ssbo_name));
     ARM_COMPUTE_GL_CHECK(glBindBuffer(GL_SHADER_STORAGE_BUFFER, _ssbo_name));
     ARM_COMPUTE_GL_CHECK(glBufferData(GL_SHADER_STORAGE_BUFFER, static_cast<GLsizeiptr>(size), nullptr, GL_STATIC_DRAW));
     ARM_COMPUTE_GL_CHECK(glBindBuffer(GL_SHADER_STORAGE_BUFFER, 0));
 }
References ARM_COMPUTE_GL_CHECK, glBindBuffer(), glBufferData(), glGenBuffers(), and IMemoryRegion::size().
~GCBufferMemoryRegion()
~GCBufferMemoryRegion ()
Destructor.
Definition at line 59 of file GCMemoryRegion.cpp.
 {
     ARM_COMPUTE_GL_CHECK(glDeleteBuffers(1, &_ssbo_name));
 }
References ARM_COMPUTE_GL_CHECK, and glDeleteBuffers().
Member Function Documentation
extract_subregion()
std::unique_ptr< IMemoryRegion > extract_subregion (size_t offset, size_t size) final virtual
Extract a sub-region from the memory.
Warning
Ownership is maintained by the parent memory, while a wrapped raw memory region is returned by this function. Thus parent memory should not be released before this.
Parameters
[in] offset Offset to the region
[in] size Size of the region
Returns
A wrapped memory sub-region with no ownership of the underlying memory
Implements IMemoryRegion.
Definition at line 91 of file GCMemoryRegion.cpp.
 {
     ARM_COMPUTE_UNUSED(offset, size);
     return nullptr;
 }
References ARM_COMPUTE_UNUSED, offset(), and IMemoryRegion::size().
map()
void * map (bool blocking) final virtual
Enqueue a map operation of the allocated buffer on the given queue.
Parameters
[in] blocking If true, then the mapping will be ready to use by the time this method returns, else it is the caller's responsibility to flush the queue and wait for the mapping operation to have completed before using the returned mapping pointer.
Returns
The mapping address.
Implements IGCMemoryRegion.
Definition at line 69 of file GCMemoryRegion.cpp.
 {
     ARM_COMPUTE_ERROR_ON(_mapping != nullptr);
     ARM_COMPUTE_UNUSED(blocking);
     ARM_COMPUTE_GL_CHECK(glBindBuffer(GL_SHADER_STORAGE_BUFFER, _ssbo_name));
     void *p  = ARM_COMPUTE_GL_CHECK(glMapBufferRange(GL_SHADER_STORAGE_BUFFER, 0, static_cast<GLsizeiptr>(size()), GL_MAP_READ_BIT | GL_MAP_WRITE_BIT));
     _mapping = reinterpret_cast<uint8_t *>(p);
     return _mapping;
 }
References ARM_COMPUTE_ERROR_ON, ARM_COMPUTE_GL_CHECK, ARM_COMPUTE_UNUSED, glBindBuffer(), glMapBufferRange(), and IMemoryRegion::size().
ptr()
void * ptr () final virtual
Host/SVM pointer accessor.
Returns
Host/SVM pointer base
Implements IGCMemoryRegion.
Definition at line 64 of file GCMemoryRegion.cpp.
 {
     return nullptr;
 }
unmap()
void unmap () final virtual
Enqueue an unmap operation of the allocated buffer on the given queue.
Note
This method simply enqueue the unmap operation, it is the caller's responsibility to flush the queue and make sure the unmap is finished before the memory is accessed by the device.
Implements IGCMemoryRegion.
Definition at line 81 of file GCMemoryRegion.cpp.
 {
     ARM_COMPUTE_ERROR_ON(_mapping == nullptr);
     ARM_COMPUTE_GL_CHECK(glBindBuffer(GL_SHADER_STORAGE_BUFFER, _ssbo_name));
     ARM_COMPUTE_GL_CHECK(glUnmapBuffer(GL_SHADER_STORAGE_BUFFER));
     ARM_COMPUTE_GL_CHECK(glBindBuffer(GL_SHADER_STORAGE_BUFFER, 0));
     _mapping = nullptr;
 }
References ARM_COMPUTE_ERROR_ON, ARM_COMPUTE_GL_CHECK, glBindBuffer(), and glUnmapBuffer().
The documentation for this class was generated from the following files:
arm_compute/runtime/GLES_COMPUTE/GCMemoryRegion.h
src/runtime/GLES_COMPUTE/GCMemoryRegion.cpp