Compute Library: SchedulerClock< output_timestamps > Class Template Reference
SchedulerClock< output_timestamps > Class Template Reference
Instrument creating measurements based on the information returned by clGetEventProfilingInfo for each OpenCL kernel executed.
#include <SchedulerTimer.h>
Data Structures
struct kernel_info
Kernel information.
Public Member Functions
SchedulerClock (ScaleFactor scale_factor)
Construct a Scheduler timer.
SchedulerClock (const SchedulerClock &)=delete
Prevent instances of this class from being copy constructed.
SchedulerClock & operator= (const SchedulerClock &)=delete
Prevent instances of this class from being copied.
SchedulerClock & operator= (SchedulerClock &&)=default
Use the default move assignment operator.
SchedulerClock (SchedulerClock &&)=default
Use the default move constructor.
~SchedulerClock ()=default
Use the default destructor.
std::string id () const override
Identifier for the instrument.
void test_start () override
Start of the test.
void start () override
Start measuring.
void test_stop () override
End of the test.
Instrument::MeasurementsMap measurements () const override
Return the latest measurements.
Public Member Functions inherited from Instrument
Instrument ()=default
Default constructor.
Instrument (const Instrument &)=default
Allow instances of this class to be copy constructed.
Instrument (Instrument &&)=default
Allow instances of this class to be move constructed.
Instrument & operator= (const Instrument &)=default
Allow instances of this class to be copied.
Instrument & operator= (Instrument &&)=default
Allow instances of this class to be moved.
virtual ~Instrument ()=default
Default destructor.
virtual void stop ()
Stop measuring.
virtual MeasurementsMap test_measurements () const
Return the latest test measurements.
Additional Inherited Members
Public Types inherited from Instrument
using MeasurementsMap = std::map< std::string, Measurement >
Map of measurements.
Static Public Member Functions inherited from Instrument
template<typename T , ScaleFactor scale>
static std::unique_ptr< Instrument > make_instrument ()
Helper function to create an instrument of the given type.
Detailed Description
template<bool output_timestamps>
class arm_compute::test::framework::SchedulerClock< output_timestamps >
Instrument creating measurements based on the information returned by clGetEventProfilingInfo for each OpenCL kernel executed.
Definition at line 41 of file SchedulerTimer.h.
Constructor & Destructor Documentation
SchedulerClock() [1/3]
SchedulerClock (ScaleFactor scale_factor)
Construct a Scheduler timer.
Parameters
[in] scale_factor Measurement scale factor.
Definition at line 116 of file SchedulerTimer.cpp.
     : _kernels(), _real_scheduler(nullptr), _real_scheduler_type(), _real_graph_function(nullptr), _scale_factor(scale_factor), _interceptor(nullptr)
 {
 }
SchedulerClock() [2/3]
SchedulerClock (const SchedulerClock< output_timestamps > &) delete
Prevent instances of this class from being copy constructed.
SchedulerClock() [3/3]
SchedulerClock (SchedulerClock< output_timestamps > &&) default
Use the default move constructor.
~SchedulerClock()
~SchedulerClock () default
Use the default destructor.
Member Function Documentation
id()
std::string id () const override virtual
Identifier for the instrument.
Implements Instrument.
Definition at line 38 of file SchedulerTimer.cpp.
 {
     if(output_timestamps)
     {
         return "SchedulerTimestamps";
     }
     else
     {
         return "SchedulerTimer";
     }
 }
measurements()
Instrument::MeasurementsMap measurements () const override virtual
Return the latest measurements.
Returns
the latest measurements.
Reimplemented from Instrument.
Definition at line 181 of file SchedulerTimer.cpp.
 {
     MeasurementsMap measurements;
     unsigned int    kernel_number = 0;
     for(auto kernel : _kernels)
     {
         std::string name = kernel.prefix + kernel.name + " #" + support::cpp11::to_string(kernel_number++);
         if(output_timestamps)
         {
             ARM_COMPUTE_ERROR_ON(kernel.measurements.size() != 2);
             for(auto const &m : kernel.measurements)
             {
                 if(m.first.find("[start]") != std::string::npos)
                 {
                     measurements.emplace("[start]" + name, m.second);
                 }
                 else if(m.first.find("[end]") != std::string::npos)
                 {
                     measurements.emplace("[end]" + name, m.second);
                 }
                 else
                 {
                     ARM_COMPUTE_ERROR("Measurement not handled");
                 }
             }
         }
         else
         {
             measurements.emplace(name, kernel.measurements.begin()->second);
         }
     }
     return measurements;
 }
References ARM_COMPUTE_ERROR, ARM_COMPUTE_ERROR_ON, and arm_compute::support::cpp11::to_string().
operator=() [1/2]
SchedulerClock& operator= (const SchedulerClock< output_timestamps > &) delete
Prevent instances of this class from being copied.
operator=() [2/2]
SchedulerClock& operator= (SchedulerClock< output_timestamps > &&) default
Use the default move assignment operator.
start()
void start () override virtual
Start measuring.
Called just before the run of the test starts
Reimplemented from Instrument.
Definition at line 164 of file SchedulerTimer.cpp.
 {
     _kernels.clear();
 }
test_start()
void test_start () override virtual
Start of the test.
Called before the test set up starts
Reimplemented from Instrument.
Definition at line 122 of file SchedulerTimer.cpp.
 {
     // Start intercepting tasks:
     ARM_COMPUTE_ERROR_ON(_real_graph_function != nullptr);
     _real_graph_function  = graph::TaskExecutor::get().execute_function;
     auto task_interceptor = [this](graph::ExecutionTask & task)
     {
         Interceptor<output_timestamps> *scheduler = nullptr;
         if(dynamic_cast<Interceptor<output_timestamps> *>(this->_interceptor.get()) != nullptr)
         {
             scheduler = arm_compute::utils::cast::polymorphic_downcast<Interceptor<output_timestamps> *>(_interceptor.get());
             if(task.node != nullptr && !task.node->name().empty())
             {
                 scheduler->set_prefix(task.node->name() + "/");
             }
             else
             {
                 scheduler->set_prefix("");
             }
         }
         this->_real_graph_function(task);
         if(scheduler != nullptr)
         {
             scheduler->set_prefix("");
         }
     };
     ARM_COMPUTE_ERROR_ON(_real_scheduler != nullptr);
     _real_scheduler_type = Scheduler::get_type();
     //Note: We can't currently replace a custom scheduler
     if(_real_scheduler_type != Scheduler::Type::CUSTOM)
     {
         _real_scheduler = &Scheduler::get();
         _interceptor    = std::make_shared<Interceptor<output_timestamps>>(_kernels, *_real_scheduler, _scale_factor);
         Scheduler::set(std::static_pointer_cast<IScheduler>(_interceptor));
         graph::TaskExecutor::get().execute_function = task_interceptor;
     }
 }
References ARM_COMPUTE_ERROR_ON, Scheduler::CUSTOM, TaskExecutor::execute_function, Scheduler::get(), TaskExecutor::get(), Scheduler::get_type(), and Scheduler::set().
test_stop()
void test_stop () override virtual
End of the test.
Called after the test teardown ended
Reimplemented from Instrument.
Definition at line 170 of file SchedulerTimer.cpp.
 {
     // Restore real scheduler
     Scheduler::set(_real_scheduler_type);
     _real_scheduler                             = nullptr;
     _interceptor                                = nullptr;
     graph::TaskExecutor::get().execute_function = _real_graph_function;
     _real_graph_function                        = nullptr;
 }
References TaskExecutor::execute_function, TaskExecutor::get(), and Scheduler::set().
The documentation for this class was generated from the following files:
tests/framework/instruments/SchedulerTimer.h
tests/framework/instruments/SchedulerTimer.cpp