Compute Library: NEChannelCombineKernel Class Reference
NEChannelCombineKernel Class Reference
Interface for the channel combine kernel.
#include <NEChannelCombineKernel.h>
Public Member Functions
const char * name () const override
Name of the kernel.
NEChannelCombineKernel ()
Default constructor.
NEChannelCombineKernel (const NEChannelCombineKernel &)=delete
Prevent instances of this class from being copied (As this class contains pointers)
NEChannelCombineKernel & operator= (const NEChannelCombineKernel &)=delete
Prevent instances of this class from being copied (As this class contains pointers)
NEChannelCombineKernel (NEChannelCombineKernel &&)=default
Allow instances of this class to be moved.
NEChannelCombineKernel & operator= (NEChannelCombineKernel &&)=default
Allow instances of this class to be moved.
~NEChannelCombineKernel ()=default
Default destructor.
void configure (const ITensor *plane0, const ITensor *plane1, const ITensor *plane2, const ITensor *plane3, ITensor *output)
Configure function's inputs and outputs.
void configure (const IImage *plane0, const IImage *plane1, const IImage *plane2, IMultiImage *output)
Configure function's inputs and outputs.
void run (const Window &window, const ThreadInfo &info) override
Execute the kernel on the passed window.
bool is_parallelisable () const override
Indicates whether or not the kernel is parallelisable.
Public Member Functions inherited from ICPPKernel
virtual ~ICPPKernel ()=default
Default destructor.
Public Member Functions inherited from IKernel
IKernel ()
Constructor.
virtual ~IKernel ()=default
Destructor.
virtual BorderSize border_size () const
The size of the border for that kernel.
const Window & window () const
The maximum window the kernel can be executed on.
Detailed Description
Interface for the channel combine kernel.
Definition at line 39 of file NEChannelCombineKernel.h.
Constructor & Destructor Documentation
NEChannelCombineKernel() [1/3]
NEChannelCombineKernel ()
Default constructor.
Definition at line 46 of file NEChannelCombineKernel.cpp.
     : _func(nullptr), _planes{ { nullptr } }, _output(nullptr), _output_multi(nullptr), _x_subsampling{ { 1, 1, 1 } }, _y_subsampling{ { 1, 1, 1 } }, _num_elems_processed_per_iteration(8),
 _is_parallelizable(true)
 {
 }
NEChannelCombineKernel() [2/3]
NEChannelCombineKernel (const NEChannelCombineKernel &) delete
Prevent instances of this class from being copied (As this class contains pointers)
NEChannelCombineKernel() [3/3]
NEChannelCombineKernel (NEChannelCombineKernel &&) default
Allow instances of this class to be moved.
~NEChannelCombineKernel()
~NEChannelCombineKernel () default
Default destructor.
Member Function Documentation
configure() [1/2]
void configure (const ITensor * plane0, const ITensor * plane1, const ITensor * plane2, const ITensor * plane3, ITensor * output)
Configure function's inputs and outputs.
Parameters
[in] plane0 The 2D plane that forms channel 0. Data type supported: U8
[in] plane1 The 2D plane that forms channel 1. Data type supported: U8
[in] plane2 The 2D plane that forms channel 2. Data type supported: U8
[in] plane3 The 2D plane that forms channel 3. Data type supported: U8
[out] output The single planar output tensor. Formats supported: RGB888/RGBA8888/UYVY422/YUYV422
Definition at line 52 of file NEChannelCombineKernel.cpp.
 {
     ARM_COMPUTE_ERROR_ON_NULLPTR(plane0, plane1, plane2, output);
     ARM_COMPUTE_ERROR_ON(plane0 == output);
     ARM_COMPUTE_ERROR_ON(plane1 == output);
     ARM_COMPUTE_ERROR_ON(plane2 == output);
     ARM_COMPUTE_ERROR_ON_FORMAT_NOT_IN(plane0, Format::U8);
     ARM_COMPUTE_ERROR_ON_FORMAT_NOT_IN(plane1, Format::U8);
     ARM_COMPUTE_ERROR_ON_FORMAT_NOT_IN(plane2, Format::U8);
     ARM_COMPUTE_ERROR_ON_FORMAT_NOT_IN(output, Format::RGB888, Format::RGBA8888, Format::UYVY422, Format::YUYV422);
     ARM_COMPUTE_ERROR_ON_DATA_TYPE_CHANNEL_NOT_IN(plane0, 1, DataType::U8);
     ARM_COMPUTE_ERROR_ON_DATA_TYPE_CHANNEL_NOT_IN(plane1, 1, DataType::U8);
     ARM_COMPUTE_ERROR_ON_DATA_TYPE_CHANNEL_NOT_IN(plane2, 1, DataType::U8);
     const Format output_format = output->info()->format();
     // Check if horizontal dimension of Y plane is even and validate horizontal sub-sampling dimensions for U and V planes
     if(Format::YUYV422 == output_format || Format::UYVY422 == output_format)
     {
         // Validate Y plane of input and output
         ARM_COMPUTE_ERROR_ON_TENSORS_NOT_EVEN(output_format, plane0, output);
         // Validate U and V plane of the input
         ARM_COMPUTE_ERROR_ON_TENSORS_NOT_SUBSAMPLED(output_format, plane0->info()->tensor_shape(), plane1, plane2);
     }
     _planes[0] = plane0;
     _planes[1] = plane1;
     _planes[2] = plane2;
     _planes[3] = nullptr;
     // Validate the last input tensor only for RGBA format
     if(Format::RGBA8888 == output_format)
     {
         ARM_COMPUTE_ERROR_ON_NULLPTR(plane3);
         ARM_COMPUTE_ERROR_ON_TENSOR_NOT_2D(plane3);
         ARM_COMPUTE_ERROR_ON_FORMAT_NOT_IN(plane3, Format::U8);
         ARM_COMPUTE_ERROR_ON_DATA_TYPE_CHANNEL_NOT_IN(plane3, 1, DataType::U8);
         _planes[3] = plane3;
     }
     _output       = output;
     _output_multi = nullptr;
     // Half the processed elements for U and V channels due to horizontal sub-sampling of 2
     if(Format::YUYV422 == output_format || Format::UYVY422 == output_format)
     {
         _x_subsampling[1] = 2;
         _x_subsampling[2] = 2;
     }
     _num_elems_processed_per_iteration = 8;
     _is_parallelizable                 = true;
     // Select function and number of elements to process given the output format
     switch(output_format)
     {
         case Format::RGB888:
             _func = &NEChannelCombineKernel::combine_3C;
             break;
         case Format::RGBA8888:
             _func = &NEChannelCombineKernel::combine_4C;
             break;
         case Format::UYVY422:
             _num_elems_processed_per_iteration = 16;
             _func                              = &NEChannelCombineKernel::combine_YUV_1p<true>;
             break;
         case Format::YUYV422:
             _num_elems_processed_per_iteration = 16;
             _func                              = &NEChannelCombineKernel::combine_YUV_1p<false>;
             break;
         default:
             ARM_COMPUTE_ERROR("Not supported format.");
             break;
     }
     Window win = calculate_max_window(*plane0->info(), Steps(_num_elems_processed_per_iteration));
     AccessWindowHorizontal output_access(output->info(), 0, _num_elems_processed_per_iteration);
     AccessWindowHorizontal plane0_access(plane0->info(), 0, _num_elems_processed_per_iteration / _x_subsampling[1], 1.f / _x_subsampling[0]);
     AccessWindowHorizontal plane1_access(plane1->info(), 0, _num_elems_processed_per_iteration / _x_subsampling[1], 1.f / _x_subsampling[1]);
     AccessWindowHorizontal plane2_access(plane2->info(), 0, _num_elems_processed_per_iteration / _x_subsampling[1], 1.f / _x_subsampling[2]);
     AccessWindowHorizontal plane3_access(plane3 == nullptr ? nullptr : plane3->info(), 0, _num_elems_processed_per_iteration);
     update_window_and_padding(
         win,
         plane0_access,
         plane1_access,
         plane2_access,
         plane3_access,
         output_access);
     ValidRegion valid_region = intersect_valid_regions(plane0->info()->valid_region(),
                                                        plane1->info()->valid_region(),
                                                        plane2->info()->valid_region());
     if(plane3 != nullptr)
     {
         valid_region = intersect_valid_regions(plane3->info()->valid_region(), valid_region);
     }
     output_access.set_valid_region(win, ValidRegion(valid_region.anchor, output->info()->tensor_shape()));
     INEKernel::configure(win);
 }
References ValidRegion::anchor, ARM_COMPUTE_ERROR, ARM_COMPUTE_ERROR_ON, ARM_COMPUTE_ERROR_ON_DATA_TYPE_CHANNEL_NOT_IN, ARM_COMPUTE_ERROR_ON_FORMAT_NOT_IN, ARM_COMPUTE_ERROR_ON_NULLPTR, ARM_COMPUTE_ERROR_ON_TENSOR_NOT_2D, ARM_COMPUTE_ERROR_ON_TENSORS_NOT_EVEN, ARM_COMPUTE_ERROR_ON_TENSORS_NOT_SUBSAMPLED, arm_compute::calculate_max_window(), ITensorInfo::format(), ITensor::info(), arm_compute::intersect_valid_regions(), arm_compute::RGB888, arm_compute::RGBA8888, ITensorInfo::tensor_shape(), arm_compute::U8, arm_compute::update_window_and_padding(), arm_compute::UYVY422, arm_compute::test::validation::valid_region, ITensorInfo::valid_region(), and arm_compute::YUYV422.
configure() [2/2]
void configure (const IImage * plane0, const IImage * plane1, const IImage * plane2, IMultiImage * output)
Configure function's inputs and outputs.
Parameters
[in] plane0 The 2D plane that forms channel 0. Data type supported: U8
[in] plane1 The 2D plane that forms channel 1. Data type supported: U8
[in] plane2 The 2D plane that forms channel 2. Data type supported: U8
[out] output The multi planar output tensor. Formats supported: NV12/NV21/IYUV/YUV444
Definition at line 162 of file NEChannelCombineKernel.cpp.
 {
     ARM_COMPUTE_ERROR_ON_NULLPTR(plane0, plane1, plane2, output);
     ARM_COMPUTE_ERROR_ON_TENSOR_NOT_2D(plane0);
     ARM_COMPUTE_ERROR_ON_TENSOR_NOT_2D(plane1);
     ARM_COMPUTE_ERROR_ON_TENSOR_NOT_2D(plane2);
     ARM_COMPUTE_ERROR_ON_FORMAT_NOT_IN(plane0, Format::U8);
     ARM_COMPUTE_ERROR_ON_FORMAT_NOT_IN(plane1, Format::U8);
     ARM_COMPUTE_ERROR_ON_FORMAT_NOT_IN(plane2, Format::U8);
     ARM_COMPUTE_ERROR_ON_FORMAT_NOT_IN(output, Format::NV12, Format::NV21, Format::IYUV, Format::YUV444);
     ARM_COMPUTE_ERROR_ON_DATA_TYPE_CHANNEL_NOT_IN(plane0, 1, DataType::U8);
     ARM_COMPUTE_ERROR_ON_DATA_TYPE_CHANNEL_NOT_IN(plane1, 1, DataType::U8);
     ARM_COMPUTE_ERROR_ON_DATA_TYPE_CHANNEL_NOT_IN(plane2, 1, DataType::U8);
     const Format output_format = output->info()->format();
     // Validate shape of Y plane to be even and shape of sub-sampling dimensions for U and V planes
     // Perform validation only for formats which require sub-sampling.
     if(Format::YUV444 != output_format)
     {
         // Validate Y plane of input and output
         ARM_COMPUTE_ERROR_ON_TENSORS_NOT_EVEN(output_format, plane0, output->plane(0));
         // Validate U and V plane of the input
         ARM_COMPUTE_ERROR_ON_TENSORS_NOT_SUBSAMPLED(output_format, plane0->info()->tensor_shape(), plane1, plane2);
         // Validate second plane U (NV12 and NV21 have a UV88 combined plane while IYUV has only the U plane)
         // MultiImage generates the correct tensor shape but also check in case the tensor shape of planes was changed to a wrong size
         ARM_COMPUTE_ERROR_ON_TENSORS_NOT_SUBSAMPLED(output_format, plane0->info()->tensor_shape(), output->plane(1));
         // Validate the last plane V of format IYUV
         if(Format::IYUV == output_format)
         {
             // Validate Y plane of the output
             ARM_COMPUTE_ERROR_ON_TENSORS_NOT_SUBSAMPLED(output_format, plane0->info()->tensor_shape(), output->plane(2));
         }
     }
     _planes[0]    = plane0;
     _planes[1]    = plane1;
     _planes[2]    = plane2;
     _planes[3]    = nullptr;
     _output       = nullptr;
     _output_multi = output;
     bool         has_two_planes           = false;
     unsigned int num_elems_written_plane1 = 8;
     _num_elems_processed_per_iteration = 8;
     _is_parallelizable                 = true;
     switch(output_format)
     {
         case Format::NV12:
         case Format::NV21:
             _x_subsampling           = { { 1, 2, 2 } };
             _y_subsampling           = { { 1, 2, 2 } };
             _func                    = &NEChannelCombineKernel::combine_YUV_2p;
             has_two_planes           = true;
             num_elems_written_plane1 = 16;
             break;
         case Format::IYUV:
             _is_parallelizable = false;
             _x_subsampling     = { { 1, 2, 2 } };
             _y_subsampling     = { { 1, 2, 2 } };
             _func              = &NEChannelCombineKernel::combine_YUV_3p;
             break;
         case Format::YUV444:
             _is_parallelizable = false;
             _x_subsampling     = { { 1, 1, 1 } };
             _y_subsampling     = { { 1, 1, 1 } };
             _func              = &NEChannelCombineKernel::combine_YUV_3p;
             break;
         default:
             ARM_COMPUTE_ERROR("Not supported format.");
             break;
     }
     const unsigned int y_step = *std::max_element(_y_subsampling.begin(), _y_subsampling.end());
     Window                win = calculate_max_window(*plane0->info(), Steps(_num_elems_processed_per_iteration, y_step));
     AccessWindowRectangle output_plane0_access(output->plane(0)->info(), 0, 0, _num_elems_processed_per_iteration, 1, 1.f, 1.f / _y_subsampling[0]);
     AccessWindowRectangle output_plane1_access(output->plane(1)->info(), 0, 0, num_elems_written_plane1, 1, 1.f / _x_subsampling[1], 1.f / _y_subsampling[1]);
     AccessWindowRectangle output_plane2_access(has_two_planes ? nullptr : output->plane(2)->info(), 0, 0, _num_elems_processed_per_iteration, 1, 1.f / _x_subsampling[2], 1.f / _y_subsampling[2]);
     update_window_and_padding(win,
                               AccessWindowHorizontal(plane0->info(), 0, _num_elems_processed_per_iteration),
                               AccessWindowRectangle(plane1->info(), 0, 0, _num_elems_processed_per_iteration, 1, 1.f / _x_subsampling[1], 1.f / _y_subsampling[1]),
                               AccessWindowRectangle(plane2->info(), 0, 0, _num_elems_processed_per_iteration, 1, 1.f / _x_subsampling[2], 1.f / _y_subsampling[2]),
                               output_plane0_access,
                               output_plane1_access,
                               output_plane2_access);
     ValidRegion plane0_valid_region  = plane0->info()->valid_region();
     ValidRegion output_plane1_region = has_two_planes ? intersect_valid_regions(plane1->info()->valid_region(), plane2->info()->valid_region()) : plane2->info()->valid_region();
     output_plane0_access.set_valid_region(win, ValidRegion(plane0_valid_region.anchor, output->plane(0)->info()->tensor_shape()));
     output_plane1_access.set_valid_region(win, ValidRegion(output_plane1_region.anchor, output->plane(1)->info()->tensor_shape()));
     output_plane2_access.set_valid_region(win, ValidRegion(plane2->info()->valid_region().anchor, output->plane(2)->info()->tensor_shape()));
     INEKernel::configure(win);
 }
References ValidRegion::anchor, ARM_COMPUTE_ERROR, ARM_COMPUTE_ERROR_ON_DATA_TYPE_CHANNEL_NOT_IN, ARM_COMPUTE_ERROR_ON_FORMAT_NOT_IN, ARM_COMPUTE_ERROR_ON_NULLPTR, ARM_COMPUTE_ERROR_ON_TENSOR_NOT_2D, ARM_COMPUTE_ERROR_ON_TENSORS_NOT_EVEN, ARM_COMPUTE_ERROR_ON_TENSORS_NOT_SUBSAMPLED, arm_compute::calculate_max_window(), MultiImageInfo::format(), IMultiImage::info(), ITensor::info(), arm_compute::intersect_valid_regions(), arm_compute::IYUV, arm_compute::NV12, arm_compute::NV21, IMultiImage::plane(), ITensorInfo::tensor_shape(), arm_compute::U8, arm_compute::update_window_and_padding(), ITensorInfo::valid_region(), and arm_compute::YUV444.
is_parallelisable()
bool is_parallelisable () const override virtual
Indicates whether or not the kernel is parallelisable.
If the kernel is parallelisable then the window returned by window() can be split into sub-windows which can then be run in parallel.
If the kernel is not parallelisable then only the window returned by window() can be passed to run()
Returns
True if the kernel is parallelisable
Reimplemented from IKernel.
Definition at line 267 of file NEChannelCombineKernel.cpp.
 {
     return _is_parallelizable;
 }
name()
const char* name () const inline override virtual
Name of the kernel.
Returns
Kernel name
Implements ICPPKernel.
Definition at line 42 of file NEChannelCombineKernel.h.
     {
         return "NEChannelCombineKernel";
     }
operator=() [1/2]
NEChannelCombineKernel& operator= (const NEChannelCombineKernel &) delete
Prevent instances of this class from being copied (As this class contains pointers)
operator=() [2/2]
NEChannelCombineKernel& operator= (NEChannelCombineKernel &&) default
Allow instances of this class to be moved.
run()
void run (const Window & window, const ThreadInfo & info) override virtual
Execute the kernel on the passed window.
Warning
If is_parallelisable() returns false then the passed window must be equal to window()
Note
The window has to be a region within the window returned by the window() method
The width of the window has to be a multiple of num_elems_processed_per_iteration().
Parameters
[in] window Region on which to execute the kernel. (Must be a region of the window returned by window())
[in] info Info about executing thread and CPU.
Implements ICPPKernel.
Definition at line 272 of file NEChannelCombineKernel.cpp.
 {
     ARM_COMPUTE_UNUSED(info);
     ARM_COMPUTE_ERROR_ON_UNCONFIGURED_KERNEL(this);
     ARM_COMPUTE_ERROR_ON_INVALID_SUBWINDOW(INEKernel::window(), window);
     ARM_COMPUTE_ERROR_ON(_func == nullptr);
     (this->*_func)(window);
 }
References ARM_COMPUTE_ERROR_ON, ARM_COMPUTE_ERROR_ON_INVALID_SUBWINDOW, ARM_COMPUTE_ERROR_ON_UNCONFIGURED_KERNEL, ARM_COMPUTE_UNUSED, arm_compute::test::validation::info, and IKernel::window().
The documentation for this class was generated from the following files:
arm_compute/core/NEON/kernels/NEChannelCombineKernel.h
src/core/NEON/kernels/NEChannelCombineKernel.cpp