Compute Library: HarrisCornersValidationFixture< TensorType, AccessorType, ArrayType, FunctionType, T > Class Template Reference
HarrisCornersValidationFixture< TensorType, AccessorType, ArrayType, FunctionType, T > Class Template Reference
#include <HarrisCornersFixture.h>
Public Member Functions
template<typename... >
void setup (std::string image, int gradient_size, int block_size, BorderMode border_mode, bool use_fp16, Format format)
Public Member Functions inherited from Fixture
void setup ()
Setup function.
void teardown ()
Teardown function.
Detailed Description
template<typename TensorType, typename AccessorType, typename ArrayType, typename FunctionType, typename T>
class arm_compute::test::validation::HarrisCornersValidationFixture< TensorType, AccessorType, ArrayType, FunctionType, T >
Definition at line 46 of file HarrisCornersFixture.h.
Member Function Documentation
void setup (std::string image, int gradient_size, int block_size, BorderMode border_mode, bool use_fp16, Format format) inline
Definition at line 50 of file HarrisCornersFixture.h.
References ARM_COMPUTE_ERROR_ON, arm_compute::test::validation::ARM_COMPUTE_EXPECT(), ARM_COMPUTE_UNUSED, arm_compute::test::validation::border_mode, HarrisCornersParameters::constant_border_value, arm_compute::test::framework::ERRORS, arm_compute::test::validation::harris_corners_parameters(), arm_compute::test::library, HarrisCornersParameters::min_dist, HarrisCornersParameters::sensitivity, SimpleTensor< T >::shape(), arm_compute::test::validation::src, HarrisCornersParameters::threshold, TensorShape::total_size(), caffe_data_extractor::type, arm_compute::U, and value.
     {
         HarrisCornersParameters params = harris_corners_parameters();
         _target = compute_target(image, gradient_size, block_size, border_mode, use_fp16, format, params);
         _reference = compute_reference(image, gradient_size, block_size, border_mode, format, params);
     }
The documentation for this class was generated from the following file:
tests/validation/fixtures/HarrisCornersFixture.h