Compute Library: GEMMLowpDataset Class Reference
GEMMLowpDataset Class Reference
#include <GEMMLowpDataset.h>
Data Structures
struct iterator
Public Types
using type = std::tuple< TensorShape, TensorShape, TensorShape, int32_t, int32_t >
Public Member Functions
iterator begin () const
int size () const
void add_config (TensorShape a, TensorShape b, TensorShape c, int32_t a_offset, int32_t b_offset)
Detailed Description
Definition at line 37 of file GEMMLowpDataset.h.
Member Typedef Documentation
using type = std::tuple<TensorShape, TensorShape, TensorShape, int32_t, int32_t>
Definition at line 40 of file GEMMLowpDataset.h.
Member Function Documentation
void add_config (TensorShape a, TensorShape b, TensorShape c, int32_t a_offset, int32_t b_offset) inline
Definition at line 102 of file GEMMLowpDataset.h.
Referenced by LargeGEMMLowpDataset::LargeGEMMLowpDataset(), and SmallGEMMLowpDataset::SmallGEMMLowpDataset().
     {
         _a_shapes.emplace_back(std::move(a));
         _b_shapes.emplace_back(std::move(b));
         _c_shapes.emplace_back(std::move(c));
         _a_offset.emplace_back(std::move(a_offset));
         _b_offset.emplace_back(std::move(b_offset));
     }
iterator begin () const inline
Definition at line 92 of file GEMMLowpDataset.h.
References GEMMLowpDataset::iterator::iterator().
     {
         return iterator(_a_shapes.begin(), _b_shapes.begin(), _c_shapes.begin(), _a_offset.begin(), _b_offset.begin());
     }
int size () const inline
Definition at line 97 of file GEMMLowpDataset.h.
References arm_compute::test::fixed_point_arithmetic::detail::min().
     {
         return std::min(_a_shapes.size(), std::min(_b_shapes.size(), std::min(_c_shapes.size(), std::min(_a_offset.size(), _b_offset.size()))));
     }
The documentation for this class was generated from the following file:
tests/datasets/GEMMLowpDataset.h