Compute Library: ArrayAccessor< T > Class Template Reference
ArrayAccessor< T > Class Template Reference
ArrayAccessor implementation for Array objects.
#include <ArrayAccessor.h>
Public Member Functions
ArrayAccessor (Array< T > &array)
Create an accessor for the given array.
ArrayAccessor (const ArrayAccessor &)=delete
Prevent instances of this class from being copy constructed.
ArrayAccessor & operator= (const ArrayAccessor &)=delete
Prevent instances of this class from being copied.
ArrayAccessor (ArrayAccessor &&)=default
Allow instances of this class to be move constructed.
ArrayAccessor & operator= (ArrayAccessor &&)=default
Allow instances of this class to be moved.
size_t num_values () const override
Number of elements of the tensor.
T * buffer () override
Access to the buffer.
void resize (size_t num) override
Resize array.
T & at (size_t index) const override
Reference to the element of the array located at the given index.
Public Member Functions inherited from IArrayAccessor< T >
virtual ~IArrayAccessor ()=default
Virtual destructor.
Additional Inherited Members
Public Types inherited from IArrayAccessor< T >
using value_type = T
Array value type.
Detailed Description
template<typename T>
class arm_compute::test::ArrayAccessor< T >
ArrayAccessor implementation for Array objects.
Definition at line 36 of file ArrayAccessor.h.
Constructor & Destructor Documentation
ArrayAccessor() [1/3]
ArrayAccessor (Array< T > & array) inline
Create an accessor for the given array.
Parameters
[in,out] array To be accessed array.
Definition at line 43 of file ArrayAccessor.h.
         : _array{ array }
     {
     }
ArrayAccessor() [2/3]
ArrayAccessor (const ArrayAccessor< T > &) delete
Prevent instances of this class from being copy constructed.
ArrayAccessor() [3/3]
ArrayAccessor (ArrayAccessor< T > &&) default
Allow instances of this class to be move constructed.
Member Function Documentation
at()
T& at (size_t index) const inline override virtual
Reference to the element of the array located at the given index.
Parameters
[in] index Index of the element
Returns
A reference to the element of the array located at the given index.
Implements IArrayAccessor< T >.
Definition at line 72 of file ArrayAccessor.h.
     {
         ARM_COMPUTE_ERROR_ON(_array.buffer() == nullptr);
         ARM_COMPUTE_ERROR_ON(index >= num_values());
         return _array.buffer()[index];
     }
References ARM_COMPUTE_ERROR_ON, and ArrayAccessor< T >::num_values().
buffer()
T* buffer () inline override virtual
Access to the buffer.
Returns
A pointer to the first element in the buffer.
Implements IArrayAccessor< T >.
Definition at line 62 of file ArrayAccessor.h.
     {
         return _array.buffer();
     }
Referenced by arm_compute::test::validation::FIXTURE_DATA_TEST_CASE().
num_values()
size_t num_values () const inline override virtual
Number of elements of the tensor.
Returns
the number of elements.
Implements IArrayAccessor< T >.
Definition at line 57 of file ArrayAccessor.h.
     {
         return _array.num_values();
     }
Referenced by ArrayAccessor< T >::at(), and arm_compute::test::validation::FIXTURE_DATA_TEST_CASE().
operator=() [1/2]
ArrayAccessor& operator= (const ArrayAccessor< T > &) delete
Prevent instances of this class from being copied.
operator=() [2/2]
ArrayAccessor& operator= (ArrayAccessor< T > &&) default
Allow instances of this class to be moved.
resize()
void resize (size_t num) inline override virtual
Resize array.
Parameters
[in] num The new array size in number of elements
Implements IArrayAccessor< T >.
Definition at line 67 of file ArrayAccessor.h.
     {
         _array.resize(num);
     }
The documentation for this class was generated from the following file:
tests/NEON/ArrayAccessor.h