Compute Library: GCDepthConcatenateLayer Class Reference
GCDepthConcatenateLayer Class Reference
Basic function to execute concatenate tensors along z axis.
#include <GCDepthConcatenateLayer.h>
Public Member Functions
GCDepthConcatenateLayer ()
Default constructor.
void configure (std::vector< IGCTensor * > inputs_vector, IGCTensor *output)
Initialise the kernel's inputs vector and output.
void run () override
Run the kernels contained in the function.
Public Member Functions inherited from IFunction
virtual ~IFunction ()=default
Destructor.
virtual void prepare ()
Prepare the function for executing.
Detailed Description
Basic function to execute concatenate tensors along z axis.
This function calls the following kernels:
GCFillBorderKernel (executed if input's lowest two dimensions are smaller than respective output's dimensions)
GCDepthConcatenateLayerKernel
Definition at line 46 of file GCDepthConcatenateLayer.h.
Constructor & Destructor Documentation
GCDepthConcatenateLayer()
GCDepthConcatenateLayer ()
Default constructor.
Definition at line 35 of file GCDepthConcatenateLayer.cpp.
     : _concat_kernels_vector(),
       _border_handlers_vector(),
       _num_inputs(0)
 {
 }
Member Function Documentation
configure()
void configure (std::vector< IGCTensor * > inputs_vector, IGCTensor * output)
Initialise the kernel's inputs vector and output.
Parameters
[in,out] inputs_vector The vectors containing all the tensors to concatenate. Data types supported: F16/F32.
[out] output Output tensor. Data types supported: Same as input.
Definition at line 42 of file GCDepthConcatenateLayer.cpp.
 {
     ARM_COMPUTE_ERROR_ON(inputs_vector.size() < 2);
     _num_inputs = inputs_vector.size();
     unsigned int depth_offset = 0;
     _concat_kernels_vector  = arm_compute::support::cpp14::make_unique<GCDepthConcatenateLayerKernel[]>(_num_inputs);
     _border_handlers_vector = arm_compute::support::cpp14::make_unique<GCFillBorderKernel[]>(_num_inputs);
     for(unsigned int i = 0; i < _num_inputs; i++)
     {
         _concat_kernels_vector[i].configure(inputs_vector.at(i), depth_offset, output);
         _border_handlers_vector[i].configure(inputs_vector.at(i), _concat_kernels_vector[i].border_size(), BorderMode::CONSTANT, PixelValue());
         depth_offset += inputs_vector.at(i)->info()->dimension(2);
     }
 }
References ARM_COMPUTE_ERROR_ON, and arm_compute::CONSTANT.
run()
void run () override virtual
Run the kernels contained in the function.
For NEON kernels:
Multi-threading is used for the kernels which are parallelisable.
By default std::thread::hardware_concurrency() threads are used.
Note
CPPScheduler::set_num_threads() can be used to manually set the number of threads
For OpenCL kernels:
All the kernels are enqueued on the queue associated with CLScheduler.
The queue is then flushed.
Note
The function will not block until the kernels are executed. It is the user's responsibility to wait.
Will call prepare() on first run if hasn't been done
Implements IFunction.
Definition at line 62 of file GCDepthConcatenateLayer.cpp.
 {
     for(unsigned i = 0; i < _num_inputs; i++)
     {
         GCScheduler::get().dispatch(_border_handlers_vector[i], false);
         GCScheduler::get().memory_barrier();
         GCScheduler::get().dispatch(_concat_kernels_vector[i], true);
     }
 }
References GCScheduler::dispatch(), GCScheduler::get(), and GCScheduler::memory_barrier().
The documentation for this class was generated from the following files:
arm_compute/runtime/GLES_COMPUTE/functions/GCDepthConcatenateLayer.h
src/runtime/GLES_COMPUTE/functions/GCDepthConcatenateLayer.cpp