Compute Library: CPPDetectionOutputLayer Class Reference
CPPDetectionOutputLayer Class Reference
CPP Function to generate the detection output based on location and confidence predictions by doing non maximum suppression.
#include <CPPDetectionOutputLayer.h>
Public Member Functions
CPPDetectionOutputLayer ()
Default constructor.
void configure (const ITensor *input_loc, const ITensor *input_conf, const ITensor *input_priorbox, ITensor *output, DetectionOutputLayerInfo info=DetectionOutputLayerInfo())
Configure the detection output layer CPP kernel.
void run () override
Run the kernels contained in the function.
CPPDetectionOutputLayer (const CPPDetectionOutputLayer &)=delete
Prevent instances of this class from being copied (As this class contains pointers)
CPPDetectionOutputLayer & operator= (const CPPDetectionOutputLayer &)=delete
Prevent instances of this class from being copied (As this class contains pointers)
Public Member Functions inherited from IFunction
virtual ~IFunction ()=default
Destructor.
virtual void prepare ()
Prepare the function for executing.
Static Public Member Functions
static Status validate (const ITensorInfo *input_loc, const ITensorInfo *input_conf, const ITensorInfo *input_priorbox, const ITensorInfo *output, DetectionOutputLayerInfo info=DetectionOutputLayerInfo())
Static function to check if given info will lead to a valid configuration of CPPDetectionOutputLayer.
Detailed Description
CPP Function to generate the detection output based on location and confidence predictions by doing non maximum suppression.
Note
Intended for use with MultiBox detection method.
Definition at line 97 of file CPPDetectionOutputLayer.h.
Constructor & Destructor Documentation
CPPDetectionOutputLayer() [1/2]
CPPDetectionOutputLayer ()
Default constructor.
Definition at line 474 of file CPPDetectionOutputLayer.cpp.
     : _input_loc(nullptr), _input_conf(nullptr), _input_priorbox(nullptr), _output(nullptr), _info(), _num_priors(), _num(), _all_location_predictions(), _all_confidence_scores(), _all_prior_bboxes(),
       _all_prior_variances(), _all_decode_bboxes(), _all_indices()
 {
 }
CPPDetectionOutputLayer() [2/2]
CPPDetectionOutputLayer (const CPPDetectionOutputLayer &) delete
Prevent instances of this class from being copied (As this class contains pointers)
Member Function Documentation
configure()
void configure (const ITensor * input_loc, const ITensor * input_conf, const ITensor * input_priorbox, ITensor * output, DetectionOutputLayerInfo info = DetectionOutputLayerInfo())
Configure the detection output layer CPP kernel.
Parameters
[in] input_loc The mbox location input tensor of size [C1, N]. Data types supported: F32.
[in] input_conf The mbox confidence input tensor of size [C2, N]. Data types supported: F32.
[in] input_priorbox The mbox prior box input tensor of size [C3, 2, N]. Data types supported: F32.
[out] output The output tensor of size [7, M]. Data types supported: Same as input
[in] info (Optional) DetectionOutputLayerInfo information.
Note
Output contains all the detections. Of those, only the ones selected by the valid region are valid.
Definition at line 480 of file CPPDetectionOutputLayer.cpp.
 {
     ARM_COMPUTE_ERROR_ON_NULLPTR(input_loc, input_conf, input_priorbox, output);
     // Output auto initialization if not yet initialized
     // Since the number of bboxes to kept is unknown before nms, the shape is set to the maximum
     // The maximum is keep_top_k * input_loc_size[1]
     // Each row is a 7 dimension std::vector, which stores [image_id, label, confidence, xmin, ymin, xmax, ymax]
     const unsigned int max_size = info.keep_top_k() * (input_loc->info()->num_dimensions() > 1 ? input_loc->info()->dimension(1) : 1);
     auto_init_if_empty(*output->info(), input_loc->info()->clone()->set_tensor_shape(TensorShape(7U, max_size)));
     // Perform validation step
     ARM_COMPUTE_ERROR_THROW_ON(detection_layer_validate_arguments(input_loc->info(), input_conf->info(), input_priorbox->info(), output->info(), info));
     _input_loc      = input_loc;
     _input_conf     = input_conf;
     _input_priorbox = input_priorbox;
     _output         = output;
     _info           = info;
     _num_priors     = input_priorbox->info()->dimension(0) / 4;
     _num            = (_input_loc->info()->num_dimensions() > 1 ? _input_loc->info()->dimension(1) : 1);
     _all_location_predictions.resize(_num);
     _all_confidence_scores.resize(_num);
     _all_prior_bboxes.resize(_num_priors);
     _all_prior_variances.resize(_num_priors);
     _all_decode_bboxes.resize(_num);
     for(int i = 0; i < _num; ++i)
     {
         for(int c = 0; c < _info.num_loc_classes(); ++c)
         {
             const int label = _info.share_location() ? -1 : c;
             if(label == _info.background_label_id())
             {
                 // Ignore background class.
                 continue;
             }
             _all_decode_bboxes[i][label].resize(_num_priors);
         }
     }
     _all_indices.resize(_num);
     Coordinates coord;
     coord.set_num_dimensions(output->info()->num_dimensions());
     output->info()->set_valid_region(ValidRegion(coord, output->info()->tensor_shape()));
 }
References ARM_COMPUTE_ERROR_ON_NULLPTR, ARM_COMPUTE_ERROR_THROW_ON, arm_compute::auto_init_if_empty(), DetectionOutputLayerInfo::background_label_id(), ICloneable< T >::clone(), ITensorInfo::dimension(), ITensor::info(), arm_compute::test::validation::info, ITensorInfo::num_dimensions(), DetectionOutputLayerInfo::num_loc_classes(), Dimensions< T >::set_num_dimensions(), ITensorInfo::set_valid_region(), DetectionOutputLayerInfo::share_location(), ITensorInfo::tensor_shape(), and arm_compute::U.
operator=()
CPPDetectionOutputLayer& operator= (const CPPDetectionOutputLayer &) delete
Prevent instances of this class from being copied (As this class contains pointers)
run()
void run () override virtual
Run the kernels contained in the function.
For NEON kernels:
Multi-threading is used for the kernels which are parallelisable.
By default std::thread::hardware_concurrency() threads are used.
Note
CPPScheduler::set_num_threads() can be used to manually set the number of threads
For OpenCL kernels:
All the kernels are enqueued on the queue associated with CLScheduler.
The queue is then flushed.
Note
The function will not block until the kernels are executed. It is the user's responsibility to wait.
Will call prepare() on first run if hasn't been done
Implements IFunction.
Definition at line 533 of file CPPDetectionOutputLayer.cpp.
 {
     // Retrieve all location predictions.
     retrieve_all_loc_predictions(_input_loc, _num, _num_priors, _info.num_loc_classes(), _info.share_location(), _all_location_predictions);
     // Retrieve all confidences.
     retrieve_all_conf_scores(_input_conf, _num, _num_priors, _info.num_classes(), _all_confidence_scores);
     // Retrieve all prior bboxes.
     retrieve_all_priorbox(_input_priorbox, _num_priors, _all_prior_bboxes, _all_prior_variances);
     // Decode all loc predictions to bboxes
     const bool clip_bbox = false;
     for(int i = 0; i < _num; ++i)
     {
         for(int c = 0; c < _info.num_loc_classes(); ++c)
         {
             const int label = _info.share_location() ? -1 : c;
             if(label == _info.background_label_id())
             {
                 // Ignore background class.
                 continue;
             }
             ARM_COMPUTE_ERROR_ON_MSG(_all_location_predictions[i].find(label) == _all_location_predictions[i].end(), "Could not find location predictions for label %d.", label);
             const std::vector<NormalizedBBox> &label_loc_preds = _all_location_predictions[i].find(label)->second;
             const int num_bboxes = _all_prior_bboxes.size();
             ARM_COMPUTE_ERROR_ON(_all_prior_variances[i].size() != 4);
             for(int j = 0; j < num_bboxes; ++j)
             {
                 DecodeBBox(_all_prior_bboxes[j], _all_prior_variances[j], _info.code_type(), _info.variance_encoded_in_target(), clip_bbox, label_loc_preds[j], _all_decode_bboxes[i][label][j]);
             }
         }
     }
     int num_kept = 0;
     for(int i = 0; i < _num; ++i)
     {
         const LabelBBox &decode_bboxes = _all_decode_bboxes[i];
         const std::map<int, std::vector<float>> &conf_scores = _all_confidence_scores[i];
         std::map<int, std::vector<int>> indices;
         int num_det = 0;
         for(int c = 0; c < _info.num_classes(); ++c)
         {
             if(c == _info.background_label_id())
             {
                 // Ignore background class
                 continue;
             }
             const int label = _info.share_location() ? -1 : c;
             if(conf_scores.find(c) == conf_scores.end() || decode_bboxes.find(label) == decode_bboxes.end())
             {
                 ARM_COMPUTE_ERROR("Could not find predictions for label %d.", label);
             }
             const std::vector<float>          &scores = conf_scores.find(c)->second;
             const std::vector<NormalizedBBox> &bboxes = decode_bboxes.find(label)->second;
             ApplyNMSFast(bboxes, scores, _info.confidence_threshold(), _info.nms_threshold(), _info.eta(), _info.top_k(), indices[c]);
             num_det += indices[c].size();
         }
         int num_to_add = 0;
         if(_info.keep_top_k() > -1 && num_det > _info.keep_top_k())
         {
             std::vector<std::pair<float, std::pair<int, int>>> score_index_pairs;
             for(auto const &it : indices)
             {
                 const int               label         = it.first;
                 const std::vector<int> &label_indices = it.second;
                 if(conf_scores.find(label) == conf_scores.end())
                 {
                     ARM_COMPUTE_ERROR("Could not find predictions for label %d.", label);
                 }
                 const std::vector<float> &scores = conf_scores.find(label)->second;
                 for(auto idx : label_indices)
                 {
                     ARM_COMPUTE_ERROR_ON(idx > static_cast<int>(scores.size()));
                     score_index_pairs.emplace_back(std::make_pair(scores[idx], std::make_pair(label, idx)));
                 }
             }
             // Keep top k results per image.
             std::sort(score_index_pairs.begin(), score_index_pairs.end(), SortScorePairDescend<std::pair<int, int>>);
             score_index_pairs.resize(_info.keep_top_k());
             // Store the new indices.
             std::map<int, std::vector<int>> new_indices;
             for(auto score_index_pair : score_index_pairs)
             {
                 int label = score_index_pair.second.first;
                 int idx   = score_index_pair.second.second;
                 new_indices[label].push_back(idx);
             }
             _all_indices[i] = new_indices;
             num_to_add      = _info.keep_top_k();
         }
         else
         {
             _all_indices[i] = indices;
             num_to_add      = num_det;
         }
         num_kept += num_to_add;
     }
     //Update the valid region of the ouput to mark the exact number of detection
     _output->info()->set_valid_region(ValidRegion(Coordinates(0, 0), TensorShape(7, num_kept)));
     int count = 0;
     for(int i = 0; i < _num; ++i)
     {
         const std::map<int, std::vector<float>> &conf_scores = _all_confidence_scores[i];
         const LabelBBox &decode_bboxes = _all_decode_bboxes[i];
         for(auto &it : _all_indices[i])
         {
             const int                 label     = it.first;
             const std::vector<float> &scores    = conf_scores.find(label)->second;
             const int                 loc_label = _info.share_location() ? -1 : label;
             if(conf_scores.find(label) == conf_scores.end() || decode_bboxes.find(loc_label) == decode_bboxes.end())
             {
                 // Either if there are no confidence predictions
                 // or there are no location predictions for current label.
                 ARM_COMPUTE_ERROR("Could not find predictions for the label %d.", label);
             }
             const std::vector<NormalizedBBox> &bboxes  = decode_bboxes.find(loc_label)->second;
             const std::vector<int>            &indices = it.second;
             for(auto idx : indices)
             {
                 *(reinterpret_cast<float *>(_output->ptr_to_element(Coordinates(count * 7))))     = i;
                 *(reinterpret_cast<float *>(_output->ptr_to_element(Coordinates(count * 7 + 1)))) = label;
                 *(reinterpret_cast<float *>(_output->ptr_to_element(Coordinates(count * 7 + 2)))) = scores[idx];
                 *(reinterpret_cast<float *>(_output->ptr_to_element(Coordinates(count * 7 + 3)))) = bboxes[idx][0];
                 *(reinterpret_cast<float *>(_output->ptr_to_element(Coordinates(count * 7 + 4)))) = bboxes[idx][1];
                 *(reinterpret_cast<float *>(_output->ptr_to_element(Coordinates(count * 7 + 5)))) = bboxes[idx][2];
                 *(reinterpret_cast<float *>(_output->ptr_to_element(Coordinates(count * 7 + 6)))) = bboxes[idx][3];
                 ++count;
             }
         }
     }
 }
References ARM_COMPUTE_ERROR, ARM_COMPUTE_ERROR_ON, ARM_COMPUTE_ERROR_ON_MSG, DetectionOutputLayerInfo::background_label_id(), DetectionOutputLayerInfo::code_type(), DetectionOutputLayerInfo::confidence_threshold(), DetectionOutputLayerInfo::eta(), ITensor::info(), DetectionOutputLayerInfo::keep_top_k(), DetectionOutputLayerInfo::nms_threshold(), DetectionOutputLayerInfo::num_classes(), DetectionOutputLayerInfo::num_loc_classes(), ITensor::ptr_to_element(), ITensorInfo::set_valid_region(), DetectionOutputLayerInfo::share_location(), DetectionOutputLayerInfo::top_k(), and DetectionOutputLayerInfo::variance_encoded_in_target().
validate()
Status validate (const ITensorInfo * input_loc, const ITensorInfo * input_conf, const ITensorInfo * input_priorbox, const ITensorInfo * output, DetectionOutputLayerInfo info = DetectionOutputLayerInfo()) static
Static function to check if given info will lead to a valid configuration of CPPDetectionOutputLayer.
Parameters
[in] input_loc The mbox location input tensor info. Data types supported: F32.
[in] input_conf The mbox confidence input tensor info. Data types supported: F32.
[in] input_priorbox The mbox prior box input tensor info. Data types supported: F32.
[in] output The output tensor info. Data types supported: Same as input
[in] info (Optional) DetectionOutputLayerInfo information.
Returns
a status
Definition at line 527 of file CPPDetectionOutputLayer.cpp.
 {
     ARM_COMPUTE_RETURN_ON_ERROR(detection_layer_validate_arguments(input_loc, input_conf, input_priorbox, output, info));
     return Status{};
 }
References ARM_COMPUTE_RETURN_ON_ERROR, and arm_compute::test::validation::info.
The documentation for this class was generated from the following files:
arm_compute/runtime/CPP/functions/CPPDetectionOutputLayer.h
src/runtime/CPP/functions/CPPDetectionOutputLayer.cpp