Compute Library: OpenCLMemoryUsage Class Reference
OpenCLMemoryUsage Class Reference
Instrument collecting memory usage information for OpenCL.
#include <OpenCLMemoryUsage.h>
Public Member Functions
OpenCLMemoryUsage (ScaleFactor scale_factor)
Construct an OpenCL timer.
std::string id () const override
Identifier for the instrument.
void test_start () override
Start of the test.
void start () override
Start measuring.
void stop () override
Stop measuring.
void test_stop () override
End of the test.
MeasurementsMap test_measurements () const override
Return the latest test measurements.
MeasurementsMap measurements () const override
Return the latest measurements.
Public Member Functions inherited from Instrument
Instrument ()=default
Default constructor.
Instrument (const Instrument &)=default
Allow instances of this class to be copy constructed.
Instrument (Instrument &&)=default
Allow instances of this class to be move constructed.
Instrument & operator= (const Instrument &)=default
Allow instances of this class to be copied.
Instrument & operator= (Instrument &&)=default
Allow instances of this class to be moved.
virtual ~Instrument ()=default
Default destructor.
Additional Inherited Members
Public Types inherited from Instrument
using MeasurementsMap = std::map< std::string, Measurement >
Map of measurements.
Static Public Member Functions inherited from Instrument
template<typename T , ScaleFactor scale>
static std::unique_ptr< Instrument > make_instrument ()
Helper function to create an instrument of the given type.
Detailed Description
Instrument collecting memory usage information for OpenCL.
Definition at line 42 of file OpenCLMemoryUsage.h.
Constructor & Destructor Documentation
OpenCLMemoryUsage()
OpenCLMemoryUsage (ScaleFactor scale_factor)
Construct an OpenCL timer.
Parameters
[in] scale_factor Measurement scale factor.
Definition at line 46 of file OpenCLMemoryUsage.cpp.
     : real_clCreateBuffer(CLSymbols::get().clCreateBuffer_ptr), real_clRetainMemObject(CLSymbols::get().clRetainMemObject_ptr), real_clReleaseMemObject(CLSymbols::get().clReleaseMemObject_ptr),
       real_clSVMAlloc(CLSymbols::get().clSVMAlloc_ptr), real_clSVMFree(CLSymbols::get().clSVMFree_ptr), _allocations(), _svm_allocations(), _start(), _end(), _now()
 {
     switch(scale_factor)
     {
         case ScaleFactor::NONE:
             _scale_factor = 1;
             _unit         = "";
             break;
         case ScaleFactor::SCALE_1K:
             _scale_factor = 1000;
             _unit         = "K ";
             break;
         case ScaleFactor::SCALE_1M:
             _scale_factor = 1000000;
             _unit         = "M ";
             break;
         default:
             ARM_COMPUTE_ERROR("Invalid scale");
     }
 }
Member Function Documentation
id()
std::string id () const override virtual
Identifier for the instrument.
Implements Instrument.
Definition at line 41 of file OpenCLMemoryUsage.cpp.
 {
     return "OpenCLMemoryUsage";
 }
measurements()
Instrument::MeasurementsMap measurements () const override virtual
Return the latest measurements.
Returns
the latest measurements.
Reimplemented from Instrument.
Definition at line 176 of file OpenCLMemoryUsage.cpp.
 {
     MeasurementsMap measurements;
     measurements.emplace("Num buffers allocated per run", Measurement(_end.num_allocations - _start.num_allocations, ""));
     measurements.emplace("Total memory allocated per run", Measurement((_end.total_allocated - _start.total_allocated) / _scale_factor, _unit));
     measurements.emplace("Memory in use at start of run", Measurement(_start.in_use / _scale_factor, _unit));
     return measurements;
 }
Referenced by OpenCLMemoryUsage::test_measurements().
start()
void start () override virtual
Start measuring.
Called just before the run of the test starts
Reimplemented from Instrument.
Definition at line 157 of file OpenCLMemoryUsage.cpp.
 {
     _start = _now;
 }
stop()
void stop () override virtual
Stop measuring.
Called just after the run of the test ends
Reimplemented from Instrument.
Definition at line 161 of file OpenCLMemoryUsage.cpp.
 {
     _end = _now;
 }
test_measurements()
Instrument::MeasurementsMap test_measurements () const override virtual
Return the latest test measurements.
Returns
the latest test measurements.
Reimplemented from Instrument.
Definition at line 185 of file OpenCLMemoryUsage.cpp.
 {
     MeasurementsMap measurements;
     measurements.emplace("Num buffers", Measurement(_now.num_allocations, ""));
     measurements.emplace("Total memory allocated", Measurement(_now.total_allocated / _scale_factor, _unit));
     measurements.emplace("Max memory allocated", Measurement(_now.max_in_use / _scale_factor, _unit));
     measurements.emplace("Memory leaked", Measurement(_now.in_use / _scale_factor, _unit));
     size_t num_programs = CLKernelLibrary::get().get_built_programs().size();
     size_t total_size   = 0;
     for(auto it : CLKernelLibrary::get().get_built_programs())
     {
         std::vector<size_t> binary_sizes = it.second.getInfo<CL_PROGRAM_BINARY_SIZES>();
         total_size                       = std::accumulate(binary_sizes.begin(), binary_sizes.end(), total_size);
     }
     measurements.emplace("Num programs in cache", Measurement(num_programs, ""));
     measurements.emplace("Total programs memory in cache", Measurement(total_size / _scale_factor, _unit));
     return measurements;
 }
References accumulate(), CLKernelLibrary::get(), CLKernelLibrary::get_built_programs(), and OpenCLMemoryUsage::measurements().
test_start()
void test_start () override virtual
Start of the test.
Called before the test set up starts
Reimplemented from Instrument.
Definition at line 69 of file OpenCLMemoryUsage.cpp.
 {
     _now = Stats();
     ARM_COMPUTE_ERROR_ON(CLSymbols::get().clCreateBuffer_ptr == nullptr);
     CLSymbols::get().clCreateBuffer_ptr = [this](
                                               cl_context   context,
                                               cl_mem_flags flags,
                                               size_t       size,
                                               void        *host_ptr,
                                               cl_int *     errcode_ret)
     {
         cl_mem retval = this->real_clCreateBuffer(context, flags, size, host_ptr, errcode_ret);
         if(host_ptr != nullptr)
         {
             // If it's an SVM / external allocation;
             size = 0;
         }
         else
         {
             _now.num_allocations++;
             _now.in_use += size;
             _now.total_allocated += size;
             if(_now.in_use > _now.max_in_use)
             {
                 _now.max_in_use = _now.in_use;
             }
         }
         this->_allocations[retval] = Allocation(size);
         return retval;
     };
     ARM_COMPUTE_ERROR_ON(CLSymbols::get().clRetainMemObject_ptr == nullptr);
     CLSymbols::get().clRetainMemObject_ptr = [this](cl_mem memobj)
     {
         cl_int retval = this->real_clRetainMemObject(memobj);
         this->_allocations[memobj].refcount++;
         return retval;
     };
     ARM_COMPUTE_ERROR_ON(CLSymbols::get().clReleaseMemObject_ptr == nullptr);
     CLSymbols::get().clReleaseMemObject_ptr = [this](cl_mem memobj)
     {
         cl_int      retval = this->real_clRetainMemObject(memobj);
         Allocation &alloc  = this->_allocations[memobj];
         if(--alloc.refcount == 0)
         {
             _now.in_use -= alloc.size;
         }
         return retval;
     };
     //Only intercept the function if it exists:
     if(CLSymbols::get().clSVMAlloc_ptr != nullptr)
     {
         CLSymbols::get().clSVMAlloc_ptr = [this](cl_context context, cl_svm_mem_flags flags, size_t size, cl_uint alignment)
         {
             void *retval = this->real_clSVMAlloc(context, flags, size, alignment);
             if(retval != nullptr)
             {
                 _svm_allocations[retval] = size;
                 _now.num_allocations++;
                 _now.in_use += size;
                 _now.total_allocated += size;
                 if(_now.in_use > _now.max_in_use)
                 {
                     _now.max_in_use = _now.in_use;
                 }
             }
             return retval;
         };
     }
     //Only intercept the function if it exists:
     if(CLSymbols::get().clSVMFree_ptr != nullptr)
     {
         CLSymbols::get().clSVMFree_ptr = [this](cl_context context, void *svm_pointer)
         {
             this->real_clSVMFree(context, svm_pointer);
             auto iterator = _svm_allocations.find(svm_pointer);
             if(iterator != _svm_allocations.end())
             {
                 size_t size = iterator->second;
                 _svm_allocations.erase(iterator);
                 _now.in_use -= size;
             }
         };
     }
 }
References ARM_COMPUTE_ERROR_ON, CLSymbols::clCreateBuffer_ptr, CLSymbols::clReleaseMemObject_ptr, CLSymbols::clRetainMemObject_ptr, CLSymbols::clSVMAlloc_ptr, CLSymbols::clSVMFree_ptr, and CLSymbols::get().
test_stop()
void test_stop () override virtual
End of the test.
Called after the test teardown ended
Reimplemented from Instrument.
Definition at line 166 of file OpenCLMemoryUsage.cpp.
 {
     // Restore real function
     CLSymbols::get().clCreateBuffer_ptr     = real_clCreateBuffer;
     CLSymbols::get().clRetainMemObject_ptr  = real_clRetainMemObject;
     CLSymbols::get().clReleaseMemObject_ptr = real_clReleaseMemObject;
     CLSymbols::get().clSVMAlloc_ptr         = real_clSVMAlloc;
     CLSymbols::get().clSVMFree_ptr          = real_clSVMFree;
 }
References CLSymbols::clCreateBuffer_ptr, CLSymbols::clReleaseMemObject_ptr, CLSymbols::clRetainMemObject_ptr, CLSymbols::clSVMAlloc_ptr, CLSymbols::clSVMFree_ptr, and CLSymbols::get().
The documentation for this class was generated from the following files:
tests/framework/instruments/OpenCLMemoryUsage.h
tests/framework/instruments/OpenCLMemoryUsage.cpp