Compute Library: CLArithmeticOperationKernel Class Reference
CLArithmeticOperationKernel Class Reference
#include <CLElementwiseOperationKernel.h>
Public Member Functions
CLArithmeticOperationKernel ()
void configure (ArithmeticOperation op, const ICLTensor *input1, const ICLTensor *input2, ICLTensor *output)
Static function to check if given info will lead to a valid configuration of CLArithmeticOperationKernel.
Public Member Functions inherited from CLElementwiseOperationKernel
CLElementwiseOperationKernel ()
Default constructor.
CLElementwiseOperationKernel (const CLElementwiseOperationKernel &)=delete
Prevent instances of this class from being copied (As this class contains pointers)
CLElementwiseOperationKernel & operator= (const CLElementwiseOperationKernel &)=delete
Prevent instances of this class from being copied (As this class contains pointers)
CLElementwiseOperationKernel (CLElementwiseOperationKernel &&)=default
Allow instances of this class to be moved.
CLElementwiseOperationKernel & operator= (CLElementwiseOperationKernel &&)=default
Allow instances of this class to be moved.
~CLElementwiseOperationKernel ()=default
Default destructor.
void run (const Window &window, cl::CommandQueue &queue) override
Enqueue the OpenCL kernel to process the given window on the passed OpenCL command queue.
BorderSize border_size () const override
The size of the border for that kernel.
Public Member Functions inherited from ICLKernel
ICLKernel ()
Constructor.
cl::Kernel & kernel ()
Returns a reference to the OpenCL kernel of this object.
template<typename T >
void add_1D_array_argument (unsigned int &idx, const ICLArray< T > *array, const Strides &strides, unsigned int num_dimensions, const Window &window)
Add the passed 1D array's parameters to the object's kernel's arguments starting from the index idx.
void add_1D_tensor_argument (unsigned int &idx, const ICLTensor *tensor, const Window &window)
Add the passed 1D tensor's parameters to the object's kernel's arguments starting from the index idx.
void add_1D_tensor_argument_if (bool cond, unsigned int &idx, const ICLTensor *tensor, const Window &window)
Add the passed 1D tensor's parameters to the object's kernel's arguments starting from the index idx if the condition is true.
void add_2D_tensor_argument (unsigned int &idx, const ICLTensor *tensor, const Window &window)
Add the passed 2D tensor's parameters to the object's kernel's arguments starting from the index idx.
void add_2D_tensor_argument_if (bool cond, unsigned int &idx, const ICLTensor *tensor, const Window &window)
Add the passed 2D tensor's parameters to the object's kernel's arguments starting from the index idx if the condition is true.
void add_3D_tensor_argument (unsigned int &idx, const ICLTensor *tensor, const Window &window)
Add the passed 3D tensor's parameters to the object's kernel's arguments starting from the index idx.
void add_4D_tensor_argument (unsigned int &idx, const ICLTensor *tensor, const Window &window)
Add the passed 4D tensor's parameters to the object's kernel's arguments starting from the index idx.
template<typename T >
void add_argument (unsigned int &idx, T value)
Add the passed parameters to the object's kernel's arguments starting from the index idx.
void set_lws_hint (const cl::NDRange &lws_hint)
Set the Local-Workgroup-Size hint.
cl::NDRange lws_hint () const
Return the Local-Workgroup-Size hint.
const std::string & config_id () const
Get the configuration ID.
void set_target (GPUTarget target)
Set the targeted GPU architecture.
void set_target (cl::Device &device)
Set the targeted GPU architecture according to the CL device.
GPUTarget get_target () const
Get the targeted GPU architecture.
size_t get_max_workgroup_size ()
Get the maximum workgroup size for the device the CLKernelLibrary uses.
template<typename T , unsigned int dimension_size>
void add_array_argument (unsigned &idx, const ICLArray< T > *array, const Strides &strides, unsigned int num_dimensions, const Window &window)
Add the passed array's parameters to the object's kernel's arguments starting from the index idx.
template<unsigned int dimension_size>
void add_tensor_argument (unsigned &idx, const ICLTensor *tensor, const Window &window)
Public Member Functions inherited from IKernel
IKernel ()
Constructor.
virtual ~IKernel ()=default
Destructor.
virtual bool is_parallelisable () const
Indicates whether or not the kernel is parallelisable.
const Window & window () const
The maximum window the kernel can be executed on.
Static Public Member Functions
static Status validate (ArithmeticOperation op, const ITensorInfo *input1, const ITensorInfo *input2, const ITensorInfo *output)
Static function to check if given info will lead to a valid configuration of CLArithmeticOperationKernel.
Static Public Member Functions inherited from ICLKernel
static constexpr unsigned int num_arguments_per_1D_array ()
Returns the number of arguments enqueued per 1D array object.
static constexpr unsigned int num_arguments_per_1D_tensor ()
Returns the number of arguments enqueued per 1D tensor object.
static constexpr unsigned int num_arguments_per_2D_tensor ()
Returns the number of arguments enqueued per 2D tensor object.
static constexpr unsigned int num_arguments_per_3D_tensor ()
Returns the number of arguments enqueued per 3D tensor object.
static constexpr unsigned int num_arguments_per_4D_tensor ()
Returns the number of arguments enqueued per 4D tensor object.
static cl::NDRange gws_from_window (const Window &window)
Get the global work size given an execution window.
Detailed Description
Definition at line 150 of file CLElementwiseOperationKernel.h.
Constructor & Destructor Documentation
CLArithmeticOperationKernel()
CLArithmeticOperationKernel () inline
Definition at line 153 of file CLElementwiseOperationKernel.h.
         : CLElementwiseOperationKernel(), _op()
     {
     }
Member Function Documentation
configure()
void configure (ArithmeticOperation op, const ICLTensor * input1, const ICLTensor * input2, ICLTensor * output)
Static function to check if given info will lead to a valid configuration of CLArithmeticOperationKernel.
Arithmetic operations.
Parameters
[in] op Arithmetic operation to be executed.
[in] input1 First tensor input. Data types supported: U8/S8/QASYMM8/U16/S16/QSYMM16/F16/U32/S32/F32.
[in] input2 Second tensor input. Data types supported: Same as input1.
[in] output Output tensor. Data types supported: Same as input1.
Definition at line 367 of file CLElementwiseOperationKernel.cpp.
 {
     _op = op;
     configure_common(input1, input2, output);
 }
validate()
Status validate (ArithmeticOperation op, const ITensorInfo * input1, const ITensorInfo * input2, const ITensorInfo * output) static
Static function to check if given info will lead to a valid configuration of CLArithmeticOperationKernel.
Parameters
[in] op Arithmetic operation to be executed.
[in] input1 First tensor input info. Data types supported: U8/S8/QASYMM8/U16/S16/QSYMM16/F16/U32/S32/F32.
[in] input2 Second tensor input info. Data types supported: Same as input1.
[in] output Output tensor info. Data types supported: Same as input1.
Returns
a Status
Definition at line 373 of file CLElementwiseOperationKernel.cpp.
 {
     ARM_COMPUTE_RETURN_ERROR_ON_NULLPTR(input1, input2, output);
     if(op == ArithmeticOperation::DIV || op == ArithmeticOperation::POWER)
     {
         // Division and Power operators don't support integer arithmetic
         ARM_COMPUTE_RETURN_ON_ERROR(validate_arguments_with_float_only_supported_rules(*input1, *input2, *output));
         ARM_COMPUTE_RETURN_ON_ERROR(validate_and_configure_window_for_division(*input1->clone(), *input2->clone(), *output->clone()).first);
     }
     else
     {
         ARM_COMPUTE_RETURN_ON_ERROR(validate_arguments_with_arithmetic_rules(*input1, *input2, *output));
         ARM_COMPUTE_RETURN_ON_ERROR(validate_and_configure_window_for_arithmetic_operators(*input1->clone(), *input2->clone(), *output->clone()).first);
     }
     return Status{};
 }
References ARM_COMPUTE_RETURN_ERROR_ON_NULLPTR, ARM_COMPUTE_RETURN_ON_ERROR, ICloneable< T >::clone(), arm_compute::DIV, and arm_compute::POWER.
Referenced by CLPReluLayer::validate(), CLArithmeticDivision::validate(), CLElementwiseMax::validate(), CLElementwiseMin::validate(), CLElementwiseSquaredDiff::validate(), and CLElementwisePower::validate().
The documentation for this class was generated from the following files:
arm_compute/core/CL/kernels/CLElementwiseOperationKernel.h
src/core/CL/kernels/CLElementwiseOperationKernel.cpp