Compute Library: CLGEMMMatrixVectorMultiplyKernel Class Reference
CLGEMMMatrixVectorMultiplyKernel Class Reference
Interface for the GEMM matrix vector multiply kernel.
#include <CLGEMMMatrixVectorMultiplyKernel.h>
Public Member Functions
CLGEMMMatrixVectorMultiplyKernel ()
Default constructor.
CLGEMMMatrixVectorMultiplyKernel (const CLGEMMMatrixVectorMultiplyKernel &)=delete
Prevent instances of this class from being copied (As this class contains pointers)
CLGEMMMatrixVectorMultiplyKernel & operator= (const CLGEMMMatrixVectorMultiplyKernel &)=delete
Prevent instances of this class from being copied (As this class contains pointers)
CLGEMMMatrixVectorMultiplyKernel (CLGEMMMatrixVectorMultiplyKernel &&)=default
Allow instances of this class to be moved.
CLGEMMMatrixVectorMultiplyKernel & operator= (CLGEMMMatrixVectorMultiplyKernel &&)=default
Allow instances of this class to be moved.
void configure (const ICLTensor *input0, const ICLTensor *input1, ICLTensor *output)
Set the input and output of the kernel.
void run (const Window &window, cl::CommandQueue &queue) override
Enqueue the OpenCL kernel to process the given window on the passed OpenCL command queue.
BorderSize border_size () const override
The size of the border for that kernel.
Public Member Functions inherited from ICLKernel
ICLKernel ()
Constructor.
cl::Kernel & kernel ()
Returns a reference to the OpenCL kernel of this object.
template<typename T >
void add_1D_array_argument (unsigned int &idx, const ICLArray< T > *array, const Strides &strides, unsigned int num_dimensions, const Window &window)
Add the passed 1D array's parameters to the object's kernel's arguments starting from the index idx.
void add_1D_tensor_argument (unsigned int &idx, const ICLTensor *tensor, const Window &window)
Add the passed 1D tensor's parameters to the object's kernel's arguments starting from the index idx.
void add_2D_tensor_argument (unsigned int &idx, const ICLTensor *tensor, const Window &window)
Add the passed 2D tensor's parameters to the object's kernel's arguments starting from the index idx.
void add_3D_tensor_argument (unsigned int &idx, const ICLTensor *tensor, const Window &window)
Add the passed 3D tensor's parameters to the object's kernel's arguments starting from the index idx.
void add_4D_tensor_argument (unsigned int &idx, const ICLTensor *tensor, const Window &window)
Add the passed 4D tensor's parameters to the object's kernel's arguments starting from the index idx.
template<typename T >
void add_argument (unsigned int &idx, T value)
Add the passed parameters to the object's kernel's arguments starting from the index idx.
void set_lws_hint (const cl::NDRange &lws_hint)
Set the Local-Workgroup-Size hint.
cl::NDRange lws_hint () const
Return the Local-Workgroup-Size hint.
const std::string & config_id () const
Get the configuration ID.
void set_target (GPUTarget target)
Set the targeted GPU architecture.
void set_target (cl::Device &device)
Set the targeted GPU architecture according to the CL device.
GPUTarget get_target () const
Get the targeted GPU architecture.
size_t get_max_workgroup_size ()
Get the maximum workgroup size for the device the CLKernelLibrary uses.
template<typename T , unsigned int dimension_size>
void add_array_argument (unsigned &idx, const ICLArray< T > *array, const Strides &strides, unsigned int num_dimensions, const Window &window)
Add the passed array's parameters to the object's kernel's arguments starting from the index idx.
template<unsigned int dimension_size>
void add_tensor_argument (unsigned &idx, const ICLTensor *tensor, const Window &window)
Public Member Functions inherited from IKernel
IKernel ()
Constructor.
virtual ~IKernel ()=default
Destructor.
virtual bool is_parallelisable () const
Indicates whether or not the kernel is parallelisable.
const Window & window () const
The maximum window the kernel can be executed on.
Static Public Member Functions
static Status validate (const ITensorInfo *input0, const ITensorInfo *input1, const ITensorInfo *output)
Static function to check if given info will lead to a valid configuration of CLGEMMMatrixVectorMultiplyKernel.
Static Public Member Functions inherited from ICLKernel
static constexpr unsigned int num_arguments_per_1D_array ()
Returns the number of arguments enqueued per 1D array object.
static constexpr unsigned int num_arguments_per_1D_tensor ()
Returns the number of arguments enqueued per 1D tensor object.
static constexpr unsigned int num_arguments_per_2D_tensor ()
Returns the number of arguments enqueued per 2D tensor object.
static constexpr unsigned int num_arguments_per_3D_tensor ()
Returns the number of arguments enqueued per 3D tensor object.
static constexpr unsigned int num_arguments_per_4D_tensor ()
Returns the number of arguments enqueued per 4D tensor object.
static cl::NDRange gws_from_window (const Window &window)
Get the global work size given an execution window.
Detailed Description
Interface for the GEMM matrix vector multiply kernel.
Definition at line 34 of file CLGEMMMatrixVectorMultiplyKernel.h.
Constructor & Destructor Documentation
CLGEMMMatrixVectorMultiplyKernel() [1/3]
CLGEMMMatrixVectorMultiplyKernel ()
Default constructor.
Definition at line 74 of file CLGEMMMatrixVectorMultiplyKernel.cpp.
     : _input0(nullptr), _input1(nullptr), _output(nullptr), _num_rows_read_per_iteration(0), _border_size(0)
 {
 }
CLGEMMMatrixVectorMultiplyKernel() [2/3]
CLGEMMMatrixVectorMultiplyKernel (const CLGEMMMatrixVectorMultiplyKernel &) delete
Prevent instances of this class from being copied (As this class contains pointers)
CLGEMMMatrixVectorMultiplyKernel() [3/3]
CLGEMMMatrixVectorMultiplyKernel (CLGEMMMatrixVectorMultiplyKernel &&) default
Allow instances of this class to be moved.
Member Function Documentation
border_size()
BorderSize border_size () const override virtual
The size of the border for that kernel.
Returns
The width in number of elements of the border.
Reimplemented from IKernel.
Definition at line 78 of file CLGEMMMatrixVectorMultiplyKernel.cpp.
 {
     return _border_size;
 }
Referenced by CLDepthwiseConvolutionLayer::configure(), and CLGEMMMatrixVectorMultiplyKernel::run().
configure()
void configure (const ICLTensor * input0, const ICLTensor * input1, ICLTensor * output)
Set the input and output of the kernel.
Parameters
[in] input0 The reshaped input tensor. Data types supported: QASYMM8/F16/F32
[in] input1 The 2D reshaped weights tensor. Data type supported: Same as input, S32 for QASYMM8 input.
[out] output The output 2D tensor. Data types supported: Same as input
Definition at line 83 of file CLGEMMMatrixVectorMultiplyKernel.cpp.
 {
     ARM_COMPUTE_ERROR_ON_NULLPTR(input0, input1, output);
     ARM_COMPUTE_ERROR_THROW_ON(validate_arguments(input0->info(), input1->info(), output->info()));
     _input0 = input0;
     _input1 = input1;
     _output = output;
     // Check if is a quantized operation
     bool is_quantized = is_data_type_quantized_asymmetric(_input0->info()->data_type());
     // Create kernel
     CLBuildOptions build_opts;
     build_opts.add_option_if(!is_quantized, "-DDATA_TYPE=" + get_cl_type_from_data_type(input0->info()->data_type()));
     build_opts.add_option("-DSRC_WIDTH=" + support::cpp11::to_string(input0->info()->dimension(0)));
     build_opts.add_option("-DSRC_HEIGHT=" + support::cpp11::to_string(input0->info()->dimension(1)));
     std::string kernel_name = is_quantized ? std::string("gemm_mv_quantized") : std::string("gemm_mv");
     _kernel                 = static_cast<cl::Kernel>(CLKernelLibrary::get().create_kernel(kernel_name, build_opts.options()));
     // Add static arguments
     if(is_quantized)
     {
         unsigned int idx = num_arguments_per_3D_tensor() + num_arguments_per_2D_tensor() + num_arguments_per_1D_tensor();
         _kernel.setArg<int>(idx++, -_input0->info()->quantization_info().offset);
         _kernel.setArg<int>(idx++, -_input1->info()->quantization_info().offset);
     }
     // Configure kernel window
     const unsigned int num_elems_read_per_iteration = 4;
     _num_rows_read_per_iteration = 4;
     const unsigned int border_x = ceil_to_multiple(input0->info()->dimension(0), num_elems_read_per_iteration) - input0->info()->dimension(0);
     const unsigned int border_y = ceil_to_multiple(input0->info()->dimension(1), _num_rows_read_per_iteration) - input0->info()->dimension(1);
     _border_size = BorderSize(border_y, border_x);
     auto win_config = validate_and_configure_window(input0->info(), input1->info(), output->info());
     ARM_COMPUTE_ERROR_THROW_ON(win_config.first);
     ICLKernel::configure_internal(win_config.second);
 }
References CLBuildOptions::add_option_if(), ARM_COMPUTE_ERROR_ON_NULLPTR, ARM_COMPUTE_ERROR_THROW_ON, arm_compute::ceil_to_multiple(), arm_compute::create_kernel(), ITensorInfo::data_type(), ITensorInfo::dimension(), CLKernelLibrary::get(), arm_compute::get_cl_type_from_data_type(), ITensor::info(), arm_compute::is_data_type_quantized_asymmetric(), ICLKernel::num_arguments_per_1D_tensor(), ICLKernel::num_arguments_per_2D_tensor(), ICLKernel::num_arguments_per_3D_tensor(), QuantizationInfo::offset, ITensorInfo::quantization_info(), and arm_compute::support::cpp11::to_string().
Referenced by CLDepthwiseConvolutionLayer::configure().
operator=() [1/2]
CLGEMMMatrixVectorMultiplyKernel& operator= (const CLGEMMMatrixVectorMultiplyKernel &) delete
Prevent instances of this class from being copied (As this class contains pointers)
operator=() [2/2]
CLGEMMMatrixVectorMultiplyKernel& operator= (CLGEMMMatrixVectorMultiplyKernel &&) default
Allow instances of this class to be moved.
run()
void run (const Window & window, cl::CommandQueue & queue) override virtual
Enqueue the OpenCL kernel to process the given window on the passed OpenCL command queue.
Note
The queue is not flushed by this method, and therefore the kernel will not have been executed by the time this method returns.
Parameters
[in] window Region on which to execute the kernel. (Must be a valid region of the window returned by window()).
[in,out] queue Command queue on which to enqueue the kernel.
Implements ICLKernel.
Definition at line 135 of file CLGEMMMatrixVectorMultiplyKernel.cpp.
 {
     ARM_COMPUTE_ERROR_ON_UNCONFIGURED_KERNEL(this);
     ARM_COMPUTE_ERROR_ON_MISMATCHING_WINDOWS(ICLKernel::window(), window);
     Window slice_in  = window.first_slice_window_3D();
     Window slice_in2 = window.first_slice_window_3D();
     Window slice_out = window.first_slice_window_3D();
     // Setup input0 slice
     slice_in.set(Window::DimX, Window::Dimension(0, _input0->info()->dimension(0), _input0->info()->dimension(0)));
     slice_in.set(Window::DimY, Window::Dimension(0, _input0->info()->dimension(1) + border_size().bottom, _num_rows_read_per_iteration));
     slice_in.set(Window::DimZ, Window::Dimension(0, _input0->info()->dimension(2), 1));
     // Setup input1 and output slice. Their dimensions are increased in the cl kernel.
     slice_in2.set(Window::DimX, Window::Dimension(0, 0, 0));
     slice_in2.set(Window::DimY, Window::Dimension(0, 0, 0));
     slice_in2.set(Window::DimZ, Window::Dimension(0, 0, 0));
     slice_out.set(Window::DimX, Window::Dimension(0, 0, 0));
     slice_out.set(Window::DimY, Window::Dimension(0, 0, 0));
     slice_out.set(Window::DimZ, Window::Dimension(0, 0, 0));
     unsigned int idx_1 = num_arguments_per_3D_tensor();
     add_2D_tensor_argument(idx_1, _input1, slice_in2);
     do
     {
         unsigned int idx_0 = 0;
         unsigned int idx_2 = num_arguments_per_3D_tensor() + num_arguments_per_2D_tensor();
         add_3D_tensor_argument(idx_0, _input0, slice_in);
         add_1D_tensor_argument(idx_2, _output, slice_out);
         enqueue(queue, *this, slice_in, lws_hint());
     }
     while(window.slide_window_slice_3D(slice_in) && window.slide_window_slice_3D(slice_out));
 }
References ICLKernel::add_1D_tensor_argument(), ICLKernel::add_2D_tensor_argument(), ICLKernel::add_3D_tensor_argument(), ARM_COMPUTE_ERROR_ON_MISMATCHING_WINDOWS, ARM_COMPUTE_ERROR_ON_UNCONFIGURED_KERNEL, CLGEMMMatrixVectorMultiplyKernel::border_size(), BorderSize::bottom, ITensorInfo::dimension(), Window::DimX, Window::DimY, Window::DimZ, arm_compute::enqueue(), Window::first_slice_window_3D(), ITensor::info(), ICLKernel::lws_hint(), ICLKernel::num_arguments_per_2D_tensor(), ICLKernel::num_arguments_per_3D_tensor(), Window::set(), Window::slide_window_slice_3D(), and IKernel::window().
validate()
Status validate (const ITensorInfo * input0, const ITensorInfo * input1, const ITensorInfo * output) static
Static function to check if given info will lead to a valid configuration of CLGEMMMatrixVectorMultiplyKernel.
Parameters
[in] input0 The reshaped input tensor. Data types supported: QASYMM8/F16/F32
[in] input1 The 2D reshaped weights tensor. Data type supported: Same as input, S32 for QASYMM8 input.
[in] output The output 2D tensor. Data types supported: Same as input
Returns
a status
Definition at line 127 of file CLGEMMMatrixVectorMultiplyKernel.cpp.
 {
     ARM_COMPUTE_RETURN_ON_ERROR(validate_arguments(input0, input1, output));
     ARM_COMPUTE_RETURN_ON_ERROR(validate_and_configure_window(input0->clone().get(), input1->clone().get(), output->clone().get()).first);
     return Status{};
 }
References ARM_COMPUTE_RETURN_ON_ERROR, and ICloneable< T >::clone().
Referenced by CLDepthwiseConvolutionLayer::validate().
The documentation for this class was generated from the following files:
arm_compute/core/CL/kernels/CLGEMMMatrixVectorMultiplyKernel.h
src/core/CL/kernels/CLGEMMMatrixVectorMultiplyKernel.cpp