Compute Library: NEBatchToSpaceLayerKernel Class Reference
NEBatchToSpaceLayerKernel Class Reference
Interface for the batch to space kernel.
#include <NEBatchToSpaceLayerKernel.h>
Public Member Functions
const char * name () const override
Name of the kernel.
NEBatchToSpaceLayerKernel ()
Default constructor.
NEBatchToSpaceLayerKernel (const NEBatchToSpaceLayerKernel &)=delete
Prevent instances of this class from being copied (As this class contains pointers)
NEBatchToSpaceLayerKernel & operator= (const NEBatchToSpaceLayerKernel &)=delete
Prevent instances of this class from being copied (As this class contains pointers)
NEBatchToSpaceLayerKernel (NEBatchToSpaceLayerKernel &&)=default
Allow instances of this class to be moved.
NEBatchToSpaceLayerKernel & operator= (NEBatchToSpaceLayerKernel &&)=default
Allow instances of this class to be moved.
~NEBatchToSpaceLayerKernel ()=default
Default destructor.
void configure (const ITensor *input, const ITensor *block_shape, ITensor *output)
Initialise the kernel's inputs and output.
void configure (const ITensor *input, const int32_t block_shape_x, const int32_t block_shape_y, ITensor *output)
Initialise the kernel's inputs and output (Static block shape).
void run (const Window &window, const ThreadInfo &info) override
Execute the kernel on the passed window.
Public Member Functions inherited from ICPPKernel
virtual ~ICPPKernel ()=default
Default destructor.
Public Member Functions inherited from IKernel
IKernel ()
Constructor.
virtual ~IKernel ()=default
Destructor.
virtual bool is_parallelisable () const
Indicates whether or not the kernel is parallelisable.
virtual BorderSize border_size () const
The size of the border for that kernel.
const Window & window () const
The maximum window the kernel can be executed on.
Static Public Member Functions
static Status validate (const ITensorInfo *input, const ITensorInfo *block_shape, const ITensorInfo *output)
Static function to check if given info will lead to a valid configuration of NEBatchToSpaceLayerKernel.
static Status validate (const ITensorInfo *input, const int32_t block_shape_x, const int32_t block_shape_y, const ITensorInfo *output)
Static function to check if given info will lead to a valid configuration of NEBatchToSpaceLayerKernel (Static block shape).
Detailed Description
Interface for the batch to space kernel.
Definition at line 34 of file NEBatchToSpaceLayerKernel.h.
Constructor & Destructor Documentation
NEBatchToSpaceLayerKernel() [1/3]
NEBatchToSpaceLayerKernel ()
Default constructor.
Definition at line 83 of file NEBatchToSpaceLayerKernel.cpp.
     : _input(nullptr), _block_shape(nullptr), _output(nullptr), _block_shape_x(), _block_shape_y()
 {
 }
NEBatchToSpaceLayerKernel() [2/3]
NEBatchToSpaceLayerKernel (const NEBatchToSpaceLayerKernel &) delete
Prevent instances of this class from being copied (As this class contains pointers)
NEBatchToSpaceLayerKernel() [3/3]
NEBatchToSpaceLayerKernel (NEBatchToSpaceLayerKernel &&) default
Allow instances of this class to be moved.
~NEBatchToSpaceLayerKernel()
~NEBatchToSpaceLayerKernel () default
Default destructor.
Member Function Documentation
configure() [1/2]
void configure (const ITensor * input, const ITensor * block_shape, ITensor * output)
Initialise the kernel's inputs and output.
Parameters
[in] input Tensor input. Supported tensor rank: 4. Data types supported: U8/S8/QASYMM8/U16/S16/F16/U32/S32/F32.
[in] block_shape 1-D tensor with shape [M]. Data types supported: S32
[out] output Tensor output. Data types supported: same as input
Definition at line 88 of file NEBatchToSpaceLayerKernel.cpp.
 {
     ARM_COMPUTE_ERROR_ON_NULLPTR(input, output);
     ARM_COMPUTE_ERROR_THROW_ON(validate_arguments(input->info(), block_shape->info(), output->info()));
     _input       = input;
     _block_shape = block_shape;
     _output      = output;
     // Configure kernel window
     Window win = calculate_max_window(*input->info(), Steps());
     ICPPKernel::configure(win);
 }
References ARM_COMPUTE_ERROR_ON_NULLPTR, ARM_COMPUTE_ERROR_THROW_ON, arm_compute::calculate_max_window(), and ITensor::info().
configure() [2/2]
void configure (const ITensor * input, const int32_t block_shape_x, const int32_t block_shape_y, ITensor * output)
Initialise the kernel's inputs and output (Static block shape).
Parameters
[in] input Tensor input. Supported tensor rank: 4. Data types supported: U8/S8/QASYMM8/U16/S16/F16/U32/S32/F32.
[in] block_shape_x Block shape x value.
[in] block_shape_y Block shape y value.
[out] output Tensor output. Data types supported: same as input
Definition at line 102 of file NEBatchToSpaceLayerKernel.cpp.
 {
     ARM_COMPUTE_ERROR_ON_NULLPTR(input, output);
     TensorShape output_shape = compute_batch_to_space_shape(input->info(), block_shape_x, block_shape_y);
     // Output auto inizialitation if not yet initialized
     auto_init_if_empty(*output->info(), input->info()->clone()->set_tensor_shape(output_shape));
     // Perform validation step
     ARM_COMPUTE_ERROR_THROW_ON(validate_arguments_static(input->info(), block_shape_x, block_shape_y, output->info()));
     _input         = input;
     _output        = output;
     _block_shape_x = block_shape_x;
     _block_shape_y = block_shape_y;
     // Configure kernel window
     Window win = calculate_max_window(*input->info(), Steps());
     ICPPKernel::configure(win);
 }
References ARM_COMPUTE_ERROR_ON_NULLPTR, ARM_COMPUTE_ERROR_THROW_ON, arm_compute::auto_init_if_empty(), arm_compute::calculate_max_window(), ICloneable< T >::clone(), arm_compute::misc::shape_calculator::compute_batch_to_space_shape(), ITensor::info(), and arm_compute::test::validation::output_shape.
name()
const char* name () const inline override virtual
Name of the kernel.
Returns
Kernel name
Implements ICPPKernel.
Definition at line 37 of file NEBatchToSpaceLayerKernel.h.
     {
         return "NEBatchToSpaceLayerKernel";
     }
operator=() [1/2]
NEBatchToSpaceLayerKernel& operator= (const NEBatchToSpaceLayerKernel &) delete
Prevent instances of this class from being copied (As this class contains pointers)
operator=() [2/2]
NEBatchToSpaceLayerKernel& operator= (NEBatchToSpaceLayerKernel &&) default
Allow instances of this class to be moved.
run()
void run (const Window & window, const ThreadInfo & info) override virtual
Execute the kernel on the passed window.
Warning
If is_parallelisable() returns false then the passed window must be equal to window()
Note
The window has to be a region within the window returned by the window() method
The width of the window has to be a multiple of num_elems_processed_per_iteration().
Parameters
[in] window Region on which to execute the kernel. (Must be a region of the window returned by window())
[in] info Info about executing thread and CPU.
Implements ICPPKernel.
Definition at line 136 of file NEBatchToSpaceLayerKernel.cpp.
 {
     ARM_COMPUTE_UNUSED(info);
     ARM_COMPUTE_ERROR_ON_UNCONFIGURED_KERNEL(this);
     ARM_COMPUTE_ERROR_ON_INVALID_SUBWINDOW(ICPPKernel::window(), window);
     if(_block_shape != nullptr)
     {
         // Retrieve the block shapes dynamically
         _block_shape_x = *(reinterpret_cast<const int *>(_block_shape->ptr_to_element(0)));
         _block_shape_y = *(reinterpret_cast<const int *>(_block_shape->ptr_to_element(1)));
     }
     const int batch_size   = _input->info()->dimension(3);
     const int r            = (batch_size / (_block_shape_x * _block_shape_y));
     const int element_size = _input->info()->element_size();
     Window slice_in  = window.first_slice_window_3D();
     Window slice_out = window.first_slice_window_4D();
     // The slice_out slice does not move
     slice_out.set(Window::DimX, Window::Dimension(0, 0, 0));
     slice_out.set(Window::DimY, Window::Dimension(0, 0, 0));
     slice_out.set(Window::DimZ, Window::Dimension(0, 0, 0));
     slice_out.set(3, Window::Dimension(0, 0, 0));
     int batch_id = 0;
     // Main loop for NCHW and NHWC
     if(_input->info()->data_layout() == DataLayout::NCHW)
     {
         do
         {
             Iterator in(_input, slice_in);
             execute_window_loop(slice_in, [&](const Coordinates & id)
             {
                 const int x = id.x();
                 const int y = id.y();
                 const int z = id.z();
                 const int   w     = batch_id % r;
                 const int   out_x = x * _block_shape_x + (batch_id / r) % _block_shape_x;
                 const int   out_y = y * _block_shape_y + (batch_id / r) / _block_shape_x;
                 Coordinates output_coords{ out_x, out_y, z, w };
                 memcpy(_output->ptr_to_element(output_coords), in.ptr(), element_size);
             },
             in);
             ++batch_id;
         }
         while(window.slide_window_slice_3D(slice_in));
     }
     else
     {
         do
         {
             Iterator in(_input, slice_in);
             execute_window_loop(slice_in, [&](const Coordinates & id)
             {
                 const int z = id.x();
                 const int x = id.y();
                 const int y = id.z();
                 const int   w     = batch_id % r;
                 const int   out_x = x * _block_shape_x + (batch_id / r) % _block_shape_x;
                 const int   out_y = y * _block_shape_y + (batch_id / r) / _block_shape_x;
                 Coordinates output_coords{ z, out_x, out_y, w };
                 memcpy(_output->ptr_to_element(output_coords), in.ptr(), element_size);
             },
             in);
             ++batch_id;
         }
         while(window.slide_window_slice_3D(slice_in));
     }
 }
References ARM_COMPUTE_ERROR_ON_INVALID_SUBWINDOW, ARM_COMPUTE_ERROR_ON_UNCONFIGURED_KERNEL, ARM_COMPUTE_UNUSED, ITensorInfo::data_layout(), ITensorInfo::dimension(), Window::DimX, Window::DimY, Window::DimZ, ITensorInfo::element_size(), arm_compute::execute_window_loop(), Window::first_slice_window_3D(), Window::first_slice_window_4D(), ITensor::info(), arm_compute::test::validation::info, arm_compute::NCHW, Iterator::ptr(), ITensor::ptr_to_element(), Window::set(), Window::slide_window_slice_3D(), arm_compute::test::validation::w, IKernel::window(), and Window::x().
validate() [1/2]
Status validate (const ITensorInfo * input, const ITensorInfo * block_shape, const ITensorInfo * output) static
Static function to check if given info will lead to a valid configuration of NEBatchToSpaceLayerKernel.
Parameters
[in] input Tensor input. Supported tensor rank: 4. Data types supported: U8/S8/QASYMM8/U16/S16/F16/U32/S32/F32.
[in] block_shape 1-D tensor with shape [M]. Data types supported: S32
[in] output Tensor output. Data types supported: same as input
Returns
a status
Definition at line 122 of file NEBatchToSpaceLayerKernel.cpp.
 {
     ARM_COMPUTE_RETURN_ERROR_ON_NULLPTR(input, block_shape, output);
     ARM_COMPUTE_RETURN_ON_ERROR(validate_arguments(input, block_shape, output));
     return Status{};
 }
References ARM_COMPUTE_RETURN_ERROR_ON_NULLPTR, and ARM_COMPUTE_RETURN_ON_ERROR.
Referenced by NEBatchToSpaceLayer::validate().
validate() [2/2]
Status validate (const ITensorInfo * input, const int32_t block_shape_x, const int32_t block_shape_y, const ITensorInfo * output) static
Static function to check if given info will lead to a valid configuration of NEBatchToSpaceLayerKernel (Static block shape).
Parameters
[in] input Tensor input. Supported tensor rank: 4. Data types supported: U8/S8/QASYMM8/U16/S16/F16/U32/S32/F32.
[in] block_shape_x Block shape x value.
[in] block_shape_y Block shape y value.
[in] output Tensor output. Data types supported: same as input
Returns
a status
Definition at line 129 of file NEBatchToSpaceLayerKernel.cpp.
 {
     ARM_COMPUTE_RETURN_ERROR_ON_NULLPTR(input, output);
     ARM_COMPUTE_RETURN_ON_ERROR(validate_arguments_static(input, block_shape_x, block_shape_y, output));
     return Status{};
 }
References ARM_COMPUTE_RETURN_ERROR_ON_NULLPTR, and ARM_COMPUTE_RETURN_ON_ERROR.
The documentation for this class was generated from the following files:
arm_compute/core/NEON/kernels/NEBatchToSpaceLayerKernel.h
src/core/NEON/kernels/NEBatchToSpaceLayerKernel.cpp