Compute Library: Scheduler Class Reference
Scheduler Class Reference
Configurable scheduler which supports multiple multithreading APIs and choosing between different schedulers at runtime.
#include <Scheduler.h>
Public Types
enum Type { ST, CPP, OMP, CUSTOM }
Scheduler type.
Static Public Member Functions
static void set (std::shared_ptr< IScheduler > scheduler)
Sets the user defined scheduler and makes it the active scheduler.
static IScheduler & get ()
Access the scheduler singleton.
static void set (Type t)
Set the active scheduler.
static Type get_type ()
Returns the type of the active scheduler.
static bool is_available (Type t)
Returns true if the given scheduler type is supported.
Detailed Description
Configurable scheduler which supports multiple multithreading APIs and choosing between different schedulers at runtime.
Definition at line 33 of file Scheduler.h.
Member Enumeration Documentation
Type
enum Type strong
Scheduler type.
Enumerator
ST
Single thread.
CPP
C++11 threads.
OMP
OpenMP.
CUSTOM
Provided by the user.
Definition at line 37 of file Scheduler.h.
     {
         ST,
         CPP,
         OMP,
         CUSTOM
     };
Member Function Documentation
get()
IScheduler & get () static
Access the scheduler singleton.
Returns
A reference to the scheduler object.
Definition at line 96 of file Scheduler.cpp.
 {
     switch(_scheduler_type)
     {
         case Type::ST:
         {
             return SingleThreadScheduler::get();
         }
         case Type::CPP:
         {
 #if ARM_COMPUTE_CPP_SCHEDULER
             return CPPScheduler::get();
 #else  /* ARM_COMPUTE_CPP_SCHEDULER */
             ARM_COMPUTE_ERROR("Recompile with cppthreads=1 to use C++11 scheduler.");
 #endif /* ARM_COMPUTE_CPP_SCHEDULER */
             break;
         }
         case Type::OMP:
         {
 #if ARM_COMPUTE_OPENMP_SCHEDULER
             return OMPScheduler::get();
 #else  /* ARM_COMPUTE_OPENMP_SCHEDULER */
             ARM_COMPUTE_ERROR("Recompile with openmp=1 to use openmp scheduler.");
 #endif /* ARM_COMPUTE_OPENMP_SCHEDULER */
             break;
         }
         case Type::CUSTOM:
         {
             if(_custom_scheduler == nullptr)
             {
                 ARM_COMPUTE_ERROR("No custom scheduler has been setup. Call set(std::shared_ptr<IScheduler> &scheduler) before Scheduler::get()");
             }
             else
             {
                 return *_custom_scheduler;
             }
             break;
         }
         default:
         {
             ARM_COMPUTE_ERROR("Invalid Scheduler type");
             break;
         }
     }
     return SingleThreadScheduler::get();
 }
References ARM_COMPUTE_ERROR, Scheduler::CPP, Scheduler::CUSTOM, OMPScheduler::get(), SingleThreadScheduler::get(), CPPScheduler::get(), Scheduler::OMP, and Scheduler::ST.
Referenced by NEHistogram::configure(), NEDepthwiseConvolutionAssemblyDispatch::configure(), NEWinogradConvolutionLayer::configure(), NEGEMMInterleavedWrapper::configure(), main(), NEWinogradConvolutionLayer::prepare(), NELocallyConnectedLayer::prepare(), NEGEMM::prepare(), NEGEMMLowpMatrixMultiplyCore::prepare(), NEDeconvolutionLayer::prepare(), NEGEMMInterleavedWrapper::prepare(), NEDepthwiseConvolutionLayer::prepare(), INESimpleFunctionNoBorder::run(), ICPPSimpleFunction::run(), INESimpleFunction::run(), NESimpleAssemblyFunction::run(), NEHistogram::run(), NEFillBorder::run(), NEMeanStdDev::run(), NEGEMMLowpAssemblyMatrixMultiplyCore::run(), NEConvertFullyConnectedWeights::run(), NEHOGDescriptor::run(), NEDerivative::run(), NEEqualizeHistogram::run(), NEROIPoolingLayer::run(), NEMinMaxLocation::run(), NEHOGGradient::run(), NERange::run(), NEGaussian5x5::run(), NEUpsampleLayer::run(), NESobel7x7::run(), NESobel5x5::run(), NEArgMinMaxLayer::run(), NEReductionOperation::run(), NEPoolingLayer::run(), NEFastCorners::run(), NEFFT1D::run(), NEL2NormalizeLayer::run(), NEStackLayer::run(), NESpaceToDepthLayer::run(), NEConvolutionLayerReshapeWeights::run(), NEIm2Col::run(), NENormalizationLayer::run(), NEPadLayer::run(), NEScale::run(), NEWinogradConvolutionLayer::run(), NERNNLayer::run(), NEConcatenateLayer::run(), NECannyEdge::run(), NEBatchNormalizationLayer::run(), NEOpticalFlow::run(), CLHarrisCorners::run(), NEHarrisCorners::run(), NESoftmaxLayer::run(), NEConvolutionSquare< matrix_size >::run(), NEHOGMultiDetection::run(), CLHOGMultiDetection::run(), NEGaussianPyramidHalf::run(), NELocallyConnectedLayer::run(), NECropResize::run(), NEGEMM::run(), NEFuseBatchNormalization::run(), NEDirectConvolutionLayer::run(), NESpaceToBatchLayer::run(), NEGEMMLowpMatrixMultiplyCore::run(), NEDepthwiseConvolutionAssemblyDispatch::run(), NEGEMMInterleavedWrapper::run(), NEFullyConnectedLayer::run(), NELSTMLayer::run(), NEGEMMConvolutionLayer::run(), NEDepthwiseConvolutionLayer::run(), NEDeviceBackend::setup_backend_context(), and SchedulerClock< output_timestamps >::test_start().
get_type()
Scheduler::Type get_type () static
Returns the type of the active scheduler.
Returns
The current scheduler's type.
Definition at line 91 of file Scheduler.cpp.
 {
     return _scheduler_type;
 }
Referenced by SchedulerClock< output_timestamps >::test_start().
is_available()
bool is_available (Type t) static
Returns true if the given scheduler type is supported.
False otherwise.
Parameters
[in] t the type of the scheduler to check.
Returns
true if the given scheduler type is supported. False otherwise.
Definition at line 55 of file Scheduler.cpp.
 {
     switch(t)
     {
         case Type::ST:
         {
             return true;
         }
         case Type::CPP:
         {
 #if ARM_COMPUTE_CPP_SCHEDULER
             return true;
 #else  /* ARM_COMPUTE_CPP_SCHEDULER */
             return false;
 #endif /* ARM_COMPUTE_CPP_SCHEDULER */
         }
         case Type::OMP:
         {
 #if ARM_COMPUTE_OPENMP_SCHEDULER
             return true;
 #else  /* ARM_COMPUTE_OPENMP_SCHEDULER */
             return false;
 #endif /* ARM_COMPUTE_OPENMP_SCHEDULER */
         }
         case Type::CUSTOM:
         {
             return _custom_scheduler != nullptr;
         }
         default:
         {
             ARM_COMPUTE_ERROR("Invalid Scheduler type");
             return false;
         }
     }
 }
References ARM_COMPUTE_ERROR, Scheduler::CPP, Scheduler::CUSTOM, Scheduler::OMP, and Scheduler::ST.
Referenced by Scheduler::set().
set() [1/2]
void set (std::shared_ptr< IScheduler > scheduler) static
Sets the user defined scheduler and makes it the active scheduler.
Parameters
[in] scheduler A shared pointer to a custom scheduler implemented by the user.
Definition at line 145 of file Scheduler.cpp.
 {
     _custom_scheduler = std::move(scheduler);
     set(Type::CUSTOM);
 }
References Scheduler::CUSTOM.
Referenced by SchedulerClock< output_timestamps >::test_start(), and SchedulerClock< output_timestamps >::test_stop().
set() [2/2]
void set (Type t) static
Set the active scheduler.
Only one scheduler can be enabled at any time.
Parameters
[in] t the type of the scheduler to be enabled.
Definition at line 49 of file Scheduler.cpp.
 {
     ARM_COMPUTE_ERROR_ON(!Scheduler::is_available(t));
     _scheduler_type = t;
 }
References ARM_COMPUTE_ERROR_ON, and Scheduler::is_available().
The documentation for this class was generated from the following files:
arm_compute/runtime/Scheduler.h
src/runtime/Scheduler.cpp