Compute Library: NEGEMMLowpOffsetContributionKernel Class Reference
NEGEMMLowpOffsetContributionKernel Class Reference
NEON kernel used to add the offset contribution after NEGEMMLowpMatrixMultiplyKernel.
#include <NEGEMMLowpOffsetContributionKernel.h>
Public Member Functions
const char * name () const override
Name of the kernel.
NEGEMMLowpOffsetContributionKernel ()
Constructor.
NEGEMMLowpOffsetContributionKernel (const NEGEMMLowpOffsetContributionKernel &)=delete
Prevent instances of this class from being copied (As this class contains pointers)
NEGEMMLowpOffsetContributionKernel & operator= (const NEGEMMLowpOffsetContributionKernel &)=delete
Prevent instances of this class from being copied (As this class contains pointers)
NEGEMMLowpOffsetContributionKernel (NEGEMMLowpOffsetContributionKernel &&)=default
Allow instances of this class to be moved.
NEGEMMLowpOffsetContributionKernel & operator= (NEGEMMLowpOffsetContributionKernel &&)=default
Allow instances of this class to be moved.
void configure (ITensor *mm_result, const ITensor *vector_sum_col, const ITensor *vector_sum_row, int32_t k, int32_t a_offset, int32_t b_offset)
Initialise the kernel's input and output.
void run (const Window &window, const ThreadInfo &info) override
Execute the kernel on the passed window.
Public Member Functions inherited from ICPPKernel
virtual ~ICPPKernel ()=default
Default destructor.
Public Member Functions inherited from IKernel
IKernel ()
Constructor.
virtual ~IKernel ()=default
Destructor.
virtual bool is_parallelisable () const
Indicates whether or not the kernel is parallelisable.
virtual BorderSize border_size () const
The size of the border for that kernel.
const Window & window () const
The maximum window the kernel can be executed on.
Static Public Member Functions
static Status validate (const ITensorInfo *mm_result, const ITensorInfo *vector_sum_col, const ITensorInfo *vector_sum_row, int32_t a_offset, int32_t b_offset)
Static function to check if given info will lead to a valid configuration of NEGEMMLowpOffsetContributionKernel.
Detailed Description
NEON kernel used to add the offset contribution after NEGEMMLowpMatrixMultiplyKernel.
The computation is performed in-place
This kernel takes a final int32 accumulator value (the output of NEGEMMLowpMatrixMultiplyKernel), and adds to it the offset contribution of matrix A and matrix B in-place.
The final result is:
mm_result[i][k] = mm_result[i][k] + (vector_sum_col[k] * a_offset) + (vector_sum_row[i] * b_offset) + (a_offset * b_offset * k)
Definition at line 46 of file NEGEMMLowpOffsetContributionKernel.h.
Constructor & Destructor Documentation
NEGEMMLowpOffsetContributionKernel() [1/3]
NEGEMMLowpOffsetContributionKernel ()
Constructor.
Definition at line 341 of file NEGEMMLowpOffsetContributionKernel.cpp.
     : _vector_sum_col(nullptr), _vector_sum_row(nullptr), _mm_result(nullptr), _a_offset(0), _b_offset(0), _k_offset(0), _slide_vector_sum_col(true)
 {
 }
NEGEMMLowpOffsetContributionKernel() [2/3]
NEGEMMLowpOffsetContributionKernel (const NEGEMMLowpOffsetContributionKernel &) delete
Prevent instances of this class from being copied (As this class contains pointers)
NEGEMMLowpOffsetContributionKernel() [3/3]
NEGEMMLowpOffsetContributionKernel (NEGEMMLowpOffsetContributionKernel &&) default
Allow instances of this class to be moved.
Member Function Documentation
configure()
void configure (ITensor * mm_result, const ITensor * vector_sum_col, const ITensor * vector_sum_row, int32_t k, int32_t a_offset, int32_t b_offset)
Initialise the kernel's input and output.
Parameters
[in,out] mm_result Input tensor containing the result of NEGEMMLowpMatrixMultiplyKernel. Data type supported: S32
[in] vector_sum_col Input row-vector of sums of all the entries in each column of matrix B. Note: vector_sum_col can be a nullptr in case a_offset = 0. Data type supported: same as mm_result
[in] vector_sum_row Input row-vector of sums of all the entries in each row of matrix A. Note: vector_sum_row can be a nullptr in case b_offset = 0. Data type supported: same as mm_result
[in] k Number of matrix A columns or Matrix B rows
[in] a_offset Offset to be added to each element of the matrix A.
[in] b_offset Offset to be added to each element of the matrix B.
Definition at line 346 of file NEGEMMLowpOffsetContributionKernel.cpp.
 {
     // Perform validate step
     ARM_COMPUTE_ERROR_ON_NULLPTR(mm_result);
     ARM_COMPUTE_ERROR_THROW_ON(validate_arguments(mm_result->info(),
                                                   vector_sum_col != nullptr ? vector_sum_col->info() : nullptr, // NOLINT
                                                   vector_sum_row != nullptr ? vector_sum_row->info() : nullptr, // NOLINT
                                                   a_offset, b_offset));                                         // NOLINT
     _vector_sum_col = vector_sum_col;
     _vector_sum_row = vector_sum_row;
     _mm_result      = mm_result;
     _a_offset       = a_offset;
     _b_offset       = b_offset;
     _k_offset       = a_offset * b_offset * k;
     // If a_offset == 0, vector_sum_col can be a nullptr
     if(a_offset != 0)
     {
         // Check if vector_sum_col_shape should be slidden or not
         // Don't slide vector_sum_col_shape along the y dimension if vector_sum_col_shape has just 1 dimension and vector_sum_row_shape more than 1
         // This scenario can happen when the the matrix multiplication is used to perform a convolution operation
         _slide_vector_sum_col = vector_sum_col->info()->tensor_shape().num_dimensions() > 1;
     }
     // Configure kernel window
     auto win_config = validate_and_configure_window(mm_result->info(),
                                                     vector_sum_col != nullptr ? vector_sum_col->info() : nullptr, // NOLINT
                                                     vector_sum_row != nullptr ? vector_sum_row->info() : nullptr, // NOLINT
                                                     a_offset, b_offset);
     ARM_COMPUTE_ERROR_THROW_ON(win_config.first);
     INEKernel::configure(win_config.second);
 }
References ARM_COMPUTE_ERROR_ON_NULLPTR, ARM_COMPUTE_ERROR_THROW_ON, ITensor::info(), Dimensions< T >::num_dimensions(), and ITensorInfo::tensor_shape().
Referenced by NEGEMMLowpMatrixMultiplyCore::configure().
name()
const char* name () const inline override virtual
Name of the kernel.
Returns
Kernel name
Implements ICPPKernel.
Definition at line 49 of file NEGEMMLowpOffsetContributionKernel.h.
     {
         return "NEGEMMLowpOffsetContributionKernel";
     }
operator=() [1/2]
NEGEMMLowpOffsetContributionKernel& operator= (const NEGEMMLowpOffsetContributionKernel &) delete
Prevent instances of this class from being copied (As this class contains pointers)
operator=() [2/2]
NEGEMMLowpOffsetContributionKernel& operator= (NEGEMMLowpOffsetContributionKernel &&) default
Allow instances of this class to be moved.
run()
void run (const Window & window, const ThreadInfo & info) override virtual
Execute the kernel on the passed window.
Warning
If is_parallelisable() returns false then the passed window must be equal to window()
Note
The window has to be a region within the window returned by the window() method
The width of the window has to be a multiple of num_elems_processed_per_iteration().
Parameters
[in] window Region on which to execute the kernel. (Must be a region of the window returned by window())
[in] info Info about executing thread and CPU.
Implements ICPPKernel.
Definition at line 393 of file NEGEMMLowpOffsetContributionKernel.cpp.
 {
     ARM_COMPUTE_UNUSED(info);
     ARM_COMPUTE_ERROR_ON_UNCONFIGURED_KERNEL(this);
     ARM_COMPUTE_ERROR_ON_INVALID_SUBWINDOW(INEKernel::window(), window);
     // Check if input is a 3D reinterpretation
     const bool reinterpret_as_3d = _vector_sum_row != nullptr
                                    && _mm_result->info()->num_dimensions() > 1
                                    && _mm_result->info()->tensor_shape().y() != _vector_sum_row->info()->tensor_shape().x();
     if(reinterpret_as_3d)
     {
         run_offset_contribution<true>(window, _mm_result, _vector_sum_col, _vector_sum_row, _a_offset, _b_offset, _k_offset, _slide_vector_sum_col);
     }
     else
     {
         run_offset_contribution<false>(window, _mm_result, _vector_sum_col, _vector_sum_row, _a_offset, _b_offset, _k_offset, _slide_vector_sum_col);
     }
 }
References ARM_COMPUTE_ERROR_ON_INVALID_SUBWINDOW, ARM_COMPUTE_ERROR_ON_UNCONFIGURED_KERNEL, ARM_COMPUTE_UNUSED, ITensor::info(), arm_compute::test::validation::info, ITensorInfo::num_dimensions(), ITensorInfo::tensor_shape(), IKernel::window(), Dimensions< T >::x(), and Dimensions< T >::y().
validate()
Status validate (const ITensorInfo * mm_result, const ITensorInfo * vector_sum_col, const ITensorInfo * vector_sum_row, int32_t a_offset, int32_t b_offset) static
Static function to check if given info will lead to a valid configuration of NEGEMMLowpOffsetContributionKernel.
Parameters
[in] mm_result Input tensor containing the result of NEGEMMLowpMatrixMultiplyKernel. Data type supported: S32
[in] vector_sum_col Input row-vector of sums of all the entries in each column of matrix B. Note: vector_sum_col can be a nullptr in case a_offset = 0. Data type supported: same as mm_result
[in] vector_sum_row Input row-vector of sums of all the entries in each row of matrix A. Note: vector_sum_row can be a nullptr in case b_offset = 0. Data type supported: same as mm_result
[in] a_offset Offset to be added to each element of the matrix A.
[in] b_offset Offset to be added to each element of the matrix B.
Returns
a status
Definition at line 380 of file NEGEMMLowpOffsetContributionKernel.cpp.
 {
     ARM_COMPUTE_RETURN_ON_ERROR(validate_arguments(mm_result, vector_sum_col, vector_sum_row, a_offset, b_offset));
     ARM_COMPUTE_RETURN_ON_ERROR(validate_and_configure_window(mm_result->clone().get(),
                                                               vector_sum_col != nullptr ? vector_sum_col->clone().get() : nullptr,
                                                               vector_sum_row != nullptr ? vector_sum_row->clone().get() : nullptr,
                                                               a_offset, b_offset)
                                 .first); // NOLINT
     return Status{};
 }
References ARM_COMPUTE_RETURN_ON_ERROR, and ICloneable< T >::clone().
Referenced by NEGEMMLowpMatrixMultiplyCore::validate().
The documentation for this class was generated from the following files:
arm_compute/core/NEON/kernels/NEGEMMLowpOffsetContributionKernel.h
src/core/NEON/kernels/NEGEMMLowpOffsetContributionKernel.cpp