Compute Library: CLL2NormalizeLayer Class Reference
CLL2NormalizeLayer Class Reference
Basic function to perform a L2 normalization on a given axis.
#include <CLL2NormalizeLayer.h>
Public Member Functions
CLL2NormalizeLayer (std::shared_ptr< IMemoryManager > memory_manager=nullptr)
Constructor.
void configure (ICLTensor *input, ICLTensor *output, unsigned int axis, float epsilon=1e-12f)
Set the input and output tensors.
void run () override
Run the kernels contained in the function.
Public Member Functions inherited from IFunction
virtual ~IFunction ()=default
Destructor.
virtual void prepare ()
Prepare the function for executing.
Static Public Member Functions
static Status validate (const ITensorInfo *input, const ITensorInfo *output, unsigned int axis, float epsilon=1e-12f)
Static function to check if given info will lead to a valid configuration of CLL2NormalizeLayer.
Detailed Description
Basic function to perform a L2 normalization on a given axis.
This function runs the following kernels:
CLReductionOperation
CLL2NormalizeLayerKernel
Definition at line 48 of file CLL2NormalizeLayer.h.
Constructor & Destructor Documentation
CLL2NormalizeLayer()
CLL2NormalizeLayer (std::shared_ptr< IMemoryManager > memory_manager = nullptr)
Constructor.
Definition at line 37 of file CLL2NormalizeLayer.cpp.
     : _memory_group(std::move(memory_manager)), _reduce_func(), _normalize_kernel(), _sumsq()
 {
 }
Member Function Documentation
configure()
void configure (ICLTensor * input, ICLTensor * output, unsigned int axis, float epsilon = 1e-12f)
Set the input and output tensors.
Parameters
[in] input Source tensor. Data types supported: F16/F32. Data layouts supported: NCHW/NHWC.
[out] output Destination tensor. Data types and data layouts supported: Same as input.
[in] axis Axis along which to reduce. Supported reduction axis : 0, 1, 2
[in] epsilon (Optional) Lower bound value for the normalization.
Definition at line 42 of file CLL2NormalizeLayer.cpp.
 {
     // Manage intermediate buffers
     _memory_group.manage(&_sumsq);
     // Configure kernels
     _reduce_func.configure(input, &_sumsq, axis, ReductionOperation::SUM_SQUARE);
     _normalize_kernel.configure(input, &_sumsq, output, axis, epsilon);
     // Allocate intermediate tensor
     _sumsq.allocator()->allocate();
 }
References CLTensorAllocator::allocate(), CLTensor::allocator(), arm_compute::test::validation::axis, CLL2NormalizeLayerKernel::configure(), CLReductionOperation::configure(), epsilon, MemoryGroupBase< TensorType >::manage(), and arm_compute::SUM_SQUARE.
run()
void run () override virtual
Run the kernels contained in the function.
For NEON kernels:
Multi-threading is used for the kernels which are parallelisable.
By default std::thread::hardware_concurrency() threads are used.
Note
CPPScheduler::set_num_threads() can be used to manually set the number of threads
For OpenCL kernels:
All the kernels are enqueued on the queue associated with CLScheduler.
The queue is then flushed.
Note
The function will not block until the kernels are executed. It is the user's responsibility to wait.
Will call prepare() on first run if hasn't been done
Implements IFunction.
Definition at line 75 of file CLL2NormalizeLayer.cpp.
 {
     MemoryGroupResourceScope scope_mg(_memory_group);
     _reduce_func.run();
     CLScheduler::get().enqueue(_normalize_kernel, true);
 }
References CLScheduler::enqueue(), CLScheduler::get(), and CLReductionOperation::run().
validate()
Status validate (const ITensorInfo * input, const ITensorInfo * output, unsigned int axis, float epsilon = 1e-12f) static
Static function to check if given info will lead to a valid configuration of CLL2NormalizeLayer.
Parameters
[in] input Source tensor info. Data types supported: F16/F32. Data layouts supported: NCHW/NHWC.
[in] output Destination tensor info. Data types and data layouts supported: Same as input.
[in] axis Axis along which to reduce. Supported reduction axis : 0, 1, 2
[in] epsilon (Optional) Lower bound value for the normalization.
Returns
a status
Definition at line 55 of file CLL2NormalizeLayer.cpp.
 {
     TensorShape shape(input->tensor_shape());
     // Create intermediate tensor info
     TensorInfo sum_sq;
     sum_sq.set_data_type(input->data_type());
     sum_sq.set_tensor_shape(shape);
     ARM_COMPUTE_RETURN_ON_ERROR(CLReductionOperation::validate(input, &sum_sq, axis, ReductionOperation::SUM_SQUARE));
     // Reduce shape on axis
     shape.set(axis, 1);
     sum_sq.set_tensor_shape(shape);
     ARM_COMPUTE_RETURN_ON_ERROR(CLL2NormalizeLayerKernel::validate(input, &sum_sq, output, axis, epsilon));
     return Status{};
 }
References ARM_COMPUTE_RETURN_ON_ERROR, arm_compute::test::validation::axis, ITensorInfo::data_type(), epsilon, TensorInfo::set_data_type(), ITensorInfo::set_tensor_shape(), arm_compute::test::validation::shape, arm_compute::SUM_SQUARE, ITensorInfo::tensor_shape(), CLReductionOperation::validate(), and CLL2NormalizeLayerKernel::validate().
The documentation for this class was generated from the following files:
arm_compute/runtime/CL/functions/CLL2NormalizeLayer.h
src/runtime/CL/functions/CLL2NormalizeLayer.cpp