Compute Library: GraphManager Class Reference
GraphManager Class Reference final
Graph manager class.
#include <GraphManager.h>
Public Member Functions
GraphManager ()
Default Constructor.
GraphManager (const GraphManager &)=delete
Prevent instances of this class from being copied (As this class contains pointers)
GraphManager (GraphManager &&)=default
Default move constructor.
GraphManager & operator= (const GraphManager &)=delete
Prevent instances of this class from being copied (As this class contains pointers)
GraphManager & operator= (GraphManager &&)=default
Default move assignment operator.
void finalize_graph (Graph &graph, GraphContext &ctx, PassManager &pm, Target target)
Finalizes a given graph.
void execute_graph (Graph &graph)
Executes a graph.
void invalidate_graph (Graph &graph)
Invalidates the graph execution workload.
Detailed Description
Graph manager class.
Manages a list of graphs along with their resources
Definition at line 45 of file GraphManager.h.
Constructor & Destructor Documentation
GraphManager() [1/3]
GraphManager ()
Default Constructor.
Definition at line 41 of file GraphManager.cpp.
     : _workloads()
 {
 }
GraphManager() [2/3]
GraphManager (const GraphManager &) delete
Prevent instances of this class from being copied (As this class contains pointers)
GraphManager() [3/3]
GraphManager (GraphManager &&) default
Default move constructor.
Member Function Documentation
execute_graph()
void execute_graph (Graph & graph)
Executes a graph.
Parameters
[in] graph Graph to execute
Definition at line 109 of file GraphManager.cpp.
 {
     // Check if graph is finalized
     auto it = _workloads.find(graph.id());
     ARM_COMPUTE_ERROR_ON_MSG(it == std::end(_workloads), "Graph is not registered!");
     while(true)
     {
         // Call input accessors
         if(!detail::call_all_input_node_accessors(it->second))
         {
             return;
         }
         // Run graph
         detail::call_all_tasks(it->second);
         // Call output accessors
         if(!detail::call_all_output_node_accessors(it->second))
         {
             return;
         }
     }
 }
References ARM_COMPUTE_ERROR_ON_MSG, arm_compute::graph::detail::call_all_input_node_accessors(), arm_compute::graph::detail::call_all_output_node_accessors(), arm_compute::graph::detail::call_all_tasks(), and Graph::id().
Referenced by Stream::run().
finalize_graph()
void finalize_graph (Graph & graph, GraphContext & ctx, PassManager & pm, Target target)
Finalizes a given graph.
Warning
At this given time finalize_graph will alter the passed graph, plan is to avoid by copying the graph structure, or provide another entry-point for this functionality as it will increase the memory requirements
Parameters
[in] graph Graph to finalize
[in] ctx Graph context
[in] pm Pass manager to use for any optimization passes
[in] target Execution target (Single target execution is currently supported)
Definition at line 46 of file GraphManager.cpp.
 {
     // Check if graph has been registered
     if(_workloads.find(graph.id()) != std::end(_workloads))
     {
         ARM_COMPUTE_ERROR("Graph is already registered!");
     }
     // Force target to all graph construct
     // TODO (COMPMID-2014) : Support heterogeneous execution
     Target forced_target = target;
     if(!is_target_supported(target))
     {
         forced_target = get_default_target();
         ARM_COMPUTE_LOG_GRAPH_INFO("Switching target from " << target << " to " << forced_target << std::endl);
     }
     force_target_to_graph(graph, forced_target);
     // Setup backend context
     // TODO (COMPMID-2014) : Setup all backends needed by the graph
     setup_requested_backend_context(ctx, forced_target);
     // Configure all tensors
     detail::configure_all_tensors(graph);
     // Apply all mutating passes
     pm.run_all(graph);
     // Perform topological sort
     std::vector<NodeID> topological_sorted_nodes = dfs(graph);
     // Validate all nodes
     detail::validate_all_nodes(graph);
     // Configure all nodes
     auto workload = detail::configure_all_nodes(graph, ctx, topological_sorted_nodes);
     ARM_COMPUTE_ERROR_ON_MSG(workload.tasks.empty(), "Could not configure all nodes!");
     // Allocate const tensors and call accessors
     detail::allocate_const_tensors(graph);
     detail::call_all_const_node_accessors(graph);
     // Prepare graph
     detail::prepare_all_tasks(workload);
     // Setup tensor memory (Allocate all tensors or setup transition manager)
     if(ctx.config().use_transition_memory_manager)
     {
         detail::configure_transition_manager(graph, ctx, workload);
     }
     else
     {
         detail::allocate_all_tensors(graph);
     }
     // Finalize Graph context
     ctx.finalize();
     // Register graph
     _workloads.insert(std::make_pair(graph.id(), std::move(workload)));
     ARM_COMPUTE_LOG_GRAPH_VERBOSE("Created workload for graph with ID : " << graph.id() << std::endl);
 }
References arm_compute::graph::detail::allocate_all_tensors(), arm_compute::graph::detail::allocate_const_tensors(), ARM_COMPUTE_ERROR, ARM_COMPUTE_ERROR_ON_MSG, ARM_COMPUTE_LOG_GRAPH_INFO, ARM_COMPUTE_LOG_GRAPH_VERBOSE, arm_compute::graph::detail::call_all_const_node_accessors(), GraphContext::config(), arm_compute::graph::detail::configure_all_nodes(), arm_compute::graph::detail::configure_all_tensors(), arm_compute::graph::detail::configure_transition_manager(), arm_compute::graph::dfs(), GraphContext::finalize(), arm_compute::graph::force_target_to_graph(), arm_compute::graph::get_default_target(), Graph::id(), arm_compute::graph::is_target_supported(), arm_compute::graph::detail::prepare_all_tasks(), PassManager::run_all(), arm_compute::graph::setup_requested_backend_context(), GraphConfig::use_transition_memory_manager, and arm_compute::graph::detail::validate_all_nodes().
Referenced by Stream::finalize().
invalidate_graph()
void invalidate_graph (Graph & graph)
Invalidates the graph execution workload.
Parameters
[in] graph Graph to invalidate
Definition at line 134 of file GraphManager.cpp.
 {
     auto it = _workloads.find(graph.id());
     ARM_COMPUTE_ERROR_ON_MSG(it == std::end(_workloads), "Graph is not registered!");
     _workloads.erase(it);
 }
References ARM_COMPUTE_ERROR_ON_MSG, and Graph::id().
operator=() [1/2]
GraphManager& operator= (const GraphManager &) delete
Prevent instances of this class from being copied (As this class contains pointers)
operator=() [2/2]
GraphManager& operator= (GraphManager &&) default
Default move assignment operator.
The documentation for this class was generated from the following files:
arm_compute/graph/GraphManager.h
src/graph/GraphManager.cpp