Compute Library: CLSubTensorHandle Class Reference
CLSubTensorHandle Class Reference final
OpenCL Sub-Tensor handle interface object.
#include <CLSubTensorHandle.h>
Public Member Functions
CLSubTensorHandle (ITensorHandle *parent_handle, const TensorShape &shape, const Coordinates &coords, bool extend_parent=false)
Default constructor.
~CLSubTensorHandle ()=default
Destructor: free the tensor's memory.
CLSubTensorHandle (CLSubTensorHandle &&)=default
Allow instances of this class to be move constructed.
CLSubTensorHandle & operator= (CLSubTensorHandle &&)=default
Allow instances of this class to be moved.
CLSubTensorHandle (const CLSubTensorHandle &)=delete
Prevent instances of this class from being copied (As this class contains pointers)
CLSubTensorHandle & operator= (const CLSubTensorHandle &)=delete
Prevent instances of this class from being copied (As this class contains pointers)
void allocate () override
Allocates backend memory for the handle.
void free () override
Allocates backend memory for the handle.
void manage (IMemoryGroup *mg) override
Set backend tensor to be managed by a memory group.
void map (bool blocking) override
Maps backend tensor object.
void unmap () override
Un-maps a backend tensor object.
void release_if_unused () override
Releases backend tensor if is marked as unused.
arm_compute::ITensor & tensor () override
Backend tensor object accessor.
const arm_compute::ITensor & tensor () const override
Backend tensor object const accessor.
ITensorHandle * parent_handle () override
Return the parent tensor handle if is a subtensor else this.
bool is_subtensor () const override
Checks if a backing tensor is a sub-tensor object or not.
Target target () const override
Returns target type.
Public Member Functions inherited from ITensorHandle
virtual ~ITensorHandle ()=default
Default virtual destructor.
Detailed Description
OpenCL Sub-Tensor handle interface object.
Definition at line 38 of file CLSubTensorHandle.h.
Constructor & Destructor Documentation
CLSubTensorHandle() [1/3]
CLSubTensorHandle (ITensorHandle * parent_handle, const TensorShape & shape, const Coordinates & coords, bool extend_parent = false)
Default constructor.
Parameters
[in] parent_handle Parent tensor handle
[in] shape Sub-Tensor shape
[in] coords Starting coordinates
[in] extend_parent Extends parent shape if true
Definition at line 34 of file CLSubTensorHandle.cpp.
     : _sub_tensor(), _parent_handle(nullptr)
 {
     ARM_COMPUTE_ERROR_ON(!parent_handle);
     auto parent_tensor = arm_compute::utils::cast::polymorphic_downcast<ICLTensor *>(&parent_handle->tensor());
     _sub_tensor        = arm_compute::CLSubTensor(parent_tensor, shape, coords, extend_parent);
     _parent_handle     = parent_handle;
 }
References ARM_COMPUTE_ERROR_ON, CLSubTensorHandle::parent_handle(), arm_compute::test::validation::shape, and ITensorHandle::tensor().
~CLSubTensorHandle()
~CLSubTensorHandle () default
Destructor: free the tensor's memory.
CLSubTensorHandle() [2/3]
CLSubTensorHandle (CLSubTensorHandle &&) default
Allow instances of this class to be move constructed.
CLSubTensorHandle() [3/3]
CLSubTensorHandle (const CLSubTensorHandle &) delete
Prevent instances of this class from being copied (As this class contains pointers)
Member Function Documentation
allocate()
void allocate () override virtual
Allocates backend memory for the handle.
Implements ITensorHandle.
Definition at line 43 of file CLSubTensorHandle.cpp.
 {
     // noop
 }
free()
void free () override virtual
Allocates backend memory for the handle.
Implements ITensorHandle.
Definition at line 48 of file CLSubTensorHandle.cpp.
 {
     // noop
 }
is_subtensor()
bool is_subtensor () const override virtual
Checks if a backing tensor is a sub-tensor object or not.
Returns
True if the backend tensor is a sub-tensor else false
Implements ITensorHandle.
Definition at line 90 of file CLSubTensorHandle.cpp.
 {
     return true;
 }
manage()
void manage (IMemoryGroup * mg) override virtual
Set backend tensor to be managed by a memory group.
Parameters
[in] mg Memory group
Implements ITensorHandle.
Definition at line 53 of file CLSubTensorHandle.cpp.
 {
     ARM_COMPUTE_UNUSED(mg);
     // noop
 }
References ARM_COMPUTE_UNUSED.
map()
void map (bool blocking) override virtual
Maps backend tensor object.
Parameters
[in] blocking Flags if the mapping operations should be blocking
Implements ITensorHandle.
Definition at line 59 of file CLSubTensorHandle.cpp.
 {
     _sub_tensor.map(blocking);
 }
References CLSubTensor::map().
operator=() [1/2]
CLSubTensorHandle& operator= (CLSubTensorHandle &&) default
Allow instances of this class to be moved.
operator=() [2/2]
CLSubTensorHandle& operator= (const CLSubTensorHandle &) delete
Prevent instances of this class from being copied (As this class contains pointers)
parent_handle()
ITensorHandle * parent_handle () override virtual
Return the parent tensor handle if is a subtensor else this.
Returns
Parent tensor handle
Implements ITensorHandle.
Definition at line 84 of file CLSubTensorHandle.cpp.
 {
     ARM_COMPUTE_ERROR_ON(_parent_handle == nullptr);
     return _parent_handle->parent_handle();
 }
References ARM_COMPUTE_ERROR_ON, and ITensorHandle::parent_handle().
Referenced by CLSubTensorHandle::CLSubTensorHandle().
release_if_unused()
void release_if_unused () override virtual
Releases backend tensor if is marked as unused.
Note
This has no effect on sub-tensors
Warning
Parent tensors don't keep track of sub-tensors, thus if a parent is set as unused then all sub-tensors will be invalidated, on the other hand if a sub-tensor is marked as unused then the parent tensor won't be released
Implements ITensorHandle.
Definition at line 69 of file CLSubTensorHandle.cpp.
 {
     // noop
 }
target()
Target target () const override virtual
Returns target type.
Returns
Target type
Implements ITensorHandle.
Definition at line 95 of file CLSubTensorHandle.cpp.
 {
     return Target::CL;
 }
References arm_compute::graph::CL.
tensor() [1/2]
arm_compute::ITensor & tensor () override virtual
Backend tensor object accessor.
Implements ITensorHandle.
Definition at line 79 of file CLSubTensorHandle.cpp.
 {
     return _sub_tensor;
 }
tensor() [2/2]
const arm_compute::ITensor & tensor () const override virtual
Backend tensor object const accessor.
Implements ITensorHandle.
Definition at line 74 of file CLSubTensorHandle.cpp.
 {
     return _sub_tensor;
 }
unmap()
void unmap () override virtual
Un-maps a backend tensor object.
Implements ITensorHandle.
Definition at line 64 of file CLSubTensorHandle.cpp.
 {
     _sub_tensor.unmap();
 }
References CLSubTensor::unmap().
The documentation for this class was generated from the following files:
arm_compute/graph/backends/CL/CLSubTensorHandle.h
src/graph/backends/CL/CLSubTensorHandle.cpp