Compute Library: CLCopyKernel Class Reference
CLCopyKernel Class Reference
OpenCL kernel to perform a copy between two tensors.
#include <CLCopyKernel.h>
Public Member Functions
CLCopyKernel ()
Default constructor.
CLCopyKernel (const CLCopyKernel &)=delete
Prevent instances of this class from being copied (As this class contains pointers).
CLCopyKernel & operator= (const CLCopyKernel &)=delete
Prevent instances of this class from being copied (As this class contains pointers).
CLCopyKernel (CLCopyKernel &&)=default
Allow instances of this class to be moved.
CLCopyKernel & operator= (CLCopyKernel &&)=default
Allow instances of this class to be moved.
void configure (const ICLTensor *input, ICLTensor *output, const PaddingList &padding=PaddingList(), Window *output_window=nullptr)
Initialize the kernel's input, output.
void run (const Window &window, cl::CommandQueue &queue) override
Enqueue the OpenCL kernel to process the given window on the passed OpenCL command queue.
Public Member Functions inherited from ICLKernel
ICLKernel ()
Constructor.
cl::Kernel & kernel ()
Returns a reference to the OpenCL kernel of this object.
template<typename T >
void add_1D_array_argument (unsigned int &idx, const ICLArray< T > *array, const Strides &strides, unsigned int num_dimensions, const Window &window)
Add the passed 1D array's parameters to the object's kernel's arguments starting from the index idx.
void add_1D_tensor_argument (unsigned int &idx, const ICLTensor *tensor, const Window &window)
Add the passed 1D tensor's parameters to the object's kernel's arguments starting from the index idx.
void add_1D_tensor_argument_if (bool cond, unsigned int &idx, const ICLTensor *tensor, const Window &window)
Add the passed 1D tensor's parameters to the object's kernel's arguments starting from the index idx if the condition is true.
void add_2D_tensor_argument (unsigned int &idx, const ICLTensor *tensor, const Window &window)
Add the passed 2D tensor's parameters to the object's kernel's arguments starting from the index idx.
void add_2D_tensor_argument_if (bool cond, unsigned int &idx, const ICLTensor *tensor, const Window &window)
Add the passed 2D tensor's parameters to the object's kernel's arguments starting from the index idx if the condition is true.
void add_3D_tensor_argument (unsigned int &idx, const ICLTensor *tensor, const Window &window)
Add the passed 3D tensor's parameters to the object's kernel's arguments starting from the index idx.
void add_4D_tensor_argument (unsigned int &idx, const ICLTensor *tensor, const Window &window)
Add the passed 4D tensor's parameters to the object's kernel's arguments starting from the index idx.
template<typename T >
void add_argument (unsigned int &idx, T value)
Add the passed parameters to the object's kernel's arguments starting from the index idx.
void set_lws_hint (const cl::NDRange &lws_hint)
Set the Local-Workgroup-Size hint.
cl::NDRange lws_hint () const
Return the Local-Workgroup-Size hint.
const std::string & config_id () const
Get the configuration ID.
void set_target (GPUTarget target)
Set the targeted GPU architecture.
void set_target (cl::Device &device)
Set the targeted GPU architecture according to the CL device.
GPUTarget get_target () const
Get the targeted GPU architecture.
size_t get_max_workgroup_size ()
Get the maximum workgroup size for the device the CLKernelLibrary uses.
template<typename T , unsigned int dimension_size>
void add_array_argument (unsigned &idx, const ICLArray< T > *array, const Strides &strides, unsigned int num_dimensions, const Window &window)
Add the passed array's parameters to the object's kernel's arguments starting from the index idx.
template<unsigned int dimension_size>
void add_tensor_argument (unsigned &idx, const ICLTensor *tensor, const Window &window)
Public Member Functions inherited from IKernel
IKernel ()
Constructor.
virtual ~IKernel ()=default
Destructor.
virtual bool is_parallelisable () const
Indicates whether or not the kernel is parallelisable.
virtual BorderSize border_size () const
The size of the border for that kernel.
const Window & window () const
The maximum window the kernel can be executed on.
Static Public Member Functions
static Status validate (const ITensorInfo *input, const ITensorInfo *output, const PaddingList &padding=PaddingList(), Window *output_window=nullptr)
Static function to check if given info will lead to a valid configuration of CLCopyKernel.
Static Public Member Functions inherited from ICLKernel
static constexpr unsigned int num_arguments_per_1D_array ()
Returns the number of arguments enqueued per 1D array object.
static constexpr unsigned int num_arguments_per_1D_tensor ()
Returns the number of arguments enqueued per 1D tensor object.
static constexpr unsigned int num_arguments_per_2D_tensor ()
Returns the number of arguments enqueued per 2D tensor object.
static constexpr unsigned int num_arguments_per_3D_tensor ()
Returns the number of arguments enqueued per 3D tensor object.
static constexpr unsigned int num_arguments_per_4D_tensor ()
Returns the number of arguments enqueued per 4D tensor object.
static cl::NDRange gws_from_window (const Window &window)
Get the global work size given an execution window.
Detailed Description
OpenCL kernel to perform a copy between two tensors.
Definition at line 35 of file CLCopyKernel.h.
Constructor & Destructor Documentation
CLCopyKernel() [1/3]
CLCopyKernel ()
Default constructor.
Definition at line 152 of file CLCopyKernel.cpp.
     : _input(nullptr), _output(nullptr), _output_window(), _has_output_window(false)
 {
 }
CLCopyKernel() [2/3]
CLCopyKernel (const CLCopyKernel &) delete
Prevent instances of this class from being copied (As this class contains pointers).
CLCopyKernel() [3/3]
CLCopyKernel (CLCopyKernel &&) default
Allow instances of this class to be moved.
Member Function Documentation
configure()
void configure (const ICLTensor * input, ICLTensor * output, const PaddingList & padding = PaddingList(), Window * output_window = nullptr)
Initialize the kernel's input, output.
Parameters
[in] input Source tensor. Data types supported: U8/S8/QASYMM8/U16/S16/F16/U32/S32/F32.
[out] output Destination tensor. Data types supported: same as input.
[in] padding (Optional) Padding to be applied to the input tensor
[in] output_window (Optional) Window to be used in case only copying into part of a tensor. Default is nullptr.
Definition at line 157 of file CLCopyKernel.cpp.
 {
     ARM_COMPUTE_ERROR_ON_NULLPTR(input, output);
     ARM_COMPUTE_ERROR_THROW_ON(validate_arguments(input->info(), output->info(), padding, output_window));
     _input  = input;
     _output = output;
     // Create kernel
     CLBuildOptions build_opts;
     build_opts.add_option("-DDATA_TYPE=" + get_cl_type_from_data_type(input->info()->data_type()));
     std::pair<Status, Window> win_config;
     const unsigned int vec_size_x = 16 / input->info()->element_size();
     if(padding.empty())
     {
         // Configure window
         win_config = validate_and_configure_window(input->info(), output->info(), output_window);
         if(output_window != nullptr)
         {
             _has_output_window        = true;
             _output_window            = Window(*output_window);
             const int  width_x        = output_window->num_iterations(0);
             const bool multi_access_x = width_x >= static_cast<int32_t>(vec_size_x);
             const bool remainder_x    = width_x % vec_size_x > 0;
             if(multi_access_x)
             {
                 _output_window.set(Window::DimX, Window::Dimension(output_window->x().start(), ceil_to_multiple(output_window->x().end(), vec_size_x), vec_size_x));
                 win_config.second.set(Window::DimX, Window::Dimension(win_config.second.x().start(), ceil_to_multiple(win_config.second.x().end(), vec_size_x), vec_size_x));
             }
             build_opts.add_option_if(multi_access_x, "-DVEC_SIZE=" + support::cpp11::to_string(vec_size_x));
             build_opts.add_option_if(multi_access_x && remainder_x, "-DLAST_ACCESSED_X=" + support::cpp11::to_string(std::max<int>(width_x - vec_size_x, 0)));
         }
         else
         {
             build_opts.add_option("-DVEC_SIZE=" + support::cpp11::to_string(vec_size_x));
         }
         // Build kernel
         _kernel = static_cast<cl::Kernel>(CLKernelLibrary::get().create_kernel("copy_tensor", build_opts.options()));
     }
     else
     {
         build_opts.add_option("-DVEC_SIZE=" + support::cpp11::to_string(vec_size_x));
         // Add compile time options
         add_padding_as_build_options(padding, build_opts);
         // If we are padding in the fourth dimension the kernel needs to know the depth of the
         // different cubes
         if(padding.size() == 4)
         {
             const size_t depth = input->info()->tensor_shape()[2];
             build_opts.add_option("-DDEPTH=" + support::cpp11::to_string(depth));
         }
         // Build kernel
         _kernel = static_cast<cl::Kernel>(CLKernelLibrary::get().create_kernel("copy_pad_tensor", build_opts.options()));
         // Configure window
         win_config = validate_and_configure_window_with_padding(input->info(), output->info(), padding);
     }
     // Validate and set the window
     ARM_COMPUTE_ERROR_THROW_ON(win_config.first);
     ICLKernel::configure_internal(win_config.second);
 }
References CLBuildOptions::add_option(), CLBuildOptions::add_option_if(), ARM_COMPUTE_ERROR_ON_NULLPTR, ARM_COMPUTE_ERROR_THROW_ON, arm_compute::ceil_to_multiple(), arm_compute::create_kernel(), ITensorInfo::data_type(), Window::DimX, ITensorInfo::element_size(), BorderSize::empty(), Window::Dimension::end(), CLKernelLibrary::get(), arm_compute::get_cl_type_from_data_type(), ITensor::info(), Window::num_iterations(), CLBuildOptions::options(), arm_compute::test::validation::padding, Window::set(), Window::Dimension::start(), ITensorInfo::tensor_shape(), arm_compute::support::cpp11::to_string(), arm_compute::validate_and_configure_window(), and Window::x().
Referenced by CLRNNLayer::configure(), CLPadLayer::configure(), CLGenerateProposalsLayer::configure(), and CLLSTMLayer::configure().
operator=() [1/2]
CLCopyKernel& operator= (const CLCopyKernel &) delete
Prevent instances of this class from being copied (As this class contains pointers).
operator=() [2/2]
CLCopyKernel& operator= (CLCopyKernel &&) default
Allow instances of this class to be moved.
run()
void run (const Window & window, cl::CommandQueue & queue) override virtual
Enqueue the OpenCL kernel to process the given window on the passed OpenCL command queue.
Note
The queue is not flushed by this method, and therefore the kernel will not have been executed by the time this method returns.
Parameters
[in] window Region on which to execute the kernel. (Must be a valid region of the window returned by window()).
[in,out] queue Command queue on which to enqueue the kernel.
Implements ICLKernel.
Definition at line 246 of file CLCopyKernel.cpp.
 {
     ARM_COMPUTE_ERROR_ON_UNCONFIGURED_KERNEL(this);
     ARM_COMPUTE_ERROR_ON_INVALID_SUBWINDOW(ICLKernel::window(), window);
     Window slice;
     if(_has_output_window)
     {
         slice            = window.first_slice_window_3D();
         Window out_slice = _output_window.first_slice_window_3D();
         do
         {
             unsigned int idx = 0;
             add_3D_tensor_argument(idx, _input, slice);
             add_3D_tensor_argument(idx, _output, out_slice);
             enqueue(queue, *this, slice);
         }
         while(window.slide_window_slice_3D(slice) && _output_window.slide_window_slice_3D(out_slice));
     }
     else
     {
         Window collapsed = window.collapse_if_possible(ICLKernel::window(), Window::DimZ);
         slice            = collapsed.first_slice_window_3D();
         do
         {
             unsigned int idx = 0;
             add_3D_tensor_argument(idx, _input, slice);
             add_3D_tensor_argument(idx, _output, slice);
             enqueue(queue, *this, slice);
         }
         while(collapsed.slide_window_slice_3D(slice));
     }
 }
References ICLKernel::add_3D_tensor_argument(), ARM_COMPUTE_ERROR_ON_INVALID_SUBWINDOW, ARM_COMPUTE_ERROR_ON_UNCONFIGURED_KERNEL, Window::collapse_if_possible(), Window::DimZ, arm_compute::enqueue(), Window::first_slice_window_3D(), arm_compute::test::validation::reference::slice(), Window::slide_window_slice_3D(), and IKernel::window().
validate()
Status validate (const ITensorInfo * input, const ITensorInfo * output, const PaddingList & padding = PaddingList(), Window * output_window = nullptr) static
Static function to check if given info will lead to a valid configuration of CLCopyKernel.
Parameters
[in] input Source tensor info. Data types supported: U8/S8/QASYMM8/U16/S16/F16/U32/S32/F32.
[in] output Destination tensor info. Data types supported: same as input.
[in] padding (Optional) Padding to be applied to the input tensor
[in] output_window (Optional) Window to be used in case only copying into part of a tensor. Default is nullptr.
Returns
a status
Definition at line 230 of file CLCopyKernel.cpp.
 {
     ARM_COMPUTE_RETURN_ON_ERROR(validate_arguments(input, output, padding, output_window));
     if(padding.empty())
     {
         ARM_COMPUTE_RETURN_ON_ERROR(validate_and_configure_window(input->clone().get(), output->clone().get(), output_window).first);
     }
     else
     {
         ARM_COMPUTE_RETURN_ON_ERROR(validate_and_configure_window_with_padding(input->clone().get(), output->clone().get(), padding).first);
     }
     return Status{};
 }
References ARM_COMPUTE_RETURN_ON_ERROR, ICloneable< T >::clone(), BorderSize::empty(), arm_compute::test::validation::padding, and arm_compute::validate_and_configure_window().
Referenced by CLCopy::validate(), CLPadLayer::validate(), CLGenerateProposalsLayer::validate(), and CLLSTMLayer::validate().
The documentation for this class was generated from the following files:
arm_compute/core/CL/kernels/CLCopyKernel.h
src/core/CL/kernels/CLCopyKernel.cpp