Compute Library: CLGaussianPyramidVertKernel Class Reference
CLGaussianPyramidVertKernel Class Reference
OpenCL kernel to perform a Gaussian filter and half scaling across height (vertical pass)
#include <CLGaussianPyramidKernel.h>
Public Member Functions
CLGaussianPyramidVertKernel ()
Default constructor.
CLGaussianPyramidVertKernel (const CLGaussianPyramidVertKernel &)=delete
Prevent instances of this class from being copied (As this class contains pointers)
CLGaussianPyramidVertKernel & operator= (const CLGaussianPyramidVertKernel &)=delete
Prevent instances of this class from being copied (As this class contains pointers)
CLGaussianPyramidVertKernel (CLGaussianPyramidVertKernel &&)=default
Allow instances of this class to be moved.
CLGaussianPyramidVertKernel & operator= (CLGaussianPyramidVertKernel &&)=default
Allow instances of this class to be moved.
~CLGaussianPyramidVertKernel ()=default
Default destructor.
void configure (const ICLTensor *input, ICLTensor *output)
Initialise the kernel's source, destination and border mode.
void run (const Window &window, cl::CommandQueue &queue) override
Enqueue the OpenCL kernel to process the given window on the passed OpenCL command queue.
BorderSize border_size () const override
The size of the border for that kernel.
Public Member Functions inherited from ICLSimpleKernel
ICLSimpleKernel ()
Constructor.
ICLSimpleKernel (const ICLSimpleKernel &)=delete
Prevent instances of this class from being copied (As this class contains pointers)
ICLSimpleKernel & operator= (const ICLSimpleKernel &)=delete
Prevent instances of this class from being copied (As this class contains pointers)
ICLSimpleKernel (ICLSimpleKernel &&)=default
Allow instances of this class to be moved.
ICLSimpleKernel & operator= (ICLSimpleKernel &&)=default
Allow instances of this class to be moved.
~ICLSimpleKernel ()=default
Default destructor.
void configure (const ICLTensor *input, ICLTensor *output, unsigned int num_elems_processed_per_iteration, bool border_undefined=false, const BorderSize &border_size=BorderSize())
Configure the kernel.
Public Member Functions inherited from ICLKernel
ICLKernel ()
Constructor.
cl::Kernel & kernel ()
Returns a reference to the OpenCL kernel of this object.
template<typename T >
void add_1D_array_argument (unsigned int &idx, const ICLArray< T > *array, const Strides &strides, unsigned int num_dimensions, const Window &window)
Add the passed 1D array's parameters to the object's kernel's arguments starting from the index idx.
void add_1D_tensor_argument (unsigned int &idx, const ICLTensor *tensor, const Window &window)
Add the passed 1D tensor's parameters to the object's kernel's arguments starting from the index idx.
void add_2D_tensor_argument (unsigned int &idx, const ICLTensor *tensor, const Window &window)
Add the passed 2D tensor's parameters to the object's kernel's arguments starting from the index idx.
void add_3D_tensor_argument (unsigned int &idx, const ICLTensor *tensor, const Window &window)
Add the passed 3D tensor's parameters to the object's kernel's arguments starting from the index idx.
void add_4D_tensor_argument (unsigned int &idx, const ICLTensor *tensor, const Window &window)
Add the passed 4D tensor's parameters to the object's kernel's arguments starting from the index idx.
template<typename T >
void add_argument (unsigned int &idx, T value)
Add the passed parameters to the object's kernel's arguments starting from the index idx.
void set_lws_hint (const cl::NDRange &lws_hint)
Set the Local-Workgroup-Size hint.
cl::NDRange lws_hint () const
Return the Local-Workgroup-Size hint.
const std::string & config_id () const
Get the configuration ID.
void set_target (GPUTarget target)
Set the targeted GPU architecture.
void set_target (cl::Device &device)
Set the targeted GPU architecture according to the CL device.
GPUTarget get_target () const
Get the targeted GPU architecture.
size_t get_max_workgroup_size ()
Get the maximum workgroup size for the device the CLKernelLibrary uses.
template<typename T , unsigned int dimension_size>
void add_array_argument (unsigned &idx, const ICLArray< T > *array, const Strides &strides, unsigned int num_dimensions, const Window &window)
Add the passed array's parameters to the object's kernel's arguments starting from the index idx.
template<unsigned int dimension_size>
void add_tensor_argument (unsigned &idx, const ICLTensor *tensor, const Window &window)
Public Member Functions inherited from IKernel
IKernel ()
Constructor.
virtual ~IKernel ()=default
Destructor.
virtual bool is_parallelisable () const
Indicates whether or not the kernel is parallelisable.
const Window & window () const
The maximum window the kernel can be executed on.
Additional Inherited Members
Static Public Member Functions inherited from ICLKernel
static constexpr unsigned int num_arguments_per_1D_array ()
Returns the number of arguments enqueued per 1D array object.
static constexpr unsigned int num_arguments_per_1D_tensor ()
Returns the number of arguments enqueued per 1D tensor object.
static constexpr unsigned int num_arguments_per_2D_tensor ()
Returns the number of arguments enqueued per 2D tensor object.
static constexpr unsigned int num_arguments_per_3D_tensor ()
Returns the number of arguments enqueued per 3D tensor object.
static constexpr unsigned int num_arguments_per_4D_tensor ()
Returns the number of arguments enqueued per 4D tensor object.
static cl::NDRange gws_from_window (const Window &window)
Get the global work size given an execution window.
Detailed Description
OpenCL kernel to perform a Gaussian filter and half scaling across height (vertical pass)
Definition at line 66 of file CLGaussianPyramidKernel.h.
Constructor & Destructor Documentation
CLGaussianPyramidVertKernel() [1/3]
CLGaussianPyramidVertKernel ()
Default constructor.
Definition at line 126 of file CLGaussianPyramidKernel.cpp.
     : _t2_load_offset(0)
 {
 }
CLGaussianPyramidVertKernel() [2/3]
CLGaussianPyramidVertKernel (const CLGaussianPyramidVertKernel &) delete
Prevent instances of this class from being copied (As this class contains pointers)
CLGaussianPyramidVertKernel() [3/3]
CLGaussianPyramidVertKernel (CLGaussianPyramidVertKernel &&) default
Allow instances of this class to be moved.
~CLGaussianPyramidVertKernel()
~CLGaussianPyramidVertKernel () default
Default destructor.
Member Function Documentation
border_size()
BorderSize border_size () const override virtual
The size of the border for that kernel.
Returns
The width in number of elements of the border.
Reimplemented from IKernel.
Definition at line 131 of file CLGaussianPyramidKernel.cpp.
 {
     return BorderSize{ 2, 0 };
 }
Referenced by CLGaussianPyramidVertKernel::configure().
configure()
void configure (const ICLTensor * input, ICLTensor * output)
Initialise the kernel's source, destination and border mode.
Parameters
[in] input Source tensor. Data types supported: U16.
[out] output Destination tensor. Output should have half the input height. Data types supported: U8.
Definition at line 136 of file CLGaussianPyramidKernel.cpp.
 {
     ARM_COMPUTE_ERROR_ON_DATA_TYPE_CHANNEL_NOT_IN(input, 1, DataType::U16);
     ARM_COMPUTE_ERROR_ON_DATA_TYPE_CHANNEL_NOT_IN(output, 1, DataType::U8);
     ARM_COMPUTE_ERROR_ON(input->info()->dimension(0) != output->info()->dimension(0));
     for(size_t i = 2; i < Coordinates::num_max_dimensions; ++i)
     {
         ARM_COMPUTE_ERROR_ON(input->info()->dimension(i) != output->info()->dimension(i));
     }
     _input  = input;
     _output = output;
     // Create kernel
     _kernel = static_cast<cl::Kernel>(CLKernelLibrary::get().create_kernel("gaussian5x1_sub_y"));
     // Configure kernel window
     constexpr unsigned int num_elems_processed_per_iteration = 8;
     constexpr unsigned int num_rows_processed_per_iteration  = 2;
     constexpr unsigned int num_elems_written_per_iteration   = 8;
     constexpr unsigned int num_elems_read_per_iteration      = 8;
     constexpr unsigned int num_rows_per_iteration            = 5;
     const float scale_y = static_cast<float>(output->info()->dimension(1)) / input->info()->dimension(1);
     Window                win = calculate_max_window(*input->info(), Steps(num_elems_processed_per_iteration, num_rows_processed_per_iteration));
     AccessWindowRectangle output_access(output->info(), 0, 0, num_elems_written_per_iteration, num_rows_per_iteration, 1.f, scale_y);
     // Determine whether we need to load even or odd rows. See above for a
     // detailed explanation.
     _t2_load_offset = -border_size().top;
     if((_input->info()->valid_region().anchor[1] + _input->info()->valid_region().shape[1]) % 2 == 0)
     {
         _t2_load_offset += 1;
     }
     update_window_and_padding(win,
                               AccessWindowRectangle(input->info(), 0, _t2_load_offset, num_elems_read_per_iteration, num_rows_per_iteration),
                               output_access);
     output->info()->set_valid_region(ValidRegion(Coordinates(), output->info()->tensor_shape()));
     ICLKernel::configure_internal(win);
 }
References ARM_COMPUTE_ERROR_ON, ARM_COMPUTE_ERROR_ON_DATA_TYPE_CHANNEL_NOT_IN, CLGaussianPyramidVertKernel::border_size(), arm_compute::calculate_max_window(), arm_compute::create_kernel(), ITensorInfo::dimension(), CLKernelLibrary::get(), ITensor::info(), Dimensions< int >::num_max_dimensions, ITensorInfo::set_valid_region(), ITensorInfo::tensor_shape(), BorderSize::top, arm_compute::U16, arm_compute::U8, and arm_compute::update_window_and_padding().
operator=() [1/2]
CLGaussianPyramidVertKernel& operator= (const CLGaussianPyramidVertKernel &) delete
Prevent instances of this class from being copied (As this class contains pointers)
operator=() [2/2]
CLGaussianPyramidVertKernel& operator= (CLGaussianPyramidVertKernel &&) default
Allow instances of this class to be moved.
run()
void run (const Window & window, cl::CommandQueue & queue) override virtual
Enqueue the OpenCL kernel to process the given window on the passed OpenCL command queue.
Note
The queue is not flushed by this method, and therefore the kernel will not have been executed by the time this method returns.
Parameters
[in] window Region on which to execute the kernel. (Must be a valid region of the window returned by window()).
[in,out] queue Command queue on which to enqueue the kernel.
Implements ICLKernel.
Definition at line 183 of file CLGaussianPyramidKernel.cpp.
 {
     ARM_COMPUTE_ERROR_ON_UNCONFIGURED_KERNEL(this);
     ARM_COMPUTE_ERROR_ON_INVALID_SUBWINDOW(IKernel::window(), window);
     ARM_COMPUTE_ERROR_ON(window.x().step() != 8);
     ARM_COMPUTE_ERROR_ON(window.y().step() % 2);
     Window win_in(window);
     win_in.shift(Window::DimY, _t2_load_offset);
     Window win_out(window);
     win_out.scale(Window::DimY, 0.5f);
     Window slice_in  = win_in.first_slice_window_2D();
     Window slice_out = win_out.first_slice_window_2D();
     do
     {
         unsigned int idx = 0;
         add_2D_tensor_argument(idx, _input, slice_in);
         add_2D_tensor_argument(idx, _output, slice_out);
         enqueue(queue, *this, slice_out);
     }
     while(win_in.slide_window_slice_2D(slice_in) && win_out.slide_window_slice_2D(slice_out));
 }
References ICLKernel::add_2D_tensor_argument(), ARM_COMPUTE_ERROR_ON, ARM_COMPUTE_ERROR_ON_INVALID_SUBWINDOW, ARM_COMPUTE_ERROR_ON_UNCONFIGURED_KERNEL, Window::DimY, arm_compute::enqueue(), Window::first_slice_window_2D(), Window::scale(), Window::slide_window_slice_2D(), Window::Dimension::step(), IKernel::window(), Window::x(), and Window::y().
The documentation for this class was generated from the following files:
arm_compute/core/CL/kernels/CLGaussianPyramidKernel.h
src/core/CL/kernels/CLGaussianPyramidKernel.cpp