Compute Library: ITensor Class Reference
ITensor Class Reference abstract
Interface for NEON tensor.
#include <ITensor.h>
Public Member Functions
virtual ITensorInfo * info () const =0
Interface to be implemented by the child class to return the tensor's metadata.
virtual ITensorInfo * info ()=0
Interface to be implemented by the child class to return the tensor's metadata.
virtual ~ITensor ()=default
Default virtual destructor.
virtual uint8_t * buffer () const =0
Interface to be implemented by the child class to return a pointer to CPU memory.
uint8_t * ptr_to_element (const Coordinates &id) const
Return a pointer to the element at the passed coordinates.
void copy_from (const ITensor &src)
Copy the content of another tensor.
void print (std::ostream &s, IOFormatInfo io_fmt=IOFormatInfo()) const
Print a tensor to a given stream using user defined formatting information.
bool is_used () const
Flags if the tensor is used or not.
void mark_as_unused () const
Marks a tensor as unused.
Detailed Description
Interface for NEON tensor.
Definition at line 36 of file ITensor.h.
Constructor & Destructor Documentation
~ITensor()
virtual ~ITensor () virtual default
Default virtual destructor.
Member Function Documentation
buffer()
virtual uint8_t* buffer () const pure virtual
Interface to be implemented by the child class to return a pointer to CPU memory.
Returns
A CPU pointer to the beginning of the image's allocation.
Implemented in ICLTensor, GCTensor, IGCTensor, SubTensor, and Tensor.
Referenced by ValidationOutputAccessor::access_tensor(), SubTensor::buffer(), NENonLinearFilterKernel::configure(), arm_compute::utils::draw_detection_rectangle(), Iterator::Iterator(), ITensor::print(), ITensor::ptr_to_element(), CPPUpsampleKernel::run(), NEWidthConcatenateLayerKernel::run(), NECannyEdge::run(), NEDirectConvolutionLayerKernel::run(), NELogits1DSoftmaxKernel::run(), NEWinogradLayerTransformInputKernel< T, OutputTileRows, OutputTileCols, KernelRows, KernelCols >::run(), NEConvolutionRectangleKernel::run(), NEWinogradLayerTransformOutputKernel< T, OutputTileRows, OutputTileCols, KernelRows, KernelCols >::run(), NEWinogradLayerTransformWeightsKernel< T, OutputTileRows, OutputTileCols, KernelRows, KernelCols >::run(), and TopNPredictionsAccessor::TopNPredictionsAccessor().
copy_from()
void copy_from (const ITensor & src)
Copy the content of another tensor.
Note
The number of dimensions of the source tensor must be less or equal to those of the destination tensor.
All dimensions of the destination tensor must be greater or equal to the source tensor ones.
num_channels() and element_size() of both tensors must match.
Parameters
[in] src Source tensor to copy from.
Definition at line 35 of file ITensor.cpp.
References ARM_COMPUTE_ERROR_ON, ITensorInfo::dimension(), Window::DimY, ITensorInfo::element_size(), arm_compute::execute_window_loop(), ITensor::info(), ITensorInfo::num_channels(), ITensorInfo::num_dimensions(), Iterator::ptr(), ITensorInfo::set_valid_region(), ITensorInfo::tensor_shape(), Window::use_tensor_dimensions(), and ITensorInfo::valid_region().
Referenced by ITensor::ptr_to_element().
 {
     if(&src == this)
     {
         return;
     }
     const ITensorInfo *src_info = src.info();
     ITensorInfo       *dst_info = this->info();
     ARM_COMPUTE_ERROR_ON(src_info->num_dimensions() > dst_info->num_dimensions());
     ARM_COMPUTE_ERROR_ON(src_info->num_channels() != dst_info->num_channels());
     ARM_COMPUTE_ERROR_ON(src_info->element_size() != dst_info->element_size());
     for(size_t d = 0; d < src_info->num_dimensions(); d++)
     {
         ARM_COMPUTE_ERROR_ON(src_info->dimension(d) > dst_info->dimension(d));
     }
     // Copy information about valid region
     dst_info->set_valid_region(src_info->valid_region());
     Window win_src;
     win_src.use_tensor_dimensions(src_info->tensor_shape(), Window::DimY);
     Window win_dst;
     win_dst.use_tensor_dimensions(dst_info->tensor_shape(), Window::DimY);
     Iterator src_it(&src, win_src);
     Iterator dst_it(this, win_dst);
     const size_t line_size = src_info->element_size() * src_info->dimension(0);
     execute_window_loop(win_src, [&](const Coordinates & id)
     {
         memcpy(dst_it.ptr(), src_it.ptr(), line_size);
     },
     src_it, dst_it);
 }
info() [1/2]
virtual ITensorInfo* info () const pure virtual
Interface to be implemented by the child class to return the tensor's metadata.
Returns
A pointer to the tensor's metadata.
Implemented in CLSubTensor, GCTensor, SubTensor, CLTensor, and Tensor.
Referenced by NumPyAccessor::access_tensor(), ImageAccessor::access_tensor(), ValidationInputAccessor::access_tensor(), ValidationOutputAccessor::access_tensor(), TopNPredictionsAccessor::access_tensor(), RandomAccessor::access_tensor(), ICLKernel::add_tensor_argument(), CLArithmeticDivisionKernel::border_size(), CLArithmeticAdditionKernel::border_size(), CLArithmeticSubtractionKernel::border_size(), CLPixelWiseMultiplicationKernel::border_size(), NEArithmeticSubtractionKernel::border_size(), NEArithmeticAdditionKernel::border_size(), NEPixelWiseMultiplicationKernel::border_size(), IGCTensor::clear(), ICLTensor::clear(), CLSoftmaxLayer::CLSoftmaxLayer(), CLSubTensor::CLSubTensor(), arm_compute::colorconvert_iyuv_to_rgb(), arm_compute::colorconvert_nv12_to_rgb(), arm_compute::utils::compare_tensor(), GCLogits1DMaxKernel::configure(), CLIntegralImageHorKernel::configure(), CLWarpPerspectiveKernel::configure(), CLDilateKernel::configure(), CLBox3x3Kernel::configure(), CLErodeKernel::configure(), CLGaussian3x3Kernel::configure(), NEArithmeticAddition::configure(), CLMedian3x3Kernel::configure(), CLNonMaximaSuppression3x3Kernel::configure(), NEFloorKernel::configure(), NEIntegralImageKernel::configure(), CLTransposeKernel::configure(), CLWarpAffineKernel::configure(), NEReshapeLayerKernel::configure(), GCTransposeKernel::configure(), NEDilateKernel::configure(), NEErodeKernel::configure(), NEGaussian3x3Kernel::configure(), CLScaleKernel::configure(), NEMedian3x3Kernel::configure(), GCScaleKernel::configure(), NEBox3x3Kernel::configure(), NELogits1DMaxKernel::configure(), NEGaussian5x5HorKernel::configure(), CLArithmeticDivision::configure(), CLPixelWiseMultiplication::configure(), CLScale::configure(), CLSlice::configure(), CLPoolingLayer::configure(), NEPixelWiseMultiplication::configure(), CLArithmeticAddition::configure(), CLDepthwiseConvolutionLayer3x3NCHWKernel::configure(), NEUpsampleLayer::configure(), CLNonLinearFilterKernel::configure(), CLGEMMMatrixAccumulateBiasesKernel::configure(), GCGEMMMatrixAccumulateBiasesKernel::configure(), NEAccumulateKernel::configure(), CLDepthwiseConvolutionLayer3x3NHWCKernel::configure(), CLGEMMMatrixVectorMultiplyKernel::configure(), CLReduceMean::configure(), NEArithmeticSubtraction::configure(), CLFlattenLayerKernel::configure(), CLFloorKernel::configure(), CLArithmeticSubtraction::configure(), CLCopyKernel::configure(), CLRNNLayer::configure(), CLSplit::configure(), NEReduceMean::configure(), CLMinMaxLayerKernel::configure(), CLNormalizationLayerKernel::configure(), CLReshapeLayerKernel::configure(), CLChannelShuffleLayerKernel::configure(), CLGaussianPyramidHorKernel::configure(), NEGEMMLowpAssemblyMatrixMultiplyCore::configure(), NEIm2Col::configure(), NEPoolingLayer::configure(), CLBatchToSpaceLayerKernel::configure(), CLPermuteKernel::configure(), CLGradientKernel::configure(), CLComputeAllAnchorsKernel::configure(), CLHistogramKernel::configure(), CLMinMaxKernel::configure(), CLBitwiseAndKernel::configure(), NECopyKernel::configure(), CLBitwiseXorKernel::configure(), CLBitwiseOrKernel::configure(), CLRemapKernel::configure(), CLReorgLayerKernel::configure(), NEGEMMMatrixAccumulateBiasesKernel::configure(), CLSpaceToBatchLayerKernel::configure(), NEGEMMMatrixVectorMultiplyKernel::configure(), CLUpsampleLayerKernel::configure(), NELocallyConnectedMatrixMultiplyKernel::configure(), CLPadLayer::configure(), CLLocallyConnectedMatrixMultiplyKernel::configure(), NEScale::configure(), CLMemsetKernel::configure(), CLDepthwiseWeightsReshapeKernel::configure(), CLDerivativeKernel::configure(), ICLSimpleKernel::configure(), CLSobel3x3Kernel::configure(), CLActivationLayerKernel::configure(), NEPriorBoxLayerKernel::configure(), NETableLookupKernel::configure(), IGCSimpleKernel::configure(), GCActivationLayerKernel::configure(), GCDepthwiseConvolutionLayer3x3Kernel::configure(), CLDeconvolutionLayerUpsampleKernel::configure(), GCPixelWiseMultiplicationKernel::configure(), GCPoolingLayerKernel::configure(), NEWidthConcatenateLayer::configure(), CLNormalizePlanarYUVLayerKernel::configure(), CLPoolingLayerKernel::configure(), CLQuantizationLayerKernel::configure(), NEGaussianPyramidHorKernel::configure(), CLSobel5x5HorKernel::configure(), CLFillBorderKernel::configure(), CLSobel7x7HorKernel::configure(), CLWidthConcatenate2TensorsKernel::configure(), CPPFlipWeightsKernel::configure(), INEWarpKernel::configure(), CLGEMMMatrixAdditionKernel::configure(), CLDirectConvolutionLayer::configure(), GCFillBorderKernel::configure(), CLMeanStdDev::configure(), GCGEMMMatrixAdditionKernel::configure(), CLHOGOrientationBinningKernel::configure(), GCNormalizationLayerKernel::configure(), CLDepthConvertLayerKernel::configure(), NEChannelShuffleLayerKernel::configure(), CLDequantizationLayerKernel::configure(), CLPixelWiseMultiplicationKernel::configure(), NEDepthwiseWeightsReshapeKernel::configure(), CLPriorBoxLayerKernel::configure(), CLReductionOperationKernel::configure(), CLBoundingBoxTransformKernel::configure(), CLAbsoluteDifferenceKernel::configure(), CLChannelExtractKernel::configure(), CLWidthConcatenateLayerKernel::configure(), GCAbsoluteDifferenceKernel::configure(), CLArithmeticDivisionKernel::configure(), CLConcatenateLayer::configure(), GCNormalizePlanarYUVLayerKernel::configure(), CLSpaceToBatchLayer::configure(), GCConvolutionLayerReshapeWeights::configure(), GCNormalizationLayer::configure(), NEConcatenateLayer::configure(), NEHOGDescriptor::configure(), NEBitwiseNotKernel::configure(), CLDepthwiseVectorToTensorKernel::configure(), NEFlattenLayerKernel::configure(), CLWidthConcatenate4TensorsKernel::configure(), NEPoolingLayerKernel::configure(), NEReorgLayerKernel::configure(), CLArithmeticAdditionKernel::configure(), CLColorConvertKernel::configure(), NEUpsampleLayerKernel::configure(), GCArithmeticAdditionKernel::configure(), CLHOGDescriptor::configure(), GCGEMMTranspose1xWKernel::configure(), CLReductionOperation::configure(), CLL2NormalizeLayerKernel::configure(), CLMagnitudePhaseKernel::configure(), CLMeanStdDevKernel::configure(), NEBitwiseAndKernel::configure(), NEBitwiseOrKernel::configure(), NEBitwiseXorKernel::configure(), NEDerivativeKernel::configure(), CLDepthwiseIm2ColKernel::configure(), CLChannelCombineKernel::configure(), CLFuseBatchNormalizationKernel::configure(), NEReductionOperationKernel::configure(), GCSoftmaxLayer::configure(), NEGaussian5x5::configure(), NEHOGGradient::configure(), NENormalizationLayer::configure(), NEColorConvertKernel::configure(), CLDirectConvolutionLayerOutputStageKernel::configure(), NEFastCornersKernel::configure(), NEHOGOrientationBinningKernel::configure(), NENormalizationLayerKernel::configure(), NERemapKernel::configure(), CPPPermuteKernel::configure(), NETransposeKernel::configure(), CLConvertFullyConnectedWeightsKernel::configure(), NEYOLOLayerKernel::configure(), CLConvolutionKernel< matrix_size >::configure(), GCBatchNormalizationLayerKernel::configure(), GCDepthConcatenateLayerKernel::configure(), GCDirectConvolutionLayerKernel< kernel_size >::configure(), CLHOGGradient::configure(), CLWidthConcatenateLayer::configure(), CLDepthConcatenateLayerKernel::configure(), NEDepthConcatenateLayer::configure(), NEConvolutionLayerReshapeWeights::configure(), CLArithmeticSubtractionKernel::configure(), NEDepthwiseVectorToTensorKernel::configure(), NEDequantizationLayerKernel::configure(), CLROIPoolingLayerKernel::configure(), NENonLinearFilterKernel::configure(), CLGEMMLowpMatrixMultiplyKernel::configure(), CLWinogradInputTransformKernel::configure(), NEQuantizationLayerKernel::configure(), CLYOLOLayerKernel::configure(), NEThresholdKernel::configure(), CPPUpsampleKernel::configure(), NEWidthConcatenateLayerKernel::configure(), CLGaussian5x5::configure(), CLIntegralImageVertKernel::configure(), NEAbsoluteDifferenceKernel::configure(), NEChannelExtractKernel::configure(), NEDepthwiseConvolutionLayer3x3Kernel::configure(), NEFillArrayKernel::configure(), NEFillInnerBorderKernel::configure(), CLROIAlignLayerKernel::configure(), NESobel5x5::configure(), NEMagnitudePhaseKernel< mag_type, phase_type >::configure(), NEActivationLayerKernel::configure(), NEMinMaxKernel::configure(), NENonMaximaSuppression3x3Kernel::configure(), NEPermuteKernel::configure(), NESobel7x7HorKernel::configure(), NESobel5x5HorKernel::configure(), CLGEMMMatrixMultiplyKernel::configure(), NESobel7x7::configure(), CLSoftmaxLayer::configure(), NERNNLayer::configure(), NEDepthConcatenateLayerKernel::configure(), NEDepthConvertLayerKernel::configure(), NEDepthwiseIm2ColKernel::configure(), NEDirectConvolutionLayerOutputStageKernel::configure(), NEFillBorderKernel::configure(), NEGEMMInterleave4x4Kernel::configure(), NEGEMMMatrixAdditionKernel::configure(), NEMeanStdDevKernel::configure(), CLWinogradFilterTransformKernel::configure(), CLConvolutionLayer::configure(), CLDepthConcatenateLayer::configure(), GCDropoutLayerKernel::configure(), GCLogits1DShiftExpSumKernel::configure(), NEGradientKernel::configure(), CLBatchNormalizationLayerKernel::configure(), NEChannelCombineKernel::configure(), NEConvertFullyConnectedWeightsKernel::configure(), GCGEMMMatrixMultiplyKernel::configure(), NEHOGDetectorKernel::configure(), CLStridedSliceKernel::configure(), NEMinMaxLayerKernel::configure(), CLWinogradOutputTransformKernel::configure(), CLGEMMLowpOffsetContributionOutputStageKernel::configure(), CPPCornerCandidatesKernel::configure(), CLHarrisScoreKernel::configure(), CLSobel5x5::configure(), CLSobel7x7::configure(), NEFastCorners::configure(), NEPixelWiseMultiplicationKernel::configure(), NECumulativeDistributionKernel::configure(), NEDirectConvolutionLayerKernel::configure(), CLFastCornersKernel::configure(), NEROIPoolingLayerKernel::configure(), NEScaleKernel::configure(), CPPBoxWithNonMaximaSuppressionLimitKernel::configure(), CLDepthwiseConvolutionLayer3x3::configure(), CLConvolutionLayerReshapeWeights::configure(), NEDepthwiseConvolutionLayer3x3::configure(), GCDirectConvolutionLayer::configure(), CLDirectConvolutionLayerKernel::configure(), CLHOGDetectorKernel::configure(), NEGEMMLowpMatrixMultiplyKernel::configure(), NEGEMMMatrixMultiplyKernel::configure(), NEGEMMInterleavedWrapper::configure(), NEBatchNormalizationLayerKernel::configure(), CLCannyEdge::configure(), CLLaplacianPyramid::configure(), GCGEMMInterleave4x4Kernel::configure(), NEConvolutionLayer::configure(), NELaplacianPyramid::configure(), CLGEMMLowpQuantizeDownInt32ToUint8ScaleByFixedPointKernel::configure(), CLGEMMLowpQuantizeDownInt32ToUint8ScaleByFloatKernel::configure(), NEConvolutionKernel< matrix_size >::configure(), NEArithmeticSubtractionKernel::configure(), CLGEMMLowpQuantizeDownInt32ToUint8ScaleKernel::configure(), CLScharr3x3Kernel::configure(), CLGEMMLowpOffsetContributionKernel::configure(), NEScharr3x3Kernel::configure(), CLFastCorners::configure(), NESobel3x3Kernel::configure(), NEDirectConvolutionLayer::configure(), NEArithmeticAdditionKernel::configure(), CLGEMMLowpMatrixAReductionKernel::configure(), NEHistogramKernel::configure(), CLGEMMInterleave4x4Kernel::configure(), NEWinogradConvolutionLayer::configure(), GCTensorShiftKernel::configure(), NEGaussian5x5VertKernel::configure(), NEGEMMLowpOffsetContributionKernel::configure(), CLCol2ImKernel::configure(), NELocallyConnectedLayer::configure(), CLLocallyConnectedLayer::configure(), NEGEMMLowpQuantizeDownInt32ToUint8ScaleByFixedPointKernel::configure(), NEGEMMLowpQuantizeDownInt32ToUint8ScaleKernel::configure(), CLGEMMTranspose1xWKernel::configure(), CLWinogradConvolutionLayer::configure(), NEGEMM::configure(), GCGEMM::configure(), NECannyEdge::configure(), CLLaplacianReconstruct::configure(), NELaplacianReconstruct::configure(), GCWeightsReshapeKernel::configure(), NECol2ImKernel::configure(), NEGEMMTranspose1xWKernel::configure(), GCCol2ImKernel::configure(), NEOpticalFlow::configure(), CLWeightsReshapeKernel::configure(), GCIm2ColKernel::configure(), CLIm2ColKernel::configure(), CLHarrisCorners::configure(), CLGEMM::configure(), NEAccumulateWeightedKernel::configure(), NEGEMMLowpMatrixMultiplyCore::configure(), NEHarrisCorners::configure(), NEGEMMLowpMatrixAReductionKernel::configure(), CLGEMMLowpMatrixMultiplyCore::configure(), NEHOGMultiDetection::configure(), CLHOGMultiDetection::configure(), NEWeightsReshapeKernel::configure(), GCFullyConnectedLayer::configure(), NELSTMLayer::configure(), CLConvolutionSquare< matrix_size >::configure(), NEConvolutionSquare< matrix_size >::configure(), CLHistogramBorderKernel::configure(), CLGaussianPyramidVertKernel::configure(), CLGenerateProposalsLayer::configure(), NEIm2ColKernel::configure(), CLGaussianPyramidHalf::configure(), CLOpticalFlow::configure(), CLLSTMLayer::configure(), NEGaussianPyramidHalf::configure(), CLEdgeNonMaxSuppressionKernel::configure(), CLMinMaxLocationKernel::configure(), NEGEMMAssemblyDispatch::configure(), NEHarrisScoreKernel< block_size >::configure(), CLHOGBlockNormalizationKernel::configure(), NEGaussianPyramidVertKernel::configure(), CLSeparableConvolutionHorKernel< matrix_size >::configure(), GCLogits1DNormKernel::configure(), CLDeconvolutionLayer::configure(), CLGEMMLowpMatrixBReductionKernel::configure(), NEDeconvolutionLayer::configure(), CLSobel5x5VertKernel::configure(), CLSobel7x7VertKernel::configure(), NELogits1DSoftmaxKernel::configure(), NEFullyConnectedLayer::configure(), CLFullyConnectedLayer::configure(), CLCopyToArrayKernel::configure(), GCConvolutionLayer::configure(), NESobel5x5VertKernel::configure(), CLGaussianPyramidOrb::configure(), NEGaussianPyramidOrb::configure(), NESobel7x7VertKernel::configure(), NEGEMMLowpMatrixBReductionKernel::configure(), NESeparableConvolutionHorKernel< matrix_size >::configure(), NEHOGBlockNormalizationKernel::configure(), NEGEMMConvolutionLayer::configure(), NEEdgeNonMaxSuppressionKernel::configure(), CLLogits1DMaxShiftExpSumKernel::configure(), CLSeparableConvolutionVertKernel< matrix_size >::configure(), CLDepthwiseConvolutionLayer::configure(), CLGEMMConvolutionLayer::configure(), CLEdgeTraceKernel::configure(), NEAccumulateSquaredKernel::configure(), NEMinMaxLocationKernel::configure(), CLLKTrackerStage0Kernel::configure(), NEDepthwiseConvolutionLayer::configure(), NESeparableConvolutionVertKernel< matrix_size >::configure(), CLConvolutionRectangleKernel::configure(), CLLKTrackerStage1Kernel::configure(), NEEdgeTraceKernel::configure(), CLLogits1DNormKernel::configure(), NEConvolutionRectangleKernel::configure(), NEWinogradLayerTransformOutputKernel< T, OutputTileRows, OutputTileCols, KernelRows, KernelCols >::configure(), ITensor::copy_from(), arm_compute::graph::backends::detail::create_concatenate_layer< GCDepthConcatenateLayer, GCTargetInfo >(), arm_compute::graph::backends::detail::create_convolution_layer< GCConvolutionLayerFunctions, GCTargetInfo >(), arm_compute::graph::backends::detail::create_depthwise_convolution_layer< GCDepthwiseConvolutionLayerFunctions, GCTargetInfo >(), arm_compute::utils::draw_detection_rectangle(), arm_compute::error_on_data_layout_not_in(), arm_compute::error_on_data_type_channel_not_in(), arm_compute::error_on_data_type_not_in(), arm_compute::error_on_mismatching_data_layouts(), arm_compute::error_on_mismatching_data_types(), arm_compute::error_on_mismatching_quantization_info(), arm_compute::error_on_mismatching_shapes(), arm_compute::error_on_tensor_not_2d(), arm_compute::error_on_unsupported_cpu_fp16(), arm_compute::error_on_unsupported_fp16(), CPPFlipWeightsKernel::flip_weights(), GCFullyConnectedLayer::GCFullyConnectedLayer(), NEDepthwiseConvolutionLayer3x3Kernel::generate_convolver(), arm_compute::graph::backends::detail::get_backing_tensor_info(), ICPPSimpleKernel::ICPPSimpleKernel(), Iterator::Iterator(), IGCKernel::kernel(), NEPriorBoxLayerKernel::NEPriorBoxLayerKernel(), NumPyAccessor::NumPyAccessor(), get_tensor_info_t< ITensorInfo * >::operator()(), CaffePreproccessor::preprocess(), TFPreproccessor::preprocess(), ITensor::print(), ITensor::ptr_to_element(), RandomAccessor::RandomAccessor(), NEMinMaxKernel::reset(), CLMinMaxLayerKernel::reset(), NEMinMaxLayerKernel::reset(), CLHistogramKernel::run(), CLMinMaxKernel::run(), NELogits1DMaxKernel::run(), GCDepthwiseConvolutionLayer3x3Kernel::run(), GCActivationLayerKernel::run(), CLGEMMMatrixVectorMultiplyKernel::run(), GCDepthConcatenateLayerKernel::run(), NEHOGOrientationBinningKernel::run(), CLIntegralImageVertKernel::run(), CPPUpsampleKernel::run(), CLFlattenLayerKernel::run(), NECopyKernel::run(), NEFillInnerBorderKernel::run(), NEGEMMMatrixAccumulateBiasesKernel::run(), NENonMaximaSuppression3x3Kernel::run(), NEFillBorderKernel::run(), NELocallyConnectedMatrixMultiplyKernel::run(), CLLocallyConnectedMatrixMultiplyKernel::run(), NEMeanStdDevKernel::run(), NEGEMMMatrixVectorMultiplyKernel::run(), NEHOGDetectorKernel::run(), CLUpsampleLayerKernel::run(), GCDirectConvolutionLayerKernel< kernel_size >::run(), NEROIPoolingLayerKernel::run(), CLDepthwiseWeightsReshapeKernel::run(), CLDeconvolutionLayerUpsampleKernel::run(), GCPoolingLayerKernel::run(), CLPoolingLayerKernel::run(), CLArithmeticDivisionKernel::run(), CPPBoxWithNonMaximaSuppressionLimitKernel::run(), CLDepthwiseVectorToTensorKernel::run(), NEChannelShuffleLayerKernel::run(), CLPriorBoxLayerKernel::run(), CLDequantizationLayerKernel::run(), NEFlattenLayerKernel::run(), CLArithmeticAdditionKernel::run(), GCArithmeticAdditionKernel::run(), CLMeanStdDevKernel::run(), GCNormalizePlanarYUVLayerKernel::run(), NEPoolingLayerKernel::run(), CLDepthConcatenateLayerKernel::run(), NEWidthConcatenateLayerKernel::run(), CLReductionOperationKernel::run(), GCTensorShiftKernel::run(), CLArithmeticSubtractionKernel::run(), NEDequantizationLayerKernel::run(), NEWinogradConvolutionLayer::run(), CLDirectConvolutionLayerOutputStageKernel::run(), NEQuantizationLayerKernel::run(), CLGEMMLowpMatrixMultiplyKernel::run(), CLPixelWiseMultiplicationKernel::run(), NEConvertFullyConnectedWeightsKernel::run(), CLDeconvolutionLayerUpsample::run(), NEDepthConvertLayerKernel::run(), CLDepthwiseIm2ColKernel::run(), NECannyEdge::run(), NEMinMaxLayerKernel::run(), NEGEMMLowpMatrixMultiplyKernel::run(), CLColorConvertKernel::run(), GCWeightsReshapeKernel::run(), GCCol2ImKernel::run(), CLROIAlignLayerKernel::run(), CLGEMMMatrixMultiplyKernel::run(), GCIm2ColKernel::run(), GCGEMMMatrixMultiplyKernel::run(), NEGEMMMatrixMultiplyKernel::run(), NEDirectConvolutionLayerKernel::run(), CLGEMMInterleave4x4Kernel::run(), NEPixelWiseMultiplicationKernel::run(), GCBatchNormalizationLayerKernel::run(), CLWinogradInputTransformKernel::run(), CLCol2ImKernel::run(), CLDirectConvolutionLayerKernel::run(), CLWinogradFilterTransformKernel::run(), NEGEMMLowpOffsetContributionKernel::run(), CLWinogradOutputTransformKernel::run(), CLSpaceToBatchLayer::run(), NEGEMMLowpMatrixAReductionKernel::run(), CLWeightsReshapeKernel::run(), CLIm2ColKernel::run(), NELogits1DSoftmaxKernel::run(), NESobel7x7VertKernel::run(), NEHOGBlockNormalizationKernel::run(), NEEdgeNonMaxSuppressionKernel::run(), NEGEMMLowpMatrixBReductionKernel::run(), CLLogits1DMaxShiftExpSumKernel::run(), NEWinogradLayerTransformInputKernel< T, OutputTileRows, OutputTileCols, KernelRows, KernelCols >::run(), NEEdgeTraceKernel::run(), NEConvolutionRectangleKernel::run(), NEWinogradLayerTransformOutputKernel< T, OutputTileRows, OutputTileCols, KernelRows, KernelCols >::run(), CPPBoxWithNonMaximaSuppressionLimitKernel::run_nmslimit(), SubTensor::SubTensor(), TopNPredictionsAccessor::TopNPredictionsAccessor(), arm_compute::vadd(), NEUpsampleLayerKernel::validate(), and NEConvertFullyConnectedWeightsKernel::validate().
info() [2/2]
virtual ITensorInfo* info () pure virtual
Interface to be implemented by the child class to return the tensor's metadata.
Returns
A pointer to the tensor's metadata.
Implemented in CLSubTensor, GCTensor, SubTensor, CLTensor, and Tensor.
is_used()
bool is_used () const
Flags if the tensor is used or not.
Returns
True if it is used else false
Definition at line 155 of file ITensor.cpp.
Referenced by GCFullyConnectedLayer::prepare(), NELocallyConnectedLayer::prepare(), CLLocallyConnectedLayer::prepare(), NEGEMM::prepare(), GCGEMM::prepare(), CLGEMMLowpMatrixMultiplyCore::prepare(), NEGEMMLowpMatrixMultiplyCore::prepare(), CLWinogradConvolutionLayer::prepare(), GCConvolutionLayer::prepare(), CLDeconvolutionLayer::prepare(), NEDeconvolutionLayer::prepare(), NEFullyConnectedLayer::prepare(), CLFullyConnectedLayer::prepare(), NEGEMMConvolutionLayer::prepare(), CLDepthwiseConvolutionLayer::prepare(), CLGEMMConvolutionLayer::prepare(), NEDepthwiseConvolutionLayer::prepare(), ITensor::ptr_to_element(), GCTensorHandle::release_if_unused(), NETensorHandle::release_if_unused(), and CLTensorHandle::release_if_unused().
 {
     return _is_used;
 }
mark_as_unused()
void mark_as_unused () const
Marks a tensor as unused.
Definition at line 160 of file ITensor.cpp.
Referenced by NEGEMMInterleavedWrapper::prepare(), NEWinogradConvolutionLayer::prepare(), GCFullyConnectedLayer::prepare(), CLLocallyConnectedLayer::prepare(), NELocallyConnectedLayer::prepare(), NEGEMM::prepare(), GCGEMM::prepare(), NEGEMMLowpMatrixMultiplyCore::prepare(), CLGEMMLowpMatrixMultiplyCore::prepare(), CLGEMM::prepare(), CLWinogradConvolutionLayer::prepare(), GCConvolutionLayer::prepare(), CLDeconvolutionLayer::prepare(), NEDeconvolutionLayer::prepare(), NEFullyConnectedLayer::prepare(), CLFullyConnectedLayer::prepare(), NEGEMMConvolutionLayer::prepare(), CLDepthwiseConvolutionLayer::prepare(), CLGEMMConvolutionLayer::prepare(), NEDepthwiseConvolutionLayer::prepare(), and ITensor::ptr_to_element().
 {
     _is_used = false;
 }
print()
void print (std::ostream & s, IOFormatInfo io_fmt = IOFormatInfo()) const
Print a tensor to a given stream using user defined formatting information.
Parameters
s Output stream
io_fmt Format information
Definition at line 74 of file ITensor.cpp.
References IOFormatInfo::align_columns, ValidRegion::anchor, ARM_COMPUTE_ERROR_ON, BorderSize::bottom, ITensor::buffer(), ITensorInfo::data_type(), IOFormatInfo::Default, ITensorInfo::dimension(), IOFormatInfo::element_delim, IOFormatInfo::Full, ITensor::info(), arm_compute::is_data_type_float(), BorderSize::left, arm_compute::max_consecutive_elements_display_width(), IOFormatInfo::NoPadding, ITensorInfo::num_channels(), offset(), ITensorInfo::offset_element_in_bytes(), ITensorInfo::offset_first_element_in_bytes(), arm_compute::test::validation::padding, ITensorInfo::padding(), IOFormatInfo::precision, IOFormatInfo::precision_type, arm_compute::print_consecutive_elements(), IOFormatInfo::print_region, BorderSize::right, IOFormatInfo::row_delim, ValidRegion::shape, ITensorInfo::strides_in_bytes(), ITensorInfo::tensor_shape(), BorderSize::top, TensorShape::total_size_upper(), arm_compute::test::validation::valid_region, ITensorInfo::valid_region(), IOFormatInfo::ValidRegion, Dimensions< T >::x(), and Dimensions< T >::y().
Referenced by arm_compute::test::print_tensor(), and ITensor::ptr_to_element().
 {
     ARM_COMPUTE_ERROR_ON(this->buffer() == nullptr);
     const DataType    dt           = this->info()->data_type();
     const size_t      slices2D     = this->info()->tensor_shape().total_size_upper(2);
     const Strides     strides      = this->info()->strides_in_bytes();
     const PaddingSize padding      = this->info()->padding();
     const size_t      num_channels = this->info()->num_channels();
     // Set precision
     if(is_data_type_float(dt) && (io_fmt.precision_type != IOFormatInfo::PrecisionType::Default))
     {
         int precision = io_fmt.precision;
         if(io_fmt.precision_type == IOFormatInfo::PrecisionType::Full)
         {
             precision = std::numeric_limits<float>().max_digits10;
         }
         s.precision(precision);
     }
     // Define region to print
     size_t print_width  = 0;
     size_t print_height = 0;
     int    start_offset = 0;
     switch(io_fmt.print_region)
     {
         case IOFormatInfo::PrintRegion::NoPadding:
             print_width  = this->info()->dimension(0);
             print_height = this->info()->dimension(1);
             start_offset = this->info()->offset_first_element_in_bytes();
             break;
         case IOFormatInfo::PrintRegion::ValidRegion:
             print_width  = this->info()->valid_region().shape.x();
             print_height = this->info()->valid_region().shape.y();
             start_offset = this->info()->offset_element_in_bytes(Coordinates(this->info()->valid_region().anchor.x(),
                                                                              this->info()->valid_region().anchor.y()));
             break;
         case IOFormatInfo::PrintRegion::Full:
             print_width  = padding.left + this->info()->dimension(0) + padding.right;
             print_height = padding.top + this->info()->dimension(1) + padding.bottom;
             start_offset = static_cast<int>(this->info()->offset_first_element_in_bytes()) - padding.top * strides[1] - padding.left * strides[0];
             break;
         default:
             break;
     }
     print_width = print_width * num_channels;
     // Set pointer to start
     const uint8_t *ptr = this->buffer() + start_offset;
     // Start printing
     for(size_t i = 0; i < slices2D; ++i)
     {
         // Find max_width of elements in slice to align columns
         int max_element_width = 0;
         if(io_fmt.align_columns)
         {
             size_t offset = i * strides[2];
             for(size_t h = 0; h < print_height; ++h)
             {
                 max_element_width = std::max<int>(max_element_width, max_consecutive_elements_display_width(s, dt, ptr + offset, print_width));
                 offset += strides[1];
             }
         }
         // Print slice
         {
             size_t offset = i * strides[2];
             for(size_t h = 0; h < print_height; ++h)
             {
                 print_consecutive_elements(s, dt, ptr + offset, print_width, max_element_width, io_fmt.element_delim);
                 offset += strides[1];
                 s << io_fmt.row_delim;
             }
             s << io_fmt.row_delim;
         }
     }
 }
ptr_to_element()
uint8_t* ptr_to_element (const Coordinates & id) const inline
Return a pointer to the element at the passed coordinates.
Parameters
[in] id Coordinates of the element
Returns
Pointer to the requested element
Definition at line 63 of file ITensor.h.
References ITensor::buffer(), ITensor::copy_from(), ITensor::info(), ITensor::is_used(), ITensor::mark_as_unused(), ITensorInfo::offset_element_in_bytes(), ITensor::print(), and arm_compute::test::validation::src.
Referenced by NEPoolingLayerKernel::configure(), NENonLinearFilterKernel::configure(), arm_compute::test::validation::DATA_TEST_CASE(), CPPFlipWeightsKernel::flip_weights(), NEDepthwiseConvolutionLayer3x3Kernel::generate_convolver(), NEPriorBoxLayerKernel::NEPriorBoxLayerKernel(), GCAccessor::operator()(), Accessor::operator()(), CLAccessor::operator()(), NEFastCornersKernel::run(), NEFillBorderKernel::run(), NEROIPoolingLayerKernel::run(), NESobel3x3Kernel::run(), NEScharr3x3Kernel::run(), NESobel5x5VertKernel::run(), and CPPBoxWithNonMaximaSuppressionLimitKernel::run_nmslimit().
     {
         return buffer() + info()->offset_element_in_bytes(id);
     }
The documentation for this class was generated from the following files:
arm_compute/core/ITensor.h
src/core/ITensor.cpp