Compute Library: DepthwiseSeparableConvolutionLayerDataset Class Reference
DepthwiseSeparableConvolutionLayerDataset Class Reference
#include <DepthwiseSeparableConvolutionLayerDataset.h>
Data Structures
struct iterator
Public Types
using type = std::tuple< TensorShape, TensorShape, TensorShape, TensorShape, TensorShape, TensorShape, TensorShape, PadStrideInfo, PadStrideInfo >
Public Member Functions
iterator begin () const
int size () const
void add_config (TensorShape src, TensorShape filter, TensorShape filter_bias, TensorShape depthwise_out, TensorShape weights, TensorShape biases, TensorShape dst, PadStrideInfo depthwise_info, PadStrideInfo pointwise_info)
Detailed Description
Definition at line 38 of file DepthwiseSeparableConvolutionLayerDataset.h.
Member Typedef Documentation
using type = std::tuple<TensorShape, TensorShape, TensorShape, TensorShape, TensorShape, TensorShape, TensorShape, PadStrideInfo, PadStrideInfo>
Definition at line 41 of file DepthwiseSeparableConvolutionLayerDataset.h.
Member Function Documentation
void add_config (TensorShape src, TensorShape filter, TensorShape filter_bias, TensorShape depthwise_out, TensorShape weights, TensorShape biases, TensorShape dst, PadStrideInfo depthwise_info, PadStrideInfo pointwise_info) inline
Definition at line 127 of file DepthwiseSeparableConvolutionLayerDataset.h.
Referenced by MobileNetDepthwiseSeparableConvolutionLayerDataset::MobileNetDepthwiseSeparableConvolutionLayerDataset().
     {
         _src_shapes.emplace_back(std::move(src));
         _filter_shapes.emplace_back(std::move(filter));
         _filter_biases_shapes.emplace_back(std::move(filter_bias));
         _depthwise_out_shapes.emplace_back(std::move(depthwise_out));
         _weight_shapes.emplace_back(std::move(weights));
         _bias_shapes.emplace_back(std::move(biases));
         _dst_shapes.emplace_back(std::move(dst));
         _depthwise_infos.emplace_back(std::move(depthwise_info));
         _pointwise_infos.emplace_back(std::move(pointwise_info));
     }
iterator begin () const inline
Definition at line 113 of file DepthwiseSeparableConvolutionLayerDataset.h.
References DepthwiseSeparableConvolutionLayerDataset::iterator::iterator().
     {
         return iterator(_src_shapes.begin(), _filter_shapes.begin(), _filter_biases_shapes.begin(), _depthwise_out_shapes.begin(), _weight_shapes.begin(), _bias_shapes.begin(), _dst_shapes.begin(),
                         _depthwise_infos.begin(),
                         _pointwise_infos.begin());
     }
int size () const inline
Definition at line 120 of file DepthwiseSeparableConvolutionLayerDataset.h.
References arm_compute::test::fixed_point_arithmetic::detail::min().
     {
         return std::min(_src_shapes.size(), std::min(_filter_shapes.size(), std::min(_filter_biases_shapes.size(), std::min(_depthwise_out_shapes.size(), std::min(_weight_shapes.size(),
                                                                                                                             std::min(_bias_shapes.size(), std::min(_dst_shapes.size(),
                                                                                                                                     std::min(_depthwise_infos.size(), _pointwise_infos.size()))))))));
     }
The documentation for this class was generated from the following file:
tests/datasets/DepthwiseSeparableConvolutionLayerDataset.h