Compute Library: NEGEMMLowpMatrixBReductionKernel Class Reference
NEGEMMLowpMatrixBReductionKernel Class Reference
NEON kernel used to compute the row-vectors of sums of all the entries in each column of Matrix B.
#include <NEGEMMLowpReductionKernel.h>
Public Member Functions
const char * name () const override
Name of the kernel.
void configure (const ITensor *mtx_b, ITensor *vector_sum_col, int32_t num_mtx_b_rows, bool is_transposed1xW) override
Initialise the kernel's input and output.
void run (const Window &window, const ThreadInfo &info) override
Execute the kernel on the passed window.
Public Member Functions inherited from INEGEMMLowpReductionKernel
INEGEMMLowpReductionKernel ()
Constructor.
INEGEMMLowpReductionKernel (const INEGEMMLowpReductionKernel &)=delete
Prevent instances of this class from being copied (As this class contains pointers)
INEGEMMLowpReductionKernel & operator= (const INEGEMMLowpReductionKernel &)=delete
Prevent instances of this class from being copied (As this class contains pointers)
INEGEMMLowpReductionKernel (INEGEMMLowpReductionKernel &&)=default
Allow instances of this class to be moved.
INEGEMMLowpReductionKernel & operator= (INEGEMMLowpReductionKernel &&)=default
Allow instances of this class to be moved.
Public Member Functions inherited from ICPPKernel
virtual ~ICPPKernel ()=default
Default destructor.
Public Member Functions inherited from IKernel
IKernel ()
Constructor.
virtual ~IKernel ()=default
Destructor.
virtual bool is_parallelisable () const
Indicates whether or not the kernel is parallelisable.
virtual BorderSize border_size () const
The size of the border for that kernel.
const Window & window () const
The maximum window the kernel can be executed on.
Static Public Member Functions
static Status validate (const ITensorInfo *mtx_b, const ITensorInfo *vector_sum_col, int32_t num_mtx_b_rows, bool is_transposed1xW)
Static function to check if given info will lead to a valid configuration of NEGEMMLowpMatrixBReductionKernel.
Detailed Description
NEON kernel used to compute the row-vectors of sums of all the entries in each column of Matrix B.
Note
This stage is needed to handle the offset of matrix product https://github.com/google/gemmlowp/blob/master/doc/low-precision.md
Definition at line 104 of file NEGEMMLowpReductionKernel.h.
Member Function Documentation
configure()
void configure (const ITensor * mtx_b, ITensor * vector_sum_col, int32_t num_mtx_b_rows, bool is_transposed1xW) override virtual
Initialise the kernel's input and output.
Parameters
[in] mtx_b Input tensor. Data type supported: Data type supported: QASYMM8
[out] vector_sum_col Output row-vector of sums of all the entries in each column of mtx_b. Data type supported: S32
[in] num_mtx_b_rows Number of matrix B rows
[in] is_transposed1xW True if the input tensor is transposed 1xW
Implements INEGEMMLowpReductionKernel.
Definition at line 253 of file NEGEMMLowpReductionKernel.cpp.
 {
     ARM_COMPUTE_ERROR_ON_NULLPTR(mtx_b, vector_sum_col);
     ARM_COMPUTE_ERROR_THROW_ON(validate_arguments_matrix_b_reduction(mtx_b->info(), vector_sum_col->info()));
     _input       = mtx_b;
     _output      = vector_sum_col;
     _k           = num_mtx_b_rows;
     _is_reshaped = is_transposed1xW;
     // Configure kernel window
     auto win_config = validate_and_configure_window_matrix_b_reduction(_input->info(), _output->info());
     ARM_COMPUTE_ERROR_THROW_ON(win_config.first);
     INEKernel::configure(win_config.second);
 }
References ARM_COMPUTE_ERROR_ON_NULLPTR, ARM_COMPUTE_ERROR_THROW_ON, and ITensor::info().
Referenced by NEGEMMLowpMatrixMultiplyCore::configure().
name()
const char* name () const inline override virtual
Name of the kernel.
Returns
Kernel name
Implements ICPPKernel.
Definition at line 107 of file NEGEMMLowpReductionKernel.h.
     {
         return "NEGEMMLowpMatrixBReductionKernel";
     }
run()
void run (const Window & window, const ThreadInfo & info) override virtual
Execute the kernel on the passed window.
Warning
If is_parallelisable() returns false then the passed window must be equal to window()
Note
The window has to be a region within the window returned by the window() method
The width of the window has to be a multiple of num_elems_processed_per_iteration().
Parameters
[in] window Region on which to execute the kernel. (Must be a region of the window returned by window())
[in] info Info about executing thread and CPU.
Implements ICPPKernel.
Definition at line 279 of file NEGEMMLowpReductionKernel.cpp.
 {
     ARM_COMPUTE_UNUSED(info);
     ARM_COMPUTE_ERROR_ON_UNCONFIGURED_KERNEL(this);
     ARM_COMPUTE_ERROR_ON_INVALID_SUBWINDOW(INEKernel::window(), window);
     Window collapsed_window = window.collapse_if_possible(IKernel::window(), Window::DimY);
     if(_is_reshaped)
     {
         Window win_input(collapsed_window);
         win_input.set(Window::DimX, Window::Dimension(0, 0, 0));
         win_input.set(Window::DimY, Window::Dimension(0, 0, 0));
         win_input.set(Window::DimZ, Window::Dimension(0, 0, 0));
         Iterator in(_input, win_input);
         Iterator out(_output, collapsed_window);
         execute_window_loop(collapsed_window, [&](const Coordinates & id)
         {
             // Note: Since the input is unsigned char, we can safely use unsigned int for the accumulation
             uint32x4x4_t sum_col =
             {
                 {
                     vdupq_n_u32(0),
                     vdupq_n_u32(0),
                     vdupq_n_u32(0),
                     vdupq_n_u32(0)
                 }
             };
             const uint8_t *matrix_b = in.ptr() + (id.x() / 16) * _input->info()->strides_in_bytes()[1] + id.y() * _input->info()->strides_in_bytes()[2];
 #if __arm__
             asm volatile("PLD [%0, #128*4]" ::"r"(matrix_b));
 #endif /* __arm__ */
             int i = 0;
             for(; i < _k; ++i)
             {
                 const uint8x16_t b0_u8 = vld1q_u8(matrix_b + i * 16);
                 // Convert S8 to U16
                 const uint16x8x2_t b0_u16 =
                 {
                     {
                         vmovl_u8(vget_low_u8(b0_u8)),
                         vmovl_u8(vget_high_u8(b0_u8))
                     }
                 };
                 // Accumulate to U32
                 sum_col =
                 {
                     {
                         vaddw_u16(sum_col.val[0], vget_low_u16(b0_u16.val[0])),
                         vaddw_u16(sum_col.val[1], vget_high_u16(b0_u16.val[0])),
                         vaddw_u16(sum_col.val[2], vget_low_u16(b0_u16.val[1])),
                         vaddw_u16(sum_col.val[3], vget_high_u16(b0_u16.val[1]))
                     }
                 };
             }
             auto vector_sum_col = reinterpret_cast<int32_t *>(out.ptr());
             vst1q_s32(vector_sum_col + 0, vreinterpretq_s32_u32(sum_col.val[0]));
             vst1q_s32(vector_sum_col + 4, vreinterpretq_s32_u32(sum_col.val[1]));
             vst1q_s32(vector_sum_col + 8, vreinterpretq_s32_u32(sum_col.val[2]));
             vst1q_s32(vector_sum_col + 12, vreinterpretq_s32_u32(sum_col.val[3]));
         },
         in, out);
     }
     else // it is not reshaped
     {
         const auto width_matrix_b = static_cast<int>(_input->info()->dimension(0));
         const auto in_b_stride    = static_cast<int>(_input->info()->strides_in_bytes()[1]);
         // The implementation computes 16 elements per iteration
         const int window_start_x = 16 * info.thread_id;
         const int window_step_x  = 16 * info.num_threads;
         // Make sure (window_end_x - window_start_x) is a multiple of window_step_x
         const int window_end_x = ceil_to_multiple(width_matrix_b - window_start_x, window_step_x) + window_start_x;
         Window win_out(collapsed_window);
         win_out.set(Window::DimX, Window::Dimension(window_start_x, window_end_x, window_step_x));
         Window win_in(win_out);
         win_in.set(Window::DimY, Window::Dimension(0, 0, 0));
         win_in.set(Window::DimZ, Window::Dimension(0, 0, 0));
         Iterator inb(_input, win_in);
         Iterator out(_output, win_out);
         execute_window_loop(win_out, [&](const Coordinates & id)
         {
             if(id.x() > width_matrix_b)
             {
                 return;
             }
             // Note: Since the input is unsigned char, we can safely use unsigned int for the accumulation
             uint32x4x4_t sum_col =
             {
                 {
                     vdupq_n_u32(0),
                     vdupq_n_u32(0),
                     vdupq_n_u32(0),
                     vdupq_n_u32(0)
                 }
             };
             const uint8_t *matrix_b = inb.ptr() + id.y() * _input->info()->strides_in_bytes()[2];
 #if __arm__
             asm volatile("PLD [%0, #128*4]" ::"r"(matrix_b));
             asm volatile("PLD [%0, #128*4]" ::"r"(matrix_b + in_b_stride));
 #endif /* __arm__ */
             int i = 0;
             // This for loop performs 4 accumulations
             for(; i <= (_k - 4); i += 4)
             {
                 const uint8x16_t b0_u8 = vld1q_u8(matrix_b + 0 * in_b_stride);
                 const uint8x16_t b1_u8 = vld1q_u8(matrix_b + 1 * in_b_stride);
                 const uint8x16_t b2_u8 = vld1q_u8(matrix_b + 2 * in_b_stride);
                 const uint8x16_t b3_u8 = vld1q_u8(matrix_b + 3 * in_b_stride);
 #if __arm__
                 asm volatile("PLD [%0, #128*1]" ::"r"(matrix_b + 1 * in_b_stride));
                 asm volatile("PLD [%0, #128*1]" ::"r"(matrix_b + 2 * in_b_stride));
                 asm volatile("PLD [%0, #128*1]" ::"r"(matrix_b + 3 * in_b_stride));
                 asm volatile("PLD [%0, #128*1]" ::"r"(matrix_b + 4 * in_b_stride));
 #endif /* __arm__ */
                 // Partial accumulation in u16
                 uint16x8x2_t tmp_sum =
                 {
                     {
                         vdupq_n_u16(0),
                         vdupq_n_u16(0)
                     }
                 };
                 tmp_sum.val[0] = vaddw_u8(tmp_sum.val[0], vget_low_u8(b0_u8));
                 tmp_sum.val[0] = vaddw_u8(tmp_sum.val[0], vget_low_u8(b1_u8));
                 tmp_sum.val[0] = vaddw_u8(tmp_sum.val[0], vget_low_u8(b2_u8));
                 tmp_sum.val[0] = vaddw_u8(tmp_sum.val[0], vget_low_u8(b3_u8));
                 tmp_sum.val[1] = vaddw_u8(tmp_sum.val[1], vget_high_u8(b0_u8));
                 tmp_sum.val[1] = vaddw_u8(tmp_sum.val[1], vget_high_u8(b1_u8));
                 tmp_sum.val[1] = vaddw_u8(tmp_sum.val[1], vget_high_u8(b2_u8));
                 tmp_sum.val[1] = vaddw_u8(tmp_sum.val[1], vget_high_u8(b3_u8));
                 // Accumulate to U32
                 sum_col =
                 {
                     {
                         vaddw_u16(sum_col.val[0], vget_low_u16(tmp_sum.val[0])),
                         vaddw_u16(sum_col.val[1], vget_high_u16(tmp_sum.val[0])),
                         vaddw_u16(sum_col.val[2], vget_low_u16(tmp_sum.val[1])),
                         vaddw_u16(sum_col.val[3], vget_high_u16(tmp_sum.val[1]))
                     }
                 };
                 matrix_b += 4 * in_b_stride;
             }
             // This for loop perfoms the leftover accumulations
             for(; i < _k; ++i)
             {
                 const uint8x16_t b0_u8 = vld1q_u8(matrix_b + 0 * in_b_stride);
                 // Convert S8 to S16
                 const uint16x8x2_t b0_u16 =
                 {
                     {
                         vmovl_u8(vget_low_u8(b0_u8)),
                         vmovl_u8(vget_high_u8(b0_u8))
                     }
                 };
                 // Accumulate to U32
                 sum_col =
                 {
                     {
                         vaddw_u16(sum_col.val[0], vget_low_u16(b0_u16.val[0])),
                         vaddw_u16(sum_col.val[1], vget_high_u16(b0_u16.val[0])),
                         vaddw_u16(sum_col.val[2], vget_low_u16(b0_u16.val[1])),
                         vaddw_u16(sum_col.val[3], vget_high_u16(b0_u16.val[1]))
                     }
                 };
                 matrix_b += in_b_stride;
             }
             auto vector_sum_col = reinterpret_cast<int32_t *>(out.ptr());
             vst1q_s32(vector_sum_col + 0, vreinterpretq_s32_u32(sum_col.val[0]));
             vst1q_s32(vector_sum_col + 4, vreinterpretq_s32_u32(sum_col.val[1]));
             vst1q_s32(vector_sum_col + 8, vreinterpretq_s32_u32(sum_col.val[2]));
             vst1q_s32(vector_sum_col + 12, vreinterpretq_s32_u32(sum_col.val[3]));
         },
         inb, out);
     }
 }
References ARM_COMPUTE_ERROR_ON_INVALID_SUBWINDOW, ARM_COMPUTE_ERROR_ON_UNCONFIGURED_KERNEL, ARM_COMPUTE_UNUSED, arm_compute::ceil_to_multiple(), Window::collapse_if_possible(), Window::DimX, Window::DimY, Window::DimZ, arm_compute::execute_window_loop(), arm_compute::test::validation::info, Iterator::ptr(), Window::set(), and IKernel::window().
validate()
Status validate (const ITensorInfo * mtx_b, const ITensorInfo * vector_sum_col, int32_t num_mtx_b_rows, bool is_transposed1xW) static
Static function to check if given info will lead to a valid configuration of NEGEMMLowpMatrixBReductionKernel.
Parameters
[in] mtx_b Input tensor. Data type supported: Data type supported: QASYMM8
[in] vector_sum_col Output row-vector of sums of all the entries in each column of mtx_b. Data type supported: S32
[in] num_mtx_b_rows Number of matrix B rows
[in] is_transposed1xW True if the input tensor is transposed 1xW
Returns
a status
Definition at line 269 of file NEGEMMLowpReductionKernel.cpp.
 {
     ARM_COMPUTE_UNUSED(num_mtx_b_rows);
     ARM_COMPUTE_UNUSED(is_transposed1xW);
     ARM_COMPUTE_RETURN_ON_ERROR(validate_arguments_matrix_b_reduction(mtx_b, vector_sum_col));
     ARM_COMPUTE_RETURN_ON_ERROR(validate_and_configure_window_matrix_b_reduction(mtx_b->clone().get(), vector_sum_col->clone().get()).first);
     return Status{};
 }
References ARM_COMPUTE_RETURN_ON_ERROR, ARM_COMPUTE_UNUSED, and ICloneable< T >::clone().
Referenced by NEGEMMLowpMatrixMultiplyCore::validate().
The documentation for this class was generated from the following files:
arm_compute/core/NEON/kernels/NEGEMMLowpReductionKernel.h
src/core/NEON/kernels/NEGEMMLowpReductionKernel.cpp