Compute Library: DirectConvolutionValidationGenericFixture< TensorType, AccessorType, FunctionType, T > Class Template Reference
DirectConvolutionValidationGenericFixture< TensorType, AccessorType, FunctionType, T > Class Template Reference
#include <DirectConvolutionLayerFixture.h>
Public Types
using TBias = typename std::conditional< std::is_same< typename std::decay< T >::type, uint8_t >::value, int32_t, T >::type
Public Member Functions
template<typename... >
void setup (TensorShape input_shape, int stride_x, int stride_y, int pad_x, int pad_y, unsigned int kernel_size, unsigned int num_kernels, DataType data_type, int fractional_bits, QuantizationInfo quantization_info)
template<typename... >
void setup (TensorShape input_shape, TensorShape weights_shape, TensorShape bias_shape, TensorShape output_shape, PadStrideInfo info, DataType data_type, int fractional_bits, QuantizationInfo quantization_info)
Public Member Functions inherited from Fixture
void setup ()
Setup function.
void teardown ()
Teardown function.
Detailed Description
template<typename TensorType, typename AccessorType, typename FunctionType, typename T>
class arm_compute::test::validation::DirectConvolutionValidationGenericFixture< TensorType, AccessorType, FunctionType, T >
Definition at line 44 of file DirectConvolutionLayerFixture.h.
Member Typedef Documentation
using TBias = typename std::conditional<std::is_same<typename std::decay<T>::type, uint8_t>::value, int32_t, T>::type
Definition at line 47 of file DirectConvolutionLayerFixture.h.
Member Function Documentation
void setup (TensorShape input_shape, int stride_x, int stride_y, int pad_x, int pad_y, unsigned int kernel_size, unsigned int num_kernels, DataType data_type, int fractional_bits, QuantizationInfo quantization_info) inline
Definition at line 51 of file DirectConvolutionLayerFixture.h.
References arm_compute::test::validation::data_type, arm_compute::FLOOR, arm_compute::test::validation::info(), arm_compute::is_data_type_quantized_asymmetric(), arm_compute::test::validation::output_shape, arm_compute::S32, and Dimensions< T >::z().
     {
         _fractional_bits   = fractional_bits;
         _quantization_info = quantization_info;
         _data_type         = data_type;
         const TensorShape   weights_shape(kernel_size, kernel_size, input_shape.z(), num_kernels);
         const TensorShape   bias_shape(num_kernels);
         const PadStrideInfo info(stride_x, stride_y, pad_x, pad_y, DimensionRoundingType::FLOOR);
         const TensorShape   output_shape   = get_output_shape(input_shape, weights_shape, info);
         const DataType      bias_data_type = is_data_type_quantized_asymmetric(data_type) ? DataType::S32 : data_type;
         _target    = compute_target(input_shape, weights_shape, bias_shape, output_shape, info, data_type, bias_data_type, fractional_bits, quantization_info);
         _reference = compute_reference(input_shape, weights_shape, bias_shape, output_shape, info, data_type, bias_data_type, fractional_bits, quantization_info);
     }
void setup (TensorShape input_shape, TensorShape weights_shape, TensorShape bias_shape, TensorShape output_shape, PadStrideInfo info, DataType data_type, int fractional_bits, QuantizationInfo quantization_info) inline
Definition at line 69 of file DirectConvolutionLayerFixture.h.
References arm_compute::test::validation::ARM_COMPUTE_EXPECT(), arm_compute::test::validation::conv, arm_compute::test::validation::data_type, arm_compute::test::validation::dst, arm_compute::test::framework::ERRORS, arm_compute::F16, arm_compute::F32, arm_compute::test::validation::info(), arm_compute::is_data_type_quantized_asymmetric(), arm_compute::test::library, arm_compute::test::validation::output_shape, arm_compute::QASYMM8, arm_compute::S32, arm_compute::scaled_dimensions(), TensorShape::set(), arm_compute::test::validation::src, arm_compute::U, Dimensions< T >::x(), and Dimensions< T >::y().
     {
         _fractional_bits   = fractional_bits;
         _quantization_info = quantization_info;
         _data_type         = data_type;
         const DataType bias_data_type = is_data_type_quantized_asymmetric(data_type) ? DataType::S32 : data_type;
         _target    = compute_target(input_shape, weights_shape, bias_shape, output_shape, info, data_type, bias_data_type, fractional_bits, quantization_info);
         _reference = compute_reference(input_shape, weights_shape, bias_shape, output_shape, info, data_type, bias_data_type, fractional_bits, quantization_info);
     }
The documentation for this class was generated from the following file:
tests/validation/fixtures/DirectConvolutionLayerFixture.h