Compute Library: ImageFileDataset Class Reference
ImageFileDataset Class Reference
#include <ImageFileDatasets.h>
Data Structures
struct iterator
Public Member Functions
iterator begin () const
int size () const
void add_image_file (std::string name)
Detailed Description
Definition at line 37 of file ImageFileDatasets.h.
Member Function Documentation
void add_image_file (std::string name) inline
Definition at line 80 of file ImageFileDatasets.h.
Referenced by LargeImageFiles::LargeImageFiles(), and SmallImageFiles::SmallImageFiles().
     {
         _names.emplace_back(std::move(name));
     }
iterator begin () const inline
Definition at line 70 of file ImageFileDatasets.h.
References ImageFileDataset::iterator::iterator().
     {
         return iterator(_names.begin());
     }
int size () const inline
Definition at line 75 of file ImageFileDatasets.h.
     {
         return _names.size();
     }
The documentation for this class was generated from the following file:
tests/datasets/ImageFileDatasets.h