Compute Library: NamedDataset Class Reference
NamedDataset Class Reference
Abstract implementation of a named dataset.
#include <Dataset.h>
Public Member Functions
NamedDataset (NamedDataset &&)=default
Allow instances of this class to be move constructed.
std::string name () const
Return name of the dataset.
Public Member Functions inherited from Dataset
Dataset (Dataset &&)=default
Allow instances of this class to be move constructed.
Detailed Description
Abstract implementation of a named dataset.
The name should describe the values of the dataset.
Definition at line 56 of file Dataset.h.
Constructor & Destructor Documentation
NamedDataset()
NamedDataset (NamedDataset &&) default
Allow instances of this class to be move constructed.
Member Function Documentation
name()
std::string name () const inline
Return name of the dataset.
Returns
Description of the values.
Definition at line 79 of file Dataset.h.
     {
         return _name;
     }
Referenced by InitializerListDataset< T >::begin(), RangeDataset< T >::begin(), SingletonDataset< T >::begin(), ContainerDataset< T >::begin(), ContainerDataset< T >::ContainerDataset(), InitializerListDataset< T >::InitializerListDataset(), InitializerListDataset< T >::iterator::iterator(), RangeDataset< T >::iterator::iterator(), ContainerDataset< T >::iterator::iterator(), and RangeDataset< T >::RangeDataset().
The documentation for this class was generated from the following file:
tests/framework/datasets/Dataset.h