Compute Library: Option Class Reference
Option Class Reference abstract
Abstract base class for a command line option.
#include <Option.h>
Public Member Functions
Option (std::string name)
Constructor.
Option (std::string name, bool is_required, bool is_set)
Constructor.
virtual ~Option ()=default
Default destructor.
virtual bool parse (std::string value)=0
Parses the given string.
virtual std::string help () const =0
Help message for the option.
std::string name () const
Name of the option.
void set_required (bool is_required)
Set whether the option is required.
void set_help (std::string help)
Set the help message for the option.
bool is_required () const
Is the option required?
bool is_set () const
Has a value been assigned to the option?
Detailed Description
Abstract base class for a command line option.
Definition at line 34 of file Option.h.
Constructor & Destructor Documentation
Option() [1/2]
Option (std::string name) inline
Constructor.
Parameters
[in] name Name of the option.
Definition at line 105 of file Option.h.
     : _name{ std::move(name) }
 {
 }
Option() [2/2]
Option (std::string name, bool is_required, bool is_set) inline
Constructor.
Parameters
[in] name Name of the option.
[in] is_required Is the option required?
[in] is_set Has a value been assigned to the option?
Definition at line 110 of file Option.h.
     : _name{ std::move(name) }, _is_required{ is_required }, _is_set{ is_set }
 {
 }
~Option()
virtual ~Option () virtual default
Default destructor.
Member Function Documentation
help()
virtual std::string help () const pure virtual
Help message for the option.
Returns
String representing the help message for the specific subclass.
Implemented in SimpleOption< T >, SimpleOption< LogFormat >, SimpleOption< std::string >, SimpleOption< int >, SimpleOption< arm_compute::CLTunerMode >, SimpleOption< arm_compute::graph::Target >, SimpleOption< unsigned int >, SimpleOption< LogLevel >, SimpleOption< arm_compute::DataLayout >, SimpleOption< arm_compute::DataType >, SimpleOption< bool >, EnumListOption< T >, EnumListOption< InstrumentsDescription >, EnumOption< T >, EnumOption< LogFormat >, EnumOption< arm_compute::graph::Target >, EnumOption< LogLevel >, EnumOption< arm_compute::DataLayout >, EnumOption< arm_compute::DataType >, ListOption< T >, and ToggleOption.
is_required()
bool is_required () const inline
Is the option required?
Returns
True if the option is required.
Definition at line 130 of file Option.h.
 {
     return _is_required;
 }
is_set()
bool is_set () const inline
Has a value been assigned to the option?
Returns
True if a value has been set.
Definition at line 135 of file Option.h.
 {
     return _is_set;
 }
Referenced by arm_compute::utils::consume_common_graph_parameters(), CommonOptions::create_printers(), and main().
name()
std::string name () const inline
Name of the option.
Returns
Name of the option.
Definition at line 115 of file Option.h.
 {
     return _name;
 }
Referenced by ToggleOption::help(), ListOption< T >::ListOption(), and ToggleOption::ToggleOption().
parse()
virtual bool parse (std::string value) pure virtual
Parses the given string.
Parameters
[in] value String representation as passed on the command line.
Returns
True if the value could be parsed by the specific subclass.
Implemented in SimpleOption< T >, SimpleOption< LogFormat >, SimpleOption< std::string >, SimpleOption< int >, SimpleOption< arm_compute::CLTunerMode >, SimpleOption< arm_compute::graph::Target >, SimpleOption< unsigned int >, SimpleOption< LogLevel >, SimpleOption< arm_compute::DataLayout >, SimpleOption< arm_compute::DataType >, SimpleOption< bool >, EnumListOption< T >, EnumListOption< InstrumentsDescription >, EnumOption< T >, EnumOption< LogFormat >, EnumOption< arm_compute::graph::Target >, EnumOption< LogLevel >, EnumOption< arm_compute::DataLayout >, EnumOption< arm_compute::DataType >, SimpleOption< T >, SimpleOption< LogFormat >, SimpleOption< std::string >, SimpleOption< int >, SimpleOption< arm_compute::CLTunerMode >, SimpleOption< arm_compute::graph::Target >, SimpleOption< unsigned int >, SimpleOption< LogLevel >, SimpleOption< arm_compute::DataLayout >, SimpleOption< arm_compute::DataType >, SimpleOption< bool >, ListOption< T >, and ToggleOption.
set_help()
void set_help (std::string help) inline
Set the help message for the option.
Parameters
[in] help Option specific help message.
Definition at line 125 of file Option.h.
 {
     _help = std::move(help);
 }
Referenced by CommonGraphOptions::CommonGraphOptions(), CommonOptions::CommonOptions(), and main().
set_required()
void set_required (bool is_required) inline
Set whether the option is required.
Parameters
[in] is_required Pass true if the option is required.
Definition at line 120 of file Option.h.
 {
     _is_required = is_required;
 }
The documentation for this class was generated from the following file:
utils/command_line/Option.h