Compute Library: ISchedulerUser Class Reference
ISchedulerUser Class Reference abstract
Scheduler user interface.
#include <SchedulerTimer.h>
Public Member Functions
virtual ~ISchedulerUser ()=default
Default Destructor.
virtual void intercept_scheduler (std::unique_ptr< IScheduler > interceptor)=0
Intercept the scheduler used by.
virtual void restore_scheduler ()=0
Restore the original scheduler.
virtual IScheduler * scheduler ()=0
Real scheduler accessor.
Detailed Description
Scheduler user interface.
Definition at line 42 of file SchedulerTimer.h.
Constructor & Destructor Documentation
~ISchedulerUser()
virtual ~ISchedulerUser () virtual default
Default Destructor.
Member Function Documentation
intercept_scheduler()
virtual void intercept_scheduler (std::unique_ptr< IScheduler > interceptor) pure virtual
Intercept the scheduler used by.
Parameters
interceptor Intercept the scheduler used by the scheduler user.
Implemented in ContextSchedulerUser.
Referenced by SchedulerClock< output_timestamps >::test_start().
restore_scheduler()
virtual void restore_scheduler () pure virtual
Restore the original scheduler.
Implemented in ContextSchedulerUser.
Referenced by SchedulerClock< output_timestamps >::test_stop().
scheduler()
virtual IScheduler* scheduler () pure virtual
Real scheduler accessor.
Returns
The real scheduler
Implemented in ContextSchedulerUser.
Referenced by SchedulerClock< output_timestamps >::test_start().
The documentation for this class was generated from the following file:
tests/framework/instruments/SchedulerTimer.h