Compute Library: IMemoryRegion Class Reference
IMemoryRegion Class Reference abstract
Memory region interface.
#include <IMemoryRegion.h>
Public Member Functions
IMemoryRegion (size_t size)
Default constructor.
virtual ~IMemoryRegion ()=default
Virtual Destructor.
virtual std::unique_ptr< IMemoryRegion > extract_subregion (size_t offset, size_t size)=0
Extract a sub-region from the memory.
virtual void * buffer ()=0
Returns the pointer to the allocated data.
virtual void * buffer () const =0
Returns the pointer to the allocated data.
size_t size () const
Memory region size accessor.
void set_size (size_t size)
Sets size of region.
Detailed Description
Memory region interface.
Definition at line 33 of file IMemoryRegion.h.
Constructor & Destructor Documentation
IMemoryRegion()
IMemoryRegion (size_t size) inline explicit
Default constructor.
Parameters
[in] size Region size
Definition at line 40 of file IMemoryRegion.h.
         : _size(size)
     {
     }
~IMemoryRegion()
virtual ~IMemoryRegion () virtual default
Virtual Destructor.
Member Function Documentation
buffer() [1/2]
virtual void* buffer () pure virtual
Returns the pointer to the allocated data.
Returns
Pointer to the allocated data
Implemented in MemoryRegion, ICLMemoryRegion, and IGCMemoryRegion.
Referenced by TensorAllocator::data(), CLTensorAllocator::map(), TensorAllocator::set_associated_memory_group(), and CLTensorAllocator::unmap().
buffer() [2/2]
virtual void* buffer () const pure virtual
Returns the pointer to the allocated data.
Returns
Pointer to the allocated data
Implemented in MemoryRegion, ICLMemoryRegion, and IGCMemoryRegion.
extract_subregion()
virtual std::unique_ptr<IMemoryRegion> extract_subregion (size_t offset, size_t size) pure virtual
Extract a sub-region from the memory.
Warning
Ownership is maintained by the parent memory, while a wrapped raw memory region is returned by this function. Thus parent memory should not be released before this.
Parameters
[in] offset Offset to the region
[in] size Size of the region
Returns
A wrapped memory sub-region with no ownership of the underlying memory
Implemented in GCBufferMemoryRegion, MemoryRegion, and ICLMemoryRegion.
set_size()
void set_size (size_t size) inline
Sets size of region.
Warning
This should only be used in correlation with handle
Parameters
[in] size Size to set
Definition at line 83 of file IMemoryRegion.h.
     {
         _size = size;
     }
References IMemoryRegion::size().
size()
size_t size () const inline
Memory region size accessor.
Returns
Memory region size
Definition at line 73 of file IMemoryRegion.h.
     {
         return _size;
     }
Referenced by CLTensorAllocator::allocate(), ICLMemoryRegion::extract_subregion(), MemoryRegion::extract_subregion(), GCBufferMemoryRegion::extract_subregion(), GCBufferMemoryRegion::GCBufferMemoryRegion(), GCBufferMemoryRegion::map(), MemoryRegion::MemoryRegion(), and IMemoryRegion::set_size().
The documentation for this class was generated from the following file:
arm_compute/runtime/IMemoryRegion.h