Compute Library: CLSobel3x3Kernel Class Reference
CLSobel3x3Kernel Class Reference
Interface for the kernel to run a 3x3 Sobel filter on a tensor.
#include <CLSobel3x3Kernel.h>
Public Member Functions
CLSobel3x3Kernel ()
Default constructor: initialize all the pointers to nullptr and parameters to zero.
CLSobel3x3Kernel (const CLSobel3x3Kernel &)=delete
Prevent instances of this class from being copied (As this class contains pointers)
CLSobel3x3Kernel & operator= (const CLSobel3x3Kernel &)=delete
Prevent instances of this class from being copied (As this class contains pointers)
CLSobel3x3Kernel (CLSobel3x3Kernel &&)=default
Allow instances of this class to be moved.
CLSobel3x3Kernel & operator= (CLSobel3x3Kernel &&)=default
Allow instances of this class to be moved.
~CLSobel3x3Kernel ()=default
Default destructor.
void configure (const ICLTensor *input, ICLTensor *output_x, ICLTensor *output_y, bool border_undefined)
Initialise the kernel's source, destination and border.
void run (const Window &window, cl::CommandQueue &queue) override
Enqueue the OpenCL kernel to process the given window on the passed OpenCL command queue.
BorderSize border_size () const override
The size of the border for that kernel.
Public Member Functions inherited from ICLKernel
ICLKernel ()
Constructor.
cl::Kernel & kernel ()
Returns a reference to the OpenCL kernel of this object.
template<typename T >
void add_1D_array_argument (unsigned int &idx, const ICLArray< T > *array, const Strides &strides, unsigned int num_dimensions, const Window &window)
Add the passed 1D array's parameters to the object's kernel's arguments starting from the index idx.
void add_1D_tensor_argument (unsigned int &idx, const ICLTensor *tensor, const Window &window)
Add the passed 1D tensor's parameters to the object's kernel's arguments starting from the index idx.
void add_1D_tensor_argument_if (bool cond, unsigned int &idx, const ICLTensor *tensor, const Window &window)
Add the passed 1D tensor's parameters to the object's kernel's arguments starting from the index idx if the condition is true.
void add_2D_tensor_argument (unsigned int &idx, const ICLTensor *tensor, const Window &window)
Add the passed 2D tensor's parameters to the object's kernel's arguments starting from the index idx.
void add_2D_tensor_argument_if (bool cond, unsigned int &idx, const ICLTensor *tensor, const Window &window)
Add the passed 2D tensor's parameters to the object's kernel's arguments starting from the index idx if the condition is true.
void add_3D_tensor_argument (unsigned int &idx, const ICLTensor *tensor, const Window &window)
Add the passed 3D tensor's parameters to the object's kernel's arguments starting from the index idx.
void add_4D_tensor_argument (unsigned int &idx, const ICLTensor *tensor, const Window &window)
Add the passed 4D tensor's parameters to the object's kernel's arguments starting from the index idx.
template<typename T >
void add_argument (unsigned int &idx, T value)
Add the passed parameters to the object's kernel's arguments starting from the index idx.
void set_lws_hint (const cl::NDRange &lws_hint)
Set the Local-Workgroup-Size hint.
cl::NDRange lws_hint () const
Return the Local-Workgroup-Size hint.
const std::string & config_id () const
Get the configuration ID.
void set_target (GPUTarget target)
Set the targeted GPU architecture.
void set_target (cl::Device &device)
Set the targeted GPU architecture according to the CL device.
GPUTarget get_target () const
Get the targeted GPU architecture.
size_t get_max_workgroup_size ()
Get the maximum workgroup size for the device the CLKernelLibrary uses.
template<typename T , unsigned int dimension_size>
void add_array_argument (unsigned &idx, const ICLArray< T > *array, const Strides &strides, unsigned int num_dimensions, const Window &window)
Add the passed array's parameters to the object's kernel's arguments starting from the index idx.
template<unsigned int dimension_size>
void add_tensor_argument (unsigned &idx, const ICLTensor *tensor, const Window &window)
Public Member Functions inherited from IKernel
IKernel ()
Constructor.
virtual ~IKernel ()=default
Destructor.
virtual bool is_parallelisable () const
Indicates whether or not the kernel is parallelisable.
const Window & window () const
The maximum window the kernel can be executed on.
Additional Inherited Members
Static Public Member Functions inherited from ICLKernel
static constexpr unsigned int num_arguments_per_1D_array ()
Returns the number of arguments enqueued per 1D array object.
static constexpr unsigned int num_arguments_per_1D_tensor ()
Returns the number of arguments enqueued per 1D tensor object.
static constexpr unsigned int num_arguments_per_2D_tensor ()
Returns the number of arguments enqueued per 2D tensor object.
static constexpr unsigned int num_arguments_per_3D_tensor ()
Returns the number of arguments enqueued per 3D tensor object.
static constexpr unsigned int num_arguments_per_4D_tensor ()
Returns the number of arguments enqueued per 4D tensor object.
static cl::NDRange gws_from_window (const Window &window)
Get the global work size given an execution window.
Detailed Description
Interface for the kernel to run a 3x3 Sobel filter on a tensor.
Definition at line 34 of file CLSobel3x3Kernel.h.
Constructor & Destructor Documentation
CLSobel3x3Kernel() [1/3]
CLSobel3x3Kernel ()
Default constructor: initialize all the pointers to nullptr and parameters to zero.
Definition at line 40 of file CLSobel3x3Kernel.cpp.
     : _input(nullptr), _output_x(nullptr), _output_y(nullptr), _run_sobel_x(false), _run_sobel_y(false)
 {
 }
CLSobel3x3Kernel() [2/3]
CLSobel3x3Kernel (const CLSobel3x3Kernel &) delete
Prevent instances of this class from being copied (As this class contains pointers)
CLSobel3x3Kernel() [3/3]
CLSobel3x3Kernel (CLSobel3x3Kernel &&) default
Allow instances of this class to be moved.
~CLSobel3x3Kernel()
~CLSobel3x3Kernel () default
Default destructor.
Member Function Documentation
border_size()
BorderSize border_size () const override virtual
The size of the border for that kernel.
Returns
The width in number of elements of the border.
Reimplemented from IKernel.
Definition at line 45 of file CLSobel3x3Kernel.cpp.
 {
     return BorderSize(1);
 }
Referenced by CLSobel3x3Kernel::configure().
configure()
void configure (const ICLTensor * input, ICLTensor * output_x, ICLTensor * output_y, bool border_undefined)
Initialise the kernel's source, destination and border.
Note
At least one of output_x or output_y must be set.
Parameters
[in] input Source tensor. Data types supported: U8.
[out] output_x (Optional) Destination tensor for the X gradient, Data types supported: S16.
[out] output_y (Optional) Destination tensor for the Y gradient, Data types supported: S16.
[in] border_undefined True if the border mode is undefined. False if it's replicate or constant.
Definition at line 50 of file CLSobel3x3Kernel.cpp.
 {
     ARM_COMPUTE_ERROR_ON_DATA_TYPE_CHANNEL_NOT_IN(input, 1, DataType::U8);
     ARM_COMPUTE_ERROR_ON((output_x == nullptr) && (output_y == nullptr));
     _run_sobel_x = output_x != nullptr;
     _run_sobel_y = output_y != nullptr;
     if(_run_sobel_x)
     {
         ARM_COMPUTE_ERROR_ON_DATA_TYPE_CHANNEL_NOT_IN(output_x, 1, DataType::S16);
     }
     if(_run_sobel_y)
     {
         ARM_COMPUTE_ERROR_ON_DATA_TYPE_CHANNEL_NOT_IN(output_y, 1, DataType::S16);
     }
     _input    = input;
     _output_x = output_x;
     _output_y = output_y;
     // Set build options
     std::set<std::string> build_opts;
     if(_run_sobel_x)
     {
         build_opts.insert("-DGRAD_X");
     }
     if(_run_sobel_y)
     {
         build_opts.insert("-DGRAD_Y");
     }
     // Create kernel
     const std::string kernel_name = std::string("sobel3x3");
     _kernel                       = static_cast<cl::Kernel>(CLKernelLibrary::get().create_kernel(kernel_name, build_opts));
     // Configure kernel window
     constexpr unsigned int num_elems_processed_per_iteration = 8;
     constexpr unsigned int num_elems_read_per_iteration      = 16;
     constexpr unsigned int num_elems_written_per_iteration   = 8;
     constexpr unsigned int num_rows_read_per_iteration       = 3;
     Window win = calculate_max_window(*input->info(), Steps(num_elems_processed_per_iteration), border_undefined, border_size());
     AccessWindowRectangle  input_access(input->info(), -border_size().left, -border_size().top, num_elems_read_per_iteration, num_rows_read_per_iteration);
     AccessWindowHorizontal output_x_access(output_x == nullptr ? nullptr : output_x->info(), 0, num_elems_written_per_iteration);
     AccessWindowHorizontal output_y_access(output_y == nullptr ? nullptr : output_y->info(), 0, num_elems_written_per_iteration);
     update_window_and_padding(win, input_access, output_x_access, output_y_access);
     output_x_access.set_valid_region(win, input->info()->valid_region(), border_undefined, border_size());
     output_y_access.set_valid_region(win, input->info()->valid_region(), border_undefined, border_size());
     ICLKernel::configure_internal(win);
     // Set config_id for enabling LWS tuning
     _config_id = kernel_name;
     _config_id += "_";
     _config_id += lower_string(string_from_data_type(input->info()->data_type()));
     _config_id += "_";
     _config_id += support::cpp11::to_string(input->info()->dimension(0));
     _config_id += "_";
     _config_id += support::cpp11::to_string(input->info()->dimension(1));
     _config_id += "_";
     _config_id += support::cpp11::to_string(border_undefined);
 }
References ARM_COMPUTE_ERROR_ON, ARM_COMPUTE_ERROR_ON_DATA_TYPE_CHANNEL_NOT_IN, CLSobel3x3Kernel::border_size(), arm_compute::calculate_max_window(), arm_compute::create_kernel(), ITensorInfo::data_type(), ITensorInfo::dimension(), CLKernelLibrary::get(), ITensor::info(), BorderSize::left, arm_compute::lower_string(), arm_compute::S16, arm_compute::string_from_data_type(), arm_compute::support::cpp11::to_string(), BorderSize::top, arm_compute::U8, arm_compute::update_window_and_padding(), and ITensorInfo::valid_region().
operator=() [1/2]
CLSobel3x3Kernel& operator= (const CLSobel3x3Kernel &) delete
Prevent instances of this class from being copied (As this class contains pointers)
operator=() [2/2]
CLSobel3x3Kernel& operator= (CLSobel3x3Kernel &&) default
Allow instances of this class to be moved.
run()
void run (const Window & window, cl::CommandQueue & queue) override virtual
Enqueue the OpenCL kernel to process the given window on the passed OpenCL command queue.
Note
The queue is not flushed by this method, and therefore the kernel will not have been executed by the time this method returns.
Parameters
[in] window Region on which to execute the kernel. (Must be a valid region of the window returned by window()).
[in,out] queue Command queue on which to enqueue the kernel.
Implements ICLKernel.
Definition at line 120 of file CLSobel3x3Kernel.cpp.
 {
     ARM_COMPUTE_ERROR_ON_UNCONFIGURED_KERNEL(this);
     ARM_COMPUTE_ERROR_ON_INVALID_SUBWINDOW(ICLKernel::window(), window);
     Window slice = window.first_slice_window_2D();
     do
     {
         unsigned int idx = 0;
         add_2D_tensor_argument(idx, _input, slice);
         add_2D_tensor_argument_if((_run_sobel_x), idx, _output_x, slice);
         add_2D_tensor_argument_if((_run_sobel_y), idx, _output_y, slice);
         enqueue(queue, *this, slice, lws_hint());
     }
     while(window.slide_window_slice_2D(slice));
 }
References ICLKernel::add_2D_tensor_argument(), ICLKernel::add_2D_tensor_argument_if(), ARM_COMPUTE_ERROR_ON_INVALID_SUBWINDOW, ARM_COMPUTE_ERROR_ON_UNCONFIGURED_KERNEL, arm_compute::enqueue(), Window::first_slice_window_2D(), ICLKernel::lws_hint(), arm_compute::test::validation::reference::slice(), Window::slide_window_slice_2D(), and IKernel::window().
The documentation for this class was generated from the following files:
arm_compute/core/CL/kernels/CLSobel3x3Kernel.h
src/core/CL/kernels/CLSobel3x3Kernel.cpp