Compute Library: Accessor Class Reference
Accessor Class Reference
Accessor implementation for Tensor objects.
#include <Accessor.h>
Public Member Functions
Accessor (Tensor &tensor)
Create an accessor for the given tensor.
Accessor (const Accessor &)=delete
Accessor & operator= (const Accessor &)=delete
Accessor (Accessor &&)=default
Accessor & operator= (Accessor &&)=default
TensorShape shape () const override
Shape of the tensor.
size_t element_size () const override
Size of each element in the tensor in bytes.
size_t size () const override
Total size of the tensor in bytes.
Format format () const override
Image format of the tensor.
DataType data_type () const override
Data type of the tensor.
int num_channels () const override
Number of channels of the tensor.
int num_elements () const override
Number of elements of the tensor.
PaddingSize padding () const override
Available padding around the tensor.
int fixed_point_position () const override
Number of bits for the fractional part.
QuantizationInfo quantization_info () const override
Quantization info in case of asymmetric quantized type.
const void * operator() (const Coordinates &coord) const override
Read only access to the specified element.
void * operator() (const Coordinates &coord) override
Access to the specified element.
const void * data () const
void * data ()
Public Member Functions inherited from IAccessor
virtual ~IAccessor ()=default
Virtual destructor.
Detailed Description
Accessor implementation for Tensor objects.
Definition at line 35 of file Accessor.h.
Constructor & Destructor Documentation
Accessor (Tensor & tensor) inline
Create an accessor for the given tensor.
Parameters
[in,out] tensor To be accessed tensor.
Definition at line 68 of file Accessor.h.
     : _tensor{ tensor }
 {
 }
Accessor (const Accessor &) delete
Accessor (Accessor &&) default
Member Function Documentation
const void * data () const inline
Definition at line 123 of file Accessor.h.
References Tensor::buffer().
 {
     return _tensor.buffer();
 }
void * data () inline
Definition at line 128 of file Accessor.h.
References Tensor::buffer().
 {
     return _tensor.buffer();
 }
DataType data_type () const inline override virtual
Data type of the tensor.
Implements IAccessor.
Definition at line 93 of file Accessor.h.
References ITensorInfo::data_type(), and Tensor::info().
 {
     return _tensor.info()->data_type();
 }
size_t element_size () const inline override virtual
Size of each element in the tensor in bytes.
Implements IAccessor.
Definition at line 78 of file Accessor.h.
References ITensorInfo::element_size(), and Tensor::info().
 {
     return _tensor.info()->element_size();
 }
int fixed_point_position () const inline override virtual
Number of bits for the fractional part.
Implements IAccessor.
Definition at line 113 of file Accessor.h.
References ITensorInfo::fixed_point_position(), and Tensor::info().
 {
     return _tensor.info()->fixed_point_position();
 }
Format format () const inline override virtual
Image format of the tensor.
Implements IAccessor.
Definition at line 88 of file Accessor.h.
References ITensorInfo::format(), and Tensor::info().
 {
     return _tensor.info()->format();
 }
int num_channels () const inline override virtual
Number of channels of the tensor.
Implements IAccessor.
Definition at line 98 of file Accessor.h.
References Tensor::info(), and ITensorInfo::num_channels().
 {
     return _tensor.info()->num_channels();
 }
int num_elements () const inline override virtual
Number of elements of the tensor.
Implements IAccessor.
Definition at line 103 of file Accessor.h.
References Tensor::info(), ITensorInfo::tensor_shape(), and TensorShape::total_size().
 {
     return _tensor.info()->tensor_shape().total_size();
 }
const void * operator() (const Coordinates & coord) const inline override virtual
Read only access to the specified element.
Parameters
[in] coord Coordinates of the desired element.
Returns
A pointer to the desired element.
Implements IAccessor.
Definition at line 133 of file Accessor.h.
References ITensor::ptr_to_element().
 {
     return _tensor.ptr_to_element(coord);
 }
void * operator() (const Coordinates & coord) inline override virtual
Access to the specified element.
Parameters
[in] coord Coordinates of the desired element.
Returns
A pointer to the desired element.
Implements IAccessor.
Definition at line 138 of file Accessor.h.
References ITensor::ptr_to_element().
 {
     return _tensor.ptr_to_element(coord);
 }
Accessor& operator= (const Accessor &) delete
Accessor& operator= (Accessor &&) default
PaddingSize padding () const inline override virtual
Available padding around the tensor.
Implements IAccessor.
Definition at line 108 of file Accessor.h.
References Tensor::info(), and ITensorInfo::padding().
 {
     return _tensor.info()->padding();
 }
QuantizationInfo quantization_info () const inline override virtual
Quantization info in case of asymmetric quantized type.
Implements IAccessor.
Definition at line 118 of file Accessor.h.
References Tensor::info(), and ITensorInfo::quantization_info().
 {
     return _tensor.info()->quantization_info();
 }
TensorShape shape () const inline override virtual
Shape of the tensor.
Implements IAccessor.
Definition at line 73 of file Accessor.h.
References Tensor::info(), and ITensorInfo::tensor_shape().
Referenced by LeNet5Network< TensorType, arm_compute::test::Accessor, ActivationLayerFunction, ConvolutionLayerFunction, FullyConnectedLayerFunction, PoolingLayerFunction, SoftmaxLayerFunction >::get_classifications(), MobileNetNetwork< TensorType, arm_compute::test::Accessor, ActivationLayerFunction, ConvolutionLayerFunction, DirectConvolutionLayerFunction, DepthwiseConvolutionLayerFunction, ReshapeFunction, PoolingLayerFunction >::get_classifications(), MobileNetV1Network< TensorType, arm_compute::test::Accessor, ActivationLayerFunction, BatchNormalizationLayerFunction, ConvolutionLayerFunction, DirectConvolutionLayerFunction, DepthwiseConvolutionFunction, ReshapeFunction, PoolingLayerFunction, SoftmaxLayerFunction >::get_classifications(), and AlexNetNetwork< ITensorType, TensorType, SubTensorType, arm_compute::test::Accessor, ActivationLayerFunction, ConvolutionLayerFunction, DirectConvolutionLayerFunction, FullyConnectedLayerFunction, NormalizationLayerFunction, PoolingLayerFunction, SoftmaxLayerFunction >::get_classifications().
 {
     return _tensor.info()->tensor_shape();
 }
size_t size () const inline override virtual
Total size of the tensor in bytes.
Implements IAccessor.
Definition at line 83 of file Accessor.h.
References Tensor::info(), and ITensorInfo::total_size().
 {
     return _tensor.info()->total_size();
 }
The documentation for this class was generated from the following file:
tests/NEON/Accessor.h