Compute Library: NEAccumulateWeightedKernel Class Reference
NEAccumulateWeightedKernel Class Reference
Interface for the accumulate weighted kernel.
#include <NEAccumulateKernel.h>
Public Member Functions
const char * name () const override
Name of the kernel.
NEAccumulateWeightedKernel ()
Default constructor.
void configure (const ITensor *input, float alpha, ITensor *accum)
Set the input and accumulation tensors, and the scale value.
void run (const Window &window, const ThreadInfo &info) override
Execute the kernel on the passed window.
Public Member Functions inherited from ICPPSimpleKernel
ICPPSimpleKernel ()
Constructor.
ICPPSimpleKernel (const ICPPSimpleKernel &)=delete
Prevent instances of this class from being copied (As this class contains pointers)
ICPPSimpleKernel & operator= (const ICPPSimpleKernel &)=delete
Prevent instances of this class from being copied (As this class contains pointers)
ICPPSimpleKernel (ICPPSimpleKernel &&)=default
Allow instances of this class to be moved.
ICPPSimpleKernel & operator= (ICPPSimpleKernel &&)=default
Allow instances of this class to be moved.
~ICPPSimpleKernel ()=default
Default destructor.
Public Member Functions inherited from ICPPKernel
virtual ~ICPPKernel ()=default
Default destructor.
Public Member Functions inherited from IKernel
IKernel ()
Constructor.
virtual ~IKernel ()=default
Destructor.
virtual bool is_parallelisable () const
Indicates whether or not the kernel is parallelisable.
virtual BorderSize border_size () const
The size of the border for that kernel.
const Window & window () const
The maximum window the kernel can be executed on.
Detailed Description
Interface for the accumulate weighted kernel.
Weighted accumulation is computed:
\[ accum(x,y) = (1 - \alpha)*accum(x,y) + \alpha*input(x,y) \]
Where \(0 \le \alpha \le 1 \) Conceptually, the rounding for this is defined as:
\[ output(x,y)= uint8((1 - \alpha) * float32(int32(output(x,y))) + \alpha * float32(int32(input(x,y)))) \]
Definition at line 67 of file NEAccumulateKernel.h.
Constructor & Destructor Documentation
NEAccumulateWeightedKernel()
NEAccumulateWeightedKernel ()
Default constructor.
Definition at line 281 of file NEAccumulateKernel.cpp.
     : _alpha(0.0f)
 {
 }
Member Function Documentation
configure()
void configure (const ITensor * input, float alpha, ITensor * accum)
Set the input and accumulation tensors, and the scale value.
Parameters
[in] input Source tensor. Data type supported: U8.
[in] alpha Scalar value in the range [0.0f, 1.0f]
[in,out] accum Accumulated tensor. Data type supported: U8.
Definition at line 286 of file NEAccumulateKernel.cpp.
 {
     ARM_COMPUTE_ERROR_ON_NULLPTR(input, accum);
     set_shape_if_empty(*accum->info(), input->info()->tensor_shape());
     set_format_if_unknown(*accum->info(), Format::U8);
     ARM_COMPUTE_ERROR_ON_MISMATCHING_SHAPES(input, accum);
     ARM_COMPUTE_ERROR_ON_DATA_TYPE_CHANNEL_NOT_IN(input, 1, DataType::U8);
     ARM_COMPUTE_ERROR_ON_DATA_TYPE_CHANNEL_NOT_IN(accum, 1, DataType::U8);
     ARM_COMPUTE_ERROR_ON(alpha < 0.0 || alpha > 1.0);
     _alpha = alpha;
     constexpr unsigned int num_elems_processed_per_iteration = 16;
     INESimpleKernel::configure(input, accum, num_elems_processed_per_iteration);
 }
References arm_compute::test::validation::alpha, ARM_COMPUTE_ERROR_ON, ARM_COMPUTE_ERROR_ON_DATA_TYPE_CHANNEL_NOT_IN, ARM_COMPUTE_ERROR_ON_MISMATCHING_SHAPES, ARM_COMPUTE_ERROR_ON_NULLPTR, ITensor::info(), arm_compute::set_format_if_unknown(), arm_compute::set_shape_if_empty(), ITensorInfo::tensor_shape(), and arm_compute::U8.
name()
const char* name () const inline override virtual
Name of the kernel.
Returns
Kernel name
Implements ICPPKernel.
Definition at line 70 of file NEAccumulateKernel.h.
     {
         return "NEAccumulateWeightedKernel";
     }
run()
void run (const Window & window, const ThreadInfo & info) override virtual
Execute the kernel on the passed window.
Warning
If is_parallelisable() returns false then the passed window must be equal to window()
Note
The window has to be a region within the window returned by the window() method
The width of the window has to be a multiple of num_elems_processed_per_iteration().
Parameters
[in] window Region on which to execute the kernel. (Must be a region of the window returned by window())
[in] info Info about executing thread and CPU.
Implements ICPPKernel.
Definition at line 305 of file NEAccumulateKernel.cpp.
 {
     ARM_COMPUTE_UNUSED(info);
     ARM_COMPUTE_ERROR_ON_UNCONFIGURED_KERNEL(this);
     ARM_COMPUTE_ERROR_ON_INVALID_SUBWINDOW(INESimpleKernel::window(), window);
     Iterator input(_input, window);
     Iterator accum(_output, window);
     const float32x4_t scale_val  = vdupq_n_f32(1.f - _alpha);
     const float32x4_t scale_val2 = vdupq_n_f32(_alpha);
     execute_window_loop(window, [&](const Coordinates & id)
     {
         acc_we_v16_u8(input.ptr(), accum.ptr(), scale_val, scale_val2);
     },
     input, accum);
 }
References ARM_COMPUTE_ERROR_ON_INVALID_SUBWINDOW, ARM_COMPUTE_ERROR_ON_UNCONFIGURED_KERNEL, ARM_COMPUTE_UNUSED, arm_compute::execute_window_loop(), arm_compute::test::validation::info, Iterator::ptr(), and IKernel::window().
The documentation for this class was generated from the following files:
arm_compute/core/NEON/kernels/NEAccumulateKernel.h
src/core/NEON/kernels/NEAccumulateKernel.cpp