Compute Library: NEWinogradLayerTransformWeightsKernel< T, OutputTileRows, OutputTileCols, KernelRows, KernelCols > Class Template Reference
NEWinogradLayerTransformWeightsKernel< T, OutputTileRows, OutputTileCols, KernelRows, KernelCols > Class Template Reference final
NEON kernel to perform Winograd weights transform.
#include <NEWinogradConvolutionLayerKernel.h>
Public Member Functions
NEWinogradLayerTransformWeightsKernel (const NEWinogradLayerTransformWeightsKernel &)=delete
Prevent instances of this class from being copied (As this class contains pointers)
NEWinogradLayerTransformWeightsKernel & operator= (const NEWinogradLayerTransformWeightsKernel &)=delete
Prevent instances of this class from being copied (As this class contains pointers)
NEWinogradLayerTransformWeightsKernel (NEWinogradLayerTransformWeightsKernel &&)=default
Allow instances of this class to be moved.
NEWinogradLayerTransformWeightsKernel & operator= (NEWinogradLayerTransformWeightsKernel &&)=default
Allow instances of this class to be moved.
~NEWinogradLayerTransformWeightsKernel ()=default
Default destructor.
NEWinogradLayerTransformWeightsKernel ()
Default constructor.
const char * name () const override
Name of the kernel.
unsigned int get_weight_storage_size (int num_output_channels, int num_input_channels) const override
Determine how much memory (in units of T) to allocate for the transformed weights.
int get_matrix_stride (const KernelShape &kernel_shape) const override
Gets the stride between matrices in the input worspace.
void run (const Window &window, const ThreadInfo &info) override
Execute the kernel on the passed window.
bool is_parallelisable () const override
Indicates whether or not the kernel is parallelisable.
Public Member Functions inherited from INEWinogradLayerTransformWeightsKernel< T >
INEWinogradLayerTransformWeightsKernel (const INEWinogradLayerTransformWeightsKernel &)=default
Prevent instances of this class from being copied (As this class contains pointers)
INEWinogradLayerTransformWeightsKernel & operator= (const INEWinogradLayerTransformWeightsKernel &)=default
Prevent instances of this class from being copied (As this class contains pointers)
INEWinogradLayerTransformWeightsKernel (INEWinogradLayerTransformWeightsKernel &&)=default
Allow instances of this class to be moved.
INEWinogradLayerTransformWeightsKernel & operator= (INEWinogradLayerTransformWeightsKernel &&)=default
Allow instances of this class to be moved.
INEWinogradLayerTransformWeightsKernel ()
virtual ~INEWinogradLayerTransformWeightsKernel ()
virtual void configure (const ITensor *weights_hwio, ITensor *output, const int matrix_stride, const int num_output_channels, const int num_input_channels)=0
Configure the weights transform kernel.
Public Member Functions inherited from ICPPKernel
virtual ~ICPPKernel ()=default
Default destructor.
Public Member Functions inherited from IKernel
IKernel ()
Constructor.
virtual ~IKernel ()=default
Destructor.
virtual BorderSize border_size () const
The size of the border for that kernel.
const Window & window () const
The maximum window the kernel can be executed on.
Static Public Member Functions
static Status validate (const ITensorInfo *input, const ITensorInfo *output, const WinogradInfo &winograd_info)
Static function to check if given info will lead to a valid configuration of NEWinogradLayerTransformWeightsKernel.
Static Public Member Functions inherited from INEWinogradLayerTransformWeightsKernel< T >
static Status validate (const ITensorInfo *input, const ITensorInfo *weights)
Static function to check if given info will lead to a valid configuration of NEWinogradLayerTransformWeightsKernel.
Detailed Description
template<typename T, int OutputTileRows, int OutputTileCols, int KernelRows, int KernelCols>
class arm_compute::NEWinogradLayerTransformWeightsKernel< T, OutputTileRows, OutputTileCols, KernelRows, KernelCols >
NEON kernel to perform Winograd weights transform.
Definition at line 418 of file NEWinogradConvolutionLayerKernel.h.
Constructor & Destructor Documentation
NEWinogradLayerTransformWeightsKernel() [1/3]
NEWinogradLayerTransformWeightsKernel (const NEWinogradLayerTransformWeightsKernel< T, OutputTileRows, OutputTileCols, KernelRows, KernelCols > &) delete
Prevent instances of this class from being copied (As this class contains pointers)
NEWinogradLayerTransformWeightsKernel() [2/3]
NEWinogradLayerTransformWeightsKernel (NEWinogradLayerTransformWeightsKernel< T, OutputTileRows, OutputTileCols, KernelRows, KernelCols > &&) default
Allow instances of this class to be moved.
~NEWinogradLayerTransformWeightsKernel()
~NEWinogradLayerTransformWeightsKernel () default
Default destructor.
NEWinogradLayerTransformWeightsKernel() [3/3]
NEWinogradLayerTransformWeightsKernel ()
Default constructor.
Definition at line 240 of file NEWinogradConvolutionLayerKernel.cpp.
     : _weights_hwio(nullptr), _output(nullptr), _matrix_stride(0), _num_output_channels(0), _num_input_channels(0)
 {
 }
Member Function Documentation
get_matrix_stride()
int get_matrix_stride (const KernelShape & kernel_shape) const override virtual
Gets the stride between matrices in the input worspace.
Parameters
[in] kernel_shape The shape of the weights tensor.
Returns
Stride expressed in bytes.
Implements INEWinogradLayerTransformWeightsKernel< T >.
Definition at line 247 of file NEWinogradConvolutionLayerKernel.cpp.
 {
     return WinogradConv::get_kernel_matrix_stride(kernel_shape);
 }
get_weight_storage_size()
unsigned int get_weight_storage_size (int num_output_channels, int num_input_channels) const override virtual
Determine how much memory (in units of T) to allocate for the transformed weights.
Parameters
[in] num_output_channels Number of output feature maps.
[in] num_input_channels Number of input feature maps.
Returns
Storage size (in units of T) required.
Implements INEWinogradLayerTransformWeightsKernel< T >.
Definition at line 231 of file NEWinogradConvolutionLayerKernel.cpp.
 {
     const KernelShape shape(num_output_channels, KernelRows, KernelCols, num_input_channels);
     return static_cast<unsigned int>(
                // WinogradConv returns the size in bytes, we divide by `sizeof(T)` to express that in units of T
                WinogradConv::get_kernel_storage_size(shape) / sizeof(T));
 }
References arm_compute::test::validation::shape.
is_parallelisable()
bool is_parallelisable () const override virtual
Indicates whether or not the kernel is parallelisable.
If the kernel is parallelisable then the window returned by window() can be split into sub-windows which can then be run in parallel.
If the kernel is not parallelisable then only the window returned by window() can be passed to run()
Returns
True if the kernel is parallelisable
Reimplemented from IKernel.
Definition at line 290 of file NEWinogradConvolutionLayerKernel.cpp.
 {
     return false;
 }
name()
const char* name () const inline override virtual
Name of the kernel.
Returns
Kernel name
Implements ICPPKernel.
Definition at line 434 of file NEWinogradConvolutionLayerKernel.h.
     {
         return "NEWinogradLayerTransformWeightsKernel";
     }
operator=() [1/2]
NEWinogradLayerTransformWeightsKernel& operator= (const NEWinogradLayerTransformWeightsKernel< T, OutputTileRows, OutputTileCols, KernelRows, KernelCols > &) delete
Prevent instances of this class from being copied (As this class contains pointers)
operator=() [2/2]
NEWinogradLayerTransformWeightsKernel& operator= (NEWinogradLayerTransformWeightsKernel< T, OutputTileRows, OutputTileCols, KernelRows, KernelCols > &&) default
Allow instances of this class to be moved.
run()
void run (const Window & window, const ThreadInfo & info) override virtual
Execute the kernel on the passed window.
Warning
If is_parallelisable() returns false then the passed window must be equal to window()
Note
The window has to be a region within the window returned by the window() method
The width of the window has to be a multiple of num_elems_processed_per_iteration().
Parameters
[in] window Region on which to execute the kernel. (Must be a region of the window returned by window())
[in] info Info about executing thread and CPU.
Implements ICPPKernel.
Definition at line 277 of file NEWinogradConvolutionLayerKernel.cpp.
 {
     ARM_COMPUTE_UNUSED(info);
     ARM_COMPUTE_ERROR_ON_UNCONFIGURED_KERNEL(this);
     const int        matrix_row_stride = roundup(_num_output_channels, WinogradConv::N_BLOCK);
     WeightsTransform transform(reinterpret_cast<T *>(_weights_hwio->buffer()), reinterpret_cast<T *>(_output->buffer()), _matrix_stride, matrix_row_stride, _num_output_channels, _num_input_channels);
     const size_t     fst = window.x().start();
     const size_t     lst = window.x().end();
     transform.run(fst, lst);
 }
References ARM_COMPUTE_ERROR_ON_UNCONFIGURED_KERNEL, ARM_COMPUTE_UNUSED, Window::Dimension::end(), arm_compute::test::validation::info, roundup(), Window::Dimension::start(), and Window::x().
validate()
Status validate (const ITensorInfo * input, const ITensorInfo * output, const WinogradInfo & winograd_info) static
Static function to check if given info will lead to a valid configuration of NEWinogradLayerTransformWeightsKernel.
Parameters
[in] input Source tensor info. The input is a 4D tensor with dimensions [kernel_x, kernel_y, IFM, OFM] (NCHW data layout). kernel_x must be 3 and equal to kernel_y. Data types supported: F32.
[in] output Destination tensor info. The output is a 3D tensor with dimensions [OFM, IFM, 16] or [OFM, IFM, 36]. Data type supported: same as input
[in] winograd_info Contains Winograd's information described in WinogradInfo
Returns
a status
Definition at line 296 of file NEWinogradConvolutionLayerKernel.cpp.
 {
     ARM_COMPUTE_RETURN_ON_ERROR(validate_arguments_winograd_weight_trans(input, output, winograd_info));
     ARM_COMPUTE_RETURN_ON_ERROR(validate_and_configure_window_winograd_weight_trans(input->clone().get(), output->clone().get(), winograd_info).first);
     return Status{};
 }
References ARM_COMPUTE_RETURN_ON_ERROR, ICloneable< T >::clone(), and arm_compute::test::validation::winograd_info.
The documentation for this class was generated from the following files:
arm_compute/core/NEON/kernels/NEWinogradConvolutionLayerKernel.h
src/core/NEON/kernels/NEWinogradConvolutionLayerKernel.cpp