Compute Library: NEStackLayer Class Reference
NEStackLayer Class Reference
Basic function to stack tensors along an axis.
#include <NEStackLayer.h>
Public Member Functions
NEStackLayer ()
Default constructor.
void configure (const std::vector< ITensor * > &input, int axis, ITensor *output)
Initialise the kernel's inputs vector and output.
void run () override
Run the kernels contained in the function.
Public Member Functions inherited from IFunction
virtual ~IFunction ()=default
Destructor.
virtual void prepare ()
Prepare the function for executing.
Static Public Member Functions
static Status validate (const std::vector< ITensorInfo * > &input, int axis, const ITensorInfo *output)
Static function to check if given info will lead to a valid configuration of NEStackLayerKernel.
Detailed Description
Basic function to stack tensors along an axis.
This function calls the following kernel:
NEStackLayerKernel
Definition at line 44 of file NEStackLayer.h.
Constructor & Destructor Documentation
NEStackLayer()
NEStackLayer ()
Default constructor.
Definition at line 37 of file NEStackLayer.cpp.
     : _input(),
       _stack_kernels(),
       _num_inputs(0)
 {
 }
Member Function Documentation
configure()
void configure (const std::vector< ITensor * > & input, int axis, ITensor * output)
Initialise the kernel's inputs vector and output.
Note
Supported input tensor rank: up to 4
Parameters
[in] input The vectors containing all the tensors with the same shape to stack. Data types supported: U8/S8/QASYMM8/U16/S16/F16/U32/S32/F32
[in] axis The dimension to stack the tensors along. It must be smaller than the number of input dimensions. Negative values wrap around
[out] output Output tensor. Data types supported: Same as input.
Definition at line 44 of file NEStackLayer.cpp.
 {
     _num_inputs    = input.size();
     _stack_kernels = arm_compute::support::cpp14::make_unique<NEStackLayerKernel[]>(_num_inputs);
     // Wrap around negative values
     const unsigned int axis_u = wrap_around(axis, static_cast<int>(input[0]->info()->num_dimensions() + 1));
     for(unsigned int i = 0; i < _num_inputs; i++)
     {
         _stack_kernels[i].configure(input[i], axis_u, i, _num_inputs, output);
     }
 }
References arm_compute::test::validation::axis, arm_compute::test::validation::info, and arm_compute::wrap_around().
run()
void run () override virtual
Run the kernels contained in the function.
For NEON kernels:
Multi-threading is used for the kernels which are parallelisable.
By default std::thread::hardware_concurrency() threads are used.
Note
CPPScheduler::set_num_threads() can be used to manually set the number of threads
For OpenCL kernels:
All the kernels are enqueued on the queue associated with CLScheduler.
The queue is then flushed.
Note
The function will not block until the kernels are executed. It is the user's responsibility to wait.
Will call prepare() on first run if hasn't been done
Implements IFunction.
Definition at line 80 of file NEStackLayer.cpp.
 {
     for(unsigned i = 0; i < _num_inputs; i++)
     {
         NEScheduler::get().schedule(&_stack_kernels[i], Window::DimY);
     }
 }
References Window::DimY, Scheduler::get(), and IScheduler::schedule().
validate()
Status validate (const std::vector< ITensorInfo * > & input, int axis, const ITensorInfo * output) static
Static function to check if given info will lead to a valid configuration of NEStackLayerKernel.
Note
Supported input tensor rank: up to 4
Parameters
[in] input The vectors containing all the tensors info with the same shape to stack. Data types supported: U8/S8/QASYMM8/U16/S16/F16/U32/S32/F32
[in] axis The dimension to stack the tensors along. It must be smaller than the number of input dimensions. Negative values wrap around
[in] output Output tensor info. Data types supported: Same as input.
Returns
a status
Definition at line 58 of file NEStackLayer.cpp.
 {
     ARM_COMPUTE_RETURN_ERROR_ON_NULLPTR(output);
     ARM_COMPUTE_RETURN_ERROR_ON(input.empty());
     // Wrap around negative values
     const size_t       rank   = input[0]->num_dimensions();
     const unsigned int axis_u = wrap_around(axis, static_cast<int>(rank + 1));
     const unsigned int num_inputs = input.size();
     for(unsigned int i = 0; i < num_inputs; i++)
     {
         // All the tensors must have the same rank
         ARM_COMPUTE_RETURN_ERROR_ON(input[i]->num_dimensions() != rank);
         // Validate Kernel
         ARM_COMPUTE_RETURN_ON_ERROR(NEStackLayerKernel::validate(input[i], axis_u, i, num_inputs, output));
     }
     return Status{};
 }
References ARM_COMPUTE_RETURN_ERROR_ON, ARM_COMPUTE_RETURN_ERROR_ON_NULLPTR, ARM_COMPUTE_RETURN_ON_ERROR, arm_compute::test::validation::axis, NEStackLayerKernel::validate(), and arm_compute::wrap_around().
The documentation for this class was generated from the following files:
arm_compute/runtime/NEON/functions/NEStackLayer.h
src/runtime/NEON/functions/NEStackLayer.cpp