Compute Library: NEHOGDetectorKernel Class Reference
NEHOGDetectorKernel Class Reference
NEON kernel to perform HOG detector kernel using linear SVM.
#include <NEHOGDetectorKernel.h>
Public Member Functions
const char * name () const override
Name of the kernel.
NEHOGDetectorKernel ()
Default constructor.
NEHOGDetectorKernel (const NEHOGDetectorKernel &)=delete
Prevent instances of this class from being copied (As this class contains pointers)
NEHOGDetectorKernel & operator= (const NEHOGDetectorKernel &)=delete
Prevent instances of this class from being copied (As this class contains pointers)
NEHOGDetectorKernel (NEHOGDetectorKernel &&)=default
Allow instances of this class to be moved.
NEHOGDetectorKernel & operator= (NEHOGDetectorKernel &&)=default
Allow instances of this class to be moved.
~NEHOGDetectorKernel ()=default
Default destructor.
void configure (const ITensor *input, const IHOG *hog, IDetectionWindowArray *detection_windows, const Size2D &detection_window_stride, float threshold=0.0f, uint16_t idx_class=0)
Initialise the kernel's input, HOG data-object, detection window, the stride of the detection window, the threshold and index of the object to detect.
void run (const Window &window, const ThreadInfo &info) override
Execute the kernel on the passed window.
Public Member Functions inherited from ICPPKernel
virtual ~ICPPKernel ()=default
Default destructor.
Public Member Functions inherited from IKernel
IKernel ()
Constructor.
virtual ~IKernel ()=default
Destructor.
virtual bool is_parallelisable () const
Indicates whether or not the kernel is parallelisable.
virtual BorderSize border_size () const
The size of the border for that kernel.
const Window & window () const
The maximum window the kernel can be executed on.
Detailed Description
NEON kernel to perform HOG detector kernel using linear SVM.
Definition at line 37 of file NEHOGDetectorKernel.h.
Constructor & Destructor Documentation
NEHOGDetectorKernel() [1/3]
NEHOGDetectorKernel ()
Default constructor.
Definition at line 36 of file NEHOGDetectorKernel.cpp.
     : _input(nullptr), _detection_windows(), _hog_descriptor(nullptr), _bias(0.0f), _threshold(0.0f), _idx_class(0), _num_bins_per_descriptor_x(0), _num_blocks_per_descriptor_y(0), _block_stride_width(0),
       _block_stride_height(0), _detection_window_width(0), _detection_window_height(0), _max_num_detection_windows(0), _mutex()
 {
 }
NEHOGDetectorKernel() [2/3]
NEHOGDetectorKernel (const NEHOGDetectorKernel &) delete
Prevent instances of this class from being copied (As this class contains pointers)
NEHOGDetectorKernel() [3/3]
NEHOGDetectorKernel (NEHOGDetectorKernel &&) default
Allow instances of this class to be moved.
~NEHOGDetectorKernel()
~NEHOGDetectorKernel () default
Default destructor.
Member Function Documentation
configure()
void configure (const ITensor * input, const IHOG * hog, IDetectionWindowArray * detection_windows, const Size2D & detection_window_stride, float threshold = 0.0f, uint16_t idx_class = 0)
Initialise the kernel's input, HOG data-object, detection window, the stride of the detection window, the threshold and index of the object to detect.
Parameters
[in] input Input tensor which stores the HOG descriptor obtained with NEHOGOrientationBinningKernel. Data type supported: F32. Number of channels supported: equal to the number of histogram bins per block
[in] hog HOG data object used by NEHOGOrientationBinningKernel and NEHOGBlockNormalizationKernel
[out] detection_windows Array of DetectionWindow. This array stores all the detected objects
[in] detection_window_stride Distance in pixels between 2 consecutive detection windows in x and y directions. It must be multiple of the hog->info()->block_stride()
[in] threshold (Optional) Threshold for the distance between features and SVM classifying plane
[in] idx_class (Optional) Index of the class used for evaluating which class the detection window belongs to
Definition at line 42 of file NEHOGDetectorKernel.cpp.
 {
     ARM_COMPUTE_ERROR_ON_DATA_TYPE_NOT_IN(input, DataType::F32);
     ARM_COMPUTE_ERROR_ON(hog == nullptr);
     ARM_COMPUTE_ERROR_ON(detection_windows == nullptr);
     ARM_COMPUTE_ERROR_ON((detection_window_stride.width % hog->info()->block_stride().width) != 0);
     ARM_COMPUTE_ERROR_ON((detection_window_stride.height % hog->info()->block_stride().height) != 0);
     const Size2D &detection_window_size = hog->info()->detection_window_size();
     const Size2D &block_size            = hog->info()->block_size();
     const Size2D &block_stride          = hog->info()->block_stride();
     _input                       = input;
     _detection_windows           = detection_windows;
     _threshold                   = threshold;
     _idx_class                   = idx_class;
     _hog_descriptor              = hog->descriptor();
     _bias                        = _hog_descriptor[hog->info()->descriptor_size() - 1];
     _num_bins_per_descriptor_x   = ((detection_window_size.width - block_size.width) / block_stride.width + 1) * input->info()->num_channels();
     _num_blocks_per_descriptor_y = (detection_window_size.height - block_size.height) / block_stride.height + 1;
     _block_stride_width          = block_stride.width;
     _block_stride_height         = block_stride.height;
     _detection_window_width      = detection_window_size.width;
     _detection_window_height     = detection_window_size.height;
     _max_num_detection_windows   = detection_windows->max_num_values();
     ARM_COMPUTE_ERROR_ON((_num_bins_per_descriptor_x * _num_blocks_per_descriptor_y + 1) != hog->info()->descriptor_size());
     // Get the number of blocks along the x and y directions of the input tensor
     const ValidRegion &valid_region = input->info()->valid_region();
     const size_t       num_blocks_x = valid_region.shape[0];
     const size_t       num_blocks_y = valid_region.shape[1];
     // Get the number of blocks along the x and y directions of the detection window
     const size_t num_blocks_per_detection_window_x = detection_window_size.width / block_stride.width;
     const size_t num_blocks_per_detection_window_y = detection_window_size.height / block_stride.height;
     const size_t window_step_x = detection_window_stride.width / block_stride.width;
     const size_t window_step_y = detection_window_stride.height / block_stride.height;
     // Configure kernel window
     Window win;
     win.set(Window::DimX, Window::Dimension(0, floor_to_multiple(num_blocks_x - num_blocks_per_detection_window_x, window_step_x) + window_step_x, window_step_x));
     win.set(Window::DimY, Window::Dimension(0, floor_to_multiple(num_blocks_y - num_blocks_per_detection_window_y, window_step_y) + window_step_y, window_step_y));
     constexpr unsigned int num_elems_read_per_iteration = 1;
     const unsigned int     num_rows_read_per_iteration  = _num_blocks_per_descriptor_y;
     update_window_and_padding(win, AccessWindowRectangle(input->info(), 0, 0, num_elems_read_per_iteration, num_rows_read_per_iteration));
     INEKernel::configure(win);
 }
References ARM_COMPUTE_ERROR_ON, ARM_COMPUTE_ERROR_ON_DATA_TYPE_NOT_IN, HOGInfo::block_size(), HOGInfo::block_stride(), IHOG::descriptor(), HOGInfo::descriptor_size(), HOGInfo::detection_window_size(), Window::DimX, Window::DimY, arm_compute::F32, arm_compute::floor_to_multiple(), Size2D::height, IHOG::info(), ITensor::info(), IArray< T >::max_num_values(), ITensorInfo::num_channels(), Window::set(), ValidRegion::shape, arm_compute::test::validation::reference::threshold(), arm_compute::update_window_and_padding(), arm_compute::test::validation::valid_region, ITensorInfo::valid_region(), and Size2D::width.
name()
const char* name () const inline override virtual
Name of the kernel.
Returns
Kernel name
Implements ICPPKernel.
Definition at line 40 of file NEHOGDetectorKernel.h.
     {
         return "NEHOGDetectorKernel";
     }
operator=() [1/2]
NEHOGDetectorKernel& operator= (const NEHOGDetectorKernel &) delete
Prevent instances of this class from being copied (As this class contains pointers)
operator=() [2/2]
NEHOGDetectorKernel& operator= (NEHOGDetectorKernel &&) default
Allow instances of this class to be moved.
run()
void run (const Window & window, const ThreadInfo & info) override virtual
Execute the kernel on the passed window.
Warning
If is_parallelisable() returns false then the passed window must be equal to window()
Note
The window has to be a region within the window returned by the window() method
The width of the window has to be a multiple of num_elems_processed_per_iteration().
Parameters
[in] window Region on which to execute the kernel. (Must be a region of the window returned by window())
[in] info Info about executing thread and CPU.
Implements ICPPKernel.
Definition at line 95 of file NEHOGDetectorKernel.cpp.
 {
     ARM_COMPUTE_UNUSED(info);
     ARM_COMPUTE_ERROR_ON_UNCONFIGURED_KERNEL(this);
     ARM_COMPUTE_ERROR_ON_INVALID_SUBWINDOW(IKernel::window(), window);
     ARM_COMPUTE_ERROR_ON(_hog_descriptor == nullptr);
     const size_t in_step_y = _input->info()->strides_in_bytes()[Window::DimY] / data_size_from_type(_input->info()->data_type());
     Iterator in(_input, window);
     execute_window_loop(window, [&](const Coordinates & id)
     {
         const auto *in_row_ptr = reinterpret_cast<const float *>(in.ptr());
         // Init score_f32 with 0
         float32x4_t score_f32 = vdupq_n_f32(0.0f);
         // Init score with bias
         float score = _bias;
         // Compute Linear SVM
         for(size_t yb = 0; yb < _num_blocks_per_descriptor_y; ++yb, in_row_ptr += in_step_y)
         {
             int32_t xb = 0;
             const int32_t offset_y = yb * _num_bins_per_descriptor_x;
             for(; xb < static_cast<int32_t>(_num_bins_per_descriptor_x) - 16; xb += 16)
             {
                 // Load descriptor values
                 const float32x4x4_t a_f32 =
                 {
                     {
                         vld1q_f32(&in_row_ptr[xb + 0]),
                         vld1q_f32(&in_row_ptr[xb + 4]),
                         vld1q_f32(&in_row_ptr[xb + 8]),
                         vld1q_f32(&in_row_ptr[xb + 12])
                     }
                 };
                 // Load detector values
                 const float32x4x4_t b_f32 =
                 {
                     {
                         vld1q_f32(&_hog_descriptor[xb + 0 + offset_y]),
                         vld1q_f32(&_hog_descriptor[xb + 4 + offset_y]),
                         vld1q_f32(&_hog_descriptor[xb + 8 + offset_y]),
                         vld1q_f32(&_hog_descriptor[xb + 12 + offset_y])
                     }
                 };
                 // Multiply accumulate
                 score_f32 = vmlaq_f32(score_f32, a_f32.val[0], b_f32.val[0]);
                 score_f32 = vmlaq_f32(score_f32, a_f32.val[1], b_f32.val[1]);
                 score_f32 = vmlaq_f32(score_f32, a_f32.val[2], b_f32.val[2]);
                 score_f32 = vmlaq_f32(score_f32, a_f32.val[3], b_f32.val[3]);
             }
             for(; xb < static_cast<int32_t>(_num_bins_per_descriptor_x); ++xb)
             {
                 const float a = in_row_ptr[xb];
                 const float b = _hog_descriptor[xb + offset_y];
                 score += a * b;
             }
         }
         score += vgetq_lane_f32(score_f32, 0);
         score += vgetq_lane_f32(score_f32, 1);
         score += vgetq_lane_f32(score_f32, 2);
         score += vgetq_lane_f32(score_f32, 3);
         if(score > _threshold)
         {
             if(_detection_windows->num_values() < _max_num_detection_windows)
             {
                 DetectionWindow win;
                 win.x         = (id.x() * _block_stride_width);
                 win.y         = (id.y() * _block_stride_height);
                 win.width     = _detection_window_width;
                 win.height    = _detection_window_height;
                 win.idx_class = _idx_class;
                 win.score     = score;
                 std::unique_lock<arm_compute::Mutex> lock(_mutex);
                 _detection_windows->push_back(win);
                 lock.unlock();
             }
         }
     },
     in);
 }
References ARM_COMPUTE_ERROR_ON, ARM_COMPUTE_ERROR_ON_INVALID_SUBWINDOW, ARM_COMPUTE_ERROR_ON_UNCONFIGURED_KERNEL, ARM_COMPUTE_UNUSED, arm_compute::test::validation::b, arm_compute::data_size_from_type(), ITensorInfo::data_type(), Window::DimY, arm_compute::execute_window_loop(), DetectionWindow::height, DetectionWindow::idx_class, ITensor::info(), arm_compute::test::validation::info, IArray< T >::num_values(), IArray< T >::push_back(), DetectionWindow::score, ITensorInfo::strides_in_bytes(), DetectionWindow::width, IKernel::window(), DetectionWindow::x, and DetectionWindow::y.
The documentation for this class was generated from the following files:
arm_compute/core/NEON/kernels/NEHOGDetectorKernel.h
src/core/NEON/kernels/NEHOGDetectorKernel.cpp