Compute Library: HOGInfo Class Reference
HOGInfo Class Reference
Store the HOG's metadata.
#include <HOGInfo.h>
Public Member Functions
HOGInfo ()
Default constructor.
virtual ~HOGInfo ()=default
Default destructor.
HOGInfo (const HOGInfo &)=default
Allow instances of this class to be copy constructed.
HOGInfo & operator= (const HOGInfo &)=default
Allow instances of this class to be copied.
HOGInfo (HOGInfo &&)=default
Allow instances of this class to be move constructed.
HOGInfo & operator= (HOGInfo &&)=default
Allow instances of this class to be moved.
HOGInfo (const Size2D &cell_size, const Size2D &block_size, const Size2D &detection_window_size, const Size2D &block_stride, size_t num_bins, HOGNormType normalization_type=HOGNormType::L2HYS_NORM, float l2_hyst_threshold=0.2f, PhaseType phase_type=PhaseType::UNSIGNED)
Constructor.
void init (const Size2D &cell_size, const Size2D &block_size, const Size2D &detection_window_size, const Size2D &block_stride, size_t num_bins, HOGNormType normalization_type=HOGNormType::L2HYS_NORM, float l2_hyst_threshold=0.2f, PhaseType phase_type=PhaseType::UNSIGNED)
Initialize the metadata structure with the given parameters.
const Size2D & cell_size () const
The cell size in pixels.
const Size2D & block_size () const
The block size in pixels.
const Size2D & detection_window_size () const
The detection window size in pixels.
const Size2D & block_stride () const
The block stride in pixels.
size_t num_bins () const
The number of histogram bins for each cell.
HOGNormType normalization_type () const
The normalization type.
float l2_hyst_threshold () const
Threshold used for L2HYS_NORM normalization type.
PhaseType phase_type () const
The type of PhaseType.
size_t descriptor_size () const
The size of HOG descriptor.
Size2D num_cells_per_block () const
Calculates the number of cells for each block.
Size2D num_cells_per_block_stride () const
Calculates the number of cells per block stride.
Size2D num_block_positions_per_image (const Size2D &image_size) const
Calculates the number of block positions for the given image size.
Detailed Description
Store the HOG's metadata.
Definition at line 35 of file HOGInfo.h.
Constructor & Destructor Documentation
HOGInfo() [1/4]
HOGInfo ()
Default constructor.
Definition at line 31 of file HOGInfo.cpp.
     : _cell_size(), _block_size(), _detection_window_size(), _block_stride(), _num_bins(0), _normalization_type(HOGNormType::L2HYS_NORM), _l2_hyst_threshold(0.0f), _phase_type(PhaseType::UNSIGNED),
       _descriptor_size(0)
 {
 }
References arm_compute::L2HYS_NORM, and arm_compute::UNSIGNED.
~HOGInfo()
virtual ~HOGInfo () virtual default
Default destructor.
HOGInfo() [2/4]
HOGInfo (const HOGInfo &) default
Allow instances of this class to be copy constructed.
HOGInfo() [3/4]
HOGInfo (HOGInfo &&) default
Allow instances of this class to be move constructed.
HOGInfo() [4/4]
HOGInfo (const Size2D & cell_size, const Size2D & block_size, const Size2D & detection_window_size, const Size2D & block_stride, size_t num_bins, HOGNormType normalization_type = HOGNormType::L2HYS_NORM, float l2_hyst_threshold = 0.2f, PhaseType phase_type = PhaseType::UNSIGNED)
Constructor.
Parameters
[in] cell_size Cell size in pixels
[in] block_size Block size in pixels. Must be a multiple of cell_size.
[in] detection_window_size Detection window size in pixels. Must be a multiple of block_size and block_stride.
[in] block_stride Distance in pixels between 2 consecutive blocks along the x and y direction. Must be a multiple of cell size
[in] num_bins Number of histogram bins for each cell
[in] normalization_type (Optional) Normalization type to use for each block
[in] l2_hyst_threshold (Optional) Threshold used for L2HYS_NORM normalization method
[in] phase_type (Optional) Type of PhaseType
Definition at line 37 of file HOGInfo.cpp.
     : HOGInfo()
 {
     init(cell_size, block_size, detection_window_size, block_stride, num_bins, normalization_type, l2_hyst_threshold, phase_type);
 }
References HOGInfo::block_size(), HOGInfo::block_stride(), HOGInfo::cell_size(), HOGInfo::detection_window_size(), HOGInfo::init(), HOGInfo::l2_hyst_threshold(), HOGInfo::normalization_type(), HOGInfo::num_bins(), and HOGInfo::phase_type().
Member Function Documentation
block_size()
const Size2D & block_size () const
The block size in pixels.
Returns
The block size in pixels
Definition at line 96 of file HOGInfo.cpp.
 {
     return _block_size;
 }
Referenced by NEHOGDetectorKernel::configure(), CLHOGDetectorKernel::configure(), CLHOGMultiDetection::configure(), NEHOGMultiDetection::configure(), CLHOGBlockNormalizationKernel::configure(), NEHOGBlockNormalizationKernel::configure(), arm_compute::test::validation::reference::hog_block_normalization(), HOGInfo::HOGInfo(), HOGInfo::init(), and arm_compute::operator<<().
block_stride()
const Size2D & block_stride () const
The block stride in pixels.
The block stride is the distance between 2 consecutive blocks
Returns
The block stride in pixels
Definition at line 106 of file HOGInfo.cpp.
 {
     return _block_stride;
 }
Referenced by NEHOGDetectorKernel::configure(), CLHOGDetectorKernel::configure(), CLHOGMultiDetection::configure(), NEHOGMultiDetection::configure(), CLHOGBlockNormalizationKernel::configure(), NEHOGBlockNormalizationKernel::configure(), arm_compute::test::validation::reference::hog_block_normalization(), arm_compute::test::validation::reference::hog_detector(), HOGInfo::HOGInfo(), HOGInfo::init(), and arm_compute::operator<<().
cell_size()
const Size2D & cell_size () const
The cell size in pixels.
Returns
The cell size in pixels
Definition at line 91 of file HOGInfo.cpp.
 {
     return _cell_size;
 }
Referenced by CLHOGOrientationBinningKernel::configure(), NEHOGDescriptor::configure(), CLHOGDescriptor::configure(), NEHOGOrientationBinningKernel::configure(), CLHOGMultiDetection::configure(), NEHOGMultiDetection::configure(), CLHOGBlockNormalizationKernel::configure(), NEHOGBlockNormalizationKernel::configure(), arm_compute::test::validation::reference::hog_block_normalization(), arm_compute::test::validation::reference::hog_descriptor(), arm_compute::test::validation::reference::hog_orientation_binning(), HOGInfo::HOGInfo(), HOGInfo::init(), and arm_compute::operator<<().
descriptor_size()
size_t descriptor_size () const
The size of HOG descriptor.
Returns
The size of HOG descriptor
Definition at line 131 of file HOGInfo.cpp.
 {
     return _descriptor_size;
 }
Referenced by NEHOGDetectorKernel::configure(), CLHOGDetectorKernel::configure(), arm_compute::test::validation::reference::hog_detector(), and HOG::init().
detection_window_size()
const Size2D & detection_window_size () const
The detection window size in pixels.
Returns
The detection window size in pixels
Definition at line 101 of file HOGInfo.cpp.
 {
     return _detection_window_size;
 }
Referenced by NEHOGDetectorKernel::configure(), CLHOGDetectorKernel::configure(), arm_compute::test::validation::reference::hog_detector(), HOGInfo::HOGInfo(), HOGInfo::init(), and arm_compute::operator<<().
init()
void init (const Size2D & cell_size, const Size2D & block_size, const Size2D & detection_window_size, const Size2D & block_stride, size_t num_bins, HOGNormType normalization_type = HOGNormType::L2HYS_NORM, float l2_hyst_threshold = 0.2f, PhaseType phase_type = PhaseType::UNSIGNED)
Initialize the metadata structure with the given parameters.
Parameters
[in] cell_size Cell size in pixels
[in] block_size Block size in pixels. Must be a multiple of cell_size.
[in] detection_window_size Detection window size in pixels. Must be a multiple of block_size and block_stride.
[in] block_stride Distance in pixels between 2 consecutive blocks along the x and y direction. Must be a multiple of cell size
[in] num_bins Number of histogram bins for each cell
[in] normalization_type (Optional) Normalization type to use for each block
[in] l2_hyst_threshold (Optional) Threshold used for L2HYS_NORM normalization method
[in] phase_type (Optional) Type of PhaseType
Definition at line 44 of file HOGInfo.cpp.
 {
     ARM_COMPUTE_ERROR_ON_MSG((block_size.width % cell_size.width), "The block width must be multiple of cell width");
     ARM_COMPUTE_ERROR_ON_MSG((block_size.height % cell_size.height), "Block height must be multiple of cell height");
     ARM_COMPUTE_ERROR_ON_MSG((block_stride.width % cell_size.width), "Block stride width must be multiple of cell width");
     ARM_COMPUTE_ERROR_ON_MSG((block_stride.height % cell_size.height), "Block stride height must be multiple of cell height");
     ARM_COMPUTE_ERROR_ON_MSG(((detection_window_size.width - block_size.width) % block_stride.width), "Window width must be multiple of block width and block stride width");
     ARM_COMPUTE_ERROR_ON_MSG(((detection_window_size.height - block_size.height) % block_stride.height), "Window height must be multiple of block height and block stride height");
     _cell_size             = cell_size;
     _block_size            = block_size;
     _detection_window_size = detection_window_size;
     _block_stride          = block_stride;
     _num_bins              = num_bins;
     _normalization_type    = normalization_type;
     _l2_hyst_threshold     = l2_hyst_threshold;
     _phase_type            = phase_type;
     // Compute descriptor size. +1 takes into account of the bias
     _descriptor_size = num_cells_per_block().area() * num_block_positions_per_image(_detection_window_size).area() * _num_bins + 1;
 }
References Size2D::area(), ARM_COMPUTE_ERROR_ON_MSG, HOGInfo::block_size(), HOGInfo::block_stride(), HOGInfo::cell_size(), HOGInfo::detection_window_size(), Size2D::height, HOGInfo::l2_hyst_threshold(), HOGInfo::normalization_type(), HOGInfo::num_bins(), HOGInfo::num_block_positions_per_image(), HOGInfo::num_cells_per_block(), HOGInfo::phase_type(), and Size2D::width.
Referenced by HOGInfo::HOGInfo().
l2_hyst_threshold()
float l2_hyst_threshold () const
Threshold used for L2HYS_NORM normalization type.
Returns
Threshold used for L2HYS_NORM normalization type
Definition at line 121 of file HOGInfo.cpp.
 {
     return _l2_hyst_threshold;
 }
Referenced by CLHOGBlockNormalizationKernel::configure(), NEHOGBlockNormalizationKernel::configure(), arm_compute::error_on_invalid_multi_hog(), HOGInfo::HOGInfo(), HOGInfo::init(), and arm_compute::operator<<().
normalization_type()
HOGNormType normalization_type () const
The normalization type.
Returns
The normalization type
Definition at line 116 of file HOGInfo.cpp.
 {
     return _normalization_type;
 }
Referenced by CLHOGBlockNormalizationKernel::configure(), NEHOGBlockNormalizationKernel::configure(), arm_compute::error_on_invalid_multi_hog(), HOGInfo::HOGInfo(), HOGInfo::init(), and arm_compute::operator<<().
num_bins()
size_t num_bins () const
The number of histogram bins for each cell.
Returns
The number of histogram bins for each cell
Definition at line 111 of file HOGInfo.cpp.
 {
     return _num_bins;
 }
Referenced by CLHOGOrientationBinningKernel::configure(), NEHOGDescriptor::configure(), CLHOGDescriptor::configure(), NEHOGOrientationBinningKernel::configure(), CLHOGMultiDetection::configure(), NEHOGMultiDetection::configure(), CLHOGBlockNormalizationKernel::configure(), NEHOGBlockNormalizationKernel::configure(), arm_compute::test::validation::reference::hog_block_normalization(), arm_compute::test::validation::reference::hog_descriptor(), arm_compute::test::validation::reference::hog_detector(), arm_compute::test::validation::reference::hog_orientation_binning(), HOGInfo::HOGInfo(), HOGInfo::init(), TensorInfo::init(), TensorInfo::init_auto_padding(), and arm_compute::operator<<().
num_block_positions_per_image()
Size2D num_block_positions_per_image (const Size2D & image_size) const
Calculates the number of block positions for the given image size.
Parameters
[in] image_size The input image size data object
Returns
The Size2D data object which stores the number of block positions along the x and y directions
Definition at line 83 of file HOGInfo.cpp.
 {
     ARM_COMPUTE_ERROR_ON(_block_stride.width == 0 || _block_stride.height == 0);
     return Size2D{ ((image_size.width - _block_size.width) / _block_stride.width) + 1,
                    ((image_size.height - _block_size.height) / _block_stride.height) + 1 };
 }
References ARM_COMPUTE_ERROR_ON, Size2D::height, and Size2D::width.
Referenced by arm_compute::test::validation::reference::hog_detector(), HOGInfo::init(), TensorInfo::init(), and TensorInfo::init_auto_padding().
num_cells_per_block()
Size2D num_cells_per_block () const
Calculates the number of cells for each block.
Returns
The Size2D data object which stores the number of cells along the x and y directions
Definition at line 67 of file HOGInfo.cpp.
 {
     ARM_COMPUTE_ERROR_ON(_cell_size.width == 0 || _cell_size.height == 0);
     return Size2D{ _block_size.width / _cell_size.width,
                    _block_size.height / _cell_size.height };
 }
References ARM_COMPUTE_ERROR_ON, Size2D::height, and Size2D::width.
Referenced by arm_compute::test::validation::reference::hog_block_normalization(), arm_compute::test::validation::reference::hog_detector(), HOGInfo::init(), TensorInfo::init(), and TensorInfo::init_auto_padding().
num_cells_per_block_stride()
Size2D num_cells_per_block_stride () const
Calculates the number of cells per block stride.
Returns
The Size2D data object which stores the number of cells per block stride along the x and y directions
Definition at line 75 of file HOGInfo.cpp.
 {
     ARM_COMPUTE_ERROR_ON(_cell_size.width == 0 || _cell_size.height == 0);
     return Size2D{ _block_stride.width / _cell_size.width,
                    _block_stride.height / _cell_size.height };
 }
References ARM_COMPUTE_ERROR_ON, Size2D::height, and Size2D::width.
Referenced by arm_compute::test::validation::reference::hog_block_normalization().
operator=() [1/2]
HOGInfo& operator= (const HOGInfo &) default
Allow instances of this class to be copied.
operator=() [2/2]
HOGInfo& operator= (HOGInfo &&) default
Allow instances of this class to be moved.
phase_type()
PhaseType phase_type () const
The type of PhaseType.
Returns
The type of PhaseType
Definition at line 126 of file HOGInfo.cpp.
 {
     return _phase_type;
 }
Referenced by CLHOGOrientationBinningKernel::configure(), NEHOGDescriptor::configure(), CLHOGDescriptor::configure(), NEHOGOrientationBinningKernel::configure(), CLHOGMultiDetection::configure(), NEHOGMultiDetection::configure(), arm_compute::error_on_invalid_multi_hog(), arm_compute::test::validation::reference::hog_descriptor(), HOGInfo::HOGInfo(), HOGInfo::init(), and arm_compute::operator<<().
The documentation for this class was generated from the following files:
arm_compute/core/HOGInfo.h
src/core/HOGInfo.cpp