Compute Library: CLWinogradConvolutionLayer Class Reference
CLWinogradConvolutionLayer Class Reference
Basic function to execute Winograd-based convolution on OpenCL.
#include <CLWinogradConvolutionLayer.h>
Public Member Functions
CLWinogradConvolutionLayer (std::shared_ptr< IMemoryManager > memory_manager=nullptr)
Default constructor.
CLWinogradConvolutionLayer (const CLWinogradConvolutionLayer &)=delete
Prevent instances of this class from being copied (As this class contains pointers)
CLWinogradConvolutionLayer (CLWinogradConvolutionLayer &&)=default
Default move constructor.
CLWinogradConvolutionLayer & operator= (const CLWinogradConvolutionLayer &)=delete
Prevent instances of this class from being copied (As this class contains pointers)
CLWinogradConvolutionLayer & operator= (CLWinogradConvolutionLayer &&)=default
Default move assignment operator.
void configure (ICLTensor *input, const ICLTensor *weights, const ICLTensor *biases, ICLTensor *output, const PadStrideInfo &conv_info, const ActivationLayerInfo &act_info=ActivationLayerInfo(), bool enable_fast_math=false)
Set the input and output tensors.
void run () override
Run the kernels contained in the function.
void prepare () override
Prepare the function for executing.
Public Member Functions inherited from IFunction
virtual ~IFunction ()=default
Destructor.
Static Public Member Functions
static Status validate (const ITensorInfo *input, const ITensorInfo *weights, const ITensorInfo *biases, const ITensorInfo *output, const PadStrideInfo &conv_info, const ActivationLayerInfo &act_info=ActivationLayerInfo(), bool enable_fast_math=false)
Static function to check if given info will lead to a valid configuration of CLWinogradConvolutionLayer.
Detailed Description
Basic function to execute Winograd-based convolution on OpenCL.
This function calls the following OpenCL functions/kernels:
CLWinogradInputTransform
CLWinogradFilterTransformKernel (only once)
CLGEMM
CLWinogradOutputTransformKernel
Definition at line 47 of file CLWinogradConvolutionLayer.h.
Constructor & Destructor Documentation
CLWinogradConvolutionLayer() [1/3]
CLWinogradConvolutionLayer (std::shared_ptr< IMemoryManager > memory_manager = nullptr)
Default constructor.
Definition at line 86 of file CLWinogradConvolutionLayer.cpp.
     : _memory_group(memory_manager), _batched_mm(memory_manager), _input_transform(), _filter_transform(), _output_transform(), _input0(), _input1(), _batched_mm_output(), _original_weights(nullptr),
       _is_prepared(false)
 {
 }
CLWinogradConvolutionLayer() [2/3]
CLWinogradConvolutionLayer (const CLWinogradConvolutionLayer &) delete
Prevent instances of this class from being copied (As this class contains pointers)
CLWinogradConvolutionLayer() [3/3]
CLWinogradConvolutionLayer (CLWinogradConvolutionLayer &&) default
Default move constructor.
Member Function Documentation
configure()
void configure (ICLTensor * input, const ICLTensor * weights, const ICLTensor * biases, ICLTensor * output, const PadStrideInfo & conv_info, const ActivationLayerInfo & act_info = ActivationLayerInfo(), bool enable_fast_math = false)
Set the input and output tensors.
Note
: This function only works with 3x3,3x1,1x3,5x5,5x1 and 1x5 kernels along with unit strides for both NCHW and NHWC data layout
Some Winograd configurations (i.e. F(4x4, 5x5)) are supported only with enable_fast_math = true
Parameters
[in] input Source tensor. 3 lower dimensions represent a single input [width, height, IFM], while every optional dimension from 4 and above represent a batch of inputs. Data types supported: F16/F32.
[in] weights Weights tensor. Weights are 4D tensor with dimensions [kernel_x, kernel_y, IFM, OFM]. Data type supported:Same as input.
[in] biases Biases tensor. Shared biases supported. Biases are 1D tensor with dimensions [OFM].Data type supported: Same as input
[out] output Destination tensor. 3 lower dimensions represent a single output [width, height, OFM], while the rest represent batch of outputs. Data types supported: Same as input.
[in] conv_info Contains padding and stride information described in PadStrideInfo.
[in] act_info (Optional) Activation layer information in case of a fused activation.
[in] enable_fast_math (Optional) Enable fast math computation. In case this flag were set, the function could dispatch the fastest implementation available which may introduce a drop of accuracy as well. Default is false
Definition at line 92 of file CLWinogradConvolutionLayer.cpp.
 {
     // Get indices for the width and height
     const size_t idx_width  = get_data_layout_dimension_index(input->info()->data_layout(), DataLayoutDimension::WIDTH);
     const size_t idx_height = get_data_layout_dimension_index(input->info()->data_layout(), DataLayoutDimension::HEIGHT);
     // Input shape, kernel size and output tile
     const Size2D input_dims  = Size2D(input->info()->tensor_shape()[idx_width], input->info()->tensor_shape()[idx_height]);
     const Size2D kernel_size = Size2D(weights->info()->tensor_shape()[idx_width], weights->info()->tensor_shape()[idx_height]);
     const Size2D output_tile = winograd_output_tile(input_dims, kernel_size, input->info()->data_layout());
     // Check if the Winograd configuration requires fast math
     if(!enable_fast_math)
     {
         ARM_COMPUTE_ERROR_ON_DATA_TYPE_CHANNEL_NOT_IN(input, 1, DataType::F32); //disable winograd for fp16 if fast math is false.
         ARM_COMPUTE_ERROR_ON_MSG(check_support_fast_math(output_tile, kernel_size), "This Winograd configuration requires enable_fast_math=true");
     }
     const WinogradInfo winograd_info = WinogradInfo(output_tile,
                                                     kernel_size,
                                                     input_dims,
                                                     conv_info,
                                                     input->info()->data_layout());
     _is_prepared      = false;
     _original_weights = weights;
     // Manage intermediate tensors
     _memory_group.manage(&_input0);
     _memory_group.manage(&_batched_mm_output);
     // Do not manage _input1 as it contains the weights
     // Configure input transform
     _input_transform.configure(input, &_input0, winograd_info);
     // Configure filter transform
     _filter_transform.configure(weights, &_input1, winograd_info);
     // Configure batched matrix multiply
     _batched_mm.configure(&_input0, &_input1, nullptr, &_batched_mm_output, 1.0f, 0.0f, GEMMInfo(false, false, true /* Reshape weights only for the first run*/, 0, false, false, GEMMLowpOutputStageInfo(),
                                                                                                  (input->info()->data_type() == DataType::F16)));
     // Configure output transform
     _output_transform.configure(&_batched_mm_output, biases, output, winograd_info, act_info);
     // Allocate temporary tensors
     _input0.allocator()->allocate();
     _batched_mm_output.allocator()->allocate();
 }
References arm_compute::test::validation::act_info, CLTensorAllocator::allocate(), CLTensor::allocator(), ARM_COMPUTE_ERROR_ON_DATA_TYPE_CHANNEL_NOT_IN, ARM_COMPUTE_ERROR_ON_MSG, CLWinogradInputTransform::configure(), CLWinogradFilterTransformKernel::configure(), CLWinogradOutputTransformKernel::configure(), CLGEMM::configure(), arm_compute::test::validation::conv_info, ITensorInfo::data_layout(), ITensorInfo::data_type(), arm_compute::F16, arm_compute::F32, arm_compute::get_data_layout_dimension_index(), arm_compute::HEIGHT, ITensor::info(), CLTensor::info(), MemoryGroupBase< TensorType >::manage(), ITensorInfo::tensor_shape(), TensorInfo::tensor_shape(), arm_compute::test::validation::weights, arm_compute::WIDTH, and arm_compute::test::validation::winograd_info.
operator=() [1/2]
CLWinogradConvolutionLayer& operator= (const CLWinogradConvolutionLayer &) delete
Prevent instances of this class from being copied (As this class contains pointers)
operator=() [2/2]
CLWinogradConvolutionLayer& operator= (CLWinogradConvolutionLayer &&) default
Default move assignment operator.
prepare()
void prepare () override virtual
Prepare the function for executing.
Any one off pre-processing step required by the function is handled here
Note
Prepare stage might not need all the function's buffers' backing memory to be available in order to execute
Reimplemented from IFunction.
Definition at line 215 of file CLWinogradConvolutionLayer.cpp.
 {
     if(!_is_prepared)
     {
         // Run filter transform and mark original weights as unused
         _input1.allocator()->allocate();
         CLScheduler::get().enqueue(_filter_transform, false);
         _original_weights->mark_as_unused();
         // Prepare GEMM and release reshaped weights if marked unused by CLGEMM
         _batched_mm.prepare();
         if(!_input1.is_used())
         {
             _input1.allocator()->free();
         }
         CLScheduler::get().queue().finish();
         _is_prepared = true;
     }
 }
References CLTensorAllocator::allocate(), CLTensor::allocator(), CLScheduler::enqueue(), CLTensorAllocator::free(), CLScheduler::get(), ITensor::is_used(), ITensor::mark_as_unused(), CLGEMM::prepare(), and CLScheduler::queue().
Referenced by CLWinogradConvolutionLayer::run().
run()
void run () override virtual
Run the kernels contained in the function.
For NEON kernels:
Multi-threading is used for the kernels which are parallelisable.
By default std::thread::hardware_concurrency() threads are used.
Note
CPPScheduler::set_num_threads() can be used to manually set the number of threads
For OpenCL kernels:
All the kernels are enqueued on the queue associated with CLScheduler.
The queue is then flushed.
Note
The function will not block until the kernels are executed. It is the user's responsibility to wait.
Will call prepare() on first run if hasn't been done
Implements IFunction.
Definition at line 197 of file CLWinogradConvolutionLayer.cpp.
 {
     prepare();
     _memory_group.acquire();
     // Run input transform
     _input_transform.run();
     // Run batched matrix multiplication
     _batched_mm.run();
     // Run output transform
     CLScheduler::get().enqueue(_output_transform);
     _memory_group.release();
 }
References MemoryGroupBase< TensorType >::acquire(), CLScheduler::enqueue(), CLScheduler::get(), CLWinogradConvolutionLayer::prepare(), MemoryGroupBase< TensorType >::release(), ICLSimpleFunction::run(), and CLGEMM::run().
validate()
Status validate (const ITensorInfo * input, const ITensorInfo * weights, const ITensorInfo * biases, const ITensorInfo * output, const PadStrideInfo & conv_info, const ActivationLayerInfo & act_info = ActivationLayerInfo(), bool enable_fast_math = false) static
Static function to check if given info will lead to a valid configuration of CLWinogradConvolutionLayer.
Note
: This function only works with 3x3,3x1,1x3,5x5,5x1 and 1x5 kernels along with unit strides for both NCHW and NHWC data layout
Some Winograd configurations (i.e. F(4x4, 5x5)) are supported only with enable_fast_math = true
Parameters
[in] input Source tensor. 3 lower dimensions represent a single input [width, height, IFM], while every optional dimension from 4 and above represent a batch of inputs. Data types supported: F16/F32.
[in] weights Weights tensor. Weights are 4D tensor with dimensions [kernel_x, kernel_y, IFM, OFM]. Data type supported:Same as input.
[in] biases Biases tensor. Shared biases supported. Biases are 1D tensor with dimensions [OFM].Data type supported: Same as input
[out] output Destination tensor. 3 lower dimensions represent a single output [width, height, OFM], while the rest represent batch of outputs. Data types supported: Same as input.
[in] conv_info Contains padding and stride information described in PadStrideInfo.
[in] act_info (Optional) Activation layer information in case of a fused activation.
[in] enable_fast_math (Optional) Enable fast math computation. In case this flag were set, the function could dispatch the fastest implementation available which may introduce a drop of accuracy as well. Default is false
Returns
a status
Definition at line 143 of file CLWinogradConvolutionLayer.cpp.
 {
     // Get indeces for the width and height
     const size_t idx_width  = get_data_layout_dimension_index(input->data_layout(), DataLayoutDimension::WIDTH);
     const size_t idx_height = get_data_layout_dimension_index(input->data_layout(), DataLayoutDimension::HEIGHT);
     // Input shape, kernel size and output tile
     const Size2D input_dims  = Size2D(input->tensor_shape()[idx_width], input->tensor_shape()[idx_height]);
     const Size2D kernel_size = Size2D(weights->tensor_shape()[idx_width], weights->tensor_shape()[idx_height]);
     const Size2D output_tile = winograd_output_tile(input_dims, kernel_size, input->data_layout());
     // Check if the Winograd configuration requires fast math
     if(!enable_fast_math)
     {
         ARM_COMPUTE_RETURN_ERROR_ON_DATA_TYPE_CHANNEL_NOT_IN(input, 1, DataType::F32); //disable winograd for fp16 if fast math is false.
         ARM_COMPUTE_RETURN_ERROR_ON_MSG(check_support_fast_math(output_tile, kernel_size), "This Winograd configuration requires enable_fast_math=true");
     }
     const WinogradInfo winograd_info = WinogradInfo(output_tile,
                                                     kernel_size,
                                                     input_dims,
                                                     conv_info,
                                                     input->data_layout());
     // Validate input transform
     const TensorShape input0_shape = misc::shape_calculator::compute_winograd_input_transform_shape(*input, winograd_info);
     const TensorInfo  input0       = input->clone()->set_tensor_shape(input0_shape);
     ARM_COMPUTE_RETURN_ON_ERROR(CLWinogradInputTransform::validate(input, &input0, winograd_info));
     // Validate filter transform
     const TensorShape input1_shape = misc::shape_calculator::compute_winograd_filter_transform_shape(*weights, winograd_info);
     const TensorInfo  input1       = weights->clone()->set_tensor_shape(input1_shape);
     ARM_COMPUTE_RETURN_ON_ERROR(CLWinogradFilterTransformKernel::validate(weights, &input1, winograd_info));
     // Validate batched matrix multiply
     TensorShape batched_mm_output_shape = input0.tensor_shape();
     batched_mm_output_shape[0]          = input1.tensor_shape()[0];
     const TensorInfo batched_mm_output  = input0.clone()->set_tensor_shape(batched_mm_output_shape);
     ARM_COMPUTE_RETURN_ON_ERROR(CLGEMM::validate(&input0, &input1, nullptr, &batched_mm_output, 1.0f, 0.0f, GEMMInfo(false, false, true /* Reshape weights only for the first run*/, 0, false, false,
                                                                                                                      GEMMLowpOutputStageInfo(), (input->data_type() == DataType::F16))));
     // Configure output transform
     ARM_COMPUTE_RETURN_ON_ERROR(CLWinogradOutputTransformKernel::validate(&batched_mm_output, biases, output, winograd_info));
     // Validate Activation Layer
     if(act_info.enabled())
     {
         ARM_COMPUTE_RETURN_ON_ERROR(CLActivationLayer::validate(output, nullptr, act_info));
     }
     return Status{};
 }
References arm_compute::test::validation::act_info, ARM_COMPUTE_RETURN_ERROR_ON_DATA_TYPE_CHANNEL_NOT_IN, ARM_COMPUTE_RETURN_ERROR_ON_MSG, ARM_COMPUTE_RETURN_ON_ERROR, ICloneable< T >::clone(), TensorInfo::clone(), arm_compute::misc::shape_calculator::compute_winograd_filter_transform_shape(), arm_compute::misc::shape_calculator::compute_winograd_input_transform_shape(), arm_compute::test::validation::conv_info, ITensorInfo::data_layout(), ITensorInfo::data_type(), arm_compute::F16, arm_compute::F32, arm_compute::get_data_layout_dimension_index(), arm_compute::HEIGHT, ITensorInfo::tensor_shape(), TensorInfo::tensor_shape(), CLActivationLayer::validate(), CLWinogradInputTransform::validate(), CLWinogradFilterTransformKernel::validate(), CLWinogradOutputTransformKernel::validate(), CLGEMM::validate(), arm_compute::test::validation::weights, arm_compute::WIDTH, and arm_compute::test::validation::winograd_info.
Referenced by CLConvolutionLayer::get_convolution_method(), and CLConvolutionLayer::validate().
The documentation for this class was generated from the following files:
arm_compute/runtime/CL/functions/CLWinogradConvolutionLayer.h
src/runtime/CL/functions/CLWinogradConvolutionLayer.cpp