Compute Library: ThresholdDataset Class Reference
ThresholdDataset Class Reference
#include <ThresholdDataset.h>
Data Structures
struct iterator
Public Types
using type = std::tuple< uint8_t, uint8_t, uint8_t, ThresholdType, uint8_t >
Public Member Functions
iterator begin () const
int size () const
void add_config (uint8_t threshold, uint8_t false_value, uint8_t true_value, ThresholdType threshold_type, uint8_t upper)
Detailed Description
Definition at line 37 of file ThresholdDataset.h.
Member Typedef Documentation
using type = std::tuple<uint8_t, uint8_t, uint8_t, ThresholdType, uint8_t>
Definition at line 40 of file ThresholdDataset.h.
Member Function Documentation
void add_config (uint8_t threshold, uint8_t false_value, uint8_t true_value, ThresholdType threshold_type, uint8_t upper) inline
Definition at line 103 of file ThresholdDataset.h.
Referenced by MixedThresholdDataset::MixedThresholdDataset().
     {
         _thresholds.emplace_back(std::move(threshold));
         _false_values.emplace_back(std::move(false_value));
         _true_values.emplace_back(std::move(true_value));
         _types.emplace_back(std::move(threshold_type));
         _uppers.emplace_back(std::move(upper));
     }
iterator begin () const inline
Definition at line 93 of file ThresholdDataset.h.
References ThresholdDataset::iterator::iterator().
     {
         return iterator(_thresholds.begin(), _false_values.begin(), _true_values.begin(), _types.begin(), _uppers.begin());
     }
int size () const inline
Definition at line 98 of file ThresholdDataset.h.
References arm_compute::test::fixed_point_arithmetic::detail::min().
     {
         return std::min(_thresholds.size(), std::min(_false_values.size(), std::min(_true_values.size(), std::min(_types.size(), _uppers.size()))));
     }
The documentation for this class was generated from the following file:
tests/datasets/ThresholdDataset.h