Compute Library: NEMinMaxKernel Class Reference
NEMinMaxKernel Class Reference
Interface for the kernel to perform min max search on an image.
#include <NEMinMaxLocationKernel.h>
Public Member Functions
const char * name () const override
Name of the kernel.
NEMinMaxKernel ()
Default constructor.
NEMinMaxKernel (const NEMinMaxKernel &)=delete
Prevent instances of this class from being copied (As this class contains pointers)
NEMinMaxKernel & operator= (const NEMinMaxKernel &)=delete
Prevent instances of this class from being copied (As this class contains pointers)
NEMinMaxKernel (NEMinMaxKernel &&)=default
Allow instances of this class to be moved.
NEMinMaxKernel & operator= (NEMinMaxKernel &&)=default
Allow instances of this class to be moved.
~NEMinMaxKernel ()=default
Default destructor.
void configure (const IImage *input, void *min, void *max)
Initialise the kernel's input and outputs.
void reset ()
Resets global minimum and maximum.
void run (const Window &window, const ThreadInfo &info) override
Execute the kernel on the passed window.
Public Member Functions inherited from ICPPKernel
virtual ~ICPPKernel ()=default
Default destructor.
Public Member Functions inherited from IKernel
IKernel ()
Constructor.
virtual ~IKernel ()=default
Destructor.
virtual bool is_parallelisable () const
Indicates whether or not the kernel is parallelisable.
virtual BorderSize border_size () const
The size of the border for that kernel.
const Window & window () const
The maximum window the kernel can be executed on.
Detailed Description
Interface for the kernel to perform min max search on an image.
Definition at line 39 of file NEMinMaxLocationKernel.h.
Constructor & Destructor Documentation
NEMinMaxKernel() [1/3]
NEMinMaxKernel ()
Default constructor.
Definition at line 44 of file NEMinMaxLocationKernel.cpp.
     : _func(), _input(nullptr), _min(), _max(), _mtx()
 {
 }
NEMinMaxKernel() [2/3]
NEMinMaxKernel (const NEMinMaxKernel &) delete
Prevent instances of this class from being copied (As this class contains pointers)
NEMinMaxKernel() [3/3]
NEMinMaxKernel (NEMinMaxKernel &&) default
Allow instances of this class to be moved.
~NEMinMaxKernel()
~NEMinMaxKernel () default
Default destructor.
Member Function Documentation
configure()
void configure (const IImage * input, void * min, void * max)
Initialise the kernel's input and outputs.
Parameters
[in] input Input Image. Data types supported: U8/S16/F32.
[out] min Minimum value of image. Data types supported: S32 if input type is U8/S16, F32 if input type is F32.
[out] max Maximum value of image. Data types supported: S32 if input type is U8/S16, F32 if input type is F32.
Definition at line 49 of file NEMinMaxLocationKernel.cpp.
 {
     ARM_COMPUTE_ERROR_ON_TENSOR_NOT_2D(input);
     ARM_COMPUTE_ERROR_ON_DATA_TYPE_CHANNEL_NOT_IN(input, 1, DataType::U8, DataType::S16, DataType::F32);
     ARM_COMPUTE_ERROR_ON(nullptr == min);
     ARM_COMPUTE_ERROR_ON(nullptr == max);
     _input = input;
     _min   = min;
     _max   = max;
     switch(_input->info()->data_type())
     {
         case DataType::U8:
             _func = &NEMinMaxKernel::minmax_U8;
             break;
         case DataType::S16:
             _func = &NEMinMaxKernel::minmax_S16;
             break;
         case DataType::F32:
             _func = &NEMinMaxKernel::minmax_F32;
             break;
         default:
             ARM_COMPUTE_ERROR("Unsupported data type");
             break;
     }
     // Configure kernel window
     constexpr unsigned int num_elems_processed_per_iteration = 1;
     Window win = calculate_max_window(*input->info(), Steps(num_elems_processed_per_iteration));
     INEKernel::configure(win);
 }
References ARM_COMPUTE_ERROR, ARM_COMPUTE_ERROR_ON, ARM_COMPUTE_ERROR_ON_DATA_TYPE_CHANNEL_NOT_IN, ARM_COMPUTE_ERROR_ON_TENSOR_NOT_2D, arm_compute::calculate_max_window(), ITensorInfo::data_type(), arm_compute::F32, ITensor::info(), arm_compute::S16, and arm_compute::U8.
Referenced by NEMinMaxLocation::configure().
name()
const char* name () const inline override virtual
Name of the kernel.
Returns
Kernel name
Implements ICPPKernel.
Definition at line 42 of file NEMinMaxLocationKernel.h.
     {
         return "NEMinMaxKernel";
     }
operator=() [1/2]
NEMinMaxKernel& operator= (const NEMinMaxKernel &) delete
Prevent instances of this class from being copied (As this class contains pointers)
operator=() [2/2]
NEMinMaxKernel& operator= (NEMinMaxKernel &&) default
Allow instances of this class to be moved.
reset()
void reset ()
Resets global minimum and maximum.
Definition at line 94 of file NEMinMaxLocationKernel.cpp.
 {
     ARM_COMPUTE_ERROR_ON_UNCONFIGURED_KERNEL(this);
     switch(_input->info()->data_type())
     {
         case DataType::U8:
             *static_cast<int32_t *>(_min) = UCHAR_MAX;
             *static_cast<int32_t *>(_max) = 0;
             break;
         case DataType::S16:
             *static_cast<int32_t *>(_min) = SHRT_MAX;
             *static_cast<int32_t *>(_max) = SHRT_MIN;
             break;
         case DataType::F32:
             *static_cast<float *>(_min) = std::numeric_limits<float>::max();
             *static_cast<float *>(_max) = std::numeric_limits<float>::lowest();
             break;
         default:
             ARM_COMPUTE_ERROR("Unsupported data type");
             break;
     }
 }
References ARM_COMPUTE_ERROR, ARM_COMPUTE_ERROR_ON_UNCONFIGURED_KERNEL, ITensorInfo::data_type(), arm_compute::F32, ITensor::info(), arm_compute::support::cpp11::lowest(), arm_compute::S16, and arm_compute::U8.
Referenced by NEMinMaxLocation::run().
run()
void run (const Window & window, const ThreadInfo & info) override virtual
Execute the kernel on the passed window.
Warning
If is_parallelisable() returns false then the passed window must be equal to window()
Note
The window has to be a region within the window returned by the window() method
The width of the window has to be a multiple of num_elems_processed_per_iteration().
Parameters
[in] window Region on which to execute the kernel. (Must be a region of the window returned by window())
[in] info Info about executing thread and CPU.
Implements ICPPKernel.
Definition at line 84 of file NEMinMaxLocationKernel.cpp.
 {
     ARM_COMPUTE_UNUSED(info);
     ARM_COMPUTE_ERROR_ON_UNCONFIGURED_KERNEL(this);
     ARM_COMPUTE_ERROR_ON_INVALID_SUBWINDOW(INEKernel::window(), window);
     ARM_COMPUTE_ERROR_ON(_func == nullptr);
     (this->*_func)(window);
 }
References ARM_COMPUTE_ERROR_ON, ARM_COMPUTE_ERROR_ON_INVALID_SUBWINDOW, ARM_COMPUTE_ERROR_ON_UNCONFIGURED_KERNEL, ARM_COMPUTE_UNUSED, arm_compute::test::validation::info, and IKernel::window().
The documentation for this class was generated from the following files:
arm_compute/core/NEON/kernels/NEMinMaxLocationKernel.h
src/core/NEON/kernels/NEMinMaxLocationKernel.cpp