Compute Library: IGCKernel::BufferParam Class Reference
IGCKernel::BufferParam Class Reference
#include <IGCKernel.h>
Public Member Functions
BufferParam (const unsigned int binding, const unsigned int shift)
Constructor.
Data Fields
unsigned int binding_point = 0
Tensor's binding point in this kernel.
unsigned int buffer_data_type_shift = 0
The base 2 logarithm of SSBO buffer data type size (Number of bits to be shift for offset calculation)
Detailed Description
Definition at line 49 of file IGCKernel.h.
Constructor & Destructor Documentation
BufferParam (const unsigned int binding, const unsigned int shift) inline
Constructor.
Parameters
[in] binding Tensor's binding point.
[in] shift Number of bits to be shift for offset calculation
Definition at line 62 of file IGCKernel.h.
References IGCKernel::add_1D_tensor_argument(), IGCKernel::add_2D_tensor_argument(), IGCKernel::add_3D_tensor_argument(), IGCKernel::BufferParam::binding_point, arm_compute::enqueue(), IGCKernel::kernel(), IGCKernel::num_arguments_per_1D_tensor(), IGCKernel::num_arguments_per_2D_tensor(), IGCKernel::num_arguments_per_3D_tensor(), IGCKernel::run(), arm_compute::U, and IKernel::window().
             : binding_point(binding), buffer_data_type_shift(shift)
         {
         }
Field Documentation
unsigned int binding_point = 0
Tensor's binding point in this kernel.
Definition at line 53 of file IGCKernel.h.
Referenced by IGCKernel::BufferParam::BufferParam().
unsigned int buffer_data_type_shift = 0
The base 2 logarithm of SSBO buffer data type size (Number of bits to be shift for offset calculation)
Definition at line 55 of file IGCKernel.h.
The documentation for this class was generated from the following file:
arm_compute/core/GLES_COMPUTE/IGCKernel.h