Compute Library: CLScaleKernel Class Reference
CLScaleKernel Class Reference
Interface for the scale kernel.
#include <CLScaleKernel.h>
Public Member Functions
void configure (const ICLTensor *input, ICLTensor *output, InterpolationPolicy policy, BorderMode border_mode, SamplingPolicy sampling_policy=SamplingPolicy::CENTER)
Initialise the kernel's inputs, output and interpolation policy.
const ICLTensor * input () const
Input tensor accessor.
const ICLTensor * output () const
Output tensor accessor.
BorderSize border_size () const override
The size of the border for that kernel.
void run (const Window &window, cl::CommandQueue &queue) override
Enqueue the OpenCL kernel to process the given window on the passed OpenCL command queue.
Public Member Functions inherited from ICLSimpleKernel
ICLSimpleKernel ()
Constructor.
ICLSimpleKernel (const ICLSimpleKernel &)=delete
Prevent instances of this class from being copied (As this class contains pointers)
ICLSimpleKernel & operator= (const ICLSimpleKernel &)=delete
Prevent instances of this class from being copied (As this class contains pointers)
ICLSimpleKernel (ICLSimpleKernel &&)=default
Allow instances of this class to be moved.
ICLSimpleKernel & operator= (ICLSimpleKernel &&)=default
Allow instances of this class to be moved.
~ICLSimpleKernel ()=default
Default destructor.
void configure (const ICLTensor *input, ICLTensor *output, unsigned int num_elems_processed_per_iteration, bool border_undefined=false, const BorderSize &border_size=BorderSize())
Configure the kernel.
Public Member Functions inherited from ICLKernel
ICLKernel ()
Constructor.
cl::Kernel & kernel ()
Returns a reference to the OpenCL kernel of this object.
template<typename T >
void add_1D_array_argument (unsigned int &idx, const ICLArray< T > *array, const Strides &strides, unsigned int num_dimensions, const Window &window)
Add the passed 1D array's parameters to the object's kernel's arguments starting from the index idx.
void add_1D_tensor_argument (unsigned int &idx, const ICLTensor *tensor, const Window &window)
Add the passed 1D tensor's parameters to the object's kernel's arguments starting from the index idx.
void add_1D_tensor_argument_if (bool cond, unsigned int &idx, const ICLTensor *tensor, const Window &window)
Add the passed 1D tensor's parameters to the object's kernel's arguments starting from the index idx if the condition is true.
void add_2D_tensor_argument (unsigned int &idx, const ICLTensor *tensor, const Window &window)
Add the passed 2D tensor's parameters to the object's kernel's arguments starting from the index idx.
void add_2D_tensor_argument_if (bool cond, unsigned int &idx, const ICLTensor *tensor, const Window &window)
Add the passed 2D tensor's parameters to the object's kernel's arguments starting from the index idx if the condition is true.
void add_3D_tensor_argument (unsigned int &idx, const ICLTensor *tensor, const Window &window)
Add the passed 3D tensor's parameters to the object's kernel's arguments starting from the index idx.
void add_4D_tensor_argument (unsigned int &idx, const ICLTensor *tensor, const Window &window)
Add the passed 4D tensor's parameters to the object's kernel's arguments starting from the index idx.
template<typename T >
void add_argument (unsigned int &idx, T value)
Add the passed parameters to the object's kernel's arguments starting from the index idx.
void set_lws_hint (const cl::NDRange &lws_hint)
Set the Local-Workgroup-Size hint.
cl::NDRange lws_hint () const
Return the Local-Workgroup-Size hint.
const std::string & config_id () const
Get the configuration ID.
void set_target (GPUTarget target)
Set the targeted GPU architecture.
void set_target (cl::Device &device)
Set the targeted GPU architecture according to the CL device.
GPUTarget get_target () const
Get the targeted GPU architecture.
size_t get_max_workgroup_size ()
Get the maximum workgroup size for the device the CLKernelLibrary uses.
template<typename T , unsigned int dimension_size>
void add_array_argument (unsigned &idx, const ICLArray< T > *array, const Strides &strides, unsigned int num_dimensions, const Window &window)
Add the passed array's parameters to the object's kernel's arguments starting from the index idx.
template<unsigned int dimension_size>
void add_tensor_argument (unsigned &idx, const ICLTensor *tensor, const Window &window)
Public Member Functions inherited from IKernel
IKernel ()
Constructor.
virtual ~IKernel ()=default
Destructor.
virtual bool is_parallelisable () const
Indicates whether or not the kernel is parallelisable.
const Window & window () const
The maximum window the kernel can be executed on.
Static Public Member Functions
static Status validate (const ITensorInfo *input, const ITensorInfo *output, InterpolationPolicy policy, BorderMode border_mode, SamplingPolicy sampling_policy=SamplingPolicy::CENTER)
Static function to check if given info will lead to a valid configuration of CLScaleKernel.
Static Public Member Functions inherited from ICLKernel
static constexpr unsigned int num_arguments_per_1D_array ()
Returns the number of arguments enqueued per 1D array object.
static constexpr unsigned int num_arguments_per_1D_tensor ()
Returns the number of arguments enqueued per 1D tensor object.
static constexpr unsigned int num_arguments_per_2D_tensor ()
Returns the number of arguments enqueued per 2D tensor object.
static constexpr unsigned int num_arguments_per_3D_tensor ()
Returns the number of arguments enqueued per 3D tensor object.
static constexpr unsigned int num_arguments_per_4D_tensor ()
Returns the number of arguments enqueued per 4D tensor object.
static cl::NDRange gws_from_window (const Window &window)
Get the global work size given an execution window.
Data Fields
InterpolationPolicy _interpolationPolicy = InterpolationPolicy::BILINEAR
Detailed Description
Interface for the scale kernel.
Definition at line 35 of file CLScaleKernel.h.
Member Function Documentation
border_size()
BorderSize border_size () const override virtual
The size of the border for that kernel.
Returns
The width in number of elements of the border.
Reimplemented from IKernel.
Definition at line 136 of file CLScaleKernel.cpp.
 {
     return BorderSize(1);
 }
Referenced by CLScaleKernel::configure().
configure()
void configure (const ICLTensor * input, ICLTensor * output, InterpolationPolicy policy, BorderMode border_mode, SamplingPolicy sampling_policy = SamplingPolicy::CENTER)
Initialise the kernel's inputs, output and interpolation policy.
Parameters
[in] input Source tensor. Data types supported: U8/QASYMM8/S16/F16/F32
[out] output Destination tensor. Data types supported: Same as input All but the lowest two dimensions must be the same size as in the input tensor, i.e. scaling is only performed within the XY-plane.
[in] policy Interpolation type to use
[in] border_mode Selected border mode.
[in] sampling_policy (Optional) Sampling policy used by the interpolation. Defaults to SamplingPolicy::CENTER
Definition at line 161 of file CLScaleKernel.cpp.
 {
     _input               = input;
     _output              = output;
     _interpolationPolicy = policy;
     ARM_COMPUTE_ERROR_THROW_ON(validate_arguments(input->info(), output->info(), policy));
     float wr = 0.f;
     float hr = 0.f;
     std::tie(wr, hr) = calculate_scale_factors(*input->info(), *output->info());
     const bool call_quantized_kernel = is_data_type_quantized_asymmetric(input->info()->data_type()) && policy == InterpolationPolicy::BILINEAR;
     DataLayout data_layout = input->info()->data_layout();
     const int  idx_width   = get_data_layout_dimension_index(data_layout, DataLayoutDimension::WIDTH);
     const int  idx_height  = get_data_layout_dimension_index(data_layout, DataLayoutDimension::HEIGHT);
     const bool is_nhwc     = data_layout == DataLayout::NHWC;
     // Compute the ratio between source width/height and destination width/height
     const unsigned int input_width   = input->info()->dimension(idx_width);
     const unsigned int input_height  = input->info()->dimension(idx_height);
     const unsigned int output_width  = output->info()->dimension(idx_width);
     const unsigned int output_height = output->info()->dimension(idx_height);
     // Compute actual border size
     BorderSize border = border_size();
     // Area interpolation behaves as Nearest Neighbour in case of up-sampling
     if(policy == InterpolationPolicy::AREA && wr <= 1.f && hr <= 1.f)
     {
         policy = InterpolationPolicy::NEAREST_NEIGHBOR;
     }
     // Configure kernel window
     auto win_config = validate_and_configure_window(input->info(), output->info(), policy, border_mode, sampling_policy, border);
     ARM_COMPUTE_ERROR_THROW_ON(win_config.first);
     ICLKernel::configure_internal(win_config.second);
     // Create kernel
     CLBuildOptions build_opts;
     build_opts.add_option("-DDATA_TYPE=" + get_cl_type_from_data_type(input->info()->data_type()));
     build_opts.add_option("-DBORDER_SIZE=" + support::cpp11::to_string(border.right));
     build_opts.add_option_if(border_mode == BorderMode::REPLICATE, "-DBORDER_MODE_REPLICATE");
     build_opts.add_option_if(is_nhwc, "-DDEPTH_OUT=" + support::cpp11::to_string(output->info()->dimension(2)));
     build_opts.add_option_if_else(sampling_policy == SamplingPolicy::CENTER, "-DSAMPLING_POLICY_CENTER", "-DSAMPLING_POLICY_TOP_LEFT");
     if(call_quantized_kernel)
     {
         const UniformQuantizationInfo qinfo = input->info()->quantization_info().uniform();
         build_opts.add_option("-DSCALE=" + support::cpp11::to_string(qinfo.scale));
         build_opts.add_option("-DOFFSET=" + support::cpp11::to_string(qinfo.offset));
     }
     std::string interpolation_name = string_from_interpolation_policy(policy);
     std::transform(interpolation_name.begin(), interpolation_name.end(), interpolation_name.begin(), ::tolower);
     std::string kernel_name = "scale_" + interpolation_name;
     kernel_name += call_quantized_kernel ? "_quantized_" : "_";
     kernel_name += lower_string(string_from_data_layout(data_layout));
     _kernel = static_cast<cl::Kernel>(CLKernelLibrary::get().create_kernel(kernel_name, build_opts.options()));
     unsigned int idx = is_nhwc ? 2 * num_arguments_per_4D_tensor() : 2 * num_arguments_per_2D_tensor(); //Skip the input and output parameters
     // Set static kernel arguments
     const float scale_x = static_cast<float>(input_width) / output_width;
     const float scale_y = static_cast<float>(input_height) / output_height;
     _kernel.setArg<float>(idx++, input_width);
     _kernel.setArg<float>(idx++, input_height);
     _kernel.setArg<float>(idx++, scale_x);
     _kernel.setArg<float>(idx++, scale_y);
     // Set config_id for enabling LWS tuning
     _config_id = "scale_";
     _config_id += (border_mode == BorderMode::REPLICATE ? "Bord_rep" : "");
     _config_id += (sampling_policy == SamplingPolicy::CENTER ? "center" : "topleft");
     _config_id += (is_nhwc ? "nhwc" : "nchw");
     _config_id += "_";
     _config_id += support::cpp11::to_string(output->info()->dimension(0));
     _config_id += "_";
     _config_id += support::cpp11::to_string(output->info()->dimension(1));
     _config_id += "_";
     _config_id += support::cpp11::to_string(output->info()->dimension(2));
     _config_id += "_";
     _config_id += support::cpp11::to_string(output->info()->dimension(3));
 }
References CLScaleKernel::_interpolationPolicy, CLBuildOptions::add_option(), CLBuildOptions::add_option_if(), CLBuildOptions::add_option_if_else(), arm_compute::AREA, ARM_COMPUTE_ERROR_THROW_ON, arm_compute::BILINEAR, arm_compute::test::validation::border_mode, CLScaleKernel::border_size(), arm_compute::CENTER, arm_compute::create_kernel(), arm_compute::test::validation::data_layout, ITensorInfo::data_layout(), ITensorInfo::data_type(), ITensorInfo::dimension(), CLKernelLibrary::get(), arm_compute::get_cl_type_from_data_type(), arm_compute::get_data_layout_dimension_index(), arm_compute::HEIGHT, ITensor::info(), CLScaleKernel::input(), arm_compute::is_data_type_quantized_asymmetric(), arm_compute::lower_string(), arm_compute::NEAREST_NEIGHBOR, arm_compute::NHWC, ICLKernel::num_arguments_per_2D_tensor(), ICLKernel::num_arguments_per_4D_tensor(), QuantizationInfo::offset(), CLBuildOptions::options(), CLScaleKernel::output(), arm_compute::test::validation::policy, arm_compute::test::validation::qinfo, ITensorInfo::quantization_info(), arm_compute::REPLICATE, BorderSize::right, QuantizationInfo::scale(), arm_compute::string_from_data_layout(), arm_compute::string_from_interpolation_policy(), arm_compute::support::cpp11::to_string(), arm_compute::utility::tolower(), QuantizationInfo::uniform(), arm_compute::validate_and_configure_window(), and arm_compute::WIDTH.
input()
const ICLTensor * input () const
Input tensor accessor.
Returns
Pointer to input tensor.
Definition at line 151 of file CLScaleKernel.cpp.
 {
     return _input;
 }
Referenced by CLScaleKernel::configure(), and CLScaleKernel::validate().
output()
const ICLTensor * output () const
Output tensor accessor.
Returns
Pointer to output tensor.
Definition at line 156 of file CLScaleKernel.cpp.
 {
     return _output;
 }
Referenced by CLScaleKernel::configure(), and CLScaleKernel::validate().
run()
void run (const Window & window, cl::CommandQueue & queue) override virtual
Enqueue the OpenCL kernel to process the given window on the passed OpenCL command queue.
Note
The queue is not flushed by this method, and therefore the kernel will not have been executed by the time this method returns.
Parameters
[in] window Region on which to execute the kernel. (Must be a valid region of the window returned by window()).
[in,out] queue Command queue on which to enqueue the kernel.
Reimplemented from ICLSimple2DKernel.
Definition at line 247 of file CLScaleKernel.cpp.
 {
     ARM_COMPUTE_ERROR_ON_UNCONFIGURED_KERNEL(this);
     ARM_COMPUTE_ERROR_ON_INVALID_SUBWINDOW(ICLKernel::window(), window);
     switch(_input->info()->data_layout())
     {
         case DataLayout::NCHW:
         {
             Window slice = window.first_slice_window_2D();
             do
             {
                 unsigned int idx = 0;
                 add_2D_tensor_argument(idx, _input, slice);
                 add_2D_tensor_argument(idx, _output, slice);
                 enqueue(queue, *this, slice, lws_hint());
             }
             while(window.slide_window_slice_2D(slice));
             break;
         }
         case DataLayout::NHWC:
         {
             Window collapsed = window.collapse(ICLKernel::window(), Window::DimZ);
             Window slice     = collapsed.first_slice_window_4D();
             unsigned int idx = 0;
             add_4D_tensor_argument(idx, _input, slice);
             add_4D_tensor_argument(idx, _output, slice);
             enqueue(queue, *this, slice, lws_hint());
             break;
         }
         default:
             ARM_COMPUTE_ERROR("Data layout not supported");
     }
 }
References ICLKernel::add_2D_tensor_argument(), ICLKernel::add_4D_tensor_argument(), ARM_COMPUTE_ERROR, ARM_COMPUTE_ERROR_ON_INVALID_SUBWINDOW, ARM_COMPUTE_ERROR_ON_UNCONFIGURED_KERNEL, Window::collapse(), Window::DimZ, arm_compute::enqueue(), Window::first_slice_window_2D(), Window::first_slice_window_4D(), ICLKernel::lws_hint(), arm_compute::NCHW, arm_compute::NHWC, arm_compute::test::validation::reference::slice(), Window::slide_window_slice_2D(), and IKernel::window().
validate()
Status validate (const ITensorInfo * input, const ITensorInfo * output, InterpolationPolicy policy, BorderMode border_mode, SamplingPolicy sampling_policy = SamplingPolicy::CENTER) static
Static function to check if given info will lead to a valid configuration of CLScaleKernel.
Parameters
[in] input Source tensor info. Data types supported: U8/QASYMM8/S16/F16/F32
[in] output Destination tensor info. Data types supported: Same as input All but the lowest two dimensions must be the same size as in the input tensor, i.e. scaling is only performed within the XY-plane.
[in] policy Interpolation type to use
[in] border_mode Selected border mode.
[in] sampling_policy (Optional) Sampling policy used by the interpolation. Defaults to SamplingPolicy::CENTER
Returns
a status
Definition at line 141 of file CLScaleKernel.cpp.
 {
     BorderSize border = BorderSize(1);
     ARM_COMPUTE_RETURN_ON_ERROR(validate_arguments(input, output, policy));
     ARM_COMPUTE_RETURN_ON_ERROR(validate_and_configure_window(input->clone().get(), output->clone().get(), policy, border_mode, sampling_policy, border).first);
     return Status{};
 }
References ARM_COMPUTE_RETURN_ON_ERROR, arm_compute::test::validation::border_mode, CLScaleKernel::input(), CLScaleKernel::output(), arm_compute::test::validation::policy, and arm_compute::validate_and_configure_window().
Referenced by CLScale::validate().
Field Documentation
_interpolationPolicy
InterpolationPolicy _interpolationPolicy = InterpolationPolicy::BILINEAR
Definition at line 77 of file CLScaleKernel.h.
Referenced by CLScaleKernel::configure().
The documentation for this class was generated from the following files:
arm_compute/core/CL/kernels/CLScaleKernel.h
src/core/CL/kernels/CLScaleKernel.cpp