Compute Library: GCNormalizationLayer Class Reference
GCNormalizationLayer Class Reference
Basic function to compute a normalization layer.
#include <GCNormalizationLayer.h>
Public Member Functions
GCNormalizationLayer (std::shared_ptr< IMemoryManager > memory_manager=nullptr)
Default constructor.
void configure (const IGCTensor *input, IGCTensor *output, const NormalizationLayerInfo &norm_info)
Set the input and output tensors.
void run () override
Run the kernels contained in the function.
Public Member Functions inherited from IFunction
virtual ~IFunction ()=default
Destructor.
virtual void prepare ()
Prepare the function for executing.
Detailed Description
Basic function to compute a normalization layer.
This function calls the following OpenGL ES kernels:
GCPixelWiseMultiplicationKernel
GCFillBorderKernel
GCNormalizationLayerKernel
Definition at line 48 of file GCNormalizationLayer.h.
Constructor & Destructor Documentation
GCNormalizationLayer()
GCNormalizationLayer (std::shared_ptr< IMemoryManager > memory_manager = nullptr)
Default constructor.
Definition at line 36 of file GCNormalizationLayer.cpp.
     : _memory_group(std::move(memory_manager)), _squared_input(), _norm_kernel(), _multiply_kernel(), _border_handler()
 {
 }
Member Function Documentation
configure()
void configure (const IGCTensor * input, IGCTensor * output, const NormalizationLayerInfo & norm_info)
Set the input and output tensors.
Parameters
[in] input Source tensor. 3 lower dims represent a single input with dimensions [width, height, IFM], and an optional 4th dimension for batch of inputs. Data types supported: F32. Number of channels must be 1.
[out] output Destination tensor. Dimensions, data type and number of channels must match the input ones.
[in] norm_info Normalization layer information like the normalization type, normalization size and other parameters.
Definition at line 41 of file GCNormalizationLayer.cpp.
 {
     ARM_COMPUTE_ERROR_ON(input == nullptr);
     _squared_input.allocator()->init(TensorInfo(input->info()->tensor_shape(), 1, input->info()->data_type()));
     _memory_group.manage(&_squared_input);
     _norm_kernel.configure(input, &_squared_input, output, norm_info);
     _multiply_kernel.configure(input, input, &_squared_input, 1.0f);
     // Fill the border by 3 elements since we need vload4 in the IN_MAP normalization kernel
     _border_handler.configure(&_squared_input, _norm_kernel.border_size(), BorderMode::CONSTANT, PixelValue());
     // Allocate intermediate buffers
     _squared_input.allocator()->allocate();
 }
References ITensorAllocator::allocate(), GCTensor::allocator(), ARM_COMPUTE_ERROR_ON, GCNormalizationLayerKernel::border_size(), GCPixelWiseMultiplicationKernel::configure(), GCNormalizationLayerKernel::configure(), GCFillBorderKernel::configure(), arm_compute::CONSTANT, ITensorInfo::data_type(), ITensor::info(), ITensorAllocator::init(), MemoryGroupBase< TensorType >::manage(), and ITensorInfo::tensor_shape().
run()
void run () override virtual
Run the kernels contained in the function.
For NEON kernels:
Multi-threading is used for the kernels which are parallelisable.
By default std::thread::hardware_concurrency() threads are used.
Note
CPPScheduler::set_num_threads() can be used to manually set the number of threads
For OpenCL kernels:
All the kernels are enqueued on the queue associated with CLScheduler.
The queue is then flushed.
Note
The function will not block until the kernels are executed. It is the user's responsibility to wait.
Will call prepare() on first run if hasn't been done
Implements IFunction.
Definition at line 57 of file GCNormalizationLayer.cpp.
 {
     _memory_group.acquire();
     GCScheduler::get().dispatch(_multiply_kernel, false);
     GCScheduler::get().memory_barrier();
     GCScheduler::get().dispatch(_border_handler, false);
     GCScheduler::get().memory_barrier();
     GCScheduler::get().dispatch(_norm_kernel, true);
     _memory_group.release();
 }
References MemoryGroupBase< TensorType >::acquire(), GCScheduler::dispatch(), GCScheduler::get(), GCScheduler::memory_barrier(), and MemoryGroupBase< TensorType >::release().
The documentation for this class was generated from the following files:
arm_compute/runtime/GLES_COMPUTE/functions/GCNormalizationLayer.h
src/runtime/GLES_COMPUTE/functions/GCNormalizationLayer.cpp