Compute Library: CLPadLayer Class Reference
CLPadLayer Class Reference
Basic function to pad a tensor.
#include <CLPadLayer.h>
Public Member Functions
CLPadLayer ()
Default constructor.
void configure (ICLTensor *input, ICLTensor *output, const PaddingList &padding, PixelValue constant_value=PixelValue(), PaddingMode mode=PaddingMode::CONSTANT)
Initialize the function.
void run () override
Run the kernels contained in the function.
Public Member Functions inherited from IFunction
virtual ~IFunction ()=default
Destructor.
virtual void prepare ()
Prepare the function for executing.
Static Public Member Functions
static Status validate (const ITensorInfo *input, const ITensorInfo *output, const PaddingList &padding, PixelValue constant_value=PixelValue(), PaddingMode mode=PaddingMode::CONSTANT)
Static function to check if given info will lead to a valid configuration of CLPadLayer.
Detailed Description
Basic function to pad a tensor.
This function calls the following OpenCL kernels:
CLMemsetKernel
CLFillBorderKernel
CLCopyKernel
Definition at line 47 of file CLPadLayer.h.
Constructor & Destructor Documentation
CLPadLayer()
CLPadLayer ()
Default constructor.
Definition at line 33 of file CLPadLayer.cpp.
     : _copy_kernel(), _mode(), _padding(), _memset_kernel(), _num_dimensions(0), _slice_functions(), _concat_functions(), _slice_results(), _concat_results()
 {
 }
Member Function Documentation
configure()
void configure (ICLTensor * input, ICLTensor * output, const PaddingList & padding, PixelValue constant_value = PixelValue(), PaddingMode mode = PaddingMode::CONSTANT)
Initialize the function.
Parameters
[in] input Source tensor. Data types supported: U8/S8/QASYMM8/U16/S16/F16/U32/S32/F32.
[out] output Output tensor. Data type supported: same as input
[in] padding The padding for each spatial dimension of the input tensor. The pair padding[i] specifies the front and the end padding in the i-th dimension.
[in] constant_value (Optional) Constant value to be used for the padding.
[in] mode (Optional) Controls whether the padding should be filled with constant_value using CONSTANT, or reflect the input, either including the border values (SYMMETRIC) or not (REFLECT). Only CONSTANT is currently supported.
Definition at line 164 of file CLPadLayer.cpp.
 {
     ARM_COMPUTE_ERROR_THROW_ON(validate(input->info(), output->info(), padding, constant_value, mode));
     _padding = padding;
     _mode    = mode;
     TensorShape padded_shape = misc::shape_calculator::compute_padded_shape(input->info()->tensor_shape(), _padding);
     auto_init_if_empty(*output->info(), input->info()->clone()->set_tensor_shape(padded_shape));
     // Find the last dimension requiring padding so that it is known when to write to output and whether any padding is applied.
     int64_t last_padding_dimension = _padding.size() - 1;
     for(; last_padding_dimension >= 0; --last_padding_dimension)
     {
         if(_padding[last_padding_dimension].first > 0 || _padding[last_padding_dimension].second > 0)
         {
             break;
         }
     }
     _num_dimensions = last_padding_dimension + 1;
     if(_num_dimensions > 0)
     {
         switch(_mode)
         {
             case PaddingMode::CONSTANT:
             {
                 configure_constant_mode(input, output, padding, constant_value);
                 break;
             }
             case PaddingMode::REFLECT:
             case PaddingMode::SYMMETRIC:
             {
                 configure_reflect_symmetric_mode(input, output);
                 break;
             }
             default:
                 ARM_COMPUTE_ERROR("Padding mode not supported.");
         }
     }
     else
     {
         // Copy the input to the whole output if no padding is applied
         _copy_kernel.configure(input, output);
     }
 }
References ARM_COMPUTE_ERROR, ARM_COMPUTE_ERROR_THROW_ON, arm_compute::auto_init_if_empty(), ICloneable< T >::clone(), arm_compute::misc::shape_calculator::compute_padded_shape(), CLCopyKernel::configure(), arm_compute::CONSTANT, ITensor::info(), arm_compute::test::validation::padding, arm_compute::REFLECT, arm_compute::SYMMETRIC, ITensorInfo::tensor_shape(), and CLPadLayer::validate().
Referenced by CLFFTConvolutionLayer::configure().
run()
void run () override virtual
Run the kernels contained in the function.
For NEON kernels:
Multi-threading is used for the kernels which are parallelisable.
By default std::thread::hardware_concurrency() threads are used.
Note
CPPScheduler::set_num_threads() can be used to manually set the number of threads
For OpenCL kernels:
All the kernels are enqueued on the queue associated with CLScheduler.
The queue is then flushed.
Note
The function will not block until the kernels are executed. It is the user's responsibility to wait.
Will call prepare() on first run if hasn't been done
Implements IFunction.
Definition at line 274 of file CLPadLayer.cpp.
 {
     if(_num_dimensions > 0)
     {
         switch(_mode)
         {
             case PaddingMode::CONSTANT:
             {
                 CLScheduler::get().enqueue(_memset_kernel, false);
                 CLScheduler::get().enqueue(_copy_kernel, true);
                 break;
             }
             case PaddingMode::REFLECT:
             case PaddingMode::SYMMETRIC:
             {
                 for(uint32_t i = 0; i < _num_dimensions; ++i)
                 {
                     if(_padding[i].first > 0 || _padding[i].second > 0)
                     {
                         if(_padding[i].first > 0 && _slice_results[2 * i].info()->total_size() > 0)
{
                             _slice_functions[2 * i].run();
                         }
                         if(_padding[i].second > 0 && _slice_results[2 * i + 1].info()->total_size() > 0)
{
                             _slice_functions[2 * i + 1].run();
                         }
                         CLScheduler::get().sync();
                         _concat_functions[i].run();
                         CLScheduler::get().sync();
                     }
                 }
                 break;
             }
             default:
                 ARM_COMPUTE_ERROR("Padding mode not supported.");
         }
     }
     else
     {
         CLScheduler::get().enqueue(_copy_kernel, true);
     }
 }
References ARM_COMPUTE_ERROR, arm_compute::CONSTANT, CLScheduler::enqueue(), CLScheduler::get(), arm_compute::test::validation::info, arm_compute::REFLECT, arm_compute::SYMMETRIC, and CLScheduler::sync().
Referenced by CLFFTConvolutionLayer::prepare(), and CLFFTConvolutionLayer::run().
validate()
Status validate (const ITensorInfo * input, const ITensorInfo * output, const PaddingList & padding, PixelValue constant_value = PixelValue(), PaddingMode mode = PaddingMode::CONSTANT) static
Static function to check if given info will lead to a valid configuration of CLPadLayer.
Parameters
[in] input Source tensor info. Data types supported: U8/S8/QASYMM8/U16/S16/F16/U32/S32/F32.
[in] output Output tensor info. Data type supported: same as input
[in] padding The padding for each spatial dimension of the input tensor. The pair padding[i] specifies the front and the end padding in the i-th dimension.
[in] constant_value (Optional) Constant value to be used for the padding
[in] mode (Optional) Controls whether the padding should be filled with constant_value using CONSTANT, or reflect the input, either including the border values (SYMMETRIC) or not (REFLECT). Only CONSTANT is currently supported.
Definition at line 211 of file CLPadLayer.cpp.
 {
     ARM_COMPUTE_RETURN_ERROR_ON(padding.size() > input->num_dimensions());
     TensorShape padded_shape = misc::shape_calculator::compute_padded_shape(input->tensor_shape(), padding);
     // Use CLCopyKernel and CLMemsetKernel to validate all padding modes as this includes all of the shape and info validation.
     PaddingList padding_extended = padding;
     for(size_t i = padding.size(); i < TensorShape::num_max_dimensions; i++)
     {
         padding_extended.emplace_back(PaddingInfo{ 0, 0 });
     }
     Window copy_window = Window();
     for(uint32_t i = 0; i < padded_shape.num_dimensions(); ++i)
     {
         copy_window.set(i, Window::Dimension(padding_extended[i].first, padding_extended[i].first + input->dimension(i), 1));
     }
     if(output->total_size() > 0)
     {
         ARM_COMPUTE_RETURN_ERROR_ON_MISMATCHING_DIMENSIONS(output->tensor_shape(), padded_shape);
         ARM_COMPUTE_RETURN_ERROR_ON_MISMATCHING_DATA_TYPES(output, input);
         ARM_COMPUTE_RETURN_ON_ERROR(CLCopyKernel::validate(input, output, PaddingList(), &copy_window));
         ARM_COMPUTE_RETURN_ON_ERROR(CLMemsetKernel::validate(output, constant_value));
     }
     else
     {
         ARM_COMPUTE_RETURN_ON_ERROR(CLCopyKernel::validate(input, &input->clone()->set_tensor_shape(padded_shape), PaddingList(), &copy_window));
         ARM_COMPUTE_RETURN_ON_ERROR(CLMemsetKernel::validate(&input->clone()->set_tensor_shape(padded_shape), constant_value));
     }
     switch(mode)
     {
         case PaddingMode::CONSTANT:
         {
             break;
         }
         case PaddingMode::REFLECT:
         case PaddingMode::SYMMETRIC:
         {
             for(uint32_t i = 0; i < padding.size(); ++i)
             {
                 if(mode == PaddingMode::REFLECT)
                 {
                     ARM_COMPUTE_RETURN_ERROR_ON(padding[i].first >= input->dimension(i));
                     ARM_COMPUTE_RETURN_ERROR_ON(padding[i].second >= input->dimension(i));
                 }
                 else
                 {
                     ARM_COMPUTE_RETURN_ERROR_ON(padding[i].first > input->dimension(i));
                     ARM_COMPUTE_RETURN_ERROR_ON(padding[i].second > input->dimension(i));
                 }
             }
             break;
         }
         default:
         {
             ARM_COMPUTE_ERROR("Invalid mode");
         }
     }
     return Status{};
 }
References ARM_COMPUTE_ERROR, ARM_COMPUTE_RETURN_ERROR_ON, ARM_COMPUTE_RETURN_ERROR_ON_MISMATCHING_DATA_TYPES, ARM_COMPUTE_RETURN_ERROR_ON_MISMATCHING_DIMENSIONS, ARM_COMPUTE_RETURN_ON_ERROR, ICloneable< T >::clone(), arm_compute::misc::shape_calculator::compute_padded_shape(), arm_compute::CONSTANT, ITensorInfo::dimension(), ITensorInfo::num_dimensions(), Dimensions< size_t >::num_max_dimensions, arm_compute::test::validation::padding, arm_compute::REFLECT, Window::set(), arm_compute::SYMMETRIC, ITensorInfo::tensor_shape(), ITensorInfo::total_size(), CLCopyKernel::validate(), and CLMemsetKernel::validate().
Referenced by CLPadLayer::configure().
The documentation for this class was generated from the following files:
arm_compute/runtime/CL/functions/CLPadLayer.h
src/runtime/CL/functions/CLPadLayer.cpp