Compute Library: TestError Class Reference
TestError Class Reference
Error class for failures during test execution.
#include <Exceptions.h>
Public Member Functions
TestError (const std::string &msg, LogLevel level, std::string context="")
Construct error with severity.
LogLevel level () const
Severity of the error.
const char * what () const noexceptoverride
Detailed Description
Error class for failures during test execution.
Definition at line 78 of file Exceptions.h.
Constructor & Destructor Documentation
TestError (const std::string & msg, LogLevel level, std::string context = "")
Construct error with severity.
Parameters
[in] msg Error message.
[in] level Severity level.
[in] context Context.
Definition at line 112 of file Exceptions.cpp.
References TestError::level().
     : std::runtime_error{ msg }, _level{ level }, _msg{ msg }, _context{ std::move(context) }, _combined{ "ERROR: " + msg }
 {
     if(!_context.empty())
     {
         _combined += "\nCONTEXT:\n" + _context;
     }
 }
Member Function Documentation
LogLevel level () const
Severity of the error.
Returns
Severity.
Definition at line 121 of file Exceptions.cpp.
Referenced by Framework::error_on_missing_assets(), Framework::log_failed_expectation(), and TestError::TestError().
 {
     return _level;
 }
const char * what () const override noexcept
Definition at line 126 of file Exceptions.cpp.
 {
     return _combined.c_str();
 }
The documentation for this class was generated from the following files:
tests/framework/Exceptions.h
tests/framework/Exceptions.cpp