Compute Library: Semaphore Class Reference
Semaphore Class Reference
Semamphore class.
#include <Semaphore.h>
Public Member Functions
Semaphore (int value=0)
Default Constuctor.
void signal ()
Signals a semaphore.
void wait ()
Waits on a semaphore.
Detailed Description
Semamphore class.
Definition at line 35 of file Semaphore.h.
Constructor & Destructor Documentation
Semaphore (int value = 0) inline
Default Constuctor.
Parameters
[in] value Semaphore initial value
Definition at line 42 of file Semaphore.h.
Referenced by Semaphore::wait().
         : _value(value), _m(), _cv()
     {
     }
Member Function Documentation
void signal () inline
Signals a semaphore.
Definition at line 47 of file Semaphore.h.
Referenced by Semaphore::wait().
     {
         std::unique_lock<std::mutex> lock(_m);
         ++_value;
         _cv.notify_one();
     }
void wait () inline
Waits on a semaphore.
Definition at line 54 of file Semaphore.h.
References Semaphore::Semaphore(), Semaphore::signal(), and value.
     {
         std::unique_lock<std::mutex> lock(_m);
         _cv.wait(lock, [this]()
         {
             return _value > 0;
         });
         --_value;
     }
The documentation for this class was generated from the following file:
support/Semaphore.h