Compute Library: CaffePreproccessor Class Reference
CaffePreproccessor Class Reference
Caffe preproccessor.
#include <GraphUtils.h>
Public Member Functions
CaffePreproccessor (std::array< float, 3 > mean=std::array< float, 3 > { { 0, 0, 0 } }, bool bgr=true, float scale=1.f)
Default Constructor.
void preprocess (ITensor &tensor) override
Preprocess the given tensor.
Public Member Functions inherited from IPreprocessor
virtual ~IPreprocessor ()=default
Default destructor.
Detailed Description
Caffe preproccessor.
Definition at line 60 of file GraphUtils.h.
Constructor & Destructor Documentation
CaffePreproccessor()
CaffePreproccessor (std::array< float, 3 > mean = std::array<float, 3> { { 0, 0, 0 } }, bool bgr = true, float scale = 1.f)
Default Constructor.
Parameters
[in] mean Mean array in RGB ordering
[in] bgr Boolean specifying if the preprocessing should assume BGR format
[in] scale Scale value
Definition at line 80 of file GraphUtils.cpp.
     : _mean(mean), _bgr(bgr), _scale(scale)
 {
     if(_bgr)
     {
         std::swap(_mean[0], _mean[2]);
     }
 }
References arm_compute::swap().
Member Function Documentation
preprocess()
void preprocess (ITensor & tensor) override virtual
Preprocess the given tensor.
Parameters
[in] tensor Tensor to preprocess.
Implements IPreprocessor.
Definition at line 89 of file GraphUtils.cpp.
 {
     Window window;
     window.use_tensor_dimensions(tensor.info()->tensor_shape());
     const int channel_idx = get_data_layout_dimension_index(tensor.info()->data_layout(), DataLayoutDimension::CHANNEL);
     execute_window_loop(window, [&](const Coordinates & id)
     {
         const float value                                     = *reinterpret_cast<float *>(tensor.ptr_to_element(id)) - _mean[id[channel_idx]];
         *reinterpret_cast<float *>(tensor.ptr_to_element(id)) = value * _scale;
     });
 }
References arm_compute::CHANNEL, ITensorInfo::data_layout(), arm_compute::execute_window_loop(), arm_compute::get_data_layout_dimension_index(), ITensor::info(), ITensorInfo::tensor_shape(), and Window::use_tensor_dimensions().
The documentation for this class was generated from the following files:
utils/GraphUtils.h
utils/GraphUtils.cpp