Compute Library: CLBatchToSpaceLayerKernel Class Reference
CLBatchToSpaceLayerKernel Class Reference
Interface for the batch to space kernel.
#include <CLBatchToSpaceLayerKernel.h>
Public Member Functions
CLBatchToSpaceLayerKernel ()
Default constructor.
CLBatchToSpaceLayerKernel (const CLBatchToSpaceLayerKernel &)=delete
Prevent instances of this class from being copied (As this class contains pointers)
CLBatchToSpaceLayerKernel & operator= (const CLBatchToSpaceLayerKernel &)=delete
Prevent instances of this class from being copied (As this class contains pointers)
CLBatchToSpaceLayerKernel (CLBatchToSpaceLayerKernel &&)=default
Allow instances of this class to be moved.
CLBatchToSpaceLayerKernel & operator= (CLBatchToSpaceLayerKernel &&)=default
Allow instances of this class to be moved.
~CLBatchToSpaceLayerKernel ()=default
Default destructor.
void configure (const ICLTensor *input, const ICLTensor *block_shape, ICLTensor *output)
Initialise the kernel's inputs and output.
void configure (const ICLTensor *input, const int32_t block_shape_x, const int32_t block_shape_y, ICLTensor *output)
Initialise the kernel's inputs and output (Static block shape).
void run (const Window &window, cl::CommandQueue &queue) override
Enqueue the OpenCL kernel to process the given window on the passed OpenCL command queue.
Public Member Functions inherited from ICLKernel
ICLKernel ()
Constructor.
cl::Kernel & kernel ()
Returns a reference to the OpenCL kernel of this object.
template<typename T >
void add_1D_array_argument (unsigned int &idx, const ICLArray< T > *array, const Strides &strides, unsigned int num_dimensions, const Window &window)
Add the passed 1D array's parameters to the object's kernel's arguments starting from the index idx.
void add_1D_tensor_argument (unsigned int &idx, const ICLTensor *tensor, const Window &window)
Add the passed 1D tensor's parameters to the object's kernel's arguments starting from the index idx.
void add_2D_tensor_argument (unsigned int &idx, const ICLTensor *tensor, const Window &window)
Add the passed 2D tensor's parameters to the object's kernel's arguments starting from the index idx.
void add_3D_tensor_argument (unsigned int &idx, const ICLTensor *tensor, const Window &window)
Add the passed 3D tensor's parameters to the object's kernel's arguments starting from the index idx.
void add_4D_tensor_argument (unsigned int &idx, const ICLTensor *tensor, const Window &window)
Add the passed 4D tensor's parameters to the object's kernel's arguments starting from the index idx.
template<typename T >
void add_argument (unsigned int &idx, T value)
Add the passed parameters to the object's kernel's arguments starting from the index idx.
void set_lws_hint (const cl::NDRange &lws_hint)
Set the Local-Workgroup-Size hint.
cl::NDRange lws_hint () const
Return the Local-Workgroup-Size hint.
const std::string & config_id () const
Get the configuration ID.
void set_target (GPUTarget target)
Set the targeted GPU architecture.
void set_target (cl::Device &device)
Set the targeted GPU architecture according to the CL device.
GPUTarget get_target () const
Get the targeted GPU architecture.
size_t get_max_workgroup_size ()
Get the maximum workgroup size for the device the CLKernelLibrary uses.
template<typename T , unsigned int dimension_size>
void add_array_argument (unsigned &idx, const ICLArray< T > *array, const Strides &strides, unsigned int num_dimensions, const Window &window)
Add the passed array's parameters to the object's kernel's arguments starting from the index idx.
template<unsigned int dimension_size>
void add_tensor_argument (unsigned &idx, const ICLTensor *tensor, const Window &window)
Public Member Functions inherited from IKernel
IKernel ()
Constructor.
virtual ~IKernel ()=default
Destructor.
virtual bool is_parallelisable () const
Indicates whether or not the kernel is parallelisable.
virtual BorderSize border_size () const
The size of the border for that kernel.
const Window & window () const
The maximum window the kernel can be executed on.
Static Public Member Functions
static Status validate (const ITensorInfo *input, const ITensorInfo *block_shape, const ITensorInfo *output)
Static function to check if given info will lead to a valid configuration of CLBatchToSpaceLayerKernel.
static Status validate (const ITensorInfo *input, const int32_t block_shape_x, const int32_t block_shape_y, const ITensorInfo *output)
Static function to check if given info will lead to a valid configuration of CLBatchToSpaceLayerKernel (Static block shape).
Static Public Member Functions inherited from ICLKernel
static constexpr unsigned int num_arguments_per_1D_array ()
Returns the number of arguments enqueued per 1D array object.
static constexpr unsigned int num_arguments_per_1D_tensor ()
Returns the number of arguments enqueued per 1D tensor object.
static constexpr unsigned int num_arguments_per_2D_tensor ()
Returns the number of arguments enqueued per 2D tensor object.
static constexpr unsigned int num_arguments_per_3D_tensor ()
Returns the number of arguments enqueued per 3D tensor object.
static constexpr unsigned int num_arguments_per_4D_tensor ()
Returns the number of arguments enqueued per 4D tensor object.
static cl::NDRange gws_from_window (const Window &window)
Get the global work size given an execution window.
Detailed Description
Interface for the batch to space kernel.
Definition at line 35 of file CLBatchToSpaceLayerKernel.h.
Constructor & Destructor Documentation
CLBatchToSpaceLayerKernel() [1/3]
CLBatchToSpaceLayerKernel ()
Default constructor.
Definition at line 79 of file CLBatchToSpaceLayerKernel.cpp.
     : _input(nullptr), _block_shape(nullptr), _output(nullptr)
 {
 }
CLBatchToSpaceLayerKernel() [2/3]
CLBatchToSpaceLayerKernel (const CLBatchToSpaceLayerKernel &) delete
Prevent instances of this class from being copied (As this class contains pointers)
CLBatchToSpaceLayerKernel() [3/3]
CLBatchToSpaceLayerKernel (CLBatchToSpaceLayerKernel &&) default
Allow instances of this class to be moved.
~CLBatchToSpaceLayerKernel()
~CLBatchToSpaceLayerKernel () default
Default destructor.
Member Function Documentation
configure() [1/2]
void configure (const ICLTensor * input, const ICLTensor * block_shape, ICLTensor * output)
Initialise the kernel's inputs and output.
Parameters
[in] input Tensor input. Supported tensor rank: 4. Data types supported: U8/S8/QASYMM8/U16/S16/F16/U32/S32/F32.
[in] block_shape 1-D tensor with shape [M]. Data types supported: S32
[out] output Tensor output. Data types supported: same as input
Definition at line 84 of file CLBatchToSpaceLayerKernel.cpp.
 {
     ARM_COMPUTE_ERROR_ON_NULLPTR(input, output);
     ARM_COMPUTE_ERROR_THROW_ON(validate_arguments(input->info(), block_shape->info(), output->info()));
     _input       = input;
     _block_shape = block_shape;
     _output      = output;
     const int idx_width = get_data_layout_dimension_index(input->info()->data_layout(), DataLayoutDimension::WIDTH);
     // Create kernel
     CLBuildOptions build_opts;
     build_opts.add_option("-DDATA_TYPE=" + get_cl_type_from_data_type(input->info()->data_type()));
     build_opts.add_option("-DBATCH_SIZE=" + support::cpp11::to_string(input->info()->dimension(3)));
     build_opts.add_option("-DWIDTH_IN=" + support::cpp11::to_string(input->info()->dimension(idx_width)));
     _kernel = static_cast<cl::Kernel>(CLKernelLibrary::get().create_kernel("batch_to_space_" + lower_string(string_from_data_layout(input->info()->data_layout())), build_opts.options()));
     // Configure kernel window
     Window win = calculate_max_window(*input->info(), Steps());
     ICLKernel::configure_internal(win);
 }
References CLBuildOptions::add_option(), ARM_COMPUTE_ERROR_ON_NULLPTR, ARM_COMPUTE_ERROR_THROW_ON, arm_compute::calculate_max_window(), arm_compute::create_kernel(), ITensorInfo::data_layout(), ITensorInfo::data_type(), ITensorInfo::dimension(), CLKernelLibrary::get(), arm_compute::get_cl_type_from_data_type(), arm_compute::get_data_layout_dimension_index(), ITensor::info(), arm_compute::lower_string(), arm_compute::string_from_data_layout(), arm_compute::support::cpp11::to_string(), and arm_compute::WIDTH.
Referenced by CLBatchToSpaceLayer::configure().
configure() [2/2]
void configure (const ICLTensor * input, const int32_t block_shape_x, const int32_t block_shape_y, ICLTensor * output)
Initialise the kernel's inputs and output (Static block shape).
Parameters
[in] input Tensor input. Supported tensor rank: 4. Data types supported: U8/S8/QASYMM8/U16/S16/F16/U32/S32/F32.
[in] block_shape_x Block shape x value.
[in] block_shape_y Block shape y value.
[out] output Tensor output. Data types supported: same as input
Definition at line 107 of file CLBatchToSpaceLayerKernel.cpp.
 {
     ARM_COMPUTE_ERROR_ON_NULLPTR(input, output);
     TensorShape output_shape = compute_batch_to_space_shape(input->info(), block_shape_x, block_shape_y);
     auto_init_if_empty(*output->info(), output_shape, 1, input->info()->data_type());
     ARM_COMPUTE_ERROR_THROW_ON(validate_arguments_static(input->info(), block_shape_x, block_shape_y, output->info()));
     _input  = input;
     _output = output;
     const int idx_width = get_data_layout_dimension_index(input->info()->data_layout(), DataLayoutDimension::WIDTH);
     // Create kernel
     CLBuildOptions build_opts;
     build_opts.add_option("-DDATA_TYPE=" + get_cl_type_from_data_type(input->info()->data_type()));
     build_opts.add_option("-DBATCH_SIZE=" + support::cpp11::to_string(input->info()->dimension(3)));
     build_opts.add_option("-DBLOCK_SHAPE_X=" + support::cpp11::to_string(block_shape_x));
     build_opts.add_option("-DBLOCK_SHAPE_Y=" + support::cpp11::to_string(block_shape_y));
     build_opts.add_option("-DWIDTH_IN=" + support::cpp11::to_string(input->info()->dimension(idx_width)));
     _kernel = static_cast<cl::Kernel>(CLKernelLibrary::get().create_kernel("batch_to_space_static_" + lower_string(string_from_data_layout(input->info()->data_layout())), build_opts.options()));
     // Configure kernel window
     Window win = calculate_max_window(*input->info(), Steps());
     ICLKernel::configure_internal(win);
 }
References CLBuildOptions::add_option(), ARM_COMPUTE_ERROR_ON_NULLPTR, ARM_COMPUTE_ERROR_THROW_ON, arm_compute::auto_init_if_empty(), arm_compute::calculate_max_window(), arm_compute::misc::shape_calculator::compute_batch_to_space_shape(), arm_compute::create_kernel(), ITensorInfo::data_layout(), ITensorInfo::data_type(), ITensorInfo::dimension(), CLKernelLibrary::get(), arm_compute::get_cl_type_from_data_type(), arm_compute::get_data_layout_dimension_index(), ITensor::info(), arm_compute::lower_string(), arm_compute::test::validation::output_shape, arm_compute::string_from_data_layout(), arm_compute::support::cpp11::to_string(), and arm_compute::WIDTH.
operator=() [1/2]
CLBatchToSpaceLayerKernel& operator= (const CLBatchToSpaceLayerKernel &) delete
Prevent instances of this class from being copied (As this class contains pointers)
operator=() [2/2]
CLBatchToSpaceLayerKernel& operator= (CLBatchToSpaceLayerKernel &&) default
Allow instances of this class to be moved.
run()
void run (const Window & window, cl::CommandQueue & queue) override virtual
Enqueue the OpenCL kernel to process the given window on the passed OpenCL command queue.
Note
The queue is not flushed by this method, and therefore the kernel will not have been executed by the time this method returns.
Parameters
[in] window Region on which to execute the kernel. (Must be a valid region of the window returned by window()).
[in,out] queue Command queue on which to enqueue the kernel.
Implements ICLKernel.
Definition at line 149 of file CLBatchToSpaceLayerKernel.cpp.
 {
     ARM_COMPUTE_ERROR_ON_UNCONFIGURED_KERNEL(this);
     ARM_COMPUTE_ERROR_ON_INVALID_SUBWINDOW(ICLKernel::window(), window);
     Window slice_in  = window.first_slice_window_3D();
     Window slice_out = window.first_slice_window_4D();
     Window vector_slice = window.first_slice_window_1D();
     vector_slice.set(Window::DimX, Window::Dimension(0, 0, 0));
     slice_out.set(Window::DimX, Window::Dimension(0, 0, 0));
     slice_out.set(Window::DimY, Window::Dimension(0, 0, 0));
     slice_out.set(Window::DimZ, Window::Dimension(0, 0, 0));
     slice_out.set(3, Window::Dimension(0, 0, 0));
     int batch_id = 0;
     do
     {
         unsigned int idx = 0;
         add_3D_tensor_argument(idx, _input, slice_in);
         add_argument(idx, batch_id);
         if(_block_shape != nullptr)
         {
             add_1D_tensor_argument(idx, _block_shape, vector_slice);
         }
         add_4D_tensor_argument(idx, _output, slice_out);
         enqueue(queue, *this, slice_in);
         ++batch_id;
     }
     while(window.slide_window_slice_3D(slice_in));
 }
References ICLKernel::add_1D_tensor_argument(), ICLKernel::add_3D_tensor_argument(), ICLKernel::add_4D_tensor_argument(), ICLKernel::add_argument(), ARM_COMPUTE_ERROR_ON_INVALID_SUBWINDOW, ARM_COMPUTE_ERROR_ON_UNCONFIGURED_KERNEL, Window::DimX, Window::DimY, Window::DimZ, arm_compute::enqueue(), Window::first_slice_window_1D(), Window::first_slice_window_3D(), Window::first_slice_window_4D(), Window::set(), Window::slide_window_slice_3D(), and IKernel::window().
validate() [1/2]
Status validate (const ITensorInfo * input, const ITensorInfo * block_shape, const ITensorInfo * output) static
Static function to check if given info will lead to a valid configuration of CLBatchToSpaceLayerKernel.
Parameters
[in] input Tensor input. Supported tensor rank: 4. Data types supported: U8/S8/QASYMM8/U16/S16/F16/U32/S32/F32.
[in] block_shape 1-D tensor with shape [M]. Data types supported: S32
[in] output Tensor output. Data types supported: same as input
Returns
a status
Definition at line 135 of file CLBatchToSpaceLayerKernel.cpp.
 {
     ARM_COMPUTE_RETURN_ERROR_ON_NULLPTR(input, block_shape, output);
     ARM_COMPUTE_RETURN_ON_ERROR(validate_arguments(input, block_shape, output));
     return Status{};
 }
References ARM_COMPUTE_RETURN_ERROR_ON_NULLPTR, and ARM_COMPUTE_RETURN_ON_ERROR.
Referenced by CLBatchToSpaceLayer::validate().
validate() [2/2]
Status validate (const ITensorInfo * input, const int32_t block_shape_x, const int32_t block_shape_y, const ITensorInfo * output) static
Static function to check if given info will lead to a valid configuration of CLBatchToSpaceLayerKernel (Static block shape).
Parameters
[in] input Tensor input. Supported tensor rank: 4. Data types supported: U8/S8/QASYMM8/U16/S16/F16/U32/S32/F32.
[in] block_shape_x Block shape x value.
[in] block_shape_y Block shape y value.
[in] output Tensor output. Data types supported: same as input
Returns
a status
Definition at line 142 of file CLBatchToSpaceLayerKernel.cpp.
 {
     ARM_COMPUTE_RETURN_ERROR_ON_NULLPTR(input, output);
     ARM_COMPUTE_RETURN_ON_ERROR(validate_arguments_static(input, block_shape_x, block_shape_y, output));
     return Status{};
 }
References ARM_COMPUTE_RETURN_ERROR_ON_NULLPTR, and ARM_COMPUTE_RETURN_ON_ERROR.
The documentation for this class was generated from the following files:
arm_compute/core/CL/kernels/CLBatchToSpaceLayerKernel.h
src/core/CL/kernels/CLBatchToSpaceLayerKernel.cpp