Compute Library: ConcatLayer Class Reference
ConcatLayer Class Reference final
Concat Layer.
#include <Layers.h>
Public Member Functions
template<typename... Ts>
ConcatLayer (SubStream &&sub_stream1, SubStream &&sub_stream2, Ts &&... rest_sub_streams)
Construct a concatenation layer.
template<typename... Ts>
ConcatLayer (DataLayoutDimension axis, SubStream &&sub_stream1, SubStream &&sub_stream2, Ts &&... rest_sub_streams)
Construct a concatenation layer.
template<typename... Ts>
ConcatLayer (SubStream &&sub_stream)
Construct a concat layer.
NodeID create_layer (IStream &s) override
Create layer and add to the given stream.
Public Member Functions inherited from ILayer
virtual ~ILayer ()=default
Default destructor.
ILayer & set_name (std::string name)
Sets the name of the layer.
const std::string & name () const
Layer name accessor.
Detailed Description
Concat Layer.
Definition at line 217 of file Layers.h.
Constructor & Destructor Documentation
ConcatLayer() [1/3]
ConcatLayer (SubStream && sub_stream1, SubStream && sub_stream2, Ts &&... rest_sub_streams) inline
Construct a concatenation layer.
Parameters
[in] sub_stream1 First graph branch
[in] sub_stream2 Second graph branch
[in] rest_sub_streams Rest sub-graph branches
Definition at line 227 of file Layers.h.
         : _sub_streams(), _axis(DataLayoutDimension::CHANNEL)
     {
         _sub_streams.push_back(arm_compute::support::cpp14::make_unique<SubStream>(std::move(sub_stream1)));
         _sub_streams.push_back(arm_compute::support::cpp14::make_unique<SubStream>(std::move(sub_stream2)));
         utility::for_each([&](SubStream && sub_stream)
         {
             _sub_streams.push_back(arm_compute::support::cpp14::make_unique<SubStream>(std::move(sub_stream)));
         },
         std::move(rest_sub_streams)...);
     }
References arm_compute::CHANNEL, and arm_compute::utility::for_each().
ConcatLayer() [2/3]
ConcatLayer (DataLayoutDimension axis, SubStream && sub_stream1, SubStream && sub_stream2, Ts &&... rest_sub_streams) inline
Construct a concatenation layer.
Parameters
[in] axis Axis over the concatenation will be performed
[in] sub_stream1 First graph branch
[in] sub_stream2 Second graph branch
[in] rest_sub_streams Rest sub-graph branches
Definition at line 247 of file Layers.h.
         : _sub_streams(), _axis(axis)
     {
         _sub_streams.push_back(arm_compute::support::cpp14::make_unique<SubStream>(std::move(sub_stream1)));
         _sub_streams.push_back(arm_compute::support::cpp14::make_unique<SubStream>(std::move(sub_stream2)));
         utility::for_each([&](SubStream && sub_stream)
         {
             _sub_streams.push_back(arm_compute::support::cpp14::make_unique<SubStream>(std::move(sub_stream)));
         },
         std::move(rest_sub_streams)...);
     }
References arm_compute::utility::for_each().
ConcatLayer() [3/3]
ConcatLayer (SubStream && sub_stream) inline
Construct a concat layer.
Parameters
[in] sub_stream Sub-stream
Definition at line 264 of file Layers.h.
         : _sub_streams(), _axis(DataLayoutDimension::CHANNEL)
     {
         _sub_streams.push_back(arm_compute::support::cpp14::make_unique<SubStream>(std::move(sub_stream)));
     }
References arm_compute::CHANNEL.
Member Function Documentation
create_layer()
NodeID create_layer (IStream & s) inline override virtual
Create layer and add to the given stream.
Parameters
[in] s Stream to add layer to.
Returns
ID of the created node.
Implements ILayer.
Definition at line 269 of file Layers.h.
     {
         NodeID     nid           = EmptyNodeID;
         NodeParams common_params = { name(), s.hints().target_hint };
         if(_sub_streams.size() == 1 && _sub_streams.at(0) != nullptr)
         {
             nid = _sub_streams[0]->tail_node();
         }
         else
         {
             // Collect tail nodes and concatenate
             std::vector<NodeIdxPair> nodes;
             for(auto &ss : _sub_streams)
             {
                 if(ss && (ss->tail_node() != EmptyNodeID))
                 {
                     const auto tail_node = s.graph().node(ss->tail_node());
                     if(tail_node != nullptr && tail_node->type() != NodeType::Output)
                     {
                         nodes.push_back({ ss->tail_node(), 0 });
                     }
                 }
             }
             nid = GraphBuilder::add_concatenate_node(s.graph(), common_params, nodes, _axis);
         }
         return nid;
     }
References GraphBuilder::add_concatenate_node(), arm_compute::graph::EmptyNodeID, IStream::graph(), IStream::hints(), ILayer::name(), Graph::node(), arm_compute::graph::Output, and StreamHints::target_hint.
The documentation for this class was generated from the following file:
arm_compute/graph/frontend/Layers.h