Compute Library: PPMLoader Class Reference
PPMLoader Class Reference
Class to load the content of a PPM file into an Image.
#include <Utils.h>
Public Member Functions
PPMLoader ()
void open (const std::string &ppm_filename)
Open a PPM file and reads its metadata (Width, height)
bool is_open ()
Return true if a PPM file is currently open.
template<typename T >
void init_image (T &image, arm_compute::Format format)
Initialise an image's metadata with the dimensions of the PPM file currently open.
template<typename T >
void fill_image (T &image)
Fill an image with the content of the currently open PPM file.
template<typename T >
void fill_planar_tensor (T &tensor, bool bgr=false)
Fill a tensor with 3 planes (one for each channel) with the content of the currently open PPM file.
unsigned int width () const
Return the width of the currently open PPM file.
unsigned int height () const
Return the height of the currently open PPM file.
Detailed Description
Class to load the content of a PPM file into an Image.
Definition at line 253 of file Utils.h.
Constructor & Destructor Documentation
PPMLoader () inline
Definition at line 256 of file Utils.h.
         : _fs(), _width(0), _height(0)
     {
     }
Member Function Documentation
void fill_image (T & image) inline
Fill an image with the content of the currently open PPM file.
Note
If the image is a CLImage, the function maps and unmaps the image
Parameters
[in,out] image Image to fill (Must be allocated, and of matching dimensions with the opened PPM).
Definition at line 312 of file Utils.h.
References ARM_COMPUTE_ERROR, ARM_COMPUTE_ERROR_ON, ARM_COMPUTE_ERROR_ON_FORMAT_NOT_IN, ARM_COMPUTE_ERROR_ON_MSG, ARM_COMPUTE_UNUSED, Window::DimX, Window::DimY, arm_compute::execute_window_loop(), arm_compute::utils::map(), Iterator::ptr(), arm_compute::RGB888, Window::set(), arm_compute::U8, and arm_compute::utils::unmap().
     {
         ARM_COMPUTE_ERROR_ON(!is_open());
         ARM_COMPUTE_ERROR_ON(image.info()->dimension(0) != _width || image.info()->dimension(1) != _height);
         ARM_COMPUTE_ERROR_ON_FORMAT_NOT_IN(&image, arm_compute::Format::U8, arm_compute::Format::RGB888);
         try
         {
             // Map buffer if creating a CLTensor/GCTensor
             map(image, true);
             // Check if the file is large enough to fill the image
             const size_t current_position = _fs.tellg();
             _fs.seekg(0, std::ios_base::end);
             const size_t end_position = _fs.tellg();
             _fs.seekg(current_position, std::ios_base::beg);
             ARM_COMPUTE_ERROR_ON_MSG((end_position - current_position) < image.info()->tensor_shape().total_size() * image.info()->element_size(),
                                      "Not enough data in file");
             ARM_COMPUTE_UNUSED(end_position);
             switch(image.info()->format())
             {
                 case arm_compute::Format::U8:
                 {
                     // We need to convert the data from RGB to grayscale:
                     // Iterate through every pixel of the image
                     arm_compute::Window window;
                     window.set(arm_compute::Window::DimX, arm_compute::Window::Dimension(0, _width, 1));
                     window.set(arm_compute::Window::DimY, arm_compute::Window::Dimension(0, _height, 1));
                     arm_compute::Iterator out(&image, window);
                     unsigned char red   = 0;
                     unsigned char green = 0;
                     unsigned char blue  = 0;
                     arm_compute::execute_window_loop(window, [&](const arm_compute::Coordinates & id)
                     {
                         red   = _fs.get();
                         green = _fs.get();
                         blue  = _fs.get();
                         *out.ptr() = 0.2126f * red + 0.7152f * green + 0.0722f * blue;
                     },
                     out);
                     break;
                 }
                 case arm_compute::Format::RGB888:
                 {
                     // There is no format conversion needed: we can simply copy the content of the input file to the image one row at the time.
                     // Create a vertical window to iterate through the image's rows:
                     arm_compute::Window window;
                     window.set(arm_compute::Window::DimY, arm_compute::Window::Dimension(0, _height, 1));
                     arm_compute::Iterator out(&image, window);
                     arm_compute::execute_window_loop(window, [&](const arm_compute::Coordinates & id)
                     {
                         // Copy one row from the input file to the current row of the image:
                         _fs.read(reinterpret_cast<std::fstream::char_type *>(out.ptr()), _width * image.info()->element_size());
                     },
                     out);
                     break;
                 }
                 default:
                     ARM_COMPUTE_ERROR("Unsupported format");
             }
             // Unmap buffer if creating a CLTensor/GCTensor
             unmap(image);
         }
         catch(const std::ifstream::failure &e)
         {
             ARM_COMPUTE_ERROR("Loading PPM file: %s", e.what());
         }
     }
void fill_planar_tensor (T & tensor, bool bgr = false) inline
Fill a tensor with 3 planes (one for each channel) with the content of the currently open PPM file.
Note
If the image is a CLImage, the function maps and unmaps the image
Parameters
[in,out] tensor Tensor with 3 planes to fill (Must be allocated, and of matching dimensions with the opened PPM). Data types supported: U8/F32
[in] bgr (Optional) Fill the first plane with blue channel (default = false)
Definition at line 399 of file Utils.h.
References ARM_COMPUTE_ERROR, ARM_COMPUTE_ERROR_ON, ARM_COMPUTE_ERROR_ON_DATA_TYPE_CHANNEL_NOT_IN, ARM_COMPUTE_ERROR_ON_MSG, ARM_COMPUTE_UNUSED, Window::DimX, Window::DimY, Window::DimZ, arm_compute::execute_window_loop(), arm_compute::F32, arm_compute::utils::map(), Iterator::ptr(), Window::set(), arm_compute::U8, and arm_compute::utils::unmap().
Referenced by PPMAccessor::access_tensor().
     {
         ARM_COMPUTE_ERROR_ON(!is_open());
         ARM_COMPUTE_ERROR_ON_DATA_TYPE_CHANNEL_NOT_IN(&tensor, 1, DataType::U8, DataType::F32);
         ARM_COMPUTE_ERROR_ON(tensor.info()->dimension(0) != _width || tensor.info()->dimension(1) != _height || tensor.info()->dimension(2) != 3);
         try
         {
             // Map buffer if creating a CLTensor
             map(tensor, true);
             // Check if the file is large enough to fill the image
             const size_t current_position = _fs.tellg();
             _fs.seekg(0, std::ios_base::end);
             const size_t end_position = _fs.tellg();
             _fs.seekg(current_position, std::ios_base::beg);
             ARM_COMPUTE_ERROR_ON_MSG((end_position - current_position) < tensor.info()->tensor_shape().total_size(),
                                      "Not enough data in file");
             ARM_COMPUTE_UNUSED(end_position);
             // Iterate through every pixel of the image
             arm_compute::Window window;
             window.set(arm_compute::Window::DimX, arm_compute::Window::Dimension(0, _width, 1));
             window.set(arm_compute::Window::DimY, arm_compute::Window::Dimension(0, _height, 1));
             window.set(arm_compute::Window::DimZ, arm_compute::Window::Dimension(0, 1, 1));
             arm_compute::Iterator out(&tensor, window);
             unsigned char red   = 0;
             unsigned char green = 0;
             unsigned char blue  = 0;
             size_t stride_z = tensor.info()->strides_in_bytes()[2];
             arm_compute::execute_window_loop(window, [&](const arm_compute::Coordinates & id)
             {
                 red   = _fs.get();
                 green = _fs.get();
                 blue  = _fs.get();
                 switch(tensor.info()->data_type())
                 {
                     case arm_compute::DataType::U8:
                     {
                         *(out.ptr() + 0 * stride_z) = bgr ? blue : red;
                         *(out.ptr() + 1 * stride_z) = green;
                         *(out.ptr() + 2 * stride_z) = bgr ? red : blue;
                         break;
                     }
                     case arm_compute::DataType::F32:
                     {
                         *reinterpret_cast<float *>(out.ptr() + 0 * stride_z) = static_cast<float>(bgr ? blue : red);
                         *reinterpret_cast<float *>(out.ptr() + 1 * stride_z) = static_cast<float>(green);
                         *reinterpret_cast<float *>(out.ptr() + 2 * stride_z) = static_cast<float>(bgr ? red : blue);
                         break;
                     }
                     default:
                     {
                         ARM_COMPUTE_ERROR("Unsupported data type");
                     }
                 }
             },
             out);
             // Unmap buffer if creating a CLTensor
             unmap(tensor);
         }
         catch(const std::ifstream::failure &e)
         {
             ARM_COMPUTE_ERROR("Loading PPM file: %s", e.what());
         }
     }
unsigned int height () const inline
Return the height of the currently open PPM file.
Definition at line 482 of file Utils.h.
Referenced by PPMAccessor::access_tensor().
     {
         return _height;
     }
void init_image (T & image, arm_compute::Format format) inline
Initialise an image's metadata with the dimensions of the PPM file currently open.
Parameters
[out] image Image to initialise
[in] format Format to use for the image (Must be RGB888 or U8)
Definition at line 295 of file Utils.h.
References ARM_COMPUTE_ERROR_ON, arm_compute::RGB888, and arm_compute::U8.
     {
         ARM_COMPUTE_ERROR_ON(!is_open());
         ARM_COMPUTE_ERROR_ON(format != arm_compute::Format::RGB888 && format != arm_compute::Format::U8);
         // Use the size of the input PPM image
         arm_compute::TensorInfo image_info(_width, _height, format);
         image.allocator()->init(image_info);
     }
bool is_open () inline
Return true if a PPM file is currently open.
Definition at line 284 of file Utils.h.
     {
         return _fs.is_open();
     }
void open (const std::string & ppm_filename) inline
Open a PPM file and reads its metadata (Width, height)
Parameters
[in] ppm_filename File to open
Definition at line 264 of file Utils.h.
References ARM_COMPUTE_ERROR, ARM_COMPUTE_ERROR_ON, ARM_COMPUTE_ERROR_ON_MSG, and arm_compute::utils::parse_ppm_header().
Referenced by PPMAccessor::access_tensor().
     {
         ARM_COMPUTE_ERROR_ON(is_open());
         try
         {
             _fs.exceptions(std::ifstream::failbit | std::ifstream::badbit);
             _fs.open(ppm_filename, std::ios::in | std::ios::binary);
             unsigned int max_val = 0;
             std::tie(_width, _height, max_val) = parse_ppm_header(_fs);
             ARM_COMPUTE_ERROR_ON_MSG(max_val >= 256, "2 bytes per colour channel not supported in file %s", ppm_filename.c_str());
         }
         catch(std::runtime_error &e)
         {
             ARM_COMPUTE_ERROR("Accessing %s: %s", ppm_filename.c_str(), e.what());
         }
     }
unsigned int width () const inline
Return the width of the currently open PPM file.
Definition at line 475 of file Utils.h.
Referenced by PPMAccessor::access_tensor().
     {
         return _width;
     }
The documentation for this class was generated from the following file:
utils/Utils.h