Compute Library: NEL2NormalizeLayer Class Reference
NEL2NormalizeLayer Class Reference
Basic function to perform a L2 normalization on a given axis.
#include <NEL2NormalizeLayer.h>
Public Member Functions
NEL2NormalizeLayer (std::shared_ptr< IMemoryManager > memory_manager=nullptr)
Constructor.
void configure (ITensor *input, ITensor *output, int axis, float epsilon=1e-12f)
Set the input and output tensors.
void run () override
Run the kernels contained in the function.
Public Member Functions inherited from IFunction
virtual ~IFunction ()=default
Destructor.
virtual void prepare ()
Prepare the function for executing.
Static Public Member Functions
static Status validate (const ITensorInfo *input, const ITensorInfo *output, int axis, float epsilon=1e-12f)
Static function to check if given info will lead to a valid configuration of NEL2NormalizeLayer.
Detailed Description
Basic function to perform a L2 normalization on a given axis.
This function runs the following kernels:
NEReductionOperation
NEL2NormalizeLayerKernel
Definition at line 46 of file NEL2NormalizeLayer.h.
Constructor & Destructor Documentation
NEL2NormalizeLayer()
NEL2NormalizeLayer (std::shared_ptr< IMemoryManager > memory_manager = nullptr)
Constructor.
Definition at line 36 of file NEL2NormalizeLayer.cpp.
     : _memory_group(std::move(memory_manager)), _reduce_func(), _normalize_kernel(), _sumsq()
 {
 }
Member Function Documentation
configure()
void configure (ITensor * input, ITensor * output, int axis, float epsilon = 1e-12f)
Set the input and output tensors.
Parameters
[in,out] input Source tensor. Data types supported: F16/F32. (Written to only for border_size != 0)
[out] output Destination tensor. Data types and data layouts supported: same as input.
[in] axis Axis along which to reduce. Negative values wrap around. Maximum supported actual reduction axis : 2
[in] epsilon (Optional) Lower bound value for the normalization.
Definition at line 41 of file NEL2NormalizeLayer.cpp.
 {
     // Manage intermediate buffers
     _memory_group.manage(&_sumsq);
     // Configure Kernels
     const uint32_t actual_axis = wrap_around(axis, max_input_tensor_dim);
     _reduce_func.configure(input, &_sumsq, actual_axis, ReductionOperation::SUM_SQUARE);
     _normalize_kernel.configure(input, &_sumsq, output, axis, epsilon);
     // Allocate intermediate tensors
     _sumsq.allocator()->allocate();
 }
References TensorAllocator::allocate(), Tensor::allocator(), arm_compute::test::validation::axis, NEReductionOperation::configure(), NEL2NormalizeLayerKernel::configure(), epsilon, MemoryGroupBase< TensorType >::manage(), arm_compute::SUM_SQUARE, and arm_compute::wrap_around().
run()
void run () override virtual
Run the kernels contained in the function.
For NEON kernels:
Multi-threading is used for the kernels which are parallelisable.
By default std::thread::hardware_concurrency() threads are used.
Note
CPPScheduler::set_num_threads() can be used to manually set the number of threads
For OpenCL kernels:
All the kernels are enqueued on the queue associated with CLScheduler.
The queue is then flushed.
Note
The function will not block until the kernels are executed. It is the user's responsibility to wait.
Will call prepare() on first run if hasn't been done
Implements IFunction.
Definition at line 76 of file NEL2NormalizeLayer.cpp.
 {
     MemoryGroupResourceScope scope_mg(_memory_group);
     _reduce_func.run();
     NEScheduler::get().schedule(&_normalize_kernel, Window::DimY);
 }
References Window::DimY, Scheduler::get(), NEReductionOperation::run(), and IScheduler::schedule().
validate()
Status validate (const ITensorInfo * input, const ITensorInfo * output, int axis, float epsilon = 1e-12f) static
Static function to check if given info will lead to a valid configuration of NEL2NormalizeLayer.
Parameters
[in] input Source tensor info. Data types supported: F16/F32. (Written to only for border_size != 0)
[in] output Destination tensor info. Data types and data layouts supported: same as input.
[in] axis Axis along which to reduce. Negative values wrap around. Maximum supported actual reduction axis : 2
[in] epsilon (Optional) Lower bound value for the normalization.
Returns
a status
Definition at line 55 of file NEL2NormalizeLayer.cpp.
 {
     TensorShape shape(input->tensor_shape());
     // Create intermediate tensor info
     TensorInfo sum_sq;
     sum_sq.set_data_type(input->data_type());
     sum_sq.set_tensor_shape(shape);
     const uint32_t actual_axis = wrap_around(axis, max_input_tensor_dim);
     ARM_COMPUTE_RETURN_ON_ERROR(NEReductionOperation::validate(input, &sum_sq, actual_axis, ReductionOperation::SUM_SQUARE));
     // Reduce shape on axis
     shape.set(actual_axis, 1);
     sum_sq.set_tensor_shape(shape);
     ARM_COMPUTE_RETURN_ON_ERROR(NEL2NormalizeLayerKernel::validate(input, &sum_sq, output, axis, epsilon));
     return Status{};
 }
References ARM_COMPUTE_RETURN_ON_ERROR, arm_compute::test::validation::axis, ITensorInfo::data_type(), epsilon, TensorInfo::set_data_type(), ITensorInfo::set_tensor_shape(), arm_compute::test::validation::shape, arm_compute::SUM_SQUARE, ITensorInfo::tensor_shape(), NEReductionOperation::validate(), NEL2NormalizeLayerKernel::validate(), and arm_compute::wrap_around().
The documentation for this class was generated from the following files:
arm_compute/runtime/NEON/functions/NEL2NormalizeLayer.h
src/runtime/NEON/functions/NEL2NormalizeLayer.cpp