Compute Library: GCTensor Class Reference
GCTensor Class Reference
Interface for OpenGL ES tensor.
#include <GCTensor.h>
Public Member Functions
GCTensor ()
Default constructor.
GCTensor (const GCTensor &)=delete
Prevent instances of this class from being copied (As this class contains pointers).
GCTensor & operator= (const GCTensor &)=delete
Prevent instances of this class from being copy assigned (As this class contains pointers).
GCTensor (GCTensor &&)=default
Allow instances of this class to be moved.
GCTensor & operator= (GCTensor &&)=default
Allow instances of this class to be moved.
virtual ~GCTensor ()=default
Virtual destructor.
ITensorAllocator * allocator ()
Return a pointer to the tensor's allocator.
void map (bool blocking=true)
Enqueue a map operation of the allocated buffer on the given queue.
void unmap ()
Enqueue an unmap operation of the allocated and mapped buffer on the given queue.
TensorInfo * info () const override
Interface to be implemented by the child class to return the tensor's metadata.
TensorInfo * info () override
Interface to be implemented by the child class to return the tensor's metadata.
uint8_t * buffer () const override
Interface to be implemented by the child class to return a pointer to CPU memory.
GLuint gc_buffer () const override
Interface to be implemented by the child class to return the tensor's gles compute buffer id.
Public Member Functions inherited from IGCTensor
IGCTensor ()
Default constructor.
IGCTensor (const IGCTensor &)=delete
Prevent instances of this class from being copied (As this class contains pointers).
IGCTensor & operator= (const IGCTensor &)=delete
Prevent instances of this class from being copy assigned (As this class contains pointers).
IGCTensor (IGCTensor &&)=default
Allow instances of this class to be moved.
IGCTensor & operator= (IGCTensor &&)=default
Allow instances of this class to be moved.
virtual ~IGCTensor ()=default
Virtual destructor.
void map (bool blocking=true)
Map on an allocated buffer.
void unmap ()
Unmap an allocated and mapped buffer.
void clear ()
Clear the contents of the tensor synchronously.
Public Member Functions inherited from ITensor
virtual ~ITensor ()=default
Default virtual destructor.
uint8_t * ptr_to_element (const Coordinates &id) const
Return a pointer to the element at the passed coordinates.
void copy_from (const ITensor &src)
Copy the content of another tensor.
void print (std::ostream &s, IOFormatInfo io_fmt=IOFormatInfo()) const
Print a tensor to a given stream using user defined formatting information.
Detailed Description
Interface for OpenGL ES tensor.
Definition at line 37 of file GCTensor.h.
Constructor & Destructor Documentation
GCTensor ()
Default constructor.
GCTensor (const GCTensor &) delete
Prevent instances of this class from being copied (As this class contains pointers).
GCTensor (GCTensor &&) default
Allow instances of this class to be moved.
virtual ~GCTensor () virtual default
Virtual destructor.
Member Function Documentation
ITensorAllocator* allocator ()
Return a pointer to the tensor's allocator.
Returns
A pointer to the tensor's allocator
Referenced by arm_compute::test::gles_compute::create_tensor().
uint8_t* buffer () const override virtual
Interface to be implemented by the child class to return a pointer to CPU memory.
Returns
A CPU pointer to the beginning of the image's allocation.
Reimplemented from IGCTensor.
GLuint gc_buffer () const override virtual
Interface to be implemented by the child class to return the tensor's gles compute buffer id.
Returns
A SSBO buffer id.
Implements IGCTensor.
TensorInfo* info () const override virtual
Interface to be implemented by the child class to return the tensor's metadata.
Returns
A pointer to the tensor's metadata.
Implements ITensor.
Referenced by arm_compute::test::validation::DATA_TEST_CASE(), GCAccessor::data_type(), GCAccessor::element_size(), GCAccessor::fixed_point_position(), GCAccessor::format(), GCAccessor::num_channels(), GCAccessor::num_elements(), GCAccessor::padding(), GCAccessor::quantization_info(), GCAccessor::shape(), and GCAccessor::size().
TensorInfo* info () override virtual
Interface to be implemented by the child class to return the tensor's metadata.
Returns
A pointer to the tensor's metadata.
Implements ITensor.
void map (bool blocking = true)
Enqueue a map operation of the allocated buffer on the given queue.
Parameters
[in] blocking (Optional) If true, then the mapping will be ready to use by the time this method returns, else it is the caller's responsibility to flush the queue and wait for the mapping operation to have completed before using the returned mapping pointer.
Returns
The mapping address.
Referenced by GCAccessor::GCAccessor(), and arm_compute::utils::unmap().
GCTensor& operator= (const GCTensor &) delete
Prevent instances of this class from being copy assigned (As this class contains pointers).
GCTensor& operator= (GCTensor &&) default
Allow instances of this class to be moved.
void unmap ()
Enqueue an unmap operation of the allocated and mapped buffer on the given queue.
Note
This method simply enqueues the unmap operation, it is the caller's responsibility to flush the queue and make sure the unmap is finished before the memory is accessed by the device.
Referenced by arm_compute::utils::unmap(), and GCAccessor::~GCAccessor().
The documentation for this class was generated from the following file:
arm_compute/runtime/GLES_COMPUTE/GCTensor.h