Compute Library: CLFastCorners Class Reference
CLFastCorners Class Reference
Basic function to execute fast corners.
#include <CLFastCorners.h>
Public Member Functions
CLFastCorners (std::shared_ptr< IMemoryManager > memory_manager=nullptr)
Constructor.
CLFastCorners (const CLFastCorners &)=delete
Prevent instances of this class from being copied (As this class contains pointers)
const CLFastCorners & operator= (const CLFastCorners &)=delete
Prevent instances of this class from being copied (As this class contains pointers)
void configure (const ICLImage *input, float threshold, bool nonmax_suppression, ICLKeyPointArray *corners, unsigned int *num_corners, BorderMode border_mode, uint8_t constant_border_value=0)
Initialize the function's source, destination, conv and border_mode.
void run () override
Run the kernels contained in the function.
Public Member Functions inherited from IFunction
virtual ~IFunction ()=default
Destructor.
virtual void prepare ()
Prepare the function for executing.
Detailed Description
Basic function to execute fast corners.
This function calls the following CL kernels:
CLFastCornersKernel
CLNonMaximaSuppression3x3Kernel (executed if nonmax_suppression == true)
CLCopyToArrayKernel
Definition at line 53 of file CLFastCorners.h.
Constructor & Destructor Documentation
CLFastCorners() [1/2]
CLFastCorners (std::shared_ptr< IMemoryManager > memory_manager = nullptr)
Constructor.
Definition at line 39 of file CLFastCorners.cpp.
     : _memory_group(std::move(memory_manager)),
       _fast_corners_kernel(),
       _suppr_func(),
       _copy_array_kernel(),
       _output(),
       _suppr(),
       _win(),
       _non_max(false),
       _num_corners(nullptr),
       _num_buffer(),
       _corners(nullptr),
       _constant_border_value(0)
 {
 }
CLFastCorners() [2/2]
CLFastCorners (const CLFastCorners &) delete
Prevent instances of this class from being copied (As this class contains pointers)
Member Function Documentation
configure()
void configure (const ICLImage * input, float threshold, bool nonmax_suppression, ICLKeyPointArray * corners, unsigned int * num_corners, BorderMode border_mode, uint8_t constant_border_value = 0)
Initialize the function's source, destination, conv and border_mode.
Parameters
[in] input Source image. Data types supported: U8.
[in] threshold Threshold on difference between intensity of the central pixel and pixels on Bresenham's circle of radius 3.
[in] nonmax_suppression If true, non-maximum suppression is applied to detected corners before being placed in the array.
[out] corners Array of keypoints to store the results.
[in,out] num_corners Record number of corners in the array
[in] border_mode Strategy to use for borders.
[in] constant_border_value (Optional) Constant value to use for borders if border_mode is set to CONSTANT.
Definition at line 55 of file CLFastCorners.cpp.
 {
     ARM_COMPUTE_ERROR_ON_TENSOR_NOT_2D(input);
     ARM_COMPUTE_ERROR_ON(BorderMode::UNDEFINED != border_mode);
     ARM_COMPUTE_ERROR_ON(nullptr == corners);
     ARM_COMPUTE_ERROR_ON(threshold < 1 && threshold > 255);
     TensorInfo tensor_info(input->info()->tensor_shape(), 1, DataType::U8);
     _output.allocator()->init(tensor_info);
     _non_max               = nonmax_suppression;
     _num_corners           = num_corners;
     _corners               = corners;
     _num_buffer            = cl::Buffer(CLScheduler::get().context(), CL_MEM_ALLOC_HOST_PTR | CL_MEM_READ_WRITE, sizeof(unsigned int));
     _constant_border_value = constant_border_value;
     const bool update_number = (nullptr != _num_corners);
     _memory_group.manage(&_output);
     _fast_corners_kernel.configure(input, &_output, threshold, nonmax_suppression, border_mode);
     if(!_non_max)
     {
         _copy_array_kernel.configure(&_output, update_number, _corners, &_num_buffer);
     }
     else
     {
         _suppr.allocator()->init(tensor_info);
         _memory_group.manage(&_suppr);
         _suppr_func.configure(&_output, &_suppr, border_mode);
         _copy_array_kernel.configure(&_suppr, update_number, _corners, &_num_buffer);
         _suppr.allocator()->allocate();
     }
     // Allocate intermediate tensors
     _output.allocator()->allocate();
 }
References CLTensorAllocator::allocate(), CLTensor::allocator(), ARM_COMPUTE_ERROR_ON, ARM_COMPUTE_ERROR_ON_TENSOR_NOT_2D, arm_compute::test::validation::border_mode, CLNonMaximaSuppression3x3::configure(), CLFastCornersKernel::configure(), CLCopyToArrayKernel::configure(), CLScheduler::get(), ITensor::info(), ITensorAllocator::init(), MemoryGroupBase< TensorType >::manage(), ITensorInfo::tensor_shape(), arm_compute::test::validation::reference::threshold(), arm_compute::U8, and arm_compute::UNDEFINED.
operator=()
const CLFastCorners& operator= (const CLFastCorners &) delete
Prevent instances of this class from being copied (As this class contains pointers)
run()
void run () override virtual
Run the kernels contained in the function.
For NEON kernels:
Multi-threading is used for the kernels which are parallelisable.
By default std::thread::hardware_concurrency() threads are used.
Note
CPPScheduler::set_num_threads() can be used to manually set the number of threads
For OpenCL kernels:
All the kernels are enqueued on the queue associated with CLScheduler.
The queue is then flushed.
Note
The function will not block until the kernels are executed. It is the user's responsibility to wait.
Will call prepare() on first run if hasn't been done
Implements IFunction.
Definition at line 96 of file CLFastCorners.cpp.
 {
     cl::CommandQueue q = CLScheduler::get().queue();
     _memory_group.acquire();
     if(_non_max)
     {
         ARM_COMPUTE_ERROR_ON_MSG(_output.cl_buffer().get() == nullptr, "Unconfigured function");
         const auto out_buffer = static_cast<unsigned char *>(q.enqueueMapBuffer(_output.cl_buffer(), CL_TRUE, CL_MAP_WRITE, 0, _output.info()->total_size()));
         memset(out_buffer, 0, _output.info()->total_size());
         q.enqueueUnmapMemObject(_output.cl_buffer(), out_buffer);
     }
     CLScheduler::get().enqueue(_fast_corners_kernel, false);
     if(_non_max)
     {
         _suppr_func.run();
     }
     CLScheduler::get().enqueue(_copy_array_kernel, false);
     unsigned int get_num_corners = 0;
     q.enqueueReadBuffer(_num_buffer, CL_TRUE, 0, sizeof(unsigned int), &get_num_corners);
     size_t corner_size = std::min(static_cast<size_t>(get_num_corners), _corners->max_num_values());
     _corners->resize(corner_size);
     if(_num_corners != nullptr)
     {
         *_num_corners = get_num_corners;
     }
     q.flush();
     _memory_group.release();
 }
References MemoryGroupBase< TensorType >::acquire(), ARM_COMPUTE_ERROR_ON_MSG, CLTensor::cl_buffer(), CLScheduler::enqueue(), CLScheduler::get(), CLTensor::info(), IArray< T >::max_num_values(), CLScheduler::queue(), MemoryGroupBase< TensorType >::release(), IArray< T >::resize(), ICLSimpleFunction::run(), and TensorInfo::total_size().
The documentation for this class was generated from the following files:
arm_compute/runtime/CL/functions/CLFastCorners.h
src/runtime/CL/functions/CLFastCorners.cpp