Compute Library: IDistribution1D Class Reference
IDistribution1D Class Reference
1D Distribution interface
#include <IDistribution1D.h>
Public Member Functions
IDistribution1D (size_t num_bins, int32_t offset, uint32_t range)
Constructor: Creates a 1D Distribution of a consecutive interval [offset, offset + range - 1] defined by a start offset and valid range, divided equally into num_bins parts.
size_t num_bins () const
Returns the number of bins that the distribution has.
int32_t offset () const
Returns the offset of the distribution.
uint32_t range () const
Returns the range of the distribution.
uint32_t window () const
Returns the window of the distribution, which is the range divided by the number of bins.
void set_range (uint32_t range)
Sets the range of the distribution.
size_t size () const override
Returns the total size in bytes of the distribution.
size_t dimensions () const override
Returns the dimensions of the distribution.
Public Member Functions inherited from IDistribution
virtual ~IDistribution ()=default
Default virtual destructor.
virtual uint32_t * buffer () const =0
Returns a pointer to the start of the distribution.
void clear () const
Clears the distribution by setting every element to zero.
Detailed Description
1D Distribution interface
Definition at line 35 of file IDistribution1D.h.
Constructor & Destructor Documentation
IDistribution1D()
IDistribution1D (size_t num_bins, int32_t offset, uint32_t range)
Constructor: Creates a 1D Distribution of a consecutive interval [offset, offset + range - 1] defined by a start offset and valid range, divided equally into num_bins parts.
Parameters
[in] num_bins The number of bins the distribution is divided in.
[in] offset The start of the values to use.
[in] range The total number of the consecutive values of the distribution interval.
Definition at line 30 of file IDistribution1D.cpp.
     : _num_bins(num_bins), _offset(offset), _range(range)
 {
     ARM_COMPUTE_ERROR_ON_MSG(0 == _num_bins, "Invalid number of bins, it should be greater than 0");
 }
References ARM_COMPUTE_ERROR_ON_MSG.
Member Function Documentation
dimensions()
size_t dimensions () const override virtual
Returns the dimensions of the distribution.
Note
This is fixed to 1-dimensional distribution for now.
Returns
Dimensions of the distribution.
Implements IDistribution.
Definition at line 66 of file IDistribution1D.cpp.
 {
     return 1;
 }
num_bins()
size_t num_bins () const
Returns the number of bins that the distribution has.
Returns
Number of bins of the distribution.
Definition at line 36 of file IDistribution1D.cpp.
 {
     return _num_bins;
 }
Referenced by NEHistogram::configure(), CLHistogramKernel::configure(), NECumulativeDistributionKernel::configure(), CLHistogramBorderKernel::configure(), and NECumulativeDistributionKernel::run().
offset()
int32_t offset () const
Returns the offset of the distribution.
Returns
Offset of the distribution.
Definition at line 41 of file IDistribution1D.cpp.
 {
     return _offset;
 }
Referenced by CLHistogramKernel::configure(), NEHistogramKernel::configure(), and CLHistogramBorderKernel::configure().
range()
uint32_t range () const
Returns the range of the distribution.
Returns
Range of the distribution.
Definition at line 46 of file IDistribution1D.cpp.
 {
     return _range;
 }
Referenced by CLHistogramKernel::configure(), NEHistogramKernel::configure(), CLHistogramBorderKernel::configure(), and IDistribution1D::set_range().
set_range()
void set_range (uint32_t range)
Sets the range of the distribution.
Parameters
[in] range New range of the distribution to be set.
Definition at line 61 of file IDistribution1D.cpp.
 {
     _range = range;
 }
References IDistribution1D::range().
size()
size_t size () const override virtual
Returns the total size in bytes of the distribution.
Returns
Total size of the distribution in bytes.
Implements IDistribution.
Definition at line 56 of file IDistribution1D.cpp.
 {
     return _num_bins * sizeof(uint32_t);
 }
Referenced by CLHistogramKernel::configure(), and CLHistogramKernel::run().
window()
uint32_t window () const
Returns the window of the distribution, which is the range divided by the number of bins.
Note
If range is not divided by the number of bins then it is invalid.
Returns
Window of the distribution.
Definition at line 51 of file IDistribution1D.cpp.
 {
     return _range / _num_bins;
 }
Referenced by CLHistogramKernel::configure(), and CLHistogramBorderKernel::configure().
The documentation for this class was generated from the following files:
arm_compute/core/IDistribution1D.h
src/core/IDistribution1D.cpp