Compute Library: CLElementWiseUnaryLayerKernel Class Reference
CLElementWiseUnaryLayerKernel Class Reference
Interface for the elementwise unary operator.
#include <CLElementWiseUnaryLayerKernel.h>
Public Member Functions
void configure (const ICLTensor *input, ICLTensor *output, const ElementWiseUnary &op)
Initialise the kernel's inputs, output.
void run (const Window &window, cl::CommandQueue &queue) override
Enqueue the OpenCL kernel to process the given window on the passed OpenCL command queue.
Public Member Functions inherited from ICLSimpleKernel
ICLSimpleKernel ()
Constructor.
ICLSimpleKernel (const ICLSimpleKernel &)=delete
Prevent instances of this class from being copied (As this class contains pointers)
ICLSimpleKernel & operator= (const ICLSimpleKernel &)=delete
Prevent instances of this class from being copied (As this class contains pointers)
ICLSimpleKernel (ICLSimpleKernel &&)=default
Allow instances of this class to be moved.
ICLSimpleKernel & operator= (ICLSimpleKernel &&)=default
Allow instances of this class to be moved.
~ICLSimpleKernel ()=default
Default destructor.
void configure (const ICLTensor *input, ICLTensor *output, unsigned int num_elems_processed_per_iteration, bool border_undefined=false, const BorderSize &border_size=BorderSize())
Configure the kernel.
Public Member Functions inherited from ICLKernel
ICLKernel ()
Constructor.
cl::Kernel & kernel ()
Returns a reference to the OpenCL kernel of this object.
template<typename T >
void add_1D_array_argument (unsigned int &idx, const ICLArray< T > *array, const Strides &strides, unsigned int num_dimensions, const Window &window)
Add the passed 1D array's parameters to the object's kernel's arguments starting from the index idx.
void add_1D_tensor_argument (unsigned int &idx, const ICLTensor *tensor, const Window &window)
Add the passed 1D tensor's parameters to the object's kernel's arguments starting from the index idx.
void add_2D_tensor_argument (unsigned int &idx, const ICLTensor *tensor, const Window &window)
Add the passed 2D tensor's parameters to the object's kernel's arguments starting from the index idx.
void add_3D_tensor_argument (unsigned int &idx, const ICLTensor *tensor, const Window &window)
Add the passed 3D tensor's parameters to the object's kernel's arguments starting from the index idx.
void add_4D_tensor_argument (unsigned int &idx, const ICLTensor *tensor, const Window &window)
Add the passed 4D tensor's parameters to the object's kernel's arguments starting from the index idx.
template<typename T >
void add_argument (unsigned int &idx, T value)
Add the passed parameters to the object's kernel's arguments starting from the index idx.
void set_lws_hint (const cl::NDRange &lws_hint)
Set the Local-Workgroup-Size hint.
cl::NDRange lws_hint () const
Return the Local-Workgroup-Size hint.
const std::string & config_id () const
Get the configuration ID.
void set_target (GPUTarget target)
Set the targeted GPU architecture.
void set_target (cl::Device &device)
Set the targeted GPU architecture according to the CL device.
GPUTarget get_target () const
Get the targeted GPU architecture.
size_t get_max_workgroup_size ()
Get the maximum workgroup size for the device the CLKernelLibrary uses.
template<typename T , unsigned int dimension_size>
void add_array_argument (unsigned &idx, const ICLArray< T > *array, const Strides &strides, unsigned int num_dimensions, const Window &window)
Add the passed array's parameters to the object's kernel's arguments starting from the index idx.
template<unsigned int dimension_size>
void add_tensor_argument (unsigned &idx, const ICLTensor *tensor, const Window &window)
Public Member Functions inherited from IKernel
IKernel ()
Constructor.
virtual ~IKernel ()=default
Destructor.
virtual bool is_parallelisable () const
Indicates whether or not the kernel is parallelisable.
virtual BorderSize border_size () const
The size of the border for that kernel.
const Window & window () const
The maximum window the kernel can be executed on.
Static Public Member Functions
static Status validate (const ITensorInfo *input, const ITensorInfo *output, const ElementWiseUnary &op)
Static function to check if given info will lead to a valid configuration of CLElementWiseUnaryLayerKernel.
Static Public Member Functions inherited from ICLKernel
static constexpr unsigned int num_arguments_per_1D_array ()
Returns the number of arguments enqueued per 1D array object.
static constexpr unsigned int num_arguments_per_1D_tensor ()
Returns the number of arguments enqueued per 1D tensor object.
static constexpr unsigned int num_arguments_per_2D_tensor ()
Returns the number of arguments enqueued per 2D tensor object.
static constexpr unsigned int num_arguments_per_3D_tensor ()
Returns the number of arguments enqueued per 3D tensor object.
static constexpr unsigned int num_arguments_per_4D_tensor ()
Returns the number of arguments enqueued per 4D tensor object.
static cl::NDRange gws_from_window (const Window &window)
Get the global work size given an execution window.
Detailed Description
Interface for the elementwise unary operator.
Definition at line 36 of file CLElementWiseUnaryLayerKernel.h.
Member Function Documentation
configure()
void configure (const ICLTensor * input, ICLTensor * output, const ElementWiseUnary & op)
Initialise the kernel's inputs, output.
Parameters
[in] input First tensor input. Data types supported: F16/F32.
[out] output Output tensor. Data types supported: Same as input.
[in] op Element wise unary operation to perform.
Definition at line 52 of file CLElementWiseUnaryLayerKernel.cpp.
 {
     ARM_COMPUTE_ERROR_ON_NULLPTR(input, output);
     ARM_COMPUTE_ERROR_THROW_ON(validate_arguments(*input->info(), *output->info()));
     // Configure kernel window
     _input  = input;
     _output = output;
     const std::string kernel_name    = "elementwise_unary";
     const int         vec_size_x     = 16 / output->info()->element_size();
     const int         output_width_x = output->info()->tensor_shape().x();
     const bool        multi_access_x = (output_width_x / vec_size_x > 0);
     Window win = calculate_max_window(*output->info());
     if(multi_access_x)
     {
         win.set(Window::DimX,
                 Window::Dimension(win.x().start(), ceil_to_multiple(win.x().end(), vec_size_x), vec_size_x));
     }
     ICLKernel::configure_internal(win);
     // Set kernel build options
     CLBuildOptions build_opts;
     build_opts.add_option("-DDATA_TYPE=" + get_cl_type_from_data_type(input->info()->data_type()));
     build_opts.add_option_if(multi_access_x, "-DVEC_SIZE=" + support::cpp11::to_string(vec_size_x));
     build_opts.add_option_if(multi_access_x, "-DLAST_ACCESSED_X=" + support::cpp11::to_string(std::max<int>(output_width_x - vec_size_x, 0)));
     switch(op)
     {
         case ElementWiseUnary::RSQRT:
             build_opts.add_option("-DOPERATION=inverse_sqrt");
             break;
         case ElementWiseUnary::EXP:
             build_opts.add_option("-DOPERATION=exponential");
             break;
         default:
             ARM_COMPUTE_ERROR("Not implemented");
     }
     // Create kernel
     _kernel = static_cast<cl::Kernel>(CLKernelLibrary::get().create_kernel(kernel_name, build_opts.options()));
 }
References CLBuildOptions::add_option(), CLBuildOptions::add_option_if(), ARM_COMPUTE_ERROR, ARM_COMPUTE_ERROR_ON_NULLPTR, ARM_COMPUTE_ERROR_THROW_ON, arm_compute::calculate_max_window(), arm_compute::ceil_to_multiple(), arm_compute::create_kernel(), ITensorInfo::data_type(), Window::DimX, ITensorInfo::element_size(), Window::Dimension::end(), arm_compute::EXP, CLKernelLibrary::get(), arm_compute::get_cl_type_from_data_type(), ITensor::info(), CLBuildOptions::options(), arm_compute::RSQRT, Window::set(), Window::Dimension::start(), ITensorInfo::tensor_shape(), arm_compute::support::cpp11::to_string(), Dimensions< T >::x(), and Window::x().
run()
void run (const Window & window, cl::CommandQueue & queue) override virtual
Enqueue the OpenCL kernel to process the given window on the passed OpenCL command queue.
Note
The queue is not flushed by this method, and therefore the kernel will not have been executed by the time this method returns.
Parameters
[in] window Region on which to execute the kernel. (Must be a valid region of the window returned by window()).
[in,out] queue Command queue on which to enqueue the kernel.
Implements ICLKernel.
Definition at line 104 of file CLElementWiseUnaryLayerKernel.cpp.
 {
     ARM_COMPUTE_ERROR_ON_UNCONFIGURED_KERNEL(this);
     ARM_COMPUTE_ERROR_ON_INVALID_SUBWINDOW(ICLKernel::window(), window);
     Window collapsed = window.collapse_if_possible(ICLKernel::window(), Window::DimX);
     do
     {
         unsigned int idx = 0;
         add_1D_tensor_argument(idx, _input, collapsed);
         add_1D_tensor_argument(idx, _output, collapsed);
         enqueue(queue, *this, collapsed);
     }
     while(window.slide_window_slice_1D(collapsed));
 }
References ICLKernel::add_1D_tensor_argument(), ARM_COMPUTE_ERROR_ON_INVALID_SUBWINDOW, ARM_COMPUTE_ERROR_ON_UNCONFIGURED_KERNEL, Window::collapse_if_possible(), Window::DimX, arm_compute::enqueue(), Window::slide_window_slice_1D(), and IKernel::window().
validate()
Status validate (const ITensorInfo * input, const ITensorInfo * output, const ElementWiseUnary & op) static
Static function to check if given info will lead to a valid configuration of CLElementWiseUnaryLayerKernel.
Parameters
[in] input First tensor input info. Data types supported: F16/F32.
[in] output Output tensor info. Data types supported: Same as input.
[in] op Element wise unary operation to perform.
Returns
a status
Definition at line 95 of file CLElementWiseUnaryLayerKernel.cpp.
 {
     ARM_COMPUTE_UNUSED(op);
     ARM_COMPUTE_RETURN_ERROR_ON_NULLPTR(input, output);
     ARM_COMPUTE_RETURN_ON_ERROR(validate_arguments(*input, *output));
     return Status{};
 }
References ARM_COMPUTE_RETURN_ERROR_ON_NULLPTR, ARM_COMPUTE_RETURN_ON_ERROR, and ARM_COMPUTE_UNUSED.
Referenced by CLRsqrtLayer::validate(), and CLExpLayer::validate().
The documentation for this class was generated from the following files:
arm_compute/core/CL/kernels/CLElementWiseUnaryLayerKernel.h
src/core/CL/kernels/CLElementWiseUnaryLayerKernel.cpp