Compute Library: GCDropoutLayer Class Reference
GCDropoutLayer Class Reference
Basic function to do dropout op.
#include <GCDropoutLayer.h>
Public Member Functions
GCDropoutLayer ()
Constructor.
void configure (const IGCTensor *input, IGCTensor *mask, IGCTensor *output, float ratio, bool forward)
Set the input and output tensors.
void run () override
Run the kernels contained in the function.
Public Member Functions inherited from IFunction
virtual ~IFunction ()=default
Destructor.
virtual void prepare ()
Prepare the function for executing.
Detailed Description
Basic function to do dropout op.
This function calls the following kernels:
GCDropoutLayerKernel
Definition at line 38 of file GCDropoutLayer.h.
Constructor & Destructor Documentation
GCDropoutLayer()
GCDropoutLayer ()
Constructor.
Definition at line 33 of file GCDropoutLayer.cpp.
     : _dropout_kernel()
 {
 }
Member Function Documentation
configure()
void configure (const IGCTensor * input, IGCTensor * mask, IGCTensor * output, float ratio, bool forward)
Set the input and output tensors.
Parameters
[in] input Source tensor. Data type supported: F16/F32.
[out] mask Destination tensor. Data type supported: Same as input.
[out] output Destination tensor. Data type supported: Same as input.
[in] ratio Dropout ratio
[in] forward Forward or backward propagation
Definition at line 38 of file GCDropoutLayer.cpp.
 {
     ARM_COMPUTE_ERROR_ON_DATA_TYPE_CHANNEL_NOT_IN(input, 1, DataType::F16, DataType::F32);
     ARM_COMPUTE_ERROR_ON_MISMATCHING_DATA_TYPES(input, mask, output);
     // Configure kernel
     _dropout_kernel.configure(input, mask, output, ratio, forward);
 }
References ARM_COMPUTE_ERROR_ON_DATA_TYPE_CHANNEL_NOT_IN, ARM_COMPUTE_ERROR_ON_MISMATCHING_DATA_TYPES, GCDropoutLayerKernel::configure(), arm_compute::F16, arm_compute::F32, and arm_compute::test::validation::forward.
run()
void run () override virtual
Run the kernels contained in the function.
For NEON kernels:
Multi-threading is used for the kernels which are parallelisable.
By default std::thread::hardware_concurrency() threads are used.
Note
CPPScheduler::set_num_threads() can be used to manually set the number of threads
For OpenCL kernels:
All the kernels are enqueued on the queue associated with CLScheduler.
The queue is then flushed.
Note
The function will not block until the kernels are executed. It is the user's responsibility to wait.
Will call prepare() on first run if hasn't been done
Implements IFunction.
Definition at line 47 of file GCDropoutLayer.cpp.
 {
     GCScheduler::get().dispatch(_dropout_kernel);
 }
References GCScheduler::dispatch(), and GCScheduler::get().
The documentation for this class was generated from the following files:
arm_compute/runtime/GLES_COMPUTE/functions/GCDropoutLayer.h
src/runtime/GLES_COMPUTE/functions/GCDropoutLayer.cpp