Compute Library: FileHandler Class Reference
FileHandler Class Reference
File Handling interface.
#include <FileHandler.h>
Public Member Functions
FileHandler ()
Default Constructor.
~FileHandler ()
Default Destructor.
FileHandler (FileHandler &&)=default
Allow instances of this class to be moved.
FileHandler (const FileHandler &)=delete
Prevent instances of this class from being copied (As this class contains pointers)
FileHandler & operator= (const FileHandler &)=delete
Prevent instances of this class from being copied (As this class contains pointers)
FileHandler & operator= (FileHandler &&)=default
Allow instances of this class to be moved.
void open (const std::string &filename, std::ios_base::openmode mode)
Opens file.
void close ()
Closes file.
std::fstream & stream ()
Returns the file stream.
std::string filename () const
Returns filename of the handled file.
Detailed Description
File Handling interface.
Definition at line 35 of file FileHandler.h.
Constructor & Destructor Documentation
FileHandler() [1/3]
FileHandler ()
Default Constructor.
Definition at line 33 of file FileHandler.cpp.
     : _filestream(), _filename(" "), _mode()
 {
 }
~FileHandler()
~FileHandler ()
Default Destructor.
Definition at line 38 of file FileHandler.cpp.
 {
     close();
 }
References FileHandler::close().
FileHandler() [2/3]
FileHandler (FileHandler &&) default
Allow instances of this class to be moved.
FileHandler() [3/3]
FileHandler (const FileHandler &) delete
Prevent instances of this class from being copied (As this class contains pointers)
Member Function Documentation
close()
void close ()
Closes file.
Definition at line 53 of file FileHandler.cpp.
 {
     _filestream.close();
 }
Referenced by FileHandler::open(), and FileHandler::~FileHandler().
filename()
std::string filename () const
Returns filename of the handled file.
Returns
File filename
Definition at line 63 of file FileHandler.cpp.
 {
     return _filename;
 }
Referenced by FileHandler::open().
open()
void open (const std::string & filename, std::ios_base::openmode mode)
Opens file.
Parameters
[in] filename File name
[in] mode File open mode
Definition at line 43 of file FileHandler.cpp.
 {
     close();
     ;
     _filestream.open(filename, mode);
     ARM_COMPUTE_ERROR_ON(!_filestream.good());
     _filename = filename;
     _mode     = mode;
 }
References ARM_COMPUTE_ERROR_ON, FileHandler::close(), and FileHandler::filename().
Referenced by FilePrinter::FilePrinter().
operator=() [1/2]
FileHandler& operator= (const FileHandler &) delete
Prevent instances of this class from being copied (As this class contains pointers)
operator=() [2/2]
FileHandler& operator= (FileHandler &&) default
Allow instances of this class to be moved.
stream()
std::fstream & stream ()
Returns the file stream.
Returns
File stream
Definition at line 58 of file FileHandler.cpp.
 {
     return _filestream;
 }
The documentation for this class was generated from the following files:
arm_compute/core/utils/io/FileHandler.h
src/core/utils/io/FileHandler.cpp