Compute Library: CLWinogradFilterTransformKernel Class Reference
CLWinogradFilterTransformKernel Class Reference
Interface for the Winograd filter transform kernel.
#include <CLWinogradFilterTransformKernel.h>
Public Member Functions
CLWinogradFilterTransformKernel ()
Default constructor.
CLWinogradFilterTransformKernel (const CLWinogradFilterTransformKernel &)=delete
Prevent instances of this class from being copied (As this class contains pointers)
CLWinogradFilterTransformKernel & operator= (const CLWinogradFilterTransformKernel &)=delete
Prevent instances of this class from being copied (As this class contains pointers)
CLWinogradFilterTransformKernel (CLWinogradFilterTransformKernel &&)=default
Allow instances of this class to be moved.
CLWinogradFilterTransformKernel & operator= (CLWinogradFilterTransformKernel &&)=default
Allow instances of this class to be moved.
~CLWinogradFilterTransformKernel ()=default
Default destructor.
void configure (const ICLTensor *input, ICLTensor *output, const WinogradInfo &winograd_info)
Set the input and output tensor.
void run (const Window &window, cl::CommandQueue &queue) override
Enqueue the OpenCL kernel to process the given window on the passed OpenCL command queue.
Public Member Functions inherited from ICLKernel
ICLKernel ()
Constructor.
cl::Kernel & kernel ()
Returns a reference to the OpenCL kernel of this object.
template<typename T >
void add_1D_array_argument (unsigned int &idx, const ICLArray< T > *array, const Strides &strides, unsigned int num_dimensions, const Window &window)
Add the passed 1D array's parameters to the object's kernel's arguments starting from the index idx.
void add_1D_tensor_argument (unsigned int &idx, const ICLTensor *tensor, const Window &window)
Add the passed 1D tensor's parameters to the object's kernel's arguments starting from the index idx.
void add_1D_tensor_argument_if (bool cond, unsigned int &idx, const ICLTensor *tensor, const Window &window)
Add the passed 1D tensor's parameters to the object's kernel's arguments starting from the index idx if the condition is true.
void add_2D_tensor_argument (unsigned int &idx, const ICLTensor *tensor, const Window &window)
Add the passed 2D tensor's parameters to the object's kernel's arguments starting from the index idx.
void add_2D_tensor_argument_if (bool cond, unsigned int &idx, const ICLTensor *tensor, const Window &window)
Add the passed 2D tensor's parameters to the object's kernel's arguments starting from the index idx if the condition is true.
void add_3D_tensor_argument (unsigned int &idx, const ICLTensor *tensor, const Window &window)
Add the passed 3D tensor's parameters to the object's kernel's arguments starting from the index idx.
void add_4D_tensor_argument (unsigned int &idx, const ICLTensor *tensor, const Window &window)
Add the passed 4D tensor's parameters to the object's kernel's arguments starting from the index idx.
template<typename T >
void add_argument (unsigned int &idx, T value)
Add the passed parameters to the object's kernel's arguments starting from the index idx.
void set_lws_hint (const cl::NDRange &lws_hint)
Set the Local-Workgroup-Size hint.
cl::NDRange lws_hint () const
Return the Local-Workgroup-Size hint.
const std::string & config_id () const
Get the configuration ID.
void set_target (GPUTarget target)
Set the targeted GPU architecture.
void set_target (cl::Device &device)
Set the targeted GPU architecture according to the CL device.
GPUTarget get_target () const
Get the targeted GPU architecture.
size_t get_max_workgroup_size ()
Get the maximum workgroup size for the device the CLKernelLibrary uses.
template<typename T , unsigned int dimension_size>
void add_array_argument (unsigned &idx, const ICLArray< T > *array, const Strides &strides, unsigned int num_dimensions, const Window &window)
Add the passed array's parameters to the object's kernel's arguments starting from the index idx.
template<unsigned int dimension_size>
void add_tensor_argument (unsigned &idx, const ICLTensor *tensor, const Window &window)
Public Member Functions inherited from IKernel
IKernel ()
Constructor.
virtual ~IKernel ()=default
Destructor.
virtual bool is_parallelisable () const
Indicates whether or not the kernel is parallelisable.
virtual BorderSize border_size () const
The size of the border for that kernel.
const Window & window () const
The maximum window the kernel can be executed on.
Static Public Member Functions
static Status validate (const ITensorInfo *input, const ITensorInfo *output, const WinogradInfo &winograd_info)
Static function to check if given info will lead to a valid configuration of CLWinogradFilterTransformKernel.
Static Public Member Functions inherited from ICLKernel
static constexpr unsigned int num_arguments_per_1D_array ()
Returns the number of arguments enqueued per 1D array object.
static constexpr unsigned int num_arguments_per_1D_tensor ()
Returns the number of arguments enqueued per 1D tensor object.
static constexpr unsigned int num_arguments_per_2D_tensor ()
Returns the number of arguments enqueued per 2D tensor object.
static constexpr unsigned int num_arguments_per_3D_tensor ()
Returns the number of arguments enqueued per 3D tensor object.
static constexpr unsigned int num_arguments_per_4D_tensor ()
Returns the number of arguments enqueued per 4D tensor object.
static cl::NDRange gws_from_window (const Window &window)
Get the global work size given an execution window.
Detailed Description
Interface for the Winograd filter transform kernel.
Definition at line 34 of file CLWinogradFilterTransformKernel.h.
Constructor & Destructor Documentation
CLWinogradFilterTransformKernel() [1/3]
CLWinogradFilterTransformKernel ()
Default constructor.
Definition at line 97 of file CLWinogradFilterTransformKernel.cpp.
     : _input(nullptr), _output(nullptr)
 {
 }
CLWinogradFilterTransformKernel() [2/3]
CLWinogradFilterTransformKernel (const CLWinogradFilterTransformKernel &) delete
Prevent instances of this class from being copied (As this class contains pointers)
CLWinogradFilterTransformKernel() [3/3]
CLWinogradFilterTransformKernel (CLWinogradFilterTransformKernel &&) default
Allow instances of this class to be moved.
~CLWinogradFilterTransformKernel()
~CLWinogradFilterTransformKernel () default
Default destructor.
Member Function Documentation
configure()
void configure (const ICLTensor * input, ICLTensor * output, const WinogradInfo & winograd_info)
Set the input and output tensor.
Note
Winograd filter transform supports the following configurations for NCWH data layout F(output tile, kernel size):F(2x2, 3x3), F(2x1, 3x1), F(1x2, 1x3), F(4x4, 3x3), F(4x1, 3x1), F(1x4, 1x3), F(4x4, 5x5), F(4x1, 5x1), F(1x4, 1x5)
Winograd filter transform supports the following configurations for NHWC data layout F(output tile, kernel size):F(4x4, 3x3), F(4x1, 3x1), F(1x4, 1x3), F(4x4, 5x5), F(4x1, 5x1), F(1x4, 1x5)
Strides: only unit strides
Parameters
[in] input Source tensor. The input is a 4D tensor with dimensions [kernel_x, kernel_y, IFM, OFM] (NCHW data layout) or [IFM, kernel_x, kernel_y, OFM] (NHWC data layout). Data types supported: F16/F32.
[out] output The output tensor. The shape for this tensor can be calculated using the utility function compute_winograd_filter_transform_shape. Data types supported: Same as input
[in] winograd_info Contains Winograd's information described in WinogradInfo
Definition at line 102 of file CLWinogradFilterTransformKernel.cpp.
 {
     ARM_COMPUTE_ERROR_ON_NULLPTR(input, output);
     // Output auto initialization if not yet initialized
     auto_init_if_empty(*output->info(), input->info()->clone()->set_tensor_shape(compute_winograd_filter_transform_shape(*input->info(), winograd_info)));
     ARM_COMPUTE_ERROR_THROW_ON(validate_arguments(input->info(), output->info(), winograd_info));
     // Set build options
     CLBuildOptions build_opts;
     build_opts.add_option("-DSRC_DIM_Z=" + support::cpp11::to_string(input->info()->dimension(2)));
     build_opts.add_option("-DDATA_TYPE=" + get_cl_type_from_data_type(input->info()->data_type()));
     build_opts.add_option_if(winograd_info.kernel_size.height == 1, "-DWINOGRAD_FILTER_TRANSFORM_HORIZONTAL");
     build_opts.add_option_if(winograd_info.kernel_size.width == 1, "-DWINOGRAD_FILTER_TRANSFORM_VERTICAL");
     const Size2D kernel_size      = winograd_info.kernel_size;
     const Size2D output_tile_size = winograd_info.output_tile_size;
     // Create kernel
     std::string kernel_name = "winograd_filter_transform_" + output_tile_size.to_string() + "_" + kernel_size.to_string() + "_" + lower_string(string_from_data_layout(input->info()->data_layout()));
     _kernel                 = static_cast<cl::Kernel>(CLKernelLibrary::get().create_kernel(kernel_name, build_opts.options()));
     _input  = input;
     _output = output;
     // Configure kernel window
     auto win_config = validate_and_configure_window(input->info(), output->info());
     ARM_COMPUTE_ERROR_THROW_ON(win_config.first);
     ICLKernel::configure_internal(win_config.second);
 }
References CLBuildOptions::add_option(), CLBuildOptions::add_option_if(), ARM_COMPUTE_ERROR_ON_NULLPTR, ARM_COMPUTE_ERROR_THROW_ON, arm_compute::auto_init_if_empty(), ICloneable< T >::clone(), arm_compute::misc::shape_calculator::compute_winograd_filter_transform_shape(), arm_compute::create_kernel(), ITensorInfo::data_layout(), ITensorInfo::data_type(), ITensorInfo::dimension(), CLKernelLibrary::get(), arm_compute::get_cl_type_from_data_type(), ITensor::info(), arm_compute::lower_string(), CLBuildOptions::options(), arm_compute::string_from_data_layout(), Size2D::to_string(), arm_compute::support::cpp11::to_string(), arm_compute::validate_and_configure_window(), and arm_compute::test::validation::winograd_info.
Referenced by CLWinogradConvolutionLayer::configure().
operator=() [1/2]
CLWinogradFilterTransformKernel& operator= (const CLWinogradFilterTransformKernel &) delete
Prevent instances of this class from being copied (As this class contains pointers)
operator=() [2/2]
CLWinogradFilterTransformKernel& operator= (CLWinogradFilterTransformKernel &&) default
Allow instances of this class to be moved.
run()
void run (const Window & window, cl::CommandQueue & queue) override virtual
Enqueue the OpenCL kernel to process the given window on the passed OpenCL command queue.
Note
The queue is not flushed by this method, and therefore the kernel will not have been executed by the time this method returns.
Parameters
[in] window Region on which to execute the kernel. (Must be a valid region of the window returned by window()).
[in,out] queue Command queue on which to enqueue the kernel.
Implements ICLKernel.
Definition at line 141 of file CLWinogradFilterTransformKernel.cpp.
 {
     ARM_COMPUTE_ERROR_ON_UNCONFIGURED_KERNEL(this);
     ARM_COMPUTE_ERROR_ON_INVALID_SUBWINDOW(ICLKernel::window(), window);
     // Setup output window
     Window window_out;
     window_out.use_tensor_dimensions(_output->info()->tensor_shape(), 0);
     unsigned int idx = 0;
     add_4D_tensor_argument(idx, _input, window);
     add_3D_tensor_argument(idx, _output, window_out);
     enqueue(queue, *this, window);
 }
References ICLKernel::add_3D_tensor_argument(), ICLKernel::add_4D_tensor_argument(), ARM_COMPUTE_ERROR_ON_INVALID_SUBWINDOW, ARM_COMPUTE_ERROR_ON_UNCONFIGURED_KERNEL, arm_compute::enqueue(), ITensor::info(), ITensorInfo::tensor_shape(), Window::use_tensor_dimensions(), and IKernel::window().
validate()
Status validate (const ITensorInfo * input, const ITensorInfo * output, const WinogradInfo & winograd_info) static
Static function to check if given info will lead to a valid configuration of CLWinogradFilterTransformKernel.
Note
Winograd filter transform supports the following configurations for NCWH data layout F(output tile, kernel size):F(2x2, 3x3), F(2x1, 3x1), F(1x2, 1x3), F(4x4, 3x3), F(4x1, 3x1), F(1x4, 1x3), F(4x4, 5x5), F(4x1, 5x1), F(1x4, 1x5)
Winograd filter transform supports the following configurations for NHWC data layout F(output tile, kernel size):F(4x4, 3x3), F(4x1, 3x1), F(1x4, 1x3), F(4x4, 5x5), F(4x1, 5x1), F(1x4, 1x5)
Strides: only unit strides
Parameters
[in] input Source tensor. The input is a 4D tensor with dimensions [kernel_x, kernel_y, IFM, OFM] (NCHW data layout) or [IFM, kernel_x, kernel_y, OFM] (NHWC data layout). Data types supported: F16/F32.
[out] output The output tensor. The shape for this tensor can be calculated using the utility function compute_winograd_filter_transform_shape. Data types supported: Same as input
[in] winograd_info Contains Winograd's information described in WinogradInfo
Returns
a status
Definition at line 133 of file CLWinogradFilterTransformKernel.cpp.
 {
     ARM_COMPUTE_RETURN_ON_ERROR(validate_arguments(input, output, winograd_info));
     ARM_COMPUTE_RETURN_ON_ERROR(validate_and_configure_window(input->clone().get(), output->clone().get()).first);
     return Status{};
 }
References ARM_COMPUTE_RETURN_ON_ERROR, ICloneable< T >::clone(), arm_compute::validate_and_configure_window(), and arm_compute::test::validation::winograd_info.
Referenced by CLWinogradConvolutionLayer::validate().
The documentation for this class was generated from the following files:
arm_compute/core/CL/kernels/CLWinogradFilterTransformKernel.h
src/core/CL/kernels/CLWinogradFilterTransformKernel.cpp