Compute Library: CLPixelWiseMultiplicationKernel Class Reference
CLPixelWiseMultiplicationKernel Class Reference
Interface for the pixelwise multiplication kernel.
#include <CLPixelWiseMultiplicationKernel.h>
Public Member Functions
CLPixelWiseMultiplicationKernel ()
Default constructor.
CLPixelWiseMultiplicationKernel (const CLPixelWiseMultiplicationKernel &)=delete
Prevent instances of this class from being copied (As this class contains pointers)
CLPixelWiseMultiplicationKernel & operator= (const CLPixelWiseMultiplicationKernel &)=delete
Prevent instances of this class from being copied (As this class contains pointers)
CLPixelWiseMultiplicationKernel (CLPixelWiseMultiplicationKernel &&)=default
Allow instances of this class to be moved.
CLPixelWiseMultiplicationKernel & operator= (CLPixelWiseMultiplicationKernel &&)=default
Allow instances of this class to be moved.
void configure (const ICLTensor *input1, const ICLTensor *input2, ICLTensor *output, float scale, ConvertPolicy overflow_policy, RoundingPolicy rounding_policy)
Initialise the kernel's input, output and border mode.
void run (const Window &window, cl::CommandQueue &queue) override
Enqueue the OpenCL kernel to process the given window on the passed OpenCL command queue.
BorderSize border_size () const override
The size of the border for that kernel.
Public Member Functions inherited from ICLKernel
ICLKernel ()
Constructor.
cl::Kernel & kernel ()
Returns a reference to the OpenCL kernel of this object.
template<typename T >
void add_1D_array_argument (unsigned int &idx, const ICLArray< T > *array, const Strides &strides, unsigned int num_dimensions, const Window &window)
Add the passed 1D array's parameters to the object's kernel's arguments starting from the index idx.
void add_1D_tensor_argument (unsigned int &idx, const ICLTensor *tensor, const Window &window)
Add the passed 1D tensor's parameters to the object's kernel's arguments starting from the index idx.
void add_1D_tensor_argument_if (bool cond, unsigned int &idx, const ICLTensor *tensor, const Window &window)
Add the passed 1D tensor's parameters to the object's kernel's arguments starting from the index idx if the condition is true.
void add_2D_tensor_argument (unsigned int &idx, const ICLTensor *tensor, const Window &window)
Add the passed 2D tensor's parameters to the object's kernel's arguments starting from the index idx.
void add_2D_tensor_argument_if (bool cond, unsigned int &idx, const ICLTensor *tensor, const Window &window)
Add the passed 2D tensor's parameters to the object's kernel's arguments starting from the index idx if the condition is true.
void add_3D_tensor_argument (unsigned int &idx, const ICLTensor *tensor, const Window &window)
Add the passed 3D tensor's parameters to the object's kernel's arguments starting from the index idx.
void add_4D_tensor_argument (unsigned int &idx, const ICLTensor *tensor, const Window &window)
Add the passed 4D tensor's parameters to the object's kernel's arguments starting from the index idx.
template<typename T >
void add_argument (unsigned int &idx, T value)
Add the passed parameters to the object's kernel's arguments starting from the index idx.
void set_lws_hint (const cl::NDRange &lws_hint)
Set the Local-Workgroup-Size hint.
cl::NDRange lws_hint () const
Return the Local-Workgroup-Size hint.
const std::string & config_id () const
Get the configuration ID.
void set_target (GPUTarget target)
Set the targeted GPU architecture.
void set_target (cl::Device &device)
Set the targeted GPU architecture according to the CL device.
GPUTarget get_target () const
Get the targeted GPU architecture.
size_t get_max_workgroup_size ()
Get the maximum workgroup size for the device the CLKernelLibrary uses.
template<typename T , unsigned int dimension_size>
void add_array_argument (unsigned &idx, const ICLArray< T > *array, const Strides &strides, unsigned int num_dimensions, const Window &window)
Add the passed array's parameters to the object's kernel's arguments starting from the index idx.
template<unsigned int dimension_size>
void add_tensor_argument (unsigned &idx, const ICLTensor *tensor, const Window &window)
Public Member Functions inherited from IKernel
IKernel ()
Constructor.
virtual ~IKernel ()=default
Destructor.
virtual bool is_parallelisable () const
Indicates whether or not the kernel is parallelisable.
const Window & window () const
The maximum window the kernel can be executed on.
Static Public Member Functions
static Status validate (const ITensorInfo *input1, const ITensorInfo *input2, const ITensorInfo *output, float scale, ConvertPolicy overflow_policy, RoundingPolicy rounding_policy)
Static function to check if given info will lead to a valid configuration of CLPixelWiseMultiplicationKernel.
Static Public Member Functions inherited from ICLKernel
static constexpr unsigned int num_arguments_per_1D_array ()
Returns the number of arguments enqueued per 1D array object.
static constexpr unsigned int num_arguments_per_1D_tensor ()
Returns the number of arguments enqueued per 1D tensor object.
static constexpr unsigned int num_arguments_per_2D_tensor ()
Returns the number of arguments enqueued per 2D tensor object.
static constexpr unsigned int num_arguments_per_3D_tensor ()
Returns the number of arguments enqueued per 3D tensor object.
static constexpr unsigned int num_arguments_per_4D_tensor ()
Returns the number of arguments enqueued per 4D tensor object.
static cl::NDRange gws_from_window (const Window &window)
Get the global work size given an execution window.
Detailed Description
Interface for the pixelwise multiplication kernel.
Definition at line 36 of file CLPixelWiseMultiplicationKernel.h.
Constructor & Destructor Documentation
CLPixelWiseMultiplicationKernel() [1/3]
CLPixelWiseMultiplicationKernel ()
Default constructor.
Definition at line 127 of file CLPixelWiseMultiplicationKernel.cpp.
     : _input1(nullptr), _input2(nullptr), _output(nullptr)
 {
 }
CLPixelWiseMultiplicationKernel() [2/3]
CLPixelWiseMultiplicationKernel (const CLPixelWiseMultiplicationKernel &) delete
Prevent instances of this class from being copied (As this class contains pointers)
CLPixelWiseMultiplicationKernel() [3/3]
CLPixelWiseMultiplicationKernel (CLPixelWiseMultiplicationKernel &&) default
Allow instances of this class to be moved.
Member Function Documentation
border_size()
BorderSize border_size () const override virtual
The size of the border for that kernel.
Returns
The width in number of elements of the border.
Reimplemented from IKernel.
Definition at line 285 of file CLPixelWiseMultiplicationKernel.cpp.
 {
     const unsigned int replicateSize = _output->info()->dimension(0) - std::min(_input1->info()->dimension(0), _input2->info()->dimension(0));
     const unsigned int border        = std::min<unsigned int>(num_elems_processed_per_iteration - 1U, replicateSize);
     return BorderSize{ 0, border, 0, 0 };
 }
References ITensorInfo::dimension(), ITensor::info(), and arm_compute::U.
configure()
void configure (const ICLTensor * input1, const ICLTensor * input2, ICLTensor * output, float scale, ConvertPolicy overflow_policy, RoundingPolicy rounding_policy)
Initialise the kernel's input, output and border mode.
Parameters
[in] input1 An input tensor. Data types supported: U8/QASYMM8/S16/QSYMM16/F16/F32.
[in] input2 An input tensor. Data types supported: same as input1.
[out] output The output tensor, Data types supported: same as input1. Note: U8 requires both inputs to be U8.
[in] scale Scale to apply after multiplication. Scale must be positive and its value must be either 1/255 or 1/2^n where n is between 0 and 15.
[in] overflow_policy Overflow policy. Supported overflow policies: Wrap, Saturate
[in] rounding_policy Rounding policy. Supported rounding modes: to zero, to nearest even.
Definition at line 132 of file CLPixelWiseMultiplicationKernel.cpp.
 {
     ARM_COMPUTE_ERROR_ON_NULLPTR(input1, input2, output);
     ARM_COMPUTE_ERROR_THROW_ON(validate_arguments(input1->info(), input2->info(), output->info(),
                                                   scale, overflow_policy, rounding_policy));
     // Configure kernel window
     auto win_config = validate_and_configure_window(input1->info(), input2->info(), output->info());
     ARM_COMPUTE_ERROR_THROW_ON(win_config.first);
     _input1 = input1;
     _input2 = input2;
     _output = output;
     int scale_int = -1;
     // Extract sign, exponent and mantissa
     int   exponent            = 0;
     float normalized_mantissa = std::frexp(scale, &exponent);
     // Use int scaling if factor is equal to 1/2^n for 0 <= n <= 15
     // frexp returns 0.5 as mantissa which means that the exponent will be in the range of -1 <= e <= 14
     // Moreover, it will be negative as we deal with 1/2^n
     if((normalized_mantissa == 0.5f) && (-14 <= exponent) && (exponent <= 1))
     {
         // Store the positive exponent. We know that we compute 1/2^n
         // Additionally we need to subtract 1 to compensate that frexp used a mantissa of 0.5
         scale_int = std::abs(exponent - 1);
     }
     std::string compute_type;
     // Check if it has float inputs and output
     if(is_data_type_float(input1->info()->data_type()) || is_data_type_float(input2->info()->data_type()))
     {
         scale_int    = -1;
         compute_type = (input1->info()->data_type() == DataType::F32 || input2->info()->data_type() == DataType::F32) ? "float" : "half";
     }
     else
     {
         if(input1->info()->data_type() == DataType::S16 || input2->info()->data_type() == DataType::S16)
         {
             compute_type = "int";
         }
         else
         {
             compute_type = "ushort";
         }
     }
     const bool is_quantized = is_data_type_quantized(input1->info()->data_type());
     // Set kernel build options
     std::string    kernel_name = "pixelwise_mul";
     CLBuildOptions build_opts;
     build_opts.add_option("-DDATA_TYPE_IN1=" + get_cl_type_from_data_type(input1->info()->data_type()));
     build_opts.add_option("-DDATA_TYPE_IN2=" + get_cl_type_from_data_type(input2->info()->data_type()));
     build_opts.add_option("-DDATA_TYPE_OUT=" + get_cl_type_from_data_type(output->info()->data_type()));
     build_opts.add_option("-DVEC_SIZE=" + support::cpp11::to_string(num_elems_processed_per_iteration));
     if(is_quantized)
     {
         const UniformQuantizationInfo iq1_info = input1->info()->quantization_info().uniform();
         const UniformQuantizationInfo iq2_info = input2->info()->quantization_info().uniform();
         const UniformQuantizationInfo oq_info  = output->info()->quantization_info().uniform();
         build_opts.add_option_if(is_data_type_quantized_asymmetric(input1->info()->data_type()),
                                  "-DOFFSET_IN1=" + support::cpp11::to_string(iq1_info.offset));
         build_opts.add_option_if(is_data_type_quantized_asymmetric(input2->info()->data_type()),
                                  "-DOFFSET_IN2=" + support::cpp11::to_string(iq2_info.offset));
         build_opts.add_option_if(is_data_type_quantized_asymmetric(output->info()->data_type()),
                                  "-DOFFSET_OUT=" + support::cpp11::to_string(oq_info.offset));
         build_opts.add_option("-DSCALE_IN1=" + float_to_string_with_full_precision(iq1_info.scale));
         build_opts.add_option("-DSCALE_IN2=" + float_to_string_with_full_precision(iq2_info.scale));
         build_opts.add_option("-DSCALE_OUT=" + float_to_string_with_full_precision(oq_info.scale));
         kernel_name += "_quantized";
     }
     else
     {
         kernel_name += (scale_int >= 0) ? "_int" : "_float";
         build_opts.add_option_if_else(overflow_policy == ConvertPolicy::WRAP || is_data_type_float(output->info()->data_type()), "-DWRAP", "-DSATURATE");
         build_opts.add_option_if_else(rounding_policy == RoundingPolicy::TO_ZERO, "-DROUND=_rtz", "-DROUND=_rte");
         build_opts.add_option("-DDATA_TYPE_RES=" + compute_type);
     }
     // Create kernel
     _kernel = static_cast<cl::Kernel>(CLKernelLibrary::get().create_kernel(kernel_name, build_opts.options()));
     // Set scale argument
     unsigned int idx = 3 * num_arguments_per_3D_tensor(); // Skip the inputs and output parameters
     if(scale_int >= 0 && !is_quantized)
     {
         _kernel.setArg(idx++, scale_int);
     }
     else
     {
         _kernel.setArg(idx++, scale);
     }
     ICLKernel::configure_internal(win_config.second);
 }
References CLBuildOptions::add_option(), CLBuildOptions::add_option_if(), CLBuildOptions::add_option_if_else(), ARM_COMPUTE_ERROR_ON_NULLPTR, ARM_COMPUTE_ERROR_THROW_ON, arm_compute::create_kernel(), ITensorInfo::data_type(), arm_compute::F32, arm_compute::float_to_string_with_full_precision(), CLKernelLibrary::get(), arm_compute::get_cl_type_from_data_type(), ITensor::info(), arm_compute::is_data_type_float(), arm_compute::is_data_type_quantized(), arm_compute::is_data_type_quantized_asymmetric(), ICLKernel::num_arguments_per_3D_tensor(), UniformQuantizationInfo::offset, CLBuildOptions::options(), ITensorInfo::quantization_info(), arm_compute::test::validation::rounding_policy, arm_compute::S16, UniformQuantizationInfo::scale, arm_compute::test::validation::scale, arm_compute::support::cpp11::to_string(), arm_compute::TO_ZERO, QuantizationInfo::uniform(), arm_compute::validate_and_configure_window(), and arm_compute::WRAP.
Referenced by CLLSTMLayer::configure().
operator=() [1/2]
CLPixelWiseMultiplicationKernel& operator= (const CLPixelWiseMultiplicationKernel &) delete
Prevent instances of this class from being copied (As this class contains pointers)
operator=() [2/2]
CLPixelWiseMultiplicationKernel& operator= (CLPixelWiseMultiplicationKernel &&) default
Allow instances of this class to be moved.
run()
void run (const Window & window, cl::CommandQueue & queue) override virtual
Enqueue the OpenCL kernel to process the given window on the passed OpenCL command queue.
Note
The queue is not flushed by this method, and therefore the kernel will not have been executed by the time this method returns.
Parameters
[in] window Region on which to execute the kernel. (Must be a valid region of the window returned by window()).
[in,out] queue Command queue on which to enqueue the kernel.
Implements ICLKernel.
Definition at line 242 of file CLPixelWiseMultiplicationKernel.cpp.
 {
     ARM_COMPUTE_ERROR_ON_UNCONFIGURED_KERNEL(this);
     ARM_COMPUTE_ERROR_ON_INVALID_SUBWINDOW(ICLKernel::window(), window);
     const TensorShape &in_shape1 = _input1->info()->tensor_shape();
     const TensorShape &in_shape2 = _input2->info()->tensor_shape();
     const TensorShape &out_shape = _output->info()->tensor_shape();
     bool can_collapse = true;
     if(std::min(in_shape1.total_size(), in_shape2.total_size()) > 1)
     {
         can_collapse = (std::min(in_shape1.num_dimensions(), in_shape2.num_dimensions()) > Window::DimZ);
         for(size_t d = Window::DimZ; can_collapse && (d < out_shape.num_dimensions()); ++d)
         {
             can_collapse = (in_shape1[d] == in_shape2[d]);
         }
     }
     bool   has_collapsed = false;
     Window collapsed     = can_collapse ? window.collapse_if_possible(ICLKernel::window(), Window::DimZ, &has_collapsed) : window;
     const TensorShape &in_shape1_collapsed = has_collapsed ? in_shape1.collapsed_from(Window::DimZ) : in_shape1;
     const TensorShape &in_shape2_collapsed = has_collapsed ? in_shape2.collapsed_from(Window::DimZ) : in_shape2;
     Window slice        = collapsed.first_slice_window_3D();
     Window slice_input1 = slice.broadcast_if_dimension_le_one(in_shape1_collapsed);
     Window slice_input2 = slice.broadcast_if_dimension_le_one(in_shape2_collapsed);
     do
     {
         unsigned int idx = 0;
         add_3D_tensor_argument(idx, _input1, slice_input1);
         add_3D_tensor_argument(idx, _input2, slice_input2);
         add_3D_tensor_argument(idx, _output, slice);
         enqueue(queue, *this, slice);
         ARM_COMPUTE_UNUSED(collapsed.slide_window_slice_3D(slice_input1));
         ARM_COMPUTE_UNUSED(collapsed.slide_window_slice_3D(slice_input2));
     }
     while(collapsed.slide_window_slice_3D(slice));
 }
References ICLKernel::add_3D_tensor_argument(), ARM_COMPUTE_ERROR_ON_INVALID_SUBWINDOW, ARM_COMPUTE_ERROR_ON_UNCONFIGURED_KERNEL, ARM_COMPUTE_UNUSED, Window::collapse_if_possible(), TensorShape::collapsed_from(), Window::DimZ, arm_compute::enqueue(), Window::first_slice_window_3D(), ITensor::info(), Dimensions< T >::num_dimensions(), arm_compute::test::validation::reference::slice(), Window::slide_window_slice_3D(), ITensorInfo::tensor_shape(), TensorShape::total_size(), and IKernel::window().
validate()
Status validate (const ITensorInfo * input1, const ITensorInfo * input2, const ITensorInfo * output, float scale, ConvertPolicy overflow_policy, RoundingPolicy rounding_policy) static
Static function to check if given info will lead to a valid configuration of CLPixelWiseMultiplicationKernel.
Parameters
[in] input1 An input tensor info. Data types supported: U8/QASYMM8/S16/QSYMM16/F16/F32.
[in] input2 An input tensor info. Data types supported: same as input1.
[in] output The output tensor info, Data types supported: same as input1. Note: U8 requires both inputs to be U8.
[in] scale Scale to apply after multiplication. Scale must be positive and its value must be either 1/255 or 1/2^n where n is between 0 and 15.
[in] overflow_policy Overflow policy. Supported overflow policies: Wrap, Saturate
[in] rounding_policy Rounding policy. Supported rounding modes: to zero, to nearest even.
Returns
a status
Definition at line 232 of file CLPixelWiseMultiplicationKernel.cpp.
 {
     ARM_COMPUTE_ERROR_ON_NULLPTR(input1, input2, output);
     ARM_COMPUTE_RETURN_ON_ERROR(validate_arguments(input1, input2, output, scale, overflow_policy, rounding_policy));
     ARM_COMPUTE_RETURN_ON_ERROR(validate_and_configure_window(input1->clone().get(), input2->clone().get(), output->clone().get()).first);
     return Status{};
 }
References ARM_COMPUTE_ERROR_ON_NULLPTR, ARM_COMPUTE_RETURN_ON_ERROR, ICloneable< T >::clone(), arm_compute::test::validation::rounding_policy, arm_compute::test::validation::scale, and arm_compute::validate_and_configure_window().
Referenced by CLPixelWiseMultiplication::validate(), and CLLSTMLayer::validate().
The documentation for this class was generated from the following files:
arm_compute/core/CL/kernels/CLPixelWiseMultiplicationKernel.h
src/core/CL/kernels/CLPixelWiseMultiplicationKernel.cpp