Compute Library: IHOG Class Reference
IHOG Class Reference abstract
Interface for HOG data-object.
#include <IHOG.h>
Public Member Functions
virtual const HOGInfo * info () const =0
Interface to be implemented by the child class to return the HOG's metadata.
virtual ~IHOG ()=default
Default virtual destructor.
virtual float * descriptor () const =0
Pointer to the first element of the array which stores the linear SVM coefficients of HOG descriptor.
Detailed Description
Interface for HOG data-object.
Definition at line 35 of file IHOG.h.
Constructor & Destructor Documentation
~IHOG()
virtual ~IHOG () virtual default
Default virtual destructor.
Member Function Documentation
descriptor()
virtual float* descriptor () const pure virtual
Pointer to the first element of the array which stores the linear SVM coefficients of HOG descriptor.
Note
Other elements of the array can be accessed using descriptor()[idx] for idx=[0, descriptor_size() - 1]
Returns
A pointer to the first element of the array which stores the linear SVM coefficients of HOG descriptor
Implemented in ICLHOG, and HOG.
Referenced by NEHOGDetectorKernel::configure().
info()
virtual const HOGInfo* info () const pure virtual
Interface to be implemented by the child class to return the HOG's metadata.
Returns
A pointer to the HOG's metadata.
Implemented in CLHOG, and HOG.
Referenced by NEHOGDescriptor::configure(), CLHOGDescriptor::configure(), NEHOGDetectorKernel::configure(), CLHOGDetectorKernel::configure(), CLHOGMultiDetection::configure(), NEHOGMultiDetection::configure(), and arm_compute::error_on_invalid_multi_hog().
The documentation for this class was generated from the following file:
arm_compute/core/IHOG.h