Compute Library: CLCopyToArrayKernel Class Reference
CLCopyToArrayKernel Class Reference
CL kernel to copy keypoints information to ICLKeyPointArray and counts the number of key points.
#include <CLFastCornersKernel.h>
Public Member Functions
CLCopyToArrayKernel ()
Default constructor.
CLCopyToArrayKernel (const CLCopyToArrayKernel &)=delete
Prevent instances of this class from being copied (As this class contains pointers)
CLCopyToArrayKernel & operator= (const CLCopyToArrayKernel &)=delete
Prevent instances of this class from being copied (As this class contains pointers)
CLCopyToArrayKernel (CLCopyToArrayKernel &&)=default
Allow instances of this class to be moved.
CLCopyToArrayKernel & operator= (CLCopyToArrayKernel &&)=default
Allow instances of this class to be moved.
~CLCopyToArrayKernel ()=default
Default destructor.
void configure (const ICLImage *input, bool update_number, ICLKeyPointArray *corners, cl::Buffer *num_buffers)
Initialise the kernel.
void run (const Window &window, cl::CommandQueue &queue) override
Enqueue the OpenCL kernel to process the given window on the passed OpenCL command queue.
Public Member Functions inherited from ICLKernel
ICLKernel ()
Constructor.
cl::Kernel & kernel ()
Returns a reference to the OpenCL kernel of this object.
template<typename T >
void add_1D_array_argument (unsigned int &idx, const ICLArray< T > *array, const Strides &strides, unsigned int num_dimensions, const Window &window)
Add the passed 1D array's parameters to the object's kernel's arguments starting from the index idx.
void add_1D_tensor_argument (unsigned int &idx, const ICLTensor *tensor, const Window &window)
Add the passed 1D tensor's parameters to the object's kernel's arguments starting from the index idx.
void add_2D_tensor_argument (unsigned int &idx, const ICLTensor *tensor, const Window &window)
Add the passed 2D tensor's parameters to the object's kernel's arguments starting from the index idx.
void add_3D_tensor_argument (unsigned int &idx, const ICLTensor *tensor, const Window &window)
Add the passed 3D tensor's parameters to the object's kernel's arguments starting from the index idx.
void add_4D_tensor_argument (unsigned int &idx, const ICLTensor *tensor, const Window &window)
Add the passed 4D tensor's parameters to the object's kernel's arguments starting from the index idx.
template<typename T >
void add_argument (unsigned int &idx, T value)
Add the passed parameters to the object's kernel's arguments starting from the index idx.
void set_lws_hint (const cl::NDRange &lws_hint)
Set the Local-Workgroup-Size hint.
cl::NDRange lws_hint () const
Return the Local-Workgroup-Size hint.
const std::string & config_id () const
Get the configuration ID.
void set_target (GPUTarget target)
Set the targeted GPU architecture.
void set_target (cl::Device &device)
Set the targeted GPU architecture according to the CL device.
GPUTarget get_target () const
Get the targeted GPU architecture.
size_t get_max_workgroup_size ()
Get the maximum workgroup size for the device the CLKernelLibrary uses.
template<typename T , unsigned int dimension_size>
void add_array_argument (unsigned &idx, const ICLArray< T > *array, const Strides &strides, unsigned int num_dimensions, const Window &window)
Add the passed array's parameters to the object's kernel's arguments starting from the index idx.
template<unsigned int dimension_size>
void add_tensor_argument (unsigned &idx, const ICLTensor *tensor, const Window &window)
Public Member Functions inherited from IKernel
IKernel ()
Constructor.
virtual ~IKernel ()=default
Destructor.
virtual bool is_parallelisable () const
Indicates whether or not the kernel is parallelisable.
virtual BorderSize border_size () const
The size of the border for that kernel.
const Window & window () const
The maximum window the kernel can be executed on.
Additional Inherited Members
Static Public Member Functions inherited from ICLKernel
static constexpr unsigned int num_arguments_per_1D_array ()
Returns the number of arguments enqueued per 1D array object.
static constexpr unsigned int num_arguments_per_1D_tensor ()
Returns the number of arguments enqueued per 1D tensor object.
static constexpr unsigned int num_arguments_per_2D_tensor ()
Returns the number of arguments enqueued per 2D tensor object.
static constexpr unsigned int num_arguments_per_3D_tensor ()
Returns the number of arguments enqueued per 3D tensor object.
static constexpr unsigned int num_arguments_per_4D_tensor ()
Returns the number of arguments enqueued per 4D tensor object.
static cl::NDRange gws_from_window (const Window &window)
Get the global work size given an execution window.
Detailed Description
CL kernel to copy keypoints information to ICLKeyPointArray and counts the number of key points.
Definition at line 80 of file CLFastCornersKernel.h.
Constructor & Destructor Documentation
CLCopyToArrayKernel() [1/3]
CLCopyToArrayKernel ()
Default constructor.
Definition at line 110 of file CLFastCornersKernel.cpp.
     : ICLKernel(), _input(nullptr), _corners(nullptr), _num_buffer(nullptr)
 {
 }
CLCopyToArrayKernel() [2/3]
CLCopyToArrayKernel (const CLCopyToArrayKernel &) delete
Prevent instances of this class from being copied (As this class contains pointers)
CLCopyToArrayKernel() [3/3]
CLCopyToArrayKernel (CLCopyToArrayKernel &&) default
Allow instances of this class to be moved.
~CLCopyToArrayKernel()
~CLCopyToArrayKernel () default
Default destructor.
Member Function Documentation
configure()
void configure (const ICLImage * input, bool update_number, ICLKeyPointArray * corners, cl::Buffer * num_buffers)
Initialise the kernel.
Parameters
[in] input Source image. Data types supported: U8.
[in] update_number Flag to indicate whether we need to update the number of corners
[out] corners Array of keypoints to store the results.
[out] num_buffers Number of keypoints to store the results.
Definition at line 115 of file CLFastCornersKernel.cpp.
 {
     ARM_COMPUTE_ERROR_ON_TENSOR_NOT_2D(input);
     ARM_COMPUTE_ERROR_ON_DATA_TYPE_CHANNEL_NOT_IN(input, 1, DataType::U8);
     ARM_COMPUTE_ERROR_ON(corners == nullptr);
     ARM_COMPUTE_ERROR_ON(num_buffers == nullptr);
     _input      = input;
     _corners    = corners;
     _num_buffer = num_buffers;
     std::set<std::string> build_opts;
     if(update_number)
     {
         build_opts.emplace("-DUPDATE_NUMBER");
     }
     // Create kernel
     _kernel = static_cast<cl::Kernel>(CLKernelLibrary::get().create_kernel("copy_to_keypoint", build_opts));
     //Get how many pixels skipped in the x dimension in the previous stages
     unsigned int offset = _input->info()->valid_region().anchor.x();
     // Set static kernel arguments
     unsigned int idx = num_arguments_per_2D_tensor(); // Skip the input and output parameters
     _kernel.setArg<unsigned int>(idx++, _corners->max_num_values());
     _kernel.setArg<cl_uint>(idx++, offset);
     _kernel.setArg(idx++, *_num_buffer);
     _kernel.setArg(idx++, _corners->cl_buffer());
     // Configure kernel window
     constexpr unsigned int num_elems_processed_per_iteration = 1;
     Window                 win                               = calculate_max_window(*input->info(), Steps(num_elems_processed_per_iteration));
     update_window_and_padding(win,
                               AccessWindowHorizontal(input->info(), 0, num_elems_processed_per_iteration));
     ICLKernel::configure_internal(win);
 }
References ValidRegion::anchor, ARM_COMPUTE_ERROR_ON, ARM_COMPUTE_ERROR_ON_DATA_TYPE_CHANNEL_NOT_IN, ARM_COMPUTE_ERROR_ON_TENSOR_NOT_2D, arm_compute::calculate_max_window(), ICLArray< T >::cl_buffer(), arm_compute::create_kernel(), CLKernelLibrary::get(), ITensor::info(), IArray< T >::max_num_values(), ICLKernel::num_arguments_per_2D_tensor(), offset(), arm_compute::U8, arm_compute::update_window_and_padding(), ITensorInfo::valid_region(), and Dimensions< T >::x().
Referenced by CLFastCorners::configure().
operator=() [1/2]
CLCopyToArrayKernel& operator= (const CLCopyToArrayKernel &) delete
Prevent instances of this class from being copied (As this class contains pointers)
operator=() [2/2]
CLCopyToArrayKernel& operator= (CLCopyToArrayKernel &&) default
Allow instances of this class to be moved.
run()
void run (const Window & window, cl::CommandQueue & queue) override virtual
Enqueue the OpenCL kernel to process the given window on the passed OpenCL command queue.
Note
The queue is not flushed by this method, and therefore the kernel will not have been executed by the time this method returns.
Parameters
[in] window Region on which to execute the kernel. (Must be a valid region of the window returned by window()).
[in,out] queue Command queue on which to enqueue the kernel.
Implements ICLKernel.
Definition at line 154 of file CLFastCornersKernel.cpp.
 {
     ARM_COMPUTE_ERROR_ON_UNCONFIGURED_KERNEL(this);
     ARM_COMPUTE_ERROR_ON_INVALID_SUBWINDOW(ICLKernel::window(), window);
     //Initialise the _num_buffer as it used as both input and output
     static const unsigned int zero_init = 0;
     queue.enqueueWriteBuffer(*_num_buffer, CL_FALSE, 0, sizeof(unsigned int), &zero_init);
     Window slice = window.first_slice_window_2D();
     do
     {
         unsigned int idx = 0;
         add_2D_tensor_argument(idx, _input, slice);
         enqueue(queue, *this, slice);
     }
     while(window.slide_window_slice_2D(slice));
 }
References ICLKernel::add_2D_tensor_argument(), ARM_COMPUTE_ERROR_ON_INVALID_SUBWINDOW, ARM_COMPUTE_ERROR_ON_UNCONFIGURED_KERNEL, arm_compute::enqueue(), Window::first_slice_window_2D(), arm_compute::test::validation::reference::slice(), Window::slide_window_slice_2D(), and IKernel::window().
The documentation for this class was generated from the following files:
arm_compute/core/CL/kernels/CLFastCornersKernel.h
src/core/CL/kernels/CLFastCornersKernel.cpp