Compute Library: NEDerivativeKernel Class Reference
NEDerivativeKernel Class Reference
Interface for the kernel to run the derivative along the X/Y directions on a tensor.
#include <NEDerivativeKernel.h>
Public Member Functions
const char * name () const override
Name of the kernel.
NEDerivativeKernel ()
Default constructor.
NEDerivativeKernel (const NEDerivativeKernel &)=delete
Prevent instances of this class from being copied (As this class contains pointers)
NEDerivativeKernel & operator= (const NEDerivativeKernel &)=delete
Prevent instances of this class from being copied (As this class contains pointers)
NEDerivativeKernel (NEDerivativeKernel &&)=default
Allow instances of this class to be moved.
NEDerivativeKernel & operator= (NEDerivativeKernel &&)=default
Allow instances of this class to be moved.
void configure (const ITensor *input, ITensor *output_x, ITensor *output_y, bool border_undefined)
Initialise the kernel's sources, destination and border.
void run (const Window &window, const ThreadInfo &info) override
Execute the kernel on the passed window.
BorderSize border_size () const override
The size of the border for that kernel.
Public Member Functions inherited from ICPPKernel
virtual ~ICPPKernel ()=default
Default destructor.
Public Member Functions inherited from IKernel
IKernel ()
Constructor.
virtual ~IKernel ()=default
Destructor.
virtual bool is_parallelisable () const
Indicates whether or not the kernel is parallelisable.
const Window & window () const
The maximum window the kernel can be executed on.
Detailed Description
Interface for the kernel to run the derivative along the X/Y directions on a tensor.
Definition at line 36 of file NEDerivativeKernel.h.
Constructor & Destructor Documentation
NEDerivativeKernel() [1/3]
NEDerivativeKernel ()
Default constructor.
Definition at line 44 of file NEDerivativeKernel.cpp.
     : _func(nullptr), _input(nullptr), _output_x(nullptr), _output_y(nullptr)
 {
 }
NEDerivativeKernel() [2/3]
NEDerivativeKernel (const NEDerivativeKernel &) delete
Prevent instances of this class from being copied (As this class contains pointers)
NEDerivativeKernel() [3/3]
NEDerivativeKernel (NEDerivativeKernel &&) default
Allow instances of this class to be moved.
Member Function Documentation
border_size()
BorderSize border_size () const override virtual
The size of the border for that kernel.
Returns
The width in number of elements of the border.
Reimplemented from IKernel.
Definition at line 49 of file NEDerivativeKernel.cpp.
 {
     return BorderSize(1);
 }
Referenced by NEDerivativeKernel::configure().
configure()
void configure (const ITensor * input, ITensor * output_x, ITensor * output_y, bool border_undefined)
Initialise the kernel's sources, destination and border.
Note
At least one of output_x or output_y must be set
Parameters
[in] input Source tensor. Data type supported: U8.
[out] output_x (Optional) Destination tensor for the X gradient. Data type supported: S16.
[out] output_y (Optional) Destination tensor for the Y gradient. Data type supported: S16.
[in] border_undefined True if the border mode is undefined. False if it's replicate or constant.
Definition at line 54 of file NEDerivativeKernel.cpp.
 {
     ARM_COMPUTE_ERROR_ON_DATA_TYPE_CHANNEL_NOT_IN(input, 1, DataType::U8);
     ARM_COMPUTE_ERROR_ON((output_x == nullptr) && (output_y == nullptr));
     const bool run_der_x = output_x != nullptr;
     const bool run_der_y = output_y != nullptr;
     if(run_der_x)
     {
         ARM_COMPUTE_ERROR_ON_DATA_TYPE_CHANNEL_NOT_IN(output_x, 1, DataType::S16);
     }
     if(run_der_y)
     {
         ARM_COMPUTE_ERROR_ON_DATA_TYPE_CHANNEL_NOT_IN(output_y, 1, DataType::S16);
     }
     _input    = input;
     _output_x = output_x;
     _output_y = output_y;
     constexpr unsigned int num_elems_processed_per_iteration = 16;
     constexpr unsigned int num_rows_read_per_iteration       = 3;
     Window win = calculate_max_window(*input->info(), Steps(num_elems_processed_per_iteration), border_undefined, border_size());
     AccessWindowHorizontal out_x_access(output_x == nullptr ? nullptr : output_x->info(), 0, num_elems_processed_per_iteration);
     AccessWindowHorizontal out_y_access(output_y == nullptr ? nullptr : output_y->info(), 0, num_elems_processed_per_iteration);
     // TODO(COMPMID-1503) Fix x-access input bug in NEON kernel instead of '+2'
     AccessWindowHorizontal in_x_access(input->info(), -border_size().left, num_elems_processed_per_iteration + 2);
     AccessWindowRectangle  in_y_access(input->info(), 0, -border_size().left, num_elems_processed_per_iteration, num_rows_read_per_iteration);
     // TODO(COMPMID-1503) Fix x-access input bug in NEON kernel instead of '+2'
     AccessWindowRectangle in_xy_access(input->info(), -border_size().left, -border_size().top, num_elems_processed_per_iteration + 2, num_rows_read_per_iteration);
     if(run_der_x && run_der_y)
     {
         _func = &NEDerivativeKernel::derivative_xy;
         update_window_and_padding(win, in_xy_access, out_x_access, out_y_access);
         out_y_access.set_valid_region(win, input->info()->valid_region(), border_undefined, border_size());
         out_x_access.set_valid_region(win, input->info()->valid_region(), border_undefined, border_size());
     }
     else
     {
         if(run_der_x)
         {
             _func = &NEDerivativeKernel::derivative_x;
             update_window_and_padding(win, in_x_access, out_x_access);
             out_x_access.set_valid_region(win, input->info()->valid_region(), border_undefined, border_size());
         }
         else if(run_der_y)
         {
             _func = &NEDerivativeKernel::derivative_y;
             update_window_and_padding(win, in_y_access, out_y_access);
             out_y_access.set_valid_region(win, input->info()->valid_region(), border_undefined, border_size());
         }
         else
         {
             ARM_COMPUTE_ERROR("At least one output must be NOT NULL");
         }
     }
     INEKernel::configure(win);
 }
References ARM_COMPUTE_ERROR, ARM_COMPUTE_ERROR_ON, ARM_COMPUTE_ERROR_ON_DATA_TYPE_CHANNEL_NOT_IN, NEDerivativeKernel::border_size(), arm_compute::calculate_max_window(), ITensor::info(), BorderSize::left, arm_compute::S16, BorderSize::top, arm_compute::U8, arm_compute::update_window_and_padding(), and ITensorInfo::valid_region().
Referenced by NEDerivative::configure().
name()
const char* name () const inline override virtual
Name of the kernel.
Returns
Kernel name
Implements ICPPKernel.
Definition at line 39 of file NEDerivativeKernel.h.
     {
         return "NEDerivativeKernel";
     }
operator=() [1/2]
NEDerivativeKernel& operator= (const NEDerivativeKernel &) delete
Prevent instances of this class from being copied (As this class contains pointers)
operator=() [2/2]
NEDerivativeKernel& operator= (NEDerivativeKernel &&) default
Allow instances of this class to be moved.
run()
void run (const Window & window, const ThreadInfo & info) override virtual
Execute the kernel on the passed window.
Warning
If is_parallelisable() returns false then the passed window must be equal to window()
Note
The window has to be a region within the window returned by the window() method
The width of the window has to be a multiple of num_elems_processed_per_iteration().
Parameters
[in] window Region on which to execute the kernel. (Must be a region of the window returned by window())
[in] info Info about executing thread and CPU.
Implements ICPPKernel.
Definition at line 221 of file NEDerivativeKernel.cpp.
 {
     ARM_COMPUTE_UNUSED(info);
     ARM_COMPUTE_ERROR_ON_UNCONFIGURED_KERNEL(this);
     ARM_COMPUTE_ERROR_ON_INVALID_SUBWINDOW(INEKernel::window(), window);
     ARM_COMPUTE_ERROR_ON(_func == nullptr);
     (this->*_func)(window);
 }
References ARM_COMPUTE_ERROR_ON, ARM_COMPUTE_ERROR_ON_INVALID_SUBWINDOW, ARM_COMPUTE_ERROR_ON_UNCONFIGURED_KERNEL, ARM_COMPUTE_UNUSED, arm_compute::test::validation::info, and IKernel::window().
The documentation for this class was generated from the following files:
arm_compute/core/NEON/kernels/NEDerivativeKernel.h
src/core/NEON/kernels/NEDerivativeKernel.cpp