Compute Library: Logger Class Reference
Logger Class Reference
Logger class.
#include <Logger.h>
Public Member Functions
Logger (std::string name, LogLevel log_level, std::shared_ptr< Printer > printer)
Default Constructor.
Logger (std::string name, LogLevel log_level, std::vector< std::shared_ptr< Printer >> printers={})
Default Constructor.
Logger (std::string name, LogLevel log_level, std::vector< std::shared_ptr< Printer >> printers, std::vector< std::unique_ptr< IDecorator >> decorators)
Default Constructor.
Logger (Logger &&)=default
Allow instances of this class to be moved.
Logger (const Logger &)=delete
Prevent instances of this class from being copied (As this class contains pointers)
Logger & operator= (const Logger &)=delete
Prevent instances of this class from being copied (As this class contains pointers)
Logger & operator= (Logger &&)=default
Allow instances of this class to be moved.
void log (LogLevel log_level, const std::string &msg)
Logs a message.
template<typename... Ts>
void log (LogLevel log_level, const std::string &fmt, Ts &&... args)
Logs a formatted message.
void set_log_level (LogLevel log_level)
Sets log level of the logger.
LogLevel log_level () const
Returns logger's log level.
std::string name () const
Returns logger's name.
void add_printer (std::shared_ptr< Printer > printer)
Adds a printer to the logger.
void add_decorator (std::unique_ptr< IDecorator > decorator)
Adds a log message decorator to the logger.
Detailed Description
Logger class.
Definition at line 42 of file Logger.h.
Constructor & Destructor Documentation
Logger() [1/5]
Logger (std::string name, LogLevel log_level, std::shared_ptr< Printer > printer)
Default Constructor.
Parameters
[in] name Name of the logger
[in] log_level Logger log level
[in] printer Printer to push the messages
Definition at line 31 of file Logger.cpp.
     : _name(std::move(name)), _log_level(log_level), _printers(
 {
     std::move(printer)
 }), _decorators()
 {
     // Check printer
     ARM_COMPUTE_ERROR_ON(printer == nullptr);
     // Set default message decorators
     set_default_decorators();
 }
Logger() [2/5]
Logger (std::string name, LogLevel log_level, std::vector< std::shared_ptr< Printer >> printers = {})
Default Constructor.
Parameters
[in] name Name of the logger
[in] log_level Logger log level
[in] printers Printers to push the messages
Definition at line 44 of file Logger.cpp.
     : _name(std::move(name)), _log_level(log_level), _printers(std::move(printers)), _decorators()
 {
     // Check printers
     for(const auto &p : _printers)
     {
         ARM_COMPUTE_UNUSED(p);
         ARM_COMPUTE_ERROR_ON(p == nullptr);
     }
     // Set default message decorators
     set_default_decorators();
 }
References ARM_COMPUTE_ERROR_ON, and ARM_COMPUTE_UNUSED.
Logger() [3/5]
Logger (std::string name, LogLevel log_level, std::vector< std::shared_ptr< Printer >> printers, std::vector< std::unique_ptr< IDecorator >> decorators)
Default Constructor.
Parameters
[in] name Name of the logger
[in] log_level Logger log level
[in] printers Printers to push the messages
[in] decorators Message decorators, which append information in the logged message
Definition at line 57 of file Logger.cpp.
     : _name(std::move(name)), _log_level(log_level), _printers(std::move(printers)), _decorators(std::move(decorators))
 {
     // Check printers
     for(const auto &p : _printers)
     {
         ARM_COMPUTE_UNUSED(p);
         ARM_COMPUTE_ERROR_ON(p == nullptr);
     }
     // Check decorators
     for(const auto &d : _decorators)
     {
         ARM_COMPUTE_UNUSED(d);
         ARM_COMPUTE_ERROR_ON(d == nullptr);
     }
 }
References ARM_COMPUTE_ERROR_ON, and ARM_COMPUTE_UNUSED.
Logger() [4/5]
Logger (Logger &&) default
Allow instances of this class to be moved.
Logger() [5/5]
Logger (const Logger &) delete
Prevent instances of this class from being copied (As this class contains pointers)
Member Function Documentation
add_decorator()
void add_decorator (std::unique_ptr< IDecorator > decorator)
Adds a log message decorator to the logger.
Warning
Not thread-safe
Parameters
[in] decorator
Definition at line 111 of file Logger.cpp.
 {
     ARM_COMPUTE_ERROR_ON(decorator == nullptr);
     _decorators.push_back(std::move(decorator));
 }
References ARM_COMPUTE_ERROR_ON.
add_printer()
void add_printer (std::shared_ptr< Printer > printer)
Adds a printer to the logger.
Warning
Not thread-safe
Parameters
[in] printer
Definition at line 105 of file Logger.cpp.
 {
     ARM_COMPUTE_ERROR_ON(printer == nullptr);
     _printers.push_back(std::move(printer));
 }
References ARM_COMPUTE_ERROR_ON.
log() [1/2]
void log (LogLevel log_level, const std::string & msg)
Logs a message.
Parameters
[in] log_level Log level of the message
[in] msg Message to log
Definition at line 77 of file Logger.cpp.
 {
     // Return if message shouldn't be logged
     // i.e. if log level does not match the logger's
     if(!is_loggable(log_level))
     {
         return;
     }
     // Print message to all printers
     print_all(create_log_msg(msg, log_level));
 }
References Logger::log_level().
log() [2/2]
void log (LogLevel log_level, const std::string & fmt, Ts &&... args) inline
Logs a formatted message.
Parameters
[in] log_level Log level of the message
[in] fmt Message format
[in] args Message arguments
Definition at line 162 of file Logger.h.
 {
     // Return if message shouldn't be logged
     // i.e. if log level does not match the logger's
     if(!is_loggable(log_level))
     {
         return;
     }
     // Print message to all printers
     print_all(create_log_msg(string_with_format(fmt, args...), log_level));
 }
References Logger::log_level(), and arm_compute::logging::string_with_format().
log_level()
LogLevel log_level () const
Returns logger's log level.
Returns
Logger's log level
Definition at line 95 of file Logger.cpp.
 {
     return _log_level;
 }
Referenced by Logger::log(), and Logger::set_log_level().
name()
std::string name () const
Returns logger's name.
Returns
Logger's name
Definition at line 100 of file Logger.cpp.
 {
     return _name;
 }
operator=() [1/2]
Logger& operator= (const Logger &) delete
Prevent instances of this class from being copied (As this class contains pointers)
operator=() [2/2]
Logger& operator= (Logger &&) default
Allow instances of this class to be moved.
set_log_level()
void set_log_level (LogLevel log_level)
Sets log level of the logger.
Warning
Not thread-safe
Parameters
[in] log_level Log level to set
Definition at line 90 of file Logger.cpp.
 {
     _log_level = log_level;
 }
References Logger::log_level().
The documentation for this class was generated from the following files:
arm_compute/core/utils/logging/Logger.h
src/core/utils/logging/Logger.cpp