Compute Library: YOLOV2ActivationLayerRELUDataset Class Reference
YOLOV2ActivationLayerRELUDataset Class Reference final
#include <YOLOV2ActivationLayerDataset.h>
Public Member Functions
YOLOV2ActivationLayerRELUDataset ()
YOLOV2ActivationLayerRELUDataset (YOLOV2ActivationLayerRELUDataset &&)=default
~YOLOV2ActivationLayerRELUDataset ()=default
Public Member Functions inherited from CartesianProductDataset< framework::dataset::InitializerListDataset< TensorShape >, framework::dataset::SingletonDataset< ActivationLayerInfo > >
CartesianProductDataset (framework::dataset::InitializerListDataset< TensorShape > &&dataset1, framework::dataset::SingletonDataset< ActivationLayerInfo > &&dataset2)
Construct dataset from the given datasets.
CartesianProductDataset (CartesianProductDataset &&)=default
iterator begin () const
Iterator pointing at the begin of the dataset.
int size () const
Size of the dataset.
Public Member Functions inherited from Dataset
Dataset (Dataset &&)=default
Additional Inherited Members
Public Types inherited from CartesianProductDataset< framework::dataset::InitializerListDataset< TensorShape >, framework::dataset::SingletonDataset< ActivationLayerInfo > >
using type = decltype(std::tuple_cat(*std::declval< iter1_type >(),*std::declval< iter2_type >()))
Type of the dataset.
Detailed Description
Definition at line 40 of file YOLOV2ActivationLayerDataset.h.
Constructor & Destructor Documentation
YOLOV2ActivationLayerRELUDataset () inline
Definition at line 44 of file YOLOV2ActivationLayerDataset.h.
References arm_compute::test::framework::dataset::make(), ActivationLayerInfo::RELU, arm_compute::U, and YOLOV2ActivationLayerRELUDataset::~YOLOV2ActivationLayerRELUDataset().
Referenced by YOLOV2ActivationLayerDataset::YOLOV2ActivationLayerDataset().
         : CartesianProductDataset
     {
         framework::dataset::make("Shape", { // relu1
             TensorShape(416U, 416U, 32U),
             // relu2
             TensorShape(208U, 208U, 64U),
             // relu3, relu5
             TensorShape(104U, 104U, 128U),
             // relu4
             TensorShape(104U, 104U, 64U),
             // relu6, relu8
             TensorShape(52U, 52U, 256U),
             // relu7
             TensorShape(52U, 52U, 128U),
             // relu9, relu11, relu13
             TensorShape(26U, 26U, 512U),
             // relu10, relu12
             TensorShape(26U, 26U, 256U),
             // relu14, relu16, relu18, relu19, relu20, relu21
             TensorShape(13U, 13U, 1024U),
             // relu15, relu17
             TensorShape(13U, 13U, 512U) }),
         framework::dataset::make("Info", ActivationLayerInfo(ActivationLayerInfo::ActivationFunction::RELU))
     }
     {
     }
YOLOV2ActivationLayerRELUDataset (YOLOV2ActivationLayerRELUDataset &&) default
~YOLOV2ActivationLayerRELUDataset () default
Referenced by YOLOV2ActivationLayerRELUDataset::YOLOV2ActivationLayerRELUDataset().
The documentation for this class was generated from the following file:
tests/datasets/system_tests/yolo/v2/YOLOV2ActivationLayerDataset.h