Compute Library: CLComparison Class Reference
CLComparison Class Reference
Basic function to run CLComparisonKernel.
#include <CLComparison.h>
Public Member Functions
void configure (ICLTensor *input1, ICLTensor *input2, ICLTensor *output, ComparisonOperation operation)
Initialise the kernel's inputs and outputs.
Public Member Functions inherited from ICLSimpleFunction
ICLSimpleFunction ()
Default constructor.
void run () override final
Run the kernels contained in the function.
Public Member Functions inherited from IFunction
virtual ~IFunction ()=default
Destructor.
virtual void prepare ()
Prepare the function for executing.
Static Public Member Functions
static Status validate (const ITensorInfo *input1, const ITensorInfo *input2, const ITensorInfo *output, ComparisonOperation operation)
Static function to check if given info will lead to a valid configuration of CLComparison.
Detailed Description
Basic function to run CLComparisonKernel.
Definition at line 36 of file CLComparison.h.
Member Function Documentation
configure()
void configure (ICLTensor * input1, ICLTensor * input2, ICLTensor * output, ComparisonOperation operation)
Initialise the kernel's inputs and outputs.
Parameters
[in] input1 Source tensor. Data types supported: U8/S8/QASYMM8/U16/S16/U32/S32/F16/F32. The input1 tensor is [in, out] because its TensorInfo might be modified inside the kernel in case of broadcasting of dimension 0.
[in] input2 Source tensor. Data types supported: Same as input1. The input2 tensor is [in, out] because its TensorInfo might be modified inside the kernel in case of broadcasting of dimension 0.
[out] output Destination tensor. Data types supported: U8.
[out] operation Comparison operation to be used.
Definition at line 33 of file CLComparison.cpp.
 {
     auto k = arm_compute::support::cpp14::make_unique<CLComparisonKernel>();
     k->configure(input1, input2, output, operation);
     _kernel = std::move(k);
     if(output->info()->dimension(0) > 1)
     {
         ICLTensor *broadcasted_info = (input1->info()->dimension(0) == 1) ? input1 : input2;
         if(broadcasted_info->info()->dimension(0) == 1)
         {
             _border_handler.configure(broadcasted_info, _kernel->border_size(), BorderMode::REPLICATE);
         }
     }
 }
References ITensorInfo::dimension(), ITensor::info(), and arm_compute::REPLICATE.
validate()
Status validate (const ITensorInfo * input1, const ITensorInfo * input2, const ITensorInfo * output, ComparisonOperation operation) static
Static function to check if given info will lead to a valid configuration of CLComparison.
Parameters
[in] input1 Source tensor. Data types supported: U8/S8/QASYMM8/U16/S16/U32/S32/F16/F32.
[in] input2 Source tensor. Data types supported: Same as input1.
[in] output Destination tensor. Data types supported: U8.
[out] operation Comparison operation to be used.
Returns
a status
Definition at line 50 of file CLComparison.cpp.
 {
     return CLComparisonKernel::validate(input1, input2, output, operation);
 }
References CLComparisonKernel::validate().
The documentation for this class was generated from the following files:
arm_compute/runtime/CL/functions/CLComparison.h
src/runtime/CL/functions/CLComparison.cpp