Compute Library: NEDerivative Class Reference
NEDerivative Class Reference
Basic function to execute first order derivative operator.
#include <NEDerivative.h>
Public Member Functions
NEDerivative ()
Default constructor.
void configure (ITensor *input, ITensor *output_x, ITensor *output_y, BorderMode border_mode, uint8_t constant_border_value=0)
Initialise the function's source, destinations and border mode.
void run () override
Run the kernels contained in the function.
Public Member Functions inherited from IFunction
virtual ~IFunction ()=default
Destructor.
virtual void prepare ()
Prepare the function for executing.
Detailed Description
Basic function to execute first order derivative operator.
This function calls the following NEON kernels:
NEFillBorderKernel (executed if border_mode == CONSTANT or border_mode == REPLICATE)
NEDerivativeKernel
Definition at line 44 of file NEDerivative.h.
Constructor & Destructor Documentation
NEDerivative()
NEDerivative ()
Default constructor.
Definition at line 34 of file NEDerivative.cpp.
     : _kernel(), _border_handler()
 {
 }
Member Function Documentation
configure()
void configure (ITensor * input, ITensor * output_x, ITensor * output_y, BorderMode border_mode, uint8_t constant_border_value = 0)
Initialise the function's source, destinations and border mode.
Note
At least one of output_x or output_y must be not NULL.
Parameters
[in,out] input Source tensor. Data type supported: U8. (Written to only for border_mode != UNDEFINED)
[out] output_x (optional) Destination tensor. Derivative along the X direction. Data type supported: S16.
[out] output_y (optional) Destination tensor. Derivative along the Y direction. Data type supported: S16.
[in] border_mode Border mode to use
[in] constant_border_value (Optional) Constant value to use for borders if border_mode is set to CONSTANT.
Definition at line 39 of file NEDerivative.cpp.
 {
     ARM_COMPUTE_ERROR_ON_DATA_TYPE_CHANNEL_NOT_IN(input, 1, DataType::U8);
     ARM_COMPUTE_ERROR_ON((output_x == nullptr) && (output_y == nullptr));
     _kernel.configure(input, output_x, output_y, border_mode == BorderMode::UNDEFINED);
     _border_handler.configure(input, BorderSize(1), border_mode, PixelValue(constant_border_value));
 }
References ARM_COMPUTE_ERROR_ON, ARM_COMPUTE_ERROR_ON_DATA_TYPE_CHANNEL_NOT_IN, arm_compute::test::validation::border_mode, NEDerivativeKernel::configure(), NEFillBorderKernel::configure(), arm_compute::U8, and arm_compute::UNDEFINED.
Referenced by NEHOGGradient::configure().
run()
void run () override virtual
Run the kernels contained in the function.
For NEON kernels:
Multi-threading is used for the kernels which are parallelisable.
By default std::thread::hardware_concurrency() threads are used.
Note
CPPScheduler::set_num_threads() can be used to manually set the number of threads
For OpenCL kernels:
All the kernels are enqueued on the queue associated with CLScheduler.
The queue is then flushed.
Note
The function will not block until the kernels are executed. It is the user's responsibility to wait.
Will call prepare() on first run if hasn't been done
Implements IFunction.
Definition at line 48 of file NEDerivative.cpp.
 {
     NEScheduler::get().schedule(&_border_handler, Window::DimZ);
     NEScheduler::get().schedule(&_kernel, Window::DimY);
 }
References Window::DimY, Window::DimZ, Scheduler::get(), and IScheduler::schedule().
Referenced by NEHOGGradient::run().
The documentation for this class was generated from the following files:
arm_compute/runtime/NEON/functions/NEDerivative.h
src/runtime/NEON/functions/NEDerivative.cpp