Compute Library: GraphContext Class Reference
GraphContext Class Reference final
Graph context.
#include <GraphContext.h>
Public Member Functions
GraphContext ()
Constructor.
~GraphContext ()
Destructor.
GraphContext (const GraphContext &)=delete
Prevent instances of this class from being copied (As this class contains pointers)
GraphContext (GraphContext &&)=default
Default move constructor.
GraphContext & operator= (const GraphContext &)=delete
Prevent instances of this class from being copied (As this class contains pointers)
GraphContext & operator= (GraphContext &&)=default
Default move assignment operator.
const GraphConfig & config () const
Graph configuration accessor.
void set_config (const GraphConfig &config)
Sets graph configuration.
bool insert_memory_management_ctx (MemoryManagerContext &&memory_ctx)
Inserts a memory manager context.
MemoryManagerContext * memory_management_ctx (Target target)
Gets a memory manager context for a given target.
std::map< Target, MemoryManagerContext > & memory_managers ()
Gets the memory managers map.
void finalize ()
Finalizes memory managers in graph context.
Detailed Description
Graph context.
Definition at line 49 of file GraphContext.h.
Constructor & Destructor Documentation
GraphContext() [1/3]
GraphContext ()
Constructor.
Definition at line 34 of file GraphContext.cpp.
     : _config(), _memory_managers()
 {
 }
~GraphContext()
~GraphContext ()
Destructor.
Definition at line 39 of file GraphContext.cpp.
 {
     _memory_managers.clear();
     release_default_graph_context(*this);
 }
References arm_compute::graph::release_default_graph_context().
GraphContext() [2/3]
GraphContext (const GraphContext &) delete
Prevent instances of this class from being copied (As this class contains pointers)
GraphContext() [3/3]
GraphContext (GraphContext &&) default
Default move constructor.
Member Function Documentation
config()
const GraphConfig & config () const
Graph configuration accessor.
Note
Every alteration has to be done before graph finalization
Returns
The graph configuration
Definition at line 45 of file GraphContext.cpp.
 {
     return _config;
 }
Referenced by GraphManager::finalize_graph(), arm_compute::graph::backends::get_memory_manager(), GraphContext::set_config(), NEDeviceBackend::setup_backend_context(), and CLDeviceBackend::setup_backend_context().
finalize()
void finalize ()
Finalizes memory managers in graph context.
Definition at line 77 of file GraphContext.cpp.
 {
     const size_t num_pools = 1;
     for(auto &mm_obj : _memory_managers)
     {
         ARM_COMPUTE_ERROR_ON(!mm_obj.second.allocator);
         // Finalize intra layer memory manager
         if(mm_obj.second.intra_mm != nullptr)
         {
             mm_obj.second.intra_mm->populate(*mm_obj.second.allocator, num_pools);
         }
         // Finalize cross layer memory manager
         if(mm_obj.second.cross_mm != nullptr)
         {
             mm_obj.second.cross_mm->populate(*mm_obj.second.allocator, num_pools);
         }
     }
 }
References ARM_COMPUTE_ERROR_ON.
Referenced by GraphManager::finalize_graph().
insert_memory_management_ctx()
bool insert_memory_management_ctx (MemoryManagerContext && memory_ctx)
Inserts a memory manager context.
Parameters
[in] memory_ctx Memory manage context
Returns
If the insertion succeeded else false
Definition at line 55 of file GraphContext.cpp.
 {
     Target target = memory_ctx.target;
     if(target == Target::UNSPECIFIED || _memory_managers.find(target) != std::end(_memory_managers))
     {
         return false;
     }
     _memory_managers[target] = std::move(memory_ctx);
     return true;
 }
References arm_compute::graph::UNSPECIFIED.
Referenced by NEDeviceBackend::setup_backend_context(), GCDeviceBackend::setup_backend_context(), and CLDeviceBackend::setup_backend_context().
memory_management_ctx()
MemoryManagerContext * memory_management_ctx (Target target)
Gets a memory manager context for a given target.
Parameters
[in] target To retrieve the management context
Returns
Management context for the target if exists else nullptr
Definition at line 67 of file GraphContext.cpp.
 {
     return (_memory_managers.find(target) != std::end(_memory_managers)) ? &_memory_managers[target] : nullptr;
 }
Referenced by arm_compute::graph::detail::configure_transition_manager(), arm_compute::graph::backends::get_memory_manager(), NEDeviceBackend::setup_backend_context(), GCDeviceBackend::setup_backend_context(), and CLDeviceBackend::setup_backend_context().
memory_managers()
std::map< Target, MemoryManagerContext > & memory_managers ()
Gets the memory managers map.
Returns
Memory manager contexts
Definition at line 72 of file GraphContext.cpp.
 {
     return _memory_managers;
 }
Referenced by arm_compute::graph::detail::call_all_tasks().
operator=() [1/2]
GraphContext& operator= (const GraphContext &) delete
Prevent instances of this class from being copied (As this class contains pointers)
operator=() [2/2]
GraphContext& operator= (GraphContext &&) default
Default move assignment operator.
set_config()
void set_config (const GraphConfig & config)
Sets graph configuration.
Parameters
[in] config Configuration to use
Definition at line 50 of file GraphContext.cpp.
 {
     _config = config;
 }
References GraphContext::config().
Referenced by Stream::finalize().
The documentation for this class was generated from the following files:
arm_compute/graph/GraphContext.h
src/graph/GraphContext.cpp