Compute Library: FusedDepthwiseConvolutionBatchNormalizationFunction< TargetInfo, FusedLayerTypes > Class Template Reference
FusedDepthwiseConvolutionBatchNormalizationFunction< TargetInfo, FusedLayerTypes > Class Template Reference
Wrapper function to first apply {NE, CL}BatchNormalizationLayer on the weights and then run {NE, CL}DepthwiseConvolutionLayer with the modified weights.
#include <FusedDepthwiseConvolutionBatchNormalizationFunction.h>
Public Types
using TensorType = typename TargetInfo::TensorType
using TensorConcreteType = typename TargetInfo::TensorConcreteType
Public Member Functions
FusedDepthwiseConvolutionBatchNormalizationFunction ()
void configure (TensorType *input, TensorType *weights, TensorType *bias, TensorType *output, const TensorType *mean, const TensorType *var, const TensorType *beta, const TensorType *gamma, float epsilon, const PadStrideInfo &conv_info, unsigned int depth_multiplier, ActivationLayerInfo const &fused_act)
Set the input and output tensors.
void run ()
Run the kernels contained in the function.
void prepare ()
Prepare the function for executing.
Public Member Functions inherited from IFunction
virtual ~IFunction ()=default
Destructor.
Detailed Description
template<typename TargetInfo, typename FusedLayerTypes>
class arm_compute::graph::backends::FusedDepthwiseConvolutionBatchNormalizationFunction< TargetInfo, FusedLayerTypes >
Wrapper function to first apply {NE, CL}BatchNormalizationLayer on the weights and then run {NE, CL}DepthwiseConvolutionLayer with the modified weights.
Definition at line 39 of file FusedDepthwiseConvolutionBatchNormalizationFunction.h.
Member Typedef Documentation
TensorConcreteType
using TensorConcreteType = typename TargetInfo::TensorConcreteType
Definition at line 43 of file FusedDepthwiseConvolutionBatchNormalizationFunction.h.
TensorType
using TensorType = typename TargetInfo::TensorType
Definition at line 42 of file FusedDepthwiseConvolutionBatchNormalizationFunction.h.
Constructor & Destructor Documentation
FusedDepthwiseConvolutionBatchNormalizationFunction()
FusedDepthwiseConvolutionBatchNormalizationFunction () inline
Definition at line 45 of file FusedDepthwiseConvolutionBatchNormalizationFunction.h.
         : _depth_conv_layer(), _fused_batch_norm_layer(), _fused_bias(), _is_prepared(false)
     {
     }
Member Function Documentation
configure()
void configure (TensorType * input, TensorType * weights, TensorType * bias, TensorType * output, const TensorType * mean, const TensorType * var, const TensorType * beta, const TensorType * gamma, float epsilon, const PadStrideInfo & conv_info, unsigned int depth_multiplier, ActivationLayerInfo const & fused_act) inline
Set the input and output tensors.
Parameters
[in] input Source tensor. 3 lower dimensions represent a single input [width, height, IFM], while every optional dimension from 4 and above represent a batch of inputs. Data types supported: F16/F32.
[in] weights Weights tensor. These are 3D tensors with shape [kernel_x, kernel_y, IFM]. Data type supported: Same as input.
[in] bias Biases tensor. Shared biases supported. Biases are 1D tensor with dimensions [IFM]. Data type supported: Should match input data type.
[out] output Destination tensor. 3 lower dimensions represent a single output [width, height, OFM], while the rest represent batch of outputs. Data types supported: Same as input.
[in] mean Mean values tensor. 1 dimension with size equal to the feature maps [FM]. Data types supported: Same as input
[in] var Variance values tensor. 1 dimension with size equal to the feature maps [FM]. Data types supported: Same as input
[in] beta Beta values tensor info. 1 dimension with size equal to the feature maps [FM]. If not provided, default value for beta is 0. Data types supported: Same as input
[in] gamma Gamma values tensor info. 1 dimension with size equal to the feature maps [FM]. If not provided, default value for gamma is 1. Data types supported: Same as input
[in] epsilon Small value to avoid division with zero. Default value is 0.001f.
[in] conv_info Contains padding and stride information described in PadStrideInfo.
[in] depth_multiplier Multiplier to apply to the input's depth in order to retrieve the output's depth. Defaults to 1.
[in] fused_act Activation layer information in case of a fused activation.
Definition at line 70 of file FusedDepthwiseConvolutionBatchNormalizationFunction.h.
     {
         // We don't run any validate, as we assume that the layers have been already validated
         const bool        has_bias = (bias != nullptr);
         const TensorType *bias_to_use;
         // We check if the layer has a bias. If yes, use it in-place. If not, we need to create one
         // as batch normalization might end up with a bias != 0
         if(has_bias)
         {
             _fused_batch_norm_layer.configure(weights, mean, var, nullptr, nullptr, bias, beta, gamma, epsilon, FuseBatchNormalizationType::DEPTHWISECONVOLUTION);
             bias_to_use = bias;
         }
         else
         {
             _fused_batch_norm_layer.configure(weights, mean, var, nullptr, &_fused_bias, nullptr, beta, gamma, epsilon, FuseBatchNormalizationType::DEPTHWISECONVOLUTION);
             bias_to_use = &_fused_bias;
         }
         _depth_conv_layer.configure(input, weights, bias_to_use, output, conv_info, depth_multiplier, fused_act.enabled() ? fused_act : ActivationLayerInfo());
         if(!has_bias)
         {
             _fused_bias.allocator()->allocate();
         }
     }
References arm_compute::test::validation::bias, arm_compute::test::validation::conv_info, arm_compute::DEPTHWISECONVOLUTION, ActivationLayerInfo::enabled(), epsilon, arm_compute::test::validation::has_bias, and arm_compute::test::validation::weights.
prepare()
void prepare () inline virtual
Prepare the function for executing.
Any one off pre-processing step required by the function is handled here
Note
Prepare stage might not need all the function's buffers' backing memory to be available in order to execute
Reimplemented from IFunction.
Definition at line 112 of file FusedDepthwiseConvolutionBatchNormalizationFunction.h.
     {
         if(!_is_prepared)
         {
             _fused_batch_norm_layer.run();
             _is_prepared = true;
         }
     }
Referenced by FusedDepthwiseConvolutionBatchNormalizationFunction< TargetInfo, FusedLayerTypes >::run().
run()
void run () inline virtual
Run the kernels contained in the function.
For NEON kernels:
Multi-threading is used for the kernels which are parallelisable.
By default std::thread::hardware_concurrency() threads are used.
Note
CPPScheduler::set_num_threads() can be used to manually set the number of threads
For OpenCL kernels:
All the kernels are enqueued on the queue associated with CLScheduler.
The queue is then flushed.
Note
The function will not block until the kernels are executed. It is the user's responsibility to wait.
Will call prepare() on first run if hasn't been done
Implements IFunction.
Definition at line 106 of file FusedDepthwiseConvolutionBatchNormalizationFunction.h.
     {
         prepare();
         _depth_conv_layer.run();
     }
References FusedDepthwiseConvolutionBatchNormalizationFunction< TargetInfo, FusedLayerTypes >::prepare().
The documentation for this class was generated from the following file:
arm_compute/graph/backends/FusedDepthwiseConvolutionBatchNormalizationFunction.h