Compute Library: CPPDetectionWindowNonMaximaSuppressionKernel Class Reference
CPPDetectionWindowNonMaximaSuppressionKernel Class Reference
CPP kernel to perform in-place computation of euclidean distance on IDetectionWindowArray.
#include <CPPDetectionWindowNonMaximaSuppressionKernel.h>
Public Member Functions
const char * name () const override
Name of the kernel.
CPPDetectionWindowNonMaximaSuppressionKernel ()
Default constructor.
CPPDetectionWindowNonMaximaSuppressionKernel (const CPPDetectionWindowNonMaximaSuppressionKernel &)=delete
Prevent instances of this class from being copied (As this class contains pointers)
CPPDetectionWindowNonMaximaSuppressionKernel & operator= (const CPPDetectionWindowNonMaximaSuppressionKernel &)=delete
Prevent instances of this class from being copied (As this class contains pointers)
CPPDetectionWindowNonMaximaSuppressionKernel (CPPDetectionWindowNonMaximaSuppressionKernel &&)=default
Allow instances of this class to be moved.
CPPDetectionWindowNonMaximaSuppressionKernel & operator= (CPPDetectionWindowNonMaximaSuppressionKernel &&)=default
Allow instances of this class to be moved.
void configure (IDetectionWindowArray *input_output, float min_distance)
Initialise the kernel's input, output and the euclidean minimum distance.
void run (const Window &window, const ThreadInfo &info) override
Execute the kernel on the passed window.
bool is_parallelisable () const override
Indicates whether or not the kernel is parallelisable.
Public Member Functions inherited from ICPPKernel
virtual ~ICPPKernel ()=default
Default destructor.
Public Member Functions inherited from IKernel
IKernel ()
Constructor.
virtual ~IKernel ()=default
Destructor.
virtual BorderSize border_size () const
The size of the border for that kernel.
const Window & window () const
The maximum window the kernel can be executed on.
Detailed Description
CPP kernel to perform in-place computation of euclidean distance on IDetectionWindowArray.
Note
This kernel is meant to be used alongside HOG or other object detection algorithms to perform a non-maxima suppression on a IDetectionWindowArray
Definition at line 39 of file CPPDetectionWindowNonMaximaSuppressionKernel.h.
Constructor & Destructor Documentation
CPPDetectionWindowNonMaximaSuppressionKernel() [1/3]
CPPDetectionWindowNonMaximaSuppressionKernel ()
Default constructor.
Definition at line 61 of file CPPDetectionWindowNonMaximaSuppressionKernel.cpp.
     : _input_output(nullptr), _min_distance(0.0f)
 {
 }
CPPDetectionWindowNonMaximaSuppressionKernel() [2/3]
CPPDetectionWindowNonMaximaSuppressionKernel (const CPPDetectionWindowNonMaximaSuppressionKernel &) delete
Prevent instances of this class from being copied (As this class contains pointers)
CPPDetectionWindowNonMaximaSuppressionKernel() [3/3]
CPPDetectionWindowNonMaximaSuppressionKernel (CPPDetectionWindowNonMaximaSuppressionKernel &&) default
Allow instances of this class to be moved.
Member Function Documentation
configure()
void configure (IDetectionWindowArray * input_output, float min_distance)
Initialise the kernel's input, output and the euclidean minimum distance.
Attention
: If IDetectionWindowArray is passed to the kernel, the map() and unmap() methods IDetectionWindowArray must be called respectively before and after the run() method of CPPDetectionWindowNonMaximaSuppressionKernel
Parameters
[in,out] input_output Input/Output array of DetectionWindow
[in] min_distance Radial Euclidean distance for non-maxima suppression
Definition at line 71 of file CPPDetectionWindowNonMaximaSuppressionKernel.cpp.
 {
     ARM_COMPUTE_ERROR_ON(nullptr == input_output);
     _input_output = input_output;
     _min_distance = min_distance;
     IKernel::configure(Window()); // Default 1 iteration window
 }
References ARM_COMPUTE_ERROR_ON.
Referenced by CLHOGMultiDetection::configure().
is_parallelisable()
bool is_parallelisable () const override virtual
Indicates whether or not the kernel is parallelisable.
If the kernel is parallelisable then the window returned by window() can be split into sub-windows which can then be run in parallel.
If the kernel is not parallelisable then only the window returned by window() can be passed to run()
Returns
True if the kernel is parallelisable
Reimplemented from IKernel.
Definition at line 66 of file CPPDetectionWindowNonMaximaSuppressionKernel.cpp.
 {
     return false;
 }
name()
const char* name () const inline override virtual
Name of the kernel.
Returns
Kernel name
Implements ICPPKernel.
Definition at line 42 of file CPPDetectionWindowNonMaximaSuppressionKernel.h.
     {
         return "CPPDetectionWindowNonMaximaSuppressionKernel";
     }
operator=() [1/2]
CPPDetectionWindowNonMaximaSuppressionKernel& operator= (const CPPDetectionWindowNonMaximaSuppressionKernel &) delete
Prevent instances of this class from being copied (As this class contains pointers)
operator=() [2/2]
CPPDetectionWindowNonMaximaSuppressionKernel& operator= (CPPDetectionWindowNonMaximaSuppressionKernel &&) default
Allow instances of this class to be moved.
run()
void run (const Window & window, const ThreadInfo & info) override virtual
Execute the kernel on the passed window.
Warning
If is_parallelisable() returns false then the passed window must be equal to window()
Note
The window has to be a region within the window returned by the window() method
The width of the window has to be a multiple of num_elems_processed_per_iteration().
Parameters
[in] window Region on which to execute the kernel. (Must be a region of the window returned by window())
[in] info Info about executing thread and CPU.
Implements ICPPKernel.
Definition at line 81 of file CPPDetectionWindowNonMaximaSuppressionKernel.cpp.
 {
     ARM_COMPUTE_UNUSED(info);
     ARM_COMPUTE_UNUSED(window);
     ARM_COMPUTE_ERROR_ON_UNCONFIGURED_KERNEL(this);
     ARM_COMPUTE_ERROR_ON_MISMATCHING_WINDOWS(IKernel::window(), window);
     ARM_COMPUTE_ERROR_ON(_input_output->buffer() == nullptr);
     const size_t num_candidates = _input_output->num_values();
     size_t       num_detections = 0;
     // Sort list of candidates by idx_class and then score
     std::sort(_input_output->buffer(), _input_output->buffer() + num_candidates, compare_detection_window);
     const float min_distance_pow2 = _min_distance * _min_distance;
     // Euclidean distance
     for(size_t i = 0; i < num_candidates; ++i)
     {
         if(0.0f != _input_output->at(i).score)
         {
             DetectionWindow cur;
             cur.x         = _input_output->at(i).x;
             cur.y         = _input_output->at(i).y;
             cur.width     = _input_output->at(i).width;
             cur.height    = _input_output->at(i).height;
             cur.idx_class = _input_output->at(i).idx_class;
             cur.score     = _input_output->at(i).score;
             // Store window
             _input_output->at(num_detections) = cur;
             ++num_detections;
             const float xc = cur.x + cur.width * 0.5f;
             const float yc = cur.y + cur.height * 0.5f;
             for(size_t k = i + 1; k < (num_candidates) && (cur.idx_class == _input_output->at(k).idx_class); ++k)
             {
                 const float xn = _input_output->at(k).x + _input_output->at(k).width * 0.5f;
                 const float yn = _input_output->at(k).y + _input_output->at(k).height * 0.5f;
                 const float dx = std::fabs(xn - xc);
                 const float dy = std::fabs(yn - yc);
                 if(dx < _min_distance && dy < _min_distance)
                 {
                     const float d = dx * dx + dy * dy;
                     if(d < min_distance_pow2)
                     {
                         // Invalidate detection window
                         _input_output->at(k).score = 0.0f;
                     }
                 }
             }
         }
     }
     _input_output->resize(num_detections);
 }
References ARM_COMPUTE_ERROR_ON, ARM_COMPUTE_ERROR_ON_MISMATCHING_WINDOWS, ARM_COMPUTE_ERROR_ON_UNCONFIGURED_KERNEL, ARM_COMPUTE_UNUSED, IArray< T >::at(), IArray< T >::buffer(), DetectionWindow::height, DetectionWindow::idx_class, arm_compute::test::validation::info, IArray< T >::num_values(), IArray< T >::resize(), DetectionWindow::score, DetectionWindow::width, IKernel::window(), DetectionWindow::x, and DetectionWindow::y.
The documentation for this class was generated from the following files:
arm_compute/core/CPP/kernels/CPPDetectionWindowNonMaximaSuppressionKernel.h
src/core/CPP/kernels/CPPDetectionWindowNonMaximaSuppressionKernel.cpp