Compute Library: Program Class Reference
Program Class Reference
Program class.
#include <CLKernelLibrary.h>
Public Member Functions
Program ()
Default constructor.
Program (cl::Context context, std::string name, std::string source)
Construct program from source file.
Program (cl::Context context, cl::Device device, std::string name, std::vector< unsigned char > binary)
Construct program from binary file.
Program (const Program &)=default
Default Copy Constructor.
Program (Program &&)=default
Default Move Constructor.
Program & operator= (const Program &)=default
Default copy assignment operator.
Program & operator= (Program &&)=default
Default move assignment operator.
std::string name () const
Returns program name.
operator cl::Program () const
User-defined conversion to the underlying CL program.
cl::Program build (const std::string &build_options="") const
Build the underlying CL program.
Static Public Member Functions
static bool build (const cl::Program &program, const std::string &build_options="")
Build the given CL program.
Detailed Description
Program class.
Definition at line 83 of file CLKernelLibrary.h.
Constructor & Destructor Documentation
Program() [1/5]
Program ()
Default constructor.
Definition at line 79 of file CLKernelLibrary.cpp.
     : _context(), _device(), _is_binary(false), _name(), _source(), _binary()
 {
 }
Program() [2/5]
Program (cl::Context context, std::string name, std::string source)
Construct program from source file.
Parameters
[in] context CL context used to create the program.
[in] name Program name.
[in] source Program source.
Definition at line 84 of file CLKernelLibrary.cpp.
     : _context(std::move(context)), _device(), _is_binary(false), _name(std::move(name)), _source(std::move(source)), _binary()
 {
 }
Program() [3/5]
Program (cl::Context context, cl::Device device, std::string name, std::vector< unsigned char > binary)
Construct program from binary file.
Parameters
[in] context CL context used to create the program.
[in] device CL device for which the programs are created.
[in] name Program name.
[in] binary Program binary.
Definition at line 89 of file CLKernelLibrary.cpp.
     : _context(std::move(context)), _device(std::move(device)), _is_binary(true), _name(std::move(name)), _source(), _binary(std::move(binary))
 {
 }
Program() [4/5]
Program (const Program &) default
Default Copy Constructor.
Program() [5/5]
Program (Program &&) default
Default Move Constructor.
Member Function Documentation
build() [1/2]
bool build (const cl::Program & program, const std::string & build_options = "") static
Build the given CL program.
Parameters
[in] program The CL program to build.
[in] build_options Options to build the CL program.
Returns
True if the CL program builds successfully.
Definition at line 106 of file CLKernelLibrary.cpp.
 {
     try
     {
         return program.build(build_options.c_str()) == CL_SUCCESS;
     }
     catch(const cl::Error &e)
     {
         cl_int     err        = CL_SUCCESS;
         const auto build_info = program.getBuildInfo<CL_PROGRAM_BUILD_LOG>(&err);
         for(auto &pair : build_info)
         {
             std::cerr << pair.second << std::endl;
         }
         return false;
     }
 }
Referenced by Program::build(), and CLKernelLibrary::create_kernel().
build() [2/2]
cl::Program build (const std::string & build_options = "") const
Build the underlying CL program.
Parameters
[in] build_options Options used to build the CL program.
Returns
A reference to itself.
Definition at line 126 of file CLKernelLibrary.cpp.
 {
     cl::Program cl_program = static_cast<cl::Program>(*this);
     build(cl_program, build_options);
     return cl_program;
 }
References Program::build().
name()
std::string name () const inline
Returns program name.
Returns
Program's name.
Definition at line 115 of file CLKernelLibrary.h.
     {
         return _name;
     }
operator cl::Program()
operator cl::Program () const explicit
User-defined conversion to the underlying CL program.
Returns
The CL program object.
Definition at line 94 of file CLKernelLibrary.cpp.
 {
     if(_is_binary)
     {
         return cl::Program(_context, { _device }, { _binary });
     }
     else
     {
         return cl::Program(_context, _source, false);
     }
 }
operator=() [1/2]
Program& operator= (const Program &) default
Default copy assignment operator.
operator=() [2/2]
Program& operator= (Program &&) default
Default move assignment operator.
The documentation for this class was generated from the following files:
arm_compute/core/CL/CLKernelLibrary.h
src/core/CL/CLKernelLibrary.cpp