Compute Library: SchedulerTimer Class Reference
SchedulerTimer Class Reference
Instrument creating measurements based on the information returned by clGetEventProfilingInfo for each OpenCL kernel executed.
#include <SchedulerTimer.h>
Data Structures
struct kernel_info
Public Member Functions
SchedulerTimer (const SchedulerTimer &)=delete
SchedulerTimer & operator= (const SchedulerTimer &)=delete
SchedulerTimer (ScaleFactor scale_factor)
std::string id () const override
Identifier for the instrument.
void start () override
Start measuring.
void stop () override
Stop measuring.
Instrument::MeasurementsMap measurements () const override
Return the latest measurement.
Public Member Functions inherited from Instrument
Instrument ()=default
Instrument (const Instrument &)=default
Instrument (Instrument &&)=default
Instrument & operator= (const Instrument &)=default
Instrument & operator= (Instrument &&)=default
virtual ~Instrument ()=default
Additional Inherited Members
Public Types inherited from Instrument
using MeasurementsMap = std::map< std::string, Measurement >
Static Public Member Functions inherited from Instrument
template<typename T , ScaleFactor scale>
static std::unique_ptr< Instrument > make_instrument ()
Helper function to create an instrument of the given type.
Detailed Description
Instrument creating measurements based on the information returned by clGetEventProfilingInfo for each OpenCL kernel executed.
Definition at line 38 of file SchedulerTimer.h.
Constructor & Destructor Documentation
SchedulerTimer (const SchedulerTimer &) delete
SchedulerTimer (ScaleFactor scale_factor)
Definition at line 77 of file SchedulerTimer.cpp.
     : _kernels(), _real_scheduler(nullptr), _real_scheduler_type(), _scale_factor(scale_factor)
 {
 }
Member Function Documentation
std::string id () const override virtual
Identifier for the instrument.
Implements Instrument.
Definition at line 35 of file SchedulerTimer.cpp.
References arm_compute::test::validation::info(), SchedulerTimer::kernel_info::measurements, SchedulerTimer::kernel_info::name, and ICPPKernel::name().
 {
     return "SchedulerTimer";
 }
Instrument::MeasurementsMap measurements () const override virtual
Return the latest measurement.
Implements Instrument.
Definition at line 103 of file SchedulerTimer.cpp.
References arm_compute::support::cpp11::to_string().
 {
     MeasurementsMap measurements;
     unsigned int    kernel_number = 0;
     for(auto kernel : _kernels)
     {
         measurements.emplace(kernel.name + " #" + support::cpp11::to_string(kernel_number++), kernel.measurements.begin()->second);
     }
     return measurements;
 }
SchedulerTimer& operator= (const SchedulerTimer &) delete
void start () override virtual
Start measuring.
Implements Instrument.
Definition at line 82 of file SchedulerTimer.cpp.
References ARM_COMPUTE_ERROR_ON, Scheduler::CUSTOM, Scheduler::get(), Scheduler::get_type(), and Scheduler::set().
 {
     ARM_COMPUTE_ERROR_ON(_real_scheduler != nullptr);
     _real_scheduler_type = Scheduler::get_type();
     //Note: We can't currently replace a custom scheduler
     if(_real_scheduler_type != Scheduler::Type::CUSTOM)
     {
         _real_scheduler  = &Scheduler::get();
         auto interceptor = std::make_shared<Interceptor>(_kernels, *_real_scheduler, _scale_factor);
         Scheduler::set(std::static_pointer_cast<IScheduler>(interceptor));
     }
     _kernels.clear();
 }
void stop () override virtual
Stop measuring.
Implements Instrument.
Definition at line 96 of file SchedulerTimer.cpp.
References Scheduler::set().
 {
     // Restore real scheduler
     Scheduler::set(_real_scheduler_type);
     _real_scheduler = nullptr;
 }
The documentation for this class was generated from the following files:
tests/framework/instruments/SchedulerTimer.h
tests/framework/instruments/SchedulerTimer.cpp