Compute Library: ILutAllocator Class Reference
ILutAllocator Class Reference abstract
Basic interface to allocate LUTs'.
#include <ILutAllocator.h>
Public Member Functions
ILutAllocator ()
Default constructor.
virtual ~ILutAllocator ()=default
Default virtual destructor.
ILutAllocator (ILutAllocator &&)=default
Allow instances of this class to be move constructed.
ILutAllocator & operator= (ILutAllocator &&)=default
Allow instances of this class to be moved.
void init (size_t num_elements, DataType data_type)
Allocate an LUT of the requested number of elements and data_type.
size_t num_elements () const
Returns the total number of elements in the LUT.
DataType type () const
Returns the type of the LUT.
size_t size () const
Returns the total size in bytes of the LUT.
Detailed Description
Basic interface to allocate LUTs'.
Definition at line 35 of file ILutAllocator.h.
Constructor & Destructor Documentation
ILutAllocator() [1/2]
ILutAllocator ()
Default constructor.
Definition at line 30 of file ILutAllocator.cpp.
     : _num_elements(0), _data_type(DataType::U8)
 {
 }
References arm_compute::U8.
~ILutAllocator()
virtual ~ILutAllocator () virtual default
Default virtual destructor.
ILutAllocator() [2/2]
ILutAllocator (ILutAllocator &&) default
Allow instances of this class to be move constructed.
Member Function Documentation
init()
void init (size_t num_elements, DataType data_type)
Allocate an LUT of the requested number of elements and data_type.
Parameters
[in] num_elements Number of elements of the LUT.
[in] data_type Data type of each element.
Definition at line 35 of file ILutAllocator.cpp.
 {
     // Init internal metadata
     _num_elements = num_elements;
     _data_type    = data_type;
     // Allocate the image's memory
     allocate();
 }
References arm_compute::test::validation::data_type, and ILutAllocator::num_elements().
Referenced by CLLut::CLLut(), and Lut::Lut().
num_elements()
size_t num_elements () const
Returns the total number of elements in the LUT.
Returns
Total number of elements.
Definition at line 45 of file ILutAllocator.cpp.
 {
     return _num_elements;
 }
Referenced by ILutAllocator::init(), Lut::num_elements(), CLLut::num_elements(), and ILutAllocator::size().
operator=()
ILutAllocator& operator= (ILutAllocator &&) default
Allow instances of this class to be moved.
size()
size_t size () const
Returns the total size in bytes of the LUT.
Returns
Total size of the LUT in bytes.
Definition at line 55 of file ILutAllocator.cpp.
 {
     return data_size_from_type(_data_type) * num_elements();
 }
References arm_compute::data_size_from_type(), and ILutAllocator::num_elements().
Referenced by CLLutAllocator::map(), Lut::size_in_bytes(), and CLLut::size_in_bytes().
type()
DataType type () const
Returns the type of the LUT.
Returns
The type of the LUT.
Definition at line 50 of file ILutAllocator.cpp.
 {
     return _data_type;
 }
Referenced by Lut::index_offset(), CLLut::index_offset(), Lut::type(), and CLLut::type().
The documentation for this class was generated from the following files:
arm_compute/runtime/ILutAllocator.h
src/runtime/ILutAllocator.cpp