Compute Library: CLGEMMLowpQuantizeDownInt32ToInt16ScaleByFixedPoint Class Reference
CLGEMMLowpQuantizeDownInt32ToInt16ScaleByFixedPoint Class Reference
Basic function to execute CLGEMMLowpQuantizeDownInt32ToInt16ScaleByFixedPoint on OpenCL.
#include <CLGEMMLowpOutputStage.h>
Public Member Functions
void configure (const ICLTensor *input, const ICLTensor *bias, ICLTensor *output, int result_fixedpoint_multiplier, int result_shift, int min=0, int max=0)
Initialise the kernel's inputs, output.
Public Member Functions inherited from ICLSimpleFunction
ICLSimpleFunction ()
Default constructor.
void run () override final
Run the kernels contained in the function.
Public Member Functions inherited from IFunction
virtual ~IFunction ()=default
Destructor.
virtual void prepare ()
Prepare the function for executing.
Static Public Member Functions
static Status validate (const ITensorInfo *input, const ITensorInfo *bias, const ITensorInfo *output, int min=0, int max=0)
Static function to check if given info will lead to a valid configuration of CLGEMMLowpQuantizeDownInt32ToInt16ScaleByFixedPoint.
Detailed Description
Basic function to execute CLGEMMLowpQuantizeDownInt32ToInt16ScaleByFixedPoint on OpenCL.
CLGEMMLowpQuantizeDownInt32ToInt16ScaleByFixedPoint depends on 2 parameters:
result_fixedpoint_multiplier, result_shift
The final result is:
(FixedPointMul(input[i][k], result_fixedpoint_multiplier) >> result_shift)
where FixedPointMul(x, y) is the nearest integer to the following mathematical expression, evaluated without overflow or intermediate rounding:
(x * y) / 2^31
For more information: https://github.com/google/gemmlowp/blob/master/public/output_stages.h#L68
In case the bias tensor is provided, the final result is:
((FixedPointMul(input[i][k] + bias[k], result_fixedpoint_multiplier)) >> result_shift) + result_offset_after_shift
This function calls the following NEON kernels:
CLGEMMLowpQuantizeDownInt32ToInt16ScaleByFixedPointKernel
Note
The function accepts also 2 optional input arguments (min and max) which can be used to implement "rectified linear unit" activation functions after the result is shifted right by result_shift
Definition at line 219 of file CLGEMMLowpOutputStage.h.
Member Function Documentation
configure()
void configure (const ICLTensor * input, const ICLTensor * bias, ICLTensor * output, int result_fixedpoint_multiplier, int result_shift, int min = 0, int max = 0)
Initialise the kernel's inputs, output.
Parameters
[in] input Input tensor. Data type supported: S32
[in] bias Biases tensor. Only shared biases supported and it can be a nullptr if the biases addition is not required. Biases are 1D tensor with dimensions [OFM]. Data type supported: Same as input.
[out] output Output tensor. Data type supported: Data type supported: QSYMM16
[in] result_fixedpoint_multiplier Fixed point value to be multiplied to each element of the input matrix when once the result_offset has been add
[in] result_shift Number of bits to shift right the result after the fixed point multiplication
[in] min (Optional) Min value used to saturate down the output result before converting back to QSYMM16. Defaults to 0.
[in] max (Optional) Max value used to saturate up the output result before converting back to QSYMM16. Along with min, this value can be used to implement "rectified linear unit" activation functions. Defaults to 0.
Definition at line 77 of file CLGEMMLowpOutputStage.cpp.
 {
     auto k = arm_compute::support::cpp14::make_unique<CLGEMMLowpQuantizeDownInt32ToInt16ScaleByFixedPointKernel>();
     k->configure(input, bias, output, result_fixedpoint_multiplier, result_shift, min, max);
     _kernel = std::move(k);
 }
References arm_compute::test::validation::bias.
Referenced by CLLSTMLayerQuantized::configure().
validate()
Status validate (const ITensorInfo * input, const ITensorInfo * bias, const ITensorInfo * output, int min = 0, int max = 0) static
Static function to check if given info will lead to a valid configuration of CLGEMMLowpQuantizeDownInt32ToInt16ScaleByFixedPoint.
Parameters
[in] input Input tensor info. It is the output of CLGEMMLowpMatrixMultiplyCore function. Data type supported: S32
[in] bias Biases tensor info. Only shared biases supported and it can be a nullptr if the addition of biases is not required. Biases are 1D tensor with dimensions [OFM]. Data type supported: Same as input.
[in] output Output tensor info. Data type supported: Data type supported: QSYMM16
[in] min (Optional) Min value used to saturate down the output result before converting back to QSYMM16. Defaults to 0.
[in] max (Optional) Max value used to saturate up the output result before converting back to QSYMM16, Along with min, this value can be used to implement "rectified linear unit" activation functions. Defaults to 0.
Returns
a status
Definition at line 86 of file CLGEMMLowpOutputStage.cpp.
 {
     return CLGEMMLowpQuantizeDownInt32ToInt16ScaleByFixedPointKernel::validate(input, bias, output, min, max);
 }
References arm_compute::test::validation::bias, and CLGEMMLowpQuantizeDownInt32ToInt16ScaleByFixedPointKernel::validate().
Referenced by CLLSTMLayerQuantized::validate().
The documentation for this class was generated from the following files:
arm_compute/runtime/CL/functions/CLGEMMLowpOutputStage.h
src/runtime/CL/functions/CLGEMMLowpOutputStage.cpp