Compute Library: Tensor< T > Class Template Reference
Tensor< T > Class Template Reference
#include <Tensor.h>
Public Member Functions
Tensor ()
Tensor (TensorShape shape, DataType dt, int fixed_point_position, T *ptr)
Tensor (TensorShape shape, DataType dt, int fixed_point_position, const T *ptr)
Tensor (const Tensor &tensor)=delete
Tensor & operator= (const Tensor &)=delete
Tensor (Tensor &&)=default
Tensor & operator= (Tensor &&)=default
~Tensor ()=default
T & operator[] (size_t offset)
const T & operator[] (size_t offset) const
int num_elements () const
TensorShape shape () const
DataType data_type () const
int fixed_point_position () const
const T * data () const
T * data ()
const T * data_const ()
Detailed Description
template<typename T>
class arm_compute::test::validation::Tensor< T >
Definition at line 37 of file Tensor.h.
Constructor & Destructor Documentation
Tensor () inline
Definition at line 40 of file Tensor.h.
References arm_compute::UNKNOWN.
Referenced by Tensor< T >::Tensor().
         : _shape(), _dt(DataType::UNKNOWN), _fixed_point_position(0), _ptr(nullptr), _ptr_const(nullptr) {};
Tensor (TensorShape shape, DataType dt, int fixed_point_position, T * ptr) inline
Definition at line 43 of file Tensor.h.
         : _shape(shape), _dt(dt), _fixed_point_position(fixed_point_position), _ptr(ptr), _ptr_const(nullptr) {};
Tensor (TensorShape shape, DataType dt, int fixed_point_position, const T * ptr) inline
Definition at line 46 of file Tensor.h.
References Tensor< T >::operator=(), Tensor< T >::Tensor(), and Tensor< T >::~Tensor().
         : _shape(shape), _dt(dt), _fixed_point_position(fixed_point_position), _ptr(nullptr), _ptr_const(ptr) {};
Tensor (const Tensor< T > & tensor) delete
Tensor (Tensor< T > &&) default
~Tensor () default
Referenced by Tensor< T >::Tensor().
Member Function Documentation
const T* data () const inline
Definition at line 86 of file Tensor.h.
Referenced by arm_compute::test::validation::tensor_operations::convolution_layer(), and arm_compute::test::validation::tensor_operations::fully_connected_layer().
     {
         return (_ptr != nullptr) ? _ptr : _ptr_const;
     }
T* data () inline
Definition at line 90 of file Tensor.h.
     {
         return _ptr;
     }
const T* data_const () inline
Definition at line 95 of file Tensor.h.
     {
         return _ptr_const;
     }
DataType data_type () const inline
Definition at line 76 of file Tensor.h.
Referenced by arm_compute::test::validation::tensor_operations::fixed_point_pixel_wise_multiplication().
     {
         return _dt;
     }
int fixed_point_position () const inline
Definition at line 81 of file Tensor.h.
Referenced by arm_compute::test::validation::tensor_operations::activation_layer(), arm_compute::test::validation::tensor_operations::convolution_layer(), arm_compute::test::validation::tensor_operations::fixed_point_operation(), arm_compute::test::validation::tensor_operations::fixed_point_pixel_wise_multiplication(), arm_compute::test::validation::tensor_operations::fully_connected_layer(), arm_compute::test::validation::tensor_operations::gemm(), arm_compute::test::validation::tensor_operations::normalization_layer(), and arm_compute::test::validation::tensor_operations::softmax_layer().
     {
         return _fixed_point_position;
     }
int num_elements () const inline
Definition at line 66 of file Tensor.h.
References accumulate(), Dimensions< T >::cbegin(), and Dimensions< T >::cend().
Referenced by arm_compute::test::validation::tensor_operations::absolute_difference(), arm_compute::test::validation::tensor_operations::accumulate(), arm_compute::test::validation::tensor_operations::accumulate_squared(), arm_compute::test::validation::tensor_operations::accumulate_weighted(), arm_compute::test::validation::tensor_operations::activation_layer(), arm_compute::test::validation::tensor_operations::arithmetic_addition(), arm_compute::test::validation::tensor_operations::arithmetic_subtraction(), arm_compute::test::validation::tensor_operations::bitwise_and(), arm_compute::test::validation::tensor_operations::bitwise_not(), arm_compute::test::validation::tensor_operations::bitwise_or(), arm_compute::test::validation::tensor_operations::bitwise_xor(), arm_compute::test::validation::tensor_operations::box3x3(), arm_compute::test::validation::tensor_operations::fixed_point_operation(), arm_compute::test::validation::tensor_operations::fixed_point_pixel_wise_multiplication(), arm_compute::test::validation::tensor_operations::normalization_layer(), arm_compute::test::validation::tensor_operations::pixel_wise_multiplication(), arm_compute::test::validation::tensor_operations::print(), and arm_compute::test::validation::tensor_operations::threshold().
     {
         return std::accumulate(_shape.cbegin(), _shape.cend(), 1, std::multiplies<int>());
     }
Tensor& operator= (const Tensor< T > &) delete
Referenced by Tensor< T >::Tensor().
Tensor& operator= (Tensor< T > &&) default
T& operator[] (size_t offset) inline
Definition at line 56 of file Tensor.h.
References offset().
     {
         return _ptr[offset];
     }
const T& operator[] (size_t offset) const inline
Definition at line 61 of file Tensor.h.
References offset().
     {
         return _ptr_const[offset];
     }
TensorShape shape () const inline
Definition at line 71 of file Tensor.h.
Referenced by arm_compute::test::validation::tensor_operations::batch_normalization_layer(), arm_compute::test::validation::tensor_operations::box3x3(), arm_compute::test::validation::tensor_operations::convolution_layer(), arm_compute::test::validation::tensor_operations::fully_connected_layer(), arm_compute::test::validation::tensor_operations::gemm(), arm_compute::test::validation::tensor_operations::integral_image(), arm_compute::test::validation::tensor_operations::normalization_layer(), arm_compute::test::validation::tensor_operations::pooling_layer(), and arm_compute::test::validation::tensor_operations::softmax_layer().
     {
         return _shape;
     }
The documentation for this class was generated from the following file:
tests/validation/Tensor.h