Compute Library: Reference Class Reference
Reference Class Reference
Interface for reference implementations.
#include <Reference.h>
Static Public Member Functions
static RawTensor compute_reference_integral_image (const TensorShape &shape)
Compute reference integral image.
static RawTensor compute_reference_absolute_difference (const TensorShape &shape, DataType dt_in0, DataType dt_in1, DataType dt_out)
Compute reference absolute difference.
static RawTensor compute_reference_accumulate (const TensorShape &shape)
Compute reference accumulate.
static RawTensor compute_reference_accumulate_squared (const TensorShape &shape, uint32_t shift)
Compute reference accumulate.
static RawTensor compute_reference_accumulate_weighted (const TensorShape &shape, float alpha)
Compute reference accumulate.
static RawTensor compute_reference_arithmetic_addition (const TensorShape &shape, DataType dt_in0, DataType dt_in1, DataType dt_out, ConvertPolicy convert_policy)
Compute reference arithmetic addition.
static RawTensor compute_reference_arithmetic_subtraction (const TensorShape &shape, DataType dt_in0, DataType dt_in1, DataType dt_out, ConvertPolicy convert_policy)
Compute reference arithmetic subtraction.
static RawTensor compute_reference_bitwise_and (const TensorShape &shape)
Compute reference bitwise and.
static RawTensor compute_reference_bitwise_or (const TensorShape &shape)
Compute reference bitwise or.
static RawTensor compute_reference_bitwise_xor (const TensorShape &shape)
Compute reference bitwise xor.
static RawTensor compute_reference_bitwise_not (const TensorShape &shape)
Compute reference bitwise not.
static RawTensor compute_reference_box3x3 (const TensorShape &shape)
Compute reference 3-by-3 box filter.
static RawTensor compute_reference_depth_convert (const TensorShape &shape, DataType dt_in, DataType dt_out, ConvertPolicy policy, uint32_t shift, uint32_t fixed_point_position)
Compute reference depth convert.
static RawTensor compute_reference_gemm (const TensorShape &src_shape1, const TensorShape &src_shape2, const TensorShape &src_shape3, const TensorShape &dst_shape, float alpha, float beta, DataType dt, int fixed_point_position=0)
Compute matrix multiply function.
static RawTensor compute_reference_pixel_wise_multiplication (const TensorShape &shape, DataType dt_in0, DataType dt_in1, DataType dt_out, float scale, ConvertPolicy convert_policy, RoundingPolicy rounding_policy)
Compute reference pixel-wise multiplication.
static RawTensor compute_reference_fixed_point_pixel_wise_multiplication (const TensorShape &shape, DataType dt_in0, DataType dt_in1, DataType dt_out, float scale, int fixed_point_position, ConvertPolicy convert_policy, RoundingPolicy rounding_policy)
Compute reference pixel-wise multiplication.
static RawTensor compute_reference_threshold (const TensorShape &shape, uint8_t threshold, uint8_t false_value, uint8_t true_value, ThresholdType type, uint8_t upper)
Compute reference threshold.
static RawTensor compute_reference_activation_layer (const TensorShape &shape, DataType dt, ActivationLayerInfo act_info, int fixed_point_position=0)
Compute reference activation layer.
static RawTensor compute_reference_batch_normalization_layer (const TensorShape &shape0, const TensorShape &shape1, DataType dt, float epsilon, int fixed_point_position=0)
Compute reference batch normalization layer.
static RawTensor compute_reference_convolution_layer (const TensorShape &input_shape, const TensorShape &weights_shape, const TensorShape &bias_shape, const TensorShape &output_shape, DataType dt, const PadStrideInfo &conv_info, int fixed_point_position)
Compute reference pixel-wise multiplication.
static RawTensor compute_reference_fully_connected_layer (const TensorShape &input_shape, const TensorShape &weights_shape, const TensorShape &bias_shape, const TensorShape &output_shape, DataType dt, bool transpose_weights, int fixed_point_position)
Compute reference for fully connected layer function.
static RawTensor compute_reference_normalization_layer (const TensorShape &shape, DataType dt, NormalizationLayerInfo norm_info, int fixed_point_position=0)
Compute reference normalization layer.
static RawTensor compute_reference_pooling_layer (const TensorShape &shape_in, const TensorShape &shape_out, DataType dt, PoolingLayerInfo pool_info, int fixed_point_position=0)
Compute reference pooling layer.
static RawTensor compute_reference_softmax_layer (const TensorShape &shape, DataType dt, int fixed_point_position=0)
Compute reference softmax layer.
static RawTensor compute_reference_fixed_point_operation (const TensorShape &shape, DataType dt_in, DataType dt_out, FixedPointOp op, int fixed_point_position)
Compute reference fixed point operation.
Detailed Description
Interface for reference implementations.
Definition at line 37 of file Reference.h.
Member Function Documentation
RawTensor compute_reference_absolute_difference (const TensorShape & shape, DataType dt_in0, DataType dt_in1, DataType dt_out) static
Compute reference absolute difference.
Parameters
[in] shape Shape of the input and output tensors.
[in] dt_in0 Data type of first input tensor.
[in] dt_in1 Data type of second input tensor.
[in] dt_out Data type of the output tensor.
Returns
Computed raw tensor.
Definition at line 56 of file Reference.cpp.
References arm_compute::test::validation::tensor_operations::absolute_difference(), and arm_compute::test::library.
 {
     // Create reference
     RawTensor ref_src1 = library->get(shape, dt_in0);
     RawTensor ref_src2 = library->get(shape, dt_in1);
     RawTensor ref_dst  = library->get(shape, dt_out);
     // Fill reference
     library->fill_tensor_uniform(ref_src1, 0);
     library->fill_tensor_uniform(ref_src2, 1);
     // Compute reference
     ReferenceCPP::absolute_difference(ref_src1, ref_src2, ref_dst);
     return ref_dst;
 }
RawTensor compute_reference_accumulate (const TensorShape & shape) static
Compute reference accumulate.
Parameters
[in] shape Shape of the input and output tensors.
Returns
Computed raw tensor.
Definition at line 73 of file Reference.cpp.
References accumulate(), arm_compute::test::library, arm_compute::S16, and arm_compute::U8.
 {
     // Create reference
     RawTensor ref_src = library->get(shape, DataType::U8);
     RawTensor ref_dst = library->get(shape, DataType::S16);
     // Fill reference
     library->fill_tensor_uniform(ref_src, 0);
     library->fill_tensor_uniform(ref_dst, 1);
     // Compute reference
     ReferenceCPP::accumulate(ref_src, ref_dst);
     return ref_dst;
 }
RawTensor compute_reference_accumulate_squared (const TensorShape & shape, uint32_t shift) static
Compute reference accumulate.
Parameters
[in] shape Shape of the input and output tensors.
[in] shift A uint32_t value within the range of [0, 15]
Returns
Computed raw tensor.
Definition at line 89 of file Reference.cpp.
References accumulate_squared(), arm_compute::test::library, arm_compute::test::fixed_point_arithmetic::detail::max(), arm_compute::S16, and arm_compute::U8.
 {
     // Create reference
     RawTensor ref_src = library->get(shape, DataType::U8);
     RawTensor ref_dst = library->get(shape, DataType::S16);
     // Fill reference
     // ref_dst tensor filled with non-negative values
     library->fill_tensor_uniform(ref_src, 0);
     library->fill_tensor_uniform(ref_dst, 1, static_cast<int16_t>(0), std::numeric_limits<int16_t>::max());
     // Compute reference
     ReferenceCPP::accumulate_squared(ref_src, ref_dst, shift);
     return ref_dst;
 }
RawTensor compute_reference_accumulate_weighted (const TensorShape & shape, float alpha) static
Compute reference accumulate.
Parameters
[in] shape Shape of the input and output tensors.
[in] alpha A float value within the range of [0, 1]
Returns
Computed raw tensor.
Definition at line 106 of file Reference.cpp.
References accumulate_weighted(), arm_compute::test::library, and arm_compute::U8.
 {
     // Create reference
     RawTensor ref_src = library->get(shape, DataType::U8);
     RawTensor ref_dst = library->get(shape, DataType::U8);
     // Fill reference
     library->fill_tensor_uniform(ref_src, 0);
     library->fill_tensor_uniform(ref_dst, 1);
     // Compute reference
     ReferenceCPP::accumulate_weighted(ref_src, ref_dst, alpha);
     return ref_dst;
 }
RawTensor compute_reference_activation_layer (const TensorShape & shape, DataType dt, ActivationLayerInfo act_info, int fixed_point_position = 0) static
Compute reference activation layer.
Parameters
[in] shape Shape of the input and output tensors.
[in] dt Data type of the tensors.
[in] act_info Activation layer information.
[in] fixed_point_position (Optional)Number of bits for the fractional part of fixed point numbers.
Returns
Computed raw tensor.
Definition at line 331 of file Reference.cpp.
References ActivationLayerInfo::activation(), activation_layer(), arm_compute::F32, and arm_compute::test::library.
 {
     // Create reference
     RawTensor ref_src = library->get(shape, dt, 1, fixed_point_position);
     RawTensor ref_dst = library->get(shape, dt, 1, fixed_point_position);
     // Fill reference
     if(dt == DataType::F32)
     {
         float min_bound = 0;
         float max_bound = 0;
         std::tie(min_bound, max_bound) = get_activation_layer_test_bounds<float>(act_info.activation());
         std::uniform_real_distribution<> distribution(min_bound, max_bound);
         library->fill(ref_src, distribution, 0);
     }
     else
     {
         int min_bound = 0;
         int max_bound = 0;
         std::tie(min_bound, max_bound) = get_activation_layer_test_bounds<int8_t>(act_info.activation(), fixed_point_position);
         std::uniform_int_distribution<> distribution(min_bound, max_bound);
         library->fill(ref_src, distribution, 0);
     }
     // Compute reference
     ReferenceCPP::activation_layer(ref_src, ref_dst, act_info);
     return ref_dst;
 }
RawTensor compute_reference_arithmetic_addition (const TensorShape & shape, DataType dt_in0, DataType dt_in1, DataType dt_out, ConvertPolicy convert_policy) static
Compute reference arithmetic addition.
Parameters
[in] shape Shape of the input and output tensors.
[in] dt_in0 Data type of first input tensor.
[in] dt_in1 Data type of second input tensor.
[in] dt_out Data type of the output tensor.
[in] convert_policy Overflow policy of the operation.
Returns
Computed raw tensor.
Definition at line 122 of file Reference.cpp.
References arm_compute::test::validation::tensor_operations::arithmetic_addition(), and arm_compute::test::library.
 {
     // Create reference
     RawTensor ref_src1 = library->get(shape, dt_in0);
     RawTensor ref_src2 = library->get(shape, dt_in1);
     RawTensor ref_dst  = library->get(shape, dt_out);
     // Fill reference
     library->fill_tensor_uniform(ref_src1, 0);
     library->fill_tensor_uniform(ref_src2, 1);
     // Compute reference
     ReferenceCPP::arithmetic_addition(ref_src1, ref_src2, ref_dst, convert_policy);
     return ref_dst;
 }
RawTensor compute_reference_arithmetic_subtraction (const TensorShape & shape, DataType dt_in0, DataType dt_in1, DataType dt_out, ConvertPolicy convert_policy) static
Compute reference arithmetic subtraction.
Parameters
[in] shape Shape of the input and output tensors.
[in] dt_in0 Data type of first input tensor.
[in] dt_in1 Data type of second input tensor.
[in] dt_out Data type of the output tensor.
[in] convert_policy Overflow policy of the operation.
Returns
Computed raw tensor.
Definition at line 139 of file Reference.cpp.
References arm_compute::test::validation::tensor_operations::arithmetic_subtraction(), and arm_compute::test::library.
 {
     // Create reference
     RawTensor ref_src1 = library->get(shape, dt_in0);
     RawTensor ref_src2 = library->get(shape, dt_in1);
     RawTensor ref_dst  = library->get(shape, dt_out);
     // Fill reference
     library->fill_tensor_uniform(ref_src1, 0);
     library->fill_tensor_uniform(ref_src2, 1);
     // Compute reference
     ReferenceCPP::arithmetic_subtraction(ref_src1, ref_src2, ref_dst, convert_policy);
     return ref_dst;
 }
RawTensor compute_reference_batch_normalization_layer (const TensorShape & shape0, const TensorShape & shape1, DataType dt, float epsilon, int fixed_point_position = 0) static
Compute reference batch normalization layer.
Parameters
[in] shape0 Shape of the input and output tensors.
[in] shape1 Shape of the vector tensors.
[in] dt Data type of all input and output tensors.
[in] epsilon Small value to avoid division with zero.
[in] fixed_point_position Fixed point position.
Returns
Computed raw tensor.
Definition at line 361 of file Reference.cpp.
References arm_compute::test::validation::tensor_operations::batch_normalization_layer(), arm_compute::F32, and arm_compute::test::library.
 {
     // Create reference
     RawTensor ref_src   = library->get(shape0, dt, 1, fixed_point_position);
     RawTensor ref_dst   = library->get(shape0, dt, 1, fixed_point_position);
     RawTensor ref_mean  = library->get(shape1, dt, 1, fixed_point_position);
     RawTensor ref_var   = library->get(shape1, dt, 1, fixed_point_position);
     RawTensor ref_beta  = library->get(shape1, dt, 1, fixed_point_position);
     RawTensor ref_gamma = library->get(shape1, dt, 1, fixed_point_position);
     // Fill tensors with values from -1 to 1.
     if(dt == DataType::F32)
     {
         float min_bound = 0.f;
         float max_bound = 0.f;
         std::tie(min_bound, max_bound) = get_batchnormalization_layer_test_bounds<float>();
         std::uniform_real_distribution<> distribution(min_bound, max_bound);
         std::uniform_real_distribution<> distribution_var(0, max_bound);
         library->fill(ref_src, distribution, 0);
         library->fill(ref_mean, distribution, 1);
         library->fill(ref_var, distribution_var, 0);
         library->fill(ref_beta, distribution, 3);
         library->fill(ref_gamma, distribution, 4);
     }
     else
     {
         int min_bound = 0;
         int max_bound = 0;
         std::tie(min_bound, max_bound) = get_batchnormalization_layer_test_bounds<int8_t>(fixed_point_position);
         std::uniform_int_distribution<> distribution(min_bound, max_bound);
         std::uniform_int_distribution<> distribution_var(0, max_bound);
         library->fill(ref_src, distribution, 0);
         library->fill(ref_mean, distribution, 1);
         library->fill(ref_var, distribution_var, 0);
         library->fill(ref_beta, distribution, 3);
         library->fill(ref_gamma, distribution, 4);
     }
     // Compute reference
     ReferenceCPP::batch_normalization_layer(ref_src, ref_dst, ref_mean, ref_var, ref_beta, ref_gamma, epsilon, fixed_point_position);
     return ref_dst;
 }
RawTensor compute_reference_bitwise_and (const TensorShape & shape) static
Compute reference bitwise and.
Parameters
[in] shape Shape of the input and output tensors.
Returns
Computed raw tensor.
Definition at line 156 of file Reference.cpp.
References bitwise_and(), arm_compute::test::library, and arm_compute::U8.
 {
     // Create reference
     RawTensor ref_src1 = library->get(shape, DataType::U8);
     RawTensor ref_src2 = library->get(shape, DataType::U8);
     RawTensor ref_dst  = library->get(shape, DataType::U8);
     // Fill reference
     library->fill_tensor_uniform(ref_src1, 0);
     library->fill_tensor_uniform(ref_src2, 1);
     // Compute reference
     ReferenceCPP::bitwise_and(ref_src1, ref_src2, ref_dst);
     return ref_dst;
 }
RawTensor compute_reference_bitwise_not (const TensorShape & shape) static
Compute reference bitwise not.
Parameters
[in] shape Shape of the input and output tensors.
Returns
Computed raw tensor.
Definition at line 207 of file Reference.cpp.
References bitwise_not(), arm_compute::test::library, and arm_compute::U8.
 {
     // Create reference
     RawTensor ref_src = library->get(shape, DataType::U8);
     RawTensor ref_dst = library->get(shape, DataType::U8);
     // Fill reference
     library->fill_tensor_uniform(ref_src, 0);
     // Compute reference
     ReferenceCPP::bitwise_not(ref_src, ref_dst);
     return ref_dst;
 }
RawTensor compute_reference_bitwise_or (const TensorShape & shape) static
Compute reference bitwise or.
Parameters
[in] shape Shape of the input and output tensors.
Returns
Computed raw tensor.
Definition at line 173 of file Reference.cpp.
References bitwise_or(), arm_compute::test::library, and arm_compute::U8.
 {
     // Create reference
     RawTensor ref_src1 = library->get(shape, DataType::U8);
     RawTensor ref_src2 = library->get(shape, DataType::U8);
     RawTensor ref_dst  = library->get(shape, DataType::U8);
     // Fill reference
     library->fill_tensor_uniform(ref_src1, 0);
     library->fill_tensor_uniform(ref_src2, 1);
     // Compute reference
     ReferenceCPP::bitwise_or(ref_src1, ref_src2, ref_dst);
     return ref_dst;
 }
RawTensor compute_reference_bitwise_xor (const TensorShape & shape) static
Compute reference bitwise xor.
Parameters
[in] shape Shape of the input and output tensors.
Returns
Computed raw tensor.
Definition at line 190 of file Reference.cpp.
References bitwise_xor(), arm_compute::test::library, and arm_compute::U8.
 {
     // Create reference
     RawTensor ref_src1 = library->get(shape, DataType::U8);
     RawTensor ref_src2 = library->get(shape, DataType::U8);
     RawTensor ref_dst  = library->get(shape, DataType::U8);
     // Fill reference
     library->fill_tensor_uniform(ref_src1, 0);
     library->fill_tensor_uniform(ref_src2, 1);
     // Compute reference
     ReferenceCPP::bitwise_xor(ref_src1, ref_src2, ref_dst);
     return ref_dst;
 }
RawTensor compute_reference_box3x3 (const TensorShape & shape) static
Compute reference 3-by-3 box filter.
Parameters
[in] shape Shape of the input and output tensors.
Returns
Computed raw tensor.
Definition at line 222 of file Reference.cpp.
References arm_compute::test::validation::tensor_operations::box3x3(), arm_compute::test::library, and arm_compute::U8.
 {
     // Create reference
     RawTensor ref_src = library->get(shape, DataType::U8);
     RawTensor ref_dst = library->get(shape, DataType::U8);
     // Fill reference
     library->fill_tensor_uniform(ref_src, 0);
     // Compute reference
     ReferenceCPP::box3x3(ref_src, ref_dst);
     return ref_dst;
 }
RawTensor compute_reference_convolution_layer (const TensorShape & input_shape, const TensorShape & weights_shape, const TensorShape & bias_shape, const TensorShape & output_shape, DataType dt, const PadStrideInfo & conv_info, int fixed_point_position) static
Compute reference pixel-wise multiplication.
Parameters
[in] input_shape Shape for the input tensor
[in] weights_shape Shape for the weights tensor
[in] bias_shape Shape for the bias tensor
[in] output_shape Shape for the output tensor
[in] dt Data type to use
[in] conv_info Pads and strides information for the convolution layer
[in] fixed_point_position Number of bits for the fractional part of the fixed point numbers
Returns
Computed raw tensor.
Definition at line 405 of file Reference.cpp.
References arm_compute::test::validation::tensor_operations::convolution_layer(), arm_compute::F32, and arm_compute::test::library.
 {
     // Create reference
     RawTensor ref_src     = library->get(input_shape, dt, 1, fixed_point_position);
     RawTensor ref_weights = library->get(weights_shape, dt, 1, fixed_point_position);
     RawTensor ref_bias    = library->get(bias_shape, dt, 1, fixed_point_position);
     RawTensor ref_dst     = library->get(output_shape, dt, 1, fixed_point_position);
     // Fill reference
     if(dt == DataType::F32)
     {
         std::uniform_real_distribution<> distribution(-1.0f, 1.0f);
         library->fill(ref_src, distribution, 0);
         library->fill(ref_weights, distribution, 1);
         library->fill(ref_bias, distribution, 2);
     }
     else
     {
         library->fill_tensor_uniform(ref_src, 0);
         library->fill_tensor_uniform(ref_weights, 1);
         library->fill_tensor_uniform(ref_bias, 2);
     }
     // Compute reference
     ReferenceCPP::convolution_layer(ref_src, ref_weights, ref_bias, ref_dst, conv_info);
     return ref_dst;
 }
RawTensor compute_reference_depth_convert (const TensorShape & shape, DataType dt_in, DataType dt_out, ConvertPolicy policy, uint32_t shift, uint32_t fixed_point_position) static
Compute reference depth convert.
Parameters
[in] shape Shape of the input and output tensors.
[in] dt_in Data type of input tensor.
[in] dt_out Data type of the output tensor.
[in] policy Overflow policy of the operation.
[in] shift Value for down/up conversions. Must be 0 <= shift < 8.
[in] fixed_point_position Fixed point position.
Returns
Computed raw tensor.
Definition at line 237 of file Reference.cpp.
References arm_compute::test::validation::tensor_operations::depth_convert(), and arm_compute::test::library.
 {
     RawTensor ref_src = library->get(shape, dt_in, 1, fixed_point_position);
     RawTensor ref_dst = library->get(shape, dt_out, 1, fixed_point_position);
     // Fill reference
     library->fill_tensor_uniform(ref_src, 0);
     // Compute reference
     ReferenceCPP::depth_convert(ref_src, ref_dst, policy, shift);
     return ref_dst;
 }
RawTensor compute_reference_fixed_point_operation (const TensorShape & shape, DataType dt_in, DataType dt_out, FixedPointOp op, int fixed_point_position) static
Compute reference fixed point operation.
Parameters
[in] shape Shape of the input and output tensors.
[in] dt_in Data type of the input tensor.
[in] dt_out Data type of the output tensor.
[in] op Fixed point operation to perform.
[in] fixed_point_position Number of bits for the fractional part of the fixed point numbers
Returns
Computed raw tensor.
Definition at line 555 of file Reference.cpp.
References ARM_COMPUTE_ERROR, arm_compute::EXP, arm_compute::test::validation::tensor_operations::fixed_point_operation(), arm_compute::INV_SQRT, arm_compute::test::library, arm_compute::LOG, arm_compute::test::fixed_point_arithmetic::detail::max(), arm_compute::test::fixed_point_arithmetic::detail::min(), and arm_compute::RECIPROCAL.
 {
     // Create reference
     RawTensor ref_src = library->get(shape, dt_in, 1, fixed_point_position);
     RawTensor ref_dst = library->get(shape, dt_out, 1, fixed_point_position);
     // Fill reference
     int min = 0;
     int max = 0;
     switch(op)
     {
         case(FixedPointOp::INV_SQRT):
             min = 32;
             max = 127;
             break;
         case(FixedPointOp::LOG):
             min = (1 << (fixed_point_position - 1));
             max = 63;
             break;
         case(FixedPointOp::EXP):
             min = 1;
             max = (1 << (fixed_point_position - 1));
             break;
         case(FixedPointOp::RECIPROCAL):
             min = 15;
             max = 100;
             break;
         default:
             ARM_COMPUTE_ERROR("Fixed point operation not supported");
     }
     std::uniform_int_distribution<> distribution(min, max);
     library->fill(ref_src, distribution, 0);
     // Compute reference
     ReferenceCPP::fixed_point_operation(ref_src, ref_dst, op);
     return ref_dst;
 }
RawTensor compute_reference_fixed_point_pixel_wise_multiplication (const TensorShape & shape, DataType dt_in0, DataType dt_in1, DataType dt_out, float scale, int fixed_point_position, ConvertPolicy convert_policy, RoundingPolicy rounding_policy) static
Compute reference pixel-wise multiplication.
Parameters
[in] shape Shape of the input and output tensors.
[in] dt_in0 Data type of first input tensor.
[in] dt_in1 Data type of second input tensor.
[in] dt_out Data type of the output tensor.
[in] scale Scale to apply after multiplication. Must be positive.
[in] fixed_point_position Fixed point position that expresses the number of bits for the fractional part of the number.
[in] convert_policy Overflow policy of the operation.
[in] rounding_policy Rounding policy of the operation.
Returns
Computed raw tensor.
Definition at line 298 of file Reference.cpp.
References arm_compute::test::validation::tensor_operations::fixed_point_pixel_wise_multiplication(), and arm_compute::test::library.
 {
     // Create reference
     RawTensor ref_src1 = library->get(shape, dt_in0, 1, fixed_point_position);
     RawTensor ref_src2 = library->get(shape, dt_in1, 1, fixed_point_position);
     RawTensor ref_dst  = library->get(shape, dt_out, 1, fixed_point_position);
     // Fill reference
     library->fill_tensor_uniform(ref_src1, 0);
     library->fill_tensor_uniform(ref_src2, 1);
     // Compute reference
     ReferenceCPP::fixed_point_pixel_wise_multiplication(ref_src1, ref_src2, ref_dst, scale, convert_policy, rounding_policy);
     return ref_dst;
 }
RawTensor compute_reference_fully_connected_layer (const TensorShape & input_shape, const TensorShape & weights_shape, const TensorShape & bias_shape, const TensorShape & output_shape, DataType dt, bool transpose_weights, int fixed_point_position) static
Compute reference for fully connected layer function.
Parameters
[in] input_shape Shape for the input tensor
[in] weights_shape Shape for the weights tensor
[in] bias_shape Shape for the bias tensor
[in] output_shape Shape for the output tensor
[in] dt Data type to use
[in] transpose_weights Transpose the weights if true
[in] fixed_point_position Number of bits for the fractional part of the fixed point numbers
Returns
Computed raw tensor.
Definition at line 435 of file Reference.cpp.
References arm_compute::F32, arm_compute::test::validation::tensor_operations::fully_connected_layer(), arm_compute::test::library, TensorShape::set(), Dimensions< T >::x(), and Dimensions< T >::y().
 {
     // Create reference
     RawTensor ref_src  = library->get(input_shape, dt, 1, fixed_point_position);
     RawTensor ref_bias = library->get(bias_shape, dt, 1, fixed_point_position);
     RawTensor ref_dst  = library->get(output_shape, dt, 1, fixed_point_position);
     // Swap the first and second dimension of weights' shape if transpose_weights is true
     TensorShape ws = weights_shape;
     if(transpose_weights)
     {
         const size_t dimx = ws.x();
         ws.set(0, ws.y());
         ws.set(1, dimx);
     }
     RawTensor ref_weights = library->get(ws, dt, 1, fixed_point_position);
     // Fill reference
     if(dt == DataType::F32)
     {
         std::uniform_real_distribution<> distribution(-1.0f, 1.0f);
         library->fill(ref_src, distribution, 0);
         library->fill(ref_weights, distribution, 1);
         library->fill(ref_bias, distribution, 2);
     }
     else
     {
         library->fill_tensor_uniform(ref_src, 0);
         library->fill_tensor_uniform(ref_weights, 1);
         library->fill_tensor_uniform(ref_bias, 2);
     }
     // Compute reference
     ReferenceCPP::fully_connected_layer(ref_src, ref_weights, ref_bias, ref_dst);
     return ref_dst;
 }
RawTensor compute_reference_gemm (const TensorShape & src_shape1, const TensorShape & src_shape2, const TensorShape & src_shape3, const TensorShape & dst_shape, float alpha, float beta, DataType dt, int fixed_point_position = 0) static
Compute matrix multiply function.
Parameters
[in] src_shape1 First input tensor shape
[in] src_shape2 Second input tensor shape
[in] src_shape3 Third input tensor shape
[out] dst_shape Output tensor.
[in] alpha Weight of the matrix product
[in] beta Weight of the third matrix
[in] dt Tensor's data type
[in] fixed_point_position (Optional) Number of bits for the fractional part of the fixed point numbers
Returns
Computed output tensor.
Definition at line 251 of file Reference.cpp.
References arm_compute::F32, arm_compute::test::validation::tensor_operations::gemm(), and arm_compute::test::library.
 {
     RawTensor src1 = library->get(src_shape1, dt, 1, fixed_point_position);
     RawTensor src2 = library->get(src_shape2, dt, 1, fixed_point_position);
     RawTensor src3 = library->get(src_shape3, dt, 1, fixed_point_position);
     RawTensor dst  = library->get(dst_shape, dt, 1, fixed_point_position);
     // Fill reference
     if(dt == DataType::F32)
     {
         std::uniform_real_distribution<> distribution(-1.0f, 1.0f);
         library->fill(src1, distribution, 0);
         library->fill(src2, distribution, 1);
         library->fill(src3, distribution, 2);
     }
     else
     {
         library->fill_tensor_uniform(src1, 0);
         library->fill_tensor_uniform(src2, 1);
         library->fill_tensor_uniform(src3, 2);
     }
     // Compute reference
     ReferenceCPP::gemm(src1, src2, src3, dst, alpha, beta);
     return dst;
 }
RawTensor compute_reference_integral_image (const TensorShape & shape) static
Compute reference integral image.
Parameters
[in] shape Shape of the input and output tensors.
Returns
Computed raw tensor.
Definition at line 42 of file Reference.cpp.
References arm_compute::test::validation::tensor_operations::integral_image(), arm_compute::test::library, arm_compute::U32, and arm_compute::U8.
 {
     // Create reference
     RawTensor ref_src = library->get(shape, DataType::U8);
     RawTensor ref_dst = library->get(shape, DataType::U32);
     // Fill reference
     library->fill_tensor_uniform(ref_src, 0);
     // Compute reference
     ReferenceCPP::integral_image(ref_src, ref_dst);
     return ref_dst;
 }
RawTensor compute_reference_normalization_layer (const TensorShape & shape, DataType dt, NormalizationLayerInfo norm_info, int fixed_point_position = 0) static
Compute reference normalization layer.
Parameters
[in] shape Shape of the input and output tensors.
[in] dt Data type of input and output tensors.
[in] norm_info Normalization Layer information.
[in] fixed_point_position (Optional) Fixed point position that expresses the number of bits for the fractional part of the number when the tensor's data type is QS8 or QS16 (default = 0).
Returns
Computed raw tensor.
Definition at line 475 of file Reference.cpp.
References arm_compute::test::library, arm_compute::test::validation::tensor_operations::normalization_layer(), and arm_compute::QS8.
 {
     // Create reference
     RawTensor ref_src = library->get(shape, dt, 1, fixed_point_position);
     RawTensor ref_dst = library->get(shape, dt, 1, fixed_point_position);
     // Fill reference
     if(dt == DataType::QS8)
     {
         const int8_t one_fixed_point       = 1 << fixed_point_position;
         const int8_t minus_one_fixed_point = -one_fixed_point;
         library->fill_tensor_uniform(ref_src, 0, minus_one_fixed_point, one_fixed_point);
     }
     else
     {
         library->fill_tensor_uniform(ref_src, 0);
     }
     // Compute reference
     ReferenceCPP::normalization_layer(ref_src, ref_dst, norm_info);
     return ref_dst;
 }
RawTensor compute_reference_pixel_wise_multiplication (const TensorShape & shape, DataType dt_in0, DataType dt_in1, DataType dt_out, float scale, ConvertPolicy convert_policy, RoundingPolicy rounding_policy) static
Compute reference pixel-wise multiplication.
Parameters
[in] shape Shape of the input and output tensors.
[in] dt_in0 Data type of first input tensor.
[in] dt_in1 Data type of second input tensor.
[in] dt_out Data type of the output tensor.
[in] scale Non-negative scale.
[in] convert_policy Overflow policy of the operation.
[in] rounding_policy Rounding policy of the operation.
Returns
Computed raw tensor.
Definition at line 280 of file Reference.cpp.
References arm_compute::test::library, and arm_compute::test::validation::tensor_operations::pixel_wise_multiplication().
 {
     // Create reference
     RawTensor ref_src1 = library->get(shape, dt_in0);
     RawTensor ref_src2 = library->get(shape, dt_in1);
     RawTensor ref_dst  = library->get(shape, dt_out);
     // Fill reference
     library->fill_tensor_uniform(ref_src1, 0);
     library->fill_tensor_uniform(ref_src2, 1);
     // Compute reference
     ReferenceCPP::pixel_wise_multiplication(ref_src1, ref_src2, ref_dst, scale, convert_policy, rounding_policy);
     return ref_dst;
 }
RawTensor compute_reference_pooling_layer (const TensorShape & shape_in, const TensorShape & shape_out, DataType dt, PoolingLayerInfo pool_info, int fixed_point_position = 0) static
Compute reference pooling layer.
Parameters
[in] shape_in Shape of the input tensor.
[in] shape_out Shape of the output tensor.
[in] dt Data type of input and output tensors.
[in] pool_info Pooling Layer information.
[in] fixed_point_position (Optional) Number of bits for the fractional part of the fixed point numbers.
Returns
Computed raw tensor.
Definition at line 499 of file Reference.cpp.
References ARM_COMPUTE_ERROR, arm_compute::F32, arm_compute::test::library, arm_compute::test::fixed_point_arithmetic::detail::max(), arm_compute::test::fixed_point_arithmetic::detail::min(), arm_compute::test::validation::tensor_operations::pooling_layer(), and arm_compute::QS8.
 {
     // Create reference
     RawTensor ref_src = library->get(shape_in, dt, 1, fixed_point_position);
     RawTensor ref_dst = library->get(shape_out, dt, 1, fixed_point_position);
     // Fill reference
     int min = 0;
     int max = 0;
     switch(dt)
     {
         case DataType::F32:
             min = -1;
             max = 1;
             break;
         case DataType::QS8:
             min = -(1 << fixed_point_position);
             max = (1 << fixed_point_position);
             break;
         default:
             ARM_COMPUTE_ERROR("DataType not supported.");
     }
     std::uniform_real_distribution<> distribution(min, max);
     library->fill(ref_src, distribution, 0.0);
     // Compute reference
     ReferenceCPP::pooling_layer(ref_src, ref_dst, pool_info, fixed_point_position);
     return ref_dst;
 }
RawTensor compute_reference_softmax_layer (const TensorShape & shape, DataType dt, int fixed_point_position = 0) static
Compute reference softmax layer.
Parameters
[in] shape Shape of the input and output tensors.
[in] dt Data type of input and output tensors.
[in] fixed_point_position (Optional) Number of bits for the fractional part of the fixed point numbers
Returns
Computed raw tensor.
Definition at line 530 of file Reference.cpp.
References arm_compute::is_data_type_float(), arm_compute::test::library, and arm_compute::test::validation::tensor_operations::softmax_layer().
 {
     // Create reference
     RawTensor ref_src = library->get(shape, dt, 1, fixed_point_position);
     RawTensor ref_dst = library->get(shape, dt, 1, fixed_point_position);
     // Fill reference
     if(arm_compute::is_data_type_float(dt))
     {
         std::uniform_real_distribution<> distribution(-10, 10);
         library->fill(ref_src, distribution, 0);
     }
     else
     {
         int                             one_fixed = 1 << fixed_point_position;
         std::uniform_int_distribution<> distribution(-one_fixed, one_fixed);
         library->fill(ref_src, distribution, 0);
     }
     // Compute reference
     ReferenceCPP::softmax_layer(ref_src, ref_dst);
     return ref_dst;
 }
RawTensor compute_reference_threshold (const TensorShape & shape, uint8_t threshold, uint8_t false_value, uint8_t true_value, ThresholdType type, uint8_t upper) static
Compute reference threshold.
Parameters
[in] shape Shape of the input and output tensors.
[in] threshold Threshold. When the threshold type is RANGE, this is used as the lower threshold.
[in] false_value value to set when the condition is not respected.
[in] true_value value to set when the condition is respected.
[in] type Thresholding type. Either RANGE or BINARY.
[in] upper Upper threshold. Only used when the thresholding type is RANGE.
Returns
Computed raw tensor.
Definition at line 316 of file Reference.cpp.
References arm_compute::test::library, arm_compute::test::validation::tensor_operations::threshold(), and arm_compute::U8.
 {
     // Create reference
     RawTensor ref_src1 = library->get(shape, DataType::U8);
     RawTensor ref_dst  = library->get(shape, DataType::U8);
     // Fill reference
     library->fill_tensor_uniform(ref_src1, 0);
     // Compute reference
     ReferenceCPP::threshold(ref_src1, ref_dst, threshold, false_value, true_value, type, upper);
     return ref_dst;
 }
The documentation for this class was generated from the following files:
tests/validation/Reference.h
tests/validation/Reference.cpp