Compute Library: RawTensor Class Reference
RawTensor Class Reference final
Simple tensor object that stores elements in a consecutive chunk of memory.
#include <RawTensor.h>
Public Types
using BufferType = uint8_t
using Buffer = std::unique_ptr< BufferType[]>
Public Member Functions
RawTensor (TensorShape shape, Format format, int fixed_point_position=0)
Create an uninitialised tensor of the given shape and format.
RawTensor (TensorShape shape, DataType data_type, int num_channels=1, int fixed_point_position=0)
Create an uninitialised tensor of the given shape and data type.
RawTensor (const RawTensor &tensor)
Create a deep copy of the given tensor.
RawTensor & operator= (RawTensor tensor)
Create a deep copy of the given tensor.
RawTensor (RawTensor &&)=default
~RawTensor ()=default
BufferType & operator[] (size_t offset)
Return value at offset in the buffer.
const BufferType & operator[] (size_t offset) const
Return constant value at offset in the buffer.
TensorShape shape () const
Shape of the tensor.
size_t element_size () const
Size of each element in the tensor in bytes.
size_t size () const
Total size of the tensor in bytes.
Format format () const
Image format of the tensor.
DataType data_type () const
Data type of the tensor.
int num_channels () const
Number of channels of the tensor.
int num_elements () const
Number of elements of the tensor.
int fixed_point_position () const
The number of bits for the fractional part of the fixed point numbers.
const BufferType * data () const
Constant pointer to the underlying buffer.
BufferType * data ()
Pointer to the underlying buffer.
const BufferType * operator() (const Coordinates &coord) const
Read only access to the specified element.
BufferType * operator() (const Coordinates &coord)
Access to the specified element.
Friends
void swap (RawTensor &tensor1, RawTensor &tensor2)
Swaps the content of the provided tensors.
Detailed Description
Simple tensor object that stores elements in a consecutive chunk of memory.
It can be created by either loading an image from a file which also initialises the content of the tensor or by explcitly specifying the size. The latter leaves the content uninitialised.
Furthermore, the class provides methods to convert the tensor's values into different image format.
Definition at line 47 of file RawTensor.h.
Member Typedef Documentation
using Buffer = std::unique_ptr<BufferType[]>
Definition at line 82 of file RawTensor.h.
using BufferType = uint8_t
Definition at line 81 of file RawTensor.h.
Constructor & Destructor Documentation
RawTensor (TensorShape shape, Format format, int fixed_point_position = 0)
Create an uninitialised tensor of the given shape and format.
Parameters
[in] shape Shape of the new raw tensor.
[in] format Format of the new raw tensor.
[in] fixed_point_position (Optional) Number of bits for the fractional part of the fixed point numbers
Definition at line 40 of file RawTensor.cpp.
References RawTensor::size().
     : _buffer(nullptr),
       _shape(shape),
       _format(format),
       _fixed_point_position(fixed_point_position)
 {
     _buffer = ::arm_compute::test::cpp14::make_unique<BufferType[]>(size());
 }
RawTensor (TensorShape shape, DataType data_type, int num_channels = 1, int fixed_point_position = 0)
Create an uninitialised tensor of the given shape and data type.
Parameters
[in] shape Shape of the new raw tensor.
[in] data_type Data type of the new raw tensor.
[in] num_channels (Optional) Number of channels (default = 1).
[in] fixed_point_position (Optional) Number of bits for the fractional part of the fixed point numbers (default = 0).
Definition at line 49 of file RawTensor.cpp.
References RawTensor::size().
     : _buffer(nullptr),
       _shape(shape),
       _data_type(data_type),
       _num_channels(num_channels),
       _fixed_point_position(fixed_point_position)
 {
     _buffer = ::arm_compute::test::cpp14::make_unique<BufferType[]>(size());
 }
RawTensor (const RawTensor & tensor)
Create a deep copy of the given tensor.
Parameters
[in] tensor To be copied tensor.
Definition at line 59 of file RawTensor.cpp.
References RawTensor::data(), and RawTensor::size().
     : _buffer(nullptr),
       _shape(tensor.shape()),
       _format(tensor.format()),
       _fixed_point_position(tensor.fixed_point_position())
 {
     _buffer = ::arm_compute::test::cpp14::make_unique<BufferType[]>(tensor.size());
     std::copy(tensor.data(), tensor.data() + size(), _buffer.get());
 }
RawTensor (RawTensor &&) default
~RawTensor () default
Member Function Documentation
const RawTensor::BufferType * data () const
Constant pointer to the underlying buffer.
Definition at line 148 of file RawTensor.cpp.
Referenced by ReferenceCPP::accumulate(), ReferenceCPP::accumulate_squared(), ReferenceCPP::accumulate_weighted(), ReferenceCPP::bitwise_and(), ReferenceCPP::bitwise_not(), ReferenceCPP::bitwise_or(), ReferenceCPP::bitwise_xor(), ReferenceCPP::box3x3(), TensorLibrary::fill(), ReferenceCPP::integral_image(), RawTensor::RawTensor(), and ReferenceCPP::threshold().
 {
     return _buffer.get();
 }
RawTensor::BufferType * data ()
Pointer to the underlying buffer.
Definition at line 153 of file RawTensor.cpp.
 {
     return _buffer.get();
 }
DataType data_type () const
Data type of the tensor.
Definition at line 112 of file RawTensor.cpp.
References arm_compute::data_type_from_format(), and arm_compute::UNKNOWN.
Referenced by ReferenceCPP::accumulate(), ReferenceCPP::accumulate_squared(), ReferenceCPP::accumulate_weighted(), ReferenceCPP::bitwise_and(), ReferenceCPP::bitwise_not(), ReferenceCPP::bitwise_or(), ReferenceCPP::bitwise_xor(), ReferenceCPP::box3x3(), RawTensor::element_size(), TensorLibrary::fill(), ReferenceCPP::integral_image(), ReferenceCPP::threshold(), and arm_compute::test::validation::validate().
 {
     if(_format != Format::UNKNOWN)
     {
         return data_type_from_format(_format);
     }
     else
     {
         return _data_type;
     }
 }
size_t element_size () const
Size of each element in the tensor in bytes.
Definition at line 91 of file RawTensor.cpp.
References RawTensor::data_type(), arm_compute::element_size_from_data_type(), and RawTensor::num_channels().
Referenced by TensorLibrary::fill(), RawTensor::operator()(), RawTensor::size(), and arm_compute::test::validation::validate().
 {
     return num_channels() * element_size_from_data_type(data_type());
 }
int fixed_point_position () const
The number of bits for the fractional part of the fixed point numbers.
Definition at line 96 of file RawTensor.cpp.
Referenced by ReferenceCPP::accumulate(), ReferenceCPP::accumulate_squared(), ReferenceCPP::accumulate_weighted(), ReferenceCPP::bitwise_and(), ReferenceCPP::bitwise_not(), ReferenceCPP::bitwise_or(), ReferenceCPP::bitwise_xor(), ReferenceCPP::box3x3(), ReferenceCPP::integral_image(), and ReferenceCPP::threshold().
 {
     return _fixed_point_position;
 }
Format format () const
Image format of the tensor.
Definition at line 107 of file RawTensor.cpp.
Referenced by TensorLibrary::fill(), and arm_compute::test::validation::validate().
 {
     return _format;
 }
int num_channels () const
Number of channels of the tensor.
Definition at line 124 of file RawTensor.cpp.
References ARM_COMPUTE_ERROR, arm_compute::RGB888, arm_compute::S16, arm_compute::S32, arm_compute::U16, arm_compute::U32, arm_compute::U8, and arm_compute::UNKNOWN.
Referenced by RawTensor::element_size(), and arm_compute::test::validation::validate().
 {
     switch(_format)
     {
         case Format::U8:
         case Format::S16:
         case Format::U16:
         case Format::S32:
         case Format::U32:
             return 1;
         case Format::RGB888:
             return 3;
         case Format::UNKNOWN:
             return _num_channels;
         default:
             ARM_COMPUTE_ERROR("NOT SUPPORTED!");
     }
 }
int num_elements () const
Number of elements of the tensor.
Definition at line 143 of file RawTensor.cpp.
References TensorShape::total_size().
Referenced by arm_compute::test::validation::validate().
 {
     return _shape.total_size();
 }
const RawTensor::BufferType * operator() (const Coordinates & coord) const
Read only access to the specified element.
Parameters
[in] coord Coordinates of the desired element.
Returns
A pointer to the desired element.
Definition at line 158 of file RawTensor.cpp.
References arm_compute::test::coord2index(), and RawTensor::element_size().
 {
     return _buffer.get() + coord2index(_shape, coord) * element_size();
 }
RawTensor::BufferType * operator() (const Coordinates & coord)
Access to the specified element.
Parameters
[in] coord Coordinates of the desired element.
Returns
A pointer to the desired element.
Definition at line 163 of file RawTensor.cpp.
References arm_compute::test::coord2index(), and RawTensor::element_size().
 {
     return _buffer.get() + coord2index(_shape, coord) * element_size();
 }
RawTensor & operator= (RawTensor tensor)
Create a deep copy of the given tensor.
Parameters
[in] tensor To be copied tensor.
Definition at line 69 of file RawTensor.cpp.
References RawTensor::swap.
 {
     swap(*this, tensor);
     return *this;
 }
RawTensor::BufferType & operator[] (size_t offset)
Return value at offset in the buffer.
Parameters
[in] offset Offset within the buffer.
Definition at line 76 of file RawTensor.cpp.
References offset().
 {
     return _buffer[offset];
 }
const RawTensor::BufferType & operator[] (size_t offset) const
Return constant value at offset in the buffer.
Parameters
[in] offset Offset within the buffer.
Definition at line 81 of file RawTensor.cpp.
References offset().
 {
     return _buffer[offset];
 }
TensorShape shape () const
Shape of the tensor.
Definition at line 86 of file RawTensor.cpp.
Referenced by ReferenceCPP::accumulate(), ReferenceCPP::accumulate_squared(), ReferenceCPP::accumulate_weighted(), ReferenceCPP::bitwise_and(), ReferenceCPP::bitwise_not(), ReferenceCPP::bitwise_or(), ReferenceCPP::bitwise_xor(), ReferenceCPP::box3x3(), arm_compute::test::cl::create_tensor(), arm_compute::test::neon::create_tensor(), TensorLibrary::fill(), TensorLibrary::get(), ReferenceCPP::integral_image(), ReferenceCPP::threshold(), and arm_compute::test::validation::validate().
 {
     return _shape;
 }
size_t size () const
Total size of the tensor in bytes.
Definition at line 101 of file RawTensor.cpp.
References accumulate(), Dimensions< T >::cbegin(), Dimensions< T >::cend(), and RawTensor::element_size().
Referenced by TensorLibrary::fill(), and RawTensor::RawTensor().
 {
     const size_t size = std::accumulate(_shape.cbegin(), _shape.cend(), 1, std::multiplies<size_t>());
     return size * element_size();
 }
Friends And Related Function Documentation
void swap (RawTensor & tensor1, RawTensor & tensor2) friend
Swaps the content of the provided tensors.
Parameters
[in,out] tensor1 Tensor to be swapped.
[in,out] tensor2 Tensor to be swapped.
Definition at line 168 of file RawTensor.cpp.
Referenced by RawTensor::operator=(), and arm_compute::test::swap().
 {
     // Use unqualified call to swap to enable ADL. But make std::swap available
     // as backup.
     using std::swap;
     swap(tensor1._shape, tensor2._shape);
     swap(tensor1._format, tensor2._format);
     swap(tensor1._data_type, tensor2._data_type);
     swap(tensor1._num_channels, tensor2._num_channels);
     swap(tensor1._buffer, tensor2._buffer);
 }
The documentation for this class was generated from the following files:
tests/RawTensor.h
tests/RawTensor.cpp