Compute Library: CLMeanStdDevKernel Class Reference
CLMeanStdDevKernel Class Reference
Interface for the kernel to calculate mean and standard deviation of input image pixels.
#include <CLMeanStdDevKernel.h>
Public Member Functions
CLMeanStdDevKernel ()
Default constructor.
CLMeanStdDevKernel (const CLMeanStdDevKernel &)=delete
Prevent instances of this class from being copied (As this class contains pointers)
CLMeanStdDevKernel & operator= (const CLMeanStdDevKernel &)=delete
Prevent instances of this class from being copied (As this class contains pointers)
CLMeanStdDevKernel (CLMeanStdDevKernel &&)=default
Allow instances of this class to be moved.
CLMeanStdDevKernel & operator= (CLMeanStdDevKernel &&)=default
Allow instances of this class to be moved.
void configure (const ICLImage *input, float *mean, cl::Buffer *global_sum, float *stddev=nullptr, cl::Buffer *global_sum_squared=nullptr)
Initialise the kernel's input and outputs.
void run (const Window &window, cl::CommandQueue &queue) override
Enqueue the OpenCL kernel to process the given window on the passed OpenCL command queue.
BorderSize border_size () const override
The size of the border for that kernel.
Public Member Functions inherited from ICLKernel
ICLKernel ()
Constructor.
cl::Kernel & kernel ()
Returns a reference to the OpenCL kernel of this object.
template<typename T >
void add_1D_array_argument (unsigned int &idx, const ICLArray< T > *array, const Strides &strides, unsigned int num_dimensions, const Window &window)
Add the passed 1D array's parameters to the object's kernel's arguments starting from the index idx.
void add_1D_tensor_argument (unsigned int &idx, const ICLTensor *tensor, const Window &window)
Add the passed 1D tensor's parameters to the object's kernel's arguments starting from the index idx.
void add_2D_tensor_argument (unsigned int &idx, const ICLTensor *tensor, const Window &window)
Add the passed 2D tensor's parameters to the object's kernel's arguments starting from the index idx.
void add_3D_tensor_argument (unsigned int &idx, const ICLTensor *tensor, const Window &window)
Add the passed 3D tensor's parameters to the object's kernel's arguments starting from the index idx.
void add_4D_tensor_argument (unsigned int &idx, const ICLTensor *tensor, const Window &window)
Add the passed 4D tensor's parameters to the object's kernel's arguments starting from the index idx.
template<typename T >
void add_argument (unsigned int &idx, T value)
Add the passed parameters to the object's kernel's arguments starting from the index idx.
void set_lws_hint (const cl::NDRange &lws_hint)
Set the Local-Workgroup-Size hint.
cl::NDRange lws_hint () const
Return the Local-Workgroup-Size hint.
const std::string & config_id () const
Get the configuration ID.
void set_target (GPUTarget target)
Set the targeted GPU architecture.
void set_target (cl::Device &device)
Set the targeted GPU architecture according to the CL device.
GPUTarget get_target () const
Get the targeted GPU architecture.
size_t get_max_workgroup_size ()
Get the maximum workgroup size for the device the CLKernelLibrary uses.
template<typename T , unsigned int dimension_size>
void add_array_argument (unsigned &idx, const ICLArray< T > *array, const Strides &strides, unsigned int num_dimensions, const Window &window)
Add the passed array's parameters to the object's kernel's arguments starting from the index idx.
template<unsigned int dimension_size>
void add_tensor_argument (unsigned &idx, const ICLTensor *tensor, const Window &window)
Public Member Functions inherited from IKernel
IKernel ()
Constructor.
virtual ~IKernel ()=default
Destructor.
virtual bool is_parallelisable () const
Indicates whether or not the kernel is parallelisable.
const Window & window () const
The maximum window the kernel can be executed on.
Static Public Member Functions
static Status validate (const ITensorInfo *input, float *mean, cl::Buffer *global_sum, float *stddev=nullptr, cl::Buffer *global_sum_squared=nullptr)
Static function to check if given info will lead to a valid configuration of CLMeanStdDevKernel.
Static Public Member Functions inherited from ICLKernel
static constexpr unsigned int num_arguments_per_1D_array ()
Returns the number of arguments enqueued per 1D array object.
static constexpr unsigned int num_arguments_per_1D_tensor ()
Returns the number of arguments enqueued per 1D tensor object.
static constexpr unsigned int num_arguments_per_2D_tensor ()
Returns the number of arguments enqueued per 2D tensor object.
static constexpr unsigned int num_arguments_per_3D_tensor ()
Returns the number of arguments enqueued per 3D tensor object.
static constexpr unsigned int num_arguments_per_4D_tensor ()
Returns the number of arguments enqueued per 4D tensor object.
static cl::NDRange gws_from_window (const Window &window)
Get the global work size given an execution window.
Detailed Description
Interface for the kernel to calculate mean and standard deviation of input image pixels.
Definition at line 40 of file CLMeanStdDevKernel.h.
Constructor & Destructor Documentation
CLMeanStdDevKernel() [1/3]
CLMeanStdDevKernel ()
Default constructor.
Definition at line 43 of file CLMeanStdDevKernel.cpp.
     : _input(nullptr), _mean(nullptr), _stddev(nullptr), _global_sum(nullptr), _global_sum_squared(nullptr), _border_size(0)
 {
 }
CLMeanStdDevKernel() [2/3]
CLMeanStdDevKernel (const CLMeanStdDevKernel &) delete
Prevent instances of this class from being copied (As this class contains pointers)
CLMeanStdDevKernel() [3/3]
CLMeanStdDevKernel (CLMeanStdDevKernel &&) default
Allow instances of this class to be moved.
Member Function Documentation
border_size()
BorderSize border_size () const override virtual
The size of the border for that kernel.
Returns
The width in number of elements of the border.
Reimplemented from IKernel.
Definition at line 48 of file CLMeanStdDevKernel.cpp.
 {
     return _border_size;
 }
Referenced by CLMeanStdDev::configure().
configure()
void configure (const ICLImage * input, float * mean, cl::Buffer * global_sum, float * stddev = nullptr, cl::Buffer * global_sum_squared = nullptr)
Initialise the kernel's input and outputs.
Parameters
[in] input Input image. Data types supported: U8.
[out] mean Input average pixel value.
[out] global_sum Keeps global sum of pixel values (Buffer size: 1 cl_ulong).
[out] stddev (Optional) Output standard deviation of pixel values.
[out] global_sum_squared (Optional if stddev is not set, required if stddev is set) Keeps global sum of squared pixel values (Buffer size: 1 cl_ulong).
Definition at line 66 of file CLMeanStdDevKernel.cpp.
 {
     ARM_COMPUTE_ERROR_ON_NULLPTR(input, mean, global_sum);
     ARM_COMPUTE_ERROR_ON(stddev && nullptr == global_sum_squared);
     ARM_COMPUTE_ERROR_THROW_ON(CLMeanStdDevKernel::validate(input->info(), mean, global_sum, stddev, global_sum_squared));
     _input              = input;
     _mean               = mean;
     _stddev             = stddev;
     _global_sum         = global_sum;
     _global_sum_squared = global_sum_squared;
     // Create kernel
     std::set<std::string> build_opts;
     if(_stddev != nullptr)
     {
         build_opts.insert("-DSTDDEV");
     }
     _kernel = static_cast<cl::Kernel>(CLKernelLibrary::get().create_kernel("mean_stddev_accumulate", build_opts));
     // Set fixed arguments
     unsigned int idx = num_arguments_per_2D_tensor(); //Skip the input parameters
     _kernel.setArg(idx++, static_cast<cl_uint>(input->info()->dimension(1)));
     _kernel.setArg(idx++, *_global_sum);
     if(_stddev != nullptr)
     {
         _kernel.setArg(idx++, *_global_sum_squared);
     }
     // Configure kernel window
     constexpr unsigned int num_elems_processed_per_iteration_x = 8;
     const unsigned int     num_elems_processed_per_iteration_y = input->info()->dimension(1);
     _border_size = BorderSize(ceil_to_multiple(input->info()->dimension(0), num_elems_processed_per_iteration_x) - input->info()->dimension(0));
     Window                win = calculate_max_window(*input->info(), Steps(num_elems_processed_per_iteration_x, num_elems_processed_per_iteration_y));
     AccessWindowRectangle input_access(input->info(), 0, 0, num_elems_processed_per_iteration_x, num_elems_processed_per_iteration_y);
     update_window_and_padding(win, input_access);
     ICLKernel::configure_internal(win);
 }
References ARM_COMPUTE_ERROR_ON, ARM_COMPUTE_ERROR_ON_NULLPTR, ARM_COMPUTE_ERROR_THROW_ON, arm_compute::calculate_max_window(), arm_compute::ceil_to_multiple(), arm_compute::create_kernel(), ITensorInfo::dimension(), CLKernelLibrary::get(), ITensor::info(), ICLKernel::num_arguments_per_2D_tensor(), arm_compute::update_window_and_padding(), and CLMeanStdDevKernel::validate().
Referenced by CLMeanStdDev::configure().
operator=() [1/2]
CLMeanStdDevKernel& operator= (const CLMeanStdDevKernel &) delete
Prevent instances of this class from being copied (As this class contains pointers)
operator=() [2/2]
CLMeanStdDevKernel& operator= (CLMeanStdDevKernel &&) default
Allow instances of this class to be moved.
run()
void run (const Window & window, cl::CommandQueue & queue) override virtual
Enqueue the OpenCL kernel to process the given window on the passed OpenCL command queue.
Note
The queue is not flushed by this method, and therefore the kernel will not have been executed by the time this method returns.
Parameters
[in] window Region on which to execute the kernel. (Must be a valid region of the window returned by window()).
[in,out] queue Command queue on which to enqueue the kernel.
Implements ICLKernel.
Definition at line 112 of file CLMeanStdDevKernel.cpp.
 {
     ARM_COMPUTE_ERROR_ON_UNCONFIGURED_KERNEL(this);
     ARM_COMPUTE_ERROR_ON_INVALID_SUBWINDOW(ICLKernel::window(), window);
     // Clear sums
     static const cl_ulong zero = 0;
     queue.enqueueWriteBuffer(*_global_sum, CL_FALSE, 0, sizeof(cl_ulong), &zero);
     if(_stddev != nullptr)
     {
         queue.enqueueWriteBuffer(*_global_sum_squared, CL_FALSE, 0, sizeof(cl_ulong), &zero);
     }
     Window slice = window.first_slice_window_2D();
     do
     {
         unsigned int idx = 0;
         add_2D_tensor_argument(idx, _input, slice);
         // Set slice step equal to height to force gws[1] to 1,
         // as each thread calculates the sum across all rows and columns equal to the number of elements processed by each work-item
         slice.set_dimension_step(Window::DimY, _input->info()->dimension(1));
         enqueue(queue, *this, slice);
     }
     while(window.slide_window_slice_2D(slice));
     // Calculate mean and stddev
     cl_ulong    global_sum         = 0;
     cl_ulong    global_sum_squared = 0;
     const float num_pixels         = _input->info()->dimension(0) * _input->info()->dimension(1);
     queue.enqueueReadBuffer(*_global_sum, CL_TRUE, 0, sizeof(cl_ulong), static_cast<void *>(&global_sum));
     const float mean = global_sum / num_pixels;
     *_mean           = mean;
     if(_stddev != nullptr)
     {
         queue.enqueueReadBuffer(*_global_sum_squared, CL_TRUE, 0, sizeof(cl_ulong), static_cast<void *>(&global_sum_squared));
         *_stddev = std::sqrt((global_sum_squared / num_pixels) - (mean * mean));
     }
 }
References ICLKernel::add_2D_tensor_argument(), ARM_COMPUTE_ERROR_ON_INVALID_SUBWINDOW, ARM_COMPUTE_ERROR_ON_UNCONFIGURED_KERNEL, ITensorInfo::dimension(), Window::DimY, arm_compute::enqueue(), Window::first_slice_window_2D(), ITensor::info(), arm_compute::test::validation::reference::slice(), Window::slide_window_slice_2D(), and IKernel::window().
validate()
Status validate (const ITensorInfo * input, float * mean, cl::Buffer * global_sum, float * stddev = nullptr, cl::Buffer * global_sum_squared = nullptr) static
Static function to check if given info will lead to a valid configuration of CLMeanStdDevKernel.
Parameters
[in] input Input image info. Data types supported: U8.
[in] mean Input average pixel value.
[in] global_sum Keeps global sum of pixel values.
[in] stddev (Optional) Output standard deviation of pixel values.
[in] global_sum_squared (Optional if stddev is not set, required if stddev is set) Keeps global sum of squared pixel values.
Returns
a status
Definition at line 53 of file CLMeanStdDevKernel.cpp.
 {
     ARM_COMPUTE_UNUSED(mean);
     ARM_COMPUTE_UNUSED(stddev);
     ARM_COMPUTE_UNUSED(global_sum);
     ARM_COMPUTE_UNUSED(global_sum_squared);
     ARM_COMPUTE_RETURN_ERROR_ON_INT64_BASE_ATOMICS_UNSUPPORTED();
     ARM_COMPUTE_RETURN_ERROR_ON_TENSOR_NOT_2D(input);
     ARM_COMPUTE_RETURN_ERROR_ON_DATA_TYPE_CHANNEL_NOT_IN(input, 1, DataType::U8);
     return Status{};
 }
References ARM_COMPUTE_RETURN_ERROR_ON_DATA_TYPE_CHANNEL_NOT_IN, ARM_COMPUTE_RETURN_ERROR_ON_INT64_BASE_ATOMICS_UNSUPPORTED, ARM_COMPUTE_RETURN_ERROR_ON_TENSOR_NOT_2D, ARM_COMPUTE_UNUSED, and arm_compute::U8.
Referenced by CLMeanStdDevKernel::configure(), and CLMeanStdDev::validate().
The documentation for this class was generated from the following files:
arm_compute/core/CL/kernels/CLMeanStdDevKernel.h
src/core/CL/kernels/CLMeanStdDevKernel.cpp