Compute Library: NEGEMMLowpAssemblyMatrixMultiplyCore Class Reference
NEGEMMLowpAssemblyMatrixMultiplyCore Class Reference
Basic function to execute matrix multiply assembly kernels.
#include <NEGEMMLowpAssemblyMatrixMultiplyCore.h>
Public Member Functions
NEGEMMLowpAssemblyMatrixMultiplyCore (std::shared_ptr< IMemoryManager > memory_manager=nullptr)
Constructor.
void configure (const ITensor *a, const ITensor *b, ITensor *output)
Initialise the kernel's inputs, output.
void run () override
Run the kernels contained in the function.
Public Member Functions inherited from IFunction
virtual ~IFunction ()=default
Destructor.
virtual void prepare ()
Prepare the function for executing.
Detailed Description
Basic function to execute matrix multiply assembly kernels.
Definition at line 43 of file NEGEMMLowpAssemblyMatrixMultiplyCore.h.
Constructor & Destructor Documentation
NEGEMMLowpAssemblyMatrixMultiplyCore()
NEGEMMLowpAssemblyMatrixMultiplyCore (std::shared_ptr< IMemoryManager > memory_manager = nullptr)
Constructor.
Definition at line 41 of file NEGEMMLowpAssemblyMatrixMultiplyCore.cpp.
     : _memory_group(memory_manager), _asm_glue(memory_manager), _mm_kernel(nullptr), _mtx_a_reshape_kernel(nullptr), _mtx_b_reshape_kernel(nullptr), _tmp_a(), _tmp_b()
 {
 }
Member Function Documentation
configure()
void configure (const ITensor * a, const ITensor * b, ITensor * output)
Initialise the kernel's inputs, output.
Parameters
[in] a First input tensor (Matrix A). Data type supported: U8, S8.
[in] b Second input tensor (Matrix B). Data type supported: same as a
[out] output Output tensor. Data type supported: Data type supported: U32, S32
Definition at line 46 of file NEGEMMLowpAssemblyMatrixMultiplyCore.cpp.
 {
     ARM_COMPUTE_ERROR_ON_DATA_TYPE_CHANNEL_NOT_IN(a, 1, DataType::U8, DataType::S8);
     ARM_COMPUTE_ERROR_ON_DATA_TYPE_CHANNEL_NOT_IN(output, 1, DataType::U32, DataType::S32);
     ARM_COMPUTE_ERROR_ON_MISMATCHING_DATA_TYPES(a, b);
     ARM_COMPUTE_ERROR_ON_MSG((a)->info()->dimension(0) != (b)->info()->dimension(1), "The product AB is defined only if the number of columns in A is equal to the number of rows in B");
     ARM_COMPUTE_ERROR_ON_MSG((a)->info()->dimension(1) != (output)->info()->dimension(1), "The output matrix must have the same number of rows as the matrix A");
     ARM_COMPUTE_ERROR_ON_MSG((b)->info()->dimension(0) != (output)->info()->dimension(0), "The output matrix must have the same number of columns as the matrix B");
     bool run_optimised = false;
     switch(a->info()->data_type())
     {
         case DataType::S8:
         case DataType::QASYMM8:
         case DataType::U8:
         {
             _asm_glue.configure(a, b, output, 1.f, 0.f, true);
             run_optimised = _asm_glue.is_configured();
             break;
         }
         default:
         {
             ARM_COMPUTE_ERROR("Datatype not supported");
             break;
         }
     }
     if(!run_optimised)
     {
         // The interleaved output matrix will have the following shape: [ a_height * 4, ceil(a_width / 4.0f) ]
         TensorShape shape_tmp_a = a->info()->tensor_shape();
         shape_tmp_a.set(0, a->info()->dimension(0) * 4);
         shape_tmp_a.set(1, std::ceil(a->info()->dimension(1) / 4.f));
         // The transpose1xW output matrix will have the following shape: [ b_height * 16, ceil(b_width / 16.0f) ]
         TensorShape shape_tmp_b = b->info()->tensor_shape();
         shape_tmp_b.set(0, b->info()->dimension(1) * 16);
         shape_tmp_b.set(1, std::ceil(b->info()->dimension(0) / 16.f));
         TensorInfo info_a(shape_tmp_a, 1, a->info()->data_type());
         TensorInfo info_b(shape_tmp_b, 1, b->info()->data_type());
         _tmp_a.allocator()->init(info_a);
         _tmp_b.allocator()->init(info_b);
         _memory_group.manage(&_tmp_a);
         _memory_group.manage(&_tmp_b);
         // Configure interleave kernel
         {
             auto k = arm_compute::support::cpp14::make_unique<NEGEMMInterleave4x4Kernel>();
             k->configure(a, &_tmp_a);
             _mtx_a_reshape_kernel = std::move(k);
         }
         // Configure transpose kernel
         {
             auto k = arm_compute::support::cpp14::make_unique<NEGEMMTranspose1xWKernel>();
             k->configure(b, &_tmp_b);
             _mtx_b_reshape_kernel = std::move(k);
         }
         // Configure matrix multiply kernel
         {
             auto k = arm_compute::support::cpp14::make_unique<NEGEMMLowpMatrixMultiplyKernel>();
             k->configure(&_tmp_a, &_tmp_b, output);
             _mm_kernel = std::move(k);
         }
         // Allocate tensors
         _tmp_a.allocator()->allocate();
         _tmp_b.allocator()->allocate();
     }
 }
References TensorAllocator::allocate(), Tensor::allocator(), ARM_COMPUTE_ERROR, ARM_COMPUTE_ERROR_ON_DATA_TYPE_CHANNEL_NOT_IN, ARM_COMPUTE_ERROR_ON_MISMATCHING_DATA_TYPES, ARM_COMPUTE_ERROR_ON_MSG, arm_compute::test::validation::b, NEGEMMAssemblyDispatch::configure(), ITensorInfo::data_type(), ITensorInfo::dimension(), ITensor::info(), arm_compute::test::validation::info, TensorAllocator::init(), NEGEMMAssemblyDispatch::is_configured(), MemoryGroupBase< TensorType >::manage(), arm_compute::QASYMM8, arm_compute::S32, arm_compute::S8, TensorShape::set(), ITensorInfo::tensor_shape(), arm_compute::U32, and arm_compute::U8.
run()
void run () override virtual
Run the kernels contained in the function.
For NEON kernels:
Multi-threading is used for the kernels which are parallelisable.
By default std::thread::hardware_concurrency() threads are used.
Note
CPPScheduler::set_num_threads() can be used to manually set the number of threads
For OpenCL kernels:
All the kernels are enqueued on the queue associated with CLScheduler.
The queue is then flushed.
Note
The function will not block until the kernels are executed. It is the user's responsibility to wait.
Will call prepare() on first run if hasn't been done
Implements IFunction.
Definition at line 118 of file NEGEMMLowpAssemblyMatrixMultiplyCore.cpp.
 {
     MemoryGroupResourceScope scope_mg(_memory_group);
     if(_mtx_a_reshape_kernel)
     {
         NEScheduler::get().schedule(_mtx_a_reshape_kernel.get(), Window::DimY);
     }
     if(_mtx_b_reshape_kernel)
     {
         NEScheduler::get().schedule(_mtx_b_reshape_kernel.get(), Window::DimY);
     }
     if(_asm_glue.is_configured())
     {
         _asm_glue.run();
     }
     else
     {
         NEScheduler::get().schedule(_mm_kernel.get(), Window::DimY);
     }
 }
References Window::DimY, Scheduler::get(), NEGEMMAssemblyDispatch::is_configured(), NEGEMMAssemblyDispatch::run(), and IScheduler::schedule().
The documentation for this class was generated from the following files:
arm_compute/runtime/NEON/functions/NEGEMMLowpAssemblyMatrixMultiplyCore.h
src/runtime/NEON/functions/NEGEMMLowpAssemblyMatrixMultiplyCore.cpp