Compute Library: CLUpsampleLayerKernel Class Reference
CLUpsampleLayerKernel Class Reference
Interface for the UpsampleLayer kernel on OpenCL.
#include <CLUpsampleLayerKernel.h>
Public Member Functions
CLUpsampleLayerKernel ()
Constructor.
CLUpsampleLayerKernel (const CLUpsampleLayerKernel &)=delete
Prevent instances of this class from being copied (As this class contains pointers)
CLUpsampleLayerKernel & operator= (const CLUpsampleLayerKernel &)=delete
Prevent instances of this class from being copied (As this class contains pointers)
CLUpsampleLayerKernel (CLUpsampleLayerKernel &&)=default
Default Move Constructor.
CLUpsampleLayerKernel & operator= (CLUpsampleLayerKernel &&)=default
Default move assignment operator.
~CLUpsampleLayerKernel ()=default
Default destructor.
void configure (const ICLTensor *input, ICLTensor *output, const Size2D &info, const InterpolationPolicy upsampling_policy)
Initialise the kernel's input and output.
void run (const Window &window, cl::CommandQueue &queue) override
Enqueue the OpenCL kernel to process the given window on the passed OpenCL command queue.
Public Member Functions inherited from ICLKernel
ICLKernel ()
Constructor.
cl::Kernel & kernel ()
Returns a reference to the OpenCL kernel of this object.
template<typename T >
void add_1D_array_argument (unsigned int &idx, const ICLArray< T > *array, const Strides &strides, unsigned int num_dimensions, const Window &window)
Add the passed 1D array's parameters to the object's kernel's arguments starting from the index idx.
void add_1D_tensor_argument (unsigned int &idx, const ICLTensor *tensor, const Window &window)
Add the passed 1D tensor's parameters to the object's kernel's arguments starting from the index idx.
void add_2D_tensor_argument (unsigned int &idx, const ICLTensor *tensor, const Window &window)
Add the passed 2D tensor's parameters to the object's kernel's arguments starting from the index idx.
void add_3D_tensor_argument (unsigned int &idx, const ICLTensor *tensor, const Window &window)
Add the passed 3D tensor's parameters to the object's kernel's arguments starting from the index idx.
void add_4D_tensor_argument (unsigned int &idx, const ICLTensor *tensor, const Window &window)
Add the passed 4D tensor's parameters to the object's kernel's arguments starting from the index idx.
template<typename T >
void add_argument (unsigned int &idx, T value)
Add the passed parameters to the object's kernel's arguments starting from the index idx.
void set_lws_hint (const cl::NDRange &lws_hint)
Set the Local-Workgroup-Size hint.
cl::NDRange lws_hint () const
Return the Local-Workgroup-Size hint.
const std::string & config_id () const
Get the configuration ID.
void set_target (GPUTarget target)
Set the targeted GPU architecture.
void set_target (cl::Device &device)
Set the targeted GPU architecture according to the CL device.
GPUTarget get_target () const
Get the targeted GPU architecture.
size_t get_max_workgroup_size ()
Get the maximum workgroup size for the device the CLKernelLibrary uses.
template<typename T , unsigned int dimension_size>
void add_array_argument (unsigned &idx, const ICLArray< T > *array, const Strides &strides, unsigned int num_dimensions, const Window &window)
Add the passed array's parameters to the object's kernel's arguments starting from the index idx.
template<unsigned int dimension_size>
void add_tensor_argument (unsigned &idx, const ICLTensor *tensor, const Window &window)
Public Member Functions inherited from IKernel
IKernel ()
Constructor.
virtual ~IKernel ()=default
Destructor.
virtual bool is_parallelisable () const
Indicates whether or not the kernel is parallelisable.
virtual BorderSize border_size () const
The size of the border for that kernel.
const Window & window () const
The maximum window the kernel can be executed on.
Static Public Member Functions
static Status validate (const ITensorInfo *input, const ITensorInfo *output, const Size2D &info, const InterpolationPolicy upsampling_policy)
Static function to check if given info will lead to a valid configuration of CLUpsampleLayerKernel.
Static Public Member Functions inherited from ICLKernel
static constexpr unsigned int num_arguments_per_1D_array ()
Returns the number of arguments enqueued per 1D array object.
static constexpr unsigned int num_arguments_per_1D_tensor ()
Returns the number of arguments enqueued per 1D tensor object.
static constexpr unsigned int num_arguments_per_2D_tensor ()
Returns the number of arguments enqueued per 2D tensor object.
static constexpr unsigned int num_arguments_per_3D_tensor ()
Returns the number of arguments enqueued per 3D tensor object.
static constexpr unsigned int num_arguments_per_4D_tensor ()
Returns the number of arguments enqueued per 4D tensor object.
static cl::NDRange gws_from_window (const Window &window)
Get the global work size given an execution window.
Detailed Description
Interface for the UpsampleLayer kernel on OpenCL.
Definition at line 34 of file CLUpsampleLayerKernel.h.
Constructor & Destructor Documentation
CLUpsampleLayerKernel() [1/3]
CLUpsampleLayerKernel ()
Constructor.
Definition at line 39 of file CLUpsampleLayerKernel.cpp.
     : _input(nullptr), _output(nullptr), _info(), _num_elems_processed_per_iteration_input_x()
 {
 }
CLUpsampleLayerKernel() [2/3]
CLUpsampleLayerKernel (const CLUpsampleLayerKernel &) delete
Prevent instances of this class from being copied (As this class contains pointers)
CLUpsampleLayerKernel() [3/3]
CLUpsampleLayerKernel (CLUpsampleLayerKernel &&) default
Default Move Constructor.
~CLUpsampleLayerKernel()
~CLUpsampleLayerKernel () default
Default destructor.
Member Function Documentation
configure()
void configure (const ICLTensor * input, ICLTensor * output, const Size2D & info, const InterpolationPolicy upsampling_policy)
Initialise the kernel's input and output.
Parameters
[in] input Source tensor. Data types supported: U8/S8/QASYMM8/U16/S16/F16/U32/S32/F32.
[out] output Destination tensor. Data types supported: same as input.
[in] info Contains stride information described in Size2D.
[in] upsampling_policy Defines the policy to fill the intermediate pixels.
Definition at line 66 of file CLUpsampleLayerKernel.cpp.
 {
     ARM_COMPUTE_ERROR_ON_NULLPTR(input, output);
     ARM_COMPUTE_UNUSED(upsampling_policy);
     _input                                     = input;
     _output                                    = output;
     _info                                      = info;
     _num_elems_processed_per_iteration_input_x = 1;
     const DataLayout data_layout = input->info()->data_layout();
     TensorShape output_shape = misc::shape_calculator::compute_upsample_shape(*input->info(), info);
     auto_init_if_empty(*output->info(), output_shape, 1, input->info()->data_type());
     output->info()->set_data_layout(data_layout);
     unsigned int num_elems_processed_per_iteration_x = 16;
     const int    output_width_x                      = output->info()->dimension(0);
     const bool   multi_access_x                      = ((output_width_x / num_elems_processed_per_iteration_x) > 0);
     // Perform validation step
     ARM_COMPUTE_ERROR_THROW_ON(CLUpsampleLayerKernel::validate(input->info(), output->info(), info, upsampling_policy));
     Window win{};
     switch(data_layout)
     {
         case DataLayout::NCHW:
         {
             win = calculate_max_window(*output->info());
             win.set(Window::DimY, Window::Dimension(win.y().start(), win.y().end(), info.y()));
             if(multi_access_x)
             {
                 _num_elems_processed_per_iteration_input_x = num_elems_processed_per_iteration_x / info.x();
                 win.set(Window::DimX, Window::Dimension(win.x().start(), ceil_to_multiple(win.x().end(), num_elems_processed_per_iteration_x), num_elems_processed_per_iteration_x));
             }
             break;
         }
         case DataLayout::NHWC:
         {
             win = calculate_max_window(*output->info());
             win.set(Window::DimY, Window::Dimension(win.y().start(), win.y().end(), info.x()));
             win.set(Window::DimZ, Window::Dimension(win.z().start(), win.z().end(), info.y()));
             if(multi_access_x)
             {
                 _num_elems_processed_per_iteration_input_x = num_elems_processed_per_iteration_x;
                 win.set(Window::DimX, Window::Dimension(win.x().start(), ceil_to_multiple(win.x().end(),
                                                                                           num_elems_processed_per_iteration_x),
                                                         num_elems_processed_per_iteration_x));
             }
             break;
         }
         default:
             ARM_COMPUTE_ERROR("Not implemented");
     }
     // Create kernel
     CLBuildOptions build_opts;
     build_opts.add_option(("-DDATA_TYPE=" + get_cl_type_from_data_type(input->info()->data_type())));
     build_opts.add_option_if(multi_access_x, "-DVEC_SIZE_IN=" + support::cpp11::to_string(_num_elems_processed_per_iteration_input_x));
     build_opts.add_option_if(multi_access_x, "-DVEC_SIZE_OUT=" + support::cpp11::to_string(num_elems_processed_per_iteration_x));
     build_opts.add_option_if(multi_access_x, "-DLAST_ACCESSED_X_IN=" + support::cpp11::to_string(std::max<int>(_input->info()->dimension(0) - _num_elems_processed_per_iteration_input_x, 0)));
     build_opts.add_option_if(multi_access_x, "-DLAST_ACCESSED_X_OUT=" + support::cpp11::to_string(std::max<int>(output_width_x - num_elems_processed_per_iteration_x, 0)));
     _kernel = static_cast<cl::Kernel>(CLKernelLibrary::get().create_kernel("upsample_layer_" + lower_string(string_from_data_layout(input->info()->data_layout())), build_opts.options()));
     ICLKernel::configure_internal(win);
 }
References CLBuildOptions::add_option(), CLBuildOptions::add_option_if(), ARM_COMPUTE_ERROR, ARM_COMPUTE_ERROR_ON_NULLPTR, ARM_COMPUTE_ERROR_THROW_ON, ARM_COMPUTE_UNUSED, arm_compute::auto_init_if_empty(), arm_compute::calculate_max_window(), arm_compute::ceil_to_multiple(), arm_compute::misc::shape_calculator::compute_upsample_shape(), arm_compute::create_kernel(), ITensorInfo::data_layout(), ITensorInfo::data_type(), ITensorInfo::dimension(), Window::DimX, Window::DimY, Window::DimZ, CLKernelLibrary::get(), arm_compute::get_cl_type_from_data_type(), ITensor::info(), arm_compute::test::validation::info, arm_compute::lower_string(), arm_compute::NCHW, arm_compute::NHWC, CLBuildOptions::options(), arm_compute::test::validation::output_shape, Window::set(), ITensorInfo::set_data_layout(), arm_compute::string_from_data_layout(), arm_compute::support::cpp11::to_string(), and CLUpsampleLayerKernel::validate().
Referenced by CLUpsampleLayer::configure().
operator=() [1/2]
CLUpsampleLayerKernel& operator= (const CLUpsampleLayerKernel &) delete
Prevent instances of this class from being copied (As this class contains pointers)
operator=() [2/2]
CLUpsampleLayerKernel& operator= (CLUpsampleLayerKernel &&) default
Default move assignment operator.
run()
void run (const Window & window, cl::CommandQueue & queue) override virtual
Enqueue the OpenCL kernel to process the given window on the passed OpenCL command queue.
Note
The queue is not flushed by this method, and therefore the kernel will not have been executed by the time this method returns.
Parameters
[in] window Region on which to execute the kernel. (Must be a valid region of the window returned by window()).
[in,out] queue Command queue on which to enqueue the kernel.
Implements ICLKernel.
Definition at line 134 of file CLUpsampleLayerKernel.cpp.
 {
     ARM_COMPUTE_ERROR_ON_UNCONFIGURED_KERNEL(this);
     ARM_COMPUTE_ERROR_ON_INVALID_SUBWINDOW(ICLKernel::window(), window);
     Window collapsed_window = window.collapse_if_possible(ICLKernel::window(), Window::DimZ);
     Window slice_out        = collapsed_window.first_slice_window_3D();
     Window slice_in         = collapsed_window.first_slice_window_3D();
     DataLayout data_layout = _input->info()->data_layout();
     switch(data_layout)
     {
         case DataLayout::NCHW:
             slice_in.set(Window::DimX, Window::Dimension(0, _input->info()->dimension(0), _num_elems_processed_per_iteration_input_x));
             slice_in.set(Window::DimY, Window::Dimension(0, _input->info()->dimension(1), 1));
             break;
         case DataLayout::NHWC:
             slice_in.set(Window::DimY, Window::Dimension(0, _input->info()->dimension(1), 1));
             slice_in.set(Window::DimZ, Window::Dimension(0, _input->info()->dimension(2), 1));
             break;
         default:
             ARM_COMPUTE_ERROR("Not implemented");
     }
     do
     {
         unsigned int idx = 0;
         add_3D_tensor_argument(idx, _input, slice_in);
         add_3D_tensor_argument(idx, _output, slice_out);
         enqueue(queue, *this, slice_out);
     }
     while(collapsed_window.slide_window_slice_3D(slice_out) && collapsed_window.slide_window_slice_3D(slice_in));
 }
References ICLKernel::add_3D_tensor_argument(), ARM_COMPUTE_ERROR, ARM_COMPUTE_ERROR_ON_INVALID_SUBWINDOW, ARM_COMPUTE_ERROR_ON_UNCONFIGURED_KERNEL, Window::collapse_if_possible(), ITensorInfo::data_layout(), ITensorInfo::dimension(), Window::DimX, Window::DimY, Window::DimZ, arm_compute::enqueue(), Window::first_slice_window_3D(), ITensor::info(), arm_compute::NCHW, arm_compute::NHWC, Window::set(), Window::slide_window_slice_3D(), and IKernel::window().
validate()
Status validate (const ITensorInfo * input, const ITensorInfo * output, const Size2D & info, const InterpolationPolicy upsampling_policy) static
Static function to check if given info will lead to a valid configuration of CLUpsampleLayerKernel.
Parameters
[in] input Source tensor info. Data types supported: U8/S8/QASYMM8/U16/S16/F16/U32/S32/F32.
[in] output Destination tensor info. Data types supported: same as input.
[in] info Contains stride information described in Size2D.
[in] upsampling_policy Defines the policy to fill the intermediate pixels.
Returns
a status
Definition at line 44 of file CLUpsampleLayerKernel.cpp.
 {
     ARM_COMPUTE_RETURN_ERROR_ON_NULLPTR(input, output);
     ARM_COMPUTE_UNUSED(upsampling_policy);
     DataLayout data_layout = input->data_layout();
     const int  idx_width   = get_data_layout_dimension_index(data_layout, DataLayoutDimension::WIDTH);
     const int  idx_height  = get_data_layout_dimension_index(data_layout, DataLayoutDimension::HEIGHT);
     ARM_COMPUTE_RETURN_ERROR_ON_F16_UNSUPPORTED(input);
     ARM_COMPUTE_RETURN_ERROR_ON_DATA_TYPE_CHANNEL_NOT_IN(input, 1, DataType::F16, DataType::F32);
     ARM_COMPUTE_RETURN_ERROR_ON_MISMATCHING_DATA_TYPES(input, output);
     ARM_COMPUTE_RETURN_ERROR_ON_MISMATCHING_DATA_LAYOUT(input, output);
     ARM_COMPUTE_RETURN_ERROR_ON(output->dimension(idx_width) != info.x() * input->dimension(idx_width));
     ARM_COMPUTE_RETURN_ERROR_ON(output->dimension(idx_height) != info.y() * input->dimension(idx_height));
     ARM_COMPUTE_RETURN_ERROR_ON_MSG(info.x() != 2 || info.y() != 2, "Only stride 2 is supported");
     ARM_COMPUTE_RETURN_ERROR_ON_MSG(upsampling_policy != InterpolationPolicy::NEAREST_NEIGHBOR, "Only nearest neighbor policy supported");
     ARM_COMPUTE_RETURN_ERROR_ON_MISMATCHING_QUANTIZATION_INFO(input, output);
     return Status{};
 }
References ARM_COMPUTE_RETURN_ERROR_ON, ARM_COMPUTE_RETURN_ERROR_ON_DATA_TYPE_CHANNEL_NOT_IN, ARM_COMPUTE_RETURN_ERROR_ON_F16_UNSUPPORTED, ARM_COMPUTE_RETURN_ERROR_ON_MISMATCHING_DATA_LAYOUT, ARM_COMPUTE_RETURN_ERROR_ON_MISMATCHING_DATA_TYPES, ARM_COMPUTE_RETURN_ERROR_ON_MISMATCHING_QUANTIZATION_INFO, ARM_COMPUTE_RETURN_ERROR_ON_MSG, ARM_COMPUTE_RETURN_ERROR_ON_NULLPTR, ARM_COMPUTE_UNUSED, ITensorInfo::data_layout(), ITensorInfo::dimension(), arm_compute::F16, arm_compute::F32, arm_compute::get_data_layout_dimension_index(), arm_compute::HEIGHT, arm_compute::test::validation::info, arm_compute::NEAREST_NEIGHBOR, and arm_compute::WIDTH.
Referenced by CLUpsampleLayerKernel::configure(), and CLUpsampleLayer::validate().
The documentation for this class was generated from the following files:
arm_compute/core/CL/kernels/CLUpsampleLayerKernel.h
src/core/CL/kernels/CLUpsampleLayerKernel.cpp