Compute Library: GCConcatenateLayer Class Reference
GCConcatenateLayer Class Reference
Basic function to execute concatenate tensors along a given axis.
#include <GCConcatenateLayer.h>
Public Member Functions
GCConcatenateLayer ()
Default constructor.
void configure (std::vector< IGCTensor * > inputs_vector, IGCTensor *output, size_t axis)
Initialise the kernel's inputs vector and output.
void run () override
Run the kernels contained in the function.
Public Member Functions inherited from IFunction
virtual ~IFunction ()=default
Destructor.
virtual void prepare ()
Prepare the function for executing.
Detailed Description
Basic function to execute concatenate tensors along a given axis.
This function calls the following kernels:
Note
only axis z is supported
GCDepthConcatenateLayerKernel
Definition at line 44 of file GCConcatenateLayer.h.
Constructor & Destructor Documentation
GCConcatenateLayer()
GCConcatenateLayer ()
Default constructor.
Definition at line 36 of file GCConcatenateLayer.cpp.
     : _concat_kernels(),
       _num_inputs(0),
       _axis(Window::DimZ)
 {
 }
Member Function Documentation
configure()
void configure (std::vector< IGCTensor * > inputs_vector, IGCTensor * output, size_t axis)
Initialise the kernel's inputs vector and output.
Note
Input and output tensor dimensions preconditions defer depending on the concatenation axis.
Parameters
[in,out] inputs_vector The vectors containing all the tensors to concatenate. Data types supported: F16/F32.
[out] output Output tensor. Data types supported: Same as input.
[in] axis Concatenation axis. Supported underlying concatenation axis is 2.
Definition at line 43 of file GCConcatenateLayer.cpp.
 {
     ARM_COMPUTE_ERROR_ON(inputs_vector.size() < 2);
     _num_inputs = inputs_vector.size();
     _axis       = axis;
     TensorShape output_shape = arm_compute::misc::shape_calculator::calculate_concatenate_shape(inputs_vector, axis);
     // Output auto inizialitation if not yet initialized
     auto_init_if_empty(*output->info(), output_shape, 1, inputs_vector[0]->info()->data_type());
     unsigned int offset = 0;
     switch(axis)
     {
         case Window::DimZ:
         {
             for(unsigned int i = 0; i < _num_inputs; ++i)
             {
                 auto kernel = support::cpp14::make_unique<GCDepthConcatenateLayerKernel>();
                 kernel->configure(inputs_vector.at(i), offset, output);
                 offset += inputs_vector.at(i)->info()->dimension(axis);
                 _concat_kernels.emplace_back(std::move(kernel));
             }
             break;
         }
         default:
             ARM_COMPUTE_ERROR("Axis not supported");
     }
 }
References ARM_COMPUTE_ERROR, ARM_COMPUTE_ERROR_ON, arm_compute::auto_init_if_empty(), arm_compute::test::validation::axis, arm_compute::misc::shape_calculator::calculate_concatenate_shape(), Window::DimZ, ITensor::info(), offset(), and arm_compute::test::validation::output_shape.
run()
void run () override virtual
Run the kernels contained in the function.
For NEON kernels:
Multi-threading is used for the kernels which are parallelisable.
By default std::thread::hardware_concurrency() threads are used.
Note
CPPScheduler::set_num_threads() can be used to manually set the number of threads
For OpenCL kernels:
All the kernels are enqueued on the queue associated with CLScheduler.
The queue is then flushed.
Note
The function will not block until the kernels are executed. It is the user's responsibility to wait.
Will call prepare() on first run if hasn't been done
Implements IFunction.
Definition at line 74 of file GCConcatenateLayer.cpp.
 {
     for(auto &kernel : _concat_kernels)
     {
         GCScheduler::get().dispatch(*kernel, true);
     }
 }
References GCScheduler::dispatch(), and GCScheduler::get().
The documentation for this class was generated from the following files:
arm_compute/runtime/GLES_COMPUTE/functions/GCConcatenateLayer.h
src/runtime/GLES_COMPUTE/functions/GCConcatenateLayer.cpp