Compute Library: CLChannelCombineKernel Class Reference
CLChannelCombineKernel Class Reference
Interface for the channel combine kernel.
#include <CLChannelCombineKernel.h>
Public Member Functions
CLChannelCombineKernel ()
Default constructor.
CLChannelCombineKernel (const CLChannelCombineKernel &)=delete
Prevent instances of this class from being copied (As this class contains pointers)
CLChannelCombineKernel & operator= (const CLChannelCombineKernel &)=delete
Prevent instances of this class from being copied (As this class contains pointers)
CLChannelCombineKernel (CLChannelCombineKernel &&)=default
Allow instances of this class to be moved.
CLChannelCombineKernel & operator= (CLChannelCombineKernel &&)=default
Allow instances of this class to be moved.
~CLChannelCombineKernel ()=default
Default destructor.
void configure (const ICLTensor *plane0, const ICLTensor *plane1, const ICLTensor *plane2, const ICLTensor *plane3, ICLTensor *output)
Configure function's inputs and outputs.
void configure (const ICLImage *plane0, const ICLImage *plane1, const ICLImage *plane2, ICLMultiImage *output)
Configure function's inputs and outputs.
void run (const Window &window, cl::CommandQueue &queue) override
Enqueue the OpenCL kernel to process the given window on the passed OpenCL command queue.
Public Member Functions inherited from ICLKernel
ICLKernel ()
Constructor.
cl::Kernel & kernel ()
Returns a reference to the OpenCL kernel of this object.
template<typename T >
void add_1D_array_argument (unsigned int &idx, const ICLArray< T > *array, const Strides &strides, unsigned int num_dimensions, const Window &window)
Add the passed 1D array's parameters to the object's kernel's arguments starting from the index idx.
void add_1D_tensor_argument (unsigned int &idx, const ICLTensor *tensor, const Window &window)
Add the passed 1D tensor's parameters to the object's kernel's arguments starting from the index idx.
void add_1D_tensor_argument_if (bool cond, unsigned int &idx, const ICLTensor *tensor, const Window &window)
Add the passed 1D tensor's parameters to the object's kernel's arguments starting from the index idx if the condition is true.
void add_2D_tensor_argument (unsigned int &idx, const ICLTensor *tensor, const Window &window)
Add the passed 2D tensor's parameters to the object's kernel's arguments starting from the index idx.
void add_2D_tensor_argument_if (bool cond, unsigned int &idx, const ICLTensor *tensor, const Window &window)
Add the passed 2D tensor's parameters to the object's kernel's arguments starting from the index idx if the condition is true.
void add_3D_tensor_argument (unsigned int &idx, const ICLTensor *tensor, const Window &window)
Add the passed 3D tensor's parameters to the object's kernel's arguments starting from the index idx.
void add_4D_tensor_argument (unsigned int &idx, const ICLTensor *tensor, const Window &window)
Add the passed 4D tensor's parameters to the object's kernel's arguments starting from the index idx.
template<typename T >
void add_argument (unsigned int &idx, T value)
Add the passed parameters to the object's kernel's arguments starting from the index idx.
void set_lws_hint (const cl::NDRange &lws_hint)
Set the Local-Workgroup-Size hint.
cl::NDRange lws_hint () const
Return the Local-Workgroup-Size hint.
const std::string & config_id () const
Get the configuration ID.
void set_target (GPUTarget target)
Set the targeted GPU architecture.
void set_target (cl::Device &device)
Set the targeted GPU architecture according to the CL device.
GPUTarget get_target () const
Get the targeted GPU architecture.
size_t get_max_workgroup_size ()
Get the maximum workgroup size for the device the CLKernelLibrary uses.
template<typename T , unsigned int dimension_size>
void add_array_argument (unsigned &idx, const ICLArray< T > *array, const Strides &strides, unsigned int num_dimensions, const Window &window)
Add the passed array's parameters to the object's kernel's arguments starting from the index idx.
template<unsigned int dimension_size>
void add_tensor_argument (unsigned &idx, const ICLTensor *tensor, const Window &window)
Public Member Functions inherited from IKernel
IKernel ()
Constructor.
virtual ~IKernel ()=default
Destructor.
virtual bool is_parallelisable () const
Indicates whether or not the kernel is parallelisable.
virtual BorderSize border_size () const
The size of the border for that kernel.
const Window & window () const
The maximum window the kernel can be executed on.
Additional Inherited Members
Static Public Member Functions inherited from ICLKernel
static constexpr unsigned int num_arguments_per_1D_array ()
Returns the number of arguments enqueued per 1D array object.
static constexpr unsigned int num_arguments_per_1D_tensor ()
Returns the number of arguments enqueued per 1D tensor object.
static constexpr unsigned int num_arguments_per_2D_tensor ()
Returns the number of arguments enqueued per 2D tensor object.
static constexpr unsigned int num_arguments_per_3D_tensor ()
Returns the number of arguments enqueued per 3D tensor object.
static constexpr unsigned int num_arguments_per_4D_tensor ()
Returns the number of arguments enqueued per 4D tensor object.
static cl::NDRange gws_from_window (const Window &window)
Get the global work size given an execution window.
Detailed Description
Interface for the channel combine kernel.
Definition at line 39 of file CLChannelCombineKernel.h.
Constructor & Destructor Documentation
CLChannelCombineKernel() [1/3]
CLChannelCombineKernel ()
Default constructor.
Definition at line 49 of file CLChannelCombineKernel.cpp.
     : _planes{ { nullptr } }, _output(nullptr), _output_multi(nullptr), _x_subsampling{ { 1, 1, 1 } }, _y_subsampling{ { 1, 1, 1 } }
 {
 }
CLChannelCombineKernel() [2/3]
CLChannelCombineKernel (const CLChannelCombineKernel &) delete
Prevent instances of this class from being copied (As this class contains pointers)
CLChannelCombineKernel() [3/3]
CLChannelCombineKernel (CLChannelCombineKernel &&) default
Allow instances of this class to be moved.
~CLChannelCombineKernel()
~CLChannelCombineKernel () default
Default destructor.
Member Function Documentation
configure() [1/2]
void configure (const ICLTensor * plane0, const ICLTensor * plane1, const ICLTensor * plane2, const ICLTensor * plane3, ICLTensor * output)
Configure function's inputs and outputs.
Parameters
[in] plane0 The 2D plane that forms channel 0. Must be of U8 format.
[in] plane1 The 2D plane that forms channel 1. Must be of U8 format.
[in] plane2 The 2D plane that forms channel 2. Must be of U8 format.
[in] plane3 The 2D plane that forms channel 3. Must be of U8 format.
[out] output The single planar output tensor.
Definition at line 54 of file CLChannelCombineKernel.cpp.
 {
     ARM_COMPUTE_ERROR_ON_NULLPTR(plane0, plane1, plane2, output);
     ARM_COMPUTE_ERROR_ON_TENSOR_NOT_2D(plane0);
     ARM_COMPUTE_ERROR_ON_TENSOR_NOT_2D(plane1);
     ARM_COMPUTE_ERROR_ON_TENSOR_NOT_2D(plane2);
     ARM_COMPUTE_ERROR_ON_TENSOR_NOT_2D(output);
     ARM_COMPUTE_ERROR_ON_FORMAT_NOT_IN(plane0, Format::U8);
     ARM_COMPUTE_ERROR_ON_FORMAT_NOT_IN(plane1, Format::U8);
     ARM_COMPUTE_ERROR_ON_FORMAT_NOT_IN(plane2, Format::U8);
     ARM_COMPUTE_ERROR_ON_FORMAT_NOT_IN(output, Format::RGB888, Format::RGBA8888, Format::YUYV422, Format::UYVY422);
     ARM_COMPUTE_ERROR_ON_DATA_TYPE_CHANNEL_NOT_IN(plane0, 1, DataType::U8);
     ARM_COMPUTE_ERROR_ON_DATA_TYPE_CHANNEL_NOT_IN(plane1, 1, DataType::U8);
     ARM_COMPUTE_ERROR_ON_DATA_TYPE_CHANNEL_NOT_IN(plane2, 1, DataType::U8);
     const Format output_format = output->info()->format();
     // Check if horizontal dimension of Y plane is even and validate horizontal sub-sampling dimensions for U and V planes
     if(Format::YUYV422 == output_format || Format::UYVY422 == output_format)
     {
         // Validate Y plane of input and output
         ARM_COMPUTE_ERROR_ON_TENSORS_NOT_EVEN(output_format, plane0, output);
         // Validate U and V plane of the input
         ARM_COMPUTE_ERROR_ON_TENSORS_NOT_SUBSAMPLED(output_format, plane0->info()->tensor_shape(), plane1, plane2);
     }
     _planes[0] = plane0;
     _planes[1] = plane1;
     _planes[2] = plane2;
     _planes[3] = nullptr;
     // Validate the last input tensor only for RGBA format
     if(Format::RGBA8888 == output_format)
     {
         ARM_COMPUTE_ERROR_ON_NULLPTR(plane3);
         ARM_COMPUTE_ERROR_ON_TENSOR_NOT_2D(plane3);
         ARM_COMPUTE_ERROR_ON_FORMAT_NOT_IN(plane3, Format::U8);
         ARM_COMPUTE_ERROR_ON_DATA_TYPE_CHANNEL_NOT_IN(plane3, 1, DataType::U8);
         _planes[3] = plane3;
     }
     _output       = output;
     _output_multi = nullptr;
     // Half the processed elements for U and V channels due to horizontal sub-sampling of 2
     if(Format::YUYV422 == output_format || Format::UYVY422 == output_format)
     {
         _x_subsampling[1] = 2;
         _x_subsampling[2] = 2;
     }
     // Create kernel
     std::string kernel_name = "channel_combine_" + string_from_format(output_format);
     _kernel                 = static_cast<cl::Kernel>(CLKernelLibrary::get().create_kernel(kernel_name));
     // Configure window
     Window win = calculate_max_window(*output->info(), Steps(num_elems_processed_per_iteration));
     AccessWindowHorizontal plane0_access(plane0->info(), 0, num_elems_processed_per_iteration);
     AccessWindowRectangle  plane1_access(plane1->info(), 0, 0, num_elems_processed_per_iteration, 1, 1.f / _x_subsampling[1], 1.f / _y_subsampling[1]);
     AccessWindowRectangle  plane2_access(plane2->info(), 0, 0, num_elems_processed_per_iteration, 1, 1.f / _x_subsampling[2], 1.f / _y_subsampling[2]);
     AccessWindowHorizontal plane3_access(plane3 == nullptr ? nullptr : plane3->info(), 0, num_elems_processed_per_iteration);
     AccessWindowHorizontal output_access(output->info(), 0, num_elems_processed_per_iteration);
     update_window_and_padding(win, plane0_access, plane1_access, plane2_access, plane3_access, output_access);
     ValidRegion valid_region = intersect_valid_regions(plane0->info()->valid_region(),
                                                        plane1->info()->valid_region(),
                                                        plane2->info()->valid_region());
     if(plane3 != nullptr)
     {
         valid_region = intersect_valid_regions(plane3->info()->valid_region(), valid_region);
     }
     output_access.set_valid_region(win, ValidRegion(valid_region.anchor, output->info()->tensor_shape()));
     ICLKernel::configure_internal(win);
 }
References ValidRegion::anchor, ARM_COMPUTE_ERROR_ON_DATA_TYPE_CHANNEL_NOT_IN, ARM_COMPUTE_ERROR_ON_FORMAT_NOT_IN, ARM_COMPUTE_ERROR_ON_NULLPTR, ARM_COMPUTE_ERROR_ON_TENSOR_NOT_2D, ARM_COMPUTE_ERROR_ON_TENSORS_NOT_EVEN, ARM_COMPUTE_ERROR_ON_TENSORS_NOT_SUBSAMPLED, arm_compute::calculate_max_window(), arm_compute::create_kernel(), ITensorInfo::format(), CLKernelLibrary::get(), ITensor::info(), arm_compute::intersect_valid_regions(), arm_compute::RGB888, arm_compute::RGBA8888, arm_compute::string_from_format(), ITensorInfo::tensor_shape(), arm_compute::U8, arm_compute::update_window_and_padding(), arm_compute::UYVY422, arm_compute::test::validation::valid_region, ITensorInfo::valid_region(), and arm_compute::YUYV422.
configure() [2/2]
void configure (const ICLImage * plane0, const ICLImage * plane1, const ICLImage * plane2, ICLMultiImage * output)
Configure function's inputs and outputs.
Parameters
[in] plane0 The 2D plane that forms channel 0. Must be of U8 format.
[in] plane1 The 2D plane that forms channel 1. Must be of U8 format.
[in] plane2 The 2D plane that forms channel 2. Must be of U8 format.
[out] output The multi planar output tensor.
Definition at line 137 of file CLChannelCombineKernel.cpp.
 {
     ARM_COMPUTE_ERROR_ON_NULLPTR(plane0, plane1, plane2, output);
     ARM_COMPUTE_ERROR_ON_TENSOR_NOT_2D(plane0);
     ARM_COMPUTE_ERROR_ON_TENSOR_NOT_2D(plane1);
     ARM_COMPUTE_ERROR_ON_TENSOR_NOT_2D(plane2);
     ARM_COMPUTE_ERROR_ON_FORMAT_NOT_IN(plane0, Format::U8);
     ARM_COMPUTE_ERROR_ON_FORMAT_NOT_IN(plane1, Format::U8);
     ARM_COMPUTE_ERROR_ON_FORMAT_NOT_IN(plane2, Format::U8);
     ARM_COMPUTE_ERROR_ON_FORMAT_NOT_IN(output, Format::NV12, Format::NV21, Format::IYUV, Format::YUV444);
     ARM_COMPUTE_ERROR_ON_DATA_TYPE_CHANNEL_NOT_IN(plane0, 1, DataType::U8);
     ARM_COMPUTE_ERROR_ON_DATA_TYPE_CHANNEL_NOT_IN(plane1, 1, DataType::U8);
     ARM_COMPUTE_ERROR_ON_DATA_TYPE_CHANNEL_NOT_IN(plane2, 1, DataType::U8);
     const Format output_format = output->info()->format();
     // Validate shape of Y plane to be even and shape of sub-sampling dimensions for U and V planes
     // Perform validation only for formats which require sub-sampling.
     if(Format::YUV444 != output_format)
     {
         // Validate Y plane of input and output
         ARM_COMPUTE_ERROR_ON_TENSORS_NOT_EVEN(output_format, plane0, output->plane(0));
         // Validate U and V plane of the input
         ARM_COMPUTE_ERROR_ON_TENSORS_NOT_SUBSAMPLED(output_format, plane0->info()->tensor_shape(), plane1, plane2);
         // Validate second plane U (NV12 and NV21 have a UV88 combined plane while IYUV has only the U plane)
         // MultiImage generates the correct tensor shape but also check in case the tensor shape of planes was changed to a wrong size
         ARM_COMPUTE_ERROR_ON_TENSORS_NOT_SUBSAMPLED(output_format, plane0->info()->tensor_shape(), output->plane(1));
         // Validate the last plane V of format IYUV
         if(Format::IYUV == output_format)
         {
             // Validate Y plane of the output
             ARM_COMPUTE_ERROR_ON_TENSORS_NOT_SUBSAMPLED(output_format, plane0->info()->tensor_shape(), output->plane(2));
         }
     }
     // Set input tensors
     _planes[0] = plane0;
     _planes[1] = plane1;
     _planes[2] = plane2;
     _planes[3] = nullptr;
     // Set output tensor
     _output       = nullptr;
     _output_multi = output;
     bool has_two_planars = false;
     // Set sub-sampling parameters for each plane
     std::string           kernel_name;
     std::set<std::string> build_opts;
     if(Format::NV12 == output_format || Format::NV21 == output_format)
     {
         _x_subsampling = { { 1, 2, 2 } };
         _y_subsampling = { { 1, 2, 2 } };
         kernel_name    = "channel_combine_NV";
         build_opts.emplace(Format::NV12 == output_format ? "-DNV12" : "-DNV21");
         has_two_planars = true;
     }
     else
     {
         if(Format::IYUV == output_format)
         {
             _x_subsampling = { { 1, 2, 2 } };
             _y_subsampling = { { 1, 2, 2 } };
         }
         kernel_name = "copy_planes_3p";
         build_opts.emplace(Format::IYUV == output_format ? "-DIYUV" : "-DYUV444");
     }
     // Create kernel
     _kernel = static_cast<cl::Kernel>(CLKernelLibrary::get().create_kernel(kernel_name, build_opts));
     // Configure window
     Window win = calculate_max_window(*plane0->info(), Steps(num_elems_processed_per_iteration));
     AccessWindowRectangle input_plane0_access(plane0->info(), 0, 0, num_elems_processed_per_iteration, 1.f);
     AccessWindowRectangle input_plane1_access(plane1->info(), 0, 0, num_elems_processed_per_iteration, 1.f, 1.f / _x_subsampling[1], 1.f / _y_subsampling[1]);
     AccessWindowRectangle input_plane2_access(plane2->info(), 0, 0, num_elems_processed_per_iteration, 1.f, 1.f / _x_subsampling[2], 1.f / _y_subsampling[2]);
     AccessWindowRectangle output_plane0_access(output->plane(0)->info(), 0, 0, num_elems_processed_per_iteration, 1.f, 1.f, 1.f / _y_subsampling[1]);
     AccessWindowRectangle output_plane1_access(output->plane(1)->info(), 0, 0, num_elems_processed_per_iteration, 1.f, 1.f / _x_subsampling[1], 1.f / _y_subsampling[1]);
     AccessWindowRectangle output_plane2_access(has_two_planars ? nullptr : output->plane(2)->info(), 0, 0, num_elems_processed_per_iteration, 1.f, 1.f / _x_subsampling[2], 1.f / _y_subsampling[2]);
     update_window_and_padding(win,
                               input_plane0_access, input_plane1_access, input_plane2_access,
                               output_plane0_access, output_plane1_access, output_plane2_access);
     ValidRegion plane0_valid_region  = plane0->info()->valid_region();
     ValidRegion output_plane1_region = has_two_planars ? intersect_valid_regions(plane1->info()->valid_region(), plane2->info()->valid_region()) : plane2->info()->valid_region();
     output_plane0_access.set_valid_region(win, ValidRegion(plane0_valid_region.anchor, output->plane(0)->info()->tensor_shape()));
     output_plane1_access.set_valid_region(win, ValidRegion(output_plane1_region.anchor, output->plane(1)->info()->tensor_shape()));
     output_plane2_access.set_valid_region(win, ValidRegion(plane2->info()->valid_region().anchor, output->plane(2)->info()->tensor_shape()));
     ICLKernel::configure_internal(win);
 }
References ValidRegion::anchor, ARM_COMPUTE_ERROR_ON_DATA_TYPE_CHANNEL_NOT_IN, ARM_COMPUTE_ERROR_ON_FORMAT_NOT_IN, ARM_COMPUTE_ERROR_ON_NULLPTR, ARM_COMPUTE_ERROR_ON_TENSOR_NOT_2D, ARM_COMPUTE_ERROR_ON_TENSORS_NOT_EVEN, ARM_COMPUTE_ERROR_ON_TENSORS_NOT_SUBSAMPLED, arm_compute::calculate_max_window(), arm_compute::create_kernel(), MultiImageInfo::format(), CLKernelLibrary::get(), IMultiImage::info(), ITensor::info(), arm_compute::intersect_valid_regions(), arm_compute::IYUV, arm_compute::NV12, arm_compute::NV21, ICLMultiImage::plane(), ITensorInfo::tensor_shape(), arm_compute::U8, arm_compute::update_window_and_padding(), ITensorInfo::valid_region(), and arm_compute::YUV444.
operator=() [1/2]
CLChannelCombineKernel& operator= (const CLChannelCombineKernel &) delete
Prevent instances of this class from being copied (As this class contains pointers)
operator=() [2/2]
CLChannelCombineKernel& operator= (CLChannelCombineKernel &&) default
Allow instances of this class to be moved.
run()
void run (const Window & window, cl::CommandQueue & queue) override virtual
Enqueue the OpenCL kernel to process the given window on the passed OpenCL command queue.
Note
The queue is not flushed by this method, and therefore the kernel will not have been executed by the time this method returns.
Parameters
[in] window Region on which to execute the kernel. (Must be a valid region of the window returned by window()).
[in,out] queue Command queue on which to enqueue the kernel.
Implements ICLKernel.
Definition at line 239 of file CLChannelCombineKernel.cpp.
 {
     ARM_COMPUTE_ERROR_ON_UNCONFIGURED_KERNEL(this);
     ARM_COMPUTE_ERROR_ON_INVALID_SUBWINDOW(ICLKernel::window(), window);
     Window slice = window.first_slice_window_2D();
     slice.set_dimension_step(Window::DimY, 1);
     do
     {
         // Subsampling in plane 1
         Window win_sub_plane1(slice);
         win_sub_plane1.set(Window::DimX, Window::Dimension(win_sub_plane1.x().start() / _x_subsampling[1], win_sub_plane1.x().end() / _x_subsampling[1], win_sub_plane1.x().step() / _x_subsampling[1]));
         win_sub_plane1.set(Window::DimY, Window::Dimension(win_sub_plane1.y().start() / _y_subsampling[1], win_sub_plane1.y().end() / _y_subsampling[1], 1));
         // Subsampling in plane 2
         Window win_sub_plane2(slice);
         win_sub_plane2.set(Window::DimX, Window::Dimension(win_sub_plane2.x().start() / _x_subsampling[2], win_sub_plane2.x().end() / _x_subsampling[2], win_sub_plane2.x().step() / _x_subsampling[2]));
         win_sub_plane2.set(Window::DimY, Window::Dimension(win_sub_plane2.y().start() / _y_subsampling[2], win_sub_plane2.y().end() / _y_subsampling[2], 1));
         unsigned int idx = 0;
         // Set inputs
         add_2D_tensor_argument(idx, _planes[0], slice);
         add_2D_tensor_argument(idx, _planes[1], win_sub_plane1);
         add_2D_tensor_argument(idx, _planes[2], win_sub_plane2);
         add_2D_tensor_argument_if((nullptr != _planes[3]), idx, _planes[3], slice);
         // Set outputs
         if(nullptr != _output) // Single planar output
         {
             add_2D_tensor_argument(idx, _output, slice);
         }
         else // Multi-planar output
         {
             // Reduce slice in case of subsampling to avoid out-of bounds access
             slice.set(Window::DimY, Window::Dimension(slice.y().start() / _y_subsampling[1], slice.y().end() / _y_subsampling[1], 1));
             add_2D_tensor_argument(idx, _output_multi->cl_plane(0), slice);
             add_2D_tensor_argument(idx, _output_multi->cl_plane(1), win_sub_plane1);
             add_2D_tensor_argument_if((3 == num_planes_from_format(_output_multi->info()->format())), idx, _output_multi->cl_plane(2), win_sub_plane2);
             _kernel.setArg(idx++, slice.y().end());
         }
         enqueue(queue, *this, slice);
     }
     while(window.slide_window_slice_2D(slice));
 }
References ICLKernel::add_2D_tensor_argument(), ICLKernel::add_2D_tensor_argument_if(), ARM_COMPUTE_ERROR_ON_INVALID_SUBWINDOW, ARM_COMPUTE_ERROR_ON_UNCONFIGURED_KERNEL, ICLMultiImage::cl_plane(), Window::DimX, Window::DimY, Window::Dimension::end(), arm_compute::enqueue(), Window::first_slice_window_2D(), MultiImageInfo::format(), IMultiImage::info(), arm_compute::num_planes_from_format(), Window::set(), arm_compute::test::validation::reference::slice(), Window::slide_window_slice_2D(), Window::Dimension::start(), Window::Dimension::step(), IKernel::window(), Window::x(), and Window::y().
The documentation for this class was generated from the following files:
arm_compute/core/CL/kernels/CLChannelCombineKernel.h
src/core/CL/kernels/CLChannelCombineKernel.cpp