Compute Library: CLGEMMLowpOffsetContributionKernel Class Reference
CLGEMMLowpOffsetContributionKernel Class Reference
OpenCL kernel used to add the offset contribution after CLGEMMLowpMatrixMultiplyKernel.
#include <CLGEMMLowpOffsetContributionKernel.h>
Public Member Functions
CLGEMMLowpOffsetContributionKernel ()
Constructor.
CLGEMMLowpOffsetContributionKernel (const CLGEMMLowpOffsetContributionKernel &)=delete
Prevent instances of this class from being copied (As this class contains pointers)
CLGEMMLowpOffsetContributionKernel & operator= (const CLGEMMLowpOffsetContributionKernel &)=delete
Prevent instances of this class from being copied (As this class contains pointers)
CLGEMMLowpOffsetContributionKernel (CLGEMMLowpOffsetContributionKernel &&)=default
Allow instances of this class to be moved.
CLGEMMLowpOffsetContributionKernel & operator= (CLGEMMLowpOffsetContributionKernel &&)=default
Allow instances of this class to be moved.
void configure (ICLTensor *mm_result, const ICLTensor *vector_sum_col, const ICLTensor *vector_sum_row, const ICLTensor *bias, int32_t k, int32_t a_offset, int32_t b_offset)
Initialise the kernel's input and output.
void run (const Window &window, cl::CommandQueue &queue) override
Enqueue the OpenCL kernel to process the given window on the passed OpenCL command queue.
Public Member Functions inherited from ICLKernel
ICLKernel ()
Constructor.
cl::Kernel & kernel ()
Returns a reference to the OpenCL kernel of this object.
template<typename T >
void add_1D_array_argument (unsigned int &idx, const ICLArray< T > *array, const Strides &strides, unsigned int num_dimensions, const Window &window)
Add the passed 1D array's parameters to the object's kernel's arguments starting from the index idx.
void add_1D_tensor_argument (unsigned int &idx, const ICLTensor *tensor, const Window &window)
Add the passed 1D tensor's parameters to the object's kernel's arguments starting from the index idx.
void add_2D_tensor_argument (unsigned int &idx, const ICLTensor *tensor, const Window &window)
Add the passed 2D tensor's parameters to the object's kernel's arguments starting from the index idx.
void add_3D_tensor_argument (unsigned int &idx, const ICLTensor *tensor, const Window &window)
Add the passed 3D tensor's parameters to the object's kernel's arguments starting from the index idx.
void add_4D_tensor_argument (unsigned int &idx, const ICLTensor *tensor, const Window &window)
Add the passed 4D tensor's parameters to the object's kernel's arguments starting from the index idx.
template<typename T >
void add_argument (unsigned int &idx, T value)
Add the passed parameters to the object's kernel's arguments starting from the index idx.
void set_lws_hint (const cl::NDRange &lws_hint)
Set the Local-Workgroup-Size hint.
cl::NDRange lws_hint () const
Return the Local-Workgroup-Size hint.
const std::string & config_id () const
Get the configuration ID.
void set_target (GPUTarget target)
Set the targeted GPU architecture.
void set_target (cl::Device &device)
Set the targeted GPU architecture according to the CL device.
GPUTarget get_target () const
Get the targeted GPU architecture.
size_t get_max_workgroup_size ()
Get the maximum workgroup size for the device the CLKernelLibrary uses.
template<typename T , unsigned int dimension_size>
void add_array_argument (unsigned &idx, const ICLArray< T > *array, const Strides &strides, unsigned int num_dimensions, const Window &window)
Add the passed array's parameters to the object's kernel's arguments starting from the index idx.
template<unsigned int dimension_size>
void add_tensor_argument (unsigned &idx, const ICLTensor *tensor, const Window &window)
Public Member Functions inherited from IKernel
IKernel ()
Constructor.
virtual ~IKernel ()=default
Destructor.
virtual bool is_parallelisable () const
Indicates whether or not the kernel is parallelisable.
virtual BorderSize border_size () const
The size of the border for that kernel.
const Window & window () const
The maximum window the kernel can be executed on.
Static Public Member Functions
static Status validate (const ITensorInfo *mm_result, const ITensorInfo *vector_sum_col, const ITensorInfo *vector_sum_row, const ITensorInfo *bias, int32_t a_offset, int32_t b_offset)
Static function to check if given info will lead to a valid configuration of CLGEMMLowpOffsetContributionKernel.
Static Public Member Functions inherited from ICLKernel
static constexpr unsigned int num_arguments_per_1D_array ()
Returns the number of arguments enqueued per 1D array object.
static constexpr unsigned int num_arguments_per_1D_tensor ()
Returns the number of arguments enqueued per 1D tensor object.
static constexpr unsigned int num_arguments_per_2D_tensor ()
Returns the number of arguments enqueued per 2D tensor object.
static constexpr unsigned int num_arguments_per_3D_tensor ()
Returns the number of arguments enqueued per 3D tensor object.
static constexpr unsigned int num_arguments_per_4D_tensor ()
Returns the number of arguments enqueued per 4D tensor object.
static cl::NDRange gws_from_window (const Window &window)
Get the global work size given an execution window.
Detailed Description
OpenCL kernel used to add the offset contribution after CLGEMMLowpMatrixMultiplyKernel.
The computation is performed in-place
This kernel takes a final int32 accumulator value (the output of CLGEMMLowpMatrixMultiplyKernel), and adds to it the offset contribution of matrix A and matrix B in-place.
The final result is:
mm_result[i][k] = mm_result[i][k] + (vector_sum_col[k] * a_offset) + (vector_sum_row[i] * b_offset) + (a_offset * b_offset * k)
Definition at line 46 of file CLGEMMLowpOffsetContributionKernel.h.
Constructor & Destructor Documentation
CLGEMMLowpOffsetContributionKernel() [1/3]
CLGEMMLowpOffsetContributionKernel ()
Constructor.
Definition at line 140 of file CLGEMMLowpOffsetContributionKernel.cpp.
     : _vector_sum_col(nullptr), _vector_sum_row(nullptr), _mm_result(nullptr), _bias(nullptr)
 {
 }
CLGEMMLowpOffsetContributionKernel() [2/3]
CLGEMMLowpOffsetContributionKernel (const CLGEMMLowpOffsetContributionKernel &) delete
Prevent instances of this class from being copied (As this class contains pointers)
CLGEMMLowpOffsetContributionKernel() [3/3]
CLGEMMLowpOffsetContributionKernel (CLGEMMLowpOffsetContributionKernel &&) default
Allow instances of this class to be moved.
Member Function Documentation
configure()
void configure (ICLTensor * mm_result, const ICLTensor * vector_sum_col, const ICLTensor * vector_sum_row, const ICLTensor * bias, int32_t k, int32_t a_offset, int32_t b_offset)
Initialise the kernel's input and output.
Parameters
[in,out] mm_result Input tensor containing the result of CLGEMMLowpMatrixMultiplyKernel. Data type supported: S32
[in] vector_sum_col Input row-vector of sums of all the entries in each column of matrix B. Note: vector_sum_col can be a nullptr in case a_offset = 0. Data type supported: same as mm_result
[in] vector_sum_row Input row-vector of sums of all the entries in each row of matrix A. Note: vector_sum_row can be a nullptr in case b_offset = 0. Data type supported: same as mm_result
[in] bias Biases tensor. Only shared biases supported and it can be a nullptr if the addition of biases is not required. Biases are 1D tensor with dimensions [OFM]. Data type supported: Same as input.
[in] k Number of matrix A columns or Matrix B rows
[in] a_offset Offset to be added to each element of the matrix A.
[in] b_offset Offset to be added to each element of the matrix B.
Definition at line 145 of file CLGEMMLowpOffsetContributionKernel.cpp.
 {
     // Perform validate step
     ARM_COMPUTE_ERROR_ON_NULLPTR(mm_result);
     ARM_COMPUTE_ERROR_THROW_ON(validate_arguments(mm_result->info(),
                                                   vector_sum_col != nullptr ? vector_sum_col->info() : nullptr,
                                                   vector_sum_row != nullptr ? vector_sum_row->info() : nullptr,
                                                   bias != nullptr ? bias->info() : nullptr,
                                                   a_offset, b_offset)); // NOLINT
     _vector_sum_col = vector_sum_col;
     _vector_sum_row = vector_sum_row;
     _mm_result      = mm_result;
     _bias           = bias;
     // Check if input is a 3D reinterpretation
     const bool reinterpret_as_3d = vector_sum_row != nullptr
                                    && mm_result->info()->num_dimensions() > 1
                                    && mm_result->info()->tensor_shape().y() != vector_sum_row->info()->tensor_shape().x();
     // Set the arguments to pass at compile time
     CLBuildOptions build_opts;
     // If a_offset == 0, vector_sum_col can be a nullptr
     if(a_offset != 0)
     {
         build_opts.add_option("-DA_OFFSET=" + support::cpp11::to_string(a_offset));
         build_opts.add_option_if(vector_sum_col->info()->tensor_shape().num_dimensions() > 1, "-DSUM_COL_HAS_BATCHES");
     }
     // If b_offset == 0, vector_sum_row can be a nullptr
     build_opts.add_option_if(b_offset != 0, "-DB_OFFSET=" + support::cpp11::to_string(b_offset));
     build_opts.add_option("-DK_OFFSET=" + support::cpp11::to_string(a_offset * b_offset * k));
     build_opts.add_option_if(reinterpret_as_3d, "-DHEIGHT_INPUT3D=" + support::cpp11::to_string(mm_result->info()->dimension(1)));
     build_opts.add_option_if(reinterpret_as_3d, "-DDEPTH_INPUT3D=" + support::cpp11::to_string(mm_result->info()->dimension(2)));
     build_opts.add_option_if(bias != nullptr, "-DADD_BIAS");
     std::string kernel_name("gemmlowp_offset_contribution");
     // Create kernel
     _kernel = static_cast<cl::Kernel>(CLKernelLibrary::get().create_kernel(kernel_name, build_opts.options()));
     // Configure kernel window
     auto win_config = validate_and_configure_window(mm_result->info(),
                                                     vector_sum_col != nullptr ? vector_sum_col->info() : nullptr,
                                                     vector_sum_row != nullptr ? vector_sum_row->info() : nullptr,
                                                     bias != nullptr ? bias->info() : nullptr,
                                                     a_offset, b_offset); // NOLINT
     ARM_COMPUTE_ERROR_THROW_ON(win_config.first);
     ICLKernel::configure_internal(win_config.second);
     // Set config_id for enabling LWS tuning
     _config_id = kernel_name + "_";
     _config_id += support::cpp11::to_string(mm_result->info()->dimension(0));
     _config_id += "_";
     _config_id += support::cpp11::to_string(mm_result->info()->dimension(1));
     _config_id += "_";
     _config_id += support::cpp11::to_string(mm_result->info()->dimension(2));
 }
References CLBuildOptions::add_option(), CLBuildOptions::add_option_if(), ARM_COMPUTE_ERROR_ON_NULLPTR, ARM_COMPUTE_ERROR_THROW_ON, arm_compute::test::validation::bias, arm_compute::create_kernel(), ITensorInfo::dimension(), CLKernelLibrary::get(), ITensor::info(), CLTensor::info(), Dimensions< T >::num_dimensions(), ITensorInfo::num_dimensions(), CLBuildOptions::options(), ITensorInfo::tensor_shape(), arm_compute::support::cpp11::to_string(), Dimensions< T >::x(), and Dimensions< T >::y().
Referenced by CLGEMMLowpMatrixMultiplyCore::configure().
operator=() [1/2]
CLGEMMLowpOffsetContributionKernel& operator= (const CLGEMMLowpOffsetContributionKernel &) delete
Prevent instances of this class from being copied (As this class contains pointers)
operator=() [2/2]
CLGEMMLowpOffsetContributionKernel& operator= (CLGEMMLowpOffsetContributionKernel &&) default
Allow instances of this class to be moved.
run()
void run (const Window & window, cl::CommandQueue & queue) override virtual
Enqueue the OpenCL kernel to process the given window on the passed OpenCL command queue.
Note
The queue is not flushed by this method, and therefore the kernel will not have been executed by the time this method returns.
Parameters
[in] window Region on which to execute the kernel. (Must be a valid region of the window returned by window()).
[in,out] queue Command queue on which to enqueue the kernel.
Implements ICLKernel.
Definition at line 219 of file CLGEMMLowpOffsetContributionKernel.cpp.
 {
     ARM_COMPUTE_ERROR_ON_UNCONFIGURED_KERNEL(this);
     ARM_COMPUTE_ERROR_ON_INVALID_SUBWINDOW(ICLKernel::window(), window);
     Window collapsed = window.collapse_if_possible(ICLKernel::window(), Window::DimZ);
     Window slice     = collapsed.first_slice_window_3D();
     // Set window for vector_sum_col
     Window win_vector_sum_col = slice;
     win_vector_sum_col.set(Window::DimY, Window::Dimension(0, 0, 0));
     win_vector_sum_col.set(Window::DimZ, Window::Dimension(0, 0, 0));
     // Set window for vector_sum_row
     Window win_vector_sum_row = slice;
     win_vector_sum_row.set(Window::DimX, Window::Dimension(0, 0, 0));
     win_vector_sum_row.set(Window::DimY, Window::Dimension(0, 0, 0));
     win_vector_sum_col.set(Window::DimZ, Window::Dimension(0, 0, 0));
     Window biases_slice = slice;
     biases_slice.set(Window::DimY, Window::Dimension(0, 1, 1));
     biases_slice.set(Window::DimZ, Window::Dimension(0, 1, 1));
     do
     {
         unsigned int idx = 0;
         add_3D_tensor_argument(idx, _mm_result, slice);
         if(_vector_sum_col != nullptr)
         {
             add_2D_tensor_argument(idx, _vector_sum_col, win_vector_sum_col);
         }
         if(_vector_sum_row != nullptr)
         {
             add_2D_tensor_argument(idx, _vector_sum_row, win_vector_sum_row);
         }
         if(_bias != nullptr)
         {
             add_1D_tensor_argument(idx, _bias, biases_slice);
         }
         enqueue(queue, *this, slice, lws_hint());
     }
     while(collapsed.slide_window_slice_3D(slice));
 }
References ICLKernel::add_1D_tensor_argument(), ICLKernel::add_2D_tensor_argument(), ICLKernel::add_3D_tensor_argument(), ARM_COMPUTE_ERROR_ON_INVALID_SUBWINDOW, ARM_COMPUTE_ERROR_ON_UNCONFIGURED_KERNEL, Window::collapse_if_possible(), Window::DimX, Window::DimY, Window::DimZ, arm_compute::enqueue(), Window::first_slice_window_3D(), ICLKernel::lws_hint(), Window::set(), arm_compute::test::validation::reference::slice(), Window::slide_window_slice_3D(), and IKernel::window().
validate()
Status validate (const ITensorInfo * mm_result, const ITensorInfo * vector_sum_col, const ITensorInfo * vector_sum_row, const ITensorInfo * bias, int32_t a_offset, int32_t b_offset) static
Static function to check if given info will lead to a valid configuration of CLGEMMLowpOffsetContributionKernel.
Parameters
[in] mm_result Input tensor containing the result of CLGEMMLowpOffsetContributionKernel. Data type supported: S32
[in] vector_sum_col Input row-vector of sums of all the entries in each column of matrix B. Note: vector_sum_col can be a nullptr in case a_offset = 0. Data type supported: same as mm_result
[in] vector_sum_row Input row-vector of sums of all the entries in each row of matrix A. Note: vector_sum_row can be a nullptr in case b_offset = 0. Data type supported: same as mm_result
[in] bias Biases tensor. Only shared biases supported and it can be a nullptr if the addition of biases is not required. Biases are 1D tensor with dimensions [OFM]. Data type supported: Same as input.
[in] a_offset Offset to be added to each element of the matrix A.
[in] b_offset Offset to be added to each element of the matrix B.
Returns
a status
Definition at line 205 of file CLGEMMLowpOffsetContributionKernel.cpp.
 {
     ARM_COMPUTE_RETURN_ON_ERROR(validate_arguments(mm_result, vector_sum_col, vector_sum_row, bias, a_offset, b_offset));
     ARM_COMPUTE_RETURN_ON_ERROR(validate_and_configure_window(mm_result->clone().get(),
                                                               vector_sum_col != nullptr ? vector_sum_col->clone().get() : nullptr,
                                                               vector_sum_row != nullptr ? vector_sum_row->clone().get() : nullptr,
                                                               bias != nullptr ? bias->clone().get() : nullptr,
                                                               a_offset, b_offset)
                                 .first); // NOLINT
     return Status{};
 }
References ARM_COMPUTE_RETURN_ON_ERROR, arm_compute::test::validation::bias, and ICloneable< T >::clone().
Referenced by CLGEMMLowpMatrixMultiplyCore::validate().
The documentation for this class was generated from the following files:
arm_compute/core/CL/kernels/CLGEMMLowpOffsetContributionKernel.h
src/core/CL/kernels/CLGEMMLowpOffsetContributionKernel.cpp