Compute Library: IMultiImage Class Reference
IMultiImage Class Reference abstract
Interface for multi-planar images.
#include <IMultiImage.h>
Public Member Functions
virtual ~IMultiImage ()=default
Destructor.
virtual const MultiImageInfo * info () const =0
Interface to be implemented by the child class to return the multi-planar image's metadata.
virtual IImage * plane (unsigned int index)=0
Return a pointer to the requested plane of the image.
virtual const IImage * plane (unsigned int index) const =0
Return a constant pointer to the requested plane of the image.
Detailed Description
Interface for multi-planar images.
Definition at line 34 of file IMultiImage.h.
Constructor & Destructor Documentation
~IMultiImage()
virtual ~IMultiImage () virtual default
Destructor.
Member Function Documentation
info()
virtual const MultiImageInfo* info () const pure virtual
Interface to be implemented by the child class to return the multi-planar image's metadata.
Returns
A pointer to the image's metadata.
Implemented in MultiImage, and CLMultiImage.
Referenced by CLChannelExtractKernel::configure(), CLColorConvertKernel::configure(), NEColorConvertKernel::configure(), CLChannelCombineKernel::configure(), NEChannelExtractKernel::configure(), NEChannelCombineKernel::configure(), CLChannelCombineKernel::run(), and CLColorConvertKernel::run().
plane() [1/2]
virtual IImage* plane (unsigned int index) pure virtual
Return a pointer to the requested plane of the image.
Parameters
[in] index The index of the wanted planed.
Returns
A pointer pointed to the plane
Implemented in MultiImage, and ICLMultiImage.
Referenced by NEColorConvertKernel::configure(), NEChannelExtractKernel::configure(), and NEChannelCombineKernel::configure().
plane() [2/2]
virtual const IImage* plane (unsigned int index) const pure virtual
Return a constant pointer to the requested plane of the image.
Parameters
[in] index The index of the wanted planed.
Returns
A constant pointer pointed to the plane
Implemented in MultiImage, and ICLMultiImage.
The documentation for this class was generated from the following file:
arm_compute/core/IMultiImage.h