Compute Library: NEUpsampleLayer Class Reference
NEUpsampleLayer Class Reference
Function to run upsample layer.
#include <NEUpsampleLayer.h>
Public Member Functions
NEUpsampleLayer ()
Constructor.
void configure (const ITensor *input, ITensor *output, const Size2D &info, const InterpolationPolicy &policy)
Set the input output tensors.
void run () override
Run the kernels contained in the function.
Public Member Functions inherited from IFunction
virtual ~IFunction ()=default
Destructor.
virtual void prepare ()
Prepare the function for executing.
Static Public Member Functions
static Status validate (const ITensorInfo *input, const ITensorInfo *output, const Size2D &info, const InterpolationPolicy &policy)
Static function to check if given info will lead to a valid configuration of NEUpsampleLayer.
Detailed Description
Function to run upsample layer.
Definition at line 38 of file NEUpsampleLayer.h.
Constructor & Destructor Documentation
NEUpsampleLayer()
NEUpsampleLayer ()
Constructor.
Definition at line 30 of file NEUpsampleLayer.cpp.
     : _kernel(), _data_layout()
 {
 }
Member Function Documentation
configure()
void configure (const ITensor * input, ITensor * output, const Size2D & info, const InterpolationPolicy & policy)
Set the input output tensors.
Parameters
[in] input Source tensor. Data types supported: QASYMM8/F16/F32.
[out] output Destination tensor. Data types supported: same as input.
[in] info Contains stride information described in Size2D.
[in] policy Defines the policy to fill the intermediate pixels.
Definition at line 41 of file NEUpsampleLayer.cpp.
 {
     _data_layout = input->info()->data_layout();
     _kernel.configure(input, output, info, policy);
 }
References NEUpsampleLayerKernel::configure(), ITensorInfo::data_layout(), ITensor::info(), arm_compute::test::validation::info, and arm_compute::test::validation::policy.
Referenced by arm_compute::test::validation::DATA_TEST_CASE().
run()
void run () override virtual
Run the kernels contained in the function.
For NEON kernels:
Multi-threading is used for the kernels which are parallelisable.
By default std::thread::hardware_concurrency() threads are used.
Note
CPPScheduler::set_num_threads() can be used to manually set the number of threads
For OpenCL kernels:
All the kernels are enqueued on the queue associated with CLScheduler.
The queue is then flushed.
Note
The function will not block until the kernels are executed. It is the user's responsibility to wait.
Will call prepare() on first run if hasn't been done
Implements IFunction.
Definition at line 47 of file NEUpsampleLayer.cpp.
 {
     const auto win = (_data_layout == DataLayout::NCHW) ? Window::DimZ : Window::DimX;
     NEScheduler::get().schedule(&_kernel, win);
 }
References Window::DimX, Window::DimZ, Scheduler::get(), arm_compute::NCHW, and IScheduler::schedule().
validate()
Status validate (const ITensorInfo * input, const ITensorInfo * output, const Size2D & info, const InterpolationPolicy & policy) static
Static function to check if given info will lead to a valid configuration of NEUpsampleLayer.
Parameters
[in] input Source tensor info. Data types supported: QASYMM8/F16/F32.
[out] output Destination tensor info. Data types supported: same as input.
[in] info Contains stride information described in Size2D.
[in] policy Defines the policy to fill the intermediate pixels.
Returns
a status
Definition at line 35 of file NEUpsampleLayer.cpp.
 {
     return NEUpsampleLayerKernel::validate(input, output, info, policy);
 }
References arm_compute::test::validation::info, arm_compute::test::validation::policy, and NEUpsampleLayerKernel::validate().
The documentation for this class was generated from the following files:
arm_compute/runtime/NEON/functions/NEUpsampleLayer.h
src/runtime/NEON/functions/NEUpsampleLayer.cpp