Compute Library: BatchNormalizationLayer Class Reference
BatchNormalizationLayer Class Reference final
Batchnormalization Layer.
#include <Layers.h>
Public Member Functions
BatchNormalizationLayer (ITensorAccessorUPtr mean, ITensorAccessorUPtr var, ITensorAccessorUPtr gamma=nullptr, ITensorAccessorUPtr beta=nullptr, float epsilon=0.001f)
Construct a batch normalization layer.
NodeID create_layer (IStream &s) override
Create layer and add to the given stream.
Public Member Functions inherited from ILayer
virtual ~ILayer ()=default
Default destructor.
ILayer & set_name (std::string name)
Sets the name of the layer.
const std::string & name () const
Layer name accessor.
Detailed Description
Batchnormalization Layer.
Definition at line 118 of file Layers.h.
Constructor & Destructor Documentation
BatchNormalizationLayer()
BatchNormalizationLayer (ITensorAccessorUPtr mean, ITensorAccessorUPtr var, ITensorAccessorUPtr gamma = nullptr, ITensorAccessorUPtr beta = nullptr, float epsilon = 0.001f) inline
Construct a batch normalization layer.
Parameters
[in] mean Accessor to get mean tensor data from.
[in] var Accessor to get var tensor data from.
[in] gamma (Optional) Accessor to get gamma tensor data from. Default: nullptr.
[in] beta (Optional) Accessor to get beta tensor data from. Default: nullptr.
[in] epsilon (Optional) Epsilon value. Default: 0.001.
Definition at line 129 of file Layers.h.
         : _mean(std::move(mean)), _var(std::move(var)), _gamma(std::move(gamma)), _beta(std::move(beta)), _epsilon(epsilon)
     {
     }
Member Function Documentation
create_layer()
NodeID create_layer (IStream & s) inline override virtual
Create layer and add to the given stream.
Parameters
[in] s Stream to add layer to.
Returns
ID of the created node.
Implements ILayer.
Definition at line 138 of file Layers.h.
     {
         ARM_COMPUTE_ERROR_ON(_mean == nullptr);
         ARM_COMPUTE_ERROR_ON(_var == nullptr);
         NodeParams  common_params = { name(), s.hints().target_hint };
         NodeIdxPair input         = { s.tail_node(), 0 };
         return GraphBuilder::add_batch_normalization_node(s.graph(), common_params, input, _epsilon,
                                                           std::move(_mean), std::move(_var), std::move(_beta), std::move(_gamma));
     }
References GraphBuilder::add_batch_normalization_node(), ARM_COMPUTE_ERROR_ON, IStream::graph(), IStream::hints(), ILayer::name(), IStream::tail_node(), and StreamHints::target_hint.
The documentation for this class was generated from the following file:
arm_compute/graph/frontend/Layers.h