Compute Library: PaddingCalculator Class Reference
PaddingCalculator Class Reference final
Calculate required padding.
#include <PaddingCalculator.h>
Public Types
enum Option { EXCLUDE_BORDER, INCLUDE_BORDER }
Options for computing the padding.
Public Member Functions
PaddingCalculator (int size, int processed_elements)
Construct calculator with size of tensor's dimension and step size.
void set_border_mode (BorderMode mode)
Set border mode.
void set_border_size (int size)
Set border size.
void set_access_offset (int offset)
Set offset of the access relative to the current position.
void set_processed_elements (int elements)
Set number of processed elements.
void set_accessed_elements (int elements)
Set number of accessed elements.
PaddingSize required_padding () const
Compute the required padding.
PaddingSize required_padding (Option option) const
Compute the required padding.
Detailed Description
Calculate required padding.
Definition at line 36 of file PaddingCalculator.h.
Member Enumeration Documentation
enum Option strong
Options for computing the padding.
Enumerator
EXCLUDE_BORDER
INCLUDE_BORDER
Definition at line 40 of file PaddingCalculator.h.
     {
         EXCLUDE_BORDER,
         INCLUDE_BORDER
     };
Constructor & Destructor Documentation
PaddingCalculator (int size, int processed_elements) inline
Construct calculator with size of tensor's dimension and step size.
Parameters
[in] size Number of elements available.
[in] processed_elements Number of elements processed per iteration.
Definition at line 51 of file PaddingCalculator.h.
References offset(), PaddingCalculator::required_padding(), PaddingCalculator::set_access_offset(), PaddingCalculator::set_accessed_elements(), PaddingCalculator::set_border_mode(), PaddingCalculator::set_border_size(), PaddingCalculator::set_processed_elements(), size, and arm_compute::UNDEFINED.
         : _size{ size }, _num_processed_elements{ processed_elements }, _num_accessed_elements{ processed_elements }
     {
     }
Member Function Documentation
PaddingSize required_padding () const inline
Compute the required padding.
If access offset is negative and border mode is not undefined, the top, bottom and left padding is set to boder size. Otherwise it is zero. The right padding is always computed based on the specified parameters.
Returns
Required padding in number of elements.
Definition at line 141 of file PaddingCalculator.h.
References PaddingCalculator::EXCLUDE_BORDER, and PaddingCalculator::INCLUDE_BORDER.
Referenced by arm_compute::test::validation::DATA_TEST_CASE(), arm_compute::test::validation::FIXTURE_DATA_TEST_CASE(), and PaddingCalculator::PaddingCalculator().
 {
     return required_padding(_offset < 0 ? Option::INCLUDE_BORDER : Option::EXCLUDE_BORDER);
 }
PaddingSize required_padding (Option option) const inline
Compute the required padding.
If option is INCLUDE_BORDER and border mode is not undefined, the top, bottom and left padding is set to boder size. Otherwise it is zero. The right padding is always computed based on the specified parameters.
Parameters
[in] option Padding option
Returns
Required padding in number of elements.
Definition at line 146 of file PaddingCalculator.h.
References PaddingCalculator::EXCLUDE_BORDER, arm_compute::test::fixed_point_arithmetic::detail::max(), padding, arm_compute::U, and arm_compute::UNDEFINED.
 {
     PaddingSize padding{ (_mode == BorderMode::UNDEFINED || option == Option::EXCLUDE_BORDER) ? 0U : static_cast<unsigned int>(std::max(0, _border_size)) };
     int padding_right = 0;
     if(_mode == BorderMode::UNDEFINED)
     {
         padding_right = (((_size - 2 * _border_size + _num_processed_elements - 1) / _num_processed_elements) - 1) * _num_processed_elements + _num_accessed_elements - _size + _border_size + _offset;
     }
     else
     {
         padding_right = (((_size + _num_processed_elements - 1) / _num_processed_elements) - 1) * _num_processed_elements + _num_accessed_elements - _size + _offset;
     }
     padding.right = std::max(0, padding_right);
     return padding;
 }
void set_access_offset (int offset) inline
Set offset of the access relative to the current position.
Parameters
[in] offset Offset of the access.
Definition at line 127 of file PaddingCalculator.h.
References offset().
Referenced by arm_compute::test::validation::DATA_TEST_CASE(), arm_compute::test::validation::FIXTURE_DATA_TEST_CASE(), and PaddingCalculator::PaddingCalculator().
 {
     _offset = offset;
 }
void set_accessed_elements (int elements) inline
Set number of accessed elements.
Parameters
[in] elements Number of accessed elements per iteration.
Definition at line 136 of file PaddingCalculator.h.
Referenced by arm_compute::test::validation::DATA_TEST_CASE(), arm_compute::test::validation::FIXTURE_DATA_TEST_CASE(), and PaddingCalculator::PaddingCalculator().
 {
     _num_accessed_elements = elements;
 }
void set_border_mode (BorderMode mode) inline
Set border mode.
Parameters
[in] mode Border mode.
Definition at line 117 of file PaddingCalculator.h.
Referenced by arm_compute::test::validation::DATA_TEST_CASE(), arm_compute::test::validation::FIXTURE_DATA_TEST_CASE(), and PaddingCalculator::PaddingCalculator().
 {
     _mode = mode;
 }
void set_border_size (int size) inline
Set border size.
Parameters
[in] size Border size in elements.
Definition at line 122 of file PaddingCalculator.h.
References size.
Referenced by arm_compute::test::validation::DATA_TEST_CASE(), arm_compute::test::validation::FIXTURE_DATA_TEST_CASE(), and PaddingCalculator::PaddingCalculator().
 {
     _border_size = size;
 }
void set_processed_elements (int elements) inline
Set number of processed elements.
Parameters
[in] elements Number of processed elements per iteration.
Definition at line 132 of file PaddingCalculator.h.
Referenced by PaddingCalculator::PaddingCalculator().
 {
     _num_processed_elements = elements;
 }
The documentation for this class was generated from the following file:
tests/PaddingCalculator.h