Compute Library: BoundingBoxTransformLayer Class Reference
BoundingBoxTransformLayer Class Reference final
Bounding Box Transform Layer.
#include <Layers.h>
Public Member Functions
BoundingBoxTransformLayer (SubStream &&sub_stream_input, SubStream &&sub_stream_deltas, BoundingBoxTransformInfo info)
Construct a bounding box transform layer.
NodeID create_layer (IStream &s) override
Create layer and add to the given stream.
Public Member Functions inherited from ILayer
virtual ~ILayer ()=default
Default destructor.
ILayer & set_name (std::string name)
Sets the name of the layer.
const std::string & name () const
Layer name accessor.
Detailed Description
Bounding Box Transform Layer.
Definition at line 158 of file Layers.h.
Constructor & Destructor Documentation
BoundingBoxTransformLayer()
BoundingBoxTransformLayer (SubStream && sub_stream_input, SubStream && sub_stream_deltas, BoundingBoxTransformInfo info) inline
Construct a bounding box transform layer.
Parameters
[in] sub_stream_input Graph sub-stream for the input
[in] sub_stream_deltas Graph sub-stream for the deltas
[in] info Contains BoundingBox operation information described in BoundingBoxTransformInfo.
Definition at line 167 of file Layers.h.
         : _ss_input(sub_stream_input), _ss_deltas(sub_stream_deltas), _bbox_info(info)
     {
     }
Member Function Documentation
create_layer()
NodeID create_layer (IStream & s) inline override virtual
Create layer and add to the given stream.
Parameters
[in] s Stream to add layer to.
Returns
ID of the created node.
Implements ILayer.
Definition at line 178 of file Layers.h.
     {
         NodeParams  common_params = { name(), s.hints().target_hint };
         NodeIdxPair input         = { _ss_input.tail_node(), 0 };
         NodeIdxPair deltas        = { _ss_deltas.tail_node(), 0 };
         return GraphBuilder::add_bounding_box_transform_node(s.graph(), common_params, input, deltas, _bbox_info);
     }
References GraphBuilder::add_bounding_box_transform_node(), IStream::graph(), IStream::hints(), ILayer::name(), IStream::tail_node(), and StreamHints::target_hint.
The documentation for this class was generated from the following file:
arm_compute/graph/frontend/Layers.h