Compute Library: ActivationLayer< DataSet, TensorType, Accessor, Function, dt > Class Template Reference
ActivationLayer< DataSet, TensorType, Accessor, Function, dt > Class Template Reference
#include <ActivationLayer.h>
Public Member Functions
void SetUp (::benchmark::State &state) override
void TearDown (::benchmark::State &state) override
Data Fields
Function act_layer {}
Profiler profiler {}
Detailed Description
template<typename DataSet, typename TensorType, typename Accessor, typename Function, DataType dt = DataType::F32>
class arm_compute::test::benchmark::ActivationLayer< DataSet, TensorType, Accessor, Function, dt >
Definition at line 44 of file ActivationLayer.h.
Member Function Documentation
void SetUp (::benchmark::State & state) inline override
Definition at line 47 of file ActivationLayer.h.
References arm_compute::test::cl::create_tensor(), ActivationLayerDataObject::info, arm_compute::test::library, Dimensions< T >::num_dimensions(), TensorShape::set(), and ActivationLayerDataObject::shape.
     {
         profiler.add(std::make_shared<WallClockTimer>());
         const ActivationLayerDataObject act_obj = *(DataSet().begin() + state.range(0));
         // Set batched in source and destination shapes
         const unsigned int batches              = state.range(1);
         const unsigned int fixed_point_position = 4;
         TensorShape        shape                = act_obj.shape;
         shape.set(shape.num_dimensions(), batches);
         // Create tensors
         src = create_tensor(shape, dt, 1, fixed_point_position);
         dst = create_tensor(shape, dt, 1, fixed_point_position);
         // Create and configure function
         act_layer.configure(&src, &dst, act_obj.info);
         // Allocate tensors
         src.allocator()->allocate();
         dst.allocator()->allocate();
         // Fill tensors
         library->fill_tensor_uniform(Accessor(src), 0);
     }
void TearDown (::benchmark::State & state) inline override
Definition at line 74 of file ActivationLayer.h.
     {
         src.allocator()->free();
         dst.allocator()->free();
         profiler.submit(state);
     }
Field Documentation
Function act_layer {}
Definition at line 82 of file ActivationLayer.h.
Profiler profiler {}
Definition at line 83 of file ActivationLayer.h.
The documentation for this class was generated from the following file:
tests/benchmark/common/ActivationLayer.h