Compute Library: NELogits1DSoftmaxKernel Class Reference
NELogits1DSoftmaxKernel Class Reference
Interface for softmax computation for QASYMM8 with pre-computed max.
#include <NESoftmaxLayerKernel.h>
Public Member Functions
const char * name () const override
Name of the kernel.
NELogits1DSoftmaxKernel ()
Default constructor.
NELogits1DSoftmaxKernel (const NELogits1DSoftmaxKernel &)=delete
Prevent instances of this class from being copied (As this class contains pointers)
NELogits1DSoftmaxKernel & operator= (const NELogits1DSoftmaxKernel &)=delete
Prevent instances of this class from being copied (As this class contains pointers)
NELogits1DSoftmaxKernel (NELogits1DSoftmaxKernel &&)=default
Allow instances of this class to be moved.
NELogits1DSoftmaxKernel & operator= (NELogits1DSoftmaxKernel &&)=default
Allow instances of this class to be moved.
~NELogits1DSoftmaxKernel ()=default
Default destructor.
void configure (const ITensor *input, const ITensor *max, ITensor *output, const float beta, ITensor *tmp)
Set the input and output tensors.
void run (const Window &window, const ThreadInfo &info) override
Execute the kernel on the passed window.
Public Member Functions inherited from ICPPKernel
virtual ~ICPPKernel ()=default
Default destructor.
Public Member Functions inherited from IKernel
IKernel ()
Constructor.
virtual ~IKernel ()=default
Destructor.
virtual bool is_parallelisable () const
Indicates whether or not the kernel is parallelisable.
virtual BorderSize border_size () const
The size of the border for that kernel.
const Window & window () const
The maximum window the kernel can be executed on.
Static Public Member Functions
static Status validate (const ITensorInfo *input, const ITensorInfo *max, const ITensorInfo *output, const float beta, const ITensorInfo *tmp)
Static function to check if given info will lead to a valid configuration of NELogits1DSoftmaxKernel.
Detailed Description
Interface for softmax computation for QASYMM8 with pre-computed max.
Definition at line 72 of file NESoftmaxLayerKernel.h.
Constructor & Destructor Documentation
NELogits1DSoftmaxKernel ()
Default constructor.
NELogits1DSoftmaxKernel (const NELogits1DSoftmaxKernel &) delete
Prevent instances of this class from being copied (As this class contains pointers)
NELogits1DSoftmaxKernel (NELogits1DSoftmaxKernel &&) default
Allow instances of this class to be moved.
~NELogits1DSoftmaxKernel () default
Default destructor.
Member Function Documentation
void configure (const ITensor * input, const ITensor * max, ITensor * output, const float beta, ITensor * tmp)
Set the input and output tensors.
Parameters
[in] input Source tensor. Data types supported: QASYMM8/F16/F32.
[in] max Max values tensor. Same shape as input with dimension 0 set to 1. Data types supported: same as input.
[out] output Destination tensor. Data types supported: same as input.
[in] beta A scaling factor for the exponent.
tmp Auxiliary tensor. Must be type F32 and same shape as the input.
const char* name () const inline override virtual
Name of the kernel.
Returns
Kernel name
Implements ICPPKernel.
Definition at line 75 of file NESoftmaxLayerKernel.h.
References arm_compute::test::validation::beta, NELogits1DMaxKernel::configure(), arm_compute::test::validation::in, arm_compute::test::validation::info(), ICPPSimpleKernel::operator=(), arm_compute::test::validation::out, NELogits1DMaxKernel::run(), NELogits1DMaxKernel::validate(), and IKernel::window().
     {
         return "NELogits1DSoftmaxKernel";
     }
NELogits1DSoftmaxKernel& operator= (const NELogits1DSoftmaxKernel &) delete
Prevent instances of this class from being copied (As this class contains pointers)
NELogits1DSoftmaxKernel& operator= (NELogits1DSoftmaxKernel &&) default
Allow instances of this class to be moved.
void run (const Window & window, const ThreadInfo & info) override virtual
Execute the kernel on the passed window.
Warning
If is_parallelisable() returns false then the passed window must be equal to window()
Note
The window has to be a region within the window returned by the window() method
The width of the window has to be a multiple of num_elems_processed_per_iteration().
Parameters
[in] window Region on which to execute the kernel. (Must be a region of the window returned by window())
[in] info Info about executing thread and CPU.
Implements ICPPKernel.
static Status validate (const ITensorInfo * input, const ITensorInfo * max, const ITensorInfo * output, const float beta, const ITensorInfo * tmp) static
Static function to check if given info will lead to a valid configuration of NELogits1DSoftmaxKernel.
Parameters
[in] input Source tensor info. Data types supported: QASYMM8/F16/F32.
[in] max Max values tensor info. Same shape as input with dimension 0 set to 1. Data types supported: same as input.
[in] output Destination tensor info. Data types supported: same as input.
[in] beta A scaling factor for the exponent.
[in] tmp Tensor info of auxiliary. Must be type F32 and same shape as the input.
Returns
a status
The documentation for this class was generated from the following file:
arm_compute/core/NEON/kernels/NESoftmaxLayerKernel.h