Compute Library: CLDeconvolutionLayerUpsample Class Reference
CLDeconvolutionLayerUpsample Class Reference
Basic function to run CLDeconvolutionLayerUpsampleKernel.
#include <CLDeconvolutionLayerUpsample.h>
Public Member Functions
CLDeconvolutionLayerUpsample ()
Default constructor.
CLDeconvolutionLayerUpsample (const CLDeconvolutionLayerUpsample &)=delete
Prevent instances of this class from being copied (As this class contains pointers)
CLDeconvolutionLayerUpsample & operator= (const CLDeconvolutionLayerUpsample &)=delete
Prevent instances of this class from being copied (As this class contains pointers)
CLDeconvolutionLayerUpsample (CLDeconvolutionLayerUpsample &&)=default
Allow instances of this class to be moved.
CLDeconvolutionLayerUpsample & operator= (CLDeconvolutionLayerUpsample &&)=default
Allow instances of this class to be moved.
virtual ~CLDeconvolutionLayerUpsample ()=default
Default destructor.
void configure (ICLTensor *input, ICLTensor *output, const BorderSize &inner_border, const PadStrideInfo &info)
Initialize the function's source, destination, interpolation type and border_mode.
void run () override
Run the kernels contained in the function.
Public Member Functions inherited from IFunction
virtual ~IFunction ()=default
Destructor.
virtual void prepare ()
Prepare the function for executing.
Static Public Member Functions
static Status validate (const ITensorInfo *input, const ITensorInfo *output, const BorderSize &inner_border, const PadStrideInfo &info)
Static function to check if given info will lead to a valid configuration of CLDeconvolutionLayerUpsample.
Detailed Description
Basic function to run CLDeconvolutionLayerUpsampleKernel.
Definition at line 40 of file CLDeconvolutionLayerUpsample.h.
Constructor & Destructor Documentation
CLDeconvolutionLayerUpsample() [1/3]
CLDeconvolutionLayerUpsample ()
Default constructor.
Definition at line 36 of file CLDeconvolutionLayerUpsample.cpp.
     : _upsample(),
       _output(nullptr)
 {
 }
CLDeconvolutionLayerUpsample() [2/3]
CLDeconvolutionLayerUpsample (const CLDeconvolutionLayerUpsample &) delete
Prevent instances of this class from being copied (As this class contains pointers)
CLDeconvolutionLayerUpsample() [3/3]
CLDeconvolutionLayerUpsample (CLDeconvolutionLayerUpsample &&) default
Allow instances of this class to be moved.
~CLDeconvolutionLayerUpsample()
virtual ~CLDeconvolutionLayerUpsample () virtual default
Default destructor.
Member Function Documentation
configure()
void configure (ICLTensor * input, ICLTensor * output, const BorderSize & inner_border, const PadStrideInfo & info)
Initialize the function's source, destination, interpolation type and border_mode.
Parameters
[in,out] input Source tensor. Data type supported: QASYMM8/F16/F32.
[out] output Destination tensor. Data type supported: same as input.
[in] inner_border The number of zeros added to right and top edges of the input.
[in] info Contains padding and policies to be used in the deconvolution.
Definition at line 48 of file CLDeconvolutionLayerUpsample.cpp.
 {
     ARM_COMPUTE_ERROR_ON_NULLPTR(input, output);
     _output = output;
     _upsample.configure(input, _output, inner_border, info);
 }
References ARM_COMPUTE_ERROR_ON_NULLPTR, CLDeconvolutionLayerUpsampleKernel::configure(), and arm_compute::test::validation::info.
Referenced by CLDeconvolutionLayer::configure().
operator=() [1/2]
CLDeconvolutionLayerUpsample& operator= (const CLDeconvolutionLayerUpsample &) delete
Prevent instances of this class from being copied (As this class contains pointers)
operator=() [2/2]
CLDeconvolutionLayerUpsample& operator= (CLDeconvolutionLayerUpsample &&) default
Allow instances of this class to be moved.
run()
void run () override virtual
Run the kernels contained in the function.
For NEON kernels:
Multi-threading is used for the kernels which are parallelisable.
By default std::thread::hardware_concurrency() threads are used.
Note
CPPScheduler::set_num_threads() can be used to manually set the number of threads
For OpenCL kernels:
All the kernels are enqueued on the queue associated with CLScheduler.
The queue is then flushed.
Note
The function will not block until the kernels are executed. It is the user's responsibility to wait.
Will call prepare() on first run if hasn't been done
Implements IFunction.
Definition at line 57 of file CLDeconvolutionLayerUpsample.cpp.
 {
     _output->map(CLScheduler::get().queue(), true);
     if(is_data_type_quantized_asymmetric(_output->info()->data_type()))
     {
         const uint8_t quantized_zero = _output->info()->quantization_info().offset;
         std::fill_n(_output->buffer(), _output->info()->total_size(), quantized_zero);
     }
     else
     {
         memset(_output->buffer(), 0, _output->info()->total_size());
     }
     _output->unmap(CLScheduler::get().queue());
     CLScheduler::get().enqueue(_upsample, false);
 }
References ICLTensor::buffer(), ITensorInfo::data_type(), CLScheduler::enqueue(), CLScheduler::get(), ITensor::info(), arm_compute::is_data_type_quantized_asymmetric(), ICLTensor::map(), QuantizationInfo::offset, ITensorInfo::quantization_info(), ITensorInfo::total_size(), and ICLTensor::unmap().
Referenced by CLDeconvolutionLayer::run().
validate()
Status validate (const ITensorInfo * input, const ITensorInfo * output, const BorderSize & inner_border, const PadStrideInfo & info) static
Static function to check if given info will lead to a valid configuration of CLDeconvolutionLayerUpsample.
Parameters
[in] input Source tensor info. Data type supported: QASYMM8/F16/F32.
[in] output Destination tensor info. Data type supported: same as input.
[in] inner_border The number of zeros added to right and top edges of the input.
[in] info Contains padding and policies to be used in the deconvolution.
Returns
a status
Definition at line 42 of file CLDeconvolutionLayerUpsample.cpp.
 {
     return CLDeconvolutionLayerUpsampleKernel::validate(input, output, inner_border, info);
 }
References arm_compute::test::validation::info, and CLDeconvolutionLayerUpsampleKernel::validate().
Referenced by CLDeconvolutionLayer::validate().
The documentation for this class was generated from the following files:
arm_compute/runtime/CL/functions/CLDeconvolutionLayerUpsample.h
src/runtime/CL/functions/CLDeconvolutionLayerUpsample.cpp