Compute Library: CLLutAllocator Class Reference
CLLutAllocator Class Reference
Basic implementation of a CL memory LUT allocator.
#include <CLLutAllocator.h>
Public Member Functions
CLLutAllocator ()
Default constructor.
~CLLutAllocator ()=default
Default destructor.
CLLutAllocator (const CLLutAllocator &)=delete
Prevent instances of this class from being copied (As this class contains pointers)
const CLLutAllocator & operator= (const CLLutAllocator &)=delete
Prevent instances of this class from being copy assigned (As this class contains pointers)
uint8_t * data ()
Interface to be implemented by the child class to return the pointer to the mapped data.
const cl::Buffer & cl_data () const
Interface to be implemented by the child class to return the pointer to the CL data.
uint8_t * map (cl::CommandQueue &q, bool blocking)
Enqueue a map operation of the allocated buffer on the given queue.
void unmap (cl::CommandQueue &q, uint8_t *mapping)
Enqueue an unmap operation of the allocated buffer on the given queue.
Public Member Functions inherited from ILutAllocator
ILutAllocator ()
Default constructor.
virtual ~ILutAllocator ()=default
Default virtual destructor.
ILutAllocator (ILutAllocator &&)=default
Allow instances of this class to be move constructed.
ILutAllocator & operator= (ILutAllocator &&)=default
Allow instances of this class to be moved.
void init (size_t num_elements, DataType data_type)
Allocate an LUT of the requested number of elements and data_type.
size_t num_elements () const
Returns the total number of elements in the LUT.
DataType type () const
Returns the type of the LUT.
size_t size () const
Returns the total size in bytes of the LUT.
Detailed Description
Basic implementation of a CL memory LUT allocator.
Definition at line 36 of file CLLutAllocator.h.
Constructor & Destructor Documentation
CLLutAllocator() [1/2]
CLLutAllocator ()
Default constructor.
Definition at line 31 of file CLLutAllocator.cpp.
     : _buffer(), _mapping(nullptr)
 {
 }
~CLLutAllocator()
~CLLutAllocator () default
Default destructor.
CLLutAllocator() [2/2]
CLLutAllocator (const CLLutAllocator &) delete
Prevent instances of this class from being copied (As this class contains pointers)
Member Function Documentation
cl_data()
const cl::Buffer & cl_data () const
Interface to be implemented by the child class to return the pointer to the CL data.
Returns
pointer to the CL data.
Definition at line 41 of file CLLutAllocator.cpp.
 {
     return _buffer;
 }
Referenced by CLLut::cl_buffer().
data()
uint8_t * data ()
Interface to be implemented by the child class to return the pointer to the mapped data.
Returns
pointer to the mapped data.
Definition at line 36 of file CLLutAllocator.cpp.
 {
     return _mapping;
 }
map()
uint8_t * map (cl::CommandQueue & q, bool blocking)
Enqueue a map operation of the allocated buffer on the given queue.
Parameters
[in,out] q The CL command queue to use for the mapping operation.
[in] blocking If true, then the mapping will be ready to use by the time this method returns, else it is the caller's responsibility to flush the queue and wait for the mapping operation to have completed before using the returned mapping pointer.
Returns
The mapping address.
Definition at line 46 of file CLLutAllocator.cpp.
 {
     ARM_COMPUTE_ERROR_ON(_buffer.get() == nullptr);
     return static_cast<uint8_t *>(q.enqueueMapBuffer(_buffer, blocking ? CL_TRUE : CL_FALSE, CL_MAP_READ | CL_MAP_WRITE, 0, size()));
 }
References ARM_COMPUTE_ERROR_ON, and ILutAllocator::size().
Referenced by CLLut::clear().
operator=()
const CLLutAllocator& operator= (const CLLutAllocator &) delete
Prevent instances of this class from being copy assigned (As this class contains pointers)
unmap()
void unmap (cl::CommandQueue & q, uint8_t * mapping)
Enqueue an unmap operation of the allocated buffer on the given queue.
Note
This method simply enqueue the unmap operation, it is the caller's responsibility to flush the queue and make sure the unmap is finished before the memory is accessed by the device.
Parameters
[in,out] q The CL command queue to use for the mapping operation.
[in] mapping The cpu mapping to unmap.
Definition at line 52 of file CLLutAllocator.cpp.
 {
     ARM_COMPUTE_ERROR_ON(_buffer.get() == nullptr);
     q.enqueueUnmapMemObject(_buffer, mapping);
 }
References ARM_COMPUTE_ERROR_ON.
Referenced by CLLut::clear().
The documentation for this class was generated from the following files:
arm_compute/runtime/CL/CLLutAllocator.h
src/runtime/CL/CLLutAllocator.cpp