Compute Library: NEHOGOrientationBinningKernel Class Reference
NEHOGOrientationBinningKernel Class Reference
NEON kernel to perform HOG Orientation Binning.
#include <NEHOGDescriptorKernel.h>
Public Member Functions
const char * name () const override
Name of the kernel.
NEHOGOrientationBinningKernel ()
Default constructor.
NEHOGOrientationBinningKernel (const NEHOGOrientationBinningKernel &)=delete
Prevent instances of this class from being copied (As this class contains pointers)
NEHOGOrientationBinningKernel & operator= (const NEHOGOrientationBinningKernel &)=delete
Prevent instances of this class from being copied (As this class contains pointers)
NEHOGOrientationBinningKernel (NEHOGOrientationBinningKernel &&)=default
Allow instances of this class to be moved.
NEHOGOrientationBinningKernel & operator= (NEHOGOrientationBinningKernel &&)=default
Allow instances of this class to be moved.
~NEHOGOrientationBinningKernel ()=default
Default destructor.
void configure (const ITensor *input_magnitude, const ITensor *input_phase, ITensor *output, const HOGInfo *hog_info)
Initialise the kernel's inputs, output and HOG's metadata.
void run (const Window &window, const ThreadInfo &info) override
Execute the kernel on the passed window.
Public Member Functions inherited from ICPPKernel
virtual ~ICPPKernel ()=default
Default destructor.
Public Member Functions inherited from IKernel
IKernel ()
Constructor.
virtual ~IKernel ()=default
Destructor.
virtual bool is_parallelisable () const
Indicates whether or not the kernel is parallelisable.
virtual BorderSize border_size () const
The size of the border for that kernel.
const Window & window () const
The maximum window the kernel can be executed on.
Detailed Description
NEON kernel to perform HOG Orientation Binning.
Definition at line 36 of file NEHOGDescriptorKernel.h.
Constructor & Destructor Documentation
NEHOGOrientationBinningKernel() [1/3]
NEHOGOrientationBinningKernel ()
Default constructor.
Definition at line 627 of file NEHOGDescriptorKernel.cpp.
     : _func(nullptr), _input_magnitude(nullptr), _input_phase(nullptr), _output(nullptr), _cell_width(0), _cell_height(0), _num_bins(0), _phase_scale(0)
 {
 }
NEHOGOrientationBinningKernel() [2/3]
NEHOGOrientationBinningKernel (const NEHOGOrientationBinningKernel &) delete
Prevent instances of this class from being copied (As this class contains pointers)
NEHOGOrientationBinningKernel() [3/3]
NEHOGOrientationBinningKernel (NEHOGOrientationBinningKernel &&) default
Allow instances of this class to be moved.
~NEHOGOrientationBinningKernel()
~NEHOGOrientationBinningKernel () default
Default destructor.
Member Function Documentation
configure()
void configure (const ITensor * input_magnitude, const ITensor * input_phase, ITensor * output, const HOGInfo * hog_info)
Initialise the kernel's inputs, output and HOG's metadata.
Parameters
[in] input_magnitude Input tensor which stores the magnitude of the gradient for each pixel. Data type supported: S16.
[in] input_phase Input tensor which stores the phase of the gradient for each pixel. Data type supported: U8
[out] output Output tensor which stores the local HOG for each cell. Data type supported: F32. Number of channels supported: equal to the number of histogram bins per cell
[in] hog_info HOG's metadata
Definition at line 632 of file NEHOGDescriptorKernel.cpp.
 {
     ARM_COMPUTE_ERROR_ON_DATA_TYPE_CHANNEL_NOT_IN(input_magnitude, 1, DataType::S16);
     ARM_COMPUTE_ERROR_ON_DATA_TYPE_CHANNEL_NOT_IN(input_phase, 1, DataType::U8);
     ARM_COMPUTE_ERROR_ON(hog_info == nullptr);
     ARM_COMPUTE_ERROR_ON_DATA_TYPE_CHANNEL_NOT_IN(output, hog_info->num_bins(), DataType::F32);
     ARM_COMPUTE_ERROR_ON(input_magnitude->info()->dimension(Window::DimX) != input_phase->info()->dimension(Window::DimX));
     ARM_COMPUTE_ERROR_ON(input_magnitude->info()->dimension(Window::DimY) != input_phase->info()->dimension(Window::DimY));
     _input_magnitude = input_magnitude;
     _input_phase     = input_phase;
     _output          = output;
     _cell_width      = hog_info->cell_size().width;
     _cell_height     = hog_info->cell_size().height;
     _num_bins        = hog_info->num_bins();
     _phase_scale     = (PhaseType::SIGNED == hog_info->phase_type() ? _num_bins / 360.0f : _num_bins / 180.0f);
     _phase_scale *= (PhaseType::SIGNED == hog_info->phase_type() ? 360.0f / 255.0f : 1.0f);
     if(_cell_width < 8)
     {
         _func = &cell_width_lt8;
     }
     else
     {
         _func = &cell_width_ge8;
     }
     constexpr unsigned int num_elems_processed_per_iteration = 1;
     const unsigned int     num_elems_read_per_iteration      = 1;
     const unsigned int     num_rows_read_per_iteration       = _cell_height;
     const unsigned int     num_elems_written_per_iteration   = 1;
     // Configure kernel window
     Window                 win = calculate_max_window(*output->info(), Steps(num_elems_processed_per_iteration));
     AccessWindowHorizontal output_access(output->info(), 0, num_elems_written_per_iteration);
     update_window_and_padding(win,
                               AccessWindowRectangle(input_magnitude->info(), 0, 0, num_elems_read_per_iteration, num_rows_read_per_iteration),
                               AccessWindowRectangle(input_phase->info(), 0, 0, num_elems_read_per_iteration, num_rows_read_per_iteration),
                               output_access);
     output->info()->set_valid_region(ValidRegion(Coordinates(), output->info()->tensor_shape()));
     INEKernel::configure(win);
 }
References ARM_COMPUTE_ERROR_ON, ARM_COMPUTE_ERROR_ON_DATA_TYPE_CHANNEL_NOT_IN, arm_compute::calculate_max_window(), HOGInfo::cell_size(), ITensorInfo::dimension(), Window::DimX, Window::DimY, arm_compute::F32, Size2D::height, ITensor::info(), HOGInfo::num_bins(), HOGInfo::phase_type(), arm_compute::S16, ITensorInfo::set_valid_region(), arm_compute::SIGNED, ITensorInfo::tensor_shape(), arm_compute::U8, arm_compute::update_window_and_padding(), and Size2D::width.
Referenced by NEHOGDescriptor::configure().
name()
const char* name () const inline override virtual
Name of the kernel.
Returns
Kernel name
Implements ICPPKernel.
Definition at line 39 of file NEHOGDescriptorKernel.h.
     {
         return "NEHOGOrientationBinningKernel";
     }
operator=() [1/2]
NEHOGOrientationBinningKernel& operator= (const NEHOGOrientationBinningKernel &) delete
Prevent instances of this class from being copied (As this class contains pointers)
operator=() [2/2]
NEHOGOrientationBinningKernel& operator= (NEHOGOrientationBinningKernel &&) default
Allow instances of this class to be moved.
run()
void run (const Window & window, const ThreadInfo & info) override virtual
Execute the kernel on the passed window.
Warning
If is_parallelisable() returns false then the passed window must be equal to window()
Note
The window has to be a region within the window returned by the window() method
The width of the window has to be a multiple of num_elems_processed_per_iteration().
Parameters
[in] window Region on which to execute the kernel. (Must be a region of the window returned by window())
[in] info Info about executing thread and CPU.
Implements ICPPKernel.
Definition at line 678 of file NEHOGDescriptorKernel.cpp.
 {
     ARM_COMPUTE_UNUSED(info);
     ARM_COMPUTE_ERROR_ON_UNCONFIGURED_KERNEL(this);
     ARM_COMPUTE_ERROR_ON_INVALID_SUBWINDOW(IKernel::window(), window);
     ARM_COMPUTE_ERROR_ON(_func == nullptr);
     const size_t mag_stride   = _input_magnitude->info()->strides_in_bytes()[Window::DimY] / pixel_size_from_format(_input_magnitude->info()->format());
     const size_t phase_stride = _input_phase->info()->strides_in_bytes()[Window::DimY] / pixel_size_from_format(_input_phase->info()->format());
     Window win_mag(window);
     win_mag.set(Window::DimX, Window::Dimension(window.x().start() * _cell_width, window.x().start() * _cell_width, _cell_width));
     win_mag.set(Window::DimY, Window::Dimension(window.y().start() * _cell_height, window.y().start() * _cell_height, _cell_height));
     Window win_phase(win_mag);
     Iterator mag(_input_magnitude, win_mag);
     Iterator phase(_input_phase, win_phase);
     Iterator out(_output, window);
     execute_window_loop(window, [&](const Coordinates &)
     {
         const auto mag_row_ptr   = reinterpret_cast<const int16_t *>(mag.ptr());
         const auto phase_row_ptr = reinterpret_cast<const uint8_t *>(phase.ptr());
         const auto out_row_ptr   = reinterpret_cast<float *>(out.ptr());
         (*_func)(mag_row_ptr, phase_row_ptr, out_row_ptr, mag_stride, phase_stride, _cell_width, _cell_height, _num_bins, _phase_scale);
     },
     mag, phase, out);
 }
References ARM_COMPUTE_ERROR_ON, ARM_COMPUTE_ERROR_ON_INVALID_SUBWINDOW, ARM_COMPUTE_ERROR_ON_UNCONFIGURED_KERNEL, ARM_COMPUTE_UNUSED, Window::DimX, Window::DimY, arm_compute::execute_window_loop(), ITensorInfo::format(), ITensor::info(), arm_compute::test::validation::info, arm_compute::test::validation::reference::phase(), arm_compute::pixel_size_from_format(), Iterator::ptr(), Window::Dimension::start(), ITensorInfo::strides_in_bytes(), IKernel::window(), Window::x(), and Window::y().
The documentation for this class was generated from the following files:
arm_compute/core/NEON/kernels/NEHOGDescriptorKernel.h
src/core/NEON/kernels/NEHOGDescriptorKernel.cpp