Compute Library: CPPSortEuclideanDistanceKernel Class Reference
CPPSortEuclideanDistanceKernel Class Reference
CPP kernel to perform sorting and euclidean distance.
#include <CPPSortEuclideanDistanceKernel.h>
Public Member Functions
const char * name () const override
Name of the kernel.
CPPSortEuclideanDistanceKernel ()
Default constructor.
CPPSortEuclideanDistanceKernel (const CPPSortEuclideanDistanceKernel &)=delete
Prevent instances of this class from being copied (As this class contains pointers)
CPPSortEuclideanDistanceKernel & operator= (const CPPSortEuclideanDistanceKernel &)=delete
Prevent instances of this class from being copied (As this class contains pointers)
CPPSortEuclideanDistanceKernel (CPPSortEuclideanDistanceKernel &&)=default
Allow instances of this class to be moved.
CPPSortEuclideanDistanceKernel & operator= (CPPSortEuclideanDistanceKernel &&)=default
Allow instances of this class to be moved.
void configure (InternalKeypoint *in_out, IKeyPointArray *output, const int32_t *num_corner_candidates, float min_distance)
Initialise the kernel's source, destination and border mode.
void run (const Window &window, const ThreadInfo &info) override
Execute the kernel on the passed window.
bool is_parallelisable () const override
Indicates whether or not the kernel is parallelisable.
Public Member Functions inherited from ICPPKernel
virtual ~ICPPKernel ()=default
Default destructor.
Public Member Functions inherited from IKernel
IKernel ()
Constructor.
virtual ~IKernel ()=default
Destructor.
virtual BorderSize border_size () const
The size of the border for that kernel.
const Window & window () const
The maximum window the kernel can be executed on.
Detailed Description
CPP kernel to perform sorting and euclidean distance.
Definition at line 36 of file CPPSortEuclideanDistanceKernel.h.
Constructor & Destructor Documentation
CPPSortEuclideanDistanceKernel() [1/3]
CPPSortEuclideanDistanceKernel ()
Default constructor.
Definition at line 47 of file CPPSortEuclideanDistanceKernel.cpp.
     : _num_corner_candidates(), _min_distance(0.0f), _in_out(nullptr), _output(nullptr)
 {
 }
CPPSortEuclideanDistanceKernel() [2/3]
CPPSortEuclideanDistanceKernel (const CPPSortEuclideanDistanceKernel &) delete
Prevent instances of this class from being copied (As this class contains pointers)
CPPSortEuclideanDistanceKernel() [3/3]
CPPSortEuclideanDistanceKernel (CPPSortEuclideanDistanceKernel &&) default
Allow instances of this class to be moved.
Member Function Documentation
configure()
void configure (InternalKeypoint * in_out, IKeyPointArray * output, const int32_t * num_corner_candidates, float min_distance)
Initialise the kernel's source, destination and border mode.
Parameters
[in,out] in_out Input internal keypoints. Marked as out as the kernel writes 0 in the strength member.
[out] output Output keypoints.
[in] num_corner_candidates Pointer to the number of corner candidates in the input array
[in] min_distance Radial Euclidean distance to use
Definition at line 52 of file CPPSortEuclideanDistanceKernel.cpp.
 {
     ARM_COMPUTE_ERROR_ON(nullptr == in_out);
     ARM_COMPUTE_ERROR_ON(nullptr == output);
     ARM_COMPUTE_ERROR_ON(nullptr == num_corner_candidates);
     ARM_COMPUTE_ERROR_ON(!((min_distance > 0) && (min_distance <= 30)));
     _in_out                = in_out;
     _output                = output;
     _min_distance          = min_distance * min_distance; // We compare squares of distances
     _num_corner_candidates = num_corner_candidates;
     ICPPKernel::configure(Window()); // Default 1 iteration window
 }
References ARM_COMPUTE_ERROR_ON.
Referenced by CLHarrisCorners::configure(), and NEHarrisCorners::configure().
is_parallelisable()
bool is_parallelisable () const override virtual
Indicates whether or not the kernel is parallelisable.
If the kernel is parallelisable then the window returned by window() can be split into sub-windows which can then be run in parallel.
If the kernel is not parallelisable then only the window returned by window() can be passed to run()
Returns
True if the kernel is parallelisable
Reimplemented from IKernel.
Definition at line 66 of file CPPSortEuclideanDistanceKernel.cpp.
 {
     return false;
 }
name()
const char* name () const inline override virtual
Name of the kernel.
Returns
Kernel name
Implements ICPPKernel.
Definition at line 39 of file CPPSortEuclideanDistanceKernel.h.
     {
         return "CPPSortEuclideanDistanceKernel";
     }
operator=() [1/2]
CPPSortEuclideanDistanceKernel& operator= (const CPPSortEuclideanDistanceKernel &) delete
Prevent instances of this class from being copied (As this class contains pointers)
operator=() [2/2]
CPPSortEuclideanDistanceKernel& operator= (CPPSortEuclideanDistanceKernel &&) default
Allow instances of this class to be moved.
run()
void run (const Window & window, const ThreadInfo & info) override virtual
Execute the kernel on the passed window.
Warning
If is_parallelisable() returns false then the passed window must be equal to window()
Note
The window has to be a region within the window returned by the window() method
The width of the window has to be a multiple of num_elems_processed_per_iteration().
Parameters
[in] window Region on which to execute the kernel. (Must be a region of the window returned by window())
[in] info Info about executing thread and CPU.
Implements ICPPKernel.
Definition at line 71 of file CPPSortEuclideanDistanceKernel.cpp.
 {
     ARM_COMPUTE_UNUSED(info);
     ARM_COMPUTE_UNUSED(window);
     ARM_COMPUTE_ERROR_ON_UNCONFIGURED_KERNEL(this);
     ARM_COMPUTE_ERROR_ON_MISMATCHING_WINDOWS(ICPPKernel::window(), window);
     const int32_t num_corner_candidates = *_num_corner_candidates;
     /* Sort list of corner candidates */
     std::sort(_in_out, _in_out + num_corner_candidates, keypoint_compare);
     /* Euclidean distance */
     for(int32_t i = 0; i < num_corner_candidates; ++i)
     {
         if(std::get<2>(_in_out[i]) != 0.0f)
         {
             KeyPoint   keypt;
             const auto xc = std::get<0>(_in_out[i]);
             const auto yc = std::get<1>(_in_out[i]);
             keypt.x               = xc;
             keypt.y               = yc;
             keypt.strength        = std::get<2>(_in_out[i]);
             keypt.tracking_status = 1;
             /* Store corner */
             _output->push_back(keypt);
             for(int32_t k = i + 1; k < num_corner_candidates; ++k)
             {
                 const float dx = std::fabs(std::get<0>(_in_out[k]) - xc);
                 const float dy = std::fabs(std::get<1>(_in_out[k]) - yc);
                 if((dx < _min_distance) && (dy < _min_distance))
                 {
                     const float d = (dx * dx + dy * dy);
                     if(d < _min_distance)
                     {
                         /* Invalidate keypoint */
                         std::get<2>(_in_out[k]) = 0.0f;
                     }
                 }
             }
         }
     }
 }
References ARM_COMPUTE_ERROR_ON_MISMATCHING_WINDOWS, ARM_COMPUTE_ERROR_ON_UNCONFIGURED_KERNEL, ARM_COMPUTE_UNUSED, arm_compute::test::validation::info, keypoint_compare(), IArray< T >::push_back(), KeyPoint::strength, KeyPoint::tracking_status, IKernel::window(), KeyPoint::x, and KeyPoint::y.
The documentation for this class was generated from the following files:
arm_compute/core/CPP/kernels/CPPSortEuclideanDistanceKernel.h
src/core/CPP/kernels/CPPSortEuclideanDistanceKernel.cpp