Compute Library: NEGaussianPyramidOrb Class Reference
NEGaussianPyramidOrb Class Reference
Basic function to execute gaussian pyramid with ORB scale factor.
#include <NEGaussianPyramid.h>
Public Member Functions
NEGaussianPyramidOrb ()
Constructor.
void configure (const ITensor *input, IPyramid *pyramid, BorderMode border_mode, uint8_t constant_border_value) override
Initialise the function's source, destinations and border mode.
void run () override
Run the kernels contained in the function.
Public Member Functions inherited from NEGaussianPyramid
NEGaussianPyramid ()
Default constructor.
NEGaussianPyramid (const NEGaussianPyramid &)=delete
Prevent instances of this class from being copied (As this class contains pointers)
NEGaussianPyramid & operator= (const NEGaussianPyramid &)=delete
Prevent instances of this class from being copied (As this class contains pointers)
NEGaussianPyramid (NEGaussianPyramid &&)=default
Allow instances of this class to be moved.
NEGaussianPyramid & operator= (NEGaussianPyramid &&)=default
Allow instances of this class to be moved.
virtual ~NEGaussianPyramid ()=default
Default destructor.
Public Member Functions inherited from IFunction
virtual ~IFunction ()=default
Destructor.
virtual void prepare ()
Prepare the function for executing.
Detailed Description
Basic function to execute gaussian pyramid with ORB scale factor.
This function calls the following NEON kernels and functions:
NEFillBorderKernel (executed if border_mode == CONSTANT or border_mode == REPLICATE)
NEGaussian5x5
NEScaleKernel
Definition at line 107 of file NEGaussianPyramid.h.
Constructor & Destructor Documentation
NEGaussianPyramidOrb()
NEGaussianPyramidOrb ()
Constructor.
Definition at line 133 of file NEGaussianPyramid.cpp.
     : _gaus5x5(),
       _scale_nearest()
 {
 }
Member Function Documentation
configure()
void configure (const ITensor * input, IPyramid * pyramid, BorderMode border_mode, uint8_t constant_border_value) override virtual
Initialise the function's source, destinations and border mode.
Parameters
[in] input Source tensor. Data type supported: U8.
[out] pyramid Destination pyramid tensors, Data type supported at each level: U8.
[in] border_mode Border mode to use.
[in] constant_border_value (Optional) Constant value to use for borders if border_mode is set to CONSTANT.
Implements NEGaussianPyramid.
Definition at line 139 of file NEGaussianPyramid.cpp.
 {
     ARM_COMPUTE_ERROR_ON_DATA_TYPE_CHANNEL_NOT_IN(input, 1, DataType::U8);
     ARM_COMPUTE_ERROR_ON(nullptr == pyramid);
     ARM_COMPUTE_ERROR_ON(input->info()->num_dimensions() != pyramid->get_pyramid_level(0)->info()->num_dimensions());
     ARM_COMPUTE_ERROR_ON(input->info()->dimension(0) != pyramid->info()->width());
     ARM_COMPUTE_ERROR_ON(input->info()->dimension(1) != pyramid->info()->height());
     ARM_COMPUTE_ERROR_ON(SCALE_PYRAMID_ORB != pyramid->info()->scale());
     /* Get number of pyramid levels */
     const size_t num_levels = pyramid->info()->num_levels();
     const size_t num_stages = num_levels - 1;
     _input   = input;
     _pyramid = pyramid;
     _gaus5x5.clear();
     _scale_nearest.clear();
     _gaus5x5.resize(num_stages);
     _scale_nearest.resize(num_stages);
     if(num_levels > 1)
     {
         PyramidInfo pyramid_info(num_levels - 1, SCALE_PYRAMID_ORB, pyramid->info()->tensor_shape(), Format::U8);
         _tmp.init(pyramid_info);
         for(size_t i = 0; i < num_levels - 1; ++i)
         {
             /* Configure gaussian 5x5 */
             _gaus5x5[i].configure(_pyramid->get_pyramid_level(i), _tmp.get_pyramid_level(i), border_mode, constant_border_value);
             /* Configure scale */
             _scale_nearest[i].configure(_tmp.get_pyramid_level(i), _pyramid->get_pyramid_level(i + 1), InterpolationPolicy::NEAREST_NEIGHBOR, BorderMode::UNDEFINED);
         }
         _tmp.allocate();
     }
 }
References ARM_COMPUTE_ERROR_ON, ARM_COMPUTE_ERROR_ON_DATA_TYPE_CHANNEL_NOT_IN, arm_compute::test::validation::border_mode, ITensorInfo::dimension(), IPyramid::get_pyramid_level(), PyramidInfo::height(), ITensor::info(), IPyramid::info(), PyramidInfo::init(), arm_compute::NEAREST_NEIGHBOR, ITensorInfo::num_dimensions(), PyramidInfo::num_levels(), PyramidInfo::scale(), arm_compute::SCALE_PYRAMID_ORB, PyramidInfo::tensor_shape(), arm_compute::U8, arm_compute::UNDEFINED, and PyramidInfo::width().
run()
void run () override virtual
Run the kernels contained in the function.
For NEON kernels:
Multi-threading is used for the kernels which are parallelisable.
By default std::thread::hardware_concurrency() threads are used.
Note
CPPScheduler::set_num_threads() can be used to manually set the number of threads
For OpenCL kernels:
All the kernels are enqueued on the queue associated with CLScheduler.
The queue is then flushed.
Note
The function will not block until the kernels are executed. It is the user's responsibility to wait.
Will call prepare() on first run if hasn't been done
Implements IFunction.
Definition at line 179 of file NEGaussianPyramid.cpp.
 {
     ARM_COMPUTE_ERROR_ON_MSG(_pyramid == nullptr, "Unconfigured function");
     /* Get number of pyramid levels */
     const size_t num_levels = _pyramid->info()->num_levels();
     /* The first level of the pyramid has the input image */
     _pyramid->get_pyramid_level(0)->copy_from(*_input);
     for(unsigned int i = 0; i < num_levels - 1; ++i)
     {
         _gaus5x5[i].run();
         _scale_nearest[i].run();
     }
 }
References ARM_COMPUTE_ERROR_ON_MSG.
The documentation for this class was generated from the following files:
arm_compute/runtime/NEON/functions/NEGaussianPyramid.h
src/runtime/NEON/functions/NEGaussianPyramid.cpp