Compute Library: BranchLayer Class Reference
BranchLayer Class Reference final
Branch Layer.
#include <Layers.h>
Public Member Functions
template<typename... Ts>
BranchLayer (BranchMergeMethod merge_method, SubStream &&sub_stream1, SubStream &&sub_stream2, Ts &&...rest_sub_streams)
Construct a branch layer.
template<typename... Ts>
BranchLayer (SubStream &&sub_stream)
Construct a branch layer.
NodeID create_layer (IStream &s) override
Create layer and add to the given stream.
Public Member Functions inherited from ILayer
virtual ~ILayer ()=default
Default destructor.
ILayer & set_name (std::string name)
Sets the name of the layer.
const std::string & name () const
Layer name accessor.
Detailed Description
Branch Layer.
Definition at line 597 of file Layers.h.
Constructor & Destructor Documentation
BranchLayer (BranchMergeMethod merge_method, SubStream && sub_stream1, SubStream && sub_stream2, Ts &&... rest_sub_streams) inline
Construct a branch layer.
Parameters
[in] merge_method Branch merging method
[in] sub_stream1 First graph branch
[in] sub_stream2 Second graph branch
[in] rest_sub_streams Rest sub-graph branches
Definition at line 608 of file Layers.h.
References arm_compute::utility::for_each().
         : _branch_merge_method(merge_method), _sub_streams()
     {
         _sub_streams.push_back(arm_compute::support::cpp14::make_unique<SubStream>(std::move(sub_stream1)));
         _sub_streams.push_back(arm_compute::support::cpp14::make_unique<SubStream>(std::move(sub_stream2)));
         utility::for_each([&](SubStream && sub_stream)
         {
             _sub_streams.push_back(arm_compute::support::cpp14::make_unique<SubStream>(std::move(sub_stream)));
         },
         std::move(rest_sub_streams)...);
     }
BranchLayer (SubStream && sub_stream) inline
Construct a branch layer.
Parameters
[in] sub_stream Sub-stream
Definition at line 625 of file Layers.h.
         : _branch_merge_method(BranchMergeMethod::DEPTH_CONCATENATE), _sub_streams()
     {
         _sub_streams.push_back(arm_compute::support::cpp14::make_unique<SubStream>(std::move(sub_stream)));
     }
Member Function Documentation
NodeID create_layer (IStream & s) inline override virtual
Create layer and add to the given stream.
Parameters
[in] s Stream to add layer to.
Returns
ID of the created node.
Implements ILayer.
Definition at line 630 of file Layers.h.
References arm_compute::graph::Add, GraphBuilder::add_concatenate_node(), GraphBuilder::add_elementwise_node(), ARM_COMPUTE_ERROR_ON, arm_compute::CHANNEL, arm_compute::graph::frontend::DEPTH_CONCATENATE, arm_compute::graph::EmptyNodeID, IStream::graph(), IStream::hints(), ILayer::name(), Graph::node(), arm_compute::graph::Output, and StreamHints::target_hint.
     {
         NodeID     nid           = EmptyNodeID;
         NodeParams common_params = { name(), s.hints().target_hint };
         if(_sub_streams.size() == 1 && _sub_streams.at(0) != nullptr)
         {
             nid = _sub_streams[0]->tail_node();
         }
         else if(_branch_merge_method == BranchMergeMethod::DEPTH_CONCATENATE)
         {
             // Collect tail nodes and concatenate
             std::vector<NodeIdxPair> nodes;
             for(auto &ss : _sub_streams)
             {
                 if(ss && (ss->tail_node() != EmptyNodeID))
                 {
                     const auto tail_node = s.graph().node(ss->tail_node());
                     if(tail_node != nullptr && tail_node->type() != NodeType::Output)
                     {
                         nodes.push_back({ ss->tail_node(), 0 });
                     }
                 }
             }
             nid = GraphBuilder::add_concatenate_node(s.graph(), common_params, nodes, DataLayoutDimension::CHANNEL);
         }
         else
         {
             ARM_COMPUTE_ERROR_ON(_sub_streams.size() != 2);
             NodeIdxPair input0 = { _sub_streams[0]->tail_node(), 0 };
             NodeIdxPair input1 = { _sub_streams[1]->tail_node(), 0 };
             nid                = GraphBuilder::add_elementwise_node(s.graph(), common_params, input0, input1, EltwiseOperation::Add);
         }
         return nid;
     }
The documentation for this class was generated from the following file:
arm_compute/graph/frontend/Layers.h