Compute Library: CLTransposeKernel Class Reference
CLTransposeKernel Class Reference
OpenCL kernel which transposes the elements of a matrix.
#include <CLTransposeKernel.h>
Public Member Functions
void configure (const ICLTensor *input, ICLTensor *output)
Initialise the kernel's input and output.
Public Member Functions inherited from ICLSimple2DKernel
void run (const Window &window, cl::CommandQueue &queue) override
Enqueue the OpenCL kernel to process the given window on the passed OpenCL command queue.
Public Member Functions inherited from ICLSimpleKernel
ICLSimpleKernel ()
Constructor.
ICLSimpleKernel (const ICLSimpleKernel &)=delete
Prevent instances of this class from being copied (As this class contains pointers)
ICLSimpleKernel & operator= (const ICLSimpleKernel &)=delete
Prevent instances of this class from being copied (As this class contains pointers)
ICLSimpleKernel (ICLSimpleKernel &&)=default
Allow instances of this class to be moved.
ICLSimpleKernel & operator= (ICLSimpleKernel &&)=default
Allow instances of this class to be moved.
~ICLSimpleKernel ()=default
Default destructor.
void configure (const ICLTensor *input, ICLTensor *output, unsigned int num_elems_processed_per_iteration, bool border_undefined=false, const BorderSize &border_size=BorderSize())
Configure the kernel.
Public Member Functions inherited from ICLKernel
ICLKernel ()
Constructor.
cl::Kernel & kernel ()
Returns a reference to the OpenCL kernel of this object.
template<typename T >
void add_1D_array_argument (unsigned int &idx, const ICLArray< T > *array, const Strides &strides, unsigned int num_dimensions, const Window &window)
Add the passed 1D array's parameters to the object's kernel's arguments starting from the index idx.
void add_1D_tensor_argument (unsigned int &idx, const ICLTensor *tensor, const Window &window)
Add the passed 1D tensor's parameters to the object's kernel's arguments starting from the index idx.
void add_2D_tensor_argument (unsigned int &idx, const ICLTensor *tensor, const Window &window)
Add the passed 2D tensor's parameters to the object's kernel's arguments starting from the index idx.
void add_3D_tensor_argument (unsigned int &idx, const ICLTensor *tensor, const Window &window)
Add the passed 3D tensor's parameters to the object's kernel's arguments starting from the index idx.
void add_4D_tensor_argument (unsigned int &idx, const ICLTensor *tensor, const Window &window)
Add the passed 4D tensor's parameters to the object's kernel's arguments starting from the index idx.
template<typename T >
void add_argument (unsigned int &idx, T value)
Add the passed parameters to the object's kernel's arguments starting from the index idx.
void set_lws_hint (const cl::NDRange &lws_hint)
Set the Local-Workgroup-Size hint.
cl::NDRange lws_hint () const
Return the Local-Workgroup-Size hint.
const std::string & config_id () const
Get the configuration ID.
void set_target (GPUTarget target)
Set the targeted GPU architecture.
void set_target (cl::Device &device)
Set the targeted GPU architecture according to the CL device.
GPUTarget get_target () const
Get the targeted GPU architecture.
size_t get_max_workgroup_size ()
Get the maximum workgroup size for the device the CLKernelLibrary uses.
template<typename T , unsigned int dimension_size>
void add_array_argument (unsigned &idx, const ICLArray< T > *array, const Strides &strides, unsigned int num_dimensions, const Window &window)
Add the passed array's parameters to the object's kernel's arguments starting from the index idx.
template<unsigned int dimension_size>
void add_tensor_argument (unsigned &idx, const ICLTensor *tensor, const Window &window)
Public Member Functions inherited from IKernel
IKernel ()
Constructor.
virtual ~IKernel ()=default
Destructor.
virtual bool is_parallelisable () const
Indicates whether or not the kernel is parallelisable.
virtual BorderSize border_size () const
The size of the border for that kernel.
const Window & window () const
The maximum window the kernel can be executed on.
Static Public Member Functions
static Status validate (const ITensorInfo *input, const ITensorInfo *output)
Static function to check if given info will lead to a valid configuration of CLTransposeKernel.
Static Public Member Functions inherited from ICLKernel
static constexpr unsigned int num_arguments_per_1D_array ()
Returns the number of arguments enqueued per 1D array object.
static constexpr unsigned int num_arguments_per_1D_tensor ()
Returns the number of arguments enqueued per 1D tensor object.
static constexpr unsigned int num_arguments_per_2D_tensor ()
Returns the number of arguments enqueued per 2D tensor object.
static constexpr unsigned int num_arguments_per_3D_tensor ()
Returns the number of arguments enqueued per 3D tensor object.
static constexpr unsigned int num_arguments_per_4D_tensor ()
Returns the number of arguments enqueued per 4D tensor object.
static cl::NDRange gws_from_window (const Window &window)
Get the global work size given an execution window.
Detailed Description
OpenCL kernel which transposes the elements of a matrix.
[width, height, batch] -> [height, width, batch]
Definition at line 38 of file CLTransposeKernel.h.
Member Function Documentation
configure()
void configure (const ICLTensor * input, ICLTensor * output)
Initialise the kernel's input and output.
Parameters
[in] input Input tensor. Data types supported: U8/S8/QASYMM8/U16/S16/F16/U32/S32/F32
[out] output Output tensor. Data type supported: Same as input
Definition at line 111 of file CLTransposeKernel.cpp.
 {
     ARM_COMPUTE_ERROR_ON_NULLPTR(input, output);
     // Output tensor auto inizialitation if not yet initialized
     auto_init_if_empty(*output->info(), input->info()->clone()->set_tensor_shape(transposed_tensor_shape(input->info()->tensor_shape())));
     ARM_COMPUTE_ERROR_THROW_ON(validate_arguments(input->info(), output->info()));
     _input  = input;
     _output = output;
     std::set<std::string> build_opts;
     std::ostringstream    data_type_in_bytes;
     data_type_in_bytes << input->info()->element_size();
     build_opts.emplace("-DDATA_TYPE_IN_BYTES=" + data_type_in_bytes.str());
     _kernel = static_cast<cl::Kernel>(CLKernelLibrary::get().create_kernel("transpose", build_opts));
     // Configure kernel window
     auto win_config = validate_and_configure_window(input->info(), output->info());
     ARM_COMPUTE_ERROR_THROW_ON(win_config.first);
     ICLKernel::configure_internal(win_config.second, cl::NDRange(2, 8));
 }
References ARM_COMPUTE_ERROR_ON_NULLPTR, ARM_COMPUTE_ERROR_THROW_ON, arm_compute::auto_init_if_empty(), ICloneable< T >::clone(), arm_compute::create_kernel(), ITensorInfo::element_size(), CLKernelLibrary::get(), ITensor::info(), and ITensorInfo::tensor_shape().
Referenced by CLLSTMLayer::configure().
validate()
Status validate (const ITensorInfo * input, const ITensorInfo * output) static
Static function to check if given info will lead to a valid configuration of CLTransposeKernel.
Parameters
[in] input Input tensor. Data types supported: U8/S8/QASYMM8/U16/S16/F16/U32/S32/F32
[in] output Output tensor. Data type supported: Same as input
Returns
a status
Definition at line 103 of file CLTransposeKernel.cpp.
 {
     ARM_COMPUTE_ERROR_ON_NULLPTR(input, output);
     ARM_COMPUTE_RETURN_ON_ERROR(validate_arguments(input, output));
     ARM_COMPUTE_RETURN_ON_ERROR(validate_and_configure_window(input->clone().get(), output->clone().get()).first);
     return Status{};
 }
References ARM_COMPUTE_ERROR_ON_NULLPTR, ARM_COMPUTE_RETURN_ON_ERROR, and ICloneable< T >::clone().
Referenced by CLTranspose::validate(), and CLFullyConnectedLayerReshapeWeights::validate().
The documentation for this class was generated from the following files:
arm_compute/core/CL/kernels/CLTransposeKernel.h
src/core/CL/kernels/CLTransposeKernel.cpp