Compute Library: TensorLibrary Class Reference
TensorLibrary Class Reference final
Factory class to create and fill tensors.
#include <TensorLibrary.h>
Public Member Functions
TensorLibrary (std::string path)
Initialises the library with a path to the image directory.
TensorLibrary (std::string path, std::random_device::result_type seed)
Initialises the library with a path to the image directory.
std::random_device::result_type seed () const
Seed that is used to fill tensors with random values.
const RawTensor & get (const std::string &name) const
Provides a contant raw tensor for the specified image.
RawTensor get (const std::string &name)
Provides a raw tensor for the specified image.
RawTensor get (const std::string &name, DataType data_type, int num_channels=1) const
Creates an uninitialised raw tensor with the given data_type and num_channels.
const RawTensor & get (const std::string &name, Format format) const
Provides a contant raw tensor for the specified image after it has been converted to format.
RawTensor get (const std::string &name, Format format)
Provides a raw tensor for the specified image after it has been converted to format.
const RawTensor & get (const std::string &name, Channel channel) const
Provides a contant raw tensor for the specified channel after it has been extracted form the given image.
RawTensor get (const std::string &name, Channel channel)
Provides a raw tensor for the specified channel after it has been extracted form the given image.
const RawTensor & get (const std::string &name, Format format, Channel channel) const
Provides a constant raw tensor for the specified channel after it has been extracted form the given image formatted to format.
RawTensor get (const std::string &name, Format format, Channel channel)
Provides a raw tensor for the specified channel after it has been extracted form the given image formatted to format.
template<typename T , typename D >
void fill (T &&tensor, D &&distribution, std::random_device::result_type seed_offset) const
Fills the specified tensor with random values drawn from distribution.
template<typename D >
void fill (RawTensor &raw, D &&distribution, std::random_device::result_type seed_offset) const
Fills the specified raw tensor with random values drawn from distribution.
template<typename T >
void fill (T &&tensor, const std::string &name, Format format) const
Fills the specified tensor with the content of the specified image converted to the given format.
void fill (RawTensor &raw, const std::string &name, Format format) const
Fills the raw tensor with the content of the specified image converted to the given format.
template<typename T >
void fill (T &&tensor, const std::string &name, Channel channel) const
Fills the specified tensor with the content of the specified channel extracted from the given image.
void fill (RawTensor &raw, const std::string &name, Channel channel) const
Fills the raw tensor with the content of the specified channel extracted from the given image.
template<typename T >
void fill (T &&tensor, const std::string &name, Format format, Channel channel) const
Fills the specified tensor with the content of the specified channel extracted from the given image after it has been converted to the given format.
void fill (RawTensor &raw, const std::string &name, Format format, Channel channel) const
Fills the raw tensor with the content of the specified channel extracted from the given image after it has been converted to the given format.
template<typename T >
void fill_tensor_uniform (T &&tensor, std::random_device::result_type seed_offset) const
Fill a tensor with uniform distribution across the range of its type.
template<typename T , typename D >
void fill_tensor_uniform (T &&tensor, std::random_device::result_type seed_offset, D low, D high) const
Fill a tensor with uniform distribution across the a specified range.
template<typename T >
void fill_layer_data (T &&tensor, std::string name) const
Fills the specified tensor with data loaded from binary in specified path.
Static Public Member Functions
static RawTensor get (const TensorShape &shape, DataType data_type, int num_channels=1, int fixed_point_position=0)
Creates an uninitialised raw tensor with the given shape, data_type and num_channels.
static RawTensor get (const TensorShape &shape, Format format)
Creates an uninitialised raw tensor with the given shape and format.
Detailed Description
Factory class to create and fill tensors.
Allows to initialise tensors from loaded images or by specifying the shape explicitly. Furthermore, provides methods to fill tensors with the content of loaded images or with random values.
Definition at line 56 of file TensorLibrary.h.
Constructor & Destructor Documentation
TensorLibrary (std::string path)
Initialises the library with a path to the image directory.
Parameters
[in] path Path to load images from.
Definition at line 208 of file TensorLibrary.cpp.
     : _library_path(std::move(path)), _seed{ std::random_device()() }
 {
 }
TensorLibrary (std::string path, std::random_device::result_type seed)
Initialises the library with a path to the image directory.
Furthermore, sets the seed for the random generator to seed.
Parameters
[in] path Path to load images from.
[in] seed Seed used to initialise the random number generator.
Definition at line 213 of file TensorLibrary.cpp.
     : _library_path(std::move(path)), _seed{ seed }
 {
 }
Member Function Documentation
void fill (T && tensor, D && distribution, std::random_device::result_type seed_offset) const
Fills the specified tensor with random values drawn from distribution.
Parameters
[in,out] tensor To be filled tensor.
[in] distribution Distribution used to fill the tensor.
[in] seed_offset The offset will be added to the global seed before initialising the random generator.
Note
The distribution has to provide operator(Generator &) which will be used to draw samples.
Definition at line 368 of file TensorLibrary.h.
References arm_compute::execute_window_loop(), Window::set(), and arm_compute::test::store_value_with_data_type().
Referenced by TensorLibrary::fill(), and TensorLibrary::fill_tensor_uniform().
 {
     Window window;
     for(unsigned int d = 0; d < tensor.shape().num_dimensions(); ++d)
     {
         window.set(d, Window::Dimension(0, tensor.shape()[d], 1));
     }
     std::mt19937 gen(_seed + seed_offset);
     execute_window_loop(window, [&](const Coordinates & id)
     {
         using ResultType         = typename std::remove_reference<D>::type::result_type;
         const ResultType value   = distribution(gen);
         void *const      out_ptr = tensor(id);
         store_value_with_data_type(out_ptr, value, tensor.data_type());
     });
 }
void fill (RawTensor & raw, D && distribution, std::random_device::result_type seed_offset) const
Fills the specified raw tensor with random values drawn from distribution.
Parameters
[in,out] raw To be filled raw.
[in] distribution Distribution used to fill the tensor.
[in] seed_offset The offset will be added to the global seed before initialising the random generator.
Note
The distribution has to provide operator(Generator &) which will be used to draw samples.
Definition at line 388 of file TensorLibrary.h.
References RawTensor::data(), RawTensor::data_type(), RawTensor::element_size(), offset(), RawTensor::size(), and arm_compute::test::store_value_with_data_type().
 {
     std::mt19937 gen(_seed + seed_offset);
     for(size_t offset = 0; offset < raw.size(); offset += raw.element_size())
     {
         using ResultType       = typename std::remove_reference<D>::type::result_type;
         const ResultType value = distribution(gen);
         store_value_with_data_type(raw.data() + offset, value, raw.data_type());
     }
 }
void fill (T && tensor, const std::string & name, Format format) const
Fills the specified tensor with the content of the specified image converted to the given format.
Parameters
[in,out] tensor To be filled tensor.
[in] name Image file used to fill the tensor.
[in] format Format of the image used to fill the tensor.
Warning
No check is performed that the specified format actually matches the format of the tensor.
Definition at line 401 of file TensorLibrary.h.
References RawTensor::data(), RawTensor::element_size(), arm_compute::test::index2coord(), offset(), RawTensor::shape(), and RawTensor::size().
 {
     const RawTensor &raw = get(name, format);
     for(size_t offset = 0; offset < raw.size(); offset += raw.element_size())
     {
         const Coordinates id = index2coord(raw.shape(), offset / raw.element_size());
         const RawTensor::BufferType *const raw_ptr = raw.data() + offset;
         const auto                         out_ptr = static_cast<RawTensor::BufferType *>(tensor(id));
         std::copy_n(raw_ptr, raw.element_size(), out_ptr);
     }
 }
void fill (RawTensor & raw, const std::string & name, Format format) const
Fills the raw tensor with the content of the specified image converted to the given format.
Parameters
[in,out] raw To be filled raw tensor.
[in] name Image file used to fill the tensor.
[in] format Format of the image used to fill the tensor.
Warning
No check is performed that the specified format actually matches the format of the tensor.
Definition at line 223 of file TensorLibrary.cpp.
References RawTensor::data(), and RawTensor::size().
 {
     const RawTensor &src = get(name, format);
     std::copy_n(src.data(), raw.size(), raw.data());
 }
void fill (T && tensor, const std::string & name, Channel channel) const
Fills the specified tensor with the content of the specified channel extracted from the given image.
Parameters
[in,out] tensor To be filled tensor.
[in] name Image file used to fill the tensor.
[in] channel Channel of the image used to fill the tensor.
Note
The channel has to be unambiguous so that the format can be inferred automatically.
Warning
No check is performed that the specified format actually matches the format of the tensor.
Definition at line 416 of file TensorLibrary.h.
References TensorLibrary::fill(), and arm_compute::test::get_format_for_channel().
 {
     fill(std::forward<T>(tensor), name, get_format_for_channel(channel), channel);
 }
void fill (RawTensor & raw, const std::string & name, Channel channel) const
Fills the raw tensor with the content of the specified channel extracted from the given image.
Parameters
[in,out] raw To be filled raw tensor.
[in] name Image file used to fill the tensor.
[in] channel Channel of the image used to fill the tensor.
Note
The channel has to be unambiguous so that the format can be inferred automatically.
Warning
No check is performed that the specified format actually matches the format of the tensor.
Definition at line 229 of file TensorLibrary.cpp.
References TensorLibrary::fill(), and arm_compute::test::get_format_for_channel().
 {
     fill(raw, name, get_format_for_channel(channel), channel);
 }
void fill (T && tensor, const std::string & name, Format format, Channel channel) const
Fills the specified tensor with the content of the specified channel extracted from the given image after it has been converted to the given format.
Parameters
[in,out] tensor To be filled tensor.
[in] name Image file used to fill the tensor.
[in] format Format of the image used to fill the tensor.
[in] channel Channel of the image used to fill the tensor.
Warning
No check is performed that the specified format actually matches the format of the tensor.
Definition at line 422 of file TensorLibrary.h.
References RawTensor::data(), RawTensor::element_size(), arm_compute::test::index2coord(), offset(), RawTensor::shape(), and RawTensor::size().
 {
     const RawTensor &raw = get(name, format, channel);
     for(size_t offset = 0; offset < raw.size(); offset += raw.element_size())
     {
         const Coordinates id = index2coord(raw.shape(), offset / raw.element_size());
         const RawTensor::BufferType *const raw_ptr = raw.data() + offset;
         const auto                         out_ptr = static_cast<RawTensor::BufferType *>(tensor(id));
         std::copy_n(raw_ptr, raw.element_size(), out_ptr);
     }
 }
void fill (RawTensor & raw, const std::string & name, Format format, Channel channel) const
Fills the raw tensor with the content of the specified channel extracted from the given image after it has been converted to the given format.
Parameters
[in,out] raw To be filled raw tensor.
[in] name Image file used to fill the tensor.
[in] format Format of the image used to fill the tensor.
[in] channel Channel of the image used to fill the tensor.
Warning
No check is performed that the specified format actually matches the format of the tensor.
Definition at line 234 of file TensorLibrary.cpp.
References TensorCache::add(), RawTensor::data(), TensorCache::find(), RawTensor::format(), arm_compute::G, arm_compute::test::get_channel_format(), arm_compute::R, arm_compute::RGB888, arm_compute::S16, RawTensor::shape(), RawTensor::size(), arm_compute::U16, and arm_compute::U8.
 {
     const RawTensor &src = get(name, format, channel);
     std::copy_n(src.data(), raw.size(), raw.data());
 }
void fill_layer_data (T && tensor, std::string name) const
Fills the specified tensor with data loaded from binary in specified path.
Parameters
[in,out] tensor To be filled tensor.
[in] name Data file.
Definition at line 621 of file TensorLibrary.h.
References arm_compute::execute_window_loop(), Window::set(), and arm_compute::test::store_value_with_data_type().
 {
 #ifdef _WIN32
     const std::string path_separator("\\");
 #else
     const std::string path_separator("/");
 #endif
     const std::string path = _library_path + path_separator + name;
     // Open file
     std::ifstream file(path, std::ios::in | std::ios::binary);
     if(!file.good())
     {
         throw std::runtime_error("Could not load binary data: " + path);
     }
     Window window;
     for(unsigned int d = 0; d < tensor.shape().num_dimensions(); ++d)
     {
         window.set(d, Window::Dimension(0, tensor.shape()[d], 1));
     }
     execute_window_loop(window, [&](const Coordinates & id)
     {
         float val;
         file.read(reinterpret_cast<char *>(&val), sizeof(float));
         void *const out_ptr = tensor(id);
         store_value_with_data_type(out_ptr, val, tensor.data_type());
     });
 }
void fill_tensor_uniform (T && tensor, std::random_device::result_type seed_offset) const
Fill a tensor with uniform distribution across the range of its type.
Parameters
[in,out] tensor To be filled tensor.
[in] seed_offset The offset will be added to the global seed before initialising the random generator.
Definition at line 437 of file TensorLibrary.h.
References ARM_COMPUTE_ERROR, arm_compute::F16, arm_compute::F32, arm_compute::F64, TensorLibrary::fill(), arm_compute::test::fixed_point_arithmetic::detail::max(), arm_compute::QS8, arm_compute::S16, arm_compute::S32, arm_compute::S64, arm_compute::S8, arm_compute::SIZET, arm_compute::U16, arm_compute::U32, arm_compute::U64, and arm_compute::U8.
 {
     switch(tensor.data_type())
     {
         case DataType::U8:
         {
             std::uniform_int_distribution<uint8_t> distribution_u8(std::numeric_limits<uint8_t>::lowest(), std::numeric_limits<uint8_t>::max());
             fill(tensor, distribution_u8, seed_offset);
             break;
         }
         case DataType::S8:
         case DataType::QS8:
         {
             std::uniform_int_distribution<int8_t> distribution_s8(std::numeric_limits<int8_t>::lowest(), std::numeric_limits<int8_t>::max());
             fill(tensor, distribution_s8, seed_offset);
             break;
         }
         case DataType::U16:
         {
             std::uniform_int_distribution<uint16_t> distribution_u16(std::numeric_limits<uint16_t>::lowest(), std::numeric_limits<uint16_t>::max());
             fill(tensor, distribution_u16, seed_offset);
             break;
         }
         case DataType::S16:
         {
             std::uniform_int_distribution<int16_t> distribution_s16(std::numeric_limits<int16_t>::lowest(), std::numeric_limits<int16_t>::max());
             fill(tensor, distribution_s16, seed_offset);
             break;
         }
         case DataType::U32:
         {
             std::uniform_int_distribution<uint32_t> distribution_u32(std::numeric_limits<uint32_t>::lowest(), std::numeric_limits<uint32_t>::max());
             fill(tensor, distribution_u32, seed_offset);
             break;
         }
         case DataType::S32:
         {
             std::uniform_int_distribution<int32_t> distribution_s32(std::numeric_limits<int32_t>::lowest(), std::numeric_limits<int32_t>::max());
             fill(tensor, distribution_s32, seed_offset);
             break;
         }
         case DataType::U64:
         {
             std::uniform_int_distribution<uint64_t> distribution_u64(std::numeric_limits<uint64_t>::lowest(), std::numeric_limits<uint64_t>::max());
             fill(tensor, distribution_u64, seed_offset);
             break;
         }
         case DataType::S64:
         {
             std::uniform_int_distribution<int64_t> distribution_s64(std::numeric_limits<int64_t>::lowest(), std::numeric_limits<int64_t>::max());
             fill(tensor, distribution_s64, seed_offset);
             break;
         }
 #ifdef ENABLE_FP16
         case DataType::F16:
         {
             std::uniform_real_distribution<float16_t> distribution_f16(std::numeric_limits<float16_t>::lowest(), std::numeric_limits<float16_t>::max());
             fill(tensor, distribution_f16, seed_offset);
             break;
         }
 #endif
         case DataType::F32:
         {
             // It doesn't make sense to check [-inf, inf], so hard code it to a big number
             std::uniform_real_distribution<float> distribution_f32(-1000.f, 1000.f);
             fill(tensor, distribution_f32, seed_offset);
             break;
         }
         case DataType::F64:
         {
             // It doesn't make sense to check [-inf, inf], so hard code it to a big number
             std::uniform_real_distribution<double> distribution_f64(-1000.f, 1000.f);
             fill(tensor, distribution_f64, seed_offset);
             break;
         }
         case DataType::SIZET:
         {
             std::uniform_int_distribution<size_t> distribution_sizet(std::numeric_limits<size_t>::lowest(), std::numeric_limits<size_t>::max());
             fill(tensor, distribution_sizet, seed_offset);
             break;
         }
         default:
             ARM_COMPUTE_ERROR("NOT SUPPORTED!");
     }
 }
void fill_tensor_uniform (T && tensor, std::random_device::result_type seed_offset, D low, D high) const
Fill a tensor with uniform distribution across the a specified range.
Parameters
[in,out] tensor To be filled tensor.
[in] seed_offset The offset will be added to the global seed before initialising the random generator.
[in] low lowest value in the range (inclusive)
[in] high highest value in the range (inclusive)
Note
low and high must be of the same type as the data type of tensor
Definition at line 524 of file TensorLibrary.h.
References ARM_COMPUTE_ERROR, ARM_COMPUTE_ERROR_ON, arm_compute::F16, arm_compute::F32, arm_compute::F64, TensorLibrary::fill(), arm_compute::QS8, arm_compute::S16, arm_compute::S32, arm_compute::S64, arm_compute::S8, arm_compute::SIZET, arm_compute::U16, arm_compute::U32, arm_compute::U64, and arm_compute::U8.
 {
     switch(tensor.data_type())
     {
         case DataType::U8:
         {
             ARM_COMPUTE_ERROR_ON(!(std::is_same<uint8_t, D>::value));
             std::uniform_int_distribution<uint8_t> distribution_u8(low, high);
             fill(tensor, distribution_u8, seed_offset);
             break;
         }
         case DataType::S8:
         case DataType::QS8:
         {
             ARM_COMPUTE_ERROR_ON(!(std::is_same<int8_t, D>::value));
             std::uniform_int_distribution<int8_t> distribution_s8(low, high);
             fill(tensor, distribution_s8, seed_offset);
             break;
         }
         case DataType::U16:
         {
             ARM_COMPUTE_ERROR_ON(!(std::is_same<uint16_t, D>::value));
             std::uniform_int_distribution<uint16_t> distribution_u16(low, high);
             fill(tensor, distribution_u16, seed_offset);
             break;
         }
         case DataType::S16:
         {
             ARM_COMPUTE_ERROR_ON(!(std::is_same<int16_t, D>::value));
             std::uniform_int_distribution<int16_t> distribution_s16(low, high);
             fill(tensor, distribution_s16, seed_offset);
             break;
         }
         case DataType::U32:
         {
             ARM_COMPUTE_ERROR_ON(!(std::is_same<uint32_t, D>::value));
             std::uniform_int_distribution<uint32_t> distribution_u32(low, high);
             fill(tensor, distribution_u32, seed_offset);
             break;
         }
         case DataType::S32:
         {
             ARM_COMPUTE_ERROR_ON(!(std::is_same<int32_t, D>::value));
             std::uniform_int_distribution<int32_t> distribution_s32(low, high);
             fill(tensor, distribution_s32, seed_offset);
             break;
         }
         case DataType::U64:
         {
             ARM_COMPUTE_ERROR_ON(!(std::is_same<uint64_t, D>::value));
             std::uniform_int_distribution<uint64_t> distribution_u64(low, high);
             fill(tensor, distribution_u64, seed_offset);
             break;
         }
         case DataType::S64:
         {
             ARM_COMPUTE_ERROR_ON(!(std::is_same<int64_t, D>::value));
             std::uniform_int_distribution<int64_t> distribution_s64(low, high);
             fill(tensor, distribution_s64, seed_offset);
             break;
         }
 #if ENABLE_FP16
         case DataType::F16:
         {
             ARM_COMPUTE_ERROR_ON(!(std::is_same<float16_t, D>::value));
             std::uniform_real_distribution<float16_t> distribution_f16(low, high);
             fill(tensor, distribution_f16, seed_offset);
             break;
         }
 #endif
         case DataType::F32:
         {
             ARM_COMPUTE_ERROR_ON(!(std::is_same<float, D>::value));
             std::uniform_real_distribution<float> distribution_f32(low, high);
             fill(tensor, distribution_f32, seed_offset);
             break;
         }
         case DataType::F64:
         {
             ARM_COMPUTE_ERROR_ON(!(std::is_same<double, D>::value));
             std::uniform_real_distribution<double> distribution_f64(low, high);
             fill(tensor, distribution_f64, seed_offset);
             break;
         }
         case DataType::SIZET:
         {
             ARM_COMPUTE_ERROR_ON(!(std::is_same<size_t, D>::value));
             std::uniform_int_distribution<size_t> distribution_sizet(low, high);
             fill(tensor, distribution_sizet, seed_offset);
             break;
         }
         default:
             ARM_COMPUTE_ERROR("NOT SUPPORTED!");
     }
 }
RawTensor get (const TensorShape & shape, DataType data_type, int num_channels = 1, int fixed_point_position = 0) static
Creates an uninitialised raw tensor with the given shape, data_type and num_channels.
Parameters
[in] shape Shape used to initialise the tensor.
[in] data_type Data type used to initialise the tensor.
[in] num_channels (Optional) Number of channels used to initialise the tensor.
[in] fixed_point_position (Optional) Number of bits for the fractional part of the fixed point numbers
Definition at line 413 of file TensorLibrary.cpp.
 {
     return RawTensor(shape, data_type, num_channels, fixed_point_position);
 }
RawTensor get (const TensorShape & shape, Format format) static
Creates an uninitialised raw tensor with the given shape and format.
Parameters
[in] shape Shape used to initialise the tensor.
[in] format Format used to initialise the tensor.
Definition at line 418 of file TensorLibrary.cpp.
 {
     return RawTensor(shape, format);
 }
const RawTensor & get (const std::string & name) const
Provides a contant raw tensor for the specified image.
Parameters
[in] name Image file used to look up the raw tensor.
Definition at line 423 of file TensorLibrary.cpp.
References arm_compute::RGB888.
 {
     return find_or_create_raw_tensor(name, Format::RGB888);
 }
RawTensor get (const std::string & name)
Provides a raw tensor for the specified image.
Parameters
[in] name Image file used to look up the raw tensor.
Definition at line 428 of file TensorLibrary.cpp.
References arm_compute::RGB888.
 {
     return RawTensor(find_or_create_raw_tensor(name, Format::RGB888));
 }
RawTensor get (const std::string & name, DataType data_type, int num_channels = 1) const
Creates an uninitialised raw tensor with the given data_type and num_channels.
The shape is derived from the specified image.
Parameters
[in] name Image file used to initialise the tensor.
[in] data_type Data type used to initialise the tensor.
[in] num_channels Number of channels used to initialise the tensor.
Definition at line 433 of file TensorLibrary.cpp.
References RawTensor::shape().
 {
     const RawTensor &raw = get(name);
     return RawTensor(raw.shape(), data_type, num_channels);
 }
const RawTensor & get (const std::string & name, Format format) const
Provides a contant raw tensor for the specified image after it has been converted to format.
Parameters
[in] name Image file used to look up the raw tensor.
[in] format Format used to look up the raw tensor.
Definition at line 440 of file TensorLibrary.cpp.
 {
     return find_or_create_raw_tensor(name, format);
 }
RawTensor get (const std::string & name, Format format)
Provides a raw tensor for the specified image after it has been converted to format.
Parameters
[in] name Image file used to look up the raw tensor.
[in] format Format used to look up the raw tensor.
Definition at line 445 of file TensorLibrary.cpp.
 {
     return RawTensor(find_or_create_raw_tensor(name, format));
 }
const RawTensor & get (const std::string & name, Channel channel) const
Provides a contant raw tensor for the specified channel after it has been extracted form the given image.
Parameters
[in] name Image file used to look up the raw tensor.
[in] channel Channel used to look up the raw tensor.
Note
The channel has to be unambiguous so that the format can be inferred automatically.
Definition at line 450 of file TensorLibrary.cpp.
References arm_compute::test::get_format_for_channel().
 {
     return get(name, get_format_for_channel(channel), channel);
 }
RawTensor get (const std::string & name, Channel channel)
Provides a raw tensor for the specified channel after it has been extracted form the given image.
Parameters
[in] name Image file used to look up the raw tensor.
[in] channel Channel used to look up the raw tensor.
Note
The channel has to be unambiguous so that the format can be inferred automatically.
Definition at line 455 of file TensorLibrary.cpp.
References arm_compute::test::get_format_for_channel().
 {
     return RawTensor(get(name, get_format_for_channel(channel), channel));
 }
const RawTensor & get (const std::string & name, Format format, Channel channel) const
Provides a constant raw tensor for the specified channel after it has been extracted form the given image formatted to format.
Parameters
[in] name Image file used to look up the raw tensor.
[in] format Format used to look up the raw tensor.
[in] channel Channel used to look up the raw tensor.
Definition at line 460 of file TensorLibrary.cpp.
 {
     return find_or_create_raw_tensor(name, format, channel);
 }
RawTensor get (const std::string & name, Format format, Channel channel)
Provides a raw tensor for the specified channel after it has been extracted form the given image formatted to format.
Parameters
[in] name Image file used to look up the raw tensor.
[in] format Format used to look up the raw tensor.
[in] channel Channel used to look up the raw tensor.
Definition at line 465 of file TensorLibrary.cpp.
 {
     return RawTensor(find_or_create_raw_tensor(name, format, channel));
 }
std::random_device::result_type seed () const
Seed that is used to fill tensors with random values.
Definition at line 218 of file TensorLibrary.cpp.
 {
     return _seed;
 }
The documentation for this class was generated from the following files:
tests/TensorLibrary.h
tests/TensorLibrary.cpp