Compute Library: SoftmaxLayer Class Reference
SoftmaxLayer Class Reference final
Softmax Layer.
#include <Layers.h>
Public Member Functions
SoftmaxLayer (float beta=1.0f)
Construct a softmax layer.
NodeID create_layer (IStream &s) override
Create layer and add to the given stream.
Public Member Functions inherited from ILayer
virtual ~ILayer ()=default
Default destructor.
ILayer & set_name (std::string name)
Sets the name of the layer.
const std::string & name () const
Layer name accessor.
Detailed Description
Softmax Layer.
Definition at line 1071 of file Layers.h.
Constructor & Destructor Documentation
SoftmaxLayer()
SoftmaxLayer (float beta = 1.0f) inline
Construct a softmax layer.
Parameters
[in] beta (Optional) Beta value. Default 1.0.
Definition at line 1078 of file Layers.h.
         : _beta(beta)
     {
     }
Member Function Documentation
create_layer()
NodeID create_layer (IStream & s) inline override virtual
Create layer and add to the given stream.
Parameters
[in] s Stream to add layer to.
Returns
ID of the created node.
Implements ILayer.
Definition at line 1083 of file Layers.h.
     {
         NodeParams  common_params = { name(), s.hints().target_hint };
         NodeIdxPair input         = { s.tail_node(), 0 };
         return GraphBuilder::add_softmax_node(s.graph(), common_params, input, _beta);
     }
References GraphBuilder::add_softmax_node(), IStream::graph(), IStream::hints(), ILayer::name(), IStream::tail_node(), and StreamHints::target_hint.
The documentation for this class was generated from the following file:
arm_compute/graph/frontend/Layers.h