Compute Library: TestCaseRegistrar< T > Class Template Reference
TestCaseRegistrar< T > Class Template Reference final
Helper class to statically register a test case.
#include <Registrars.h>
Public Member Functions
TestCaseRegistrar (std::string test_name, DatasetMode mode, TestCaseFactory::Status status)
Add a new test case with the given name to the framework.
template<typename D >
TestCaseRegistrar (std::string test_name, DatasetMode mode, TestCaseFactory::Status status, D &&dataset)
Add a new data test case with the given name to the framework.
Detailed Description
template<typename T>
class arm_compute::test::framework::detail::TestCaseRegistrar< T >
Helper class to statically register a test case.
Definition at line 43 of file Registrars.h.
Constructor & Destructor Documentation
TestCaseRegistrar() [1/2]
TestCaseRegistrar (std::string test_name, DatasetMode mode, TestCaseFactory::Status status) inline
Add a new test case with the given name to the framework.
Parameters
[in] test_name Name of the test case.
[in] mode Mode in which the test should be activated.
[in] status Status of the test case.
Definition at line 80 of file Registrars.h.
 {
     Framework::get().add_test_case<T>(std::move(test_name), mode, status);
 }
References Framework::add_test_case(), and Framework::get().
TestCaseRegistrar() [2/2]
TestCaseRegistrar (std::string test_name, DatasetMode mode, TestCaseFactory::Status status, D && dataset) inline
Add a new data test case with the given name to the framework.
Parameters
[in] test_name Name of the test case.
[in] mode Mode in which the test should be activated.
[in] status Status of the test case.
[in] dataset Dataset used as input for the test case.
Definition at line 87 of file Registrars.h.
 {
     auto it = dataset.begin();
     for(int i = 0; i < dataset.size(); ++i, ++it)
     {
         // WORKAROUND for GCC 4.9
         // The last argument should be *it to pass just the data and not the
         // iterator.
         Framework::get().add_data_test_case<T>(test_name, mode, status, it.description(), it);
     }
 }
References Framework::add_data_test_case(), and Framework::get().
The documentation for this class was generated from the following file:
tests/framework/Registrars.h