Compute Library: BufferManager Class Reference
BufferManager Class Reference
#include <buffer_manager.hpp>
Public Member Functions
BufferManager (BufferManager &)=delete
BufferManager & operator= (BufferManager &)=delete
BufferManager (const int maxthreads, const size_t buffersize, void *storage)
~BufferManager ()
template<typename T >
void * get (const int index, T func)
template<typename T >
void try_populate (const int index, T func)
void release (const int index)
void set_nthreads (int threads)
Static Public Member Functions
static size_t get_storage_requirement (const int maxthreads, const size_t buffersize)
Detailed Description
Definition at line 205 of file buffer_manager.hpp.
Constructor & Destructor Documentation
BufferManager() [1/2]
BufferManager (BufferManager &) delete
BufferManager() [2/2]
BufferManager (const int maxthreads, const size_t buffersize, void * storage) inline
Definition at line 222 of file buffer_manager.hpp.
                                                                                 : _maxthreads(maxthreads), _storage(storage) {
         const int numbuffers = (maxthreads == 1) ? 1 : 3;
         /* We don't need any Buffer objects in single thread mode. */
         if (_maxthreads == 1) {
             return;
         }
         /* Use intptr_t to avoid performing arithmetic on a void * */
         intptr_t storage_int = reinterpret_cast<intptr_t>(_storage);
         for (int i=0; i<numbuffers; i++) {
             _buffers.push_back(new Buffer(reinterpret_cast<void *>(storage_int), _maxthreads));
             storage_int += buffersize;
         }
     }
~BufferManager()
~BufferManager () inline
Definition at line 239 of file buffer_manager.hpp.
                      {
         while (_buffers.size()) {
             delete _buffers.back();
             _buffers.pop_back();
         }
     }
Member Function Documentation
get()
void* get (const int index, T func) inline
Definition at line 247 of file buffer_manager.hpp.
{
         /* In single thread mode, we just directly call the populating
          * function on the (single) buffer, otherwise forward to the
          * relevant Buffer.  */
         if (_maxthreads==1) {
             func(_storage);
             return _storage;
         } else {
             return _buffers[index % _buffers.size()]->get(index, func);
         }
     }
get_storage_requirement()
static size_t get_storage_requirement (const int maxthreads, const size_t buffersize) inline static
Definition at line 218 of file buffer_manager.hpp.
{
         return buffersize * ((maxthreads == 1) ? 1 : 3);
     }
Referenced by GemmInterleaved< strategy, To, Tr >::get_working_size(), and GemmInterleaved< strategy, To, Tr >::set_working_space().
operator=()
BufferManager& operator= (BufferManager &) delete
release()
void release (const int index) inline
Definition at line 269 of file buffer_manager.hpp.
{
         /* No need for this in single thread mode. */
         if (_maxthreads==1) {
             return;
         }
         _buffers[index % _buffers.size()]->release();
     }
set_nthreads()
void set_nthreads (int threads) inline
Definition at line 278 of file buffer_manager.hpp.
{
         if (_maxthreads==1) {
             return;
         }
         for(unsigned int i=0; i<_buffers.size(); i++) {
             _buffers[i]->set_numusers(threads);
         }
     }
Referenced by GemmInterleaved< strategy, To, Tr >::set_nthreads().
try_populate()
void try_populate (const int index, T func) inline
Definition at line 260 of file buffer_manager.hpp.
{
         /* No need for this in single thread mode. */
         if (_maxthreads==1) {
             return;
         }
         _buffers[index % _buffers.size()]->try_populate(index, func);
     }
The documentation for this class was generated from the following file:
src/core/NEON/kernels/arm_gemm/buffer_manager.hpp