Compute Library: src/core/CL/cl_kernels/convolution3x3.cl File Reference
convolution3x3.cl File Reference
#include "helpers.h"
Macros
#define DATA_TYPE short
#define DATA_TYPE_OUT uchar
Functions
short8 convolution1x3 (__global const uchar *left_pixel, const short left_coeff, const short middle_coeff, const short right_coeff)
Compute a 1D horizontal convolution of size 3 for 8 bytes assuming the input is made of 1 channel of 1 byte (i.e 8 pixels).
short8 convolution3x3 (Image *src, const short mat0, const short mat1, const short mat2, const short mat3, const short mat4, const short mat5, const short mat6, const short mat7, const short mat8, uint scale)
Apply a 3x3 convolution matrix to a single channel U8 input image and return the result.
__kernel void convolution3x3_static (__global uchar *src_ptr, uint src_stride_x, uint src_step_x, uint src_stride_y, uint src_step_y, uint src_offset_first_element_in_bytes, __global uchar *dst_ptr, uint dst_stride_x, uint dst_step_x, uint dst_stride_y, uint dst_step_y, uint dst_offset_first_element_in_bytes)
Apply a 3x3 static convolution matrix to a single channel U8 input image and output a single channel image.
Macro Definition Documentation
DATA_TYPE
#define DATA_TYPE short
Definition at line 27 of file convolution3x3.cl.
DATA_TYPE_OUT
#define DATA_TYPE_OUT uchar
Definition at line 31 of file convolution3x3.cl.
Function Documentation
convolution1x3()
short8 convolution1x3 (__global const uchar * left_pixel, const short left_coeff, const short middle_coeff, const short right_coeff) inline
Compute a 1D horizontal convolution of size 3 for 8 bytes assuming the input is made of 1 channel of 1 byte (i.e 8 pixels).
Parameters
[in] left_pixel Pointer to the left pixel.
[in] left_coeff Weight of the left pixel
[in] middle_coeff Weight of the middle pixel
[in] right_coeff Weight of the right pixel
Returns
a short8 containing 8 convoluted values.
Definition at line 43 of file convolution3x3.cl.
 {
     uchar16 temp = vload16(0, left_pixel);
     VEC_DATA_TYPE(DATA_TYPE, 8)
     left = CONVERT(temp.s01234567, VEC_DATA_TYPE(DATA_TYPE, 8));
     VEC_DATA_TYPE(DATA_TYPE, 8)
     middle = CONVERT(temp.s12345678, VEC_DATA_TYPE(DATA_TYPE, 8));
     VEC_DATA_TYPE(DATA_TYPE, 8)
     right = CONVERT(temp.s23456789, VEC_DATA_TYPE(DATA_TYPE, 8));
     return left * (VEC_DATA_TYPE(DATA_TYPE, 8))left_coeff + middle * (VEC_DATA_TYPE(DATA_TYPE, 8))middle_coeff + right * (VEC_DATA_TYPE(DATA_TYPE, 8))right_coeff;
 }
References CONVERT, DATA_TYPE, and VEC_DATA_TYPE.
Referenced by convolution3x3(), and convolution_rectangle().
convolution3x3()
short8 convolution3x3 (Image * src, const short mat0, const short mat1, const short mat2, const short mat3, const short mat4, const short mat5, const short mat6, const short mat7, const short mat8, uint scale) inline
Apply a 3x3 convolution matrix to a single channel U8 input image and return the result.
Convolution matrix layout:
[ mat0, mat1, mat2 ]
[ mat3, mat4, mat5 ]
[ mat6, mat7, mat8 ]
Parameters
[in] src A pointer to source Image structure
[in] mat0 Coefficient from the convolution matrix
[in] mat1 Coefficient from the convolution matrix
[in] mat2 Coefficient from the convolution matrix
[in] mat3 Coefficient from the convolution matrix
[in] mat4 Coefficient from the convolution matrix
[in] mat5 Coefficient from the convolution matrix
[in] mat6 Coefficient from the convolution matrix
[in] mat7 Coefficient from the convolution matrix
[in] mat8 Coefficient from the convolution matrix
[in] scale Convolution matrix scale (Sum of the coefficients, or 1 if the sum is 0)
Returns
a short8 containing 8 convoluted and scaled values.
Definition at line 81 of file convolution3x3.cl.
 {
     // Output pixels
     VEC_DATA_TYPE(DATA_TYPE, 8)
     pixels;
     // Row 0
     pixels = convolution1x3(offset(src, -1, -1), mat0, mat1, mat2);
     // Row
     pixels += convolution1x3(offset(src, -1, 0), mat3, mat4, mat5);
     // Row 2
     pixels += convolution1x3(offset(src, -1, 1), mat6, mat7, mat8);
     // Divide by the scale
     return pixels / (VEC_DATA_TYPE(DATA_TYPE, 8))scale;
 }
References convolution1x3(), DATA_TYPE, offset(), arm_compute::test::validation::scale, arm_compute::test::validation::src, and VEC_DATA_TYPE.
Referenced by convolution3x3_static().
convolution3x3_static()
__kernel void convolution3x3_static (__global uchar * src_ptr, uint src_stride_x, uint src_step_x, uint src_stride_y, uint src_step_y, uint src_offset_first_element_in_bytes, __global uchar * dst_ptr, uint dst_stride_x, uint dst_step_x, uint dst_stride_y, uint dst_step_y, uint dst_offset_first_element_in_bytes)
Apply a 3x3 static convolution matrix to a single channel U8 input image and output a single channel image.
Attention
The matrix coefficients(MAT0, MAT1, ... MAT8, SCALE), DATA_TYPE, and DATA_TYPE_OUT need to be passed at compile time.
e.g. -DMAT0=1 -DMAT2=2, ...-DMAT8=8, -DSCALE=1, -DDATA_TYPE=int, -DDATA_TYPE_OUT=int
Parameters
[in] src_ptr Pointer to the source image
[in] src_stride_x Stride of the source image in X dimension (in bytes)
[in] src_step_x src_stride_x * number of elements along X processed per workitem(in bytes)
[in] src_stride_y Stride of the source image in Y dimension (in bytes)
[in] src_step_y src_stride_y * number of elements along Y processed per workitem(in bytes)
[in] src_offset_first_element_in_bytes The offset of the first element in the source image
[out] dst_ptr Pointer to the destination image. Supported data types: U8, S16
[in] dst_stride_x Stride of the destination image in X dimension (in bytes)
[in] dst_step_x dst_stride_x * number of elements along X processed per workitem(in bytes)
[in] dst_stride_y Stride of the destination image in Y dimension (in bytes)
[in] dst_step_y dst_stride_y * number of elements along Y processed per workitem(in bytes)
[in] dst_offset_first_element_in_bytes The offset of the first element in the destination image
Definition at line 122 of file convolution3x3.cl.
 {
     Image src = CONVERT_TO_IMAGE_STRUCT(src);
     Image dst = CONVERT_TO_IMAGE_STRUCT(dst);
     VEC_DATA_TYPE(DATA_TYPE, 8)
     pixels = convolution3x3(&src,
                             MAT0, MAT1, MAT2, MAT3, MAT4, MAT5, MAT6, MAT7, MAT8, SCALE);
     // Store the result as is in dst
     vstore8(CONVERT_SAT(pixels, VEC_DATA_TYPE(DATA_TYPE_OUT, 8)), 0, (__global DATA_TYPE_OUT *)dst.ptr);
 }
References CONVERT_SAT, CONVERT_TO_IMAGE_STRUCT, convolution3x3(), DATA_TYPE, DATA_TYPE_OUT, arm_compute::test::validation::dst, arm_compute::test::validation::src, and VEC_DATA_TYPE.