Compute Library: src/core/CL/cl_kernels/convolution5x5.cl File Reference
convolution5x5.cl File Reference
#include "helpers.h"
Macros
#define DATA_TYPE short
#define COMPUTE_TYPE int
#define DATA_TYPE_OUT uchar
Functions
short8 convolution1x5 (__global const uchar *left_pixel, const short left1_coeff, const short left2_coeff, const short middle_coeff, const short right1_coeff, const short right2_coeff)
Compute a 1D horizontal convolution of size 5 for 8 bytes assuming the input is made of 1 channel of 1 byte (i.e 8 pixels).
int8 convolution5x1 (Image *src, const short up1_coeff, const short up2_coeff, const short middle_coeff, const short down1_coeff, const short down2_coeff)
Compute a 1D vertical convolution of size 5 for 8 bytes assuming the input is made of 1 channel of 1 byte (i.e 8 pixels).
short8 convolution5x5 (Image *src, const short mat0, const short mat1, const short mat2, const short mat3, const short mat4, const short mat5, const short mat6, const short mat7, const short mat8, const short mat9, const short mat10, const short mat11, const short mat12, const short mat13, const short mat14, const short mat15, const short mat16, const short mat17, const short mat18, const short mat19, const short mat20, const short mat21, const short mat22, const short mat23, const short mat24, uint scale)
Apply a 5x5 convolution matrix to a single channel U8 input image and return the result.
__kernel void convolution_separable1x5_static (__global uchar *src_ptr, uint src_stride_x, uint src_step_x, uint src_stride_y, uint src_step_y, uint src_offset_first_element_in_bytes, __global uchar *dst_ptr, uint dst_stride_x, uint dst_step_x, uint dst_stride_y, uint dst_step_y, uint dst_offset_first_element_in_bytes)
Apply a 1x5 static convolution matrix to a single channel U8 input image and output a single temporary channel image(Support U16, S16, S32).
__kernel void convolution_separable5x1_static (__global uchar *src_ptr, uint src_stride_x, uint src_step_x, uint src_stride_y, uint src_step_y, uint src_offset_first_element_in_bytes, __global uchar *dst_ptr, uint dst_stride_x, uint dst_step_x, uint dst_stride_y, uint dst_step_y, uint dst_offset_first_element_in_bytes)
Apply a 5x1 static convolution matrix to a single channel U8 input image and output a single channel image.
__kernel void convolution5x5_static (__global uchar *src_ptr, uint src_stride_x, uint src_step_x, uint src_stride_y, uint src_step_y, uint src_offset_first_element_in_bytes, __global uchar *dst_ptr, uint dst_stride_x, uint dst_step_x, uint dst_stride_y, uint dst_step_y, uint dst_offset_first_element_in_bytes)
Apply a static 5x5 convolution matrix to a single channel U8 input image and output a single channel image including borders.
Macro Definition Documentation
COMPUTE_TYPE
#define COMPUTE_TYPE int
Definition at line 31 of file convolution5x5.cl.
DATA_TYPE
#define DATA_TYPE short
Definition at line 27 of file convolution5x5.cl.
DATA_TYPE_OUT
#define DATA_TYPE_OUT uchar
Definition at line 35 of file convolution5x5.cl.
Function Documentation
convolution1x5()
short8 convolution1x5 (__global const uchar * left_pixel, const short left1_coeff, const short left2_coeff, const short middle_coeff, const short right1_coeff, const short right2_coeff)
Compute a 1D horizontal convolution of size 5 for 8 bytes assuming the input is made of 1 channel of 1 byte (i.e 8 pixels).
Parameters
[in] left_pixel Pointer to the left pixel
[in] left1_coeff Weight of the most left pixel
[in] left2_coeff Weight of the left pixel
[in] middle_coeff Weight of the middle pixel
[in] right1_coeff Weight of the right pixel
[in] right2_coeff Weight of the most right pixel
Returns
a short8 containing 8 convoluted values.
Definition at line 50 of file convolution5x5.cl.
 {
     uchar16 temp = vload16(0, left_pixel);
     VEC_DATA_TYPE(DATA_TYPE, 8)
     left1 = CONVERT(temp.s01234567, VEC_DATA_TYPE(DATA_TYPE, 8));
     VEC_DATA_TYPE(DATA_TYPE, 8)
     left2 = CONVERT(temp.s12345678, VEC_DATA_TYPE(DATA_TYPE, 8));
     VEC_DATA_TYPE(DATA_TYPE, 8)
     middle = CONVERT(temp.s23456789, VEC_DATA_TYPE(DATA_TYPE, 8));
     VEC_DATA_TYPE(DATA_TYPE, 8)
     right1 = CONVERT(temp.s3456789a, VEC_DATA_TYPE(DATA_TYPE, 8));
     VEC_DATA_TYPE(DATA_TYPE, 8)
     right2 = CONVERT(temp.s456789ab, VEC_DATA_TYPE(DATA_TYPE, 8));
     return left1 * (VEC_DATA_TYPE(DATA_TYPE, 8))left1_coeff + left2 * (VEC_DATA_TYPE(DATA_TYPE, 8))left2_coeff
            + middle * (VEC_DATA_TYPE(DATA_TYPE, 8))middle_coeff + right1 * (VEC_DATA_TYPE(DATA_TYPE, 8))right1_coeff + right2 * (VEC_DATA_TYPE(DATA_TYPE, 8))right2_coeff;
 }
References CONVERT, DATA_TYPE, and VEC_DATA_TYPE.
Referenced by convolution5x5(), convolution_rectangle(), and convolution_separable1x5_static().
convolution5x1()
int8 convolution5x1 (Image * src, const short up1_coeff, const short up2_coeff, const short middle_coeff, const short down1_coeff, const short down2_coeff)
Compute a 1D vertical convolution of size 5 for 8 bytes assuming the input is made of 1 channel of 1 byte (i.e 8 pixels).
Parameters
[in] src Pointer to source image.
[in] up1_coeff Weight of the most up pixel
[in] up2_coeff Weight of the up pixel
[in] middle_coeff Weight of the middle pixel
[in] down1_coeff Weight of the down pixel
[in] down2_coeff Weight of the most down pixel
Returns
a short8 containing 8 convoluted values.
Definition at line 87 of file convolution5x5.cl.
 {
     VEC_DATA_TYPE(COMPUTE_TYPE, 8)
     val;
     VEC_DATA_TYPE(COMPUTE_TYPE, 8)
     out = (VEC_DATA_TYPE(COMPUTE_TYPE, 8))0;
     val = CONVERT(vload8(0, (__global DATA_TYPE *)offset(src, 0, -2)), VEC_DATA_TYPE(COMPUTE_TYPE, 8));
     out += val * (VEC_DATA_TYPE(COMPUTE_TYPE, 8))up1_coeff;
     val = CONVERT(vload8(0, (__global DATA_TYPE *)offset(src, 0, -1)), VEC_DATA_TYPE(COMPUTE_TYPE, 8));
     out += val * (VEC_DATA_TYPE(COMPUTE_TYPE, 8))up2_coeff;
     val = CONVERT(vload8(0, (__global DATA_TYPE *)offset(src, 0, 0)), VEC_DATA_TYPE(COMPUTE_TYPE, 8));
     out += val * (VEC_DATA_TYPE(COMPUTE_TYPE, 8))middle_coeff;
     val = CONVERT(vload8(0, (__global DATA_TYPE *)offset(src, 0, 1)), VEC_DATA_TYPE(COMPUTE_TYPE, 8));
     out += val * (VEC_DATA_TYPE(COMPUTE_TYPE, 8))down1_coeff;
     val = CONVERT(vload8(0, (__global DATA_TYPE *)offset(src, 0, 2)), VEC_DATA_TYPE(COMPUTE_TYPE, 8));
     out += val * (VEC_DATA_TYPE(COMPUTE_TYPE, 8))down2_coeff;
     return out;
 }
References COMPUTE_TYPE, CONVERT, DATA_TYPE, offset(), arm_compute::test::validation::src, and VEC_DATA_TYPE.
Referenced by convolution_separable5x1_static().
convolution5x5()
short8 convolution5x5 (Image * src, const short mat0, const short mat1, const short mat2, const short mat3, const short mat4, const short mat5, const short mat6, const short mat7, const short mat8, const short mat9, const short mat10, const short mat11, const short mat12, const short mat13, const short mat14, const short mat15, const short mat16, const short mat17, const short mat18, const short mat19, const short mat20, const short mat21, const short mat22, const short mat23, const short mat24, uint scale)
Apply a 5x5 convolution matrix to a single channel U8 input image and return the result.
Convolution matrix layout:
[ mat0, mat1, mat2, mat3 , mat4 ]
[ mat5, mat6, mat7, mat8, mat9 ]
[ mat10, mat11, mat12, mat13, mat14 ]
[ mat15, mat16, mat17, mat18, mat19 ]
[ mat20, mat21, mat22, mat23, mat24 ]
Parameters
[in] src A pointer to source Image structure.
[in] mat0 Coefficient from the convolution matrix
[in] mat1 Coefficient from the convolution matrix
[in] mat2 Coefficient from the convolution matrix
[in] mat3 Coefficient from the convolution matrix
[in] mat4 Coefficient from the convolution matrix
[in] mat5 Coefficient from the convolution matrix
[in] mat6 Coefficient from the convolution matrix
[in] mat7 Coefficient from the convolution matrix
[in] mat8 Coefficient from the convolution matrix
[in] mat9 Coefficient from the convolution matrix
[in] mat10 Coefficient from the convolution matrix
[in] mat11 Coefficient from the convolution matrix
[in] mat12 Coefficient from the convolution matrix
[in] mat13 Coefficient from the convolution matrix
[in] mat14 Coefficient from the convolution matrix
[in] mat15 Coefficient from the convolution matrix
[in] mat16 Coefficient from the convolution matrix
[in] mat17 Coefficient from the convolution matrix
[in] mat18 Coefficient from the convolution matrix
[in] mat19 Coefficient from the convolution matrix
[in] mat20 Coefficient from the convolution matrix
[in] mat21 Coefficient from the convolution matrix
[in] mat22 Coefficient from the convolution matrix
[in] mat23 Coefficient from the convolution matrix
[in] mat24 Coefficient from the convolution matrix
[in] scale Convolution matrix scale (Sum of the coefficients, or 1 if the sum is 0)
Returns
a short8 containing 8 convoluted and scaled values.
Definition at line 157 of file convolution5x5.cl.
 {
     VEC_DATA_TYPE(DATA_TYPE, 8)
     pixels;
     pixels = convolution1x5(offset(src, -2, -2), mat0, mat1, mat2, mat3, mat4);
     pixels += convolution1x5(offset(src, -2, -1), mat5, mat6, mat7, mat8, mat9);
     pixels += convolution1x5(offset(src, -2, 0), mat10, mat11, mat12, mat13, mat14);
     pixels += convolution1x5(offset(src, -2, 1), mat15, mat16, mat17, mat18, mat19);
     pixels += convolution1x5(offset(src, -2, 2), mat20, mat21, mat22, mat23, mat24);
     if(scale > 0)
     {
         pixels /= (VEC_DATA_TYPE(DATA_TYPE, 8))scale;
     }
     return convert_short8_sat(pixels);
 }
References convolution1x5(), DATA_TYPE, offset(), arm_compute::test::validation::scale, arm_compute::test::validation::src, and VEC_DATA_TYPE.
Referenced by convolution5x5_static().
convolution5x5_static()
__kernel void convolution5x5_static (__global uchar * src_ptr, uint src_stride_x, uint src_step_x, uint src_stride_y, uint src_step_y, uint src_offset_first_element_in_bytes, __global uchar * dst_ptr, uint dst_stride_x, uint dst_step_x, uint dst_stride_y, uint dst_step_y, uint dst_offset_first_element_in_bytes)
Apply a static 5x5 convolution matrix to a single channel U8 input image and output a single channel image including borders.
Attention
The matrix coefficients(MAT0, MAT1, ... MAT24, SCALE), DATA_TYPE_OUT need to be passed at compile time:
e.g. -DMAT0=1 -DMAT1=2, ... -DMAT24=24, -DSCALE=6, -DDATA_TYPE_OUT=int
Parameters
[in] src_ptr Pointer to the source image. Supported data types: U8
[in] src_stride_x Stride of the source image in X dimension (in bytes)
[in] src_step_x src_stride_x * number of elements along X processed per workitem(in bytes)
[in] src_stride_y Stride of the source image in Y dimension (in bytes)
[in] src_step_y src_stride_y * number of elements along Y processed per workitem(in bytes)
[in] src_offset_first_element_in_bytes The offset of the first element in the source image
[out] dst_ptr Pointer to the destination image. Supported data types: U8, S16
[in] dst_stride_x Stride of the destination image in X dimension (in bytes)
[in] dst_step_x dst_stride_x * number of elements along X processed per workitem(in bytes)
[in] dst_stride_y Stride of the destination image in Y dimension (in bytes)
[in] dst_step_y dst_stride_y * number of elements along Y processed per workitem(in bytes)
[in] dst_offset_first_element_in_bytes The offset of the first element in the destination image
Definition at line 272 of file convolution5x5.cl.
 {
     Image src = CONVERT_TO_IMAGE_STRUCT(src);
     Image dst = CONVERT_TO_IMAGE_STRUCT(dst);
     short8 pixels = convolution5x5(&src,
                                    MAT0, MAT1, MAT2, MAT3, MAT4, MAT5, MAT6, MAT7, MAT8, MAT9, MAT10, MAT11, MAT12, MAT13,
                                    MAT14, MAT15, MAT16, MAT17, MAT18, MAT19, MAT20, MAT21, MAT22, MAT23, MAT24, SCALE);
     // Store the result as is in dst
     vstore8(CONVERT_SAT(pixels, VEC_DATA_TYPE(DATA_TYPE_OUT, 8)), 0, (__global DATA_TYPE_OUT *)dst.ptr);
 }
References CONVERT_SAT, CONVERT_TO_IMAGE_STRUCT, convolution5x5(), DATA_TYPE_OUT, arm_compute::test::validation::dst, arm_compute::test::validation::src, and VEC_DATA_TYPE.
convolution_separable1x5_static()
__kernel void convolution_separable1x5_static (__global uchar * src_ptr, uint src_stride_x, uint src_step_x, uint src_stride_y, uint src_step_y, uint src_offset_first_element_in_bytes, __global uchar * dst_ptr, uint dst_stride_x, uint dst_step_x, uint dst_stride_y, uint dst_step_y, uint dst_offset_first_element_in_bytes)
Apply a 1x5 static convolution matrix to a single channel U8 input image and output a single temporary channel image(Support U16, S16, S32).
Attention
The matrix coefficients (MAT0, MAT1, MAT2, MAT3, MAT4) and DATA_TYPE need to be passed at compile time:
e.g. -DMAT0=1 -DMAT2=2, -DMAT3=3, -DMAT4=4, -DDATA_TYPE=int
Parameters
[in] src_ptr Pointer to the source image. Supported data types: U8
[in] src_stride_x Stride of the source image in X dimension (in bytes)
[in] src_step_x src_stride_x * number of elements along X processed per workitem(in bytes)
[in] src_stride_y Stride of the source image in Y dimension (in bytes)
[in] src_step_y src_stride_y * number of elements along Y processed per workitem(in bytes)
[in] src_offset_first_element_in_bytes The offset of the first element in the source image
[out] dst_ptr Pointer to the destination image. Supported data types: U16, S16, S32
[in] dst_stride_x Stride of the destination image in X dimension (in bytes)
[in] dst_step_x dst_stride_x * number of elements along X processed per workitem(in bytes)
[in] dst_stride_y Stride of the destination image in Y dimension (in bytes)
[in] dst_step_y dst_stride_y * number of elements along Y processed per workitem(in bytes)
[in] dst_offset_first_element_in_bytes The offset of the first element in the destination image
Definition at line 203 of file convolution5x5.cl.
 {
     Image src = CONVERT_TO_IMAGE_STRUCT(src);
     Image dst = CONVERT_TO_IMAGE_STRUCT(dst);
     // Output pixels
     VEC_DATA_TYPE(DATA_TYPE, 8)
     pixels = convolution1x5(offset(&src, -2, 0), MAT0, MAT1, MAT2, MAT3, MAT4);
     // Store result in dst
     vstore8(pixels, 0, (__global DATA_TYPE *)dst.ptr);
 }
References CONVERT_TO_IMAGE_STRUCT, convolution1x5(), DATA_TYPE, arm_compute::test::validation::dst, offset(), arm_compute::test::validation::src, and VEC_DATA_TYPE.
convolution_separable5x1_static()
__kernel void convolution_separable5x1_static (__global uchar * src_ptr, uint src_stride_x, uint src_step_x, uint src_stride_y, uint src_step_y, uint src_offset_first_element_in_bytes, __global uchar * dst_ptr, uint dst_stride_x, uint dst_step_x, uint dst_stride_y, uint dst_step_y, uint dst_offset_first_element_in_bytes)
Apply a 5x1 static convolution matrix to a single channel U8 input image and output a single channel image.
Attention
The matrix coefficients (MAT5, MAT6, MAT7, MAT8, MAT9, SCALE), COMPUTE_TYPE and DATA_TYPE_OUT need to be passed at compile time:
e.g. -DMAT5=1 -DMAT6=2, -DMAT7=3, -DMAT8=4, -DMAT9=5, -DSCALE=6, -DCOMPUTE_TYPE=int, -DDATA_TYPE_OUT=int
Parameters
[in] src_ptr Pointer to the source image. Supported data types: U16, S16, S32
[in] src_stride_x Stride of the source image in X dimension (in bytes)
[in] src_step_x src_stride_x * number of elements along X processed per workitem(in bytes)
[in] src_stride_y Stride of the source image in Y dimension (in bytes)
[in] src_step_y src_stride_y * number of elements along Y processed per workitem(in bytes)
[in] src_offset_first_element_in_bytes The offset of the first element in the source image
[out] dst_ptr Pointer to the destination image. Supported data types: U8, S16
[in] dst_stride_x Stride of the destination image in X dimension (in bytes)
[in] dst_step_x dst_stride_x * number of elements along X processed per workitem(in bytes)
[in] dst_stride_y Stride of the destination image in Y dimension (in bytes)
[in] dst_step_y dst_stride_y * number of elements along Y processed per workitem(in bytes)
[in] dst_offset_first_element_in_bytes The offset of the first element in the destination image
Definition at line 236 of file convolution5x5.cl.
 {
     Image src = CONVERT_TO_IMAGE_STRUCT(src);
     Image dst = CONVERT_TO_IMAGE_STRUCT(dst);
     // Output pixels
     VEC_DATA_TYPE(COMPUTE_TYPE, 8)
     pixels = convolution5x1(&src, MAT5, MAT6, MAT7, MAT8, MAT9);
     // Divide by the scale
     pixels /= (VEC_DATA_TYPE(COMPUTE_TYPE, 8))SCALE;
     // Store result in dst
     vstore8(CONVERT_SAT(pixels, VEC_DATA_TYPE(DATA_TYPE_OUT, 8)), 0, (__global DATA_TYPE_OUT *)dst.ptr);
 }
References COMPUTE_TYPE, CONVERT_SAT, CONVERT_TO_IMAGE_STRUCT, convolution5x1(), DATA_TYPE_OUT, arm_compute::test::validation::dst, arm_compute::test::validation::src, and VEC_DATA_TYPE.