Compute Library: src/core/CL/cl_kernels/dilate.cl File Reference
dilate.cl File Reference
#include "helpers.h"
Functions
__kernel void dilate (__global uchar *src_ptr, uint src_stride_x, uint src_step_x, uint src_stride_y, uint src_step_y, uint src_offset_first_element_in_bytes, __global uchar *dst_ptr, uint dst_stride_x, uint dst_step_x, uint dst_stride_y, uint dst_step_y, uint dst_offset_first_element_in_bytes)
This function dilates an input image.
Function Documentation
__kernel void dilate (__global uchar * src_ptr, uint src_stride_x, uint src_step_x, uint src_stride_y, uint src_step_y, uint src_offset_first_element_in_bytes, __global uchar * dst_ptr, uint dst_stride_x, uint dst_step_x, uint dst_stride_y, uint dst_step_y, uint dst_offset_first_element_in_bytes)
This function dilates an input image.
Parameters
[in] src_ptr Pointer to the source image. Supported data types: U8
[in] src_stride_x Stride of the source image in X dimension (in bytes)
[in] src_step_x src_stride_x * number of elements along X processed per workitem(in bytes)
[in] src_stride_y Stride of the source image in Y dimension (in bytes)
[in] src_step_y src_stride_y * number of elements along Y processed per workitem(in bytes)
[in] src_offset_first_element_in_bytes The offset of the first element in the source image
[out] dst_ptr Pointer to the destination image. Supported data types: U8
[in] dst_stride_x Stride of the destination image in X dimension (in bytes)
[in] dst_step_x dst_stride_x * number of elements along X processed per workitem(in bytes)
[in] dst_stride_y Stride of the destination image in Y dimension (in bytes)
[in] dst_step_y dst_stride_y * number of elements along Y processed per workitem(in bytes)
[in] dst_offset_first_element_in_bytes The offset of the first element in the destination image
Definition at line 41 of file dilate.cl.
References CONVERT_TO_IMAGE_STRUCT, arm_compute::test::validation::dst, arm_compute::test::fixed_point_arithmetic::detail::max(), offset(), Image::ptr, and arm_compute::test::validation::src.
Referenced by DilateValidationFixture< TensorType, AccessorType, FunctionType, T >::setup().
 {
     Image src = CONVERT_TO_IMAGE_STRUCT(src);
     Image dst = CONVERT_TO_IMAGE_STRUCT(dst);
     uchar16 top    = vload16(0, offset(&src, -1, -1));
     uchar16 middle = vload16(0, offset(&src, -1, 0));
     uchar16 bottom = vload16(0, offset(&src, -1, 1));
     uchar16 tmp = max(top, max(middle, bottom));
     uchar8  out = max(tmp.s01234567, max(tmp.s12345678, tmp.s23456789));
     vstore8(out, 0, dst.ptr);
 }