var dir_0538a82dae0483a21d0f1e9d7e0a45c6 =
[
    [ "Fixedpoint", "dir_1e190f7698f059a15072d193afa255c8.xhtml", "dir_1e190f7698f059a15072d193afa255c8" ],
    [ "Pooling", "dir_2661e87454575451859bd783c869d609.xhtml", "dir_2661e87454575451859bd783c869d609" ],
    [ "AbsoluteDifference.cpp", "_absolute_difference_8cpp.xhtml", null ],
    [ "Accumulate.cpp", "_accumulate_8cpp.xhtml", null ],
    [ "AccumulateSquared.cpp", "_accumulate_squared_8cpp.xhtml", null ],
    [ "AccumulateWeighted.cpp", "_accumulate_weighted_8cpp.xhtml", null ],
    [ "ActivationLayer.cpp", "validation_2_n_e_o_n_2_activation_layer_8cpp.xhtml", null ],
    [ "ArithmeticAddition.cpp", "_arithmetic_addition_8cpp.xhtml", null ],
    [ "ArithmeticSubtraction.cpp", "_arithmetic_subtraction_8cpp.xhtml", null ],
    [ "BatchNormalizationLayer.cpp", "_batch_normalization_layer_8cpp.xhtml", null ],
    [ "BitwiseAnd.cpp", "validation_2_n_e_o_n_2_bitwise_and_8cpp.xhtml", null ],
    [ "BitwiseNot.cpp", "_bitwise_not_8cpp.xhtml", null ],
    [ "BitwiseOr.cpp", "_bitwise_or_8cpp.xhtml", null ],
    [ "BitwiseXor.cpp", "_bitwise_xor_8cpp.xhtml", null ],
    [ "Box3x3.cpp", "_box3x3_8cpp.xhtml", null ],
    [ "ConvolutionLayer.cpp", "validation_2_n_e_o_n_2_convolution_layer_8cpp.xhtml", null ],
    [ "ConvolutionLayerDirect.cpp", "validation_2_n_e_o_n_2_convolution_layer_direct_8cpp.xhtml", null ],
    [ "DepthConvert.cpp", "_n_e_o_n_2_depth_convert_8cpp.xhtml", null ],
    [ "FillBorder.cpp", "_n_e_o_n_2_fill_border_8cpp.xhtml", null ],
    [ "FullyConnectedLayer.cpp", "validation_2_n_e_o_n_2_fully_connected_layer_8cpp.xhtml", null ],
    [ "GEMM.cpp", "validation_2_n_e_o_n_2_g_e_m_m_8cpp.xhtml", null ],
    [ "IntegralImage.cpp", "_integral_image_8cpp.xhtml", null ],
    [ "NormalizationLayer.cpp", "validation_2_n_e_o_n_2_normalization_layer_8cpp.xhtml", null ],
    [ "PixelWiseMultiplication.cpp", "_pixel_wise_multiplication_8cpp.xhtml", null ],
    [ "SoftmaxLayer.cpp", "_softmax_layer_8cpp.xhtml", null ],
    [ "Threshold.cpp", "_n_e_o_n_2_threshold_8cpp.xhtml", null ]
];