Compute Library: src/core/CL/cl_kernels/fast_corners.cl File Reference
fast_corners.cl File Reference
#include "helpers.h"
#include "types.h"
Macros
#define LOAD_AND_SET_MASK(ptr, a, stride, dark, bright, dark_mask, bright_mask)
Load a pixel and set the mask values.
#define CHECK_CORNER(bright_mask, dark_mask, isCorner)
Checks if a pixel is a corner.
Functions
uchar compute_strength (uchar candidate_pixel, __global unsigned char *ptr, unsigned int stride, unsigned char threshold)
__kernel void fast_corners (__global uchar *input_ptr, uint input_stride_x, uint input_step_x, uint input_stride_y, uint input_step_y, uint input_offset_first_element_in_bytes, __global uchar *output_ptr, uint output_stride_x, uint output_step_x, uint output_stride_y, uint output_step_y, uint output_offset_first_element_in_bytes, float threshold_value)
Fast corners implementation.
__kernel void copy_to_keypoint (__global uchar *input_ptr, uint input_stride_x, uint input_step_x, uint input_stride_y, uint input_step_y, uint input_offset_first_element_in_bytes, uint max_num_points, uint offset, __global uint *num_of_points, __global Keypoint *out)
Copy result to Keypoint buffer and count number of corners.
Variables
constant int offsets_s [16][2]
Macro Definition Documentation
CHECK_CORNER
#define CHECK_CORNER (bright_mask, dark_mask, isCorner)
Value:
{                                                     \
        for(int i = 0; i < 16; i++)                       \
        {                                                 \
            isCorner |= ((bright_mask & 0x1FF) == 0x1FF); \
            isCorner |= ((dark_mask & 0x1FF) == 0x1FF);   \
            if(isCorner)                                  \
            {                                             \
                break;                                    \
            }                                             \
            bright_mask >>= 1;                            \
            dark_mask >>= 1;                              \
        }                                                 \
    }
Checks if a pixel is a corner.
Pixel is considerred as a corner if the 9 continuous pixels in the Bresenham circle are bright or dark.
Parameters
[in] bright_mask The mask recording postions of bright pixels
[in] dark_mask The mask recording postions of dark pixels
[out] isCorner Indicate whether candidate pixel is corner
Definition at line 82 of file fast_corners.cl.
LOAD_AND_SET_MASK
#define LOAD_AND_SET_MASK (ptr, a, stride, dark, bright, dark_mask, bright_mask)
Value:
{                                                                           \
        unsigned char pixel;                                                    \
        pixel = *(ptr + (int)stride * offsets_s[a][1] + offsets_s[a][0]);       \
        dark_mask |= (pixel < dark) << a;                                       \
        bright_mask |= (pixel > bright) << a;                                   \
    }
Load a pixel and set the mask values.
Parameters
[in] ptr The pointer to the starting address of source image
[in] a Index to indicate the position in the Bresenham circle
[in] stride Stride of source image in x dimension
[in] dark The left end of the threshold range
[in] bright The right end of the threshold range
[out] dark_mask The bit-set mask records dark pixels. Its bit is set as 1 if the corresponding pixel is dark
[out] bright_mask The bit-set mask records bright pixels. Its bit is set as 1 if the corresponding pixel is bright
Definition at line 68 of file fast_corners.cl.
Function Documentation
compute_strength()
uchar compute_strength (uchar candidate_pixel, __global unsigned char * ptr, unsigned int stride, unsigned char threshold)
Definition at line 98 of file fast_corners.cl.
 {
     short a = threshold;
     short b = 255;
     while(b - a > 1)
     {
         uchar        c           = convert_uchar_sat((a + b) / 2);
         unsigned int bright_mask = 0;
         unsigned int dark_mask   = 0;
         unsigned char p_bright = add_sat(candidate_pixel, c);
         unsigned char p_dark   = sub_sat(candidate_pixel, c);
         bool isCorner = 0;
         for(uint i = 0; i < 16; i++)
         {
             LOAD_AND_SET_MASK(ptr, i, stride, p_dark, p_bright, dark_mask, bright_mask)
         }
         bright_mask |= (bright_mask << 16);
         dark_mask |= (dark_mask << 16);
         CHECK_CORNER(bright_mask, dark_mask, isCorner);
         if(isCorner)
         {
             a = convert_short(c);
         }
         else
         {
             b = convert_short(c);
         }
     }
     return a;
 }
References arm_compute::wrapper::add_sat(), arm_compute::test::validation::b, CHECK_CORNER, LOAD_AND_SET_MASK, and arm_compute::test::validation::reference::threshold().
Referenced by fast_corners().
copy_to_keypoint()
__kernel void copy_to_keypoint (__global uchar * input_ptr, uint input_stride_x, uint input_step_x, uint input_stride_y, uint input_step_y, uint input_offset_first_element_in_bytes, uint max_num_points, uint offset, __global uint * num_of_points, __global Keypoint * out)
Copy result to Keypoint buffer and count number of corners.
Parameters
[in] input_ptr Pointer to the image with calculated strenghs. Supported data types: U8
[in] input_stride_x Stride of the first source image in X dimension (in bytes)
[in] input_step_x input_stride_x * number of elements along X processed per workitem(in bytes)
[in] input_stride_y Stride of the first source image in Y dimension (in bytes)
[in] input_step_y input_stride_y * number of elements along Y processed per workitem(in bytes)
[in] input_offset_first_element_in_bytes The offset of the first element in the first source image
[in] max_num_points The maximum number of keypoints the array can hold
[out] offset The number of skipped pixels in x dimension
[out] num_of_points Number of points found
[out] out The keypoints found
Definition at line 230 of file fast_corners.cl.
 {
 #ifndef UPDATE_NUMBER
     if(*num_of_points >= max_num_points)
     {
         return;
     }
 #endif /* UPDATE_NUMBER */
     Image in = CONVERT_TO_IMAGE_STRUCT(input);
     uchar value = *in.ptr;
     if(value > 0)
     {
         int id = atomic_inc(num_of_points);
         if(id < max_num_points)
         {
             out[id].strength        = value;
             out[id].x               = get_global_id(0) + offset;
             out[id].y               = get_global_id(1) + offset;
             out[id].tracking_status = 1;
             out[id].scale           = 0.f;
             out[id].orientation     = 0.f;
             out[id].error           = 0.f;
         }
     }
 }
References CONVERT_TO_IMAGE_STRUCT.
fast_corners()
__kernel void fast_corners (__global uchar * input_ptr, uint input_stride_x, uint input_step_x, uint input_stride_y, uint input_step_y, uint input_offset_first_element_in_bytes, __global uchar * output_ptr, uint output_stride_x, uint output_step_x, uint output_stride_y, uint output_step_y, uint output_offset_first_element_in_bytes, float threshold_value)
Fast corners implementation.
Calculates and returns the strength of each pixel.
The algorithm loops through the 16 pixels in the Bresenham circle and set low 16 bit of masks if corresponding pixel is bright or dark. It then copy the low 16 bit to the high 16 bit of the masks. Right shift the bit to check whether the 9 continuous bits from the LSB are set.
Parameters
[in] input_ptr Pointer to the first source image. Supported data types: U8
[in] input_stride_x Stride of the first source image in X dimension (in bytes)
[in] input_step_x input_stride_x * number of elements along X processed per workitem(in bytes)
[in] input_stride_y Stride of the first source image in Y dimension (in bytes)
[in] input_step_y input_stride_y * number of elements along Y processed per workitem(in bytes)
[in] input_offset_first_element_in_bytes The offset of the first element in the first source image
[out] output_ptr Pointer to the first source image. Supported data types: U8
[in] output_stride_x Stride of the first source image in X dimension (in bytes)
[in] output_step_x output_stride_x * number of elements along X processed per workitem(in bytes)
[in] output_stride_y Stride of the first source image in Y dimension (in bytes)
[in] output_step_y output_stride_y * number of elements along Y processed per workitem(in bytes)
[in] output_offset_first_element_in_bytes The offset of the first element in the first source image
[in] threshold_value Threshold value.
Definition at line 155 of file fast_corners.cl.
 {
     Image in  = CONVERT_TO_IMAGE_STRUCT(input);
     Image out = CONVERT_TO_IMAGE_STRUCT(output);
     const unsigned char threshold = (uchar)threshold_value;
     unsigned int bright_mask = 0;
     unsigned int dark_mask   = 0;
     unsigned char isCorner = 0;
     unsigned char p        = *in.ptr;
     unsigned char p_bright = add_sat(p, threshold);
     unsigned char p_dark   = sub_sat(p, threshold);
     LOAD_AND_SET_MASK(in.ptr, 0, input_stride_y, p_dark, p_bright, dark_mask, bright_mask)
     LOAD_AND_SET_MASK(in.ptr, 4, input_stride_y, p_dark, p_bright, dark_mask, bright_mask)
     LOAD_AND_SET_MASK(in.ptr, 8, input_stride_y, p_dark, p_bright, dark_mask, bright_mask)
     LOAD_AND_SET_MASK(in.ptr, 12, input_stride_y, p_dark, p_bright, dark_mask, bright_mask)
     if(((bright_mask | dark_mask) & 0x1111) == 0)
     {
         *out.ptr = 0;
         return;
     }
     LOAD_AND_SET_MASK(in.ptr, 1, input_stride_y, p_dark, p_bright, dark_mask, bright_mask)
     LOAD_AND_SET_MASK(in.ptr, 2, input_stride_y, p_dark, p_bright, dark_mask, bright_mask)
     LOAD_AND_SET_MASK(in.ptr, 3, input_stride_y, p_dark, p_bright, dark_mask, bright_mask)
     LOAD_AND_SET_MASK(in.ptr, 5, input_stride_y, p_dark, p_bright, dark_mask, bright_mask)
     LOAD_AND_SET_MASK(in.ptr, 6, input_stride_y, p_dark, p_bright, dark_mask, bright_mask)
     LOAD_AND_SET_MASK(in.ptr, 7, input_stride_y, p_dark, p_bright, dark_mask, bright_mask)
     LOAD_AND_SET_MASK(in.ptr, 9, input_stride_y, p_dark, p_bright, dark_mask, bright_mask)
     LOAD_AND_SET_MASK(in.ptr, 10, input_stride_y, p_dark, p_bright, dark_mask, bright_mask)
     LOAD_AND_SET_MASK(in.ptr, 11, input_stride_y, p_dark, p_bright, dark_mask, bright_mask)
     LOAD_AND_SET_MASK(in.ptr, 13, input_stride_y, p_dark, p_bright, dark_mask, bright_mask)
     LOAD_AND_SET_MASK(in.ptr, 14, input_stride_y, p_dark, p_bright, dark_mask, bright_mask)
     LOAD_AND_SET_MASK(in.ptr, 15, input_stride_y, p_dark, p_bright, dark_mask, bright_mask)
     bright_mask |= (bright_mask << 16);
     dark_mask |= (dark_mask << 16);
     CHECK_CORNER(bright_mask, dark_mask, isCorner)
     if(!isCorner)
     {
         *out.ptr = 0;
         return;
     }
 #ifdef USE_MAXSUPPRESSION
     *out.ptr = compute_strength(p, in.ptr, input_stride_y, threshold);
 #else  /* USE_MAXSUPPRESSION */
     *out.ptr = 1;
 #endif /* USE_MAXSUPPRESSION */
 }
References arm_compute::wrapper::add_sat(), CHECK_CORNER, compute_strength(), CONVERT_TO_IMAGE_STRUCT, LOAD_AND_SET_MASK, Image::ptr, and arm_compute::test::validation::reference::threshold().
Variable Documentation
offsets_s
constant int offsets_s[16][2]
Initial value:
=
{
    { 0, -3 },
    { 1, -3 },
    { 2, -2 },
    { 3, -1 },
    { 3, 0 },
    { 3, 1 },
    { 2, 2 },
    { 1, 3 },
    { 0, 3 },
    { -1, 3 },
    { -2, 2 },
    { -3, 1 },
    { -3, 0 },
    { -3, -1 },
    { -2, -2 },
    { -1, -3 },
}
Definition at line 37 of file fast_corners.cl.