ARM Compute Library: src/core/CL/cl_kernels/gemm.cl File Reference
gemm.cl File Reference
#include "helpers.h"
Functions
__kernel void gemm_transpose1x4_f32 (__global uchar *src_ptr, uint src_stride_x, uint src_step_x, uint src_stride_y, uint src_step_y, uint src_offset_first_element_in_bytes, __global uchar *dst_ptr, uint dst_stride_x, uint dst_step_x, uint dst_stride_y, uint dst_step_y, uint dst_offset_first_element_in_bytes)
This OpenCL kernel computes the "vector" 1x4 transposition of input matrix.
__kernel void gemm_transpose1x8_f16 (__global uchar *src_ptr, uint src_stride_x, uint src_step_x, uint src_stride_y, uint src_step_y, uint src_offset_first_element_in_bytes, __global uchar *dst_ptr, uint dst_stride_x, uint dst_step_x, uint dst_stride_y, uint dst_step_y, uint dst_offset_first_element_in_bytes)
This OpenCL kernel computes the "vector" 1x8 transposition of input matrix.
__kernel void gemm_transpose1x16_u8 (__global uchar *src_ptr, uint src_stride_x, uint src_step_x, uint src_stride_y, uint src_step_y, uint src_offset_first_element_in_bytes, __global uchar *dst_ptr, uint dst_stride_x, uint dst_step_x, uint dst_stride_y, uint dst_step_y, uint dst_offset_first_element_in_bytes)
This OpenCL kernel computes the "vector" 1x16 transposition of input matrix.
__kernel void gemm_interleave4x4_f32 (__global uchar *src_ptr, uint src_stride_x, uint src_step_x, uint src_stride_y, uint src_step_y, uint src_offset_first_element_in_bytes, __global uchar *dst_ptr, uint dst_stride_x, uint dst_step_x, uint dst_stride_y, uint dst_step_y, uint dst_offset_first_element_in_bytes)
This OpenCL kernel reshapes the input matrix transposing each 4x4 block and interleaving the values.
__kernel void gemm_interleave4x4_f16 (__global uchar *src_ptr, uint src_stride_x, uint src_step_x, uint src_stride_y, uint src_step_y, uint src_offset_first_element_in_bytes, __global uchar *dst_ptr, uint dst_stride_x, uint dst_step_x, uint dst_stride_y, uint dst_step_y, uint dst_offset_first_element_in_bytes)
This OpenCL kernel reshapes the input matrix transposing each 4x4 block and interleaving the values.
__kernel void gemm_interleave4x4_u8 (__global uchar *src_ptr, uint src_stride_x, uint src_step_x, uint src_stride_y, uint src_step_y, uint src_offset_first_element_in_bytes, __global uchar *dst_ptr, uint dst_stride_x, uint dst_step_x, uint dst_stride_y, uint dst_step_y, uint dst_offset_first_element_in_bytes)
This OpenCL kernel reshapes the input matrix transposing each 4x4 block and interleaving the values.
__kernel void gemm_accumulate_biases_f32 (__global uchar *accum_ptr, uint accum_stride_x, uint accum_step_x, uint accum_stride_y, uint accum_step_y, uint accum_offset_first_element_in_bytes, __global uchar *biases_ptr, uint biases_stride_x, uint biases_step_x, uint biases_offset_first_element_in_bytes)
This kernel accumulates each row with the biases vector.
__kernel void gemm_accumulate_biases_f16 (__global uchar *accum_ptr, uint accum_stride_x, uint accum_step_x, uint accum_stride_y, uint accum_step_y, uint accum_offset_first_element_in_bytes, __global uchar *biases_ptr, uint biases_stride_x, uint biases_step_x, uint biases_offset_first_element_in_bytes)
This kernel accumulates each row with the biases vector.
Function Documentation
__kernel void gemm_accumulate_biases_f16 (__global uchar * accum_ptr, uint accum_stride_x, uint accum_step_x, uint accum_stride_y, uint accum_step_y, uint accum_offset_first_element_in_bytes, __global uchar * biases_ptr, uint biases_stride_x, uint biases_step_x, uint biases_offset_first_element_in_bytes)
This kernel accumulates each row with the biases vector.
Parameters
[in,out] accum_ptr Pointer to the accumulate tensor. Supported data type: F16
[in] accum_stride_x Stride of the accumulate tensor in X dimension (in bytes)
[in] accum_step_x accum_stride_x * number of elements along X processed per workitem(in bytes)
[in] accum_stride_y Stride of the accumlulate tensor in Y dimension (in bytes)
[in] accum_step_y src_stride_y * number of elements along Y processed per workitem(in bytes)
[in] accum_offset_first_element_in_bytes The offset of the first element in the accumulate tensor
[in] biases_ptr Pointer to the biases vector. Same as input.
[in] biases_stride_x Stride of the destination tensor in X dimension (in bytes)
[in] biases_step_x dst_stride_x * number of elements along X processed per workitem(in bytes)
[in] biases_offset_first_element_in_bytes The offset of the first element in the destination tensor
Definition at line 290 of file gemm.cl.
References CONVERT_TO_IMAGE_STRUCT, CONVERT_TO_VECTOR_STRUCT, IMAGE_DECLARATION, offset(), Vector::ptr, and Image::ptr.
 {
     Image  accum  = CONVERT_TO_IMAGE_STRUCT(accum);
     Vector biases = CONVERT_TO_VECTOR_STRUCT(biases);
     half8 accum_value  = vload8(0, (__global half *)accum.ptr);
     half8 biases_value = vload8(0, (__global half *)biases.ptr);
     accum_value        = biases_value + accum_value;
     // Store result in the accummulate buffer
     vstore8(accum_value, 0, (__global half *)accum.ptr);
 }
__kernel void gemm_accumulate_biases_f32 (__global uchar * accum_ptr, uint accum_stride_x, uint accum_step_x, uint accum_stride_y, uint accum_step_y, uint accum_offset_first_element_in_bytes, __global uchar * biases_ptr, uint biases_stride_x, uint biases_step_x, uint biases_offset_first_element_in_bytes)
This kernel accumulates each row with the biases vector.
Parameters
[in,out] accum_ptr Pointer to the accumulate tensor. Supported data type: F32
[in] accum_stride_x Stride of the accmulate tensor in X dimension (in bytes)
[in] accum_step_x accum_stride_x * number of elements along X processed per workitem(in bytes)
[in] accum_stride_y Stride of the accumlulate tensor in Y dimension (in bytes)
[in] accum_step_y src_stride_y * number of elements along Y processed per workitem(in bytes)
[in] accum_offset_first_element_in_bytes The offset of the first element in the accumulate tensor
[in] biases_ptr Pointer to the biases vector. Same as input.
[in] biases_stride_x Stride of the destination tensor in X dimension (in bytes)
[in] biases_step_x dst_stride_x * number of elements along X processed per workitem(in bytes)
[in] biases_offset_first_element_in_bytes The offset of the first element in the destination tensor
Definition at line 262 of file gemm.cl.
References CONVERT_TO_IMAGE_STRUCT, CONVERT_TO_VECTOR_STRUCT, Vector::ptr, and Image::ptr.
 {
     Image  accum  = CONVERT_TO_IMAGE_STRUCT(accum);
     Vector biases = CONVERT_TO_VECTOR_STRUCT(biases);
     float4 accum_value  = vload4(0, (__global float *)accum.ptr);
     float4 biases_value = vload4(0, (__global float *)biases.ptr);
     accum_value         = biases_value + accum_value;
     // Store result in the accummulate buffer
     vstore4(accum_value, 0, (__global float *)accum.ptr);
 }
__kernel void gemm_interleave4x4_f16 (__global uchar * src_ptr, uint src_stride_x, uint src_step_x, uint src_stride_y, uint src_step_y, uint src_offset_first_element_in_bytes, __global uchar * dst_ptr, uint dst_stride_x, uint dst_step_x, uint dst_stride_y, uint dst_step_y, uint dst_offset_first_element_in_bytes)
This OpenCL kernel reshapes the input matrix transposing each 4x4 block and interleaving the values.
Parameters
[in] src_ptr Pointer to the source matrix. Supported data types: F16
[in] src_stride_x Stride of the source matrix in X dimension (in bytes)
[in] src_step_x src_stride_x * number of elements along X processed per workitem(in bytes)
[in] src_stride_y Stride of the source matrix in Y dimension (in bytes)
[in] src_step_y src_stride_y * number of elements along Y processed per workitem(in bytes)
[in] src_offset_first_element_in_bytes The offset of the first element in the source matrix
[out] dst_ptr Pointer to the destination matrix Supported data types: F16
[in] dst_stride_x Stride of the destination matrix in X dimension (in bytes)
[in] dst_step_x dst_gx_stride_x * number of elements along X processed per workitem(in bytes)
[in] dst_stride_y Stride of the destination matrix in Y dimension (in bytes)
[in] dst_step_y dst_gx_stride_y * number of elements along Y processed per workitem(in bytes)
[in] dst_offset_first_element_in_bytes The offset of the first element in the destination matrix
Definition at line 178 of file gemm.cl.
References CONVERT_TO_IMAGE_STRUCT, offset(), and Image::ptr.
 {
     /* Compute source and destination addresses */
     Image src = CONVERT_TO_IMAGE_STRUCT(src);
     Image dst = CONVERT_TO_IMAGE_STRUCT(dst);
     /* Load values from Matrix A */
     half8 a0 = vload8(0, (__global half *)(offset(&src, 0, 0)));
     half8 a1 = vload8(0, (__global half *)(offset(&src, 0, 1)));
     half8 a2 = vload8(0, (__global half *)(offset(&src, 0, 2)));
     half8 a3 = vload8(0, (__global half *)(offset(&src, 0, 3)));
     half8 val0 = (half8)((half4)(a0.s0, a1.s0, a2.s0, a3.s0), (half4)(a0.s1, a1.s1, a2.s1, a3.s1));
     vstore8(val0, 0, ((__global half *)dst.ptr) + 0);
     val0 = (half8)((half4)(a0.s2, a1.s2, a2.s2, a3.s2), (half4)(a0.s3, a1.s3, a2.s3, a3.s3));
     vstore8(val0, 0, ((__global half *)dst.ptr) + 8);
     val0 = (half8)((half4)(a0.s4, a1.s4, a2.s4, a3.s4), (half4)(a0.s5, a1.s5, a2.s5, a3.s5));
     vstore8(val0, 0, ((__global half *)dst.ptr) + 16);
     val0 = (half8)((half4)(a0.s6, a1.s6, a2.s6, a3.s6), (half4)(a0.s7, a1.s7, a2.s7, a3.s7));
     vstore8(val0, 0, ((__global half *)dst.ptr) + 24);
 }
__kernel void gemm_interleave4x4_f32 (__global uchar * src_ptr, uint src_stride_x, uint src_step_x, uint src_stride_y, uint src_step_y, uint src_offset_first_element_in_bytes, __global uchar * dst_ptr, uint dst_stride_x, uint dst_step_x, uint dst_stride_y, uint dst_step_y, uint dst_offset_first_element_in_bytes)
This OpenCL kernel reshapes the input matrix transposing each 4x4 block and interleaving the values.
Parameters
[in] src_ptr Pointer to the source matrix. Supported data types: F32
[in] src_stride_x Stride of the source matrix in X dimension (in bytes)
[in] src_step_x src_stride_x * number of elements along X processed per workitem(in bytes)
[in] src_stride_y Stride of the source matrix in Y dimension (in bytes)
[in] src_step_y src_stride_y * number of elements along Y processed per workitem(in bytes)
[in] src_offset_first_element_in_bytes The offset of the first element in the source matrix
[out] dst_ptr Pointer to the destination matrix Supported data types: F32
[in] dst_stride_x Stride of the destination matrix in X dimension (in bytes)
[in] dst_step_x dst_gx_stride_x * number of elements along X processed per workitem(in bytes)
[in] dst_stride_y Stride of the destination matrix in Y dimension (in bytes)
[in] dst_step_y dst_gx_stride_y * number of elements along Y processed per workitem(in bytes)
[in] dst_offset_first_element_in_bytes The offset of the first element in the destination matrix
Definition at line 137 of file gemm.cl.
References CONVERT_TO_IMAGE_STRUCT, offset(), and Image::ptr.
 {
     /* Compute source and destination addresses */
     Image src = CONVERT_TO_IMAGE_STRUCT(src);
     Image dst = CONVERT_TO_IMAGE_STRUCT(dst);
     /* Load values from Matrix A */
     float4 a0 = vload4(0, (__global float *)(offset(&src, 0, 0)));
     float4 a1 = vload4(0, (__global float *)(offset(&src, 0, 1)));
     float4 a2 = vload4(0, (__global float *)(offset(&src, 0, 2)));
     float4 a3 = vload4(0, (__global float *)(offset(&src, 0, 3)));
     float4 val0 = (float4)(a0.s0, a1.s0, a2.s0, a3.s0);
     vstore4(val0, 0, ((__global float *)dst.ptr) + 0);
     val0 = (float4)(a0.s1, a1.s1, a2.s1, a3.s1);
     vstore4(val0, 0, ((__global float *)dst.ptr) + 4);
     val0 = (float4)(a0.s2, a1.s2, a2.s2, a3.s2);
     vstore4(val0, 0, ((__global float *)dst.ptr) + 8);
     val0 = (float4)(a0.s3, a1.s3, a2.s3, a3.s3);
     vstore4(val0, 0, ((__global float *)dst.ptr) + 12);
 }
__kernel void gemm_interleave4x4_u8 (__global uchar * src_ptr, uint src_stride_x, uint src_step_x, uint src_stride_y, uint src_step_y, uint src_offset_first_element_in_bytes, __global uchar * dst_ptr, uint dst_stride_x, uint dst_step_x, uint dst_stride_y, uint dst_step_y, uint dst_offset_first_element_in_bytes)
This OpenCL kernel reshapes the input matrix transposing each 4x4 block and interleaving the values.
Parameters
[in] src_ptr Pointer to the source matrix. Supported data types: U8
[in] src_stride_x Stride of the source matrix in X dimension (in bytes)
[in] src_step_x src_stride_x * number of elements along X processed per workitem(in bytes)
[in] src_stride_y Stride of the source matrix in Y dimension (in bytes)
[in] src_step_y src_stride_y * number of elements along Y processed per workitem(in bytes)
[in] src_offset_first_element_in_bytes The offset of the first element in the source matrix
[out] dst_ptr Pointer to the destination matrix Supported data types: U8
[in] dst_stride_x Stride of the destination matrix in X dimension (in bytes)
[in] dst_step_x dst_gx_stride_x * number of elements along X processed per workitem(in bytes)
[in] dst_stride_y Stride of the destination matrix in Y dimension (in bytes)
[in] dst_step_y dst_gx_stride_y * number of elements along Y processed per workitem(in bytes)
[in] dst_offset_first_element_in_bytes The offset of the first element in the destination matrix
Definition at line 219 of file gemm.cl.
References CONVERT_TO_IMAGE_STRUCT, offset(), and Image::ptr.
 {
     /* Compute source and destination addresses */
     Image src = CONVERT_TO_IMAGE_STRUCT(src);
     Image dst = CONVERT_TO_IMAGE_STRUCT(dst);
     /* Load values from Matrix A */
     uchar16 a0 = vload16(0, (__global uchar *)(offset(&src, 0, 0)));
     uchar16 a1 = vload16(0, (__global uchar *)(offset(&src, 0, 1)));
     uchar16 a2 = vload16(0, (__global uchar *)(offset(&src, 0, 2)));
     uchar16 a3 = vload16(0, (__global uchar *)(offset(&src, 0, 3)));
     uchar16 val0 = (uchar16)((uchar4)(a0.s0, a1.s0, a2.s0, a3.s0), (uchar4)(a0.s1, a1.s1, a2.s1, a3.s1),
                              (uchar4)(a0.s2, a1.s2, a2.s2, a3.s2), (uchar4)(a0.s3, a1.s3, a2.s3, a3.s3));
     vstore16(val0, 0, ((__global uchar *)dst.ptr) + 0);
     val0 = (uchar16)((uchar4)(a0.s4, a1.s4, a2.s4, a3.s4), (uchar4)(a0.s5, a1.s5, a2.s5, a3.s5),
                      (uchar4)(a0.s6, a1.s6, a2.s6, a3.s6), (uchar4)(a0.s7, a1.s7, a2.s7, a3.s7));
     vstore16(val0, 0, ((__global uchar *)dst.ptr) + 16);
     val0 = (uchar16)((uchar4)(a0.s8, a1.s8, a2.s8, a3.s8), (uchar4)(a0.s9, a1.s9, a2.s9, a3.s9),
                      (uchar4)(a0.sA, a1.sA, a2.sA, a3.sA), (uchar4)(a0.sB, a1.sB, a2.sB, a3.sB));
     vstore16(val0, 0, ((__global uchar *)dst.ptr) + 32);
     val0 = (uchar16)((uchar4)(a0.sC, a1.sC, a2.sC, a3.sC), (uchar4)(a0.sD, a1.sD, a2.sD, a3.sD),
                      (uchar4)(a0.sE, a1.sE, a2.sE, a3.sE), (uchar4)(a0.sF, a1.sF, a2.sF, a3.sF));
     vstore16(val0, 0, ((__global uchar *)dst.ptr) + 48);
 }
__kernel void gemm_transpose1x16_u8 (__global uchar * src_ptr, uint src_stride_x, uint src_step_x, uint src_stride_y, uint src_step_y, uint src_offset_first_element_in_bytes, __global uchar * dst_ptr, uint dst_stride_x, uint dst_step_x, uint dst_stride_y, uint dst_step_y, uint dst_offset_first_element_in_bytes)
This OpenCL kernel computes the "vector" 1x16 transposition of input matrix.
Parameters
[in] src_ptr Pointer to the source matrix. Supported data types: U8
[in] src_stride_x Stride of the source matrix in X dimension (in bytes)
[in] src_step_x src_stride_x * number of elements along X processed per workitem(in bytes)
[in] src_stride_y Stride of the source matrix in Y dimension (in bytes)
[in] src_step_y src_stride_y * number of elements along Y processed per workitem(in bytes)
[in] src_offset_first_element_in_bytes The offset of the first element in the source matrix
[out] dst_ptr Pointer to the destination matrix Supported data types: U8
[in] dst_stride_x Stride of the destination matrix in X dimension (in bytes)
[in] dst_step_x dst_gx_stride_x * number of elements along X processed per workitem(in bytes)
[in] dst_stride_y Stride of the destination matrix in Y dimension (in bytes)
[in] dst_step_y dst_gx_stride_y * number of elements along Y processed per workitem(in bytes)
[in] dst_offset_first_element_in_bytes The offset of the first element in the destination matrix
Definition at line 105 of file gemm.cl.
References CONVERT_TO_IMAGE_STRUCT, and Image::ptr.
 {
     uint x = get_global_id(0);
     uint y = get_global_id(1);
     /* Compute address for Matrix B - source */
     Image src = CONVERT_TO_IMAGE_STRUCT(src);
     /* Compute address for Matrix B transposed - destination. X and Y are swapped */
     uint dst_addr_in_bytes = y * 16 + ((x * dst_stride_y + dst_offset_first_element_in_bytes));
     uchar16 b0 = vload16(0, (__global uchar *)src.ptr);
     vstore16(b0, 0, (__global uchar *)(dst_ptr + dst_addr_in_bytes));
 }
__kernel void gemm_transpose1x4_f32 (__global uchar * src_ptr, uint src_stride_x, uint src_step_x, uint src_stride_y, uint src_step_y, uint src_offset_first_element_in_bytes, __global uchar * dst_ptr, uint dst_stride_x, uint dst_step_x, uint dst_stride_y, uint dst_step_y, uint dst_offset_first_element_in_bytes)
This OpenCL kernel computes the "vector" 1x4 transposition of input matrix.
Parameters
[in] src_ptr Pointer to the source matrix. Supported data types: F32
[in] src_stride_x Stride of the source matrix in X dimension (in bytes)
[in] src_step_x src_stride_x * number of elements along X processed per workitem(in bytes)
[in] src_stride_y Stride of the source matrix in Y dimension (in bytes)
[in] src_step_y src_stride_y * number of elements along Y processed per workitem(in bytes)
[in] src_offset_first_element_in_bytes The offset of the first element in the source matrix
[out] dst_ptr Pointer to the destination matrix Supported data types: F32
[in] dst_stride_x Stride of the destination matrix in X dimension (in bytes)
[in] dst_step_x dst_gx_stride_x * number of elements along X processed per workitem(in bytes)
[in] dst_stride_y Stride of the destination matrix in Y dimension (in bytes)
[in] dst_step_y dst_gx_stride_y * number of elements along Y processed per workitem(in bytes)
[in] dst_offset_first_element_in_bytes The offset of the first element in the destination matrix
Definition at line 41 of file gemm.cl.
References CONVERT_TO_IMAGE_STRUCT, and Image::ptr.
 {
     uint x = get_global_id(0);
     uint y = get_global_id(1);
     /* Compute address for Matrix B - source */
     Image src = CONVERT_TO_IMAGE_STRUCT(src);
     /* Compute address for Matrix B transposed - destination. X and Y are swapped */
     uint dst_addr_in_bytes = y * 16 + ((x * dst_stride_y + dst_offset_first_element_in_bytes));
     float4 b0 = vload4(0, (__global float *)src.ptr);
     vstore4(b0, 0, (__global float *)(dst_ptr + dst_addr_in_bytes));
 }
__kernel void gemm_transpose1x8_f16 (__global uchar * src_ptr, uint src_stride_x, uint src_step_x, uint src_stride_y, uint src_step_y, uint src_offset_first_element_in_bytes, __global uchar * dst_ptr, uint dst_stride_x, uint dst_step_x, uint dst_stride_y, uint dst_step_y, uint dst_offset_first_element_in_bytes)
This OpenCL kernel computes the "vector" 1x8 transposition of input matrix.
Parameters
[in] src_ptr Pointer to the source matrix. Supported data types: F16
[in] src_stride_x Stride of the source matrix in X dimension (in bytes)
[in] src_step_x src_stride_x * number of elements along X processed per workitem(in bytes)
[in] src_stride_y Stride of the source matrix in Y dimension (in bytes)
[in] src_step_y src_stride_y * number of elements along Y processed per workitem(in bytes)
[in] src_offset_first_element_in_bytes The offset of the first element in the source matrix
[out] dst_ptr Pointer to the destination matrix Supported data types: F16
[in] dst_stride_x Stride of the destination matrix in X dimension (in bytes)
[in] dst_step_x dst_gx_stride_x * number of elements along X processed per workitem(in bytes)
[in] dst_stride_y Stride of the destination matrix in Y dimension (in bytes)
[in] dst_step_y dst_gx_stride_y * number of elements along Y processed per workitem(in bytes)
[in] dst_offset_first_element_in_bytes The offset of the first element in the destination matrix
Definition at line 73 of file gemm.cl.
References CONVERT_TO_IMAGE_STRUCT, and Image::ptr.
 {
     uint x = get_global_id(0);
     uint y = get_global_id(1);
     /* Compute address for Matrix B - source */
     Image src = CONVERT_TO_IMAGE_STRUCT(src);
     /* Compute address for Matrix B transposed - destination. X and Y are swapped */
     uint dst_addr_in_bytes = y * 16 + ((x * dst_stride_y + dst_offset_first_element_in_bytes));
     half8 b0 = vload8(0, (__global half *)src.ptr);
     vstore8(b0, 0, (__global half *)(dst_ptr + dst_addr_in_bytes));
 }