var globals_func =
[
    [ "a", "globals_func.xhtml", null ],
    [ "b", "globals_func_b.xhtml", null ],
    [ "c", "globals_func_c.xhtml", null ],
    [ "d", "globals_func_d.xhtml", null ],
    [ "e", "globals_func_e.xhtml", null ],
    [ "f", "globals_func_f.xhtml", null ],
    [ "g", "globals_func_g.xhtml", null ],
    [ "h", "globals_func_h.xhtml", null ],
    [ "i", "globals_func_i.xhtml", null ],
    [ "l", "globals_func_l.xhtml", null ],
    [ "m", "globals_func_m.xhtml", null ],
    [ "n", "globals_func_n.xhtml", null ],
    [ "o", "globals_func_o.xhtml", null ],
    [ "p", "globals_func_p.xhtml", null ],
    [ "q", "globals_func_q.xhtml", null ],
    [ "r", "globals_func_r.xhtml", null ],
    [ "s", "globals_func_s.xhtml", null ],
    [ "t", "globals_func_t.xhtml", null ],
    [ "u", "globals_func_u.xhtml", null ],
    [ "v", "globals_func_v.xhtml", null ],
    [ "w", "globals_func_w.xhtml", null ],
    [ "y", "globals_func_y.xhtml", null ]
];