Compute Library: examples/graph_lenet.cpp File Reference
graph_lenet.cpp File Reference
#include "arm_compute/graph/Graph.h"
#include "arm_compute/graph/Nodes.h"
#include "arm_compute/runtime/CL/CLScheduler.h"
#include "arm_compute/runtime/Scheduler.h"
#include "support/ToolchainSupport.h"
#include "utils/GraphUtils.h"
#include "utils/Utils.h"
#include <cstdlib>
#include <iostream>
#include <memory>
Functions
std::unique_ptr< ITensorAccessor > get_accessor (const std::string &path, const std::string &data_file)
Generates appropriate accessor according to the specified path.
void main_graph_lenet (int argc, const char **argv)
Example demonstrating how to implement LeNet's network using the Compute Library's graph API.
int main (int argc, const char **argv)
Main program for LeNet.
Function Documentation
std::unique_ptr<ITensorAccessor> get_accessor (const std::string & path, const std::string & data_file)
Generates appropriate accessor according to the specified path.
Note
If path is empty will generate a DummyAccessor else will generate a NumPyBinLoader
Parameters
path Path to the data files
data_file Relative path to the data files from path
Returns
An appropriate tensor accessor
Definition at line 52 of file graph_lenet.cpp.
Referenced by main_graph_lenet().
 {
     if(path.empty())
     {
         return arm_compute::support::cpp14::make_unique<DummyAccessor>();
     }
     else
     {
         return arm_compute::support::cpp14::make_unique<NumPyBinLoader>(path + data_file);
     }
 }
int main (int argc, const char ** argv)
Main program for LeNet.
Parameters
[in] argc Number of arguments
[in] argv Arguments ([optional] Path to the weights folder, [optional] batches)
Definition at line 139 of file graph_lenet.cpp.
References main_graph_lenet(), and arm_compute::utils::run_example().
 {
     return arm_compute::utils::run_example(argc, argv, main_graph_lenet);
 }
void main_graph_lenet (int argc, const char ** argv)
Example demonstrating how to implement LeNet's network using the Compute Library's graph API.
Parameters
[in] argc Number of arguments
[in] argv Arguments ([optional] Path to the weights folder, [optional] batches)
Path to the trainable data
Number of batches
Definition at line 69 of file graph_lenet.cpp.
References CLScheduler::default_init(), arm_compute::F32, CLScheduler::get(), get_accessor(), arm_compute::MAX, arm_compute::graph::OPENCL, arm_compute::opencl_is_available(), ActivationLayerInfo::RELU, Graph::run(), and Graph::set_info_enablement().
Referenced by main().
 {
     std::string  data_path;
     unsigned int batches = 4;
     // Parse arguments
     if(argc < 2)
     {
         // Print help
         std::cout << "Usage: " << argv[0] << " [path_to_data] [batches]\n\n";
         std::cout << "No data folder provided: using random values\n\n";
     }
     else if(argc == 2)
     {
         //Do something with argv[1]
         data_path = argv[1];
         std::cout << "Usage: " << argv[0] << " [path_to_data] [batches]\n\n";
         std::cout << "No number of batches where specified, thus will use the default : " << batches << "\n\n";
     }
     else
     {
         //Do something with argv[1] and argv[2]
         data_path = argv[1];
         batches   = std::strtol(argv[2], nullptr, 0);
     }
     // Check if OpenCL is available and initialize the scheduler
     if(arm_compute::opencl_is_available())
     {
         arm_compute::CLScheduler::get().default_init();
     }
     Graph graph;
     graph.set_info_enablement(true);
     //conv1 << pool1 << conv2 << pool2 << fc1 << act1 << fc2 << smx
     graph << Hint::OPENCL
           << Tensor(TensorInfo(TensorShape(28U, 28U, 1U, batches), 1, DataType::F32), DummyAccessor())
           << ConvolutionLayer(
               5U, 5U, 20U,
               get_accessor(data_path, "/cnn_data/lenet_model/conv1_w.npy"),
               get_accessor(data_path, "/cnn_data/lenet_model/conv1_b.npy"),
               PadStrideInfo(1, 1, 0, 0))
           << PoolingLayer(PoolingLayerInfo(PoolingType::MAX, 2, PadStrideInfo(2, 2, 0, 0)))
           << ConvolutionLayer(
               5U, 5U, 50U,
               get_accessor(data_path, "/cnn_data/lenet_model/conv2_w.npy"),
               get_accessor(data_path, "/cnn_data/lenet_model/conv2_b.npy"),
               PadStrideInfo(1, 1, 0, 0))
           << PoolingLayer(PoolingLayerInfo(PoolingType::MAX, 2, PadStrideInfo(2, 2, 0, 0)))
           << FullyConnectedLayer(
               500U,
               get_accessor(data_path, "/cnn_data/lenet_model/ip1_w.npy"),
               get_accessor(data_path, "/cnn_data/lenet_model/ip1_b.npy"))
           << ActivationLayer(ActivationLayerInfo(ActivationLayerInfo::ActivationFunction::RELU))
           << FullyConnectedLayer(
               10U,
               get_accessor(data_path, "/cnn_data/lenet_model/ip2_w.npy"),
               get_accessor(data_path, "/cnn_data/lenet_model/ip2_b.npy"))
           << SoftmaxLayer()
           << Tensor(DummyAccessor());
     graph.run();
 }