Compute Library: arm_compute::logging Namespace Reference
arm_compute::logging Namespace Reference
Data Structures
class DateDecorator
Date Decorator.
class FilePrinter
File Printer.
class IDecorator
Log message decorator interface.
class Logger
Logger class.
class LoggerRegistry
Registry class holding all the instantiated loggers.
class LogLevelDecorator
Log Level Decorator.
struct LogMsg
Log message.
class Printer
Base printer class to be inherited by other printer classes.
class StdPrinter
Std Printer.
class StringDecorator
String Decorator.
class ThreadIdDecorator
Thread ID Decorator.
Enumerations
enum LogLevel {
VERBOSE, INFO, WARN, ERROR,
OFF
}
Logging level enumeration.
Functions
template<typename... Ts>
std::string string_with_format (const std::string &fmt, Ts &&... args)
Create a string given a format.
template<typename T >
std::string angle_wrap_value (const T &val)
Wraps a value with angles and returns the string.
const std::string & string_from_log_level (LogLevel log_level)
Translates a given log level to a string.
Enumeration Type Documentation
LogLevel
enum LogLevel strong
Logging level enumeration.
Enumerator
VERBOSE
All logging messages.
INFO
Information log level.
WARN
Warning log level.
ERROR
Error log level.
OFF
No logging.
Definition at line 34 of file Types.h.
 {
     VERBOSE,
     INFO,
     WARN,
     ERROR,
     OFF
 };
Function Documentation
angle_wrap_value()
std::string arm_compute::logging::angle_wrap_value (const T & val) inline
Wraps a value with angles and returns the string.
Parameters
[in] val Value to wrap
Returns
Wrapped string
Definition at line 62 of file Helpers.h.
 {
     std::ostringstream ss;
     ss << "[" << val << "]";
     return ss.str();
 }
Referenced by DateDecorator::decorate(), ThreadIdDecorator::decorate(), LogLevelDecorator::decorate(), and StringDecorator::StringDecorator().
string_from_log_level()
const std::string & string_from_log_level (LogLevel log_level)
Translates a given log level to a string.
Parameters
[in] log_level LogLevel to be translated to string.
Returns
The string describing the logging level.
Definition at line 31 of file Helpers.cpp.
 {
     static std::map<LogLevel, const std::string> log_level_map =
     {
         { LogLevel::VERBOSE, "VERBOSE" },
         { LogLevel::INFO, "INFO" },
         { LogLevel::WARN, "WARN" },
         { LogLevel::OFF, "OFF" },
     };
     return log_level_map[log_level];
 }
References INFO, OFF, VERBOSE, and WARN.
Referenced by LogLevelDecorator::decorate().
string_with_format()
std::string arm_compute::logging::string_with_format (const std::string & fmt, Ts &&... args) inline
Create a string given a format.
Parameters
[in] fmt String format
[in] args Arguments
Returns
The formatted string
Definition at line 48 of file Helpers.h.
 {
     size_t size     = support::cpp11::snprintf(nullptr, 0, fmt.c_str(), args...) + 1;
     auto   char_str = support::cpp14::make_unique<char[]>(size);
     support::cpp11::snprintf(char_str.get(), size, fmt.c_str(), args...);
     return std::string(char_str.get(), char_str.get() + size - 1);
 }
References arm_compute::support::cpp11::snprintf().
Referenced by Logger::log().