Compute Library: arm_compute::graph::frontend Namespace Reference
arm_compute::graph::frontend Namespace Reference
Data Structures
class ActivationLayer
Activation Layer.
class BatchNormalizationLayer
Batchnormalization Layer.
class BoundingBoxTransformLayer
Bounding Box Transform Layer.
class ChannelShuffleLayer
Channel Shuffle Layer.
class ConcatLayer
Concat Layer.
class ConvolutionLayer
Convolution Layer.
class DeconvolutionLayer
Deconvolution Layer.
class DepthwiseConvolutionLayer
Depthwise Convolution Layer.
class DetectionOutputLayer
DetectionOutput Layer.
class DummyLayer
Dummy Layer.
class EltwiseLayer
class FlattenLayer
Flatten Layer.
class FullyConnectedLayer
Fully Connected Layer.
class GenerateProposalsLayer
Generate Proposals Layer.
class ILayer
ILayer interface.
class InputLayer
Input Layer.
class IStream
Stream interface.
class NormalizationLayer
Normalization Layer.
class NormalizePlanarYUVLayer
Normalize planar YUV Layer.
class OutputLayer
Output Layer.
class PadLayer
Pad Layer.
class PermuteLayer
Permute Layer.
class PoolingLayer
Pooling Layer.
class PriorBoxLayer
PriorBox Layer.
class ReorgLayer
Reorg Layer.
class ReshapeLayer
Reshape Layer.
class ResizeLayer
Resize Layer.
class ROIAlignLayer
ROIAlign Layer.
class ScaleLayer
Scale Layer.
class SliceLayer
Slice Layer.
class SoftmaxLayer
Softmax Layer.
class StackLayer
Stack Layer.
class Stream
Stream frontend class to construct simple graphs in a stream fashion.
struct StreamHints
Hints that can be passed to the stream to expose parameterization.
class SubStream
Sub stream class.
class UpsampleLayer
Upsample Layer.
class YOLOLayer
YOLO Layer.
Functions
IStream & operator<< (IStream &s, ILayer &&layer)
Overloaded stream operator to add a node to the graph.
IStream & operator<< (IStream &s, ILayer &layer)
Overloaded stream operator to add a node to the graph.
IStream & operator<< (IStream &s, Target target_hint)
Overloaded stream operator to provide a target hint to the graph.
IStream & operator<< (IStream &s, ConvolutionMethod convolution_method_hint)
Overloaded stream operator to provide a convolution method hint to the graph.
IStream & operator<< (IStream &s, DepthwiseConvolutionMethod depthwise_convolution_method_hint)
Overloaded stream operator to provide a depthwise convolution method hint to the graph.
IStream & operator<< (IStream &s, FastMathHint fast_math_hint)
Overloaded stream operator to provide a fast math hint to the graph.
Function Documentation
operator<<() [1/6]
IStream& arm_compute::graph::frontend::operator<< (IStream & s, ILayer && layer) inline
Overloaded stream operator to add a node to the graph.
Parameters
[in,out] s Stream to add the tensor
[in] layer Layer to be added
Returns
Updated stream
Definition at line 46 of file IStreamOperators.h.
 {
     s.add_layer(layer);
     return s;
 }
References IStream::add_layer().
operator<<() [2/6]
IStream& arm_compute::graph::frontend::operator<< (IStream & s, ILayer & layer) inline
Overloaded stream operator to add a node to the graph.
Parameters
[in,out] s Stream to add the tensor
[in] layer Layer to be added
Returns
Updated stream
Definition at line 58 of file IStreamOperators.h.
 {
     s.add_layer(layer);
     return s;
 }
References IStream::add_layer().
operator<<() [3/6]
IStream& arm_compute::graph::frontend::operator<< (IStream & s, Target target_hint) inline
Overloaded stream operator to provide a target hint to the graph.
Parameters
[in,out] s Stream to provide the hint to
[in] target_hint Target hint to be considered
Returns
Updated stream
Definition at line 70 of file IStreamOperators.h.
 {
     s.hints().target_hint = target_hint;
     return s;
 }
References IStream::hints(), and StreamHints::target_hint.
operator<<() [4/6]
IStream& arm_compute::graph::frontend::operator<< (IStream & s, ConvolutionMethod convolution_method_hint) inline
Overloaded stream operator to provide a convolution method hint to the graph.
Parameters
[in,out] s Stream to provide the hint to
[in] convolution_method_hint Convolution method hint to be considered
Returns
Updated stream
Definition at line 82 of file IStreamOperators.h.
 {
     s.hints().convolution_method_hint = convolution_method_hint;
     return s;
 }
References StreamHints::convolution_method_hint, and IStream::hints().
operator<<() [5/6]
IStream& arm_compute::graph::frontend::operator<< (IStream & s, DepthwiseConvolutionMethod depthwise_convolution_method_hint) inline
Overloaded stream operator to provide a depthwise convolution method hint to the graph.
Parameters
[in,out] s Stream to provide the hint to
[in] depthwise_convolution_method_hint Depthwise Convolution method hint to be considered
Returns
Updated stream
Definition at line 94 of file IStreamOperators.h.
 {
     s.hints().depthwise_convolution_method_hint = depthwise_convolution_method_hint;
     return s;
 }
References StreamHints::depthwise_convolution_method_hint, and IStream::hints().
operator<<() [6/6]
IStream& arm_compute::graph::frontend::operator<< (IStream & s, FastMathHint fast_math_hint) inline
Overloaded stream operator to provide a fast math hint to the graph.
Parameters
[in,out] s Stream to provide the hint to
[in] fast_math_hint Convolution method hint to be considered
Returns
Updated stream
Definition at line 106 of file IStreamOperators.h.
 {
     s.hints().fast_math_hint = fast_math_hint;
     return s;
 }
References StreamHints::fast_math_hint, and IStream::hints().