Compute Library: arm_compute::helpers::tensor_transform Namespace Reference
arm_compute::helpers::tensor_transform Namespace Reference
Functions
Coordinates slice_absolute_end_coords (TensorShape input_shape, Coordinates ends)
Returns the absolute ends coordinates of slice.
TensorShape compute_slice_output_shape (TensorShape input_shape, Coordinates starts, Coordinates ends_abs)
Computes output shape of slice.
Coordinates strided_slice_absolute_start_coords (TensorShape input_shape, Coordinates starts, Coordinates strides, int32_t begin_mask=0)
Returns the absolute start coordinates of strided slice.
Coordinates strided_slice_absolute_end_coords (TensorShape input_shape, Coordinates starts_abs, Coordinates ends, Coordinates strides, int32_t end_mask=0, int32_t shrink_axis_mask=0)
Returns the absolute ends coordinates of strided slice.
Coordinates strided_slice_strides (TensorShape input_shape, Coordinates strides)
Returns the final strides of strided slice.
TensorShape compute_strided_slice_output_shape (TensorShape input_shape, Coordinates starts_abs, Coordinates ends_abs, Coordinates final_strides)
Computes output shape of strided slice.
Function Documentation
compute_slice_output_shape()
TensorShape compute_slice_output_shape (TensorShape input_shape, Coordinates starts, Coordinates ends_abs)
Computes output shape of slice.
Warning
Ends must be non-negative
Parameters
[in] input_shape Input tensor shape
[in] starts Start coordinates
[in] ends_abs Absolute end coordinates
Returns
The output tensor shape
Definition at line 49 of file tensor_transform.cpp.
References compute_strided_slice_output_shape(), and strided_slice_strides().
Referenced by arm_compute::test::validation::reference::slice().
 {
     // Get unit strides
     const BiStrides unit_strides = strided_slice_strides(input_shape, BiStrides());
     return compute_strided_slice_output_shape(input_shape, starts, ends_abs, unit_strides);
 }
compute_strided_slice_output_shape()
TensorShape compute_strided_slice_output_shape (TensorShape input_shape, Coordinates starts_abs, Coordinates ends_abs, Coordinates final_strides)
Computes output shape of strided slice.
Warning
Starts and ends must be non-negative
Starts, ends and final strides should have the same dimensions as the input shape
Parameters
[in] input_shape Input tensor shape
[in] starts_abs Absolute start coordinates
[in] ends_abs Absolute end coordinates
[in] final_strides Slice strides
Returns
The output tensor shape
Definition at line 142 of file tensor_transform.cpp.
References Dimensions< T >::num_dimensions(), arm_compute::test::validation::output_shape, and TensorShape::set().
Referenced by compute_slice_output_shape(), arm_compute::misc::shape_calculator::compute_strided_slice_shape(), and arm_compute::test::validation::reference::strided_slice().
 {
     TensorShape output_shape = input_shape;
     for(unsigned int i = 0; i < input_shape.num_dimensions(); ++i)
     {
         const int stride_i = final_strides[i];
         const int range    = ends_abs[i] - starts_abs[i];
         if((range == 0) ||                 // Zero range
            (range < 0 && stride_i >= 0) || // Negative range with positive stride
            (range > 0 && stride_i <= 0))   // Positive range with negative stride
         {
             output_shape.set(i, 0);
             return output_shape;
         }
         else
         {
             int dim = range / stride_i + (range % stride_i != 0 ? 1 : 0);
             output_shape.set(i, dim);
         }
     }
     return output_shape;
 }
slice_absolute_end_coords()
Coordinates slice_absolute_end_coords (TensorShape input_shape, Coordinates ends)
Returns the absolute ends coordinates of slice.
Parameters
[in] input_shape Input tensor shape
[in] ends End coordinates
Returns
Absolute end coordinate
Definition at line 32 of file tensor_transform.cpp.
References Dimensions< T >::num_dimensions(), strided_slice_absolute_end_coords(), and strided_slice_strides().
Referenced by SliceLayerNode::compute_output_descriptor(), CLSlice::configure(), arm_compute::test::validation::reference::slice(), and CLSlice::validate().
 {
     // Create end mask
     int32_t end_mask = 0;
     for(unsigned int i = 0; i < ends.num_dimensions(); ++i)
     {
         if(ends[i] < 0)
         {
             end_mask |= 1 << i;
         }
     }
     // Get unit strides
     const BiStrides unit_strides = strided_slice_strides(input_shape, BiStrides());
     return strided_slice_absolute_end_coords(input_shape, Coordinates(), ends, unit_strides, end_mask);
 }
strided_slice_absolute_end_coords()
Coordinates strided_slice_absolute_end_coords (TensorShape input_shape, Coordinates starts_abs, Coordinates ends, Coordinates strides, int32_t end_mask = 0, int32_t shrink_axis_mask = 0)
Returns the absolute ends coordinates of strided slice.
Warning
Starts must be non-negative
Parameters
[in] input_shape Input tensor shape
[in] starts_abs Absolute start coordinates
[in] ends End coordinates
[in] strides Slice strides
[in] end_mask (Optional) If the ith bit of end_mask is set, end[i] is ignored and the fullest possible range in that dimension is used instead.
[in] shrink_axis_mask (Optional) If the ith bit of shrink_axis_mask is set, it implies that the ith specification shrinks the dimensionality by 1. A slice of size 1 starting from starts[i] in the dimension must be preserved.
Returns
Absolute end coordinates
Definition at line 91 of file tensor_transform.cpp.
References arm_compute::utility::clamp(), arm_compute::support::cpp11::lowest(), Dimensions< T >::num_dimensions(), and Dimensions< T >::set().
Referenced by arm_compute::misc::shape_calculator::compute_strided_slice_shape(), CLStridedSliceKernel::configure(), slice_absolute_end_coords(), and arm_compute::test::validation::reference::strided_slice().
 {
     Coordinates ends_abs;
     for(unsigned int i = 0; i < ends.num_dimensions(); ++i)
     {
         // Get end index
         int stop_i = ends[i];
         // Shrink dimension
         if((shrink_axis_mask & (1 << i)) != 0)
         {
             stop_i = starts_abs[i] + 1;
         }
         // Reset in case of begin mask present
         if((end_mask & 1 << i) != 0)
         {
             stop_i = (strides[i] > 0) ? std::numeric_limits<int>::max() : std::numeric_limits<int>::lowest();
         }
         // Account negative end points
         const int dim_size = input_shape[i];
         if(stop_i < 0)
         {
             stop_i += dim_size;
         }
         // Final clamp
         stop_i = (strides[i] > 0) ? utility::clamp(stop_i, 0, dim_size) : utility::clamp(stop_i, -1, dim_size - 1);
         ends_abs.set(i, stop_i);
     }
     // Fill remaining ends
     for(unsigned int i = ends_abs.num_dimensions(); i < input_shape.num_dimensions(); ++i)
     {
         ends_abs.set(i, input_shape[i]);
     }
     return ends_abs;
 }
strided_slice_absolute_start_coords()
Coordinates strided_slice_absolute_start_coords (TensorShape input_shape, Coordinates starts, Coordinates strides, int32_t begin_mask = 0)
Returns the absolute start coordinates of strided slice.
Parameters
[in] input_shape Input tensor shape
[in] starts Start coordinates
[in] strides Slice strides
[in] begin_mask (Optional) If the ith bit of begin_mask is set, starts[i] is ignored and the fullest possible range in that dimension is used instead.
Returns
Absolute start coordinates
Definition at line 56 of file tensor_transform.cpp.
References arm_compute::utility::clamp(), arm_compute::support::cpp11::lowest(), Dimensions< T >::num_dimensions(), and Dimensions< T >::set().
Referenced by arm_compute::misc::shape_calculator::compute_strided_slice_shape(), CLStridedSliceKernel::configure(), and arm_compute::test::validation::reference::strided_slice().
 {
     Coordinates starts_abs;
     for(unsigned int i = 0; i < starts.num_dimensions(); ++i)
     {
         // Get start index
         int start_i = starts[i];
         // Reset in case of begin mask present
         if((begin_mask & 1 << i) != 0)
         {
             start_i = strides[i] > 0 ? std::numeric_limits<int>::lowest() : std::numeric_limits<int>::max();
         }
         // Account negative start points
         const int dim_size = input_shape[i];
         if(start_i < 0)
         {
             start_i += dim_size;
         }
         // Final clamp
         start_i = utility::clamp(start_i, 0, dim_size - 1);
         starts_abs.set(i, start_i);
     }
     // Fill remaining
     for(unsigned int i = starts_abs.num_dimensions(); i < input_shape.num_dimensions(); ++i)
     {
         starts_abs.set(i, 0);
     }
     return starts_abs;
 }
strided_slice_strides()
Coordinates strided_slice_strides (TensorShape input_shape, Coordinates strides)
Returns the final strides of strided slice.
Parameters
[in] input_shape Input tensor shape
[in] strides Slice strides
Returns
The final strides need by strided slice
Definition at line 133 of file tensor_transform.cpp.
References Dimensions< T >::num_dimensions(), and Dimensions< T >::set().
Referenced by compute_slice_output_shape(), arm_compute::misc::shape_calculator::compute_strided_slice_shape(), CLStridedSliceKernel::configure(), slice_absolute_end_coords(), and arm_compute::test::validation::reference::strided_slice().
 {
     for(unsigned int i = strides.num_dimensions(); i < input_shape.num_dimensions(); ++i)
     {
         strides.set(i, 1);
     }
     return strides;
 }