Compute Library: arm_compute::helpers::bit_ops Namespace Reference
arm_compute::helpers::bit_ops Namespace Reference
Functions
template<typename T , typename = typename std::enable_if<(std::is_integral<T>::value), arm_compute::utils::requires::detail::enabler>::type>
bool is_bit_set (T v, unsigned int idx)
Checks if the idx-th bit is set in an integral type.
Function Documentation
is_bit_set()
bool arm_compute::helpers::bit_ops::is_bit_set (T v, unsigned int idx)
Checks if the idx-th bit is set in an integral type.
Parameters
[in] v Integral input
[in] idx Index of the bit to check
Returns
True if the idx-th bit is set else false
Definition at line 45 of file bit_ops.h.
 {
     return (v & 1 << idx) != 0;
 }
Referenced by arm_compute::helpers::tensor_transform::calculate_end_on_index(), arm_compute::helpers::tensor_transform::calculate_start_on_index(), arm_compute::helpers::tensor_transform::compute_strided_slice_output_shape(), and CLStridedSliceKernel::configure().