Compute Library: arm_compute::test Namespace Reference
arm_compute::test Namespace Reference
Namespaces
benchmark
CLSuite
datasets
fixed_point_arithmetic
framework
gles_compute
networks
traits
validation
Data Structures
class Accessor
Accessor implementation for Tensor objects.
class ActivationLayerFixture
Fixture that can be used for NEON and CL.
class AlexNetFixture
class ArrayAccessor
ArrayAccessor implementation for Array objects.
class AssetsLibrary
Factory class to create and fill tensors.
class BatchNormalizationLayerFixture
Fixture that can be used for NEON and CL.
class CLAccessor
Accessor implementation for CLTensor objects.
class CLArrayAccessor
Accessor implementation for CLArray objects.
class CLLutAccessor
Accessor implementation for CLLut objects.
class CLSynthetizeFunction
class CLSynthetizeFunctionWithZeroConstantBorder
struct common_promoted_signed_type
Find the signed promoted common type.
struct common_promoted_unsigned_type
Find the unsigned promoted common type.
class ConvolutionLayerFixture
Fixture that can be used for NEON and CL.
class DepthwiseConvolutionLayerFixture
Fixture that can be used for NEON and CL.
class DepthwiseSeparableConvolutionLayerFixture
Fixture that can be used for NEON and CL.
class FloorFixture
Fixture that can be used for NEON and CL.
class FullyConnectedLayerFixture
Fixture that can be used for NEON and CL.
class GCAccessor
Accessor implementation for GCTensor objects.
class GEMMFixture
Fixture that can be used for NEON and CL.
class GEMMLowpMatrixMultiplyCoreFixture
Fixture that can be used for NEON and CL.
class IAccessor
Common interface to provide information and access to tensor like structures.
class IArrayAccessor
Common interface to provide information and access to array like structures.
class ILutAccessor
Common interface to provide information and access to Lut like structures.
class LeNet5Fixture
class LutAccessor
Accessor implementation for Lut objects.
class MobileNetFixture
class MobileNetV1Fixture
class NESynthetizeFunction
class NESynthetizeFunctionWithZeroConstantBorder
class NormalizationLayerFixture
Fixture that can be used for NEON and CL.
class NormalizePlanarYUVLayerFixture
Fixture that can be used for NEON and CL.
class PaddingCalculator
Calculate required padding.
class PoolingLayerFixture
Fixture that can be used for NEON and CL.
class RawLutAccessor
Accessor implementation for std::map-lut objects.
class RawTensor
Subclass of SimpleTensor using uint8_t as value type.
class ROIPoolingLayerFixture
Fixture that can be used for NEON and CL.
class ScaleLayerFixture
Fixture that can be used for NEON, CL and OpenGL ES.
class SimpleTensor
Simple tensor object that stores elements in a consecutive chunk of memory.
class SoftmaxLayerFixture
Fixture that can be used for NEON, CL and OpenGL ES.
class TensorCache
Stores RawTensor categorised by the image they are created from including name, format and channel.
Typedefs
using CLActivationLayerFixture = ActivationLayerFixture< CLTensor, CLActivationLayer, CLAccessor >
using CLBatchNormalizationLayerFixture = BatchNormalizationLayerFixture< CLTensor, CLBatchNormalizationLayer, CLAccessor >
using CLConvolutionLayerFixture = ConvolutionLayerFixture< CLTensor, CLConvolutionLayer, CLAccessor >
using CLDepthwiseConvolutionLayerFixture = DepthwiseConvolutionLayerFixture< CLTensor, CLDepthwiseConvolutionLayer3x3, CLAccessor >
using CLDepthwiseSeparableConvolutionLayerFixture = DepthwiseSeparableConvolutionLayerFixture< CLTensor, CLDepthwiseSeparableConvolutionLayer, CLAccessor >
using CLFloorFixture = FloorFixture< CLTensor, CLFloor, CLAccessor >
using CLFullyConnectedLayerFixture = FullyConnectedLayerFixture< CLTensor, CLFullyConnectedLayer, CLAccessor >
using CLGEMMFixture = GEMMFixture< CLTensor, CLGEMM, CLAccessor >
using CLGEMMLowpFixture = GEMMLowpMatrixMultiplyCoreFixture< CLTensor, CLGEMMLowpMatrixMultiplyCore, CLAccessor >
using CLNormalizationLayerFixture = NormalizationLayerFixture< CLTensor, CLNormalizationLayer, CLAccessor >
using CLPoolingLayerFixture = PoolingLayerFixture< CLTensor, CLPoolingLayer, CLAccessor >
using CLROIPoolingLayerFixture = ROIPoolingLayerFixture< CLTensor, CLROIPoolingLayer, CLAccessor, CLArray< ROI >, CLArrayAccessor< ROI >>
using CLSoftmaxLayerFixture = SoftmaxLayerFixture< CLTensor, CLSoftmaxLayer, CLAccessor >
using CLAlexNetFixture = AlexNetFixture< ICLTensor, CLTensor, CLSubTensor, CLAccessor, CLActivationLayer, CLConvolutionLayer, CLDirectConvolutionLayer, CLFullyConnectedLayer, CLNormalizationLayer, CLPoolingLayer, CLSoftmaxLayer >
using CLLeNet5Fixture = LeNet5Fixture< CLTensor, CLAccessor, CLActivationLayer, CLConvolutionLayer, CLFullyConnectedLayer, CLPoolingLayer, CLSoftmaxLayer >
using CLMobileNetFixture = MobileNetFixture< CLTensor, CLAccessor, CLActivationLayer, CLConvolutionLayer, CLDirectConvolutionLayer, CLDepthwiseConvolutionLayer, CLReshapeLayer, CLPoolingLayer >
using CLMobileNetV1_224_Fixture = MobileNetV1Fixture< CLTensor, CLAccessor, CLActivationLayer, CLBatchNormalizationLayer, CLConvolutionLayer, CLDirectConvolutionLayer, CLDepthwiseConvolutionLayer3x3, CLReshapeLayer, CLPoolingLayer, CLSoftmaxLayer, 224 >
using CLMobileNetV1_128_Fixture = MobileNetV1Fixture< CLTensor, CLAccessor, CLActivationLayer, CLBatchNormalizationLayer, CLConvolutionLayer, CLDirectConvolutionLayer, CLDepthwiseConvolutionLayer3x3, CLReshapeLayer, CLPoolingLayer, CLSoftmaxLayer, 128 >
using GCBatchNormalizationLayerFixture = BatchNormalizationLayerFixture< GCTensor, GCBatchNormalizationLayer, GCAccessor >
using GCConvolutionLayerFixture = ConvolutionLayerFixture< GCTensor, GCConvolutionLayer, GCAccessor >
using GCDepthwiseConvolutionLayerFixture = DepthwiseConvolutionLayerFixture< GCTensor, GCDepthwiseConvolutionLayer3x3, GCAccessor >
using GCFullyConnectedLayerFixture = FullyConnectedLayerFixture< GCTensor, GCFullyConnectedLayer, GCAccessor >
using GCGEMMFixture = GEMMFixture< GCTensor, GCGEMM, GCAccessor >
using GCNormalizePlanarYUVLayerFixture = NormalizePlanarYUVLayerFixture< GCTensor, GCNormalizePlanarYUVLayer, GCAccessor >
using GCPoolingLayerFixture = PoolingLayerFixture< GCTensor, GCPoolingLayer, GCAccessor >
template<typename T >
using GCScaleLayerFixture = ScaleLayerFixture< GCTensor, GCScale, GCAccessor, T >
using GCSoftmaxLayerFixture = SoftmaxLayerFixture< GCTensor, GCSoftmaxLayer, GCAccessor >
using NEActivationLayerFixture = ActivationLayerFixture< Tensor, NEActivationLayer, Accessor >
using NEBatchNormalizationLayerFixture = BatchNormalizationLayerFixture< Tensor, NEBatchNormalizationLayer, Accessor >
using NEConvolutionLayerFixture = ConvolutionLayerFixture< Tensor, NEConvolutionLayer, Accessor >
using NEFloorFixture = FloorFixture< Tensor, NEFloor, Accessor >
using NEFullyConnectedLayerFixture = FullyConnectedLayerFixture< Tensor, NEFullyConnectedLayer, Accessor >
using NEGEMMFixture = GEMMFixture< Tensor, NEGEMM, Accessor >
using NEGEMMLowpFixture = GEMMLowpMatrixMultiplyCoreFixture< Tensor, NEGEMMLowpMatrixMultiplyCore, Accessor >
using NENormalizationLayerFixture = NormalizationLayerFixture< Tensor, NENormalizationLayer, Accessor >
using NEPoolingLayerFixture = PoolingLayerFixture< Tensor, NEPoolingLayer, Accessor >
using NEROIPoolingLayerFixture = ROIPoolingLayerFixture< Tensor, NEROIPoolingLayer, Accessor, Array< ROI >, ArrayAccessor< ROI >>
using NESoftmaxLayerFixture = SoftmaxLayerFixture< Tensor, NESoftmaxLayer, Accessor >
using NEAlexNetFixture = AlexNetFixture< ITensor, Tensor, SubTensor, Accessor, NEActivationLayer, NEConvolutionLayer, NEConvolutionLayer, NEFullyConnectedLayer, NENormalizationLayer, NEPoolingLayer, NESoftmaxLayer >
using NELeNet5Fixture = LeNet5Fixture< Tensor, Accessor, NEActivationLayer, NEConvolutionLayer, NEFullyConnectedLayer, NEPoolingLayer, NESoftmaxLayer >
Functions
REGISTER_FIXTURE_DATA_TEST_CASE (YOLOV2BatchNormalizationLayer, CLBatchNormalizationLayerFixture, framework::DatasetMode::ALL, framework::dataset::combine(framework::dataset::combine(datasets::YOLOV2BatchNormalizationLayerDataset(), data_types), framework::dataset::make("Batches", 1)))
REGISTER_FIXTURE_DATA_TEST_CASE (GoogLeNetInceptionV4BatchNormalizationLayer, CLBatchNormalizationLayerFixture, framework::DatasetMode::ALL, framework::dataset::combine(framework::dataset::combine(datasets::GoogLeNetInceptionV4BatchNormalizationLayerDataset(), data_types), framework::dataset::make("Batches", 1)))
REGISTER_FIXTURE_DATA_TEST_CASE (YOLOV2BatchNormalizationLayer, CLBatchNormalizationLayerFixture, framework::DatasetMode::NIGHTLY, framework::dataset::combine(framework::dataset::combine(datasets::YOLOV2BatchNormalizationLayerDataset(), data_types), framework::dataset::make("Batches",{4, 8})))
REGISTER_FIXTURE_DATA_TEST_CASE (GoogLeNetInceptionV4BatchNormalizationLayer, CLBatchNormalizationLayerFixture, framework::DatasetMode::NIGHTLY, framework::dataset::combine(framework::dataset::combine(datasets::GoogLeNetInceptionV4BatchNormalizationLayerDataset(), data_types), framework::dataset::make("Batches",{4, 8})))
REGISTER_FIXTURE_DATA_TEST_CASE (AlexNetConvolutionLayer, CLConvolutionLayerFixture, framework::DatasetMode::ALL, framework::dataset::combine(framework::dataset::combine(datasets::AlexNetConvolutionLayerDataset(), data_types), framework::dataset::make("Batches", 1)))
REGISTER_FIXTURE_DATA_TEST_CASE (LeNet5ConvolutionLayer, CLConvolutionLayerFixture, framework::DatasetMode::ALL, framework::dataset::combine(framework::dataset::combine(datasets::LeNet5ConvolutionLayerDataset(), data_types), framework::dataset::make("Batches", 1)))
REGISTER_FIXTURE_DATA_TEST_CASE (GoogLeNetInceptionV1ConvolutionLayer, CLConvolutionLayerFixture, framework::DatasetMode::ALL, framework::dataset::combine(framework::dataset::combine(datasets::GoogLeNetInceptionV1ConvolutionLayerDataset(), data_types), framework::dataset::make("Batches", 1)))
REGISTER_FIXTURE_DATA_TEST_CASE (GoogLeNetInceptionV4ConvolutionLayer, CLConvolutionLayerFixture, framework::DatasetMode::ALL, framework::dataset::combine(framework::dataset::combine(datasets::GoogLeNetInceptionV4ConvolutionLayerDataset(), data_types), framework::dataset::make("Batches", 1)))
REGISTER_FIXTURE_DATA_TEST_CASE (SqueezeNetConvolutionLayer, CLConvolutionLayerFixture, framework::DatasetMode::ALL, framework::dataset::combine(framework::dataset::combine(datasets::SqueezeNetConvolutionLayerDataset(), data_types), framework::dataset::make("Batches", 1)))
REGISTER_FIXTURE_DATA_TEST_CASE (AlexNetConvolutionLayer, CLConvolutionLayerFixture, framework::DatasetMode::NIGHTLY, framework::dataset::combine(framework::dataset::combine(datasets::AlexNetConvolutionLayerDataset(), data_types), framework::dataset::make("Batches",{4, 8})))
REGISTER_FIXTURE_DATA_TEST_CASE (LeNet5ConvolutionLayer, CLConvolutionLayerFixture, framework::DatasetMode::NIGHTLY, framework::dataset::combine(framework::dataset::combine(datasets::LeNet5ConvolutionLayerDataset(), data_types), framework::dataset::make("Batches",{4, 8})))
REGISTER_FIXTURE_DATA_TEST_CASE (GoogLeNetInceptionV1ConvolutionLayer, CLConvolutionLayerFixture, framework::DatasetMode::NIGHTLY, framework::dataset::combine(framework::dataset::combine(datasets::GoogLeNetInceptionV1ConvolutionLayerDataset(), data_types), framework::dataset::make("Batches",{4, 8})))
REGISTER_FIXTURE_DATA_TEST_CASE (GoogLeNetInceptionV4ConvolutionLayer, CLConvolutionLayerFixture, framework::DatasetMode::NIGHTLY, framework::dataset::combine(framework::dataset::combine(datasets::GoogLeNetInceptionV4ConvolutionLayerDataset(), data_types), framework::dataset::make("Batches",{4, 8})))
REGISTER_FIXTURE_DATA_TEST_CASE (SqueezeNetConvolutionLayer, CLConvolutionLayerFixture, framework::DatasetMode::NIGHTLY, framework::dataset::combine(framework::dataset::combine(datasets::SqueezeNetConvolutionLayerDataset(), data_types), framework::dataset::make("Batches",{4, 8})))
REGISTER_FIXTURE_DATA_TEST_CASE (VGG16ConvolutionLayer, CLConvolutionLayerFixture, framework::DatasetMode::NIGHTLY, framework::dataset::combine(framework::dataset::combine(datasets::VGG16ConvolutionLayerDataset(), data_types), framework::dataset::make("Batches",{1, 4})))
REGISTER_FIXTURE_DATA_TEST_CASE (YOLOV2ConvolutionLayer, CLConvolutionLayerFixture, framework::DatasetMode::NIGHTLY, framework::dataset::combine(framework::dataset::combine(datasets::YOLOV2ConvolutionLayerDataset(), data_types), framework::dataset::make("Batches",{1, 4, 8})))
REGISTER_FIXTURE_DATA_TEST_CASE (MobileNetDepthwiseConvLayer, CLDepthwiseConvolutionLayerFixture, framework::DatasetMode::ALL, framework::dataset::combine(framework::dataset::combine(datasets::MobileNetDepthwiseConvolutionLayerDataset(), data_types), framework::dataset::make("Batches",{1})))
REGISTER_FIXTURE_DATA_TEST_CASE (MobileNetDepthwiseSeparableConvolutionLayer, CLDepthwiseSeparableConvolutionLayerFixture, framework::DatasetMode::ALL, framework::dataset::combine(framework::dataset::combine(datasets::MobileNetDepthwiseSeparableConvolutionLayerDataset(), data_types), framework::dataset::make("Batches",{1})))
REGISTER_FIXTURE_DATA_TEST_CASE (AlexNetDirectConvolutionLayer, CLConvolutionLayerFixture, framework::DatasetMode::ALL, framework::dataset::combine(framework::dataset::combine(datasets::AlexNetDirectConvolutionLayerDataset(), data_types), framework::dataset::make("Batches", 1)))
REGISTER_FIXTURE_DATA_TEST_CASE (GoogLeNetInceptionV1DirectConvolutionLayer, CLConvolutionLayerFixture, framework::DatasetMode::ALL, framework::dataset::combine(framework::dataset::combine(datasets::GoogLeNetInceptionV1DirectConvolutionLayerDataset(), data_types), framework::dataset::make("Batches", 1)))
REGISTER_FIXTURE_DATA_TEST_CASE (GoogLeNetInceptionV4DirectConvolutionLayer, CLConvolutionLayerFixture, framework::DatasetMode::ALL, framework::dataset::combine(framework::dataset::combine(datasets::GoogLeNetInceptionV4DirectConvolutionLayerDataset(), data_types), framework::dataset::make("Batches", 1)))
REGISTER_FIXTURE_DATA_TEST_CASE (SqueezeNetDirectConvolutionLayer, CLConvolutionLayerFixture, framework::DatasetMode::ALL, framework::dataset::combine(framework::dataset::combine(datasets::SqueezeNetConvolutionLayerDataset(), data_types), framework::dataset::make("Batches", 1)))
REGISTER_FIXTURE_DATA_TEST_CASE (AlexNetDirectConvolutionLayer, CLConvolutionLayerFixture, framework::DatasetMode::NIGHTLY, framework::dataset::combine(framework::dataset::combine(datasets::AlexNetDirectConvolutionLayerDataset(), data_types), framework::dataset::make("Batches",{4, 8})))
REGISTER_FIXTURE_DATA_TEST_CASE (GoogLeNetInceptionV1DirectConvolutionLayer, CLConvolutionLayerFixture, framework::DatasetMode::NIGHTLY, framework::dataset::combine(framework::dataset::combine(datasets::GoogLeNetInceptionV1DirectConvolutionLayerDataset(), data_types), framework::dataset::make("Batches",{4, 8})))
REGISTER_FIXTURE_DATA_TEST_CASE (GoogLeNetInceptionV4DirectConvolutionLayer, CLConvolutionLayerFixture, framework::DatasetMode::NIGHTLY, framework::dataset::combine(framework::dataset::combine(datasets::GoogLeNetInceptionV4DirectConvolutionLayerDataset(), data_types), framework::dataset::make("Batches",{4, 8})))
REGISTER_FIXTURE_DATA_TEST_CASE (SqueezeNetDirectConvolutionLayer, CLConvolutionLayerFixture, framework::DatasetMode::NIGHTLY, framework::dataset::combine(framework::dataset::combine(datasets::SqueezeNetConvolutionLayerDataset(), data_types), framework::dataset::make("Batches",{4, 8})))
REGISTER_FIXTURE_DATA_TEST_CASE (VGG16DirectConvolutionLayer, CLConvolutionLayerFixture, framework::DatasetMode::NIGHTLY, framework::dataset::combine(framework::dataset::combine(datasets::VGG16ConvolutionLayerDataset(), data_types), framework::dataset::make("Batches",{1, 4, 8})))
REGISTER_FIXTURE_DATA_TEST_CASE (YOLOV2DirectConvolutionLayer, CLConvolutionLayerFixture, framework::DatasetMode::NIGHTLY, framework::dataset::combine(framework::dataset::combine(datasets::YOLOV2ConvolutionLayerDataset(), data_types), framework::dataset::make("Batches",{1, 4, 8})))
REGISTER_FIXTURE_DATA_TEST_CASE (Floor, CLFloorFixture, framework::DatasetMode::ALL, framework::dataset::combine(datasets::SmallShapes(), data_types))
REGISTER_FIXTURE_DATA_TEST_CASE (AlexNetFullyConnectedLayer, CLFullyConnectedLayerFixture, framework::DatasetMode::ALL, framework::dataset::combine(framework::dataset::combine(datasets::AlexNetFullyConnectedLayerDataset(), data_types), framework::dataset::make("Batches", 1)))
REGISTER_FIXTURE_DATA_TEST_CASE (LeNet5FullyConnectedLayer, CLFullyConnectedLayerFixture, framework::DatasetMode::ALL, framework::dataset::combine(framework::dataset::combine(datasets::LeNet5FullyConnectedLayerDataset(), data_types), framework::dataset::make("Batches", 1)))
REGISTER_FIXTURE_DATA_TEST_CASE (VGG16FullyConnectedLayer, CLFullyConnectedLayerFixture, framework::DatasetMode::ALL, framework::dataset::combine(framework::dataset::combine(datasets::VGG16FullyConnectedLayerDataset(), data_types), framework::dataset::make("Batches", 1)))
REGISTER_FIXTURE_DATA_TEST_CASE (GoogLeNetInceptionV1FullyConnectedLayer, CLFullyConnectedLayerFixture, framework::DatasetMode::ALL, framework::dataset::combine(framework::dataset::combine(datasets::GoogLeNetInceptionV1FullyConnectedLayerDataset(), data_types), framework::dataset::make("Batches", 1)))
REGISTER_FIXTURE_DATA_TEST_CASE (GoogLeNetInceptionV4FullyConnectedLayer, CLFullyConnectedLayerFixture, framework::DatasetMode::ALL, framework::dataset::combine(framework::dataset::combine(datasets::GoogLeNetInceptionV4FullyConnectedLayerDataset(), data_types), framework::dataset::make("Batches", 1)))
REGISTER_FIXTURE_DATA_TEST_CASE (AlexNetFullyConnectedLayer, CLFullyConnectedLayerFixture, framework::DatasetMode::NIGHTLY, framework::dataset::combine(framework::dataset::combine(datasets::AlexNetFullyConnectedLayerDataset(), data_types), framework::dataset::make("Batches",{4, 8})))
REGISTER_FIXTURE_DATA_TEST_CASE (LeNet5FullyConnectedLayer, CLFullyConnectedLayerFixture, framework::DatasetMode::NIGHTLY, framework::dataset::combine(framework::dataset::combine(datasets::LeNet5FullyConnectedLayerDataset(), data_types), framework::dataset::make("Batches",{4, 8})))
REGISTER_FIXTURE_DATA_TEST_CASE (VGG16FullyConnectedLayer, CLFullyConnectedLayerFixture, framework::DatasetMode::NIGHTLY, framework::dataset::combine(framework::dataset::combine(datasets::VGG16FullyConnectedLayerDataset(), data_types), framework::dataset::make("Batches",{4, 8})))
REGISTER_FIXTURE_DATA_TEST_CASE (GoogLeNetInceptionV1FullyConnectedLayer, CLFullyConnectedLayerFixture, framework::DatasetMode::NIGHTLY, framework::dataset::combine(framework::dataset::combine(datasets::GoogLeNetInceptionV1FullyConnectedLayerDataset(), data_types), framework::dataset::make("Batches",{4, 8})))
REGISTER_FIXTURE_DATA_TEST_CASE (GoogLeNetInceptionV4FullyConnectedLayer, CLFullyConnectedLayerFixture, framework::DatasetMode::NIGHTLY, framework::dataset::combine(framework::dataset::combine(datasets::GoogLeNetInceptionV4FullyConnectedLayerDataset(), data_types), framework::dataset::make("Batches",{4, 8})))
REGISTER_FIXTURE_DATA_TEST_CASE (GoogLeNetInceptionV1GEMM, CLGEMMFixture, framework::DatasetMode::ALL, framework::dataset::combine(datasets::GoogLeNetInceptionV1GEMMDataset(), data_types))
REGISTER_FIXTURE_DATA_TEST_CASE (MatrixMultiplyGEMM, CLGEMMFixture, framework::DatasetMode::ALL, framework::dataset::combine(datasets::MatrixMultiplyGEMMDataset(), data_types))
REGISTER_FIXTURE_DATA_TEST_CASE (GoogleNetGEMM, CLGEMMFixture, framework::DatasetMode::NIGHTLY, framework::dataset::combine(datasets::GoogleNetGEMMDataset(), data_types))
REGISTER_FIXTURE_DATA_TEST_CASE (AlexNetGEMM, CLGEMMFixture, framework::DatasetMode::NIGHTLY, framework::dataset::combine(datasets::AlexNetGEMMDataset(), data_types))
REGISTER_FIXTURE_DATA_TEST_CASE (GoogLeNetInceptionV1GEMMLowp, CLGEMMLowpFixture, framework::DatasetMode::ALL, datasets::GoogLeNetInceptionV1GEMMDataset())
REGISTER_FIXTURE_DATA_TEST_CASE (MatrixMultiplyGEMMLowp, CLGEMMLowpFixture, framework::DatasetMode::ALL, datasets::MatrixMultiplyGEMMDataset())
REGISTER_FIXTURE_DATA_TEST_CASE (GoogleNetGEMMLowp, CLGEMMLowpFixture, framework::DatasetMode::NIGHTLY, datasets::GoogleNetGEMMDataset())
REGISTER_FIXTURE_DATA_TEST_CASE (AlexNetGEMMLowp, CLGEMMLowpFixture, framework::DatasetMode::NIGHTLY, datasets::AlexNetGEMMDataset())
REGISTER_FIXTURE_DATA_TEST_CASE (AlexNetNormalizationLayer, CLNormalizationLayerFixture, framework::DatasetMode::ALL, framework::dataset::combine(framework::dataset::combine(datasets::AlexNetNormalizationLayerDataset(), data_types), framework::dataset::make("Batches", 1)))
REGISTER_FIXTURE_DATA_TEST_CASE (GoogLeNetInceptionV1NormalizationLayer, CLNormalizationLayerFixture, framework::DatasetMode::ALL, framework::dataset::combine(framework::dataset::combine(datasets::GoogLeNetInceptionV1NormalizationLayerDataset(), data_types), framework::dataset::make("Batches", 1)))
REGISTER_FIXTURE_DATA_TEST_CASE (AlexNetNormalizationLayer, CLNormalizationLayerFixture, framework::DatasetMode::NIGHTLY, framework::dataset::combine(framework::dataset::combine(datasets::AlexNetNormalizationLayerDataset(), data_types), framework::dataset::make("Batches",{4, 8})))
REGISTER_FIXTURE_DATA_TEST_CASE (GoogLeNetInceptionV1NormalizationLayer, CLNormalizationLayerFixture, framework::DatasetMode::NIGHTLY, framework::dataset::combine(framework::dataset::combine(datasets::GoogLeNetInceptionV1NormalizationLayerDataset(), data_types), framework::dataset::make("Batches",{4, 8})))
REGISTER_FIXTURE_DATA_TEST_CASE (AlexNetPoolingLayer, CLPoolingLayerFixture, framework::DatasetMode::ALL, framework::dataset::combine(framework::dataset::combine(datasets::AlexNetPoolingLayerDataset(), data_types), framework::dataset::make("Batches", 1)))
REGISTER_FIXTURE_DATA_TEST_CASE (LeNet5PoolingLayer, CLPoolingLayerFixture, framework::DatasetMode::ALL, framework::dataset::combine(framework::dataset::combine(datasets::LeNet5PoolingLayerDataset(), data_types), framework::dataset::make("Batches", 1)))
REGISTER_FIXTURE_DATA_TEST_CASE (GoogLeNetInceptionV1PoolingLayer, CLPoolingLayerFixture, framework::DatasetMode::ALL, framework::dataset::combine(framework::dataset::combine(datasets::GoogLeNetInceptionV1PoolingLayerDataset(), data_types), framework::dataset::make("Batches", 1)))
REGISTER_FIXTURE_DATA_TEST_CASE (GoogLeNetInceptionV4PoolingLayer, CLPoolingLayerFixture, framework::DatasetMode::ALL, framework::dataset::combine(framework::dataset::combine(datasets::GoogLeNetInceptionV4PoolingLayerDataset(), data_types), framework::dataset::make("Batches", 1)))
REGISTER_FIXTURE_DATA_TEST_CASE (SqueezeNetPoolingLayer, CLPoolingLayerFixture, framework::DatasetMode::ALL, framework::dataset::combine(framework::dataset::combine(datasets::SqueezeNetPoolingLayerDataset(), data_types), framework::dataset::make("Batches", 1)))
REGISTER_FIXTURE_DATA_TEST_CASE (VGG16PoolingLayer, CLPoolingLayerFixture, framework::DatasetMode::ALL, framework::dataset::combine(framework::dataset::combine(datasets::VGG16PoolingLayerDataset(), data_types), framework::dataset::make("Batches", 1)))
REGISTER_FIXTURE_DATA_TEST_CASE (YOLOV2PoolingLayer, CLPoolingLayerFixture, framework::DatasetMode::ALL, framework::dataset::combine(framework::dataset::combine(datasets::YOLOV2PoolingLayerDataset(), data_types), framework::dataset::make("Batches", 1)))
REGISTER_FIXTURE_DATA_TEST_CASE (AlexNetPoolingLayer, CLPoolingLayerFixture, framework::DatasetMode::NIGHTLY, framework::dataset::combine(framework::dataset::combine(datasets::AlexNetPoolingLayerDataset(), data_types), framework::dataset::make("Batches",{4, 8})))
REGISTER_FIXTURE_DATA_TEST_CASE (LeNet5PoolingLayer, CLPoolingLayerFixture, framework::DatasetMode::NIGHTLY, framework::dataset::combine(framework::dataset::combine(datasets::LeNet5PoolingLayerDataset(), data_types), framework::dataset::make("Batches",{4, 8})))
REGISTER_FIXTURE_DATA_TEST_CASE (GoogLeNetInceptionV1PoolingLayer, CLPoolingLayerFixture, framework::DatasetMode::NIGHTLY, framework::dataset::combine(framework::dataset::combine(datasets::GoogLeNetInceptionV1PoolingLayerDataset(), data_types), framework::dataset::make("Batches",{4, 8})))
REGISTER_FIXTURE_DATA_TEST_CASE (GoogLeNetInceptionV4PoolingLayer, CLPoolingLayerFixture, framework::DatasetMode::NIGHTLY, framework::dataset::combine(framework::dataset::combine(datasets::GoogLeNetInceptionV4PoolingLayerDataset(), data_types), framework::dataset::make("Batches",{4, 8})))
REGISTER_FIXTURE_DATA_TEST_CASE (SqueezeNetPoolingLayer, CLPoolingLayerFixture, framework::DatasetMode::NIGHTLY, framework::dataset::combine(framework::dataset::combine(datasets::SqueezeNetPoolingLayerDataset(), data_types), framework::dataset::make("Batches",{4, 8})))
REGISTER_FIXTURE_DATA_TEST_CASE (VGG16PoolingLayer, CLPoolingLayerFixture, framework::DatasetMode::NIGHTLY, framework::dataset::combine(framework::dataset::combine(datasets::VGG16PoolingLayerDataset(), data_types), framework::dataset::make("Batches",{4, 8})))
REGISTER_FIXTURE_DATA_TEST_CASE (YOLOV2PoolingLayer, CLPoolingLayerFixture, framework::DatasetMode::NIGHTLY, framework::dataset::combine(framework::dataset::combine(datasets::YOLOV2PoolingLayerDataset(), data_types), framework::dataset::make("Batches",{4, 8})))
REGISTER_FIXTURE_DATA_TEST_CASE (SmallROIPoolingLayer, CLROIPoolingLayerFixture, framework::DatasetMode::ALL, framework::dataset::combine(framework::dataset::combine(datasets::SmallROIPoolingLayerDataset(), framework::dataset::make("DataType",{DataType::F16, DataType::F32})), framework::dataset::make("Batches",{1, 4, 8})))
REGISTER_FIXTURE_DATA_TEST_CASE (SoftmaxLayerSmall, CLSoftmaxLayerFixture, framework::DatasetMode::ALL, framework::dataset::combine(datasets::SoftmaxLayerSmallShapes(), data_types))
REGISTER_FIXTURE_DATA_TEST_CASE (SoftmaxLayerLarge, CLSoftmaxLayerFixture, framework::DatasetMode::NIGHTLY, framework::dataset::combine(datasets::SoftmaxLayerLargeShapes(), data_types))
REGISTER_FIXTURE_DATA_TEST_CASE (AlexNet, CLAlexNetFixture, framework::DatasetMode::ALL, framework::dataset::combine(framework::dataset::make("DataType",{DataType::F16, DataType::F32}), framework::dataset::make("Batches",{1, 2, 4})))
REGISTER_FIXTURE_DATA_TEST_CASE (LeNet5, CLLeNet5Fixture, framework::DatasetMode::ALL, framework::dataset::make("Batches",{1, 4, 8}))
REGISTER_FIXTURE_DATA_TEST_CASE (MobileNet, CLMobileNetFixture, framework::DatasetMode::ALL, framework::dataset::make("Batches",{1, 4, 8}))
REGISTER_FIXTURE_DATA_TEST_CASE (MobileNetV1_224, CLMobileNetV1_224_Fixture, framework::DatasetMode::ALL, framework::dataset::make("Batches",{1, 4, 8}))
REGISTER_FIXTURE_DATA_TEST_CASE (MobileNetV1_128, CLMobileNetV1_128_Fixture, framework::DatasetMode::ALL, framework::dataset::make("Batches",{1, 4, 8}))
REGISTER_FIXTURE_DATA_TEST_CASE (YOLOV2BatchNormalizationLayer, GCBatchNormalizationLayerFixture, framework::DatasetMode::ALL, framework::dataset::combine(framework::dataset::combine(datasets::YOLOV2BatchNormalizationLayerDataset(), data_types), framework::dataset::make("Batches", 1)))
REGISTER_FIXTURE_DATA_TEST_CASE (GoogLeNetInceptionV4BatchNormalizationLayer, GCBatchNormalizationLayerFixture, framework::DatasetMode::ALL, framework::dataset::combine(framework::dataset::combine(datasets::GoogLeNetInceptionV4BatchNormalizationLayerDataset(), data_types), framework::dataset::make("Batches", 1)))
REGISTER_FIXTURE_DATA_TEST_CASE (YOLOV2BatchNormalizationLayer, GCBatchNormalizationLayerFixture, framework::DatasetMode::NIGHTLY, framework::dataset::combine(framework::dataset::combine(datasets::YOLOV2BatchNormalizationLayerDataset(), data_types), framework::dataset::make("Batches",{4, 8})))
REGISTER_FIXTURE_DATA_TEST_CASE (GoogLeNetInceptionV4BatchNormalizationLayer, GCBatchNormalizationLayerFixture, framework::DatasetMode::NIGHTLY, framework::dataset::combine(framework::dataset::combine(datasets::GoogLeNetInceptionV4BatchNormalizationLayerDataset(), data_types), framework::dataset::make("Batches",{4, 8})))
REGISTER_FIXTURE_DATA_TEST_CASE (AlexNetConvolutionLayer, GCConvolutionLayerFixture, framework::DatasetMode::ALL, framework::dataset::combine(framework::dataset::combine(datasets::AlexNetConvolutionLayerDataset(), data_types), framework::dataset::make("Batches", 1)))
REGISTER_FIXTURE_DATA_TEST_CASE (LeNet5ConvolutionLayer, GCConvolutionLayerFixture, framework::DatasetMode::ALL, framework::dataset::combine(framework::dataset::combine(datasets::LeNet5ConvolutionLayerDataset(), data_types), framework::dataset::make("Batches", 1)))
REGISTER_FIXTURE_DATA_TEST_CASE (GoogLeNetInceptionV1ConvolutionLayer, GCConvolutionLayerFixture, framework::DatasetMode::ALL, framework::dataset::combine(framework::dataset::combine(datasets::GoogLeNetInceptionV1ConvolutionLayerDataset(), data_types), framework::dataset::make("Batches", 1)))
REGISTER_FIXTURE_DATA_TEST_CASE (GoogLeNetInceptionV4ConvolutionLayer, GCConvolutionLayerFixture, framework::DatasetMode::ALL, framework::dataset::combine(framework::dataset::combine(datasets::GoogLeNetInceptionV4ConvolutionLayerDataset(), data_types), framework::dataset::make("Batches", 1)))
REGISTER_FIXTURE_DATA_TEST_CASE (SqueezeNetConvolutionLayer, GCConvolutionLayerFixture, framework::DatasetMode::ALL, framework::dataset::combine(framework::dataset::combine(datasets::SqueezeNetConvolutionLayerDataset(), data_types), framework::dataset::make("Batches", 1)))
REGISTER_FIXTURE_DATA_TEST_CASE (AlexNetConvolutionLayer, GCConvolutionLayerFixture, framework::DatasetMode::NIGHTLY, framework::dataset::combine(framework::dataset::combine(datasets::AlexNetConvolutionLayerDataset(), data_types), framework::dataset::make("Batches",{4, 8})))
REGISTER_FIXTURE_DATA_TEST_CASE (LeNet5ConvolutionLayer, GCConvolutionLayerFixture, framework::DatasetMode::NIGHTLY, framework::dataset::combine(framework::dataset::combine(datasets::LeNet5ConvolutionLayerDataset(), data_types), framework::dataset::make("Batches",{4, 8})))
REGISTER_FIXTURE_DATA_TEST_CASE (GoogLeNetInceptionV1ConvolutionLayer, GCConvolutionLayerFixture, framework::DatasetMode::NIGHTLY, framework::dataset::combine(framework::dataset::combine(datasets::GoogLeNetInceptionV1ConvolutionLayerDataset(), data_types), framework::dataset::make("Batches",{4, 8})))
REGISTER_FIXTURE_DATA_TEST_CASE (GoogLeNetInceptionV4ConvolutionLayer, GCConvolutionLayerFixture, framework::DatasetMode::NIGHTLY, framework::dataset::combine(framework::dataset::combine(datasets::GoogLeNetInceptionV4ConvolutionLayerDataset(), data_types), framework::dataset::make("Batches",{4, 8})))
REGISTER_FIXTURE_DATA_TEST_CASE (SqueezeNetConvolutionLayer, GCConvolutionLayerFixture, framework::DatasetMode::NIGHTLY, framework::dataset::combine(framework::dataset::combine(datasets::SqueezeNetConvolutionLayerDataset(), data_types), framework::dataset::make("Batches",{4, 8})))
REGISTER_FIXTURE_DATA_TEST_CASE (VGG16ConvolutionLayer, GCConvolutionLayerFixture, framework::DatasetMode::NIGHTLY, framework::dataset::combine(framework::dataset::combine(datasets::VGG16ConvolutionLayerDataset(), data_types), framework::dataset::make("Batches",{1, 4})))
REGISTER_FIXTURE_DATA_TEST_CASE (YOLOV2ConvolutionLayer, GCConvolutionLayerFixture, framework::DatasetMode::NIGHTLY, framework::dataset::combine(framework::dataset::combine(datasets::YOLOV2ConvolutionLayerDataset(), data_types), framework::dataset::make("Batches",{1, 4, 8})))
REGISTER_FIXTURE_DATA_TEST_CASE (MobileNetDepthwiseConvLayer, GCDepthwiseConvolutionLayerFixture, framework::DatasetMode::ALL, framework::dataset::combine(framework::dataset::combine(datasets::MobileNetDepthwiseConvolutionLayerDataset(), data_types), framework::dataset::make("Batches",{1})))
REGISTER_FIXTURE_DATA_TEST_CASE (AlexNetDirectConvolutionLayer, GCConvolutionLayerFixture, framework::DatasetMode::ALL, framework::dataset::combine(framework::dataset::combine(datasets::AlexNetDirectConvolutionLayerDataset(), data_types), framework::dataset::make("Batches", 1)))
REGISTER_FIXTURE_DATA_TEST_CASE (GoogLeNetInceptionV1DirectConvolutionLayer, GCConvolutionLayerFixture, framework::DatasetMode::ALL, framework::dataset::combine(framework::dataset::combine(datasets::GoogLeNetInceptionV1DirectConvolutionLayerDataset(), data_types), framework::dataset::make("Batches", 1)))
REGISTER_FIXTURE_DATA_TEST_CASE (GoogLeNetInceptionV4DirectConvolutionLayer, GCConvolutionLayerFixture, framework::DatasetMode::ALL, framework::dataset::combine(framework::dataset::combine(datasets::GoogLeNetInceptionV4DirectConvolutionLayerDataset(), data_types), framework::dataset::make("Batches", 1)))
REGISTER_FIXTURE_DATA_TEST_CASE (SqueezeNetDirectConvolutionLayer, GCConvolutionLayerFixture, framework::DatasetMode::ALL, framework::dataset::combine(framework::dataset::combine(datasets::SqueezeNetConvolutionLayerDataset(), data_types), framework::dataset::make("Batches", 1)))
REGISTER_FIXTURE_DATA_TEST_CASE (AlexNetDirectConvolutionLayer, GCConvolutionLayerFixture, framework::DatasetMode::NIGHTLY, framework::dataset::combine(framework::dataset::combine(datasets::AlexNetDirectConvolutionLayerDataset(), data_types), framework::dataset::make("Batches",{4, 8})))
REGISTER_FIXTURE_DATA_TEST_CASE (GoogLeNetInceptionV1DirectConvolutionLayer, GCConvolutionLayerFixture, framework::DatasetMode::NIGHTLY, framework::dataset::combine(framework::dataset::combine(datasets::GoogLeNetInceptionV1DirectConvolutionLayerDataset(), data_types), framework::dataset::make("Batches",{4, 8})))
REGISTER_FIXTURE_DATA_TEST_CASE (GoogLeNetInceptionV4DirectConvolutionLayer, GCConvolutionLayerFixture, framework::DatasetMode::NIGHTLY, framework::dataset::combine(framework::dataset::combine(datasets::GoogLeNetInceptionV4DirectConvolutionLayerDataset(), data_types), framework::dataset::make("Batches",{4, 8})))
REGISTER_FIXTURE_DATA_TEST_CASE (SqueezeNetDirectConvolutionLayer, GCConvolutionLayerFixture, framework::DatasetMode::NIGHTLY, framework::dataset::combine(framework::dataset::combine(datasets::SqueezeNetConvolutionLayerDataset(), data_types), framework::dataset::make("Batches",{4, 8})))
REGISTER_FIXTURE_DATA_TEST_CASE (VGG16DirectConvolutionLayer, GCConvolutionLayerFixture, framework::DatasetMode::NIGHTLY, framework::dataset::combine(framework::dataset::combine(datasets::VGG16ConvolutionLayerDataset(), data_types), framework::dataset::make("Batches",{1, 4, 8})))
REGISTER_FIXTURE_DATA_TEST_CASE (YOLOV2DirectConvolutionLayer, GCConvolutionLayerFixture, framework::DatasetMode::NIGHTLY, framework::dataset::combine(framework::dataset::combine(datasets::YOLOV2ConvolutionLayerDataset(), data_types), framework::dataset::make("Batches",{1, 4, 8})))
REGISTER_FIXTURE_DATA_TEST_CASE (AlexNetFullyConnectedLayer, GCFullyConnectedLayerFixture, framework::DatasetMode::ALL, framework::dataset::combine(framework::dataset::combine(datasets::AlexNetFullyConnectedLayerDataset(), data_types), framework::dataset::make("Batches", 1)))
REGISTER_FIXTURE_DATA_TEST_CASE (LeNet5FullyConnectedLayer, GCFullyConnectedLayerFixture, framework::DatasetMode::ALL, framework::dataset::combine(framework::dataset::combine(datasets::LeNet5FullyConnectedLayerDataset(), data_types), framework::dataset::make("Batches", 1)))
REGISTER_FIXTURE_DATA_TEST_CASE (VGG16FullyConnectedLayer, GCFullyConnectedLayerFixture, framework::DatasetMode::ALL, framework::dataset::combine(framework::dataset::combine(datasets::VGG16FullyConnectedLayerDataset(), data_types), framework::dataset::make("Batches", 1)))
REGISTER_FIXTURE_DATA_TEST_CASE (GoogLeNetInceptionV1FullyConnectedLayer, GCFullyConnectedLayerFixture, framework::DatasetMode::ALL, framework::dataset::combine(framework::dataset::combine(datasets::GoogLeNetInceptionV1FullyConnectedLayerDataset(), data_types), framework::dataset::make("Batches", 1)))
REGISTER_FIXTURE_DATA_TEST_CASE (GoogLeNetInceptionV4FullyConnectedLayer, GCFullyConnectedLayerFixture, framework::DatasetMode::ALL, framework::dataset::combine(framework::dataset::combine(datasets::GoogLeNetInceptionV4FullyConnectedLayerDataset(), data_types), framework::dataset::make("Batches", 1)))
REGISTER_FIXTURE_DATA_TEST_CASE (AlexNetFullyConnectedLayer, GCFullyConnectedLayerFixture, framework::DatasetMode::NIGHTLY, framework::dataset::combine(framework::dataset::combine(datasets::AlexNetFullyConnectedLayerDataset(), data_types), framework::dataset::make("Batches",{4, 8})))
REGISTER_FIXTURE_DATA_TEST_CASE (LeNet5FullyConnectedLayer, GCFullyConnectedLayerFixture, framework::DatasetMode::NIGHTLY, framework::dataset::combine(framework::dataset::combine(datasets::LeNet5FullyConnectedLayerDataset(), data_types), framework::dataset::make("Batches",{4, 8})))
REGISTER_FIXTURE_DATA_TEST_CASE (VGG16FullyConnectedLayer, GCFullyConnectedLayerFixture, framework::DatasetMode::NIGHTLY, framework::dataset::combine(framework::dataset::combine(datasets::VGG16FullyConnectedLayerDataset(), data_types), framework::dataset::make("Batches",{4, 8})))
REGISTER_FIXTURE_DATA_TEST_CASE (GoogLeNetInceptionV1FullyConnectedLayer, GCFullyConnectedLayerFixture, framework::DatasetMode::NIGHTLY, framework::dataset::combine(framework::dataset::combine(datasets::GoogLeNetInceptionV1FullyConnectedLayerDataset(), data_types), framework::dataset::make("Batches",{4, 8})))
REGISTER_FIXTURE_DATA_TEST_CASE (GoogLeNetInceptionV4FullyConnectedLayer, GCFullyConnectedLayerFixture, framework::DatasetMode::NIGHTLY, framework::dataset::combine(framework::dataset::combine(datasets::GoogLeNetInceptionV4FullyConnectedLayerDataset(), data_types), framework::dataset::make("Batches",{4, 8})))
REGISTER_FIXTURE_DATA_TEST_CASE (GoogLeNetInceptionV1GEMM, GCGEMMFixture, framework::DatasetMode::ALL, framework::dataset::combine(datasets::GoogLeNetInceptionV1GEMMDataset(), data_types))
REGISTER_FIXTURE_DATA_TEST_CASE (MatrixMultiplyGEMM, GCGEMMFixture, framework::DatasetMode::ALL, framework::dataset::combine(datasets::MatrixMultiplyGEMMDataset(), data_types))
REGISTER_FIXTURE_DATA_TEST_CASE (GoogleNetGEMM, GCGEMMFixture, framework::DatasetMode::NIGHTLY, framework::dataset::combine(datasets::GoogleNetGEMMDataset(), data_types))
REGISTER_FIXTURE_DATA_TEST_CASE (GoogLeNetInceptionV4NormalizePlanarYUVLayer, GCNormalizePlanarYUVLayerFixture, framework::DatasetMode::ALL, framework::dataset::combine(framework::dataset::combine(datasets::GoogLeNetInceptionV4NormalizePlanarYUVLayerDataset(), data_types), framework::dataset::make("Batches", 1)))
REGISTER_FIXTURE_DATA_TEST_CASE (AlexNetPoolingLayer, GCPoolingLayerFixture, framework::DatasetMode::ALL, framework::dataset::combine(framework::dataset::combine(datasets::AlexNetPoolingLayerDataset(), data_types), framework::dataset::make("Batches", 1)))
REGISTER_FIXTURE_DATA_TEST_CASE (LeNet5PoolingLayer, GCPoolingLayerFixture, framework::DatasetMode::ALL, framework::dataset::combine(framework::dataset::combine(datasets::LeNet5PoolingLayerDataset(), data_types), framework::dataset::make("Batches", 1)))
REGISTER_FIXTURE_DATA_TEST_CASE (GoogLeNetInceptionV1PoolingLayer, GCPoolingLayerFixture, framework::DatasetMode::ALL, framework::dataset::combine(framework::dataset::combine(datasets::GoogLeNetInceptionV1PoolingLayerDataset(), data_types), framework::dataset::make("Batches", 1)))
REGISTER_FIXTURE_DATA_TEST_CASE (GoogLeNetInceptionV4PoolingLayer, GCPoolingLayerFixture, framework::DatasetMode::ALL, framework::dataset::combine(framework::dataset::combine(datasets::GoogLeNetInceptionV4PoolingLayerDataset(), data_types), framework::dataset::make("Batches", 1)))
REGISTER_FIXTURE_DATA_TEST_CASE (SqueezeNetPoolingLayer, GCPoolingLayerFixture, framework::DatasetMode::ALL, framework::dataset::combine(framework::dataset::combine(datasets::SqueezeNetPoolingLayerDataset(), data_types), framework::dataset::make("Batches", 1)))
REGISTER_FIXTURE_DATA_TEST_CASE (VGG16PoolingLayer, GCPoolingLayerFixture, framework::DatasetMode::ALL, framework::dataset::combine(framework::dataset::combine(datasets::VGG16PoolingLayerDataset(), data_types), framework::dataset::make("Batches", 1)))
REGISTER_FIXTURE_DATA_TEST_CASE (YOLOV2PoolingLayer, GCPoolingLayerFixture, framework::DatasetMode::ALL, framework::dataset::combine(framework::dataset::combine(datasets::YOLOV2PoolingLayerDataset(), data_types), framework::dataset::make("Batches", 1)))
REGISTER_FIXTURE_DATA_TEST_CASE (AlexNetPoolingLayer, GCPoolingLayerFixture, framework::DatasetMode::NIGHTLY, framework::dataset::combine(framework::dataset::combine(datasets::AlexNetPoolingLayerDataset(), data_types), framework::dataset::make("Batches",{4, 8})))
REGISTER_FIXTURE_DATA_TEST_CASE (LeNet5PoolingLayer, GCPoolingLayerFixture, framework::DatasetMode::NIGHTLY, framework::dataset::combine(framework::dataset::combine(datasets::LeNet5PoolingLayerDataset(), data_types), framework::dataset::make("Batches",{4, 8})))
REGISTER_FIXTURE_DATA_TEST_CASE (GoogLeNetInceptionV1PoolingLayer, GCPoolingLayerFixture, framework::DatasetMode::NIGHTLY, framework::dataset::combine(framework::dataset::combine(datasets::GoogLeNetInceptionV1PoolingLayerDataset(), data_types), framework::dataset::make("Batches",{4, 8})))
REGISTER_FIXTURE_DATA_TEST_CASE (GoogLeNetInceptionV4PoolingLayer, GCPoolingLayerFixture, framework::DatasetMode::NIGHTLY, framework::dataset::combine(framework::dataset::combine(datasets::GoogLeNetInceptionV4PoolingLayerDataset(), data_types), framework::dataset::make("Batches",{4, 8})))
REGISTER_FIXTURE_DATA_TEST_CASE (SqueezeNetPoolingLayer, GCPoolingLayerFixture, framework::DatasetMode::NIGHTLY, framework::dataset::combine(framework::dataset::combine(datasets::SqueezeNetPoolingLayerDataset(), data_types), framework::dataset::make("Batches",{4, 8})))
REGISTER_FIXTURE_DATA_TEST_CASE (VGG16PoolingLayer, GCPoolingLayerFixture, framework::DatasetMode::NIGHTLY, framework::dataset::combine(framework::dataset::combine(datasets::VGG16PoolingLayerDataset(), data_types), framework::dataset::make("Batches",{4, 8})))
REGISTER_FIXTURE_DATA_TEST_CASE (YOLOV2PoolingLayer, GCPoolingLayerFixture, framework::DatasetMode::NIGHTLY, framework::dataset::combine(framework::dataset::combine(datasets::YOLOV2PoolingLayerDataset(), data_types), framework::dataset::make("Batches",{4, 8})))
REGISTER_FIXTURE_DATA_TEST_CASE (SmallScaleLayer, GCScaleLayerFixture< half >, framework::DatasetMode::ALL, framework::dataset::combine(datasets::SmallScaleLayerShapes(), data_types))
REGISTER_FIXTURE_DATA_TEST_CASE (LargeScaleLayer, GCScaleLayerFixture< half >, framework::DatasetMode::NIGHTLY, framework::dataset::combine(datasets::LargeScaleLayerShapes(), data_types))
REGISTER_FIXTURE_DATA_TEST_CASE (SoftmaxLayer, GCSoftmaxLayerFixture, framework::DatasetMode::ALL, framework::dataset::combine(datasets::SoftmaxLayerSmallShapes(), data_types))
REGISTER_FIXTURE_DATA_TEST_CASE (SoftmaxLayer, GCSoftmaxLayerFixture, framework::DatasetMode::NIGHTLY, framework::dataset::combine(datasets::SoftmaxLayerLargeShapes(), data_types))
REGISTER_FIXTURE_DATA_TEST_CASE (AlexNetActivationLayer, NEActivationLayerFixture, framework::DatasetMode::ALL, framework::dataset::combine(framework::dataset::combine(datasets::AlexNetActivationLayerDataset(), data_types), framework::dataset::make("Batches", 1)))
REGISTER_FIXTURE_DATA_TEST_CASE (LeNet5ActivationLayer, NEActivationLayerFixture, framework::DatasetMode::ALL, framework::dataset::combine(framework::dataset::combine(datasets::LeNet5ActivationLayerDataset(), data_types), framework::dataset::make("Batches", 1)))
REGISTER_FIXTURE_DATA_TEST_CASE (MobileNetActivationLayer, NEActivationLayerFixture, framework::DatasetMode::ALL, framework::dataset::combine(framework::dataset::combine(datasets::MobileNetActivationLayerDataset(), data_types_mobilenet), framework::dataset::make("Batches", 1)))
REGISTER_FIXTURE_DATA_TEST_CASE (GoogLeNetInceptionV1ActivationLayer, NEActivationLayerFixture, framework::DatasetMode::ALL, framework::dataset::combine(framework::dataset::combine(datasets::GoogLeNetInceptionV1ActivationLayerDataset(), data_types), framework::dataset::make("Batches", 1)))
REGISTER_FIXTURE_DATA_TEST_CASE (GoogLeNetInceptionV4ActivationLayer, NEActivationLayerFixture, framework::DatasetMode::ALL, framework::dataset::combine(framework::dataset::combine(datasets::GoogLeNetInceptionV4ActivationLayerDataset(), data_types), framework::dataset::make("Batches", 1)))
REGISTER_FIXTURE_DATA_TEST_CASE (SqueezeNetActivationLayer, NEActivationLayerFixture, framework::DatasetMode::ALL, framework::dataset::combine(framework::dataset::combine(datasets::SqueezeNetActivationLayerDataset(), data_types), framework::dataset::make("Batches", 1)))
REGISTER_FIXTURE_DATA_TEST_CASE (VGG16ActivationLayer, NEActivationLayerFixture, framework::DatasetMode::ALL, framework::dataset::combine(framework::dataset::combine(datasets::VGG16ActivationLayerDataset(), data_types), framework::dataset::make("Batches", 1)))
REGISTER_FIXTURE_DATA_TEST_CASE (YOLOV2ActivationLayer, NEActivationLayerFixture, framework::DatasetMode::ALL, framework::dataset::combine(framework::dataset::combine(datasets::YOLOV2ActivationLayerDataset(), data_types), framework::dataset::make("Batches", 1)))
REGISTER_FIXTURE_DATA_TEST_CASE (AlexNetActivationLayer, NEActivationLayerFixture, framework::DatasetMode::NIGHTLY, framework::dataset::combine(framework::dataset::combine(datasets::AlexNetActivationLayerDataset(), data_types), framework::dataset::make("Batches",{4, 8})))
REGISTER_FIXTURE_DATA_TEST_CASE (LeNet5ActivationLayer, NEActivationLayerFixture, framework::DatasetMode::NIGHTLY, framework::dataset::combine(framework::dataset::combine(datasets::LeNet5ActivationLayerDataset(), data_types), framework::dataset::make("Batches",{4, 8})))
REGISTER_FIXTURE_DATA_TEST_CASE (MobileNetActivationLayer, NEActivationLayerFixture, framework::DatasetMode::NIGHTLY, framework::dataset::combine(framework::dataset::combine(datasets::MobileNetActivationLayerDataset(), data_types_mobilenet), framework::dataset::make("Batches",{4, 8})))
REGISTER_FIXTURE_DATA_TEST_CASE (GoogLeNetInceptionV1ActivationLayer, NEActivationLayerFixture, framework::DatasetMode::NIGHTLY, framework::dataset::combine(framework::dataset::combine(datasets::GoogLeNetInceptionV1ActivationLayerDataset(), data_types), framework::dataset::make("Batches",{4, 8})))
REGISTER_FIXTURE_DATA_TEST_CASE (GoogLeNetInceptionV4ActivationLayer, NEActivationLayerFixture, framework::DatasetMode::NIGHTLY, framework::dataset::combine(framework::dataset::combine(datasets::GoogLeNetInceptionV4ActivationLayerDataset(), data_types), framework::dataset::make("Batches",{4, 8})))
REGISTER_FIXTURE_DATA_TEST_CASE (SqueezeNetActivationLayer, NEActivationLayerFixture, framework::DatasetMode::NIGHTLY, framework::dataset::combine(framework::dataset::combine(datasets::SqueezeNetActivationLayerDataset(), data_types), framework::dataset::make("Batches",{4, 8})))
REGISTER_FIXTURE_DATA_TEST_CASE (VGG16ActivationLayer, NEActivationLayerFixture, framework::DatasetMode::NIGHTLY, framework::dataset::combine(framework::dataset::combine(datasets::VGG16ActivationLayerDataset(), data_types), framework::dataset::make("Batches",{2})))
REGISTER_FIXTURE_DATA_TEST_CASE (YOLOV2ActivationLayer, NEActivationLayerFixture, framework::DatasetMode::NIGHTLY, framework::dataset::combine(framework::dataset::combine(datasets::YOLOV2ActivationLayerDataset(), data_types), framework::dataset::make("Batches",{4, 8})))
REGISTER_FIXTURE_DATA_TEST_CASE (YOLOV2BatchNormalizationLayer, NEBatchNormalizationLayerFixture, framework::DatasetMode::ALL, framework::dataset::combine(framework::dataset::combine(datasets::YOLOV2BatchNormalizationLayerDataset(), data_types), framework::dataset::make("Batches", 1)))
REGISTER_FIXTURE_DATA_TEST_CASE (GoogLeNetInceptionV4BatchNormalizationLayer, NEBatchNormalizationLayerFixture, framework::DatasetMode::ALL, framework::dataset::combine(framework::dataset::combine(datasets::GoogLeNetInceptionV4BatchNormalizationLayerDataset(), data_types), framework::dataset::make("Batches", 1)))
REGISTER_FIXTURE_DATA_TEST_CASE (YOLOV2BatchNormalizationLayer, NEBatchNormalizationLayerFixture, framework::DatasetMode::NIGHTLY, framework::dataset::combine(framework::dataset::combine(datasets::YOLOV2BatchNormalizationLayerDataset(), data_types), framework::dataset::make("Batches",{4, 8})))
REGISTER_FIXTURE_DATA_TEST_CASE (GoogLeNetInceptionV4BatchNormalizationLayer, NEBatchNormalizationLayerFixture, framework::DatasetMode::NIGHTLY, framework::dataset::combine(framework::dataset::combine(datasets::GoogLeNetInceptionV4BatchNormalizationLayerDataset(), data_types), framework::dataset::make("Batches",{4, 8})))
REGISTER_FIXTURE_DATA_TEST_CASE (AlexNetConvolutionLayer, NEConvolutionLayerFixture, framework::DatasetMode::ALL, framework::dataset::combine(framework::dataset::combine(datasets::AlexNetConvolutionLayerDataset(), data_types), framework::dataset::make("Batches", 1)))
REGISTER_FIXTURE_DATA_TEST_CASE (LeNet5ConvolutionLayer, NEConvolutionLayerFixture, framework::DatasetMode::ALL, framework::dataset::combine(framework::dataset::combine(datasets::LeNet5ConvolutionLayerDataset(), data_types), framework::dataset::make("Batches", 1)))
REGISTER_FIXTURE_DATA_TEST_CASE (GoogLeNetInceptionV1ConvolutionLayer, NEConvolutionLayerFixture, framework::DatasetMode::ALL, framework::dataset::combine(framework::dataset::combine(datasets::GoogLeNetInceptionV1ConvolutionLayerDataset(), data_types), framework::dataset::make("Batches", 1)))
REGISTER_FIXTURE_DATA_TEST_CASE (GoogLeNetInceptionV4ConvolutionLayer, NEConvolutionLayerFixture, framework::DatasetMode::ALL, framework::dataset::combine(framework::dataset::combine(datasets::GoogLeNetInceptionV4ConvolutionLayerDataset(), data_types), framework::dataset::make("Batches", 1)))
REGISTER_FIXTURE_DATA_TEST_CASE (SqueezeNetConvolutionLayer, NEConvolutionLayerFixture, framework::DatasetMode::ALL, framework::dataset::combine(framework::dataset::combine(datasets::SqueezeNetConvolutionLayerDataset(), data_types), framework::dataset::make("Batches", 1)))
REGISTER_FIXTURE_DATA_TEST_CASE (AlexNetConvolutionLayer, NEConvolutionLayerFixture, framework::DatasetMode::NIGHTLY, framework::dataset::combine(framework::dataset::combine(datasets::AlexNetConvolutionLayerDataset(), data_types), framework::dataset::make("Batches",{4, 8})))
REGISTER_FIXTURE_DATA_TEST_CASE (LeNet5ConvolutionLayer, NEConvolutionLayerFixture, framework::DatasetMode::NIGHTLY, framework::dataset::combine(framework::dataset::combine(datasets::LeNet5ConvolutionLayerDataset(), data_types), framework::dataset::make("Batches",{4, 8})))
REGISTER_FIXTURE_DATA_TEST_CASE (GoogLeNetInceptionV1ConvolutionLayer, NEConvolutionLayerFixture, framework::DatasetMode::NIGHTLY, framework::dataset::combine(framework::dataset::combine(datasets::GoogLeNetInceptionV1ConvolutionLayerDataset(), data_types), framework::dataset::make("Batches",{4, 8})))
REGISTER_FIXTURE_DATA_TEST_CASE (GoogLeNetInceptionV4ConvolutionLayer, NEConvolutionLayerFixture, framework::DatasetMode::NIGHTLY, framework::dataset::combine(framework::dataset::combine(datasets::GoogLeNetInceptionV4ConvolutionLayerDataset(), data_types), framework::dataset::make("Batches",{4, 8})))
REGISTER_FIXTURE_DATA_TEST_CASE (SqueezeNetConvolutionLayer, NEConvolutionLayerFixture, framework::DatasetMode::NIGHTLY, framework::dataset::combine(framework::dataset::combine(datasets::SqueezeNetConvolutionLayerDataset(), data_types), framework::dataset::make("Batches",{4, 8})))
REGISTER_FIXTURE_DATA_TEST_CASE (VGG16ConvolutionLayer, NEConvolutionLayerFixture, framework::DatasetMode::NIGHTLY, framework::dataset::combine(framework::dataset::combine(datasets::VGG16ConvolutionLayerDataset(), data_types), framework::dataset::make("Batches",{1, 2})))
REGISTER_FIXTURE_DATA_TEST_CASE (YOLOV2ConvolutionLayer, NEConvolutionLayerFixture, framework::DatasetMode::NIGHTLY, framework::dataset::combine(framework::dataset::combine(datasets::YOLOV2ConvolutionLayerDataset(), data_types), framework::dataset::make("Batches",{1, 4, 8})))
REGISTER_FIXTURE_DATA_TEST_CASE (AlexNetDirectConvolutionLayer, NEConvolutionLayerFixture, framework::DatasetMode::ALL, framework::dataset::combine(framework::dataset::combine(datasets::AlexNetDirectConvolutionLayerDataset(), data_types), framework::dataset::make("Batches", 1)))
REGISTER_FIXTURE_DATA_TEST_CASE (GoogLeNetInceptionV1DirectConvolutionLayer, NEConvolutionLayerFixture, framework::DatasetMode::ALL, framework::dataset::combine(framework::dataset::combine(datasets::GoogLeNetInceptionV1DirectConvolutionLayerDataset(), data_types), framework::dataset::make("Batches", 1)))
REGISTER_FIXTURE_DATA_TEST_CASE (GoogLeNetInceptionV4DirectConvolutionLayer, NEConvolutionLayerFixture, framework::DatasetMode::ALL, framework::dataset::combine(framework::dataset::combine(datasets::GoogLeNetInceptionV4DirectConvolutionLayerDataset(), data_types), framework::dataset::make("Batches", 1)))
REGISTER_FIXTURE_DATA_TEST_CASE (SqueezeNetDirectConvolutionLayer, NEConvolutionLayerFixture, framework::DatasetMode::ALL, framework::dataset::combine(framework::dataset::combine(datasets::SqueezeNetConvolutionLayerDataset(), data_types), framework::dataset::make("Batches", 1)))
REGISTER_FIXTURE_DATA_TEST_CASE (AlexNetDirectConvolutionLayer, NEConvolutionLayerFixture, framework::DatasetMode::NIGHTLY, framework::dataset::combine(framework::dataset::combine(datasets::AlexNetDirectConvolutionLayerDataset(), data_types), framework::dataset::make("Batches",{4, 8})))
REGISTER_FIXTURE_DATA_TEST_CASE (GoogLeNetInceptionV1DirectConvolutionLayer, NEConvolutionLayerFixture, framework::DatasetMode::NIGHTLY, framework::dataset::combine(framework::dataset::combine(datasets::GoogLeNetInceptionV1DirectConvolutionLayerDataset(), data_types), framework::dataset::make("Batches",{4, 8})))
REGISTER_FIXTURE_DATA_TEST_CASE (GoogLeNetInceptionV4DirectConvolutionLayer, NEConvolutionLayerFixture, framework::DatasetMode::NIGHTLY, framework::dataset::combine(framework::dataset::combine(datasets::GoogLeNetInceptionV4DirectConvolutionLayerDataset(), data_types), framework::dataset::make("Batches",{4, 8})))
REGISTER_FIXTURE_DATA_TEST_CASE (SqueezeNetDirectConvolutionLayer, NEConvolutionLayerFixture, framework::DatasetMode::NIGHTLY, framework::dataset::combine(framework::dataset::combine(datasets::SqueezeNetConvolutionLayerDataset(), data_types), framework::dataset::make("Batches",{4, 8})))
REGISTER_FIXTURE_DATA_TEST_CASE (VGG16DirectConvolutionLayer, NEConvolutionLayerFixture, framework::DatasetMode::NIGHTLY, framework::dataset::combine(framework::dataset::combine(datasets::VGG16ConvolutionLayerDataset(), data_types), framework::dataset::make("Batches",{1, 2})))
REGISTER_FIXTURE_DATA_TEST_CASE (YOLOV2DirectConvolutionLayer, NEConvolutionLayerFixture, framework::DatasetMode::NIGHTLY, framework::dataset::combine(framework::dataset::combine(datasets::YOLOV2ConvolutionLayerDataset(), data_types), framework::dataset::make("Batches",{1, 4, 8})))
REGISTER_FIXTURE_DATA_TEST_CASE (Floor, NEFloorFixture, framework::DatasetMode::ALL, framework::dataset::combine(datasets::SmallShapes(), data_types))
REGISTER_FIXTURE_DATA_TEST_CASE (AlexNetFullyConnectedLayer, NEFullyConnectedLayerFixture, framework::DatasetMode::ALL, framework::dataset::combine(framework::dataset::combine(datasets::AlexNetFullyConnectedLayerDataset(), data_types), framework::dataset::make("Batches", 1)))
REGISTER_FIXTURE_DATA_TEST_CASE (LeNet5FullyConnectedLayer, NEFullyConnectedLayerFixture, framework::DatasetMode::ALL, framework::dataset::combine(framework::dataset::combine(datasets::LeNet5FullyConnectedLayerDataset(), data_types), framework::dataset::make("Batches", 1)))
REGISTER_FIXTURE_DATA_TEST_CASE (VGG16FullyConnectedLayer, NEFullyConnectedLayerFixture, framework::DatasetMode::ALL, framework::dataset::combine(framework::dataset::combine(datasets::VGG16FullyConnectedLayerDataset(), data_types), framework::dataset::make("Batches", 1)))
REGISTER_FIXTURE_DATA_TEST_CASE (GoogLeNetInceptionV1FullyConnectedLayer, NEFullyConnectedLayerFixture, framework::DatasetMode::ALL, framework::dataset::combine(framework::dataset::combine(datasets::GoogLeNetInceptionV1FullyConnectedLayerDataset(), data_types), framework::dataset::make("Batches", 1)))
REGISTER_FIXTURE_DATA_TEST_CASE (GoogLeNetInceptionV4FullyConnectedLayer, NEFullyConnectedLayerFixture, framework::DatasetMode::ALL, framework::dataset::combine(framework::dataset::combine(datasets::GoogLeNetInceptionV4FullyConnectedLayerDataset(), data_types), framework::dataset::make("Batches", 1)))
REGISTER_FIXTURE_DATA_TEST_CASE (AlexNetFullyConnectedLayer, NEFullyConnectedLayerFixture, framework::DatasetMode::NIGHTLY, framework::dataset::combine(framework::dataset::combine(datasets::AlexNetFullyConnectedLayerDataset(), data_types), framework::dataset::make("Batches",{4, 8})))
REGISTER_FIXTURE_DATA_TEST_CASE (LeNet5FullyConnectedLayer, NEFullyConnectedLayerFixture, framework::DatasetMode::NIGHTLY, framework::dataset::combine(framework::dataset::combine(datasets::LeNet5FullyConnectedLayerDataset(), data_types), framework::dataset::make("Batches",{4, 8})))
REGISTER_FIXTURE_DATA_TEST_CASE (VGG16FullyConnectedLayer, NEFullyConnectedLayerFixture, framework::DatasetMode::NIGHTLY, framework::dataset::combine(framework::dataset::combine(datasets::VGG16FullyConnectedLayerDataset(), data_types), framework::dataset::make("Batches",{2})))
REGISTER_FIXTURE_DATA_TEST_CASE (GoogLeNetInceptionV1FullyConnectedLayer, NEFullyConnectedLayerFixture, framework::DatasetMode::NIGHTLY, framework::dataset::combine(framework::dataset::combine(datasets::GoogLeNetInceptionV1FullyConnectedLayerDataset(), data_types), framework::dataset::make("Batches",{4, 8})))
REGISTER_FIXTURE_DATA_TEST_CASE (GoogLeNetInceptionV4FullyConnectedLayer, NEFullyConnectedLayerFixture, framework::DatasetMode::NIGHTLY, framework::dataset::combine(framework::dataset::combine(datasets::GoogLeNetInceptionV4FullyConnectedLayerDataset(), data_types), framework::dataset::make("Batches",{4, 8})))
REGISTER_FIXTURE_DATA_TEST_CASE (GoogLeNetInceptionV1GEMM, NEGEMMFixture, framework::DatasetMode::ALL, framework::dataset::combine(datasets::GoogLeNetInceptionV1GEMMDataset(), data_types))
REGISTER_FIXTURE_DATA_TEST_CASE (MatrixMultiplyGEMM, NEGEMMFixture, framework::DatasetMode::ALL, framework::dataset::combine(datasets::MatrixMultiplyGEMMDataset(), data_types))
REGISTER_FIXTURE_DATA_TEST_CASE (GoogleNetGEMM, NEGEMMFixture, framework::DatasetMode::NIGHTLY, framework::dataset::combine(datasets::GoogleNetGEMMDataset(), data_types))
REGISTER_FIXTURE_DATA_TEST_CASE (GoogLeNetInceptionV1GEMMLowp, NEGEMMLowpFixture, framework::DatasetMode::ALL, datasets::GoogLeNetInceptionV1GEMMDataset())
REGISTER_FIXTURE_DATA_TEST_CASE (MatrixMultiplyGEMMLowp, NEGEMMLowpFixture, framework::DatasetMode::ALL, datasets::MatrixMultiplyGEMMDataset())
REGISTER_FIXTURE_DATA_TEST_CASE (GoogleNetGEMMLowp, NEGEMMLowpFixture, framework::DatasetMode::NIGHTLY, datasets::GoogleNetGEMMDataset())
REGISTER_FIXTURE_DATA_TEST_CASE (AlexNetNormalizationLayer, NENormalizationLayerFixture, framework::DatasetMode::ALL, framework::dataset::combine(framework::dataset::combine(datasets::AlexNetNormalizationLayerDataset(), data_types), framework::dataset::make("Batches", 1)))
REGISTER_FIXTURE_DATA_TEST_CASE (GoogLeNetInceptionV1NormalizationLayer, NENormalizationLayerFixture, framework::DatasetMode::ALL, framework::dataset::combine(framework::dataset::combine(datasets::GoogLeNetInceptionV1NormalizationLayerDataset(), data_types), framework::dataset::make("Batches", 1)))
REGISTER_FIXTURE_DATA_TEST_CASE (AlexNetNormalizationLayer, NENormalizationLayerFixture, framework::DatasetMode::NIGHTLY, framework::dataset::combine(framework::dataset::combine(datasets::AlexNetNormalizationLayerDataset(), data_types), framework::dataset::make("Batches",{4, 8})))
REGISTER_FIXTURE_DATA_TEST_CASE (GoogLeNetInceptionV1NormalizationLayer, NENormalizationLayerFixture, framework::DatasetMode::NIGHTLY, framework::dataset::combine(framework::dataset::combine(datasets::GoogLeNetInceptionV1NormalizationLayerDataset(), data_types), framework::dataset::make("Batches",{4, 8})))
REGISTER_FIXTURE_DATA_TEST_CASE (AlexNetPoolingLayer, NEPoolingLayerFixture, framework::DatasetMode::ALL, framework::dataset::combine(framework::dataset::combine(datasets::AlexNetPoolingLayerDataset(), data_types), framework::dataset::make("Batches", 1)))
REGISTER_FIXTURE_DATA_TEST_CASE (LeNet5PoolingLayer, NEPoolingLayerFixture, framework::DatasetMode::ALL, framework::dataset::combine(framework::dataset::combine(datasets::LeNet5PoolingLayerDataset(), data_types), framework::dataset::make("Batches", 1)))
REGISTER_FIXTURE_DATA_TEST_CASE (GoogLeNetInceptionV1PoolingLayer, NEPoolingLayerFixture, framework::DatasetMode::ALL, framework::dataset::combine(framework::dataset::combine(datasets::GoogLeNetInceptionV1PoolingLayerDataset(), data_types), framework::dataset::make("Batches", 1)))
REGISTER_FIXTURE_DATA_TEST_CASE (GoogLeNetInceptionV4PoolingLayer, NEPoolingLayerFixture, framework::DatasetMode::ALL, framework::dataset::combine(framework::dataset::combine(datasets::GoogLeNetInceptionV4PoolingLayerDataset(), data_types), framework::dataset::make("Batches", 1)))
REGISTER_FIXTURE_DATA_TEST_CASE (SqueezeNetPoolingLayer, NEPoolingLayerFixture, framework::DatasetMode::ALL, framework::dataset::combine(framework::dataset::combine(datasets::SqueezeNetPoolingLayerDataset(), data_types), framework::dataset::make("Batches", 1)))
REGISTER_FIXTURE_DATA_TEST_CASE (VGG16PoolingLayer, NEPoolingLayerFixture, framework::DatasetMode::ALL, framework::dataset::combine(framework::dataset::combine(datasets::VGG16PoolingLayerDataset(), data_types), framework::dataset::make("Batches", 1)))
REGISTER_FIXTURE_DATA_TEST_CASE (YOLOV2PoolingLayer, NEPoolingLayerFixture, framework::DatasetMode::ALL, framework::dataset::combine(framework::dataset::combine(datasets::YOLOV2PoolingLayerDataset(), data_types), framework::dataset::make("Batches", 1)))
REGISTER_FIXTURE_DATA_TEST_CASE (AlexNetPoolingLayer, NEPoolingLayerFixture, framework::DatasetMode::NIGHTLY, framework::dataset::combine(framework::dataset::combine(datasets::AlexNetPoolingLayerDataset(), data_types), framework::dataset::make("Batches",{4, 8})))
REGISTER_FIXTURE_DATA_TEST_CASE (LeNet5PoolingLayer, NEPoolingLayerFixture, framework::DatasetMode::NIGHTLY, framework::dataset::combine(framework::dataset::combine(datasets::LeNet5PoolingLayerDataset(), data_types), framework::dataset::make("Batches",{4, 8})))
REGISTER_FIXTURE_DATA_TEST_CASE (GoogLeNetInceptionV1PoolingLayer, NEPoolingLayerFixture, framework::DatasetMode::NIGHTLY, framework::dataset::combine(framework::dataset::combine(datasets::GoogLeNetInceptionV1PoolingLayerDataset(), data_types), framework::dataset::make("Batches",{4, 8})))
REGISTER_FIXTURE_DATA_TEST_CASE (GoogLeNetInceptionV4PoolingLayer, NEPoolingLayerFixture, framework::DatasetMode::NIGHTLY, framework::dataset::combine(framework::dataset::combine(datasets::GoogLeNetInceptionV4PoolingLayerDataset(), data_types), framework::dataset::make("Batches",{4, 8})))
REGISTER_FIXTURE_DATA_TEST_CASE (SqueezeNetPoolingLayer, NEPoolingLayerFixture, framework::DatasetMode::NIGHTLY, framework::dataset::combine(framework::dataset::combine(datasets::SqueezeNetPoolingLayerDataset(), data_types), framework::dataset::make("Batches",{4, 8})))
REGISTER_FIXTURE_DATA_TEST_CASE (VGG16PoolingLayer, NEPoolingLayerFixture, framework::DatasetMode::NIGHTLY, framework::dataset::combine(framework::dataset::combine(datasets::VGG16PoolingLayerDataset(), data_types), framework::dataset::make("Batches",{2})))
REGISTER_FIXTURE_DATA_TEST_CASE (YOLOV2PoolingLayer, NEPoolingLayerFixture, framework::DatasetMode::NIGHTLY, framework::dataset::combine(framework::dataset::combine(datasets::YOLOV2PoolingLayerDataset(), data_types), framework::dataset::make("Batches",{4, 8})))
REGISTER_FIXTURE_DATA_TEST_CASE (SmallROIPoolingLayer, NEROIPoolingLayerFixture, framework::DatasetMode::ALL, framework::dataset::combine(framework::dataset::combine(datasets::SmallROIPoolingLayerDataset(), framework::dataset::make("DataType",{DataType::F32})), framework::dataset::make("Batches",{1, 4, 8})))
REGISTER_FIXTURE_DATA_TEST_CASE (SoftmaxLayerSmall, NESoftmaxLayerFixture, framework::DatasetMode::ALL, framework::dataset::combine(datasets::SoftmaxLayerSmallShapes(), data_types))
REGISTER_FIXTURE_DATA_TEST_CASE (SoftmaxLayerLarge, NESoftmaxLayerFixture, framework::DatasetMode::NIGHTLY, framework::dataset::combine(datasets::SoftmaxLayerLargeShapes(), data_types))
REGISTER_FIXTURE_DATA_TEST_CASE (AlexNet, NEAlexNetFixture, framework::DatasetMode::ALL, framework::dataset::combine(alex_net_data_types, framework::dataset::make("Batches",{1, 2, 4})))
REGISTER_FIXTURE_DATA_TEST_CASE (LeNet5, NELeNet5Fixture, framework::DatasetMode::ALL, framework::dataset::make("Batches",{1, 4, 8}))
template<typename O , typename F , typename... As>
void apply (O *obj, F &&func, const std::tuple< As... > &args)
template<typename T , typename std::enable_if< std::is_same< typename T::value_type, std::string >::value, int >::type = 0>
std::string join (T first, T last, const std::string &separator)
Helper function to concatenate multiple strings.
template<typename T , typename UnaryOp >
std::string join (T &&first, T &&last, const std::string &separator, UnaryOp &&op)
Helper function to concatenate multiple values.
template<typename T , typename std::enable_if< std::is_arithmetic< typename T::value_type >::value, int >::type = 0>
std::string join (T &&first, T &&last, const std::string &separator)
Helper function to concatenate multiple values.
std::string tolower (std::string string)
Convert string to lower case.
template<typename T , typename std::enable_if< std::is_arithmetic< T >::value, int >::type = 0>
std::string arithmetic_to_string (T val, int decimal_places=0)
Create a string with the arithmetic value in full precision.
template<typename D , typename T , typename... Ts>
void fill_tensors (D &&dist, std::initializer_list< int > seeds, T &&tensor, Ts &&...other_tensors)
template<typename U >
void swap (SimpleTensor< U > &tensor1, SimpleTensor< U > &tensor2)
template<typename T , typename = typename std::enable_if<std::is_floating_point<T>::value>::type>
T round_half_up (T value)
Round floating-point value with half value rounding to positive infinity.
template<typename T , typename = typename std::enable_if<std::is_floating_point<T>::value>::type>
T round_half_even (T value, T epsilon=std::numeric_limits< T >::epsilon())
Round floating-point value with half value rounding to nearest even.
Format get_format_for_channel (Channel channel)
Look up the format corresponding to a channel.
Format get_channel_format (Channel channel)
Return the format of a channel.
template<typename F , typename T >
T foldl (F &&, const T &value)
Base case of foldl.
template<typename F , typename T , typename U >
auto foldl (F &&func, T &&value1, U &&value2) -> decltype(func(value1, value2))
Base case of foldl.
template<typename F , typename I , typename T , typename... Vs>
I foldl (F &&func, I &&initial, T &&value, Vs &&...values)
Fold left.
ValidRegion shape_to_valid_region (const TensorShape &a_shape, bool border_undefined=false, BorderSize border_size=BorderSize(0))
Create a valid region based on tensor shape, border mode and border size.
ValidRegion shape_to_valid_region_gaussian_pyramid_half (const TensorShape &a_shape, const ValidRegion &a_valid_region, bool border_undefined=false)
Create a valid region for Gaussian Pyramid Half based on tensor shape and valid region at level "i - 1" and border mode.
template<typename T >
void store_value_with_data_type (void *ptr, T value, DataType data_type)
Write the value after casting the pointer according to data_type.
template<typename U , typename T >
T saturate_cast (T val)
Saturate a value of type T against the numeric limits of type U.
Coordinates index2coord (const TensorShape &shape, int index)
Convert a linear index into n-dimensional coordinates.
int coord2index (const TensorShape &shape, const Coordinates &coord)
Linearise the given coordinate.
bool is_in_valid_region (const ValidRegion &valid_region, Coordinates coord)
Check if a coordinate is within a valid region.
template<typename T >
T create_tensor (const TensorShape &shape, DataType data_type, int num_channels=1, int fixed_point_position=0, QuantizationInfo quantization_info=QuantizationInfo())
Create and initialize a tensor of the given type.
template<typename T >
T create_tensor (const TensorShape &shape, Format format)
Create and initialize a tensor of the given type.
template<typename T >
T create_HOG (const Size2D &cell_size, const Size2D &block_size, const Size2D &detection_window_size, const Size2D &block_stride, size_t num_bins, HOGNormType normalization_type=HOGNormType::L2HYS_NORM, float l2_hyst_threshold=0.2f, PhaseType phase_type=PhaseType::UNSIGNED)
Create and initialize a HOG (Histogram of Oriented Gradients) of the given type.
std::vector< ROI > generate_random_rois (const TensorShape &shape, const ROIPoolingLayerInfo &pool_info, unsigned int num_rois, std::random_device::result_type seed)
Create a vector of random ROIs.
template<typename T , typename ArrayAccessor_T >
void fill_array (ArrayAccessor_T &&array, const std::vector< T > &v)
std::string get_typestring (DataType data_type)
Obtain numpy type string from DataType.
template<typename TensorType >
void sync_if_necessary ()
Sync if necessary.
template<typename TensorType >
void sync_tensor_if_necessary (TensorType &tensor)
Sync tensor if necessary.
Variables
const auto data_types = framework::dataset::make("DataType", { DataType::F32, DataType::QASYMM8 })
std::unique_ptr< AssetsLibrary > library
Typedef Documentation
using CLActivationLayerFixture = ActivationLayerFixture<CLTensor, CLActivationLayer, CLAccessor>
Definition at line 53 of file ActivationLayer.cpp.
using CLAlexNetFixture = AlexNetFixture<ICLTensor, CLTensor, CLSubTensor, CLAccessor, CLActivationLayer, CLConvolutionLayer, CLDirectConvolutionLayer, CLFullyConnectedLayer, CLNormalizationLayer, CLPoolingLayer, CLSoftmaxLayer>
Definition at line 56 of file AlexNet.cpp.
using CLBatchNormalizationLayerFixture = BatchNormalizationLayerFixture<CLTensor, CLBatchNormalizationLayer, CLAccessor>
Definition at line 46 of file BatchNormalizationLayer.cpp.
typedef ConvolutionLayerFixture< CLTensor, CLDirectConvolutionLayer, CLAccessor > CLConvolutionLayerFixture
Definition at line 51 of file ConvolutionLayer.cpp.
using CLDepthwiseConvolutionLayerFixture = DepthwiseConvolutionLayerFixture<CLTensor, CLDepthwiseConvolutionLayer3x3, CLAccessor>
Definition at line 41 of file DepthwiseConvolutionLayer.cpp.
using CLDepthwiseSeparableConvolutionLayerFixture = DepthwiseSeparableConvolutionLayerFixture<CLTensor, CLDepthwiseSeparableConvolutionLayer, CLAccessor>
Definition at line 41 of file DepthwiseSeparableConvolutionLayer.cpp.
using CLFloorFixture = FloorFixture<CLTensor, CLFloor, CLAccessor>
Definition at line 45 of file Floor.cpp.
using CLFullyConnectedLayerFixture = FullyConnectedLayerFixture<CLTensor, CLFullyConnectedLayer, CLAccessor>
Definition at line 49 of file FullyConnectedLayer.cpp.
using CLGEMMFixture = GEMMFixture<CLTensor, CLGEMM, CLAccessor>
Definition at line 47 of file GEMM.cpp.
using CLGEMMLowpFixture = GEMMLowpMatrixMultiplyCoreFixture<CLTensor, CLGEMMLowpMatrixMultiplyCore, CLAccessor>
Definition at line 43 of file GEMMLowp.cpp.
using CLLeNet5Fixture = LeNet5Fixture<CLTensor, CLAccessor, CLActivationLayer, CLConvolutionLayer, CLFullyConnectedLayer, CLPoolingLayer, CLSoftmaxLayer>
Definition at line 49 of file LeNet5.cpp.
using CLMobileNetFixture = MobileNetFixture<CLTensor, CLAccessor, CLActivationLayer, CLConvolutionLayer, CLDirectConvolutionLayer, CLDepthwiseConvolutionLayer, CLReshapeLayer, CLPoolingLayer>
Definition at line 51 of file MobileNet.cpp.
using CLMobileNetV1_128_Fixture = MobileNetV1Fixture<CLTensor, CLAccessor, CLActivationLayer, CLBatchNormalizationLayer, CLConvolutionLayer, CLDirectConvolutionLayer, CLDepthwiseConvolutionLayer3x3, CLReshapeLayer, CLPoolingLayer, CLSoftmaxLayer, 128>
Definition at line 68 of file MobileNetV1.cpp.
using CLMobileNetV1_224_Fixture = MobileNetV1Fixture<CLTensor, CLAccessor, CLActivationLayer, CLBatchNormalizationLayer, CLConvolutionLayer, CLDirectConvolutionLayer, CLDepthwiseConvolutionLayer3x3, CLReshapeLayer, CLPoolingLayer, CLSoftmaxLayer, 224>
Definition at line 56 of file MobileNetV1.cpp.
using CLNormalizationLayerFixture = NormalizationLayerFixture<CLTensor, CLNormalizationLayer, CLAccessor>
Definition at line 46 of file NormalizationLayer.cpp.
using CLPoolingLayerFixture = PoolingLayerFixture<CLTensor, CLPoolingLayer, CLAccessor>
Definition at line 51 of file PoolingLayer.cpp.
using CLROIPoolingLayerFixture = ROIPoolingLayerFixture<CLTensor, CLROIPoolingLayer, CLAccessor, CLArray<ROI>, CLArrayAccessor<ROI>>
Definition at line 42 of file ROIPoolingLayer.cpp.
using CLSoftmaxLayerFixture = SoftmaxLayerFixture<CLTensor, CLSoftmaxLayer, CLAccessor>
Definition at line 45 of file SoftmaxLayer.cpp.
using GCBatchNormalizationLayerFixture = BatchNormalizationLayerFixture<GCTensor, GCBatchNormalizationLayer, GCAccessor>
Definition at line 46 of file BatchNormalizationLayer.cpp.
typedef ConvolutionLayerFixture< GCTensor, GCDirectConvolutionLayer, GCAccessor > GCConvolutionLayerFixture
Definition at line 51 of file ConvolutionLayer.cpp.
using GCDepthwiseConvolutionLayerFixture = DepthwiseConvolutionLayerFixture<GCTensor, GCDepthwiseConvolutionLayer3x3, GCAccessor>
Definition at line 41 of file DepthwiseConvolutionLayer.cpp.
using GCFullyConnectedLayerFixture = FullyConnectedLayerFixture<GCTensor, GCFullyConnectedLayer, GCAccessor>
Definition at line 49 of file FullyConnectedLayer.cpp.
using GCGEMMFixture = GEMMFixture<GCTensor, GCGEMM, GCAccessor>
Definition at line 46 of file GEMM.cpp.
using GCNormalizePlanarYUVLayerFixture = NormalizePlanarYUVLayerFixture<GCTensor, GCNormalizePlanarYUVLayer, GCAccessor>
Definition at line 45 of file NormalizePlanarYUVLayer.cpp.
using GCPoolingLayerFixture = PoolingLayerFixture<GCTensor, GCPoolingLayer, GCAccessor>
Definition at line 51 of file PoolingLayer.cpp.
using GCScaleLayerFixture = ScaleLayerFixture<GCTensor, GCScale, GCAccessor, T>
Definition at line 46 of file Scale.cpp.
using GCSoftmaxLayerFixture = SoftmaxLayerFixture<GCTensor, GCSoftmaxLayer, GCAccessor>
Definition at line 45 of file SoftmaxLayer.cpp.
using NEActivationLayerFixture = ActivationLayerFixture<Tensor, NEActivationLayer, Accessor>
Definition at line 58 of file ActivationLayer.cpp.
using NEAlexNetFixture = AlexNetFixture<ITensor, Tensor, SubTensor, Accessor, NEActivationLayer, NEConvolutionLayer, NEConvolutionLayer, NEFullyConnectedLayer, NENormalizationLayer, NEPoolingLayer, NESoftmaxLayer>
Definition at line 65 of file AlexNet.cpp.
using NEBatchNormalizationLayerFixture = BatchNormalizationLayerFixture<Tensor, NEBatchNormalizationLayer, Accessor>
Definition at line 51 of file BatchNormalizationLayer.cpp.
typedef ConvolutionLayerFixture< Tensor, NEDirectConvolutionLayer, Accessor > NEConvolutionLayerFixture
Definition at line 56 of file ConvolutionLayer.cpp.
using NEFloorFixture = FloorFixture<Tensor, NEFloor, Accessor>
Definition at line 45 of file Floor.cpp.
using NEFullyConnectedLayerFixture = FullyConnectedLayerFixture<Tensor, NEFullyConnectedLayer, Accessor>
Definition at line 53 of file FullyConnectedLayer.cpp.
using NEGEMMFixture = GEMMFixture<Tensor, NEGEMM, Accessor>
Definition at line 53 of file GEMM.cpp.
using NEGEMMLowpFixture = GEMMLowpMatrixMultiplyCoreFixture<Tensor, NEGEMMLowpMatrixMultiplyCore, Accessor>
Definition at line 42 of file GEMMLowp.cpp.
using NELeNet5Fixture = LeNet5Fixture<Tensor, Accessor, NEActivationLayer, NEConvolutionLayer, NEFullyConnectedLayer, NEPoolingLayer, NESoftmaxLayer>
Definition at line 49 of file LeNet5.cpp.
using NENormalizationLayerFixture = NormalizationLayerFixture<Tensor, NENormalizationLayer, Accessor>
Definition at line 49 of file NormalizationLayer.cpp.
using NEPoolingLayerFixture = PoolingLayerFixture<Tensor, NEPoolingLayer, Accessor>
Definition at line 55 of file PoolingLayer.cpp.
using NEROIPoolingLayerFixture = ROIPoolingLayerFixture<Tensor, NEROIPoolingLayer, Accessor, Array<ROI>, ArrayAccessor<ROI>>
Definition at line 42 of file ROIPoolingLayer.cpp.
using NESoftmaxLayerFixture = SoftmaxLayerFixture<Tensor, NESoftmaxLayer, Accessor>
Definition at line 45 of file SoftmaxLayer.cpp.
Function Documentation
void arm_compute::test::apply (O * obj, F && func, const std::tuple< As... > & args)
Definition at line 79 of file Utils.h.
References arm_compute::test::framework::apply_impl(), caffe_data_extractor::type, and value.
 {
     detail::apply_impl(obj, std::forward<F>(func), args, detail::sequence_t<sizeof...(As)>());
 }
std::string arm_compute::test::arithmetic_to_string (T val, int decimal_places = 0) inline
Create a string with the arithmetic value in full precision.
Parameters
val Arithmetic value
decimal_places How many decimal places to show
Returns
String with the arithmetic value.
Definition at line 164 of file Utils.h.
Referenced by PrettyPrinter::print_measurements().
 {
     std::stringstream ss;
     ss << std::fixed;
     ss.precision((decimal_places) ? decimal_places : std::numeric_limits<T>::digits10 + 1);
     ss << val;
     return ss.str();
 }
int arm_compute::test::coord2index (const TensorShape & shape, const Coordinates & coord) inline
Linearise the given coordinate.
Transforms the given coordinate into a linear offset in terms of elements.
Parameters
[in] shape Shape of the n-dimensional tensor.
[in] coord The to be converted coordinate.
Returns
Linear offset to the element.
Definition at line 432 of file Utils.h.
References ARM_COMPUTE_ERROR_ON_MSG, Dimensions< T >::num_dimensions(), and TensorShape::total_size().
Referenced by arm_compute::test::validation::apply_2d_spatial_filter(), DATA_TEST_CASE(), RawTensor::operator()(), SimpleTensor< T >::operator()(), arm_compute::test::validation::reference::permute(), arm_compute::test::validation::reference::scale(), ConvolutionValidationGenericFixture< TensorType, AccessorType, FunctionType, T >::setup(), arm_compute::test::validation::tensor_elem_at(), arm_compute::test::validation::reference::transpose(), arm_compute::test::validation::reference::warp_affine(), and arm_compute::test::validation::reference::warp_perspective().
 {
     ARM_COMPUTE_ERROR_ON_MSG(shape.total_size() == 0, "Cannot get index from empty shape");
     ARM_COMPUTE_ERROR_ON_MSG(coord.num_dimensions() == 0, "Cannot get index of empty coordinate");
     int index    = 0;
     int dim_size = 1;
     for(unsigned int i = 0; i < coord.num_dimensions(); ++i)
     {
         index += coord[i] * dim_size;
         dim_size *= shape[i];
     }
     return index;
 }
T arm_compute::test::create_HOG (const Size2D & cell_size, const Size2D & block_size, const Size2D & detection_window_size, const Size2D & block_stride, size_t num_bins, HOGNormType normalization_type = HOGNormType::L2HYS_NORM, float l2_hyst_threshold = 0.2f, PhaseType phase_type = PhaseType::UNSIGNED) inline
Create and initialize a HOG (Histogram of Oriented Gradients) of the given type.
Parameters
[in] cell_size Cell size in pixels
[in] block_size Block size in pixels. Must be a multiple of cell_size.
[in] detection_window_size Detection window size in pixels. Must be a multiple of block_size and block_stride.
[in] block_stride Distance in pixels between 2 consecutive blocks along the x and y direction. Must be a multiple of cell size
[in] num_bins Number of histogram bins for each cell
[in] normalization_type (Optional) Normalization type to use for each block
[in] l2_hyst_threshold (Optional) Threshold used for L2HYS_NORM normalization method
[in] phase_type (Optional) Type of PhaseType
Returns
Initialized HOG of given type.
Definition at line 517 of file Utils.h.
 {
     T       hog;
     HOGInfo hog_info(cell_size, block_size, block_size, block_stride, num_bins, normalization_type, l2_hyst_threshold, phase_type);
     hog.init(hog_info);
     return hog;
 }
T arm_compute::test::create_tensor (const TensorShape & shape, DataType data_type, int num_channels = 1, int fixed_point_position = 0, QuantizationInfo quantization_info = QuantizationInfo()) inline
Create and initialize a tensor of the given type.
Parameters
[in] shape Tensor shape.
[in] data_type Data type.
[in] num_channels (Optional) Number of channels.
[in] fixed_point_position (Optional) Number of fractional bits.
[in] quantization_info (Optional) Quantization info for asymmetric quantized types.
Returns
Initialized tensor of given type.
Definition at line 474 of file Utils.h.
References arm_compute::test::validation::info(), and TensorInfo::set_quantization_info().
 {
     T          tensor;
     TensorInfo info(shape, num_channels, data_type, fixed_point_position);
     info.set_quantization_info(quantization_info);
     tensor.allocator()->init(info);
     return tensor;
 }
T arm_compute::test::create_tensor (const TensorShape & shape, Format format) inline
Create and initialize a tensor of the given type.
Parameters
[in] shape Tensor shape.
[in] format Format type.
Returns
Initialized tensor of given type.
Definition at line 493 of file Utils.h.
References arm_compute::test::validation::info().
 {
     TensorInfo info(shape, format);
     T tensor;
     tensor.allocator()->init(info);
     return tensor;
 }
void arm_compute::test::fill_array (ArrayAccessor_T && array, const std::vector< T > & v) inline
Definition at line 574 of file Utils.h.
Referenced by ROIPoolingLayerFixture< TensorType, Function, Accessor, Array_T, ArrayAccessor >::setup().
 {
     array.resize(v.size());
     std::memcpy(array.buffer(), v.data(), v.size() * sizeof(T));
 }
void arm_compute::test::fill_tensors (D && dist, std::initializer_list< int > seeds, T && tensor, Ts &&... other_tensors)
Definition at line 41 of file Helper.h.
References ARM_COMPUTE_ERROR_ON, and library.
 {
     const std::array < T, 1 + sizeof...(Ts) > tensors{ { std::forward<T>(tensor), std::forward<Ts>(other_tensors)... } };
     std::vector<int> vs(seeds);
     ARM_COMPUTE_ERROR_ON(vs.size() != tensors.size());
     int k = 0;
     for(auto tp : tensors)
     {
         library->fill(Accessor(*tp), std::forward<D>(dist), vs[k++]);
     }
 }
T arm_compute::test::foldl (F && , const T & value) inline
Base case of foldl.
Returns
value.
Definition at line 175 of file Utils.h.
References value.
Referenced by foldl().
 {
     return value;
 }
auto arm_compute::test::foldl (F && func, T && value1, U && value2) -> decltype(func(value1, value2)) inline
Base case of foldl.
Returns
func(value1, value2).
Definition at line 185 of file Utils.h.
 {
     return func(value1, value2);
 }
I arm_compute::test::foldl (F && func, I && initial, T && value, Vs &&... values) inline
Fold left.
Parameters
[in] func Binary function to be called.
[in] initial Initial value.
[in] value Argument passed to the function.
[in] values Remaining arguments.
Definition at line 198 of file Utils.h.
References foldl().
 {
     return foldl(std::forward<F>(func), func(std::forward<I>(initial), std::forward<T>(value)), std::forward<Vs>(values)...);
 }
std::vector<ROI> arm_compute::test::generate_random_rois (const TensorShape & shape, const ROIPoolingLayerInfo & pool_info, unsigned int num_rois, std::random_device::result_type seed) inline
Create a vector of random ROIs.
Parameters
[in] shape The shape of the input tensor.
[in] pool_info The ROI pooling information.
[in] num_rois The number of ROIs to be created.
[in] seed The random seed to be used.
Returns
A vector that contains the requested number of random ROIs
Definition at line 536 of file Utils.h.
References ARM_COMPUTE_ERROR_ON, ROI::batch_idx, Rectangle::height, arm_compute::test::fixed_point_arithmetic::detail::max(), ROIPoolingLayerInfo::pooled_height(), ROIPoolingLayerInfo::pooled_width(), ROI::rect, ROIPoolingLayerInfo::spatial_scale(), Rectangle::width, Dimensions< T >::x(), Rectangle::x, Dimensions< T >::y(), and Rectangle::y.
Referenced by ROIPoolingLayerFixture< TensorType, Function, Accessor, Array_T, ArrayAccessor >::setup().
 {
     ARM_COMPUTE_ERROR_ON((pool_info.pooled_width() < 4) || (pool_info.pooled_height() < 4));
     std::vector<ROI> rois;
     std::mt19937     gen(seed);
     const int        pool_width  = pool_info.pooled_width();
     const int        pool_height = pool_info.pooled_height();
     const float      roi_scale   = pool_info.spatial_scale();
     // Calculate distribution bounds
     const auto scaled_width  = static_cast<int>((shape.x() / roi_scale) / pool_width);
     const auto scaled_height = static_cast<int>((shape.y() / roi_scale) / pool_height);
     const auto min_width     = static_cast<int>(pool_width / roi_scale);
     const auto min_height    = static_cast<int>(pool_height / roi_scale);
     // Create distributions
     std::uniform_int_distribution<int> dist_batch(0, shape[3] - 1);
     std::uniform_int_distribution<int> dist_x(0, scaled_width);
     std::uniform_int_distribution<int> dist_y(0, scaled_height);
     std::uniform_int_distribution<int> dist_w(min_width, std::max(min_width, (pool_width - 2) * scaled_width));
     std::uniform_int_distribution<int> dist_h(min_height, std::max(min_height, (pool_height - 2) * scaled_height));
     for(unsigned int r = 0; r < num_rois; ++r)
     {
         ROI roi;
         roi.batch_idx   = dist_batch(gen);
         roi.rect.x      = dist_x(gen);
         roi.rect.y      = dist_y(gen);
         roi.rect.width  = dist_w(gen);
         roi.rect.height = dist_h(gen);
         rois.push_back(roi);
     }
     return rois;
 }
Format arm_compute::test::get_channel_format (Channel channel) inline
Return the format of a channel.
Parameters
[in] channel Channel type.
Returns
Format of the given channel.
Definition at line 157 of file Utils.h.
References arm_compute::B, arm_compute::G, arm_compute::R, and arm_compute::U8.
Referenced by AssetsLibrary::fill().
 {
     switch(channel)
     {
         case Channel::R:
         case Channel::G:
         case Channel::B:
             return Format::U8;
         default:
             throw std::runtime_error("Unsupported channel");
     }
 }
Format arm_compute::test::get_format_for_channel (Channel channel) inline
Look up the format corresponding to a channel.
Parameters
[in] channel Channel type.
Returns
Format that contains the given channel.
Definition at line 138 of file Utils.h.
References arm_compute::B, arm_compute::G, arm_compute::R, and arm_compute::RGB888.
Referenced by AssetsLibrary::fill(), and AssetsLibrary::get().
 {
     switch(channel)
     {
         case Channel::R:
         case Channel::G:
         case Channel::B:
             return Format::RGB888;
         default:
             throw std::runtime_error("Unsupported channel");
     }
 }
std::string arm_compute::test::get_typestring (DataType data_type) inline
Obtain numpy type string from DataType.
Parameters
[in] data_type Data type.
Returns
numpy type string.
Definition at line 586 of file Utils.h.
References ARM_COMPUTE_ERROR, arm_compute::test::validation::c, arm_compute::F32, arm_compute::F64, arm_compute::S16, arm_compute::S32, arm_compute::S64, arm_compute::S8, arm_compute::SIZET, arm_compute::support::cpp11::to_string(), arm_compute::U16, arm_compute::U32, arm_compute::U64, and arm_compute::U8.
Referenced by AssetsLibrary::fill_layer_data().
 {
     // Check endianness
     const unsigned int i = 1;
     const char        *c = reinterpret_cast<const char *>(&i);
     std::string        endianness;
     if(*c == 1)
     {
         endianness = std::string("<");
     }
     else
     {
         endianness = std::string(">");
     }
     const std::string no_endianness("|");
     switch(data_type)
     {
         case DataType::U8:
             return no_endianness + "u" + support::cpp11::to_string(sizeof(uint8_t));
         case DataType::S8:
             return no_endianness + "i" + support::cpp11::to_string(sizeof(int8_t));
         case DataType::U16:
             return endianness + "u" + support::cpp11::to_string(sizeof(uint16_t));
         case DataType::S16:
             return endianness + "i" + support::cpp11::to_string(sizeof(int16_t));
         case DataType::U32:
             return endianness + "u" + support::cpp11::to_string(sizeof(uint32_t));
         case DataType::S32:
             return endianness + "i" + support::cpp11::to_string(sizeof(int32_t));
         case DataType::U64:
             return endianness + "u" + support::cpp11::to_string(sizeof(uint64_t));
         case DataType::S64:
             return endianness + "i" + support::cpp11::to_string(sizeof(int64_t));
         case DataType::F32:
             return endianness + "f" + support::cpp11::to_string(sizeof(float));
         case DataType::F64:
             return endianness + "f" + support::cpp11::to_string(sizeof(double));
         case DataType::SIZET:
             return endianness + "u" + support::cpp11::to_string(sizeof(size_t));
         default:
             ARM_COMPUTE_ERROR("NOT SUPPORTED!");
     }
 }
Coordinates arm_compute::test::index2coord (const TensorShape & shape, int index) inline
Convert a linear index into n-dimensional coordinates.
Parameters
[in] shape Shape of the n-dimensional tensor.
[in] index Linear index specifying the i-th element.
Returns
n-dimensional coordinates.
Definition at line 403 of file Utils.h.
References ARM_COMPUTE_ERROR_ON_MSG, Dimensions< T >::num_dimensions(), TensorShape::set(), and TensorShape::total_size().
Referenced by arm_compute::test::validation::reference::box3x3(), arm_compute::test::validation::reference::convolution(), DATA_TEST_CASE(), arm_compute::test::validation::reference::derivative(), arm_compute::test::validation::reference::dilate(), arm_compute::test::validation::reference::erode(), AssetsLibrary::fill(), arm_compute::test::validation::reference::gaussian3x3(), arm_compute::test::validation::reference::gaussian5x5(), arm_compute::test::validation::reference::median3x3(), arm_compute::test::validation::reference::non_linear_filter(), arm_compute::test::validation::reference::non_maxima_suppression(), arm_compute::test::validation::reference::permute(), arm_compute::test::validation::reference::scale(), arm_compute::test::validation::reference::scharr(), FullyConnectedLayerValidationGenericFixture< TensorType, AccessorType, FunctionType, T, run_interleave >::setup(), ConvolutionValidationGenericFixture< TensorType, AccessorType, FunctionType, T >::setup(), arm_compute::test::validation::reference::sobel(), arm_compute::test::validation::reference::transpose(), arm_compute::test::validation::transpose(), arm_compute::test::validation::validate(), arm_compute::test::validation::validate_wrap(), arm_compute::test::validation::reference::warp_affine(), and arm_compute::test::validation::reference::warp_perspective().
 {
     int num_elements = shape.total_size();
     ARM_COMPUTE_ERROR_ON_MSG(index < 0 || index >= num_elements, "Index has to be in [0, num_elements]");
     ARM_COMPUTE_ERROR_ON_MSG(num_elements == 0, "Cannot create coordinate from empty shape");
     Coordinates coord{ 0 };
     for(int d = shape.num_dimensions() - 1; d >= 0; --d)
     {
         num_elements /= shape[d];
         coord.set(d, index / num_elements);
         index %= num_elements;
     }
     return coord;
 }
bool arm_compute::test::is_in_valid_region (const ValidRegion & valid_region, Coordinates coord) inline
Check if a coordinate is within a valid region.
Definition at line 450 of file Utils.h.
References ValidRegion::end(), Dimensions< int >::num_max_dimensions, and ValidRegion::start().
Referenced by arm_compute::test::validation::reference::derivative(), arm_compute::test::validation::reference::non_linear_filter(), arm_compute::test::validation::reference::non_maxima_suppression(), arm_compute::test::validation::reference::scharr(), arm_compute::test::validation::reference::sobel(), arm_compute::test::validation::validate(), and arm_compute::test::validation::validate_wrap().
 {
     for(size_t d = 0; d < Coordinates::num_max_dimensions; ++d)
     {
         if(coord[d] < valid_region.start(d) || coord[d] >= valid_region.end(d))
         {
             return false;
         }
     }
     return true;
 }
std::string arm_compute::test::join (T first, T last, const std::string & separator)
Helper function to concatenate multiple strings.
Parameters
[in] first Iterator pointing to the first element to be concatenated.
[in] last Iterator pointing behind the last element to be concatenated.
[in] separator String used to join the elements.
Returns
String containing all elements joined by separator.
Definition at line 93 of file Utils.h.
References accumulate().
Referenced by Framework::init(), join(), and JSONPrinter::print_measurements().
 {
     return std::accumulate(std::next(first), last, *first, [&separator](const std::string & base, const std::string & suffix)
     {
         return base + separator + suffix;
     });
 }
std::string arm_compute::test::join (T && first, T && last, const std::string & separator, UnaryOp && op)
Helper function to concatenate multiple values.
All values are converted to std::string using the provided operation before being joined.
The signature of op has to be equivalent to std::string op(const T::value_type &val).
Parameters
[in] first Iterator pointing to the first element to be concatenated.
[in] last Iterator pointing behind the last element to be concatenated.
[in] separator String used to join the elements.
[in] op Conversion function.
Returns
String containing all elements joined by separator.
Definition at line 117 of file Utils.h.
References accumulate(), and value.
 {
     return std::accumulate(std::next(first), last, op(*first), [&separator, &op](const std::string & base, const typename T::value_type & suffix)
     {
         return base + separator + op(suffix);
     });
 }
std::string arm_compute::test::join (T && first, T && last, const std::string & separator)
Helper function to concatenate multiple values.
All values are converted to std::string using std::to_string before being joined.
Parameters
[in] first Iterator pointing to the first element to be concatenated.
[in] last Iterator pointing behind the last element to be concatenated.
[in] separator String used to join the elements.
Returns
String containing all elements joined by separator.
Definition at line 136 of file Utils.h.
References join(), and arm_compute::support::cpp11::to_string().
 {
     return join(std::forward<T>(first), std::forward<T>(last), separator, support::cpp11::to_string);
 }
arm_compute::test::REGISTER_FIXTURE_DATA_TEST_CASE (MobileNetDepthwiseSeparableConvolutionLayer , CLDepthwiseSeparableConvolutionLayerFixture , framework::DatasetMode::ALL , framework::dataset::combine(framework::dataset::combine(datasets::MobileNetDepthwiseSeparableConvolutionLayerDataset(), data_types), framework::dataset::make("Batches",{1})))
arm_compute::test::REGISTER_FIXTURE_DATA_TEST_CASE (MobileNetDepthwiseConvLayer , GCDepthwiseConvolutionLayerFixture , framework::DatasetMode::ALL , framework::dataset::combine(framework::dataset::combine(datasets::MobileNetDepthwiseConvolutionLayerDataset(), data_types), framework::dataset::make("Batches",{1})))
arm_compute::test::REGISTER_FIXTURE_DATA_TEST_CASE (MobileNetDepthwiseConvLayer , CLDepthwiseConvolutionLayerFixture , framework::DatasetMode::ALL , framework::dataset::combine(framework::dataset::combine(datasets::MobileNetDepthwiseConvolutionLayerDataset(), data_types), framework::dataset::make("Batches",{1})))
arm_compute::test::REGISTER_FIXTURE_DATA_TEST_CASE (SmallROIPoolingLayer , CLROIPoolingLayerFixture , framework::DatasetMode::ALL , framework::dataset::combine(framework::dataset::combine(datasets::SmallROIPoolingLayerDataset(), framework::dataset::make("DataType",{DataType::F16, DataType::F32})), framework::dataset::make("Batches",{1, 4, 8})))
arm_compute::test::REGISTER_FIXTURE_DATA_TEST_CASE (GoogLeNetInceptionV1GEMMLowp , NEGEMMLowpFixture , framework::DatasetMode::ALL , datasets::GoogLeNetInceptionV1GEMMDataset())
arm_compute::test::REGISTER_FIXTURE_DATA_TEST_CASE (SmallROIPoolingLayer , NEROIPoolingLayerFixture , framework::DatasetMode::ALL , framework::dataset::combine(framework::dataset::combine(datasets::SmallROIPoolingLayerDataset(), framework::dataset::make("DataType",{DataType::F32})), framework::dataset::make("Batches",{1, 4, 8})))
arm_compute::test::REGISTER_FIXTURE_DATA_TEST_CASE (GoogLeNetInceptionV1GEMMLowp , CLGEMMLowpFixture , framework::DatasetMode::ALL , datasets::GoogLeNetInceptionV1GEMMDataset())
arm_compute::test::REGISTER_FIXTURE_DATA_TEST_CASE (MatrixMultiplyGEMMLowp , NEGEMMLowpFixture , framework::DatasetMode::ALL , datasets::MatrixMultiplyGEMMDataset())
arm_compute::test::REGISTER_FIXTURE_DATA_TEST_CASE (MatrixMultiplyGEMMLowp , CLGEMMLowpFixture , framework::DatasetMode::ALL , datasets::MatrixMultiplyGEMMDataset())
arm_compute::test::REGISTER_FIXTURE_DATA_TEST_CASE (GoogleNetGEMMLowp , NEGEMMLowpFixture , framework::DatasetMode::NIGHTLY , datasets::GoogleNetGEMMDataset())
arm_compute::test::REGISTER_FIXTURE_DATA_TEST_CASE (SoftmaxLayerSmall , CLSoftmaxLayerFixture , framework::DatasetMode::ALL , framework::dataset::combine(datasets::SoftmaxLayerSmallShapes(), data_types))
arm_compute::test::REGISTER_FIXTURE_DATA_TEST_CASE (SoftmaxLayer , GCSoftmaxLayerFixture , framework::DatasetMode::ALL , framework::dataset::combine(datasets::SoftmaxLayerSmallShapes(), data_types))
arm_compute::test::REGISTER_FIXTURE_DATA_TEST_CASE (Floor , NEFloorFixture , framework::DatasetMode::ALL , framework::dataset::combine(datasets::SmallShapes(), data_types))
arm_compute::test::REGISTER_FIXTURE_DATA_TEST_CASE (GoogleNetGEMMLowp , CLGEMMLowpFixture , framework::DatasetMode::NIGHTLY , datasets::GoogleNetGEMMDataset())
arm_compute::test::REGISTER_FIXTURE_DATA_TEST_CASE (SoftmaxLayerSmall , NESoftmaxLayerFixture , framework::DatasetMode::ALL , framework::dataset::combine(datasets::SoftmaxLayerSmallShapes(), data_types))
arm_compute::test::REGISTER_FIXTURE_DATA_TEST_CASE (Floor , CLFloorFixture , framework::DatasetMode::ALL , framework::dataset::combine(datasets::SmallShapes(), data_types))
arm_compute::test::REGISTER_FIXTURE_DATA_TEST_CASE (GoogLeNetInceptionV4NormalizePlanarYUVLayer , GCNormalizePlanarYUVLayerFixture , framework::DatasetMode::ALL , framework::dataset::combine(framework::dataset::combine(datasets::GoogLeNetInceptionV4NormalizePlanarYUVLayerDataset(), data_types), framework::dataset::make("Batches", 1)))
arm_compute::test::REGISTER_FIXTURE_DATA_TEST_CASE (YOLOV2BatchNormalizationLayer , CLBatchNormalizationLayerFixture , framework::DatasetMode::ALL , framework::dataset::combine(framework::dataset::combine(datasets::YOLOV2BatchNormalizationLayerDataset(), data_types), framework::dataset::make("Batches", 1)))
arm_compute::test::REGISTER_FIXTURE_DATA_TEST_CASE (SmallScaleLayer , GCScaleLayerFixture< half > , framework::DatasetMode::ALL , framework::dataset::combine(datasets::SmallScaleLayerShapes(), data_types))
arm_compute::test::REGISTER_FIXTURE_DATA_TEST_CASE (YOLOV2BatchNormalizationLayer , GCBatchNormalizationLayerFixture , framework::DatasetMode::ALL , framework::dataset::combine(framework::dataset::combine(datasets::YOLOV2BatchNormalizationLayerDataset(), data_types), framework::dataset::make("Batches", 1)))
arm_compute::test::REGISTER_FIXTURE_DATA_TEST_CASE (AlexNetGEMMLowp , CLGEMMLowpFixture , framework::DatasetMode::NIGHTLY , datasets::AlexNetGEMMDataset())
arm_compute::test::REGISTER_FIXTURE_DATA_TEST_CASE (GoogLeNetInceptionV1GEMM , GCGEMMFixture , framework::DatasetMode::ALL , framework::dataset::combine(datasets::GoogLeNetInceptionV1GEMMDataset(), data_types))
arm_compute::test::REGISTER_FIXTURE_DATA_TEST_CASE (AlexNetNormalizationLayer , CLNormalizationLayerFixture , framework::DatasetMode::ALL , framework::dataset::combine(framework::dataset::combine(datasets::AlexNetNormalizationLayerDataset(), data_types), framework::dataset::make("Batches", 1)))
arm_compute::test::REGISTER_FIXTURE_DATA_TEST_CASE (GoogLeNetInceptionV1GEMM , CLGEMMFixture , framework::DatasetMode::ALL , framework::dataset::combine(datasets::GoogLeNetInceptionV1GEMMDataset(), data_types))
arm_compute::test::REGISTER_FIXTURE_DATA_TEST_CASE (MatrixMultiplyGEMM , GCGEMMFixture , framework::DatasetMode::ALL , framework::dataset::combine(datasets::MatrixMultiplyGEMMDataset(), data_types))
arm_compute::test::REGISTER_FIXTURE_DATA_TEST_CASE (SoftmaxLayerLarge , CLSoftmaxLayerFixture , framework::DatasetMode::NIGHTLY , framework::dataset::combine(datasets::SoftmaxLayerLargeShapes(), data_types))
arm_compute::test::REGISTER_FIXTURE_DATA_TEST_CASE (MatrixMultiplyGEMM , CLGEMMFixture , framework::DatasetMode::ALL , framework::dataset::combine(datasets::MatrixMultiplyGEMMDataset(), data_types))
arm_compute::test::REGISTER_FIXTURE_DATA_TEST_CASE (SoftmaxLayerLarge , NESoftmaxLayerFixture , framework::DatasetMode::NIGHTLY , framework::dataset::combine(datasets::SoftmaxLayerLargeShapes(), data_types))
arm_compute::test::REGISTER_FIXTURE_DATA_TEST_CASE (GoogleNetGEMM , GCGEMMFixture , framework::DatasetMode::NIGHTLY , framework::dataset::combine(datasets::GoogleNetGEMMDataset(), data_types))
arm_compute::test::REGISTER_FIXTURE_DATA_TEST_CASE (GoogleNetGEMM , CLGEMMFixture , framework::DatasetMode::NIGHTLY , framework::dataset::combine(datasets::GoogleNetGEMMDataset(), data_types))
arm_compute::test::REGISTER_FIXTURE_DATA_TEST_CASE (AlexNetFullyConnectedLayer , GCFullyConnectedLayerFixture , framework::DatasetMode::ALL , framework::dataset::combine(framework::dataset::combine(datasets::AlexNetFullyConnectedLayerDataset(), data_types), framework::dataset::make("Batches", 1)))
arm_compute::test::REGISTER_FIXTURE_DATA_TEST_CASE (AlexNetNormalizationLayer , NENormalizationLayerFixture , framework::DatasetMode::ALL , framework::dataset::combine(framework::dataset::combine(datasets::AlexNetNormalizationLayerDataset(), data_types), framework::dataset::make("Batches", 1)))
arm_compute::test::REGISTER_FIXTURE_DATA_TEST_CASE (AlexNetFullyConnectedLayer , CLFullyConnectedLayerFixture , framework::DatasetMode::ALL , framework::dataset::combine(framework::dataset::combine(datasets::AlexNetFullyConnectedLayerDataset(), data_types), framework::dataset::make("Batches", 1)))
arm_compute::test::REGISTER_FIXTURE_DATA_TEST_CASE (SoftmaxLayer , GCSoftmaxLayerFixture , framework::DatasetMode::NIGHTLY , framework::dataset::combine(datasets::SoftmaxLayerLargeShapes(), data_types))
arm_compute::test::REGISTER_FIXTURE_DATA_TEST_CASE (LeNet5 , CLLeNet5Fixture , framework::DatasetMode::ALL , framework::dataset::make("Batches",{1, 4, 8}))
arm_compute::test::REGISTER_FIXTURE_DATA_TEST_CASE (AlexNetDirectConvolutionLayer , CLConvolutionLayerFixture , framework::DatasetMode::ALL , framework::dataset::combine(framework::dataset::combine(datasets::AlexNetDirectConvolutionLayerDataset(), data_types), framework::dataset::make("Batches", 1)))
arm_compute::test::REGISTER_FIXTURE_DATA_TEST_CASE (AlexNetGEMM , CLGEMMFixture , framework::DatasetMode::NIGHTLY , framework::dataset::combine(datasets::AlexNetGEMMDataset(), data_types))
arm_compute::test::REGISTER_FIXTURE_DATA_TEST_CASE (AlexNetDirectConvolutionLayer , GCConvolutionLayerFixture , framework::DatasetMode::ALL , framework::dataset::combine(framework::dataset::combine(datasets::AlexNetDirectConvolutionLayerDataset(), data_types), framework::dataset::make("Batches", 1)))
arm_compute::test::REGISTER_FIXTURE_DATA_TEST_CASE (LeNet5 , NELeNet5Fixture , framework::DatasetMode::ALL , framework::dataset::make("Batches",{1, 4, 8}))
arm_compute::test::REGISTER_FIXTURE_DATA_TEST_CASE (LargeScaleLayer , GCScaleLayerFixture< half > , framework::DatasetMode::NIGHTLY , framework::dataset::combine(datasets::LargeScaleLayerShapes(), data_types))
arm_compute::test::REGISTER_FIXTURE_DATA_TEST_CASE (GoogLeNetInceptionV4BatchNormalizationLayer , GCBatchNormalizationLayerFixture , framework::DatasetMode::ALL , framework::dataset::combine(framework::dataset::combine(datasets::GoogLeNetInceptionV4BatchNormalizationLayerDataset(), data_types), framework::dataset::make("Batches", 1)))
arm_compute::test::REGISTER_FIXTURE_DATA_TEST_CASE (YOLOV2BatchNormalizationLayer , NEBatchNormalizationLayerFixture , framework::DatasetMode::ALL , framework::dataset::combine(framework::dataset::combine(datasets::YOLOV2BatchNormalizationLayerDataset(), data_types), framework::dataset::make("Batches", 1)))
arm_compute::test::REGISTER_FIXTURE_DATA_TEST_CASE (GoogLeNetInceptionV4BatchNormalizationLayer , CLBatchNormalizationLayerFixture , framework::DatasetMode::ALL , framework::dataset::combine(framework::dataset::combine(datasets::GoogLeNetInceptionV4BatchNormalizationLayerDataset(), data_types), framework::dataset::make("Batches", 1)))
arm_compute::test::REGISTER_FIXTURE_DATA_TEST_CASE (AlexNetConvolutionLayer , GCConvolutionLayerFixture , framework::DatasetMode::ALL , framework::dataset::combine(framework::dataset::combine(datasets::AlexNetConvolutionLayerDataset(), data_types), framework::dataset::make("Batches", 1)))
arm_compute::test::REGISTER_FIXTURE_DATA_TEST_CASE (AlexNetConvolutionLayer , CLConvolutionLayerFixture , framework::DatasetMode::ALL , framework::dataset::combine(framework::dataset::combine(datasets::AlexNetConvolutionLayerDataset(), data_types), framework::dataset::make("Batches", 1)))
arm_compute::test::REGISTER_FIXTURE_DATA_TEST_CASE (GoogLeNetInceptionV1NormalizationLayer , CLNormalizationLayerFixture , framework::DatasetMode::ALL , framework::dataset::combine(framework::dataset::combine(datasets::GoogLeNetInceptionV1NormalizationLayerDataset(), data_types), framework::dataset::make("Batches", 1)))
arm_compute::test::REGISTER_FIXTURE_DATA_TEST_CASE (AlexNetPoolingLayer , CLPoolingLayerFixture , framework::DatasetMode::ALL , framework::dataset::combine(framework::dataset::combine(datasets::AlexNetPoolingLayerDataset(), data_types), framework::dataset::make("Batches", 1)))
arm_compute::test::REGISTER_FIXTURE_DATA_TEST_CASE (AlexNetPoolingLayer , GCPoolingLayerFixture , framework::DatasetMode::ALL , framework::dataset::combine(framework::dataset::combine(datasets::AlexNetPoolingLayerDataset(), data_types), framework::dataset::make("Batches", 1)))
arm_compute::test::REGISTER_FIXTURE_DATA_TEST_CASE (MobileNet , CLMobileNetFixture , framework::DatasetMode::ALL , framework::dataset::make("Batches",{1, 4, 8}))
arm_compute::test::REGISTER_FIXTURE_DATA_TEST_CASE (AlexNetFullyConnectedLayer , NEFullyConnectedLayerFixture , framework::DatasetMode::ALL , framework::dataset::combine(framework::dataset::combine(datasets::AlexNetFullyConnectedLayerDataset(), data_types), framework::dataset::make("Batches", 1)))
arm_compute::test::REGISTER_FIXTURE_DATA_TEST_CASE (GoogLeNetInceptionV1GEMM , NEGEMMFixture , framework::DatasetMode::ALL , framework::dataset::combine(datasets::GoogLeNetInceptionV1GEMMDataset(), data_types))
arm_compute::test::REGISTER_FIXTURE_DATA_TEST_CASE (MatrixMultiplyGEMM , NEGEMMFixture , framework::DatasetMode::ALL , framework::dataset::combine(datasets::MatrixMultiplyGEMMDataset(), data_types))
arm_compute::test::REGISTER_FIXTURE_DATA_TEST_CASE (GoogLeNetInceptionV1NormalizationLayer , NENormalizationLayerFixture , framework::DatasetMode::ALL , framework::dataset::combine(framework::dataset::combine(datasets::GoogLeNetInceptionV1NormalizationLayerDataset(), data_types), framework::dataset::make("Batches", 1)))
arm_compute::test::REGISTER_FIXTURE_DATA_TEST_CASE (LeNet5FullyConnectedLayer , GCFullyConnectedLayerFixture , framework::DatasetMode::ALL , framework::dataset::combine(framework::dataset::combine(datasets::LeNet5FullyConnectedLayerDataset(), data_types), framework::dataset::make("Batches", 1)))
arm_compute::test::REGISTER_FIXTURE_DATA_TEST_CASE (LeNet5FullyConnectedLayer , CLFullyConnectedLayerFixture , framework::DatasetMode::ALL , framework::dataset::combine(framework::dataset::combine(datasets::LeNet5FullyConnectedLayerDataset(), data_types), framework::dataset::make("Batches", 1)))
arm_compute::test::REGISTER_FIXTURE_DATA_TEST_CASE (GoogLeNetInceptionV4BatchNormalizationLayer , NEBatchNormalizationLayerFixture , framework::DatasetMode::ALL , framework::dataset::combine(framework::dataset::combine(datasets::GoogLeNetInceptionV4BatchNormalizationLayerDataset(), data_types), framework::dataset::make("Batches", 1)))
arm_compute::test::REGISTER_FIXTURE_DATA_TEST_CASE (GoogLeNetInceptionV1DirectConvolutionLayer , CLConvolutionLayerFixture , framework::DatasetMode::ALL , framework::dataset::combine(framework::dataset::combine(datasets::GoogLeNetInceptionV1DirectConvolutionLayerDataset(), data_types), framework::dataset::make("Batches", 1)))
arm_compute::test::REGISTER_FIXTURE_DATA_TEST_CASE (GoogLeNetInceptionV1DirectConvolutionLayer , GCConvolutionLayerFixture , framework::DatasetMode::ALL , framework::dataset::combine(framework::dataset::combine(datasets::GoogLeNetInceptionV1DirectConvolutionLayerDataset(), data_types), framework::dataset::make("Batches", 1)))
arm_compute::test::REGISTER_FIXTURE_DATA_TEST_CASE (GoogleNetGEMM , NEGEMMFixture , framework::DatasetMode::NIGHTLY , framework::dataset::combine(datasets::GoogleNetGEMMDataset(), data_types))
arm_compute::test::REGISTER_FIXTURE_DATA_TEST_CASE (AlexNetPoolingLayer , NEPoolingLayerFixture , framework::DatasetMode::ALL , framework::dataset::combine(framework::dataset::combine(datasets::AlexNetPoolingLayerDataset(), data_types), framework::dataset::make("Batches", 1)))
arm_compute::test::REGISTER_FIXTURE_DATA_TEST_CASE (LeNet5ConvolutionLayer , GCConvolutionLayerFixture , framework::DatasetMode::ALL , framework::dataset::combine(framework::dataset::combine(datasets::LeNet5ConvolutionLayerDataset(), data_types), framework::dataset::make("Batches", 1)))
arm_compute::test::REGISTER_FIXTURE_DATA_TEST_CASE (AlexNetDirectConvolutionLayer , NEConvolutionLayerFixture , framework::DatasetMode::ALL , framework::dataset::combine(framework::dataset::combine(datasets::AlexNetDirectConvolutionLayerDataset(), data_types), framework::dataset::make("Batches", 1)))
arm_compute::test::REGISTER_FIXTURE_DATA_TEST_CASE (LeNet5PoolingLayer , CLPoolingLayerFixture , framework::DatasetMode::ALL , framework::dataset::combine(framework::dataset::combine(datasets::LeNet5PoolingLayerDataset(), data_types), framework::dataset::make("Batches", 1)))
arm_compute::test::REGISTER_FIXTURE_DATA_TEST_CASE (LeNet5PoolingLayer , GCPoolingLayerFixture , framework::DatasetMode::ALL , framework::dataset::combine(framework::dataset::combine(datasets::LeNet5PoolingLayerDataset(), data_types), framework::dataset::make("Batches", 1)))
arm_compute::test::REGISTER_FIXTURE_DATA_TEST_CASE (LeNet5ConvolutionLayer , CLConvolutionLayerFixture , framework::DatasetMode::ALL , framework::dataset::combine(framework::dataset::combine(datasets::LeNet5ConvolutionLayerDataset(), data_types), framework::dataset::make("Batches", 1)))
arm_compute::test::REGISTER_FIXTURE_DATA_TEST_CASE (AlexNet , CLAlexNetFixture , framework::DatasetMode::ALL , framework::dataset::combine(framework::dataset::make("DataType",{DataType::F16, DataType::F32}), framework::dataset::make("Batches",{1, 2, 4})))
arm_compute::test::REGISTER_FIXTURE_DATA_TEST_CASE (YOLOV2BatchNormalizationLayer , GCBatchNormalizationLayerFixture , framework::DatasetMode::NIGHTLY , framework::dataset::combine(framework::dataset::combine(datasets::YOLOV2BatchNormalizationLayerDataset(), data_types), framework::dataset::make("Batches",{4, 8})))
arm_compute::test::REGISTER_FIXTURE_DATA_TEST_CASE (YOLOV2BatchNormalizationLayer , CLBatchNormalizationLayerFixture , framework::DatasetMode::NIGHTLY , framework::dataset::combine(framework::dataset::combine(datasets::YOLOV2BatchNormalizationLayerDataset(), data_types), framework::dataset::make("Batches",{4, 8})))
arm_compute::test::REGISTER_FIXTURE_DATA_TEST_CASE (AlexNetNormalizationLayer , CLNormalizationLayerFixture , framework::DatasetMode::NIGHTLY , framework::dataset::combine(framework::dataset::combine(datasets::AlexNetNormalizationLayerDataset(), data_types), framework::dataset::make("Batches",{4, 8})))
arm_compute::test::REGISTER_FIXTURE_DATA_TEST_CASE (AlexNetActivationLayer , NEActivationLayerFixture , framework::DatasetMode::ALL , framework::dataset::combine(framework::dataset::combine(datasets::AlexNetActivationLayerDataset(), data_types), framework::dataset::make("Batches", 1)))
arm_compute::test::REGISTER_FIXTURE_DATA_TEST_CASE (LeNet5FullyConnectedLayer , NEFullyConnectedLayerFixture , framework::DatasetMode::ALL , framework::dataset::combine(framework::dataset::combine(datasets::LeNet5FullyConnectedLayerDataset(), data_types), framework::dataset::make("Batches", 1)))
arm_compute::test::REGISTER_FIXTURE_DATA_TEST_CASE (LeNet5PoolingLayer , NEPoolingLayerFixture , framework::DatasetMode::ALL , framework::dataset::combine(framework::dataset::combine(datasets::LeNet5PoolingLayerDataset(), data_types), framework::dataset::make("Batches", 1)))
arm_compute::test::REGISTER_FIXTURE_DATA_TEST_CASE (VGG16FullyConnectedLayer , CLFullyConnectedLayerFixture , framework::DatasetMode::ALL , framework::dataset::combine(framework::dataset::combine(datasets::VGG16FullyConnectedLayerDataset(), data_types), framework::dataset::make("Batches", 1)))
arm_compute::test::REGISTER_FIXTURE_DATA_TEST_CASE (VGG16FullyConnectedLayer , GCFullyConnectedLayerFixture , framework::DatasetMode::ALL , framework::dataset::combine(framework::dataset::combine(datasets::VGG16FullyConnectedLayerDataset(), data_types), framework::dataset::make("Batches", 1)))
arm_compute::test::REGISTER_FIXTURE_DATA_TEST_CASE (YOLOV2BatchNormalizationLayer , NEBatchNormalizationLayerFixture , framework::DatasetMode::NIGHTLY , framework::dataset::combine(framework::dataset::combine(datasets::YOLOV2BatchNormalizationLayerDataset(), data_types), framework::dataset::make("Batches",{4, 8})))
arm_compute::test::REGISTER_FIXTURE_DATA_TEST_CASE (GoogLeNetInceptionV4DirectConvolutionLayer , GCConvolutionLayerFixture , framework::DatasetMode::ALL , framework::dataset::combine(framework::dataset::combine(datasets::GoogLeNetInceptionV4DirectConvolutionLayerDataset(), data_types), framework::dataset::make("Batches", 1)))
arm_compute::test::REGISTER_FIXTURE_DATA_TEST_CASE (GoogLeNetInceptionV1DirectConvolutionLayer , NEConvolutionLayerFixture , framework::DatasetMode::ALL , framework::dataset::combine(framework::dataset::combine(datasets::GoogLeNetInceptionV1DirectConvolutionLayerDataset(), data_types), framework::dataset::make("Batches", 1)))
arm_compute::test::REGISTER_FIXTURE_DATA_TEST_CASE (GoogLeNetInceptionV4DirectConvolutionLayer , CLConvolutionLayerFixture , framework::DatasetMode::ALL , framework::dataset::combine(framework::dataset::combine(datasets::GoogLeNetInceptionV4DirectConvolutionLayerDataset(), data_types), framework::dataset::make("Batches", 1)))
arm_compute::test::REGISTER_FIXTURE_DATA_TEST_CASE (AlexNetNormalizationLayer , NENormalizationLayerFixture , framework::DatasetMode::NIGHTLY , framework::dataset::combine(framework::dataset::combine(datasets::AlexNetNormalizationLayerDataset(), data_types), framework::dataset::make("Batches",{4, 8})))
arm_compute::test::REGISTER_FIXTURE_DATA_TEST_CASE (GoogLeNetInceptionV1ConvolutionLayer , GCConvolutionLayerFixture , framework::DatasetMode::ALL , framework::dataset::combine(framework::dataset::combine(datasets::GoogLeNetInceptionV1ConvolutionLayerDataset(), data_types), framework::dataset::make("Batches", 1)))
arm_compute::test::REGISTER_FIXTURE_DATA_TEST_CASE (GoogLeNetInceptionV1PoolingLayer , NEPoolingLayerFixture , framework::DatasetMode::ALL , framework::dataset::combine(framework::dataset::combine(datasets::GoogLeNetInceptionV1PoolingLayerDataset(), data_types), framework::dataset::make("Batches", 1)))
arm_compute::test::REGISTER_FIXTURE_DATA_TEST_CASE (GoogLeNetInceptionV1PoolingLayer , CLPoolingLayerFixture , framework::DatasetMode::ALL , framework::dataset::combine(framework::dataset::combine(datasets::GoogLeNetInceptionV1PoolingLayerDataset(), data_types), framework::dataset::make("Batches", 1)))
arm_compute::test::REGISTER_FIXTURE_DATA_TEST_CASE (GoogLeNetInceptionV1ConvolutionLayer , CLConvolutionLayerFixture , framework::DatasetMode::ALL , framework::dataset::combine(framework::dataset::combine(datasets::GoogLeNetInceptionV1ConvolutionLayerDataset(), data_types), framework::dataset::make("Batches", 1)))
arm_compute::test::REGISTER_FIXTURE_DATA_TEST_CASE (GoogLeNetInceptionV1PoolingLayer , GCPoolingLayerFixture , framework::DatasetMode::ALL , framework::dataset::combine(framework::dataset::combine(datasets::GoogLeNetInceptionV1PoolingLayerDataset(), data_types), framework::dataset::make("Batches", 1)))
arm_compute::test::REGISTER_FIXTURE_DATA_TEST_CASE (GoogLeNetInceptionV4BatchNormalizationLayer , CLBatchNormalizationLayerFixture , framework::DatasetMode::NIGHTLY , framework::dataset::combine(framework::dataset::combine(datasets::GoogLeNetInceptionV4BatchNormalizationLayerDataset(), data_types), framework::dataset::make("Batches",{4, 8})))
arm_compute::test::REGISTER_FIXTURE_DATA_TEST_CASE (LeNet5ActivationLayer , NEActivationLayerFixture , framework::DatasetMode::ALL , framework::dataset::combine(framework::dataset::combine(datasets::LeNet5ActivationLayerDataset(), data_types), framework::dataset::make("Batches", 1)))
arm_compute::test::REGISTER_FIXTURE_DATA_TEST_CASE (GoogLeNetInceptionV4BatchNormalizationLayer , GCBatchNormalizationLayerFixture , framework::DatasetMode::NIGHTLY , framework::dataset::combine(framework::dataset::combine(datasets::GoogLeNetInceptionV4BatchNormalizationLayerDataset(), data_types), framework::dataset::make("Batches",{4, 8})))
arm_compute::test::REGISTER_FIXTURE_DATA_TEST_CASE (GoogLeNetInceptionV1NormalizationLayer , CLNormalizationLayerFixture , framework::DatasetMode::NIGHTLY , framework::dataset::combine(framework::dataset::combine(datasets::GoogLeNetInceptionV1NormalizationLayerDataset(), data_types), framework::dataset::make("Batches",{4, 8})))
arm_compute::test::REGISTER_FIXTURE_DATA_TEST_CASE (VGG16FullyConnectedLayer , NEFullyConnectedLayerFixture , framework::DatasetMode::ALL , framework::dataset::combine(framework::dataset::combine(datasets::VGG16FullyConnectedLayerDataset(), data_types), framework::dataset::make("Batches", 1)))
arm_compute::test::REGISTER_FIXTURE_DATA_TEST_CASE (GoogLeNetInceptionV1FullyConnectedLayer , CLFullyConnectedLayerFixture , framework::DatasetMode::ALL , framework::dataset::combine(framework::dataset::combine(datasets::GoogLeNetInceptionV1FullyConnectedLayerDataset(), data_types), framework::dataset::make("Batches", 1)))
arm_compute::test::REGISTER_FIXTURE_DATA_TEST_CASE (GoogLeNetInceptionV4BatchNormalizationLayer , NEBatchNormalizationLayerFixture , framework::DatasetMode::NIGHTLY , framework::dataset::combine(framework::dataset::combine(datasets::GoogLeNetInceptionV4BatchNormalizationLayerDataset(), data_types), framework::dataset::make("Batches",{4, 8})))
arm_compute::test::REGISTER_FIXTURE_DATA_TEST_CASE (GoogLeNetInceptionV4PoolingLayer , NEPoolingLayerFixture , framework::DatasetMode::ALL , framework::dataset::combine(framework::dataset::combine(datasets::GoogLeNetInceptionV4PoolingLayerDataset(), data_types), framework::dataset::make("Batches", 1)))
arm_compute::test::REGISTER_FIXTURE_DATA_TEST_CASE (GoogLeNetInceptionV4DirectConvolutionLayer , NEConvolutionLayerFixture , framework::DatasetMode::ALL , framework::dataset::combine(framework::dataset::combine(datasets::GoogLeNetInceptionV4DirectConvolutionLayerDataset(), data_types), framework::dataset::make("Batches", 1)))
arm_compute::test::REGISTER_FIXTURE_DATA_TEST_CASE (GoogLeNetInceptionV1FullyConnectedLayer , GCFullyConnectedLayerFixture , framework::DatasetMode::ALL , framework::dataset::combine(framework::dataset::combine(datasets::GoogLeNetInceptionV1FullyConnectedLayerDataset(), data_types), framework::dataset::make("Batches", 1)))
arm_compute::test::REGISTER_FIXTURE_DATA_TEST_CASE (SqueezeNetDirectConvolutionLayer , CLConvolutionLayerFixture , framework::DatasetMode::ALL , framework::dataset::combine(framework::dataset::combine(datasets::SqueezeNetConvolutionLayerDataset(), data_types), framework::dataset::make("Batches", 1)))
arm_compute::test::REGISTER_FIXTURE_DATA_TEST_CASE (SqueezeNetDirectConvolutionLayer , GCConvolutionLayerFixture , framework::DatasetMode::ALL , framework::dataset::combine(framework::dataset::combine(datasets::SqueezeNetConvolutionLayerDataset(), data_types), framework::dataset::make("Batches", 1)))
arm_compute::test::REGISTER_FIXTURE_DATA_TEST_CASE (GoogLeNetInceptionV1NormalizationLayer , NENormalizationLayerFixture , framework::DatasetMode::NIGHTLY , framework::dataset::combine(framework::dataset::combine(datasets::GoogLeNetInceptionV1NormalizationLayerDataset(), data_types), framework::dataset::make("Batches",{4, 8})))
arm_compute::test::REGISTER_FIXTURE_DATA_TEST_CASE (MobileNetActivationLayer , NEActivationLayerFixture , framework::DatasetMode::ALL , framework::dataset::combine(framework::dataset::combine(datasets::MobileNetActivationLayerDataset(), data_types_mobilenet), framework::dataset::make("Batches", 1)))
arm_compute::test::REGISTER_FIXTURE_DATA_TEST_CASE (GoogLeNetInceptionV4ConvolutionLayer , CLConvolutionLayerFixture , framework::DatasetMode::ALL , framework::dataset::combine(framework::dataset::combine(datasets::GoogLeNetInceptionV4ConvolutionLayerDataset(), data_types), framework::dataset::make("Batches", 1)))
arm_compute::test::REGISTER_FIXTURE_DATA_TEST_CASE (GoogLeNetInceptionV4ConvolutionLayer , GCConvolutionLayerFixture , framework::DatasetMode::ALL , framework::dataset::combine(framework::dataset::combine(datasets::GoogLeNetInceptionV4ConvolutionLayerDataset(), data_types), framework::dataset::make("Batches", 1)))
arm_compute::test::REGISTER_FIXTURE_DATA_TEST_CASE (AlexNet , NEAlexNetFixture , framework::DatasetMode::ALL , framework::dataset::combine(alex_net_data_types, framework::dataset::make("Batches",{1, 2, 4})))
arm_compute::test::REGISTER_FIXTURE_DATA_TEST_CASE (GoogLeNetInceptionV4PoolingLayer , CLPoolingLayerFixture , framework::DatasetMode::ALL , framework::dataset::combine(framework::dataset::combine(datasets::GoogLeNetInceptionV4PoolingLayerDataset(), data_types), framework::dataset::make("Batches", 1)))
arm_compute::test::REGISTER_FIXTURE_DATA_TEST_CASE (GoogLeNetInceptionV4PoolingLayer , GCPoolingLayerFixture , framework::DatasetMode::ALL , framework::dataset::combine(framework::dataset::combine(datasets::GoogLeNetInceptionV4PoolingLayerDataset(), data_types), framework::dataset::make("Batches", 1)))
arm_compute::test::REGISTER_FIXTURE_DATA_TEST_CASE (SqueezeNetPoolingLayer , NEPoolingLayerFixture , framework::DatasetMode::ALL , framework::dataset::combine(framework::dataset::combine(datasets::SqueezeNetPoolingLayerDataset(), data_types), framework::dataset::make("Batches", 1)))
arm_compute::test::REGISTER_FIXTURE_DATA_TEST_CASE (SqueezeNetDirectConvolutionLayer , NEConvolutionLayerFixture , framework::DatasetMode::ALL , framework::dataset::combine(framework::dataset::combine(datasets::SqueezeNetConvolutionLayerDataset(), data_types), framework::dataset::make("Batches", 1)))
arm_compute::test::REGISTER_FIXTURE_DATA_TEST_CASE (GoogLeNetInceptionV1FullyConnectedLayer , NEFullyConnectedLayerFixture , framework::DatasetMode::ALL , framework::dataset::combine(framework::dataset::combine(datasets::GoogLeNetInceptionV1FullyConnectedLayerDataset(), data_types), framework::dataset::make("Batches", 1)))
arm_compute::test::REGISTER_FIXTURE_DATA_TEST_CASE (GoogLeNetInceptionV4FullyConnectedLayer , CLFullyConnectedLayerFixture , framework::DatasetMode::ALL , framework::dataset::combine(framework::dataset::combine(datasets::GoogLeNetInceptionV4FullyConnectedLayerDataset(), data_types), framework::dataset::make("Batches", 1)))
arm_compute::test::REGISTER_FIXTURE_DATA_TEST_CASE (MobileNetV1_224 , CLMobileNetV1_224_Fixture , framework::DatasetMode::ALL , framework::dataset::make("Batches",{1, 4, 8}))
arm_compute::test::REGISTER_FIXTURE_DATA_TEST_CASE (GoogLeNetInceptionV4FullyConnectedLayer , GCFullyConnectedLayerFixture , framework::DatasetMode::ALL , framework::dataset::combine(framework::dataset::combine(datasets::GoogLeNetInceptionV4FullyConnectedLayerDataset(), data_types), framework::dataset::make("Batches", 1)))
arm_compute::test::REGISTER_FIXTURE_DATA_TEST_CASE (GoogLeNetInceptionV1ActivationLayer , NEActivationLayerFixture , framework::DatasetMode::ALL , framework::dataset::combine(framework::dataset::combine(datasets::GoogLeNetInceptionV1ActivationLayerDataset(), data_types), framework::dataset::make("Batches", 1)))
arm_compute::test::REGISTER_FIXTURE_DATA_TEST_CASE (VGG16PoolingLayer , NEPoolingLayerFixture , framework::DatasetMode::ALL , framework::dataset::combine(framework::dataset::combine(datasets::VGG16PoolingLayerDataset(), data_types), framework::dataset::make("Batches", 1)))
arm_compute::test::REGISTER_FIXTURE_DATA_TEST_CASE (SqueezeNetConvolutionLayer , CLConvolutionLayerFixture , framework::DatasetMode::ALL , framework::dataset::combine(framework::dataset::combine(datasets::SqueezeNetConvolutionLayerDataset(), data_types), framework::dataset::make("Batches", 1)))
arm_compute::test::REGISTER_FIXTURE_DATA_TEST_CASE (SqueezeNetConvolutionLayer , GCConvolutionLayerFixture , framework::DatasetMode::ALL , framework::dataset::combine(framework::dataset::combine(datasets::SqueezeNetConvolutionLayerDataset(), data_types), framework::dataset::make("Batches", 1)))
arm_compute::test::REGISTER_FIXTURE_DATA_TEST_CASE (AlexNetDirectConvolutionLayer , CLConvolutionLayerFixture , framework::DatasetMode::NIGHTLY , framework::dataset::combine(framework::dataset::combine(datasets::AlexNetDirectConvolutionLayerDataset(), data_types), framework::dataset::make("Batches",{4, 8})))
arm_compute::test::REGISTER_FIXTURE_DATA_TEST_CASE (AlexNetDirectConvolutionLayer , GCConvolutionLayerFixture , framework::DatasetMode::NIGHTLY , framework::dataset::combine(framework::dataset::combine(datasets::AlexNetDirectConvolutionLayerDataset(), data_types), framework::dataset::make("Batches",{4, 8})))
arm_compute::test::REGISTER_FIXTURE_DATA_TEST_CASE (SqueezeNetPoolingLayer , CLPoolingLayerFixture , framework::DatasetMode::ALL , framework::dataset::combine(framework::dataset::combine(datasets::SqueezeNetPoolingLayerDataset(), data_types), framework::dataset::make("Batches", 1)))
arm_compute::test::REGISTER_FIXTURE_DATA_TEST_CASE (SqueezeNetPoolingLayer , GCPoolingLayerFixture , framework::DatasetMode::ALL , framework::dataset::combine(framework::dataset::combine(datasets::SqueezeNetPoolingLayerDataset(), data_types), framework::dataset::make("Batches", 1)))
arm_compute::test::REGISTER_FIXTURE_DATA_TEST_CASE (MobileNetV1_128 , CLMobileNetV1_128_Fixture , framework::DatasetMode::ALL , framework::dataset::make("Batches",{1, 4, 8}))
arm_compute::test::REGISTER_FIXTURE_DATA_TEST_CASE (AlexNetDirectConvolutionLayer , NEConvolutionLayerFixture , framework::DatasetMode::NIGHTLY , framework::dataset::combine(framework::dataset::combine(datasets::AlexNetDirectConvolutionLayerDataset(), data_types), framework::dataset::make("Batches",{4, 8})))
arm_compute::test::REGISTER_FIXTURE_DATA_TEST_CASE (GoogLeNetInceptionV4FullyConnectedLayer , NEFullyConnectedLayerFixture , framework::DatasetMode::ALL , framework::dataset::combine(framework::dataset::combine(datasets::GoogLeNetInceptionV4FullyConnectedLayerDataset(), data_types), framework::dataset::make("Batches", 1)))
arm_compute::test::REGISTER_FIXTURE_DATA_TEST_CASE (YOLOV2PoolingLayer , NEPoolingLayerFixture , framework::DatasetMode::ALL , framework::dataset::combine(framework::dataset::combine(datasets::YOLOV2PoolingLayerDataset(), data_types), framework::dataset::make("Batches", 1)))
arm_compute::test::REGISTER_FIXTURE_DATA_TEST_CASE (GoogLeNetInceptionV4ActivationLayer , NEActivationLayerFixture , framework::DatasetMode::ALL , framework::dataset::combine(framework::dataset::combine(datasets::GoogLeNetInceptionV4ActivationLayerDataset(), data_types), framework::dataset::make("Batches", 1)))
arm_compute::test::REGISTER_FIXTURE_DATA_TEST_CASE (AlexNetFullyConnectedLayer , CLFullyConnectedLayerFixture , framework::DatasetMode::NIGHTLY , framework::dataset::combine(framework::dataset::combine(datasets::AlexNetFullyConnectedLayerDataset(), data_types), framework::dataset::make("Batches",{4, 8})))
arm_compute::test::REGISTER_FIXTURE_DATA_TEST_CASE (AlexNetConvolutionLayer , NEConvolutionLayerFixture , framework::DatasetMode::ALL , framework::dataset::combine(framework::dataset::combine(datasets::AlexNetConvolutionLayerDataset(), data_types), framework::dataset::make("Batches", 1)))
arm_compute::test::REGISTER_FIXTURE_DATA_TEST_CASE (AlexNetFullyConnectedLayer , GCFullyConnectedLayerFixture , framework::DatasetMode::NIGHTLY , framework::dataset::combine(framework::dataset::combine(datasets::AlexNetFullyConnectedLayerDataset(), data_types), framework::dataset::make("Batches",{4, 8})))
arm_compute::test::REGISTER_FIXTURE_DATA_TEST_CASE (GoogLeNetInceptionV1DirectConvolutionLayer , GCConvolutionLayerFixture , framework::DatasetMode::NIGHTLY , framework::dataset::combine(framework::dataset::combine(datasets::GoogLeNetInceptionV1DirectConvolutionLayerDataset(), data_types), framework::dataset::make("Batches",{4, 8})))
arm_compute::test::REGISTER_FIXTURE_DATA_TEST_CASE (GoogLeNetInceptionV1DirectConvolutionLayer , CLConvolutionLayerFixture , framework::DatasetMode::NIGHTLY , framework::dataset::combine(framework::dataset::combine(datasets::GoogLeNetInceptionV1DirectConvolutionLayerDataset(), data_types), framework::dataset::make("Batches",{4, 8})))
arm_compute::test::REGISTER_FIXTURE_DATA_TEST_CASE (VGG16PoolingLayer , CLPoolingLayerFixture , framework::DatasetMode::ALL , framework::dataset::combine(framework::dataset::combine(datasets::VGG16PoolingLayerDataset(), data_types), framework::dataset::make("Batches", 1)))
arm_compute::test::REGISTER_FIXTURE_DATA_TEST_CASE (VGG16PoolingLayer , GCPoolingLayerFixture , framework::DatasetMode::ALL , framework::dataset::combine(framework::dataset::combine(datasets::VGG16PoolingLayerDataset(), data_types), framework::dataset::make("Batches", 1)))
arm_compute::test::REGISTER_FIXTURE_DATA_TEST_CASE (AlexNetConvolutionLayer , CLConvolutionLayerFixture , framework::DatasetMode::NIGHTLY , framework::dataset::combine(framework::dataset::combine(datasets::AlexNetConvolutionLayerDataset(), data_types), framework::dataset::make("Batches",{4, 8})))
arm_compute::test::REGISTER_FIXTURE_DATA_TEST_CASE (GoogLeNetInceptionV1DirectConvolutionLayer , NEConvolutionLayerFixture , framework::DatasetMode::NIGHTLY , framework::dataset::combine(framework::dataset::combine(datasets::GoogLeNetInceptionV1DirectConvolutionLayerDataset(), data_types), framework::dataset::make("Batches",{4, 8})))
arm_compute::test::REGISTER_FIXTURE_DATA_TEST_CASE (AlexNetConvolutionLayer , GCConvolutionLayerFixture , framework::DatasetMode::NIGHTLY , framework::dataset::combine(framework::dataset::combine(datasets::AlexNetConvolutionLayerDataset(), data_types), framework::dataset::make("Batches",{4, 8})))
arm_compute::test::REGISTER_FIXTURE_DATA_TEST_CASE (AlexNetPoolingLayer , NEPoolingLayerFixture , framework::DatasetMode::NIGHTLY , framework::dataset::combine(framework::dataset::combine(datasets::AlexNetPoolingLayerDataset(), data_types), framework::dataset::make("Batches",{4, 8})))
arm_compute::test::REGISTER_FIXTURE_DATA_TEST_CASE (SqueezeNetActivationLayer , NEActivationLayerFixture , framework::DatasetMode::ALL , framework::dataset::combine(framework::dataset::combine(datasets::SqueezeNetActivationLayerDataset(), data_types), framework::dataset::make("Batches", 1)))
arm_compute::test::REGISTER_FIXTURE_DATA_TEST_CASE (AlexNetFullyConnectedLayer , NEFullyConnectedLayerFixture , framework::DatasetMode::NIGHTLY , framework::dataset::combine(framework::dataset::combine(datasets::AlexNetFullyConnectedLayerDataset(), data_types), framework::dataset::make("Batches",{4, 8})))
arm_compute::test::REGISTER_FIXTURE_DATA_TEST_CASE (LeNet5ConvolutionLayer , NEConvolutionLayerFixture , framework::DatasetMode::ALL , framework::dataset::combine(framework::dataset::combine(datasets::LeNet5ConvolutionLayerDataset(), data_types), framework::dataset::make("Batches", 1)))
arm_compute::test::REGISTER_FIXTURE_DATA_TEST_CASE (LeNet5FullyConnectedLayer , CLFullyConnectedLayerFixture , framework::DatasetMode::NIGHTLY , framework::dataset::combine(framework::dataset::combine(datasets::LeNet5FullyConnectedLayerDataset(), data_types), framework::dataset::make("Batches",{4, 8})))
arm_compute::test::REGISTER_FIXTURE_DATA_TEST_CASE (LeNet5FullyConnectedLayer , GCFullyConnectedLayerFixture , framework::DatasetMode::NIGHTLY , framework::dataset::combine(framework::dataset::combine(datasets::LeNet5FullyConnectedLayerDataset(), data_types), framework::dataset::make("Batches",{4, 8})))
arm_compute::test::REGISTER_FIXTURE_DATA_TEST_CASE (LeNet5PoolingLayer , NEPoolingLayerFixture , framework::DatasetMode::NIGHTLY , framework::dataset::combine(framework::dataset::combine(datasets::LeNet5PoolingLayerDataset(), data_types), framework::dataset::make("Batches",{4, 8})))
arm_compute::test::REGISTER_FIXTURE_DATA_TEST_CASE (GoogLeNetInceptionV4DirectConvolutionLayer , CLConvolutionLayerFixture , framework::DatasetMode::NIGHTLY , framework::dataset::combine(framework::dataset::combine(datasets::GoogLeNetInceptionV4DirectConvolutionLayerDataset(), data_types), framework::dataset::make("Batches",{4, 8})))
arm_compute::test::REGISTER_FIXTURE_DATA_TEST_CASE (GoogLeNetInceptionV4DirectConvolutionLayer , NEConvolutionLayerFixture , framework::DatasetMode::NIGHTLY , framework::dataset::combine(framework::dataset::combine(datasets::GoogLeNetInceptionV4DirectConvolutionLayerDataset(), data_types), framework::dataset::make("Batches",{4, 8})))
arm_compute::test::REGISTER_FIXTURE_DATA_TEST_CASE (GoogLeNetInceptionV4DirectConvolutionLayer , GCConvolutionLayerFixture , framework::DatasetMode::NIGHTLY , framework::dataset::combine(framework::dataset::combine(datasets::GoogLeNetInceptionV4DirectConvolutionLayerDataset(), data_types), framework::dataset::make("Batches",{4, 8})))
arm_compute::test::REGISTER_FIXTURE_DATA_TEST_CASE (YOLOV2PoolingLayer , CLPoolingLayerFixture , framework::DatasetMode::ALL , framework::dataset::combine(framework::dataset::combine(datasets::YOLOV2PoolingLayerDataset(), data_types), framework::dataset::make("Batches", 1)))
arm_compute::test::REGISTER_FIXTURE_DATA_TEST_CASE (YOLOV2PoolingLayer , GCPoolingLayerFixture , framework::DatasetMode::ALL , framework::dataset::combine(framework::dataset::combine(datasets::YOLOV2PoolingLayerDataset(), data_types), framework::dataset::make("Batches", 1)))
arm_compute::test::REGISTER_FIXTURE_DATA_TEST_CASE (VGG16ActivationLayer , NEActivationLayerFixture , framework::DatasetMode::ALL , framework::dataset::combine(framework::dataset::combine(datasets::VGG16ActivationLayerDataset(), data_types), framework::dataset::make("Batches", 1)))
arm_compute::test::REGISTER_FIXTURE_DATA_TEST_CASE (LeNet5ConvolutionLayer , GCConvolutionLayerFixture , framework::DatasetMode::NIGHTLY , framework::dataset::combine(framework::dataset::combine(datasets::LeNet5ConvolutionLayerDataset(), data_types), framework::dataset::make("Batches",{4, 8})))
arm_compute::test::REGISTER_FIXTURE_DATA_TEST_CASE (LeNet5ConvolutionLayer , CLConvolutionLayerFixture , framework::DatasetMode::NIGHTLY , framework::dataset::combine(framework::dataset::combine(datasets::LeNet5ConvolutionLayerDataset(), data_types), framework::dataset::make("Batches",{4, 8})))
arm_compute::test::REGISTER_FIXTURE_DATA_TEST_CASE (GoogLeNetInceptionV1ConvolutionLayer , NEConvolutionLayerFixture , framework::DatasetMode::ALL , framework::dataset::combine(framework::dataset::combine(datasets::GoogLeNetInceptionV1ConvolutionLayerDataset(), data_types), framework::dataset::make("Batches", 1)))
arm_compute::test::REGISTER_FIXTURE_DATA_TEST_CASE (GoogLeNetInceptionV1PoolingLayer , NEPoolingLayerFixture , framework::DatasetMode::NIGHTLY , framework::dataset::combine(framework::dataset::combine(datasets::GoogLeNetInceptionV1PoolingLayerDataset(), data_types), framework::dataset::make("Batches",{4, 8})))
arm_compute::test::REGISTER_FIXTURE_DATA_TEST_CASE (LeNet5FullyConnectedLayer , NEFullyConnectedLayerFixture , framework::DatasetMode::NIGHTLY , framework::dataset::combine(framework::dataset::combine(datasets::LeNet5FullyConnectedLayerDataset(), data_types), framework::dataset::make("Batches",{4, 8})))
arm_compute::test::REGISTER_FIXTURE_DATA_TEST_CASE (VGG16FullyConnectedLayer , CLFullyConnectedLayerFixture , framework::DatasetMode::NIGHTLY , framework::dataset::combine(framework::dataset::combine(datasets::VGG16FullyConnectedLayerDataset(), data_types), framework::dataset::make("Batches",{4, 8})))
arm_compute::test::REGISTER_FIXTURE_DATA_TEST_CASE (SqueezeNetDirectConvolutionLayer , NEConvolutionLayerFixture , framework::DatasetMode::NIGHTLY , framework::dataset::combine(framework::dataset::combine(datasets::SqueezeNetConvolutionLayerDataset(), data_types), framework::dataset::make("Batches",{4, 8})))
arm_compute::test::REGISTER_FIXTURE_DATA_TEST_CASE (VGG16FullyConnectedLayer , GCFullyConnectedLayerFixture , framework::DatasetMode::NIGHTLY , framework::dataset::combine(framework::dataset::combine(datasets::VGG16FullyConnectedLayerDataset(), data_types), framework::dataset::make("Batches",{4, 8})))
arm_compute::test::REGISTER_FIXTURE_DATA_TEST_CASE (YOLOV2ActivationLayer , NEActivationLayerFixture , framework::DatasetMode::ALL , framework::dataset::combine(framework::dataset::combine(datasets::YOLOV2ActivationLayerDataset(), data_types), framework::dataset::make("Batches", 1)))
arm_compute::test::REGISTER_FIXTURE_DATA_TEST_CASE (SqueezeNetDirectConvolutionLayer , GCConvolutionLayerFixture , framework::DatasetMode::NIGHTLY , framework::dataset::combine(framework::dataset::combine(datasets::SqueezeNetConvolutionLayerDataset(), data_types), framework::dataset::make("Batches",{4, 8})))
arm_compute::test::REGISTER_FIXTURE_DATA_TEST_CASE (SqueezeNetDirectConvolutionLayer , CLConvolutionLayerFixture , framework::DatasetMode::NIGHTLY , framework::dataset::combine(framework::dataset::combine(datasets::SqueezeNetConvolutionLayerDataset(), data_types), framework::dataset::make("Batches",{4, 8})))
arm_compute::test::REGISTER_FIXTURE_DATA_TEST_CASE (GoogLeNetInceptionV4PoolingLayer , NEPoolingLayerFixture , framework::DatasetMode::NIGHTLY , framework::dataset::combine(framework::dataset::combine(datasets::GoogLeNetInceptionV4PoolingLayerDataset(), data_types), framework::dataset::make("Batches",{4, 8})))
arm_compute::test::REGISTER_FIXTURE_DATA_TEST_CASE (GoogLeNetInceptionV1ConvolutionLayer , CLConvolutionLayerFixture , framework::DatasetMode::NIGHTLY , framework::dataset::combine(framework::dataset::combine(datasets::GoogLeNetInceptionV1ConvolutionLayerDataset(), data_types), framework::dataset::make("Batches",{4, 8})))
arm_compute::test::REGISTER_FIXTURE_DATA_TEST_CASE (GoogLeNetInceptionV4ConvolutionLayer , NEConvolutionLayerFixture , framework::DatasetMode::ALL , framework::dataset::combine(framework::dataset::combine(datasets::GoogLeNetInceptionV4ConvolutionLayerDataset(), data_types), framework::dataset::make("Batches", 1)))
arm_compute::test::REGISTER_FIXTURE_DATA_TEST_CASE (GoogLeNetInceptionV1ConvolutionLayer , GCConvolutionLayerFixture , framework::DatasetMode::NIGHTLY , framework::dataset::combine(framework::dataset::combine(datasets::GoogLeNetInceptionV1ConvolutionLayerDataset(), data_types), framework::dataset::make("Batches",{4, 8})))
arm_compute::test::REGISTER_FIXTURE_DATA_TEST_CASE (AlexNetPoolingLayer , CLPoolingLayerFixture , framework::DatasetMode::NIGHTLY , framework::dataset::combine(framework::dataset::combine(datasets::AlexNetPoolingLayerDataset(), data_types), framework::dataset::make("Batches",{4, 8})))
arm_compute::test::REGISTER_FIXTURE_DATA_TEST_CASE (AlexNetPoolingLayer , GCPoolingLayerFixture , framework::DatasetMode::NIGHTLY , framework::dataset::combine(framework::dataset::combine(datasets::AlexNetPoolingLayerDataset(), data_types), framework::dataset::make("Batches",{4, 8})))
arm_compute::test::REGISTER_FIXTURE_DATA_TEST_CASE (SqueezeNetPoolingLayer , NEPoolingLayerFixture , framework::DatasetMode::NIGHTLY , framework::dataset::combine(framework::dataset::combine(datasets::SqueezeNetPoolingLayerDataset(), data_types), framework::dataset::make("Batches",{4, 8})))
arm_compute::test::REGISTER_FIXTURE_DATA_TEST_CASE (VGG16FullyConnectedLayer , NEFullyConnectedLayerFixture , framework::DatasetMode::NIGHTLY , framework::dataset::combine(framework::dataset::combine(datasets::VGG16FullyConnectedLayerDataset(), data_types), framework::dataset::make("Batches",{2})))
arm_compute::test::REGISTER_FIXTURE_DATA_TEST_CASE (VGG16DirectConvolutionLayer , NEConvolutionLayerFixture , framework::DatasetMode::NIGHTLY , framework::dataset::combine(framework::dataset::combine(datasets::VGG16ConvolutionLayerDataset(), data_types), framework::dataset::make("Batches",{1, 2})))
arm_compute::test::REGISTER_FIXTURE_DATA_TEST_CASE (GoogLeNetInceptionV1FullyConnectedLayer , GCFullyConnectedLayerFixture , framework::DatasetMode::NIGHTLY , framework::dataset::combine(framework::dataset::combine(datasets::GoogLeNetInceptionV1FullyConnectedLayerDataset(), data_types), framework::dataset::make("Batches",{4, 8})))
arm_compute::test::REGISTER_FIXTURE_DATA_TEST_CASE (GoogLeNetInceptionV1FullyConnectedLayer , CLFullyConnectedLayerFixture , framework::DatasetMode::NIGHTLY , framework::dataset::combine(framework::dataset::combine(datasets::GoogLeNetInceptionV1FullyConnectedLayerDataset(), data_types), framework::dataset::make("Batches",{4, 8})))
arm_compute::test::REGISTER_FIXTURE_DATA_TEST_CASE (AlexNetActivationLayer , NEActivationLayerFixture , framework::DatasetMode::NIGHTLY , framework::dataset::combine(framework::dataset::combine(datasets::AlexNetActivationLayerDataset(), data_types), framework::dataset::make("Batches",{4, 8})))
arm_compute::test::REGISTER_FIXTURE_DATA_TEST_CASE (SqueezeNetConvolutionLayer , NEConvolutionLayerFixture , framework::DatasetMode::ALL , framework::dataset::combine(framework::dataset::combine(datasets::SqueezeNetConvolutionLayerDataset(), data_types), framework::dataset::make("Batches", 1)))
arm_compute::test::REGISTER_FIXTURE_DATA_TEST_CASE (VGG16DirectConvolutionLayer , CLConvolutionLayerFixture , framework::DatasetMode::NIGHTLY , framework::dataset::combine(framework::dataset::combine(datasets::VGG16ConvolutionLayerDataset(), data_types), framework::dataset::make("Batches",{1, 4, 8})))
arm_compute::test::REGISTER_FIXTURE_DATA_TEST_CASE (VGG16DirectConvolutionLayer , GCConvolutionLayerFixture , framework::DatasetMode::NIGHTLY , framework::dataset::combine(framework::dataset::combine(datasets::VGG16ConvolutionLayerDataset(), data_types), framework::dataset::make("Batches",{1, 4, 8})))
arm_compute::test::REGISTER_FIXTURE_DATA_TEST_CASE (VGG16PoolingLayer , NEPoolingLayerFixture , framework::DatasetMode::NIGHTLY , framework::dataset::combine(framework::dataset::combine(datasets::VGG16PoolingLayerDataset(), data_types), framework::dataset::make("Batches",{2})))
arm_compute::test::REGISTER_FIXTURE_DATA_TEST_CASE (LeNet5PoolingLayer , CLPoolingLayerFixture , framework::DatasetMode::NIGHTLY , framework::dataset::combine(framework::dataset::combine(datasets::LeNet5PoolingLayerDataset(), data_types), framework::dataset::make("Batches",{4, 8})))
arm_compute::test::REGISTER_FIXTURE_DATA_TEST_CASE (LeNet5PoolingLayer , GCPoolingLayerFixture , framework::DatasetMode::NIGHTLY , framework::dataset::combine(framework::dataset::combine(datasets::LeNet5PoolingLayerDataset(), data_types), framework::dataset::make("Batches",{4, 8})))
arm_compute::test::REGISTER_FIXTURE_DATA_TEST_CASE (GoogLeNetInceptionV4ConvolutionLayer , CLConvolutionLayerFixture , framework::DatasetMode::NIGHTLY , framework::dataset::combine(framework::dataset::combine(datasets::GoogLeNetInceptionV4ConvolutionLayerDataset(), data_types), framework::dataset::make("Batches",{4, 8})))
arm_compute::test::REGISTER_FIXTURE_DATA_TEST_CASE (GoogLeNetInceptionV4ConvolutionLayer , GCConvolutionLayerFixture , framework::DatasetMode::NIGHTLY , framework::dataset::combine(framework::dataset::combine(datasets::GoogLeNetInceptionV4ConvolutionLayerDataset(), data_types), framework::dataset::make("Batches",{4, 8})))
arm_compute::test::REGISTER_FIXTURE_DATA_TEST_CASE (YOLOV2DirectConvolutionLayer , NEConvolutionLayerFixture , framework::DatasetMode::NIGHTLY , framework::dataset::combine(framework::dataset::combine(datasets::YOLOV2ConvolutionLayerDataset(), data_types), framework::dataset::make("Batches",{1, 4, 8})))
arm_compute::test::REGISTER_FIXTURE_DATA_TEST_CASE (GoogLeNetInceptionV1FullyConnectedLayer , NEFullyConnectedLayerFixture , framework::DatasetMode::NIGHTLY , framework::dataset::combine(framework::dataset::combine(datasets::GoogLeNetInceptionV1FullyConnectedLayerDataset(), data_types), framework::dataset::make("Batches",{4, 8})))
arm_compute::test::REGISTER_FIXTURE_DATA_TEST_CASE (LeNet5ActivationLayer , NEActivationLayerFixture , framework::DatasetMode::NIGHTLY , framework::dataset::combine(framework::dataset::combine(datasets::LeNet5ActivationLayerDataset(), data_types), framework::dataset::make("Batches",{4, 8})))
arm_compute::test::REGISTER_FIXTURE_DATA_TEST_CASE (GoogLeNetInceptionV4FullyConnectedLayer , CLFullyConnectedLayerFixture , framework::DatasetMode::NIGHTLY , framework::dataset::combine(framework::dataset::combine(datasets::GoogLeNetInceptionV4FullyConnectedLayerDataset(), data_types), framework::dataset::make("Batches",{4, 8})))
arm_compute::test::REGISTER_FIXTURE_DATA_TEST_CASE (YOLOV2PoolingLayer , NEPoolingLayerFixture , framework::DatasetMode::NIGHTLY , framework::dataset::combine(framework::dataset::combine(datasets::YOLOV2PoolingLayerDataset(), data_types), framework::dataset::make("Batches",{4, 8})))
arm_compute::test::REGISTER_FIXTURE_DATA_TEST_CASE (GoogLeNetInceptionV4FullyConnectedLayer , GCFullyConnectedLayerFixture , framework::DatasetMode::NIGHTLY , framework::dataset::combine(framework::dataset::combine(datasets::GoogLeNetInceptionV4FullyConnectedLayerDataset(), data_types), framework::dataset::make("Batches",{4, 8})))
arm_compute::test::REGISTER_FIXTURE_DATA_TEST_CASE (AlexNetConvolutionLayer , NEConvolutionLayerFixture , framework::DatasetMode::NIGHTLY , framework::dataset::combine(framework::dataset::combine(datasets::AlexNetConvolutionLayerDataset(), data_types), framework::dataset::make("Batches",{4, 8})))
arm_compute::test::REGISTER_FIXTURE_DATA_TEST_CASE (YOLOV2DirectConvolutionLayer , GCConvolutionLayerFixture , framework::DatasetMode::NIGHTLY , framework::dataset::combine(framework::dataset::combine(datasets::YOLOV2ConvolutionLayerDataset(), data_types), framework::dataset::make("Batches",{1, 4, 8})))
arm_compute::test::REGISTER_FIXTURE_DATA_TEST_CASE (YOLOV2DirectConvolutionLayer , CLConvolutionLayerFixture , framework::DatasetMode::NIGHTLY , framework::dataset::combine(framework::dataset::combine(datasets::YOLOV2ConvolutionLayerDataset(), data_types), framework::dataset::make("Batches",{1, 4, 8})))
arm_compute::test::REGISTER_FIXTURE_DATA_TEST_CASE (GoogLeNetInceptionV1PoolingLayer , CLPoolingLayerFixture , framework::DatasetMode::NIGHTLY , framework::dataset::combine(framework::dataset::combine(datasets::GoogLeNetInceptionV1PoolingLayerDataset(), data_types), framework::dataset::make("Batches",{4, 8})))
arm_compute::test::REGISTER_FIXTURE_DATA_TEST_CASE (SqueezeNetConvolutionLayer , CLConvolutionLayerFixture , framework::DatasetMode::NIGHTLY , framework::dataset::combine(framework::dataset::combine(datasets::SqueezeNetConvolutionLayerDataset(), data_types), framework::dataset::make("Batches",{4, 8})))
arm_compute::test::REGISTER_FIXTURE_DATA_TEST_CASE (SqueezeNetConvolutionLayer , GCConvolutionLayerFixture , framework::DatasetMode::NIGHTLY , framework::dataset::combine(framework::dataset::combine(datasets::SqueezeNetConvolutionLayerDataset(), data_types), framework::dataset::make("Batches",{4, 8})))
arm_compute::test::REGISTER_FIXTURE_DATA_TEST_CASE (GoogLeNetInceptionV1PoolingLayer , GCPoolingLayerFixture , framework::DatasetMode::NIGHTLY , framework::dataset::combine(framework::dataset::combine(datasets::GoogLeNetInceptionV1PoolingLayerDataset(), data_types), framework::dataset::make("Batches",{4, 8})))
arm_compute::test::REGISTER_FIXTURE_DATA_TEST_CASE (MobileNetActivationLayer , NEActivationLayerFixture , framework::DatasetMode::NIGHTLY , framework::dataset::combine(framework::dataset::combine(datasets::MobileNetActivationLayerDataset(), data_types_mobilenet), framework::dataset::make("Batches",{4, 8})))
arm_compute::test::REGISTER_FIXTURE_DATA_TEST_CASE (GoogLeNetInceptionV4FullyConnectedLayer , NEFullyConnectedLayerFixture , framework::DatasetMode::NIGHTLY , framework::dataset::combine(framework::dataset::combine(datasets::GoogLeNetInceptionV4FullyConnectedLayerDataset(), data_types), framework::dataset::make("Batches",{4, 8})))
arm_compute::test::REGISTER_FIXTURE_DATA_TEST_CASE (LeNet5ConvolutionLayer , NEConvolutionLayerFixture , framework::DatasetMode::NIGHTLY , framework::dataset::combine(framework::dataset::combine(datasets::LeNet5ConvolutionLayerDataset(), data_types), framework::dataset::make("Batches",{4, 8})))
arm_compute::test::REGISTER_FIXTURE_DATA_TEST_CASE (GoogLeNetInceptionV4PoolingLayer , GCPoolingLayerFixture , framework::DatasetMode::NIGHTLY , framework::dataset::combine(framework::dataset::combine(datasets::GoogLeNetInceptionV4PoolingLayerDataset(), data_types), framework::dataset::make("Batches",{4, 8})))
arm_compute::test::REGISTER_FIXTURE_DATA_TEST_CASE (GoogLeNetInceptionV4PoolingLayer , CLPoolingLayerFixture , framework::DatasetMode::NIGHTLY , framework::dataset::combine(framework::dataset::combine(datasets::GoogLeNetInceptionV4PoolingLayerDataset(), data_types), framework::dataset::make("Batches",{4, 8})))
arm_compute::test::REGISTER_FIXTURE_DATA_TEST_CASE (GoogLeNetInceptionV1ActivationLayer , NEActivationLayerFixture , framework::DatasetMode::NIGHTLY , framework::dataset::combine(framework::dataset::combine(datasets::GoogLeNetInceptionV1ActivationLayerDataset(), data_types), framework::dataset::make("Batches",{4, 8})))
arm_compute::test::REGISTER_FIXTURE_DATA_TEST_CASE (VGG16ConvolutionLayer , CLConvolutionLayerFixture , framework::DatasetMode::NIGHTLY , framework::dataset::combine(framework::dataset::combine(datasets::VGG16ConvolutionLayerDataset(), data_types), framework::dataset::make("Batches",{1, 4})))
arm_compute::test::REGISTER_FIXTURE_DATA_TEST_CASE (VGG16ConvolutionLayer , GCConvolutionLayerFixture , framework::DatasetMode::NIGHTLY , framework::dataset::combine(framework::dataset::combine(datasets::VGG16ConvolutionLayerDataset(), data_types), framework::dataset::make("Batches",{1, 4})))
arm_compute::test::REGISTER_FIXTURE_DATA_TEST_CASE (GoogLeNetInceptionV1ConvolutionLayer , NEConvolutionLayerFixture , framework::DatasetMode::NIGHTLY , framework::dataset::combine(framework::dataset::combine(datasets::GoogLeNetInceptionV1ConvolutionLayerDataset(), data_types), framework::dataset::make("Batches",{4, 8})))
arm_compute::test::REGISTER_FIXTURE_DATA_TEST_CASE (GoogLeNetInceptionV4ActivationLayer , NEActivationLayerFixture , framework::DatasetMode::NIGHTLY , framework::dataset::combine(framework::dataset::combine(datasets::GoogLeNetInceptionV4ActivationLayerDataset(), data_types), framework::dataset::make("Batches",{4, 8})))
arm_compute::test::REGISTER_FIXTURE_DATA_TEST_CASE (SqueezeNetPoolingLayer , CLPoolingLayerFixture , framework::DatasetMode::NIGHTLY , framework::dataset::combine(framework::dataset::combine(datasets::SqueezeNetPoolingLayerDataset(), data_types), framework::dataset::make("Batches",{4, 8})))
arm_compute::test::REGISTER_FIXTURE_DATA_TEST_CASE (SqueezeNetPoolingLayer , GCPoolingLayerFixture , framework::DatasetMode::NIGHTLY , framework::dataset::combine(framework::dataset::combine(datasets::SqueezeNetPoolingLayerDataset(), data_types), framework::dataset::make("Batches",{4, 8})))
arm_compute::test::REGISTER_FIXTURE_DATA_TEST_CASE (YOLOV2ConvolutionLayer , GCConvolutionLayerFixture , framework::DatasetMode::NIGHTLY , framework::dataset::combine(framework::dataset::combine(datasets::YOLOV2ConvolutionLayerDataset(), data_types), framework::dataset::make("Batches",{1, 4, 8})))
arm_compute::test::REGISTER_FIXTURE_DATA_TEST_CASE (GoogLeNetInceptionV4ConvolutionLayer , NEConvolutionLayerFixture , framework::DatasetMode::NIGHTLY , framework::dataset::combine(framework::dataset::combine(datasets::GoogLeNetInceptionV4ConvolutionLayerDataset(), data_types), framework::dataset::make("Batches",{4, 8})))
arm_compute::test::REGISTER_FIXTURE_DATA_TEST_CASE (YOLOV2ConvolutionLayer , CLConvolutionLayerFixture , framework::DatasetMode::NIGHTLY , framework::dataset::combine(framework::dataset::combine(datasets::YOLOV2ConvolutionLayerDataset(), data_types), framework::dataset::make("Batches",{1, 4, 8})))
arm_compute::test::REGISTER_FIXTURE_DATA_TEST_CASE (SqueezeNetActivationLayer , NEActivationLayerFixture , framework::DatasetMode::NIGHTLY , framework::dataset::combine(framework::dataset::combine(datasets::SqueezeNetActivationLayerDataset(), data_types), framework::dataset::make("Batches",{4, 8})))
arm_compute::test::REGISTER_FIXTURE_DATA_TEST_CASE (SqueezeNetConvolutionLayer , NEConvolutionLayerFixture , framework::DatasetMode::NIGHTLY , framework::dataset::combine(framework::dataset::combine(datasets::SqueezeNetConvolutionLayerDataset(), data_types), framework::dataset::make("Batches",{4, 8})))
arm_compute::test::REGISTER_FIXTURE_DATA_TEST_CASE (VGG16PoolingLayer , CLPoolingLayerFixture , framework::DatasetMode::NIGHTLY , framework::dataset::combine(framework::dataset::combine(datasets::VGG16PoolingLayerDataset(), data_types), framework::dataset::make("Batches",{4, 8})))
arm_compute::test::REGISTER_FIXTURE_DATA_TEST_CASE (VGG16PoolingLayer , GCPoolingLayerFixture , framework::DatasetMode::NIGHTLY , framework::dataset::combine(framework::dataset::combine(datasets::VGG16PoolingLayerDataset(), data_types), framework::dataset::make("Batches",{4, 8})))
arm_compute::test::REGISTER_FIXTURE_DATA_TEST_CASE (VGG16ActivationLayer , NEActivationLayerFixture , framework::DatasetMode::NIGHTLY , framework::dataset::combine(framework::dataset::combine(datasets::VGG16ActivationLayerDataset(), data_types), framework::dataset::make("Batches",{2})))
arm_compute::test::REGISTER_FIXTURE_DATA_TEST_CASE (YOLOV2PoolingLayer , CLPoolingLayerFixture , framework::DatasetMode::NIGHTLY , framework::dataset::combine(framework::dataset::combine(datasets::YOLOV2PoolingLayerDataset(), data_types), framework::dataset::make("Batches",{4, 8})))
arm_compute::test::REGISTER_FIXTURE_DATA_TEST_CASE (YOLOV2PoolingLayer , GCPoolingLayerFixture , framework::DatasetMode::NIGHTLY , framework::dataset::combine(framework::dataset::combine(datasets::YOLOV2PoolingLayerDataset(), data_types), framework::dataset::make("Batches",{4, 8})))
arm_compute::test::REGISTER_FIXTURE_DATA_TEST_CASE (VGG16ConvolutionLayer , NEConvolutionLayerFixture , framework::DatasetMode::NIGHTLY , framework::dataset::combine(framework::dataset::combine(datasets::VGG16ConvolutionLayerDataset(), data_types), framework::dataset::make("Batches",{1, 2})))
arm_compute::test::REGISTER_FIXTURE_DATA_TEST_CASE (YOLOV2ActivationLayer , NEActivationLayerFixture , framework::DatasetMode::NIGHTLY , framework::dataset::combine(framework::dataset::combine(datasets::YOLOV2ActivationLayerDataset(), data_types), framework::dataset::make("Batches",{4, 8})))
arm_compute::test::REGISTER_FIXTURE_DATA_TEST_CASE (YOLOV2ConvolutionLayer , NEConvolutionLayerFixture , framework::DatasetMode::NIGHTLY , framework::dataset::combine(framework::dataset::combine(datasets::YOLOV2ConvolutionLayerDataset(), data_types), framework::dataset::make("Batches",{1, 4, 8})))
T arm_compute::test::round_half_even (T value, T epsilon = std::numeric_limits<T>::epsilon()) inline
Round floating-point value with half value rounding to nearest even.
Parameters
[in] value floating-point value to be rounded.
[in] epsilon precision.
Returns
Floating-point value of rounded value.
Definition at line 84 of file Utils.h.
References arm_compute::test::fixed_point_arithmetic::detail::abs(), arm_compute::support::cpp11::copysign(), and arm_compute::support::cpp11::round().
Referenced by DATA_TEST_CASE(), and arm_compute::test::validation::reference::pixel_wise_multiplication().
 {
     T positive_value = std::abs(value);
     T ipart          = 0;
     std::modf(positive_value, &ipart);
     // If 'value' is exactly halfway between two integers
     if(std::abs(positive_value - (ipart + 0.5f)) < epsilon)
     {
         // If 'ipart' is even then return 'ipart'
         if(std::fmod(ipart, 2.f) < epsilon)
         {
             return support::cpp11::copysign(ipart, value);
         }
         // Else return the nearest even integer
         return support::cpp11::copysign(std::ceil(ipart + 0.5f), value);
     }
     // Otherwise use the usual round to closest
     return support::cpp11::copysign(support::cpp11::round(positive_value), value);
 }
T arm_compute::test::round_half_up (T value) inline
Round floating-point value with half value rounding to positive infinity.
Parameters
[in] value floating-point value to be rounded.
Returns
Floating-point value of rounded value.
Definition at line 71 of file Utils.h.
References caffe_data_extractor::type, and value.
Referenced by DATA_TEST_CASE(), and arm_compute::test::validation::reference::pixel_wise_multiplication().
 {
     return std::floor(value + 0.5f);
 }
T arm_compute::test::saturate_cast (T val)
Saturate a value of type T against the numeric limits of type U.
Parameters
[in] val Value to be saturated.
Returns
saturated value.
Definition at line 363 of file Utils.h.
References arm_compute::test::fixed_point_arithmetic::detail::max().
Referenced by arm_compute::test::validation::reference::absolute_difference(), arm_compute::test::validation::reference::accumulate(), arm_compute::test::validation::reference::accumulate_squared(), arm_compute::test::validation::reference::depthwise_convolution(), arm_compute::test::validation::reference::magnitude(), arm_compute::test::validation::reference::non_linear_filter(), and constant_expr< T >::to_fixed().
 {
     if(val > static_cast<T>(std::numeric_limits<U>::max()))
     {
         val = static_cast<T>(std::numeric_limits<U>::max());
     }
     if(val < static_cast<T>(std::numeric_limits<U>::lowest()))
     {
         val = static_cast<T>(std::numeric_limits<U>::lowest());
     }
     return val;
 }
ValidRegion arm_compute::test::shape_to_valid_region (const TensorShape & a_shape, bool border_undefined = false, BorderSize border_size = BorderSize(0)) inline
Create a valid region based on tensor shape, border mode and border size.
Parameters
[in] a_shape Shape used as size of the valid region.
[in] border_undefined (Optional) Boolean indicating if the border mode is undefined.
[in] border_size (Optional) Border size used to specify the region to exclude.
Returns
A valid region starting at (0, 0, ...) with size of shape if border_undefined is false; otherwise return A valid region starting at (border_size.left, border_size.top, ...) with reduced size of shape.
Definition at line 212 of file Utils.h.
References ARM_COMPUTE_ERROR_ON, arm_compute::test::fixed_point_arithmetic::detail::max(), Dimensions< T >::num_dimensions(), TensorShape::set(), Dimensions< T >::set(), arm_compute::test::validation::shape, Dimensions< T >::x(), and Dimensions< T >::y().
Referenced by arm_compute::test::validation::DATA_TEST_CASE(), arm_compute::test::validation::reference::derivative(), arm_compute::test::validation::FIXTURE_DATA_TEST_CASE(), arm_compute::test::validation::reference::non_linear_filter(), arm_compute::test::validation::reference::non_maxima_suppression(), arm_compute::test::validation::reference::scharr(), arm_compute::test::validation::reference::sobel(), arm_compute::test::validation::validate(), and arm_compute::test::validation::validate_wrap().
 {
     ValidRegion valid_region{ Coordinates(), a_shape };
     Coordinates &anchor = valid_region.anchor;
     TensorShape &shape  = valid_region.shape;
     if(border_undefined)
     {
         ARM_COMPUTE_ERROR_ON(shape.num_dimensions() < 2);
         anchor.set(0, border_size.left);
         anchor.set(1, border_size.top);
         const int valid_shape_x = std::max(0, static_cast<int>(shape.x()) - static_cast<int>(border_size.left) - static_cast<int>(border_size.right));
         const int valid_shape_y = std::max(0, static_cast<int>(shape.y()) - static_cast<int>(border_size.top) - static_cast<int>(border_size.bottom));
         shape.set(0, valid_shape_x);
         shape.set(1, valid_shape_y);
     }
     return valid_region;
 }
ValidRegion arm_compute::test::shape_to_valid_region_gaussian_pyramid_half (const TensorShape & a_shape, const ValidRegion & a_valid_region, bool border_undefined = false) inline
Create a valid region for Gaussian Pyramid Half based on tensor shape and valid region at level "i - 1" and border mode.
Note
The border size is 2 in case of Gaussian Pyramid Half
Parameters
[in] a_shape Shape used at level "i - 1" of Gaussian Pyramid Half
[in] a_valid_region Valid region used at level "i - 1" of Gaussian Pyramid Half
[in] border_undefined (Optional) Boolean indicating if the border mode is undefined.
return The valid region for the level "i" of Gaussian Pyramid Half
Definition at line 246 of file Utils.h.
References ValidRegion::anchor, ARM_COMPUTE_ERROR_ON, arm_compute::test::fixed_point_arithmetic::detail::max(), Dimensions< T >::num_dimensions(), Dimensions< T >::set(), TensorShape::set(), arm_compute::test::validation::shape, ValidRegion::shape, Dimensions< T >::x(), and Dimensions< T >::y().
 {
     constexpr int border_size = 2;
     ValidRegion valid_region{ Coordinates(), a_shape };
     Coordinates &anchor = valid_region.anchor;
     TensorShape &shape  = valid_region.shape;
     // Compute tensor shape for level "i" of Gaussian Pyramid Half
     // dst_width  = (src_width + 1) * 0.5f
     // dst_height = (src_height + 1) * 0.5f
     shape.set(0, (shape[0] + 1) * 0.5f);
     shape.set(1, (shape[1] + 1) * 0.5f);
     if(border_undefined)
     {
         ARM_COMPUTE_ERROR_ON(shape.num_dimensions() < 2);
         // Compute the left and top invalid borders
         float invalid_border_left = static_cast<float>(a_valid_region.anchor.x() + border_size) / 2.0f;
         float invalid_border_top  = static_cast<float>(a_valid_region.anchor.y() + border_size) / 2.0f;
         // For the new anchor point we can have 2 cases:
         // 1) If the width/height of the tensor shape is odd, we have to take the ceil value of (a_valid_region.anchor.x() + border_size) / 2.0f or (a_valid_region.anchor.y() + border_size / 2.0f
         // 2) If the width/height of the tensor shape is even, we have to take the floor value of (a_valid_region.anchor.x() + border_size) / 2.0f or (a_valid_region.anchor.y() + border_size) / 2.0f
         // In this manner we should be able to propagate correctly the valid region along all levels of the pyramid
         invalid_border_left = (shape[0] % 2) ? std::ceil(invalid_border_left) : std::floor(invalid_border_left);
         invalid_border_top  = (shape[1] % 2) ? std::ceil(invalid_border_top) : std::floor(invalid_border_top);
         // Set the anchor point
         anchor.set(0, static_cast<int>(invalid_border_left));
         anchor.set(1, static_cast<int>(invalid_border_top));
         // Compute shape
         // Calculate the right and bottom invalid borders at the previous level of the pyramid
         const float prev_invalid_border_right  = static_cast<float>(shape[0] - (a_valid_region.anchor.x() + a_valid_region.shape[0]));
         const float prev_invalid_border_bottom = static_cast<float>(shape[1] - (a_valid_region.anchor.y() + a_valid_region.shape[1]));
         // Calculate the right and bottom invalid borders at the current level of the pyramid
         const float invalid_border_right  = std::ceil((prev_invalid_border_right + static_cast<float>(border_size)) / 2.0f);
         const float invalid_border_bottom = std::ceil((prev_invalid_border_bottom + static_cast<float>(border_size)) / 2.0f);
         const int valid_shape_x = std::max(0, static_cast<int>(shape.x()) - static_cast<int>(invalid_border_left) - static_cast<int>(invalid_border_right));
         const int valid_shape_y = std::max(0, static_cast<int>(shape.y()) - static_cast<int>(invalid_border_top) - static_cast<int>(invalid_border_bottom));
         shape.set(0, valid_shape_x);
         shape.set(1, valid_shape_y);
     }
     return valid_region;
 }
void arm_compute::test::store_value_with_data_type (void * ptr, T value, DataType data_type)
Write the value after casting the pointer according to data_type.
Warning
The type of the value must match the specified data type.
Parameters
[out] ptr Pointer to memory where the value will be written.
[in] value Value that will be written.
[in] data_type Data type that will be written.
Definition at line 308 of file Utils.h.
References ARM_COMPUTE_ERROR, arm_compute::F16, arm_compute::F32, arm_compute::F64, arm_compute::QASYMM8, arm_compute::QS16, arm_compute::QS8, arm_compute::S16, arm_compute::S32, arm_compute::S64, arm_compute::S8, arm_compute::SIZET, arm_compute::U16, arm_compute::U32, arm_compute::U64, and arm_compute::U8.
Referenced by AssetsLibrary::fill(), and AssetsLibrary::fill_borders_with_garbage().
 {
     switch(data_type)
     {
         case DataType::U8:
         case DataType::QASYMM8:
             *reinterpret_cast<uint8_t *>(ptr) = value;
             break;
         case DataType::S8:
         case DataType::QS8:
             *reinterpret_cast<int8_t *>(ptr) = value;
             break;
         case DataType::U16:
             *reinterpret_cast<uint16_t *>(ptr) = value;
             break;
         case DataType::S16:
         case DataType::QS16:
             *reinterpret_cast<int16_t *>(ptr) = value;
             break;
         case DataType::U32:
             *reinterpret_cast<uint32_t *>(ptr) = value;
             break;
         case DataType::S32:
             *reinterpret_cast<int32_t *>(ptr) = value;
             break;
         case DataType::U64:
             *reinterpret_cast<uint64_t *>(ptr) = value;
             break;
         case DataType::S64:
             *reinterpret_cast<int64_t *>(ptr) = value;
             break;
         case DataType::F16:
             *reinterpret_cast<half *>(ptr) = value;
             break;
         case DataType::F32:
             *reinterpret_cast<float *>(ptr) = value;
             break;
         case DataType::F64:
             *reinterpret_cast<double *>(ptr) = value;
             break;
         case DataType::SIZET:
             *reinterpret_cast<size_t *>(ptr) = value;
             break;
         default:
             ARM_COMPUTE_ERROR("NOT SUPPORTED!");
     }
 }
void arm_compute::test::swap (SimpleTensor< U > & tensor1, SimpleTensor< U > & tensor2)
Parameters
[in,out] tensor1 Tensor to be swapped.
[in,out] tensor2 Tensor to be swapped.
Definition at line 352 of file SimpleTensor.h.
References SimpleTensor< T >::swap.
 {
     // Use unqualified call to swap to enable ADL. But make std::swap available
     // as backup.
     using std::swap;
     swap(tensor1._shape, tensor2._shape);
     swap(tensor1._format, tensor2._format);
     swap(tensor1._data_type, tensor2._data_type);
     swap(tensor1._num_channels, tensor2._num_channels);
     swap(tensor1._buffer, tensor2._buffer);
 }
void arm_compute::test::sync_if_necessary () inline
Sync if necessary.
Definition at line 634 of file Utils.h.
References CLScheduler::get(), arm_compute::opencl_is_available(), CLScheduler::sync(), and caffe_data_extractor::type.
 {
 #ifdef ARM_COMPUTE_CL
     if(opencl_is_available() && std::is_same<typename std::decay<TensorType>::type, arm_compute::CLTensor>::value)
     {
         CLScheduler::get().sync();
     }
 #endif /* ARM_COMPUTE_CL */
 }
void arm_compute::test::sync_tensor_if_necessary (TensorType & tensor) inline
Sync tensor if necessary.
Note
: If the destination tensor not being used on OpenGL ES, GPU will optimize out the operation.
Parameters
[in] tensor Tensor to be sync.
Definition at line 651 of file Utils.h.
References IGCTensor::map(), arm_compute::opengles31_is_available(), caffe_data_extractor::type, and IGCTensor::unmap().
 {
 #ifdef ARM_COMPUTE_GC
     if(opengles31_is_available() && std::is_same<typename std::decay<TensorType>::type, arm_compute::GCTensor>::value)
     {
         // Force sync the tensor by calling map and unmap.
         IGCTensor &t = dynamic_cast<IGCTensor &>(tensor);
         t.map();
         t.unmap();
     }
 #endif /* ARM_COMPUTE_GC */
 }
std::string arm_compute::test::tolower (std::string string) inline
Convert string to lower case.
Parameters
[in] string To be converted string.
Returns
Lower case string.
Definition at line 147 of file Utils.h.
References arm_compute::test::validation::c, and value.
Referenced by arm_compute::test::validation::DATA_TEST_CASE(), arm_compute::test::framework::dataset_mode_from_name(), arm_compute::test::framework::instrument_type_from_name(), arm_compute::test::framework::log_format_from_name(), arm_compute::test::framework::log_level_from_name(), and CommandLineParser::parse().
 {
     std::transform(string.begin(), string.end(), string.begin(), [](unsigned char c)
     {
         return std::tolower(c);
     });
     return string;
 }
Variable Documentation
const auto data_types = framework::dataset::make("DataType", { DataType::F32, DataType::QASYMM8 })
Definition at line 40 of file DepthwiseConvolutionLayer.cpp.
std::unique_ptr< AssetsLibrary > library
Definition at line 59 of file main.cpp.
Referenced by arm_compute::test::validation::reference::accumulate(), arm_compute::test::validation::reference::accumulate_squared(), arm_compute::test::validation::reference::accumulate_weighted(), arm_compute::test::gles_compute::create_tensor(), arm_compute::test::validation::DATA_TEST_CASE(), LeNet5Network< TensorType, arm_compute::test::Accessor, ActivationLayerFunction, ConvolutionLayerFunction, FullyConnectedLayerFunction, PoolingLayerFunction, SoftmaxLayerFunction >::feed(), MobileNetNetwork< TensorType, arm_compute::test::Accessor, ActivationLayerFunction, ConvolutionLayerFunction, DirectConvolutionLayerFunction, DepthwiseConvolutionLayerFunction, ReshapeFunction, PoolingLayerFunction >::feed(), MobileNetV1Network< TensorType, arm_compute::test::Accessor, ActivationLayerFunction, BatchNormalizationLayerFunction, ConvolutionLayerFunction, DirectConvolutionLayerFunction, DepthwiseConvolutionFunction, ReshapeFunction, PoolingLayerFunction, SoftmaxLayerFunction >::feed(), AlexNetNetwork< ITensorType, TensorType, SubTensorType, arm_compute::test::Accessor, ActivationLayerFunction, ConvolutionLayerFunction, DirectConvolutionLayerFunction, FullyConnectedLayerFunction, NormalizationLayerFunction, PoolingLayerFunction, SoftmaxLayerFunction >::feed(), LeNet5Network< TensorType, arm_compute::test::Accessor, ActivationLayerFunction, ConvolutionLayerFunction, FullyConnectedLayerFunction, PoolingLayerFunction, SoftmaxLayerFunction >::fill(), AlexNetNetwork< ITensorType, TensorType, SubTensorType, arm_compute::test::Accessor, ActivationLayerFunction, ConvolutionLayerFunction, DirectConvolutionLayerFunction, FullyConnectedLayerFunction, NormalizationLayerFunction, PoolingLayerFunction, SoftmaxLayerFunction >::fill(), arm_compute::test::validation::fill_lookuptable(), arm_compute::test::validation::fill_mask_from_pattern(), LeNet5Network< TensorType, arm_compute::test::Accessor, ActivationLayerFunction, ConvolutionLayerFunction, FullyConnectedLayerFunction, PoolingLayerFunction, SoftmaxLayerFunction >::fill_random(), MobileNetNetwork< TensorType, arm_compute::test::Accessor, ActivationLayerFunction, ConvolutionLayerFunction, DirectConvolutionLayerFunction, DepthwiseConvolutionLayerFunction, ReshapeFunction, PoolingLayerFunction >::fill_random(), MobileNetV1Network< TensorType, arm_compute::test::Accessor, ActivationLayerFunction, BatchNormalizationLayerFunction, ConvolutionLayerFunction, DirectConvolutionLayerFunction, DepthwiseConvolutionFunction, ReshapeFunction, PoolingLayerFunction, SoftmaxLayerFunction >::fill_random(), AlexNetNetwork< ITensorType, TensorType, SubTensorType, arm_compute::test::Accessor, ActivationLayerFunction, ConvolutionLayerFunction, DirectConvolutionLayerFunction, FullyConnectedLayerFunction, NormalizationLayerFunction, PoolingLayerFunction, SoftmaxLayerFunction >::fill_random(), fill_tensors(), arm_compute::test::validation::fill_warp_matrix(), arm_compute::test::validation::FIXTURE_DATA_TEST_CASE(), DepthConcatenateLayerFixture< TensorType, ITensorType, Function, AccessorType >::generate_input_shapes(), arm_compute::test::validation::harris_corners_parameters(), main(), MeanStdDevValidationFixture< TensorType, AccessorType, FunctionType, T >::setup(), HarrisCornersFixture< TensorType, Function, Accessor, ArrayType >::setup(), ScaleFixture< TensorType, Function, Accessor >::setup(), ScaleLayerFixture< TensorType, Function, Accessor, T >::setup(), ThresholdValidationFixture< TensorType, AccessorType, FunctionType, T >::setup(), PhaseValidationFixture< TensorType, AccessorType, FunctionType, T >::setup(), MagnitudeValidationFixture< TensorType, AccessorType, FunctionType, T >::setup(), DerivativeValidationFixture< TensorType, AccessorType, FunctionType, T, U >::setup(), FixedPointPixelWiseMultiplicationValidationFixture< TensorType, AccessorType, FunctionType, T >::setup(), IntegralImageValidationFixture< TensorType, AccessorType, FunctionType, T >::setup(), PixelWiseMultiplicationValidationFixture< TensorType, AccessorType, FunctionType, T1, T2 >::setup(), BitwiseAndValidationFixture< TensorType, AccessorType, FunctionType, T >::setup(), ReshapeLayerValidationFixture< TensorType, AccessorType, FunctionType, T >::setup(), BitwiseNotValidationFixture< TensorType, AccessorType, FunctionType, T >::setup(), BitwiseOrValidationFixture< TensorType, AccessorType, FunctionType, T >::setup(), BitwiseXorValidationFixture< TensorType, AccessorType, FunctionType, T >::setup(), ScaleValidationFixture< TensorType, AccessorType, FunctionType, T >::setup(), DeconvolutionLayerFixtureBase< TensorType, AccessorType, FunctionType, T >::setup(), NonLinearFilterValidationFixture< TensorType, AccessorType, FunctionType, T >::setup(), FixedPointValidationFixture< TensorType, AccessorType, T >::setup(), TransposeValidationFixture< TensorType, AccessorType, FunctionType, T >::setup(), HOGDescriptorValidationFixture< TensorType, HOGType, AccessorType, FunctionType, T, U >::setup(), L2NormalizeLayerValidationFixture< TensorType, AccessorType, FunctionType, T >::setup(), BatchNormalizationLayerValidationFixedPointFixture< TensorType, AccessorType, FunctionType, T >::setup(), FloorValidationFixture< TensorType, AccessorType, FunctionType, T >::setup(), NormalizePlanarYUVLayerValidationFixedPointFixture< TensorType, AccessorType, FunctionType, T >::setup(), AbsoluteDifferenceValidationFixture< TensorType, AccessorType, FunctionType, T >::setup(), AccumulateBaseValidationFixture< TensorType, AccessorType, FunctionType, T1, T2 >::setup(), ArithmeticAdditionValidationFixedPointFixture< TensorType, AccessorType, FunctionType, T >::setup(), ReductionOperationValidationFixture< TensorType, AccessorType, FunctionType, T >::setup(), ArithmeticSubtractionValidationFixedPointFixture< TensorType, AccessorType, FunctionType, T1, T2, T3 >::setup(), DepthConvertLayerValidationFixedPointFixture< TensorType, AccessorType, FunctionType, T1, T2 >::setup(), DilateValidationFixture< TensorType, AccessorType, FunctionType, T >::setup(), ErodeValidationFixture< TensorType, AccessorType, FunctionType, T >::setup(), Gaussian5x5ValidationFixture< TensorType, AccessorType, FunctionType, T >::setup(), GaussianPyramidHalfValidationFixture< TensorType, AccessorType, FunctionType, T, PyramidType >::setup(), Gaussian3x3ValidationFixture< TensorType, AccessorType, FunctionType, T >::setup(), Median3x3ValidationFixture< TensorType, AccessorType, FunctionType, T >::setup(), PermuteValidationFixture< TensorType, AccessorType, FunctionType, T >::setup(), RemapValidationFixture< TensorType, AccessorType, FunctionType, T >::setup(), TableLookupValidationFixture< TensorType, AccessorType, FunctionType, LutAccessorType, LutType, T >::setup(), MinMaxLocationValidationFixture< TensorType, AccessorType, ArrayType, ArrayAccessorType, FunctionType, T >::setup(), Box3x3ValidationFixture< TensorType, AccessorType, FunctionType, T >::setup(), GEMMLowpAssemblyFixture< TensorType, AccessorType, FunctionType, T2 >::setup(), ActivationValidationGenericFixture< TensorType, AccessorType, FunctionType, T >::setup(), GEMMInterleave4x4ValidationFixedPointFixture< TensorType, AccessorType, FunctionType, T >::setup(), QuantizationValidationFixedPointFixture< TensorType, AccessorType, FunctionType, T >::setup(), DepthConcatenateLayerValidationFixture< TensorType, ITensorType, AccessorType, FunctionType, T >::setup(), HistogramValidationFixture< TensorType, AccessorType, FunctionType, T, DistributionType >::setup(), GEMMInterleaveBlockedValidationFixture< TensorType, AccessorType, FunctionType, Transposed >::setup(), PoolingLayerValidationGenericFixture< TensorType, AccessorType, FunctionType, T >::setup(), SoftmaxValidationGenericFixture< TensorType, AccessorType, FunctionType, T >::setup(), DropoutLayerValidationFixture< TensorType, AccessorType, FunctionType, T >::setup(), GEMMTranspose1xWValidationFixedPointFixture< TensorType, AccessorType, FunctionType, T >::setup(), DepthwiseSeparableConvolutionValidationFixture< TensorType, AccessorType, FunctionType, T >::setup(), WarpAffineValidationFixture< TensorType, AccessorType, FunctionType, T >::setup(), DequantizationValidationFixedPointFixture< TensorType, AccessorType, FunctionType, T >::setup(), HarrisCornersValidationFixture< TensorType, AccessorType, ArrayType, FunctionType, T >::setup(), NormalizationValidationFixedPointFixture< TensorType, AccessorType, FunctionType, T >::setup(), GEMMLowpMatrixMultiplyCoreValidationFixture< TensorType, AccessorType, FunctionType >::setup(), GEMMValidationFixedPointFixture< TensorType, AccessorType, FunctionType, T >::setup(), WarpPerspectiveValidationFixture< TensorType, AccessorType, FunctionType, T >::setup(), FlattenLayerValidationFixture< TensorType, AccessorType, FunctionType, T >::setup(), WinogradLayerValidationFixture< TensorType, AccessorType, FunctionType, T >::setup(), DepthwiseConvolutionLayerValidationGenericFixture< TensorType, AccessorType, FunctionType, T >::setup(), FullyConnectedLayerValidationGenericFixture< TensorType, AccessorType, FunctionType, T, run_interleave >::setup(), ConvolutionValidationGenericFixture< TensorType, AccessorType, FunctionType, T >::setup(), DirectConvolutionValidationGenericFixture< TensorType, AccessorType, FunctionType, T >::setup(), ScharrValidationFixture< TensorType, AccessorType, FunctionType, T, U >::setup(), SobelValidationFixture< TensorType, AccessorType, FunctionType, T, U >::setup(), GEMMLowpQuantizeDownInt32ToUint8ScaleValidationFixture< TensorType, AccessorType, FunctionType >::setup(), AccumulateWeightedValidationFixture< TensorType, AccessorType, FunctionType, T1, T2 >::setup(), AccumulateSquaredValidationFixture< TensorType, AccessorType, FunctionType, T1, T2 >::setup(), GEMMLowpQuantizeDownInt32ToUint8ScaleByFixedPointValidationFixture< TensorType, AccessorType, FunctionType >::setup(), and arm_compute::test::validation::TEST_CASE().