Compute Library: arm_compute::test::neon Namespace Reference
arm_compute::test::neon Namespace Reference
Data Structures
class NEAccessor
Accessor implementation for Tensor objects.
Functions
Tensor create_tensor (const TensorShape &shape, DataType data_type, int num_channels=1, int fixed_point_position=0)
Helper to create an empty tensor.
Tensor create_tensor (const std::string &name, DataType data_type, int fixed_point_position=0)
Helper to create an empty tensor.
Function Documentation
Tensor arm_compute::test::neon::create_tensor (const TensorShape & shape, DataType data_type, int num_channels = 1, int fixed_point_position = 0) inline
Helper to create an empty tensor.
Parameters
[in] shape Desired shape.
[in] data_type Desired data type.
[in] num_channels (Optional) It indicates the number of channels for each tensor element
[in] fixed_point_position (Optional) Fixed point position that expresses the number of bits for the fractional part of the number when the tensor's data type is QS8 or QS16.
Returns
Empty Tensor with the specified shape and data type.
Definition at line 47 of file Helper.h.
References Tensor::allocator(), and TensorAllocator::init().
 {
     Tensor tensor;
     tensor.allocator()->init(TensorInfo(shape, num_channels, data_type, fixed_point_position));
     return tensor;
 }
Tensor arm_compute::test::neon::create_tensor (const std::string & name, DataType data_type, int fixed_point_position = 0) inline
Helper to create an empty tensor.
Parameters
[in] name File name from which to get the dimensions.
[in] data_type Desired data type.
[in] fixed_point_position (Optional) Number of bits for the fractional part of the fixed point numbers
Returns
Empty Tensor with the specified shape and data type.
Definition at line 63 of file Helper.h.
References Tensor::allocator(), TensorAllocator::init(), arm_compute::test::library, and RawTensor::shape().
 {
     constexpr unsigned int num_channels = 1;
     const RawTensor &raw = library->get(name);
     Tensor tensor;
     tensor.allocator()->init(TensorInfo(raw.shape(), num_channels, data_type, fixed_point_position));
     return tensor;
 }