Compute Library: arm_compute::wrapper Namespace Reference
arm_compute::wrapper Namespace Reference
Namespaces
traits
Functions
int8x8_t vabs (const int8x8_t &a)
int16x4_t vabs (const int16x4_t &a)
int32x2_t vabs (const int32x2_t &a)
float32x2_t vabs (const float32x2_t &a)
int8x16_t vabs (const int8x16_t &a)
int16x8_t vabs (const int16x8_t &a)
int32x4_t vabs (const int32x4_t &a)
float32x4_t vabs (const float32x4_t &a)
int8x8_t vqabs (const int8x8_t &a)
int16x4_t vqabs (const int16x4_t &a)
int32x2_t vqabs (const int32x2_t &a)
int8x16_t vqabs (const int8x16_t &a)
int16x8_t vqabs (const int16x8_t &a)
int32x4_t vqabs (const int32x4_t &a)
uint8x8_t vadd (const uint8x8_t &a, const uint8x8_t &b)
int8x8_t vadd (const int8x8_t &a, const int8x8_t &b)
uint16x4_t vadd (const uint16x4_t &a, const uint16x4_t &b)
int16x4_t vadd (const int16x4_t &a, const int16x4_t &b)
uint32x2_t vadd (const uint32x2_t &a, const uint32x2_t &b)
int32x2_t vadd (const int32x2_t &a, const int32x2_t &b)
uint64x1_t vadd (const uint64x1_t &a, const uint64x1_t &b)
int64x1_t vadd (const int64x1_t &a, const int64x1_t &b)
float32x2_t vadd (const float32x2_t &a, const float32x2_t &b)
uint8x16_t vadd (const uint8x16_t &a, const uint8x16_t &b)
int8x16_t vadd (const int8x16_t &a, const int8x16_t &b)
uint16x8_t vadd (const uint16x8_t &a, const uint16x8_t &b)
int16x8_t vadd (const int16x8_t &a, const int16x8_t &b)
uint32x4_t vadd (const uint32x4_t &a, const uint32x4_t &b)
int32x4_t vadd (const int32x4_t &a, const int32x4_t &b)
uint64x2_t vadd (const uint64x2_t &a, const uint64x2_t &b)
int64x2_t vadd (const int64x2_t &a, const int64x2_t &b)
float32x4_t vadd (const float32x4_t &a, const float32x4_t &b)
uint8x8_t vqadd (const uint8x8_t &a, const uint8x8_t &b)
int8x8_t vqadd (const int8x8_t &a, const int8x8_t &b)
uint16x4_t vqadd (const uint16x4_t &a, const uint16x4_t &b)
int16x4_t vqadd (const int16x4_t &a, const int16x4_t &b)
uint32x2_t vqadd (const uint32x2_t &a, const uint32x2_t &b)
int32x2_t vqadd (const int32x2_t &a, const int32x2_t &b)
uint64x1_t vqadd (const uint64x1_t &a, const uint64x1_t &b)
int64x1_t vqadd (const int64x1_t &a, const int64x1_t &b)
float32x2_t vqadd (const float32x2_t &a, const float32x2_t &b)
uint8x16_t vqadd (const uint8x16_t &a, const uint8x16_t &b)
int8x16_t vqadd (const int8x16_t &a, const int8x16_t &b)
uint16x8_t vqadd (const uint16x8_t &a, const uint16x8_t &b)
int16x8_t vqadd (const int16x8_t &a, const int16x8_t &b)
uint32x4_t vqadd (const uint32x4_t &a, const uint32x4_t &b)
int32x4_t vqadd (const int32x4_t &a, const int32x4_t &b)
uint64x2_t vqadd (const uint64x2_t &a, const uint64x2_t &b)
int64x2_t vqadd (const int64x2_t &a, const int64x2_t &b)
float32x4_t vqadd (const float32x4_t &a, const float32x4_t &b)
uint8x8_t vand (const uint8x8_t &a, const uint8x8_t &b)
int8x8_t vand (const int8x8_t &a, const int8x8_t &b)
uint16x4_t vand (const uint16x4_t &a, const uint16x4_t &b)
int16x4_t vand (const int16x4_t &a, const int16x4_t &b)
uint32x2_t vand (const uint32x2_t &a, const uint32x2_t &b)
int32x2_t vand (const int32x2_t &a, const int32x2_t &b)
uint64x1_t vand (const uint64x1_t &a, const uint64x1_t &b)
int64x1_t vand (const int64x1_t &a, const int64x1_t &b)
uint8x16_t vand (const uint8x16_t &a, const uint8x16_t &b)
int8x16_t vand (const int8x16_t &a, const int8x16_t &b)
uint16x8_t vand (const uint16x8_t &a, const uint16x8_t &b)
int16x8_t vand (const int16x8_t &a, const int16x8_t &b)
uint32x4_t vand (const uint32x4_t &a, const uint32x4_t &b)
int32x4_t vand (const int32x4_t &a, const int32x4_t &b)
uint64x2_t vand (const uint64x2_t &a, const uint64x2_t &b)
int64x2_t vand (const int64x2_t &a, const int64x2_t &b)
uint8x8_t vbsl (const uint8x8_t &a, const uint8x8_t &b, const uint8x8_t &c)
int8x8_t vbsl (const uint8x8_t &a, const int8x8_t &b, const int8x8_t &c)
uint16x4_t vbsl (const uint16x4_t &a, const uint16x4_t &b, const uint16x4_t &c)
int16x4_t vbsl (const uint16x4_t &a, const int16x4_t &b, const int16x4_t &c)
uint32x2_t vbsl (const uint32x2_t &a, const uint32x2_t &b, const uint32x2_t &c)
int32x2_t vbsl (const uint32x2_t &a, const int32x2_t &b, const int32x2_t &c)
float32x2_t vbsl (const uint32x2_t &a, const float32x2_t &b, const float32x2_t &c)
uint8x16_t vbsl (const uint8x16_t &a, const uint8x16_t &b, const uint8x16_t &c)
int8x16_t vbsl (const uint8x16_t &a, const int8x16_t &b, const int8x16_t &c)
uint16x8_t vbsl (const uint16x8_t &a, const uint16x8_t &b, const uint16x8_t &c)
int16x8_t vbsl (const uint16x8_t &a, const int16x8_t &b, const int16x8_t &c)
uint32x4_t vbsl (const uint32x4_t &a, const uint32x4_t &b, const uint32x4_t &c)
int32x4_t vbsl (const uint32x4_t &a, const int32x4_t &b, const int32x4_t &c)
float32x4_t vbsl (const uint32x4_t &a, const float32x4_t &b, const float32x4_t &c)
uint8x8_t vceq (const uint8x8_t &a, const uint8x8_t &b)
uint8x8_t vceq (const int8x8_t &a, const int8x8_t &b)
uint16x4_t vceq (const uint16x4_t &a, const uint16x4_t &b)
uint16x4_t vceq (const int16x4_t &a, const int16x4_t &b)
uint32x2_t vceq (const uint32x2_t &a, const uint32x2_t &b)
uint32x2_t vceq (const int32x2_t &a, const int32x2_t &b)
uint32x2_t vceq (const float32x2_t &a, const float32x2_t &b)
uint8x16_t vceq (const uint8x16_t &a, const uint8x16_t &b)
uint8x16_t vceq (const int8x16_t &a, const int8x16_t &b)
uint16x8_t vceq (const uint16x8_t &a, const uint16x8_t &b)
uint16x8_t vceq (const int16x8_t &a, const int16x8_t &b)
uint32x4_t vceq (const uint32x4_t &a, const uint32x4_t &b)
uint32x4_t vceq (const int32x4_t &a, const int32x4_t &b)
uint32x4_t vceq (const float32x4_t &a, const float32x4_t &b)
uint8x8_t vcge (const uint8x8_t &a, const uint8x8_t &b)
uint8x8_t vcge (const int8x8_t &a, const int8x8_t &b)
uint16x4_t vcge (const uint16x4_t &a, const uint16x4_t &b)
uint16x4_t vcge (const int16x4_t &a, const int16x4_t &b)
uint32x2_t vcge (const uint32x2_t &a, const uint32x2_t &b)
uint32x2_t vcge (const int32x2_t &a, const int32x2_t &b)
uint32x2_t vcge (const float32x2_t &a, const float32x2_t &b)
uint8x16_t vcge (const uint8x16_t &a, const uint8x16_t &b)
uint8x16_t vcge (const int8x16_t &a, const int8x16_t &b)
uint16x8_t vcge (const uint16x8_t &a, const uint16x8_t &b)
uint16x8_t vcge (const int16x8_t &a, const int16x8_t &b)
uint32x4_t vcge (const uint32x4_t &a, const uint32x4_t &b)
uint32x4_t vcge (const int32x4_t &a, const int32x4_t &b)
uint32x4_t vcge (const float32x4_t &a, const float32x4_t &b)
uint8x8_t vcgt (const uint8x8_t &a, const uint8x8_t &b)
uint8x8_t vcgt (const int8x8_t &a, const int8x8_t &b)
uint16x4_t vcgt (const uint16x4_t &a, const uint16x4_t &b)
uint16x4_t vcgt (const int16x4_t &a, const int16x4_t &b)
uint32x2_t vcgt (const uint32x2_t &a, const uint32x2_t &b)
uint32x2_t vcgt (const int32x2_t &a, const int32x2_t &b)
uint32x2_t vcgt (const float32x2_t &a, const float32x2_t &b)
uint8x16_t vcgt (const uint8x16_t &a, const uint8x16_t &b)
uint8x16_t vcgt (const int8x16_t &a, const int8x16_t &b)
uint16x8_t vcgt (const uint16x8_t &a, const uint16x8_t &b)
uint16x8_t vcgt (const int16x8_t &a, const int16x8_t &b)
uint32x4_t vcgt (const uint32x4_t &a, const uint32x4_t &b)
uint32x4_t vcgt (const int32x4_t &a, const int32x4_t &b)
uint32x4_t vcgt (const float32x4_t &a, const float32x4_t &b)
uint8x8_t vclt (const uint8x8_t &a, const uint8x8_t &b)
uint8x8_t vclt (const int8x8_t &a, const int8x8_t &b)
uint16x4_t vclt (const uint16x4_t &a, const uint16x4_t &b)
uint16x4_t vclt (const int16x4_t &a, const int16x4_t &b)
uint32x2_t vclt (const uint32x2_t &a, const uint32x2_t &b)
uint32x2_t vclt (const int32x2_t &a, const int32x2_t &b)
uint32x2_t vclt (const float32x2_t &a, const float32x2_t &b)
uint8x16_t vclt (const uint8x16_t &a, const uint8x16_t &b)
uint8x16_t vclt (const int8x16_t &a, const int8x16_t &b)
uint16x8_t vclt (const uint16x8_t &a, const uint16x8_t &b)
uint16x8_t vclt (const int16x8_t &a, const int16x8_t &b)
uint32x4_t vclt (const uint32x4_t &a, const uint32x4_t &b)
uint32x4_t vclt (const int32x4_t &a, const int32x4_t &b)
uint32x4_t vclt (const float32x4_t &a, const float32x4_t &b)
uint8x16_t vcombine (const uint8x8_t &a, const uint8x8_t &b)
int8x16_t vcombine (const int8x8_t &a, const int8x8_t &b)
uint16x8_t vcombine (const uint16x4_t &a, const uint16x4_t &b)
int16x8_t vcombine (const int16x4_t &a, const int16x4_t &b)
uint32x4_t vcombine (const uint32x2_t &a, const uint32x2_t &b)
int32x4_t vcombine (const int32x2_t &a, const int32x2_t &b)
float32x4_t vcombine (const float32x2_t &a, const float32x2_t &b)
float32x2_t vdiv (const float32x2_t &a, const float32x2_t &b)
float32x4_t vdiv (const float32x4_t &a, const float32x4_t &b)
uint8x8_t vdup_n (uint8_t value, traits::vector_64_tag)
int8x8_t vdup_n (int8_t value, traits::vector_64_tag)
uint16x4_t vdup_n (uint16_t value, traits::vector_64_tag)
int16x4_t vdup_n (int16_t value, traits::vector_64_tag)
uint32x2_t vdup_n (uint32_t value, traits::vector_64_tag)
int32x2_t vdup_n (int32_t value, traits::vector_64_tag)
float32x2_t vdup_n (float value, traits::vector_64_tag)
uint8x16_t vdup_n (uint8_t value, traits::vector_128_tag)
int8x16_t vdup_n (int8_t value, traits::vector_128_tag)
uint16x8_t vdup_n (uint16_t value, traits::vector_128_tag)
int16x8_t vdup_n (int16_t value, traits::vector_128_tag)
uint32x4_t vdup_n (uint32_t value, traits::vector_128_tag)
int32x4_t vdup_n (int32_t value, traits::vector_128_tag)
float32x4_t vdup_n (float value, traits::vector_128_tag)
float32x4_t vexpq (const float32x4_t &a)
uint8x8_t vgethigh (const uint8x16_t val)
int8x8_t vgethigh (const int8x16_t val)
uint16x4_t vgethigh (const uint16x8_t val)
int16x4_t vgethigh (const int16x8_t val)
uint32x2_t vgethigh (const uint32x4_t val)
int32x2_t vgethigh (const int32x4_t val)
float32x2_t vgethigh (const float32x4_t val)
uint8_t vgetlane (const uint8x8_t vector, const unsigned int lane)
int8_t vgetlane (const int8x8_t vector, const unsigned int lane)
uint16_t vgetlane (const uint16x4_t vector, const unsigned int lane)
int16_t vgetlane (const int16x4_t vector, const unsigned int lane)
uint32_t vgetlane (const uint32x2_t vector, const unsigned int lane)
int32_t vgetlane (const int32x2_t vector, const unsigned int lane)
float vgetlane (const float32x2_t vector, const unsigned int lane)
uint8_t vgetlane (const uint8x16_t vector, const unsigned int lane)
int8_t vgetlane (const int8x16_t vector, const unsigned int lane)
uint16_t vgetlane (const uint16x8_t vector, const unsigned int lane)
int16_t vgetlane (const int16x8_t vector, const unsigned int lane)
uint32_t vgetlane (const uint32x4_t vector, const unsigned int lane)
int32_t vgetlane (const int32x4_t vector, const unsigned int lane)
float vgetlane (const float32x4_t vector, const unsigned int lane)
uint8x8_t vgetlow (const uint8x16_t val)
int8x8_t vgetlow (const int8x16_t val)
uint16x4_t vgetlow (const uint16x8_t val)
int16x4_t vgetlow (const int16x8_t val)
uint32x2_t vgetlow (const uint32x4_t val)
int32x2_t vgetlow (const int32x4_t val)
float32x2_t vgetlow (const float32x4_t val)
float32x2_t vinv (const float32x2_t &a)
int32x2_t vinv (const int32x2_t &a)
float32x4_t vinv (const float32x4_t &a)
int32x4_t vinv (const int32x4_t &a)
float32x2_t vinvsqrt (const float32x2_t &a)
float32x4_t vinvsqrt (const float32x4_t &a)
uint8x8_t vload (const uint8_t *ptr)
int8x8_t vload (const int8_t *ptr)
uint16x4_t vload (const uint16_t *ptr)
int16x4_t vload (const int16_t *ptr)
uint32x2_t vload (const uint32_t *ptr)
int32x2_t vload (const int32_t *ptr)
float32x2_t vload (const float *ptr)
uint8x16_t vloadq (const uint8_t *ptr)
int8x16_t vloadq (const int8_t *ptr)
uint16x8_t vloadq (const uint16_t *ptr)
int16x8_t vloadq (const int16_t *ptr)
uint32x4_t vloadq (const uint32_t *ptr)
int32x4_t vloadq (const int32_t *ptr)
float32x4_t vloadq (const float *ptr)
float32x4_t vlog (const float32x4_t &a)
uint8x8_t vmax (const uint8x8_t &a, const uint8x8_t &b)
int8x8_t vmax (const int8x8_t &a, const int8x8_t &b)
uint16x4_t vmax (const uint16x4_t &a, const uint16x4_t &b)
int16x4_t vmax (const int16x4_t &a, const int16x4_t &b)
uint32x2_t vmax (const uint32x2_t &a, const uint32x2_t &b)
int32x2_t vmax (const int32x2_t &a, const int32x2_t &b)
float32x2_t vmax (const float32x2_t &a, const float32x2_t &b)
uint8x16_t vmax (const uint8x16_t &a, const uint8x16_t &b)
int8x16_t vmax (const int8x16_t &a, const int8x16_t &b)
uint16x8_t vmax (const uint16x8_t &a, const uint16x8_t &b)
int16x8_t vmax (const int16x8_t &a, const int16x8_t &b)
uint32x4_t vmax (const uint32x4_t &a, const uint32x4_t &b)
int32x4_t vmax (const int32x4_t &a, const int32x4_t &b)
float32x4_t vmax (const float32x4_t &a, const float32x4_t &b)
uint8x8_t vmin (const uint8x8_t &a, const uint8x8_t &b)
int8x8_t vmin (const int8x8_t &a, const int8x8_t &b)
uint16x4_t vmin (const uint16x4_t &a, const uint16x4_t &b)
int16x4_t vmin (const int16x4_t &a, const int16x4_t &b)
uint32x2_t vmin (const uint32x2_t &a, const uint32x2_t &b)
int32x2_t vmin (const int32x2_t &a, const int32x2_t &b)
float32x2_t vmin (const float32x2_t &a, const float32x2_t &b)
uint8x16_t vmin (const uint8x16_t &a, const uint8x16_t &b)
int8x16_t vmin (const int8x16_t &a, const int8x16_t &b)
uint16x8_t vmin (const uint16x8_t &a, const uint16x8_t &b)
int16x8_t vmin (const int16x8_t &a, const int16x8_t &b)
uint32x4_t vmin (const uint32x4_t &a, const uint32x4_t &b)
int32x4_t vmin (const int32x4_t &a, const int32x4_t &b)
float32x4_t vmin (const float32x4_t &a, const float32x4_t &b)
uint8x8_t vmla (const uint8x8_t &a, const uint8x8_t &b, const uint8x8_t &c)
int8x8_t vmla (const int8x8_t &a, const int8x8_t &b, const int8x8_t &c)
uint16x4_t vmla (const uint16x4_t &a, const uint16x4_t &b, const uint16x4_t &c)
int16x4_t vmla (const int16x4_t &a, const int16x4_t &b, const int16x4_t &c)
uint32x2_t vmla (const uint32x2_t &a, const uint32x2_t &b, const uint32x2_t &c)
int32x2_t vmla (const int32x2_t &a, const int32x2_t &b, const int32x2_t &c)
float32x2_t vmla (const float32x2_t &a, const float32x2_t &b, const float32x2_t &c)
uint8x16_t vmla (const uint8x16_t &a, const uint8x16_t &b, const uint8x16_t &c)
int8x16_t vmla (const int8x16_t &a, const int8x16_t &b, const int8x16_t &c)
uint16x8_t vmla (const uint16x8_t &a, const uint16x8_t &b, const uint16x8_t &c)
int16x8_t vmla (const int16x8_t &a, const int16x8_t &b, const int16x8_t &c)
uint32x4_t vmla (const uint32x4_t &a, const uint32x4_t &b, const uint32x4_t &c)
int32x4_t vmla (const int32x4_t &a, const int32x4_t &b, const int32x4_t &c)
float32x4_t vmla (const float32x4_t &a, const float32x4_t &b, const float32x4_t &c)
uint16x8_t vmovl (const uint8x8_t &a)
int16x8_t vmovl (const int8x8_t &a)
uint32x4_t vmovl (const uint16x4_t &a)
int32x4_t vmovl (const int16x4_t &a)
uint64x2_t vmovl (const uint32x2_t &a)
int64x2_t vmovl (const int32x2_t &a)
uint32x2_t vmovn (const uint64x2_t &a)
int32x2_t vmovn (const int64x2_t &a)
uint16x4_t vmovn (const uint32x4_t &a)
int16x4_t vmovn (const int32x4_t &a)
uint8x8_t vmovn (const uint16x8_t &a)
int8x8_t vmovn (const int16x8_t &a)
uint32x2_t vqmovn (const uint64x2_t &a)
int32x2_t vqmovn (const int64x2_t &a)
uint16x4_t vqmovn (const uint32x4_t &a)
int16x4_t vqmovn (const int32x4_t &a)
uint8x8_t vqmovn (const uint16x8_t &a)
int8x8_t vqmovn (const int16x8_t &a)
uint8x8_t vmul (const uint8x8_t &a, const uint8x8_t &b)
int8x8_t vmul (const int8x8_t &a, const int8x8_t &b)
uint16x4_t vmul (const uint16x4_t &a, const uint16x4_t &b)
int16x4_t vmul (const int16x4_t &a, const int16x4_t &b)
uint32x2_t vmul (const uint32x2_t &a, const uint32x2_t &b)
int32x2_t vmul (const int32x2_t &a, const int32x2_t &b)
float32x2_t vmul (const float32x2_t &a, const float32x2_t &b)
uint8x16_t vmul (const uint8x16_t &a, const uint8x16_t &b)
int8x16_t vmul (const int8x16_t &a, const int8x16_t &b)
uint16x8_t vmul (const uint16x8_t &a, const uint16x8_t &b)
int16x8_t vmul (const int16x8_t &a, const int16x8_t &b)
uint32x4_t vmul (const uint32x4_t &a, const uint32x4_t &b)
int32x4_t vmul (const int32x4_t &a, const int32x4_t &b)
float32x4_t vmul (const float32x4_t &a, const float32x4_t &b)
int8x8_t vneg (const int8x8_t &a)
int16x4_t vneg (const int16x4_t &a)
int32x2_t vneg (const int32x2_t &a)
float32x2_t vneg (const float32x2_t &a)
int8x16_t vneg (const int8x16_t &a)
int16x8_t vneg (const int16x8_t &a)
int32x4_t vneg (const int32x4_t &a)
float32x4_t vneg (const float32x4_t &a)
uint8x8_t vnot (const uint8x8_t &a)
int8x8_t vnot (const int8x8_t &a)
uint16x4_t vnot (const uint16x4_t &a)
int16x4_t vnot (const int16x4_t &a)
uint32x2_t vnot (const uint32x2_t &a)
int32x2_t vnot (const int32x2_t &a)
float32x2_t vnot (const float32x2_t &a)
uint8x16_t vnot (const uint8x16_t &a)
int8x16_t vnot (const int8x16_t &a)
uint16x8_t vnot (const uint16x8_t &a)
int16x8_t vnot (const int16x8_t &a)
uint32x4_t vnot (const uint32x4_t &a)
int32x4_t vnot (const int32x4_t &a)
float32x4_t vnot (const float32x4_t &a)
uint8x8_t vorr (const uint8x8_t &a, const uint8x8_t &b)
int8x8_t vorr (const int8x8_t &a, const int8x8_t &b)
uint16x4_t vorr (const uint16x4_t &a, const uint16x4_t &b)
int16x4_t vorr (const int16x4_t &a, const int16x4_t &b)
uint32x2_t vorr (const uint32x2_t &a, const uint32x2_t &b)
int32x2_t vorr (const int32x2_t &a, const int32x2_t &b)
uint64x1_t vorr (const uint64x1_t &a, const uint64x1_t &b)
int64x1_t vorr (const int64x1_t &a, const int64x1_t &b)
uint8x16_t vorr (const uint8x16_t &a, const uint8x16_t &b)
int8x16_t vorr (const int8x16_t &a, const int8x16_t &b)
uint16x8_t vorr (const uint16x8_t &a, const uint16x8_t &b)
int16x8_t vorr (const int16x8_t &a, const int16x8_t &b)
uint32x4_t vorr (const uint32x4_t &a, const uint32x4_t &b)
int32x4_t vorr (const int32x4_t &a, const int32x4_t &b)
uint64x2_t vorr (const uint64x2_t &a, const uint64x2_t &b)
int64x2_t vorr (const int64x2_t &a, const int64x2_t &b)
uint8x8_t vpadd (const uint8x8_t &a, const uint8x8_t &b)
int8x8_t vpadd (const int8x8_t &a, const int8x8_t &b)
uint16x4_t vpadd (const uint16x4_t &a, const uint16x4_t &b)
int16x4_t vpadd (const int16x4_t &a, const int16x4_t &b)
uint32x2_t vpadd (const uint32x2_t &a, const uint32x2_t &b)
int32x2_t vpadd (const int32x2_t &a, const int32x2_t &b)
float32x2_t vpadd (const float32x2_t &a, const float32x2_t &b)
uint8x8_t vpmax (const uint8x8_t &a, const uint8x8_t &b)
int8x8_t vpmax (const int8x8_t &a, const int8x8_t &b)
uint16x4_t vpmax (const uint16x4_t &a, const uint16x4_t &b)
int16x4_t vpmax (const int16x4_t &a, const int16x4_t &b)
uint32x2_t vpmax (const uint32x2_t &a, const uint32x2_t &b)
int32x2_t vpmax (const int32x2_t &a, const int32x2_t &b)
float32x2_t vpmax (const float32x2_t &a, const float32x2_t &b)
uint8x8_t vpmin (const uint8x8_t &a, const uint8x8_t &b)
int8x8_t vpmin (const int8x8_t &a, const int8x8_t &b)
uint16x4_t vpmin (const uint16x4_t &a, const uint16x4_t &b)
int16x4_t vpmin (const int16x4_t &a, const int16x4_t &b)
uint32x2_t vpmin (const uint32x2_t &a, const uint32x2_t &b)
int32x2_t vpmin (const int32x2_t &a, const int32x2_t &b)
float32x2_t vpmin (const float32x2_t &a, const float32x2_t &b)
float32x4_t vpow (const float32x4_t &a, const float32x4_t &b)
uint8x8_t vrev64 (const uint8x8_t &a)
int8x8_t vrev64 (const int8x8_t &a)
uint16x4_t vrev64 (const uint16x4_t &a)
int16x4_t vrev64 (const int16x4_t &a)
uint32x2_t vrev64 (const uint32x2_t &a)
int32x2_t vrev64 (const int32x2_t &a)
float32x2_t vrev64 (const float32x2_t &a)
uint8x16_t vrev64 (const uint8x16_t &a)
int8x16_t vrev64 (const int8x16_t &a)
uint16x8_t vrev64 (const uint16x8_t &a)
int16x8_t vrev64 (const int16x8_t &a)
uint32x4_t vrev64 (const uint32x4_t &a)
int32x4_t vrev64 (const int32x4_t &a)
float32x4_t vrev64 (const float32x4_t &a)
float32x4_t vround (const float32x4_t &a)
uint8x8_t vsetlane (const uint8_t value, const uint8x8_t vector, const unsigned int lane)
int8x8_t vsetlane (const int8_t value, const int8x8_t vector, const unsigned int lane)
uint16x4_t vsetlane (const uint16_t value, const uint16x4_t vector, const unsigned int lane)
int16x4_t vsetlane (const int16_t value, const int16x4_t vector, const unsigned int lane)
uint32x2_t vsetlane (const uint32_t value, const uint32x2_t vector, const unsigned int lane)
int32x2_t vsetlane (const int32_t value, const int32x2_t vector, const unsigned int lane)
float32x2_t vsetlane (const float value, const float32x2_t vector, const unsigned int lane)
uint8x16_t vsetlane (const uint8_t value, const uint8x16_t vector, const unsigned int lane)
int8x16_t vsetlane (const int8_t value, const int8x16_t vector, const unsigned int lane)
uint16x8_t vsetlane (const uint16_t value, const uint16x8_t vector, const unsigned int lane)
int16x8_t vsetlane (const int16_t value, const int16x8_t vector, const unsigned int lane)
uint32x4_t vsetlane (const uint32_t value, const uint32x4_t vector, const unsigned int lane)
int32x4_t vsetlane (const int32_t value, const int32x4_t vector, const unsigned int lane)
float32x4_t vsetlane (const float value, const float32x4_t vector, const unsigned int lane)
float32x4_t vsin (const float32x4_t &a)
void vstore (uint8_t *ptr, uint8x8_t val)
void vstore (int8_t *ptr, int8x8_t val)
void vstore (uint16_t *ptr, uint16x4_t val)
void vstore (int16_t *ptr, int16x4_t val)
void vstore (uint32_t *ptr, uint32x2_t val)
void vstore (int32_t *ptr, int32x2_t val)
void vstore (float *ptr, float32x2_t val)
void vstore (uint8_t *ptr, uint8x16_t val)
void vstore (int8_t *ptr, int8x16_t val)
void vstore (uint16_t *ptr, uint16x8_t val)
void vstore (int16_t *ptr, int16x8_t val)
void vstore (uint32_t *ptr, uint32x4_t val)
void vstore (int32_t *ptr, int32x4_t val)
void vstore (float *ptr, float32x4_t val)
uint8x8_t vsub (const uint8x8_t &a, const uint8x8_t &b)
int8x8_t vsub (const int8x8_t &a, const int8x8_t &b)
uint16x4_t vsub (const uint16x4_t &a, const uint16x4_t &b)
int16x4_t vsub (const int16x4_t &a, const int16x4_t &b)
uint32x2_t vsub (const uint32x2_t &a, const uint32x2_t &b)
int32x2_t vsub (const int32x2_t &a, const int32x2_t &b)
uint64x1_t vsub (const uint64x1_t &a, const uint64x1_t &b)
int64x1_t vsub (const int64x1_t &a, const int64x1_t &b)
float32x2_t vsub (const float32x2_t &a, const float32x2_t &b)
uint8x16_t vsub (const uint8x16_t &a, const uint8x16_t &b)
int8x16_t vsub (const int8x16_t &a, const int8x16_t &b)
uint16x8_t vsub (const uint16x8_t &a, const uint16x8_t &b)
int16x8_t vsub (const int16x8_t &a, const int16x8_t &b)
uint32x4_t vsub (const uint32x4_t &a, const uint32x4_t &b)
int32x4_t vsub (const int32x4_t &a, const int32x4_t &b)
uint64x2_t vsub (const uint64x2_t &a, const uint64x2_t &b)
int64x2_t vsub (const int64x2_t &a, const int64x2_t &b)
float32x4_t vsub (const float32x4_t &a, const float32x4_t &b)
float32x4_t vtanh (const float32x4_t &a)
uint8_t add_sat (const uint8_t &a, const uint8_t &b)
int16_t add_sat (const int16_t &a, const int16_t &b)
float add_sat (const float &a, const float &b)
Function Documentation
add_sat() [1/3]
uint8_t arm_compute::wrapper::add_sat (const uint8_t & a, const uint8_t & b) inline
Definition at line 33 of file add.h.
 {
     const uint8x8_t va = { a, 0, 0, 0, 0, 0, 0, 0 };
     const uint8x8_t vb = { b, 0, 0, 0, 0, 0, 0, 0 };
     return vget_lane_u8(vqadd_u8(va, vb), 0);
 }
References arm_compute::test::validation::b.
Referenced by accumulate(), compute_strength(), fast_corners(), and magnitude_l1().
add_sat() [2/3]
int16_t arm_compute::wrapper::add_sat (const int16_t & a, const int16_t & b) inline
Definition at line 40 of file add.h.
 {
     const int16x4_t va = { a, 0, 0, 0 };
     const int16x4_t vb = { b, 0, 0, 0 };
     return vget_lane_s16(vqadd_s16(va, vb), 0);
 }
References arm_compute::test::validation::b.
add_sat() [3/3]
float arm_compute::wrapper::add_sat (const float & a, const float & b) inline
Definition at line 47 of file add.h.
 {
     // No notion of saturation exists in floating point
     return a + b;
 }
References arm_compute::test::validation::b.
vabs() [1/8]
int8x8_t arm_compute::wrapper::vabs (const int8x8_t & a) inline
Definition at line 46 of file abs.h.
vabs() [2/8]
int16x4_t arm_compute::wrapper::vabs (const int16x4_t & a) inline
Definition at line 47 of file abs.h.
vabs() [3/8]
int32x2_t arm_compute::wrapper::vabs (const int32x2_t & a) inline
Definition at line 48 of file abs.h.
vabs() [4/8]
float32x2_t arm_compute::wrapper::vabs (const float32x2_t & a) inline
Definition at line 49 of file abs.h.
vabs() [5/8]
int8x16_t arm_compute::wrapper::vabs (const int8x16_t & a) inline
Definition at line 54 of file abs.h.
vabs() [6/8]
int16x8_t arm_compute::wrapper::vabs (const int16x8_t & a) inline
Definition at line 55 of file abs.h.
vabs() [7/8]
int32x4_t arm_compute::wrapper::vabs (const int32x4_t & a) inline
Definition at line 56 of file abs.h.
vabs() [8/8]
float32x4_t arm_compute::wrapper::vabs (const float32x4_t & a) inline
Definition at line 57 of file abs.h.
vadd() [1/18]
uint8x8_t arm_compute::wrapper::vadd (const uint8x8_t & a, const uint8x8_t & b) inline
Definition at line 39 of file add.h.
 {                                                  \
Referenced by logistic< T, S >::operator()().
vadd() [2/18]
int8x8_t arm_compute::wrapper::vadd (const int8x8_t & a, const int8x8_t & b) inline
Definition at line 40 of file add.h.
 {                                                  \
vadd() [3/18]
uint16x4_t arm_compute::wrapper::vadd (const uint16x4_t & a, const uint16x4_t & b) inline
Definition at line 41 of file add.h.
 {                                                  \
vadd() [4/18]
int16x4_t arm_compute::wrapper::vadd (const int16x4_t & a, const int16x4_t & b) inline
Definition at line 42 of file add.h.
 {                                                  \
vadd() [5/18]
uint32x2_t arm_compute::wrapper::vadd (const uint32x2_t & a, const uint32x2_t & b) inline
Definition at line 43 of file add.h.
 {                                                  \
vadd() [6/18]
int32x2_t arm_compute::wrapper::vadd (const int32x2_t & a, const int32x2_t & b) inline
Definition at line 44 of file add.h.
 {                                                  \
vadd() [7/18]
uint64x1_t arm_compute::wrapper::vadd (const uint64x1_t & a, const uint64x1_t & b) inline
Definition at line 45 of file add.h.
 {                                                  \
vadd() [8/18]
int64x1_t arm_compute::wrapper::vadd (const int64x1_t & a, const int64x1_t & b) inline
Definition at line 46 of file add.h.
 {                                                  \
vadd() [9/18]
float32x2_t arm_compute::wrapper::vadd (const float32x2_t & a, const float32x2_t & b) inline
Definition at line 47 of file add.h.
 {                                                  \
vadd() [10/18]
uint8x16_t arm_compute::wrapper::vadd (const uint8x16_t & a, const uint8x16_t & b) inline
Definition at line 52 of file add.h.
 {                                                  \
vadd() [11/18]
int8x16_t arm_compute::wrapper::vadd (const int8x16_t & a, const int8x16_t & b) inline
Definition at line 53 of file add.h.
 {                                                  \
vadd() [12/18]
uint16x8_t arm_compute::wrapper::vadd (const uint16x8_t & a, const uint16x8_t & b) inline
Definition at line 54 of file add.h.
 {                                                  \
vadd() [13/18]
int16x8_t arm_compute::wrapper::vadd (const int16x8_t & a, const int16x8_t & b) inline
Definition at line 55 of file add.h.
 {                                                  \
vadd() [14/18]
uint32x4_t arm_compute::wrapper::vadd (const uint32x4_t & a, const uint32x4_t & b) inline
Definition at line 56 of file add.h.
 {                                                  \
vadd() [15/18]
int32x4_t arm_compute::wrapper::vadd (const int32x4_t & a, const int32x4_t & b) inline
Definition at line 57 of file add.h.
 {                                                  \
vadd() [16/18]
uint64x2_t arm_compute::wrapper::vadd (const uint64x2_t & a, const uint64x2_t & b) inline
Definition at line 58 of file add.h.
 {                                                  \
vadd() [17/18]
int64x2_t arm_compute::wrapper::vadd (const int64x2_t & a, const int64x2_t & b) inline
Definition at line 59 of file add.h.
 {                                                  \
vadd() [18/18]
float32x4_t arm_compute::wrapper::vadd (const float32x4_t & a, const float32x4_t & b) inline
Definition at line 60 of file add.h.
 {                                                  \
vand() [1/16]
uint8x8_t arm_compute::wrapper::vand (const uint8x8_t & a, const uint8x8_t & b) inline
Definition at line 39 of file and.h.
vand() [2/16]
int8x8_t arm_compute::wrapper::vand (const int8x8_t & a, const int8x8_t & b) inline
Definition at line 40 of file and.h.
vand() [3/16]
uint16x4_t arm_compute::wrapper::vand (const uint16x4_t & a, const uint16x4_t & b) inline
Definition at line 41 of file and.h.
vand() [4/16]
int16x4_t arm_compute::wrapper::vand (const int16x4_t & a, const int16x4_t & b) inline
Definition at line 42 of file and.h.
vand() [5/16]
uint32x2_t arm_compute::wrapper::vand (const uint32x2_t & a, const uint32x2_t & b) inline
Definition at line 43 of file and.h.
vand() [6/16]
int32x2_t arm_compute::wrapper::vand (const int32x2_t & a, const int32x2_t & b) inline
Definition at line 44 of file and.h.
vand() [7/16]
uint64x1_t arm_compute::wrapper::vand (const uint64x1_t & a, const uint64x1_t & b) inline
Definition at line 45 of file and.h.
vand() [8/16]
int64x1_t arm_compute::wrapper::vand (const int64x1_t & a, const int64x1_t & b) inline
Definition at line 46 of file and.h.
vand() [9/16]
uint8x16_t arm_compute::wrapper::vand (const uint8x16_t & a, const uint8x16_t & b) inline
Definition at line 48 of file and.h.
vand() [10/16]
int8x16_t arm_compute::wrapper::vand (const int8x16_t & a, const int8x16_t & b) inline
Definition at line 49 of file and.h.
vand() [11/16]
uint16x8_t arm_compute::wrapper::vand (const uint16x8_t & a, const uint16x8_t & b) inline
Definition at line 50 of file and.h.
vand() [12/16]
int16x8_t arm_compute::wrapper::vand (const int16x8_t & a, const int16x8_t & b) inline
Definition at line 51 of file and.h.
vand() [13/16]
uint32x4_t arm_compute::wrapper::vand (const uint32x4_t & a, const uint32x4_t & b) inline
Definition at line 52 of file and.h.
vand() [14/16]
int32x4_t arm_compute::wrapper::vand (const int32x4_t & a, const int32x4_t & b) inline
Definition at line 53 of file and.h.
vand() [15/16]
uint64x2_t arm_compute::wrapper::vand (const uint64x2_t & a, const uint64x2_t & b) inline
Definition at line 54 of file and.h.
vand() [16/16]
int64x2_t arm_compute::wrapper::vand (const int64x2_t & a, const int64x2_t & b) inline
Definition at line 55 of file and.h.
vbsl() [1/14]
uint8x8_t arm_compute::wrapper::vbsl (const uint8x8_t & a, const uint8x8_t & b, const uint8x8_t & c) inline
Definition at line 39 of file bsl.h.
vbsl() [2/14]
int8x8_t arm_compute::wrapper::vbsl (const uint8x8_t & a, const int8x8_t & b, const int8x8_t & c) inline
Definition at line 40 of file bsl.h.
vbsl() [3/14]
uint16x4_t arm_compute::wrapper::vbsl (const uint16x4_t & a, const uint16x4_t & b, const uint16x4_t & c) inline
Definition at line 41 of file bsl.h.
vbsl() [4/14]
int16x4_t arm_compute::wrapper::vbsl (const uint16x4_t & a, const int16x4_t & b, const int16x4_t & c) inline
Definition at line 42 of file bsl.h.
vbsl() [5/14]
uint32x2_t arm_compute::wrapper::vbsl (const uint32x2_t & a, const uint32x2_t & b, const uint32x2_t & c) inline
Definition at line 43 of file bsl.h.
vbsl() [6/14]
int32x2_t arm_compute::wrapper::vbsl (const uint32x2_t & a, const int32x2_t & b, const int32x2_t & c) inline
Definition at line 44 of file bsl.h.
vbsl() [7/14]
float32x2_t arm_compute::wrapper::vbsl (const uint32x2_t & a, const float32x2_t & b, const float32x2_t & c) inline
Definition at line 45 of file bsl.h.
vbsl() [8/14]
uint8x16_t arm_compute::wrapper::vbsl (const uint8x16_t & a, const uint8x16_t & b, const uint8x16_t & c) inline
Definition at line 50 of file bsl.h.
vbsl() [9/14]
int8x16_t arm_compute::wrapper::vbsl (const uint8x16_t & a, const int8x16_t & b, const int8x16_t & c) inline
Definition at line 51 of file bsl.h.
vbsl() [10/14]
uint16x8_t arm_compute::wrapper::vbsl (const uint16x8_t & a, const uint16x8_t & b, const uint16x8_t & c) inline
Definition at line 52 of file bsl.h.
vbsl() [11/14]
int16x8_t arm_compute::wrapper::vbsl (const uint16x8_t & a, const int16x8_t & b, const int16x8_t & c) inline
Definition at line 53 of file bsl.h.
vbsl() [12/14]
uint32x4_t arm_compute::wrapper::vbsl (const uint32x4_t & a, const uint32x4_t & b, const uint32x4_t & c) inline
Definition at line 54 of file bsl.h.
vbsl() [13/14]
int32x4_t arm_compute::wrapper::vbsl (const uint32x4_t & a, const int32x4_t & b, const int32x4_t & c) inline
Definition at line 55 of file bsl.h.
vbsl() [14/14]
float32x4_t arm_compute::wrapper::vbsl (const uint32x4_t & a, const float32x4_t & b, const float32x4_t & c) inline
Definition at line 56 of file bsl.h.
vceq() [1/14]
uint8x8_t arm_compute::wrapper::vceq (const uint8x8_t & a, const uint8x8_t & b) inline
Definition at line 39 of file ceq.h.
vceq() [2/14]
uint8x8_t arm_compute::wrapper::vceq (const int8x8_t & a, const int8x8_t & b) inline
Definition at line 40 of file ceq.h.
vceq() [3/14]
uint16x4_t arm_compute::wrapper::vceq (const uint16x4_t & a, const uint16x4_t & b) inline
Definition at line 41 of file ceq.h.
vceq() [4/14]
uint16x4_t arm_compute::wrapper::vceq (const int16x4_t & a, const int16x4_t & b) inline
Definition at line 42 of file ceq.h.
vceq() [5/14]
uint32x2_t arm_compute::wrapper::vceq (const uint32x2_t & a, const uint32x2_t & b) inline
Definition at line 43 of file ceq.h.
vceq() [6/14]
uint32x2_t arm_compute::wrapper::vceq (const int32x2_t & a, const int32x2_t & b) inline
Definition at line 44 of file ceq.h.
vceq() [7/14]
uint32x2_t arm_compute::wrapper::vceq (const float32x2_t & a, const float32x2_t & b) inline
Definition at line 45 of file ceq.h.
vceq() [8/14]
uint8x16_t arm_compute::wrapper::vceq (const uint8x16_t & a, const uint8x16_t & b) inline
Definition at line 50 of file ceq.h.
vceq() [9/14]
uint8x16_t arm_compute::wrapper::vceq (const int8x16_t & a, const int8x16_t & b) inline
Definition at line 51 of file ceq.h.
vceq() [10/14]
uint16x8_t arm_compute::wrapper::vceq (const uint16x8_t & a, const uint16x8_t & b) inline
Definition at line 52 of file ceq.h.
vceq() [11/14]
uint16x8_t arm_compute::wrapper::vceq (const int16x8_t & a, const int16x8_t & b) inline
Definition at line 53 of file ceq.h.
vceq() [12/14]
uint32x4_t arm_compute::wrapper::vceq (const uint32x4_t & a, const uint32x4_t & b) inline
Definition at line 54 of file ceq.h.
vceq() [13/14]
uint32x4_t arm_compute::wrapper::vceq (const int32x4_t & a, const int32x4_t & b) inline
Definition at line 55 of file ceq.h.
vceq() [14/14]
uint32x4_t arm_compute::wrapper::vceq (const float32x4_t & a, const float32x4_t & b) inline
Definition at line 56 of file ceq.h.
vcge() [1/14]
uint8x8_t arm_compute::wrapper::vcge (const uint8x8_t & a, const uint8x8_t & b) inline
Definition at line 39 of file cge.h.
vcge() [2/14]
uint8x8_t arm_compute::wrapper::vcge (const int8x8_t & a, const int8x8_t & b) inline
Definition at line 40 of file cge.h.
vcge() [3/14]
uint16x4_t arm_compute::wrapper::vcge (const uint16x4_t & a, const uint16x4_t & b) inline
Definition at line 41 of file cge.h.
vcge() [4/14]
uint16x4_t arm_compute::wrapper::vcge (const int16x4_t & a, const int16x4_t & b) inline
Definition at line 42 of file cge.h.
vcge() [5/14]
uint32x2_t arm_compute::wrapper::vcge (const uint32x2_t & a, const uint32x2_t & b) inline
Definition at line 43 of file cge.h.
vcge() [6/14]
uint32x2_t arm_compute::wrapper::vcge (const int32x2_t & a, const int32x2_t & b) inline
Definition at line 44 of file cge.h.
vcge() [7/14]
uint32x2_t arm_compute::wrapper::vcge (const float32x2_t & a, const float32x2_t & b) inline
Definition at line 45 of file cge.h.
vcge() [8/14]
uint8x16_t arm_compute::wrapper::vcge (const uint8x16_t & a, const uint8x16_t & b) inline
Definition at line 50 of file cge.h.
vcge() [9/14]
uint8x16_t arm_compute::wrapper::vcge (const int8x16_t & a, const int8x16_t & b) inline
Definition at line 51 of file cge.h.
vcge() [10/14]
uint16x8_t arm_compute::wrapper::vcge (const uint16x8_t & a, const uint16x8_t & b) inline
Definition at line 52 of file cge.h.
vcge() [11/14]
uint16x8_t arm_compute::wrapper::vcge (const int16x8_t & a, const int16x8_t & b) inline
Definition at line 53 of file cge.h.
vcge() [12/14]
uint32x4_t arm_compute::wrapper::vcge (const uint32x4_t & a, const uint32x4_t & b) inline
Definition at line 54 of file cge.h.
vcge() [13/14]
uint32x4_t arm_compute::wrapper::vcge (const int32x4_t & a, const int32x4_t & b) inline
Definition at line 55 of file cge.h.
vcge() [14/14]
uint32x4_t arm_compute::wrapper::vcge (const float32x4_t & a, const float32x4_t & b) inline
Definition at line 56 of file cge.h.
vcgt() [1/14]
uint8x8_t arm_compute::wrapper::vcgt (const uint8x8_t & a, const uint8x8_t & b) inline
Definition at line 39 of file cgt.h.
vcgt() [2/14]
uint8x8_t arm_compute::wrapper::vcgt (const int8x8_t & a, const int8x8_t & b) inline
Definition at line 40 of file cgt.h.
vcgt() [3/14]
uint16x4_t arm_compute::wrapper::vcgt (const uint16x4_t & a, const uint16x4_t & b) inline
Definition at line 41 of file cgt.h.
vcgt() [4/14]
uint16x4_t arm_compute::wrapper::vcgt (const int16x4_t & a, const int16x4_t & b) inline
Definition at line 42 of file cgt.h.
vcgt() [5/14]
uint32x2_t arm_compute::wrapper::vcgt (const uint32x2_t & a, const uint32x2_t & b) inline
Definition at line 43 of file cgt.h.
vcgt() [6/14]
uint32x2_t arm_compute::wrapper::vcgt (const int32x2_t & a, const int32x2_t & b) inline
Definition at line 44 of file cgt.h.
vcgt() [7/14]
uint32x2_t arm_compute::wrapper::vcgt (const float32x2_t & a, const float32x2_t & b) inline
Definition at line 45 of file cgt.h.
vcgt() [8/14]
uint8x16_t arm_compute::wrapper::vcgt (const uint8x16_t & a, const uint8x16_t & b) inline
Definition at line 50 of file cgt.h.
vcgt() [9/14]
uint8x16_t arm_compute::wrapper::vcgt (const int8x16_t & a, const int8x16_t & b) inline
Definition at line 51 of file cgt.h.
vcgt() [10/14]
uint16x8_t arm_compute::wrapper::vcgt (const uint16x8_t & a, const uint16x8_t & b) inline
Definition at line 52 of file cgt.h.
vcgt() [11/14]
uint16x8_t arm_compute::wrapper::vcgt (const int16x8_t & a, const int16x8_t & b) inline
Definition at line 53 of file cgt.h.
vcgt() [12/14]
uint32x4_t arm_compute::wrapper::vcgt (const uint32x4_t & a, const uint32x4_t & b) inline
Definition at line 54 of file cgt.h.
vcgt() [13/14]
uint32x4_t arm_compute::wrapper::vcgt (const int32x4_t & a, const int32x4_t & b) inline
Definition at line 55 of file cgt.h.
vcgt() [14/14]
uint32x4_t arm_compute::wrapper::vcgt (const float32x4_t & a, const float32x4_t & b) inline
Definition at line 56 of file cgt.h.
vclt() [1/14]
uint8x8_t arm_compute::wrapper::vclt (const uint8x8_t & a, const uint8x8_t & b) inline
Definition at line 39 of file clt.h.
vclt() [2/14]
uint8x8_t arm_compute::wrapper::vclt (const int8x8_t & a, const int8x8_t & b) inline
Definition at line 40 of file clt.h.
vclt() [3/14]
uint16x4_t arm_compute::wrapper::vclt (const uint16x4_t & a, const uint16x4_t & b) inline
Definition at line 41 of file clt.h.
vclt() [4/14]
uint16x4_t arm_compute::wrapper::vclt (const int16x4_t & a, const int16x4_t & b) inline
Definition at line 42 of file clt.h.
vclt() [5/14]
uint32x2_t arm_compute::wrapper::vclt (const uint32x2_t & a, const uint32x2_t & b) inline
Definition at line 43 of file clt.h.
vclt() [6/14]
uint32x2_t arm_compute::wrapper::vclt (const int32x2_t & a, const int32x2_t & b) inline
Definition at line 44 of file clt.h.
vclt() [7/14]
uint32x2_t arm_compute::wrapper::vclt (const float32x2_t & a, const float32x2_t & b) inline
Definition at line 45 of file clt.h.
vclt() [8/14]
uint8x16_t arm_compute::wrapper::vclt (const uint8x16_t & a, const uint8x16_t & b) inline
Definition at line 50 of file clt.h.
vclt() [9/14]
uint8x16_t arm_compute::wrapper::vclt (const int8x16_t & a, const int8x16_t & b) inline
Definition at line 51 of file clt.h.
vclt() [10/14]
uint16x8_t arm_compute::wrapper::vclt (const uint16x8_t & a, const uint16x8_t & b) inline
Definition at line 52 of file clt.h.
vclt() [11/14]
uint16x8_t arm_compute::wrapper::vclt (const int16x8_t & a, const int16x8_t & b) inline
Definition at line 53 of file clt.h.
vclt() [12/14]
uint32x4_t arm_compute::wrapper::vclt (const uint32x4_t & a, const uint32x4_t & b) inline
Definition at line 54 of file clt.h.
vclt() [13/14]
uint32x4_t arm_compute::wrapper::vclt (const int32x4_t & a, const int32x4_t & b) inline
Definition at line 55 of file clt.h.
vclt() [14/14]
uint32x4_t arm_compute::wrapper::vclt (const float32x4_t & a, const float32x4_t & b) inline
Definition at line 56 of file clt.h.
vcombine() [1/7]
uint8x16_t arm_compute::wrapper::vcombine (const uint8x8_t & a, const uint8x8_t & b) inline
Definition at line 39 of file combine.h.
Referenced by arm_compute::run_reverse().
vcombine() [2/7]
int8x16_t arm_compute::wrapper::vcombine (const int8x8_t & a, const int8x8_t & b) inline
Definition at line 40 of file combine.h.
vcombine() [3/7]
uint16x8_t arm_compute::wrapper::vcombine (const uint16x4_t & a, const uint16x4_t & b) inline
Definition at line 41 of file combine.h.
vcombine() [4/7]
int16x8_t arm_compute::wrapper::vcombine (const int16x4_t & a, const int16x4_t & b) inline
Definition at line 42 of file combine.h.
vcombine() [5/7]
uint32x4_t arm_compute::wrapper::vcombine (const uint32x2_t & a, const uint32x2_t & b) inline
Definition at line 43 of file combine.h.
vcombine() [6/7]
int32x4_t arm_compute::wrapper::vcombine (const int32x2_t & a, const int32x2_t & b) inline
Definition at line 44 of file combine.h.
vcombine() [7/7]
float32x4_t arm_compute::wrapper::vcombine (const float32x2_t & a, const float32x2_t & b) inline
Definition at line 45 of file combine.h.
vdiv() [1/2]
float32x2_t arm_compute::wrapper::vdiv (const float32x2_t & a, const float32x2_t & b) inline
Definition at line 58 of file div.h.
vdiv() [2/2]
float32x4_t arm_compute::wrapper::vdiv (const float32x4_t & a, const float32x4_t & b) inline
Definition at line 63 of file div.h.
vdup_n() [1/14]
uint8x8_t arm_compute::wrapper::vdup_n (uint8_t value, traits::vector_64_tag) inline
Definition at line 41 of file dup_n.h.
vdup_n() [2/14]
int8x8_t arm_compute::wrapper::vdup_n (int8_t value, traits::vector_64_tag) inline
Definition at line 42 of file dup_n.h.
vdup_n() [3/14]
uint16x4_t arm_compute::wrapper::vdup_n (uint16_t value, traits::vector_64_tag) inline
Definition at line 43 of file dup_n.h.
vdup_n() [4/14]
int16x4_t arm_compute::wrapper::vdup_n (int16_t value, traits::vector_64_tag) inline
Definition at line 44 of file dup_n.h.
vdup_n() [5/14]
uint32x2_t arm_compute::wrapper::vdup_n (uint32_t value, traits::vector_64_tag) inline
Definition at line 45 of file dup_n.h.
vdup_n() [6/14]
int32x2_t arm_compute::wrapper::vdup_n (int32_t value, traits::vector_64_tag) inline
Definition at line 46 of file dup_n.h.
vdup_n() [7/14]
float32x2_t arm_compute::wrapper::vdup_n (float value, traits::vector_64_tag) inline
Definition at line 47 of file dup_n.h.
vdup_n() [8/14]
uint8x16_t arm_compute::wrapper::vdup_n (uint8_t value, traits::vector_128_tag) inline
Definition at line 52 of file dup_n.h.
vdup_n() [9/14]
int8x16_t arm_compute::wrapper::vdup_n (int8_t value, traits::vector_128_tag) inline
Definition at line 53 of file dup_n.h.
vdup_n() [10/14]
uint16x8_t arm_compute::wrapper::vdup_n (uint16_t value, traits::vector_128_tag) inline
Definition at line 54 of file dup_n.h.
vdup_n() [11/14]
int16x8_t arm_compute::wrapper::vdup_n (int16_t value, traits::vector_128_tag) inline
Definition at line 55 of file dup_n.h.
vdup_n() [12/14]
uint32x4_t arm_compute::wrapper::vdup_n (uint32_t value, traits::vector_128_tag) inline
Definition at line 56 of file dup_n.h.
vdup_n() [13/14]
int32x4_t arm_compute::wrapper::vdup_n (int32_t value, traits::vector_128_tag) inline
Definition at line 57 of file dup_n.h.
vdup_n() [14/14]
float32x4_t arm_compute::wrapper::vdup_n (float value, traits::vector_128_tag) inline
Definition at line 58 of file dup_n.h.
vexpq()
float32x4_t arm_compute::wrapper::vexpq (const float32x4_t & a) inline
Definition at line 40 of file exp.h.
Referenced by logistic< T, S >::operator()().
vgethigh() [1/7]
uint8x8_t arm_compute::wrapper::vgethigh (const uint8x16_t val) inline
Definition at line 39 of file gethigh.h.
Referenced by arm_compute::run_reverse().
vgethigh() [2/7]
int8x8_t arm_compute::wrapper::vgethigh (const int8x16_t val) inline
Definition at line 40 of file gethigh.h.
vgethigh() [3/7]
uint16x4_t arm_compute::wrapper::vgethigh (const uint16x8_t val) inline
Definition at line 41 of file gethigh.h.
vgethigh() [4/7]
int16x4_t arm_compute::wrapper::vgethigh (const int16x8_t val) inline
Definition at line 42 of file gethigh.h.
vgethigh() [5/7]
uint32x2_t arm_compute::wrapper::vgethigh (const uint32x4_t val) inline
Definition at line 43 of file gethigh.h.
vgethigh() [6/7]
int32x2_t arm_compute::wrapper::vgethigh (const int32x4_t val) inline
Definition at line 44 of file gethigh.h.
vgethigh() [7/7]
float32x2_t arm_compute::wrapper::vgethigh (const float32x4_t val) inline
Definition at line 45 of file gethigh.h.
vgetlane() [1/14]
uint8_t arm_compute::wrapper::vgetlane (const uint8x8_t vector, const unsigned int lane) inline
Definition at line 91 of file getlane.h.
 {                                                                  \
vgetlane() [2/14]
int8_t arm_compute::wrapper::vgetlane (const int8x8_t vector, const unsigned int lane) inline
Definition at line 92 of file getlane.h.
 {                                                                  \
vgetlane() [3/14]
uint16_t arm_compute::wrapper::vgetlane (const uint16x4_t vector, const unsigned int lane) inline
Definition at line 93 of file getlane.h.
 {                                                                  \
vgetlane() [4/14]
int16_t arm_compute::wrapper::vgetlane (const int16x4_t vector, const unsigned int lane) inline
Definition at line 94 of file getlane.h.
 {                                                                  \
vgetlane() [5/14]
uint32_t arm_compute::wrapper::vgetlane (const uint32x2_t vector, const unsigned int lane) inline
Definition at line 95 of file getlane.h.
 {                                                                  \
vgetlane() [6/14]
int32_t arm_compute::wrapper::vgetlane (const int32x2_t vector, const unsigned int lane) inline
Definition at line 96 of file getlane.h.
 {                                                                  \
vgetlane() [7/14]
float arm_compute::wrapper::vgetlane (const float32x2_t vector, const unsigned int lane) inline
Definition at line 97 of file getlane.h.
 {                                                                  \
vgetlane() [8/14]
uint8_t arm_compute::wrapper::vgetlane (const uint8x16_t vector, const unsigned int lane) inline
Definition at line 188 of file getlane.h.
vgetlane() [9/14]
int8_t arm_compute::wrapper::vgetlane (const int8x16_t vector, const unsigned int lane) inline
Definition at line 189 of file getlane.h.
vgetlane() [10/14]
uint16_t arm_compute::wrapper::vgetlane (const uint16x8_t vector, const unsigned int lane) inline
Definition at line 190 of file getlane.h.
vgetlane() [11/14]
int16_t arm_compute::wrapper::vgetlane (const int16x8_t vector, const unsigned int lane) inline
Definition at line 191 of file getlane.h.
vgetlane() [12/14]
uint32_t arm_compute::wrapper::vgetlane (const uint32x4_t vector, const unsigned int lane) inline
Definition at line 192 of file getlane.h.
vgetlane() [13/14]
int32_t arm_compute::wrapper::vgetlane (const int32x4_t vector, const unsigned int lane) inline
Definition at line 193 of file getlane.h.
vgetlane() [14/14]
float arm_compute::wrapper::vgetlane (const float32x4_t vector, const unsigned int lane) inline
Definition at line 194 of file getlane.h.
vgetlow() [1/7]
uint8x8_t arm_compute::wrapper::vgetlow (const uint8x16_t val) inline
Definition at line 39 of file getlow.h.
Referenced by arm_compute::run_reverse().
vgetlow() [2/7]
int8x8_t arm_compute::wrapper::vgetlow (const int8x16_t val) inline
Definition at line 40 of file getlow.h.
vgetlow() [3/7]
uint16x4_t arm_compute::wrapper::vgetlow (const uint16x8_t val) inline
Definition at line 41 of file getlow.h.
vgetlow() [4/7]
int16x4_t arm_compute::wrapper::vgetlow (const int16x8_t val) inline
Definition at line 42 of file getlow.h.
vgetlow() [5/7]
uint32x2_t arm_compute::wrapper::vgetlow (const uint32x4_t val) inline
Definition at line 43 of file getlow.h.
vgetlow() [6/7]
int32x2_t arm_compute::wrapper::vgetlow (const int32x4_t val) inline
Definition at line 44 of file getlow.h.
vgetlow() [7/7]
float32x2_t arm_compute::wrapper::vgetlow (const float32x4_t val) inline
Definition at line 45 of file getlow.h.
vinv() [1/4]
float32x2_t arm_compute::wrapper::vinv (const float32x2_t & a) inline
Definition at line 46 of file inv.h.
Referenced by logistic< T, S >::operator()().
vinv() [2/4]
int32x2_t arm_compute::wrapper::vinv (const int32x2_t & a) inline
Definition at line 47 of file inv.h.
vinv() [3/4]
float32x4_t arm_compute::wrapper::vinv (const float32x4_t & a) inline
Definition at line 52 of file inv.h.
vinv() [4/4]
int32x4_t arm_compute::wrapper::vinv (const int32x4_t & a) inline
Definition at line 53 of file inv.h.
vinvsqrt() [1/2]
float32x2_t arm_compute::wrapper::vinvsqrt (const float32x2_t & a) inline
Definition at line 40 of file invsqrt.h.
vinvsqrt() [2/2]
float32x4_t arm_compute::wrapper::vinvsqrt (const float32x4_t & a) inline
Definition at line 45 of file invsqrt.h.
vload() [1/7]
uint8x8_t arm_compute::wrapper::vload (const uint8_t * ptr) inline
Definition at line 39 of file load.h.
 {                                      \
vload() [2/7]
int8x8_t arm_compute::wrapper::vload (const int8_t * ptr) inline
Definition at line 40 of file load.h.
 {                                      \
vload() [3/7]
uint16x4_t arm_compute::wrapper::vload (const uint16_t * ptr) inline
Definition at line 41 of file load.h.
 {                                      \
vload() [4/7]
int16x4_t arm_compute::wrapper::vload (const int16_t * ptr) inline
Definition at line 42 of file load.h.
 {                                      \
vload() [5/7]
uint32x2_t arm_compute::wrapper::vload (const uint32_t * ptr) inline
Definition at line 43 of file load.h.
 {                                      \
vload() [6/7]
int32x2_t arm_compute::wrapper::vload (const int32_t * ptr) inline
Definition at line 44 of file load.h.
 {                                      \
vload() [7/7]
float32x2_t arm_compute::wrapper::vload (const float * ptr) inline
Definition at line 47 of file load.h.
 {                                      \
vloadq() [1/7]
uint8x16_t arm_compute::wrapper::vloadq (const uint8_t * ptr) inline
Definition at line 58 of file load.h.
Referenced by NEHeightConcatenateLayerKernel::run(), NEWidthConcatenateLayerKernel::run(), and arm_compute::run_reverse().
vloadq() [2/7]
int8x16_t arm_compute::wrapper::vloadq (const int8_t * ptr) inline
Definition at line 59 of file load.h.
vloadq() [3/7]
uint16x8_t arm_compute::wrapper::vloadq (const uint16_t * ptr) inline
Definition at line 60 of file load.h.
vloadq() [4/7]
int16x8_t arm_compute::wrapper::vloadq (const int16_t * ptr) inline
Definition at line 61 of file load.h.
vloadq() [5/7]
uint32x4_t arm_compute::wrapper::vloadq (const uint32_t * ptr) inline
Definition at line 62 of file load.h.
vloadq() [6/7]
int32x4_t arm_compute::wrapper::vloadq (const int32_t * ptr) inline
Definition at line 63 of file load.h.
vloadq() [7/7]
float32x4_t arm_compute::wrapper::vloadq (const float * ptr) inline
Definition at line 66 of file load.h.
vlog()
float32x4_t arm_compute::wrapper::vlog (const float32x4_t & a) inline
Definition at line 40 of file log.h.
vmax() [1/14]
uint8x8_t arm_compute::wrapper::vmax (const uint8x8_t & a, const uint8x8_t & b) inline
Definition at line 39 of file max.h.
Referenced by relu< T, S >::operator()(), brelu< T, S >::operator()(), and lubrelu< T, S >::operator()().
vmax() [2/14]
int8x8_t arm_compute::wrapper::vmax (const int8x8_t & a, const int8x8_t & b) inline
Definition at line 40 of file max.h.
vmax() [3/14]
uint16x4_t arm_compute::wrapper::vmax (const uint16x4_t & a, const uint16x4_t & b) inline
Definition at line 41 of file max.h.
vmax() [4/14]
int16x4_t arm_compute::wrapper::vmax (const int16x4_t & a, const int16x4_t & b) inline
Definition at line 42 of file max.h.
vmax() [5/14]
uint32x2_t arm_compute::wrapper::vmax (const uint32x2_t & a, const uint32x2_t & b) inline
Definition at line 43 of file max.h.
vmax() [6/14]
int32x2_t arm_compute::wrapper::vmax (const int32x2_t & a, const int32x2_t & b) inline
Definition at line 44 of file max.h.
vmax() [7/14]
float32x2_t arm_compute::wrapper::vmax (const float32x2_t & a, const float32x2_t & b) inline
Definition at line 45 of file max.h.
vmax() [8/14]
uint8x16_t arm_compute::wrapper::vmax (const uint8x16_t & a, const uint8x16_t & b) inline
Definition at line 50 of file max.h.
vmax() [9/14]
int8x16_t arm_compute::wrapper::vmax (const int8x16_t & a, const int8x16_t & b) inline
Definition at line 51 of file max.h.
vmax() [10/14]
uint16x8_t arm_compute::wrapper::vmax (const uint16x8_t & a, const uint16x8_t & b) inline
Definition at line 52 of file max.h.
vmax() [11/14]
int16x8_t arm_compute::wrapper::vmax (const int16x8_t & a, const int16x8_t & b) inline
Definition at line 53 of file max.h.
vmax() [12/14]
uint32x4_t arm_compute::wrapper::vmax (const uint32x4_t & a, const uint32x4_t & b) inline
Definition at line 54 of file max.h.
vmax() [13/14]
int32x4_t arm_compute::wrapper::vmax (const int32x4_t & a, const int32x4_t & b) inline
Definition at line 55 of file max.h.
vmax() [14/14]
float32x4_t arm_compute::wrapper::vmax (const float32x4_t & a, const float32x4_t & b) inline
Definition at line 56 of file max.h.
vmin() [1/14]
uint8x8_t arm_compute::wrapper::vmin (const uint8x8_t & a, const uint8x8_t & b) inline
Definition at line 39 of file min.h.
Referenced by brelu< T, S >::operator()(), and lubrelu< T, S >::operator()().
vmin() [2/14]
int8x8_t arm_compute::wrapper::vmin (const int8x8_t & a, const int8x8_t & b) inline
Definition at line 40 of file min.h.
vmin() [3/14]
uint16x4_t arm_compute::wrapper::vmin (const uint16x4_t & a, const uint16x4_t & b) inline
Definition at line 41 of file min.h.
vmin() [4/14]
int16x4_t arm_compute::wrapper::vmin (const int16x4_t & a, const int16x4_t & b) inline
Definition at line 42 of file min.h.
vmin() [5/14]
uint32x2_t arm_compute::wrapper::vmin (const uint32x2_t & a, const uint32x2_t & b) inline
Definition at line 43 of file min.h.
vmin() [6/14]
int32x2_t arm_compute::wrapper::vmin (const int32x2_t & a, const int32x2_t & b) inline
Definition at line 44 of file min.h.
vmin() [7/14]
float32x2_t arm_compute::wrapper::vmin (const float32x2_t & a, const float32x2_t & b) inline
Definition at line 45 of file min.h.
vmin() [8/14]
uint8x16_t arm_compute::wrapper::vmin (const uint8x16_t & a, const uint8x16_t & b) inline
Definition at line 50 of file min.h.
vmin() [9/14]
int8x16_t arm_compute::wrapper::vmin (const int8x16_t & a, const int8x16_t & b) inline
Definition at line 51 of file min.h.
vmin() [10/14]
uint16x8_t arm_compute::wrapper::vmin (const uint16x8_t & a, const uint16x8_t & b) inline
Definition at line 52 of file min.h.
vmin() [11/14]
int16x8_t arm_compute::wrapper::vmin (const int16x8_t & a, const int16x8_t & b) inline
Definition at line 53 of file min.h.
vmin() [12/14]
uint32x4_t arm_compute::wrapper::vmin (const uint32x4_t & a, const uint32x4_t & b) inline
Definition at line 54 of file min.h.
vmin() [13/14]
int32x4_t arm_compute::wrapper::vmin (const int32x4_t & a, const int32x4_t & b) inline
Definition at line 55 of file min.h.
vmin() [14/14]
float32x4_t arm_compute::wrapper::vmin (const float32x4_t & a, const float32x4_t & b) inline
Definition at line 56 of file min.h.
vmla() [1/14]
uint8x8_t arm_compute::wrapper::vmla (const uint8x8_t & a, const uint8x8_t & b, const uint8x8_t & c) inline
Definition at line 46 of file mla.h.
Referenced by linear< T, S >::operator()().
vmla() [2/14]
int8x8_t arm_compute::wrapper::vmla (const int8x8_t & a, const int8x8_t & b, const int8x8_t & c) inline
Definition at line 47 of file mla.h.
vmla() [3/14]
uint16x4_t arm_compute::wrapper::vmla (const uint16x4_t & a, const uint16x4_t & b, const uint16x4_t & c) inline
Definition at line 48 of file mla.h.
vmla() [4/14]
int16x4_t arm_compute::wrapper::vmla (const int16x4_t & a, const int16x4_t & b, const int16x4_t & c) inline
Definition at line 49 of file mla.h.
vmla() [5/14]
uint32x2_t arm_compute::wrapper::vmla (const uint32x2_t & a, const uint32x2_t & b, const uint32x2_t & c) inline
Definition at line 50 of file mla.h.
vmla() [6/14]
int32x2_t arm_compute::wrapper::vmla (const int32x2_t & a, const int32x2_t & b, const int32x2_t & c) inline
Definition at line 51 of file mla.h.
vmla() [7/14]
float32x2_t arm_compute::wrapper::vmla (const float32x2_t & a, const float32x2_t & b, const float32x2_t & c) inline
Definition at line 52 of file mla.h.
vmla() [8/14]
uint8x16_t arm_compute::wrapper::vmla (const uint8x16_t & a, const uint8x16_t & b, const uint8x16_t & c) inline
Definition at line 57 of file mla.h.
vmla() [9/14]
int8x16_t arm_compute::wrapper::vmla (const int8x16_t & a, const int8x16_t & b, const int8x16_t & c) inline
Definition at line 58 of file mla.h.
vmla() [10/14]
uint16x8_t arm_compute::wrapper::vmla (const uint16x8_t & a, const uint16x8_t & b, const uint16x8_t & c) inline
Definition at line 59 of file mla.h.
vmla() [11/14]
int16x8_t arm_compute::wrapper::vmla (const int16x8_t & a, const int16x8_t & b, const int16x8_t & c) inline
Definition at line 60 of file mla.h.
vmla() [12/14]
uint32x4_t arm_compute::wrapper::vmla (const uint32x4_t & a, const uint32x4_t & b, const uint32x4_t & c) inline
Definition at line 61 of file mla.h.
vmla() [13/14]
int32x4_t arm_compute::wrapper::vmla (const int32x4_t & a, const int32x4_t & b, const int32x4_t & c) inline
Definition at line 62 of file mla.h.
vmla() [14/14]
float32x4_t arm_compute::wrapper::vmla (const float32x4_t & a, const float32x4_t & b, const float32x4_t & c) inline
Definition at line 63 of file mla.h.
vmovl() [1/6]
uint16x8_t arm_compute::wrapper::vmovl (const uint8x8_t & a) inline
Definition at line 39 of file movl.h.
vmovl() [2/6]
int16x8_t arm_compute::wrapper::vmovl (const int8x8_t & a) inline
Definition at line 40 of file movl.h.
vmovl() [3/6]
uint32x4_t arm_compute::wrapper::vmovl (const uint16x4_t & a) inline
Definition at line 41 of file movl.h.
vmovl() [4/6]
int32x4_t arm_compute::wrapper::vmovl (const int16x4_t & a) inline
Definition at line 42 of file movl.h.
vmovl() [5/6]
uint64x2_t arm_compute::wrapper::vmovl (const uint32x2_t & a) inline
Definition at line 43 of file movl.h.
vmovl() [6/6]
int64x2_t arm_compute::wrapper::vmovl (const int32x2_t & a) inline
Definition at line 44 of file movl.h.
vmovn() [1/6]
uint32x2_t arm_compute::wrapper::vmovn (const uint64x2_t & a) inline
Definition at line 39 of file movn.h.
 {                                              \
vmovn() [2/6]
int32x2_t arm_compute::wrapper::vmovn (const int64x2_t & a) inline
Definition at line 40 of file movn.h.
 {                                              \
vmovn() [3/6]
uint16x4_t arm_compute::wrapper::vmovn (const uint32x4_t & a) inline
Definition at line 41 of file movn.h.
 {                                              \
vmovn() [4/6]
int16x4_t arm_compute::wrapper::vmovn (const int32x4_t & a) inline
Definition at line 42 of file movn.h.
 {                                              \
vmovn() [5/6]
uint8x8_t arm_compute::wrapper::vmovn (const uint16x8_t & a) inline
Definition at line 43 of file movn.h.
 {                                              \
vmovn() [6/6]
int8x8_t arm_compute::wrapper::vmovn (const int16x8_t & a) inline
Definition at line 44 of file movn.h.
 {                                              \
vmul() [1/14]
uint8x8_t arm_compute::wrapper::vmul (const uint8x8_t & a, const uint8x8_t & b) inline
Definition at line 39 of file mul.h.
Referenced by square< T, S >::operator()().
vmul() [2/14]
int8x8_t arm_compute::wrapper::vmul (const int8x8_t & a, const int8x8_t & b) inline
Definition at line 40 of file mul.h.
vmul() [3/14]
uint16x4_t arm_compute::wrapper::vmul (const uint16x4_t & a, const uint16x4_t & b) inline
Definition at line 41 of file mul.h.
vmul() [4/14]
int16x4_t arm_compute::wrapper::vmul (const int16x4_t & a, const int16x4_t & b) inline
Definition at line 42 of file mul.h.
vmul() [5/14]
uint32x2_t arm_compute::wrapper::vmul (const uint32x2_t & a, const uint32x2_t & b) inline
Definition at line 43 of file mul.h.
vmul() [6/14]
int32x2_t arm_compute::wrapper::vmul (const int32x2_t & a, const int32x2_t & b) inline
Definition at line 44 of file mul.h.
vmul() [7/14]
float32x2_t arm_compute::wrapper::vmul (const float32x2_t & a, const float32x2_t & b) inline
Definition at line 45 of file mul.h.
vmul() [8/14]
uint8x16_t arm_compute::wrapper::vmul (const uint8x16_t & a, const uint8x16_t & b) inline
Definition at line 50 of file mul.h.
vmul() [9/14]
int8x16_t arm_compute::wrapper::vmul (const int8x16_t & a, const int8x16_t & b) inline
Definition at line 51 of file mul.h.
vmul() [10/14]
uint16x8_t arm_compute::wrapper::vmul (const uint16x8_t & a, const uint16x8_t & b) inline
Definition at line 52 of file mul.h.
vmul() [11/14]
int16x8_t arm_compute::wrapper::vmul (const int16x8_t & a, const int16x8_t & b) inline
Definition at line 53 of file mul.h.
vmul() [12/14]
uint32x4_t arm_compute::wrapper::vmul (const uint32x4_t & a, const uint32x4_t & b) inline
Definition at line 54 of file mul.h.
vmul() [13/14]
int32x4_t arm_compute::wrapper::vmul (const int32x4_t & a, const int32x4_t & b) inline
Definition at line 55 of file mul.h.
vmul() [14/14]
float32x4_t arm_compute::wrapper::vmul (const float32x4_t & a, const float32x4_t & b) inline
Definition at line 56 of file mul.h.
vneg() [1/8]
int8x8_t arm_compute::wrapper::vneg (const int8x8_t & a) inline
Definition at line 39 of file neg.h.
Referenced by logistic< T, S >::operator()().
vneg() [2/8]
int16x4_t arm_compute::wrapper::vneg (const int16x4_t & a) inline
Definition at line 40 of file neg.h.
vneg() [3/8]
int32x2_t arm_compute::wrapper::vneg (const int32x2_t & a) inline
Definition at line 41 of file neg.h.
vneg() [4/8]
float32x2_t arm_compute::wrapper::vneg (const float32x2_t & a) inline
Definition at line 42 of file neg.h.
vneg() [5/8]
int8x16_t arm_compute::wrapper::vneg (const int8x16_t & a) inline
Definition at line 47 of file neg.h.
vneg() [6/8]
int16x8_t arm_compute::wrapper::vneg (const int16x8_t & a) inline
Definition at line 48 of file neg.h.
vneg() [7/8]
int32x4_t arm_compute::wrapper::vneg (const int32x4_t & a) inline
Definition at line 49 of file neg.h.
vneg() [8/8]
float32x4_t arm_compute::wrapper::vneg (const float32x4_t & a) inline
Definition at line 50 of file neg.h.
vnot() [1/14]
uint8x8_t arm_compute::wrapper::vnot (const uint8x8_t & a) inline
Definition at line 39 of file not.h.
vnot() [2/14]
int8x8_t arm_compute::wrapper::vnot (const int8x8_t & a) inline
Definition at line 40 of file not.h.
vnot() [3/14]
uint16x4_t arm_compute::wrapper::vnot (const uint16x4_t & a) inline
Definition at line 41 of file not.h.
vnot() [4/14]
int16x4_t arm_compute::wrapper::vnot (const int16x4_t & a) inline
Definition at line 42 of file not.h.
vnot() [5/14]
uint32x2_t arm_compute::wrapper::vnot (const uint32x2_t & a) inline
Definition at line 43 of file not.h.
vnot() [6/14]
int32x2_t arm_compute::wrapper::vnot (const int32x2_t & a) inline
Definition at line 44 of file not.h.
vnot() [7/14]
float32x2_t arm_compute::wrapper::vnot (const float32x2_t & a) inline
Definition at line 45 of file not.h.
vnot() [8/14]
uint8x16_t arm_compute::wrapper::vnot (const uint8x16_t & a) inline
Definition at line 50 of file not.h.
vnot() [9/14]
int8x16_t arm_compute::wrapper::vnot (const int8x16_t & a) inline
Definition at line 51 of file not.h.
vnot() [10/14]
uint16x8_t arm_compute::wrapper::vnot (const uint16x8_t & a) inline
Definition at line 52 of file not.h.
vnot() [11/14]
int16x8_t arm_compute::wrapper::vnot (const int16x8_t & a) inline
Definition at line 53 of file not.h.
vnot() [12/14]
uint32x4_t arm_compute::wrapper::vnot (const uint32x4_t & a) inline
Definition at line 54 of file not.h.
vnot() [13/14]
int32x4_t arm_compute::wrapper::vnot (const int32x4_t & a) inline
Definition at line 55 of file not.h.
vnot() [14/14]
float32x4_t arm_compute::wrapper::vnot (const float32x4_t & a) inline
Definition at line 56 of file not.h.
vorr() [1/16]
uint8x8_t arm_compute::wrapper::vorr (const uint8x8_t & a, const uint8x8_t & b) inline
Definition at line 39 of file orr.h.
vorr() [2/16]
int8x8_t arm_compute::wrapper::vorr (const int8x8_t & a, const int8x8_t & b) inline
Definition at line 40 of file orr.h.
vorr() [3/16]
uint16x4_t arm_compute::wrapper::vorr (const uint16x4_t & a, const uint16x4_t & b) inline
Definition at line 41 of file orr.h.
vorr() [4/16]
int16x4_t arm_compute::wrapper::vorr (const int16x4_t & a, const int16x4_t & b) inline
Definition at line 42 of file orr.h.
vorr() [5/16]
uint32x2_t arm_compute::wrapper::vorr (const uint32x2_t & a, const uint32x2_t & b) inline
Definition at line 43 of file orr.h.
vorr() [6/16]
int32x2_t arm_compute::wrapper::vorr (const int32x2_t & a, const int32x2_t & b) inline
Definition at line 44 of file orr.h.
vorr() [7/16]
uint64x1_t arm_compute::wrapper::vorr (const uint64x1_t & a, const uint64x1_t & b) inline
Definition at line 45 of file orr.h.
vorr() [8/16]
int64x1_t arm_compute::wrapper::vorr (const int64x1_t & a, const int64x1_t & b) inline
Definition at line 46 of file orr.h.
vorr() [9/16]
uint8x16_t arm_compute::wrapper::vorr (const uint8x16_t & a, const uint8x16_t & b) inline
Definition at line 48 of file orr.h.
vorr() [10/16]
int8x16_t arm_compute::wrapper::vorr (const int8x16_t & a, const int8x16_t & b) inline
Definition at line 49 of file orr.h.
vorr() [11/16]
uint16x8_t arm_compute::wrapper::vorr (const uint16x8_t & a, const uint16x8_t & b) inline
Definition at line 50 of file orr.h.
vorr() [12/16]
int16x8_t arm_compute::wrapper::vorr (const int16x8_t & a, const int16x8_t & b) inline
Definition at line 51 of file orr.h.
vorr() [13/16]
uint32x4_t arm_compute::wrapper::vorr (const uint32x4_t & a, const uint32x4_t & b) inline
Definition at line 52 of file orr.h.
vorr() [14/16]
int32x4_t arm_compute::wrapper::vorr (const int32x4_t & a, const int32x4_t & b) inline
Definition at line 53 of file orr.h.
vorr() [15/16]
uint64x2_t arm_compute::wrapper::vorr (const uint64x2_t & a, const uint64x2_t & b) inline
Definition at line 54 of file orr.h.
vorr() [16/16]
int64x2_t arm_compute::wrapper::vorr (const int64x2_t & a, const int64x2_t & b) inline
Definition at line 55 of file orr.h.
vpadd() [1/7]
uint8x8_t arm_compute::wrapper::vpadd (const uint8x8_t & a, const uint8x8_t & b) inline
Definition at line 39 of file padd.h.
vpadd() [2/7]
int8x8_t arm_compute::wrapper::vpadd (const int8x8_t & a, const int8x8_t & b) inline
Definition at line 40 of file padd.h.
vpadd() [3/7]
uint16x4_t arm_compute::wrapper::vpadd (const uint16x4_t & a, const uint16x4_t & b) inline
Definition at line 41 of file padd.h.
vpadd() [4/7]
int16x4_t arm_compute::wrapper::vpadd (const int16x4_t & a, const int16x4_t & b) inline
Definition at line 42 of file padd.h.
vpadd() [5/7]
uint32x2_t arm_compute::wrapper::vpadd (const uint32x2_t & a, const uint32x2_t & b) inline
Definition at line 43 of file padd.h.
vpadd() [6/7]
int32x2_t arm_compute::wrapper::vpadd (const int32x2_t & a, const int32x2_t & b) inline
Definition at line 44 of file padd.h.
vpadd() [7/7]
float32x2_t arm_compute::wrapper::vpadd (const float32x2_t & a, const float32x2_t & b) inline
Definition at line 45 of file padd.h.
vpmax() [1/7]
uint8x8_t arm_compute::wrapper::vpmax (const uint8x8_t & a, const uint8x8_t & b) inline
Definition at line 39 of file pmax.h.
vpmax() [2/7]
int8x8_t arm_compute::wrapper::vpmax (const int8x8_t & a, const int8x8_t & b) inline
Definition at line 40 of file pmax.h.
vpmax() [3/7]
uint16x4_t arm_compute::wrapper::vpmax (const uint16x4_t & a, const uint16x4_t & b) inline
Definition at line 41 of file pmax.h.
vpmax() [4/7]
int16x4_t arm_compute::wrapper::vpmax (const int16x4_t & a, const int16x4_t & b) inline
Definition at line 42 of file pmax.h.
vpmax() [5/7]
uint32x2_t arm_compute::wrapper::vpmax (const uint32x2_t & a, const uint32x2_t & b) inline
Definition at line 43 of file pmax.h.
vpmax() [6/7]
int32x2_t arm_compute::wrapper::vpmax (const int32x2_t & a, const int32x2_t & b) inline
Definition at line 44 of file pmax.h.
vpmax() [7/7]
float32x2_t arm_compute::wrapper::vpmax (const float32x2_t & a, const float32x2_t & b) inline
Definition at line 45 of file pmax.h.
vpmin() [1/7]
uint8x8_t arm_compute::wrapper::vpmin (const uint8x8_t & a, const uint8x8_t & b) inline
Definition at line 39 of file pmin.h.
vpmin() [2/7]
int8x8_t arm_compute::wrapper::vpmin (const int8x8_t & a, const int8x8_t & b) inline
Definition at line 40 of file pmin.h.
vpmin() [3/7]
uint16x4_t arm_compute::wrapper::vpmin (const uint16x4_t & a, const uint16x4_t & b) inline
Definition at line 41 of file pmin.h.
vpmin() [4/7]
int16x4_t arm_compute::wrapper::vpmin (const int16x4_t & a, const int16x4_t & b) inline
Definition at line 42 of file pmin.h.
vpmin() [5/7]
uint32x2_t arm_compute::wrapper::vpmin (const uint32x2_t & a, const uint32x2_t & b) inline
Definition at line 43 of file pmin.h.
vpmin() [6/7]
int32x2_t arm_compute::wrapper::vpmin (const int32x2_t & a, const int32x2_t & b) inline
Definition at line 44 of file pmin.h.
vpmin() [7/7]
float32x2_t arm_compute::wrapper::vpmin (const float32x2_t & a, const float32x2_t & b) inline
Definition at line 45 of file pmin.h.
vpow()
float32x4_t arm_compute::wrapper::vpow (const float32x4_t & a, const float32x4_t & b) inline
Definition at line 40 of file pow.h.
vqabs() [1/6]
int8x8_t arm_compute::wrapper::vqabs (const int8x8_t & a) inline
Definition at line 63 of file abs.h.
vqabs() [2/6]
int16x4_t arm_compute::wrapper::vqabs (const int16x4_t & a) inline
Definition at line 64 of file abs.h.
vqabs() [3/6]
int32x2_t arm_compute::wrapper::vqabs (const int32x2_t & a) inline
Definition at line 65 of file abs.h.
vqabs() [4/6]
int8x16_t arm_compute::wrapper::vqabs (const int8x16_t & a) inline
Definition at line 67 of file abs.h.
vqabs() [5/6]
int16x8_t arm_compute::wrapper::vqabs (const int16x8_t & a) inline
Definition at line 68 of file abs.h.
vqabs() [6/6]
int32x4_t arm_compute::wrapper::vqabs (const int32x4_t & a) inline
Definition at line 69 of file abs.h.
vqadd() [1/18]
uint8x8_t arm_compute::wrapper::vqadd (const uint8x8_t & a, const uint8x8_t & b) inline
Definition at line 73 of file add.h.
vqadd() [2/18]
int8x8_t arm_compute::wrapper::vqadd (const int8x8_t & a, const int8x8_t & b) inline
Definition at line 74 of file add.h.
vqadd() [3/18]
uint16x4_t arm_compute::wrapper::vqadd (const uint16x4_t & a, const uint16x4_t & b) inline
Definition at line 75 of file add.h.
vqadd() [4/18]
int16x4_t arm_compute::wrapper::vqadd (const int16x4_t & a, const int16x4_t & b) inline
Definition at line 76 of file add.h.
vqadd() [5/18]
uint32x2_t arm_compute::wrapper::vqadd (const uint32x2_t & a, const uint32x2_t & b) inline
Definition at line 77 of file add.h.
vqadd() [6/18]
int32x2_t arm_compute::wrapper::vqadd (const int32x2_t & a, const int32x2_t & b) inline
Definition at line 78 of file add.h.
vqadd() [7/18]
uint64x1_t arm_compute::wrapper::vqadd (const uint64x1_t & a, const uint64x1_t & b) inline
Definition at line 79 of file add.h.
vqadd() [8/18]
int64x1_t arm_compute::wrapper::vqadd (const int64x1_t & a, const int64x1_t & b) inline
Definition at line 80 of file add.h.
vqadd() [9/18]
float32x2_t arm_compute::wrapper::vqadd (const float32x2_t & a, const float32x2_t & b) inline
Definition at line 81 of file add.h.
vqadd() [10/18]
uint8x16_t arm_compute::wrapper::vqadd (const uint8x16_t & a, const uint8x16_t & b) inline
Definition at line 86 of file add.h.
vqadd() [11/18]
int8x16_t arm_compute::wrapper::vqadd (const int8x16_t & a, const int8x16_t & b) inline
Definition at line 87 of file add.h.
vqadd() [12/18]
uint16x8_t arm_compute::wrapper::vqadd (const uint16x8_t & a, const uint16x8_t & b) inline
Definition at line 88 of file add.h.
vqadd() [13/18]
int16x8_t arm_compute::wrapper::vqadd (const int16x8_t & a, const int16x8_t & b) inline
Definition at line 89 of file add.h.
vqadd() [14/18]
uint32x4_t arm_compute::wrapper::vqadd (const uint32x4_t & a, const uint32x4_t & b) inline
Definition at line 90 of file add.h.
vqadd() [15/18]
int32x4_t arm_compute::wrapper::vqadd (const int32x4_t & a, const int32x4_t & b) inline
Definition at line 91 of file add.h.
vqadd() [16/18]
uint64x2_t arm_compute::wrapper::vqadd (const uint64x2_t & a, const uint64x2_t & b) inline
Definition at line 92 of file add.h.
vqadd() [17/18]
int64x2_t arm_compute::wrapper::vqadd (const int64x2_t & a, const int64x2_t & b) inline
Definition at line 93 of file add.h.
vqadd() [18/18]
float32x4_t arm_compute::wrapper::vqadd (const float32x4_t & a, const float32x4_t & b) inline
Definition at line 94 of file add.h.
vqmovn() [1/6]
uint32x2_t arm_compute::wrapper::vqmovn (const uint64x2_t & a) inline
Definition at line 52 of file movn.h.
vqmovn() [2/6]
int32x2_t arm_compute::wrapper::vqmovn (const int64x2_t & a) inline
Definition at line 53 of file movn.h.
vqmovn() [3/6]
uint16x4_t arm_compute::wrapper::vqmovn (const uint32x4_t & a) inline
Definition at line 54 of file movn.h.
vqmovn() [4/6]
int16x4_t arm_compute::wrapper::vqmovn (const int32x4_t & a) inline
Definition at line 55 of file movn.h.
vqmovn() [5/6]
uint8x8_t arm_compute::wrapper::vqmovn (const uint16x8_t & a) inline
Definition at line 56 of file movn.h.
vqmovn() [6/6]
int8x8_t arm_compute::wrapper::vqmovn (const int16x8_t & a) inline
Definition at line 57 of file movn.h.
vrev64() [1/14]
uint8x8_t arm_compute::wrapper::vrev64 (const uint8x8_t & a) inline
Definition at line 39 of file rev64.h.
Referenced by arm_compute::run_reverse().
vrev64() [2/14]
int8x8_t arm_compute::wrapper::vrev64 (const int8x8_t & a) inline
Definition at line 40 of file rev64.h.
vrev64() [3/14]
uint16x4_t arm_compute::wrapper::vrev64 (const uint16x4_t & a) inline
Definition at line 41 of file rev64.h.
vrev64() [4/14]
int16x4_t arm_compute::wrapper::vrev64 (const int16x4_t & a) inline
Definition at line 42 of file rev64.h.
vrev64() [5/14]
uint32x2_t arm_compute::wrapper::vrev64 (const uint32x2_t & a) inline
Definition at line 43 of file rev64.h.
vrev64() [6/14]
int32x2_t arm_compute::wrapper::vrev64 (const int32x2_t & a) inline
Definition at line 44 of file rev64.h.
vrev64() [7/14]
float32x2_t arm_compute::wrapper::vrev64 (const float32x2_t & a) inline
Definition at line 45 of file rev64.h.
vrev64() [8/14]
uint8x16_t arm_compute::wrapper::vrev64 (const uint8x16_t & a) inline
Definition at line 50 of file rev64.h.
vrev64() [9/14]
int8x16_t arm_compute::wrapper::vrev64 (const int8x16_t & a) inline
Definition at line 51 of file rev64.h.
vrev64() [10/14]
uint16x8_t arm_compute::wrapper::vrev64 (const uint16x8_t & a) inline
Definition at line 52 of file rev64.h.
vrev64() [11/14]
int16x8_t arm_compute::wrapper::vrev64 (const int16x8_t & a) inline
Definition at line 53 of file rev64.h.
vrev64() [12/14]
uint32x4_t arm_compute::wrapper::vrev64 (const uint32x4_t & a) inline
Definition at line 54 of file rev64.h.
vrev64() [13/14]
int32x4_t arm_compute::wrapper::vrev64 (const int32x4_t & a) inline
Definition at line 55 of file rev64.h.
vrev64() [14/14]
float32x4_t arm_compute::wrapper::vrev64 (const float32x4_t & a) inline
Definition at line 56 of file rev64.h.
vround()
float32x4_t arm_compute::wrapper::vround (const float32x4_t & a) inline
Definition at line 40 of file round.h.
vsetlane() [1/14]
uint8x8_t arm_compute::wrapper::vsetlane (const uint8_t value, const uint8x8_t vector, const unsigned int lane) inline
Definition at line 91 of file setlane.h.
 {                                                                                     \
vsetlane() [2/14]
int8x8_t arm_compute::wrapper::vsetlane (const int8_t value, const int8x8_t vector, const unsigned int lane) inline
Definition at line 92 of file setlane.h.
 {                                                                                     \
vsetlane() [3/14]
uint16x4_t arm_compute::wrapper::vsetlane (const uint16_t value, const uint16x4_t vector, const unsigned int lane) inline
Definition at line 93 of file setlane.h.
 {                                                                                     \
vsetlane() [4/14]
int16x4_t arm_compute::wrapper::vsetlane (const int16_t value, const int16x4_t vector, const unsigned int lane) inline
Definition at line 94 of file setlane.h.
 {                                                                                     \
vsetlane() [5/14]
uint32x2_t arm_compute::wrapper::vsetlane (const uint32_t value, const uint32x2_t vector, const unsigned int lane) inline
Definition at line 95 of file setlane.h.
 {                                                                                     \
vsetlane() [6/14]
int32x2_t arm_compute::wrapper::vsetlane (const int32_t value, const int32x2_t vector, const unsigned int lane) inline
Definition at line 96 of file setlane.h.
 {                                                                                     \
vsetlane() [7/14]
float32x2_t arm_compute::wrapper::vsetlane (const float value, const float32x2_t vector, const unsigned int lane) inline
Definition at line 97 of file setlane.h.
 {                                                                                     \
vsetlane() [8/14]
uint8x16_t arm_compute::wrapper::vsetlane (const uint8_t value, const uint8x16_t vector, const unsigned int lane) inline
Definition at line 188 of file setlane.h.
vsetlane() [9/14]
int8x16_t arm_compute::wrapper::vsetlane (const int8_t value, const int8x16_t vector, const unsigned int lane) inline
Definition at line 189 of file setlane.h.
vsetlane() [10/14]
uint16x8_t arm_compute::wrapper::vsetlane (const uint16_t value, const uint16x8_t vector, const unsigned int lane) inline
Definition at line 190 of file setlane.h.
vsetlane() [11/14]
int16x8_t arm_compute::wrapper::vsetlane (const int16_t value, const int16x8_t vector, const unsigned int lane) inline
Definition at line 191 of file setlane.h.
vsetlane() [12/14]
uint32x4_t arm_compute::wrapper::vsetlane (const uint32_t value, const uint32x4_t vector, const unsigned int lane) inline
Definition at line 192 of file setlane.h.
vsetlane() [13/14]
int32x4_t arm_compute::wrapper::vsetlane (const int32_t value, const int32x4_t vector, const unsigned int lane) inline
Definition at line 193 of file setlane.h.
vsetlane() [14/14]
float32x4_t arm_compute::wrapper::vsetlane (const float value, const float32x4_t vector, const unsigned int lane) inline
Definition at line 194 of file setlane.h.
vsin()
float32x4_t arm_compute::wrapper::vsin (const float32x4_t & a) inline
Definition at line 40 of file sin.h.
vstore() [1/14]
void arm_compute::wrapper::vstore (uint8_t * ptr, uint8x8_t val) inline
Definition at line 39 of file store.h.
Referenced by NEHeightConcatenateLayerKernel::run(), NEWidthConcatenateLayerKernel::run(), and arm_compute::run_reverse().
vstore() [2/14]
void arm_compute::wrapper::vstore (int8_t * ptr, int8x8_t val) inline
Definition at line 40 of file store.h.
vstore() [3/14]
void arm_compute::wrapper::vstore (uint16_t * ptr, uint16x4_t val) inline
Definition at line 41 of file store.h.
vstore() [4/14]
void arm_compute::wrapper::vstore (int16_t * ptr, int16x4_t val) inline
Definition at line 42 of file store.h.
vstore() [5/14]
void arm_compute::wrapper::vstore (uint32_t * ptr, uint32x2_t val) inline
Definition at line 43 of file store.h.
vstore() [6/14]
void arm_compute::wrapper::vstore (int32_t * ptr, int32x2_t val) inline
Definition at line 44 of file store.h.
vstore() [7/14]
void arm_compute::wrapper::vstore (float * ptr, float32x2_t val) inline
Definition at line 47 of file store.h.
vstore() [8/14]
void arm_compute::wrapper::vstore (uint8_t * ptr, uint8x16_t val) inline
Definition at line 52 of file store.h.
vstore() [9/14]
void arm_compute::wrapper::vstore (int8_t * ptr, int8x16_t val) inline
Definition at line 53 of file store.h.
vstore() [10/14]
void arm_compute::wrapper::vstore (uint16_t * ptr, uint16x8_t val) inline
Definition at line 54 of file store.h.
vstore() [11/14]
void arm_compute::wrapper::vstore (int16_t * ptr, int16x8_t val) inline
Definition at line 55 of file store.h.
vstore() [12/14]
void arm_compute::wrapper::vstore (uint32_t * ptr, uint32x4_t val) inline
Definition at line 56 of file store.h.
vstore() [13/14]
void arm_compute::wrapper::vstore (int32_t * ptr, int32x4_t val) inline
Definition at line 57 of file store.h.
vstore() [14/14]
void arm_compute::wrapper::vstore (float * ptr, float32x4_t val) inline
Definition at line 60 of file store.h.
vsub() [1/18]
uint8x8_t arm_compute::wrapper::vsub (const uint8x8_t & a, const uint8x8_t & b) inline
Definition at line 39 of file sub.h.
vsub() [2/18]
int8x8_t arm_compute::wrapper::vsub (const int8x8_t & a, const int8x8_t & b) inline
Definition at line 40 of file sub.h.
vsub() [3/18]
uint16x4_t arm_compute::wrapper::vsub (const uint16x4_t & a, const uint16x4_t & b) inline
Definition at line 41 of file sub.h.
vsub() [4/18]
int16x4_t arm_compute::wrapper::vsub (const int16x4_t & a, const int16x4_t & b) inline
Definition at line 42 of file sub.h.
vsub() [5/18]
uint32x2_t arm_compute::wrapper::vsub (const uint32x2_t & a, const uint32x2_t & b) inline
Definition at line 43 of file sub.h.
vsub() [6/18]
int32x2_t arm_compute::wrapper::vsub (const int32x2_t & a, const int32x2_t & b) inline
Definition at line 44 of file sub.h.
vsub() [7/18]
uint64x1_t arm_compute::wrapper::vsub (const uint64x1_t & a, const uint64x1_t & b) inline
Definition at line 45 of file sub.h.
vsub() [8/18]
int64x1_t arm_compute::wrapper::vsub (const int64x1_t & a, const int64x1_t & b) inline
Definition at line 46 of file sub.h.
vsub() [9/18]
float32x2_t arm_compute::wrapper::vsub (const float32x2_t & a, const float32x2_t & b) inline
Definition at line 47 of file sub.h.
vsub() [10/18]
uint8x16_t arm_compute::wrapper::vsub (const uint8x16_t & a, const uint8x16_t & b) inline
Definition at line 52 of file sub.h.
vsub() [11/18]
int8x16_t arm_compute::wrapper::vsub (const int8x16_t & a, const int8x16_t & b) inline
Definition at line 53 of file sub.h.
vsub() [12/18]
uint16x8_t arm_compute::wrapper::vsub (const uint16x8_t & a, const uint16x8_t & b) inline
Definition at line 54 of file sub.h.
vsub() [13/18]
int16x8_t arm_compute::wrapper::vsub (const int16x8_t & a, const int16x8_t & b) inline
Definition at line 55 of file sub.h.
vsub() [14/18]
uint32x4_t arm_compute::wrapper::vsub (const uint32x4_t & a, const uint32x4_t & b) inline
Definition at line 56 of file sub.h.
vsub() [15/18]
int32x4_t arm_compute::wrapper::vsub (const int32x4_t & a, const int32x4_t & b) inline
Definition at line 57 of file sub.h.
vsub() [16/18]
uint64x2_t arm_compute::wrapper::vsub (const uint64x2_t & a, const uint64x2_t & b) inline
Definition at line 58 of file sub.h.
vsub() [17/18]
int64x2_t arm_compute::wrapper::vsub (const int64x2_t & a, const int64x2_t & b) inline
Definition at line 59 of file sub.h.
vsub() [18/18]
float32x4_t arm_compute::wrapper::vsub (const float32x4_t & a, const float32x4_t & b) inline
Definition at line 60 of file sub.h.
vtanh()
float32x4_t arm_compute::wrapper::vtanh (const float32x4_t & a) inline
Definition at line 40 of file tanh.h.