Compute Library: arm_compute::graph Namespace Reference
arm_compute::graph Namespace Reference
Namespaces
backends
descriptors
detail
frontend
Data Structures
class ActivationLayerNode
Activation Layer node.
class BatchNormalizationLayerNode
Batch Normalization Layer node.
class BoundingBoxTransformLayerNode
Bounding Box Transform Layer node.
class ChannelShuffleLayerNode
Channel Shuffle Layer node.
class ConcatenateLayerNode
Concatenation Layer node.
class ConstNode
Const node.
class ConvolutionLayerNode
Convolution Layer node.
class DeconvolutionLayerNode
Deconvolution Layer node.
class DefaultNodeVisitor
Default visitor implementation.
class DepthConcatSubTensorMutator
Mutation pass to optimize depth concatenation operations by using sub-tensors.
class DepthwiseConvolutionLayerNode
Depthwise Convolution Layer node.
class DetectionOutputLayerNode
DetectionOutput Layer node.
class DotGraphPrinter
Graph printer interface.
class DotGraphVisitor
Graph printer visitor.
class DummyNode
Dummy Layer node.
class Edge
Graph Edge.
class EltwiseLayerNode
Eltwise Layer node.
struct ExecutionTask
Execution task.
struct ExecutionWorkload
Execution workload.
class FlattenLayerNode
Flatten Layer node.
class FullyConnectedLayerNode
Fully Connected Layer node.
class FusedConvolutionBatchNormalizationNode
Batch Normalization node.
class GenerateProposalsLayerNode
Generate Proposals Layer node.
class Graph
Graph class.
class GraphBuilder
Graph builder class.
struct GraphConfig
Graph configuration structure Device target types.
class GraphContext
Graph context.
class GraphManager
Graph manager class.
class GroupedConvolutionMutator
Mutation pass to implement/optimize grouped convolutions.
class IGraphMutator
Graph mutator interface.
class IGraphPrinter
Graph printer interface.
class INode
Node interface.
class INodeVisitor
Node visitor interface.
class InPlaceOperationMutator
Mutation pass to optimize operations that can be performed in-place.
class InputNode
Input Layer node.
class ITensorAccessor
Tensor accessor interface.
class ITensorHandle
Tensor handle interface object.
struct MemoryManagerContext
Contains structs required for memory management.
class NodeExecutionMethodMutator
Mutation pass to fall-back to default execution method.
class NodeFusionMutator
Mutation pass to fuss nodes.
struct NodeIdxPair
NodeID-index struct.
struct NodeParams
Common node parameters.
class NormalizationLayerNode
Normalization Layer node.
class NormalizePlanarYUVLayerNode
Batch Normalization Layer node.
class OutputNode
Output Layer node.
class PadLayerNode
Pad Layer node.
class PassManager
Pass manager.
class PermuteLayerNode
Permute Layer node.
class PoolingLayerNode
Pooling Layer node.
class PriorBoxLayerNode
PriorBox Layer node.
class ReorgLayerNode
Reorg Layer node.
class ReshapeLayerNode
Reshape Layer node.
class ResizeLayerNode
Resize Layer node.
class ROIAlignLayerNode
ROI Align node.
class SliceLayerNode
Slice Layer node.
class SoftmaxLayerNode
Softmax Layer node.
class SplitLayerNode
Split Layer node.
class SplitLayerSubTensorMutator
Mutation pass to optimize split operations by using sub-tensors.
class StackLayerNode
Stack Layer node.
class TaskExecutor
Task executor.
class Tensor
Tensor object.
struct TensorDescriptor
Tensor metadata class.
class UpsampleLayerNode
Upsample Layer node.
class YOLOLayerNode
YOLO Layer node.
Typedefs
using ITensorAccessorUPtr = std::unique_ptr< ITensorAccessor >
using GraphID = unsigned int
using TensorID = unsigned int
using NodeID = unsigned int
using EdgeID = unsigned int
using Activation = arm_compute::ActivationLayerInfo::ActivationFunction
Constant TensorID specifying an equivalent of null tensor.
Enumerations
enum Target { UNSPECIFIED, NEON, CL, GC }
enum EltwiseOperation { Add, Sub, Mul }
Supported Element-wise operations.
enum ConvolutionMethod { Default, GEMM, Direct, Winograd }
Supported Convolution layer methods.
enum DepthwiseConvolutionMethod { Default, GEMV, Optimized3x3 }
Supported Depthwise Convolution layer methods.
enum FastMathHint { Enabled, Disabled }
Enable or disable fast math for Convolution layer.
enum NodeType {
ActivationLayer, BatchNormalizationLayer, BoundingBoxTransformLayer, ChannelShuffleLayer,
ConcatenateLayer, ConvolutionLayer, DeconvolutionLayer, DepthwiseConvolutionLayer,
DetectionOutputLayer, EltwiseLayer, FlattenLayer, FullyConnectedLayer,
FusedConvolutionBatchNormalizationLayer, GenerateProposalsLayer, NormalizationLayer, NormalizePlanarYUVLayer,
PadLayer, PermuteLayer, PoolingLayer, PriorBoxLayer,
ReorgLayer, ReshapeLayer, ResizeLayer, ROIAlignLayer,
SoftmaxLayer, SliceLayer, SplitLayer, StackLayer,
UpsampleLayer, YOLOLayer, Input, Output,
Const, Dummy
}
Supported nodes.
enum MemoryManagerAffinity { Buffer, Offset }
Backend Memory Manager affinity.
Functions
std::vector< NodeID > bfs (Graph &g)
Breadth first search traversal.
std::vector< NodeID > dfs (Graph &g)
Depth first search traversal.
Target target_from_name (const std::string &name)
Converts a string to a strong types enumeration Target.
inline ::std::istream & operator>> (::std::istream &stream, Target &target)
Input Stream operator for Target.
ConvolutionMethod Convolution_method_from_name (const std::string &name)
Converts a string to a strong types enumeration ConvolutionMethod.
inline ::std::istream & operator>> (::std::istream &stream, ConvolutionMethod &target)
Input Stream operator for ConvolutionMethod.
DepthwiseConvolutionMethod depthwise_convolution_method_from_name (const std::string &name)
Converts a string to a strong types enumeration DepthwiseConvolutionMethod.
inline ::std::istream & operator>> (::std::istream &stream, DepthwiseConvolutionMethod &target)
Input Stream operator for DepthwiseConvolutionMethod.
inline ::std::ostream & operator<< (::std::ostream &os, const Target &target)
Formatted output of the Target.
inline ::std::ostream & operator<< (::std::ostream &os, const NodeType &node_type)
inline ::std::ostream & operator<< (::std::ostream &os, const EltwiseOperation &eltwise_op)
Formatted output of the EltwiseOperation type.
inline ::std::ostream & operator<< (::std::ostream &os, const ConvolutionMethod &method)
Formatted output of the ConvolutionMethod type.
inline ::std::ostream & operator<< (::std::ostream &os, const FastMathHint &hint)
Formatted output of the FastMathHint type.
inline ::std::ostream & operator<< (::std::ostream &os, const DepthwiseConvolutionMethod &method)
Formatted output of the DepthwiseConvolutionMethod type.
TensorDescriptor get_tensor_descriptor (const Graph &g, TensorID tid)
Returns the tensor descriptor of a given tensor.
Status set_tensor_accessor (Tensor *tensor, std::unique_ptr< ITensorAccessor > accessor)
Sets an accessor on a given tensor.
bool is_target_supported (Target target)
Checks if a specific target is supported.
Target get_default_target ()
Returns default target for execution.
void force_target_to_graph (Graph &g, Target target)
Forces a single target to all graph constructs.
PassManager create_default_pass_manager (Target target)
Creates a default PassManager.
void setup_requested_backend_context (GraphContext &ctx, Target target)
Setups requested backend context if it exists, is supported and hasn't been initialized already.
void release_default_graph_context (GraphContext &ctx)
Default releases the graph context if not done manually.
size_t get_dimension_size (const TensorDescriptor &descriptor, const DataLayoutDimension data_layout_dimension)
Get size of a tensor's given dimension depending on its layout.
size_t get_dimension_idx (DataLayout data_layout, const DataLayoutDimension data_layout_dimension)
Get index of a tensor's given dimension depending on its layout.
std::vector< NodeIdxPair > get_driving_nodes (const INode &node)
Get the list of driving nodes of a given node.
void configure_tensor (Tensor *tensor)
Configures tensor.
void execute_task (ExecutionTask &task)
Variables
constexpr TensorID NullTensorID = std::numeric_limits<TensorID>::max()
Constant NodeID specifying an equivalent of null node.
constexpr NodeID EmptyNodeID = std::numeric_limits<NodeID>::max()
Constant EdgeID specifying an equivalent of null edge.
constexpr EdgeID EmptyEdgeID = std::numeric_limits<EdgeID>::max()
Typedef Documentation
Activation
using Activation = arm_compute::ActivationLayerInfo::ActivationFunction
Constant TensorID specifying an equivalent of null tensor.
Definition at line 67 of file Types.h.
EdgeID
using EdgeID = unsigned int
Definition at line 64 of file Types.h.
GraphID
using GraphID = unsigned int
Definition at line 61 of file Types.h.
ITensorAccessorUPtr
using ITensorAccessorUPtr = std::unique_ptr<ITensorAccessor>
Definition at line 50 of file ITensorAccessor.h.
NodeID
using NodeID = unsigned int
Definition at line 63 of file Types.h.
TensorID
using TensorID = unsigned int
Definition at line 62 of file Types.h.
Enumeration Type Documentation
ConvolutionMethod
enum ConvolutionMethod strong
Supported Convolution layer methods.
Enumerator
Default
Default approach using internal heuristics.
GEMM
GEMM based convolution.
Direct
Deep direct convolution.
Winograd
Winograd based convolution.
Definition at line 105 of file Types.h.
 {
     Default,
     GEMM,
     Direct,
     Winograd
 };
DepthwiseConvolutionMethod
enum DepthwiseConvolutionMethod strong
Supported Depthwise Convolution layer methods.
Enumerator
Default
Default approach using internal heuristics.
GEMV
Generic GEMV based depthwise convolution.
Optimized3x3
Optimized 3x3 direct depthwise convolution.
Definition at line 114 of file Types.h.
 {
     Default,
     GEMV,
     Optimized3x3,
 };
EltwiseOperation
enum EltwiseOperation strong
Supported Element-wise operations.
Enumerator
Add
Arithmetic addition.
Sub
Arithmetic subtraction.
Mul
Arithmetic multiplication.
Definition at line 97 of file Types.h.
 {
     Add,
     Sub,
     Mul
 };
FastMathHint
enum FastMathHint strong
Enable or disable fast math for Convolution layer.
Enumerator
Enabled
Fast math enabled for Convolution layer.
Disabled
Fast math disabled for Convolution layer.
Definition at line 122 of file Types.h.
 {
     Enabled,
     Disabled,
 };
MemoryManagerAffinity
enum MemoryManagerAffinity strong
Backend Memory Manager affinity.
Enumerator
Buffer
Affinity at buffer level.
Offset
Affinity at offset level.
Definition at line 170 of file Types.h.
 {
     Buffer,
     Offset
 };
NodeType
enum NodeType strong
Supported nodes.
Enumerator
ActivationLayer
BatchNormalizationLayer
BoundingBoxTransformLayer
ChannelShuffleLayer
ConcatenateLayer
ConvolutionLayer
DeconvolutionLayer
DepthwiseConvolutionLayer
DetectionOutputLayer
EltwiseLayer
FlattenLayer
FullyConnectedLayer
FusedConvolutionBatchNormalizationLayer
GenerateProposalsLayer
NormalizationLayer
NormalizePlanarYUVLayer
PadLayer
PermuteLayer
PoolingLayer
PriorBoxLayer
ReorgLayer
ReshapeLayer
ResizeLayer
ROIAlignLayer
SoftmaxLayer
SliceLayer
SplitLayer
StackLayer
UpsampleLayer
YOLOLayer
Input
Output
Const
Dummy
Definition at line 129 of file Types.h.
 {
     ActivationLayer,
     BatchNormalizationLayer,
     BoundingBoxTransformLayer,
     ChannelShuffleLayer,
     ConcatenateLayer,
     ConvolutionLayer,
     DeconvolutionLayer,
     DepthwiseConvolutionLayer,
     DetectionOutputLayer,
     EltwiseLayer,
     FlattenLayer,
     FullyConnectedLayer,
     FusedConvolutionBatchNormalizationLayer,
     GenerateProposalsLayer,
     NormalizationLayer,
     NormalizePlanarYUVLayer,
     PadLayer,
     PermuteLayer,
     PoolingLayer,
     PriorBoxLayer,
     ReorgLayer,
     ReshapeLayer,
     ResizeLayer,
     ROIAlignLayer,
     SoftmaxLayer,
     SliceLayer,
     SplitLayer,
     StackLayer,
     UpsampleLayer,
     YOLOLayer,
     Input,
     Output,
     Const,
     Dummy
 };
Target
enum Target strong
Enumerator
UNSPECIFIED
Unspecified Target.
NEON
NEON capable target device.
CL
OpenCL capable target device.
GC
GLES compute capable target device.
Definition at line 88 of file Types.h.
 {
     UNSPECIFIED,
     NEON,
     CL,
     GC,
 };
Function Documentation
bfs()
std::vector< NodeID > bfs (Graph & g)
Breadth first search traversal.
Parameters
g Graph to traverse
Returns
A vector with the node id traversal order
Definition at line 72 of file TopologicalSort.cpp.
 {
     std::vector<NodeID> bfs_order_vector;
     // Created visited vector
     std::vector<bool> visited(g.nodes().size(), false);
     // Create BFS queue
     std::list<NodeID> queue;
     // Push inputs and mark as visited
     for(auto &input : g.nodes(NodeType::Input))
     {
         if(input != EmptyNodeID)
         {
             visited[input] = true;
             queue.push_back(input);
         }
     }
     // Push const nodes and mark as visited
     for(auto &const_node : g.nodes(NodeType::Const))
     {
         if(const_node != EmptyNodeID)
         {
             visited[const_node] = true;
             queue.push_back(const_node);
         }
     }
     // Iterate over vector and edges
     while(!queue.empty())
     {
         // Dequeue a node from queue and process
         NodeID n = queue.front();
         bfs_order_vector.push_back(n);
         queue.pop_front();
         const INode *node = g.node(n);
         ARM_COMPUTE_ERROR_ON(node == nullptr);
         for(const auto &eid : node->output_edges())
         {
             const Edge *e = g.edge(eid);
             ARM_COMPUTE_ERROR_ON(e == nullptr);
             if(!visited[e->consumer_id()] && detail::all_inputs_are_visited(e->consumer(), visited))
             {
                 visited[e->consumer_id()] = true;
                 queue.push_back(e->consumer_id());
             }
         }
     }
     return bfs_order_vector;
 }
References arm_compute::graph::detail::all_inputs_are_visited(), ARM_COMPUTE_ERROR_ON, Const, Edge::consumer(), Edge::consumer_id(), Graph::edge(), EmptyNodeID, Input, Graph::node(), Graph::nodes(), and INode::output_edges().
configure_tensor()
void configure_tensor (Tensor * tensor)
Configures tensor.
Parameters
[in,out] tensor Tensor to configure
Definition at line 174 of file Utils.cpp.
 {
     if(tensor != nullptr && tensor->handle() == nullptr)
     {
         Target                         target  = tensor->desc().target;
         backends::IDeviceBackend      &backend = backends::BackendRegistry::get().get_backend(target);
         std::unique_ptr<ITensorHandle> handle  = backend.create_tensor(*tensor);
         ARM_COMPUTE_ERROR_ON_MSG(!handle, "Couldn't create backend handle!");
         tensor->set_handle(std::move(handle));
     }
 }
References ARM_COMPUTE_ERROR_ON_MSG, IDeviceBackend::create_tensor(), Tensor::desc(), BackendRegistry::get(), BackendRegistry::get_backend(), Tensor::handle(), Tensor::set_handle(), and TensorDescriptor::target.
Referenced by arm_compute::graph::detail::fuse_convolution_with_batch_normalization(), and GroupedConvolutionMutator::mutate().
Convolution_method_from_name()
ConvolutionMethod Convolution_method_from_name (const std::string & name)
Converts a string to a strong types enumeration ConvolutionMethod.
Parameters
[in] name String to convert
Returns
Converted Target enumeration
Definition at line 104 of file TypeLoader.cpp.
 {
     static const std::map<std::string, ConvolutionMethod> methods =
     {
         { "default", ConvolutionMethod::Default },
         { "direct", ConvolutionMethod::Direct },
         { "gemm", ConvolutionMethod::GEMM },
         { "winograd", ConvolutionMethod::Winograd },
     };
 #ifndef ARM_COMPUTE_EXCEPTIONS_DISABLED
     try
     {
 #endif /* ARM_COMPUTE_EXCEPTIONS_DISABLED */
         return methods.at(arm_compute::utility::tolower(name));
 #ifndef ARM_COMPUTE_EXCEPTIONS_DISABLED
     }
     catch(const std::out_of_range &)
     {
         throw std::invalid_argument(name);
     }
 #endif /* ARM_COMPUTE_EXCEPTIONS_DISABLED */
 }
References Default, Direct, GEMM, arm_compute::utility::tolower(), and Winograd.
create_default_pass_manager()
PassManager create_default_pass_manager (Target target)
Creates a default PassManager.
Parameters
[in] target Target to create the pass manager for
Returns
A PassManager with default mutating passes
Definition at line 77 of file Utils.cpp.
 {
     PassManager pm;
     const bool is_target_gc = target == Target::GC;
     // Passes that mutate graph IR
     pm.append(support::cpp14::make_unique<NodeFusionMutator>(), !is_target_gc);
     pm.append(support::cpp14::make_unique<GroupedConvolutionMutator>());
     pm.append(support::cpp14::make_unique<InPlaceOperationMutator>(), !is_target_gc);
     // Passes that mutate backend information
     pm.append(support::cpp14::make_unique<DepthConcatSubTensorMutator>(), !is_target_gc);
     pm.append(support::cpp14::make_unique<SplitLayerSubTensorMutator>(), !is_target_gc);
     pm.append(support::cpp14::make_unique<NodeExecutionMethodMutator>());
     return pm;
 }
References PassManager::append(), and GC.
Referenced by Stream::finalize().
depthwise_convolution_method_from_name()
DepthwiseConvolutionMethod depthwise_convolution_method_from_name (const std::string & name)
Converts a string to a strong types enumeration DepthwiseConvolutionMethod.
Parameters
[in] name String to convert
Returns
Converted Target enumeration
Definition at line 129 of file TypeLoader.cpp.
 {
     static const std::map<std::string, DepthwiseConvolutionMethod> methods =
     {
         { "default", DepthwiseConvolutionMethod::Default },
         { "gemv", DepthwiseConvolutionMethod::GEMV },
         { "optimized3x3", DepthwiseConvolutionMethod::Optimized3x3 },
     };
 #ifndef ARM_COMPUTE_EXCEPTIONS_DISABLED
     try
     {
 #endif /* ARM_COMPUTE_EXCEPTIONS_DISABLED */
         return methods.at(arm_compute::utility::tolower(name));
 #ifndef ARM_COMPUTE_EXCEPTIONS_DISABLED
     }
     catch(const std::out_of_range &)
     {
         throw std::invalid_argument(name);
     }
 #endif /* ARM_COMPUTE_EXCEPTIONS_DISABLED */
 }
References Default, GEMV, Optimized3x3, and arm_compute::utility::tolower().
dfs()
std::vector< NodeID > dfs (Graph & g)
Depth first search traversal.
Parameters
g Graph to traverse
Returns
A vector with the node id traversal order
Definition at line 127 of file TopologicalSort.cpp.
 {
     std::vector<NodeID> dfs_order_vector;
     // Created visited vector
     std::vector<bool> visited(g.nodes().size(), false);
     // Create DFS stack
     std::stack<NodeID> stack;
     // Push inputs and mark as visited
     for(auto &input : g.nodes(NodeType::Input))
     {
         if(input != EmptyNodeID)
         {
             visited[input] = true;
             stack.push(input);
         }
     }
     // Push const nodes and mark as visited
     for(auto &const_node : g.nodes(NodeType::Const))
     {
         if(const_node != EmptyNodeID)
         {
             visited[const_node] = true;
             stack.push(const_node);
         }
     }
     // Iterate over vector and edges
     while(!stack.empty())
     {
         // Pop a node from stack and process
         NodeID n = stack.top();
         dfs_order_vector.push_back(n);
         stack.pop();
         // Mark node as visited
         if(!visited[n])
         {
             visited[n] = true;
         }
         const INode *node = g.node(n);
         ARM_COMPUTE_ERROR_ON(node == nullptr);
         // Reverse iterate to push branches from right to left and pop on the opposite order
         for(const auto &eid : arm_compute::utils::iterable::reverse_iterate(node->output_edges()))
         {
             const Edge *e = g.edge(eid);
             ARM_COMPUTE_ERROR_ON(e == nullptr);
             if(!visited[e->consumer_id()] && detail::all_inputs_are_visited(e->consumer(), visited))
             {
                 stack.push(e->consumer_id());
             }
         }
     }
     return dfs_order_vector;
 }
References arm_compute::graph::detail::all_inputs_are_visited(), ARM_COMPUTE_ERROR_ON, Const, Edge::consumer(), Edge::consumer_id(), Graph::edge(), EmptyNodeID, Input, Graph::node(), Graph::nodes(), INode::output_edges(), and arm_compute::utils::iterable::reverse_iterate().
Referenced by GraphManager::finalize_graph(), SplitLayerSubTensorMutator::mutate(), and DepthConcatSubTensorMutator::mutate().
execute_task()
void execute_task (ExecutionTask & task)
Definition at line 38 of file Workload.cpp.
 {
     if(task.task)
     {
         task.task->run();
     }
 }
References ExecutionTask::task.
force_target_to_graph()
void force_target_to_graph (Graph & g, Target target)
Forces a single target to all graph constructs.
Parameters
[in] g Graph to force target on
[in] target Target to force
Definition at line 56 of file Utils.cpp.
 {
     auto &nodes = g.nodes();
     for(auto &node : nodes)
     {
         if(node)
         {
             node->set_assigned_target(target);
         }
     }
     auto &tensors = g.tensors();
     for(auto &tensor : tensors)
     {
         if(tensor)
         {
             tensor->desc().target = target;
         }
     }
 }
References Graph::nodes(), and Graph::tensors().
Referenced by GraphManager::finalize_graph().
get_default_target()
Target get_default_target ()
Returns default target for execution.
Note
If an OpenCL backend exists then OpenCL is returned, else if the NEON backend exists returns NEON as target. If no backends are registered an error is raised.
Returns
Default target
Definition at line 39 of file Utils.cpp.
 {
     if(is_target_supported(Target::NEON))
     {
         return Target::NEON;
     }
     if(is_target_supported(Target::CL))
     {
         return Target::CL;
     }
     if(is_target_supported(Target::GC))
     {
         return Target::GC;
     }
     ARM_COMPUTE_ERROR("No backend exists!");
 }
References ARM_COMPUTE_ERROR, CL, GC, is_target_supported(), and NEON.
Referenced by GraphManager::finalize_graph().
get_dimension_idx()
size_t get_dimension_idx (DataLayout data_layout, const DataLayoutDimension data_layout_dimension)
Get index of a tensor's given dimension depending on its layout.
Parameters
[in] data_layout Data layout of the tensor
[in] data_layout_dimension Tensor data layout dimension
Returns
Idx of given dimension
Definition at line 125 of file Utils.cpp.
 {
     ARM_COMPUTE_ERROR_ON_MSG(data_layout == DataLayout::UNKNOWN, "Cannot retrieve the dimension index for an unknown layout!");
     /* Return the index based on the data layout
      * [N C H W]
      * [3 2 1 0]
      * [N H W C]
      */
     switch(data_layout_dimension)
     {
         case DataLayoutDimension::CHANNEL:
             return (data_layout == DataLayout::NCHW) ? 2 : 0;
             break;
         case DataLayoutDimension::HEIGHT:
             return (data_layout == DataLayout::NCHW) ? 1 : 2;
             break;
         case DataLayoutDimension::WIDTH:
             return (data_layout == DataLayout::NCHW) ? 0 : 1;
             break;
         case DataLayoutDimension::BATCHES:
             return 3;
             break;
         default:
             ARM_COMPUTE_ERROR("Data layout index not supported!");
             break;
     }
 }
References ARM_COMPUTE_ERROR, ARM_COMPUTE_ERROR_ON_MSG, arm_compute::BATCHES, arm_compute::CHANNEL, arm_compute::HEIGHT, arm_compute::NCHW, arm_compute::UNKNOWN, and arm_compute::WIDTH.
Referenced by GraphBuilder::add_convolution_node(), GraphBuilder::add_deconvolution_node(), GraphBuilder::add_depthwise_convolution_node(), GraphBuilder::add_scale_layer(), ConcatenateLayerNode::compute_output_descriptor(), PoolingLayerNode::compute_output_descriptor(), ReorgLayerNode::compute_output_descriptor(), UpsampleLayerNode::compute_output_descriptor(), DeconvolutionLayerNode::compute_output_descriptor(), FusedConvolutionBatchNormalizationNode::compute_output_descriptor(), DepthwiseConvolutionLayerNode::compute_output_descriptor(), ConvolutionLayerNode::compute_output_descriptor(), ResizeLayerNode::configure_output(), arm_compute::graph::backends::detail::create_concatenate_layer(), get_dimension_size(), and DepthConcatSubTensorMutator::mutate().
get_dimension_size()
size_t get_dimension_size (const TensorDescriptor & descriptor, const DataLayoutDimension data_layout_dimension)
Get size of a tensor's given dimension depending on its layout.
Parameters
[in] descriptor Descriptor
[in] data_layout_dimension Tensor data layout dimension
Returns
Size of requested dimension
Definition at line 119 of file Utils.cpp.
 {
     ARM_COMPUTE_ERROR_ON_MSG(descriptor.layout == DataLayout::UNKNOWN, "Cannot retrieve the dimension index for an unknown layout!");
     return descriptor.shape[get_dimension_idx(descriptor.layout, data_layout_dimension)];
 }
References ARM_COMPUTE_ERROR_ON_MSG, get_dimension_idx(), TensorDescriptor::layout, TensorDescriptor::shape, and arm_compute::UNKNOWN.
Referenced by GraphBuilder::add_batch_normalization_node(), GraphBuilder::add_convolution_node(), GraphBuilder::add_deconvolution_node(), GraphBuilder::add_depthwise_convolution_node(), GraphBuilder::add_normalize_planar_yuv_node(), PoolingLayerNode::compute_output_descriptor(), PriorBoxLayerNode::compute_output_descriptor(), ReorgLayerNode::compute_output_descriptor(), UpsampleLayerNode::compute_output_descriptor(), DeconvolutionLayerNode::compute_output_descriptor(), FusedConvolutionBatchNormalizationNode::compute_output_descriptor(), DepthwiseConvolutionLayerNode::compute_output_descriptor(), and ConvolutionLayerNode::compute_output_descriptor().
get_driving_nodes()
std::vector< NodeIdxPair > get_driving_nodes (const INode & node)
Get the list of driving nodes of a given node.
Parameters
[in] node Node to find the driving node of
Returns
A list with the driving node of a given node
Definition at line 154 of file Utils.cpp.
 {
     std::vector<NodeIdxPair> driving_nodes;
     const Graph *g = node.graph();
     ARM_COMPUTE_ERROR_ON(g == nullptr);
     for(auto &output_edge_id : node.output_edges())
     {
         auto output_edge = g->edge(output_edge_id);
         if(output_edge != nullptr)
         {
             ARM_COMPUTE_ERROR_ON(output_edge->consumer() == nullptr);
             driving_nodes.push_back({ output_edge->consumer_id(), output_edge->consumer_idx() });
         }
     }
     return driving_nodes;
 }
References ARM_COMPUTE_ERROR_ON, Graph::edge(), INode::graph(), and INode::output_edges().
Referenced by arm_compute::graph::detail::fuse_convolution_with_batch_normalization(), arm_compute::graph::detail::fuse_node_with_activation(), and GroupedConvolutionMutator::mutate().
get_tensor_descriptor()
TensorDescriptor arm_compute::graph::get_tensor_descriptor (const Graph & g, TensorID tid) inline
Returns the tensor descriptor of a given tensor.
Parameters
[in] g Graph that the tensor belongs to
[in] tid Tensor ID
Returns
Tensor descriptor if tensor was found else empty descriptor
Definition at line 44 of file Utils.h.
 {
     const Tensor *tensor = g.tensor(tid);
     return (tensor != nullptr) ? tensor->desc() : TensorDescriptor();
 }
References Tensor::desc(), and Graph::tensor().
Referenced by GraphBuilder::add_batch_normalization_node(), GraphBuilder::add_convolution_node(), GraphBuilder::add_deconvolution_node(), GraphBuilder::add_depthwise_convolution_node(), GraphBuilder::add_fully_connected_layer(), GraphBuilder::add_normalize_planar_yuv_node(), and GraphBuilder::add_scale_layer().
is_target_supported()
bool is_target_supported (Target target)
Checks if a specific target is supported.
Parameters
[in] target Target to check
Returns
True if target is support else false
Definition at line 34 of file Utils.cpp.
 {
     return backends::BackendRegistry::get().contains(target) && backends::BackendRegistry::get().find_backend(target)->is_backend_supported();
 }
References BackendRegistry::contains(), BackendRegistry::find_backend(), BackendRegistry::get(), and IDeviceBackend::is_backend_supported().
Referenced by GraphManager::finalize_graph(), get_default_target(), DepthConcatSubTensorMutator::mutate(), and SplitLayerSubTensorMutator::mutate().
operator<<() [1/6]
inline ::std::ostream& arm_compute::graph::operator<< (::std::ostream & os, const Target & target)
Formatted output of the Target.
Definition at line 38 of file TypePrinter.h.
 {
     switch(target)
     {
         case Target::UNSPECIFIED:
             os << "UNSPECIFIED";
             break;
         case Target::NEON:
             os << "NEON";
             break;
         case Target::CL:
             os << "CL";
             break;
         case Target::GC:
             os << "GC";
             break;
         default:
             ARM_COMPUTE_ERROR("NOT_SUPPORTED!");
     }
     return os;
 }
References ARM_COMPUTE_ERROR, CL, GC, NEON, and UNSPECIFIED.
operator<<() [2/6]
inline ::std::ostream& arm_compute::graph::operator<< (::std::ostream & os, const NodeType & node_type)
Definition at line 61 of file TypePrinter.h.
 {
     switch(node_type)
     {
         case NodeType::ActivationLayer:
             os << "ActivationLayer";
             break;
         case NodeType::BatchNormalizationLayer:
             os << "BatchNormalizationLayer";
             break;
         case NodeType::BoundingBoxTransformLayer:
             os << "BoundingBoxTransformLayer";
             break;
         case NodeType::ChannelShuffleLayer:
             os << "ChannelShuffleLayer";
             break;
         case NodeType::ConcatenateLayer:
             os << "ConcatenateLayer";
             break;
         case NodeType::ConvolutionLayer:
             os << "ConvolutionLayer";
             break;
         case NodeType::DeconvolutionLayer:
             os << "DeconvolutionLayer";
             break;
         case NodeType::DetectionOutputLayer:
             os << "DetectionOutputLayer";
             break;
         case NodeType::DepthwiseConvolutionLayer:
             os << "DepthwiseConvolutionLayer";
             break;
         case NodeType::EltwiseLayer:
             os << "EltwiseLayer";
             break;
         case NodeType::FlattenLayer:
             os << "FlattenLayer";
             break;
         case NodeType::FullyConnectedLayer:
             os << "FullyConnectedLayer";
             break;
         case NodeType::FusedConvolutionBatchNormalizationLayer:
             os << "FusedConvolutionBatchNormalizationLayer";
             break;
         case NodeType::GenerateProposalsLayer:
             os << "GenerateProposalsLayer";
             break;
         case NodeType::NormalizationLayer:
             os << "NormalizationLayer";
             break;
         case NodeType::NormalizePlanarYUVLayer:
             os << "NormalizePlanarYUVLayer";
             break;
         case NodeType::PadLayer:
             os << "PadLayer";
             break;
         case NodeType::PermuteLayer:
             os << "PermuteLayer";
             break;
         case NodeType::PoolingLayer:
             os << "PoolingLayer";
             break;
         case NodeType::PriorBoxLayer:
             os << "PriorBoxLayer";
             break;
         case NodeType::ReorgLayer:
             os << "ReorgLayer";
             break;
         case NodeType::ReshapeLayer:
             os << "ReshapeLayer";
             break;
         case NodeType::ResizeLayer:
             os << "ResizeLayer";
             break;
         case NodeType::ROIAlignLayer:
             os << "ROIAlignLayer";
             break;
         case NodeType::SoftmaxLayer:
             os << "SoftmaxLayer";
             break;
         case NodeType::SliceLayer:
             os << "SliceLayer";
             break;
         case NodeType::SplitLayer:
             os << "SplitLayer";
             break;
         case NodeType::StackLayer:
             os << "StackLayer";
             break;
         case NodeType::UpsampleLayer:
             os << "UpsampleLayer";
             break;
         case NodeType::YOLOLayer:
             os << "YOLOLayer";
             break;
         case NodeType::Input:
             os << "Input";
             break;
         case NodeType::Output:
             os << "Output";
             break;
         case NodeType::Const:
             os << "Const";
             break;
         case NodeType::Dummy:
             os << "Dummy";
             break;
         default:
             ARM_COMPUTE_ERROR("NOT_SUPPORTED!");
     }
     return os;
 }
References ActivationLayer, ARM_COMPUTE_ERROR, BatchNormalizationLayer, BoundingBoxTransformLayer, ChannelShuffleLayer, ConcatenateLayer, Const, ConvolutionLayer, DeconvolutionLayer, DepthwiseConvolutionLayer, DetectionOutputLayer, Dummy, EltwiseLayer, FlattenLayer, FullyConnectedLayer, FusedConvolutionBatchNormalizationLayer, GenerateProposalsLayer, Input, NormalizationLayer, NormalizePlanarYUVLayer, Output, PadLayer, PermuteLayer, PoolingLayer, PriorBoxLayer, ReorgLayer, ReshapeLayer, ResizeLayer, ROIAlignLayer, SliceLayer, SoftmaxLayer, SplitLayer, StackLayer, UpsampleLayer, and YOLOLayer.
operator<<() [3/6]
inline ::std::ostream& arm_compute::graph::operator<< (::std::ostream & os, const EltwiseOperation & eltwise_op)
Formatted output of the EltwiseOperation type.
Definition at line 175 of file TypePrinter.h.
 {
     switch(eltwise_op)
     {
         case EltwiseOperation::Add:
             os << "Add";
             break;
         case EltwiseOperation::Mul:
             os << "Mul";
             break;
         case EltwiseOperation::Sub:
             os << "Sub";
             break;
         default:
             ARM_COMPUTE_ERROR("NOT_SUPPORTED!");
     }
     return os;
 }
References Add, ARM_COMPUTE_ERROR, Mul, and Sub.
operator<<() [4/6]
inline ::std::ostream& arm_compute::graph::operator<< (::std::ostream & os, const ConvolutionMethod & method)
Formatted output of the ConvolutionMethod type.
Definition at line 196 of file TypePrinter.h.
 {
     switch(method)
     {
         case ConvolutionMethod::Default:
             os << "Default";
             break;
         case ConvolutionMethod::Direct:
             os << "Direct";
             break;
         case ConvolutionMethod::GEMM:
             os << "GEMM";
             break;
         case ConvolutionMethod::Winograd:
             os << "Winograd";
             break;
         default:
             ARM_COMPUTE_ERROR("NOT_SUPPORTED!");
     }
     return os;
 }
References ARM_COMPUTE_ERROR, Default, Direct, GEMM, and Winograd.
operator<<() [5/6]
inline ::std::ostream& arm_compute::graph::operator<< (::std::ostream & os, const FastMathHint & hint)
Formatted output of the FastMathHint type.
Definition at line 220 of file TypePrinter.h.
 {
     switch(hint)
     {
         case FastMathHint::Enabled:
             os << "Enabled";
             break;
         case FastMathHint::Disabled:
             os << "Disabled";
             break;
         default:
             ARM_COMPUTE_ERROR("NOT_SUPPORTED!");
     }
     return os;
 }
References ARM_COMPUTE_ERROR, Disabled, and Enabled.
operator<<() [6/6]
inline ::std::ostream& arm_compute::graph::operator<< (::std::ostream & os, const DepthwiseConvolutionMethod & method)
Formatted output of the DepthwiseConvolutionMethod type.
Definition at line 238 of file TypePrinter.h.
 {
     switch(method)
     {
         case DepthwiseConvolutionMethod::Default:
             os << "DEFAULT";
             break;
         case DepthwiseConvolutionMethod::GEMV:
             os << "GEMV";
             break;
         case DepthwiseConvolutionMethod::Optimized3x3:
             os << "Optimized3x3";
             break;
         default:
             ARM_COMPUTE_ERROR("NOT_SUPPORTED!");
     }
     return os;
 }
References ARM_COMPUTE_ERROR, Default, GEMV, and Optimized3x3.
operator>>() [1/3]
inline ::std::istream& arm_compute::graph::operator>> (::std::istream & stream, Target & target)
Input Stream operator for Target.
Parameters
[in] stream Stream to parse
[out] target Output target
Returns
Updated stream
Definition at line 96 of file TypeLoader.h.
 {
     std::string value;
     stream >> value;
     target = target_from_name(value);
     return stream;
 }
operator>>() [2/3]
inline ::std::istream& arm_compute::graph::operator>> (::std::istream & stream, ConvolutionMethod & target)
Input Stream operator for ConvolutionMethod.
Parameters
[in] stream Stream to parse
[out] target Output target
Returns
Updated stream
Definition at line 119 of file TypeLoader.h.
 {
     std::string value;
     stream >> value;
     target = Convolution_method_from_name(value);
     return stream;
 }
operator>>() [3/3]
inline ::std::istream& arm_compute::graph::operator>> (::std::istream & stream, DepthwiseConvolutionMethod & target)
Input Stream operator for DepthwiseConvolutionMethod.
Parameters
[in] stream Stream to parse
[out] target Output target
Returns
Updated stream
Definition at line 142 of file TypeLoader.h.
 {
     std::string value;
     stream >> value;
     target = depthwise_convolution_method_from_name(value);
     return stream;
 }
release_default_graph_context()
void release_default_graph_context (GraphContext & ctx)
Default releases the graph context if not done manually.
Parameters
[in,out] ctx Graph Context
Definition at line 96 of file Utils.cpp.
 {
     for(const auto &backend : backends::BackendRegistry::get().backends())
     {
         if(backend.second->is_backend_supported())
         {
             backend.second->release_backend_context(ctx);
         }
     }
 }
References BackendRegistry::get().
Referenced by GraphContext::~GraphContext().
set_tensor_accessor()
Status arm_compute::graph::set_tensor_accessor (Tensor * tensor, std::unique_ptr< ITensorAccessor > accessor) inline
Sets an accessor on a given tensor.
Parameters
[in] tensor Tensor to set the accessor to
[in] accessor Accessor to set
Returns
True if accessor was set else false
Definition at line 56 of file Utils.h.
 {
     ARM_COMPUTE_RETURN_ERROR_ON(tensor == nullptr);
     tensor->set_accessor(std::move(accessor));
     return Status{};
 }
References ARM_COMPUTE_RETURN_ERROR_ON, and Tensor::set_accessor().
setup_requested_backend_context()
void setup_requested_backend_context (GraphContext & ctx, Target target)
Setups requested backend context if it exists, is supported and hasn't been initialized already.
Parameters
[in,out] ctx Graph Context.
[in] target Target to setup the backend for.
Definition at line 107 of file Utils.cpp.
 {
     if(backends::BackendRegistry::get().contains(target))
     {
         const auto &backend = backends::BackendRegistry::get().find_backend(target);
         if(backend->is_backend_supported())
         {
             backend->setup_backend_context(ctx);
         }
     }
 }
References BackendRegistry::find_backend(), BackendRegistry::get(), and IDeviceBackend::setup_backend_context().
Referenced by GraphManager::finalize_graph().
target_from_name()
Target target_from_name (const std::string & name)
Converts a string to a strong types enumeration Target.
Parameters
[in] name String to convert
Returns
Converted Target enumeration
Definition at line 80 of file TypeLoader.cpp.
 {
     static const std::map<std::string, Target> targets =
     {
         { "neon", Target::NEON },
         { "cl", Target::CL },
         { "gc", Target::GC },
     };
 #ifndef ARM_COMPUTE_EXCEPTIONS_DISABLED
     try
     {
 #endif /* ARM_COMPUTE_EXCEPTIONS_DISABLED */
         return targets.at(arm_compute::utility::tolower(name));
 #ifndef ARM_COMPUTE_EXCEPTIONS_DISABLED
     }
     catch(const std::out_of_range &)
     {
         throw std::invalid_argument(name);
     }
 #endif /* ARM_COMPUTE_EXCEPTIONS_DISABLED */
 }
References CL, GC, NEON, and arm_compute::utility::tolower().
Variable Documentation
EmptyEdgeID
constexpr EdgeID EmptyEdgeID = std::numeric_limits<EdgeID>::max()
Definition at line 72 of file Types.h.
Referenced by ActivationLayerNode::ActivationLayerNode(), BatchNormalizationLayerNode::BatchNormalizationLayerNode(), BoundingBoxTransformLayerNode::BoundingBoxTransformLayerNode(), ChannelShuffleLayerNode::ChannelShuffleLayerNode(), ConcatenateLayerNode::ConcatenateLayerNode(), StackLayerNode::configure_output(), ConcatenateLayerNode::configure_output(), ConvolutionLayerNode::ConvolutionLayerNode(), DeconvolutionLayerNode::DeconvolutionLayerNode(), DepthwiseConvolutionLayerNode::DepthwiseConvolutionLayerNode(), DetectionOutputLayerNode::DetectionOutputLayerNode(), DummyNode::DummyNode(), EltwiseLayerNode::EltwiseLayerNode(), FlattenLayerNode::FlattenLayerNode(), FullyConnectedLayerNode::FullyConnectedLayerNode(), FusedConvolutionBatchNormalizationNode::FusedConvolutionBatchNormalizationNode(), GenerateProposalsLayerNode::GenerateProposalsLayerNode(), NormalizationLayerNode::NormalizationLayerNode(), NormalizePlanarYUVLayerNode::NormalizePlanarYUVLayerNode(), OutputNode::OutputNode(), PadLayerNode::PadLayerNode(), PermuteLayerNode::PermuteLayerNode(), PoolingLayerNode::PoolingLayerNode(), PriorBoxLayerNode::PriorBoxLayerNode(), Graph::remove_connection(), ReorgLayerNode::ReorgLayerNode(), ReshapeLayerNode::ReshapeLayerNode(), ResizeLayerNode::ResizeLayerNode(), ROIAlignLayerNode::ROIAlignLayerNode(), SliceLayerNode::SliceLayerNode(), SoftmaxLayerNode::SoftmaxLayerNode(), SplitLayerNode::SplitLayerNode(), StackLayerNode::StackLayerNode(), UpsampleLayerNode::UpsampleLayerNode(), and YOLOLayerNode::YOLOLayerNode().
EmptyNodeID
constexpr NodeID EmptyNodeID = std::numeric_limits<NodeID>::max()
Constant EdgeID specifying an equivalent of null edge.
Definition at line 70 of file Types.h.
Referenced by GraphBuilder::add_batch_normalization_node(), GraphBuilder::add_convolution_node(), GraphBuilder::add_deconvolution_node(), GraphBuilder::add_depthwise_convolution_node(), GraphBuilder::add_fully_connected_layer(), arm_compute::graph::detail::all_inputs_are_visited(), bfs(), Edge::consumer_id(), ConcatLayer::create_layer(), FullyConnectedLayer::create_layer(), StackLayer::create_layer(), dfs(), GroupedConvolutionMutator::mutate(), and Edge::producer_id().
NullTensorID
constexpr TensorID NullTensorID = std::numeric_limits<TensorID>::max()
Constant NodeID specifying an equivalent of null node.
Definition at line 68 of file Types.h.
Referenced by ActivationLayerNode::ActivationLayerNode(), Graph::add_connection(), BatchNormalizationLayerNode::BatchNormalizationLayerNode(), BoundingBoxTransformLayerNode::BoundingBoxTransformLayerNode(), ChannelShuffleLayerNode::ChannelShuffleLayerNode(), ConcatenateLayerNode::ConcatenateLayerNode(), ConstNode::ConstNode(), ConvolutionLayerNode::ConvolutionLayerNode(), DeconvolutionLayerNode::DeconvolutionLayerNode(), DepthwiseConvolutionLayerNode::DepthwiseConvolutionLayerNode(), DetectionOutputLayerNode::DetectionOutputLayerNode(), DummyNode::DummyNode(), EltwiseLayerNode::EltwiseLayerNode(), FlattenLayerNode::FlattenLayerNode(), NormalizePlanarYUVLayerNode::forward_descriptors(), FlattenLayerNode::forward_descriptors(), ConstNode::forward_descriptors(), InputNode::forward_descriptors(), ReshapeLayerNode::forward_descriptors(), SoftmaxLayerNode::forward_descriptors(), NormalizationLayerNode::forward_descriptors(), ChannelShuffleLayerNode::forward_descriptors(), GenerateProposalsLayerNode::forward_descriptors(), BoundingBoxTransformLayerNode::forward_descriptors(), PadLayerNode::forward_descriptors(), PermuteLayerNode::forward_descriptors(), DummyNode::forward_descriptors(), ActivationLayerNode::forward_descriptors(), ResizeLayerNode::forward_descriptors(), YOLOLayerNode::forward_descriptors(), ROIAlignLayerNode::forward_descriptors(), PriorBoxLayerNode::forward_descriptors(), PoolingLayerNode::forward_descriptors(), DetectionOutputLayerNode::forward_descriptors(), ReorgLayerNode::forward_descriptors(), StackLayerNode::forward_descriptors(), BatchNormalizationLayerNode::forward_descriptors(), UpsampleLayerNode::forward_descriptors(), EltwiseLayerNode::forward_descriptors(), DeconvolutionLayerNode::forward_descriptors(), SliceLayerNode::forward_descriptors(), SplitLayerNode::forward_descriptors(), ConcatenateLayerNode::forward_descriptors(), FullyConnectedLayerNode::forward_descriptors(), DepthwiseConvolutionLayerNode::forward_descriptors(), ConvolutionLayerNode::forward_descriptors(), FusedConvolutionBatchNormalizationNode::forward_descriptors(), IStream::forward_tail(), FullyConnectedLayerNode::FullyConnectedLayerNode(), FusedConvolutionBatchNormalizationNode::FusedConvolutionBatchNormalizationNode(), GenerateProposalsLayerNode::GenerateProposalsLayerNode(), INode::input_id(), InputNode::InputNode(), NormalizationLayerNode::NormalizationLayerNode(), NormalizePlanarYUVLayerNode::NormalizePlanarYUVLayerNode(), PadLayerNode::PadLayerNode(), PermuteLayerNode::PermuteLayerNode(), PoolingLayerNode::PoolingLayerNode(), PriorBoxLayerNode::PriorBoxLayerNode(), ReorgLayerNode::ReorgLayerNode(), ReshapeLayerNode::ReshapeLayerNode(), ResizeLayerNode::ResizeLayerNode(), ROIAlignLayerNode::ROIAlignLayerNode(), INode::set_output_tensor(), SliceLayerNode::SliceLayerNode(), SoftmaxLayerNode::SoftmaxLayerNode(), SplitLayerNode::SplitLayerNode(), StackLayerNode::StackLayerNode(), Edge::tensor_id(), UpsampleLayerNode::UpsampleLayerNode(), and YOLOLayerNode::YOLOLayerNode().