Compute Library: arm_compute::test::gles_compute Namespace Reference
arm_compute::test::gles_compute Namespace Reference
Functions
GCTensor create_tensor (const TensorShape &shape, DataType data_type, int num_channels=1, int fixed_point_position=0)
Helper to create an empty tensor.
GCTensor create_tensor (const std::string &name, DataType data_type)
Helper to create an empty tensor.
void print_tensor (ITensor &tensor, const std::string &name, IOFormatInfo info=IOFormatInfo(IOFormatInfo::PrintRegion::Full))
Helper to print tensor.
Function Documentation
GCTensor arm_compute::test::gles_compute::create_tensor (const TensorShape & shape, DataType data_type, int num_channels = 1, int fixed_point_position = 0) inline
Helper to create an empty tensor.
Parameters
[in] shape Desired shape.
[in] data_type Desired data type.
[in] num_channels (Optional) It indicates the number of channels for each tensor element
[in] fixed_point_position (Optional) Fixed point position that expresses the number of bits for the fractional part of the number when the tensor's data type is QS8 or QS16.
Returns
Empty GCTensor with the specified shape and data type.
Definition at line 49 of file Helper.h.
References GCTensor::allocator(), and ITensorAllocator::init().
 {
     GCTensor tensor;
     tensor.allocator()->init(TensorInfo(shape, num_channels, data_type, fixed_point_position));
     return tensor;
 }
GCTensor arm_compute::test::gles_compute::create_tensor (const std::string & name, DataType data_type) inline
Helper to create an empty tensor.
Parameters
[in] name File name from which to get the dimensions.
[in] data_type Desired data type.
Returns
Empty GCTensor with the specified shape and data type.
Definition at line 64 of file Helper.h.
References GCTensor::allocator(), arm_compute::test::validation::data_type, ITensorAllocator::init(), arm_compute::test::library, and SimpleTensor< T >::shape().
 {
     constexpr unsigned int num_channels = 1;
     const RawTensor &raw = library->get(name);
     GCTensor tensor;
     tensor.allocator()->init(TensorInfo(raw.shape(), num_channels, data_type));
     return tensor;
 }
void arm_compute::test::gles_compute::print_tensor (ITensor & tensor, const std::string & name, IOFormatInfo info = IOFormatInfo(IOFormatInfo::PrintRegion::Full)) inline
Helper to print tensor.
Parameters
[in] tensor Tensor to print.
[in] name Tensor name.
[in] info Format information.
Returns
Empty GCTensor with the specified shape and data type.
Definition at line 84 of file Helper.h.
References arm_compute::test::validation::info(), IGCTensor::map(), ITensor::print(), and IGCTensor::unmap().
 {
     std::ostringstream s;
     IGCTensor         &t = dynamic_cast<IGCTensor &>(tensor);
     t.map();
     t.print(s, info);
     std::cout << name << ":" << std::endl;
     std::cout << s.str().c_str();
     t.unmap();
 }