ARM Compute Library: examples/neon_scale.cpp File Reference
neon_scale.cpp File Reference
#include "arm_compute/runtime/NEON/NEFunctions.h"
#include "arm_compute/core/Types.h"
#include "test_helpers/Utils.h"
Functions
void main_neon_scale (int argc, const char **argv)
int main (int argc, const char **argv)
Main program for convolution test.
Function Documentation
int main (int argc, const char ** argv)
Main program for convolution test.
Parameters
[in] argc Number of arguments
[in] argv Arguments ([optional] Path to PPM image to process)
Definition at line 86 of file neon_scale.cpp.
References main_neon_scale(), and test_helpers::run_example().
 {
     return test_helpers::run_example(argc, argv, main_neon_scale);
 }
void main_neon_scale (int argc, const char ** argv)
Definition at line 32 of file neon_scale.cpp.
References NEScale::configure(), PPMLoader::fill_image(), PPMLoader::init_image(), PPMLoader::is_open(), arm_compute::NEAREST_NEIGHBOR, PPMLoader::open(), INESimpleFunction::run(), test_helpers::save_to_ppm(), arm_compute::U8, and arm_compute::UNDEFINED.
Referenced by main().
 {
     PPMLoader ppm;
     Image     src, dst;
     if(argc < 2)
     {
         // Print help
         std::cout << "Usage: ./build/neon_scale[input_image.ppm]\n\n";
         std::cout << "No input_image provided, creating a dummy 640x480 image\n";
         // Create an empty grayscale 640x480 image
         src.allocator()->init(TensorInfo(640, 480, Format::U8));
     }
     else
     {
         ppm.open(argv[1]);
         ppm.init_image(src, Format::U8);
     }
     constexpr int scale_factor = 2;
     TensorInfo dst_tensor_info(src.info()->dimension(0) / scale_factor, src.info()->dimension(1) / scale_factor, Format::U8);
     // Configure the destination image
     dst.allocator()->init(dst_tensor_info);
     // Create and initialize a Scale function object:
     NEScale scale;
     scale.configure(&src, &dst, InterpolationPolicy::NEAREST_NEIGHBOR, BorderMode::UNDEFINED);
     // Allocate all the images
     src.allocator()->allocate();
     dst.allocator()->allocate();
     // Fill the input image with the content of the PPM image if a filename was provided:
     if(ppm.is_open())
     {
         ppm.fill_image(src);
     }
     // Run the scale operation:
     scale.run();
     // Save the result to file:
     if(ppm.is_open())
     {
         const std::string output_filename = std::string(argv[1]) + "_out.ppm";
         save_to_ppm(dst, output_filename);
     }
 }