Compute Library: examples/neon_cartoon_effect.cpp File Reference
neon_cartoon_effect.cpp File Reference
#include "arm_compute/runtime/NEON/NEFunctions.h"
#include "arm_compute/core/Types.h"
#include "utils/Utils.h"
Functions
void main_neon_cartoon_effect (int argc, const char **argv)
int main (int argc, const char **argv)
Main program for cartoon effect test.
Function Documentation
int main (int argc, const char ** argv)
Main program for cartoon effect test.
Parameters
[in] argc Number of arguments
[in] argv Arguments ([optional] Path to PPM image to process)
Definition at line 100 of file neon_cartoon_effect.cpp.
References main_neon_cartoon_effect(), and arm_compute::utils::run_example().
 {
     return utils::run_example(argc, argv, main_neon_cartoon_effect);
 }
void main_neon_cartoon_effect (int argc, const char ** argv)
Definition at line 33 of file neon_cartoon_effect.cpp.
References NEArithmeticSubtraction::configure(), NEGaussian5x5::configure(), NECannyEdge::configure(), PPMLoader::fill_image(), PPMLoader::init_image(), PPMLoader::is_open(), PPMLoader::open(), arm_compute::REPLICATE, INESimpleFunction::run(), NEGaussian5x5::run(), NECannyEdge::run(), arm_compute::SATURATE, arm_compute::utils::save_to_ppm(), arm_compute::test::fixed_point_arithmetic::detail::sub(), and arm_compute::U8.
Referenced by main().
 {
     // Open PPM file
     PPMLoader ppm;
     Image     src_img;
     Image     dst_img;
     Image     gaus5x5_img;
     Image     canny_edge_img;
     if(argc < 2)
     {
         // Print help
         std::cout << "Usage: ./build/neon_cartoon_effect [input_image.ppm]\n\n";
         std::cout << "No input_image provided, creating a dummy 640x480 image\n";
         // Create an empty grayscale 640x480 image
         src_img.allocator()->init(TensorInfo(640, 480, Format::U8));
     }
     else
     {
         ppm.open(argv[1]);
         ppm.init_image(src_img, Format::U8);
     }
     // Initialize just the dimensions and format of the images:
     gaus5x5_img.allocator()->init(*src_img.info());
     canny_edge_img.allocator()->init(*src_img.info());
     dst_img.allocator()->init(*src_img.info());
     NEGaussian5x5           gaus5x5;
     NECannyEdge             canny_edge;
     NEArithmeticSubtraction sub;
     // Configure the functions to call
     gaus5x5.configure(&src_img, &gaus5x5_img, BorderMode::REPLICATE);
     canny_edge.configure(&src_img, &canny_edge_img, 100, 80, 3, 1, BorderMode::REPLICATE);
     sub.configure(&gaus5x5_img, &canny_edge_img, &dst_img, ConvertPolicy::SATURATE);
     // Now that the padding requirements are known we can allocate the images:
     src_img.allocator()->allocate();
     dst_img.allocator()->allocate();
     gaus5x5_img.allocator()->allocate();
     canny_edge_img.allocator()->allocate();
     // Fill the input image with the content of the PPM image if a filename was provided:
     if(ppm.is_open())
     {
         ppm.fill_image(src_img);
     }
     // Execute the functions:
     gaus5x5.run();
     canny_edge.run();
     sub.run();
     // Save the result to file:
     if(ppm.is_open())
     {
         const std::string output_filename = std::string(argv[1]) + "_out.ppm";
         save_to_ppm(dst_img, output_filename);
     }
 }