Compute Library: src/core/CL/cl_kernels/non_linear_filter_helpers.h File Reference
non_linear_filter_helpers.h File Reference
Macros
#define SORT(a, b)
Sorts element-wise two vectors.
Functions
uchar8 sort5 (uchar8 p0, uchar8 p1, uchar8 p2, uchar8 p3, uchar8 p4)
Sorting network to sort 5 vectors of 8 elements and return their median.
uchar8 sort9 (uchar8 p0, uchar8 p1, uchar8 p2, uchar8 p3, uchar8 p4, uchar8 p5, uchar8 p6, uchar8 p7, uchar8 p8)
Sorting network to sort 9 vectors of 8 elements and return their median.
uchar8 row_reduce_min_3 (uchar16 val)
Calculate the minimum of a sliding window of size 3.
uchar8 row_reduce_max_3 (uchar16 val)
Calculate the maximum of a sliding window of size 3.
uchar8 row_reduce_min_5 (uchar16 val)
Calculate the minimum of a sliding window of size 5.
uchar8 row_reduce_max_5 (uchar16 val)
Calculate the maximum of a sliding window of size 5.
Macro Definition Documentation
SORT
#define SORT (a, b)
Value:
{                               \
        uchar8 min_val = min(a, b); \
        uchar8 max_val = max(a, b); \
        a              = min_val;   \
        b              = max_val;   \
    }
Sorts element-wise two vectors.
Parameters
[in,out] a First vector
[in,out] b Second vector
Definition at line 30 of file non_linear_filter_helpers.h.
Function Documentation
row_reduce_max_3()
uchar8 row_reduce_max_3 (uchar16 val) inline
Calculate the maximum of a sliding window of size 3.
Parameters
val Values to calculate the maximum values
Returns
Maximum values of 8 elements on a sliding window of size 3.
Definition at line 120 of file non_linear_filter_helpers.h.
 {
     return max(val.s01234567, max(val.s12345678, val.s23456789));
 }
Referenced by non_linear_filter_box3x3(), non_linear_filter_cross3x3(), non_linear_filter_disk3x3(), and non_linear_filter_disk5x5().
row_reduce_max_5()
uchar8 row_reduce_max_5 (uchar16 val) inline
Calculate the maximum of a sliding window of size 5.
Parameters
val Values to calculate the maximum values
Returns
Maximum values of 8 elements on a sliding window of size 5.
Definition at line 142 of file non_linear_filter_helpers.h.
 {
     return max(val.s01234567, max(max(val.s12345678, val.s23456789), max(val.s3456789A, val.s456789AB)));
 }
Referenced by non_linear_filter_box5x5(), non_linear_filter_cross5x5(), and non_linear_filter_disk5x5().
row_reduce_min_3()
uchar8 row_reduce_min_3 (uchar16 val) inline
Calculate the minimum of a sliding window of size 3.
Parameters
val Values to calculate the minimum values
Returns
Minimum values of 8 elements on a sliding window of size 3.
Definition at line 109 of file non_linear_filter_helpers.h.
 {
     return min(val.s01234567, min(val.s12345678, val.s23456789));
 }
Referenced by non_linear_filter_box3x3(), non_linear_filter_cross3x3(), non_linear_filter_disk3x3(), and non_linear_filter_disk5x5().
row_reduce_min_5()
uchar8 row_reduce_min_5 (uchar16 val) inline
Calculate the minimum of a sliding window of size 5.
Parameters
val Values to calculate the minimum values
Returns
Minimum values of 8 elements on a sliding window of size 5.
Definition at line 131 of file non_linear_filter_helpers.h.
 {
     return min(val.s01234567, min(min(val.s12345678, val.s23456789), min(val.s3456789A, val.s456789AB)));
 }
Referenced by non_linear_filter_box5x5(), non_linear_filter_cross5x5(), and non_linear_filter_disk5x5().
sort5()
uchar8 sort5 (uchar8 p0, uchar8 p1, uchar8 p2, uchar8 p3, uchar8 p4) inline
Sorting network to sort 5 vectors of 8 elements and return their median.
Parameters
[in] p0 First element vector
[in] p1 Second element vector
[in] p2 Third element vector
[in] p3 Fourth element vector
[in] p4 Fifth element vector
Returns
Median values for 8 elements.
Definition at line 50 of file non_linear_filter_helpers.h.
 {
     SORT(p0, p1);
     SORT(p2, p3);
     SORT(p0, p2);
     SORT(p1, p3);
     SORT(p1, p2);
     SORT(p0, p4);
     SORT(p1, p4);
     SORT(p2, p4);
     return p2;
 }
References SORT.
Referenced by non_linear_filter_cross3x3().
sort9()
uchar8 sort9 (uchar8 p0, uchar8 p1, uchar8 p2, uchar8 p3, uchar8 p4, uchar8 p5, uchar8 p6, uchar8 p7, uchar8 p8) inline
Sorting network to sort 9 vectors of 8 elements and return their median.
Parameters
[in] p0 First element vector
[in] p1 Second element vector
[in] p2 Third element vector
[in] p3 Fourth element vector
[in] p4 Fifth element vector
[in] p5 Sixth element vector
[in] p6 Seventh element vector
[in] p7 Eigth element vector
[in] p8 Ninth element vector
Returns
Median values for 8 elements.
Definition at line 78 of file non_linear_filter_helpers.h.
 {
     SORT(p1, p2);
     SORT(p4, p5);
     SORT(p7, p8);
     SORT(p0, p1);
     SORT(p3, p4);
     SORT(p6, p7);
     SORT(p1, p2);
     SORT(p4, p5);
     SORT(p7, p8);
     SORT(p0, p3);
     SORT(p5, p8);
     SORT(p4, p7);
     SORT(p3, p6);
     SORT(p1, p4);
     SORT(p2, p5);
     SORT(p4, p7);
     SORT(p4, p2);
     SORT(p6, p4);
     SORT(p4, p2);
     return p4;
 }
References SORT.
Referenced by non_linear_filter_box3x3(), non_linear_filter_cross5x5(), and non_linear_filter_disk3x3().