Compute Library: src/core/CL/cl_kernels/non_linear_filter3x3.cl File Reference
non_linear_filter3x3.cl File Reference
#include "helpers.h"
#include "non_linear_filter_helpers.h"
Functions
__kernel void non_linear_filter_box3x3 (__global uchar *src_ptr, uint src_stride_x, uint src_step_x, uint src_stride_y, uint src_step_y, uint src_offset_first_element_in_bytes, __global uchar *dst_ptr, uint dst_stride_x, uint dst_step_x, uint dst_stride_y, uint dst_step_y, uint dst_offset_first_element_in_bytes)
This function applies a non linear filter on a 3x3 box basis on an input image.
__kernel void non_linear_filter_cross3x3 (__global uchar *src_ptr, uint src_stride_x, uint src_step_x, uint src_stride_y, uint src_step_y, uint src_offset_first_element_in_bytes, __global uchar *dst_ptr, uint dst_stride_x, uint dst_step_x, uint dst_stride_y, uint dst_step_y, uint dst_offset_first_element_in_bytes)
This function applies a non linear filter on a 3x3 cross basis on an input image.
__kernel void non_linear_filter_disk3x3 (__global uchar *src_ptr, uint src_stride_x, uint src_step_x, uint src_stride_y, uint src_step_y, uint src_offset_first_element_in_bytes, __global uchar *dst_ptr, uint dst_stride_x, uint dst_step_x, uint dst_stride_y, uint dst_step_y, uint dst_offset_first_element_in_bytes)
This function applies a non linear filter on a 3x3 disk basis on an input image.
Function Documentation
__kernel void non_linear_filter_box3x3 (__global uchar * src_ptr, uint src_stride_x, uint src_step_x, uint src_stride_y, uint src_step_y, uint src_offset_first_element_in_bytes, __global uchar * dst_ptr, uint dst_stride_x, uint dst_step_x, uint dst_stride_y, uint dst_step_y, uint dst_offset_first_element_in_bytes)
This function applies a non linear filter on a 3x3 box basis on an input image.
Note
The needed filter operation is defined through the preprocessor by passing either -DMIN, -DMAX or -DMEDIAN.
Parameters
[in] src_ptr Pointer to the source image. Supported data types: U8
[in] src_stride_x Stride of the source image in X dimension (in bytes)
[in] src_step_x src_stride_x * number of elements along X processed per workitem(in bytes)
[in] src_stride_y Stride of the source image in Y dimension (in bytes)
[in] src_step_y src_stride_y * number of elements along Y processed per workitem(in bytes)
[in] src_offset_first_element_in_bytes The offset of the first element in the source image
[out] dst_ptr Pointer to the destination image. Supported data types: U8
[in] dst_stride_x Stride of the destination image in X dimension (in bytes)
[in] dst_step_x dst_stride_x * number of elements along X processed per workitem(in bytes)
[in] dst_stride_y Stride of the destination image in Y dimension (in bytes)
[in] dst_step_y dst_stride_y * number of elements along Y processed per workitem(in bytes)
[in] dst_offset_first_element_in_bytes The offset of the first element in the destination image
Definition at line 44 of file non_linear_filter3x3.cl.
References CONVERT_TO_IMAGE_STRUCT, arm_compute::test::validation::dst, arm_compute::test::fixed_point_arithmetic::detail::max(), arm_compute::test::fixed_point_arithmetic::detail::min(), offset(), Image::ptr, row_reduce_max_3(), row_reduce_min_3(), sort9(), and arm_compute::test::validation::src.
 {
     Image src = CONVERT_TO_IMAGE_STRUCT(src);
     Image dst = CONVERT_TO_IMAGE_STRUCT(dst);
     // Load values
     uchar16 top    = vload16(0, offset(&src, -1, -1));
     uchar16 middle = vload16(0, offset(&src, -1, 0));
     uchar16 bottom = vload16(0, offset(&src, -1, 1));
     // Apply respective filter
 #ifdef MIN
     uchar16 tmp = min(top, min(middle, bottom));
     uchar8  out = row_reduce_min_3(tmp);
 #elif defined(MAX)
     uchar16 tmp = max(top, max(middle, bottom));
     uchar8  out = row_reduce_max_3(tmp);
 #elif defined(MEDIAN)
     uchar8 p0  = top.s01234567;
     uchar8 p1  = top.s12345678;
     uchar8 p2  = top.s23456789;
     uchar8 p3  = middle.s01234567;
     uchar8 p4  = middle.s12345678;
     uchar8 p5  = middle.s23456789;
     uchar8 p6  = bottom.s01234567;
     uchar8 p7  = bottom.s12345678;
     uchar8 p8  = bottom.s23456789;
     uchar8 out = sort9(p0, p1, p2, p3, p4, p5, p6, p7, p8);
 #else /* MIN or MAX or MEDIAN */
 #error "Unsupported filter function"
 #endif /* MIN or MAX or MEDIAN */
     // Store result
     vstore8(out, 0, dst.ptr);
 }
__kernel void non_linear_filter_cross3x3 (__global uchar * src_ptr, uint src_stride_x, uint src_step_x, uint src_stride_y, uint src_step_y, uint src_offset_first_element_in_bytes, __global uchar * dst_ptr, uint dst_stride_x, uint dst_step_x, uint dst_stride_y, uint dst_step_y, uint dst_offset_first_element_in_bytes)
This function applies a non linear filter on a 3x3 cross basis on an input image.
Note
The needed filter operation is defined through the preprocessor by passing either -DMIN, -DMAX or -DMEDIAN.
Parameters
[in] src_ptr Pointer to the source image. Supported data types: U8
[in] src_stride_x Stride of the source image in X dimension (in bytes)
[in] src_step_x src_stride_x * number of elements along X processed per workitem(in bytes)
[in] src_stride_y Stride of the source image in Y dimension (in bytes)
[in] src_step_y src_stride_y * number of elements along Y processed per workitem(in bytes)
[in] src_offset_first_element_in_bytes The offset of the first element in the source image
[out] dst_ptr Pointer to the destination image. Supported data types: U8
[in] dst_stride_x Stride of the destination image in X dimension (in bytes)
[in] dst_step_x dst_stride_x * number of elements along X processed per workitem(in bytes)
[in] dst_stride_y Stride of the destination image in Y dimension (in bytes)
[in] dst_step_y dst_stride_y * number of elements along Y processed per workitem(in bytes)
[in] dst_offset_first_element_in_bytes The offset of the first element in the destination image
Definition at line 99 of file non_linear_filter3x3.cl.
References CONVERT_TO_IMAGE_STRUCT, arm_compute::test::validation::dst, arm_compute::test::fixed_point_arithmetic::detail::max(), arm_compute::test::fixed_point_arithmetic::detail::min(), offset(), Image::ptr, row_reduce_max_3(), row_reduce_min_3(), sort5(), and arm_compute::test::validation::src.
 {
     Image src = CONVERT_TO_IMAGE_STRUCT(src);
     Image dst = CONVERT_TO_IMAGE_STRUCT(dst);
     // Load values
     uchar8  top    = vload8(0, offset(&src, 0, -1));
     uchar16 middle = vload16(0, offset(&src, -1, 0));
     uchar8  bottom = vload8(0, offset(&src, 0, 1));
     // Apply respective filter
 #ifdef MIN
     uchar8 tmp_middle = row_reduce_min_3(middle);
     uchar8 out        = min(tmp_middle, min(top, bottom));
 #elif defined(MAX)
     uchar8  tmp_middle = row_reduce_max_3(middle);
     uchar8  out        = max(tmp_middle, max(top, bottom));
 #elif defined(MEDIAN)
     uchar8 p0  = top.s01234567;
     uchar8 p1  = middle.s01234567;
     uchar8 p2  = middle.s12345678;
     uchar8 p3  = middle.s23456789;
     uchar8 p4  = bottom.s01234567;
     uchar8 out = sort5(p0, p1, p2, p3, p4);
 #else /* MIN or MAX or MEDIAN */
 #error "Unsupported filter function"
 #endif /* MIN or MAX or MEDIAN */
     // Store result
     vstore8(out, 0, dst.ptr);
 }
__kernel void non_linear_filter_disk3x3 (__global uchar * src_ptr, uint src_stride_x, uint src_step_x, uint src_stride_y, uint src_step_y, uint src_offset_first_element_in_bytes, __global uchar * dst_ptr, uint dst_stride_x, uint dst_step_x, uint dst_stride_y, uint dst_step_y, uint dst_offset_first_element_in_bytes)
This function applies a non linear filter on a 3x3 disk basis on an input image.
Note
The needed filter operation is defined through the preprocessor by passing either -DMIN, -DMAX or -DMEDIAN.
Parameters
[in] src_ptr Pointer to the source image. Supported data types: U8
[in] src_stride_x Stride of the source image in X dimension (in bytes)
[in] src_step_x src_stride_x * number of elements along X processed per workitem(in bytes)
[in] src_stride_y Stride of the source image in Y dimension (in bytes)
[in] src_step_y src_stride_y * number of elements along Y processed per workitem(in bytes)
[in] src_offset_first_element_in_bytes The offset of the first element in the source image
[out] dst_ptr Pointer to the destination image. Supported data types: U8
[in] dst_stride_x Stride of the destination image in X dimension (in bytes)
[in] dst_step_x dst_stride_x * number of elements along X processed per workitem(in bytes)
[in] dst_stride_y Stride of the destination image in Y dimension (in bytes)
[in] dst_step_y dst_stride_y * number of elements along Y processed per workitem(in bytes)
[in] dst_offset_first_element_in_bytes The offset of the first element in the destination image
Definition at line 150 of file non_linear_filter3x3.cl.
References CONVERT_TO_IMAGE_STRUCT, arm_compute::test::validation::dst, arm_compute::test::fixed_point_arithmetic::detail::max(), arm_compute::test::fixed_point_arithmetic::detail::min(), offset(), Image::ptr, row_reduce_max_3(), row_reduce_min_3(), sort9(), and arm_compute::test::validation::src.
 {
     Image src = CONVERT_TO_IMAGE_STRUCT(src);
     Image dst = CONVERT_TO_IMAGE_STRUCT(dst);
     // Load values
     uchar16 top    = vload16(0, offset(&src, -1, -1));
     uchar16 middle = vload16(0, offset(&src, -1, 0));
     uchar16 bottom = vload16(0, offset(&src, -1, 1));
     // Apply respective filter
 #ifdef MIN
     uchar16 tmp = min(top, min(middle, bottom));
     uchar8  out = row_reduce_min_3(tmp);
 #elif defined(MAX)
     uchar16 tmp        = max(top, max(middle, bottom));
     uchar8  out        = row_reduce_max_3(tmp);
 #elif defined(MEDIAN)
     uchar8 p0  = top.s01234567;
     uchar8 p1  = top.s12345678;
     uchar8 p2  = top.s23456789;
     uchar8 p3  = middle.s01234567;
     uchar8 p4  = middle.s12345678;
     uchar8 p5  = middle.s23456789;
     uchar8 p6  = bottom.s01234567;
     uchar8 p7  = bottom.s12345678;
     uchar8 p8  = bottom.s23456789;
     uchar8 out = sort9(p0, p1, p2, p3, p4, p5, p6, p7, p8);
 #else /* MIN or MAX or MEDIAN */
 #error "Unsupported filter function"
 #endif /* MIN or MAX or MEDIAN */
     // Store result
     vstore8(out, 0, dst.ptr);
 }