Compute Library: src/core/CL/cl_kernels/nonmax.cl File Reference
nonmax.cl File Reference
#include "helpers.h"
Functions
__kernel void non_max_suppression (__global uchar *src_ptr, uint src_stride_x, uint src_step_x, uint src_stride_y, uint src_step_y, uint src_offset_first_element_in_bytes, __global uchar *dst_ptr, uint dst_stride_x, uint dst_step_x, uint dst_stride_y, uint dst_step_y, uint dst_offset_first_element_in_bytes)
This function performs Non maxima suppression over a 3x3 window on a given image.
Function Documentation
non_max_suppression()
__kernel void non_max_suppression (__global uchar * src_ptr, uint src_stride_x, uint src_step_x, uint src_stride_y, uint src_step_y, uint src_offset_first_element_in_bytes, __global uchar * dst_ptr, uint dst_stride_x, uint dst_step_x, uint dst_stride_y, uint dst_step_y, uint dst_offset_first_element_in_bytes)
This function performs Non maxima suppression over a 3x3 window on a given image.
Parameters
[in] src_ptr Pointer to the source image. Supported data types: F32
[in] src_stride_x Stride of the source image in X dimension (in bytes)
[in] src_step_x src_stride_x * number of elements along X processed per workitem(in bytes)
[in] src_stride_y Stride of the source image in Y dimension (in bytes)
[in] src_step_y src_stride_y * number of elements along Y processed per workitem(in bytes)
[in] src_offset_first_element_in_bytes The offset of the first element in the source image
[out] dst_ptr Pointer to the destination image. Supported data types: F32
[in] dst_stride_x Stride of the destination image in X dimension (in bytes)
[in] dst_step_x dst_stride_x * number of elements along X processed per workitem(in bytes)
[in] dst_stride_y Stride of the destination image in Y dimension (in bytes)
[in] dst_step_y dst_stride_y * number of elements along Y processed per workitem(in bytes)
[in] dst_offset_first_element_in_bytes The offset of the first element in the destination image
Definition at line 41 of file nonmax.cl.
 {
     Image src = CONVERT_TO_IMAGE_STRUCT(src);
     Image dst = CONVERT_TO_IMAGE_STRUCT(dst);
     VEC_DATA_TYPE(DATA_TYPE, 8)
     vc = vload8(0, (__global DATA_TYPE *)src.ptr);
     if(all(vc == (DATA_TYPE)0))
     {
         vstore8(0, 0, (__global DATA_TYPE *)dst.ptr);
         return;
     }
     VEC_DATA_TYPE(DATA_TYPE, 16)
     nc = vload16(0, (__global DATA_TYPE *)offset(&src, -1, -1));
     VEC_DATA_TYPE(DATA_TYPE, 8)
     out = select((DATA_TYPE)0, vc, (vc >= nc.s01234567) && (vc >= nc.s12345678) && (vc >= nc.s23456789));
     nc  = vload16(0, (__global DATA_TYPE *)offset(&src, -1, 0));
     out = select((DATA_TYPE)0, out, (vc >= nc.s01234567) && (vc > nc.s23456789));
     nc  = vload16(0, (__global DATA_TYPE *)offset(&src, -1, +1));
     out = select((DATA_TYPE)0, out, (vc > nc.s01234567) && (vc > nc.s12345678) && (vc > nc.s23456789));
     vstore8(out, 0, (__global DATA_TYPE *)dst.ptr);
 }
References CONVERT_TO_IMAGE_STRUCT, DATA_TYPE, arm_compute::test::validation::dst, offset(), arm_compute::test::validation::select, arm_compute::test::validation::src, and VEC_DATA_TYPE.
Referenced by NEFastCornersKernel::configure(), and CLFastCornersKernel::configure().