Compute Library: src/core/CL/cl_kernels/softmax_layer_quantized.cl File Reference
softmax_layer_quantized.cl File Reference
#include "asymm_helper.h"
#include "helpers.h"
Macros
#define MAX_OP(x, y, type, size) max((x), (y))
#define ADD_OP(x, y, type, size) ((x) + (y))
Functions
__kernel void softmax_layer_max_quantized (__global uchar *src_ptr, uint src_stride_x, uint src_step_x, uint src_stride_y, uint src_step_y, uint src_stride_z, uint src_step_z, uint src_offset_first_element_in_bytes, __global uchar *dst_ptr, uint dst_stride_x, uint dst_step_x, uint dst_stride_y, uint dst_step_y, uint dst_stride_z, uint dst_step_z, uint dst_offset_first_element_in_bytes, uint width)
Identifies the maximum value across the 1st dimension.
Variables
__constant uchar16 type_min = 0
__constant uint16 idx16 = (uint16)(0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15)
Macro Definition Documentation
#define ADD_OP (x, y, type, size) ((x) + (y))
Definition at line 28 of file softmax_layer_quantized.cl.
Referenced by softmax_layer_max_quantized().
#define MAX_OP (x, y, type, size) max((x), (y))
Definition at line 27 of file softmax_layer_quantized.cl.
Referenced by softmax_layer_max_quantized().
Function Documentation
__kernel void softmax_layer_max_quantized (__global uchar * src_ptr, uint src_stride_x, uint src_step_x, uint src_stride_y, uint src_step_y, uint src_stride_z, uint src_step_z, uint src_offset_first_element_in_bytes, __global uchar * dst_ptr, uint dst_stride_x, uint dst_step_x, uint dst_stride_y, uint dst_step_y, uint dst_stride_z, uint dst_step_z, uint dst_offset_first_element_in_bytes, uint width)
Identifies the maximum value across the 1st dimension.
Note
In case the input is not multiple of 16 -DNON_MULTIPLE_OF_16 must be passed.
Parameters
[in] src_ptr Pointer to the source tensor slice. Supported data types: QASYMM8
[in] src_stride_x Stride of the source tensor in X dimension (in bytes)
[in] src_step_x src_stride_x * number of elements along X processed per workitem(in bytes)
[in] src_stride_y Stride of the source tensor in Y dimension (in bytes)
[in] src_step_y src_stride_y * number of elements along Y processed per workitem(in bytes)
[in] src_stride_z Stride of the source tensor in Z dimension (in bytes)
[in] src_step_z src_stride_z * number of elements along Z processed per workitem(in bytes)
[in] src_offset_first_element_in_bytes The offset of the first element in the source tensor
[out] dst_ptr Pointer to the destination tensor slice. Supported data types: same as src_ptr
[in] dst_stride_x Stride of the destination tensor in X dimension (in bytes)
[in] dst_step_x dst_stride_x * number of elements along X processed per workitem(in bytes)
[in] dst_stride_y Stride of the destination tensor in Y dimension (in bytes)
[in] dst_step_y dst_stride_y * number of elements along Y processed per workitem(in bytes)
[in] dst_stride_z Stride of the destination tensor in Z dimension (in bytes)
[in] dst_step_z dst_stride_z * number of elements along Z processed per workitem(in bytes)
[in] dst_offset_first_element_in_bytes The offset of the first element in the destination tensor
[in] width Input image width
Definition at line 55 of file softmax_layer_quantized.cl.
References ADD_OP, asymm_exp_on_negative_values(), asymm_mult(), asymm_one_over_one_plus_x_for_x_in_0_1(), asymm_rescale(), asymm_rounding_divide_by_pow2(), arm_compute::test::fixed_point_arithmetic::detail::clz(), CONVERT_TENSOR3D_TO_IMAGE_STRUCT, CONVERT_TENSOR3D_TO_IMAGE_STRUCT_NO_STEP, arm_compute::test::validation::dst, idx16, arm_compute::test::fixed_point_arithmetic::detail::max(), MAX_OP, offset(), Image::ptr, arm_compute::test::validation::src, sum(), TENSOR3D_DECLARATION, and type_min.
 {
     Image src = CONVERT_TENSOR3D_TO_IMAGE_STRUCT(src);
     Image dst = CONVERT_TENSOR3D_TO_IMAGE_STRUCT(dst);
     // Initialize local maximum
     uchar16 max_val = 0;
     // Calculate max of row
     const uint width4 = width >> 4;
     for(uint i = 0; i < width4; i++)
     {
         uchar16 data = vload16(0, (__global uchar *)offset(&src, i << 4, 0));
         max_val      = MAX_OP(data, max_val, uchar, 16);
     }
 #ifdef NON_MULTIPLE_OF_16
     // Handle non multiple of 16
     uchar16 data = vload16(0, (__global uchar *)offset(&src, width4 << 4, 0));
     uchar16 widx = convert_uchar16(((uint16)(width4 << 4) + idx16) < width);
     max_val      = MAX_OP(max_val, select(type_min, data, widx), uchar, 16);
 #endif /* NON_MULTIPLE_OF_16 */
     // Perform max reduction
     max_val.s01234567 = MAX_OP(max_val.s01234567, max_val.s89ABCDEF, uchar, 8);
     max_val.s0123     = MAX_OP(max_val.s0123, max_val.s4567, uchar, 4);
     max_val.s01       = MAX_OP(max_val.s01, max_val.s23, uchar, 2);
     max_val.s0        = MAX_OP(max_val.s0, max_val.s1, uchar, 1);
     // Store result
     *((__global uchar *)dst.ptr) = max_val.s0;
 }
Variable Documentation
__constant uint16 idx16 = (uint16)(0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15)
Definition at line 31 of file softmax_layer_quantized.cl.
Referenced by softmax_layer_max_quantized().
__constant uchar16 type_min = 0
Definition at line 30 of file softmax_layer_quantized.cl.
Referenced by softmax_layer_max_quantized().