Compute Library: QuantizationInfo Struct Reference
QuantizationInfo Struct Reference
Quantization settings (used for QASYMM8 data type)
#include <Types.h>
Public Member Functions
QuantizationInfo () noexcept
Default constructor.
QuantizationInfo (float scale, int offset)
Construct quantization info.
bool operator== (const QuantizationInfo &other)
Check whether equal to a given quantization info.
bool operator!= (const QuantizationInfo &other)
Check whether not equal to a given quantization info.
qasymm8_t quantize (float value, RoundingPolicy rounding_policy) const
Quantizes a value using the scale/offset in this QuantizationInfo.
float dequantize (qasymm8_t value) const
Dequantizes a value using the scale/offset in this QuantizationInfo.
bool empty () const
Indicates whether this QuantizationInfo has valid settings or not.
Data Fields
float scale
scale
int offset
offset
Detailed Description
Quantization settings (used for QASYMM8 data type)
Definition at line 124 of file Types.h.
Constructor & Destructor Documentation
QuantizationInfo () inline noexcept
Default constructor.
Definition at line 127 of file Types.h.
         : scale(0.0f),
           offset(0)
     {
     }
QuantizationInfo (float scale, int offset) inline
Construct quantization info.
Parameters
[in] scale Scale.
[in] offset Offset.
Definition at line 138 of file Types.h.
         : scale(scale), offset(offset)
     {
     }
Member Function Documentation
float dequantize (qasymm8_t value) const inline
Dequantizes a value using the scale/offset in this QuantizationInfo.
Parameters
[in] value Value to dequantize.
Returns
the original value before quantization.
Definition at line 187 of file Types.h.
References ARM_COMPUTE_ERROR_ON_MSG.
Referenced by arm_compute::test::validation::convert_from_asymmetric().
     {
         ARM_COMPUTE_ERROR_ON_MSG(scale == 0, "QuantizationInfo::dequantize: scale == 0");
         return scvt_f32_qasymm8(value, scale, offset);
     }
bool empty () const inline
Indicates whether this QuantizationInfo has valid settings or not.
Returns
True if the this has invalid settings.
Definition at line 197 of file Types.h.
Referenced by arm_compute::set_quantization_info_if_empty().
     {
         return scale == 0;
     }
bool operator!= (const QuantizationInfo & other) inline
Check whether not equal to a given quantization info.
Parameters
[in] other Other quantization info.
Returns
True if the given quantization info is not the same.
Definition at line 160 of file Types.h.
     {
         return !(*this == other);
     }
bool operator== (const QuantizationInfo & other) inline
Check whether equal to a given quantization info.
Parameters
[in] other Other quantization info.
Returns
True if the given quantization info is the same.
Definition at line 149 of file Types.h.
References QuantizationInfo::offset, offset(), QuantizationInfo::scale, and arm_compute::test::validation::scale.
     {
         return scale == other.scale && offset == other.offset;
     }
qasymm8_t quantize (float value, RoundingPolicy rounding_policy) const inline
Quantizes a value using the scale/offset in this QuantizationInfo.
Parameters
[in] value Value to quantize.
[in] rounding_policy Policy to use when rounding.
Returns
the quantized value.
Definition at line 175 of file Types.h.
References ARM_COMPUTE_ERROR_ON_MSG.
     {
         ARM_COMPUTE_ERROR_ON_MSG(scale == 0, "QuantizationInfo::quantize: scale == 0");
         return sqcvt_qasymm8_f32(value, scale, offset, rounding_policy);
     }
Field Documentation
int offset
offset
Definition at line 166 of file Types.h.
Referenced by arm_compute::test::validation::reference::depthwise_convolution(), arm_compute::operator<<(), and QuantizationInfo::operator==().
float scale
scale
Definition at line 165 of file Types.h.
Referenced by arm_compute::test::validation::reference::depthwise_convolution(), arm_compute::operator<<(), and QuantizationInfo::operator==().
The documentation for this struct was generated from the following file:
arm_compute/core/Types.h