Compute Library: Measurement Struct Reference
Measurement Struct Reference
Generic measurement that stores values as either double or long long int.
#include <Measurement.h>
Data Structures
struct Value
Measurement value.
Public Member Functions
bool operator< (const Measurement &b) const
Compare the stored value with another value.
template<typename Floating , typename std::enable_if< !std::is_integral< Floating >::value, int >::type = 0>
Measurement (Floating v, std::string unit, std::list< std::string > raw={})
Constructor to store a floating point value.
template<typename Integer , typename std::enable_if< std::is_integral< Integer >::value, int >::type = 0>
Measurement (Integer v, std::string unit, std::list< std::string > raw={})
Constructor to store an integer value.
const std::string & unit () const
Accessor for the unit of the measurement.
const std::list< std::string > & raw_data () const
Accessor for the raw data.
const Value & value () const
Accessor for the stored value.
Friends
std::ostream & operator<< (std::ostream &os, const Measurement &measurement)
Stream output operator to print the measurement.
Detailed Description
Generic measurement that stores values as either double or long long int.
Definition at line 41 of file Measurement.h.
Constructor & Destructor Documentation
Measurement (Floating v, std::string unit, std::list< std::string > raw = {}) inline
Constructor to store a floating point value.
Parameters
[in] v Value to store
[in] unit Unit of v
[in] raw (Optional) The raw value(s) was generated from.
Definition at line 252 of file Measurement.h.
References Measurement::Value::v.
                                                                      {})
         : _unit(unit), _raw_data(std::move(raw)), _value(true)
     {
         _value.v.floating_point = static_cast<double>(v);
         if(_raw_data.empty())
         {
             _raw_data = { _value.to_string() };
         }
     }
Measurement (Integer v, std::string unit, std::list< std::string > raw = {}) inline
Constructor to store an integer value.
Parameters
[in] v Value to store
[in] unit Unit of v
[in] raw (Optional) The raw value(s) was generated from.
Definition at line 269 of file Measurement.h.
References Measurement::Value::v.
                                                                     {})
         : _unit(unit), _raw_data(std::move(raw)), _value(false)
     {
         _value.v.integer = static_cast<long long int>(v);
         if(_raw_data.empty())
         {
             _raw_data = { _value.to_string() };
         }
     }
Member Function Documentation
bool operator< (const Measurement & b) const inline
Compare the stored value with another value.
Parameters
[in] b Value to compare against
Returns
The result of stored value < b
Definition at line 225 of file Measurement.h.
References Measurement::value().
     {
         return _value < b.value();
     }
const std::list<std::string>& raw_data () const inline
Accessor for the raw data.
Returns
The raw data
Definition at line 292 of file Measurement.h.
     {
         return _raw_data;
     }
const std::string& unit () const inline
Accessor for the unit of the measurement.
Returns
Unit of the measurement
Definition at line 283 of file Measurement.h.
Referenced by PrettyPrinter::print_measurements().
     {
         return _unit;
     }
const Value& value () const inline
Accessor for the stored value.
Returns
The stored value
Definition at line 301 of file Measurement.h.
Referenced by InstrumentsStats::InstrumentsStats(), Measurement::operator<(), and PrettyPrinter::print_measurements().
     {
         return _value;
     }
Friends And Related Function Documentation
std::ostream& operator<< (std::ostream & os, const Measurement & measurement) friend
Stream output operator to print the measurement.
Prints value and unit.
Parameters
[out] os Output stream.
[in] measurement Measurement.
Returns
the modified output stream.
Definition at line 239 of file Measurement.h.
     {
         os << measurement._value << " " << measurement._unit;
         return os;
     }
The documentation for this struct was generated from the following file:
tests/framework/instruments/Measurement.h