Compute Library: RangeDataset< T >::iterator Struct Reference
RangeDataset< T >::iterator Struct Reference
Iterator for the dataset.
#include <RangeDataset.h>
Public Member Functions
iterator (std::string name, T start, T step)
Construct an iterator.
std::string description () const
Get the description of the current value.
RangeDataset::type operator * () const
Get the value of the iterator.
iterator & operator++ ()
Inrement the iterator.
Detailed Description
template<typename T>
struct arm_compute::test::framework::dataset::RangeDataset< T >::iterator
Iterator for the dataset.
Definition at line 70 of file RangeDataset.h.
Constructor & Destructor Documentation
iterator()
iterator (std::string name, T start, T step) inline
Construct an iterator.
Parameters
[in] name Dataset name.
[in] start Dataset start value.
[in] step Dataset step size.
Definition at line 78 of file RangeDataset.h.
             : _name{ name }, _value{ start }, _step{ step }
         {
         }
References NamedDataset::name().
Member Function Documentation
description()
std::string description () const inline
Get the description of the current value.
Returns
description of the current value.
Definition at line 87 of file RangeDataset.h.
         {
             using support::cpp11::to_string;
             return _name + "=" + to_string(_value);
         }
References arm_compute::test::framework::to_string(), and arm_compute::support::cpp11::to_string().
operator *()
RangeDataset::type operator * () const inline
Get the value of the iterator.
Returns
the value of the iterator.
Definition at line 97 of file RangeDataset.h.
         {
             return std::make_tuple(_value);
         }
operator++()
iterator& operator++ () inline
Inrement the iterator.
Returns
*this;
Definition at line 106 of file RangeDataset.h.
         {
             _value += _step;
             return *this;
         }
The documentation for this struct was generated from the following file:
tests/framework/datasets/RangeDataset.h