Compute Library: ValidRegion Struct Reference
ValidRegion Struct Reference
#include <Types.h>
Public Member Functions
ValidRegion ()
ValidRegion (const ValidRegion &)=default
ValidRegion (ValidRegion &&)=default
ValidRegion & operator= (const ValidRegion &)=default
ValidRegion & operator= (ValidRegion &&)=default
~ValidRegion ()=default
ValidRegion (const Coordinates &an_anchor, const TensorShape &a_shape)
ValidRegion (const Coordinates &an_anchor, const TensorShape &a_shape, size_t num_dimensions)
int start (unsigned int d) const
Return the start of the valid region for the given dimension d.
int end (unsigned int d) const
Return the end of the valid region for the given dimension d.
Data Fields
Coordinates anchor
TensorShape shape
Detailed Description
Definition at line 155 of file Types.h.
Constructor & Destructor Documentation
ValidRegion () inline
Definition at line 157 of file Types.h.
References arm_compute::test::validation::shape.
         : anchor{}, shape{}
     {
     }
ValidRegion (const ValidRegion &) default
ValidRegion (ValidRegion &&) default
~ValidRegion () default
ValidRegion (const Coordinates & an_anchor, const TensorShape & a_shape) inline
Definition at line 168 of file Types.h.
References arm_compute::test::fixed_point_arithmetic::detail::max(), and arm_compute::test::validation::shape.
         : anchor{ an_anchor }, shape{ a_shape }
     {
         anchor.set_num_dimensions(std::max(anchor.num_dimensions(), shape.num_dimensions()));
     }
ValidRegion (const Coordinates & an_anchor, const TensorShape & a_shape, size_t num_dimensions) inline
Definition at line 174 of file Types.h.
References ARM_COMPUTE_ERROR_ON, arm_compute::test::fixed_point_arithmetic::detail::max(), and arm_compute::test::validation::shape.
         : anchor{ an_anchor }, shape{ a_shape }
     {
         ARM_COMPUTE_ERROR_ON(num_dimensions < std::max(anchor.num_dimensions(), shape.num_dimensions()));
         anchor.set_num_dimensions(num_dimensions);
     }
Member Function Documentation
int end (unsigned int d) const inline
Return the end of the valid region for the given dimension d.
Definition at line 188 of file Types.h.
References arm_compute::test::validation::shape.
Referenced by arm_compute::test::is_in_valid_region().
     {
         return anchor[d] + shape[d];
     }
ValidRegion& operator= (const ValidRegion &) default
ValidRegion& operator= (ValidRegion &&) default
int start (unsigned int d) const inline
Return the start of the valid region for the given dimension d.
Definition at line 182 of file Types.h.
Referenced by arm_compute::test::is_in_valid_region().
     {
         return anchor[d];
     }
Field Documentation
Coordinates anchor
Definition at line 193 of file Types.h.
Referenced by arm_compute::calculate_valid_region_scale(), arm_compute::intersect_valid_regions(), arm_compute::test::shape_to_valid_region_gaussian_pyramid_half(), and arm_compute::test::validation::validate().
TensorShape shape
Definition at line 194 of file Types.h.
Referenced by arm_compute::calculate_valid_region_scale(), arm_compute::intersect_valid_regions(), arm_compute::test::shape_to_valid_region_gaussian_pyramid_half(), and arm_compute::test::validation::validate().
The documentation for this struct was generated from the following file:
arm_compute/core/Types.h