Compute Library: functions Struct Reference
functions Struct Reference
#include <FixedPoint.h>
Static Public Member Functions
template<typename T , typename U , typename traits >
static std::basic_ostream< T, traits > & write (std::basic_ostream< T, traits > &s, fixed_point< U > &x)
Output stream operator.
template<typename T >
static bool signbit (fixed_point< T > x)
Signbit of a fixed point number.
template<typename T >
static bool isequal (fixed_point< T > x, fixed_point< T > y)
Checks if two fixed point numbers are equal.
template<typename T >
static bool isnotequal (fixed_point< T > x, fixed_point< T > y)
Checks if two fixed point number are not equal.
template<typename T >
static bool isgreater (fixed_point< T > x, fixed_point< T > y)
Checks if one fixed point is greater than the other.
template<typename T >
static bool isgreaterequal (fixed_point< T > x, fixed_point< T > y)
Checks if one fixed point is greater or equal than the other.
template<typename T >
static bool isless (fixed_point< T > x, fixed_point< T > y)
Checks if one fixed point is less than the other.
template<typename T >
static bool islessequal (fixed_point< T > x, fixed_point< T > y)
Checks if one fixed point is less or equal than the other.
template<typename T >
static bool islessgreater (fixed_point< T > x, fixed_point< T > y)
Checks if one fixed point is less or greater than the other.
template<typename T >
static fixed_point< T > clamp (fixed_point< T > x, T min, T max)
Clamp fixed point to specific range.
template<OverflowPolicy OP = OverflowPolicy::SATURATE, typename T >
static fixed_point< T > negate (fixed_point< T > x)
Negate number.
template<OverflowPolicy OP = OverflowPolicy::SATURATE, typename T >
static fixed_point< T > add (fixed_point< T > x, fixed_point< T > y)
Perform addition among two fixed point numbers.
template<OverflowPolicy OP = OverflowPolicy::SATURATE, typename T >
static fixed_point< T > sub (fixed_point< T > x, fixed_point< T > y)
Perform subtraction among two fixed point numbers.
template<OverflowPolicy OP = OverflowPolicy::SATURATE, typename T >
static fixed_point< T > mul (fixed_point< T > x, fixed_point< T > y)
Perform multiplication among two fixed point numbers.
template<OverflowPolicy OP = OverflowPolicy::SATURATE, typename T >
static fixed_point< T > div (fixed_point< T > x, fixed_point< T > y)
Perform division among two fixed point numbers.
template<OverflowPolicy OP = OverflowPolicy::SATURATE, typename T >
static fixed_point< T > shift_left (fixed_point< T > x, size_t shift)
Shift left.
template<typename T >
static fixed_point< T > shift_right (fixed_point< T > x, size_t shift)
Shift right.
template<typename T >
static fixed_point< T > abs (fixed_point< T > x)
Calculate absolute value.
template<typename T >
static fixed_point< T > log (fixed_point< T > x)
Calculate the logarithm of a fixed point number.
template<typename T >
static fixed_point< T > exp (fixed_point< T > x)
Calculate the exponential of a fixed point number.
template<typename T >
static fixed_point< T > inv_sqrt (fixed_point< T > x)
Calculate the inverse square root of a fixed point number.
template<typename T >
static fixed_point< T > tanh (fixed_point< T > x)
Calculate the hyperbolic tangent of a fixed point number.
template<typename T >
static fixed_point< T > pow (fixed_point< T > x, fixed_point< T > a)
Calculate the a-th power of a fixed point number.
Detailed Description
Definition at line 365 of file FixedPoint.h.
Member Function Documentation
static fixed_point<T> abs (fixed_point< T > x) inline static
Calculate absolute value.
Parameters
[in] x Fixed point operand
Returns
Absolute value of operand
Definition at line 655 of file FixedPoint.h.
References fixed_point< T >::precision(), and fixed_point< T >::raw().
Referenced by arm_compute::test::fixed_point_arithmetic::detail::abs().
     {
         using promoted_T = typename traits::promote<T>::type;
         T val            = (x.raw() < 0) ? constant_expr<T>::saturate_cast(-static_cast<promoted_T>(x.raw())) : x.raw();
         return fixed_point<T>(val, x.precision(), true);
     }
static fixed_point<T> add (fixed_point< T > x, fixed_point< T > y) inline static
Perform addition among two fixed point numbers.
Parameters
[in] x First fixed point operand
[in] y Second fixed point operand
Returns
Result fixed point with precision equal to minimum precision of both operands
Definition at line 527 of file FixedPoint.h.
References arm_compute::test::fixed_point_arithmetic::detail::min(), fixed_point< T >::precision(), fixed_point< T >::raw(), fixed_point< T >::rescale(), arm_compute::test::fixed_point_arithmetic::SATURATE, constant_expr< T >::saturate_cast(), and caffe_data_extractor::type.
Referenced by arm_compute::test::fixed_point_arithmetic::detail::operator+().
     {
         uint8_t p = std::min(x.precision(), y.precision());
         x.rescale(p);
         y.rescale(p);
         if(OP == OverflowPolicy::SATURATE)
         {
             using type = typename traits::promote<T>::type;
             type val   = static_cast<type>(x.raw()) + static_cast<type>(y.raw());
             val        = constant_expr<T>::saturate_cast(val);
             return fixed_point<T>(static_cast<T>(val), p, true);
         }
         else
         {
             return fixed_point<T>(x.raw() + y.raw(), p, true);
         }
     }
static fixed_point<T> clamp (fixed_point< T > x, T min, T max) inline static
Clamp fixed point to specific range.
Parameters
[in] x Fixed point operand
[in] min Minimum value to clamp to
[in] max Maximum value to clamp to
Returns
Clamped result
Definition at line 498 of file FixedPoint.h.
References constant_expr< T >::clamp(), arm_compute::test::fixed_point_arithmetic::detail::max(), arm_compute::test::fixed_point_arithmetic::detail::min(), fixed_point< T >::precision(), and fixed_point< T >::raw().
Referenced by arm_compute::test::fixed_point_arithmetic::detail::clamp().
     {
         return fixed_point<T>(constant_expr<T>::clamp(x.raw(), min, max), x.precision(), true);
     }
static fixed_point<T> div (fixed_point< T > x, fixed_point< T > y) inline static
Perform division among two fixed point numbers.
Parameters
[in] x First fixed point operand
[in] y Second fixed point operand
Returns
Result fixed point with precision equal to minimum precision of both operands
Definition at line 598 of file FixedPoint.h.
References arm_compute::test::fixed_point_arithmetic::detail::max(), arm_compute::test::fixed_point_arithmetic::detail::min(), fixed_point< T >::precision(), fixed_point< T >::raw(), arm_compute::test::fixed_point_arithmetic::SATURATE, and constant_expr< T >::saturate_cast().
Referenced by arm_compute::test::fixed_point_arithmetic::detail::div(), and arm_compute::test::fixed_point_arithmetic::detail::operator/().
     {
         using promoted_T = typename traits::promote<T>::type;
         uint8_t    p     = std::min(x.precision(), y.precision());
         promoted_T denom = static_cast<promoted_T>(y.raw());
         if(denom != 0)
         {
             promoted_T val = (static_cast<promoted_T>(x.raw()) << std::max(x.precision(), y.precision())) / denom;
             if(OP == OverflowPolicy::SATURATE)
             {
                 val = constant_expr<T>::saturate_cast(val);
             }
             return fixed_point<T>(static_cast<T>(val), p, true);
         }
         else
         {
             T val = (x.raw() < 0) ? std::numeric_limits<T>::min() : std::numeric_limits<T>::max();
             return fixed_point<T>(val, p, true);
         }
     }
static fixed_point<T> exp (fixed_point< T > x) inline static
Calculate the exponential of a fixed point number.
exp(x) = exp(floor(x)) * exp(x - floor(x)) = pow(2, floor(x) / ln(2)) * exp(x - floor(x)) = exp(x - floor(x)) << (floor(x) / ln(2))
Parameters
[in] x Fixed point operand
Returns
Exponential value of operand
Definition at line 715 of file FixedPoint.h.
References arm_compute::A, arm_compute::test::fixed_point_arithmetic::detail::add(), arm_compute::B, arm_compute::test::fixed_point_arithmetic::detail::clz(), arm_compute::test::fixed_point_arithmetic::detail::max(), arm_compute::test::fixed_point_arithmetic::detail::mul(), fixed_point< T >::precision(), arm_compute::test::fixed_point_arithmetic::detail::sub(), and constant_expr< T >::to_int().
Referenced by arm_compute::test::fixed_point_arithmetic::detail::exp().
     {
         uint8_t p = x.precision();
         // Constants
         auto const_one = fixed_point<T>(1, p);
         auto ln2       = fixed_point<T>(0.6931471, p);
         auto inv_ln2   = fixed_point<T>(1.442695, p);
         auto A         = fixed_point<T>(0.9978546, p);
         auto B         = fixed_point<T>(0.4994721, p);
         auto C         = fixed_point<T>(0.1763723, p);
         auto D         = fixed_point<T>(0.0435108, p);
         T scaled_int_part = detail::constant_expr<T>::to_int(mul(x, inv_ln2).raw(), p);
         // Polynomial expansion
         auto frac_part = sub(x, mul(ln2, fixed_point<T>(scaled_int_part, p)));
         auto taylor    = add(mul(frac_part, D), C);
         taylor         = add(mul(frac_part, taylor), B);
         taylor         = add(mul(frac_part, taylor), A);
         taylor         = mul(frac_part, taylor);
         taylor         = add(taylor, const_one);
         // Saturate value
         if(static_cast<T>(clz(taylor.raw())) <= scaled_int_part)
         {
             return fixed_point<T>(std::numeric_limits<T>::max(), p, true);
         }
         return (scaled_int_part < 0) ? shift_right(taylor, -scaled_int_part) : shift_left(taylor, scaled_int_part);
     }
static fixed_point<T> inv_sqrt (fixed_point< T > x) inline static
Calculate the inverse square root of a fixed point number.
Parameters
[in] x Fixed point operand
Returns
Inverse square root value of operand
Definition at line 752 of file FixedPoint.h.
References arm_compute::test::validation::a, arm_compute::test::fixed_point_arithmetic::detail::clz(), arm_compute::test::fixed_point_arithmetic::detail::mul(), fixed_point< T >::precision(), fixed_point< T >::raw(), arm_compute::test::fixed_point_arithmetic::detail::sub(), and value.
Referenced by arm_compute::test::fixed_point_arithmetic::detail::inv_sqrt().
     {
         const uint8_t p     = x.precision();
         int8_t        shift = std::numeric_limits<T>::digits - (p + detail::clz(x.raw()));
         shift += std::numeric_limits<T>::is_signed ? 1 : 0;
         // Use volatile to restrict compiler optimizations on shift as compiler reports maybe-uninitialized error on Android
         volatile int8_t *shift_ptr = &shift;
         auto           const_three = fixed_point<T>(3, p);
         auto           a           = (*shift_ptr < 0) ? shift_left(x, -(shift)) : shift_right(x, shift);
         fixed_point<T> x2          = a;
         // We need three iterations to find the result for QS8 and five for QS16
         constexpr int num_iterations = std::is_same<T, int8_t>::value ? 3 : 5;
         for(int i = 0; i < num_iterations; ++i)
         {
             fixed_point<T> three_minus_dx = sub(const_three, mul(a, mul(x2, x2)));
             x2                            = shift_right(mul(x2, three_minus_dx), 1);
         }
         return (shift < 0) ? shift_left(x2, (-shift) >> 1) : shift_right(x2, shift >> 1);
     }
static bool isequal (fixed_point< T > x, fixed_point< T > y) inline static
Checks if two fixed point numbers are equal.
Parameters
[in] x First fixed point operand
[in] y Second fixed point operand
Returns
True if fixed points are equal else false
Definition at line 398 of file FixedPoint.h.
References arm_compute::test::fixed_point_arithmetic::detail::min(), fixed_point< T >::precision(), fixed_point< T >::raw(), and fixed_point< T >::rescale().
Referenced by arm_compute::test::fixed_point_arithmetic::detail::operator==().
     {
         uint8_t p = std::min(x.precision(), y.precision());
         x.rescale(p);
         y.rescale(p);
         return (x.raw() == y.raw());
     }
static bool isgreater (fixed_point< T > x, fixed_point< T > y) inline static
Checks if one fixed point is greater than the other.
Parameters
[in] x First fixed point operand
[in] y Second fixed point operand
Returns
True if fixed point is greater than other
Definition at line 425 of file FixedPoint.h.
References arm_compute::test::fixed_point_arithmetic::detail::min(), fixed_point< T >::precision(), fixed_point< T >::raw(), and fixed_point< T >::rescale().
     {
         uint8_t p = std::min(x.precision(), y.precision());
         x.rescale(p);
         y.rescale(p);
         return (x.raw() > y.raw());
     }
static bool isgreaterequal (fixed_point< T > x, fixed_point< T > y) inline static
Checks if one fixed point is greater or equal than the other.
Parameters
[in] x First fixed point operand
[in] y Second fixed point operand
Returns
True if fixed point is greater or equal than other
Definition at line 440 of file FixedPoint.h.
References arm_compute::test::fixed_point_arithmetic::detail::min(), fixed_point< T >::precision(), fixed_point< T >::raw(), and fixed_point< T >::rescale().
     {
         uint8_t p = std::min(x.precision(), y.precision());
         x.rescale(p);
         y.rescale(p);
         return (x.raw() >= y.raw());
     }
static bool isless (fixed_point< T > x, fixed_point< T > y) inline static
Checks if one fixed point is less than the other.
Parameters
[in] x First fixed point operand
[in] y Second fixed point operand
Returns
True if fixed point is less than other
Definition at line 455 of file FixedPoint.h.
References arm_compute::test::fixed_point_arithmetic::detail::min(), fixed_point< T >::precision(), fixed_point< T >::raw(), and fixed_point< T >::rescale().
Referenced by arm_compute::test::fixed_point_arithmetic::detail::operator<().
     {
         uint8_t p = std::min(x.precision(), y.precision());
         x.rescale(p);
         y.rescale(p);
         return (x.raw() < y.raw());
     }
static bool islessequal (fixed_point< T > x, fixed_point< T > y) inline static
Checks if one fixed point is less or equal than the other.
Parameters
[in] x First fixed point operand
[in] y Second fixed point operand
Returns
True if fixed point is less or equal than other
Definition at line 470 of file FixedPoint.h.
References arm_compute::test::fixed_point_arithmetic::detail::min(), fixed_point< T >::precision(), fixed_point< T >::raw(), and fixed_point< T >::rescale().
     {
         uint8_t p = std::min(x.precision(), y.precision());
         x.rescale(p);
         y.rescale(p);
         return (x.raw() <= y.raw());
     }
static bool islessgreater (fixed_point< T > x, fixed_point< T > y) inline static
Checks if one fixed point is less or greater than the other.
Parameters
[in] x First fixed point operand
[in] y Second fixed point operand
Returns
True if fixed point is less or greater than other
Definition at line 485 of file FixedPoint.h.
     {
         return isnotequal(x, y);
     }
static bool isnotequal (fixed_point< T > x, fixed_point< T > y) inline static
Checks if two fixed point number are not equal.
Parameters
[in] x First fixed point operand
[in] y Second fixed point operand
Returns
True if fixed points are not equal else false
Definition at line 413 of file FixedPoint.h.
     {
         return !isequal(x, y);
     }
static fixed_point<T> log (fixed_point< T > x) inline static
Calculate the logarithm of a fixed point number.
Parameters
[in] x Fixed point operand
Returns
Logarithm value of operand
Definition at line 668 of file FixedPoint.h.
References arm_compute::A, arm_compute::test::fixed_point_arithmetic::detail::add(), arm_compute::B, arm_compute::test::fixed_point_arithmetic::detail::div(), arm_compute::test::fixed_point_arithmetic::detail::log(), arm_compute::test::fixed_point_arithmetic::detail::mul(), fixed_point< T >::precision(), fixed_point< T >::raw(), arm_compute::test::fixed_point_arithmetic::detail::sub(), and sum().
Referenced by arm_compute::test::fixed_point_arithmetic::detail::log().
     {
         uint8_t p         = x.precision();
         auto    const_one = fixed_point<T>(static_cast<T>(1), p);
         // Logarithm of 1 is zero and logarithm of negative values is not defined in R, so return 0.
         // Also, log(x) == -log(1/x) for 0 < x < 1.
         if(isequal(x, const_one) || islessequal(x, fixed_point<T>(static_cast<T>(0), p)))
         {
             return fixed_point<T>(static_cast<T>(0), p, true);
         }
         else if(isless(x, const_one))
         {
             return mul(log(div(const_one, x)), fixed_point<T>(-1, p));
         }
         // Remove even powers of 2
         T shift_val = 31 - __builtin_clz(x.raw() >> p);
         x           = shift_right(x, shift_val);
         x           = sub(x, const_one);
         // Constants
         auto ln2 = fixed_point<T>(0.6931471, p);
         auto A   = fixed_point<T>(1.4384189, p);
         auto B   = fixed_point<T>(-0.67719, p);
         auto C   = fixed_point<T>(0.3218538, p);
         auto D   = fixed_point<T>(-0.0832229, p);
         // Polynomial expansion
         auto sum = add(mul(x, D), C);
         sum      = add(mul(x, sum), B);
         sum      = add(mul(x, sum), A);
         sum      = mul(x, sum);
         return mul(add(sum, fixed_point<T>(static_cast<T>(shift_val), p)), ln2);
     }
static fixed_point<T> mul (fixed_point< T > x, fixed_point< T > y) inline static
Perform multiplication among two fixed point numbers.
Parameters
[in] x First fixed point operand
[in] y Second fixed point operand
Returns
Result fixed point with precision equal to minimum precision of both operands
Definition at line 577 of file FixedPoint.h.
References arm_compute::test::fixed_point_arithmetic::detail::max(), arm_compute::test::fixed_point_arithmetic::detail::min(), fixed_point< T >::precision(), fixed_point< T >::raw(), arm_compute::test::fixed_point_arithmetic::SATURATE, and constant_expr< T >::saturate_cast().
Referenced by arm_compute::test::fixed_point_arithmetic::detail::operator*().
     {
         using promoted_T        = typename traits::promote<T>::type;
         uint8_t    p_min        = std::min(x.precision(), y.precision());
         uint8_t    p_max        = std::max(x.precision(), y.precision());
         promoted_T round_factor = (1 << (p_max - 1));
         promoted_T val          = ((static_cast<promoted_T>(x.raw()) * static_cast<promoted_T>(y.raw())) + round_factor) >> p_max;
         if(OP == OverflowPolicy::SATURATE)
         {
             val = constant_expr<T>::saturate_cast(val);
         }
         return fixed_point<T>(static_cast<T>(val), p_min, true);
     }
static fixed_point<T> negate (fixed_point< T > x) inline static
Negate number.
Parameters
[in] x Fixed point operand
Returns
Negated fixed point result
Definition at line 509 of file FixedPoint.h.
References fixed_point< T >::precision(), fixed_point< T >::raw(), arm_compute::test::fixed_point_arithmetic::SATURATE, and constant_expr< T >::saturate_cast().
Referenced by arm_compute::test::fixed_point_arithmetic::detail::operator-().
     {
         using promoted_T = typename traits::promote<T>::type;
         promoted_T val   = -x.raw();
         if(OP == OverflowPolicy::SATURATE)
         {
             val = constant_expr<T>::saturate_cast(val);
         }
         return fixed_point<T>(static_cast<T>(val), x.precision(), true);
     }
static fixed_point<T> pow (fixed_point< T > x, fixed_point< T > a) inline static
Calculate the a-th power of a fixed point number.
The power is computed as x^a = e^(log(x) * a)
Parameters
[in] x Fixed point operand
[in] a Fixed point exponent
Returns
a-th power of the operand
Definition at line 807 of file FixedPoint.h.
References arm_compute::test::fixed_point_arithmetic::detail::exp(), and arm_compute::test::fixed_point_arithmetic::detail::log().
Referenced by arm_compute::test::fixed_point_arithmetic::detail::pow().
     {
         return exp(log(x) * a);
     }
static fixed_point<T> shift_left (fixed_point< T > x, size_t shift) inline static
Shift left.
Parameters
[in] x Fixed point operand
[in] shift Shift value
Returns
Shifted value
Definition at line 626 of file FixedPoint.h.
References fixed_point< T >::precision(), fixed_point< T >::raw(), arm_compute::test::fixed_point_arithmetic::SATURATE, and constant_expr< T >::saturate_cast().
Referenced by arm_compute::test::fixed_point_arithmetic::detail::operator<<().
     {
         using promoted_T = typename traits::promote<T>::type;
         promoted_T val   = static_cast<promoted_T>(x.raw()) << shift;
         if(OP == OverflowPolicy::SATURATE)
         {
             val = constant_expr<T>::saturate_cast(val);
         }
         return fixed_point<T>(static_cast<T>(val), x.precision(), true);
     }
static fixed_point<T> shift_right (fixed_point< T > x, size_t shift) inline static
Shift right.
Parameters
[in] x Fixed point operand
[in] shift Shift value
Returns
Shifted value
Definition at line 644 of file FixedPoint.h.
References fixed_point< T >::precision(), and fixed_point< T >::raw().
Referenced by arm_compute::test::fixed_point_arithmetic::detail::operator>>().
     {
         return fixed_point<T>(x.raw() >> shift, x.precision(), true);
     }
static bool signbit (fixed_point< T > x) inline static
Signbit of a fixed point number.
Parameters
[in] x Fixed point number
Returns
True if negative else false.
Definition at line 386 of file FixedPoint.h.
References fixed_point< T >::raw().
     {
         return ((x.raw() >> std::numeric_limits<T>::digits) != 0);
     }
static fixed_point<T> sub (fixed_point< T > x, fixed_point< T > y) inline static
Perform subtraction among two fixed point numbers.
Parameters
[in] x First fixed point operand
[in] y Second fixed point operand
Returns
Result fixed point with precision equal to minimum precision of both operands
Definition at line 552 of file FixedPoint.h.
References arm_compute::test::fixed_point_arithmetic::detail::min(), fixed_point< T >::precision(), fixed_point< T >::raw(), fixed_point< T >::rescale(), arm_compute::test::fixed_point_arithmetic::SATURATE, constant_expr< T >::saturate_cast(), and caffe_data_extractor::type.
Referenced by arm_compute::test::fixed_point_arithmetic::detail::operator-().
     {
         uint8_t p = std::min(x.precision(), y.precision());
         x.rescale(p);
         y.rescale(p);
         if(OP == OverflowPolicy::SATURATE)
         {
             using type = typename traits::promote<T>::type;
             type val   = static_cast<type>(x.raw()) - static_cast<type>(y.raw());
             val        = constant_expr<T>::saturate_cast(val);
             return fixed_point<T>(static_cast<T>(val), p, true);
         }
         else
         {
             return fixed_point<T>(x.raw() - y.raw(), p, true);
         }
     }
static fixed_point<T> tanh (fixed_point< T > x) inline static
Calculate the hyperbolic tangent of a fixed point number.
Parameters
[in] x Fixed point operand
Returns
Hyperbolic tangent of the operand
Definition at line 783 of file FixedPoint.h.
References arm_compute::test::fixed_point_arithmetic::detail::exp(), fixed_point< T >::precision(), and arm_compute::test::fixed_point_arithmetic::detail::tanh().
Referenced by arm_compute::test::fixed_point_arithmetic::detail::tanh().
     {
         uint8_t p = x.precision();
         // Constants
         auto const_one = fixed_point<T>(1, p);
         auto const_two = fixed_point<T>(2, p);
         auto exp2x = exp(const_two * x);
         auto num   = exp2x - const_one;
         auto den   = exp2x + const_one;
         auto tanh  = num / den;
         return tanh;
     }
static std::basic_ostream<T, traits>& write (std::basic_ostream< T, traits > & s, fixed_point< U > & x) inline static
Output stream operator.
Parameters
[in] s Output stream
[in] x Fixed point value
Returns
Reference output to updated stream
Definition at line 375 of file FixedPoint.h.
Referenced by arm_compute::test::fixed_point_arithmetic::detail::operator<<().
     {
         return s << static_cast<float>(x);
     }
The documentation for this struct was generated from the following file:
tests/validation/FixedPoint.h