Compute Library: CartesianProductDataset< T, U >::iterator Struct Reference
CartesianProductDataset< T, U >::iterator Struct Reference
Iterator for the dataset.
#include <CartesianProductDataset.h>
Public Member Functions
iterator (const T_noref *dataset1, const U_noref *dataset2)
iterator (const iterator &)=default
iterator & operator= (const iterator &)=default
iterator (iterator &&)=default
iterator & operator= (iterator &&)=default
~iterator ()=default
std::string description () const
CartesianProductDataset::type operator* () const
iterator & operator++ ()
Detailed Description
template<typename T, typename U>
struct arm_compute::test::framework::dataset::CartesianProductDataset< T, U >::iterator
Iterator for the dataset.
Definition at line 73 of file CartesianProductDataset.h.
Constructor & Destructor Documentation
iterator (const T_noref * dataset1, const U_noref * dataset2) inline
Definition at line 75 of file CartesianProductDataset.h.
References CartesianProductDataset< T, U >::iterator::operator=(), and CartesianProductDataset< T, U >::iterator::~iterator().
Referenced by CartesianProductDataset< framework::dataset::SingletonDataset< TensorShape >, framework::dataset::SingletonDataset< ActivationLayerInfo > >::begin().
             : _iter1{ dataset1->begin() },
               _dataset2{ dataset2 },
               _iter2{ dataset2->begin() }
         {
         }
iterator (const iterator &) default
iterator (iterator &&) default
~iterator () default
Referenced by CartesianProductDataset< T, U >::iterator::iterator().
Member Function Documentation
std::string description () const inline
Definition at line 89 of file CartesianProductDataset.h.
         {
             return _iter1.description() + ":" + _iter2.description();
         }
CartesianProductDataset::type operator* () const inline
Definition at line 94 of file CartesianProductDataset.h.
         {
             return std::tuple_cat(*_iter1, *_iter2);
         }
iterator& operator++ () inline
Definition at line 99 of file CartesianProductDataset.h.
References CartesianProductDataset< T, U >::size().
         {
             ++_second_pos;
             if(_second_pos < _dataset2->size())
             {
                 ++_iter2;
             }
             else
             {
                 _second_pos = 0;
                 _iter2      = _dataset2->begin();
                 ++_iter1;
             }
             return *this;
         }
iterator& operator= (const iterator &) default
Referenced by CartesianProductDataset< T, U >::iterator::iterator().
iterator& operator= (iterator &&) default
The documentation for this struct was generated from the following file:
tests/framework/datasets/CartesianProductDataset.h