Compute Library: constant_expr< T > Struct Template Reference
constant_expr< T > Struct Template Reference
#include <FixedPoint.h>
Static Public Member Functions
static constexpr T fixed_one (uint8_t p)
Calculate representation of 1 in fixed point given a fixed point precision.
static constexpr float fixed_step (uint8_t p)
Calculate fixed point precision step given a fixed point precision.
static constexpr float to_float (T val, uint8_t p)
Convert a fixed point value to float given its precision.
static constexpr T to_int (T val, uint8_t p)
Convert a fixed point value to integer given its precision.
static constexpr T to_fixed (float val, uint8_t p)
Convert a single precision floating point value to a fixed point representation given its precision.
static constexpr T clamp (T val, T min, T max)
Clamp value between two ranges.
template<typename U >
static constexpr T saturate_cast (U val)
Saturate given number.
Detailed Description
template<typename T>
struct arm_compute::test::fixed_point_arithmetic::detail::constant_expr< T >
Definition at line 48 of file FixedPoint.h.
Member Function Documentation
static constexpr T clamp (T val, T min, T max) inline static
Clamp value between two ranges.
Parameters
[in] val Value to clamp
[in] min Minimum value to clamp to
[in] max Maximum value to clamp to
Returns
clamped value
Definition at line 349 of file FixedPoint.h.
References arm_compute::test::fixed_point_arithmetic::detail::max(), and arm_compute::test::fixed_point_arithmetic::detail::min().
Referenced by functions::clamp().
     {
         return std::min(std::max(val, min), max);
     }
static constexpr T fixed_one (uint8_t p) inline static
Calculate representation of 1 in fixed point given a fixed point precision.
Parameters
[in] p Fixed point precision
Returns
Representation of value 1 in fixed point.
Definition at line 293 of file FixedPoint.h.
     {
         return (1 << p);
     }
static constexpr float fixed_step (uint8_t p) inline static
Calculate fixed point precision step given a fixed point precision.
Parameters
[in] p Fixed point precision
Returns
Fixed point precision step
Definition at line 303 of file FixedPoint.h.
     {
         return (1.0f / static_cast<float>(1 << p));
     }
static constexpr T saturate_cast (U val) inline static
Saturate given number.
Parameters
[in] val Value to saturate
Returns
Saturated value
Definition at line 360 of file FixedPoint.h.
References arm_compute::test::fixed_point_arithmetic::detail::max(), arm_compute::test::fixed_point_arithmetic::detail::min(), and arm_compute::U.
Referenced by functions::add(), functions::div(), fixed_point< T >::fixed_point(), functions::mul(), functions::negate(), fixed_point< T >::operator fixed_point< U >(), fixed_point< T >::rescale(), functions::shift_left(), and functions::sub().
     {
         return static_cast<T>(std::min<U>(std::max<U>(val, static_cast<U>(std::numeric_limits<T>::min())), static_cast<U>(std::numeric_limits<T>::max())));
     }
static constexpr T to_fixed (float val, uint8_t p) inline static
Convert a single precision floating point value to a fixed point representation given its precision.
Parameters
[in] val Floating point value
[in] p Fixed point precision
Returns
The raw fixed point representation
Definition at line 337 of file FixedPoint.h.
References arm_compute::test::saturate_cast().
     {
         return static_cast<T>(saturate_cast<float>(val * fixed_one(p) + ((val >= 0) ? 0.5 : -0.5)));
     }
static constexpr float to_float (T val, uint8_t p) inline static
Convert a fixed point value to float given its precision.
Parameters
[in] val Fixed point value
[in] p Fixed point precision
Returns
Float representation of the fixed point number
Definition at line 315 of file FixedPoint.h.
Referenced by fixed_point< T >::operator float().
     {
         return static_cast<float>(val * fixed_step(p));
     }
static constexpr T to_int (T val, uint8_t p) inline static
Convert a fixed point value to integer given its precision.
Parameters
[in] val Fixed point value
[in] p Fixed point precision
Returns
Integer of the fixed point number
Definition at line 326 of file FixedPoint.h.
Referenced by functions::exp(), and fixed_point< T >::operator U().
     {
         return val >> p;
     }
The documentation for this struct was generated from the following file:
tests/validation/FixedPoint.h