Compute Library: tests/validation/main.cpp File Reference
main.cpp File Reference
#include "Globals.h"
#include "TensorLibrary.h"
#include "Utils.h"
#include "ValidationProgramOptions.h"
#include "ValidationUserConfiguration.h"
#include "arm_compute/runtime/Scheduler.h"
#include "boost_wrapper.h"
#include <iostream>
#include <memory>
#include <random>
Namespaces
arm_compute
arm_compute::test
Macros
#define BOOST_TEST_ALTERNATIVE_INIT_API
Functions
BOOST_GLOBAL_FIXTURE (GlobalFixture)
bool init_unit_test ()
Macro Definition Documentation
#define BOOST_TEST_ALTERNATIVE_INIT_API
Definition at line 24 of file main.cpp.
Function Documentation
BOOST_GLOBAL_FIXTURE (GlobalFixture)
bool init_unit_test ()
Definition at line 71 of file main.cpp.
References Scheduler::get(), ProgramOptions::get_help(), ProgramOptions::parse_commandline(), IScheduler::set_num_threads(), arm_compute::test::user_config, and ProgramOptions::wants_help().
 {
     boost::unit_test::framework::master_test_suite().p_name.value = "Compute Library Validation Tests";
     ValidationProgramOptions options;
     int   &argc = boost::unit_test::framework::master_test_suite().argc;
     char **argv = boost::unit_test::framework::master_test_suite().argv;
     try
     {
         options.parse_commandline(argc, argv);
         if(options.wants_help())
         {
             std::cout << "Usage: " << argv[0] << " [options] PATH\n";
             std::cout << options.get_help() << "\n";
             return false;
         }
         user_config = ValidationUserConfiguration(options);
     }
     catch(const boost::program_options::required_option &err)
     {
         std::cerr << "Error: " << err.what() << "\n";
         std::cout << "\nUsage: " << argv[0] << " [options] PATH\n";
         std::cout << options.get_help() << "\n";
         return false;
     }
     std::cout << "Using " << user_config.threads << " CPU " << (user_config.threads == 1 ? "thread" : "threads") << "\n";
     arm_compute::Scheduler::get().set_num_threads(user_config.threads);
     return true;
 }