Compute Library: src/core/CL/cl_kernels/warp_helpers_quantized.h File Reference
warp_helpers_quantized.h File Reference
#include "helpers_asymm.h"
Functions
const float8 clamp_to_border_with_size_quantized (float8 coords, const float width, const float height, const float border_size)
Clamps the given coordinates to the borders according to the border size.
const float8 clamp_to_border_quantized (float8 coords, const float width, const float height)
Clamps the given coordinates to the borders.
const float8 get_neighbour_coords_quantized (const float2 coord)
Given a texel coordinates this function will return the following array of coordinates: [ P, right neighbour, below neighbour, below right neighbour ].
const float2 get_current_coords_quantized ()
Returns the current thread coordinates.
const DATA_TYPE4 bilinear_interpolate_with_border_quantized (const Image *in, const float8 coords, const float width, const float height, const float border_size, const float scale, const int offset_qasymm)
Computes the bilinear interpolation for each set of coordinates in the vector coords and returns the values.
const DATA_TYPE4 bilinear_interpolate_quantized (const Image *in, const float8 coords, const float width, const float height, const float scale, const int offset_qasymm)
Computes the bilinear interpolation for each set of coordinates in the vector coords and returns the values.
Function Documentation
bilinear_interpolate_quantized()
const DATA_TYPE4 bilinear_interpolate_quantized (const Image * in, const float8 coords, const float width, const float height, const float scale, const int offset_qasymm) inline
Computes the bilinear interpolation for each set of coordinates in the vector coords and returns the values.
Parameters
[in] in Pointer to the source image.
[in] coords Vector of four 2D coordinates. Even pos is x and odd y.
[in] width Width of the image
[in] height Height of the image
[in] scale Scale value
[in] offset_qasymm Offset value
Definition at line 135 of file warp_helpers_quantized.h.
 {
     return bilinear_interpolate_with_border_quantized(in, coords, width, height, 1, scale, offset_qasymm);
 }
References bilinear_interpolate_with_border_quantized(), and arm_compute::test::validation::scale.
bilinear_interpolate_with_border_quantized()
const DATA_TYPE4 bilinear_interpolate_with_border_quantized (const Image * in, const float8 coords, const float width, const float height, const float border_size, const float scale, const int offset_qasymm) inline
Computes the bilinear interpolation for each set of coordinates in the vector coords and returns the values.
Parameters
[in] in Pointer to the source image.
[in] coords Vector of four 2D coordinates. Even pos is x and odd y.
[in] width Width of the image
[in] height Height of the image
[in] border_size Border size
[in] scale Scale value
[in] offset_qasymm Offset value
Definition at line 84 of file warp_helpers_quantized.h.
 {
     // If any of the 4 texels is out of the image's boundaries we use the border value (REPLICATE or CONSTANT) for any texel out of the image.
     // Sets the 4x4 coordinates for each of the four input texels
     const float8  fc = floor(coords);
     const float16 c1 = (float16)(
                            clamp_to_border_with_size_quantized(get_neighbour_coords_quantized((float2)(fc.s0, fc.s1)), width, height, border_size),
                            clamp_to_border_with_size_quantized(get_neighbour_coords_quantized((float2)(fc.s2, fc.s3)), width, height, border_size));
     const float16 c2 = (float16)(
                            clamp_to_border_with_size_quantized(get_neighbour_coords_quantized((float2)(fc.s4, fc.s5)), width, height, border_size),
                            clamp_to_border_with_size_quantized(get_neighbour_coords_quantized((float2)(fc.s6, fc.s7)), width, height, border_size));
     // Loads the values from the input image
     const int16 t = (int16)(
                         /* tl, tr, bl, br */
                         * ((__global DATA_TYPE *)offset(in, c1.s0, c1.s1)), *((__global DATA_TYPE *)offset(in, c1.s2, c1.s3)),
                         *((__global DATA_TYPE *)offset(in, c1.s4, c1.s5)), *((__global DATA_TYPE *)offset(in, c1.s6, c1.s7)),
                         *((__global DATA_TYPE *)offset(in, c1.s8, c1.s9)), *((__global DATA_TYPE *)offset(in, c1.sa, c1.sb)),
                         *((__global DATA_TYPE *)offset(in, c1.sc, c1.sd)), *((__global DATA_TYPE *)offset(in, c1.se, c1.sf)),
                         *((__global DATA_TYPE *)offset(in, c2.s0, c2.s1)), *((__global DATA_TYPE *)offset(in, c2.s2, c2.s3)),
                         *((__global DATA_TYPE *)offset(in, c2.s4, c2.s5)), *((__global DATA_TYPE *)offset(in, c2.s6, c2.s7)),
                         *((__global DATA_TYPE *)offset(in, c2.s8, c2.s9)), *((__global DATA_TYPE *)offset(in, c2.sa, c2.sb)),
                         *((__global DATA_TYPE *)offset(in, c2.sc, c2.sd)), *((__global DATA_TYPE *)offset(in, c2.se, c2.sf)));
     const float16 inf32 = convert_float16(t - (int16)offset_qasymm) * (float16)scale;
     const float8 a  = coords - fc;
     const float8 b  = ((float8)(1.f)) - a;
     const float4 fr = (float4)(
                           ((inf32.s0 * b.s0 * b.s1) + (inf32.s1 * a.s0 * b.s1) + (inf32.s2 * b.s0 * a.s1) + (inf32.s3 * a.s0 * a.s1)),
                           ((inf32.s4 * b.s2 * b.s3) + (inf32.s5 * a.s2 * b.s3) + (inf32.s6 * b.s2 * a.s3) + (inf32.s7 * a.s2 * a.s3)),
                           ((inf32.s8 * b.s4 * b.s5) + (inf32.s9 * a.s4 * b.s5) + (inf32.sa * b.s4 * a.s5) + (inf32.sb * a.s4 * a.s5)),
                           ((inf32.sc * b.s6 * b.s7) + (inf32.sd * a.s6 * b.s7) + (inf32.se * b.s6 * a.s7) + (inf32.sf * a.s6 * a.s7)));
     const uchar4 res = convert_uchar4_sat(convert_int4_sat_rtp(fr / scale) + offset_qasymm);
     return res;
 }
References arm_compute::test::validation::b, clamp_to_border_with_size_quantized(), DATA_TYPE, get_neighbour_coords_quantized(), offset(), and arm_compute::test::validation::scale.
Referenced by bilinear_interpolate_quantized(), and scale_bilinear_quantized_nchw().
clamp_to_border_quantized()
const float8 clamp_to_border_quantized (float8 coords, const float width, const float height) inline
Clamps the given coordinates to the borders.
Parameters
[in] coords Vector of 2D coordinates to clamp. Even positions are X coords, odd positions are Y coords.
[in] width Width of the image
[in] height Height of the image
Definition at line 49 of file warp_helpers_quantized.h.
 {
     return clamp_to_border_with_size_quantized(coords, width, height, 1);
 }
References clamp_to_border_with_size_quantized().
clamp_to_border_with_size_quantized()
const float8 clamp_to_border_with_size_quantized (float8 coords, const float width, const float height, const float border_size) inline
Clamps the given coordinates to the borders according to the border size.
Parameters
[in] coords Vector of 2D coordinates to clamp. Even positions are X coords, odd positions are Y coords.
[in] width Width of the image
[in] height Height of the image
[in] border_size Border size of the image
Definition at line 34 of file warp_helpers_quantized.h.
 {
     const float4 clamped_x = clamp(coords.even, 0.0f - border_size, width - 1 + border_size);
     const float4 clamped_y = clamp(coords.odd, 0.0f - border_size, height - 1 + border_size);
     return (float8)(clamped_x.s0, clamped_y.s0, clamped_x.s1, clamped_y.s1, clamped_x.s2, clamped_y.s2, clamped_x.s3, clamped_y.s3);
 }
References arm_compute::utility::clamp().
Referenced by bilinear_interpolate_with_border_quantized(), and clamp_to_border_quantized().
get_current_coords_quantized()
const float2 get_current_coords_quantized () inline
Returns the current thread coordinates.
Definition at line 69 of file warp_helpers_quantized.h.
 {
     return (float2)(get_global_id(0) * 4, get_global_id(1));
 }
Referenced by scale_bilinear_quantized_nchw().
get_neighbour_coords_quantized()
const float8 get_neighbour_coords_quantized (const float2 coord) inline
Given a texel coordinates this function will return the following array of coordinates: [ P, right neighbour, below neighbour, below right neighbour ].
Note
No checks to see if the coordinates are out of the image are done here.
Parameters
[in] coord Input coordinates
Returns
vector of 8 floats with the coordinates, even positions are x and odd y.
Definition at line 63 of file warp_helpers_quantized.h.
 {
     return (float8)(/*tl*/ coord.s0, coord.s1, /*tr*/ coord.s0 + 1, coord.s1, /*bl*/ coord.s0, coord.s1 + 1, /*br*/ coord.s0 + 1, coord.s1 + 1);
 }
Referenced by bilinear_interpolate_with_border_quantized().