Compute Library: GpuMatMul Class Reference
GpuMatMul Class Reference final
Operator interface.
#include <GpuMatMul.h>
Public Types
using Attributes = MatMulAttributes
using Settings = GpuMatMulSettings
Static Public Member Functions
static ITensorInfo * create_op (GpuWorkloadSketch &sketch, ITensorInfo *lhs, ITensorInfo *rhs, const Attributes &attributes, const Settings &settings)
static Status is_supported_op (const GpuWorkloadContext &context, const ITensorInfo *lhs, const ITensorInfo *rhs, const Attributes &attributes, const Settings &settings)
static Status validate_op (const GpuWorkloadSketch &sketch, const ITensorInfo *lhs, const ITensorInfo *rhs, const Attributes &attributes, const Settings &settings)
Detailed Description
Operator interface.
Definition at line 68 of file GpuMatMul.h.
Member Typedef Documentation
Attributes
using Attributes = MatMulAttributes
Definition at line 72 of file GpuMatMul.h.
Settings
using Settings = GpuMatMulSettings
Definition at line 74 of file GpuMatMul.h.
Member Function Documentation
create_op()
ITensorInfo * create_op (GpuWorkloadSketch & sketch, ITensorInfo * lhs, ITensorInfo * rhs, const Attributes & attributes, const Settings & settings) static
Definition at line 191 of file GpuMatMul.cpp.
 {
     ARM_COMPUTE_LOG_PARAMS(lhs, rhs, attributes, settings);
     ITensorInfo *dst = sketch.implementation().create_virtual_tensor();
     // Assert validation
     ARM_COMPUTE_ERROR_THROW_ON(GpuMatMul::validate_op(sketch, lhs, rhs, attributes, settings));
     ARM_COMPUTE_ERROR_ON_NULLPTR(lhs, rhs, dst);
     // Auto initialize dst tensor
     calculate_and_init_dst_if_empty(dst, lhs, rhs, attributes, settings);
     // Translate into components and add to component graph
     auto      &comp_graph = sketch.implementation().component_graph();
     const auto sketch_ctx = sketch.implementation().context();
     if (sketch_ctx->gpu_language() == GpuLanguage::OpenCL)
     {
         auto properties = IGpuKernelComponent::Properties();
         properties.stage(UnitWorkloadStage{UnitWorkloadStage::Stage::Run});
         ArgumentPack<ITensorInfo> arguments;
         arguments.add_const_tensor(ACL_SRC_0, lhs);
         arguments.add_const_tensor(ACL_SRC_1, rhs);
         arguments.add_const_tensor(ACL_DST_0, dst);
         comp_graph.add_new_component<ClComponentMatMul>(properties, arguments, attributes, settings);
     }
     else
     {
         ARM_COMPUTE_ERROR("Unimplemented Gpu language");
     }
     // Set up fusion test by adding to the Operator Group
     // Note this has to be performed after all the components have been successfully added to the component graph
     // Pack tensor infos
     ArgumentPack<ITensorInfo> tensors;
     tensors.add_const_tensor(ACL_SRC_0, lhs);
     tensors.add_const_tensor(ACL_SRC_1, rhs);
     tensors.add_const_tensor(ACL_DST_0, dst);
     const auto op = sketch.implementation().operator_group().new_operator(operator_type, tensors);
     sketch.implementation().operator_group().add_operator(op);
     return dst;
 }
References arm_compute::ACL_DST_0, arm_compute::ACL_SRC_0, arm_compute::ACL_SRC_1, ArgumentPack< T >::add_const_tensor(), GpuOperatorGroup::add_operator(), ARM_COMPUTE_ERROR, ARM_COMPUTE_ERROR_ON_NULLPTR, ARM_COMPUTE_ERROR_THROW_ON, ARM_COMPUTE_LOG_PARAMS, GpuWorkloadSketch::Implementation::component_graph(), GpuWorkloadSketch::Implementation::context(), GpuWorkloadSketch::Implementation::create_virtual_tensor(), arm_compute::test::validation::dst, GpuWorkloadSketch::implementation(), GpuOperatorGroup::new_operator(), arm_compute::experimental::dynamic_fusion::OpenCL, GpuWorkloadSketch::Implementation::operator_group(), UnitWorkloadStage::Run, arm_compute::test::validation::sketch, and GpuMatMul::validate_op().
is_supported_op()
Status is_supported_op (const GpuWorkloadContext & context, const ITensorInfo * lhs, const ITensorInfo * rhs, const Attributes & attributes, const Settings & settings) static
Definition at line 151 of file GpuMatMul.cpp.
 {
     return is_supported_op_helper(context, lhs, rhs, nullptr, attributes, settings);
 }
References arm_compute::test::validation::context.
validate_op()
Status validate_op (const GpuWorkloadSketch & sketch, const ITensorInfo * lhs, const ITensorInfo * rhs, const Attributes & attributes, const Settings & settings) static
Definition at line 160 of file GpuMatMul.cpp.
 {
     ARM_COMPUTE_RETURN_ERROR_ON_NULLPTR(lhs, rhs);
     // Check if tensors have valid id. I.e. they are created from a sketch
     ARM_COMPUTE_RETURN_ERROR_ON(!lhs->has_valid_id() || !rhs->has_valid_id());
     // Refer to GpuMatmul::validate_op() for id-validness of this TensorInfo object
     TensorInfo dst_info_to_validate;
     // Auto initialize dst tensor info
     calculate_and_init_dst_if_empty(&dst_info_to_validate, lhs, rhs, attributes, settings);
     // Perform fusion test
     // Check if operator meets fusion constraints
     ArgumentPack<ITensorInfo> tensors;
     tensors.add_const_tensor(ACL_SRC_0, lhs);
     tensors.add_const_tensor(ACL_SRC_1, rhs);
     tensors.add_const_tensor(ACL_DST_0, &dst_info_to_validate);
     const auto op = sketch.implementation().operator_group().new_operator(operator_type, tensors);
     ARM_COMPUTE_RETURN_ERROR_ON_MSG(!sketch.implementation().operator_group().try_add_operator(op),
                                     "Operator fusion test failed. This operator cannot be fused into the workload");
     // Check if configuration is supported
     return is_supported_op_helper(*sketch.gpu_context(), lhs, rhs, &dst_info_to_validate, attributes, settings);
 }
References arm_compute::ACL_DST_0, arm_compute::ACL_SRC_0, arm_compute::ACL_SRC_1, ArgumentPack< T >::add_const_tensor(), ARM_COMPUTE_RETURN_ERROR_ON, ARM_COMPUTE_RETURN_ERROR_ON_MSG, ARM_COMPUTE_RETURN_ERROR_ON_NULLPTR, GpuWorkloadSketch::gpu_context(), ITensorInfo::has_valid_id(), GpuWorkloadSketch::implementation(), GpuOperatorGroup::new_operator(), GpuWorkloadSketch::Implementation::operator_group(), arm_compute::test::validation::sketch, and GpuOperatorGroup::try_add_operator().
Referenced by GpuMatMul::create_op().
The documentation for this class was generated from the following files:
arm_compute/dynamic_fusion/sketch/gpu/operators/GpuMatMul.h
src/dynamic_fusion/sketch/gpu/operators/GpuMatMul.cpp