Compute Library: CPUInfo Class Reference
CPUInfo Class Reference final
#include <CPPTypes.h>
Public Member Functions
CPUInfo (CPUInfo const &)=delete
CPUInfo (CPUInfo &&)=delete
CPUInfo & operator= (CPUInfo const &)=delete
CPUInfo & operator= (CPUInfo &&)=delete
bool has_fp16 () const
Checks if the cpu model supports fp16.
bool has_bf16 () const
Checks if the cpu model supports bf16.
bool has_svebf16 () const
Checks if the cpu model supports bf16.
bool has_dotprod () const
Checks if the cpu model supports dot product.
bool has_svef32mm () const
Checks if the cpu model supports floating-point matrix multiplication.
bool has_i8mm () const
Checks if the cpu model supports integer matrix multiplication.
bool has_svei8mm () const
Checks if the cpu model supports integer matrix multiplication.
bool has_sve () const
Checks if the cpu model supports sve.
bool has_sve2 () const
Checks if the cpu model supports sve2.
bool has_sme () const
Checks if the cpu model supports sme.
bool has_sme2 () const
Checks if the cpu model supports sme2.
CPUModel get_cpu_model (unsigned int cpuid) const
Gets the cpu model for a given cpuid.
CPUModel get_cpu_model () const
Gets the current thread's cpu model.
cpuinfo::CpuIsaInfo get_isa () const
Gets the current cpu's ISA information.
unsigned int get_L1_cache_size () const
Gets the L1 cache size.
unsigned int get_L2_cache_size () const
Gets the L2 cache size.
unsigned int get_cpu_num () const
Return the maximum number of CPUs present.
unsigned int get_cpu_num_excluding_little () const
Return the maximum number of CPUs present excluding the little cores in case of an Android device.
unsigned long get_sme2_vector_length () const
Return the vector length in bytes for sme2.
Static Public Member Functions
static CPUInfo & get ()
Access the KernelLibrary singleton.
Detailed Description
Definition at line 66 of file CPPTypes.h.
Constructor & Destructor Documentation
CPUInfo() [1/2]
CPUInfo (CPUInfo const &) delete
CPUInfo() [2/2]
CPUInfo (CPUInfo &&) delete
Member Function Documentation
get()
CPUInfo & get () static
Access the KernelLibrary singleton.
This method has been deprecated and will be removed in future releases
Returns
The KernelLibrary instance.
Definition at line 42 of file CPPTypes.cpp.
 {
     static CPUInfo _cpuinfo;
     return _cpuinfo;
 }
Referenced by CpuFloorKernel::configure(), CpuSoftmaxKernel::configure(), CpuPool2dKernel::configure(), CpuActivationKernel::configure(), CpuMaxUnpoolingLayerKernel::configure(), CpuElementwiseUnaryKernel::configure(), CpuPool3dKernel::configure(), CpuSubKernel::configure(), CpuGemmMatrixAdditionKernel::configure(), CpuAddMulAddKernel::configure(), CpuDirectConv3dKernel::configure(), CpuDepthwiseConv2dNativeKernel::configure(), NEFuseBatchNormalizationKernel::configure(), CpuGemmMatrixMultiplyKernel::configure(), CpuScaleKernel::configure(), CpuAddKernel::configure(), IScheduler::cpu_info(), arm_compute::error_on_unsupported_cpu_bf16(), arm_compute::error_on_unsupported_cpu_fp16(), arm_compute::scale_utils::is_precomputation_required(), NEBatchNormalizationLayerKernel::run(), CpuDirectConv2dKernel::run_op(), CpuCastKernel::run_op(), and CpuElementwiseUnaryKernel::validate().
get_cpu_model() [1/2]
CPUModel get_cpu_model () const
Gets the current thread's cpu model.
Returns
Current thread's CPUModel
Definition at line 115 of file CPPTypes.cpp.
 {
     return _impl->info.cpu_model();
 }
get_cpu_model() [2/2]
CPUModel get_cpu_model (unsigned int cpuid) const
Gets the cpu model for a given cpuid.
Parameters
[in] cpuid the id of the cpu core to be retrieved,
Returns
the CPUModel of the cpuid queiried.
Definition at line 120 of file CPPTypes.cpp.
 {
     return _impl->info.cpu_model(cpuid);
 }
Referenced by CpuSubKernel::get_mws(), CpuAddKernel::get_mws(), CpuMulKernel::get_mws(), CpuArithmeticKernel::get_mws(), CpuDivisionKernel::get_mws(), and main().
get_cpu_num()
unsigned int get_cpu_num () const
Return the maximum number of CPUs present.
Returns
Number of CPUs
Definition at line 55 of file CPPTypes.cpp.
 {
     return _impl->info.num_cpus();
 }
Referenced by CPUInfo::get_cpu_num_excluding_little(), and main().
get_cpu_num_excluding_little()
unsigned int get_cpu_num_excluding_little () const
Return the maximum number of CPUs present excluding the little cores in case of an Android device.
Returns
Number of CPUs excluding little
Definition at line 151 of file CPPTypes.cpp.
 {
 #if defined(__ANDROID__)
     return _impl->info.not_little_num_cpus();
 #else  /* defined(__ANDROID__) */
     return get_cpu_num();
 #endif /* defined(__ANDROID__) */
 }
References CPUInfo::get_cpu_num().
get_isa()
cpuinfo::CpuIsaInfo get_isa () const
Gets the current cpu's ISA information.
Returns
Current cpu's ISA information
Definition at line 125 of file CPPTypes.cpp.
 {
     return _impl->info.isa();
 }
Referenced by CpuPool2dKernel::configure(), NEFuseBatchNormalizationKernel::configure(), CpuDepthwiseConv2dNativeKernel::configure(), and CpuCastKernel::run_op().
get_L1_cache_size()
unsigned int get_L1_cache_size () const
Gets the L1 cache size.
Returns
the size of the L1 cache
Definition at line 130 of file CPPTypes.cpp.
 {
     return _impl->L1_cache_size;
 }
get_L2_cache_size()
unsigned int get_L2_cache_size () const
Gets the L2 cache size.
Returns
the size of the L1 cache
Definition at line 135 of file CPPTypes.cpp.
 {
     return _impl->L2_cache_size;
 }
get_sme2_vector_length()
unsigned long get_sme2_vector_length () const
Return the vector length in bytes for sme2.
Returns
Vector length if sme2 is enabled, otherwise returns 0.
Definition at line 140 of file CPPTypes.cpp.
 {
 #ifdef ARM_COMPUTE_ENABLE_SME2
     if (this->has_sme2())
         return arm_gemm::utils::sme::get_vector_length<int8_t>();
     else
         return 0;
 #else  // ARM_COMPUTE_ENABLE_SME2
     return 0;
 #endif // ARM_COMPUTE_ENABLE_SME2
 }
References CPUInfo::has_sme2().
has_bf16()
bool has_bf16 () const
Checks if the cpu model supports bf16.
Returns
true if the cpu supports bf16, false otherwise
Definition at line 65 of file CPPTypes.cpp.
 {
     return _impl->info.has_bf16();
 }
Referenced by arm_compute::error_on_unsupported_cpu_bf16(), and main().
has_dotprod()
bool has_dotprod () const
Checks if the cpu model supports dot product.
Returns
true if the cpu supports dot product, false otherwise
Definition at line 75 of file CPPTypes.cpp.
 {
     return _impl->info.has_dotprod();
 }
Referenced by main().
has_fp16()
bool has_fp16 () const
Checks if the cpu model supports fp16.
Returns
true if the cpu supports fp16, false otherwise
Definition at line 60 of file CPPTypes.cpp.
 {
     return _impl->info.has_fp16();
 }
Referenced by arm_compute::error_on_unsupported_cpu_fp16(), and main().
has_i8mm()
bool has_i8mm () const
Checks if the cpu model supports integer matrix multiplication.
Returns
true if the cpu supports integer matrix multiplication, false otherwise
Definition at line 85 of file CPPTypes.cpp.
 {
     return _impl->info.has_i8mm();
 }
Referenced by main().
has_sme()
bool has_sme () const
Checks if the cpu model supports sme.
Returns
true if the cpu supports sme, false otherwise
Definition at line 105 of file CPPTypes.cpp.
 {
     return _impl->info.has_sme();
 }
Referenced by main().
has_sme2()
bool has_sme2 () const
Checks if the cpu model supports sme2.
Returns
true if the cpu supports sme2, false otherwise
Definition at line 110 of file CPPTypes.cpp.
 {
     return _impl->info.has_sme2();
 }
Referenced by CPUInfo::get_sme2_vector_length(), and main().
has_sve()
bool has_sve () const
Checks if the cpu model supports sve.
Returns
true if the cpu supports sve, false otherwise
Definition at line 95 of file CPPTypes.cpp.
 {
     return _impl->info.has_sve();
 }
Referenced by main().
has_sve2()
bool has_sve2 () const
Checks if the cpu model supports sve2.
Returns
true if the cpu supports sve2, false otherwise
Definition at line 100 of file CPPTypes.cpp.
 {
     return _impl->info.has_sve2();
 }
Referenced by main().
has_svebf16()
bool has_svebf16 () const
Checks if the cpu model supports bf16.
Returns
true if the cpu supports bf16, false otherwise
Definition at line 70 of file CPPTypes.cpp.
 {
     return _impl->info.has_svebf16();
 }
Referenced by main().
has_svef32mm()
bool has_svef32mm () const
Checks if the cpu model supports floating-point matrix multiplication.
Returns
true if the cpu supports floating-point matrix multiplication, false otherwise
Definition at line 80 of file CPPTypes.cpp.
 {
     return _impl->info.has_svef32mm();
 }
Referenced by main().
has_svei8mm()
bool has_svei8mm () const
Checks if the cpu model supports integer matrix multiplication.
Returns
true if the cpu supports integer matrix multiplication, false otherwise
Definition at line 90 of file CPPTypes.cpp.
 {
     return _impl->info.has_svei8mm();
 }
Referenced by main().
operator=() [1/2]
CPUInfo& operator= (CPUInfo &&) delete
operator=() [2/2]
CPUInfo& operator= (CPUInfo const &) delete
The documentation for this class was generated from the following files:
arm_compute/core/CPP/CPPTypes.h
src/core/CPP/CPPTypes.cpp