Compute Library: CLAuxTensorHandler Class Reference
CLAuxTensorHandler Class Reference
Tensor handler to wrap and handle tensor allocations on workspace buffers.
#include <ClAuxTensorHandler.h>
Public Member Functions
CLAuxTensorHandler (int slot_id, TensorInfo &info, ITensorPack &pack, bool pack_inject=false, bool bypass_alloc=false, bool bypass_import=false)
Create a temporary tensor handle, by either important an existing tensor from a tensor pack, or allocating a new one.
CLAuxTensorHandler (TensorInfo &info, ICLTensor &tensor, bool bypass_import=false)
Create a temporary handle to the original tensor with a new TensorInfo This is useful if we want to change a tensor's tensor info at run time without modifying the original tensor.
CLAuxTensorHandler (const CLAuxTensorHandler &)=delete
CLAuxTensorHandler & operator= (const CLAuxTensorHandler)=delete
~CLAuxTensorHandler ()
ICLTensor * get ()
ICLTensor * operator() ()
Detailed Description
Tensor handler to wrap and handle tensor allocations on workspace buffers.
Note
About memory handling using bypass_* flags See arm_compute::cpu::CpuAuxTensorHandler
Definition at line 43 of file ClAuxTensorHandler.h.
Constructor & Destructor Documentation
CLAuxTensorHandler() [1/3]
CLAuxTensorHandler (int slot_id, TensorInfo & info, ITensorPack & pack, bool pack_inject = false, bool bypass_alloc = false, bool bypass_import = false) inline
Create a temporary tensor handle, by either important an existing tensor from a tensor pack, or allocating a new one.
Parameters
[in] slot_id Slot id of the tensor to be retrieved in the tensor pack If no such tensor exists in the tensor pack, a new tensor will be allocated.
[in] info Tensor info containing requested size of the new tensor. If requested size is larger than the tensor retrieved from the tensor pack, a new tensor will be allocated.
[in,out] pack Tensor pack to retrieve the old tensor. When pack_inject is true, the new tensor will also be added here.
[in] pack_inject In case of a newly allocated tensor, whether to add this tensor back to the pack
[in] bypass_alloc Bypass allocation in case of a new tensor This is to prevent unnecessary memory operations when the handler object is not used
[in] bypass_import Bypass importation in case of a retrieved tensor This is to prevent unnecessary memory operations when the handler object is not used
Definition at line 65 of file ClAuxTensorHandler.h.
         : _tensor()
     {
         if (info.total_size() == 0)
         {
             return;
         }
         _tensor.allocator()->soft_init(info);
         ICLTensor *packed_tensor = utils::cast::polymorphic_downcast<ICLTensor *>(pack.get_tensor(slot_id));
         if ((packed_tensor == nullptr) || (info.total_size() > packed_tensor->info()->total_size()))
         {
             if (!bypass_alloc)
             {
                 _tensor.allocator()->allocate();
                 ARM_COMPUTE_LOG_INFO_WITH_FUNCNAME_ACL("Allocating auxiliary tensor");
             }
             if (pack_inject)
             {
                 pack.add_tensor(slot_id, &_tensor);
                 _injected_tensor_pack = &pack;
                 _injected_slot_id     = slot_id;
             }
         }
         else
         {
             if (!bypass_import)
             {
                 _tensor.allocator()->import_memory(packed_tensor->cl_buffer());
             }
         }
     }
References ITensorPack::add_tensor(), CLTensorAllocator::allocate(), CLTensor::allocator(), ARM_COMPUTE_LOG_INFO_WITH_FUNCNAME_ACL, ICLTensor::cl_buffer(), ITensorPack::get_tensor(), CLTensorAllocator::import_memory(), ITensor::info(), arm_compute::test::validation::info, arm_compute::test::validation::pack, ITensorAllocator::soft_init(), and ITensorInfo::total_size().
CLAuxTensorHandler() [2/3]
CLAuxTensorHandler (TensorInfo & info, ICLTensor & tensor, bool bypass_import = false) inline
Create a temporary handle to the original tensor with a new TensorInfo This is useful if we want to change a tensor's tensor info at run time without modifying the original tensor.
Parameters
[in] info New tensor info to "assign" to tensor
[in] tensor Tensor to be assigned a new TensorInfo
[in] bypass_import Bypass importing tensor's memory into the handler. This is to prevent unnecessary memory operations when the handler object is not used
Definition at line 112 of file ClAuxTensorHandler.h.
                                                                                         : _tensor()
     {
         _tensor.allocator()->soft_init(info);
         if (!bypass_import)
         {
             ARM_COMPUTE_ERROR_ON(tensor.info() == nullptr);
             if (info.total_size() <= tensor.info()->total_size())
             {
                 _tensor.allocator()->import_memory(tensor.cl_buffer());
             }
         }
     }
References CLTensor::allocator(), ARM_COMPUTE_ERROR_ON, CLTensorAllocator::import_memory(), arm_compute::test::validation::info, ITensorAllocator::soft_init(), and tensor.
CLAuxTensorHandler() [3/3]
CLAuxTensorHandler (const CLAuxTensorHandler &) delete
~CLAuxTensorHandler()
~CLAuxTensorHandler () inline
Definition at line 128 of file ClAuxTensorHandler.h.
     {
         if (_injected_tensor_pack)
         {
             _injected_tensor_pack->remove_tensor(_injected_slot_id);
         }
     }
References ITensorPack::remove_tensor().
Member Function Documentation
get()
ICLTensor* get () inline
Definition at line 136 of file ClAuxTensorHandler.h.
     {
         return &_tensor;
     }
Referenced by ClFullyConnected::prepare(), ClGemmLowpMatrixMultiplyCore::prepare(), ClGemm::prepare(), ClWinogradConv2d::prepare(), ClGemmConv2d::prepare(), ClSoftmax::run(), ClIndirectConv2d::run(), ClFullyConnected::run(), ClGemmLowpMatrixMultiplyCore::run(), ClGemm::run(), ClWinogradConv2d::run(), and ClGemmConv2d::run().
operator()()
ICLTensor* operator() () inline
Definition at line 141 of file ClAuxTensorHandler.h.
     {
         return &_tensor;
     }
operator=()
CLAuxTensorHandler& operator= (const CLAuxTensorHandler) delete
The documentation for this class was generated from the following file:
src/gpu/cl/utils/ClAuxTensorHandler.h