Compute Library: src/core/CL/cl_kernels/activation_layer_qa8.cl File Reference
activation_layer_qa8.cl File Reference
#include "helpers.h"
Macros
#define TYPE VEC_DATA_TYPE(DATA_TYPE, VEC_SIZE)
#define ACTIVATION_OP2(op, x) op##_op(x)
#define ACTIVATION_OP(op, x) ACTIVATION_OP2(op, x)
Functions
DATA_TYPEVEC_SIZE brelu_op (DATA_TYPEVEC_SIZE x)
DATA_TYPEVEC_SIZE lu_brelu_op (DATA_TYPEVEC_SIZE x)
__kernel void activation_layer_qa8 (__global uchar *input_ptr, uint input_stride_x, uint input_step_x, uint input_stride_y, uint input_step_y, uint input_stride_z, uint input_step_z, uint input_offset_first_element_in_bytes, __global uchar *output_ptr, uint output_stride_x, uint output_step_x, uint output_stride_y, uint output_step_y, uint output_stride_z, uint output_step_z, uint output_offset_first_element_in_bytes)
This performs an activation function on QASYMM8 inputs.
Macro Definition Documentation
#define ACTIVATION_OP (op, x) ACTIVATION_OP2(op, x)
Definition at line 40 of file activation_layer_qa8.cl.
Referenced by activation_layer_qa8().
#define ACTIVATION_OP2 (op, x) op##_op(x)
Definition at line 39 of file activation_layer_qa8.cl.
#define TYPE VEC_DATA_TYPE(DATA_TYPE, VEC_SIZE)
Definition at line 26 of file activation_layer_qa8.cl.
Referenced by activation_layer_qa8(), brelu_op(), and lu_brelu_op().
Function Documentation
__kernel void activation_layer_qa8 (__global uchar * input_ptr, uint input_stride_x, uint input_step_x, uint input_stride_y, uint input_step_y, uint input_stride_z, uint input_step_z, uint input_offset_first_element_in_bytes, __global uchar * output_ptr, uint output_stride_x, uint output_step_x, uint output_stride_y, uint output_step_y, uint output_stride_z, uint output_step_z, uint output_offset_first_element_in_bytes)
This performs an activation function on QASYMM8 inputs.
Note
In order to perform the activation function "in-place", the pre-processor -DIN_PLACE must be passed at compile time
Datatype should be given as a preprocessor argument using -DDATA_TYPE=type. e.g. -DDATA_TYPE=short
Vector size should be given as a preprocessor argument using -DVEC_SIZE=size. e.g. -DVEC_SIZE=16
Activation function should be given as a preprocessor argument using -DACT=name. e.g. -DACT=TANH
A, B variables required by some activation functions are set using -DA_VAL= and -DB_VAL= respectively.
Quantization scales of the input/output tensors are passed in with -DS1_VAL= and -DS2_VAL= respectively.
Quantization offsets of the input/output tensors are passed in with -DO1_VAL= and -DO2_VAL= respectively.
Parameters
[in] input_ptr Pointer to the source image. Supported data types: QASYMM8
[in] input_stride_x Stride of the source image in X dimension (in bytes)
[in] input_step_x input_stride_x * number of elements along X processed per workitem(in bytes)
[in] input_stride_y Stride of the source image in Y dimension (in bytes)
[in] input_step_y input_stride_y * number of elements along Y processed per workitem(in bytes)
[in] input_stride_z Stride of the source tensor in Z dimension (in bytes)
[in] input_step_z input_stride_z * number of elements along Z processed per workitem(in bytes)
[in] input_offset_first_element_in_bytes The offset of the first element in the source image
[out] output_ptr Pointer to the destination image. Supported data types: same as input_ptr
[in] output_stride_x Stride of the destination image in X dimension (in bytes)
[in] output_step_x output_stride_x * number of elements along X processed per workitem(in bytes)
[in] output_stride_y Stride of the destination image in Y dimension (in bytes)
[in] output_step_y output_stride_y * number of elements along Y processed per workitem(in bytes)
[in] output_stride_z Stride of the source tensor in Z dimension (in bytes)
[in] output_step_z output_stride_z * number of elements along Z processed per workitem(in bytes)
[in] output_offset_first_element_in_bytes The offset of the first element in the destination image
Definition at line 70 of file activation_layer_qa8.cl.
References ACTIVATION_OP, CONVERT, CONVERT_SAT, CONVERT_TO_TENSOR3D_STRUCT, DATA_TYPE, Tensor3D::ptr, arm_compute::round(), TYPE, VEC_DATA_TYPE, VLOAD, and VSTORE.
 {
     // Get pixels pointer
     Tensor3D input = CONVERT_TO_TENSOR3D_STRUCT(input);
 #ifdef IN_PLACE
     Tensor3D output = input;
 #else  /* IN_PLACE */
     Tensor3D output = CONVERT_TO_TENSOR3D_STRUCT(output);
 #endif /* IN_PLACE */
     // Load data
     TYPE data = VLOAD(VEC_SIZE)(0, (__global DATA_TYPE *)input.ptr);
     // Perform activation
     data = ACTIVATION_OP(ACT, data);
 #if defined(O1_VAL) && defined(O2_VAL) && defined(S1_VAL) && defined(S2_VAL)
     // requantize to output space
     VEC_DATA_TYPE(float, VEC_SIZE)
     fdata = CONVERT(data, VEC_DATA_TYPE(float, VEC_SIZE));
     fdata = round((fdata - (float)O1_VAL) * ((float)S1_VAL / (float)S2_VAL) + (float)O2_VAL);
     data  = CONVERT_SAT(fdata, VEC_DATA_TYPE(uchar, VEC_SIZE));
 #endif // defined(O1_VAL) && defined(O2_VAL) && defined(S1_VAL) && defined(S2_VAL)
     // Store result
     VSTORE(VEC_SIZE)
     (data, 0, (__global DATA_TYPE *)output.ptr);
 }
DATA_TYPEVEC_SIZE brelu_op (DATA_TYPEVEC_SIZE x) inline
Definition at line 29 of file activation_layer_qa8.cl.
References arm_compute::test::fixed_point_arithmetic::detail::max(), arm_compute::test::fixed_point_arithmetic::detail::min(), and TYPE.
 {
     return min((TYPE)A_VAL, max(0, x));
 }
DATA_TYPEVEC_SIZE lu_brelu_op (DATA_TYPEVEC_SIZE x) inline
Definition at line 34 of file activation_layer_qa8.cl.
References arm_compute::test::fixed_point_arithmetic::detail::max(), arm_compute::test::fixed_point_arithmetic::detail::min(), and TYPE.
 {
     return min(max(x, (TYPE)B_VAL), (TYPE)A_VAL);
 }