Compute Library: src/core/CL/cl_kernels/asymm_helper.h File Reference
asymm_helper.h File Reference
Macros
#define EXP_BARREL_SHIFTER(Exponent, FixedPointMultiplier)
Functions
int16 asymm_mask_if_zero (int16 a)
For each element of input vector, the corresponding bits of the result item are set if the input item is zero.
int16 asymm_mask_if_non_zero (int16 a)
For each element of input vector, the corresponding bits of the result item are set if the input item is non-zero.
int16 asymm_select_using_mask (int16 if_mask, int16 then_val, int16 else_val)
Each bit of the result is set to the corresponding bit of either then_val or else_val depending on whether the corresponding bit of if_mask is set.
int16 asymm_rounding_divide_by_pow2 (int16 x, int exponent)
Correctly rounded to nearest division by a power of two.
int16 asymm_saturating_rounding_mult_by_pow2 (int16 x, int exponent)
Calculates the product of a integer value by a power of two, with either a positive exponent (equivalent to an arithmetic left shift, saturating) or a negative exponent (equivalent to an arithmetic right shift, rounding to nearest).
int16 asymm_rounding_half_sum (int16 a, int16 b)
Calculates (a+b)/2, rounded to the nearest integer.
int16 asymm_saturating_rounding_doubling_high_mul (int16 a, int16 b)
Product of two numbers, interpreting them as fixed-point values in the interval [-1, 1), rounding to the nearest value, and saturating -1 * -1 to the maximum value.
int16 asymm_mult (int16 a, int16 b)
Fixed-point multiplication.
int16 asymm_exp_on_interval_between_negative_one_quarter_and_0_excl (int16 a)
Calculates \(exp(x) \) for x in [-1/4, 0).
int16 asymm_exp_on_negative_values (int16 a, int k_integer_bits)
Calculates \(exp(x) \) for x < 0.
int16 asymm_one_over_one_plus_x_for_x_in_0_1 (int16 a)
Calculates \(1 / (1 + x) \) for x in (0, 1).
int16 asymm_rescale (int16 value, int src_integer_bits, int dst_integer_bits)
Considering the integer value as fixed-point, change the number of integer bits and update value accordingly.
Macro Definition Documentation
#define EXP_BARREL_SHIFTER (Exponent, FixedPointMultiplier)
Value:
if(k_integer_bits > Exponent)                                                                \
    {                                                                                            \
        const int k_shift_amount = k_integer_bits > Exponent ? k_fractional_bits + Exponent : 0; \
        result                   = asymm_select_using_mask(                                      \
                                                                                                 asymm_mask_if_non_zero(remainder & (1 << k_shift_amount)),                           \
                                                                                                 asymm_mult(result, FixedPointMultiplier), result);                                   \
    }
Referenced by asymm_exp_on_negative_values().
Function Documentation
int16 asymm_exp_on_interval_between_negative_one_quarter_and_0_excl (int16 a) inline
Calculates \(exp(x) \) for x in [-1/4, 0).
Parameters
[in] a Argument in fixed-point format Q0.
Returns
Result in fixed-point format Q0.
Definition at line 178 of file asymm_helper.h.
References asymm_mult(), and asymm_rounding_divide_by_pow2().
Referenced by asymm_exp_on_negative_values().
 {
     const int16 constant_term                            = 1895147668;
     const int16 constant_1_over_3                        = 715827883;
     const int   k_fractional_bits                        = 31;
     int16       x                                        = a + (1 << (k_fractional_bits - 3));
     int16       x2                                       = asymm_mult(x, x);
     int16       x3                                       = asymm_mult(x2, x);
     int16       x4                                       = asymm_mult(x2, x2);
     int16       x4_over_4                                = asymm_rounding_divide_by_pow2(x4, 2);
     int16       x4_over_24_plus_x3_over_6_plus_x2        = asymm_mult((x4_over_4 + x3), constant_1_over_3) + x2;
     int16       x4_over_24_plus_x3_over_6_plus_x2_over_2 = asymm_rounding_divide_by_pow2(x4_over_24_plus_x3_over_6_plus_x2, 1);
     return constant_term + asymm_mult(constant_term, x + x4_over_24_plus_x3_over_6_plus_x2_over_2);
 }
int16 asymm_exp_on_negative_values (int16 a, int k_integer_bits) inline
Calculates \(exp(x) \) for x < 0.
Parameters
[in] a Argument in fixed-point format Q(k_integer_bits).
[in] k_integer_bits Number of integer bit in argument.
Returns
Result in fixed-point format Q0.
Definition at line 200 of file asymm_helper.h.
References arm_compute::test::validation::a, asymm_exp_on_interval_between_negative_one_quarter_and_0_excl(), asymm_mask_if_non_zero(), asymm_mask_if_zero(), asymm_select_using_mask(), arm_compute::utility::clamp(), and EXP_BARREL_SHIFTER.
Referenced by softmax_layer_max_quantized().
 {
     const int k_fractional_bits                      = 31 - k_integer_bits;
     int16     k_one_quarter                          = 1 << (k_fractional_bits - 2);
     int16     mask                                   = k_one_quarter - 1;
     int16     a_mod_quarter_minus_one_quarter        = (a & mask) - k_one_quarter;
     int16     a_mod_quarter_minus_one_quarter_scaled = a_mod_quarter_minus_one_quarter << k_integer_bits;
     int16     result                                 = asymm_exp_on_interval_between_negative_one_quarter_and_0_excl(a_mod_quarter_minus_one_quarter_scaled);
     int16     remainder                              = a_mod_quarter_minus_one_quarter - a;
 #define EXP_BARREL_SHIFTER(Exponent, FixedPointMultiplier)                                       \
     if(k_integer_bits > Exponent)                                                                \
     {                                                                                            \
         const int k_shift_amount = k_integer_bits > Exponent ? k_fractional_bits + Exponent : 0; \
         result                   = asymm_select_using_mask(                                      \
                                                                                                  asymm_mask_if_non_zero(remainder & (1 << k_shift_amount)),                           \
                                                                                                  asymm_mult(result, FixedPointMultiplier), result);                                   \
     }
     EXP_BARREL_SHIFTER(-2, 1672461947);
     EXP_BARREL_SHIFTER(-1, 1302514674);
     EXP_BARREL_SHIFTER(+0, 790015084);
     EXP_BARREL_SHIFTER(+1, 290630308);
     EXP_BARREL_SHIFTER(+2, 39332535);
     EXP_BARREL_SHIFTER(+3, 720401);
     EXP_BARREL_SHIFTER(+4, 242);
 #undef EXP_BARREL_SHIFTER
     if(k_integer_bits > 5)
     {
         const int16 clamp = -(1 << (k_fractional_bits + 5));
         result            = asymm_select_using_mask(asymm_mask_if_non_zero(a < clamp), 0, result);
     }
     const int16 Q0_one = INT_MAX;
     return asymm_select_using_mask(asymm_mask_if_zero(a), Q0_one, result);
 }
int16 asymm_mask_if_non_zero (int16 a) inline
For each element of input vector, the corresponding bits of the result item are set if the input item is non-zero.
Parameters
[in] a Input vector whose non-zero bits define which corresponding bits in result will be set.
Returns
Output vector with bits set when corresponding bit in a is non zero.
Definition at line 52 of file asymm_helper.h.
Referenced by asymm_exp_on_negative_values(), and asymm_saturating_rounding_mult_by_pow2().
 {
     const int16 all_zeros = 0;
     const int16 all_ones  = ~0;
     return select(all_zeros, all_ones, a != 0);
 }
int16 asymm_mask_if_zero (int16 a) inline
For each element of input vector, the corresponding bits of the result item are set if the input item is zero.
Parameters
[in] a Input vector whose zero bits define which corresponding bits in result will be set.
Returns
Output vector with bits set when corresponding bit in a is zero.
Definition at line 38 of file asymm_helper.h.
Referenced by asymm_exp_on_negative_values().
 {
     const int16 all_zeros = 0;
     const int16 all_ones  = ~0;
     return select(all_zeros, all_ones, a == 0);
 }
int16 asymm_mult (int16 a, int16 b) inline
Fixed-point multiplication.
Parameters
[in] a Argument 1 in fixed-point format Q(a).
[in] b Argument 2 in fixed-point format Q(b).
Returns
Result in fixed-point format Q(a+b).
Definition at line 167 of file asymm_helper.h.
References asymm_saturating_rounding_doubling_high_mul().
Referenced by asymm_exp_on_interval_between_negative_one_quarter_and_0_excl(), asymm_one_over_one_plus_x_for_x_in_0_1(), and softmax_layer_max_quantized().
 {
     return asymm_saturating_rounding_doubling_high_mul(a, b);
 }
int16 asymm_one_over_one_plus_x_for_x_in_0_1 (int16 a) inline
Calculates \(1 / (1 + x) \) for x in (0, 1).
Parameters
[in] a Argument in fixed-point format Q0.
Returns
Result in fixed-point format Q0.
Definition at line 243 of file asymm_helper.h.
References asymm_mult(), asymm_rounding_half_sum(), and asymm_saturating_rounding_mult_by_pow2().
Referenced by softmax_layer_max_quantized().
 {
     const int16 Q0_one            = INT_MAX;
     const int16 Q2_one            = 1 << (31 - 2);
     int16       half_denominator  = asymm_rounding_half_sum(a, Q0_one);
     const int16 Q2_48_over_17     = 1515870810;
     const int16 Q2_neg_32_over_17 = -1010580540;
     int16       x                 = Q2_48_over_17 + asymm_mult(half_denominator, Q2_neg_32_over_17);
     for(int i = 0; i < 3; i++)
     {
         int16 half_denominator_times_x           = asymm_mult(half_denominator, x);
         int16 one_minus_half_denominator_times_x = Q2_one - half_denominator_times_x;
         int16 tmp                                = asymm_mult(x, one_minus_half_denominator_times_x);
         x                                        = x + asymm_saturating_rounding_mult_by_pow2(tmp, 2);
     }
     return asymm_saturating_rounding_mult_by_pow2(x, 1);
 }
int16 asymm_rescale (int16 value, int src_integer_bits, int dst_integer_bits) inline
Considering the integer value as fixed-point, change the number of integer bits and update value accordingly.
Parameters
[in] value Value to be rescaled.
[in] src_integer_bits Old number of integer bits.
[in] dst_integer_bits New number of integer bits.
Returns
Rescaled value.
Definition at line 269 of file asymm_helper.h.
References asymm_saturating_rounding_mult_by_pow2().
Referenced by softmax_layer_max_quantized().
 {
     int exponent = src_integer_bits - dst_integer_bits;
     return asymm_saturating_rounding_mult_by_pow2(value, exponent);
 }
int16 asymm_rounding_divide_by_pow2 (int16 x, int exponent) inline
Correctly rounded to nearest division by a power of two.
Also known as a rounding arithmetic right shift.
Parameters
[in] x Value needed to be divided by power of two.
[in] exponent Power of two, must be positive number.
Returns
Arithmetic right shift.
Definition at line 82 of file asymm_helper.h.
References arm_compute::test::validation::reference::threshold().
Referenced by asymm_exp_on_interval_between_negative_one_quarter_and_0_excl(), asymm_saturating_rounding_mult_by_pow2(), and softmax_layer_max_quantized().
 {
     int16       mask      = (1 << exponent) - 1;
     const int16 zero      = 0;
     const int16 one       = 1;
     int16       threshold = (mask >> 1) + select(zero, one, x < 0);
     return (x >> exponent) + select(zero, one, (x & mask) > threshold);
 }
int16 asymm_rounding_half_sum (int16 a, int16 b) inline
Calculates (a+b)/2, rounded to the nearest integer.
Equivalent to VRHADD in the ARM NEON instruction set.
Parameters
[in] a First term of half-sum.
[in] b Second term of half-sum.
Returns
(a+b)/2, rounded to the nearest integer.
Definition at line 126 of file asymm_helper.h.
References sum().
Referenced by asymm_one_over_one_plus_x_for_x_in_0_1().
 {
     long16       a64       = convert_long16(a);
     long16       b64       = convert_long16(b);
     long16       sum       = a64 + b64;
     const long16 one       = 1;
     const long16 minus_one = -1;
     long16       sign      = select(minus_one, one, sum >= 0);
     return convert_int16((sum + sign) / 2);
 }
int16 asymm_saturating_rounding_doubling_high_mul (int16 a, int16 b) inline
Product of two numbers, interpreting them as fixed-point values in the interval [-1, 1), rounding to the nearest value, and saturating -1 * -1 to the maximum value.
This is equivalent to the VQRDMULH instruction in ARM NEON.
Parameters
[in] a First term of product.
[in] b Second term of product.
Returns
Product of two numbers.
Definition at line 146 of file asymm_helper.h.
References arm_compute::test::validation::b.
Referenced by asymm_mult().
 {
     int16  overflow     = (a == b) && (a == INT_MIN);
     long16 a_64         = convert_long16(a);
     long16 b_64         = convert_long16(b);
     long16 ab_64        = a_64 * b_64;
     long16 mask1        = 1 << 30;
     long16 mask2        = 1 - (1 << 30);
     long16 nudge        = select(mask2, mask1, ab_64 >= 0);
     long16 mask         = 1ll << 31;
     int16  ab_x2_high32 = convert_int16((ab_64 + nudge) / mask);
     return select(ab_x2_high32, INT_MAX, overflow);
 }
int16 asymm_saturating_rounding_mult_by_pow2 (int16 x, int exponent) inline
Calculates the product of a integer value by a power of two, with either a positive exponent (equivalent to an arithmetic left shift, saturating) or a negative exponent (equivalent to an arithmetic right shift, rounding to nearest).
Parameters
[in] x Value needed to be multiplied or divided by power of two depending on sign of exponent.
[in] exponent Power of two, can be positive or negative number.
Returns
Arithmetic left or right shift.
Definition at line 100 of file asymm_helper.h.
References asymm_mask_if_non_zero(), asymm_rounding_divide_by_pow2(), asymm_select_using_mask(), arm_compute::test::fixed_point_arithmetic::detail::max(), arm_compute::test::fixed_point_arithmetic::detail::min(), and arm_compute::test::validation::reference::threshold().
Referenced by asymm_one_over_one_plus_x_for_x_in_0_1(), and asymm_rescale().
 {
     if(exponent < 0)
     {
         return asymm_rounding_divide_by_pow2(x, -exponent);
     }
     const int16 min           = INT_MIN;
     const int16 max           = INT_MAX;
     int         threshold     = ((1 << (31 - exponent)) - 1);
     int16       positive_mask = asymm_mask_if_non_zero(x > threshold);
     int16       negative_mask = asymm_mask_if_non_zero(x < -threshold);
     int16       result        = x << exponent;
     result                    = asymm_select_using_mask(positive_mask, max, result);
     result                    = asymm_select_using_mask(negative_mask, min, result);
     return result;
 }
int16 asymm_select_using_mask (int16 if_mask, int16 then_val, int16 else_val) inline
Each bit of the result is set to the corresponding bit of either then_val or else_val depending on whether the corresponding bit of if_mask is set.
Equivalent to the VBSL instruction in ARM NEON.
Parameters
[in] if_mask Mask defines will bit be taken from then_val or else_val depending on corresponding bit in mask is set or not.
[in] then_val Value whose bit will be used for result when corresponding bit in if_mask is set.
[in] else_val Value whose bit will be used for result when corresponding bit in if_mask is not set.
Returns
Result contaning bits from then_val or from else_val depending on corresponding bit in if_mask is set or not.
Definition at line 69 of file asymm_helper.h.
Referenced by asymm_exp_on_negative_values(), and asymm_saturating_rounding_mult_by_pow2().
 {
     return (if_mask & then_val) ^ (~if_mask & else_val);
 }