Compute Library: PoolingLayerDataset Class Reference
PoolingLayerDataset Class Reference
#include <PoolingLayerDataset.h>
Data Structures
struct iterator
Public Types
using type = std::tuple< TensorShape, TensorShape, PoolingLayerInfo >
Public Member Functions
iterator begin () const
int size () const
void add_config (TensorShape src, TensorShape dst, PoolingLayerInfo info)
Detailed Description
Definition at line 37 of file PoolingLayerDataset.h.
Member Typedef Documentation
using type = std::tuple<TensorShape, TensorShape, PoolingLayerInfo>
Definition at line 40 of file PoolingLayerDataset.h.
Member Function Documentation
void add_config (TensorShape src, TensorShape dst, PoolingLayerInfo info) inline
Definition at line 92 of file PoolingLayerDataset.h.
Referenced by AlexNetPoolingLayerDataset::AlexNetPoolingLayerDataset(), GoogLeNetInceptionV1PoolingLayerDataset::GoogLeNetInceptionV1PoolingLayerDataset(), GoogLeNetInceptionV4PoolingLayerDataset::GoogLeNetInceptionV4PoolingLayerDataset(), LeNet5PoolingLayerDataset::LeNet5PoolingLayerDataset(), SqueezeNetPoolingLayerDataset::SqueezeNetPoolingLayerDataset(), VGG16PoolingLayerDataset::VGG16PoolingLayerDataset(), and YOLOV2PoolingLayerDataset::YOLOV2PoolingLayerDataset().
     {
         _src_shapes.emplace_back(std::move(src));
         _dst_shapes.emplace_back(std::move(dst));
         _infos.emplace_back(std::move(info));
     }
iterator begin () const inline
Definition at line 82 of file PoolingLayerDataset.h.
References PoolingLayerDataset::iterator::iterator().
     {
         return iterator(_src_shapes.begin(), _dst_shapes.begin(), _infos.begin());
     }
int size () const inline
Definition at line 87 of file PoolingLayerDataset.h.
References arm_compute::test::fixed_point_arithmetic::detail::min().
     {
         return std::min(_src_shapes.size(), std::min(_dst_shapes.size(), _infos.size()));
     }
The documentation for this class was generated from the following file:
tests/datasets/PoolingLayerDataset.h