Compute Library: Option Class Reference
Option Class Reference abstract
Abstract base class for a command line option.
#include <Option.h>
Public Member Functions
Option (std::string name)
Constructor.
Option (std::string name, bool is_required, bool is_set)
Constructor.
virtual ~Option ()=default
Default destructor.
virtual bool parse (std::string value)=0
Parses the given string.
virtual std::string help () const =0
Help message for the option.
std::string name () const
Name of the option.
void set_required (bool is_required)
Set whether the option is required.
void set_help (std::string help)
Set the help message for the option.
bool is_required () const
Is the option required?
bool is_set () const
Has a value been assigned to the option?
Detailed Description
Abstract base class for a command line option.
Definition at line 36 of file Option.h.
Constructor & Destructor Documentation
Option (std::string name)
Constructor.
Parameters
[in] name Name of the option.
Definition at line 32 of file Option.cpp.
     : _name{ std::move(name) }
 {
 }
Option (std::string name, bool is_required, bool is_set)
Constructor.
Parameters
[in] name Name of the option.
[in] is_required Is the option required?
[in] is_set Has a value been assigned to the option?
Definition at line 37 of file Option.cpp.
References Option::is_required(), and Option::is_set().
     : _name{ std::move(name) }, _is_required{ is_required }, _is_set{ is_set }
 {
 }
virtual ~Option () virtual default
Default destructor.
Member Function Documentation
virtual std::string help () const pure virtual
Help message for the option.
Returns
String representing the help message for the specific subclass.
Implemented in EnumListOption< T >, EnumListOption< InstrumentsDescription >, EnumOption< T >, EnumOption< LogFormat >, EnumOption< LogLevel >, ListOption< T >, SimpleOption< T >, SimpleOption< LogFormat >, SimpleOption< std::string >, SimpleOption< int >, SimpleOption< LogLevel >, SimpleOption< bool >, and ToggleOption.
bool is_required () const
Is the option required?
Returns
True if the option is required.
Definition at line 57 of file Option.cpp.
Referenced by Option::Option(), and Option::set_required().
 {
     return _is_required;
 }
bool is_set () const
Has a value been assigned to the option?
Returns
True if a value has been set.
Definition at line 62 of file Option.cpp.
Referenced by CommonOptions::create_printers(), main(), and Option::Option().
 {
     return _is_set;
 }
std::string name () const
Name of the option.
Returns
Name of the option.
Definition at line 42 of file Option.cpp.
Referenced by SimpleOption< T >::help(), ListOption< T >::help(), EnumListOption< T >::help(), and ToggleOption::ToggleOption().
 {
     return _name;
 }
virtual bool parse (std::string value) pure virtual
Parses the given string.
Parameters
[in] value String representation as passed on the command line.
Returns
True if the value could be parsed by the specific subclass.
Implemented in SimpleOption< T >, EnumListOption< T >, EnumListOption< InstrumentsDescription >, EnumOption< T >, EnumOption< LogFormat >, EnumOption< LogLevel >, ListOption< T >, SimpleOption< T >, SimpleOption< LogFormat >, SimpleOption< std::string >, SimpleOption< int >, SimpleOption< LogLevel >, SimpleOption< bool >, and ToggleOption.
void set_help (std::string help)
Set the help message for the option.
Parameters
[in] help Option specific help message.
Definition at line 52 of file Option.cpp.
Referenced by CommonOptions::CommonOptions(), and main().
 {
     _help = std::move(help);
 }
void set_required (bool is_required)
Set whether the option is required.
Parameters
[in] is_required Pass true if the option is required.
Definition at line 47 of file Option.cpp.
References Option::is_required().
 {
     _is_required = is_required;
 }
The documentation for this class was generated from the following files:
tests/framework/command_line/Option.h
tests/framework/command_line/Option.cpp