Compute Library: NDRange Class Reference
NDRange Class Reference
Class interface for specifying NDRange values.
#include <OpenGLES.h>
Public Member Functions
NDRange ()
Default constructor - resulting range has zero dimensions.
NDRange (size_t size0)
Constructs one-dimensional range.
NDRange (size_t size0, size_t size1)
Constructs two-dimensional range.
NDRange (size_t size0, size_t size1, size_t size2)
Constructs three-dimensional range.
operator const size_t * () const
Conversion operator to const size_t *.
size_t dimensions () const
Queries the number of dimensions in the range.
size_t size () const
Returns the size of the object in bytes based on the runtime number of dimensions.
size_t * get ()
Returns the sizes array for each dimensions.
const size_t * get () const
Returns the sizes array for each dimensions.
Detailed Description
Class interface for specifying NDRange values.
Definition at line 53 of file OpenGLES.h.
Constructor & Destructor Documentation
NDRange () inline
Default constructor - resulting range has zero dimensions.
Definition at line 61 of file OpenGLES.h.
Referenced by NDRange::get().
         : _dimensions(0)
     {
         _sizes[0] = 0;
         _sizes[1] = 0;
         _sizes[2] = 0;
     }
NDRange (size_t size0) inline
Constructs one-dimensional range.
Parameters
[in] size0 Size of the first dimension.
Definition at line 73 of file OpenGLES.h.
         : _dimensions(1)
     {
         _sizes[0] = size0;
         _sizes[1] = 1;
         _sizes[2] = 1;
     }
NDRange (size_t size0, size_t size1) inline
Constructs two-dimensional range.
Parameters
[in] size0 Size of the first dimension.
[in] size1 Size of the second dimension.
Definition at line 86 of file OpenGLES.h.
         : _dimensions(2)
     {
         _sizes[0] = size0;
         _sizes[1] = size1;
         _sizes[2] = 1;
     }
NDRange (size_t size0, size_t size1, size_t size2) inline
Constructs three-dimensional range.
Parameters
[in] size0 Size of the first dimension.
[in] size1 Size of the second dimension.
[in] size2 Size of the third dimension.
Definition at line 100 of file OpenGLES.h.
         : _dimensions(3)
     {
         _sizes[0] = size0;
         _sizes[1] = size1;
         _sizes[2] = size2;
     }
Member Function Documentation
size_t dimensions () const inline
Queries the number of dimensions in the range.
Returns
The number of dimensions.
Definition at line 121 of file OpenGLES.h.
     {
         return _dimensions;
     }
size_t* get () inline
Returns the sizes array for each dimensions.
Returns
The sizes array
Definition at line 139 of file OpenGLES.h.
     {
         return _sizes;
     }
const size_t* get () const inline
Returns the sizes array for each dimensions.
Returns
The sizes array
Definition at line 148 of file OpenGLES.h.
References NDRange::NDRange(), and arm_compute::opengles31_is_available().
     {
         return _sizes;
     }
operator const size_t * () const inline
Conversion operator to const size_t *.
Returns
A pointer to the size of the first dimension.
Definition at line 112 of file OpenGLES.h.
     {
         return _sizes;
     }
size_t size () const inline
Returns the size of the object in bytes based on the runtime number of dimensions.
Returns
The size of the object in bytes.
Definition at line 130 of file OpenGLES.h.
     {
         return _dimensions * sizeof(size_t);
     }
The documentation for this class was generated from the following file:
arm_compute/core/GLES_COMPUTE/OpenGLES.h