Compute Library: GoogLeNetInceptionV4ActivationLayerDataset Class Reference
GoogLeNetInceptionV4ActivationLayerDataset Class Reference final
#include <GoogLeNetInceptionV4ActivationLayerDataset.h>
Public Member Functions
GoogLeNetInceptionV4ActivationLayerDataset ()
GoogLeNetInceptionV4ActivationLayerDataset (GoogLeNetInceptionV4ActivationLayerDataset &&)=default
~GoogLeNetInceptionV4ActivationLayerDataset ()=default
Public Member Functions inherited from CartesianProductDataset< framework::dataset::InitializerListDataset< TensorShape >, framework::dataset::SingletonDataset< ActivationLayerInfo > >
CartesianProductDataset (framework::dataset::InitializerListDataset< TensorShape > &&dataset1, framework::dataset::SingletonDataset< ActivationLayerInfo > &&dataset2)
Construct dataset from the given datasets.
CartesianProductDataset (CartesianProductDataset &&)=default
iterator begin () const
Iterator pointing at the begin of the dataset.
int size () const
Size of the dataset.
Public Member Functions inherited from Dataset
Dataset (Dataset &&)=default
Additional Inherited Members
Public Types inherited from CartesianProductDataset< framework::dataset::InitializerListDataset< TensorShape >, framework::dataset::SingletonDataset< ActivationLayerInfo > >
using type = decltype(std::tuple_cat(*std::declval< iter1_type >(),*std::declval< iter2_type >()))
Type of the dataset.
Detailed Description
Definition at line 40 of file GoogLeNetInceptionV4ActivationLayerDataset.h.
Constructor & Destructor Documentation
GoogLeNetInceptionV4ActivationLayerDataset () inline
Definition at line 44 of file GoogLeNetInceptionV4ActivationLayerDataset.h.
References arm_compute::test::framework::dataset::make(), ActivationLayerInfo::RELU, arm_compute::U, and GoogLeNetInceptionV4ActivationLayerDataset::~GoogLeNetInceptionV4ActivationLayerDataset().
         : CartesianProductDataset
     {
         framework::dataset::make("Shape", { // conv1_3x3_s2_relu
             TensorShape(149U, 149U, 32U),
             // conv2_3x3_s1_relu
             TensorShape(147U, 147U, 32U),
             // conv3_3x3_s1_relu
             TensorShape(147U, 147U, 64U),
             // inception_stem1_3x3_s2_relu
             TensorShape(73U, 73U, 96U),
             // inception_stem2_3x3_reduce_relu, inception_stem2_1x7_reduce_relu, inception_stem2_1x7_relu, inception_stem2_7x1_relu
             TensorShape(73U, 73U, 64U),
             // inception_stem2_3x3_relu, inception_stem2_3x3_2_relu
             TensorShape(71U, 71U, 96U),
             // inception_stem3_3x3_s2_relu, reduction_a_3x3_2_reduce_relu
             TensorShape(35U, 35U, 192U),
             // inception_a1_1x1_2_relu, inception_a1_3x3_relu, inception_a1_3x3_2_relu, inception_a1_3x3_3_relu, inception_a1_1x1_relu, inception_a2_1x1_2_relu, inception_a2_3x3_relu, inception_a2_3x3_2_relu, inception_a2_3x3_3_relu, inception_a2_1x1_relu, inception_a3_1x1_2_relu, inception_a3_3x3_relu, inception_a3_3x3_2_relu, inception_a3_3x3_3_relu, inception_a3_1x1_relu, inception_a4_1x1_2_relu, inception_a4_3x3_relu, inception_a4_3x3_2_relu, inception_a4_3x3_3_relu, inception_a4_1x1_relu
             TensorShape(35U, 35U, 96U),
             // inception_a1_3x3_reduce_relu, inception_a1_3x3_2_reduce_relu, inception_a2_3x3_reduce_relu, inception_a2_3x3_2_reduce_relu, inception_a3_3x3_reduce_relu, inception_a3_3x3_2_reduce_relu, inception_a4_3x3_reduce_relu, inception_a4_3x3_2_reduce_relu
             TensorShape(35U, 35U, 64U),
             // reduction_a_3x3_relu, inception_b1_1x1_2_relu, inception_b2_1x1_2_relu, inception_b3_1x1_2_relu, inception_b4_1x1_2_relu, inception_b5_1x1_2_relu, inception_b6_1x1_2_relu, inception_b7_1x1_2_relu
             TensorShape(17U, 17U, 384U),
             // reduction_a_3x3_2_relu
             TensorShape(35U, 35U, 224U),
             // reduction_a_3x3_3_relu, inception_b1_7x1_relu, inception_b1_1x7_3_relu, inception_b2_7x1_relu, inception_b2_1x7_3_relu, inception_b3_7x1_relu, inception_b3_1x7_3_relu, inception_b4_7x1_relu, inception_b4_1x7_3_relu, inception_b5_7x1_relu, inception_b5_1x7_3_relu, inception_b6_7x1_relu, inception_b6_1x7_3_relu, inception_b7_7x1_relu, inception_b7_1x7_3_relu, reduction_b_1x7_reduce_relu, reduction_b_1x7_relu
             TensorShape(17U, 17U, 256U),
             // inception_b1_1x7_reduce_relu, inception_b1_7x1_2_reduce_relu, inception_b1_7x1_2_relu, inception_b2_1x7_reduce_relu, inception_b2_7x1_2_reduce_relu, inception_b2_7x1_2_relu, inception_b3_1x7_reduce_relu, inception_b3_7x1_2_reduce_relu, inception_b3_7x1_2_relu, inception_b4_1x7_reduce_relu, inception_b4_7x1_2_reduce_relu, inception_b4_7x1_2_relu, inception_b5_1x7_reduce_relu, inception_b5_7x1_2_reduce_relu, inception_b5_7x1_2_relu, inception_b6_1x7_reduce_relu, inception_b6_7x1_2_reduce_relu, inception_b6_7x1_2_relu, inception_b7_1x7_reduce_relu, inception_b7_7x1_2_reduce_relu, inception_b7_7x1_2_relu, reduction_b_3x3_reduce_relu
             TensorShape(17U, 17U, 192U),
             // inception_b1_1x7_relu, inception_b1_1x7_2_relu, inception_b1_7x1_3_relu, inception_b2_1x7_relu, inception_b2_1x7_2_relu, inception_b2_7x1_3_relu, inception_b3_1x7_relu, inception_b3_1x7_2_relu, inception_b3_7x1_3_relu, inception_b4_1x7_relu, inception_b4_1x7_2_relu, inception_b4_7x1_3_relu, inception_b5_1x7_relu, inception_b5_1x7_2_relu, inception_b5_7x1_3_relu, inception_b6_1x7_relu, inception_b6_1x7_2_relu, inception_b6_7x1_3_relu, inception_b7_1x7_relu, inception_b7_1x7_2_relu, inception_b7_7x1_3_relu
             TensorShape(17U, 17U, 224U),
             // inception_b1_1x1_relu, inception_b2_1x1_relu, inception_b3_1x1_relu, inception_b4_1x1_relu, inception_b5_1x1_relu, inception_b6_1x1_relu, inception_b7_1x1_relu
             TensorShape(17U, 17U, 128U),
             // reduction_b_3x3_relu
             TensorShape(8U, 8U, 192U),
             // reduction_b_7x1_relu
             TensorShape(17U, 17U, 320U),
             // reduction_b_3x3_2_relu
             TensorShape(8U, 8U, 320U),
             // inception_c1_1x1_2_relu, inception_c1_1x3_relu, inception_c1_3x1_relu, inception_c1_1x3_3_relu, inception_c1_3x1_3_relu, inception_c1_1x1_relu, inception_c2_1x1_2_relu, inception_c2_1x3_relu, inception_c2_3x1_relu, inception_c2_1x3_3_relu, inception_c2_3x1_3_relu, inception_c2_1x1_relu, inception_c3_1x1_2_relu, inception_c3_1x3_relu, inception_c3_3x1_relu, inception_c3_1x3_3_relu, inception_c3_3x1_3_relu, inception_c3_1x1_relu
             TensorShape(8U, 8U, 256U),
             // inception_c1_1x1_3_relu, inception_c1_1x1_4_relu, inception_c2_1x1_3_relu, inception_c2_1x1_4_relu, inception_c3_1x1_3_relu, inception_c3_1x1_4_relu
             TensorShape(8U, 8U, 384U),
             // inception_c1_3x1_2_relu, inception_c2_3x1_2_relu, inception_c3_3x1_2_relu
             TensorShape(8U, 8U, 448U),
             // inception_c1_1x3_2_relu, inception_c2_1x3_2_relu, inception_c3_1x3_2_relu
             TensorShape(8U, 8U, 512U) }),
         framework::dataset::make("Info", ActivationLayerInfo(ActivationLayerInfo::ActivationFunction::RELU))
     }
     {
     }
GoogLeNetInceptionV4ActivationLayerDataset (GoogLeNetInceptionV4ActivationLayerDataset &&) default
~GoogLeNetInceptionV4ActivationLayerDataset () default
Referenced by GoogLeNetInceptionV4ActivationLayerDataset::GoogLeNetInceptionV4ActivationLayerDataset().
The documentation for this class was generated from the following file:
tests/datasets/system_tests/googlenet/inceptionv4/GoogLeNetInceptionV4ActivationLayerDataset.h