Compute Library: Fixture Class Reference
Fixture Class Reference
Abstract fixture class.
#include <Fixture.h>
Public Member Functions
void setup ()
Setup function.
void teardown ()
Teardown function.
Detailed Description
Abstract fixture class.
All custom fixtures have to inherit from this class.
Definition at line 37 of file Fixture.h.
Member Function Documentation
void setup () inline
Setup function.
This function is only invoked by non-data fixture test cases. Fixture data test cases implement a setup function with arguments matching the dataset.
The function is called before the test case is executed.
Definition at line 48 of file Fixture.h.
Referenced by QuantizationValidationFixture< TensorType, AccessorType, FunctionType, T >::setup(), DepthConvertLayerValidationFixture< TensorType, AccessorType, FunctionType, T1, T2 >::setup(), ArithmeticAdditionValidationFixture< TensorType, AccessorType, FunctionType, T >::setup(), ArithmeticSubtractionValidationFixture< TensorType, AccessorType, FunctionType, T1, T2, T3 >::setup(), AccumulateValidationFixture< TensorType, AccessorType, FunctionType, T1, T2 >::setup(), DepthConvertLayerValidationFractionalBitsFixture< TensorType, AccessorType, FunctionType, T1, T2 >::setup(), NormalizationValidationFixture< TensorType, AccessorType, FunctionType, T >::setup(), NormalizePlanarYUVLayerValidationFixture< TensorType, AccessorType, FunctionType, T >::setup(), GEMMInterleave4x4ValidationFixture< TensorType, AccessorType, FunctionType, T >::setup(), GEMMTranspose1xWValidationFixture< TensorType, AccessorType, FunctionType, T >::setup(), SoftmaxValidationFixture< TensorType, AccessorType, FunctionType, T >::setup(), PoolingLayerValidationFixture< TensorType, AccessorType, FunctionType, T >::setup(), AccumulateWeightedValidationFixture< TensorType, AccessorType, FunctionType, T1, T2 >::setup(), DeconvolutionValidationFixture< TensorType, AccessorType, FunctionType, T, kernel_size_x, kernel_size_y >::setup(), GEMMValidationFixture< TensorType, AccessorType, FunctionType, T >::setup(), PoolingLayerValidationFixedPointFixture< TensorType, AccessorType, FunctionType, T >::setup(), SoftmaxValidationFixedPointFixture< TensorType, AccessorType, FunctionType, T >::setup(), ConvolutionSquareValidationFixture< TensorType, AccessorType, FunctionType, T >::setup(), ActivationValidationFixture< TensorType, AccessorType, FunctionType, T >::setup(), BatchNormalizationLayerValidationFixture< TensorType, AccessorType, FunctionType, T >::setup(), PoolingLayerValidationQuantizedFixture< TensorType, AccessorType, FunctionType, T >::setup(), DepthwiseConvolutionLayerValidationFixture< TensorType, AccessorType, FunctionType, T >::setup(), SoftmaxValidationQuantizedFixture< TensorType, AccessorType, FunctionType, T >::setup(), ActivationValidationFixedPointFixture< TensorType, AccessorType, FunctionType, T >::setup(), AccumulateSquaredValidationFixture< TensorType, AccessorType, FunctionType, T1, T2 >::setup(), GlobalPoolingLayerValidationFixture< TensorType, AccessorType, FunctionType, T >::setup(), DequantizationValidationFixture< TensorType, AccessorType, FunctionType, T >::setup(), DepthwiseConvolutionLayerValidationQuantizedFixture< TensorType, AccessorType, FunctionType, T >::setup(), ActivationValidationQuantizedFixture< TensorType, AccessorType, FunctionType, T >::setup(), ConvolutionSeparableValidationFixture< TensorType, AccessorType, FunctionType, T >::setup(), DirectConvolutionValidationFixture< TensorType, AccessorType, FunctionType, T >::setup(), DirectConvolutionValidationFixedPointFixture< TensorType, AccessorType, FunctionType, T >::setup(), DirectConvolutionValidationQuantizedFixture< TensorType, AccessorType, FunctionType, T >::setup(), FullyConnectedLayerValidationFixture< TensorType, AccessorType, FunctionType, T, run_interleave >::setup(), DirectConvolutionValidationWithTensorShapesQuantizedFixture< TensorType, AccessorType, FunctionType, T >::setup(), ConvolutionRectangleValidationFixture< TensorType, AccessorType, FunctionType, T >::setup(), FullyConnectedLayerValidationFixedPointFixture< TensorType, AccessorType, FunctionType, T, run_interleave >::setup(), DirectConvolutionValidationWithTensorShapesFixture< TensorType, AccessorType, FunctionType, T >::setup(), FullyConnectedLayerValidationQuantizedFixture< TensorType, AccessorType, FunctionType, T, run_interleave >::setup(), ConvolutionValidationFixture< TensorType, AccessorType, FunctionType, T >::setup(), ConvolutionValidationFixedPointFixture< TensorType, AccessorType, FunctionType, T >::setup(), and ConvolutionValidationQuantizedFixture< TensorType, AccessorType, FunctionType, T >::setup().
 {};
void teardown () inline
Teardown function.
The function is called after the test case finished.
Definition at line 54 of file Fixture.h.
 {};
The documentation for this class was generated from the following file:
tests/framework/Fixture.h