Compute Library: PhaseValidationFixture< TensorType, AccessorType, FunctionType, T > Class Template Reference
PhaseValidationFixture< TensorType, AccessorType, FunctionType, T > Class Template Reference
#include <PhaseFixture.h>
Public Member Functions
template<typename... >
void setup (TensorShape shape, Format format, PhaseType phase_type)
Public Member Functions inherited from Fixture
void setup ()
Setup function.
void teardown ()
Teardown function.
Detailed Description
template<typename TensorType, typename AccessorType, typename FunctionType, typename T>
class arm_compute::test::validation::PhaseValidationFixture< TensorType, AccessorType, FunctionType, T >
Definition at line 42 of file PhaseFixture.h.
Member Function Documentation
void setup (TensorShape shape, Format format, PhaseType phase_type) inline
Definition at line 46 of file PhaseFixture.h.
References arm_compute::test::validation::ARM_COMPUTE_EXPECT(), arm_compute::test::validation::data_type, arm_compute::data_type_from_format(), arm_compute::test::validation::dst, arm_compute::test::framework::ERRORS, CLTensor::info(), arm_compute::test::library, arm_compute::test::validation::reference::phase(), TensorInfo::set_format(), arm_compute::test::validation::shape, arm_compute::U, and arm_compute::U8.
     {
         _target    = compute_target(shape, format, phase_type);
         _reference = compute_reference(shape, format, phase_type);
     }
The documentation for this class was generated from the following file:
tests/validation/fixtures/PhaseFixture.h