Compute Library: ConvolutionLayerDataset Class Reference
ConvolutionLayerDataset Class Reference
#include <ConvolutionLayerDataset.h>
Data Structures
struct iterator
Public Types
using type = std::tuple< TensorShape, TensorShape, TensorShape, TensorShape, PadStrideInfo >
Public Member Functions
iterator begin () const
int size () const
void add_config (TensorShape src, TensorShape weights, TensorShape biases, TensorShape dst, PadStrideInfo info)
Detailed Description
Definition at line 38 of file ConvolutionLayerDataset.h.
Member Typedef Documentation
using type = std::tuple<TensorShape, TensorShape, TensorShape, TensorShape, PadStrideInfo>
Definition at line 41 of file ConvolutionLayerDataset.h.
Member Function Documentation
void add_config (TensorShape src, TensorShape weights, TensorShape biases, TensorShape dst, PadStrideInfo info) inline
Definition at line 103 of file ConvolutionLayerDataset.h.
Referenced by AlexNetConvolutionLayerDataset::AlexNetConvolutionLayerDataset(), AlexNetDirectConvolutionLayerDataset::AlexNetDirectConvolutionLayerDataset(), AlexNetWinogradLayerDataset::AlexNetWinogradLayerDataset(), DirectConvolutionLayerDataset::DirectConvolutionLayerDataset(), GoogLeNetInceptionV1ConvolutionLayerDataset::GoogLeNetInceptionV1ConvolutionLayerDataset(), GoogLeNetInceptionV1DirectConvolutionLayerDataset::GoogLeNetInceptionV1DirectConvolutionLayerDataset(), GoogLeNetInceptionV1WinogradLayerDataset::GoogLeNetInceptionV1WinogradLayerDataset(), GoogLeNetInceptionV4ConvolutionLayerDataset::GoogLeNetInceptionV4ConvolutionLayerDataset(), GoogLeNetInceptionV4DirectConvolutionLayerDataset::GoogLeNetInceptionV4DirectConvolutionLayerDataset(), GoogLeNetInceptionV4WinogradLayerDataset::GoogLeNetInceptionV4WinogradLayerDataset(), LargeConvolutionLayerDataset::LargeConvolutionLayerDataset(), LeNet5ConvolutionLayerDataset::LeNet5ConvolutionLayerDataset(), SmallConvolutionLayerDataset::SmallConvolutionLayerDataset(), SmallWinogradLayerDataset::SmallWinogradLayerDataset(), SqueezeNetConvolutionLayerDataset::SqueezeNetConvolutionLayerDataset(), SqueezeNetWinogradLayerDataset::SqueezeNetWinogradLayerDataset(), VGG16ConvolutionLayerDataset::VGG16ConvolutionLayerDataset(), VGG16DirectConvolutionLayerDataset::VGG16DirectConvolutionLayerDataset(), and YOLOV2ConvolutionLayerDataset::YOLOV2ConvolutionLayerDataset().
     {
         _src_shapes.emplace_back(std::move(src));
         _weight_shapes.emplace_back(std::move(weights));
         _bias_shapes.emplace_back(std::move(biases));
         _dst_shapes.emplace_back(std::move(dst));
         _infos.emplace_back(std::move(info));
     }
iterator begin () const inline
Definition at line 93 of file ConvolutionLayerDataset.h.
References ConvolutionLayerDataset::iterator::iterator().
     {
         return iterator(_src_shapes.begin(), _weight_shapes.begin(), _bias_shapes.begin(), _dst_shapes.begin(), _infos.begin());
     }
int size () const inline
Definition at line 98 of file ConvolutionLayerDataset.h.
References arm_compute::test::fixed_point_arithmetic::detail::min().
     {
         return std::min(_src_shapes.size(), std::min(_weight_shapes.size(), std::min(_bias_shapes.size(), std::min(_dst_shapes.size(), _infos.size()))));
     }
The documentation for this class was generated from the following file:
tests/datasets/ConvolutionLayerDataset.h