Compute Library: FlattenLayerValidationFixture< TensorType, AccessorType, FunctionType, T > Class Template Reference
FlattenLayerValidationFixture< TensorType, AccessorType, FunctionType, T > Class Template Reference
#include <FlattenLayerFixture.h>
Public Member Functions
template<typename... >
void setup (TensorShape shape, DataType data_type)
Public Member Functions inherited from Fixture
void setup ()
Setup function.
void teardown ()
Teardown function.
Detailed Description
template<typename TensorType, typename AccessorType, typename FunctionType, typename T>
class arm_compute::test::validation::FlattenLayerValidationFixture< TensorType, AccessorType, FunctionType, T >
Definition at line 47 of file FlattenLayerFixture.h.
Member Function Documentation
void setup (TensorShape shape, DataType data_type) inline
Definition at line 51 of file FlattenLayerFixture.h.
References ARM_COMPUTE_ERROR_ON_MISMATCHING_DIMENSIONS, arm_compute::test::validation::ARM_COMPUTE_EXPECT(), TensorShape::collapse(), arm_compute::test::validation::data_type, arm_compute::test::validation::dst, arm_compute::test::framework::ERRORS, arm_compute::test::validation::reference::flatten_layer(), arm_compute::is_data_type_fixed_point(), arm_compute::test::library, arm_compute::test::validation::shape, arm_compute::test::validation::src, and arm_compute::U.
     {
         _fractional_bits = is_data_type_fixed_point(data_type) ? 4 : 0;
         _target          = compute_target(shape, data_type);
         _reference       = compute_reference(shape, data_type);
         ARM_COMPUTE_ERROR_ON_MISMATCHING_DIMENSIONS(_target.info()->tensor_shape(), _reference.shape());
     }
The documentation for this class was generated from the following file:
tests/validation/fixtures/FlattenLayerFixture.h