Compute Library: NEGEMMAssemblyBaseKernel Class Reference
NEGEMMAssemblyBaseKernel Class Reference abstract
Base class for GEMM NEON kernels implemented in Assembly.
#include <NEGEMMAssemblyBaseKernel.h>
Public Member Functions
NEGEMMAssemblyBaseKernel ()
Constructor.
NEGEMMAssemblyBaseKernel (const NEGEMMAssemblyBaseKernel &)=delete
Prevent instances of this class from being copied (As this class contains pointers)
NEGEMMAssemblyBaseKernel & operator= (const NEGEMMAssemblyBaseKernel &)=delete
Prevent instances of this class from being copied (As this class contains pointers)
NEGEMMAssemblyBaseKernel (NEGEMMAssemblyBaseKernel &&)=default
Allow instances of this class to be moved.
NEGEMMAssemblyBaseKernel & operator= (NEGEMMAssemblyBaseKernel &&)=default
Allow instances of this class to be moved.
virtual ~NEGEMMAssemblyBaseKernel ()=default
void configure (const ITensor *input0, const ITensor *input1, ITensor *output, ITensor *workspace, float alpha=1.f, float beta=0.f, bool is_transposed_0=false, bool is_transposed_1=false)
Initialise the kernel's input and output.
Public Member Functions inherited from ICPPKernel
virtual ~ICPPKernel ()=default
Default destructor.
virtual void run (const Window &window, const ThreadInfo &info)=0
Execute the kernel on the passed window.
Public Member Functions inherited from IKernel
IKernel ()
Constructor.
virtual ~IKernel ()=default
Destructor.
virtual bool is_parallelisable () const
Indicates whether or not the kernel is parallelisable.
virtual BorderSize border_size () const
The size of the border for that kernel.
const Window & window () const
The maximum window the kernel can be executed on.
Detailed Description
Base class for GEMM NEON kernels implemented in Assembly.
Definition at line 34 of file NEGEMMAssemblyBaseKernel.h.
Constructor & Destructor Documentation
NEGEMMAssemblyBaseKernel () inline
Constructor.
Definition at line 38 of file NEGEMMAssemblyBaseKernel.h.
References NEGEMMAssemblyBaseKernel::operator=(), and NEGEMMAssemblyBaseKernel::~NEGEMMAssemblyBaseKernel().
         : _input0(nullptr), _input1(nullptr), _output(nullptr), _workspace(nullptr), _alpha(1.f), _beta(0.f), _is_transposed_0(false), _is_transposed_1(false)
     {
     }
NEGEMMAssemblyBaseKernel (const NEGEMMAssemblyBaseKernel &) delete
Prevent instances of this class from being copied (As this class contains pointers)
NEGEMMAssemblyBaseKernel (NEGEMMAssemblyBaseKernel &&) default
Allow instances of this class to be moved.
virtual ~NEGEMMAssemblyBaseKernel () virtual default
Referenced by NEGEMMAssemblyBaseKernel::NEGEMMAssemblyBaseKernel().
Member Function Documentation
void configure (const ITensor * input0, const ITensor * input1, ITensor * output, ITensor * workspace, float alpha = 1.f, float beta = 0.f, bool is_transposed_0 = false, bool is_transposed_1 = false) inline
Initialise the kernel's input and output.
The computed function is C = a * AxB + b * C.
Parameters
[in] input0 Input tensor containing the Matrix A. Data types supported: F32
[in] input1 Input tensor containing the Matrix B. Data types supported: same as input0
[in,out] output Output tensor to store the result of matrix multiplication. If beta is not zero the values are multiplied by beta before the result is accumulated. Otherwise the values are overwritten by the result. Data types supported: same as input0.
[out] workspace Space for intermediate results.
[in] alpha Weight of the matrix product
[in] beta Weight of the accumulation.
[in] is_transposed_0 (Optional)True if input0 is transposed else false. (Defaults to false)
[in] is_transposed_1 (Optional)True if input1 is transposed else false. (Defaults to false)
Definition at line 67 of file NEGEMMAssemblyBaseKernel.h.
References arm_compute::test::validation::alpha, and arm_compute::test::validation::beta.
     {
         internal_configure(input0, input1, output, workspace, alpha, beta, is_transposed_0, is_transposed_1);
     }
NEGEMMAssemblyBaseKernel& operator= (const NEGEMMAssemblyBaseKernel &) delete
Prevent instances of this class from being copied (As this class contains pointers)
Referenced by NEGEMMAssemblyBaseKernel::NEGEMMAssemblyBaseKernel().
NEGEMMAssemblyBaseKernel& operator= (NEGEMMAssemblyBaseKernel &&) default
Allow instances of this class to be moved.
The documentation for this class was generated from the following file:
arm_compute/core/NEON/kernels/NEGEMMAssemblyBaseKernel.h