Compute Library: ScaleLayerDataset Class Reference
ScaleLayerDataset Class Reference
#include <ScaleLayerDataset.h>
Data Structures
struct iterator
Public Types
using type = std::tuple< TensorShape, InterpolationPolicy, BorderMode, SamplingPolicy, float, float >
Public Member Functions
iterator begin () const
int size () const
void add_config (TensorShape src, InterpolationPolicy policy, BorderMode border_mode, SamplingPolicy sampling_policy, float scale_x, float scale_y)
Detailed Description
Definition at line 38 of file ScaleLayerDataset.h.
Member Typedef Documentation
using type = std::tuple<TensorShape, InterpolationPolicy, BorderMode, SamplingPolicy, float, float>
Definition at line 41 of file ScaleLayerDataset.h.
Member Function Documentation
void add_config (TensorShape src, InterpolationPolicy policy, BorderMode border_mode, SamplingPolicy sampling_policy, float scale_x, float scale_y) inline
Definition at line 108 of file ScaleLayerDataset.h.
Referenced by LargeScaleLayerShapes::LargeScaleLayerShapes(), and SmallScaleLayerShapes::SmallScaleLayerShapes().
     {
         _src_shapes.emplace_back(std::move(src));
         _policy.emplace_back(std::move(policy));
         _border_mode.emplace_back(std::move(border_mode));
         _sampling_policy.emplace_back(std::move(sampling_policy));
         _scale_x.emplace_back(std::move(scale_x));
         _scale_y.emplace_back(std::move(scale_y));
     }
iterator begin () const inline
Definition at line 98 of file ScaleLayerDataset.h.
References ScaleLayerDataset::iterator::iterator().
     {
         return iterator(_src_shapes.begin(), _policy.begin(), _border_mode.begin(), _sampling_policy.begin(), _scale_x.begin(), _scale_y.begin());
     }
int size () const inline
Definition at line 103 of file ScaleLayerDataset.h.
References arm_compute::test::fixed_point_arithmetic::detail::min().
     {
         return std::min(_src_shapes.size(), std::min(_policy.size(), std::min(_border_mode.size(), std::min(_sampling_policy.size(), std::min(_scale_x.size(), _scale_y.size())))));
     }
The documentation for this class was generated from the following file:
tests/datasets/ScaleLayerDataset.h