Compute Library: ConvolutionSquareValidationFixture< TensorType, AccessorType, FunctionType, T > Class Template Reference
ConvolutionSquareValidationFixture< TensorType, AccessorType, FunctionType, T > Class Template Reference
#include <ConvolutionFixture.h>
Public Member Functions
template<typename... >
void setup (TensorShape shape, DataType data_type, BorderMode border_mode, const unsigned int width)
Public Member Functions inherited from ConvolutionValidationFixture< TensorType, AccessorType, FunctionType, T >
template<typename... >
void setup (TensorShape input_shape, TensorShape weights_shape, TensorShape bias_shape, TensorShape output_shape, PadStrideInfo info, bool reshape_weights, DataType data_type)
Public Member Functions inherited from ConvolutionValidationGenericFixture< TensorType, AccessorType, FunctionType, T >
template<typename... >
void setup (TensorShape input_shape, TensorShape weights_shape, TensorShape bias_shape, TensorShape output_shape, PadStrideInfo info, bool reshape_weights, DataType data_type, int fractional_bits, QuantizationInfo quantization_info)
Public Member Functions inherited from Fixture
void setup ()
Setup function.
void teardown ()
Teardown function.
Additional Inherited Members
Public Types inherited from ConvolutionValidationGenericFixture< TensorType, AccessorType, FunctionType, T >
using TBias = typename std::conditional< std::is_same< typename std::decay< T >::type, uint8_t >::value, int32_t, T >::type
Detailed Description
template<typename TensorType, typename AccessorType, typename FunctionType, typename T>
class arm_compute::test::validation::ConvolutionSquareValidationFixture< TensorType, AccessorType, FunctionType, T >
Definition at line 149 of file ConvolutionFixture.h.
Member Function Documentation
void setup (TensorShape shape, DataType data_type, BorderMode border_mode, const unsigned int width) inline
Definition at line 153 of file ConvolutionFixture.h.
References arm_compute::test::validation::ARM_COMPUTE_EXPECT(), arm_compute::test::validation::border_mode, CLConvolutionSquare< matrix_size >::configure(), arm_compute::test::validation::conv, arm_compute::test::validation::convolution, arm_compute::test::validation::data_type, arm_compute::test::validation::dst, arm_compute::test::framework::ERRORS, arm_compute::test::validation::scale, Fixture::setup(), arm_compute::test::validation::shape, and arm_compute::test::validation::src.
     {
         ConvolutionValidationFixture<TensorType, AccessorType, FunctionType, T>::setup(shape, data_type, border_mode, width, width);
     }
The documentation for this class was generated from the following file:
tests/validation/fixtures/ConvolutionFixture.h