Compute Library: DepthConcatenateLayerFixture< TensorType, ITensorType, Function, AccessorType > Class Template Reference
DepthConcatenateLayerFixture< TensorType, ITensorType, Function, AccessorType > Class Template Reference
Fixture that can be used for NE/CL/GC.
#include <DepthConcatenateLayerFixture.h>
Public Member Functions
std::vector< TensorShape > generate_input_shapes (TensorShape shape)
template<typename... >
void setup (TensorShape shape, DataType data_type)
void run ()
void sync ()
void teardown ()
Public Member Functions inherited from Fixture
void setup ()
Setup function.
void teardown ()
Teardown function.
Detailed Description
template<typename TensorType, typename ITensorType, typename Function, typename AccessorType>
class arm_compute::test::benchmark::DepthConcatenateLayerFixture< TensorType, ITensorType, Function, AccessorType >
Fixture that can be used for NE/CL/GC.
Definition at line 45 of file DepthConcatenateLayerFixture.h.
Member Function Documentation
std::vector<TensorShape> generate_input_shapes (TensorShape shape) inline
Definition at line 48 of file DepthConcatenateLayerFixture.h.
References arm_compute::test::library.
Referenced by DepthConcatenateLayerFixture< TensorType, ITensorType, Function, AccessorType >::setup().
     {
         // Create input shapes
         std::mt19937                    gen(library->seed());
         std::uniform_int_distribution<> num_dis(2, 6);
         const int                       num_tensors = num_dis(gen);
         std::vector<TensorShape>         shapes(num_tensors, shape);
         std::uniform_int_distribution<>  depth_dis(1, 7);
         std::bernoulli_distribution      mutate_dis(0.25f);
         std::uniform_real_distribution<> change_dis(-0.25f, 0.f);
         // Generate more shapes based on the input
         for(auto &s : shapes)
         {
             // Set the depth of the tensor
             s.set(2, depth_dis(gen));
             // Randomly change the first dimension
             if(mutate_dis(gen))
             {
                 // Decrease the dimension by a small percentage. Don't increase
                 // as that could make tensor too large. Also the change must be
                 // an even number. Otherwise out depth concatenate fails.
                 s.set(0, s[0] + 2 * static_cast<int>(s[0] * change_dis(gen)));
             }
             // Repeat the same as above for the second dimension
             if(mutate_dis(gen))
             {
                 s.set(1, s[1] + 2 * static_cast<int>(s[1] * change_dis(gen)));
             }
         }
         return shapes;
     }
void run () inline
Definition at line 115 of file DepthConcatenateLayerFixture.h.
     {
         _depth_concat.run();
     }
void setup (TensorShape shape, DataType data_type) inline
Definition at line 86 of file DepthConcatenateLayerFixture.h.
References arm_compute::calculate_depth_concatenate_shape(), arm_compute::test::validation::data_type, DepthConcatenateLayerFixture< TensorType, ITensorType, Function, AccessorType >::generate_input_shapes(), and arm_compute::test::validation::src.
     {
         // Generate input shapes
         std::vector<TensorShape> src_shapes = generate_input_shapes(shape);
         // Create tensors
         _srcs.reserve(src_shapes.size());
         std::vector<ITensorType *> src_ptrs;
         for(const auto &shape : src_shapes)
         {
             _srcs.emplace_back(create_tensor<TensorType>(shape, data_type, 1, _fractional_bits));
             src_ptrs.emplace_back(&_srcs.back());
         }
         TensorShape dst_shape = calculate_depth_concatenate_shape(src_ptrs);
         _dst                  = create_tensor<TensorType>(dst_shape, data_type, 1, _fractional_bits);
         _depth_concat.configure(src_ptrs, &_dst);
         for(auto &src : _srcs)
         {
             src.allocator()->allocate();
         }
         _dst.allocator()->allocate();
     }
void sync () inline
Definition at line 120 of file DepthConcatenateLayerFixture.h.
     {
         sync_if_necessary<TensorType>();
         sync_tensor_if_necessary<TensorType>(_dst);
     }
void teardown () inline
Definition at line 126 of file DepthConcatenateLayerFixture.h.
References arm_compute::test::validation::src.
     {
         for(auto &src : _srcs)
         {
             src.allocator()->free();
         }
         _srcs.clear();
         _dst.allocator()->free();
     }
The documentation for this class was generated from the following file:
tests/benchmark/fixtures/DepthConcatenateLayerFixture.h