Compute Library: CLArrayAccessor< T > Class Template Reference
CLArrayAccessor< T > Class Template Reference
Accessor implementation for CLArray objects.
#include <CLArrayAccessor.h>
Public Member Functions
CLArrayAccessor (CLArray< T > &array)
Create an accessor for the given array.
CLArrayAccessor (const CLArrayAccessor &)=delete
CLArrayAccessor & operator= (const CLArrayAccessor &)=delete
CLArrayAccessor (CLArrayAccessor &&)=default
CLArrayAccessor & operator= (CLArrayAccessor &&)=default
~CLArrayAccessor ()
Destructor that unmaps the CL memory.
size_t num_values () const override
Number of elements of the tensor.
T * buffer () override
Access to the buffer.
void resize (size_t num) override
Resize array.
T & at (size_t index) const override
Reference to the element of the array located at the given index.
Public Member Functions inherited from IArrayAccessor< T >
virtual ~IArrayAccessor ()=default
Virtual destructor.
Additional Inherited Members
Public Types inherited from IArrayAccessor< T >
using value_type = T
Detailed Description
template<typename T>
class arm_compute::test::CLArrayAccessor< T >
Accessor implementation for CLArray objects.
Definition at line 36 of file CLArrayAccessor.h.
Constructor & Destructor Documentation
CLArrayAccessor (CLArray< T > & array) inline
Create an accessor for the given array.
Parameters
[in,out] array To be accessed array.
Note
The CL memory is mapped by the constructor.
Definition at line 46 of file CLArrayAccessor.h.
References CLArrayAccessor< T >::operator=().
         : _array{ array }
     {
         _array.map();
     }
CLArrayAccessor (const CLArrayAccessor< T > &) delete
CLArrayAccessor (CLArrayAccessor< T > &&) default
~CLArrayAccessor () inline
Destructor that unmaps the CL memory.
Definition at line 58 of file CLArrayAccessor.h.
     {
         _array.unmap();
     }
Member Function Documentation
T& at (size_t index) const inline override virtual
Reference to the element of the array located at the given index.
Parameters
[in] index Index of the element
Returns
A reference to the element of the array located at the given index.
Implements IArrayAccessor< T >.
Definition at line 78 of file CLArrayAccessor.h.
References ARM_COMPUTE_ERROR_ON, and CLArrayAccessor< T >::num_values().
     {
         ARM_COMPUTE_ERROR_ON(_array.buffer() == nullptr);
         ARM_COMPUTE_ERROR_ON(index >= num_values());
         return _array.buffer()[index];
     }
T* buffer () inline override virtual
Access to the buffer.
Returns
A pointer to the first element in the buffer.
Implements IArrayAccessor< T >.
Definition at line 68 of file CLArrayAccessor.h.
Referenced by arm_compute::test::validation::FIXTURE_DATA_TEST_CASE().
     {
         return _array.buffer();
     }
size_t num_values () const inline override virtual
Number of elements of the tensor.
Implements IArrayAccessor< T >.
Definition at line 63 of file CLArrayAccessor.h.
Referenced by CLArrayAccessor< T >::at(), and arm_compute::test::validation::FIXTURE_DATA_TEST_CASE().
     {
         return _array.num_values();
     }
CLArrayAccessor& operator= (const CLArrayAccessor< T > &) delete
Referenced by CLArrayAccessor< T >::CLArrayAccessor().
CLArrayAccessor& operator= (CLArrayAccessor< T > &&) default
void resize (size_t num) inline override virtual
Resize array.
Parameters
[in] num The new array size in number of elements
Implements IArrayAccessor< T >.
Definition at line 73 of file CLArrayAccessor.h.
     {
         _array.resize(num);
     }
The documentation for this class was generated from the following file:
tests/CL/CLArrayAccessor.h