Compute Library: NodeContext Class Reference
NodeContext Class Reference
Node Context class.
#include <NodeContext.h>
Public Member Functions
NodeContext (OperationType operation)
Default Constructor.
void set_target (TargetHint target)
Sets the execution target of the node.
void add_input (arm_compute::ITensor *input)
Adds an input tensor to the context.
void add_output (arm_compute::ITensor *output)
Adds and output to the context.
template<typename T >
void add_parameter (std::string name, T parameter)
Adds a parameter to the context.
OperationType operation () const
Returns the operation of this node.
TargetHint target () const
Returns the execution target of this node.
arm_compute::ITensor * input (size_t idx) const
Returns input tensor of a given index.
arm_compute::ITensor * output (size_t idx) const
Returns output tensor of a given index.
template<typename T >
T parameter (std::string name) const
Returns the parameter with the given name.
size_t num_inputs () const
Returns number of inputs.
size_t num_outputs () const
Returns number of output.
Detailed Description
Node Context class.
Node context class is used to hold all the parameters required by a node to execute
Definition at line 44 of file NodeContext.h.
Constructor & Destructor Documentation
NodeContext (OperationType operation) inline
Default Constructor.
Parameters
[in] operation Name of the operation
Definition at line 51 of file NodeContext.h.
References NodeContext::add_input(), NodeContext::add_output(), NodeContext::add_parameter(), NodeContext::input(), NodeContext::num_inputs(), NodeContext::num_outputs(), NodeContext::operation(), NodeContext::output(), NodeContext::parameter(), NodeContext::set_target(), and NodeContext::target().
         : _operation(operation), _target(TargetHint::DONT_CARE), _inputs(), _outputs(), _parameters() {};
Member Function Documentation
void add_input (arm_compute::ITensor * input)
Adds an input tensor to the context.
Parameters
[in] input Input to add
Referenced by NodeContext::NodeContext().
void add_output (arm_compute::ITensor * output)
Adds and output to the context.
Parameters
[in] output Output to add
Referenced by NodeContext::NodeContext().
void add_parameter (std::string name, T parameter) inline
Adds a parameter to the context.
Parameters
[in] name Parameter name
[in] parameter Parameter to add
Definition at line 127 of file NodeContext.h.
References ARM_COMPUTE_ERROR_ON_MSG, and NodeContext::parameter().
Referenced by NodeContext::NodeContext().
 {
     ARM_COMPUTE_ERROR_ON_MSG(_parameters.find(name) != _parameters.end(), "Parameter already exists!");
     _parameters[name] = support::cpp14::make_unique<NodeParameter<T>>(name, parameter);
 }
arm_compute::ITensor* input (size_t idx) const
Returns input tensor of a given index.
Parameters
[in] idx Index of the input tensor
Returns
A pointer the requested input tensor else nullptr
Referenced by NodeContext::NodeContext().
size_t num_inputs () const
Returns number of inputs.
Returns
Number of inputs
Referenced by NodeContext::NodeContext().
size_t num_outputs () const
Returns number of output.
Returns
Number of outputs
Referenced by NodeContext::NodeContext().
OperationType operation () const
Returns the operation of this node.
Returns
The operation type
Referenced by NodeContext::NodeContext().
arm_compute::ITensor* output (size_t idx) const
Returns output tensor of a given index.
Parameters
[in] idx Index of the output tensor
Returns
A pointer the requested output tensor else nullptr
Referenced by NodeContext::NodeContext().
T parameter (std::string name) const inline
Returns the parameter with the given name.
Parameters
[in] name Parameter name
Returns
The requested parameter else an empty object
Definition at line 134 of file NodeContext.h.
References ARM_COMPUTE_ERROR_ON, and value.
Referenced by NodeContext::add_parameter(), and NodeContext::NodeContext().
 {
     auto it = _parameters.find(name);
     ARM_COMPUTE_ERROR_ON(it == _parameters.end());
     return static_cast<NodeParameter<T> *>(it->second.get())->value();
 }
void set_target (TargetHint target)
Sets the execution target of the node.
Parameters
[in] target Execution target of the node
Referenced by NodeContext::NodeContext().
TargetHint target () const
Returns the execution target of this node.
Returns
The execution target
Referenced by NodeContext::NodeContext().
The documentation for this class was generated from the following file:
arm_compute/graph/NodeContext.h