Compute Library: Status Class Reference
Status Class Reference
Status class.
#include <Error.h>
Public Member Functions
Status ()
Default Constructor.
Status (ErrorCode error_status, std::string error_description=" ")
Default Constructor.
Status (const Status &)=default
Allow instances of this class to be copy constructed.
Status (Status &&)=default
Allow instances of this class to be move constructed.
Status & operator= (const Status &)=default
Allow instances of this class to be copy assigned.
Status & operator= (Status &&)=default
Allow instances of this class to be move assigned.
operator bool () const noexcept
Explicit bool conversion operator.
ErrorCode error_code () const
Gets error code.
std::string error_description () const
Gets error description if any.
void throw_if_error ()
Throws a runtime exception in case it contains a valid error status.
Detailed Description
Status class.
Definition at line 39 of file Error.h.
Constructor & Destructor Documentation
Status () inline
Default Constructor.
Definition at line 43 of file Error.h.
         : _code(ErrorCode::OK), _error_description(" ")
     {
     }
Status (ErrorCode error_status, std::string error_description = " ") inline explicit
Default Constructor.
Parameters
error_status Error status.
error_description (Optional) Error description if error_status is not valid.
Definition at line 52 of file Error.h.
         : _code(error_status), _error_description(error_description)
     {
     }
Status (const Status &) default
Allow instances of this class to be copy constructed.
Status (Status &&) default
Allow instances of this class to be move constructed.
Member Function Documentation
ErrorCode error_code () const inline
Gets error code.
Returns
Error code.
Definition at line 76 of file Error.h.
     {
         return _code;
     }
std::string error_description () const inline
Gets error description if any.
Returns
Error description.
Definition at line 84 of file Error.h.
     {
         return _error_description;
     }
operator bool () const inline explicit noexcept
Explicit bool conversion operator.
Returns
True if there is no error else false
Definition at line 68 of file Error.h.
References arm_compute::OK.
     {
         return _code == ErrorCode::OK;
     }
Status& operator= (const Status &) default
Allow instances of this class to be copy assigned.
Status& operator= (Status &&) default
Allow instances of this class to be move assigned.
void throw_if_error () inline
Throws a runtime exception in case it contains a valid error status.
Definition at line 89 of file Error.h.
References caffe_data_extractor::args, arm_compute::create_error(), arm_compute::create_error_va_list(), and arm_compute::error().
     {
         if(!bool(*this))
         {
             internal_throw_on_error();
         }
     }
The documentation for this class was generated from the following file:
arm_compute/core/Error.h