Compute Library: Coordinates Class Reference
Coordinates Class Reference
Coordinates of an item.
#include <Coordinates.h>
Public Member Functions
template<typename... Ts>
constexpr Coordinates (Ts...coords)
Constructor to initialize the coordinates.
constexpr Coordinates (const Coordinates &)=default
Allow instances of this class to be copy constructed.
Coordinates & operator= (const Coordinates &)=default
Allow instances of this class to be copied.
constexpr Coordinates (Coordinates &&)=default
Allow instances of this class to be move constructed.
Coordinates & operator= (Coordinates &&)=default
Allow instances of this class to be moved.
~Coordinates ()=default
Default destructor.
Public Member Functions inherited from Dimensions< int >
Dimensions (Ts...dims)
Constructor to initialize the tensor shape.
Dimensions (const Dimensions &)=default
Allow instances of this class to be copy constructed.
Dimensions (Dimensions &&)=default
Allow instances of this class to be move constructed.
Dimensions & operator= (const Dimensions &)=default
Allow instances of this class to be copied.
Dimensions & operator= (Dimensions &&)=default
Allow instances of this class to be moved.
void set (size_t dimension, intvalue)
Accessor to set the value of one of the dimensions.
int x () const
Alias to access the size of the first dimension.
int y () const
Alias to access the size of the second dimension.
int z () const
Alias to access the size of the third dimension.
const int & operator[] (size_t dimension) const
Generic accessor to get the size of any dimension.
int & operator[] (size_t dimension)
Generic accessor to get the size of any dimension.
unsigned int num_dimensions () const
Returns the effective dimensionality of the tensor.
void set_num_dimensions (size_t num_dimensions)
Set number of dimensions.
void collapse (size_t n, size_t first=0)
Collapse dimensions.
void collapse_from (size_t start)
Collapse dimensions starting from a given point.
std::array< int, num_max_dimensions >::iterator begin ()
Returns a read/write iterator that points to the first element in the dimension array.
std::array< int, num_max_dimensions >::const_iterator begin () const
Returns a read-only (constant) iterator that points to the first element in the dimension array.
std::array< int, num_max_dimensions >::const_iterator cbegin () const
Returns a read-only (constant) iterator that points to the first element in the dimension array.
std::array< int, num_max_dimensions >::iterator end ()
Returns a read/write iterator that points one past the last element in the dimension array.
std::array< int, num_max_dimensions >::const_iterator end () const
Returns a read-only (constant) iterator that points one past the last element in the dimension array.
std::array< int, num_max_dimensions >::const_iterator cend () const
Returns a read-only (constant) iterator that points one past the last element in the dimension array.
Additional Inherited Members
Static Public Attributes inherited from Dimensions< int >
static constexpr size_t num_max_dimensions
Number of dimensions the tensor has.
Detailed Description
Coordinates of an item.
Definition at line 37 of file Coordinates.h.
Constructor & Destructor Documentation
constexpr Coordinates (Ts... coords) inline
Constructor to initialize the coordinates.
Parameters
[in] coords Values to initialize the dimensions.
Definition at line 45 of file Coordinates.h.
References Coordinates::operator=(), and Coordinates::~Coordinates().
         : Dimensions{ coords... }
     {
     }
constexpr Coordinates (const Coordinates &) default
Allow instances of this class to be copy constructed.
constexpr Coordinates (Coordinates &&) default
Allow instances of this class to be move constructed.
~Coordinates () default
Default destructor.
Referenced by Coordinates::Coordinates().
Member Function Documentation
Coordinates& operator= (const Coordinates &) default
Allow instances of this class to be copied.
Referenced by Coordinates::Coordinates().
Coordinates& operator= (Coordinates &&) default
Allow instances of this class to be moved.
The documentation for this class was generated from the following file:
arm_compute/core/Coordinates.h