Compute Library: HOGDescriptorDataset Class Reference
HOGDescriptorDataset Class Reference
#include <HOGDescriptorDataset.h>
Data Structures
struct iterator
Public Types
using type = std::tuple< std::string, HOGInfo >
Public Member Functions
iterator begin () const
int size () const
void add_config (std::string image, Size2D cell_size, Size2D block_size, Size2D detection_window_size, Size2D block_stride, size_t num_bins, HOGNormType normalization_type, float l2_hyst_threshold, PhaseType phase_type)
Detailed Description
Definition at line 35 of file HOGDescriptorDataset.h.
Member Typedef Documentation
using type = std::tuple<std::string, HOGInfo>
Definition at line 38 of file HOGDescriptorDataset.h.
Member Function Documentation
void add_config (std::string image, Size2D cell_size, Size2D block_size, Size2D detection_window_size, Size2D block_stride, size_t num_bins, HOGNormType normalization_type, float l2_hyst_threshold, PhaseType phase_type) inline
Definition at line 86 of file HOGDescriptorDataset.h.
Referenced by LargeHOGDescriptorDataset::LargeHOGDescriptorDataset(), and SmallHOGDescriptorDataset::SmallHOGDescriptorDataset().
     {
         _image.emplace_back(std::move(image));
         _hog_info.emplace_back(HOGInfo(cell_size, block_size, detection_window_size, block_stride, num_bins, normalization_type, l2_hyst_threshold, phase_type));
     }
iterator begin () const inline
Definition at line 76 of file HOGDescriptorDataset.h.
References HOGDescriptorDataset::iterator::iterator().
     {
         return iterator(_image.begin(), _hog_info.begin());
     }
int size () const inline
Definition at line 81 of file HOGDescriptorDataset.h.
References arm_compute::test::fixed_point_arithmetic::detail::min().
     {
         return std::min(_image.size(), _hog_info.size());
     }
The documentation for this class was generated from the following file:
tests/datasets/HOGDescriptorDataset.h