Compute Library: GEMMLowpQuantizeDownInt32ToUint8ScaleByFixedPointValidationFixture< TensorType, AccessorType, FunctionType > Class Template Reference
GEMMLowpQuantizeDownInt32ToUint8ScaleByFixedPointValidationFixture< TensorType, AccessorType, FunctionType > Class Template Reference
#include <GEMMLowpFixture.h>
Public Member Functions
template<typename... >
void setup (TensorShape shape, int32_t result_fixedpoint_multiplier, int32_t result_shift, int32_t result_offset_after_shift, int32_t min, int32_t max, bool add_bias)
Public Member Functions inherited from Fixture
void setup ()
Setup function.
void teardown ()
Teardown function.
Detailed Description
template<typename TensorType, typename AccessorType, typename FunctionType>
class arm_compute::test::validation::GEMMLowpQuantizeDownInt32ToUint8ScaleByFixedPointValidationFixture< TensorType, AccessorType, FunctionType >
Definition at line 212 of file GEMMLowpFixture.h.
Member Function Documentation
void setup (TensorShape shape, int32_t result_fixedpoint_multiplier, int32_t result_shift, int32_t result_offset_after_shift, int32_t min, int32_t max, bool add_bias) inline
Definition at line 216 of file GEMMLowpFixture.h.
References arm_compute::test::validation::a, arm_compute::test::validation::ARM_COMPUTE_EXPECT(), arm_compute::test::validation::b, arm_compute::test::validation::c, arm_compute::test::framework::ERRORS, arm_compute::test::library, arm_compute::test::fixed_point_arithmetic::detail::max(), arm_compute::test::fixed_point_arithmetic::detail::min(), arm_compute::QASYMM8, arm_compute::S32, arm_compute::test::validation::shape, and arm_compute::U.
     {
         _target    = compute_target(shape, result_fixedpoint_multiplier, result_shift, result_offset_after_shift, min, max, add_bias);
         _reference = compute_reference(shape, result_fixedpoint_multiplier, result_shift, result_offset_after_shift, min, max, add_bias);
     }
The documentation for this class was generated from the following file:
tests/validation/fixtures/GEMMLowpFixture.h