Compute Library: TestCaseFactory Class Reference
TestCaseFactory Class Reference abstract
Abstract factory class to create test cases.
#include <TestCaseFactory.h>
Public Types
enum Status { ACTIVE, EXPECTED_FAILURE, DISABLED }
Test case status.
Public Member Functions
TestCaseFactory (std::string suite_name, std::string name, DatasetMode mode, Status status, std::string description="")
Constructor.
virtual ~TestCaseFactory ()=default
Default destructor.
std::string name () const
Name of the test case.
DatasetMode mode () const
Get the mode for which test case will be enabled.
Status status () const
Get the status of the test case.
virtual std::unique_ptr< TestCase > make () const =0
Factory function to create the test case.
Detailed Description
Abstract factory class to create test cases.
Definition at line 41 of file TestCaseFactory.h.
Member Enumeration Documentation
enum Status strong
Test case status.
ACTIVE == Test is run and result is validated. Failure on failed validation. EXPECTED_FAILURE == Test is run and result is validated. Failure on successful validation. DISABLED == Test is not run.
Enumerator
ACTIVE
EXPECTED_FAILURE
DISABLED
Definition at line 50 of file TestCaseFactory.h.
     {
         ACTIVE,
         EXPECTED_FAILURE,
         DISABLED
     };
Constructor & Destructor Documentation
TestCaseFactory (std::string suite_name, std::string name, DatasetMode mode, Status status, std::string description = "") inline
Constructor.
Parameters
[in] suite_name Name of the test suite to which the test case has been added.
[in] name Name of the test case.
[in] mode Datset mode of the test case.
[in] status Status of the test case.
[in] description Description of data arguments.
Definition at line 134 of file TestCaseFactory.h.
References TestCaseFactory::mode(), and TestCaseFactory::status().
     : _suite_name{ std::move(suite_name) }, _test_name{ std::move(test_name) }, _data_description{ std::move(description) }, _mode{ mode }, _status{ status }
 {
 }
virtual ~TestCaseFactory () virtual default
Default destructor.
Member Function Documentation
virtual std::unique_ptr<TestCase> make () const pure virtual
Factory function to create the test case.
Returns
Unique pointer to a newly created test case.
Implemented in DataTestCaseFactory< T, D >, and SimpleTestCaseFactory< T >.
Referenced by Framework::error_on_missing_assets().
DatasetMode mode () const inline
Get the mode for which test case will be enabled.
Returns
Dataset mode of the test case.
Definition at line 152 of file TestCaseFactory.h.
Referenced by DataTestCaseFactory< T, D >::DataTestCaseFactory(), Framework::run(), and TestCaseFactory::TestCaseFactory().
 {
     return _mode;
 }
std::string name () const inline
Name of the test case.
Returns
Name of the test case.
Definition at line 140 of file TestCaseFactory.h.
Referenced by Framework::run().
 {
     std::string name = _suite_name + "/" + _test_name;
     if(!_data_description.empty())
     {
         name += "@" + _data_description;
     }
     return name;
 }
TestCaseFactory::Status status () const inline
Get the status of the test case.
Returns
Status of the test case.
Definition at line 157 of file TestCaseFactory.h.
Referenced by DataTestCaseFactory< T, D >::DataTestCaseFactory(), Framework::error_on_missing_assets(), Framework::run(), and TestCaseFactory::TestCaseFactory().
 {
     return _status;
 }
The documentation for this class was generated from the following file:
tests/framework/TestCaseFactory.h