Compute Library: PMUCounter Class Reference
PMUCounter Class Reference
Implementation of an instrument to count CPU cycles.
#include <PMUCounter.h>
Public Member Functions
PMUCounter (ScaleFactor scale_factor)
std::string id () const override
Identifier for the instrument.
void start () override
Start measuring.
void stop () override
Stop measuring.
MeasurementsMap measurements () const override
Return the latest measurement.
Public Member Functions inherited from Instrument
Instrument ()=default
Instrument (const Instrument &)=default
Instrument (Instrument &&)=default
Instrument & operator= (const Instrument &)=default
Instrument & operator= (Instrument &&)=default
virtual ~Instrument ()=default
Additional Inherited Members
Public Types inherited from Instrument
using MeasurementsMap = std::map< std::string, Measurement >
Static Public Member Functions inherited from Instrument
template<typename T , ScaleFactor scale>
static std::unique_ptr< Instrument > make_instrument ()
Helper function to create an instrument of the given type.
Detailed Description
Implementation of an instrument to count CPU cycles.
Definition at line 37 of file PMUCounter.h.
Constructor & Destructor Documentation
PMUCounter (ScaleFactor scale_factor) inline
Definition at line 40 of file PMUCounter.h.
References ARM_COMPUTE_ERROR, PMUCounter::id(), PMUCounter::measurements(), arm_compute::test::framework::NONE, arm_compute::test::framework::SCALE_1K, arm_compute::test::framework::SCALE_1M, PMUCounter::start(), and PMUCounter::stop().
     {
         switch(scale_factor)
         {
             case ScaleFactor::NONE:
                 _scale_factor = 1;
                 _unit         = "";
                 break;
             case ScaleFactor::SCALE_1K:
                 _scale_factor = 1000;
                 _unit         = "K ";
                 break;
             case ScaleFactor::SCALE_1M:
                 _scale_factor = 1000000;
                 _unit         = "M ";
                 break;
             default:
                 ARM_COMPUTE_ERROR("Invalid scale");
         }
     };
Member Function Documentation
std::string id () const override virtual
Identifier for the instrument.
Implements Instrument.
Definition at line 32 of file PMUCounter.cpp.
Referenced by PMUCounter::PMUCounter().
 {
     return "PMU Counter";
 }
Instrument::MeasurementsMap measurements () const override virtual
Return the latest measurement.
Implements Instrument.
Definition at line 64 of file PMUCounter.cpp.
Referenced by PMUCounter::PMUCounter().
 {
     return MeasurementsMap
     {
         { "CPU cycles", Measurement(_cycles / _scale_factor, _unit + "cycles") },
         { "CPU instructions", Measurement(_instructions / _scale_factor, _unit + "instructions") },
     };
 }
void start () override virtual
Start measuring.
Implements Instrument.
Definition at line 37 of file PMUCounter.cpp.
References PMU::reset().
Referenced by PMUCounter::PMUCounter().
 {
     _pmu_cycles.reset();
     _pmu_instructions.reset();
 }
void stop () override virtual
Stop measuring.
Implements Instrument.
Definition at line 43 of file PMUCounter.cpp.
References PMU::get_value().
Referenced by PMUCounter::PMUCounter().
 {
     try
     {
         _cycles = _pmu_cycles.get_value<long long>();
     }
     catch(const std::runtime_error &)
     {
         _cycles = 0;
     }
     try
     {
         _instructions = _pmu_instructions.get_value<long long>();
     }
     catch(const std::runtime_error &)
     {
         _instructions = 0;
     }
 }
The documentation for this class was generated from the following files:
tests/framework/instruments/PMUCounter.h
tests/framework/instruments/PMUCounter.cpp