Compute Library: GoogLeNetInceptionV1ActivationLayerDataset Class Reference
GoogLeNetInceptionV1ActivationLayerDataset Class Reference final
#include <GoogLeNetInceptionV1ActivationLayerDataset.h>
Public Member Functions
GoogLeNetInceptionV1ActivationLayerDataset ()
GoogLeNetInceptionV1ActivationLayerDataset (GoogLeNetInceptionV1ActivationLayerDataset &&)=default
~GoogLeNetInceptionV1ActivationLayerDataset ()=default
Public Member Functions inherited from CartesianProductDataset< framework::dataset::InitializerListDataset< TensorShape >, framework::dataset::SingletonDataset< ActivationLayerInfo > >
CartesianProductDataset (framework::dataset::InitializerListDataset< TensorShape > &&dataset1, framework::dataset::SingletonDataset< ActivationLayerInfo > &&dataset2)
Construct dataset from the given datasets.
CartesianProductDataset (CartesianProductDataset &&)=default
iterator begin () const
Iterator pointing at the begin of the dataset.
int size () const
Size of the dataset.
Public Member Functions inherited from Dataset
Dataset (Dataset &&)=default
Additional Inherited Members
Public Types inherited from CartesianProductDataset< framework::dataset::InitializerListDataset< TensorShape >, framework::dataset::SingletonDataset< ActivationLayerInfo > >
using type = decltype(std::tuple_cat(*std::declval< iter1_type >(),*std::declval< iter2_type >()))
Type of the dataset.
Detailed Description
Definition at line 40 of file GoogLeNetInceptionV1ActivationLayerDataset.h.
Constructor & Destructor Documentation
GoogLeNetInceptionV1ActivationLayerDataset () inline
Definition at line 44 of file GoogLeNetInceptionV1ActivationLayerDataset.h.
References arm_compute::test::framework::dataset::make(), ActivationLayerInfo::RELU, arm_compute::U, and GoogLeNetInceptionV1ActivationLayerDataset::~GoogLeNetInceptionV1ActivationLayerDataset().
         : CartesianProductDataset
     {
         framework::dataset::make("Shape", { // conv1/relu_7x7
             TensorShape(112U, 112U, 64U),
             // conv2/relu_3x3_reduce
             TensorShape(56U, 56U, 64U),
             // conv2/relu_3x3
             TensorShape(56U, 56U, 192U),
             // inception_3a/relu_1x1, inception_3b/relu_pool_proj
             TensorShape(28U, 28U, 64U),
             // inception_3a/relu_3x3_reduce, inception_3b/relu_5x5
             TensorShape(28U, 28U, 96U),
             // inception_3a/relu_3x3, inception_3b/relu_1x1, inception_3b/relu_3x3_reduce
             TensorShape(28U, 28U, 128U),
             // inception_3a/relu_5x5_reduce
             TensorShape(28U, 28U, 16U),
             // inception_3a/relu_5x5, inception_3a/relu_pool_proj, inception_3b/relu_5x5_reduce
             TensorShape(28U, 28U, 32U),
             // inception_3b/relu_3x3
             TensorShape(28U, 28U, 192U),
             // inception_4a/relu_1x1
             TensorShape(14U, 14U, 192U),
             // inception_4a/relu_3x3_reduce
             TensorShape(14U, 14U, 96U),
             // inception_4a/relu_3x3
             TensorShape(14U, 14U, 208U),
             // inception_4a/relu_5x5_reduce
             TensorShape(14U, 14U, 16U),
             // inception_4a/relu_5x5
             TensorShape(14U, 14U, 48U),
             // inception_4a/relu_pool_proj, inception_4b/relu_5x5, inception_4b/relu_pool_proj, inception_4c/relu_5x5, inception_4c/relu_pool_proj, inception_4d/relu_5x5, inception_4d/relu_pool_proj
             TensorShape(14U, 14U, 64U),
             // inception_4b/relu_1x1, inception_4e/relu_3x3_reduce
             TensorShape(14U, 14U, 160U),
             // inception_4b/relu_3x3_reduce, inception_4d/relu_1x1
             TensorShape(14U, 14U, 112U),
             // inception_4b/relu_3x3
             TensorShape(14U, 14U, 224U),
             // inception_4b/relu_5x5_reduce, inception_4c/relu_5x5_reduce
             TensorShape(14U, 14U, 24U),
             // inception_4c/relu_1x1, inception_4c/relu_3x3_reduce, inception_4e/relu_5x5, inception_4e/relu_pool_proj
             TensorShape(14U, 14U, 128U),
             // inception_4c/relu_3x3, inception_4e/relu_1x1
             TensorShape(14U, 14U, 256U),
             // inception_4d/relu_3x3_reduce
             TensorShape(14U, 14U, 144U),
             // inception_4d/relu_3x3
             TensorShape(14U, 14U, 288U),
             // inception_4d/relu_5x5_reduce, inception_4e/relu_5x5_reduce
             TensorShape(14U, 14U, 32U),
             // inception_4e/relu_3x3
             TensorShape(14U, 14U, 320U),
             // inception_5a/relu_1x1
             TensorShape(7U, 7U, 256U),
             // inception_5a/relu_3x3_reduce
             TensorShape(7U, 7U, 160U),
             // inception_5a/relu_3x3
             TensorShape(7U, 7U, 320U),
             // inception_5a/relu_5x5_reduce
             TensorShape(7U, 7U, 32U),
             // inception_5a/relu_5x5, inception_5a/relu_pool_proj, inception_5b/relu_5x5, inception_5b/relu_pool_proj
             TensorShape(7U, 7U, 128U),
             // inception_5b/relu_1x1, inception_5b/relu_3x3
             TensorShape(7U, 7U, 384U),
             // inception_5b/relu_3x3_reduce
             TensorShape(7U, 7U, 192U),
             // inception_5b/relu_5x5_reduce
             TensorShape(7U, 7U, 48U) }),
         framework::dataset::make("Info", ActivationLayerInfo(ActivationLayerInfo::ActivationFunction::RELU))
     }
     {
     }
GoogLeNetInceptionV1ActivationLayerDataset (GoogLeNetInceptionV1ActivationLayerDataset &&) default
~GoogLeNetInceptionV1ActivationLayerDataset () default
Referenced by GoogLeNetInceptionV1ActivationLayerDataset::GoogLeNetInceptionV1ActivationLayerDataset().
The documentation for this class was generated from the following file:
tests/datasets/system_tests/googlenet/inceptionv1/GoogLeNetInceptionV1ActivationLayerDataset.h