Compute Library: PPMAccessor Class Reference
PPMAccessor Class Reference final
PPM accessor class.
#include <GraphUtils.h>
Public Member Functions
PPMAccessor (std::string ppm_path, bool bgr=true, float mean_r=0.0f, float mean_g=0.0f, float mean_b=0.0f, float std_r=1.f, float std_g=1.f, float std_b=1.f)
Constructor.
PPMAccessor (PPMAccessor &&)=default
Allow instances of this class to be move constructed.
bool access_tensor (ITensor &tensor) override
Interface to be implemented to access a given tensor.
Public Member Functions inherited from ITensorAccessor
virtual ~ITensorAccessor ()=default
Default virtual destructor.
Detailed Description
PPM accessor class.
Definition at line 83 of file GraphUtils.h.
Constructor & Destructor Documentation
PPMAccessor (std::string ppm_path, bool bgr = true, float mean_r = 0.0f, float mean_g = 0.0f, float mean_b = 0.0f, float std_r = 1.f, float std_g = 1.f, float std_b = 1.f)
Constructor.
Parameters
[in] ppm_path Path to PPM file
[in] bgr (Optional) Fill the first plane with blue channel (default = false)
[in] mean_r (Optional) Red mean value to be subtracted from red channel
[in] mean_g (Optional) Green mean value to be subtracted from green channel
[in] mean_b (Optional) Blue mean value to be subtracted from blue channel
[in] std_r (Optional) Red standard deviation value to be divided from red channel
[in] std_g (Optional) Green standard deviation value to be divided from green channel
[in] std_b (Optional) Blue standard deviation value to be divided from blue channel
Definition at line 77 of file GraphUtils.cpp.
     : _ppm_path(std::move(ppm_path)), _bgr(bgr), _mean_r(mean_r), _mean_g(mean_g), _mean_b(mean_b), _std_r(std_r), _std_g(std_g), _std_b(std_b)
 {
 }
PPMAccessor (PPMAccessor &&) default
Allow instances of this class to be move constructed.
Member Function Documentation
bool access_tensor (ITensor & tensor) override virtual
Interface to be implemented to access a given tensor.
Parameters
[in] tensor Tensor to be accessed
Returns
True if access is successful else false
Implements ITensorAccessor.
Definition at line 84 of file GraphUtils.cpp.
References ARM_COMPUTE_ERROR_ON_MSG, ITensorInfo::dimension(), arm_compute::execute_window_loop(), PPMLoader::fill_planar_tensor(), PPMLoader::height(), ITensor::info(), PPMLoader::open(), ITensor::ptr_to_element(), ITensorInfo::tensor_shape(), Window::use_tensor_dimensions(), value, and PPMLoader::width().
 {
     utils::PPMLoader ppm;
     const float      mean[3] =
     {
         _bgr ? _mean_b : _mean_r,
         _mean_g,
         _bgr ? _mean_r : _mean_b
     };
     const float std[3] =
     {
         _bgr ? _std_b : _std_r,
         _std_g,
         _bgr ? _std_r : _std_b
     };
     // Open PPM file
     ppm.open(_ppm_path);
     ARM_COMPUTE_ERROR_ON_MSG(ppm.width() != tensor.info()->dimension(0) || ppm.height() != tensor.info()->dimension(1),
                              "Failed to load image file: dimensions [%d,%d] not correct, expected [%d,%d].", ppm.width(), ppm.height(), tensor.info()->dimension(0), tensor.info()->dimension(1));
     // Fill the tensor with the PPM content (BGR)
     ppm.fill_planar_tensor(tensor, _bgr);
     // Subtract the mean value from each channel
     Window window;
     window.use_tensor_dimensions(tensor.info()->tensor_shape());
     execute_window_loop(window, [&](const Coordinates & id)
     {
         const float value                                     = *reinterpret_cast<float *>(tensor.ptr_to_element(id)) - mean[id.z()];
         *reinterpret_cast<float *>(tensor.ptr_to_element(id)) = value / std[id.z()];
     });
     return true;
 }
The documentation for this class was generated from the following files:
utils/GraphUtils.h
utils/GraphUtils.cpp