Compute Library: fixed_point< T > Class Template Reference
fixed_point< T > Class Template Reference
Arbitrary fixed-point arithmetic class.
#include <FixedPoint.h>
Public Member Functions
template<typename U >
fixed_point (fixed_point< U > val, uint8_t p)
Constructor (from different fixed point type)
template<typename U , typename = typename std::enable_if<std::is_integral<U>::value>::type>
fixed_point (U val, uint8_t p, bool is_raw=false)
Constructor (from integer)
fixed_point (float val, uint8_t p)
Constructor (from float)
fixed_point (std::string str, uint8_t p)
Constructor (from float string)
fixed_point & operator= (const fixed_point &)=default
Default copy constructor.
fixed_point & operator= (fixed_point &&)=default
Default move constructor.
fixed_point (const fixed_point &)=default
Default copy assignment operator.
fixed_point (fixed_point &&)=default
Default move assignment operator.
operator float () const
Float conversion operator.
template<typename U , typename = typename std::enable_if<std::is_integral<T>::value>::type>
operator U () const
Integer conversion operator.
template<typename U >
operator fixed_point< U > ()
Convert to different fixed point of different type but same precision.
template<typename U >
fixed_point< T > & operator+= (const fixed_point< U > &rhs)
Arithmetic += assignment operator.
template<typename U >
fixed_point< T > & operator-= (const fixed_point< U > &rhs)
Arithmetic -= assignment operator.
T raw () const
Raw value accessor.
uint8_t precision () const
Precision accessor.
void rescale (uint8_t p)
Rescale a fixed point to a new precision.
Detailed Description
template<typename T>
class arm_compute::test::fixed_point_arithmetic::fixed_point< T >
Arbitrary fixed-point arithmetic class.
Definition at line 87 of file FixedPoint.h.
Constructor & Destructor Documentation
fixed_point (fixed_point< U > val, uint8_t p) inline
Constructor (from different fixed point type)
Parameters
[in] val Fixed point
[in] p Fixed point precision
Definition at line 99 of file FixedPoint.h.
References fixed_point< T >::raw(), fixed_point< T >::rescale(), constant_expr< T >::saturate_cast(), caffe_data_extractor::type, and value.
         : _value(0), _fixed_point_position(p)
     {
         assert(p > 0 && p < std::numeric_limits<T>::digits);
         T v = 0;
         if(std::numeric_limits<T>::digits < std::numeric_limits<U>::digits)
         {
             val.rescale(p);
             v = detail::constant_expr<T>::saturate_cast(val.raw());
         }
         else
         {
             auto v_cast = static_cast<fixed_point<T>>(val);
             v_cast.rescale(p);
             v = v_cast.raw();
         }
         _value = static_cast<T>(v);
     }
fixed_point (U val, uint8_t p, bool is_raw = false) inline
Constructor (from integer)
Parameters
[in] val Integer value to be represented as fixed point
[in] p Fixed point precision
[in] is_raw If true val is a raw fixed point value else an integer
Definition at line 125 of file FixedPoint.h.
         : _value(val << p), _fixed_point_position(p)
     {
         if(is_raw)
         {
             _value = val;
         }
     }
fixed_point (float val, uint8_t p) inline
Constructor (from float)
Parameters
[in] val Float value to be represented as fixed point
[in] p Fixed point precision
Definition at line 138 of file FixedPoint.h.
         : _value(detail::constant_expr<T>::to_fixed(val, p)), _fixed_point_position(p)
     {
         assert(p > 0 && p < std::numeric_limits<T>::digits);
     }
fixed_point (std::string str, uint8_t p) inline
Constructor (from float string)
Parameters
[in] str Float string to be represented as fixed point
[in] p Fixed point precision
Definition at line 148 of file FixedPoint.h.
         : _value(detail::constant_expr<T>::to_fixed(support::cpp11::stof(str), p)), _fixed_point_position(p)
     {
         assert(p > 0 && p < std::numeric_limits<T>::digits);
     }
fixed_point (const fixed_point< T > &) default
Default copy assignment operator.
fixed_point (fixed_point< T > &&) default
Default move assignment operator.
Member Function Documentation
operator fixed_point< U > () inline
Convert to different fixed point of different type but same precision.
Note
Down-conversion might fail.
Definition at line 184 of file FixedPoint.h.
References constant_expr< T >::saturate_cast(), and arm_compute::U.
     {
         U val = static_cast<U>(_value);
         if(std::numeric_limits<U>::digits < std::numeric_limits<T>::digits)
         {
             val = detail::constant_expr<U>::saturate_cast(_value);
         }
         return fixed_point<U>(val, _fixed_point_position, true);
     }
operator float () const inline
Float conversion operator.
Returns
Float representation of fixed point
Definition at line 166 of file FixedPoint.h.
References constant_expr< T >::to_float(), caffe_data_extractor::type, and value.
     {
         return detail::constant_expr<T>::to_float(_value, _fixed_point_position);
     }
operator U () const inline
Integer conversion operator.
Returns
Integer representation of fixed point
Definition at line 175 of file FixedPoint.h.
References constant_expr< T >::to_int(), and arm_compute::U.
     {
         return detail::constant_expr<T>::to_int(_value, _fixed_point_position);
     }
fixed_point<T>& operator+= (const fixed_point< U > & rhs) inline
Arithmetic += assignment operator.
Parameters
[in] rhs Fixed point operand
Returns
Reference to this fixed point
Definition at line 201 of file FixedPoint.h.
References fixed_point< T >::raw().
     {
         fixed_point<T> val(rhs, _fixed_point_position);
         _value += val.raw();
         return *this;
     }
fixed_point<T>& operator-= (const fixed_point< U > & rhs) inline
Arithmetic -= assignment operator.
Parameters
[in] rhs Fixed point operand
Returns
Reference to this fixed point
Definition at line 214 of file FixedPoint.h.
References fixed_point< T >::raw().
     {
         fixed_point<T> val(rhs, _fixed_point_position);
         _value -= val.raw();
         return *this;
     }
fixed_point& operator= (const fixed_point< T > &) default
Default copy constructor.
fixed_point& operator= (fixed_point< T > &&) default
Default move constructor.
uint8_t precision () const inline
Precision accessor.
Returns
Precision of fixed point
Definition at line 233 of file FixedPoint.h.
Referenced by functions::abs(), functions::add(), functions::clamp(), functions::div(), functions::exp(), functions::inv_sqrt(), functions::isequal(), functions::isgreater(), functions::isgreaterequal(), functions::isless(), functions::islessequal(), functions::log(), functions::mul(), functions::negate(), functions::shift_left(), functions::shift_right(), functions::sub(), and functions::tanh().
     {
         return _fixed_point_position;
     }
T raw () const inline
Raw value accessor.
Returns
Raw fixed point value
Definition at line 225 of file FixedPoint.h.
Referenced by functions::abs(), functions::add(), arm_compute::test::validation::reference::batch_normalization_layer(), functions::clamp(), functions::div(), fixed_point< T >::fixed_point(), functions::inv_sqrt(), functions::isequal(), functions::isgreater(), functions::isgreaterequal(), functions::isless(), functions::islessequal(), functions::log(), functions::mul(), functions::negate(), fixed_point< T >::operator+=(), fixed_point< T >::operator-=(), functions::shift_left(), functions::shift_right(), functions::signbit(), and functions::sub().
     {
         return _value;
     }
void rescale (uint8_t p) inline
Rescale a fixed point to a new precision.
Parameters
[in] p New fixed point precision
Definition at line 241 of file FixedPoint.h.
References constant_expr< T >::saturate_cast().
Referenced by functions::add(), fixed_point< T >::fixed_point(), functions::isequal(), functions::isgreater(), functions::isgreaterequal(), functions::isless(), functions::islessequal(), and functions::sub().
     {
         assert(p > 0 && p < std::numeric_limits<T>::digits);
         using promoted_T = typename traits::promote<T>::type;
         promoted_T val   = _value;
         if(p > _fixed_point_position)
         {
             val <<= (p - _fixed_point_position);
         }
         else if(p < _fixed_point_position)
         {
             uint8_t pbar = _fixed_point_position - p;
             val += (pbar != 0) ? (1 << (pbar - 1)) : 0;
             val >>= pbar;
         }
         _value                = detail::constant_expr<T>::saturate_cast(val);
         _fixed_point_position = p;
     }
The documentation for this class was generated from the following file:
tests/validation/FixedPoint.h