Compute Library: GEMMLowpMatrixMultiplyCoreValidationFixture< TensorType, AccessorType, FunctionType > Class Template Reference
GEMMLowpMatrixMultiplyCoreValidationFixture< TensorType, AccessorType, FunctionType > Class Template Reference
#include <GEMMLowpFixture.h>
Public Member Functions
template<typename... >
void setup (TensorShape shape_a, TensorShape shape_b, TensorShape shape_c, int32_t a_offset, int32_t b_offset)
Public Member Functions inherited from Fixture
void setup ()
Setup function.
void teardown ()
Teardown function.
Detailed Description
template<typename TensorType, typename AccessorType, typename FunctionType>
class arm_compute::test::validation::GEMMLowpMatrixMultiplyCoreValidationFixture< TensorType, AccessorType, FunctionType >
Definition at line 46 of file GEMMLowpFixture.h.
Member Function Documentation
void setup (TensorShape shape_a, TensorShape shape_b, TensorShape shape_c, int32_t a_offset, int32_t b_offset) inline
Definition at line 50 of file GEMMLowpFixture.h.
References arm_compute::test::validation::a, arm_compute::test::validation::ARM_COMPUTE_EXPECT(), arm_compute::test::validation::b, arm_compute::test::validation::c, arm_compute::test::framework::ERRORS, arm_compute::test::validation::reference::gemmlowp(), CLTensor::info(), arm_compute::test::library, arm_compute::QASYMM8, arm_compute::S32, ITensorInfo::set_quantization_info(), TensorInfo::set_quantization_info(), arm_compute::test::validation::shape_a, arm_compute::test::validation::shape_b, arm_compute::test::validation::shape_c, and arm_compute::U.
     {
         _target    = compute_target(shape_a, shape_b, shape_c, a_offset, b_offset);
         _reference = compute_reference(shape_a, shape_b, shape_c, a_offset, b_offset);
     }
The documentation for this class was generated from the following file:
tests/validation/fixtures/GEMMLowpFixture.h