Compute Library: HOGDescriptorValidationFixture< TensorType, HOGType, AccessorType, FunctionType, T, U > Class Template Reference
HOGDescriptorValidationFixture< TensorType, HOGType, AccessorType, FunctionType, T, U > Class Template Reference
#include <HOGDescriptorFixture.h>
Public Member Functions
template<typename... >
void setup (std::string image, HOGInfo hog_info, Format format, BorderMode border_mode)
Public Member Functions inherited from Fixture
void setup ()
Setup function.
void teardown ()
Teardown function.
Detailed Description
template<typename TensorType, typename HOGType, typename AccessorType, typename FunctionType, typename T, typename U>
class arm_compute::test::validation::HOGDescriptorValidationFixture< TensorType, HOGType, AccessorType, FunctionType, T, U >
Definition at line 44 of file HOGDescriptorFixture.h.
Member Function Documentation
void setup (std::string image, HOGInfo hog_info, Format format, BorderMode border_mode) inline
Definition at line 48 of file HOGDescriptorFixture.h.
References ARM_COMPUTE_ERROR_ON, arm_compute::test::validation::ARM_COMPUTE_EXPECT(), HOGInfo::block_size(), HOGInfo::block_stride(), arm_compute::test::validation::border_mode, HOGInfo::cell_size(), arm_compute::data_type_from_format(), HOGInfo::detection_window_size(), arm_compute::test::validation::dst, arm_compute::test::framework::ERRORS, arm_compute::F32, arm_compute::test::validation::reference::hog_descriptor(), HOGInfo::l2_hyst_threshold(), arm_compute::test::library, arm_compute::test::fixed_point_arithmetic::detail::max(), HOGInfo::normalization_type(), HOGInfo::num_bins(), HOGInfo::phase_type(), arm_compute::test::validation::shape, arm_compute::test::validation::src, arm_compute::UNDEFINED, arm_compute::V, Dimensions< T >::x(), and Dimensions< T >::y().
     {
         // Only defined borders supported
         ARM_COMPUTE_ERROR_ON(border_mode == BorderMode::UNDEFINED);
         // Generate a random constant value
         std::mt19937                     gen(library->seed());
         std::uniform_int_distribution<T> int_dist(0, 255);
         const T                          constant_border_value = int_dist(gen);
         _target    = compute_target(image, format, border_mode, constant_border_value, hog_info);
         _reference = compute_reference(image, format, border_mode, constant_border_value, hog_info);
     }
The documentation for this class was generated from the following file:
tests/validation/fixtures/HOGDescriptorFixture.h