Compute Library: arm_compute::test::fixed_point_arithmetic::detail Namespace Reference
arm_compute::test::fixed_point_arithmetic::detail Namespace Reference
Data Structures
struct constant_expr
struct functions
Functions
template<typename T >
constexpr int clz (T value)
Count the number of leading zero bits in the given value.
template<typename T >
bool operator== (const fixed_point< T > &lhs, const fixed_point< T > &rhs)
template<typename T >
bool operator!= (const fixed_point< T > &lhs, const fixed_point< T > &rhs)
template<typename T >
bool operator< (const fixed_point< T > &lhs, const fixed_point< T > &rhs)
template<typename T >
bool operator> (const fixed_point< T > &lhs, const fixed_point< T > &rhs)
template<typename T >
bool operator<= (const fixed_point< T > &lhs, const fixed_point< T > &rhs)
template<typename T >
bool operator>= (const fixed_point< T > &lhs, const fixed_point< T > &rhs)
template<typename T >
fixed_point< T > operator+ (const fixed_point< T > &lhs, const fixed_point< T > &rhs)
template<typename T >
fixed_point< T > operator- (const fixed_point< T > &lhs, const fixed_point< T > &rhs)
template<typename T >
fixed_point< T > operator- (const fixed_point< T > &rhs)
template<typename T >
fixed_point< T > operator* (fixed_point< T > x, fixed_point< T > y)
template<typename T >
fixed_point< T > operator/ (fixed_point< T > x, fixed_point< T > y)
template<typename T >
fixed_point< T > operator>> (fixed_point< T > x, size_t shift)
template<typename T >
fixed_point< T > operator<< (fixed_point< T > x, size_t shift)
template<typename T , typename U , typename traits >
std::basic_ostream< T, traits > & operator<< (std::basic_ostream< T, traits > &s, fixed_point< U > x)
template<typename T >
fixed_point< T > min (fixed_point< T > x, fixed_point< T > y)
template<typename T >
fixed_point< T > max (fixed_point< T > x, fixed_point< T > y)
template<OverflowPolicy OP = OverflowPolicy::SATURATE, typename T >
fixed_point< T > add (fixed_point< T > x, fixed_point< T > y)
template<OverflowPolicy OP = OverflowPolicy::SATURATE, typename T >
fixed_point< T > sub (fixed_point< T > x, fixed_point< T > y)
template<OverflowPolicy OP = OverflowPolicy::SATURATE, typename T >
fixed_point< T > mul (fixed_point< T > x, fixed_point< T > y)
template<typename T >
fixed_point< T > div (fixed_point< T > x, fixed_point< T > y)
template<typename T >
fixed_point< T > abs (fixed_point< T > x)
template<typename T >
fixed_point< T > clamp (fixed_point< T > x, T min, T max)
template<typename T >
fixed_point< T > exp (fixed_point< T > x)
template<typename T >
fixed_point< T > log (fixed_point< T > x)
template<typename T >
fixed_point< T > inv_sqrt (fixed_point< T > x)
template<typename T >
fixed_point< T > tanh (fixed_point< T > x)
template<typename T >
fixed_point< T > pow (fixed_point< T > x, fixed_point< T > a)
Function Documentation
fixed_point<T> arm_compute::test::fixed_point_arithmetic::detail::abs (fixed_point< T > x) inline
Definition at line 914 of file FixedPoint.h.
References functions::abs().
Referenced by arm_compute::test::validation::reference::absolute_difference(), arm_compute::test::validation::reference::activation_layer(), arm_compute::calculate_matrix_scale(), combine_gradients_L1(), arm_compute::test::validation::DATA_TEST_CASE(), arm_compute::test::validation::reference::magnitude(), magnitude_l1(), compare< AbsoluteTolerance< U > >::operator bool(), compare< RelativeTolerance< U > >::operator bool(), pow(), arm_compute::test::round_half_even(), arm_compute::separate_matrix(), RangeDataset< T >::size(), and arm_compute::test::validation::validate_wrap().
 {
     return functions::abs(x);
 }
fixed_point<T> arm_compute::test::fixed_point_arithmetic::detail::add (fixed_point< T > x, fixed_point< T > y) inline
Definition at line 894 of file FixedPoint.h.
Referenced by arm_compute::test::validation::reference::activation_layer(), arm_compute::test::validation::DATA_TEST_CASE(), functions::exp(), arm_compute::test::validation::FIXTURE_DATA_TEST_CASE(), functions::log(), arm_compute::test::validation::reference::normalization_layer(), arm_compute::test::validation::reference::pooling_layer(), pow(), ArithmeticAdditionValidationFixedPointFixture< TensorType, AccessorType, FunctionType, T >::setup(), and arm_compute::test::validation::reference::softmax_layer().
 {
     return functions::add<OP>(x, y);
 }
fixed_point<T> arm_compute::test::fixed_point_arithmetic::detail::clamp (fixed_point< T > x, T min, T max) inline
Definition at line 919 of file FixedPoint.h.
References functions::clamp().
Referenced by pow().
 {
     return functions::clamp(x, min, max);
 }
constexpr int arm_compute::test::fixed_point_arithmetic::detail::clz (T value)
Count the number of leading zero bits in the given value.
Parameters
[in] value Input value.
Returns
Number of leading zero bits.
Definition at line 276 of file FixedPoint.h.
References caffe_data_extractor::type.
Referenced by functions::exp(), functions::inv_sqrt(), and softmax_layer_max_quantized().
 {
     using unsigned_T = typename std::make_unsigned<T>::type;
     // __builtin_clz is available for int. Need to correct reported number to
     // match the original type.
     return __builtin_clz(value) - (32 - std::numeric_limits<unsigned_T>::digits);
 }
fixed_point<T> arm_compute::test::fixed_point_arithmetic::detail::div (fixed_point< T > x, fixed_point< T > y) inline
Definition at line 909 of file FixedPoint.h.
References functions::div().
Referenced by arm_compute::test::validation::reference::fixed_point_operation(), functions::log(), arm_compute::test::validation::reference::normalization_layer(), arm_compute::test::validation::reference::pooling_layer(), pow(), and arm_compute::test::validation::reference::softmax_layer().
 {
     return functions::div(x, y);
 }
fixed_point<T> arm_compute::test::fixed_point_arithmetic::detail::exp (fixed_point< T > x) inline
Definition at line 924 of file FixedPoint.h.
References functions::exp().
Referenced by arm_compute::test::validation::reference::activation_layer(), arm_compute::test::validation::DATA_TEST_CASE(), arm_compute::test::validation::reference::fixed_point_operation(), arm_compute::test::validation::reference::normalization_layer(), functions::pow(), pow(), arm_compute::test::validation::reference::softmax_layer(), and functions::tanh().
 {
     return functions::exp(x);
 }
fixed_point<T> arm_compute::test::fixed_point_arithmetic::detail::inv_sqrt (fixed_point< T > x) inline
Definition at line 934 of file FixedPoint.h.
References functions::inv_sqrt().
Referenced by arm_compute::test::validation::reference::activation_layer(), arm_compute::test::validation::reference::batch_normalization_layer(), arm_compute::test::validation::DATA_TEST_CASE(), arm_compute::test::validation::reference::fixed_point_operation(), arm_compute::test::validation::reference::pooling_layer(), and pow().
 {
     return functions::inv_sqrt(x);
 }
fixed_point<T> arm_compute::test::fixed_point_arithmetic::detail::log (fixed_point< T > x) inline
Definition at line 929 of file FixedPoint.h.
References functions::log().
Referenced by arm_compute::test::validation::reference::activation_layer(), arm_compute::test::validation::DATA_TEST_CASE(), arm_compute::test::validation::reference::fixed_point_operation(), functions::log(), arm_compute::test::validation::reference::normalization_layer(), functions::pow(), and pow().
 {
     return functions::log(x);
 }
fixed_point<T> arm_compute::test::fixed_point_arithmetic::detail::max (fixed_point< T > x, fixed_point< T > y) inline
Definition at line 889 of file FixedPoint.h.
Referenced by arm_compute::test::validation::reference::accumulate(), arm_compute::test::validation::reference::accumulate_squared(), arm_compute::test::validation::reference::accumulate_weighted(), arm_compute::test::validation::reference::activation_layer(), arm_compute::test::validation::asymm_int_mult(), asymm_saturating_rounding_mult_by_pow2(), brelu_op(), calculate_avg_scale(), arm_compute::test::validation::calculate_depth_concatenate_shape(), arm_compute::calculate_depth_concatenate_shape(), arm_compute::calculate_matrix_scale(), arm_compute::utility::clamp(), constant_expr< T >::clamp(), functions::clamp(), arm_compute::test::validation::DATA_TEST_CASE(), arm_compute::test::validation::reference::dequantization_layer(), dilate(), functions::div(), functions::exp(), arm_compute::test::validation::fill_lookuptable(), AssetsLibrary::fill_tensor_uniform(), arm_compute::test::validation::reference::fully_connected_layer(), arm_compute::test::validation::reference::gemmlowp_quantize_down_int32_to_uint8_scale(), arm_compute::test::validation::reference::gemmlowp_quantize_down_int32_to_uint8_scale_by_fixedpoint(), arm_compute::test::generate_random_rois(), arm_compute::test::validation::get_activation_layer_test_bounds(), hysteresis(), arm_compute::intersect_valid_regions(), TestFilter::is_selected(), arm_compute::test::validation::reference::l2_normalize(), lu_brelu_op(), minmax(), functions::mul(), non_linear_filter_box3x3(), non_linear_filter_box5x5(), non_linear_filter_cross3x3(), non_linear_filter_cross5x5(), non_linear_filter_disk3x3(), non_linear_filter_disk5x5(), normalization_layer_cross_map(), normalization_layer_in_map(), arm_compute::pixel_area_c1u8_clamp(), arm_compute::pixel_bilinear_c1_clamp(), arm_compute::test::validation::reference::pooling_layer(), pow(), arm_compute::test::validation::reference::quantization_layer(), relu_op(), PaddingCalculator::required_padding(), RGB888_to_IYUV_bt709(), RGB888_to_NV12_bt709(), RGB888_to_YUV444_bt709(), RGBA8888_to_IYUV_bt709(), RGBA8888_to_NV12_bt709(), RGBA8888_to_YUV444_bt709(), row_reduce_max_3(), row_reduce_max_5(), arm_compute::sabs_qs16(), arm_compute::sabs_qs8(), constant_expr< T >::saturate_cast(), arm_compute::test::saturate_cast(), arm_compute::test::validation::reference::scale(), Dimensions< size_t >::set(), HOGDescriptorValidationFixture< TensorType, HOGType, AccessorType, FunctionType, T, U >::setup(), FixedPointValidationFixture< TensorType, AccessorType, T >::setup(), AccumulateBaseValidationFixture< TensorType, AccessorType, FunctionType, T1, T2 >::setup(), TableLookupValidationFixture< TensorType, AccessorType, FunctionType, LutAccessorType, LutType, T >::setup(), DequantizationValidationFixedPointFixture< TensorType, AccessorType, FunctionType, T >::setup(), WinogradLayerValidationFixture< TensorType, AccessorType, FunctionType, T >::setup(), GEMMLowpQuantizeDownInt32ToUint8ScaleValidationFixture< TensorType, AccessorType, FunctionType >::setup(), GEMMLowpQuantizeDownInt32ToUint8ScaleByFixedPointValidationFixture< TensorType, AccessorType, FunctionType >::setup(), arm_compute::test::shape_to_valid_region(), arm_compute::test::shape_to_valid_region_gaussian_pyramid_half(), arm_compute::test::validation::reference::softmax_layer(), softmax_layer_max_quantized(), softmax_layer_shift_exp_sum(), arm_compute::sqcvt_qasymm8_f32(), arm_compute::test::validation::tensor_elem_at(), Window::use_tensor_dimensions(), arm_compute::test::validation::validate_configuration(), arm_compute::test::validation::validate_wrap(), ValidRegion::ValidRegion(), arm_compute::vqrecipq_qs16(), arm_compute::test::validation::reference::warp_affine(), and arm_compute::test::validation::reference::warp_perspective().
 {
     return x > y ? x : y;
 }
fixed_point<T> arm_compute::test::fixed_point_arithmetic::detail::min (fixed_point< T > x, fixed_point< T > y) inline
Definition at line 884 of file FixedPoint.h.
Referenced by arm_compute::test::validation::reference::activation_layer(), functions::add(), arm_compute::test::validation::asymm_int_mult(), asymm_saturating_rounding_mult_by_pow2(), brelu_op(), calculate_avg_scale(), arm_compute::utility::clamp(), constant_expr< T >::clamp(), functions::clamp(), Dimensions< size_t >::collapse(), arm_compute::test::validation::reference::convolution_layer(), arm_compute::test::validation::DATA_TEST_CASE(), arm_compute::test::validation::reference::depthwise_convolution(), arm_compute::test::validation::reference::dequantization_layer(), functions::div(), erode(), arm_compute::test::validation::fill_lookuptable(), arm_compute::test::validation::reference::gemmlowp_quantize_down_int32_to_uint8_scale(), arm_compute::test::validation::reference::gemmlowp_quantize_down_int32_to_uint8_scale_by_fixedpoint(), hysteresis(), arm_compute::intersect_valid_regions(), functions::isequal(), functions::isgreater(), functions::isgreaterequal(), functions::isless(), functions::islessequal(), BorderSize::limit(), lu_brelu_op(), minmax(), functions::mul(), non_linear_filter_box3x3(), non_linear_filter_box5x5(), non_linear_filter_cross3x3(), non_linear_filter_cross5x5(), non_linear_filter_disk3x3(), non_linear_filter_disk5x5(), normalization_layer_cross_map(), normalization_layer_in_map(), arm_compute::pixel_area_c1u8_clamp(), arm_compute::pixel_bilinear_c1_clamp(), arm_compute::test::validation::reference::pooling_layer(), pow(), arm_compute::test::validation::reference::quantization_layer(), RGB888_to_IYUV_bt709(), RGB888_to_NV12_bt709(), RGB888_to_YUV444_bt709(), RGBA8888_to_IYUV_bt709(), RGBA8888_to_NV12_bt709(), RGBA8888_to_YUV444_bt709(), row_reduce_min_3(), row_reduce_min_5(), arm_compute::sabs_qs16(), arm_compute::sabs_qs8(), constant_expr< T >::saturate_cast(), arm_compute::test::validation::reference::scale(), FixedPointValidationFixture< TensorType, AccessorType, T >::setup(), DequantizationValidationFixedPointFixture< TensorType, AccessorType, FunctionType, T >::setup(), WinogradLayerValidationFixture< TensorType, AccessorType, FunctionType, T >::setup(), GEMMLowpQuantizeDownInt32ToUint8ScaleValidationFixture< TensorType, AccessorType, FunctionType >::setup(), GEMMLowpQuantizeDownInt32ToUint8ScaleByFixedPointValidationFixture< TensorType, AccessorType, FunctionType >::setup(), ReshapeLayerDataset::size(), HOGDescriptorDataset::size(), NormalizePlanarYUVLayerDataset::size(), PoolingLayerDataset::size(), ROIPoolingLayerDataset::size(), BatchNormalizationLayerDataset::size(), DepthwiseConvolutionLayerDataset::size(), FullyConnectedLayerDataset::size(), GEMMLowpDataset::size(), ThresholdDataset::size(), ConvolutionLayerDataset::size(), GEMMDataset::size(), ScaleLayerDataset::size(), ZipDataset< T, U >::size(), DepthwiseSeparableConvolutionLayerDataset::size(), arm_compute::sqcvt_qasymm8_f32(), functions::sub(), arm_compute::test::validation::tensor_elem_at(), arm_compute::test::validation::validate(), arm_compute::test::validation::validate_configuration(), arm_compute::test::validation::validate_wrap(), arm_compute::test::validation::reference::warp_affine(), and arm_compute::test::validation::reference::warp_perspective().
 {
     return x > y ? y : x;
 }
fixed_point<T> arm_compute::test::fixed_point_arithmetic::detail::mul (fixed_point< T > x, fixed_point< T > y) inline
Definition at line 904 of file FixedPoint.h.
Referenced by arm_compute::test::validation::reference::activation_layer(), functions::exp(), arm_compute::test::validation::reference::fixed_point_pixel_wise_multiplication(), functions::inv_sqrt(), functions::log(), arm_compute::test::validation::reference::normalization_layer(), arm_compute::test::validation::reference::pooling_layer(), and pow().
 {
     return functions::mul<OP>(x, y);
 }
bool arm_compute::test::fixed_point_arithmetic::detail::operator!= (const fixed_point< T > & lhs, const fixed_point< T > & rhs)
Definition at line 819 of file FixedPoint.h.
References operator==().
 {
     return !operator==(lhs, rhs);
 }
fixed_point<T> arm_compute::test::fixed_point_arithmetic::detail::operator* (fixed_point< T > x, fixed_point< T > y)
Definition at line 859 of file FixedPoint.h.
References functions::mul().
 {
     return functions::mul(x, y);
 }
fixed_point<T> arm_compute::test::fixed_point_arithmetic::detail::operator+ (const fixed_point< T > & lhs, const fixed_point< T > & rhs)
Definition at line 844 of file FixedPoint.h.
References functions::add().
 {
     return functions::add(lhs, rhs);
 }
fixed_point<T> arm_compute::test::fixed_point_arithmetic::detail::operator- (const fixed_point< T > & lhs, const fixed_point< T > & rhs)
Definition at line 849 of file FixedPoint.h.
References functions::sub().
 {
     return functions::sub(lhs, rhs);
 }
fixed_point<T> arm_compute::test::fixed_point_arithmetic::detail::operator- (const fixed_point< T > & rhs)
Definition at line 854 of file FixedPoint.h.
References functions::negate().
 {
     return functions::negate(rhs);
 }
fixed_point<T> arm_compute::test::fixed_point_arithmetic::detail::operator/ (fixed_point< T > x, fixed_point< T > y)
Definition at line 864 of file FixedPoint.h.
References functions::div().
 {
     return functions::div(x, y);
 }
bool arm_compute::test::fixed_point_arithmetic::detail::operator< (const fixed_point< T > & lhs, const fixed_point< T > & rhs)
Definition at line 824 of file FixedPoint.h.
References functions::isless().
Referenced by operator>(), and operator>=().
 {
     return functions::isless(lhs, rhs);
 }
std::basic_ostream<T, traits>& arm_compute::test::fixed_point_arithmetic::detail::operator<< (std::basic_ostream< T, traits > & s, fixed_point< U > x)
Definition at line 879 of file FixedPoint.h.
References functions::write().
 {
     return functions::write(s, x);
 }
fixed_point<T> arm_compute::test::fixed_point_arithmetic::detail::operator<< (fixed_point< T > x, size_t shift)
Definition at line 874 of file FixedPoint.h.
References functions::shift_left().
 {
     return functions::shift_left(x, shift);
 }
bool arm_compute::test::fixed_point_arithmetic::detail::operator<= (const fixed_point< T > & lhs, const fixed_point< T > & rhs)
Definition at line 834 of file FixedPoint.h.
References operator>().
 {
     return !operator>(lhs, rhs);
 }
bool arm_compute::test::fixed_point_arithmetic::detail::operator== (const fixed_point< T > & lhs, const fixed_point< T > & rhs)
Definition at line 814 of file FixedPoint.h.
References functions::isequal().
Referenced by operator!=().
 {
     return functions::isequal(lhs, rhs);
 }
bool arm_compute::test::fixed_point_arithmetic::detail::operator> (const fixed_point< T > & lhs, const fixed_point< T > & rhs)
Definition at line 829 of file FixedPoint.h.
References operator<().
Referenced by operator<=().
 {
     return operator<(rhs, lhs);
 }
bool arm_compute::test::fixed_point_arithmetic::detail::operator>= (const fixed_point< T > & lhs, const fixed_point< T > & rhs)
Definition at line 839 of file FixedPoint.h.
References operator<().
 {
     return !operator<(lhs, rhs);
 }
fixed_point<T> arm_compute::test::fixed_point_arithmetic::detail::operator>> (fixed_point< T > x, size_t shift)
Definition at line 869 of file FixedPoint.h.
References functions::shift_right().
 {
     return functions::shift_right(x, shift);
 }
fixed_point<T> arm_compute::test::fixed_point_arithmetic::detail::pow (fixed_point< T > x, fixed_point< T > a) inline
Definition at line 944 of file FixedPoint.h.
References abs(), add(), clamp(), div(), exp(), inv_sqrt(), log(), max(), min(), mul(), functions::pow(), sub(), and tanh().
Referenced by arm_compute::test::validation::DATA_TEST_CASE(), and arm_compute::test::validation::reference::normalization_layer().
 {
     return functions::pow(x, a);
 }
fixed_point<T> arm_compute::test::fixed_point_arithmetic::detail::sub (fixed_point< T > x, fixed_point< T > y) inline
Definition at line 899 of file FixedPoint.h.
Referenced by arm_compute::test::validation::DATA_TEST_CASE(), functions::exp(), arm_compute::test::validation::FIXTURE_DATA_TEST_CASE(), functions::inv_sqrt(), functions::log(), pow(), and ArithmeticSubtractionValidationFixedPointFixture< TensorType, AccessorType, FunctionType, T1, T2, T3 >::setup().
 {
     return functions::sub<OP>(x, y);
 }
fixed_point<T> arm_compute::test::fixed_point_arithmetic::detail::tanh (fixed_point< T > x) inline
Definition at line 939 of file FixedPoint.h.
References functions::tanh().
Referenced by arm_compute::test::validation::reference::activation_layer(), pow(), functions::tanh(), arm_compute::vpowq_f32(), arm_compute::vqtanh_qs16(), arm_compute::vqtanh_qs8(), arm_compute::vqtanhq_qs16(), arm_compute::vqtanhq_qs8(), and arm_compute::vtanhq_f32().
 {
     return functions::tanh(x);
 }