Compute Library: arm_compute::test::framework::dataset Namespace Reference
arm_compute::test::framework::dataset Namespace Reference
Data Structures
class CartesianProductDataset
Implementation of a dataset representing all combinations of values of the input datasets.
class ContainerDataset
Implementation of a dataset created from a container.
class Dataset
Abstract dataset base class.
class InitializerListDataset
Implementation of a dataset created from an initializer list.
struct is_container
Base case.
struct is_container< std::vector< V, A > >
Vector is considered a container.
class JoinDataset
Implementation of a dataset representing the concatenation of the input datasets.
class NamedDataset
Abstract implementation of a named dataset.
class RangeDataset
Implementation of a dataset created from a range of values.
class SingletonDataset
Implementation of a dataset holding a single value.
class ZipDataset
Implementation of a dataset representing pairs of values of the input datasets.
Functions
template<typename T , typename U >
CartesianProductDataset< T, U > combine (T &&dataset1, U &&dataset2)
Helper function to create a CartesianProductDataset.
template<typename T , typename U >
CartesianProductDataset< T, U > operator* (T &&dataset1, U &&dataset2)
template<typename T >
std::enable_if< is_container< T >::value, ContainerDataset< T > >::type make (std::string name, T &&values)
Helper function to create a ContainerDataset.
template<typename T >
InitializerListDataset< T > make (std::string name, std::initializer_list< T > &&list)
Helper function to create an InitializerListDataset.
template<typename T , typename U >
JoinDataset< T, U > concat (T &&dataset1, U &&dataset2)
Helper function to create a JoinDataset.
template<typename T >
RangeDataset< T > make (std::string name, T start, T end, T step=1)
Helper function to create a RangeDataset.
template<typename T >
std::enable_if< !is_container< T >::value, SingletonDataset< T > >::type make (std::string name, T &&value)
Helper function to create a SingletonDataset.
template<typename T , typename U >
ZipDataset< T, U > zip (T &&dataset1, U &&dataset2)
Helper function to create a ZipDataset.
Function Documentation
CartesianProductDataset<T, U> arm_compute::test::framework::dataset::combine (T && dataset1, U && dataset2)
Helper function to create a CartesianProductDataset.
Parameters
[in] dataset1 First dataset.
[in] dataset2 Second dataset.
Returns
A grid dataset.
Definition at line 157 of file CartesianProductDataset.h.
 {
     return CartesianProductDataset<T, U>(std::forward<T>(dataset1), std::forward<U>(dataset2));
 }
JoinDataset<T, U> arm_compute::test::framework::dataset::concat (T && dataset1, U && dataset2)
Helper function to create a JoinDataset.
Parameters
[in] dataset1 First dataset.
[in] dataset2 Second dataset.
Returns
A join dataset.
Definition at line 142 of file JoinDataset.h.
Referenced by arm_compute::test::validation::DATA_TEST_CASE(), arm_compute::test::validation::FIXTURE_DATA_TEST_CASE(), and arm_compute::test::validation::validate_configuration().
 {
     return JoinDataset<T, U>(std::forward<T>(dataset1), std::forward<U>(dataset2));
 }
InitializerListDataset<T> arm_compute::test::framework::dataset::make (std::string name, std::initializer_list< T > && list)
Helper function to create an InitializerListDataset.
Parameters
[in] name Name of the dataset.
[in] list Initializer list.
Returns
An initializer list dataset.
Definition at line 127 of file InitializerListDataset.h.
 {
     return InitializerListDataset<T>(std::move(name), std::forward<std::initializer_list<T>>(list));
 }
std::enable_if< !is_container<T>::value, SingletonDataset<T > >::type arm_compute::test::framework::dataset::make (std::string name, T && value)
Helper function to create a SingletonDataset.
Parameters
[in] name Name of the dataset.
[in] value Value.
Returns
A singleton dataset.
Definition at line 130 of file SingletonDataset.h.
References value.
 {
     return SingletonDataset<T>(std::move(name), std::forward<T>(value));
 }
RangeDataset<T> arm_compute::test::framework::dataset::make (std::string name, T start, T end, T step = 1)
Helper function to create a RangeDataset.
Parameters
[in] name Name of the dataset.
[in] start Begin of the range.
[in] end End of the range.
[in] step Step size.
Returns
A range dataset.
Definition at line 133 of file RangeDataset.h.
 {
     return RangeDataset<T>(std::move(name), start, end, step);
 }
std::enable_if<is_container<T>::value, ContainerDataset<T> >::type arm_compute::test::framework::dataset::make (std::string name, T && values)
Helper function to create a ContainerDataset.
Parameters
[in] name Name of the dataset.
[in] values Container.
Returns
A container dataset.
Definition at line 140 of file ContainerDataset.h.
Referenced by AlexNetActivationLayerDataset::AlexNetActivationLayerDataset(), AlexNetNormalizationLayerDataset::AlexNetNormalizationLayerDataset(), arm_compute::test::validation::combine(), DATA_TEST_CASE(), arm_compute::test::validation::DATA_TEST_CASE(), arm_compute::test::validation::FIXTURE_DATA_TEST_CASE(), GoogLeNetInceptionV1ActivationLayerDataset::GoogLeNetInceptionV1ActivationLayerDataset(), GoogLeNetInceptionV1NormalizationLayerDataset::GoogLeNetInceptionV1NormalizationLayerDataset(), GoogLeNetInceptionV4ActivationLayerDataset::GoogLeNetInceptionV4ActivationLayerDataset(), LeNet5ActivationLayerDataset::LeNet5ActivationLayerDataset(), MobileNetActivationLayerDataset::MobileNetActivationLayerDataset(), SqueezeNetActivationLayerDataset::SqueezeNetActivationLayerDataset(), arm_compute::test::validation::validate_configuration(), VGG16ActivationLayerDataset::VGG16ActivationLayerDataset(), YOLOV2ActivationLayerLINEARDataset::YOLOV2ActivationLayerLINEARDataset(), and YOLOV2ActivationLayerRELUDataset::YOLOV2ActivationLayerRELUDataset().
 {
     return ContainerDataset<T>(std::move(name), std::forward<T>(values));
 }
CartesianProductDataset<T, U> arm_compute::test::framework::dataset::operator* (T && dataset1, U && dataset2)
Definition at line 164 of file CartesianProductDataset.h.
 {
     return CartesianProductDataset<T, U>(std::forward<T>(dataset1), std::forward<U>(dataset2));
 }
ZipDataset<T, U> arm_compute::test::framework::dataset::zip (T && dataset1, U && dataset2)
Helper function to create a ZipDataset.
Parameters
[in] dataset1 First dataset.
[in] dataset2 Second dataset.
Returns
A zip dataset.
Definition at line 131 of file ZipDataset.h.
Referenced by arm_compute::test::validation::DATA_TEST_CASE().
 {
     return ZipDataset<T, U>(std::forward<T>(dataset1), std::forward<U>(dataset2));
 }