Compute Library: InitializerListDataset< T >::iterator Struct Reference
InitializerListDataset< T >::iterator Struct Reference
Iterator for the dataset.
#include <InitializerListDataset.h>
Public Member Functions
iterator (std::string name, data_const_iterator iterator)
std::string description () const
InitializerListDataset::type operator* () const
iterator & operator++ ()
Detailed Description
template<typename T>
struct arm_compute::test::framework::dataset::InitializerListDataset< T >::iterator
Iterator for the dataset.
Definition at line 68 of file InitializerListDataset.h.
Constructor & Destructor Documentation
iterator (std::string name, data_const_iterator iterator) inline
Definition at line 70 of file InitializerListDataset.h.
Referenced by InitializerListDataset< TensorShape >::begin().
             : _name{ name }, _iterator{ iterator }
         {
         }
Member Function Documentation
std::string description () const inline
Definition at line 75 of file InitializerListDataset.h.
References arm_compute::test::framework::to_string(), and arm_compute::support::cpp11::to_string().
         {
             using support::cpp11::to_string;
             return _name + "=" + to_string(*_iterator);
         }
InitializerListDataset::type operator* () const inline
Definition at line 81 of file InitializerListDataset.h.
         {
             return std::make_tuple(*_iterator);
         }
iterator& operator++ () inline
Definition at line 86 of file InitializerListDataset.h.
         {
             ++_iterator;
             return *this;
         }
The documentation for this struct was generated from the following file:
tests/framework/datasets/InitializerListDataset.h