Compute Library: SingletonDataset< T >::iterator Struct Reference
SingletonDataset< T >::iterator Struct Reference
Iterator for the dataset.
#include <SingletonDataset.h>
Public Member Functions
iterator (std::string name, const T *value)
~iterator ()=default
iterator (const iterator &)=default
iterator & operator= (const iterator &)=default
iterator (iterator &&)=default
iterator & operator= (iterator &&)=default
std::string description () const
SingletonDataset::type operator* () const
iterator & operator++ ()
Detailed Description
template<typename T>
struct arm_compute::test::framework::dataset::SingletonDataset< T >::iterator
Iterator for the dataset.
Definition at line 65 of file SingletonDataset.h.
Constructor & Destructor Documentation
iterator (std::string name, const T * value) inline
Definition at line 67 of file SingletonDataset.h.
References SingletonDataset< T >::iterator::operator=(), value, and SingletonDataset< T >::iterator::~iterator().
Referenced by SingletonDataset< ActivationLayerInfo >::begin().
             : _name{ name }, _value{ value }
         {
         }
~iterator () default
Referenced by SingletonDataset< T >::iterator::iterator().
iterator (const iterator &) default
iterator (iterator &&) default
Member Function Documentation
std::string description () const inline
Definition at line 79 of file SingletonDataset.h.
References arm_compute::test::framework::to_string(), and arm_compute::support::cpp11::to_string().
         {
             using support::cpp11::to_string;
             return _name + "=" + to_string(*_value);
         }
SingletonDataset::type operator* () const inline
Definition at line 85 of file SingletonDataset.h.
         {
             return std::make_tuple(*_value);
         }
iterator& operator++ () inline
Definition at line 90 of file SingletonDataset.h.
         {
             return *this;
         }
iterator& operator= (const iterator &) default
Referenced by SingletonDataset< T >::iterator::iterator().
iterator& operator= (iterator &&) default
The documentation for this struct was generated from the following file:
tests/framework/datasets/SingletonDataset.h