Compute Library: tests/validation/UNIT/Utils.cpp File Reference
Utils.cpp File Reference
#include "tests/Utils.h"
#include "tests/framework/Asserts.h"
#include "tests/framework/Macros.h"
#include "tests/framework/datasets/Datasets.h"
#include "tests/validation/Validation.h"
#include "utils/TypePrinter.h"
#include <stdexcept>
Functions
DATA_TEST_CASE (RoundHalfUp, framework::DatasetMode::ALL, zip(framework::dataset::make("FloatIn",{1.f, 1.2f, 1.5f, 2.5f, 2.9f,-3.f,-3.5f,-3.8f,-4.3f,-4.5f}), framework::dataset::make("FloatOut",{1.f, 1.f, 2.f, 3.f, 3.f,-3.f,-3.f,-4.f,-4.f,-4.f})), value, result)
DATA_TEST_CASE (RoundHalfEven, framework::DatasetMode::ALL, zip(framework::dataset::make("FloatIn",{1.f, 1.2f, 1.5f, 2.5f, 2.9f,-3.f,-3.5f,-3.8f,-4.3f,-4.5f}), framework::dataset::make("FloatOut",{1.f, 1.f, 2.f, 2.f, 3.f,-3.f,-4.f,-4.f,-4.f,-4.f})), value, result)
DATA_TEST_CASE (Index2Coord, framework::DatasetMode::ALL, zip(zip(framework::dataset::make("Shape",{TensorShape{1U}, TensorShape{2U}, TensorShape{2U, 3U}}), framework::dataset::make("Index",{0, 1, 2})), framework::dataset::make("Coordinates",{Coordinates{0}, Coordinates{1}, Coordinates{0, 1}})), shape, index, ref_coordinate)
DATA_TEST_CASE (RoundFloatToZero, framework::DatasetMode::ALL, zip(framework::dataset::make("FloatIn",{1.f, 1.2f, 1.5f, 2.5f, 2.9f,-3.f,-3.5f,-3.8f,-4.3f,-4.5f}), framework::dataset::make("FloatOut",{1.f, 1.f, 1.f, 2.f, 2.f,-3.f,-3.f,-3.f,-4.f,-4.f})), value, result)
DATA_TEST_CASE (RoundFloatToNearestUp, framework::DatasetMode::ALL, zip(framework::dataset::make("FloatIn",{1.f, 1.2f, 1.5f, 2.5f, 2.9f,-3.f,-3.5f,-3.8f,-4.3f,-4.5f}), framework::dataset::make("FloatOut",{1.f, 1.f, 2.f, 3.f, 3.f,-3.f,-4.f,-4.f,-4.f,-5.f})), value, result)
DATA_TEST_CASE (Coord2Index, framework::DatasetMode::ALL, zip(zip(framework::dataset::make("Shape",{TensorShape{1U}, TensorShape{2U}, TensorShape{2U, 3U}}), framework::dataset::make("Coordinates",{Coordinates{0}, Coordinates{1}, Coordinates{0, 1}})), framework::dataset::make("Index",{0, 1, 2})), shape, coordinate, ref_index)
Function Documentation
DATA_TEST_CASE (RoundHalfUp , framework::DatasetMode::ALL , zip(framework::dataset::make("FloatIn",{1.f, 1.2f, 1.5f, 2.5f, 2.9f,-3.f,-3.5f,-3.8f,-4.3f,-4.5f}),framework::dataset::make("FloatOut",{1.f, 1.f, 2.f, 3.f, 3.f,-3.f,-3.f,-4.f,-4.f,-4.f})) , value , result)
Definition at line 40 of file Utils.cpp.
References arm_compute::test::validation::ARM_COMPUTE_EXPECT(), arm_compute::test::framework::ERRORS, arm_compute::test::framework::dataset::make(), arm_compute::test::round_half_up(), and value.
                                                                                          { 1.f, 1.2f, 1.5f, 2.5f, 2.9f, -3.f, -3.5f, -3.8f, -4.3f, -4.5f }),
                                                              framework::dataset::make("FloatOut", { 1.f, 1.f, 2.f, 3.f, 3.f, -3.f, -3.f, -4.f, -4.f, -4.f })),
                value, result)
 {
     ARM_COMPUTE_EXPECT(round_half_up(value) == result, framework::LogLevel::ERRORS);
 }
DATA_TEST_CASE (RoundHalfEven , framework::DatasetMode::ALL , zip(framework::dataset::make("FloatIn",{1.f, 1.2f, 1.5f, 2.5f, 2.9f,-3.f,-3.5f,-3.8f,-4.3f,-4.5f}),framework::dataset::make("FloatOut",{1.f, 1.f, 2.f, 2.f, 3.f,-3.f,-4.f,-4.f,-4.f,-4.f})) , value , result)
Definition at line 47 of file Utils.cpp.
References arm_compute::test::validation::ARM_COMPUTE_EXPECT(), arm_compute::test::framework::ERRORS, arm_compute::test::framework::dataset::make(), arm_compute::test::round_half_even(), and value.
                                                                                            { 1.f, 1.2f, 1.5f, 2.5f, 2.9f, -3.f, -3.5f, -3.8f, -4.3f, -4.5f }),
                                                                framework::dataset::make("FloatOut", { 1.f, 1.f, 2.f, 2.f, 3.f, -3.f, -4.f, -4.f, -4.f, -4.f })),
                value, result)
 {
     ARM_COMPUTE_EXPECT(round_half_even(value) == result, framework::LogLevel::ERRORS);
 }
DATA_TEST_CASE (Index2Coord , framework::DatasetMode::ALL , zip(zip(framework::dataset::make("Shape",{TensorShape{1U}, TensorShape{2U}, TensorShape{2U, 3U}}), framework::dataset::make("Index",{0, 1, 2})),framework::dataset::make("Coordinates",{Coordinates{0}, Coordinates{1}, Coordinates{0, 1}})) , shape , index , ref_coordinate)
Definition at line 54 of file Utils.cpp.
References arm_compute::test::validation::ARM_COMPUTE_EXPECT(), arm_compute::test::validation::compare_dimensions(), arm_compute::test::framework::ERRORS, arm_compute::test::index2coord(), arm_compute::test::framework::dataset::make(), arm_compute::test::validation::shape, and arm_compute::U.
                                                                                            { TensorShape{ 1U }, TensorShape{ 2U }, TensorShape{ 2U, 3U } }), framework::dataset::make("Index", { 0, 1, 2 })),
                                                              framework::dataset::make("Coordinates", { Coordinates{ 0 }, Coordinates{ 1 }, Coordinates{ 0, 1 } })),
                shape, index, ref_coordinate)
 {
     Coordinates coordinate = index2coord(shape, index);
     ARM_COMPUTE_EXPECT(compare_dimensions(coordinate, ref_coordinate), framework::LogLevel::ERRORS);
 }
DATA_TEST_CASE (RoundFloatToZero , framework::DatasetMode::ALL , zip(framework::dataset::make("FloatIn",{1.f, 1.2f, 1.5f, 2.5f, 2.9f,-3.f,-3.5f,-3.8f,-4.3f,-4.5f}),framework::dataset::make("FloatOut",{1.f, 1.f, 1.f, 2.f, 2.f,-3.f,-3.f,-3.f,-4.f,-4.f})) , value , result)
Definition at line 63 of file Utils.cpp.
References arm_compute::test::validation::ARM_COMPUTE_EXPECT(), arm_compute::test::framework::ERRORS, arm_compute::test::framework::dataset::make(), arm_compute::round(), arm_compute::TO_ZERO, and value.
                                                                                               { 1.f, 1.2f, 1.5f, 2.5f, 2.9f, -3.f, -3.5f, -3.8f, -4.3f, -4.5f }),
                                                                   framework::dataset::make("FloatOut", { 1.f, 1.f, 1.f, 2.f, 2.f, -3.f, -3.f, -3.f, -4.f, -4.f })),
                value, result)
 {
     ARM_COMPUTE_EXPECT(round(value, RoundingPolicy::TO_ZERO) == result, framework::LogLevel::ERRORS);
 }
DATA_TEST_CASE (RoundFloatToNearestUp , framework::DatasetMode::ALL , zip(framework::dataset::make("FloatIn",{1.f, 1.2f, 1.5f, 2.5f, 2.9f,-3.f,-3.5f,-3.8f,-4.3f,-4.5f}),framework::dataset::make("FloatOut",{1.f, 1.f, 2.f, 3.f, 3.f,-3.f,-4.f,-4.f,-4.f,-5.f})) , value , result)
Definition at line 70 of file Utils.cpp.
References arm_compute::test::validation::ARM_COMPUTE_EXPECT(), arm_compute::test::framework::ERRORS, arm_compute::test::framework::dataset::make(), arm_compute::round(), arm_compute::TO_NEAREST_UP, and value.
                                                                                                    { 1.f, 1.2f, 1.5f, 2.5f, 2.9f, -3.f, -3.5f, -3.8f, -4.3f, -4.5f }),
                                                                        framework::dataset::make("FloatOut", { 1.f, 1.f, 2.f, 3.f, 3.f, -3.f, -4.f, -4.f, -4.f, -5.f })),
                value, result)
 {
     ARM_COMPUTE_EXPECT(round(value, RoundingPolicy::TO_NEAREST_UP) == result, framework::LogLevel::ERRORS);
 }
DATA_TEST_CASE (Coord2Index , framework::DatasetMode::ALL , zip(zip(framework::dataset::make("Shape",{TensorShape{1U}, TensorShape{2U}, TensorShape{2U, 3U}}),framework::dataset::make("Coordinates",{Coordinates{0}, Coordinates{1}, Coordinates{0, 1}})),framework::dataset::make("Index",{0, 1, 2})) , shape , coordinate , ref_index)
Definition at line 77 of file Utils.cpp.
References arm_compute::test::validation::ARM_COMPUTE_EXPECT(), arm_compute::test::coord2index(), arm_compute::test::framework::ERRORS, arm_compute::test::framework::dataset::make(), arm_compute::test::validation::shape, arm_compute::test::validation::TEST_SUITE_END(), and arm_compute::U.
                                                                                            { TensorShape{ 1U }, TensorShape{ 2U }, TensorShape{ 2U, 3U } }),
                                                                  framework::dataset::make("Coordinates", { Coordinates{ 0 }, Coordinates{ 1 }, Coordinates{ 0, 1 } })),
                                                              framework::dataset::make("Index", { 0, 1, 2 })),
                shape, coordinate, ref_index)
 {
     int index = coord2index(shape, coordinate);
     ARM_COMPUTE_EXPECT(index == ref_index, framework::LogLevel::ERRORS);
 }