Compute Library: CLSplit Class Reference
CLSplit Class Reference
Basic function to split a tensor along a given axis.
#include <CLSplit.h>
Public Member Functions
CLSplit ()
Default constructor.
void configure (const ICLTensor *input, const std::vector< ICLTensor * > &outputs, unsigned int axis)
Initialise the kernel's input and outputs.
void run () override
Run the kernels contained in the function.
Public Member Functions inherited from IFunction
virtual ~IFunction ()=default
Destructor.
virtual void prepare ()
Prepare the function for executing.
Static Public Member Functions
static Status validate (const ITensorInfo *input, const std::vector< ITensorInfo * > &outputs, unsigned int axis)
Static function to check if given info will lead to a valid configuration of CLSplit.
Detailed Description
Basic function to split a tensor along a given axis.
Definition at line 41 of file CLSplit.h.
Constructor & Destructor Documentation
CLSplit()
CLSplit ()
Default constructor.
Definition at line 37 of file CLSplit.cpp.
     : _outputs_vector(), _slice_functions(), _num_outputs(0)
 {
 }
Member Function Documentation
configure()
void configure (const ICLTensor * input, const std::vector< ICLTensor * > & outputs, unsigned int axis)
Initialise the kernel's input and outputs.
Parameters
[in] input The input tensor. Data types supported: U8/S8/QASYMM8/U16/S16/U32/S32/F16/F32.
[out] outputs A vector containing the output tensors. Data types supported: Same as input. The output tensors should match the input tensor dimensions for all shape dimensions apart from the split dimension.
[in] axis Axis on which to split the input.
Definition at line 42 of file CLSplit.cpp.
 {
     // Create Slice functions
     _num_outputs = outputs.size();
     _slice_functions.resize(_num_outputs);
     // Get output shape
     const TensorShape output_shape = arm_compute::misc::shape_calculator::compute_split_shape(input->info(), axis, _num_outputs);
     // Extract output tensor info
     std::vector<ITensorInfo *> outputs_info;
     for(auto &output : outputs)
     {
         ARM_COMPUTE_ERROR_ON_NULLPTR(output);
         outputs_info.emplace_back(output->info());
     }
     // Validate
     ARM_COMPUTE_ERROR_THROW_ON(CLSplit::validate(input->info(), outputs_info, axis));
     const size_t axis_split_step = output_shape[axis];
     unsigned int axis_offset     = 0;
     // Start/End coordinates
     Coordinates start_coords;
     Coordinates end_coords;
     for(unsigned int d = 0; d < output_shape.num_dimensions(); ++d)
     {
         end_coords.set(d, -1);
     }
     for(unsigned int i = 0; i < _num_outputs; i++)
     {
         // Update coordinate on axis
         start_coords.set(axis, axis_offset);
         end_coords.set(axis, axis_offset + axis_split_step);
         // Configure slice function
         _slice_functions[i].configure(input, outputs[i], start_coords, end_coords);
         // Set valid region from shape
         outputs[i]->info()->set_valid_region(ValidRegion(Coordinates(), output_shape));
         // Update axis offset
         axis_offset += axis_split_step;
     }
 }
References ARM_COMPUTE_ERROR_ON_NULLPTR, ARM_COMPUTE_ERROR_THROW_ON, arm_compute::test::validation::axis, arm_compute::misc::shape_calculator::compute_split_shape(), ITensor::info(), arm_compute::test::validation::output_shape, Dimensions< T >::set(), and CLSplit::validate().
run()
void run () override virtual
Run the kernels contained in the function.
For NEON kernels:
Multi-threading is used for the kernels which are parallelisable.
By default std::thread::hardware_concurrency() threads are used.
Note
CPPScheduler::set_num_threads() can be used to manually set the number of threads
For OpenCL kernels:
All the kernels are enqueued on the queue associated with CLScheduler.
The queue is then flushed.
Note
The function will not block until the kernels are executed. It is the user's responsibility to wait.
Will call prepare() on first run if hasn't been done
Implements IFunction.
Definition at line 131 of file CLSplit.cpp.
 {
     cl::CommandQueue q = CLScheduler::get().queue();
     for(unsigned i = 0; i < _num_outputs; ++i)
     {
         _slice_functions[i].run();
     }
 }
References CLScheduler::get(), and CLScheduler::queue().
validate()
Status validate (const ITensorInfo * input, const std::vector< ITensorInfo * > & outputs, unsigned int axis) static
Static function to check if given info will lead to a valid configuration of CLSplit.
Parameters
[in] input The input tensor info. Data types supported: U8/S8/QASYMM8/U16/S16/U32/S32/F16/F32.
[in] outputs A vector containing the output tensors' info. Data types supported: Same as input. The output tensors should match the input tensor dimensions for all shape dimensions apart from the split dimension
[in] axis Axis on which to split the input.
Returns
a status
Definition at line 90 of file CLSplit.cpp.
 {
     ARM_COMPUTE_RETURN_ERROR_ON_NULLPTR(input);
     ARM_COMPUTE_RETURN_ERROR_ON(axis >= input->num_dimensions());
     ARM_COMPUTE_RETURN_ERROR_ON(outputs.size() < 2);
     // Get output shape
     const TensorShape output_shape = arm_compute::misc::shape_calculator::compute_split_shape(input, axis, outputs.size());
     ARM_COMPUTE_RETURN_ERROR_ON(output_shape.total_size() == 0);
     const size_t axis_split_step = output_shape[axis];
     unsigned int axis_offset     = 0;
     // Start/End coordinates
     Coordinates start_coords;
     Coordinates end_coords;
     for(unsigned int d = 0; d < output_shape.num_dimensions(); ++d)
     {
         end_coords.set(d, -1);
     }
     // Validate output tensors
     for(const auto &output : outputs)
     {
         ARM_COMPUTE_RETURN_ERROR_ON_NULLPTR(output);
         // Output auto inizialitation if not yet initialized
         TensorInfo tmp_output_info = *output->clone();
         auto_init_if_empty(tmp_output_info, input->clone()->set_is_resizable(true).set_tensor_shape(output_shape));
         // Update coordinate on axis
         start_coords.set(axis, axis_offset);
         end_coords.set(axis, axis_offset + axis_split_step);
         ARM_COMPUTE_RETURN_ON_ERROR(CLSlice::validate(input, output, start_coords, end_coords));
         axis_offset += axis_split_step;
     }
     return Status{};
 }
References ARM_COMPUTE_RETURN_ERROR_ON, ARM_COMPUTE_RETURN_ERROR_ON_NULLPTR, ARM_COMPUTE_RETURN_ON_ERROR, arm_compute::auto_init_if_empty(), arm_compute::test::validation::axis, ICloneable< T >::clone(), TensorInfo::clone(), arm_compute::misc::shape_calculator::compute_split_shape(), ITensorInfo::num_dimensions(), arm_compute::test::validation::output_shape, Dimensions< T >::set(), and CLSlice::validate().
Referenced by CLSplit::configure().
The documentation for this class was generated from the following files:
arm_compute/runtime/CL/functions/CLSplit.h
src/runtime/CL/functions/CLSplit.cpp