Compute Library: CLPoolingLayerKernel Class Reference
CLPoolingLayerKernel Class Reference
Interface for the pooling layer kernel.
#include <CLPoolingLayerKernel.h>
Public Member Functions
CLPoolingLayerKernel ()
Default constructor.
CLPoolingLayerKernel (const CLPoolingLayerKernel &)=delete
Prevent instances of this class from being copied (As this class contains pointers)
CLPoolingLayerKernel & operator= (const CLPoolingLayerKernel &)=delete
Prevent instances of this class from being copied (As this class contains pointers)
CLPoolingLayerKernel (CLPoolingLayerKernel &&)=default
Allow instances of this class to be moved.
CLPoolingLayerKernel & operator= (CLPoolingLayerKernel &&)=default
Allow instances of this class to be moved.
~CLPoolingLayerKernel ()=default
Default destructor.
void configure (const ICLTensor *input, ICLTensor *output, const PoolingLayerInfo &pool_info)
Set the input and output tensors.
void run (const Window &window, cl::CommandQueue &queue) override
Enqueue the OpenCL kernel to process the given window on the passed OpenCL command queue.
BorderSize border_size () const override
The size of the border for that kernel.
Public Member Functions inherited from ICLKernel
ICLKernel ()
Constructor.
cl::Kernel & kernel ()
Returns a reference to the OpenCL kernel of this object.
template<typename T >
void add_1D_array_argument (unsigned int &idx, const ICLArray< T > *array, const Strides &strides, unsigned int num_dimensions, const Window &window)
Add the passed 1D array's parameters to the object's kernel's arguments starting from the index idx.
void add_1D_tensor_argument (unsigned int &idx, const ICLTensor *tensor, const Window &window)
Add the passed 1D tensor's parameters to the object's kernel's arguments starting from the index idx.
void add_1D_tensor_argument_if (bool cond, unsigned int &idx, const ICLTensor *tensor, const Window &window)
Add the passed 1D tensor's parameters to the object's kernel's arguments starting from the index idx if the condition is true.
void add_2D_tensor_argument (unsigned int &idx, const ICLTensor *tensor, const Window &window)
Add the passed 2D tensor's parameters to the object's kernel's arguments starting from the index idx.
void add_2D_tensor_argument_if (bool cond, unsigned int &idx, const ICLTensor *tensor, const Window &window)
Add the passed 2D tensor's parameters to the object's kernel's arguments starting from the index idx if the condition is true.
void add_3D_tensor_argument (unsigned int &idx, const ICLTensor *tensor, const Window &window)
Add the passed 3D tensor's parameters to the object's kernel's arguments starting from the index idx.
void add_4D_tensor_argument (unsigned int &idx, const ICLTensor *tensor, const Window &window)
Add the passed 4D tensor's parameters to the object's kernel's arguments starting from the index idx.
template<typename T >
void add_argument (unsigned int &idx, T value)
Add the passed parameters to the object's kernel's arguments starting from the index idx.
void set_lws_hint (const cl::NDRange &lws_hint)
Set the Local-Workgroup-Size hint.
cl::NDRange lws_hint () const
Return the Local-Workgroup-Size hint.
const std::string & config_id () const
Get the configuration ID.
void set_target (GPUTarget target)
Set the targeted GPU architecture.
void set_target (cl::Device &device)
Set the targeted GPU architecture according to the CL device.
GPUTarget get_target () const
Get the targeted GPU architecture.
size_t get_max_workgroup_size ()
Get the maximum workgroup size for the device the CLKernelLibrary uses.
template<typename T , unsigned int dimension_size>
void add_array_argument (unsigned &idx, const ICLArray< T > *array, const Strides &strides, unsigned int num_dimensions, const Window &window)
Add the passed array's parameters to the object's kernel's arguments starting from the index idx.
template<unsigned int dimension_size>
void add_tensor_argument (unsigned &idx, const ICLTensor *tensor, const Window &window)
Public Member Functions inherited from IKernel
IKernel ()
Constructor.
virtual ~IKernel ()=default
Destructor.
virtual bool is_parallelisable () const
Indicates whether or not the kernel is parallelisable.
const Window & window () const
The maximum window the kernel can be executed on.
Static Public Member Functions
static Status validate (const ITensorInfo *input, const ITensorInfo *output, const PoolingLayerInfo &pool_info)
Static function to check if given info will lead to a valid configuration of CLPoolingLayerKernel.
Static Public Member Functions inherited from ICLKernel
static constexpr unsigned int num_arguments_per_1D_array ()
Returns the number of arguments enqueued per 1D array object.
static constexpr unsigned int num_arguments_per_1D_tensor ()
Returns the number of arguments enqueued per 1D tensor object.
static constexpr unsigned int num_arguments_per_2D_tensor ()
Returns the number of arguments enqueued per 2D tensor object.
static constexpr unsigned int num_arguments_per_3D_tensor ()
Returns the number of arguments enqueued per 3D tensor object.
static constexpr unsigned int num_arguments_per_4D_tensor ()
Returns the number of arguments enqueued per 4D tensor object.
static cl::NDRange gws_from_window (const Window &window)
Get the global work size given an execution window.
Data Fields
const ICLTensor * _input
ICLTensor * _output
PoolingLayerInfo _pool_info
DataLayout _data_layout
BorderSize _border_size
unsigned int _num_elems_processed_per_iteration
Detailed Description
Interface for the pooling layer kernel.
Definition at line 36 of file CLPoolingLayerKernel.h.
Constructor & Destructor Documentation
CLPoolingLayerKernel() [1/3]
CLPoolingLayerKernel ()
Default constructor.
Definition at line 174 of file CLPoolingLayerKernel.cpp.
     : _input(nullptr), _output(nullptr), _pool_info(), _data_layout(DataLayout::UNKNOWN), _border_size(0), _num_elems_processed_per_iteration(1)
 {
 }
References arm_compute::UNKNOWN.
CLPoolingLayerKernel() [2/3]
CLPoolingLayerKernel (const CLPoolingLayerKernel &) delete
Prevent instances of this class from being copied (As this class contains pointers)
CLPoolingLayerKernel() [3/3]
CLPoolingLayerKernel (CLPoolingLayerKernel &&) default
Allow instances of this class to be moved.
~CLPoolingLayerKernel()
~CLPoolingLayerKernel () default
Default destructor.
Member Function Documentation
border_size()
BorderSize border_size () const override virtual
The size of the border for that kernel.
Returns
The width in number of elements of the border.
Reimplemented from IKernel.
Definition at line 179 of file CLPoolingLayerKernel.cpp.
 {
     return _border_size;
 }
References CLPoolingLayerKernel::_border_size.
configure()
void configure (const ICLTensor * input, ICLTensor * output, const PoolingLayerInfo & pool_info)
Set the input and output tensors.
Parameters
[in] input Source tensor. Data types supported: QASYMM8/F16/F32.
[out] output Destination tensor. Data types supported: Same as input.
[in] pool_info Contains pooling operation information described in PoolingLayerInfo.
Definition at line 184 of file CLPoolingLayerKernel.cpp.
 {
     ARM_COMPUTE_ERROR_ON_NULLPTR(input, output);
     // Set instance variables
     _input       = input;
     _output      = output;
     _pool_info   = pool_info;
     _data_layout = input->info()->data_layout();
     int                 pool_stride_x   = 0;
     int                 pool_stride_y   = 0;
     const PoolingType   pool_type       = pool_info.pool_type();
     const int           idx_width       = get_data_layout_dimension_index(_data_layout, DataLayoutDimension::WIDTH);
     const int           idx_height      = get_data_layout_dimension_index(_data_layout, DataLayoutDimension::HEIGHT);
     const int           idx_channel     = get_data_layout_dimension_index(_data_layout, DataLayoutDimension::CHANNEL);
     const int           pool_size_x     = pool_info.is_global_pooling() ? input->info()->dimension(idx_width) : pool_info.pool_size().width;
     const int           pool_size_y     = pool_info.is_global_pooling() ? input->info()->dimension(idx_height) : pool_info.pool_size().height;
     const PadStrideInfo pad_stride_info = pool_info.pad_stride_info();
     const bool          exclude_padding = pool_info.exclude_padding();
     std::tie(pool_stride_x, pool_stride_y) = pad_stride_info.stride();
     const int pool_pad_top  = pad_stride_info.pad_top();
     const int pool_pad_left = pad_stride_info.pad_left();
     // Set build options
     CLBuildOptions build_opts;
     if(is_data_type_quantized_asymmetric(input->info()->data_type()) && input->info()->quantization_info() != output->info()->quantization_info())
     {
         const UniformQuantizationInfo iq_info = input->info()->quantization_info().uniform();
         const UniformQuantizationInfo oq_info = output->info()->quantization_info().uniform();
         build_opts.add_option("-DOFFSET_IN1=" + float_to_string_with_full_precision(iq_info.offset));
         build_opts.add_option("-DOFFSET_OUT=" + float_to_string_with_full_precision(oq_info.offset));
         build_opts.add_option("-DSCALE_IN1=" + float_to_string_with_full_precision(iq_info.scale));
         build_opts.add_option("-DSCALE_OUT=" + float_to_string_with_full_precision(oq_info.scale));
     }
     // Check output dimensions
     auto_init(input->info(), output->info(), pool_info);
     ARM_COMPUTE_ERROR_THROW_ON(validate_arguments(input->info(), output->info(), pool_info));
     const DataType data_type = input->info()->data_type();
     build_opts.add_option("-DDATA_TYPE=" + get_cl_type_from_data_type(data_type));
     build_opts.add_option("-DPOOL_" + string_from_pooling_type(pool_type));
     build_opts.add_option("-DSTRIDE_X=" + support::cpp11::to_string(pool_stride_x));
     build_opts.add_option("-DSTRIDE_Y=" + support::cpp11::to_string(pool_stride_y));
     build_opts.add_option("-DPAD_X=" + support::cpp11::to_string(pool_pad_left));
     build_opts.add_option("-DPAD_Y=" + support::cpp11::to_string(pool_pad_top));
     build_opts.add_option("-DPOOL_SIZE_X=" + support::cpp11::to_string(pool_size_x));
     build_opts.add_option("-DPOOL_SIZE_Y=" + support::cpp11::to_string(pool_size_y));
     build_opts.add_option_if(data_type == DataType::F16, "-DFP16");
     // Create kernel
     switch(_data_layout)
     {
         case DataLayout::NCHW:
         {
             build_opts.add_option("-DMAX_WIDTH=" + support::cpp11::to_string(input->info()->dimension(idx_width) + (exclude_padding ? 0 : pool_pad_left)));
             build_opts.add_option("-DMAX_HEIGHT=" + support::cpp11::to_string(input->info()->dimension(idx_height) + (exclude_padding ? 0 : pool_pad_top)));
             if(pool_type != PoolingType::MAX)
             {
                 build_opts.add_option_if(exclude_padding, "-DEXCLUDE_PADDING");
             }
             if((pool_size_x == 3) && (pool_size_y == 3) && !is_data_type_quantized_asymmetric(data_type))
             {
                 // Check if we have pool3x3 with stride_x less equal than 3. In these cases, run an optimized OpenCL kernel where
                 // each thread computes 4 output elements
                 const bool is_pool3x3_stride_le3 = (pool_size_x == 3) && (pool_size_y == 3) && (pool_stride_x <= 3);
                 std::string kernel_name = ((is_pool3x3_stride_le3) ? "pooling_layer_optimized_" : "pooling_layer_")
                                           + support::cpp11::to_string(pool_size_x);
                 _kernel = static_cast<cl::Kernel>(CLKernelLibrary::get().create_kernel(kernel_name, build_opts.options()));
             }
             else // Run general case
             {
                 std::string kernel_name = is_data_type_quantized_asymmetric(data_type) ? "pooling_layer_MxN_quantized_nchw" : "pooling_layer_MxN_nchw";
                 _kernel                 = static_cast<cl::Kernel>(CLKernelLibrary::get().create_kernel(kernel_name, build_opts.options()));
             }
             break;
         }
         case DataLayout::NHWC:
         {
             build_opts.add_option_if(exclude_padding, "-DEXCLUDE_PADDING");
             build_opts.add_option("-DMAX_WIDTH=" + support::cpp11::to_string(input->info()->dimension(idx_width)));
             build_opts.add_option("-DMAX_HEIGHT=" + support::cpp11::to_string(input->info()->dimension(idx_height)));
             build_opts.add_option_if(output->info()->tensor_shape().total_size_upper(3) > 1,
                                      "-DDST_DEPTH=" + support::cpp11::to_string(output->info()->dimension(idx_height)));
             std::string kernel_name = is_data_type_quantized_asymmetric(data_type) ? "pooling_layer_MxN_quantized_nhwc" : "pooling_layer_MxN_nhwc";
             _kernel                 = static_cast<cl::Kernel>(CLKernelLibrary::get().create_kernel(kernel_name, build_opts.options()));
             break;
         }
         default:
             ARM_COMPUTE_ERROR("Not implemented");
     }
     // Configure kernel window
     auto win_config = validate_and_configure_window(input->info(), output->info(), pool_info);
     ARM_COMPUTE_ERROR_THROW_ON(std::get<0>(win_config));
     ICLKernel::configure_internal(std::get<1>(win_config));
     if(_data_layout == DataLayout::NCHW)
     {
         CLPoolingConfig pooling_config     = std::get<2>(win_config);
         _num_elems_processed_per_iteration = pooling_config.first;
         _border_size                       = pooling_config.second;
     }
     else
     {
         _border_size                       = BorderSize(1, 0, 0, 0);
         _num_elems_processed_per_iteration = 8;
     }
     // Set config_id for enabling LWS tuning
     _config_id = "pooling_layer_";
     _config_id += lower_string(string_from_data_type(data_type));
     _config_id += "_";
     _config_id += lower_string(string_from_data_layout(_data_layout));
     _config_id += "_";
     _config_id += support::cpp11::to_string(output->info()->dimension(idx_width));
     _config_id += "_";
     _config_id += support::cpp11::to_string(output->info()->dimension(idx_height));
     _config_id += "_";
     _config_id += support::cpp11::to_string(output->info()->dimension(idx_channel));
     _config_id += "_";
     _config_id += lower_string(string_from_data_layout(input->info()->data_layout()));
 }
References CLPoolingLayerKernel::_border_size, CLPoolingLayerKernel::_data_layout, CLPoolingLayerKernel::_input, CLPoolingLayerKernel::_num_elems_processed_per_iteration, CLPoolingLayerKernel::_output, CLPoolingLayerKernel::_pool_info, CLBuildOptions::add_option(), CLBuildOptions::add_option_if(), ARM_COMPUTE_ERROR, ARM_COMPUTE_ERROR_ON_NULLPTR, ARM_COMPUTE_ERROR_THROW_ON, arm_compute::CHANNEL, arm_compute::create_kernel(), ITensorInfo::data_layout(), arm_compute::test::validation::data_type, ITensorInfo::data_type(), ITensorInfo::dimension(), PoolingLayerInfo::exclude_padding(), arm_compute::F16, arm_compute::float_to_string_with_full_precision(), CLKernelLibrary::get(), arm_compute::get_cl_type_from_data_type(), arm_compute::get_data_layout_dimension_index(), Size2D::height, arm_compute::HEIGHT, ITensor::info(), arm_compute::is_data_type_quantized_asymmetric(), PoolingLayerInfo::is_global_pooling(), arm_compute::lower_string(), arm_compute::MAX, arm_compute::NCHW, arm_compute::NHWC, UniformQuantizationInfo::offset, CLBuildOptions::options(), PadStrideInfo::pad_left(), PoolingLayerInfo::pad_stride_info(), PadStrideInfo::pad_top(), PoolingLayerInfo::pool_size(), PoolingLayerInfo::pool_type(), ITensorInfo::quantization_info(), UniformQuantizationInfo::scale, PadStrideInfo::stride(), arm_compute::string_from_data_layout(), arm_compute::string_from_data_type(), arm_compute::string_from_pooling_type(), ITensorInfo::tensor_shape(), arm_compute::support::cpp11::to_string(), TensorShape::total_size_upper(), QuantizationInfo::uniform(), arm_compute::validate_and_configure_window(), Size2D::width, and arm_compute::WIDTH.
operator=() [1/2]
CLPoolingLayerKernel& operator= (const CLPoolingLayerKernel &) delete
Prevent instances of this class from being copied (As this class contains pointers)
operator=() [2/2]
CLPoolingLayerKernel& operator= (CLPoolingLayerKernel &&) default
Allow instances of this class to be moved.
run()
void run (const Window & window, cl::CommandQueue & queue) override virtual
Enqueue the OpenCL kernel to process the given window on the passed OpenCL command queue.
Note
The queue is not flushed by this method, and therefore the kernel will not have been executed by the time this method returns.
Parameters
[in] window Region on which to execute the kernel. (Must be a valid region of the window returned by window()).
[in,out] queue Command queue on which to enqueue the kernel.
Implements ICLKernel.
Definition at line 324 of file CLPoolingLayerKernel.cpp.
 {
     ARM_COMPUTE_ERROR_ON_UNCONFIGURED_KERNEL(this);
     ARM_COMPUTE_ERROR_ON_INVALID_SUBWINDOW(IKernel::window(), window);
     unsigned int pool_stride_x = 0;
     unsigned int pool_stride_y = 0;
     std::tie(pool_stride_x, pool_stride_y) = _pool_info.pad_stride_info().stride();
     // Collapse window
     Window window_collapsed = window.collapse_if_possible(ICLKernel::window(), Window::DimZ);
     switch(_data_layout)
     {
         case DataLayout::NCHW:
         {
             Window slice = window_collapsed.first_slice_window_3D();
             do
             {
                 // Upsample input by pool size
                 Window in_slice(slice);
                 in_slice.set(Window::DimX, Window::Dimension(in_slice.x().start() - _pool_info.pad_stride_info().pad_left(),
                                                              (in_slice.x().end() - _pool_info.pad_stride_info().pad_left()) * pool_stride_x,
                                                              pool_stride_x * _num_elems_processed_per_iteration));
                 in_slice.set(Window::DimY, Window::Dimension(in_slice.y().start() - _pool_info.pad_stride_info().pad_top(),
                                                              (in_slice.y().end() - _pool_info.pad_stride_info().pad_top()) * pool_stride_y,
                                                              pool_stride_y));
                 // Set inputs
                 unsigned int idx = 0;
                 add_3D_tensor_argument(idx, _input, in_slice);
                 add_3D_tensor_argument(idx, _output, slice);
                 enqueue(queue, *this, slice, lws_hint());
             }
             while(window_collapsed.slide_window_slice_3D(slice));
             break;
         }
         case DataLayout::NHWC:
         {
             const size_t total_batches = _output->info()->tensor_shape().total_size_upper(3);
             Window slice    = window_collapsed.first_slice_window_4D();
             Window in_slice = window_collapsed.first_slice_window_4D();
             in_slice.set(Window::DimX, Window::Dimension(0, _input->info()->dimension(0), _num_elems_processed_per_iteration));
             in_slice.set(Window::DimY, Window::Dimension(0, _input->info()->dimension(1), pool_stride_x));
             in_slice.set(Window::DimZ, Window::Dimension(0, _input->info()->dimension(2), pool_stride_y));
             in_slice.set(3, Window::Dimension(0, total_batches, 1));
             do
             {
                 // Set inputs
                 unsigned int idx = 0;
                 add_4D_tensor_argument(idx, _input, in_slice);
                 add_4D_tensor_argument(idx, _output, slice);
                 enqueue(queue, *this, slice, lws_hint());
             }
             while(window.slide_window_slice_4D(slice) && window.slide_window_slice_4D(in_slice));
             break;
         }
         default:
             ARM_COMPUTE_ERROR("Not implemented");
     }
 }
References CLPoolingLayerKernel::_data_layout, CLPoolingLayerKernel::_input, CLPoolingLayerKernel::_num_elems_processed_per_iteration, CLPoolingLayerKernel::_output, CLPoolingLayerKernel::_pool_info, ICLKernel::add_3D_tensor_argument(), ICLKernel::add_4D_tensor_argument(), ARM_COMPUTE_ERROR, ARM_COMPUTE_ERROR_ON_INVALID_SUBWINDOW, ARM_COMPUTE_ERROR_ON_UNCONFIGURED_KERNEL, Window::collapse_if_possible(), ITensorInfo::dimension(), Window::DimX, Window::DimY, Window::DimZ, Window::Dimension::end(), arm_compute::enqueue(), Window::first_slice_window_3D(), Window::first_slice_window_4D(), ITensor::info(), ICLKernel::lws_hint(), arm_compute::NCHW, arm_compute::NHWC, PadStrideInfo::pad_left(), PoolingLayerInfo::pad_stride_info(), PadStrideInfo::pad_top(), Window::set(), arm_compute::test::validation::reference::slice(), Window::slide_window_slice_3D(), Window::slide_window_slice_4D(), Window::Dimension::start(), PadStrideInfo::stride(), ITensorInfo::tensor_shape(), TensorShape::total_size_upper(), IKernel::window(), Window::x(), and Window::y().
validate()
Status validate (const ITensorInfo * input, const ITensorInfo * output, const PoolingLayerInfo & pool_info) static
Static function to check if given info will lead to a valid configuration of CLPoolingLayerKernel.
Parameters
[in] input Source tensor info. Data types supported: QASYMM8/F16/F32.
[in] output Destination tensor info. Data types supported: Same as input.
[in] pool_info Contains pooling operation information described in PoolingLayerInfo.
Returns
a status
Definition at line 316 of file CLPoolingLayerKernel.cpp.
 {
     ARM_COMPUTE_RETURN_ON_ERROR(validate_arguments(input, output, pool_info));
     ARM_COMPUTE_RETURN_ON_ERROR(std::get<0>(validate_and_configure_window(input->clone().get(), output->clone().get(), pool_info)));
     return Status{};
 }
References ARM_COMPUTE_RETURN_ON_ERROR, ICloneable< T >::clone(), and arm_compute::validate_and_configure_window().
Referenced by CLPoolingLayer::validate().
Field Documentation
_border_size
BorderSize _border_size
Definition at line 79 of file CLPoolingLayerKernel.h.
Referenced by CLPoolingLayerKernel::border_size(), and CLPoolingLayerKernel::configure().
_data_layout
DataLayout _data_layout
Definition at line 78 of file CLPoolingLayerKernel.h.
Referenced by CLPoolingLayerKernel::configure(), and CLPoolingLayerKernel::run().
_input
const ICLTensor* _input
Definition at line 75 of file CLPoolingLayerKernel.h.
Referenced by CLPoolingLayerKernel::configure(), and CLPoolingLayerKernel::run().
_num_elems_processed_per_iteration
unsigned int _num_elems_processed_per_iteration
Definition at line 80 of file CLPoolingLayerKernel.h.
Referenced by CLPoolingLayerKernel::configure(), and CLPoolingLayerKernel::run().
_output
ICLTensor* _output
Definition at line 76 of file CLPoolingLayerKernel.h.
Referenced by CLPoolingLayerKernel::configure(), and CLPoolingLayerKernel::run().
_pool_info
PoolingLayerInfo _pool_info
Definition at line 77 of file CLPoolingLayerKernel.h.
Referenced by CLPoolingLayerKernel::configure(), and CLPoolingLayerKernel::run().
The documentation for this class was generated from the following files:
arm_compute/core/CL/kernels/CLPoolingLayerKernel.h
src/core/CL/kernels/CLPoolingLayerKernel.cpp