Compute Library: NEGEMMMatrixMultiplyKernel Class Reference
NEGEMMMatrixMultiplyKernel Class Reference
NEON kernel to multiply two input matrices "A" and "B".
#include <NEGEMMMatrixMultiplyKernel.h>
Public Member Functions
const char * name () const override
Name of the kernel.
NEGEMMMatrixMultiplyKernel ()
Constructor.
NEGEMMMatrixMultiplyKernel (const NEGEMMMatrixMultiplyKernel &)=delete
Prevent instances of this class from being copied (As this class contains pointers)
NEGEMMMatrixMultiplyKernel & operator= (const NEGEMMMatrixMultiplyKernel &)=delete
Prevent instances of this class from being copied (As this class contains pointers)
NEGEMMMatrixMultiplyKernel (NEGEMMMatrixMultiplyKernel &&)=default
Allow instances of this class to be moved.
NEGEMMMatrixMultiplyKernel & operator= (NEGEMMMatrixMultiplyKernel &&)=default
Allow instances of this class to be moved.
void configure (const ITensor *input0, const ITensor *input1, ITensor *output, float alpha, bool is_interleaved, const GEMMReshapeInfo &reshape_info=GEMMReshapeInfo())
Initialise the kernel's input and output.
void run (const Window &window, const ThreadInfo &info) override
Execute the kernel on the passed window.
Public Member Functions inherited from ICPPKernel
virtual ~ICPPKernel ()=default
Default destructor.
Public Member Functions inherited from IKernel
IKernel ()
Constructor.
virtual ~IKernel ()=default
Destructor.
virtual bool is_parallelisable () const
Indicates whether or not the kernel is parallelisable.
virtual BorderSize border_size () const
The size of the border for that kernel.
const Window & window () const
The maximum window the kernel can be executed on.
Static Public Member Functions
static Status validate (const ITensorInfo *input0, const ITensorInfo *input1, const ITensorInfo *output, float alpha, bool is_interleaved, const GEMMReshapeInfo &reshape_info)
Static function to check if given info will lead to a valid configuration of NEGEMMMatrixMultiplyKernel.
Detailed Description
NEON kernel to multiply two input matrices "A" and "B".
All elements of the output matrix/vector will be multiplied by alpha after the matrix multiplication
Note
If the output tensor is a matrix, the implementation assumes that the input tensors input0 and input1 are both matrices and reshaped respectively with NEGEMMInterleave4x4Kernel" and NEGEMMTranspose1xWKernel
If the output tensor is a vector and the data type is F32, the implementation assumes that the first input tensor input0 is a vector and the second input tensor input1 a matrix. The implementation also assumes that both tensors have not been reshaped
Definition at line 39 of file NEGEMMMatrixMultiplyKernel.h.
Constructor & Destructor Documentation
NEGEMMMatrixMultiplyKernel() [1/3]
NEGEMMMatrixMultiplyKernel ()
Constructor.
Definition at line 957 of file NEGEMMMatrixMultiplyKernel.cpp.
     : _input0(nullptr), _input1(nullptr), _output(nullptr), _alpha(1.0f)
 {
 }
NEGEMMMatrixMultiplyKernel() [2/3]
NEGEMMMatrixMultiplyKernel (const NEGEMMMatrixMultiplyKernel &) delete
Prevent instances of this class from being copied (As this class contains pointers)
NEGEMMMatrixMultiplyKernel() [3/3]
NEGEMMMatrixMultiplyKernel (NEGEMMMatrixMultiplyKernel &&) default
Allow instances of this class to be moved.
Member Function Documentation
configure()
void configure (const ITensor * input0, const ITensor * input1, ITensor * output, float alpha, bool is_interleaved, const GEMMReshapeInfo & reshape_info = GEMMReshapeInfo())
Initialise the kernel's input and output.
Note
If the output tensor is a matrix, the input matrices input0 and input1 should be the output of the kernels: NEGEMMInterleave4x4Kernel and NEGEMMTranspose1xWKernel These two kernels change the layout of the original matrices to be more cache-friendly.
Parameters
[in] input0 Input tensor containing the interleaved Matrix A or the vector A. Data types supported: F16/F32
[in] input1 Input tensor containing the transposed Matrix B if the first input tensor A is not a vector. If the output tensor is a vector, input1 must contain the matrix B not reshaped. Data type supported: same as input0
[out] output Output tensor to store the result of matrix multiplication. Data type supported: same as input0.
[in] alpha Weight of the matrix product
[in] is_interleaved (Optional) True if input0 and input1 have been reshaped respectively using NEGEMMInterleave4x4Kernel and NEGEMMTranspose1xWKernel
[in] reshape_info (Optional) GEMM reshape info. If is_interleaved_transposed = true, this object must contain the information to understand how the matrix A and matrix B have been reshaped
Definition at line 962 of file NEGEMMMatrixMultiplyKernel.cpp.
 {
     ARM_COMPUTE_ERROR_ON_NULLPTR(input0, input1, output);
     // Output tensor auto inizialitation if not yet initialized
     TensorShape tensor_shape{ input0->info()->tensor_shape() };
     tensor_shape.set(0, is_interleaved ? reshape_info.n() : input1->info()->dimension(0));
     tensor_shape.set(1, is_interleaved ? reshape_info.m() : input0->info()->dimension(1));
     auto_init_if_empty(*output->info(), input0->info()->clone()->set_tensor_shape(tensor_shape));
     // Perform validate step
     ARM_COMPUTE_ERROR_THROW_ON(validate_arguments(input0->info(), input1->info(), output->info(), alpha, is_interleaved, reshape_info));
     _input0 = input0;
     _input1 = input1;
     _output = output;
     _alpha  = alpha;
     // Configure kernel window
     auto win_config = validate_and_configure_window(input0->info(), input1->info(), output->info());
     ARM_COMPUTE_ERROR_THROW_ON(win_config.first);
     INEKernel::configure(win_config.second);
 }
References arm_compute::test::validation::alpha, ARM_COMPUTE_ERROR_ON_NULLPTR, ARM_COMPUTE_ERROR_THROW_ON, arm_compute::auto_init_if_empty(), ICloneable< T >::clone(), ITensorInfo::dimension(), ITensor::info(), GEMMReshapeInfo::m(), GEMMReshapeInfo::n(), TensorShape::set(), ITensorInfo::tensor_shape(), and arm_compute::validate_and_configure_window().
Referenced by NEGEMM::configure().
name()
const char* name () const inline override virtual
Name of the kernel.
Returns
Kernel name
Implements ICPPKernel.
Definition at line 42 of file NEGEMMMatrixMultiplyKernel.h.
     {
         return "NEGEMMMatrixMultiplyKernel";
     }
operator=() [1/2]
NEGEMMMatrixMultiplyKernel& operator= (const NEGEMMMatrixMultiplyKernel &) delete
Prevent instances of this class from being copied (As this class contains pointers)
operator=() [2/2]
NEGEMMMatrixMultiplyKernel& operator= (NEGEMMMatrixMultiplyKernel &&) default
Allow instances of this class to be moved.
run()
void run (const Window & window, const ThreadInfo & info) override virtual
Execute the kernel on the passed window.
Warning
If is_parallelisable() returns false then the passed window must be equal to window()
Note
The window has to be a region within the window returned by the window() method
The width of the window has to be a multiple of num_elems_processed_per_iteration().
Parameters
[in] window Region on which to execute the kernel. (Must be a region of the window returned by window())
[in] info Info about executing thread and CPU.
Implements ICPPKernel.
Definition at line 996 of file NEGEMMMatrixMultiplyKernel.cpp.
 {
     ARM_COMPUTE_ERROR_ON_UNCONFIGURED_KERNEL(this);
     ARM_COMPUTE_ERROR_ON_INVALID_SUBWINDOW(INEKernel::window(), window);
     const bool multiply_alpha = !(helpers::float_ops::is_one(_alpha));
     // Check if the output tensor is a vector. If so,the kernel runs the vector-matrix multiplication
     if((_output->info()->dimension(1) == 1))
     {
         switch(_input0->info()->data_type())
         {
             case DataType::F32:
             {
                 multiply_alpha ? vector_matrix_multiply_f32<true>(_input0, _input1, _output, window, info, _alpha) :
                 vector_matrix_multiply_f32<false>(_input0, _input1, _output, window, info, _alpha);
                 break;
             }
 #ifdef __ARM_FEATURE_FP16_VECTOR_ARITHMETIC
             case DataType::F16:
             {
                 multiply_alpha ? vector_matrix_multiply_f16<true>(_input0, _input1, _output, window, info, _alpha) :
                 vector_matrix_multiply_f16<false>(_input0, _input1, _output, window, info, _alpha);
                 break;
             }
 #endif /* __ARM_FEATURE_FP16_VECTOR_ARITHMETIC */
             default:
             {
                 ARM_COMPUTE_ERROR("Data type not supported");
                 break;
             }
         }
     }
     else
     {
         switch(_input0->info()->data_type())
         {
             case DataType::F32:
             {
                 multiply_alpha ? matrix_matrix_multiply_f32<true>(_input0, _input1, _output, window, _alpha) :
                 matrix_matrix_multiply_f32<false>(_input0, _input1, _output, window, _alpha);
                 break;
             }
 #ifdef __ARM_FEATURE_FP16_VECTOR_ARITHMETIC
             case DataType::F16:
             {
                 multiply_alpha ? matrix_matrix_multiply_f16<true>(_input0, _input1, _output, window, _alpha) :
                 matrix_matrix_multiply_f16<false>(_input0, _input1, _output, window, _alpha);
                 break;
             }
 #endif /* __ARM_FEATURE_FP16_VECTOR_ARITHMETIC */
             default:
             {
                 ARM_COMPUTE_ERROR("Data type not supported");
                 break;
             }
         }
     }
 }
References ARM_COMPUTE_ERROR, ARM_COMPUTE_ERROR_ON_INVALID_SUBWINDOW, ARM_COMPUTE_ERROR_ON_UNCONFIGURED_KERNEL, ITensorInfo::data_type(), ITensorInfo::dimension(), arm_compute::F16, arm_compute::F32, ITensor::info(), arm_compute::test::validation::info, arm_compute::helpers::float_ops::is_one(), and IKernel::window().
validate()
Status validate (const ITensorInfo * input0, const ITensorInfo * input1, const ITensorInfo * output, float alpha, bool is_interleaved, const GEMMReshapeInfo & reshape_info) static
Static function to check if given info will lead to a valid configuration of NEGEMMMatrixMultiplyKernel.
Parameters
[in] input0 Input tensor containing the interleaved Matrix A or the vector A. Data types supported: F16/F32
[in] input1 Input tensor containing the transposed Matrix B if the first input tensor A is not a vector. If the output tensor is a vector, input1 must contain the matrix B not reshaped. Data type supported: same as input0
[in] output Output tensor to store the result of matrix multiplication. Data type supported: same as input0.
[in] alpha Weight of the matrix product
[in] is_interleaved (Optional) True if input0 and input1 have been reshaped respectively using NEGEMMInterleave4x4Kernel and NEGEMMTranspose1xWKernel
[in] reshape_info (Optional) GEMM reshape info. If is_interleaved_transposed = true, this object must contain the information to understand how the matrix A and matrix B have been reshaped
Returns
a status
Definition at line 987 of file NEGEMMMatrixMultiplyKernel.cpp.
 {
     ARM_COMPUTE_RETURN_ON_ERROR(validate_arguments(input0, input1, output, alpha, is_interleaved, reshape_info));
     ARM_COMPUTE_RETURN_ON_ERROR(validate_and_configure_window(input0->clone().get(), input1->clone().get(), output->clone().get()).first);
     return Status{};
 }
References arm_compute::test::validation::alpha, ARM_COMPUTE_RETURN_ON_ERROR, ICloneable< T >::clone(), and arm_compute::validate_and_configure_window().
Referenced by NEGEMM::validate().
The documentation for this class was generated from the following files:
arm_compute/core/NEON/kernels/NEGEMMMatrixMultiplyKernel.h
src/core/NEON/kernels/NEGEMMMatrixMultiplyKernel.cpp