Compute Library: NESpaceToDepthLayer Class Reference
NESpaceToDepthLayer Class Reference
This function calls the following NEON kernels/functions:
#include <NESpaceToDepthLayer.h>
Public Member Functions
NESpaceToDepthLayer ()
Default constructor.
NESpaceToDepthLayer (const NESpaceToDepthLayer &)=delete
Prevent instances of this class from being copied (As this class contains pointers)
NESpaceToDepthLayer & operator= (const NESpaceToDepthLayer &)=delete
Prevent instances of this class from being copied (As this class contains pointers)
NESpaceToDepthLayer (NESpaceToDepthLayer &&)=default
Allow instances of this class to be moved.
NESpaceToDepthLayer & operator= (NESpaceToDepthLayer &&)=default
Allow instances of this class to be moved.
virtual ~NESpaceToDepthLayer ()=default
Default destructor.
void configure (const ITensor *input, ITensor *output, int32_t block_shape)
Set the input and output tensors.
void run () override
Run the kernels contained in the function.
Public Member Functions inherited from IFunction
virtual ~IFunction ()=default
Destructor.
virtual void prepare ()
Prepare the function for executing.
Static Public Member Functions
static Status validate (const ITensorInfo *input, const ITensorInfo *output, int32_t block_shape)
Static function to check if given info will lead to a valid configuration of NESpaceToDepthLayer (Static block shape and paddings)
Detailed Description
This function calls the following NEON kernels/functions:
NESpaceToDepthLayerKernel
Definition at line 41 of file NESpaceToDepthLayer.h.
Constructor & Destructor Documentation
NESpaceToDepthLayer() [1/3]
NESpaceToDepthLayer ()
Default constructor.
Definition at line 35 of file NESpaceToDepthLayer.cpp.
     : _space_to_depth_kernel()
 {
 }
NESpaceToDepthLayer() [2/3]
NESpaceToDepthLayer (const NESpaceToDepthLayer &) delete
Prevent instances of this class from being copied (As this class contains pointers)
NESpaceToDepthLayer() [3/3]
NESpaceToDepthLayer (NESpaceToDepthLayer &&) default
Allow instances of this class to be moved.
~NESpaceToDepthLayer()
virtual ~NESpaceToDepthLayer () virtual default
Default destructor.
Member Function Documentation
configure()
void configure (const ITensor * input, ITensor * output, int32_t block_shape)
Set the input and output tensors.
Parameters
[in] input Tensor input. Supported tensor rank: 4. Data types supported: U8/S8/QASYMM8/U16/S16/F16/U32/S32/F32.
[out] output Tensor output. Data types supported: same as input
[in] block_shape Block shape value
Definition at line 40 of file NESpaceToDepthLayer.cpp.
 {
     ARM_COMPUTE_ERROR_ON_NULLPTR(input, output);
     _space_to_depth_kernel.configure(input, output, block_shape);
 }
References ARM_COMPUTE_ERROR_ON_NULLPTR, and NESpaceToDepthLayerKernel::configure().
operator=() [1/2]
NESpaceToDepthLayer& operator= (const NESpaceToDepthLayer &) delete
Prevent instances of this class from being copied (As this class contains pointers)
operator=() [2/2]
NESpaceToDepthLayer& operator= (NESpaceToDepthLayer &&) default
Allow instances of this class to be moved.
run()
void run () override virtual
Run the kernels contained in the function.
For NEON kernels:
Multi-threading is used for the kernels which are parallelisable.
By default std::thread::hardware_concurrency() threads are used.
Note
CPPScheduler::set_num_threads() can be used to manually set the number of threads
For OpenCL kernels:
All the kernels are enqueued on the queue associated with CLScheduler.
The queue is then flushed.
Note
The function will not block until the kernels are executed. It is the user's responsibility to wait.
Will call prepare() on first run if hasn't been done
Implements IFunction.
Definition at line 52 of file NESpaceToDepthLayer.cpp.
 {
     NEScheduler::get().schedule(&_space_to_depth_kernel, Window::DimY);
 }
References Window::DimY, Scheduler::get(), and IScheduler::schedule().
validate()
Status validate (const ITensorInfo * input, const ITensorInfo * output, int32_t block_shape) static
Static function to check if given info will lead to a valid configuration of NESpaceToDepthLayer (Static block shape and paddings)
Parameters
[in] input Tensor input info. Supported tensor rank: 4. Data types supported: U8/S8/QASYMM8/U16/S16/F16/U32/S32/F32.
[in] output Tensor output info. Data types supported: same as input
[in] block_shape Block shape value
Returns
a status
Definition at line 46 of file NESpaceToDepthLayer.cpp.
 {
     ARM_COMPUTE_RETURN_ON_ERROR(NESpaceToDepthLayerKernel::validate(input, output, block_shape));
     return Status{};
 }
References ARM_COMPUTE_RETURN_ON_ERROR, and NESpaceToDepthLayerKernel::validate().
The documentation for this class was generated from the following files:
arm_compute/runtime/NEON/functions/NESpaceToDepthLayer.h
src/runtime/NEON/functions/NESpaceToDepthLayer.cpp