Compute Library: NEColorConvertKernel Class Reference
NEColorConvertKernel Class Reference
Interface for the color convert kernel.
#include <NEColorConvertKernel.h>
Public Member Functions
const char * name () const override
Name of the kernel.
NEColorConvertKernel ()
Default constructor.
NEColorConvertKernel (const NEColorConvertKernel &)=delete
Prevent instances of this class from being copied (As this class contains pointers)
NEColorConvertKernel & operator= (const NEColorConvertKernel &)=delete
Prevent instances of this class from being copied (As this class contains pointers)
NEColorConvertKernel (NEColorConvertKernel &&)=default
Allow instances of this class to be moved.
NEColorConvertKernel & operator= (NEColorConvertKernel &&)=default
Allow instances of this class to be moved.
~NEColorConvertKernel ()=default
Default destructor.
void configure (const ITensor *input, ITensor *output)
Set the input and output of the kernel.
void configure (const IMultiImage *input, IImage *output)
Set the input and output of the kernel.
void configure (const IImage *input, IMultiImage *output)
Set the input and output of the kernel.
void configure (const IMultiImage *input, IMultiImage *output)
Set the input and output of the kernel.
void run (const Window &window, const ThreadInfo &info) override
Execute the kernel on the passed window.
Public Member Functions inherited from ICPPKernel
virtual ~ICPPKernel ()=default
Default destructor.
Public Member Functions inherited from IKernel
IKernel ()
Constructor.
virtual ~IKernel ()=default
Destructor.
virtual bool is_parallelisable () const
Indicates whether or not the kernel is parallelisable.
virtual BorderSize border_size () const
The size of the border for that kernel.
const Window & window () const
The maximum window the kernel can be executed on.
Detailed Description
Interface for the color convert kernel.
Definition at line 36 of file NEColorConvertKernel.h.
Constructor & Destructor Documentation
NEColorConvertKernel() [1/3]
NEColorConvertKernel ()
Default constructor.
Definition at line 40 of file NEColorConvertKernel.cpp.
     : _input(nullptr), _output(nullptr), _func(nullptr)
 {
 }
NEColorConvertKernel() [2/3]
NEColorConvertKernel (const NEColorConvertKernel &) delete
Prevent instances of this class from being copied (As this class contains pointers)
NEColorConvertKernel() [3/3]
NEColorConvertKernel (NEColorConvertKernel &&) default
Allow instances of this class to be moved.
~NEColorConvertKernel()
~NEColorConvertKernel () default
Default destructor.
Member Function Documentation
configure() [1/4]
void configure (const ITensor * input, ITensor * output)
Set the input and output of the kernel.
Parameters
[in] input Source tensor. Formats supported: RGBA8888/UYVY422/YUYV422/RGB888
[out] output Destination tensor. Formats supported: RGB888 (if the formats of input are RGBA8888/UYVY422/YUYV422), RGBA8888 (if the formats of input are UYVY422/YUYV422/RGB888/), U8 (if the formats of input is RGB888)
Definition at line 45 of file NEColorConvertKernel.cpp.
 {
     ARM_COMPUTE_ERROR_ON_NULLPTR(input, output);
     set_shape_if_empty(*output->info(), input->info()->tensor_shape());
     ARM_COMPUTE_ERROR_ON_MISMATCHING_SHAPES(input, output);
     unsigned int num_elems_processed_per_iteration = 0;
     switch(input->info()->format())
     {
         case Format::RGBA8888:
         {
             switch(output->info()->format())
             {
                 case Format::RGB888:
                     _func                             = colorconvert_rgbx_to_rgb;
                     num_elems_processed_per_iteration = 16;
                     break;
                 default:
                     ARM_COMPUTE_ERROR("Not supported");
                     break;
             }
             break;
         }
         case Format::UYVY422:
         {
             switch(output->info()->format())
             {
                 case Format::RGB888:
                     _func                             = colorconvert_yuyv_to_rgb<false, false>;
                     num_elems_processed_per_iteration = 32;
                     break;
                 case Format::RGBA8888:
                     _func                             = colorconvert_yuyv_to_rgb<false, true>;
                     num_elems_processed_per_iteration = 32;
                     break;
                 default:
                     ARM_COMPUTE_ERROR("Not supported");
                     break;
             }
             break;
         }
         case Format::YUYV422:
         {
             switch(output->info()->format())
             {
                 case Format::RGB888:
                     _func                             = colorconvert_yuyv_to_rgb<true, false>;
                     num_elems_processed_per_iteration = 32;
                     break;
                 case Format::RGBA8888:
                     _func                             = colorconvert_yuyv_to_rgb<true, true>;
                     num_elems_processed_per_iteration = 32;
                     break;
                 default:
                     ARM_COMPUTE_ERROR("Not supported");
                     break;
             }
             break;
         }
         case Format::RGB888:
         {
             switch(output->info()->format())
             {
                 case Format::RGBA8888:
                     _func                             = colorconvert_rgb_to_rgbx;
                     num_elems_processed_per_iteration = 16;
                     break;
                 case Format::U8:
                     _func                             = colorconvert_rgb_to_u8;
                     num_elems_processed_per_iteration = 16;
                     break;
                 default:
                     ARM_COMPUTE_ERROR("Not supported");
                     break;
             }
             break;
         }
         default:
             ARM_COMPUTE_ERROR("Not supported");
             break;
     }
     _input  = input;
     _output = output;
     // Configure kernel window
     Window                 win = calculate_max_window(*input->info(), Steps(num_elems_processed_per_iteration));
     AccessWindowHorizontal input_access(input->info(), 0, num_elems_processed_per_iteration);
     AccessWindowHorizontal output_access(output->info(), 0, num_elems_processed_per_iteration);
     update_window_and_padding(win, input_access, output_access);
     output_access.set_valid_region(win, input->info()->valid_region());
     INEKernel::configure(win);
 }
References ARM_COMPUTE_ERROR, ARM_COMPUTE_ERROR_ON_MISMATCHING_SHAPES, ARM_COMPUTE_ERROR_ON_NULLPTR, arm_compute::calculate_max_window(), arm_compute::colorconvert_rgb_to_rgbx(), arm_compute::colorconvert_rgb_to_u8(), arm_compute::colorconvert_rgbx_to_rgb(), ITensorInfo::format(), ITensor::info(), arm_compute::RGB888, arm_compute::RGBA8888, arm_compute::set_shape_if_empty(), ITensorInfo::tensor_shape(), arm_compute::U8, arm_compute::update_window_and_padding(), arm_compute::UYVY422, ITensorInfo::valid_region(), and arm_compute::YUYV422.
configure() [2/4]
void configure (const IMultiImage * input, IImage * output)
Set the input and output of the kernel.
Parameters
[in] input Multi-planar source image. Formats supported: NV12/NV21/IYUV
[out] output Single-planar destination image. Formats supported: RGB888/RGBA8888
Definition at line 145 of file NEColorConvertKernel.cpp.
 {
     ARM_COMPUTE_ERROR_ON_NULLPTR(input, output);
     ARM_COMPUTE_ERROR_ON_TENSOR_NOT_2D(output);
     set_shape_if_empty(*output->info(), input->plane(0)->info()->tensor_shape());
     ARM_COMPUTE_ERROR_ON_MISMATCHING_SHAPES(input->plane(0), output);
     unsigned int num_elems_processed_per_iteration = 0;
     switch(input->info()->format())
     {
         case Format::NV12:
         {
             switch(output->info()->format())
             {
                 case Format::RGB888:
                     _func                             = colorconvert_nv12_to_rgb<true, false>;
                     num_elems_processed_per_iteration = 32;
                     break;
                 case Format::RGBA8888:
                     _func                             = colorconvert_nv12_to_rgb<true, true>;
                     num_elems_processed_per_iteration = 32;
                     break;
                 default:
                     ARM_COMPUTE_ERROR("Not supported");
                     break;
             }
             break;
         }
         case Format::NV21:
         {
             switch(output->info()->format())
             {
                 case Format::RGB888:
                     _func                             = colorconvert_nv12_to_rgb<false, false>;
                     num_elems_processed_per_iteration = 32;
                     break;
                 case Format::RGBA8888:
                     _func                             = colorconvert_nv12_to_rgb<false, true>;
                     num_elems_processed_per_iteration = 32;
                     break;
                 default:
                     ARM_COMPUTE_ERROR("Not supported");
                     break;
             }
             break;
         }
         case Format::IYUV:
         {
             switch(output->info()->format())
             {
                 case Format::RGB888:
                     _func                             = colorconvert_iyuv_to_rgb<false>;
                     num_elems_processed_per_iteration = 32;
                     break;
                 case Format::RGBA8888:
                     _func                             = colorconvert_iyuv_to_rgb<true>;
                     num_elems_processed_per_iteration = 32;
                     break;
                 default:
                     ARM_COMPUTE_ERROR("Not supported");
                     break;
             }
             break;
         }
         default:
             ARM_COMPUTE_ERROR("Not supported");
             break;
     }
     _input  = input;
     _output = output;
     // Configure kernel window
     Window win = calculate_max_window(*output->info(), Steps(num_elems_processed_per_iteration));
     win.set_dimension_step(Window::DimY, 2);
     unsigned int input_plane_count = 3;
     if(input->info()->format() == Format::NV12 || input->info()->format() == Format::NV21)
     {
         input_plane_count = 2;
     }
     AccessWindowHorizontal input0_access(input->plane(0)->info(), 0, num_elems_processed_per_iteration);
     AccessWindowRectangle  input1_access(input->plane(1)->info(), 0, 0, num_elems_processed_per_iteration, 1, 0.5f, 0.5f);
     AccessWindowRectangle  input2_access(input_plane_count == 2 ? nullptr : input->plane(2)->info(), 0, 0, num_elems_processed_per_iteration, 1, 0.5f, 0.5f);
     AccessWindowHorizontal output_access(output->info(), 0, num_elems_processed_per_iteration);
     update_window_and_padding(win,
                               input0_access, input1_access, input2_access,
                               output_access);
     ValidRegion intersect_region = intersect_valid_regions(input->plane(0)->info()->valid_region(),
                                                            input->plane(1)->info()->valid_region());
     if(input_plane_count == 3)
     {
         intersect_region = intersect_valid_regions(intersect_region, input->plane(2)->info()->valid_region());
     }
     output_access.set_valid_region(win, intersect_region);
     INEKernel::configure(win);
 }
References ARM_COMPUTE_ERROR, ARM_COMPUTE_ERROR_ON_MISMATCHING_SHAPES, ARM_COMPUTE_ERROR_ON_NULLPTR, ARM_COMPUTE_ERROR_ON_TENSOR_NOT_2D, arm_compute::calculate_max_window(), Window::DimY, MultiImageInfo::format(), ITensorInfo::format(), IMultiImage::info(), ITensor::info(), arm_compute::intersect_valid_regions(), arm_compute::IYUV, arm_compute::NV12, arm_compute::NV21, IMultiImage::plane(), arm_compute::RGB888, arm_compute::RGBA8888, Window::set_dimension_step(), arm_compute::set_shape_if_empty(), ITensorInfo::tensor_shape(), arm_compute::update_window_and_padding(), and ITensorInfo::valid_region().
configure() [3/4]
void configure (const IImage * input, IMultiImage * output)
Set the input and output of the kernel.
Parameters
[in] input Single-planar source image. Formats supported: RGB888/RGBA8888/UYVY422/YUYV422
[out] output Multi-planar destination image. Formats supported: NV12/IYUV/YUV444 (if the formats of input are RGB888/RGB8888)
Definition at line 253 of file NEColorConvertKernel.cpp.
 {
     ARM_COMPUTE_ERROR_ON_NULLPTR(input, output);
     ARM_COMPUTE_ERROR_ON_TENSOR_NOT_2D(input);
     set_shape_if_empty(*output->plane(0)->info(), input->info()->tensor_shape());
     switch(output->info()->format())
     {
         case Format::NV12:
         {
             TensorShape subsampled_shape = input->info()->tensor_shape();
             subsampled_shape.set(0, subsampled_shape[0] / 2);
             subsampled_shape.set(1, subsampled_shape[1] / 2);
             set_shape_if_empty(*output->plane(1)->info(), subsampled_shape);
             ARM_COMPUTE_ERROR_ON_MISMATCHING_DIMENSIONS(subsampled_shape, output->plane(1)->info()->tensor_shape());
             break;
         }
         case Format::IYUV:
         {
             TensorShape subsampled_shape = input->info()->tensor_shape();
             subsampled_shape.set(0, subsampled_shape[0] / 2);
             subsampled_shape.set(1, subsampled_shape[1] / 2);
             set_shape_if_empty(*output->plane(1)->info(), subsampled_shape);
             set_shape_if_empty(*output->plane(2)->info(), subsampled_shape);
             ARM_COMPUTE_ERROR_ON_MISMATCHING_DIMENSIONS(subsampled_shape, output->plane(1)->info()->tensor_shape());
             ARM_COMPUTE_ERROR_ON_MISMATCHING_DIMENSIONS(subsampled_shape, output->plane(2)->info()->tensor_shape());
             break;
         }
         case Format::YUV444:
             set_shape_if_empty(*output->plane(1)->info(), input->info()->tensor_shape());
             set_shape_if_empty(*output->plane(2)->info(), input->info()->tensor_shape());
             ARM_COMPUTE_ERROR_ON_MISMATCHING_SHAPES(input, output->plane(1));
             ARM_COMPUTE_ERROR_ON_MISMATCHING_SHAPES(input, output->plane(2));
             break;
         default:
             ARM_COMPUTE_ERROR("Not supported");
     }
     ARM_COMPUTE_ERROR_ON_MISMATCHING_SHAPES(input, output->plane(0));
     unsigned int num_elems_processed_per_iteration = 0;
     switch(input->info()->format())
     {
         case Format::RGB888:
         {
             switch(output->info()->format())
             {
                 case Format::NV12:
                     _func                             = colorconvert_rgb_to_nv12<false>;
                     num_elems_processed_per_iteration = 16;
                     break;
                 case Format::IYUV:
                     _func                             = colorconvert_rgb_to_iyuv<false>;
                     num_elems_processed_per_iteration = 16;
                     break;
                 case Format::YUV444:
                     _func                             = colorconvert_rgb_to_yuv4<false>;
                     num_elems_processed_per_iteration = 16;
                     break;
                 default:
                     ARM_COMPUTE_ERROR("Not supported");
                     break;
             }
             break;
         }
         case Format::RGBA8888:
         {
             switch(output->info()->format())
             {
                 case Format::NV12:
                     _func                             = colorconvert_rgb_to_nv12<true>;
                     num_elems_processed_per_iteration = 16;
                     break;
                 case Format::IYUV:
                     _func                             = colorconvert_rgb_to_iyuv<true>;
                     num_elems_processed_per_iteration = 16;
                     break;
                 case Format::YUV444:
                     _func                             = colorconvert_rgb_to_yuv4<true>;
                     num_elems_processed_per_iteration = 16;
                     break;
                 default:
                     ARM_COMPUTE_ERROR("Not supported");
                     break;
             }
             break;
         }
         case Format::UYVY422:
         {
             switch(output->info()->format())
             {
                 case Format::NV12:
                     _func                             = colorconvert_yuyv_to_nv12<false>;
                     num_elems_processed_per_iteration = 32;
                     break;
                 case Format::IYUV:
                     _func                             = colorconvert_yuyv_to_iyuv<false>;
                     num_elems_processed_per_iteration = 32;
                     break;
                 default:
                     ARM_COMPUTE_ERROR("Not supported");
                     break;
             }
             break;
         }
         case Format::YUYV422:
         {
             switch(output->info()->format())
             {
                 case Format::NV12:
                     _func                             = colorconvert_yuyv_to_nv12<true>;
                     num_elems_processed_per_iteration = 32;
                     break;
                 case Format::IYUV:
                     _func                             = colorconvert_yuyv_to_iyuv<true>;
                     num_elems_processed_per_iteration = 32;
                     break;
                 default:
                     ARM_COMPUTE_ERROR("Not supported");
                     break;
             }
             break;
         }
         default:
             ARM_COMPUTE_ERROR("Not supported");
             break;
     }
     _input  = input;
     _output = output;
     // Configure kernel window
     Window win = calculate_max_window(*input->info(), Steps(num_elems_processed_per_iteration));
     float sub_sampling = 1.f;
     if((input->info()->format() != Format::RGB888 || output->info()->format() != Format::YUV444) && (input->info()->format() != Format::RGBA8888 || output->info()->format() != Format::YUV444))
     {
         win.set_dimension_step(Window::DimY, 2);
         sub_sampling = 0.5f;
     }
     unsigned int output_plane_count = 3;
     if(output->info()->format() == Format::NV12 || output->info()->format() == Format::NV21)
     {
         output_plane_count = 2;
     }
     AccessWindowHorizontal output0_access(output->plane(0)->info(), 0, num_elems_processed_per_iteration);
     AccessWindowRectangle  output1_access(output->plane(1)->info(), 0, 0, num_elems_processed_per_iteration, 1, sub_sampling, sub_sampling);
     AccessWindowRectangle  output2_access(output_plane_count == 2 ? nullptr : output->plane(2)->info(), 0, 0, num_elems_processed_per_iteration, 1, sub_sampling, sub_sampling);
     update_window_and_padding(win,
                               AccessWindowHorizontal(input->info(), 0, num_elems_processed_per_iteration),
                               output0_access,
                               output1_access,
                               output2_access);
     output0_access.set_valid_region(win, input->info()->valid_region());
     output1_access.set_valid_region(win, input->info()->valid_region());
     output2_access.set_valid_region(win, input->info()->valid_region());
     INEKernel::configure(win);
 }
References ARM_COMPUTE_ERROR, ARM_COMPUTE_ERROR_ON_MISMATCHING_DIMENSIONS, ARM_COMPUTE_ERROR_ON_MISMATCHING_SHAPES, ARM_COMPUTE_ERROR_ON_NULLPTR, ARM_COMPUTE_ERROR_ON_TENSOR_NOT_2D, arm_compute::calculate_max_window(), Window::DimY, MultiImageInfo::format(), ITensorInfo::format(), ITensor::info(), IMultiImage::info(), arm_compute::IYUV, arm_compute::NV12, arm_compute::NV21, IMultiImage::plane(), arm_compute::RGB888, arm_compute::RGBA8888, TensorShape::set(), Window::set_dimension_step(), arm_compute::set_shape_if_empty(), ITensorInfo::tensor_shape(), arm_compute::update_window_and_padding(), arm_compute::UYVY422, ITensorInfo::valid_region(), arm_compute::YUV444, and arm_compute::YUYV422.
configure() [4/4]
void configure (const IMultiImage * input, IMultiImage * output)
Set the input and output of the kernel.
Parameters
[in] input Multi-planar source image. Formats supported: NV12/NV21/IYUV
[out] output Multi-planar destination image. Formats supported: YUV444/IYUV (if the formats of input are NV12/NV21)/NV12 (if the format of input is IYUV)
Definition at line 426 of file NEColorConvertKernel.cpp.
 {
     ARM_COMPUTE_ERROR_ON_NULLPTR(input, output);
     ARM_COMPUTE_ERROR_ON(input == output);
     set_shape_if_empty(*output->plane(0)->info(), input->plane(0)->info()->tensor_shape());
     switch(output->info()->format())
     {
         case Format::NV12:
         {
             TensorShape subsampled_shape = input->plane(0)->info()->tensor_shape();
             subsampled_shape.set(0, subsampled_shape[0] / 2);
             subsampled_shape.set(1, subsampled_shape[1] / 2);
             set_shape_if_empty(*output->plane(1)->info(), subsampled_shape);
             ARM_COMPUTE_ERROR_ON_MISMATCHING_DIMENSIONS(subsampled_shape, output->plane(1)->info()->tensor_shape());
             break;
         }
         case Format::IYUV:
         {
             TensorShape subsampled_shape = input->plane(0)->info()->tensor_shape();
             subsampled_shape.set(0, subsampled_shape[0] / 2);
             subsampled_shape.set(1, subsampled_shape[1] / 2);
             set_shape_if_empty(*output->plane(1)->info(), subsampled_shape);
             set_shape_if_empty(*output->plane(2)->info(), subsampled_shape);
             ARM_COMPUTE_ERROR_ON_MISMATCHING_DIMENSIONS(subsampled_shape, output->plane(1)->info()->tensor_shape());
             ARM_COMPUTE_ERROR_ON_MISMATCHING_DIMENSIONS(subsampled_shape, output->plane(2)->info()->tensor_shape());
             break;
         }
         case Format::YUV444:
             set_shape_if_empty(*output->plane(1)->info(), input->plane(0)->info()->tensor_shape());
             set_shape_if_empty(*output->plane(2)->info(), input->plane(0)->info()->tensor_shape());
             ARM_COMPUTE_ERROR_ON_MISMATCHING_SHAPES(input->plane(0), output->plane(1));
             ARM_COMPUTE_ERROR_ON_MISMATCHING_SHAPES(input->plane(0), output->plane(2));
             break;
         default:
             ARM_COMPUTE_ERROR("Not supported");
     }
     ARM_COMPUTE_ERROR_ON_MISMATCHING_SHAPES(input->plane(0), output->plane(0));
     switch(input->info()->format())
     {
         case Format::NV12:
         {
             switch(output->info()->format())
             {
                 case Format::IYUV:
                     _func = colorconvert_nv12_to_iyuv<true>;
                     break;
                 case Format::YUV444:
                     _func = colorconvert_nv12_to_yuv4<true>;
                     break;
                 default:
                     ARM_COMPUTE_ERROR("Not supported");
                     break;
             }
             break;
         }
         case Format::NV21:
         {
             switch(output->info()->format())
             {
                 case Format::IYUV:
                     _func = colorconvert_nv12_to_iyuv<false>;
                     break;
                 case Format::YUV444:
                     _func = colorconvert_nv12_to_yuv4<false>;
                     break;
                 default:
                     ARM_COMPUTE_ERROR("Not supported");
                     break;
             }
             break;
         }
         case Format::IYUV:
         {
             switch(output->info()->format())
             {
                 case Format::NV12:
                     _func = colorconvert_iyuv_to_nv12;
                     break;
                 case Format::YUV444:
                     _func = colorconvert_iyuv_to_yuv4;
                     break;
                 default:
                     ARM_COMPUTE_ERROR("Not supported");
                     break;
             }
             break;
         }
         default:
             ARM_COMPUTE_ERROR("Not supported");
             break;
     }
     _input  = input;
     _output = output;
     constexpr unsigned int num_elems_processed_per_iteration = 32;
     constexpr float        input_sub_sampling                = 0.5f;
     const float            output_sub_sampling               = output->info()->format() == Format::YUV444 ? 1.f : 0.5f;
     // Configure kernel window
     Window win = calculate_max_window(*input->plane(0)->info(), Steps(num_elems_processed_per_iteration));
     win.set_dimension_step(Window::DimY, 2);
     unsigned int input_plane_count = 3;
     if(input->info()->format() == Format::NV12 || input->info()->format() == Format::NV21)
     {
         input_plane_count = 2;
     }
     unsigned int output_plane_count = 3;
     if(output->info()->format() == Format::NV12 || output->info()->format() == Format::NV21)
     {
         output_plane_count = 2;
     }
     AccessWindowHorizontal output0_access(output->plane(0)->info(), 0, num_elems_processed_per_iteration);
     AccessWindowRectangle  output1_access(output->plane(1)->info(), 0, 0, num_elems_processed_per_iteration, 1, output_sub_sampling, output_sub_sampling);
     AccessWindowRectangle  output2_access(output_plane_count == 2 ? nullptr : output->plane(2)->info(), 0, 0, num_elems_processed_per_iteration, 1, output_sub_sampling, output_sub_sampling);
     update_window_and_padding(win,
                               AccessWindowHorizontal(input->plane(0)->info(), 0, num_elems_processed_per_iteration),
                               AccessWindowRectangle(input->plane(1)->info(), 0, 0, num_elems_processed_per_iteration, 1, input_sub_sampling, input_sub_sampling),
                               AccessWindowRectangle(input_plane_count == 2 ? nullptr : input->plane(2)->info(), 0, 0, num_elems_processed_per_iteration, 1, input_sub_sampling, input_sub_sampling),
                               output0_access,
                               output1_access,
                               output2_access);
     ValidRegion intersect_region = intersect_valid_regions(input->plane(0)->info()->valid_region(),
                                                            input->plane(1)->info()->valid_region());
     if(input_plane_count == 3)
     {
         intersect_region = intersect_valid_regions(intersect_region, input->plane(2)->info()->valid_region());
     }
     output0_access.set_valid_region(win, intersect_region);
     output1_access.set_valid_region(win, intersect_region);
     output2_access.set_valid_region(win, intersect_region);
     INEKernel::configure(win);
 }
References ARM_COMPUTE_ERROR, ARM_COMPUTE_ERROR_ON, ARM_COMPUTE_ERROR_ON_MISMATCHING_DIMENSIONS, ARM_COMPUTE_ERROR_ON_MISMATCHING_SHAPES, ARM_COMPUTE_ERROR_ON_NULLPTR, arm_compute::calculate_max_window(), arm_compute::colorconvert_iyuv_to_nv12(), arm_compute::colorconvert_iyuv_to_yuv4(), Window::DimY, MultiImageInfo::format(), ITensor::info(), IMultiImage::info(), arm_compute::intersect_valid_regions(), arm_compute::IYUV, arm_compute::NV12, arm_compute::NV21, IMultiImage::plane(), TensorShape::set(), Window::set_dimension_step(), arm_compute::set_shape_if_empty(), ITensorInfo::tensor_shape(), arm_compute::update_window_and_padding(), ITensorInfo::valid_region(), and arm_compute::YUV444.
name()
const char* name () const inline override virtual
Name of the kernel.
Returns
Kernel name
Implements ICPPKernel.
Definition at line 39 of file NEColorConvertKernel.h.
     {
         return "NEColorConvertKernel";
     }
operator=() [1/2]
NEColorConvertKernel& operator= (const NEColorConvertKernel &) delete
Prevent instances of this class from being copied (As this class contains pointers)
operator=() [2/2]
NEColorConvertKernel& operator= (NEColorConvertKernel &&) default
Allow instances of this class to be moved.
run()
void run (const Window & window, const ThreadInfo & info) override virtual
Execute the kernel on the passed window.
Warning
If is_parallelisable() returns false then the passed window must be equal to window()
Note
The window has to be a region within the window returned by the window() method
The width of the window has to be a multiple of num_elems_processed_per_iteration().
Parameters
[in] window Region on which to execute the kernel. (Must be a region of the window returned by window())
[in] info Info about executing thread and CPU.
Implements ICPPKernel.
Definition at line 579 of file NEColorConvertKernel.cpp.
 {
     ARM_COMPUTE_UNUSED(info);
     ARM_COMPUTE_ERROR_ON_UNCONFIGURED_KERNEL(this);
     ARM_COMPUTE_ERROR_ON_INVALID_SUBWINDOW(INEKernel::window(), window);
     ARM_COMPUTE_ERROR_ON(_func == nullptr);
     (*_func)(_input, _output, window);
 }
References ARM_COMPUTE_ERROR_ON, ARM_COMPUTE_ERROR_ON_INVALID_SUBWINDOW, ARM_COMPUTE_ERROR_ON_UNCONFIGURED_KERNEL, ARM_COMPUTE_UNUSED, arm_compute::test::validation::info, and IKernel::window().
The documentation for this class was generated from the following files:
arm_compute/core/NEON/kernels/NEColorConvertKernel.h
src/core/NEON/kernels/NEColorConvertKernel.cpp