Compute Library: NEScaleKernel Class Reference
NEScaleKernel Class Reference
NEON kernel to perform scaling on a tensor.
#include <NEScaleKernel.h>
Public Member Functions
const char * name () const override
Name of the kernel.
NEScaleKernel ()
Default constructor.
NEScaleKernel (const NEScaleKernel &)=delete
Prevent instances of this class from being copied (As this class contains pointers)
NEScaleKernel & operator= (const NEScaleKernel &)=delete
Prevent instances of this class from being copied (As this class contains pointers)
NEScaleKernel (NEScaleKernel &&)=default
Allow instances of this class to be moved.
NEScaleKernel & operator= (NEScaleKernel &&)=default
Allow instances of this class to be moved.
~NEScaleKernel ()=default
Default destructor.
void configure (const ITensor *input, const ITensor *dx, const ITensor *dy, const ITensor *offsets, ITensor *output, InterpolationPolicy policy, BorderMode border_mode, PixelValue constant_border_value=PixelValue(), SamplingPolicy sampling_policy=SamplingPolicy::CENTER, bool use_padding=true)
Initialise the kernel's inputs, output and interpolation policy.
void run (const Window &window, const ThreadInfo &info) override
Execute the kernel on the passed window.
BorderSize border_size () const override
The size of the border for that kernel.
Public Member Functions inherited from ICPPKernel
virtual ~ICPPKernel ()=default
Default destructor.
Public Member Functions inherited from IKernel
IKernel ()
Constructor.
virtual ~IKernel ()=default
Destructor.
virtual bool is_parallelisable () const
Indicates whether or not the kernel is parallelisable.
const Window & window () const
The maximum window the kernel can be executed on.
Static Public Member Functions
static Status validate (const ITensorInfo *input, const ITensorInfo *dx, const ITensorInfo *dy, const ITensorInfo *offsets, ITensorInfo *output, InterpolationPolicy policy, BorderMode border_mode, PixelValue constant_border_value=PixelValue(), SamplingPolicy sampling_policy=SamplingPolicy::CENTER, bool use_padding=true)
Static function to check if given info will lead to a valid configuration of NEScaleKernel.
Detailed Description
NEON kernel to perform scaling on a tensor.
Definition at line 35 of file NEScaleKernel.h.
Constructor & Destructor Documentation
NEScaleKernel() [1/3]
NEScaleKernel ()
Default constructor.
Definition at line 328 of file NEScaleKernel.cpp.
     : _func(nullptr), _offsets(nullptr), _dx(nullptr), _dy(nullptr), _input(nullptr), _output(nullptr), _policy(), _border_size(1), _border_mode(), _constant_border_value(PixelValue()),
       _sampling_offset(0), _use_padding(true)
 {
 }
NEScaleKernel() [2/3]
NEScaleKernel (const NEScaleKernel &) delete
Prevent instances of this class from being copied (As this class contains pointers)
NEScaleKernel() [3/3]
NEScaleKernel (NEScaleKernel &&) default
Allow instances of this class to be moved.
~NEScaleKernel()
~NEScaleKernel () default
Default destructor.
Member Function Documentation
border_size()
BorderSize border_size () const override virtual
The size of the border for that kernel.
Returns
The width in number of elements of the border.
Reimplemented from IKernel.
Definition at line 334 of file NEScaleKernel.cpp.
 {
     return _border_size;
 }
Referenced by NEScale::configure(), NEScaleKernel::configure(), and NEScaleKernel::validate().
configure()
void configure (const ITensor * input, const ITensor * dx, const ITensor * dy, const ITensor * offsets, ITensor * output, InterpolationPolicy policy, BorderMode border_mode, PixelValue constant_border_value = PixelValue(), SamplingPolicy sampling_policy = SamplingPolicy::CENTER, bool use_padding = true)
Initialise the kernel's inputs, output and interpolation policy.
Note
dx, dy and offsets have the same dimensions (width and height) of the output tensor
Using policy Area only supports data layout NCHW and input data type U8.
Parameters
[in] input Source tensor. Data types supported: U8/S16/F16/F32.
[in] dx Pixel's distance between the X real coordinate and the smallest X following integer. Data type supported: F32
[in] dy Pixel's distance between the Y real coordinate and the smallest Y following integer. Data type supported: F32
[in] offsets Offset to access the pixel with NEAREST interpolation or the top-left pixel with BILINEAR interpolation in the input tensor. Data type supported: S32.
[out] output Destination tensor. Data types supported: Same as input. All but the lowest two dimensions must be the same size as in the input tensor, i.e. scaling is only performed within the XY-plane.
[in] policy Interpolation type to use
[in] border_mode Border mode policy
[in] constant_border_value (Optional) Constant value to use for borders if border_mode is set to CONSTANT and use_padding is set to false.
[in] sampling_policy (Optional) Sampling policy used by the interpolation. Defaults to SamplingPolicy::CENTER
[in] use_padding (Optional) Is padding in use or not. Defaults to true.
Definition at line 339 of file NEScaleKernel.cpp.
 {
     ARM_COMPUTE_ERROR_ON_NULLPTR(input, output);
     // Perform validation step
     ARM_COMPUTE_ERROR_THROW_ON(validate_arguments(input->info(),
                                                   dx != nullptr ? dx->info() : nullptr,
                                                   dy != nullptr ? dy->info() : nullptr,
                                                   offsets != nullptr ? offsets->info() : nullptr,
                                                   output->info(),
                                                   policy, border_mode, constant_border_value, sampling_policy, use_padding));
     // Get data layout and width/height indices
     const DataLayout data_layout = input->info()->data_layout();
     const int        idx_width   = get_data_layout_dimension_index(data_layout, DataLayoutDimension::WIDTH);
     const int        idx_height  = get_data_layout_dimension_index(data_layout, DataLayoutDimension::HEIGHT);
     _input                 = input;
     _output                = output;
     _offsets               = offsets;
     _dx                    = dx;
     _dy                    = dy;
     _policy                = policy;
     _border_size           = BorderSize(1);
     _border_mode           = border_mode;
     _constant_border_value = constant_border_value;
     _use_padding           = use_padding;
     if(sampling_policy == SamplingPolicy::CENTER)
     {
         _sampling_offset = 0.5f;
     }
     // Compute the ratio between source width/height and destination width/height
     const auto wr = static_cast<float>(input->info()->dimension(idx_width)) / static_cast<float>(output->info()->dimension(idx_width));
     const auto hr = static_cast<float>(input->info()->dimension(idx_height)) / static_cast<float>(output->info()->dimension(idx_height));
     // Add constant border only on top in case of NHWC layout
     if(data_layout == DataLayout::NHWC)
     {
         _border_size = (border_mode != BorderMode::REPLICATE && policy == InterpolationPolicy::BILINEAR && use_padding) ? BorderSize(1, 0, 0, 0) : BorderSize(0);
     }
     // Area interpolation behaves as Nearest Neighbour in case of up-sampling
     if(policy == InterpolationPolicy::AREA && wr <= 1.f && hr <= 1.f)
     {
         policy = InterpolationPolicy::NEAREST_NEIGHBOR;
     }
     // Select interpolation function
     switch(policy)
     {
         case InterpolationPolicy::NEAREST_NEIGHBOR:
         {
             _func = (data_layout == DataLayout::NCHW) ? &NEScaleKernel::scale_nearest_nchw : &NEScaleKernel::scale_nhwc;
             break;
         }
         case InterpolationPolicy::BILINEAR:
         {
             _func = (data_layout == DataLayout::NCHW) ? &NEScaleKernel::scale_bilinear_nchw : &NEScaleKernel::scale_nhwc;
             break;
         }
         case InterpolationPolicy::AREA:
         {
             _func = &NEScaleKernel::scale_area_nchw;
             break;
         }
         default:
             ARM_COMPUTE_ERROR("Unsupported interpolation mode");
     }
     // Configure window
     std::pair<Status, Window> win_config = validate_and_configure_window(input->info(),
                                                                          dx != nullptr ? dx->info() : nullptr,
                                                                          dy != nullptr ? dy->info() : nullptr,
                                                                          offsets != nullptr ? offsets->info() : nullptr,
                                                                          output->info(),
                                                                          policy, border_mode == BorderMode::UNDEFINED, sampling_policy, border_size(), use_padding);
     ARM_COMPUTE_ERROR_THROW_ON(win_config.first);
     INEKernel::configure(win_config.second);
 }
References arm_compute::AREA, ARM_COMPUTE_ERROR, ARM_COMPUTE_ERROR_ON_NULLPTR, ARM_COMPUTE_ERROR_THROW_ON, arm_compute::BILINEAR, arm_compute::test::validation::border_mode, NEScaleKernel::border_size(), arm_compute::CENTER, arm_compute::test::validation::data_layout, ITensorInfo::data_layout(), ITensorInfo::dimension(), arm_compute::get_data_layout_dimension_index(), arm_compute::HEIGHT, ITensor::info(), arm_compute::NCHW, arm_compute::NEAREST_NEIGHBOR, arm_compute::NHWC, arm_compute::test::validation::policy, arm_compute::REPLICATE, arm_compute::UNDEFINED, arm_compute::validate_and_configure_window(), and arm_compute::WIDTH.
Referenced by NEScale::configure().
name()
const char* name () const inline override virtual
Name of the kernel.
Returns
Kernel name
Implements ICPPKernel.
Definition at line 38 of file NEScaleKernel.h.
     {
         return "NEScaleKernel";
     }
operator=() [1/2]
NEScaleKernel& operator= (const NEScaleKernel &) delete
Prevent instances of this class from being copied (As this class contains pointers)
operator=() [2/2]
NEScaleKernel& operator= (NEScaleKernel &&) default
Allow instances of this class to be moved.
run()
void run (const Window & window, const ThreadInfo & info) override virtual
Execute the kernel on the passed window.
Warning
If is_parallelisable() returns false then the passed window must be equal to window()
Note
The window has to be a region within the window returned by the window() method
The width of the window has to be a multiple of num_elems_processed_per_iteration().
Parameters
[in] window Region on which to execute the kernel. (Must be a region of the window returned by window())
[in] info Info about executing thread and CPU.
Implements ICPPKernel.
Definition at line 1017 of file NEScaleKernel.cpp.
 {
     ARM_COMPUTE_UNUSED(info);
     ARM_COMPUTE_ERROR_ON_UNCONFIGURED_KERNEL(this);
     ARM_COMPUTE_ERROR_ON_INVALID_SUBWINDOW(INEKernel::window(), window);
     ARM_COMPUTE_ERROR_ON(_func == nullptr);
     (this->*_func)(window);
 }
References ARM_COMPUTE_ERROR_ON, ARM_COMPUTE_ERROR_ON_INVALID_SUBWINDOW, ARM_COMPUTE_ERROR_ON_UNCONFIGURED_KERNEL, ARM_COMPUTE_UNUSED, arm_compute::test::validation::info, and IKernel::window().
validate()
Status validate (const ITensorInfo * input, const ITensorInfo * dx, const ITensorInfo * dy, const ITensorInfo * offsets, ITensorInfo * output, InterpolationPolicy policy, BorderMode border_mode, PixelValue constant_border_value = PixelValue(), SamplingPolicy sampling_policy = SamplingPolicy::CENTER, bool use_padding = true) static
Static function to check if given info will lead to a valid configuration of NEScaleKernel.
Note
dx, dy and offsets have the same dimensions (width and height) of the output tensor
Using policy Area only supports data layout NCHW and input data type U8.
Parameters
[in] input Source tensor. Data types supported: U8/S16/F16/F32.
[in] dx Pixel's distance between the X real coordinate and the smallest X following integer. Data type supported: F32
[in] dy Pixel's distance between the Y real coordinate and the smallest Y following integer. Data type supported: F32
[in] offsets Offset to access the pixel with NEAREST interpolation or the top-left pixel with BILINEAR interpolation in the input tensor. Data type supported: S32.
[in] output Destination tensor. Data types supported: Same as input. All but the lowest two dimensions must be the same size as in the input tensor, i.e. scaling is only performed within the XY-plane.
[in] policy Interpolation type to use
[in] border_mode Border mode policy
[in] constant_border_value (Optional) Constant value to use for borders if border_mode is set to CONSTANT and use_padding is set to false.
[in] sampling_policy (Optional) Sampling policy used by the interpolation. Defaults to SamplingPolicy::CENTER
[in] use_padding (Optional) Is padding in use or not. Defaults to true.
Definition at line 995 of file NEScaleKernel.cpp.
 {
     BorderSize border_size(1);
     if(input->data_layout() == DataLayout::NHWC)
     {
         border_size = (border_mode == BorderMode::CONSTANT && policy == InterpolationPolicy::BILINEAR) ? BorderSize(1, 0, 0, 0) : BorderSize(0);
     }
     ARM_COMPUTE_RETURN_ON_ERROR(validate_arguments(input, dx, dy, offsets, output, policy, border_mode, constant_border_value, sampling_policy, use_padding));
     ARM_COMPUTE_RETURN_ON_ERROR(validate_and_configure_window(input->clone().get(),
                                                               dx != nullptr ? dx->clone().get() : nullptr,
                                                               dy != nullptr ? dy->clone().get() : nullptr,
                                                               offsets != nullptr ? offsets->clone().get() : nullptr,
                                                               output->clone().get(),
                                                               policy, border_mode == BorderMode::UNDEFINED, sampling_policy, border_size, use_padding)
                                 .first);
     return Status{};
 }
References ARM_COMPUTE_RETURN_ON_ERROR, arm_compute::BILINEAR, arm_compute::test::validation::border_mode, NEScaleKernel::border_size(), ICloneable< T >::clone(), arm_compute::CONSTANT, ITensorInfo::data_layout(), arm_compute::NHWC, arm_compute::test::validation::policy, arm_compute::UNDEFINED, and arm_compute::validate_and_configure_window().
Referenced by NEScale::validate().
The documentation for this class was generated from the following files:
arm_compute/core/NEON/kernels/NEScaleKernel.h
src/core/NEON/kernels/NEScaleKernel.cpp