Compute Library: NEMeanStdDev Class Reference
NEMeanStdDev Class Reference
Basic function to execute mean and std deviation.
#include <NEMeanStdDev.h>
Public Member Functions
NEMeanStdDev ()
Default Constructor.
void configure (IImage *input, float *mean, float *stddev=nullptr)
Initialise the kernel's inputs and outputs.
void run () override
Run the kernels contained in the function.
Public Member Functions inherited from IFunction
virtual ~IFunction ()=default
Destructor.
virtual void prepare ()
Prepare the function for executing.
Detailed Description
Basic function to execute mean and std deviation.
This function calls the following NEON kernels:
NEMeanStdDevKernel
Definition at line 41 of file NEMeanStdDev.h.
Constructor & Destructor Documentation
NEMeanStdDev()
NEMeanStdDev ()
Default Constructor.
Definition at line 30 of file NEMeanStdDev.cpp.
     : _mean_stddev_kernel(), _fill_border_kernel(), _global_sum(0), _global_sum_squared(0)
 {
 }
Member Function Documentation
configure()
void configure (IImage * input, float * mean, float * stddev = nullptr)
Initialise the kernel's inputs and outputs.
Parameters
[in,out] input Input image. Data types supported: U8. (Written to only for border filling)
[out] mean Output average pixel value.
[out] stddev (Optional) Output standard deviation of pixel values.
Definition at line 35 of file NEMeanStdDev.cpp.
 {
     _mean_stddev_kernel.configure(input, mean, &_global_sum, stddev, &_global_sum_squared);
     _fill_border_kernel.configure(input, _mean_stddev_kernel.border_size(), BorderMode::CONSTANT, PixelValue(static_cast<uint8_t>(0)));
 }
References NEMeanStdDevKernel::border_size(), NEFillBorderKernel::configure(), NEMeanStdDevKernel::configure(), and arm_compute::CONSTANT.
run()
void run () override virtual
Run the kernels contained in the function.
For NEON kernels:
Multi-threading is used for the kernels which are parallelisable.
By default std::thread::hardware_concurrency() threads are used.
Note
CPPScheduler::set_num_threads() can be used to manually set the number of threads
For OpenCL kernels:
All the kernels are enqueued on the queue associated with CLScheduler.
The queue is then flushed.
Note
The function will not block until the kernels are executed. It is the user's responsibility to wait.
Will call prepare() on first run if hasn't been done
Implements IFunction.
Definition at line 41 of file NEMeanStdDev.cpp.
 {
     _global_sum         = 0;
     _global_sum_squared = 0;
     NEScheduler::get().schedule(&_fill_border_kernel, Window::DimZ);
     NEScheduler::get().schedule(&_mean_stddev_kernel, Window::DimY);
 }
References Window::DimY, Window::DimZ, Scheduler::get(), and IScheduler::schedule().
The documentation for this class was generated from the following files:
arm_compute/runtime/NEON/functions/NEMeanStdDev.h
src/runtime/NEON/functions/NEMeanStdDev.cpp