Compute Library: CLGEMMLowpQuantizeDownInt32ToUint8ScaleByFixedPointKernel Class Reference
CLGEMMLowpQuantizeDownInt32ToUint8ScaleByFixedPointKernel Class Reference
OpenCL kernel used to quantize down the int32 accumulator values of GEMMLowp to QASYMM8.
#include <CLGEMMLowpQuantizeDownInt32ToUint8ScaleByFixedPointKernel.h>
Public Member Functions
CLGEMMLowpQuantizeDownInt32ToUint8ScaleByFixedPointKernel ()
Constructor.
CLGEMMLowpQuantizeDownInt32ToUint8ScaleByFixedPointKernel (const CLGEMMLowpQuantizeDownInt32ToUint8ScaleByFixedPointKernel &)=delete
Prevent instances of this class from being copied (As this class contains pointers)
CLGEMMLowpQuantizeDownInt32ToUint8ScaleByFixedPointKernel & operator= (const CLGEMMLowpQuantizeDownInt32ToUint8ScaleByFixedPointKernel &)=delete
Prevent instances of this class from being copied (As this class contains pointers)
CLGEMMLowpQuantizeDownInt32ToUint8ScaleByFixedPointKernel (CLGEMMLowpQuantizeDownInt32ToUint8ScaleByFixedPointKernel &&)=default
Allow instances of this class to be moved.
CLGEMMLowpQuantizeDownInt32ToUint8ScaleByFixedPointKernel & operator= (CLGEMMLowpQuantizeDownInt32ToUint8ScaleByFixedPointKernel &&)=default
Allow instances of this class to be moved.
void configure (const ICLTensor *input, const ICLTensor *bias, ICLTensor *output, int result_fixedpoint_multiplier, int result_shift, int result_offset_after_shift, int min=0, int max=0)
Initialise the kernel's input and output.
void run (const Window &window, cl::CommandQueue &queue) override
Enqueue the OpenCL kernel to process the given window on the passed OpenCL command queue.
Public Member Functions inherited from ICLKernel
ICLKernel ()
Constructor.
cl::Kernel & kernel ()
Returns a reference to the OpenCL kernel of this object.
template<typename T >
void add_1D_array_argument (unsigned int &idx, const ICLArray< T > *array, const Strides &strides, unsigned int num_dimensions, const Window &window)
Add the passed 1D array's parameters to the object's kernel's arguments starting from the index idx.
void add_1D_tensor_argument (unsigned int &idx, const ICLTensor *tensor, const Window &window)
Add the passed 1D tensor's parameters to the object's kernel's arguments starting from the index idx.
void add_1D_tensor_argument_if (bool cond, unsigned int &idx, const ICLTensor *tensor, const Window &window)
Add the passed 1D tensor's parameters to the object's kernel's arguments starting from the index idx if the condition is true.
void add_2D_tensor_argument (unsigned int &idx, const ICLTensor *tensor, const Window &window)
Add the passed 2D tensor's parameters to the object's kernel's arguments starting from the index idx.
void add_2D_tensor_argument_if (bool cond, unsigned int &idx, const ICLTensor *tensor, const Window &window)
Add the passed 2D tensor's parameters to the object's kernel's arguments starting from the index idx if the condition is true.
void add_3D_tensor_argument (unsigned int &idx, const ICLTensor *tensor, const Window &window)
Add the passed 3D tensor's parameters to the object's kernel's arguments starting from the index idx.
void add_4D_tensor_argument (unsigned int &idx, const ICLTensor *tensor, const Window &window)
Add the passed 4D tensor's parameters to the object's kernel's arguments starting from the index idx.
template<typename T >
void add_argument (unsigned int &idx, T value)
Add the passed parameters to the object's kernel's arguments starting from the index idx.
void set_lws_hint (const cl::NDRange &lws_hint)
Set the Local-Workgroup-Size hint.
cl::NDRange lws_hint () const
Return the Local-Workgroup-Size hint.
const std::string & config_id () const
Get the configuration ID.
void set_target (GPUTarget target)
Set the targeted GPU architecture.
void set_target (cl::Device &device)
Set the targeted GPU architecture according to the CL device.
GPUTarget get_target () const
Get the targeted GPU architecture.
size_t get_max_workgroup_size ()
Get the maximum workgroup size for the device the CLKernelLibrary uses.
template<typename T , unsigned int dimension_size>
void add_array_argument (unsigned &idx, const ICLArray< T > *array, const Strides &strides, unsigned int num_dimensions, const Window &window)
Add the passed array's parameters to the object's kernel's arguments starting from the index idx.
template<unsigned int dimension_size>
void add_tensor_argument (unsigned &idx, const ICLTensor *tensor, const Window &window)
Public Member Functions inherited from IKernel
IKernel ()
Constructor.
virtual ~IKernel ()=default
Destructor.
virtual bool is_parallelisable () const
Indicates whether or not the kernel is parallelisable.
virtual BorderSize border_size () const
The size of the border for that kernel.
const Window & window () const
The maximum window the kernel can be executed on.
Static Public Member Functions
static Status validate (const ITensorInfo *input, const ITensorInfo *bias, const ITensorInfo *output, int min=0, int max=0)
Static function to check if given info will lead to a valid configuration of CLGEMMLowpQuantizeDownInt32ToUint8ScaleByFixedPointKernel.
Static Public Member Functions inherited from ICLKernel
static constexpr unsigned int num_arguments_per_1D_array ()
Returns the number of arguments enqueued per 1D array object.
static constexpr unsigned int num_arguments_per_1D_tensor ()
Returns the number of arguments enqueued per 1D tensor object.
static constexpr unsigned int num_arguments_per_2D_tensor ()
Returns the number of arguments enqueued per 2D tensor object.
static constexpr unsigned int num_arguments_per_3D_tensor ()
Returns the number of arguments enqueued per 3D tensor object.
static constexpr unsigned int num_arguments_per_4D_tensor ()
Returns the number of arguments enqueued per 4D tensor object.
static cl::NDRange gws_from_window (const Window &window)
Get the global work size given an execution window.
Detailed Description
OpenCL kernel used to quantize down the int32 accumulator values of GEMMLowp to QASYMM8.
This kernel takes a final int32 accumulator value (the output of CLGEMMLowpMatrixMultiplyKernel), and processes it to obtain the final QASYMM8 value. The following computations will be performed by the kernel:
Compute fixed point multiplication between each entry of input by result_fixedpoint_multiplier
Add bias to final result if bias tensor is not a nullptr
Round to nearest division by a power-of-two using result_shift
Add offset to each result
Clamp the value between the specified min and max bounds
Clamp the resulting int32 values to the [0..255] range and cast to QASYMM8.
Definition at line 45 of file CLGEMMLowpQuantizeDownInt32ToUint8ScaleByFixedPointKernel.h.
Constructor & Destructor Documentation
CLGEMMLowpQuantizeDownInt32ToUint8ScaleByFixedPointKernel() [1/3]
CLGEMMLowpQuantizeDownInt32ToUint8ScaleByFixedPointKernel ()
Constructor.
Definition at line 106 of file CLGEMMLowpQuantizeDownInt32ToUint8ScaleByFixedPointKernel.cpp.
     : _input(nullptr), _bias(nullptr), _output(nullptr)
 {
 }
CLGEMMLowpQuantizeDownInt32ToUint8ScaleByFixedPointKernel() [2/3]
CLGEMMLowpQuantizeDownInt32ToUint8ScaleByFixedPointKernel (const CLGEMMLowpQuantizeDownInt32ToUint8ScaleByFixedPointKernel &) delete
Prevent instances of this class from being copied (As this class contains pointers)
CLGEMMLowpQuantizeDownInt32ToUint8ScaleByFixedPointKernel() [3/3]
CLGEMMLowpQuantizeDownInt32ToUint8ScaleByFixedPointKernel (CLGEMMLowpQuantizeDownInt32ToUint8ScaleByFixedPointKernel &&) default
Allow instances of this class to be moved.
Member Function Documentation
configure()
void configure (const ICLTensor * input, const ICLTensor * bias, ICLTensor * output, int result_fixedpoint_multiplier, int result_shift, int result_offset_after_shift, int min = 0, int max = 0)
Initialise the kernel's input and output.
Parameters
[in] input Input tensor. Data type supported: S32
[in] bias Biases tensor. Only shared biases supported and it can be a nullptr if the biases addition is not required. Biases are 1D tensor with dimensions [OFM]. Data type supported: Same as input.
[out] output Output tensor. Data type supported: Data type supported: QASYMM8
[in] result_fixedpoint_multiplier Fixed point value to be multiplied to each element of the input matrix when once the result_offset has been add
[in] result_shift Integer value used to round to nearest division by a power-of-two the result after the fixed point multiplication
[in] result_offset_after_shift Offset to be applied to result before converting it back to QASYMM8
[in] min (Optional) Min value used to saturate down the output result before converting back to QASYMM8
[in] max (Optional) Max value used to saturate up the output result before converting back to QASYMM8, Along with min, this value can be used to implement "rectified linear unit" activation functions
Definition at line 124 of file CLGEMMLowpQuantizeDownInt32ToUint8ScaleByFixedPointKernel.cpp.
 {
     // Perform validate step
     ARM_COMPUTE_ERROR_ON_NULLPTR(input, output);
     ARM_COMPUTE_ERROR_THROW_ON(validate_arguments(input->info(), (bias != nullptr) ? bias->info() : nullptr, output->info(),
                                                   min, max));
     _input  = input;
     _bias   = bias;
     _output = output;
     // Set the arguments to pass at compile time
     CLBuildOptions build_opts;
     build_opts.add_option("-DRESULT_OFFSET_AFTER_SHIFT=" + support::cpp11::to_string(result_offset_after_shift));
     build_opts.add_option("-DRESULT_FIXEDPOINT_MULTIPLIER=" + support::cpp11::to_string(result_fixedpoint_multiplier));
     build_opts.add_option("-DRESULT_SHIFT=" + support::cpp11::to_string(result_shift));
     build_opts.add_option_if((min != 0) && (min != max), "-DMIN_BOUND=" + support::cpp11::to_string(min));
     build_opts.add_option_if((max != 255) && (min != max), "-DMAX_BOUND=" + support::cpp11::to_string(max));
     build_opts.add_option_if(bias != nullptr, "-DADD_BIAS");
     // Create kernel
     _kernel = static_cast<cl::Kernel>(CLKernelLibrary::get().create_kernel("gemmlowp_output_stage_quantize_down_fixedpoint", build_opts.options()));
     // Configure kernel window
     auto win_config = validate_and_configure_window(input->info(), (bias != nullptr) ? bias->info() : nullptr, output->info());
     ARM_COMPUTE_ERROR_THROW_ON(win_config.first);
     ICLKernel::configure_internal(win_config.second);
 }
References CLBuildOptions::add_option(), CLBuildOptions::add_option_if(), ARM_COMPUTE_ERROR_ON_NULLPTR, ARM_COMPUTE_ERROR_THROW_ON, arm_compute::test::validation::bias, arm_compute::create_kernel(), CLKernelLibrary::get(), ITensor::info(), CLTensor::info(), CLBuildOptions::options(), arm_compute::support::cpp11::to_string(), and arm_compute::validate_and_configure_window().
operator=() [1/2]
CLGEMMLowpQuantizeDownInt32ToUint8ScaleByFixedPointKernel& operator= (const CLGEMMLowpQuantizeDownInt32ToUint8ScaleByFixedPointKernel &) delete
Prevent instances of this class from being copied (As this class contains pointers)
operator=() [2/2]
CLGEMMLowpQuantizeDownInt32ToUint8ScaleByFixedPointKernel& operator= (CLGEMMLowpQuantizeDownInt32ToUint8ScaleByFixedPointKernel &&) default
Allow instances of this class to be moved.
run()
void run (const Window & window, cl::CommandQueue & queue) override virtual
Enqueue the OpenCL kernel to process the given window on the passed OpenCL command queue.
Note
The queue is not flushed by this method, and therefore the kernel will not have been executed by the time this method returns.
Parameters
[in] window Region on which to execute the kernel. (Must be a valid region of the window returned by window()).
[in,out] queue Command queue on which to enqueue the kernel.
Implements ICLKernel.
Definition at line 155 of file CLGEMMLowpQuantizeDownInt32ToUint8ScaleByFixedPointKernel.cpp.
 {
     ARM_COMPUTE_ERROR_ON_UNCONFIGURED_KERNEL(this);
     ARM_COMPUTE_ERROR_ON_INVALID_SUBWINDOW(ICLKernel::window(), window);
     // Create input window
     Window collapsed = window.collapse_if_possible(ICLKernel::window(), Window::DimZ);
     Window slice     = collapsed.first_slice_window_3D();
     // Setup bias slice
     unsigned int idx1 = num_arguments_per_3D_tensor();
     if(_bias != nullptr)
     {
         Window biases_slice(slice);
         biases_slice.set(Window::DimY, Window::Dimension(0, 1, 1));
         biases_slice.set(Window::DimZ, Window::Dimension(0, 1, 1));
         add_1D_tensor_argument(idx1, _bias, biases_slice);
     }
     do
     {
         unsigned int idx = 0;
         add_3D_tensor_argument(idx, _input, slice);
         add_3D_tensor_argument(idx1, _output, slice);
         enqueue(queue, *this, slice);
     }
     while(collapsed.slide_window_slice_3D(slice));
 }
References ICLKernel::add_1D_tensor_argument(), ICLKernel::add_3D_tensor_argument(), ARM_COMPUTE_ERROR_ON_INVALID_SUBWINDOW, ARM_COMPUTE_ERROR_ON_UNCONFIGURED_KERNEL, Window::collapse_if_possible(), Window::DimY, Window::DimZ, arm_compute::enqueue(), Window::first_slice_window_3D(), ICLKernel::num_arguments_per_3D_tensor(), Window::set(), arm_compute::test::validation::reference::slice(), Window::slide_window_slice_3D(), and IKernel::window().
validate()
Status validate (const ITensorInfo * input, const ITensorInfo * bias, const ITensorInfo * output, int min = 0, int max = 0) static
Static function to check if given info will lead to a valid configuration of CLGEMMLowpQuantizeDownInt32ToUint8ScaleByFixedPointKernel.
Parameters
[in] input Input tensor. Data type supported: S32
[in] bias Biases tensor. Only shared biases supported and it can be a nullptr if the biases addition is not required. Biases are 1D tensor with dimensions [OFM]. Data type supported: Same as input.
[in] output Output tensor. Data type supported: Data type supported: QASYMM8
[in] min (Optional) Min value used to saturate down the output result before converting back to QASYMM8
[in] max (Optional) Max value used to saturate up the output result before converting back to QASYMM8, Along with min, this value can be used to implement "rectified linear unit" activation functions
Returns
a status
Definition at line 111 of file CLGEMMLowpQuantizeDownInt32ToUint8ScaleByFixedPointKernel.cpp.
 {
     ARM_COMPUTE_ERROR_ON_NULLPTR(input, output);
     ARM_COMPUTE_RETURN_ON_ERROR(validate_arguments(input, bias, output, min, max));
     ARM_COMPUTE_RETURN_ON_ERROR(validate_and_configure_window(input->clone().get(),
                                                               (bias != nullptr) ? bias->clone().get() : nullptr,
                                                               output->clone().get())
                                 .first);
     return Status{};
 }
References ARM_COMPUTE_ERROR_ON_NULLPTR, ARM_COMPUTE_RETURN_ON_ERROR, arm_compute::test::validation::bias, ICloneable< T >::clone(), and arm_compute::validate_and_configure_window().
Referenced by CLGEMMLowpQuantizeDownInt32ToUint8ScaleByFixedPoint::validate().
The documentation for this class was generated from the following files:
arm_compute/core/CL/kernels/CLGEMMLowpQuantizeDownInt32ToUint8ScaleByFixedPointKernel.h
src/core/CL/kernels/CLGEMMLowpQuantizeDownInt32ToUint8ScaleByFixedPointKernel.cpp