Compute Library: NEFastCorners Class Reference
NEFastCorners Class Reference
Basic function to execute fast corners.
#include <NEFastCorners.h>
Public Member Functions
NEFastCorners (std::shared_ptr< IMemoryManager > memory_manager=nullptr)
Constructor.
void configure (IImage *input, float threshold, bool nonmax_suppression, KeyPointArray *corners, BorderMode border_mode, uint8_t constant_border_value=0)
Initialize the function's source, destination, conv and border_mode.
void run () override
Run the kernels contained in the function.
Public Member Functions inherited from IFunction
virtual ~IFunction ()=default
Destructor.
virtual void prepare ()
Prepare the function for executing.
Detailed Description
Basic function to execute fast corners.
This function call the following NEON kernels:
NEFastCornersKernel
NENonMaximaSuppression3x3Kernel (executed if nonmax_suppression == true)
NEFillArrayKernel
Definition at line 53 of file NEFastCorners.h.
Constructor & Destructor Documentation
NEFastCorners()
NEFastCorners (std::shared_ptr< IMemoryManager > memory_manager = nullptr)
Constructor.
Definition at line 38 of file NEFastCorners.cpp.
     : _memory_group(std::move(memory_manager)),
       _fast_corners_kernel(),
       _border_handler(),
       _nonmax_kernel(),
       _fill_kernel(),
       _output(),
       _suppressed(),
       _non_max(false)
 {
 }
Member Function Documentation
configure()
void configure (IImage * input, float threshold, bool nonmax_suppression, KeyPointArray * corners, BorderMode border_mode, uint8_t constant_border_value = 0)
Initialize the function's source, destination, conv and border_mode.
Parameters
[in,out] input Source image. Data type supported: U8. (Written to only for border_mode != UNDEFINED)
[in] threshold Threshold on difference between intensity of the central pixel and pixels on Bresenham's circle of radius 3.
[in] nonmax_suppression If true, non-maximum suppression is applied to detected corners before being placed in the array.
[out] corners Array of keypoints to store the results.
[in] border_mode Strategy to use for borders.
[in] constant_border_value (Optional) Constant value to use for borders if border_mode is set to CONSTANT.
Definition at line 50 of file NEFastCorners.cpp.
 {
     ARM_COMPUTE_ERROR_ON_TENSOR_NOT_2D(input);
     ARM_COMPUTE_ERROR_ON(BorderMode::UNDEFINED != border_mode);
     ARM_COMPUTE_ERROR_ON_DATA_TYPE_CHANNEL_NOT_IN(input, 1, DataType::U8);
     ARM_COMPUTE_ERROR_ON(nullptr == corners);
     ARM_COMPUTE_ERROR_ON(threshold < 1 && threshold > 255);
     _non_max = nonmax_suppression;
     TensorInfo tensor_info(input->info()->tensor_shape(), Format::U8);
     _output.allocator()->init(tensor_info);
     _memory_group.manage(&_output);
     // If border is UNDEFINED _fast_corners_kernel will operate in xwindow (3,
     // width - 3) and ywindow (3, height -3) so the output image will leave the
     // pixels on the borders unchanged. This is reflected in the valid region
     // of the output. The non maxima suppression is only run on the valid
     // pixels.
     _fast_corners_kernel.configure(input, &_output, threshold, nonmax_suppression, BorderMode::UNDEFINED == border_mode);
     _border_handler.configure(input, _fast_corners_kernel.border_size(), border_mode, constant_border_value);
     if(!_non_max)
     {
         _fill_kernel.configure(&_output, 1 /* we keep all texels >0 */, corners);
     }
     else
     {
         _suppressed.allocator()->init(tensor_info);
         _memory_group.manage(&_suppressed);
         _nonmax_kernel.configure(&_output, &_suppressed, BorderMode::UNDEFINED == border_mode);
         _fill_kernel.configure(&_suppressed, 1 /* we keep all texels >0 */, corners);
         // Allocate intermediate tensors
         _suppressed.allocator()->allocate();
     }
     // Allocate intermediate tensors
     _output.allocator()->allocate();
 }
References TensorAllocator::allocate(), Tensor::allocator(), ARM_COMPUTE_ERROR_ON, ARM_COMPUTE_ERROR_ON_DATA_TYPE_CHANNEL_NOT_IN, ARM_COMPUTE_ERROR_ON_TENSOR_NOT_2D, arm_compute::test::validation::border_mode, NEFastCornersKernel::border_size(), NEFastCornersKernel::configure(), NEFillArrayKernel::configure(), NENonMaximaSuppression3x3Kernel::configure(), NEFillBorderKernel::configure(), ITensor::info(), TensorAllocator::init(), MemoryGroupBase< TensorType >::manage(), ITensorInfo::tensor_shape(), arm_compute::test::validation::reference::threshold(), arm_compute::U8, and arm_compute::UNDEFINED.
run()
void run () override virtual
Run the kernels contained in the function.
For NEON kernels:
Multi-threading is used for the kernels which are parallelisable.
By default std::thread::hardware_concurrency() threads are used.
Note
CPPScheduler::set_num_threads() can be used to manually set the number of threads
For OpenCL kernels:
All the kernels are enqueued on the queue associated with CLScheduler.
The queue is then flushed.
Note
The function will not block until the kernels are executed. It is the user's responsibility to wait.
Will call prepare() on first run if hasn't been done
Implements IFunction.
Definition at line 92 of file NEFastCorners.cpp.
 {
     NEScheduler::get().schedule(&_border_handler, Window::DimZ);
     MemoryGroupResourceScope scope_mg(_memory_group);
     NEScheduler::get().schedule(&_fast_corners_kernel, Window::DimY);
     if(_non_max)
     {
         NEScheduler::get().schedule(&_nonmax_kernel, Window::DimY);
     }
     NEScheduler::get().schedule(&_fill_kernel, Window::DimY);
 }
References Window::DimY, Window::DimZ, Scheduler::get(), and IScheduler::schedule().
The documentation for this class was generated from the following files:
arm_compute/runtime/NEON/functions/NEFastCorners.h
src/runtime/NEON/functions/NEFastCorners.cpp