Compute Library: NEFillInnerBorderKernel Class Reference
NEFillInnerBorderKernel Class Reference
Interface for the kernel to fill the interior borders.
#include <NEFillInnerBorderKernel.h>
Public Member Functions
const char * name () const override
Name of the kernel.
NEFillInnerBorderKernel ()
Default constructor.
NEFillInnerBorderKernel (const NEFillInnerBorderKernel &)=delete
Prevent instances of this class from being copied (As this class contains pointers)
NEFillInnerBorderKernel & operator= (const NEFillInnerBorderKernel &)=delete
Prevent instances of this class from being copied (As this class contains pointers)
NEFillInnerBorderKernel (NEFillInnerBorderKernel &&)=default
Allow instances of this class to be moved.
NEFillInnerBorderKernel & operator= (NEFillInnerBorderKernel &&)=default
Allow instances of this class to be moved.
~NEFillInnerBorderKernel ()=default
Default destructor.
void configure (ITensor *input, BorderSize border_size, const PixelValue &constant_border_value=PixelValue())
Initialise the function.
void run (const Window &window, const ThreadInfo &info) override
Execute the kernel on the passed window.
Public Member Functions inherited from ICPPKernel
virtual ~ICPPKernel ()=default
Default destructor.
Public Member Functions inherited from IKernel
IKernel ()
Constructor.
virtual ~IKernel ()=default
Destructor.
virtual bool is_parallelisable () const
Indicates whether or not the kernel is parallelisable.
virtual BorderSize border_size () const
The size of the border for that kernel.
const Window & window () const
The maximum window the kernel can be executed on.
Detailed Description
Interface for the kernel to fill the interior borders.
Definition at line 36 of file NEFillInnerBorderKernel.h.
Constructor & Destructor Documentation
NEFillInnerBorderKernel() [1/3]
NEFillInnerBorderKernel ()
Default constructor.
Definition at line 44 of file NEFillInnerBorderKernel.cpp.
     : _tensor(nullptr), _border_size(0), _constant_border_value(static_cast<float>(0.f))
 {
 }
NEFillInnerBorderKernel() [2/3]
NEFillInnerBorderKernel (const NEFillInnerBorderKernel &) delete
Prevent instances of this class from being copied (As this class contains pointers)
NEFillInnerBorderKernel() [3/3]
NEFillInnerBorderKernel (NEFillInnerBorderKernel &&) default
Allow instances of this class to be moved.
~NEFillInnerBorderKernel()
~NEFillInnerBorderKernel () default
Default destructor.
Member Function Documentation
configure()
void configure (ITensor * input, BorderSize border_size, const PixelValue & constant_border_value = PixelValue())
Initialise the function.
Note
This kernel fills the borders within the XY-planes.
Parameters
[in,out] input Tensor to process. Data types supported: U8/S16/S32/F32.
[in] border_size Size of the border to fill in elements.
[in] constant_border_value (Optional) Constant value to use for borders if border_mode is set to CONSTANT.
Definition at line 49 of file NEFillInnerBorderKernel.cpp.
 {
     ARM_COMPUTE_ERROR_ON_DATA_TYPE_CHANNEL_NOT_IN(input, 1, DataType::U8, DataType::S16, DataType::S32, DataType::F32);
     _tensor                = input;
     _border_size           = border_size;
     _constant_border_value = constant_border_value;
     Window win;
     win.set(Window::DimX, Window::Dimension(0, 1, 1));
     win.set(Window::DimY, Window::Dimension(0, 1, 1));
     win.use_tensor_dimensions(_tensor->info()->tensor_shape(), Window::DimZ);
     INEKernel::configure(win);
 }
References ARM_COMPUTE_ERROR_ON_DATA_TYPE_CHANNEL_NOT_IN, IKernel::border_size(), Window::DimX, Window::DimY, Window::DimZ, arm_compute::F32, ITensor::info(), arm_compute::S16, arm_compute::S32, Window::set(), ITensorInfo::tensor_shape(), arm_compute::U8, and Window::use_tensor_dimensions().
name()
const char* name () const inline override virtual
Name of the kernel.
Returns
Kernel name
Implements ICPPKernel.
Definition at line 39 of file NEFillInnerBorderKernel.h.
     {
         return "NEFillInnerBorderKernel";
     }
operator=() [1/2]
NEFillInnerBorderKernel& operator= (const NEFillInnerBorderKernel &) delete
Prevent instances of this class from being copied (As this class contains pointers)
operator=() [2/2]
NEFillInnerBorderKernel& operator= (NEFillInnerBorderKernel &&) default
Allow instances of this class to be moved.
run()
void run (const Window & window, const ThreadInfo & info) override virtual
Execute the kernel on the passed window.
Warning
If is_parallelisable() returns false then the passed window must be equal to window()
Note
The window has to be a region within the window returned by the window() method
The width of the window has to be a multiple of num_elems_processed_per_iteration().
Parameters
[in] window Region on which to execute the kernel. (Must be a region of the window returned by window())
[in] info Info about executing thread and CPU.
Implements ICPPKernel.
Definition at line 64 of file NEFillInnerBorderKernel.cpp.
 {
     ARM_COMPUTE_UNUSED(info);
     ARM_COMPUTE_ERROR_ON_UNCONFIGURED_KERNEL(this);
     ARM_COMPUTE_ERROR_ON_INVALID_SUBWINDOW(INEKernel::window(), window);
     // If there is no border: early exit
     if(_border_size.empty())
     {
         return;
     }
     switch(_tensor->info()->data_type())
     {
         case DataType::U8:
             fill_value_single_channel<uint8_t>(window);
             break;
         case DataType::S16:
             fill_value_single_channel<int16_t>(window);
             break;
         case DataType::S32:
             fill_value_single_channel<int32_t>(window);
             break;
         case DataType::F32:
             static_assert(sizeof(float) == 4, "Float must be 32 bit");
             fill_value_single_channel<float>(window);
             break;
         default:
             ARM_COMPUTE_ERROR("Not handled");
             break;
     }
 }
References ARM_COMPUTE_ERROR, ARM_COMPUTE_ERROR_ON_INVALID_SUBWINDOW, ARM_COMPUTE_ERROR_ON_UNCONFIGURED_KERNEL, ARM_COMPUTE_UNUSED, ITensorInfo::data_type(), BorderSize::empty(), arm_compute::F32, ITensor::info(), arm_compute::test::validation::info, arm_compute::S16, arm_compute::S32, arm_compute::U8, and IKernel::window().
The documentation for this class was generated from the following files:
arm_compute/core/NEON/kernels/NEFillInnerBorderKernel.h
src/core/NEON/kernels/NEFillInnerBorderKernel.cpp