Compute Library: CLCropKernel Class Reference
CLCropKernel Class Reference
OpenCL kernel to perform a copy between two tensors.
#include <CLCropKernel.h>
Public Member Functions
CLCropKernel ()
Default constructor.
CLCropKernel (const CLCropKernel &)=delete
Prevent instances of this class from being copied (As this class contains pointers).
CLCropKernel & operator= (const CLCropKernel &)=delete
Prevent instances of this class from being copied (As this class contains pointers).
CLCropKernel (CLCropKernel &&)=default
Allow instances of this class to be moved.
CLCropKernel & operator= (CLCropKernel &&)=default
Allow instances of this class to be moved.
void configure (const ICLTensor *input, ICLTensor *output, Coordinates2D start, Coordinates2D end, uint32_t batch_index, float extrapolation_value=0, Window *output_window=nullptr)
Configure kernel.
void run (const Window &window, cl::CommandQueue &queue) override
Enqueue the OpenCL kernel to process the given window on the passed OpenCL command queue.
Public Member Functions inherited from ICLKernel
ICLKernel ()
Constructor.
cl::Kernel & kernel ()
Returns a reference to the OpenCL kernel of this object.
template<typename T >
void add_1D_array_argument (unsigned int &idx, const ICLArray< T > *array, const Strides &strides, unsigned int num_dimensions, const Window &window)
Add the passed 1D array's parameters to the object's kernel's arguments starting from the index idx.
void add_1D_tensor_argument (unsigned int &idx, const ICLTensor *tensor, const Window &window)
Add the passed 1D tensor's parameters to the object's kernel's arguments starting from the index idx.
void add_1D_tensor_argument_if (bool cond, unsigned int &idx, const ICLTensor *tensor, const Window &window)
Add the passed 1D tensor's parameters to the object's kernel's arguments starting from the index idx if the condition is true.
void add_2D_tensor_argument (unsigned int &idx, const ICLTensor *tensor, const Window &window)
Add the passed 2D tensor's parameters to the object's kernel's arguments starting from the index idx.
void add_2D_tensor_argument_if (bool cond, unsigned int &idx, const ICLTensor *tensor, const Window &window)
Add the passed 2D tensor's parameters to the object's kernel's arguments starting from the index idx if the condition is true.
void add_3D_tensor_argument (unsigned int &idx, const ICLTensor *tensor, const Window &window)
Add the passed 3D tensor's parameters to the object's kernel's arguments starting from the index idx.
void add_4D_tensor_argument (unsigned int &idx, const ICLTensor *tensor, const Window &window)
Add the passed 4D tensor's parameters to the object's kernel's arguments starting from the index idx.
template<typename T >
void add_argument (unsigned int &idx, T value)
Add the passed parameters to the object's kernel's arguments starting from the index idx.
void set_lws_hint (const cl::NDRange &lws_hint)
Set the Local-Workgroup-Size hint.
cl::NDRange lws_hint () const
Return the Local-Workgroup-Size hint.
const std::string & config_id () const
Get the configuration ID.
void set_target (GPUTarget target)
Set the targeted GPU architecture.
void set_target (cl::Device &device)
Set the targeted GPU architecture according to the CL device.
GPUTarget get_target () const
Get the targeted GPU architecture.
size_t get_max_workgroup_size ()
Get the maximum workgroup size for the device the CLKernelLibrary uses.
template<typename T , unsigned int dimension_size>
void add_array_argument (unsigned &idx, const ICLArray< T > *array, const Strides &strides, unsigned int num_dimensions, const Window &window)
Add the passed array's parameters to the object's kernel's arguments starting from the index idx.
template<unsigned int dimension_size>
void add_tensor_argument (unsigned &idx, const ICLTensor *tensor, const Window &window)
Public Member Functions inherited from IKernel
IKernel ()
Constructor.
virtual ~IKernel ()=default
Destructor.
virtual bool is_parallelisable () const
Indicates whether or not the kernel is parallelisable.
virtual BorderSize border_size () const
The size of the border for that kernel.
const Window & window () const
The maximum window the kernel can be executed on.
Static Public Member Functions
static Status validate (const ITensorInfo *input, const ITensorInfo *output, Coordinates2D start, Coordinates2D end, uint32_t batch_index, float extrapolation_value=0, Window *output_window=nullptr)
Static function to check if given info will lead to a valid configuration of CLStridedSliceKernel.
Static Public Member Functions inherited from ICLKernel
static constexpr unsigned int num_arguments_per_1D_array ()
Returns the number of arguments enqueued per 1D array object.
static constexpr unsigned int num_arguments_per_1D_tensor ()
Returns the number of arguments enqueued per 1D tensor object.
static constexpr unsigned int num_arguments_per_2D_tensor ()
Returns the number of arguments enqueued per 2D tensor object.
static constexpr unsigned int num_arguments_per_3D_tensor ()
Returns the number of arguments enqueued per 3D tensor object.
static constexpr unsigned int num_arguments_per_4D_tensor ()
Returns the number of arguments enqueued per 4D tensor object.
static cl::NDRange gws_from_window (const Window &window)
Get the global work size given an execution window.
Detailed Description
OpenCL kernel to perform a copy between two tensors.
Definition at line 35 of file CLCropKernel.h.
Constructor & Destructor Documentation
CLCropKernel() [1/3]
CLCropKernel ()
Default constructor.
Definition at line 44 of file CLCropKernel.cpp.
     : _input(nullptr), _output(nullptr), _start(), _batch_index(0), _extrapolation_value(0)
 {
 }
CLCropKernel() [2/3]
CLCropKernel (const CLCropKernel &) delete
Prevent instances of this class from being copied (As this class contains pointers).
CLCropKernel() [3/3]
CLCropKernel (CLCropKernel &&) default
Allow instances of this class to be moved.
Member Function Documentation
configure()
void configure (const ICLTensor * input, ICLTensor * output, Coordinates2D start, Coordinates2D end, uint32_t batch_index, float extrapolation_value = 0, Window * output_window = nullptr)
Configure kernel.
Note
Supported tensor rank: up to 4
Parameters
[in] input Source tensor. Data type supported: U16/S16/U32/S32/F16/F32. Data layouts supported: NHWC.
[out] output Destination tensor. Data type supported: F32
[in] start Coordinates of where to start cropping the image.
[in] end Coordinates of where to end cropping the image.
[in] batch_index Fourth dimension index of the 3D image to crop in input.
[in] extrapolation_value Value to be used for values outside of the image. Default is 0.
[in] output_window Output window to be used in case cropped image is being copied into a tensor. Default is nullptr.
Definition at line 49 of file CLCropKernel.cpp.
 {
     ARM_COMPUTE_ERROR_ON_NULLPTR(input, output);
     ARM_COMPUTE_ERROR_THROW_ON(validate(input->info(), output->info(), start, end, batch_index, extrapolation_value, output_window));
     _input               = input;
     _output              = output;
     _start               = start;
     _batch_index         = batch_index;
     _extrapolation_value = extrapolation_value;
     const int vec_size_x = 4;
     // Create and update the window (if needed)
     Window win = calculate_max_window(*output->info());
     if(output_window != nullptr)
     {
         ARM_COMPUTE_ERROR_ON_INVALID_SUBWINDOW(win, *output_window);
         win = *output_window;
     }
     const int  output_width_x = win.num_iterations(0);
     const bool multi_access_x = output_width_x >= vec_size_x;
     const bool remainder_x    = output_width_x % vec_size_x > 0;
     if(multi_access_x)
     {
         win.set(Window::DimX,
                 Window::Dimension(win.x().start(), ceil_to_multiple(win.x().end(), vec_size_x), vec_size_x));
     }
     ICLKernel::configure_internal(win);
     // Create kernel
     CLBuildOptions build_opts;
     build_opts.add_option("-DDATA_TYPE=" + get_cl_type_from_data_type(input->info()->data_type()));
     build_opts.add_option_if(multi_access_x, "-DVEC_SIZE=" + support::cpp11::to_string(vec_size_x));
     build_opts.add_option_if(multi_access_x && remainder_x, "-DLAST_ACCESSED_X=" + support::cpp11::to_string(std::max<int>(output_width_x - vec_size_x, 0)));
     build_opts.add_option_if(start.x > end.x, "-DWIDTH_FLIPPED=");
     build_opts.add_option_if(start.y > end.y, "-DHEIGHT_FLIPPED=");
     _kernel = static_cast<cl::Kernel>(CLKernelLibrary::get().create_kernel("crop_tensor", build_opts.options()));
 }
References CLBuildOptions::add_option(), CLBuildOptions::add_option_if(), ARM_COMPUTE_ERROR_ON_INVALID_SUBWINDOW, ARM_COMPUTE_ERROR_ON_NULLPTR, ARM_COMPUTE_ERROR_THROW_ON, arm_compute::calculate_max_window(), arm_compute::ceil_to_multiple(), arm_compute::create_kernel(), ITensorInfo::data_type(), Window::DimX, Window::Dimension::end(), CLKernelLibrary::get(), arm_compute::get_cl_type_from_data_type(), ITensor::info(), Window::num_iterations(), CLBuildOptions::options(), Window::set(), Window::Dimension::start(), arm_compute::support::cpp11::to_string(), CLCropKernel::validate(), Window::x(), Coordinates2D::x, and Coordinates2D::y.
operator=() [1/2]
CLCropKernel& operator= (const CLCropKernel &) delete
Prevent instances of this class from being copied (As this class contains pointers).
operator=() [2/2]
CLCropKernel& operator= (CLCropKernel &&) default
Allow instances of this class to be moved.
run()
void run (const Window & window, cl::CommandQueue & queue) override virtual
Enqueue the OpenCL kernel to process the given window on the passed OpenCL command queue.
Note
The queue is not flushed by this method, and therefore the kernel will not have been executed by the time this method returns.
Parameters
[in] window Region on which to execute the kernel. (Must be a valid region of the window returned by window()).
[in,out] queue Command queue on which to enqueue the kernel.
Implements ICLKernel.
Definition at line 115 of file CLCropKernel.cpp.
 {
     ARM_COMPUTE_ERROR_ON_UNCONFIGURED_KERNEL(this);
     ARM_COMPUTE_ERROR_ON_INVALID_SUBWINDOW(ICLKernel::window(), window);
     Window in_slice = Window();
     in_slice.use_tensor_dimensions(_input->info()->tensor_shape());
     in_slice.set(Window::DimX, Window::Dimension(in_slice.x().start(), ceil_to_multiple(in_slice.x().end(), window.x().step()), window.x().step()));
     in_slice.set(3, Window::Dimension(_batch_index, _batch_index + 1, 1));
     unsigned int idx = 0;
     add_3D_tensor_argument(idx, _input, in_slice);
     add_3D_tensor_argument(idx, _output, window);
     add_argument(idx, _start.x);
     add_argument(idx, _start.y);
     enqueue(queue, *this, window);
 }
References ICLKernel::add_3D_tensor_argument(), ICLKernel::add_argument(), ARM_COMPUTE_ERROR_ON_INVALID_SUBWINDOW, ARM_COMPUTE_ERROR_ON_UNCONFIGURED_KERNEL, arm_compute::ceil_to_multiple(), Window::DimX, Window::Dimension::end(), arm_compute::enqueue(), ITensor::info(), Window::set(), Window::Dimension::start(), Window::Dimension::step(), ITensorInfo::tensor_shape(), Window::use_tensor_dimensions(), IKernel::window(), Window::x(), Coordinates2D::x, and Coordinates2D::y.
validate()
Status validate (const ITensorInfo * input, const ITensorInfo * output, Coordinates2D start, Coordinates2D end, uint32_t batch_index, float extrapolation_value = 0, Window * output_window = nullptr) static
Static function to check if given info will lead to a valid configuration of CLStridedSliceKernel.
Note
Supported tensor rank: up to 4
Parameters
[in] input Source tensor info. Data type supported: U16/S16/U32/S32/F16/F32. Data layouts supported: NHWC.
[in] output Destination tensor info. Data type supported: F32
[in] start Coordinates of where to start cropping the image.
[in] end Coordinates of where to end cropping the image.
[in] batch_index Fourth dimension index of the 3D image to crop in input.
[in] extrapolation_value Value to be used for values outside of the image. Default is 0.
[in] output_window Output window to be used in case cropped image is being copied into a tensor. Default is nullptr.
Definition at line 91 of file CLCropKernel.cpp.
 {
     ARM_COMPUTE_UNUSED(extrapolation_value, output_window);
     ARM_COMPUTE_RETURN_ERROR_ON_CPU_F16_UNSUPPORTED(input);
     ARM_COMPUTE_RETURN_ERROR_ON_DATA_TYPE_CHANNEL_NOT_IN(input, 1, DataType::U16, DataType::S16, DataType::F16, DataType::U32, DataType::S32, DataType::F32);
     ARM_COMPUTE_RETURN_ERROR_ON_DATA_LAYOUT_NOT_IN(input, DataLayout::NHWC);
     ARM_COMPUTE_RETURN_ERROR_ON(input->tensor_shape().num_dimensions() > 4);
     ARM_COMPUTE_RETURN_ERROR_ON(start.x < 0 || start.y < 0 || end.x < 0 || end.y < 0);
     ARM_COMPUTE_RETURN_ERROR_ON(start.x >= static_cast<int32_t>(input->dimension(1)) || start.y >= static_cast<int32_t>(input->dimension(2))
                                 || end.x >= static_cast<int32_t>(input->dimension(1)) || end.y >= static_cast<int32_t>(input->dimension(2)));
     ARM_COMPUTE_RETURN_ERROR_ON(batch_index >= input->dimension(3));
     if(output_window != nullptr)
     {
         ARM_COMPUTE_RETURN_ERROR_ON(output_window->x().step() != 1);
     }
     if(output->total_size() > 0)
     {
         ARM_COMPUTE_RETURN_ERROR_ON_DATA_TYPE_NOT_IN(output, DataType::F32);
         ARM_COMPUTE_RETURN_ERROR_ON_MISMATCHING_DATA_LAYOUT(input, output);
         ARM_COMPUTE_RETURN_ERROR_ON(output->num_dimensions() > 3);
     }
     return Status{};
 }
References ARM_COMPUTE_RETURN_ERROR_ON, ARM_COMPUTE_RETURN_ERROR_ON_CPU_F16_UNSUPPORTED, ARM_COMPUTE_RETURN_ERROR_ON_DATA_LAYOUT_NOT_IN, ARM_COMPUTE_RETURN_ERROR_ON_DATA_TYPE_CHANNEL_NOT_IN, ARM_COMPUTE_RETURN_ERROR_ON_DATA_TYPE_NOT_IN, ARM_COMPUTE_RETURN_ERROR_ON_MISMATCHING_DATA_LAYOUT, ARM_COMPUTE_UNUSED, ITensorInfo::dimension(), arm_compute::F16, arm_compute::F32, arm_compute::NHWC, Dimensions< T >::num_dimensions(), ITensorInfo::num_dimensions(), arm_compute::S16, arm_compute::S32, Window::Dimension::step(), ITensorInfo::tensor_shape(), ITensorInfo::total_size(), arm_compute::U16, arm_compute::U32, Window::x(), Coordinates2D::x, and Coordinates2D::y.
Referenced by CLCropKernel::configure(), and CLCropResize::validate().
The documentation for this class was generated from the following files:
arm_compute/core/CL/kernels/CLCropKernel.h
src/core/CL/kernels/CLCropKernel.cpp