Compute Library: GCScheduler Class Reference
GCScheduler Class Reference
Provides global access to a OpenGL ES context and command queue.
#include <GCScheduler.h>
Public Member Functions
void default_init ()
Initialises the context and command queue used by the scheduler to default values and sets a default device and kernel path for the GCKernelLibrary.
void dispatch (IGCKernel &kernel, bool flush=true)
Schedule the execution of the passed kernel if possible.
void init (EGLDisplay dpy, EGLContext ctx)
Initialises the display and context to be used by the scheduler.
void memory_barrier ()
Defines a barrier ordering memory transactions.
GPUTarget get_target () const
Get the target GPU.
void set_target (GPUTarget target)
Accessor to set target GPU to be used by the scheduler.
Static Public Member Functions
static GCScheduler & get ()
Access the scheduler singleton.
Detailed Description
Provides global access to a OpenGL ES context and command queue.
Definition at line 36 of file GCScheduler.h.
Member Function Documentation
default_init()
void default_init ()
Initialises the context and command queue used by the scheduler to default values and sets a default device and kernel path for the GCKernelLibrary.
Definition at line 48 of file GCScheduler.cpp.
 {
     setup_context();
     init(_display, _context);
 }
References GCScheduler::init().
Referenced by GCDeviceBackend::initialize_backend(), and main().
dispatch()
void dispatch (IGCKernel & kernel, bool flush = true)
Schedule the execution of the passed kernel if possible.
Parameters
[in] kernel Kernel to execute.
[in] flush (Optional) Specifies if the command queue will be flushed after running the kernel.
Definition at line 69 of file GCScheduler.cpp.
 {
     kernel.run(kernel.window());
     if(flush)
     {
         ARM_COMPUTE_GL_CHECK(glFlush());
     }
 }
References ARM_COMPUTE_GL_CHECK, glFlush(), IGCKernel::run(), and IKernel::window().
Referenced by GCGEMM::prepare(), IGCSimpleFunction::run(), GCDropoutLayer::run(), GCConcatenateLayer::run(), GCConvolutionLayerReshapeWeights::run(), GCBatchNormalizationLayer::run(), GCNormalizationLayer::run(), GCDepthwiseConvolutionLayer3x3::run(), GCSoftmaxLayer::run(), GCPoolingLayer::run(), GCNormalizePlanarYUVLayer::run(), GCDirectConvolutionLayer::run(), GCFullyConnectedLayer::run(), GCGEMM::run(), and GCConvolutionLayer::run().
get()
GCScheduler & get () static
Access the scheduler singleton.
Returns
The scheduler
Definition at line 62 of file GCScheduler.cpp.
 {
     std::call_once(_initialize_symbols, opengles31_is_available);
     static GCScheduler scheduler;
     return scheduler;
 }
References arm_compute::opengles31_is_available().
Referenced by GCGEMM::configure(), GCConvolutionLayer::configure(), GCDeviceBackend::initialize_backend(), main(), GCGEMM::prepare(), IGCSimpleFunction::run(), GCDropoutLayer::run(), GCConcatenateLayer::run(), GCConvolutionLayerReshapeWeights::run(), GCBatchNormalizationLayer::run(), GCNormalizationLayer::run(), GCSoftmaxLayer::run(), GCDepthwiseConvolutionLayer3x3::run(), GCPoolingLayer::run(), GCNormalizePlanarYUVLayer::run(), GCDirectConvolutionLayer::run(), GCFullyConnectedLayer::run(), GCGEMM::run(), and GCConvolutionLayer::run().
get_target()
GPUTarget get_target () const inline
Get the target GPU.
Returns
The target GPU.
Definition at line 71 of file GCScheduler.h.
     {
         return _target;
     }
Referenced by GCGEMM::configure().
init()
void init (EGLDisplay dpy, EGLContext ctx)
Initialises the display and context to be used by the scheduler.
Parameters
[in] dpy The EGL display connection
[in] ctx The EGL rendering context
Definition at line 55 of file GCScheduler.cpp.
 {
     _target = get_target_from_device();
     GCKernelLibrary::get().init("./cs_shaders/", dpy, ctx);
 }
References GCKernelLibrary::get(), arm_compute::get_target_from_device(), and GCKernelLibrary::init().
Referenced by GCScheduler::default_init().
memory_barrier()
void memory_barrier ()
Defines a barrier ordering memory transactions.
Definition at line 78 of file GCScheduler.cpp.
 {
     ARM_COMPUTE_GL_CHECK(glMemoryBarrier(GL_SHADER_STORAGE_BARRIER_BIT));
 }
References ARM_COMPUTE_GL_CHECK, and glMemoryBarrier().
Referenced by GCGEMM::prepare(), IGCSimpleFunction::run(), GCNormalizationLayer::run(), GCSoftmaxLayer::run(), GCDepthwiseConvolutionLayer3x3::run(), GCPoolingLayer::run(), GCDirectConvolutionLayer::run(), GCFullyConnectedLayer::run(), GCGEMM::run(), and GCConvolutionLayer::run().
set_target()
void set_target (GPUTarget target) inline
Accessor to set target GPU to be used by the scheduler.
Parameters
[in] target The target GPU.
Definition at line 80 of file GCScheduler.h.
     {
         _target = target;
     }
The documentation for this class was generated from the following files:
arm_compute/runtime/GLES_COMPUTE/GCScheduler.h
src/runtime/GLES_COMPUTE/GCScheduler.cpp