Compute Library: NEWeightsReshapeKernel Class Reference
NEWeightsReshapeKernel Class Reference
NEON kernel to perform reshaping on the weights used by convolution and locally connected layer.
#include <NEWeightsReshapeKernel.h>
Public Member Functions
const char * name () const override
Name of the kernel.
NEWeightsReshapeKernel ()
Constructor.
NEWeightsReshapeKernel (const NEWeightsReshapeKernel &)=delete
Prevent instances of this class from being copied (As this class contains pointers)
NEWeightsReshapeKernel & operator= (const NEWeightsReshapeKernel &)=delete
Prevent instances of this class from being copied (As this class contains pointers)
NEWeightsReshapeKernel (NEWeightsReshapeKernel &&)=default
Allow instances of this class to be moved.
NEWeightsReshapeKernel & operator= (NEWeightsReshapeKernel &&)=default
Allow instances of this class to be moved.
~NEWeightsReshapeKernel ()=default
Default destructor.
void configure (const ITensor *input, const ITensor *bias, ITensor *output)
Set the input and output of the kernel.
void run (const Window &window, const ThreadInfo &info) override
Execute the kernel on the passed window.
Public Member Functions inherited from ICPPKernel
virtual ~ICPPKernel ()=default
Default destructor.
Public Member Functions inherited from IKernel
IKernel ()
Constructor.
virtual ~IKernel ()=default
Destructor.
virtual bool is_parallelisable () const
Indicates whether or not the kernel is parallelisable.
virtual BorderSize border_size () const
The size of the border for that kernel.
const Window & window () const
The maximum window the kernel can be executed on.
Static Public Member Functions
static Status validate (const ITensorInfo *input, const ITensorInfo *biases, const ITensorInfo *output)
Static function to check if given info will lead to a valid configuration of NEWeightsReshapeKernel.
Detailed Description
NEON kernel to perform reshaping on the weights used by convolution and locally connected layer.
Rearranges each 3-dimensional kernel to a single row leading to a matrix with linearized kernels. In combination with the NEIm2ColKernel can transform a convolution to a matrix multiplication.
For example assuming a 3D weight kernel of 3x3 dimensions and depth of 2 we have:
\[ \left(\begin{array}{ccc} a000 & a001 & a002 \\ a010 & a011 & a012 \\ a020 & a021 & a022 \\ \end{array} \right) \left(\begin{array}{ccc} a100 & a101 & a102 \\ a110 & a111 & a112 \\ a120 & a121 & a122 \\ \end{array} \right) \rightarrow \left(\begin{array}{ccccccccc} a000 & a001 & a002 & a010 & a011 & a012 & a020 & a021 & a022 & a100 & a101 & a102 & a110 & a111 & a112 & a120 & a121 & a122 \\ \end{array} \right) \]
Definition at line 56 of file NEWeightsReshapeKernel.h.
Constructor & Destructor Documentation
NEWeightsReshapeKernel() [1/3]
NEWeightsReshapeKernel ()
Constructor.
Definition at line 90 of file NEWeightsReshapeKernel.cpp.
     : _input(nullptr), _bias(nullptr), _output(nullptr)
 {
 }
NEWeightsReshapeKernel() [2/3]
NEWeightsReshapeKernel (const NEWeightsReshapeKernel &) delete
Prevent instances of this class from being copied (As this class contains pointers)
NEWeightsReshapeKernel() [3/3]
NEWeightsReshapeKernel (NEWeightsReshapeKernel &&) default
Allow instances of this class to be moved.
~NEWeightsReshapeKernel()
~NEWeightsReshapeKernel () default
Default destructor.
Member Function Documentation
configure()
void configure (const ITensor * input, const ITensor * bias, ITensor * output)
Set the input and output of the kernel.
Parameters
[in] input The input tensor to convert. Weights are 4D tensor with dimensions [kernel_x, kernel_y, IFM, OFM] if shared, and 5D tensor with dimensions [kernel_x, kernel_y, IFM, OFM, num_patches] if unshared. Data types supported: QASYMM8/F32
[in] bias The shared biases tensor to append. Bias is 1D tensor with dimensions [OFM] if shared and 2D tensor with dimensions [OFM, num_patches] if unshared. Data types supported: Same as input
Warning
Appending biases to weights reshaped matrix is not supported for quantized asymmetric types.
Parameters
[out] output The output tensor. Data types supported: Same as input
Definition at line 95 of file NEWeightsReshapeKernel.cpp.
 {
     ARM_COMPUTE_ERROR_ON_NULLPTR(input, output);
     // Output tensor auto inizialitation if not yet initialized
     auto_init_if_empty(*output->info(), input->info()->clone()->set_tensor_shape(get_output_shape(input->info(), (bias != nullptr))));
     // Perform validation step
     ARM_COMPUTE_ERROR_THROW_ON(validate_arguments(input->info(),
                                                   (bias != nullptr) ? bias->info() : nullptr,
                                                   output->info()));
     _input  = input;
     _bias   = bias;
     _output = output;
     // Configure kernel
     auto win_config = validate_and_configure_window(input->info(), output->info());
     ARM_COMPUTE_ERROR_THROW_ON(win_config.first);
     INEKernel::configure(win_config.second);
 }
References ARM_COMPUTE_ERROR_ON_NULLPTR, ARM_COMPUTE_ERROR_THROW_ON, arm_compute::auto_init_if_empty(), arm_compute::test::validation::bias, ICloneable< T >::clone(), ITensor::info(), CLTensor::info(), and arm_compute::validate_and_configure_window().
Referenced by NEConvolutionLayerReshapeWeights::configure(), and NELocallyConnectedLayer::configure().
name()
const char* name () const inline override virtual
Name of the kernel.
Returns
Kernel name
Implements ICPPKernel.
Definition at line 59 of file NEWeightsReshapeKernel.h.
     {
         return "NEWeightsReshapeKernel";
     }
operator=() [1/2]
NEWeightsReshapeKernel& operator= (const NEWeightsReshapeKernel &) delete
Prevent instances of this class from being copied (As this class contains pointers)
operator=() [2/2]
NEWeightsReshapeKernel& operator= (NEWeightsReshapeKernel &&) default
Allow instances of this class to be moved.
run()
void run (const Window & window, const ThreadInfo & info) override virtual
Execute the kernel on the passed window.
Warning
If is_parallelisable() returns false then the passed window must be equal to window()
Note
The window has to be a region within the window returned by the window() method
The width of the window has to be a multiple of num_elems_processed_per_iteration().
Parameters
[in] window Region on which to execute the kernel. (Must be a region of the window returned by window())
[in] info Info about executing thread and CPU.
Implements ICPPKernel.
Definition at line 125 of file NEWeightsReshapeKernel.cpp.
 {
     ARM_COMPUTE_UNUSED(info);
     ARM_COMPUTE_ERROR_ON_UNCONFIGURED_KERNEL(this);
     ARM_COMPUTE_ERROR_ON_INVALID_SUBWINDOW(INEKernel::window(), window);
     const unsigned int kernel_size_x   = _input->info()->dimension(0);
     const unsigned int kernel_size_y   = _input->info()->dimension(1);
     const unsigned int kernel_depth    = _input->info()->dimension(2);
     const unsigned int input_stride_x  = _input->info()->strides_in_bytes().x();
     const unsigned int input_stride_y  = _input->info()->strides_in_bytes().y();
     const unsigned int input_stride_z  = _input->info()->strides_in_bytes().z();
     const unsigned int output_stride_y = _output->info()->strides_in_bytes().y();
     // Create iterators
     Iterator in(_input, window);
     execute_window_loop(window, [&](const Coordinates & id)
     {
         // Get column index
         const int kernel_idx = id[3];
         const int kernel_idz = id[4];
         // Setup pointers
         const uint8_t *tmp_input_ptr        = in.ptr();
         uint8_t       *tmp_output_ptr       = _output->ptr_to_element(Coordinates(kernel_idx, 0, kernel_idz));
         const uint8_t *curr_input_row_ptr   = tmp_input_ptr;
         const uint8_t *curr_input_depth_ptr = tmp_input_ptr;
         // Linearize volume
         for(unsigned int d = 0; d < kernel_depth; ++d)
         {
             for(unsigned int j = 0; j < kernel_size_y; ++j)
             {
                 for(unsigned int i = 0; i < kernel_size_x; ++i)
                 {
                     std::memcpy(tmp_output_ptr, tmp_input_ptr, _input->info()->element_size());
                     tmp_input_ptr += input_stride_x;
                     tmp_output_ptr += output_stride_y;
                 }
                 curr_input_row_ptr += input_stride_y;
                 tmp_input_ptr = curr_input_row_ptr;
             }
             curr_input_depth_ptr += input_stride_z;
             curr_input_row_ptr = curr_input_depth_ptr;
             tmp_input_ptr      = curr_input_depth_ptr;
         }
         // Add bias
         if(_bias != nullptr)
         {
             std::memcpy(tmp_output_ptr, _bias->ptr_to_element(Coordinates(kernel_idx, kernel_idz)), _input->info()->element_size());
         }
     },
     in);
 }
References ARM_COMPUTE_ERROR_ON_INVALID_SUBWINDOW, ARM_COMPUTE_ERROR_ON_UNCONFIGURED_KERNEL, ARM_COMPUTE_UNUSED, ITensorInfo::dimension(), ITensorInfo::element_size(), arm_compute::execute_window_loop(), ITensor::info(), arm_compute::test::validation::info, Iterator::ptr(), ITensor::ptr_to_element(), ITensorInfo::strides_in_bytes(), IKernel::window(), Dimensions< T >::x(), Dimensions< T >::y(), and Dimensions< T >::z().
validate()
Status validate (const ITensorInfo * input, const ITensorInfo * biases, const ITensorInfo * output) static
Static function to check if given info will lead to a valid configuration of NEWeightsReshapeKernel.
Parameters
[in] input The input tensor to convert. Weights are 4D tensor with dimensions [kernel_x, kernel_y, IFM, OFM] if shared, and 5D tensor with dimensions [kernel_x, kernel_y, IFM, OFM, num_patches] if unshared. Data types supported: QASYMM8/F16/F32
[in] biases The shared biases tensor to append. Bias is 1D tensor with dimensions [OFM] if shared and 2D tensor with dimensions [OFM, num_patches] if unshared. Data types supported: Same as input
Warning
Appending biases to weights reshaped matrix is not supported for quantized asymmetric types.
Parameters
[in] output The output tensor. Should be a 2D Tensor. Data types supported: Same as input
Returns
a status
Definition at line 117 of file NEWeightsReshapeKernel.cpp.
 {
     ARM_COMPUTE_RETURN_ON_ERROR(validate_arguments(input, biases, output));
     ARM_COMPUTE_RETURN_ON_ERROR(validate_and_configure_window(input->clone().get(), output->clone().get()).first);
     return Status{};
 }
References ARM_COMPUTE_RETURN_ON_ERROR, ICloneable< T >::clone(), and arm_compute::validate_and_configure_window().
Referenced by NEConvolutionLayerReshapeWeights::validate(), and NELocallyConnectedLayer::validate().
The documentation for this class was generated from the following files:
arm_compute/core/NEON/kernels/NEWeightsReshapeKernel.h
src/core/NEON/kernels/NEWeightsReshapeKernel.cpp