Compute Library: NEDepthwiseIm2ColKernel Class Reference
NEDepthwiseIm2ColKernel Class Reference
Interface for the depthwise im2col reshape kernel.
#include <NEDepthwiseIm2ColKernel.h>
Public Member Functions
const char * name () const override
Name of the kernel.
NEDepthwiseIm2ColKernel ()
Default constructor.
NEDepthwiseIm2ColKernel (const NEDepthwiseIm2ColKernel &)=delete
Prevent instances of this class from being copied (As this class contains pointers)
NEDepthwiseIm2ColKernel & operator= (const NEDepthwiseIm2ColKernel &)=delete
Prevent instances of this class from being copied (As this class contains pointers)
NEDepthwiseIm2ColKernel (NEDepthwiseIm2ColKernel &&)=default
Allow instances of this class to be moved.
NEDepthwiseIm2ColKernel & operator= (NEDepthwiseIm2ColKernel &&)=default
Allow instances of this class to be moved.
void configure (const ITensor *input, ITensor *output, const Size2D &kernel_dims, const PadStrideInfo &conv_info, bool has_bias=false, unsigned int depth_multiplier=1, const Size2D &dilation=Size2D(1U, 1U))
Set the input and output of the kernel.
void run (const Window &window, const ThreadInfo &info) override
Execute the kernel on the passed window.
Public Member Functions inherited from ICPPKernel
virtual ~ICPPKernel ()=default
Default destructor.
Public Member Functions inherited from IKernel
IKernel ()
Constructor.
virtual ~IKernel ()=default
Destructor.
virtual bool is_parallelisable () const
Indicates whether or not the kernel is parallelisable.
virtual BorderSize border_size () const
The size of the border for that kernel.
const Window & window () const
The maximum window the kernel can be executed on.
Static Public Member Functions
static Status validate (const ITensorInfo *input, const ITensorInfo *output, const Size2D &kernel_dims, const PadStrideInfo &conv_info, bool has_bias=false, unsigned int depth_multiplier=1, const Size2D &dilation=Size2D(1U, 1U))
Static function to check if given info will lead to a valid configuration of NEDepthwiseIm2ColKernel.
Detailed Description
Interface for the depthwise im2col reshape kernel.
This kernel reshape the input low 3 dimensions to a new 3D shape where the output's first dimension is the linear patch size (FILTER_WIDTH * FILTER_HEIGHT) and second dimension is number of patches in per image and third dimension unchanged .
Definition at line 38 of file NEDepthwiseIm2ColKernel.h.
Constructor & Destructor Documentation
NEDepthwiseIm2ColKernel() [1/3]
NEDepthwiseIm2ColKernel ()
Default constructor.
Definition at line 134 of file NEDepthwiseIm2ColKernel.cpp.
     : _func(nullptr), _input(nullptr), _output(nullptr), _kernel_dims(), _conv_info(), _has_bias(), _depth_multiplier(1), _dilation()
 {
 }
NEDepthwiseIm2ColKernel() [2/3]
NEDepthwiseIm2ColKernel (const NEDepthwiseIm2ColKernel &) delete
Prevent instances of this class from being copied (As this class contains pointers)
NEDepthwiseIm2ColKernel() [3/3]
NEDepthwiseIm2ColKernel (NEDepthwiseIm2ColKernel &&) default
Allow instances of this class to be moved.
Member Function Documentation
configure()
void configure (const ITensor * input, ITensor * output, const Size2D & kernel_dims, const PadStrideInfo & conv_info, bool has_bias = false, unsigned int depth_multiplier = 1, const Size2D & dilation = Size2D(1U, 1U))
Set the input and output of the kernel.
Parameters
[in] input The input tensor to convert. 3 lower dimensions represent a single input [width, height, IFM], while every optional dimension from 4 and above represent a batch of inputs. Data types supported: QASYMM8/F16/F32
[out] output The output tensor. First 3 lower dimensions represent a transform of each 3D input, while every dimension above 3 represents a batch. Data types supported: Same as input
[in] kernel_dims The kernel dimensions (width and height).
[in] conv_info Contains padding and stride information described in PadStrideInfo.
[in] has_bias Boolean that specifies if the depthwise convolution has bias.
[in] depth_multiplier (Optional) Multiplier to apply to the input's depth in order to retrieve the output's depth. Defaults to 1.
[in] dilation (Optional) Dilation, in elements, across x and y. Defaults to (1, 1).
Definition at line 139 of file NEDepthwiseIm2ColKernel.cpp.
 {
     ARM_COMPUTE_ERROR_ON_NULLPTR(input, output);
     ARM_COMPUTE_ERROR_THROW_ON(validate_arguments(input->info(), output->info(), kernel_dims, conv_info, has_bias, depth_multiplier, dilation));
     _input            = input;
     _output           = output;
     _kernel_dims      = kernel_dims;
     _conv_info        = conv_info;
     _has_bias         = has_bias;
     _depth_multiplier = depth_multiplier;
     _dilation         = dilation;
     // Configure kernel window
     Window win = calculate_max_window(*input->info(), Steps());
     // Set appropriate function to run
     switch(input->info()->data_type())
     {
         case DataType::QASYMM8:
             _func = &NEDepthwiseIm2ColKernel::run_generic<uint8_t>;
             break;
         case DataType::F16:
             _func = &NEDepthwiseIm2ColKernel::run_generic<half>;
             break;
         case DataType::F32:
             _func = &NEDepthwiseIm2ColKernel::run_generic<float>;
             break;
         default:
             ARM_COMPUTE_ERROR("Unsupported data type");
     }
     // The NEDepthwiseIm2ColKernel doesn't need padding so update_window_and_padding() can be skipped
     output->info()->set_valid_region(ValidRegion(Coordinates(), output->info()->tensor_shape()));
     INEKernel::configure(win);
 }
References ARM_COMPUTE_ERROR, ARM_COMPUTE_ERROR_ON_NULLPTR, ARM_COMPUTE_ERROR_THROW_ON, arm_compute::calculate_max_window(), arm_compute::test::validation::conv_info, ITensorInfo::data_type(), arm_compute::test::validation::dilation, arm_compute::F16, arm_compute::F32, arm_compute::test::validation::has_bias, ITensor::info(), arm_compute::QASYMM8, ITensorInfo::set_valid_region(), and ITensorInfo::tensor_shape().
Referenced by NEDepthwiseConvolutionLayer::configure().
name()
const char* name () const inline override virtual
Name of the kernel.
Returns
Kernel name
Implements ICPPKernel.
Definition at line 41 of file NEDepthwiseIm2ColKernel.h.
     {
         return "NEDepthwiseIm2ColKernel";
     }
operator=() [1/2]
NEDepthwiseIm2ColKernel& operator= (const NEDepthwiseIm2ColKernel &) delete
Prevent instances of this class from being copied (As this class contains pointers)
operator=() [2/2]
NEDepthwiseIm2ColKernel& operator= (NEDepthwiseIm2ColKernel &&) default
Allow instances of this class to be moved.
run()
void run (const Window & window, const ThreadInfo & info) override virtual
Execute the kernel on the passed window.
Warning
If is_parallelisable() returns false then the passed window must be equal to window()
Note
The window has to be a region within the window returned by the window() method
The width of the window has to be a multiple of num_elems_processed_per_iteration().
Parameters
[in] window Region on which to execute the kernel. (Must be a region of the window returned by window())
[in] info Info about executing thread and CPU.
Implements ICPPKernel.
Definition at line 187 of file NEDepthwiseIm2ColKernel.cpp.
 {
     ARM_COMPUTE_UNUSED(info);
     ARM_COMPUTE_ERROR_ON_UNCONFIGURED_KERNEL(this);
     ARM_COMPUTE_ERROR_ON_INVALID_SUBWINDOW(INEKernel::window(), window);
     if(_func != nullptr)
     {
         (this->*_func)(window);
     }
 }
References ARM_COMPUTE_ERROR_ON_INVALID_SUBWINDOW, ARM_COMPUTE_ERROR_ON_UNCONFIGURED_KERNEL, ARM_COMPUTE_UNUSED, arm_compute::test::validation::info, and IKernel::window().
validate()
Status validate (const ITensorInfo * input, const ITensorInfo * output, const Size2D & kernel_dims, const PadStrideInfo & conv_info, bool has_bias = false, unsigned int depth_multiplier = 1, const Size2D & dilation = Size2D(1U, 1U)) static
Static function to check if given info will lead to a valid configuration of NEDepthwiseIm2ColKernel.
Parameters
[in] input The input tensor info to convert. 3 lower dimensions represent a single input [width, height, IFM], while every optional dimension from 4 and above represent a batch of inputs. Data types supported: QASYMM8/F16/F32
[in] output The output tensor info. First 3 lower dimensions represent a transform of each 3D input, while every dimension above 3 represents a batch. Data types supported: Same as input
[in] kernel_dims The kernel dimensions (width and height).
[in] conv_info Contains padding and stride information described in PadStrideInfo.
[in] has_bias Boolean that specifies if the depthwise convolution has bias.
[in] depth_multiplier (Optional) Multiplier to apply to the input's depth in order to retrieve the output's depth. Defaults to 1.
[in] dilation (Optional) Dilation, in elements, across x and y. Defaults to (1, 1).
Returns
a status
Definition at line 179 of file NEDepthwiseIm2ColKernel.cpp.
 {
     ARM_COMPUTE_RETURN_ERROR_ON_NULLPTR(input, output);
     ARM_COMPUTE_RETURN_ON_ERROR(validate_arguments(input, output, kernel_dims, conv_info, has_bias, depth_multiplier, dilation));
     return Status{};
 }
References ARM_COMPUTE_RETURN_ERROR_ON_NULLPTR, ARM_COMPUTE_RETURN_ON_ERROR, arm_compute::test::validation::conv_info, arm_compute::test::validation::dilation, and arm_compute::test::validation::has_bias.
Referenced by NEDepthwiseConvolutionLayer::validate().
The documentation for this class was generated from the following files:
arm_compute/core/NEON/kernels/NEDepthwiseIm2ColKernel.h
src/core/NEON/kernels/NEDepthwiseIm2ColKernel.cpp