Compute Library: ICloneable< T > Class Template Reference
ICloneable< T > Class Template Reference abstract
Clonable Interface.
#include <ICloneable.h>
Public Member Functions
virtual ~ICloneable ()=default
Default virtual desctructor.
virtual std::unique_ptr< T > clone () const =0
Provide a clone of the current object of class T.
Detailed Description
template<class T>
class arm_compute::misc::ICloneable< T >
Clonable Interface.
Definition at line 35 of file ICloneable.h.
Constructor & Destructor Documentation
~ICloneable()
virtual ~ICloneable () virtual default
Default virtual desctructor.
Member Function Documentation
clone()
virtual std::unique_ptr<T> clone () const pure virtual
Provide a clone of the current object of class T.
Returns
Clone object of class T
Implemented in TensorInfo, TensorDescriptor, and SubTensorInfo.
Referenced by SubTensorInfo::clone(), CLTransposeKernel::configure(), CLReduceMean::configure(), NEReduceMean::configure(), CLReverseKernel::configure(), CPPDetectionOutputLayer::configure(), CLNormalizationLayerKernel::configure(), CLPermuteKernel::configure(), CLReorgLayerKernel::configure(), CLActivationLayerKernel::configure(), NEReverseKernel::configure(), NEDepthToSpaceLayerKernel::configure(), NEPadLayer::configure(), CLNormalizePlanarYUVLayerKernel::configure(), GCNormalizePlanarYUVLayerKernel::configure(), NEChannelShuffleLayerKernel::configure(), CLDepthwiseVectorToTensorKernel::configure(), NEReorgLayerKernel::configure(), CLReductionOperation::configure(), CLConvertFullyConnectedWeightsKernel::configure(), NETransposeKernel::configure(), CPPPermuteKernel::configure(), CLWinogradInputTransformKernel::configure(), CLPadLayer::configure(), NEDepthwiseVectorToTensorKernel::configure(), NEPermuteKernel::configure(), CLSoftmaxLayer::configure(), CLFuseBatchNormalizationKernel::configure(), CLDirectConvolutionLayerOutputStageKernel::configure(), CLWinogradFilterTransformKernel::configure(), NEDirectConvolutionLayerOutputStageKernel::configure(), NEFFTRadixStageKernel::configure(), NEGEMMInterleave4x4Kernel::configure(), NEBatchToSpaceLayerKernel::configure(), NEConvertFullyConnectedWeightsKernel::configure(), CLWinogradOutputTransformKernel::configure(), NEDepthwiseConvolutionAssemblyDispatch::configure(), NEGEMMMatrixMultiplyKernel::configure(), NEFuseBatchNormalizationKernel::configure(), CLGEMMLowpQuantizeDownInt32ToUint8ScaleKernel::configure(), NESoftmaxLayer::configure(), NEGEMMLowpQuantizeDownInt32ToUint8ScaleKernel::configure(), NEGEMM::configure(), GCWeightsReshapeKernel::configure(), GCCol2ImKernel::configure(), CLWeightsReshapeKernel::configure(), NEWeightsReshapeKernel::configure(), CLFFTConvolutionLayer::configure(), NEFFTConvolutionLayer::configure(), CLDirectDeconvolutionLayer::configure(), NEDeconvolutionLayer::configure(), NEFullyConnectedLayer::configure(), CLFullyConnectedLayer::configure(), NEGEMMInterleavedWrapper::configure(), CLLogits1DMaxShiftExpSumKernel::configure(), CLDepthwiseConvolutionLayer::configure(), CLLogits1DNormKernel::configure(), NEDepthwiseConvolutionLayer::configure(), CLTransposeKernel::validate(), NEFloorKernel::validate(), NELogits1DMaxKernel::validate(), CLGEMMMatrixAccumulateBiasesKernel::validate(), CLGEMMMatrixVectorMultiplyKernel::validate(), CLFloorKernel::validate(), CLDequantizationLayerKernel::validate(), CLMinMaxLayerKernel::validate(), CLChannelShuffleLayerKernel::validate(), CLFFT2D::validate(), NEFFT2D::validate(), CLFlattenLayerKernel::validate(), CLDepthwiseConvolutionLayerReshapeWeightsKernel::validate(), CLQuantizationLayerKernel::validate(), NEGEMMMatrixAccumulateBiasesKernel::validate(), CLCopyKernel::validate(), CLSplit::validate(), NESplit::validate(), NELocallyConnectedMatrixMultiplyKernel::validate(), NEDequantizationLayerKernel::validate(), CLLocallyConnectedMatrixMultiplyKernel::validate(), NEGEMMMatrixVectorMultiplyKernel::validate(), CLFFTScaleKernel::validate(), CLNormalizationLayerKernel::validate(), NEPriorBoxLayerKernel::validate(), CLGatherKernel::validate(), CLWidthConcatenate2TensorsKernel::validate(), CLGEMMMatrixAdditionKernel::validate(), CLActivationLayerKernel::validate(), GCPoolingLayerKernel::validate(), CLComparisonKernel::validate(), CLMeanStdDevNormalizationKernel::validate(), CLPoolingLayerKernel::validate(), CLFFTDigitReverseKernel::validate(), CLWidthConcatenateLayerKernel::validate(), CLDepthwiseConvolutionLayer3x3NCHWKernel::validate(), CLHeightConcatenateLayerKernel::validate(), CLDepthwiseConvolutionLayer3x3NHWCKernel::validate(), CLPriorBoxLayerKernel::validate(), CLRangeKernel::validate(), CLFFTRadixStageKernel::validate(), NETransposeKernel::validate(), NEUpsampleLayerKernel::validate(), GCArithmeticAdditionKernel::validate(), CLNormalizePlanarYUVLayerKernel::validate(), NEFFTScaleKernel::validate(), NEFlattenLayerKernel::validate(), CLWidthConcatenate4TensorsKernel::validate(), CLSelectKernel::validate(), NEPadLayer::validate(), NEPoolingLayerKernel::validate(), CLDepthConcatenateLayerKernel::validate(), NEScale::validate(), GCNormalizePlanarYUVLayerKernel::validate(), CLBatchConcatenateLayerKernel::validate(), NEHeightConcatenateLayerKernel::validate(), CLReductionOperationKernel::validate(), NEWidthConcatenateLayerKernel::validate(), NEFFTDigitReverseKernel::validate(), CLPixelWiseMultiplicationKernel::validate(), NEReductionOperationKernel::validate(), NEYOLOLayerKernel::validate(), NEGEMMInterleave4x4Kernel::validate(), NENormalizationLayerKernel::validate(), CLL2NormalizeLayerKernel::validate(), CLYOLOLayerKernel::validate(), NEBatchConcatenateLayerKernel::validate(), NEDepthConcatenateLayerKernel::validate(), NERangeKernel::validate(), NEFFTRadixStageKernel::validate(), NEActivationLayerKernel::validate(), NEMeanStdDevNormalizationKernel::validate(), NEMinMaxLayerKernel::validate(), CLGEMMReshapeRHSMatrixKernel::validate(), CLGEMMLowpMatrixMultiplyKernel::validate(), CLGEMMLowpMatrixMultiplyNativeKernel::validate(), CLSoftmaxLayer::validate(), NEGEMMMatrixAdditionKernel::validate(), CLDirectConvolutionLayerOutputStageKernel::validate(), CLStackLayerKernel::validate(), CLPadLayer::validate(), NEGEMMLowpMatrixMultiplyKernel::validate(), NEDepthwiseConvolutionLayer3x3Kernel::validate(), CLGEMMReshapeLHSMatrixKernel::validate(), GCBatchNormalizationLayerKernel::validate(), GCGEMMMatrixMultiplyKernel::validate(), NEDepthConvertLayerKernel::validate(), CLGEMMLowpMatrixAReductionKernel::validate(), NEStackLayerKernel::validate(), CLGEMMLowpMatrixMultiplyReshapedOnlyRHSKernel::validate(), NEDepthwiseConvolutionLayerNativeKernel::validate(), NEDirectConvolutionLayerOutputStageKernel::validate(), NEGEMMMatrixMultiplyKernel::validate(), NEDirectConvolutionLayerKernel::validate(), CLGEMMLowpQuantizeDownInt32ToInt16ScaleByFixedPointKernel::validate(), CLBatchNormalizationLayerKernel::validate(), NEPixelWiseMultiplicationKernel::validate(), CLGEMMLowpQuantizeDownInt32ToUint8ScaleByFloatKernel::validate(), CLWinogradInputTransformKernel::validate(), NEArithmeticAdditionKernel::validate(), CLGEMMLowpOffsetContributionOutputStageKernel::validate(), NEArithmeticSubtractionKernel::validate(), CLStridedSliceKernel::validate(), CLGEMMLowpQuantizeDownInt32ToUint8ScaleByFixedPointKernel::validate(), NESoftmaxLayer::validate(), CLCol2ImKernel::validate(), CLGEMMLowpQuantizeDownInt32ToUint8ScaleKernel::validate(), CLDirectConvolutionLayerKernel::validate(), CLGEMMMatrixMultiplyNativeKernel::validate(), NEBatchNormalizationLayerKernel::validate(), CLWinogradFilterTransformKernel::validate(), CLGEMMLowpOffsetContributionKernel::validate(), NEGEMMLowpOffsetContributionKernel::validate(), NEGEMMLowpQuantizeDownInt32ToInt16ScaleByFixedPointKernel::validate(), CLGEMMMatrixMultiplyKernel::validate(), CLGEMMLowpMatrixMultiplyReshapedKernel::validate(), NEGEMMTranspose1xWKernel::validate(), NEGEMMLowpQuantizeDownInt32ToUint8ScaleKernel::validate(), NEGEMMLowpQuantizeDownInt32ToUint8ScaleByFixedPointKernel::validate(), NEStridedSliceKernel::validate(), CLGEMMMatrixMultiplyReshapedOnlyRHSKernel::validate(), NEScaleKernel::validate(), NECol2ImKernel::validate(), CLWinogradOutputTransformKernel::validate(), NECropResize::validate(), NEGEMM::validate(), NEDirectConvolutionLayer::validate(), NEGEMMLowpMatrixAReductionKernel::validate(), CLCropResize::validate(), CLGEMMLowpMatrixMultiplyCore::validate(), NEWeightsReshapeKernel::validate(), CLWinogradConvolutionLayer::validate(), NEWinogradConvolutionLayer::validate(), CLGEMMMatrixMultiplyReshapedKernel::validate(), CLIm2ColKernel::validate(), NEDepthwiseConvolutionLayer3x3::validate(), CLDepthwiseConvolutionLayer3x3::validate(), NEGEMMLowpMatrixMultiplyCore::validate(), CLGenerateProposalsLayer::validate(), NEIm2ColKernel::validate(), CLGEMMLowpMatrixBReductionKernel::validate(), NEDeconvolutionLayer::validate(), CLGEMMDeconvolutionLayer::validate(), CLDirectDeconvolutionLayer::validate(), NEGEMMLowpOffsetContributionOutputStageKernel::validate(), NELogits1DSoftmaxKernel::validate(), CLComplexPixelWiseMultiplicationKernel::validate(), NEFullyConnectedLayer::validate(), CLFullyConnectedLayer::validate(), CLLSTMLayerQuantized::validate(), NELSTMLayerQuantized::validate(), NEGEMMLowpMatrixBReductionKernel::validate(), CLLogits1DMaxShiftExpSumKernel::validate(), CLSaturatedArithmeticOperationKernel::validate(), CLGEMMConvolutionLayer::validate(), NEComplexPixelWiseMultiplicationKernel::validate(), CLDepthwiseConvolutionLayer::validate(), CLArithmeticOperationKernel::validate(), CLLogits1DNormKernel::validate(), NEWinogradLayerTransformInputKernel< T, OutputTileRows, OutputTileCols, KernelRows, KernelCols >::validate(), NEDepthwiseConvolutionLayerOptimized::validate(), NEDepthwiseConvolutionLayer::validate(), NEWinogradLayerTransformOutputKernel< T, OutputTileRows, OutputTileCols, KernelRows, KernelCols >::validate(), NEWinogradLayerTransformWeightsKernel< T, OutputTileRows, OutputTileCols, KernelRows, KernelCols >::validate(), arm_compute::validate_and_configure_window(), and arm_compute::validate_config().
The documentation for this class was generated from the following file:
arm_compute/core/utils/misc/ICloneable.h