Compute Library: IImageLoader Class Reference
IImageLoader Class Reference abstract
Image loader interface.
#include <ImageLoader.h>
Public Member Functions
IImageLoader ()
Default Constructor.
virtual ~IImageLoader ()=default
Virtual base destructor.
unsigned int width () const
Return the width of the currently open image file.
unsigned int height () const
Return the height of the currently open image file.
virtual bool is_open ()=0
Return true if the image file is currently open.
virtual void open (const std::string &filename)=0
Open an image file and reads its metadata (Width, height)
virtual void close ()=0
Closes an image file.
template<typename T >
void init_image (T &image, Format format)
Initialise an image's metadata with the dimensions of the image file currently open.
template<typename T >
void fill_image (T &image)
Fill an image with the content of the currently open image file.
template<typename T >
void fill_planar_tensor (T &tensor, bool bgr=false)
Fill a tensor with 3 planes (one for each channel) with the content of the currently open image file.
Detailed Description
Image loader interface.
Definition at line 125 of file ImageLoader.h.
Constructor & Destructor Documentation
IImageLoader()
IImageLoader () inline
Default Constructor.
Definition at line 129 of file ImageLoader.h.
         : _feeder(nullptr), _width(0), _height(0)
     {
     }
~IImageLoader()
virtual ~IImageLoader () virtual default
Virtual base destructor.
Member Function Documentation
close()
virtual void close () pure virtual
Closes an image file.
Implemented in JPEGLoader, and PPMLoader.
fill_image()
void fill_image (T & image) inline
Fill an image with the content of the currently open image file.
Note
If the image is a CLImage, the function maps and unmaps the image
Parameters
[in,out] image Image to fill (Must be allocated, and of matching dimensions with the opened image file).
Definition at line 176 of file ImageLoader.h.
     {
         ARM_COMPUTE_ERROR_ON(!is_open());
         ARM_COMPUTE_ERROR_ON(image.info()->dimension(0) != _width || image.info()->dimension(1) != _height);
         ARM_COMPUTE_ERROR_ON_FORMAT_NOT_IN(&image, Format::U8, Format::RGB888);
         ARM_COMPUTE_ERROR_ON(_feeder.get() == nullptr);
         try
         {
             // Map buffer if creating a CLTensor/GCTensor
             map(image, true);
             // Validate feeding data
             validate_info(image.info());
             switch(image.info()->format())
             {
                 case Format::U8:
                 {
                     // We need to convert the data from RGB to grayscale:
                     // Iterate through every pixel of the image
                     Window window;
                     window.set(Window::DimX, Window::Dimension(0, _width, 1));
                     window.set(Window::DimY, Window::Dimension(0, _height, 1));
                     Iterator out(&image, window);
                     unsigned char red   = 0;
                     unsigned char green = 0;
                     unsigned char blue  = 0;
                     execute_window_loop(window, [&](const Coordinates & id)
                     {
                         red   = _feeder->get();
                         green = _feeder->get();
                         blue  = _feeder->get();
                         *out.ptr() = 0.2126f * red + 0.7152f * green + 0.0722f * blue;
                     },
                     out);
                     break;
                 }
                 case Format::RGB888:
                 {
                     // There is no format conversion needed: we can simply copy the content of the input file to the image one row at the time.
                     // Create a vertical window to iterate through the image's rows:
                     Window window;
                     window.set(Window::DimY, Window::Dimension(0, _height, 1));
                     Iterator out(&image, window);
                     size_t   row_size = _width * image.info()->element_size();
                     execute_window_loop(window, [&](const Coordinates & id)
                     {
                         _feeder->get_row(out.ptr(), row_size);
                     },
                     out);
                     break;
                 }
                 default:
                     ARM_COMPUTE_ERROR("Unsupported format");
             }
             // Unmap buffer if creating a CLTensor/GCTensor
             unmap(image);
         }
         catch(const std::ifstream::failure &e)
         {
             ARM_COMPUTE_ERROR("Loading image file: %s", e.what());
         }
     }
References ARM_COMPUTE_ERROR, ARM_COMPUTE_ERROR_ON, ARM_COMPUTE_ERROR_ON_FORMAT_NOT_IN, Window::DimX, Window::DimY, arm_compute::execute_window_loop(), IImageLoader::is_open(), arm_compute::utils::map(), Iterator::ptr(), arm_compute::RGB888, Window::set(), arm_compute::U8, and arm_compute::utils::unmap().
fill_planar_tensor()
void fill_planar_tensor (T & tensor, bool bgr = false) inline
Fill a tensor with 3 planes (one for each channel) with the content of the currently open image file.
Note
If the image is a CLImage, the function maps and unmaps the image
Parameters
[in,out] tensor Tensor with 3 planes to fill (Must be allocated, and of matching dimensions with the opened image). Data types supported: U8/F32
[in] bgr (Optional) Fill the first plane with blue channel (default = false)
Definition at line 256 of file ImageLoader.h.
     {
         ARM_COMPUTE_ERROR_ON(!is_open());
         ARM_COMPUTE_ERROR_ON_DATA_TYPE_CHANNEL_NOT_IN(&tensor, 1, DataType::U8, DataType::F32);
         const DataLayout  data_layout  = tensor.info()->data_layout();
         const TensorShape tensor_shape = tensor.info()->tensor_shape();
         ARM_COMPUTE_UNUSED(tensor_shape);
         ARM_COMPUTE_ERROR_ON(tensor_shape[get_data_layout_dimension_index(data_layout, DataLayoutDimension::WIDTH)] != _width);
         ARM_COMPUTE_ERROR_ON(tensor_shape[get_data_layout_dimension_index(data_layout, DataLayoutDimension::HEIGHT)] != _height);
         ARM_COMPUTE_ERROR_ON(tensor_shape[get_data_layout_dimension_index(data_layout, DataLayoutDimension::CHANNEL)] != 3);
         ARM_COMPUTE_ERROR_ON(_feeder.get() == nullptr);
         try
         {
             // Map buffer if creating a CLTensor
             map(tensor, true);
             // Validate feeding data
             validate_info(tensor.info());
             // Stride across channels
             size_t stride_z = 0;
             // Iterate through every pixel of the image
             Window window;
             if(data_layout == DataLayout::NCHW)
             {
                 window.set(Window::DimX, Window::Dimension(0, _width, 1));
                 window.set(Window::DimY, Window::Dimension(0, _height, 1));
                 window.set(Window::DimZ, Window::Dimension(0, 1, 1));
                 stride_z = tensor.info()->strides_in_bytes()[2];
             }
             else
             {
                 window.set(Window::DimX, Window::Dimension(0, 1, 1));
                 window.set(Window::DimY, Window::Dimension(0, _width, 1));
                 window.set(Window::DimZ, Window::Dimension(0, _height, 1));
                 stride_z = tensor.info()->strides_in_bytes()[0];
             }
             Iterator out(&tensor, window);
             unsigned char red   = 0;
             unsigned char green = 0;
             unsigned char blue  = 0;
             execute_window_loop(window, [&](const Coordinates & id)
             {
                 red   = _feeder->get();
                 green = _feeder->get();
                 blue  = _feeder->get();
                 switch(tensor.info()->data_type())
                 {
                     case DataType::U8:
                     {
                         *(out.ptr() + 0 * stride_z) = bgr ? blue : red;
                         *(out.ptr() + 1 * stride_z) = green;
                         *(out.ptr() + 2 * stride_z) = bgr ? red : blue;
                         break;
                     }
                     case DataType::F32:
                     {
                         *reinterpret_cast<float *>(out.ptr() + 0 * stride_z) = static_cast<float>(bgr ? blue : red);
                         *reinterpret_cast<float *>(out.ptr() + 1 * stride_z) = static_cast<float>(green);
                         *reinterpret_cast<float *>(out.ptr() + 2 * stride_z) = static_cast<float>(bgr ? red : blue);
                         break;
                     }
                     default:
                     {
                         ARM_COMPUTE_ERROR("Unsupported data type");
                     }
                 }
             },
             out);
             // Unmap buffer if creating a CLTensor
             unmap(tensor);
         }
         catch(const std::ifstream::failure &e)
         {
             ARM_COMPUTE_ERROR("Loading image file: %s", e.what());
         }
     }
References ARM_COMPUTE_ERROR, ARM_COMPUTE_ERROR_ON, ARM_COMPUTE_ERROR_ON_DATA_TYPE_CHANNEL_NOT_IN, ARM_COMPUTE_UNUSED, arm_compute::CHANNEL, arm_compute::test::validation::data_layout, Window::DimX, Window::DimY, Window::DimZ, arm_compute::execute_window_loop(), arm_compute::F32, arm_compute::get_data_layout_dimension_index(), arm_compute::HEIGHT, IImageLoader::is_open(), arm_compute::utils::map(), arm_compute::NCHW, Iterator::ptr(), Window::set(), arm_compute::U8, arm_compute::utils::unmap(), and arm_compute::WIDTH.
Referenced by ValidationInputAccessor::access_tensor().
height()
unsigned int height () const inline
Return the height of the currently open image file.
Definition at line 141 of file ImageLoader.h.
     {
         return _height;
     }
Referenced by ValidationInputAccessor::access_tensor(), and JPEGLoader::open().
init_image()
void init_image (T & image, Format format) inline
Initialise an image's metadata with the dimensions of the image file currently open.
Parameters
[out] image Image to initialise
[in] format Format to use for the image (Must be RGB888 or U8)
Definition at line 160 of file ImageLoader.h.
     {
         ARM_COMPUTE_ERROR_ON(!is_open());
         ARM_COMPUTE_ERROR_ON(format != Format::RGB888 && format != Format::U8);
         // Use the size of the input image
         TensorInfo image_info(_width, _height, format);
         image.allocator()->init(image_info);
     }
References ARM_COMPUTE_ERROR_ON, IImageLoader::is_open(), arm_compute::RGB888, and arm_compute::U8.
is_open()
virtual bool is_open () pure virtual
Return true if the image file is currently open.
Implemented in JPEGLoader, and PPMLoader.
Referenced by IImageLoader::fill_image(), IImageLoader::fill_planar_tensor(), and IImageLoader::init_image().
open()
virtual void open (const std::string & filename) pure virtual
Open an image file and reads its metadata (Width, height)
Parameters
[in] filename File to open
Implemented in JPEGLoader, and PPMLoader.
width()
unsigned int width () const inline
Return the width of the currently open image file.
Definition at line 136 of file ImageLoader.h.
     {
         return _width;
     }
Referenced by ValidationInputAccessor::access_tensor(), and JPEGLoader::open().
The documentation for this class was generated from the following file:
utils/ImageLoader.h