Compute Library: CLColorConvertKernel Class Reference
CLColorConvertKernel Class Reference
Interface for the color convert kernel.
#include <CLColorConvertKernel.h>
Public Member Functions
CLColorConvertKernel ()
Default constructor.
CLColorConvertKernel (const CLColorConvertKernel &)=delete
Prevent instances of this class from being copied (As this class contains pointers)
CLColorConvertKernel & operator= (const CLColorConvertKernel &)=delete
Prevent instances of this class from being copied (As this class contains pointers)
CLColorConvertKernel (CLColorConvertKernel &&)=default
Allow instances of this class to be moved.
CLColorConvertKernel & operator= (CLColorConvertKernel &&)=default
Allow instances of this class to be moved.
~CLColorConvertKernel ()=default
Default destructor.
void configure (const ICLTensor *input, ICLTensor *output)
Set the input and output of the kernel.
void configure (const ICLMultiImage *input, ICLImage *output)
Set the input and output of the kernel.
void configure (const ICLImage *input, ICLMultiImage *output)
Set the input and output of the kernel.
void configure (const ICLMultiImage *input, ICLMultiImage *output)
Set the input and output of the kernel.
void run (const Window &window, cl::CommandQueue &queue) override
Enqueue the OpenCL kernel to process the given window on the passed OpenCL command queue.
Public Member Functions inherited from ICLKernel
ICLKernel ()
Constructor.
cl::Kernel & kernel ()
Returns a reference to the OpenCL kernel of this object.
template<typename T >
void add_1D_array_argument (unsigned int &idx, const ICLArray< T > *array, const Strides &strides, unsigned int num_dimensions, const Window &window)
Add the passed 1D array's parameters to the object's kernel's arguments starting from the index idx.
void add_1D_tensor_argument (unsigned int &idx, const ICLTensor *tensor, const Window &window)
Add the passed 1D tensor's parameters to the object's kernel's arguments starting from the index idx.
void add_1D_tensor_argument_if (bool cond, unsigned int &idx, const ICLTensor *tensor, const Window &window)
Add the passed 1D tensor's parameters to the object's kernel's arguments starting from the index idx if the condition is true.
void add_2D_tensor_argument (unsigned int &idx, const ICLTensor *tensor, const Window &window)
Add the passed 2D tensor's parameters to the object's kernel's arguments starting from the index idx.
void add_2D_tensor_argument_if (bool cond, unsigned int &idx, const ICLTensor *tensor, const Window &window)
Add the passed 2D tensor's parameters to the object's kernel's arguments starting from the index idx if the condition is true.
void add_3D_tensor_argument (unsigned int &idx, const ICLTensor *tensor, const Window &window)
Add the passed 3D tensor's parameters to the object's kernel's arguments starting from the index idx.
void add_4D_tensor_argument (unsigned int &idx, const ICLTensor *tensor, const Window &window)
Add the passed 4D tensor's parameters to the object's kernel's arguments starting from the index idx.
template<typename T >
void add_argument (unsigned int &idx, T value)
Add the passed parameters to the object's kernel's arguments starting from the index idx.
void set_lws_hint (const cl::NDRange &lws_hint)
Set the Local-Workgroup-Size hint.
cl::NDRange lws_hint () const
Return the Local-Workgroup-Size hint.
const std::string & config_id () const
Get the configuration ID.
void set_target (GPUTarget target)
Set the targeted GPU architecture.
void set_target (cl::Device &device)
Set the targeted GPU architecture according to the CL device.
GPUTarget get_target () const
Get the targeted GPU architecture.
size_t get_max_workgroup_size ()
Get the maximum workgroup size for the device the CLKernelLibrary uses.
template<typename T , unsigned int dimension_size>
void add_array_argument (unsigned &idx, const ICLArray< T > *array, const Strides &strides, unsigned int num_dimensions, const Window &window)
Add the passed array's parameters to the object's kernel's arguments starting from the index idx.
template<unsigned int dimension_size>
void add_tensor_argument (unsigned &idx, const ICLTensor *tensor, const Window &window)
Public Member Functions inherited from IKernel
IKernel ()
Constructor.
virtual ~IKernel ()=default
Destructor.
virtual bool is_parallelisable () const
Indicates whether or not the kernel is parallelisable.
virtual BorderSize border_size () const
The size of the border for that kernel.
const Window & window () const
The maximum window the kernel can be executed on.
Additional Inherited Members
Static Public Member Functions inherited from ICLKernel
static constexpr unsigned int num_arguments_per_1D_array ()
Returns the number of arguments enqueued per 1D array object.
static constexpr unsigned int num_arguments_per_1D_tensor ()
Returns the number of arguments enqueued per 1D tensor object.
static constexpr unsigned int num_arguments_per_2D_tensor ()
Returns the number of arguments enqueued per 2D tensor object.
static constexpr unsigned int num_arguments_per_3D_tensor ()
Returns the number of arguments enqueued per 3D tensor object.
static constexpr unsigned int num_arguments_per_4D_tensor ()
Returns the number of arguments enqueued per 4D tensor object.
static cl::NDRange gws_from_window (const Window &window)
Get the global work size given an execution window.
Detailed Description
Interface for the color convert kernel.
Definition at line 38 of file CLColorConvertKernel.h.
Constructor & Destructor Documentation
CLColorConvertKernel() [1/3]
CLColorConvertKernel ()
Default constructor.
Definition at line 43 of file CLColorConvertKernel.cpp.
     : _input(nullptr), _output(nullptr), _multi_input(nullptr), _multi_output(nullptr)
 {
 }
CLColorConvertKernel() [2/3]
CLColorConvertKernel (const CLColorConvertKernel &) delete
Prevent instances of this class from being copied (As this class contains pointers)
CLColorConvertKernel() [3/3]
CLColorConvertKernel (CLColorConvertKernel &&) default
Allow instances of this class to be moved.
~CLColorConvertKernel()
~CLColorConvertKernel () default
Default destructor.
Member Function Documentation
configure() [1/4]
void configure (const ICLTensor * input, ICLTensor * output)
Set the input and output of the kernel.
Parameters
[in] input Source tensor. Formats supported: RGBA8888/UYVY422/YUYV422/RGB888
[out] output Destination tensor. Formats supported: RGB888 (if the formats of input are RGBA8888/UYVY422/YUYV422), RGBA8888 (if the formats of input are UYVY422/YUYV422/RGB888/), U8 (if the formats of input is RGB888)
Definition at line 48 of file CLColorConvertKernel.cpp.
 {
     ARM_COMPUTE_ERROR_ON(input == nullptr);
     ARM_COMPUTE_ERROR_ON(output == nullptr);
     unsigned int num_elems_processed_per_iteration = 0;
     switch(input->info()->format())
     {
         case Format::RGBA8888:
         {
             switch(output->info()->format())
             {
                 case Format::RGB888:
                     num_elems_processed_per_iteration = 16;
                     break;
                 default:
                     ARM_COMPUTE_ERROR("Not supported");
                     break;
             }
             break;
         }
         case Format::UYVY422:
         case Format::YUYV422:
         {
             switch(output->info()->format())
             {
                 case Format::RGB888:
                 case Format::RGBA8888:
                     num_elems_processed_per_iteration = 8;
                     break;
                 default:
                     ARM_COMPUTE_ERROR("Not supported");
                     break;
             }
             break;
         }
         case Format::RGB888:
         {
             switch(output->info()->format())
             {
                 case Format::RGBA8888:
                 case Format::U8:
                     num_elems_processed_per_iteration = 16;
                     break;
                 default:
                     ARM_COMPUTE_ERROR("Not supported");
                     break;
             }
             break;
         }
         default:
             break;
     }
     ARM_COMPUTE_ERROR_ON_MSG(num_elems_processed_per_iteration == 0, "Conversion from %s to %s not supported",
                              string_from_format(input->info()->format()).c_str(),
                              string_from_format(output->info()->format()).c_str());
     std::stringstream kernel_name;
     kernel_name << string_from_format(input->info()->format());
     kernel_name << "_to_";
     kernel_name << string_from_format(output->info()->format());
     kernel_name << "_bt709";
     _input  = input;
     _output = output;
     // Create kernel
     _kernel = static_cast<cl::Kernel>(CLKernelLibrary::get().create_kernel(kernel_name.str()));
     // Configure kernel window
     Window                 win = calculate_max_window(*input->info(), Steps(num_elems_processed_per_iteration));
     AccessWindowHorizontal input_access(input->info(), 0, num_elems_processed_per_iteration);
     AccessWindowHorizontal output_access(output->info(), 0, num_elems_processed_per_iteration);
     update_window_and_padding(win, input_access, output_access);
     output_access.set_valid_region(win, input->info()->valid_region());
     ICLKernel::configure_internal(win);
     // Set config_id for enabling LWS tuning
     _config_id = kernel_name.str();
     _config_id += "_";
     _config_id += lower_string(string_from_data_type(input->info()->data_type()));
     _config_id += "_";
     _config_id += support::cpp11::to_string(input->info()->dimension(0));
     _config_id += "_";
     _config_id += support::cpp11::to_string(input->info()->dimension(1));
 }
References ARM_COMPUTE_ERROR, ARM_COMPUTE_ERROR_ON, ARM_COMPUTE_ERROR_ON_MSG, arm_compute::calculate_max_window(), arm_compute::create_kernel(), ITensorInfo::data_type(), ITensorInfo::dimension(), ITensorInfo::format(), CLKernelLibrary::get(), ITensor::info(), arm_compute::lower_string(), arm_compute::RGB888, arm_compute::RGBA8888, arm_compute::string_from_data_type(), arm_compute::string_from_format(), arm_compute::support::cpp11::to_string(), arm_compute::U8, arm_compute::update_window_and_padding(), arm_compute::UYVY422, ITensorInfo::valid_region(), and arm_compute::YUYV422.
configure() [2/4]
void configure (const ICLMultiImage * input, ICLImage * output)
Set the input and output of the kernel.
Parameters
[in] input Multi-planar source image. Formats supported: NV12/NV21/IYUV
[out] output Single-planar destination image. Formats supported: RGB888/RGBA8888
Definition at line 139 of file CLColorConvertKernel.cpp.
 {
     ARM_COMPUTE_ERROR_ON_TENSOR_NOT_2D(output);
     ARM_COMPUTE_ERROR_ON(output == nullptr);
     unsigned int num_elems_processed_per_iteration = 0;
     switch(input->info()->format())
     {
         case Format::NV12:
         case Format::NV21:
         case Format::IYUV:
         {
             switch(output->info()->format())
             {
                 case Format::RGB888:
                 case Format::RGBA8888:
                     num_elems_processed_per_iteration = 4;
                     break;
                 default:
                     ARM_COMPUTE_ERROR("Not supported");
                     break;
             }
             break;
         }
         default:
             break;
     }
     ARM_COMPUTE_ERROR_ON_MSG(num_elems_processed_per_iteration == 0, "Conversion from %s to %s not supported",
                              string_from_format(input->info()->format()).c_str(),
                              string_from_format(output->info()->format()).c_str());
     std::stringstream kernel_name;
     kernel_name << string_from_format(input->info()->format());
     kernel_name << "_to_";
     kernel_name << string_from_format(output->info()->format());
     kernel_name << "_bt709";
     _multi_input = input;
     _output      = output;
     // Create kernel
     _kernel = static_cast<cl::Kernel>(CLKernelLibrary::get().create_kernel(kernel_name.str()));
     // Configure kernel window
     const bool  has_two_planes = (input->info()->format() == Format::NV12) || (input->info()->format() == Format::NV21);
     const float sub_sampling   = (has_two_planes || (input->info()->format() == Format::IYUV)) ? 0.5f : 1;
     Window win = calculate_max_window(*output->info(), Steps(num_elems_processed_per_iteration));
     win.set_dimension_step(Window::DimY, 2);
     AccessWindowHorizontal plane0_access(input->plane(0)->info(), 0, num_elems_processed_per_iteration);
     AccessWindowRectangle  plane1_access(input->plane(1)->info(), 0, 0, num_elems_processed_per_iteration, 1,
                                          sub_sampling, sub_sampling);
     AccessWindowRectangle plane2_access(has_two_planes ? nullptr : input->plane(2)->info(), 0, 0, num_elems_processed_per_iteration, 1,
                                         sub_sampling, sub_sampling);
     AccessWindowHorizontal output_access(output->info(), 0, num_elems_processed_per_iteration);
     update_window_and_padding(win,
                               plane0_access, plane1_access, plane2_access,
                               output_access);
     ValidRegion intersect_region = intersect_valid_regions(input->plane(0)->info()->valid_region(), input->plane(1)->info()->valid_region(),
                                                            input->plane(2)->info()->valid_region());
     output_access.set_valid_region(win, ValidRegion(intersect_region.anchor, output->info()->tensor_shape()));
     ICLKernel::configure_internal(win);
     // Set config_id for enabling LWS tuning
     _config_id = kernel_name.str();
     _config_id += "_";
     _config_id += lower_string(string_from_data_type(input->plane(0)->info()->data_type()));
     _config_id += "_";
     _config_id += support::cpp11::to_string(input->plane(0)->info()->dimension(0));
     _config_id += "_";
     _config_id += support::cpp11::to_string(input->plane(0)->info()->dimension(1));
     _config_id += "_";
     _config_id += lower_string(string_from_data_type(input->plane(1)->info()->data_type()));
     _config_id += "_";
     _config_id += support::cpp11::to_string(input->plane(1)->info()->dimension(0));
     _config_id += "_";
     _config_id += support::cpp11::to_string(input->plane(1)->info()->dimension(1));
 }
References ValidRegion::anchor, ARM_COMPUTE_ERROR, ARM_COMPUTE_ERROR_ON, ARM_COMPUTE_ERROR_ON_MSG, ARM_COMPUTE_ERROR_ON_TENSOR_NOT_2D, arm_compute::calculate_max_window(), arm_compute::create_kernel(), ITensorInfo::data_type(), ITensorInfo::dimension(), Window::DimY, MultiImageInfo::format(), ITensorInfo::format(), CLKernelLibrary::get(), ITensor::info(), IMultiImage::info(), arm_compute::intersect_valid_regions(), arm_compute::IYUV, arm_compute::lower_string(), arm_compute::NV12, arm_compute::NV21, ICLMultiImage::plane(), arm_compute::RGB888, arm_compute::RGBA8888, Window::set_dimension_step(), arm_compute::string_from_data_type(), arm_compute::string_from_format(), ITensorInfo::tensor_shape(), arm_compute::support::cpp11::to_string(), arm_compute::update_window_and_padding(), and ITensorInfo::valid_region().
configure() [3/4]
void configure (const ICLImage * input, ICLMultiImage * output)
Set the input and output of the kernel.
Parameters
[in] input Single-planar source image. Formats supported: RGB888/RGBA8888/UYVY422/YUYV422
[out] output Multi-planar destination image. Formats supported: NV12/IYUV/YUV444 (if the formats of input are RGB888/RGB8888)
Definition at line 224 of file CLColorConvertKernel.cpp.
 {
     ARM_COMPUTE_ERROR_ON_TENSOR_NOT_2D(input);
     ARM_COMPUTE_ERROR_ON(output == nullptr);
     unsigned int num_elems_processed_per_iteration = 0;
     unsigned int num_elems_read_per_iteration_x    = 0;
     bool  has_two_planes = (output->info()->format() == Format::NV12) || (output->info()->format() == Format::NV21);
     float sub_sampling   = (has_two_planes || (output->info()->format() == Format::IYUV)) ? 0.5f : 1;
     switch(input->info()->format())
     {
         case Format::RGB888:
         case Format::RGBA8888:
         {
             switch(output->info()->format())
             {
                 case Format::NV12:
                 case Format::IYUV:
                     num_elems_processed_per_iteration = 2;
                     num_elems_read_per_iteration_x    = 8;
                     break;
                 case Format::YUV444:
                     num_elems_processed_per_iteration = 4;
                     num_elems_read_per_iteration_x    = 16;
                     break;
                 default:
                     ARM_COMPUTE_ERROR("Not supported");
                     break;
             }
             break;
         }
         case Format::UYVY422:
         case Format::YUYV422:
         {
             switch(output->info()->format())
             {
                 case Format::NV12:
                 case Format::IYUV:
                     num_elems_processed_per_iteration = 8;
                     num_elems_read_per_iteration_x    = 8;
                     break;
                 default:
                     ARM_COMPUTE_ERROR("Not supported");
                     break;
             }
             break;
         }
         default:
             break;
     }
     ARM_COMPUTE_ERROR_ON_MSG(num_elems_processed_per_iteration == 0, "Conversion from %s to %s not supported",
                              string_from_format(input->info()->format()).c_str(),
                              string_from_format(output->info()->format()).c_str());
     std::stringstream kernel_name;
     kernel_name << string_from_format(input->info()->format());
     kernel_name << "_to_";
     kernel_name << string_from_format(output->info()->format());
     kernel_name << "_bt709";
     _input        = input;
     _multi_output = output;
     // Create kernel
     _kernel = static_cast<cl::Kernel>(CLKernelLibrary::get().create_kernel(kernel_name.str()));
     // Configure kernel window
     Window win = calculate_max_window(*input->info(), Steps(num_elems_processed_per_iteration));
     if((input->info()->format() != Format::RGB888 || output->info()->format() != Format::YUV444) && (input->info()->format() != Format::RGBA8888 || output->info()->format() != Format::YUV444))
     {
         win.set_dimension_step(Window::DimY, 2);
     }
     AccessWindowHorizontal output_plane0_access(output->plane(0)->info(), 0, num_elems_processed_per_iteration);
     AccessWindowRectangle  output_plane1_access(output->plane(1)->info(), 0, 0, num_elems_processed_per_iteration, 1, sub_sampling, sub_sampling);
     AccessWindowRectangle  output_plane2_access(has_two_planes ? nullptr : output->plane(2)->info(), 0, 0,
                                                 num_elems_processed_per_iteration, 1, sub_sampling, sub_sampling);
     AccessWindowHorizontal input_access(input->info(), 0, num_elems_read_per_iteration_x);
     update_window_and_padding(win,
                               input_access,
                               output_plane0_access,
                               output_plane1_access,
                               output_plane2_access);
     ValidRegion input_region = input->info()->valid_region();
     output_plane0_access.set_valid_region(win, ValidRegion(input_region.anchor, output->plane(0)->info()->tensor_shape()));
     output_plane1_access.set_valid_region(win, ValidRegion(input_region.anchor, output->plane(1)->info()->tensor_shape()));
     output_plane2_access.set_valid_region(win, ValidRegion(input_region.anchor, output->plane(2)->info()->tensor_shape()));
     ICLKernel::configure_internal(win);
     // Set config_id for enabling LWS tuning
     _config_id = kernel_name.str();
     _config_id += "_";
     _config_id += lower_string(string_from_data_type(input->info()->data_type()));
     _config_id += "_";
     _config_id += support::cpp11::to_string(input->info()->dimension(0));
     _config_id += "_";
     _config_id += support::cpp11::to_string(input->info()->dimension(1));
 }
References ValidRegion::anchor, ARM_COMPUTE_ERROR, ARM_COMPUTE_ERROR_ON, ARM_COMPUTE_ERROR_ON_MSG, ARM_COMPUTE_ERROR_ON_TENSOR_NOT_2D, arm_compute::calculate_max_window(), arm_compute::create_kernel(), ITensorInfo::data_type(), ITensorInfo::dimension(), Window::DimY, MultiImageInfo::format(), ITensorInfo::format(), CLKernelLibrary::get(), ITensor::info(), IMultiImage::info(), arm_compute::IYUV, arm_compute::lower_string(), arm_compute::NV12, arm_compute::NV21, ICLMultiImage::plane(), arm_compute::RGB888, arm_compute::RGBA8888, Window::set_dimension_step(), arm_compute::string_from_data_type(), arm_compute::string_from_format(), ITensorInfo::tensor_shape(), arm_compute::support::cpp11::to_string(), arm_compute::update_window_and_padding(), arm_compute::UYVY422, ITensorInfo::valid_region(), arm_compute::YUV444, and arm_compute::YUYV422.
configure() [4/4]
void configure (const ICLMultiImage * input, ICLMultiImage * output)
Set the input and output of the kernel.
Parameters
[in] input Multi-planar source image. Formats supported: NV12/NV21/IYUV
[out] output Multi-planar destination image. Formats supported: YUV444/IYUV (if the formats of input are NV12/NV21)/NV12 (if the format of input is IYUV)
Definition at line 331 of file CLColorConvertKernel.cpp.
 {
     unsigned int num_elems_processed_per_iteration = 0;
     switch(input->info()->format())
     {
         case Format::NV12:
         case Format::NV21:
         {
             switch(output->info()->format())
             {
                 case Format::IYUV:
                 case Format::YUV444:
                     num_elems_processed_per_iteration = 16;
                     break;
                 default:
                     ARM_COMPUTE_ERROR("Not supported");
                     break;
             }
             break;
         }
         case Format::IYUV:
         {
             switch(output->info()->format())
             {
                 case Format::YUV444:
                 case Format::NV12:
                     num_elems_processed_per_iteration = 16;
                     break;
                 default:
                     ARM_COMPUTE_ERROR("Not supported");
                     break;
             }
             break;
         }
         default:
             break;
     }
     ARM_COMPUTE_ERROR_ON_MSG(num_elems_processed_per_iteration == 0, "Conversion from %s to %s not supported",
                              string_from_format(input->info()->format()).c_str(),
                              string_from_format(output->info()->format()).c_str());
     std::stringstream kernel_name;
     kernel_name << string_from_format(input->info()->format());
     kernel_name << "_to_";
     kernel_name << string_from_format(output->info()->format());
     kernel_name << "_bt709";
     _multi_input  = input;
     _multi_output = output;
     // Create kernel
     bool has_two_input_planars  = (input->info()->format() == Format::NV12) || (input->info()->format() == Format::NV21);
     bool has_two_output_planars = (output->info()->format() == Format::NV12) || (output->info()->format() == Format::NV21);
     float sub_sampling_input  = (has_two_input_planars || (input->info()->format() == Format::IYUV)) ? 0.5f : 1;
     float sub_sampling_output = (has_two_output_planars || (output->info()->format() == Format::IYUV)) ? 0.5f : 1;
     _kernel = static_cast<cl::Kernel>(CLKernelLibrary::get().create_kernel(kernel_name.str()));
     Window win = calculate_max_window(*input->cl_plane(0)->info(), Steps(num_elems_processed_per_iteration));
     win.set_dimension_step(Window::DimY, 2);
     AccessWindowHorizontal input_plane0_access(input->plane(0)->info(), 0, num_elems_processed_per_iteration);
     AccessWindowRectangle  input_plane1_access(input->plane(1)->info(), 0, 0, num_elems_processed_per_iteration, 1,
                                                sub_sampling_input, sub_sampling_input);
     AccessWindowRectangle input_plane2_access(has_two_input_planars ? nullptr : input->plane(2)->info(), 0, 0, num_elems_processed_per_iteration, 1,
                                               sub_sampling_input, sub_sampling_input);
     AccessWindowHorizontal output_plane0_access(output->plane(0)->info(), 0, num_elems_processed_per_iteration);
     AccessWindowRectangle  output_plane1_access(output->plane(1)->info(), 0, 0, num_elems_processed_per_iteration, 1, sub_sampling_output, sub_sampling_output);
     AccessWindowRectangle  output_plane2_access(has_two_output_planars ? nullptr : output->plane(2)->info(), 0, 0,
                                                 num_elems_processed_per_iteration, 1, sub_sampling_output, sub_sampling_output);
     update_window_and_padding(win,
                               input_plane0_access, input_plane1_access, input_plane2_access,
                               output_plane0_access, output_plane1_access, output_plane2_access);
     ValidRegion intersect_region = intersect_valid_regions(input->plane(0)->info()->valid_region(), input->plane(1)->info()->valid_region(),
                                                            input->plane(2)->info()->valid_region());
     output_plane0_access.set_valid_region(win, ValidRegion(intersect_region.anchor, output->plane(0)->info()->tensor_shape()));
     output_plane1_access.set_valid_region(win, ValidRegion(intersect_region.anchor, output->plane(1)->info()->tensor_shape()));
     output_plane2_access.set_valid_region(win, ValidRegion(intersect_region.anchor, output->plane(2)->info()->tensor_shape()));
     ICLKernel::configure_internal(win);
     // Set config_id for enabling LWS tuning
     _config_id = kernel_name.str();
     _config_id += "_";
     _config_id += lower_string(string_from_data_type(input->plane(0)->info()->data_type()));
     _config_id += "_";
     _config_id += support::cpp11::to_string(input->plane(0)->info()->dimension(0));
     _config_id += "_";
     _config_id += support::cpp11::to_string(input->plane(0)->info()->dimension(1));
     _config_id += "_";
     _config_id += lower_string(string_from_data_type(input->plane(1)->info()->data_type()));
     _config_id += "_";
     _config_id += support::cpp11::to_string(input->plane(1)->info()->dimension(0));
     _config_id += "_";
     _config_id += support::cpp11::to_string(input->plane(1)->info()->dimension(1));
 }
References ValidRegion::anchor, ARM_COMPUTE_ERROR, ARM_COMPUTE_ERROR_ON_MSG, arm_compute::calculate_max_window(), ICLMultiImage::cl_plane(), arm_compute::create_kernel(), ITensorInfo::data_type(), ITensorInfo::dimension(), Window::DimY, MultiImageInfo::format(), CLKernelLibrary::get(), IMultiImage::info(), ITensor::info(), arm_compute::intersect_valid_regions(), arm_compute::IYUV, arm_compute::lower_string(), arm_compute::NV12, arm_compute::NV21, ICLMultiImage::plane(), Window::set_dimension_step(), arm_compute::string_from_data_type(), arm_compute::string_from_format(), ITensorInfo::tensor_shape(), arm_compute::support::cpp11::to_string(), arm_compute::update_window_and_padding(), ITensorInfo::valid_region(), and arm_compute::YUV444.
operator=() [1/2]
CLColorConvertKernel& operator= (const CLColorConvertKernel &) delete
Prevent instances of this class from being copied (As this class contains pointers)
operator=() [2/2]
CLColorConvertKernel& operator= (CLColorConvertKernel &&) default
Allow instances of this class to be moved.
run()
void run (const Window & window, cl::CommandQueue & queue) override virtual
Enqueue the OpenCL kernel to process the given window on the passed OpenCL command queue.
Note
The queue is not flushed by this method, and therefore the kernel will not have been executed by the time this method returns.
Parameters
[in] window Region on which to execute the kernel. (Must be a valid region of the window returned by window()).
[in,out] queue Command queue on which to enqueue the kernel.
Implements ICLKernel.
Definition at line 432 of file CLColorConvertKernel.cpp.
 {
     ARM_COMPUTE_ERROR_ON_UNCONFIGURED_KERNEL(this);
     ARM_COMPUTE_ERROR_ON_INVALID_SUBWINDOW(ICLKernel::window(), window);
     Window slice = window.first_slice_window_2D();
     if(nullptr != _input && nullptr != _output)
     {
         do
         {
             unsigned int idx = 0;
             add_2D_tensor_argument(idx, _input, slice);
             add_2D_tensor_argument(idx, _output, slice);
             enqueue(queue, *this, slice, lws_hint());
         }
         while(window.slide_window_slice_2D(slice));
     }
     else if(nullptr != _input && nullptr != _multi_output)
     {
         Format format = _multi_output->info()->format();
         do
         {
             Window win_uv(slice);
             if((Format::NV12 == format) || (Format::NV21 == format) || (Format::IYUV == format))
             {
                 win_uv.set(Window::DimX, Window::Dimension(win_uv.x().start() / 2, win_uv.x().end() / 2, win_uv.x().step() / 2));
                 win_uv.set(Window::DimY, Window::Dimension(win_uv.y().start() / 2, win_uv.y().end() / 2, 1));
             }
             unsigned int idx = 0;
             add_2D_tensor_argument(idx, _input, slice);
             add_2D_tensor_argument(idx, _multi_output->cl_plane(0), slice);
             for(int i = 1; i < 3 && (0 != _multi_output->cl_plane(i)->info()->num_dimensions()); ++i)
             {
                 add_2D_tensor_argument(idx, _multi_output->cl_plane(i), win_uv);
             }
             enqueue(queue, *this, slice, lws_hint());
         }
         while(window.slide_window_slice_2D(slice));
     }
     else if(nullptr != _multi_input && nullptr != _output)
     {
         Format format = _multi_input->info()->format();
         do
         {
             Window win_uv(slice);
             if((Format::NV12 == format) || (Format::NV21 == format) || (Format::IYUV == format))
             {
                 win_uv.set(Window::DimX, Window::Dimension(win_uv.x().start() / 2, win_uv.x().end() / 2, win_uv.x().step() / 2));
                 win_uv.set(Window::DimY, Window::Dimension(win_uv.y().start() / 2, win_uv.y().end() / 2, 1));
             }
             unsigned int idx = 0;
             add_2D_tensor_argument(idx, _multi_input->cl_plane(0), slice);
             for(int i = 1; i < 3 && (0 != _multi_input->cl_plane(i)->info()->num_dimensions()); ++i)
             {
                 add_2D_tensor_argument(idx, _multi_input->cl_plane(i), win_uv);
             }
             add_2D_tensor_argument(idx, _output, slice);
             enqueue(queue, *this, slice, lws_hint());
         }
         while(window.slide_window_slice_2D(slice));
     }
     else if(nullptr != _multi_input && nullptr != _multi_output)
     {
         Format in_format  = _multi_input->info()->format();
         Format out_format = _multi_output->info()->format();
         do
         {
             Window win_in_uv(slice);
             if((Format::NV12 == in_format) || (Format::NV21 == in_format) || (Format::IYUV == in_format))
             {
                 win_in_uv.set(Window::DimX, Window::Dimension(win_in_uv.x().start() / 2,
                                                               win_in_uv.x().end() / 2, win_in_uv.x().step() / 2));
                 win_in_uv.set(Window::DimY, Window::Dimension(win_in_uv.y().start() / 2, win_in_uv.y().end() / 2, 1));
             }
             unsigned int idx = 0;
             add_2D_tensor_argument(idx, _multi_input->cl_plane(0), slice);
             for(int i = 1; i < 3 && (0 != _multi_input->cl_plane(i)->info()->num_dimensions()); ++i)
             {
                 add_2D_tensor_argument(idx, _multi_input->cl_plane(i), win_in_uv);
             }
             Window win_out_uv(slice);
             if((Format::NV12 == out_format) || (Format::NV21 == out_format) || (Format::IYUV == out_format))
             {
                 win_out_uv.set(Window::DimX, Window::Dimension(win_out_uv.x().start() / 2,
                                                                win_out_uv.x().end() / 2, win_out_uv.x().step() / 2));
                 win_out_uv.set(Window::DimY, Window::Dimension(win_out_uv.y().start() / 2, win_out_uv.y().end() / 2, 1));
             }
             add_2D_tensor_argument(idx, _multi_output->cl_plane(0), slice);
             for(int i = 1; i < 3 && (0 != _multi_output->cl_plane(i)->info()->num_dimensions()); ++i)
             {
                 add_2D_tensor_argument(idx, _multi_output->cl_plane(i), win_out_uv);
             }
             enqueue(queue, *this, slice, lws_hint());
         }
         while(window.slide_window_slice_2D(slice));
     }
     else
     {
         ARM_COMPUTE_ERROR("Not supported");
     }
 }
References ICLKernel::add_2D_tensor_argument(), ARM_COMPUTE_ERROR, ARM_COMPUTE_ERROR_ON_INVALID_SUBWINDOW, ARM_COMPUTE_ERROR_ON_UNCONFIGURED_KERNEL, ICLMultiImage::cl_plane(), Window::DimX, Window::DimY, Window::Dimension::end(), arm_compute::enqueue(), Window::first_slice_window_2D(), MultiImageInfo::format(), IMultiImage::info(), ITensor::info(), arm_compute::IYUV, ICLKernel::lws_hint(), ITensorInfo::num_dimensions(), arm_compute::NV12, arm_compute::NV21, Window::set(), arm_compute::test::validation::reference::slice(), Window::slide_window_slice_2D(), Window::Dimension::start(), Window::Dimension::step(), IKernel::window(), Window::x(), and Window::y().
The documentation for this class was generated from the following files:
arm_compute/core/CL/kernels/CLColorConvertKernel.h
src/core/CL/kernels/CLColorConvertKernel.cpp