Compute Library: NEGatherKernel Class Reference
NEGatherKernel Class Reference
Kernel to perform other operation on NEON.
#include <NEGatherKernel.h>
Public Member Functions
NEGatherKernel ()
Default constructor.
NEGatherKernel (const NEGatherKernel &)=delete
Prevent instances of this class from being copied (As this class contains pointers).
NEGatherKernel & operator= (const NEGatherKernel &)=delete
Prevent instances of this class from being copied (As this class contains pointers).
NEGatherKernel (NEGatherKernel &&)=default
Allow instances of this class to be moved.
NEGatherKernel & operator= (NEGatherKernel &&)=default
Allow instances of this class to be moved.
~NEGatherKernel ()=default
Default detructor.
const char * name () const override
Name of the kernel.
void configure (const ITensor *input, const ITensor *indices, ITensor *output, int axis=0)
Initialise the kernel's inputs and outputs.
void run (const Window &window, const ThreadInfo &info) override
Execute the kernel on the passed window.
Public Member Functions inherited from ICPPKernel
virtual ~ICPPKernel ()=default
Default destructor.
Public Member Functions inherited from IKernel
IKernel ()
Constructor.
virtual ~IKernel ()=default
Destructor.
virtual bool is_parallelisable () const
Indicates whether or not the kernel is parallelisable.
virtual BorderSize border_size () const
The size of the border for that kernel.
const Window & window () const
The maximum window the kernel can be executed on.
Static Public Member Functions
static Status validate (const ITensorInfo *input, const ITensorInfo *indices, const ITensorInfo *output, int axis)
Static function to check if given info will lead to a valid configuration of NEGatherKernel.
Detailed Description
Kernel to perform other operation on NEON.
Definition at line 36 of file NEGatherKernel.h.
Constructor & Destructor Documentation
NEGatherKernel() [1/3]
NEGatherKernel ()
Default constructor.
Definition at line 57 of file NEGatherKernel.cpp.
     : _input{}, _indices{}, _axis{}, _output{}, _func{}
 {
 }
NEGatherKernel() [2/3]
NEGatherKernel (const NEGatherKernel &) delete
Prevent instances of this class from being copied (As this class contains pointers).
NEGatherKernel() [3/3]
NEGatherKernel (NEGatherKernel &&) default
Allow instances of this class to be moved.
~NEGatherKernel()
~NEGatherKernel () default
Default detructor.
Member Function Documentation
configure()
void configure (const ITensor * input, const ITensor * indices, ITensor * output, int axis = 0)
Initialise the kernel's inputs and outputs.
Parameters
[in] input Source tensor. Supported tensor rank: up to 4. Data type supported: U8/S8/QASYMM8/U16/S16/U32/S32/F16/F32
[in] indices Indices tensor. Supported tensor rank: up to 1. Must be one of the following type: U32/S32. Each value Must be in range [0, input.shape[axis])
[out] output Destination tensor. Data type supported: Same as input
[in] axis (Optional) The axis in input to gather indices from. Negative values wrap around. Defaults to 0
Definition at line 107 of file NEGatherKernel.cpp.
 {
     ARM_COMPUTE_ERROR_ON_NULLPTR(input, output, indices);
     ARM_COMPUTE_ERROR_ON(indices->info()->num_dimensions() != 1);
     ARM_COMPUTE_ERROR_ON_DATA_TYPE_CHANNEL_NOT_IN(indices, 1, DataType::U32, DataType::S32);
     ARM_COMPUTE_ERROR_ON_DATA_TYPE_CHANNEL_NOT_IN(input, 1, DataType::U8, DataType::S8, DataType::QASYMM8, DataType::U16, DataType::S16, DataType::U32, DataType::S32, DataType::F16, DataType::F32);
     _input   = input;
     _indices = indices;
     _output  = output;
     _axis    = axis;
     if(_axis < 0)
     {
         _axis += input->info()->num_dimensions();
     }
     ARM_COMPUTE_ERROR_ON(0 > _axis || _axis >= static_cast<int32_t>(input->info()->num_dimensions()));
     if(0 == _axis)
     {
         switch(_indices->info()->data_type())
         {
             case DataType::U32:
                 _func = &NEGatherKernel::gather_0_axis<uint32_t>;
                 break;
             case DataType::S32:
                 _func = &NEGatherKernel::gather_0_axis<int32_t>;
                 break;
             default:
                 ARM_COMPUTE_ERROR("Not supported");
                 break;
         }
     }
     else
     {
         switch(_indices->info()->data_type())
         {
             case DataType::U32:
                 _func = &NEGatherKernel::gather_n_axis<uint32_t>;
                 break;
             case DataType::S32:
                 _func = &NEGatherKernel::gather_n_axis<int32_t>;
                 break;
             default:
                 ARM_COMPUTE_ERROR("Not supported");
                 break;
         }
     }
     // Output auto initialization if not yet initialized
     TensorShape output_shape = arm_compute::misc::shape_calculator::compute_gather_shape(input->info()->tensor_shape(), indices->info()->tensor_shape(), _axis);
     auto_init_if_empty(*output->info(), output_shape, 1, input->info()->data_type());
     // Create window
     Window win = calculate_max_window(*output->info(), Steps());
     output->info()->set_valid_region(ValidRegion(Coordinates(), output->info()->tensor_shape()));
     INEKernel::configure(win);
 }
References ARM_COMPUTE_ERROR, ARM_COMPUTE_ERROR_ON, ARM_COMPUTE_ERROR_ON_DATA_TYPE_CHANNEL_NOT_IN, ARM_COMPUTE_ERROR_ON_NULLPTR, arm_compute::auto_init_if_empty(), arm_compute::test::validation::axis, arm_compute::calculate_max_window(), arm_compute::misc::shape_calculator::compute_gather_shape(), ITensorInfo::data_type(), arm_compute::F16, arm_compute::F32, ITensor::info(), ITensorInfo::num_dimensions(), arm_compute::test::validation::output_shape, arm_compute::QASYMM8, arm_compute::S16, arm_compute::S32, arm_compute::S8, ITensorInfo::set_valid_region(), ITensorInfo::tensor_shape(), arm_compute::U16, arm_compute::U32, and arm_compute::U8.
name()
const char* name () const inline override virtual
Name of the kernel.
Returns
Kernel name
Implements ICPPKernel.
Definition at line 56 of file NEGatherKernel.h.
     {
         return "NEGatherKernel";
     }
operator=() [1/2]
NEGatherKernel& operator= (const NEGatherKernel &) delete
Prevent instances of this class from being copied (As this class contains pointers).
operator=() [2/2]
NEGatherKernel& operator= (NEGatherKernel &&) default
Allow instances of this class to be moved.
run()
void run (const Window & window, const ThreadInfo & info) override virtual
Execute the kernel on the passed window.
Warning
If is_parallelisable() returns false then the passed window must be equal to window()
Note
The window has to be a region within the window returned by the window() method
The width of the window has to be a multiple of num_elems_processed_per_iteration().
Parameters
[in] window Region on which to execute the kernel. (Must be a region of the window returned by window())
[in] info Info about executing thread and CPU.
Implements ICPPKernel.
Definition at line 196 of file NEGatherKernel.cpp.
 {
     ARM_COMPUTE_UNUSED(info);
     ARM_COMPUTE_ERROR_ON_UNCONFIGURED_KERNEL(this);
     ARM_COMPUTE_ERROR_ON(_func == nullptr);
     (this->*_func)(window, info);
 }
References ARM_COMPUTE_ERROR_ON, ARM_COMPUTE_ERROR_ON_UNCONFIGURED_KERNEL, ARM_COMPUTE_UNUSED, arm_compute::test::validation::info, and IKernel::window().
validate()
Status validate (const ITensorInfo * input, const ITensorInfo * indices, const ITensorInfo * output, int axis) static
Static function to check if given info will lead to a valid configuration of NEGatherKernel.
Parameters
[in] input Source tensor info. Supported tensor rank: up to 4. Data type supported: U8/S8/QASYMM8/U16/S16/U32/S32/F16/F32
[in] indices Indices tensor info. Supported tensor rank: up to 1. Must be one of the following type: U32/S32. Each value Must be in range [0, input.shape[axis])
[in] output Destination tensor info. Data type supported: Same as input
[in] axis (Optional) The axis in input to gather indices from. Negative values wrap around. Defaults to 0
Returns
a status
Definition at line 166 of file NEGatherKernel.cpp.
 {
     ARM_COMPUTE_RETURN_ERROR_ON_NULLPTR(input, indices, output);
     ARM_COMPUTE_RETURN_ERROR_ON(indices->num_dimensions() > 1);
     ARM_COMPUTE_RETURN_ERROR_ON(input->num_dimensions() > 4);
     if(axis < 0)
     {
         axis += input->num_dimensions();
     }
     ARM_COMPUTE_RETURN_ERROR_ON(0 > axis || axis >= static_cast<int32_t>(input->num_dimensions()));
     ARM_COMPUTE_RETURN_ERROR_ON_CPU_F16_UNSUPPORTED(input);
     ARM_COMPUTE_RETURN_ERROR_ON_DATA_TYPE_CHANNEL_NOT_IN(input, 1, DataType::U8, DataType::S8, DataType::QASYMM8,
                                                          DataType::U16, DataType::S16,
                                                          DataType::U32, DataType::S32, DataType::F16, DataType::F32);
     if(output->total_size() != 0)
     {
         ARM_COMPUTE_RETURN_ERROR_ON_MISMATCHING_DATA_TYPES(input, output);
         ARM_COMPUTE_RETURN_ERROR_ON_MISMATCHING_QUANTIZATION_INFO(input, output);
         TensorShape output_shape = arm_compute::misc::shape_calculator::compute_gather_shape(input->tensor_shape(), indices->tensor_shape(), axis);
         ARM_COMPUTE_RETURN_ERROR_ON(output_shape.total_size() != output->tensor_shape().total_size());
     }
     ARM_COMPUTE_RETURN_ERROR_ON_DATA_TYPE_CHANNEL_NOT_IN(indices, 1, DataType::U32, DataType::S32);
     return Status{};
 }
References ARM_COMPUTE_RETURN_ERROR_ON, ARM_COMPUTE_RETURN_ERROR_ON_CPU_F16_UNSUPPORTED, ARM_COMPUTE_RETURN_ERROR_ON_DATA_TYPE_CHANNEL_NOT_IN, ARM_COMPUTE_RETURN_ERROR_ON_MISMATCHING_DATA_TYPES, ARM_COMPUTE_RETURN_ERROR_ON_MISMATCHING_QUANTIZATION_INFO, ARM_COMPUTE_RETURN_ERROR_ON_NULLPTR, arm_compute::test::validation::axis, arm_compute::misc::shape_calculator::compute_gather_shape(), arm_compute::F16, arm_compute::F32, ITensorInfo::num_dimensions(), arm_compute::test::validation::output_shape, arm_compute::QASYMM8, arm_compute::S16, arm_compute::S32, arm_compute::S8, ITensorInfo::tensor_shape(), TensorShape::total_size(), ITensorInfo::total_size(), arm_compute::U16, arm_compute::U32, and arm_compute::U8.
Referenced by NEGather::validate().
The documentation for this class was generated from the following files:
arm_compute/core/NEON/kernels/NEGatherKernel.h
src/core/NEON/kernels/NEGatherKernel.cpp