Compute Library: NEArithmeticAdditionKernel Class Reference
NEArithmeticAdditionKernel Class Reference
Interface for the kernel to perform addition between two tensors.
#include <NEArithmeticAdditionKernel.h>
Public Member Functions
const char * name () const override
Name of the kernel.
NEArithmeticAdditionKernel ()
Default constructor.
NEArithmeticAdditionKernel (const NEArithmeticAdditionKernel &)=delete
Prevent instances of this class from being copied (As this class contains pointers)
NEArithmeticAdditionKernel & operator= (const NEArithmeticAdditionKernel &)=delete
Prevent instances of this class from being copied (As this class contains pointers)
NEArithmeticAdditionKernel (NEArithmeticAdditionKernel &&)=default
Allow instances of this class to be moved.
NEArithmeticAdditionKernel & operator= (NEArithmeticAdditionKernel &&)=default
Allow instances of this class to be moved.
~NEArithmeticAdditionKernel ()=default
Default destructor.
void configure (const ITensor *input1, const ITensor *input2, ITensor *output, ConvertPolicy policy)
Initialise the kernel's input, output and border mode.
void run (const Window &window, const ThreadInfo &info) override
Execute the kernel on the passed window.
Public Member Functions inherited from ICPPKernel
virtual ~ICPPKernel ()=default
Default destructor.
Public Member Functions inherited from IKernel
IKernel ()
Constructor.
virtual ~IKernel ()=default
Destructor.
virtual bool is_parallelisable () const
Indicates whether or not the kernel is parallelisable.
virtual BorderSize border_size () const
The size of the border for that kernel.
const Window & window () const
The maximum window the kernel can be executed on.
Static Public Member Functions
static Status validate (const ITensorInfo *input1, const ITensorInfo *input2, const ITensorInfo *output, ConvertPolicy policy)
Static function to check if given info will lead to a valid configuration of NEArithmeticAdditionKernel.
Detailed Description
Interface for the kernel to perform addition between two tensors.
Definition at line 35 of file NEArithmeticAdditionKernel.h.
Constructor & Destructor Documentation
NEArithmeticAdditionKernel() [1/3]
NEArithmeticAdditionKernel ()
Default constructor.
Definition at line 718 of file NEArithmeticAdditionKernel.cpp.
     : _func(nullptr), _input1(nullptr), _input2(nullptr), _output(nullptr), _policy()
 {
 }
NEArithmeticAdditionKernel() [2/3]
NEArithmeticAdditionKernel (const NEArithmeticAdditionKernel &) delete
Prevent instances of this class from being copied (As this class contains pointers)
NEArithmeticAdditionKernel() [3/3]
NEArithmeticAdditionKernel (NEArithmeticAdditionKernel &&) default
Allow instances of this class to be moved.
~NEArithmeticAdditionKernel()
~NEArithmeticAdditionKernel () default
Default destructor.
Member Function Documentation
configure()
void configure (const ITensor * input1, const ITensor * input2, ITensor * output, ConvertPolicy policy)
Initialise the kernel's input, output and border mode.
Valid configurations (Input1,Input2) -> Output :
(U8,U8) -> U8
(U8,U8) -> S16
(S16,U8) -> S16
(U8,S16) -> S16
(S16,S16) -> S16
(F16,F16) -> F16
(F32,F32) -> F32
(QASYMM8,QASYMM8) -> QASYMM8
(QSYMM16,QSYMM16) -> QSYMM16
Parameters
[in] input1 An input tensor. Data types supported: U8/QASYMM8/S16/QSYMM16/F16/F32
[in] input2 An input tensor. Data types supported: U8/QASYMM8/S16/QSYMM16/F16/F32
[out] output The output tensor. Data types supported: U8/QASYMM8/S16/QSYMM16/F16/F32.
[in] policy Overflow policy.
Definition at line 723 of file NEArithmeticAdditionKernel.cpp.
 {
     ARM_COMPUTE_ERROR_ON_NULLPTR(input1, input2, output);
     ARM_COMPUTE_ERROR_THROW_ON(validate_arguments(*input1->info(), *input2->info(), *output->info(), policy));
     // Configure kernel window
     auto win_config = validate_and_configure_window(*input1->info(), *input2->info(), *output->info());
     ARM_COMPUTE_ERROR_THROW_ON(win_config.first);
     static std::map<std::string, AddFunction *> map_function =
     {
         { "add_wrap_QASYMM8_QASYMM8_QASYMM8", &add_QASYMM8_QASYMM8_QASYMM8 },
         { "add_saturate_QASYMM8_QASYMM8_QASYMM8", &add_QASYMM8_QASYMM8_QASYMM8 },
         { "add_wrap_QSYMM16_QSYMM16_QSYMM16", &add_QSYMM16_QSYMM16_QSYMM16 },
         { "add_saturate_QSYMM16_QSYMM16_QSYMM16", &add_QSYMM16_QSYMM16_QSYMM16 },
         { "add_wrap_U8_U8_U8", &add_same<uint8_t, false> },
         { "add_saturate_U8_U8_U8", &add_same<uint8_t, true> },
         { "add_wrap_S16_U8_S16", &add_S16_U8_S16 },
         { "add_saturate_S16_U8_S16", &add_S16_U8_S16 },
         { "add_wrap_U8_S16_S16", &add_U8_S16_S16 },
         { "add_saturate_U8_S16_S16", &add_U8_S16_S16 },
         { "add_wrap_U8_U8_S16", &add_U8_U8_S16 },
         { "add_saturate_U8_U8_S16", &add_U8_U8_S16 },
         { "add_wrap_S16_S16_S16", &add_same<int16_t, false> },
         { "add_saturate_S16_S16_S16", &add_same<int16_t, true> },
         { "add_wrap_F32_F32_F32", &add_same<float, false> },
         { "add_saturate_F32_F32_F32", &add_same<float, false> },
 #ifdef __ARM_FEATURE_FP16_VECTOR_ARITHMETIC
         { "add_wrap_F16_F16_F16", &add_same<float16_t, false> },
         { "add_saturate_F16_F16_F16", &add_same<float16_t, false> },
 #endif /* __ARM_FEATURE_FP16_VECTOR_ARITHMETIC */
     };
     _input1 = input1;
     _input2 = input2;
     _output = output;
     _policy = policy;
     std::string function_to_call("add_");
     function_to_call += policy == ConvertPolicy::WRAP ? "wrap_" : "saturate_";
     function_to_call += string_from_data_type(input1->info()->data_type()) + "_";
     function_to_call += string_from_data_type(input2->info()->data_type()) + "_";
     function_to_call += string_from_data_type(output->info()->data_type());
     auto it = map_function.find(function_to_call);
     if(it != map_function.end())
     {
         _func = it->second;
     }
     INEKernel::configure(win_config.second);
 }
References ARM_COMPUTE_ERROR_ON_NULLPTR, ARM_COMPUTE_ERROR_THROW_ON, ITensorInfo::data_type(), ITensor::info(), arm_compute::test::validation::policy, arm_compute::string_from_data_type(), arm_compute::validate_and_configure_window(), and arm_compute::WRAP.
Referenced by NERNNLayer::configure(), NELSTMLayer::configure(), and NEGEMMConvolutionLayer::configure().
name()
const char* name () const inline override virtual
Name of the kernel.
Returns
Kernel name
Implements ICPPKernel.
Definition at line 38 of file NEArithmeticAdditionKernel.h.
     {
         return "NEArithmeticAdditionKernel";
     }
operator=() [1/2]
NEArithmeticAdditionKernel& operator= (const NEArithmeticAdditionKernel &) delete
Prevent instances of this class from being copied (As this class contains pointers)
operator=() [2/2]
NEArithmeticAdditionKernel& operator= (NEArithmeticAdditionKernel &&) default
Allow instances of this class to be moved.
run()
void run (const Window & window, const ThreadInfo & info) override virtual
Execute the kernel on the passed window.
Warning
If is_parallelisable() returns false then the passed window must be equal to window()
Note
The window has to be a region within the window returned by the window() method
The width of the window has to be a multiple of num_elems_processed_per_iteration().
Parameters
[in] window Region on which to execute the kernel. (Must be a region of the window returned by window())
[in] info Info about executing thread and CPU.
Implements ICPPKernel.
Definition at line 787 of file NEArithmeticAdditionKernel.cpp.
 {
     ARM_COMPUTE_UNUSED(info);
     ARM_COMPUTE_ERROR_ON_UNCONFIGURED_KERNEL(this);
     ARM_COMPUTE_ERROR_ON_INVALID_SUBWINDOW(INEKernel::window(), window);
     ARM_COMPUTE_ERROR_ON(_func == nullptr);
     (*_func)(_input1, _input2, _output, _policy, window);
 }
References ARM_COMPUTE_ERROR_ON, ARM_COMPUTE_ERROR_ON_INVALID_SUBWINDOW, ARM_COMPUTE_ERROR_ON_UNCONFIGURED_KERNEL, ARM_COMPUTE_UNUSED, arm_compute::test::validation::info, and IKernel::window().
validate()
Status validate (const ITensorInfo * input1, const ITensorInfo * input2, const ITensorInfo * output, ConvertPolicy policy) static
Static function to check if given info will lead to a valid configuration of NEArithmeticAdditionKernel.
Parameters
[in] input1 An input tensor. Data types supported: U8/QASYMM8/S16/QSYMM16/F16/F32
[in] input2 An input tensor. Data types supported: U8/QASYMM8/S16/QSYMM16/F16/F32
[in] output The output tensor. Data types supported: U8/QASYMM8/S16/QSYMM16/F16/F32.
[in] policy Overflow policy.
Returns
a status
Definition at line 777 of file NEArithmeticAdditionKernel.cpp.
 {
     ARM_COMPUTE_RETURN_ERROR_ON_NULLPTR(input1, input2, output);
     ARM_COMPUTE_RETURN_ON_ERROR(validate_arguments(*input1, *input2, *output, policy));
     ARM_COMPUTE_RETURN_ON_ERROR(validate_and_configure_window(*input1->clone(), *input2->clone(), *output->clone()).first);
     return Status{};
 }
References ARM_COMPUTE_RETURN_ERROR_ON_NULLPTR, ARM_COMPUTE_RETURN_ON_ERROR, ICloneable< T >::clone(), arm_compute::test::validation::policy, and arm_compute::validate_and_configure_window().
Referenced by NEArithmeticAddition::validate(), NERNNLayer::validate(), and NEGEMMConvolutionLayer::validate().
The documentation for this class was generated from the following files:
arm_compute/core/NEON/kernels/NEArithmeticAdditionKernel.h
src/core/NEON/kernels/NEArithmeticAdditionKernel.cpp