Compute Library: NEGEMMLowpMatrixAReductionKernel Class Reference
NEGEMMLowpMatrixAReductionKernel Class Reference
NEON kernel used to compute the row-vectors of sums of all the entries in each row of Matrix A.
#include <NEGEMMLowpReductionKernel.h>
Public Member Functions
const char * name () const override
Name of the kernel.
void configure (const ITensor *mtx_a, ITensor *vector_sum_row, int32_t num_mtx_a_cols, bool is_interleaved4x4) override
Initialise the kernel's input and output.
void run (const Window &window, const ThreadInfo &info) override
Execute the kernel on the passed window.
Public Member Functions inherited from INEGEMMLowpReductionKernel
INEGEMMLowpReductionKernel ()
Constructor.
INEGEMMLowpReductionKernel (const INEGEMMLowpReductionKernel &)=delete
Prevent instances of this class from being copied (As this class contains pointers)
INEGEMMLowpReductionKernel & operator= (const INEGEMMLowpReductionKernel &)=delete
Prevent instances of this class from being copied (As this class contains pointers)
INEGEMMLowpReductionKernel (INEGEMMLowpReductionKernel &&)=default
Allow instances of this class to be moved.
INEGEMMLowpReductionKernel & operator= (INEGEMMLowpReductionKernel &&)=default
Allow instances of this class to be moved.
Public Member Functions inherited from ICPPKernel
virtual ~ICPPKernel ()=default
Default destructor.
Public Member Functions inherited from IKernel
IKernel ()
Constructor.
virtual ~IKernel ()=default
Destructor.
virtual bool is_parallelisable () const
Indicates whether or not the kernel is parallelisable.
virtual BorderSize border_size () const
The size of the border for that kernel.
const Window & window () const
The maximum window the kernel can be executed on.
Static Public Member Functions
static Status validate (const ITensorInfo *mtx_a, const ITensorInfo *vector_sum_row, int32_t num_mtx_a_cols, bool is_interleaved4x4)
Static function to check if given info will lead to a valid configuration of NEGEMMLowpMatrixAReductionKernel.
Detailed Description
NEON kernel used to compute the row-vectors of sums of all the entries in each row of Matrix A.
Note
This stage is needed to handle the offset of matrix product https://github.com/google/gemmlowp/blob/master/doc/low-precision.md
Definition at line 69 of file NEGEMMLowpReductionKernel.h.
Member Function Documentation
configure()
void configure (const ITensor * mtx_a, ITensor * vector_sum_row, int32_t num_mtx_a_cols, bool is_interleaved4x4) override virtual
Initialise the kernel's input and output.
Parameters
[in] mtx_a Input tensor. Data type supported: QASYMM8
[out] vector_sum_row Output row-vector of sums of all the entries in each row of mtx_a. Data type supported: S32
[in] num_mtx_a_cols Number of matrix A columns
[in] is_interleaved4x4 True if the matrix A has been interleaved4x4
Implements INEGEMMLowpReductionKernel.
Definition at line 105 of file NEGEMMLowpReductionKernel.cpp.
 {
     // Perform validate step
     ARM_COMPUTE_ERROR_ON_NULLPTR(mtx_a, vector_sum_row);
     ARM_COMPUTE_ERROR_THROW_ON(validate_arguments_matrix_a_reduction(mtx_a->info(), vector_sum_row->info()));
     _input       = mtx_a;
     _output      = vector_sum_row;
     _k           = num_mtx_a_cols;
     _is_reshaped = is_interleaved4x4;
     // Configure kernel window
     auto win_config = validate_and_configure_window_matrix_a_reduction(_input->info(), _output->info(), _is_reshaped);
     ARM_COMPUTE_ERROR_THROW_ON(win_config.first);
     INEKernel::configure(win_config.second);
 }
References ARM_COMPUTE_ERROR_ON_NULLPTR, ARM_COMPUTE_ERROR_THROW_ON, and ITensor::info().
Referenced by NEGEMMLowpMatrixMultiplyCore::configure().
name()
const char* name () const inline override virtual
Name of the kernel.
Returns
Kernel name
Implements ICPPKernel.
Definition at line 72 of file NEGEMMLowpReductionKernel.h.
     {
         return "NEGEMMLowpMatrixAReductionKernel";
     }
run()
void run (const Window & window, const ThreadInfo & info) override virtual
Execute the kernel on the passed window.
Warning
If is_parallelisable() returns false then the passed window must be equal to window()
Note
The window has to be a region within the window returned by the window() method
The width of the window has to be a multiple of num_elems_processed_per_iteration().
Parameters
[in] window Region on which to execute the kernel. (Must be a region of the window returned by window())
[in] info Info about executing thread and CPU.
Implements ICPPKernel.
Definition at line 131 of file NEGEMMLowpReductionKernel.cpp.
 {
     ARM_COMPUTE_UNUSED(info);
     ARM_COMPUTE_ERROR_ON_UNCONFIGURED_KERNEL(this);
     ARM_COMPUTE_ERROR_ON_INVALID_SUBWINDOW(INEKernel::window(), window);
     Window collapsed_window = window.collapse_if_possible(IKernel::window(), Window::DimY);
     Window win_input(collapsed_window);
     win_input.set(Window::DimX, Window::Dimension(0, 0, 0));
     win_input.set(Window::DimY, Window::Dimension(0, 0, 0));
     win_input.set(Window::DimZ, Window::Dimension(0, 0, 0));
     Iterator in(_input, win_input);
     Iterator out(_output, collapsed_window);
     if(_is_reshaped)
     {
         execute_window_loop(collapsed_window, [&](const Coordinates & id)
         {
             // Note: Since the input is unsigned char, we can safely use unsigned int for the accumulation
             uint32x4_t sum_row = vdupq_n_u32(0);
             const uint8_t *matrix_a = (in.ptr() + (id.x() / 4) * _input->info()->strides_in_bytes()[1] + id.y() * _input->info()->strides_in_bytes()[2]);
 #if __arm__
             asm volatile("PLD [%0, #128*4]" ::"r"(matrix_a));
 #endif /* __arm__ */
             int i = 0;
             // This for loop performs 4 accumulations
             for(; i <= (_k - 4); i += 4)
             {
                 const uint8x16_t a0_u8 = vld1q_u8(matrix_a + i * 4);
                 // Convert U8 to U16
                 uint16x4x4_t a0_u16 =
                 {
                     {
                         vget_low_u16(vmovl_u8(vget_low_u8(a0_u8))),
                         vget_high_u16(vmovl_u8(vget_low_u8(a0_u8))),
                         vget_low_u16(vmovl_u8(vget_high_u8(a0_u8))),
                         vget_high_u16(vmovl_u8(vget_high_u8(a0_u8)))
                     }
                 };
                 // Accumulate to U16
                 a0_u16.val[0] = vadd_u16(a0_u16.val[0], a0_u16.val[1]);
                 a0_u16.val[0] = vadd_u16(a0_u16.val[0], a0_u16.val[2]);
                 a0_u16.val[0] = vadd_u16(a0_u16.val[0], a0_u16.val[3]);
                 // Accumulate to U32
                 sum_row = vaddw_u16(sum_row, a0_u16.val[0]);
             }
             // This for loop performs the leftover accumulations
             for(; i < _k; ++i)
             {
                 const uint8x8_t a0_u8 = vld1_u8(matrix_a + i * 4);
                 // Convert U8 to U16
                 const uint16x4_t a0_u16 = vget_low_u16(vmovl_u8(a0_u8));
                 // Accumulate to U32
                 sum_row = vaddw_u16(sum_row, a0_u16);
             }
             auto vector_sum_row = reinterpret_cast<int32_t *>(out.ptr());
             vst1q_s32(vector_sum_row, vreinterpretq_s32_u32(sum_row));
         },
         in, out);
     }
     else // it is not reshaped
     {
         execute_window_loop(collapsed_window, [&](const Coordinates & id)
         {
             // Note: Since the input is unsigned char, we can safely use unsigned int for the accumulation
             uint32x4_t sum_row_u32 = vdupq_n_u32(0);
             uint32_t   sum_row     = 0;
             const uint8_t *matrix_a = (in.ptr() + id.x() * _input->info()->strides_in_bytes()[1] + id.y() * _input->info()->strides_in_bytes()[2]);
 #if __arm__
             asm volatile("PLD [%0, #128*4]" ::"r"(matrix_a));
 #endif /* __arm__ */
             int i = 0;
             // This for loop performs 16 accumulations
             for(; i <= (_k - 16); i += 16)
             {
                 const uint8x16_t a0_u8 = vld1q_u8(matrix_a + i);
                 // Partial accumulations in U16
                 const uint16x8_t tmp_sum0 = vaddl_u8(vget_low_u8(a0_u8), vget_high_u8(a0_u8));
                 // Accumulate to U32
                 sum_row_u32 = vaddq_u32(sum_row_u32, vpaddlq_u16(tmp_sum0));
             }
             // This for loop performs the leftover accumulations
             for(; i < _k; ++i)
             {
                 sum_row += static_cast<uint32_t>(matrix_a[i]);
             }
 #if defined(__aarch64__)
             // Reduction operation available on 64 bit architectures only
             sum_row += vaddvq_u32(sum_row_u32);
 #else  // __aarch64__
             uint32x2_t tmp = vpadd_u32(vget_high_u32(sum_row_u32), vget_low_u32(sum_row_u32));
             tmp            = vpadd_u32(tmp, tmp);
             sum_row += vget_lane_u32(tmp, 0);
 #endif // __aarch64__
             *(reinterpret_cast<int *>(out.ptr())) = static_cast<int>(sum_row);
         },
         in, out);
     }
 }
References ARM_COMPUTE_ERROR_ON_INVALID_SUBWINDOW, ARM_COMPUTE_ERROR_ON_UNCONFIGURED_KERNEL, ARM_COMPUTE_UNUSED, Window::collapse_if_possible(), Window::DimX, Window::DimY, Window::DimZ, arm_compute::execute_window_loop(), arm_compute::test::validation::info, Iterator::ptr(), Window::set(), and IKernel::window().
validate()
Status validate (const ITensorInfo * mtx_a, const ITensorInfo * vector_sum_row, int32_t num_mtx_a_cols, bool is_interleaved4x4) static
Static function to check if given info will lead to a valid configuration of NEGEMMLowpMatrixAReductionKernel.
Parameters
[in] mtx_a Input tensor. Data type supported: QASYMM8
[in] vector_sum_row Output row-vector of sums of all the entries in each row of mtx_a. Data type supported: S32
[in] num_mtx_a_cols Number of matrix A columns
[in] is_interleaved4x4 True if the matrix A has been interleaved4x4
Returns
a status
Definition at line 122 of file NEGEMMLowpReductionKernel.cpp.
 {
     ARM_COMPUTE_UNUSED(num_mtx_a_cols);
     ARM_COMPUTE_RETURN_ON_ERROR(validate_arguments_matrix_a_reduction(mtx_a, vector_sum_row));
     ARM_COMPUTE_RETURN_ON_ERROR(validate_and_configure_window_matrix_a_reduction(mtx_a->clone().get(), vector_sum_row->clone().get(), is_interleaved4x4).first);
     return Status{};
 }
References ARM_COMPUTE_RETURN_ON_ERROR, ARM_COMPUTE_UNUSED, and ICloneable< T >::clone().
Referenced by NEGEMMLowpMatrixMultiplyCore::validate().
The documentation for this class was generated from the following files:
arm_compute/core/NEON/kernels/NEGEMMLowpReductionKernel.h
src/core/NEON/kernels/NEGEMMLowpReductionKernel.cpp