Compute Library: NEConvertFullyConnectedWeightsKernel Class Reference
NEConvertFullyConnectedWeightsKernel Class Reference
Interface to convert the 2D Fully Connected weights from NCHW to NHWC or vice versa.
#include <NEConvertFullyConnectedWeightsKernel.h>
Public Member Functions
const char * name () const override
Name of the kernel.
NEConvertFullyConnectedWeightsKernel ()
Default constructor.
NEConvertFullyConnectedWeightsKernel (const NEConvertFullyConnectedWeightsKernel &)=delete
Prevent instances of this class from being copied (As this class contains pointers)
NEConvertFullyConnectedWeightsKernel & operator= (const NEConvertFullyConnectedWeightsKernel &)=delete
Prevent instances of this class from being copied (As this class contains pointers)
NEConvertFullyConnectedWeightsKernel (NEConvertFullyConnectedWeightsKernel &&)=default
Allow instances of this class to be moved.
NEConvertFullyConnectedWeightsKernel & operator= (NEConvertFullyConnectedWeightsKernel &&)=default
Allow instances of this class to be moved.
~NEConvertFullyConnectedWeightsKernel ()=default
Default destructor.
void configure (const ITensor *input, ITensor *output, const TensorShape &original_input_shape, DataLayout data_layout)
Set the input and output tensor.
void run (const Window &window, const ThreadInfo &info) override
Execute the kernel on the passed window.
Public Member Functions inherited from ICPPKernel
virtual ~ICPPKernel ()=default
Default destructor.
Public Member Functions inherited from IKernel
IKernel ()
Constructor.
virtual ~IKernel ()=default
Destructor.
virtual bool is_parallelisable () const
Indicates whether or not the kernel is parallelisable.
virtual BorderSize border_size () const
The size of the border for that kernel.
const Window & window () const
The maximum window the kernel can be executed on.
Static Public Member Functions
static Status validate (const ITensorInfo *input, const ITensorInfo *output, const TensorShape &original_input_shape, DataLayout data_layout)
Static function to check if given info will lead to a valid configuration of NEConvertFullyConnectedWeightsKernel.
Detailed Description
Interface to convert the 2D Fully Connected weights from NCHW to NHWC or vice versa.
Note
This function can be applied to the 2D weights used by a Fully Connected layer if:
It follows a Convolution layer
The data layout used by the network does not match the one the model has been trained in.
This function assumes the weights are already reshaped (transposed)
Definition at line 41 of file NEConvertFullyConnectedWeightsKernel.h.
Constructor & Destructor Documentation
NEConvertFullyConnectedWeightsKernel() [1/3]
NEConvertFullyConnectedWeightsKernel ()
Default constructor.
Definition at line 31 of file NEConvertFullyConnectedWeightsKernel.cpp.
     : _input(nullptr), _output(nullptr), _factor1(0), _factor2(0)
 {
 }
NEConvertFullyConnectedWeightsKernel() [2/3]
NEConvertFullyConnectedWeightsKernel (const NEConvertFullyConnectedWeightsKernel &) delete
Prevent instances of this class from being copied (As this class contains pointers)
NEConvertFullyConnectedWeightsKernel() [3/3]
NEConvertFullyConnectedWeightsKernel (NEConvertFullyConnectedWeightsKernel &&) default
Allow instances of this class to be moved.
~NEConvertFullyConnectedWeightsKernel()
~NEConvertFullyConnectedWeightsKernel () default
Default destructor.
Member Function Documentation
configure()
void configure (const ITensor * input, ITensor * output, const TensorShape & original_input_shape, DataLayout data_layout)
Set the input and output tensor.
Parameters
[in] input Source weights tensor to convert. Must be 2 dimensional. Data types supported: U8/S8/QASYMM8/U16/S16/U32/S32/F16/F32.
[out] output The converted weights tensor. Shape and Data Type: Same as input.
[in] original_input_shape Shape of the original input tensor (the one entering fully connected layer).
[in] data_layout The data layout the weights have been trained in.
Definition at line 36 of file NEConvertFullyConnectedWeightsKernel.cpp.
 {
     ARM_COMPUTE_ERROR_ON_NULLPTR(input, output);
     // Output tensor auto initialisation if not yet initialized
     auto_init_if_empty(*output->info(), *input->info()->clone());
     ARM_COMPUTE_ERROR_THROW_ON(NEConvertFullyConnectedWeightsKernel::validate(input->info(), output->info(), original_input_shape, data_layout));
     _input  = input;
     _output = output;
     const DataLayout input_data_layout = (data_layout == DataLayout::NCHW) ? DataLayout::NHWC : DataLayout::NCHW;
     const int width_idx   = get_data_layout_dimension_index(input_data_layout, DataLayoutDimension::WIDTH);
     const int height_idx  = get_data_layout_dimension_index(input_data_layout, DataLayoutDimension::HEIGHT);
     const int channel_idx = get_data_layout_dimension_index(input_data_layout, DataLayoutDimension::CHANNEL);
     const unsigned int num_elems_per_input_plane = original_input_shape[width_idx] * original_input_shape[height_idx];
     const unsigned int num_channels              = original_input_shape[channel_idx];
     _factor1 = (data_layout == DataLayout::NCHW) ? num_elems_per_input_plane : num_channels;
     _factor2 = (data_layout == DataLayout::NCHW) ? num_channels : num_elems_per_input_plane;
     // Configure kernel window
     Window win = calculate_max_window(*input->info(), Steps());
     INEKernel::configure(win);
 }
References ARM_COMPUTE_ERROR_ON_NULLPTR, ARM_COMPUTE_ERROR_THROW_ON, arm_compute::auto_init_if_empty(), arm_compute::calculate_max_window(), arm_compute::CHANNEL, ICloneable< T >::clone(), arm_compute::test::validation::data_layout, arm_compute::get_data_layout_dimension_index(), arm_compute::HEIGHT, ITensor::info(), arm_compute::NCHW, arm_compute::NHWC, NEConvertFullyConnectedWeightsKernel::validate(), and arm_compute::WIDTH.
Referenced by NEConvertFullyConnectedWeights::configure().
name()
const char* name () const inline override virtual
Name of the kernel.
Returns
Kernel name
Implements ICPPKernel.
Definition at line 44 of file NEConvertFullyConnectedWeightsKernel.h.
     {
         return "NEConvertFullyConnectedWeightsKernel";
     }
operator=() [1/2]
NEConvertFullyConnectedWeightsKernel& operator= (const NEConvertFullyConnectedWeightsKernel &) delete
Prevent instances of this class from being copied (As this class contains pointers)
operator=() [2/2]
NEConvertFullyConnectedWeightsKernel& operator= (NEConvertFullyConnectedWeightsKernel &&) default
Allow instances of this class to be moved.
run()
void run (const Window & window, const ThreadInfo & info) override virtual
Execute the kernel on the passed window.
Warning
If is_parallelisable() returns false then the passed window must be equal to window()
Note
The window has to be a region within the window returned by the window() method
The width of the window has to be a multiple of num_elems_processed_per_iteration().
Parameters
[in] window Region on which to execute the kernel. (Must be a region of the window returned by window())
[in] info Info about executing thread and CPU.
Implements ICPPKernel.
Definition at line 105 of file NEConvertFullyConnectedWeightsKernel.cpp.
 {
     ARM_COMPUTE_UNUSED(info);
     ARM_COMPUTE_ERROR_ON_UNCONFIGURED_KERNEL(this);
     ARM_COMPUTE_ERROR_ON_INVALID_SUBWINDOW(INEKernel::window(), window);
     switch(_input->info()->element_size())
     {
         case 1:
             run_convert_fc_weights<uint8_t>(window);
             break;
         case 2:
             run_convert_fc_weights<uint16_t>(window);
             break;
         case 4:
             run_convert_fc_weights<uint32_t>(window);
             break;
         default:
             ARM_COMPUTE_ERROR("Data type not supported.");
             break;
     }
 }
References ARM_COMPUTE_ERROR, ARM_COMPUTE_ERROR_ON_INVALID_SUBWINDOW, ARM_COMPUTE_ERROR_ON_UNCONFIGURED_KERNEL, ARM_COMPUTE_UNUSED, ITensorInfo::element_size(), ITensor::info(), arm_compute::test::validation::info, and IKernel::window().
validate()
Status validate (const ITensorInfo * input, const ITensorInfo * output, const TensorShape & original_input_shape, DataLayout data_layout) static
Static function to check if given info will lead to a valid configuration of NEConvertFullyConnectedWeightsKernel.
Parameters
[in] input Source weights tensor info to convert. Must be 2 dimensional. Data types supported: U8/S8/QASYMM8/U16/S16/U32/S32/F16/F32.
[in] output The converted weights tensor info. Shape and Data Type: Same as input.
[in] original_input_shape Shape of the original input tensor (the one entering fully connected layer).
[in] data_layout The data layout the weights have been trained in.
Definition at line 66 of file NEConvertFullyConnectedWeightsKernel.cpp.
 {
     //Note: ARM_COMPUTE_RETURN_ERROR_ON_CPU_F16_UNSUPPORTED(input) is not needed here as this kernel doesn't use NEON FP16 instructions.
     ARM_COMPUTE_RETURN_ERROR_ON_DATA_TYPE_CHANNEL_NOT_IN(input, 1,
                                                          DataType::U8, DataType::S8, DataType::QASYMM8,
                                                          DataType::U16, DataType::S16,
                                                          DataType::U32, DataType::S32,
                                                          DataType::F16, DataType::F32);
     ARM_COMPUTE_RETURN_ERROR_ON(input->num_dimensions() != 2);
     ARM_COMPUTE_RETURN_ERROR_ON(input->dimension(1) != original_input_shape.total_size_lower(3));
     ARM_COMPUTE_RETURN_ERROR_ON(data_layout == DataLayout::UNKNOWN);
     // Checks performed when output is configured
     if((output != nullptr) && (output->total_size() != 0))
     {
         ARM_COMPUTE_RETURN_ERROR_ON_MISMATCHING_DATA_TYPES(input, output);
         ARM_COMPUTE_RETURN_ERROR_ON_MISMATCHING_SHAPES(input, output);
     }
     return Status{};
 }
References ARM_COMPUTE_RETURN_ERROR_ON, ARM_COMPUTE_RETURN_ERROR_ON_DATA_TYPE_CHANNEL_NOT_IN, ARM_COMPUTE_RETURN_ERROR_ON_MISMATCHING_DATA_TYPES, ARM_COMPUTE_RETURN_ERROR_ON_MISMATCHING_SHAPES, arm_compute::test::validation::data_layout, ITensorInfo::dimension(), arm_compute::F16, arm_compute::F32, ITensorInfo::num_dimensions(), arm_compute::QASYMM8, arm_compute::S16, arm_compute::S32, arm_compute::S8, ITensorInfo::total_size(), TensorShape::total_size_lower(), arm_compute::U16, arm_compute::U32, arm_compute::U8, and arm_compute::UNKNOWN.
Referenced by NEConvertFullyConnectedWeightsKernel::configure(), and NEConvertFullyConnectedWeights::validate().
The documentation for this class was generated from the following files:
arm_compute/core/NEON/kernels/NEConvertFullyConnectedWeightsKernel.h
src/core/NEON/kernels/NEConvertFullyConnectedWeightsKernel.cpp