Compute Library: NELaplacianReconstruct Class Reference
NELaplacianReconstruct Class Reference
Basic function to execute laplacian reconstruction.
#include <NELaplacianReconstruct.h>
Public Member Functions
NELaplacianReconstruct ()
Constructor.
void configure (const IPyramid *pyramid, ITensor *input, ITensor *output, BorderMode border_mode, uint8_t constant_border_value)
Initialise the function's source, destinations and border mode.
void run () override
Run the kernels contained in the function.
Public Member Functions inherited from IFunction
virtual ~IFunction ()=default
Destructor.
virtual void prepare ()
Prepare the function for executing.
Detailed Description
Basic function to execute laplacian reconstruction.
This function calls the following NEON kernels and functions:
NEArithmeticAddition
NEScale
NEDepthConvertLayer
This function reconstructs the original image from a Laplacian Image Pyramid.
The input image is added to the last level of the Laplacian pyramid L(n-2), the resulting image is upsampled to the resolution of the next pyramid level.
I(n-2) = upsample(input + L(n-1)
For each pyramid level i, except i=0 and i=n-1: I(i-1) = upsample(I(i) + L(i))
output = I(0) + L(0)
Definition at line 60 of file NELaplacianReconstruct.h.
Constructor & Destructor Documentation
NELaplacianReconstruct()
NELaplacianReconstruct ()
Constructor.
Definition at line 37 of file NELaplacianReconstruct.cpp.
     : _tmp_pyr(),
       _addf(),
       _scalef(),
       _depthf()
 {
 }
Member Function Documentation
configure()
void configure (const IPyramid * pyramid, ITensor * input, ITensor * output, BorderMode border_mode, uint8_t constant_border_value)
Initialise the function's source, destinations and border mode.
The Output image must have the same size as the first level of the pyramid. The Input image must have the same size as the last level of the pyramid.
The idea is to reconstuct the original hi-res image from a low-res representation of it and the laplacian pyramid.
Parameters
[in] pyramid Laplacian pyramid tensors, Data type supported at each level: S16.
[in] input Source tensor. Data type supported: S16.
[out] output Output tensor. Data type supported: U8.
[in] border_mode Border mode to use for the convolution.
[in] constant_border_value (Optional) Constant value to use for borders if border_mode is set to CONSTANT.
Definition at line 45 of file NELaplacianReconstruct.cpp.
 {
     ARM_COMPUTE_ERROR_ON(nullptr == pyramid);
     ARM_COMPUTE_ERROR_ON(input == output);
     ARM_COMPUTE_ERROR_ON_DATA_TYPE_CHANNEL_NOT_IN(input, 1, DataType::S16);
     ARM_COMPUTE_ERROR_ON_DATA_TYPE_CHANNEL_NOT_IN(output, 1, DataType::U8);
     ARM_COMPUTE_ERROR_ON(input->info()->num_dimensions() != pyramid->get_pyramid_level(0)->info()->num_dimensions());
     ARM_COMPUTE_ERROR_ON(output->info()->num_dimensions() != pyramid->get_pyramid_level(0)->info()->num_dimensions());
     ARM_COMPUTE_ERROR_ON(output->info()->dimension(0) != pyramid->get_pyramid_level(0)->info()->dimension(0));
     ARM_COMPUTE_ERROR_ON(output->info()->dimension(1) != pyramid->get_pyramid_level(0)->info()->dimension(1));
     ARM_COMPUTE_ERROR_ON(input->info()->dimension(0) != pyramid->get_pyramid_level(pyramid->info()->num_levels() - 1)->info()->dimension(0));
     ARM_COMPUTE_ERROR_ON(input->info()->dimension(1) != pyramid->get_pyramid_level(pyramid->info()->num_levels() - 1)->info()->dimension(1));
     const size_t num_levels = pyramid->info()->num_levels();
     // Create and initialize the tmp pyramid: I(n-2) = upsample( input + Laplace(n-1) )
     PyramidInfo pyramid_info;
     pyramid_info.init(num_levels, 0.5f, output->info()->tensor_shape(), arm_compute::Format::S16);
     _tmp_pyr.init(pyramid_info);
     // Allocate add and scale functions. Level 0 does not need to be scaled.
     _addf.resize(num_levels);
     _scalef.resize(num_levels - 1);
     const size_t last_level = num_levels - 1;
     _addf[last_level].configure(input, pyramid->get_pyramid_level(last_level), _tmp_pyr.get_pyramid_level(last_level), ConvertPolicy::SATURATE);
     // Scale levels n-1 to 1, and add levels n-2 to 0
     for(size_t l = 0; l < last_level; ++l)
     {
         _scalef[l].configure(_tmp_pyr.get_pyramid_level(l + 1), _tmp_pyr.get_pyramid_level(l), arm_compute::InterpolationPolicy::NEAREST_NEIGHBOR, border_mode, constant_border_value);
         _addf[l].configure(_tmp_pyr.get_pyramid_level(l), pyramid->get_pyramid_level(l), _tmp_pyr.get_pyramid_level(l), ConvertPolicy::SATURATE);
     }
     // Convert level 0 from S16 to U8
     _depthf.configure(_tmp_pyr.get_pyramid_level(0), output, ConvertPolicy::SATURATE, 0);
     _tmp_pyr.allocate();
 }
References Pyramid::allocate(), ARM_COMPUTE_ERROR_ON, ARM_COMPUTE_ERROR_ON_DATA_TYPE_CHANNEL_NOT_IN, arm_compute::test::validation::border_mode, NEDepthConvertLayer::configure(), ITensorInfo::dimension(), IPyramid::get_pyramid_level(), Pyramid::get_pyramid_level(), ITensor::info(), IPyramid::info(), arm_compute::test::validation::info, Pyramid::init(), PyramidInfo::init(), arm_compute::NEAREST_NEIGHBOR, ITensorInfo::num_dimensions(), PyramidInfo::num_levels(), arm_compute::S16, arm_compute::SATURATE, ITensorInfo::tensor_shape(), and arm_compute::U8.
run()
void run () override virtual
Run the kernels contained in the function.
For NEON kernels:
Multi-threading is used for the kernels which are parallelisable.
By default std::thread::hardware_concurrency() threads are used.
Note
CPPScheduler::set_num_threads() can be used to manually set the number of threads
For OpenCL kernels:
All the kernels are enqueued on the queue associated with CLScheduler.
The queue is then flushed.
Note
The function will not block until the kernels are executed. It is the user's responsibility to wait.
Will call prepare() on first run if hasn't been done
Implements IFunction.
Definition at line 87 of file NELaplacianReconstruct.cpp.
 {
     ARM_COMPUTE_ERROR_ON_MSG(_addf.empty(), "Unconfigured function");
     const size_t last_level = _tmp_pyr.info()->num_levels() - 1;
     _addf[last_level].run();
     // Run l = [last_level - 1, 0]
     for(size_t l = last_level; l-- > 0;)
     {
         _scalef[l].run();
         _addf[l].run();
     }
     _depthf.run();
 }
References ARM_COMPUTE_ERROR_ON_MSG, Pyramid::info(), PyramidInfo::num_levels(), and INESimpleFunctionNoBorder::run().
The documentation for this class was generated from the following files:
arm_compute/runtime/NEON/functions/NELaplacianReconstruct.h
src/runtime/NEON/functions/NELaplacianReconstruct.cpp