Compute Library: GCAbsoluteDifferenceKernel Class Reference
GCAbsoluteDifferenceKernel Class Reference
Interface for the absolute difference kernel.
#include <GCAbsoluteDifferenceKernel.h>
Public Member Functions
GCAbsoluteDifferenceKernel ()
Default constructor.
GCAbsoluteDifferenceKernel (const GCAbsoluteDifferenceKernel &)=delete
Prevent instances of this class from being copied (As this class contains pointers)
GCAbsoluteDifferenceKernel & operator= (const GCAbsoluteDifferenceKernel &)=delete
Prevent instances of this class from being copied (As this class contains pointers)
GCAbsoluteDifferenceKernel (GCAbsoluteDifferenceKernel &&)=default
Allow instances of this class to be moved.
GCAbsoluteDifferenceKernel & operator= (GCAbsoluteDifferenceKernel &&)=default
Allow instances of this class to be moved.
~GCAbsoluteDifferenceKernel ()=default
Default destructor.
void configure (const IGCTensor *input1, const IGCTensor *input2, IGCTensor *output)
Set the inputs and output images.
void run (const Window &window) override
Enqueue the OpenGL ES shader to process the given window.
Public Member Functions inherited from IGCKernel
IGCKernel ()
Constructor.
GCKernel & kernel ()
Returns a reference to the GLES kernel of this object.
void add_1D_tensor_argument (unsigned int &idx, const IGCTensor *tensor, const unsigned int binding_point, const Window &window)
Add the passed 1D tensor's parameters to the object's kernel's arguments starting from the index idx.
void add_2D_tensor_argument (unsigned int &idx, const IGCTensor *tensor, const unsigned int binding_point, const Window &window)
Add the passed 2D tensor's parameters to the object's kernel's arguments starting from the index idx.
void add_3D_tensor_argument (unsigned int &idx, const IGCTensor *tensor, const unsigned int binding_point, const Window &window)
Add the passed 3D tensor's parameters to the object's kernel's arguments starting from the index idx.
unsigned int num_arguments_per_1D_tensor () const
Returns the number of arguments enqueued per 1D tensor object.
unsigned int num_arguments_per_2D_tensor () const
Returns the number of arguments enqueued per 2D tensor object.
unsigned int num_arguments_per_3D_tensor () const
Returns the number of arguments enqueued per 3D tensor object.
void set_lws_hint (gles::NDRange &lws_hint)
Set the Local-Workgroup-Size hint.
void set_target (GPUTarget target)
Set the targeted GPU architecture.
GPUTarget get_target () const
Get the targeted GPU architecture.
Public Member Functions inherited from IKernel
IKernel ()
Constructor.
virtual ~IKernel ()=default
Destructor.
virtual bool is_parallelisable () const
Indicates whether or not the kernel is parallelisable.
virtual BorderSize border_size () const
The size of the border for that kernel.
const Window & window () const
The maximum window the kernel can be executed on.
Detailed Description
Interface for the absolute difference kernel.
Absolute difference is computed by:
\[ output(x,y) = | input1(x,y) - input2(x,y) | \]
Definition at line 38 of file GCAbsoluteDifferenceKernel.h.
Constructor & Destructor Documentation
GCAbsoluteDifferenceKernel() [1/3]
GCAbsoluteDifferenceKernel ()
Default constructor.
Definition at line 42 of file GCAbsoluteDifferenceKernel.cpp.
     : _input1(nullptr), _input2(nullptr), _output(nullptr)
 {
 }
GCAbsoluteDifferenceKernel() [2/3]
GCAbsoluteDifferenceKernel (const GCAbsoluteDifferenceKernel &) delete
Prevent instances of this class from being copied (As this class contains pointers)
GCAbsoluteDifferenceKernel() [3/3]
GCAbsoluteDifferenceKernel (GCAbsoluteDifferenceKernel &&) default
Allow instances of this class to be moved.
~GCAbsoluteDifferenceKernel()
~GCAbsoluteDifferenceKernel () default
Default destructor.
Member Function Documentation
configure()
void configure (const IGCTensor * input1, const IGCTensor * input2, IGCTensor * output)
Set the inputs and output images.
Parameters
[in] input1 Source tensor. Data types supported: U8
[in] input2 Source tensor. Data types supported: U8
[out] output Destination tensor. Data types supported: U8
Definition at line 47 of file GCAbsoluteDifferenceKernel.cpp.
 {
     ARM_COMPUTE_ERROR_ON_DATA_TYPE_CHANNEL_NOT_IN(input1, 1, DataType::U8);
     ARM_COMPUTE_ERROR_ON_DATA_TYPE_CHANNEL_NOT_IN(input2, 1, DataType::U8);
     ARM_COMPUTE_ERROR_ON_DATA_TYPE_CHANNEL_NOT_IN(output, 1, DataType::U8);
     ARM_COMPUTE_ERROR_ON_MISMATCHING_DATA_TYPES(input1, input2, output);
     _input1 = input1;
     _input2 = input2;
     _output = output;
     constexpr unsigned int num_elems_processed_per_iteration = 4;
     // Set kernel build options
     std::set<std::string> build_opts;
     build_opts.emplace("#define LOCAL_SIZE_X " + support::cpp11::to_string(1));
     build_opts.emplace("#define LOCAL_SIZE_Y " + support::cpp11::to_string(1));
     build_opts.emplace("#define LOCAL_SIZE_Z " + support::cpp11::to_string(1));
     // Create kernel
     _kernel = static_cast<GCKernel>(GCKernelLibrary::get().create_kernel("absdiff", build_opts));
     // Configure kernel window
     Window win = calculate_max_window(*input1->info(), Steps(num_elems_processed_per_iteration));
     AccessWindowRectangle input1_access(input1->info(), 0, 0, 4, 1);
     AccessWindowRectangle input2_access(input2->info(), 0, 0, 4, 1);
     AccessWindowRectangle output_access(output->info(), 0, 0, 4, 1);
     update_window_and_padding(win, input1_access, input2_access, output_access);
     ValidRegion valid_region = intersect_valid_regions(input1->info()->valid_region(),
                                                        input2->info()->valid_region());
     output_access.set_valid_region(win, valid_region);
     IGCKernel::configure(win);
 }
References ARM_COMPUTE_ERROR_ON_DATA_TYPE_CHANNEL_NOT_IN, ARM_COMPUTE_ERROR_ON_MISMATCHING_DATA_TYPES, arm_compute::calculate_max_window(), arm_compute::create_kernel(), GCKernelLibrary::get(), ITensor::info(), arm_compute::intersect_valid_regions(), arm_compute::support::cpp11::to_string(), arm_compute::U8, arm_compute::update_window_and_padding(), arm_compute::test::validation::valid_region, and ITensorInfo::valid_region().
operator=() [1/2]
GCAbsoluteDifferenceKernel& operator= (const GCAbsoluteDifferenceKernel &) delete
Prevent instances of this class from being copied (As this class contains pointers)
operator=() [2/2]
GCAbsoluteDifferenceKernel& operator= (GCAbsoluteDifferenceKernel &&) default
Allow instances of this class to be moved.
run()
void run (const Window & window) override virtual
Enqueue the OpenGL ES shader to process the given window.
Parameters
[in] window Region on which to execute the kernel. (Must be a valid region of the window returned by window()).
Implements IGCKernel.
Definition at line 86 of file GCAbsoluteDifferenceKernel.cpp.
 {
     ARM_COMPUTE_ERROR_ON_UNCONFIGURED_KERNEL(this);
     ARM_COMPUTE_ERROR_ON_INVALID_SUBWINDOW(IGCKernel::window(), window);
     _kernel.use();
     Window slice = window.first_slice_window_2D();
     do
     {
         unsigned int idx     = 0;
         unsigned int binding = 1; // SSBO binding starts from 1.
         add_2D_tensor_argument(idx, _input1, binding++, slice);
         add_2D_tensor_argument(idx, _input2, binding++, slice);
         add_2D_tensor_argument(idx, _output, binding++, slice);
         _kernel.update_shader_params();
         enqueue(*this, slice);
     }
     while(window.slide_window_slice_2D(slice));
 }
References IGCKernel::add_2D_tensor_argument(), ARM_COMPUTE_ERROR_ON_INVALID_SUBWINDOW, ARM_COMPUTE_ERROR_ON_UNCONFIGURED_KERNEL, arm_compute::enqueue(), Window::first_slice_window_2D(), arm_compute::test::validation::reference::slice(), Window::slide_window_slice_2D(), and IKernel::window().
The documentation for this class was generated from the following files:
arm_compute/core/GLES_COMPUTE/kernels/GCAbsoluteDifferenceKernel.h
src/core/GLES_COMPUTE/kernels/GCAbsoluteDifferenceKernel.cpp