Compute Library: CLBatchConcatenateLayerKernel Class Reference
CLBatchConcatenateLayerKernel Class Reference
Interface for the batch concatenate kernel.
#include <CLBatchConcatenateLayerKernel.h>
Public Member Functions
CLBatchConcatenateLayerKernel ()
Default constructor.
CLBatchConcatenateLayerKernel (const CLBatchConcatenateLayerKernel &)=delete
Prevent instances of this class from being copied (As this class contains pointers)
CLBatchConcatenateLayerKernel & operator= (const CLBatchConcatenateLayerKernel &)=delete
Prevent instances of this class from being copied (As this class contains pointers)
CLBatchConcatenateLayerKernel (CLBatchConcatenateLayerKernel &&)=default
Allow instances of this class to be moved.
CLBatchConcatenateLayerKernel & operator= (CLBatchConcatenateLayerKernel &&)=default
Allow instances of this class to be moved.
~CLBatchConcatenateLayerKernel ()=default
Default destructor.
void configure (const ICLTensor *input, unsigned int batch_offset, ICLTensor *output)
Initialise the kernel's inputs and output.
void run (const Window &window, cl::CommandQueue &queue) override
Enqueue the OpenCL kernel to process the given window on the passed OpenCL command queue.
Public Member Functions inherited from ICLKernel
ICLKernel ()
Constructor.
cl::Kernel & kernel ()
Returns a reference to the OpenCL kernel of this object.
template<typename T >
void add_1D_array_argument (unsigned int &idx, const ICLArray< T > *array, const Strides &strides, unsigned int num_dimensions, const Window &window)
Add the passed 1D array's parameters to the object's kernel's arguments starting from the index idx.
void add_1D_tensor_argument (unsigned int &idx, const ICLTensor *tensor, const Window &window)
Add the passed 1D tensor's parameters to the object's kernel's arguments starting from the index idx.
void add_1D_tensor_argument_if (bool cond, unsigned int &idx, const ICLTensor *tensor, const Window &window)
Add the passed 1D tensor's parameters to the object's kernel's arguments starting from the index idx if the condition is true.
void add_2D_tensor_argument (unsigned int &idx, const ICLTensor *tensor, const Window &window)
Add the passed 2D tensor's parameters to the object's kernel's arguments starting from the index idx.
void add_2D_tensor_argument_if (bool cond, unsigned int &idx, const ICLTensor *tensor, const Window &window)
Add the passed 2D tensor's parameters to the object's kernel's arguments starting from the index idx if the condition is true.
void add_3D_tensor_argument (unsigned int &idx, const ICLTensor *tensor, const Window &window)
Add the passed 3D tensor's parameters to the object's kernel's arguments starting from the index idx.
void add_4D_tensor_argument (unsigned int &idx, const ICLTensor *tensor, const Window &window)
Add the passed 4D tensor's parameters to the object's kernel's arguments starting from the index idx.
template<typename T >
void add_argument (unsigned int &idx, T value)
Add the passed parameters to the object's kernel's arguments starting from the index idx.
void set_lws_hint (const cl::NDRange &lws_hint)
Set the Local-Workgroup-Size hint.
cl::NDRange lws_hint () const
Return the Local-Workgroup-Size hint.
const std::string & config_id () const
Get the configuration ID.
void set_target (GPUTarget target)
Set the targeted GPU architecture.
void set_target (cl::Device &device)
Set the targeted GPU architecture according to the CL device.
GPUTarget get_target () const
Get the targeted GPU architecture.
size_t get_max_workgroup_size ()
Get the maximum workgroup size for the device the CLKernelLibrary uses.
template<typename T , unsigned int dimension_size>
void add_array_argument (unsigned &idx, const ICLArray< T > *array, const Strides &strides, unsigned int num_dimensions, const Window &window)
Add the passed array's parameters to the object's kernel's arguments starting from the index idx.
template<unsigned int dimension_size>
void add_tensor_argument (unsigned &idx, const ICLTensor *tensor, const Window &window)
Public Member Functions inherited from IKernel
IKernel ()
Constructor.
virtual ~IKernel ()=default
Destructor.
virtual bool is_parallelisable () const
Indicates whether or not the kernel is parallelisable.
virtual BorderSize border_size () const
The size of the border for that kernel.
const Window & window () const
The maximum window the kernel can be executed on.
Static Public Member Functions
static Status validate (const ITensorInfo *input, unsigned int batch_offset, const ITensorInfo *output)
Static function to check if given info will lead to a valid configuration of CLBatchConcatenateLayerKernel.
Static Public Member Functions inherited from ICLKernel
static constexpr unsigned int num_arguments_per_1D_array ()
Returns the number of arguments enqueued per 1D array object.
static constexpr unsigned int num_arguments_per_1D_tensor ()
Returns the number of arguments enqueued per 1D tensor object.
static constexpr unsigned int num_arguments_per_2D_tensor ()
Returns the number of arguments enqueued per 2D tensor object.
static constexpr unsigned int num_arguments_per_3D_tensor ()
Returns the number of arguments enqueued per 3D tensor object.
static constexpr unsigned int num_arguments_per_4D_tensor ()
Returns the number of arguments enqueued per 4D tensor object.
static cl::NDRange gws_from_window (const Window &window)
Get the global work size given an execution window.
Detailed Description
Interface for the batch concatenate kernel.
The input tensor will be concatenated into the output tensor.
Definition at line 38 of file CLBatchConcatenateLayerKernel.h.
Constructor & Destructor Documentation
CLBatchConcatenateLayerKernel() [1/3]
CLBatchConcatenateLayerKernel ()
Default constructor.
Definition at line 85 of file CLBatchConcatenateLayerKernel.cpp.
     : _input(nullptr), _output(nullptr), _batch_offset(0)
 {
 }
CLBatchConcatenateLayerKernel() [2/3]
CLBatchConcatenateLayerKernel (const CLBatchConcatenateLayerKernel &) delete
Prevent instances of this class from being copied (As this class contains pointers)
CLBatchConcatenateLayerKernel() [3/3]
CLBatchConcatenateLayerKernel (CLBatchConcatenateLayerKernel &&) default
Allow instances of this class to be moved.
~CLBatchConcatenateLayerKernel()
~CLBatchConcatenateLayerKernel () default
Default destructor.
Member Function Documentation
configure()
void configure (const ICLTensor * input, unsigned int batch_offset, ICLTensor * output)
Initialise the kernel's inputs and output.
Parameters
[in] input Input tensor. Data types supported: U8/S8/QASYMM8/U16/S16/F16/U32/S32/F32.
[in] batch_offset The offset on axis # 3.
[in,out] output Output tensor. Data types supported: Same as input.
Note
: The output tensor's low two dimensions can't be smaller than the input one's.
: The gaps between the two lowest dimensions of input and output need to be divisible by 2.
Definition at line 90 of file CLBatchConcatenateLayerKernel.cpp.
 {
     ARM_COMPUTE_ERROR_ON_NULLPTR(input, output);
     ARM_COMPUTE_ERROR_THROW_ON(validate_arguments(input->info(), batch_offset, output->info()));
     _input        = input;
     _output       = output;
     _batch_offset = batch_offset;
     const unsigned int num_elems_processed_per_iteration = 16 / input->info()->element_size();
     // Add build options
     CLBuildOptions build_opts;
     build_opts.add_option("-DDATA_TYPE=" + get_underlying_cl_type_from_data_type(input->info()->data_type()));
     build_opts.add_option("-DVEC_SIZE=" + support::cpp11::to_string(num_elems_processed_per_iteration));
     if(is_data_type_quantized_asymmetric(input->info()->data_type()) && input->info()->quantization_info() != output->info()->quantization_info())
     {
         const UniformQuantizationInfo iq_info = input->info()->quantization_info().uniform();
         const UniformQuantizationInfo oq_info = output->info()->quantization_info().uniform();
         build_opts.add_option("-DOFFSET_IN1=" + float_to_string_with_full_precision(iq_info.offset));
         build_opts.add_option("-DOFFSET_OUT=" + float_to_string_with_full_precision(oq_info.offset));
         build_opts.add_option("-DSCALE_IN1=" + float_to_string_with_full_precision(iq_info.scale));
         build_opts.add_option("-DSCALE_OUT=" + float_to_string_with_full_precision(oq_info.scale));
     }
     // Create kernel
     _kernel = static_cast<cl::Kernel>(CLKernelLibrary::get().create_kernel("concatenate", build_opts.options()));
     // Configure kernel window
     auto win_config = validate_and_configure_window(input->info(), batch_offset, output->info());
     ARM_COMPUTE_ERROR_THROW_ON(std::get<0>(win_config));
     ICLKernel::configure_internal(std::get<1>(win_config));
     // Set output valid region
     output->info()->set_valid_region(ValidRegion(Coordinates(), output->info()->tensor_shape()));
     // Set config_id for enabling LWS tuning
     _config_id = "concatenate_";
     _config_id += support::cpp11::to_string(3);
     _config_id += "_";
     _config_id += support::cpp11::to_string(batch_offset);
     _config_id += "_";
     _config_id += support::cpp11::to_string(input->info()->dimension(0));
     _config_id += "_";
     _config_id += support::cpp11::to_string(input->info()->dimension(1));
     _config_id += "_";
     _config_id += support::cpp11::to_string(input->info()->dimension(2));
     _config_id += "_";
     _config_id += support::cpp11::to_string(input->info()->dimension(3));
 }
References CLBuildOptions::add_option(), ARM_COMPUTE_ERROR_ON_NULLPTR, ARM_COMPUTE_ERROR_THROW_ON, arm_compute::create_kernel(), ITensorInfo::data_type(), ITensorInfo::dimension(), ITensorInfo::element_size(), arm_compute::float_to_string_with_full_precision(), CLKernelLibrary::get(), arm_compute::get_underlying_cl_type_from_data_type(), ITensor::info(), arm_compute::is_data_type_quantized_asymmetric(), UniformQuantizationInfo::offset, CLBuildOptions::options(), ITensorInfo::quantization_info(), UniformQuantizationInfo::scale, ITensorInfo::set_valid_region(), ITensorInfo::tensor_shape(), arm_compute::support::cpp11::to_string(), QuantizationInfo::uniform(), and arm_compute::validate_and_configure_window().
operator=() [1/2]
CLBatchConcatenateLayerKernel& operator= (const CLBatchConcatenateLayerKernel &) delete
Prevent instances of this class from being copied (As this class contains pointers)
operator=() [2/2]
CLBatchConcatenateLayerKernel& operator= (CLBatchConcatenateLayerKernel &&) default
Allow instances of this class to be moved.
run()
void run (const Window & window, cl::CommandQueue & queue) override virtual
Enqueue the OpenCL kernel to process the given window on the passed OpenCL command queue.
Note
The queue is not flushed by this method, and therefore the kernel will not have been executed by the time this method returns.
Parameters
[in] window Region on which to execute the kernel. (Must be a valid region of the window returned by window()).
[in,out] queue Command queue on which to enqueue the kernel.
Implements ICLKernel.
Definition at line 152 of file CLBatchConcatenateLayerKernel.cpp.
 {
     ARM_COMPUTE_ERROR_ON_UNCONFIGURED_KERNEL(this);
     ARM_COMPUTE_ERROR_ON_INVALID_SUBWINDOW(ICLKernel::window(), window);
     Window slice = window.first_slice_window_3D();
     const int offset_to_first_elements_in_bytes = _batch_offset * _output->info()->strides_in_bytes()[3];
     unsigned int idx = 2 * num_arguments_per_3D_tensor(); // Skip the input and output parameters
     _kernel.setArg<cl_int>(idx, offset_to_first_elements_in_bytes);
     do
     {
         unsigned int idx = 0;
         add_3D_tensor_argument(idx, _input, slice);
         add_3D_tensor_argument(idx, _output, slice);
         enqueue(queue, *this, slice, lws_hint());
     }
     while(window.slide_window_slice_3D(slice));
 }
References ICLKernel::add_3D_tensor_argument(), ARM_COMPUTE_ERROR_ON_INVALID_SUBWINDOW, ARM_COMPUTE_ERROR_ON_UNCONFIGURED_KERNEL, arm_compute::enqueue(), Window::first_slice_window_3D(), ITensor::info(), ICLKernel::lws_hint(), ICLKernel::num_arguments_per_3D_tensor(), arm_compute::test::validation::reference::slice(), Window::slide_window_slice_3D(), ITensorInfo::strides_in_bytes(), and IKernel::window().
validate()
Status validate (const ITensorInfo * input, unsigned int batch_offset, const ITensorInfo * output) static
Static function to check if given info will lead to a valid configuration of CLBatchConcatenateLayerKernel.
Parameters
[in] input Input tensor info. Data types supported: U8/S8/QASYMM8/U16/S16/F16/U32/S32/F32
[in] batch_offset The offset on axis # 3.
[in] output Output tensor info. Data types supported: Same as input.
Returns
a status
Definition at line 143 of file CLBatchConcatenateLayerKernel.cpp.
 {
     ARM_COMPUTE_RETURN_ON_ERROR(validate_arguments(input, batch_offset, output));
     ARM_COMPUTE_RETURN_ON_ERROR(validate_and_configure_window(input->clone().get(), batch_offset, output->clone().get()).first);
     return Status{};
 }
References ARM_COMPUTE_RETURN_ON_ERROR, ICloneable< T >::clone(), and arm_compute::validate_and_configure_window().
The documentation for this class was generated from the following files:
arm_compute/core/CL/kernels/CLBatchConcatenateLayerKernel.h
src/core/CL/kernels/CLBatchConcatenateLayerKernel.cpp