Compute Library: NEReorgLayerKernel Class Reference
NEReorgLayerKernel Class Reference
Interface for the kernel to perform tensor re-organization.
#include <NEReorgLayerKernel.h>
Public Member Functions
const char * name () const override
Name of the kernel.
NEReorgLayerKernel ()
Default constructor.
NEReorgLayerKernel (const NEReorgLayerKernel &)=delete
Prevent instances of this class from being copied (As this class contains pointers)
NEReorgLayerKernel & operator= (const NEReorgLayerKernel &)=delete
Prevent instances of this class from being copied (As this class contains pointers)
NEReorgLayerKernel (NEReorgLayerKernel &&)=default
Default Move Constructor.
NEReorgLayerKernel & operator= (NEReorgLayerKernel &&)=default
Default move assignment operator.
~NEReorgLayerKernel ()=default
Default destructor.
void configure (const ITensor *input, ITensor *output, int32_t stride)
Set the input and output of the kernel.
void run (const Window &window, const ThreadInfo &info) override
Execute the kernel on the passed window.
Public Member Functions inherited from ICPPKernel
virtual ~ICPPKernel ()=default
Default destructor.
Public Member Functions inherited from IKernel
IKernel ()
Constructor.
virtual ~IKernel ()=default
Destructor.
virtual bool is_parallelisable () const
Indicates whether or not the kernel is parallelisable.
virtual BorderSize border_size () const
The size of the border for that kernel.
const Window & window () const
The maximum window the kernel can be executed on.
Static Public Member Functions
static Status validate (const ITensorInfo *input, const ITensorInfo *output, int32_t stride)
Static function to check if given info will lead to a valid configuration of NEReshapeLayerKernel.
Detailed Description
Interface for the kernel to perform tensor re-organization.
Definition at line 35 of file NEReorgLayerKernel.h.
Constructor & Destructor Documentation
NEReorgLayerKernel() [1/3]
NEReorgLayerKernel ()
Default constructor.
Definition at line 70 of file NEReorgLayerKernel.cpp.
     : _input(nullptr), _output(nullptr), _stride(1)
 {
 }
NEReorgLayerKernel() [2/3]
NEReorgLayerKernel (const NEReorgLayerKernel &) delete
Prevent instances of this class from being copied (As this class contains pointers)
NEReorgLayerKernel() [3/3]
NEReorgLayerKernel (NEReorgLayerKernel &&) default
Default Move Constructor.
~NEReorgLayerKernel()
~NEReorgLayerKernel () default
Default destructor.
Member Function Documentation
configure()
void configure (const ITensor * input, ITensor * output, int32_t stride)
Set the input and output of the kernel.
Parameters
[in] input Source tensor. Data type supported: U8/S8/U16/S16/QASYMM8/U32/S32/F16/F32
[out] output Destination tensor. Data type supported: Same as input
[in] stride Stride to be used during data re-organization. It defines the spatial distance between 2 consecutive pixels in the x and y direction
Definition at line 75 of file NEReorgLayerKernel.cpp.
 {
     ARM_COMPUTE_ERROR_ON_NULLPTR(input, output);
     // Output auto inizialitation if not yet initialized
     const TensorShape output_shape = misc::shape_calculator::compute_reorg_output_shape(*input->info(), stride);
     auto_init_if_empty(*output->info(), input->info()->clone()->set_tensor_shape(output_shape));
     // Perform validation step
     ARM_COMPUTE_ERROR_THROW_ON(validate_arguments(input->info(), output->info(), stride));
     _input  = input;
     _output = output;
     _stride = stride;
     // The NEReorgLayerKernel doesn't need padding so update_window_and_padding() can be skipped
     output->info()->set_valid_region(ValidRegion(Coordinates(), output->info()->tensor_shape()));
     // Configure kernel window
     Window win = calculate_max_window(*output->info(), Steps());
     ICPPKernel::configure(win);
 }
References ARM_COMPUTE_ERROR_ON_NULLPTR, ARM_COMPUTE_ERROR_THROW_ON, arm_compute::auto_init_if_empty(), arm_compute::calculate_max_window(), ICloneable< T >::clone(), arm_compute::misc::shape_calculator::compute_reorg_output_shape(), ITensor::info(), arm_compute::test::validation::output_shape, ITensorInfo::set_valid_region(), and ITensorInfo::tensor_shape().
name()
const char* name () const inline override virtual
Name of the kernel.
Returns
Kernel name
Implements ICPPKernel.
Definition at line 38 of file NEReorgLayerKernel.h.
     {
         return "NEReorgLayerKernel";
     }
operator=() [1/2]
NEReorgLayerKernel& operator= (const NEReorgLayerKernel &) delete
Prevent instances of this class from being copied (As this class contains pointers)
operator=() [2/2]
NEReorgLayerKernel& operator= (NEReorgLayerKernel &&) default
Default move assignment operator.
run()
void run (const Window & window, const ThreadInfo & info) override virtual
Execute the kernel on the passed window.
Warning
If is_parallelisable() returns false then the passed window must be equal to window()
Note
The window has to be a region within the window returned by the window() method
The width of the window has to be a multiple of num_elems_processed_per_iteration().
Parameters
[in] window Region on which to execute the kernel. (Must be a region of the window returned by window())
[in] info Info about executing thread and CPU.
Implements ICPPKernel.
Definition at line 105 of file NEReorgLayerKernel.cpp.
 {
     ARM_COMPUTE_UNUSED(info);
     ARM_COMPUTE_ERROR_ON_UNCONFIGURED_KERNEL(this);
     ARM_COMPUTE_ERROR_ON_INVALID_SUBWINDOW(ICPPKernel::window(), window);
     const DataLayout data_layout = _input->info()->data_layout();
     const size_t     idx_w       = get_data_layout_dimension_index(data_layout, DataLayoutDimension::WIDTH);
     const size_t     idx_h       = get_data_layout_dimension_index(data_layout, DataLayoutDimension::HEIGHT);
     const size_t     idx_c       = get_data_layout_dimension_index(data_layout, DataLayoutDimension::CHANNEL);
     const unsigned int stride = _stride;
     const unsigned int out_c  = _output->info()->tensor_shape()[idx_c] / (stride * stride);
     const uint8_t     *in_ptr = _input->buffer();
     // Collapse
     Window collapsed_window = window.collapse_if_possible(window, 4);
     // Create Iterator
     Iterator out(_output, collapsed_window);
     // Perform reorg
     execute_window_loop(collapsed_window, [&](const Coordinates & id)
     {
         // Get spatial coords and channels
         const unsigned int w = id[idx_w];
         const unsigned int h = id[idx_h];
         const unsigned int c = id[idx_c];
         // Calculate mapping
         const unsigned int offset     = c / out_c;
         Coordinates        map_coords = id;
         map_coords.set(idx_w, w * stride + offset % stride);
         map_coords.set(idx_h, h * stride + offset / stride);
         map_coords.set(idx_c, c % out_c);
         // Perform mapping
         std::memcpy(out.ptr(), in_ptr + _input->info()->offset_element_in_bytes(map_coords), _input->info()->element_size());
     },
     out);
 }
References ARM_COMPUTE_ERROR_ON_INVALID_SUBWINDOW, ARM_COMPUTE_ERROR_ON_UNCONFIGURED_KERNEL, ARM_COMPUTE_UNUSED, ITensor::buffer(), arm_compute::CHANNEL, Window::collapse_if_possible(), arm_compute::test::validation::data_layout, ITensorInfo::data_layout(), ITensorInfo::element_size(), arm_compute::execute_window_loop(), arm_compute::get_data_layout_dimension_index(), arm_compute::HEIGHT, ITensor::info(), arm_compute::test::validation::info, offset(), ITensorInfo::offset_element_in_bytes(), Iterator::ptr(), Dimensions< T >::set(), ITensorInfo::tensor_shape(), arm_compute::test::validation::w, arm_compute::WIDTH, and IKernel::window().
validate()
Status validate (const ITensorInfo * input, const ITensorInfo * output, int32_t stride) static
Static function to check if given info will lead to a valid configuration of NEReshapeLayerKernel.
Parameters
[in] input Source tensor info. Data type supported: U8/S8/U16/S16/QASYMM8/U32/S32/F16/F32
[in] output Destination tensor info. Data type supported: Same as input
[in] stride Stride to be used during data re-organization It defines the spatial distance between 2 consecutive pixels in the x and y direction
Returns
a status
Definition at line 99 of file NEReorgLayerKernel.cpp.
 {
     ARM_COMPUTE_RETURN_ON_ERROR(validate_arguments(input, output, stride));
     return Status{};
 }
References ARM_COMPUTE_RETURN_ON_ERROR.
Referenced by NEReorgLayer::validate().
The documentation for this class was generated from the following files:
arm_compute/core/NEON/kernels/NEReorgLayerKernel.h
src/core/NEON/kernels/NEReorgLayerKernel.cpp