Compute Library: NEMinMaxLocation Class Reference
NEMinMaxLocation Class Reference
Basic function to execute min and max location.
#include <NEMinMaxLocation.h>
Public Member Functions
NEMinMaxLocation ()
Constructor.
void configure (const IImage *input, void *min, void *max, ICoordinates2DArray *min_loc=nullptr, ICoordinates2DArray *max_loc=nullptr, uint32_t *min_count=nullptr, uint32_t *max_count=nullptr)
Initialise the kernel's inputs and outputs.
void run () override
Run the kernels contained in the function.
Public Member Functions inherited from IFunction
virtual ~IFunction ()=default
Destructor.
virtual void prepare ()
Prepare the function for executing.
Detailed Description
Basic function to execute min and max location.
This function calls the following NEON kernels:
NEMinMaxKernel
NEMinMaxLocationKernel
Definition at line 44 of file NEMinMaxLocation.h.
Constructor & Destructor Documentation
NEMinMaxLocation()
NEMinMaxLocation ()
Constructor.
Definition at line 30 of file NEMinMaxLocation.cpp.
     : _min_max(), _min_max_loc()
 {
 }
Member Function Documentation
configure()
void configure (const IImage * input, void * min, void * max, ICoordinates2DArray * min_loc = nullptr, ICoordinates2DArray * max_loc = nullptr, uint32_t * min_count = nullptr, uint32_t * max_count = nullptr)
Initialise the kernel's inputs and outputs.
Parameters
[in] input Input image. Data types supported: U8/S16/F32.
[out] min Minimum value of image. Data types supported: S32 if input type is U8/S16, F32 if input type is F32.
[out] max Maximum value of image. Data types supported: S32 if input type is U8/S16, F32 if input type is F32.
[out] min_loc (Optional) Array of minimum value locations.
[out] max_loc (Optional) Array of maximum value locations.
[out] min_count (Optional) Number of minimum value encounters.
[out] max_count (Optional) Number of maximum value encounters.
Definition at line 35 of file NEMinMaxLocation.cpp.
 {
     _min_max.configure(input, min, max);
     _min_max_loc.configure(input, min, max, min_loc, max_loc, min_count, max_count);
 }
References NEMinMaxKernel::configure(), and NEMinMaxLocationKernel::configure().
Referenced by arm_compute::test::validation::validate_configuration().
run()
void run () override virtual
Run the kernels contained in the function.
For NEON kernels:
Multi-threading is used for the kernels which are parallelisable.
By default std::thread::hardware_concurrency() threads are used.
Note
CPPScheduler::set_num_threads() can be used to manually set the number of threads
For OpenCL kernels:
All the kernels are enqueued on the queue associated with CLScheduler.
The queue is then flushed.
Note
The function will not block until the kernels are executed. It is the user's responsibility to wait.
Will call prepare() on first run if hasn't been done
Implements IFunction.
Definition at line 41 of file NEMinMaxLocation.cpp.
 {
     _min_max.reset();
     /* Run min max kernel */
     NEScheduler::get().schedule(&_min_max, Window::DimY);
     /* Run min max location */
     NEScheduler::get().schedule(&_min_max_loc, Window::DimY);
 }
References Window::DimY, Scheduler::get(), NEMinMaxKernel::reset(), and IScheduler::schedule().
The documentation for this class was generated from the following files:
arm_compute/runtime/NEON/functions/NEMinMaxLocation.h
src/runtime/NEON/functions/NEMinMaxLocation.cpp