Compute Library: AccessWindowAutoPadding Class Reference
AccessWindowAutoPadding Class Reference
Dummy access window.
#include <AccessWindowAutoPadding.h>
Public Member Functions
AccessWindowAutoPadding (ITensorInfo *info)
Default constructor.
AccessWindowAutoPadding (const AccessWindowAutoPadding &)=delete
Prevent instances of this class from being copied (As this class contains pointers)
AccessWindowAutoPadding & operator= (const AccessWindowAutoPadding &)=delete
Prevent instances of this class from being copied (As this class contains pointers)
AccessWindowAutoPadding (AccessWindowAutoPadding &&)=default
Allow instances of this class to be move constructed.
AccessWindowAutoPadding & operator= (AccessWindowAutoPadding &&)=default
Allow instances of this class to be moved.
~AccessWindowAutoPadding ()=default
Default destructor.
void set_valid_region ()
Set the valid region to match the entire tensor.
ValidRegion compute_valid_region () const
Return a valid region that spans across the entire tensor.
bool update_window_if_needed (Window &window) const override
Shrink the window if padding is not large enough.
bool update_padding_if_needed (const Window &window) override
Increase the padding to be large enough for the window.
ValidRegion compute_valid_region (const Window &window, ValidRegion input_valid_region, bool border_undefined, BorderSize border_size) const override
Compute the valid region based on access pattern and valid region of the inputs.
Public Member Functions inherited from IAccessWindow
virtual ~IAccessWindow ()=default
Default virtual destructor.
Detailed Description
Dummy access window.
This implementation always uses the auto padding of the tensor info and never updates the window. The valid region is always set to cover the entire tensor.
Note
This access window is only used during the migration to the new padding system. It will be removed once all kernels have been ported.
Definition at line 47 of file AccessWindowAutoPadding.h.
Constructor & Destructor Documentation
AccessWindowAutoPadding() [1/3]
AccessWindowAutoPadding (ITensorInfo * info)
Default constructor.
Parameters
[in,out] info Tensor info of the accessed kernel.
Definition at line 31 of file AccessWindowAutoPadding.cpp.
     : _info(info)
 {
 }
AccessWindowAutoPadding() [2/3]
AccessWindowAutoPadding (const AccessWindowAutoPadding &) delete
Prevent instances of this class from being copied (As this class contains pointers)
AccessWindowAutoPadding() [3/3]
AccessWindowAutoPadding (AccessWindowAutoPadding &&) default
Allow instances of this class to be move constructed.
~AccessWindowAutoPadding()
~AccessWindowAutoPadding () default
Default destructor.
Member Function Documentation
compute_valid_region() [1/2]
ValidRegion compute_valid_region () const
Return a valid region that spans across the entire tensor.
Returns
a valid region.
Definition at line 46 of file AccessWindowAutoPadding.cpp.
 {
     if(_info == nullptr)
     {
         return ValidRegion{};
     }
     return ValidRegion{ Coordinates(), _info->tensor_shape() };
 }
References ITensorInfo::tensor_shape().
Referenced by AccessWindowAutoPadding::compute_valid_region(), and AccessWindowAutoPadding::set_valid_region().
compute_valid_region() [2/2]
ValidRegion compute_valid_region (const Window & window, ValidRegion input_valid_region, bool border_undefined, BorderSize border_size) const override virtual
Compute the valid region based on access pattern and valid region of the inputs.
Note
This method assumes that there is no border.
Parameters
[in] window Execution window of the kernel.
[in] input_valid_region Combined valid region of all inputs.
[in] border_undefined Undefined borders are excluded from the valid region.
[in] border_size Size of the border around the XY-plane of the tensor.
Returns
a valid region.
Implements IAccessWindow.
Definition at line 36 of file AccessWindowAutoPadding.cpp.
 {
     ARM_COMPUTE_UNUSED(window);
     ARM_COMPUTE_UNUSED(input_valid_region);
     ARM_COMPUTE_UNUSED(border_undefined);
     ARM_COMPUTE_UNUSED(border_size);
     return compute_valid_region();
 }
References ARM_COMPUTE_UNUSED, and AccessWindowAutoPadding::compute_valid_region().
operator=() [1/2]
AccessWindowAutoPadding& operator= (const AccessWindowAutoPadding &) delete
Prevent instances of this class from being copied (As this class contains pointers)
operator=() [2/2]
AccessWindowAutoPadding& operator= (AccessWindowAutoPadding &&) default
Allow instances of this class to be moved.
set_valid_region()
void set_valid_region ()
Set the valid region to match the entire tensor.
Definition at line 56 of file AccessWindowAutoPadding.cpp.
 {
     if(_info == nullptr)
     {
         return;
     }
     _info->set_valid_region(compute_valid_region());
 }
References AccessWindowAutoPadding::compute_valid_region(), and ITensorInfo::set_valid_region().
update_padding_if_needed()
bool update_padding_if_needed (const Window & window) override virtual
Increase the padding to be large enough for the window.
Parameters
[in] window Window used by the kernel.
Returns
True if the padding has been changed.
Implements IAccessWindow.
Definition at line 73 of file AccessWindowAutoPadding.cpp.
 {
     ARM_COMPUTE_UNUSED(window);
     // Only update the padding if the tensor allows it
     if(_info == nullptr || !_info->is_resizable())
     {
         return false;
     }
     // Update strides in tensor info
     return _info->auto_padding();
 }
References ARM_COMPUTE_UNUSED, ITensorInfo::auto_padding(), and ITensorInfo::is_resizable().
update_window_if_needed()
bool update_window_if_needed (Window & window) const override virtual
Shrink the window if padding is not large enough.
Parameters
[in] window Window used by the kernel.
Returns
True if the window has been changed.
Implements IAccessWindow.
Definition at line 66 of file AccessWindowAutoPadding.cpp.
 {
     ARM_COMPUTE_UNUSED(window);
     return false;
 }
References ARM_COMPUTE_UNUSED.
The documentation for this class was generated from the following files:
arm_compute/core/AccessWindowAutoPadding.h
src/core/AccessWindowAutoPadding.cpp