Compute Library: GCConvolutionLayer Class Reference
GCConvolutionLayer Class Reference
Basic function to compute the convolution layer.
#include <GCConvolutionLayer.h>
Public Member Functions
GCConvolutionLayer (std::shared_ptr< IMemoryManager > memory_manager=nullptr)
Default constructor.
GCConvolutionLayer (const GCConvolutionLayer &)=delete
Prevent instances of this class from being copied (As this class contains pointers)
GCConvolutionLayer (GCConvolutionLayer &&)=default
Default move constructor.
GCConvolutionLayer & operator= (const GCConvolutionLayer &)=delete
Prevent instances of this class from being copied (As this class contains pointers)
GCConvolutionLayer & operator= (GCConvolutionLayer &&)=default
Default move assignment operator.
void configure (const IGCTensor *input, const IGCTensor *weights, const IGCTensor *biases, IGCTensor *output, const PadStrideInfo &conv_info, const WeightsInfo &weights_info=WeightsInfo(), const Size2D &dilation=Size2D(1U, 1U), const ActivationLayerInfo &act_info=ActivationLayerInfo(), unsigned int num_groups=1)
Set the input and output tensors.
void run () override
Run the kernels contained in the function.
void prepare () override
Prepare the function for executing.
Public Member Functions inherited from IFunction
virtual ~IFunction ()=default
Destructor.
Detailed Description
Basic function to compute the convolution layer.
This function calls the following GLES kernels:
GCWeightsReshapeKernel (executed only once for each configuration)
GCGEMMTranspose1xWKernel (executed only once for each configuration)
GCIm2ColKernel
GCGEMMInterleave4x4Kernel
GCCol2ImKernel
Definition at line 76 of file GCConvolutionLayer.h.
Constructor & Destructor Documentation
GCConvolutionLayer() [1/3]
GCConvolutionLayer (std::shared_ptr< IMemoryManager > memory_manager = nullptr)
Default constructor.
Definition at line 69 of file GCConvolutionLayer.cpp.
     : _memory_group(std::move(memory_manager)), _reshape_weights(), _input_im2col_kernel(), _mm_gemm(), _output_col2im_kernel(), _fill_border(), _activationlayer_function(), _original_weights(nullptr),
       _input_im2col_reshaped(), _input_interleaved_reshaped(), _weights_reshaped(), _weights_transposed(), _gemm_output(), _tmp_output(), _is_activationlayer_enabled(false), _is_prepared(false)
 {
 }
GCConvolutionLayer() [2/3]
GCConvolutionLayer (const GCConvolutionLayer &) delete
Prevent instances of this class from being copied (As this class contains pointers)
GCConvolutionLayer() [3/3]
GCConvolutionLayer (GCConvolutionLayer &&) default
Default move constructor.
Member Function Documentation
configure()
void configure (const IGCTensor * input, const IGCTensor * weights, const IGCTensor * biases, IGCTensor * output, const PadStrideInfo & conv_info, const WeightsInfo & weights_info = WeightsInfo(), const Size2D & dilation = Size2D(1U, 1U), const ActivationLayerInfo & act_info = ActivationLayerInfo(), unsigned int num_groups = 1)
Set the input and output tensors.
Parameters
[in] input Source tensor. 3 lower dimensions represent a single input [width, height, IFM], while every optional dimension from 4 and above represent a batch of inputs. Data types supported: F16/F32.
[in] weights Weights tensor. Weights are 4D tensor with dimensions [kernel_x, kernel_y, IFM, OFM]. Data type supported: Same as input.
[in] biases Biases tensor. Shared biases supported. Biases are 1D tensor with dimensions [OFM]. Data type supported: Should match input data type, except for input of QASYMM8 type where biases should be of S32 type.
[out] output Destination tensor. 3 lower dimensions represent a single output [width, height, OFM], while the rest represent batch of outputs. Data types supported: Same as input.
[in] conv_info Contains padding and stride information described in PadStrideInfo.
[in] weights_info Specifies if the weights tensor has been reshaped with GCWeightsReshapeKernel. If this is not part of the fully connected layer the weights tensor has also been transposed with GCGEMMTranspose1xWKernel. Data type supported: Same as input.
[in] dilation (Optional) Dilation, in elements, across x and y. Defaults to (1, 1).
[in] act_info (Optional) Activation layer information in case of a fused activation.
[in] num_groups (Optional) Number of groups when performing a grouped convolution. num_groups != 1 is not supported
Definition at line 90 of file GCConvolutionLayer.cpp.
 {
     ARM_COMPUTE_ERROR_ON_NULLPTR(input, weights);
     ARM_COMPUTE_ERROR_ON_DATA_TYPE_CHANNEL_NOT_IN(input, 1, DataType::F16, DataType::F32);
     ARM_COMPUTE_ERROR_ON_MISMATCHING_DATA_TYPES(input, weights);
     ARM_COMPUTE_ERROR_ON_MSG(weights_info.are_reshaped(), "Weights already reshaped are not supported!");
     ARM_COMPUTE_ERROR_ON(weights->info()->dimension(2) != input->info()->dimension(2));
     ARM_COMPUTE_ERROR_ON(weights->info()->num_dimensions() > 4);
     ARM_COMPUTE_ERROR_ON(num_groups > 1);
     ARM_COMPUTE_UNUSED(num_groups);
     _is_prepared      = false;
     _original_weights = weights;
     if(biases != nullptr)
     {
         ARM_COMPUTE_ERROR_ON_MISMATCHING_DATA_TYPES(input, biases);
         ARM_COMPUTE_ERROR_ON(biases->info()->dimension(0) != weights->info()->dimension(3));
         ARM_COMPUTE_ERROR_ON(biases->info()->num_dimensions() > 1);
     }
     const DataType dt = input->info()->data_type();
     // Set the GPU target for im2col and col2im
     _input_im2col_kernel.set_target(GCScheduler::get().get_target());
     _output_col2im_kernel.set_target(GCScheduler::get().get_target());
     const bool       append_bias   = (biases != nullptr);
     const unsigned   bias_element  = (append_bias) ? 1 : 0;
     const IGCTensor *biases_to_use = (append_bias) ? biases : nullptr;
     // Get parameters from conv_info
     unsigned int stride_x = 0;
     unsigned int stride_y = 0;
     std::tie(stride_x, stride_y) = conv_info.stride();
     // Get convolved dimensions
     unsigned int conv_w = 0;
     unsigned int conv_h = 0;
     const unsigned int kernel_width  = weights->info()->dimension(0);
     const unsigned int kernel_height = weights->info()->dimension(1);
     std::tie(conv_w, conv_h) = scaled_dimensions(input->info()->dimension(0), input->info()->dimension(1), kernel_width, kernel_height,
                                                  conv_info, dilation);
     unsigned int mat_weights_cols = weights->info()->dimension(3);
     unsigned int mat_weights_rows = weights->info()->dimension(0) * weights->info()->dimension(1) * weights->info()->dimension(2) + bias_element;
     // _weights_reshaped will be auto configured in the kernel.
     // Just append biases and do not transpose 1xW as it will be reshaped in GCGEMM
     _reshape_weights.configure(weights, biases_to_use, &_weights_reshaped);
     weights = &_weights_reshaped;
     // Create tensor to store im2col reshaped inputs
     const unsigned int mat_input_cols = mat_weights_rows;
     const unsigned int mat_input_rows = conv_w * conv_h;
     TensorShape        shape_im2col   = input->info()->tensor_shape();
     shape_im2col.set(0, mat_input_cols);
     shape_im2col.set(1, mat_input_rows);
     shape_im2col.set(2, 1);
     // FIXME: input->clone() doesn't work with subtensors for grouped convolutions.
     TensorInfo im2col_reshaped_info(shape_im2col, 1, dt);
     _input_im2col_reshaped.allocator()->init(im2col_reshaped_info);
     _memory_group.manage(&_input_im2col_reshaped);
     // Create GEMM output tensor
     TensorShape shape_gemm = _input_im2col_reshaped.info()->tensor_shape();
     shape_gemm.set(0, mat_weights_cols);
     shape_gemm.set(1, mat_input_rows);
     const DataType gemm_data_type = dt;
     // FIXME: input->clone() doesn't work with subtensors for grouped convolutions.
     TensorInfo info_gemm(shape_gemm, 1, gemm_data_type);
     _gemm_output.allocator()->init(info_gemm);
     _memory_group.manage(&_gemm_output);
     if(dt == DataType::F16)
     {
         BorderSize border_size = BorderSize(conv_info.pad_top(), conv_info.pad_right(), conv_info.pad_bottom(), conv_info.pad_left());
         input->info()->extend_padding(border_size);
         _fill_border.configure(input, border_size, BorderMode::CONSTANT, PixelValue()); // for PAD of im2col fp16: consider it as border
     }
     // Configure im2col
     _input_im2col_kernel.configure(input, &_input_im2col_reshaped, Size2D(kernel_width, kernel_height), conv_info, append_bias, dilation);
     // Configure GEMM
     configure_mm(&_input_im2col_reshaped, weights, &_gemm_output);
     _input_im2col_reshaped.allocator()->allocate();
     // Configure Col2Im
     _output_col2im_kernel.configure(&_gemm_output, output, std::make_pair(conv_w, conv_h));
     _gemm_output.allocator()->allocate();
     ARM_COMPUTE_ERROR_ON_MSG((output->info()->dimension(0) != conv_w) || (output->info()->dimension(1) != conv_h), "Output shape does not match the expected one");
     //Configure Activation Layer
     _is_activationlayer_enabled = act_info.enabled();
     if(_is_activationlayer_enabled)
     {
         _activationlayer_function.configure(output, nullptr, act_info);
     }
     ARM_COMPUTE_UNUSED(weights_info);
 }
References arm_compute::test::validation::act_info, ITensorAllocator::allocate(), GCTensor::allocator(), ARM_COMPUTE_ERROR_ON, ARM_COMPUTE_ERROR_ON_DATA_TYPE_CHANNEL_NOT_IN, ARM_COMPUTE_ERROR_ON_MISMATCHING_DATA_TYPES, ARM_COMPUTE_ERROR_ON_MSG, ARM_COMPUTE_ERROR_ON_NULLPTR, ARM_COMPUTE_UNUSED, GCActivationLayer::configure(), GCFillBorderKernel::configure(), GCConvolutionLayerReshapeWeights::configure(), GCCol2ImKernel::configure(), GCIm2ColKernel::configure(), arm_compute::CONSTANT, arm_compute::test::validation::conv_info, ITensorInfo::data_type(), arm_compute::test::validation::dilation, ITensorInfo::dimension(), TensorInfo::dimension(), ITensorInfo::extend_padding(), arm_compute::F16, arm_compute::F32, GCScheduler::get(), ITensor::info(), CLTensor::info(), GCTensor::info(), ITensorAllocator::init(), MemoryGroupBase< TensorType >::manage(), ITensorInfo::num_dimensions(), TensorInfo::num_dimensions(), arm_compute::test::validation::num_groups, arm_compute::scaled_dimensions(), TensorShape::set(), IGCKernel::set_target(), ITensorInfo::tensor_shape(), TensorInfo::tensor_shape(), arm_compute::test::validation::weights, and arm_compute::test::validation::weights_info.
operator=() [1/2]
GCConvolutionLayer& operator= (const GCConvolutionLayer &) delete
Prevent instances of this class from being copied (As this class contains pointers)
operator=() [2/2]
GCConvolutionLayer& operator= (GCConvolutionLayer &&) default
Default move assignment operator.
prepare()
void prepare () override virtual
Prepare the function for executing.
Any one off pre-processing step required by the function is handled here
Note
Prepare stage might not need all the function's buffers' backing memory to be available in order to execute
Reimplemented from IFunction.
Definition at line 226 of file GCConvolutionLayer.cpp.
 {
     if(!_is_prepared)
     {
         ARM_COMPUTE_ERROR_ON(!_original_weights->is_used());
         // Run weights reshaping and mark as unused
         _weights_reshaped.allocator()->allocate();
         _reshape_weights.run();
         // Mark original weights tensor as unused
         _original_weights->mark_as_unused();
         _is_prepared = true;
     }
 }
References ITensorAllocator::allocate(), GCTensor::allocator(), ARM_COMPUTE_ERROR_ON, ITensor::is_used(), ITensor::mark_as_unused(), and GCConvolutionLayerReshapeWeights::run().
Referenced by GCConvolutionLayer::run().
run()
void run () override virtual
Run the kernels contained in the function.
For NEON kernels:
Multi-threading is used for the kernels which are parallelisable.
By default std::thread::hardware_concurrency() threads are used.
Note
CPPScheduler::set_num_threads() can be used to manually set the number of threads
For OpenCL kernels:
All the kernels are enqueued on the queue associated with CLScheduler.
The queue is then flushed.
Note
The function will not block until the kernels are executed. It is the user's responsibility to wait.
Will call prepare() on first run if hasn't been done
Implements IFunction.
Definition at line 200 of file GCConvolutionLayer.cpp.
 {
     prepare();
     MemoryGroupResourceScope scope_mg(_memory_group);
     // Run im2col
     GCScheduler::get().dispatch(_fill_border);
     GCScheduler::get().memory_barrier();
     GCScheduler::get().dispatch(_input_im2col_kernel);
     // Run gemm on reshaped matrices
     _mm_gemm.run();
     GCScheduler::get().memory_barrier();
     // Reshape output matrix
     GCScheduler::get().dispatch(_output_col2im_kernel, false);
     GCScheduler::get().memory_barrier();
     // Run Activation Layer
     if(_is_activationlayer_enabled)
     {
         _activationlayer_function.run();
     }
 }
References GCScheduler::dispatch(), GCScheduler::get(), GCScheduler::memory_barrier(), GCConvolutionLayer::prepare(), IGCSimpleFunction::run(), and GCGEMM::run().
The documentation for this class was generated from the following files:
arm_compute/runtime/GLES_COMPUTE/functions/GCConvolutionLayer.h
src/runtime/GLES_COMPUTE/functions/GCConvolutionLayer.cpp