Compute Library: CLFFT1D Class Reference
CLFFT1D Class Reference
Basic function to execute one dimensional FFT.
#include <CLFFT1D.h>
Public Member Functions
CLFFT1D (std::shared_ptr< IMemoryManager > memory_manager=nullptr)
Default Constructor.
void configure (const ICLTensor *input, ICLTensor *output, const FFT1DInfo &config)
Initialise the function's source, destinations and border mode.
void run () override
Run the kernels contained in the function.
Public Member Functions inherited from IFunction
virtual ~IFunction ()=default
Destructor.
virtual void prepare ()
Prepare the function for executing.
Static Public Member Functions
static Status validate (const ITensorInfo *input, const ITensorInfo *output, const FFT1DInfo &config)
Static function to check if given info will lead to a valid configuration of CLFFT1D.
Detailed Description
Basic function to execute one dimensional FFT.
This function calls the following OpenCL kernels:
CLFFTDigitReverseKernel Performs digit reverse.
CLFFTRadixStageKernel A list of FFT kernels depending on the radix decomposition.
CLFFTScaleKernel Performs output scaling in case of in inverse FFT.
Definition at line 47 of file CLFFT1D.h.
Constructor & Destructor Documentation
CLFFT1D()
CLFFT1D (std::shared_ptr< IMemoryManager > memory_manager = nullptr)
Default Constructor.
Definition at line 33 of file CLFFT1D.cpp.
     : _memory_group(std::move(memory_manager)), _digit_reverse_kernel(), _fft_kernels(), _scale_kernel(), _digit_reversed_input(), _digit_reverse_indices(), _num_ffts(0), _run_scale(false)
 {
 }
Member Function Documentation
configure()
void configure (const ICLTensor * input, ICLTensor * output, const FFT1DInfo & config)
Initialise the function's source, destinations and border mode.
Parameters
[in] input Source tensor. Data types supported: F32.
[out] output Destination tensor. Data types and data layouts supported: Same as input.
[in] config FFT related configuration
Definition at line 38 of file CLFFT1D.cpp.
 {
     ARM_COMPUTE_ERROR_ON_NULLPTR(input, output);
     ARM_COMPUTE_ERROR_THROW_ON(CLFFT1D::validate(input->info(), output->info(), config));
     // Decompose size to radix factors
     const auto         supported_radix   = CLFFTRadixStageKernel::supported_radix();
     const unsigned int N                 = input->info()->tensor_shape()[config.axis];
     const auto         decomposed_vector = arm_compute::helpers::fft::decompose_stages(N, supported_radix);
     ARM_COMPUTE_ERROR_ON(decomposed_vector.empty());
     // Flags
     _run_scale        = config.direction == FFTDirection::Inverse;
     const bool is_c2r = input->info()->num_channels() == 2 && output->info()->num_channels() == 1;
     // Configure digit reverse
     FFTDigitReverseKernelInfo digit_reverse_config;
     digit_reverse_config.axis      = config.axis;
     digit_reverse_config.conjugate = config.direction == FFTDirection::Inverse;
     TensorInfo digit_reverse_indices_info(TensorShape(input->info()->tensor_shape()[config.axis]), 1, DataType::U32);
     _digit_reverse_indices.allocator()->init(digit_reverse_indices_info);
     _memory_group.manage(&_digit_reversed_input);
     _digit_reverse_kernel.configure(input, &_digit_reversed_input, &_digit_reverse_indices, digit_reverse_config);
     // Create and configure FFT kernels
     unsigned int Nx = 1;
     _num_ffts       = decomposed_vector.size();
     _fft_kernels.resize(_num_ffts);
     for(unsigned int i = 0; i < _num_ffts; ++i)
     {
         const unsigned int radix_for_stage = decomposed_vector.at(i);
         FFTRadixStageKernelInfo fft_kernel_info;
         fft_kernel_info.axis           = config.axis;
         fft_kernel_info.radix          = radix_for_stage;
         fft_kernel_info.Nx             = Nx;
         fft_kernel_info.is_first_stage = (i == 0);
         _fft_kernels[i].configure(&_digit_reversed_input, ((i == (_num_ffts - 1)) && !is_c2r) ? output : nullptr, fft_kernel_info);
         Nx *= radix_for_stage;
     }
     // Configure scale kernel
     if(_run_scale)
     {
         FFTScaleKernelInfo scale_config;
         scale_config.scale     = static_cast<float>(N);
         scale_config.conjugate = config.direction == FFTDirection::Inverse;
         is_c2r ? _scale_kernel.configure(&_digit_reversed_input, output, scale_config) : _scale_kernel.configure(output, nullptr, scale_config);
     }
     // Allocate tensors
     _digit_reversed_input.allocator()->allocate();
     _digit_reverse_indices.allocator()->allocate();
     // Init digit reverse indices
     const auto digit_reverse_cpu = arm_compute::helpers::fft::digit_reverse_indices(N, decomposed_vector);
     _digit_reverse_indices.map(CLScheduler::get().queue(), true);
     std::copy_n(digit_reverse_cpu.data(), N, reinterpret_cast<unsigned int *>(_digit_reverse_indices.buffer()));
     _digit_reverse_indices.unmap(CLScheduler::get().queue());
 }
References CLTensorAllocator::allocate(), CLTensor::allocator(), ARM_COMPUTE_ERROR_ON, ARM_COMPUTE_ERROR_ON_NULLPTR, ARM_COMPUTE_ERROR_THROW_ON, FFT1DInfo::axis, FFTDigitReverseKernelInfo::axis, FFTRadixStageKernelInfo::axis, ICLTensor::buffer(), CLFFTScaleKernel::configure(), CLFFTDigitReverseKernel::configure(), FFTScaleKernelInfo::conjugate, FFTDigitReverseKernelInfo::conjugate, arm_compute::helpers::fft::decompose_stages(), arm_compute::helpers::fft::digit_reverse_indices(), FFT1DInfo::direction, CLScheduler::get(), ITensor::info(), ITensorAllocator::init(), arm_compute::Inverse, FFTRadixStageKernelInfo::is_first_stage, MemoryGroupBase< TensorType >::manage(), CLTensor::map(), ITensorInfo::num_channels(), FFTRadixStageKernelInfo::Nx, FFTRadixStageKernelInfo::radix, FFTScaleKernelInfo::scale, CLFFTRadixStageKernel::supported_radix(), ITensorInfo::tensor_shape(), arm_compute::U32, CLTensor::unmap(), and CLFFT1D::validate().
Referenced by CLFFT2D::configure(), and arm_compute::test::validation::DATA_TEST_CASE().
run()
void run () override virtual
Run the kernels contained in the function.
For NEON kernels:
Multi-threading is used for the kernels which are parallelisable.
By default std::thread::hardware_concurrency() threads are used.
Note
CPPScheduler::set_num_threads() can be used to manually set the number of threads
For OpenCL kernels:
All the kernels are enqueued on the queue associated with CLScheduler.
The queue is then flushed.
Note
The function will not block until the kernels are executed. It is the user's responsibility to wait.
Will call prepare() on first run if hasn't been done
Implements IFunction.
Definition at line 125 of file CLFFT1D.cpp.
 {
     MemoryGroupResourceScope scope_mg(_memory_group);
     // Run digit reverse
     CLScheduler::get().enqueue(_digit_reverse_kernel, false);
     // Run radix kernels
     for(unsigned int i = 0; i < _num_ffts; ++i)
     {
         CLScheduler::get().enqueue(_fft_kernels[i], i == (_num_ffts - 1) && !_run_scale);
     }
     // Run output scaling
     if(_run_scale)
     {
         CLScheduler::get().enqueue(_scale_kernel, true);
     }
 }
References CLScheduler::enqueue(), and CLScheduler::get().
Referenced by CLFFT2D::run().
validate()
Status validate (const ITensorInfo * input, const ITensorInfo * output, const FFT1DInfo & config) static
Static function to check if given info will lead to a valid configuration of CLFFT1D.
Parameters
[in] input Source tensor info. Data types supported: F32.
[in] output Destination tensor info. Data types and data layouts supported: Same as input.
[in] config FFT related configuration
Returns
a status
Definition at line 100 of file CLFFT1D.cpp.
 {
     ARM_COMPUTE_RETURN_ERROR_ON_NULLPTR(input, output);
     ARM_COMPUTE_RETURN_ERROR_ON(input->data_type() != DataType::F32);
     ARM_COMPUTE_RETURN_ERROR_ON(input->num_channels() != 1 && input->num_channels() != 2);
     ARM_COMPUTE_RETURN_ERROR_ON(std::set<unsigned int>({ 0, 1 }).count(config.axis) == 0);
     // Check if FFT is decomposable
     const auto         supported_radix   = CLFFTRadixStageKernel::supported_radix();
     const unsigned int N                 = input->tensor_shape()[config.axis];
     const auto         decomposed_vector = arm_compute::helpers::fft::decompose_stages(N, supported_radix);
     ARM_COMPUTE_RETURN_ERROR_ON(decomposed_vector.empty());
     // Checks performed when output is configured
     if((output != nullptr) && (output->total_size() != 0))
     {
         ARM_COMPUTE_RETURN_ERROR_ON(output->num_channels() == 1 && input->num_channels() == 1);
         ARM_COMPUTE_RETURN_ERROR_ON(output->num_channels() != 1 && output->num_channels() != 2);
         ARM_COMPUTE_RETURN_ERROR_ON_MISMATCHING_SHAPES(input, output);
         ARM_COMPUTE_RETURN_ERROR_ON_MISMATCHING_DATA_TYPES(input, output);
     }
     return Status{};
 }
References ARM_COMPUTE_RETURN_ERROR_ON, ARM_COMPUTE_RETURN_ERROR_ON_MISMATCHING_DATA_TYPES, ARM_COMPUTE_RETURN_ERROR_ON_MISMATCHING_SHAPES, ARM_COMPUTE_RETURN_ERROR_ON_NULLPTR, FFT1DInfo::axis, ITensorInfo::data_type(), arm_compute::helpers::fft::decompose_stages(), arm_compute::F32, ITensorInfo::num_channels(), CLFFTRadixStageKernel::supported_radix(), ITensorInfo::tensor_shape(), and ITensorInfo::total_size().
Referenced by CLFFT1D::configure(), and CLFFT2D::validate().
The documentation for this class was generated from the following files:
arm_compute/runtime/CL/functions/CLFFT1D.h
src/runtime/CL/functions/CLFFT1D.cpp