Compute Library: CLMeanStdDev Class Reference
CLMeanStdDev Class Reference
Basic function to execute mean and standard deviation by calling CLMeanStdDevKernel.
#include <CLMeanStdDev.h>
Public Member Functions
CLMeanStdDev (std::shared_ptr< IMemoryManager > memory_manager=nullptr)
Default Constructor.
CLMeanStdDev (const CLMeanStdDev &)=delete
Prevent instances of this class from being copied (As this class contains pointers)
CLMeanStdDev & operator= (const CLMeanStdDev &)=delete
Prevent instances of this class from being copied (As this class contains pointers)
CLMeanStdDev (CLMeanStdDev &&)=default
Allow instances of this class to be moved.
CLMeanStdDev & operator= (CLMeanStdDev &&)=default
Allow instances of this class to be moved.
~CLMeanStdDev ()=default
Default destructor.
void configure (ICLImage *input, float *mean, float *stddev=nullptr)
Initialise the kernel's inputs and outputs.
void run () override
Run the kernels contained in the function.
Public Member Functions inherited from IFunction
virtual ~IFunction ()=default
Destructor.
virtual void prepare ()
Prepare the function for executing.
Static Public Member Functions
static Status validate (ITensorInfo *input, float *mean, float *stddev=nullptr)
Static function to check if given info will lead to a valid configuration of CLMeanStdDev.
Detailed Description
Basic function to execute mean and standard deviation by calling CLMeanStdDevKernel.
Definition at line 38 of file CLMeanStdDev.h.
Constructor & Destructor Documentation
CLMeanStdDev() [1/3]
CLMeanStdDev (std::shared_ptr< IMemoryManager > memory_manager = nullptr)
Default Constructor.
Definition at line 31 of file CLMeanStdDev.cpp.
     : _memory_group(std::move(memory_manager)),
       _data_type(),
       _num_pixels(),
       _run_stddev(),
       _reduction_operation_mean(),
       _reduction_operation_stddev(),
       _reduction_output_mean(),
       _reduction_output_stddev(),
       _mean(nullptr),
       _stddev(nullptr),
       _mean_stddev_kernel(),
       _fill_border_kernel(),
       _global_sum(),
       _global_sum_squared()
 {
 }
CLMeanStdDev() [2/3]
CLMeanStdDev (const CLMeanStdDev &) delete
Prevent instances of this class from being copied (As this class contains pointers)
CLMeanStdDev() [3/3]
CLMeanStdDev (CLMeanStdDev &&) default
Allow instances of this class to be moved.
~CLMeanStdDev()
~CLMeanStdDev () default
Default destructor.
Member Function Documentation
configure()
void configure (ICLImage * input, float * mean, float * stddev = nullptr)
Initialise the kernel's inputs and outputs.
Parameters
[in,out] input Input image. Data types supported: U8/F16/F32. (Written to only for border filling)
[out] mean Output average pixel value.
[out] stddev (Optional) Output standard deviation of pixel values.
Definition at line 67 of file CLMeanStdDev.cpp.
 {
     // In the case of F16/F32 we call reduction operation for calculating CLMeanStdDev
     _data_type = input->info()->data_type();
     if(is_data_type_float(_data_type))
     {
         _num_pixels = input->info()->dimension(0) * input->info()->dimension(1);
         _memory_group.manage(&_reduction_output_mean);
         _reduction_operation_mean.configure(input, &_reduction_output_mean, 0, ReductionOperation::SUM);
         _reduction_output_mean.allocator()->allocate();
         _mean = mean;
         if(stddev != nullptr)
         {
             _memory_group.manage(&_reduction_output_stddev);
             _reduction_operation_stddev.configure(input, &_reduction_output_stddev, 0, ReductionOperation::SUM_SQUARE);
             _reduction_output_stddev.allocator()->allocate();
             _stddev     = stddev;
             _run_stddev = true;
         }
     }
     else
     {
         _global_sum = cl::Buffer(CLScheduler::get().context(), CL_MEM_ALLOC_HOST_PTR | CL_MEM_READ_WRITE, sizeof(cl_ulong));
         if(stddev != nullptr)
         {
             _global_sum_squared = cl::Buffer(CLScheduler::get().context(), CL_MEM_ALLOC_HOST_PTR | CL_MEM_READ_WRITE, sizeof(cl_ulong));
         }
         _mean_stddev_kernel.configure(input, mean, &_global_sum, stddev, &_global_sum_squared);
         _fill_border_kernel.configure(input, _mean_stddev_kernel.border_size(), BorderMode::CONSTANT, PixelValue(static_cast<uint8_t>(0)));
     }
 }
References CLTensorAllocator::allocate(), CLTensor::allocator(), CLMeanStdDevKernel::border_size(), CLFillBorderKernel::configure(), CLReductionOperation::configure(), CLMeanStdDevKernel::configure(), arm_compute::CONSTANT, ITensorInfo::data_type(), ITensorInfo::dimension(), CLScheduler::get(), ITensor::info(), arm_compute::is_data_type_float(), MemoryGroupBase< TensorType >::manage(), arm_compute::SUM, and arm_compute::SUM_SQUARE.
operator=() [1/2]
CLMeanStdDev& operator= (const CLMeanStdDev &) delete
Prevent instances of this class from being copied (As this class contains pointers)
operator=() [2/2]
CLMeanStdDev& operator= (CLMeanStdDev &&) default
Allow instances of this class to be moved.
run()
void run () override virtual
Run the kernels contained in the function.
For NEON kernels:
Multi-threading is used for the kernels which are parallelisable.
By default std::thread::hardware_concurrency() threads are used.
Note
CPPScheduler::set_num_threads() can be used to manually set the number of threads
For OpenCL kernels:
All the kernels are enqueued on the queue associated with CLScheduler.
The queue is then flushed.
Note
The function will not block until the kernels are executed. It is the user's responsibility to wait.
Will call prepare() on first run if hasn't been done
Implements IFunction.
Definition at line 151 of file CLMeanStdDev.cpp.
 {
     switch(_data_type)
     {
         case DataType::F16:
             run_float<half>();
             break;
         case DataType::F32:
             run_float<float>();
             break;
         case DataType::U8:
             run_int();
             break;
         default:
             ARM_COMPUTE_ERROR_ON("Not supported");
     }
 }
References ARM_COMPUTE_ERROR_ON, arm_compute::F16, arm_compute::F32, and arm_compute::U8.
validate()
Status validate (ITensorInfo * input, float * mean, float * stddev = nullptr) static
Static function to check if given info will lead to a valid configuration of CLMeanStdDev.
Parameters
[in] input Input image. Data types supported: U8/F16/F32.
[in] mean Output average pixel value.
[in] stddev (Optional) Output standard deviation of pixel values.
Returns
a status
Definition at line 49 of file CLMeanStdDev.cpp.
 {
     ARM_COMPUTE_RETURN_ERROR_ON_TENSOR_NOT_2D(input);
     if(is_data_type_float(input->data_type()))
     {
         ARM_COMPUTE_UNUSED(mean);
         ARM_COMPUTE_UNUSED(stddev);
         TensorShape output_shape      = TensorShape{ 1, input->dimension(1) };
         TensorInfo  output_shape_info = TensorInfo(output_shape, 1, DataType::U8);
         return CLReductionOperation::validate(input, &output_shape_info, 0, ReductionOperation::SUM);
     }
     else
     {
         return CLMeanStdDevKernel::validate(input, mean, nullptr, stddev, nullptr);
     }
 }
References ARM_COMPUTE_RETURN_ERROR_ON_TENSOR_NOT_2D, ARM_COMPUTE_UNUSED, ITensorInfo::data_type(), ITensorInfo::dimension(), arm_compute::is_data_type_float(), arm_compute::test::validation::output_shape, arm_compute::SUM, arm_compute::U8, CLMeanStdDevKernel::validate(), and CLReductionOperation::validate().
The documentation for this class was generated from the following files:
arm_compute/runtime/CL/functions/CLMeanStdDev.h
src/runtime/CL/functions/CLMeanStdDev.cpp