Compute Library: NEGEMMLowpQuantizeDownInt32ToUint8ScaleKernel Class Reference
NEGEMMLowpQuantizeDownInt32ToUint8ScaleKernel Class Reference
NEON kernel used to quantize down the int32 accumulator values of GEMMLowp to QASYMM8.
#include <NEGEMMLowpQuantizeDownInt32ToUint8ScaleKernel.h>
Public Member Functions
const char * name () const override
Name of the kernel.
NEGEMMLowpQuantizeDownInt32ToUint8ScaleKernel ()
Constructor.
NEGEMMLowpQuantizeDownInt32ToUint8ScaleKernel (const NEGEMMLowpQuantizeDownInt32ToUint8ScaleKernel &)=delete
Prevent instances of this class from being copied (As this class contains pointers)
NEGEMMLowpQuantizeDownInt32ToUint8ScaleKernel & operator= (const NEGEMMLowpQuantizeDownInt32ToUint8ScaleKernel &)=delete
Prevent instances of this class from being copied (As this class contains pointers)
NEGEMMLowpQuantizeDownInt32ToUint8ScaleKernel (NEGEMMLowpQuantizeDownInt32ToUint8ScaleKernel &&)=default
Allow instances of this class to be moved.
NEGEMMLowpQuantizeDownInt32ToUint8ScaleKernel & operator= (NEGEMMLowpQuantizeDownInt32ToUint8ScaleKernel &&)=default
Allow instances of this class to be moved.
void configure (const ITensor *input, const ITensor *bias, ITensor *output, int result_offset, int result_mult_int, int result_shift, int min=0, int max=0)
Initialise the kernel's input and output.
void run (const Window &window, const ThreadInfo &info) override
Execute the kernel on the passed window.
Public Member Functions inherited from ICPPKernel
virtual ~ICPPKernel ()=default
Default destructor.
Public Member Functions inherited from IKernel
IKernel ()
Constructor.
virtual ~IKernel ()=default
Destructor.
virtual bool is_parallelisable () const
Indicates whether or not the kernel is parallelisable.
virtual BorderSize border_size () const
The size of the border for that kernel.
const Window & window () const
The maximum window the kernel can be executed on.
Static Public Member Functions
static Status validate (const ITensorInfo *input, const ITensorInfo *bias, const ITensorInfo *output, int min=0, int max=0)
Static function to check if given info will lead to a valid configuration of NEGEMMLowpQuantizeDownInt32ToUint8ScaleKernel.
Detailed Description
NEON kernel used to quantize down the int32 accumulator values of GEMMLowp to QASYMM8.
This kernel takes a final int32 accumulator value (the output of NEGEMMLowpMatrixMultiplyKernel), and processes it to obtain the final QASYMM8 value. The following computations will be performed by the kernel:
Add offset terms to final result
Multiply each entry of result by result_mult_int
Add bias to final result if bias tensor is not a nullptr
Shift the int32 accumulator by result_shift
Clamp the value between the specified min and max bounds
Clamp the resulting int32 values to the [0..255] range and cast to QASYMM8.
Definition at line 46 of file NEGEMMLowpQuantizeDownInt32ToUint8ScaleKernel.h.
Constructor & Destructor Documentation
NEGEMMLowpQuantizeDownInt32ToUint8ScaleKernel() [1/3]
NEGEMMLowpQuantizeDownInt32ToUint8ScaleKernel ()
Constructor.
Definition at line 293 of file NEGEMMLowpQuantizeDownInt32ToUint8ScaleKernel.cpp.
     : _func(nullptr), _input(nullptr), _bias(nullptr), _output(nullptr), _result_offset(0), _result_mult_int(0), _result_shift(0), _min(0), _max(0)
 {
 }
NEGEMMLowpQuantizeDownInt32ToUint8ScaleKernel() [2/3]
NEGEMMLowpQuantizeDownInt32ToUint8ScaleKernel (const NEGEMMLowpQuantizeDownInt32ToUint8ScaleKernel &) delete
Prevent instances of this class from being copied (As this class contains pointers)
NEGEMMLowpQuantizeDownInt32ToUint8ScaleKernel() [3/3]
NEGEMMLowpQuantizeDownInt32ToUint8ScaleKernel (NEGEMMLowpQuantizeDownInt32ToUint8ScaleKernel &&) default
Allow instances of this class to be moved.
Member Function Documentation
configure()
void configure (const ITensor * input, const ITensor * bias, ITensor * output, int result_offset, int result_mult_int, int result_shift, int min = 0, int max = 0)
Initialise the kernel's input and output.
Parameters
[in] input Input tensor. Data type supported: S32
[in] bias Biases tensor. Only shared biases supported and it can be a nullptr if the biases addition is not required. Biases are 1D tensor with dimensions [OFM]. Data type supported: Same as input.
[out] output Output tensor. Data type supported: Data type supported: QASYMM8
[in] result_offset Offset to be added to each element of the input matrix
[in] result_mult_int Value to be multiplied to each element of the input matrix when once the result_offset has been add
[in] result_shift Number of bits to shift right the result before converting back to QASYMM8
[in] min (Optional) Min value used to saturate down the output result before converting back to QASYMM8
[in] max (Optional) Max value used to saturate up the output result before converting back to QASYMM8, Along with min, this value can be used to implement "rectified linear unit" activation functions
Definition at line 298 of file NEGEMMLowpQuantizeDownInt32ToUint8ScaleKernel.cpp.
 {
     // Perform validate step
     ARM_COMPUTE_ERROR_ON_NULLPTR(input, output);
     // Output auto inizialitation if not yet initialized
     auto_init_if_empty(*output->info(), input->info()->clone()->set_data_type(DataType::QASYMM8));
     ARM_COMPUTE_ERROR_THROW_ON(validate_arguments(input->info(),
                                                   (bias != nullptr) ? bias->info() : nullptr,
                                                   output->info(),
                                                   min,
                                                   max));
     _input           = input;
     _bias            = bias;
     _output          = output;
     _result_offset   = result_offset;
     _result_mult_int = result_mult_int;
     _result_shift    = result_shift;
     _min             = min;
     _max             = max;
     // Configure kernel window
     auto win_config = validate_and_configure_window(input->info(), (bias != nullptr) ? bias->info() : nullptr, output->info());
     ARM_COMPUTE_ERROR_THROW_ON(win_config.first);
     INEKernel::configure(win_config.second);
     // Check if we need to clamp the result using min and max
     const bool is_bounded_relu = ((min != max) && !(min == 0 && max == 255));
     _func                      = is_bounded_relu ? &NEGEMMLowpQuantizeDownInt32ToUint8ScaleKernel::run<true> : &NEGEMMLowpQuantizeDownInt32ToUint8ScaleKernel::run<false>;
 }
References ARM_COMPUTE_ERROR_ON_NULLPTR, ARM_COMPUTE_ERROR_THROW_ON, arm_compute::auto_init_if_empty(), arm_compute::test::validation::bias, ICloneable< T >::clone(), ITensor::info(), CLTensor::info(), arm_compute::QASYMM8, and arm_compute::validate_and_configure_window().
name()
const char* name () const inline override virtual
Name of the kernel.
Returns
Kernel name
Implements ICPPKernel.
Definition at line 49 of file NEGEMMLowpQuantizeDownInt32ToUint8ScaleKernel.h.
     {
         return "NEGEMMLowpQuantizeDownInt32ToUint8ScaleKernel";
     }
operator=() [1/2]
NEGEMMLowpQuantizeDownInt32ToUint8ScaleKernel& operator= (const NEGEMMLowpQuantizeDownInt32ToUint8ScaleKernel &) delete
Prevent instances of this class from being copied (As this class contains pointers)
operator=() [2/2]
NEGEMMLowpQuantizeDownInt32ToUint8ScaleKernel& operator= (NEGEMMLowpQuantizeDownInt32ToUint8ScaleKernel &&) default
Allow instances of this class to be moved.
run()
void run (const Window & window, const ThreadInfo & info) override virtual
Execute the kernel on the passed window.
Warning
If is_parallelisable() returns false then the passed window must be equal to window()
Note
The window has to be a region within the window returned by the window() method
The width of the window has to be a multiple of num_elems_processed_per_iteration().
Parameters
[in] window Region on which to execute the kernel. (Must be a region of the window returned by window())
[in] info Info about executing thread and CPU.
Implements ICPPKernel.
Definition at line 343 of file NEGEMMLowpQuantizeDownInt32ToUint8ScaleKernel.cpp.
 {
     ARM_COMPUTE_UNUSED(info);
     ARM_COMPUTE_ERROR_ON_UNCONFIGURED_KERNEL(this);
     ARM_COMPUTE_ERROR_ON_INVALID_SUBWINDOW(INEKernel::window(), window);
     (this->*_func)(window);
 }
References ARM_COMPUTE_ERROR_ON_INVALID_SUBWINDOW, ARM_COMPUTE_ERROR_ON_UNCONFIGURED_KERNEL, ARM_COMPUTE_UNUSED, arm_compute::test::validation::info, and IKernel::window().
validate()
Status validate (const ITensorInfo * input, const ITensorInfo * bias, const ITensorInfo * output, int min = 0, int max = 0) static
Static function to check if given info will lead to a valid configuration of NEGEMMLowpQuantizeDownInt32ToUint8ScaleKernel.
Parameters
[in] input Input tensor. Data type supported: S32
[in] bias Biases tensor. Only shared biases supported and it can be a nullptr if the biases addition is not required. Biases are 1D tensor with dimensions [OFM]. Data type supported: Same as input.
[in] output Output tensor. Data type supported: Data type supported: QASYMM8
[in] min (Optional) Min value used to saturate down the output result before converting back to QASYMM8
[in] max (Optional) Max value used to saturate up the output result before converting back to QASYMM8, Along with min, this value can be used to implement "rectified linear unit" activation functions
Returns
a status
Definition at line 331 of file NEGEMMLowpQuantizeDownInt32ToUint8ScaleKernel.cpp.
 {
     ARM_COMPUTE_ERROR_ON_NULLPTR(input, output);
     ARM_COMPUTE_RETURN_ON_ERROR(validate_arguments(input, bias, output, min, max));
     ARM_COMPUTE_RETURN_ON_ERROR(validate_and_configure_window(input->clone().get(),
                                                               (bias != nullptr) ? bias->clone().get() : nullptr,
                                                               output->clone().get())
                                 .first);
     return Status{};
 }
References ARM_COMPUTE_ERROR_ON_NULLPTR, ARM_COMPUTE_RETURN_ON_ERROR, arm_compute::test::validation::bias, ICloneable< T >::clone(), and arm_compute::validate_and_configure_window().
Referenced by NEGEMMLowpQuantizeDownInt32ToUint8Scale::validate().
The documentation for this class was generated from the following files:
arm_compute/core/NEON/kernels/NEGEMMLowpQuantizeDownInt32ToUint8ScaleKernel.h
src/core/NEON/kernels/NEGEMMLowpQuantizeDownInt32ToUint8ScaleKernel.cpp