Compute Library: CLSubTensor Class Reference
CLSubTensor Class Reference
Basic implementation of the OpenCL sub-tensor interface.
#include <CLSubTensor.h>
Public Member Functions
CLSubTensor ()
Default Constructor.
CLSubTensor (ICLTensor *parent, const TensorShape &tensor_shape, const Coordinates &coords, bool extend_parent=false)
Constructor.
~CLSubTensor ()=default
Destructor: free the tensor's memory.
CLSubTensor (const CLSubTensor &)=delete
Restrict instances of this class to be copy constructed.
CLSubTensor & operator= (const CLSubTensor &)=delete
Restrict instances of this class to be copied.
CLSubTensor (CLSubTensor &&)=default
Allow instances of this class to be move constructed.
CLSubTensor & operator= (CLSubTensor &&)=default
Allow instances of this class to be moved.
void map (bool blocking=true)
Enqueue a map operation of the allocated buffer.
void unmap ()
Enqueue an unmap operation of the allocated and mapped buffer.
ICLTensor * parent ()
Return the parent tensor of the subtensor.
ITensorInfo * info () const override
Interface to be implemented by the child class to return the tensor's metadata.
ITensorInfo * info () override
Interface to be implemented by the child class to return the tensor's metadata.
const cl::Buffer & cl_buffer () const override
Interface to be implemented by the child class to return a reference to the OpenCL buffer containing the image's data.
CLQuantization quantization () const override
Interface to be implemented by the child class to return the wrapped quantization info data.
void map (cl::CommandQueue &q, bool blocking=true)
Enqueue a map operation of the allocated buffer on the given queue.
void unmap (cl::CommandQueue &q)
Enqueue an unmap operation of the allocated and mapped buffer on the given queue.
Public Member Functions inherited from ICLTensor
ICLTensor ()
Default constructor.
ICLTensor (const ICLTensor &)=delete
Prevent instances of this class from being copy constructed.
ICLTensor & operator= (const ICLTensor &)=delete
Prevent instances of this class from being copied.
ICLTensor (ICLTensor &&)=default
Allow instances of this class to be move constructed.
ICLTensor & operator= (ICLTensor &&)=default
Allow instances of this class to be copied.
virtual ~ICLTensor ()=default
Default virtual destructor.
void map (cl::CommandQueue &q, bool blocking=true)
Enqueue a map operation of the allocated buffer on the given queue.
void unmap (cl::CommandQueue &q)
Enqueue an unmap operation of the allocated and mapped buffer on the given queue.
void clear (cl::CommandQueue &q)
Clear the contents of the tensor synchronously.
uint8_t * buffer () const override
Interface to be implemented by the child class to return a pointer to CPU memory.
Public Member Functions inherited from ITensor
virtual ~ITensor ()=default
Default virtual destructor.
uint8_t * ptr_to_element (const Coordinates &id) const
Return a pointer to the element at the passed coordinates.
void copy_from (const ITensor &src)
Copy the content of another tensor.
void print (std::ostream &s, IOFormatInfo io_fmt=IOFormatInfo()) const
Print a tensor to a given stream using user defined formatting information.
bool is_used () const
Flags if the tensor is used or not.
void mark_as_unused () const
Marks a tensor as unused.
Detailed Description
Basic implementation of the OpenCL sub-tensor interface.
Definition at line 37 of file CLSubTensor.h.
Constructor & Destructor Documentation
CLSubTensor() [1/4]
CLSubTensor ()
Default Constructor.
Definition at line 32 of file CLSubTensor.cpp.
     : _parent(nullptr), _info()
 {
 }
CLSubTensor() [2/4]
CLSubTensor (ICLTensor * parent, const TensorShape & tensor_shape, const Coordinates & coords, bool extend_parent = false)
Constructor.
Parameters
[in] parent Parent tensor
[in] tensor_shape Shape of the subtensor
[in] coords Coordinates of the first subtensor element inside the parent tensor.
[in] extend_parent (Optional) Extend parent with subtensor shape if subtensor indexes out of bounds
Definition at line 37 of file CLSubTensor.cpp.
     : _parent(nullptr), _info()
 {
     ARM_COMPUTE_ERROR_ON(parent == nullptr);
     _info   = SubTensorInfo(parent->info(), tensor_shape, coords, extend_parent);
     _parent = parent;
 }
References ARM_COMPUTE_ERROR_ON, ITensor::info(), and CLSubTensor::parent().
~CLSubTensor()
~CLSubTensor () default
Destructor: free the tensor's memory.
CLSubTensor() [3/4]
CLSubTensor (const CLSubTensor &) delete
Restrict instances of this class to be copy constructed.
CLSubTensor() [4/4]
CLSubTensor (CLSubTensor &&) default
Allow instances of this class to be move constructed.
Member Function Documentation
cl_buffer()
const cl::Buffer & cl_buffer () const override virtual
Interface to be implemented by the child class to return a reference to the OpenCL buffer containing the image's data.
Returns
A reference to an OpenCL buffer containing the image's data.
Implements ICLTensor.
Definition at line 55 of file CLSubTensor.cpp.
 {
     ARM_COMPUTE_ERROR_ON(_parent == nullptr);
     return _parent->cl_buffer();
 }
References ARM_COMPUTE_ERROR_ON, and ICLTensor::cl_buffer().
info() [1/2]
ITensorInfo * info () const override virtual
Interface to be implemented by the child class to return the tensor's metadata.
Returns
A pointer to the tensor's metadata.
Implements ITensor.
Definition at line 45 of file CLSubTensor.cpp.
 {
     return &_info;
 }
info() [2/2]
ITensorInfo * info () override virtual
Interface to be implemented by the child class to return the tensor's metadata.
Returns
A pointer to the tensor's metadata.
Implements ITensor.
Definition at line 50 of file CLSubTensor.cpp.
 {
     return &_info;
 }
map() [1/2]
void map (bool blocking = true)
Enqueue a map operation of the allocated buffer.
Note
Mapping a subtensor will lead to the mapping of the whole parent tensor for now.
Parameters
[in] blocking If true, then the mapping will be ready to use by the time this method returns, else it is the caller's responsibility to flush the queue and wait for the mapping operation to have completed.
Definition at line 71 of file CLSubTensor.cpp.
 {
     ICLTensor::map(CLScheduler::get().queue(), blocking);
 }
References CLScheduler::get(), and ICLTensor::map().
Referenced by CLSubTensorHandle::map().
map() [2/2]
void map
Enqueue a map operation of the allocated buffer on the given queue.
Parameters
[in,out] q The CL command queue to use for the mapping operation.
[in] blocking If true, then the mapping will be ready to use by the time this method returns, else it is the caller's responsibility to flush the queue and wait for the mapping operation to have completed before using the returned mapping pointer.
Returns
The mapping address.
Definition at line 35 of file ICLTensor.cpp.
 {
     _mapping = do_map(q, blocking);
 }
operator=() [1/2]
CLSubTensor& operator= (const CLSubTensor &) delete
Restrict instances of this class to be copied.
operator=() [2/2]
CLSubTensor& operator= (CLSubTensor &&) default
Allow instances of this class to be moved.
parent()
ICLTensor * parent ()
Return the parent tensor of the subtensor.
Returns
Parent tensor
Definition at line 66 of file CLSubTensor.cpp.
 {
     return _parent;
 }
Referenced by CLSubTensor::CLSubTensor().
quantization()
CLQuantization quantization () const override virtual
Interface to be implemented by the child class to return the wrapped quantization info data.
Returns
A wrapped quantization info object.
Implements ICLTensor.
Definition at line 61 of file CLSubTensor.cpp.
 {
     return _parent->quantization();
 }
References ICLTensor::quantization().
unmap() [1/2]
void unmap ()
Enqueue an unmap operation of the allocated and mapped buffer.
Note
Unmapping a subtensor will lead to the unmapping of the whole parent tensor for now.
This method simply enqueues the unmap operation, it is the caller's responsibility to flush the queue and make sure the unmap is finished before the memory is accessed by the device.
Definition at line 76 of file CLSubTensor.cpp.
 {
     ICLTensor::unmap(CLScheduler::get().queue());
 }
References CLScheduler::get(), and ICLTensor::unmap().
Referenced by CLSubTensorHandle::unmap().
unmap() [2/2]
void unmap
Enqueue an unmap operation of the allocated and mapped buffer on the given queue.
Note
This method simply enqueues the unmap operation, it is the caller's responsibility to flush the queue and make sure the unmap is finished before the memory is accessed by the device.
Parameters
[in,out] q The CL command queue to use for the mapping operation.
Definition at line 40 of file ICLTensor.cpp.
 {
     do_unmap(q);
     _mapping = nullptr;
 }
The documentation for this class was generated from the following files:
arm_compute/runtime/CL/CLSubTensor.h
src/runtime/CL/CLSubTensor.cpp