Compute Library: CLHOG Class Reference
CLHOG Class Reference
OpenCL implementation of HOG data-object.
#include <CLHOG.h>
Public Member Functions
CLHOG ()
Default constructor.
void init (const HOGInfo &input)
Allocate the HOG descriptor using the given HOG's metadata.
void map (bool blocking=true)
Enqueue a map operation of the allocated buffer.
void unmap ()
Enqueue an unmap operation of the allocated and mapped buffer.
void free () override
Interface to be implemented by the child class to free the allocated cl buffer.
const HOGInfo * info () const override
Interface to be implemented by the child class to return the HOG's metadata.
const cl::Buffer & cl_buffer () const override
Interface to be implemented by the child class to return a reference to the OpenCL buffer containing the hog's descriptor.
void map (cl::CommandQueue &q, bool blocking=true)
Enqueue a map operation of the allocated buffer on the given queue.
void unmap (cl::CommandQueue &q)
Enqueue an unmap operation of the allocated and mapped buffer on the given queue.
Public Member Functions inherited from ICLHOG
ICLHOG ()
Default constructor.
ICLHOG (const ICLHOG &)=delete
Prevent instances of this class from being copied (As this class contains pointers)
ICLHOG & operator= (const ICLHOG &)=delete
Prevent instances of this class from being copied (As this class contains pointers)
ICLHOG (ICLHOG &&)=default
Allow instances of this class to be moved.
ICLHOG & operator= (ICLHOG &&)=default
Allow instances of this class to be moved.
virtual ~ICLHOG ()=default
Default destructor.
void map (cl::CommandQueue &q, bool blocking=true)
Enqueue a map operation of the allocated buffer on the given queue.
void unmap (cl::CommandQueue &q)
Enqueue an unmap operation of the allocated and mapped buffer on the given queue.
float * descriptor () const override
Pointer to the first element of the array which stores the linear SVM coefficients of HOG descriptor.
Public Member Functions inherited from IHOG
virtual ~IHOG ()=default
Default virtual destructor.
Detailed Description
OpenCL implementation of HOG data-object.
Definition at line 37 of file CLHOG.h.
Constructor & Destructor Documentation
CLHOG()
CLHOG ()
Default constructor.
Definition at line 33 of file CLHOG.cpp.
     : _info(), _buffer()
 {
 }
Member Function Documentation
cl_buffer()
const cl::Buffer & cl_buffer () const override virtual
Interface to be implemented by the child class to return a reference to the OpenCL buffer containing the hog's descriptor.
Returns
A reference to an OpenCL buffer containing the hog's descriptor
Implements ICLHOG.
Definition at line 57 of file CLHOG.cpp.
 {
     return _buffer;
 }
free()
void free () override virtual
Interface to be implemented by the child class to free the allocated cl buffer.
Warning
The buffer must have been allocated previously. Otherwise calling the function will fail.
Implements ICLHOG.
Definition at line 45 of file CLHOG.cpp.
 {
     ARM_COMPUTE_ERROR_ON(_buffer.get() == nullptr);
     _buffer = cl::Buffer();
 }
References ARM_COMPUTE_ERROR_ON.
info()
const HOGInfo * info () const override virtual
Interface to be implemented by the child class to return the HOG's metadata.
Returns
A pointer to the HOG's metadata.
Implements IHOG.
Definition at line 52 of file CLHOG.cpp.
 {
     return &_info;
 }
Referenced by CLHOG::init().
init()
void init (const HOGInfo & input)
Allocate the HOG descriptor using the given HOG's metadata.
Parameters
[in] input HOG's metadata used to allocate the HOG descriptor
Definition at line 38 of file CLHOG.cpp.
 {
     ARM_COMPUTE_ERROR_ON(_buffer.get() != nullptr);
     _info   = input;
     _buffer = cl::Buffer(CLScheduler::get().context(), CL_MEM_ALLOC_HOST_PTR | CL_MEM_READ_WRITE, info()->descriptor_size() * sizeof(float));
 }
References ARM_COMPUTE_ERROR_ON, CLScheduler::get(), and CLHOG::info().
map() [1/2]
void map (bool blocking = true)
Enqueue a map operation of the allocated buffer.
Parameters
[in] blocking If true, then the mapping will be ready to use by the time this method returns, else it is the caller's responsibility to flush the queue and wait for the mapping operation to have completed.
Definition at line 62 of file CLHOG.cpp.
 {
     ARM_COMPUTE_ERROR_ON(descriptor() != nullptr);
     ICLHOG::map(CLScheduler::get().queue(), blocking);
 }
References ARM_COMPUTE_ERROR_ON, ICLHOG::descriptor(), CLScheduler::get(), and ICLHOG::map().
map() [2/2]
void map
Enqueue a map operation of the allocated buffer on the given queue.
Parameters
[in,out] q The CL command queue to use for the mapping operation.
[in] blocking If true, then the mapping will be ready to use by the time this method returns, else it is the caller's responsibility to flush the queue and wait for the mapping operation to have completed before using the returned mapping pointer.
Returns
The mapping address.
Definition at line 33 of file ICLHOG.cpp.
 {
     _mapping = do_map(q, blocking);
 }
unmap() [1/2]
void unmap ()
Enqueue an unmap operation of the allocated and mapped buffer.
Note
This method simply enqueues the unmap operation, it is the caller's responsibility to flush the queue and make sure the unmap is finished before the memory is accessed by the device.
Definition at line 68 of file CLHOG.cpp.
 {
     ARM_COMPUTE_ERROR_ON(descriptor() == nullptr);
     ICLHOG::unmap(CLScheduler::get().queue());
 }
References ARM_COMPUTE_ERROR_ON, ICLHOG::descriptor(), CLScheduler::get(), and ICLHOG::unmap().
Referenced by CLHOGAccessor::~CLHOGAccessor().
unmap() [2/2]
void unmap
Enqueue an unmap operation of the allocated and mapped buffer on the given queue.
Note
This method simply enqueues the unmap operation, it is the caller's responsibility to flush the queue and make sure the unmap is finished before the memory is accessed by the device.
Parameters
[in,out] q The CL command queue to use for the mapping operation.
Definition at line 38 of file ICLHOG.cpp.
 {
     do_unmap(q);
     _mapping = nullptr;
 }
The documentation for this class was generated from the following files:
arm_compute/runtime/CL/CLHOG.h
src/runtime/CL/CLHOG.cpp