Compute Library: NEFullyConnectedLayer Class Reference
NEFullyConnectedLayer Class Reference
Basic function to compute a Fully Connected layer on NEON.
#include <NEFullyConnectedLayer.h>
Public Member Functions
NEFullyConnectedLayer (std::shared_ptr< IMemoryManager > memory_manager=nullptr)
Constructor.
NEFullyConnectedLayer (const NEFullyConnectedLayer &)=delete
Prevent instances of this class from being copied (As this class contains pointers)
NEFullyConnectedLayer (NEFullyConnectedLayer &&)=default
Default move constructor.
NEFullyConnectedLayer & operator= (const NEFullyConnectedLayer &)=delete
Prevent instances of this class from being copied (As this class contains pointers)
NEFullyConnectedLayer & operator= (NEFullyConnectedLayer &&)=default
Default move assignment operator.
void configure (const ITensor *input, const ITensor *weights, const ITensor *biases, ITensor *output, FullyConnectedLayerInfo fc_info=FullyConnectedLayerInfo())
Set the input and output tensors.
void run () override
Run the kernels contained in the function.
void prepare () override
Prepare the function for executing.
Public Member Functions inherited from IFunction
virtual ~IFunction ()=default
Destructor.
Static Public Member Functions
static Status validate (const ITensorInfo *input, const ITensorInfo *weights, const ITensorInfo *biases, const ITensorInfo *output, FullyConnectedLayerInfo fc_info=FullyConnectedLayerInfo())
Static function to check if given info will lead to a valid configuration of NEFullyConnectedLayer.
Detailed Description
Basic function to compute a Fully Connected layer on NEON.
This function calls the following NEON kernels:
NEIm2ColKernel (called when the input comes from a convolutional layer)
NEFullyConnectedLayerReshapeWeights (if are_weights_reshaped is set to false and transpose_weights is set to true) (called once)
NEGEMMMatrixMultiplyKernel or NEGEMMLowpMatrixMultiplyCore (if quantized asymmetric)
NEGEMMMatrixAccumulateBiasesKernel or NEGEMMLowpQuantizeDownInt32ToUint8ScaleByFixedPoint (if quantized asymmetric) (if biases is not equal to nullptr)
Note
The fully connected layer accepts "weights" tensors only with 2 dimensions.
Definition at line 74 of file NEFullyConnectedLayer.h.
Constructor & Destructor Documentation
NEFullyConnectedLayer() [1/3]
NEFullyConnectedLayer (std::shared_ptr< IMemoryManager > memory_manager = nullptr)
Constructor.
Definition at line 77 of file NEFullyConnectedLayer.cpp.
     : _memory_group(std::move(memory_manager)), _flatten_kernel(), _convert_weights(), _reshape_weights_function(), _mm_gemm(), _mm_gemmlowp(), _gemmlowp_output_stage(), _accumulate_biases_kernel(),
       _flatten_output(), _gemmlowp_output(), _converted_weights_output(), _reshape_weights_output(), _original_weights(nullptr), _are_weights_converted(true), _are_weights_reshaped(false),
       _is_fc_after_conv(false), _accumulate_biases(false), _is_quantized(false), _is_prepared(false)
 {
 }
NEFullyConnectedLayer() [2/3]
NEFullyConnectedLayer (const NEFullyConnectedLayer &) delete
Prevent instances of this class from being copied (As this class contains pointers)
NEFullyConnectedLayer() [3/3]
NEFullyConnectedLayer (NEFullyConnectedLayer &&) default
Default move constructor.
Member Function Documentation
configure()
void configure (const ITensor * input, const ITensor * weights, const ITensor * biases, ITensor * output, FullyConnectedLayerInfo fc_info = FullyConnectedLayerInfo())
Set the input and output tensors.
Parameters
[in] input Source tensor. Data type supported: QASYMM8/F16/F32.
[in] weights Weights tensor. The weights must be 2 dimensional. If this function is called after a Convolution Layer, the (transposed) weights will have as many rows as the product of the first 3 input's dimensions. If it is called after another FullyConnected Layer, the (transposed) weights will have as many rows as the input's first dimension. Data type supported: Same as input.
[in] biases Bias tensor. Can be nullptr. Data type supported:Same as input.
[out] output Destination tensor. Its shape should be equal to the output of a matrix multiplication between:
The output of im2col on the input and the (transposed) 2D weights, if the function is called after a Convolution Layer
The input tensor and the (transposed) 2D weights, if the function is called after another FullyConnected Layer. Data type supported: Same as input.
[in] fc_info (Optional) Fully connected layer additional info
Definition at line 139 of file NEFullyConnectedLayer.cpp.
 {
     ARM_COMPUTE_ERROR_ON_NULLPTR(input, weights, output);
     // Perform validate step
     ARM_COMPUTE_ERROR_THROW_ON(NEFullyConnectedLayer::validate(input->info(),
                                                                weights->info(),
                                                                biases != nullptr ? biases->info() : nullptr,
                                                                output->info(),
                                                                fc_info));
     _are_weights_converted = true;
     _are_weights_reshaped  = fc_info.transpose_weights ? fc_info.are_weights_reshaped : true;
     _is_fc_after_conv      = true;
     _accumulate_biases     = false;
     _is_quantized          = is_data_type_quantized_asymmetric(input->info()->data_type());
     _original_weights      = weights;
     // Configure gemmlowp output
     if(_is_quantized)
     {
         _gemmlowp_output.allocator()->init(output->info()->clone()->set_is_resizable(true).reset_padding().set_data_type(DataType::S32));
     }
     // Configure accumulate biases kernel for non quantized asymmetric types
     if(biases != nullptr && !_is_quantized)
     {
         _accumulate_biases = true;
         // Configure accumulate biases kernel
         _accumulate_biases_kernel.configure(output, biases);
     }
     // With the Fully Connected layer we can have 4 different cases:
     //  1) Convolution layer -> Fully Connected layer without batches
     //  2) Fully Connected layer -> Fully Connected layer without batches
     //  3) Convolution layer -> Fully Connected layer with batches
     //  4) Fully Connected layer -> Fully Connected layer with batches
     const ITensor *weights_to_use = weights;
     // Check if we have a fully connected layer with batches
     const bool is_batched_fc_layer = output->info()->dimension(1) > 1;
     if(is_batched_fc_layer)
     {
         _is_fc_after_conv = (TensorShape::num_max_dimensions >= 4) && (std::equal(input->info()->tensor_shape().cbegin() + 3,
                                                                                   input->info()->tensor_shape().cend(),
                                                                                   output->info()->tensor_shape().cbegin() + 1));
     }
     else
     {
         _is_fc_after_conv = input->info()->num_dimensions() > 1;
     }
     // Reshape weights if needed
     if(!_are_weights_reshaped)
     {
         // Reshape the weights
         _reshape_weights_function.configure(weights, &_reshape_weights_output);
         weights_to_use = &_reshape_weights_output;
     }
     // Convert weights if needed
     if(_is_fc_after_conv && (input->info()->data_layout() != fc_info.weights_trained_layout))
     {
         // Convert weights
         _convert_weights.configure(weights_to_use,
                                    &_converted_weights_output,
                                    input->info()->tensor_shape(),
                                    fc_info.weights_trained_layout);
         weights_to_use         = &_converted_weights_output;
         _are_weights_converted = false;
     }
     ITensor *tmp_output = (_is_quantized) ? &_gemmlowp_output : output;
     if(_is_fc_after_conv)
     {
         // Fully Connected layer after a Convolution Layer without batches
         configure_conv_fc(input, weights_to_use, tmp_output);
     }
     else
     {
         // Fully Connected layer after a Fully Connected Layer without batches
         configure_fc_fc(input, weights_to_use, tmp_output);
     }
     // Configure output stage for asymmetric quantized types
     if(_is_quantized)
     {
         const UniformQuantizationInfo iq_info = input->info()->quantization_info().uniform();
         const UniformQuantizationInfo wq_info = weights->info()->quantization_info().uniform();
         const UniformQuantizationInfo oq_info = output->info()->quantization_info().uniform();
         float multiplier = (iq_info.scale * wq_info.scale) / oq_info.scale;
         int   output_multiplier;
         int   output_shift;
         quantization::calculate_quantized_multiplier_less_than_one(multiplier, &output_multiplier, &output_shift);
         _gemmlowp_output_stage.configure(&_gemmlowp_output, biases, output, output_multiplier, output_shift, oq_info.offset);
         _gemmlowp_output.allocator()->allocate();
     }
     _are_weights_reshaped = _are_weights_reshaped || fc_info.retain_internal_weights;
 }
References TensorAllocator::allocate(), Tensor::allocator(), FullyConnectedLayerInfo::are_weights_reshaped, ARM_COMPUTE_ERROR_ON_NULLPTR, ARM_COMPUTE_ERROR_THROW_ON, arm_compute::quantization::calculate_quantized_multiplier_less_than_one(), Dimensions< T >::cbegin(), Dimensions< T >::cend(), ICloneable< T >::clone(), NEConvertFullyConnectedWeights::configure(), NEFullyConnectedLayerReshapeWeights::configure(), NEGEMMMatrixAccumulateBiasesKernel::configure(), NEGEMMLowpQuantizeDownInt32ToUint8ScaleByFixedPoint::configure(), ITensorInfo::data_layout(), ITensorInfo::data_type(), ITensorInfo::dimension(), ITensor::info(), CLTensor::info(), TensorAllocator::init(), arm_compute::is_data_type_quantized_asymmetric(), ITensorInfo::num_dimensions(), Dimensions< size_t >::num_max_dimensions, UniformQuantizationInfo::offset, ITensorInfo::quantization_info(), TensorInfo::quantization_info(), FullyConnectedLayerInfo::retain_internal_weights, arm_compute::S32, UniformQuantizationInfo::scale, ITensorInfo::tensor_shape(), FullyConnectedLayerInfo::transpose_weights, QuantizationInfo::uniform(), NEFullyConnectedLayer::validate(), arm_compute::test::validation::weights, and FullyConnectedLayerInfo::weights_trained_layout.
Referenced by NERNNLayer::configure(), and NELSTMLayer::configure().
operator=() [1/2]
NEFullyConnectedLayer& operator= (const NEFullyConnectedLayer &) delete
Prevent instances of this class from being copied (As this class contains pointers)
operator=() [2/2]
NEFullyConnectedLayer& operator= (NEFullyConnectedLayer &&) default
Default move assignment operator.
prepare()
void prepare () override virtual
Prepare the function for executing.
Any one off pre-processing step required by the function is handled here
Note
Prepare stage might not need all the function's buffers' backing memory to be available in order to execute
Reimplemented from IFunction.
Definition at line 380 of file NEFullyConnectedLayer.cpp.
 {
     if(!_is_prepared)
     {
         ARM_COMPUTE_ERROR_ON(!_original_weights->is_used());
         auto release_unused = [](Tensor * w)
         {
             if(!w->is_used())
             {
                 w->allocator()->free();
             }
         };
         // Pointer to current weights
         const ITensor *cur_weights = _original_weights;
         // Reshape of the weights (happens only once)
         if(!_are_weights_reshaped)
         {
             // Run reshape weights kernel and mark weights as unused
             _reshape_weights_output.allocator()->allocate();
             _reshape_weights_function.run();
             cur_weights->mark_as_unused();
             cur_weights           = &_reshape_weights_output;
             _are_weights_reshaped = true;
         }
         // Convert weights if needed (happens only once)
         if(!_are_weights_converted)
         {
             _converted_weights_output.allocator()->allocate();
             _convert_weights.run();
             cur_weights->mark_as_unused();
             _are_weights_converted = true;
         }
         // Release reshaped weights if unused
         release_unused(&_reshape_weights_output);
         // Prepare GEMM prepare and release unused weights
         if(!_is_quantized)
         {
             _mm_gemm.prepare();
         }
         // Release converted weights if unused
         release_unused(&_reshape_weights_output);
         release_unused(&_converted_weights_output);
         _is_prepared = true;
     }
 }
References TensorAllocator::allocate(), Tensor::allocator(), ARM_COMPUTE_ERROR_ON, ITensor::is_used(), ITensor::mark_as_unused(), NEGEMM::prepare(), INESimpleFunctionNoBorder::run(), NEConvertFullyConnectedWeights::run(), and arm_compute::test::validation::w.
Referenced by NERNNLayer::prepare(), and NEFullyConnectedLayer::run().
run()
void run () override virtual
Run the kernels contained in the function.
For NEON kernels:
Multi-threading is used for the kernels which are parallelisable.
By default std::thread::hardware_concurrency() threads are used.
Note
CPPScheduler::set_num_threads() can be used to manually set the number of threads
For OpenCL kernels:
All the kernels are enqueued on the queue associated with CLScheduler.
The queue is then flushed.
Note
The function will not block until the kernels are executed. It is the user's responsibility to wait.
Will call prepare() on first run if hasn't been done
Implements IFunction.
Definition at line 344 of file NEFullyConnectedLayer.cpp.
 {
     prepare();
     MemoryGroupResourceScope scope_mg(_memory_group);
     // Linearize input if it comes from a convolutional layer
     if(_is_fc_after_conv)
     {
         NEScheduler::get().schedule(&_flatten_kernel, Window::DimY);
     }
     // Run matrix multiply
     if(_is_quantized)
     {
         _mm_gemmlowp.run();
     }
     else
     {
         _mm_gemm.run();
     }
     // Accumulate biases if provided
     if(_is_quantized)
     {
         _gemmlowp_output_stage.run();
     }
     else
     {
         if(_accumulate_biases)
         {
             NEScheduler::get().schedule(&_accumulate_biases_kernel, Window::DimY);
         }
     }
 }
References Window::DimY, Scheduler::get(), NEFullyConnectedLayer::prepare(), INESimpleFunctionNoBorder::run(), NEGEMM::run(), NEGEMMLowpMatrixMultiplyCore::run(), and IScheduler::schedule().
Referenced by NERNNLayer::run(), and NELSTMLayer::run().
validate()
Status validate (const ITensorInfo * input, const ITensorInfo * weights, const ITensorInfo * biases, const ITensorInfo * output, FullyConnectedLayerInfo fc_info = FullyConnectedLayerInfo()) static
Static function to check if given info will lead to a valid configuration of NEFullyConnectedLayer.
Parameters
[in] input Source tensor info. Data type supported: QASYMM8/F16/F32.
[in] weights Weights tensor info. The weights must be 2 dimensional. If this function is called after a Convolution Layer, the (transposed) weights will have as many rows as the product of the first 3 input's dimensions. If it is called after another FullyConnected Layer, the (transposed) weights will have as many rows as the input's first dimension. Data type supported: Same as input.
[in] biases Bias tensor info. Can be nullptr. Data type supported:Same as input.
[out] output Destination tensor info. Its shape should be equal to the output of a matrix multiplication between:
The output of im2col on the input and the (transposed) 2D weights, if the function is called after a Convolution Layer
The input tensor and the (transposed) 2D weights, if the function is called after another FullyConnected Layer. Data type supported: Same as input.
[in] fc_info (Optional) Fully connected layer additional info
Returns
a status
Definition at line 245 of file NEFullyConnectedLayer.cpp.
 {
     ARM_COMPUTE_UNUSED(fc_info.retain_internal_weights);
     ARM_COMPUTE_RETURN_ERROR_ON_NULLPTR(input, weights, output);
     ARM_COMPUTE_RETURN_ERROR_ON_DATA_TYPE_CHANNEL_NOT_IN(input, 1, DataType::QASYMM8, DataType::F16, DataType::F32);
     ARM_COMPUTE_RETURN_ERROR_ON_MISMATCHING_DATA_TYPES(input, weights, output);
     ARM_COMPUTE_RETURN_ERROR_ON(weights->num_dimensions() > 2);
     bool weights_reshaped = fc_info.transpose_weights ? fc_info.are_weights_reshaped : true;
     bool is_fc_after_conv = true;
     bool is_quantized     = is_data_type_quantized_asymmetric(input->data_type());
     const ITensorInfo &flatten_input     = TensorInfo(input->clone()->set_is_resizable(true).reset_padding().set_tensor_shape(compute_flatten_shape(input)));
     const ITensorInfo &reshaped_weights  = TensorInfo(weights->clone()->set_is_resizable(true).reset_padding().set_tensor_shape(compute_transposed_shape(*weights)));
     const ITensorInfo &converted_weights = weights_reshaped ? TensorInfo(weights->clone()->set_is_resizable(true).reset_padding()) : TensorInfo(*reshaped_weights.clone());
     const ITensorInfo &gemmlowp_output   = TensorInfo(output->clone()->set_is_resizable(true).reset_padding().set_data_type(DataType::S32));
     // Configure accumulate biases kernel for non quantized asymmetric types
     if(biases != nullptr && !is_quantized)
     {
         ARM_COMPUTE_RETURN_ERROR_ON_MISMATCHING_DATA_TYPES(input, biases);
         ARM_COMPUTE_RETURN_ON_ERROR(NEGEMMMatrixAccumulateBiasesKernel::validate(output, biases));
     }
     // With the Fully Connected layer we can have 4 different cases:
     //  1) Convolution layer -> Fully Connected layer without batches
     //  2) Fully Connected layer -> Fully Connected layer without batches
     //  3) Convolution layer -> Fully Connected layer with batches
     //  4) Fully Connected layer -> Fully Connected layer with batches
     const ITensorInfo *input_to_use   = input;
     const ITensorInfo *weights_to_use = weights;
     const ITensorInfo *tmp_output     = (is_quantized) ? &gemmlowp_output : output;
     // Check if we have a fully connected layer with batches
     const bool is_batched_fc_layer = output->dimension(1) > 1;
     if(is_batched_fc_layer)
     {
         is_fc_after_conv = (TensorShape::num_max_dimensions >= 4) && (std::equal(input->tensor_shape().cbegin() + 3,
                                                                                  input->tensor_shape().cend(),
                                                                                  output->tensor_shape().cbegin() + 1));
     }
     else
     {
         is_fc_after_conv = input->num_dimensions() > 1;
     }
     if(!weights_reshaped)
     {
         // Validate reshape weights kernel
         ARM_COMPUTE_RETURN_ON_ERROR(NEFullyConnectedLayerReshapeWeights::validate(weights, &reshaped_weights));
         weights_to_use = &reshaped_weights;
     }
     if(is_fc_after_conv && (input->data_layout() != fc_info.weights_trained_layout))
     {
         // Validate convert weights kernel
         ARM_COMPUTE_RETURN_ON_ERROR(NEConvertFullyConnectedWeights::validate(weights_to_use,
                                                                              &converted_weights,
                                                                              input->tensor_shape(),
                                                                              fc_info.weights_trained_layout));
         weights_to_use = &converted_weights;
     }
     if(is_fc_after_conv)
     {
         // Fully Connected layer after a Convolution Layer without batches
         ARM_COMPUTE_RETURN_ERROR_ON((weights_to_use->dimension(1) != (input->dimension(0) * input->dimension(1) * input->dimension(2))));
         // Validate flatten kernel
         ARM_COMPUTE_RETURN_ON_ERROR(NEFlattenLayerKernel::validate(input, &flatten_input));
         input_to_use = &flatten_input;
     }
     else
     {
         // Fully Connected layer after a Fully Connected Layer without batches
         ARM_COMPUTE_RETURN_ERROR_ON(input->dimension(0) != weights_to_use->dimension(1));
     }
     // Validate matrix multiply kernel
     ARM_COMPUTE_RETURN_ON_ERROR(validate_mm(*input_to_use, *weights_to_use, *tmp_output));
     // Validate output stage for asymmetric quantized types
     if(is_quantized)
     {
         const UniformQuantizationInfo iq_info    = input->quantization_info().uniform();
         const UniformQuantizationInfo wq_info    = weights->quantization_info().uniform();
         const UniformQuantizationInfo oq_info    = output->quantization_info().uniform();
         const float                   multiplier = iq_info.scale * wq_info.scale / oq_info.scale;
         ARM_COMPUTE_UNUSED(multiplier);
         ARM_COMPUTE_RETURN_ERROR_ON(multiplier > 1.0f);
         ARM_COMPUTE_RETURN_ON_ERROR(NEGEMMLowpQuantizeDownInt32ToUint8ScaleByFixedPoint::validate(&gemmlowp_output, biases, output));
     }
     return Status{};
 }
References FullyConnectedLayerInfo::are_weights_reshaped, ARM_COMPUTE_RETURN_ERROR_ON, ARM_COMPUTE_RETURN_ERROR_ON_DATA_TYPE_CHANNEL_NOT_IN, ARM_COMPUTE_RETURN_ERROR_ON_MISMATCHING_DATA_TYPES, ARM_COMPUTE_RETURN_ERROR_ON_NULLPTR, ARM_COMPUTE_RETURN_ON_ERROR, ARM_COMPUTE_UNUSED, Dimensions< T >::cbegin(), Dimensions< T >::cend(), ICloneable< T >::clone(), arm_compute::misc::shape_calculator::compute_flatten_shape(), arm_compute::misc::shape_calculator::compute_transposed_shape(), ITensorInfo::data_layout(), ITensorInfo::data_type(), ITensorInfo::dimension(), arm_compute::F16, arm_compute::F32, arm_compute::is_data_type_quantized_asymmetric(), ITensorInfo::num_dimensions(), Dimensions< size_t >::num_max_dimensions, arm_compute::QASYMM8, ITensorInfo::quantization_info(), FullyConnectedLayerInfo::retain_internal_weights, arm_compute::S32, UniformQuantizationInfo::scale, ITensorInfo::tensor_shape(), FullyConnectedLayerInfo::transpose_weights, QuantizationInfo::uniform(), NEConvertFullyConnectedWeights::validate(), NEFullyConnectedLayerReshapeWeights::validate(), NEGEMMMatrixAccumulateBiasesKernel::validate(), NEFlattenLayerKernel::validate(), NEGEMMLowpQuantizeDownInt32ToUint8ScaleByFixedPoint::validate(), arm_compute::test::validation::weights, and FullyConnectedLayerInfo::weights_trained_layout.
Referenced by NEFullyConnectedLayer::configure(), NERNNLayer::validate(), and NELSTMLayer::validate().
The documentation for this class was generated from the following files:
arm_compute/runtime/NEON/functions/NEFullyConnectedLayer.h
src/runtime/NEON/functions/NEFullyConnectedLayer.cpp