Compute Library: SubTensor Class Reference
SubTensor Class Reference
Basic implementation of the sub-tensor interface.
#include <SubTensor.h>
Public Member Functions
SubTensor ()
Default Constructor.
SubTensor (ITensor *parent, const TensorShape &tensor_shape, const Coordinates &coords, bool extend_parent=false)
Constructor.
~SubTensor ()=default
Destructor: free the tensor's memory.
SubTensor (const SubTensor &)=delete
Restrict instances of this class to be copy constructed.
SubTensor & operator= (const SubTensor &)=delete
Restrict instances of this class to be copied.
SubTensor (SubTensor &&)=default
Allow instances of this class to be move constructed.
SubTensor & operator= (SubTensor &&)=default
Allow instances of this class to be moved.
ITensor * parent ()
Return the parent tensor of the subtensor.
ITensorInfo * info () const override
Interface to be implemented by the child class to return the tensor's metadata.
ITensorInfo * info () override
Interface to be implemented by the child class to return the tensor's metadata.
uint8_t * buffer () const override
Interface to be implemented by the child class to return a pointer to CPU memory.
Public Member Functions inherited from ITensor
virtual ~ITensor ()=default
Default virtual destructor.
uint8_t * ptr_to_element (const Coordinates &id) const
Return a pointer to the element at the passed coordinates.
void copy_from (const ITensor &src)
Copy the content of another tensor.
void print (std::ostream &s, IOFormatInfo io_fmt=IOFormatInfo()) const
Print a tensor to a given stream using user defined formatting information.
bool is_used () const
Flags if the tensor is used or not.
void mark_as_unused () const
Marks a tensor as unused.
Detailed Description
Basic implementation of the sub-tensor interface.
Definition at line 37 of file SubTensor.h.
Constructor & Destructor Documentation
SubTensor() [1/4]
SubTensor ()
Default Constructor.
Definition at line 30 of file SubTensor.cpp.
     : _parent(nullptr), _info()
 {
 }
SubTensor() [2/4]
SubTensor (ITensor * parent, const TensorShape & tensor_shape, const Coordinates & coords, bool extend_parent = false)
Constructor.
Parameters
[in] parent Parent tensor
[in] tensor_shape Shape of the subtensor
[in] coords Coordinates of the first subtensor element inside the parent tensor.
[in] extend_parent (Optional) Extend parent with subtensor shape if subtensor indexes out of bounds
Definition at line 35 of file SubTensor.cpp.
     : _parent(nullptr), _info()
 {
     ARM_COMPUTE_ERROR_ON(parent == nullptr);
     _info   = SubTensorInfo(parent->info(), tensor_shape, coords, extend_parent);
     _parent = parent;
 }
References ARM_COMPUTE_ERROR_ON, ITensor::info(), and SubTensor::parent().
~SubTensor()
~SubTensor () default
Destructor: free the tensor's memory.
SubTensor() [3/4]
SubTensor (const SubTensor &) delete
Restrict instances of this class to be copy constructed.
SubTensor() [4/4]
SubTensor (SubTensor &&) default
Allow instances of this class to be move constructed.
Member Function Documentation
buffer()
uint8_t * buffer () const override virtual
Interface to be implemented by the child class to return a pointer to CPU memory.
Returns
A CPU pointer to the beginning of the image's allocation.
Implements ITensor.
Definition at line 53 of file SubTensor.cpp.
 {
     ARM_COMPUTE_ERROR_ON(_parent == nullptr);
     return _parent->buffer();
 }
References ARM_COMPUTE_ERROR_ON, and ITensor::buffer().
info() [1/2]
ITensorInfo * info () const override virtual
Interface to be implemented by the child class to return the tensor's metadata.
Returns
A pointer to the tensor's metadata.
Implements ITensor.
Definition at line 43 of file SubTensor.cpp.
 {
     return &_info;
 }
info() [2/2]
ITensorInfo * info () override virtual
Interface to be implemented by the child class to return the tensor's metadata.
Returns
A pointer to the tensor's metadata.
Implements ITensor.
Definition at line 48 of file SubTensor.cpp.
 {
     return &_info;
 }
operator=() [1/2]
SubTensor& operator= (const SubTensor &) delete
Restrict instances of this class to be copied.
operator=() [2/2]
SubTensor& operator= (SubTensor &&) default
Allow instances of this class to be moved.
parent()
ITensor * parent ()
Return the parent tensor of the subtensor.
Returns
Parent tensor
Definition at line 59 of file SubTensor.cpp.
 {
     return _parent;
 }
Referenced by SubTensor::SubTensor().
The documentation for this class was generated from the following files:
arm_compute/runtime/SubTensor.h
src/runtime/SubTensor.cpp