Compute Library: NEMemsetKernel Class Reference
NEMemsetKernel Class Reference
Interface for filling the planes of a tensor.
#include <NEMemsetKernel.h>
Public Member Functions
const char * name () const override
Name of the kernel.
NEMemsetKernel ()
Default constructor.
~NEMemsetKernel ()=default
Default destructor.
NEMemsetKernel (const NEMemsetKernel &)=delete
Prevent instances of this class from being copied (As this class contains pointers)
NEMemsetKernel & operator= (const NEMemsetKernel &)=delete
Prevent instances of this class from being copied (As this class contains pointers)
NEMemsetKernel (NEMemsetKernel &&)=default
Allow instances of this class to be moved.
NEMemsetKernel & operator= (NEMemsetKernel &&)=default
Allow instances of this class to be moved.
void configure (ITensor *tensor, const PixelValue &constant_value)
Initialise the kernel's tensor and filling value.
void run (const Window &window, const ThreadInfo &info) override
Execute the kernel on the passed window.
Public Member Functions inherited from ICPPKernel
virtual ~ICPPKernel ()=default
Default destructor.
Public Member Functions inherited from IKernel
IKernel ()
Constructor.
virtual ~IKernel ()=default
Destructor.
virtual bool is_parallelisable () const
Indicates whether or not the kernel is parallelisable.
virtual BorderSize border_size () const
The size of the border for that kernel.
const Window & window () const
The maximum window the kernel can be executed on.
Detailed Description
Interface for filling the planes of a tensor.
Definition at line 37 of file NEMemsetKernel.h.
Constructor & Destructor Documentation
NEMemsetKernel() [1/3]
NEMemsetKernel ()
Default constructor.
Definition at line 35 of file NEMemsetKernel.cpp.
     : _tensor(nullptr), _constant_value()
 {
 }
~NEMemsetKernel()
~NEMemsetKernel () default
Default destructor.
NEMemsetKernel() [2/3]
NEMemsetKernel (const NEMemsetKernel &) delete
Prevent instances of this class from being copied (As this class contains pointers)
NEMemsetKernel() [3/3]
NEMemsetKernel (NEMemsetKernel &&) default
Allow instances of this class to be moved.
Member Function Documentation
configure()
void configure (ITensor * tensor, const PixelValue & constant_value)
Initialise the kernel's tensor and filling value.
Parameters
[in,out] tensor Input tensor to fill. Supported data types: U8/S8/QASYMM8/U16/S16/F16/U32/S32/F32
[in] constant_value The value used to fill the planes of the tensor
Definition at line 40 of file NEMemsetKernel.cpp.
 {
     ARM_COMPUTE_ERROR_ON_NULLPTR(tensor);
     _tensor         = tensor;
     _constant_value = constant_value;
     // Configure kernel window
     Window win = calculate_max_window(*tensor->info(), Steps());
     INEKernel::configure(win);
 }
References ARM_COMPUTE_ERROR_ON_NULLPTR, arm_compute::calculate_max_window(), and ITensor::info().
Referenced by NESpaceToBatchLayer::configure().
name()
const char* name () const inline override virtual
Name of the kernel.
Returns
Kernel name
Implements ICPPKernel.
Definition at line 40 of file NEMemsetKernel.h.
     {
         return "NEMemsetKernel";
     }
operator=() [1/2]
NEMemsetKernel& operator= (const NEMemsetKernel &) delete
Prevent instances of this class from being copied (As this class contains pointers)
operator=() [2/2]
NEMemsetKernel& operator= (NEMemsetKernel &&) default
Allow instances of this class to be moved.
run()
void run (const Window & window, const ThreadInfo & info) override virtual
Execute the kernel on the passed window.
Warning
If is_parallelisable() returns false then the passed window must be equal to window()
Note
The window has to be a region within the window returned by the window() method
The width of the window has to be a multiple of num_elems_processed_per_iteration().
Parameters
[in] window Region on which to execute the kernel. (Must be a region of the window returned by window())
[in] info Info about executing thread and CPU.
Implements ICPPKernel.
Definition at line 51 of file NEMemsetKernel.cpp.
 {
     ARM_COMPUTE_UNUSED(info);
     ARM_COMPUTE_ERROR_ON_UNCONFIGURED_KERNEL(this);
     ARM_COMPUTE_ERROR_ON_INVALID_SUBWINDOW(INEKernel::window(), window);
     // Collapse all the batches on the third dimension
     bool   has_collapsed = true;
     Window collapsed     = window.collapse_if_possible(window, Window::DimZ, &has_collapsed);
     ARM_COMPUTE_ERROR_ON(!has_collapsed);
     uint8_t *const start_valid_region = _tensor->ptr_to_element(_tensor->info()->valid_region().anchor);
     const auto     window_width       = static_cast<int>(collapsed.x().end()) - static_cast<int>(collapsed.x().start());
     const size_t   element_size       = _tensor->info()->element_size();
     // Unroll X dimension
     collapsed.set(Window::DimX, Window::Dimension(0, 1, 1));
     Iterator tensor_it(_tensor, collapsed);
     execute_window_loop(collapsed, [&](const Coordinates &)
     {
         uint8_t *base_addr = start_valid_region + tensor_it.offset();
         // Set memory
         for(int i = 0; i < window_width; ++i)
         {
             std::memcpy(base_addr + i * element_size, &_constant_value.value, element_size);
         }
     },
     tensor_it);
 }
References ValidRegion::anchor, ARM_COMPUTE_ERROR_ON, ARM_COMPUTE_ERROR_ON_INVALID_SUBWINDOW, ARM_COMPUTE_ERROR_ON_UNCONFIGURED_KERNEL, ARM_COMPUTE_UNUSED, Window::collapse_if_possible(), Window::DimX, Window::DimZ, ITensorInfo::element_size(), Window::Dimension::end(), arm_compute::execute_window_loop(), ITensor::info(), arm_compute::test::validation::info, Iterator::offset(), ITensor::ptr_to_element(), Window::set(), Window::Dimension::start(), ITensorInfo::valid_region(), PixelValue::value, IKernel::window(), and Window::x().
The documentation for this class was generated from the following files:
arm_compute/core/NEON/kernels/NEMemsetKernel.h
src/core/NEON/kernels/NEMemsetKernel.cpp