Compute Library: NEBitwiseXorKernel Class Reference
NEBitwiseXorKernel Class Reference
Interface for the kernel to perform bitwise exclusive OR (XOR) between two tensors.
#include <NEBitwiseXorKernel.h>
Public Member Functions
const char * name () const override
Name of the kernel.
NEBitwiseXorKernel ()
Default constructor.
NEBitwiseXorKernel (const NEBitwiseXorKernel &)=delete
Prevent instances of this class from being copied (As this class contains pointers)
NEBitwiseXorKernel & operator= (const NEBitwiseXorKernel &)=delete
Prevent instances of this class from being copied (As this class contains pointers)
NEBitwiseXorKernel (NEBitwiseXorKernel &&)=default
Allow instances of this class to be moved.
NEBitwiseXorKernel & operator= (NEBitwiseXorKernel &&)=default
Allow instances of this class to be moved.
void configure (const ITensor *input1, const ITensor *input2, ITensor *output)
Initialise the kernel's input and output.
void run (const Window &window, const ThreadInfo &info) override
Execute the kernel on the passed window.
Public Member Functions inherited from ICPPKernel
virtual ~ICPPKernel ()=default
Default destructor.
Public Member Functions inherited from IKernel
IKernel ()
Constructor.
virtual ~IKernel ()=default
Destructor.
virtual bool is_parallelisable () const
Indicates whether or not the kernel is parallelisable.
virtual BorderSize border_size () const
The size of the border for that kernel.
const Window & window () const
The maximum window the kernel can be executed on.
Detailed Description
Interface for the kernel to perform bitwise exclusive OR (XOR) between two tensors.
Result is computed by:
\[ output(x,y) = input1(x,y) \oplus input2(x,y) \]
Definition at line 38 of file NEBitwiseXorKernel.h.
Constructor & Destructor Documentation
NEBitwiseXorKernel() [1/3]
NEBitwiseXorKernel ()
Default constructor.
Definition at line 52 of file NEBitwiseXorKernel.cpp.
     : _input1(nullptr), _input2(nullptr), _output(nullptr)
 {
 }
NEBitwiseXorKernel() [2/3]
NEBitwiseXorKernel (const NEBitwiseXorKernel &) delete
Prevent instances of this class from being copied (As this class contains pointers)
NEBitwiseXorKernel() [3/3]
NEBitwiseXorKernel (NEBitwiseXorKernel &&) default
Allow instances of this class to be moved.
Member Function Documentation
configure()
void configure (const ITensor * input1, const ITensor * input2, ITensor * output)
Initialise the kernel's input and output.
Parameters
[in] input1 An input tensor. Data type supported: U8.
[in] input2 An input tensor. Data type supported: U8
[out] output The output tensor. Data type supported: U8.
Definition at line 57 of file NEBitwiseXorKernel.cpp.
 {
     ARM_COMPUTE_ERROR_ON_NULLPTR(input1, input2, output);
     set_shape_if_empty(*output->info(), input1->info()->tensor_shape());
     set_format_if_unknown(*output->info(), Format::U8);
     set_format_if_unknown(*input1->info(), Format::U8);
     set_format_if_unknown(*input2->info(), Format::U8);
     ARM_COMPUTE_ERROR_ON_MISMATCHING_SHAPES(input1, input2, output);
     ARM_COMPUTE_ERROR_ON_DATA_TYPE_CHANNEL_NOT_IN(input1, 1, DataType::U8);
     ARM_COMPUTE_ERROR_ON_DATA_TYPE_CHANNEL_NOT_IN(input2, 1, DataType::U8);
     ARM_COMPUTE_ERROR_ON_DATA_TYPE_CHANNEL_NOT_IN(output, 1, DataType::U8);
     ARM_COMPUTE_ERROR_ON_MISMATCHING_DATA_TYPES(input1, input2, output);
     _input1 = input1;
     _input2 = input2;
     _output = output;
     constexpr unsigned int num_elems_processed_per_iteration = 16;
     Window                 win = calculate_max_window(*input1->info(), Steps(num_elems_processed_per_iteration));
     AccessWindowHorizontal output_access(output->info(), 0, num_elems_processed_per_iteration);
     update_window_and_padding(win, AccessWindowHorizontal(input1->info(), 0, num_elems_processed_per_iteration),
                               AccessWindowHorizontal(input2->info(), 0, num_elems_processed_per_iteration), output_access);
     const ValidRegion valid_region = intersect_valid_regions(input1->info()->valid_region(), input2->info()->valid_region());
     output_access.set_valid_region(win, valid_region);
     INEKernel::configure(win);
 }
References ARM_COMPUTE_ERROR_ON_DATA_TYPE_CHANNEL_NOT_IN, ARM_COMPUTE_ERROR_ON_MISMATCHING_DATA_TYPES, ARM_COMPUTE_ERROR_ON_MISMATCHING_SHAPES, ARM_COMPUTE_ERROR_ON_NULLPTR, arm_compute::calculate_max_window(), ITensor::info(), arm_compute::intersect_valid_regions(), arm_compute::set_format_if_unknown(), arm_compute::set_shape_if_empty(), ITensorInfo::tensor_shape(), arm_compute::U8, arm_compute::update_window_and_padding(), arm_compute::test::validation::valid_region, and ITensorInfo::valid_region().
name()
const char* name () const inline override virtual
Name of the kernel.
Returns
Kernel name
Implements ICPPKernel.
Definition at line 41 of file NEBitwiseXorKernel.h.
     {
         return "NEBitwiseXorKernel";
     }
operator=() [1/2]
NEBitwiseXorKernel& operator= (const NEBitwiseXorKernel &) delete
Prevent instances of this class from being copied (As this class contains pointers)
operator=() [2/2]
NEBitwiseXorKernel& operator= (NEBitwiseXorKernel &&) default
Allow instances of this class to be moved.
run()
void run (const Window & window, const ThreadInfo & info) override virtual
Execute the kernel on the passed window.
Warning
If is_parallelisable() returns false then the passed window must be equal to window()
Note
The window has to be a region within the window returned by the window() method
The width of the window has to be a multiple of num_elems_processed_per_iteration().
Parameters
[in] window Region on which to execute the kernel. (Must be a region of the window returned by window())
[in] info Info about executing thread and CPU.
Implements ICPPKernel.
Definition at line 92 of file NEBitwiseXorKernel.cpp.
 {
     ARM_COMPUTE_UNUSED(info);
     ARM_COMPUTE_ERROR_ON_UNCONFIGURED_KERNEL(this);
     ARM_COMPUTE_ERROR_ON_INVALID_SUBWINDOW(INEKernel::window(), window);
     Iterator input1(_input1, window);
     Iterator input2(_input2, window);
     Iterator output(_output, window);
     execute_window_loop(window, [&](const Coordinates &)
     {
         bitwise_xor_U8_U8_U8(input1.ptr(), input2.ptr(), output.ptr());
     },
     input1, input2, output);
 }
References ARM_COMPUTE_ERROR_ON_INVALID_SUBWINDOW, ARM_COMPUTE_ERROR_ON_UNCONFIGURED_KERNEL, ARM_COMPUTE_UNUSED, arm_compute::execute_window_loop(), arm_compute::test::validation::info, Iterator::ptr(), and IKernel::window().
The documentation for this class was generated from the following files:
arm_compute/core/NEON/kernels/NEBitwiseXorKernel.h
src/core/NEON/kernels/NEBitwiseXorKernel.cpp