Compute Library: Printer Class Reference
Printer Class Reference abstract
Abstract printer class used by the Framework to present output.
#include <Printer.h>
Public Member Functions
Printer ()=default
Default constructor.
Printer (std::ostream &stream)
Construct printer with given output stream.
Printer (const Printer &)=delete
Prevent instances of this class from being copy constructed.
Printer & operator= (const Printer &)=delete
Prevent instances of this class from being copied.
Printer (Printer &&)=default
Allow instances of this class to be move constructed.
Printer & operator= (Printer &&)=default
Allow instances of this class to be moved.
virtual ~Printer ()=default
Default destructor.
void print (const std::string &str)
Print given string.
virtual void print_entry (const std::string &name, const std::string &value)=0
Print an entry consisting of a (name, value) pair.
virtual void print_global_header ()=0
Print global header.
virtual void print_global_footer ()=0
Print global footer.
virtual void print_run_header ()=0
Print header before running all tests.
virtual void print_run_footer ()=0
Print footer after running all tests.
virtual void print_test_header (const TestInfo &info)=0
Print header before a test.
virtual void print_test_footer ()=0
Print footer after a test.
virtual void print_errors_header ()=0
Print header before errors.
virtual void print_errors_footer ()=0
Print footer after errors.
virtual void print_list_tests (const std::vector< TestInfo > &infos)=0
Print the list of all the tests.
virtual void print_error (const std::exception &error, bool expected)=0
Print test error.
virtual void print_info (const std::string &info)=0
Print test log info.
virtual void print_measurements (const Profiler::MeasurementsMap &measurements)=0
Print measurements for a test.
void set_stream (std::ostream &stream)
Set the output stream.
Detailed Description
Abstract printer class used by the Framework to present output.
Definition at line 43 of file Printer.h.
Constructor & Destructor Documentation
Printer() [1/4]
Printer () default
Default constructor.
Prints values to std::cout.
Printer() [2/4]
Printer (std::ostream & stream)
Construct printer with given output stream.
Parameters
[out] stream Output stream.
Definition at line 32 of file Printer.cpp.
     : _stream{ &stream }
 {
 }
Printer() [3/4]
Printer (const Printer &) delete
Prevent instances of this class from being copy constructed.
Printer() [4/4]
Printer (Printer &&) default
Allow instances of this class to be move constructed.
~Printer()
virtual ~Printer () virtual default
Default destructor.
Member Function Documentation
operator=() [1/2]
Printer& operator= (const Printer &) delete
Prevent instances of this class from being copied.
operator=() [2/2]
Printer& operator= (Printer &&) default
Allow instances of this class to be moved.
print()
void print (const std::string & str)
Print given string.
Parameters
[in] str String.
Definition at line 37 of file Printer.cpp.
 {
     *_stream << str;
 }
print_entry()
virtual void print_entry (const std::string & name, const std::string & value) pure virtual
Print an entry consisting of a (name, value) pair.
Parameters
[in] name Description of the value.
[in] value Value.
Implemented in PrettyPrinter, and JSONPrinter.
print_error()
virtual void print_error (const std::exception & error, bool expected) pure virtual
Print test error.
Parameters
[in] error Description of the error.
[in] expected Whether the error was expected or not.
Implemented in PrettyPrinter, and JSONPrinter.
Referenced by Framework::log_failed_expectation().
print_errors_footer()
virtual void print_errors_footer () pure virtual
Print footer after errors.
Implemented in PrettyPrinter, and JSONPrinter.
print_errors_header()
virtual void print_errors_header () pure virtual
Print header before errors.
Implemented in PrettyPrinter, and JSONPrinter.
print_global_footer()
virtual void print_global_footer () pure virtual
Print global footer.
Implemented in PrettyPrinter, and JSONPrinter.
print_global_header()
virtual void print_global_header () pure virtual
Print global header.
Implemented in PrettyPrinter, and JSONPrinter.
print_info()
virtual void print_info (const std::string & info) pure virtual
Print test log info.
Parameters
[in] info Description of the log.
Implemented in PrettyPrinter, and JSONPrinter.
Referenced by Framework::log_info().
print_list_tests()
virtual void print_list_tests (const std::vector< TestInfo > & infos) pure virtual
Print the list of all the tests.
Parameters
[in] infos List of tests to print
Implemented in PrettyPrinter, and JSONPrinter.
print_measurements()
virtual void print_measurements (const Profiler::MeasurementsMap & measurements) pure virtual
Print measurements for a test.
Parameters
[in] measurements Measurements as collected by a Profiler.
Implemented in PrettyPrinter, and JSONPrinter.
Referenced by Framework::log_test_end(), and Framework::print_test_results().
print_run_footer()
virtual void print_run_footer () pure virtual
Print footer after running all tests.
Implemented in PrettyPrinter, and JSONPrinter.
Referenced by Framework::print_test_results(), and Framework::run().
print_run_header()
virtual void print_run_header () pure virtual
Print header before running all tests.
Implemented in PrettyPrinter, and JSONPrinter.
Referenced by Framework::print_test_results(), and Framework::run().
print_test_footer()
virtual void print_test_footer () pure virtual
Print footer after a test.
Implemented in PrettyPrinter, and JSONPrinter.
Referenced by Framework::log_test_end(), and Framework::print_test_results().
print_test_header()
virtual void print_test_header (const TestInfo & info) pure virtual
Print header before a test.
Parameters
[in] info Test info.
Implemented in PrettyPrinter, and JSONPrinter.
Referenced by Framework::log_test_start(), and Framework::print_test_results().
set_stream()
void set_stream (std::ostream & stream)
Set the output stream.
Parameters
[out] stream Output stream.
Definition at line 42 of file Printer.cpp.
 {
     _stream = &stream;
 }
The documentation for this class was generated from the following files:
tests/framework/printers/Printer.h
tests/framework/printers/Printer.cpp