Compute Library: DeconvolutionLayer Class Reference
DeconvolutionLayer Class Reference final
Deconvolution Layer.
#include <Layers.h>
Public Member Functions
DeconvolutionLayer (unsigned int conv_width, unsigned int conv_height, unsigned int ofm, ITensorAccessorUPtr weights, ITensorAccessorUPtr bias, PadStrideInfo deconv_info)
Construct a convolution layer.
NodeID create_layer (IStream &s) override
Create layer and add to the given stream.
Public Member Functions inherited from ILayer
virtual ~ILayer ()=default
Default destructor.
ILayer & set_name (std::string name)
Sets the name of the layer.
const std::string & name () const
Layer name accessor.
Detailed Description
Deconvolution Layer.
Definition at line 368 of file Layers.h.
Constructor & Destructor Documentation
DeconvolutionLayer()
DeconvolutionLayer (unsigned int conv_width, unsigned int conv_height, unsigned int ofm, ITensorAccessorUPtr weights, ITensorAccessorUPtr bias, PadStrideInfo deconv_info) inline
Construct a convolution layer.
Parameters
[in] conv_width Convolution width.
[in] conv_height Convolution height.
[in] ofm Output feature map.
[in] weights Accessor to get kernel weights from.
[in] bias Accessor to get kernel bias from.
[in] deconv_info Padding and stride information.
Definition at line 380 of file Layers.h.
         : _conv_width(conv_width),
           _conv_height(conv_height),
           _ofm(ofm),
           _deconv_info(std::move(deconv_info)),
           _weights(std::move(weights)),
           _bias(std::move(bias))
     {
     }
Member Function Documentation
create_layer()
NodeID create_layer (IStream & s) inline override virtual
Create layer and add to the given stream.
Parameters
[in] s Stream to add layer to.
Returns
ID of the created node.
Implements ILayer.
Definition at line 395 of file Layers.h.
     {
         NodeIdxPair input         = { s.tail_node(), 0 };
         NodeParams  common_params = { name(), s.hints().target_hint };
         return GraphBuilder::add_deconvolution_node(s.graph(), common_params, input,
                                                     Size2D(_conv_width, _conv_height), _ofm, _deconv_info,
                                                     std::move(_weights), std::move(_bias));
     }
References GraphBuilder::add_deconvolution_node(), IStream::graph(), IStream::hints(), ILayer::name(), IStream::tail_node(), and StreamHints::target_hint.
The documentation for this class was generated from the following file:
arm_compute/graph/frontend/Layers.h