Compute Library: GCBufferAllocator Class Reference
GCBufferAllocator Class Reference final
Default GLES buffer allocator implementation.
#include <GCBufferAllocator.h>
Public Member Functions
GCBufferAllocator ()=default
Default constructor.
void * allocate (size_t size, size_t alignment) override
Interface to be implemented by the child class to allocate bytes.
void free (void *ptr) override
Interface to be implemented by the child class to free the allocated tensor.
std::unique_ptr< IMemoryRegion > make_region (size_t size, size_t alignment) override
Create self-managed memory region.
Public Member Functions inherited from IAllocator
virtual ~IAllocator ()=default
Default virtual destructor.
Detailed Description
Default GLES buffer allocator implementation.
Definition at line 37 of file GCBufferAllocator.h.
Constructor & Destructor Documentation
GCBufferAllocator()
GCBufferAllocator () default
Default constructor.
Member Function Documentation
allocate()
void * allocate (size_t size, size_t alignment) override virtual
Interface to be implemented by the child class to allocate bytes.
Parameters
[in] size Size to allocate
[in] alignment Alignment that the returned pointer should comply with
Returns
A pointer to the allocated memory
Implements IAllocator.
Definition at line 34 of file GCBufferAllocator.cpp.
 {
     ARM_COMPUTE_UNUSED(alignment);
     auto *gl_ssbo_name = new GLuint;
     ARM_COMPUTE_GL_CHECK(glBindBuffer(GL_SHADER_STORAGE_BUFFER, *gl_ssbo_name));
     ARM_COMPUTE_GL_CHECK(glBufferData(GL_SHADER_STORAGE_BUFFER, static_cast<GLsizeiptr>(size), nullptr, GL_STATIC_DRAW));
     ARM_COMPUTE_GL_CHECK(glBindBuffer(GL_SHADER_STORAGE_BUFFER, 0));
     return reinterpret_cast<void *>(gl_ssbo_name);
 }
References ARM_COMPUTE_GL_CHECK, ARM_COMPUTE_UNUSED, glBindBuffer(), and glBufferData().
free()
void free (void * ptr) override virtual
Interface to be implemented by the child class to free the allocated tensor.
Implements IAllocator.
Definition at line 46 of file GCBufferAllocator.cpp.
 {
     ARM_COMPUTE_ERROR_ON(ptr == nullptr);
     auto *gl_ssbo_name = reinterpret_cast<GLuint *>(ptr);
     ARM_COMPUTE_GL_CHECK(glDeleteBuffers(1, gl_ssbo_name));
     delete gl_ssbo_name;
 }
References ARM_COMPUTE_ERROR_ON, ARM_COMPUTE_GL_CHECK, and glDeleteBuffers().
make_region()
std::unique_ptr< IMemoryRegion > make_region (size_t size, size_t alignment) override virtual
Create self-managed memory region.
Parameters
[in] size Size of the memory region
[in] alignment Alignment of the memory region
Returns
The memory region object
Implements IAllocator.
Definition at line 54 of file GCBufferAllocator.cpp.
 {
     ARM_COMPUTE_UNUSED(alignment);
     return arm_compute::support::cpp14::make_unique<GCBufferMemoryRegion>(size);
 }
References ARM_COMPUTE_UNUSED.
The documentation for this class was generated from the following files:
arm_compute/runtime/GLES_COMPUTE/GCBufferAllocator.h
src/runtime/GLES_COMPUTE/GCBufferAllocator.cpp