Compute Library: NETableLookupKernel Class Reference
NETableLookupKernel Class Reference
Interface for the kernel to perform table lookup calculations.
#include <NETableLookupKernel.h>
Public Member Functions
const char * name () const override
Name of the kernel.
NETableLookupKernel ()
Default constructor.
NETableLookupKernel (const NETableLookupKernel &)=delete
Prevent instances of this class from being copied (As this class contains pointers)
NETableLookupKernel & operator= (const NETableLookupKernel &)=delete
Prevent instances of this class from being copied (As this class contains pointers)
NETableLookupKernel (NETableLookupKernel &&)=default
Allow instances of this class to be moved.
NETableLookupKernel & operator= (NETableLookupKernel &&)=default
Allow instances of this class to be moved.
void configure (const ITensor *input, const ILut *lut, ITensor *output)
Initialise the kernel's input, lut and output.
void run (const Window &window, const ThreadInfo &info) override
Execute the kernel on the passed window.
Public Member Functions inherited from ICPPSimpleKernel
ICPPSimpleKernel ()
Constructor.
ICPPSimpleKernel (const ICPPSimpleKernel &)=delete
Prevent instances of this class from being copied (As this class contains pointers)
ICPPSimpleKernel & operator= (const ICPPSimpleKernel &)=delete
Prevent instances of this class from being copied (As this class contains pointers)
ICPPSimpleKernel (ICPPSimpleKernel &&)=default
Allow instances of this class to be moved.
ICPPSimpleKernel & operator= (ICPPSimpleKernel &&)=default
Allow instances of this class to be moved.
~ICPPSimpleKernel ()=default
Default destructor.
Public Member Functions inherited from ICPPKernel
virtual ~ICPPKernel ()=default
Default destructor.
Public Member Functions inherited from IKernel
IKernel ()
Constructor.
virtual ~IKernel ()=default
Destructor.
virtual bool is_parallelisable () const
Indicates whether or not the kernel is parallelisable.
virtual BorderSize border_size () const
The size of the border for that kernel.
const Window & window () const
The maximum window the kernel can be executed on.
Detailed Description
Interface for the kernel to perform table lookup calculations.
Definition at line 35 of file NETableLookupKernel.h.
Constructor & Destructor Documentation
NETableLookupKernel() [1/3]
NETableLookupKernel ()
Default constructor.
Definition at line 46 of file NETableLookupKernel.cpp.
     : _func(nullptr), _lut(nullptr)
 {
 }
NETableLookupKernel() [2/3]
NETableLookupKernel (const NETableLookupKernel &) delete
Prevent instances of this class from being copied (As this class contains pointers)
NETableLookupKernel() [3/3]
NETableLookupKernel (NETableLookupKernel &&) default
Allow instances of this class to be moved.
Member Function Documentation
configure()
void configure (const ITensor * input, const ILut * lut, ITensor * output)
Initialise the kernel's input, lut and output.
Parameters
[in] input An input tensor. Data types supported: U8/S16.
[in] lut The input LUT.
[out] output The output tensor. Data types supported: same as input
Definition at line 109 of file NETableLookupKernel.cpp.
 {
     ARM_COMPUTE_ERROR_ON(input == nullptr);
     ARM_COMPUTE_ERROR_ON(lut == nullptr);
     ARM_COMPUTE_ERROR_ON(output == nullptr);
     ARM_COMPUTE_ERROR_ON_DATA_TYPE_CHANNEL_NOT_IN(input, 1, DataType::U8, DataType::S16);
     ARM_COMPUTE_ERROR_ON_DATA_TYPE_CHANNEL_NOT_IN(output, 1, DataType::U8, DataType::S16);
     ARM_COMPUTE_ERROR_ON_MISMATCHING_DATA_TYPES(input, output);
     _lut = lut;
     if(input->info()->data_type() == DataType::U8 && output->info()->data_type() == DataType::U8)
     {
         _func = &NETableLookupKernel::tableLookup<uint8_t>;
     }
     else if(input->info()->data_type() == DataType::S16 && output->info()->data_type() == DataType::S16)
     {
         _func = &NETableLookupKernel::tableLookup<int16_t>;
     }
     else
     {
         ARM_COMPUTE_ERROR("Unsupported combination of input and output DataType.");
     }
     INESimpleKernel::configure(input, output, num_num_elems_processed_per_iteration);
 }
References ARM_COMPUTE_ERROR, ARM_COMPUTE_ERROR_ON, ARM_COMPUTE_ERROR_ON_DATA_TYPE_CHANNEL_NOT_IN, ARM_COMPUTE_ERROR_ON_MISMATCHING_DATA_TYPES, ITensorInfo::data_type(), ITensor::info(), arm_compute::num_num_elems_processed_per_iteration, arm_compute::S16, and arm_compute::U8.
Referenced by NEEqualizeHistogram::configure().
name()
const char* name () const inline override virtual
Name of the kernel.
Returns
Kernel name
Implements ICPPKernel.
Definition at line 38 of file NETableLookupKernel.h.
     {
         return "NETableLookupKernel";
     }
operator=() [1/2]
NETableLookupKernel& operator= (const NETableLookupKernel &) delete
Prevent instances of this class from being copied (As this class contains pointers)
operator=() [2/2]
NETableLookupKernel& operator= (NETableLookupKernel &&) default
Allow instances of this class to be moved.
run()
void run (const Window & window, const ThreadInfo & info) override virtual
Execute the kernel on the passed window.
Warning
If is_parallelisable() returns false then the passed window must be equal to window()
Note
The window has to be a region within the window returned by the window() method
The width of the window has to be a multiple of num_elems_processed_per_iteration().
Parameters
[in] window Region on which to execute the kernel. (Must be a region of the window returned by window())
[in] info Info about executing thread and CPU.
Implements ICPPKernel.
Definition at line 136 of file NETableLookupKernel.cpp.
 {
     ARM_COMPUTE_UNUSED(info);
     ARM_COMPUTE_ERROR_ON_UNCONFIGURED_KERNEL(this);
     ARM_COMPUTE_ERROR_ON_INVALID_SUBWINDOW(INESimpleKernel::window(), window);
     ARM_COMPUTE_ERROR_ON(_func == nullptr);
     (this->*_func)(window);
 }
References ARM_COMPUTE_ERROR_ON, ARM_COMPUTE_ERROR_ON_INVALID_SUBWINDOW, ARM_COMPUTE_ERROR_ON_UNCONFIGURED_KERNEL, ARM_COMPUTE_UNUSED, arm_compute::test::validation::info, and IKernel::window().
The documentation for this class was generated from the following files:
arm_compute/core/NEON/kernels/NETableLookupKernel.h
src/core/NEON/kernels/NETableLookupKernel.cpp