Compute Library: TensorAllocator Class Reference
TensorAllocator Class Reference
Basic implementation of a CPU memory tensor allocator.
#include <TensorAllocator.h>
Public Member Functions
TensorAllocator (Tensor *owner=nullptr)
Default constructor.
~TensorAllocator ()
Default destructor.
TensorAllocator (const TensorAllocator &)=delete
Prevent instances of this class from being copied (As this class contains pointers)
TensorAllocator & operator= (const TensorAllocator &)=delete
Prevent instances of this class from being copy assigned (As this class contains pointers)
TensorAllocator (TensorAllocator &&) noexcept
Allow instances of this class to be moved.
TensorAllocator & operator= (TensorAllocator &&) noexcept
Allow instances of this class to be moved.
void init (const TensorAllocator &allocator, const Coordinates &coords, TensorInfo &sub_info)
Shares the same backing memory with another tensor allocator, while the tensor info might be different.
uint8_t * data () const
Returns the pointer to the allocated data.
void allocate () override
Allocate size specified by TensorInfo of CPU memory.
void free () override
Free allocated CPU memory.
Status import_memory (void *memory)
Import an existing memory as a tensor's backing memory.
void set_associated_memory_group (MemoryGroup *associated_memory_group)
Associates the tensor with a memory group.
void init (const TensorInfo &input, size_t alignment=0)
Make ITensorAllocator's init methods available.
Public Member Functions inherited from ITensorAllocator
ITensorAllocator ()
Default constructor.
ITensorAllocator (const ITensorAllocator &)=default
Allow instances of this class to be copy constructed.
ITensorAllocator & operator= (const ITensorAllocator &)=default
Allow instances of this class to be copied.
ITensorAllocator (ITensorAllocator &&)=default
Allow instances of this class to be move constructed.
ITensorAllocator & operator= (ITensorAllocator &&)=default
Allow instances of this class to be moved.
virtual ~ITensorAllocator ()=default
Default virtual destructor.
void init (const TensorInfo &input, size_t alignment=0)
Initialize a tensor based on the passed TensorInfo.
TensorInfo & info ()
Return a reference to the tensor's metadata.
const TensorInfo & info () const
Return a constant reference to the tensor's metadata.
size_t alignment () const
Return underlying's tensor buffer alignment.
Detailed Description
Basic implementation of a CPU memory tensor allocator.
Definition at line 44 of file TensorAllocator.h.
Constructor & Destructor Documentation
TensorAllocator() [1/3]
TensorAllocator (Tensor * owner = nullptr)
Default constructor.
Parameters
[in] owner Owner of the tensor allocator.
Definition at line 69 of file TensorAllocator.cpp.
     : _associated_memory_group(nullptr), _memory(), _owner(owner)
 {
 }
~TensorAllocator()
~TensorAllocator ()
Default destructor.
Definition at line 74 of file TensorAllocator.cpp.
 {
     info().set_is_resizable(true);
 }
References ITensorAllocator::info(), and TensorInfo::set_is_resizable().
TensorAllocator() [2/3]
TensorAllocator (const TensorAllocator &) delete
Prevent instances of this class from being copied (As this class contains pointers)
TensorAllocator() [3/3]
TensorAllocator (TensorAllocator && o) noexcept
Allow instances of this class to be moved.
Definition at line 79 of file TensorAllocator.cpp.
     : ITensorAllocator(std::move(o)),
       _associated_memory_group(o._associated_memory_group),
       _memory(std::move(o._memory)),
       _owner(o._owner)
 {
     o._associated_memory_group = nullptr;
     o._memory                  = Memory();
     o._owner                   = nullptr;
 }
Member Function Documentation
allocate()
void allocate () override virtual
Allocate size specified by TensorInfo of CPU memory.
Note
The tensor must not already be allocated when calling this function.
Implements ITensorAllocator.
Definition at line 133 of file TensorAllocator.cpp.
 {
     if(_associated_memory_group == nullptr)
     {
         _memory.set_owned_region(support::cpp14::make_unique<MemoryRegion>(info().total_size(), alignment()));
     }
     else
     {
         _associated_memory_group->finalize_memory(_owner, _memory, info().total_size(), alignment());
     }
     info().set_is_resizable(false);
 }
References ITensorAllocator::alignment(), MemoryGroupBase< TensorType >::finalize_memory(), ITensorAllocator::info(), TensorInfo::set_is_resizable(), and Memory::set_owned_region().
Referenced by NETensorHandle::allocate(), NEGEMMLowpAssemblyMatrixMultiplyCore::configure(), NEFFT2D::configure(), NEL2NormalizeLayer::configure(), NEScale::configure(), NEFFT1D::configure(), NEHOGDescriptor::configure(), NENormalizationLayer::configure(), NEGaussian5x5::configure(), NEHOGGradient::configure(), NERNNLayer::configure(), NESobel5x5::configure(), NESobel7x7::configure(), NEFastCorners::configure(), CPPDetectionPostProcessLayer::configure(), NEDepthwiseConvolutionAssemblyDispatch::configure(), NESoftmaxLayer::configure(), NEWinogradConvolutionLayer::configure(), NELocallyConnectedLayer::configure(), NEGEMM::configure(), NECannyEdge::configure(), NEHarrisCorners::configure(), NEHOGMultiDetection::configure(), NEFFTConvolutionLayer::configure(), NEGEMMLowpMatrixMultiplyCore::configure(), NELSTMLayer::configure(), NELSTMLayerQuantized::configure(), NEDeconvolutionLayer::configure(), NEFullyConnectedLayer::configure(), NEGEMMInterleavedWrapper::configure(), NEGEMMConvolutionLayer::configure(), NEDepthwiseConvolutionLayer::configure(), NumPyAccessor::NumPyAccessor(), NEWinogradConvolutionLayer::prepare(), NELocallyConnectedLayer::prepare(), NEGEMM::prepare(), NEDepthwiseConvolutionLayer3x3::prepare(), NEGEMMLowpMatrixMultiplyCore::prepare(), NEDepthwiseConvolutionAssemblyDispatch::prepare(), NEFFTConvolutionLayer::prepare(), NEDeconvolutionLayer::prepare(), NEGEMMInterleavedWrapper::prepare(), NEFullyConnectedLayer::prepare(), NELSTMLayerQuantized::prepare(), NEGEMMConvolutionLayer::prepare(), NEDepthwiseConvolutionLayerOptimized::prepare(), NEDepthwiseConvolutionLayer::prepare(), and arm_compute::test::validation::TEST_CASE().
data()
uint8_t * data () const
Returns the pointer to the allocated data.
Returns
a pointer to the allocated data.
Definition at line 128 of file TensorAllocator.cpp.
 {
     return (_memory.region() == nullptr) ? nullptr : reinterpret_cast<uint8_t *>(_memory.region()->buffer());
 }
References IMemoryRegion::buffer(), and Memory::region().
Referenced by Tensor::buffer().
free()
void free () override virtual
Free allocated CPU memory.
Note
The tensor must have been allocated when calling this function.
Implements ITensorAllocator.
Definition at line 146 of file TensorAllocator.cpp.
 {
     _memory.set_region(nullptr);
     info().set_is_resizable(true);
 }
References ITensorAllocator::info(), TensorInfo::set_is_resizable(), and Memory::set_region().
Referenced by NEDirectConvolutionLayer::configure(), NETensorHandle::free(), NEWinogradConvolutionLayer::prepare(), NEDepthwiseConvolutionLayer3x3::prepare(), NEFFTConvolutionLayer::prepare(), NEDeconvolutionLayer::prepare(), NELSTMLayerQuantized::prepare(), NEGEMMConvolutionLayer::prepare(), NEDepthwiseConvolutionLayerOptimized::prepare(), NETensorHandle::release_if_unused(), and arm_compute::test::validation::TEST_CASE().
import_memory()
Status import_memory (void * memory)
Import an existing memory as a tensor's backing memory.
Warning
size is expected to be compliant with total_size reported by ITensorInfo.
ownership of memory is not transferred.
tensor shouldn't be memory managed.
padding should be accounted by the client code.
memory must be writable in case of in-place operations
Note
buffer alignment will be checked to be compliant with alignment reported by ITensorInfo.
Parameters
[in] memory Raw memory pointer to be used as backing memory
Returns
An error status
Definition at line 152 of file TensorAllocator.cpp.
 {
     ARM_COMPUTE_RETURN_ERROR_ON(memory == nullptr);
     ARM_COMPUTE_RETURN_ERROR_ON(_associated_memory_group != nullptr);
     ARM_COMPUTE_RETURN_ERROR_ON(alignment() != 0 && !arm_compute::utility::check_aligned(memory, alignment()));
     _memory.set_owned_region(support::cpp14::make_unique<MemoryRegion>(memory, info().total_size()));
     info().set_is_resizable(false);
     return Status{};
 }
References ITensorAllocator::alignment(), ARM_COMPUTE_RETURN_ERROR_ON, arm_compute::utility::check_aligned(), ITensorAllocator::info(), TensorInfo::set_is_resizable(), and Memory::set_owned_region().
Referenced by NEFFTConvolutionLayer::run(), and arm_compute::test::validation::TEST_CASE().
init() [1/2]
void init
Make ITensorAllocator's init methods available.
Definition at line 38 of file ITensorAllocator.cpp.
 {
     _info      = input;
     _alignment = alignment;
 }
init() [2/2]
void init (const TensorAllocator & allocator, const Coordinates & coords, TensorInfo & sub_info)
Shares the same backing memory with another tensor allocator, while the tensor info might be different.
In other words this can be used to create a sub-tensor from another tensor while sharing the same memory.
Note
TensorAllocator have to be of the same specialized type.
Parameters
[in] allocator The allocator that owns the backing memory to be shared. Ownership becomes shared afterwards.
[in] coords The starting coordinates of the new tensor inside the parent tensor.
[in] sub_info The new tensor information (e.g. shape etc)
Definition at line 108 of file TensorAllocator.cpp.
 {
     // Get parent info
     const TensorInfo parent_info = allocator.info();
     // Check if coordinates and new shape are within the parent tensor
     ARM_COMPUTE_ERROR_ON(!validate_subtensor_shape(parent_info, sub_info, coords));
     ARM_COMPUTE_UNUSED(validate_subtensor_shape);
     // Copy pointer to buffer
     _memory = Memory(allocator._memory.region());
     // Init tensor info with new dimensions
     size_t total_size = parent_info.offset_element_in_bytes(coords) + sub_info.total_size() - sub_info.offset_first_element_in_bytes();
     sub_info.init(sub_info.tensor_shape(), sub_info.format(), parent_info.strides_in_bytes(), parent_info.offset_element_in_bytes(coords), total_size);
     // Set TensorInfo
     init(sub_info);
 }
References arm_compute::test::validation::allocator(), ARM_COMPUTE_ERROR_ON, ARM_COMPUTE_UNUSED, TensorInfo::format(), TensorInfo::init(), TensorInfo::offset_element_in_bytes(), TensorInfo::offset_first_element_in_bytes(), TensorInfo::strides_in_bytes(), TensorInfo::tensor_shape(), and TensorInfo::total_size().
Referenced by NEGEMMLowpAssemblyMatrixMultiplyCore::configure(), NEScale::configure(), NEFFT1D::configure(), NEHOGDescriptor::configure(), NEGaussian5x5::configure(), NEHOGGradient::configure(), NENormalizationLayer::configure(), NERNNLayer::configure(), NESobel5x5::configure(), NESobel7x7::configure(), NEFastCorners::configure(), NEDepthwiseConvolutionAssemblyDispatch::configure(), NEWinogradConvolutionLayer::configure(), NESoftmaxLayer::configure(), NELocallyConnectedLayer::configure(), NEGEMM::configure(), NECannyEdge::configure(), NEHarrisCorners::configure(), NEHOGMultiDetection::configure(), NEFFTConvolutionLayer::configure(), NEGEMMLowpMatrixMultiplyCore::configure(), NELSTMLayer::configure(), NELSTMLayerQuantized::configure(), NEDeconvolutionLayer::configure(), NEFullyConnectedLayer::configure(), NEGEMMInterleavedWrapper::configure(), NEGEMMConvolutionLayer::configure(), NEDepthwiseConvolutionLayer::configure(), NETensorHandle::NETensorHandle(), NumPyAccessor::NumPyAccessor(), and arm_compute::test::validation::TEST_CASE().
operator=() [1/2]
TensorAllocator& operator= (const TensorAllocator &) delete
Prevent instances of this class from being copy assigned (As this class contains pointers)
operator=() [2/2]
TensorAllocator & operator= (TensorAllocator && o) noexcept
Allow instances of this class to be moved.
Definition at line 90 of file TensorAllocator.cpp.
 {
     if(&o != this)
     {
         _associated_memory_group   = o._associated_memory_group;
         o._associated_memory_group = nullptr;
         _memory   = std::move(o._memory);
         o._memory = Memory();
         _owner   = o._owner;
         o._owner = nullptr;
         ITensorAllocator::operator=(std::move(o));
     }
     return *this;
 }
References ITensorAllocator::operator=().
set_associated_memory_group()
void set_associated_memory_group (MemoryGroup * associated_memory_group)
Associates the tensor with a memory group.
Parameters
[in] associated_memory_group Memory group to associate the tensor with
Definition at line 164 of file TensorAllocator.cpp.
 {
     ARM_COMPUTE_ERROR_ON(associated_memory_group == nullptr);
     ARM_COMPUTE_ERROR_ON(_associated_memory_group != nullptr);
     ARM_COMPUTE_ERROR_ON(_memory.region() != nullptr && _memory.region()->buffer() != nullptr);
     _associated_memory_group = associated_memory_group;
 }
References ARM_COMPUTE_ERROR_ON, IMemoryRegion::buffer(), and Memory::region().
The documentation for this class was generated from the following files:
arm_compute/runtime/TensorAllocator.h
src/runtime/TensorAllocator.cpp