Compute Library: Edge Class Reference
Edge Class Reference final
Graph Edge.
#include <Edge.h>
Public Member Functions
Edge (EdgeID id, INode *producer, unsigned int producer_idx, INode *consumer, unsigned int consumer_idx, Tensor *tensor)
Default Constructor.
EdgeID id () const
Returns edge id.
NodeID producer_id () const
Returns producer node id.
NodeID consumer_id () const
Returns sink node id.
INode * producer () const
Returns producer node.
INode * consumer () const
Returns consumer node.
unsigned int producer_idx () const
Returns the index of the output that produces the result in the producer node.
unsigned int consumer_idx () const
Returns the index of the input that consumes the result in the consumer node.
Tensor * tensor () const
Returns the tensor associated with this edge.
TensorID tensor_id () const
Returns the tensor id associated with this edge.
void update_bound_tensor (Tensor *tensor)
Bind the edge to another tensor.
Friends
class Graph
Detailed Description
Graph Edge.
Definition at line 39 of file Edge.h.
Constructor & Destructor Documentation
Edge()
Edge (EdgeID id, INode * producer, unsigned int producer_idx, INode * consumer, unsigned int consumer_idx, Tensor * tensor) inline
Default Constructor.
Parameters
[in] id Edge id
[in] producer Producer node id
[in] producer_idx Producer node output index
[in] consumer Consumer node id
[in] consumer_idx Consumer node input index
[in] tensor Tensor associated with the edge
Definition at line 51 of file Edge.h.
         : _id(id), _producer(producer), _consumer(consumer), _producer_idx(producer_idx), _consumer_idx(consumer_idx), _tensor(tensor)
     {
     }
Member Function Documentation
consumer()
INode* consumer () const inline
Returns consumer node.
Returns
Consumer node
Definition at line 92 of file Edge.h.
     {
         return _consumer;
     }
Referenced by arm_compute::graph::bfs(), arm_compute::graph::dfs(), arm_compute::graph::detail::fuse_convolution_with_batch_normalization(), arm_compute::graph::detail::fuse_depthwise_convolution_with_batch_normalization(), arm_compute::graph::detail::fuse_node_with_activation(), and Graph::remove_connection().
consumer_id()
NodeID consumer_id () const inline
Returns sink node id.
Returns
Sink node id
Definition at line 76 of file Edge.h.
     {
         return (_consumer == nullptr) ? EmptyNodeID : _consumer->id();
     }
References arm_compute::graph::EmptyNodeID, and INode::id().
Referenced by Graph::add_connection(), arm_compute::graph::bfs(), arm_compute::graph::dfs(), arm_compute::graph::detail::fuse_convolution_with_batch_normalization(), arm_compute::graph::detail::fuse_depthwise_convolution_with_batch_normalization(), and arm_compute::graph::detail::fuse_node_with_activation().
consumer_idx()
unsigned int consumer_idx () const inline
Returns the index of the input that consumes the result in the consumer node.
Returns
Consumer node input index
Definition at line 108 of file Edge.h.
     {
         return _consumer_idx;
     }
Referenced by Graph::add_connection(), and Graph::remove_connection().
id()
EdgeID id () const inline
Returns edge id.
Returns
Edge id
Definition at line 60 of file Edge.h.
     {
         return _id;
     }
Referenced by Graph::add_connection().
producer()
INode* producer () const inline
Returns producer node.
Returns
Producer node
Definition at line 84 of file Edge.h.
     {
         return _producer;
     }
Referenced by arm_compute::graph::detail::all_inputs_are_visited(), arm_compute::graph::detail::fuse_convolution_with_batch_normalization(), arm_compute::graph::detail::fuse_depthwise_convolution_with_batch_normalization(), arm_compute::graph::detail::fuse_node_with_activation(), InPlaceOperationMutator::mutate(), NodeFusionMutator::mutate(), and Graph::remove_connection().
producer_id()
NodeID producer_id () const inline
Returns producer node id.
Returns
Producer node id
Definition at line 68 of file Edge.h.
     {
         return (_producer == nullptr) ? EmptyNodeID : _producer->id();
     }
References arm_compute::graph::EmptyNodeID, and INode::id().
Referenced by Graph::add_connection(), arm_compute::graph::detail::all_inputs_are_visited(), arm_compute::graph::detail::fuse_convolution_with_batch_normalization(), arm_compute::graph::detail::fuse_depthwise_convolution_with_batch_normalization(), and arm_compute::graph::detail::fuse_node_with_activation().
producer_idx()
unsigned int producer_idx () const inline
Returns the index of the output that produces the result in the producer node.
Returns
Producer node output index
Definition at line 100 of file Edge.h.
     {
         return _producer_idx;
     }
Referenced by Graph::add_connection().
tensor()
Tensor* tensor () const inline
Returns the tensor associated with this edge.
Returns
Tensor id
Definition at line 116 of file Edge.h.
     {
         return _tensor;
     }
Referenced by INode::input(), InPlaceOperationMutator::mutate(), DepthConcatSubTensorMutator::mutate(), Graph::remove_connection(), INode::set_output_tensor(), and Edge::update_bound_tensor().
tensor_id()
TensorID tensor_id () const inline
Returns the tensor id associated with this edge.
Returns
Tensor id
Definition at line 124 of file Edge.h.
     {
         return (_tensor == nullptr) ? NullTensorID : _tensor->id();
     }
References Tensor::id(), and arm_compute::graph::NullTensorID.
Referenced by INode::input_id().
update_bound_tensor()
void update_bound_tensor (Tensor * tensor) inline
Bind the edge to another tensor.
Note
If tensor is nullptr then nothing happens
Parameters
[in] tensor Tensor to bind the edge to
Definition at line 134 of file Edge.h.
     {
         _tensor = (tensor != nullptr) ? tensor : _tensor;
     }
References Edge::tensor().
Friends And Related Function Documentation
Graph
friend class Graph friend
Definition at line 140 of file Edge.h.
The documentation for this class was generated from the following file:
arm_compute/graph/Edge.h