Compute Library: src/core/CL/cl_kernels/histogram.cl File Reference
histogram.cl File Reference
#include "helpers.h"
Macros
#define VATOMIC_INC16(histogram, win_pos)
Functions
__kernel void hist_local_kernel (__global uchar *input_ptr, uint input_stride_x, uint input_step_x, uint input_stride_y, uint input_step_y, uint input_offset_first_element_in_bytes, __local uint *histogram_local, __global uint *restrict histogram, uint num_bins, uint offset, uint range, uint offrange)
Calculate the histogram of an 8 bit grayscale image.
__kernel void hist_border_kernel (__global uchar *input_ptr, uint input_stride_x, uint input_step_x, uint input_stride_y, uint input_step_y, uint input_offset_first_element_in_bytes, __global uint *restrict histogram, uint num_bins, uint offset, uint range, uint offrange)
Calculate the histogram of an 8 bit grayscale image's border.
__kernel void hist_local_kernel_fixed (__global uchar *input_ptr, uint input_stride_x, uint input_step_x, uint input_stride_y, uint input_step_y, uint input_offset_first_element_in_bytes, __local uint *histogram_local, __global uint *restrict histogram)
Calculate the histogram of an 8 bit grayscale image with bin size of 256 and window size of 1.
__kernel void hist_border_kernel_fixed (__global uchar *input_ptr, uint input_stride_x, uint input_step_x, uint input_stride_y, uint input_step_y, uint input_offset_first_element_in_bytes, __global uint *restrict histogram)
Calculate the histogram of an 8 bit grayscale image with bin size as 256 and window size as 1.
Macro Definition Documentation
VATOMIC_INC16
#define VATOMIC_INC16 (histogram, win_pos)
Value:
{                                       \
        atomic_inc(histogram + win_pos.s0); \
        atomic_inc(histogram + win_pos.s1); \
        atomic_inc(histogram + win_pos.s2); \
        atomic_inc(histogram + win_pos.s3); \
        atomic_inc(histogram + win_pos.s4); \
        atomic_inc(histogram + win_pos.s5); \
        atomic_inc(histogram + win_pos.s6); \
        atomic_inc(histogram + win_pos.s7); \
        atomic_inc(histogram + win_pos.s8); \
        atomic_inc(histogram + win_pos.s9); \
        atomic_inc(histogram + win_pos.sa); \
        atomic_inc(histogram + win_pos.sb); \
        atomic_inc(histogram + win_pos.sc); \
        atomic_inc(histogram + win_pos.sd); \
        atomic_inc(histogram + win_pos.se); \
        atomic_inc(histogram + win_pos.sf); \
    }
Definition at line 26 of file histogram.cl.
Function Documentation
hist_border_kernel()
__kernel void hist_border_kernel (__global uchar * input_ptr, uint input_stride_x, uint input_step_x, uint input_stride_y, uint input_step_y, uint input_offset_first_element_in_bytes, __global uint *restrict histogram, uint num_bins, uint offset, uint range, uint offrange)
Calculate the histogram of an 8 bit grayscale image's border.
Each thread will process one pixel using global atomic. When all work items in a work group are done the resulting local histograms are added to the global histogram using global atomics.
Note
The input image is represented as a two-dimensional array of type uchar. The output is represented as a one-dimensional uint array of length of num_bins
Parameters
[in] input_ptr Pointer to the first source image. Supported data types: U8
[in] input_stride_x Stride of the first source image in X dimension (in bytes)
[in] input_step_x input_stride_x * number of elements along X processed per workitem(in bytes)
[in] input_stride_y Stride of the first source image in Y dimension (in bytes)
[in] input_step_y input_stride_y * number of elements along Y processed per workitem(in bytes)
[in] input_offset_first_element_in_bytes The offset of the first element in the first source image
[out] histogram The output buffer to hold histogram final result. Supported data types: U32
[out] num_bins The number of bins
[out] offset The start of values to use (inclusive)
[out] range The range of a bin
[out] offrange The maximum value (exclusive)
Definition at line 141 of file histogram.cl.
 {
     Image input_buffer = CONVERT_TO_IMAGE_STRUCT(input);
     uint val = (uint)(*input_buffer.ptr);
     uint win_pos = (val >= offset) ? (((val - offset) * num_bins) / range) : 0;
     if(val >= offset && (val < offrange))
     {
         atomic_inc(histogram + win_pos);
     }
 }
References CONVERT_TO_IMAGE_STRUCT, arm_compute::test::validation::reference::histogram(), offset(), Image::ptr, and arm_compute::test::validation::reference::range().
hist_border_kernel_fixed()
__kernel void hist_border_kernel_fixed (__global uchar * input_ptr, uint input_stride_x, uint input_step_x, uint input_stride_y, uint input_step_y, uint input_offset_first_element_in_bytes, __global uint *restrict histogram)
Calculate the histogram of an 8 bit grayscale image with bin size as 256 and window size as 1.
Each thread will process one pixel using global atomic. When all work items in a work group are done the resulting local histograms are added to the global histogram using global atomics.
Note
The input image is represented as a two-dimensional array of type uchar. The output is represented as a one-dimensional uint array of 256
Parameters
[in] input_ptr Pointer to the first source image. Supported data types: U8
[in] input_stride_x Stride of the first source image in X dimension (in bytes)
[in] input_step_x input_stride_x * number of elements along X processed per workitem(in bytes)
[in] input_stride_y Stride of the first source image in Y dimension (in bytes)
[in] input_step_y input_stride_y * number of elements along Y processed per workitem(in bytes)
[in] input_offset_first_element_in_bytes The offset of the first element in the first source image
[out] histogram The output buffer to hold histogram final result. Supported data types: U32
Definition at line 238 of file histogram.cl.
 {
     Image input_buffer = CONVERT_TO_IMAGE_STRUCT(input);
     atomic_inc(histogram + *input_buffer.ptr);
 }
References CONVERT_TO_IMAGE_STRUCT, arm_compute::test::validation::reference::histogram(), and Image::ptr.
hist_local_kernel()
__kernel void hist_local_kernel (__global uchar * input_ptr, uint input_stride_x, uint input_step_x, uint input_stride_y, uint input_step_y, uint input_offset_first_element_in_bytes, __local uint * histogram_local, __global uint *restrict histogram, uint num_bins, uint offset, uint range, uint offrange)
Calculate the histogram of an 8 bit grayscale image.
Each thread will process 16 pixels and use one local atomic operation per pixel. When all work items in a work group are done the resulting local histograms are added to the global histogram using global atomics.
Note
The input image is represented as a two-dimensional array of type uchar. The output is represented as a one-dimensional uint array of length of num_bins
Parameters
[in] input_ptr Pointer to the first source image. Supported data types: U8
[in] input_stride_x Stride of the first source image in X dimension (in bytes)
[in] input_step_x input_stride_x * number of elements along X processed per workitem(in bytes)
[in] input_stride_y Stride of the first source image in Y dimension (in bytes)
[in] input_step_y input_stride_y * number of elements along Y processed per workitem(in bytes)
[in] input_offset_first_element_in_bytes The offset of the first element in the first source image
[in] histogram_local The local buffer to hold histogram result in per workgroup. Supported data types: U32
[out] histogram The output buffer to hold histogram final result. Supported data types: U32
[out] num_bins The number of bins
[out] offset The start of values to use (inclusive)
[out] range The range of a bin
[out] offrange The maximum value (exclusive)
Definition at line 68 of file histogram.cl.
 {
     Image input_buffer = CONVERT_TO_IMAGE_STRUCT(input);
     uint  local_id_x   = get_local_id(0);
     uint local_x_size = get_local_size(0);
     if(num_bins > local_x_size)
     {
         for(int i = local_id_x; i < num_bins; i += local_x_size)
         {
             histogram_local[i] = 0;
         }
     }
     else
     {
         if(local_id_x <= num_bins)
         {
             histogram_local[local_id_x] = 0;
         }
     }
     uint16 vals = convert_uint16(vload16(0, input_buffer.ptr));
     uint16 win_pos = select(num_bins, ((vals - offset) * num_bins) / range, (vals >= offset && vals < offrange));
     barrier(CLK_LOCAL_MEM_FENCE);
     VATOMIC_INC16(histogram_local, win_pos);
     barrier(CLK_LOCAL_MEM_FENCE);
     if(num_bins > local_x_size)
     {
         for(int i = local_id_x; i < num_bins; i += local_x_size)
         {
             atomic_add(histogram + i, histogram_local[i]);
         }
     }
     else
     {
         if(local_id_x <= num_bins)
         {
             atomic_add(histogram + local_id_x, histogram_local[local_id_x]);
         }
     }
 }
References CONVERT_TO_IMAGE_STRUCT, arm_compute::test::validation::reference::histogram(), local_x_size, offset(), Image::ptr, arm_compute::test::validation::reference::range(), arm_compute::test::validation::select, and VATOMIC_INC16.
hist_local_kernel_fixed()
__kernel void hist_local_kernel_fixed (__global uchar * input_ptr, uint input_stride_x, uint input_step_x, uint input_stride_y, uint input_step_y, uint input_offset_first_element_in_bytes, __local uint * histogram_local, __global uint *restrict histogram)
Calculate the histogram of an 8 bit grayscale image with bin size of 256 and window size of 1.
Each thread will process 16 pixels and use one local atomic operation per pixel. When all work items in a work group are done the resulting local histograms are added to the global histogram using global atomics.
Note
The input image is represented as a two-dimensional array of type uchar. The output is represented as a one-dimensional uint array of 256 elements
Parameters
[in] input_ptr Pointer to the first source image. Supported data types: U8
[in] input_stride_x Stride of the first source image in X dimension (in bytes)
[in] input_step_x input_stride_x * number of elements along X processed per workitem(in bytes)
[in] input_stride_y Stride of the first source image in Y dimension (in bytes)
[in] input_step_y input_stride_y * number of elements along Y processed per workitem(in bytes)
[in] input_offset_first_element_in_bytes The offset of the first element in the first source image
[in] histogram_local The local buffer to hold histogram result in per workgroup. Supported data types: U32
[out] histogram The output buffer to hold histogram final result. Supported data types: U32
Definition at line 178 of file histogram.cl.
 {
     Image input_buffer = CONVERT_TO_IMAGE_STRUCT(input);
     uint local_index  = get_local_id(0);
     uint local_x_size = get_local_size(0);
     for(int i = local_index; i < 256; i += local_x_size)
     {
         histogram_local[i] = 0;
     }
     uint16 vals = convert_uint16(vload16(0, input_buffer.ptr));
     barrier(CLK_LOCAL_MEM_FENCE);
     atomic_inc(histogram_local + vals.s0);
     atomic_inc(histogram_local + vals.s1);
     atomic_inc(histogram_local + vals.s2);
     atomic_inc(histogram_local + vals.s3);
     atomic_inc(histogram_local + vals.s4);
     atomic_inc(histogram_local + vals.s5);
     atomic_inc(histogram_local + vals.s6);
     atomic_inc(histogram_local + vals.s7);
     atomic_inc(histogram_local + vals.s8);
     atomic_inc(histogram_local + vals.s9);
     atomic_inc(histogram_local + vals.sa);
     atomic_inc(histogram_local + vals.sb);
     atomic_inc(histogram_local + vals.sc);
     atomic_inc(histogram_local + vals.sd);
     atomic_inc(histogram_local + vals.se);
     atomic_inc(histogram_local + vals.sf);
     barrier(CLK_LOCAL_MEM_FENCE);
     for(int i = local_index; i < 256; i += local_x_size)
     {
         atomic_add(histogram + i, histogram_local[i]);
     }
 }
References CONVERT_TO_IMAGE_STRUCT, arm_compute::test::validation::reference::histogram(), local_x_size, and Image::ptr.