Compute Library: src/core/CL/cl_kernels/l2_normalize.cl File Reference
l2_normalize.cl File Reference
#include "helpers.h"
Functions
__kernel void l2_normalize_x (__global uchar *src_ptr, uint src_stride_x, uint src_step_x, uint src_stride_y, uint src_step_y, uint src_offset_first_element_in_bytes, __global uchar *sum_ptr, uint sum_stride_x, uint sum_step_x, uint sum_stride_y, uint sum_step_y, uint sum_offset_first_element_in_bytes, __global uchar *dst_ptr, uint dst_stride_x, uint dst_step_x, uint dst_stride_y, uint dst_step_y, uint dst_offset_first_element_in_bytes, DATA_TYPE epsilon)
This kernel performs l2 normalization on x-axis.
__kernel void l2_normalize_y (__global uchar *src_ptr, uint src_stride_x, uint src_step_x, uint src_stride_y, uint src_step_y, uint src_offset_first_element_in_bytes, __global uchar *sum_ptr, uint sum_stride_x, uint sum_step_x, uint sum_stride_y, uint sum_step_y, uint sum_offset_first_element_in_bytes, __global uchar *dst_ptr, uint dst_stride_x, uint dst_step_x, uint dst_stride_y, uint dst_step_y, uint dst_offset_first_element_in_bytes, DATA_TYPE epsilon)
This kernel performs l2 normalization on y-axis.
__kernel void l2_normalize_z (__global uchar *src_ptr, uint src_stride_x, uint src_step_x, uint src_stride_y, uint src_step_y, uint src_stride_z, uint src_step_z, uint src_offset_first_element_in_bytes, __global uchar *sum_ptr, uint sum_stride_x, uint sum_step_x, uint sum_stride_y, uint sum_step_y, uint sum_stride_z, uint sum_step_z, uint sum_offset_first_element_in_bytes, __global uchar *dst_ptr, uint dst_stride_x, uint dst_step_x, uint dst_stride_y, uint dst_step_y, uint dst_stride_z, uint dst_step_z, uint dst_offset_first_element_in_bytes, DATA_TYPE epsilon)
This kernel performs l2 normalization on z-axis.
Function Documentation
l2_normalize_x()
__kernel void l2_normalize_x (__global uchar * src_ptr, uint src_stride_x, uint src_step_x, uint src_stride_y, uint src_step_y, uint src_offset_first_element_in_bytes, __global uchar * sum_ptr, uint sum_stride_x, uint sum_step_x, uint sum_stride_y, uint sum_step_y, uint sum_offset_first_element_in_bytes, __global uchar * dst_ptr, uint dst_stride_x, uint dst_step_x, uint dst_stride_y, uint dst_step_y, uint dst_offset_first_element_in_bytes, DATA_TYPE epsilon)
This kernel performs l2 normalization on x-axis.
Note
The data type must be passed at compile time using -DDATA_TYPE: e.g. -DDATA_TYPE=float
The data size must be passed at compile time using -DDATA_SIZE e.g. -DDATA_SIZE=32
Parameters
[in] src_ptr Pointer to the source tensor. Supported data types: F16/F32
[in] src_stride_x Stride of the source tensor in X dimension (in bytes)
[in] src_step_x src_stride_x * number of elements along X processed per workitem(in bytes)
[in] src_stride_y Stride of the source tensor in Y dimension (in bytes)
[in] src_step_y src_stride_y * number of elements along X processed per workitem(in bytes)
[in] src_offset_first_element_in_bytes The offset of the first element in the source tensor
[in] sum_ptr Pointer to the source tensor. Supported data types: F16/F32
[in] sum_stride_x Stride of the source tensor in X dimension (in bytes)
[in] sum_step_x sum_stride_x * number of elements along X processed per workitem(in bytes)
[in] sum_stride_y Stride of the source tensor in Y dimension (in bytes)
[in] sum_step_y sum_stride_y * number of elements along Y processed per workitem(in bytes)
[in] sum_offset_first_element_in_bytes The offset of the first element in the source tensor
[out] dst_ptr Pointer to the destination tensor. Supported data types: same as src_ptr
[in] dst_stride_x Stride of the destination tensor in X dimension (in bytes)
[in] dst_step_x dst_stride_x * number of elements along X processed per workitem(in bytes)
[in] dst_stride_y Stride of the destination tensor in Y dimension (in bytes)
[in] dst_step_y dst_stride_y * number of elements along Y processed per workitem(in bytes)
[in] dst_offset_first_element_in_bytes The offset of the first element in the destination tensor
[in] epsilon Epsilon value
Definition at line 51 of file l2_normalize.cl.
 {
     Image src = CONVERT_TO_IMAGE_STRUCT(src);
     Image sum = CONVERT_TO_IMAGE_STRUCT(sum);
     Image dst = CONVERT_TO_IMAGE_STRUCT(dst);
     VEC_DATA_TYPE(DATA_TYPE, 16)
     in = vload16(0, (__global DATA_TYPE *)src.ptr);
     VEC_DATA_TYPE(DATA_TYPE, 16)
     normalize_value = (VEC_DATA_TYPE(DATA_TYPE, 16))rsqrt(fmax(((__global DATA_TYPE *)sum.ptr)[0], epsilon));
     vstore16(in * normalize_value, 0, (__global DATA_TYPE *)dst.ptr);
 }
References CONVERT_TO_IMAGE_STRUCT, DATA_TYPE, arm_compute::test::validation::dst, epsilon, arm_compute::test::validation::src, sum(), and VEC_DATA_TYPE.
l2_normalize_y()
__kernel void l2_normalize_y (__global uchar * src_ptr, uint src_stride_x, uint src_step_x, uint src_stride_y, uint src_step_y, uint src_offset_first_element_in_bytes, __global uchar * sum_ptr, uint sum_stride_x, uint sum_step_x, uint sum_stride_y, uint sum_step_y, uint sum_offset_first_element_in_bytes, __global uchar * dst_ptr, uint dst_stride_x, uint dst_step_x, uint dst_stride_y, uint dst_step_y, uint dst_offset_first_element_in_bytes, DATA_TYPE epsilon)
This kernel performs l2 normalization on y-axis.
Note
The data type must be passed at compile time using -DDATA_TYPE: e.g. -DDATA_TYPE=float
The data size must be passed at compile time using -DDATA_SIZE e.g. -DDATA_SIZE=32
Parameters
[in] src_ptr Pointer to the source tensor. Supported data types: F16/F32
[in] src_stride_x Stride of the source tensor in X dimension (in bytes)
[in] src_step_x src_stride_x * number of elements along Y processed per workitem(in bytes)
[in] src_stride_y Stride of the source tensor in Y dimension (in bytes)
[in] src_step_y src_stride_y * number of elements along X processed per workitem(in bytes)
[in] src_offset_first_element_in_bytes The offset of the first element in the source tensor
[in] sum_ptr Pointer to the source tensor. Supported data types: F16/F32
[in] sum_stride_x Stride of the source tensor in X dimension (in bytes)
[in] sum_step_x sum_stride_x * number of elements along X processed per workitem(in bytes)
[in] sum_stride_y Stride of the source tensor in Y dimension (in bytes)
[in] sum_step_y sum_stride_y * number of elements along Y processed per workitem(in bytes)
[in] sum_offset_first_element_in_bytes The offset of the first element in the source tensor
[out] dst_ptr Pointer to the destination tensor. Supported data types: same as src_ptr
[in] dst_stride_x Stride of the destination tensor in X dimension (in bytes)
[in] dst_step_x dst_stride_x * number of elements along X processed per workitem(in bytes)
[in] dst_stride_y Stride of the destination tensor in Y dimension (in bytes)
[in] dst_step_y dst_stride_y * number of elements along Y processed per workitem(in bytes)
[in] dst_offset_first_element_in_bytes The offset of the first element in the destination tensor
[in] epsilon Epsilon value
Definition at line 94 of file l2_normalize.cl.
 {
     Image src = CONVERT_TO_IMAGE_STRUCT(src);
     Image sum = CONVERT_TO_IMAGE_STRUCT(sum);
     Image dst = CONVERT_TO_IMAGE_STRUCT(dst);
     VEC_DATA_TYPE(DATA_TYPE, 16)
     in = vload16(0, (__global DATA_TYPE *)src.ptr);
     VEC_DATA_TYPE(DATA_TYPE, 16)
     sums = vload16(0, (__global DATA_TYPE *)sum.ptr);
     VEC_DATA_TYPE(DATA_TYPE, 16)
     normalize_value = (VEC_DATA_TYPE(DATA_TYPE, 16))rsqrt(fmax(sums, epsilon));
     vstore16(in * normalize_value, 0, (__global DATA_TYPE *)dst.ptr);
 }
References CONVERT_TO_IMAGE_STRUCT, DATA_TYPE, arm_compute::test::validation::dst, epsilon, arm_compute::test::validation::src, sum(), and VEC_DATA_TYPE.
l2_normalize_z()
__kernel void l2_normalize_z (__global uchar * src_ptr, uint src_stride_x, uint src_step_x, uint src_stride_y, uint src_step_y, uint src_stride_z, uint src_step_z, uint src_offset_first_element_in_bytes, __global uchar * sum_ptr, uint sum_stride_x, uint sum_step_x, uint sum_stride_y, uint sum_step_y, uint sum_stride_z, uint sum_step_z, uint sum_offset_first_element_in_bytes, __global uchar * dst_ptr, uint dst_stride_x, uint dst_step_x, uint dst_stride_y, uint dst_step_y, uint dst_stride_z, uint dst_step_z, uint dst_offset_first_element_in_bytes, DATA_TYPE epsilon)
This kernel performs l2 normalization on z-axis.
Note
The data type must be passed at compile time using -DDATA_TYPE: e.g. -DDATA_TYPE=float
The data size must be passed at compile time using -DDATA_SIZE e.g. -DDATA_SIZE=32
Parameters
[in] src_ptr Pointer to the source tensor. Supported data types: F16/F32
[in] src_stride_x Stride of the source tensor in X dimension (in bytes)
[in] src_step_x src_stride_x * number of elements along Y processed per workitem(in bytes)
[in] src_stride_y Stride of the source tensor in Y dimension (in bytes)
[in] src_step_y src_stride_y * number of elements along X processed per workitem(in bytes)
[in] src_stride_z Stride of the source tensor in Z dimension (in bytes)
[in] src_step_z src_stride_z * number of elements along Z processed per workitem(in bytes)
[in] src_offset_first_element_in_bytes The offset of the first element in the source tensor
[in] sum_ptr Pointer to the source tensor. Supported data types: F16/F32
[in] sum_stride_x Stride of the source tensor in X dimension (in bytes)
[in] sum_step_x sum_stride_x * number of elements along X processed per workitem(in bytes)
[in] sum_stride_y Stride of the source tensor in Y dimension (in bytes)
[in] sum_step_y sum_stride_y * number of elements along Y processed per workitem(in bytes)
[in] sum_stride_z Stride of the source tensor in Z dimension (in bytes)
[in] sum_step_z sum_stride_z * number of elements along Z processed per workitem(in bytes)
[in] sum_offset_first_element_in_bytes The offset of the first element in the source tensor
[out] dst_ptr Pointer to the destination tensor. Supported data types: same as src_ptr
[in] dst_stride_x Stride of the destination tensor in X dimension (in bytes)
[in] dst_step_x dst_stride_x * number of elements along X processed per workitem(in bytes)
[in] dst_stride_y Stride of the destination tensor in Y dimension (in bytes)
[in] dst_step_y dst_stride_y * number of elements along Y processed per workitem(in bytes)
[in] dst_stride_z Stride of the destination tensor in Z dimension (in bytes)
[in] dst_step_z dst_stride_z * number of elements along Y processed per workitem(in bytes)
[in] dst_offset_first_element_in_bytes The offset of the first element in the destination tensor
[in] epsilon Epsilon value
Definition at line 145 of file l2_normalize.cl.
 {
     Tensor3D src = CONVERT_TO_TENSOR3D_STRUCT(src);
     Tensor3D sum = CONVERT_TO_TENSOR3D_STRUCT(sum);
     Tensor3D dst = CONVERT_TO_TENSOR3D_STRUCT(dst);
     VEC_DATA_TYPE(DATA_TYPE, 16)
     in = vload16(0, (__global DATA_TYPE *)src.ptr);
     VEC_DATA_TYPE(DATA_TYPE, 16)
     sums = vload16(0, (__global DATA_TYPE *)sum.ptr);
     VEC_DATA_TYPE(DATA_TYPE, 16)
     normalize_value = (VEC_DATA_TYPE(DATA_TYPE, 16))rsqrt(fmax(sums, epsilon));
     vstore16(in * normalize_value, 0, (__global DATA_TYPE *)dst.ptr);
 }
References CONVERT_TO_TENSOR3D_STRUCT, DATA_TYPE, arm_compute::test::validation::dst, epsilon, arm_compute::test::validation::src, sum(), and VEC_DATA_TYPE.