Compute Library: arm_compute::helpers::fft Namespace Reference
arm_compute::helpers::fft Namespace Reference
Functions
std::vector< unsigned int > decompose_stages (unsigned int N, const std::set< unsigned int > &supported_factors)
Decompose a given 1D input size using the provided supported factors.
std::vector< unsigned int > digit_reverse_indices (unsigned int N, const std::vector< unsigned int > &fft_stages)
Calculate digit reverse index vector given fft size and the decomposed stages.
Function Documentation
decompose_stages()
std::vector< unsigned int > decompose_stages (unsigned int N, const std::set< unsigned int > & supported_factors)
Decompose a given 1D input size using the provided supported factors.
Parameters
[in] N Input size to be decomposed.
[in] supported_factors Supported factors that can be used for decomposition.
Returns
A vector with the stages of the decomposition. Will be empty if decomposition failed.
Definition at line 34 of file fft.cpp.
 {
     std::vector<unsigned int> stages;
     unsigned int              res = N;
     // Early exit if no supported factors are provided
     if(supported_factors.empty())
     {
         return stages;
     }
     // Create reverse iterator (Start decomposing from the larger supported factors)
     auto rfactor_it = supported_factors.rbegin();
     // Decomposition step
     while(res != 0)
     {
         const unsigned int factor = *rfactor_it;
         if(0 == (res % factor) && res >= factor)
         {
             stages.push_back(factor);
             res /= factor;
         }
         else
         {
             ++rfactor_it;
             if(rfactor_it == supported_factors.rend())
             {
                 if(res > 1)
                 {
                     // Couldn't decompose with given factors
                     stages.clear();
                     return stages;
                 }
                 else
                 {
                     res = 0;
                 }
             }
         }
     }
     return stages;
 }
Referenced by CLFFT1D::configure(), NEFFT1D::configure(), CLFFT1D::validate(), and NEFFT1D::validate().
digit_reverse_indices()
std::vector< unsigned int > digit_reverse_indices (unsigned int N, const std::vector< unsigned int > & fft_stages)
Calculate digit reverse index vector given fft size and the decomposed stages.
Parameters
N Input size to calculate digit reverse for
fft_stages A vector with the FFT decomposed stages
Returns
A vector with the digit reverse indices. Will be empty if it failed.
Definition at line 79 of file fft.cpp.
 {
     std::vector<unsigned int> idx_digit_reverse;
     // Early exit in case N and fft stages do not match
     const float stages_prod = std::accumulate(std::begin(fft_stages), std::end(fft_stages), 1, std::multiplies<unsigned int>());
     if(stages_prod != N)
     {
         return idx_digit_reverse;
     }
     // Resize digit reverse vector
     idx_digit_reverse.resize(N);
     // Get number of radix stages
     unsigned int n_stages = fft_stages.size();
     // Scan elements
     for(unsigned int n = 0; n < N; ++n)
     {
         unsigned int k  = n;
         unsigned int Nx = fft_stages[0];
         // Scan stages
         for(unsigned int s = 1; s < n_stages; ++s)
         {
             // radix of stage i-th
             unsigned int Ny = fft_stages[s];
             unsigned int Ni = Ny * Nx;
             // Update k index
             k = (k * Ny) % Ni + (k / Nx) % Ny + Ni * (k / Ni);
             // Update Nx
             Nx *= Ny;
         }
         // K is the index of digit-reverse
         idx_digit_reverse[n] = k;
     }
     return idx_digit_reverse;
 }
References accumulate().
Referenced by CLFFT1D::configure(), and NEFFT1D::configure().