Compute Library: arm_compute::helpers::float_ops Namespace Reference
arm_compute::helpers::float_ops Namespace Reference
Data Structures
union RawFloat
Functions
bool is_equal_ulps (float a, float b, int max_allowed_ulps=0)
Checks if two floating point numbers are equal given an allowed number of ULPs.
bool is_one (float a, float epsilon=0.00001f)
Checks if the input floating point number is 1.0f checking if the difference is within a range defined with epsilon.
bool is_zero (float a, float epsilon=0.00001f)
Checks if the input floating point number is 0.0f checking if the difference is within a range defined with epsilon.
Function Documentation
is_equal_ulps()
bool arm_compute::helpers::float_ops::is_equal_ulps (float a, float b, int max_allowed_ulps = 0) inline
Checks if two floating point numbers are equal given an allowed number of ULPs.
Parameters
[in] a First number to compare
[in] b Second number to compare
[in] max_allowed_ulps (Optional) Number of allowed ULPs
Returns
True if number is close else false
Definition at line 80 of file float_ops.h.
 {
     RawFloat ra(a);
     RawFloat rb(b);
     // Check ULP distance
     const int ulps = std::abs(ra.i32 - rb.i32);
     return ulps <= max_allowed_ulps;
 }
References arm_compute::test::validation::b, and RawFloat::i32.
is_one()
bool arm_compute::helpers::float_ops::is_one (float a, float epsilon = 0.00001f) inline
Checks if the input floating point number is 1.0f checking if the difference is within a range defined with epsilon.
Parameters
[in] a Input floating point number
[in] epsilon (Optional) Epsilon used to define the error bounds
Returns
True if number is close to 1.0f
Definition at line 97 of file float_ops.h.
 {
     return std::abs(1.0f - a) <= epsilon;
 }
References epsilon.
Referenced by CLGEMMMatrixMultiplyNativeKernel::configure(), CLGEMMMatrixMultiplyReshapedOnlyRHSKernel::configure(), CLGEMMMatrixMultiplyKernel::configure(), CLGEMMMatrixMultiplyReshapedKernel::configure(), and NEGEMMMatrixMultiplyKernel::run().
is_zero()
bool arm_compute::helpers::float_ops::is_zero (float a, float epsilon = 0.00001f) inline
Checks if the input floating point number is 0.0f checking if the difference is within a range defined with epsilon.
Parameters
[in] a Input floating point number
[in] epsilon (Optional) Epsilon used to define the error bounds
Returns
True if number is close to 0.0f
Definition at line 109 of file float_ops.h.
 {
     return std::abs(0.0f - a) <= epsilon;
 }
References epsilon.
Referenced by CLGEMMMatrixMultiplyNativeKernel::configure(), CLGEMMMatrixMultiplyReshapedOnlyRHSKernel::configure(), CLGEMMMatrixMultiplyKernel::configure(), CLGEMMMatrixMultiplyReshapedKernel::configure(), CLGEMM::configure(), and CLGEMM::validate().