var searchData=
[
  ['macros_2eh',['Macros.h',['../arm__compute_2core_2utils_2logging_2_macros_8h.xhtml',1,'(Global Namespace)'],['../arm__compute_2core_2utils_2misc_2_macros_8h.xhtml',1,'(Global Namespace)'],['../src_2common_2utils_2_macros_8h.xhtml',1,'(Global Namespace)'],['../src_2core_2common_2_macros_8h.xhtml',1,'(Global Namespace)'],['../tests_2framework_2_macros_8h.xhtml',1,'(Global Namespace)']]],
  ['main_2ecpp',['main.cpp',['../main_8cpp.xhtml',1,'']]],
  ['malicounter_2ecpp',['MaliCounter.cpp',['../_mali_counter_8cpp.xhtml',1,'']]],
  ['malicounter_2eh',['MaliCounter.h',['../_mali_counter_8h.xhtml',1,'']]],
  ['mat_5fmul_2ecl',['mat_mul.cl',['../mat__mul_8cl.xhtml',1,'']]],
  ['mat_5fmul_5fquantized_2ecl',['mat_mul_quantized.cl',['../mat__mul__quantized_8cl.xhtml',1,'']]],
  ['matmul_2ecpp',['MatMul.cpp',['../_c_l_2_mat_mul_8cpp.xhtml',1,'(Global Namespace)'],['../_n_e_o_n_2_mat_mul_8cpp.xhtml',1,'(Global Namespace)']]],
  ['matmulkernel_2ecpp',['MatMulKernel.cpp',['../_mat_mul_kernel_8cpp.xhtml',1,'']]],
  ['matmullowpnativekernel_2ecpp',['MatMulLowpNativeKernel.cpp',['../_mat_mul_lowp_native_kernel_8cpp.xhtml',1,'']]],
  ['max_2eh',['max.h',['../max_8h.xhtml',1,'']]],
  ['maxunpoolinglayer_2ecpp',['MaxUnpoolingLayer.cpp',['../_c_l_2_max_unpooling_layer_8cpp.xhtml',1,'(Global Namespace)'],['../_n_e_o_n_2_max_unpooling_layer_8cpp.xhtml',1,'(Global Namespace)'],['../reference_2_max_unpooling_layer_8cpp.xhtml',1,'(Global Namespace)']]],
  ['maxunpoolinglayer_2eh',['MaxUnpoolingLayer.h',['../_max_unpooling_layer_8h.xhtml',1,'']]],
  ['mean_5fstddev_5fnormalization_2ecl',['mean_stddev_normalization.cl',['../mean__stddev__normalization_8cl.xhtml',1,'']]],
  ['meanstddev_2ecpp',['MeanStdDev.cpp',['../_mean_std_dev_8cpp.xhtml',1,'']]],
  ['meanstddev_2eh',['MeanStdDev.h',['../_mean_std_dev_8h.xhtml',1,'']]],
  ['meanstddevnormalizationlayer_2ecpp',['MeanStdDevNormalizationLayer.cpp',['../_c_l_2_mean_std_dev_normalization_layer_8cpp.xhtml',1,'(Global Namespace)'],['../_n_e_o_n_2_mean_std_dev_normalization_layer_8cpp.xhtml',1,'(Global Namespace)'],['../reference_2_mean_std_dev_normalization_layer_8cpp.xhtml',1,'(Global Namespace)']]],
  ['meanstddevnormalizationlayer_2eh',['MeanStdDevNormalizationLayer.h',['../_mean_std_dev_normalization_layer_8h.xhtml',1,'']]],
  ['measurement_2eh',['Measurement.h',['../_measurement_8h.xhtml',1,'']]],
  ['memory_2ecpp',['Memory.cpp',['../_memory_8cpp.xhtml',1,'']]],
  ['memory_2eh',['Memory.h',['../_memory_8h.xhtml',1,'']]],
  ['memorydescriptor_2eh',['MemoryDescriptor.h',['../_memory_descriptor_8h.xhtml',1,'']]],
  ['memorygroup_2eh',['MemoryGroup.h',['../_memory_group_8h.xhtml',1,'']]],
  ['memoryhelpers_2eh',['MemoryHelpers.h',['../_memory_helpers_8h.xhtml',1,'']]],
  ['memorymanager_2ecpp',['MemoryManager.cpp',['../_c_l_2_u_n_i_t_2_memory_manager_8cpp.xhtml',1,'(Global Namespace)'],['../_n_e_o_n_2_u_n_i_t_2_memory_manager_8cpp.xhtml',1,'(Global Namespace)']]],
  ['memorymanagerondemand_2ecpp',['MemoryManagerOnDemand.cpp',['../_memory_manager_on_demand_8cpp.xhtml',1,'']]],
  ['memorymanagerondemand_2eh',['MemoryManagerOnDemand.h',['../_memory_manager_on_demand_8h.xhtml',1,'']]],
  ['memoryregion_2eh',['MemoryRegion.h',['../_memory_region_8h.xhtml',1,'']]],
  ['memset_2ecl',['memset.cl',['../memset_8cl.xhtml',1,'']]],
  ['mergeresults_2dfp16_2ecpp',['mergeresults-fp16.cpp',['../mergeresults-fp16_8cpp.xhtml',1,'']]],
  ['mergeresults_2dsve_2ecpp',['mergeresults-sve.cpp',['../mergeresults-sve_8cpp.xhtml',1,'']]],
  ['mergeresults_2ecpp',['mergeresults.cpp',['../mergeresults_8cpp.xhtml',1,'']]],
  ['mergeresults_2ehpp',['mergeresults.hpp',['../mergeresults_8hpp.xhtml',1,'']]],
  ['min_2eh',['min.h',['../min_8h.xhtml',1,'']]],
  ['minmax_5flayer_2ecl',['minmax_layer.cl',['../minmax__layer_8cl.xhtml',1,'']]],
  ['minmaxlocation_2ecpp',['MinMaxLocation.cpp',['../_min_max_location_8cpp.xhtml',1,'']]],
  ['minmaxlocation_2eh',['MinMaxLocation.h',['../_min_max_location_8h.xhtml',1,'']]],
  ['misc_2dsve_2ecpp',['misc-sve.cpp',['../misc-sve_8cpp.xhtml',1,'']]],
  ['misc_2ecpp',['misc.cpp',['../misc_8cpp.xhtml',1,'']]],
  ['mla_2eh',['mla.h',['../mla_8h.xhtml',1,'']]],
  ['mlgoheuristics_2ecpp',['MLGOHeuristics.cpp',['../src_2runtime_2_c_l_2mlgo_2_m_l_g_o_heuristics_8cpp.xhtml',1,'(Global Namespace)'],['../tests_2validation_2_c_l_2_u_n_i_t_2_m_l_g_o_heuristics_8cpp.xhtml',1,'(Global Namespace)']]],
  ['mlgoheuristics_2eh',['MLGOHeuristics.h',['../_m_l_g_o_heuristics_8h.xhtml',1,'']]],
  ['mlgoparser_2ecpp',['MLGOParser.cpp',['../_m_l_g_o_parser_8cpp.xhtml',1,'']]],
  ['mlgoparser_2eh',['MLGOParser.h',['../_m_l_g_o_parser_8h.xhtml',1,'']]],
  ['mmappedfile_2ecpp',['MMappedFile.cpp',['../_m_mapped_file_8cpp.xhtml',1,'']]],
  ['mmappedfile_2eh',['MMappedFile.h',['../_m_mapped_file_8h.xhtml',1,'']]],
  ['movl_2eh',['movl.h',['../movl_8h.xhtml',1,'']]],
  ['movn_2eh',['movn.h',['../movn_8h.xhtml',1,'']]],
  ['mul_2ecpp',['Mul.cpp',['../_mul_8cpp.xhtml',1,'']]],
  ['mul_2eh',['mul.h',['../mul_8h.xhtml',1,'']]],
  ['multithreaded_2ecpp',['Multithreaded.cpp',['../_multithreaded_8cpp.xhtml',1,'']]],
  ['mutatorutils_2ecpp',['MutatorUtils.cpp',['../_mutator_utils_8cpp.xhtml',1,'']]],
  ['mutatorutils_2eh',['MutatorUtils.h',['../_mutator_utils_8h.xhtml',1,'']]],
  ['mutex_2eh',['Mutex.h',['../_mutex_8h.xhtml',1,'']]]
];
